### ISSUE TITLE
Some NPCs cannot be interacted with

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#10]
Right clicking on some NPCs does not cause an interaction. NPCs so far I have found:
Rally master, The forces of Order/Destruction Guild NPC, Healer, Herald. All are within the Warcamp in Nordland.int
![npcs not interactive](https://cloud.githubusercontent.com/assets/7492543/2882578/46bb3362-d490-11e3-9900-3be1263d9d3f.png)

**Comment by MaxHayman** [comment]
This is a bit vague and most issues with it is fixed.
