### ISSUE TITLE
Tok order side chapter 21 high elf "buying time" 2 item are missing in basic influence reward and 1 item in advance influence reward

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#10004]
Tok order side chapter 21 high elf "the call of time" 2 item are missing in basic influence reward and 1 item in advance influence reward

The reward should be the choice between 2 potions for basic influence reward

for advance reward don't know what kind of item.. may be shoulder

**Comment by Lheana** [comment]
Duplicate of #7270
