### ISSUE TITLE
[Talabecland] [Empire] Chapter 13 Influence Reward Helm Icon Wrong

### ISSUE THREAD

**Issue by BastionWAR** [WarEmu/WarBugs#10013]
Item icon looks like gloves in a helm item. The potions are from level 10 min and 35 max in a 26 chapter level, but maybe this is correct.

![thyrom_007](https://user-images.githubusercontent.com/30054005/28479529-0d399d62-6e5d-11e7-84fd-d2e326c526b0.jpg)

**Comment by Razielhell** [comment]
Can't do anything about potions yet. Fixed the icon.
