### ISSUE TITLE
Career mastery point bug MEGATHREAD

### ISSUE THREAD

**Issue by Zzeppenn** [WarEmu/WarBugs#1001]
Certain careers' mastery points DO NOT increase the damage dealt / effect of the abilities related to that mastery path.

- Black Orc: Path of Da' Brawler; Path of Da' Boss
- Squig Herder: Path of Quick Shootin'

I'm sorry about making a new thread, since I've already made one about the Squig Herder before, but it seems that more careers' mastery trees have this problem.
So I kindly ask everybody who can afford respeccing a couple of times to check if their characters' masteries are affected by the bug or not - order and destruction alike - and report the results here.

**Comment by Silentguard** [comment]
can you check this is only tooltip bug or really not increases abilities damage?

**Comment by Zzeppenn** [comment]
I did check it already, forgot to mention it, and no, unfortunately it is not just the tooltip, there is effectively no damage increase for those abilities.

Tested with SH, Path of QS, 4 abilities: Yer Bleedin', Stop Runnin', Run 'n' Shoot and Not So Fast.
Tested it separately after every mastery point learned. 
I checked the Long Shootin' tree for SH and it worked perfectly, so the bug affects only certain mastery trees, not all of the careers' abilities.

**Comment by Zzeppenn** [comment]
After 3 days I spent my mastery points in Quick Shootin' again and now it worked perfectly.
When it bugged for the first time, I waited 10 minutes and then relogged, and it still persisted. Now it works normally.

It still affects my Black Orc's Path of Da' Brawler, Path of Da' Boss though, so I have no clue what's going on, or if it's happening on to me. I will wait a few days and then respec with my BO.

**Comment by Zealote** [comment]
There might be something off with BO's mastery anyway: with no mastery points spent, the WS buff/debuff and tough buff on mine (lvl 18, unbolstered) are giving +/- 54 stat points (in tooltip and, at least for the buffs, in stat window), whereas I believe it should be a base +/-45.

At 4 mastery levels, none of the numbers changed in terms of neither damage or (de)buff values, but the Da Toughest! war bellow's +wounds proc increased by 4 (from 20 originally).

Given Zzeppenn's last post, I'll try again in a coupla days and see if it changes. Might be helpful if a lvl 20 could try as well just in case my being lvl 18 is messing it up somehow.

**Comment by Zzeppenn** [comment]
Zealote, current rank doesn't seem to be relevant, I repsecced my chars when they were 20.

Things is, I deleted that BO and brought another one up to lvl 20, and this one's masteries points are bugged as well. I just can't find any pattern, or cause of occurance.

On a sidenote, I removed my mastery points with that SH first, before waiting for it to work for 3 days. I didn't know it'd be fixed. Just plain random.

**Comment by knezekj** [comment]
Hi i have slayer lvl 17 i have spend 4 mastery points and nothing done. Not increase of abillities and no new tactics

**Comment by Zzeppenn** [comment]
Knezekj, you'll have to spend another point at lvl 19 to get the tactic itself (click on the tactic's icon, you won't earn every ability/tactic automatically in a mastery tree once you reach it's level with basic mastery points, you'll always have to spend another point for them).
So far tactics always worked, they could be learned, but the mastery points do not increase ability damage/effect.

**Comment by knezekj** [comment]
So if i understand i must be on lvl 19 when tactics start be functional? Because i have spend 4 points in mastery tree so there is first tactic available on this tree but i haven´t it there in my abillities/tactics.

and sorry for my bad English i am from czech rebuplic so English is not my first language.

**Comment by knezekj** [comment]
thanks its founctional pretty well

**Comment by Zzeppenn** [comment]
You are welcome Knezekj^

Black Orc mastery points still provide no bonus for me.

**Comment by SiegeOrk** [comment]
I was specced Da Boss, and tested Follow me Lead before and after respeccing. The damage stayed exactly the same. The mastery points have no effect at least on the Da Boss path.

**Comment by Evildoor** [comment]
Seems to be fixed. I have not tried respeccing yet, but now, with 4 points in Da Boss, Follow me Lead deals more damage than Trip Em Up (they do same damage if same level, and did same damage before patch even with 4 points), both in tooltip and in combat.
