### ISSUE TITLE
[Talabecland] [Empire] Chapter 13 PQ "Wagon Defense" Stage 2 gameobjects don't work

### ISSUE THREAD

**Issue by BastionWAR** [WarEmu/WarBugs#10012]
I can't interact with gameobjetcts.

![thyrom_006](https://user-images.githubusercontent.com/30054005/28479431-ad69da6e-6e5c-11e7-8d56-5f0afa1b0dc6.jpg)

**Comment by Razielhell** [comment]
Please next time check if there is already a ticket with the same issue. #7153
