### ISSUE TITLE
Invalid Username/password

### ISSUE THREAD

**Issue by FootFactory** [WarEmu/WarBugs#1002]
Looks like changing password is not updating to server, or something similar. Numerous tries changing password, and same message. NO previous passwords work.

**Comment by g3n0k0m0** [comment]
I am having the same issue as this one

**Comment by Reggaewaldo** [comment]
This should be resovled after some time, there is just a delay AFAIK.

**Comment by Evildoor** [comment]
@Reggaewaldo is correct. Changed my password recently, the switch applied to forum login immediately and with delay (really big delay, several hours if not days) to game login. Just a guess - maybe the change only applies on server restart? Anyway, i don't think it's a bug, so i'm closing this.
