### ISSUE TITLE
Missing Skaven Token

### ISSUE THREAD

**Issue by Dragothurch** [WarEmu/WarBugs#10024]
Hi !

I doing all skaven quest, 2 in IC and all if high pass, kill last boss and pick up ring from last quest bust somewhere someone quest not give me toke, i got only 3. I think someone high pass quest not give but i dont know what. Any ide and help for 4. token for pet? Thx

**Comment by Lheana** [comment]
Take the quest 'As Lord TcharZanek Demands' in Talabecland Destruction Warcamp from chosen 'Arnorr Seven-Struck'. Then follow the quests.
