### ISSUE TITLE
ranulf baumann champion mount bloodhorn neutral state?

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#10029]
You can attack him and target him but Champion "ranulf baumann" is on neutral state instead of hostile. 

Normal?

location 56.7 mount bloddhorn

**Comment by Lheana** [comment]
Do you have a website that tells he is meant to be hostile ?

**Comment by thorbolt80** [comment]
https://wiki.returnofreckoning.com/index.php?title=Dirty_Dealings

The only thing I got. As he should stay neutral because its an unlock for destruction and order. for achievement : "Dirty Dealin'"

Please close this issue.
