### ISSUE TITLE
SW Whirling Pin ability bug

### ISSUE THREAD

**Issue by Dekata** [WarEmu/WarBugs#1003]
I have one question. Used in the official version of the game abilities like as WE Fleet-Footed when were activated, not given SW to jump through such as Whirling Pin. This will be fixed or not? Now this feature is extremely unbalanced against melee classes.

**Comment by Nfkillz** [comment]
why only SW? how about SH?

**Comment by Dekata** [comment]
I wrote it as an example. I am poorly familiar with the SH. But surely this mechanic should be extended to other classes, as well as in the official version of the game.

**Comment by Titoos** [comment]
"By the way this ability can be used without any enemies...." - so it's bugged.
AFAIK in the official war you could never use escape abilities such as "whirling pin" in following circumstances: 
-when your mdps target used immunity skill as choppa's "Shrug it off" or previously mentioned "Fleet-footed".
-when your target was knock-back immune.

**Comment by magter3001** [comment]
#811, people already know about this.

**Comment by Evildoor** [comment]
Closing, #811.
