### ISSUE TITLE
[IB] Shieldbearer's Defender of Glory Block Rating

### ISSUE THREAD

**Issue by joschika77** [WarEmu/WarBugs#10037]
Hello,

Is the Shieldbearer's Defender of Glory with 390 Block Rating buggy?
I can see no difference to the old shield with 357 Block Rating. Normally I should have 2% more block i think.  I've tryed the addon "statdoll" because ".getstats" does't display the real value.
Is it possible that it is'nt calculated?

regards

**Comment by sioding** [comment]
My old Shield:
![image](https://user-images.githubusercontent.com/18517842/40308092-5784cbac-5d05-11e8-9362-a964bb4c3531.png)

The Shieldbearer's Defender of Glory:
![image](https://user-images.githubusercontent.com/18517842/40308114-683d0ffe-5d05-11e8-8c1d-f00635375bc9.png)

Close cause no bug.
