### ISSUE TITLE
Quest : Lord's game - Elder Meresene does not respawn

### ISSUE THREAD

**Issue by jcstelu** [WarEmu/WarBugs#10041]
I'm unable to complete this step of the quest, because the body of Elder Meresene does not disappear and she won't respawn.

![bloodtide_012](https://user-images.githubusercontent.com/17513553/28711720-44d78534-7391-11e7-8605-46b1e774a24b.jpg)
![bloodtide_013](https://user-images.githubusercontent.com/17513553/28711903-ce779d74-7391-11e7-8d48-658c9140a9b1.jpg)

**Comment by Torquemadra** [comment]
seems fine to me

![untitled](https://user-images.githubusercontent.com/16200780/28723294-4ec81dd6-7384-11e7-850a-6c88c8a515b4.png)

**Comment by Lheana** [comment]
Works fine now.
