### ISSUE TITLE
Mara's wepon

### ISSUE THREAD

**Issue by Judart** [WarEmu/WarBugs#1005]
It's not possible to use Mara's wepon from chapter 8 rewards in off hand.

**Comment by Judart** [comment]
And seems they have stats from both hands wepon. Rune-Scribed axes have lower stats then they...

**Comment by Evildoor** [comment]
Weapon name?

**Comment by milosxe** [comment]
![blutausnord_009_cr](https://cloud.githubusercontent.com/assets/13332067/9981777/bf84672e-5fc6-11e5-8802-a2b095d8c8bd.jpg)
It's this axe. Elite reward from chaos ch8. Works fine. Closing.
