### ISSUE TITLE
Error in Officer Emblems

### ISSUE THREAD

**Issue by Chris-Otey** [WarEmu/WarBugs#10068]
Hey guys. This one frustrated me. I was buying my Mercenary set from the War Quarters in Altdorf. I had exactly 137 Officer Emblems. I know this was the exact number because I could have bought the boots but I wanted the nice round number of 100 emblems afterwards. When I bought the gloves, costing 37 emblems, I had 0 left.

**Comment by Kaelang** [comment]
May have been the case in 2017, however this no longer happens in the current version of RoR. Closing.
