### ISSUE TITLE
PQ Troll Country Deathstone Quarry

### ISSUE THREAD

**Issue by DedMango** [WarEmu/WarBugs#10064]
Trying to do the Deathstone Quarry PQ it tells you to kill horrors and flamers, killing the horrors counted as both horrors and flamers.
but did no update the "horrors" part
-Durtun Order

**Comment by Razielhell** [comment]
Works fine. Just this bug #6935 .

**Comment by Razielhell** [comment]
Quick fix. Run out of the PQ area and go back in so PQ tracker resets.
