### ISSUE TITLE
Quest: Boss' Huntin' - Unable to Complete

### ISSUE THREAD

**Issue by Kyragem** [WarEmu/WarBugs#10067]
During the later stages of the Boss Huntin' quest chain, there is a step to talk to a Goblin named Heem.

While the step to do so is there and it checks off, there is a step prior that reads "Invalid GameObject - QuestID 49072,ObjId=3856"

Attempting to turn the quest into Heem is impossible, as the quest will not register as completed.

**Comment by Razielhell** [comment]
#10057
#10038
