### ISSUE TITLE
Quest: Lob it Good! - Bloody Sun Lobber Dead - Bug

### ISSUE THREAD

**Issue by GentleN** [WarEmu/WarBugs#10072]
Map- Mount Bloodhorn
Task- Speak to the Bloody Sun Lobber

The Bloody Sun Lobber object is dead and can't be used to fly over to the Dwarf Wall.
The Npc Skarzag (located on the Greenskin prologue) has the icon over its head, giving the option to
complete the quest, but it does nothing.

**Comment by Razielhell** [comment]
Talk to Loba gitter next patch.
