### ISSUE TITLE
Obj giving infinite capture exp, influence, and rr

### ISSUE THREAD

**Issue by Killeramgon** [WarEmu/WarBugs#10074]
![image](https://user-images.githubusercontent.com/24874603/28803830-1f98bf4c-7614-11e7-93e6-409f2b299fa6.png)
![shagot_001](https://user-images.githubusercontent.com/24874603/28803839-3256b968-7614-11e7-98d5-4f0895d1a1f2.jpg)

**Comment by MRejou** [comment]
All is good, I don't understand.....? you can stay on BO  getting (very) small ticks waiting a min for order or go in lakes.

**Comment by MRejou** [comment]
read patch notes ! ^^

**Comment by Lheana** [comment]
So it is intended, not a bug ;)
