### ISSUE TITLE
Healer Npc not responding  -Blighted Isle

### ISSUE THREAD

**Issue by GentleN** [WarEmu/WarBugs#10078]
Map- Blighted Isle

Talking to Healer Npc  Laek Duskbranch does nothing, no window do pay for a debuff removal, nothing.

**Comment by Razielhell** [comment]
I just tried. Works fine.

**Comment by GentleN** [comment]
wierd.. maybe t'was a issue in my part. I'll try talking to him again.

**Comment by Razielhell** [comment]
Make sure you have Battle Fatigue debuff...or else he won't respond.
