### ISSUE TITLE
Second missing gold bag in two days, BUT its okay!

### ISSUE THREAD

**Issue by BrokedArrer** [WarEmu/WarBugs#10083]
So, I was have another post about missing a gold bag from the weekend that I never got, still havent.

Today I did some keep takes / defenses and learned something and hope with the knowledge, it can help YOU guys pin point where its going wrong.

So this morning, I won a loot bag, I did the same thing I had done on the weekend. The zone locked. the timer for the "reset" so to say,  hadnt ended yet, but I had left the zone, guild scroll'd home. Never received the bag. Still havent.

Later on in the afternoon, we did some more keep takes, I won another bag. this time however. I didnt leave the zone at all, until the zone "reset" timer had ended ( Waited in the WC after zone locked for the 3 minutes or whatever) and boom. Got mail with my bag in it.

This maybe how it is, it maybe just back luck on my part. But I think that even if you win the bag, and leave the zone, the server code somewhere forgets to still send you the bag if youve left even before that 3 minute timer is up after the zone locks.

**Comment by BrokedArrer** [comment]
So! I forgot to record this yesterday, but yesterday my golden bag showed up that i originally reported missing. I took 9 days. Upon checking my mail box it said 21 days remaining on it. LOL

**Comment by Razielhell** [comment]
#10279 Ty for the report.
