### ISSUE TITLE
The Bright Wizard Acolyte, Captain Von Wilke, and Tower Guards aren't respawning

### ISSUE THREAD

**Issue by Tydril** [WarEmu/WarBugs#1008]
The Bright Wizard Acolyte, Captain Von Wilke, and Tower Guards aren't respawning around the tower
![2015-07-22_00002](https://cloud.githubusercontent.com/assets/13453119/8827577/18b34e1c-3053-11e5-97a8-05e7a4ae5eb6.jpg)
![2015-07-22_00003](https://cloud.githubusercontent.com/assets/13453119/8827578/18b5d024-3053-11e5-8941-c5e76f801e82.jpg)
![2015-07-22_00001](https://cloud.githubusercontent.com/assets/13453119/8827579/18bb015c-3053-11e5-818c-0160a74a3d9a.jpg)

**Comment by Tydril** [comment]
Checked this morning and they were there, not sure what happened.

**Comment by Lumberjackscoot** [comment]
Right now the Bright Wizard Acolyte is not respawning. Not sure why. Other mobs were spawning fine though.

**Comment by Tydril** [comment]
Hmm.. it seems to come and go then

**Comment by Whoareyouagain** [comment]
I have the same issue today, I stand for 20 min for that to spawn and it never did.

**Comment by milosxe** [comment]
They are respawning normally. Closing.
