### ISSUE TITLE
Talisman Making

### ISSUE THREAD

**Issue by Saarsak** [WarEmu/WarBugs#10088]
Hi,
I am Zankar on game (Marauder) and i have a serious problem with the game, more precisely the one that prevents me to make talismans after 1 or 3 and forces me to relog to the game to resolve that.

For example, if i want to make 20 talismans i have to log out AT LEAST 4 times... and... it's really frustrating

There are no images because they're useless... how can i show you that i can't make talismans? :(

Thanks!

**Comment by wwitunsky** [comment]
Same exact problem

**Comment by Fenixfree** [comment]
Sorry but what is the solution?it still persist...

Thx
