### ISSUE TITLE
Vendor sell wrong item

### ISSUE THREAD

**Issue by ladislavmacoun** [WarEmu/WarBugs#10089]
Commodities Quartermaster at IC undercroft sell Token of the Blackguard Killer to BG that cannot equip it or use it.
![untitled](https://user-images.githubusercontent.com/15619993/28991870-5ff4a802-798f-11e7-833c-38b047b4dc6b.jpg)

**Comment by Lheana** [comment]
Yes it is only for Order: this item gives the related title for the ToK unlock Kill 1,000 Blackguards, as it was not working before patch of 24/06/2017. As Destruction can ont kill Blackguard players, this item is for Order only.
This vendor was previously selling pocket items for full set titles (annihilator, havoc etc), but these items have been removed from the vendor as now you obtain the ToK unlocks and the related titles for full sets by equipping it.
