### ISSUE TITLE
"The King's Flying Corps" can't trigger? kadrin valley history & lore 44.7k 58k.

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#10082]
According to ROR wiki it's possible :

https://wiki.returnofreckoning.com/index.php/Kadrin_Valley_History_and_Lore

We can trigger the unlock in fact the gyrocopter was removed from the pad and now there is some fire burning.

see also #8897. Should update ROR wiki?

**Comment by Lheana** [comment]
Thanks for reporting it. In fact the gyrocopter has been set as an objective for stage II of the destruction PQ where it is. That's why you can not see it, the PQ must be stage II for the gyrocopter to appear.
