### ISSUE TITLE
throwing dagger/snapshot damage

### ISSUE THREAD

**Issue by gebajger** [WarEmu/WarBugs#10087]
![trial_024](https://user-images.githubusercontent.com/13971319/28989323-d1b7e8d4-7974-11e7-9d52-d9d1073b7d47.jpg)

**Comment by Scrilian** [comment]
Yep, both WH/WE ranged throw attack deals right now roughly 10to20 times the damage of any other throw attack in the game.

**Comment by Torquemadra** [comment]
fixed long ago
