### ISSUE TITLE
Loading issue with Black Ork

### ISSUE THREAD

**Issue by GentleN** [WarEmu/WarBugs#10084]
Im truly not sure about this, but it's been almost a week since i can't load into the game properly, ONLY, with my Black Ork...
Every other character loads normaly, no problems.
But with my BO, most of the times, the loading goes on and on and suddendly, just sends me back to the main menu, without 
any warning window like a disconnection, it just kicks me offthe loading, it's a bit frustrating really.

But again, not sure if this is an issue around everyone.. but i would like some help :S
Thank you for listening.

**Comment by Lheana** [comment]
Contact a GM ingame with a char you can log on.
