### ISSUE TITLE
riding an enslaved pack mule as a chaos magus

### ISSUE THREAD

**Issue by Molestus** [WarEmu/WarBugs#10080]
i started a new chaos magus character and i noticed that i can for some reason ride pack mules, so i took one and i summoned it, was not disappointed when i just ended up standing on top of the body of a dead dwarf and skiing on him.
![warhammer online age of reckoning 08 01 2017 - 15 04 11 02](https://user-images.githubusercontent.com/30628770/28829659-cd39e872-76d4-11e7-991c-616bb18e64fc.png)

**Comment by Torquemadra** [comment]
thx fix next patch

**Comment by Molestus** [comment]
would be better if you gave the dwarf animation so i can fulfill my dream of riding slave dwarves
