### ISSUE TITLE
Dok/ WP bugged Class Mechanic

### ISSUE THREAD

**Issue by Elratie** [WarEmu/WarBugs#1009]
on DoK and WP, if you hit Flee the Soul/ Fury are replenishing just normal and you can still use the abilities/ heal, for the time Flee is active it shouldn´t do that

**Comment by Silentguard** [comment]
If you are not in combat its ok.

**Comment by Elratie** [comment]
sorry but it´s not, an example: you running in Reikland on the left/ right side hitting Flee 5 sec. later you turn around the corner and look at a fight with on of your groupmates against 2 others, so you have 5 sec. left on the Flee timer but oh wonder half your Soul/ Fury is back and you can throw some heal that you shouldn´t. so with Flee you can do nothing! except running

**Comment by Evildoor** [comment]
AFAIK, it was exactly the same in official WHO. So, i don't think it's a bug. However, the suggested change still makes sense.

**Comment by Silentguard** [comment]
WP\DoK have non-combat career resource regen so as i said its ok and it was the same on live server.

**Comment by Elratie** [comment]
then it was on live after the rr 90/ 100 expensions came out, i stopped playing before they came and it was as i explained no reg and use of Abilities if the 10 sec. Flee is active. every Class loses Class mechanic point´s and AP with the use of Flee why should DoK/ WP be an exception?w

**Comment by grumcajs** [comment]
its same with all mechanics. 

when u hit flee as IB/BG u still gain grudge hate when they hit you or when they hit your ally 
when u hit flee as slayer/choppa, u still build up that berserk'o meter 

wp/dok do not regen at all if they are in combat except the passive regen from chalice/gear

everything works as intented - no I do not play WP/dok - close and move to another topic

**Comment by Elratie** [comment]
that´s a very nice attitude you have perfect for this game: a few classes broken and it is working as intended, i think you didn´t get what i was explaining earlier.

so you saying that every class with an extra pool of resource, that too me seems actually broken big times, has a big advantage against those classes with just the AP resource is working as intended? LOL

same example just do it with an AP based healer and oh wonder you can just staying there like Max in the Sun and watch how your groupmate dyes and do nothing cuz no abilitie works in the last 5 sec or rather need more time since the AP has to be regenerate

another Example maybe you get it then 
Gate of Ekrund with BG:

Dark Protecter on a choppa who stays in middle flag, you going up with the middle stairs half the way und the roof you hit flee so in the time you get to the choppa for guard you have gained 30 Hatred, still has the flee timer lets say 4 sec., and man it is nice to have 30 hatred as a BG you can use so much abilities with a 30% run speed like: Blade of Ruin (block should pop with guard), Mounstrous Rending (hit 2 of the foes on the choppa and they are dying....), Pitiless Strike, Crimson Death, Furios Howl, Shield of Rage, Choking Fury and Bolstering Anger. i have to say wow omfg that´s so awesome and then you get people spreading that every one is speedhacking.

so now do the same with an Kotbs, Chosen, BO or SM and omfg you cant do anything except block some inc. dmg

so do you guys need more example´s? or did you get it?

**Comment by Silentguard** [comment]
Dont make from bug tracker place for disuccsion, use the forum for this.

**Comment by noisestorm** [comment]
Flee did just set your Fury (like every other class mechanic) and AP to Zero, but the regen from the Book was ALWAYS on. No bugs here

**Comment by ozarmidrashim** [comment]
Agreed that this is not a bug. Skill description also agrees:

"You instantly lose any mechanic points". It only states that AP will not be regenerated.

Given that this is not a bug, no further discussion should occur here - it is now a balance issue.

**Comment by maakur** [comment]
Since a recent patch, AP and career mechanic depletes for my WP upon Fleeing, but I am unable to cast Divine Mend with any regenerated Righteous Fury... until the AP begins to fill (other heal spells do work, oddly). Since the casted heals do not actually use AP this behavior seems odd, and it did not happen previously. Was this change intended?
