### ISSUE TITLE
Tome unlock

### ISSUE THREAD

**Issue by Eneko85** [WarEmu/WarBugs#10097]
Hi, my problem is that it don´t let me collect the rewards of tome, for example "Organ Grinder" or  "Soul Catcher" items appears empty. Several images of the problem:

![issue1](https://user-images.githubusercontent.com/30751521/28995907-cf276eba-79f5-11e7-8407-33294dd45999.jpg)

![issue2](https://user-images.githubusercontent.com/30751521/28995908-d2113ca0-79f5-11e7-9ee7-95bcd4f38a51.jpg)

**Comment by Lheana** [comment]
Talk to the vendor 'Disciple Venomstung' who sells these items in the Lyceum (as you are destro), at this moment they will appear.
