### ISSUE TITLE
Quests: List of some.

### ISSUE THREAD

**Issue by GentleN** [WarEmu/WarBugs#10093]
Chaos Wastes/Praag:
The Pleasure of Pain - After killing the mob and talking to its corpse, the quest is completed, but no where to deliver.
Fury Tamed - No quest marker and cant find what i'm suppose to defeat.
Trail of Blood - No quests marker, and cant find the npc or corpse.. dont know really.
The Deamon Released - No quest marker, still didn't found the npc.

Note: My apologies if these had nothing wrong in them, just trying to help.
I will try to report more around these maps, most of what i have found are were a mess..
Will create a bigger list soon, and again, apologie for my mistakes.

**Comment by Razielhell** [comment]
1 report per ticket
