### ISSUE TITLE
ToK: No Reflexion of Your Skill

### ISSUE THREAD

**Issue by blechkautz** [WarEmu/WarBugs#10107]
It seems like the skeleton(Komnor Bronzemug) for the unlock isn't at the place it should be.  
Or atleast the entry in the wiki about the coordinates is wrong.
![dampfwalze_001](https://user-images.githubusercontent.com/30760089/28999213-cf4db8a6-7a3e-11e7-888c-1891887bd22b.jpg)
![dampfwalze_000](https://user-images.githubusercontent.com/30760089/28999214-cf524e2a-7a3e-11e7-8e91-3c6db526a80a.jpg)

**Comment by Lheana** [comment]
Yes I know, it is currently under the ground, I fixed it yesterday, so will be fixed next patch.

**Comment by tomaslumba** [comment]
Thx for all the hard work you guys put in!
