### ISSUE TITLE
Snare effect not applied after mdps immunity ability ends

### ISSUE THREAD

**Issue by Zealote** [WarEmu/WarBugs#1010]
Tested with WL's Feline Grace (FG). Used 10s snare when FG had 5s remaining - no snare effect applied for the remaining 5s after FG had ended.

**Comment by Titoos** [comment]
Im almost sure it works as intended.

**Comment by ozarmidrashim** [comment]
100% working as intended.

**Comment by Zealote** [comment]
Okey doke, will close.
