### ISSUE TITLE
Sigmar's Grace range

### ISSUE THREAD

**Issue by Niakahn** [WarEmu/WarBugs#10100]
Sigmar's Grace range bug/nerf.

Significant reduction in Sigmar's Grace range.

Contrary to the tooltip, the buff's range is well below the specified 100 foot range.

[url]http://imgur.com/QzoiUOq[/url]...

As you can see, the intended recipient did not in fact, receive the buff, delineated by the absent heal indicator.  I later looked through his status tooltip to confirm, and he indeed did not have a wounds buff of any classification.

The range reduction bug/nerf has persisted for about a month, now, and though it hasn't necessarily severely impacted my performance, it still has remained a relative nuisance to keep everybody within range buffed.  Haven't been able to verify whether or not this was an intended change, as it hasn't appeared on the patch notes thus far.  Any word would be appreciated.

**Comment by Torquemadra** [comment]
intended
