### ISSUE TITLE
The Pale Eye

### ISSUE THREAD

**Issue by Zaphologist** [WarEmu/WarBugs#10101]
Haven`t found anything about that topic, so i opened up this one.

In the Quest "The Pale Eye" in Altdorf, you need to find a clue, which is the sack laying on the right side (outside at the docks) of the "Tavern Blowhole". This sack can´t get clicked on. I´m pretty sure this was the clue, I did this Quest so often.

Thanks for your effort and sorry for my english.

You Guys are awesome!!!
Blood for the Bloodgod, Skulls for the Skullthrone and Milk for my Khorneflakes

**Comment by Lheana** [comment]
True, fixed next patch.

**Comment by Zaphologist** [comment]
Nice, that was really fast! 
I can´t thank you guys often enough, for spending all that time and effort to this game!
Hugs & Kisses
Your biggest Fan
Zaph
