### ISSUE TITLE
Black Ork Loading game issue ( keeps getting worse )

### ISSUE THREAD

**Issue by GentleN** [WarEmu/WarBugs#10114]
Most of the time when i wish to play whit my black ork, the loading screen ( book with lore while loading )
doesn't load at all, it just Send me back to the main menu.
![screenshot_005](https://user-images.githubusercontent.com/30581957/29005325-d0e5b834-7ad0-11e7-8549-2fa4e5457c34.jpg)

Rarely it does this to me.
![girgurdatuff_016](https://user-images.githubusercontent.com/30581957/29005329-fb1681d8-7ad0-11e7-9fcb-8b4ada40c252.jpg)

![girgurdatuff_017](https://user-images.githubusercontent.com/30581957/29005335-15cd15be-7ad1-11e7-83fb-810404be4d2a.jpg)

And one time.. instead of showing up the loading book, it showed this...
![screenshot_004](https://user-images.githubusercontent.com/30581957/29005340-2ea9e954-7ad1-11e7-8647-0b126a427304.jpg)

Now i Cant even connect to a Scenario without being expelled to the menu screen ( 1st picture )
And constantly getting Quitter debuff, Great!

Note: This only happens ON my Black Ork, other characters so far, all safe.
Please help...

**Comment by GentleN** [comment]
Yes i have spoken to a GM and all he said was to write /stuck  while loading ._. ...

**Comment by HtGeist** [comment]
try /stuck 2 times type very fast while loading...has to be fast 2 timesin rapid succession should send you to chaos starter zzone...and hopefully out of the badd loop.

**Comment by sioding** [comment]
**Thanks for the report.** Since there is no confirmation, i will close this issue now. You can help us by following the bugtracker rules which you can find here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)
