### ISSUE TITLE
Red mist magus /Napalm Grenade Engineer

### ISSUE THREAD

**Issue by HtGeist** [WarEmu/WarBugs#10118]
In pve yea they hit,in rvr/scs they not hitting anything...had a shammy walk into the middle of my napalm grenade stand there for 8 seconds nothing,then he mounted up and still stood smack in center..no dmg at all,same story with redmist on magus ib standing dead in center no dmg...no diisrupt, no block simply nothing...not hitting any at all ,or doing anything to people walking into the area..

**Comment by wargrimnir** [comment]
I wonder if this is related to the AOE cap, did it simply hit no one, or did the ability already land on several people and fail afterwards?

**Comment by HtGeist** [comment]
Just seen mist hit something after 3 days of casting it in rvr...had casted on group of 3-5 orders on a flag pole,should be no where near any cap...and solo ib was in it at dead center till it ran out/expired not 1 dmg to him...maybe its highly affected by latency/server memory cropping up,i dont know...but hit something today after 3 days...

**Comment by HtGeist** [comment]
Just been conducting research with magus,my situation im laggy 200ms...hence i play ranged..i i put down dissolving mist on a group of 3 i hit em all with 3 ticks...then it stops doing dmg,anyone entering the area is not getting hit...and area seems to be 20 radius  total not 20 radius from center 40 at its widest...increased dmg tick doesent start doing dmg..

**Comment by HtGeist** [comment]
This is for rvr in sc¨s,in pve yea you can hit area still seems too small.
