### ISSUE TITLE
Apothecary ingredient text misspelling - very minor 

### ISSUE THREAD

**Issue by MalandraRoR** [WarEmu/WarBugs#10116]
Acrid Arachnid Venom text reads "This average ingredient can be used to create thoughness concoctions."  Should read 'toughness', I'm assuming.

**Comment by Lheana** [comment]
Typo fixed next patch

**Comment by wargrimnir** [comment]
This is a common spelling error in the DB, there's probably many instances of it.

**Comment by MalandraRoR** [comment]
Is this something you guys even want a report on?  I don't want to clog up the works.

**Comment by Lheana** [comment]
Sure you can report these spelling errors in this post (even when it is closed). Easy thing to fix.
Btw I fixed the typo for 'Acrid Arachnid Venom' but also for 'Milky Arachnid Venom' cause there had the same typo, so no need to report it.
