### ISSUE TITLE
Archmage Instant cast

### ISSUE THREAD

**Issue by Joytoy** [WarEmu/WarBugs#10120]
It appears that if the mechanic is up to 5 and you try to cast a spell that should be instant, it does not trigger if you are on the move. You have to actually stop for a certain amount of time for anything to trigger and there is a delay before the triggering that does not correspond to the cast time on the skill tab. The animation however triggers, but not the effect. It makes the class pretty much unusable as far as mechanics are concerned.

**Comment by Joytoy** [comment]
After some testing, it seems that the ability is triggered at the end of the global cooldown. So for instance if I use 5 damaging abilities to crank my mechanic and then use boon of Hysh while standing still, the animation occurs right away, and at the END of the global cooldown afterwards the heal actually triggers and then i can move or use another skill.

**Comment by wargrimnir** [comment]
Class mechanic was changed.
