### ISSUE TITLE
Quest : "Burden of vengeance" order side "TM+Cinderfall" final red mark quest don't show up.

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#10125]
The final red mark of the quest (quest finished) don't show up where you give up the quest to have the last reward.

"kill dragonblessed larina" 1/1 don't show on the map where you give up the quest.

**Comment by thorbolt80** [comment]
Look like the problem happen when you **log off.** After  relog you don't have the red mark on the map but you can still finish the quest. Have to check if this problem happens for all quests after log off.

**Comment by Razielhell** [comment]
known issue. Nothing can be done yet.
