### ISSUE TITLE
Quest : "breaking the cult" order side "TM+Cinderfall" final red mark quest don't show up.

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#10123]
The final red mark of the quest (quest finished) don't show up where you give up the quest to have the last reward.

"kill dragonblessed korlis " 1/1 
drakk flamewards 3/3
read the letter from merona 1/1

Don't show on the map where you give up the quest.

**Comment by thorbolt80** [comment]
Look like the problem happen when you **log off.** After  relog you don't have the red mark on the map but you can still finish the quest. Have to check if this problem happens for all quests after log off.

**Comment by Razielhell** [comment]
Same #10125 #10124
