### ISSUE TITLE
Game object: all "dwarf tool box"  seems floating PQ : "gobbo carvas" BC 38.31

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#10139]

**Comment by Razielhell** [comment]
https://image.prntscr.com/image/DDGbjTB6SNeO-39cd1eNsA.png
https://image.prntscr.com/image/twhEch57RPysAOEMM2aY4Q.png
Nothing we can fix at the moment. Sometimes they will fly when you enter the PQ sometimes they won't.
