### ISSUE TITLE
Quest: death from above. order side BC. (no cask) chapter 21 dwarf

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#10138]
You are suppose to examine the cask given  by Rorki thunderbreaker (33.19) after killing idegir the unclean

examine cask 0/1
idegir the unclean 1/1

There is no cask in my inventory because Rorki thunderbreaker don't gave it.

Even if you interact with quest giver (farlin ironbeard 33.20) nothing happen

**Comment by Lheana** [comment]
Changed a bit the quest objectives as it is not possible to implement it like official: You will now have to kill Idegir the Unclean (that I have moved closer to his original place), killing him will drop item 'Cask of Blood' that will complete the second objective.

**Comment by sioding** [comment]
fixed in patch 22.09.2018
