### ISSUE TITLE
Bags dropping in Serpents Fang- Talebecland- appear to be wonky

### ISSUE THREAD

**Issue by Truedie** [WarEmu/WarBugs#10131]
Upon completing the PQ, we saw the usual place achieved, followed by the roll.. Not only did we not appear in the place we achieved, we did not align with the roll either.  I rolled 4th place, showed as  2nd place on the list and received an empty blue bag. Another party member rolled 3rd, showed as 4th and received an empty purple bag. Also, 5th place player received a gold bag. All bag were empty except for gold, I believe.  I do have screen shots if needed.

**Comment by Razielhell** [comment]
provide screenshots please.

**Comment by sioding** [comment]
**Thanks for the report.** Since there is no confirmation, i will close this issue now. You can help us by following the bugtracker rules which you can find here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)
