### ISSUE TITLE
Detonate casts from any other player's Hex.

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#10149]
BW's detonate is a AOE which affects splash damage..  Right now, the bug, is that you can open with a detonate provided some other player has already placed a Hex on said player.
The proper implementation is that your own hex must be first placed on your target.

thx

**Comment by Torquemadra** [comment]
This seems highly unlikely, proof please

**Comment by Scrilian** [comment]
Has always worked with any source of hex.

**Comment by Haojun-Phalanx** [comment]
There is no information about "it should be your own hex" on the tooltip. It was always like this iirc.

**Comment by gittoaster** [comment]
I don't agree but I accept that there is no proof although I could see some cases where Detonate would clearly not be available (often AOE spec BW), but I am not able to confirm because of the specifics related to demonstrable cases.
thanks..
I have always known that ability to not be an available option as 'an opener' ability, such as it is now.  The argument is that it's too powerful to have as an insta-cast career ability (non-spec) without that 1 extra GCD cast of any Hex.  
(no response is necessary)
thank you
