### ISSUE TITLE
Komnor Bronzemug is gone!

### ISSUE THREAD

**Issue by Bobbiom** [WarEmu/WarBugs#10142]
''Wordbreaker Band: (38.5k, 35.5k) Travel to Thunder Mountain and head far West to Cinderfall. Make your way to the coordinates given. Sight an interacrive object on the ground called "Komnor Bronzemug". Simply click on it and you will be granted the tome unlock, "No Reflection of Your Skill", allowing you to claim Wordbreaker Band.''

Komnor Bronzemug is nowhere to be found at this location.

**Comment by Razielhell** [comment]
He is there. 
https://image.prntscr.com/image/5ccrab7PS8SoYvQFdhCY8A.png

**Comment by tomaslumba** [comment]
Gone again, unless it has been moved in the last couple of months. 

Kind regards

**Comment by Razielhell** [comment]
You are right. He is in the ground. Replaced him. Hopefully will be fixed next patch

**Comment by tomaslumba** [comment]
Sweet, thx mate! Keep up the great work!
