### ISSUE TITLE
[Ability] Hold The Line! isn't working

### ISSUE THREAD

**Issue by Haojun-Phalanx** [WarEmu/WarBugs#10145]
Self buff %45 is working on yourself.
%15 X 3 on friendly buff isn't.

1- https://www.youtube.com/watch?v=0k36OU0oC2c&feature=youtu.be

agaist bw, magus has : 62 base distrupt + 45 from htl = 107 distrupt
agaist sw magus has: 50 dodge + 45 from htl = 95 dodge

2- https://www.youtube.com/watch?v=pAM_nOb5olE&t=4s

agaist bw, mara has : 46 distrupt + 45 from htl = 91 distrupt

3- there is a bug report about it **[%15X3 buff can't be seen in .getstats]** from january 2017, locked by azarael without useful information.
https://github.com/WarEmu/WarBugs/issues/8945

4- from 3 hours RvR today while my sorc got %0 dodge and distrupt. i have always 3X HTL in every combat. according enemy combat statistic i didn't dodge or distrupt at all.
![haojun_150](https://user-images.githubusercontent.com/23129933/29196411-c4c3777a-7e3c-11e7-9352-e82bcbbac3e3.jpg)

**Comment by Fuineir** [comment]
You should've used .getstats after whenever testing occured, without it everything can be blamed on rng gods.

**Comment by Haojun-Phalanx** [comment]
already done. you can check it by yourself. no increse from .getstats

**Comment by Nfkillz** [comment]
getstats doesn't show this increase because of how it is implemented (Azarael #8945)

**Comment by Natherul** [comment]
fixed now

**Comment by Haojun-Phalanx** [comment]
awesome.
