### ISSUE TITLE
Arathan Sunblade t4 epic weapon elf quest icon missing

### ISSUE THREAD

**Issue by Korvinus89** [WarEmu/WarBugs#10141]
The quest giver Arathan sunblade in chapter 20 his quest icon is missing/sunk into the map

Ordric Wolflord
(trying to get a posh mount reported a few :3)

**Comment by Razielhell** [comment]
Looks good to me. https://image.prntscr.com/image/21Nifya4Rca62_gYmhHeCA.png

**Comment by Korvinus89** [comment]
thats very strange :3 my apologies for wasting your time.
