### ISSUE TITLE
Elder Kadrias has no respawn- A Lord's Game epic (T2)

### ISSUE THREAD

**Issue by mwasp** [WarEmu/WarBugs#10148]
After kill Eldar Kadras(before pick up quest) he has no respawn any more. His body doesnt disappear, and no new respawn.. so epic quest chain broke this way. 

Check picture

![kettehasitalak_004](https://user-images.githubusercontent.com/28621963/29175013-430b93ec-7de8-11e7-89c0-c35f52803d4b.jpg)

Its an epic quest game breaking bug as quest chain broken this way.

**Comment by Lheana** [comment]
Just killed her on live, she respawned after like 1 min

**Comment by narogart** [comment]
Elder Kadrias is bugged atm, not respawning.
