### ISSUE TITLE
npc Magister Dhetal : missing animation and wrong foe state

### ISSUE THREAD

**Issue by Mene51** [WarEmu/WarBugs#10143]
The boss of PQ : Magister Dhetal, chapter 21 dwarf, is missing animations and stay "neutral" during the last step of the public quest. We can hit him, but all ranged attacks appears red during the fight.

![menetos_005](https://user-images.githubusercontent.com/30856126/29107695-b85367c8-7cdb-11e7-8c1f-c07f0a47eb18.jpg)
![menetos_006](https://user-images.githubusercontent.com/30856126/29107697-b85cf496-7cdb-11e7-827c-cb757f2b81cc.jpg)
![menetos_007](https://user-images.githubusercontent.com/30856126/29107696-b858a2d8-7cdb-11e7-9d20-dc421039f8d9.jpg)

**Comment by Ryanfawkez** [comment]
Fixed the animation issue; leaving the figleafdata for somebody else to determine.
