### ISSUE TITLE
Archmage/Shaman Mechanic

### ISSUE THREAD

**Issue by HtGeist** [WarEmu/WarBugs#10156]
Read in patch note its supposed to go back to good old 5 heals 1 damage spell with 25% insta if had cast time,5 dmg spells insta heal.... but i am still getting the experimental mechanic,and a very bad one at that 5 dmg spells heals all fiery i casta 2single target heal,while staionary...elfie waves his hands in the air for a good 1-2 seconds..then nothing for another 1-2 seconds and slightly delayed a basic single target heal appears....took a good 4-5 seconds to land for the supposed insta...i coulda casted 2 heals and moved abit if the damn mechanic would leave me alone....fix comming?

**Comment by wargrimnir** [comment]
Did you read in the patch notes the part where Dev changes are waiting for a hotfix to apply?
