### ISSUE TITLE
Double Seal of Paragon gain

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#10154]
there was a report. #9987 
I can confirm this Seal of Paragon double bug.
![seal_bug](https://user-images.githubusercontent.com/19988772/29133819-a5e2b3b6-7d6f-11e7-8423-1d04d3eaaee6.jpg)
I missed screenshot of inside of mail. there were 2 officer medals and 1 seal of paragon.

you get seals when zone locked, no matter where you are.
it goes directly into your currency bag.
and you get same amount of seals from mail if you were in SC when timer of reward chest expired.
aao is not related to this bug. screenshot is when I won zone.

I had experienced this once and tried to reproduce this bug by joining SC when zone is almost locked.
if chest popped on your screen inside of SC but you got out of it before timer of chest expired
mail is not sent.
or mail is not sent because I didn't earn single officer medals at that time.

sry my english.
bug is you getting seal from mail and directly both, in some situation.
that situation is when you were in SC.

**Comment by Razielhell** [comment]
This is not a bug like i said on the other ticket...this is normal.

**Comment by Razielhell** [comment]
#9987
