### ISSUE TITLE
The Well Of Qhaysh Warden cannot be attacked

### ISSUE THREAD

**Issue by wdesu** [WarEmu/WarBugs#10151]
The outer door warden (the one on the right) cannot be attacked with any abilities (out of range), he's just standing there doing nothing. Sending pet squigs to attack him makes them disappear.
![qhayshwarden](https://user-images.githubusercontent.com/29466521/29202288-6c89c96e-7e6f-11e7-8cc5-9b1953244f53.jpg)

**Comment by Lheana** [comment]
Keep Warden will eventually be attackable.

**Comment by sioding** [comment]
fixed with patch from 24.02.2018
