### ISSUE TITLE
NPC Keetz in Kadrin Valley, Gashfang's Warband (Greenskin Chap. 21)

### ISSUE THREAD

**Issue by MalandraRoR** [WarEmu/WarBugs#10158]
This NPC gives a quest that is not complete-able  - does not give the item 'Squid Siccer' needed to complete the quest.  <s> Once the quest is abandoned, this NPC still has the orange quest completed indicator overhead, although the quest is not taken. </s>

EDIT:  Logging that character out and back in seems to have resolved the orange quest circle over his head.

Screenshots indicate NPC's location, the quest text indicating the item needed to complete it (Squig Siccer) and showing that I do not have the quest, yet he still has the overhead orange indicator -- which seems to be resolved on relog, but i left the ss here.
 

![malandra_000](https://user-images.githubusercontent.com/30743648/29237114-d649cbac-7edc-11e7-9dde-399b7a850123.jpg)

![malandra_001](https://user-images.githubusercontent.com/30743648/29237115-d65a6534-7edc-11e7-96a2-5f6d6591eb80.jpg)

![malandra_004](https://user-images.githubusercontent.com/30743648/29237116-d65e94f6-7edc-11e7-8500-35940c2b1ce2.jpg)

**Comment by Lheana** [comment]
So is it fixed?

**Comment by MalandraRoR** [comment]
Quest is still not complete-able, does not give object needed to complete it.  Orange circle issue appears to be fixed.
