### ISSUE TITLE
Bugged-Quest-Shadowlands-MinorBug

### ISSUE THREAD

**Issue by gke96** [WarEmu/WarBugs#10152]
NPC Katmis Shattersword in Shadowlands order warcamp give quests that you can finish on him again total 4 quests. You get free 10k exp and some free silver
![dogwhisperer_000](https://user-images.githubusercontent.com/11146551/29212012-15eb5f9c-7ea5-11e7-9faf-25799286eb32.jpg)
![dogwhisperer_001](https://user-images.githubusercontent.com/11146551/29212011-15e7062c-7ea5-11e7-9d52-1478b275c268.jpg)

**Comment by Razielhell** [comment]
Yes because we don't have a system yet to scout areas for quests.

**Comment by Lheana** [comment]
Duplicate of #6872
