### ISSUE TITLE
Always In Combat Scenario Queue on all characters

### ISSUE THREAD

**Issue by shamequa** [WarEmu/WarBugs#1015]
None of my characters can join a Scenario because when the queue pops it always says I'm in combat.  I've tried queuing on 3 characters, in warcamp, out of warcamp, flagged and unflagged, also in Altdorf. Queuing for a single scenario or for all.  Was working a few hours prior.

**Comment by gittoaster** [comment]
you are probably experiencing a known "in combat" bug.  close the game by task menu 'ctrl-alt-delete' and relaunch the game should fix it.

**Comment by knezekj** [comment]
i have the same problem i hope it will be fixed after ctrl-alt-del.

**Comment by ozarmidrashim** [comment]
Temporary fix via &jump command (see post in News regarding combat bug)

**Comment by knezekj** [comment]
&jump is not functional for me and after ctrl-alt-del i can join two-times sometimes three-times but than still in combat bug.

**Comment by xyeppp** [comment]
How is it not functional? Are you typing it on /say chat or /advice? You have to type it on /say chat.

**Comment by Evildoor** [comment]
Command was changed to ".unlock" in 18.12.2015 patch.
