### ISSUE TITLE
[Quest]Center of the World in Altdorf cannot be completed [Minor]

### ISSUE THREAD

**Issue by TKOEF1112** [WarEmu/WarBugs#10157]
I wanted to state that I am new to GitHub, much less the WarEmu Github process.  That said I was hoping I could make this issue known to devs, if not already known by them about the quest Center of the World, in Altdorf, issued by some Crier guy (I forgot his name) near the flightmaster.  I was able to talk to all of the people except for the Patriarch guy (Thyrrus? something like that) who is at the Bright Wizard College, which is inaccessible.  I'm not sure why it's not accessible, but could we at least have the requirement to speak to that guy waived until it is accessible?  I'd like to be able to complete the quest on my lowbie order toons for easy xp.  Thanks!

**Comment by wargrimnir** [comment]
Use the search function before entering tickets. This is a very old one waiting on the Bright Wizard College implementation. https://github.com/WarEmu/WarBugs/issues/297
