### ISSUE TITLE
BL weekend DW questgiver bug (Destro)

### ISSUE THREAD

**Issue by ragafury** [WarEmu/WarBugs#10153]
Can't finish the follow up quest on my choppa.

Finished the BL Quests for the shoulders, helmet, ring, cloak, chest mid and after season one.

can pick up the follow up quests on my choppa from the following areas / npc's: KV, BC, CW, West Praag / Praag.

Can't pick up the follow up quests from DW (cloak follow up quest) (Krelith Ebonhide).

NPC just has no quest, no overhead symbol and I can't interact with him in a dialogue.

**Comment by Tesq** [comment]
confirm no one can take it
