### ISSUE TITLE
cinderscale lizzards not attackable

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#10163]
When you click on this cart in Thunder Mountain, these lizards called Cinderscale Monitor spawns, which is not targetable.  Although the screenshot states they are not attackable, they are not able to be targeted unless they attack you first..  Tab target can't pick them up either.

https://nxxqmq.bn1303.livefilestore.com/y4mtQUrXJskDDEhQTI96SS4LyZ2g4-lv57FoEbuhJmD5Cf6OS4PyaSmaptkm7dNSWjvp1KRPDHU4Lf_AxclUDvtPHJdsyeg-qz-lNhF0E1IbgRMaLtEICStxeumKJCO3Sl-OIXFRijX6QIoXOT8JexbiBdcv77wU7u1NUXdsBDKOfpX3JZ2IkQIgtHLsQS10NrUCO9CgxKVK7Dib67ejG9szg/little%20dragons.png?psid=1
thx

**Comment by Razielhell** [comment]
Sorry i found nothing about this. Can you give me the name of the cart?

**Comment by Razielhell** [comment]
Lizards bug are fixed by they way. Good finding. If you find same issue with other mobs report please.
