### ISSUE TITLE
Caledor Tree

### ISSUE THREAD

**Issue by dansarii** [WarEmu/WarBugs#10165]
The Caledor tree is the bane of order's existence. Adding some objects to block the tree would be great. (Tree down the hill from the warcamp).

**Comment by anarchypark** [comment]
![solitair_018](https://user-images.githubusercontent.com/19988772/39406438-a77c76ca-4bf1-11e8-9b1e-a7ac6814b719.jpg)
![solitair_020](https://user-images.githubusercontent.com/19988772/39406447-bac63248-4bf1-11e8-8007-7d575fd4f21d.jpg)
run or ride down to steep hill, you met tree.

**Comment by sioding** [comment]
fixed with patch from 26.05.2018
