### ISSUE TITLE
Harbringer of Doom always lit

### ISSUE THREAD

**Issue by Whoareyouagain** [WarEmu/WarBugs#1016]
Once I click Harbringer of Doom, the icon do the swirling light. I want to untoggle it, so I click it again. The icon is still highlighted. But the effect is off. it just the graphic bug.

**Comment by Reggaewaldo** [comment]
It's the same for RP.

Icon after toggling and untoggling:
![icon](https://cloud.githubusercontent.com/assets/13517919/8901675/f5343612-344a-11e5-9852-cd93eaa67a1c.PNG)

Might also be noted that on live the passive effect Harbringer of Change was active by default until you effected HoD. Same on Rune of Breaking for RP.

Initial logon:
![1](https://cloud.githubusercontent.com/assets/13517919/8901649/c838daa0-344a-11e5-9fd1-be2943eb5337.PNG)

Toggling on:
![toggled](https://cloud.githubusercontent.com/assets/13517919/8901661/dade2d36-344a-11e5-833a-55d485c72361.PNG)

Toggled off:
![untoggled](https://cloud.githubusercontent.com/assets/13517919/8901672/eb8394d2-344a-11e5-8714-56a3ae96161e.PNG)

**Comment by Evildoor** [comment]
https://github.com/WarEmu/WarBugs/issues/752
