### ISSUE TITLE
Big White lion Bug

### ISSUE THREAD

**Issue by triedset** [WarEmu/WarBugs#10162]
Hi.

I play a White Lion, and every time I change to a different zone, i lose my lion, witch is a big set back for White Lion. Especially when you play RvR. When I lose the Lion there is a 15 second cool down, before I can get it back again. It also happens when a leave an RVR zone.

Hope this is something you can fix fast.

Yours Sincerely
Triedset

**Comment by Haojun-Phalanx** [comment]
very big bug indeed.

**Comment by triedset** [comment]
Hi Thanks for understanding.

A White lion without a lion is not that strong :P

Hope you can Fix it

Den 12. aug. 2017 18.39 skrev "Haojun-Phalanx" <notifications@github.com>:
