### ISSUE TITLE
Quest BC order side "stench" 

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#10168]
retrieve bluegut's staff 0/1

There is not blue guts shaman to kill at all in the quest area. Kill all mobs twice to be sure.
So they don't drop any staff can't complete the quest.

**Comment by sioding** [comment]
Sorry.... i have found him - and he is in the questmarker area:

![image](https://user-images.githubusercontent.com/18517842/45373749-7c7ac800-b5f0-11e8-96db-73c277c56c3a.png)
