### ISSUE TITLE
BL quest resetting bug

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#10161]
my magus Tzazaarnakon complete all first step off all bl quest which required kill the lairs bosses after log out this morning the reset quest bug happened and ALL quest i had had been resetted this also matter for epic quest all got cleared as if i never done any quest.

Thus i also have to re kill all the bosses to re take the second part for get the token for BL pocket

This also alredy happened once on my chosen Tesq

I could bet fault is from the dw BL quest (probably a bug due the fact that is repeatable) because it happened exatly the same on my chosen after be completed and all be at second step it resetted evrything and not when i skipped and done that dw quest for last

I suggest PPL do the second step of the DW quest for last when the other 4 first part alredy been completed

EDIT: idk what happened  after reloggin few sec ao quest all got back at the same step as before regardless may be worth of investigate as this happen only with BL quests and is not the first time.

**Comment by munkwards** [comment]
My IGN is Munk and have encountered the same problem. I logged in this am and had my quest log cleared as well as my AH mailbox cleared.

**Comment by Lheana** [comment]
Seems like a temporary bug, that a relogg fixes, so I close this.

**Comment by Tesq** [comment]
it didnt reset with a relog at the time, if no fix hasen't been found it will still soft reset step 2 and saved tome quest, true that it MAY fix itself after a while still you can do again till it fix quests which should give you unique rewards such epic quests, tough  i image is not a so broken thing now that sov is bis gear.
