### ISSUE TITLE
Infinite Supplie Dropps at Keep

### ISSUE THREAD

**Issue by donsastre** [WarEmu/WarBugs#10169]
Dear Dev,

i allready reported it to a GM and now posting it here! I reported directly after i noticed it and did it just for reproduction of the screenshot as mentioned (3-5 times) in the PM to the GM. (before lock of DW)

Bug:

I dropped the supplies at the Keep (DW Keep Order) and still had the blue beam on me so i tried to press the Flag inside keep again to get the beam away but suprisingly i could drop the supplies again and again... always same renownpoints and i think if i remember correct supplies for keep increased to...

after 6 Minutes i didnt dropped the supplies as well.

i hope this will help!!

greetings

p.s. i can send the screen via pm or the GM allready got one

**Comment by Lheana** [comment]
Already known and reported.
#9850
