### ISSUE TITLE
Catapult Orc Chapter 1 (Dregrot)

### ISSUE THREAD

**Issue by Zaphologist** [WarEmu/WarBugs#10173]
Hey there,

in the Orc Chapter 1 there was a Quest ( I think from Dregrot) to use the Catapult and shoot yourself up on the big Wall. Neither the Quest is to get, nor the Catapult is to use, to get up there. The Catapults I am talking about is at Lobber Hill. Maybe a portal up to the wall is an option, because on your minimap you can see, that on that wall is an available quest giver (first orc trophy).

Thank you guys!

Blood for the Bloodgod, Skulls for the Skullthrone and Milk for my Khorneflakes
Zaph

**Comment by Lheana** [comment]
The action with catapults is not implemented yet.
You can nevertheless reach the top of the wall going through the mountains. Here you can find tip to start the climb, look at 'Ironmane's Lock': https://wiki.returnofreckoning.com/index.php/Mount_Bloodhorn_History_and_Lore

**Comment by Zaphologist** [comment]
Oh nice, thanks! So I will start the climb ;)

**Comment by Natherul** [comment]
fixed in next patch

**Comment by sioding** [comment]
Fixed with patch from 28.09.2019
