### ISSUE TITLE
chosen\kotbs auras

### ISSUE THREAD

**Issue by Glohroc** [WarEmu/WarBugs#1017]
1.Auras stop working after changing location or rested. 
2.Chosen`s aura Discrodant Fluctuation doesn`t damage everytime when being hit by magic spell. It works 1 time from 10,

**Comment by Titoos** [comment]
ad 2. "...doesnt damage everytime when being hit by magic spell." - and it shouldn't.
"This effect will not trigger more than once every 3 seconds"..

**Comment by Glohroc** [comment]
Well, sorry for missing that part, it does changes my question a bit, but then it looks like aura triggers once per 3 seconds not for every single player that hits me, but it triggers once per 3 seconds globally. So for example-If player Jimm hits me and Aura damages him back, players Johny, Pete and Will can hit me with magic spells for 3 seconds after Jimm`s hit without taking damage from Aura.

**Comment by Radiantknight** [comment]
"This effect will not trigger more than once every 3 seconds"..
where is it said? it's not in the description of aura here: http://warhammeronline.wikia.com/wiki/Discordant_Fluctuation
But still, some guy says about tick on forums, the other BW says something in bugtracker, then you add, but I seem the only one to actually look it up around the web and put some proof.
The "once per x seconds" is usually stated in description for tactics, not abilities, but even if so, it is reflected in tooltip.

**Comment by ozarmidrashim** [comment]
Discordant Fluctuation was changed specifically because AoE casters were noticing that they were getting absolutely hammered by the damage from it. I think they're more than capable of telling whether Discordant Fluctuation has a retrigger interval or not.

**Comment by Evildoor** [comment]
As of 19.09.2015, auras persist through death and zone change (not sure what "rested" means).
Second problem is different and, since we have a disagreement, it is now more of a balance decision rather than bug - and should be discussed on forum (this was already done, IIRC) and not here. Therefore, i'm closing this.
