### ISSUE TITLE
Quest Blighted island order side "artistry of war" wrong red circle + can't recruit shield bearers

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#10174]
spearmen recruited 4/4
shield bearers recruited 0/4

"shield bearers must be the "young elf" in the village of lacorith 36.37

red circle show only spearmen area for shield bearers (around 41.39) the correct red circle area for spearmen should be in the village of lacorith (around 36.37)

See quest description.

**Comment by thorbolt80** [comment]
Can't take reward also...
![thorbolt_072](https://user-images.githubusercontent.com/16274785/34097657-17a8edf0-e3da-11e7-8e02-c6e99067465d.jpg)

**Comment by sioding** [comment]
Sorry @thorbolt80  - but i can´t follow your suggestions that the young elf´s should be shieldbearer. The quest text is fine: 
_Recruit the Hunters in the Swale of Miralei to the east and southeast to serve as Spearmen. Recruit the Armor Smiths in the village of Lacorith southwest of Adunei to serve as Shield Bearers. Return to Eronin Shorewind in Adunei when done._
And i got also my rewards.
