### ISSUE TITLE
quest bug the lords game 

### ISSUE THREAD

**Issue by normanis** [WarEmu/WarBugs#10170]
hello maby its not bug byt supousto bee like that byt it was suspicious for me dps helmet provides armor byt healer helmet provides ap regen . both are for disciple of khaine . dok dont use much ap for healing
![visenia_002](https://user-images.githubusercontent.com/23311386/29249353-4b479b00-8036-11e7-81ab-c70ac92034a0.jpg)
![visenia_001](https://user-images.githubusercontent.com/23311386/29249352-4b4482d0-8036-11e7-9278-1860f97c0977.jpg)

**Comment by sioding** [comment]
Ok this is no bugreport. this is a question - and for sure do dok´s use AP for healing. so it is intended. Close.
