### ISSUE TITLE
Quest "means of betrayal" order side Saphery missing second red mark

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#10188]
There is no red mark for the second part of the quest :

Return to sonsea stormfire 1/1   : fine
Acquire luminescence stone 0/1  :  (no red mark)

**Comment by thorbolt80** [comment]
![thorbolt_098](https://user-images.githubusercontent.com/16274785/35195104-c0f9545e-febe-11e7-82bb-d65b5569cd75.jpg)

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 31.03.2018
