### ISSUE TITLE
Slayer rage

### ISSUE THREAD

**Issue by Toldavf** [WarEmu/WarBugs#1018]
It seems to drop off far to quickly it should be a very gradual drop off.

**Comment by Chummi** [comment]
Slayer rage works exactly how it did on live. 
~ Bretin

**Comment by Toldavf** [comment]
No it really doesn't it takes giant bites of the rage in one go instead of a gradual down tick. Every movie I can find supports this.

It currently drops off in 5 ticks it should be more like 20.

**Comment by ozarmidrashim** [comment]
Yay for buffing Slayer.

**Comment by ropuch** [comment]
Uhm, then maybe it was broken on live, too? On BG after hitting flee Hate is dropped instantly to 0, and morale starts to go down just as tooltip says. And I'm pretty sure it is the same as it was on live (for BG). Flee is working the same for Shaman, DoK, WE and Sorc  (and their order-mirrors, I suppose) - instantly dropping career points. It does not prevent gaining them back, but all career points hit 0 after you flee.
Why Flee for Slayer/Choppa should work different? It's core skill, the same for all classes. I perfectly understand using it (with AP pots) to close the distance, but this seriously looks like a unresolved bug from live. Slayer/Choppa have their rage exhaust mechanic (which both can suppress by Wot Rules?/Power Through, at certain risk/cost) - and now you want to grant them "Oh, I'm so enraged that I feel like cooling down just a tiny little bit" at the cost of AP pot ;-). Apart of "Flee" working differently  on other classes, this is also messing with Slayer/Choppa  rage/chop/exhaust archetype ;/

**Comment by Evildoor** [comment]
This issue is about rage out of combat. #2309 is about rage on Flee.

**Comment by Chummi** [comment]
well i checked the videos and you're right, my bad. since it does not feel clunky or bugged at all i might got confused (it has been a while you know).
