### ISSUE TITLE
Avelorn : Dryad Oldback dissapear ?

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#10187]
According https://wiki.returnofreckoning.com/index.php/Chip_Off_the_Old...

The dryad should be in Avelorn at 32.5k 46.5k.

There is nothing more here only "fiendish talon"

According to #6758 Look like the unlock can't be fixed.

May be should update ror wiki?

Thanks in advance.

**Comment by Lheana** [comment]
![anaehll_373](https://user-images.githubusercontent.com/11537611/29309730-527eade8-81ab-11e7-9ae3-bc4497b5c570.jpg)
Oldback is not easy to find but she is there. The unlock works perfectly, the ToK tactics are just not working yet.
