### ISSUE TITLE
Quest "defensive fire" order side Saphery missing second red mark

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#10189]
There is no red mark for the second part of the quest :

bloody sun boyzs 10/10  : fine

Kill Yukha's boy 0/4 : no red mark for the second part

**Comment by thorbolt80** [comment]
The red mark should be around 32.44 where they are some  Yukha's boy

**Comment by sioding** [comment]
fixed with next boot

**Comment by sioding** [comment]
fixed with patch from 31.03.2018
