### ISSUE TITLE
Eataine 41.5 "rageclaw harpy" spot some untargetable and/or not attackable

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#10193]
Around 3 or 4 are not attackable or/and attackable. At least One "rageclaw harpy" to the South of the spot and one inside the small wood towards North. (be careful) this is not 37.13 harpy spot who works well.

**Comment by Lheana** [comment]
There is not any harpy at coord 41k 5k. The only spot I found around was at 40.4k 11k and I can target/attack all harpies there.
