### ISSUE TITLE
Update please "ceylnath vineyards" order PQ Eataine

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#10192]
Stage 1 works now ! 
but on stage 2 the hero "forlak" (giant skin) pop and he is not targetable and he should pop on stage 3

Stage 3 work fine

See also #6920

**Comment by Paleolog77** [comment]
Stage 3 does not work. Mistress Valira & her channelers are impossible to attack
![2021-11-14_16-21-38](https://user-images.githubusercontent.com/23325288/141683234-853ecad3-fdc4-43de-9fb3-0a34a0639de8.png)
.

**Comment by Lheana** [comment]
Don't hesitate to open a new ticket when the ticket has been closed because it was fixed.

**Comment by Lheana** [comment]
This has been fixed some time ago.
