### ISSUE TITLE
Lordling Title on low Character

### ISSUE THREAD

**Issue by chouxfleur** [WarEmu/WarBugs#10202]
I have a Level 5 Character with the Lordling Title
![level_001](https://user-images.githubusercontent.com/13787774/29377409-0b940858-82bc-11e7-9af3-96eed4eb1e1c.jpg)

**Comment by Lheana** [comment]
It shows 'Renown Rank: 40'. Is it still like that after a relog?

**Comment by chouxfleur** [comment]
Its still there and i just saw i have 1 Mastery Point to spend.
![level_002](https://user-images.githubusercontent.com/13787774/29411051-8efe0fda-8353-11e7-8301-64c1b725f6e0.jpg)

**Comment by Lheana** [comment]
Is your Renown Rank 40?

**Comment by chouxfleur** [comment]
Renown Rank is probably 5 cause i only have 5 to spend but it grants me an extra Mastery Point from shown Rank 40. Only played a few Scenario with this Character.

**Comment by Lheana** [comment]
The bug was not the title but the fact you had your renown rank 40.
