### ISSUE TITLE
Can not talk to Grumlok

### ISSUE THREAD

**Issue by ncarreiro0619** [WarEmu/WarBugs#10209]
I am currently doing my T3 Greenskin epic quest line and i had to travel to the IC to speak with Grumlok. For some reason I can not speak on him after clicking him. After a minute or so of clicking him he then disappears. I have tried logging out and closing the game twice. Upon log in he is back but still unable to click him for quest turn in.

**Comment by HtGeist** [comment]
I am on Grumloks Reward part of the last and 4th skaven token uest,and big green mcfarty pants wont talk,has yellow quest completed but right clicking him,he farts the cloak vavers and he dissapears after 10 seconds nothing happens.stuck...

**Comment by ncarreiro0619** [comment]
Here is a video of the issue: https://www.youtube.com/watch?v=MJB8RadcNkM

**Comment by mwasp** [comment]
yeah T4 epic quest line in Time to waaagh  Grumlok npc is not able to speak then disappears....

**Comment by ncarreiro0619** [comment]
Logged in this morning. Problem is fixed, I was able to turn in and continue the quest line. Thank you !
