### ISSUE TITLE
double seal of paragon from zone flip

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#10204]
let me explain normal zone flips and mail system first.
1.
![normal_seal](https://user-images.githubusercontent.com/19988772/29405489-06158510-8379-11e7-9bf4-32020e44aee2.jpg)
if you're in the same zone when zone flips you get medals and seals. it goes directly to your bag.
mail is not sent.
2.
![absent](https://user-images.githubusercontent.com/19988772/29405798-ee323d5c-8379-11e7-9023-2e549c885e31.jpg)
this is absence rewards.
when you login, if you had contribution but zone was NOT flipped, you get only medals from mail.
3.
![absent_seal](https://user-images.githubusercontent.com/19988772/29405985-97882146-837a-11e7-9372-86cfab776dec.jpg)
contribution remains 1 hour from last contribute.
when you login, if you had contribution AND zone was flipped, you get both medals and seals from mail.
this is also absence rewards but, with zone flip. 
so 1, 2, 3, are normal.

here is double reward issue.
![double_seal](https://user-images.githubusercontent.com/19988772/29406500-38a008fe-837c-11e7-8345-b200b0b36771.jpg)
I was not in the same zone when it flips. 
you get seals directly to your bag. AND you also get mails. 
this is the issue i wanna report.
compare this with normal reward in 1 plz.
if I was in same zone reward should be 2 medals and 5 seals.
instead I fly to other zone just b4 it flips and got 2 medals and 10 seals.
5 seals from direct, plus 2 medals and 5 seals from mail. 
I think mail is fine. direct reward of seal is problem.

ps. previously I thought joining SC was causing bug. but it was not. just being in different zone was causing double drop.

**Comment by Razielhell** [comment]
#10154

**Comment by Torquemadra** [comment]
thanks for the steps

**Comment by anarchypark** [comment]
you need 1,5k~2k rp from flip for at least 1 medal in order to get mail.
no medals = no mail
