### ISSUE TITLE
Orb of Cadaith not working - Dragonwake

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#10215]
The Orb of Cadaith (100 feet) south east of chapter 18 high elf (Dragonwake, 48.22) is supposed to teleport you to its counterpart in the tower underground.  (Dragonwake, 7.25).

It is supposed to work by right clicking the orb, which was I think a 3 second cast, and then you teleport to the other one.

**Comment by Lheana** [comment]
The Orb of Cadaith in High Elf Chapter 18 will now teleport players to the other Orb of Cadaith inside the tower, and vice versa.

**Comment by sioding** [comment]
Fixed with patch from 1.12.2017
