### ISSUE TITLE
Wrong outgoing heal after Guidance buff

### ISSUE THREAD

**Issue by Kaloell** [WarEmu/WarBugs#10226]
When getting the Guidance proc from beastlord, the outgoing healing is increased to 1.06. But after the buff runs out it becomes 0.99999999 instead of 1 (or going back to not being displayed).
![kalell_046](https://user-images.githubusercontent.com/29151272/29493716-ff659bfe-859b-11e7-8ae7-5cb9dcae1dbc.jpg)

**Comment by Torquemadra** [comment]
no difference in actuality
