### ISSUE TITLE
skaven engineers suck

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#10230]
the portal to the skaven maze in altdorf is broken and just takes you back to your rally point (no idea if this is the same for des toons)

**Comment by Lheana** [comment]
Tried the 4 portals related to Altdorf skaven zones, they all worked.

**Comment by MightyPhred** [comment]
i got into grovod cavers and the junk running place just fine, every time i try to jump into the maze it throws me back into high pass warcamp

**Comment by Lheana** [comment]
So you try to use the portal in Altdorf at 26.3k 33.2k in the Market next to dwarf "Mining Overseer Kamrod", and when you try to use it, it teleports you to High Pass?

**Comment by MightyPhred** [comment]
yup, tested it again just now, the market square portal gives me the standard loading screen with "outer dark" written on the book page, then it fades very briefly to black and comes up with another load screen for high pass, and then dumps me out in the warcamp, which is my current rally point

**Comment by Lheana** [comment]
What level are you?

**Comment by MightyPhred** [comment]
i think i was 26 the first time i tried it, 29 when i tried it most recently

**Comment by MightyPhred** [comment]
ah, im now level 34 and its just let me in

**Comment by MightyPhred** [comment]
and now im level 36, offered to help someone and the portals f***ed again

**Comment by Lheana** [comment]
Should be fixed next patch
