### ISSUE TITLE
Infinite delivery of a flag

### ISSUE THREAD

**Issue by petro3x** [WarEmu/WarBugs#10236]
![imbalance_005](https://user-images.githubusercontent.com/31226404/29542197-114d20f2-86e2-11e7-96c8-0222634b303d.jpg)

![imbalance_004](https://user-images.githubusercontent.com/31226404/29542178-f7ec8e18-86e1-11e7-973c-7d7b1bc4d785.jpg)

![imbalance_003](https://user-images.githubusercontent.com/31226404/29542173-f5136054-86e1-11e7-99a1-d49394c0caad.jpg)

![imbalance_002](https://user-images.githubusercontent.com/31226404/29542172-f2a30a68-86e1-11e7-9a86-327921bb3e19.jpg)

![imbalance_001](https://user-images.githubusercontent.com/31226404/29542170-efdcc56c-86e1-11e7-98f9-330659e8e217.jpg)

![imbalance_000](https://user-images.githubusercontent.com/31226404/29542167-eae45444-86e1-11e7-9f0c-7e511844ebc3.jpg)

If to stand still emergence of resources and to click on him with a mouse at once to take a resource that it is infinite and he can be handed over infinitely
I wrote about Google of translitas as I don't know English. My login in the game petro3x

**Comment by Lheana** [comment]
Already reported #9850
