### ISSUE TITLE
Apostle's Tome of Zeal

### ISSUE THREAD

**Issue by Kults** [WarEmu/WarBugs#10233]
Hello,

The **level 34 Apostle's Tome of Zeal** which you can buy for Officer's Emblems provides only **+4 Righteous Fury** each second, while the level 29 and 39 offer +8 RF/s. 
The Titan's Tome of Zeal, level 34 from the same vendor gives +6 only.

**Comment by SecretsOTheP** [comment]
https://gaarawarrgabs.wordpress.com/2010/06/03/the-weapons-of-war/ This lists the RF amount as 6. Titan's Tome of Zeal is listed as +8. Updating these accordingly.

**Comment by Torquemadra** [comment]
set to 8
