### ISSUE TITLE
Quest: "spotting trouble" Altdorf. "The floating corpse" too far to be clickable and no red mark

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#10244]
Floating corpse is at 38.38 but not reachable. Too far away for clicking and he got no red circle on the map.

Find floating corpse 0/1

**Comment by sioding** [comment]
fixed with patch from 2.3.2018

**Comment by sioding** [comment]
fixed with patch from 2.3.2018

**Comment by Paleolog77** [comment]
The next part of this questline. Need kill Warprot Stormvermin 0\8 in Altdorf's sewers. Kills are not up.
![paleo_000](https://user-images.githubusercontent.com/23325288/50656945-fec73780-0fa5-11e9-9984-63049c6917f6.jpg)

**Comment by Paleolog77** [comment]
yes, i have

**Comment by Paleolog77** [comment]
![paleo_001](https://user-images.githubusercontent.com/23325288/50657922-da208f00-0fa8-11e9-9d35-91c5c3a31f27.jpg)

**Comment by Paleolog77** [comment]
The same situation with quests "Spotting trouble", "Tasty Morsels", "Rat man?" & i'm affraid "Poor Gustav"

**Comment by Paleolog77** [comment]
![paleo_002](https://user-images.githubusercontent.com/23325288/50658773-79468600-0fab-11e9-8440-813457e95c18.jpg)

**Comment by Paleolog77** [comment]
![paleo_003](https://user-images.githubusercontent.com/23325288/50658982-24efd600-0fac-11e9-8fe3-0f62c15077ad.jpg)

**Comment by Paleolog77** [comment]
100% four quests not work "Spotting trouble", "Tasty Morsels", "Rat man?" & "Poor Gustav". In addition to everything, quest "Poor Gustav" makin' at middle sewer, but it not sowes on map.

**Comment by Paleolog77** [comment]
![paleo_004](https://user-images.githubusercontent.com/23325288/50659173-d262e980-0fac-11e9-8232-1809b3e0919b.jpg)

**Comment by sioding** [comment]
Issue locked. This is not the forum
