### ISSUE TITLE
Debolster in t1 potions bug

### ISSUE THREAD

**Issue by HtGeist** [WarEmu/WarBugs#10240]
drank a 1hour armor potion and 1 hour stamina potion lvl 15 at elf t1 warcamp,took portal to house of loryndyt or whatever...timer counted down from 10 and i got bolster...lvl 15 and field of glory and gone were my potions..checked stats and .getstats no effect from potions anymore...drank new ones..they stayed up...till i moved to dwarfs t1 and went into rvr lake,potions dissapeared no effect...

**Comment by sioding** [comment]
Since debolster is gone and won´t come back - close

**Comment by Oculta** [comment]
This problem is not solved yet. I have teh same issue with my shaman lvl 35 ... everytime bolster comes up the potion / effect was gone.
