### ISSUE TITLE
Bug in Logrin's Forge

### ISSUE THREAD

**Issue by GarquiIII** [WarEmu/WarBugs#10249]
I've found a way to get under/out of the map in the scenario Logrin's Force. From there I was able to shoot  ennemis while being unkillable. tried it several times, worked perfectly.
I showed (GM)Gambero the way to do it because it's kind of hard to explain.
( You have to get between a bunch of kegs and a wall, after that you will fall in the lava just under the map, from there you can run out of the map or just shot players from the bottom !)

Hope I helped,
have a nice day
Garqui

**Comment by Kaelang** [comment]
Appreciate this is an older report - however the lack of information here makes this almost impossible to replicate without having to guess what this report is for. Please re-open with more information if this issue persists.

Closing.
