### ISSUE TITLE
Quest in Barak Varr

### ISSUE THREAD

**Issue by gigibengal** [WarEmu/WarBugs#10248]
The quest named "Kill Dem All" from Greenskins Chapter 8, given by a goblin (don't really remember his name) has to be turned in at another goblin named Gnashfang after killing the dwarfs it asks me to kill, but when I click on complete in the dialogue with Gnashfang it does nothing. On the minimap i can see the completed quest sign but above the goblin there's none. The quest also says it gives only experience, nothing else, no item or money.

**Comment by SecretsOTheP** [comment]
This seems like it should work. Make sure you kill both of the dwarf guards plus the dwarf with a name.

**Comment by NorKalli** [comment]
fixed NPC so overhead quest icons display

**Comment by sioding** [comment]
fixed with patch from 26.05.2018
