### ISSUE TITLE
BW Tactic Searing Vitality not working

### ISSUE THREAD

**Issue by Morrdread** [WarEmu/WarBugs#10255]
The tactic is supposed to heal BW for 67% of damage done. I specced into it today and it has not worked all day. Thank you.

**Comment by Torquemadra** [comment]
of the damage that SEAR deals

**Comment by gittoaster** [comment]
It works for me.  I haven't tried in last week or so, but it surely works.  You can see in scenarios or by using addon WSCT.

**Comment by Haojun-Phalanx** [comment]
it's working.

**Comment by Morrdread** [comment]
Sorry for delay in getting back to this. I manage a Viking historical settlement on the weekends.

 I tried it again, and still did not get a heal from it
![wardoctor_002](https://user-images.githubusercontent.com/18380142/29798085-cefbbd02-8c28-11e7-9463-8926f6b03631.jpg)
I uploaded a screen shot.

**Comment by Morrdread** [comment]
Sorry for delay in getting back to this. I manage a Viking historical settlement on the weekends.

I tried it again, and still did not get a heal from it
![wardoctor_003](https://user-images.githubusercontent.com/18380142/29798215-b935dc54-8c29-11e7-9f0f-41aa24f2d9b3.jpg)

**Comment by wargrimnir** [comment]
It's working, kind of. It deals negative damage.
http://i.imgur.com/PUXSneN.png

**Comment by Morrdread** [comment]
Wow I dint even notice that

**Comment by sioding** [comment]
Searing Vitality works fine

**Comment by dalen** [comment]
I tried it out, but it is healing for way less than 67% for me (sometimes the heal is even mitigated according to combat log).

![faliniel_000](https://user-images.githubusercontent.com/7400/49689689-03263f00-fb25-11e8-9fb3-93ea6ea2b14a.jpg)
![faliniel_001](https://user-images.githubusercontent.com/7400/49689690-04576c00-fb25-11e8-8833-63c5c70ef391.jpg)
