### ISSUE TITLE
Unable to turn in quest Daemon's Gate

### ISSUE THREAD

**Issue by Blipinator** [WarEmu/WarBugs#10253]
Empire Chapter 16 
Quest: Daemon's Gate

  Quest objective is to find Walram Kappel.  He is in the correct location.  Killing him completes the objective.  However, quest guide initially seemed to indicate he is also the entity to turn in the quest to.  After re-logging there is now no map marker for turn-in.

**Comment by sioding** [comment]
Checked that - you are able to speak to him to finish the quest - so close
