### ISSUE TITLE
'Zone 0' Bug

### ISSUE THREAD

**Issue by Aurenia** [WarEmu/WarBugs#10254]
After leaving a scenario I returned to Ostland when suddenly my character was in 'Zone 0'. The interface is still there but there is nothing but the sky around my character and I could still open the map to view Ostland, however I could not see my  character marker on the map. I typed in '.u' which worked momentarily before I was transported back to 'Zone 0', I attempted this 3 times but each time I was back in 'Zone 0' within a few seconds. 
![aurenia_002](https://user-images.githubusercontent.com/31326995/29692113-4e7b3ca2-8926-11e7-8cd6-917958d47141.jpg)

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
