### ISSUE TITLE
Warband Green dots on Map not showing up - Bug?

### ISSUE THREAD

**Issue by GentleN** [WarEmu/WarBugs#10265]
The members were currently on Bligted Isles and Chrace, but can't see them anywhere on the map, besides the mini map.

![girgurdatuff_043](https://user-images.githubusercontent.com/30581957/29743439-186b3fda-8a8a-11e7-8481-4ad5ff0ce555.jpg)
![girgurdatuff_044](https://user-images.githubusercontent.com/30581957/29743441-1b5b4f82-8a8a-11e7-8213-7f89aecf6512.jpg)

**Comment by MaxHayman** [comment]
@sioding is this fixed?

**Comment by sioding** [comment]
fixed with patch from 1.12.2018
