### ISSUE TITLE
Cannot return resources.

### ISSUE THREAD

**Issue by Zxul** [WarEmu/WarBugs#10267]
When I clicked on Destruction Resource Drop item in Reikland castle, I got message "NullReferenceException was thrown from SuppliesReturned".
After that, when trying to use the item again, whatever in castle or by WC, I got message "Lxul is already interacting with this item" (Lxul being my character name).
Asking in t4, apparently others couldn't return resources as well.  
![image](https://user-images.githubusercontent.com/31373407/29743848-0b34cdf0-8aa2-11e7-8099-420336380432.png)

**Comment by sioding** [comment]
Since there is a new OrVR system without users have to carry resources i will close this now
