### ISSUE TITLE
Quest: Chaos Starting Zone (Norsca); "The Dark One"

### ISSUE THREAD

**Issue by powermetalEm** [WarEmu/WarBugs#10269]
Minor Bug in "The Dark One":

Once you kill the Felhorn Gor the track on the map/mark on map for the quest disappears and does not reappear. There is no quest map marker for the bloody pike and Braewold portions of the quest.

I tried checking and unchecking the box next to the quest AND separately on the map. I tried relogging. I tried removing all my tracked quests but The Dark Ones. All had the same result.

Reading the whole quest makes your objective clear. Just reporting the missing functionality.

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 31.03.2018
