### ISSUE TITLE
[PQ NPC] Last stage "boss" missing animation.

### ISSUE THREAD

**Issue by Irontoof** [WarEmu/WarBugs#10261]
Good evening, Dev team,

Yesterday I was farming influence for Dwarf chapter 21, and found this easy PQ, named Magister Dhetal in Black Crag. 
![archbishop_096](https://user-images.githubusercontent.com/30251290/29738271-caccb9b8-89ec-11e7-83d3-f885c00462ad.jpg)

At stages 1 and 2 all is good and working as expected until stage 3, when the objective is to kill Magister Dhetal himself, his NPC is motionless, without any animation, it only floats to your position and does not display attack or death animations. Did the PQ about 3 times to verify, all had the same result.
![archbishop_080](https://user-images.githubusercontent.com/30251290/29738288-2838063e-89ed-11e7-9ae2-15fe5c8fc8af.jpg)

![archbishop_079](https://user-images.githubusercontent.com/30251290/29738304-2ebf5a84-89ed-11e7-9f3b-0fd8f734c1f8.jpg)

Another thing that got my attention was that, no matter how close I got to the "boss" NPC, to add to the lack of animation, it also displayed a red status on my skill bar, like If I couldn't attack him, even displaying the target is not attackable screen warning, but I could still attack him nonetheless.
![archbishop_083](https://user-images.githubusercontent.com/30251290/29738337-573e9564-89ee-11e7-9e65-2433926eaa41.jpg)

That's my report for now, wish you a great weekend.
Until the next one!

**Comment by Lheana** [comment]
#10143

**Comment by Lheana** [comment]
Fixed next patch
