### ISSUE TITLE
Logrin's Forge - Keg jump location is not blocked

### ISSUE THREAD

**Issue by wdesu** [WarEmu/WarBugs#10262]
All jump locations that allow you to get on higher parts in this scenario are blocked by invisible walls except for this one, i think this inconsistency may be not intended.
![lf](https://user-images.githubusercontent.com/29466521/29740997-334f5890-8a6c-11e7-9f43-d41a15de7115.jpg)

**Comment by sioding** [comment]
Fixed long time ago
