### ISSUE TITLE
DPS zeal 4K Tzeentch's Cry

### ISSUE THREAD

**Issue by retkeszaju** [WarEmu/WarBugs#10266]
Pretty much the tile say all it. i made 4000 damage hit whit that spell which is way beyond normal, i can't really give any hint what could trigger this out, i had all my stuff regular, i post a screen, where i stood and jumped toward the end of the brdige where WL was, than hit my spell in the air, WL died at near the bridge end
Also he killed me a couple of minutes ago, if that can interference whit anything
http://imgur.com/a/pIk9s

**Comment by Kaloell** [comment]
I can't find the official post right now, but if I recall correctly your damage is increased (ten fold?) while you are in your warcamp, to help the guards kill those pesky, overextending enemies.

**Comment by retkeszaju** [comment]
hm aint knowed that, ty
