### ISSUE TITLE
Shaman 3rd Dot Getn Smarter

### ISSUE THREAD

**Issue by Wabnappa** [WarEmu/WarBugs#10273]
Hello im dont playing half a year and then return find something stange. 
![wabnappa_000](https://user-images.githubusercontent.com/31390633/29752921-563a82fc-8b80-11e7-9620-99341be404bc.jpg)

**Comment by wargrimnir** [comment]
Do you think this is unintentional for some reason? At very least search the forum before you post "bugs" like this.
