### ISSUE TITLE
Serpent Passage - Stuck behind crashed boat

### ISSUE THREAD

**Issue by CountTalabecland** [WarEmu/WarBugs#10276]
The other day I was super-punted by a Black Guard away from the ship part spawn and over the wreckage of the ship. This caused me to become stuck in the ground and .u could not get me out. I had to end up using the book of binding to leave the scenario since even destro could not be bothered to come kill me back there :D.

![brynnoth_009](https://user-images.githubusercontent.com/31392662/29753998-7dd0ab7c-8b42-11e7-822d-616dee159ad2.jpg)

**Comment by sioding** [comment]
Fixed with Hotfix from 29.04.2017
