### ISSUE TITLE
No conqueror piece on Bag

### ISSUE THREAD

**Issue by Kikrin** [WarEmu/WarBugs#10279]
I opened the bag and there was no conqueror piece inside, as shown on the screenshot
![mattdamon_002](https://user-images.githubusercontent.com/31110323/29755042-2951f712-8b89-11e7-8e91-204e54266891.jpg)

**Comment by Razielhell** [comment]
#9263

**Comment by sofronguy** [comment]
Empty gold bag from Caledor lock @ 19/10/2017 (locked by order). Got the bag via mail at IC after the lock (if that matters).

![snipp_000](https://user-images.githubusercontent.com/30108162/31778934-9ec195da-b4fa-11e7-94e6-42d8e11f7bed.jpg)

**Comment by sioding** [comment]
No bag in Mailbox is fixed
No conq item in bag is fixed
Close this for now.
