### ISSUE TITLE
Finish 'em Off

### ISSUE THREAD

**Issue by TheRealJurki** [WarEmu/WarBugs#10289]
Finish 'em Off has a quite long delay between casting the ability and actually dealing damage. the gap between it is that large that sometimes you have to cast the ability when the target has still 50%: because of the delay your dots and other abilities will let the targets health drop to 25% and THEN the damage of finish em off will actually hit the target and deal the extra damage.  its even possible to cast finish em off first and then the explosive arrer but the explosive arrer is still hitting the target first

**Comment by grunbag** [comment]
Fixed
