### ISSUE TITLE
Missing Money

### ISSUE THREAD

**Issue by VonEpic** [WarEmu/WarBugs#10281]
I didn't notice right away when it happened, but as last I remembered I had 40+ gold approximately an hour before I noticed. Previously I did a little RvR then logged to create a new character, only to return back to my main shortly thereafter. Within about 15 minutes of being logged in I come across a merchant, attempt to buy something and when I look at the error messages popping up they read "you don't have enough gold" etc. Mind boggled, I check the inventory window, sure enough, only a few silvers from items I had just sold showed up. There were a few uncharacteristic lag spikes and two DC's (which never happen to me) earlier today but that was all before I noticed my money had gone missing.

**Comment by wargrimnir** [comment]
Without a reproducible process there's nothing for us to do here. Open another ticket in the future if you figure out what is causing it.

**Comment by VonEpic** [comment]
Yeah, I figured as much, just putting it in writing.
