### ISSUE TITLE
Scenario Talabec Damm issue 

### ISSUE THREAD

**Issue by Oculta** [WarEmu/WarBugs#10293]
If you grab the stone to move to the zone and you die with the bomb, you cant get on your horse in this scenario. 

I hope you have a look on it.

Great game i hope  i can help with this bugrequest

**Comment by Lheana** [comment]
Dying from explosion of the keg or by enemies?

**Comment by Oculta** [comment]
Both ... but it is fixed with the new patch. thx alot great wishes for the team
