### ISSUE TITLE
Big Choppa of Conquest

### ISSUE THREAD

**Issue by MadMask** [WarEmu/WarBugs#1030]
The Big Choppa of Conquest is considered as a 1H weapon whereas it's a 2H weapon.
It means that it uses a 1H animation and model and can't use 2H abilities.

It's a bit sad because it's a very nice weapon for Black Orcs and Choppas.

**Comment by Titoos** [comment]
I reported this in #861 
Small update: in fact 2h abilities are working, despite they are greyed, and the error message is presented.

**Comment by Evildoor** [comment]
You can use abilities despite the warnings like "Great Weapon required". Closing.
