### ISSUE TITLE
"Savage Bloodseekers" fail to respawn for quest

### ISSUE THREAD

**Issue by VonEpic** [WarEmu/WarBugs#10305]
![perturabro_070](https://user-images.githubusercontent.com/31397093/29838596-9bc1487a-8cc9-11e7-950d-6ab2ed0ddfcd.jpg)

Approximately 30 minutes and the Savage Bloodseekers have failed to respawn. The Quest is Allure of Rage and it takes place around the PQ "Tempest Horn".

**Comment by Lheana** [comment]
Has it been fixed?

**Comment by Lheana** [comment]
Works fine.
