### ISSUE TITLE
Norsca T1 Vampire Lair Doesnt Reset

### ISSUE THREAD

**Issue by Co1iny** [WarEmu/WarBugs#10307]
I watched the T1 vampire lair in the southern Norscan island in RVR since 6 am EST to 4pm EST. It was found dead and GM Gambero came to investigate, and suggested I write this report. Unsure how long it was dead or when it was killed that morning, we just know that it never respawned. Attached is a screenshot taken at the end of Gambero's visit, the vamp lay dead inside. Figured I might as well upload something to document the visit. 
![untitled](https://user-images.githubusercontent.com/31453772/29841338-0a435de8-8cd3-11e7-9758-320c832c4a2c.png)

**Comment by NorKalli** [comment]
previously fixed
