### ISSUE TITLE
Elven Shadow Warriors/Crystal Grove Scouts have no battle animations

### ISSUE THREAD

**Issue by VonEpic** [WarEmu/WarBugs#10308]
Elven Shadow Warriors and Crystal Grove Scouts (same model) engage in combat, switch to the appropriate melee or ranged weapon, and attack, but the animation (swing sword/drawing bow) does not activate.

![perturabro_078](https://user-images.githubusercontent.com/31397093/29841683-55e027a8-8cd4-11e7-8358-6973e038c182.jpg)

**Comment by sioding** [comment]
checked - everythings fine
