### ISSUE TITLE
T3 elf epic quest

### ISSUE THREAD

**Issue by Dragothurch** [WarEmu/WarBugs#10304]
Hi

T3 epic weapon quest "controll" not working. Gethlan Stormwood not give the quest. Pls repair when fot time, Thx.

**Comment by Razielhell** [comment]
What level are you?

**Comment by Dragothurch** [comment]
Hi.

I try pick up on lvl 22. Other 2 eoic quest i can pick up and doing some
stage just elf cant.

2017-08-29 15:56 GMT+02:00 Razielhell <notifications@github.com>:

**Comment by Dragothurch** [comment]
Hi!

Now im lvl 23 and i can pick up, so sry for bug report. im dont know the
different epic quest need different level for pick up. Sry and thx for
answer.

2017-08-30 6:24 GMT+02:00 Gulyás András <gugitok1978@gmail.com>:
