### ISSUE TITLE
T4 rvr lock reward bugged

### ISSUE THREAD

**Issue by panodill** [WarEmu/WarBugs#10300]
After many hours of fighting and alot of kills in zone the lock reward seems a bit low.
Dont know if the has been any changes, if thats the case i have missed that infromation.
![war_2017-08-29_00-05-33](https://user-images.githubusercontent.com/19293638/29796044-5a7a0bd8-8c4f-11e7-9795-3de965334543.png)

**Comment by panodill** [comment]
Happend more times now, feels like we are getting loser roll after winning zone

**Comment by sioding** [comment]
Since we have a new Bagsystem for ORvR i close this now.
