### ISSUE TITLE
Bugs in Highpass Tier 3 RVR

### ISSUE THREAD

**Issue by VonRugen** [WarEmu/WarBugs#10313]
![bres_003](https://user-images.githubusercontent.com/31458882/29849795-2a06c3bc-8cf7-11e7-8adc-a5308bafecb3.jpg)
Chaos fortress did not reset as of  7:50 PM EST 8/29/2017 and would not accept supplies for destruction in game, Keep had our npcs but did not reset properly.  Basically it was set as if the keep had been taken in icons, yet it had not, as the npcs etc had the gates working as normal and prevented dropping supplies

**Comment by sioding** [comment]
Since we have totally changes the open rvr campaign and there is no need to carry supplies i will close this now. Thanks for the report.
