### ISSUE TITLE
No Gear in Gold Keep Bag

### ISSUE THREAD

**Issue by Rhombutts** [WarEmu/WarBugs#10317]
![slagnarf_910](https://user-images.githubusercontent.com/13096975/29856568-b01c26a2-8d21-11e7-9638-4f62761e63d2.jpg)
Have no conqueror gear in my gold loot bag. My character's name is Slagnarf.

http://i.imgur.com/ptCD6sH.jpg

**Comment by Natherul** [comment]
same as https://github.com/WarEmu/WarBugs/issues/10279#event-1223391622
