### ISSUE TITLE
Empty (no conqueror piece) gold bag in Dragonwake defense 

### ISSUE THREAD

**Issue by sofronguy** [WarEmu/WarBugs#10315]
Natherul mentioned in the patch notes at 26/8/2017 that if we still get empty bags we should provide screenshot so he can gather data, so here it goes. It happened at Dragonwake order defense on 30/08/2017. Didn't reconnect/logoff until I received and opened the bag via mail. 

![abaq_000](https://user-images.githubusercontent.com/30108162/29851011-4cb7dd4a-8d3a-11e7-9032-a989c469228a.jpg)

**Comment by Natherul** [comment]
same as https://github.com/WarEmu/WarBugs/issues/10279#event-1223391622
