### ISSUE TITLE
[Quest Bug] Lionsbane Banner

### ISSUE THREAD

**Issue by HahnHolio** [WarEmu/WarBugs#1032]
2nd part of the quest your supposed to get the shield of Geathin Whitemane.
He is spawned, but does not drop the shield.
Killed him several times to be sure of a certain droprate, but nothing.
Image shows the quest entry and the killed mob.
![synergy_005](https://cloud.githubusercontent.com/assets/13593973/9018469/6ff7bee0-37df-11e5-9888-baaacc27554e.jpg)

**Comment by bobeer86** [comment]
still bugged as of 9/8/15

**Comment by Reggaewaldo** [comment]
I have made the arrangements to change this in the DB but I will have to verify the functionality when I have the time.

**Comment by Reggaewaldo** [comment]
Tested OK the change will be applied with the next hotfix.

Closing.
