### ISSUE TITLE
Theologians Quest in Chaos Wastes

### ISSUE THREAD

**Issue by VonEpic** [WarEmu/WarBugs#10321]
The watermark on the map shows a broad area which covers 2 of the 3 items required (Raven Phylactery and Frozen Corpse, both of which don't show up when the mouse is over the watermark) but the third item, Bones of a Bloodbeast, seem to be missing (Unless they were intended to drop from a Blood Spawn?). The only other interactive item found in the quest area is a "Ritual Cauldron" which does nothing at this juncture. The quest text is vague/curt and offers no specifics as to the location of any of the items.

![perturabro_135](https://user-images.githubusercontent.com/31397093/29902070-e14e10fc-8dc9-11e7-820e-da0d806e0310.jpg)

![perturabro_133](https://user-images.githubusercontent.com/31397093/29901977-3c6f4880-8dc9-11e7-8b60-e4802a6bd063.jpg)

**Comment by Lheana** [comment]
Bones of a Bloodbeast are at 12.3k 26k near the water

**Comment by Lheana** [comment]
Interacting with the bones of a bloodbeast finished the quest?

**Comment by VonEpic** [comment]
Affirmative, they were not "clickable" when I had come through the first two times. Must have been fixed by one of the reboots. Thank you!
