### ISSUE TITLE
Sweet Revenge IB tactic.

### ISSUE THREAD

**Issue by Ashton0007** [WarEmu/WarBugs#10323]
It doesn't display the 15% crit on character sheet. also tested it in a duel against my brother and found that i didn't crit more.

**Comment by Torquemadra** [comment]
Shows fine on mine, use .getstats and only adds 15% crit if over 50 grudge

![image](https://user-images.githubusercontent.com/16200780/29947139-21b30704-8e76-11e7-8c3f-1c924bfbc98b.png)
