### ISSUE TITLE
Destruction of the Weak PQ switched counters

### ISSUE THREAD

**Issue by VonEpic** [WarEmu/WarBugs#10320]
When killing Refugee Duelists, a tally is added to killing Gherig the Faithful's counter, and vice versa. It doesn't impair completion of the quest but it does show 12/1 Gherig kills and 1/12 kills of Refugee Duelists.

**Comment by VonEpic** [comment]
![brochete_026](https://user-images.githubusercontent.com/31397093/29883538-ad66f984-8d7e-11e7-9235-3ab48269a946.jpg)

**Comment by Razielhell** [comment]
#6935
