### ISSUE TITLE
Nobody Home in West Praag

### ISSUE THREAD

**Issue by VonEpic** [WarEmu/WarBugs#10326]
The respawn point in West Praag has no friendly NPCs, most importantly healer or flight master.
(I understand it's an area still under development.)

![perturabro_151](https://user-images.githubusercontent.com/31397093/29924546-4dbdf692-8e2b-11e7-84bf-1d80b2f845c0.jpg)

**Comment by Lheana** [comment]
Healer perhaps, but no flight master is meant to be in West Praag.

**Comment by VonEpic** [comment]
Ah, I assumed a flight master for outgoing, not incoming, flights would be available.

**Comment by VonEpic** [comment]
Reiterating the importance of this, there is no healer where you respawn, which is important now that dying during Ursa Domina (Beastlord) raid spawns you at this camp.

**Comment by wargrimnir** [comment]
Will change the respawn point, I assumed the one for the area would send
you to the nearest chapter camp.

**Comment by VonEpic** [comment]
Well, as in Death Peak, it sends you to a nearby Orc camp, populated with healer and some NPCs, this place looks like it should be a similar Chaos camp, it's just unpopulated. The nearby Chaos camp is only a few extra seconds away though so it shouldn't be a huge inconvenience to have to respawn there, though I don't know how far away Order is forced to spawn.

**Comment by Lheana** [comment]
This place has been populated few months ago.
