### ISSUE TITLE
Cauterize

### ISSUE THREAD

**Issue by Toldavf** [WarEmu/WarBugs#1033]
Cauterize doesn't seem to be able to cleanse a mara's snare

**Comment by ozarmidrashim** [comment]
The client thinks it's Damaging. Might have to replace the Debuff component with another Ailment snare.

**Comment by Evildoor** [comment]
https://github.com/WarEmu/WarBugs/issues/1339
According to ^, this cannot be fixed yet. Closing this issue since linked one is more correct (mara snare bug in general, not Cauterize bug).
