### ISSUE TITLE
Bolster.

### ISSUE THREAD

**Issue by Ashton0007** [WarEmu/WarBugs#10336]
If you debolster into t1 you become rank 45.

**Comment by Ashton0007** [comment]
Ok actually i think you are just rank 45 in t1 period.

**Comment by Ashton0007** [comment]
And you can solo the lairs apparently.

**Comment by Ashton0007** [comment]
Update: Im currently rank 16 standing at Festenplatz and am bolstered to rank 50.

**Comment by Jordjio** [comment]
No lvl 50 bolster after character lvlup in RvR zone. Effect restored after reenter/change zone.

**Comment by Hargrim** [comment]
Fixed, closing. Thanks for reporting.
