### ISSUE TITLE
The Mysterious M.B. Quest

### ISSUE THREAD

**Issue by VonEpic** [WarEmu/WarBugs#10334]
During the questline for "The Stunty Mystery - The Mysterious M.B.", It is impossible to reach the Rare Flask because the Redhammer Brewery is surrounded by level 55 NPC's that kill on sight, and the back door that I was able to sneak to is not a working door.

![perturabro_172](https://user-images.githubusercontent.com/31397093/29938995-7685e0c6-8e58-11e7-8ae6-8a0f0c25bdc0.jpg)

**Comment by Razielhell** [comment]
Fixed the door. Try again tomorrow please.

**Comment by VonEpic** [comment]
Sincerest apologies, apparently someone just put the item outside, not requiring you to go inside. Going off old information. Thank you.

**Comment by Lheana** [comment]
Indeed, there are 2 spawns for the Rare Flask; https://wiki.returnofreckoning.com/index.php/The_Mysterious_M.B.
