### ISSUE TITLE
Gork Sez Stop - works on (not moving) Keep Lords

### ISSUE THREAD

**Issue by rakels** [WarEmu/WarBugs#10338]
Don't know if it's a bug or a feature:

In some tanking constellations the shaman M1 "Gork Sez Stop" does damage on the keep lord (600 every 2 seconds). Compared to other attacks, this adds up pretty fast on these lords which have high defense.

![mobut_000](https://user-images.githubusercontent.com/9309339/29970683-c612c7f8-8f25-11e7-9f60-73c1a32c89c0.jpg)

**Comment by Scrilian** [comment]
Same thing happens to lion pets set to passive.

**Comment by Natherul** [comment]
keep lords are excluded for the the automatic refreshes with the next update
