### ISSUE TITLE
Broken Portal in IC

### ISSUE THREAD

**Issue by VonEpic** [WarEmu/WarBugs#10330]
Portal 168912104 in the star shaped arena in IC is broken.

![perturabro_156](https://user-images.githubusercontent.com/31397093/29933026-14e3020e-8e44-11e7-8e8c-40a7ea29d746.jpg)

**Comment by Lheana** [comment]
Portals in IC in the arena are for Sacellum dungeons, so it is intended they don't work as Sacellum dungeons are not implemented yet.
