### ISSUE TITLE
Marauder Bolstering + 1222 Ballistic Skill

### ISSUE THREAD

**Issue by Shaliaz** [WarEmu/WarBugs#10344]
Hi, my character has gotten 1222 ballistic skill with the new bolstering.

I've been told by a dev to report this bug here.

Character Name : Nephalem -- http://imgur.com/a/DgFXo

.Getstats results in RVR http://imgur.com/a/pvUAK

Outside RVR http://imgur.com/a/Z0yGT

**Comment by wargrimnir** [comment]
Include more details. Screenshots of combat log/tooltips. Use .getstats in and out of RvR.

**Comment by Shaliaz** [comment]
I will post out RVR stats in a minute.

**Comment by Shaliaz** [comment]
Is this intented or?im hitting ALOT with my throwing axes, i also shot some footage i'l edit and post it on the forums tommorow
