### ISSUE TITLE
Trap Door OUT of Horned Tower Not Working

### ISSUE THREAD

**Issue by VonEpic** [WarEmu/WarBugs#10340]
The secret river cave entrance works to bring you into the Horned Tower, but the trapdoor to exit is static.

![perturabro_208](https://user-images.githubusercontent.com/31397093/29973778-b4be7474-8efe-11e7-945c-00aadb8dfebe.jpg)

**Comment by Lheana** [comment]
You are meant to exist using the skaven portal on the top of the tower. That's not because there is an appearance of door that it is a real door that is meant to be usable.

**Comment by VonEpic** [comment]
Ah. Gratsi.
