### ISSUE TITLE
Oil is not doing enough damage to matter in t2/t3 keep defenses.

### ISSUE THREAD

**Issue by sofronguy** [WarEmu/WarBugs#10349]
I was told that I should post this here as a suggestion/issue in light of the recent changes. 

The issue is that, at least from my experience, level 40 players can easily withstand/heal the damage done by light and medium oil, so much that in most cases it is not worth the gold (since you don't kill anything). 

Also, on that matter, is it intended for lowbie (non-40) players to not be able to damage siege machines/oil in t3/t4? Whenever they try their hits are blocked by the oil, ram, catapult etc.

**Comment by wargrimnir** [comment]
The second issue may be a side effect of the powerleveling restrictions.

**Comment by sioding** [comment]
Should be fixed with patch from 13.10.2017. Please post here, if its not solved properly.
