### ISSUE TITLE
Skaven Quest Area Issues

### ISSUE THREAD

**Issue by VonEpic** [WarEmu/WarBugs#10341]
The skaven [quest and] portal in Inevitable City, and the portal atop Horned Tower in Talabecland take you to Outer Dark/Dangerous Area, but immediately upon arrival send you back to your rally point, rendering the last two parts of the skaven questline for the tokens inaccessible. (Both the skaven obstacle course in IC and the skaven cave in High Pass questlines work.)

**Comment by Lheana** [comment]
Have you tried the portal in IC for skaven maze (at the north of IC, just before the citadel) today?

**Comment by VonEpic** [comment]
Checking now.

**Comment by VonEpic** [comment]
IC portal is operating properly. Thank you!
