### ISSUE TITLE
Gromril Junction BO rvr zone

### ISSUE THREAD

**Issue by Scrilian** [WarEmu/WarBugs#10358]
There seems like there a few spots on the objective, in the middle of it, in Kadrin Valley that are not a part of RvR zone. It constantly causes issues with despawning any siege weapons nearby, esp. rams.

**Comment by saupreusse** [comment]
Just make sure you're no longer than 10 seconds underneath the bridge above the BO. It will be considered PvE Area and your siege will despawn.
