### ISSUE TITLE
Crash reboots PC

### ISSUE THREAD

**Issue by Waaughhammer** [WarEmu/WarBugs#10359]
Was away awhile due to very annoying connectivity issues.
Now am able to get back into game, so logged between toons to mark them as active, and to re-set-up my hotbars, which emptied themselves for some reason.
Can log to 5 or 6 toons to do this AOK, but then. . .

The screen goes beige for several seconds, with the PC being locked up, and then the PC, unprompted, REBOOTS into a NON-SAFE shutdown/restart.

I do have a new vid card, as old one got fried, but it is better card (4GVRAM).  Noting that WAR debug log shows 512 VRAM (presuming is default note saying minimum OK).

EDIT: (can't believe I forgot this) I am connecting via a different device, tho one superior to the old devices. Specifically, I am connecting, as I was before, through a directly-tethered phone with 4G connectivity. Tho it is a new phone, it generally gets very good connection speeds, far in excess of MMO requirements. 

I am avoiding relogging atm, as I do not want to induce further hard resets of my PC.  

Please note that I am NOT blaming the game or game staff, as ROR rocks and you guys are awesome, and it is probable the issue is here on my end, anyway, as no one else seems to be having it.  I am just very wary of potential HDD damage from unprepped reboots, and need to avoid logging until I can be sure ROR wont bounce my PC.

Please advise.  I can send DXDiag if you want, tho would prefer to mail it rather than attatch to ticket, in order to restrict my system info availability to ROR staff.   Thank you in advance, guys.

**Comment by wargrimnir** [comment]
Bugtracker is for in-game bugs, not technical issues. TBH, those issues don't sound like anything we would be able to fix anyway.
