### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ingurbard** [WarEmu/WarBugs#10355]
Hi guys it just happened today, for yesterday game was ok. Game lagged a lot during RvR battle in High Pass-Talabecland and then crashed, I opened launcher again and logged in, the game lagged and crashed again when destruction entered the keep, as I respawned in High Pass far from keep when I logged in again, I closed the game and started writting this.

**Comment by Kaelang** [comment]
Appreciate this is an older report - however the lack of information here makes this almost impossible to replicate without having to guess what this report is for. Please re-open with more information if this issue persists.

Closing.
