### ISSUE TITLE
Bestial Tokens

### ISSUE THREAD

**Issue by Itmritual** [WarEmu/WarBugs#10350]
I killed 1,000 Dwarfs and 1,000 Humans and didn't get a Bestial Token for either.

**Comment by Lheana** [comment]
That's because you are not meant to get Bestial Token for these unlocks: https://wiki.returnofreckoning.com/index.php/Empire
https://wiki.returnofreckoning.com/index.php/Dwarf
Check RoR wiki next time, there are all information about ToK unlocks.
