### ISSUE TITLE
Focused Mind wrong sound fx

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#10356]
This Morale isn't using the correct sound fx.  There is also an animation now which I don't think is correct.
Confirmation plz

**Comment by Lheana** [comment]
Don't know about the sound, but the animation when using FM is correct (verified with a video made on official)

**Comment by Torquemadra** [comment]
based on what evidence??

**Comment by gittoaster** [comment]
Correct Lheana, on the animation.
this vid is a pretty good one and he drops it around 1:00
https://www.youtube.com/watch?v=f3OQHmnAOjE

**Comment by Lheana** [comment]
Based on this video, the sound also seems correct to me.

**Comment by gittoaster** [comment]
Can you hear the sound which sounds similar do a disrupt.  There is more than one effect going on there, but if you listen carefully there is a sound there other than the 'swoosh' sound.  Sounds like a sped-up type of sound which is more like a short pulse.
