### ISSUE TITLE
Invisible Choppa T2 influence rewards

### ISSUE THREAD

**Issue by Grywwy** [WarEmu/WarBugs#1035]
I've noticed that the T2 influence rewards for the Choppa dont show up on the character model.

Items with this issue (as far as I know):

Mandred's/Stonetroll Punchas
Mandred's/Stonetroll Tuff Chest

**Comment by Meralors** [comment]
Fixed all 4 item's model, they now display correctly.
Can close issue ;)

**Comment by Evildoor** [comment]
According to #1844, "Sholdaspike of thunder and Stompas of thunder" are invisible.

**Comment by Evildoor** [comment]
Checked Choppa T2 RVR influence rewards (purple ones), items with no models:
Karaz Bellybuckle
Fangbreaker Bellybuckle
Spite's Stompas
Stompas of Thunder
Spite's Sholdaspikes
Sholdaspikes of Thunder

Twohanders with onehander model:
Fangbreaker Bigchoppa
Bigchoppa of Thunder

Also, some items are missing stats, but i can't find sources for most of them.
http://www.arsenalofwar.com/armor/Destruction/Sholdaspikes%20of%20Thunder

**Comment by chaostod** [comment]
still not working cant see them...

**Comment by Evildoor** [comment]
Why should they work? You reported 2 items, then i added some more, now we must wait until some DB developer fixes them.

**Comment by chaostod** [comment]
someone said they were working ... i was just sayin that for me they are not.


________________________________

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
