### ISSUE TITLE
Skull of Ograrand script not working

### ISSUE THREAD

**Issue by VonEpic** [WarEmu/WarBugs#10361]
Not critical but it's probably a simple little script somewhere, the Skull of Ograrand is supposed to be like a magic eight ball and give you vague answers to questions you "ask" it when activated.

![perturabro_249](https://user-images.githubusercontent.com/31397093/30009717-88f95088-90f8-11e7-919f-921a027ab8c7.jpg)

**Comment by wargrimnir** [comment]
https://github.com/WarEmu/WarBugs/issues/9608

Search before you post new issues.
