### ISSUE TITLE
Talisman making bug when mats in different bags

### ISSUE THREAD

**Issue by Telmorial** [WarEmu/WarBugs#10363]
When I have some mats in my trade bag and some in my main bag, the UI bugs out. EG. I try to make a talisman with mats in different bags, I click the make button then the fragment icon in the trade UI disappears and nothing happens.
But if I then move all the mats to the trade skill bag and try again, it works.
I've had this happen multiple times and also had people ask in /ad and they say the same temp fix works.

(Can I have my Griffin mount token now please :P  )

**Comment by wargrimnir** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366#p118993

**Comment by Telmorial** [comment]
Oppps, sorry, was just tongue in cheek re asking for griffon mount, was rather drunk last night.
Seriously though, I was trying to report a bug. What do you need for proof? Exact steps with names of materials/frags etc? I'm not sure screenshot will help though.

Cheers,
Telmorial.

**Comment by Telmorial** [comment]
Just to give an update, I've made more talismans without this bug happening. I think it might be only certain frags and/or other mats. If and when I get the problem again, I'll write down which mats were in which bags and report results here.

**Comment by raptrr** [comment]
Still a prob? If yes please provide as much info as you can. Screenshots, names of mats, etc.
