### ISSUE TITLE
Large renown amount of renown for 'tagging' players

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#10368]
While playing solo I noticted that I get at least 100 renown for every player I tag when he dies. This minimum seems to be independent on the amount of damage I did. As I'm RR70 this seems a bit much. Usually I would get something between 10-30 renown if I didn't do any significant amount of damage
![cimbina_035](https://user-images.githubusercontent.com/16117730/30073577-93749d70-926e-11e7-9aaf-d10bf1e171bf.jpg)
![cimbina_037](https://user-images.githubusercontent.com/16117730/30073579-947a02dc-926e-11e7-8a0a-d6654be3db86.jpg)

**Comment by Hargrim** [comment]
Fixed, thanks for reporting.
