### ISSUE TITLE
[Class Bug]  Summoned Magus Pets Spawning With Low Hp + Blue Horror Combat Bug + Daemonic Infestations in IC

### ISSUE THREAD

**Issue by Kaori1** [WarEmu/WarBugs#1036]
I noticed that when I summon pets as a magus that all 3 of them spawn with less than 100% hp. The actual amount seems to vary from time to time...but they're almost always missing around 1/5th to about 1/4th of their health. I've tested this with and without the +summon pet wounds tactic. Please fix!

***Also** Blue Horror seems to continue attacking mobs even after they're dead...it even recieves damage and will eventually die if not unsummoned. 

Lastly, Daemonic Infestation does not work in IC...which is somewhat problematic if you're a magus tryin to farm the npcs there.

**Comment by Silentguard** [comment]
Pet actually attack himself as i noticed.

**Comment by ozarmidrashim** [comment]
Fixed in next. Closing as more recent report exists.
