### ISSUE TITLE
[Epic Quest] Faith is Madness, can't access Ebon Keep

### ISSUE THREAD

**Issue by Fractus1484** [WarEmu/WarBugs#10365]
One of the last parts is to face the darkness, who is inside the Ebon Keep, currently this cannot be accessed, big red barrier.

Thanks,

**Comment by Lheana** [comment]
On which side is the quest?

**Comment by Fractus1484** [comment]
Order

**Comment by Lheana** [comment]
Use the key on the left of the barrier to enter.
