### ISSUE TITLE
[Item Issue] Magus Disc: Glacier Blue Enslaved Disk, Wrong Color Scheme

### ISSUE THREAD

**Issue by Kaori1** [WarEmu/WarBugs#1037]
So I was VERY careful when buying the mount I wanted...because farming 15g for me is not fun at all. After doing research on wikis as well as looking at the in-game display of disc mounts (next to the vendor in IC) I decided to buy the blue disc with orange/redish tint on it. The item is called Glacier Blue Enslaved Disc (confirmed to be in my inventory). According to the wikis, in-game mount displays and the icon of the mount itself...it is suppose to be blue and red. However...when I used the item my mount was a blue disc with a turquoise/greenish tint which is suppose to be the Dark Blue Enslaved Disk's color scheme. 

Small bug I know but I do hope this gets looked into if its not too much trouble to fix.

**Comment by Radiantknight** [comment]
I can join this topic, cause my magus disc was also the wrong color, can we just swap disks, Kaori? Mine looks like yours and yours looks like the one i wanted

**Comment by ozarmidrashim** [comment]
Should be fixed - database entries were wrong

**Comment by Radiantknight** [comment]
It was fixed BEFORE last patch, now it's broken again, still red

**Comment by nibblers** [comment]
bought the blue disc from ic island merchant just the other day. shows as blue in item description etc. yet when mounted it looks like the glacier blue disc (could be red, but the red from live did not have the blue edgeing)? Shows as the red/Pink disc when hovered over target. A pink disc :(
