### ISSUE TITLE
Death Warden Deathgirdle Appearance

### ISSUE THREAD

**Issue by Gronz** [WarEmu/WarBugs#10378]
Unable to change appearance with the Chosen Belt 'Death Warden Deathgirdle', although it is stated that it's available in the Tooltip. Also unable to use the inventory bag work around to alter appearance with the item. 

![gird2](https://user-images.githubusercontent.com/31695488/30113951-37882888-930e-11e7-91d4-93c77a304567.jpg)

**Comment by Lheana** [comment]
This should have been fixed with patch of 22/02/2020.
