### ISSUE TITLE
"Trolling" Gap on the road to Citadel in IC.

### ISSUE THREAD

**Issue by Antalor** [WarEmu/WarBugs#10379]
Well. I've used to go trough this road many times. To rename my last name, complete Epic Quests or check Overlord sets and there was few accidents where I fall inside this gap or I saw someone else inside it. You actually don't need to stand on it, if you even go through this gap there is a chance that you will fall inside it. I've took some screens in the past, but I couldn't find them when I searched them so I waited to see if someone else/me will fall into it. 
One day when I was going to Overlord vendor on my BG then I saw BO hitting mobs there. He had few on them on himself and his hp was low so he started to draw back and then he crossed this gap he fell into it. I've took a screen to be able to report it here.
Greetings.
![0004](https://user-images.githubusercontent.com/13917674/30116842-d4e81c18-931e-11e7-852a-31b432c0e2af.jpg)

**Comment by Lokenoth** [comment]
As its been listed already I'm gonna just confirm its quite easy to do intentionally as well. Group mate fell down there after fighting the mob. 

A quick fix could be inserting a plane with collision just below the terrain.

![lokrin_012](https://user-images.githubusercontent.com/17035321/32000875-0343f1e4-b990-11e7-9222-63196e0c12bd.jpg)
![lokrin_013](https://user-images.githubusercontent.com/17035321/32000876-0361e24e-b990-11e7-9083-cab9f6e0f5bf.jpg)
![lokrin_014](https://user-images.githubusercontent.com/17035321/32000878-03a5a998-b990-11e7-970f-9298ea126128.jpg)
![lokrin_015](https://user-images.githubusercontent.com/17035321/32000879-03bca9f4-b990-11e7-9953-d3976a4b5f74.jpg)

**Comment by sioding** [comment]
fixed with patch from 26.05.2018
