### ISSUE TITLE
Black Crag keep not able to spawn ram

### ISSUE THREAD

**Issue by Fractus1484** [WarEmu/WarBugs#10374]
Cannot spawn ram in Black Crag at friendly order keep, "says must be deployed at friendly keep" suggesting Ironskin Skar is owned by Destruction.  However map/guards etc all order.

**Comment by Fractus1484** [comment]
This applies to all siege, we also tried to spawn at destruction keep in BC, order keep in TM, and destruction keep in TM, just in case, not working at any.

**Comment by sioding** [comment]
Never seen that again in BC - close
