### ISSUE TITLE
My character (Barghaz, 40/56 Black Orc) is stuck in a sort of Limbo

### ISSUE THREAD

**Issue by Barghaz** [WarEmu/WarBugs#10387]
Hello there.

Before logging out for the night yesterday, I left my character in the Destruction warcamp in the Marshes of Madness (very much alive, as I should mention.)

When I logged back in this evening, I suddenly found that all my character's equipment and items had vanished. The armor slots as well as all of my bags are completely empty. Furthermore, the abilities have disappeared from my interface bars and neither the Experience nor the Renown bar are being displayed anymore. The character portrait at the top left shows a corpse instead of my character, as if I had died in game and when I attempt to log out, it says I can't due to my being dead. I tried forcing a relog by closing the game window several times and even waited a couple of hours before logging back in again, but that didn't solve the issue.

Things I can't do in this state:
-talk to NPC's.
-attack enemies. Neither will enemy NPC's attack me. I can even walk right into an Order warcamp and nothing happens.
-use any abilities.

Things I can do:
-queue for scenarios, curiously enough. When I enter a scenario, though, I'm still completely naked without any items on me. I'm suddenly able to use abilities, but the game won't give me any renown for participating in the scenario because I'm "running Solo." When I leave the scenario, I just end up right back in Limbo.
-talk in channels.
-use emotes.

It has been several hours now since I've discovered this bug and I can't seem to get my character out of this situation no matter what I do. I'm completely stuck. I should add that this issue only affects my Black Orc. I checked my other characters and they were all fine. They could interact with NPC's, use abilities and all their stuff was where it belonged.

Here's a screenshot for evidence:
![screenshot 8](https://user-images.githubusercontent.com/31717198/30144156-be2e003a-9389-11e7-9e48-70f6b8ed3ac0.png)

**Comment by sioding** [comment]
**Thanks for the report.** Since there is no confirmation, i will close this issue now. You can help us by following the bugtracker rules which you can find here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)
