### ISSUE TITLE
Bugged cooldown on inventory items 

### ISSUE THREAD

**Issue by Antalor** [WarEmu/WarBugs#10382]
Hello.
I've recorder a video after some roaming in Praag after I heard that cooldown on items like Scroll of Altdorf or Book of Bindings are fixed and no longer works after relog. 
I recorder a video then to show that it's still works and this bug remains. I'm also afraid it works for Subjugator's cape skills or similiar to it items.  Here is a link to the video: 
https://www.youtube.com/watch?v=3UwKjh2VC2o
Greetings!
PS. Apologise for low resolution. I needed to lower it a bit to cut the video's size by 70-80% and my internet isn't enough fast to upload it for next 5-6 hours.
PSS. Apologise for music in the background. I used it while I roamed in Praag and I didn't knowed that Fraps gonna record it as well.

Edit: Forgot to add.. Big thanks to Borliss which reminded me to check if this bugs still remains.

**Comment by Antalor** [comment]
I'm sorry for the spam, but we have tested it on Subjugator's cape too as well. Unfortunately it is like I said above. It's can be reseted via relog like Scroll or Book.
Best Regards!

**Comment by VonEpic** [comment]
I've noticed that using the Flight Master resets my Scroll of Inevitable City/Book of Binding cooldown as well, but the timer remains on the object/icon.

**Comment by Antalor** [comment]
Yes, you're right. Well, I hope it will be fixed of course if it's even possible to fix. 
Greetings! =)

**Comment by rakels** [comment]
same goes for the ROR Aegis, after zone change can be used despise of timer (for example at the end of each sc)

**Comment by rakels** [comment]
same for "Party Keg" aswell. After zoning it can be used again, despite the cooldown

**Comment by Nomilamlir** [comment]
is the issue i left closed? because it is a totally different issue to the above issue. Im saying that you can use this item with out wearing it as per people i have asked online but i cannot use it form my backpack. i have also heard that multiple capes can be used in succession. if this is the case then this bug is game breakingly good.
