### ISSUE TITLE
Light Mount Vendor not functioning

### ISSUE THREAD

**Issue by bensaret** [WarEmu/WarBugs#10384]
The Light Mount Vendor in Inevitable City cannot be interacted with, and as such cannot sell low-level mounts to players (leaving me stuck with my starter pack mule)

**Comment by VonEpic** [comment]
Only one vendor was active in the IC Stables.

**Comment by Lheana** [comment]
Known, fixed next patch. Until fix, you can buy 50% mount at vendors in warcamps.
