### ISSUE TITLE
Drop That!!

### ISSUE THREAD

**Issue by TheRealJurki** [WarEmu/WarBugs#10380]
The disarm ability of the squig herder doesnt work sometimes after ordering your pet to come back to you again. This bug happens also with tastes like chicken and explosive squigs, i already reported that

**Comment by raptrr** [comment]
https://github.com/WarEmu/WarBugs/issues/10288

**Comment by raptrr** [comment]
https://github.com/WarEmu/WarBugs/issues/9842

**Comment by Kaelang** [comment]
Tested with multiple calls back and disarm still went through.

Closing.
