### ISSUE TITLE
(Item) Sguig Herder Spear of remembrance 2h granting block strike through

### ISSUE THREAD

**Issue by smingleton** [WarEmu/WarBugs#10385]
![matrik_099](https://user-images.githubusercontent.com/24352165/30131495-d17fb044-9301-11e7-8bc6-a86807049a1e.jpg)

The spear is a 2h weapon from Dark elf T4, I figured I wouldn't be able to equip it.
but I can, and it also grants 10 percent block strike through, I discovered.
In the mean time I'm putting it back into the bank, and hope the weapon speed remains if their are changes =)

**Comment by Torquemadra** [comment]
thanks
