### ISSUE TITLE
Tank's Guard skill likes to reset/turn off

### ISSUE THREAD

**Issue by Antalor** [WarEmu/WarBugs#10398]
Good evening.
Since few last weeks I saw that my guard likes to turn off by itself. It's NOT happening when changing oRvR like (e.g. High Pass/Talabec in T3 or similiar ORvR lakes). It happens randomly. I tried to find what causes it but I can't. It just resets in (I think so) randomly time.
At the beginning I thought it happens because of my add-ons but I turned them off and my guard keeps reset. It's even hard to describe when it resets. I would say it resets once per ~hour (more/less).
Best Regards!
PS. I will share more info if I find anything what's gonna help with this problem.
Have a nice day!

**Comment by sioding** [comment]
I will close this issue cause no more information have been added since the creation of the report.
