### ISSUE TITLE
Unable to join scenario even while not in combat

### ISSUE THREAD

**Issue by drakni** [WarEmu/WarBugs#10393]
It happened to me a few times, when the scenario window pops, it says I can't join while in combat, even when I'm not. I tried fighting another mob to get in and out of combat once again but still can't join scenario.
Then I get leaver debuff... 

It just happened again to me and a friend.

edit: It seems that I need to exit and relaunch the game to be able to join scenario, until I get the problem once again.

![image](https://user-images.githubusercontent.com/2564812/30233037-56cab6fc-94f3-11e7-8081-37197ea932e7.png)

**Comment by gittoaster** [comment]
you just type ".unlock" to fix that when it happens.

**Comment by drakni** [comment]
Ok didn't know about that, thx.
