### ISSUE TITLE
Small request/suggestion

### ISSUE THREAD

**Issue by Ironbyrde** [WarEmu/WarBugs#10397]
I dont consider my eye sight to be poor but i often struggle to see or find the healer in WC. Could they not have an icon, maybe a cross, or better visual text? Ty for an amazing game!!

**Comment by Ryanfawkez** [comment]
Bugtracker is not for suggestions and feedback; the forums are. There is a section where you could post this request; https://www.returnofreckoning.com/forum/viewforum.php?f=15
