### ISSUE TITLE
Tor Achare PQ - Dark Elf Chapter 4 - Hard PQ

### ISSUE THREAD

**Issue by MalandraRoR** [WarEmu/WarBugs#10408]
The PQ Tracker and the PQ Boss Meter do not appear on the screen in this PQ.  It appears and works fine in the PQ Lionholm Lodge, just to the east of this one.

**Comment by Lheana** [comment]
Have you tried several times?

**Comment by MalandraRoR** [comment]
Entered and left the PQ several times, did /rel several times, logged out of game completely several times.  Also went into layout editor to make sure windows were not hidden or too small. Windows confirmed to be shown by entering neighboring PQ.

**Comment by Razielhell** [comment]
It works good.
