### ISSUE TITLE
T2/T3 SC bug.

### ISSUE THREAD

**Issue by Ashton0007** [WarEmu/WarBugs#10402]
Ok... So I'm not exactly sure how yet but a few people have figured out a way to get bolstered to r40 as opposed to the max r36. 
![velathiel_000](https://user-images.githubusercontent.com/31329704/30245203-ae5ca412-9597-11e7-833f-6898a76f6ebc.jpg)

**Comment by Kaelang** [comment]
Appreciate this is an older report - however the lack of information here makes this almost impossible to replicate without having to guess. Please re-open with more information if this issue persists.

Closing.
