### ISSUE TITLE
Stuck at the dwarf area starting screen after taking a fly

### ISSUE THREAD

**Issue by Kiriziel** [WarEmu/WarBugs#1040]
Hello,

After taking a fly to the dwarves area, my shadow warrior lvl 10 named Xalaria was stuck on the area. When i want to take this character from the choosing screen, the game try to load but failed and then return to the character screen.

Impossible to play with Xalaria at this moment ...

Thanks by advance for debugging my character

**Comment by xyeppp** [comment]
At loading screen type in /stuck and press enter, this will fix your issue.

**Comment by Kiriziel** [comment]
It works ! Thank you very much :)
