### ISSUE TITLE
Mysterious Death.

### ISSUE THREAD

**Issue by Ashton0007** [WarEmu/WarBugs#10410]
Died for no reason whatsoever while fighting a destro WB. I now some of you will say it was "geometry" but in that scenario it would tell me i died to myself. Possible GM abuse?
![velathiel_004](https://user-images.githubusercontent.com/31329704/30264684-2c940160-969f-11e7-8822-fea504093cd3.jpg)

**Comment by wargrimnir** [comment]
Check your combat log.

Don't accuse our staff of anything dubious without proof or you're going to end up having serious problems with the GM team.

**Comment by Lheana** [comment]
If it was a staff member, the chat would not tell 'You have died' but 'You have been killed by ...'

**Comment by Ashton0007** [comment]
I didn't accuse anyone of anything i simply asked if it was possible. Note the question mark. 

    On Monday, September 11, 2017 11:24 AM, wargrimnir <notifications@github.com> wrote:
 

 Check your combat log.Don't accuse our staff of anything dubious without proof or you're going to end up having serious problems with the GM team.—

**Comment by wargrimnir** [comment]
The implication that anyone on staff randomly kills players during combat is what warrants the response.

Again, check your combat log. If you see a name, then I can deal with it. If not, you've randomly died and it's a different issue that needs to be looked at. Without it, this report is rather useless.
