### ISSUE TITLE
[SW\SH] Lots o' Arrers\Rapid Fire dont interrupts when target move out of range

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#1041]

**Comment by magter3001** [comment]
I play a SH and can tell that  lots of arrows does interrupt. Not sure about SW.

**Comment by Green-Wolf** [comment]
I think you're both right, it seems inconsistent. On my Shadow warrior when they run out of range it does stop. But I've run out of Line of Sight of some squig herders and the arrows keep coming through the walls.

**Comment by wargrimnir** [comment]
LoS/Range is checked on each tick of the channel. I'm going to assume 2 years later this is no longer a persistent issue.
