### ISSUE TITLE
Norscan Longship PQ bugged

### ISSUE THREAD

**Issue by Kaeartes** [WarEmu/WarBugs#10412]
In the Norscan Longship PQ in Nordland the counter for actions appears bugged, and will switch between two sets of values after a few kills. For example 2 Norse Sea Dogs killed and then shifting to 11 and then after a few more kills, which are counted correctly, back down to a lower value.

I also could not interact with the crate of torches, making it impossible for me to complete stage 1 of the PQ. I have tried the quest a few times solo and with others in the area with the same results. 

One time I was there a group arrived and somehow managed to complete stage 1. When it shifted to Stage 2 the tents could not be interacted with, the supply barrels that need destroying would not be counted when all their health disappeared and instead immediately regenerated, and the killing the plunders portion had the same issue as the Norse Sea Dog section where the counter shifted up and down, at one point shifting above the maximum number needed. 

Since stage 2 is timed it just ended incomplete. I have attempted this PQ multiple times over the past 3 days with the same results

**Comment by Razielhell** [comment]
This is working now.
