### ISSUE TITLE
Falling out of world. Dwarf, Ironbreaker on The Blighted Isle

### ISSUE THREAD

**Issue by Sciberr** [WarEmu/WarBugs#10414]
The bug started after I finished a scenario and came back in this void. When I tried to respawn it brings me back but then quickly after I teleport/fall out of the world.

https://www.youtube.com/watch?v=ViA7v7gb8Hc

**Comment by wargrimnir** [comment]
https://github.com/WarEmu/WarBugs/issues/6831
