### ISSUE TITLE
Public Quest: Revoltin Gobbos

### ISSUE THREAD

**Issue by Moorningstaar** [WarEmu/WarBugs#10425]
Lvl 22-23 Hard Public Quest in NW of Badlands, next to Gunbad entrance.  Goblins will detect and attack through walls

**Comment by Lheana** [comment]
NPCs attacking through walls can not be fixed yet.

**Comment by Zaphologist** [comment]
Also the Moonfire Headhita Gobbos don´t give any Influence when you kill them.

Blood for the Bloodgod, Skulls for the Skullthrone and Milk for my Khorneflakes

**Comment by Lheana** [comment]
PQ will be fixed with next patch.
NPCs attacking through walls can not be fixed yet.
