### ISSUE TITLE
Empire foreman at Southern Garrison bugged position 

### ISSUE THREAD

**Issue by sofronguy** [WarEmu/WarBugs#10428]
I don't know how important this bug is (though i can see how it can be abused) but the foreman (guy with siege supplies) can be kited to the roof and stay there while also being invulnerable (my WE couldn't hit him with melee or ranged attacks). I asked an order guy to come test it and apparently the foreman remains usable by order. 

![zexy_000](https://user-images.githubusercontent.com/30108162/30391760-4d79fe90-98c3-11e7-9b18-798f4884e1da.jpg)

**Comment by sioding** [comment]
Thanks for the report. Checked it on my own - spawned fine.
