### ISSUE TITLE
Auction House, can not cancel items

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#10424]
I have a few items (8 greens and 2 purples) in the Auction House. I want to cancel these items but each time I get an error when I'm trying. The error reads: An unknown error has encountered with the auction house.

When I put a new item in the auction house, then I am able to cancel that one.

Character name: Nasty (destruction)

**Comment by Kaelang** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/1103.
