### ISSUE TITLE
Quest: Shield of Squig

### ISSUE THREAD

**Issue by Moorningstaar** [WarEmu/WarBugs#10427]
Upon taking this quest the quest giver immediately changes icons to the turn in icon.  However you do not get the squig shaped shield, nor does the tracker, or text give you any idea where you would find it.

**Comment by thorbolt80** [comment]
no red mark on the badland map for the second part of the quest
![thorbolt_116](https://user-images.githubusercontent.com/16274785/36442287-8d3a3fd8-1675-11e8-8b5f-9324ad925394.jpg)

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 31.03.2018
