### ISSUE TITLE
lair boss spawn/loot bug

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#10423]
t1 empire lair dosnt seem to be respawning

sometime between 10-11am gmt my team killed her, our shaman left the party shortly before she died because he didnt need the loot, when she died the text box came up with something like "nullreferenceexeption on lootdrop" (i forget the exact wording) as of this report it is now 2:30pm gmt, my new team has killed the elven and dwarven bosses, but the empire one still hasnt respawned, and her corpse is right where i left it earlier so im guessing nobody else has ninja'd the kill

**Comment by sioding** [comment]
Fixed with patch from 4.11.2017
