### ISSUE TITLE
Spawned outside of Talabec map 

### ISSUE THREAD

**Issue by Achillevas** [WarEmu/WarBugs#10436]
After leaving the Grovod Taverns of the Skaventide questline I was spawned outside or underneath the Talabec map. I had the caption on screen that I've entered 'Geistfeld', which is the ordinary location of the portal. But I couldn't really see anything and the minimap was oddly split into four different fragments of a map named Zone 0.
All this can be seen in the attached image. 
I could teleport out by using my Book of Binding.

![achillevas_007](https://user-images.githubusercontent.com/31998566/30498445-10ecedda-9a57-11e7-96fd-fbc258467caa.jpg)

**Comment by wargrimnir** [comment]
https://github.com/WarEmu/WarBugs/issues/6831
