### ISSUE TITLE
Emp T3 can't spawn ram

### ISSUE THREAD

**Issue by blechkautz** [WarEmu/WarBugs#10438]
In empire t3, destro attacked keep, but we defend it although door got broken. After a while we when doors already respawned, we tried to deploy siege, but i'm getting the keep is not safe message although nobody is attacking the keep. Same happened with canon on another char. It seems like the keep doesn't loose its under attack state for a time after the doors respawned.

![pfosten_002](https://user-images.githubusercontent.com/30760089/30507092-80033d6c-9a81-11e7-8843-b8039011c831.jpg)

**Comment by Kaelang** [comment]
No longer happens in current version of RoR.
