### ISSUE TITLE
Quest: Mob Mentality

### ISSUE THREAD

**Issue by Moorningstaar** [WarEmu/WarBugs#10432]
This easter egg quest is picked up at roughly 11.5k by 28k in the Badlands and is supposed to be turned in to Norrikson's Excavation (Dwarf CH 10) to a dwarf named Grufdok Dourfist.  No complete symbol appears on the map or over his head after you kill Luug, and interacting with him does not complete the quest.

**Comment by Ryanfawkez** [comment]
Grufdok Dourfist should be the hand-out NPC as well as hand-in. Fixing.
