### ISSUE TITLE
Rally Master Light

### ISSUE THREAD

**Issue by Moorningstaar** [WarEmu/WarBugs#10441]
Once you've earned any reputation for a chapter the tiel light over the rally master comes on and does not shut off even after you've selected rewards.  In the original game this light only came on to indicate you had unselected rewards.

**Comment by MaxHayman** [comment]
@Lheana This icon should only appear when player has rewards?

![](https://user-images.githubusercontent.com/16274785/38348145-65ff099c-38a0-11e8-979e-c66115b57a14.jpg)

**Comment by Lheana** [comment]
Yes, the icon is meant to be blue only when player can pick up rewards. Otherwise, it should be grey.

**Comment by MaxHayman** [comment]
This seems to be working as intended now.
