### ISSUE TITLE
Issue with Ch 10 Quest "Mourning Beauty"

### ISSUE THREAD

**Issue by Stormvermin** [WarEmu/WarBugs#10447]
Having issue with the quest "Mourning Beauty" in Chaos Ch 10 from Aneselma Selki. Able to Collect Corpsetallow flower but either the Knight of the Rose isn't there or I can't spawn him from the Grave. This was on my Magus Hapsheba

**Comment by Lheana** [comment]
This NPC is meant to be inside the tower
