### ISSUE TITLE
PQ ch 7 "the dragon gate" shadowland order side. Final boss stage 3 wrong level.

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#10442]
The final boss of stage 3 "lord khirareq" (heroes) is level 8. He should be level 16.

**Comment by Razielhell** [comment]
**_What makes you think that he should be level 16?_**

**Comment by thorbolt80** [comment]
The surrouding mob around the boss pop as level 16. So usually the boss is same level.
