### ISSUE TITLE
Scenario bolstering!

### ISSUE THREAD

**Issue by Raidon227** [WarEmu/WarBugs#10448]
If you level up to 31 while in a 16-31 Scenario, you become bolstered to 40, instead of 30.
![eragon_000](https://user-images.githubusercontent.com/32024553/30516432-2da70cf6-9b0d-11e7-8168-e7f69bee244f.jpg)

**Comment by Kaelang** [comment]
This issue no longer applies to current status of RoR. Bolster / Tiers have changed brackets.
