### ISSUE TITLE
Fabricated Artisan's Relic Box

### ISSUE THREAD

**Issue by Moorningstaar** [WarEmu/WarBugs#10446]
These boxes can be purchased from the guild merchant, and are used as containers for talisman making.  Unfortunately, craft items though they be, they cannot be moved into the crafting backpack.  This is of course a minor annoyance, and more than likely a simple variable shift.

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
