### ISSUE TITLE
PQ Watchtower of Aethwyn (Avelorn, Destruction)

### ISSUE THREAD

**Issue by spacestarkid13** [WarEmu/WarBugs#10456]
This PQ belongs to chapter 12, but gives influence to chapter 11.

![mashka_006](https://user-images.githubusercontent.com/16030337/30524611-0258895a-9c00-11e7-9172-2169d6b011ce.jpg)

**Comment by Lheana** [comment]
In fact even if the area shows chapter 11, influence correctly counts for chapter 12.

**Comment by Lheana** [comment]
#7388
