### ISSUE TITLE
SC quest npc 'Kaige Mortem'

### ISSUE THREAD

**Issue by ShiStar** [WarEmu/WarBugs#10450]
I had completed the "The Cemetary of High Pass" SC quest but the NPC at Altdorf did not show any quest complete for me to click, just a 'Good bye' option.

**Comment by Lheana** [comment]
Are you sure you have completed it?

**Comment by ShiStar** [comment]
of cause, I've had check my quest journal before posting.
Anyway, the bug been fixed after the hotfix patch.
