### ISSUE TITLE
specced mastery points are gone (marauder)

### ISSUE THREAD

**Issue by Kozhiie** [WarEmu/WarBugs#1046]
my specced mastery point are now gone. 
The toon is a lvl20 marauder.
see pic.

not possible to respec. even it shows a icon for resoec,
![kozh_003](https://cloud.githubusercontent.com/assets/13669057/9100547/719a24d0-3bdc-11e5-83a4-249f0f74cb13.jpg)

**Comment by ozarmidrashim** [comment]
I'm having trouble reproducing this issue.

Does it occur on the first map you load into, before you fly anywhere or take any scenarios?

**Comment by Kozhiie** [comment]
just signed in again today.  (inside the keep, just like i logged out yesterday night.
Same issue today. 
master points  0 0 0
Clicking respec. , see pic.
![kozh_006](https://cloud.githubusercontent.com/assets/13669057/9114619/0ae81a06-3c5b-11e5-97e7-f87196e8e396.jpg)
hmm, No cost to respec. clicking yes. and nothing happen.
+ and  - icon still gray in all trees

**Comment by Evildoor** [comment]
Maybe you don't have enough money to respec? I had the same thing on my BO, clicked "yes", got charged something like 1 gold and was allowed to reallocate points normally.
Overall it seems to be a bug after some of the recent patches, i have the same thing on most of my chars (no points showing), but the abilities in the tree with points in it have higher level, stats and damage/healing as they should(unless https://github.com/WarEmu/WarBugs/issues/1001), and i can use tactic which i've taken from the tree.
However, this can force you to spend money to respec if you want to pick a tactic: i had 4 points in Savagery on my 20 mara and 1 free point. I have no points showing and 1 free point, so i can't pick the tactic, but when i put 1 point into Savagery and press "Train" it properly shows 5 points into Savagery. After relog the points disappear again.

**Comment by Kozhiie** [comment]
Now i got 1g and 26s on the mara.
Same thing happening.
maybe its more expensive than that?, i dont know.

-But i know, that ive got 4 points in sav, at least. 
because ive got det first tactic. Scything talons equiped.
Dont want to respec, just want to know if all my points is in sav-tree.
/Kozh

**Comment by Radiantknight** [comment]
When I login my mastery points don't show up also, but when i hit respec, it costs 1 gold and i can reinvest points. After relog i can't see any points, but the tooltip damage for skills is same as before relog.
![sorc_mastery_skill1](https://cloud.githubusercontent.com/assets/13692665/9134825/c0d5a8a0-3d10-11e5-9366-7553bc2726cf.png)
![sorc_mastery_skill1_1](https://cloud.githubusercontent.com/assets/13692665/9134822/c08a77cc-3d10-11e5-97ea-5e095c95844b.png)
![sorc_mastery_skill2](https://cloud.githubusercontent.com/assets/13692665/9134827/c0d9eb86-3d10-11e5-90ae-d962657365be.png)
![sorc_mastery_skill2_1](https://cloud.githubusercontent.com/assets/13692665/9134824/c090f62e-3d10-11e5-8953-0aaa02aec021.png)
![sorc_mastery1](https://cloud.githubusercontent.com/assets/13692665/9134823/c08cded6-3d10-11e5-9d3a-14c8113dc2e8.png)
![sorc_mastery2](https://cloud.githubusercontent.com/assets/13692665/9134826/c0d723f6-3d10-11e5-89a5-31b9c7a5df27.png)

**Comment by Evildoor** [comment]
Points are showing now. Thanks.

**Comment by Kozhiie** [comment]
perfect!
