### ISSUE TITLE
[Black Guard] "Thirst for Death"/"Simmering Anger"/"Efficient slaughter" tactics

### ISSUE THREAD

**Issue by murmelon** [WarEmu/WarBugs#10469]
"Thirst for Death"/"Simmering Anger"/"Efficient slaughter" tactics is not working, i think so.
My testing is below.
https://youtu.be/lHubCC68PtU
https://youtu.be/n0p0RalK_GY
https://youtu.be/B0NCHnBJiKM

**Comment by Yellowpillow** [comment]
#7466 is about Efficient Slaughter, more detailed.

**Comment by sioding** [comment]
fixed with patch from 21.10.2017
