### ISSUE TITLE
D3DCOMPILER_47 is missing

### ISSUE THREAD

**Issue by Poussky** [WarEmu/WarBugs#10460]
All work correctly since I restart my computer, after installing windows 7 update I got this message with the Launcher :

https://image.noelshack.com/fichiers/2017/38/1/1505719037-d3dcompiler.png

In english, it say approximatly :

"RoRLauncher.exe - System Error

Unable to start the program because it is missing D3DCOMPILER_47.dll on your computer. Try reinstalling the program to correct this problem."

**Comment by wargrimnir** [comment]
Not something we did, why are you posting it here?

**Comment by Poussky** [comment]
I'm not very skills in computer things, and I don't know if this problem came with your programm or with my computer. So, if you don't need this, you can close it and I try to resolve it myself. Sorry for that.

**Comment by wargrimnir** [comment]
Casual google searching. This might help.
https://www.youtube.com/watch?v=8cKgUE7pBKk
