### ISSUE TITLE
[Engineer] Sticky Bomb UI/Tooltip bug

### ISSUE THREAD

**Issue by WAR-Lust** [WarEmu/WarBugs#10463]
Just bought the Sticky Bomb mastery at R20 and tooltip states I am too low level to use it (skill is red on hotbar, #2 in screenshot below).

I can use it just fine but a big yellow message saying I am too level pop on screen every use.
![lustineer_005](https://user-images.githubusercontent.com/32098196/30592432-a29afa12-9d3e-11e7-864a-bde99436d232.jpg)
(In screenshot: you can see the dot on mob, announcement and tooltip as well as #2 skill being red.)

Cheers! Keep up the great work (:

**Comment by grunbag** [comment]
Fixed on Next Patch

**Comment by sioding** [comment]
fixed with patch from 09.03.2019
