### ISSUE TITLE
Quest: Armor of the Ancestors

### ISSUE THREAD

**Issue by Moorningstaar** [WarEmu/WarBugs#10462]
Pickup Location: Durlin Kanstone in Lorkinson's Excavation, Thunder Mountain (Dwarf Ch17)
This quest asks you to check two debris piles for a piece of armor.  Only one location shows on the map and the rubble pile is not interactable.  I can find nothing else in the area that would suggest itself as a pile.

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
Fixed with patch from 30.06.2018
