### ISSUE TITLE
Purple bag from ORVR

### ISSUE THREAD

**Issue by espi1ce** [WarEmu/WarBugs#10477]
Hello.
I won the purple bag from RvR in Reikland. It was mailed but with our main reward.
![buged purpel bag](https://user-images.githubusercontent.com/32179180/30718978-81bec24a-9f2a-11e7-809e-3b9125f12e44.png)

**Comment by wargrimnir** [comment]
Already reported, we plan some changes with bag deployment in the near future. In the meantime, empty bags happen rarely. We don't refund them unfortunately.
