### ISSUE TITLE
Black Fire Pass Lair of Ravack dropped 2 items for same class

### ISSUE THREAD

**Issue by Sciberr** [WarEmu/WarBugs#10474]
It was only me as Warrior Priest and an Archmage together doing lairs in a party and when we looted the boss it dropped 2 of the same items for just the Archmage

https://youtu.be/zYZajGXo1H0

**Comment by wargrimnir** [comment]
This is normal. The drop system guarantees a chance at items for players in your group. All bosses drop two items. If two people kill a boss, there is a 50% chance both items will be for one class. Lair bosses are not intended to be killed with two people, but many of them do not have abilities yet, which makes them quite a bit easier than intended.
