### ISSUE TITLE
Trouble with parry.

### ISSUE THREAD

**Issue by Ripliel** [WarEmu/WarBugs#10487]
As you can see on these screenshots, I have 15% parry on my SW while being in Assault stance. There is a 10% parry bonus for this stance. So the issue is I can't quite believe that 632 weapon skills can grant me only 5% of parry. 
Please prove me if I am wrong. 
Also when I use any other buffs for WS like Wrist slash or Instinctive Aim tactics, the parry rate doesn't change in .getstats.
![ws bug 1](https://user-images.githubusercontent.com/16005849/30773755-c035ede0-a07f-11e7-8fbb-e47f2fa52273.jpg)
![ws bug 2](https://user-images.githubusercontent.com/16005849/30773759-c313a49e-a07f-11e7-8e0f-d791cf17a917.jpg)

**Comment by wargrimnir** [comment]
Weaponskill does not translate to Parry on RoR.

It is a comparative stat to Strength. If someone attacking you is STR based, and your WS is higher than their STR, you will receive some Parry bonus. The vast majority of the time this is not the case. Weaponskill is not a flat Parry buff.
