### ISSUE TITLE
Quest: Raise the Chaos Banner for Glory

### ISSUE THREAD

**Issue by avalus** [WarEmu/WarBugs#10483]
As BOs don't have any guards anymore, the 2nd stage of the T3 quest in the Quest chain to obtain City scroll (and the last Skaven token AFAIR?) - "_Raise the Chaos banner for glory_" (35 kills & interact with a T3 Emp BO Sergeant) given by _Arnorr Seven-Struck in Talabecland_ - is not doable anymore.
This is for Destro side but i suppose the same issue is present on Order side as it is the same type of quest.

**Comment by VonEpic** [comment]
Yeah they haven't spawned since the RvR change, but the quest is flagged "complete" at Seven-Struck but selecting "complete" in dialogue does not allow finishing the quest.

**Comment by Ryanfawkez** [comment]
Changed the objective to capturing Feiten's Lock. Order will have to capture Verentane's Tower for their quest.

**Comment by avalus** [comment]
Destro side, Feiten's Lock BO recapping (taking it from Order) didn't work.
Maybe it's supposed to work on a Neutral FL?
Could also anyone from Order confirm or infirm if it worked for them concerning Veterane Tower BO ?

**Comment by VonEpic** [comment]
VonRugen just posted in the BT about it not working on Order's side either.

**Comment by avalus** [comment]
After reading the Quest Log, i found out you had to do a kill while recapping.
Tested today, killing while defending BO doesn't work either, last guess is :

**Comment by VonEpic** [comment]
I have both captured it from neutral stance at beginning of RvR, captured it BACK from Order, and re-engaged it from "abandoned" status. All to no avail. If the object is to force interaction with RvR, maybe just place the respective NPC (Destro/Order) in the back portion of Feiten's Lock or on the very top of Veltran's Tower, for the time being so we can at least continue the quest to the next stages?

**Comment by sioding** [comment]
Fixed with patch from 4.11.2017

**Comment by sioding** [comment]
Could someone verify that the quest ist working again?

**Comment by Lheana** [comment]
Fixed next patch.
Destruction players will now have to click on the GameObject 'Chaos Banner' next to the Battlefield Objective Feiten's Lock.
Order players will now have to click on the GameObject 'Empire Banner' at the top of the Battlefield Objective Verentane's Tower.

**Comment by VonEpic** [comment]
Thanks!

**Comment by sioding** [comment]
Fiexed with patch from 10.11.2017
