### ISSUE TITLE
[PQ] Echoes of War - T3 Empire High Pass - Potential reward issue

### ISSUE THREAD

**Issue by WAR-Lust** [WarEmu/WarBugs#10482]
Finished the PQ twice in a row with someone else (one grouped and one non grouped) and reward from Blue and Purple bag ended up only being crafting items and money. No gear for both of us.

Chest shows a different quest/pq name when hovering on it too.
![lustineer_006](https://user-images.githubusercontent.com/32098196/30758451-6492f312-9fca-11e7-8018-71c3ce7ff0d7.jpg)

Not sure if it's working as intended. Sorry for the post if it is!

**Comment by wargrimnir** [comment]
PQ rewards for bag less than gold are only implemented up to Chapter 8 currently.

**Comment by WAR-Lust** [comment]
Oh ok, good to know! Thanks for the quick reply (:

**Comment by Razielhell** [comment]
Closing.
