### ISSUE TITLE
[RP] Concussive Runes Tactic doesn't work on Rune of Cleaving

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#10480]
![balin_035](https://user-images.githubusercontent.com/14627932/30732224-d04f1274-9f71-11e7-9742-662a64a7354f.jpg)

The Tactic Concussive Runes should put a detaunt on enemies if you use Attacks from the Path of Grimnir.
It has a 25% chance to apply them.

I have tested that this Detaunt works on the Enemy with the Rune of Battle from that Tree and with The Rune of Might. If you hit the target afterwards the detaunt is removed.

But after Hitting for 5 minutes npcs with the Rune of Cleaving there was not a single Detaunt on the NPCs. I havent used any other ability in the testing process except the auto attack.

**Comment by Kaelang** [comment]
Appreciate this is a dated report, however in the off chance you are still playing on this Runepriest and experiencing this issue please could you submit supporting evidence such as a video / chat log etc. 

I will close this report in 2 weeks if no supporting evidence is provided. If you find this report whilst considering opening a report - please go ahead and do so.

**Comment by Kaelang** [comment]
No further information - closed.
