### ISSUE TITLE
[Engi] Strafing Run, -19% Damage than on Text description

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#10489]
Most Abilites have different Damage than on their text Description. Something like 820 for Grunblast but in real on an NPC it does 819. So this maybe be calculation discrepancies or not calculating Ranged Power in.
Most abilites have then a discrepancy on up to 1%.
Only Friction Burn does 4,6% less damage than the Tooltip says.

Also the Text doesn't match if the Ability was buffed in the past, like recently Phosphorous Shells.

Strafing run on the Grenadier Tree says on text it should deal 650 Damage.
On Tests it does 525 Damage vs Npcs. (Dealt Damage + Mitigation)
I have Relogged two times to verify that it hast to anything with turret buff or anything like that. No Turret buff was used in testing.

I have also made a retest with not 15 Mastery but only 9 Mastery. Damage Discrepancy between Text and recorded Damage is around 130 Damage.

I have around 520 BS on the Engi and +20 Ranged Power.
Character Window says Extra Bonus on Ability on Ranged Attacks should be 104 dps.
Extra Damage n auto Attack 52 dps.

![lesti_464](https://user-images.githubusercontent.com/14627932/30775342-b4cfd53a-a091-11e7-9c5a-e4e318bca405.jpg)

**Comment by grunbag** [comment]
It’s still the case. ?
