### ISSUE TITLE
Renown skill points not showing.

### ISSUE THREAD

**Issue by VonRugen** [WarEmu/WarBugs#10481]
For the last week when visiting the trainer for renown despite showing renown points spent it shows all skills as if no points have been spent , this is difficult to track progress and makes one doubt if their renown points are active at all, do they keep resetting or are they not showing, I do know that spending more points does not seem to progress beyond base skill it is like they are being spent but not going to any skill.

**Comment by Vellwynd** [comment]
bump

Was going to post same bug

**Comment by wargrimnir** [comment]
https://github.com/WarEmu/WarBugs/issues/4575

Please use the search function when reporting bugs.
