### ISSUE TITLE
[Slayer] - Breaking point.

### ISSUE THREAD

**Issue by Fuineir** [WarEmu/WarBugs#10493]
Seems like recently changed tactic Breaking Point doesn't increase crit chance to giantslayer abilities anymore.
Testing was performed on dok with 18% chance to be crit, with SL base crit of 0% at the time of the test.
After 2mins without tactic slotted I crit the target (with Cleft in Twain) 18% of times, which is correct, after slotting the tactic i crit the target 16% of times.

Here's the vid:
https://drive.google.com/file/d/0B9MkfxKSbm9yNzZGdGFTM2pBdlU/view?usp=sharing

**Comment by Torquemadra** [comment]
you are incorrect ability was extensively tested
