### ISSUE TITLE
Quest kill not tracking bug

### ISSUE THREAD

**Issue by Vellwynd** [WarEmu/WarBugs#10492]
High Elf Chapter 8, the quest "The Price for Survival". Killing the mob Corrupted Chargers will not advance the quest, but killing the mob Dreadcharge Riders will count as kills for both Corrupted Chargers x/6 and Dreadcharge Riders x/6

**Comment by SecretsOTheP** [comment]
Fixed, pending database update. 
"Corrupted Charger" should now update by killing the proper NPC.
