### ISSUE TITLE
Tactics not really changing upon selecting another set

### ISSUE THREAD

**Issue by Radiantknight** [WarEmu/WarBugs#1049]
I have 2 sets of tactics for my Sorc and 3 empty set slots. Problem is when i switch between sets, tactics do not change, ie. I have Grasping Darkness & Piercing Shadows in set 5 and Endless Knowledge & Alignment of Naggaroth in set 1. When i switch to set 5, then select set 1, my int and ele resist do not change, although icons change. But if i select empty tactic set and then change to set 1, I see the increase in int/resist.

**Comment by ozarmidrashim** [comment]
Bug because Grasping Darkness throws an exception when removed.
