### ISSUE TITLE
Bolstered Armor doesn't reset after re-entering PvE area

### ISSUE THREAD

**Issue by kolybri** [WarEmu/WarBugs#10497]
Description:
You can enter the RvR area and get bolstered stats. These will reset after you re-enter the PvE area. All stats are reset except the armor value. What this means is that essentially you can enter the RvR area with level 1 (or 16 for T2-4), get a huge armor bolster if you have every slot equipped, and then facetank hordes of mobs as you take immensely reduced physical damage. 
The only way to lose the bolstered armor value is to log off.

This could also explain ticket #10472 

Process: 
(1) Enter RvR area T1 or T2-4 and get bolstered stats
(2) Go back into PvE area and watch all stats get reset except armor (see pictures)
(3) Powerlevel as you essentially can now tank hordes of mobs

Picture 1 shows my character just logged in without having entered the RvR area
https://www.pic-upload.de/view-33977734/Iksooo_000.jpg.html

Picture 2 shows my bolstered character, who just entered the RvR area
https://www.pic-upload.de/view-33977733/Iksooo_001.jpg.html

Picture 3 shows my character with reset resists but with the same armor value
(the stats also reset, no need for a pic there)
https://www.pic-upload.de/view-33977735/Iksooo_002.jpg.html

It is the same with T1 RvR bolster see pics
https://www.pic-upload.de/view-33977788/Fatdude_001.jpg.html (logging in)
https://www.pic-upload.de/view-33977789/Fatdude_002.jpg.html (entering RvR)
https://www.pic-upload.de/view-33977787/Fatdude_003.jpg.html (re-enter PvE)

**Comment by Kaelang** [comment]
Bolster is now correctly removed (including Armor) when leaving RvR zones. Please re-open if issue persists.
