### ISSUE TITLE
Every quest hints the objectives are in order starting zone

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#105]
All nordland quest seem bugged about map marks to sign order character creation pop zone as target for quest. Worthless said that there nothing to do on order chap1 camp, i've checked btw
![tesq_002](https://cloud.githubusercontent.com/assets/7527415/2928319/5b1b5bfa-d77b-11e3-9437-fcdeb2894cb0.jpg)

**Comment by Evildoor** [comment]
Since the "Progress" has been made, i think i'll close this and in the future problematic quests should be reported individually.
