### ISSUE TITLE
"Theologians" chain quest jewelry reward is without tali slot.

### ISSUE THREAD

**Issue by Zxul** [WarEmu/WarBugs#10500]
There is a chain quest in Chaos Ch 15, which back on live rewarded Talismand of the Raven jewelry with tali slot.

Doing the quest yesterday, I did got the item, but it is without the tali slot.

Links to the item back from live (can't open them since Python 2.5 MiA, but at least can see item stats using google search):

https://www.google.com/search?q=%22talismand+of+the+raven%22&dcr=0&nfpr=1&filter=0&biw=1920&bih=920

![image](https://user-images.githubusercontent.com/31373407/30821140-f9e37702-a22c-11e7-99fa-f363964f41e4.png)

**Comment by SecretsOTheP** [comment]
Fixed, pending DB patch.

**Comment by SecretsOTheP** [comment]
Reverted fix. This should be closed, as the talisman slots were removed for balance concerns.
