### ISSUE TITLE
Specialization Point reset

### ISSUE THREAD

**Issue by Bargmeps** [WarEmu/WarBugs#10501]
Sometimes when i change a zone my specialization point in the ability "Keep On Choppin'" resets and i have to train it again, the other points in the tree are still in there but the one of the ability loses it.

Edit: on the 9.27 it happened when i changed the belt of the choppa. It was a renown rank belt for a normal one a mob dropped.

**Comment by SecretsOTheP** [comment]
This also occurs with White Lions when using a set piece that grants a rank of career points. The ability granted from the tree it boosts will reset if it's the last point trained to get said ability every time an item is changed out in your inventory.

**Comment by Bargmeps** [comment]
OK, it resets the latest ability, this time "Can't stop the Chop". I "gained a specialization point" after getting a new renown cloak on level 16, but this cloak doesn't give a specialization point in its description.

**Comment by avalus** [comment]
I second "SecretsOTheP", this usually happens when you have a Set bonus giving you +1 in either skillpath, once you equip/unequip any other item on/from the character (even not belonging to the said Set) the +1 SP resets and you have to put it back EVERY time ;)

**Comment by Zealote** [comment]
Needs to be clarified whether this only happens when OP changes gear or when they simply change zone as well. If it's the first, it's already known: https://github.com/WarEmu/WarBugs/issues/7024

**Comment by Natherul** [comment]
this is 7024, closing
