### ISSUE TITLE
Flanking skill not present as core skill in Shadow Warrior training window

### ISSUE THREAD

**Issue by slaughterk1n** [WarEmu/WarBugs#10504]
You changed flanking from being a mastery skill to a core skill in the latest patch.  However it seems
 the skill was not put in the core list.  Instead Eye shot is listed twice, as a core that cannot be selected, and as the new 13 level mastery ability.  Flanking is not listed at any level (it was probably intended to be placed at level 18, which is where the non-functional eye shot skill is listed)
![inyofacelike_002](https://user-images.githubusercontent.com/32292747/30849860-ba7c38a2-a271-11e7-974e-7eac67f35cea.jpg)
![inyofacelike_000](https://user-images.githubusercontent.com/32292747/30849870-c6cd70e4-a271-11e7-8dda-a55ba0dec7c6.jpg)

**Comment by wargrimnir** [comment]
It should show up in your abilities automatically when you reach the appropriate level for it. You don't need to buy career abilities currently, they're given automatically. Flanking Shot is earned at R25.
