### ISSUE TITLE
Spirits for the Raven God non-progressable due to NPC naming

### ISSUE THREAD

**Issue by bensaret** [WarEmu/WarBugs#10508]
The quest Spirits for the Raven God in High Pass cannot be progressed due to NPC naming, specifically killing the "Luminous SPRITE". There are similarly-named "Luminous SPITE" NPCs, but because of the name (and possibly subsequent NPC number), they are not progressing the quest when killed, preventing further game progression.
![prizrak_014](https://user-images.githubusercontent.com/31707952/30872057-b7efe15c-a29d-11e7-9e49-775342263013.jpg)

**Comment by Ryanfawkez** [comment]
Actually there's no killcount associated to that specific objective, and there's only a typo in there.
