### ISSUE TITLE
[Black Guard ] "Enraged Beating"

### ISSUE THREAD

**Issue by murmelon** [WarEmu/WarBugs#10507]
Hi there. 
Critical damage (from EB) doesn't bring 10 hate ( like it's at skill tooltip).
Test is below.
https://youtu.be/JKE5AoH9_-s

**Comment by Ashton0007** [comment]
Works from my end.

**Comment by SecretsOTheP** [comment]
Should work after next patch.

**Comment by sioding** [comment]
fixed with patch 21.10.2017
