### ISSUE TITLE
Dwarf boss  body disappeared

### ISSUE THREAD

**Issue by Dragothurch** [WarEmu/WarBugs#10505]
Hi !

Today we kill dwarf lair boss and when die, not show dead body just say somethin message (nullreferenceexception was thrown from generate loot. this object will be destroyed)and 
disappeared. So no loot, no boss reset. nothing. Pls help(repair, maybe loot)

Thx

**Comment by Dragothurch** [comment]
Hi, what is the confirmation request?

**Comment by Dragothurch** [comment]
![dragothur_008](https://user-images.githubusercontent.com/29735256/30867075-3a4969c4-a2db-11e7-81dc-13538ae4b93a.jpg)

**Comment by Lheana** [comment]
#10423

**Comment by sioding** [comment]
Fixed with patch from 4.11.2017
