### ISSUE TITLE
[Bug] Floating Textures

### ISSUE THREAD

**Issue by Azorast** [WarEmu/WarBugs#10506]
-Hi dev. team. I'll try to make a compilation of all floating textures that ill see ingame in this issue post.

- Death Peak: 

1. (5300,39000) - Seems all this whole area has floating textures problems:

![war 2017-09-26 13-49-06_result](https://user-images.githubusercontent.com/32238699/30860270-e7fe4158-a2c6-11e7-91f7-3e71a411f084.png)
![war 2017-09-26 13-49-40_result](https://user-images.githubusercontent.com/32238699/30860271-e800dd0a-a2c6-11e7-8588-79696f7f4c13.png)

**Comment by wargrimnir** [comment]
This will require a map editor, the vast majority of objects in-game are client-based.
