### ISSUE TITLE
Exception while killing mobs

### ISSUE THREAD

**Issue by bloodi** [WarEmu/WarBugs#10514]
Trying something on the PQ outside troll country wc, after killing a few of them this happened:

https://imgur.com/a/aLnVZ

AFter it, my character is unable to cast or attack and its ap does not regen, is able to talk to npcs however and flying to another zones solved it.

Edit: Most likely the same as this https://github.com/WarEmu/WarBugs/issues/9632

**Comment by sioding** [comment]
Fixed with patch from 4.11.2017
