### ISSUE TITLE
Lost gear - can i get it back? 

### ISSUE THREAD

**Issue by Kozhiie** [WarEmu/WarBugs#1051]
Is it posible to get back sended/lost gear.

Just created a new toon.
Gave it a name,.....

After that i switch to another toon. and mailed the gear to my just created toon. 
The sended gear have not reach my new toon.!
Should it not be a warning text that the mailed toon not existing or something.
-Will the mail return if it not is opened for a few days or so ?

Really hope to get my gear back,

**Comment by ozarmidrashim** [comment]
Nope, and this should have been posted in Game Support.
