### ISSUE TITLE
Kadrin Valley stuck between rocks.

### ISSUE THREAD

**Issue by Sciberr** [WarEmu/WarBugs#10518]
Theres a spot in front of the lair of Kyreia Sek where you can get stuck in between two rocks. 

https://youtu.be/ryOsHGfS19U

**Comment by VonEpic** [comment]
Use /stuck command (twice in quick succession).

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
.Fixed with patch from .17.03.2018
