### ISSUE TITLE
Bag did not mail out (yet?)

### ISSUE THREAD

**Issue by VonEpic** [WarEmu/WarBugs#10517]
Placed in RvR in Reikland, at least one other person said they got their bag, I still have not received anything. Tried relogging, but still nothing. I did leave the zone shortly after the RvR closed but before the banner disappeared.

![izzmerelda_042](https://user-images.githubusercontent.com/31397093/30945688-a15fa8ec-a3cd-11e7-8910-74bca912debf.jpg)

**Comment by Razielhell** [comment]
Ty for the report. #10279

**Comment by VonEpic** [comment]
Negative, no bag. Was there something I was supposed to do to trigger the bag being sent? Or wait in zone til it sends?

**Comment by VonEpic** [comment]
Got a green bag in mail today, don't think I placed in any RvR's last night (could have) but if you did something on your end, I'm assuming it worked. Thank you!

**Comment by Razielhell** [comment]
You can try and error. Stay at zone and see if you get bags. Next time always leave and check again. Investigate and report. Thanks!

**Comment by VonEpic** [comment]
I'm not worried about it, these things fall through the cracks. I just wanted a record of it so if it is a re-creatable error, I'll have...a record of when/where it happened.
