### ISSUE TITLE
Joining sc crash

### ISSUE THREAD

**Issue by Marawo** [WarEmu/WarBugs#10524]
As title said joining/leaving/using Flightmaster an sc crashes me to this screen (other characters work fine)
![screenshot_000](https://user-images.githubusercontent.com/29643742/31047951-21dd524c-a614-11e7-8f09-e8b6c28bc70b.jpg)
after a few minutes on this screen it becomes this one
![screenshot_001](https://user-images.githubusercontent.com/29643742/31047961-470644f2-a614-11e7-87aa-5a2396d315ef.jpg)

**Comment by Kaelang** [comment]
This crash still happens 3 years' later but isn't tied to the flight master. I will close this report for the time being as there is no additional information to support the team with replicating / finding the source of this issue. 

If you are still active in RoR and have any other ideas as to why this issue persists, please comment and/or open a new issue with more information.
