### ISSUE TITLE
I can't reset my crafting skills !!!!!!

### ISSUE THREAD

**Issue by Diasgod** [WarEmu/WarBugs#10520]
Hello,

I will be grateful if u can help me and finally to solve this problem.

I can't reset my crafting skills. I have magical salvaging and Apothecary. I had already tried to relog many times but when i talk to Hedge Wizard i have no option or a selection button to learn Talisman Making profession. See my above 
![dias_000](https://user-images.githubusercontent.com/32371913/30985047-c6c20e34-a497-11e7-9633-0659d74dea48.jpg)
or my attached photo to see it clearly.

https://www.dropbox.com/home/WARHAMMER%20ONLINE?preview=Dias_000.jpg
![dias_000](https://user-images.githubusercontent.com/32371913/30985067-d53a95a8-a497-11e7-8f15-1822ccbde0a4.jpg)

Many thanks
Dias

**Comment by szejoza** [comment]
Have you tried different trainers? I've respecced 2 days ago and had no problem with learning new crafts (trained at Altdorf trainers)

**Comment by ErikWPotter** [comment]
I'm unable to retrain from Magical Salvaging to Scavenging either. Or any other gathering trade for that matter. I've tried in both High Elf T1 Adunei and The Empire T1 Grey Lady Coaching Inn.

**Comment by ErikWPotter** [comment]
The character I tried to retrain was level 17. He is able to retrain in Altdorf. I suspect that after T1 you are unable to use the T1 craft trainers. If this is intentional the trainers should inform you that you must travel to the capital.

**Comment by szejoza** [comment]
Might be the same case as is with the renown trainers - in tier 1 most (if not all) renown trainers are actually an 'apprentice renown trainer' which means that after certain point you can't use their services. Don't know if it is intended or not, but making it more universal so everyone can retrain no matter their level would not be gamebreaking and the game wouldn't lose anything from the immersion.
