### ISSUE TITLE
Oathstone still does damage to Myself!

### ISSUE THREAD

**Issue by tquere** [WarEmu/WarBugs#10528]
Hello, after yesterday's patch where the bug was announced as "Closed", I gave it a try.
Unfortunately, it still occurs. No visible change :/

[17/10/01][09:42:12] Your Oathstone hits you for 179 damage. (537 mitigated)
[17/10/01][09:42:12] You blocked your Guard.

The 2 lines "block your guard" and oathstone seem to be just swapped from before the patch but that is pretty it.

Thank you

**Comment by Natherul** [comment]
Ill look into it further, should not happen with the last batch of changes. Also for the future, you could comment on the old closed one and it reopens :D

**Comment by Natherul** [comment]
old ticket: https://github.com/WarEmu/WarBugs/issues/10512

**Comment by tquere** [comment]
Ok sorry about that ...
Didnt know that a comment would untrigger the "Closed" status.

And just to say it out loud, the Oathstone is a damage shield .. not a
damage proc.
Since the fix told about damage proc, I just wanted to precise it, though
you certainly know that already.

Thanx again for that great game !

2017-10-02 9:10 GMT+02:00 Natherul <notifications@github.com>:

**Comment by Natherul** [comment]
I got another fix that has been verified multiple times now on the testserver, will be fixed with next patch.
