### ISSUE TITLE
Health Potions

### ISSUE THREAD

**Issue by grotsaidstop** [WarEmu/WarBugs#1052]
When i end the quest This is War with my Squig Herder i just win 5 potions, 20 with my Black Ork.

Then I tryed to buy old 20 potions stack with the NPC vendor with my squig herder, but only 1 potion appeared in my inventory.

Don't know if there are same problems with others characters.

**Comment by Evildoor** [comment]
Seems to be a problem with buying stacks of items back. According to this:
http://www.returnofreckoning.com/forum/viewtopic.php?f=2&t=5787
this was fixed. Closing.
