### ISSUE TITLE
Beastlord: Dorala Grindal does not give the BL Quest

### ISSUE THREAD

**Issue by sioding** [WarEmu/WarBugs#10523]
The Questgiver in TM does not work. Maybe cause its also a Healer?

![image](https://user-images.githubusercontent.com/18517842/31043982-c4e5c012-a5c6-11e7-9ce8-377618c61247.png)

**Comment by wargrimnir** [comment]
This will be hotfixed next time we boot.

**Comment by sioding** [comment]
Move Questgiver to Bergul Redhammer works fine. Close.
