### ISSUE TITLE
Wayshrine of Sigmar - Ostland - Massive Loot Bag

### ISSUE THREAD

**Issue by aryafaun** [WarEmu/WarBugs#10536]
At 10:41 pm EST I was at Wayshrine of Sigmar in Ostland I received a massive loot bag, however the contents are not of what a massive loot bag should be. I have attached a picture.
![ainra_149](https://user-images.githubusercontent.com/32444564/31062760-18034870-a6fb-11e7-8153-4bc2976b5b94.jpg)

**Comment by Razielhell** [comment]
Can you try again and check if you get Set item this time?

**Comment by Razielhell** [comment]
#10279
