### ISSUE TITLE
Good will mission hero boss

### ISSUE THREAD

**Issue by ragnarian** [WarEmu/WarBugs#10532]
the boss of the mission 'Good Will', Wilhelm Von Kleinbach in troll country is a hero class enemy and is too hard to be killed, suspect eh isn't supposed to be, i am level 29, he is level 15, i still cannot kill him.

**Comment by Lheana** [comment]
Wilhelm Von Kleinbach is meant to be a level 15 hero. It's for a set so you must prove you are a good warrior!
I can kill him with my heal shaman level 40. Call some friends to help you ;)
