### ISSUE TITLE
Verantanes tower not showing as captured in quest:Raising the Empire Banner

### ISSUE THREAD

**Issue by VonRugen** [WarEmu/WarBugs#10533]
I have claimed this morning 10/1/2017 the Verantane tower in relation to my next part of the skaven token questline and it will not show the tower as being taken even after multiple captures. is the new system making this not show and is therefore the skaven questline a total dead end and waste of time now?

![serhawthorne_002](https://user-images.githubusercontent.com/31458882/31056818-2169eb30-a6a6-11e7-970e-43c2b56fd0d4.jpg)

**Comment by VonEpic** [comment]
Thanks, I posted about this for Destruction and we needed to know if Order wasn't getting the quest as well, thanks!

**Comment by VonRugen** [comment]
No problem, as long as this gets fixed

**Comment by VonRugen** [comment]
Played on Destro this seems to still not be working....

**Comment by VonEpic** [comment]
Raz just reopened the original ticket here:
https://github.com/WarEmu/WarBugs/issues/10483

**Comment by sioding** [comment]
OK after @Razielhell  reopened #10483  i close this now - no need to have two issues open for the same problem. thanks @VonEpic  for pointing this out
