### ISSUE TITLE
rampaging syphon

### ISSUE THREAD

**Issue by Toldavf** [WarEmu/WarBugs#1053]
![khorlar_001](https://cloud.githubusercontent.com/assets/13355649/9150791/2f0336a8-3de3-11e5-82ef-5016b3d12a19.jpg)
Screen shot is pretty self explanatory I think. Don't know what causes it :(

**Comment by ozarmidrashim** [comment]
Rampaging Siphon throws an exception if the user's group is in an invalid state. If this happens, the attack will repeat until all allies within 30ft of the caster are dead.
