### ISSUE TITLE
Engineer - Napalm grenade/explosive tactics

### ISSUE THREAD

**Issue by putmaikel** [WarEmu/WarBugs#10538]
I don't know if this is realy a bug or intented to work like this.
At the current moment morale 3 from engi (explosive tactics) is triggering off of napalm grenade.
If u then also spam blunderbuss u get alot of dmg down in aoe situations.
I do not know if magus has the same problem or not.
If i am in a napalm spec and i get a chance i will take some pictures and add them here.

**Comment by Kaelang** [comment]
This has recently been changed - so this should no longer be a valid report.

Closed.
