### ISSUE TITLE
Quest; Chapter 3: The Trail of Bones

### ISSUE THREAD

**Issue by Manatikik** [WarEmu/WarBugs#10530]
Quest tracker has invalid NPC ID. in Sigmar's Temple.

![grandtheo](https://user-images.githubusercontent.com/19319894/31053191-27e36668-a655-11e7-9a41-87f44a812fb6.png)

**Comment by SecretsOTheP** [comment]
Fixed, pending next patch. Finisher NPC should now spawn in War Quarter.
