### ISSUE TITLE
CtD on Book of Binding usage

### ISSUE THREAD

**Issue by VonEpic** [WarEmu/WarBugs#10534]
I've had several CtD's/DC's lately, most of them without error popups, but I have had at least three with this runtime termination error, two of them during usage of Book of Binding. 

![untitled](https://user-images.githubusercontent.com/31397093/31056719-67f2e7ac-a6a4-11e7-85cc-ae3b7b666158.png)

**Comment by VonEpic** [comment]
I've gotten the same error trying to log out/exit game from inside the game (not the main menu/character selection)

**Comment by sioding** [comment]
Sounds like client problems - and its strange that you encounter the issue while using the book of binding. The bugtracker is for ingame bugs only. Did you followed these points ?

https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=20075

**Comment by MaxHayman** [comment]
Going to close this as I assume it has been fixed over the years.
