### ISSUE TITLE
Inventory bug another junk

### ISSUE THREAD

**Issue by rollinseed** [WarEmu/WarBugs#10549]
Hello, 
I have a really problematic issue. My bagpacks seems empty at first look but, in reality it is full of "Another junk" item with "no icon set". i can't see what kind of items is it, i don't want to sell them randomly (because i'm not sure what i'm vending!) and when i send one of them by mailbox my friend see the "another junk" too. The problem is i will soon can't loot new item anymore (bags are almost full). 
I really hope you can solve my problem! 
I join a screenshot of my inventory to this message.
With respect, have a nice day, Rollinseed/Zygilzit.
![zygilzit_000](https://user-images.githubusercontent.com/32551788/31242884-cf53d1f6-aa08-11e7-91fd-95746681d30e.jpg)

**Comment by wargrimnir** [comment]
No idea where those came from, they're not in any drop tables that I could find.

Added a model id anyway. They are indeed junk, you can throw them out.
