### ISSUE TITLE
Icehearth Crossing Influence

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#10544]
Influence from BO Icehearth Crossing in Kadrin Valley gives inf to chapter 15 Dwarfs (seen on screenshots with timestamps in chat)

![sheykis_009](https://user-images.githubusercontent.com/18032193/31150908-ba763e32-a895-11e7-8042-e3fc0e64e705.jpg)
![sheykis_010](https://user-images.githubusercontent.com/18032193/31150909-ba77aaba-a895-11e7-8511-533f5771109e.jpg)
![sheykis_011](https://user-images.githubusercontent.com/18032193/31150910-ba7e61ac-a895-11e7-98a8-905a2aaf087b.jpg)

**Comment by Lheana** [comment]
This should have been fixed some weeks ago. Please comment here if the issue still occurs.
