### ISSUE TITLE
[Squig Herder] Farty Squig ability - instant summon not working

### ISSUE THREAD

**Issue by Paninii** [WarEmu/WarBugs#1054]
After using Farty Squig to blow up your squig, the next squig thats not the same one as the one that blew up, should be summoned instantly, but it gets summoned with a cast time.

Note: the error might be visual, as i think the pet gets summoned right away, but you're stil casting after the insta summon.

**Comment by Paninii** [comment]
just adding that if you jump while summoning a squig after exploding, you actually summon it, and there's no cast bar.
So, i gues this is low priority.

**Comment by Evildoor** [comment]
https://github.com/WarEmu/WarBugs/issues/1619 was closed with "Fix Pending" label, i guess the fix includes this ability as well. Closing.
