### ISSUE TITLE
Engineer - Gun Turret Buff to high ( 40% - 80% dmg boost instead of 20%)

### ISSUE THREAD

**Issue by Frostlatte** [WarEmu/WarBugs#10553]
Whats wrong?`
The Gun Turrets dmg buff increases the damage by 40% at ca. 50ft - 100ft

The Turret dmg increases the dmg for nearly 80% when the Target is beneath ca. 50 ft.

How should it be?
The buff should be increases the dmg by max of 20%

Sources:

a) Test it...with lvl 3 Engineer: 
Basic Dmg of gunblast was 65 on spider lvl 4
40% dmg boost when target is above 50ft. away --> 91 dmg
80% dmg boost when target is beneath 50ft away --> 112dmg

b) http://waronlinebuilder.org/#career=eng;    looking at gun turret notes
c) ingame Gun - Turret Ability Notes

**Comment by Lheana** [comment]
Are you sure it is not related to changes made for magus/engi?

**Comment by LestiArdisson** [comment]
I made a retest on life server.
You are doing more damage on gunblast at 50 ft because your turret has hit the spider with penetrating round at that moment. Reducing its armor.

If you deactivate Penetrating Round on Gunturret you should see all the time the same Damage.

**Comment by Frostlatte** [comment]
This would mean, the engineer gains a buff for ignoring 100% of the Armor for the period of the turrets firing ability... 

.that is that another issue, or ?!

**Comment by LestiArdisson** [comment]
40% is the full Damage Buff on the Engineer Turrets. On Life it was +20%, in RoR it is +40%.

The Armor Buff gave me less mittigation on the target. From 700 Damage comming through it changed to 900 Damage comming through. So at lvl 40 I cant see your damage Numbers.

You have also watched in the combat log that it were all normal Damages and not critical ones?

**Comment by Frostlatte** [comment]
Huhu...  thx for info..

- counted from 91 you're right.... count from 65 its nearly 70%  but if you are right, its another issue that you gain the Turrets deBuff for ignoring enemy armor.

- back to 40% ...so it is doubled to live Server. How is this justified?  Cause  an engineer hiding between his turret doing up to 70% more dmg with Gun turrets Armor Debuff... in close range. 
And you cannot do anything against it, instead of destroying, cause there is no CD for turrets.

- in comparison to my class ,the Squig Herder f. example, i see nothing comparable by similar abilities..with buffs, shots etc. 
-  Other classes like WL or MAgus get CDs for summoned Minons too..

**Comment by wargrimnir** [comment]
Wrong on enough points that we can simply close your ticket.

The bugtracker is not for balance. The was changed from live, it is intentional. If you want to have a discussion, use the forums.
