### ISSUE TITLE
DOK strength buff not working

### ISSUE THREAD

**Issue by kisskaa** [WarEmu/WarBugs#10556]
Consume strength is not working on my char Kisskaa.  When I use the ablity my strength is not increased by 76.

**Comment by kisskaa** [comment]
just found out that the dok str is capped at 905

**Comment by Lheana** [comment]
So we can close it?

**Comment by kisskaa** [comment]
Yes, one other thing is I’m getting a runtime error all the time is that a computer issue or the game?

Sent from Mail for Windows 10

**Comment by sioding** [comment]
Please use the technical support forum for the client issue. I will cluse this one now.
