### ISSUE TITLE
Enraged Beating

### ISSUE THREAD

**Issue by Annaise16** [WarEmu/WarBugs#10557]
Enraged Beating should have 7 hits. The following link has a youtube vid from 2011. At 1.12-1.16 on the vid, you should be able to see Enraged Beating hit 7 consecutive times in the combat log (bottom right of screen). The first hit crits for 69 points of damage with the next 6 hits doing 47 points each.
https://www.youtube.com/watch?v=uiJmhkbatLo

In the combat log, the hits are at:
12:05:15  69 dmg
12:05:16  47
12:05:17  47
12:05:17  47
12:05:18  47
12:05:18  47
12:05:19  47

**Comment by Torquemadra** [comment]
Try comparing it to whats on RoR before wasting everyones time.
