### ISSUE TITLE
[Items] Single swords are 'useful' for Warrior Priest

### ISSUE THREAD

**Issue by DedIago** [WarEmu/WarBugs#10560]
While wares are filtered as 'useful now or later', there are also shown single-handed swords. game mentions no class restrictions, only 'race: Empire'.
although it's only UI bug, WP still can not equip swords.
![theodoricus_016](https://user-images.githubusercontent.com/32600964/31315705-61ec98ee-ac26-11e7-9411-61354935a68f.jpg)

**Comment by sioding** [comment]
fixed with patch 21.10.2017
