### ISSUE TITLE
Flightmaster Wolfenburg

### ISSUE THREAD

**Issue by FruchtZucker** [WarEmu/WarBugs#10564]
Griffon War Wizard kills the flightmaster because it is hostile to Empire players.

Location: Wolfenburg Chapter 9 Empire

![theratnor_000](https://user-images.githubusercontent.com/921332/31333857-fd922384-aceb-11e7-8e59-36907ba593b7.jpg)

**Comment by grunbag** [comment]
Fixed in Next Patch
