### ISSUE TITLE
Bar Dawazbak ToK unlocks

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#10565]
Finishing every step of Bar Dawazbak PQ doesn't update story in the tome of knowledge (only one step is unlocked)
![sheykis_032](https://user-images.githubusercontent.com/18032193/31335240-fac94208-acf1-11e7-9810-fb8e8cab836a.jpg)

**Comment by Lheana** [comment]
I have recently verified all ToK unlocks for PQ stages, to be sure the first stage triggers the ToK unlock for the first stage of the correct PQ for instance. But there are many errors in the ToK like missing description of the unlock so the line vanishes when the unlock is triggered, or 4 stages noted in ToK but only unlocks for 3 stages. All these errors can not be fixed yet, as we need client control.
I am aware of all these bugs, and I will fix it asap, but not possible not. Thus, no need to report these bugs.
Closing this report as not fixable yet.
