### ISSUE TITLE
beastial tokens

### ISSUE THREAD

**Issue by miniozzy** [WarEmu/WarBugs#10575]
i have had it on 2 characters where no beastial token has dropped off the mobs that drop them the goatman on the path in averlorn being one and the troll under the bridge in troll country

**Comment by Lheana** [comment]
Bestial Tokens don't drop from NPC. Bestial Tokens are reward for ToK Bestiary unlock, thus you get it automatically when you trigger the unlock.
Verify you have obtained the unlock, and the unlock you obtained must give a bestial token (see [wiki](https://wiki.returnofreckoning.com/index.php/Bestial_Token) to verify)
According to your "description" Goremaw, the Chaos Troll in Avelorn triggers a ToK Bestiary unlock that give a bestial token. Nevertheless Bridge Troll under the bridge in Troll Country trigger a ToK Bestiary unlock that does NOT give a bestial token.
