### ISSUE TITLE
Wrong names at T1 destruction III norsca public quest

### ISSUE THREAD

**Issue by Stenier** [WarEmu/WarBugs#10578]
![issue](https://user-images.githubusercontent.com/32696070/31423517-f55144de-ae5d-11e7-8724-de87f358abd1.png)
![location](https://user-images.githubusercontent.com/32696070/31423518-f57176fa-ae5d-11e7-9d5a-15926a01d2b9.png)
Uploaded 2 pictures, that explain what is the bug.
The names are messed up.

**Comment by Lheana** [comment]
It is not the names that are messed up, but a general bug with PQ stages that have multiple objectives: numbers are reverted.
