### ISSUE TITLE
Dwarf Tier 2 RVR influence rewards are unavailable

### ISSUE THREAD

**Issue by DedIago** [WarEmu/WarBugs#10576]
Influence is full, but reward icons aren't even shown and there is no way to collect them.
![theodoricus_019](https://user-images.githubusercontent.com/32600964/31414654-ae8d3ab6-ae27-11e7-8f86-7c72e0201b3d.jpg)

**Comment by Lheana** [comment]
Have you tried with the rally master of Marshes of Madness?

**Comment by DedIago** [comment]
actually, it's MoM rally master who's buggy. but yes, i forgot about the second one. rally master in Barak Varr  works fine, all rewards are shown and collectable.

**Comment by Lheana** [comment]
We can not fix it yet. When there are several rally masters for the same influence rewards, only one of them works.
