### ISSUE TITLE
Skaven quest

### ISSUE THREAD

**Issue by Beybisi** [WarEmu/WarBugs#10577]
Hey,

Today i had started skaven quest but at first step when i selected skaven token i did not get any token then at 2. step it did not let me to select skaven token but when i selected both of token which were skaven token and symbol of the horned rat it gived me both of them.

So i can not complete 4 token to get the ring .

please fix this and give my first token :)

**Comment by Lheana** [comment]
Have you done the 4 quests?

**Comment by Beybisi** [comment]
No i stop to continue becouse lots of people have same problem and will note get the reward

**Comment by Razielhell** [comment]
quest name that you couldn't pick the token please?

**Comment by Beybisi** [comment]
i dont remember the quest name but when you enter the portal in altdorf center, it port you to the maze and at the end of the maze there is a quest giver who want you to kill some skavens and champions near him

**Comment by Beybisi** [comment]
if you still need quest name i can create a new character to get mount :)

**Comment by Lheana** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366#p118993

**Comment by Beybisi** [comment]
Ohh ok then . i recorded a video about this quest. 
and the name of quest is " A Last Request" i could not take my token again :)
