### ISSUE TITLE
The Power of War "completed" Bug

### ISSUE THREAD

**Issue by Solutar** [WarEmu/WarBugs#10579]
Hello, first of, sorry for my English.

My Quest Book told me that i finished the Quest "The Power of War", while i was fighting in ORvR in Caledor. So i went to the WC to submit the Quest to the Questgiver, that dude with the Hood in every T4 WC. But instead of getting the Reward of the Quest, i got the Message, my Backpack is full, i have to make space to submit the Quest. so i checked my backpack, and yeah, my Main Inventory is full, but the part of the Backpack where i keep all the Medaillions and Emblems etc. was not full, so i was kinda confused but okay, i made space in my Main Inventory and tryed to submit the Quest again, but again i get the Message, your backpack is full, you need to make space. So this seems to be very clearly a Bug, would be great to get a bit of Help so i can submit the Quest finally, took a while to kill all those Order.

Thanks in advance,
Solutar.

**Comment by Lheana** [comment]
Have you tried relogging?

**Comment by Solutar** [comment]
Yes. Didnt worked out.

**Comment by Lheana** [comment]
I advice you to abandon the quest, and to retake it. And verify you have free slot in your inventory next time before validating the quest.

**Comment by sioding** [comment]
No answer for 23 days. Close for now.
