### ISSUE TITLE
Squig Herder - GasSquig ArmorBuff

### ISSUE THREAD

**Issue by Frostlatte** [WarEmu/WarBugs#10572]
When the Gas Squig is active, the Herder should gain an increased Armor by the Amount of his currently weared armor.

Whats wrong?
The buff is working for a short time, when the squig dies and you summon an other squig.

Source
http://waronlinebuilder.org/#career=sh;   gassquig tooltip

**Comment by Torquemadra** [comment]
?

**"Your armor is increased by the amount of armor gained from items as long as your Squig is alive."**

No gas squig = no armour buff

I dont understand what your issue is.

**Comment by Frostlatte** [comment]
When your gas squig is alive you do NOT get the buff... 
Simple..

Gas squig = no armour buff 

:)

**Comment by Torquemadra** [comment]
I need evidence of this and use .getstats

**Comment by Frostlatte** [comment]
Hello again,

thanks for the .getstats advice. Didnt know that tool. 

So its seems to be a notification bug in the DefenseWindow...?. there is noticed 1000 Armor at the same time .getstats shows 2000.
