### ISSUE TITLE
Magus - Unholy Empowerment buff

### ISSUE THREAD

**Issue by Niobandi** [WarEmu/WarBugs#10574]
When a Magus summon a daemon and stay close, he gain the Unholy Empowerment bonus who increase his damage.

It should increase damage by 4% each 2 secondes to a maximum of 20% bonus ( 5 stacks )

At this time it increase damage by 5% each 2 secondes to a maximum of 40% bonus ( 8 stacks )

( On the career builder the Pink Horror summon is marked with 5% each 2 secondes to a maximum of 40% but in the game it is marked like the other at 4% each 2 secondes to a maximum of 20%. Don't know the correct one )

As you can see, the bonus stack 8 times and grant 40% damage bonus with every deamon.
![azkhanar_001](https://user-images.githubusercontent.com/16079024/31375809-0b3df726-ada3-11e7-82ed-8edaed8e4350.jpg)
![azkhanar_003](https://user-images.githubusercontent.com/16079024/31375830-21992d06-ada3-11e7-89b7-4ef3ef6e6858.jpg)
![azkhanar_004](https://user-images.githubusercontent.com/16079024/31375835-25804846-ada3-11e7-8a51-bb06ca1f05ea.jpg)

Here you can see my Flickering Red Fire do 126 damage without the bonus.
![azkhanar_000](https://user-images.githubusercontent.com/16079024/31375708-b86fe338-ada2-11e7-84de-0999ec6deb82.jpg)

And after with the bonus it deal 176.
![azkhanar_002](https://user-images.githubusercontent.com/16079024/31375915-649a4c98-ada3-11e7-8be3-63afc4da88ba.jpg)

**Comment by Zealote** [comment]
It was changed to work this way on RoR. See this thread on forum: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=8768

**Comment by Niobandi** [comment]
Oh ok, don't know of this, sorry.
