### ISSUE TITLE
Chaos T1 Chapter 3 PQ macabre fervor

### ISSUE THREAD

**Issue by miniozzy** [WarEmu/WarBugs#10573]
public quest is bugged and your get no loot from the chest at the end of the pq

**Comment by Razielhell** [comment]
No need to confirm this. It's true....12 level player can't roll. Looks like players above 16 lvl get loot.

**Comment by Lheana** [comment]
Are you sure you have finished the PQ? Cause the area of this PQ is really bugged and NPCs for last stage are out of the PQ area. I tried this PQ and I had bag.

**Comment by Razielhell** [comment]
Tried with 12 lvl player and didn't get the bag. Needs confirmation from people.

**Comment by sioding** [comment]
Fixed with patch from 4.11.2017
