### ISSUE TITLE
In-game Logging bug

### ISSUE THREAD

**Issue by DoctorMerril** [WarEmu/WarBugs#10584]
Hello everyone.
I have a strange bug - when i logging in to the game my screen is black, there is no sound, i can see only buttons, but no background like on the picture:
![image](https://user-images.githubusercontent.com/32715084/31456491-9a8832b4-aec2-11e7-9429-4dc3b9093ce0.png)

And when i press "Play", after long loading, game just crahes.
#

**Comment by sioding** [comment]
please use the technical support forum for this issue. the bugtracker is for game bugs only.
