### ISSUE TITLE
Wrong NPC with merchant icons - Barak Varr

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#10586]
Dwarf mobs have merchant icon at 26k,20k in Barak Varr, and they are not interactable
![sheykis_039](https://user-images.githubusercontent.com/18032193/31481115-f7f94834-af21-11e7-9ae8-43af533b5fb1.jpg)

**Comment by sioding** [comment]
Fixed with patch from 13.10.2017
