### ISSUE TITLE
Howling Gorge Terrain

### ISSUE THREAD

**Issue by biotek7** [WarEmu/WarBugs#10585]
I got stuck in terrain during the Scenario and could not get out of my own accord, even with the /stuck command. This happened during a melee at the center objective when I got hit by a knockback. The enemy team had a very small window to get LOS on me and ignored it for most of the match.
![kyrela_000](https://user-images.githubusercontent.com/32723768/31475185-0336eac4-aec5-11e7-8695-98d473dde2fb.jpg)

**Comment by NorKalli** [comment]
Filled

**Comment by NorKalli** [comment]
![image](https://user-images.githubusercontent.com/19868634/39390631-4c8737ec-4a4c-11e8-99ab-e8d279fb7bd3.png)

**Comment by sioding** [comment]
Fixed with Hotfix from 29.04.2017
