### ISSUE TITLE
Witch Elf tactic Masterful Treachery

### ISSUE THREAD

**Issue by kyranria** [WarEmu/WarBugs#10581]
After hitting an ennemy with Treacherous assault, Vehement Blades or Enfeebling Strike, you will deal 15% more damage for 10 seconds.

Enfeebling Strike: https://imgur.com/A2O5oi4 tactic it works
Vehement Blades: https://imgur.com/K2ZT5aQ tactic it works
Treacherous assault: https://imgur.com/JajvyT8 tactic it doesn't work

**Comment by Torquemadra** [comment]
melee channels are a little problematic atm and need to be reworked

**Comment by sioding** [comment]
Fixed with patch from 13.10.2017
