### ISSUE TITLE
critical error on started menu and application crashing when the game's supposed to be started

### ISSUE THREAD

**Issue by arthason** [WarEmu/WarBugs#10588]
Enviropment: win 10 pro x64. (but as i know this doesn't depend on hardware and soft).
Result: critical error on started menu and application crashing when the game's supposed to be started
Expected result: a characters and a loading screed are visible. The game starts succesfully.

**Comment by sioding** [comment]
Thanks für the report, but please use the technical support forum for client issues. The bugtracker is only for game issues.
