### ISSUE TITLE
Lost Gold Bag after Server Restart.

### ISSUE THREAD

**Issue by Solutar** [WarEmu/WarBugs#10580]
Hello, first of, sorry for my English.

On Saturday Morning i was playing ORvR, but not in T4 cause all T4 was not open for some reason, but T2 was. So i played ORvR in Swamp in the Greenskin T2 and Destro won AND i even won a Gold Bag. But instead of receiving my Reward, the Server restarted and i never got the Message with the Bag. Is any Help possible?

Thanks in advance,
Solutar.

**Comment by Razielhell** [comment]
#10279 Thanks for the report.
