### ISSUE TITLE
I can't log in.

### ISSUE THREAD

**Issue by RichardLeeSmith69** [WarEmu/WarBugs#10582]
This thing says my email is in use.  So I tried the other thing, and it says my login Is incorrect.  There isn't a way to fix this.  Please help.  If you are willing, can you go in and delete my email, and let me register again?
Thank you.

**Comment by RichardLeeSmith69** [comment]
So I managed to log in and download the client, but I am getting an error trying to get things to run.  It says the patch client was unable to retreieve the file [rather.prod.sig] from the patch server(0 total errors encountered).  Please try the patch operation again in a short while.

**Comment by sioding** [comment]
please use the technical support forum for this issue. the bugtracker is for game bugs only.
