### ISSUE TITLE
Marauder - Career Mastery Points

### ISSUE THREAD

**Issue by endlesspank** [WarEmu/WarBugs#10599]
Hey, old time player here! Was rocking the Marauder and decided to utilize my Mastery points and acquire some abilities. I placed 5 points into the Brutality tree, Corrupted Edge and Guillotine was never added to my skill list or tactics. I then proceeded to "re-spec" my character into the Monstrosity tree (to see if issue was exclusive to one tree). Unfortunately, I experienced the same problem neither gaining the equivalent skills for Monstrosity (Hulking Brute & Wave of Mutilation). Now I'm not sure if I missed something, but I am confident that there's an "issue". Thank you for your time.

**Comment by wargrimnir** [comment]
You need to spend a point on the abilities and tactics in the tree.

**Comment by endlesspank** [comment]
I am embarrassed! I realized that shortly afterwards. Thank you for your
speedy response.  :)
