### ISSUE TITLE
Destruction PQ chapter 9 Dwarf vs Greenskin

### ISSUE THREAD

**Issue by Throatripper** [WarEmu/WarBugs#10596]
One of the elite chapter 9 rewards is a twohand axe for choppa wich has the icon symbol of a ring.
Unsure if it bugs out when equiped or if it has no skin/appearance as well.

**Comment by Razielhell** [comment]
I don't see anything. Can you confirm please? https://image.prntscr.com/image/6tDQAHZvTuu8BvVI9iIb7A.png

**Comment by Throatripper** [comment]
Hello! I Will submit two screenshots to confirm.
First one is of the correct 2h axe and the second one is the 2h axe för choppa with the ring symbol/Icon called the squigfeedas big choppa.


Skickat från min Samsung Galaxy-smartphone.

-------- Originalmeddelande --------
Från: Razielhell <notifications@github.com>
Datum: 2017-10-15 08:47 (GMT+01:00)
Till: WarEmu/WarBugs <WarBugs@noreply.github.com>
Kopia: Throatripper <john.cederblad@live.se>, Author <author@noreply.github.com>
Rubrik: Re: [WarEmu/WarBugs] Destruction PQ chapter 9 Dwarf vs Greenskin (#10596)


I don't see anything. Can you confirm please? https://image.prntscr.com/image/6tDQAHZvTuu8BvVI9iIb7A.png

**Comment by Throatripper** [comment]
![brainerror_000](https://user-images.githubusercontent.com/22511042/31583205-bfa14852-b196-11e7-92ab-489398d0458b.jpg)
![brainerror_001](https://user-images.githubusercontent.com/22511042/31583206-bfb7d9c8-b196-11e7-8ce1-cf98f34870c1.jpg)

Incase you didnt get the screenshots via phone.

**Comment by Throatripper** [comment]
Upon further investigation, i picked the bugged 2h axe and once equipped in the main weapon slot it completely lacks a icon and all skills are disabled. 
![brainerror_003](https://user-images.githubusercontent.com/22511042/31583610-1b2e6206-b19f-11e7-91a3-b199b792d001.jpg)

Btw, thanks for all your hard work :)

**Comment by Razielhell** [comment]
Thanks for these. Will be fixed next Patch!

**Comment by sioding** [comment]
Fixed with patch 21.10.2017
