### ISSUE TITLE
[Marauder] Ferocious Assault toughness buff doesn't stack with Hulking Brute tactic

### ISSUE THREAD

**Issue by Zealote** [WarEmu/WarBugs#10594]
Tested on unbolstered level 25 marauder. No gear or renown spent.

Hulking Brute (HB) tactic gives +100 toughness.
Ferocious Assault (FA) gives +130 strength/toughness.

- With HB, toughness correctly went from 110 to 210 (image a).

- With HB and FA, toughness went from 210 to 240 (image b), i.e. it's only buffed by the extra 30 points of FA.

- The strength buff portion of FA stacks with Brute Force tactic. See image c below, in which my strength is 261 (up from 161 due to Brute Force) and then 391 due to FA. 

Needs to be tested whether it's a general issue with mastery tactics and not just HB. E.g. does FA's strength buff stack with Gift of Brutality (str/ini buff)? I don't have the money to re-spec to test it and then re-spec again back to normal.

a)
![test1](https://user-images.githubusercontent.com/10598420/31575161-121dd33a-b0d8-11e7-8e79-a9e1575126a3.png)
b)
![test2](https://user-images.githubusercontent.com/10598420/31575163-2b67613a-b0d8-11e7-83c6-4b0d988f5c11.png)
c)
![test3](https://user-images.githubusercontent.com/10598420/31575233-ba80be92-b0d9-11e7-9dae-9c453488c77c.png)

**Comment by wargrimnir** [comment]
This behavior is intended. Each 'type' of buff stacks with each other, but not itself. Potion/Tactic/Ability are the three that stack together.

**Comment by Zealote** [comment]
Potions/tactics/abilities stacking was my understanding as well, so shouldn't HB (a tactic) stack with FA (an ability)?

**Comment by wargrimnir** [comment]
Guess this can be open then...

**Comment by Torquemadra** [comment]
theres a construction issue as its working on an obsolete aspect of the monstrosity buff

8403	You are imbued with the Gift of Monstrosity, warping and twisting the flesh of your arm into a vicious club. This grants you improved Toughness well as the ability to launch powerful club attacks.

will need to rework it

**Comment by sioding** [comment]
Fixed with patch 21.10.2017
