### ISSUE TITLE
Dark Elf Chapter 2 PQ - The Watchtower

### ISSUE THREAD

**Issue by Throatripper** [WarEmu/WarBugs#10591]
Hello

At the second stage of this PQ (The Watchtower in the Dark Elf T1 pairing) 6 Arcane masters spawn as objectives and each Arcane Master is guarded by two swordmasters, trouble is these two guards (12 in total) cannot be targeted unless you have no target and let them attack you so the target gets auto picked or you can spam aoes. Neither can they be looted, even when the option "loot nearest" is hotkeyed.

Thank you
![rorbug1](https://user-images.githubusercontent.com/22511042/31552211-15c017d8-b037-11e7-93b9-040045ae8f3a.jpg)
![rorbug2](https://user-images.githubusercontent.com/22511042/31552212-15dadc62-b037-11e7-8b3e-a626e99896e4.jpg)

**Comment by Razielhell** [comment]
Thank you for the report. Fixed in next.

**Comment by sioding** [comment]
Fixed with patch 21.10.2017
