### ISSUE TITLE
"will of the warboss" buggy

### ISSUE THREAD

**Issue by Lhunara** [WarEmu/WarBugs#10595]
Hello, just reporting a bug in that quest,
At step 8 of the quest, when we have to find 10 "Boom Powder", there is absolutely nothing to deal with in the designated area !!! all kegs there are static (we can't interact with them) so we can't finish taht quest...

PLEASE HELP

**Comment by sioding** [comment]
Just to make sure - you followed the wiki suggestion:
https://wiki.returnofreckoning.com/index.php/Greenskins_T3_Epic_Quest_Will_of_the_Warboss#STEP_8

"(you can click spam on one)" and nothing works?

**Comment by Razielhell** [comment]
You can't spam on one cause they are part of the Public Quest. Is your issue resolved? I could click it just fine. You need to progress Stage I. Boom Powders appear on Stage II.

**Comment by sioding** [comment]
No response sind October - close.
