### ISSUE TITLE
hotbar bug

### ISSUE THREAD

**Issue by lopinoid** [WarEmu/WarBugs#10592]
https://youtu.be/8XQBSPVucCc

**Comment by Razielhell** [comment]
Can't see the video mate. It ask me to create an account. Could you host it somewhere else like Youtube and post again please?

**Comment by lopinoid** [comment]
Update

**Comment by Razielhell** [comment]
First and second bars have number 1 that's why. Try scrolling one of them to 2. https://image.prntscr.com/image/cTIHpSd2TUWfBfJKxCXU_Q.png

**Comment by Kaelang** [comment]
Videos no longer work and has no information.

Closing.
