### ISSUE TITLE
Tome of Knowledge "It's in the Bag"

### ISSUE THREAD

**Issue by Cofry324** [WarEmu/WarBugs#10593]
"It's in the Bag" TOK unlock does not work on destruction's side. We are supposed to kill 6 young basilisks and then talk to Gubs in chapter 16, Black Crag. By completing this, we are supposed to get a bestial tome tactic fragment but nothing happens when you talk to gubs after the young basilisks are killed

-Rylde of Destruction

**Comment by Lheana** [comment]
We can not make the ToK unlock as original yet.
So please, before report, read the Wiki[https://wiki.returnofreckoning.com/index.php/It%27s_in_the_Bag](url)
