### ISSUE TITLE
Blightstone Axe have 2h stats

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#1060]

**Comment by milosxe** [comment]
There's a number of weapons for mara with broken stats.
Weapon dps seems fine, Blighted slayer obviously has 2hander speed, and all +stats are for a 2hander weapon. 
Blighted slayer with +52str/ws is from a ch8 quest (can't remember the quest name), Plaguewood slayer is ch8 inf reward, Blightstone Blade and Axe are ch9 inf rewards, Chaosaxe of the Wicked is a mob drop.
![blutausnord_007_cr](https://cloud.githubusercontent.com/assets/13332067/9179844/62ee6a42-3f9f-11e5-8713-f6dbe2030429.jpg)

**Comment by Radiantknight** [comment]
Those same weapons are rewards/drops for Chosen too.
But if Arsenal of WAR to be believed, stats on Plaguewood Slayer are correct, except it lists it as main hand only: http://www.arsenalofwar.com/items?i=2181
There's also http://www.warbits.com/warhammer-search.html with same stats for that axe

**Comment by Reggaewaldo** [comment]
The sure is a "both hands" thing in the Arsenal DB please refer to this item:
http://www.arsenalofwar.com/items/Destruction/Sentry%20Big%20Choppa

Plaguewood Slayer is correct according to:
http://www.arsenalofwar.com/items/Destruction/Plaguewood%20Slayer
http://war.mmodb.com/items/plaguewood-slayer-104134.php

Blighted Slayer is correct according to:
http://www.arsenalofwar.com/items/Destruction/Blighted%20Slayer
http://war.mmodb.com/items/blighted-slayer-100518.php

Chaos Axe of the Wicked is correct according to:
http://war.mmodb.com/items/chaosaxe-of-the-wicked-103996.php

Blightstone Blade is correct according to:
http://war.mmodb.com/items/blightstone-blade-93391.php

Blightstone Axe is correct according to:
http://war.mmodb.com/items/blightstone-axe-96248.php

So without any referance online I'm hesitant to make any change. I will run it by Dana and see what he thinks.

**Comment by Evildoor** [comment]
Reduced stats on Slayer of the Wicked, Blightstone Blade, Blightstone Axe, Blighted Slayer, Chaosaxe of the Wicked, Plaguewood Slayer.
This maybe an imperfect solution (proper solution means that if some of these are twohanders then it should be checked, suitable model should be found, etc), but it was decided that for now we apply a hotfix to item stats, which means, among other things, that PVE items are ignored unless they are too strong.
