### ISSUE TITLE
Brutal Smash willpower buff is not increasing Disrupt 

### ISSUE THREAD

**Issue by Garnerr** [WarEmu/WarBugs#10602]
![](https://image.prntscr.com/image/9EuBVn-9Td2SR_kkoay9oA.png)
Brutal Smash gives your Dark Protector Str and WP buff, but I noticed the added willpower was not increasing my Disrupt chance. It also gives yourself the Str and WP buff.

![](https://image.prntscr.com/image/FeOwLY8ER_yOK54ofL51nw.png)
This is before Brutal Smash is applied,

![](https://image.prntscr.com/image/i8rDAI31SZauMVJXXofYlA.png)
This is after Brutal Smash is applied,

**Comment by sioding** [comment]
**Thanks for the report.** Can you please do the same screenshots with using the ".getstats" command? Thanks

**Comment by Garnerr** [comment]
![](https://image.prntscr.com/image/jEHG8Ns_Rqi037cTJr62TQ.png)
Before it's applied,


![](https://image.prntscr.com/image/WlXEGIDjSRuUY6EFAC8Hlw.png)
After it was applied,

I also got someone in my party to check and see if it was working for my Dark Protector and he said it wasn't.

**Comment by Zealote** [comment]
The stats shown in char window are unreliable and .getstats only shows flat % modifiers: not, for example, the additional disrupt granted by a Willpower buff.

No reason to think it isn't working but the only way to test it (that I'm aware of) would be by doing a large number of trials with and without buff and comparing disrupt rate.

**Comment by SecretsOTheP** [comment]
GetStats is showing strength increases from buffs in those screenshots. It's possible willpower was forgotten about for the ability. I am checking into this.

**Comment by Zealote** [comment]
How do you mean Secrets? Getstats is showing willpower going from 133 to 469, which matches Brutal Smash's tooltip.

**Comment by Garnerr** [comment]
Yea it's giving the str/willpower buff like intended, but i'm unsure if the willpower that is given is increasing my/dark protector's disrupt.

**Comment by Torquemadra** [comment]
getstats doesnt translate this, the paperdoll does.

**Comment by Torquemadra** [comment]
fix incoming next patch

**Comment by sioding** [comment]
Fixed with patch 21.10.2017
