### ISSUE TITLE
Name and Login Problems

### ISSUE THREAD

**Issue by TimoTimeYoutube** [WarEmu/WarBugs#10604]
Good day,
at the beginning I apologize for my bad English (German manufacture below)

I was logged into my account this morning and deleted 1 char, because I wanted to have his name for a new one.
However, I could not create a new one with the name (earlier, this went for why?)

After some try I could not play with any of my Chars games, it did not happen anymore.

After further try I could no longer log on to my account, even after a password change does not go. Please help.

Account name: TimoTimeYoutube
Accountemail: timotimeyt@gmail.com

(German)
Guten Tag,
am anfang entschuldige ich mich für mein schlechtes Englisch (Deutsche anfertigung unten)

Ich war heute morgen auf meinem Account Eingeloggt und habe 1 Char gelöscht, da ich seinen Namen für einen neuen haben wollte.
Ich konnte jedoch keinen neuen erstellen mit dem Namen (früher ging dies, warum?)

Nach einigen versuchen konnte ich mich auf einmal mit keinem meiner Chars Spielen, es passierte nichts mehr.

Nach weiteren versuchen konnte ich mich nicht mehr auf meinen Account einloggen, auch nach einem Passwort wechsel geht es nicht. Bitte um Hilfe.

Accountname: TimoTimeYoutube
Accountemail: timotimeyt@gmail.com

**Comment by AdoredTV** [comment]
Same issue for me where I deleted a character and now cannot name another one with the same name.

I also briefly had the issue of not being able to log in on any of my characters but this was resolved by restarting the client and I think creating a new character (with a different name, obviously).

**Comment by sioding** [comment]
This one is from the patchnotes:

> Natherul
>-Added a limit so you cant make a character with a name that has been deleted before the server >restarts (this is because if you make one, it wont be playable anyway since the old character is still >cached)

Just wait until we have a server restart.

**Comment by TimoTimeYoutube** [comment]
Ohhh thx.
Butter WhatsApp is with the Logins Problems?

Am 15.10.2017 21:54 schrieb "Sio" <notifications@github.com>:

**Comment by sioding** [comment]
@TimoTimeYoutube warte bitte einfach den nächsten reboot ab. Ich glaube du hast mit deinen ganzen Versuchen was kaputt gespielt.
