### ISSUE TITLE
FormatException in PQ "da orcwerks"

### ISSUE THREAD

**Issue by ahsokah** [WarEmu/WarBugs#10607]
Was doing the PQ when a "Lobba'd Squig" said "FormatException was thrown from StringToNumber. This object will be destroyed."
Later a white lion pet did the same and a few other npc's.
![flurrybob_008](https://user-images.githubusercontent.com/16574741/31591316-d199aa26-b21e-11e7-9497-77b530752b24.jpg)

**Comment by Lheana** [comment]
It seems like it has been fixed.
