### ISSUE TITLE
kamilla the vanishing

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#10605]
this was the result when i killed the lair boss earlier today (GMT timezone), her corpse should have been on the floor roughly in front of me, it appears she has not respawned since then...that was about 8 hours ago

![lyrael_000](https://user-images.githubusercontent.com/16922842/31589381-6dbfabde-b1f8-11e7-86a4-65f5dd26bf80.jpg)

**Comment by wargrimnir** [comment]
Unless you've been standing there for 8 hours, we will assume someone else has taken the kill and thrown you off your rotation timer.

**Comment by Lheana** [comment]
It is not the first time there is a similar problem with lair bosses. Always the same things: players kill the NPC, the message "NullReferenceException' and then the boss don't respawn.
#10505 #10423 #10307 
I think there may be a real problem.

**Comment by MightyPhred** [comment]
if that had happened warg there would be a corpse somewhere in the lair, theres no boss, and no corpse, ive seen no talk of anyone putting up a group or successfully killing her in the almost 24 hours since this happened, and i was actually present at the time she should have respawned, roughly 2-3 hours after i took the screenshot, she never respawned, although the elf zone boss came back as she was supposed to, i checked on her spawn and found her alive shortly after deciding that the empire lair was bugged, in the previous kill-cycle i killed the empire boss, followed by the elf one

i also logged in my witch elf just before writing this post, there is still no boss or corpse-of present anywhere in the lair

**Comment by sioding** [comment]
Fixed with patch from 4.11.2017
