### ISSUE TITLE
Squigherder. No morale gain when pet only is on combat. 

### ISSUE THREAD

**Issue by AlistaireCrowley** [WarEmu/WarBugs#10603]
When pet is in agressive stance and attacks a mob there is no morale gain for Squigherder. Even tho it say I am in combat.

**Comment by sioding** [comment]
Tried it with the help of another player and it´s true. Maybe it´s an issue for all pet classes. Morale gaining only works when the pet owner also attacks.

**Comment by wargrimnir** [comment]
This is intended. You don't get to send your pet into danger while you hang out in safety gaining morale.
