### ISSUE TITLE
Sigmar's Grace(WP wounds buff) Generating renown

### ISSUE THREAD

**Issue by wwright72** [WarEmu/WarBugs#10606]
My brother and I were doing some testing and we found that Sigmar's Grace(WP wounds buff) was awarding 30 renown points for not only the caster but for the recipient as well, regardless of where you cast it. We tested in the lake, out of the lake, on a BO, off a BO always 30. But this only happens after pvping/getting killed in a rvr lake a few times from my testing.
![sigmar s grace bug](https://user-images.githubusercontent.com/29286837/31590619-06e94650-b1d9-11e7-82dd-b0f88b42246f.jpg)

(Disclaimer; i'm not the best at math but...) 
Let's say for example 6 WPs are in a party spamming this, they can potentially generate something like 1080 renown per person per 5 seconds. This could be very abusable, allowing people to power level RR without having to pvp.

**Comment by dalen** [comment]
Wouldn't jumping off a cliff and firing other heals have the same effect?
