### ISSUE TITLE
Terminate

### ISSUE THREAD

**Issue by Korgazar** [WarEmu/WarBugs#10614]
Had a weird bug where i would instantly die and my combat log would say " your terminate hits you for 30000 damage" got this bug in Caledor and apparantly it's an elevation bug from live it fixed itself atleast after i ported from the zone.

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format. 

You can help us by following these bugreport rules: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Korgazar** [comment]
![korgazar_003](https://user-images.githubusercontent.com/32879429/31686440-6c43e7b8-b386-11e7-81a7-83534c177b4e.jpg)
