### ISSUE TITLE
Flightmaster Dworrag Coinbringer Dwarf Ch12

### ISSUE THREAD

**Issue by garytownsend** [WarEmu/WarBugs#10611]
The flight master at the dwarf chapter 12 camp has decided he would rather be a part of the furniture and has melded with his table.

**Comment by garytownsend** [comment]
![image](https://user-images.githubusercontent.com/32038375/31641900-afd6f992-b29c-11e7-8255-c50f4bc37d82.png)

**Comment by garytownsend** [comment]
![shalk_001](https://user-images.githubusercontent.com/32038375/31641918-d6780a00-b29c-11e7-8929-1fa3cfa084c9.jpg)

**Comment by wargrimnir** [comment]
Seems to be appropriately placed.
