### ISSUE TITLE
[Chosen] Tactic; Feed on the Weary, not working properly

### ISSUE THREAD

**Issue by cimator** [WarEmu/WarBugs#10610]
Just for info, here are the tactic and the ability it affects;
![tactic](https://user-images.githubusercontent.com/17130290/31638702-ab1e6dae-b2dd-11e7-9d46-d59af5d2e3a0.png)
![skill2](https://user-images.githubusercontent.com/17130290/31638703-acabe228-b2dd-11e7-8d65-a9cbd3952c13.png)

While the tactic is equipped, the ability gives the enemy target 40 ap instead of draining it.
Short video proof of me testing it; https://youtu.be/EeAewXIFnd0

**Comment by sioding** [comment]
fixed with patch from 21.10.2017
