### ISSUE TITLE
Fall Death In SC - Stonetroll Crossing

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#10616]
Died to falling in sc while being at around 80% health, at the souther part of the tree in the middle where pacifier is located (wasn't falling at the time, just standing and fighting WE)

![sheykis_006](https://user-images.githubusercontent.com/18032193/31691063-01b926ba-b395-11e7-8bb4-726a12838352.jpg)

**Comment by sioding** [comment]
Hm. Did you jumped or did you just walked over the edge?

**Comment by szejoza** [comment]
I didn't jump or move, wasn't in any spot to fall either, I died on a flat ground
Happened again today in completely different place (Eataine, Manor BO)
![sheykis_010](https://user-images.githubusercontent.com/18032193/31739257-a2474752-b44d-11e7-846c-a99dc8ac17ef.jpg)

**Comment by szejoza** [comment]
https://vimeo.com/240269751

another record of my death, same issue, instant fall dmg on flat
