### ISSUE TITLE
Quest - Eye for an eye

### ISSUE THREAD

**Issue by Niobandi** [WarEmu/WarBugs#10613]
The Order quest " Eye for an eye " where you have to kill " Ennemy Choppa " in the Marshes of Madness didn't work and have no map tracker.

**Comment by Niobandi** [comment]
After some scenario it appear that Choppa Player count in this quest, while the quest asks to kill Black Skull Choppa of the public quest near the camp.

**Comment by sioding** [comment]
Fixed with patch from 28.10.2017
