### ISSUE TITLE
WEs cannot stealth in the air while moving anymore?

### ISSUE THREAD

**Issue by sofronguy** [WarEmu/WarBugs#10622]
I don't know if this is intentional but Witch Elf cannot longer stealth while moving in the air. What i mean is for example if you are mounted or on foot and you are moving forward, and you jump and then press 'shadow prowler' the stealth casting bar will get interrupted before landing. 

Before the last couple of patches you could be mounted, jump forward, stealth while in the air and land more or less stealthed.

**Comment by sioding** [comment]
Thanks for the report. Yes you should not be able to do things while in air.  This was fixed a while ago, but broken for some pathces. Now its fixed again.
