### ISSUE TITLE
Guild invite bug

### ISSUE THREAD

**Issue by Lo-Taren** [WarEmu/WarBugs#10621]
So since the double exp event ended we've had some issues with inviting players to our guild, we get a number of bugs.
1. You are not in the same zone and cannot invite
2. Player is already in a guild
3. Your guild is full 

We tried to fix this by relogging and removing a guild member but still had the same three issues in various orders.

**Comment by sioding** [comment]
We have some issues with CTDs - thats why things got changed: 

> Natherul
>- Players can no longer accept guild invites to guilds with more then 78 players. Please note that this change is experimental and can be revoked at any point, I do suggest however that any big guilds sort down to 77 players or less as I will ignore any talks from guilds with numbers above this to track down the issue.

**Comment by Lo-Taren** [comment]
Okay that makes sense, the guild has 275 players in it, before I kick a LOT of people and make some people mad I'd kinda like to know how long the experiment will last.

Thanks :)
