### ISSUE TITLE
Quest - Disenchanting the Stone

### ISSUE THREAD

**Issue by JeraSpites** [WarEmu/WarBugs#10625]
Yes, I see there was one with the exact same problem that was closed already.  However, it is not working for me.

The adorned stone purple things are not giving me the dark gems.

![jyrha_007](https://user-images.githubusercontent.com/20675668/31744074-0732342c-b423-11e7-9151-11cfd9490d6d.jpg)
![jyrha_008](https://user-images.githubusercontent.com/20675668/31744076-0998445e-b423-11e7-92a2-c99a36e37e44.jpg)
![jyrha_009](https://user-images.githubusercontent.com/20675668/31744077-0bce07c2-b423-11e7-8703-6f2ff54af205.jpg)
![jyrha_010](https://user-images.githubusercontent.com/20675668/31744080-0f578a08-b423-11e7-84fd-518ac6306f21.jpg)
![jyrha_011](https://user-images.githubusercontent.com/20675668/31744083-1233e7f8-b423-11e7-9a71-e9696d414ef8.jpg)
![jyrha_012](https://user-images.githubusercontent.com/20675668/31744086-15109b9c-b423-11e7-98e1-3e3ea4e8c1ef.jpg)
![jyrha_013](https://user-images.githubusercontent.com/20675668/31744090-18df3b02-b423-11e7-8709-aa2e114b374c.jpg)
![jyrha_014](https://user-images.githubusercontent.com/20675668/31744098-1e001e58-b423-11e7-95e4-d2bcf80d2eed.jpg)

**Comment by wargrimnir** [comment]
Fixed in next.

**Comment by sioding** [comment]
Fixed with patch from 28.10.2017
