### ISSUE TITLE
Arkaneth Guard not targetable

### ISSUE THREAD

**Issue by Sebiascor** [WarEmu/WarBugs#10629]
It is at Dark Elf ch13 Recompense PQ. Akraneth Guards are not targetable.

Sebiascor.

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format. 

You can help us by following these bugreport rules: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Did the PQ on my own. Arkaneth Guards aren´t targetable but can be aggroed by aoe.

**Comment by Sebiascor** [comment]
Yes sir. I just wanted to point out they are not targetable. It is a minor
bug I am sorry to bother.

2017-10-19 17:18 GMT+03:00 Sio <notifications@github.com>:

**Comment by Lheana** [comment]
No problem, thanks for reporting. Fixed next patch.

**Comment by sioding** [comment]
Fixed with patch 21.10.2017
