### ISSUE TITLE
Quest - Reversal of Fortune

### ISSUE THREAD

**Issue by JeraSpites** [WarEmu/WarBugs#10624]
The quest is not completing.  I can find the bird fine and kill it and get the message, and talk to Uldhon Lashscar, the quest appears complete, but the seems to be no turn in.  I have checked all the camps on the dark elf side from Ellyrion to the the ship you 'start' at.  Nothing to indicate if this can be turned in or how.

My character name is Jyrha, and she is a Dark Elf Disciple of Khaine.

I had used the in game Help->Report a Bug to report this, however someone on advice told me I need to do it here.  There were other quests I reported too, but I forgot the names of them.  I can go through my streaming vod if you need me to.

Here are screenshots.

![jyrha_002](https://user-images.githubusercontent.com/20675668/31742808-7bbd07f4-b41e-11e7-8ede-a9317c938df4.jpg)
![jyrha_003](https://user-images.githubusercontent.com/20675668/31742813-7f0857ec-b41e-11e7-8e8f-165f7f51bd58.jpg)
![jyrha_004](https://user-images.githubusercontent.com/20675668/31742814-82a11358-b41e-11e7-8385-dc5418cc68dc.jpg)
![jyrha_005](https://user-images.githubusercontent.com/20675668/31742818-85d207f8-b41e-11e7-9764-110d3e67c5f4.jpg)
![jyrha_006](https://user-images.githubusercontent.com/20675668/31742823-88982742-b41e-11e7-947f-f0831c8fc10e.jpg)

**Comment by wargrimnir** [comment]
Assigned a turn-in point for this quest.

**Comment by sioding** [comment]
Fixed with patch from 28.10.2017
