### ISSUE TITLE
Missing Magic Critical Chance?

### ISSUE THREAD

**Issue by VonEpic** [WarEmu/WarBugs#10627]
![radmagnus_002](https://user-images.githubusercontent.com/31397093/31745761-2c446e2e-b432-11e7-8b05-4ccd6dec4b65.jpg)

I wasn't noticing the change until I started spec'ing for it, but then using CaVES it does not show my critical chance from the Mercenary set, nor in the character window.

**Comment by Torquemadra** [comment]
yeah... we dont provide support for addons

**Comment by VonEpic** [comment]
Allow me to reiterate, it does not show it in the character window either.

**Comment by VonEpic** [comment]
Got help in game. Figured it out. it's just not showing in any GUI, but it's showing in GetStat
