### ISSUE TITLE
PQ Flavor text

### ISSUE THREAD

**Issue by babum88** [WarEmu/WarBugs#10620]
Howdy!

A very minor nitpick, this. Back in the day, when WAR was originally out, I remember there being small snippets of flavor text whenever you completed a stage of a PQ and the next started. For Example; completing Stage 1 of Raven Host Vanguard would display something like "The Raven host falters beneath the renewed Order assault" in the Chat Window and then "Father Sigwald Arrives to lend his aid to the beleaguered peasants" when stage 2 started.

Are there any plans to add these back in? I know it's a very minor thing but I personally loved and they really aided the immersion.

Cheers. You're doing good work.

**Comment by szejoza** [comment]
https://github.com/WarEmu/WarBugs/issues/10567

It should unlock when step is completed (the x in a circle), see info from dev in that post^

**Comment by babum88** [comment]
Ah, no, I'm not talking about ToK unlocks, that seems to work fine on my end. I'm talking about some small snippets of text in the chat window that appears when you complete a stage, usually explaining the transition to the next stage, such as why explaining where champion mobs, for example, came from 

"Seeing their lesser brethren fall, the chosen of chaos step in to halt the order of the Griffon" I remember being one from an Empire PQ.
