### ISSUE TITLE
/Scenario Black Fire Basin tecture trap

### ISSUE THREAD

**Issue by Paurax** [WarEmu/WarBugs#10637]
When you walk in these places you are instantly killaed despite being settled, you probably need to put more tiles

[url=https://postimg.org/image/3n5pril3or/][img]https://s1.postimg.org/7duvcr9ywf/Wedra_041.jpg[/img][/url]

[url=https://postimg.org/image/2szmrq2f3v/][img]https://s1.postimg.org/20mr9zltdr/Wedra_037.jpg[/img][/url]

**Comment by wargrimnir** [comment]
Could not reproduce. Walking across these works just fine in every direction I tried. Provide video of "dying instantly" and we might investigate further.
