### ISSUE TITLE
[Engineer] Turret ability damage / Tooltips incorrect?

### ISSUE THREAD

**Issue by Jaycub** [WarEmu/WarBugs#1063]
Are the tool tips for turrets broken? Or are they dealing the wrong damage?

The tool tip damage for both abilities on gun turret are listing amounts significantly higher than their actual damage.

Machine gun is saying 120 damage twice per second for 3 seconds, but is dealing 43 twice per second. This is before mitigation. Against tanks with high enough toughness it deals about 5-6 damage.

Same thing for penetrating round, it's tool tip is reading a higher damage amount that it is actually doing.

Here is a picture of the testing I did in game w/ a combat log and the tooltips next to it: http://www.mediafire.com/view/0808s4b1hpcvig0/Kingcrimson_018.jpg

**Comment by ozarmidrashim** [comment]
Damage was wrong for Penetrating Round and Machine Gun. Dealt with.
