### ISSUE TITLE
Dwarf PQ Tree of Beards

### ISSUE THREAD

**Issue by donnk** [WarEmu/WarBugs#10631]
Stage 2 is bugged, kill x mobs. When you kill them they dont count.

thanks!

**Comment by szejoza** [comment]
did that PQ about one week ago, every step worked just fine so might be one-time bug

**Comment by sioding** [comment]
OK did that PQ on my own now. The PQ works fine. It´s just the counter that resets, but if you killed the 10 champs and you liberated the 10 dwarfs stage 3 will be available.

**Comment by Lheana** [comment]
So it means it is a general bug that affects all PQs that have several objectives within the same stages. The objectives are noted on only 1 line instead of 2 for this PQ. Thus it switches between the 2 objective numbers.
This issue can not be fixed yet, so I close the ticket.
