### ISSUE TITLE
Zone flip defenders win

### ISSUE THREAD

**Issue by acidicrain** [WarEmu/WarBugs#10630]
In Talabacland the defenders won after losing their keep.
They were able to flip the zone by owning the BO's and ruin but had no keep of own. 
The draw timer should have been on 3hours so don't think this was invoked.
The bug appeared to be that for defenders the ruin plays as their keep and ruin allowing them to flip zone.

**Comment by Hargrim** [comment]
Do you know what was Realm Rank of Order when they locked? If it was 5 and they had 4 BOs lock is currently possible and 'as designed'.

**Comment by acidicrain** [comment]
Hi
They were at rank 2 before we took the keep, not sure of exact number at time as we had just taken the keep and we're in process of getting first bo back. Yes every went to bo's and none stayed at ruin.
But just for my understanding , once a keep is taken it does not really matter at all who has a keep it's just the bo's and ruin that matter ?
