### ISSUE TITLE
[Quest/ORVR] 'Raise the Chaos Banner for Glory'  not working.

### ISSUE THREAD

**Issue by GilbertBeilschmid** [WarEmu/WarBugs#10644]
The quest objectives are to kill 35 players in RVR and then take over Feiten's Lock in High pass. If players try to take over the Lock in order to progress with the quest it does not check it off in the quest log nor will it allow you to turn it in. 
![linhir_017](https://user-images.githubusercontent.com/32606500/31847824-9bdc76d6-b5d7-11e7-8bee-234b0a736911.jpg)

**Comment by sunborn23** [comment]
Can confirm. Tested by capturing while BO was controlled by nobody and also while controlled by Order. Also did some fighting at the point prior to capturing, nothing worked.

**Comment by Lheana** [comment]
Fixed next patch.
Destruction players will now have to click on the GameObject 'Chaos Banner' next to the Battlefield Objective Feiten's Lock.
Order players will now have to click on the GameObject 'Empire Banner' at the top of the Battlefield Objective Verentane's Tower.

**Comment by sioding** [comment]
Fixed with patch from 10.11.2017
