### ISSUE TITLE
[Public Quest] Caledor/The Fortress of Caledor

### ISSUE THREAD

**Issue by Jubok22** [WarEmu/WarBugs#10642]
PQ The Fortress of Caledor   Rank 32    Sometimes you can loot the Mobs all time... all time 50c so you can get for 1 Mob 8g or more... Door Bugged often too and you can do Spells on Cooltime sometimes... a lot Buggy PQ

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format. 

You can help us by following these bugreport rules: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Hm did the PQ on my own right now and i did´t see that.

**Comment by Jubok22** [comment]
It was today @ about 13 o Clock      @ PQ The Fortress of Caledor Rank 32      If you Kill some mobs. Not all they die and you can Loot then all time and they not despawn.  If you make the PQ the Door to Entrace bugged or you Stucked in there and cant open.

**Comment by Jubok22** [comment]
and you get no Cooldowns on Skills... its at this PQ

**Comment by sioding** [comment]
I am still there - killing mobs and don´t see the issue.

**Comment by Jubok22** [comment]
Hmm we do the Heros etc and lost all AP etc and can spam normaly Spells with CD

**Comment by sioding** [comment]
So it would be great to get some ppropriate evidence, be it in screenshot or video format.

**Comment by Jubok22** [comment]
dont make some sorry... can only tell you that its Buggy

**Comment by wargrimnir** [comment]
Tested this today, couldn't find anything weird like you were describing.

**Comment by Lheana** [comment]
Worked on this PQ, did not notice weird things like that.
