### ISSUE TITLE
Quest - Mob Mentality

### ISSUE THREAD

**Issue by Niobandi** [WarEmu/WarBugs#10647]
In the order quest " Mob Mentality " in the Badlands, the stage where you have to kill Muk'Rosh, and the stage where you have to Speack to Gora Lightmare haven't map tracker.

**Comment by thorbolt80** [comment]
No red circle on the map
![thorbolt_095](https://user-images.githubusercontent.com/16274785/35192042-a386ca6c-fe89-11e7-9213-b1467f8891b1.jpg)

**Comment by thorbolt80** [comment]
Muk'Rosh is at : 4.38 west of chapter 10 dwarf
![thorbolt_096](https://user-images.githubusercontent.com/16274785/35192140-1d175f7a-fe8c-11e7-9a60-463ed407c90b.jpg)

**Comment by thorbolt80** [comment]
You can add red circle around Gora lightmane loc : 12.25 badlands
![thorbolt_097](https://user-images.githubusercontent.com/16274785/35192358-fc7256e4-fe90-11e7-944f-b7afb806522a.jpg)

**Comment by sioding** [comment]
fixed with patch from 16/02/2018
