### ISSUE TITLE
pq not always active in Norsca

### ISSUE THREAD

**Issue by Spaduzio** [WarEmu/WarBugs#1064]
Hi and sorry if that was mentioned before.
Very often when i try to play a pq in Norsca it doesn't seem to work.
I do not get influence from kills or interactions with items and i do not get count for the stage progress.
It's like it is in reset, but it isn't.
This has happened in all the pq in Norsca.

Thanks

**Comment by Evildoor** [comment]
Most PQs are not working. Closing, since this is a well known issue.
