### ISSUE TITLE
Not generating micro ticks from BOs in t2 Elyrion and Shadowlands

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#10645]
Hi all, 

In short with this change: "players flagged as afk will no longer receive mirco ticks" has resulted in no micro ticks at all being generated from BOs in the zone mentioned in the subject when we were taking BOs and waited a while with our grp of 6 after capping the BO to test.

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format. 

Please remember this from the Patchnotes:

> - Removed Renown microticks on BOs when Realm Rank is equal to 3 or more.

You can help us by following these bugreport rules: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
