### ISSUE TITLE
untargetable healer in city

### ISSUE THREAD

**Issue by velkos4ever** [WarEmu/WarBugs#10641]
![nighteyes_403](https://user-images.githubusercontent.com/16551075/31795796-d985a262-b52f-11e7-8818-7317a429c4cd.jpg)
![nighteyes_404](https://user-images.githubusercontent.com/16551075/31795797-d9aad672-b52f-11e7-8b28-ed1ff905d2fc.jpg)

**Comment by Lheana** [comment]
Has it been fixed with last reboot?

**Comment by sioding** [comment]
checked it on my own - is fixed.

**Comment by Lheana** [comment]
Has been fixed by the boot.
