### ISSUE TITLE
Instructor`s Boon 

### ISSUE THREAD

**Issue by Symbelmyne** [WarEmu/WarBugs#10649]
Instructor`s Boon (vendor scroll to reduce exp by 75%) is not working for scenario rewards upon victory. Works on mobs tho.
Dont think need any SS cause easy to replicate.

**Comment by sioding** [comment]
![image](https://user-images.githubusercontent.com/18517842/31854021-e98b2056-b692-11e7-8de1-422a1b2d2fa1.png)

**Comment by Symbelmyne** [comment]
I`s been fixed, at least today it reduces sc reward EXP.
