### ISSUE TITLE
The new calculations for parry killed WL Flashing Claws Tactic

### ISSUE THREAD

**Issue by BrockRiefenstahl** [WarEmu/WarBugs#10648]
Also .Getstats seem to bring faulty statnumbers.

Anyway: I have 38,8% Parry according to char screen and my addon. When I slot this tactic I get only 1% parry according to statscreen + addon. However getstats does not show any  difference whatsoever!

Getstats Parry without Tactic: Parry 23 [(18 + 5) x 1]
Getstats with Tactic: Parry 23 [(18 + 5) x 1]
Getstats with Tactic + Pet active directly beside me: Parry 23 [(18 + 5) x 1]

Please fix, I want the 10% Parry back, especially vs all those Destru Meleetrains

**Comment by Riefenstahl** [comment]
I want to add, that there is an Issue with the .getstats command.
I don't know what it causes, but many time it does not work anymore without one or two zonechanges.

Mostly it works 1 time (sometimes even not on the first try), but when I want to fiddle with gear and stats, it wont work a second time untill I teleport away or fly or relog. I have also tried /rel but that also is not reproduceable. Theerror seems totally inconsistent. 

I am not an expert and dont know if this is serversided or maybe some of my addons (Pure/Enemy/MSCT/Buffhead/Minimapaddon)

**Comment by sioding** [comment]
Thanks for the report. I have a dev looking into your parry issue. But please remember only one bug per report so the .getstats add won´t be handled here.

**Comment by sioding** [comment]
This issue was checked. The tactic whorks fine serverside. Just the paperdoll/.getstats doesn´t show the correct numbers.
