### ISSUE TITLE
renown lvl

### ISSUE THREAD

**Issue by Wagrash** [WarEmu/WarBugs#10656]
![zirak_000](https://user-images.githubusercontent.com/16164209/31860986-78061928-b72c-11e7-8201-75080fec6d4c.jpg)
29 renown lvl and only 26 points avaliable after respec

**Comment by Lheana** [comment]
Have you tried to use 29 points?

**Comment by Wagrash** [comment]
Yep, few times. I tryed to take deft defender (4 lvls -> 20 points), reflexes (2 lvls -> 4 points) and for last 5 points I tryed to take opportunist (1 lvl -> last five points) but I cant train it

**Comment by Wagrash** [comment]
ah I understand whats up. thats because I must lvl up normal lvls - I find my old issue with same "problem"

**Comment by Wagrash** [comment]
sorry for wasting your time
