### ISSUE TITLE
Bright Warrior + Witch Hunter

### ISSUE THREAD

**Issue by sirgregor** [WarEmu/WarBugs#10650]
There is no ability to "strangle" inflicting physical damage and inflicting silence on the enemy for 3 seconds.
Also, if you select tactics for specialization tactics in the 2nd branch (burning), tactics are not added to the abilities window (hotkey "B")
Also, potions are not used to absorb damage dealt.
Also on the character "Witch Hunter" incorrectly credited points of skill. (for example, from level 11 to 22, only 6 points were credited)

**Comment by wargrimnir** [comment]
One issue per ticket. 
Also SEARCH the bugtracker BEFORE you post a new issue. 
Also provide proper evidence for your issues to prove things, at very least, do not match live. 
Also be aware that SOME things have changed, intentionally.
Also, you can ask in advice for many issues, players are relatively helpful and aware of such changes.

**Comment by sioding** [comment]
No evidence - no answer - close for now,
