### ISSUE TITLE
Bright Wizard dmg abuse.

### ISSUE THREAD

**Issue by flannelok** [WarEmu/WarBugs#10658]
Hello i dont know this is some how bug abuse or not. So i got Insta die from BW. He was casting 4spels with the same gkd. How? i realy dont know, but all i know its realy imposible to do in 1sec.
![dpsdrait](https://user-images.githubusercontent.com/33010012/31866829-0d1bafe4-b78e-11e7-9066-89f702053556.jpg)
This is the pic provide casts. So as you see i got Ignite+**Sear+Pyroclastic Surge+Fireball Barrage**
All this dmg is done in 1sec, so its mean he cast all this 4casts in 1sec or at least 3 cast.
https://youtu.be/mPZy7pfxngo
So i log to my BW and try to do this 3cast sequenc. As you se its took at least 3sec to cast.
This man is proud bug abuse or cheater.

**Comment by Jbillz** [comment]
This is not hacking but the standard BW/SC rotation utilizing spells that have a delayed response to spike damage on a single timestamp. This particular damage spike is also buffed by "Flames of Ruin", "Funnel Power", and warrior priest buff "Prayer of Righteousness". The tactic "Fuel to the Fire" must be slotted to accomplish this rotation. Ignite>Boiling Blood>Pyro Surge>Sear>Fireball Barrage. Welcome to the server. -Jbz

**Comment by Lefze** [comment]
Actually, sear, pyroclastic and fireball barrage hitting in the exact same timestamp looks pretty impossible on paper, unless there's some projectilespeed in play here, which I don't know for sure as I play sorc and not bw.

**Comment by wargrimnir** [comment]
The bugtracker should not be your default to figuring out how combat works.
