### ISSUE TITLE
Double Xp/BO Ticks

### ISSUE THREAD

**Issue by 27a779** [WarEmu/WarBugs#10652]
If you rank up inside a lake/zone where you are bolstered you lose the bolster. After that you will get double xp for BO ticks and also be able to get double experience off mobs that are within that zone as you are no longer bolstered.

**Comment by Hargrim** [comment]
Fixed, will update this ticket when live is patched.

**Comment by 27a779** [comment]
Awesome thanks.


Sent from Yahoo Mail for iPhone


On Sunday, October 22, 2017, 8:05 AM, Hargrim <notifications@github.com> wrote:


Fixed, will update this ticket when live is patched.

**Comment by sioding** [comment]
fixed with hotfix from 21.10.2017
