### ISSUE TITLE
Saphery PQ [The Ithilmat Tower] Wrong Level Mob.

### ISSUE THREAD

**Issue by owensac1** [WarEmu/WarBugs#10651]
In the PQ there is a level 37 who is suppose to be 27 from the looks of the other mob at this PQ. 
![3](https://user-images.githubusercontent.com/30947245/31855454-a9fd3f6e-b679-11e7-8f9e-ef3ee65ec529.PNG)

![2](https://user-images.githubusercontent.com/30947245/31855461-afd14688-b679-11e7-8b47-6e4e1859c28c.PNG)

![1](https://user-images.githubusercontent.com/30947245/31855460-ade9a766-b679-11e7-9eb6-86c4c487c47f.PNG)

**Comment by sioding** [comment]
Fixed with patch from 28.10.2017
