### ISSUE TITLE
Mara ability tree 5-point tactic

### ISSUE THREAD

**Issue by Gnashspike** [WarEmu/WarBugs#1065]
After purchasing (with a point) the Scything Talons tactic and slotting it I received no bonus to WS nor Ini. Out of curiosity I in turn purchased the 5-point tactics from the other two trees. After slotting each one respectively there was still zero change in any stats, including those listed on the repective 5-point tactics. None of these raised/changed my stats in paper doll window, Stat Doll add on, nor the combat log. Brute Force tactic, however, DOES change my strength by appropriate amount.

Cheers!

**Comment by ozarmidrashim** [comment]
You realise that those tactics work in concert with the Mutation buffs from the respective trees, right?

**Comment by Gnashspike** [comment]
I could swear I applied the 'gifts' while tactics were slotted. I'll go do that right now to make sure, then come back and confirm or close the request.

Thanks Ozar!

**Comment by Gnashspike** [comment]
The tactics DO work. I forgot to mutate. Silly me. =/

Closing this request. Thanks again.
