### ISSUE TITLE
floating corpse in Altdorf and non targetable 25.37 & 24.37

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#10655]
There are 3 floating corpse and non targetable. 2 of them 25.37 the other one on the other side of the street 24.37

**Comment by sioding** [comment]
Thanks for the report. Checked that on my own and do not found something like you said. Please provide some screenshots.

**Comment by Lheana** [comment]
Are they for a quest? Or something like that?

**Comment by thorbolt80** [comment]
After reconnecting look like a visual bug they are not floating anymore. Not for a quest. They are just non targetable.  Should I report cats, rats and so on non targetable in Altdorf?

**Comment by Lheana** [comment]
GameObjects floating above the ground are unconsistent bug: Sometimes they are floating, sometimes not.
No, no need to report them except if they are for a quest.
