### ISSUE TITLE
Wrong Location

### ISSUE THREAD

**Issue by Ladylissa** [WarEmu/WarBugs#10663]
After I was finished with an scenario, I ended up at the very beginning. Not sure if I was supposed to report this or not. I also have a screen shot of where I landed.
![smoke_004](https://user-images.githubusercontent.com/33042601/31916190-73e54172-b81f-11e7-8255-0bc0f5a3d232.jpg)

**Comment by sioding** [comment]
Thanks for the report. As far as you don´t say: This happens ever when i am doing "THIS" we aren´t able to reproduce it. So may i ask to which rally master have you ben bound and does that always happen when you leave the scenario / is it always the same scenario?

**Comment by Ladylissa** [comment]
This only happened after the Reikland factory scenario. It only happened once so far. The Rally Master I am bound to is Dragonwake. I haven't been back in the Reikland Scenario so I am not sure if it happens more than once. I reported it as soon as it happened.

**Comment by sioding** [comment]
Thanks fpr your reply.

**Comment by MaxHayman** [comment]
We have made a lot of changes which should have fixed this issue. Please reopen this if not.
