### ISSUE TITLE
Order Keep Lords Giving quests to Destro. 

### ISSUE THREAD

**Issue by Lokenoth** [WarEmu/WarBugs#10667]
Right clicking the enemy keep lord whilst battling can open the dialogue box offering the player quests. These quests appear to be unable to be completed as "Enemy" players as defined by the quest requirements appears to only mean that sides "Enemy" 
![a5415e2c-98fb-4cb6-9290-506b1b54476f](https://user-images.githubusercontent.com/17035321/31920247-901ac5fc-b85f-11e7-97d6-0052291695b9.png)

**Comment by Lokenoth** [comment]
I can duplicate this upon request, and so far has worked on every Lord I've faced since discovering it.

**Comment by sioding** [comment]
Sorry but i can not reproduce that anymore.
