### ISSUE TITLE
Weird Bug with not turning into a chicken.  16 in t1 rvr

### ISSUE THREAD

**Issue by owensac1** [WarEmu/WarBugs#10668]
i leveled to 16 but was not turned into a chicken even managed to get into a SC, i'm not sure if this bug was related to me had already been qued for an SC while i lvled or not in the rvr zone.

![curtimous_013](https://user-images.githubusercontent.com/30947245/31937038-50cb28d4-b881-11e7-854d-92ddedaaf996.jpg)
![curtimous_014](https://user-images.githubusercontent.com/30947245/31937039-50dec344-b881-11e7-95d1-b6acd16474e2.jpg)
![curtimous_016](https://user-images.githubusercontent.com/30947245/31937040-50f0dc28-b881-11e7-9922-160339172d7e.jpg)

**Comment by MaxHayman** [comment]
Should be fixed.
