### ISSUE TITLE
All Quests are Gone / No RvR Lootdice UI/rewards

### ISSUE THREAD

**Issue by Ghostcrowler** [WarEmu/WarBugs#10661]
Hello,

since friday last week something rly rly strange happens to me... i lost all my quests on friday night... i noticed that when i was on the way to kill Skarlok for the Beastlord hunt quest (got disconnect because of bad internet before)... so i went to get the quest again (before killing skarlok). today i log in again and see that the quest is still there but the skarlok kill is gone (and all other quests are still gone too) second strange think... since friday i done like 4-5 T4 RvR plays. but i never see any rolls coming . i see the little box left from the minimap and after winning the RvR the box disappear but no Rolltable UI shown up!

Admin told me that a server restart is needed for fix the issue with the quests but your homepage tells us that the server is live since today (Up since: 2017-10-23 10:07:41). So that can't be the fix for the problem!

please help im realy demotivated now...

BR

Maik

**Comment by sioding** [comment]
Until we have an open issue i will reference this one to the original one and close this.
