### ISSUE TITLE
Icons created in the RoR Macro Window

### ISSUE THREAD

**Issue by Gnashspike** [WarEmu/WarBugs#1066]
Do not remain in any slot of any hotbar, with or without the use of Nerfed Buttons, after a zone-in of any kind, whether SC, flight, zone zero, /stuck. Incidentally death does not effect this (unlike it effects my 'mara bar' resetting a couple key abilities at THE WORST possible timing... yet that's another request). Having to replace them is only tedious/next to impossible if one zones to an SC with less than 30 seconds til start There are some great add on macro icons that fulfill a purpose in my playstyle since live. Out of three hotbars, my third bar was half macro icons created in W.A.R.'s <ESC> menu.

It would be much appreciated if RoR has the resources, to implement a dependable work around, or fix
for this little irritation. =)

Cheers!

**Comment by ozarmidrashim** [comment]
Fixed in latest
