### ISSUE TITLE
Still in combat after leaving scenario prevents joining a new one

### ISSUE THREAD

**Issue by medktulu** [WarEmu/WarBugs#10662]
The first time I log in I can join a scenario as normal then when it finishes and I queue again when I get the popup to join I can't always join as it says I'm in combat. This doesn't always happen, I can do 2-3 SC's before this happens. I can be in a warcamp or IC, I've tried getting myself into combat and leaving but it has no effect. The only way to "re-set" it is to close down RoR and fire it up again. Inevitably this does cause me to end up with a quitter debuff.

Not sure if anybody else gets it or just me.

**Comment by Titoos** [comment]
It is well known combat bug. To apply workaround just type:
/s .unlock 
or just
/s .u

**Comment by sioding** [comment]
Thanks @Titoos .
