### ISSUE TITLE
[Quest] t4 dwarf ch19 "A Prod in the Right Direction"

### ISSUE THREAD

**Issue by Csernobog** [WarEmu/WarBugs#10670]
Missing quest mobs in the red area (Trained Sludge Troll)

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format. 

You can help us by following these bugreport rules: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
fixed with patch from 09.06.2018
