### ISSUE TITLE
Slayer - Rampage

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#10674]
Rampage skill (from Trollslayer mastery tree) when used as furious (red) gives only 10s buff as opposed to 20s given in the skill description (look at timestamps in the combat log on screenshots as an evidence, checked it several times, always with the same result, rage isn't dropping on screenshots cause I'm using Power Through tactic)
![sheykis_029](https://user-images.githubusercontent.com/18032193/31982302-7681fa30-b958-11e7-83f4-bb96e304d676.jpg)
![sheykis_031](https://user-images.githubusercontent.com/18032193/31982303-769c114a-b958-11e7-97e3-7af8f2d707ce.jpg)
![untitled](https://user-images.githubusercontent.com/18032193/31982333-ac48e75a-b958-11e7-8c93-0e8ecdf2d09d.png)

**Comment by Torquemadra** [comment]
furious is middle (orange) berserk is end (red), slayer mechanic is best results using mechanic abilities from the middle, if you power through you miss the sweet spot.
