### ISSUE TITLE
[engineer] Coordinated fire 

### ISSUE THREAD

**Issue by Asherdoom** [WarEmu/WarBugs#10676]
Not staking additional 15% damage on nothing. i tested on my morale 3 (2400 basic damage and after this tactic slotted still 2400) and also tested on other engi skills in duel with my guildmate friends.

**Comment by sioding** [comment]
Thank you for the report. Would you please add the screenshots you´ve made to help us looking into this issue?

**Comment by Asherdoom** [comment]
as you can see in both screens i made an example with and without Coordinated Fire tactic. as you can see morale 3 damage is the very same. 2400

https://imgur.com/a/9I6uQ

**Comment by Torquemadra** [comment]
morale damage isnt modifiable under any situation
