### ISSUE TITLE
Cannon De-spawn

### ISSUE THREAD

**Issue by Lokenoth** [WarEmu/WarBugs#10672]
![lokrin_003](https://user-images.githubusercontent.com/17035321/31961511-d9d0a94e-b8f2-11e7-9cbf-41ecce817bf9.jpg)

Dismounted to deploy my Chaos Hellcannon on the steps shown here within Pass watch castles walls. The cannon disappeared but I was still receiving updates about it being resupplied suggesting the game object wasn't deleted but moved elsewhere!

**Comment by Lokenoth** [comment]
![lokrin_005](https://user-images.githubusercontent.com/17035321/31961650-4076db78-b8f3-11e7-83df-64a250fa67c9.jpg)

Proof it is still ticking over

**Comment by Lokenoth** [comment]
![image](https://user-images.githubusercontent.com/17035321/31961705-6fb3b9e2-b8f3-11e7-9cb3-f73cfca6bc61.png)
Found it, it died due to some unknown reason but yurns out it spawned beneath the steps?

**Comment by sioding** [comment]
Thats not a good psoition for a siege weapon. Please use only the ground or the walls which are safe but not the houses.
