### ISSUE TITLE
ORvR no loot roll

### ISSUE THREAD

**Issue by shattera** [WarEmu/WarBugs#10675]
I played the ORvR in Praag (closed ~16:32 25.10.17 with a 5* win) with the character "shatbreaker" and got no roll pop up, even i participated from 1*->5* without afking at a BO.
During the entire time i was in a group with a friend and he get a roll and a bag.
I disconnected for a very short time in the middle of the match.

**Comment by sioding** [comment]
#10673

**Comment by shattera** [comment]
in the linked bug report the player saw a loot roll, i got no pop up
