### ISSUE TITLE
Mara Change of appearance when stance change

### ISSUE THREAD

**Issue by samdammers** [WarEmu/WarBugs#10678]
Hi team,

I am a new user, downloaded the client 25/10/2017
Have encountered this issue (was previously closed a few years back)
https://github.com/WarEmu/WarBugs/issues/559

I went into a scenario with a mutation active, upon coming out, changing mutation now changes appearance.

**Comment by Lokenoth** [comment]
This happens whilst under the effect of spooky.

**Comment by samdammers** [comment]
Ah all good
