### ISSUE TITLE
ORvR/New solo roll bag system

### ISSUE THREAD

**Issue by slaughterk1n** [WarEmu/WarBugs#10673]
On order character Snoorii on Tuesday(today) at around 5 pm eastern on a failed defense of praag I saw a roll on screen and it showed a blue bag I won.  I was subsequently dropped from the game by the server.  I never received my blue bag in the mail.  I wish I had taken a picture I but there was no way for me to know it would happen

**Comment by SecretsOTheP** [comment]
If you are offline at the same time a bag roll happens it will not distribute the loot. We'll look into the disconnect issue but this is working as intended for the most part.

**Comment by slaughterk1n** [comment]
that's not what happened.  The roll already occurred.  that's how I know what I got.  then the server disconnected me along with several others in my wb who all complained about getting disconnected.  it also happened to my son whom I play with, and my connection did not get severed locally because our teamspeak connection didn't drop.  I was disconnected by your server AFTER the roll. 
 I WASNT offline at the same time as the bag roll.

**Comment by SecretsOTheP** [comment]
The mails are sent *if you are online when the 180s timer expires* after winning a roll.

**Comment by Titoos** [comment]
I can confirm there is an issue. It's happened to me three times already, since the patch went live. 
I definitetly got the contribution. I wasnt offline. I wasnt disconnected between lock and roll timer expiration. I wasnt porting to another zone either.

**Comment by sioding** [comment]
Just a friendly reminder: We need as much information as you can give. That means also when,where,what...  In this case the "when" is really important.

**Comment by Lokenoth** [comment]
Reporting this one for a friend if thats fine.

He participated in the entirety of the Reikland keep assault, disconnected whilst the keep lord was on 5% When he logged back in the lord was dead, And he was unable to successfully accrue enough contribution from that point onward to qualify for a bag.

He was there for a tick of the keep lord capture that was about 52 renown for him 5000 for everyone who hadn't disconnected (In our party) He moved on to secure  Schwenderhalle Manor BO and the zone locked. He was not given the chance to roll thanks to that disconnect, and any contribution he had earned prior to the disconnect had evidently been reset. 

I can't recall just what time we were knocking down Reikland I believe it was about 1:AM GMT

**Comment by Titoos** [comment]
> I can confirm there is an issue. It's happened to me three times already, since the patch went live.

Strange things happened to me today. I was participating in Reikland siege yesterday, but I logged out before lock. Today, when I logged in, I got white bag (I suppose it was reward for yesterday's siege), and three other bags, including lost blue bag from the past :) Looks like the lost-rewards-mails were stuck in some queue, and now they were sent. Maybe it's something you should investigate.

**Comment by SecretsOTheP** [comment]
We're still looking into this however information from the original ticket creator about if they got their bag after a restart or not would be helpful.

**Comment by slaughterk1n** [comment]
I did receive a blue bag in the mail.  It was after a server reset.  If I knew the system did that I wouldn't have opened the ticket.  You can consider my particular case closed.
