### ISSUE TITLE
frustrated about runtime error

### ISSUE THREAD

**Issue by Ghostcrowler** [WarEmu/WarBugs#10679]
Good Morning or afternoon,

i cant finish my beastlord quest because everytime i try to kill Snizzort in Death Peak - Bristle Cavern i got a runtime error!

![error](https://user-images.githubusercontent.com/33037972/32050603-b421c8da-ba51-11e7-8cca-2d9fd8bf3ddb.jpg)

i tried everything... game without addons, game on lowest graphics, reinstall Visual Runtime Library, reinstall Warhammer ... everything!

This Error only happens on this Boss... Please help i want to finish my beastlord quests....

**Comment by sioding** [comment]
Hey Maik,

did you tried the boss with the lowest video setings? I see a lot of ohhh shiny!
We can not debug the client situation on your side and as you can see you are the only
one with that problem. I would suggest to deactivte ALL addons while doing the
boss and try the fastes framerate.

**Comment by Ghostcrowler** [comment]
exactly this was what i am doing... addons off and "fastes framerate" and even when im healing with my back to the boss the error pops! and in RvR or some other situtation i never got this error so it must be the boss causing that!

**Comment by Jokerloz** [comment]
I've had the same issue for years honestly why i stopped playing. its happened twice tried to get a SS but it closed on me. this happens anywhere. have all my settings to low and effects to self.

**Comment by Jokerloz** [comment]
![untitled](https://user-images.githubusercontent.com/10342124/52595368-bc520f80-2e1b-11e9-8538-df43430cc74c.jpg)

**Comment by sioding** [comment]
Have you ever tried the same with the 64 Bit .exe? You can choose it from the launcher settings. Would be nice to see if things run better with it.

**Comment by Kaelang** [comment]
I'm going to go ahead and close this as no further information was provided. If you still experience this issue, feel free to open a thread in the Technical Support section of this forum. As implied in previous comments, this is more of an issue with your client, rather than an in-game feature.
