### ISSUE TITLE
Quest - Bloodspike

### ISSUE THREAD

**Issue by Niobandi** [WarEmu/WarBugs#10687]
The Order quest " Bloodspike " where you have to get " Bloodspike Shadow's Head " in the Badlands haven't map tracker and the Bloodspike Shadow is spawn on " 4900 - 22600 " but doesn't give his head.

**Comment by ErikWPotter** [comment]
I concur. I'm having the same problem.

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
fixed with patch from 09.06.2018
