### ISSUE TITLE
Tier 2 Shadow Spire

### ISSUE THREAD

**Issue by Vl4ddy** [WarEmu/WarBugs#10681]
So it seems Destro is able to hit Shadow Spire from their warcamp with siege. I am not sure whether this was one that was planted, or it is one of the permanent siege weapons. This doesn't seem fair because they are able to use siege weapons to defend an objective while we can't ever touch the destro. 
![sloppynachos_011](https://user-images.githubusercontent.com/33129563/32062797-c87a84bc-ba32-11e7-8b03-6f44be0cd00b.jpg)
![sloppynachos_017](https://user-images.githubusercontent.com/33129563/32062799-c88aedde-ba32-11e7-9888-c6c8e091d4fb.jpg)
![sloppynachos_019](https://user-images.githubusercontent.com/33129563/32062800-c89a333e-ba32-11e7-8718-f60759e52206.jpg)

**Comment by wargrimnir** [comment]
Fixed next patch.

**Comment by sioding** [comment]
Fixed with patch from 28.10.2017
