### ISSUE TITLE
Shadow Warrior Stances Bug when changing zone

### ISSUE THREAD

**Issue by Green-Wolf** [WarEmu/WarBugs#1068]
Theres a problem with the shadow warriors stance bars when you go into scenarios.

When you change zone the abilties will get all muddled in one or two of the stances and you have to redo all your bars each time you go into a SC. The other bars are alright, its just the first one that changes based on stance.

**Comment by Gnashspike** [comment]
Same happening with Marauder and my squig herder. I'd venture White Lions, too. Hoping for fix to this and macro icons soon!

Cheers!

**Comment by Green-Wolf** [comment]
I think this has been fixed with the recent hotbar changes, Thanks!
