### ISSUE TITLE
Halloween event

### ISSUE THREAD

**Issue by Dottina** [WarEmu/WarBugs#10685]
Keeper of Death is not Work in  IC

Become I a Bug token? :D Destruction my char name Dottina :P

**Comment by GilbertBeilschmid** [comment]
I seem to be having the same issue though I am not sure if everyone on the server is. I can click on and use all of the other Halloween token trade ins just not the Keeper of Death.

**Comment by Torquemadra** [comment]
contact a GM ingame with .gm or on forums to fix that
