### ISSUE TITLE
The blighted farm TC hard PQ

### ISSUE THREAD

**Issue by blechkautz** [WarEmu/WarBugs#10694]
The quest stage 2 is broken. There is no goal nor timer displayed and we killed all 3 demagoges and the altars (don't if thats the goal for this stage) but didn't manage to reach stage 3.

**Comment by Lheana** [comment]
I tried and it worked for me.

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format. 

You can help us by following these bugreport rules: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by blechkautz** [comment]
Not able to reproduce it. Sorry for wasting your time. 
But i noticed that at stage one there is one bligthend believer (mobs from stage 2 but not needed to kill), which despawns after stage one.  Also the mobs who spawn after you destroy one altar won't despawn after that stage(stage 2). 
![bug](https://user-images.githubusercontent.com/30760089/32189520-3e1877bc-bdab-11e7-8415-18a18cd52760.png)

**Comment by Lheana** [comment]
The Blighted Believer in stage 1 will no longer spawn. Destroying the Black Altars will no longer make spawn NPCs.

**Comment by sioding** [comment]
Fixed with patch from 29.12.2017
