### ISSUE TITLE
aa haste not being calculated properly?

### ISSUE THREAD

**Issue by felkia** [WarEmu/WarBugs#10691]
with oaths tones equipped aa speed.15 if i equip a second piece of aa haste gear with 10% aa speed changes to 15.2 so wondering if there is bug?

**Comment by felkia** [comment]
![wetworks_002](https://user-images.githubusercontent.com/33167801/32129840-86305b80-bb41-11e7-8765-d7da1b7b85a6.jpg)
![wetworks_003](https://user-images.githubusercontent.com/33167801/32129842-88cf4b44-bb41-11e7-9282-39ee86fd26a6.jpg)

**Comment by cimator** [comment]
Character window is usually buggy. I see the .getstats shows %25 aa speed as it should be the way it stacks, looks like it is working fine.

**Comment by sioding** [comment]
Cimator already answered. Thanks @cimator
