### ISSUE TITLE
Precursor Greencloak wrong career stats

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#10697]
This item contains 30 intelligence and can be equipped by healers, including Disciple of Khaine, who can't use intelligence stat in any possible way at all.

**Comment by wargrimnir** [comment]
Details on accessory item unification are from a patch in February. DoK has access to Shaman cloaks, Shamans occasionally get Int. Don't use it if it's not something that works for you. Not a bug.
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=19970
