### ISSUE TITLE
zone lock rp issue

### ISSUE THREAD

**Issue by Keldorin** [WarEmu/WarBugs#10690]
Since the halloween event went live the ticks from the zone locks went down ridiculously low. For 5 hour praag fight with aao in the beggining on destro side I got about 300 rp for the lock, many players reported same amounts of low rp gain. For lord kill it was even less, about 70 rp (considering we tried siege 3 times and many wipes went down, heavy fighting all in all). Is this intended or somethings wrong ?

**Comment by SecretsOTheP** [comment]
We put in a fix today that should address the issue.

**Comment by Keldorin** [comment]
Great, I'll check and report back.

**Comment by Keldorin** [comment]
Yes it's fixed now thanks alot.
