### ISSUE TITLE
Constant pq bags without participation

### ISSUE THREAD

**Issue by Telcular** [WarEmu/WarBugs#10692]
I´ve been recieving constant reward bags from the pq "Ruinous Power" , the very first pq for chaos.
As of making this report, i havent been there for about an hour, maybe more, yet im still getting participation rewards from it with a 0001 roll every time, as of now, i´ve gotten 5 bags in the mail from it.
![war ror bug](https://user-images.githubusercontent.com/33172164/32131996-912cc4e0-bbbb-11e7-8e8f-70a57b08091c.PNG)
My ingame name is Aerenlis.

**Comment by Telcular** [comment]
As of making the report, i got another bag, this time from "Destruction of the weak" , the 2nd pq.
And another bag from ruinous power.
![war ror bug 2](https://user-images.githubusercontent.com/33172164/32132029-0cf4020a-bbbc-11e7-9b0f-f49d72b36f1b.PNG)

**Comment by SecretsOTheP** [comment]
Fixed as of the emergency hotfix - 28/10/2017
