### ISSUE TITLE
BO's flags are bugged into each other making them purple

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#10698]
While being recaptured destruction's red flag and order's blue flags merge into each other, making it purple. 
![nonameness_019](https://user-images.githubusercontent.com/18102127/32133687-731c1784-bbee-11e7-9282-41ea49686f4f.jpg)
![nonameness_020](https://user-images.githubusercontent.com/18102127/32133688-7336ae3c-bbee-11e7-9475-99e8ad4adf63.jpg)
![nonameness_021](https://user-images.githubusercontent.com/18102127/32133689-734ff8b0-bbee-11e7-912a-ef2bca49f4e9.jpg)
![nonameness_022](https://user-images.githubusercontent.com/18102127/32133690-7369ec98-bbee-11e7-8a69-930c0e0128b1.jpg)

**Comment by sioding** [comment]
Fixed with patch from 13.1.2018
