### ISSUE TITLE
flames of ruin CD

### ISSUE THREAD

**Issue by pantofolo** [WarEmu/WarBugs#10702]
Flames of Ruin has a 45 sec cooldown instead of being spammable

https://mega.nz/#!sWwDnDSZ!Yj_JU-1J4oSp000wsBB1NStoSmOKrGjAV8Ec-36fiLg

https://mega.nz/#!IfhESboR!Y3d7ss8SgrPwWTtNJxjCzlevVV2aP1vUbVVvfL2UglA

**Comment by wargrimnir** [comment]
Intended. Long duration buffs have a long cooldown, this allows shatter/sever counterplay so a buff can't be instantly reapplied.
