### ISSUE TITLE
Buying Stacks of Non-stackable items removes gold but doesn't give items

### ISSUE THREAD

**Issue by Nizdizzle** [WarEmu/WarBugs#10703]
Buying a stack of items from an NPC vendor of items that do not stack takes the gold from the player but does not give the player the items.

Example: 
Go to T1 Renown Gear Merchant.
Shift + Click and type "2" into the pop-up for quantity to purchase and select OK.
Gold will be removed from inventory but items will not be added.

**Comment by sioding** [comment]
Sorry. We know that issue but atm we won´t change that. If you want to have two items (or more) please buy one after one.
