### ISSUE TITLE
Nordland Cap reward for Lvl17? possible Bug

### ISSUE THREAD

**Issue by Luggrim** [WarEmu/WarBugs#10709]
Hi guys

I just wanted to check, it appears you have updated the level limit for Tier 1 to 21?  Anyway my RP was lvl 15 and ended up at Level 17 by end of Nordland.  When Order capped the zone, I didn't get any reward.  No XP, RP, or Medallions.  Is this a bug or a restriction for been higher than level 15?

Sorry I didn't get a picture of my screen, and the game crashed when I opened the forum.  

FYI I think you guys are doing a great job, and am getting tired of the idiots whining about  things like Keep lord reset, etc.

**Comment by wargrimnir** [comment]
Level cap is still 15. You should be turned into a chicken if you reach R16 in RvR, and you don't receive rewards for T1 if you're outside the cap range.

**Comment by Luggrim** [comment]
Hi there

Then fyi last night myself and another didn't turn chicken when we hit
level 16 while in the zone.  However I did turn chicken when I went into
the zone later.  This was after my first email.

Thanks for fast response.

Jason
