### ISSUE TITLE
Slayer - no model on weapon

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#10704]
![sheykis_043](https://user-images.githubusercontent.com/18032193/32138023-bdea58a6-bc2b-11e7-908f-d32ca19d6095.jpg)
As seen on screenshot, Orcsplitter of the Patroller (reward from Ch3 High Elves influence) doesn't have model and it is invisible (and deals regular damage). Can be used as an alternative appearance which can be confusing

**Comment by sioding** [comment]
Fixed with patch from 4.11.2017
