### ISSUE TITLE
PQ, Fields of Ruin, Reikland

### ISSUE THREAD

**Issue by ktomais** [WarEmu/WarBugs#10708]
There is a weird issue when trying to enter or exit the keep in this PQ. It gives you a message that the PQ is ongoing, without something actually happening, resulting in either being locked out or locked in. In my case a log-out, log-in seemed to fix the issue after a few moments.

**Comment by Lheana** [comment]
Tried, could not reproduce. Were you Order or Destro? It is the door at 54k 58k, right?

**Comment by ktomais** [comment]
I am Order. Unfortunately I won't have access to my computer for a few days, to confirm the coordinates for you, my apologies. 

But I am talking about the main keep door, I believe there is also a gate on a small wall around it. 

In any case, the keep door of the tower in this particular PQ.

**Comment by ktomais** [comment]
Another user noticing the same thing.

https://github.com/WarEmu/WarBugs/issues/10741

**Comment by Lheana** [comment]
Issue still happening?

**Comment by ktomais** [comment]
I went to check it to confirm. In my try everything worked fine. I even went up to click on Lord Heinrich to make sure there isn't anything weird happening with the targeting. 

Issue seems fixed.

**Comment by Lheana** [comment]
Ok so I close the ticket. If it happens again, comment and reopen it.
