### ISSUE TITLE
[Magus] Ninestaff of Woe

### ISSUE THREAD

**Issue by Radiantknight** [WarEmu/WarBugs#1070]
Here I found some other stats for Magus's staff, which correspond with other staffs for this class:
http://www.warbits.com/gold-items-15814-Ninestaff-of-Woe.html
There's 20 WP instead of toughness.
Also, no results for this ninestaff on Arsenal of war and war.mmodb
If there's already a topic about wrong stats, please redirect me, couldn't find it, but would like to contribute.

**Comment by xyeppp** [comment]
Wasn't this changed to Toughness due to http://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=5050&p=55460&hilit=ninestaff#p55460 ?

**Comment by Radiantknight** [comment]
oh well, Github told as much, can close
