### ISSUE TITLE
Event-cloak alternate appearance not working

### ISSUE THREAD

**Issue by Tykros** [WarEmu/WarBugs#10714]
Hey,

Character named Shyish, Sorcerer.

Got from the event the cloak "Hide of the Varghulf" and tried to use it as alternate appearance for "Khaine's Alter Charmcloak" (T1 RVR Elf Inf Reward) - both cloaks are lvl 12 

When I try to put Varghulf in the slot for alternate appearance, I get the usual pop-up telling me my former appearance will be lost but the item doesn't get locked in it slot. 
I can wear Varghulf as a normal cloak though. 

I relogged and restarted the game, both did nothing.

I haven't taken any screenshot because I can't really show more than an item in my back-pack and I don't have filming software to show you me trying to put the item in the slot. I hope this description will be enough.

Regards

**Comment by sioding** [comment]
Fixed with patch from 4.11.2017
