### ISSUE TITLE
PQ progression tracker not displaying

### ISSUE THREAD

**Issue by Domorak** [WarEmu/WarBugs#10718]
The first time i enter any PQ area the tracker displays just fine but if i leave the pq area and come back later the progession wont show up, I can participate in the pqs normaly and get normal loot roll its just the tracker that wont show up again. I tried disabeling all Addons and restarting the game and it still happens.

First time entering the area:
https://i.imgur.com/AZe5jCe.jpg

After leaving the PQ area and coming back:
https://i.imgur.com/H8bNCQx.jpg

**Comment by sioding** [comment]
Thanks for the report. As far as i can see on the screens are you not standing at the same spot. Does this issue appears on every PQ you are participating?

**Comment by Domorak** [comment]
It apears with every PQ ive been at in the last 2 or 3 days. and in the pictures im standing maybe a couple of steps apart.
After some more testing It also seems if the i leave the pq area, the PQ gets finished without me there, and then gets completed or reset again without me having been anywhere close. (so PQ resets twice without me close) and i then move into the PQ area the tracker shows up again until i leave then its gone again.

**Comment by sioding** [comment]
Fixed with Hotfix from 31.10.2017
