### ISSUE TITLE
Harbinger Runed Beads, Jewellery

### ISSUE THREAD

**Issue by gke96** [WarEmu/WarBugs#10713]
Isn't this supposed to be Bright Wizard rather than Warrior Priest? Intelligence for WP?

![dogwhisperer_011](https://user-images.githubusercontent.com/11146551/32146656-cb594e46-bceb-11e7-9027-28e2079cb85f.jpg)

**Comment by wargrimnir** [comment]
Runed Beads are a Runepriest accessory. Shared among healers.
