### ISSUE TITLE
Teleport Issue / Lair of Snizzort

### ISSUE THREAD

**Issue by Gstarhk** [WarEmu/WarBugs#10715]
Lair of snizzort : 
When you go straight ahead
![starhk_006](https://user-images.githubusercontent.com/30270344/32180327-f068352a-bd91-11e7-974b-01470a8dc7ac.jpg)
you're teleporting here, in the top of the hill
![starhk_004](https://user-images.githubusercontent.com/30270344/32180338-f855446c-bd91-11e7-88eb-efb8338b721d.jpg)

![starhk_005](https://user-images.githubusercontent.com/30270344/32180342-fbd46a50-bd91-11e7-96a3-d34504548009.jpg)

**Comment by sioding** [comment]
fixed with patch from 09.03.2018
