### ISSUE TITLE
Not being able to participate in scenarios. 

### ISSUE THREAD

**Issue by jihsgabj** [WarEmu/WarBugs#10711]
After receiving scenario invitation i retreated from combat, but it still didn't allow me to participate, then  made sure i don't have any hostile npc targeted, still wasn't able to join.
![saphyria_007](https://user-images.githubusercontent.com/33173649/32146372-847c90e0-bce7-11e7-9bba-258f53cfe352.jpg)
![saphyria_009](https://user-images.githubusercontent.com/33173649/32146373-8498d26e-bce7-11e7-94d7-3447208564d3.jpg)
![saphyria_011](https://user-images.githubusercontent.com/33173649/32146374-84b7e69a-bce7-11e7-94f1-47916060f1ff.jpg)

**Comment by cimator** [comment]
its a well known bug, type .unlock or .u to fix it

**Comment by sioding** [comment]
Thanks again @cimator
