### ISSUE TITLE
old loot rolls working in parralel with new loot system

### ISSUE THREAD

**Issue by acidicrain** [WarEmu/WarBugs#10719]
Hi/
just left praag and got a white bag. went to CW and was around the keep and the old loot roll poped up. nothing was locked but the loot roll showed. i did not  win a bag so can not say if it gave rewards .. ss here.
![poxi_000](https://user-images.githubusercontent.com/28633576/32190491-49daa46e-bdae-11e7-8672-96259bd4da74.jpg)

**Comment by acidicrain** [comment]
same zone just locked with new loot system

**Comment by sioding** [comment]
ORvR System is a different than the PvE System. The old system works fine and your screenshot shows you have contributed to the Southern Breach PQ. Thats why you rolled for the PQ.

**Comment by acidicrain** [comment]
ok see that now :) , sry for not looking better
