### ISSUE TITLE
Stuck but stuck commands would not work, or display

### ISSUE THREAD

**Issue by Lokenoth** [WarEmu/WarBugs#10710]
Was just about to jump off the edge of the keep but fell short, got caught on the big spike and continued to fall endlessly. The "You are stuck" prompt never showed, and attempts at using /stuck were met with an error demanding that I stop moving before attempting the command again. I was able to use .u to "Bounce" back out and up onto the ledge. 

![lokrin_027](https://user-images.githubusercontent.com/17035321/32145736-51b7381c-bcc5-11e7-8ab5-1475621c04c8.jpg)
![lokrin_030](https://user-images.githubusercontent.com/17035321/32145737-51cad660-bcc5-11e7-8eeb-bd53b5be7289.jpg)

**Comment by sioding** [comment]
Please a GM ingame. You can check which GM is online by using this command: .gmlist

**Comment by Lokenoth** [comment]
Well I was referencing the fact that It wasn't giving a stuck response when stuck but okay...
