### ISSUE TITLE
List of Set Gear - Incorrect Listing for Ironbreaker Beastlord

### ISSUE THREAD

**Issue by Zoggof** [WarEmu/WarBugs#10729]
In the google doc "Complete List of Set Gear" found here - https://docs.google.com/spreadsheets/d/1EFNAP_IYPHAYAEL1IbbxstkkMtN6VIjK5l9Z8tg2IAQ/edit#gid=0

Ironbreaker Beastlord 6 piece set bonus is listed as Corrosion (the armor debuff) while in-game the Ironbreaker Beastlord 6 piece set bonus is Erosion (the resistance debuff).

**Comment by sioding** [comment]
Thanks for the report but this bugtracker is only for ingame issues. Please use the forum for those things.
