### ISSUE TITLE
Can't choose influence rewards at greenskin T2 WC (BV - MoM)

### ISSUE THREAD

**Issue by Jerkling** [WarEmu/WarBugs#10720]
i have accumulated enuf influence to choose up to a 2nd tier influence reward at the greenskin Tier 2 Open RvR warcamp in MoM, yet when i talk to the NPC and open the window to select the rewards it says "Need more influence" -.-

![vladolfr_000](https://user-images.githubusercontent.com/33235244/32194311-4f8bff78-bdba-11e7-8f68-3072120c3fa1.jpg)
![vladolfr_001](https://user-images.githubusercontent.com/33235244/32194312-4fa6149e-bdba-11e7-91ff-964fa3aa1221.jpg)

**Comment by sioding** [comment]
Just go to the other WC and you can choose your inluence reward.
