### ISSUE TITLE
ToK/night goblin or goblin? 14.16 badlands

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#10727]
Badlands 14.16 across the river dwarf chapter 11 there is  4 night goblins (same skin) but when you kill it they count as goblin. Normal?

**Comment by sioding** [comment]
And the bug you would like to report is?

**Comment by thorbolt80** [comment]
When you kill it. He counts as "goblin" kill inside the Tok not "night goblin"

**Comment by sioding** [comment]
Thanks - thats helps to label your report.

**Comment by Lheana** [comment]
Nobwort and Moonfang Blasta will now count as Night Goblins. Tell me if I missed other NPCs around.

**Comment by sioding** [comment]
Fixed with patch from 4.11.2017
