### ISSUE TITLE
Construct of Bone [T1] doesn't respawn

### ISSUE THREAD

**Issue by Skirf** [WarEmu/WarBugs#10725]
The Boss "Construct of Bone" doesn't respawn. We waited around 30 minutes and he didn't respawn.

**Comment by sioding** [comment]
#10605

**Comment by Skirf** [comment]
There was no corpse. It wasnt the lair boss.

**Comment by sioding** [comment]
I just referenced a ticket. We know its one of the event bosses.

**Comment by Skirf** [comment]
The Boss finally respawned.

Greets
