### ISSUE TITLE
Harvest of Fear - Quest

### ISSUE THREAD

**Issue by Waaghaa** [WarEmu/WarBugs#10724]
The quest requires you to find Radcliff Shoerner in the fields of Felde, theres only 1 character in a coccon but it is guarded by a lvl 42 spider named "Silken" , there is no way to reach Radcliff w/o getting aggro from it.

**Comment by sioding** [comment]
removed double gameobject spawn and checked that there is no lvl 42 spider anymore.

**Comment by sioding** [comment]
fixed with patch from 16/02/2018
