### ISSUE TITLE
Teleporting to middle of nowhere

### ISSUE THREAD

**Issue by pootato** [WarEmu/WarBugs#1072]
When teleporting from Dwarf Tier 1 to Human Tier 1, you get teleported to the middle of nowhere.

**Comment by Radiantknight** [comment]
Same happens with Destro side too, actually on rare occasions happens upon teleports to anywhere.
With destro even more disturbing, when you get out of the scene and end up underneath IC, happens mostly when you are on a narrow walk around fly service

**Comment by monstertheme** [comment]
That's a tough one to fix if it's a random teleport, maybe you can narrow it down?

**Comment by Radiantknight** [comment]
Kinda hard to reproduce, just happens on using fly service. One time was stuck on a mountain half map away from greenskin t1 rvr camp, while porting from chaos t1 rvr. The other time was thrown in the water half map away from Norsca, while porting to chaos camp. Easier to reproduce IC bug than this one, honestly

**Comment by Evildoor** [comment]
Closing per #639.
