### ISSUE TITLE
Mail Icon Bug When Deleting Auction Item Returned from Auction House

### ISSUE THREAD

**Issue by Rilof** [WarEmu/WarBugs#10733]
My Mail icon on the map is still active although there is really no mail.  This took place when I proceeded to delete my returned item from the Auction House with my "Duelist" gloves for a Runepriest still in the mail.  I did not retrieve the item from the mail before I deleted it.  Perhaps this caused the bug...not sure.

Rilof

PS I hope this gets me a Bug Token for a mount!

**Comment by sioding** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366#p118993

**Comment by sioding** [comment]
#1109
