### ISSUE TITLE
6 blunderbluss blast from the same player at the exact same time

### ISSUE THREAD

**Issue by Starwhisper** [WarEmu/WarBugs#10737]
I really dont know what happened. This was like 15sec after the fight started.
https://imgur.com/a/Qd9G2
Sorry I did not know beforhand this would happen and combat log disappears so fast :( . I can only assure you they all ticked at the exact same time, there was like 20 people hitting me yet not a single hit form any other ennemy happened during the 6 BB hits.

**Comment by sioding** [comment]
Thanks fpr the report. As @wargrimnir  said: turn on the timestamps. We need a reliable evidence for those cases.
