### ISSUE TITLE
Silkens in Ostland lvl 40+

### ISSUE THREAD

**Issue by Duvaindir** [WarEmu/WarBugs#10736]
Ostland is an area for levels 10-11 and 14-15. In the pq "Silkens" while most spiders are around level 13 as normal, there are some that are level 40+ which instantly kill any player leveling there. Specifically, there is one such high level spider exactly in front of a quest objective which happens to be in the pq area (a man in a spider web). I presume that this is a mistake because I see no reason for such high level mobs being in that area. Thank you for your time.

**Comment by sioding** [comment]
Fixed with patch from 4.11.2017
