### ISSUE TITLE
Bug - Public Quest continuing and completing in RvR

### ISSUE THREAD

**Issue by Ranzinza** [WarEmu/WarBugs#10730]
Hello,

Bug in Public Quest. I entered the quest published (PQ) in Norsca, I killed 2 mobs and went to the RvR of NordLand. Even within the RvR I continued to gain influence from PQ, I was far away. when RvR ended, I had closed the influence of 2 PQ (Proving Ground and Rite Of Passage). Also, when I was on RvR NordLand and Blighted Isle map, PQ's chestbox was still active on the upper right side, implying that my char was within the radius of PB. 

Here is an attached photo.
https://i.imgur.com/iyqZX4D.png

Char name for log info: Rabugento (Destru)

Please forgive the errors in English, it is not my native language.

**Comment by Lheana** [comment]
Secrets fixed it.
