### ISSUE TITLE
Champion challenge not working at all

### ISSUE THREAD

**Issue by Asherdoom** [WarEmu/WarBugs#10734]
This morning with my BG i challenged a shadow warrior  with my champion challenge morale 2 of black guard. he just moved away like nothing happened. 
champion challenge clearly states he should not be able to move at all while this shadow warrior just walked away with his jump skill.

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format. 

You can help us by following these bugreport rules: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Asherdoom** [comment]
screenshot i will put once will happen again.

i was at armory in Marshes of Madness. I saw this shadow warrior incoming. I assault him with my mount and start dps him. We were in the middle of the road. i get morale and i use the Champion challenge on him to root him. As soon as the Trench appears, the shadow warrior uses his ability to disengage melee fight and fly away leaving me rooted and killing me while i was there taking hits for the while duration...

i will be try to get as much as screens as possible.

**Comment by sioding** [comment]
Thank you. I bet we would have more than one report about champion challenge here if this won´t work. 
I will close this for now - please do not hesitate do add a comment if you have an appropriate evidence.
