### ISSUE TITLE
Welcome to Troll Country Stage III

### ISSUE THREAD

**Issue by stealthc98** [WarEmu/WarBugs#10738]
If you drag The Rock to the guards and they kill him it bugs the 3rd stage of the PQ.  Troll Country area...

**Comment by Lheana** [comment]
NPCs 'Eckhart's Spearman' and 'Captain Eckhart' don't attack the trolls of the PQ. Pigs will no longer attack NPCs of the PQ.
Thus if players don't pull the NPCs to the NPCs of the chapter, everything should be fine.

**Comment by sioding** [comment]
Fixed with patch from 29.12.2017
