### ISSUE TITLE
Neborhest vanguard PQ order side marsh of madness chapter 8 stage 2 wrong location of champion pack

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#10731]
Neborhest vanguard PQ order side marsh of madness chapter 8

On stage 2 there is 2 pack of champions. The first spot of champion "souless dead" on stage 2 at 59.74 are not inside the PQ (too slighlty to the East of the map so when you kill champion  they don't count. 

The second pack are too close of dwarf guard so they fight each other you are not sure to get the kill.

**Comment by Lheana** [comment]
Dwarf NPCs will no longer attack NPCs of the PQ. There are no longer NPCs of second stage out of the PQ area.
However note that the PQ area still needs to be increased at the northeast to include all NPCs of first stage.

**Comment by sioding** [comment]
Fixed with patch from 26.01.2017
