### ISSUE TITLE
Heinrich Estate, Reikland, keeping you locked inside

### ISSUE THREAD

**Issue by baroke** [WarEmu/WarBugs#10741]
Can't click on the door to leave the Estate.

![malthala_000](https://user-images.githubusercontent.com/20115114/32319936-cf4cedd8-bfc4-11e7-89a9-dc7f88fb473d.jpg)

**Comment by baroke** [comment]
It fixed itself after relogging.

**Comment by sioding** [comment]
#10708

**Comment by Lheana** [comment]
This issue is not related to #10708 . The issue here is that sometimes the GO that is targeted when clicking on the door is another GO (a scroll) located at the top of the tower. Thus clicking on it does not open the door.
There was an error in DB, so I think I fixed it.

**Comment by sioding** [comment]
Fixed with patch from 6.1.2018
