### ISSUE TITLE
Resolute Defense and Cleansing Wind not working

### ISSUE THREAD

**Issue by Anirne** [WarEmu/WarBugs#10740]
Greetings,
I am having issues with two abilities from the renown tree, resolute defense and cleansing wind.
Whenever I try using on of the abilities I am getting an implementation error
"27832 Resolute Defense has no implementation"
"27826 Cleansing Wind has no implementation"
I haven't played the game for a month or two and I looked for older patch notes trying to notice a change but I couldn't. I'v also asked in advice chat if people had the same issue as mine, some had a problem as well , some said theirs were working, some said it bugs sometimes.
Iv tried wiping renown points from mastery trainer and relearn the abilities, nothing changed.
Here are pictures showing in chat what I'm seeing when I try to use the abilities.

![pic2](https://user-images.githubusercontent.com/33312326/32316188-dd21256c-bfb7-11e7-8165-b940902e69a1.jpg)
![pic1](https://user-images.githubusercontent.com/33312326/32316189-dd3eb096-bfb7-11e7-9ebe-8b3a1ed680ef.jpg)

**Comment by Yellowpillow** [comment]
Same issue with me, yesterday it worked just fine and today it doesn't.

**Comment by Runiez** [comment]
Worked yesterday, broken today.....

**Comment by spacestarkid13** [comment]
I confirm. "27832 Resolute Defense has no implementation".

**Comment by sioding** [comment]
Working as intended. See patchnotes from 4.11.2017
