### ISSUE TITLE
T2 Empire vs Chaos Keep Resource BUG?

### ISSUE THREAD

**Issue by Xkullibor** [WarEmu/WarBugs#10748]
So me and a couple of other ppl formed a wb and captured all 4 BO's. At some point the lvl bar of the keep was full and then it reseted. Then it started filling up and reseted again.

Any ideas? I got a video but don't know how to post it

**Comment by Xkullibor** [comment]
Doesn't accept it apprently

**Comment by Xkullibor** [comment]
![1](https://user-images.githubusercontent.com/33327610/32341452-2fca7360-c006-11e7-80b0-2c378518d657.jpg)
![2](https://user-images.githubusercontent.com/33327610/32341453-2ff17f00-c006-11e7-9e0e-b053762234f0.jpg)

**Comment by Hargrim** [comment]
Please read recent patch notes. If yours oponent AAO is 80% or more 5 star keep lock is no longer available.
