### ISSUE TITLE
Client bug report

### ISSUE THREAD

**Issue by Radiantknight** [WarEmu/WarBugs#1075]
Don't know if it works. Have sent some reports, but other than 'Your feedback has been sent' can't see results. If it doesn't, then change topic for bug to Quest Reward lost (couple of quests in Troll country give talismans as rewards, selected talisman, didn't receive it)

**Comment by Evildoor** [comment]
Closing this since https://github.com/WarEmu/WarBugs/issues/1634 has more information. Bugged quests should be reported separately and with more details (at least quest names).
