### ISSUE TITLE
Rest Exp bug on Corrupted Farmhand mobs

### ISSUE THREAD

**Issue by KiraAnathema** [WarEmu/WarBugs#10750]
me and a friend are in a party, we both have rest exp and are killing mobs one lvl above us, which are called "Corrupted Farmhand", which you find in "Talabecland" (lvl 26-29, bottom left PQ). they should be giving us about 2k exp (in a 2man group), they are only giving us about 1k exp, which would be the unrested exp. when i solo kill that mobtype, it gives me 4k exp, which is correct, but in a 2 man party, the rest exp doesnt apply.

**Comment by sioding** [comment]
Fixed with patch from 4.11.2017
