### ISSUE TITLE
Realm not found

### ISSUE THREAD

**Issue by austinsmith-zz** [WarEmu/WarBugs#10754]
Every time I start the world server it says Realm <num> not found. How to fix?

**Comment by sioding** [comment]
Are you running your own server?

**Comment by austinsmith-zz** [comment]
yes @sioding

**Comment by austinsmith-zz** [comment]
I tried to look back at the code and trace everything to see why a realm isnt being created when I run everything but no luck so far

**Comment by sioding** [comment]
This bugtracker is only for RoR ingame issues. So sorry - you won´t get any help here.
