### ISSUE TITLE
Shaman - "Ain't Done Yet" 

### ISSUE THREAD

**Issue by freshour** [WarEmu/WarBugs#10769]
Tactic states "Healing abilities" are increased by 40% when target is below 25% hp. It currently only works on direct heals and not HoT's when all other tactics that increase total healing also affect HoT's. So either the tactic info needs changed, or the ability needs to made to affect HoT's as well.

**Comment by Torquemadra** [comment]
provide proof this is how it worked on live

**Comment by sioding** [comment]
No confirmation after 18 days. Case closed.
