### ISSUE TITLE
[Item] Bloodfist rapier no + Mele power

### ISSUE THREAD

**Issue by iAleks2008** [WarEmu/WarBugs#10763]
Bloodfist rapier no + Mele power

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format. 

You can help us by following these bugreport rules: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
