### ISSUE TITLE
Bolstering broken again after patch 4/11/2017

### ISSUE THREAD

**Issue by BrockRiefenstahl** [WarEmu/WarBugs#10765]
Agonizing wounds from behind is ignoring all armor.
I have super low dmg on lvl 18 toons today. There must be some bug with super high toughness.
The WP in screenshot ran away a kilometer while I stabbed his back with black lotus healdebuff + kiss switch healdebuf + ap drain kiss.

not sure if attachment works here imgur link to combat log

https://imgur.com/a/z3ezD

That is seriously not normal today 
![bolsteringbroken](https://user-images.githubusercontent.com/32821249/32410235-e9ac463a-c1bb-11e7-9cfe-d1f5f4635edc.png)

**Comment by sioding** [comment]
#10766

**Comment by sioding** [comment]
Should be fixed
