### ISSUE TITLE
Chapter 9 broken gear

### ISSUE THREAD

**Issue by Titoos** [WarEmu/WarBugs#1076]
Hi, this is an example of ch9 gear missing some stats (BO version):

http://war.mmodb.com/items/blightstone-eadplate-94686.php (missing 20 Wounds)
http://war.mmodb.com/items/trolldoom-feetsplate-96974.php (missing 12 Wounds)
http://war.mmodb.com/items/trolldoom-andsplate-94685.php (missing 17 WS)

It would be fine to fix that, as it vital alternative for conqueror/woe gear.

**Comment by Styrkarr** [comment]
Fixed in the next patch.
