### ISSUE TITLE
Kotbs strong aura bug

### ISSUE THREAD

**Issue by Enrow** [WarEmu/WarBugs#10761]
Hey i found out when you activate youre Kotbs Aura´s in open rvr and then run out into pve or do scenarios as low level youre auras are still bolstered so instead 50toughness you get at level 16 you get 140 toughness in an scenario  or when you farm pq or grind  its the same with all other auras like the heal aura or reflect aura they all do much more heal/damage . Its just overpowered in scenarios or while grinding

When you got questions. Whisper me ingame
I mainly play on Dragclaw,Othania or Hawk

**Comment by sioding** [comment]
Fixed with hotfix from 5.11.2017
