### ISSUE TITLE
Public Quest - Bloody Savages

### ISSUE THREAD

**Issue by Niobandi** [WarEmu/WarBugs#10764]
The Order Public Quest " Bloody Savages " in the Badlands got a surprising Lvl 41 Champion in his middle.

![aldroin_000](https://user-images.githubusercontent.com/16079024/32409712-0d54ba64-c1b1-11e7-8ada-b9f3ebcccf92.jpg)
![aldroin_001](https://user-images.githubusercontent.com/16079024/32409713-0d770268-c1b1-11e7-9d9d-6ab2d7079e2f.jpg)

**Comment by sioding** [comment]
Fixed with hotfix from 5.11.2017
