### ISSUE TITLE
Dwarf slayer still trigger for order side inside Tok

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#10770]
I just killed 100 slayers then I got the trigger in Tok. As order I am not suppose to trigger it.

FYI I check all other order class (11) they are not broken inside Tok only dwarf slayer.

**Comment by Lheana** [comment]
There is a special entry for slayers. There are pve slayers ("Dwarven, Slayer" in ToK) AND pvp slayers ("Dwarf, Slayer" in ToK). Order is not able to trigger the unlocks for pvp slayers, but they can for pve slayer. And as an Order, you are not able to kill pvp slayers so I am sure you are talking about pve slayers and not pvp slayers, which means it is not a bug.
