### ISSUE TITLE
[Rally Master Bug] Breaka da Big

### ISSUE THREAD

**Issue by Asherdoom** [WarEmu/WarBugs#10774]
in MOM (marshes of Mdness) the t2 warcamp rally master is not offering any influence at all. To be precise, the items are not eligible and just appears as blank squares. they are not clickable at all.

i leave screen here to explain myself better. I checked in bug tracker so far found nothing about this issue :)

https://imgur.com/a/l8z6M (Rally Master bugged)

**Comment by sioding** [comment]
Did you´ve tried to get your influence items in Barak Varr ?

**Comment by Lheana** [comment]
Try in Barak Varr. When several zones (and thus different rally masters) share the same influence rewards, only one of them is able to give the rewards for now.
Also it has already been reported before, so please check for reports before doing one.
