### ISSUE TITLE
[Item Missing salvageable tag] Badmoon Carapace 

### ISSUE THREAD

**Issue by Lokenoth** [WarEmu/WarBugs#10782]
Not too sure if its intentional or not but just selected the badmoon carapace for salvaging purposes only  to realise its the only item available from t4 Orc 2nd influence reward that does not have the salvageable tag. 

![compilation](https://user-images.githubusercontent.com/17035321/32457660-c632101a-c321-11e7-8f8d-10dec722f068.png)

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
