### ISSUE TITLE
KotBS/Chosen Aura bug

### ISSUE THREAD

**Issue by Enrow** [WarEmu/WarBugs#10781]
Hey i need to recast my auras in open rvr when i switch the zones example, in Troll Country when i go into Ostland or it happens just random in a fight or when i stand somewhere at  a flag my auras stop working but in my skillbar it still shows me that its activated even when i dont get the buffs from it.

When you get questions whisper me ingame 

Dragclaw,Othania

**Comment by sioding** [comment]
Checked that on my own - is not reproducable

**Comment by Lokenoth** [comment]
@sioding 

I've had this happen on my chosen as well I'm not sure what causes it, I believe it has a small chance to occur when changing zones. Or joining / leaving scenarios. I'll keep an eye out on it to see if i can force it to reproduce the error. 

As you can see in this image I've got 1 aura active on my character portrait, but all 3 auras are highlighted as if active. Clicking on them recasts them as if they were not engaged.

![lokrin_051](https://user-images.githubusercontent.com/17035321/32471989-15b705c4-c358-11e7-929d-4eb9390235aa.jpg)

**Comment by sioding** [comment]
Thanks. @Lokenoth  and @Enrow if you have any chance to reproduce that on a way we can understand that i will reopen this issue. I tried that yesterday on a lot zones/sc pops etc - and it never occured.

**Comment by Lokenoth** [comment]
@sioding Had it occur a couple more times today, I believe its when going into Scenarios whilst in RVR Lakes. at least thats what seems to be the issue for me. Or zoning from RVR Lakes (EG the use of the book of binding)

[Picture 1] : All 3 auras were show as active on my hotbar, only 2 auras showed as active on my character panel. And on others near me, my stats were not changed by the auras displaying as active.
[Picture 2] : Activated Dreadful fear, thinking that it was just the one aura that had failed, causing both Dreaful Fear and Corrupting Wrath to drop off the buff menu but remained active.
[Picture 3] ; After returning from Nordland Scenario I used my Book of binding in the Dragonwake RVR lake, moving me to chaos wastes warcamp, before flying to IC and re-specing my renown abilities. Noticed that my strength seemed low. before realising all auras displayed on my hot bars had once again turned off. 
[Picture 4 / 5]: Showing my toughness before and after I re toggle corrupting wrath that shows as active in my hotbar. 
![lokrin_062](https://user-images.githubusercontent.com/17035321/32500372-21ad21ea-c3cd-11e7-9488-6002710911b5.jpg)
![lokrin_061](https://user-images.githubusercontent.com/17035321/32500373-21caa9ae-c3cd-11e7-9772-5f93f118c07d.jpg)
![lokrin_064](https://user-images.githubusercontent.com/17035321/32500379-25644692-c3cd-11e7-8377-58db0024267b.jpg)
![lokrin_063](https://user-images.githubusercontent.com/17035321/32500382-279a2a26-c3cd-11e7-8b66-47a3fecf9303.jpg)
![lokrin_065](https://user-images.githubusercontent.com/17035321/32500386-290f7cc6-c3cd-11e7-8cd0-a56427b38e1b.jpg)

**Comment by Enrow** [comment]
Yea this happend on my Kotbs^^ and its still happening

**Comment by Lokenoth** [comment]
@sioding Just hit a Scenario whilst in IC and its dropped off right then and there when I exited. I believe it to be the character move to the Scenario server that causes the issue.

**Comment by Lokenoth** [comment]
@sioding Yep it happens when you leave scenarios quite frequently.

**Comment by Shmerrick** [comment]
This also occurs when you level up. Level up causes auras to clear and they have to be reapplied.

**Comment by Natherul** [comment]
This is not a bug, its due to bolstering/debolstering. 
As we dont want the auras to be at a higher level then intended they are dispelled.

**Comment by Lokenoth** [comment]
@Natherul I was rank 40 so not under the effects of bolster though.

**Comment by Natherul** [comment]
yes, initially it did not check at all the rank, and when you enter a rvr zone it does the bolster check regardless of level, this has changed since though and lvl 40s should be excluded from that part of code
