### ISSUE TITLE
Quests Gone

### ISSUE THREAD

**Issue by ArdzofPT** [WarEmu/WarBugs#10788]
Yesterday when I logged on, all my BW's quests were gone. I was able to pick up quests that can only be completed once, and repeatables. I gathered a bunch of kill player quests and SC quests, etc. Today when I logged on, all her quests were missing again. This seems to only happen to my BW. I haven't logged on all my alts, but my RP and Knights seem fine.

She kept her quests when I logged out to char select, and also when I exited game and relogged. This bug seems to happen while I sleep at night - so maybe it happens with server restart or something? But again, only seems to happen to the BW.

**Comment by sioding** [comment]
#10476
