### ISSUE TITLE
Breaking Keep Door with Rune of Iron

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#10783]
You can use the Rune of Iron dot on keep doors and nuke them fairly quickly open. The 4 dots shown in the screenshot did about 3% damage. So with a warband you can probably kill the keep door faster this way than with a ram.

![cimbina_050](https://user-images.githubusercontent.com/16117730/32465708-a73d223a-c344-11e7-84a9-dfe7a2aa6aa5.jpg)

**Comment by Lokenoth** [comment]
I believe you can also use some of the Zealot granted dots on the destro side to do the same thing. I can't remember which one it is though.

**Comment by Lokenoth** [comment]
Borrowed a guildy to test this out on Stone Troll Keep in Troll Country.  The Zealot abilities Spell destroyer and Vortex both damage the keep. 
![lokrin_058](https://user-images.githubusercontent.com/17035321/32473252-93f65722-c35e-11e7-977e-06c99c9a03b9.jpg)

**Comment by sioding** [comment]
Thank you for the report. Will be fixed with next patch.

**Comment by sioding** [comment]
Fixed with patch from 10.11.2017
