### ISSUE TITLE
Resist buffs not applying until you change stance as Marauder

### ISSUE THREAD

**Issue by AlistaireCrowley** [WarEmu/WarBugs#10786]
When my Marauder get an resist buff it doesnt show until I change stance. 
Do not know if it is only visual. 
Have noticed it both with shaman, zealot resist buff and chosen resists aura.

**Comment by Lokenoth** [comment]
Just tried this with another Mara and my chosen resist Aura, I couldn't recreate the issue with any of the Stances or with any of my Auras. (Including the resist aura) 

Perhaps its an issue with being rebolstered?

**Comment by AlistaireCrowley** [comment]
Ok. Very wierd. Might have been in SC:s then. I noticed it several times yesterday. Tried it in IC today and it was working. Ah well. My bad. I will keep an lookout if it occurs again and will holler.

**Comment by sioding** [comment]
good one @AlistaireCrowley. Until that - this is closed.
