### ISSUE TITLE
Cleansing an Empire - WP Book Reward

### ISSUE THREAD

**Issue by Zackaos** [WarEmu/WarBugs#10799]
I have just completed and chosen the purple book from the epic quest line but noticed it says 6 RF per second (the buff gained from a blue book) But I think purple books should be 8 RF per second. Character in game is Zachmar.
This is a normal purple book:
![image](https://user-images.githubusercontent.com/33501774/32581196-bf1fc7de-c4e0-11e7-9875-23e6ba11f2b5.png)
This is the Reward book:
![image](https://user-images.githubusercontent.com/33501774/32581204-d13922b2-c4e0-11e7-9ac2-c9551f9aabbb.png)

**Comment by sioding** [comment]
fixed with patch from 09.03.2018
