### ISSUE TITLE
Blackguard - Enraged Beating

### ISSUE THREAD

**Issue by danissrv** [WarEmu/WarBugs#10791]
There is an issue the last few days that Enraged Beating "gets interrupted" most the time when they hit me and completely stops the channeling. 

Another issue seems that I am losing AP when channeling EB. That was not the case a few days earlier also... 
Is there any "hotfix" that made it cost 25AP/sec?

**Comment by Zoggof** [comment]
Just to add to this, I get this for other melee channels as well (eg: T'ree Hit and Grudge Born Fury), the interrupt always gives me the message "Cannot see target" after half to one second of channel.

**Comment by sioding** [comment]
Fixed with patch from 10.11.2017
