### ISSUE TITLE
High Elf Ch15 Slayer inf reward skin

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#10793]
Foeseeker's Torc reward from ch15 influence HE got skin and icon of the body armor (not shoulders)
![sheykis_054](https://user-images.githubusercontent.com/18032193/32538423-4236aae6-c466-11e7-8099-8cf5af11e3d9.jpg)
![sheykis_055](https://user-images.githubusercontent.com/18032193/32538424-424ffafa-c466-11e7-99d9-7dfdbf36b7ec.jpg)

**Comment by NorKalli** [comment]
assigned level 29 green shoulders

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
