### ISSUE TITLE
RvR flagged when exiting a SC on a T1 zone

### ISSUE THREAD

**Issue by baroke** [WarEmu/WarBugs#10794]
There seems to be some inconsistency on what happens after you exit a SC.
I am R20.
I queue all SCs from Nordland, not RvR flagged, join the SC and when exiting, for some unknown reason, i become RvR flagged, thus a chicken.
When i do exactly the same thing from Troll Country, i am unflagged when i exit the SC.

p.s. by "exit the SC", i mean that the SC finishes normally, i don't run away.

**Comment by Razielhell** [comment]
This is not only happening when you exiting a SC but also when you relog. Or when you make a new character you get RvR flagged for no reason.

**Comment by sioding** [comment]
fixed with patch from 06.07.2019
