### ISSUE TITLE
Scs death

### ISSUE THREAD

**Issue by Lodykillington** [WarEmu/WarBugs#10804]
Hi,

I just left a scenario and found myself instantly killed upon returning to the inevitable city. I attempted to respawn but when the timer ended I just continued to lay there dead on the exact same spot. Relogging fixes the issue but it has happened before, so I just thought I'd mention it.

**Comment by sioding** [comment]
Can we please have screenshots whit the combat log?

**Comment by Lodykillington** [comment]
Next time it happens I will take some screenshots


________________________________
Van: Sio <notifications@github.com>
Verzonden: vrijdag 10 november 2017 7:49
Aan: WarEmu/WarBugs
CC: Lodykillington; Author
Onderwerp: Re: [WarEmu/WarBugs] Scs death (#10804)


Can we please have screenshots whit the combat log?

**Comment by sioding** [comment]
Thanks - until thiat happens - i close this one.
