### ISSUE TITLE
Beastlord - Completing quests not recieving tokens

### ISSUE THREAD

**Issue by s0undie** [WarEmu/WarBugs#10803]
So, done all 5 of the beastlord bosses and gotten then quests handed in and recieved gear. Oddly i have not recieved any tokens for the 6th piece.

**Comment by Zurgoth76** [comment]
Done all 5 quest Beastlord Bosses,but just 4 quests are available (i've killed 20 Bw-20 Slayers-10 WL/10SW-20 Eng, so a killing quest is missing,but can't pick it
