### ISSUE TITLE
Quest: The Blood Of Our Enemies

### ISSUE THREAD

**Issue by WarbossWarboss** [WarEmu/WarBugs#10800]
On the final step of the quest The Blood Of Our Enemies in Nordland, the quest objective is a Pyre in Death's Brink.  However, the quest shows the location as the previous objective, in Pillage and Plunder.  The quest is still readable and completable if you pay attention to the text.

**Comment by Razielhell** [comment]
The whole quest objective was wrong for last stage. Thanks for the report.
Will be fixed with next Patch!

**Comment by sioding** [comment]
Fixed with patch from 17.11.2017
