### ISSUE TITLE
[Scenario] Battle for Praag

### ISSUE THREAD

**Issue by Lokenoth** [WarEmu/WarBugs#10808]
Multiple objectives were open for capture in the Battle for Praag Scenario.

This was caused by a player starting the capture before the timer ran out on the final Order side BO as it was about to lock for order, when  causing both central Praag and north Praag to both be open, and contested.

[Picture 1] Myself standing at a contested central praag in sight of the contested North Praag objective.
[Picture 2] the Scenario map registering the same information, as the visual pings. 
![lokrin_075](https://user-images.githubusercontent.com/17035321/32677815-df2d44ac-c657-11e7-9f10-ed0ca0677153.jpg)
![lokrin_076](https://user-images.githubusercontent.com/17035321/32677816-df425f86-c657-11e7-8b27-ecd17299b9a5.jpg)

**Comment by Natherul** [comment]
should be fixed as of today
