### ISSUE TITLE
RvR flagged at char creation

### ISSUE THREAD

**Issue by severeleven** [WarEmu/WarBugs#10805]
All new Order characters are created flagged for pvp (this doesn't seem to effect Destro), using /rvr removes the flag after 10 mins but the potential for griefing is obvious.

**Comment by Lokenoth** [comment]
I can confirm they are all starting off flagged for RVR.

![lokrin_070](https://user-images.githubusercontent.com/17035321/32638743-af42b01e-c5b8-11e7-8f71-b9afb2866820.jpg)

**Comment by sioding** [comment]
It does not depend on char creation. Even Level40 chars are rvr flagged when they log on a t1 zone or join a t1 zone. #10794 
So this issue is closed after referencing it to the first one.
Thanks fpr the report.

**Comment by Lokenoth** [comment]
@sioding 

Just checking wouldn't that mean if I entered Tier 1 on my 40 (Which I did) then I'd be instantly turned into a chicken? Or does that only happen when you kill someone? AS the Scenario report would suggest it happens regardless of whether I kill anyone or not.
