### ISSUE TITLE
Lissariel's Glade didn't complete - Public Quest

### ISSUE THREAD

**Issue by Zleepyhead** [WarEmu/WarBugs#10801]
We killed Deeproot but the PQ didn't finish properly and didn't reward us with any chest.
The group consisted of me (Ironbreaker), an Engineer and a Warrior Priest.
We killed him by having me taunt him and run around, kiting him while engineer providing ranged dps and stunning when able and warrior priest healing us.

![lissarielpq](https://user-images.githubusercontent.com/23521005/32594248-95471836-c52b-11e7-8b1d-9bc98aaa48e7.png)

**Comment by Lheana** [comment]
Are you sure it's one player who had the kill, and not a NPC near?

**Comment by Zleepyhead** [comment]
90% sure. We kited him away from the mobs if I recall correctly. Can't find any combat logs to check though :/

**Comment by Lheana** [comment]
Have you tried again the PQ?

**Comment by Lheana** [comment]
Tried on dev server, worked. I advice you to try again, really far from the NPCs.

**Comment by sioding** [comment]
two weeks done without an answer. case closed
