### ISSUE TITLE
sooo sloooooow

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#10809]
it seems the bug that allowed channeled/buildtime skills to be to cast on the move is still partially in effect, if your wounded badly enough to be slowed AND using walk speed you can still cast on the move (discovered by accident using pit of shades, i havnt made any attempt to test whether this also works with walking while snared)

also discovered that when i logged out with 5 health debuffs i logged back in with only one after forgetting to mail some junk to my salvager

**Comment by Lokenoth** [comment]
I can confirm logging out reduces the wound debuff stack! (Thanks Druin for your help with this.) 
![lokrin_080](https://user-images.githubusercontent.com/17035321/32684850-56c86582-c680-11e7-95a4-a5db97a02a37.jpg)
![lokrin_079](https://user-images.githubusercontent.com/17035321/32684851-56dd03de-c680-11e7-9559-38bec7197436.jpg)

**Comment by Penthactus** [comment]
Your character looks awesome.

**Comment by Kaelang** [comment]
This should've been fixed in a recent patch.
