### ISSUE TITLE
Marauder's Gift of savagery and siege weapon

### ISSUE THREAD

**Issue by Lotsdawittaz** [WarEmu/WarBugs#10807]
I've noticed that gift of savagery can proc on players while you damage them with a siege weapon. Looks like a bug to me. I think you couldn't be able to proc it while you do damage not by yourself but with help of smth else. Here is a screenshot. You can see that proc from subjugator weapon "Cuncussion X" can happen also to other players, moreover some procs from players can affect you while you do damage to them with siege weapons.
![warhammer online age of reckoning screenshot 2017 11 10 - 18 56 20 46](https://user-images.githubusercontent.com/23447430/32668421-8e5c44b4-c64e-11e7-888b-f19fef89d2bd.png)

**Comment by sinadin** [comment]
same for Witch Elf Kisses - an aoe Heavy Dark Elf Bolt Thrower with Kiss of Death (heal debuff) = awesome.
Needs to be fixed - where is my mount :-)

**Comment by sioding** [comment]
> Anyone who asks for a Griffon or Manticore mount will not receive one, regardless of whether the report would otherwise be eligible.

**Comment by sioding** [comment]
fixed with patch from 8.12.2017
