### ISSUE TITLE
Dodge and Disrupt rates are not working as intended

### ISSUE THREAD

**Issue by Shmerrick** [WarEmu/WarBugs#10818]
Dodge and Disrupt rates are not working as intended. Chance to defend is much higher than the original game. Players with relatively no attribute points in initiative or willpower are dodging and disrupting 20%-40% of the respective attack type. I have only done testing in T1 & T2-T3.

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format. 

You can help us by following these bugreport rules: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Shmerrick** [comment]
Will do.

**Comment by Torquemadra** [comment]
you are basing this on what exactly? Because these are client values

**Comment by sioding** [comment]
No proofs after 15 days. Close.
