### ISSUE TITLE
Detaunt clears if dots are applied

### ISSUE THREAD

**Issue by Shmerrick** [WarEmu/WarBugs#10819]
Detaunt not working as intended. Detaunt clears if dots are applied to the detaunt target.

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format. 

You can help us by following these bugreport rules: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Shmerrick** [comment]
https://youtu.be/gaFv8hUp3uU

**Comment by Torquemadra** [comment]
working as intended
