### ISSUE TITLE
new WAR.exe exception on client exit

### ISSUE THREAD

**Issue by baroke** [WarEmu/WarBugs#10815]
When exiting the game with the new WAR.exe, i got the following exception in Visual Studio:

The thread 0x20c4 has exited with code 0 (0x0).
Unhandled exception at 0x005C0BF4 in WAR.exe: 0xC0000005: Access violation reading location 0x00000000.

Call stack:
>	WAR.exe!005c0bf4()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for WAR.exe]	
 	WAR.exe!0099da8d()	Unknown
 	WAR.exe!0099dc39()	Unknown
 	WAR.exe!0099dc44()	Unknown
 	WAR.exe!009962f9()	Unknown
 	WAR.exe!009979d1()	Unknown
 	WAR.exe!008ed7d0()	Unknown
 	WAR.exe!0040789a()	Unknown
 	WAR.exe!00407744()	Unknown
 	WAR.exe!004033c5()	Unknown
 	WAR.exe!0067bab1()	Unknown
 	WAR.exe!008ed7d0()	Unknown
 	WAR.exe!0040789a()	Unknown
 	WAR.exe!008ed7d0()	Unknown
 	WAR.exe!0040789a()	Unknown
 	WAR.exe!005be2f1()	Unknown
 	WAR.exe!008ed7d0()	Unknown
 	WAR.exe!0040789a()	Unknown
 	WAR.exe!00407744()	Unknown
 	WAR.exe!0053cb54()	Unknown
 	WAR.exe!005d8a9b()	Unknown
 	WAR.exe!005bcc74()	Unknown
 	WAR.exe!005dc80c()	Unknown
 	WAR.exe!005ae270()	Unknown
 	WAR.exe!0041bc9e()	Unknown
 	WAR.exe!0088bc6d()	Unknown
 	WAR.exe!004176c2()	Unknown
 	WAR.exe!0041532b()	Unknown
 	WAR.exe!00406132()	Unknown
 	WAR.exe!004061c8()	Unknown
 	WAR.exe!0099b77b()	Unknown
 	[External Code]	

Doesn't seem to affect anything important.

**Comment by sioding** [comment]
Thanks for the report but sorry - this buftracker is only for ingame issues. Please use the forum for the client issues.
