### ISSUE TITLE
Annihilation - Epic Quest Chain / Duke Wickham

### ISSUE THREAD

**Issue by satexas69** [WarEmu/WarBugs#10811]
As of 11/10/2017, at 11:59pm, the final stage (Duke Wickham) is bugged.

When you go into the tower, and you go straight in to the back room, there's a wood door that's red and clickable, but no matter if you clear all the NPC's around it (even a few times, because they spawn fast)... the door can never been opened or entered.

Duke Wickham is unreachable and the quest unfinishable.

Stage Details & Descriptions Here:  https://wiki.returnofreckoning.com/index.php/Chaos_T4_Epic_Quest_Annihilation

**Comment by Lheana** [comment]
You have to finish the first stage of the PQ to be able to reach this NPC.

**Comment by satexas69** [comment]
Thank you. I would update the Wiki to cease any confusion. :)

---
Russ Bennett
World Net
210-226-6666

**Comment by Lheana** [comment]
Did it before posting here and closing the report ;)
