### ISSUE TITLE
Scenario weapons vendors

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#1081]
Corporal Keegan in War Quarter in Altdorf is supposed to be T2 scenario weapons vendor, but you can't trade with him. 
Chieftain Volor, Destro's T1 vendor, is missing entirely from Nordland and Inevitable City (he was present in IC before all vendors were removed and returned after the fix).
Herald Orelon, Destro's T2 vendor, exists in several instances:
1) In IC at the Apex - one instance at the southwest side of the pyramid.
2) In IC at the Apex - several overlapping instances at the northwest side of the pyramid.
3) In IC in Slaanesh's domain - inside of the wall.
Private Synna functions properly in Altdorf, however, the patchnotes say that "You find order t1 emblem vendor in t1 warcamps and Altdorf look for Private Synna", and she is not present in Nordland.

I have only checked the most likely locations, so any additions or clarifications are welcome.

**Comment by monstertheme** [comment]
So that's what everyone is talking about, no wonder Tier 2 games are so 1-sided this past week.

This should be #1 priority at this point since it would take 10 minutes to fix. @Evildoor @ozarmidrashim @MaxHayman @Milkyn @nalgol @DanaBloodkiss

**Comment by Evildoor** [comment]
13.08.2015 patch: Corporal Keegan fixed, Herald Orelon removed from all 3 places (?), Chieftain Volor added to the Apex and to Nordland warcamp, Private Synna added to Nordland warcamp.

**Comment by monstertheme** [comment]
Awesome

**Comment by Evildoor** [comment]
Update: Herald Orelon (single instance) returned to the Apex, but does not shows on the minimap and you can't trade with him.

**Comment by ozarmidrashim** [comment]
Server probably needs a restart to link the vendor with him.

**Comment by Evildoor** [comment]
Update: Orelon works, but is also titled "Merchant". Anyway, closing this, minor bugs are not so much of a problem.
