### ISSUE TITLE
Witch Elf starts with 1 point on Treachery SkillTree

### ISSUE THREAD

**Issue by Daenar7** [WarEmu/WarBugs#10816]
As title says, i've tried to respec and everything but the game calculates a single treachery point in any case. You can see my pg is lvl 20 with 5 points to spend as it should be, but one extra point still stays on the treachery path and it will be calculated if you spend any other point on this skill tree, so it is not just a graphic bug.
![myrvyn_014](https://user-images.githubusercontent.com/33597909/32699158-5904fedc-c7b1-11e7-85a9-b24e4ff91b24.jpg)

P.S: didn't find any topics about this bug or similar.

**Comment by Nfkillz** [comment]
probably you have set bonus that gives +1 point to treachery tree

**Comment by Daenar7** [comment]
Oh god, totally forgot about that. Sorry for my newbiness.
