### ISSUE TITLE
Genesis vendor - Tank - Undying incorrect token listing

### ISSUE THREAD

**Issue by SunsetCNTK** [WarEmu/WarBugs#10829]
This Set has incorrect tokens set as the price, and as such Cloak is listed for aspect token / Remnant for fragment token / Aspect for shard token / Fragment for Cloak token / Shard for Remnant token

They are buyable with listed token so it is not  only visual bug.
![untitled](https://user-images.githubusercontent.com/16652212/32808105-4f1081de-c992-11e7-8a4a-091666c112c3.png)
![untitled2](https://user-images.githubusercontent.com/16652212/32808107-4f3de732-c992-11e7-9b96-c9a1abdd0ab8.png)
![untitled3](https://user-images.githubusercontent.com/16652212/32808109-4f622e3a-c992-11e7-84f9-5c89da47d6e8.png)
![untitled4](https://user-images.githubusercontent.com/16652212/32808111-4fbd5788-c992-11e7-97c2-07766da73ea4.png)
![untitled5](https://user-images.githubusercontent.com/16652212/32808112-4fdeec54-c992-11e7-8315-ed88d0381db5.png)

**Comment by sioding** [comment]
Fixed with patch from 17.11.2017
