### ISSUE TITLE
Buying Multiple Emblem items which are not usable results in items not being purchased but emblems being removed anyway

### ISSUE THREAD

**Issue by erotalr** [WarEmu/WarBugs#10821]
To reproduce:

1. Shift right click an item not usable by your class from the emblem quartermaster
2. Select multiple quantities (I did with 10)
3. When prompted that you will never be able to use, click yes
4. Items will not be added to your backpack, emblems will be removed

Lost several 100 emblems before I realized what was happening

Note: Haven't tested if this is the same with items for your class that you can't use yet (too low level, RR etc)

**Comment by sioding** [comment]
#8174
