### ISSUE TITLE
Mage Bolt Tier 1 morale bug

### ISSUE THREAD

**Issue by HKMFNADO** [WarEmu/WarBugs#10820]
The tier 1 morale ability ''Mage Bolt'' keeps being disrupted, I have been monitoring this issue for about a week or so. I have noticed that on my melee classes the Tier 1 morale never gets parried/dodged/blocked but the Bright Wizard one gets disrupted and very oftenly.

I don't think this was intended. 

Hope it helps 

~HK

**Comment by sioding** [comment]
Thanks for the report. Can we please have Screenshots with your combat log?

**Comment by sioding** [comment]
No combat log - sad one....
