### ISSUE TITLE
Lair Boss loot missing - full inventory

### ISSUE THREAD

**Issue by W00Di3** [WarEmu/WarBugs#10823]
Looted items disappearing if inventory was full at the moment.
Character name: Dunbalf 
Class: Iron Breaker
Item: Greathelm of the Bandit Queen (IB)
[bugreport.zip](https://github.com/WarEmu/WarBugs/files/1466476/bugreport.zip)

**Comment by sioding** [comment]
Thanks for the report but we do not recover missing items. Please make sure you have enough free slots in your inventory.
