### ISSUE TITLE
Quest: Misled in Norsca bugged

### ISSUE THREAD

**Issue by LuckyRaider** [WarEmu/WarBugs#10827]
Step talisman smashing bugged.
Altar isn't clickable. Relog doesn't work.

**Comment by almeric13** [comment]
I found the quest is to destroy the talisman by clicking on the quest item. The bug is still there because the quest item is missing.

**Comment by LeonVic** [comment]
Starting this step, npc dont give the quest item necessary to do that quest. 
I've try to click at the altar, but isn't possible,
I've check on my bag but nothing inside the quest item (see the Screenshot) 
Also i've try to complete the PQ, but nothing again.
Pls fix
![learco_023](https://user-images.githubusercontent.com/38075110/38982003-ff4ba31e-43c0-11e8-88eb-6c0a6dfe2e6f.jpg)

**Comment by sioding** [comment]
fixed with patch from 09.06.2018
