### ISSUE TITLE
Enraged Beating

### ISSUE THREAD

**Issue by Vular** [WarEmu/WarBugs#10825]
Enraged Beating was broken 2 days ago.  It was supposedly fixed.

It is broken again.  Same issue.

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format. 

You can help us by following these bugreport rules: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Vular** [comment]
I don't have any video evidence or screen shots.  I don't video record and screen shots won't show the issue.  The problem is that when you use Enraged Beating, it has a 3 second channel time, and this 3 second channel time is being interrupted by damage.  I experienced it in ORVR all night last night.  Caledor, Black Crag, and in every SC I joined.  The channel effect is being broken on damage.

**Comment by Torquemadra** [comment]
Im not seeing this, on live or dev, proof please

**Comment by sioding** [comment]
No proof since 14 days - close
