### ISSUE TITLE
Old mails after name change cannot be deleted

### ISSUE THREAD

**Issue by HKMFNADO** [WarEmu/WarBugs#10824]
As the title says, after undergoing a name change old mails directed to the previous name remain undeletable. When clicking ''Delete'' it displays the error message ''You have 0 unread messages in your inbox.'' but the messages remain.

Attached a SS -
https://imgur.com/a/I26VY

**Comment by Natherul** [comment]
a probable fix for this will come with next patch

**Comment by sioding** [comment]
fixed with patch from 31.03.2018
