### ISSUE TITLE
No bag after lock zone

### ISSUE THREAD

**Issue by nohh** [WarEmu/WarBugs#10828]
have to won blue bag, after roll timer ends I got a message:
![1](https://user-images.githubusercontent.com/19315739/32806221-d9739e7e-c99c-11e7-94a3-c55e82c69cba.gif)
and being ported to capital and did not receive a bag.

**Comment by Torquemadra** [comment]
wait for next server boot

**Comment by nohh** [comment]
got the bag after reboot
