### ISSUE TITLE
3 Buffs at once with Chosen

### ISSUE THREAD

**Issue by Penthactus** [WarEmu/WarBugs#10822]
Well, I found out that I can have 3 Buffs ("Dreadful Fear" "Corrupting Wrath" and "Discordant Instability"
at the same time. I looked at my stats and its effects were active for an hour or so. 

In the description a buff is supposed to last only 12 seconds when I activated another one or ended it.

Here is a screenshot: 

![penthactussoul_000](https://user-images.githubusercontent.com/33615953/32711658-57a66320-c840-11e7-9023-3bb9b64eb918.jpg)

**Comment by sioding** [comment]
Thats the way it works on this server. We are not able to change the tooltip informations until we have client control.
