### ISSUE TITLE
Holding Banner one handed.

### ISSUE THREAD

**Issue by Gluckma** [WarEmu/WarBugs#10834]
To hold the banner one handed you have to have the flag out then put one of your weapons or weapon into you bag then requip your weapon and after you click the standard again on hot bar to make it go away (Only Click once) Then you will have the flag in hand while being able to use all your abilities as if you didn't have the debuff of having the flag out. 

-Nolan

**Comment by sioding** [comment]
Standards aren´t really implemented yet. You can show them, but thats all.
