### ISSUE TITLE
Booted back to character select

### ISSUE THREAD

**Issue by Vylor** [WarEmu/WarBugs#1083]
Hi, 

Every time I try to select a character to hit play the loading screen comes up and loads for about a minute before inevitably putting me back on the character select screen. This is happening with all my characters no matter what map they are on.

**Comment by xyeppp** [comment]
Type in /stuck when at loading screen.

**Comment by Vylor** [comment]
Worked beautifully, thanks a lot.

**Comment by xyeppp** [comment]
Might want to mark this one as closed then, less work for people dealing with open bugs.
