### ISSUE TITLE
Contribute Breaker.

### ISSUE THREAD

**Issue by Gluckma** [WarEmu/WarBugs#10838]
Warning: This has only been tested on a black ork. 
Before the update I would place always in the top 24 on my Black Ork and it was bad to the point where I joined a RvR zone and placed 16th out of 50 for just doing it. 

Sorry I forget the buff name but the buff that restores AP for Black Orks has a cold down of one minute' if you are standing around or moving with your Warband (Best if near all party members) And place a buff you are building contribute where others were not. While people were standing on BO's if you spammed it you would build contribute more then those around you. 
Combined with Da' Strongest (I believe that's the one that boots str.)  It would proc more then once on a target' adding to the factor it buffs your team mates as well building more contribute with using AoE on top of it with a two hander you were hitting several enemies helping build contribute towards kills.

This was only tested once when new system came out and all I did was buff that entire time didn't even really attack anyone and got a blue bag. 

-Nolan

**Comment by sioding** [comment]
Thanks for the report but why do you think spamming an abilty at a BO would generate contribution? We haven´t until now and we will not release how contribution is being generated.

**Comment by Gluckma** [comment]
The forumla I've come up with insist of being the one to spawn ram as well combined with buffing your party and being at almost every BO take but for some odd reason if you mainly just buff over anything you'll get high contribute. When you're attacking or defending buffing over loads contribute. I haven't figured it out exactly but stacking the AP regen buff and Da' Strongest for it's multiple times it will proc adds a lot of contribute. You can't just stand at one BO either you have to follow your party and try to get the max amount of 5 extra people being buffed vs yourself where it doesn't build contribute as much. Also popping AP regen right before a fight and during them increases it more. 

(Just my observations though) 
My original forumala was be at every BO take and be the first one in zone also to be the one to spawn ram.  
But the buffing added on top of this got my crazy bag rolls where I went for example three RvR zones and got a purple, an orange and a blue at level 20 when all I spammed was the AP regen and didn't attack anything. I only added the extra buff Da' Strongest (What ever one gives you strength proc buff) to increase contribute even more. 

-Nolan

**Comment by sioding** [comment]
Sorry to destroy your thoughts - but we will not reveal how contribution is being generated. That includes also that i can´t say that this issue is an issue or that this is working as intended.
