### ISSUE TITLE
WL pets block mine of magus (probably because damage type of mine is aoe) and you cant stagger pet

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#10831]
https://monosnap.com/file/Q2oMk83imJRt9VpXPxVeUgoWv951Ff

**Comment by Torquemadra** [comment]
looking into it, thanks

**Comment by Nfkillz** [comment]
probably stagger of chosen...knock back of dok and some other control work same

**Comment by Nfkillz** [comment]
fixed
