### ISSUE TITLE
Reikland factory 

### ISSUE THREAD

**Issue by Lotsdawittaz** [WarEmu/WarBugs#10830]
Wanted to leave a scenario but could not get myself to the leaving point in reikland factory scenario. (Destruction side) Unfortunately, the screenshot isn't showing full perspective but there is no clear passway to the location from where you can leave the scenario.
![warhammer online age of reckoning screenshot 2017 11 15 - 08 50 06 23](https://user-images.githubusercontent.com/23447430/32821171-1f2d5e0a-c9e3-11e7-96f5-d102bf044e2f.png)

**Comment by Lotsdawittaz** [comment]
![warhammer online age of reckoning screenshot 2017 11 15 - 09 19 58 24](https://user-images.githubusercontent.com/23447430/32821976-57e7a972-c9e7-11e7-8f9c-a29ce08c992f.png)
Here is a new screenshot.

**Comment by sioding** [comment]
fixed with patch from 2.3.2018
