### ISSUE TITLE
Logrin's Forge: Infinite Falling Bug

### ISSUE THREAD

**Issue by Artorian-Runaan** [WarEmu/WarBugs#10839]
![ror infinite falling spot](https://user-images.githubusercontent.com/33736471/32921145-47e6402e-cae1-11e7-894c-b179e9831a88.png)
On the right side of the Order Starting Zone, when dropping down to the ground you can be stuck in an infinite-falling animation, which prevents you from logging out or exiting. I tried /stuck and /unstuck, but neither worked (though I'm unsure if those are commands). 

As part of the bug, you don't appear to be falling to other players, so I was reported as AFK. Unfortunately, I failed to screenshot the exact location, but the spot is right up against the left-side of the right drop down. You pretty much have to be pressed up against the er... battlement I guess I call the low-walls?

EDIT: I managed to get into Logrin's Forge again, here's the picture of the location. I was afraid to stand in the exact location, but it's essentially that spot, just a bit closer to the edge.

**Comment by sioding** [comment]
sorry not reqeoducable
