### ISSUE TITLE
Slayers Demise PQ.

### ISSUE THREAD

**Issue by Gluckma** [WarEmu/WarBugs#10835]
At this PQ if you AoE on the NPC's you will be able to kill them.

-Nolan

**Comment by sioding** [comment]
Screenshots... and please be more precise. NPC means what?

**Comment by Gluckma** [comment]
I shall make this a more detailed report in a few hours when I get home. 
Thank you for your reply and sorry again for lack of details. 
For now on they'll be professional reports.

As for the precise none player characters I am talking about are the slayers who are sitting at the camp at the PQ' the ones around the tents are the ones I am talking about. 

Will upload screenshots with cords later. 
Thank you again for replying.

-Nolan

**Comment by Razielhell** [comment]
#6953 Thanks for the report. Someone will fix it asap.
