### ISSUE TITLE
BO ticks when chickened. 

### ISSUE THREAD

**Issue by Drstrangeone** [WarEmu/WarBugs#10849]
I became chickened when we locked the Empire zone and I leveled to 16. I took a flight to Elf and teleported to a BO. When I arrived I was able to receive the BO ticks. Not sure if this is a bug or intended.

**Comment by sioding** [comment]
thats ok - as a chicken you are a simple hit for someone. if you would like to get a 20 rp tick and being killed 20 time for trying it would be fine.
