### ISSUE TITLE
PQ Dragon Blessing / Dwarf Chapt. 17 / Thunder Mountain

### ISSUE THREAD

**Issue by Pumpgunpete** [WarEmu/WarBugs#10841]
Aloha Team ROR.

PQ Dragon Blessing / Dwarf Chapt. 17 / Thunder Mountain

Stage 1 - Destroy Dragon Bone. 
After destroying a Dragon Bone a mob named "Awakened Skeleton" appears which lvl is very low. 
Skeleton lvl.  is 16-17 only. TM is lvl rank 34-37.  Dunno if it is intend or just a wrong lvl? 

Many thanks
Cheers
PGP

**Comment by Lheana** [comment]
NPCs 'Awakened Skeleton' will no longer spawn when destroying GOs 'Dragon Bone'.

**Comment by sioding** [comment]
fixed with patch from 9.2.2018
