### ISSUE TITLE
Death Warden Bladebelt can't be assigned under appearance

### ISSUE THREAD

**Issue by Antalor** [WarEmu/WarBugs#10842]
![dd 1](https://user-images.githubusercontent.com/13917674/32960526-71e8f88c-cbc5-11e7-848f-31f834d642dd.jpg)

Good evening.
I tried to put it under appearance, but seems it doesn't work.
Greetings!

**Comment by NorKalli** [comment]
I think there's nothing that can be done, requesting permission to close @Lheana

**Comment by Lheana** [comment]
This should have been fixed with patch of 22/02/2020.
