### ISSUE TITLE
Able to use Guild Vault and personal Bank while in a Scenario

### ISSUE THREAD

**Issue by skavok** [WarEmu/WarBugs#10843]
Open the bank before taking Scenario. Once inside SC you can then withdraw or deposit items from your bank or guild vault.

**Comment by skavok** [comment]
After further testing this leads to being able to access the guild vault or bank from anywhere so long as you dont close the window after coming out of a Scenario.

**Comment by sioding** [comment]
Fixed with patch from 24.03.2018
