### ISSUE TITLE
Witch Hunter Dragon Gun

### ISSUE THREAD

**Issue by Grious** [WarEmu/WarBugs#10848]
The Dragon Gun execution in the Path of Confession is applying the Knockdown from Pistol Whip even when not spec'd into Pistol Whip. Doesn't seem to happen 100% of the time and ignores Pistol Whips positional requirement.

**Comment by Torquemadra** [comment]
thats the carrier for vfx, working as intended as added the KD to primary target on dragon gun to mirror on your knees
