### ISSUE TITLE
NPC: Dregenis, Avelorn. Title: Void Walker. Is killable.

### ISSUE THREAD

**Issue by Gluckma** [WarEmu/WarBugs#10859]
You can kill Dregenis in Avelorn with AoE dmg. Normally you get "Void Walker," after right clicking him. 
Cords: 44k, 44k.

-Nolan

**Comment by Lheana** [comment]
As Order and Destruction you can talk to him, and are meant to talk to him. He also correctly triggers his ToK unlock and his title. This NPC was like that on official: orange but both factions could talk to him. Can not change the way you can kill him with aoe, but players are not meant to try to kill him...
