### ISSUE TITLE
Broken bow model

### ISSUE THREAD

**Issue by Gargatyk** [WarEmu/WarBugs#1085]
Just saw a Squig Herder with broken (?) bow model, that looks like a red/yellow "standart" bow base model. 
Some other people mentioned it in the game and I saw this player several times in SCs so it's not just my vision. Can only say that this player's name is Gitgat.

**Comment by monstertheme** [comment]
Get a screenshot

**Comment by Reggaewaldo** [comment]
Verified. Changed the bow to feature a valid skin and to be usable by goblins only.

Closing.
