### ISSUE TITLE
.u command can be used to take no fall dmg.

### ISSUE THREAD

**Issue by Gluckma** [WarEmu/WarBugs#10858]
Using the .u mechanic allows you to take no fall dmg when using .u to jump off a bridge or a high height. 
What you need to do is face your back towards the area you want to jump towards then type .u causing your character to leap the rest of the way off the object but when you land on the ground you will take no fall dmg. 

I tested this in DW RvR on the bridges above BO Ember.

-Nolan

**Comment by sioding** [comment]
Tested on my own - not reproducable. Also the .unlock is limited to do once every 30 seconds.

**Comment by Gluckma** [comment]
I have screenshots if you want them on my end.

**Comment by Gluckma** [comment]
https://imgur.com/gallery/TsL6J 

Screenshots, with time stamp to show I didn't just run down the hills to bottom of bridge. And one Screenshot after using .u to take off from bridge.

**Comment by Gluckma** [comment]
Hey is this still going to be re-opened or for now will it be in the closed spot but be re-opened?

**Comment by Gluckma** [comment]
Hey is this still being reopened?
