### ISSUE TITLE
No roll and no bag after zone lock

### ISSUE THREAD

**Issue by Akirg** [WarEmu/WarBugs#10851]
Hello i was TP  from WC to MS when it's lock.
Before i participated to kill some player (valide in the kill quest) and make damage on the enemy keep lord.
![poupinette_003](https://user-images.githubusercontent.com/33703701/32978867-ce39435a-cc4a-11e7-863d-35c095686db6.jpg)

**Comment by sioding** [comment]
#10851

**Comment by sioding** [comment]
Duplicate of #10828
