### ISSUE TITLE
Magus Morale Four Fire Wyvern in the Demonology Tree not working.

### ISSUE THREAD

**Issue by Neutrinoo** [WarEmu/WarBugs#10854]
The Magus Morale Four Fire Wyvern in the Demonology Tree is not working.  I use to love to use it.  First it would be great to fix as it is, then if it can be improved I'd add the following abilities.

* Increase its overall damage so it is feared.
* Add aoe punt when it approaches to one or more targets.
* Add aoe knockdown when it dies.

**Comment by sioding** [comment]
Improvement is not part of the bugtracker.

**Comment by grunbag** [comment]
It’s fixed
