### ISSUE TITLE
Morale does not build fast enough to ever use M3 and M4

### ISSUE THREAD

**Issue by Neutrinoo** [WarEmu/WarBugs#10855]
There are very little situations in combat where morale can increase to any level so that one can use M3 and M4.  Only in situations with a morale pump tactic can one use M3 and M4.  It's simply too slow and wastes the use of any code related to these higher morales.

**Comment by sioding** [comment]
This is no bug report. If you want to improve morale gain use the balance forums: https://www.returnofreckoning.com/forum/viewforum.php?f=95 - and please make sure you follow the rules for a proposal.
