### ISSUE TITLE
Death Peak. NPC's at Destro Respawn. Killable by Order. 

### ISSUE THREAD

**Issue by Gluckma** [WarEmu/WarBugs#10868]
You guys should put guards for their spawn point at  cords: 10k, 18k. 

As Order you can go into their camp and kill their quest givers and healer. 

Confirmed: I just killed their healer and quest givers. Sorry was only testing it do not plan to abuse this.

-Nolan

**Comment by sioding** [comment]
Screenshots with a map showing where you standing would help a lot.

**Comment by Gluckma** [comment]
Kk. Will go back and take screen shots. I use Imgur if that's alright for screenshots.

**Comment by sioding** [comment]
would be great. thanks

**Comment by Gluckma** [comment]
It saying I have to wait 50 mins to post images to Imgur. Is there another way of posting screenshots?

**Comment by Lheana** [comment]
You should be able clicking on 'selecting them', on the message (Attack files by dragging & dropping, selecting them, or pasting from the clipboard') just below when you do a comment here.

**Comment by Gluckma** [comment]
Here's link for Screen Shots and thank you Lheana I will try that next time =)

**Comment by sioding** [comment]
Fixed with patch from 1.12.2017
