### ISSUE TITLE
PQ NPC are not available

### ISSUE THREAD

**Issue by Shmerrick** [WarEmu/WarBugs#10862]
PQ Not spawning mobs. Affecting the ability to complete elf epic quest.

https://imgur.com/a/v5Wo3

**Comment by Lheana** [comment]
Had the same problem with different PQs on dev server. It is not due to DB as it is well set. This issue is for Secrets I think ;)
If a GM uses the command .pq reset it should fix it.

**Comment by orderr** [comment]
still not working((

**Comment by TibbyB** [comment]
I can confirm. Photo took today on Blighted Isle ELF PQ T1 
![tiberiusultany_000](https://user-images.githubusercontent.com/32936075/36060454-aec5abe0-0e52-11e8-875a-e463debdc1af.jpg)

**Comment by Aduneth** [comment]
Griffon Gate is bugged. Can't progress through my epic delf t2 questline.

**Comment by Lheana** [comment]
This has been fixed with today's patch.
