### ISSUE TITLE
Barak Varr. NPC: Brakka champ 31. Killable for Order and believe he's part of a Destro Quest.

### ISSUE THREAD

**Issue by Gluckma** [WarEmu/WarBugs#10866]
Cords:10k, 52k. 

You can just run up and attack him.

-Nolan

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format. 

You can help us by following these bugreport rules: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Gluckma** [comment]
![nolan_045](https://user-images.githubusercontent.com/22874575/32990244-cef4cffc-cceb-11e7-8791-06a2bfbacffb.jpg)
![nolan_046](https://user-images.githubusercontent.com/22874575/32990249-dc0a5c34-cceb-11e7-982b-ff4370a20621.jpg)
![nolan_048](https://user-images.githubusercontent.com/22874575/32990251-e02330d4-cceb-11e7-92f9-7c51313b2c42.jpg)

**Comment by Gluckma** [comment]
The last Screen Shot on here you can see a little goblin standing on the road' you can kill him as well and he gives quests for Destro.

**Comment by sioding** [comment]
discussed that internally - its fine as it is. Even when a NPC is killable by the other faction and its part of a quest it will respawn.
