### ISSUE TITLE
Death Peak. NPC's: Lobber Gits. Don't attack Order unless attacked.

### ISSUE THREAD

**Issue by Gluckma** [WarEmu/WarBugs#10867]
Cords:3k, 25k. 

The Lobber Gits will not attack Order unless attacked.
Not sure if it's a bug or not but just thought I'd mention it. 

-Nolan

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format. 

You can help us by following these bugreport rules: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
