### ISSUE TITLE
Dwarf Chapter 14. Missing Basic Rewards from Inf PQ bar.

### ISSUE THREAD

**Issue by Gluckma** [WarEmu/WarBugs#10871]
As before title says issue. 

But Chapter 14 dwarf is missing basic rewards for Inf bar. 

-Nolan

**Comment by sioding** [comment]
Would you please stop you bugtracker hammering and follow the rules? As far as i see i can find this issue here again: #10008
Search before posting.

**Comment by Gluckma** [comment]
Sorry new to this. 
Will do in future! 
Didn't mean to bother anyone =(
