### ISSUE TITLE
[Tactic] "Accuracy" does not increase the distance of flurry

### ISSUE THREAD

**Issue by nohh** [WarEmu/WarBugs#10875]
Flurry is 25 feet distance:
![default](https://user-images.githubusercontent.com/19315739/32991373-3d896c8e-cd4b-11e7-90b7-36beb0bf4479.png)

Tactic "Accuracy" should increase distance to 30 feet
![default](https://user-images.githubusercontent.com/19315739/32991379-558b5a54-cd4b-11e7-9f61-6d0cd08fc37f.png)

But distance is equal in both cases.
Didnt tested with choppa maybe there is same problem.

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 20.04.2019

**Comment by sioding** [comment]
Fixed with patch from 27.04.2019
