### ISSUE TITLE
NPC Lucas Heimdell in High Pass

### ISSUE THREAD

**Issue by dwzimmer** [WarEmu/WarBugs#10878]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
NPC should be standing but he is laying on the ground twitching. The quest icon above his head is also orange as if the quest is complete when it's not complete yet.

Steps to reproduce the problem:
Start the Saving Souls quest and go talk to Lucas Heimdell.

Screenshots/Videos or archive.org evidences:
[https://plays.tv/video/5a11de508d49a5d8e1/lucas-heimdell-bug?from=user](url)

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
_The Quest:
Go to the Lake of the Damned and finish the work that Brothers Heimdell and Dangren started. While there, search for Lucas Heimdell and rescue him from torment._

Well - rescue him from torment. Thats why he is laying on the ground "twitching"
