### ISSUE TITLE
Barak Varr" Greenskin Chapter 5. Order can Kill flight master and quest givers.

### ISSUE THREAD

**Issue by Gluckma** [WarEmu/WarBugs#10874]
To do this you must Swim from the Light House BO in Barak Varr. Cords: 13k, 30k
![nolan_049](https://user-images.githubusercontent.com/22874575/32990385-4666c156-ccee-11e7-850e-92bc70f4d7d9.jpg)
This is where you start at to swim to chapter 5 (Picture above.) 
![nolan_050](https://user-images.githubusercontent.com/22874575/32990392-63511320-ccee-11e7-83f8-e759cb9d0eaf.jpg)
This is a picture of me pulling the Flight Master and advancing into Chapter 5. (Picture above)
![nolan_052](https://user-images.githubusercontent.com/22874575/32990406-7f8d9bd0-ccee-11e7-9452-d92aa0d6209c.jpg)
![nolan_053](https://user-images.githubusercontent.com/22874575/32990407-816d9450-ccee-11e7-90bb-117e40550612.jpg)
The final two screen shots are of me killing the flight master. 

The back of Chapter 5 from the sea has to many open points where you can pull flight master, quest givers to the shore and kill them without guards attacking you.

-Nolan

**Comment by sioding** [comment]
Fixed with patch from 1.12.2017
