### ISSUE TITLE
Troll Country: Way out of map.

### ISSUE THREAD

**Issue by Gluckma** [WarEmu/WarBugs#10882]
Cords: 5k, 8k.

![nolan_080](https://user-images.githubusercontent.com/22874575/33003558-0137b6c4-cd81-11e7-9681-be435ac6a9d8.jpg)
Location on Map to start. (Above)
![nolan_075](https://user-images.githubusercontent.com/22874575/33003508-c28315a4-cd80-11e7-8399-4156599d7769.jpg)
When you're on this rock you will see a slight slant in front of you on the same rock. It will seem like you're not going to make it. You will. 
![nolan_076](https://user-images.githubusercontent.com/22874575/33003515-c65745b0-cd80-11e7-89c2-f8966209f59c.jpg)
From this point you want to rotate your camera to face up the rock.
![nolan_077](https://user-images.githubusercontent.com/22874575/33003516-c6d30ccc-cd80-11e7-85d7-af6c3ae658be.jpg)
Once at the top of the rock you want to aim for the mountain side with the rock just before hand.
![nolan_078](https://user-images.githubusercontent.com/22874575/33003517-c8f58f20-cd80-11e7-881f-a3ce878ad756.jpg)
This is the end location of jump from other rock to mountain.
![nolan_079](https://user-images.githubusercontent.com/22874575/33003519-cb448d9e-cd80-11e7-9a1f-a1fc42aeeb25.jpg)
From this location you can turn around and go up the mountain that blocks the two tiers from meeting. 
![nolan_081](https://user-images.githubusercontent.com/22874575/33003691-e2c4e378-cd81-11e7-88ea-e7bcfce757ae.jpg)
Example of some of the stuff on mountain side.

-Nolan

**Comment by sioding** [comment]
We can not fix those things cause client based. Stop reporting those isuues.
