### ISSUE TITLE
Empire Start - Quest reward require renown

### ISSUE THREAD

**Issue by Niobandi** [WarEmu/WarBugs#10887]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Currently, some of the quests at the start of the Empire zone have reward gear with renown rank require.
This quest should give reward with no renown rank require.

Steps to reproduce the problem:
Take the quest at the Empire start zone.

Screenshots/Videos or archive.org evidences:
Quest : Hearts and Minds
![riseldia_000](https://user-images.githubusercontent.com/16079024/33038153-08928bac-ce34-11e7-9c5f-e2d9873dfbc7.jpg)
![riseldia_001](https://user-images.githubusercontent.com/16079024/33038154-08b07e82-ce34-11e7-8578-546cdb115bc5.jpg)

Quest : Return Fire
![riseldia_002](https://user-images.githubusercontent.com/16079024/33038157-08c9cb12-ce34-11e7-846d-e736d4dfd8e1.jpg)
![riseldia_003](https://user-images.githubusercontent.com/16079024/33038158-08e3b07c-ce34-11e7-9ca3-b035ad7fdca1.jpg)
![riseldia_004](https://user-images.githubusercontent.com/16079024/33038159-0900be1a-ce34-11e7-862e-002378fb0ef6.jpg)

Quest : Woebegone
![riseldia_005](https://user-images.githubusercontent.com/16079024/33038160-091b4762-ce34-11e7-9791-7a7e2954246d.jpg)

Quest : Amber Blossom
![riseldia_006](https://user-images.githubusercontent.com/16079024/33038161-093b5426-ce34-11e7-88ae-8de4fca09642.jpg)

Quest : Horrors of War
![riseldia_007](https://user-images.githubusercontent.com/16079024/33038163-095a8472-ce34-11e7-8d14-85aa8e0f0c34.jpg)

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by wargrimnir** [comment]
These were unused items that were added to the quests where previously there were no rewards (or worse rewards). Didn't notice they had RR reqs on them, but that's probably fine.

**Comment by Azyrian** [comment]
This issue is still present. Causes characters to lack gear improvements in early game.

**Comment by Lheana** [comment]
Checked and corrected the rewards of Empire Chapter 1 quests, everything is fine now.
