### ISSUE TITLE
Public Quest Loot Bag Missing Item (Labeled as "Auction Mail")

### ISSUE THREAD

**Issue by Rilof** [WarEmu/WarBugs#10886]
Hello Kind Sirs,

Today I received mail labeled as Auction Mail.  I opened it said I won a Public Quest but contained nothing.  

Before this issue occurred, I won a Green Loot Bag from a orvr T3.  I didn't receive the mail in 10min like most of the participants.  After about 3hours or so I received the mail, but I got a white bag instead.  I sent a CSR ticket about the item.  Then, I received the following issue described above.

See picture below:
![warhammer online age of reckoning screenshot 2017 11 20 - 20 42 54 08](https://user-images.githubusercontent.com/33287995/33021162-70fbc588-ce33-11e7-8b36-4df94cfadbca.png)

Thanks,
Rilof

Update,

About 2 hours later, my auction mail finally came.  See picture below.
![warhammer online age of reckoning screenshot 2017 11 20 - 22 11 20 96](https://user-images.githubusercontent.com/33287995/33025259-1242afc2-ce40-11e7-818e-4008e279fe2c.png)

**Comment by Natherul** [comment]
If this happens again reopen a ticket please but this is probably down to your object (player) was unable to be added to mail when it was sent (perhaps you where loading) and then it wont add to your character instantly but will instead be added once your object is reloaded by server.
