### ISSUE TITLE
Altdorf: Floating barrels that lead to seeing out of the map. Maybe a quest?

### ISSUE THREAD

**Issue by Gluckma** [WarEmu/WarBugs#10885]
Cords: 30k, 46k. 

![nolan_000](https://user-images.githubusercontent.com/22874575/33006292-71d95a96-cd8f-11e7-9b80-3c05495015eb.jpg)
![nolan_001](https://user-images.githubusercontent.com/22874575/33006299-7442f346-cd8f-11e7-8dbf-38d245c0fe71.jpg)
![nolan_002](https://user-images.githubusercontent.com/22874575/33006303-77175c9c-cd8f-11e7-8d0a-641910008b5d.jpg)

On the ledge there's a box called "Balthasar Gelts supplies." Maybe just remove floating barrels and place the box on the ground? 

-Nolan

**Comment by sioding** [comment]
Please stop that MAYBE reports - this is not a bug.
