### ISSUE TITLE
Norsca: Way out of map. 

### ISSUE THREAD

**Issue by Gluckma** [WarEmu/WarBugs#10881]
Cords: 61k, 63k.

![nolan_069](https://user-images.githubusercontent.com/22874575/33003145-71310726-cd7e-11e7-8990-1b5c3794cb18.jpg)
![nolan_070](https://user-images.githubusercontent.com/22874575/33003148-73c8d568-cd7e-11e7-93f9-6a399745a68e.jpg)
This is where you start. (Step 1)
![nolan_071](https://user-images.githubusercontent.com/22874575/33003149-741272e0-cd7e-11e7-8b5f-314b5b5c42e8.jpg)
Jump from Step 1 to where you see in photo (Step 2)
![nolan_072](https://user-images.githubusercontent.com/22874575/33003152-761b4bde-cd7e-11e7-8549-0be15408d633.jpg)
You leap from Step 2 and from this point it's as simple as facing up the hill and running forward.
![nolan_073](https://user-images.githubusercontent.com/22874575/33003227-013f5516-cd7f-11e7-839c-77791e17bf97.jpg)
You can continue left or go straight into unfinished area.

-Nolan

**Comment by sioding** [comment]
We can not fix those things cause client based. Stop reporting those isuues.
