### ISSUE TITLE
Damage to a T3 keep lord while bolstered. 

### ISSUE THREAD

**Issue by HKMFNADO** [WarEmu/WarBugs#10888]
While bolstered to lvl 40 in T4 Highpass all my skills did between 5-30dmg to the Hero with a high % of miss/dodge. This would be ''okeysh'' if there were alot of lvl 40 players to the fight, but if a full wb of lvl 16s would try to kill the keep lord it would take 2 days probably . So I am filing this under bug reports as it should definitely be addressed. The bolster should work with mobs aswell within the RvR lakes to allow low level players to not be utterly useless.

Screenshot of a combat log while beating the hero.

https://i.imgur.com/4u86FE4.jpg

**Comment by sioding** [comment]
Sorry - this is not bug at all. If you want to change the balancing your are welcome to create a post in here: https://www.returnofreckoning.com/forum/viewforum.php?f=95
