### ISSUE TITLE
Norsca: Screamer wrong tomb unlock.

### ISSUE THREAD

**Issue by Gluckma** [WarEmu/WarBugs#10884]
Cords: 30k, 10k. Just left of when you create a character on Destro. 

![nolan_030](https://user-images.githubusercontent.com/22874575/33005562-f85dd1ae-cd8b-11e7-8888-4fbf3077cd0a.jpg)
Screamer located just left of character creation spawn point for Destro. 
![nolan_031](https://user-images.githubusercontent.com/22874575/33005580-088601e6-cd8c-11e7-928d-cee7b385932a.jpg)
The tomb unlock for Screamer shows up as "Nomads."

-Nolan

**Comment by sioding** [comment]
According to the Wiki its fine as it is. Can we please have some evidence why you think its wrong?

**Comment by thorbolt80** [comment]
I think Nomads its a proximity unlock

**Comment by Gluckma** [comment]
Only bit of evidence I have is from other creatures I've killed giving wrong creature kills and unlocking wrong tomb unlocks. (Before I started taking screenshots) But I forgot about the Wiki and will check there first for Tomb Unlock because I lack the evidence other then my own opinion. 

-Nolan

**Comment by Lheana** [comment]
This Tom**e** Unlock works perfectly. Yes it is a proximity unlock but can also be triggered by talking to this screamer ([Proof](https://web.archive.org/web/20130502022449/http://warhammeronline.wikia.com/wiki/Norsca/History_%26_Lore)).
It is different to have a creature that triggers a Tom**e** Unlock like an Achievement or a History & Lore unlock, and to have a creature that does not count how it should. This screamer triggers the H&L unlock 'Nomads' (intended and was like that on official), and correctly counts as a Screamer of Tzeentch when killed.
