### ISSUE TITLE
Norsca: Killing all the starting Destro quest givers up to Cannon quest to kill dwarf choppa's.

### ISSUE THREAD

**Issue by Gluckma** [WarEmu/WarBugs#10883]
Cords: 37k, 11k. I'm just going to apologize now there's going to be so many screenshots.

![nolan_000](https://user-images.githubusercontent.com/22874575/33005187-60f8f218-cd8a-11e7-98d0-92dfe2607afb.jpg)
![nolan_006](https://user-images.githubusercontent.com/22874575/33005191-63cfbdb4-cd8a-11e7-89f0-bd57afc516ac.jpg)
Above is where you start. Then follow the rest of screenshots for the side of the hill to see the path to get up it. There are multiple ways you can climb this hill but I only chose one for an example.
![nolan_007](https://user-images.githubusercontent.com/22874575/33005197-6a66e7e2-cd8a-11e7-96f0-c96497c87327.jpg)
![nolan_008](https://user-images.githubusercontent.com/22874575/33005199-6ca543d2-cd8a-11e7-8263-e062473ce2ae.jpg)
![nolan_009](https://user-images.githubusercontent.com/22874575/33005201-6e074130-cd8a-11e7-9968-aaa6cf55650d.jpg)
![nolan_010](https://user-images.githubusercontent.com/22874575/33005204-6f8256bc-cd8a-11e7-8245-b5b02997f3c2.jpg)
![nolan_011](https://user-images.githubusercontent.com/22874575/33005206-70c6e16e-cd8a-11e7-8f4e-949ada459279.jpg)
![nolan_012](https://user-images.githubusercontent.com/22874575/33005207-71e0bffc-cd8a-11e7-916e-098d456dba2f.jpg)
![nolan_013](https://user-images.githubusercontent.com/22874575/33005212-73216920-cd8a-11e7-900d-aa5536c217c9.jpg)
![nolan_014](https://user-images.githubusercontent.com/22874575/33005216-77a540fc-cd8a-11e7-8607-0cc35c2d9e68.jpg)
![nolan_015](https://user-images.githubusercontent.com/22874575/33005217-7943859a-cd8a-11e7-8722-0e0ccac0f427.jpg)
![nolan_016](https://user-images.githubusercontent.com/22874575/33005220-7b27fbd4-cd8a-11e7-96bf-4593649b2b35.jpg)
![nolan_017](https://user-images.githubusercontent.com/22874575/33005222-7c7da89e-cd8a-11e7-88d4-f7b0b94b09f0.jpg)
![nolan_018](https://user-images.githubusercontent.com/22874575/33005225-80131336-cd8a-11e7-92ec-c542a4a66bba.jpg)
![nolan_019](https://user-images.githubusercontent.com/22874575/33005227-81479fec-cd8a-11e7-8a57-3fb4a67a5add.jpg)
![nolan_020](https://user-images.githubusercontent.com/22874575/33005229-827eaaea-cd8a-11e7-9e79-7f08dde0ca77.jpg)
![nolan_021](https://user-images.githubusercontent.com/22874575/33005230-83eed8b4-cd8a-11e7-8d1b-e290f7eebfc7.jpg)
Above you can see me killing the quest cannons for Destro.
![nolan_022](https://user-images.githubusercontent.com/22874575/33005231-85090116-cd8a-11e7-9910-9e6d9f12349c.jpg)
This is testing to see how close I could get without getting aggro from guards.
![nolan_023](https://user-images.githubusercontent.com/22874575/33005234-893fdae8-cd8a-11e7-8c45-fa073580cae7.jpg)
One good throwing axe later!
![nolan_024](https://user-images.githubusercontent.com/22874575/33005236-8ae80988-cd8a-11e7-9f48-5a97d06124ef.jpg)
Dead! Onto the next quest giver!
![nolan_025](https://user-images.githubusercontent.com/22874575/33005240-8c570666-cd8a-11e7-821d-a866955fed7e.jpg)
Didn't stand any chance... 
![nolan_026](https://user-images.githubusercontent.com/22874575/33005241-8e38ff7a-cd8a-11e7-9e79-5cd5d49e1f0a.jpg)
Guards need to be placed at that entrance or bottom of hill. 
![nolan_027](https://user-images.githubusercontent.com/22874575/33005243-8fe7b3e8-cd8a-11e7-900d-b8a59a8a0a8b.jpg)
![nolan_028](https://user-images.githubusercontent.com/22874575/33005244-911840de-cd8a-11e7-8160-18a21261b48b.jpg)
Got another quest giver!
![nolan_029](https://user-images.githubusercontent.com/22874575/33005246-930d277e-cd8a-11e7-9609-d8b2d79e967f.jpg)
A guard could be placed here as well because this path is the only thing that allows you to get over to other quest givers. (Spawning point of character creation)
![nolan_032](https://user-images.githubusercontent.com/22874575/33005250-949c083a-cd8a-11e7-8592-0f88962ee413.jpg)
Got another quest giver! Take that Destro! Just kidding.
![nolan_034](https://user-images.githubusercontent.com/22874575/33005254-9804ceee-cd8a-11e7-8b55-5bc9c3f12608.jpg)
You looking at me funny Quest giver? 
![nolan_035](https://user-images.githubusercontent.com/22874575/33005257-9a915600-cd8a-11e7-81f5-132dd4466d61.jpg)
That's what I thought... You couldn't handle the Mohawk! 

(Tried to make it at least entertaining to go through this one..... So many screenshots...)

-Nolan just your friendly hood Slayer that likes finding bugs!

**Comment by sioding** [comment]
OK Nolan,

this doesn´t mean finding bugs. You are using a level 40 char go to the startpoint of the other faction and kill the questgivers. Stop doing those things right now. It´s not OK. You have to follow the rules as any other player. I am not a GM but i  think killing the destro quest giver is a disruptive behaviour. 

Just because you didn´t got killed by a lvl 55 champion doesn´t mean its either a bug or OK.

Again: Stop it.
