### ISSUE TITLE
Norsca: Two out of place Destro Raven War Breakers. 

### ISSUE THREAD

**Issue by Gluckma** [WarEmu/WarBugs#10880]
I understand that these Raven War Breakers are use to help protect camps or areas for Destro from Order or to help them if they're going to die but the issue with these two Raven War Breakers is that they're in the middle of no where and aren't use full at all and if they're there to prevent order from jumping down to get into Chapter 1, chapter 2 area from Chapter 4 Order then there should be more placed because all you have to do is go a little bit  to the side of them and you can jump down and they're just standing there aimlessly. 

Cords:44k, 25k. 

![nolan_064](https://user-images.githubusercontent.com/22874575/33002658-26fc1450-cd7b-11e7-9993-79656e5a8cc9.jpg)
![nolan_065](https://user-images.githubusercontent.com/22874575/33002660-32717fb4-cd7b-11e7-907e-ff30b578d7bb.jpg)
![nolan_066](https://user-images.githubusercontent.com/22874575/33002665-354a66ce-cd7b-11e7-9d3c-c9b19daa97dd.jpg)

![nolan_067](https://user-images.githubusercontent.com/22874575/33002711-7836e1e2-cd7b-11e7-8b81-fb7e9037b230.jpg)

-Nolan

**Comment by sioding** [comment]
Stop with your desruptive behaviour. It´s ok to farm influence with your level40 char on your side of norsca but there is no need to go to the destruction side. BTW is it not your job to find ways - we know you can but you are now allowd to cause uf this rule:

* First and foremost: Don't Be A ****. This means no flaming, no trolling, no disruptive behaviour, and showing respect to other players and the staff.

https://www.returnofreckoning.com/forum/viewtopic.php?f=2&t=13607

Stop it NOW
