### ISSUE TITLE
Binding point 'Bohsenfels' has wrong arrival point

### ISSUE THREAD

**Issue by Ryanfawkez** [WarEmu/WarBugs#1088]
Using your BoB to Empire Ch8 Bohsenfels places you at 36k, 25k, while you should be appearing at 32k, 26k.

**Comment by bumik94** [comment]
It would be nice to at least delete that one bat that attacks you right after arrival.

**Comment by Reggaewaldo** [comment]
This has been fixed so that you will end up in front of the Rally Master. The change has been added to the DB and will roll over with the next hotfix.

Closing.
