### ISSUE TITLE
Disallowed Renown? (Keep Take)

### ISSUE THREAD

**Issue by Stophy22** [WarEmu/WarBugs#10890]
So I must be one unlucky son of a b!tch, haha. I was in Chaos Wastes this morning (Tue, Nov 21st) when we capped the keep in Chaos Wastes and I got a chat message that said, "You somehow gained an amount of renown larger than the system allows (54420). This gain has been prevented."

So I don't know if I got ripped out of my renown or what but I was a low renown rank and was in the zone for some considerable time. Screenshots below provided of course. 
https://imgur.com/a/nwl8w <-(if this doesn't work I attached them as well)

![disallowwar](https://user-images.githubusercontent.com/23489906/33097531-bee9277e-cec7-11e7-949a-a45073c97233.PNG)
![keeplockrewards](https://user-images.githubusercontent.com/23489906/33097535-c225bd1c-cec7-11e7-99fe-411ac298be95.PNG)
![zonelockreward](https://user-images.githubusercontent.com/23489906/33097541-c51afaf0-cec7-11e7-8d64-b42d407b1f6d.PNG)

 The one with Black pen Is my gain of renown from the zone lock, Blue pen represents the keep locks rewards (no renown given) and the red pen is the message. I'd like to note that the exp and inf I got was correct and the renown I was prevented to obtain was the only problem.
**Side Notes:**
-I was in Praag a few hours before and I don't recall ever seeing a message like that but we didn't cap a keep in praag.
-I was in the zone Chaos Wastes from start to finish so I should have gotten a lot of renown for that keep take 9999 renown was what I was awarded for the zone lock, but the keep take gave me 0.
-I renown ranked up in Praag on an unsuccessful zone take from: I want to say rr18-23/24 so only getting 1-2 ranks in chaos wastes on a success zone take seem odd, although I did get a lot of deathblows in praag.

Anyway hope this is all a misunderstanding with the system and me but if it isn't I don't know if my heart can handle the bad news. Thanks in advance.

**Comment by sioding** [comment]
Fixed with Patch from 25.11.2017
