### ISSUE TITLE
Enemy Addon in Warband

### ISSUE THREAD

**Issue by dansarii** [WarEmu/WarBugs#10896]
Expected behavior:
Enemy party icons should show updating health bars and light up icons when they are in your proximity. These party icons should also update on your map.

Actual behavior:
Enemy party icons are not updating health bars, nor lighting up the icons when they are in your proximity. This only occurs in warbands within groups that are not full (6 members). As soon as 6 members fill the warband group, the bug goes away. Party icons do not update on the map continuously until the warband group as six members.

Steps to reproduce the problem:
Create a warband with two or more people, but less than six. Note health bars or proximity of the party units.

**Comment by sioding** [comment]
Thanks for the report, but we do not support addons. Maybe you can get help in our forums: https://www.returnofreckoning.com/forum/viewforum.php?f=66
