### ISSUE TITLE
Cant join a scenario

### ISSUE THREAD

**Issue by hutzufh** [WarEmu/WarBugs#10907]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
No Info´s - close
