### ISSUE TITLE
Public Quest - Nurenmir's Lancers

### ISSUE THREAD

**Issue by Niobandi** [WarEmu/WarBugs#10908]
The Order Public Quest " Nurenmir's Lancers " in Ostland isn't showing and don't work.

![riseldia_013](https://user-images.githubusercontent.com/16079024/33229785-e0910ade-d1d5-11e7-887a-664474ba2cb9.jpg)

**Comment by Lheana** [comment]
Not a permanent bug, thus not DB related.

**Comment by Lheana** [comment]
#10498
