### ISSUE TITLE
Snizzort

### ISSUE THREAD

**Issue by Hattiro** [WarEmu/WarBugs#10904]
Hi , i have the problem when i heal with my dok at Snizzort Dungeon, everytime he goes under 50% i have an run time error. Any one else have the same?
![snizzort](https://user-images.githubusercontent.com/33959832/33213288-43bab5a6-d127-11e7-9d71-35b3acba0110.jpg)

**Comment by sioding** [comment]
Sorry we can not help here with client issues. This bugtracker is only for ingame bugs. Maybe you can get help here: https://www.returnofreckoning.com/forum/viewforum.php?f=5
