### ISSUE TITLE
Icon of Entropy without Soul Essence regeneration

### ISSUE THREAD

**Issue by Toppitop** [WarEmu/WarBugs#10903]
![pokuri_000](https://user-images.githubusercontent.com/33959177/33212450-a61ec254-d13c-11e7-969c-6e30d4ab0081.jpg)
have no soul essence regeneration in charm

**Comment by Toppitop** [comment]
![ugik_002](https://user-images.githubusercontent.com/33959177/33223786-831191c0-d17c-11e7-8395-1ca57e9c86c7.jpg)
sword reward for WE, not dagger :)

**Comment by sioding** [comment]
fixed with patch from 09.03.2018

**Comment by Firzum** [comment]
Hello

This fix is not solving the issue, I got exactly the same bug, not regen.

Regards
