### ISSUE TITLE
Public Quest - Ulfenwyr

### ISSUE THREAD

**Issue by Niobandi** [WarEmu/WarBugs#10902]
The Order Public Quest " Ulfenwyr " in Norsca have his npc fighting each other in stage 2 and stage 3.

![riseldia_010](https://user-images.githubusercontent.com/16079024/33182590-ef10e154-d074-11e7-886c-70295556fd42.jpg)

![riseldia_011](https://user-images.githubusercontent.com/16079024/33182592-ef371d9c-d074-11e7-9548-a7097ac2c0c2.jpg)

**Comment by sioding** [comment]
Fixed with patch from 29.12.2017
