### ISSUE TITLE
Sticky Feetz is the newest WH ability

### ISSUE THREAD

**Issue by TheSockPuppet** [WarEmu/WarBugs#10910]
No idea how it happened, the ability just appeared on my abilities when i dinged and i didn't even notice it until i opened them to check something irrelevant. I tested it and the snare part is functioning (no idea about the elemental resist shave), it has no cooldown or AP cost and the "booger" animation seems to be permanent, also, i don't enter combat when i cast it and the mobs don't be seem to be aggroed by it either (but they are still snared), it also seems to scale with my level.

![image](https://user-images.githubusercontent.com/25719734/33231189-b4114fae-d1f9-11e7-859c-bdbacbfa5708.png)

![image](https://user-images.githubusercontent.com/25719734/33231228-53334c72-d1fa-11e7-89bf-db8b88d9539a.png)

![image](https://user-images.githubusercontent.com/25719734/33231256-a79c632a-d1fa-11e7-9a14-d17ad935391e.png)
 
![image](https://user-images.githubusercontent.com/25719734/33231278-e22d73f8-d1fa-11e7-80c1-7060fc584382.png)

**Comment by sioding** [comment]
Fixed with patch from 1.12.2017
