### ISSUE TITLE
Slayer Quest Reward

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#10918]
Slayer quest rewards for quests Woebegone and Amber Blossom (empire chapter 1) got skins unique for hammerer class
![sheykis_074](https://user-images.githubusercontent.com/18032193/33270369-1c9e41fe-d384-11e7-88da-fbd967c5eda4.jpg)
![sheykis_075](https://user-images.githubusercontent.com/18032193/33270370-1cbeb8e4-d384-11e7-8f79-6ae731a5f55f.jpg)

**Comment by sioding** [comment]
Hooray - a slayer which is not half naked

**Comment by szejoza** [comment]
seems like you fixed it recently cause as of now they got regular looks of some of t1 items
