### ISSUE TITLE
Squigherder T2 influence items

### ISSUE THREAD

**Issue by AlistaireCrowley** [WarEmu/WarBugs#1091]
When you leave a SC with a pet up. And the que again and join a new sc and try summon same pet u cant. It say ability is not ready. Not a game breaking bug but still a bug.

SH T2 rvr inf reward medal have wrong stats. 12 wounds/ 6 initiative. Should be 12 ballistics. Sry if this have been reported Before. 

Best regards

**Comment by murmelon** [comment]
![stats](https://cloud.githubusercontent.com/assets/12655727/9290055/3158fb96-438c-11e5-8287-b4f9735a8cb9.jpg)

**Comment by AlistaireCrowley** [comment]
Thank you very much Murmelon!

**Comment by Evildoor** [comment]
Next time - one report per problem, please.
#2069 will be used as a report for the first problem.
Jewel was fixed as suggested here, Chewtop was not.

**Comment by saupreusse** [comment]
Fixed these two items.
