### ISSUE TITLE
"Priesterstadt Twanga" has a stabba model for Squig Herder

### ISSUE THREAD

**Issue by Greatgloin** [WarEmu/WarBugs#10913]
The 'Priesterstadt Twanga' bow is a spear, in its appearance, and the animations don't work while it's being used. I got the weapon from a quest, I believe, but I forget which quest it came from (it's possible it was a simple drop from a mob, I don't remember). I've been using it for a few days.

No animation present with this screenshot, and the weapon is also equipped in the wrong hand.
![greatgloin_078](https://user-images.githubusercontent.com/33998186/33238422-b531df42-d24a-11e7-90a1-43222f56ebe4.jpg)

My character animations are not bugged, as shown with a proper weapon:
![greatgloin_079](https://user-images.githubusercontent.com/33998186/33238418-a36d2884-d24a-11e7-935b-2933cca6b3e3.jpg)

![greatgloin_077](https://user-images.githubusercontent.com/33998186/33238442-ee8e09aa-d24a-11e7-9b33-1788b825d839.jpg)

When both weapons are sheathed, they are placed in the same position, instead of the bow being placed perpendicular to the spear:
![greatgloin_076](https://user-images.githubusercontent.com/33998186/33238445-161b5504-d24b-11e7-8e67-6e30bab7ffb9.jpg)

![greatgloin_075](https://user-images.githubusercontent.com/33998186/33238448-1ddb4150-d24b-11e7-91f6-d3379c229bd6.jpg)

![greatgloin_074](https://user-images.githubusercontent.com/33998186/33238449-2287a9aa-d24b-11e7-8285-5b54f5352f84.jpg)

**Comment by Torquemadra** [comment]
thanks

**Comment by sioding** [comment]
Fixed with patch from 1.12.2017
