### ISSUE TITLE
no interface

### ISSUE THREAD

**Issue by Moelmes** [WarEmu/WarBugs#10916]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*
hey is disable all my addons and my interface just got away i cant even go to esc menu

Expected behavior and actual behavior:
i wanted to enable miracle addon

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![ledude_001](https://user-images.githubusercontent.com/34013647/33246009-f3370950-d30f-11e7-906d-e782ceab5569.jpg)

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Did you tried to remove the MGRemix Addon and restart the client? Sorry but this is not the place for problems with addons cause we do not support them here. Please try to use the forum for those things.
