### ISSUE TITLE
Not receiving XP after praag lock.

### ISSUE THREAD

**Issue by HKMFNADO** [WarEmu/WarBugs#10925]
Been fighting for 4h in Praag, when the lock happened I only got RR and Infamy tick but the XP one, I have a tab for RR/XP/Inf as shown in the screenshot. I was told to bug track it. 

Screenshot:
https://i.imgur.com/4dZuCpJ.jpg

**Comment by jundii** [comment]
I am able to reproduce this issue currently. Playing the last two days on a witch elf around level 19-21... Each time the zone flips (destro success) I get the following message... "You somehow gained an amount of xp larger than the system allows (x). This gain has been prevented." (I have very similar screenshots as the OP).

2/1/2018 @ 10:52:15 EST... blocked what I assume was 102,772. Was not at BO when zone locked. Level 19, no rested xp. Lots of time having fun in zone. ~25k renown gained from flip. Solo when zone flipped as well.

2/2/2018 @ 1:53:33.... blocked what I assume is 90,393 xp from all day night working in DW. I was at BO when zone flipped. Level 21, no rested xp... ~22k renown. In warband when zone flipped.

Is there any other information I can be giving about this?

**Comment by jundii** [comment]
Update: so after a few failed hours in Eataine (2/2/2018 @ 6:12:49 AM EST) I was grinding PvE when zone flipped (not in Eataine)... I received XP for this flip.

**Comment by Oberheim** [comment]
I also encountered this today after fighting the entire morning in Dragonwake. I have attached a screenshot of the message.

![offerheim_004](https://user-images.githubusercontent.com/1072548/36425053-ce95e4e4-1645-11e8-96a2-bb6c59426c7a.jpg)
