### ISSUE TITLE
Potent Rejuvenating draught: Missing Tool tip information

### ISSUE THREAD

**Issue by Lokenoth** [WarEmu/WarBugs#10923]
As the title says, the potion is missing its tool tip information, I actually wound up using one thinking that because it was missing the tooltip info it probably because it wasn't implemented. Turns out I just wasted a potion! Woops.
![lokrin_150](https://user-images.githubusercontent.com/17035321/33342913-845a7af4-d47b-11e7-88b8-5a5e02b9e1f0.jpg)

**Comment by thorbolt80** [comment]
It's implemented. The staff knows the issue.

**Comment by Kaelang** [comment]
Fixed. 
![image](https://user-images.githubusercontent.com/60117106/82151964-4296a600-9856-11ea-918d-077c017e91b2.png)
