### ISSUE TITLE
Number of skillpoints for renown rank are wrong

### ISSUE THREAD

**Issue by Alaera** [WarEmu/WarBugs#10922]
Hi there,
I got a problem with my renown rank abilities. I only can spend with all my characters sill Point for renown abilities equal to my character Level and not equal to the renown rank.
For example: My KOTBS is lvl. 29 and has rr34 - I can only spend 29 skillpoints for renown abilites. Of course I have tried to spend the Points new by clicking the refresh button - did not worked. Also I have tried if this only is a visiual bug but I am not allowed to spend more points then 29. 
Thanks for your help!

**Comment by sioding** [comment]
If that would be true all user >rr40 and lvl 40 would create tickets or forum threads. If thats something which only affects you we definily more information what are you exactly doing. Did a relog fixed that? How do you respec? Are you using addons like the anywhere trainer ....

**Comment by Alaera** [comment]
I am wondering myself about this bug. I am using the renown Trainer just "normal" - I am choosing the renown skill, learning the skill and paying skill points for it.
The issue is that I only have 29 skill points to spend but it should be 34. I use the button "verlernen" (using the German Client) to unlearn my renown abilities. Also I have tried after unlearning to relog and to restart the whoe game. But every time the renown Trainer gives me only 29 skill points for renown abilities. Also I have tried the possibilty that this is maybe only a visual bug. But after 29 points are spent I am not able to spent more. 
I am using only add ons caring about guard but this problem occoured even before I implemented the add ons.

**Comment by sioding** [comment]
Can you please give us the character name?

**Comment by Alaera** [comment]
Hi there,
thank you very much for your Support.The character name is Alaera. The second name that you are able to generate with lvl 20 is Aretaquetta.She is a KotBS, lvl. 29, rr 34. Also I have attched a screenshot with the Interface of the renown Trainer at Sigmar temple.As you can see at the screenshot I am allowed to spend 29 Point for renown skills despite the fact that she has rr 34.
Again - thank you very much for your help and for realizing this great project.
Kind regards
Stephan 

    Sio <notifications@github.com> schrieb am 13:56 Dienstag, 28.November 2017:
 

 Can you please give us the character name?—

**Comment by Alaera** [comment]
I have also checked other characters of my account - they are affected, too.
Names are Seabharinn (Swordmaster, lvl. 14) or Valorean (White Lion, lvl. 4).

Thank you!

**Comment by szejoza** [comment]
Renown points available to spend are capped at your current character level if you are below level 40 I believe.
So at 29lvl, even if you have 50RR you still will be able to spend only 29 points

**Comment by Alaera** [comment]
Thank you for the advice!
Okay - I guessed this and asked fellows from my guild. They have characters under Level 40 but can spend they full rr rank for skill points. So - maybe my guild comrades told me nonses, maybe I am a total noob :) or maybe it is really a bug. We will see! 
Cheers

**Comment by sioding** [comment]
Thx @szejoza
