### ISSUE TITLE
Glue Potions are Spammable in PvE

### ISSUE THREAD

**Issue by gke96** [WarEmu/WarBugs#10920]
(lvl1 glue potions tested only)
https://youtu.be/Omo4sAMX4fY

**Comment by gke96** [comment]
+ I tried this in RvR now and it was working normally on 5 min cooldown

**Comment by gke96** [comment]
I don't know how I did that on the video, but I cant do it in PvE anymore either. Maybe there is a way to bug it? I have no idea. or dıd it get fixed already?

**Comment by Haojun-Phalanx** [comment]
maybe the same bug for bypass book of binding, guild scroll cooldowns ?

**Comment by Torquemadra** [comment]
i live fixed

**Comment by sioding** [comment]
Fixed with patch from 1.12.2017
