### ISSUE TITLE
Only half the dwarfs in the quest Raising Da banner" give credit.

### ISSUE THREAD

**Issue by Rufert** [WarEmu/WarBugs#10928]
The objective is to kill Grundadrakk Dwarfs. But only Grudgers give credit not Grudgehammers.

**Comment by sioding** [comment]
And the Quest said you have to kill what?

**Comment by Rufert** [comment]
Grundadrakk unless I'm blind. Both are prefixed with that.

**Comment by sioding** [comment]
Checked that and its fine. The Grudgehammer belongs to the Public Quest the others are also stand in. So its fine as it is.
