### ISSUE TITLE
Attack through keep door

### ISSUE THREAD

**Issue by mylesrangel** [WarEmu/WarBugs#10924]
As a BW I can cast dots through the keep door at the enemy ram/players. I was able to cast ignite and boiling blood through the door. I couldn't try an ability with a cast because they moved. I think I was in Thickmuck Pit in Badlands at the time.

It seemed to be an los issue. I tab targeted the ram and jumped around back and forth in front of the door and there was a sweet spot where I could cast. I was probably about 5 yards from the ram. Once the player or the ram moved I had to find the sweet spot again. 

I took screenshots of me casting through the door using the ingame screenshot system but it did not save to my folder.

**Comment by sioding** [comment]
Thanks for the report but this is way too vague to reproduce it. You "think" you were in Thickmuck and you say it seemed to be an issue. After all there are no screenshots. I believe you would like to report something important but how should we be able to reproduce it? Waiting at keep with ppl attacking it and trying to find your sweet spot? Sorry but i can not let this report open. If you find there spots again - please make sure you are able to be more specific and attach some screeshots.
