### ISSUE TITLE
Discordant Fluctuation and dots

### ISSUE THREAD

**Issue by Scrilian** [WarEmu/WarBugs#10921]
Chosen aura procs off disrupted dot tick, most likely because the aura reflect damage triggers prior the actual dot tick.
![dis](https://user-images.githubusercontent.com/16498708/33283519-233bf1c6-d3bd-11e7-94d0-86d2944052e4.jpg)
Probably the same issue with melee dots and kotbs On Your Guard! aura.
It should proc after the defense check, not prior to it.

**Comment by sioding** [comment]
We had a lot of discussions about that in already closed issues:
https://github.com/WarEmu/WarBugs/issues?q=is%3Aissue+Discordant+Fluctuation+is%3Aclosed

**Comment by Haojun-Phalanx** [comment]
Enemies dare to use offensive **magical abilities** agaist a groupmate in this radius will be hit with a magical backlash, causing them x spirit damage.

according the tooltip, for getting backlash,  successful hit not required. if you use magical ability on a target with DF aura, you got backlash.

after new dot changes, all dot ticks acting like a fresh new spell.

**Comment by Scrilian** [comment]
"Dare" in that case is nothing but a fluff text as chosen aura required actual hit to proc them.
Kotbs variant reads it more clearly - who strikes - and actual dot tic should not count as a separate spell/melee hit application post dot changes patch.

**Comment by Haojun-Phalanx** [comment]
well, the first attack always got a backlash even it defended or not. dot thing is completely new, make a proposal if you have a problem tho. nothing buggy here.

**Comment by sioding** [comment]
This is not the forum and you do not decide anything here @Haojun-Phalanx

**Comment by sioding** [comment]
See Patchnotes from 1.12.2017
