### ISSUE TITLE
"Rasing the Empire Banner" Order Quest.

### ISSUE THREAD

**Issue by Skalier** [WarEmu/WarBugs#10927]
This quest can't be finished because in Verentaines Tower are no guards, and that's why can't capture this BO and in effect can't get last Skaven Token for dog.

It's in High Pass, quest starts in Warcamp.

**Comment by sioding** [comment]
Patchnotes from 11.11.2017:
[10483] Quests 'Raising The Empire Banner' and 'Raise the Chaos Banner for Glory' are now fixed:
Destruction players will now have to click on the GameObject 'Chaos Banner' next to the Battlefield Objective Feiten's Lock.
Order players will now have to click on the GameObject 'Empire Banner' at the top of the Battlefield Objective Verentane's Tower.
