### ISSUE TITLE
40k + solider's Medallions in the bag

### ISSUE THREAD

**Issue by KovQ** [WarEmu/WarBugs#10936]
![20171201023740_1](https://user-images.githubusercontent.com/34159139/33479720-bf68bcbc-d653-11e7-9f7b-e09e649f5d8e.jpg)

Several solider's medallions appeared in my currency bag during a two hour long siege in Troll country/ Ostland ORvR. After we beat back the destro side from the keep in troll country, several of my random Warband members stated that they suddenly had over 20k or 30k medallions in their bags, after that I checked mine and I had several as well. This image was taken slightly later, as we were attacked at Ruins. I still gained some more afterwards but it seemed like a normal pace after we left the keep. I don't know how much I had at the beginning or during the siege but this is an image after it. My final count of medallions is: 47,932. This report is being made after the ORvR's completion.

**Comment by Natherul** [comment]
Implemented a hardlock in code for next patch and I have done some manual removal of medallions in the DB today.

**Comment by IDietrich** [comment]
issue looks to get back as i (and heard some other players in warband) got a huge amount of medallions for defeding a bo in chaos wastes. also got a huge amount of rr.
![flamerella_008](https://user-images.githubusercontent.com/34206979/35197856-289cf628-fef7-11e7-9ea9-c1a9d8dc7cc2.jpg)
