### ISSUE TITLE
Warrior Priest Prayers

### ISSUE THREAD

**Issue by JaegarMjolnir** [WarEmu/WarBugs#10932]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: If you go into an RVR area and get bolstered, you can activate your prayer and once you leave it retains the bolstered level. Tested with Absolution and the armor given was not just a visual bug. It reduced damage of enemies considerably.

Steps to reproduce the problem: Go into RVR, cast Prayer, leave RVR. 

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Natherul** [comment]
This will be fixed in the next patch, fix will be just like it was fixed with auras on kotbs and chosens

**Comment by sioding** [comment]
Fixed with patch from 1.12.2017
