### ISSUE TITLE
runtime error at BL Boss

### ISSUE THREAD

**Issue by Hattiro** [WarEmu/WarBugs#10930]
Hi now i have two BL Bosses with the same problem, the game make a runtime error. I`ve talk with an GM and they now about this. Any got a idea what i can do, to get this quest done? Happens at SNizzort and Khorgash.
greetings Yip
![snizzort](https://user-images.githubusercontent.com/33959832/33374821-f6d9bc0c-d507-11e7-8f9a-9a027596e6e0.jpg)

**Comment by sioding** [comment]
Duplicate of #10679
