### ISSUE TITLE
Squigs in Altdorf

### ISSUE THREAD

**Issue by Manatikik** [WarEmu/WarBugs#10938]
After the 12/1 patch there are two random squigs and a mushroom (assuming Gunbad assets) that shouldn't be there (to my knowledge).  By entrance to War Quarter from Lord's Row.

![squiginaltdorf](https://user-images.githubusercontent.com/19319894/33512337-93721a20-d6eb-11e7-8449-3869b283b4b9.png)

**Comment by Hargrim** [comment]
It's not a bug, squigs are everywhere!
