### ISSUE TITLE
A Portent of Triumph quest.

### ISSUE THREAD

**Issue by Zdaemon214** [WarEmu/WarBugs#10939]
Location 14.5k, 35.5k Wounded Unicorn gives quest. The objective in the quest tracker says Invalid Creature - Quest ID 36118, objid=40389 - 0/1. The objective of the quest is actually to kill the "Hungry Cold One".  The "Hungry Cold One" doesn't seem to spawn either.

**Comment by NorKalli** [comment]
Swapped to Hungry Manticore, placed mob

**Comment by sioding** [comment]
Fixed with patch from 02.06.20018
