### ISSUE TITLE
PQ t4 medium size gold bag 

### ISSUE THREAD

**Issue by Symbelmyne** [WarEmu/WarBugs#10942]
Gold bag t4 PQ medium size contains redeye set piece.

**Comment by eherenreich** [comment]
Drops gloves and boots - confirmed from PQ 15 in etaine.

**Comment by eherenreich** [comment]
After patch its been fixed - tried the same PQ 15 in Etaine and its now dropping ruin again :)

**Comment by sioding** [comment]
fixed with hotfix on 2.12.2017
