### ISSUE TITLE
Defendable Sever Blessing

### ISSUE THREAD

**Issue by tlitschye** [WarEmu/WarBugs#10949]
I heard some people talk about a recent fix where "SEVER BLESSING" would be undefendable.
If that is the case, it is still defendable.

![image](https://user-images.githubusercontent.com/20156460/33530214-c3eee4b6-d87c-11e7-91e1-98c273f2efc7.png)

Greets

**Comment by sioding** [comment]
Can we please have a combat log - not  a screenshot out of an addon? 

Patchnotes: https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=23117

* Witch Hunter and Witch Elf abilities Sever Blessing are now undefendable (This is ONLY WH/WE, the rest are defendable against as per live)

**Comment by kyranria** [comment]
https://imgur.com/bHgmAOP 28/10/17 on WH 100% parry

**Comment by tlitschye** [comment]
https://youtu.be/hABoMbxTZ2U

**Comment by Torquemadra** [comment]
Balance choice, core ability and first in line on NB string shouldnt trump a 10 point tree investment ability and turn its use into a free hit.

**Comment by tlitschye** [comment]
I do not talk about "Repel Blasphemy" i talk about "Sever Blessing" being defendable.... and i provided an evidence that it is. I do not talk about balance either. I will provide more evidence, that it also gets defended in other ocasions.
