### ISSUE TITLE
Out of Range bug after dismount

### ISSUE THREAD

**Issue by tlitschye** [WarEmu/WarBugs#10944]
Hey all,

since it is over 1 year that i know this bug and it did not even get touched, i post it.

Situation:
Enemy on 60% mount, any class
Me no mount, me as Witch Elf
1. I dismount the enemy with my opener, i can reach him perfectly with the opener, thats no problem at all.
2. EVERY following attack is OUT OF RANGE, even with a 30 ft OYK, it is not possible to hit the enemy
3. I trow daggers to slow the enemy
4. he is slowed
5. i catch up to his position
6. i get collision with this playermodel
7. i still CANT ATTACK HIM
8. i walk infront of him, still not possible
9. As soon as he stops walking away in a strait line or turn around i can SUDDENLY HIT HIM.

I know i heard aswers that this issue is serversided, but is it somehow possible to manipulate the positioncalculation after dismount from 60% mount?

This issue makes it possible for griefing player to just walk away in a strait line without a possibility to get hit.

Can you please try to fix this bug.

thank you

**Comment by Torquemadra** [comment]
you have any video?

**Comment by tlitschye** [comment]
i try to make one

**Comment by Kaelang** [comment]
Closed as dated and no confirmation was given when requested.
