### ISSUE TITLE
Chapter 5 Greenskin Easy PQ Firebeard's Slayers Stage 1

### ISSUE THREAD

**Issue by zibiman** [WarEmu/WarBugs#10943]
![ziehb_000](https://user-images.githubusercontent.com/16434526/33519905-144be734-d7b9-11e7-992e-8daaa1eb4edc.jpg)
*I need to destroy 10xPiles of Goods but is there are only 8 and thay dont respawn and the othere are on the Beach but the PQ area is only till the Road so i cant Destroy them.*

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:Black Area is PQ area and Red is the area with the Goods but arend inside PQ area
![ziehb_001](https://user-images.githubusercontent.com/16434526/33519903-084ae818-d7b9-11e7-92d1-dd12a89a92ca.jpg)

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Lheana** [comment]
Reduced the required number of destroyed GOs to the number of spawns of the GO inside the PQ.

**Comment by sioding** [comment]
Fixed with patch from 15.12.2017
