### ISSUE TITLE
Chosen can run multiple curse auras

### ISSUE THREAD

**Issue by wraithedge** [WarEmu/WarBugs#1094]
The text of the Chosen's curse aura states "This curse will last until another curse is activated or this one is toggled off. After this the curse will linger for another 12 seconds"

But the current behavior is that triggering a new curse does not cancel the previous and all curse auras possessed by the Chosen can be run with their all effects overlapping all the time.

The text leads me to believe that the intended model is a sort of twisting whereby the Chosen player must toggle them in sequence to have them overlap. 

![amrak_001](https://cloud.githubusercontent.com/assets/13814104/9291179/3476df10-4377-11e5-9fe8-0cbed1a22a27.jpg)

**Comment by xyeppp** [comment]
This was changed on RoR due to every competent Chosen/KoTBS running Twister anyways. 
You can have all 3 active at once. - to close.
