### ISSUE TITLE
Fighter's Axe of Vengeance for IB Appearance Issue

### ISSUE THREAD

**Issue by CountTalabecland** [WarEmu/WarBugs#10941]
I was attempting to use the appearance of this T1 1h axe on T4 one and got a message that the weapon was not of the same type and therefore the appearance cannot be used. This seems wrong because they are both dwarf 1h axes. Screenshot attached.
![brynnoth_044](https://user-images.githubusercontent.com/31392662/33517625-15000686-d74d-11e7-8520-aa6eb5948028.jpg)

**Comment by NorKalli** [comment]
long since fixed
