### ISSUE TITLE
inventory disfunction

### ISSUE THREAD

**Issue by esariobug** [WarEmu/WarBugs#10947]
Hi,
i'm in trouble with my inventory bag, can open it, but can't see the items.
All my caracters are in same situation.

Screenshots/Videos or archive.org evidences: https://1fichier.com/?dwty6b3hzn

**Comment by esariobug** [comment]
i tryed to create a new caracter and it work but not my old's

**Comment by sioding** [comment]
Are you sharing a profile? Have you tried to create a new one? Does this problem still occur?

**Comment by esariobug** [comment]
My main account is affected by this problem (all my caracters : order and chaos). The inventory is like on the screenshot for all of them. I have another account (yes, it's bad but...) and it was bugged too.
I'll tried my wife's account and it have no problem. (the same computer).
It appeared when i have my inventory open and the item menu from a PNJ too. I was AFK for few minutes and when i reloged... If i create a new caracter, the problem don't affect it...
(Sorry for my bad english...)

**Comment by sioding** [comment]
OK as fahr as i see its not an ingame bug -  cause your wife´s account is fine. I advise you to create a new profile. if that´s not working ask for help in our forum.
