### ISSUE TITLE
[extremely minor: Red Cold One] One of these things is not like the other.

### ISSUE THREAD

**Issue by Lokenoth** [WarEmu/WarBugs#10950]
Just spotted this, whilst rolling around The Undercroft. The red cold one pet on display has either grown up or his character model has been replaced. 

![lokrin_157](https://user-images.githubusercontent.com/17035321/33532574-ac1c5998-d892-11e7-8448-34d19b2e29f7.jpg)

**Comment by sioding** [comment]
fixed with patch from 8.12.2017
