### ISSUE TITLE
quest: taking the offensive

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#10959]
speaking to npc Lord Xyshrenth does not complete the quest.
![image](https://user-images.githubusercontent.com/17765890/33646951-a2f64c36-da52-11e7-93f7-12536d58bd40.png)

**Comment by zak68** [comment]
seems that the correct npc is located in Praag at Souther Breech warcamp
![gabri_203](https://user-images.githubusercontent.com/17765890/33652776-e5621d80-da6a-11e7-841b-25fe3950f015.jpg)

**Comment by Lheana** [comment]
These two NPCs were previously the same NPC, and I changed it for several reasons.
The quest will now complete when you talk to the correct 'Lord Xyshrenth', he is the quest finisher and will give the next quest. Also I removed the uncorrect quest marker for the Lord Xyshrenth in Praag.

**Comment by sioding** [comment]
fixed with patch from 8.12.2017
