### ISSUE TITLE
Witch Hunter KD

### ISSUE THREAD

**Issue by Padja** [WarEmu/WarBugs#10958]
Hello, 
Pajda here and i just wanna warm you that WH knockdown Pistol Whip is cleanseable by shammy. 
WEs KD cant be clease so far. Thx your Pajda.

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format. 

You can help us by following these bugreport rules: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Torquemadra** [comment]
its an ailment, ailments can be cleansed
