### ISSUE TITLE
Not in guild whilst in a guild 

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#10955]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

On several characters I'm no longer in my guild Nazgul. When I press G, it says I'm 1/1 in the Guild. The guild chat still works though and my guildies see me in the roster. But my roster is just 1/1 persons. On one alt I also lost my backpacks and all equipment. 

Steps to reproduce the problem:

-sometimes logging out of the game solves it. 

PS we did have the same issue with our guild last year. At one point everything got really messed up (guildies all of a sudden got rights to vault/gold/etc), if you were in the guild you could not login at all, etc.
I then completely deleted the guild Nazgul, and made a new one. But these symptoms I'm having now look a lot like we were having last year. 

Screenshots/Videos or archive.org evidences:

![clipboard01](https://user-images.githubusercontent.com/11788060/33560374-d8ebdfd4-d90f-11e7-93c6-0864aab3ae14.jpg)
![clipboard02](https://user-images.githubusercontent.com/11788060/33560375-d9095f00-d90f-11e7-92eb-bce52002ab97.jpg)

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
did you tried to leave/join the guild?

**Comment by wiscel** [comment]
Yes, didn't solve it :-/

**Comment by szejoza** [comment]
this is quite common occurence (at least for me :D), we had it in Bitterstone Thunderers for some time and doing /rel fixes it (at least until it happens again)

**Comment by wiscel** [comment]
Today it seems to be ok on all my alts. We'll see how it goes.
