### ISSUE TITLE
[Event: Huntin' for Shrooms]  This git won't eat his shrooms

### ISSUE THREAD

**Issue by Lokenoth** [WarEmu/WarBugs#10956]
Quest Hand in fails to work, and the quest log fails to track or display the quest objectives. 20 shrooms were asked for, 20 shrooms were collected. But the Growing Git won't complete the quest.  Registers as complete in the quest tracker. 

![lokrin_161](https://user-images.githubusercontent.com/17035321/33575318-19002a70-d934-11e7-9e00-6b4da5d6d67e.jpg)

**Comment by szejoza** [comment]
same for order counterpart [Gunbad] Mushroom Hunt
![shey_019](https://user-images.githubusercontent.com/18032193/33580796-cc754c6a-d94e-11e7-85d0-ae195c5d55b2.jpg)

**Comment by Ryanfawkez** [comment]
Should work for Order at the Explosives Engineer, Destro can hand it in at the Minin' Boy.

**Comment by szejoza** [comment]
Order version of that quest is working now (got no way of checking destro tho)

**Comment by sioding** [comment]
fixed with patch from 8.12.2017
