### ISSUE TITLE
quest: huntin' for shrooms

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#10952]
once in tok, quest reward seems missing.

![untitled](https://user-images.githubusercontent.com/17765890/33542030-9da965e2-d8d1-11e7-9da9-9add99e4f31f.jpg)

![image](https://user-images.githubusercontent.com/17765890/33542072-c3f4d808-d8d1-11e7-80c0-942021bcadb4.png)

**Comment by sioding** [comment]
Seems like you you are doing quests which aren´t really released - no gunbad atm.

**Comment by Lheana** [comment]
Not a bug. You see the red arrow at the right bottom of the right page? Click on it ;)

**Comment by zak68** [comment]
ouch!
