### ISSUE TITLE
MAJOR Issue, Altdorf causing CTD every time game loads.

### ISSUE THREAD

**Issue by Zdaemon214** [WarEmu/WarBugs#10951]
Any attempt to zone into Altdorf is causing the game to crash to the desktop, only solution is to type /stuck twice while in the loading screen to teleport to Norsca/Nordland. Also any char in Altdorf will crash to desktop any time the play button is pressed. Seems many people are affected, but not everyone. First logon to Altdorf parked toon was a success. Crash did not start until I left Altdorf and then tryed to return. 

      Turns out crashing can occur in the loading of any new zone, it isn't always permanent though, meaning crash may occur on new zone, but logging back in works and lets u into the zone.

**Comment by Bufitos** [comment]
that was next mesage when i try telport to aldorf and crashed game, next time loaded and used /stuck 2 times and was teleported DEAD ,,,-30.000 dmg on me... 
![bufitos_021](https://user-images.githubusercontent.com/23417736/33549678-a3d01370-d8eb-11e7-90d2-9b7b12cc9d9c.jpg)

**Comment by kam19080** [comment]
why u can type /stuck in loading screen....

i cant type

**Comment by kam19080** [comment]
O..i know type enter first..

**Comment by Lokenoth** [comment]
@kam19080 A loading screen is typically just a graphical overlay to stop you from seeing the zone your moving into get populated by objects, Functions such typing, and even in some cases abilities and targeting can still be used whilst loading into the zone.

**Comment by sioding** [comment]
Should have been fixed.
