### ISSUE TITLE
Neborhest Vanguard Stage III - Dwarf Chapter 9 Public Quest - Hero Issue

### ISSUE THREAD

**Issue by Rilof** [WarEmu/WarBugs#10967]
Haven't seen this part reported.

During Stage 3 of the quest.  I killed the hero but the stage didn't complete.  And the hero mob did not repawn either and the quest reset.  The dwarf npcs shot at the hero a little...maybe that was the issue?  But should the mob repawn?  Or not?

Anyways, I thought I should report this nonetheless.

Thanks,
Rilor

See pic below.

![desktop screenshot 2017 12 08 - 07 12 45 37](https://user-images.githubusercontent.com/33287995/33745306-a3c6fbb4-dbe8-11e7-890f-69fe39550e28.png)

**Comment by Lheana** [comment]
Dwarf NPCs will no longer attack the Hero.

**Comment by sioding** [comment]
Fixed with patch from 26.01.2017
