### ISSUE TITLE
critically heals

### ISSUE THREAD

**Issue by Bufitos** [WarEmu/WarBugs#10961]
criticall heals have random healing value? is not +50% ?
or si standart healing+ (40...-.....55) % ?
![bufitos_034](https://user-images.githubusercontent.com/23417736/33669120-df2e139c-daa1-11e7-8d0f-7f0a48590a06.jpg)

**Comment by sioding** [comment]
This is not the place for questions.  What bug would you like to report?

**Comment by Bufitos** [comment]
Error on critical healing skills .
Becouse is not standart healing value , how i mencion on first message.

**Comment by sioding** [comment]
Ah Thanks. Proof please.

**Comment by Tyramissoux** [comment]
No bug. Crits were always in a range of %-values on live, never static.

**Comment by sioding** [comment]
No prrof. Close
