### ISSUE TITLE
Subjugator Cloak - curse of ailment does not work.

### ISSUE THREAD

**Issue by WJamesLord** [WarEmu/WarBugs#10962]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
The subjugator cloak should remove one hex, one curse, and one ailment when invoked.  It may not currently remove any ailment.

Steps to reproduce the problem:
With a Shadow Warrior Broadhead Arrow debuff on me, I clicked the cloak on my hot bar.  The cool down reset to 30 minutes, but the Broadhead Arrow ailment was not removed.  I repeated this behavior twice.

Screenshots/Videos or archive.org evidences:
I have no screenshot at this time, but it is pretty easy to replicate.

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Fixed with patch from 15.12.2017
