### ISSUE TITLE
Quest: Bone of Contention - Offering bowl missing

### ISSUE THREAD

**Issue by Corvishar** [WarEmu/WarBugs#10968]
During the Bone of Contention quest you are asked to place the heart into the bowl.
The bowl does not appear next to the quest giver: Volkrad Schwarc
Destruction, Avelorn, 17840,20500

![corvishar_001](https://user-images.githubusercontent.com/34367906/33758151-6c6cfcc6-dbfd-11e7-8e57-0a21898fa372.jpg)
![corvishar_000](https://user-images.githubusercontent.com/34367906/33758156-70c87c46-dbfd-11e7-8a94-470e76159fc6.jpg)

Quest chain cannot be continued without the fix.

**Comment by NorKalli** [comment]
added mapmarker

**Comment by sioding** [comment]
Fixed with patch from 02.06.20018
