### ISSUE TITLE
Quest: Strike of Saphery

### ISSUE THREAD

**Issue by Corvishar** [WarEmu/WarBugs#10969]
Destruction, Avelorn, 3,61
During the quest Stroke of Saphery 2nd part you are to meet Ultorin Siege Lord - Lord is missing
You are to use the bolt throwers 6 times, but uses do not register in the quest log.
![corvishar_002](https://user-images.githubusercontent.com/34367906/33758671-76bf04e2-dbff-11e7-87df-6e721a9b5571.jpg)
![corvishar_003](https://user-images.githubusercontent.com/34367906/33758846-5723c27a-dc00-11e7-8dbd-6dca8f6257ac.jpg)

**Comment by sioding** [comment]
Fixed with patch from 02.06.20018
