### ISSUE TITLE
Fireforge's Camp  #10426 Closed...but issue still found

### ISSUE THREAD

**Issue by Rilof** [WarEmu/WarBugs#10964]
On Dec. 7 5:02pm (Thailand time).  On stage 1 of the Fireforge's Camp quest, a female Oathbearer Storguard attacked me.  I could do no damage to her.  As a lvl 40 she only did +22 dmg to me which is insignificant, but not sure how this would affect other players.  I tried to reproduce the effect during stage 2, aoe(ing) them, taunting, etc.  but I could not repeat it.

See pictures below.  It seems its an NPC form this area of the quest.

Thanks,
Rilof

![warhammer online age of reckoning screenshot 2017 12 07 - 16 37 42 43](https://user-images.githubusercontent.com/33287995/33709746-f30b35f0-db70-11e7-9c50-572adaa0cac3.png)

![warhammer online age of reckoning screenshot 2017 12 07 - 16 38 58 49](https://user-images.githubusercontent.com/33287995/33709755-fe4a2fc0-db70-11e7-9795-dd5e498436bf.png)

**Comment by Lheana** [comment]
Already reported for other PQs #9880
