### ISSUE TITLE
[Map/Area] The Badlands, Thickmuck Pit Keep entrance through texture failure

### ISSUE THREAD

**Issue by iAleks2008** [WarEmu/WarBugs#10963]
Expected behavior and actual behavior:
You can fall through the textures and enter to keep.

Steps to reproduce the problem:
See video, run forward and jump.

Screenshots/Videos or archive.org evidences:
https://youtu.be/a90TZcs0NHE

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Close - cause you can not cat on anything inside the keep. No need to do anything on this texture failure

**Comment by iAleks2008** [comment]
I'm not sure if I understood you correctly, but https://youtu.be/P6BNKRly_U8

**Comment by sioding** [comment]
This is a complete other video - i haven´t been able to go inside the inner keep. reopened

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
.Fixed with patch from .17.03.2018

**Comment by iAleks2008** [comment]
I will get  ̶p̶o̶n̶y̶  gryphon mount? :)

**Comment by wargrimnir** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366#p118993
