### ISSUE TITLE
[Public Quest] Order: Faewulf´s Rest Stage 2

### ISSUE THREAD

**Issue by sioding** [WarEmu/WarBugs#10979]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Summoning Stones should be able to destroy them

Steps to reproduce the problem:
1. Finisch Step 1
2. Kill Vile Cultist
3. Try to kill the summoning Stone

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/18517842/33804001-78f38a8c-dd9c-11e7-80bc-0efd14ff55f1.png)

**Comment by Lheana** [comment]
Clicking on it does not complete the stage?

**Comment by sioding** [comment]
No - just tested. Not possible to click them to continue to step 3

**Comment by sioding** [comment]
fixed with patch from 22.12.2017
