### ISSUE TITLE
Cinderash Enclave Easy Public Quest in Praag

### ISSUE THREAD

**Issue by RoR-Darrell** [WarEmu/WarBugs#10976]
Expected behavior and actual behavior:
It is my understanding that Easy public quests do not grant gold bags. However, while doing the pq last night with a guildmate, two gold bags dropped as rewards. He received one, which contained the choppa ruin boots. I received the second, which contained the Black Orc ruin helmet. His bag dropped approximately 1:30 am EST the morning of Saturday, December 9th. Mine dropped approximately around 2:00 am EST.

Steps to reproduce the problem:

I’m unsure how the reward system decides the color of bags (mostly it was giving green bags), but over the course of about an hour we had two gold bags rewarded.

Screenshots/Videos or archive.org evidences:

No screenshots, as I didn’t realize at the time that it could be a bug. I will do the PQ again to see if I can replicate and screenshot a rewarded gold bag.

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
You can get gold bags in easy pq´s - it´s ultra rare but you can.
