### ISSUE TITLE
Hulking Brute tactic.

### ISSUE THREAD

**Issue by AlistaireCrowley** [WarEmu/WarBugs#10973]
Hulking Brute tactic does not add initiative when equipped as stated in latest patchnotes.

Screenshot with tactic off:

![fabio_007](https://user-images.githubusercontent.com/10405430/33795781-21a03852-dce8-11e7-89b2-a9b479d1d97c.jpg)

Screenshot with tactic on:

![fabio_006](https://user-images.githubusercontent.com/10405430/33795787-304cc1ae-dce8-11e7-9573-1bda17e05af8.jpg)

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Thanks for the report. Please use the ".getstats" command and create screenshots with the output to make sure its not a paperdoll problem.

**Comment by Haojun-Phalanx** [comment]
the tactic working with .getstats.

**Comment by AlistaireCrowley** [comment]
Ok. Just a paperdoll bug.

Cheers for testing.



Skickat från min Samsung Galaxy-smartphone.


-------- Originalmeddelande --------
Från: Haojun-Phalanx <notifications@github.com>
Datum: 2017-12-09 16:42 (GMT+01:00)
Till: WarEmu/WarBugs <WarBugs@noreply.github.com>
Kopia: AlistaireCrowley <Mr_Darkstalker@hotmail.com>, Author <author@noreply.github.com>
Rubrik: Re: [WarEmu/WarBugs] Hulking Brute tactic. (#10973)


the tactic working with .getstats.

**Comment by sioding** [comment]
close
