### ISSUE TITLE
Zone locked, win gold back, lose ''loot bonus roll'' bag never arrives. It has happened already twice.

### ISSUE THREAD

**Issue by HKMFNADO** [WarEmu/WarBugs#10977]
Irritating to say the least, especially how rare it is to actually get a gold bag...

https://i.imgur.com/MImnrqR.png

**Comment by sioding** [comment]
Wait for the next server restart. If he bag isn´t in you mailbox please give us an information here.

**Comment by HKMFNADO** [comment]
Logged in right now, the bag is in my mailbox .
