### ISSUE TITLE
[Choppa] Big Choppa of conquest broken

### ISSUE THREAD

**Issue by Radiantknight** [WarEmu/WarBugs#1097]
Lists 2H stats, occupies both hands, but model is 1H and I can't use 2H finisher Weaklin' Killa with it

**Comment by Titoos** [comment]
https://github.com/WarEmu/WarBugs/issues/900
https://github.com/WarEmu/WarBugs/issues/861
https://github.com/WarEmu/WarBugs/issues/1030

**Comment by Radiantknight** [comment]
So...will it be fixed? no better 2H alternative for now, but inability to use finisher is kinda gimping the class, since it's almost the only  reason to get 2H in the first place.

**Comment by Evildoor** [comment]
You can use the finisher, as well as BO's Big Un. It is grayed out, it will say "Requires Great Weapon", but it will fire off anyway.

**Comment by Radiantknight** [comment]
really? was confused by those, will test and then close the issue
