### ISSUE TITLE
Mount Gunbad - in-place respawn

### ISSUE THREAD

**Issue by GreatHarlequin** [WarEmu/WarBugs#10970]
Not sure if this is a feature or a bug.

I entered the instance on my own. Took the portal to the bottom with all the R51 skeletons who kill me. Then when I click respawn, I stand up from where I died. Book of Binding doesn't work. I have to use /stuck x2 to get out.

**Comment by wwright72** [comment]
Yes, can confirm. When you die in Mount Gunbad and you try to respawn you simply get back up where-ever you died. This can make it VERY easy to get stuck because of all the knockback and rift abilities that the mobs and bosses use.

**Comment by Hargrim** [comment]
Fixed.
