### ISSUE TITLE
Empire - Chapter 7 PQ Warrior Priest Rewards

### ISSUE THREAD

**Issue by garytownsend** [WarEmu/WarBugs#10984]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
After working the PQ on my Warrior Priest  and doing a couple of passes i completed the infulence for this PQ. When i went to claim my influence rewards  the basic rewards did not appear and the advanced and elite rewards said i needed more influence.

Also noted that the Rally master in the text for the chapter lists a different person. Than the Rally master in the village.

Steps to reproduce the problem:

Complete the influence for the chapter using the Boshenfels Siege and only the seige PQ once finished went to Rally Master and couldn't get rewards

Screenshots/Videos or archive.org evidences:
https://imgur.com/a/11GoI

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Lheana** [comment]
To get the influence rewards of **Empire Chapter 7**, you must talk to the Rally Master of the **Empire Chapter 7**. The SS you put clearly show the Rally Master of **Empire Chapter 8**. Talk to the correct Rally Master...

**Comment by garytownsend** [comment]
you are indeed correct what throws a person and i went back to check this is that standing at the Chapter 8 Rally master the PQ meter says you are in chapter 7 not 8 and that is shown in my screenshot. I misread that and file this in error.  After opening the tome i saw that i did not have the requisite influence. So not sure if i should put a different bug in or not but thought i would amend this instead.
