### ISSUE TITLE
Runtime error in Gunbad Bossfight

### ISSUE THREAD

**Issue by tlitschye** [WarEmu/WarBugs#10983]
One teammember keeps getting runtime errors durin Boss encounter in gunbad.
Tried several bosses in right wing and the teammember keeps getting the problem.

It is ONLY during the last step of the PQs,everything else is fine

**Comment by sioding** [comment]
I guess they are running different language clients? Had the same - set to english was the solution.

**Comment by tlitschye** [comment]
Exactly, we will try if it fixes it.

**Comment by grunbag** [comment]
Did it fix the issues ?

**Comment by tlitschye** [comment]
yes

**Comment by sioding** [comment]
Thanks for the feedback @tlitschye.
