### ISSUE TITLE
Crashes as soon as it tries to log me in

### ISSUE THREAD

**Issue by ferraz19** [WarEmu/WarBugs#10988]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

expected to log in normally...game crashes as soon as it seems like it is gonna log in

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Haojun-Phalanx** [comment]
Leave your guild and try again.

**Comment by sioding** [comment]
Try double /stuck while you see the loading screen.
