### ISSUE TITLE
PQs in Dark Elf ch. 15 don't build inf

### ISSUE THREAD

**Issue by korwrath** [WarEmu/WarBugs#10985]
The PQs in Dark Elf Chapter 15 do not give/record influence for killing mobs or completing objectives for any of them.  You can kill mobs in the working PQs as usual and for the PQ objectives it will accept that, but players influence bar remains at zero (for example)

**Comment by Lheana** [comment]
Have you tried with all PQs?

**Comment by Lheana** [comment]
Kelysian's Landing PQ was set as giving influence for the DE chapter 16. I corrected it, thus it now grants influence for the DE chapter 15.
The 2 other PQs of the chapter are correctly set: they are showing as PQs of chapter 15 and grant influence for this chapter.

**Comment by korwrath** [comment]
I just tried Kelysian's Landing PQ and it is not giving inf for chapter 15.   The other two are now giving inf correctly.

**Comment by Lheana** [comment]
It means it is not a general issue for chapter 15, but just the PQ Kelysian's Land that was giving influence for chapter 16 instead of 15.

**Comment by sioding** [comment]
Fixed with patch from 15.12.2017
