### ISSUE TITLE
Auction house - class filter only works for own class

### ISSUE THREAD

**Issue by CornerbackAC** [WarEmu/WarBugs#1098]
When using the class-filter in the auction house, it doesn't show any results if you select a different class than the one you are currently logged in with, unless you can use them.

Example: 
i search for RP items with my slayer. i get no results.
i search for IB items. the only results shown are shields, as they are restricted to all dwarves and i could use them (if i could use shields).

**Comment by Tyramissoux** [comment]
Works also for other classes BUT it always includes your class. Example: Searched on my dok for shaman items. Found staffs but only dark elf ones. If I look for blue shaman armor on my dok, there will be no results even though there are several blue shaman items in the AH.

**Comment by Kaelang** [comment]
Merging this with https://github.com/WarEmu/WarBugs/issues/12109.
