### ISSUE TITLE
Quest: Those Who Serve

### ISSUE THREAD

**Issue by thevanburenboys** [WarEmu/WarBugs#10989]
The quest asks to do 2 things:

- Use the horn near the hatchery
- Speak with the Bloody Sun Brawler

The map tracker however points to an unrelated horn, inside the Avelorn/Saphery RVR lake (the one that unlocks the "Do You Know The Way" tome unlock @ 14.7k 900) and using it actually works. On the other hand, the Bloody Sun Brawler is nowhere to be seen in the area, even though the quest tracker continues to point to that location. 

I've also searched for the NPC around the area where the quest text actually points to (near the gryphons in saphery) but couldn't find him either.

![haraddus_000](https://user-images.githubusercontent.com/34468938/33870173-d0717d7a-def3-11e7-9807-317a51859ff3.jpg)
![haraddus_001](https://user-images.githubusercontent.com/34468938/33870178-d9de0a54-def3-11e7-963d-11b25862cf88.jpg)
![haraddus_002](https://user-images.githubusercontent.com/34468938/33870193-e2203c78-def3-11e7-8f27-7173b2ffe62d.jpg)

**Comment by sioding** [comment]
Fixed with patch from 02.06.20018
