### ISSUE TITLE
Destro PQ Silkens appears completely empty

### ISSUE THREAD

**Issue by lennip** [WarEmu/WarBugs#10981]
Hi, sorry about the duplicate, but all previous tickets for that PQ have been closed. Patchnotes from 25/11/2017 say the PQ "Silkens" (Ostland - Chaos ch. 6) has been reworked and is now fully functional...

However when I go there, nothing shows up: 
- no PQ title, stage info or progress tracker
- no NPCs (spiders, etc) except a couple of lvl 1 rats
- the entire area of the PQ is almost empty: no enemy NPC or clickable object

![silkens](https://user-images.githubusercontent.com/2891053/33808376-8c8e018c-dde5-11e7-9778-c536990748f3.jpg)

**Comment by Lheana** [comment]
Have you tried several times to go out of the PQ area and come back?

**Comment by Lheana** [comment]
Works fine on dev server, but yes could not activate the PQ on live, don't know why.

**Comment by Lheana** [comment]
Should be fixed next patch. The thing Saup did to fix this PQ had not been pushed on live.

**Comment by Lheana** [comment]
PQ is now working on live.

**Comment by sioding** [comment]
fixed with patch from 22.12.2017
