### ISSUE TITLE
SH: Sticky Squigz and  "Sigil of Sigmar"

### ISSUE THREAD

**Issue by tr806042** [WarEmu/WarBugs#10995]
Hi,

one again not sure if this is a bug or intentional. But after experinceing multiple failt jump aways form wh, where i would goo them up get cd on  Sticky Squigz and just not jump. I ask the wh why that happend and he said he had a skill not saying which. Then i searched couldn't finde it (no snare or kd), so i asked my guildm8s and they told me it's bcause they are slow immune(Sigil of Sigmar/(Break loose/Feline Grace). I don't get why this would prevent me from jumping.

**Comment by sioding** [comment]
Sorry but this Bugtracker is for bugs only. If you are not sure - please use the forum and discuss it on one of the boards. If you found a bug, please describe it as precise as you can. Bring in some good screenshots and evidences why you thnk this is a bug. "Not sure if its a bug or intended" is the wrong way for this bugtracker.

**Comment by tr806042** [comment]
im not sure, but i created this post as it is since i know i often can't jump from mdps. I have been told by a wh that he has a skill thats prefents me, that he hasn't, other then Sigil of Sigmar which shoudn't, reading the spell discriptions. So if this isn't a intended change meaning it is a bug i will happly provide u with more avidence of the interaction.

**Comment by tr806042** [comment]
O.o 
so it's a bug and u want me to show u some avidence?

**Comment by tr806042** [comment]
![ernh_001](https://user-images.githubusercontent.com/3294961/33960969-b4cf160e-e04c-11e7-969a-27ccb490dc8c.jpg)
![piechoppa_000](https://user-images.githubusercontent.com/3294961/33960975-b7026764-e04c-11e7-83e1-9044e1ca62a0.jpg)

**Comment by Krimalicious** [comment]
he is actually correct.... This is a bug !

**Comment by Nfkillz** [comment]
lol. it s not a bug. snare immune of melee chars gives immune to Sticky Squigz/whirling pin

**Comment by tr806042** [comment]
sure it clearly says "prevents jumping" in the spell discription, rofl

**Comment by sioding** [comment]
Fixed with patch from 15.12.2017

**Comment by tr806042** [comment]
:D sweet <3
