### ISSUE TITLE
chaos ch17

### ISSUE THREAD

**Issue by paasta3** [WarEmu/WarBugs#10993]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: chaos ch 17public Q- gates of praag -1 stage..there are empire barrickades that need to be destroyed..5..but if public quest is done after the resetting barrickades sometimes dont reset and its shows as dead and cant attack it and 1 stage cant be done...

Steps to reproduce the problem: need to reset barricades

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Lheana** [comment]
Barricades will no longer respawn, which will prevent this bug from happenning.

**Comment by sioding** [comment]
Fixed with patch from 15.12.2017
