### ISSUE TITLE
Quest: Distrust

### ISSUE THREAD

**Issue by Corvishar** [WarEmu/WarBugs#10991]
During the Quest Distrust, you are to obtain and deliver the enchanted flute next to a Champion: Belran Woodsong. Quest should update when reaching the correct coordinates or after killing the champion.
None of that is happening.

Dark elves, Eataine, 4733, 59754
![corvishar_000](https://user-images.githubusercontent.com/34367906/33874204-3a6c6134-df1e-11e7-8178-4f60ba0c92e5.jpg)
![corvishar_001](https://user-images.githubusercontent.com/34367906/33874220-50cbef12-df1e-11e7-9664-085d1d592cee.jpg)

**Comment by Akenatoth** [comment]
I'm having the same problem, after getting the Entrancing Flute I should meet with Belreann Woodsong but she's hostile and killing her doesn't help.

**Comment by NorKalli** [comment]
placed missing mob

**Comment by NorKalli** [comment]
having issues with quest turn in

**Comment by sioding** [comment]
Fixed with patch from 02.06.20018
