### ISSUE TITLE
Genesis Vendor - Undying set Magus/Engi

### ISSUE THREAD

**Issue by timoteiz** [WarEmu/WarBugs#10990]
In the genesis vendor there is only 1 part of the genesis undying jewels availible to buy just the fragment one.  The other 4 are not there. Also the item does not have class restriction on it.

**Comment by sioding** [comment]
screenshots plz

**Comment by timoteiz** [comment]
![fixxer_011](https://user-images.githubusercontent.com/34124804/33899660-d5eb7928-df74-11e7-8725-4afbc3d84191.jpg)


I have scrolled at the end of the item sin teh vendor.. only fragment availible

**Comment by sioding** [comment]
Fixed with patch from 15.12.2017

**Comment by timoteiz** [comment]
fixed as in removed from the game? teh vendors now doesnt have the undying set for engies at all... or am i mistaken?

**Comment by Neutrinoo** [comment]
This is broken for magus.  i bought it anyway with my genesis token so I have it when its fixed.   See my magus bug for same issue.

**Comment by sioding** [comment]
I will ask if it´s intended. I will close your other issue @Neutrinoo

**Comment by sioding** [comment]
checked that für you - its intended.

**Comment by Neutrinoo** [comment]
Is there some good reasoning why its intended?  Can I get conqs for the pieces I bought in anticipation?

**Comment by sioding** [comment]
This is the wrong place for this discussion. Please use the forum for it.
