### ISSUE TITLE
Issue when logging in

### ISSUE THREAD

**Issue by Toriaz** [WarEmu/WarBugs#10994]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Log in successful with my Barbaak character

Steps to reproduce the problem:
After the second loading screen (in inevitable city) the game crashes and it's game over for me.
My other characters do not encounter the issue.

Please help :)

Screenshots/Videos or archive.org evidences:
Can't provide screenshot

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by deLunel** [comment]
I have same problem with my WE Blendaa. 
Played it about 1 hour ago and logged off while in IC. Trying to log in now it instantly crashes the client after loading IC. Have tried 8 or 9 times. Would it be possible to move her to a safe starting point maybe?
I have no problem logging on to other alts.

**Comment by Toriaz** [comment]
Solved thanks to a double /stuck on loading screen. Many thanks to the GM.
Cheers!

**Comment by deLunel** [comment]
Yes, worked for me too. Leaving guild did not make a difference btw.
