### ISSUE TITLE
Shadow Warrior: Armor buff in Assault stance

### ISSUE THREAD

**Issue by Comadrin** [WarEmu/WarBugs#10997]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

When going in to Assault stance with SW it should increase your Armour with same amount from items, but it does not for me.
If i take away an armour piece and put it back when in Assault stance then I get the increase.

Steps to reproduce the problem:
Look at armour when in Scout or skirmish stance, go to Assault stance and there is no increase in armour, put one armour piece in backpack and put it on again then the increase shows.

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Screenshots with .getstats please.

**Comment by Comadrin** [comment]
Ok when use .getstats i see i have the armour in my stats but not in the profile.

![image](https://user-images.githubusercontent.com/34538282/33989367-88c9d596-e0c7-11e7-9180-46d9311c4bd4.png)

**Comment by Torquemadra** [comment]
paperdoll visual only

**Comment by LeonVic** [comment]
This visual Bug still. 

![nhindael_002](https://user-images.githubusercontent.com/38075110/38693717-10a2941c-3e88-11e8-8dc3-9a3a80766000.jpg)
![nhindael_003](https://user-images.githubusercontent.com/38075110/38693723-1462f59c-3e88-11e8-91d0-c56a9b624ca4.jpg)
