### ISSUE TITLE
BW Backlash

### ISSUE THREAD

**Issue by Godzip** [WarEmu/WarBugs#11008]
Backlash on BW activating on dot ticks? 

pls close if existing!

**Comment by sioding** [comment]
Screenshots please.

**Comment by cimator** [comment]
Backlash seems to be working fine. Make sure you didnt mistake it with Pyroclastic Surge backlash, which happens when the projectile hits your target instead of on cast.

**Comment by sioding** [comment]
Thx @cimator. I´ve checked that too with another BW. Backlashes are not activated on ticks.
