### ISSUE TITLE
Squig Herder Spiked pet ability Poisoned Spine, incorrectly flaged as curse (It is an Ailment)

### ISSUE THREAD

**Issue by Torete-war** [WarEmu/WarBugs#11009]
The Spiked Pet ability Poison Spine asigned as an Ailment in tootip, is hiting the NPC'S as a Curse.

The Squigh herder needs the enemy target already ailing if he want to cast the heal debuff ability "Rotten arrer"

This pet's ability is flagged as a Curse in target, should be an Ailment instead

Pic of the spike pet's ability "Poison Spine", asigned as a Ailment in the tooltip.
https://ibb.co/foJO0R

Pic of the Character ability "Rotten Arrer", this ability requires an Ailign target, and you are unable to use it untill the target has an Ailment:
https://ibb.co/krwJ0R

Attacking an NPC only with Spiked Pet and manualy clicking ability Poison Spine, the target has Poison Spine running on him, but the Rotten Arrer ability is unable to beign used....Once i pass the cursor over the enemy target and check what type of attack is asigned to Poison Spine Spiked pet ability, shows asigned as a Curse, when it should be an Ailment instead.
https://ibb.co/enb7um

**Comment by sioding** [comment]
fixed with patch from 22.12.2017

**Comment by Torete-war** [comment]
It is broken other time, the squig herder spiked pet ability, which should be flagged as an ailment "Poison Spine"

Isn't flaging itself as an ailment, you can't use the heal debuff that require an ailment in target, because the pet ability "Poison Spine" is not giving you the posibility to use the heal debuff after.

Please reopen the report, because now is not working.
