### ISSUE TITLE
Squig Herder Gas Squig, doing way much less damage than the tooltip ability say.

### ISSUE THREAD

**Issue by Torete-war** [WarEmu/WarBugs#11003]
There is a huge diference (dramatic diference) betwen the damage shown by Gas Squigh ability "Goop Shootin" in tooltip and what it is really doing in a simply level 37 green NPC (not a champion, not a hero, just a simply level 37 green npc)

The ability tooltip says, the base damage is 491 with my character equipment, and full ability path specialized, but the real damage deal in a low green npc level 37, is far from that base damage and not even matching it by a good amount if you sum both damages (damage dealt + damage mitigated) in that simply lvl 37 green npc.

I am pretty sure, there is something not working with the damage dealt, for such an huge diference in a lvl 37 npc (not even a player with armor,tought,etc)

https://ibb.co/eVGppm

https://ibb.co/bR0FUm

https://ibb.co/hSGB26

https://ibb.co/jXMppm

As you can see in the combat log, against a lvl 37 npc, the ability "goop shootin" it is really underperforming at the supoused damage it should be dealing with a base damage of 491, in a low lvl npc (will be even worse in players)

With 491 base damage, it is really doing this type of hits in that NPC:

**-Normal hit** **- 224 damage and (67 mitigated)** -----> **(224+ 67 = 291 damage, this is not even close to fulfill the base of 491 damage in a lvl 37 green npc)**

**-Normal hit** **- 224 damage and (67 mitigated)** -----> **(224+ 67 = 291 damage, this is not even close to fulfill the base of 491 damage in a lvl 37 green npc)**

**-CRITICAL HIT!!** **- 316 damage and (95 mitigated)** -----> **(316+ 95 = 411 CRITICAL DAMAGE!!, this is not even close to fulfill the base of 491 damage in a lvl 37 green npc)**

**-Normal hit** **- 224 damage and (67 mitigated)** -----> **(224+ 67 = 291 damage, this is not even close to fulfill the base of 491 damage in a lvl 37 green npc)**

Let's remember all this dramaticaly diference with the damage in tooltip and the damage it is really doing, has been tested in a level 37 green NPC, in normal players, the diference is way much more important than this... and this one it is already dramaticaly high.

I really think, there is a bug and the ability is underperforming and giving much less damage than it should be doing... when even a CRITICAL HIT, is not able to match the base damage ability in a simply level 37 Green NPC.

And even worse, once we add, the Squigh Herder players lose the autoattack, when they use this pet instead of Spiked Squig...

**Comment by Torquemadra** [comment]
Tooltip is running of YOUR stats when it should be running off the PETs stats, this is likely a unlocated packet issue. Damage is now accurate as per combat formulas and client primary stat multiplier values, tooltip will still not be.
