### ISSUE TITLE
When clicking play..keeps coming back to character selection screen

### ISSUE THREAD

**Issue by Ironbyrde** [WarEmu/WarBugs#1100]
Had some issues yday with not being able to join scenario - kept saying I was in combat while I was no where near any combat, and would not allow me to unselect Flag for RVR even in PVE zone. Then I took Flight Master from Ekrund to Nordland had me appear in Mount Bloodhorn instead. Logged off and since then cannot log back in again on any of my characters. Have uninstalled and re-installed game but every time after I pick the character I want to play and click play, it goes to the normal "loading mount bloodhorn (or other depending or character) screen" and then back to  the start screen where I select which character to play again?  Is there a fix?  Name of character is Ironbyrde

**Comment by bumik94** [comment]
Type /stuck when at loading screen and press enter. As for the combat bug, type /say &jump, that fixes it.

**Comment by Ironbyrde** [comment]
Thank you! It worked! Back at slashing orcs yey!
