### ISSUE TITLE
Squigh herder pets not using theyr self abilities at intended range

### ISSUE THREAD

**Issue by Torete-war** [WarEmu/WarBugs#11000]
Squig herder spiket pet abilities tooltip say theyr range are 100 feets, but actually the pet is not using them at 100 feets, it is more like a 75 feets range.

It is very easy to reproduce the problem, the own squigh herder character has 100 feets range abilities, this abilities are flaged as red in ability's number, when you are not able to use them (What blocka?)

Once you enter in the 100 feets range, that red number turns to white, and means you are in 100 feets range, so, you pet should be able to use theyr abilities whithouth go any further in fight, or closer to the target, but instead he goes closer by a huge amount, making him much easier to be killed in areas, and easier to target by pounce friendly classes.

The target is over 100 feets range and i am unable to use the ability:
https://ibb.co/b8jqc6

The mensage target is out of range is trigered, i am still behind those 100 feets range:
https://ibb.co/kreHPm

Now i gonna step in 2-3 feets, untill the what blocka ability number turns into white, and means i am in 100 feet range with my pet, next to me:
https://ibb.co/kExRH6

Now i am sending my own's Spiked Pet to attack the same target, and since i am already in 100 feets range, he should attack straight withouth go closer to the target.
https://ibb.co/hzuj4m

Instead of respect those 100 feets range abilities have, the pet get closer to the target for use them, by a bunch of space (looks like at least 25feets, or a 25% less range than the abilities have) and as you can see, it is a patern which repeat in each target you test it with, the pet has much less range than the abilities have.

https://ibb.co/h5Tix6

https://ibb.co/nHoGH6

https://ibb.co/dcx44m

https://ibb.co/eTJcPm

Here, casting 100 feets ability What blocka, interrumping ability, sending pet, and pet moving too close to the target for the ability it has (stated as 100 feets ability, both of them) losing around a 25% of intended abilities range

https://ibb.co/b6ggjm

https://ibb.co/ge3SPm

https://ibb.co/bzGQAR

**Comment by Nfkillz** [comment]
read patchnotes. range was decreased

**Comment by sioding** [comment]
Hm - tried to find the notes @Nfkillz  - cause when its true, its missing also on the changes section in our wiki.

**Comment by Torete-war** [comment]
Even if it was changed and made shorter range, a staff member discussed with me about this fact and told me literally "post it in bugtracker". Because he thought, spiked pet were attacking in 100 feets range, while i knew the pet was not attacking in 100 feets.

I only wanna prove the pet is attacking in shorter range as i said, and i am showing i was right.

Since this is not a original server mechanic, and was a only implemented for RoR server.
I think it should be in .AB changelist command (right now it is not in change list, and can lead to confusion when people discuss about pet's range, when they are wrong, as has been proven)

**Comment by Nfkillz** [comment]
The range of the Spiked Squig is now 65ft.
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=18653&hilit=spiked

**Comment by Torete-war** [comment]
Actually that 65 feets range, was changed to 85 feets, days after... because the Squig herder comunity was standing against that 45% cut range nerf, withouth sense.

**Comment by Torquemadra** [comment]
The abilities are 100ft, pet AI is something else, regardless its not getting touched at this point.
