### ISSUE TITLE
Lion doesn't get crowd controlled

### ISSUE THREAD

**Issue by Mezirah** [WarEmu/WarBugs#11002]
When I play on my sorcerer, I save grip of fear (root) often for white lion pets when I know someone wants to get me pulled or snared with their pet. When it's sent at me, there's nothing I can to do defend myself like I could on live, and it literally kills me. I don't think snares are working either.

Video footage proof it existed on live is at 1:08 

https://youtu.be/yZ70RpTvcqE?t=1m7s

**Comment by tlitschye** [comment]
What tier are you playing atm? Because in t4 a lot of WL player play with Leonine Frenzy that makes the pet immune to all kinds of CCs.
Did you check the WL pets active buffs when you CCd them?

Greets

**Comment by Mezirah** [comment]
You can close this for now. I tested it and seems to be working in controlled setting. May have been lag issues or the ability mentioned above. Thanks,
