### ISSUE TITLE
Oppressing blows post patch 

### ISSUE THREAD

**Issue by plutobhg** [WarEmu/WarBugs#11004]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: 15% crit and spirit dmg as long as youre using 2hander, does not give the 15% crit bonus. 

Steps to reproduce the problem: checked .getstats and paper doll

Screenshots/Videos or archive.org evidences: check it

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Nice that checked .getstats and paperdoll. Can we have your screenshots please?

**Comment by Zumos** [comment]
on .getstats it does show 15% crit

**Comment by Horusaximand** [comment]
Could You give a screenshot? I have same problem.

**Comment by Torquemadra** [comment]
there is no problem its criticalhitrate overall not melee crit

![xanaxe_032 1](https://user-images.githubusercontent.com/16200780/34075148-8b2ee022-e28b-11e7-9ef9-48b2a510e21d.jpg)
