### ISSUE TITLE
Lord NPC in RvR Lake 

### ISSUE THREAD

**Issue by Zoggof** [WarEmu/WarBugs#11005]
There's a level 41 lord NPC located at the Wood Choppaz BO in Avelorn.

![doinks_000](https://user-images.githubusercontent.com/23256143/34071774-e268c882-e2cf-11e7-8f63-1aaab2303782.jpg)

**Comment by Torquemadra** [comment]
destruction quest mob, let sleeping lords lie

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 20.4.2018

**Comment by sioding** [comment]
This isn´t fixed - reopen.

**Comment by Lheana** [comment]
This has been fixed for a while by Kab: this is no longer an NPC but a GO, as it is meant to be.
