### ISSUE TITLE
Sigmars Shield

### ISSUE THREAD

**Issue by eherenreich** [WarEmu/WarBugs#11017]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Sigmars Shield in live ran out when you hit 0 RF - The way it currently is working, it will create problems with the regain and thus prevent access to RF cost abilites.

I understand that this is the leftover of the unannounced change a few days ago. The implications of this ability when you get down to RF 0 and not dispel is makeing the shield more of a curse than a benefit.

What you could have done was make the constant drain cost higher than the 5 pt. it resently was (If you considered that to be OP) and take the CD from 20 to 10 and the uptime from 20 to 10. More frequent cast means less of a curse when its actually cast and the flow of battle changes, it will be a shorter liability/curse.

Most classes will give you atleast 2 damage hits pr. second - right now if the shield is cast and a "goblin nerf herder" is around, the pet alone will take you to zero RF way to fast and you wont have any chance to regain RF until the shield runs out.

I tried to test this useing suplication while i was attacked and at 0 RF - it was impossible to get any RF. Because as ap is converted to RF dureing the channel any damage will eat 20 RF. Suplication channels and goes up 20 RF then back down to zero right away.

The full duration of suplication just extended the shield for those 3 seconds and left me with zero RF after it was complete. This is essentially makeing the shield a curse on yourself not a buff and a down right death sentence in most cases.

What you should do is adjust the constant drain so its not ticking pr. damage but pr. second. and adjust the amount it ticks pr. second and its recast timer to prevent it from beeing too powerfull. Else at the very least make it a 7 second uptime, to easen the "curse" it has become.

A quick solution for now - Change it back to its ab.state or make the buff dispell, when you run out of RF as it was on live. Ernest and Frank, in this current state its a liability and a curse not a buff a complete lackluster. I would prefere a constant drain, adjusted by as stated in the top.

Sorry if you feel offended by my advice / suggestion that is not intended. Regardless I speak the truth here, it's not only broken now, but useing it breaks the class synergy.

**Comment by sioding** [comment]
Sigmars Shield should stop if you are at 0 RF. You are free to write a proposal in our balance forum: https://www.returnofreckoning.com/forum/viewforum.php?f=95

**Comment by eherenreich** [comment]
Well it does not

**Comment by sioding** [comment]
Well - it will.

**Comment by eherenreich** [comment]
Okay, thats an excellent logic - I think il save you the trouble of reading my crap in the future. Cause as you say "It will" and so why bother trying to help out if its already getting fixed!
