### ISSUE TITLE
Bug at connection =/

### ISSUE THREAD

**Issue by Novawarp** [WarEmu/WarBugs#11014]
I disconnected with my KOTBS the 12/16/2017 at around 22h30 in Altdorf (Paris hour)  and when I reconnected ( today 12/17/2017 at 11h45 ) I found myself in a closed map with invisible barriers called Winds of Chaos.
My character is a lvl 34 KOTBS called Novaware
![sans titre](https://user-images.githubusercontent.com/34621094/34078806-b0fd2660-e321-11e7-84ed-f4c0a0cdf990.png)
![sans titre1](https://user-images.githubusercontent.com/34621094/34078807-b36949ba-e321-11e7-8072-f7da01550e25.png)
![sans titre2](https://user-images.githubusercontent.com/34621094/34078809-b4fc09de-e321-11e7-9e75-addafe327743.png)

**Comment by Novawarp** [comment]
It's said racial slur, but I never insulted anybody.
No reason ban.

**Comment by sioding** [comment]
Seems like you got banned. You should get a private message or email. You can open an appeal right here: https://www.returnofreckoning.com/forum/viewforum.php?f=87 but please: check the rules before.
