### ISSUE TITLE
Archmage Issues with Mechanic

### ISSUE THREAD

**Issue by Zumos** [WarEmu/WarBugs#11015]
I was thinking about proposing some changes to AM mechanic, so first I wanted to check exactly how it was working now and I found many weird things happening that shouldn't. So I tested all abilities which use/gain High Magic points and put them in the excel file. While I was working on testing everything I didn't screenshot or record anything, so when I was done I redid some tests and screenshotted or made of video of the issue. I didn't record every issue, but at least show all "types" of issues. In the excel file, the second part are the tests where everything in Red has some issue. "Combat log" stands for the combat log of the game, "Effect symbol text" stands for when you hover over an ability effect on unit target frames, and "Tooltip" stands for when you hover over an ability on your hotbar. The list on top is a total summary of the "bonuses" that abilities get with the use of the AM mechanic. 

[AM Mechanic Testing.xlsx](https://github.com/WarEmu/WarBugs/files/1565784/AM.Mechanic.Testing.xlsx)

First I will give the list of issues and after that the screenshots and videos with prove. Note that some absolute values might be different due to different stats or different mastery training (as I had to switch to test all abilities). But all relative differences should remain the same. 

Issue 1: Lambent Aura --> HoT should increase with Force points, but doesn't. Weirdly enough the Effect symbol text does show the expected increase, but it doesn't actually heal for that.

Issue 2: Blessing of Isha --> Combat log value does not equal the tooltip value.

Issue 3: Balance Essence --> For some reason when you have 1-5 Tranquility points, the ability does 3.5% more damage. There is no reason it should do this.

Issue 4: Transfer Force --> First of all does not scale with Tranquility points, which it should. Second the Effect symbol text does scale, but has lower values than the Combat log and Tooltip values.

Issue 5: Storm of Cronos --> Combat log value different from Tooltip value. In addition does not use a Tranquility point, which it should.

Issue 6: Law of Gold --> For some reason when you have 1-5 Tranquility points, the ability does 3.5% more damage. There is no reason it should do this.

Issue 7: Energy of Vaul --> For some reason when you have 1-5 Tranquility points, the ability does 3.5% more damage. There is no reason it should do this. In Addition Combat log value is very different from Tooltip value.

Issue 8: Fury of Asuryan --> Does 37% increased damage when you have 1-5 Tranquility points, where its damage should not increase at all.

Issue 9: Law of Conductivity --> First of all does not scale with Tranquility points, which it should. Second the Effect symbol text does scale, but has lower values than the Combat log and Tooltip values.

Issue 10: Radiant Gaze --> First of all does not scale with Tranquility points, which it should. Second the Effect symbol text does scale, but has lower values than the Combat log and Tooltip values.

Issue 11: Radiant Lance --> Does 35% increased damage when you have 1-5 Tranquility points, where its damage should not increase at all. 

Issue 12: Cleansing Flare --> For some reason when you have 1-5 Tranquility points, the ability does 4.1% more damage. There is no reason it should do this.

Issue 13: Scatter the Winds --> First of all does not scale with Tranquility points, which it should. Second the Effect symbol text does scale, but has lower values than the Combat log and Tooltip values.

Issue 14: Dissipating Energies --> For some reason when you have 1-5 Tranquility points, the ability does 3.6% more damage. There is no reason it should do this. In Addition the Combat log values differ a lot from the tooltip values. 

Issue 1:
![zumoss_015](https://user-images.githubusercontent.com/19267650/34080311-262ba096-e33c-11e7-96b0-7879d9e6bf51.jpg)

Issue 2: 
![zumoss_016](https://user-images.githubusercontent.com/19267650/34080318-32e39e9c-e33c-11e7-97be-6cc9fafa18ad.jpg)

Issue 7: (Similar problems with issues 3, 6, 12, 14 as in a random small increase of damage: about 3.5-4.1%)
![zumoss_018](https://user-images.githubusercontent.com/19267650/34080345-8930b6d6-e33c-11e7-9268-17129da3dcf2.jpg)

Issue 9: (Similar problems with issues 4, 10, 13 as in shared problems of DoTs. Need two screenshots for proving)
![zumoss_020](https://user-images.githubusercontent.com/19267650/34080371-daf6fd5e-e33c-11e7-865b-8cc4f70a4b1b.jpg)
![zumoss_022](https://user-images.githubusercontent.com/19267650/34080374-e2001478-e33c-11e7-8db5-52a5eb3c1e36.jpg)

 Issue 5: https://youtu.be/Z_I6_toJsSQ

Issue 8: (Similar problems with issue 11) https://youtu.be/-l7DZztcL4s

Issue 14: 
![zumoss_024](https://user-images.githubusercontent.com/19267650/34080421-edeb83ca-e33d-11e7-90f7-71a6785aad69.jpg)
![zumoss_025](https://user-images.githubusercontent.com/19267650/34080427-0907f3a0-e33e-11e7-8cdf-1e708e7388d4.jpg)

**Comment by sioding** [comment]
Wow. Thanks for all the effort your bring into this report but i don´t think the devs could work on it that way. We need one report per issue.

**Comment by Torquemadra** [comment]
Its fine how it is

**Comment by Natherul** [comment]
Im going to have to agree with sio here, I dont do well with a wall of text when its not related and all I can say from looking at it is that damage disparity of these small numbers (a few %) are well within the normal range of the damage and healing of an ability itself and as such is most likley not something wrong

**Comment by Zumos** [comment]
This is just an insult after spending hours on testing and getting this all nicely written out. Besides Torque says it is fine as it is written. 

Also abilities do not randomly start doing a couple percent more damage consistently. There can be a rounding off error causing a difference of 1 or maybe 2 damage/healing, but not anything more. Further there are many more issues I highlighted.

**Comment by Natherul** [comment]
Thats not an insult, but:
1. I cant work with tickets like this, tickets are here to represent a unique issue each
2. Each ability have a set min and max damage or healing, a increase or decrease of sub 5% is more likely to be a statistical random element then it is imperial fact. (especially since there is no code related damage increase for the class, there can be DB overrides set, but they would more then likely be increases of more then 5%)
and again Im sorry but posting a long list like this in one ticket WILL make me read it fast and skip if it does not look relevant, as such refer to #1

**Comment by Zumos** [comment]
1. The reason I put it all together is because several of the issues of abilities show the exact same and wrong behaviour. Also because it is all related to the High Magic mechanic.
2. Non-crit are static values, so even 3-4% difference on using points versus not using points cannot be explained by some random element. 

Also I would say that DoTs not scaling with Tranquility points, or Radiant Lance/Fury of Asuryan doing about 35% more damage with Tranquility points is quite relevant. 

If you are not just going to close all issues again I can put some effort in creating them one by one. But I don't see the advantage in that for you.

**Comment by Natherul** [comment]
Since there is nothing globally set for the career these are individual issues most likely (if an issue at all) in the DB having it all as one big ticket just makes it more of a nightmare to track whats fixed and whats not.

I just added this as a rule for bugtracking as well (and was surprised it was not already). 

Either way Im not here to insult at all, but again having a list of issues in the same ticket is not a way to do it, and as it is right now there is nothing on my table (code) thats wrong with these abilities as they are not hardcoded in any way.
