### ISSUE TITLE
quest : "time to rally"

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11018]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
invalid game object

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

![thorbolt_071](https://user-images.githubusercontent.com/16274785/34085188-c953dd92-e38c-11e7-92cc-f5a8ccbf7f38.jpg)

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
remember: destro quest is also broken!

**Comment by Ryanfawkez** [comment]
Quest discontinued. Best to throw it away.
