### ISSUE TITLE
Warrior Priest: Sigmar's Shield is back to pre-.ab changelist form

### ISSUE THREAD

**Issue by Rydiak** [WarEmu/WarBugs#11013]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Expected:  Sigmar's Shield lasts for 7 seconds, and drains 15 Righteous Fury per second.
Actual:  Sigmar's Shield lasts for 20 seconds, and drains 20 Righteous Fury PER EACH ATTACK received.

Steps to reproduce the problem:
Spec for Sigmar's Shield and use it on an enemy.  Watch your Righteous Fury drain instantly.

Screenshots/Videos or archive.org evidences:
https://i.imgur.com/8oOeFkz.jpg

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by eherenreich** [comment]
Its a joke! you cant even use salvation to regain RF if that shield is up and your takeing damage.

**Comment by Rydiak** [comment]
I just noticed that the 12/16/2017 patch reverted Sigmar's Shield back to AoR form, so this "Issue" should be closed.  That said, Sigmar's Shield is likely not worth speccing into anymore if you plan to use Divine Assault or any other form of Righteous Fury spender for the next 20 seconds.

**Comment by eherenreich** [comment]
This problem is still here on 17.12/2017
