### ISSUE TITLE
Witch Hunter Imperator set bonus not working

### ISSUE THREAD

**Issue by gomboni** [WarEmu/WarBugs#11012]
Expected behavior and actual behavior:
The 2 piece set bonus from the WH imperator bonus doesn't activate, it may have something to do with the name of the headpiece (Hat of the imperator of the imperator)

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
https://i.gyazo.com/dd47b8f0c8053c8681641f824d566e3e.png

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Torquemadra** [comment]
Works fine, typo doesnt effect though corrected next patch.

![wh_013 1](https://user-images.githubusercontent.com/16200780/34083004-dcf7bc3e-e336-11e7-9be3-635934535722.jpg)
