### ISSUE TITLE
HE Inf Reward, Ch20: KoTBS helmet - Pathfinder Casque

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#11021]
Model for the helmet appears in quite a wierd spot (in the character belly)
![shey_000](https://user-images.githubusercontent.com/18032193/34104641-9ef980be-e3f1-11e7-9508-e0ae699ef17b.jpg)

**Comment by szejoza** [comment]
Fixed as of now
![shey_001](https://user-images.githubusercontent.com/18032193/34162749-17b486c8-e4d5-11e7-84f3-d539d58ccdb2.jpg)

**Comment by sioding** [comment]
fixed with patch from 22.12.2017
