### ISSUE TITLE
Dragonwake dragon corpse

### ISSUE THREAD

**Issue by timoteiz** [WarEmu/WarBugs#11027]
Just outside the WC in dragon wake order site... at 9446, 31501 location

chalenge from IB can aggro teh dead mob and kill you.. in the mean tiem that dragon corpse can not be targeted.. 
![durrin_003](https://user-images.githubusercontent.com/34124804/34154511-67e7be6a-e4be-11e7-8bf4-1a4106c1ffa1.jpg)
![durrin_004](https://user-images.githubusercontent.com/34124804/34154522-700a17e6-e4be-11e7-857c-34947e8a317c.jpg)

**Comment by sioding** [comment]
fixed with patch from 9.2.2018
