### ISSUE TITLE
Massive Renown Award - Bug?

### ISSUE THREAD

**Issue by Rilof** [WarEmu/WarBugs#11020]
Today Dec. 18, 2017 @ about 8:10am (Asia) I was awarded about 26k renown for capturing Goblin Armory in Marshes of Madness.  I was with 2 other people.  I inquired if they receive the same effect but they did not respond.  I have included a picture which shows the other players with me and the renown gain.  I haven't seen any other post which includes this issue so here it is.

Rilof

![desktop screenshot 2017 12 18 - 08 08 11 83](https://user-images.githubusercontent.com/33287995/34086177-82f517a4-e3cc-11e7-98c9-d08e05a7d74f.png)

![desktop screenshot 2017 12 18 - 08 08 51 19](https://user-images.githubusercontent.com/33287995/34086188-970cf982-e3cc-11e7-91fb-f8c23956e35f.png)

**Comment by sioding** [comment]
This is a well known issue which occurs sometimes and the reason why we have implemented a max renown cap.
