### ISSUE TITLE
Access to guild vendor items above guild rank

### ISSUE THREAD

**Issue by Resteloin** [WarEmu/WarBugs#11026]
For a year and a half, I keep getting ejected from my guild everytime there is a new patch applied to the server (I saw other posts related to this).

However, while I am without guild, I can still use the guild recall scrolls I have on me to teleport to Sigmar's Hammer. While there, I saw that I can buy stuff from the guild vendor that would only be available to rank 40 guilds (while my previous guild is rank 23 and I am guildless).

For example, I can buy all the teleport scrolls (guild, gunbad, bastion stair, lost vale) and several level 150 crafting stuff.

![_guild bug](https://user-images.githubusercontent.com/11785962/34140065-33de1cb8-e446-11e7-9990-7ede8b9fb370.jpg)

Resteloin

**Comment by Natherul** [comment]
with next hotfix you should be ejected quite quickly from the guild places while not in a guild
