### ISSUE TITLE
PQ Glitternig Citadel, impossible to complete

### ISSUE THREAD

**Issue by Therielis** [WarEmu/WarBugs#11029]
In the last stage of the PQ Glittering Citadel (Etaine, DE ch22 Hard PQ) one of the 3 hero that must be killed to complete the stage (the one in the middle , sorry forgot to record the name ^^') spawn as a FRIENDLY nps rather than an ENEMY npc.

The pq was working fine until 3 days ago (16/12/17, that is the last time I completed it, don't know the exact timeframe when it bugged), but now every time you enter the last stage the NPC spawn as friendly.

Note that other npc for that stage (all the champions and the other 2 hero that the stage require you to kill) correctly spawn as ENEMY npc.

**Comment by sioding** [comment]
Sorry but the Ch22 hard PQ´s are not free to play with. The team is working on them and thats the reason why you can have those wierd situations like: yesterday they are working but now its.... meh. Please use other hard pq´s.
