### ISSUE TITLE
Lots of shooting hitting twice with high damage

### ISSUE THREAD

**Issue by s0undie** [WarEmu/WarBugs#11030]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
AOE moral for squig does 1.6k ae damage
Actual:
Hit twice for 2.4k

Steps to reproduce the problem:
Uncertain

Screenshots/Videos or archive.org evidences:
I have a screenshot if needed

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
More than one screenshot whith the combat log please.

**Comment by Torquemadra** [comment]
![untitled34](https://user-images.githubusercontent.com/16200780/34187391-1c255488-e4ff-11e7-908c-4176aceb6505.png)
