### ISSUE TITLE
The Siege of Anyerrial PQ (Eataine) not spawning final boss

### ISSUE THREAD

**Issue by baroke** [WarEmu/WarBugs#11031]
At stage III of Siege of Anyerrial PQ (Eataine), Lord Carathen Norithar should spawn, but he didn't.

I don't know if it happens all the time

![gogol_000](https://user-images.githubusercontent.com/20115114/34200150-b2e85478-e578-11e7-9033-96ff2e84e555.jpg)

**Comment by Lheana** [comment]
From last patch "- Order PQ 'The Siege of Anyerrial': Reworked the first stage; **Moved the last boss**".
Look at where the chest is on your map, the last boss will be there, on a cold one in front of a tent.
