### ISSUE TITLE
Order: ch 19 Thunder Mountain bugged bind point

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#11038]

**Comment by sioding** [comment]
Can we get more information than that? I´ve tried that on my chosen and everything is fine.

**Comment by Nfkillz** [comment]
ofc
https://clips.twitch.tv/AmericanCautiousDurianYouDontSay

**Comment by sioding** [comment]
ahh order ;) thx

**Comment by Nfkillz** [comment]
sorry for bad description

**Comment by sioding** [comment]
fixed with patch from 24.02.2018
