### ISSUE TITLE
Auction house: cant cancel auction

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#1103]
for some items you cant cancel your auction (here: Steelhelm of Woe). Example attached. Some others work. Error msg. in chat.

![tiggo_003](https://cloud.githubusercontent.com/assets/13809443/9309731/d51207ca-450b-11e5-8559-4b6ce6ee3760.jpg)

**Comment by chazzwozza** [comment]
i have the same issue

**Comment by Socratic85** [comment]
Got the same issue have auctions that are not mine. The thing is it only happened after i get my character name changed

**Comment by MaxHayman** [comment]
Will be fixed from next patch.

**Comment by Kaelang** [comment]
This should now be fixed. Please re-open if issue persists.
