### ISSUE TITLE
Banish Darkness tactics bug (Kotbs)

### ISSUE THREAD

**Issue by tiarnaz** [WarEmu/WarBugs#11037]
there is a bug with the Kotbs tactics BANISH DARKNESS, that modify the ability REPEL DARKNESS.

![image](https://user-images.githubusercontent.com/34770232/34298755-9c846048-e71f-11e7-98e9-0362eb0068f1.png)
this is the skill before apply the tactics

now i apply this tactics
![image](https://user-images.githubusercontent.com/34770232/34298797-cc0daeaa-e71f-11e7-9623-d5d04bc02813.png)

and this is the results
![image](https://user-images.githubusercontent.com/34770232/34298811-da015296-e71f-11e7-9ea9-85785a3758fb.png)

now the point is,  the knockback work well, and the tooltip say 10s cooldown (the correct value), BUT
when i use the ability the cooldown isnt 10s, but is 20s like before.

i test this with other knight of the blazing sun, and all have the same issue.

please fix this, thanks in advance.

**Comment by sioding** [comment]
Are you using a great weapon?
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=23117#p258569

**Comment by tiarnaz** [comment]
not, i use 1hand/shield.

then this "bug" is a dev change, sorry i see this patch notes now for the first time.

think you can close my post, but aniway dont understand the reason of this change :( 
ty.
