### ISSUE TITLE
New XP Cap stops player getting xp

### ISSUE THREAD

**Issue by fesust** [WarEmu/WarBugs#11032]
Expected behavior and actual behavior:
If a bolstered player spends a few hours in the RVR lake with an objective-oriented warband (capping bos, attacking/defending keeps) and the zone locks 0 xp will be gained as a reward, due to the new xp cap system.

Screenshots/Videos or archive.org evidences:
https://i.imgur.com/p7ijh26.jpg - Chat window, with the xp cap message
https://i.imgur.com/POrajCa.jpg - Combat log showing no xp was given for the lock

**Comment by sioding** [comment]
Thats the way it should work.

**Comment by fesust** [comment]
I need 565000 xp for gaining a level at that rank. How is 112000 too much for 4 hours of doing RVR?
I think the code needs a bit of work. If I guess correctly the current xp cap is a static number, instead of a dynamic cap considering the players rank.

**Comment by sioding** [comment]
Use your thread: https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=24427
