### ISSUE TITLE
Strange Skarsnik bug

### ISSUE THREAD

**Issue by Harkanor** [WarEmu/WarBugs#11036]
Hi, got a really strange bug with my sorcerer Uhran.
I was riding on my horse in IC and at location approx 36K/41K, i gor the Skarsnik mob riding with me on my horse. 2 sec later i got a CTD so no time to take a pic.
My main Char is Harkanor. Sorcerer Uhran a reroll only.

**Comment by sioding** [comment]
Sounds like a one timer - which is not reproducable.
