### ISSUE TITLE
You die after entering isle of the dead (same as gunbad)

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11041]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Fixed with patch from 29.12.2017
