### ISSUE TITLE
Trouble logging in / loss of all tab 1 items in backpack

### ISSUE THREAD

**Issue by maciaveli** [WarEmu/WarBugs#11045]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Lots of disconnect/fail to log in issues all of a sudden this PM (AM was fine)
On one disconnect (while playing Bitezyerass - destro/squiggy) I noticed that when I finally managed to get back in my backpack (tab 1) was empty of everything - mount, potions loot etc...

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Kaelang** [comment]
Appreciate this is an older report - however the lack of information here makes this almost impossible to replicate without having to guess what this report is for. Please re-open with more information if this issue persists.

Closing.
