### ISSUE TITLE
Realm Points from kills:Not being divided equally between all attackers.

### ISSUE THREAD

**Issue by Reoddry** [WarEmu/WarBugs#1104]
Not sure how much of a priority it will be due to no realm abilities at the moment.  I have noticed when fighting in RVR and scenarios that the only people who receive realm points for the kills are the person who gets the killing blow and that person's group. Just wanted to give a heads up, so it can be worked on before realm abilities are brought into the game. Also, this seems to work on all classes vs any other classes, on both realms.

**Comment by Evildoor** [comment]
This was fixed for the most part - i received rewards for others' killing blows while running solo in RVR. In scenarios the only case when rewards are not divided equally is when someone enters no party at all - i do believe it was this way on live, but i'm not sure that it should stay this way if we can help it. Other question is - can we?

**Comment by Evildoor** [comment]
Fix for out of party kill stealers was implemented. closing.
