### ISSUE TITLE
quest: three names for the fire

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#11048]
the quest is completed speaking to the same named npc in Praag in Southern Breach wc.
![gabri_220](https://user-images.githubusercontent.com/17765890/34325151-51019d2c-e88a-11e7-80d1-feccbbf0052a.jpg)
seems similar to  #10959

**Comment by Lheana** [comment]
Fixed next patch. This quest will now be completed by talking to the correct Lord Xyshrenth. I also removed the uncorrect quest marker in Praag, and this NPC will now be the giver of this quest chain.

**Comment by sioding** [comment]
Fixed with patch from 29.12.2017
