### ISSUE TITLE
Choppa Morale 1:"Dat Tickles"-bugged

### ISSUE THREAD

**Issue by GK111** [WarEmu/WarBugs#11047]
m1 "Dat Tickles" should absorb 3600dmg
proof:
![m1-1](https://user-images.githubusercontent.com/24727277/34323438-044c1424-e85a-11e7-9703-27b94ad8d5f5.png)

on practice absorb much less:
![m1](https://user-images.githubusercontent.com/24727277/34323439-231551cc-e85a-11e7-8b5b-16c25495043e.png)

**Comment by Torquemadra** [comment]
it doesnt count dots in combat log
