### ISSUE TITLE
Tok isle of dead wrong unlock with mob : "living armor"

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11049]
I killed 100 living armor and I didn't get the unlock but I gain the title : "anyone have a can opener"
![thorbolt_073](https://user-images.githubusercontent.com/16274785/34328094-a0bb45d4-e8d5-11e7-88f1-71ac7ba859c8.jpg)

**Comment by Lheana** [comment]
Thanks for reporting it, fixed next patch. I advice you not to try to do the other kill unlocks for Living Armor until next patch as there were other errors that I also corrected.

**Comment by sioding** [comment]
Fixed with patch from 29.12.2017
