### ISSUE TITLE
Cant enter world with main character

### ISSUE THREAD

**Issue by smauhg** [WarEmu/WarBugs#11059]
Expected behavior and actual behavior: 
- getting past loadscreen but getting thrown back to character selection

Steps to reproduce the problem:
- happens everytime i try to enter the world

Hello, 2 days ago i was thrown to character selection during the loadscreen for a scenario. 
After that every time i try to log in with my SH (name:"Ulumulu") i can see the loading screen and am thrown back to character selection before i appear in the world.

After 10-15 restarts and relog attempts (with cleared cache and unstuck during loadscreen) i could log on and play for a while but suddenly after taking a flight point i was thrown back to character selection again and couldnt play for hours.

This happened like 7 times in the past 2 days while i currently cant get it back working (trying since almost 2hours on and off :/ ). 

I tried it on 2 PCs, same problem. All other characters work perfectly fine!

Thanks in advance

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Please try double /stuck while the loading screen is visible.

**Comment by smauhg** [comment]
already doing that, its the only way to get it working again. Even then it takes around 30-90min until i have success.

I could log on 10mins ago but the first flight i took threw me back to character loading screen and iam stuck there again now

**Comment by sioding** [comment]
ok a last try: remove the profile which is linked to that character and create a new one ( yes i know it sucks and its a lot of work ) but really remove it (or rename it first)

**Comment by smauhg** [comment]
made a backup and removed the whole profile folder. 
Sadly the bug still persists :/

**Comment by wargrimnir** [comment]
Dump your excess quests. I see 57 active ones in your book. Having more than 20 generally causes issues.

**Comment by smauhg** [comment]
I could enter the world 15mins ago. All my gear and backpack slots were empty, It showed 0/0 exp (lvl23) but i could dump my whole Q book.

Problem occured again when I tried to relog. Anyway i got back in the world, had my gear back and still an empty Qlog. 
Tried to use a flight point (diff one) and I am back to character selection... stuck again.

**Comment by wargrimnir** [comment]
I see you only have 6 currently. That's different. Issue resolved?

**Comment by smauhg** [comment]
Nope, I could actually play and use flight points for the past hour. 
But 10min ago I had to relog and again i couldnt enter the world without getting thrown back to character selection after the loadscreen

**Comment by gorrtoof** [comment]
Im having the exact samr issue execpt its with two of my chars Gorrtoof and Bigwaka both orks my white lion char no issues

**Comment by Kaelang** [comment]
I appreciate this is a dated report - that being said, there's been a myriad of changes and upgrades since 2017 and there haven't been any similar reports of this happening anymore. The team commented and were unable to replicate this issue back in 2017.

If you are still experience these problems, playing RoR in 2020. Please feel free to reply and I will reopen this report.

For now, I'm going to close this as I work through the backlog.

Thanks.
