### ISSUE TITLE
Stuck after being shot by Repel Darkness (KOTBS)

### ISSUE THREAD

**Issue by mbanane** [WarEmu/WarBugs#11055]
Hi, like to report some episode happens to me yesterday.
Playing my Kotbs in Ellyrion, near BO usually called "stabbles".
Spotted a Squig Herder on the top of the hill.
I got in his back, was mounted and used Repel Darkness aiming throwing down the hill.

**Expected behavior:**
Used Repel Darkness on goblin, goblin should fly a little and fall.
**Actual behavior:**
Goblin disapeared and accuse me of cheating as it seems he was stuck and couldn't move.

**Steps to reproduce the problem:**
Really don't know how to reproduce, have done this for a long time now, never have this issue. But i promise i will keep shooting goblins from hills.

**Screenshots/Videos or archive.org evidences:**
No evidence here, i only have a screenshot of my chat arguing with this angry Gobelin i'm not a cheater.
Will post names and chat if asked.

Thank you!

**Comment by sioding** [comment]
Thanks for the report, but if we can not reproduce it - we call it a noe-timer. Sometime weird things happens - and i understand you wanna report it as a some kind of  a evidence but we can not do anything on this in special.
