### ISSUE TITLE
[Item] A Festive Treat

### ISSUE THREAD

**Issue by Tyramissoux** [WarEmu/WarBugs#11058]
- Expected behavior and actual behavior:
Expected: Shouldn't be useable when cooldown is shown on item and item was used within last 60 min.
Actual: Can be used when cooldown is showing under certain circumstances.

- Steps to reproduce the problem:
Joining an SC seems to internally reset the CD. Had the potion active (--> was a pig) when I entered a SC. Left SC, stood in IC and clicked out of boredom onto item in backpack showing the CD --> turned into pig. Reproduced this and it worked again.
Cherry on top:  Additionally, it also worked when in SC with CD. 

Summed up: Used before SC, was able to use it inside SC and after SC all in the span of about 15 min --> 3x pig.

Cooldown is not broken for me otherwise. Only in context of SCs.

-Screenshots/Videos or archive.org evidences:
None. If wished for, I can record a video.

**Comment by sioding** [comment]
#11051

**Comment by sioding** [comment]
i merge this one with the 11051

**Comment by sioding** [comment]
Fixed with patch from 29.12.2017
