### ISSUE TITLE
Isle of dead. Quest name : gathering storm

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11064]
No chest of Althanis inside the red circle quest mark. So you can't finish the quest.
![thorbolt_047](https://user-images.githubusercontent.com/16274785/34404037-13c94c3c-ebac-11e7-92af-76591b7df58b.jpg)

**Comment by sioding** [comment]
Fixed with patch from 26.01.2017

**Comment by sioding** [comment]
just reopened this one - the questmarker for this one is wrong

**Comment by sioding** [comment]
questmarkers fine now

**Comment by sioding** [comment]
Fixed with patch from 2.2.2018
