### ISSUE TITLE
Guild has disappeared

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#11067]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Yesterday we made a new guild called HAVOC, today I login and it has disappeared. I logged in with some alts but also on alts the guild is gone

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
I assume you´ve created the guild before the crash yesterday? Just create your guild again. If the server crashes it does not save everything as it does when it went down in a proper way.

**Comment by wiscel** [comment]
Ah ok, thank you for the info. Will try again.
