### ISSUE TITLE
Potion of acclaim

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#11069]
Dont work for rp from sc (Black Fire Basin)

**Comment by sioding** [comment]
Can you please add a screenshot ?

**Comment by MKorin** [comment]
![scrr](https://user-images.githubusercontent.com/13823154/34440749-a16c718e-ecb7-11e7-958f-638676f604e2.jpg)

**Comment by sioding** [comment]
![image](https://user-images.githubusercontent.com/18517842/34442534-08494a70-ecc3-11e7-9165-987094a528a6.png)

**Comment by zak68** [comment]
doesn't work with renown gained by holding bos either.
in praag with 2 bos: 16 points per tick, using potion still 16 points. Relogged but nothing changed.

**Comment by sioding** [comment]
fixed with patch from 09.03.2018
