### ISSUE TITLE
Isle of dead. Quest name : a shattered peace

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11066]
No shyish crytsal inside red circle. You got one near red circle but when you click on it or try to attack there is no effect.
![thorbolt_052](https://user-images.githubusercontent.com/16274785/34404473-1ae81014-ebae-11e7-94b3-cc98803a7cb6.jpg)

**Comment by thorbolt80** [comment]
![thorbolt_088](https://user-images.githubusercontent.com/16274785/35047112-493ebe5e-fb99-11e7-964c-8252bf1ee56b.jpg)

This one isn't working

**Comment by sioding** [comment]
fixed with patch from 2.3.2018
