### ISSUE TITLE
Isle of dead. Quest name : legacy of the drakecaller

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11065]
No scrying pool inside or near red circle 
![thorbolt_049](https://user-images.githubusercontent.com/16274785/34404237-f237f414-ebac-11e7-9e12-09779922fe25.jpg)
so you can't finish the quest

**Comment by Lindvior84** [comment]
Pool is at 43397, 34402 (just found it now) but it is out of the red area (a lil bit under it on the right)

**Comment by thorbolt80** [comment]
So the quest is working you just have to change the red mark circle slighly more towards south

**Comment by sioding** [comment]
fixed with patch from 2.3.2018
