### ISSUE TITLE
Bastion Stair?

### ISSUE THREAD

**Issue by CeeJay89** [WarEmu/WarBugs#11063]
I don't know whether this is an intended location at this time, however, it can be accessed right now, has two R39-40 Heroes, and is loaded with R37-39 Champions. As I understand, it is a dungeon from live, but we obviously don't have it yet. I stumbled across it while finding mobs that could be butchered.

It can be accessed from Chaos Wastes **64.5k, 60.8k**, and is also bugged.

You can respawn an infinite number of times. When you die you hit respawn, you wait 5 seconds, and you respawn at the exact location you died. 

Mobs are pretty consistent on their drops. I can not kill the Heroes by my little Engineer lonesome, so I have no idea if they drop anything of significance. There is a Destruction healer at the entrance, as well as a mailbox, which suggests to me that perhaps the dev team is testing stuff here? I don't know, anyways, may be significant.

I have included a screenshot of the entrance, and a video showing the bug, some of the mobs, one hero and the location.

As a final note, you can not leave through the portal. The only way to exit is by using your Book of Binding, and I assume(?) /stuck x2

![fusilli_019](https://user-images.githubusercontent.com/25260106/34401667-9812e224-eb6a-11e7-863a-0fe7424f0932.jpg)

Video: https://www.youtube.com/watch?v=Uwe7azq2RNo&feature=youtu.be

**Comment by thorbolt80** [comment]
Confirm. I think devs should close the area as it's not normally not available inside the game.

**Comment by sioding** [comment]
Thx for the report. will be fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 29.12.2017
