### ISSUE TITLE
Instadeath code from river of mortis?

### ISSUE THREAD

**Issue by Nastylicious** [WarEmu/WarBugs#11061]
so i was flying to Talabecland and this message was trigged and i got oneshot by something 
so i think you should have the screenshot like it said in the message :) 

![ammeliaa_000](https://user-images.githubusercontent.com/14811125/34393333-f10adad0-eb51-11e7-9dcf-a47a17863406.jpg)

**Comment by Natherul** [comment]
interesting, thanks for the report. Considering how long that has been in now I would right now label this as a freak accident where your client either sent a packet malformed or it was corrupted en route to the server. Either way closing this down for now, if it happens more Ill def look into it more. (this is the first report for code that has to be older then 6 months)
