### ISSUE TITLE
MailBug and Capped RR Bug

### ISSUE THREAD

**Issue by Enrow** [WarEmu/WarBugs#11070]
Hey, Today i had 2 different bugs,
The first one were that i fighted in Ostland with 400% Aao had a nice keep deff afterwards i took the morr BO  and then in chat stand : That i got over 40k rr and i will get the capped maximum from the rr ,but i did not got the 40k rr from the bo deftick .

The second one is that i got an gold bag today in praag and it hasn´t been send per mail even after 5-8hours 
-When you got more questions ask me ingame pls   -Shirao

**Comment by sioding** [comment]
Hey,

thanks for the report. for your first issue is already an open report: #11053.
For the second: Wait until server restart.

For the future: Please do not report two things in one report and use the search function maybe another one reported it before.
