### ISSUE TITLE
Engineer Gun Turret

### ISSUE THREAD

**Issue by Glomzorn** [WarEmu/WarBugs#11076]
The Machine Gun skill isnt dealing any dmg, the animation goes of but it doesnt deal dmg. 

so does the armor dbuff,animation goes of, dbuff gets added but no dmg in the combat log/on screen.

also check the stats on the armor debuff it says 24. not sure how much it actually is.

Using Loyal Pet AddOn. 

cheers Glomzorn

**Comment by sioding** [comment]
Screenshots out aof your combat log please. And make sure your filter shows Pet Damage and Pet Hits.

**Comment by Glomzorn** [comment]
ah nvm now it seems to work again, dont know what it whas, just deals only 10 dmg tho :dagger:
