### ISSUE TITLE
Talisman making with 150 skill blue "Howling Russet Core" and 150 relic box "Fabricated Artisan's Relic Box"

### ISSUE THREAD

**Issue by Zdaemon214** [WarEmu/WarBugs#11079]
Expected behavior and actual behavior:
    Using said fragment "Howling Russet Core" with the "Fabricated Artisan's Relic Box" causes the fragment to be unable to be placed into the talisman crafting screen, preventing my ability to make the talisman with the said fragment and relic box. If I instead use a "Apprentice's Relic Box" the crafting screen works fine and I am able to complete making the talisman.

Steps to reproduce the problem:
1: Open Talisman making screen
2: Right Click or click and drag "Fabricated Artisan's Relic Box" to Talisman making screen.
3: Right Click or click and drag "Howling Russet Core" to Talisman making screen.
4: You then cannot add any other curios/essence/gold dust or click the "Fuse!" button only "Clear" works at this point.

**Comment by sioding** [comment]
Already fixed
