### ISSUE TITLE
Can't Get Into Game

### ISSUE THREAD

**Issue by Itmritual** [WarEmu/WarBugs#11073]
Sp yesterday I tried making a new character but then changed my mind and never pressed create. I then tried to play one of my characters but the play button went white. I then logged out and canceled the screen and went back  to log in. After I went onto the log in tab, the Web Server is red and the Login Server is yellow. I quit out of that screen and waited for the game to patch/update and I did. It updated this morning but it still shows up as red and yellow and I can't log in. 

Account: Itm4life

**Comment by sioding** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=2&t=24546
