### ISSUE TITLE
Quest: Ransacked Vale, supplies bugged

### ISSUE THREAD

**Issue by krillep** [WarEmu/WarBugs#11077]
Expected behavior: Pick up supplies
Actual behavior: Untargetable or missing, unsure, maybe replaced by the nearby Public Quest supplies?

Steps to reproduce the problem: None.

Video of the bug: https://www.youtube.com/watch?v=mAzdWGplB3E&feature=youtu.be

**Comment by sioding** [comment]
Fixed with patch from 6.1.2018
