### ISSUE TITLE
Khorgash Damage Bug?

### ISSUE THREAD

**Issue by Manatikik** [WarEmu/WarBugs#11071]
Tonight we had a guild group trying to kill Khorgash and he was hitting waaay harder than usual (have tanked him on the same SM twice before without any issue.) He was using Bestial Flurry about every 5 seconds and was hitting 5 times a cycle (so ~10k damage in 1.5 seconds). Taunt would interrupt it but can't interrupt something every 5 seconds. Think its just glitched (or you guys REALLY made him harder to kill :D )

Combat log of his damage (was cross guarded by an IB who claimed to take 9k guard damage in 1 second as well)

![khorgash](https://user-images.githubusercontent.com/19319894/34432524-47ff0fb2-ec35-11e7-8254-b9a8d0fa7fae.png)

**Comment by sioding** [comment]
Just made him today - no problem with two tanks - so i will close this here.
