### ISSUE TITLE
Instructor's boon not reducing XP in SC rewards

### ISSUE THREAD

**Issue by Elykz** [WarEmu/WarBugs#11086]
Expected behavior and actual behavior:
Instructor's boon buff should reduce XP by 75% in SC
SC reward seems to be unchanged by the Instructor's boon buff

Steps to reproduce the problem:
- Use boon Instuctor's boon potion
- Win a SC
- The reward seems to be full XP and not reduced by 75%

**Comment by Natherul** [comment]
fixed with next patch
