### ISSUE TITLE
Missing Basic Influence Reward - Empire Ch. 10

### ISSUE THREAD

**Issue by krillep** [WarEmu/WarBugs#11080]
Expected behavior: Reward for Basic Influence
Actual behavior: Reward tier missing

Steps to reproduce the problem: None

Screenshot evidence: https://i.imgur.com/TjzI4ts.jpg

EDIT: Sorry, didn't see this was already on here, didn't search for enough different terms.

**Comment by krillep** [comment]
Sorry, didn't see this was already on here, didn't search for enough different terms.

**Comment by thorbolt80** [comment]
Already report see #9994

**Comment by sioding** [comment]
And thx again @thorbolt80
