### ISSUE TITLE
No bag received after zone lock

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#11081]
Today, jan 1st 2018 Praag zone was locked in ~ 18:00 (Moscow day time) 
At this moment I was in the scenario (Howling Gorge) and got a message, that I won a Lesser loot bag
When scenario was ended and I returned back to the Praag zone, I've seen a messages in the region chat, that ppl already recieved their bags.
I've checked a mail and seen nothing. 
Dunno is it related to being on the scenario at the moment of lock or not.

Character name: Bestial (WE 25 lvl)

**Comment by sioding** [comment]
Wait fpr the server restart.
