### ISSUE TITLE
Nurglings quest empire chapter 4

### ISSUE THREAD

**Issue by Dra3gm** [WarEmu/WarBugs#11084]
So today i was trying to do the nurglings quest so i can receive the reward that means a lvl 7 jewelry and i killed nurglings but nothing happens
![tallbott_000](https://user-images.githubusercontent.com/34137217/34491480-4302f838-efec-11e7-9de7-cb7eea560798.jpg)
![tallbott_001](https://user-images.githubusercontent.com/34137217/34491481-432585ec-efec-11e7-9692-e7ef7b161ee7.jpg)
![tallbott_002](https://user-images.githubusercontent.com/34137217/34491482-43466280-efec-11e7-84ef-9fc1ceb1844b.jpg)
![tallbott_003](https://user-images.githubusercontent.com/34137217/34491483-4363b2e0-efec-11e7-871a-83c553ce075f.jpg)
![tallbott_004](https://user-images.githubusercontent.com/34137217/34491484-438242b4-efec-11e7-809a-f1a1e8c8677c.jpg)
![tallbott_005](https://user-images.githubusercontent.com/34137217/34491485-43a056c8-efec-11e7-9d34-d2bab85642fb.jpg)

**Comment by Lheana** [comment]
Thanks for report. Fixed next patch.

**Comment by sioding** [comment]
Fixed with patch from 6.1.2018
