### ISSUE TITLE
Mob: Magi Destroyer, double spawn at Cult of the Magus PQ

### ISSUE THREAD

**Issue by krillep** [WarEmu/WarBugs#11082]
Expected behavior: Single spawn
Actual behavior: Double spawn

Steps to reproduce the problem: None

Video evidence: https://www.youtube.com/watch?v=Y4LmfsVJKmI&feature=youtu.be

**Comment by Lheana** [comment]
There were several double spawns in this PQ, I have already corrected it yesterday, so will be fixed next patch :)

**Comment by sioding** [comment]
Fixed with patch from 6.1.2018
