### ISSUE TITLE
Daemonic Contract, Magus tactic

### ISSUE THREAD

**Issue by panodill** [WarEmu/WarBugs#11085]
**Expected behavior and actual behavior:**
Should Increase damage when target is within 45ft.
Does not increase damage on dots, only direct damage

**Steps to reproduce the problem:**
dot up target with tactic. remove tactic and then dot up same target

**Screenshots/Videos or archive.org evidences:**
https://youtu.be/DcTJOd4MWWc

**Comment by thorbolt80** [comment]
It's the same for engineer?

**Comment by panodill** [comment]
A friend tested on Squig Herder tactic Sneaky Stabbin. also same problem, only increase direct damage.

**Comment by Neutrinoo** [comment]
Fix this please.

**Comment by grunbag** [comment]
Fixed already
