### ISSUE TITLE
Missing Apperance Wraith's Kladgird

### ISSUE THREAD

**Issue by FearTheGriff** [WarEmu/WarBugs#11093]
The Ironbreaker belt item "Wraith's Kladgird" has no apperance

**Comment by sioding** [comment]
Screenshots please.. With/Without belt.

**Comment by FearTheGriff** [comment]
https://imgur.com/a/h1dbD

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
