### ISSUE TITLE
Quest - Orky Vandalism, Black Fire Pass, GS Campain

### ISSUE THREAD

**Issue by Grunbeast** [WarEmu/WarBugs#11095]
Quest objective "Cannons Crippled" is impossible to complete, can not interact with cannons.

**Comment by g4USA** [comment]
Quest is still broken. 
Cannons Crippled still 0/2 even when clicking on cannons:
![qew 1](https://user-images.githubusercontent.com/29905200/39849077-2e7bfd20-53fa-11e8-93e0-3c05f669598d.jpg)
![qew 2](https://user-images.githubusercontent.com/29905200/39849083-31328886-53fa-11e8-921a-a5af2a69beae.jpg)
![qew 3](https://user-images.githubusercontent.com/29905200/39849085-332d49d2-53fa-11e8-81f7-e85b2e483220.jpg)
![qew 4](https://user-images.githubusercontent.com/29905200/39849086-34d00aea-53fa-11e8-93e1-9adb075a38f2.jpg)

**Comment by sioding** [comment]
Complete freaked out questmarkers. Removed them all and set them again. Now you will find the right cannons and the other stuff to complete the quest. fixed next patch.

**Comment by sioding** [comment]
fixed with patch from 09.06.2018

**Comment by cyric013** [comment]
Still not working on 14/08/2018

**Comment by cyric013** [comment]
![image](https://user-images.githubusercontent.com/35191469/44076215-a1928982-9f9f-11e8-8e64-f84b699dd0da.png)

**Comment by sioding** [comment]
wrong cannons - follow the questmarker
