### ISSUE TITLE
.getstats don't work on your own pet

### ISSUE THREAD

**Issue by Mausini** [WarEmu/WarBugs#11091]
Expected behavior:
.getstats should show the stats of your own pet

Actual behavior:
.getstats gives you the answer that only GM are allowed to use .getstats on other players

Steps to reproduce the problem:
Use .getstats on your own pet

**Comment by Torquemadra** [comment]
that means only GM are allowed to use getstats on your pet, working as intended.

**Comment by Mausini** [comment]
According to the patchnotes from 4/11/2017 .getstats should work on your own pets.
Didn't found any later patchnotes that reverted this functionality

In the following is the imprtant part of the mentioned patchnotes

Secrets
-Fixed an issue where White Lion pets were having too much of a stat when overrides were used.
-Fixed the killswitch for White Lion pet overrides.
**-The .getstats command can be used on your own pet now.**
-Inspecting a player will now send relevant info about the set that an item in the inspect window may contain.
-Skills that scale off of Toughness or Wounds will now use reduced crit chance as crit chance (only applies to WL's leonine frenzy)
