### ISSUE TITLE
PVE NPC's in the World don't use spells

### ISSUE THREAD

**Issue by cooler-SAI** [WarEmu/WarBugs#11094]
Expected behavior and actual behavior:
most NPC's in the world doesn't cast any spells, only melee attacks

Steps to reproduce the problem:
Create Empire character, go attack Chaos Mages on the Chapter 1, they attack only melee, but must cast spells

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Known issue.
