### ISSUE TITLE
CH22 Dwarf Slayer Inf Reward Missing Skin

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#11097]
Chargers
![sheykis_000](https://user-images.githubusercontent.com/18032193/34620146-c091baa0-f244-11e7-9341-e3ccae396856.jpg)
 of the Slayer are missing skin (influence reward from chapter 22 dwarfs - black crag)

**Comment by NorKalli** [comment]
assigned blue level 35 appearance

**Comment by NorKalli** [comment]
![image](https://user-images.githubusercontent.com/19868634/39671468-bc970dfa-50cd-11e8-8214-48d494735803.png)

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
