### ISSUE TITLE
SW Double Initiative Debuff doesnt work if Target has less than 180 initial Initiative

### ISSUE THREAD

**Issue by DiodosXoX** [WarEmu/WarBugs#11096]
Expected behavior and actual behavior:
Conq debuff 100 Initiative + Wrist Slash tactic debuff 80 Initiative = 180 Initiative (that works).
If target has below 180 initial Initiative, default value should be set to 0. It doesnt even show up in getstats anymore. So I guess it goes down to minus value and the debuff doesnt work at all.

DoK in Video had first 174 Initiave, after double debuff getstats doesnt show anymore a value and I was not really able to crit the DoK in the video.
DoK in Videos 2nd part had 200 Initiative, after Double debuff getstats showed 20 Initiative (as it should be) and Im critting the DoK as expected.

Steps to reproduce the problem:
Find any player which can reproduce an Initiative value below and above 180, you need a SW with 5x piece Conq and the wrist slash tactic.

Screenshots/Videos or archive.org evidences:
https://www.youtube.com/watch?v=uJnmSqqvYsM

**Comment by Pxl555** [comment]
From a small test i did , it would seem that if a target drops to 0 initiative it becomes immune to crit's regardless if it comes from its low initiative or the attackers chance to crit.

 If i recall the formula for initiative was taken from old wiki  - 
[(Level * 7.5 + 50) / 10] / Initiative = base % to be critically hit. 
Could be a case of the system going weird while attempting to divide by 0.

**Comment by Natherul** [comment]
fixed in the next patch
