### ISSUE TITLE
Mail Icon on Minimap doesnt vanish after deleting mails

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#1109]
the mail icon on the minimap stays even after visiting mailbox
and deleting all mails. exiting game and restart fixes it.

**Comment by Tiggonos** [comment]
this is actually only with auction house mails. when opening and deleting "normal mails" the icon disapears. so it looks like auction house mails are not deleted properly.

**Comment by Stefanosgr18** [comment]
![war 2015-12-22 10-40-00-78](https://cloud.githubusercontent.com/assets/16375224/11951572/ae195856-a89a-11e5-9180-55e4e7074057.jpg)

**Comment by dalen** [comment]
This was fixed in a recent patch.
