### ISSUE TITLE
Greenskins CH10 - PQ Gassy Mines in Black Fire Pass

### ISSUE THREAD

**Issue by Grunbeast** [WarEmu/WarBugs#11099]
Can not destroy 20/20 Mining Supplies. Only 18 crates spawn in PQ area and they do not respawn after destruction.

**Comment by Lheana** [comment]
Thanks for report. There are 19 in fact, but I reduced the required kill to 15.

**Comment by sioding** [comment]
Fixed with patch from 13.1.2018
