### ISSUE TITLE
Focus of the Subjugator - wrong bonus

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#11092]
This is a Zealot's offhand item, that have absolutely strange bonus on it:
_On being hit: 2% chance attacker is impaled for 360 damage._
![war 2018-01-04 18-19-14-143](https://user-images.githubusercontent.com/16439840/34570746-be33741e-f17d-11e7-8c17-0a2443706949.jpg)

Zealot - is a support class. His offhand end-game(!) weapon must have somthing from this:
On being hit: X% chance to increase wounds by XX for X sec
On being hit: X% chance to increase movement speed by XX for X sec
On defense: X% chance to increase dodge, disrupt and parry rate by X% for X sec
On being hit: X% chance to form a protective barrier, absorbing XXX damage for X sec

**Comment by Nfkillz** [comment]
good proc to interrupt detaunt

**Comment by sioding** [comment]
Well - this is not a bug. This is a working item. You think it would be better to have another proc - which is more a suggestion than a bugreport.. But i will try to get an information about it.

**Comment by sioding** [comment]
Well @SilverWF  - the bugtracker is not your new forum account. Close
