### ISSUE TITLE
oppression+armur pop(chosen)

### ISSUE THREAD

**Issue by blaksoso** [WarEmu/WarBugs#11100]
Issue : Armor pots + Chosen ability "Opression" (A thunderous shield slam that inficts XXX damage,increases your amor by XXX for 20 second and reduces your damage taken by 15 % for 10 second)
Effect : Only armor points given bye ability proc > of the armor pot i use are counted. It doesn't stack with armor pots, and makes the ability not very usefull.

br hillusion 

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
This is working as intended - if you want to change this start a proposal in our forum. Sorry but its not a bug if you feel an ability is not as useful as you would like it to have. But use your chance and start a proposal: https://www.returnofreckoning.com/forum/viewforum.php?f=95
