### ISSUE TITLE
Stay on top of the flag from Gateswitch

### ISSUE THREAD

**Issue by Astrador** [WarEmu/WarBugs#11105]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
If u get punted to the Flag of the gateswitch in scenario Gates of Erkrund u shouldnt be able to stand on top of it 

Steps to reproduce the problem:

Punt someone from the balcony in direktion of the flag  from gateswitch happend in my last scenario, just accidential punted a zealot away and he was then not reachable by normal means

Screenshots/Videos or archive.org evidences:

sry forgot to take screenshot

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
As far as i know - it was the same on the old live servers.
