### ISSUE TITLE
Subjugator Cloak Cleanse

### ISSUE THREAD

**Issue by Lifebane** [WarEmu/WarBugs#11107]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
On "use" the [Subjugator's Greatcloak] fails to cleanse the Witch Hunter ability [Burn Away Lies] which is listed as an Ailment per the RoR career builder. It cleanse everything except for that.

Steps to reproduce the problem:
Have a Witch Hunter apply the ability to you and use the cloak.

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Torquemadra** [comment]
tested and it works fine, you need to make sure you have no other ailments on you such as sudden accusation (wh opener, also ailment) as its ONE ailment ONE curse and ONE hex.
