### ISSUE TITLE
Gunbad instance boss : wipe and respawn into a glitched instance

### ISSUE THREAD

**Issue by rekkir** [WarEmu/WarBugs#11104]
When we wipe on the instance boss of the left or right wing in Gunbad(haven't reached mid instance boss yet) and release we are ported outside the boss room in a glitched instance. There we find a reset PQ even though we cleared it before the instance boss and it should actually have an 8 h lockout timer, also there are no friendly NPC's like a healer or quest mobs. 

To solve this we die and spawn backwards until we reach the entrance (where there are also no NPC's) then re-enter or book out and re-enter the instance. The key to getting back into your own unbugged instance is by re-entering the dungeon. After you do this and ride back to enter the boss room your healers can now ress during the boss fight and possibly some mechanics from boss disappear aswell.

**Comment by Hargrim** [comment]
Try to relog and the leader should get back first to the instance.

**Comment by rekkir** [comment]
will do ! Thx for the swift reply

**Comment by Zdaemon214** [comment]
This happened to us on Solithex and Ard Ta Feed as well. Didn't get to try relogging after the wipes. Ard Ta Feed wipes still had access to the portal, but the Solithex portal had a wall in front of it.

**Comment by Tesq** [comment]
happened to me too in left wing,  wipe at last boss and relogged in a bug/istance with no healer and  pq resetted, then several problem and /stuck attemp to re-enter in game

**Comment by sioding** [comment]
Fixed with patch from 26.01.2017
