### ISSUE TITLE
Unshakable Focus Shadow warrior

### ISSUE THREAD

**Issue by Thehamrider** [WarEmu/WarBugs#11106]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: I should be able to purchase and use the ability "Unshakable Focus" from a career merchant. When i try and purchase it i get the message "This ability is not implemented"

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Torquemadra** [comment]
Removed from game as per balance decision.
