### ISSUE TITLE
Moonfang Remnant Order PQ

### ISSUE THREAD

**Issue by cyric013** [WarEmu/WarBugs#11102]
Expected behavior and actual behavior:
The second part of the PQ don't work, the player is expected to collect/kill Moonfang Skitterer and there is nothing like that to be seen.
The description of the PQ said :
![kruncki_000](https://user-images.githubusercontent.com/35191469/34649153-979ef3b8-f3a9-11e7-9f59-cbc311996d57.jpg)
But you can't use the banner and if you destroy one you didn't get any Moonfang Skitterer Completion.

Steps to reproduce the problem:
Complet the PQ stage 1

Screenshots/Videos or archive.org evidences:
![kruncki_000](https://user-images.githubusercontent.com/35191469/34649153-979ef3b8-f3a9-11e7-9f59-cbc311996d57.jpg)

I hope this issue isn't already reported and thanks you for all the great work you're doing !
Plus i wish all of you an great 2018 year.

**Comment by sioding** [comment]
Fixed with patch from 2.2.2018
