### ISSUE TITLE
RVR Quest Bug

### ISSUE THREAD

**Issue by Prumbai** [WarEmu/WarBugs#11103]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
I got a quest from keep lord in one of the RVR areas which says me to kill 25 people. I was also on the scenario queue. A few minutes after I joined the scenario and when I kill people the it was counted for the quest. I think the quest should only got the kills from RVR area where the keep is.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Which lord? Screenshot of the quest?

**Comment by Prumbai** [comment]
I don't have a screenshot but as far as I remember it was Well of Qhaysh in Saphery region. Just take the quest from the lord, join a scenario.
