### ISSUE TITLE
Tok Mount Gunbad History and Lore "Brightstone"

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11116]
When you interact with 'Brightstone Deposit' on the first (west) wing nothing happen.

(After having passing the first bridge, and the pass with 2 pillars, go on the right. The Brightstone Deposit will be at the edge of the ravine.)

You should unlock : 'Brightstone'

**Comment by Lheana** [comment]
This unlock works perfectly.
![lheana_081](https://user-images.githubusercontent.com/11537611/34717124-3d5d9276-f532-11e7-8eed-21a4184f5e5d.jpg)
However once triggered, you can not see it in the pages of History & Lore in ToK.
