### ISSUE TITLE
Gunbad Healers dieing to mobs, wound debuffs get out of control.

### ISSUE THREAD

**Issue by Zdaemon214** [WarEmu/WarBugs#11117]
Expected behavior and actual behavior:
    In the Mid Wing of Gunbad, the healer after the first PQ constantly gets aggro from a pack of goblins. He dies and once the group wipes, u get stuck with a wound debuff, and so on. We also had the healer at the end of the 2nd PQ aggro the boss, die and didn't re-spawn for at-least 30-45 minutes. Either the healers should re-spawn much faster, or be placed in different spots.

Steps to reproduce the problem:
The healer right after the First PQ in the Mid Wing of Gunbad dies no matter what, we cleared that area, but the mobs respawned and kept killing the healer. The Healer at the end of the 2nd PQ aggroed the boss that ran near the healer, the aoe killed the healer and we never saw that said healer respawn in the extra 30-45 minutes we remained in the mid wing.

**Comment by grunbag** [comment]
I'll move NPC. Do they fight all the time or only when you aggro mobs all around?

**Comment by Zdaemon214** [comment]
Both are once they aggro mobs. First has respawning Goblins near him which
he aggros usually because of us hugging the wall and getting aggro from
them, archer aoes him and he runs further toward Goblins and rest kill him.
Second aggros the spider/goblin once we pull the bosses

**Comment by grunbag** [comment]
Moved healers to a safe place.
