### ISSUE TITLE
Gunbad Mid Wing Second PQ, Mobs do not despawn on advancing the PQ to the 2nd stage.

### ISSUE THREAD

**Issue by Zdaemon214** [WarEmu/WarBugs#11119]
Expected behavior and actual behavior:
    We Cleared every spider we could see on the way through the 2nd PQ of the Mid Wing in Gunbad.  Once we cleared all 50 that the PQ required, the rest of the Spiders/Goblins/Eggs did not de-spawn as they normally would in a PQ. We had to clear even more trash, but this ran out the timer on the 2nd stage of the PQ which meant we had not enough time to kill both bosses.

Steps to reproduce the problem:
    Kill 50 spiders in the 2nd PQ of Gunbad Mid Wing, the rest of the spiders/goblins/eggs do not despawn and continue to stand in the way of the path to the boss even though the timer to kill the boss is still counting down.

**Comment by grunbag** [comment]
Only spiders are part of the public quest, goblins are instance spawns
