### ISSUE TITLE
Stuck in sandbox like ostland (not zone 0!). BoB and  /stuck command not working

### ISSUE THREAD

**Issue by Koentjuh1992NL** [WarEmu/WarBugs#1111]
My Shaman Gitgutz is stuck in sandbox like ostland. /stuck command only logs me out and Book of binding (bound on t2 warcamp) is not working. &jump command makes me shammy apear and i can move the little guy around on the screen but camera is locked ( shammy walks off the screen so to speak) camera point of vieuw is also undergound level.

Devs have been informed true Github, just made this report to Help em fix the problem and add a Screenshot of the problem. my shammy is seen in the top rightside of the screen shot very small near the help button (question mark) 

Hope it gets fixed dont feel rushed though i have other characters to keep myself entertained

![gitgutz_000](https://cloud.githubusercontent.com/assets/13716103/9335629/62d8732c-45d5-11e5-9d04-e831fa15d144.jpg)

**Comment by monstertheme** [comment]
Yea they really fucked up by changing /stuck command.

**Comment by ozarmidrashim** [comment]
As of next patch, entering /stuck once will invoke live handling. Entering /stuck while in the logout phase of another /stuck will invoke the old handling, warping you to the new character spawnpoint.

**Comment by Evildoor** [comment]
If even a new implementation of /stuck have not helped you, you should create a thread here:
http://www.returnofreckoning.com/forum/viewforum.php?f=4
Closing.
