### ISSUE TITLE
Greenskin Chapter 10 Wrong Class Influence Reward

### ISSUE THREAD

**Issue by stonefuzzy** [WarEmu/WarBugs#11114]
Elite Influence Reward at Greenskin Chapter 10 for Witch Elf contains a Charm usable by DoK

**Comment by Torquemadra** [comment]
name?

**Comment by stonefuzzy** [comment]
Symbol of da Miner is the name of the Charm

**Comment by sioding** [comment]
Fixed with patch from 2.2.2018
