### ISSUE TITLE
Ashreaver Tribe Stronghold PQ final stage champion has wrong level

### ISSUE THREAD

**Issue by fesust** [WarEmu/WarBugs#11110]
Expected behavior and actual behavior:
Level 36 easy pq in Cinderfall with 35-36 mobs, however champion in final stage is level 42

Steps to reproduce the problem:
1. Kill gnoblars
2. Kill ogres
3. Check champion level when it spawns

Screenshots/Videos or archive.org evidences:
https://i.imgur.com/UP5LPp2.jpg

**Comment by sioding** [comment]
fixed with patch from 9.2.2018
