### ISSUE TITLE
Gunbad 'Ard Ta Feed Instance portals.

### ISSUE THREAD

**Issue by Zdaemon214** [WarEmu/WarBugs#11127]
Expected behavior and actual behavior:
    Multiple times members of our group used the portal near Ghollum in "Ard Ta Feed's" instance, and multiple times members ended up in zone 0 and were teleported to Altdorf.  This caused lots of downtime as each time they had to run all the way back. We used this portal so many times because we ended up with wounds debuffs and the healer was missing when we respawned. Using this portal behind the boss was the only way to get to a healer that could heal the wounds debuffs.

Steps to reproduce the problem:
    1. Go in and out of the portals leading into, and out of "Ard Ta Feed's" instance area.
    2.  Eventually you will get ported to Altdorf.
    3. Happened to 1-2 people each time we wiped on the boss.

**Comment by grunbag** [comment]
Issue has been identified, will be few fixed soon

**Comment by sioding** [comment]
Fixed with patch from 26.01.2017
