### ISSUE TITLE
Gunbad Mid-Wing First PQ bug.

### ISSUE THREAD

**Issue by Zdaemon214** [WarEmu/WarBugs#11122]
Expected behavior and actual behavior:
    Twice now our group has entered the instance (Far after the 8 hour PQ lockout 24 hours atleast) and upon reaching the first PQ in the mid wing the PQ is not active. No giants, missing packs of goblins. The PQ only seems to become active after clearing our way to the wall that spawns at the end if the first PQ, crossing the border killing a few spiders and running back from the spiders to the Giants PQ. The wall spawns as soon as one person crosses the border, the PQ starts and the group is unable to go back to the first PQ unless they suicide to respawn behind the wall.

Steps to reproduce the problem:
    1. Complete the first PQ in the mid wing.
    2. Wait about 24h or more and renter Gunbad.
    3. Clear to First PQ, PQ isn't active 
    4.Clear to Second PQ and a few spiders.
    5. Run back towards the First PQ. 
    6.Once u cross the area where the wall spawns on an active PQ, the PQ suddenly starts and the Giants/Goblins Spawn. 
    7. The wall goes up and only one person makes it across causing the rest of the group to need to commit suicide to get to the other side of the wall and access to the First PQ.

P.S.  This has happened twice in the three times we have been into the Mid Wing of Gunbad. All three times we completed the first PQ.

**Comment by saupreusse** [comment]
That happens when the server can not load the pq on the first try while you cross it. It then loads the pq on the second time someone enters it. Its aknown issue and extremely annoying but no one could find the issue yet.

**Comment by grunbag** [comment]
It seems to not happen anymore
