### ISSUE TITLE
Raven Host Vanguard, Father Sigwald not Champion status

### ISSUE THREAD

**Issue by Numuul** [WarEmu/WarBugs#11124]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
From what I recall, Father Sigwald from the Raven Host Vanguard Public Quest has always been a champion when he spawns in (to prevent him from dying instantly when the 3 enemies spawn per wave), and I believe the reasoning being that it is the very first PQ and is supposed to be very easy to complete. I've noticed that he spawns in as a regular rank NPC, and is in fact extremely easy to kill. At times I've seen him die within 2 seconds of the stage beginning. I could be incorrect, but as a previous player of the original MMO, that's how I recall it. If the PQ had to be simplified to minimize strain on the server, I understand. Just thought I'd bring this to your attention. 

Steps to reproduce the problem:
Reach the second stage of the Raven Host Vanguard PQ

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
We need hard facts for those things. "From what i recall" is no evidence at all. Are you able to bring in a video or screenshots? Just to make it clear: It sounds useful to flag him as a champion ... but without a proper evidence....

**Comment by Lheana** [comment]
Note that the second stage of this PQ needs a really rework of the script.
