### ISSUE TITLE
0 cast time-flight time-gcd Fireballs?

### ISSUE THREAD

**Issue by roadkillrobin** [WarEmu/WarBugs#11121]
I'm just leaving this one here.
BW was atleast 80 feet away from me btw. 
![pharagax_017](https://user-images.githubusercontent.com/16356956/34742001-fd9f5838-f584-11e7-9b34-35b9fb129253.jpg)

**Comment by sioding** [comment]
Well - could be a normal fireball and "flash fire" fireball after that.

**Comment by roadkillrobin** [comment]
Does Flashfire remove the traveltime of FB?

**Comment by Zdaemon214** [comment]
No but casting a fireball and immediately using flashfire proc on fireball they would both leave at the same time as there would be no gcd on the instant Fb

**Comment by roadkillrobin** [comment]
I guess it could happen but were did the disrupt proc come from then?

**Comment by Zdaemon214** [comment]
Probably a dot on someone else

**Comment by sioding** [comment]
OK i will close this now.
