### ISSUE TITLE
How to get ur quest reseted always when u want

### ISSUE THREAD

**Issue by Farlopa** [WarEmu/WarBugs#11128]
I know there are more post talking about them lost them quest and things but i will put here the steps for how u get that reset and is easy i test it 6 times and the 6 times happens.

1-load the game, when u arrive to ur character and press play u arrive to the loading screen so in that moment put down ur connect and wait to be sended back to server selection.
2-repeat this same thing of the first step.
3-when u log again after this press play in ur character and this time go to work administrator when u arrive the loading screen close the game directly.

After this steps u will get ur quest reset in the character u was trying to play. Another thing,after this reset dont be afraid u didnt lose nothing u just can do again all the quest but when the server restarts u will get back ur old quest.
Sorry for dont bring pictures to the post.

**Comment by sioding** [comment]
Brought your informations into the original ticket and will close this one. Thank you for this testing.
