### ISSUE TITLE
Quest: "Black Stuff", Thunder Mountain, Greenskeens Ch 17

### ISSUE THREAD

**Issue by Grunbeast** [WarEmu/WarBugs#11125]
Need to kill monsters and mix ingredients in a mug. Killing monsters work as intended and count to quest but there is no mug to mix ingredients. Quest states that mug should be given by Sizzlum to a player. I could not find any mugs in settlement either. Unable to complete this quest.

**Comment by Lheana** [comment]
The quest name is "Hot Stuff" in real.
This quest has been fixed on 14/07/2017 #12020
