### ISSUE TITLE
Gunbad 'Ard Ta Feed no loot at all

### ISSUE THREAD

**Issue by Zdaemon214** [WarEmu/WarBugs#11126]
Expected behavior and actual behavior:
    We wiped several times on this boss "'Ard Ta Feed", but finally managed to kill him. once we killed him tho nobody was able to loot his corpse. We ran in and out of the instance, ran all the way back down and nothing allowed us to loot him. We thought he was suppose to drop the "Redeye" chest piece or some part of the set. 

Steps to reproduce the problem:
   1. Wipe several times. ( This also involved zoning in and out of his little instance and out of the dungeon as well.)
   2. Kill the boss.
   3. Can't loot the boss, nobody in the party at all could loot him.

**Comment by sioding** [comment]
Fixed with patch from 13.1.2018

**Comment by stillwaterww** [comment]
As of 18-1-2018 not lootable again

**Comment by stillwaterww** [comment]
Killed by Miae, Tesq, Whoopass, Zaliryatera and Ichopthings

**Comment by wargrimnir** [comment]
Verified in Gunbad. Outside of Gunbad the boss drops loot appropriately. Loot tables are set correctly, something else is stealing the kill contribution, and I would wager it might be the friendly squigs that bounce around him.

**Comment by Zdaemon214** [comment]
Yeah guarantee that's what it is

**Comment by stillwaterww** [comment]
Certain that is it.

**Comment by Hargrim** [comment]
Will be fixed after next patch / hot fix.

Until this time clear all adds and GOs when he is low on HP to avoid that.

**Comment by stillwaterww** [comment]
![ardtaloot](https://user-images.githubusercontent.com/19287032/35597358-5dba1f38-061e-11e8-9330-e7bc811625da.png)

Theres been a patch, but its still 'Ard ta Loot

**Comment by Cpryt** [comment]
![run_066](https://user-images.githubusercontent.com/19481783/35597746-255ca2e6-05dd-11e8-8bfb-929ecc0bdd60.jpg)
![run_060](https://user-images.githubusercontent.com/19481783/35597769-3cc03ede-05dd-11e8-8338-3a3af2f47150.jpg)
![run_043](https://user-images.githubusercontent.com/19481783/35597792-4f612260-05dd-11e8-83bf-f4413e4d9fdc.jpg)
Killed 'Ard ta Feed with players:
Run (me, zealot)
Miae (black guard)
Mng (black orc)
Miszha (witch elf)
Ilpa (shaman)
Nosebleeda (squig herder)

Wiped a good bit of times before actually being able to kill it, but we received no loot. Screenshot shows the loot table was enabled upon killing it. Nothing was received.

**Comment by Nosebleeda** [comment]
Ha, seems like Run got the post going, if you need any explanation on how we killed it, let me know, i'll be glad to explain how.
