### ISSUE TITLE
Guild bug ongoing

### ISSUE THREAD

**Issue by GutshotSheerak** [WarEmu/WarBugs#11136]
*created a guild that disappeared the next day
*transferred our whole guild into an order guild (we play destroy)
*Left the order guild and reformed another guild, 2nd time, again it disappeared the next day
*3rd time forming a guild and it disappeared
*Joined an established guild lvl 29, auto kicks me the next day
*Rejoined the established guild and it has kicked me out 4 times now this week (The members of the guild did not kick me out)
I am trying the join/leave/join/leave/join/leave guild to see if that fixes issue.  

What do I do?

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
#11072
