### ISSUE TITLE
game client

### ISSUE THREAD

**Issue by ziguzanuzoon** [WarEmu/WarBugs#11130]
when a loanch the game client i get the a messeg saying that the patch client was unable to retrieve the fille patch.prod.sig from the pach server although is tells me 0 errors encountered and to pleas try to run the patcher again in a short time ive ran this 7 times and keep geting theas

**Comment by sioding** [comment]
Please use this forum for your question: https://www.returnofreckoning.com/forum/viewforum.php?f=5
