### ISSUE TITLE
Chosen Bug Tactic

### ISSUE THREAD

**Issue by Chechenaib** [WarEmu/WarBugs#11132]
the tactic of 15% critical for chosen not working. Fix the bug please

**Comment by sioding** [comment]
Sorry but this ist not the type of tickets that are acceptable. Name the tactic. Add Screenshots with your tests. Otherwise i will close the ticket again.

Please read the bugtracker rules:
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
