### ISSUE TITLE
Chosen Tactic: Oppressing Blows / Melee Crit Rate

### ISSUE THREAD

**Issue by Chechenaib** [WarEmu/WarBugs#11133]
![naib_671](https://user-images.githubusercontent.com/35333467/34826034-4b8d7132-f6d5-11e7-8214-d8dce2c2d55d.jpg)

![naib_681](https://user-images.githubusercontent.com/35333467/34826251-22801c9e-f6d6-11e7-9d54-ae9c5e6c15d5.jpg)

![naib_683](https://user-images.githubusercontent.com/35333467/34826255-277d2818-f6d6-11e7-83b9-4f07d41df350.jpg)

![naib_673](https://user-images.githubusercontent.com/35333467/34826289-4a525ba6-f6d6-11e7-9872-6e35daed0e95.jpg)

![naib_675](https://user-images.githubusercontent.com/35333467/34826303-535a07da-f6d6-11e7-8b3b-b9912c4c0cb6.jpg)

Here is the screen, check and correct it please

**Comment by Torquemadra** [comment]
paperdoll issue only
