### ISSUE TITLE
Firebeard's Slayers PQ (Greenskin level 10-11 PQ) Barak Varr

### ISSUE THREAD

**Issue by Asherdoom** [WarEmu/WarBugs#11139]
As per screenshot in phase 2 of this quest there is no way to damage and destroy enemy cannons as requested by PQ
I tried with AOE or single target attacks, checking crates around for items needed maybe to destroy cannons yet nothing happens

sorry for disturb!
![sahul_001](https://user-images.githubusercontent.com/16918614/34878375-b9020a76-f788-11e7-87f6-cf45471660c4.jpg)

**Comment by Lheana** [comment]
Thanks for report. Fixed next patch

**Comment by sioding** [comment]
Fixed with patch from 13.1.2018
