### ISSUE TITLE
Reserving guild heraldry doesn't need guild rank 10 or heraldry rights

### ISSUE THREAD

**Issue by tutti13** [WarEmu/WarBugs#1113]
When using the script command (/script WindowSetShowing("HeraldryEditor",true)) to open the guild heraldry editor, i can save the heraldry, even without the guild rights to edit the heraldry and with a lvl 8 guild.

It can also be changed as often as you like.

**Comment by Luth-RoR** [comment]
Needs confirmation if this still works like that.

**Comment by Luth-RoR** [comment]
Tested ingame with guild leader rights; doesn't work anymore.
