### ISSUE TITLE
GUNBAD - Problem die near healer 3rd QP.

### ISSUE THREAD

**Issue by IRW-Gloux** [WarEmu/WarBugs#11137]
Hello !
This bug is about the GUNBAD dungeon.

When we dies in the 3rd QP, we respawn near the healers, then we die directly with mobe behin the wood barrier.
 Click on respawn and we respawn near the healer of the 2nd QP !
Then, we are stuck on the 2nd QP even the rest of the groupe are in 3rd QP :/

Thanks in avdance for fix :) PS : Thanke again for the amazin works !

**Comment by grunbag** [comment]
Fixed in next patch
