### ISSUE TITLE
 Problem inscription scenario

### ISSUE THREAD

**Issue by Silhanna** [WarEmu/WarBugs#11148]
Hi,

When you want to register as a group for the scenarios, even the group leader can not make "join group" because the button can not be activated. 
We have to do several times unbundling / grouping to get there.
Thank you in advance for your help.
Good night.
Silhanna SW 40 order

**Comment by sioding** [comment]
And the Levelrange in your group is? Can you please add a screenshot?

**Comment by Silhanna** [comment]
![silhanna_005](https://user-images.githubusercontent.com/35430790/34919714-203a925e-f968-11e7-80aa-c87827c1b714.jpg)

We are always next to each other.

**Comment by sioding** [comment]
OK both of you are R40. Thats what i wanted to check. I know that issue - had the same one in my own group. Right click on tthe other person in the group and use the "Make Leader" function. You should be able to queue for scenario´s after that.

**Comment by Silhanna** [comment]
it does not work either. We are still oglig to remake the group each time. It's been a long time since we have this problem!

**Comment by sioding** [comment]
OK just to make it clear: Both of you haven´t a Quitter debuff and you can´t join the SC queue as a group correct?

**Comment by Silhanna** [comment]
Yes that's it.

**Comment by sioding** [comment]
Tried that on my own with several group constallations and cannot reproduce that. sorry - don´t know what´s going wrong on your side and if we have more than one group which would not be able to queue for the scenario we would know that. Please try the forum for an answer - this is definitly not a bug on the serverside.
