### ISSUE TITLE
CheckArea - NullReferenceException thrown

### ISSUE THREAD

**Issue by Tyramissoux** [WarEmu/WarBugs#11146]
"[] says: NullReferenceException was thrown from CheckArea. This object will be destroyed."

See screenshot for text and context.

![annnoying_037](https://user-images.githubusercontent.com/13544944/34916214-b072843c-f934-11e7-8f96-600f57ce8abc.jpg)

**Comment by sioding** [comment]
Thanks for the report. - can you give us some more information? What stops working and have this exception? Whens did you get it (your timezone and time you get it). We need to search for it in logfiles so some more information would be great.

**Comment by Tyramissoux** [comment]
Can't say that anything stopped working. Just noticed the exception in my chat log. Was generally laggy around that time and exceptions cause lag.

Timezone: GMT+1 
Exception time from screen: 13:03:53

First, I thought it might have happened in context of my char's death but the exception was before that.
Time of screenshot is seen in the black bar on the upper border (13:04:22). Time of death can be calculated backwards (13:04:22 - 9 secs).

**Comment by sioding** [comment]
Thanks again.

**Comment by Hargrim** [comment]
This was on 14.01.2018?

**Comment by sioding** [comment]
yes - 14.01.2018 - 13:03:53 GMT+1

**Comment by MaxHayman** [comment]
This should be fixed
