### ISSUE TITLE
Again bugs in Gunbad left wing

### ISSUE THREAD

**Issue by rhix112** [WarEmu/WarBugs#11149]
1 - healer npc dieing at last boss, when we start him healer starting agro from outside. So stack Battle Fatigue on us with dead healer npc
![carsen_003](https://user-images.githubusercontent.com/31020540/34919283-3591cba4-f972-11e7-8dc7-321294d4b638.jpg)
2 - pq before last boss in left wing we made 2 times after wipe on last boss.
![carsen_001](https://user-images.githubusercontent.com/31020540/34919420-c77f6ac4-f974-11e7-8b89-d871ac516207.jpg)

**Comment by Tesq** [comment]
in live healers were invincible/unattackable and not aggressive

**Comment by grunbag** [comment]
i can't fix healer for now

moved barrier a bit, so if PQ bug again you won't respawn on the wrong side of the barrier when you die from instanced boss

fixed in next patch

**Comment by sioding** [comment]
fixed with patch from 20.1.2018
