### ISSUE TITLE
EDIT: ALL gunbad wing's boss

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#11143]
it appear after 13/01 patch that enter in the barrier leads you again into an empty istance but boss can be see throught the barrier from outside

EDIT: it is the same for all the other bosses, pre today restart left one was missing, then i done mid wing and found also that solithex and final boss of the dungeon are missing.

EDIT2: re-done again Gunbad got same results.

**Comment by grunbag** [comment]
Someone in your group already killed the boss?

**Comment by grunbag** [comment]
Also don't trust what you see in the barrier from outside

**Comment by Tesq** [comment]
from outside it was up, from outside it wasnt; no none had killed it.

**Comment by grunbag** [comment]
from outside he will always up , no matter if you kill him or not inside.

if you don't see him inside it means someone has lockout active in your party

**Comment by grunbag** [comment]
Also try to let party leader enter first.

**Comment by Tesq** [comment]
closing this since it seems to work fine
