### ISSUE TITLE
Not receiving mail stuff on 1 char

### ISSUE THREAD

**Issue by Ulrok** [WarEmu/WarBugs#11145]
Hello

one of my chars is not getting the stuff im sending to, i sended before restart and after restart, a gm sended something to test and i didint got anything but he got what i sent.

**Comment by sioding** [comment]
Hey, thanks for the report. Can we please have the Characternames you have send from and to - and the time you´ve tried it?

**Comment by Ulrok** [comment]
dont remember the time, i send from my other alts to ulrok

**Comment by sioding** [comment]
OK thanks - please give a feedback if the mail arrive after the next server restart.

**Comment by Ulrok** [comment]
hey... yes is working now thank you...what about the items i sended?

**Comment by sioding** [comment]
Dunno - ask the person you have sended them?
