### ISSUE TITLE
Tank's Champion Challenge bug

### ISSUE THREAD

**Issue by magter3001** [WarEmu/WarBugs#1114]
When using the rank 1 morale Champion Challenge on a target that has snare immunity ability on (so all mdps) The morale will go off, and root the tank but will not root the target he is trying to root. What ends up is the tank is rooted in place while a mdps is running off freely. You end up wasting a morale, and get rooted for 10s for your trouble. Only happens when the mdps already has the snare immunity ability activated.

**Comment by Silentguard** [comment]
Same as it was on live.

**Comment by magter3001** [comment]
I don't think it was exactly the same. A tank would not get rooted on live, the morale would just gray out until the immunity wears off. As it is now, the morale would fire off, the tank would get rooted but the mdps would not. Very dubious indeed. :P

**Comment by Nfkillz** [comment]
lol. good tank looks at buffs and doesnt have this trouble

**Comment by magter3001** [comment]
Good tanks look at buffs but there is a reason I posted this here, because it's a bug. Please leave your "lol" away if you have nothing good to add. 

On the original post, M2 for healers (Focused Mind) does the same thing and has the same effect. This wasn't a problem until last patch, if that helps any.

**Comment by Evildoor** [comment]
This is now broken into other side:
https://github.com/WarEmu/WarBugs/issues/1167
