### ISSUE TITLE
Terrible Embrace(Marrauder ability)bug

### ISSUE THREAD

**Issue by BugHammer** [WarEmu/WarBugs#11141]
Ability is not working properly,when trying to pull someone that stands on higer ground(ex.on a big rock,gates of ekrund middle flag to plato,keep walls etc) it says "can't see your target when target is clearly visible,it used to work properly before

**Comment by sioding** [comment]
Can we please see the screenshots you´ve made?

**Comment by BugHammer** [comment]
i didnt it was yesterday and days before,it can be recreated easly,just a guy on a wall and marrauder down,i recreated it with a some guy in a duel,he stood on a rock(lower then keep wall) in a range of 65 feet,when ability is used it will chanel for some time and stop not completing the ability,and thats on very close range and low hight within like 40 feet,didnt get any message about not seeing a target this time but ability was still bugged,and only worked at really low heights,i didnt play for game for about year on off,but ability used to work nearly perfectly in past

**Comment by sioding** [comment]
Hm tried it with my own Marauder and didn´t get the same error. So please add a video to let us see what you see.

**Comment by BugHammer** [comment]
ok i will try
