### ISSUE TITLE
Bug with Barron Bernhardt von Altdorf

### ISSUE THREAD

**Issue by Silhanna** [WarEmu/WarBugs#11147]
Hi,
I do not see all the items that can be purchased from the NPC mentioned in the title.
I watched with my husband who has them all.
Can you help me because I can not buy anything with Imperious Warrant?
Thanks for your help.
Good night.
Silhanna SW 40 order

**Comment by sioding** [comment]
Screeeeeenshot please.

**Comment by Silhanna** [comment]
![silhanna_005](https://user-images.githubusercontent.com/35430790/34919748-8836d106-f968-11e7-878a-46ea3c20b1fa.jpg)

I do not see the items for the Imperious Warrant.

**Comment by sioding** [comment]
Well - i can see the items in your own screenshot. 
![image](https://user-images.githubusercontent.com/18517842/34955608-869ccdc4-fa25-11e7-8a55-108c84e34f5d.png)
