### ISSUE TITLE
Suderheim PQ

### ISSUE THREAD

**Issue by Wildaa** [WarEmu/WarBugs#11142]
During the first stage of this PQ it requires you to destroy 10 each barrels, chest, baskets, and crates. There are plenty of each type except baskets there are only 9 baskets. Please add more

Expected behavior and actual behavior: Should be enough baskets to ope the next stage.

Steps to reproduce the problem: I have attempted this PQ several times after server restart with the saem results.

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/35405901/34909177-03c73b4e-f86a-11e7-831f-10d73a329168.png)

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Lheana** [comment]
Added spawns so that there are 13 Baskets now.

**Comment by sioding** [comment]
Fixed with patch from 26.01.2017
