### ISSUE TITLE
gunbad port with tome

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#11144]
each time you get port into the bug istance (the same you do when you wipe from a wing boss ) with no healers/npc

**Comment by grunbag** [comment]
When you wipe at boss it always port you to the empty instance ?

**Comment by Tesq** [comment]
yes, wiped mroe than once in previously days just reported it today

**Comment by grunbag** [comment]
Issue is identified, need a coder to fix it

**Comment by grunbag** [comment]
Fixed by Hargrim in Next patch

**Comment by sioding** [comment]
Fixed with patch from 26.01.2017
