### ISSUE TITLE
Stonepillars BO Lookout

### ISSUE THREAD

**Issue by LuckyRaider** [WarEmu/WarBugs#11153]
There are a few Pillarspots at the BO lookout where ya could jump on the top by mount. On this top ya will be untouchable by meleechars but only by rangechars. But ya could shoot or cast to the ground and get also rr, xp and inf. So i want to report this spot cause one gm-char (Carml) said this was a bit against the rules. So it should be fixed a bit, cause it will/was a advantage for hte rangeclasses and a disadvantage for all melees. Ty for notice.

**Comment by sioding** [comment]
Are you able to bring in a screenshot?

**Comment by LuckyRaider** [comment]
Sure if i've don't catch a kick/ban to show ya the pillars on a screenshot.
I will jump upon the pillars after work to show the spots.
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 16.01.18, 11:03, Sio <notifications@github.com> schrieb:
Are you able to bring in a screenshot?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/WarEmu/WarBugs","title":"WarEmu/WarBugs","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/WarEmu/WarBugs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sioding in #11153: Are you able to bring in a screenshot?"}],"action":{"name":"View Issue","url":"https://github.com/WarEmu/WarBugs/issues/11153#issuecomment-357911463"}}}

**Comment by sioding** [comment]
If you have any problems with a GM catching you doing this screenshout you can point out to this report and that i have asked for a screenshot

**Comment by LuckyRaider** [comment]
The pillar i stand on the top and the pillar infront my sight are the 2 ya can jump on.

Screenshot is available as .jpg


Gesendet: Dienstag, 16. Januar 2018 um 12:26 Uhr
Von: Sio <notifications@github.com>
An: WarEmu/WarBugs <WarBugs@noreply.github.com>
Cc: LuckyRaider <o.kaiser.75@web.de>, Author <author@noreply.github.com>
Betreff: Re: [WarEmu/WarBugs] Stonepillars BO Lookout (#11153)


If you have any problems with a GM catching you doing this screenshout you can point out to this report and that i have asked for a screenshot

**Comment by LuckyRaider** [comment]
![toothless_000](https://user-images.githubusercontent.com/32480173/35086391-c8f86ca6-fc2c-11e7-9c11-15e1445e0643.jpg)

**Comment by sioding** [comment]
Checked that on my own. Nothing special here and noting i can do to prevent that.
