### ISSUE TITLE
Quest: "the elf behind the curtain" order side avelorn

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11158]
There is no red mark on the map

![thorbolt_081](https://user-images.githubusercontent.com/16274785/34987302-f47f8b2a-faba-11e7-946a-7d27aa0786de.jpg)

**Comment by sioding** [comment]
![image](https://user-images.githubusercontent.com/18517842/36949146-ac00c568-1fe4-11e8-86a8-8fe7ba8cc473.png)
The Log is in the same red circle as the vanquishers you have to kill - don´t wanna make it too easy ...
