### ISSUE TITLE
Destro: Nowhere to Hide

### ISSUE THREAD

**Issue by Luuca** [WarEmu/WarBugs#1115]
An introduction:

This big happens when I selected the last item on the right of the quest rewards; the 70 Block Shield. When I selected the shield, the quest completed and the shield did not appear in my inventory. 

If working properly, I would have recieved the shield selected and completed the quest. 

Evidence:

Additional Information:

I saw another CLOSED bug report about this same issue on this quest with a different item

How to reproduce the bug:

Only way to reproduce it is to roll a new character and start the quest, complete it, and try to select the 70 Block Shield.

**Comment by Radiantknight** [comment]
Same with talisman quest rewards in ch8 and 9. get exp, but no tali

**Comment by Reggaewaldo** [comment]
I have a fix pending here. I will just verify.

**Comment by Evildoor** [comment]
Status?

**Comment by Ryanfawkez** [comment]
Checked quest rewards for Choppa; item on the 2nd row is unobtainable. Since the 2nd row items are no longer obtainable and will instead not give any reward until a suitable one is chosen, before completing the quest, I'll check the actual quest rewards and add them as necessary.
