### ISSUE TITLE
[gunbad] ghoullum NPC most of times die by enemy in the area

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#11152]
Quest taker/giver between 2nd and 3rd  pq  middle wing

It get every time/ most of time  killed by enemy mobs
![tesq_320](https://user-images.githubusercontent.com/7527415/34923348-42244e2c-f99b-11e7-9d48-9b417e6a25e9.jpg)

**Comment by grunbag** [comment]
Fixed in next patch

**Comment by sioding** [comment]
fixed with patch from 20.1.2018
