### ISSUE TITLE
Quest: "Give 'im wot he want", Cinderfall, Destruction

### ISSUE THREAD

**Issue by Grunbeast** [WarEmu/WarBugs#11155]
Can not interact with barrel. Barrel not marked on map
![grunbeast_057](https://user-images.githubusercontent.com/35007878/34980718-9f88e338-faa5-11e7-82ca-0ac12e559ed4.jpg)
![grunbeast_058](https://user-images.githubusercontent.com/35007878/34980719-9fa6b110-faa5-11e7-896d-060c3aa582c2.jpg)
![grunbeast_059](https://user-images.githubusercontent.com/35007878/34980720-9fc41b38-faa5-11e7-91f3-f8a8b98e5482.jpg)

**Comment by NorKalli** [comment]
GO now tied to quest

**Comment by NorKalli** [comment]
questmarker added

**Comment by sioding** [comment]
Fixed with patch from 02.06.20018
