### ISSUE TITLE
Quest: Fightin' Infightin', Death Peak, Destruction

### ISSUE THREAD

**Issue by Grunbeast** [WarEmu/WarBugs#11157]
'Eadbutta is friendly target and can not be killed to complete this quest.
![grunbeast_060](https://user-images.githubusercontent.com/35007878/34985397-273fb622-fab4-11e7-8a50-4eb2e70236da.jpg)
![grunbeast_061](https://user-images.githubusercontent.com/35007878/34985398-275eb9dc-fab4-11e7-8f66-11112b8a2cf0.jpg)
![grunbeast_062](https://user-images.githubusercontent.com/35007878/34985399-277e60d4-fab4-11e7-82a8-4dbe15d449df.jpg)

**Comment by NorKalli** [comment]
NPC set to neutral

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
