### ISSUE TITLE
Dark Elf: Striking Saphery (Avelorn)

### ISSUE THREAD

**Issue by Akenatoth** [WarEmu/WarBugs#11154]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Expected: I should move to the marked location, find a "Uthorin Siegelord" and speak to him, use the Reaper Bolt Throwers 6 times and kill 6 Sea Guard Beachstormers.

Actual: No Uthorin Siegelord NPC to be found at location (just 2x Devak's Elite). Using the Reaper Bolt Throwers doesn't update anything, killing the Sea Guard Beachstormers updates the kill bit (bolt throwers work but don't update).

Steps to reproduce the problem:

Pick up the quest from Devak Bloodbane at the Jade Coast DE Ch.12 camp , go to the marked location (bottom left on Averlorn's map). Verify that Uthorin Siegelord isn't there. Use Reaper Bolt Throwers and verify that their use doesn't update the quest.

Screenshots/Videos or archive.org evidences:

![image](https://user-images.githubusercontent.com/35481383/34975261-46aa498c-fa91-11e7-8167-181ba6f9619a.png)

![strikingsaphery_1](https://user-images.githubusercontent.com/35481383/34975227-2455f052-fa91-11e7-89bf-4b38b0a09ac6.jpg)

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
fixed with patch from 09.06.2018
