### ISSUE TITLE
Flashfire Proc vanish while cast already started

### ISSUE THREAD

**Issue by dansarii** [WarEmu/WarBugs#11150]
It appears that Flashfire is bugging out. Haven't determined how to reproduce yet, but sometimes the BW will get disrupted and Flashfire doesn't proc (outside of the 6s icd). Submitting for further investigation to see if it's actually not triggering or confirmation that I can't count to 6.

Edit: I believe it sometimes occurs when you are currently channeling an ability that would be consumed when you use the Flashfire proc. You can even sometimes see a disrupt, see the Flashfire proc, then it immediately goes away while you're channeling the ability as if the ability you're currently channeling was supposed to be instant cast.

**Comment by sioding** [comment]
I will test that on my BW this evening - as far as i saw while channeling Fireball Barrage the proc won´t vanish and i can cast an insta firball right after the FB is done. Please try to catch a video proof for that.

**Comment by dansarii** [comment]
I will see if I can get video recording set up. Can confirm that it doesn't happen with Fireball Barrage though *because* Fireball Barrage is only a channel. I meant that when you're loading a Fireball or a Fiery Blast and you get a proc during that cast, it will sometimes be consumed.

**Comment by sioding** [comment]
ok thanks - will try to test that on my own too.

**Comment by Blubberino** [comment]
The same bug was on zealot with scourged warping. The ability was using up the proc. It was solved a while back. However I'm unsure if it's in this case intendet. 2 fireballs hitting shortly after each other is kinda strong and this tactic already is strong but if you want to solve the bug just look what they did with scourged warping proc.

**Comment by dansarii** [comment]
Playing tonight on my BW and did not see any issues with the Flashfire proc, so it could have been a fluke that got fixed upon hotfix/patch.
