### ISSUE TITLE
Not showing mount Gunbad inside Tok quests description

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11156]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
They should have a description "mount gunbad" below "zone" inside Tok

Steps to reproduce the problem:
I wrote in red where "mount gunbad" must appear for each quests

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
![mount gunbad no zone in tok](https://user-images.githubusercontent.com/16274785/34984626-e0d596b8-fab1-11e7-942e-ab3955b467e5.png)

**Comment by grunbag** [comment]
Fixed in next patch

**Comment by sioding** [comment]
fixed with patch from 20.1.2018
