### ISSUE TITLE
High Elf Ch. 2 Quest "Cruelty to Animals"

### ISSUE THREAD

**Issue by ErikWPotter** [WarEmu/WarBugs#11165]
This is a reopen of "Elf chapter 2 quest Cruelty to Animals #9760".

This quest remains or is once again broken.

**Expected behavior and actual behavior:**

Killing Cold Ones "that are stalking the Swale Mares in the Swale of Miraelei" should grant quest credit for 2 Cold Ones.

I was in "The Swale of Miralei" and got kill credits for the Harpies but not for the Cold Ones. I killed many Cold Ones within the PQ area, even all the Cold Ones near each Swale Mare. I left the PQ area and killed some caged Cold Ones in a Dark Elf camp to the NE...no credit. And the Cold Ones closer to the starting area forest didn't give credit either.

**Steps to reproduce the problem:**

Start the "Cruelty to Animals" quest. Kill Cold Ones in the Swale of Miraelei.

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 20.1.2018
