### ISSUE TITLE
Visual bug with some Dwarf Ironbreaker belts who not appears on the character

### ISSUE THREAD

**Issue by Brokhe** [WarEmu/WarBugs#1116]
I did some tests and I noticed a few Dward Ironbreaker belts skins did not appear on the character. 

Here is the belts skins name who not appear on the character : 

Kladgird of Dominion
Kladgird of Conquest

Here is the belts skins name who appear on the character : 

Militia Kladgird
Kladgird of Vengeance

Here is the screenshot with the visual bug  : 
![capture d ecran 2015-08-19 19 10 19](https://cloud.githubusercontent.com/assets/13872868/9363332/2af8ffd6-46a6-11e5-962c-7be8e5b1e77d.png)

Here is the screenshot without the visual bug : 
![capture d ecran 2015-08-19 19 04 13](https://cloud.githubusercontent.com/assets/13872868/9363303/02ab0268-46a6-11e5-972c-ba8c89ee71d5.png)

**Comment by DanaBloodkiss** [comment]
Should be fixed in next.

**Comment by Reggaewaldo** [comment]
Verified functionality on the dev server.

Closing.
