### ISSUE TITLE
nullrefrenceException was thrown from lockouts?

### ISSUE THREAD

**Issue by felkia** [WarEmu/WarBugs#11164]
after the server restart on Tue Jan 16 my slayer and many other players characters have become bugged with this text being thrown up upon loging into the game

nullReferenceException was thrown from update.

using any skill thats buffs or goes on cool down not giving buffs but go on cool down use AP cant IE. Flee

https://imgur.com/a/JTlML

i log in game logs me back to log in screen log back in game kills me in altdorf been like that since server restart jan 16.

since server restart last night jan 18 game is now giving new text

nullRefrenceException was thrown from Sendlockouts.

despite the change in code that was pushed last night my slayer is still broken with the issues i have stated.

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
This should have been fixed. Are you still having issues with your slayer?
