### ISSUE TITLE
Russian Cyrillic letters are displayed wrong.

### ISSUE THREAD

**Issue by Thralgar** [WarEmu/WarBugs#11169]
Greetings! Recently after some bug fixing reboots on the server, Ru players started to have problems with typing/seeing Cyrillic letters. Squares are being displayed instead of Сyrillic. It`s hard to communicate through /8 and personal messages. Changing of fonts doesn't help. Are there any useful solutions to this problem and how soon will it be fixed?

![default](https://user-images.githubusercontent.com/35611272/35170304-8ef63df2-fd81-11e7-972e-be11f793c78b.png)

**Comment by MaxHayman** [comment]
Hi @Thralgar,

We are applying an update which should fix this tomorrow. 

I will message here once it has been applied.

Thanks,
Max

**Comment by Yellowpillow** [comment]
Is this fix will affect this issue #5613?

**Comment by MaxHayman** [comment]
If you can demo #5613 to me i can fix it.

**Comment by Yellowpillow** [comment]
Here you go:
![nonameness_017](https://user-images.githubusercontent.com/18102127/36147368-5ccbbba0-10d1-11e8-8e39-6c51410f1e70.jpg)
![nonameness_018](https://user-images.githubusercontent.com/18102127/36147370-5ce8972a-10d1-11e8-9353-22dc38d970e6.jpg)

**Comment by Natherul** [comment]
Should be fixed by now, if not then please make a comment and we reopen it.
