### ISSUE TITLE
Public quest mobs kill counted double/triple etc...

### ISSUE THREAD

**Issue by Idrug999** [WarEmu/WarBugs#11161]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
PQ that have steps with kill x number of mobs. They are counted for each member of the party. I've tested this in Altar of Madness in CW, Dammaz Skar in Black Crag, Plague Mist Vale and The Sealed Tower in Kadrin Valley and all have the same problem. I've replied this in other pq, and seems to be a general bug of the pq...For each member of the party (of the mob that u need to kill for complete the pq) u can see a kill tracked in the pq objective

Steps to reproduce the problem:
For replicate, u need to group with one other people and kill one mob of a pq that u need to kill for complete the step (example, disciple of whisperer in Altar of madness). Retry in solo or with 3 people in group

Screenshots/Videos or archive.org evidences:
cannot post a screenshot, is impossible to evidence with a screen, and cannot do a video for pc problem

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Idrug999** [comment]
tryied last night with my pg Idrugsword, and other 3 friends Therheal, Koldrim and Arthanis in two pq and is confirmed. Order side

**Comment by Idrug999** [comment]
also confirmed at Siren's Sea, CW order side. Tested with me, Idrugsword and Saphyrael

**Comment by Idrug999** [comment]
Correction: u take kill in the objective of the pq **for every member of the group that hit the mob** example:
me and Saphyrael are in party in Siren Sea pq. i kill one demonette, Saphyrael don't hit my demonette= on the pq objective there is only 1 kill of the demonette. I kill one demonette and Saphyrael hit my same demonette= 2 kill on the pq objective. 
This not work for objective that have to kill a thing like altar or Topple of the Siren Braziers

**Comment by stillwaterww** [comment]
I have a feeling this has to do with the changes made to how loot distribution works. Before the loot would go to the player and his group that got the killingblow, nowadays it goes to the group whom has done the most damage to the npc/player. Offcourse I cant confirm this as I cant see you code, or wouldnt be able to make any sense of it if I could, but I believe this problem arose around the same time that this hange was implemented. Could be worth checking into. This theory is further empowered by mine and others experience that influence is rewarded per player hitting the npc in for example pq's and not perse multiplied by the number of players in the group.
Regards,

**Comment by sioding** [comment]
fixed with Hotfix - 2/11/2018
