### ISSUE TITLE
[Bright Wizard] Morale 4; Wall of Fire

### ISSUE THREAD

**Issue by cimator** [WarEmu/WarBugs#11171]
![wall of fire](https://user-images.githubusercontent.com/17130290/35186303-fff08e80-fe22-11e7-9806-31ea6b6439c7.jpg)

Its not working atm, throws a "8221 Wall of Fire has no implementation."

**Comment by BomblingTV** [comment]
Just tested this mastery M4. The ability does not fire off when you press it either by clicking it, or with assigned hotkey. instead it just goes on 1min cooldown for the M4 slot and does not drain your morale bar while nothing happends.

**Comment by cimator** [comment]
This was open for a long time, tested again today, looks like it has been implemented, doesn an 8 seconds channeling, damaging up to 65ft in a straight line.
