### ISSUE TITLE
Quest : "Mirelen's Lost" Shadowlands (Order side) no red mark

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11173]
no red mark on map
![thorbolt_092](https://user-images.githubusercontent.com/16274785/35191733-d4028796-fe82-11e7-99de-442a241bacc7.jpg)

**Comment by sioding** [comment]
Well - the scroll is in the same circle as the Uthorin Seekers...
![image](https://user-images.githubusercontent.com/18517842/36949104-1e3891a2-1fe4-11e8-86eb-7e74c6190884.png)
