### ISSUE TITLE
Dark Elf: Power Hungry (Eataine Ch 20)

### ISSUE THREAD

**Issue by Akenatoth** [WarEmu/WarBugs#11175]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Expected: Go to the Vault of Serian, find the Windsong Dais and use the Text of Immerial to recite the ancient words. When the words are spoken in the proper sequence, your guide will become apparent.

Actual: You click on the Windsong Dais in the Vault of Serian, you get the "Text of Immerial 1/1" quest update, your guide doesn't show so you can't hand in the quest anywhere (checked on Ch 20/21 camps too, just in case).

Steps to reproduce the problem:

Get the quest from Dirkaln Vorsept in ch 20 DE camp, go to Vault of Serian, enter the building, go all the way down and at the end click on the altar. The quest updates but you can't hand it in.

Screenshots/Videos or archive.org evidences:

![ondori_002](https://user-images.githubusercontent.com/35481383/35192166-bee49ec6-fe8c-11e7-9a0a-376c934a5467.jpg)

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Sorry don´t get it - is the quest generally ok - but just not live like?

**Comment by Akenatoth** [comment]
You can't hand in the quest. When you click on the altar and get the quest completion, a NPC is supposed to spawn so that you can hand it in. It doesn't spawn.

**Comment by sioding** [comment]
questmarker has been set so you know where to go for finishing the quest

**Comment by sioding** [comment]
.Fixed with patch from .17.03.2018
