### ISSUE TITLE
Barak Var Influence Items for Magus have an offhand focus.

### ISSUE THREAD

**Issue by Neutrinoo** [WarEmu/WarBugs#11182]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
There should be a tier 3 weapon for magus that is usable.  Not a focus.

Steps to reproduce the problem:
Get the tier 3 influence item in Barak Var

Screenshots/Videos or archive.org evidences:
https://cdn.discordapp.com/attachments/329292495336767488/404685155907928064/unknown.png

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Fixed with patch from 26.01.2017
