### ISSUE TITLE
Quest order side mount bloodhorn : "boom rush" no red mark on map

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11181]
![thorbolt_101](https://user-images.githubusercontent.com/16274785/35195951-7fd1ae92-fecb-11e7-8e8b-b655606e2ba5.jpg)
no red mark on map

**Comment by sioding** [comment]
![image](https://user-images.githubusercontent.com/18517842/35765457-59317a30-08c4-11e8-8221-7302b462cd48.png)

**Comment by sioding** [comment]
fixed with patch from 9.2.2018
