### ISSUE TITLE
Word of Pain does not work as expected

### ISSUE THREAD

**Issue by Fngar** [WarEmu/WarBugs#11185]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
The ability "Word of Pain" should be usable while running with back to enemies
Currently, using the ability does not trigger it, but still wastes a GCD.

Steps to reproduce the problem:
Make Word of Pain work like its similar DoT, Vision of Torment (which is demonstrated in video)

Screenshots/Videos or archive.org evidences:
You can see Vision of Torment debuff enemy, while Word of Pain does not, but still uses a GCD.
[Word of Pain.zip](https://github.com/WarEmu/WarBugs/files/1650199/Word.of.Pain.zip)

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Torquemadra** [comment]
yeah.... no, you can look at them and cast, ass-casting is not intended to be a thing here.

**Comment by Fngar** [comment]
That is fine by me, but then will you please fix the ability so I don't waste a GCD if I'm not angled enough while kiting. That is the real issue. There are other abilities that don't go off when ass casting, but nothing happens so I can make a quick adjustment and fire again.
