### ISSUE TITLE
Word of Pain bypass Concealment

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#11186]
Expected behavior and actual behavior:
Concealment should give full disrupt but it dont work on WoP.
Dunno if its Concealmen's bug or maybe WoP cant be disrupted at all?

Screenshots/Videos or archive.org evidences:

![badyl_005](https://user-images.githubusercontent.com/13823154/35205078-dcad0104-ff32-11e7-8918-b23e85e3597c.jpg)

**Comment by cimator** [comment]
Word of pain and boiling blood damage tick is undefendable, its intended iirc, should be in one of the patch notes.

**Comment by Torquemadra** [comment]
you can defend the application not the backload.
