### ISSUE TITLE
Ground target abilities going on CD when cast out of range

### ISSUE THREAD

**Issue by xyeppp** [WarEmu/WarBugs#1118]
Subject.

**Comment by Radiantknight** [comment]
Same with DI. Thing is, sometimes it sets at max distance, but most of the time it just goes on CD

**Comment by Evildoor** [comment]
To clarify a bit - it seems that this is a general issue with ground target abilities (Landmine, SF, MotM, Rituals, etc) - they go on CD with no effect when cast out of range.

**Comment by ozarmidrashim** [comment]
Replication conditions: Using hotkey to start ability, with cursor out of range and never coming into range.

**Comment by ozarmidrashim** [comment]
Further investigation reveals that if cast out of range, the local coordinates are 0,0,0. The code to reset the ability is being called but has no effect on the client.

Marking as unfixable.

**Comment by Evildoor** [comment]
Is milestone needed here? From
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=17985&p=195176

"Fixed an issue which would cause ground-targeted abilities cast out of range to fire for no effect, blowing the cooldown. The server will now be able to issue a cancel when a ground-targeted ability is cast out of range, allowing you to retry immediately."

So, isn't this bug fixed?

**Comment by Luth-RoR** [comment]
Thanks, i mass assigned all open "cannot fix yet" reports, so that this one slipped through.
