### ISSUE TITLE
Order side Ellyrion quest name : 'The Threat Revealed' 

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11187]
Sethys Stormwalk shouldn't have a yellow halo around his head because the quest is not finish.
![thorbolt_102](https://user-images.githubusercontent.com/16274785/35210104-256637e4-ff51-11e7-88cf-6e3d34caf036.jpg)

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
