### ISSUE TITLE
Order quest  Ellyrion quest name : "library of lesandria" no red mark on the map

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11189]
![thorbolt_103](https://user-images.githubusercontent.com/16274785/35210579-1693ba32-ff53-11e7-85d1-4a1486e17cb4.jpg)

The red mark should be at 53,46 the PQ shady tower

**Comment by saupreusse** [comment]
fixed next patch.

**Comment by sioding** [comment]
fixed with patch from 9.2.2018
