### ISSUE TITLE
Reekmarsh Camp Influence reward

### ISSUE THREAD

**Issue by SheldoFB** [WarEmu/WarBugs#11198]
Hello, 

It seems the influence rewards for Reekmarsh Camp dwarf chapter 8 dont work, once I have maxed my influence for the chapter it isnt allowing me to pick my rewards from the rally master Barin Oathsmiter

**Comment by sioding** [comment]
Can we have a screenshot please?

**Comment by Lheana** [comment]
Works fine for me.

**Comment by sioding** [comment]
Checked that also - works like a charm. Closing
