### ISSUE TITLE
[launcher/client] new issue with client post new way of update 

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#11191]
I have this issue between client and launcher:

Once after i alredy play and i close the client i cant re-open it, When war.exe launch i get an error and client stop work; windows dont say any erro in particula jsut ther as been an unexpected error and   it happen when the client is trying to connect to the server:(not after at handshacking , precisely when trying to connect).

 it seems. the only way/workaround is  every time use again RORupdater.exe to fix the launcher/client and then i can play normally.

i am currently using the new war.exe client and not old one.

basically it seems to be a problem between after update and when client close or an adress problem when client try to connect.

Edit: forgot to mention that of course i re downloaded both client and launcher but the issue still persist

edit: 29/01/2018:
the issue seems had restarted agina after it stopped the day after i made the  report ( i had it the report day, then got no more prob till today) , i  start to suspect is related to some strange code serverside/server lag idk....

again,  use RORupdater.exe fix the problem but need to refresh the update everytime.

edit: 30701/2018
the issue seems to persist atm, also the launcher seems to not load patchnote anymore

**Comment by MaxHayman** [comment]
Closing as no one else appears to have the issue.
