### ISSUE TITLE
(Engi) Self-Destruct has no cooldown

### ISSUE THREAD

**Issue by Pumatouch** [WarEmu/WarBugs#11195]
Expected behavior and actual behavior:

Self-Destruct/Instability to blow up pet has a 1 minute cooldown. When using my Engineer Self-Destruct  it has no CD. It simply lost its cooldown somehow. Magus is not affected when I checked.
Self-Destruct is a pretty big thing, offering really high damage in 30 feet radius, as well as knocking down affected targets for several seconds. It is with good reason it has a 1 minute cooldown. 
Could easily be abused by, say, a Dwarf Gunline full of engineers for massive effect. Well-Oiled tactic also springs to mind.

Steps to reproduce the problem:

1. Create Turret
2. Build 8 stacks of buff to raise damage, just for kicks.
3. Self-Destruct. 30 feet radius knockdown + high damage.
4. Repeat with no recourse. 

Screenshots/Videos or archive.org evidences:
![nocd](https://user-images.githubusercontent.com/16616998/35248243-b359d6ec-ffcd-11e7-94de-798d61b9a630.png)

Sincerely
 Arthur

**Comment by sioding** [comment]
Thanks for the report. For the next report: Could you please activate timestamps in your chat?

**Comment by Pumatouch** [comment]
Roger that, Sir.

**Comment by Torquemadra** [comment]
fixed direct on live

**Comment by sioding** [comment]
Fixed with patch from 26.01.2017
