### ISSUE TITLE
RVR: Getting XP/Renown/Influence for non-upleveled player kill

### ISSUE THREAD

**Issue by fesust** [WarEmu/WarBugs#11199]
Today I killed a rank 12 WH in the T2 Dwarf/Greenskin RVR zone. He was not upleveled, i was to 48.
For the kill I received 5336 xp, 203 renown and 395 influence
In my opinion i should receive 0 for all 3 when killing not upleveled people.

Screenshots/Videos or archive.org evidences:
https://i.imgur.com/k0V5ZsW.jpg

**Comment by sioding** [comment]
Sorry but this screenshot and the informations doesn´t help at all. If the guy was rvr flagged - you could kill him. You screen doesn´t show anything about you target or if he was bolstered or not.

**Comment by fesust** [comment]
As I wrote, he was rank 12. Bolster works from rank 16, so he wasn't bolstered. I didnt mind killing him, i just dont understand why i've been rewarded for killing him :)
