### ISSUE TITLE
Broken agro on mob

### ISSUE THREAD

**Issue by rhix112** [WarEmu/WarBugs#11209]
public quest - Damaz Skar
Mobs are starting agro without reason even if tank or dps starting agro them first, mobs are going immidietly to a healers, even if healer just standing and without any using skills.

![dewayne_000](https://user-images.githubusercontent.com/31020540/35329292-7416a656-0110-11e8-8423-bcd88d400ef5.jpg)

![dewayne_002](https://user-images.githubusercontent.com/31020540/35329294-744d9d00-0110-11e8-99f3-15ac5c81fac4.jpg)

**Comment by sioding** [comment]
These two screenshots with no description are not enough for a good report. Please invest some time to bring in a good description,.

**Comment by rhix112** [comment]
Mobs are starting agro without reason even if tank or dps starting agro them first, mobs are going immidietly to a healers, even if healer just standing and without any using skills.

**Comment by sioding** [comment]
Ah no i see a chapter 22 Hard PQ. Sorry there are not standard PQ´s and will be redesign to fit a warband. you should better not farm there.
