### ISSUE TITLE
Warband groups not displayed properly

### ISSUE THREAD

**Issue by fesust** [WarEmu/WarBugs#11205]
Expected behavior and actual behavior:
Given player
When joins an open warband with free slots
Then should see all the groups with people in them

When player joins an open warband with free slots
Then warband is only partially displayed
And also affects the display for other members of the warband

On the screenshot I'm in Kriser's warband. 21 people in the warband, only groups 1&2 displayed. This bug only affects my BW, it's fine on my destro characters using the same shared UI

Screenshots/Videos or archive.org evidences:
![alt text](https://i.imgur.com/IA9ZM9h.jpg)

**Comment by fesust** [comment]
One more thing. My character went through a name change if that's any help

**Comment by fesust** [comment]
And one more thing, guild name has some hungarian letters in it: Sárkány Lovagrend

**Comment by MaxHayman** [comment]
@sioding I think this was fixed.

**Comment by sioding** [comment]
fixed with patch from 1.12.2018
