### ISSUE TITLE
ELF PQ CH1 mobs are not spawning

### ISSUE THREAD

**Issue by TibbyB** [WarEmu/WarBugs#11204]
When I tried to do the CH1 PQ from Elf side in Blighted Isle, "House Arkaneth" - Stage 1, the mobs are not spawning. All I can see are the Bolt Throwers. 

![jukylostaratus_001](https://user-images.githubusercontent.com/32936075/35292704-064e8cce-007a-11e8-843f-e368b700d431.jpg)

![jukylostaratus_000](https://user-images.githubusercontent.com/32936075/35292787-50fada16-007a-11e8-9cf8-e39f64f5842e.jpg)

**Comment by Lheana** [comment]
#10862

**Comment by frankystein65** [comment]
I'm having this same issue.  I know it worked a week ago.  I've tried the PQ on two different characters.  stage one does not spawn the NPC's and only the bolt throwers are seen

**Comment by Lheana** [comment]
Known issue. Must wait for a server reboot.

**Comment by iwka53** [comment]
not spawning again :(
