### ISSUE TITLE
/stuck did not worked.

### ISSUE THREAD

**Issue by NervZ** [WarEmu/WarBugs#1120]
So i stucked at the stairs near AH at IC. I typed /stuck and after 20s i got logged out. When i got back i was at the same spot. I had to BoB to unstuck my toon.

**Comment by Reoddry** [comment]
Last patch stated, "/stuck has been modified. Entering /stuck once will result in the new handling. Entering /stuck again during the logout period caused by the first /stuck will warp you to Nordland or Norsca as before." This should work for situations like this.
