### ISSUE TITLE
Guild Search not working

### ISSUE THREAD

**Issue by Akenatoth** [WarEmu/WarBugs#11206]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

In the guild search window (G) I should be able to set filters and click the "Search" button to search for guilds. The search button doesn't work, it's grey. It worked before the last update.  The character I tested this with is currently not in a guild. I asked other people (both in a guild and not) to test it as well and it's greyed out for everyone.

Steps to reproduce the problem:

Login a character, press G to open the guild search window (make sure you're in the "Search" tab), set some broad filters and see if the "Search" button works or not (for me, it doesn't).

Screenshots/Videos or archive.org evidences:

![tarul_000](https://user-images.githubusercontent.com/35481383/35298763-784f1592-0083-11e8-9d76-6aa837792845.jpg)

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by MaxHayman** [comment]
Seems to be working for me @sioding

**Comment by sioding** [comment]
double check - works for me too - close
