### ISSUE TITLE
Squig Pets and PQ Influence

### ISSUE THREAD

**Issue by magter3001** [WarEmu/WarBugs#1121]
Currently, if you're on your squig herder and your pet squig gets the deathblow, you don't get any influence for the kill. This happens in PvE for sure. Unsure if it happens in PvP but another Squig Herder told me he didn't get influence in PvP either... I don't know because my character is already maxed. :D

**Comment by Evildoor** [comment]
Part of 
https://github.com/WarEmu/WarBugs/issues/1229
