### ISSUE TITLE
Zone locks reward issues

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#11217]
As in title, don't know how it is for winners, but as losing side all I got was bag roll 3 times in a row, no extra renown, no extra medalions/seals
Screenshots below
![shey_008](https://user-images.githubusercontent.com/18032193/35411094-c1f6b69c-0217-11e8-945b-d4f69c5a7bba.jpg)
![shey_009](https://user-images.githubusercontent.com/18032193/35411095-c21a0c46-0217-11e8-9f1a-e765d26509b9.jpg)
![shey_010](https://user-images.githubusercontent.com/18032193/35411096-c236447e-0217-11e8-9b1e-302aa3926363.jpg)

**Comment by szejoza** [comment]
Update (dont know if you were fixing it this morning or not)
On win I got rewarded with double medalions/seals
![shey_011](https://user-images.githubusercontent.com/18032193/35443269-ca45d574-02aa-11e8-8a6d-a6040007a186.jpg)

**Comment by szejoza** [comment]
Cheers
Losing side still isn't rewarded with medalions/seals though, creates even bigger gap between winners/losers
![shey_012](https://user-images.githubusercontent.com/18032193/35451798-b47011c8-02c4-11e8-9509-233ce8f80a64.jpg)

**Comment by sioding** [comment]
Fixed with patch from 26.01.2018

**Comment by szejoza** [comment]
The new screenshot (Praag zone lock) was made after yesterday patch. Will try to report how it is today
