### ISSUE TITLE
Bags not mailed from zone flip.

### ISSUE THREAD

**Issue by Deadnod** [WarEmu/WarBugs#11213]
Expected behavior and actual behavior:
Zone flipped on evening of 1/23 (TM?).
Mine and my fiance's character's were playing an SC when the zone flipped. I saw I had a white bag. She saw she had a blue bag. The scenario ended at an odd time with a score of 300 to some odd number and time still left on the clock. We did not receive our loot bags in the mail. We assumed that the loot would probably be in the mail the following day when we logged in. It was not. 

I'm unsure how to replicate. It may be pertinent that we are playing in the same household.

**Comment by sioding** [comment]
Just wait until the next server restart.
