### ISSUE TITLE
after removing object from appereance "" the pop message yes or not "" i think the game destroy that item ""sash of hatred22

### ISSUE THREAD

**Issue by Cosmine** [WarEmu/WarBugs#11211]
*tha item sash o f hatred is not more inside back pack ,

please any gm cal list or watch my log caracter name: Cosmine 

cheers
regards 
Paolo 

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Please create an ingame ticket.
