### ISSUE TITLE
Ability Pandemonium hitting me after SC end

### ISSUE THREAD

**Issue by baroke** [WarEmu/WarBugs#11212]
When a SC ends the character should be cleansed from any dots he had while inside the SC.
But i got hit by Pandemonium ability for several seconds after the SC ended, in fact it also reapplied itself after the SC end.

![klain_001](https://user-images.githubusercontent.com/20115114/35364388-9385b1aa-0177-11e8-9995-a5833bb94bb8.jpg)
![klain_002](https://user-images.githubusercontent.com/20115114/35364390-99812c88-0177-11e8-9866-58d614f349b8.jpg)

**Comment by sioding** [comment]
Thanks for the report. Sadly these screenshots doesn´t help at all. Please use the show us the combat log with activated timestamps if this issue occur again.
