### ISSUE TITLE
One of my characters gets moved inside Gunbad every login from other zones

### ISSUE THREAD

**Issue by Beerburps** [WarEmu/WarBugs#11214]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: Character: Beerburps was logged out in the mouth of the Khorgash Manbreaker beastlord tunnel in Reikland.  Now on all logins, no matter where he is logged out, character select screen says he in is Mount Gunbad, and tries to put him there.  Which then crashes back to character select screen, requiring restart of game.  Out of 9 attempts, twice successfully reappeared in Gunbad, left and logged out in different zones.. on login was back inside Gunbad.

Steps to reproduce the problem:  Log out in mouth of Manbreaker tunnel.

Screenshots/Videos or archive.org evidences:  Game crashes, no screenshots possible.

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Have you tried double /stuck on the loading screen and bindiung again at a rally master?

**Comment by Beerburps** [comment]
Yep that fixed the issue, thanks.
