### ISSUE TITLE
Beastial Tokens bugged

### ISSUE THREAD

**Issue by DakkBlakk** [WarEmu/WarBugs#11216]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: Beastial tokens are awarded when you kill certain mobs in the world. as you know.

i went and killed 3 enemies earlier that all gave me the beastial token unlocks in the Tome of Knowledge yet in my bags i had only one beastial token. 

i've spent only two bestial tokens on my character. one i got by accident when i was lower lvl i believe i was lvl 33 in praag when i got my first beastial token. i spent that token and moved on.

I'm now lvl 38 and i should have 2 more beastial tokens in my bags (i spent the one it did award me) yet i do not.

i know you guys are busy. i'm so appreciative you have brought Warhammer RoR to us, it was missed by it's many fans. Your time on my ticket is appreciated.

Thank you,
DakkBlakk

Steps to reproduce the problem: Kill the same Beastial token awarding enemies i did. Bridge troll, Goremaw, Khurraak Might horns,

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Lheana** [comment]
So ONCE AGAIN, before making a report, CHECK RoR Wiki!
Among the 3 unlocks you mentioned, only one gives Bestial Token as reward:
- [Bridge Troll](https://wiki.returnofreckoning.com/index.php/Takes_its_Toll)
- [Goremaw](https://wiki.returnofreckoning.com/index.php/Dispense_Justice)
- [Khurraak Might-Horns](https://wiki.returnofreckoning.com/index.php/Bossy_Beastie)
