### ISSUE TITLE
Keep Lord Quest "Defend XXX" kills are also counting in Scenarios

### ISSUE THREAD

**Issue by hasashim** [WarEmu/WarBugs#11210]
Today i was playing nordenwatch sc and everytime i got a kill inside the fortress flag i got kills for Defend mandred's hold quest,and even completed it

**Comment by wargrimnir** [comment]
Corrected keep defense quests so they only apply to the keep area. Several were not assigned.

**Comment by sioding** [comment]
Fixed with patch from 2.2.2018
