### ISSUE TITLE
speed bug

### ISSUE THREAD

**Issue by grindill** [WarEmu/WarBugs#1122]
I don't know how it occurred but was involving mount summoning, I was moving fast and snares didn't seem to work on me . I hope the 2 mindless destros that were hitting me recorded the deed .
so...I was mounted ,I got hit by a SH I auto dismounted and I summoned the mount again ,only I was moving fast but no mount ,after every respawn I was moving ,fast I relog and things were ok.

**Comment by Evildoor** [comment]
I presume that this issue was fixed.
