### ISSUE TITLE
Scenario froze up in stroke with server. Gave us stupid amounts of exp and leveled guild to 31.

### ISSUE THREAD

**Issue by Dirksolomon** [WarEmu/WarBugs#11220]
Server had some stroke during scenario and kills gave us stupid amount of exp, making guild rank up from rank 2 to 31 in span of a five minutes. For some reason though the exp gained in scenario did not affect characters. Guild affected: I The Unnamed I, friends also reported seeing this bug in the guild.

![largh_000](https://user-images.githubusercontent.com/13361058/35460858-1227e5e2-02ee-11e8-824e-09bad410001c.jpg)

**Comment by sioding** [comment]
Fixed with patch from 26.01.2017
