### ISSUE TITLE
Low Priority - Auto Roll Settings

### ISSUE THREAD

**Issue by swilkers808** [WarEmu/WarBugs#11223]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
The auto roll selections are not saving when you exit the game. You need to set them up every time that you log in. 

Steps to reproduce the problem:
Set up auto roll, log out and log back in. 

Screenshots/Videos or archive.org evidences:
I can provide screens if necessary but this is easy to reproduce. 

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Well - on my side - the Autoroll settings will be saved.

**Comment by swilkers808** [comment]
Seems to be working now and holding the settings. 
Cheers
