### ISSUE TITLE
Dwarf T3 Epic Quest - Ancient Horror

### ISSUE THREAD

**Issue by zaxxo1990** [WarEmu/WarBugs#11229]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Expected: I'm on step 3 of the Ancient Horror epic questline and i need to collect Brightstone Flecks which should be collected in the bloodspike cave by clicking brightstone deposit.

Actual: I cant click brightstone deposit, i tried all of them. No brightstone flecks are collected.

Steps to reproduce the problem:

Accept this part of the quest and try it out?

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Well have you searched in the cave? Works fine for me:
![image](https://user-images.githubusercontent.com/18517842/36352614-e2877c6e-14bb-11e8-8a65-d9be6c7c691f.png)
