### ISSUE TITLE
Glomp da Squig Masta not teleport away

### ISSUE THREAD

**Issue by stillwaterww** [WarEmu/WarBugs#11226]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
At 90% hp the boss is supposed to teleport away and let us handle the squigs he spawns, instead he keep doing his random aggro attaks on the group. Making it near impossible to kill this boss.

Steps to reproduce the problem:
Get the boss below 90% hp

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by grunbag** [comment]
The boss doesn't teleport as on live. Instead he ride a squig and still attack you. You have to deal with both. If it's too hard make feedback on forum, but what you describe is intended

**Comment by Hargrim** [comment]
It's doable the way it is.
