### ISSUE TITLE
Invisible and unattackable q-mob "bait & switch"

### ISSUE THREAD

**Issue by LuckyRaider** [WarEmu/WarBugs#11225]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Questmob Doomglade Vraslyn (Quest: Bait & switch) has a wrong spawn location and couldn't target to attack. Looks like the spawn is under the map or inside the house - no cave or entrance there

Steps to reproduce the problem:
I talked yesterday to an gm and he kills him to become respawn, the mob spawns at the same position under the map/inside the house without been attackable. 
I relogged before for myself, and talked to my guildmates if they had the same problem - "aye, the same"
I ran around the house and spot to take a look if there is an entrance (no one) and hit "tab"
 to target the mob, via tab i could found him but still isn't to attack and no where to see. 

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
fixed with patch from 9.2.2018
