### ISSUE TITLE
Cant login with sepcific char

### ISSUE THREAD

**Issue by mubbl** [WarEmu/WarBugs#11228]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
I cant login on my bright wizzard, stands in altdorf, without the exe stop working.
Deleted cache and settings for the bw but nothing changed

this is my first report, so if any more information needed let me know

Steps to reproduce the problem:
-

Screenshots/Videos or archive.org evidences:
-

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
You won´t get any help here. Please use the forum for this: https://www.returnofreckoning.com/forum/viewforum.php?f=5
