### ISSUE TITLE
Gunbad public quest after reset boss doesn't reset

### ISSUE THREAD

**Issue by rhix112** [WarEmu/WarBugs#11227]
after wipe on boss right wing first boss, public quest doesn't reset with mobs. And wall behind boss open for continue
![smileypie_000](https://user-images.githubusercontent.com/31020540/35484956-4886dab8-0469-11e8-8871-dd4c369d2bd4.jpg)

**Comment by stillwaterww** [comment]
Far as I know this is currently working as intended, they increased the time you get to complete the final stage of each pq to 15 minutes to compensate untill they figure out what is causing the bugged 4-5x kill contribution on the pq's.

**Comment by grunbag** [comment]
Fixed already
