### ISSUE TITLE
Kegs end Questgiver still available

### ISSUE THREAD

**Issue by sioding** [WarEmu/WarBugs#11221]
a lot of Bugman´s Brewman are still on duty. Here a sample in Chaos Waste:

![image](https://user-images.githubusercontent.com/18517842/35470110-bd7a2bbc-0343-11e8-9a34-38dcf121283f.png)

**Comment by wargrimnir** [comment]
Disabled the rest of the Keg End NPC's

**Comment by sioding** [comment]
Fixed with patch from 2.2.2018
