### ISSUE TITLE
server selection buttons spawned instead of actionbars / character selection UI

### ISSUE THREAD

**Issue by Yardape** [WarEmu/WarBugs#11224]
![yobb_001](https://user-images.githubusercontent.com/19935059/35479175-a316b282-043c-11e8-9070-d333e7c44d5f.jpg)

Took a pop for a Warzone while in Nordland, spawned in the city with these buttons instead of action bars.
could still use keyboard movement buttons, but nothing else, no popup windows or the Esc menu.

**Comment by velkos4ever** [comment]
i can confirm this happened to me also.i took a scenario and when it was loading the game tried to crash to a black screen only to come back after 4 secs to my character with the same problem....here's a picture below
![nighteyes_533](https://user-images.githubusercontent.com/16551075/35866006-a97eea9e-0b5e-11e8-8de2-e895f17c1b51.jpg)

**Comment by Yardape** [comment]
Here is another one, that happened on a guildy mate: again they were out in the rvr lake, took the senario pop, then spawned in the city with action bars removed and server selection buttons instead.  only way to fix is to close game down.

https://gyazo.com/9d3059fddd54446110416e6797e1b044

**Comment by Yardape** [comment]
Oh yeah and you get the quitters debuff for it too

**Comment by Telemachos2018** [comment]
Just had this happen to me as well.

![scenario](https://user-images.githubusercontent.com/51891475/59570126-00b71b80-9059-11e9-9a98-45f89490b9b3.png)

**Comment by MaxHayman** [comment]
Has anyone experienced this recently?
