### ISSUE TITLE
Order (and maybe Destruction) War mount

### ISSUE THREAD

**Issue by Rayzeefool** [WarEmu/WarBugs#1123]
Yesterday, i managed to reach the amount of 150 gold, required to buy the war mount in the capital (as Order). After the trasaction, the item correctly appeared in my inventory, but it does not work, i' ve it from the inventory, no way, from the hotbar, neither, i tried it again in both ways after disabling an interface addon and rebooted the game, and kept not working.

Maybe I was just unlucky and i' ve picked up the only mount that does not work, or simply all that sort of mount, in this stage of development of the game don't work yet, since is low priority thing.

**Comment by Titoos** [comment]
As far as I remember 150g  (60%speed) mounts were usable by 40rank characters only.

**Comment by ozarmidrashim** [comment]
They're not linked to any ability, so I don't know why they were made available in the first place.

**Comment by Evildoor** [comment]
This was fixed some time ago.
