### ISSUE TITLE
Quest NPC level too low

### ISSUE THREAD

**Issue by fesust** [WarEmu/WarBugs#11236]
Expected behavior and actual behavior:
Tier 2 Greenskin Epic Quest Boss Huntin'. Almost the final part is to kill Nogaz, for level 18-20 players, however the target NPC (Angry Nogaz) is a level 13 one, which is a but underwhelming for this stage. He should be a lvl 19 just like the Ladz around him.

The final part is to kill Runepriest Stelvia. She should be a champion just like the all the other Epic Quest final bosses. However she's a lvl 17 normal mob.

Screenshots/Videos or archive.org evidences:
![giggitygoo_000](https://user-images.githubusercontent.com/22993093/35563018-a2c05c00-05b5-11e8-95fc-982af718a1df.jpg)
![giggitygoo_001](https://user-images.githubusercontent.com/22993093/35563346-b0e1ec12-05b6-11e8-8914-ceb0fe4ca72c.jpg)

**Comment by sioding** [comment]
Fixed with patch from 2.2.2018
