### ISSUE TITLE
[Gunbad] Instance save for killing healer npc

### ISSUE THREAD

**Issue by stillwaterww** [WarEmu/WarBugs#11237]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
I expect to be saved to the instance when killing an instanced boss. However the healer npc's getting involved in the fights and subsequently dieing is also giving me lockouts.

Steps to reproduce the problem:
Let the npc be killed

Screenshots/Videos or archive.org evidences:
![gettingsaved for killing healers](https://user-images.githubusercontent.com/19287032/35600920-b62e84f8-0630-11e8-83d4-d37e633286d2.png)

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by stillwaterww** [comment]
I would like to add to this that when the healer npc dies to the boss aggroing in the instanced parts of the dungeon we no longer had the "terror" debuff. Making it possible to resurrect mid fight and giving us a considerable edge during these fights.

**Comment by sioding** [comment]
fixed with patch from 9.2.2018
