### ISSUE TITLE
[Zealot] Ritual of Innervation

### ISSUE THREAD

**Issue by Servant-of-Chaos** [WarEmu/WarBugs#11238]
According the tooltip, every attack got a %20 chance to regenerate 50 action points. It's working fine with single target but when using AoE abilities on several targets you have infinite ap, which shouldn't.

There was a icd back on live if i remember correctly.

**Comment by sioding** [comment]
Thanks for the report. Plase add your testing screenshots and a proper evidence how it worked on live.

**Comment by Servant-of-Chaos** [comment]
Sadly, i couldn't find anything on old patchnotes or youtube videos from live but i can still provide a video that you have infinite ap all the time when spamming aoe abilities on several targets. it shouldn't work like that because it isn't %20 according the tooltip.

**Comment by Laurentz18** [comment]
I used AOE dps build at live with Ritual of Innervation that was also pulsing from Waves of Chaos tactic. Against a group or more of enemies, yes, you effectively had infinite AP because you were hitting 3 or 4 people every second. This was one of the reasons I went AOE spec, the more people I was attacking the more AP I had.

**Comment by Servant-of-Chaos** [comment]
Another thing about AP Ritual of Zealot; AoE Morales can trigger it, like Raze ect.

**Comment by Blubberino** [comment]
I don't know where you got your info but that's how the ritual always worked. Order has 20% per skill destro has 20% per hit. If you hit several enemys you get several procs. Order ritual isgood for healers/casters while destro is useless for healers therefore better for meeles and esp. for aoe classes.

**Comment by grunbag** [comment]
Those abilities have been mirrored
