### ISSUE TITLE
Quest:"Great Green Mushroom", Thunder Mountain, Destruction

### ISSUE THREAD

**Issue by Grunbeast** [WarEmu/WarBugs#11235]
You need to kill a giant Roshk in marked area. There no giant in there and I could not find any giant with this name in TM.
![grunbeast_065](https://user-images.githubusercontent.com/35007878/35549763-6b361a8c-0587-11e8-8cda-000d692f39d9.jpg)

**Comment by Pearlpetalbee** [comment]
There was a Giant outside Gromril BO near lava and mushrooms in orvr area. But he is not there for a long time.

**Comment by NorKalli** [comment]
Replaced Roshk, updated questmarker

**Comment by sioding** [comment]
fixed with patch from 26.05.2018
