### ISSUE TITLE
Squig herder bugz

### ISSUE THREAD

**Issue by Nihilan** [WarEmu/WarBugs#11231]
hello,..
I would like to report some bugs i ve found while playing a squig herder....
1) While in squig armor the skills "Git Em!" and "Ard Noggin" and generally any path of stabbin specialization skills do not work. The character may remain inside the squig but does no damage whatsoever either in pvp or pve.
2) the skill "stop runnin" has a 3sec cast however the arrow travels very very slow, like takes up to 30 sec to reach the target by which time the target may be already dead or gone and thus the ability is cancelled. In order to describe how slow it travels it is possible to shoot the arrow to an enemy and then if i run to the target to melee him the arrow i already shot would not have reached the target yet. 
3) the skill "explodin arrer" it says by its description that does xx elemental damage to the primary target and xx elemental damage over x sec to additional targets 20ft max distance from primary target... in Pve the direct dmg does affect primary target however no nearby enemies are affected by the ability, in Pvp neither the primary nor the secondary dmage to surrounding enemies seems to take effect. 
4) the stances of a squig do not work,... supposedly defensive stance means the squig attack the enemy that attack the character but this is not happening. Same with passive stance, meaning squig should stay put no matter what,... all the same the squig attacks the target of the squig herder ignoring the command for passive stance.
5) if a squig herder has a squig by his side but he goes afk and then disconnects because of inactivity when he relogs the squig he had eqquipped has become an npc charging in straight line to its max distance and resets doing this loop endlessly,...noting that the name of the squig remains " characters' name squig" also is interesting that this bugged squig will remain active till server reboots/resets and is account bound meaning that if the player logs out and relogs with different character he can still see the running squig 
6) sometimes during zone change if a squig is eqquiped during the change the squig disappears,...while showing is still active yet it doesnt exist

**Comment by sioding** [comment]
Thanks for the report(s) please follow the rules. One of them is:

*One issue per ticket

Only report one issue per ticket as multiple issues within one ticket is harder to track and harder to address.
