### ISSUE TITLE
Inevitable Power Quest T3 Chaos Epic Quest

### ISSUE THREAD

**Issue by IneptCorpse** [WarEmu/WarBugs#11240]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Kill Lady Krueger at the last floor of the Tower in Kruegerhaus Public Quest. Get the crown and return to quest giver

Steps to reproduce the problem:
I have done this at least 5 or 6 times, crown never appears and quest will not complete

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
I went through the whole quest and it works like it should. I could kill Lady Krueger and was able to give the quest back to Jorana. Please show some sreenshots what happens when you kill Lady Krueger.

**Comment by sioding** [comment]
No reaction for 8 days. Close.
