### ISSUE TITLE
Quest Bug - Nurglings

### ISSUE THREAD

**Issue by swilkers808** [WarEmu/WarBugs#11248]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Norsca - Quest - Nurglings
Kill 8 Belierot Nurglings
There are no Nurglings in the area, onle Belierot Scavengers. 

Steps to reproduce the problem:
Accept quest  - Head to area. 

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
The quest is working fine. The nurglings will be there if you head to stage 2 of the PQ which is in the quest area.
