### ISSUE TITLE
Balanced Mending

### ISSUE THREAD

**Issue by kabbolt** [WarEmu/WarBugs#11242]
Hello, Balanced Mending is not implant in the Game ( Tactic Archemage - Your Healing Energy is more 35% effective on other people, but 15 % less effective on you )

The Value of the Heal don't change when i switch of target. This Tactic have Never Work that why i repport.

Cordially

Kabbolt

**Comment by sioding** [comment]
Can you please add your testing screenhots?

**Comment by sioding** [comment]
no response for 12 days  -close
