### ISSUE TITLE
Scenario Queue - Cannot Cancel

### ISSUE THREAD

**Issue by swilkers808** [WarEmu/WarBugs#11246]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Cancel queue - remove player from queue

Steps to reproduce the problem:
Sign up for queue - Remove self from queue
Cancelling the queue for a scenario does not remove you from it. 

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Weird. Haven´t had that before. Any Errormessages in the chat?

**Comment by swilkers808** [comment]
No error messages are displayed. You simply cannot exit from the queue.




*This message was brought to you by the numbers 0 and 1*

**Comment by Kaelang** [comment]
Leaving the queue now correctly removes you from the queue. If this persists moving forward in the latest versions of RoR, please re-open the issue.
