### ISSUE TITLE
New ability of WL pets?

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#11243]
NPC mobs have an ability that hits hard in absorb and probably pet has the same...

https://monosnap.com/file/6aF10GPAVNgJrCkSgjUl2FMOSg8LDZ

https://monosnap.com/file/8wlsKdDf4T2jgHvENn4EGgxvGN1i1g

P.S.: i didnt check turrets, squigs and deamons

**Comment by Nfkillz** [comment]
https://monosnap.com/file/xKZtbb3Pphpu5G8cqcSxu5zQESpfpX

**Comment by Torquemadra** [comment]
Just how absorbs show, its the general attack being mitigated.

**Comment by Nfkillz** [comment]
whats the general attack? 
https://monosnap.com/file/xKZtbb3Pphpu5G8cqcSxu5zQESpfpX

**Comment by Nfkillz** [comment]
AA 54 dmg
