### ISSUE TITLE
Mastery respec prices jacking up via renown respec

### ISSUE THREAD

**Issue by SACancel** [WarEmu/WarBugs#11249]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: 
Alright so, I went to respec my rank 14 squig herder and noticed the price of his mastery respec was 5g 80s...when I had never respec'd before. The only thing I had done earlier was my renown respec, so I figured I'd see on another character. I got on my rank 12 magus and checked the respec, it was 20s I was like alright cool. Then I did a renown respec on my magus and the price  of mastery jumped to 5g 80s. Upon relog my squig herder's mastery price was down to 40s, which is still one respec higher than usual. Checked my magus as well, his mastery was back down to 20s. Something is causing a crossfire between both respec systems maybe?

Steps to reproduce the problem: 
check mastery respec price, reset your renown points and check mastery respec price again.

Screenshots/Videos or archive.org evidences:
https://imgur.com/a/HMyP4

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Natherul** [comment]
the system for mastery and renown have changed since this report, is this still an issue?
