### ISSUE TITLE
name registrar after paying gold does not change surname

### ISSUE THREAD

**Issue by stormin1971** [WarEmu/WarBugs#11244]

**Comment by sioding** [comment]
Which surname have you tried? Any special characters? Some Errormessages?

**Comment by wargrimnir** [comment]
I suppose if you hit the naming filter with something unsavory, it would just keep your gold and give you nothing. Which I would be fine with.

**Comment by stormin1971** [comment]
I suppose if you hit the naming filter with something unsavory, it would
just keep your gold and give you nothing. Which I would be fine with. (dont
see how its what i got now just different spelling so it wouldnt have
allowed it in the first place....so can i get an answer now?

**Comment by stormin1971** [comment]
no its currently Depayen and wanted dePayen

**Comment by sioding** [comment]
OK no Bug. The NPC is working as intended.
