### ISSUE TITLE
Black Fire Basin Objective

### ISSUE THREAD

**Issue by velkos4ever** [WarEmu/WarBugs#11245]
Hello today i run into a problem in Black Fire Basin i took the flag and i could't give it to the location it supposed to go... same thing happened to a zealot in the scenario as well.here some picture below:
![nighteyes_528](https://user-images.githubusercontent.com/16551075/35696256-ad0194d2-078f-11e8-95f9-1ae36438e801.jpg)

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Kaelang** [comment]
The objective is accepting turn-ins as intended. If you can recreate such issue, please re-open this ticket with further evidence to support.

Thanks.
