### ISSUE TITLE
Flashfire (proc is consumend on cast start)

### ISSUE THREAD

**Issue by Scrilian** [WarEmu/WarBugs#11247]
Proc is consumed on the cast start instead of the actual cast finish. Makes it barely playable with any kind of terrain due to constant interruption.

**Comment by sioding** [comment]
Thanks for the report. But this isn´t a bug for the tracker. If you want to change something like that please use the forum

**Comment by sioding** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=15&t=25230

**Comment by Scrilian** [comment]
https://www.youtube.com/watch?v=BR4r5eVuOiA
if it helps

**Comment by tiarnaz** [comment]
i can confirm this bug.
Proc is consumed every time u start a cast, and you lose the Flashfire buff in many case, like target goes out of range, out of line of sight, cast interrupted, definitely ALL the thing that make ur cast incomplete.

in this state the tactic is broken.

my possible solution
Solution #1 add the range/line of sight/other check at the end of the cast and not during the cast.
Solution #2 reintroduce the old flashfire mechanic, with an internal cooldown increased

**Comment by Natherul** [comment]
should be sorted with the next DB push / patch
