### ISSUE TITLE
Officer medalions drop from BOs instead of conqueror

### ISSUE THREAD

**Issue by Timmitz** [WarEmu/WarBugs#11259]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*Officers medalions drop from BO def ticks instead of conqueror
![falaria_016](https://user-images.githubusercontent.com/36116924/35822130-7fcfe0c6-0aab-11e8-9385-921a8470c9f1.jpg)
![falaria_015](https://user-images.githubusercontent.com/36116924/35822131-7fef3e8a-0aab-11e8-9b85-86f962f07ecc.jpg)

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by wargrimnir** [comment]
Intended

**Comment by Timmitz** [comment]
quoting from patch notes:
"- Rewards from flag microticks are now based on your character tier, not zone tier"
char is rr 48 and yesterday conq medals dropped?

**Comment by Timmitz** [comment]
soz, quote should have been:
 
- Rewards from flag microticks are now based on your character tier, not zone tier
- Rewards from flag takes are now based on your character tier, not zone tier
