### ISSUE TITLE
[New Reward System]Empty Gold Bag-2018/02/03-Shadowlands

### ISSUE THREAD

**Issue by tionblack** [WarEmu/WarBugs#11250]
I got an empty gold bag in the shadowlands after the new system changes.

Screenshots/Videos or archive.org evidences:

https://imgur.com/BJngDiJ

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Tyrpak** [comment]
Same, but in T4 DW.

Character is 39/40 , maybe that's the problem.

![emptygold](https://user-images.githubusercontent.com/35927891/35773038-28dac728-0947-11e8-864e-8b46c8a39e6c.png)

**Comment by sioding** [comment]
fixed with patch from 9.2.2018
