### ISSUE TITLE
No Skin Shown

### ISSUE THREAD

**Issue by donsastre** [WarEmu/WarBugs#1125]
Well i saw an Post where a IB Belt had no Skin ... now i have the same issue with a slayer head..

Item: Murderer's War Shroud

hope there's a chance to activate the skin :)

greetings

don

**Comment by donsastre** [comment]
as a mate told me, the willpower stat is  wrong too :3 thx for spending your time with such issues :)

wish u best

greetings 

don

**Comment by Reggaewaldo** [comment]
I have deleted the willpower and changed the head so that it now includes a model.

I'm a bit unsure about the itemization though since I can't seem to find any online source on it.

**Comment by Reggaewaldo** [comment]
If the item has an online source and that is found please reopen this.
