### ISSUE TITLE
respawn from death in DW in Caledor

### ISSUE THREAD

**Issue by Timmitz** [WarEmu/WarBugs#11253]
after death in DW people spawn in caledor keep

**Comment by Hargrim** [comment]
Fixed in next patch, closing.

**Comment by Timmitz** [comment]
No mount fer this one? Lots of draws for order instead of losses due to minutes wasted on regroups 😎

Verzonden vanaf mijn Windows 10-telefoon

Van: Hargrim<mailto:notifications@github.com>
Verzonden: donderdag 15 februari 2018 21:59
Aan: WarEmu/WarBugs<mailto:WarBugs@noreply.github.com>
CC: Timmitz<mailto:thousandandones@hotmail.com>; Author<mailto:author@noreply.github.com>
Onderwerp: Re: [WarEmu/WarBugs] respawn from death in DW in Caledor (#11253)


Fixed in next patch, closing.

**Comment by sioding** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366#p118993
