### ISSUE TITLE
[NPC/Vendor] order Dominator gear at destro's Vanquisher's Quartermaster in IC

### ISSUE THREAD

**Issue by Tyramissoux** [WarEmu/WarBugs#11257]
**Expected behavior and actual behavior:**
Normally, when you click the vendor, you see all the gear you could buy for your career (which works fine),  but if you click "show all" at the vendor you should be able to see all other career's buy options for your own faction, too. As destro you'll only get order careers shown (see screenshot) while it's working fine on order side.
It's not that order is shown additionally, it is there exclusively. No other destro careers.

**Steps to reproduce the problem:**

Go to the vendor Haarkoth the Doombringer as destro and choose "show all" on the dropdown menu.

**Screenshots/Videos or archive.org evidences:**

![annnoying_038](https://user-images.githubusercontent.com/13544944/35781800-205a3810-09ef-11e8-8ded-8a9fcbba7985.jpg)

**Comment by NorKalli** [comment]
Works fine for me
