### ISSUE TITLE
Double Spawn "rorg 'eadbutta"

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#11252]
NPC rorg 'eadbutta (thunder mountain, ork chapter 17) seems to have an identical twin brother living in kadrin vally (chapter 22)

**Comment by Lheana** [comment]
Would need to verify it is not meant to be that way.

**Comment by MightyPhred** [comment]
as verification i offer the fact that both spawns of him offer the same quests

**Comment by Lheana** [comment]
From what I can see they are all meant to be where they are, these are not real double spawns (i.e. the same NPC at the same location several times).
