### ISSUE TITLE
[Ability] Flame Breath not working properly

### ISSUE THREAD

**Issue by Servant-of-Chaos** [WarEmu/WarBugs#11267]
Flame Breath is a "damaging+dot" ability of path of conflagration tree but it's acting like a dot here.

![flame breath](https://user-images.githubusercontent.com/35977688/35924126-3add2a76-0c33-11e8-8e2f-230d50e88aaf.jpg)

![icespikes](https://user-images.githubusercontent.com/35977688/35924129-3d6574f6-0c33-11e8-815f-748b27862e12.jpg)

Flame Breath not working with these abilities below  :
![funnelpower](https://user-images.githubusercontent.com/35977688/35924188-630d8018-0c33-11e8-9114-1a228d9c4d2a.jpg)
![edf](https://user-images.githubusercontent.com/35977688/35924191-66581ada-0c33-11e8-9a15-879917581097.jpg)
![wildfire](https://user-images.githubusercontent.com/35977688/35924218-7e53f74e-0c33-11e8-822e-cf277db6bd90.jpg)
![for](https://user-images.githubusercontent.com/35977688/35924228-83e5775a-0c33-11e8-94ee-a3ea0dad8059.jpg)

Flame Breath was proccing all 4 abilities above on live with first tick, the rest was acting like a normal dot.

**Comment by sioding** [comment]
As you stated how it works on live. Can we please see any proper evidence for this?

**Comment by Servant-of-Chaos** [comment]
https://youtu.be/Hk-UVsBESiU?t=80 Check 1:23 and after, Flames of Rhuin procs from Flame Breath. Sadly couldn't find a BW with Wildfire and Embrace the Flames yet on youtube. But if Flames of Rhuin procs from Flame Breath's first tick it should (was) procs Wildfire and Embrace the Flames aswell.

**Comment by Servant-of-Chaos** [comment]
I found this on web to show flame breath and wildfire relationship:

http://web.archive.org/web/20080916142437/http://www.wardb.com:80/spell.aspx?id=8211

![originalwildfire](https://user-images.githubusercontent.com/35977688/35973518-cef73e78-0ce6-11e8-8a12-bbe4ef71825b.jpg)

**Comment by Torquemadra** [comment]
things change, hence the fact that you linked a tactic from long before 1.48. Flame breath is a dot, not a damaging + dot

**Comment by Servant-of-Chaos** [comment]
![infernal wave](https://user-images.githubusercontent.com/35977688/36126819-4609a3b6-106b-11e8-92c0-ce1fb91fb607.jpg)

Also another thing i forget to mention, Flame Breath is mirror of Infernal Wave, not Ice Spikes. Both of abilities builds 20 career mechanic, both abilties got same cooldown, both abilities get benefits from tactics:

Neverending Agony : Decreasing cooldown of Infernal Wave for 5 seconds.
Fiery Reserves: Decreasing cooldown of Flame Breath for 10 seconds.

With the same approach, Flame Breath's first tick shouldn't be instant at the moment ? Because Ice Spikes starts damaging after 2 seconds. Again, Flame Breath was a damaging + dot ability on live, I didn't see anything on wikipedia/forums/website about Flame Breath change except this : 

Azarael :
Huh. You're proven correct with https://www.youtube.com/watch?v=Hk-UVsBESiU at 1:23.Not only that, but it procced Flames of Rhuin too. @Torquemadra 

https://github.com/WarEmu/WarBugs/issues/4530

**Comment by emailkook** [comment]
It was damaging+dot on live. Being BW Team Lead on live kinda helps with the proof 😊
