### ISSUE TITLE
Quest:"Beat Squirmz", Kadrin Valley, Destruction.

### ISSUE THREAD

**Issue by Grunbeast** [WarEmu/WarBugs#11262]
Need to get on top of the tower and get banner. I could not open that door and door it self count as banner.
![grunbeast_094](https://user-images.githubusercontent.com/35007878/35855259-f7a113cc-0b32-11e8-8b0d-94221fdf7fee.jpg)
![grunbeast_097](https://user-images.githubusercontent.com/35007878/35855333-295f883a-0b33-11e8-8bb2-f892ff94f910.jpg)

**Comment by Lheana** [comment]
Exact location please

**Comment by Grunbeast** [comment]
I'm sorry for poor wording. You can not complete this quest. If you target that door you see banner in your target frame. Clicking on it wont end the quest and I wasn't able to open or destroy that door.
![grunbeast_099](https://user-images.githubusercontent.com/35007878/35863937-8dabe686-0b50-11e8-8a8b-ed4d629cf7b9.jpg)

**Comment by Lheana** [comment]
Thanks for the report and info. Will be fixed next patch

**Comment by sioding** [comment]
fixed with patch from 9.2.2018
