### ISSUE TITLE
Stuck in Marshes of Madness near PQ "Dam Boglars"

### ISSUE THREAD

**Issue by Sanasanitix** [WarEmu/WarBugs#11269]
Hi, I was exploring around the area and went down a hill, i managed to get caught with some roots, I can't move but my character is in a constant fall, which doesn't let me tp out or try to get in my mount.

(https://user-images.githubusercontent.com/36246954/35944787-0d9bf968-0c5e-11e8-9df7-c6a4141d204e.png)

**Comment by sioding** [comment]
have you tried using doube /stuck while the login screen appears?

**Comment by Sanasanitix** [comment]
yes, but I have to be stationary, and Im free falling
