### ISSUE TITLE
Slayer Keep PQ locks you inside

### ISSUE THREAD

**Issue by Psyk16** [WarEmu/WarBugs#11268]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
In Kadrin Valley, the PQ Slayer Keep has a third stage where you enter inside a building. The problem is that if you are inside that building AFTER stage 3 ends, and the PQ resets, you will be trapped inside because two walls are placed in front of the exits. 

Steps to reproduce the problem:
Complete stages 1 and 2 of the PQ, and either complete or fail stage 3 to reset the PQ. Be standing inside the building when this happens, and you will be trapped.

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
The Ch 22 hard PQs are not open for play. they will be redisigned soon for the onslaught set. so be aware to expect starge behaviours in all ch22 hard pqs.
