### ISSUE TITLE
Character cant zone

### ISSUE THREAD

**Issue by maciaveli** [WarEmu/WarBugs#11260]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Every time I try to zone with my character 'Wuntusk' I get kicked to Character Select (this does not occur with any alt I have) - this includes zoning to Scenarios. Quite often I cannot select any character back into the game from Character Select screen and have to re-log.
 Wuntusk cannot be selected once he has been dropped to Character select (play button greyed out) and I have to re-log ( but issue still persisits)

Not sure if its relevant but it seems that every time I log him back in, he enters a random zone (i.e. not where he zoned from or to before kicking to CS

Steps to reproduce the problem:
None occurs every time

Screenshots/Videos or archive.org evidences:
Can Supply if needed...

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Have you tried a double /stuck while login sreen appears and bind to a new rally master?
