### ISSUE TITLE
All characters gone after latest patch

### ISSUE THREAD

**Issue by Nantarg** [WarEmu/WarBugs#11266]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
No characters show up when logging in to the game. Goes straight to the character creation screen. 

Characters can be found in the armory and no bans, warnings or similar has been given to my account by my knowledge. 

Affected characters of note:
Yhrfa
Cheyl
Irrbloss
Toofbash

Steps to reproduce the problem:
Patched the launcher. 
Reset my password as I had forgotten it.
Logged in again. 

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/36206593/35879570-d5b45fe6-0b7b-11e8-8406-d1b7e84beb92.png)

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Tbh: this will not work here. The bugtracker is for ingame bugs - not for problems with an account. Please write a PM on the forum to one of the gamemaster.
