### ISSUE TITLE
Blank Items dropping, no name, no icon set

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#1126]
![warhammer_ age of reckoning version 1 4 8 copyright 2001-2012 electronic arts](https://cloud.githubusercontent.com/assets/12942408/9415972/d3f2a5b8-4810-11e5-82ea-ad0999caa7e5.png)

**Comment by xyeppp** [comment]
That is - as far as I know - some scavenging/crafting loot that is not added in yet fully to the database. I might be very wrong about that though.

**Comment by Thorgatin** [comment]
Human-like enemies (humans, orcs, elfs) can be scavenged.
Beast-like enemies (wolfs, boars) can be butchered.

As butchering is not in the game yet, i guess it's just a little buggy until it is introduced.

**Comment by Evildoor** [comment]
Beasts can no longer be scavenged. Closing.
