### ISSUE TITLE
Siege weapons counting damage in SC

### ISSUE THREAD

**Issue by asdf92** [WarEmu/WarBugs#11265]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: 
expect Does not count as damage done on the SC scorebored  ~ counts as damage in SC

Steps to reproduce the problem:
join battle for praag and use the launchers when enemy team is near base

Screenshots/Videos or archive.org evidences:
http://tinypic.com/r/35cl9fk/9

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
This is not a bug. The siege weapon is used by a player - so the damage counts as damage from this player. If you want to suggest to change that please use the feedback forum.
