### ISSUE TITLE
Receiving Loot Bags for Zone Locks I Did Not Contribute To

### ISSUE THREAD

**Issue by CountTalabecland** [WarEmu/WarBugs#11276]
I received a bag for Reikland yesterday but I did not participate in orvr in Reikland, did not enter the zone, nor was I in a group/wb that then went to Reikland. I was in a wb in Praag, which was then locked by the enemy and I received my roll for Praag. We then disbanded the wb (I was not the leader, just a member) and then I logged off. Later yesterday evening I was back online doing scens when Reik locked and I received a roll with over 700 contribution for Reikland and a bag. 

I don't know if this is some weird roll over from praag but from the contribution numbers (I was in Praag for approximately 2 hrs, we were outnumbered and didn't get many kills, so that roll was pretty bad and I didn't get a bag, and then suddenly I had great contribution in Reik) it seems like I got a bonus for the next zone w/o actually going there.
-Brynnoth

![brynnoth_063](https://user-images.githubusercontent.com/31392662/36032883-fc68d05e-0d74-11e8-8694-5a1fbe3577a2.jpg)

**Comment by sioding** [comment]
Blue bag Problem fixed with latest patch
