### ISSUE TITLE
Forum Login Problems

### ISSUE THREAD

**Issue by Yardape** [WarEmu/WarBugs#11271]
Every time i log onto the forums i get hit with a warning saying i have attempted to log in too much.  and have to always fill out the text questions.

Expected behavior and actual behavior:
Log in for the first time in a day should not have this red writing and should not prompt a visual text questionnaire. 

Steps to reproduce the problem:
I just need to log out and log back in again, and i get the multiple attempts to log in text everytime
![image](https://user-images.githubusercontent.com/19935059/35956206-e31d44bc-0cdf-11e8-831a-2968ec2c7956.png)

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Yardape** [comment]
just tried again (3 hours after this post) and hod no problem.  However for about 3 hours before this post it was a problem constantly within those 3 hours

**Comment by sioding** [comment]
Sorry this tracker is for ingame problems only.
