### ISSUE TITLE
Gotta Nosh! quest supply crates

### ISSUE THREAD

**Issue by nanwalker** [WarEmu/WarBugs#11275]
Recovered Supply Crates will smash and count toward the PQ = Fireforge's Camp but not toward the Gotta Nosh! quest.  Please forgive if this issue has already been reported, I did try to research it and found nothing.  Thanks so much for such and wonderful game.  My husband and I really appreciate all the hard work.

**Comment by sioding** [comment]
fixed with patch from 9.2.2018
