### ISSUE TITLE
Genesis Remnant of Undying/Ever Lasting same stats

### ISSUE THREAD

**Issue by stormin1971** [WarEmu/WarBugs#11278]
this set is for KOTBS same stats as with the other pieces for same two groups

**Comment by stormin1971** [comment]
this set is for KOTBS same stats as with the other pieces for same two groups

**Comment by sioding** [comment]
Sorry - don´t get it. Screenshots plz. And you can edit your comments here - but i did that for you and deleted the empty one.

**Comment by sioding** [comment]
No response for 15 days
