### ISSUE TITLE
Warband Health Bars

### ISSUE THREAD

**Issue by dansarii** [WarEmu/WarBugs#11277]
Group health bars do not update unless there are six members in the group within a warband. There seems to be no issue when there are two members in the group, but between 3 and 5, it's as if the server does not recognize where they are or update their health bars on your screen. This is also the case if you have six members in a group but not all six members are within your sight range. This is not an addon issue, as it persists with members of the warband who do not have any group UI addons. This has been an issue since roughly Jan 13th patch.

**Comment by Laurentz18** [comment]
This was also an issue plaguing Live after a patch they did. Took them a while to finally fix it.

**Comment by nat3s** [comment]
This is game-breaking for healers. Every WB or SC you join you are faced with the problem of health bars not being updated (can show 40% when someone is 100% or 100% when someone is near death). Doesn't update to show who is in/out of range too.

This needs to be treated as the highest priority ticket imo.

**Comment by Natherul** [comment]
This issue is hard to track down as Im currently unaware of how to replicate it with a 100% certainty. I have made a fix that the testers have said seems to work, if it does not comment on this ticket again and Ill reopen it but hopefully the bug is gone as of today.
