### ISSUE TITLE
Guild Search Stopped Working

### ISSUE THREAD

**Issue by foghladha** [WarEmu/WarBugs#11273]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Should present a list of available guilds.

Steps to reproduce the problem:

Open Guild Window, Click on Search. The Search button is not active.

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Works fine for me:
![image](https://user-images.githubusercontent.com/18517842/36015270-14321b98-0d6e-11e8-9f75-5390c6f07cf3.png)

Please add more informations.

**Comment by foghladha** [comment]
Looks like it was temporary it's working again for me. Was getting a greyed out search button. It works now.
