### ISSUE TITLE
Spite's reach third floor unsafe

### ISSUE THREAD

**Issue by GloomySam** [WarEmu/WarBugs#11280]
There's a mountain to the west of Shadowlands' Spite's reach keep. RDPS can shoot into the keep from there, although it's supposedly a safe spot. Magus/Engi duo can damn near clear the whole top floor from there, without going in the keep. I knmow there's already an invisible barrier there that prevents you from jumping from the mountain into the keep - why not make it block spells as well?

**Comment by sioding** [comment]
Checked that - and thats just the way it works on live too. Who said that the third floor is save in an RvR area? It´s like "Stop the WAR - we are on the third floor" - YES you can´t just sit there and spam your heal or whatever you want to - but the guys on the mointain can also be killed by magus/engi from the keep 3rd floor. So close...
