### ISSUE TITLE
Gas Squig broken since new patch

### ISSUE THREAD

**Issue by fesust** [WarEmu/WarBugs#11282]
Gas Squigs keep dropping invalidcastexception and disappear

Screenshots/Videos or archive.org evidences:
See chat
![nastybiccs_005](https://user-images.githubusercontent.com/22993093/36059442-3f4f3f06-0e39-11e8-9948-8ed0debd21e7.jpg)

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Patched with hotfix
