### ISSUE TITLE
[Saphery] Flying NPC's 

### ISSUE THREAD

**Issue by stillwaterww** [WarEmu/WarBugs#11281]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Some of the mounted skyrage trainers at 14k,30k appear to have learned how to fly their horses.

Steps to reproduce the problem:
ehm..

Screenshots/Videos or archive.org evidences:
![flyingelfs](https://user-images.githubusercontent.com/19287032/36059333-ecd70e40-0e36-11e8-96e8-a7d9ac8c9a34.png)

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Lheana** [comment]
They will still be flying, but on the back of griffons.

**Comment by sioding** [comment]
fixed with patch from 16/02/2018
