### ISSUE TITLE
[Slayer] Damage tooltip mismatch

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#1128]
That is known issue i believe. Many classes have small tooltips mismatch, but for slayer its a big numbers equal 50 str lose. Choppa could have same problem.

Pulverizing Strike - 320 raw \ 480 bers \ 446 real (34 dmg lost, -7.6%)
Spine Crusher - 316 raw \ 474 bers \ 442 real (32 dmg lost, -6.7%)
Slow Down - 266 raw \ 399 bers \ 365 real (34 dmg lost, -8.5%)

![slayertooltips](https://cloud.githubusercontent.com/assets/13031465/9422040/90f3cdfa-48b5-11e5-8bb3-ffd4abc49bef.jpg)

**Comment by xyeppp** [comment]
Plink mismatches 6 points of damage hitting for 323 (111 mitigated)= 434, on tooltip 440
Actual HP lost is 434 as well, not a combat log visual.

**Comment by ozarmidrashim** [comment]
Wild Gambit did not stack with Brute Force. Fixed in next.

(Perfect proof that Slayer vs. Choppa complaints in T2 are completely imagined)

**Comment by Silentguard** [comment]
Not really. Jagged Edge give more dmg.

**Comment by ozarmidrashim** [comment]
Perhaps you misunderstood me. I'm saying that Choppas not having Wild Gambit had no real effect on the relative performance of the classes in RoR's T2 scenarios :)

**Comment by Vigfuss** [comment]
I think you would have to show your stat sheet and take the class mechanic into account to really prove that there is something wrong with the damage.

**Comment by ozarmidrashim** [comment]
There was something wrong with the damage, so that's moot.
