### ISSUE TITLE
No loot after lock DW

### ISSUE THREAD

**Issue by barrmyy** [WarEmu/WarBugs#11284]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

After lock DW (10,02,2018 22:45 +3 GMT) I didn't resive any loot, any roll - it was nothing, no white bug, no crow pie. no "zero" roll.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Please use this forum thread: https://www.returnofreckoning.com/forum/viewtopic.php?f=11&t=25204
