### ISSUE TITLE
BOs in Reikland do not tick

### ISSUE THREAD

**Issue by Timmitz** [WarEmu/WarBugs#11286]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*While at 1 star the Reikwatch BO does not tick.

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![poostainz_033](https://user-images.githubusercontent.com/36116924/36074914-11d6a73a-0f47-11e8-8516-c0773cc4431a.jpg)

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
patched with hotfix
