### ISSUE TITLE
[SC] BO in Reikland Factory Scenario isn't cap-able

### ISSUE THREAD

**Issue by Tyramissoux** [WarEmu/WarBugs#11283]
**Expected behavior and actual behavior:**
When approaching, there should be a bar showing the progress of turning the BO "The Machine Shop".

Although we were more 3+ players (not visible in linked video, was before), the BO mechanic didn't react. No bar showed up, BO didn't turn red.

Don't know if any of the other BOs had the same problem, but I assume yes because we dominated mid shortly and BO stayed blue. 

**Steps to reproduce the problem:**
Go into SC, I guess. 

**Screenshots/Videos or archive.org evidences:**
https://www.twitch.tv/videos/227655649 Short stream. Tried to move away from BO to trigger the mechanic but nothing helped.

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Tyramissoux** [comment]
Seems to be a one-time problem. Entered the SC again and the BO was normally flipable.

**Comment by sioding** [comment]
I will leave this report open a bit - if its really a one timer i will close this tomorrow. Anyway - thanks for the report.
