### ISSUE TITLE
Obstruction Glitching by Anonymous Pt. 5 - Nordland RvR

### ISSUE THREAD

**Issue by Cpryt** [WarEmu/WarBugs#11295]
-NOTICE-
These practices are not to be used for malicious intent. They are on the bug-tracker with reason to be noticed a/o fixed. Do not attempt.

Obstruction Glitching Pt. 5 - Nordland RvR

For the integrity of the game, I will reveal my secret spot from Live. I am never in T1 anyway so ¯\_(ツ)_/¯ Also I am doing this for my chicken brethren...

At 25k, 8k, in Nordland, if you run up to the giant boulders, find the smallest boulder between the biggest and run in-between them. While in-between these two boulders, run forward and continue trying to jump. This will force your character under the ground and you can roam RvR under the map. This can benefit both Order and Destruction forces against either force by harassing other players without receiving damage.

This glitch was never patched on any server during Live, and has remained uncovered since the ending day of WAR.

![anonymous_059](https://user-images.githubusercontent.com/19481783/36143805-5d017276-1069-11e8-8166-3bbe52546307.jpg)
![anonymous_060](https://user-images.githubusercontent.com/19481783/36143807-5d170c76-1069-11e8-96f9-eb8a03741deb.jpg)
![anonymous_061](https://user-images.githubusercontent.com/19481783/36143808-5d3111de-1069-11e8-96ef-3b471e1fa64d.jpg)
![anonymous_062](https://user-images.githubusercontent.com/19481783/36143810-5d48b802-1069-11e8-8fd9-5f11fba99dd3.jpg)
![anonymous_063](https://user-images.githubusercontent.com/19481783/36143811-5d611bf4-1069-11e8-8bf7-96238b5c66af.jpg)
![anonymous_064](https://user-images.githubusercontent.com/19481783/36143818-62ba904e-1069-11e8-9326-306cdbecb977.jpg)

More to come... How much is the Imperial Griffon again...?

**Comment by sioding** [comment]
fixed with next patch

**Comment by Cpryt** [comment]
Awesome sauce!

**Comment by sioding** [comment]
fix pending removed - doesn´t work like it should.

**Comment by sioding** [comment]
fixed with patch from 24.02.2018
