### ISSUE TITLE
Obstruction Glitching by Anonymous Pt. 4 - The Inevitable City

### ISSUE THREAD

**Issue by Cpryt** [WarEmu/WarBugs#11294]
-NOTICE-
These practices are not to be used for malicious intent. They are on the bug-tracker with reason to be noticed a/o fixed. Do not attempt.

Obstruction Glitching Pt. 4 - The Inevitable City

At 37k, 55k, you can get a peek at a majority of The Inevitable City by simply walking along-side a wall that lacks obstruction. Use a mount or simply walk along it and you'll see that the end of the path reveals a bit of The Inevitable City from an outside view. With this, you can also fall under the map, though it provides no harm.

![fun_019](https://user-images.githubusercontent.com/19481783/36142809-643dd244-1066-11e8-8579-443fac7a5cc5.jpg)
![fun_020](https://user-images.githubusercontent.com/19481783/36142813-669734e0-1066-11e8-8845-6c7cf890bc20.jpg)
![fun_021](https://user-images.githubusercontent.com/19481783/36142818-6a3adb24-1066-11e8-8582-d3331bbc5096.jpg)
![fun_022](https://user-images.githubusercontent.com/19481783/36142819-6a574dea-1066-11e8-808a-9d915ada4559.jpg)
![fun_023](https://user-images.githubusercontent.com/19481783/36142820-6a6eea4a-1066-11e8-94d2-656e256466e0.jpg)

More to come...

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 24.02.2018
