### ISSUE TITLE
Warband wiped at South Garrison of Praag and respawned in Wilhelm's Fist of Reikland

### ISSUE THREAD

**Issue by baroke** [WarEmu/WarBugs#11298]
We wiped at South Garrison of Praag, while defending inner, and respawned in Wilhelm's Fist of Reikland, instead of Praag WC.

![kyrontor_002](https://user-images.githubusercontent.com/20115114/36148476-e737cfd4-10c4-11e8-9d1c-f064522c1949.jpg)

**Comment by Cpryt** [comment]
I can vouch, haha, this just happened to me.

**Comment by sioding** [comment]
#11253

**Comment by Hargrim** [comment]
Fixed in next patch, closing.
