### ISSUE TITLE
Obstruction Glitching by Anonymous Pt. 7 - Altdorf

### ISSUE THREAD

**Issue by Cpryt** [WarEmu/WarBugs#11297]
-NOTICE-
These practices are not to be used for malicious intent. They are on the bug-tracker with reason to be noticed a/o fixed. Do not attempt.

Obstruction Glitching Pt. 7 - Altdorf

At 23k, 38k, in Altdorf, there is a set of stairs that you can walk up. At the top of the first stair platform, you can aim your character to strafe over a gated arch. This is accessible by using a mount for speed, jumping across and over the arch. Once you get across, you can walk through buildings and ground that has no collision. In doing this, you can only walk about the area of homes which it provides, as you cannot get under the map doing this, and benefits nothing.

![anonymous_088](https://user-images.githubusercontent.com/19481783/36147339-1a3af73a-1075-11e8-8050-874c0adfc9ff.jpg)
![anonymous_098](https://user-images.githubusercontent.com/19481783/36147344-1d685560-1075-11e8-8e38-431d71a5d050.jpg)
![anonymous_089](https://user-images.githubusercontent.com/19481783/36147356-245af350-1075-11e8-9b34-cda4961d9612.jpg)
![anonymous_090](https://user-images.githubusercontent.com/19481783/36147357-246fbe66-1075-11e8-97fd-87dea46c15b7.jpg)
![anonymous_091](https://user-images.githubusercontent.com/19481783/36147358-2483a9b2-1075-11e8-88f7-d4dc8d4746a6.jpg)
![anonymous_092](https://user-images.githubusercontent.com/19481783/36147359-2496c100-1075-11e8-896c-c1a416fbdce2.jpg)
![anonymous_093](https://user-images.githubusercontent.com/19481783/36147361-24ab8496-1075-11e8-8ed0-702c15d58c61.jpg)
![anonymous_094](https://user-images.githubusercontent.com/19481783/36147362-24be7358-1075-11e8-9333-6e6c445a0602.jpg)
![anonymous_095](https://user-images.githubusercontent.com/19481783/36147363-24cfc55e-1075-11e8-8b89-9d90b7f8bd1d.jpg)
![anonymous_096](https://user-images.githubusercontent.com/19481783/36147366-28d15c08-1075-11e8-90e1-c0613ae2934e.jpg)
![anonymous_097](https://user-images.githubusercontent.com/19481783/36147367-28e460dc-1075-11e8-915d-c3ffa2e37359.jpg)

More to come...

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 24.02.2018
