### ISSUE TITLE
Obstruction Glitching by Anonymous Pt. 6 - Nordland Order Start

### ISSUE THREAD

**Issue by Cpryt** [WarEmu/WarBugs#11296]
-NOTICE-
These practices are not to be used for malicious intent. They are on the bug-tracker with reason to be noticed a/o fixed. Do not attempt.

Obstruction Glitching Pt. 6 - Nordland Order Spawn

If Destruction, along the pathway to Grimmenhagen Windmill and Grimmenhagen Farm, then to the Grimmenhagen Village, you might find that there are Griffon War Soldiers guarding the area, preventing you from harassing the Order start spawn. This can be countered a variety of ways, I can reveal two.

![anonymous_065](https://user-images.githubusercontent.com/19481783/36144769-6759ee94-106c-11e8-9ffe-2c2125a8b6e4.jpg)
![anonymous_066](https://user-images.githubusercontent.com/19481783/36144770-676ef320-106c-11e8-973f-c31595a5cb12.jpg)

1.
At 37k, 35k, you can leap onto the downward boulder connected to the slope-slide. Use a mount and get a distanced leap from the slope curve to the boulder. From this boulder, you can make your way through the mountains to the Order start.

![anonymous_068](https://user-images.githubusercontent.com/19481783/36144859-b1110860-106c-11e8-97f5-bd12728355cc.jpg)
![anonymous_068](https://user-images.githubusercontent.com/19481783/36144868-bb42b144-106c-11e8-8927-7f83ba9a6035.jpg)
![anonymous_069](https://user-images.githubusercontent.com/19481783/36144869-bb5c71a6-106c-11e8-9c60-18f950145431.jpg)
![anonymous_070](https://user-images.githubusercontent.com/19481783/36144870-bb74997a-106c-11e8-9723-62e53f892144.jpg)
![anonymous_071](https://user-images.githubusercontent.com/19481783/36144871-bb8c45e8-106c-11e8-83c7-2d0c7b0caefa.jpg)
![anonymous_072](https://user-images.githubusercontent.com/19481783/36144886-c666c2c2-106c-11e8-814e-2604a8958485.jpg)

2.
At 39k, 59k, just before Morra's lair, there's a rock surfaced in the middle of the water. Jump on that middle rock, then onto the mass of rocks after it. Scale up those rocks as shown in the screenshots and you'll reach land. Make your way through the vast mountain surface to the Order start.

![anonymous_074](https://user-images.githubusercontent.com/19481783/36145048-5a8a4a32-106d-11e8-9e38-7e5176277cde.jpg)
![anonymous_075](https://user-images.githubusercontent.com/19481783/36145049-5aa28d40-106d-11e8-919f-43a7faedd9ee.jpg)
![anonymous_076](https://user-images.githubusercontent.com/19481783/36145050-5abb3d54-106d-11e8-8a6a-95acbe574033.jpg)
![anonymous_077](https://user-images.githubusercontent.com/19481783/36145051-5ad0f9be-106d-11e8-98e2-3d5055808450.jpg)
![anonymous_078](https://user-images.githubusercontent.com/19481783/36145052-5ae94f46-106d-11e8-9d90-933ca957fd6f.jpg)
![anonymous_079](https://user-images.githubusercontent.com/19481783/36145053-5afafa02-106d-11e8-931a-524854258965.jpg)
![anonymous_080](https://user-images.githubusercontent.com/19481783/36145055-5f2634b6-106d-11e8-8663-dedaa22efefb.jpg)
![anonymous_081](https://user-images.githubusercontent.com/19481783/36145056-5f3e677a-106d-11e8-98f1-d53ea07d47c3.jpg)
![anonymous_082](https://user-images.githubusercontent.com/19481783/36145057-5f56f02e-106d-11e8-973a-8bf2064feceb.jpg)
![anonymous_083](https://user-images.githubusercontent.com/19481783/36145058-5f6ef264-106d-11e8-89b7-08a08e724044.jpg)
![anonymous_084](https://user-images.githubusercontent.com/19481783/36145059-5f90aa8a-106d-11e8-99d1-973679090d80.jpg)
![anonymous_085](https://user-images.githubusercontent.com/19481783/36145060-5fb56c12-106d-11e8-851a-28e366fbc966.jpg)
![anonymous_086](https://user-images.githubusercontent.com/19481783/36145062-5fd04e6a-106d-11e8-9b7a-92740473a206.jpg)
![anonymous_087](https://user-images.githubusercontent.com/19481783/36145064-5fe9216a-106d-11e8-9844-f97f3a6f96f8.jpg)

More to come...

**Comment by sioding** [comment]
I do not see any problem here. If Destro players do that it would be agaoint the ToS which will result in a ban.

**Comment by Cpryt** [comment]
Awesome @sioding! I know that the NPCs are on the pathways for a reason, I was just making sure that this was known at the least. I can take this thread down if needed.

**Comment by Lheana** [comment]
And there are some ToK unlocks around there that are meant to be reachable for both sides.

**Comment by sioding** [comment]
I would take down this report. Your other reports are fine as they are. Maybe not even that major as you think but we will take care of it.
