### ISSUE TITLE
PQ Burning Windmill Boss

### ISSUE THREAD

**Issue by Peleliu** [WarEmu/WarBugs#11292]
Empire Chapter 2 The Burning Windmill

Boss mob named Boruun the Seeker on stage 3 never takes more than 1 point of damage.

**Comment by sioding** [comment]
Can we please see your test screenshots?

**Comment by Peleliu** [comment]
I hope this works...

![khorr_000](https://user-images.githubusercontent.com/36434636/36164843-9f13b4ba-10bb-11e8-9624-fae4a4644890.jpg)

**Comment by sioding** [comment]
tried that pq more than one time - can not reproduce that error
