### ISSUE TITLE
Obstruction Glitching by Anonymous Pt. 3 - Praag RvR

### ISSUE THREAD

**Issue by Cpryt** [WarEmu/WarBugs#11293]
-NOTICE-
These practices are not to be used for malicious intent. They are on the bug-tracker with reason to be noticed a/o fixed. Do not attempt.

Obstruction Glitching Pt. 3 - Praag, Westmark Barricade, Empire War Camp

At 16k, 32k, there is a gated barrier that prevents you from prowling into the Empire War Camp. You can, however if you get it just right, jump onto the barricade. This effort requires no need for a mount nor the "Flee" skill. Simply position yourself under the arch of the door and jump forward. It may take a few tries, but you will eventually stand on top of the barricade, if not fall to the other side. There is little space to roam, but you can essentially harass the forces of Order by killing NPCs with ranged DPS or enemies themselves if you're lucky enough. This glitch benefits Destruction.

![anonymous_042](https://user-images.githubusercontent.com/19481783/36135893-08d948ae-104b-11e8-9007-6c012eb86593.jpg)
![anonymous_043](https://user-images.githubusercontent.com/19481783/36135894-08ee5fbe-104b-11e8-9720-0f9c50c2bd47.jpg)
![anonymous_044](https://user-images.githubusercontent.com/19481783/36135895-09029998-104b-11e8-84aa-26c1d384c7ba.jpg)
![anonymous_045](https://user-images.githubusercontent.com/19481783/36135896-0917cf20-104b-11e8-8a23-4c290a4e7479.jpg)
![anonymous_046](https://user-images.githubusercontent.com/19481783/36135897-092c84ce-104b-11e8-8e91-a6620a2948ee.jpg)
![anonymous_047](https://user-images.githubusercontent.com/19481783/36135898-093f3b78-104b-11e8-99d5-f763c40da5e5.jpg)

More to come...

**Comment by sioding** [comment]
fixed with next patch

**Comment by Cpryt** [comment]
Awesome :)

**Comment by sioding** [comment]
fixed with patch from 24.02.2018
