### ISSUE TITLE
Obstruction Glitching by Anonymous Pt. 2 - Doomfist Crater

### ISSUE THREAD

**Issue by Cpryt** [WarEmu/WarBugs#11291]
-NOTICE-
These practices are not to be used for malicious intent. They are on the bug-tracker with reason to be noticed a/o fixed. Do not attempt.

Obstruction Glitching Pt. 2 - Doomfist Crater (platform/under map)

In Doomfist Crater (left side; destruction spawn)

This platform on (right side; destruction --- left side; order (34k, 28k), there is a slope on the mountain-side just under a raised balcony. If you run up into the indent and leap up on the pushed slope, you can do one of two things.

1.
If you run into the mountain-side under the platform's wooden post, you can glitch under the map. This doesn't provide too many advantages, but you can essentially harass the enemy team by using ranged attacks through the terrain. This glitch can be performed by both Destruction and Order players, and both sides can harass the enemy team.

2.
If you dismount (if not already mounted), skim your player to the side of the platform and run up the slope. You can jump onto the end-corner of the balcony. This too does not provide too many advantages. For Order players, you can harass Destruction players emerging from their spawn with ranged attacks. If you are skilled at this, both sides can hide the Battle Objective in this location.

![anonymous_026](https://user-images.githubusercontent.com/19481783/36134934-1dd2a9fe-1045-11e8-8368-6679f76240c2.jpg)
![anonymous_027](https://user-images.githubusercontent.com/19481783/36134935-1de97ba2-1045-11e8-8682-2c364fdcacf1.jpg)
![anonymous_028](https://user-images.githubusercontent.com/19481783/36134936-1dfcbbcc-1045-11e8-904c-290cba3f4abe.jpg)
![anonymous_029](https://user-images.githubusercontent.com/19481783/36134938-1e100a92-1045-11e8-8327-69f424dd52af.jpg)
![anonymous_030](https://user-images.githubusercontent.com/19481783/36134939-1e23d856-1045-11e8-80e4-63a9a15319a6.jpg)
![anonymous_031](https://user-images.githubusercontent.com/19481783/36134940-1e3777c6-1045-11e8-96d7-b5ae0c430a15.jpg)
![anonymous_034](https://user-images.githubusercontent.com/19481783/36134941-1e4c9aac-1045-11e8-9c5b-7a5730486e60.jpg)
![anonymous_035](https://user-images.githubusercontent.com/19481783/36134942-1e65c004-1045-11e8-9805-96e7ff539894.jpg)
![anonymous_036](https://user-images.githubusercontent.com/19481783/36134943-1e793562-1045-11e8-9478-a0b7d071dc72.jpg)
![anonymous_037](https://user-images.githubusercontent.com/19481783/36134944-1ea4a224-1045-11e8-8d4f-da1b0b244004.jpg)
![anonymous_038](https://user-images.githubusercontent.com/19481783/36134945-1eb81bec-1045-11e8-9d4d-25e56e15ffe2.jpg)
![anonymous_039](https://user-images.githubusercontent.com/19481783/36134946-1ecceae0-1045-11e8-98b8-099dae2c75a5.jpg)

More to come...

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 2.3.2018
