### ISSUE TITLE
Quest: Welcome Back: Brotherhood

### ISSUE THREAD

**Issue by Peleliu** [WarEmu/WarBugs#11303]
Mission taken at Ekrund to "Get a crate of cannonballs"

All crates and cannonballs I can click on do not complete the quest. Tried the crate at the cannon battery and all the crates and piles behind the Gates of Ekrund on the Destruction side of the map. Also tried the pile at the top of the front of the gate. Can't select anything. There is no red lake showing the quest area...just a red arrow pointing to the Destro side of the map. I looks like the same issue and reported previously by another user: "Welcome back : brotherhood" quest #6317.

**Comment by sioding** [comment]
![image](https://user-images.githubusercontent.com/18517842/36948974-a5dd0ebe-1fe2-11e8-8705-4da6f472dfed.png)

**Comment by sioding** [comment]
I can do that quest and find all items on the destro side inside the red circle which is OK.
