### ISSUE TITLE
Helmsteinn Revisited PQ Chaos Cap.2 bugged

### ISSUE THREAD

**Issue by LuckyRaider** [WarEmu/WarBugs#11308]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Destro Cap.2 Chaos Helmsteinn Revisited
No Nordland Scouts and boxes to collect. pq was always in phase 1. so the q: deadly task couldn't finish and the pq couldn't finish

Steps to reproduce the problem:
reloged, restarted, switched fraktion, reloaded ui

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
This is a known issue. Sometimes PQ´s don´t load until server restart.
