### ISSUE TITLE
Potential Loot Table Issue

### ISSUE THREAD

**Issue by Rothsper** [WarEmu/WarBugs#11305]
(This is my first use of bug tracker.  Please let me know if I can improve on this report.)

Expected behavior and actual behavior:  

Expected:  Level 40 RR 39 Witch Elf wins gold bag in oRvR and this contains some level appropriate gear.
Actual:  Bag contains shoes from the level 4 set.  (I think it was Braggart)

Steps to reproduce the problem:  Difficult - win more gold bags as level 40, rr 39

NB:  This report is solely to flag a potential bug in a loot table somewhere.   TY for this project.

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
Screenshots with bag content and ingame mail please.

**Comment by Rothsper** [comment]
I am very sorry, I didn't think to take a screenshot at the time.  If I see
anything like that again I will make sure that I do.

I am not looking for any replacement item, I just thought I'd flag the
issue in case it is something you could find on a table etc.

If I see it again I will make sure to take a screenshot.

**Comment by sioding** [comment]
OK got you. Would you please add your informations to this thread next time: https://www.returnofreckoning.com/forum/viewtopic.php?f=11&t=25204 
We are collecting them at a single point instead of different reports.
Thansk
