### ISSUE TITLE
[Bright Wizard] Tactic: Fan The Flames partially working

### ISSUE THREAD

**Issue by cimator** [WarEmu/WarBugs#11307]
![fan the flames](https://user-images.githubusercontent.com/17130290/36257031-69dfadec-1266-11e8-84de-d2a9cac8b9c3.jpg)

It Increases the radius of detonate, but not rain of fire. I think it has to do with the tactic and this patch note: -Rain of Fire radius extended to meet its visual effects, not stacking.

**Comment by sioding** [comment]
How did you test it? Can we please see the screenshots of your test?

**Comment by cimator** [comment]
It was a pretty long test actually, so dont have screenshots. Tested it this way with a chosen; he just stood still, and I used rain of fire, if the ability hit him, I use it again just a little bit further away from him and so on until the ability didnt hit him, so he would stand just outside the radius of the skill. Then I used the tactic for %50 radius inc and used rain of fire again on that last spot, where he would be 1-2 feet away. And it didnt hit still.

**Comment by sioding** [comment]
Next time - please save your testing screenshots. This would save us time for the research.

**Comment by Torquemadra** [comment]
this time too thanks

**Comment by cimator** [comment]
Screenshots might not be clear to show radius, so I made a video instead; https://youtu.be/1KCRiCFwHn0

**Comment by cimator** [comment]
This has been open for a while now, so I tested it again today. Looks like it is fixed, cheers.
