### ISSUE TITLE
Inf points bugged for the charecter Nymf Which is me

### ISSUE THREAD

**Issue by Nicklas9400** [WarEmu/WarBugs#1130]
Well i logged on and suddenly all my inf points was reset or removed, i was realyl close to get the t2 rvr thing and i need it for being healer, so pls help me out here cause it doesn't work my inf anymore.

**Comment by xyeppp** [comment]
Relog.

**Comment by Evildoor** [comment]
I encountered this problem several times, but it was long ago, and usually visual only. Have you got your influence back?

**Comment by Evildoor** [comment]
No confirmation, closing for now.
