### ISSUE TITLE
Black Orc Tactic No Choppin' Me not working

### ISSUE THREAD

**Issue by Shadowgurke** [WarEmu/WarBugs#11300]
Expected behavior and actual behavior:
The tactic No choppin me is supposed to alter Follow Me Lead (FML) to buff Weaponskill to all groupmates within 30 yards of the defensive target. On RoR this tactic appears to do nothing

**Comment by sioding** [comment]
Can we please see your testing screenshots?

**Comment by Q73px** [comment]
just tested it and i can confirm, the tactic doesn't do anything.

**Comment by sioding** [comment]
If you are testing stuff - why are you not adding your screenshots to this ticket? I would 
expect screenshots from the blackorc with the tactic on - and a screenshot from a groupmember showing us .getstats with no additional weaponskill points.

**Comment by Shadowgurke** [comment]
Could not replicate the bug. On Feburary 13th no icon showed up on any groupmember despite them being very close to the defensive target, On February 14th it worked just fine. Other factors might be to blame, not excluding error in the testing method. Closing for now
