### ISSUE TITLE
Balanced Mending Tactic

### ISSUE THREAD

**Issue by kabbolt** [WarEmu/WarBugs#11302]
The tactics does not work on my character and on my ally.
Some screen for proof.

http://image.noelshack.com/fichiers/2018/07/3/1518634341-novabella-003.jpg

http://image.noelshack.com/fichiers/2018/07/3/1518634343-novabella-004.jpg

http://image.noelshack.com/fichiers/2018/07/3/1518635037-novabella-005.jpg

**Comment by sioding** [comment]
I only see wrong testing screenshots. Why are you using the wrong skills to test the tactic? Balanced Mending only works for the skill "Healing Energy" and not for the skills you´ve shown in your report.

**Comment by kabbolt** [comment]
Yep sorry bad traduction .. Close the topic please.
