### ISSUE TITLE
The Pleasure of Pain

### ISSUE THREAD

**Issue by Dodelijk** [WarEmu/WarBugs#11312]
Hey,

Map: Chaos Wastes, Destro, Chapter 15.
Quest: The Pleasure of Pain - Talk to Varthon Bloodblade

The mob is just hostile. Killed him multiple times but can't talk to him. Tried various things:
- /talk
- lowering HP and waiting
- lowering HP and /talk
- relogging
- abandon quest and retake
- finishing the PQ and then tried above mentioned

According to the Patch Notes of 26.08.2017 the quest should work
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=22643&p=252155&hilit=The+pleasure+of+pain#p252155

Please support - thanks :)

**Comment by sioding** [comment]
Works like a charm for me - just killed him and as the quest said: Talk to his remains.
![image](https://user-images.githubusercontent.com/18517842/36349116-04b521d8-1480-11e8-8325-97865f2555f8.png)

**Comment by Dodelijk** [comment]
True, but can you talk to his remains? Because I can't and that's the thing. The quest objective settles for me but I can't hand in the quest.

**Comment by sioding** [comment]
Thanks that you asked again. I have changed the quest from speak to the remains to kill the mob and hand in the quest to the questgiver. if you wanna do this quest - please abort the step and get it again from amoch. So: fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 2.3.2018

**Comment by Dodelijk** [comment]
Thanks for the help there. Have a nice evening :)
