### ISSUE TITLE
HP Quest: Tower of Destiny

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#11311]
Running into BO Verentane's Tower doesn't complete quest (which worked for similair other quests in High Pass like scouting ogrund tavern, manor or feiten's lock). Also there is missing marker on map for the quest
![shey_026](https://user-images.githubusercontent.com/18032193/36297144-56ca9b00-12f1-11e8-8a4c-60a2d393ce85.jpg)
![shey_027](https://user-images.githubusercontent.com/18032193/36297145-56e592e8-12f1-11e8-86ed-d3a20734922b.jpg)

**Comment by sioding** [comment]
since a real scouting isn´t implemented yet i have changed the questobject and adjusted the questtext.
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 05.05.2018
