### ISSUE TITLE
[Archmage] Tactic: Balanced Mending partially working

### ISSUE THREAD

**Issue by cimator** [WarEmu/WarBugs#11316]
Just for info here's the tactic and the ability it affects;
![balanced mending](https://user-images.githubusercontent.com/17130290/36342426-68128642-140f-11e8-88ab-cd66db6a4d51.jpg)
![healing energy](https://user-images.githubusercontent.com/17130290/36342427-6a878cec-140f-11e8-9f03-c555d2edbd01.jpg)

It affects ability's direct heal only and not the 5 seconds HoT part of it.
Here are some SS;
Using the ability Without tactic:
![no tactic friendly](https://user-images.githubusercontent.com/17130290/36342453-e728d814-140f-11e8-9307-19f594541a4b.png)

Using the ability With the tactic on a friendly target;
![with tactic friendly](https://user-images.githubusercontent.com/17130290/36342460-0881c8fe-1410-11e8-9a9e-037421918174.jpg)

Using the ability With the tactic on self;
![with tactic self](https://user-images.githubusercontent.com/17130290/36342463-16495790-1410-11e8-99c2-c299da82aaf1.jpg)
As you can see the direct heal scales just fine but the hot is not affected.

also if it helps, lingering healing energy ID: 3558

**Comment by sioding** [comment]
Thanks for report and the screenshots inside. As far as i understand its working as intended Healing Engery is not Lingering Healing Energy.  Are you having any proof that the tactic works also for the HoT part of the skill in AoR?

**Comment by cimator** [comment]
Sorry, dont know how it worked on live. 
I think it should work for both since its the same ability, tho it doesnt matter what I think. Probably need a Dev's opinion on this I suppose :P

**Comment by sioding** [comment]
ok - lets wait for @Torquemadra

**Comment by Nfkillz** [comment]
shaman has the same issue

**Comment by grunbag** [comment]
The  direct heal and the hot are 2 different abilities . Maybe we can include the hot , but not sure

**Comment by grunbag** [comment]
it should increase it already
