### ISSUE TITLE
Obstruction Glitching by Anonymous Pt. 9 - Gates of Ekrund

### ISSUE THREAD

**Issue by Cpryt** [WarEmu/WarBugs#11314]
-NOTICE-
These practices are not to be used for malicious intent. They are on the bug-tracker with reason to be noticed a/o fixed. Do not attempt.

Obstruction Glitching Pt. 9 - Gates of Ekrund

In Gates of Ekrund (left side; destruction spawn)

Attached Video:
https://youtu.be/YKz8F2xb4Zs

1.
At 30k, 30k, you can use a mount or the 'Flee' ability to leap onto the edge of the Gorkamorka-styled siege. Using this, you can (if Order) harass Destruction from their spawn. You can also keep away from any incoming damage, ranged or melee if you insert yourself directly against the vertical obstruction.

![anonymous_172](https://user-images.githubusercontent.com/19481783/36336237-48d8afc6-1343-11e8-8525-744f11b41060.jpg)
![anonymous_193](https://user-images.githubusercontent.com/19481783/36336242-56201656-1343-11e8-9dfa-4e3dc1534f1c.jpg)
![anonymous_173](https://user-images.githubusercontent.com/19481783/36336246-5bc0d794-1343-11e8-9cb0-219e073d2ad5.jpg)
![anonymous_174](https://user-images.githubusercontent.com/19481783/36336247-5bddc85e-1343-11e8-9575-a9bc60c3ae8f.jpg)
![anonymous_175](https://user-images.githubusercontent.com/19481783/36336248-5bf62be2-1343-11e8-8c7f-80cda95c5adf.jpg)
![anonymous_176](https://user-images.githubusercontent.com/19481783/36336250-5e7ad3cc-1343-11e8-8a72-1704261dfc18.jpg)
![anonymous_177](https://user-images.githubusercontent.com/19481783/36336251-5e95c66e-1343-11e8-986c-d4716ae6c1aa.jpg)

2.
At 29k, 32k, just to the left of the door that leads up to the Battle Objectives, if you run along the lining beside the wall, you can aim yourself using a mount to leap onto the edge of the raised ground. Doing this, you can (if Order) harass the Destruction both from their spawn and at their spawn. There is a wooden platform by their spawn when running along this ground that gives you a perfect range point from your standing to their spawn that will let you hit them (if ranged DPS). Additionally, if they exit their spawn point, they cannot get back up unless they die, so you can hit them until they run far enough or you kill them. This can be an advantage point along the whole side of the platform in which you leaped onto.

![anonymous_178](https://user-images.githubusercontent.com/19481783/36336256-66fcc62c-1343-11e8-9c4c-52ef21e1c0e2.jpg)
![anonymous_194](https://user-images.githubusercontent.com/19481783/36336260-73ff412e-1343-11e8-8165-dd82f309cfe7.jpg)
![anonymous_195](https://user-images.githubusercontent.com/19481783/36336261-74196806-1343-11e8-8313-f18bbf8ec2e1.jpg)
![anonymous_196](https://user-images.githubusercontent.com/19481783/36336262-7435d126-1343-11e8-8a6a-7e558a0be3a1.jpg)
![anonymous_197](https://user-images.githubusercontent.com/19481783/36336263-744ce4b0-1343-11e8-8182-b5925c10182e.jpg)
![anonymous_181](https://user-images.githubusercontent.com/19481783/36336268-7f679264-1343-11e8-90cd-4b1594c3cd64.jpg)
![anonymous_182](https://user-images.githubusercontent.com/19481783/36336269-7f861c34-1343-11e8-9e89-35e9171cc51a.jpg)
![anonymous_185](https://user-images.githubusercontent.com/19481783/36336274-8da39580-1343-11e8-9a2e-e9e391705859.jpg)
![anonymous_189](https://user-images.githubusercontent.com/19481783/36336277-8fe06cd8-1343-11e8-9c1d-13b379148b4c.jpg)

More to come...

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 2.3.2018
