### ISSUE TITLE
Overextension Debuff ? [Gunbad]

### ISSUE THREAD

**Issue by rhix112** [WarEmu/WarBugs#11317]
Last boss'es left and right wing - we  getting this debuff and instant wipe

![carsen_004](https://user-images.githubusercontent.com/31020540/36344579-f3c9e2ca-142d-11e8-9308-52be481d3740.jpg)
![carsen_005](https://user-images.githubusercontent.com/31020540/36344580-f3ea2d3c-142d-11e8-96e1-d745489b69d0.jpg)

**Comment by sioding** [comment]
fixed with hotpatch today
