### ISSUE TITLE
Obstruction Glitching by Anonymous Pt. 8 - Stonetroll Crossing

### ISSUE THREAD

**Issue by Cpryt** [WarEmu/WarBugs#11313]
-NOTICE-
These practices are not to be used for malicious intent. They are on the bug-tracker with reason to be noticed a/o fixed. Do not attempt.

Obstruction Glitching Pt. 8 - Stonetroll Crossing

At 24k, 30k, in the Stonetroll Crossing SC, there is a large rock that sits in front of the Destruction spawn point in the scenario. If you run up the slope by the tree at the coordinates given, and turn your character around, backing up and jumping onto the upper part of the rock, you have a large area to run around on without being touched (if ranged DPS). This platform also gives an advantage point over the Battlefield Objective that sits just under the far end of the rock. This could benefit Destruction or the Order realm.

![anonymous_160](https://user-images.githubusercontent.com/19481783/36335090-a2aa6e30-133a-11e8-929e-c3d744daf565.jpg)
![anonymous_161](https://user-images.githubusercontent.com/19481783/36335091-a2c2c854-133a-11e8-99bf-84f702a31cac.jpg)
![anonymous_162](https://user-images.githubusercontent.com/19481783/36335092-a2d9e21e-133a-11e8-872e-225131f8ac76.jpg)
![anonymous_163](https://user-images.githubusercontent.com/19481783/36335093-a2f3532a-133a-11e8-8087-97d1c2e38fb2.jpg)
![anonymous_164](https://user-images.githubusercontent.com/19481783/36335094-a3081b84-133a-11e8-8a83-5b55dd0982bb.jpg)
![anonymous_165](https://user-images.githubusercontent.com/19481783/36335095-a321c1e2-133a-11e8-8aff-effa015b2fee.jpg)
![anonymous_166](https://user-images.githubusercontent.com/19481783/36335096-a3386370-133a-11e8-8e94-6af240fa90a1.jpg)
![anonymous_167](https://user-images.githubusercontent.com/19481783/36335097-a35314b8-133a-11e8-86a7-3a5e5a2534c6.jpg)
![anonymous_168](https://user-images.githubusercontent.com/19481783/36335099-a9037290-133a-11e8-9d65-2f9b224cf8e2.jpg)
![anonymous_169](https://user-images.githubusercontent.com/19481783/36335100-a9219856-133a-11e8-9e59-e7f86386ea8f.jpg)
![anonymous_170](https://user-images.githubusercontent.com/19481783/36335101-a93a6516-133a-11e8-89bd-0a2a2a31ec76.jpg)

More to come...

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 2.3.2018
