### ISSUE TITLE
Witch Elf agile escape early breaking from white lion pet

### ISSUE THREAD

**Issue by asdf92** [WarEmu/WarBugs#11320]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
pet stays rooted after agile escape pet charges after 1 second or completely ignores agile escape (also disappeared while under its effects due to range)

Steps to reproduce the problem:
tab target to white lion pet and use agile escape in combat

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by asdf92** [comment]
did it again seemed to ignore it when it was commanded to attack

**Comment by Torquemadra** [comment]
proof please

**Comment by asdf92** [comment]
will a screenshot reel work, I don't have the means to record I can do screenshot interval 1 per sec

**Comment by asdf92** [comment]
or maybe provide a simple recording software, free fraps isn't working for me very effectively and I spent an hour or 2 with obs and got a black screen

**Comment by Nfkillz** [comment]
probably pet has buff - leonine frenzy?

**Comment by asdf92** [comment]
I don't think I'm gonna be providing any proof sorry

**Comment by asdf92** [comment]
Also For the hag queen it ignored it as it was running away at mount speed , makes it possible to get a screenshot now

**Comment by asdf92** [comment]
happened again on agile escape this time the pet didn't even engage to begin with I didn't get a good screenshot

**Comment by asdf92** [comment]
[IMG]http://i64.tinypic.com/30msimd.jpg[/IMG]
[IMG]http://i65.tinypic.com/3011s41.jpg[/IMG]
[IMG]http://i66.tinypic.com/t4v85z.jpg[/IMG]

**Comment by asdf92** [comment]
if they have the buff it should not stop them in the first place i'd imagine and as for the screenshots sometimes they just been breaking it but the icon will go away so its just a buffhead issue and the pet can auto cast it or something?
