### ISSUE TITLE
[PQ] Ghyran's Embrace

### ISSUE THREAD

**Issue by Shmerrick** [WarEmu/WarBugs#11323]
Stage 2 Mobs are not spawning.
![ghyran s embrace](https://user-images.githubusercontent.com/33600225/36353051-52ffe8be-148f-11e8-8bd4-6206a04c0635.png)

**Comment by Lheana** [comment]
Are you sure you well searched? "Push further into the maze"

**Comment by Shmerrick** [comment]
Yes. The center of the maze is where you complete Phase I. I circled the inner and outer portions of the maze multiple times. I even killed a few random champions that I thought might turn into stags once I killed them.

**Comment by Lheana** [comment]
![anaehll_381](https://user-images.githubusercontent.com/11537611/36354213-0acb67f2-14d1-11e8-9830-054cc46ea608.jpg)

**Comment by Shmerrick** [comment]
So why didn't they spawn the first time.

**Comment by Lheana** [comment]
The first time? The stags spawn close to where the chest is on your map. The ss you put shows the outer wall of the maze.

**Comment by Shmerrick** [comment]
Yes. I understand that. I was at the location you linked in your screenshot when it turned from Phase I to Phase II and the stags didn't spawn. This isn't ignorance on my part, and I'm not trying to waste your time.

**Comment by Lheana** [comment]
Have you tried again the PQ since the first time?
