### ISSUE TITLE
Quest giver for dye; unrepeatable to repeatable?

### ISSUE THREAD

**Issue by Cpryt** [WarEmu/WarBugs#11329]
The quest giver, Caravella Betz in Ostland's Kraussner's Garrison (Order Chapter 7) offers a quest that is repeatable to give dye(s) Dark Yellow, Red, Navy Blue, and Sage Green.

The quest giver, Finn Hobelspan in Avelorn (60k, 19k) offers a quest that gives dye(s) Dark Navy Blue Dye, and Dark Sea Blue Dye. This quest unfortunately is unrepeatable.  This NPC is the only NPC/quest/objective/misc. in the game currently that grants Dark Sea Blue Dye.

Both Caravella Betz and Finn Hobelspan require the player to venture and find x of x objectives.

Caravella 0/6
Finn 0/3

![anonymous_238](https://user-images.githubusercontent.com/19481783/36364848-c6908878-1503-11e8-9382-cb6cd5787756.jpg)

Allow Finn Hobelspan to be a repeatable quest for the dyes? The quest, alike Caravella's quest, offers no XP and two different common-rarity dyes.

**Comment by sioding** [comment]
At the moment there is a NO for it.Sorry.
