### ISSUE TITLE
die in combat makes u in combat forever

### ISSUE THREAD

**Issue by jomy** [WarEmu/WarBugs#1132]
i died a couple of times while questing (by the npc) with the sc queue window open, and i stay in combat forever. u have to exit the game (relog doesnt work) to leave the combat for good.

**Comment by xyeppp** [comment]
That is the combat bug. 
To fix it type in /say &jump

**Comment by Evildoor** [comment]
This was already reported and solution given. https://github.com/WarEmu/WarBugs/issues/1015, for example.
