### ISSUE TITLE
(shadow warrior)Marked gives only 10 bs

### ISSUE THREAD

**Issue by Clypper** [WarEmu/WarBugs#11325]
Marked(5 pieces conqueror bonus) gives only 10 bs
![clypper_097](https://user-images.githubusercontent.com/36601995/36353435-b68737c0-14c6-11e8-8d84-a5566c73c221.jpg)
![clypper_098](https://user-images.githubusercontent.com/36601995/36353438-b90c8842-14c6-11e8-8876-095d3cdf6b69.jpg)

**Comment by zegotax** [comment]
You are using BS pot (I guess it's +80 bs) and since the buff doesn't stack with it you can only get +20. Since you're over cap you get diminishing returns on stat, so you only get +10.

**Comment by sioding** [comment]
thx @zegotax  - all being said. close
