### ISSUE TITLE
Beacon of hope

### ISSUE THREAD

**Issue by BerserkKittens** [WarEmu/WarBugs#11331]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
 Quest "beacon of hope" in Chrace should count defeated Uthorin besiegers, however killing them does not count for quest completion. Tried on multiple characters

Steps to reproduce the problem:
 Simply accept the quest and attempt to complete it. It will not work

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
![image](https://user-images.githubusercontent.com/18517842/36631020-09f15bb2-1971-11e8-846b-2692a16742dd.png)
Works fine for me
