### ISSUE TITLE
A Stuck spot in Reikland Factory scenario, where a punt can get many stuck. 

### ISSUE THREAD

**Issue by Yardape** [WarEmu/WarBugs#11333]
In Reikland Factory scenario, you can get punted in into a corner with a piece of Terrain clutter stopping you from getting out.

Steps to reproduce the problem:
Continue to repeat punt players into the corner, resulting in a swing of active players on the field. 

Screenshots/Videos or archive.org evidences:
![scutegera_004 - copy](https://user-images.githubusercontent.com/19935059/36412199-e82e615a-1664-11e8-9312-e70b6ba50fb9.jpg)
This Picture is of 3 destruction stuck and out of the game because of it
![scutegera_005 - copy](https://user-images.githubusercontent.com/19935059/36412241-145c8090-1665-11e8-96bd-c41d2e57a17e.jpg)
This is a picture from the stuck point looking back at the flag where in this case the IB there continued to punt players into this stuck spot

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 2.3.2018
