### ISSUE TITLE
Race Specifice Pairings zone lock bonuses not working

### ISSUE THREAD

**Issue by Turrin66** [WarEmu/WarBugs#11330]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: When greenskin zones flip I am only receiving half the amount of medallions as other guild and party members of the same race. Essentially, I'm not receiving the racial pairing bonus.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
What the heck is a racial pairing bonus?

**Comment by wargrimnir** [comment]
It's a thing here.

**Comment by sioding** [comment]
OK - reading the patchnotes more precise would stop me asking dumb questions. We are taling about this:
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=25176&hilit=racial+pairing+bonus.

> Introduced pairing medallion bonus - you will get double the medallions from zone lock reward in your racial pairing

Can we please see screenshots with your rewardscompared to your friends from the next lock?

**Comment by sioding** [comment]
No uodate since 2 month - close
