### ISSUE TITLE
Dwarfs vs. Greenskins (Chapters Influence)

### ISSUE THREAD

**Issue by Antalor** [WarEmu/WarBugs#1133]
Hello!
Problem is clear and should be easy. From one Chapter I wanted to make INF and take reward.. I went PQ and starts killing orcs.. There was writing at middle "+50INF" but when I opened book with influence bar and rewards there was writing that I have 0 INF. I was trying relog and other things and this not helped. I maked it on KOTBS 20 lvl.. It should works Im sure. In live even 40 lvl was able to make INF on T1 chapters (and others too) so 20 lvl should too. 
Greetings and please for fast reply =)
PS. This bug can be too at other places (not only dwarfs vs geenskins)

**Comment by Antalor** [comment]
I now checked it again.. This problem is only for Chapter 2

**Comment by Evildoor** [comment]
I remember having similar problems with influence in different places, but they were resolved. Do you still have this problem?

**Comment by Sulorie** [comment]
My t2 rvr inf bar in empire is still empty, while I earn influence in rvr on my DoK. On other toons I had the inf collected for a session but after relogging it was gone too.

**Comment by Evildoor** [comment]
No response, closing.
