### ISSUE TITLE
Always "Need" roll

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#1134]
It seems that something is wrong with loot roll system, it always (at least in my case, so far) treats your choice as "Need" (even though it may change it to "Greed" if you can't use the dropped item).

Recently i've noticed that message "your Need roll was changed to Greed roll" appears even when i select "Greed" on scs. Then i farmed some pve with a friend and tried selecting "Greed" or "Pass" on general items (seeds, jewelry) - each time both of us were in "Need" roll.

**Comment by supercrazylick** [comment]
I have the same issue. It happen everytime I get the loot window open and I click pass. It always need. Here the video I am talking about.

https://youtu.be/yE_yyL7PkOg

**Comment by Evildoor** [comment]
Seems to be working properly now. Closing.
