### ISSUE TITLE
Harbinger of Doom Conversion Toggled off

### ISSUE THREAD

**Issue by Formidilosus** [WarEmu/WarBugs#11340]
The Harbinger of Doom (HoD) Core Ability is a buff that when cast converts the Zealot’s main stats in favor to an offensive or defensive role. HoD converts the bonuses from items.

When toggled on converts:
	Healing power to Magic Power
	Willpower to Intelligence
	Healing Critical Chance to Magic Critical Chance

When toggled off converts:
	Magic Power to Healing power
	Intelligence to Willpower
	Magic Critical Chance to Healing Critical Chance

![hod](https://user-images.githubusercontent.com/17179642/36426724-aab1a2a0-1610-11e8-8093-e6c067766a9b.jpg)

# Issue:
**## HoD, when toggled off does not convert correctly. (Intelligence into Willpower. I don't have anything with Magic Critical Chance and Magic Power to test those)**

![ebou](https://user-images.githubusercontent.com/17179642/36424826-51e5bd10-160a-11e8-98d4-ba329759ad1e.jpg)

This item has +31 Intelligence, when toggled off HoD should convert this into +31 Willpower.

[Warhammer Age of Reckonin 2018-02-20_07-27-13.zip](https://github.com/WarEmu/WarBugs/files/1740184/Warhammer.Age.of.Reckonin.2018-02-20_07-27-13.zip)

When toggled on HoD converts correctly, but when toggled off the Intelligence did not convert into Willpower. 

I think the offensive stats do not convert, but with my lack of items I can't test my hypothesis.

* Complete rules for the bugtracker https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by cimator** [comment]
It does convert it, just doesnt show up on Character window, try it with .getstats

**Comment by sioding** [comment]
Thx @cimator  - can we please see some .getstats screens?

**Comment by Laurentz18** [comment]
I've noticed the displayed stats for my zealot shift on flight zoning or joining/leaving scenarios if I have Harbinger on. It reverts back to displaying stats as if I had Harbinger off. As a habit I now turn off and turn back on the Harbinger whenever I transition locations. Maybe this is a related issue?

**Comment by sioding** [comment]
no reaction for 11 days - close.
