### ISSUE TITLE
Quest: Sigmarite Relic

### ISSUE THREAD

**Issue by ErikWPotter** [WarEmu/WarBugs#11347]
On the step "Find Bone Pile" I located the object "Bone Pile" (floating about a foot above the ground) but neither standing on it and/or clicking on it will complete the requirement.

**Comment by ErikWPotter** [comment]
Strange. I left to do a nearby quest (Bitten) and when I passed by on my way back out (while riding my horse) I was able to click to activate the requirement.

**Comment by PeterOlsenInvokers** [comment]
I found the same problem today (bone pile being unclickable with an hp bar that is empty). I'm guessing a server reset will do the trick. Also, the PQ in the area does not work. No PQ bar comes up and no progression is made by killing trolls.
