### ISSUE TITLE
[KOTBS] No Escape M3 Not Working Properly

### ISSUE THREAD

**Issue by omaewomoshinderu** [WarEmu/WarBugs#11342]
All morale roots in the game un breakable with normal attacks. All morale roots in the game breakable with only [Focused Mind/Casters] , [Juggernaut/Tanks] and Mdps Root Breakers.

Mara M1, WL M1, IB M1, Sorc M4 are all the same.

The only exception is KOTBS M3 No Escape; normal attacks breaking that "Morale Root", it acting like normal tank "Root".

**Comment by Torquemadra** [comment]
working as intended
