### ISSUE TITLE
[No Escape] KoTBS M3 NOT Working as Intented

### ISSUE THREAD

**Issue by omaewomoshinderu** [WarEmu/WarBugs#11345]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=17514

From 07/10/2016 Patch Note Thread;

_Azarael :
Root changes
The Marauder M1 root "Flames of Fate", the White Lion M1 root "Ensnare" and the Knight of the Blazing Sun M3 root "No Escape" will now have a 25% chance to break any time the target is attacked (direct damage, application of DoT, etc.)_

**This change reverted a couple of days later except KoTBS M3 "No Escape"** . Probably it's forgotten while the team reverting Mara M1 and WL M1 morale root conditions.

Again; The only morale root in the game breakable from attacks is "No Escape". It's M3, you need to wait 180 seconds to reach that M3. Atm, it's like normal tank root with aoe damage which **isn't intented**.

**Video from live:**
https://youtu.be/71QaAEZlvoo?t=9

0:11
7:46
11:55
12:57

KoTBS M3 not breaking with normal damage in that moments.

If morales roots should break with normal attacks, the morale roots below is bugged atm.

Mara M1, not breakable
WL M1, not breakable
IB M1, not breakable
Sorc M4, not breakable

**Comment by Servant-of-Chaos** [comment]
I'm %100 sure No Escape was different on live. Both duration and break conditionals.

**Comment by sioding** [comment]
You got a "Working as intended" from a project leader. Please stop creating new reports for this ability.

**Comment by Servant-of-Chaos** [comment]
@sioding OP refering a potantial bug. WL, Mara Morale Root changes **REVERTED**. According the patchnotes, No Escape should act like the same as Mara/WL M1. Could we have a confirmation from @Torquemadra it's not forgotten 1 year ago ?

**Comment by sioding** [comment]
@11342
