### ISSUE TITLE
Gunbad quest "the threat from solithex" just kill the boss and got nothing

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11343]
Just kill the boss solithex and then I got nothing
![thorbolt_115](https://user-images.githubusercontent.com/16274785/36441625-71a7e254-1673-11e8-815f-15c90487edbc.jpg)
 
May be others quests for dye inside Gunabd are bugged also.

**Comment by sioding** [comment]
fixed with patch from 24.02.2018
