### ISSUE TITLE
Furious Mending deactivates at times.

### ISSUE THREAD

**Issue by CeeJay89** [WarEmu/WarBugs#11348]
Expected behavior and actual behavior: Tactic heals you every 5 seconds for XXX amount of life. It normally works fine, however, when you first log in, leave a scenario, and sometimes after dying, the tactic just stops working even though it's slotted. In order to fix, you have to leave combat, unslot the tactic and reslot it to get it to start working again.

Steps to reproduce the problem: First log in, die, leave a scenario, etc...happens quite often, hard to notice sometimes since you can't tell until you start taking damage or pay attention to the combat log for overheal ticks.

Screenshots/Videos or archive.org evidences: Here's a video I uploaded just after a scenario ended to show that it stops working.

https://www.youtube.com/watch?v=YleKNe8Npt4&feature=youtu.be

**Comment by grunbag** [comment]
Tactic have been fixed already
