### ISSUE TITLE
[Engi] Concussive Mine Casttime Debuff Reduced from 50% to 25%

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#11349]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Expected:
Concussive mine is a tactic for the Landmine that puts a +50% builduptime debuff on the hitted Targets.
a 2 sec Ability on the target should be debuffed to a 3 sec casttime. (2 Seconds +50%) = (2 seconds +1 second) = 3 seconds.

Actual Behaviour: 
Debuff Icon says now 25% builduptime.
Test on Squigherder shows increase from 2sec casttime on squig to 2.5 sec casttime. This is plus 25% and not plus 50%.

Steps to reproduce the problem:
1 Engi, 1 Squiggy or other caster. Put Landmine on Squiggy.

Screenshots/Videos or archive.org evidences:

Casttime increase:
![concussive mine](https://user-images.githubusercontent.com/14627932/36533429-d1169964-17c3-11e8-8a05-137bbc928203.png)

Debuff Icon:
![concussive 2](https://user-images.githubusercontent.com/14627932/36533655-8394636e-17c4-11e8-8f3a-2b49d6c853df.png)

_No Goblins where harmed in taking these tests._

**Comment by Servant-of-Chaos** [comment]
working as intented.

**Comment by Pumatouch** [comment]
Here is a 3 second casttime ability. Under effects of Concussive Mines tactic, the buildtime increase is 25%, not 50%. 

![instasplat_003](https://user-images.githubusercontent.com/16616998/36541305-c3b37ff2-17dd-11e8-8b2f-46f8bb40bbe2.jpg)
