### ISSUE TITLE
Marauder tactic Piercing Bite doesn't affect some skills

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#11344]
Description of tactic: All abilities that require mutation now would bypass 50% of enemy armor.
But some skills doesn't affected by this tactic:

Flail - hit twice if mutated or once if not. Obviously, 2nd hit requires mutation, but it is not affected by PB tactic

Gift of Savagery DOT - this is mutation by itself, but still PB tactic has no effect on this DOT.

![marapbbug](https://user-images.githubusercontent.com/16439840/36454816-900babd2-16ae-11e8-9bb8-b47ca56bb068.jpg)

As you can see, in two tests (with and without PB tactic) both skills mitigates by the same value.

At live it wasn't a problem, because PB allowed to bypass 50% armor with anything while mutated. Here this tactic has been fixed, so, I believe, it must work correctly - for anything, that requires mutation.

**Comment by sioding** [comment]
Sorry but can you test that again with an ability that requires a mutation? Flail is an ability which doesn´t require a mutation. It have some extras if you are using a mutation - but its not required.

**Comment by Torquemadra** [comment]
Answered.
