### ISSUE TITLE
Obstruction Glitching by Anonymous Pt. 10 - Phoenix Gate

### ISSUE THREAD

**Issue by Cpryt** [WarEmu/WarBugs#11352]
-NOTICE-
These practices are not to be used for malicious intent. They are on the bug-tracker with reason to be noticed a/o fixed. Do not attempt.

Obstruction Glitching Pt. 10 - Phoenix Gate

In Phoenix Gate (left side; destruction spawn)

At 23k, 37k, there is a small-scaled ledge that you can leap up to. Using "Flee" (or a mount if you are not holding the Battle Objective), you can simply get a running leap and get up into the mountains. If you are holding the Battle Objective, you can potentially control the scenario by having it be unobtainable, whether it harms your own team or the enemy's. Also, whilst up into these mountains, you can potentially harass the enemy spawn. Both spawns can be reached within the mountains.

Additionally, whilst up in the mountains, if you are not carrying the Battle Objective, you have an advantage point (for either side, rDPS or healing) for your own team over the enemy team. As you can see in the screenshots attached below, I am holding the Battle Objective but am in range of healing my own team.

Attached Video:
https://youtu.be/F1XNgOsoABc

![run_042](https://user-images.githubusercontent.com/19481783/36542116-302473da-179d-11e8-9d91-0aaa59c35eff.jpg)
![run_043](https://user-images.githubusercontent.com/19481783/36542120-32e3640a-179d-11e8-9e39-05d978da1bfc.jpg)
![run_044](https://user-images.githubusercontent.com/19481783/36542123-3554a4c4-179d-11e8-8638-e77824a46273.jpg)
![run_045](https://user-images.githubusercontent.com/19481783/36542124-35716a00-179d-11e8-935a-bf6bd9899b19.jpg)
![run_046](https://user-images.githubusercontent.com/19481783/36542125-358d049a-179d-11e8-8294-fe3ada0f897a.jpg)
![run_047](https://user-images.githubusercontent.com/19481783/36542126-35c5edaa-179d-11e8-8656-6828b076302d.jpg)
![run_048](https://user-images.githubusercontent.com/19481783/36542127-35e55424-179d-11e8-949b-80d1974aee9b.jpg)
![run_049](https://user-images.githubusercontent.com/19481783/36542128-3603c238-179d-11e8-99b7-e41c33f6742f.jpg)
![run_050](https://user-images.githubusercontent.com/19481783/36542129-36257842-179d-11e8-84cf-f09664c2b06a.jpg)
![run_051](https://user-images.githubusercontent.com/19481783/36542132-38d8a816-179d-11e8-900e-6e890980f33a.jpg)
![run_052](https://user-images.githubusercontent.com/19481783/36542133-38f11856-179d-11e8-999a-79eff03e6684.jpg)
![run_053](https://user-images.githubusercontent.com/19481783/36542134-39130cf4-179d-11e8-8377-cd66af292f71.jpg)
![screenshot_000](https://user-images.githubusercontent.com/19481783/36542135-392e37c2-179d-11e8-9ae8-4848a509eff1.jpg)

More to come...

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
fixed with patch from 2.3.2018
