### ISSUE TITLE
Multi-Stance bar still trying to reset on SC zone-in

### ISSUE THREAD

**Issue by Gnashspike** [WarEmu/WarBugs#1135]
This doesn't happen every time I play, and I haven't been able to reproduce it. Here's the plays.tv link; there are more notes on bug at the video. Cheers!

http://plays.tv/video/55d95f0e94902f0301

**Comment by Kaelang** [comment]
This video is no longer visible and the report does not provide enough information to identify / replicate the reported issue.

Please re-open this problem if it persists with further information.
