### ISSUE TITLE
Gunbad - Foul Mouf da 'ungry

### ISSUE THREAD

**Issue by Cpryt** [WarEmu/WarBugs#11354]
As of the patch notes from the 16th of February, it is stated that "Increase PQ bosses timers to 30 mins"

When we made way to Foul Mouf da 'ungry, he spawned with under 10 minutes, not 30 - were unable to complete in time.

![run_037](https://user-images.githubusercontent.com/19481783/36545299-d1c9e938-17a5-11e8-9e57-23b3019b0b4e.jpg)
![run_038](https://user-images.githubusercontent.com/19481783/36545300-d1edf1d4-17a5-11e8-97d2-6252d73c06c6.jpg)

**Comment by sioding** [comment]
fixed with patch from 2.3.2018
