### ISSUE TITLE
Gunbad - Teleportation

### ISSUE THREAD

**Issue by Cpryt** [WarEmu/WarBugs#11356]
I will explain this the simplest and best way I can. I am not sure if this has been reported yet or if this is at all intentional, but when entering Gunbad, the portal from the beginning of the dungeon, and the portal at the end of the dungeon (through the doors behind Ard ta Feed), have a tendency to teleport you all the way back to Altdorf instead of outside of the dungeon. That is all I can provide.

**Comment by grunbag** [comment]
It’s a bug , you’ll have the possibility to teleport back to gunbad with guild gunbad scroll at next patch
