### ISSUE TITLE
Mastery points except for 1, are reset on all characters every time you log in, 

### ISSUE THREAD

**Issue by Yardape** [WarEmu/WarBugs#11351]
This issue only started after the Hotfix reboot Wargrim did at about 18:30 AEST (about 5 hours ago).
The Mastery points are all reset except for one.
-I've disabled all addons to check if that's the problem....and to no avail, they are all still reset every time.
-I was under the assumption it could of been the shared profile i have on most of my characters. But it is affecting all profiles.
-I thought it might be the gear with the +1 mastery point in it. But my T2 toons are all still getting reset and they don't have the +1 gear

**Expected behavior and actual behavior:**
Mastery points should stay set on all characters after log out.
After each log out and log on, every character has all it's mastery points reset except for 1

**Steps to reproduce the problem:**
-Log in set mastery points back up, log out.
-Log back in on either the same character or an alternative one, and all points will be reverted except for one

**Screenshots/Videos or archive.org evidence**s:
I only have screenshots of the mastery trees on some characters just to show what i mean. The reason there is 2 points up is because these characters have the +1 Mastery set bonus gear.  If you want a video I can make one if you request it (i'll have to download some software for that)
![yardpig_006](https://user-images.githubusercontent.com/19935059/36540632-e0b3d9aa-1826-11e8-8d8d-18358f814d36.jpg)
![yardy_000](https://user-images.githubusercontent.com/19935059/36540662-fcbeb99e-1826-11e8-9be8-6de1e5bdf7d6.jpg)
![yard_000](https://user-images.githubusercontent.com/19935059/36540692-12edb724-1827-11e8-986b-337f631f3a9c.jpg)

**Comment by Cpryt** [comment]
This does not happen to me... I run a Ritual zealot and with re-logging, my abilities do not go away. My mastery points remain. I do not doubt this error but it could be a visual bug?

**Comment by Cpryt** [comment]
May I add when I say re-logging, I can exit out of the client completely and my mastery abilities/points still remain.

**Comment by Natherul** [comment]
will be fixed in the next patch

**Comment by Afterlife92** [comment]
I have the same issue.

**Comment by sioding** [comment]
fixed with patch from 24.02.2018
