### ISSUE TITLE
Gunbad - Redeye Big Oaf

### ISSUE THREAD

**Issue by Cpryt** [WarEmu/WarBugs#11359]
Greetings,

Not sure if this is intentional but I would like to list it up here just in case. Me and a party attempted 3 times to kill Redeye Big Oaf but as we were seeing the light at the end of the tunnel, Redeye adds spawned and annihilated our group. When clearing the room with the Redeye giants 0/5, the adds aren't supposed to spawn anymore, right? There is a row of 5 Redeye adds that spawn during fighting the Redeye Big Oaf, if we are not near them, the giant will knock us into them, if we are remotely near them, the aggro gets pulled onto our whole team and we get killed. Again, we have nearly killed this 3 times in a row and of those 3 times, we were wiped by the same NPCs. As a suggestion, can this be fixed to where they don't respawn after being killed? Many other NPCs in this dungeon do not respawn after getting killed but for some reason, these 5 have.

Attached screenshot(s):

![run_055](https://user-images.githubusercontent.com/19481783/36559829-4e0dbc88-17cc-11e8-83ef-ec00e4186ee9.jpg)
![run_056](https://user-images.githubusercontent.com/19481783/36559830-4fb912a8-17cc-11e8-9d0c-4cae1f1ef774.jpg)
![run_057](https://user-images.githubusercontent.com/19481783/36559834-51504db6-17cc-11e8-8279-4721c0d3e532.jpg)

**Comment by grunbag** [comment]
THis is intended mechanics . Need to check mobs  timer here
