### ISSUE TITLE
Gunbad - Ard ta Feed Missing

### ISSUE THREAD

**Issue by Cpryt** [WarEmu/WarBugs#11357]
Went through Gunbad with party, reached the end of the mid path, and Ard ta Feed was not at the end. Contacted GM and were told to try exiting Dungeon altogether. Went back in and Ard ta Feed still wasn't around.

![anonymous_046](https://user-images.githubusercontent.com/19481783/36550839-79988c2a-17b3-11e8-8ad9-7379ca4b7e28.jpg)
![anonymous_047](https://user-images.githubusercontent.com/19481783/36550841-79b58848-17b3-11e8-8ea1-b6f1f5c4755d.jpg)
![anonymous_048](https://user-images.githubusercontent.com/19481783/36550842-79d17ad0-17b3-11e8-8d3d-1bf12d195d0c.jpg)

**Comment by Lheana** [comment]
Are you sure no one had a timer for this boss?

**Comment by grunbag** [comment]
Someone has probably a lockout in your party . It works fine
