### ISSUE TITLE
Corrupted Magus (Incorrect Model or Incorrect Monster Type)

### ISSUE THREAD

**Issue by ErikWPotter** [WarEmu/WarBugs#11358]
Expected behavior and actual behavior:
In Ostland, in the catacombs that lead to the Grim Monastery you will find Corrupted Thralls & Corrupted Priests (that appear skeletal), and Corrupted Magus (that appear human).
+ Killing a Corrupted Thrall and Priests credit your Bestiary with a skeleton kill.
+ Killing a Corrupted Magus credits your Bestiary with a skeleton kill.

Either the Corrupted Magus has the wrong character model or is flagged incorrectly for it's Bestiary type.

**Comment by sioding** [comment]
fixed with patch from 24.02.2018
