### ISSUE TITLE
Gunbad - Morgit the Waaagher

### ISSUE THREAD

**Issue by Cpryt** [WarEmu/WarBugs#11360]
Greetings,

Simply, the NPC is located in the Redeye Stompin' Grounds PQ area of Gunbad. NPC is able to be targetted but cannot be damaged. Possibly due to being partly stuck in some collision. Cannot cause damage through AoE either.

Attached screenshot(s):

![run_058](https://user-images.githubusercontent.com/19481783/36560775-fc66b3aa-17ce-11e8-9ed8-041dd52d4ef9.jpg)
![run_059](https://user-images.githubusercontent.com/19481783/36560776-fc819d5a-17ce-11e8-8fb5-27ba9d532344.jpg)
![run_060](https://user-images.githubusercontent.com/19481783/36560777-fcaf892c-17ce-11e8-9b95-6f2ae5862c99.jpg)

**Comment by sioding** [comment]
fixed with patch from 2.3.2018
