### ISSUE TITLE
Empire Chapter 8 Rally Master Demona Gaertner

### ISSUE THREAD

**Issue by ErikWPotter** [WarEmu/WarBugs#11361]
After earning sufficient influence for the Basic rewards (and enough for Advanced and Elite also) the Rally Master overhead icon lights up and the Tome of Knowledge shows "You can collect your Basic Reward!" there are no rewards available.

Talking to the Rally Master and selecting "Select your influence rewards" shows you an empty list under Basic. There are no icons.

**Comment by Lheana** [comment]
Screenshot please.

**Comment by sioding** [comment]
no screenshot - Close
