### ISSUE TITLE
Gunbad - No reward

### ISSUE THREAD

**Issue by Cpryt** [WarEmu/WarBugs#11369]
Glump da Squig Lova at the end of the left wing of Gunbad offers the quest, 'Da New Masta' with a reward of 0 Xp. Possible Xp missing? No reward, or intentional? Leaving this here for review.

![run_096](https://user-images.githubusercontent.com/19481783/36633696-2d8bab46-1957-11e8-8b06-d7b09bdd0544.jpg)
![run_097](https://user-images.githubusercontent.com/19481783/36633697-2da1d5b0-1957-11e8-8cef-220455d52978.jpg)

**Comment by grunbag** [comment]
Fixed in next patch

**Comment by sioding** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=25909
