### ISSUE TITLE
[Gunbad] Undermountain Waaaghum Ring

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#11365]
Initiative instead Intelligence in Shaman's ring

![szam](https://user-images.githubusercontent.com/13823154/36617151-ad37e3bc-18e6-11e8-9579-d4758dadc405.jpg)

Here is DoK's 
![febr](https://user-images.githubusercontent.com/13823154/36617178-bcd699b2-18e6-11e8-8288-22c726321ac3.jpg)

Since Zealot can switch stats to dps Shaman is only healer now who dont have off stat on this rings

**Comment by wargrimnir** [comment]
Not a bug.

**Comment by MKorin** [comment]
Ahh of course not a bug just imbecility.
