### ISSUE TITLE
[sorcerer] Arctic blast's snare support

### ISSUE THREAD

**Issue by Starwhisper** [WarEmu/WarBugs#1137]
Hi, I know this could be a case of "buff my class", but I'll try to stay as objective as possible.

 So arctic blast can snare targets afflicted by a curse for 5 seconds. Right now the game checks if the target is cursed at the end of the cast and applies the snare when the missile hits the target. So in order to slow someone you need to put a curse (1.5sec), then cast arctic blast (2sec) then wait for travel time (~0.7?).

 Could it be changed to check if the target is cursed when the missile hits the target? After all the snare effect is triggered when the missile hits.
 It would also put this ability in line with "unshakable focus": sh & sw, for example, can use a 3sec cast and pop M2 when the arrow is flying to land a buffed arrow even if M2 was not activated at the end of the cast.
 Theory-wise, it is complete fantasy and archer suddenly entering trance when he shot his arrow and empowering it while it is flying, while is seems (somewhat lol) logical that a spell triggering a slow on touch checks if the targed is cursed on touch and not beforehand. (this sentence has no value gameplay wise, I know it)
 Finally this would make arctic blast really able to slow a melee running to the sorc (~2.5sec to slow compared to  ~4.2sec to slow at the moment) thus giving a real use to this spell outside of a burst rotation and explaining why this spell got a cooldown whils his couterpart got none.

sorry for wall of text.

**Comment by ozarmidrashim** [comment]
This as well as Snap Shot and Throwing Dagger will now check their snare condition on hit instead of on cast.
