### ISSUE TITLE
934+80=354...? Incorrect status on potion usage

### ISSUE THREAD

**Issue by Cpryt** [WarEmu/WarBugs#11370]
Usage of Lasting Potion of Discipline only increases my willpower by 20, not 80, as it states.

"Increases your willpower by 80 for 60 minutes."

![run_102](https://user-images.githubusercontent.com/19481783/36636068-00e931a6-197c-11e8-8a3a-dfdb1c12a122.jpg)
![run_103](https://user-images.githubusercontent.com/19481783/36636069-00ff96da-197c-11e8-8515-4c74bbe187f6.jpg)
![run_104](https://user-images.githubusercontent.com/19481783/36636070-0116af00-197c-11e8-970c-ed527242da06.jpg)

¯\_(ツ)_/¯

**Comment by sioding** [comment]
As far as is see it in your screens. You are using Mark of the Spell Destroyer for a willpower buff. You will only be get a 80 stats buff - the potion will not stack - only fillup until 80. so no bug - sorry.
