### ISSUE TITLE
order quest badland : "finding phineas"  no questmarker

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11375]
I complete the quest inside gunbad then when you get out 
![thorbolt_119](https://user-images.githubusercontent.com/16274785/36638823-833ca872-19fe-11e8-835f-c48e1fa88ae1.jpg)
no red mark on the map.

The questmarker must be at chapter 11 dwarf,  (NPC name : brudig stouthelm)

![thorbolt_120](https://user-images.githubusercontent.com/16274785/36638824-9b0be512-19fe-11e8-9e70-3f13f778e3b8.jpg)

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 2.3.2018

**Comment by DurinThornaxe** [comment]
I have this problem where I can't find Phineas' remains. Me and a friend had the usual 4 hours Gunbad run the other night and we stood around after we cleared it looking for that dude described in the quest for more than 2 hours without Success. 

Thank you for your time and effort, 
Durinsson

![Untitled](https://user-images.githubusercontent.com/86794706/132705996-58baeb4a-f41a-483e-ae35-21175d1fdfc8.jpg)
