### ISSUE TITLE
Obstruction Glitching by Anonymous Pt. 12 - Howling Gorge

### ISSUE THREAD

**Issue by Cpryt** [WarEmu/WarBugs#11374]
-NOTICE-
These practices are not to be used for malicious intent. They are on the bug-tracker with reason to be noticed a/o fixed. Do not attempt.

Obstruction Glitching Pt. 12 - Howling Gorge

In Howling Gorge (from destruction spawn)

Attached is a video to get to a vantage point over the enemy team if you are able to climb such. The elevated area can be used for rDPS and healing, offering such of what could be unnoticed throughout most of the game... In the video, I show the only way (that I have found) to get up this rock formation. It's quite easy, and takes minimal effort. I am leaving this up for developer opinion.

Attached Video:
https://youtu.be/eG3_Z0dESWQ

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
we have decided no to do anything here.
