### ISSUE TITLE
Log In bug ( I look like the Thing)

### ISSUE THREAD

**Issue by KasperHawker** [WarEmu/WarBugs#11372]
Hi Guys,

I've tried to log in, but bounced off the server. I think decided to create a white lion called Nerfwhitelions.

The result was i logged into a half Shaman half-white lion character at the same time.

![bug](https://user-images.githubusercontent.com/36804013/36636546-d1dd6630-19c0-11e8-9ff8-6179159643af.JPG)

I don't know what you could do with this bug, but i thought it worth reporting.

Kind Regards,
Snarsnarik.

**Comment by MaxHayman** [comment]
Should be fixed.
