### ISSUE TITLE
Misplaced NPC, Saphery

### ISSUE THREAD

**Issue by Cpryt** [WarEmu/WarBugs#11379]
At Kyaran's Advance (Dark Elf Chapter 14) in Saphery, there is a passive Archmage of Hoeth inside of the encampment area. Possibly doesn't need to be there. Leaving this for developer opinion.

Attached screenshot(s):

![run_110](https://user-images.githubusercontent.com/19481783/36641595-69a88f5c-19ef-11e8-990b-cd5c7c366a12.jpg)
![run_111](https://user-images.githubusercontent.com/19481783/36641596-69c083c8-19ef-11e8-94a5-289c93a2ef07.jpg)
![run_112](https://user-images.githubusercontent.com/19481783/36641597-6e446ffe-19ef-11e8-8a07-c9e512255c69.jpg)
![run_113](https://user-images.githubusercontent.com/19481783/36641598-6e5c593e-19ef-11e8-84ba-8a92cef12431.jpg)

**Comment by wargrimnir** [comment]
Doesn't appear to be used for any quests or tok's. Removed.

**Comment by sioding** [comment]
fixed with patch from 09.03.2018
