### ISSUE TITLE
Witch Elf Ruthless assault early inturupt

### ISSUE THREAD

**Issue by asdf92** [WarEmu/WarBugs#11386]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:cast ruthless assault use it for 3 seconds ; use it for 3 seconds get LOS interrupted by a player

Steps to reproduce the problem:
use ruthless assault in packed environment 

Screenshots/Videos or archive.org evidences: I will try and get some if it is said this is a bug

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format.
