### ISSUE TITLE
Honorable Deceit T3 Dark Elves Epic Quest

### ISSUE THREAD

**Issue by Jankristian** [WarEmu/WarBugs#11381]
**Character** : Jankristianz
**NPC** : Shelathi Rorthandor, Avelorn Warcamp
**Step** : Last

I have finished the quest on saturday 24 February.
I was able to get one of the two weapons from the NPC (which had closed the quest).
I came back on sunday 25 February.
NPC had the orange marker and I was able to get the other weapon.

I have done this quest with two other character and it's the first time the NPC has this behavior.

**Comment by sioding** [comment]
Checked the quest - can not reproduce this.
