### ISSUE TITLE
Gunbad: Wight King Solithex - Undead Giant spawn phase

### ISSUE THREAD

**Issue by Zoggof** [WarEmu/WarBugs#11382]
During the fight with Wight King Solithex, once you reach the stage where he summons 4 undead giants. The super punt up into the air can cause issues where the mob disappears out of LOS if you have aggro on them when punted because the game thinks they are up in the air with you. This can cause the mob to get stuck up in the air visually where you cannot target them without some extreme kiting to drag them out of the skybox.

Also we encountered another issue where once we killed all 4 giants, another 4 immediately got summoned in (not sure if this is working as intended but I figured to report it anyway), we've fought the boss before where the giants didn't respawn after we had killed them all.

**Comment by Tesq** [comment]
the giant re summon since also to happen when you take a bit to kill em

**Comment by Zoggof** [comment]
The timer for them being killed must be pretty extreme in that case. We killed the giants fairly quickly both times.

**Comment by grunbag** [comment]
Already fixed
