### ISSUE TITLE
Bulbous belts, unable to dye

### ISSUE THREAD

**Issue by Cpryt** [WarEmu/WarBugs#11388]
Bulbous belts received from The Bulbous One in West Praag are unable to dye. When another belt is equipped that can be dyed, and the Bulbous belt is put on the dyed belt as an alternate appearance, the Bulbous belt takes the colors of that item.

Unlike items like Beastlord Mantle of the Stag that cannot be dyed but takes place over no dyed item if used as an alternate appearance, this item, the Bulbous belt, signifies that it could be dyed. This may be the instance with all Bulbous belts and not just the zealot's one. Leaving this here for developer opinion.

![run_000](https://user-images.githubusercontent.com/19481783/36676086-f8cc0500-1ac7-11e8-9aac-c7b3eb8218be.jpg)
![run_001](https://user-images.githubusercontent.com/19481783/36676087-f8e26b60-1ac7-11e8-9e41-99e973cdee1a.jpg)
![run_002](https://user-images.githubusercontent.com/19481783/36676088-f8f8dd46-1ac7-11e8-9e88-6416b5bde37e.jpg)
![run_003](https://user-images.githubusercontent.com/19481783/36676089-f91540f8-1ac7-11e8-9ec6-c57a64025314.jpg)
![run_004](https://user-images.githubusercontent.com/19481783/36676091-f930e27c-1ac7-11e8-8bf7-82d0519756ca.jpg)
![run_005](https://user-images.githubusercontent.com/19481783/36676092-f947d0fe-1ac7-11e8-8ed6-23776e705c90.jpg)

**Comment by NorKalli** [comment]
@Hargrim Mind if I update all the belt pieces to dyeable?

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
