### ISSUE TITLE
Heavy Rams Appearing as Light Rams in Tier 2 Zones

### ISSUE THREAD

**Issue by dansarii** [WarEmu/WarBugs#11389]
During the RVR campaign in a Tier 2 zone: when you spawn a heavy ram, it will generate a light ram instead.

- Need to add evidence of this occurring (screenshots).
- Need to test if this is simply a visual bug or if it affects the stats of the ram as well.
- Need to confirm if this occurs in T3 zones with medium rams as well.

**Comment by dansarii** [comment]
- Need to confirm if this occurs in T3 zones with medium rams as well.

**Comment by Natherul** [comment]
fixed in the next patch

**Comment by sioding** [comment]
fixed with patch from 09.03.2018
