### ISSUE TITLE
Repopen of Quest - Eye for an eye #10613

### ISSUE THREAD

**Issue by ErikWPotter** [WarEmu/WarBugs#11399]
You are tasked with "Kill Enemy Choppas" (quest text says 20 but tracking log says 0/10). However killing "Black Skull Choppa" in the PQ: Battle at Blood Fen does not grant credit.

Additionally there is no map 'lake' indicator.

**Comment by sioding** [comment]
The quest description is corrected to ten choppas. and no - no questmarker cause you need to find the choppas in RvR/Sc´s.

**Comment by sioding** [comment]
fixed with patch from 2.3.2018
