### ISSUE TITLE
Being kicked out of a guild almost every time I log off.

### ISSUE THREAD

**Issue by Wedard** [WarEmu/WarBugs#11395]
I have been having issues with being kicked out of the guild when I log off and having to be invited again. The guild doesn't even register my being kicked and there are at least 5 or 6 instances of me joining in the log of the guild without leaving. At first I thought it was because on exit my client crashed so I tried logging off first and then quitting and that sometimes works but sometimes the end result is the same.  I am on Order, the guild is Klinger's Regiment and my character is Backstabbath.

**Comment by Natherul** [comment]
will be fixed on next reboot, issue in your case was that the DB remembered you being in a guild that does not exist which caused it to not register the new membership into the database.

**Comment by Wedard** [comment]
Thanks so much! 

    On Monday, March 5, 2018 1:56 PM, Mark Jack Sundahl <notifications@github.com> wrote:
 

 will be fixed on next reboot, issue in your case was that the DB remembered you being in a guild that does not exist which caused it to not register the new membership into the database.—
