### ISSUE TITLE
SC Shield for Chosen

### ISSUE THREAD

**Issue by osium** [WarEmu/WarBugs#1139]
the SC shield for the chosen now lists no block rating after testing this is indeed not a graphical bug the shield now has zero block rating as of today

**Comment by osium** [comment]
this is still broken not sure if that blurb in the last patch was about this shield

**Comment by milosxe** [comment]
Chosen shields are now showing the block rating. Since I can't buy them and test the block chance, can anyone confirm the fix?

**Comment by Reggaewaldo** [comment]
It is fixed. I have doublechecked both shields.

Closing.
