### ISSUE TITLE
Gunbad, PQ A Taint from Below, issue with contribution

### ISSUE THREAD

**Issue by Grunbeast** [WarEmu/WarBugs#11393]
Yesterday we have done this public quest and only 2 players out of 6 was in contribution board.
![gun](https://user-images.githubusercontent.com/35007878/36729765-8dd4b130-1bc5-11e8-8651-b923f4d6cd1e.png)
We have tanked the boss at waterfall. Me and another tank stood in the middle of the room with nurglings.
So we have been knocked back fairly far away.

**Comment by grunbag** [comment]
I can’t fix it , it’s a positioning issue
