### ISSUE TITLE
Swimming in air in West Praag 

### ISSUE THREAD

**Issue by Nesiex** [WarEmu/WarBugs#11409]
I found this area in West Praag during the quest "Explosive Situation" while looting the Plunger Wiring. Upon dropping down from where you loot the item (Which is the only way out) and instead of hitting the bottom of the valley and dieing so i could get unstuck from the situation, i instead was met with endless swimming in mid air. 

![boaty_000](https://user-images.githubusercontent.com/36968057/36863886-3c443668-1d48-11e8-8906-e3a880c91e6d.jpg)
![boaty_001](https://user-images.githubusercontent.com/36968057/36863894-3eebfd74-1d48-11e8-842a-bd29d8167833.jpg)
![boaty_002](https://user-images.githubusercontent.com/36968057/36863911-497d669c-1d48-11e8-820a-0f1b47ef0b72.jpg)

**Comment by manuelando** [comment]
Happened to me to, on the same situation and for the same thinking xD.
The character still swim Horizontally as while in water but texureless.

**Comment by sioding** [comment]
fixed with patch from 26.05.2018
