### ISSUE TITLE
Quest: Center of the World

### ISSUE THREAD

**Issue by ErikWPotter** [WarEmu/WarBugs#11401]
The quest has the task of "Speak to Patriarch Thyrus Gormann". Both the quest text and the map arrow marker point to his being in the Bright Wizard College.

I've tried to enter the portal guarded by the two necromancers in Altdorf at about 32k, 34k but the portal does not admit me.

**Comment by Lheana** [comment]
BWC is not opened yet.

**Comment by Eusebeus82** [comment]
I'll add to this issue, as it is related.

Quest: On the Brink of Chaos also refers you to speak to Thyrus Gormann in the BWC as well, and therefore can not be advanced.
The quest is obtained from an NPC at 11.5k 24.5k in Reikland, although previous quests may be needed as part of a quest chain.

It is worth noting, that at some stage of RoR I think Thyrus Gormann was placed outside the BWC so the Centre of the World quest could be completed, as I have done it on my main, and unlocked the Tome point for talking to him.

![eusebeus_001](https://user-images.githubusercontent.com/18599533/41131023-579ae8b0-6ab1-11e8-9fa4-4f3a3c8dc426.jpg)

![eusebeus_002](https://user-images.githubusercontent.com/18599533/41131047-6fd02ef4-6ab1-11e8-9a6e-7dfdc772b96f.jpg)

**Comment by Lheana** [comment]
BWC is now accessible, so these quests must work now.
