### ISSUE TITLE
Crafting/Cultivating: Everlasting Yellow Honeythorn Seed doesn't work

### ISSUE THREAD

**Issue by Heniek7799** [WarEmu/WarBugs#11405]
Expected behavior and actual behavior:

Supposed to growth and after refine should be apothecary ingredient  for liniment of war:blood  (60wounds + 5% crit). Atm it just doesn't work, can't place a seed into a vacant plot to start growth cycle. Any other 200 lev seed working as intended.

**Comment by Kaelang** [comment]
This seed isn't implemented as of yet - if this seed does make it to live, and issues persist - please reopen such report.
