### ISSUE TITLE
[choppa] Recless Blow

### ISSUE THREAD

**Issue by flannelok** [WarEmu/WarBugs#11413]
Hello. Today sudenly checked that choppas finisher ability [Recless Blow] not working properly. Checked ingame .ab changelist and finding nothing. So [Recless Blow] not providing 5% male crit chance buff. Cheked this with 29% crit with duals, and 28% with 2h weapon.
![rb1](https://user-images.githubusercontent.com/33010012/36937181-6a8fc802-1edd-11e8-8024-472e8ed8fa02.jpg)
![rb2](https://user-images.githubusercontent.com/33010012/36937182-6c4171aa-1edd-11e8-8454-af8d6232e81e.jpg)

Screenshots/Videos or archive.org evidences:

**Comment by cimator** [comment]
It doesnt provide a melee crit bonus, it increases your chance to be critically hit. You can see it on your .getstats as, CriticalHitRateReduction -5
