### ISSUE TITLE
Tactic Hastened Dismissal does not grant cooldown reduce for Repel

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#11417]
use of sword'n'board seems to bug the hastened dismissal tactic into not providing the reduced cooldown for the chosens repel, although it still gets the range/height buff - notice in the first screenshot i have the tactic selected yet yet the cooldown on repel is 15s at the time of the screenshot, a quick trip to IC to get my 2h out of the bank and you see that the cooldown is properly reduced (compare combat log timestamp against action bar)
![abizmhaal_002](https://user-images.githubusercontent.com/16922842/36943110-f3584d9c-1f7a-11e8-8244-115381245c25.jpg)
![abizmhaal_003](https://user-images.githubusercontent.com/16922842/36943111-fb1d7872-1f7a-11e8-84f6-cffd6d8255ef.jpg)

**Comment by sioding** [comment]
Working as intended:
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=23117#p258569

> Chosen

Tactic - Hastened Dismissal now grants the cooldown reduction of Repel only if you are weilding a Great Weapon, super punt effect remains regardless of weapon used.
