### ISSUE TITLE
Elf Chapter 18 Influence PVE

### ISSUE THREAD

**Issue by swilkers808** [WarEmu/WarBugs#11415]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
PQ Keepers Watch - Influence is shown on the screen as being given but the influence rewards bar for chapter 18 fails to fill up. I killed 30+ in this PQ and the bar did not register any influence. 

Steps to reproduce the problem:
Play the PQ Keepers Watch - Kill elves and the bar will not fill up. 

Screenshots/Videos or archive.org evidences:
![2018-03-03 11_38_00-warhammer_ age of reckoning version 1 4 8 copyright 2001-2012 electronic arts](https://user-images.githubusercontent.com/5131136/36938921-8ee0bdc4-1edd-11e8-9761-510c882201fd.png)

**Comment by Lheana** [comment]
Thanks for report, fixed next patch

**Comment by sioding** [comment]
fixed with patch from 09.03.2018
