### ISSUE TITLE
[Reikland] NPC riding a weird yellow dude in Ch22

### ISSUE THREAD

**Issue by stillwaterww** [WarEmu/WarBugs#11414]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

ehm... ill let the screenshot do the talking.

Screenshots/Videos or archive.org evidences:

![yellowdude](https://user-images.githubusercontent.com/19287032/36937814-3b4b8c3e-1f19-11e8-82be-93f1e6f80146.png)

**Comment by Lheana** [comment]
Everything is fine for me

**Comment by stillwaterww** [comment]
I have returned to the spot and now the npc looks fine, mustve been an error on my side I think

**Comment by Lheana** [comment]
Ok so closing the ticket.
