### ISSUE TITLE
Character bugged

### ISSUE THREAD

**Issue by Shelene** [WarEmu/WarBugs#11410]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Steps to reproduce the problem:
I have a character named Shídara, when i logued in i saw that the name has changed to ShÄdara, as the same time, i don´t appear in groups, searching window...etc, others players can´t select me and more bugs. Please help me! Thanks

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Ask a GM which is online to rename you if you are not 40/40 and can do it on your own.
