### ISSUE TITLE
Quest: "spotting trouble" Altdorf. No questmarker on the map

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11419]
No questmarker on the map. The questmarker should be at 26.29 Altdorf.
![thorbolt_123](https://user-images.githubusercontent.com/16274785/36972816-e1734c16-2070-11e8-876a-dea8c7f137f3.jpg)
![thorbolt_124](https://user-images.githubusercontent.com/16274785/36972825-e8ce1338-2070-11e8-9dcf-6267e08a040a.jpg)

**Comment by sioding** [comment]
questmarker for all steps checked

**Comment by sioding** [comment]
fixed with patch from 09.03.2018
