### ISSUE TITLE
Quest: "spotting trouble" Altdorf. Cant' finish the quest

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11420]
When you arrive at the NPC and right click on it, he opens a pannel to change name so you can't finish "spotting trouble" quest.
![thorbolt_125](https://user-images.githubusercontent.com/16274785/36972936-5afdde8e-2071-11e8-9731-f66953b704bd.jpg)

**Comment by thorbolt80** [comment]
![thorbolt_126](https://user-images.githubusercontent.com/16274785/36972983-7a9cd6b4-2071-11e8-8d2b-34d1f69d0954.jpg)

**Comment by Natherul** [comment]
will be fixed in the next patch

**Comment by thorbolt80** [comment]
fixed
