### ISSUE TITLE
Crafting Blotchy Smedleycap

### ISSUE THREAD

**Issue by Livetoserve** [WarEmu/WarBugs#11429]
So whenever I get a critical on the level 25 "Blotchy Smedleycap" I get a level 35 intelligence potion instead of a level 10 critical potion. On the craft I use level 200 resin, 200 taut, 200 fusk, and a level 1 vial. The strength, ballistic, napalm, etc all make into the critical 10 potions.

**Comment by sioding** [comment]
Duplicate of #11392
