### ISSUE TITLE
liniment of boundless sight description missing

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11426]
The end of the sentence is missing he should be : use : increase your initiative and wounds  **for 30 minutes**
![thorbolt_128](https://user-images.githubusercontent.com/16274785/37077223-439c4680-21da-11e8-977f-a301e68de82f.jpg)

**Comment by NorKalli** [comment]
Green description = spell ID = can't be changed yet, however updated grey/item description

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
