### ISSUE TITLE
Regulation Torc for slayer

### ISSUE THREAD

**Issue by Livetoserve** [WarEmu/WarBugs#11428]
So all the other level 13 regulation shoulders have talisman slots available on them except the "Regulation Torc" for the slayer.

Screenshots/Videos or archive.org evidences:
![regulation torc for slayer](https://user-images.githubusercontent.com/37156009/37112391-406546b6-2210-11e8-871c-9c69d7d442fd.png)

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
