### ISSUE TITLE
sigmar's grace overheal

### ISSUE THREAD

**Issue by lftr** [WarEmu/WarBugs#11425]
The wp skill sigmar's grace is bugged or the sc's scoreboard is.
When you heal your targets with sigmar's grace EVEN IF YOUR TARGETS ARE FULL LIFE the heal done is counted for the scoreboard at the sc end.

**Comment by sioding** [comment]
Can we please see your testing screenshots?

**Comment by lftr** [comment]
yes here  two screenshots:

the first show the first secondes of one sc when poeple are joining

and the second the heal done during this sc




2018-03-06 21:17 GMT+01:00 Sio <notifications@github.com>:

**Comment by sioding** [comment]
Screenhots are not added via enail. Please attach it on the report.

**Comment by lftr** [comment]
![image](https://user-images.githubusercontent.com/19917186/37110460-46a4b52a-223d-11e8-8b42-514b4ae0012a.png)

**Comment by dalen** [comment]
Isn't this the same as any wounds buff, including the Magus ability Aegis of Orange Fire. Seems a bit like a non-issue as well tbh.
