### ISSUE TITLE
The 10s root's new complete freeze of movement together with a KD -> 10s KD!

### ISSUE THREAD

**Issue by deLunel** [WarEmu/WarBugs#11422]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
So, personal view but when 2 (in my case were 2 WLs but any class) players wait to build morale and then coordinate a KD and root, it seems to turn into a full 10s helpless knockdown during which my defensive S+B tank was leisurly chopped apart by the WLs while not able to do anything at all.
Fine if one cannot rotate, but atleast the KD should not last throughout the 10s root so one can use abilities atleast.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Thanks for the report. Beside your personal view, you said "it seems" - can we please see any proof for it?

**Comment by deLunel** [comment]
Seems = schooled to write cautiously politely :).. ok, tried to recreate myself with friends on destro toons against an order but he definitely wasnt kd longer than my 3s Down Ya Go. Cannot try with WLs cos we dont play them.
Hm, so cant replicate - guess I must been wrong. my bad and apologies for wasting time.

**Comment by sioding** [comment]
and close ;)
