### ISSUE TITLE
Slayer Keep PQ

### ISSUE THREAD

**Issue by korwrath** [WarEmu/WarBugs#11424]
Standard mobs in The PQ Slayer keep are far beyond the level/rank they say they are (40 - 41).  They also take longer to kill then other mobs of that rank as well as hitting quite harder as well.  Not only that but they will constantly seek out players that have aggroed them endlessly, though will still rummberband, but moment you enter the area they will disengage from even NPCs they are fighting and beeline right for you.

**Comment by sioding** [comment]
Chapter 22 hard PQ´s are being redesigned atm to fit a warband balance level. So no bug - working as intended.
