### ISSUE TITLE
DW Destruction Warcamp - Order can reach and atttack in camp via PVE quest area 

### ISSUE THREAD

**Issue by deLunel** [WarEmu/WarBugs#11421]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
As per headline, would expect safety while in the Dragonwake War camp. See Bright Wizard. He and his healer came down from where my screen shot is taken from (the Caladain Step PQ area) .
Maybe an NPC can be placed somewhere that side of camp?

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![gitbrain_001](https://user-images.githubusercontent.com/26348163/36972910-4441220a-2071-11e8-89a7-78dfbcd3982b.jpg)

**Comment by sioding** [comment]
fixed with patch from 09.03.2018
