### ISSUE TITLE
Hold the Line!

### ISSUE THREAD

**Issue by bugreportingisnotworththeeffort** [WarEmu/WarBugs#1142]
After activation and even a quick cancel the buff seems to stay for the full 12 seconds onto allies.
I can not say whether it is just visually or whether the 15% dodge/disrupt are really applied.
This could be abused by tanks using and canceling "Hold the Line!" every 12 seconds to support every ally with 15% protection from range attacks. It stacks up too with multiple tanks (which is working as intended).

**Comment by Silentguard** [comment]
Just checked it. Sometimes buff persist cancelling.

**Comment by Temmacore** [comment]
the block rating at chosen for emblems of the scenario doesn't work at a board
