### ISSUE TITLE
Warriorpriest charm Book of quelled adversaries has the wrong appearance

### ISSUE THREAD

**Issue by gomboni** [WarEmu/WarBugs#11436]
Expected behavior and actual behavior:
The item Book of quelled adversaries looks like a 2handed weapon.

Steps to reproduce the problem:
The item comes from an rvr bag.

Screenshots/Videos or archive.org evidences:
https://i.gyazo.com/3f20a4571561d9796d7f08de9f7c6614.jpg

**Comment by NorKalli** [comment]
assigned a book appearance

**Comment by sioding** [comment]
fixed with patch from 05.05.2018

**Comment by NorKalli** [comment]
This didn't make last weeks patched, but it's fixed with the next one

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
