### ISSUE TITLE
Reopen of Quest - Bloody Shame #10612

### ISSUE THREAD

**Issue by ErikWPotter** [WarEmu/WarBugs#11437]
There is no map tracker for
Order Quest: Bloody Shame
Zone: Marshes of Madness
Task: Kill Gazrog Beardrippa

**Comment by ErikWPotter** [comment]
Additionally, the quest description in the tome directs you to Rottoof Swamp, it's called Rotfoot Swamp.

More importantly, Gazrog is not in Rotfoot Swamp. He is in Deadwater.

**Comment by sioding** [comment]
#10612

**Comment by sioding** [comment]
fixed with next petch

**Comment by sioding** [comment]
.Fixed with patch from .17.03.2018
