### ISSUE TITLE
[Morale] You can use M1, M2 that aren't sloted

### ISSUE THREAD

**Issue by bozzax** [WarEmu/WarBugs#1143]
There need to be a check server side that the morale being used is also in a morale slot

**Comment by Tesq** [comment]
also flee do not reset moral bar.

**Comment by Evildoor** [comment]
It is also possible to change morales in morale slots during combat. Icon remains the same, but description and effect are changing.

**Comment by Evildoor** [comment]
No longer possible to use morale not in slot, but still possible to swap them.

**Comment by Evildoor** [comment]
Was fixed at some point.
