### ISSUE TITLE
Scenario Unable to Leave

### ISSUE THREAD

**Issue by Aldmhac** [WarEmu/WarBugs#11435]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

After the scenario is completed we expect to be able to click the "Leave Now" button. Actual behavior: clicking it and the scenario continues/ unable to leave.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
SC´s has been broken - fixed with restart
