### ISSUE TITLE
Visual mount bug

### ISSUE THREAD

**Issue by jihsgabj** [WarEmu/WarBugs#11432]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Happens when i try to use low lvl mount and instead of the horse i'm riding a naked dude.
![imladris_030](https://user-images.githubusercontent.com/33173649/37151353-36b668b2-22e6-11e8-9952-27a7cc9bce37.jpg)
![imladris_032](https://user-images.githubusercontent.com/33173649/37151354-36d821aa-22e6-11e8-9a47-e86c750d8537.jpg)
![imladris_035](https://user-images.githubusercontent.com/33173649/37151355-36fd35b2-22e6-11e8-943f-98cf1fc1f248.jpg)

Steps to reproduce the problem:
Giving me one of those fancy looking griffon mounts might fix the bug :-)

Screenshots/Videos or archive.org evidences:

**Comment by Lheana** [comment]
Name of the mount please.

**Comment by jihsgabj** [comment]
Give it a fitting name.

**Comment by Lheana** [comment]
...
When you write "Happens when i try to use low lvl mount and instead of the horse i'm riding a naked dude." what is the name of the mount you try to use?

**Comment by jihsgabj** [comment]
The basic mount you get from the beginning, it didn't happened again after i relogged though.
