### ISSUE TITLE
Quest "sum of the whole" - bloodmaw gnoblar is unattackable

### ISSUE THREAD

**Issue by Joshwa70** [WarEmu/WarBugs#11438]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
should be able to kill the mob for quest "sum of the whole"
bloodmaw gnoblar in badlands 40k 37k and he is unable to engage.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
I do not find any quest with this name. please add a screenshot.

**Comment by Lheana** [comment]
I think he means https://wiki.returnofreckoning.com/index.php/Sum_of_the_Whole

**Comment by Lheana** [comment]
Nevertheless I tried with order and destruction char, works fine for me, and there are several spawns of this NPC. If only one spawn is unattackable, find him and give coord and screenshot.

**Comment by sioding** [comment]
No reaction for 11 days. Close
