### ISSUE TITLE
[Zealot] Lashing Waves Tactic

### ISSUE THREAD

**Issue by Laurentz18** [WarEmu/WarBugs#11439]
Expected behavior and actual behavior:

Lashing Waves is a Zealot tactic that turns our single target silence dot Tzeentch's Lash into a 20ft aoe silence dot centered on the primary target. When buying and loading this tactic you get an error message saying "Nonexistant tactic: 8599 Lashing Waves". It will show the tactic as being slotted, but when using it the aoe component does not trigger.

I also fear that if this tactic were doing the aoe effect, it might also suffer from the same issue as Chaotic Agitation I previously reported.

Screenshots/Videos or archive.org evidences:

Below is a screenshot of the tactic being bought and loaded with the error message in the dialog.

![laurentz_021](https://user-images.githubusercontent.com/36253097/37243327-1858e752-243d-11e8-8a3a-f3d10b59cb57.jpg)

Here are a few screenshots of me testing it on a mob where it should have hit multiple targets but, hit only one. Casting, target hit and begins running to me, first tick of dot damage occurs after 1 second.

![laurentz_023](https://user-images.githubusercontent.com/36253097/37243346-585055a2-243d-11e8-89ad-50e507365cfa.jpg)

![laurentz_027](https://user-images.githubusercontent.com/36253097/37243352-6c70587a-243d-11e8-8335-505e22d314ee.jpg)

![laurentz_033](https://user-images.githubusercontent.com/36253097/37243361-978d21aa-243d-11e8-8477-89a167d45d0b.jpg)

**Comment by AxelF17** [comment]
Can confirm that this is still an issue as of 05/05/18, can someone confirm this is being looked at please?

**Comment by Atomicfate** [comment]
Still an issue

**Comment by Natherul** [comment]
fixed as of patch just now
