### ISSUE TITLE
[Zealot] Wind of Insanity

### ISSUE THREAD

**Issue by Laurentz18** [WarEmu/WarBugs#11440]
Expected behavior and actual behavior:

![laurentz_034](https://user-images.githubusercontent.com/36253097/37243826-56018412-2445-11e8-9238-da04b851c410.jpg)

Wind of Insanity is a zealot ability that provides a sustained damaging knockback that allows you to use other abilities while it is active with the downside that you are rooted while it is active. While the tooltip states it does not grant immunities from the knockback, at Live it also ignored temporary immunities granted by other cc abilities previously used on them. Only morale abilities and Resolute Defense granted immunity to the Wind of Insanity continuous knockback effect.

It was possible at Live to jump into the middle of a massive warband on warband fray, activate this ability and knock everyone around with perhaps only 1 or 2 people being immune because of a morale ability or Resolute Defense. At present when using this ability there will frequently be melee dps and tanks immune to the ability because of granted timed immunity from previous cc. This makes the self rooting effect of Wind of Insanity now somewhat suicidal and negates a lot of the reason for this ability to exist. It was basically a guaranteed 6 second melee dps shield for a cloth wearing caster.

Screenshots/Videos or archive.org evidences:

In this video of the DPS Zealot Obran, starting at about 2:42 you will see a dwarf player gets knocked down and just as he stands up Obran activates Wind of Insanity and it knocks him back despite his temporary cc immunity.

https://www.youtube.com/watch?v=cmVj7Ps1j_s

**Comment by Torquemadra** [comment]
It doesnt grant immunities but it respects them, knock down gives unstoppable immunity not immovable which is the one winds respects.

**Comment by Laurentz18** [comment]
Maybe something else has changed, but Wind of Insanity quite simply is not performing like it did at Live. I will continue to look for evidence.
