### ISSUE TITLE
Crashing after activating abilities..

### ISSUE THREAD

**Issue by ferraz19** [WarEmu/WarBugs#11443]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

I'm crashing repeatedly after casting a few abilities

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=20075
