### ISSUE TITLE
Reduced HP in T2

### ISSUE THREAD

**Issue by CeeJay89** [WarEmu/WarBugs#11442]
Expected behavior and actual behavior: I should have my max HP...however, in T2, many times I'll have less than max HP that fluctuates without any debuffs or for any given reason.  As you can see from the screenshot, I have 816 wounds, however, my HP is only 7620 instead of the usual 8160.

This is not the first character I've had this issue on. I have video evidence of it sticking for no apparent reason if necessary, however, the screenshot sums up what I mean. I'm not sure this is intended. IF it's intended, and I'm just missing something, I apologize.

Steps to reproduce the problem: It just happens, and it sticks. No idea how to fix or keep doing it.

Screenshots/Videos or archive.org evidences: 
![pici_007](https://user-images.githubusercontent.com/25260106/37250618-cc168524-24ce-11e8-8f57-39e35f342f33.jpg)

**Comment by sioding** [comment]
Thanks for the report. Can we please get a screenshot with the ".getstats"command instead of the paperdoll thing? It´s also kinda hard to reproduce a problem without any hint how it happend to you.

**Comment by CeeJay89** [comment]
I figured it out. It's the Diminishing Rations debuff. Happens even in T4. I don't know what triggers that debuff, but is the HP debuff it gives intended?

**Comment by CeeJay89** [comment]
Just to show it. That icon isn't for AAO, it's for Diminishing Rations. The other one isn't a wounds debuff, it's the Quitter! debuff.

In one screenshot it's a 500 HP debuff, another is a 1000 HP debuff, and the other is a 1500 debuff. I keep forgetting to get a .getstats, but it's definitely less HP because I most certainly die when I hit 0. My Wounds are 8100. The moment diminishing rations disappears, I get my HP back.

![pici_013](https://user-images.githubusercontent.com/25260106/37444985-50397428-27eb-11e8-914a-df8693f04727.jpg)
![pici_012](https://user-images.githubusercontent.com/25260106/37444986-52b00c80-27eb-11e8-9543-96c0a6947a9d.jpg)
![pici_011](https://user-images.githubusercontent.com/25260106/37444988-54e01a90-27eb-11e8-9dcb-a2017de08f99.jpg)

**Comment by sioding** [comment]
OK you found the reason on your own. Diminishing rations is a wounds and stats debuff to your realm. It occurs when you do not hold enough Battle Field objectives and is designed to pushing turtle play.
