### ISSUE TITLE
[PQ] Reaper's Circle last stage bug

### ISSUE THREAD

**Issue by simonborg92** [WarEmu/WarBugs#11444]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

PQ to register slaying Kraunel the Reaper on the last part of PQ. It does not register after several tries and relogs.

Steps to reproduce the problem:

Get to Stage 3 of the Reaper's Circle PQ.

Screenshots/Videos or archive.org evidences:

Had already left and thought of registering the bug on the way back to town, so no SS.

**Comment by Lheana** [comment]
The problem must be that Kraunel is making an aoe that affects the vultures around. Thus vultures must have the kill, and not you.
