### ISSUE TITLE
Erupting Blast Potion proccs and damage

### ISSUE THREAD

**Issue by Pumatouch** [WarEmu/WarBugs#11441]
_Expected behavior and actual behavior:_

Erupting Potions, which works a little like Engi Napalm, has a higher damage output than tooltips list. 
Furthermore, every tick of damage is not a dot-tick; it counts as a direct hit, **so all your Beastlord/Domi/Conq/Subjugator Weapon proccs** will go off on all targets in the area.
In the case of Subjugator Weapon proccs, it goes off no matter the distance. Every burn-tick is simply counted as a direct hit, with all the consequences that comes with that in terms of proccs.

It is speculated that certain speccs that accomodate direct hit proccs might also be affected, getting free proccs. 

_Steps to reproduce the problem:_

Have a tank bunch up some mobs/players. Throw Lasting Erupting Blast Potion into the crowd and step back. Watch all your proccs go off on the victims, even at a distance.

_Screenshots/Videos or archive.org evidences:_

![blastpot](https://user-images.githubusercontent.com/16616998/37249307-76e2c29a-24e5-11e8-94d3-ff677139a9d5.png)

![subaxe](https://user-images.githubusercontent.com/16616998/37249309-809e3d46-24e5-11e8-92af-597363a2e0c5.png)

Below here seen not frontally engaging the mobs, hence no melee hits. The Concussion proccs stem from the burn-ticks.
![binbam](https://user-images.githubusercontent.com/16616998/37249311-903a765c-24e5-11e8-9b9a-f67e9e83a169.png)

(Aware that tooltips might not be correct, hence the damage discrepancy.)

**Comment by thorbolt80** [comment]
it's the auto attack not?

**Comment by Pumatouch** [comment]
It is not. You will see no auto attack in the log around that procc. I shall have someone else tank, and do it from a ranged toon then.

**Comment by wargrimnir** [comment]
2 years later :0

**Comment by Kaelang** [comment]
As of 29/04/2020 this should now be fixed. Please re-open if issues persist.
