### ISSUE TITLE
[quest] inevitable power

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#11446]
I was going to do step 3 which requires killing "Savage Flesh Hounds" and "Savage Bloodletter" but when i reached the prescripted spot such mobs were not in place; seems that they pop up when pq "Tempest horn" enters step 2. Is this a side effect of "Mayhem" (?) armor set farming ?

**Comment by sioding** [comment]
Sorry but this is no bug report. I have checked quest und public quest. YES - you need to go into step 2 to kill the npc´s you need for the epic quest.

**Comment by zak68** [comment]
Can u put me back to step 2 of inevitable power quest ?
