### ISSUE TITLE
set wb/party note have no effect

### ISSUE THREAD

**Issue by jonyjones** [WarEmu/WarBugs#11448]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: type /partynote /warbandnote with a message when you are leader should set note. Nothing happen.

Steps to reproduce the problem: Create party/wb type and see nothing happen

Screenshots/Videos or archive.org evidences: No party or wb with note, vocal chat need this

**Comment by MaxHayman** [comment]
This is implemented.
