### ISSUE TITLE
Returning from scenario, lost progress

### ISSUE THREAD

**Issue by ErikWPotter** [WarEmu/WarBugs#11450]
Expected behavior and actual behavior:

When I return from a completed scenario, I expect to return to the location I started from with all of my major character states intact. Instead, having just picked up the quest "Balance" and having completed 2/2 of "Kill Covetous Bladebearer", I was called to a queued scenario (Logrin's Forge). So I stood in a safe place and entered the scenario. After completion I was returned to the safe place I left from...but with no quest credit...and actually with the quest missing from my tome. My safe state contained my location (not anywhere along the path I had taken to get to the quest giver, but instead right where I was when I entered the scenario), but at least a minute+ of pve progress (accepting a quest and completing all quest progress) was not saved.

Steps to reproduce the problem:

Presumably, do something you can verifiably accomplish in PvE (like take and/or make progress on a quest). Then very soon after enter a scenario. Complete the scenario. Check to see if that progress is lost.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Could you please remove ALL quests you have accepted and start with a fresh ONE quest - to make sure it happens again?

**Comment by ErikWPotter** [comment]
Wow. I've got over 45 quests on me right now. I'm running through every quest I can find Order side so I've got quests across three realms and the capitol city. Relocating all of those would require wandering through about 12+ zones. I've even got quests that I found far off the roads that I'd likely miss. I'd have fewer but I'm trying to hold on to the bugged quests that I've reported too.

That's a lot of time.

**Comment by wargrimnir** [comment]
Having a large amount of quests has been known to cause issues.

**Comment by ErikWPotter** [comment]
I'm not surprised. Seems like it may be an issue with the server not getting around to completing the database write before something like a copy of my character to a different instance/server/process or something grabs an old database copy which then get treated as current. Just a guess.

**Comment by sioding** [comment]
You maybe right - or not - but back to my question: Did you removed all quests - start with ONE again and are you discovering the same issues? I know its kinda hard to get all these quests again - but we need you to test such things to make the server better.

**Comment by sioding** [comment]
No answer since 13 days. close
