### ISSUE TITLE
Quest - An Evil Crop

### ISSUE THREAD

**Issue by swilkers808** [WarEmu/WarBugs#11455]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Kill 5 Uthorin Ebonshade - complete quest
I have killed at least 10 of these and the quest is failing to register the kills.

Steps to reproduce the problem:
Take quest  and kill some Uthorin Ebonshade
![2018-03-14 18_44_17-warhammer_ age of reckoning version 1 4 8 copyright 2001-2012 electronic arts](https://user-images.githubusercontent.com/5131136/37439950-ba0be5b8-27b7-11e8-9995-80ec2ddc25a9.png)

Screenshots/Videos or archive.org evidences:

**Comment by Lheana** [comment]
The NPCs you show on your ss are Uthorin Ebonblade and not Ebonshade.

**Comment by sioding** [comment]
So i´ll set it to fixed/closed.
