### ISSUE TITLE
Spike and Gas squig now attack at melee range

### ISSUE THREAD

**Issue by Harnag** [WarEmu/WarBugs#1145]
after last patch, the spike and gas squig now run to the target to attack them at melee range, instead of firing from 100ft range.  Spike and Gas squig should only run close enough to target to get within 100 ft range.  This worked properly before last patch.

**Comment by dalgrimar** [comment]
Very annoying idd!
Cant keep my spiked squig alive for more than 5 seconds...

**Comment by Harnag** [comment]
This now appears fixed
