### ISSUE TITLE
Armor Debuffs on SW/SH with assault stance or gaz squig

### ISSUE THREAD

**Issue by Kohagen** [WarEmu/WarBugs#11457]
Expected behavior : 
       
Armor buffs are applied after the bonus of assault stance /gazs quig and debuffs should work 
       symetricaly.

       example : 
               total armor from items = 1600
               armor from pot =600
               Actual armor with assault stance/gaz squig = 1600 x 2 + 600 = 3800
              when debuffed by 1600 it should be = 3600 - 1600 = 2200
 
and actual behavior:

         armor debuffs are currently lowering the armor from items not the actual armor of the 
         character.

        Following the previous example:
              armor from items = 1600 - 1600 armor debuff = 0
              actual armor with assault stance/gaz squig = 0 x 2 + 600 armor pot = 600

Steps to reproduce the problem:
easily reproduced
.getstats when armor debuffed

**Comment by sioding** [comment]
Can we please see your testing screenshots?

**Comment by cimator** [comment]
Here is my test result with 841 armor debuff;
![kuzgun_016](https://user-images.githubusercontent.com/17130290/37526864-8b4b6060-2941-11e8-8a57-f8e8d41435ad.jpg)
It seems to be working fine, armor goes from 3946 to 3105

**Comment by Kohagen** [comment]
Well, I failed in reproducing what I saw last time.
As cimator did, I tested on my SW with BG armor debuff it worked properly and tried also on my SH it worked fine aswell with engie turret debuff and lion pet debuff.

I did not see any moral debuff at that time. The gaz squig might have died just before I used .getsats... and I didn't notice.
I'll keep on testing then and see if some armor debuffs stacks (apart of tank M1 and engi M3).

**Comment by Kohagen** [comment]
Well, I just found what probably occured : 

with the SH = get squig gaz and then take a portal in RvR to some BO, not to far...
after some time then gaz squig will reach you and behave as usual but no armor buff...
this is a small bug that can be settled by spawning a new gaz squig after any portal.
![kikass_005](https://user-images.githubusercontent.com/21983403/37941565-c5056d7a-313c-11e8-8771-a6f23cf6345d.jpg)
![kikass_006](https://user-images.githubusercontent.com/21983403/37941592-f3183076-313c-11e8-8854-8874643bb88e.jpg)

**Comment by Kohagen** [comment]
It seems to happen with posterns, just tested on High Pass postern. I took postern and the pet buff disappeared

**Comment by grunbag** [comment]
This has been fixed already
