### ISSUE TITLE
Quest: The Glory of Ulthuan

### ISSUE THREAD

**Issue by ErikWPotter** [WarEmu/WarBugs#11453]
On the step with the tasks: "Find Starwillow Root 4/4", "Find Valeflower 4/4", Find Wildbrush 1/1"...

There is a map tracker centered around 45k, 47k for Valeflowers, there are none there though I did find Wildbrush.

The map tracker for Starwillows around 53k, 52k however is where both Starwillows and Valeflowers can be found, as well as wildbrush.

There is no map tracker for Wildbrush.

**Comment by sioding** [comment]
To be honest - the two given Questmarker were set fine. I removed the two markers and created a new one. All three questobjects can be found inside the area of the mark. 
That means - not fixed cause it was OK before - but changed to make it easier with the next patch.

**Comment by sioding** [comment]
.Fixed with patch from .17.03.2018
