### ISSUE TITLE
Quest: "Army of the Fallen" Incorrect/Extra Map Marker

### ISSUE THREAD

**Issue by ErikWPotter** [WarEmu/WarBugs#11451]
The "Army of the Fallen" quest step "Speak with Forellion Lightbringer" has two map trackers. There is a red seal at about 62k 39k that marks the correct location.

There is also a false red lake marker near 43k, 25k.

**Comment by sioding** [comment]
Thanks for the report. Fixed with next patch

**Comment by sioding** [comment]
.Fixed with patch from .17.03.2018
