### ISSUE TITLE
Bug quest - The black forest 

### ISSUE THREAD

**Issue by Lethandrius** [WarEmu/WarBugs#11459]
There is a quest called - The Black Forest - (Empire Chapter 4). 

The player needs to recover a chest full with black powder but the chest is not at the quest spot in the map.
There must be a chest (object) that must be clicked to get the objective done.

**Comment by ErikWPotter** [comment]
I confirm. I've completed this multiple times before always finding the chest easily. Now its gone. Ive searched the entire map tracker area and everything nearby...particularly the camps and tents.

**Comment by sioding** [comment]
![image](https://user-images.githubusercontent.com/18517842/37566278-43df70f0-2ab7-11e8-8fd3-cb5a0720c5df.png)
The chest is back with the next patch

**Comment by sioding** [comment]
Fixed with Hotfix from 18.03.2018
