### ISSUE TITLE
Tok summoned mount 1000 times while unarmored blue text show 100 times

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11465]
The blue text inside the log (bottom corner left of the screen) show 100 times instead of 1000 time
![image1](https://user-images.githubusercontent.com/16274785/37557085-a5480cfc-29ff-11e8-8a52-bfabc04c47a9.png)

**Comment by Natherul** [comment]
will be fixed in the next patch, entry in DB is wrong

**Comment by Natherul** [comment]
should be fixed as of today
