### ISSUE TITLE
Tok. Entered water unarmored 10 times don't work

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11468]
Natherul said : "he should be deep water" so I tried 10 times crossing the sea from south to north barack varr. No unlock.

**Comment by Natherul** [comment]
fixed next patch, I forgot to clear in a good way when you exited water, right now it only clears if you exit from lava :P

**Comment by Natherul** [comment]
oh and to clarify for later, to get this to count you need to go into deep water so your character gets dismounted and is swimming and then go all the way to solid ground for it to count once and reset if your in water or not.

**Comment by Natherul** [comment]
should be fixed as of today

**Comment by thorbolt80** [comment]
Really thank you for your answer !


________________________________
De : Mark Jack Sundahl <notifications@github.com>
Envoyé : dimanche 18 mars 2018 07:51
À : WarEmu/WarBugs
Cc : thorbolt80; Author
Objet : Re: [WarEmu/WarBugs] Tok. Entered water unarmored 10 times don't work (#11468)


oh and to clarify for later, to get this to count you need to go into deep water so your character gets dismounted and is swimming and then go all the way to solid ground for it to count once and reset if your in water or not.
