### ISSUE TITLE
Tok unlock talked to 1000 citizens while unarmored trigger in the same time talked to 10 000 citizens while unarmored

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11463]
![thorbolt_134](https://user-images.githubusercontent.com/16274785/37552227-49cb210a-29b1-11e8-93e2-53e3517d62bd.jpg)

**Comment by Natherul** [comment]
will be fixed on next patch, I missed a zero

**Comment by Natherul** [comment]
should be fixed as of today
