### ISSUE TITLE
Quest: "spotting trouble" Altdorf.  Ruffian's don't turn hostile so you can't finish the quest

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11461]
Stage : you have to kill bernfrieds's  ruffiian 0/2

The ruffian don't turn hostile so you can't finish the quest
![thorbolt_132](https://user-images.githubusercontent.com/16274785/37552093-5a60ca18-29ae-11e8-8994-4c95f6a28c50.jpg)

**Comment by sioding** [comment]
![image](https://user-images.githubusercontent.com/18517842/37566112-c7c9c4b8-2ab4-11e8-802b-ef894c07ae58.png)
fixed with next patch

**Comment by sioding** [comment]
Fixed with Hotfix from 18.03.2018
