### ISSUE TITLE
Sacking for sacs

### ISSUE THREAD

**Issue by swilkers808** [WarEmu/WarBugs#11460]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Sacking for sacs - Obtain 5 venom sacs and deliver to librarians. 
Obtain pocket item of Vial of concentrated venom
Recieve Tome unlock and Crow Caller Chain
I did not receive the unlock or chain. 

Steps to reproduce the problem:
Perform steps above

Screenshots/Videos or archive.org evidences:

![2018-03-16 21_01_02-warhammer_ age of reckoning version 1 4 8 copyright 2001-2012 electronic arts](https://user-images.githubusercontent.com/5131136/37551462-2ad053d2-295d-11e8-8fb2-a395729ad7df.png)

**Comment by Lheana** [comment]
Screenshot of the ToK page of Giant Spiders please

**Comment by swilkers808** [comment]
![2018-03-17 14_51_03-warhammer_ age of reckoning version 1 4 8 copyright 2001-2012 electronic arts](https://user-images.githubusercontent.com/5131136/37560285-afa4d002-29f2-11e8-9698-2c187b11b0fd.png)

**Comment by Lheana** [comment]
Which proves you have the unlock, you just have to talk to the correct merchant in Library to have your jewel if you wanna have it. Once again, when a ToK unlock has a jewel as reward, you have to buy it.
