### ISSUE TITLE
Buy back items that sold in stacks

### ISSUE THREAD

**Issue by NervZ** [WarEmu/WarBugs#1146]
I dont know if this is already reported but if you sell a stack of an item and then you try to buy it back you can see the x number of the stack (x) however when you buy back you buy just one

**Comment by Tyramissoux** [comment]
Seen that too.

**Comment by Evildoor** [comment]
According to this:
http://www.returnofreckoning.com/forum/viewtopic.php?f=2&t=5787
this was fixed. Closing.
