### ISSUE TITLE
[NPC] Keep Lord

### ISSUE THREAD

**Issue by Haojun-Phalanx** [WarEmu/WarBugs#11469]
There are 2 issues with keep lord.

1- Healers getting aggro super easy, it's open for griefing.
2- WL pets getting aggro a lot.

PS: Bolstered healers/players might have more aggro than the others -can't confirm it- . 

https://www.youtube.com/watch?v=DubDoRaZBAY

**Comment by sioding** [comment]
No changes to the Lord - so - working as intended.

**Comment by Haojun-Phalanx** [comment]
Is it ok to reset keep lord with/without knowing it ? It's really dumb to trying keep lord like 30-40 minutes+ while some people keep resetting it with/without knowing it.

**Comment by sioding** [comment]
This is not the forum. Thread locked.
