### ISSUE TITLE
Quest: "new allies, new enemies" Altdorf.

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11462]
There is no questmarker on the map.
![thorbolt_133](https://user-images.githubusercontent.com/16274785/37552107-aec72a02-29ae-11e8-90ff-e982b57883df.jpg)

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=25909
