### ISSUE TITLE
"The Blooded"

### ISSUE THREAD

**Issue by Squea** [WarEmu/WarBugs#11464]
Character: Fey Rank 28 Archmage

Today in the Gates of Ekrund Scenario I killed a DoK and unlocked, "The Lucky," title after killing ten players in RvR. Simultaneously the titles, "The Mauler," and, "The Blooded," unlocked as well corresponding to 100 and 1000 kills respectively. I'm not sure if these screenshots uploaded properly, I'm not savvy.

![fey_010](https://user-images.githubusercontent.com/16263277/37552743-cb4287d8-2988-11e8-9a39-513e50f7527f.jpg)
![fey_009](https://user-images.githubusercontent.com/16263277/37552746-d8965568-2988-11e8-8a80-95bb683e999d.jpg)

**Comment by Squea** [comment]
This one is going around. Domoarigobbo got, "The Psychopath title.
![domoarigobbo_124](https://user-images.githubusercontent.com/16263277/37553447-6f29bcf6-2996-11e8-82ac-61e1ac22dc94.jpg)

**Comment by sioding** [comment]
@Squea thats fine. I had the same. My tome shows this:
![image](https://user-images.githubusercontent.com/18517842/37554874-481082be-29df-11e8-8092-7ebb87b79612.png)
And i got the Lucky/The Mauler/The Blodded after my fist kill caus i already have more than 1000 rvr kills - so you get the lower titles as well as the higer one with the fist kill you did cause you already deserve them. The count doesn´t start with the latest patch.
