### ISSUE TITLE
glitch issue

### ISSUE THREAD

**Issue by rycko2b** [WarEmu/WarBugs#11474]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
 a player from Destruction (as many times ) is using a glitch to get  on spot where you can't get  . 
it's at Cemetery Scenario, he gets athe top of a pillar in crypt [Flag](   [)](
)

[](url)

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by wargrimnir** [comment]
If by glitch, you mean jumping, then it's not a glitch. Demonstrate otherwise.

**Comment by rycko2b** [comment]
Hello,

Sorry about the late answer. Well i don’t know if you can really jump up there (screenshot attached), anyways we tried with another guy to get up there, jumping on tomb, even with mounts. Couldn’t reach the top of pillar.
So I dunno if it’s a glitch, or if he’s pro at jumping, was wondering and it could help if thats a bug/glitch.

I also had another bug to report, but I remember you can’t do anything about « holes » in textures. I died of fall damage  while walking a a middle ramp in Gates of Ekrund scenario. Can’t find screenshot for that one sorry.

Best reguards.


Eric
________________________________
De : wargrimnir <notifications@github.com>
Envoyé : Monday, March 19, 2018 2:28:11 AM
À : WarEmu/WarBugs
Cc : rycko2b; Author
Objet : Re: [WarEmu/WarBugs] glitch issue (#11474)


If by glitch, you mean jumping, then it's not a glitch. Demonstrate otherwise.

**Comment by wargrimnir** [comment]
This did not attach a screenshot...

**Comment by rycko2b** [comment]
Hello, here it is. Had a latency sending mail, French ISP…


________________________________
De : wargrimnir <notifications@github.com>
Envoyé : Wednesday, March 21, 2018 1:06:03 AM
À : WarEmu/WarBugs
Cc : rycko2b; Author
Objet : Re: [WarEmu/WarBugs] glitch issue (#11474)


This did not attach a screenshot...

**Comment by sioding** [comment]
Mails with attachments do not work at all. If you want to add an attachement to the report you have to do it on the github website.

**Comment by rycko2b** [comment]
![babadoooks](https://user-images.githubusercontent.com/26632001/37861284-24f15f62-2f37-11e8-853d-c927e1e513d5.png)

there it is.

**Comment by wargrimnir** [comment]
That's what I thought. You can easily jump up there.
