### ISSUE TITLE
item

### ISSUE THREAD

**Issue by lijebin** [WarEmu/WarBugs#11472]
![winford_000](https://user-images.githubusercontent.com/17027595/37565230-2d4a59e4-2ae0-11e8-8ce2-152e13fc9143.jpg)
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by lijebin** [comment]
sorry what does this do

**Comment by sioding** [comment]
The bugtracker is not your /advice. If you have any questions please use the /advice channel ingame or the forum. Sorry but here are only ingame bugs handled.
