### ISSUE TITLE
[ORDER] Welcome Back: Brotherhood

### ISSUE THREAD

**Issue by VoxelBase** [WarEmu/WarBugs#11470]
Expected behavior and actual behavior: Supposed to grab a crate of cannonballs on the order side of the Gates of Ekrund, however, it's tagging an actual cannon as the quest objective and clicking on it just lets you use it like any other cannon and doesn't complete the quest. 

Steps to reproduce the problem: Simply going to the quest objective location will show the issue. I checked every inch of that side of the wall and there are no other clickable item as far as I can see. 

Screenshots/Videos or archive.org evidences: 
![ellar_001](https://user-images.githubusercontent.com/37499667/37564705-8a0bcd08-2a58-11e8-99b9-3e8250bad5f2.jpg)

**Comment by sioding** [comment]
Hm - also the order side quest is fine:
![image](https://user-images.githubusercontent.com/18517842/37565620-ce54a486-2aac-11e8-8bbf-271d63c66590.png)
All whats missing is a fine questmarker which i´ve added now. So - you can find the crate of cannonballs...

**Comment by sioding** [comment]
Fixed with Hotfix from 18.03.2018

**Comment by gittoaster** [comment]
It seems the map marker is missing again, it shows just an arrow in the Ekrund zone, but nothing in Mt Bloodhorn.
