### ISSUE TITLE
Dark Elves T2 Epic Quest ''A Lords' Game'' Stop at the Griffon Gate Part

### ISSUE THREAD

**Issue by Pearlpetalbee** [WarEmu/WarBugs#11484]
Dark Elves T2 Epic Quest A Lords' Game. Stop at the Griffon Gate Part where it requires to kill 10 Griffon Guards and 10 Griffon Defenders at location 7K, 61K Shadowlands. However there is no Guards and no Defenders. The location having a Public Quest "The Griffon Gate" also is bugged as the first stage there is no Eagle Claws Bolt Throwers to be destroyed. 

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
I have checked that on our dev server and its completely fine. PQ is up and the correct NPC´s are also inside. We know the problem with PQ´s not loading - but do not know how to fix it yet. You just need to wait for a server restart. sorry.
