### ISSUE TITLE
burn armor problem

### ISSUE THREAD

**Issue by knocknocks** [WarEmu/WarBugs#11485]
its was test burn armor debuff . WH use burn armor and me use wrecking balls for some mobs . look damage per second from burn armor debuff 
 https://s18.postimg.org/3zexrbysp/Knocknock_040.jpg
i take dmge from burn armor everytime my wrecking balls shoot from each target . Calc  if burn armor shoot 200 dmge and i use wrecking balls from party enemys 6 strike * 200 * 6(target) = 7200 dmge by 3 sec   take back.

**Comment by sioding** [comment]
Sounds fine for me. If you had the burn armor debuff you better do not any aoe spells. So - what kind of bug whould you like to report? For now its working as intended for me.

**Comment by roadkillrobin** [comment]
Looking at the wording of the skill, it isn't connected to hits at all. "Use a melee skill". 
It should only trigger once of a skill activation. 

If it was connected to hits it would also trigger on AA's which it doesn't.

**Comment by sioding** [comment]
Nope sorry - its not "use a melee skill" its "melee attack"... that includes a auto attack cause this is a melee attack.

**Comment by roadkillrobin** [comment]
The mechanic of how the skill function in the game right now is, " ... whenever they deal damage to a enemy target with a melee attack. Coz it doesn't proc when you parry/block it. It's not what the tooltip says.

**Comment by knocknocks** [comment]
**Sounds fine for me. If you had the burn armor debuff you better do not any aoe spells. So - what kind of bug whould you like to report? For now its working as intended for me.** 

ok if use FLAIL i take 2 dmge  from debuff coz 2 melee attack 
and if i have 2 debuff burn armor i take dmge from 2 debuff  . 

its not correct .  i remember when nerf chosen aura  backslash magic .

**Comment by sioding** [comment]
This is not the forum and i don´t want to discuss here with two people. If you want to discuss things - you are welcome to do that in our forum. Sorry @roadkillrobin. Back to @knocknocks. I don´t get your last comment. Please add screens which would (maybe) help to understand you.

**Comment by knocknocks** [comment]
2 wh 2 debuff ))

https://s31.postimg.org/ky8xeuytn/Knocknock_045.jpg

**Comment by sioding** [comment]
I still think everything is fine but there is enough evidence now to let it through. Maybe Torq can say if its intended or not. For now: Thanks for the report.

**Comment by Toldavf** [comment]
https://github.com/WarEmu/WarBugs/issues/1772 touch of rot used to do something similar. It was easy to bring down a target using any aoe with it before it was fixed.

**Comment by Shemrock3267** [comment]
Got the same issue.
I can attach my 5 screenshots where i died in 3 seconds, just by **hitting** random targets with wrecking ball, though i **used it only once**.

**Comment by Shemrock3267** [comment]
Screenshots from September action
![shoom_019](https://user-images.githubusercontent.com/10697124/47222986-c8274b00-d3c0-11e8-85be-f4ae427e99f6.jpg)
![shoom_020](https://user-images.githubusercontent.com/10697124/47223001-cfe6ef80-d3c0-11e8-84cf-0053586644c5.jpg)
![shoom_021](https://user-images.githubusercontent.com/10697124/47223011-d4aba380-d3c0-11e8-8400-8100046be5f6.jpg)
![shoom_022](https://user-images.githubusercontent.com/10697124/47223023-d83f2a80-d3c0-11e8-9bd1-98cb358fe8fb.jpg)
![shoom_023](https://user-images.githubusercontent.com/10697124/47223028-dbd2b180-d3c0-11e8-8087-a5ef6d6fc2f9.jpg)
![shoom_024](https://user-images.githubusercontent.com/10697124/47223036-e1c89280-d3c0-11e8-8ac5-f89685fb0129.jpg)

**Comment by Shemrock3267** [comment]
Screenshots from today.
Fix this already, pls.
![eilen_000](https://user-images.githubusercontent.com/10697124/47223077-058bd880-d3c1-11e8-9c52-82715b190a71.jpg)
![eilen_001](https://user-images.githubusercontent.com/10697124/47223085-09b7f600-d3c1-11e8-9ead-69b735bb4288.jpg)
![eilen_002](https://user-images.githubusercontent.com/10697124/47223094-0d4b7d00-d3c1-11e8-9b2c-fd22279ce207.jpg)
![eilen_003](https://user-images.githubusercontent.com/10697124/47223099-0fadd700-d3c1-11e8-9e4f-a3cbceeaaacb.jpg)
![eilen_004](https://user-images.githubusercontent.com/10697124/47223107-12103100-d3c1-11e8-9a5d-81d6fbd31d8b.jpg)
![eilen_005](https://user-images.githubusercontent.com/10697124/47223123-1c322f80-d3c1-11e8-929f-5b0b4c74b24d.jpg)

**Comment by Shemrock3267** [comment]
Debuff (Burn Armour) counts as a use of melee ability as not clicking a button (Wrecking Ball ex.), but for dealing melee dmg.

**Comment by grunbag** [comment]
Fixed already
