### ISSUE TITLE
siege engine and minimap problem

### ISSUE THREAD

**Issue by asdf92** [WarEmu/WarBugs#11488]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:While in a siege engine in battle for praag I could not see red dots on the mini map, I thought u would be able to see red dots on the minimap

Steps to reproduce the problem:hop in a siege wep in a sc specifically in battle for praag

Screenshots/Videos or archive.org evidences:
https://imgur.com/a/HFZGg

**Comment by sioding** [comment]
You thought you would be able to see red dots? That means you think you can see the enemies as red dots on the mini map to aim better?
Since when sould this work? Did it on live? Have you any proof for it?

**Comment by wargrimnir** [comment]
This was a feature from the Skaven Assassin class that was on live. It was briefly on RoR and was later removed. We do not plan to re-implement it.
