### ISSUE TITLE
NPC: Caged Prisoner: Norsca

### ISSUE THREAD

**Issue by Squea** [WarEmu/WarBugs#11481]
NPC: Caged Prisoner, level  9
Location: Norsca, 59k, 39k

These are some accessory mobs in a small camp of Norse Raiders, it is not affiliated with a PQ. They are captive NPCs ostensibly captured by the raiders and put in cages. They have no name associated with the NPC. They can be damaged by aoe abilities, and when they aggro you cannot tab-target these Caged Prisoner mobs. However when attacked, if you have no target you can then use single-target damage abilities on the mob. They cannot be looted/scavenged although they do have the slight glow that indicates they have a loot table.

Go to: 59k,39k in Norsca with a player character that has aoe damage abilities and attempt to aggro the Caged Prisoners there.
![aquataco_001](https://user-images.githubusercontent.com/16263277/37622214-1b4b99f6-2b8f-11e8-8f05-64245ee7ab5f.jpg)

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=25909
