### ISSUE TITLE
Warped Flesh - Ritual of Superiority doesn't absorb Autoattacks

### ISSUE THREAD

**Issue by roadkillrobin** [WarEmu/WarBugs#11482]
I was doing some PVE farming and noticing that i took alot of damage even tho running both the tactic and Ritual. I checked the damage log and noticed this.

![numenon_034](https://user-images.githubusercontent.com/16356956/37682754-b1bc389a-2c8a-11e8-9c9c-2b8b989ebed9.jpg)
![numenon_035](https://user-images.githubusercontent.com/16356956/37682755-b1e86df2-2c8a-11e8-828d-1497baf25c65.jpg)
![numenon_036](https://user-images.githubusercontent.com/16356956/37682757-b20bf420-2c8a-11e8-85f9-698dda26b70f.jpg)
![numenon_037](https://user-images.githubusercontent.com/16356956/37682758-b234d2f0-2c8a-11e8-9644-f8f0b22d39c1.jpg)

You can see 477 "Attacks" and 0 absorbs while other NPC skills being absorbed between 18-57% of damage.

**Comment by sioding** [comment]
Hm - i am not happy with weird addon statistics without any combat log. Maybe Natherul is fine with it - so i will let it through...

**Comment by roadkillrobin** [comment]
It's the Enemy combat log and it's been 100% accurate on everything else i've tested for. 

Im not even sure how many pages of the in game combat log would be required to show even hints of ressault of this. Probobly 30-40 pictures. 

I'll try to find some NPC's with just the attack skill and make a video of it in addition.

**Comment by roadkillrobin** [comment]
I tried this out with just AA NPC's and it's a bug with the enemy combat log. The attacks can be absorbed. You can close it
