### ISSUE TITLE
Dark Elf Chapter 13 PQ - Trial by Fire

### ISSUE THREAD

**Issue by Yvelfir** [WarEmu/WarBugs#11489]
No mobs are spawning so it is stuck at stage 1, preventing anyone from doing Honorable Deceit.

![yvelfir_000](https://user-images.githubusercontent.com/37705760/37839068-778cdd40-2eb1-11e8-8164-d660ca9145a7.jpg)

**Comment by sioding** [comment]
This is a known - but not fixable problem - you need to wait until server restart.
