### ISSUE TITLE
Block maybe parry too on black orc

### ISSUE THREAD

**Issue by bugreportingisnotworththeeffort** [WarEmu/WarBugs#1148]
Since the update I played some hours on my black orc and didn't block once, even with "Shield Wall".
My Chosen and my Black Guard are blocking and parrying normally.

**Comment by bugreportingisnotworththeeffort** [comment]
The SC shield seems to be the cause.

**Comment by Reggaewaldo** [comment]
Double-checked the DB and the item. This should be resolved.

Please reopen if issue still exists.
