### ISSUE TITLE
Magus skill Indigo fire of change keeps disappearing from the skill bar

### ISSUE THREAD

**Issue by effie138** [WarEmu/WarBugs#11480]
Recently I chose the skill Indigo fire of change from the path of changing tree. One hour later, I saw that it disappeared from my skill bar and the abilities tab. I went to IC a couple of times to take it again, but it keeps disappearing...

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format. 

You can help us by following these bugreport rules: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by cimator** [comment]
@effie138 If you get a +1 mastery point from gear, and if you arent able take that skill without that 1 extra point, its gonna reset whenever you change any item.

**Comment by sioding** [comment]
Thx @cimator
