### ISSUE TITLE
Mini map not working while in siege Properly

### ISSUE THREAD

**Issue by asdf92** [WarEmu/WarBugs#11486]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:show dots on minimap to help aim: it does not show dots on mini map

Steps to reproduce the problem: hop in a siege engine specifically in battle for praag

Screenshots/Videos or archive.org evidences:I will get back to this since my prnt screen didn't work but I did have a screenshot!

**Comment by sioding** [comment]
I don´t get what you would like to report sorry. Please invest some mote time to descibe the problem and add some helpful screenhots. Until this i will close this report.
