### ISSUE TITLE
Guild Vault Item Retrieval

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#11496]
I am an officer in Kar Khadath Regiment (GUILD:1864). This morning I've gone to our vault to clear some of the junk items in there to make way for some nice shinies. It let me remove one green talisman, but when I try to take anything else out, I get the message:

"Another member of your guild is currently moving that item."

They're not, there are only 3 of us online at the moment and I'm the only one at the vault.

I've tried /reloadui and also reloading the game, but this error still comes up.

After a couple of attempts this message won't even appear. 

I have also tried dragging the item out of the vault into my backpack, and tried from vault 2 and 3 tabs, with other items such as crafting items.

Expected behavior and actual behavior:

That the item will appear in my backpack when clicking on it to remove from the vault, or by dragging the item into my backpack from the vault.

Steps to reproduce the problem:

Unsure

Screenshots/Videos or archive.org evidences:
First pic shows clicking on item with message in chat box
![ithilsyn_111](https://user-images.githubusercontent.com/22262165/37862678-e74b7618-2f48-11e8-8cf8-0e40e71584ee.jpg)

Second image shows that an item can be dragged but won't drop into backpack
![ithilsyn_112](https://user-images.githubusercontent.com/22262165/37862679-f878d94e-2f48-11e8-84f6-4d65d272d38d.jpg)

**Comment by Senthoi** [comment]
A quick update, after half an hour I went back and tried again. It was working, no strange messages. I am not sure why it thought there were multiple people in the vault trying to take an item. 

Seems to have resolved itself.

**Comment by Natherul** [comment]
preliminary testing on our dev server have shown this as fixed, I will have more testing done but should be fixed at least before next weeks patch if not before

**Comment by Senthoi** [comment]
Awesome, thank you Natherul.

**Comment by Natherul** [comment]
fixed as of now
