### ISSUE TITLE
Hastened Doom bugged values

### ISSUE THREAD

**Issue by Playerhater** [WarEmu/WarBugs#11495]
After the patch today the blackguard tactic hastened doom applies a 324 wounds instead of 120 wounds and debuff lasts for 10 minutes instead of 10 seconds

**Comment by sioding** [comment]
Can we please see Screenshots?

**Comment by Playerhater** [comment]
![playerhater_001](https://user-images.githubusercontent.com/37733560/37862655-e347d75e-2f0d-11e8-8d19-b755fe422a0f.jpg)

**Comment by Playerhater** [comment]
Also the auto attack speed buff will apply tooltips multiple times, but it seems like the attack speed buff only applies one time for a 50% increase.

**Comment by sioding** [comment]
Thanks for the screens.

**Comment by Torquemadra** [comment]
works fine for me

**Comment by sioding** [comment]
No answer for 15 days. close
