### ISSUE TITLE
probelm with mastery

### ISSUE THREAD

**Issue by lijebin** [WarEmu/WarBugs#11497]
i click it but nothing happend 
![winford_001](https://user-images.githubusercontent.com/17027595/37863428-1572d40a-2f99-11e8-8275-6450daa025d4.jpg)
![Uploading Winford_002.jpg…]()
![Uploading Winford_003.jpg…]()
![Uploading Winford_004.jpg…]()

**Comment by lijebin** [comment]
![winford_002](https://user-images.githubusercontent.com/17027595/37863496-a19e70b0-2f99-11e8-895f-4bfe413bdbf1.jpg)

**Comment by lijebin** [comment]
![winford_003](https://user-images.githubusercontent.com/17027595/37863498-abd2ee94-2f99-11e8-825b-7b27abab757e.jpg)

**Comment by lijebin** [comment]
![winford_004](https://user-images.githubusercontent.com/17027595/37863500-b41b6978-2f99-11e8-9c61-aef563cdc5ad.jpg)

**Comment by sioding** [comment]
Please check the patchnotes. You have to go to the trainer.
