### ISSUE TITLE
ab changelist command WL is empty

### ISSUE THREAD

**Issue by DragonTank** [WarEmu/WarBugs#11498]
.ab changelist command doesn't work on white lions can we get a fix  on this since there are many changes to this class?

https://imgur.com/a/8Uq06

**Comment by sioding** [comment]
Best place for those informations is the wiki. But you are right - as long as we offer an ingame command - it should work.

**Comment by wargrimnir** [comment]
That looks like you have chat filtered. Turn on all the system chats and try again.

**Comment by DragonTank** [comment]
seems to work thanks Wargrim! also i dont know who updates the Wiki can we get a tooltip for the Stalker Tactic on what stats it really gives thanks.
