### ISSUE TITLE
Cultivation Soil,Watering Can, Nutrient does not work

### ISSUE THREAD

**Issue by ELWEYNBUNE** [WarEmu/WarBugs#11491]
Hello,

I bought cultivation materials from the Guild Hall Quartermaster NPC (Elisia Bloodraven) and they could not implemented in the cultivation process (the ingredients I bought were level 150), while materials bought from various craft merchants worked fine (of course those ingredients are only level 1). Also they could not be moved to the crafting inventory.

Thank you very much for your hard work.

Screenshots/Videos or archive.org evidences:
![crafting_004](https://user-images.githubusercontent.com/37719867/37857797-d1bdcc16-2f06-11e8-9d91-013146abcd82.jpg)

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
