### ISSUE TITLE
The "Poser" and "The Ogler" line of titles aren't bound to the correct action

### ISSUE THREAD

**Issue by bwdaWAR** [WarEmu/WarBugs#11493]
It seems that the action "Targeted an unarmored player x times" grants the  Poser for 100, Celebrity for 1000 and Emperor for 10000 despite that those [should be](https://wiki.returnofreckoning.com/index.php/Whacky#Casual) granted by "Been targeted, outside of combat, x times while unarmored". The "Been targeted, outside of combat, x times while unarmored" action (which I believe should count for "Been targeted x times while unarmored" too) doesn't grant any titles at all.

**Comment by Natherul** [comment]
correct you are, this will be fixed in the next patch. I was getting dizzy when coding this all and mixed some up :D

**Comment by Natherul** [comment]
fixed as of now
