### ISSUE TITLE
Set bonus issue with bonus spec points

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#11492]
. 

Expected behavior and actual behavior:
When you swap gear with +1 to mastery, even if you still meet the requirement for the bonus you lose it temporarily, causing you to potentially lose an ability. For example if you have the 13 point ability in a tree and no extra points above it you will lose that ability and then have a spare point.

With the latest patch making it so you have to visit a trainer to spend that point again it makes this bug a lot more of an issue.
The expected behavior is that if you retain the relevant bonus after swapping gear you should not lose the spec point and any associated ability. 

Steps to reproduce the problem:
Wear 5 pieces of for example Mercenary gear. Spec for 13 point ability in relevant tree with no additional points above. Then swap one piece of the set out, keeping 4 pieces for the bonus. 

Screenshots/Videos or archive.org evidences:

**Comment by wargrimnir** [comment]
https://github.com/WarEmu/WarBugs/issues/7024
