### ISSUE TITLE
[Talisman] Intel Tali and Sorcerer SC weapon not working properly

### ISSUE THREAD

**Issue by Cheewyz** [WarEmu/WarBugs#1149]
I have tested the Intelligence talisman on two items and on both of them, rather then giving +10 intelligence as it should it gives either 1 or 2. I also tested the +14 Intel which also didn't work correctly.

Below is an image of the staff not equipped showing you 401 intelligence and when the staff is equipped it should add up to 455 but it ends up at 447. (+2 int from tali)
![bug1](https://cloud.githubusercontent.com/assets/13965450/9471254/d517dc76-4b92-11e5-8755-e67fe179638e.png)

Below Is an image of gloves not equipped with an intelligence of 387 and then at the top with equipped where it should be 420 but its 411 (+1 int from tali).
![bug3](https://cloud.githubusercontent.com/assets/13965450/9471325/19c167c0-4b93-11e5-8f57-db62aa3194c8.png)

Finally The Sorcerer SC weapon slots seem to not work correctly, I am able to slot a talisman into the first slot but it will not let me use the second slot. All 2h SC weapons might have this problem but I was only able to check my own.
![bug2](https://cloud.githubusercontent.com/assets/13965450/9471397/6ec31066-4b93-11e5-9978-009ecfb86232.png)

**Comment by Zealote** [comment]
The +44 and +23 int on the staff and gloves respectively are the values with the tali added aren't they? If so, you've actually got +2 and +1 more than you should (issue with stat window, or effect of bolster maybe?).

Wrt the second issue, maybe the OP was trying to equip two int talis.

**Comment by Luth-RoR** [comment]
High likely a visual issue issue with the paperdoll stats in the window. Always use .getstats in the chatwindow to get an output of your real stats.
