### ISSUE TITLE
Dawn's Early Fight-Stage 1 The Shadowlands

### ISSUE THREAD

**Issue by Satios** [WarEmu/WarBugs#11502]
The public quest "Dawn's Early Fight-Stage 1" has forgotten to spawn the mobs necessary to advance the the quest, where there should be mobs.

As I have not completed the public quest before, I do not know what has caused it.

![satios_000](https://user-images.githubusercontent.com/37757412/37870283-64f8c17e-2f8f-11e8-8521-244cf9d4d47a.jpg)

![satios_001](https://user-images.githubusercontent.com/37757412/37870291-70ba2156-2f8f-11e8-97fc-82d6e6dc758e.jpg)

![satios_002](https://user-images.githubusercontent.com/37757412/37870292-77c1f6ea-2f8f-11e8-86b4-d8109ec2f975.jpg)

![satios_003](https://user-images.githubusercontent.com/37757412/37870294-810e833a-2f8f-11e8-8898-158a1d5badea.jpg)

**Comment by wargrimnir** [comment]
Sometimes if you're the first one approaching the PQ, you need to leave the area and go back into it for things to spawn. We don't preload all the PQ's in the game during the boot process.

**Comment by Satios** [comment]
As in leaving the entire zone, or just the public quest area?

**Comment by wargrimnir** [comment]
Just the quest area. Give it a couple seconds, then walk back in.

**Comment by Satios** [comment]
I'll try this when I log back in tomorrow, though I did try reentering without the few second delay with no avail.

**Comment by Lheana** [comment]
Same issue as #10862
The PQ tracker appears but NPCs don't spawn.
