### ISSUE TITLE
Cant create a guild

### ISSUE THREAD

**Issue by Grunbeast** [WarEmu/WarBugs#11509]
We were party of 6, I had 70 gold in bags, no one was a member of another guild. NPC told me that all requirements have been met. After I pressed create a guild button nothing happening. No messages for party members, no error messages for me.

**Comment by Natherul** [comment]
without any additional information this is impossible to track down, make sure that the person trying to get the guild signed dont filter out any error messages as there are a few ways it could fail and it should be noted in those. (gray messages if using standard settings).

**Comment by Grunbeast** [comment]
I enabled system messages. Its working since if im trying to register a guild with names of existing ones or unallowed names it says that this name is not available. Party member does not receive any errors as well.
We are party of 6 staying near npc in IC, I have 70 gold in backpack.

**Comment by Natherul** [comment]
Due to catching the errors on the server as you did it I could track it down. Next time please add more informatoin like what guild name, time and so on as without that or sheer luck we wont be able to find any information.

Either way this should be resolved with next update

**Comment by Grunbeast** [comment]
Thank you for response. I will add time line in such bug reports next time.

**Comment by sioding** [comment]
fixed with patch from 31.03.2018
