### ISSUE TITLE
No bagspace when trade - item dissapears

### ISSUE THREAD

**Issue by vaishiyas** [WarEmu/WarBugs#11507]
Expected behavior:
Trade not getting validated because of lack of space.

actual behavior: 
Trade is "successful", items that exceed the bag size limit are removed from the person that trades the item and the reciever won't get these items.

Steps to reproduce the problem:
1) Have a full inventory 
2) Have someone else trade you an item. 
3) The traded item will now be gone from the trader's inventory and will not be in your inventory

**Comment by sioding** [comment]
fixed with patch from 17.11.2018
