### ISSUE TITLE
Tok : Title not working : Targeted an unarmored player 100 times	Title: The Ogler

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11511]
Natherul fix the title "the poser" see #11493

but The title "The ogler" same issue see #11493 isn't working. 

(Targeted an unarmored player 100 times) | Title: The Ogler, XP: 66

I just try it

**Comment by Natherul** [comment]
it works as intended, but that intention is that it only works when targeting naked enemy players as I differentiated them from the unlocks where it stated outside of combat.

**Comment by thorbolt80** [comment]
thanks for the information
