### ISSUE TITLE
Game Automatically Logs Me Out On Movement

### ISSUE THREAD

**Issue by AngeloMaligno** [WarEmu/WarBugs#11514]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Game automatically logs out when I move or go into another window for a short time.

Steps to reproduce the problem:

Play game in windowed mode and move or exit the window for a short time.

Screenshots/Videos or archive.org evidences:

Will provide on demand. I don't see how it's necessary though.

**Comment by sioding** [comment]
This bugtracker is only for ingame Problems. Seems like you having any client problems we can not deal with here. I would suggest to use this forum: https://www.returnofreckoning.com/forum/viewforum.php?f=5
