### ISSUE TITLE
Sorcerer Ability - Frostbite

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#11517]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

When I use this, I would expect the ability to deliver up to 519 Corporeal Damage and Disarm my enemy for 3 seconds, causing them to not be able to use melee or ranged abilities. The damage is delivering (on average around 400 damage) but the disarm is not working. 

I have tested this in combat with a friend who has verified that the disarm does not trigger when I use this specific attack.

Steps to reproduce the problem:

Please activate the disarm if it is possible.

Screenshots/Videos or archive.org evidences:

![frost](https://user-images.githubusercontent.com/22262165/37931330-32d54780-313d-11e8-9d6a-784fa594bc27.png)

![frost2](https://user-images.githubusercontent.com/22262165/37931472-a951959e-313d-11e8-8aef-e8155e44f297.png)

**Comment by wargrimnir** [comment]
You are mistaking the difference between Disarm and Silence. Disarm works against the physical damage classes Squig Herder, Engineer, and Shadow Warrior.

**Comment by Senthoi** [comment]
Thanks for clarifying :)
