### ISSUE TITLE
i got kicked after i logged in and moved to thunder mountain , when i trie now to logg in it says yaour acc not aktive , pls check notifications .  but there are none 

### ISSUE THREAD

**Issue by gorobelly** [WarEmu/WarBugs#11512]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
That was a server reboot.
