### ISSUE TITLE
can't join a new SC queue..

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#1151]
After I join a SC and then if I am afk, the timer might expire
After that I can no longer join a SC queue, it says "You cannot join a queue when you have a queue pop pending."  Even though I am no longer in one.

**Comment by Tiggonos** [comment]
its not after joining but if you queue for a sc it pops and then dont join but timer runs out after prolonging you cant queue anymore

**Comment by noisestorm** [comment]
*bump*  'Just' needs to be set as leave queue when the timer reaches 60seconds

**Comment by ozarmidrashim** [comment]
Can anyone confirm that this is still actually bugged? If it were bugged it would create a memory leak, and I've seen no evidence of this in the last dump.

**Comment by Tiggonos** [comment]
Fixed as of 16.09.2015

**Comment by Gobtar** [comment]
![pending](https://cloud.githubusercontent.com/assets/7888608/19214200/0a04349e-8d54-11e6-9fb9-e60badac041e.png)

As of 10/8/2016
