### ISSUE TITLE
Maw of Madness Orb.

### ISSUE THREAD

**Issue by Ripliel** [WarEmu/WarBugs#11520]
Expected behavior and actual behavior:
If you pick up one of the orbs right before the SC ends, it will still persist and damage you.

Steps to reproduce the problem:
Pick up orb right before the SC ends. Perfectly in few seconds before the stats window appear.

Screenshots/Videos or archive.org evidences:
![ripliel_123](https://user-images.githubusercontent.com/16005849/37984468-04403a2a-31ff-11e8-9c5c-d5e4e63357de.jpg)

**Comment by Natherul** [comment]
a possible fix for this is in the pipe for the next patch.

**Comment by sioding** [comment]
fixed with patch from 31.03.2018
