### ISSUE TITLE
Sigmar's Vision & Oathbound Stacking

### ISSUE THREAD

**Issue by jonomurphy** [WarEmu/WarBugs#11525]
WP Parry 10% buff and IB 25% Parry buff are stacking.

https://imgur.com/a/fpmvk

**Comment by sioding** [comment]
And it should not?

**Comment by jonomurphy** [comment]
EDIT: Feel free to close this; error on my part.

**Comment by thorbolt80** [comment]
You can close it by yourself if you created it
