### ISSUE TITLE
 Quest: "new allies, new enemies" Altdorf can't finish the quest

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11521]
When you click on NPC.  "complete" quest, nothing happen
![thorbolt_157](https://user-images.githubusercontent.com/16274785/37987963-f191f8cc-31ff-11e8-8ed4-8a523f7570e6.jpg)

**Comment by sioding** [comment]
Sorry thorbolt - can not reproduce thtat. Can you please redo the queststep and kill the pale assasin before talkin to lorenz guttman.

**Comment by thorbolt80** [comment]
Don't have questmarker on the map for the pale assasin do you have the pale assasin location please?
