### ISSUE TITLE
Blue Bag Reward 

### ISSUE THREAD

**Issue by Kuldus** [WarEmu/WarBugs#11522]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Clicked Gensis shard on a blue bag drop, gave me relic box

Steps to reproduce the problem:

Haven't been able to 

Screenshots/Videos or archive.org evidences:

https://imgur.com/a/c3f1w

**Comment by sioding** [comment]
Sorry but this can´t happen. If this would happen, we would have a lot of reports. Your screenshot also doesn´t help at all - it only shows a relic box.  Close
