### ISSUE TITLE
 T2 Epic Quest Chasing Oathgold. Missing NPC Dormir Karashot

### ISSUE THREAD

**Issue by EnmityOzZ** [WarEmu/WarBugs#11529]
As the title said I've encountered a missing NPC while I was trying to make the T2 epic quest Chasing Oathgold. On the 6th step you are required to speak with Dormir Karashot at 55k, 59k, the thing is that the NPC is missing. I've talked with some people and they told me the NPC should be there and some others told me they've done the quest 2 days ago. Even the quest marker is showing us that he should be around the area but he's no where to be found.

**Comment by sioding** [comment]
Checked that and sorry. the NPC is on the right place. 
![image](https://user-images.githubusercontent.com/18517842/38161406-7653ef2c-34ce-11e8-9f44-f449f466d4b3.png)
He is part of a PublicQuest which CAN be bugged sometimes. We know this problem but do not have a fix for it. Sometimes BPC´s do not load in Public Quests - so you need to wait until the next server restart.
