### ISSUE TITLE
Skull thumper's stacking 

### ISSUE THREAD

**Issue by Rzarrios** [WarEmu/WarBugs#11531]
Just saw this as I died to a zerg, it appears that skull thumper from multiple black orc's are stacking? I have no idea if it's intended or not, or if it is spec based. But I thought the more powerful one would overwrite the other. Either way, barely managed to grab a screenshot in the spam. 
![goldhand_001](https://user-images.githubusercontent.com/29615029/38168065-6b3ae356-34f7-11e8-9d93-2b49ed001ebe.jpg)

**Comment by sioding** [comment]
Thanks for the report. I see two Skull Thumper in your screenshot from two different BO´s. Its a normal ability from two players - why should only the one from the higher player hit?You said "you though". Can we please get any proof from live that it should?

**Comment by Rzarrios** [comment]
Well my reasoning was that other buffs / debuffs don't stack, why would this one be different? If it is working as intended that is fine, but I've never seen it so, after some consensus in channels I decided to submit it. I have no problem with the actual damage / initiation portion of the attack, just the debuff apparently not overwriting each other so that the higher tier would take precedence.

**Comment by sioding** [comment]
Well - thats not what i said. Could be a language thing cause i am not a nativ english guy. You screen shows two blows of Skull Thumper with its initial hits:
![image](https://user-images.githubusercontent.com/18517842/38171374-d54dee22-3598-11e8-9fc8-e35db8936d0f.png)
After that you should have a debuff which would hit you whenever you got a critical hit. Your screen doesn´t show that debuff cause you do not made it in combat. 
Maybe a better screenshot will help AND if you think something is wrong with it don´t bring phrases like "i thought" "maybe its intended" - we need good proof for those things.

**Comment by Rzarrios** [comment]
Those aren't initial blows, those are the debuff triggering when the squig herder crit me. Or am I reading the combat log incorrectly?

**Comment by sioding** [comment]
No proof or new screens for 14 days. close
