### ISSUE TITLE
Sonsea stormfire high elf chapter 14 saphery has a merchant icon over her head but she isn't merchant

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11530]
She don't sell anything
![thorbolt_159](https://user-images.githubusercontent.com/16274785/38159785-2c3479de-34b0-11e8-80c0-5d6bd89684b7.jpg)

**Comment by sioding** [comment]
@thorbolt80 was that after you finished all three quests she was giving before?

**Comment by sioding** [comment]
clsoe could not reproduce

**Comment by thorbolt80** [comment]
Yes sioding. After I finished all three quests you right.

**Comment by sioding** [comment]
Thanks - reopened - will check .

**Comment by sioding** [comment]
Fixed with Hotfix from 29.04.2017
