### ISSUE TITLE
Duplicates of "Runesash of the Depraved"

### ISSUE THREAD

**Issue by landgoat** [WarEmu/WarBugs#11535]
Expected behavior and actual behavior:
There should only be one "Runesash of the Depraved" however there are 2, with 2 different level requirements and stats under the same name. Just a minor bug.

Steps to reproduce the problem:
I got a the drop of a lvl 23 blue RP belt and searched it on the Auction House for others to pricematch and sell, and that is when I noticed the duplicates.

Screenshots/Videos or archive.org evidences:
Lvl 23. belt: https://imgur.com/a/be5k5
Lvl 15. belt: https://imgur.com/a/4o7SP
both same name, different items (stats, icon, lvl req, etc)

**Comment by sioding** [comment]
Checked - and no bug. We have level 15 and level 23 sets "of the Depraved". Close
