### ISSUE TITLE
drain magic

### ISSUE THREAD

**Issue by gebajger** [WarEmu/WarBugs#1153]
On live, drain magic was leeching  (180) AP over 9 sec regardless of the target's actual action points.
It was ticking about once every second.
In ROR it seems it's  ticking slower, making some of the stolen ap wasted, furthermore , if the target is low (on action) drain magic will not do anything making it a waste (45 ap cost).

**Comment by Silentguard** [comment]
Nope.
https://youtu.be/s3Gt3aTkNBo

**Comment by gebajger** [comment]
That video is not normal speed, i don't see whats the point.
I'm not sure that drain magic was ticking exactly every sec, but definitely faster than in ROR.
And I'm 100% sure that the target's actionpoints had no effect, you always got the 180 AP (unless disrupted, blocked or cleansed).

**Comment by Tesq** [comment]
maybe the first tick was at 0 sec like dok rec skill.

**Comment by Silentguard** [comment]
Than find video where ap gain clearly visible. Because am always get 90 ap each tick or value that was drained. Zero ap pool - zero ap gain. Exception is mobs and pets.

**Comment by Evildoor** [comment]
IIRC, all AP drains give you nothing if the target player has no AP. Closing.
