### ISSUE TITLE
ToK unlock Great Eagle from Dragons

### ISSUE THREAD

**Issue by Alfred19** [WarEmu/WarBugs#11537]
Mob "Unusual Sun Dragon" at Saphery 15.5k, 55.3k gives the ToK unlock "Encounter a Great Eagle" and counts upwards on kill.
![unusualsundragon](https://user-images.githubusercontent.com/37483326/38207491-55ada2e0-36ae-11e8-826e-012a829294d9.png)

**Comment by Vayra** [comment]
They are part of the PQ or a quest, IIRC, they are actually eagles with a dragon illusion

**Comment by Lheana** [comment]
They are Unusual Dragons, which means they are not common Dragons. In real they are not dragons, they are Great Eagles that have the appearance of Dragons, which explains why they count as Great Eagles.
