### ISSUE TITLE
Ostland: Access to Dangerous Territory

### ISSUE THREAD

**Issue by EienEcho** [WarEmu/WarBugs#11539]
There's a spot in Ostland where you can get to dangerous territory.

Steps to reproduce the problem:
Hop on this rock at 60,54
![co-ords](https://user-images.githubusercontent.com/38013634/38208386-bd5a2b3c-3665-11e8-8f3a-7181187d21ce.jpg)
![territory bug](https://user-images.githubusercontent.com/38013634/38207750-b7b6958c-3663-11e8-9746-49b8d0d672a7.jpg)
Then jump forward
![jump forward](https://user-images.githubusercontent.com/38013634/38207802-e6e23212-3663-11e8-8a4b-143ddb93d908.jpg)

From there you can head east a bit and you're in dangerous territory.

Edit: I'm not sure how to label this, but I suppose it would be Minor, and Map

**Comment by sioding** [comment]
Thanks for the report - but if you enter the area you would be teleported don´t you?

**Comment by EienEcho** [comment]
I can enter into "Dangerous Territory" without being teleported. I didn't go as far as  I could though. Eventually I randomly died and it couldn't respawn me. Relogging fixed that.

Should I be teleported as soon as I enter dangerous territory? 'Cause that didn't happen. I can go back and go deeper if you want.

**Comment by sioding** [comment]
Would be great. Thanks

**Comment by EienEcho** [comment]
After walking for a few minutes I can make it to this edge
![edge](https://user-images.githubusercontent.com/38013634/38275282-445d3c60-3746-11e8-94e2-93aa8e04176b.jpg)

No teleportation.
For my future reference, is accessing these areas worth reporting? Or would it be considered too minor?

**Comment by sioding** [comment]
Thanks for the test

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
