### ISSUE TITLE
Shadow Warrior's "Enchanted Arrows" not working on Flame Arrow's Direct Damage

### ISSUE THREAD

**Issue by Jevanko** [WarEmu/WarBugs#11542]
Expected behavior and actual behavior:
The Tactic should make flame arrow penetrate all resist mitigation. However, it only does so for the dot portion of the ability, but not the direct damage part.

Steps to reproduce the problem:
I tested this with a zealot friend. I hit him with and without the zealot resist buff to see that this was indeed the case.

**Comment by sioding** [comment]
Your testing screenshots please.

**Comment by Jevanko** [comment]
Did not screenshot it. But easy to test, don't even need to take the tactic off like explained above.

**Comment by sioding** [comment]
Thanks for the answer - if it´s that easy: Please do it and attach the screenshots here.

**Comment by sioding** [comment]
No reply since 24 days. close
