### ISSUE TITLE
Resetting Keep Lord 04.04.2018 /time 22:32 Badlands

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#11547]
There needs to be a bugreport about resetting Lords. So I will make this one as of a short evidence video taken on 04.04.2018 /time 22:32 in Badlands Destro Keep.

https://www.youtube.com/watch?v=TlQjlLKvnmU&feature=youtu.be

In the video the Lord is resetting while we are fighting Destro.
But he was also resetting like that around 20 minutes earlier with no Destro around.
He stopped moving, then began to blink in and out and then resets.

**Comment by Kaelang** [comment]
The leash range on lord reset has changed considerably since this report was written. If this issue persists please re-record new information and re-submit a report.
