### ISSUE TITLE
2 rally master in kadrin valley order warcamp (Balin runeshield don't give reward when you clic on it)

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11549]
The second one inside the tent Balin runeshield  don't give reward and he should be fix (grey icon). The first one Coras Grimhammer work fine and give rewards Problem : Coras Grimhammer are also in thunder mountain warcamp and black crag (triple spawn)

![thorbolt_164](https://user-images.githubusercontent.com/16274785/38348145-65ff099c-38a0-11e8-979e-c66115b57a14.jpg)
![thorbolt_163](https://user-images.githubusercontent.com/16274785/38348153-70995ce0-38a0-11e8-83b8-fcddd88d0474.jpg)

**Comment by Lheana** [comment]
#10992 Known issue, not fixable yet.
To sum up, we added the rally master of BC to warcamps of KV and TM so that players can take their influence rewards from each T4 greenskin VS dwarf warcamp, as for now we can not set different rally masters as giving the same infuence rewards.

**Comment by MaxHayman** [comment]
Added support for this.

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
