### ISSUE TITLE
Experience limit exceeded

### ISSUE THREAD

**Issue by rhayda** [WarEmu/WarBugs#11543]
I was in an extended keep siege. At least a couple hours multiple attempts and multiple lord resets. After keep was taken I received a message that I exceeded experience cap and i received no experience.

Expected behavior and actual behavior:
I would have expected to get at least the max cap limit but i received 0 experience.

Steps to reproduce the problem:
Earn higher then cap allows on long keep sieges.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Can we please see screenshots and if you know - please the time when it happend.

**Comment by rhayda** [comment]
It happened on 3/28/18 at 10 p.m.and the zone was caledor.  I did not capture a screenshot sorry. I originally posted on game support and it was mentioned to put in bugtracker.
