### ISSUE TITLE
Tactic "I got lots": Un summoning current squig of same type

### ISSUE THREAD

**Issue by smingleton** [WarEmu/WarBugs#11540]
When I got lots is slotted it shouldn't un summon any squig it should just start summoning whichever squig you click on. 
It works except whenever you try to summon the same kind of squig you already have out, it unsummons it so you have to click the key bind twice to start summoning again, and you lose the current buff in place which doesn't happen when switching between different squigs.

Slot I got lots tactic, summon spiked squig, then summon gas squig and notice how spiked squig buff is up while casting gas squig. Now try and summon gas squig, gas squig vanished like the tactic wasn't even there. It works the same with any squig you try to summon that you already have out

I made a video showing the bug. https://www.youtube.com/watch?v=1gXzDJ4glxk&feature=youtu.be

**Comment by sioding** [comment]
Put the minor flag on it cause its only a problem if you summon the same pet again. You should know which pet you are currently using.

**Comment by smingleton** [comment]
Thank you for looking into this! I am aware which squig I am using, that's not how I experienced the bug I think.
It's mainly a problem for the gas squig, if it's far away or getting killed while your also being attacked. you should be able to summon a new one while keeping the armor buff if using I got lots tactic.
