### ISSUE TITLE
Riposte procs from melee dot damage (Bleeds)

### ISSUE THREAD

**Issue by Smokeymaxamus** [WarEmu/WarBugs#11548]
Not sure if we should follow this format but since its here might as well.
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Riposte should proc on hit of abilities or melee, procs on any DoT damage considered melee and with really far range between players

Steps to reproduce the problem:
long time melee dot like mara wave of mutilation and enemy with high parry or parry skill/morale

Screenshots/Videos or archive.org evidences:
![ihavepsoriasis_007](https://user-images.githubusercontent.com/38093139/38347575-45bd915c-386a-11e8-9830-6cce8e348cba.jpg)

I applied dot right before i died (which you can see the "you are dead"), and was being hit with riposte damage when i was respawned in keep

**Comment by grunbag** [comment]
Fixed already
