### ISSUE TITLE
scenario 11 vs 13 bug

### ISSUE THREAD

**Issue by velkos4ever** [WarEmu/WarBugs#11541]
Hello sometimes i noticed that the scenario instead of making a 12 vs 12 it does 11 vs 13 or 12 vs 13
here some picture's down below

scenario 1:
![nighteyes_555](https://user-images.githubusercontent.com/16551075/38215544-df7dce24-36d0-11e8-96b6-7169ea3b003e.jpg)
![nighteyes_556](https://user-images.githubusercontent.com/16551075/38215546-e1c7bc8a-36d0-11e8-96a8-6a495fff3f57.jpg)
scenario 2:
![nighteyes_557](https://user-images.githubusercontent.com/16551075/38215560-ed7babc2-36d0-11e8-913c-4025ea0c703d.jpg)
![nighteyes_558](https://user-images.githubusercontent.com/16551075/38215567-f1e3695c-36d0-11e8-8ca1-219ac2192fbc.jpg)

**Comment by sioding** [comment]
You see 13 ppl in a scenario when one of them left or the scenario or chrashed or whatever and antoher one has inveted for him.
