### ISSUE TITLE
Trading items w/ talismans

### ISSUE THREAD

**Issue by magter3001** [WarEmu/WarBugs#1154]
Trading an item that has a talisman in it to another player will make the talisman on the item disappear.

**Comment by magter3001** [comment]
Another Talisman bug, If you put a talisman into an item and then press the x on the top right corner of the item screen, the talisman will be used up and the item you wanted to put the talisman in will still have an empty talisman slot. So you completely destroy your talisman then without using it.

**Comment by Evildoor** [comment]
First problem should be fixed. Second one is reported elsewhere.
