### ISSUE TITLE
Chaos Chapter 7 Rally Master Bug

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#1155]
During the quest chain "Chosen" there is a quest where you have to kill Bor Graymane and get his eye, in the half a dozen times I have killed him, his eye has not yet dropped preventing the quest from being completed.

Also the Rally Master (Kournar the Chosen) for Chaos Chapter 7 does not allow for setting the rally point to him, it gives the error message: "ERROR: Unknown Rally Point NPC (549)."

Both of these were tested in multiple sessions as well as with different characters

Thank you

**Comment by milosxe** [comment]
Here's the proper ticket concerning the quest "Chosen" https://github.com/WarEmu/WarBugs/issues/1185

I'll rename this to the rally master bug cause that's still an issue, exactly as described.

**Comment by Torquemadra** [comment]
fixed next patch
