### ISSUE TITLE
[Visual Bug] Komar Dwarf camp. BM T1 : Npc without gear and dress 

### ISSUE THREAD

**Issue by LeonVic** [WarEmu/WarBugs#11551]
Not an essential
![immagine2](https://user-images.githubusercontent.com/38075110/38370584-bc270406-38ea-11e8-8be4-dcac50aff1d9.png)
  bug. But just to make a good play experience through the RoR country.

**Comment by sioding** [comment]
This is already know - and not fixadble. These NPC are not naked but the client thinks they are. If you kome to the zone again they will be shown with clothes.So no bug. Close
