### ISSUE TITLE
2 rally master thunder mountain WC order side (Dagren ironshot don't give reward when you click on it)

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11550]
Dagren ironshot inside the tent don't give reward and Coras grimhammer have triple spawn (kadrin, thunder and black crag) any way to fix Dagren ironhsot?
![thorbolt_167](https://user-images.githubusercontent.com/16274785/38348374-ab0a1792-38a1-11e8-90b4-e85b7f1c7433.jpg)

![thorbolt_162](https://user-images.githubusercontent.com/16274785/38348409-d36e104e-38a1-11e8-9168-a7d185bdb20a.jpg)

**Comment by Lheana** [comment]
#10992 Known issue, not fixable yet.
To sum up, we added the rally master of BC to warcamps of KV and TM so that players can take their influence rewards from each T4 greenskin VS dwarf warcamp, as for now we can not set different rally masters as giving the same infuence rewards.

**Comment by MaxHayman** [comment]
Added support for this.

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
