### ISSUE TITLE
Gunbad, Glomp da Squig Masta 

### ISSUE THREAD

**Issue by Grunbeast** [WarEmu/WarBugs#11556]
If you tank this boss on uneven surface he will stop casting any ability's except auto attack. If he stuck on one of those 4 stone roads leading to central platform it may happen. I think it have some thing to do with terrain levels in the game because we could not cast some range attacks on him and got "you can not see your target" message but melee could dps him.
We have seen same bug with a goblin miniboss before last pq in left wing(I forgot his name). If you pull him down from the top of the hill where he staying at, he will not cast anything as well.

**Comment by Grunbeast** [comment]
![grunbeast_255](https://user-images.githubusercontent.com/35007878/39472930-80016018-4d4c-11e8-96be-d12c5a726d1a.jpg)
![grunbeast_256](https://user-images.githubusercontent.com/35007878/39472931-801d94a4-4d4c-11e8-8588-45761d06298b.jpg)
So if he stay here he stop cast anything except aa.

**Comment by grunbag** [comment]
Already fixed
