### ISSUE TITLE
Absorb shields and crit damage

### ISSUE THREAD

**Issue by Karast** [WarEmu/WarBugs#11557]
There seems to be an issue concerning absorb shields and crit damage.

When an absorb shield is active it seems that an abilities chance to crit, and possibly the scaled crit damage is greatly reduced. The first part can be somewhat easily confirmed with a high crit character and one with constant absorbs. The second part is a little bit harder to confirm. Some crits do go through the absorb, but the damage is often lower than it would be on a normal crit. Something strange is happening.

After some basic testing in duels, scenarios, and warbands, absorbs have a huge effect on survivability since they are almost working as a 3-5s anti crit. You still get crit but crits seem to do greatly reduced damage, to the point of doing non crit damage into the absorb.

The existence of this bug may also be reinforced with the sudden meta shift to absorb proc gear, tactics, and the huge spike in cost for absorbs on the AH seen recently.

**Comment by sioding** [comment]
Thanks for the report. Can we please see your testing screenshots?

**Comment by Karast** [comment]
![inkedinkedkarast_021_li](https://user-images.githubusercontent.com/16921765/38418979-79e84970-39d9-11e8-8bfd-3f25f9c32cd8.jpg)
![inkedinkedkarast_030_li](https://user-images.githubusercontent.com/16921765/38418980-7a0ed694-39d9-11e8-867e-8d307bc879a7.jpg)



Here are two easy SS's form this morning. If you look at the circled areas you can see a regular hits, regulars hits vs absorb, critical hits, and critical hits vs absorb.

Notice that the regular hit vs absorb and the critical hit vs absorb is the same value.  447. As long as their is enough absorb remaining every crit from that abililty will be 447 with slightly different mitigation values. The same absorb value as a non crit hit.  If you have a partial absorb the ability does more damage than if you have a full absorb. I tried to sloppily high light the screenshots so please take a look. 
All things considered something fishy is going on. A crit and non crit should no be doing the same damage with absorb.

As far as the crit rate vs absorb. I need to make a cleaner video for it. It is harder to tell due to the randomness of crit in smaller scale tests.

**Comment by Lefze** [comment]
We tested some absorbs yesterday, it seems that numbers in combat log are displayed incorrectly. Crit/non crits were all showing roughly the same amount of absorbed damage, about 600, but bubble was consumed by said 600 damage even though tooltip for the bubble is over 900.

Also dot ticks didn't show at all before bubble was gone, something wonky is going on with at least a few bubbles.

**Comment by Torquemadra** [comment]
I can see literally NOTHING in those screenshots. opaque log = worthless.

**Comment by Karast** [comment]
I'll see about taking more SS's for you when I am off work later this week. 

But it literally takes 5 min with a healer and enemy dps to see the issue noted above. So if anyone could beat me to the punch I'd be grateful. I might not have time till Monday.

I don't know why but crit hits and non crit hits are hitting for the same damage when fully absorb'd. Something strange is happening.

**Comment by sioding** [comment]
Thx for the new screen.

**Comment by dalen** [comment]
This works as intended, absorbed damage can't crit.
