### ISSUE TITLE
[Loot rate] T1 Dwarf, PQ: Kron Komar Gap

### ISSUE THREAD

**Issue by LeonVic** [WarEmu/WarBugs#11552]
I wont to advice u about this "strange" loot rate that i find in T1 Dwarf PQ: Kron Komar Gap.
In less than 5 min i spin to get aggro of many npc , and theire release me 3 epic gear.
Ok, gear are for lv 5 but , loot rate is correct?
Tks

![learco_013](https://user-images.githubusercontent.com/38075110/38371663-4bbcdd96-38ed-11e8-9980-c1dbecdeb78b.jpg)
![learco_014](https://user-images.githubusercontent.com/38075110/38371664-4bdc9488-38ed-11e8-9ea8-77ba5005aef7.jpg)
![learco_015](https://user-images.githubusercontent.com/38075110/38371665-4bfa2d9a-38ed-11e8-9788-3cc8e9a46834.jpg)

**Comment by sioding** [comment]
Thats the war RNG runs - sometimes you are lucky. No bug. Close
