### ISSUE TITLE
[Choppa] Git to da choppa ability is pulling people from above

### ISSUE THREAD

**Issue by easykatka** [WarEmu/WarBugs#11553]
Expected behavior and actual behavior:
Git to da choppa should not pull players from surfaces above caster according to global magus/engi/mara/wl pull abilities changes, but it pulls, sometime through textures of keep floors. Its possible to pull player from keep wall aswell.
Steps to reproduce the problem:
Choppa using Git to da choppa on enemy player.
Video: 
https://youtu.be/Ox8hHeF3sNM

**Comment by sioding** [comment]
fixed with patch from 14.04.2018
