### ISSUE TITLE
[visual bug] Quest Markers on Map and ToK

### ISSUE THREAD

**Issue by LeonVic** [WarEmu/WarBugs#11565]
Hello there!!
As the following img show , i have 5 quest active, but no one appear marked on map.

![learco_018](https://user-images.githubusercontent.com/38075110/38465500-ce544bdc-3b1c-11e8-9c11-262e16efc98f.jpg)

In Tome of Knowledge it appear like that:
![learco_019](https://user-images.githubusercontent.com/38075110/38465547-6d721f1e-3b1d-11e8-99b9-95ccf0d48e5f.jpg)

Its all ok?

take my apology if that work as intend and isnt a bug

**Comment by thorbolt80** [comment]
I got the same problem for all quests but it works on the mini map only . Weird.
