### ISSUE TITLE
Elves on boat at Reikland Agro zone 

### ISSUE THREAD

**Issue by oroxor** [WarEmu/WarBugs#11566]
In the south of Reikland (in rvr zone), the elves on boat before was able to farm, now we can't cause the agro zone is too small.

Steps to reproduce the problem:
Enlarge the Elves agro zone like before

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Screen with locations please and why can´t you just pull them ?

**Comment by oroxor** [comment]
Screen as you ask 

![jeanclode_000](https://user-images.githubusercontent.com/38176487/38466552-220a340e-3b2b-11e8-93d7-36ab55c5af5e.jpg)


location 32550 , 50871

![jeanclode_001](https://user-images.githubusercontent.com/38176487/38466555-31c6f0ee-3b2b-11e8-90b9-d99718bb7cde.jpg)

**Comment by sioding** [comment]
No bug - everythings fine. You can "farm" these elves by simply pull them with a shout or knife

**Comment by oroxor** [comment]
hello ,

No i try now and i cant throw a knife on them the aggro zone is not enough high

**Comment by sioding** [comment]
Creating a new ticket won´t help at all. There is no need to change any of these elves on the boat - you have enough elves on the beach right beneath the boat. So _why_  should we change anything ?

**Comment by oroxor** [comment]
Because they are level 41 and im interested by them
