### ISSUE TITLE
road warden title in murder woods 

### ISSUE THREAD

**Issue by lijebin** [WarEmu/WarBugs#11564]
not working when i click on a herdstone

**Comment by lijebin** [comment]
Interact with the beastman 'Herdstone' at 40.5k 36.4k in Nordland, in the northeast part of the 'Murder Wood' Major Landmark. i do that but nothing happen Rewards Road Warden

**Comment by Lheana** [comment]
Screenshot of the ToK page of Beastman, Gor please

**Comment by sioding** [comment]
fixed with patch from 14.04.2018
