### ISSUE TITLE
Order Quest: Self Fulfiling Prophecy / wrong questmarker

### ISSUE THREAD

**Issue by Eusebeus82** [WarEmu/WarBugs#11573]
Expected behavior and actual behavior:
Map marker shows for quest at location c35k,36k
Quest objective is obelisk outsied red circle at c35k,40k

Steps to reproduce the problem:
Obtain quest at HE ch19 Eataine. Observe incorrect map marker.

Screenshots/Videos or archive.org evidences:
![eusebeus_011](https://user-images.githubusercontent.com/18599533/38494953-b6dba63e-3bef-11e8-8e25-49d95502f9c9.jpg)
![eusebeus_010](https://user-images.githubusercontent.com/18599533/38494971-c54ee1ea-3bef-11e8-9bee-4801ee42211a.jpg)

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 14.04.2018
