### ISSUE TITLE
BFP Keep player trap

### ISSUE THREAD

**Issue by Simmox** [WarEmu/WarBugs#11571]
quick search reveals no prior mention?

BFp keep player trap.
viewing as from the outside of keep.(ie,the first gate/wall)
upon entering the LH side outer postern door and then proceeding up the closest ramp to outer wall,you can fall off the edge of the staircase and become trapped between the keep wall and stair case itself.
there is a small gap to try and squeeze through but,after trying for sometime, i dont think you can get out again.i can supply screenie if required but its pretty obvious to see if in the area.

**Comment by sioding** [comment]
Screens are always good. Thanks for adding them.

**Comment by sioding** [comment]
Hm tried to find the place - but your description is strange for me. please add screens

**Comment by Simmox** [comment]
i shall do,as soon as im able to get to the keep again.

**Comment by Simmox** [comment]
![gnol baraz 002](https://user-images.githubusercontent.com/16268327/39295014-6b256776-497c-11e8-9929-b8e07dad12eb.jpg)

the approximate area of the trap,right in the corner of the walls,on the inside,climb the ramp and try to fall into that corner

**Comment by sioding** [comment]
![image](https://user-images.githubusercontent.com/18517842/39626056-bcc4a37e-4fa0-11e8-89a1-f34fc1ac8849.png)

**Comment by NorKalli** [comment]
![image](https://user-images.githubusercontent.com/19868634/39669804-00a8a06c-50ab-11e8-813b-904fdf7ad349.png)

plank placed, should no longer eat people

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
