### ISSUE TITLE
T4 epic quest Unmasking the enemy - bugged NPC

### ISSUE THREAD

**Issue by Timmitz** [WarEmu/WarBugs#11570]
Expected behavior and actual behavior:
1st stage of the epic T4 quest Unmasking the Enemy
Uthorin Direscythe lvl 38 cant be taunted/hit. does aggro but cant be hit back.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![halfxane_010](https://user-images.githubusercontent.com/36116924/38482396-668d040e-3bcf-11e8-8247-11c28898f8df.jpg)

**Comment by sioding** [comment]
Two things. 
1. It´s not something for the quest - cause the NPC you are targeting is not a questobject. 
2. I can clearly fight against both of them:
![image](https://user-images.githubusercontent.com/18517842/38571926-173f37ae-3cf2-11e8-80a4-27c640e81c86.png)


So sorry close - not reproducable.
