### ISSUE TITLE
Terrain issue in troll country kins bo

### ISSUE THREAD

**Issue by Kvoth2** [WarEmu/WarBugs#11579]
Somehow he manage to get up there and we couldn't get the BO because of that.
Expected behavior and actual behavior:

Maybe block that terrain so they cant climb up there?

Screenshots/Videos or archive.org evidences:
![kvoth_011](https://user-images.githubusercontent.com/38228702/38522155-653a1142-3c50-11e8-8d9e-e8b972e2932d.jpg)

**Comment by sioding** [comment]
Nope sorry - this is no issue. You can simply jump up there - since ages.
