### ISSUE TITLE
Can read and see order warband while i am on my destro

### ISSUE THREAD

**Issue by NervZ** [WarEmu/WarBugs#1157]
So i was on my White Lion and i joined a scenario while i was in a open warband. During scenario i was  in a sc group and in that warband at the same time.
 After the sc finished i relog on my Marauder. However, i was still able to see the order's warband, i was with my White Lion, chat and i could even see the warband's members on the warband tab. 
Also, a visual bug. On my backpack it did show the gold i have on my White lion instead my marauder's gold.
I got a screenshot but i forgot to take while i had the warband tab ON.
After i closed the game and relog it was fixed.
![nervzorder_000](https://cloud.githubusercontent.com/assets/9929186/9492980/048b5a60-4c05-11e5-9dfe-f90e19880fd8.jpg)

**Comment by Evildoor** [comment]
I had the same problem once, also when i joined a scenario while being in wb. However, in some patches after that the mechanics of parties was updated and you don't leave the party when you go to scenario. Does this problem still persists for anyone?

**Comment by Evildoor** [comment]
No confirmation, closing for now.
