### ISSUE TITLE
Chrace WC mailbox isn't working atm

### ISSUE THREAD

**Issue by ferraz19** [WarEmu/WarBugs#11578]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
the mailbox should open but it does not. 3 people in group tried opening but nothing happened.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

![whyn_000](https://user-images.githubusercontent.com/30166423/38521962-2889e29e-3c15-11e8-8ba9-fc34f08e102d.jpg)

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 14.04.2018
