### ISSUE TITLE
Order Quest: What Separates us

### ISSUE THREAD

**Issue by Eusebeus82** [WarEmu/WarBugs#11575]
Expected behavior and actual behavior:
Quest has additional stage 0/10 which I believe is an error.

Steps to reproduce the problem:
Take quest HE ch19 Eataine, observe.

Screenshots/Videos or archive.org evidences:
![eusebeus_014](https://user-images.githubusercontent.com/18599533/38495834-06373a7e-3bf3-11e8-9bd2-aa68663eb11f.jpg)

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 14.04.2018
