### ISSUE TITLE
PQ Rotten Embrace HE CH 10 Mobs not spawning fast enough

### ISSUE THREAD

**Issue by offkors** [WarEmu/WarBugs#11572]
Expected behavior and actual behavior:
In stage 2 of the PQ it's possible to click the roots without a mob spawning. It will still grant inf and progress the stage.

Steps to reproduce the problem:
Click one of the roots spawning a mob, kill the mob. When the same root becomes clickable again, click it.
It will produce a server message but no mob.

Screenshots/Videos or archive.org evidences:

![manlet_000](https://user-images.githubusercontent.com/37836035/38491694-ea322d3a-3bec-11e8-8d73-2c86e5f61045.jpg)

Note that this isn't gamebreaking, just a small issue.

**Comment by sioding** [comment]
fixed with patch from 04.08.2018
