### ISSUE TITLE
Order Quest: Key to the past / wrong questmarker

### ISSUE THREAD

**Issue by Eusebeus82** [WarEmu/WarBugs#11574]
Seems to be a theme in Isle of the Dead so far
Expected behavior and actual behavior:
Map marker for quest is at c 41k,30k
Quest object Grimstar Spear is at c41k,35k

Steps to reproduce the problem:
Obtain quest HE ch19 Eataine, observe quest marker error.

Screenshots/Videos or archive.org evidences:
![eusebeus_013](https://user-images.githubusercontent.com/18599533/38495447-847ad7f8-3bf1-11e8-98c0-ac0b2c6fbf40.jpg)
![eusebeus_012](https://user-images.githubusercontent.com/18599533/38495450-8616add0-3bf1-11e8-88df-4e49d128412d.jpg)

Thanks also to Wardor for helping locate item..

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 14.04.2018
