### ISSUE TITLE
lag in altdorf

### ISSUE THREAD

**Issue by krunched** [WarEmu/WarBugs#11576]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
when you walk into the market square in altdorf you get a sharp lag or freeze up... some people just plain crash as ive been watching this for a few weeks now...

Steps to reproduce the problem:
enter the market square from any angle... when the boat for land of the dead loads in it causes a freeze up some people crash... i believe disabling this boat as we do not have access to land of the dead anyway will prevent this issue from happening... it occurs when you land from the flight master entering market square or if leaving from say the bank end of town into the market square... as soon as the land of the dead boat loads (and you can visually watch it happen if you pan your camera angle) you will freeze for a hot second while the boat loads in... many crashes and just straight freezing up caused by this item

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Should be fixed ( even not that bad as before) now
