### ISSUE TITLE
Earthshatter

### ISSUE THREAD

**Issue by bloodi** [WarEmu/WarBugs#11585]
https://github.com/WarEmu/WarBugs/issues/8357
https://github.com/WarEmu/WarBugs/issues/8351
https://github.com/WarEmu/WarBugs/issues/6824

Its happening again, randomly not doing damage on targets that still get the snare debuff and thus, should be damaged.

**Comment by sioding** [comment]
Your testing Screenshots please.

**Comment by sioding** [comment]
No reply since 15 days. close
