### ISSUE TITLE
[Engineer] cant summon turret

### ISSUE THREAD

**Issue by Halhammer** [WarEmu/WarBugs#1158]
I'm gettin this cast exception error since last nite's reset, saw other engis with it too, although some seem to be able to cast/summon as normal.

Guess that's a known issue, just wanted to keep ya posted.

**Comment by Evildoor** [comment]
I don't play engi much, but when i played recently i had no problems, and so did my friend. Does this problem still exists for anyone?

**Comment by Halhammer** [comment]
Seems to be workin properly the last few weeks now. Only the issue with turret self destruct ability remains

**Comment by Evildoor** [comment]
Ok, closing this then.
