### ISSUE TITLE
Mastery Respecialization in Altdorf Stole from me.

### ISSUE THREAD

**Issue by Acamano** [WarEmu/WarBugs#11583]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Acamano** [comment]
Messed up the OP. 
Anyways, tried to respecialize with the career trainer in Alforf’s Palace district. The NPC - Trainer Eduardt was who I spoke with the respec. I walked over in front of him, spoke, opened masteries, and then chose to respec. I got the warning that it would cost, I accepted and the sound of my coins being taken was heard but my points were not refunded. I did it again and the same thing happened. After relogging, I did it again and still no refund nor points. I lost about 20g for doing it a few times.
Talking to the other trainer worked the first time, but I also removed all my gear and put it back on.

**Comment by sioding** [comment]
Sorry tried my best to reproduce that but i wasn´t able to. This trainer does his job very well. Maybe some UI problems on your side? a lot of addons? TBH when we really had a problem with that trainer - believe me we had tons of reports after the Anywhere Trainer nerf.
