### ISSUE TITLE
Manticore/Griffon allows mounting with scenario part

### ISSUE THREAD

**Issue by NorKalli** [WarEmu/WarBugs#11587]
self explanatory

**Comment by Natherul** [comment]
which scenario? They use different code

**Comment by NorKalli** [comment]
Howling Gorge, Black Fire Basin

[https://imgur.com/a/qx6j8](url)

**Comment by Natherul** [comment]
fixed in the next patch

**Comment by sioding** [comment]
fixed with patch from 14.04.2018
