### ISSUE TITLE
Thunder mountain warcamp order side guard kill non stop a spider "magma crawler"

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11582]
40.6 at the exit of the order warcamp 

![meteore_004](https://user-images.githubusercontent.com/16274785/38539168-415a9e1c-3c97-11e8-84ee-b779f8e36753.jpg)
![meteore_005](https://user-images.githubusercontent.com/16274785/38539176-4f49fa86-3c97-11e8-8d42-5802c3002c4f.jpg)

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 14.04.2018
