### ISSUE TITLE
Tor Anroc Bauble, caught in air after dying during punt.

### ISSUE THREAD

**Issue by Arryhthmia** [WarEmu/WarBugs#11597]
Holding Bauble, got punted and died in the air, bauble stayed put the whole game and match had to be played on kills, instead of resetting itself.

Get punted and die in mid-air to reproduce.

![arrhythmia_010](https://user-images.githubusercontent.com/38362793/38754906-0d728642-3fa7-11e8-8fc0-d5e021101e00.jpg)

**Comment by Natherul** [comment]
should be addressed with the next update

**Comment by Natherul** [comment]
should be sorted with hotfix that was deployed now
