### ISSUE TITLE
Gunbad: Masta Mixa

### ISSUE THREAD

**Issue by nelsonus** [WarEmu/WarBugs#11592]
My group ran Gunbad on Tuesday, 4/10/18, from 6:00 - 9:30 PM PST.
We did the right wing first, and got down to Instance boss, Masta Mixa. Edit: We did fail on the first PQ boss, but continued after the timer ran out.
We did the fight and got him down to 0% health, and he died. But we could not loot him. Also, he kept performing ranged attack on me (i was the tank) while dead. If i moved out of range, his corpse followed and kept shooting.

We were able to target the corpse, but could not attack the corpse. We could not hit the corpse with any AOE abilities either. The mechanics of the fight did not continue, there was no adds or sticks, etc.

After roughly 3 or 4 minutes, the boss corpse disappeared with error message in chat log. I forget the exact words, but i think it was "NullZoneException".

I will attach screenshots when I return from work.ld be unique. Check if someone else reported the issue 

Steps to reproduce the problem:
Kill Masta Mixa

Screenshots
![racta_006](https://user-images.githubusercontent.com/16074190/38716022-6b165e1e-3e93-11e8-931e-7ed382aef9f5.jpg)
![racta_002](https://user-images.githubusercontent.com/16074190/38716023-6b36841e-3e93-11e8-904f-45f780071c12.jpg)
![racta_003](https://user-images.githubusercontent.com/16074190/38716024-6b5386b8-3e93-11e8-9c25-f21404f6592f.jpg)
![racta_004](https://user-images.githubusercontent.com/16074190/38716025-6b7061ac-3e93-11e8-9e05-f7899b4a43f3.jpg)
![racta_005](https://user-images.githubusercontent.com/16074190/38716026-6b8d8e4e-3e93-11e8-9995-89409908f884.jpg)

**Comment by grunbag** [comment]
Fixed already

**Comment by dihanin** [comment]
sorry, we did it last boss of gunbad right wing, when we loot , didn't get anything. please help
2018/12/22
