### ISSUE TITLE
Glaive of Change Alt Appearance

### ISSUE THREAD

**Issue by Zoggof** [WarEmu/WarBugs#11591]
Glaive of Change for the BG is listed as a Great Sword therefore its alternative appearance is unusable with Great Spear (2h) weaponry.

![capture](https://user-images.githubusercontent.com/23256143/38670676-ceaab486-3e8c-11e8-8b02-3506db0be830.PNG)

**Comment by sioding** [comment]
Where did you get this item from?

**Comment by cimator** [comment]
Its a reward from Chaos T3 Epic quest, Inevitable Power;
https://wiki.returnofreckoning.com/index.php/Chaos_T3_Epic_Quest_Inevitable_Power

**Comment by NorKalli** [comment]
Weapon type set to spear, should work now

**Comment by sioding** [comment]
[11591] It
