### ISSUE TITLE
Reikland Factory - Destro Guard by Destro Side mid BO entrance - Aggro range too close to BO entrance

### ISSUE THREAD

**Issue by Zaxx0nd** [WarEmu/WarBugs#11593]
Expected behavior and actual behavior:
In Reikland Factory, there is a warcamp guard by the destro side Steamtank plant middle BO.  Destro uses this guard to kill order by punting, pulling and standing right behind the guard.  As to why this is a problem, the guard aggro range is very close to the entrance and the champion is typically used by Destro to kill Order because of the aggro range being so close to the entrance.   Destro will run to center, then kite to the guard to draw aggro.

Screenshots/Videos or archive.org evidences:  I can provide a screenshot if really needed, but you can see how close the Destro Champion is to the Destro side middle BO entrance in Reikland factory.  Please move this guard back.

**Comment by sioding** [comment]
Sorry no bug - thats intended.
