### ISSUE TITLE
tor anroc bubble

### ISSUE THREAD

**Issue by velkos4ever** [WarEmu/WarBugs#11596]
Hello i played a scenario in tor anroc and when the bubble reseted from an overextending player the bubble instead of appearing in the middle as intended it appeared somewhere of in the lava while the map showed that it was in the middle so i tried to go in the middle and click the bubble way off me and it interacted.picture below:
![nighteyes_603](https://user-images.githubusercontent.com/16551075/38752135-cd506e10-3f62-11e8-8979-b24452eb035f.jpg)
the bubble is in the right side of the screen in the lava

**Comment by Natherul** [comment]
same as https://github.com/WarEmu/WarBugs/issues/11597
or well they are linked as in they are caused by the same issue
