### ISSUE TITLE
Magus pet / engineer turret still melting should I report as a bug? or intentionnaly nerf?

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11602]
Magus/engineer pets are so weak now that all smart order or destroy players first focus pet and destroy it in maximum 3 seconds. I even saw a dps dok then another time marauder instant destroy turret same for white lion who destroy magus pet instantly... Then you have to recast pet (3 seconds) then wait x8 damage (after 16 seconds to have normal dps) so 19 seconds to have full dps for magus/engineer.

The magus/engineer pets was may be not nerfed intentionally? He came from the change on white lion pets patch that affect magus/engineer pets?

May be a dev who in charge of class balance can give us an answer? Magus/engineer pets were nerf intentionnaly? or it's just a bug to report came from the change of white lion pets patch?

The communites ask if it's a bug or not?  for discussion on the forum :

Secret weakness magus pet / engineer turret still melting

https://www.returnofreckoning.com/forum/viewtopic.php?f=74&t=25991&p=296699#p296699

**Comment by sioding** [comment]
Nope @thorbolt80  - the bugtracker is the wrong place for this question. Use the forum for this.
