### ISSUE TITLE
Blessing of Heaven [SM] database error.

### ISSUE THREAD

**Issue by Ramasee** [WarEmu/WarBugs#11609]
Expected behavior and actual behavior:
Blessing of Heaven receives a bonus to its healing by 4 per rank. At ranks 28, 32, 36, and 40 it gains zero increase at all.

Steps to reproduce the problem:
Place points into path of hoeth one at a time and note the healing values.

I only tested ranks 25 - 40 of the ability as I did not think to test all of this when I was leveling my SM. If you go to the Swordmaster Abilities tab on this spreadsheet, you can see the values from 25 - 40.
https://docs.google.com/spreadsheets/d/1dUibivNokYm-L0QWN59oJjb0wweDtUzWKgUYTP1Q_EA/edit?usp=sharing

**Comment by sioding** [comment]
screenshots with your testst please.

**Comment by Ramasee** [comment]
![boh25](https://user-images.githubusercontent.com/18507595/38783277-f410f9e0-40cd-11e8-8d76-a7a269c2184c.jpg)
![boh26](https://user-images.githubusercontent.com/18507595/38783278-f4be3600-40cd-11e8-85ad-094037d1a326.jpg)
![boh27](https://user-images.githubusercontent.com/18507595/38783279-f5c00b78-40cd-11e8-9901-2c406e401c40.jpg)
![boh28](https://user-images.githubusercontent.com/18507595/38783281-f674fd6c-40cd-11e8-84b9-b775b6b8ec82.jpg)
![boh29](https://user-images.githubusercontent.com/18507595/38783282-f756e8f8-40cd-11e8-8150-4acf765fa933.jpg)
![boh30](https://user-images.githubusercontent.com/18507595/38783283-f80b7854-40cd-11e8-84d8-5f48dbc5cf7a.jpg)
![boh31](https://user-images.githubusercontent.com/18507595/38783285-f8d51092-40cd-11e8-847b-1d9b7e9d76b4.jpg)
![boh32](https://user-images.githubusercontent.com/18507595/38783287-fab652cc-40cd-11e8-84fe-a6046bc891c4.jpg)
![boh33](https://user-images.githubusercontent.com/18507595/38783289-fc03c1a0-40cd-11e8-94e8-a65c7088f8ca.jpg)
![boh34](https://user-images.githubusercontent.com/18507595/38783291-fc59eeb8-40cd-11e8-983c-bdd162c6af33.jpg)
![boh35](https://user-images.githubusercontent.com/18507595/38783292-fc68daa4-40cd-11e8-9582-5ba40a9f58df.jpg)
![boh36](https://user-images.githubusercontent.com/18507595/38783293-fc94e66c-40cd-11e8-80ff-ac0e50330255.jpg)
![boh37](https://user-images.githubusercontent.com/18507595/38783294-fd0698c0-40cd-11e8-8906-9022980f1f42.jpg)
![boh38](https://user-images.githubusercontent.com/18507595/38783296-00c7a184-40ce-11e8-8b76-e0243b79e829.jpg)
![boh39](https://user-images.githubusercontent.com/18507595/38783295-00b6fd34-40ce-11e8-9525-7b1d19ef4b0c.jpg)
![boh40](https://user-images.githubusercontent.com/18507595/38783297-00e8a8fc-40ce-11e8-8ec5-4c36fe471514.jpg)

**Comment by grunbag** [comment]
Tooltip values are generated by client , I don’t think it’s a bug
