### ISSUE TITLE
.gestats only show block stat from renown

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11604]
I have 4.7 block with the shield. I choose defender 1(cost 1 renown points) who give (+1% block)  so 4.7 + 1% with renown tactic = 5.7% block

getstats show only 1%
![victorine_000](https://user-images.githubusercontent.com/16274785/38768000-b57cc650-3fec-11e8-91f3-b8282a27fcdc.jpg)

**Comment by Natherul** [comment]
because getstats only shows the added stats, not the total of stats from base added as well.
