### ISSUE TITLE
Can't attack players in RvR

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#11601]
Since yesterday me and some guildies are having a weird bug where we can't attack people in RvR. The enemies are all in attackrange and are also flagged for RvR. At first we thought it was lagrelated and a serverreboot might fix the problem, but after new patch and serverreboot (14.4/2018 patch) we are still experiencing this problem.
We found some workaround: target someone, hit Escape, target the same person again. That will sometimes do the trick.

**Comment by Natherul** [comment]
when you first encouter these things, do you target them initially at a larger distance?

**Comment by wiscel** [comment]
Hey Nath, it's from the video I send to you yesterday.

**Comment by Natherul** [comment]
ah, judging my the text you supplied then I assumed you wanted to report someone aka GM matter...

This is from the detarget system from 2 weeks ago, seems I need to increase the range, will be fixed in the next update

**Comment by Natherul** [comment]
as a small sidenote this happened as I tested on my local the max range but I was only checking in a plane field. If you are elevated then the distance that you see it further. Not sure how to test to find the best values but it is increased in the next patch

**Comment by Natherul** [comment]
should be sorted with hotfix that was deployed now
