### ISSUE TITLE
Quest: Searching For Answers is showing completed when it needs to be obtained.

### ISSUE THREAD

**Issue by mattander83** [WarEmu/WarBugs#11605]
The next step in Searching For Answers appears to be completed when it still needs to be obtained.

Complete the quest up until you need to slay 20 Blackfoot Bruisa.  Don’t take that quest.  The Scouts still show the previous quest is completed, even after turning that quest in.  Side note, they are all laying down with non hostile Blackwood Bruisa’s around them.

![df946970-8980-45f0-9ad4-ddf01bd2f865](https://user-images.githubusercontent.com/31325974/38768435-cf2a3d88-3fc1-11e8-90af-c19ea9cb9863.jpeg)
![aa015af6-42a1-4aad-8cfa-3a0c21561464](https://user-images.githubusercontent.com/31325974/38768436-cf45d516-3fc1-11e8-8dd0-840f19d3da35.jpeg)
![6bc132a4-fc17-4f0d-b9ba-2a1a993dac81](https://user-images.githubusercontent.com/31325974/38768437-cf582194-3fc1-11e8-8617-4fc55704dd55.jpeg)
![9808b27f-e677-437e-b904-3bb648b0b2ab](https://user-images.githubusercontent.com/31325974/38768438-cf67d9ae-3fc1-11e8-9715-f9f191b2f7dc.jpeg)

**Comment by sioding** [comment]
Thats because you have have to have spoken on the first step to the Eataine Scout. Nothin we can fix now.
