### ISSUE TITLE
Potent Enchantments Tactic [SM] has no Modifier

### ISSUE THREAD

**Issue by Ramasee** [WarEmu/WarBugs#11611]
Expected behavior and actual behavior:
Potent Enchantments receives no bonus damage from any source. Other DoT tactics such as Encorselled Agony and Deep Incisions have bonuses to their damage from strength.

Steps to reproduce the problem:
Equip anything you want, the damage will not increase tooltip or actual.

*Side note* Centuries of Training has no modifier as well. But that one is an elf tactic shared by all 4 elven classes.

**Comment by sioding** [comment]
screenshots with your testst please.

**Comment by Ramasee** [comment]
![51dps-cot](https://user-images.githubusercontent.com/18507595/38783176-e39c0e70-40cc-11e8-9f55-67a9ad0ed2a2.jpg)
![51dps-di](https://user-images.githubusercontent.com/18507595/38783177-e4505b78-40cc-11e8-9915-0588c96dad5e.jpg)
![51dps-ea](https://user-images.githubusercontent.com/18507595/38783178-e50df2aa-40cc-11e8-9bc9-b419f0edea34.jpg)
![51dps-pe](https://user-images.githubusercontent.com/18507595/38783180-e8d0662a-40cc-11e8-970f-675985aa1691.jpg)
![61str-cot](https://user-images.githubusercontent.com/18507595/38783181-e977bc5e-40cc-11e8-9851-7f0fe1a854bd.jpg)
![61str-di](https://user-images.githubusercontent.com/18507595/38783182-e9b51392-40cc-11e8-860a-ec4c764bb66f.jpg)
![61str-ea](https://user-images.githubusercontent.com/18507595/38783183-e9fddb40-40cc-11e8-97b7-44a3fbd410d0.jpg)
![61str-pe](https://user-images.githubusercontent.com/18507595/38783184-ea13e174-40cc-11e8-9466-96b141918e18.jpg)
![base-cot](https://user-images.githubusercontent.com/18507595/38783185-ea44b2cc-40cc-11e8-89f1-9d0d2d81e45f.jpg)
![base-di](https://user-images.githubusercontent.com/18507595/38783186-eb11a714-40cc-11e8-8351-3f7da679d9e5.jpg)
![base-ea](https://user-images.githubusercontent.com/18507595/38783187-ebf65d0a-40cc-11e8-9afc-25ec51ee19ad.jpg)
![base-pe](https://user-images.githubusercontent.com/18507595/38783190-f33a3e10-40cc-11e8-9eb2-1fd9162e5618.jpg)

**Comment by sioding** [comment]
Thx @Q73px
