### ISSUE TITLE
BV phase in Ground

### ISSUE THREAD

**Issue by Killerstem** [WarEmu/WarBugs#11613]
In Barrak Varr 
next to Keep down near beach u can phase into the ground and drop out underground in water
 you start to jump bout where the bug is if you run facing keep 
there is a like a little hole in the ground  and if you run in it facing keep you will phase in
https://i.imgur.com/gSSU6HW.jpg
https://i.imgur.com/rMVF1JJ.jpg

**Comment by NorKalli** [comment]
![image](https://user-images.githubusercontent.com/19868634/39346411-de84e87e-49a2-11e8-958b-bc67105018a6.png)

Will add fix pending lable and close as soon as I figure out how.

**Comment by sioding** [comment]
fixed with patch from 05.05.2018
