### ISSUE TITLE
Dwarf Tier 10 Influence Reward

### ISSUE THREAD

**Issue by Aldmhac** [WarEmu/WarBugs#11618]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: Expected behavior is to be able to claim an influence reward after completing the the influence bar/ maxing out the influence for the particular chapter. Actual behavior is not allowing me to select an influence reward. The "boxes" / options when visiting the rally master are blank/ unable to be selected (see attached screenshot).

Steps to reproduce the problem: I changed zones, logged in and out to attempt to solve the issue and I am unfortunately still unable to collect the reward. 

Screenshots/Videos or archive.org evidences:
![dwarf chapter 10](https://user-images.githubusercontent.com/37214345/38811748-6129e278-4158-11e8-8cfe-df4e2233523b.png)

**Comment by sioding** [comment]
Just go to the rally master in mashes of madness. We know that´s a problem but this isn´t fixable atm.

**Comment by Aldmhac** [comment]
Unable I select chapter 10 influence rewards there either
