### ISSUE TITLE
Quest: As Lord Tzchar'Zanek Demands : First Mission - Missing Empire Courier

### ISSUE THREAD

**Issue by Telenfynddar** [WarEmu/WarBugs#11623]
Aim: Kill 25 Enemies/Gather information from Empire Courier

The needed Courier, normally infront of the Tavern in RVR HighPass, is not on his place. Only a dead Chaos Corpse lies on the ground. So now continuation of the quest possible.

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 20.4.2018
