### ISSUE TITLE
Talabec dam scenario stuck on the fence

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11627]
after a bump you get stuck on the fence and can't do nothing. You are inside the fence near order drop point
![thorbolt_182](https://user-images.githubusercontent.com/16274785/38941850-bd79413c-432d-11e8-9191-8b02244e4ad5.jpg)

**Comment by NorKalli** [comment]
invisible walls placed

**Comment by sioding** [comment]
Fixed with Hotfix from 29.04.2017
