### ISSUE TITLE
Quest: An opportunity for glory [Shadowlands]

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#11628]
Deadwoven marauders required for the quest are missing

![sheykis_017](https://user-images.githubusercontent.com/18032193/39011665-66445d94-4412-11e8-89d5-3d0a90607f1d.jpg)

**Comment by sioding** [comment]
Hm - they are available:
![image](https://user-images.githubusercontent.com/18517842/39014328-5859c6a8-441a-11e8-9db1-571c64692c96.png)
And the questmarker is fine too.

**Comment by szejoza** [comment]
must have been bugged when I was doing it then (was about 2 weeks ago) as Im 100% positive they weren't there

Cheers

**Comment by sioding** [comment]
They are part of a PQ - sometimes the PQ doesn´t load the NPCs - we know that problem but have no fix for it
