### ISSUE TITLE
Tis Only A Flesh Wound quest in Ostland

### ISSUE THREAD

**Issue by warwalker** [WarEmu/WarBugs#11622]
dead marauders by Thridi Valhal are not working for collecting heads.

Expected behavior and actual behavior:
click on dead marauders lying on ground to get credit for Collect 5 heads.
they were working not long ago when playing another alt, but have stopped working. Cannot complete Missing Maiden quest line for 1st Anniversary cloak without this quest.

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 20.4.2018
