### ISSUE TITLE
Quest: Shield of the Squig [Badlands]

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#11639]
Can't really progress with the quest. No info in ToK. Quest giver icon turn orange when you pick up quest suggesting it could be completed but there is no more info of what to do
![sheykis_030](https://user-images.githubusercontent.com/18032193/39013209-fec88e92-4416-11e8-86d3-835d6f953c44.jpg)

**Comment by sioding** [comment]
![image](https://user-images.githubusercontent.com/18517842/39082805-3e6a42dc-4559-11e8-8c00-746fae87114b.png)
Not reproducable
