### ISSUE TITLE
Quest: Heart of Chaos [Black Crag]

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#11634]
Missing NPC for Bloody Sun Killa Feet
![sheykis_023](https://user-images.githubusercontent.com/18032193/39012836-d689ad2c-4415-11e8-982b-3a40ceaa2896.jpg)

**Comment by sioding** [comment]
Hm Bloody Sun Killa are part of the ch22 hard PQ.

**Comment by szejoza** [comment]
Ah, okay, I know what was wrong here, mobs in that area were stupidly strong (tons of HP, hitting hard)

**Comment by sioding** [comment]
fixed with patch from 20.4.2018
