### ISSUE TITLE
Quest: Overwhelming odds [no zone in ToK]

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#11638]
According to description it should be located in Badlands/Gunbad but the NPC for quest is missing
![sheykis_029](https://user-images.githubusercontent.com/18032193/39013159-d62689bc-4416-11e8-9841-fe42f094aeb2.jpg)

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
Patched with hotfix on 22.04.2018
