### ISSUE TITLE
Quest: Mourkain Crystal [no zone in ToK]

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#11637]
NPC missing/not reacting for turn in. Hard to locate as information in ToK are incomplete
![sheykis_027](https://user-images.githubusercontent.com/18032193/39013050-7b1bf958-4416-11e8-8396-2f044fd1a97a.jpg)
![sheykis_028](https://user-images.githubusercontent.com/18032193/39013065-867987fc-4416-11e8-8628-cc69bb1deff9.jpg)

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
Patched with hotfix on 22.04.2018
