### ISSUE TITLE
Quest: Into the Depths [Badlands/Gunbad]

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#11636]
NPC missing for quest turn in
![sheykis_026](https://user-images.githubusercontent.com/18032193/39012980-47e18a6c-4416-11e8-8769-bf26c3c46d1d.jpg)

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
Patched with hotfix on 22.04.2018
