### ISSUE TITLE
Quest: Hidden Talons [Blighted Isle]

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#11635]
Finishable but NPC are for sure not in the marked area (I have no idea where I got these 2 kills, must have been somewhere in elf zones though)
![sheykis_025](https://user-images.githubusercontent.com/18032193/39012895-0ffa55e8-4416-11e8-9a82-2844c59f6d59.jpg)

**Comment by sioding** [comment]
Sorry this quest was fixed by me last patch. Please abbandon it and start again. the questmarker and the drops are working fine
