### ISSUE TITLE
Quest: Clearing the Way [Ellyrion/Avelorn]

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#11632]
NPC in the quest description isn't working as a NPC to turn in quest
![sheykis_021](https://user-images.githubusercontent.com/18032193/39012262-4286fae0-4414-11e8-9a36-968704465a5c.jpg)

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 20.4.2018
