### ISSUE TITLE
T2 human rvr kinschel's stronghold you can tag the BO if you stand at the top of the tower

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11646]
You can tag the BO if you stand at the top of the tower (the tower just in front of the character)

![thorbolt_184](https://user-images.githubusercontent.com/16274785/39084165-3dc3c98a-4571-11e8-8dae-0b674d8a5e65.jpg)

**Comment by sioding** [comment]
Well @thorbolt80 i don´t see a bug. Yes you can stand on the tower - and yes you will tap the BO. Hard to get those ppl if you are a mdps/heal/tank but fine if you are a rdps. This was fine on live - and its here too. So sorry - no change.
