### ISSUE TITLE
Quest: The Final Assault - Daelerys Strike [Caledor]

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#11641]
One of the 4 quests with the tower defense but for this one there is no mobs to kill therefore unable to complete.

![sheykis_034](https://user-images.githubusercontent.com/18032193/39013389-8e3146dc-4417-11e8-8920-b535afe9c6a3.jpg)

**Comment by sioding** [comment]
This is again a chapter 22 hard PQ thing. In order not to have the problem in future i changed the quest to another object and adjusted the questdescription. fixed with next patch

**Comment by sioding** [comment]
Patched with hotfix on 22.04.2018
