### ISSUE TITLE
Quest: The Grudges of Karak Drazh! [Black Crag]

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#11642]
No mob to kill for quest in the marked area and near vicinity

![sheykis_035](https://user-images.githubusercontent.com/18032193/39013503-d90eb2e8-4417-11e8-8e60-af5f351dee31.jpg)

**Comment by Sinrman** [comment]
This quest is active.  The Particulars Section is incorrect. The Map marker is correct and the named mob is Flayskin Eadcarver. 
![gunnr_000](https://user-images.githubusercontent.com/42098334/46573249-2cc1bf00-c958-11e8-9215-2c2a28431000.jpg)
![gunnr_001](https://user-images.githubusercontent.com/42098334/46573253-38ad8100-c958-11e8-85de-216f70b084f1.jpg)

**Comment by Sinrman** [comment]
The Particulars Section of the tome entry is incorrect. Killing/looting Speezy will not complete quest. The Map marker is correct but Speezy is not there. The named mob should be Flayskin Edcarver. You have to kill/loot him quick because the Muck Pen PQ mobs attack and kill him.

**Comment by Lheana** [comment]
Speezy will now drop the item needed for the quest. Also corrected the quest marker.

**Comment by Lheana** [comment]
Fixed with patch from 21.10.2018

**Comment by Lheana** [comment]
Fixed with patch from 21.10.2018
