### ISSUE TITLE
Quest: Steeped in Filth [no zone in ToK]

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#11640]
Description says Gunbad, but NPC is missing
![sheykis_031](https://user-images.githubusercontent.com/18032193/39013299-3db03308-4417-11e8-9e7d-8cb0753a6ae1.jpg)

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
Patched with hotfix on 22.04.2018
