### ISSUE TITLE
Quest: What Separates Us [Isle of the Dead/Dragonwake]

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#11643]
Mobs are scattered through zone, not necessarily in the marked area, but even after killing them it is not possible to progress with the quest as there is no object/NPC to turn in this step

![sheykis_037](https://user-images.githubusercontent.com/18032193/39013692-6ba484e8-4418-11e8-8234-77e8bb6f3819.jpg)

**Comment by sioding** [comment]
![image](https://user-images.githubusercontent.com/18517842/39083123-783ff032-455f-11e8-97f8-433d058826bf.png)
i can finish the step and have a questmarker to hand it in
sorry could not reproduce
