### ISSUE TITLE
Eataine RvR Quests

### ISSUE THREAD

**Issue by Aldmhac** [WarEmu/WarBugs#11645]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: Expected Behavior is for the red completed map icon to not pop up when first accepting a quest. Actual Behavior: red completed map icon popped up upon accepting the "Solemn Defense of Eataine" and "Securing the Front" quests in Eataine.

Steps to reproduce the problem: Visit Eataine warcamp and speak to Lanril Elderborn.

Screenshots/Videos or archive.org evidences:

![eataine](https://user-images.githubusercontent.com/37214345/39067322-416e91f8-44a6-11e8-9929-45decdefd8c0.png)

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
Patched with hotfix on 22.04.2018
