### ISSUE TITLE
Zealot: Devastor 4 piece bonus "Vivacious" not working

### ISSUE THREAD

**Issue by sorclose** [WarEmu/WarBugs#11658]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Should - On heal 10% chance to regain 50AP
Actual effect - none

I first thought that the buff icon simply does not work/show up - ain't sure about that yet
Could only trigger on wounds restored, if it is not an overheal?(would be the only skill behaving like that I know of)

Steps to reproduce the problem:
I tried to cover every way to reproduce the "On heal..." requirment (tested in rvr/sc/pve)

Test's:
- healing myself as def-target/other player in group (same for being healed by a player)
- healing out of grp

No effect whatsoever! 
.. at least with the limited data of the client

Screenshots/Videos or archive.org evidences:
https://youtu.be/SLcS4Txm894

PS: first post on the bugtracker - sorry for any uncalled for part or further required but missing data
Edit: Added the video link

**Comment by cimator** [comment]
You can see here that it works; https://youtu.be/TgLNYwjdaSw , BUT it procs only on direct healing, I think HoT ticks should be included aswell, as it doesn't specify whether it should be direct or not.

**Comment by sorclose** [comment]
Hello, pardon me for the lack of evidence and thanks for replies! 
I made a video https://youtu.be/SLcS4Txm894
No proc -> and seeing how fast it triggers in cimators video, hope this is proof enough^^
I un-/reequipped tactics - thought it might be "Restorative Burst" 's procs that is causing the issue.

**Comment by cimator** [comment]
@sorclose I did see it proc on your video aswell at 1:09, you are at 215 ap, you use Flash of chaos(15 cost) and you are at 250 ap instead of 200. I think you were expecting some kinda buff on you, but its an instant proc. You can check it only by looking at your ap bar, or use wsct addon to show the ap gain(you can see the +50 on my vid)

**Comment by sorclose** [comment]
You are right - I thought it was the buff icon for the setproc in your vid. Thanks.
I had the suspicion, that there simply is no indicator for the proc. Is it not shown cause there is no limitation -> a.e. Effect triggers only once every 5 sec - ) ?

I put the ap gain that you pointed out at 1:09 into the "out of combat" bucket.. so hard to check this particular proc -.-
Does this apply to every effect triggering on chance only and not any further limitation like a cooldown?


Please excuse the unnecessary report and thanks  for clarification.

Regards!

**Comment by sioding** [comment]
aaaand close cause no bug at all. again: thx @cimator
