### ISSUE TITLE
Cleansing an Empire - Order T3 Empire Quest

### ISSUE THREAD

**Issue by mastersmok** [WarEmu/WarBugs#11650]
**Expected behavior and actual behavior:**
After grabbing the quest, the first part asks you to scout an area near a PQ. What you should do for the part is click on an Empire corpse. There are corpses littered across the PQ area, but none of them are clickable to advance the quest.

**Steps to reproduce the problem:**
Start quest "Cleansing an Empire" in High Pass at Chapter 10. Speak to Gerard Cammen. Try to complete the very first step, unable to click on any corpses in the designated area to advance the quest.

**Comment by sioding** [comment]
The corpse was a bit outside the questmarker area. it is fixed with the next patch

**Comment by sioding** [comment]
Patched with hotfix on 22.04.2018
