### ISSUE TITLE
Praag Quest Ancient Power Reborn finding Black Sword Shard

### ISSUE THREAD

**Issue by Pearlpetalbee** [WarEmu/WarBugs#11651]
Praag Quest Ancient Power Reborn at Chaos Chapter 18, to find Black Sword Shardx3. The map tracker red circle showing 50K, 22K. But there is no Shard in red circle area. There is a shard at 55K 38K (outside red circle map tracker) at the hill near a building. Click it 3 times and the quest is completed.

**Comment by sioding** [comment]
questmarker fixed with next patch

**Comment by sioding** [comment]
Patched with hotfix on 22.04.2018
