### ISSUE TITLE
2018/04/23 hotfix seems to have broken AoE of Sticky Squigs and Whirling Pin

### ISSUE THREAD

**Issue by DanskuL** [WarEmu/WarBugs#11659]
Expected behavior and actual behavior:
Expected
You apply a slow to everyone in a AoE around you and knock yourself backwards.

Actual
Doesn't apply any slow, nor does it knock you back, the AoE calculation seems to be the issue

Edit
After more input from Tallon and Vaelatrix it seems to only bug if you enter a SC.
And seems to apply to WL pounce as well. (don't have one to try with for video proof so if someone else can confirm this with a video it would be great.)

Seems to affect WH and WE's as well.

Steps to reproduce the problem:
use the ability to disengage from any enemy,

Screenshots/Videos or archive.org evidences:

VIDEO:
https://streamable.com/t038y

6 mins of video proof.

Seems like if you join a SC it stops working.

**Comment by DanskuL** [comment]
https://streamable.com/t038y

 6 mins of video proof.

Seems like if you RvR enable yourself it stops working.

**Comment by NabaroNya** [comment]
I confirm. seems all jump abilities broken - WH, WE, WL, SH and SW. For hour I play SC, "Declare Anathema" never worked how should(only stagger - no jump).

**Comment by DanskuL** [comment]
Tried it in ORvR, it's seems to not set the boolean when you're in air back to false when you land.

**Comment by Natherul** [comment]
should be fixed as of hotfix this morning.
