### ISSUE TITLE
Crashing while near Tavern in quick succession, happened to me two times in a row while in RvR.

### ISSUE THREAD

**Issue by Urtel1** [WarEmu/WarBugs#11654]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
I expect that it doesn't crash and it crashed.

Steps to reproduce the problem:
I was defending the Tavern when around 3 WB's came through and wiped us and as soon as I died my game crashed as well but it also happened to me when I didn't die but just completely randomly while defending tavern

Screenshots/Videos or archive.org evidences:
I don't have any screenshots/videos due to me not recording gameplay :/ I'm sorry but I promise I'm sincere. I went to ask other people and it appears to be new but also pretty common 3 other people said they experienced crashing while near the tavern.

**Comment by sioding** [comment]
Thanks for the report - but its nothing we can do here. Please follow these thread https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=20075
