### ISSUE TITLE
Enduring Flaming Blast Potion not working

### ISSUE THREAD

**Issue by lijebin** [WarEmu/WarBugs#11652]
enduring flaming blast potion i right click nothing happen

![winford_011](https://user-images.githubusercontent.com/17027595/39091972-79f81f38-4633-11e8-9aaf-16e6460241cc.jpg)

**Comment by Kaelang** [comment]
![image](https://user-images.githubusercontent.com/60117106/82151133-37417b80-9852-11ea-82f5-f50e66b5b70e.png)

Working as intended.
