### ISSUE TITLE
Bug with RR in Eataine

### ISSUE THREAD

**Issue by Ulanna** [WarEmu/WarBugs#11656]
On Saturday, at the rvr in Eataine (Chillwind Manor), I got about 12 lvl rr from the bug (originally I had 52 rr lvl and ~ 15%) . After server reboot i still got 64 rr and 74% left. Could you fix this?
nickname: Malleuss
![230418](https://user-images.githubusercontent.com/32061114/39119559-d60de4b2-46f4-11e8-8613-a624c2403624.JPG)

**Comment by NabaroNya** [comment]
Hi, I have the same. Seems the DB rollback did not help. I got ~3 rr levels (61-64) on my WH (Triv) when standing on BO in Eataine.

**Comment by Natherul** [comment]
we have had some hotfixes and now we have not seen this happening again. If it happens again please open a new ticket. For now this seems resolved.
