### ISSUE TITLE
Praag Binding

### ISSUE THREAD

**Issue by Zyndell** [WarEmu/WarBugs#11653]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Trying to set bind point in Praag warcamp.  Bind point gets set for CW warcamp instead,

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Its a known issue we can not fix atm.
Please use the rally master inside the house for your bind in praag:
![image](https://user-images.githubusercontent.com/18517842/39265501-b48da0c8-48c7-11e8-9916-fe191ab61a85.png)
