### ISSUE TITLE
Ekrund Destro WC Mailbox

### ISSUE THREAD

**Issue by ferraz19** [WarEmu/WarBugs#11657]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Mailbox doesn't open when it should be working :D

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![vyel_001](https://user-images.githubusercontent.com/30166423/39122559-4bcc8802-46c3-11e8-80ef-265b54350d62.jpg)

**Comment by sioding** [comment]
Hm where did you found it ? Checked all mailboxes in Ekrund and they work fine. Can you add a map screenshot?

**Comment by sioding** [comment]
Fixed with Hotfix from 29.04.2017
