### ISSUE TITLE
BO Savin Me Hide

### ISSUE THREAD

**Issue by deathkylem** [WarEmu/WarBugs#11669]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: Big bug with this skill, the skill must buff tougnes for BO during 20 sec and 4 sec 20%magic reduction for all groupmates for 4 sec. Now the skill buff tougness and 20% magic reduction during 20 sec (not 4) for BO and 4 sec for all groupmates.

Steps to reproduce the problem: Was tested with 2 friends, Andoni (am dps) and Dalin (rune dps). I used Da biggest to buff me tougness(99) and see damage, after that we test with Saving me Hide that buff me 108 tougness+20% damage (in the middle of the buff timing not at early)
Andoni->Searing Touch 614 vs Searing Touch 468 +- 20%
Dalin-> Rune of Fire 398 vs Rune of Fire 318 +- 20%

The skill musnt work like this, is a BIG BUFF for BO because the skill hasnt got CD and no need spend all best plans to take the reduction up all the time.

Screenshots/Videos or archive.org evidences:

**Comment by deathkylem** [comment]
This is my first post here...sorry if is not wrtting good. TY =)

**Comment by sioding** [comment]
Can you please add your testing screenshots?

**Comment by deathkylem** [comment]
Dont know how to post via internet screens but if anyone have discord or hotmail can send you screenshots ofc

**Comment by GK111** [comment]
![fhkf](https://user-images.githubusercontent.com/24727277/39228130-0b064e72-4865-11e8-8d2c-8bc4692b40dc.png)

**Comment by deathkylem** [comment]
Not more to say...confirmation then ty GK111

**Comment by sioding** [comment]
Fixed with Hotfix from 29.04.2017
