### ISSUE TITLE
bug furie 

### ISSUE THREAD

**Issue by cececeliana** [WarEmu/WarBugs#11666]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

good evening, I play my fury tonight and I see that the spell '' agile evasion '' no longer works, it is no longer possible to jump back, well to you, celiana

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by DanskuL** [comment]
seems related to #11659 (as I guess Furie is Witch Elf)

**Comment by sioding** [comment]
Duplicate of #11659
