### ISSUE TITLE
Quest: Dogs of War [Altdorf]

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#11660]
No interactable object/NPC in Blowhole tavern in Altdorf
![sheykis_041](https://user-images.githubusercontent.com/18032193/39147934-40c2d7ea-473b-11e8-909b-8cdac8ffd5e2.jpg)
![sheykis_042](https://user-images.githubusercontent.com/18032193/39147935-40de9e44-473b-11e8-851b-0a3960ea74cc.jpg)

**Comment by sioding** [comment]
Sorry the questobject is on his place:
![image](https://user-images.githubusercontent.com/18517842/39266063-37f168d6-48c9-11e8-9848-c224bab70ad7.png)
