### ISSUE TITLE
Shaman: Sticky Feetz doesn't work (in IC)

### ISSUE THREAD

**Issue by Tyramissoux** [WarEmu/WarBugs#1166]
No animation, no effect. Correct cooldown.

**Comment by Zzeppenn** [comment]
Just tested, it does work, but aoe animation is invisible.

**Comment by Tyramissoux** [comment]
Had it tested in IC - no reaction from the mobs.

**Comment by Zzeppenn** [comment]
It works on players, same with Mistrees of the Marsh, no animation but affects players.

**Comment by Tyramissoux** [comment]
Mistress of the Marsh is a different story. Debuff lasted extremely long (in oRVR). Definitely longer than the area. Had to despell it for normal movement speed.

**Comment by Zzeppenn** [comment]
Not sure, but now it's more like an AoE spell that you cast on players, not on the ground itself as it should be.

**Comment by ozarmidrashim** [comment]
IC has positional issues; for some reason there's an exception which adds a large Z value to worldpositions calculated in IC. Will experiment with removal.

Issue with MotM also affects SF and every other aura in the game. Fix soon.

**Comment by Evildoor** [comment]
Seems like a bunch of resolved/reported elsewhere issues to me. Height issues in IC (although there is some new info on this point, at least to me), ground target AoE failing if cast out of range, debuffs persisting indefinitely. Seen SF/MotM in action many times. Closing.
