### ISSUE TITLE
Mail system hybrid mats undeliverable

### ISSUE THREAD

**Issue by NimeriaNim** [WarEmu/WarBugs#11667]
For some reason I am not able to send my alt hybrid mats. The subject/message lines are correctly filled out, but when I click send nothing happens.

**Comment by sioding** [comment]
Screenshot please. And remember not to filter out the system messages. Thanks

**Comment by NimeriaNim** [comment]
For some reason it's working today. Yesterday I was sending two messages with attachments to my alt, and the second message had the hybrid mats attached, and wasn't allowing my to send them. So, that's why I thought there was issue with the hybrid mats being deliverable.
