### ISSUE TITLE
Altar of Madness PQ Boss Not Resetting

### ISSUE THREAD

**Issue by Aldmhac** [WarEmu/WarBugs#11678]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: Expected behavior is for the quest to reset after it has failed. Actual behavior, quest does not completely reset after the quest has failed. My partner and I failed the PQ at stage 2. Once the PQ said we had failed, the final boss popped up as well as the Tome of Knowledge saying that we had "completed the Public Quest Alter of Madness" with a three minute "resetting" timer. After the three minutes completed, and the PQ fully reset itself, the boss stuck around as seen in the screenshot.

Steps to reproduce the problem: Possibly fail the public quest "Alter of Madness" at stage two. Unfortunately I was unable to kill the bugged boss to progress to stage 2/3 to see if we could reproduce the issue.
![alter of madness](https://user-images.githubusercontent.com/37214345/39276512-4b7cbc3c-48b7-11e8-92a7-d3b2e40c1724.png)

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Tried different stages on the testserverand stand there a lot to let them fail but i was not able to reproduce that.
