### ISSUE TITLE
bright wizard cooldown  flame shield and flame of ruin 45 sec

### ISSUE THREAD

**Issue by lijebin** [WarEmu/WarBugs#11670]
it say no cooldown but got 45 sec or that not a bug it doesn't happen on live 
![winford_013](https://user-images.githubusercontent.com/17027595/39192652-409cdce4-480c-11e8-8b3a-c97a30bb9d74.jpg)

**Comment by lijebin** [comment]
![winford_014](https://user-images.githubusercontent.com/17027595/39192685-560415fc-480c-11e8-90fa-93890bdf9759.jpg)

**Comment by lijebin** [comment]
![winford_015](https://user-images.githubusercontent.com/17027595/39192706-632edd02-480c-11e8-9be4-7bbcd9ee872e.jpg)

**Comment by sioding** [comment]
No bug - working as intended
