### ISSUE TITLE
Mail Undeliverable 

### ISSUE THREAD

**Issue by NimeriaNim** [WarEmu/WarBugs#11674]
I'm not able to send my alt mats for some reason. Sometimes it works when I log in at first, but it only worked once today, and now I can't send my alts anything in the mail. Not sure what's going on. I'm filling out all of the proper lines in the mail. 
![fatbikerchicks_001](https://user-images.githubusercontent.com/38672066/39217743-553a7994-47ef-11e8-8fd0-e8b9845b2986.jpg)

**Comment by sioding** [comment]
As you see yourself - no errormessage given means we are not able to reproduce it. We know this "problem" but can not fix it this way. please try it agin later on - it will work. (relogging sould help sometimes)
