### ISSUE TITLE
bug epic quest

### ISSUE THREAD

**Issue by panpiedra** [WarEmu/WarBugs#11676]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

The epic quest ancient horror, of order in t3 badlands, have a bug and it cant be finished.

Steps to reproduce the problem:

In the part of need to observe the stone plinth you need a spyglasses to do that and the anyone give it to you a spyglasses. sorry for my bad english.
Thankyou

Screenshots/Videos or archive.org evidences:
![rograk_000](https://user-images.githubusercontent.com/38721732/39240344-c6f35a3a-4883-11e8-8d3c-27e2450d1115.jpg)

**Comment by szejoza** [comment]
iirc there are clickable spyglasses if you follow the road to the east, they should be somewhere on your left

**Comment by sioding** [comment]
Is the questmarker missing @panpiedra  ?

**Comment by sioding** [comment]
Checked that. Questmarker is fine and questobject is also inside and working fine.
Close
![image](https://user-images.githubusercontent.com/18517842/39540828-2506dc80-4e44-11e8-983f-e6f392e5ab9f.png)
