### ISSUE TITLE
BG (ability) Enraged Beating 

### ISSUE THREAD

**Issue by IMHAPPYTODAY** [WarEmu/WarBugs#11675]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
The ability from the tree Path of malice (enraged beating) can be obtained at lvl 19
BUT the skill it self cant be used untill your level 21

Steps to reproduce the problem:
Change the abilty lvl without redusing base damage

Screenshots/Videos or archive.org evidences:

Hope that helps

**Comment by sioding** [comment]
I do not have a clue whats ment in this report. @IMHAPPYTODAY  could you please add more context?

**Comment by Torquemadra** [comment]
the skill can be used, it just gives a message
