### ISSUE TITLE
Crash in Altdorf

### ISSUE THREAD

**Issue by Eversoris** [WarEmu/WarBugs#11682]
gmorning.

Game client crash near NPC scenario in Altdorf. It does crash talking to him, walking or running close.

Can't provide any screen since it does crash and closes game itself.

**Comment by sioding** [comment]
Thanks for the report - but nothing we can do here. Please follow the suggestions in this Thread: https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=20075

**Comment by Eversoris** [comment]
It never happened before and I'm playing in RoR since 2016 if I reckon. Some people talking in advice channel about crashing in Altdorf today, just today started. That's why I decided to create an account here in github and do bugtracker report.

Not sure if its server side or some addon that happen to crash, but it wasnt me alone. Nothing related with graphic card, settings or something else. RoR happened to work perfect to me except on big fights which fps drop insane but that's normal.

Hope I can help reporting more bugs (the less report means no bugs at all) =)
