### ISSUE TITLE
T4 Empire Epic quest "Faith is Madness" last part

### ISSUE THREAD

**Issue by Panzarpaddan** [WarEmu/WarBugs#11683]
Expected behavior and actual behavior: The mob "The Dakrness" is supposed to spawn in the middle of the room. Or you get the key and then enter the portal to get to him. Have tried click the keys and take the portal. This leads to a 43 Hero Herald of Tzeentch because of the Onslaught PQ.

The last part of the quest is uncompletable.

Steps to reproduce the problem: Try to go to Ebon Keep and get the last part done.

Screenshots/Videos or archive.org evidences: Talked with GM, shouldn't be needed since the Onslaught is at the same location.

**Comment by MightyPhred** [comment]
same problem here...went looking for a new hammer skin with a guildmate and all we can find is splattery death at the hands of that daemon hero, lol

**Comment by grunbag** [comment]
Mob has been moved . When you face ebon keep entrance from the outside , turn left . The darkness is in the middle of the ruins here

**Comment by sioding** [comment]
grunbag moved the NPC - Questmarker are fine too - seems like fixed in next patch

**Comment by sioding** [comment]
Fixed with Hotfix from 29.04.2017
