### ISSUE TITLE
Quest: Keeping Secrets bugged

### ISSUE THREAD

**Issue by Jeeves-Archibald** [WarEmu/WarBugs#11689]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: The NPC (Moenar Karinth) that needs to be interacted with is lying on the ground and can't be interacted with. There have been two server restarts and the issue persists.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences: https://imgur.com/a/wFihSPm

**Comment by sioding** [comment]
My bad - will be interactable again with next patch

**Comment by sioding** [comment]
#11005

**Comment by sioding** [comment]
fixed with patch from 05.05.2018
