### ISSUE TITLE
bug rampage for killer

### ISSUE THREAD

**Issue by mactatane** [WarEmu/WarBugs#11681]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
for the killer when using rampage in the 25/75% rage it works well and displays 10 seconds of duration, but when used in the 75/100% rage the duration remains at 10 seconds

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Could you please invest some more time than just leave 1 sentence? 
Which class?
You are welcome to add your testing screenshots.
Thanks.

**Comment by sioding** [comment]
No answer since 13 days - close
