### ISSUE TITLE
White rank 9 shoulders + helm Slayer

### ISSUE THREAD

**Issue by Symbelmyne** [WarEmu/WarBugs#11680]
I`ve noticed buyable white rank 9 shoulders and helm for slayer class from Norsca WC vendor are missing talisman slots, unlike same items for other classes. In fact, all white items from rank 1 to at least 17 for slayer class have no talisman slots. I guess its a glitch.

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
