### ISSUE TITLE
Spoils of War - Ironbreaker Tome Unlock

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#11684]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Upon obtaining the "Piece of Gromril Armour" from an Ironbreaker in RVR, you should be able to purchase Six Sided Dice from Disciple Venomstung in the Lyceum in the Inevitable City. The unlock should also register in your Tome of Knowledge.

I have the Piece of Gromril Armour in my currency tab in my backpack now. It is not appearing in the ToK, nor can I use it to purchase this trophy.

Steps to reproduce the problem:

This item needs to be hooked up with the trader to allow players to obtain the Six Sided Dice, and also register in ToK when it has been obtained.

Screenshots/Videos or archive.org evidences:

![ithilsyn_635](https://user-images.githubusercontent.com/22262165/39366660-71fd4702-4a2c-11e8-9e00-819ae65fb2f1.jpg)

![ithilsyn_636](https://user-images.githubusercontent.com/22262165/39366709-9c47b4ac-4a2c-11e8-80fd-bbd84758ac4d.jpg)

**Comment by Lheana** [comment]
#11500
