### ISSUE TITLE
Chaos Unleashed tactic showing critical chance as 0%

### ISSUE THREAD

**Issue by Coffeecakes** [WarEmu/WarBugs#11687]
Expected behavior and actual behavior: It is expected this tactic would not alter the amount of critical strike chance shown on the character screen. Instead it always sets it to 0.

Steps to reproduce the problem: Use the Chaos Unleashed tactic while having critical strike chance from any other source. The value will be now shown as 0% on the character screen.

**Comment by sioding** [comment]
Do we talk about a paperdoll problem? Please add your testing screenshot with .getstat outout.

**Comment by Laurentz18** [comment]
I can confirm this issue on my Magus.

![vocarae_006](https://user-images.githubusercontent.com/36253097/39678600-41ef7c4e-5155-11e8-99d0-23d65c3ffce2.jpg)

**Comment by grunbag** [comment]
Intended , mythic removed t intentionally from stat doll because it only affect path of X abilities and was confusing players .
