### ISSUE TITLE
crafting items don't display and wont add to crafting window

### ISSUE THREAD

**Issue by Cylwen** [WarEmu/WarBugs#11696]
Crafting items do not consistently display.
Items cannot be dragged to crafting window, or generate errors when added to crafting window.

`Item move failed: attempted to move 5 of the item Savage Rugged Debris while only having 1.`

![slekrien_001](https://user-images.githubusercontent.com/38857938/39427682-0e326e7a-4cc8-11e8-86a4-cc26c8c381df.jpg)
![slekrien_002](https://user-images.githubusercontent.com/38857938/39427703-20fdd878-4cc8-11e8-8995-6bfbabb9bb0a.jpg)

See #2427 and also #1548 and #2817 and #4118 and #4417

Like #6481 I think this happened due to crafting at the time of a server crash.

I also had the flickering craft items problem (#5654) which was resolved by transferring to main backpack, and back again, the items tended to be hidden after that (see screenshots).

I also tried the solutions on #7264 which did not work.

**Comment by sioding** [comment]
Thanks for for the report. Since you referenced the existing tickets on your own i can close this one. Its no to let you know you report isn´t important but it won´t help to create a new one if there is an existing one open with the same problem.
