### ISSUE TITLE
Gift of Savagery should ignore toughness

### ISSUE THREAD

**Issue by Toldavf** [WarEmu/WarBugs#11698]
On live it was a proc and so ignored toughness, here it doesn't

several screen shots from live

![khorlar_001](https://user-images.githubusercontent.com/13355649/39457943-218345dc-4ce9-11e8-959c-8c90c8f2848f.jpg)
![khorlar_004](https://user-images.githubusercontent.com/13355649/39457956-31971e26-4ce9-11e8-8f5e-23299deded88.jpg)
![khorlar_002](https://user-images.githubusercontent.com/13355649/39457983-559103e6-4ce9-11e8-95c6-761e4c7b21d1.jpg)

**Comment by grunbag** [comment]
Fixed already
