### ISSUE TITLE
[Quest] [Chaos] Ch. 22 quest "Press the Attack" not working, no marker

### ISSUE THREAD

**Issue by lennip** [WarEmu/WarBugs#11693]
Chaos chapter 22 quest "Press the Attack" is not working and has several problems.
![mutty_006](https://user-images.githubusercontent.com/2891053/39409532-25dda024-4be9-11e8-841f-e2ea87748732.jpg)

1 - There is no marker on the map
2 - The first objective is to use Hellcannons to kill Bladesingers on the elf boats. There are indeed "Silversong Bladesingers" on the boats that are on the river below the Ch. 22 camp, but killing them has no effect and does not count for the quest objective.
![mutty_009](https://user-images.githubusercontent.com/2891053/39409591-04ce9784-4bea-11e8-9535-d77e1ead93f0.jpg)

Not to mention it is quite painstaking to actually kill them, due to the fact that they are on a boat in the middle of the river (it's not possible to target them from the water near the boats) and the cannons won't kill them, just hit them and make them run towards you...

3 - The other objective is to set fire to the Reiksguard peasant huts using the lanterns and kill the peasants. However, near The Fields of Reikland PQ where the huts and peasants are, the lanterns near the huts are not interactable, and killing the peasants has no effect on quest progress.
![mutty_019](https://user-images.githubusercontent.com/2891053/39409744-d862dcc0-4bec-11e8-83fc-e00968377057.jpg)

**Comment by sioding** [comment]
Questmarkers are fixed. The lamps are now counting. If you activate the lamps - pleasants will spawn und you have to kill them too. ATM we are not able to make you shoot at the boat - even when its now targetable. until this is fixed you have to kill 5 baldesingers onboard of the boats. the hellcannons work now.  fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 05.05.2018
