### ISSUE TITLE
[Quest] [Chaos] Ch. 22 Quest Brush of Wings not working properly

### ISSUE THREAD

**Issue by lennip2** [WarEmu/WarBugs#11690]
Hi, 
Chaos chapter 22 quest "Brush of Wings" cannot be completed and has several problems:
1 - There is no quest marker on the map
![mutty_001](https://user-images.githubusercontent.com/38103240/39409213-5a88a2ac-4be3-11e8-87f8-fd5cffb5def4.jpg)

2 - The same objective "Kill Reisguard Patrol" is repeated twice with different numbers
![mutty_002](https://user-images.githubusercontent.com/38103240/39409215-6dda40ea-4be3-11e8-84df-e672406d9116.jpg)

3 - The last objective is to kill some Reikland Militia, however, no NPC in the area have that name. There are Reikland Militiamen, but killing them does not count for the quest.
I searched everywhere in the chapter 22 area and Reiksguard castle, and killed about every NPC with a name like "Reikland something" and none of them trigger quest progress.

**Comment by sioding** [comment]
Fixed with patch from 18.09.2018
