### ISSUE TITLE
[Marauder] 5 point mastery skills not dealing correct damage

### ISSUE THREAD

**Issue by Jaycub** [WarEmu/WarBugs#1169]
Tool tip damage on Guillotine is 415 damage, yet it only deals 535 damage when it crits (and it crits every time). Which would suggest a tool tip / base damage of 357 rather than 415.

Thunderous Blow also suffers from lower damage than what the tool tip states, and its damage is applied before the debuff, meaning its damage is lost in the wounds debuff effect. Whether or not that is intended I'm not sure.

**Comment by Chummi** [comment]
thunderous blow definitely does not work as intended since its damage was always applied after the debuff. it's one of the most important skills on mrd and i guess it's not only me who would like to get that one fixed asap <3. 
i can also confirm that guillotine dmg seems to be a bit too low

**Comment by magter3001** [comment]
The same thing happens with the Chosen wounds debuff, it does damage first and then applies the debuff.

**Comment by Toldavf** [comment]
can confirm debuff is applying before damage.

**Comment by Jaycub** [comment]
Don't you mean after?
