### ISSUE TITLE
Player in Scenario was immune to any CC the whole Scenario

### ISSUE THREAD

**Issue by ferraz19** [WarEmu/WarBugs#11699]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Player ( Xerel ) was immune to all CC for extended duration. Not sure how he did it but he could not be CCed for a crazy amount of time with 3+ ppl trying and watching Immunities.

Steps to reproduce the problem:

try to CC Xerel. 

Screenshots/Videos or archive.org evidences:

i have video evidence of this but it will not let me attach it.

**Comment by sioding** [comment]
This is nothing für the bugtracker - report such things to a gamemaster. Thanks
