### ISSUE TITLE
Reikland Factory questgiver

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#11695]
Is it possible to put the Questgiver on Destro side in Reikland Factory at the spawnpoint like Order has? Now at the start of the scen all destro first have to pick up the quest whilst Order can take it when they join the scenario.

**Comment by wiscel** [comment]
Yes, meaning the other side has 2 seconds advantage.

**Comment by sioding** [comment]
OK that made me laugh - and because of that i moved the questgiver a bit towards the spawnpoint. to remove the 2 seconds advantage ;)

**Comment by sioding** [comment]
fixed with patch from 05.05.2018
