### ISSUE TITLE
[Quest] When handing in a finished quest. The icon colour is grey, rather than orange.

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#117]
I've noticed that some of the quests have been affected by this.

When you return to complete a quest. Sometimes they are grey instead of the orange to symbolise "completed".

Not all the quests behave in this manner and I can't figure out the pattern that could be causing it.

![ready to complete quests icons are in colour grey and not orange](https://cloud.githubusercontent.com/assets/7492543/2936867/95d75116-d877-11e3-8958-55a2e90ed46b.png)

![ready to complete quests icons are in colour grey and not orange2](https://cloud.githubusercontent.com/assets/7492543/2936868/9e9d393c-d877-11e3-9828-631b920fda55.png)

**Comment by genisaurus** [comment]
Fixed in a recent patch.
