### ISSUE TITLE
[Quest] [Chaos] Ch. 20 quest "Undeserved blessing" not working

### ISSUE THREAD

**Issue by lennip** [WarEmu/WarBugs#11702]
Quest from Chaos chapter 20 "Undeserved blessing" is not working at all (interactions not implemented, objects and NPCs not there)
![mutty_025](https://user-images.githubusercontent.com/2891053/39470212-9edad5f6-4d3c-11e8-9d26-b7e0093381a0.jpg)

- No quest marker on map (should be around Garrisonburg, which is the PQ closest to Chapter 20)
![mutty_026](https://user-images.githubusercontent.com/2891053/39470200-90e603c6-4d3c-11e8-94e2-bec45f03c7e1.jpg)

- You don't receive the poison from the quest giver, nor is the well in Garrisonburg interactable, so first objective can't be completed

- The Ambush at Garrisonburg PQ and the NPCs that should be in the area don't seem to be implemented correctly, so there are no "residents" you can kill to obtain a Flesh Sample, therefore the second objective cannot be completed either

**Comment by NorKalli** [comment]
Needs some script work, can't fix yet

**Comment by Lheana** [comment]
Quest will be working with next patch.
Note that you will have to abandon and retake the quest to be able to complete it.

**Comment by sioding** [comment]
fixed with patch from 05.11.2018
