### ISSUE TITLE
[Quest] [Dark Elves] Ch.5 quest "Land of shadows" not working

### ISSUE THREAD

**Issue by lennip** [WarEmu/WarBugs#11707]
Hi, 
the quest "Land of shadows" from Dark Elves chapter 5 doesn't seem to be implemented properly.

![gaernith_000](https://user-images.githubusercontent.com/2891053/39486025-0dc3e492-4d7b-11e8-919b-d2e361d82147.jpg)

There are several issues:

- Quests objectives are incorrect: they read "kill Celedaine Duskbringer" twice, when in fact, the correct objectives of that quest should be to kill all 3 commanders of the Shadow Warrior camp: Moroirl Shadowdancer, Celedaine Duskbringer and Endhrios Silentfall (the dialog text of the quest indeed says "slay the Shadow Warrior commanders" so there should be more than one guy to kill)

- Celedaine Duskbringer is missing. The other two (Endhrios Silentfall and Moroirl Shadowdancer) are there (near some tents) but I searched the whole area and couldn't find Celedaine Duskbringer anywhere...

**Comment by sioding** [comment]
fixed with patch from 05.05.2018
