### ISSUE TITLE
Instant casts getting build ups

### ISSUE THREAD

**Issue by Toldavf** [WarEmu/WarBugs#11709]
Something potentially concussive mine is giving my instant casts skills build ups. I didnt grab a screen shot but something was causing the skills on my mara to display cast bars which would then instantly interrupt because im moving. Was in the middle of getting zerged at the time so I am not 100% sure its the mine tactic.

**Comment by cimator** [comment]
Very likely it was Archmage M2 Blinding Light, it adds +1 second cast time to all abilities including insta cast ones

**Comment by sioding** [comment]
I bet @cimator got it but sorry @Toldavf  - with no screens / tests or videos we aren´t able to reproduce such things which make this report not fixable.
