### ISSUE TITLE
[Quest] [Chaos] Ch.22 quest "Complete Destruction" not working

### ISSUE THREAD

**Issue by lennip** [WarEmu/WarBugs#11701]
Chaos chapter 22 quest "Complete Destruction" does not seem to be working at all:
![mutty_023](https://user-images.githubusercontent.com/2891053/39469153-240f1a6c-4d37-11e8-9f59-2279fa2b4a2c.jpg)

- There is no quest marker
- Quest description and objectives say you have to place 2 objects (Earthrenders) you get from the quest giver in two locations near Reisguard Castle. However, you don't receive the Earthrenders in your Quest items or Inventory
- I also searched the specified locations (Reisguard Castle courtyard and cannons) to try and find something to click on that would trigger the quest objective completion but I could not find any interactable object around those places

So it seems the objects that should be interacted with in order to validate the quest have not been implemented at all...

**Comment by Lheana** [comment]
You will now receive item 'Earthrender' when accepting the quest. You will have to use it.
Note that you will have to abandon the quest and retake it to be able to complete it.

**Comment by sioding** [comment]
fixed with patch from 05.11.2018
