### ISSUE TITLE
[Quest] [Greenskin] Barak Varr warcamp quest "Seeing Green" cannot be completed

### ISSUE THREAD

**Issue by ascense** [WarEmu/WarBugs#11703]
Expected behavior and actual behavior:
After completing the first part of the quest (speak to Brakka), the second part of the quest (Mushroom placed at Herdstone) cannot be completed.

I tried
 - interacting with the Herdstone
 - killing the monsters around the herdstone
 - directly turn in the quest to Shaman Thrizzle

Quest:
![ruffskul_006](https://user-images.githubusercontent.com/53078/39471019-96f6106e-4d49-11e8-9d34-32efe5f2df15.jpg)
![ruffskul_005](https://user-images.githubusercontent.com/53078/39470912-f32f67a0-4d48-11e8-8065-914bb328b638.jpg)

Herdstone:
![ruffskul_003](https://user-images.githubusercontent.com/53078/39470864-ba9f8672-4d48-11e8-8e5e-591e8912cf9f.jpg)
![ruffskul_000](https://user-images.githubusercontent.com/53078/39470870-c3984cc8-4d48-11e8-91dc-4b9dff8ad890.jpg)

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 05.05.2018
