### ISSUE TITLE
[Quest][Greenskin] Ch.1 quest,"Pile it Up!" not working

### ISSUE THREAD

**Issue by g4USA** [WarEmu/WarBugs#11700]
The quest, "Pile it Up!" in Tier 1 Greenskin starting zone in Mount Bloodhorn, offered by questgiver, "Crankz"(4342 ,55094).
The quest used to work several months ago for me by simply clicking on one of the piles of mud, causing one of the statues to be automatically muddied.

The quest is currently broken because when I now click on the mud, I get 1/1 handful of mud, but the statue is still not muddied/gorkified.
I tried clicking on all of the piles of mud = statue still not muddied/gorkified.
I tried clicking on each pile of mud individually, and then clicking on each nearby statues to muddy it/gorkify it = doesn't work.
I tried searching my quest inventory for the mud after I clicked on a pile to muddy/gorkify it = nothing there.
I tried abandoning the quest and taking it again = same thing.
I tried logging out and logging back in = quest still doesn't work, even when I abandoned it and tried it again.
![77345634656](https://user-images.githubusercontent.com/29905200/39468438-861ac1a8-4d22-11e8-8e14-f6a76e50627e.jpg)
![ghir_006](https://user-images.githubusercontent.com/29905200/39657590-d1dfb64c-4ff8-11e8-8ecd-3702a4331c05.jpg)
![ghir_000](https://user-images.githubusercontent.com/29905200/39657601-e8c83a6e-4ff8-11e8-8e2b-769e62a6336a.jpg)
![ghir_007](https://user-images.githubusercontent.com/29905200/39657585-c5bb835a-4ff8-11e8-98c9-8f1832413972.jpg)

**Comment by NorKalli** [comment]
Needs client control to update a handler to allow condition set to be "target game object, use item" upon using item, player should animate throwing, statue should change VFX state and objective should be complete.

**Comment by Lheana** [comment]
The quest will be working with next patch. Though it won't work as it was on live, still need some features to make it that way.

**Comment by Natherul** [comment]
Should be fixed as of todays patch (14/07/2017)
