### ISSUE TITLE
Stone troll crossing scenario small renow tick when you put the bauble on stone troll control point

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11715]
I remember on live server to have few tick 2x10 tick on all players who stand near the rock when you put the bauble on one of the three rocks. It's a bonus for the players to help to put the bauble (like the  serpent passage now when you get 70 renow when you take back the bauble to your camp).

**Comment by sioding** [comment]
No proof after 2 Weeks - close
