### ISSUE TITLE
WL Mending Tactic only healing the cat.

### ISSUE THREAD

**Issue by drunkenpunkus** [WarEmu/WarBugs#11716]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
The tactic says that it will heal the cat and yourself (meager points). 
![elsabet_015](https://user-images.githubusercontent.com/38984997/39635296-f1da678a-4f71-11e8-8d72-2b0ac3414844.jpg)
![elsabet_013](https://user-images.githubusercontent.com/38984997/39635299-f40d4888-4f71-11e8-8547-ba983aa68dc2.jpg)
![elsabet_015](https://user-images.githubusercontent.com/38984997/39635296-f1da678a-4f71-11e8-8d72-2b0ac3414844.jpg)
![elsabet_013](https://user-images.githubusercontent.com/38984997/39635299-f40d4888-4f71-11e8-8547-ba983aa68dc2.jpg)

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Natherul** [comment]
same issue as https://github.com/WarEmu/WarBugs/issues/11717
