### ISSUE TITLE
Visual Issue - Missing Hydra NPC - Shadowlands

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#11719]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

In High Elf Tier 2, Shadowlands zone at around 53652:55968 on the cliff side of the path, there used to be a Hydra NPC with a small number of Dark Elf Beast Masters. The Hydra would be trying to attack the Druchii, who would be stood around it, I guess "panicking" by how their animations were set, trying I think, to get the Hydra under control. The NPCs would not attack Order players, or kill eachother.

Steps to reproduce the problem:

Drop the Hydra and a few Beast Masters back into this position to restore them to the map. The position is roughly ahead of where my mount's head is pointing!

Screenshots/Videos or archive.org evidences:

![senthoi_011](https://user-images.githubusercontent.com/22262165/39646741-5276b190-4fd4-11e8-89d0-6367d40ddda5.jpg)

**Comment by sioding** [comment]
Are you having any live pics / videos from it? Not saying that we have any priorities for things like that but it would be gret to restore such things

**Comment by Lheana** [comment]
Your description reminds me the Hydra in Caledor for ToK unlock "Who Let That Thing Out?". Are you sure it was there in this map? There were not many Hydra on official.

**Comment by Senthoi** [comment]
I wish I did. The computer I had the game on died, and I didn't have this among the screenshots I'd backed up onto USB. It was a bit like that, yes Lheana! Now there is the Hydra at the top end of the Shadowlands when you first get into the area, but this one was more like a random NPC just giving the Dark Elves trouble. It didn't do anything special, was just something going on as part of the scenery.

**Comment by NorKalli** [comment]
Moved a double-spawn hydra from the north of shadowlands and placed him down south, found level appropriate beastlord mobs and gave them some life

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
