### ISSUE TITLE
[Ch. 5 Chaos][Quest] The Corruption within

### ISSUE THREAD

**Issue by Wosboruf** [WarEmu/WarBugs#11713]
Quest says, you should collect 3 plants, Bloodthorn, Shimmerweed & Fungal Rot.
![dose_000](https://user-images.githubusercontent.com/38959916/39596734-9ab45320-4f13-11e8-8351-ad16901a111d.jpg)

- The Quest marker is on the R 12-13 PQ (Reaper's Circle) , where u can find the Bloodthorn.

- Shimmerweed & Fungal Rot are in the RvR Area in Ostland. (area 22574:4777)

Bug or intended?

**Comment by sioding** [comment]
Intended - you should feel the fear  of war sometimes. Anyway - thanks for the report.
