### ISSUE TITLE
Aegis of Orange Fire bug?

### ISSUE THREAD

**Issue by Jeeves-Archibald** [WarEmu/WarBugs#11717]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: Aegis of Orange Fire no longer provides a heal, but rather increases maximum Wounds while current Wounds remains at the same value as prior to the use of the ability.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences: https://imgur.com/a/vQ9Ke6L

**Comment by Natherul** [comment]
should hopefully be fixed in the next patch

**Comment by sioding** [comment]
fixed with patch from 05.05.2018
