### ISSUE TITLE
Slayer Grayoath impossible to get to

### ISSUE THREAD

**Issue by Joshwa70** [WarEmu/WarBugs#11727]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*
The slayer at the end of the epic quest for dwarf/greenskin pairing is behind the super onslaught pq,   meant for level 36's.  With the 150 mobs to clear you would need a wb for people to get clear the trash and get to the quest mob.
Expected behavior and actual behavior:
I would expect to be able to get to the mob and kill it :)

Steps to reproduce the problem:
Move the mob somewhere that the pq doesnt' interfere with non warbands trying to do the epic quest.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
