### ISSUE TITLE
[IB] Tactic "Sweet Revenge"

### ISSUE THREAD

**Issue by jebca** [WarEmu/WarBugs#11725]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Simple, iron breaker tactic "sweet revenge" don t work

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Thanks for the report. Plase add your testing screenshots to this report.

**Comment by jebca** [comment]
![horigan_000](https://user-images.githubusercontent.com/18122933/39661324-d6dd3a96-504f-11e8-9ba3-11cc87283fe9.jpg)
![horigan_001](https://user-images.githubusercontent.com/18122933/39661325-d7014f94-504f-11e8-8db6-e0aaf691c669.jpg)

**Comment by jebca** [comment]
![horigan_002](https://user-images.githubusercontent.com/18122933/39661331-f380a11a-504f-11e8-9bda-e90bde568c0d.jpg)
![horigan_003](https://user-images.githubusercontent.com/18122933/39661332-f3b6ccc2-504f-11e8-9507-c01bb0fa3008.jpg)

**Comment by sioding** [comment]
Thanks - but my bad sorry. To make sure its not a paperdoll problem - please add screenshots while using the .getstats command on youself. Thanks

**Comment by jebca** [comment]
![horigan_004](https://user-images.githubusercontent.com/18122933/39661527-2c857b54-5053-11e8-8fd1-228446a2be99.jpg)

**Comment by jebca** [comment]
![horigan_006](https://user-images.githubusercontent.com/18122933/39661537-5508a290-5053-11e8-8c86-9be690f2203e.jpg)

**Comment by sioding** [comment]
Thanks for adding the screens - even if its hard to see the critrate. please set the opacity to 100% for the next report.

**Comment by cimator** [comment]
I see it's working fine. Reason why you see CriticalHitRate seperate from MeleeCritRate is because Sweet Revenge gives all around crit chance including heal/ranged/magic crit aswell, so for ex on your case, you have 29 melee crit, and 15 heal/magic/ranged crit

**Comment by jebca** [comment]
Sorry m8 but you don t have a right. i take screnshot of my engi to with tactic "tracer rounds" +15crit bonus to everything
![smiling_000](https://user-images.githubusercontent.com/18122933/39695305-6f273608-51ea-11e8-80a8-251131206817.jpg)
![smiling_001](https://user-images.githubusercontent.com/18122933/39695306-6f4ad586-51ea-11e8-9e77-d49bbb00c77d.jpg)
![smiling_002](https://user-images.githubusercontent.com/18122933/39695307-6f6c5fa8-51ea-11e8-9c1d-a360d9b8d93a.jpg)

**Comment by jebca** [comment]
i see that bonus everywhere. Melee magic ranget.

**Comment by sioding** [comment]
OK thanks @all for clearing this up. Close cause the tactic works fine.
