### ISSUE TITLE
Satchel of Scout's Emblems (5) Not converting correctly.

### ISSUE THREAD

**Issue by Scottx125** [WarEmu/WarBugs#11723]
Expected behavior and actual behavior:
When right clicking a satchel, you should get 5 scout emblems. What actually happens is you only get 0.5 of 1 (literally found out after opening like 40 Satchels...). Even when control-right clicking, you open only one and you get the same amount..

Steps to reproduce the problem:
Open multiple Satchels of Scout's Emblems.

Screenshots/Videos or archive.org evidences:
Initial Scout's emblems:
https://steamuserimages-a.akamaihd.net/ugc/911294107791546574/A29376DAAAE26CEDED55E0E7D9E0401BF5224FBD/
Initial Satchels of Scout's Emblems (5):
https://steamuserimages-a.akamaihd.net/ugc/911294107791546753/71E974DBD87A64CF9FEE16BF23A72C8B9F50F118/
Number of Satchels of Scout's Emblems (5) after opening 2 satchels:
https://steamuserimages-a.akamaihd.net/ugc/911294107791546912/9C113A41835BA99E31155713BFD0CD07CBF24F86/
Increase of only 1 Scout's Emblem from original after 2 satchels consumed:
https://steamuserimages-a.akamaihd.net/ugc/911294107791547073/29A149F5EE7F7F5AD92C2B9E10D9A1943C28BC1F/

**Comment by sioding** [comment]
Heyho,

i´ve tried to reproduce this but i really can´t. I´ve converted several stacks of 200 satchel´s and always get 1000 emblems out of it. So OK maybe i can not click as fast as you can - but if we are not able to reproduce it - we can not fix something. If there would be a gneral problem in converting satchel´s - i bet we had a lot of reports. So my best tip for you is not to convert as fast as you can - give the server some time.
