### ISSUE TITLE
Ancestral Relic - Graphic Issue

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#11720]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

High Elf starter zone, coordinates 35389: 8083. In the wooded area there is a "Dark Elf Looter" NPC thrashing about on the floor, near to a clickable item, "Ancestral Relic". In live, the Looter used to be hovering in the air, surrounded by a bright magical effect animation of some kind. When you clicked on the Ancestral Relic, you would receive an item in your backpack, as I remember it was called something like the Orb of Caldaith. In appearance this looked like a silvery grey pearl. No Tome Unlock would occur and it was not a trophy or pocket item. It seemed to be a bug in live, or quest item that had not been implemented.

Steps to reproduce the problem:

Maybe attach a pocket item to the Ancestral Relic, and see if you can get the Dark Elf to float again!

Screenshots/Videos or archive.org evidences:
 
![senthoi_014](https://user-images.githubusercontent.com/22262165/39648752-39975e7a-4fdb-11e8-9202-f5bae60d0837.jpg)

**Comment by Lheana** [comment]
Seems like the NPC is now correctly flying above the floor. For the item, no real info so closing the ticket until we get further information.
