### ISSUE TITLE
T2 Barak Varr-Marshes of Madness 2h weapon cosmetic glitch

### ISSUE THREAD

**Issue by DaGreenest** [WarEmu/WarBugs#11721]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Steps to reproduce the problem:

T2 Greenskin- Dwarf RVR 2h weapon reward. I got only greenskin one so not sure if this drops for other classes as well.

Screenshots/Videos or archive.org evidences:

![bugged weapon](https://user-images.githubusercontent.com/38992707/39655285-64683df6-5001-11e8-93ff-a556452a503d.jpg)

**Comment by DaGreenest** [comment]
Looks like T2 RVR Shadowlands - Ellyrion reward is also identical to this glitch.
![bugged weapon 2](https://user-images.githubusercontent.com/38992707/39658183-4e00e0f0-5019-11e8-8542-29d13d404bc3.jpg)

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
