### ISSUE TITLE
PQ Skullbreaker Ridge Dwarf Chapter 14 - No Enemys

### ISSUE THREAD

**Issue by Lorgrim** [WarEmu/WarBugs#11729]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Public Quest Skullbreaker Ridge - Dwarf Chapter 14
No Enemys

Steps to reproduce the problem:
Walk into PQ and search them. ^^

Screenshots/Videos or archive.org evidences:

![bug1](https://user-images.githubusercontent.com/39011091/39665581-07e14b9a-5097-11e8-9e69-2e9002a7cd6c.JPG)

**Comment by sioding** [comment]
This is a known issues - sometimes the PQ doesn´t start until server restart -  we have no fix for it atm.
