### ISSUE TITLE
PQ Empire Chapter 22: The Fall of Night

### ISSUE THREAD

**Issue by hiddenagenda** [WarEmu/WarBugs#11728]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:should be getting 100 influence per kill, however after 3 clears of this PQ it shows as 2200 which is well under 1/3 of the influence it should have produced

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Thanks for the report. Please add your testing screenshots.

**Comment by Lheana** [comment]
#9990
