### ISSUE TITLE
Genesis Jewelry Dyeable

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#11726]
It is possible to dye genesis items (at least the ones I have). It is troublesome especially if someone is using 'Apply to all items' at the vendor as he have to pay for the accessories as well
![sheykis_055](https://user-images.githubusercontent.com/18032193/39661485-73d56aa6-5052-11e8-8d50-2207ca44ea61.jpg)

**Comment by sioding** [comment]
Hm - well you can take them off before using the vendor and i bet we are talking abount lots of gold for it - but yes you are right. :)

**Comment by Natherul** [comment]
fixed next patch

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
