### ISSUE TITLE
Loot Bag with wrong class item

### ISSUE THREAD

**Issue by Snotlingus** [WarEmu/WarBugs#11739]
This evening i got my first Golden loot Bag i Opened it and chose the Set item i Accepted and got an Magus item diden´t know why me as a Order char go´t Destro items i cant Sell or use it

![vallkyra_000](https://user-images.githubusercontent.com/38992800/39787753-33fd4f20-5327-11e8-816b-ff9d69ea9ec9.jpg)

**Comment by Dephyantx** [comment]
Just received my first gold bag and the armor piece was obliterator vambraces for a swordmaster on my blackguard. I haven't claimed any of the rewards and still have the bag in my inventory.

**Comment by Illrathor** [comment]
This happened on 04/04. 
![Jorbane_002](https://user-images.githubusercontent.com/48930723/55537084-3f4f5380-5670-11e9-8d7f-53a390632867.jpg)

**Comment by ropuch** [comment]
2019-04-08, Massive Loot Bag from Reikland
![Iskaral_002](https://user-images.githubusercontent.com/24792/55747460-9b352600-5a3c-11e9-8de5-1c8edce5656c.jpg)

**Comment by rameden** [comment]
8/6/19 - Wrong reward from T3 keep (Thunder Mountain)
![Drhover_001](https://user-images.githubusercontent.com/1105847/62573203-812d1800-b863-11e9-8155-22bfbd88bc1f.jpg)

**Comment by Natherul** [comment]
this might be fixed as of today, if no replies after today it will be closed in 2 weeks time and considered fixed.

**Comment by raptrr** [comment]
No replies, seems fixed, closing this issue.
