### ISSUE TITLE
Vanity cloaks alternate appearance can not be used

### ISSUE THREAD

**Issue by Remmingtonz** [WarEmu/WarBugs#11737]
Expected behavior and actual behavior:

I have a cloak on that has alternate appearance, however when trying to put 1st birthday or hide of killing frost (only 2 i own) on it asks for confirmation, but wont actuall apply the visual changes

Steps to reproduce the problem:

grab a vanity cloak
select appreance box
try to eqiup

Screenshots/Videos or archive.org evidences:

![alanahandra_000](https://user-images.githubusercontent.com/38742275/39757268-6f27f44e-5320-11e8-933a-05bad826d630.jpg)
![alanahandra_001](https://user-images.githubusercontent.com/38742275/39757269-6f59bd12-5320-11e8-9662-4d5957a6398f.jpg)
![alanahandra_002](https://user-images.githubusercontent.com/38742275/39757270-6f87759a-5320-11e8-9f5e-b97b42144c01.jpg)

**Comment by sioding** [comment]
Hm works fine for me:
![image](https://user-images.githubusercontent.com/18517842/39760726-685f4eb8-52d6-11e8-8421-2c6ea3971a1c.png)

We need more informations. Which Cloak are you using now? Which exactly item are you using for the alternate appearance?

**Comment by Lheana** [comment]
I don't see any cloak equipped at the slot of the cloak appearance on your last screenshot. It must explain your issue.

**Comment by sioding** [comment]
Problem found and fixed with next patch

**Comment by Remmingtonz** [comment]
awesome thanks a bunch :)

**Comment by Remmingtonz** [comment]
so after much leveling and frustration, it seems it was the cloak i had equipped may have been the culprit.

Glad to report that new cloak allows alt appearance.

![alanahandra_000](https://user-images.githubusercontent.com/38742275/39797191-e4712caa-53ae-11e8-8f99-a6dcefd417e6.jpg)

may have just been issue with T1 RR reward cloak (s)

**Comment by Remmingtonz** [comment]
![alanahandra_004](https://user-images.githubusercontent.com/38742275/39797214-113b756a-53af-11e8-8692-31e9392dc13b.jpg)

gah! uploaded wrong ss

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
