### ISSUE TITLE
Cultivating stucked on 175 over 5days

### ISSUE THREAD

**Issue by WAR2014** [WarEmu/WarBugs#11730]
My Witch Hunter name Uballda's cultivate processing stucked on lv175 more than 5 days. No matter how many times I did cleaned cache in game folder or relog the game, the problem still remained.  The cultivate rank is full 200, I can grown some 200 green seeds but by the times when growing 175 to 200 no luck. I used MG-Remix addon for processing.

Any solution?

**Comment by sioding** [comment]
Please move your question to the forum. This is only for bugs and no support tool.
