### ISSUE TITLE
Entertain me, Worm issue

### ISSUE THREAD

**Issue by teizeman** [WarEmu/WarBugs#1173]
im trying to do the quest, but my goblin cant reach the first platform.
it seems that its land dectection is way off, its like hitting a wall and i slide off.
had the same problem with my Chosen, often he would just hit an ivisible wall and slide off

**Comment by milosxe** [comment]
I just did this quest without an issue. 
I remember that people used to report this in /advice, but I guess that even if there was something wrong, it's fixed now?

**Comment by Evildoor** [comment]
Closing since @milosxe and other people were able to do the quest without problems.
