### ISSUE TITLE
BFP - Kolaz Umgal : flying orcs

### ISSUE THREAD

**Issue by benitoben20** [WarEmu/WarBugs#11733]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Hi, 
Upon entering the Kolaz Umgal PQ, i've spotted a few orcs flying or more likely, being thrown from a catapult while they are holding a barell. I can't recall if there was an animation on live of orcs being catapulted. 

Expected behavior and actual behavior:
Orcs are "flying"/"catapulted". It might be an animation problem, but for now they could only be on the ground or remove. 

Steps to reproduce the problem:
None

Screenshots/Videos or archive.org evidences:
![zamerick_000](https://user-images.githubusercontent.com/16641170/39677335-23a87442-5147-11e8-8819-a0500dada1b2.jpg)
![zamerick_001](https://user-images.githubusercontent.com/16641170/39677336-23be81e2-5147-11e8-92d0-3e1e56afa177.jpg)

**Comment by NorKalli** [comment]
These guys are named "rock proxy" and are a wierd result of the sniffer picking up the animation when the EMU was being created. For now there's nothing we can do.

**Comment by Lheana** [comment]
Half fixed: Disabled the spawns.

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
