### ISSUE TITLE
Logrin's Forge Objective Range

### ISSUE THREAD

**Issue by Pumatouch** [WarEmu/WarBugs#11735]
When cruising various Scenarios, one notices that the range for interacting with an objective have been decreased in many instances. The Explosive Kegs from Talabec Dam etc. are examples; one has to be in actual reach of the thing. When visiting Logrin's Forge, the objective can be handled from several feet away. 

![binwin_152](https://user-images.githubusercontent.com/16616998/39748080-6de0d23e-52af-11e8-9ad4-8c0598f7ea6e.jpg)

**Comment by Natherul** [comment]
fixed in the next patch

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
