### ISSUE TITLE
[Black Guard] Hastened Doom AA (TACTIC) does not stack with choppa's Git Stuck in (SKILL)

### ISSUE THREAD

**Issue by argott** [WarEmu/WarBugs#11742]
no buff
![no buff](https://user-images.githubusercontent.com/28632635/39844889-47a10d1c-53fb-11e8-8cc9-aa899e7ddb31.png)

bg's tactic proc
![bg s buff only](https://user-images.githubusercontent.com/28632635/39844955-a1875c14-53fb-11e8-8449-eb837c05eaeb.png)

both buffs
![both buffs](https://user-images.githubusercontent.com/28632635/39844858-1b5759fa-53fb-11e8-82e0-e420a49018b6.png)

choppa's aa haste only
![choppa s buff only](https://user-images.githubusercontent.com/28632635/39844881-3da3a73e-53fb-11e8-90de-5c307882445b.png)

**Comment by sioding** [comment]
Just to make sure we are not facing a paperdoll problem, can you please add screens with .getstats output? Maybe it´s useless to ask but you were in 100 feet range from the choppa while you are doing your tests?

**Comment by argott** [comment]
here is full screeshot with both buffs up

.getstats
![warhammer online age of reckoning screenshot 2018 05 11 - 04 24 57 49](https://user-images.githubusercontent.com/28632635/39901815-7fbf6774-54d3-11e8-8342-fd68631e81b8.png)

paperdoll
![warhammer online age of reckoning screenshot 2018 05 10 - 02 27 45 84](https://user-images.githubusercontent.com/28632635/39901298-4e9808ca-54d0-11e8-9dc8-3d1fc486c0b6.png)

**Comment by sioding** [comment]
fixed with patch from 26.05.2018
