### ISSUE TITLE
NPC Issue - Unicorns Lying down

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#11744]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Elf pairing, Shadowlands, coordinates 16166, 43997 
"Majestic Unicorn" NPCs 
Most of them seem to be lying down as if they are slain, but get back up to attack you when you are within range and behave normally.

Steps to reproduce the problem:

Have them stood up as normal until you kill them.

Screenshots/Videos or archive.org evidences:

![ithilsyn_001](https://user-images.githubusercontent.com/22262165/39881207-2b4b3dea-5478-11e8-9a08-e2bf44b7f106.jpg)

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
