### ISSUE TITLE
Black Orc - Great Axe that looks like one-hander

### ISSUE THREAD

**Issue by rakels** [WarEmu/WarBugs#11748]
The item "Big Choppa of Wicked Deeds" on black orcs (influence reward dark elves chapter 3) is a great weapon but has the appearance of a one hander:

![zokrig_000](https://user-images.githubusercontent.com/9309339/39911909-47452364-54fd-11e8-8dc2-b86de1dd44e1.jpg)

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
