### ISSUE TITLE
60% Mount Deleted

### ISSUE THREAD

**Issue by Dratsummr** [WarEmu/WarBugs#11746]
Bought 60% mount 5/8/18 
Log into the server under the same character 5/10/18 and the mount has been deleted.

![diem_032](https://user-images.githubusercontent.com/13211474/39898464-6cee2bb4-547c-11e8-968a-3baac40171ac.jpg)

**Comment by sioding** [comment]
We did nothing with your mount and sory but this is not a support tool. It is for ingame bugs only. You can get in touch with a GM ingame - but as far as i know there is is no item recover support.
