### ISSUE TITLE
Tactics Crown of Fire/Frozen Fury

### ISSUE THREAD

**Issue by nohh** [WarEmu/WarBugs#11745]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Tactics Crown of Fire/Frozen Fury doesnt work if another BW/Sorc buff party.

Steps to reproduce the problem:
1. Two sorcs in party.
2. One sorc have more points in Path of Agony and buff party with Frozen Touch.
3. Second sorc sloted Frozen Fury and unable to buff self with Frozen Touch cos first sorc already do it (more points in Path of Agony)
4. Frozen Fury tactic doesnt work.

Screenshots/Videos or archive.org evidences:
no

**Comment by grunbag** [comment]
Frozen touch don’t stack with itself so it’s intended you can use this tactic
