### ISSUE TITLE
Darkelf chapter 4, Silvermane (Level 9 Champion Great cat) flagged for scavaging

### ISSUE THREAD

**Issue by lakih** [WarEmu/WarBugs#11747]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

The named level 9 champion great cat Silvermane is currently flagged for scavenging

Expected behavior and actual behavior:

Expected behavior: Mob should be flagged for butchering and yield apothecary materials

Actual behavior: Mob is flagged for scavenging and yield talisman making materials

Steps to reproduce the problem:

Kill the mob, loot the corpse.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
