### ISSUE TITLE
Lord terminate range

### ISSUE THREAD

**Issue by Lefze** [WarEmu/WarBugs#11756]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

As far as I could tell from patch notes it's supposed to terminate people pulling aggro outside lord room. The actual behavior is that the lord quite literally teleports around the whole keep area terminating random people. All the way to outer door, even if said people are not hitting the lord and have already been terminated and haven't hit the lord after the terminate. Quite gamebreaking when trying to wipe defenders either at 3rd floor or between inner and outer.

Steps to reproduce the problem:

Fight at the keep after door goes down.

Screenshots/Videos or archive.org evidences:

https://imgur.com/a/7v1CB5Y

Lord just randomly teleported and terminated me by outer wall. Not the first time it happened either.

**Comment by Zoggof** [comment]
It seems you can also get terminated at the WC.
![doinks_002](https://user-images.githubusercontent.com/23256143/42157337-c09a0728-7e30-11e8-85a5-f1d0dcc5351c.jpg)

**Comment by sioding** [comment]
fixed with patch from 14.08.2018
