### ISSUE TITLE
PQ The Griffon Gate

### ISSUE THREAD

**Issue by Krucz** [WarEmu/WarBugs#11758]
In PQ The Griffon Gate dont show up Eagle Claws in stage 1. Without it you can not go to part 2 and finish stage for T2 Epic Quest.

**Comment by Lheana** [comment]
#10862

**Comment by frankystein65** [comment]
looks like the same issue has happened again.  currently stage 1 shows kill Eagle Claws 0/8 and no Eagle Claws
