### ISSUE TITLE
Can't Salvage items ( BoP Duelist and rep ring)

### ISSUE THREAD

**Issue by Merliin** [WarEmu/WarBugs#11754]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
List of items that should be salvageable but are not, 
Illuminations of the Duelist, Grille of the Duelist, Flamerobe of the Duelist, and Ember Ring of Thunder.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by NorKalli** [comment]
All duelist gear + ember rings of x now salvagable

**Comment by sioding** [comment]
fixed with patch from 26.05.2018
