### ISSUE TITLE
altdorf gates / do not open

### ISSUE THREAD

**Issue by thorgallis** [WarEmu/WarBugs#11755]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: The double gates just north of sigmars hammer do not work and therefore, someone not in a guild, would have to go all the way around altdorf to get to the merchant trainers. the north gate operates correctly. the south gate does not have an object. to click on to make the gate go up.

Steps to reproduce the problem: click on south gate leading from sigmars towards the bank area. gate is not interactive.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
fixed with patch from 26.05.2018

**Comment by sioding** [comment]
reopen cause its not fexed.

**Comment by sioding** [comment]
Fixed with patch from 02.06.20018

**Comment by sioding** [comment]
and back to @Ryanfawkez

**Comment by sioding** [comment]
works fine now

**Comment by thorgallis** [comment]
will check it out soon. thanks
