### ISSUE TITLE
Invisible Engineer shoulders

### ISSUE THREAD

**Issue by Deadpoet99** [WarEmu/WarBugs#11751]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

shoulderpiece should have an appearance. When I put them it shows as if I wasn't wearing any.

Steps to reproduce the problem:
 This is a reward from chapter 12 dwarf, BFP.
![reach_018](https://user-images.githubusercontent.com/39203818/39949002-c3365ad0-5578-11e8-8b80-0a24a01cf8ef.jpg)

Screenshots/Videos or archive.org evidences:

**Comment by NorKalli** [comment]
Given level 24 green appearance

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
