### ISSUE TITLE
Missing Skin: Ironmane Mantle [WP]

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#11750]
Ironmane Mantle for WP is missing model/skin
![sheyp_000](https://user-images.githubusercontent.com/18032193/39947677-146d8898-5573-11e8-98eb-91b58ec5a838.jpg)

**Comment by NorKalli** [comment]
fixed

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
