### ISSUE TITLE
Shadowland pve in rvr area 40.52

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11757]
You can stand in 40.52 area without be flagged rvr and engage only as you wish
![thorbolt_187](https://user-images.githubusercontent.com/16274785/39963465-db5aa082-566b-11e8-923e-b094973b2ec4.jpg)

**Comment by sioding** [comment]
And how are you able to get in there without being flagged?

**Comment by thorbolt80** [comment]
You take a scenario then you arrive here in same place

**Comment by sioding** [comment]
Ahh ok - so no problem at all. its ok when you not flagged at this place. So - close - no bug but thanks for the report.
