### ISSUE TITLE
30 mins stagger

### ISSUE THREAD

**Issue by velkos4ever** [WarEmu/WarBugs#11764]
ability name : in shock-30 mins(stagger)
![oug_010](https://user-images.githubusercontent.com/16551075/40065532-b6cb0486-586a-11e8-9687-27e517912254.jpg)
![oug_012](https://user-images.githubusercontent.com/16551075/40065546-bcdd58f6-586a-11e8-91e0-5921ba3cece9.jpg)

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 26.05.2018
