### ISSUE TITLE
MAss skill table crash

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#11760]
today as im writing , 12:40-12:45 (gmt+1/cet+0)we had a mass (local?) skill table crash on shadowlands, basically server was stable and not lagging (chat wasn't)  most of ppl on both sides could use skills exept from some (guards/flee and fireballs and some engi ones), my wb got completly hit by this seems also enemy wb too to some extent

**Comment by sioding** [comment]
Hey @Tesq 
those bugreports won´t help at all. We can not reproduce that. I will try to get an dev looking into the log after the next restart. Maybe he can find something - but this could lead into no real "fix".

**Comment by Tesq** [comment]
yes they need to look at logs as it wasn't an isolate case, post server restart today from 16:43 i had same issue; i was a t a flag and flag stopped grant renown(we had 2 flags) i used flee and after that my ap never regenerate again; then i was in combat and could only use some skill which where meccanic dependant (i was on BG) ; this happened  between 16:43 to 16:50 (16/05/2018  gmt+1/cet+0)
