### ISSUE TITLE
Wrong Respawn

### ISSUE THREAD

**Issue by Hattiro** [WarEmu/WarBugs#11761]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:Fight at Stables bfo at Elyrion, get killed and respawn at same point and this 4 times oO

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
That was during a time the server was in a not stable situation. Somtimes things happen...
