### ISSUE TITLE
potion n*2[emulator][itiems]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#1176]
postion seems have a bid delay after being used, it seems like itiem got first removed by inventory and then you get the heal. The delay should be the one of a skill, and it's like half-1 sec atm

**Comment by milosxe** [comment]
It's related to this issue https://github.com/WarEmu/WarBugs/issues/1265 . Potions used to ignore GCD on live and they were consumed almost if not instantly.

**Comment by Luth-RoR** [comment]
Potions use the global cooldown, unlike on the mythic server. Seems like an intended design decission atm.
