### ISSUE TITLE
Mirithas Lirenor and Krothen Hireth hostile toward is own people

### ISSUE THREAD

**Issue by benitoben20** [WarEmu/WarBugs#11768]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Hi,

I was making the T2 epic quest in elf and we noticed that both Mirithas Lirenor and Krothen Hireth are hostile/being attacked by the other dark elves surrounding them. There is also a "guard" inside the tent where both of them are and the guard is always killed by those two.

Normally, they should be in the same faction, not attacking each other at least haha :)

Steps to reproduce the problem:
None

Screenshots/Videos or archive.org evidences:
![wodnargyl_000](https://user-images.githubusercontent.com/16641170/40090370-63cf88b4-587f-11e8-9339-627e1646c30e.jpg)
![wodnargyl_001](https://user-images.githubusercontent.com/16641170/40090371-6438bc76-587f-11e8-9e8c-53c60c210e7b.jpg)

**Comment by NorKalli** [comment]
Removed aggressive flag

**Comment by sioding** [comment]
fixed with patch from 26.05.2018
