### ISSUE TITLE
no renown on locks

### ISSUE THREAD

**Issue by Kalmar101** [WarEmu/WarBugs#11767]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

I made RvR 2 times today and did not get any renown when winning on order side in barak varr and black rock
dwarf engineer Jonson

barak varr that's open again
Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

![jonson_003](https://user-images.githubusercontent.com/39157007/40080579-ae2c5836-588b-11e8-804d-5c0e4eb1807f.jpg)

![jonson_002](https://user-images.githubusercontent.com/39157007/40080668-f6ee835a-588b-11e8-9018-2aa80e5d95bf.jpg)

**Comment by sioding** [comment]
Can we please see your screenshots from the locks ?

**Comment by sioding** [comment]
No answer since 12 days - close
