### ISSUE TITLE
Greenskin chapter 1 missing monster spawn.

### ISSUE THREAD

**Issue by DaGreenest** [WarEmu/WarBugs#11771]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: There is snotling called Sploop in Mount Bloodhorn (Greenskin chapter 1) who has quest. He wants the player to go into woods where pile of junk can be found. After interacting with the pile 5 snotlings rush at player from the bushes in attempt to kill them for their valuables. In current state you can only get quest and touch pile but no snotlings will come out.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![sploop](https://user-images.githubusercontent.com/38992707/40150742-3d8d0c52-5984-11e8-95bf-072d2f81c49b.jpg)
![pile](https://user-images.githubusercontent.com/38992707/40150778-6c77bcce-5984-11e8-9706-8a1a7b27ce11.jpg)

Youtube video about the quest progression:
https://youtu.be/xzNeHYJkqvg?t=186

**Comment by Lheana** [comment]
Do you have the exact name of the snotlings that are meant to spawn?

**Comment by Lheana** [comment]
Please need more information like the name of the snotlings.

**Comment by Lheana** [comment]
Some snotlings spawn when you click on this object for a while now.
