### ISSUE TITLE
Same Jewelry 4 times - Bug or Cheater?

### ISSUE THREAD

**Issue by Kalmar101** [WarEmu/WarBugs#11774]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
i have seen some guy today who had 4 times the same jewelry but you can only wear one of this at the same time

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![jonson_004](https://user-images.githubusercontent.com/39157007/40188100-710bb266-59f9-11e8-82bf-40cb550f4f7b.jpg)
![jonson_005](https://user-images.githubusercontent.com/39157007/40188101-713addc0-59f9-11e8-802d-221a10d630ee.jpg)
![jonson_006](https://user-images.githubusercontent.com/39157007/40188103-7158d410-59f9-11e8-8ac4-4ef022c66dc7.jpg)
![jonson_007](https://user-images.githubusercontent.com/39157007/40188105-71760be8-59f9-11e8-9a8e-d0e925c63fb6.jpg)

**Comment by benitoben20** [comment]
If I may, a long time ago equiping 4 jewelry of the same type was allowed. Later on, a patch was made given the attribute unique to every jewelry. I've seen that if you've created a toon before that patch wearing 4 jewelry of the same type, these 4 jewelry stays equiped and give their bonuses. It might be possible that this toon was created before that patch and he recently start replaying that toon.

**Comment by sioding** [comment]
Double checked - can not reproduce that. I close this one cause @benitoben20  gave a good reason for this.
