### ISSUE TITLE
Basic squigs taunt does not apply aggro.

### ISSUE THREAD

**Issue by ManBearSquig** [WarEmu/WarBugs#11777]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*
This issue has been raised a number of times and closed **without** being fixed

Expected behavior and actual behavior:
The basic squigs squeal should act in the same way as for example a black orcs taunt and force the mob targeted to attack the squig. It does not.

The basic squigs main use was as a tank and used to be a mainstay for any SH doing solo PVE now its just useless, this would be a huge QoL change for solo SH's

Steps to reproduce the problem:
Find and target a mob begin to attack it and it will aggro you, wait for the basic squigs "taunt" to fire and watch as the mob totally ignores the squig and keeps humping your leg.

Screenshots/Videos or archive.org evidences:
Will add this after work.

**Comment by sioding** [comment]
Thanks for the report - looking forward for your screens.

**Comment by ManBearSquig** [comment]
Ok video is [here](http://www.filedropper.com/2018-05-1819-20-51), you can see the squig squeal trigger twice in this fight and the mob doesn't bat an eyelid and continues to attack me.

**Comment by smingleton** [comment]
There is no damage increase from the ability either. Pet will hit the same while attacking taunted target.

**Comment by sioding** [comment]
Fixed with patch from 02.06.20018
