### ISSUE TITLE
Mount Bloodhorn 1st Chapter name has typo

### ISSUE THREAD

**Issue by DaGreenest** [WarEmu/WarBugs#11772]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: Mount Bloodhorn 1st chapter is named as Scarzag´s Stompin´
Grounds although the npc name is Skarzag and the chapter lore shows also him named as Skarzag.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![mb](https://user-images.githubusercontent.com/38992707/40150886-0d90bc1e-5985-11e8-8c21-010cfb278152.jpg)

![mb2](https://user-images.githubusercontent.com/38992707/40150895-222b76aa-5985-11e8-957f-8902bb403b1e.jpg)

![mb3](https://user-images.githubusercontent.com/38992707/40150910-32fb1828-5985-11e8-9267-e5d3656d833c.jpg)

**Comment by MaxHayman** [comment]
Will get this checked out

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
