### ISSUE TITLE
Mobs/NPC disappearing in Mount Gunbad after joining a scenario

### ISSUE THREAD

**Issue by Arlen88** [WarEmu/WarBugs#11779]
NPC/Mobs disappearing in Mount Gunbad when joining a scenario while in the dungeon.
In my case I was in Mount Gunbad with a friend of mine, as the group leader and joined a scenario.

As I returned, the mobs/npc where gone for me, but not for the friend of mine.
It could be reproduced and was not a display bug only, as I could run right through the mobs.
Zoning in/out helps.

**Comment by Hargrim** [comment]
Probably need to disable scenario queues in instances.

**Comment by Hargrim** [comment]
Fixed.
