### ISSUE TITLE
Burn Away Lies seems to be undefendable

### ISSUE THREAD

**Issue by deathkylem** [WarEmu/WarBugs#11783]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: This skill is undefendeable, dots in this server can be defended but this skill damage is undefendeable...think that this is not intentional...(ticks and final damage, both are undefendeable).

Steps to reproduce the problem:Not screenshots but easy to check with one friend "Morer" and my Marauder "Gaara" with my m1 100% parry/dodge.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
I looking forward for your testing screenshots.

**Comment by deathkylem** [comment]
Dont know how to post screenshots here... =( can send you via discord or email

**Comment by sioding** [comment]
![image](https://user-images.githubusercontent.com/18517842/40274323-045074c2-5bd4-11e8-91e2-b4f255164201.png)

**Comment by Torquemadra** [comment]
working as intended
