### ISSUE TITLE
Cant' take any quests anymore. NPC have grey icon above head or nothing

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11786]
I can't take quests anymore. I can just give back the quest then there is no icon anymore above the head of NPC or the icon is grey. May be it's because I reach RR 81? I can't have any answer on the forum.

Even the quests I didn't take like picture 3 (nordland) they don't even have an icon (see picture 3)

My quests are of course not full in Tok

![thorbolt_227](https://user-images.githubusercontent.com/16274785/40275146-b2ccbb3e-5be6-11e8-8f01-cf57dd26aba3.jpg)
![thorbolt_228](https://user-images.githubusercontent.com/16274785/40275147-bb7ceeca-5be6-11e8-90d8-9c52a24bd0e4.jpg)
![thorbolt_229](https://user-images.githubusercontent.com/16274785/40275151-092509d2-5be7-11e8-8898-16394f2a21aa.jpg)

**Comment by sioding** [comment]
fixed with patch from 26.05.2018
