### ISSUE TITLE
Squig Herder cant train Morale 2 skills\

### ISSUE THREAD

**Issue by Neeadbeer** [WarEmu/WarBugs#11782]
I cant train my morale 2 skill on my SH "unshakable focus". It isnt in my abilities tab and when i click to train it nothing happens

Expected behavior and actual behavior:

Steps to reproduce the problem:
Tried logging a few times

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/39436073/40268714-b434f92c-5bb5-11e8-812e-6b29b494cda1.png)

**Comment by sioding** [comment]
Unshakable Focus is removed on this server because of balancing decisions

https://wiki.returnofreckoning.com/index.php/Squig_Herder#Class_Changes
