### ISSUE TITLE
[Public Quest] Tor Elyr Part 3

### ISSUE THREAD

**Issue by Krealot** [WarEmu/WarBugs#11789]
On failure of completing the step of activating the Channeling Orbs they will still remain. They will also, however, still give you Influence for clicking them. 

Expected behavior and actual behavior:
They should not give Inf on activation due to the fact of failure of Public Quest.

Steps to reproduce the problem:
Go to Ellyrion, head to Tor Elyrn, finish steps 1 and 2. When this bug was found, there was 0/20 orbs activated during the step. 

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
fixed with patch from 26.05.2018
