### ISSUE TITLE
Stuck in the tree at the exit of caledor warcamp

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11787]
It's a well know bug for order side but no reported yet.

Tons of order get stuck in the tree at the exit of order warcamp caledor 30.40

May be you can do something?

![thorbolt_232](https://user-images.githubusercontent.com/16274785/40275863-d5a7b374-5bfb-11e8-97e6-f4e5a558ef1d.jpg)

**Comment by Lheana** [comment]
This tree and stuck place is so iconic :p

**Comment by sioding** [comment]
fixed with patch from 26.05.2018
