### ISSUE TITLE
Holmsteinn Revisited PQ Broken

### ISSUE THREAD

**Issue by mainframe0651** [WarEmu/WarBugs#11780]
Holmsteinn Revisited public quest in Norsca is broken. The required item to advance past stage 1 have not shown up nor have the Nordland NPCs which also stops the quest Deadly Task from being completed. It has been like this for ~24h.

**Comment by sioding** [comment]
Duplicate of #10862
Sorry but you have to wait until Server restart

**Comment by CatraioPT** [comment]
After recent patch this PQ is bugged. Might look into it.
