### ISSUE TITLE
Bolstered buff versions persist when going back to PvE areas

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#11788]
When entering RvR zones buffs you cast get bolster effect making them significantly stronger. It can be used to ease the PvE aspect of the game if player goes out to RvR zone to cast buffs while bolstered and then go back to PvE with his stronger buff versions.

edit: I though I'd report it as knight/chosen auras already get removed when getting bolstered and though the same should be applied to other classes buffs

Few screenshots showing buff versions with/without bolster when in PvE area (for RP and AM)
![sheyx_002](https://user-images.githubusercontent.com/18032193/40278124-94b4a810-5c2b-11e8-9cb5-440cab8d4695.jpg)
![sheyx_001](https://user-images.githubusercontent.com/18032193/40278125-94cf0aac-5c2b-11e8-83b0-c20ed3ddc76e.jpg)
![amshey_006](https://user-images.githubusercontent.com/18032193/40278141-cfd5bec0-5c2b-11e8-946d-7a33237798ff.jpg)
![amshey_005](https://user-images.githubusercontent.com/18032193/40278142-cff13ace-5c2b-11e8-9d9f-f49f5f53c2f5.jpg)

**Comment by Natherul** [comment]
this should no longer be an issue and fixed.
