### ISSUE TITLE
SC Gates of Ekrund (bug?)

### ISSUE THREAD

**Issue by Solutar** [WarEmu/WarBugs#11790]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: Punted a WP accidently on one of the Towers in the SC, he stood up there and just healed, pretty much broke the SC for Destro cause nobody could get to him. Maybe place a barrier there so nobody can actually stand on the Tower?

Steps to reproduce the problem: Just used punt in slightly the wrong angle, and the guy(Berry) got up there.

Screenshots/Videos or archive.org evidences:
![solutar_000](https://user-images.githubusercontent.com/25050452/40320526-5309e0ae-5d2c-11e8-9f43-6bdecb120fbd.jpg)

**Comment by sioding** [comment]
Nothing new and already reported. We will not prevent a punt to this location
