### ISSUE TITLE
Relog in enemy keep.

### ISSUE THREAD

**Issue by Tholkienn** [WarEmu/WarBugs#11796]
Hi, this morning i disconnect in our keep at TM, when i log in, i was, at the same place, but the zones where flip, or an reboot server, anyway, the same keep is for the other, and i was in.

I think i shouldn't able to log in that keep, because as a healer, i can pull some mate in, just with a rez.

![aniomed_121](https://user-images.githubusercontent.com/13720388/40348883-371a991e-5da5-11e8-88b3-e01a3fa038bb.jpg)

![aniomed_120](https://user-images.githubusercontent.com/13720388/40348912-4c543a9c-5da5-11e8-8ab1-fe24398e5f2a.jpg)

**Comment by sioding** [comment]
You can pull everyone in but it won´t help you at all - if the doors are not down - you can not kill the lord . So its ok to respawn inside. Sorry - no bug.

**Comment by Tholkienn** [comment]
Good to know.
