### ISSUE TITLE
Gorfang T4 Dwarf Epic Boss Hp unusually high

### ISSUE THREAD

**Issue by Seraphror** [WarEmu/WarBugs#11791]
Gorfang Rotgut, the T4 Dwarf Epic Quest boss has unusually high HP, not in line with other T4 epic bosses. Virtually impossible to solo at the moment for most classes whereas other bosses are usually soloable with right build. Seems to have hero-level hp.

**Comment by grunbag** [comment]
fixed in next patch

**Comment by sioding** [comment]
fixed with patch from 26.05.2018
