### ISSUE TITLE
[Zealot] Ritual of Innervation

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#1179]
There are 2 issues with this ritual (one minor & one major)

The main issue is as follows when in a group, and the ritual is placed at parties feet, the only character to get AP is the zealot who planted the ritual, and gets the AP procs from the other party members' attacks.
For example Y places down ritual of innervation, Z attacks monsters while Y heals (according to the tool tip the ritual should only proc on attacks). Z gets no extra AP, while Y gets +50 AP every so often (which didn't appear to be tied to the heal cast time). It should be that as Z attacks they get the procs for +50 AP, while Y gets no extra AP. This was tested analytically with Warhammer Scrolling Combat Text add-on, but could be observed as well with the AP bar.

The minor issue is that when placed the buff doesn't show up under the character portrait

Thank you

**Comment by Evildoor** [comment]
I do believe that ritual should grant AP on ability use (so on heals too) rather than on attacks only: while zealot's ritual tooltip says "on attack", RP's mirror (Master Rune of Fury) tooltip says "when they activate an ability", which makes more sense, IMO. I think they were identical in official WAR and i don't see any reason for such a mirror abilities (same mechanic, AP cost, cd, duration, position in masteries) to be weaker for zealot.

**Comment by LadyEmaleth** [comment]
Unless it was changed later in the game (I played up to Skaven patch), I'm sure you needed to do damage to activate the proc. I remember using Waves of Chaos tactic for that proc.

**Comment by Evildoor** [comment]
Hmm, in that case can some experienced RP clarify, how exactly did Master Rune of Fury worked on live? My point is - these two abilities are pretty much the same (mechanic, cooldown, duration, position in trees), so i do believe that difference in tooltips (on attack/on ability usage) is just a result of Mythic's poor wording (just like with Warped Flesh / Emperor's Ward, where tooltips are even more different, but in reality the tactics are identical) and both abilities should trigger on the same condition.

**Comment by LadyEmaleth** [comment]
I found this thread: http://www.mmorpgitalia.it/mmorpg/threads/work-in-progress-patch-1-4-7-career-balance.320624/ with gathered suggestions about class balance and one of the suggestions for zealot was:
"-Make the AP ritual work on ability so it benefits the healer as well as the DPS. RP's already does."
It confirms that there was a difference in how those skills worked. Zealot's Ritual worked on any damage you dealt including DoT ticks or Waves of Chaos tactic.

**Comment by Nfkillz** [comment]
Patch 1.4.7

http://web.archive.org/web/20130127162904/http://ageofreckoning.warhammeronline.com/article/Game-Update-147-1018

Patch 1.4.8

http://web.archive.org/web/20130127162915/http://ageofreckoning.warhammeronline.com/article/Game-Update-148-1203

now ritual works fine

**Comment by Evildoor** [comment]
Yeah, leveled my zealot to 21, ritual works on any abilities. Nice.
