### ISSUE TITLE
Item with incorrect icon

### ISSUE THREAD

**Issue by Valterius87** [WarEmu/WarBugs#11797]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:Glove item should have glove icon, but this one has shoulder armor icon

Steps to reproduce the problem:Loot the item

Screenshots/Videos or archive.org evidences:

![vellius_002](https://user-images.githubusercontent.com/39542987/40400176-03059420-5e0f-11e8-811a-41ad95e725f1.jpg)

**Comment by sioding** [comment]
fixed with patch from 26.05.2018
