### ISSUE TITLE
Out of Favor: Leashing the Waaaagh!

### ISSUE THREAD

**Issue by ReluctantTechnologist** [WarEmu/WarBugs#11792]
Expected behavior and actual behavior:

Not sure if this invalid creature in the quest line is intended, or if it will break the quest, or noticed.

Steps to reproduce the problem:

following the quest line of Out of Favor: Leashing the Waaagh for destruction.

Screenshots/Videos or archive.org evidences:

http://puu.sh/Aqwnq.jpg

**Comment by sioding** [comment]
Fixed with patch from 02.06.20018
