### ISSUE TITLE
[Bug]The Emperor's Mandate 

### ISSUE THREAD

**Issue by McConn75** [WarEmu/WarBugs#11798]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

The quest doesnt continue at the marked spot

Expected behavior and actual behavior:

Speak with Lieutenant Wilhelm ( he got the orange marking..) but does not accept talking.
Instead Questbook says speaking to Oscar Hredricson, googled and its a char for a quest belonging to destruction side.. which doesnt make sense. ;)

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

![feawen_002](https://user-images.githubusercontent.com/10255765/40445678-1f46d81a-5ecd-11e8-9968-9632b582b772.jpg)

**Comment by NorKalli** [comment]
someone else fixed but didn't update

**Comment by sioding** [comment]
Fixed with patch from 02.06.20018
