### ISSUE TITLE
"Return Fire"  is now displaying the broken location link as part of the objectives for the quest

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#118]
The quest "Return fire" has now started displaying the stange text I presume is to show the location of the target you need to go to.

This quest was displaying the text fine before the latest updates were added.

![return fire](https://cloud.githubusercontent.com/assets/7492543/2936870/007f50e0-d878-11e3-9df6-398fed48c1f1.png)

**Comment by Reggaewaldo** [comment]
Tested OK.

This can be closed.
