### ISSUE TITLE
Auction house missing attachment

### ISSUE THREAD

**Issue by Novotah** [WarEmu/WarBugs#11801]
Hi, couple days ago i put an item to the AH named Axe of the Lady for 50 gold and there was no any other Axe of the Lady on the AH at that moment. Yesterday when i logged into game i saw that item got sold but only 22 gold and 50 silver attached to the mail. I know there is AH cut but there is huge amount of gold missing.

Expected behavior and actual behavior: It should be like 3 and a half or 4 gold missing with the AH cut.. Not more than half of the buyout price (27 gold and 50 silver)...

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
I am not able to reproduce that. My best guess is you do not set it to 50 G. Until we do not get any error messages or wer are not able to reproduce it - we can not fix something.
