### ISSUE TITLE
Blightstone Squignoggin

### ISSUE THREAD

**Issue by milosxe** [WarEmu/WarBugs#1180]
This item is missing 20 Wounds

![shiznit_000_cr](https://cloud.githubusercontent.com/assets/13332067/9543166/e0399a46-4d76-11e5-9ffc-7e9140389649.jpg)

Link for reference
http://war.mmodb.com/items/blightstone-squignoggin-102461.php

**Comment by M0rf** [comment]
This is a common issue for most classes. 1 good thing unlike other items where stats are different for some classes, it appears all classes have +9 tough and +20 wounds helm from ch9.

**Comment by Reggaewaldo** [comment]
Change has been implemented on the DB. It will roll out to the regular server on next hotfix / patch.

Closing.
