### ISSUE TITLE
[Gunbad] mailbox doesnt work

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#11802]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Fixed with patch from 02.06.20018

**Comment by sioding** [comment]
fixed with patch from 16.06.2018
