### ISSUE TITLE
Unmasking the Enemy Epic quest issue

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#11807]
Recent changes to the chapter22 PQ Tor Sethai (mobs hitting much harder and having tons of hp) made impossible to do the epic quest Unmasking the Enemy solo or even in a small party (mobs hitting harder than the champ itself)

Solution: similair to faith is madness epic quest, move the required champ to area that is more easily accesible

**Comment by sioding** [comment]
which step of the quest?

**Comment by szejoza** [comment]
The one requiring to kill the champion in PQ22 Area (step #13 https://wiki.returnofreckoning.com/index.php/High_Elves_T4_Epic_Quest_Unmasking_the_Enemy )

**Comment by sioding** [comment]
Thx - will fix that

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
Fixed with patch from 02.06.20018
