### ISSUE TITLE
Sewers of Altdorf zoning problem

### ISSUE THREAD

**Issue by Medley475** [WarEmu/WarBugs#11813]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*
Unable to zone back to Altdorf
Expected behavior and actual behavior:
Expect behavior: zone back to Altdorf
Actual behavior: Zone not available

Steps to reproduce the problem:
Enter any wing of the Sewers of Altdorf, attempt to zone back out

Screenshots/Videos or archive.org evidences:
![sethani_008](https://user-images.githubusercontent.com/39679147/40625315-a2b6eb80-627f-11e8-8553-e73c84658e16.jpg)
![sethani_009](https://user-images.githubusercontent.com/39679147/40625322-a5b5b9f6-627f-11e8-90a4-8fa2ce548195.jpg)
![sethani_010](https://user-images.githubusercontent.com/39679147/40625323-a77fcbaa-627f-11e8-82a0-07b80292ffe8.jpg)
![sethani_011](https://user-images.githubusercontent.com/39679147/40625325-a8d9cf0a-627f-11e8-81f2-805d283d2500.jpg)
![sethani_012](https://user-images.githubusercontent.com/39679147/40625327-aa1e663c-627f-11e8-984e-f8b665103efc.jpg)

**Comment by sioding** [comment]
we can´t replicate that on dev - but we will have an eye on it when sewers go live. anyway - thanks for the report.
