### ISSUE TITLE
butchering liniment main ingredients drop rate

### ISSUE THREAD

**Issue by nachtkap** [WarEmu/WarBugs#11819]
Expected behavior and actual behavior:
I would have expected that all liniment main ingredients from butchering would have an equal drop rate.
In actuality 3 ingredients have a high drop rate, 3 ingredients a medium drop rate and two a low drop rate.
actual numbers:
Alacrity:25
Frenzy:22
Defense:22
Affinity:29
Hunger:19
Strength:32
Grace:30
Vision:17
Sample size:196

Steps to reproduce the problem:
Butcher t4 mobs

Screenshots/Videos or archive.org evidences:

![2018-05-31 00_25_37-warhammer_ age of reckoning version 1 4 8 copyright 2001-2012 electronic arts](https://user-images.githubusercontent.com/14278647/40751368-2bc77eb6-646b-11e8-8381-0f04ed94cd2c.png)
![2018-05-31 00_26_00-warhammer_ age of reckoning version 1 4 8 copyright 2001-2012 electronic arts](https://user-images.githubusercontent.com/14278647/40751377-31ab114e-646b-11e8-86bb-f608597e57e2.png)

**Comment by Torquemadra** [comment]
its the same chance, look up roulette odds
