### ISSUE TITLE
Quest: Tasty Morsels

### ISSUE THREAD

**Issue by Medley475** [WarEmu/WarBugs#11815]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Expected behavior: drops from NPCs in Sewers of Altdorf
Actual behabior: no dropos

Steps to reproduce the problem:
Enter Sewers of Altdorf and clear wings

Screenshots/Videos or archive.org evidences:
Unable to provide pictures of something that doesnt happen

**Comment by NorKalli** [comment]
work in progress, not supposed to be open yet

**Comment by Ryanfawkez** [comment]
Fixed.

**Comment by sioding** [comment]
Fixed with patch from 02.06.20018
