### ISSUE TITLE
Da Fings Wot Got Boom - zone description

### ISSUE THREAD

**Issue by benitoben20** [WarEmu/WarBugs#11810]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
As seen in the picture, the zone for the quest "Da Fings Wot Got Boom" is labelled as IC and "Empty slot - no need to translate this line". Since it's taking 2 lines, it would be nice if it could be removed. 

Steps to reproduce the problem:
Take the quest and open your quest tab in the book of knowledge.

Screenshots/Videos or archive.org evidences:
![zamerick_000](https://user-images.githubusercontent.com/16641170/40582336-15c64e26-6141-11e8-9564-08802934fc02.jpg)

**Comment by sioding** [comment]
fixed with patch from 29.6.2019
