### ISSUE TITLE
Quest: Poor Gustav!

### ISSUE THREAD

**Issue by Medley475** [WarEmu/WarBugs#11814]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: 
Expected behavior: Find Warprot Kidnapper in one of the three wings of the Sewers of Altdorf
Actual Behavior: NPC does not spawn

Steps to reproduce the problem:
Enter Sewers of Altdorf and clear all three wings

Screenshots/Videos or archive.org evidences:

**Comment by Ryanfawkez** [comment]
Would like to know the NPC's original location in either of three wings; quest description and objective are too vague. However, I'll pick one at will and place it wherever I see fit.

**Comment by sioding** [comment]
Fixed with patch from 02.06.20018
