### ISSUE TITLE
[WE] Elixir of The Cauldron (100% disrupt for 7 sec) doestn give you 100% disrupt chance

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#11816]
Enemies can apply dots on you, stagger you etc. if you are buffed by this elixir

**Comment by sioding** [comment]
Please add your testing screenshots.

**Comment by Nfkillz** [comment]
https://www.youtube.com/watch?v=fi1vUg4Jl4A

**Comment by MKorin** [comment]
WH's Shroud of Magnus dont protects from Shaman's or Zealot's knockback.

**Comment by sioding** [comment]
Fixed with patch from 02.06.20018
