### ISSUE TITLE
Can not use AH after visiting the bank

### ISSUE THREAD

**Issue by Skraldesovs** [WarEmu/WarBugs#11818]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
I should be able to use the AH after visiting the bank.

Steps to reproduce the problem:
Visit the bank and after that visit AH and click on an auctioneer. They do not open the AH for you.
This can be reproduced and issue is solved when logging out and in again. 

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Tried with different chars on order and destro. not reproducable
