### ISSUE TITLE
Chosen tactic "Flawless armor" bug

### ISSUE THREAD

**Issue by DUSKANGEL** [WarEmu/WarBugs#1182]
Its increase my chance to be critical hit. From 17% to be critical hit its put it to 27%

**Comment by ozarmidrashim** [comment]
Client display issue.

**Comment by Luuca** [comment]
@ozarmidrashim 
So you are saying that although our tooltip under Initiative is displaying an increase of 10% chance to be crit, the game mechanics are actually 10% less? How can I (or you) verify this?

**Comment by Evildoor** [comment]
Visual bug was fixed as well, closing. @Luuca - it can be verified by measuring the crit chance against you - by gathering several mobs, letting them hit you and collecting statistics. For example, Enemy addon has such functionality - i used it to measure parry chance.

**Comment by Evildoor** [comment]
Update: visual bug (not sure about real one) is still present ONLY on developer server, not on Martyr's Square.

**Comment by Evildoor** [comment]
Fixed.
