### ISSUE TITLE
concealment morale 1 versus word of pain (sorcerer) automatic disrupt dont' work it's normal?

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11826]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*
 
morale 1 concealment : "you are able to dodge and disrupt all magic attack against you for 7 seconds"

Expected behavior and actual behavior:
The morale 1 concealment don't work versus word of pain

Steps to reproduce the problem:
cast a word of pain (sorcerer skill) and cast morale 1 concealement (engineer and sw)

Screenshots/Videos or archive.org evidences:

**Comment by Torquemadra** [comment]
you can disrupt the application you cant disrupt the backloaded damage once its on you
