### ISSUE TITLE
[PQ] destro can participate in BC PQ the Defiled Anvil

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#11820]
all mobs kills are counted and you can get reward for the PQ

https://monosnap.com/file/w50EYUC1Ou56pNyj3zbU09ZiOd7EeK

**Comment by sioding** [comment]
I do not see any problem in participating to the PQ as a destro.

**Comment by Nfkillz** [comment]
it is order`s PQ
