### ISSUE TITLE
Liniment of War: Fervor

### ISSUE THREAD

**Issue by nohh** [WarEmu/WarBugs#11824]
Expected behavior and actual behavior:
Liniment of War: Fervor increase crit change by X*1.05 instead of X+5%

Screenshots/Videos or archive.org evidences:
without liniment:
![without](https://user-images.githubusercontent.com/19315739/40811461-f4a821cc-6539-11e8-9871-4977117790f5.png)

with liniment:
![with](https://user-images.githubusercontent.com/19315739/40811463-f6e96400-6539-11e8-97b2-68ad946a33c3.png)

**Comment by sioding** [comment]
Fixed with patch from 02.06.20018
