### ISSUE TITLE
[Ability] "Guild Standard" Can use abilities with the guild standard movement buff

### ISSUE THREAD

**Issue by Sciberr** [WarEmu/WarBugs#11822]
An introduction:
I was still able to use abilities with the guild standards movement speed buff and even when I died it wasn't destroyed because it wasn't equipped either. 

Evidence:
https://youtu.be/GHnQo6VpYQI

How to reproduce the bug:
To recreate it just become a guild standard and buy the Campaigners War Standard. For some reason you need the Campaigners War Standard to get the buff, and the other two standards only remove the buff. Use the Campaigners War Standard to get the speed buff and you should still be able to use abilities as well.

**Comment by sioding** [comment]
fixed on live
