### ISSUE TITLE
Tok unlock for entering sewers?

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11821]
I don't have Tok unlock when I entered sewers. They have a tok unlock like when you enter bastion stairs?

**Comment by Ryanfawkez** [comment]
There's no influence entry for the Sewers of Altdorf, so I doubt it.

**Comment by sioding** [comment]
So @thorbolt80  - if you have any proof for it - it would be great to see it.

**Comment by sioding** [comment]
Duplicate of #9653
