### ISSUE TITLE
Stuck at "Warpblade Tunnels"

### ISSUE THREAD

**Issue by Imeriath** [WarEmu/WarBugs#11825]
Issue:
!Please consider that I'm inexperienced about such topics and that english is not my native tongue! Please keep it simple.

Order side: I'm stuck at the location named "Warpblade Tunnels".
Character: Shadow Warrior

Expected behavior and actual behavior:

Expected behavior: When I entered the portal, I entered a unfinished place. The problem is I keep dying, being slain by myself. I tried it with commands like /stuck and /debug BUT >actual behavior<:

These commands don't work. I can't escape. I keep dying immediately after respawning the same buggy location. Thus waiting 5 seconds for the command to be able to set in, like I was told in the chatbox doesn't work. I just get following text after dying:
"You have fallen through the floor, instead of falling and getting stuck somewhere you get terminated."

Steps to reproduce the problem:
The entrance can be found behind a shelf in the basement of a tavern called something like "Hissing Cat" I guess. The tavern is located at a corner of the harbor of Altdorf.

I'd be glad if somebody can help me. I'll be patient if this issue can take some time. I also think that it is important to warn other players about this issue. No more characters should get stuck out of sheer curiosity. :)

Screenshots/Videos or archive.org evidences:
![imeriath_000](https://user-images.githubusercontent.com/39815223/40816405-11ae11ba-654d-11e8-99c6-dd3418c630a7.jpg)

![imeriath_001](https://user-images.githubusercontent.com/39815223/40816438-48e0c9e8-654d-11e8-9385-062ea51198cc.jpg)

![imeriath_002](https://user-images.githubusercontent.com/39815223/40816440-48fcbf40-654d-11e8-9b4d-86f4776a87bd.jpg)

![imeriath_003](https://user-images.githubusercontent.com/39815223/40816441-491e2860-654d-11e8-832b-d1f7ed843de9.jpg)

![imeriath_004](https://user-images.githubusercontent.com/39815223/40816442-493aa418-654d-11e8-9e50-32185f5d4ec6.jpg)

![imeriath_005](https://user-images.githubusercontent.com/39815223/40816450-53d0d032-654d-11e8-9292-2a6fb90bbab4.jpg)

![imeriath_006](https://user-images.githubusercontent.com/39815223/40816451-53ec2710-654d-11e8-9f05-c3e76e8d546d.jpg)

![imeriath_007](https://user-images.githubusercontent.com/39815223/40816452-5409cd10-654d-11e8-87e4-d7867a485dc3.jpg)

**Comment by sioding** [comment]
Please do a double /stuck after you have chose "Play" on the character screen. put /stuck into your clipboard and paste it twice after the loading screen appears.
