### ISSUE TITLE
Quest: Nobwart Noggins

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#1183]
Nobwart is a lv1 NPC found in a T2 area, all of his quests are at the wrong level/xp/reward for the effort required.

I believe there may be different versions of Nobwart across different tiers, as he is supposed to give repeatable quests across a pairing of zones. According to mmodb he can also be found in Norsca/Nordland

http://i.imgur.com/YTmOR42.png

**Comment by Reggaewaldo** [comment]
Yes I remember that Nobwart was wandering around giving quests and so.

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 01.06.2019
