### ISSUE TITLE
[Engineer] Turret doesn't dissapear at great ranges. Propably Magus too.

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#11837]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Expected, is that at some ranges, I think 200-300feet your build turret is getting destroyed automatically. I dont know at which range exactly.
ATM it doesnt get destroyed at ranges of around 500-600 feet.

I haven't tested it, but reports say it is the same on the magus.

Steps to reproduce the problem:
See video.

Screenshots/Videos or archive.org evidences:
https://youtu.be/UnMh8xqitqQ

**Comment by Flavor-burst** [comment]
Definitely happens to Magus:

![image](https://user-images.githubusercontent.com/39884574/40889599-69373510-6737-11e8-9bff-cefdabb5757d.png)

That said, I constantly see the despawn message on my Eng when I get out of range, so I feel like there is something specific that is triggering it.

**Comment by Natherul** [comment]
fixed in next patch for both careers

**Comment by sioding** [comment]
fixed with patch from 09.06.2018
