### ISSUE TITLE
2 potions of acclaim : same effect but different price

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11839]
Same effect but different price :
First one : 40 seal of examplar
Second one  : 20 seal of examplar and 40 seal of parangon (much harder to get)

There is a different effect with the most expensive one?

![thorbolt_267](https://user-images.githubusercontent.com/16274785/40899819-1eca15b4-67c9-11e8-8193-3ddc16974f73.jpg)

**Comment by sioding** [comment]
No @thorbolt80  - the price is fine as it is. Its you choice from which seals you want to spent more for the buff. Its not wrong that both potions have 35% more renown - it was never designed to have one with more % renown. So sorry - working as intended - no bug. close
