### ISSUE TITLE
Lost my gold just now

### ISSUE THREAD

**Issue by Greygan** [WarEmu/WarBugs#11835]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Around 23:05 there was a server restart, and at this time, I was creating with my brother a new character in the destruction ( I created a chosen - Andical, and my brother created a Black Orc - Drukkar)

We tried to send from my main dwarf character in Order - Greygan (lvl 30) 1 gold to Destruction to buy noob sets and when I logged my dwarf, there was only 41 gold (from 180g I had).
I noticed its not possible to send gold between realms but instead of losing only that gold I lost 139 .....)
Its really frustrating to see 2 days of farm gone with no reason.

**Comment by sioding** [comment]
This is no bug. You can´t send gold between order and destruction toons. close

**Comment by Greygan** [comment]
but if I tried sending 1 gold why instead of losing only 1 gold I lost 139g? LOL please read better thanks
