### ISSUE TITLE
Annihilation T4 Epic Quests - Duke Wickham

### ISSUE THREAD

**Issue by Grimgarl** [WarEmu/WarBugs#11833]
Duke Wickham is no longer in the Rieksguard castle and therefore the T4 epic quest chain Annihilation is not completable.  I cleared the 1st stage of the PQ in order to get to the first floor but he is not there.  I searched the entire castle and he is not there.

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
That guy stands 46,1/57k on the map and isn´t in the PQ anymore - cause we do not want epic  quest NPC inside the ch22 hard PQs.  I will update the quest description and the questmarker. thanks for the ticket.

**Comment by sioding** [comment]
fixed with patch from 09.06.2018
