### ISSUE TITLE
[Engineer] Keg Heals in Group only on <= 30 feet.

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#11832]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
The Keg in a group setup should heal members in 60feet range.
Currently it stops healing if you are over 30 feet away.

Steps to reproduce the problem:
Setup Keg, place Turret with range indicator. move away till 40 feet away, then keg stops to healing.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Your testing screenshots please.

**Comment by thorbolt80** [comment]
Ok I took lesti with me and we have done test : keg don't heal after 30 feet instead of 60 feet.
![thorbolt_264](https://user-images.githubusercontent.com/16274785/40873991-faaf1a18-6669-11e8-98d9-c314bcb1f162.jpg)

![thorbolt_265](https://user-images.githubusercontent.com/16274785/40873994-0396c5ea-666a-11e8-8e97-9611076172b9.jpg)

**Comment by Torquemadra** [comment]
and why should the keg be working 60ft away?

**Comment by LestiArdisson** [comment]
After an 30 page Keg-Whine Thread a Nerf was placed on the Engineers Keg.

As an Explanation by Natherul:
Post#54 » Wed Jan 11, 2017 9:23 am
Guys, the keg had its OWN discussion in the balance topic. And Aza clearly stated he will "nerf" the keg in order to also buff the Engi career in the future when we have more granular control of the client.

If you keep whining about the keg here without no constructive criticism (in relation to the patch) I will either issue warnings on your accounts or close this thread permanently.
Link: https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=19283&p=212210&hilit=keg+60#p212210

From Patchnotes on 7/1/2017
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=19283&hilit=keg+60#p211558

From Wargrimnir:
[Combat and Careers]

Engineer

- The Gun Turret improves range to a maximum of 25%, but still improves range by 5% per stack. This means that having more than 5 stacks of Improvised Upgrades will not improve your range.

- Bugman's Best now heals group members instead of all allies, but its range increases from 30ft to 65ft.

Magus

- The Pink Horror improves range to a maximum of 25%, but still improves range by 5% per stack. This means that having more than 5 stacks of Unholy Empowerment will not improve your range.

The balance team will have the responsibility of deciding what further to do with these classes.

**Comment by thorbolt80** [comment]
Thank Lesti for you all efforts to find this old post of Wargrimnir.

**Comment by Torquemadra** [comment]
This is something that was never in place, possibly because the heal radiated from the player as opposed to the object which was fixed months ago, regardless the change wasnt ever made. You will need to start a new balance proposal.
