### ISSUE TITLE
Dwarf character giving elf quest

### ISSUE THREAD

**Issue by Mcgotrek** [WarEmu/WarBugs#11842]
Furmir Sourhelm
Dwarf chapter 17
Quest: The Lance of Lothern
Issue: It's a dwarf character but he's giving a elf quest. Wrong character skin?

![btmcg](https://user-images.githubusercontent.com/19507230/40964297-0ee1d064-68ab-11e8-933e-762fd6fc7acb.png)

**Comment by sioding** [comment]
Checked the quest description of all three steps - looks fine fpr me - no elvish things.
