### ISSUE TITLE
Deleted Guild on server crash 4-5 June 2018

### ISSUE THREAD

**Issue by Eusebeus82** [WarEmu/WarBugs#11843]
Expected behavior and actual behavior:

On 4 June 2018 Created guild for low level characters called " Seraphim " (note spaces at end and beginning as "Seraphim" was taken.

On morning of 5 June 2018 guild had simply vanished. I believe there was a server crash or outage in the intervening period.

Guild had 10+ character members from 5 accounts, and we had filled the guild vault with 1000 gold and a vast selection of potions and talismans for low characters, so its a big loss of investment. Is there any chance of investigating this? Or will the guild maybe re-appear after a sever reboot?

Steps to reproduce the problem:
Get unlucky? Impossible to actively reproduce this, although I think some other guilds have had same issue before.

Screenshots/Videos or archive.org evidences:
Can't provide any meaningful pics for this.

**Comment by sioding** [comment]
Hey @Eusebeus82,

we know that problem already: #11072

So its a known issue and i will close this ticket with a reference to the existing one. In your case its kinda hard, cause of the big amount of gold.  You can try to get in contact with a gamemaster or the boss of the GM´s - wargrimmnis via forum PM. Maybe he can do something - but unfortunatly i can not help on this side of the project.
