### ISSUE TITLE
Marauder nad WH

### ISSUE THREAD

**Issue by deathkylem** [WarEmu/WarBugs#11845]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
I will not show screens because i dont waste my time for 0 rewards, i reported the 20% free magic reduction to BO (ni si quiera me dieron las gracias). Now i discover that Wrecking Ball can be use disarmed if you want... fixed if not, dont fixed (my main is a mara, better for me). And Burns Away lies continue be undefendeable. Ty

Steps to reproduce the problem:No more time to explain it, believe me if you want =)

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
So you don´t  want to waste your time unless you got rewarded.. Well - nice attitude. Nevertheless - as we ask everyone here which reports ability problems: Please add your testing screenshots.
