### ISSUE TITLE
Char damage issue

### ISSUE THREAD

**Issue by Slowbra87** [WarEmu/WarBugs#11848]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: I put a ticket into a GM and in his response he told me to open a bug report about it. About a week ago I was seeing normal damage/crit damage from my WE. For the past week maybe week and a half my damage has just be gone. I'm hitting people for around 100 damage and critting them for around 500. Before I was seeing AW crits for around 11-1300 damage and PA crits from 15-1700. I've tried different gear set ups and different RR point set up and nothing is seeming to work.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

![image](https://user-images.githubusercontent.com/40008125/41067952-722c6610-69b5-11e8-885f-8590f44aa066.png)

![image](https://user-images.githubusercontent.com/40008125/41067975-91da3b36-69b5-11e8-9f72-63771633fcb6.png)

**Comment by grunbag** [comment]
It think it’s fixed while ago
