### ISSUE TITLE
Witch Steel Gladius Chapter 22 Darkelf Blackguard inf reward

### ISSUE THREAD

**Issue by edavoc** [WarEmu/WarBugs#11849]
The stats on this chapter reward weapon are all wrong for the class. 

Stats are strength, willpower, and intelligence  which don't make any sense on a weapon for a tank class.
![malikor_000](https://user-images.githubusercontent.com/16967436/41120101-8a4cf126-6a62-11e8-9be1-e324789e1db3.jpg)

**Comment by sioding** [comment]
Fixed with patch from 06.07.2018
