### ISSUE TITLE
Wrong respawn leads to old event area (Kegs End)

### ISSUE THREAD

**Issue by Kosovolt** [WarEmu/WarBugs#11840]
So if you die near the broken bridge in death peak, and respawn, you respawn where the kegs end event area was (Where you teleported to get the items with keg ends coins)
![kosovolt_010](https://user-images.githubusercontent.com/39867505/40941271-33d1d7ae-67ff-11e8-9498-bcac1cec2a56.jpg)
![kosovolt_011](https://user-images.githubusercontent.com/39867505/40941281-393b91c6-67ff-11e8-86e6-28a3bc7b5961.jpg)
![kosovolt_012](https://user-images.githubusercontent.com/39867505/40941286-3c3f6a8c-67ff-11e8-8e5c-bb55ec2aaaaa.jpg)
Steps to reproduce the bug
Step 1: Fly to thunder mountain
Step 2: Run all the way to Death peak
Step 3: Fall off the broken bridge, hit respawn, and you will now respawn in the old kegs end area.

**Comment by sioding** [comment]
fixed with patch from 16.06.2018
