### ISSUE TITLE
College of Corruption T2-T3 has no bolster

### ISSUE THREAD

**Issue by wdesu** [WarEmu/WarBugs#11853]
In CoC scenario for lvls 16-30 there's no bolster visible in buffs of either faction and lowbies die too easily. I think there's actually no bolster and it's a bug.

![split_014](https://user-images.githubusercontent.com/29466521/41191716-3541134c-6bfc-11e8-9c6f-61d1367ea8a1.jpg)
![split_016](https://user-images.githubusercontent.com/29466521/41191708-2e492426-6bfc-11e8-8548-fbd95901e077.jpg)
![screenshot_000](https://user-images.githubusercontent.com/29466521/41191704-29b9221c-6bfc-11e8-9295-0f66f5c58d44.jpg)

**Comment by Kosovolt** [comment]
The same goes for t4 (If  your a t4 lowbie in that sc.)

**Comment by Natherul** [comment]
should be fixed as of this morning, reopen if it still is an issue
