### ISSUE TITLE
chicken in college of corruption scenario and altdorf

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11851]
chicken inside nordland warcamp. I still remain chicken inside college of corruption scenario
![thorbolt_276](https://user-images.githubusercontent.com/16274785/41189311-49d9e124-6bcc-11e8-9fb6-27ab652d94ac.jpg)

**Comment by thorbolt80** [comment]
![thorbolt_277](https://user-images.githubusercontent.com/16274785/41189363-f6f21016-6bcc-11e8-8b57-1c06c97178d7.jpg)

**Comment by sioding** [comment]
Hotfix should have cleared that. Can you please retest?

**Comment by sioding** [comment]
This is fixed.
