### ISSUE TITLE
"Worn Leather Jacket" won't equip.

### ISSUE THREAD

**Issue by Bloodlet** [WarEmu/WarBugs#11858]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: I made a Blackguard and wanted to level in the Dark Elf starting area. Either as a quest reward or from loot I was given a "Worn Leather Jacket" to replace my Regimental Garb. The game however won't let me equip the item. It gives me a popup to bind it to me but when I try to right click to equip or drag and drop to the proper spot, it does not equip. Restarting the game or reloading ui did not help.

Steps to reproduce the problem:
Explained above.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Hm this is Light Armor - as a BH you can wear heavy armor. since you can not say if its a drop or a quest reward - i can not help at all.
