### ISSUE TITLE
Quest: Chosen

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#1185]
Quest requires you to kill the target and use an item. So far these types of quests do not work well, it should be updated to a standard kill quest and turn in at the appropriate reward giver.

http://i.imgur.com/cMjcwEZ.png

**Comment by milosxe** [comment]
It's not fixable atm. You won't get the usable item after killing the mob, but you can still return the quest to the quest giver, and proceed to the next quest in chain.
