### ISSUE TITLE
Herald Orelon - just 1 Scout's Emblem per unlimited pots

### ISSUE THREAD

**Issue by Tyramissoux** [WarEmu/WarBugs#1186]
When buying more than one pot from the T2 SC weapon vendor via shift click, you only have to pay one scout's emblem per how many you pots you entered. Probably works for weapons, too (though haven't tested).

**Comment by ozarmidrashim** [comment]
@nalgol

**Comment by milosxe** [comment]
This issue has been fixed. Shift+click buying works as intended at the sc vendors now.
