### ISSUE TITLE
Steamtank Whistle has no soundeffect.

### ISSUE THREAD

**Issue by velkos4ever** [WarEmu/WarBugs#11862]
one of the rewards from the event(Steamtank Whistle) has no sound effect on it when used

**Comment by ninhojoi** [comment]
I have the same problem !!
![roofos_001](https://user-images.githubusercontent.com/40143132/41202008-51f0222e-6c99-11e8-9f3e-04f1e9ad90b1.jpg)

**Comment by sioding** [comment]
Please do not hijack other reports ninhojoi. Removed your comment cause there is already a report for your problem.

**Comment by MKorin** [comment]
For me there is sound but its short and animation is too fast

**Comment by sioding** [comment]
Checked that on my own too and have a sound.
