### ISSUE TITLE
At T1 runs the level 40 engineer

### ISSUE THREAD

**Issue by Mr0wl13** [WarEmu/WarBugs#11861]
Today is 06.10.18. At T1 runs the engineer under the nickname Pineapples and quietly kills the players. This is probably some kind of bug that is not often but not very pleasant.
[
![xakyp_002](https://user-images.githubusercontent.com/22168095/41200538-077b548c-6caf-11e8-8b23-11eec41cfd8b.jpg)
![Uploading Xakyp_003.jpg…]()

](url)

**Comment by sioding** [comment]
Already alarmed a GM thanks for reporting. GitHub got him.
