### ISSUE TITLE
Sigmartide Warshrines wont accept completed quest

### ISSUE THREAD

**Issue by Cylwen** [WarEmu/WarBugs#11860]
Expected behavior and actual behavior:
The Curious Collector in IC displays the yellow quest complete icon, and should allow the Sigmartide Warshrines quest to be completed.  Instead, there is no result when clicking the Complete button.  The quest window closes, but the quest remains uncompleted, and no reward is granted.

Steps to reproduce the problem:
1. Complete the Sigmartide Warshrines quest.
2. Go to The Curious Collector questgiver in IC.
3. Click Complete.  
4. The quest window closes, but no reward granted, and the quest remains incomplete.

Restarting the game or reloading ui did not help.

Screenshots/Videos or archive.org evidences:
![quest bug](https://user-images.githubusercontent.com/38857938/41198878-c448e5a4-6ccb-11e8-8fa4-8e8d30b03e70.jpg)

**Comment by Ryanfawkez** [comment]
Are you sure that you have both objectives completed? Sadly some quest objectives allow the quest to seem to be completed at the NPC, but you are still required to do whatever the quest has for objectives.

**Comment by sioding** [comment]
No answer for 13 days - close
