### ISSUE TITLE
BC stonetrolls

### ISSUE THREAD

**Issue by Lefze** [WarEmu/WarBugs#11865]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
The bug affects the rank 36 stonetrolls that previously were rank 40 champs. They only use their knockdown, no attacks besides it. The attack does zero damage.

Steps to reproduce the problem:

Attack the trolls.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Thanks for the report. Can wer please have a screenshot or at least a loc - cause "the BC stonetrolls" won´t help to find the NPC.

**Comment by Lefze** [comment]
My bad, assumed "stonetrolls that previously were rank 40 champs" was enough for anyone to instantly know which spot I was referring to. Will upload location or full video of the bug when I'm home depending on how awake I am, but asking literally anyone that used to scavenge should clarify which spot exactly it is. Anyways, sorry for not including it right away.

**Comment by Lefze** [comment]
Video up

https://www.youtube.com/watch?v=-5XUN08q4gU&feature=youtu.be

**Comment by grunbag** [comment]
Fixed at next patch

**Comment by sioding** [comment]
fixed with patch from 04.08.2018
