### ISSUE TITLE
[sigmartide] Can't collect meat from the hungry vultures. 

### ISSUE THREAD

**Issue by Gareth80** [WarEmu/WarBugs#11870]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![erih_000](https://user-images.githubusercontent.com/40175744/41241089-c88fecbe-6da4-11e8-9931-8b1ba2a2f8d8.jpg)
![erih_001](https://user-images.githubusercontent.com/40175744/41241094-cb3df276-6da4-11e8-9c09-69c67197041c.jpg)

**Comment by NorKalli** [comment]
fix pending hotfix, for now look in the top right of your first screenshot- kill that vulture.

**Comment by sioding** [comment]
fixed with patch from 16.06.2018
