### ISSUE TITLE
Quest: Blighted Ambition (shaman)

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#1187]
Rewards include heavy armor, and have no stats assigned.

http://i.imgur.com/NpZVbdC.png

**Comment by milosxe** [comment]
Quest rewards are not completely fixed. One heavy armor reward still remains and has no restrictions for cloth classes. Stats are still missing.
![fizzy_004_cr](https://cloud.githubusercontent.com/assets/13332067/9975943/02eaf502-5ed0-11e5-8330-88ed95f7f10a.jpg)

**Comment by wargrimnir** [comment]
Checked this on my Chosen. Looks like rewards between this and Hopeslayer are mixed up and items are still incorrect.
http://www.warbits.com/gold-quests-114-Blighted-Ambition.html
http://www.warbits.com/gold-quests-2692-Hopeslayer.html

http://i.imgur.com/JlNn2O4.jpg

**Comment by saupreusse** [comment]
fixed
