### ISSUE TITLE
[Bug] The Glory of Ulthuan - reward

### ISSUE THREAD

**Issue by McConn75** [WarEmu/WarBugs#11875]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Finished last step, cant turn in the reward, since it wont get marked as done on th e main quest page

Steps to reproduce the problem:

![feawen_033](https://user-images.githubusercontent.com/10255765/41270229-582a9f3a-6e0a-11e8-8c39-600007d901d9.jpg)
![feawen_031](https://user-images.githubusercontent.com/10255765/41270234-5f5d55cc-6e0a-11e8-95e0-f0ff02d97dfb.jpg)

Screenshots/Videos or archive.org evidences:

**Comment by Lheana** [comment]
After a test, I could complete the quest but it did not let me finish the quest when selecting some items. Worked when I selected the first one.

**Comment by Lheana** [comment]
Reduced the number of reward possibilities, which should fix this.

**Comment by sioding** [comment]
Fixed with patch from 18.09.2018
