### ISSUE TITLE
Quest: Sigmartide Battleshrines couldnt be completed

### ISSUE THREAD

**Issue by exotlv** [WarEmu/WarBugs#11889]
Trying to Complete quest by pressing the button but nothing happening. Cant either take new quests.

Expected behavior and actual behavior:
Quest is completed / couldnt be completed

Screenshots/Videos or archive.org evidences:

![image](https://user-images.githubusercontent.com/8436809/41400027-9e5369c2-6fc4-11e8-86a5-8e9c48b13fc7.png)

**Comment by Ryanfawkez** [comment]
Make sure you've fulfilled the objectives required; can't see them on your UI

**Comment by sioding** [comment]
Liveevent ended - close
