### ISSUE TITLE
Sigmartide: Soup is Good Food (maggot/rat killing)

### ISSUE THREAD

**Issue by Eusebeus82** [WarEmu/WarBugs#11883]
Expected behavior and actual behavior:

Order
At the second part of this quest given from the slayer NPC in T2, you are instructed to kill a mob to obtain "mysterious meat". Quest description indicates that maggots should be killed

Destro
At the second part of this quest given from the troll NPC in T2, you are instructed to kill a mob to obtain "mystery meat". I understand rats are to be killed.

It seems clear, and others have completed and confirmed that the required mobs are inside the enemy keep. However, currently the friendly status of the mobs seems reversed. There are rats hostile to order inside destro keeps, and maggots friendly to them inside order keeps.

It seems that therefore neither order or destro can kill the required mobs to complete this stage.

Steps to reproduce the problem:
Visit appropriate active destro and order keeps, or see screenshots from order perspective below.

Screenshots/Videos or archive.org evidences:
![eusebeus_005](https://user-images.githubusercontent.com/18599533/41304434-0d60550e-6e68-11e8-858a-058cf4dfd976.jpg)

![eusebeus_006](https://user-images.githubusercontent.com/18599533/41304715-d0e48ea0-6e68-11e8-84bd-6deccf6ee968.jpg)

**Comment by NorKalli** [comment]
You're trying to do the t2 step... in t3 :3
