### ISSUE TITLE
Quest: Hopeslayer (shaman)

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#1188]
Rewards include Soldier's/Dutiful Grimbraces heavy armor.

Soldier's Greenbringas should have +22 Int 
http://war.mmodb.com/items/soldiers-greenbringas-91495.php

Greenbringas of the Dutiful is missing +12 Initiative 
http://war.mmodb.com/items/greenbringas-of-the-dutiful-93401.php

http://i.imgur.com/vGHav6n.png

**Comment by milosxe** [comment]
Heavy armor rewards have been fixed. They belong now to the right (armor) class.
The missing stat issue is still there, probably for every class.
![fizzy_002_cr](https://cloud.githubusercontent.com/assets/13332067/9975936/2e0c6820-5ecf-11e5-9dbc-41d4463b71b0.jpg)
![fizzy_003_cr](https://cloud.githubusercontent.com/assets/13332067/9975937/336a96de-5ecf-11e5-903c-c59e768c11b1.jpg)

**Comment by Reggaewaldo** [comment]
I have checked the items and added the missing stats. The change will go live with the next update.

Closing.
