### ISSUE TITLE
Siege weapon bolt thrower and repeater won't release when you get away

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11887]
When you walk few feet from siege weapon normally they release. Here not in the screenshot. I am more than 100 feet away and I have still control of it. They currently release more than 300 feet away (around)

I tried to use bolt thrower at this range and it's possible.

![elendir_006](https://user-images.githubusercontent.com/16274785/41393573-bbd80d0e-6fa6-11e8-8120-1507af0d6098.jpg)

**Comment by aperson12** [comment]
bug reappeared with the same effects and source, cant  use skills/items unless i go back to the specific siege weapon and once in awhile(1/5 of the time) even that wont work, ill click on the siege weapon but no menu will show up

hope im doing this right so i apologize in advance.

**Comment by Natherul** [comment]
this should have been fixed by now, if not please report back
