### ISSUE TITLE
Killed enemy at skarlok spawn dragonwake got 0 renown.

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11880]
Killed a level 36 magus. I got 0 renown. Normal?
![harmonie_000](https://user-images.githubusercontent.com/16274785/41282904-843f0fc2-6e35-11e8-856c-557bc4601da5.jpg)

**Comment by sioding** [comment]
dragonwake is not an active zone in your screenshot - thats why you don´t get any renown. working as intended
