### ISSUE TITLE
Caledor order warcamp respawn point got 30 000 damage

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11888]
When I walk away from the healer 30 000 damage
see damage in the combat log
![elendir_003](https://user-images.githubusercontent.com/16274785/41393781-a6291dbc-6fa7-11e8-82c8-6536f3e0ec6d.jpg)

**Comment by Natherul** [comment]
cannot repliacte, this is terminate damage which should only be sent under certain circumstances. Please try and replicate this and if you can please tell exactly under what circumstances.

**Comment by sioding** [comment]
also tried to reproduce.... but could not.
