### ISSUE TITLE
Man-bear-pig transformation

### ISSUE THREAD

**Issue by Jandeporas** [WarEmu/WarBugs#11895]
**Expected behavior and actual behavior:**
Use Kossar's Helm and transform into a bear, using any skill should transform you back to normal

**Steps to reproduce the problem:**
Use Kossar's Helm transforming your character into a bear, use flee skill to cancel the bear look, others will see your character becoming man-bear-pig but you won't see nothing weird

**Screenshots/Videos or archive.org evidences:**
https://www.youtube.com/watch?v=9Izt7aHNJfs

**Comment by grunbag** [comment]
It’s a graphic bug , note sure we can fix it now
