### ISSUE TITLE
Quest: Temptress (shaman)

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#1189]
Entrop Robefings should be +11 INT +11 INI +3 WIL
http://war.mmodb.com/items/entrop-robefings-92368.php

Green Bringer's Robefings should be +14 INT +11 INI
http://war.mmodb.com/items/grief-bringers-robefings-92434.php

**Comment by milosxe** [comment]
![fizzy_000_cr](https://cloud.githubusercontent.com/assets/13332067/9975919/61816e7c-5ece-11e5-8906-7d5a3701ab61.jpg)
![fizzy_001_cr](https://cloud.githubusercontent.com/assets/13332067/9975920/68a17896-5ece-11e5-847c-58594eb2242c.jpg)

**Comment by Reggaewaldo** [comment]
The change has been made in the DB, this will be applied to the server when the next hotfix/patch is applied.

Closing.
