### ISSUE TITLE
Stuck at loading screen

### ISSUE THREAD

**Issue by Kozhiie** [WarEmu/WarBugs#11893]
im stuck at loading screen after l ast patch.
Tryed to log in a few of my chars. 
But with same result. :( 

Tryed stuck command. x2 ..
but only dif.. is that now ive got loading screen för norsca .

like a loop.

anyone else got this problem?

**Comment by sioding** [comment]
Sorry but this is not the forum. Please ask this here:
https://www.returnofreckoning.com/forum/viewforum.php?f=4
