### ISSUE TITLE
.Guildinvolve - Have to zone back in to get +5% RR Bonus

### ISSUE THREAD

**Issue by Zaxx0nd** [WarEmu/WarBugs#11894]
When I do the .guildinvolve command in RVR zone, I need to zone out and zone back in to receive +5% RR boon.

Prior to tonight, I would do .guildinvolve and +5% RR boon would show up without having to zone out and zone back in.

Also I was unable to do the .getstat command prior to the zone out and zone back in to check my stats.  When I would check stats (Clearing out targets and targeting myself) I got a message stating I cant do getstats on a member of the other realm. 

Once I zoned back in, getstat would work as normal.

**Comment by Zaxx0nd** [comment]
One more thing to add.  On 6/302018 I did the .guildinvolve command @ Hardwater BO and the guild vault popped up on my screen.  
![guildinvolve_bug](https://user-images.githubusercontent.com/19254707/42185075-85c24cfc-7dfc-11e8-8b17-19b0c39fcf11.jpg)

**Comment by Natherul** [comment]
going through old tickets. This should be fixed by now. If the problem persist please comment back and Ill reopen the ticket and investigate
