### ISSUE TITLE
Influence rewards in high elf chapter 10, except first 2 basics, aren't available

### ISSUE THREAD

**Issue by Bolplip** [WarEmu/WarBugs#11892]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
The rally master of high elf chapter 10 should give all the influence rewards but I could only choose from the first two "basic" rewards and nothing else.

Steps to reproduce the problem:
I have no idea. I am just playing a swordmaster on level 20 and that's about all I can say. Relogging did not solve the problem. Before that, I completed the influence in the "hard public quest" of chapter 10.

Screenshots/Videos or archive.org evidences:
![faladar_000](https://user-images.githubusercontent.com/40275021/41428369-2e3d03b4-700a-11e8-831d-a3a67747f556.jpg)

**Comment by Lheana** [comment]
Could you please provide a screenshot of the ToK page of influence of this chapter please?

**Comment by Lheana** [comment]
Should be fixed next patch

**Comment by sioding** [comment]
fixed with patch from 04.08.2018
