### ISSUE TITLE
The "Paranoid Raven Games" Quest's Last Stage Is Duplicated.

### ISSUE THREAD

**Issue by Volgarn** [WarEmu/WarBugs#11909]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

This last stage of the a quest-line for Destruction in Chaos Wastes that starts in their warcamp, then takes you through the CW RvR lake to two NPCs, before returning to the warcamp.  The last stage is duplicated and can be both accepted and returned twice, getting ~7k XP and 1.5 gold for each.

Steps to reproduce the problem:

If you can auto-advance the quest, just go to Rugger Skullfork in the warcamp and he'll give you two of quests which can turn in to Onnister Preul just a few feet to the right under the purple tent. Otherwise, the quest starts at Onnister Preul, taking you to Daria Ravenblood outside Order warcamp, then Rhece Farseeker southwest of Statue of the Everchosen, and back to Rugger Skullfork in the warcamp.

Screenshots/Videos or archive.org evidences:

![war_2018_06_17_20_02_45_787](https://user-images.githubusercontent.com/38593980/41543248-9592a6a4-72e4-11e8-8ec2-19051bc82b90.jpg)

![war_2018_06_18_10_50_31_086](https://user-images.githubusercontent.com/38593980/41543789-9142ce34-72e5-11e8-8f5e-bf48d941e3d9.jpg)

**Comment by sioding** [comment]
fixed with patch from 27.07.2018
