### ISSUE TITLE
Pets channeling abilities interupted by next pets abilities

### ISSUE THREAD

**Issue by nohh** [WarEmu/WarBugs#11901]
Expected behavior and actual behavior:
Pets channeling abilities interupted by next pets abilities

On an example of magus:
Coruscating Energy is 3 sec channel
Wapring Energy is instant ability

Channel hit 4 times with turned off Warping Energy pet ability (through Loyal Pet addon)
and hit only 2 times with Warping Energy turned on.

![channel_interupt](https://user-images.githubusercontent.com/19315739/41500063-d4a250b2-7193-11e8-9c38-babcbee79744.png)

**Comment by nohh** [comment]
If pets was changing in last patch notes, is any chance to take this bug to work. Squig pets loose a lot of damage cos Spine Fling interuped by Poisoned Spine all times.

**Comment by SecretsOTheP** [comment]
Fix pending. NPCs will no longer attempt to use another ability during a channel unless interrupted.

**Comment by sioding** [comment]
fixed with patch from 09.02.2019
