### ISSUE TITLE
[Desciple of Khaine] Soul shielding

### ISSUE THREAD

**Issue by Ardenau** [WarEmu/WarBugs#1190]
Soul Shielding does not work for all member of group. It is work only for myself.
![ardenau_001](https://cloud.githubusercontent.com/assets/13996760/9560880/21f344ae-4e36-11e5-8578-cdb5a16e210b.jpg)

**Comment by Evildoor** [comment]
https://github.com/WarEmu/WarBugs/issues/1172
Why another report?
