### ISSUE TITLE
Older Event Items alternate Appearance

### ISSUE THREAD

**Issue by Marawo** [WarEmu/WarBugs#11900]
The Halloween facemask alternate skins from older events don't work properly. Originally these were pocketitems hence they miss the "alternate Appearance available" property. The ones you can obtain from the anniversary event "Sigmartide" are considered Helms now. In the Database this seems to have changed the older pocket facemasks to Helm as well, but missing the "alternate Appearance available" property making it only equippable like regular gear.

**Old Masks:**
![skullold](https://user-images.githubusercontent.com/29643742/41499145-d7f92514-717b-11e8-84a7-955fcae0a40e.jpg)
![faceeaterold](https://user-images.githubusercontent.com/29643742/41499146-d9a6a9ea-717b-11e8-8b8c-d13a06e77dc7.jpg)

**New Masks:**
![skullnew](https://user-images.githubusercontent.com/29643742/41499158-e0189130-717b-11e8-8186-71283da13041.jpg)
![faceeaternew](https://user-images.githubusercontent.com/29643742/41499162-e1af7e32-717b-11e8-9c32-239b0b8031db.jpg)

**Error Message**
![textcannotbeequipped](https://user-images.githubusercontent.com/29643742/41499190-f7d4c816-717b-11e8-85e1-51974c1acd2a.jpg)

**Comment by Lheana** [comment]
This has been fixed.
