### ISSUE TITLE
Defenders Defeat mob issue

### ISSUE THREAD

**Issue by Deladriendil** [WarEmu/WarBugs#11904]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
expect the mobs react as enemies.
actual behavior is that the  Longbowman and shieldbreaker give the error 'target is not attackable'
 - avelorn chapter 10

Steps to reproduce the problem:
go the area north of the DE camp where these mobs spawn. tab target through, you will note that the longbowman and shieldbreakers have a white circle under them. not a red one. when you either you will get the error.

forum name: Ambalynn

**Comment by sioding** [comment]
Not all NPC´s need to react as enemies - some of them are maybe part of a quest where you have to talk to them. I will close this report.

**Comment by Deladriendil** [comment]
in the context of this quest all target NPCs are enemies. the longbowmen and shieldbreakers are required to be killed as part of the quest progression. so they shouldn't have a white circle under them. they also attack when a destroy player gets close to them. i'd assume a conversational/quest giving NPC would not do so.
