### ISSUE TITLE
Stalker's Armbracers appearance

### ISSUE THREAD

**Issue by zegotax** [WarEmu/WarBugs#11914]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

These gloves have different appearance in game compared to the character selection screen.
Character selection screen model was used also in game back in t3 days, and looks unique and pretty nice.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

![screenshot_000_cr](https://user-images.githubusercontent.com/36109086/41662560-51b3edba-7499-11e8-90b9-640b76dc07af.jpg)
![asd_000_cr](https://user-images.githubusercontent.com/36109086/41662576-5637cd02-7499-11e8-9d66-7be3f39eae89.jpg)

**Comment by Torquemadra** [comment]
yeah no, they were bugged now they are not
