### ISSUE TITLE
Order side pop in college of corruption starting point then died by lava

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11910]
pop in college of corruption starting point then died by lava 4 tick 1500 each (have a look at the log on the screen)
I didn't move from starting point for order. I died during loading screen (I heard the tick) Then I release then I died again (lava same)
![thorbolt_300](https://user-images.githubusercontent.com/16274785/41541235-41aaaf22-7312-11e8-94a6-33df7e2bb34b.jpg)

**Comment by Kaelang** [comment]
Played many matches on College of Corruption as Order and haven't experienced this in the latest version of RoR. Please re-open if issue persists.
