### ISSUE TITLE
[Sigmartide] Skulltakers : Quest deleting Skulls of the Damned

### ISSUE THREAD

**Issue by CrimsonFenris** [WarEmu/WarBugs#11913]
I noticed a loss of my first 10-12 Skulls of the Damned I already had dropped, before starting this quest.

I noticed the complete loss of them in my backpack, after toroughly searching if I made a mistake, but it appeared those items simply are gone, and the quest start from 0.
I checked if I moved them (it's not movable or sellable anyway), or accidentaly bought something with them (I had no idea how to spend them at the time being).
I checked an inventory bug as well (with filters on, stacking all items on one slot), without success.

They simply are gone without explanation, except this specific quest wich require skulls to be collected, so I presume the bug is related to it ; looks like the quest doesn't check the Skulls already obtained, and wipe them from 0...

Someone told me it may be possible to have lost them by clicking on an allied Shrine, but I could not remember such actions (still don't know what it is anyway, still being a nearly complete noob ^^)

It's not a big deal for me since it's relatively easy to drop in RvR battles, but it could be very annoying for others that may see disappear significant amount of currencies...

**Comment by sioding** [comment]
Sorry - no bug at all cause working as intneded. Don´t touch the shrines until the quest is done. (and to be honest... i did the same.)
