### ISSUE TITLE
Game crashes when character flies to Kadrin Valley

### ISSUE THREAD

**Issue by Skullgrin** [WarEmu/WarBugs#11917]
After helping capture the Keep in Thunder Mountain, I went to the flight master and took the fight to Kadrin Valley at which point the game crashed to the desktop. After attempting to relog on to my character (Thargrimm), game crashed again at the load screen. 

Re-entered the game and did the double /stuck command. at which point the Norsca load screen came up for several seconds and then switched to the Praag load screen, which is where my character appeared (Praag is my book of binding bind-point, don't know if this is relevant). I tried to fly from Praag to Kadrin Valley, at which point the game crashed again. Restarted, did /stuck twice, and the Norsca load screen appeared and then switched to the Inevitable City load screen. Character then appeared in Inevitable City. As I wandered about in IC, all the NPC's disappeared and I thought that perhaps the server was crashing so I exited the game and re-entered. Tried to fly from IC to KV and the game crashed again. Re-entered, did /stuck, ended up in Praag again somehow. Rode from Praag to the Chaos Wastes hoping that manually crossing a zone line would reset whatever had broken. Then tried to fly to KV from the Chaos Wastes, game crashed again. Entered again, did /stuck, flew to Thunder Mountain and game crashed. Entered again, this time Thunder Mountain loaded and I rode to KV from there. Lasted in Kadrin Valley for about a minute before the game crashed again. Re-logged, and lasted about 5 minutes before it crashed again.  

Re-entered game, Did /stuck to get to Norsca and it worked properly this time. I then contacted Azmodias to see if he could help with the problems I was having. He had me exit the game and delete the cache. This did not seem to help as when I re-entered the game, I rode to the Norsca chapter 2 flight master, tried to go to KV and game crashed again.

At this point Azmodias had me exit the game and he moved my character to The Shadowlands. I logged back in, tried to fly to KV  and once again the game crashed. Did /stuck, Flew from Norsca to IC, and consulted with Azmodias who suggested placing this bug report. I also have noticed that my quest log is empty and that all the quests in IC have reset for me, meaning that I could do them all again if I were so inclined (again, I do not know if this is relevant however thought I should mention it).  

Any assistance would be greatly appreciated, as I am afraid that this inability to fly to KV may spread to other areas in the game.

**Comment by sioding** [comment]
Thanks for the impressing bugreport but you can not get any help here. This bug tracker is for ingame problems with the game itself - not with the client. It´s also a single problem for one player and not a global one for a lot of players. I see Azmodias already tried to assist you and i would suggest you take a look at this post and follow the todos: 

https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=20075

If that does not help ask warggrimmnir if he can have a look at your character - he and the leads are the only one with acceess to the live DB.

Good luck

Sio
