### ISSUE TITLE
[Choppa] Can't Stop Da Chop visual bug

### ISSUE THREAD

**Issue by Titoos** [WarEmu/WarBugs#1191]
It's redden on the skill bar, and when you use ability it fires but there's error message:
"your curren level is too low to use this ability"

**Comment by ozarmidrashim** [comment]
Unfixable atm.

**Comment by Titoos** [comment]
Ability level checking hardcoded on client side?

**Comment by Evildoor** [comment]
Skill returned to 9 points, so this is fixed now.
