### ISSUE TITLE
Title Vendor in the Undercroft is missing

### ISSUE THREAD

**Issue by Skullgrin** [WarEmu/WarBugs#11918]
Title vendor was mentioned in the 9/6/2018 patch notes, found here - 

https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=26951

Here is a quote from the post - 
"RyanMakara
- Added an additional currency reward for nearly all Scenario quests for every tier. These can be spent on special Scenario titles at the Title Vendors in either the War Quarter/Undercroft, or at either Sigmar's Hammer/Viper's Pit."

I have visited every vendor in the Undercroft and none of them sell titles at this point. I think that the title vendor was possibly removed from this area when the training dummies were added. Please add him back as I cannot use the Viper Pit vendor, as I am not in a guild.

**Comment by sioding** [comment]
Fixed with patch from 30.06.2018
