### ISSUE TITLE
quest - battle at gromril crossing.  can't select rewards

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#11915]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
found i couldn't select a reward to complete this quest

Steps to reproduce the problem:
take gromril crossing scenario, complete and attempt to turn in (as Order realm).

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
With which level have you accepted the quest? Cause with my level 40 character i can not reproduce it.

**Comment by gittoaster** [comment]
Okay, thx.  Either fixed already or my mistake.  I tried to select items but couldn't accept..  closed
