### ISSUE TITLE
Siege weapon you still got icon very far away

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#11911]
![thorbolt_301](https://user-images.githubusercontent.com/16274785/41546335-affc141a-731d-11e8-9fdc-1dabc99d5593.jpg)
Still the icon of siege weapon even very far away (here in gromril scenario)

Normally the icon must disappear when you move even slighty from siege weapon

**Comment by sioding** [comment]
Already addressed. Thanks for the report.

**Comment by sioding** [comment]
Duplicate of #11887
