### ISSUE TITLE
Academy of Corruption Order Heal not able to join the portals

### ISSUE THREAD

**Issue by Zaccar20** [WarEmu/WarBugs#11916]
Hey,
Sorry first of all if i reposte a known problem!
But i can't find some post at the moment.

What happend?
I can't use the portal/door on order warcamp in Academy of Corruption.

How this happend?
I'm not sure... i think its maybe a HoT i used on a living teammate. (i'm a Archemage full heal skilled)

How should it work?
I should be able to join the portal/door to assist my teammates!

**Comment by sioding** [comment]
No thiis is working as intended and does not belongs to one side. Also Destro Players aren´t able to use the portals while in combat. So sorry no bug.
