### ISSUE TITLE
[ToK] wrong unlock 

### ISSUE THREAD

**Issue by desolator87loc** [WarEmu/WarBugs#11924]
Killing a quest centigor near empire ch1 in nordland opens this unlock
![image](https://user-images.githubusercontent.com/40502641/41797154-a133cade-7671-11e8-8f5f-0f03cb287c77.png)

**Comment by Lheana** [comment]
Name of the NPC please

**Comment by Lheana** [comment]
Intended: https://wiki.returnofreckoning.com/index.php/Hot_Deal
Please refer to RoR Wiki for ToK unlocks.
