### ISSUE TITLE
BW - Overlord armor proc

### ISSUE THREAD

**Issue by porterrr** [WarEmu/WarBugs#11921]
the bright wizard proc from the overlord set (swift affliction - 4% extra dmg on person u hit) only procs on a person you have targeted, if u aoe on a group without having 1 of them targeted it will never proc.

this may be how it was designed, but couldn't find any clarification or older posts about this.

**Comment by sioding** [comment]
Sorry but this is not the place to discuss a working ability. Please use the forum for it.
