### ISSUE TITLE
PQ: Lursa's Blight (Chaos CH8 Easy)

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#1192]
Seems to have a nurgling problem. There's ~50 in a very small area, level 1. Looks easy to farm with a Chosen.

http://i.imgur.com/lQadTXy.png

**Comment by Reggaewaldo** [comment]
Thanks for the info will look into it.

**Comment by Reggaewaldo** [comment]
I have looked this up and I have a vague memory that it was like this on live. I have not found any source to confirm as of now though.

**Comment by Evildoor** [comment]
Since we have no proofs that this situation is wrong, and @Reggaewaldo 's statement that it was this way on live, i'm closing this until someone brings more solid info. Although i don't see why anyone should bother.
