### ISSUE TITLE
PQ in The Shadowlands is instantly resetting dirt patches

### ISSUE THREAD

**Issue by Polyphemous99** [WarEmu/WarBugs#11927]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
The "Gloomridge Copse" PQ in The Shadowlands requires clicking on 20 dirt patches.  These patches instantly reset, allowing a player to spam clicks on 1 patch to advance through the stage in a matter of seconds.

Steps to reproduce the problem:

Char name is Polyfemus if you need to get in touch with me.

Screenshots/Videos or archive.org evidences:

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/14893
