### ISSUE TITLE
[Quest] Inevitable power missing

### ISSUE THREAD

**Issue by desolator87loc** [WarEmu/WarBugs#11922]
I created this chosen a while ago, Now I returned and started doing t3 quest. Did all in ch10, 11 and 12 except pve set one, still epic quest is unobtainable. 100% sure didn't pick it. Now I'm 33/31 and don't have an option to do this quest

**Comment by sioding** [comment]
Sorry quest is active and i can accept it without problems. have to be something with your char - please contact a GM ingame.
