### ISSUE TITLE
[Quest] Bone of Contention - Offering bowl missing

### ISSUE THREAD

**Issue by desolator87loc** [WarEmu/WarBugs#11925]
This one was fixed 02/06/2018 via patch notes, quest marker and bowl are still missing

![image](https://user-images.githubusercontent.com/40502641/41805660-4dcc28d2-76b7-11e8-944b-2aa4c5bdf882.png)
![image](https://user-images.githubusercontent.com/40502641/41805662-556482f6-76b7-11e8-9c6b-6713f76b00f5.png)
![image](https://user-images.githubusercontent.com/40502641/41805665-613317dc-76b7-11e8-9f01-9a48b96d44c0.png)

**Comment by Natherul** [comment]
Should be fixed as of todays patch (14/07/2017)
