### ISSUE TITLE
Against All Odds PQ - Shaphery

### ISSUE THREAD

**Issue by benitoben20** [WarEmu/WarBugs#11938]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Hi,

Just before the patch of June 23 2018, I was grinding the PQ Against All Odds in Saphery. The PQ was working fine and now, since the patch, there aren't any orcs anymore. As seen in the picture, the camp is empty and as such, the PQ isnt playable at the moment since there is no orc to kill.

Greetings,

Steps to reproduce the problem:
None

Screenshots/Videos or archive.org evidences:
![lathanielle_002](https://user-images.githubusercontent.com/16641170/41814477-753a239c-771b-11e8-8fc1-a89fdd8cbcc0.jpg)
![lathanielle_003](https://user-images.githubusercontent.com/16641170/41814478-754a8034-771b-11e8-875c-de0635e86ee1.jpg)

**Comment by sioding** [comment]
This is a known issue which happens sometimes and we don´t know why - you have to wait for a server restart
