### ISSUE TITLE
SC queue will not stopped if you switch from t1 to a higher tier

### ISSUE THREAD

**Issue by Volgarn** [WarEmu/WarBugs#11936]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

If you are que'd for scenarios at r15, ding out of T1, you can still get a T1 pop and join it as (at least) a r16. The character has the bolster icon and hovering over it says you're bolstered to r15, though my stats remained at r16 values. My pet was r15 according to the UI, but r16 according to the targeting unit frame, and I was able to use the r16 skill (Trained To Hunt for White Lion).

Screenshots/Videos or archive.org evidences:

![war_2018_06_23_17_11_56_6422](https://user-images.githubusercontent.com/38593980/41814267-a633b856-7715-11e8-84ca-cabd92504d92.jpg)

**Comment by Natherul** [comment]
fixed in the next patch

**Comment by sioding** [comment]
Fixed with patch from 30.06.2018
