### ISSUE TITLE
Penetration bonus from offensive stats do not show up in .getstats. 

### ISSUE THREAD

**Issue by Esperflame** [WarEmu/WarBugs#11934]
.getstats fails to tell me how much parry/block penetration I get from my strength. I'm wondering if all this dodge/disrupt/parry problems are because I'm not getting my bonus at all.

**Comment by sioding** [comment]
Your testing screenshots please.

**Comment by Natherul** [comment]
getstats only shows the pure stats collected not stats gained from other sources like other stats, this is working as intended.
