### ISSUE TITLE
KotBS Mighty Soul Tactic not working

### ISSUE THREAD

**Issue by Zumos** [WarEmu/WarBugs#11931]
**Expected behavior and actual behavior**
Tactic should turn the damaging abilities of Path of Glory into Elemental damage, but we found that this is not working at all. It was tested for Unbalancing Attack and Blazing Blade.

**Steps to reproduce the problem**
To prove the attacks were not doing Elemental Damage, we first did an attack against a shaman without Mork's Buffer, then applied Mork's Buffer and did an attack again. If it was doing Elemental Damage, the mitagation value should be different but as you can see in the screenshots and videos, the values are the same. 

**Screenshots/Videos or archive.org evidences**
Screenshot of KoBS running the tactic:
![war mighty soul tactic ss](https://user-images.githubusercontent.com/19267650/41810630-1f32fcda-7702-11e8-988b-c658537fcb86.jpg)

Unbalancing Attack:
![war 1](https://user-images.githubusercontent.com/19267650/41810637-51743772-7702-11e8-9c55-ad23b155f258.jpg)
![war 2](https://user-images.githubusercontent.com/19267650/41810638-53878e10-7702-11e8-933a-27c122cd9490.jpg)
[Video Proof](https://youtu.be/ePW_KY6YUYc)

Blazing Blade:
![war 3](https://user-images.githubusercontent.com/19267650/41810641-5bd2de8a-7702-11e8-8cc7-5b02d4b5748d.jpg)
![war 4](https://user-images.githubusercontent.com/19267650/41810643-5dda01e0-7702-11e8-848d-1acaf7bce4d0.jpg)
[Video Proof](https://youtu.be/0hEKTgvorJA)

**Comment by Kaelang** [comment]
Discordant Winds / Mighty Soul have been removed in todays patch.
