### ISSUE TITLE
Mourkain Temple Flag issue

### ISSUE THREAD

**Issue by NorKalli** [WarEmu/WarBugs#11935]
when flag runs out of range and resets to middle, the VISUAL flag game object itself remains  where it was dropped, but it is actually reset into the middle.

Therefore, when flag is brought too close to either teams spawn, it is then unable to be picked up in the middle.

![image](https://user-images.githubusercontent.com/19868634/41813457-af3f5b6e-76eb-11e8-8851-886f5da0a41e.png)

**Comment by Natherul** [comment]
Can this please be confirmed as Im unable to replicate this behaviour.

**Comment by sioding** [comment]
No answer since 9th of november. Close
