### ISSUE TITLE
2 bugs for disciple of khaine

### ISSUE THREAD

**Issue by BloodyBakala** [WarEmu/WarBugs#1193]
disciple of khaine by tortute path does not have sanguinary extension buff at 5 lvl

defensive buff of disciple's badge at 22 lvl does not exist.

Thank you

**Comment by BloodyBakala** [comment]
another bug more, at 9 points od torture path, does not give the buff.
I pass this character, nothingthing works...

**Comment by BloodyBakala** [comment]
disciple of khaine is useless right now

**Comment by Evildoor** [comment]
Stupid question: have you just spent 5 points into torture OR spent 5 point into torture and then put a 6th point into Sanguinary Extension itself?

**Comment by Evildoor** [comment]
No reply... Anyway, this works fine on my DoK, closing this.
