### ISSUE TITLE
level 27-28 mobs drops level 7 item

### ISSUE THREAD

**Issue by velkos4ever** [WarEmu/WarBugs#11943]
some mobs that are level 27-28 droped an item that is level 7 here some picture below
![wildnight_026](https://user-images.githubusercontent.com/16551075/41821290-ef87d4a2-77e6-11e8-9fda-2003b073a650.jpg)
![wildnight_027](https://user-images.githubusercontent.com/16551075/41821291-efbafbde-77e6-11e8-815e-ecadadf45fff.jpg)
![wildnight_028](https://user-images.githubusercontent.com/16551075/41821292-f169bca4-77e6-11e8-931e-3dc0249813af.jpg)

**Comment by wargrimnir** [comment]
Looks like the full set of these items were missing from the R7-8 loot tables.
Added for next patch. Removed the random ones at odd levels.

**Comment by Natherul** [comment]
Should be fixed as of todays patch (14/07/2017)
