### ISSUE TITLE
Weapon mislabeled as Axe: Headcracka's Choppa

### ISSUE THREAD

**Issue by vikingofmars** [WarEmu/WarBugs#11945]
Expected behavior and actual behavior:

This weapon should be a sword. It is labeled as an Axe. Pls fix so i can have a flavorful appearance/experience. Thanks bros.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

<img width="960" alt="cutta" src="https://user-images.githubusercontent.com/37393516/41828023-c1c5c708-7800-11e8-9aa0-be94bbaf8edf.png">

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
Fixed with patch from 06.07.2018
