### ISSUE TITLE
Scoutmaster Herold Nordland Art

### ISSUE THREAD

**Issue by Akion1** [WarEmu/WarBugs#11941]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Character 'Scoutmaster Herold' seems disfigured

Steps to reproduce the problem:
WC Nordland Order
[Herold.docx](https://github.com/WarEmu/WarBugs/files/2130887/Herold.docx)

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
This seems to be a one timer cause i can not reproduce it.
