### ISSUE TITLE
[Quest] Revelation (High pass)

### ISSUE THREAD

**Issue by desolator87loc** [WarEmu/WarBugs#11947]
map markers are confused, it says to pick a banner where you should place it and vice versa.
On the 2nd stage quest missing map marker for Malum Greyhand

![image](https://user-images.githubusercontent.com/40502641/41834680-c906b952-785d-11e8-9a7d-809050d9bb25.png)
![image](https://user-images.githubusercontent.com/40502641/41837430-1f3a1b0e-7866-11e8-8501-2dacf0f292e6.png)

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
Fixed with patch from 30.06.2018

**Comment by StaH84** [comment]
Quest still have wrong markers (getting and planting standard)

**Comment by StaH84** [comment]
![bjoorn_007](https://user-images.githubusercontent.com/18528095/53833048-f8464380-3f87-11e9-8033-bfbe32b7660c.jpg)

As You can see banner is taken but quest marker on dwarf camp disappeared

**Comment by StaH84** [comment]
On the another stage of quest, there is no marker of Malum Greyhand in PQ area.
![bjoorn_008](https://user-images.githubusercontent.com/18528095/53833242-596e1700-3f88-11e9-923f-f2c894290d7e.jpg)

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
