### ISSUE TITLE
Mugash's Rippa

### ISSUE THREAD

**Issue by Folgrimma** [WarEmu/WarBugs#11952]
Item listed as sword should be listed as an axe. Able to apply appearance to swords.
![screenshot 1](https://user-images.githubusercontent.com/40577289/41868099-50d9be74-7872-11e8-87bf-6d060be193ae.png)
![capture](https://user-images.githubusercontent.com/40577289/41868104-551b8562-7872-11e8-830f-7c7203cd3329.PNG)

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
Fixed with patch from 30.06.2018
