### ISSUE TITLE
NPC Riellyan Jadeheart seems to be buffed

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#11959]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Taken from the RoR-Wiki:"
**The Ebon Flame - STEP 9**
Kill Riellyan Jadehart (Champion lvl 40) at **56.3k/61.2k.** _in Eataine_"

At said location the NPC can't be found, though the quest can not be completed.

Steps to reproduce the problem:

Move to the Coords and check if the NPC is present.
(Maybe the respawn is broken as the PQ-NPCs don't seem to respawn either)

Screenshots/Videos or archive.org evidences:

![jadeheart1](https://user-images.githubusercontent.com/40274248/41994093-a9a7d400-7a4d-11e8-8bcd-3de5a24e2814.jpg)
![jadeheart2](https://user-images.githubusercontent.com/40274248/41994094-a9ca56ba-7a4d-11e8-957a-862ce12a72b8.jpg)

**Comment by Torquemadra** [comment]
someone erroneously added them to the PQ stages

**Comment by NorKalli** [comment]
npc WAS tied to PQ stage, removed and questmarker shrunk and placed accurately

**Comment by Scophis** [comment]
Riellyan is back again, but now he's a lvl42 Champ and testing how tough he's, it seems like he is now one of those bolstert PQ Champs. Is that intendet?^^

**Comment by sioding** [comment]
Fixed with patch from 30.06.2018

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
Fixed with patch from 06.07.2018
