### ISSUE TITLE
Liniment of Quickend Blades

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#11953]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*
Couldn't find aynthing to Quickend Blades
Expected behavior and actual behavior:
If it read the tool tip correct the liniment should give you 60 Weapon Skill and 5% Reduced Armor Penetration. What it acutally gives you is 60 Weapon Skill and 5% Armor Penetration. Dont know if that is intended but it is kind of a deviation from how I read that tooltip.

Steps to reproduce the problem:
Just use one and do getstats. We also tested it and it didnt change incoming damage.

Screenshots/Videos or archive.org evidences:
![cimbina_074](https://user-images.githubusercontent.com/16117730/41891456-c4540f4c-7914-11e8-8c92-a17bebcddca3.jpg)

**Comment by Pxl555** [comment]
The original liniment 'Quickend Blades' did indeed provide armor penetration on live and not 'reduced armor penetration'. It could be a case of a display bug, or the dev's intending a different implementation.

Source:
https://gaiscioch.com/lore/guide_to_the_liniments.html

**Comment by Torquemadra** [comment]
Op is correct and fix incoming

**Comment by sioding** [comment]
Fixed with patch from 30.06.2018
