### ISSUE TITLE
[Ab changelist] Missing changes BO and SH

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#11967]
The following changes are missing in the changelists:

Black Ork:
- Still saying DYG at 9pts and not mentioning the Chop Fasta buff
- the 10sec icd of Youz see me blok' dat'?! instead of 3sec 

Squig Herder: 
- KABOOM! requires you to be on the ground to activate 
- Sticky Squigz can no longer be activated while rooted or in the air preventing the ability from being wasted
- The Horned Squig's Head Butt will now perform a 2 second knockdown instead of a knock back
- Morale 2 ability Unshakeable Focus removed 
- Reduced Squig Herder pet disarm to 3s duration

**Comment by Natherul** [comment]
any jump ability not fiering while not on the ground will not be on ab changelist but in .ror command as its a general change for all such abilities. 

Looking up the rest.

**Comment by Natherul** [comment]
Fixed as of today (04/07/2018)
