### ISSUE TITLE
T2 ORvR Rewards Missing Talisman Slots

### ISSUE THREAD

**Issue by Volgarn** [WarEmu/WarBugs#11962]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

A number of T2 ORvR Influence rewards are missing talisman slots:

Fangbreaker Steelhelm (White Lion), Dwarf T2 Reward - Has none, should have one.
Fangbreaker Long Axe (White Lion), Dwarf T2 Reward - Has none, should have two.
Spite's Runemantle (Rune Priest), Elf T2 Reward - Has none, should have one.
Mandred's Brassarts (Knight of the Blazing Sun), Emp T2 Reward - Has none, should have one.
Mandred's Ironguants (Ironbreaker), Emp T2 Reward - Has none, should have one.

**Comment by sioding** [comment]
Fixed with patch from 06.07.2018

**Comment by sioding** [comment]
Fixed with patch from 06.07.2018
