### ISSUE TITLE
Visual bug KotBS dual wielding

### ISSUE THREAD

**Issue by Skullgrin** [WarEmu/WarBugs#11960]
Came across a group Knights the other night and 2 of the 3 were dual wielding a sword and an axe. 
![dw](https://user-images.githubusercontent.com/40448982/42000732-e3af5986-7a1e-11e8-879c-d689c73618da.JPG)
I have no idea as to how to duplicate this, only that it is possible. My personal guess would be that a shield has a weapon appearance attached to it somehow.

**Comment by sioding** [comment]
Fixed with patch from 30.06.2018
