### ISSUE TITLE
Cannot Respawn at Nearest Healer After Jumping Off Chittering Bluff at Death Peak

### ISSUE THREAD

**Issue by Mehem** [WarEmu/WarBugs#11961]
Cannot respawn in a different area after jumping off cliff at Chittering Bluff in Death Peak.

Expect to respawn at the nearest healer. Actual behavior  is respawning at the same location with a message in chat stating, "You have fallen through the floor instead of falling and getting stuck somewhere you get terminated."

Clicking the Respawn button repeats the death in the same location over and over. Character cannot escape the area and is trapped by the repeated deaths.

**Comment by sioding** [comment]
Use double /stuck while the loading screen appears.
