### ISSUE TITLE
Diminishing Rations activating when Against All Odds is up

### ISSUE THREAD

**Issue by Skullgrin** [WarEmu/WarBugs#11964]
This occasionally happens in ORvR. No idea what causes it however there should probably be a check to see that DR (tool-tip states that you have a larger army than your opponents) does not activate if the defenders have AAO (tool-tip states that you are outnumbered by your opponents).

Both can be seen to be active in the upper left corner under my active buffs/debuffs in the following screen shots.

Screen Shot from Dragonwake - 
![draao1](https://user-images.githubusercontent.com/40448982/42105930-64f3a152-7b8f-11e8-8485-9b7a00e6d857.jpg)

Screen Shot from Chaos Wastes - 
![draao2](https://user-images.githubusercontent.com/40448982/42105947-7712d380-7b8f-11e8-9cdb-cd35033454e9.jpg)

**Comment by Natherul** [comment]
not an issue, it is working as intended.

We have not been able to change tooltips yet. But this is used when too many players of a faction is in the keep. its modified by the rank of the keep and the size of attacking force. In other words its a way to prevent players from turtling in the keep all day.
