### ISSUE TITLE
Remmerbruck's Regulars Quest Broken

### ISSUE THREAD

**Issue by Bloodlet** [WarEmu/WarBugs#11968]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
The quest Remmerbruck Regulars which is a quest that sends you to scout the ships in the empire T1 RvR area is broken. I've only completed it on one character before in RoR and when I did there was a lever on the ground I had to pull to advance the quest. It seemed like with the lever disappeared around the time of the Sigmartide event. I believe back during the official game the quest would update simply by walking into the area.

Steps to reproduce the problem:
Acquire the quest, go to the red quest area and the quest will not update either from walking in the area nor from interacting with anything currently in the area.

Screenshots/Videos or archive.org evidences:
Nothing to show.

**Comment by sioding** [comment]
Fixed with patch from 06.07.2018
