### ISSUE TITLE
Chaos PQ "Suderholm" in Norsca

### ISSUE THREAD

**Issue by Whateverletmein** [WarEmu/WarBugs#11969]
Expected behavior and actual behavior:
Kindling doesn't have any "cooldown" or respawn time. Clicking on one kindling pile continuously keeps counting as burning down houses. This obviously shouldn't be the case. There's an empire bucketeer champion that spawns in the area so I suppose he was intended to put out the fires and respawn kindling, but that might be too much work so just adding a cooldown to kindling should work.

Steps to reproduce the problem:
Click on kindling several times.

Screenshots/Videos or archive.org evidences:
Can't take a video in reasonable quality with my hardware, however this issue is easy to reproduce.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/14893
