### ISSUE TITLE
Shadow Warrior can shoot 200ft in skirmish stance!!

### ISSUE THREAD

**Issue by Green-Wolf** [WarEmu/WarBugs#1196]
My skirmish abilties can go double the distance of scout ones, it started with scout ones going double, then all the scout ones stopped working and the skirmish ones go super far! Pretty urgent i think!

**Comment by Green-Wolf** [comment]
Oh im lvl 21 if that matters

**Comment by Green-Wolf** [comment]
https://www.youtube.com/watch?v=xzqAxRDib1o

**Comment by ozarmidrashim** [comment]
If you could replicate this and notify me when you have so I can come on and check a few things, I'd appreciate it.

**Comment by ozarmidrashim** [comment]
Bug in Shrapnel and Glass Arrow - they increase range by 75% instead of decreasing it by 25%.

**Comment by Green-Wolf** [comment]
I won't get a chance to log on until later tonight, did you still want me to try and replicate this or is it sorted  with what you found?

**Comment by ozarmidrashim** [comment]
Should be sorted.
