### ISSUE TITLE
Masks not available for appearance 

### ISSUE THREAD

**Issue by Rokrag** [WarEmu/WarBugs#11963]
Reminder for Torque. 
Masks from other events that went from pocket to helm do not allow for appearance change. All masks on all my alts are like this. 

![sheeeb_001](https://user-images.githubusercontent.com/39213178/42064790-b4b54eaa-7b05-11e8-96ea-19eb42f3adf8.jpg)

**Comment by Lheana** [comment]
This has been fixed.
