### ISSUE TITLE
[All the King's Men] Shard of Ruin in white bag

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#11973]
Expected behavior and actual behavior:
Chap22. Hard PQs:
- White Bags contain a box of 4 random liniments

I got a _Shard of Ruin_.

![chap_22_ruin](https://user-images.githubusercontent.com/40274248/42132339-747eacb0-7d16-11e8-9fb4-37b020c3963b.jpg)

**Comment by NorKalli** [comment]
wargrim hotfixed the issue yesterday :)
