### ISSUE TITLE
Chaos Quest "Battering the Barony" on Nordland

### ISSUE THREAD

**Issue by Whateverletmein** [WarEmu/WarBugs#11971]
Expected behavior and actual behavior:
Salzenmund handgunners aren't marked on the map if the Salzenmund Greatswords objective is complete.

Steps to reproduce the problem:
Kill 5 Salzenmund Greatswords and observe the map.

Screenshots/Videos or archive.org evidences:
https://imgur.com/a/S32VpmB

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
Fixed with patch from 06.07.2018
