### ISSUE TITLE
Chaos PQ "Salzenmund" in Nordland

### ISSUE THREAD

**Issue by Whateverletmein** [WarEmu/WarBugs#11972]
Expected behavior and actual behavior:
Player 1 (in a party with player 3) interacted with a supply chest. Player 2 (without a party if that matters) waited for the chest to respawn, clicked it and it remained interactive allowing to complete objective of 25 supply chests in seconds.

Steps to reproduce the problem:
Listed above. There might be different ways to achieve this, I have nobody to test it with, found this bug by pure coincidence.

Screenshots/Videos or archive.org evidences:
I have nobody to reproduce the bug with, the area is rather barren and nobody wanted to come check it out. You can contact me in-game to reproduce it together, name's "Dreamhaze".

**Comment by Natherul** [comment]
this should no longer be an issue, if you notice this still please comment on this report and Ill reopen
