### ISSUE TITLE
Impossible to travel on foot from Nordland to Ostland

### ISSUE THREAD

**Issue by Whateverletmein** [WarEmu/WarBugs#11970]
Expected behavior and actual behavior:
Bumping into the portal on region border produces "Region currently not available. Please try again later." message.

Steps to reproduce the problem:
Bump into region transition.

Screenshots/Videos or archive.org evidences:
https://imgur.com/a/5rkwbHh

**Comment by sioding** [comment]
I can not reproduce it. It works on live and on dev as it should. My best guess is to run back out of sight from the portal and try it again. Make sure you aren´t in fight anymore.

**Comment by Whateverletmein** [comment]
I even relogged and tried again, maybe it's not constant

**Comment by Bloodlet** [comment]
This is happening to me right now. Relogging to character select made no difference. I'll try to close the game and log in to try again.

**Comment by WAR2014** [comment]
still not work, message pop" Region currently not available. Please try again later."
