### ISSUE TITLE
Renown Trainer issue

### ISSUE THREAD

**Issue by watmotje** [WarEmu/WarBugs#11975]
Every time I buy a renown spell, it won't be added to my skill section.
Practically pay a renown point for nothing in return. 
Also, like said on other topics, the points available/spent are bugged, too.

However I did not find any topic about the spells actually not being added to the character.

**Comment by sioding** [comment]
I don´t get it at all. Which renown "spells" are we talking about?
Please add screenshots which maybe helpsto understand what you are talking about.

**Comment by gittoaster** [comment]
it's possible he has an extra point from an armor set which can only be applied to a specific mastery path skill.
