### ISSUE TITLE
Linament/Initiative&Wounds Buff

### ISSUE THREAD

**Issue by LittlefishSail** [WarEmu/WarBugs#11978]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*  I searched only for the word Linament, and found nothing, so I hope this is the first time this has been reported.

Expected behavior and actual behavior:  The linament that buffs wounds and initiative by 60 each (forgot the name since I jumped on here from in-game) does NOT actually buff wounds at all.

Steps to reproduce the problem:  No steps needed, other than to consume the linament, and watch as wounds remain unchanged.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
First of all its called liniment and you will find some issues here. But back to your report. Please add screenshots with .getstats command output before and after you used the liniment. Make sure you do not have any other buff up. Thanks for the report.
