### ISSUE TITLE
Can't obtain Chaos T4 Epic quest Annihilation

### ISSUE THREAD

**Issue by Jandeporas** [WarEmu/WarBugs#11979]
**Expected behavior and actual behavior:**
I was playing with my lvl 40 SH (Tadpoledancer) and after taking a look at the T4 rewards I've decided I wanted the reward bow from the epic T4 chaos quest. The problem comes when I approach the npc that supposedly gives the quest (Cultist Begrid), he only offered me "Rule of Three", I though it was a requisite to start the epic quest but after its completion I still can't get "Annihilation" quest.

(I checked five times to ensure I didn't have the quest in my quest log)

**Steps to reproduce the problem:**
Be a squid herder and try to start Annihilation quest

**Screenshots/Videos or archive.org evidences:**
https://i.imgur.com/DGHN0BD.jpg

**Comment by sioding** [comment]
Well - this must be something with you special squig cause i can accept the quest:
![image](https://user-images.githubusercontent.com/18517842/42177789-4f07b85a-7e2e-11e8-9195-ff89f5c61e91.png)

**Comment by nibblers** [comment]
Have very similar issue.  Cultist only shows 'Rule of Three'.
Only difference on my toon is that she had taken the quest a good year and a half back and had progressed through to the kill bw in hunting the hunters.  on returning to this toon the quest would not progress once killed said bw so had abandoned, my thinking would re-start new quest line. But now cultist dose not offer the quest.  ticketed in-game saying it is being looked into on forum.

**Comment by sioding** [comment]
Well - if you abbandond a quest in the middle of the questline you can not go back to the first NPC to accept it again. Now you have to check every Questgiver in the questline if you can accept it.

**Comment by nibblers** [comment]
TY sioding.  
Did not know about that, always thought it reset the complete quest line.  Good to know.
Yes. returned to Radult the Eldar and quest is available from that same stage.
