### ISSUE TITLE
Deadly Task Quest Broken

### ISSUE THREAD

**Issue by Bloodlet** [WarEmu/WarBugs#11989]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
The Deadly Task quest from Chaos Chapter 2 sends you to the Holmsteinn Revisited PQ area to kill 5 Nordland scouts. No scouts are present to be killed, only wolves.

Steps to reproduce the problem: Travel to the indicated quest zone and look for Nordland scouts. None are spawned in to be killed.

Screenshots/Videos or archive.org evidences:

**Comment by Lheana** [comment]
Works fine. May have been because of the PQ that bugs and does not make appear NPCs/GOs.
