### ISSUE TITLE
Onslaught for WP 4 set bonus isn't working

### ISSUE THREAD

**Issue by Korthian** [WarEmu/WarBugs#11981]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
I tried the RF regeneration but still get only 8 from Book no matter how many times i heal my group and there is no buff proc.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Screenshots with buff and .getstats output please.

**Comment by Korthian** [comment]
There in no buff of any kind so screenshot won't saw anything. And how do i get the .getstats output?

**Comment by Yalfentra** [comment]
what you play? WP or Dok (you write chalice)

**Comment by Korthian** [comment]
ohhh sorry i play both but this is happened on WP

**Comment by Yalfentra** [comment]
kk
then it dosent proc on both sides. but WP has Fury no Essence proc?:D

**Comment by Korthian** [comment]
yeap the tooltip is right for WP it has Furry proc

**Comment by sioding** [comment]
OK - let me be more specific. The 4 pc bonus is: On Heal: 10% chance to recover 45 Righteous Fury over 3 seconds. That would mean you will get a buff which adds 45 RF over 3 seconds on a 10% chance if you heal. I would like to ask you to help us by bringing in screens or a video which shows us that the proc doesn´t fire. Can you help with a video showing you heals over a minute and no proc goes off?

**Comment by Korthian** [comment]
yes i will make this video

**Comment by Korthian** [comment]
@sioding File is too big. Any idea of how can i upload it to you?

**Comment by Korthian** [comment]
and something else i have noticed. As you will se in video the 4 bonus of set sais 60 furry over 3 secs and not 45 as intented to be. Dunno if that makes any sence to you.

**Comment by sioding** [comment]
upload the file to youtibe - post a link here.
The 60 vs 45 RF problem is fixed in another report.

**Comment by Korthian** [comment]
https://www.youtube.com/watch?v=X0h--oC1qQU

here is the link. As you can see no buff from healing

**Comment by wargrimnir** [comment]
https://github.com/WarEmu/WarBugs/issues/11980
