### ISSUE TITLE
Holmstein Revisited PQ Broken

### ISSUE THREAD

**Issue by Bloodlet** [WarEmu/WarBugs#11988]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Holmsteinn Revisited.Easy Public Quest Chaos Chapter 2 | RANKS 3-4 | Basic Rewards
Stage 1 of this PQ seems to be broken as it wants you to gather supplies but there are no supplies to gather. If I recall correctly from live, there are barrels in the area that you should be able to interact with to gather supplies.

Steps to reproduce the problem:
Go to PQ area for Holmsteinn revisited and see that none of the objects are interactable.

Screenshots/Videos or archive.org evidences:

**Comment by Lheana** [comment]
![anaehll_385](https://user-images.githubusercontent.com/11537611/42314134-af129da6-8044-11e8-83d6-40cc4ddcd938.jpg)
Works fine. And what you describe seems related to #10862
