### ISSUE TITLE
Account is not active

### ISSUE THREAD

**Issue by Haojun-Phalanx** [WarEmu/WarBugs#11984]
I can't log in my main and my second account.

It says " your account is not active "
I have no problem with logging friends accounts.

**Comment by sioding** [comment]
@Hargrim already asked @wargrimnir to check your account. He will do that if he has some spare time.

**Comment by Korthian** [comment]
gogo we need leader back!!!!!!!!!!

**Comment by sioding** [comment]
And again - this is not the forum. Closed

**Comment by sioding** [comment]
Since you double post here:
https://www.returnofreckoning.com/forum/viewtopic.php?f=87&t=27240

i´ll close this one.
