### ISSUE TITLE
Oathgold Burrow - Easy PQ

### ISSUE THREAD

**Issue by Zaccar20** [WarEmu/WarBugs#11986]
Hello,
i think i found a Bug/Error.

Dwarf Ch.5  Easy PQ - Oathgold Burrow - Stage 1
The Muck Scorpion NPCs don't count as Vermin.

**Expected behavior and actual behavior:**
The Muck Scorpion NPCs don't count as Vermin.
The Muck Scorpion NPCs should count as Vermin like the Howling Bats.

![blispur_001](https://user-images.githubusercontent.com/12786673/42270491-4a4f4c2a-7f81-11e8-906e-88992ee8ff73.jpg)
![blispur_002](https://user-images.githubusercontent.com/12786673/42270500-53cc2fa2-7f81-11e8-9979-53bd0d02af3a.jpg)

**Comment by Lheana** [comment]
Any proof of it?

**Comment by Zaccar20** [comment]
I bring the fotos.
And the Howling Bats are very low populateted.

This scorpions just in the PQ area and im prety sure they count on live when i did the pq.

But i have not made a video from this PQ if you mean somethink like that ;)

**Comment by Scophis** [comment]
Only Bats count towards the progress
![PQ](https://user-images.githubusercontent.com/40274248/54308699-d6c00a00-45ce-11e9-9cba-b7d40164b529.jpg)
only Bats grant INF
![PQ2](https://user-images.githubusercontent.com/40274248/54308877-41714580-45cf-11e9-94f4-bd28c35cbaee.jpg)

**Comment by Kaelang** [comment]
"This is a fairly simple task which invloves finding 10 ore locations in the mine and killing tons and tons of bats." refers to a guide used based off of live data.

Looks to be working as intended - please move this to Suggestions & Feedback if you feel like this should change.
