### ISSUE TITLE
Shift/Right Click inoperative

### ISSUE THREAD

**Issue by REXQWONDO** [WarEmu/WarBugs#11982]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

can not add talis to equipment

Steps to reproduce the problem:
Shift/Right Click just swaps items from inventory to wearing.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
This is no reproducable - i can add talisman here. Please check your keyboard layout.
