### ISSUE TITLE
Onslaught DoK gives Fury not Essences

### ISSUE THREAD

**Issue by Yalfentra** [WarEmu/WarBugs#11980]
Onslaught 4 piecesproc doesent work for DoK

it gives you FURY! not essences. and it dosent proc (if it should)

![onslaught](https://user-images.githubusercontent.com/38870831/42173068-2b45e8d4-7e1e-11e8-882c-abf37b09f945.JPG)

**Comment by wargrimnir** [comment]
Used the wrong buff when I built these. Unfortunately that means they will be doing 45 over 3s instead of 60. Fixed in next.

**Comment by Yalfentra** [comment]
but why?:( i want 60 :D 
and what will get the wp? 45 fury too or 60

**Comment by Korthian** [comment]
to be honest i want 60 too 45 is to low :P

**Comment by Yalfentra** [comment]
i agree:P other healers get 50 ap instant?!

**Comment by sioding** [comment]
This is not the forum.

**Comment by sioding** [comment]
Fiex with patch from 06.07.2018
