### ISSUE TITLE
et Bar/Abilities Faulty on New Summon or zone change.

### ISSUE THREAD

**Issue by Bloodlet** [WarEmu/WarBugs#11987]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:  If I have a Magus pet out and decide to summon a different kind of pet without desummoning the first pet then the pet old bar should simply be replaced with one appropriate to the new pet. Instead the new pet bar is faded and the ability icons/buttons are missing except for the pet attack button. Desummoning pets and re-summoning the pet you want resolves the issue making the pet bar show at full opacity and with all ability buttons. I imagine this may be happening with Engineer turrets too but I don't currently have one to test with.

Steps to reproduce the problem: Summon a pet (pink horror) and then without desummoning the first pet, summon a new pet (blue horror) and notice how the blue horrors pet bar is faded and buttons are missing.

Screenshots/Videos or archive.org evidences:
![correct](https://user-images.githubusercontent.com/40131399/42279190-02bc7290-7f6b-11e8-8075-223f69d07f5f.jpg)
![incorrect](https://user-images.githubusercontent.com/40131399/42279195-05c94b70-7f6b-11e8-94a2-42a08f015c83.jpg)

**Comment by Natherul** [comment]
This is in fact the same issue as if you are a squig herder or white lion and change zone.

**Comment by Kaelang** [comment]
The pet bar is now fully removed when the pet despawns. Closing.
