### ISSUE TITLE
[Slayer] Reckless Gamble have backlash for each hited target

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#1199]

**Comment by magter3001** [comment]
It's suppose to give a backlash for every enemy hit. It was like that on live. Same for Choppa. So if you use an AoE, you are suppose to suffer damage for every enemy you hit as they will also take the damage from the ability. Not a bug.

**Comment by danissrv** [comment]
You are wrong.It is supposed to give a backlash on every gcd, not for every target that is hitting.
That was on live of course!

**Comment by Evildoor** [comment]
Can someone provide a screenshot or video to clarify this?

**Comment by danissrv** [comment]
![war-screenshot](https://cloud.githubusercontent.com/assets/13067648/10020550/3b917b96-614c-11e5-821d-b5f6fdf3db89.jpg)

I found a proof (Wild Swing) from old screenshots...Hope that helps.

**Comment by danissrv** [comment]
![war-screenshot2](https://cloud.githubusercontent.com/assets/13067648/10020741/38415c76-614d-11e5-817a-521bf5dc3603.jpg)

Another one with Inevitable Doom!

**Comment by Evildoor** [comment]
Nice. Also, i do believe that if it is really 1 backlash hit per ability press (not per target), then the same mechanics should be applied to other skills with "damage per attack" (Touch Of Rot, Burn Armor, Vehement Blades, etc).

**Comment by danissrv** [comment]
Unfortunately I don't have screenshots for those abilities so I'm not sure, but should be like that...

**Comment by Toldavf** [comment]
Perhaps its time to bump this up a bit with ID now available fixing it has become somewhat more important.

**Comment by ozarmidrashim** [comment]
I will be honest with you. I'm loath to fix it because I think it's bullshit that you don't get backlash from every target hit by an AoE, especially Inevitable Doom.

**Comment by Evildoor** [comment]
I see your point, and it makes sense when we talk about Reckless Gamble/Hurtin' Time (and BW similar skill, forgot the exact name). What about other similar things (Burn Armor/Vehement Blades/Touch of Rot)?
Maybe it's a bit different, but Discordant Fluctuation (#748) also comes to mind, and its usefulness is rather questionable with single proc per magical attack. And its mirror On Your Guard, which is really strong even with single tick per attack.

**Comment by Toldavf** [comment]
funnel power

It would certainly make bombers think twice if they got backlash up 9 times a tick seems a bit strong though :/

Ill leave it up to you but imo if it procs on melee it should do the same for magic.

**Comment by ozarmidrashim** [comment]
Evildoor: BA / VB / ToR activate when a melee ability is cast, not when it hits.

**Comment by ozarmidrashim** [comment]
Moved to "Intentional Changes From Live"
