### ISSUE TITLE
[Squig herder] Outta My Way!

### ISSUE THREAD

**Issue by Blubberino** [WarEmu/WarBugs#11998]
Sometimes after using it the cooldown does not show.

Currently uncertain what causes it seems to be random. I'll add more info if I have more.

Mostly happend when infight. 
uploaded a little video of it sorry for the quality.
https://imgur.com/a/f97lXif

**Comment by Torquemadra** [comment]
need more details please

**Comment by grunbag** [comment]
No details given , closing
