### ISSUE TITLE
mount art defect

### ISSUE THREAD

**Issue by prototron** [WarEmu/WarBugs#11993]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
character gets stuck only art defect while moving before mounting

Steps to reproduce the problem:
mount and move 

Screenshots/Videos or archive.org evidences:
![screens](https://user-images.githubusercontent.com/40894552/42385147-c7e7095a-80f0-11e8-8528-62d1c33f4b76.png)

**Comment by prototron** [comment]
enslaved pack mule

**Comment by sioding** [comment]
Tried to reproduce it - but i can´t. Until we are not able to reproduce something we can not fix it - sorry.
