### ISSUE TITLE
Terminate Bug again (2018 version)

### ISSUE THREAD

**Issue by Maeryk** [WarEmu/WarBugs#11995]
There was a post from 2017, and it said a fix was implemented but Terminate in PVE is still a thing as of this moment.  At about 12:00pm PST I was farming Dragonkin in CW for Tali's, when all of a sudden I was Terminated. I was trying to loot a corpse at that exact moment. Had not been rvr flagged since logging in, and was nowhere near a keep. Reikland was the zone that was under attack at the time.
The coordinates were 60.5k / 22k.
![rzarrios_000](https://user-images.githubusercontent.com/29615029/42397190-c641ada2-8119-11e8-89c3-3698717b8e7c.jpg)
![rzarrios_001](https://user-images.githubusercontent.com/29615029/42397193-c90b09fc-8119-11e8-8fec-2f5aecbc8e1c.jpg)

**Comment by gittoaster** [comment]
I also experienced this issue, this last week.

**Comment by Kaelang** [comment]
This doesn't look to be happening on the newer, more updated versions of RoR. If you are still experiencing such issues after the updates, please re-open this report. However, as this is from back in 2018 and no subsequent reports have occurred, I'm going to close this for the time being.
