### ISSUE TITLE
Empire PQ Chapter 22 Ebon Keep

### ISSUE THREAD

**Issue by XmatXergon** [WarEmu/WarBugs#11996]
Expected behavior and actual behavior:
After killing Hero in Portal Room, barrier should disappear, but it didn't.
We managed to destroy eye with AoE Abilites and im not sure if you can also damage that Eye even with Lord alive. Will test tonight.

Steps to reproduce the problem:
Coding problem ? 

Screenshots/Videos or archive.org evidences:
<a href="https://ibb.co/koLq7J"><img src="https://thumb.ibb.co/koLq7J/Xergos_022.jpg" alt="Xergos_022" border="0"></a> <a href="https://ibb.co/dagK1d"><img src="https://thumb.ibb.co/dagK1d/Xergos_024.jpg" alt="Xergos_024" border="0"></a>

**Comment by XmatXergon** [comment]
Want to confirm, you can hit Eye with AoE and destroy it w/o killing Hero in portal room.

**Comment by sioding** [comment]
No answer since 14 days - close

**Comment by XmatXergon** [comment]
Sorry but its hard to get 24 ppl together to do that PQ again atm... whenever i will know if anything changed i'll post...
