### ISSUE TITLE
[item] Some quests are not giving the item rewards you choose

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#120]
When you complete a quest and you select a reward. You don't receive the item (it vanishes).

Not all quests do this but it has been at least 2 I have found, so far.

Quests:
Wolves among sheep (Order)
Love lost (Order)

![item not received](https://cloud.githubusercontent.com/assets/7492543/2936886/f3cf937c-d878-11e3-9cb9-e9ea795a0c70.png)

![item not received2](https://cloud.githubusercontent.com/assets/7492543/2936887/fd5110f6-d878-11e3-85dd-380c2a3942ce.png)

**Comment by Evildoor** [comment]
Both quests work fine as far as i've tested.
