### ISSUE TITLE
Dwarf chapter 22 onslaught no bag for the second time for everyone in the warband

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#12004]
May be you should know it? Yesterday and 2 days ago.

**Comment by XmatXergon** [comment]
To get bag you need to kill lord in PQ area, best in middle around piles of skulls.
Best would be increase PQ Area, becouse Hut should be in PQ zone (one of heroes spawn there so why not), but atm its not.

**Comment by sioding** [comment]
all said.
