### ISSUE TITLE
PQ - Empire Ch2 - Schloss von Rubendorff stage 2 bugs

### ISSUE THREAD

**Issue by SeriousSham** [WarEmu/WarBugs#1200]
Bug 1: during the stage 2, two named mobs should spawn to guard the banners. They are Faar Skulltaker (id 3984) and Pergris Lostsight (id 3992).

Bug 2: both banners are unclickable. The cursor appears, but nothing happens when they are clicked. They are the Skulltaker Banner (id 18) and the Banner of Lostsight (id 99286).

Repro steps:
.teleport map 106 827655 913151 6000
Kill 15 Ravagers to initiate phase 2
Notice unclickable banner and absent npc
.teleport map 106 824700 917360 6290 to check the 2nd banner/mob

**Comment by Reggaewaldo** [comment]
Currently do not have the resources to fix.

Will reopen when we do.
