### ISSUE TITLE
[SquigHerder] I got lots tactic

### ISSUE THREAD

**Issue by smingleton** [WarEmu/WarBugs#12008]
pet cool down remains with I got lots tactic.

before if I had gas squig out, and pressed the keybind for gas squig, it would make the pet dissappear with no cool down. 

now it gives you a cooldown.

also tied to another bug report, because it should just start summoning a new squig when you click on the ability while the tactic is slotted.

while I got lots is slotted summon any squig, press the ability again to experience the cooldown.

![matrik_107](https://user-images.githubusercontent.com/24352165/42417561-78e0990e-8242-11e8-8a38-2ec8fb850dc2.jpg)

**Comment by Simtexx** [comment]
https://www.youtube.com/watch?v=_sMckAVxpvE

lost but not forgotten

**Comment by Kaelang** [comment]
This ability is working as intended. You can change pets without Cooldown consistantly, only if your pet dies, does a 30 second cooldown begin, which I believe is intended. Without the tactic equipped, swapping your pet triggers a 30 second cooldown. With the tactic equipped, this CD is removed.
