### ISSUE TITLE
Are these mobs behaving as intended?

### ISSUE THREAD

**Issue by Wallace34** [WarEmu/WarBugs#12009]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:Normally when you kill mobs in gunbad there is some timer before they repop. This is especially known for champion mobs in all areas of the game. Actual behavior on these 3 mobs is as follows: the 3 are tethered together so when you hit 1 of them the other 2 come. The punter i usually pulled up the hill to have a better chance at killing the 2 weaker champions. Once the punter reset i proceeded to kill the 2 other champs. Afterwards i would continue back down and kill the punter, then move on. After getting punted to the bottom X amount of times, I noticed the 2 nonpunter mobs wouldbe back. 

Steps to reproduce the problem:You can basically and easily rekill the 1st 2 mobs in the pic over and over if you wanted to, by just not killing the 3rd (and tethered) punter mob. Wallac/Stonedwally

Screenshots/Videos or archive.org evidences:

![stonedfree_001](https://user-images.githubusercontent.com/33632623/42423884-d91a0406-82c7-11e8-8fd0-789012f9fc22.jpg)

**Comment by grunbag** [comment]
I fixed them already
