### ISSUE TITLE
Mail

### ISSUE THREAD

**Issue by LeighAnneS** [WarEmu/WarBugs#12010]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
I can't send any attachments in my mail. Been like this for months. I make sure to use a subject, but still can't send the attachments. Not even $$. 

Steps to reproduce the problem:
Been like this for months now. 

Screenshots/Videos or archive.org evidences:
None.

**Comment by sioding** [comment]
The characterrname you have the problems with?

**Comment by LeighAnneS** [comment]
Azalya
Clover
Ophelia
Basically all of the toons linked to my account. But Azalya is my main that
I'm on most of the time.

Thank you for your help :)

**Comment by sioding** [comment]
Does that problem still exist?

**Comment by LeighAnneS** [comment]
No, it does not! Thank you so much for your help :) That was a quick fix!!
