### ISSUE TITLE
Squig Herder Fasta Squiggy Mount movement in Water (not demounting)

### ISSUE THREAD

**Issue by Yardape** [WarEmu/WarBugs#12012]
Expected behavior and actual behavior: Demount when ya hit water, While having Fasta Squiggy summoned.

But you stay mounted and do move alot faster than swimming, it is great to be honest haha.

Steps to reproduce the problem: Just jump in the water while on the Fasta squiggy mount 

Screenshots/Videos or archive.org evidences:
https://gyazo.com/0a1e465d2f36581f933d5f22876bcf53

**Comment by Yardape** [comment]
Also if you get out of your squig armour stance while riding the Fasta Squiggy mount, you become a goblin with really fast legs....this also doesn't demount you while in water (as you are still technically still mounted, even though you don't appear to be mounted)

**Comment by Torquemadra** [comment]
fix inc

**Comment by Natherul** [comment]
Should be fixed as of todays patch (14/07/2017)
