### ISSUE TITLE
Oil bugged @ Siege T3

### ISSUE THREAD

**Issue by nabito0991** [WarEmu/WarBugs#12018]
**Expected behavior:** To spawn at the oil location in keeps
**Actual behavior:** It spawned on the floor in front of the door wich means, melee dps could hit it and melt it in like 2 secs

**Steps to reproduce the problem:** There is not a exact way to reproduce it, i can tell it happend in Gnol Baraz **Black Fire Pass** in the past 2 sieges i've been. In the **Outer Door** to be exact

**Screenshots/Videos or archive.org evidences:** It only happend 2 times and it was rly fast so i couldn't screen it because when he dies/ gets destroyed it resets back up to where it was supose to be in the frist place.

**Comment by Natherul** [comment]
have you seen it happen anywhere else? Im trying to track down this issue but its been seemingly random so far.

**Comment by Yardape** [comment]
It happened to us t4 Chaos wastes about a week ago.....it spawned behind the outer door instead of at the top above it

**Comment by nabito0991** [comment]
Also saw it on Shadowlands, but it doesn't seem to have a certain step to reproduce it somehow it just glitches, but one think i notice is that it was always the **Dwarf Oil**

**Comment by Natherul** [comment]
I have a screenshot I got in a PM with this bug with a empire oil, so its not just the dwarf one sadly.

**Comment by nabito0991** [comment]
Saldy, after inumerous tries i've not been able to see a way to reproduce it, It's pretty random as far as i know, only thing i can add, if it does matter, is that usualy it happends when sv is lagging, so i can be some glitch from the connection clientside - serverside ? Idk, just throwing stuff out here

**Comment by Natherul** [comment]
I have not heard this issue happen again for a long time now I assume its fixed. if not comment here and Ill reopen and investigate again
