### ISSUE TITLE
Fightin at Da Mourkain Temple Rewards

### ISSUE THREAD

**Issue by vikingofmars** [WarEmu/WarBugs#12014]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: Fightin at Da Mourkain Temple Quest gives Basin Bone as a reward should be the Mourkain Medal, no?

Screenshots/Videos or archive.org evidences:
<img width="960" alt="basin bone" src="https://user-images.githubusercontent.com/37393516/42479105-5bd25528-83a5-11e8-96ae-4158316a25e1.png">

<img width="960" alt="mourkain medal" src="https://user-images.githubusercontent.com/37393516/42479180-a09ad7ac-83a5-11e8-9283-ad175251b846.png">

**Comment by Lheana** [comment]
This has been changed a while ago, so it's no longer an issue.
