### ISSUE TITLE
Road to Madness Rewards

### ISSUE THREAD

**Issue by vikingofmars** [WarEmu/WarBugs#12015]
Expected behavior and actual behavior: Road to Madness SC quest rewards a Cemetary Candle

Screenshots/Videos or archive.org evidences:
<img width="960" alt="road to madness" src="https://user-images.githubusercontent.com/37393516/42481147-e79ed56e-83ae-11e8-875e-40dbd2792af6.png">

How many tickets to i need to submit to get a manticore?

**Comment by Lheana** [comment]
I close this ticket as this reward is no longer given.
