### ISSUE TITLE
'Ead Unta

### ISSUE THREAD

**Issue by DakkaDakka223** [WarEmu/WarBugs#12013]
*Quests says take 20 Ironbreakers heads but only requires 10 killed enemies.

*Quest tracker appears on map but no such enemies are found in the area; does not say quest is pvp related.

**Comment by Lheana** [comment]
Corrected the description of the quest.
Nevertheless there is no quest marker except the one to turn in the quest when you have completed the quest.

**Comment by sioding** [comment]
fixed with patch from 19.08.2018
