### ISSUE TITLE
Blademasters in Eatine CH22 PQ

### ISSUE THREAD

**Issue by charlysixb86** [WarEmu/WarBugs#12011]
Well i have done this PQ several times now with my shaman ( Chifli ) and my squig herder ( Peckman ).
Recently ( 2-3 days ago ) discovered that Blademasters were buffed a lot doing huge damage with AoE Ether Dance. 
There're ways to deal with it but the problem comes at the stage 2 ( the one before Shinelords ) where you've 3 minutes to deal with Silentblades and the other ones. Blademasters aint needed in that stage but there're lots between the mobs wanted and doing this in 3 minutes is nearly impossible. Blademasters rekt everybody or you miss 1-2 more minutes to deal with the stage.
To Add i want to say the attempt i had were with full organized WB via Discord ( last one with Csi ).
Dont know if this is intendeed because the PQ wasnt hard once you know how to CC Shinelords away to kill Keepers in Stage 3. Asked Norkalli and he sent me here.
There's a SS of a single one hittin' me. Imagine 6 of em.
![chifli_286](https://user-images.githubusercontent.com/7903846/42450892-e55da70e-8385-11e8-9bf3-17e432595351.jpg)

**Comment by grunbag** [comment]
Fixed in next patch

**Comment by Natherul** [comment]
Should be fixed as of todays patch (14/07/2017)
