### ISSUE TITLE
Warriors of Ages Past Rewards

### ISSUE THREAD

**Issue by vikingofmars** [WarEmu/WarBugs#12017]
Expected behavior and actual behavior: The SC Quest for Highpass Cemetery gives a Dam Dime as a reward

Screenshots/Videos or archive.org evidences:
<img width="960" alt="road to madness" src="https://user-images.githubusercontent.com/37393516/42481247-5cb7c266-83af-11e8-8241-a7d2f546a43c.png">

**Comment by Lheana** [comment]
This has been changed a while ago, so it's no longer an issue.
