### ISSUE TITLE
Quest: Fightin' Infightin' (Greenskin Chapter 17)

### ISSUE THREAD

**Issue by thevanburenboys** [WarEmu/WarBugs#12021]
Quest asks you to kill Tulk and speak with Low Boss Brung. Low Boss never appears after you kill Tulk and he's not located on any of the other camps of Thunder Mountain.

![skiggok_001](https://user-images.githubusercontent.com/34468938/42521586-9f34921e-843f-11e8-8cc1-9206120af20d.jpg)

**Comment by Lheana** [comment]
#8109
Added a spawn of NPC 'Low Boss Brung' near. When it will be possible, this NPC must spawn when Tulk is killed.

**Comment by Natherul** [comment]
Should be fixed as of todays patch (14/07/2017)
