### ISSUE TITLE
No bag after chapter 22 PQ

### ISSUE THREAD

**Issue by buffotheclown** [WarEmu/WarBugs#12023]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: Win PQ, get a window to see rolls. This is the third time I have finished this PQ and have received no notice or a roll, and hence, no bag. This time I recorded it.

Steps to reproduce the problem: Just play the PQ.

Screenshots/Videos or archive.org evidences: https://youtu.be/pobDMcvV7KQ

**Comment by sioding** [comment]
No answer since 14 days. Close
