### ISSUE TITLE
Quest: Hot Stuff (Greenskin Chapter 17)

### ISSUE THREAD

**Issue by thevanburenboys** [WarEmu/WarBugs#12020]
Quest asks you do to 3 things:

- Gather 5 burning blood from the fork-tongues
- Gather 3 spit from the Veterans 
- Mix it in Sizzlum's Mug

The gathering part works fine, but there's no mug to interact anywhere. The quest marker points to cave where the fork-tongues are located but I've searched the entire cave and there's nothing to interact. I've also searched the camp and tried talking to both the quest giver and the quest ender but nothing happened. 

![skiggok_000](https://user-images.githubusercontent.com/34468938/42519775-26148d3e-843b-11e8-8e17-216dea7ab0f6.jpg)

**Comment by Natherul** [comment]
Should be fixed as of todays patch (14/07/2017)
