### ISSUE TITLE
Quest "Pile it Up!"

### ISSUE THREAD

**Issue by JackSnow008** [WarEmu/WarBugs#12022]
the quest lets us pick up the soil but it does not let us gorkify the statue (throw the mud at it)

Steps to reproduce the problem:
happens every time even if i relog or abandon and take the quest again.

------------------------------------------------------------------------------------------------------
ahhh stupid stunties gettin in me way!

**Comment by Natherul** [comment]
Should be fixed as of todays patch (14/07/2017)
