### ISSUE TITLE
My horned squig attacked me.

### ISSUE THREAD

**Issue by gomdor38** [WarEmu/WarBugs#12026]
My pet(sqiug) attacked me.

I slotted the tactic 'Ere, Squiggy.' Then I used the skill 'Outta My Way!,' my horned squig attacked me and keep hitting me. Tested in IC, pet didn't hit me. Back to RvR lake and tested again on the same condition, then pet attacked me this time again. Seems it happens only in RvR area. And this happens on agrresive or defenssive mode, won't happen when squig is on passive mode.

ID: Gomdor / squig name 'Gomblin'

Screenshots/Videos or archive.org evidences:

![gomblin_002](https://user-images.githubusercontent.com/41106728/42558008-f5c47fcc-852a-11e8-82a9-db09a62dcdf4.jpg)

**Comment by Torquemadra** [comment]
likely due to bespoke channel system which seems to proc own weapon procs on self. will be getting looked at

**Comment by Natherul** [comment]
fixed in the next patch

**Comment by Natherul** [comment]
Should be fixed as of todays patch (14/07/2017)
