### ISSUE TITLE
Friendly Mob in Greenskins Chapter 11 PQ don't like Dark elves

### ISSUE THREAD

**Issue by Yardape** [WarEmu/WarBugs#12024]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.* (I had a look couldn't find a Duplicate.....)

**Expected behavior and actual behavior:**  Well not to be attacked by the friendly mobs in the PQ,
However, randomly they attack, the pic shown is the second one attack (never screen shotted the first)
This is at the Fireforge's Camp PQ

You cant hit it back though.

**Steps to reproduce the problem:** Well I don't really know. the second time i was actually afk for about 3-4mins and when i came back it was beating on me

Screenshots/Videos or archive.org evidences:
![yardstain_001 friendly attacking me](https://user-images.githubusercontent.com/19935059/42556562-56c8c4a0-852f-11e8-95cc-d6ac6f8bbfb1.jpg)

**Comment by Lheana** [comment]
#9880
