### ISSUE TITLE
Bonus Inf in Greenskin PQs

### ISSUE THREAD

**Issue by Wyvernmoon** [WarEmu/WarBugs#12027]
I've done PQs for characters in their respective zones matching race and they get 150 inf per kill in the PQ.  I rolled a Black Orc and started doing PQs in Greenskin zone and he is only getting 100 inf per kill.  Thank you.
![150inf100](https://user-images.githubusercontent.com/41122586/42585137-d249d0c4-8502-11e8-9d4d-d742422a1c25.jpg)

**Comment by Natherul** [comment]
fixed in the next update

**Comment by Natherul** [comment]
Should be fixed as of todays patch (14/07/2017)
