### ISSUE TITLE
[AM][AB.EX] Healing value bugs

### ISSUE THREAD

**Issue by Gilandar** [WarEmu/WarBugs#12037]
1) There is an odd bug where the healing I do on others is completely insane, compared to the healing I do to myself. Green numbers in images are actual values in SC with no healing taken boosters. What's more, these aren't even critical numbers.

https://ibb.co/di4Zz8

https://ibb.co/dOMEz8

2) Single target self heals also don't seem to recieve willpower bonus from mechanic. Before this patch I healed for 800 hp with 47 heal bonus and 20% reduction to healing, now I heal for 837 even when consuming a force stack with Boon of Isha.

**Comment by Natherul** [comment]
self target heals are excluded. I forgot to add that to the notes originally.
