### ISSUE TITLE
Fields of Reikland

### ISSUE THREAD

**Issue by Zoggof** [WarEmu/WarBugs#12036]
Chaos Chapter 22 - Fields of Reikland

There is only 17 "Reikland Goods" to destroy out of the 20 you need to progress the PQ. Searched the entire PQ and there aren't any left anywhere, nor any that respawn.

![leatherman_000](https://user-images.githubusercontent.com/23256143/42724401-deb11ac0-87b4-11e8-8ffa-ba334fed90b3.jpg)

**Comment by sioding** [comment]
fixed with patch from 04.08.2018
