### ISSUE TITLE
[Squig Herder] 5th bonus in Conq set

### ISSUE THREAD

**Issue by Horusaximand** [WarEmu/WarBugs#12031]
The 5th bonus in Conq set - On Hit : 25% chance to reduce target's Initiative by 100 while increasing your Ballistic Skill by 100 for 10 seconds - does not transform Ballistic Skills into Strength while in Squig Armor. It should, otherwise, this set bonus is half useless.

**Comment by wargrimnir** [comment]
Most potions and buffs also do not translate over while in SA. Use the appropriate potions and buffs. The initiative debuff is still good though.

Not a bug.
