### ISSUE TITLE
Siege Weapons Despawning in Saph/Ave

### ISSUE THREAD

**Issue by Flavor-burst** [WarEmu/WarBugs#12032]
Ram and Canons will randomly despawn when changing zones in a 2 zone rvr lake. This isn't a particularly new issue, so I am just providing a screenshot of where it last happened:

![image](https://user-images.githubusercontent.com/39884574/42716164-351c8dba-86c8-11e8-81e3-de7cc207e2e0.png)

**Comment by Kaelang** [comment]
This doesn't seem to be happening in the latest version of RoR - please re-open if this issue persist.
