### ISSUE TITLE
Choppa Onslaught Helm Missing 1% Crit Reduction

### ISSUE THREAD

**Issue by WJamesLord** [WarEmu/WarBugs#12035]
The Onslaught helm for the Choppa only has 2% crit reduction while every other Onslaught helm with crit reduction listed on the armor spreadsheet has 3% reduction.  I also have the Zealot Onslaught helm, which correctly has 3% crit reduction.  Please correct this oversight.

Thanks much!

**Comment by NorKalli** [comment]
fixed

**Comment by sioding** [comment]
fixed with patch from 14.08.2018
