### ISSUE TITLE
Don't receive gold send by mailbox

### ISSUE THREAD

**Issue by rollinseed** [WarEmu/WarBugs#12044]
hello,
Earlier today(15/07/2018) i have send some gold (16 in total, 15 first and 1 just after) from my main character "Zygilzit" to a reroll "Bullyu". My problem is "Bullyu" don't receive those mails and so don't receive the gold.
I hope you will solve my issue.
Thanks for your time and have a nice day.
Rollinseed/Asparfel

**Comment by Natherul** [comment]
The mail is in the DB, so at worst it will be delivered on a restart. But with the new changes if someone sends you a mail while you are in loading with Bullyu it should reload your mailbox
