### ISSUE TITLE
Map quest marker disappearing

### ISSUE THREAD

**Issue by Barmatyr** [WarEmu/WarBugs#12046]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Map quest marker follow quest progression and show objectives location
Completing part of quest objectives make quest marker disappearing, Unable to have them reappearing.

Steps to reproduce the problem:

Do quest with more than one kill counter for exemple, step or objectives

Screenshots/Videos or archive.org evidences:

**Comment by Bloodlet** [comment]
I agree, this is very annoying. For example I have the quest "Greenies" which is an Empire quest in Talbecland. The quest marker only showed the part for "Boilnog's Ear" so I found and killed Boilnog and left the area not realizing there was also a "Swamptoof Greenskins" part that I wasn't aware of after I reviewed the tome of knowledge and quest log so now I have to travel back to the area. This happens on all quests with multiple components.

**Comment by Tazo83** [comment]
i agree i had a quest that says kill 8 of something and find the evidence .... i did kill the 8 require monsters and the marker on the map disappeared i and i didn't know that so i moved back to the town to claim the reward and found out that the quest still not finished yet and the marker is disappear without completing the quest

**Comment by sioding** [comment]
Sorry guys - this reports doesn´t help at all. I do understand that it´s annoying but we have to set the questmarker correct for every quest you found with "strange" questmarker behavior. So sorry but i will close this one here. report every single quest with this issue - we will handle it - cause i am the king of questmakers ;)
