### ISSUE TITLE
talbecland pq steinbruck manor 

### ISSUE THREAD

**Issue by lijebin** [WarEmu/WarBugs#12059]
Screenshots/Videos or archive.org evidences:
talabecland pq steinbruck manor don't count the kill when you kill you still get inf and exp 
still say zero

**Comment by lijebin** [comment]
![farram_000](https://user-images.githubusercontent.com/17027595/42948523-3ab5be48-8ba2-11e8-9246-30a920083ed0.jpg)

**Comment by lijebin** [comment]
![farram_001](https://user-images.githubusercontent.com/17027595/42948534-3f5a8fd2-8ba2-11e8-8706-2cb20e9e96d2.jpg)

**Comment by Natherul** [comment]
may be related to
https://github.com/WarEmu/WarBugs/issues/12051

In which case its fixed. I cannot replicate this issue as of current code, please confirm

**Comment by Lheana** [comment]
Please confirm if the issue still happen or not.

**Comment by Lheana** [comment]
Just tried the PQ, and it works fine

**Comment by Natherul** [comment]
just checked again to see and it works fine. If its still an issue please make a new report with as much information as possible. Thanks for the report
