### ISSUE TITLE
can't open backpack or abilitiesw

### ISSUE THREAD

**Issue by ariakus68** [WarEmu/WarBugs#12056]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.* 

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Natherul** [comment]
close the game and launcher and start again, there are some files that was not downloaded yet and therefor caused issues. It may take 3 or so starts before its all set
