### ISSUE TITLE
Merchant at Mobash's Place

### ISSUE THREAD

**Issue by hiddenagenda** [WarEmu/WarBugs#12055]
the merchant at greenskin chapter 9 "Mobash's Place" is selling level 11 equipment instead of the level 19 that would be normal
![illgotten_000](https://user-images.githubusercontent.com/35900446/42897489-047e5502-8a75-11e8-9383-545b4a42dd21.jpg)
![illgotten_001](https://user-images.githubusercontent.com/35900446/42897498-0a0e752e-8a75-11e8-9625-26b1b1b0caea.jpg)

**Comment by Lheana** [comment]
Nomiz was the equipment merchant of GS Chap 5 and 9; He is no longer a merchant. Thus I created two new merchants for GS Chap 5 and 9 and placed them.

**Comment by sioding** [comment]
fixed with patch from 27.07.2018
