### ISSUE TITLE
Keep Claiming

### ISSUE THREAD

**Issue by ferraz19** [WarEmu/WarBugs#12050]
I paid gold to claim a keep in avelorn today but did not get any zone bonuses or saw anywhere that i had claim of keep besides the initial message and gold transfer in chat box. It seems like it took the gold but didnt go into effect.

**Comment by sioding** [comment]
Please add screenshots for this. One with you buffs and one with the output of the command ".rvr"

**Comment by sioding** [comment]
No answer since 12 days - close
