### ISSUE TITLE
Quest 'Tapping the vein' in ch.19

### ISSUE THREAD

**Issue by Algenubi** [WarEmu/WarBugs#12054]
Quest named 'Tapping the vein' in TM dwarf chapter 19. Player needs to interact with ore shovel placed in chapter 19 itself, near forge, according to quest description. Interacting gives nothing. In addition, quest has no markers on the map, as all other quests in chapter 19.

**Comment by Lheana** [comment]
Works fine, quest marker is set and correct, and clicking on the "Ore Sample" correctly gives item of the same name that completes the quest.
![lheana_071](https://user-images.githubusercontent.com/11537611/43045251-82beead8-8db5-11e8-8125-647f713de2c5.jpg)
You are talking about other quests in Dwarf Chapter 19 that don't have quest marker set, please reverify and if there are really none, report them.

**Comment by Lheana** [comment]
Clicking on the Ore Shovel will now give item "Sack of Ore Samples". Right-click on it to complete the quest.

**Comment by sioding** [comment]
fixed with patch from 27.07.2018
