### ISSUE TITLE
T4 Epic Quest: The Ebon Flame (Mob: Keeper of the Way)

### ISSUE THREAD

**Issue by Chiladan** [WarEmu/WarBugs#12063]
Mob is standing right behind Champions and Heroes in the Hard Ch22 PQ in Eataine. Would it be possible to move him somewhere more accessible?

**Comment by Lheana** [comment]
There are 2 champions nearby him, but it is possible to taunt/aggro Keeper of the Way without beeing attacked by them. And it is possible going through water, to avoid other champions/heroes.

**Comment by sioding** [comment]
fixed with patch from 19.08.2018
