### ISSUE TITLE
RP ch. 5 reward - cane of troll slayer, can't equip weapon type

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#12068]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
This Rallymaster reward isn't equipable and seems to be wrong weapon type class.

Steps to reproduce the problem:

Empire Ch. 5 reward

Screenshots/Videos or archive.org evidences:
https://preview.ibb.co/bTGtRy/cane.jpg

**Comment by sioding** [comment]
fixed with patch from 27.07.2018
