### ISSUE TITLE
RVR T4 RAM BUGGED

### ISSUE THREAD

**Issue by nabito0991** [WarEmu/WarBugs#12061]
**Expected behavior and actual behavior:** Spot to place the Destro Ram what actually happend is that an Empire Ram was in the way an we couldn't place the Destro Ram

**Steps to reproduce the problem:** No Idea xD

**Screenshots/Videos or archive.org evidences:**

![nabbz_020](https://user-images.githubusercontent.com/20178363/43031556-d90797ca-8c9b-11e8-805c-431d0fd95e24.jpg)

**Comment by Natherul** [comment]
is this really an issue? Unless you could not kill it I dont see how this is an issue.

**Comment by nabito0991** [comment]
It only takes damage from the Oil which akward enough was also Order

**Comment by nabito0991** [comment]
we hit and hit it and it wouldn't take damage, idk why

**Comment by MaxHayman** [comment]
Anyone had this issue recently?
