### ISSUE TITLE
excessive PQ spawning in TC, possibly more

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#12069]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
I have expected at least a few PQ's now visited in Troll Country that have many many spawns.  

Steps to reproduce the problem:
Just visit some PQ like Plague Trolls, Blighted Farm, WTTC

Screenshots/Videos or archive.org evidences:

https://preview.ibb.co/g6fgDd/spawns.jpg

**Comment by Lheana** [comment]
I don't see anything abnormal in the PQ Plague Trolls. There are several spawns, yes, but not excessively.
