### ISSUE TITLE
RP core ability no icon - 'Rune Priest Badge'

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#12065]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: expected icon, it says 'no icon set'.

Steps to reproduce the problem:
ability shown in general skills "v" tab

Screenshots/Videos or archive.org evidences:
https://image.ibb.co/k1YcjJ/badge.png

**Comment by grunbag** [comment]
Fixed it but lots of mechanic skill don’t have icons
