### ISSUE TITLE
[BO] Ability "You Wot!?!!!" remove Taunt damage increase

### ISSUE THREAD

**Issue by nohh** [WarEmu/WarBugs#12062]
Taunt increase damage for 30%, "You Wot!?!!!" increase damage for 20%

Damage without Taunt and without "You Wot" - 359
Damage with Taunt - 457
Damage with "You Wot" - 418
Damage with Taunt and with "You Wot" - 418

**Comment by Torquemadra** [comment]
fixed direct on live
