### ISSUE TITLE
[DoK][Tac] Terrifying Aura wrong mechanic

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#1207]
Using detaunt makes detaunted selected target and enemies around you. Should detaunt selected target and enemies around this target.

**Comment by Tesq** [comment]
no it works correctly, dok detaun always worked this way vice versa wp de-taund worked as youd escribed here.

**Comment by Silentguard** [comment]
Yea, looks like this. Different tac tooltip. My bad.
