### ISSUE TITLE
Quest : Useles, Destruction, Talabecland 

### ISSUE THREAD

**Issue by Grunbeast** [WarEmu/WarBugs#12070]
![daclutcha_008](https://user-images.githubusercontent.com/35007878/43050516-48143154-8e0a-11e8-904f-004dd66e6dff.jpg)
![daclutcha_006](https://user-images.githubusercontent.com/35007878/43050519-4cba03e6-8e0a-11e8-9b2c-4469fa00011f.jpg)
![daclutcha_005](https://user-images.githubusercontent.com/35007878/43050520-525b3694-8e0a-11e8-9445-67e554466fc3.jpg)

In order to complete this quest you need to go inside of this tower and kill a skaven. I found no way to open doors and I could not pull rats out of the tower with my aoe skills.

**Comment by Grunbeast** [comment]
I found the way in. Could be nice to have a marker on that portal tho :)

**Comment by Lheana** [comment]
The barrier that prevents entering the tower will be removed with next patch

**Comment by sioding** [comment]
fixed with patch from 19.08.2018
