### ISSUE TITLE
[Destro][T3 Dwarf][ RvR] 1st influence reward stuck even UI displays it unlocked

### ISSUE THREAD

**Issue by zulnam** [WarEmu/WarBugs#12079]
[Destro]
STR:
1. Fight in the Badlands / Black Fire Pass rvr.
2. Reach first influence reward.
3. Go to Warcamp > Rally Master.
4. Attempt to buy first reward.

EXP: Reward should be unlocked or UI should display correct point of unlock.

ACT:
Reward still locked. Tome displays reward as unlocked

![image](https://user-images.githubusercontent.com/19802847/43194104-869950bc-8ff9-11e8-915f-14525dda9235.png)

**Comment by sioding** [comment]
Please go to the rally master in the other warcamp - we know about that problem but can not fix it atm.
