### ISSUE TITLE
Inevitable City Portal-Gate barrel-roll (21,7k/35,2K)

### ISSUE THREAD

**Issue by Carypcerath** [WarEmu/WarBugs#12072]
In the Inevitable City at Dungeon entrance (21783/35227) you open a Gate to interact with the Dungeon-Portal - in the actual state of the Game there will be no event start after this, only interaction option is the Gate that roll to the side for the Player(s). If the person does not leave the portal quickly enough, they will be caught by the gate and taken along.

**Expected behavior and actual behavior:**

After interaction and certain time the gate will close and move the people in way to the side.
But currently its will drag you with the movement of the rolling Gate and throw you over the Portal.
Let you stuck behind the room of the Portal, no interaction possibilities and without portal-scroll no go-back.

Possible are other end position for the player, like stucking between gate and portal - here you can only zoom out with the character and try to interact with the gate again to come out.

**Steps to reproduce the problem:**

1. First you open the gate and get a position between Gate and Portal. (Picture 1-2)
2. Let the Gate close itself.
3. in case of the Position (Picture 3, 5 & 7)  one of (for me) 3 possible things will happen (Picture 4, 6 & 8)

Screenshots/Videos or archive.org evidences:
1. ![image](https://user-images.githubusercontent.com/41629639/43137176-58f9c366-8f4b-11e8-9aad-196c381b6660.png) (Closed Gate)

2. ![image](https://user-images.githubusercontent.com/41629639/43137153-45e83afa-8f4b-11e8-9b45-30e2fe88c3d9.png) (Open Gate)

3. ![image](https://user-images.githubusercontent.com/41629639/43137347-eaa54a2e-8f4b-11e8-9b9a-a54c9e270bc0.png) (Position between Gate for a Barrel roll - refers to end position 1)

4. ![image](https://user-images.githubusercontent.com/41629639/43137380-0c570dce-8f4c-11e8-9d3e-d9626bcaeb58.png) (possible end position 1 - with go-back option)

5. ![image](https://user-images.githubusercontent.com/41629639/43137438-36152916-8f4c-11e8-8943-d9017d4776c1.png) ( positon between gate above scroll - refers to end position 2)

 6. ![image](https://user-images.githubusercontent.com/41629639/43137574-6211f68e-8f4c-11e8-8382-08a186dc5413.png) ( possible end position 2 - stuck between gate and portal) 

7. ![image](https://user-images.githubusercontent.com/41629639/43137664-ae21c040-8f4c-11e8-9c2c-2f62a8395220.png) ( position between gate, above scroll - refers to end position 3)

8 ![image](https://user-images.githubusercontent.com/41629639/43137709-d01f8fd8-8f4c-11e8-9f4d-4b010aaa8258.png) (possible end position 3 - throw over the portal, stuck in the room behind)

**Comment by Lheana** [comment]
Simple fix: don't do it until this dungeon is open.

**Comment by Carypcerath** [comment]
The report in the bug tracker was not meant to tell me that I should ignore this problem until a possible instance is opened.
But it was purely for information purposes. This is objectively a mistake/bug and I have reported.

When it comes to the solution, it would also be possible to simply deactivate the gate or place an item in the room to teleport the player out without a GM intervention.
