### ISSUE TITLE
Magic penetrable walls in Siege

### ISSUE THREAD

**Issue by Carypcerath** [WarEmu/WarBugs#12074]
In the conquests at the castles, one can stand on the 1st level behind the outside walls and conjure up in the room, healing effect, resurrection.

**Expected behavior and actual behavior:**

In fact, in the absence of visual contact, there should be no magic interaction with the character, such as when someone is behind a hill or behind a wall.

Anyway, this is possible at this point and is only visually perceived as a wall, even as a physical wall because you can not walk through it. However, the walls of this level, in particular of these "pillars" are penetrateble with magic.

**Steps to reproduce the problem:**

1. Go in any Castle of you´re choice, move to the first level ( the level above bottom ), with 2 People.
2. Person A stands in the middle of the room, Person B stands hidden behind the "pillar".
3. Person B cast a Spell to A. 

**Screenshots/Videos or archive.org evidences:**
1. ![image](https://user-images.githubusercontent.com/41629639/43153528-cece0496-8f71-11e8-9018-76cbc932eff7.png) (Healing in the Building)

2.
![image](https://user-images.githubusercontent.com/41629639/43153593-f68d9dc0-8f71-11e8-9a2b-db4e18c2e405.png) (more Healing)

3. ![image](https://user-images.githubusercontent.com/41629639/43160104-8965bcb0-8f84-11e8-8f77-836c908c5a0c.png) (different keep, same healing possiblity

4. ![image](https://user-images.githubusercontent.com/41629639/43160136-a2f34cd8-8f84-11e8-8b0c-3c94708248d0.png) (same keep as 3. same healing)

**Comment by sioding** [comment]
You shown that with a group releated spell. the group healing is designed to work like this. Every member in a specific range will be healed regardless of LoS. Is that what you mean?

**Comment by Carypcerath** [comment]
Also, because in that case it was the simplest spell to show that multiple health outcomes were achieved no matter where the individuals are.

But I can also execute direct heals from the position, so select a group member and directly select or revive heals.

If that goes underneath, that would of course be redundant. It made for me the impression that it is not planned.

**Comment by sioding** [comment]
Just to make it clear. You can stand on top of a keep - target a single player and using a direct heal which is not group tageted and you heal without respecting LoS?Please show this in better Screens or a video for us. thx.

**Comment by sioding** [comment]
No answer since 15 days. close
