### ISSUE TITLE
Ch 18 pq Unlikely Allies, West Praag - pq does not start when I am in the area

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#12076]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
I noticed that Unlikely Allies behavior was that the PQ seems incorrectly aligned or similar issue which results in not being able to start (?) register the PQ while anywhere in the PQ caves or entrance.
I was able to quickly start it while being in the very back of the caves, but only momentarily.

Also, I didn't get the ToK unlock for discovering the PQ.

Expected behavior was to start the PQ from the entrance of the cave and within them.

Steps to reproduce the problem:
Ch. 18 West Praag (empire)

Screenshots/Videos or archive.org evidences:
https://preview.ibb.co/hrfUoo/unlikely.png

**Comment by sioding** [comment]
This is a well known issue that we can´t fix atm. Sorry you have to wait for a server restart
