### ISSUE TITLE
[Disciple of Khaine] Chaos chapter 9, influence 3 reward: stats missing

### ISSUE THREAD

**Issue by Tyramissoux** [WarEmu/WarBugs#1208]
The Blightstone Gorget reward justhas 9 toughness on it. Nothing else. Warrior priest version of it (Wolfenburg Helm) has 24 willpower + 10 wounds.

**Comment by Reggaewaldo** [comment]
Fixed.

Source: http://war.mmodb.com/items/blightstone-gorget-96104.php

Closing.
