### ISSUE TITLE
Quest: Sorceresses

### ISSUE THREAD

**Issue by PeterOlsenInvokers** [WarEmu/WarBugs#12083]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
as a lvl 11'ish BW, I went to the BW college in Altdorf and got the quest "Sorceresses". The quest is marked as EPIC with red skulls. 
The quest sends me to Nordland, where the quest marker is right outside the pvp area and asks me to kill fifty sorceresses. However, there is no sorceresses at the marked location.

Steps to reproduce the problem:
Get quest from NPC in BW college in Altdorf, then go to nordland.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Sorceresses are enemy players fromt the other realm with the class Sorceresses ... kill them to finish the quest

**Comment by PeterOlsenInvokers** [comment]
It is NOT just enemy players.

1) I have killed enemy sorceresses both in the nordland rvr area and in scenarioes - killling them does not count towards the quest.

2) the quest area marked on the map is outside the pvp area, not inside.

3) if it was enemy sorceresses killed in pvp in nordland, it would make it impossible to finish the quest once you hit lvl 15, since at that time you'd be turned into a chicken.

Here is a screenshot of the quest area, showing it is outside the pvp area. The quest text also clearly says that you should "clear the roads".

Please reopen this ticket.

![zanzan_000](https://user-images.githubusercontent.com/1871221/43241731-2ac03a68-909d-11e8-93f8-668d27f35169.jpg)

**Comment by sioding** [comment]
my bad - read the quest wrong. reopened

**Comment by sioding** [comment]
Sorry but you have accepted a quest which should not be active. Please abondon the quest it will be deactivated with next patch.
