### ISSUE TITLE
Beastlord quest missing

### ISSUE THREAD

**Issue by Zurgoth76** [WarEmu/WarBugs#12086]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

I've done all 5 Beastlord Bosses ,and then picked the pvp killing quests, but one  disappeared from my quest log (Beastlord hunt:Which Hunters) Now i got 4/5 tokens ,and i cannot buy the Pocket :-(Please help! 
Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![beastlord quest](https://user-images.githubusercontent.com/41755390/43282287-f5bffdd4-9115-11e8-9df0-f009cfa9a918.jpg)

**Comment by NorKalli** [comment]
Do you know exactly which quest is missing?

**Comment by Zurgoth76** [comment]
Nope :-( but i've killed "20 Eng-20 Bw-20 Slayers-10 WL/10 WP"

**Comment by Zurgoth76** [comment]
![gorodan_017](https://user-images.githubusercontent.com/41755390/43671503-9942c852-979b-11e8-886a-4a94e0a5f1fe.jpg)
Was happening the same tonight with the BO i leveled to do BL again... same quest giver..  am'i so unlucky or...?

**Comment by Zurgoth76** [comment]
![zurgoth_041](https://user-images.githubusercontent.com/41755390/43681051-1f54a3e0-9849-11e8-9949-8806367982a0.jpg)
Thanks NoRKaLKiLLa!!! <3
