### ISSUE TITLE
[Chosen] Auras of the chosen block bonuses of the charactreistics of the poisons (fully)

### ISSUE THREAD

**Issue by havok01** [WarEmu/WarBugs#12081]
![default](https://user-images.githubusercontent.com/41685302/43201137-513d0a22-9020-11e8-8890-dcb4c8405c15.png)

![default](https://user-images.githubusercontent.com/41685302/43201198-75ff3ede-9020-11e8-9ef8-01714c759f74.png)

![default](https://user-images.githubusercontent.com/41685302/43201253-a033a60e-9020-11e8-83ac-32bb921cb0e2.png)

![default](https://user-images.githubusercontent.com/41685302/43201348-ea45cd3a-9020-11e8-83eb-acf1eab5feaf.png)

![default](https://user-images.githubusercontent.com/41685302/43201385-050092ea-9021-11e8-8eb2-91b38790cfba.png)

![default](https://user-images.githubusercontent.com/41685302/43201421-1bdcdd16-9021-11e8-9c6f-a2d3f22566e9.png)

![default](https://user-images.githubusercontent.com/41685302/43201655-c545d5e2-9021-11e8-89bc-6a5e4bd5fbd9.png)

![default](https://user-images.githubusercontent.com/41685302/43201742-052f3234-9022-11e8-965d-db2c53ec4481.png)

![default](https://user-images.githubusercontent.com/41685302/43202031-f2166568-9022-11e8-8aeb-ec7660954aab.png)

![default](https://user-images.githubusercontent.com/41685302/43202128-36f4ee2a-9023-11e8-9c98-da355abc26cf.png)

![default](https://user-images.githubusercontent.com/41685302/43202194-815f6904-9023-11e8-9a33-012e1fb94ff1.png)

![default](https://user-images.githubusercontent.com/41685302/43202437-31544eb0-9024-11e8-81a6-80b2d08ce49f.png)

**Comment by sioding** [comment]
We do not accept bug reports made with dummies. Sorry. - and for the next time please add .getstats output on your screen
