### ISSUE TITLE
quest - Karagaz Lost.  completes after talking to quest giver.

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#12082]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Expect that the given task should be completed before quest can be handed in for completion.
Actual behavior - accepted the quest, then spoke again to Thora Althrandotr in Badlands (dwarf).

Steps to reproduce the problem:
Talk to Thora Althrandotr in Badlands

Screenshots/Videos or archive.org evidences:

**Comment by Lheana** [comment]
Quests that require to scout an area can not be implemented yet as they are meant to work.

**Comment by Kabucoror** [comment]
fixed
