### ISSUE TITLE
[Destro][Caledor][PQ] Malyros' Rest not spawning units for Stage I

### ISSUE THREAD

**Issue by zulnam** [WarEmu/WarBugs#12080]
STR:
1. Reach Caledor.
2. Go to Malyros' Rest.

ACT:
No mobs are being spawned to complete Stage 1.

EXP: 
Squishy elves.

[Notes] It was working a few days ago. Seen similar issue with other PQs. Suggest adding command to reset PQs (for GMs) until root of problem is fixed. (ex .resetpq [unique index key])

**Comment by sioding** [comment]
We know about that problem but can not fix it atm. you have to wait for a server restart to play this PQ
