### ISSUE TITLE
30 feet range seems too short for AoE abilities

### ISSUE THREAD

**Issue by AxelF17** [WarEmu/WarBugs#12087]
The range of abilities that affect 'targets with 30 feet of you' seems too short, certainly on RP - will test on other characters too.

First off to establish a scale (I'm arbitrarily taking the target as the front of the target model and the character position from the centre of the model to allow for larger/smaller races): 
![scale](https://user-images.githubusercontent.com/39012033/43284747-b0188be4-9114-11e8-8aa5-94df5614064c.jpg)

Then Rune of Might which hits all targets within 30 feet:
![30ft no](https://user-images.githubusercontent.com/39012033/43284779-cbcf624a-9114-11e8-8d4b-186d31f1aebc.jpg)
Unsuccessful

![30ft yes](https://user-images.githubusercontent.com/39012033/43284818-e9731d3c-9114-11e8-83cc-526554e1f447.jpg)
Successful

The successful range by my very rough scale is 4 full squares plus the 0.4 gap plus a half square = 4.9 by my scale. That gives a 1 foot value of 4.9/30 = 0.163 recurring.

And Rune of Battle which also hits all enemies within 30 feet:
![30ft no2](https://user-images.githubusercontent.com/39012033/43285521-13b53b32-9117-11e8-9686-17fafd0649d3.jpg)
Unsuccessful 

![30ft yes2](https://user-images.githubusercontent.com/39012033/43285532-1d37c51c-9117-11e8-9d74-504b2a035749.jpg)
Successful

Gives the same 4.9 units = 0.163 per foot scale as RoM.

Next is Rune of Cleaving which hits targets 40 feet in front of you:
![40 ft no](https://user-images.githubusercontent.com/39012033/43284941-55e0ca5a-9115-11e8-8f16-0e2ad052f057.jpg)
Unsuccessful

![40ft yes](https://user-images.githubusercontent.com/39012033/43284948-5b0b9f82-9115-11e8-9441-d8d67c00324d.jpg)
Successful

The successful range by my scale is 8 full squares plus the 0.4 gap = 8.4 by my scale. That gives a 1 foot value of 8.4/40 = 0.21

Finally we have abilities such as Rune of Fire, Rune of Immolation, Rune of Fate which have a 100 feet range:
![100ft no](https://user-images.githubusercontent.com/39012033/43285054-bbdf3e68-9115-11e8-85a4-7d7f7cd9c152.jpg)
Unsuccessful - you can see the first three abilities on the top hotbar are red

![100ft yes](https://user-images.githubusercontent.com/39012033/43285078-cc96dc70-9115-11e8-95f5-1e4701444d5b.jpg)
Successful - the abilities are now good to go

The successful range by my scale is 19 full squares plus the 0.4 gap plus about 0.8 of a square = 20.2 by my scale. That gives a 1 foot value of 20.2/100 = 0.20

You can see from the above that abilities with a 100 feet or 40 feet range give a similar result when testing range on a taregt dummy, but abilities which affect enemies within 30 feet look to be too short. Using the values obtained from 40 feet and 100 feet abilities, the 30 feet range abilities should hit from 6 squares away (0.2 * 30), rather than the 4.9 that they currently do. That makes the current in game range of these abilities 24.5 feet. 

Caveat - the 30 feet range abilities tested so far are 360 degree abilities, while the 40 feet one is a cone and the 100 feet abilities are ST - this could be the issue rather than 30 feet v any other range. I'll test further when possible.     

*EDIT engie abilities*

Friction Burn - 'all enemies in front of you up to 40 feet away':
![40ft no2](https://user-images.githubusercontent.com/39012033/43287269-785eb22a-911c-11e8-81f2-2b4152974e58.jpg)
Unsuccessful

![40ft yes2](https://user-images.githubusercontent.com/39012033/43287274-7f3357b8-911c-11e8-8e3b-e4fde9cdccd5.jpg)
Successful (it's a delayed DoT)

It's the same 8.4 distance by my scale. That gives a 1 foot value of 8.4/40 = 0.21

Firebomb and Acid Bomb (2nd and 4th abilities on top hotbar) - 65 feet range:
![65ft no](https://user-images.githubusercontent.com/39012033/43287405-df77acdc-911c-11e8-97d1-25e07b7fb2d1.jpg)
Unsuccessful

![65ft yes](https://user-images.githubusercontent.com/39012033/43287409-e42c7e60-911c-11e8-9578-4913b7494789.jpg)
Successful

Successful range by my scale is 13 full squares plus the 0.4 gap plus about 0.2 of a square = 13.6. That gives a 1 foot value of 13.6/65 = 0.21

The we have Gun Blast (1st ability on top hotbar) - 100 feet range:
![100ft no2](https://user-images.githubusercontent.com/39012033/43287865-28d6b6b0-911e-11e8-90b1-82822071dd46.jpg)
Ability red

![100ft yes2](https://user-images.githubusercontent.com/39012033/43287872-2d4b2f50-911e-11e8-9994-b83289770cf6.jpg)
Ability white

Gives 19 full squares plus the 0.4 gap plus about 0.9 of a square = 20.3 by my scale. That gives a 1 foot value of 20.2/100 = 0.20

 Finally there's Spanner Swipe (first ability bottom hotbar) - 5 feet range:

![5ft no](https://user-images.githubusercontent.com/39012033/43288970-704a6e94-9121-11e8-8ad4-ee98f191ef26.jpg)
Unsuccessful

![5ft yes](https://user-images.githubusercontent.com/39012033/43288982-74ab2848-9121-11e8-97d3-4fed84c3afe1.jpg)
Successful

Range of 2.4 which gives a 1 foot value of 2.4/5 = 0.48 - about double that of all ranged attacks (except 30 feet attacks!). I think I remember reading that melee range (5 feet) attacks have a greater range though to allow for lag/ping/jumping - is this right?

*EDIT IB abilities*

Earthshatter 'snares all enemies within 30 feet' (doesn't cause damage as testing at 0 grudge):
![30ft no3](https://user-images.githubusercontent.com/39012033/43288749-b8607cce-9120-11e8-8b8a-3fcb4912900f.jpg)
Unsuccessful

![30ft yes3](https://user-images.githubusercontent.com/39012033/43288756-bd5cb0d0-9120-11e8-9c23-4490f3e26e94.jpg)
Successful

Gives the same 4.9 distance as the RP abilities - goving a 1 foot distance of 4.9/30 = 0.163 recurring.

Then all of the 5 feet melee abilities:
![5ft no2](https://user-images.githubusercontent.com/39012033/43289000-824d396e-9121-11e8-94eb-05183e9faddc.jpg)
Unsuccessful

![5ft yes2](https://user-images.githubusercontent.com/39012033/43289016-876ef5ea-9121-11e8-8625-0e17047073f3.jpg)
Successful

Gives the same 2.4 distance which gives a 1 foot value of 2.4/5 = 0.48

**CONCLUSION**

Using my arbitrary scale from the first picture, ranged attacks seem to have a value of 1 foot = 0.20 or 0.21 of my units. This applies to attacks with 40, 65 or 100 feet ranges.

Attacks with a 30 feet range though seem to be consistently coming up short though, with a 1 foot value of 0.163, giving these attacks an in game range of 24.5 feet rather than 30 feet.

The other exception seems to be melee or 5 feet range abilities, which have a value of 1 foot = 0.48 of my units. With a 5 feet range and a value of 1 foot - 0.2 units, melee attacks should hit from 1 unit away rather than the 2.4 units that they actually do. This gives melee attacks an in game range of 12 feet rather than 5. As mentioned though I have a nagging feeling that this melee range increase is deliberate to account for lag/ping though. 

It would seem that abilities with a 30 feet range need to have their range increased - this may be related to these attacks being 360 degree rather than cone/ST attacks, in which case these 30 feet range 360 degree abilities need a range increase.

**Comment by sioding** [comment]
Thanks for all the effort you bring in with this report. I try to find a dev looking ito it.

**Comment by Lefze** [comment]
ST range is supposed to be 10ft longer than AoE range, and as such a 5ft melee ability it almost as big as a 20ft pbaoe. However with cones you will notice this is not true as they were incorrectly patched to match the ST equivalents, adding 10ft to them. However, a lot of ranges are still incorrect, and it is beyond a players means to make a proper report on this as there is no way to test properly, these discrepancies are more in the range of 2-5ft or so.

**Comment by AxelF17** [comment]
We're not talking balancing here though, we're talking scaling/physics. If the devs decide that AoE should have a shorter range than ST (they already do - are there any ST 30 or 40 feet range abilities?) then the range of those abilities needs to be adjusted accordingly. 

If an ability says it has a range of 30 feet though and it actually has a range of just under 25 feet that's a bug. You can't have a system where 1 foot means one distance for an AoE ability, but a totally different distance for a ST ability. 

As I mentioned, melee abilities have some leeway to allow iirc for ping/latency issues, but this doesn't apply to ranged abilities - either ST or AoE.

**Comment by Lefze** [comment]
I agree, but that's the way it is. ST abilities calculate range from the players radius, which is 4.5ft, adding 4.5ft+4.5ft to the tooltip range, pretty much. AoE abilities ignore the players radius, and calculate from the center of caster to the center of the target.

Trial by pain is an ability you can use to see this going on in-game.

**Comment by sioding** [comment]
Do i really need to close this one? Guys - its the bugtracker - not a forum. Please...

**Comment by AxelF17** [comment]
@Lefze You're right - I don't have a WH to test but have a zealot and a WE, though IC doesn't have the same helpful grid:

Right of Agony - 30 feet 360 degree AoE:

![30 no](https://user-images.githubusercontent.com/39012033/43511932-a312abe4-9571-11e8-9973-2d89a8deeeb6.jpg)
Unsuccesful

![30 yes](https://user-images.githubusercontent.com/39012033/43511939-ad341216-9571-11e8-90de-b3eded3ef7eb.jpg)
Successful - 30 feet AoE distance


Ruthless Assault - 30 feet ST range (1st ability, bottom hotbar)

![ra no](https://user-images.githubusercontent.com/39012033/43511965-b88eafcc-9571-11e8-8736-e656a9092bf0.jpg)
Not in range

![ra yes](https://user-images.githubusercontent.com/39012033/43512011-dd74d7b2-9571-11e8-9810-dcb23c5651a9.jpg)
In range - 30 feet ST distance

@sioding Just trying to work out exactly what the problem is. Lefze is right, there is a discrepancy between 30 feet ST and 30 feet AoE distances, so the range of all 30 feet AoE abilities is bugged - too short. Question for the devs I guess is should the 30 feet AoE abilities have their range adjusted to be in line with all other (non melee) abilities, or should the in-game tool tips of these abilities be changed to reflect their actual range of 25 feet?

**Comment by sioding** [comment]
OK guys. Talked to Natherul about that. It will be addressed - but not right now. So a really big thank you for a good report.

**Comment by grunbag** [comment]
All Aoe radius have been checked and corrected . We measured th correct distance for next patch
