### ISSUE TITLE
[rvr] dirty trick message during keep raid

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#12093]
we stormed TM keep , i was guarding another chosen, had toughness, resists and self heal auras up, while going up to 3rd floor got "terminated" and saw this strange system message.
![attilio_051](https://user-images.githubusercontent.com/17765890/43353586-2a8213d2-923c-11e8-8e9d-e3e19acd9e13.jpg)
don't know what wrong i was doing ; could someone explain please ?

**Comment by sioding** [comment]
This is the wrong place for it sorry but this is the bugtracker. The lord is working fine - no bug atm. If you wanna discuss it please use our forums.

**Comment by zak68** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=27627&p=312468#p312468
