### ISSUE TITLE
I get constant dc (but my main char is mostly affected)

### ISSUE THREAD

**Issue by Metal96** [WarEmu/WarBugs#12090]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*
It seems i get constant dc at The Apex in IC. I get dc mostly when i am with my main character.
Expected behavior and actual behavior:
It dc after seconds/minutes
It shouldn't :D

Steps to reproduce the problem:
IC The Apex

Screenshots/Videos or archive.org evidences:

**Comment by Lheana** [comment]
Should have been fixed with Nath's update.
