### ISSUE TITLE
Witch Hunter's Incognito ability does not work properly with mobs

### ISSUE THREAD

**Issue by TimoTimeYoutube** [WarEmu/WarBugs#12096]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
One should lose the aggro as soon as one goes into the incognito.
However, if one has attacked a mob and then goes into the incognito attacks this continues.

Steps to reproduce the problem:
One should lose the aggro as soon as one goes into the incognito.

Screenshots/Videos or archive.org evidences:

![timotimetv_001](https://user-images.githubusercontent.com/27195546/43354988-d4e37e48-9254-11e8-8341-592bfcdac114.jpg)

![timotimetv_002](https://user-images.githubusercontent.com/27195546/43354990-d91987d2-9254-11e8-9919-5418735b94ce.jpg)

**Comment by sioding** [comment]
Sorry - you think that if you are in combat with a hostile NPC you can push incognito and the NPC should lose their combat mode and reset to its place?

**Comment by TimoTimeYoutube** [comment]
Hello, yes I thought so far. Or should it be like that? Then I'm sorry.

**Comment by sioding** [comment]
If you thinks so - please bring in some proof for this. A youtube link / old live patchnotes...

**Comment by sioding** [comment]
No answer since 19 days. close
