### ISSUE TITLE
The Aldorf sewer debloster bug patch note say level 19 but it is level 17

### ISSUE THREAD

**Issue by lijebin** [WarEmu/WarBugs#12091]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

debloster level 17
![winford_016](https://user-images.githubusercontent.com/17027595/43353215-1ac4006c-9265-11e8-9bfb-773531cc096a.jpg)

**Comment by Lheana** [comment]
"All players can join the dungeons of their corresponding faction at level 16 to 40, but players above level 20 will be debolstered automatically to level **### 17**."
