### ISSUE TITLE
Can't hit Mobs in sewers with melee abilities

### ISSUE THREAD

**Issue by carmine3161** [WarEmu/WarBugs#12092]
Expected behavior: able to use melee abilities on mobs.

Actual behavior: Unable to use melee abilities on mobs, auto's work and ranged attacks work. WL pet can auto but no abilities either.

Steps to reproduce the problem: Try using melee abilities on a mob in the sewers  of altdorf.

Screenshots/Videos or archive.org evidences:
![syebella_009](https://user-images.githubusercontent.com/19709971/43353452-7de1c3ea-91ee-11e8-8e11-de553db646d0.jpg)![syebella_011](https://user-images.githubusercontent.com/19709971/43353456-8f74cf80-91ee-11e8-9bfe-c5384aed8f18.jpg)

**Comment by Natherul** [comment]
There seems to be an issue if you first try and use an ability which is higher level then what you should have available. In some cases that makes it get stuck in denying all abilities until you zone

**Comment by Natherul** [comment]
There is a probable fix in the next patch/hotfix

**Comment by Natherul** [comment]
Should be fixed with hotfix as of today
