### ISSUE TITLE
"Notched Work Gloves of Fortification" reward for "Love Lost" wrong item icon

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#121]
There is an incorrect item icon for one of the rewards on the quest "Love Lost".

The item reward is some gloves but it does not display a glove icon.

![wrong item icon](https://cloud.githubusercontent.com/assets/7492543/2936894/4eacc4cc-d879-11e3-8f5e-bf21928c9e70.png)

**Comment by Reggaewaldo** [comment]
The items have been reworked since the post and now it rewards weapons. The weapons are working as intended.

Closing.
