### ISSUE TITLE
my Conqueror arms just disapeared....

### ISSUE THREAD

**Issue by erec1001** [WarEmu/WarBugs#12108]
I was farming Spirit of Eatain PQ and won gold loot bag ,,chose Ruin arms as prize then they went straight to my armor slot and my Conqueror arms just disappeared,,they are now where to be found...

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Sorry this tracker is for ingame bugs only - not for things that happens on your character. Please create a ticket or ask a GM to help you.
