### ISSUE TITLE
Search In AH shows items depending on the career of the player.

### ISSUE THREAD

**Issue by feronimus** [WarEmu/WarBugs#12109]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
If i log in with a X career character and try to search all the rare fortune items for a different career (Putting rare in the name and choosing a career like IB), it either shows my X careers only items or if i have shinies it shows nothing. While it should show me all the rare fortune items for the different career that i searched (in my example IB). Now i have seen this only with Rare Fortune set but i don't know if it is with something else also. 

Steps to reproduce the problem:

Take any X career champ, go to AH, insert into the "Item Name:"  'rare' or 'rare fortune' and into the career filter any other career that is not X. Now if you have shinies you see nothing and if you don't have it you see the rare fortune items of your X career and not the one that you filtered the results for. 

Screenshots/Videos or archive.org evidences:

**Comment by feronimus** [comment]
I dont think you really read what i wrote... Ofc you can see them. You cant filter for a different class. 

Take any X career champ, go to AH, insert into the "Item Name:" 'rare' or 'rare fortune' **and into the career filter any other career that is not X**. Now if you have shinies you see nothing and if you don't have it you see the rare fortune items of your X career and not the one that you filtered the results for.

**Comment by sioding** [comment]
You got me. Could reproduce.

**Comment by Kaelang** [comment]
This should now be fixed. Please re-open if issue persists.
