### ISSUE TITLE
Sapping Strike unusable at my level

### ISSUE THREAD

**Issue by RonRonaldJeremy** [WarEmu/WarBugs#12100]
Path of Khaine unlockable ability at rank 5; Sapping Strike is unusable at level 19
 
Its probably because game doesnt expect me to have enough points to unlock it at my level but thanks to Challenger kit which grants me one point more into path of Khaine I can.

![bazingga_003](https://user-images.githubusercontent.com/41800675/43360701-5fa8266c-92bb-11e8-99ea-4784ecc3f0d1.jpg)

**Comment by sioding** [comment]
Can ypu please show us your mastery in a screenshot?I guess you have changed an item and after that you have to skill it again.

**Comment by sioding** [comment]
I do not see any screenshots.

**Comment by RonRonaldJeremy** [comment]
I've allready leveled up i'd have to make another character and spam scenarios just to show you thing that i've described

**Comment by sioding** [comment]
ok pal - i will try to reproduce it on the dev server - if i am not able to - you´ll get a close of this report. Please add more details to the next report you create.

**Comment by sioding** [comment]
![image](https://user-images.githubusercontent.com/18517842/43365580-43915d1c-932f-11e8-87d2-6e40e1524e64.png)

**Comment by sioding** [comment]
ok confirmed

**Comment by Torquemadra** [comment]
client control issue not source code

**Comment by Kaelang** [comment]
As of 22/04/2020 this should have been fixed. Please re-open this report if you find you are still having issues.

- Edited some Level requirements on spec abilities tooltip from Ror made abilties . This caused some abilties to turn red even if they were accessible.
