### ISSUE TITLE
Siphoned Energy tactic for Chosen does not work

### ISSUE THREAD

**Issue by Dobzse** [WarEmu/WarBugs#12106]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: Equip Siphoned Energy -> disrupt any spell -> receive healing+30% run speed. In reallity you wont get neither of these bonuses.

Steps to reproduce the problem: I used Tzeentch reflection+hold the line, had close to 100% disrupt,
but received nothing at all.

**Comment by sioding** [comment]
Please add your testing screenshots with .getstats output.

**Comment by Dobzse** [comment]
not sure what has happened, but now it does seem to work.
