### ISSUE TITLE
Sacellum Dungeon: Mysterious Nurgling

### ISSUE THREAD

**Issue by Zoggof** [WarEmu/WarBugs#12103]
Mysterious Nurgling can aggro onto mobs within the dungeon and 1-2 shot them. Biggest issue with this is the Nurgling 1 shotting dungeon Heroes that you need for the quest and it robs you and your group of the kill quest credit.

EDIT: The best example of this is west wing near the two Leadbelcher Ogre heroes since the Mysterious Nurgling is quite close to the wall and can easily aggro through the wall onto them if the Ogre goes towards the steps/healers.

**Comment by NorKalli** [comment]
mob made invulnerable, non aggressive

**Comment by sioding** [comment]
fixed with patch from 04.08.2018
