### ISSUE TITLE
destro chapter 18

### ISSUE THREAD

**Issue by lijebin** [WarEmu/WarBugs#12105]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
i can easily jump into the camp and kill some npc should add some guard at bridge

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

![winford_016](https://user-images.githubusercontent.com/17027595/43382430-55475cc4-940a-11e8-8ea5-1b11936992ac.jpg)

**Comment by Lheana** [comment]
There is a ToK unlock that is meant to be obtainable for Order and Destruction in this Chapter. Need a script to make guards walk to prevent Order to camp in the chapter.
