### ISSUE TITLE
Magus Keeper Set Last Bonus - AA Haste

### ISSUE THREAD

**Issue by charlysixb86** [WarEmu/WarBugs#12107]
Expected behavior and actual behavior:

Last bonus of new Keeper Set for Magus class gives actually +25 AA Haste, i think this is not intendeed and its a bug.

Steps to reproduce the problem:

Get Keepers set off new dungeon quests.

Screenshots/Videos or archive.org evidences:

![debora_006](https://user-images.githubusercontent.com/7903846/43392561-521bc852-93f4-11e8-9910-e1656ef1007f.jpg)

**Comment by sioding** [comment]
fixed with patch from 1.12.2018
