### ISSUE TITLE
Accept scenario while at Ellyrion Keep, return to warcamp.

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#12115]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
expected - all other zones I know of with with keeps will allow you to return to the keep after a scenario unless the inner (afaik) door is up and not under siege.  
actual - i was there recently while the zones were active for RvR.  I accepted a scenario, returned and was put back to the wc.. (long way)

actual - was just at Avelorn keep which has both doors down and was able to accept a scenario and return.
played as order
please let me know if that is how it supposed to be

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Well T2 Keeps do noch have any outer doors - you are always on the inner door if you hit a T2 keep. Thats the reason why you are ported back if the active zone is in T2

**Comment by gittoaster** [comment]
It doesn't matter if it's active or not.  Other pairs are not like this, I think this is a bug/not implemented correctly.
