### ISSUE TITLE
backpack not useable

### ISSUE THREAD

**Issue by HanibalKing42** [WarEmu/WarBugs#12110]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
to show the backpack correctly...
a buggy not useable version of the backpack is displayed

Steps to reproduce the problem:
just open the backpack

Screenshots/Videos or archive.org evidences:
[Backpackreport#1.pdf](https://github.com/WarEmu/WarBugs/files/2250210/Backpackreport.1.pdf)
[Backpackreport#2.pdf](https://github.com/WarEmu/WarBugs/files/2250211/Backpackreport.2.pdf)
[Backpackreport#3.pdf](https://github.com/WarEmu/WarBugs/files/2250212/Backpackreport.3.pdf)
[Backpackreport#4.pdf](https://github.com/WarEmu/WarBugs/files/2250213/Backpackreport.4.pdf)

**Comment by sioding** [comment]
This is not serverbased. It is something on your client side. Please empty the cache forlder - make sure you use the latest launcher. And sorry - the bugtracker is the wrong place to ask for help for your special problem. Please use our game support furum.
