### ISSUE TITLE
Blackhoof doe - double spawns in TM

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#12116]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
attacked by multiples of Blackhoof doe in TM
expected - not to be doubles

Steps to reproduce the problem:
TM 50k, 10k

Screenshots/Videos or archive.org evidences:
https://ibb.co/gTHuqe

**Comment by Lheana** [comment]
I don't see any double spawn of Blackhoof Doe, there are several spawns of this NPC, but nothing abnormal.

**Comment by sioding** [comment]
No answer for 20 days - close
