### ISSUE TITLE
Ram Healed

### ISSUE THREAD

**Issue by mbanane** [WarEmu/WarBugs#12111]
Expected behavior:
- Hitting Ram a lot
- Ram get destroyed

Actual behavior:

- Hitting Ram a lot
- Ram reach 10% life
- Ram reached 20% life

- Hitting Ram a lot
- Ram reach 5% life
- Ram reached 15% life

- Hitting Ram a lot
- Ram get finally destroyed

Steps to reproduce the problem: Don't know, but i was told on /advice it was due to a shaman group heal bug.

Screenshots/Videos or archive.org evidences: No evidence, sorry. I'll try to provide.

Hope this helps.

**Comment by sioding** [comment]
fixed with patch from 04.08.2018
