### ISSUE TITLE
Engineer

### ISSUE THREAD

**Issue by pobratim** [WarEmu/WarBugs#12112]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by pobratim** [comment]
Tactic "expert skirmisher" doesnt work correct with turret planting.Ability "blunderbuss blast" can be usefull from very long distance if you targeting someone.

**Comment by sioding** [comment]
Sorry butt thats not enough informations. Please be more precise and add testing screenshots.

**Comment by sioding** [comment]
No answer sinde 15 days. close
