### ISSUE TITLE
no 2 piece bonus for Genesis set? (jewelry)

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#12113]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
description in Genesis peieces says there is a 2-piece bonus
actual - no bonus shown. 

when equipped, both pieces show as being active individually

Steps to reproduce the problem:
Equip for (RP) Genesis Remnant of the Curative, Scholar.

Screenshots/Videos or archive.org evidences:
https://ibb.co/bCiNae

**Comment by sioding** [comment]
Curative = Heal
Scholar = Damage

If you buy diferent items you won´t get the set bonus. There is a Scholar Set and a Curative Set.
