### ISSUE TITLE
WASD and arrow keys wont work

### ISSUE THREAD

**Issue by TediousPayload** [WarEmu/WarBugs#1211]
Created a sorceress and can only move by holding down both mouse buttons. WASD and arrows not working. All other keys seem to work and have keybinded the correct keys.

**Comment by Tesq** [comment]
if something like that happen close the client and re-open it; relog dont work, it's a client side problem

**Comment by TediousPayload** [comment]
Still happens and on multiple  characters

**Comment by Tesq** [comment]
mm maybe you wanna pm dana/max directly on forum so

**Comment by Evildoor** [comment]
Strange problem and i can't think of any reason or course of action for it. If this problem still persists and you are sure that your keyboard is fine, and keybinds for movement are fine, then you should create a thread here, in Technical Support:
http://www.returnofreckoning.com/forum/viewforum.php?f=4
