### ISSUE TITLE
WL Stalker tactic not giving pet toughness

### ISSUE THREAD

**Issue by carmine3161** [WarEmu/WarBugs#12114]
Expected behavior: 160 Strength and toughness you WL pet
Actual behavior: Only the 160 Strength is given

Steps to reproduce the problem: Summon your WL and then check stats with and without stalker tactic equipped 

Screenshots/Videos or archive.org evidences: GM tested it on the live server (WL owners can not .getstats their own WL pet)

**Comment by Torquemadra** [comment]
Stalker increases pet STR, speed and critical only.

**Comment by carmine3161** [comment]
Ok, my bad the .ab changelist says it gives only STR and Toughness
