### ISSUE TITLE
Renown Abilities are removed at logon

### ISSUE THREAD

**Issue by ScooterMogens** [WarEmu/WarBugs#12125]
Hi. When I buy Renown Abilities at the Renown Trainer in Altdorf it works great the first time. But after I logon again all the Renown Abilities on my char (General Abilities) are gone. At the R-Trainer it says that my points are spent but I haven't got any R-Abilities. If I respec I get all my points back and can buy it all again. But it would be better if I don't lose them all when I log on :)

![billede](https://user-images.githubusercontent.com/42101222/43680786-71c432fa-9842-11e8-9e53-5cc100a663fa.png)

**Comment by CrimsonFenris** [comment]
It's a display issue only, afaik, from first time I played RoR. You can check your stats, they are taken into account, but you have prior to respec (for free) every time you want to spend renown points.

**Comment by Kaelang** [comment]
This isn't a bug with the game itself as this issue isn't wide spread. If you're continuously having this issue, please use the forums for support.
