### ISSUE TITLE
Tactic: Close Combat

### ISSUE THREAD

**Issue by Lileldys** [WarEmu/WarBugs#12121]
Expected behavior and actual behavior:
_"Added archetype tactic "Close Combat". This tactic provides a 25% damage reduction against ranged and magical damage for 2 seconds after using a direct-damage, single-target melee ability on an enemy. This reduction will not stack with the effects of localized damage reductions, such as Detaunts or Guard."_

This is currently proccing on AoE Damage, and on the AoE DoT Ticks.

Steps to reproduce the problem:
Slot tactic, use AoE ability:
Tested:
Yer All Bleedin' Now,
Lotsa Choppin
Git to da Choppa
Wild Choppin'
Bring It On

Screenshots/Videos or archive.org evidences:
Screenshot shows I'm 1s left on the GTTC Cast, and have procced the Close Combat tactic.
![peepohappy_006](https://user-images.githubusercontent.com/13259775/43675212-4b702416-97d8-11e8-8c5c-2293e9601512.jpg)

This screenshot shows I'm out of range to use melee, and my AoE DoT is ticking and procing close combat.
![peepohappy_007](https://user-images.githubusercontent.com/13259775/43675225-7bade60e-97d8-11e8-8fa5-206df77b3ef5.jpg)

**Comment by sioding** [comment]
fixed with hotfix from 06/08/2018
