### ISSUE TITLE
Chosen Auras Group problem

### ISSUE THREAD

**Issue by Horusaximand** [WarEmu/WarBugs#12126]
While in group, 1 of 3 auras somethimes swithes off when someone leaves or joins (or maybe with another reason).

**Comment by sioding** [comment]
Never had that in my own group. The problem here is your "maybe with another reason". Please test it and cadd your result to this ticket. This "maybe" is n not precise enough. Thanks

**Comment by Iamwithstupid** [comment]
I can confirm that one of three auras can be removed suddenly (unknown reason) and unable to recast it or any other aswell, relog fixes it.

**Comment by sioding** [comment]
There is nothing that shows us how we should reproduce that problem. No new tests - no screens - no videos. Sorry guys but a dev can not fix something that comes up "somehow". Please try to test thos things you report here.
