### ISSUE TITLE
Mysterious Nurgling Sacellum Dungeons Uninteractable

### ISSUE THREAD

**Issue by Panzarpaddan** [WarEmu/WarBugs#12123]
Expected behavior and actual behavior: Earlier in the week the Myserious Nurgling could be targeted, but then he could die. Now he cant be targeted, so cant talk to him to turn in the quests.

Steps to reproduce the problem: Enter the Dungeon and try to turn in the quest.

Screenshots/Videos or archive.org evidences: https://imgur.com/a/ZGFBi2c

**Comment by NorKalli** [comment]
Invulnerable toggled off, AA speed set to 0

**Comment by sioding** [comment]
fixed with patch from 14.08.2018
