### ISSUE TITLE
Lake of the Damned - Stage 1 (Hard)

### ISSUE THREAD

**Issue by Sinrman** [WarEmu/WarBugs#12127]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.* : Checked, all Lake of the Damned issues closed.

Expected behavior: Click on each pike to save a soldier's soul up to 30 to complete.

Actual behavior: Click on a single pike 30 times and get all 30 souls without moving

Steps to reproduce the problem: Just click on a single pike during Stage 1

Screenshots/Videos or archive.org evidences:

**Comment by Arain2812** [comment]
This bug is still in the game. WE can get all 30 souls from a single pike.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/14893
