### ISSUE TITLE
Invisible permament snare [emulator]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#1212]
there is 1 snare or 1 skill that cause permanente snare from orders, (move slow an juggernaut show as a snare it's active on me).  It get show no debuff and it persist until cleared/dead, cannot found what made it; i will update if i get something.

![tesq_195](https://cloud.githubusercontent.com/assets/7527415/9567715/8cd22e7a-4f35-11e5-8b60-e285bfee8076.jpg)

**Comment by ozarmidrashim** [comment]
Is this snare 40% or 60%?

**Comment by Silentguard** [comment]
Also got 60% snare couple hours ago.

**Comment by Jaycub** [comment]
It's happened to me a few times, my hunch is its mistress of the marsh not ending. It goes away on death.

**Comment by Tyramissoux** [comment]
It happens when you enter die MoM area very shortly before it ends - within the last second. The debuff will stay until it gets despelled.

**Comment by ozarmidrashim** [comment]
Should be fixed. There is another issue causing stuck buffs but per Tyramissoux, the 0 Duration infinite MoM / Sticky Feetz can no longer happen.
