### ISSUE TITLE
Bugged Quest

### ISSUE THREAD

**Issue by AlexTheCleric** [WarEmu/WarBugs#12138]
Quest : Seeing Green 
Location: Barak Varr  10340 52400
Quest NPC: Brakka (goblin)
![warhammer_ age of reckoning version 1 4 8 copyright 2001-2012 electronic arts inc 7_8_2018 8_52_30](https://user-images.githubusercontent.com/42165408/43756856-439f5330-9a1f-11e8-9fe6-85e705610fc6.png)

The quest requires a mushroom that was supposed to be given by  the quest giver in order to finish it. You get the quest normally from the npc but no mushroom appears in your inventory so you can execute it.

check it :)

**Comment by sioding** [comment]
You don´t get the mushroom - but accept the quest - follow to the red circle and interact with the stone.
