### ISSUE TITLE
Grisly horns

### ISSUE THREAD

**Issue by Bezimeni** [WarEmu/WarBugs#12136]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*
Grisly horns
Expected behavior and actual behavior:

getting full inv of these horns when fight in empire ch 12

Steps to reproduce the problem:

tom get quest done u need 15  but when u finish quest u get unlimited more

Screenshots/Videos or archive.org evidences:

dont have

**Comment by Bezimeni** [comment]
no coment

**Comment by sioding** [comment]
Sorry this is not a bug. It´s Quest loot which you can decline. If you have auoloot on - just dont accept this grey loot.

**Comment by Bezimeni** [comment]
It si bug, indone these pq 100 times and didnt get  200 horns to destro 1 by 1 cos u cant sell it
Didnt have that quest on for horns, and still have full quest inv with horns

Poslano s mojeg iPhonea

06.08.2018., u 20:12, korisnik Sio <notifications@github.com> je napisao:
