### ISSUE TITLE
Keep getting disconnected!!

### ISSUE THREAD

**Issue by ThGingerNob** [WarEmu/WarBugs#12137]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Expecting the problem to be fixed as soon as possible.

Steps to reproduce the problem:
I keep getting disconnected either if entering Altdorf or seconds after breaching the second gate of a T4 keep. It keeps happening more and more often and its a big pain in the arse trying to connect and seeing that someone took your place in the warband. No idea if its from the maxed out settings or what, but it gets really annoying. Thanks for taking the time to read my report. P.S. Now entering a scenario will disconnect you to the character menu but with an all blue screen.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
This the wrong place for your problems. The bugtracker is only for ingame server bugs. Please follow this thread: https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=20075
