### ISSUE TITLE
Doomfist Crater Stuck Spot

### ISSUE THREAD

**Issue by buffotheclown** [WarEmu/WarBugs#12140]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: not be stuck, or be able to use the /stuck command to get out.

Steps to reproduce the problem: Not be able to be punted into this piece of terrain or allow /stuck to work here.

Screenshots/Videos or archive.org evidences:

[img]https://i.imgur.com/MI26iJz.jpg[/img]

**Comment by sioding** [comment]
Sorry but we will not change something here. The location is in the middle of the scenario - we can not set any "you can not be punted on this location". We do fix some glitched which allows ppl to get out of the area - but this is not the same here. You can use /stuck - just do it twice.

**Comment by buffotheclown** [comment]
I used /stuck, and nothing happened. /stuck was not working at all. I was stuck in that spot the entire match.
