### ISSUE TITLE
Primal Hunger is not labeled correctly

### ISSUE THREAD

**Issue by buffotheclown** [WarEmu/WarBugs#12146]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: Item description should read Wounds + Strength because that is the potion this item creates.

Steps to reproduce the problem: Item's description incorrectly reads Wounds + Initiative

Screenshots/Videos or archive.org evidences:

https://imgur.com/mfRlpKZ

**Comment by OldSerpenTxbl** [comment]
It's craftvaluetip addon issue, not the game.

**Comment by sioding** [comment]
As already said - thats an addon problem
