### ISSUE TITLE
Wasserfall Bug in Caledor

### ISSUE THREAD

**Issue by Blackplaic** [WarEmu/WarBugs#12143]
In Caledor am Wasserfall vor dem Kriegs Lager  der Ordnung muss man auf den Linken stein unter dem Wasserfall gehen und gerade aus Laufen dann Buggt man sich rein wenn man weiter gerade ausläuft dann buggt man sich denn Wasserfall wieder hoch
![langnei_000](https://user-images.githubusercontent.com/42219347/43859019-de1dd37e-9b4f-11e8-8258-34b10a574c96.jpg)
![langnei_001](https://user-images.githubusercontent.com/42219347/43859041-eabd391c-9b4f-11e8-9d76-44cfad2dedcd.jpg)
![langnei_002](https://user-images.githubusercontent.com/42219347/43859054-ee8b165e-9b4f-11e8-94e7-bcd6b0bb8621.jpg)

**Comment by sioding** [comment]
Danke - nächstes mal dann auf englisch bitte :)

**Comment by Blackplaic** [comment]
okay
