### ISSUE TITLE
Dark elf ch 20 - 2 quests bugged Distrust + The great hunt

### ISSUE THREAD

**Issue by Timmitz** [WarEmu/WarBugs#12148]
Quest Distrust: No Songblade Shadows spawn / seem not to be in game?

Quest: The great hunt: Kortul Darkspear is the questgiver and friendly. no way to kill him.

Screenshots/Videos or archive.org evidences:
![afbeelding](https://user-images.githubusercontent.com/36116924/43911406-aa5c98a8-9bff-11e8-8a4b-49232f565cbd.png)
![afbeelding](https://user-images.githubusercontent.com/36116924/43911425-b5407d48-9bff-11e8-83a4-5a55e005e275.png)
![afbeelding](https://user-images.githubusercontent.com/36116924/43911448-c631d322-9bff-11e8-9fff-133c4ae2f72d.png)

**Comment by Lheana** [comment]
Next time, one issue per report.
Distrust quest will be fixed with next patch.
The other quest can ne be fixed yet.

**Comment by sioding** [comment]
fixed with patch from 14.08.2018
