### ISSUE TITLE
Sorc: Overlord's Essence Devourer Kit

### ISSUE THREAD

**Issue by OldSerpenTxbl** [WarEmu/WarBugs#12149]
Overlord's Essence Devourer Kit tooltip states following:
2 piece bonus: On hit: 10% chance to increase all damage taken by your target  by 4% for 10 seconds.

Expected behavior:
"on hit" should proc from auto attack.
"all damage" should increase damage from procs as well.

Observed behavior:
never procs from AA
doesn't affect procs damage

**Comment by Torquemadra** [comment]
working as intended
