### ISSUE TITLE
Crashing right after rolling for loot fills bag with item

### ISSUE THREAD

**Issue by Bregual** [WarEmu/WarBugs#12152]
![image](https://user-images.githubusercontent.com/42259577/43996727-427f6ade-9d86-11e8-9c68-17a950d2b3a8.png)

**Comment by sioding** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=20075

**Comment by Bregual** [comment]
the crash itself was not the bug i was just reporting that crashing directly after a loot role duplicates the item you rolled for and fills your entire inventory with the item
