### ISSUE TITLE
38 Magus, 60% mount doesn't summon in rvr lakes

### ISSUE THREAD

**Issue by gobo-WarWizKing** [WarEmu/WarBugs#12156]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*
I have the Moonlit Blue Disk (MBD) and am level 38, rr 24. I can summon the MBD in IC or any pve zone, can even ride it into an rvr lake. Should I get dismounted, from combat, summoning daemon pet, or anything else, when I attempt to re-mount I get stuck on the summoning animation and the MBD does not summon. I can move around and summon other things, which breaks the animation freeze, and can summon my level 16 50% mount fine.
Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Hm i can not reproduce it. Please show us some screens - maybe with an error in the chat?

**Comment by gobo-WarWizKing** [comment]
![cassini_004](https://user-images.githubusercontent.com/41939212/44050691-985c2372-9eec-11e8-8636-8f34a2b67249.jpg)
![cassini_005](https://user-images.githubusercontent.com/41939212/44050696-9b432e0a-9eec-11e8-8fce-f4ea5dd429b4.jpg)

**Comment by gobo-WarWizKing** [comment]
004 is me on the 60% mount in a pve area. 005 is me in RvR lake stuck in the summoning pose.

**Comment by gobo-WarWizKing** [comment]
I can move around in that pose, and upon using any ability (including summoning the 50% mount) I revert to normal animations. I asked if any other magus had this problem in Advice channel and got no replys, so it might be a local problem. If interested I can log into the game and meet someone to show them.

**Comment by gobo-WarWizKing** [comment]
Having reached level 40 I can now summon the 60% speed MBD in RvR lakes normally. You can close this as I think it was some bug on my local part, as no other magus (level 38, 39) spoke up when I asked in Advice channels.

**Comment by Sandskid** [comment]
I have the same issue https://github.com/WarEmu/WarBugs/issues/12290
