### ISSUE TITLE
[Quest] Dark Elf Chapter 10 "What Empire wants"

### ISSUE THREAD

**Issue by Coretin** [WarEmu/WarBugs#12155]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

In the third step of the questline you have to kill 2 named. Desalion Fallingleaf and Alexis Koerting.
When you kill Desalion everything goes fine, but Alexis would never shown as completed. I've killed him several times but nothing happends.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![calaniera_003](https://user-images.githubusercontent.com/42323967/44005361-566549e6-9e72-11e8-813b-af9719ddc4ad.jpg)

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
fixed with patch from 14.08.2018
