### ISSUE TITLE
[Quest][High Elf] Ch.5 quest "Sewer Invasion" not working

### ISSUE THREAD

**Issue by TheBlueCarpetsBand** [WarEmu/WarBugs#12151]
_Expected behavior and actual behavior:_
Before Sewers in Altdorf was implemented, the City Guard NPC was available, and the quest was able to be turned in and completed, but now the NPC is missing and the quest cannot be turned in.

_Steps to reproduce the problem:_
Questgiver,"Empire Courier" offers quest in the Tier 2, Ch.5 Mathrin's Watch.
City Guard NPC to turn in quest is missing by the Sewer entrances and is also not located in the highlighted area of the map in Altdorf as well.

_Screenshots/Videos or archive.org evidences:_
![sewer invasion3](https://user-images.githubusercontent.com/38879353/43987619-e8e4c456-9d12-11e8-984d-1b9164fa3dcf.jpg)
![sewer invasion](https://user-images.githubusercontent.com/38879353/43987622-f14f0732-9d12-11e8-9e03-cf96c1b1a882.jpg)
![sewer invasion2](https://user-images.githubusercontent.com/38879353/43987621-ef2f5858-9d12-11e8-9fc0-8e123dd3ce08.jpg)
![sewer invasion4](https://user-images.githubusercontent.com/38879353/43987704-88a02796-9d14-11e8-9944-420e10ab7b91.jpg)

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
fixed with patch from 14.08.2018
