### ISSUE TITLE
Chaos Chapter 11 [Useless] quest can't find the NPC mob

### ISSUE THREAD

**Issue by WAR2014** [WarEmu/WarBugs#12158]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Tring to finsih this quest [Useless] at chapter 11 Horned Tower outside of Destro Warcamp. As like the quest descripted, I need to kill a Verminkin and take his tail. Quest requirements is Verminkin Clanrat Tail x 1. Searching around the tower no such as name of NPC. The tower was blocked.

Steps to reproduce the problem:
Only 1 step at the moment.

Screenshots/Videos or archive.org evidences:

![default](https://user-images.githubusercontent.com/17757461/44027528-2b34a80c-9f3a-11e8-8ee2-6b7cbafeb0a9.PNG)

**Comment by WAR2014** [comment]
I found the NPC, he was inside the tower, I can't get inside the tower, he can't come out. 
![default](https://user-images.githubusercontent.com/17757461/44027850-4e494748-9f3b-11e8-82ea-4397634f74d9.png)

**Comment by sioding** [comment]
Looks like a barrirer in a public quest - maybe you should bring it into the next stage - should i really check that to prove my guess?

**Comment by Lheana** [comment]
Use the portal at 26k 19.5k.

**Comment by WAR2014** [comment]
Nice, it's worked. Thanks a lot. Case closed!

**Comment by WAR2014** [comment]
Eh, how can I get out of the tower?

**Comment by Lheana** [comment]
There is a portal at the top of the tower.

**Comment by WAR2014** [comment]
The portal I went through that map wasn't release. And it killed me every
minute then revive at same spot.

Lheana <notifications@github.com> 於 2018年8月15日 週三 20:12 寫道：

**Comment by WAR2014** [comment]
The quest is finished. I used bind of book transfered out. Friend of mine
said it's a small tiny keys on wall or floor that can used to open the
door. But I think that was before you setups the barrier before. Never mind
then. And thanks a lot.

Lheana <notifications@github.com> 於 2018年8月15日 週三 23:21 寫道：
