### ISSUE TITLE
[Quest] Dark Elf Chapter 10 "Defender's defeat"

### ISSUE THREAD

**Issue by Coretin** [WarEmu/WarBugs#12157]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
At the point of the questline you had to kill 2 Avalon Blademasters 2 Avalon Longbowman and 2 Avalon Shieldbreakers to complete the task. But there are no Shieldbreakers in this area and neither
somewhere around. 
So it's impossible to complete the quest.

Steps to reproduce the problem:
i think 4 steps so far... but not sure

Screenshots/Videos or archive.org evidences:

![calaniera_004 shield](https://user-images.githubusercontent.com/42323967/44025701-1ae8546a-9ef1-11e8-9034-84ef5f6a1c29.jpg)

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
fixed with patch from 14.08.2018
