### ISSUE TITLE
items & ability info not showing.

### ISSUE THREAD

**Issue by J4M3SR** [WarEmu/WarBugs#12154]
When I pick up an item, or hover over any ability or item with my mouse there is no description of anything. I have to link everything in order to see what it does or is for.

**Comment by sioding** [comment]
Sounds like an addon problem. Please turn off every addon and try it again.
Also show us some screens please.

**Comment by J4M3SR** [comment]
![aagust_001](https://user-images.githubusercontent.com/42319977/44005896-e4f6268c-9e48-11e8-92c5-021012d147e4.jpg)
![aagust_000](https://user-images.githubusercontent.com/42319977/44005899-e90dedfe-9e48-11e8-8cf3-d6dd7bcb3fa9.jpg)

**Comment by J4M3SR** [comment]
in the you picture its a little clearer, you can see that i had my mouse over the gloves currently equipped, its not showing anything. If i were to link them into the chat though i can see the stats then only

**Comment by J4M3SR** [comment]
top picture**

**Comment by Jhoel01** [comment]
I have the same bug.

**Comment by wargrimnir** [comment]
Russian specific?

**Comment by Jhoel01** [comment]
I installed it in Spanish, right now im re installing in english. Will update this in a bit.

**Comment by sioding** [comment]
Thanks for the info. I will close thise here since we recommend to use the latest client via download or torrent.
