### ISSUE TITLE
Cleansing Power tactic

### ISSUE THREAD

**Issue by Sinrman** [WarEmu/WarBugs#12153]
With the cleansing power tactic slotted you cannot cleanse anyone not in your party. I tried running solo with this tactic and you are unable to cleanse any hex or curse on someone other than you. In a warband you cannot cleanse anyone outside of your group even when targeting them specifically. 

Expected behavior and actual behavior:
-These are patch notes form from Nov 29, 2015
The group cleansing tactic Cleansing Power will no longer cause the cleanse to be untargeted, and it will cleanse either your groupmates or yourself, but not both.

-I get it but, Is it intended to not allow you to cleanse anyone outside your group ever, even when you target them specifically?

Steps to reproduce the problem: Slot it and go to Keep Lord fight and try to cleanse someone not in your part. Go solo with it slotted and you will not be able to cleanse the Keep Lord's hex off of anyone.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
You describe the ability as it is listed inside our wiki:
"Cleansing Power will cause you to cleanse either yourself or your groupmates, instead of your entire group".
If you wanna change something on it - please create a proposal in our forum.
Close cause no bug.
