### ISSUE TITLE
Mastery Abilities reset

### ISSUE THREAD

**Issue by Raegor** [WarEmu/WarBugs#12150]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Class: chosen
When i change my armor the mastery ability "Rending Blade" always gets reseted. Its not equiped anymore and i have to go to the career builder and spent the mastery point again.

All auras get deactivated when i change my armor, too.

First time occured at 10.08.2018

Steps to reproduce the problem:
Change armor for example: boots, belts, etc
changing my weapon did not trigger the bug

Screenshots/Videos or archive.org evidences:
![raegor_054](https://user-images.githubusercontent.com/42284326/43985127-4d33944a-9d05-11e8-9e16-c8d7a390fbf7.jpg)
![raegor_055](https://user-images.githubusercontent.com/42284326/43985128-4d52515a-9d05-11e8-83cf-6a88578170dc.jpg)

**Comment by sioding** [comment]
This is working as intended. Sorry - no bug.
