### ISSUE TITLE
keep lord morning 16/08

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#12169]
there seems to be an issue with keep lord going down way too fast happened in tm and BC , my wb wiped and we didnt even make in time get back to keep that order had killed it alredy (and we had aao) and they where not holding any flag.

happened around 12 am in tm

**Comment by sioding** [comment]
Hey Tesq - sorry but "it seems to be" reports doesn´t help at all. No screens with ".rvr" output attached or a screen with BO status or something else. It´s just a report where you talking about: It feels something is wrong. I am happy that ppl telling that - but how should we be able to replicate it. Next time - please add some screens. Sorry - but i will close this one.
