### ISSUE TITLE
Indigestion missing in mastery tree of bouncin

### ISSUE THREAD

**Issue by Timmitz** [WarEmu/WarBugs#12163]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Ability is missing from the tree.
![eadcheeze_028](https://user-images.githubusercontent.com/36116924/44099092-219e312a-9fe2-11e8-989d-48f4cbb24f76.jpg)

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
fixed with hotfix
