### ISSUE TITLE
Career path bonus set not working on DoK mercenary set since new patch.

### ISSUE THREAD

**Issue by Kaarna02** [WarEmu/WarBugs#12167]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: Before patch, my lacerate produced a 111 toughness debuff, now when i check it in my shortcuts or even on a mob it's shows now a 108 toughness debuff. I tried respecialize and taking out and putting back my set, but the bonus set still seems missing.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
No answer for 13 days. close
