### ISSUE TITLE
A lots of client "shutdown" after the server restart

### ISSUE THREAD

**Issue by notre4ror** [WarEmu/WarBugs#12160]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Expected to remain on the server for more than 20 minutes...
Actually i get random client shutdowns, no error msg.
7 times the client has closed for now.
Two of them the client shutdown inmediatly after the char was ready to play, and the others between 5 and 20 minutes (random)
Steps to reproduce the problem:
Just login.
I tried 3 different toons with the same result.
Two days ago happened but with random "kicks" from the server (not shutdowns like today) on one char, then i just logout and login with another toon and had no more issues (later i back to the first char and play good), but today has happened with 3 chars since the restart.

Screenshots/Videos or archive.org evidences:
The client shutdown, so there is no screenshot.

**Comment by sioding** [comment]
Sorry you are wrong here. This bugtracker is not for client issues. Please use our technical support forum.

**Comment by notre4ror** [comment]
Sorry, but is NOT a client issue and it's a server bug.
A lot of people have the same problem today, after the restart, so isn't a client issue.
