### ISSUE TITLE
Cost for Respecialization at trainers swapped.

### ISSUE THREAD

**Issue by edavoc** [WarEmu/WarBugs#12172]
Today at 2:46pm est. I noticed that the gold cost at the mastery trainer altdorf temple was free. I then went to respec my renown at the other trainer and it now costs 5.47g roughly what reseting mastery would cost. 
I think the costs were somehow swapped in the last update, since renown used to be free and mastery used to cost gold.

**Comment by sioding** [comment]
No - working as intended.
