### ISSUE TITLE
Quest: Striking Saphery in Avelorn can't be completed

### ISSUE THREAD

**Issue by ibaun** [WarEmu/WarBugs#12173]
Expected behavior and actual behavior: Quest calls for the use of 6 Reaper Bolt throwers in South-West of Avelorn.

Steps to reproduce the problem: Pick up the quest from Devak Bloodbane at the Jade Coast DE Ch.12 camp. Go to the marked location at south-west of Avelorn. There's only 3 Reaper Bolt throwers available at that location. Can only use them once to update the quest, so that leaves 3/6 you can't finish. Each second or more use of a thrower returns the message "Already spoken with"

**Comment by ibaun** [comment]
After logout/login, it can be completed by using the same 3 reaper bolt throwers. So can be completed, just not in the right way.

**Comment by Lheana** [comment]
Reduced to 3 until we can make this quest work as it is meant to.

**Comment by sioding** [comment]
Fixed with patch from 25.05.2018
