### ISSUE TITLE
Stonetroll Crossing scenario flag drop off bugged

### ISSUE THREAD

**Issue by zabis** [WarEmu/WarBugs#12176]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Expected behavior: being able to drop off the flag
Actual behavior: was not letting my team drop off the flag

**Comment by sioding** [comment]
Any error Messages? Was the other flag captured? Any screenshots? Sorry but this report doesn´t help to replicate it.

**Comment by sioding** [comment]
No answer since 15 days. Close
