### ISSUE TITLE
[Shaman] Don' Feel Nuthin

### ISSUE THREAD

**Issue by andytomlins** [WarEmu/WarBugs#12174]
Expected behavior and actual behavior:
AP cost should be reduced by Gorks (dps) stacks.
Currently its reduced by Morks (healing) stacks.

Steps to reproduce the problem:
Cast healing spells for mechanic stacks.

**Comment by sioding** [comment]
Testing screenshots/video?

**Comment by sioding** [comment]
No answer since 15 days. Close
