### ISSUE TITLE
[Quest] Scroll of the Inevitable City

### ISSUE THREAD

**Issue by Jankristian** [WarEmu/WarBugs#12170]
Hi
I get the quest **"As Lord Tchar'zanek Demands"** from the NPC **Arnorr Seven-Struck** in Talabecland Chaos Warcamp.
I have completed this 1st step (kills + empire courrier) with the NPC.
**The issue is** : the NPC doesn't give me the 2nd step "**Raise the Chaos Banner for Glory**".
(thus clicking to the Chaos Banner near Feiten does nothing).

Character : Ulkryg, Marauder

**Comment by sioding** [comment]
Seems like you had that quest accepted before it was disabled. The complete questline is not available anymore.
