### ISSUE TITLE
Salzenmund PQ Stage 2

### ISSUE THREAD

**Issue by Borozo** [WarEmu/WarBugs#12178]
During the second Stage of the Salzenmund PQ, where you have to kill 2 NPCs, there is a good Chance that one of the NPCs (the Captain) gets attacked by a chaos NPC when pulled. If the chaos NPCs takes the last blow and kills the Captain it won't count towards the PQ objective. The NPC doesn't spwan again, you'll have to wait until the timer runs out and the PQ restarts from the beginning.

Maybe it is a feature, but I think it is a bug… :)

**Comment by Lheana** [comment]
Champions are now neutral, they should no longer be attacked by other NPCs

**Comment by sioding** [comment]
fixed with patch from 19.08.2018
