### ISSUE TITLE
Squig Leap up on walls

### ISSUE THREAD

**Issue by Mcgotrek** [WarEmu/WarBugs#12179]
18/8. 8
![ebesneeza_003](https://user-images.githubusercontent.com/19507230/44302050-30ef3a00-a322-11e8-95d4-cae2bd2c52de.jpg)
 CET.
I was on my squig herder in Thunder Mountain when we got to the inner keep.
I went to the balcony watching for Order jumping walls when I saw a shadow warrior standing on the edge on the top floor.
I tried using squig leap and to my surprise I actually jumped him. That made it possible for me to use Indigestion and Kaboom on their entire backline before using Sticky Squigz back down.
I contacted StormX2 right away. I've added a screenshot with the location from where I could use Squig Leap

**Comment by Kaelang** [comment]
Tested making this jump and it's no longer doable on current versions of RoR. Please re-open if you can replicate.
