### ISSUE TITLE
[Epic Quest] A Lord's Game : Quest mobs only spawn in Hard PQ Step 2

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#12180]
In one of the last steps of this quest you have to kill Ellyrian Archer and Ellyrian Commander in the area of the Hard PQ Tor Elyr.
The Archers a avaible in the first step, to get to the Commanders you have to push the PQ to the next step.

I'm not sure, but if I remember correctly it was stated some time ago, that no PQ needs to be pushed to higher steps to complete the Epic Quests.

**Comment by sioding** [comment]
That was meant for T4 Epi quests to make sure you do not have to walk into a chapter 22 hard PQ - but i will ask  the DB lead..

**Comment by Timmitz** [comment]
the commanders were always in stage 2, also in live. I always just use a lvl 40 to wipe stage 1 after killing the 8 archers to avoid all that exp.

**Comment by Lheana** [comment]
I have reworked on my own all PQs including this one months ago, which explains why before the NPCs were there all the time, and no longer now.
Thanks for the info Timmitz. I have to take a look at the epic quests of this tier to take a decision.

**Comment by sioding** [comment]
fixed with patch from 23.02.2019
