### ISSUE TITLE
[Shadow Warrior] Rare Fortune 4th bonus piece - Surging.

### ISSUE THREAD

**Issue by XmatXergon** [WarEmu/WarBugs#12185]
Expected behavior and actual behavior:
4th piece bonus doesn't proc.
Surging - On Hit: 10% chance to deal 122 damage to an additional target within 30 feet of the first.

Tested about 10 minutes on Target Dummies in Altdorf and on mobs in TC, no single proc.

Steps to reproduce the problem:
Gear up 4 pieces of Rare Fortune and attack Target Dummies / Group of mobs.

Screenshots/Videos or archive.org evidences:
I didn't record but i can provide if needed.

**Comment by XmatXergon** [comment]
Any news, any progress ?

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 03.08.2019
