### ISSUE TITLE
Banish Darkness tactic not linked to repel darkness

### ISSUE THREAD

**Issue by Asho80** [WarEmu/WarBugs#12183]
Status message in chat while using the kick with slotted Banish dartkness (KotBS):
8047 banish darkness modifier effect not found
 kick and cooldown act as tactic is not slotted.

**Comment by Kaelang** [comment]
Unable to replicate on newer versions of RoR - seems as if it's now been fixed since this report was placed. Please re-open if you are able to replicate this issue.
