### ISSUE TITLE
Quest Stalker of the Void can't be completed

### ISSUE THREAD

**Issue by ibaun** [WarEmu/WarBugs#12182]
Expected behavior and actual behavior: Quest specifies to go to South East and investigate a Dark Elf Corpse. Found a corpse named 'Windscarred Corpse' at the statue south east of Saruthil's Wake. Corpse can't be interacted with.

Expected: right click corpse and get quest advance

**Comment by Lheana** [comment]
Thanks for report.
Clicking on the Windscarred Corpse will now complete the quest. I also corrected the quest marker.

**Comment by sioding** [comment]
Fixed with patch from 25.05.2018
