### ISSUE TITLE
Festering Arrow/Fell the Weak combo

### ISSUE THREAD

**Issue by TanithScout** [WarEmu/WarBugs#12181]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Both should hit, using FTW immediately after FA doesn't hit. Nothing in combat log or UI

Steps to reproduce the problem:
Every time I use FTW after FA

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
even if nothing can be seen in the combat log - can please add a screenshot with one of your tests?

**Comment by XmatXergon** [comment]
hmm, actually tested it just now on Target Dummies, most of time it did work, but couple times (few) FTW went on CD but no DMG registered.
![xergos_031](https://user-images.githubusercontent.com/37849311/44321901-ea492f00-a44a-11e8-9e9d-64d999f2f1a3.jpg)

**Comment by grunbag** [comment]
it seems already fixed i spammed both for several minutes
