### ISSUE TITLE
Cannot redeem RVR INF rewards 

### ISSUE THREAD

**Issue by defleshed2** [WarEmu/WarBugs#12199]
So it seems like there is an issue as my character and items were wiped yet when I get INF for RVR I cannot redeem any rewards... I cannot get any of the rewards that I got INF from.

Expected behavior and actual behavior:
Allow the user to redeem the rewards when a certain INF is reached in RVR

Steps to reproduce the problem:
1. get enough INF to get a reward
2. cannot redeem reward

Screenshots/Videos or archive.org evidences:
![broken rvr](https://user-images.githubusercontent.com/15912090/44498874-3f559280-a64f-11e8-8eb0-f4c6bd309261.png)

you can check my account I do not have those items but completed the RVR yet cannot get the rewards...

**Comment by sioding** [comment]
There is another warcam - please go to the rally master over there. yes - we know that problem but we have no fix for it atm.
