### ISSUE TITLE
[WH] Burn Armor procs every time the target is blocking an attack using the skill "Cant hit me" from BO for example

### ISSUE THREAD

**Issue by Jakkaru** [WarEmu/WarBugs#12195]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Burn Armor said "causing them to take XXX dmg everytime they use a melee attack". Ich would expect that the Burn Armor proccs on every attack.
But it proccs every time a BO using "Cant hit me" on the reflec dmg proc i think

Steps to reproduce the problem:
Puting burn armor on a tank target using his block and reflec skill

Screenshots/Videos or archive.org evidences:
![burn armor](https://user-images.githubusercontent.com/42607283/44535861-623d8080-a6fb-11e8-8314-8bd2e18f5ae8.PNG)

**Comment by grunbag** [comment]
Fixed already
