### ISSUE TITLE
[Bright Wizard] Funnel Power Respec

### ISSUE THREAD

**Issue by andytomlins** [WarEmu/WarBugs#12196]
Expected behavior and actual behavior:
Turning on Funnel Power and then respecing without it still keeps the buff.

Steps to reproduce the problem:
Turn it on then respec.

Screenshots/Videos or archive.org evidences:
![heligbrand_002](https://user-images.githubusercontent.com/6351625/44462679-4eb3ec00-a60d-11e8-9d66-b5fdb2d5b2f5.jpg)

**Comment by sioding** [comment]
did it stay after respec and zone to another region?

**Comment by Torquemadra** [comment]
#12188
