### ISSUE TITLE
Marauder : Some Wrong Tooltip

### ISSUE THREAD

**Issue by adells** [WarEmu/WarBugs#12194]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

The tooltip are still the old one for some marauder Skill and tactic : 

Draining swipe : cooldown is now 10 s instead of 20 , and duration of the debuff is now 5 s instead of 10

Thunderous blow : Cooldown is now 10s instead of 5

Hulking brute : miss the initiative part in addition of the toughness (give 160 toughness and 160 initiative , at the moment only the toughness part is mentionned)

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Fixed with patch from 25.05.2018
