### ISSUE TITLE
Squig Herder small issue

### ISSUE THREAD

**Issue by Demoriel** [WarEmu/WarBugs#12197]
Killing own Squig (to get a new one) Puts you in combat.
Also when you get out of Squig Armor - the Animation is a flurry of barbed wire now (Like an Engie snare)
Expected behavior and actual behavior: You should not be in combat for killing own squig, and animation should be different for Squig Armor (not the Engie Barbed wire)

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Any poof from live that you wasn´t in combat for killing your own squig?

**Comment by Demoriel** [comment]
Prior to just last week or so, Killing your own Squig (to summon a new one) didn't grey out your tactic bar/put you in combat. Proof, not sure a screen shot would prove anything sorry, and i don't have video capture capability sorry.

**Comment by sioding** [comment]
Ah ok - so nothing from AoR - it just changed with the patch.

**Comment by grunbag** [comment]
Fixed already
