### ISSUE TITLE
(Loot) Not receiving bags again

### ISSUE THREAD

**Issue by Fractus1484** [WarEmu/WarBugs#12193]
Hi, 
I know this was fixed a while ago but seems to be re-appearing and got a screenshot this time, winning zone lock bags, but not got them in the mail.  Checked after client re-start, logged different characters and left it a day.  Mail is working as normal to send items between characters.

Screenshot below:

![talitus_254](https://user-images.githubusercontent.com/26185873/44447493-45605a80-a5e0-11e8-886e-98e4df6781a0.jpg)

**Comment by sioding** [comment]
When do you think was it fixed? I can´t find the patchnote for this. Please wait for a server restart and give us a sign if the bag was delivered or not.

**Comment by Fractus1484** [comment]
Thanks and here - https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=25176&hilit=server+patch+notes+loot+bags

I received the bag today, 2 days after event, odd one, i was half expecting to see it after server restart.

Thanks again

**Comment by sioding** [comment]
The only mail i can see in your patchnotes is this:
*Mail with bags will now contain time and name of PQ / RvR zone it was generated for

**Comment by sioding** [comment]
No answer for 16 days. Close
