### ISSUE TITLE
[BO] Tooltip on WAAAAAAAGH! shows wrong resi-debuff

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#12191]
Expected behavior and actual behavior:

WAAAAAAAGH! debuffs Corporal Resistance, as the change to Elemental had been reverted. The skill-discription and debuff-tooltip still show an elemental-debuff.
(Tested the debuff and it indeed debuffs corporal, as WAAAAAAAGH's corporal-dmg output increases.)  

Steps to reproduce the problem:

Debuff target with skill and check tooltip. 

![waaaaaaagh](https://user-images.githubusercontent.com/40274248/44426301-8fb8eb80-a58e-11e8-850c-1c92e4256db8.jpg)

**Comment by sioding** [comment]
Fixed with patch from 25.05.2018
