### ISSUE TITLE
Issue with Ebon Flame Epic T4 Quest after Aug 19 patch

### ISSUE THREAD

**Issue by Hiftem** [WarEmu/WarBugs#12190]
My wife and I were working on the step in the Ebon Flame epic quest where you click on the orb to reach Flameshrine to kill the Champion Riannmar Jadehart.  We killed the Keeper, clicked on the orb, and were transported to a ledge on the tower.  There is a second orb there, and when you click on it it takes you inside the tower (assume the Flameshrine), but are immediately attacked by one of the 2 Heroes in the tower.  This seems odd since no other T4 Epic makes you kill a Hero, also, it creates a situation where you are killed in a matter of seconds, even with a Choppa and DoK.

Appreciate the help with the quest so we can finish.
Thanks!

**Comment by sioding** [comment]
Fixed with patch from 25.05.2018
