### ISSUE TITLE
Cultivating

### ISSUE THREAD

**Issue by naxzor** [WarEmu/WarBugs#12204]
after the update today it is not posibble to make plants back into seeds from cultivating in advice they are saying its a general issue after patch. there is no text saying ctrl rightclick to convert item anymore. and there is nothing in the update text saying it is a change following the patch.

**Comment by rhizo** [comment]
Yes Control right click is not harvesting seeds from plants cultivated.

**Comment by MaxHayman** [comment]
Hi @rhizo can you give me the name of the seed you were using.

**Comment by naxzor** [comment]
![hammermanden_002](https://user-images.githubusercontent.com/42573183/44627611-23910b80-a931-11e8-9011-6333bf9023e6.jpg)
![hammermanden_000](https://user-images.githubusercontent.com/42573183/44627612-2429a200-a931-11e8-9aa9-156954302844.jpg)
![Uploading Hammermanden_001.jpg…]()

**Comment by MaxHayman** [comment]
I'll get this fixed asap. I know what the issue is.

**Comment by rhizo** [comment]
After trying 3 different plants, I knew something was wrong.I am on level 25 seeds. The three plants that will not convert to seeds are:Bitter Elvish ParsleySandy FuskFestering Ashberry
   On Sunday, August 26, 2018, 4:06:14 AM CDT, Max Hayman <notifications@github.com> wrote:  
 
 
Hi @rhizo can you give me the name of the seed you were using.

**Comment by naxzor** [comment]
nice thanks for the quick reply to my post

**Comment by jundii** [comment]
Every level 200 seed I own is not able to be reaped (Healing, Str, Int, AP, Will, etc...)

**Comment by MaxHayman** [comment]
Fix is ready. Waiting to be pushed live. @sioding

**Comment by naxzor** [comment]
@MaxHayman nice you know when it will happen (i am out of healing pots xD)

**Comment by MurkinUnderbush** [comment]
yay cheers man for the heads up.

**Comment by sioding** [comment]
Patches are on friday/saturday - depends on your timezone @naxzor

**Comment by naxzor** [comment]
@sioding cool thanks for the heads up :)

**Comment by Natherul** [comment]
should have been fixed with hotfix today

**Comment by rhizo** [comment]
All fixed

**Comment by MurkinUnderbush** [comment]
thanks. I now have heal pots! huzzah!
