### ISSUE TITLE
Toughness buff of WL Woodsman stance

### ISSUE THREAD

**Issue by Mausini** [WarEmu/WarBugs#12206]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
According to the tooltip it should give 80 toughness and maybe scale with invested points in the tree
actual behaviour: It gives 76 toughness with 13 invested points in woodman tree

Steps to reproduce the problem:
invest some points in to the wl woodman tree and hover over the buff icon of your character

Screenshots/Videos or archive.org evidences:

**Comment by Mausini** [comment]
The stats number according to stats window is correct, the number in the buff icon not.

**Comment by sioding** [comment]
Can we please see some screens?

**Comment by sioding** [comment]
No answer for 13 days - close
