### ISSUE TITLE
alliance bug

### ISSUE THREAD

**Issue by Enoelxx** [WarEmu/WarBugs#12214]
we cant use the alliance chat, it is a bug, here a screenshot i think that help

![enoo_038](https://user-images.githubusercontent.com/19532295/44629455-da03e900-a94f-11e8-8cfe-067a8433d9cc.jpg)

**Comment by sioding** [comment]
Did you set the acciance talk permissions in your guild correct? please show screens from the guild management

**Comment by Enoelxx** [comment]
yeah that is all fine, and the gm saupreusse see the problem too on his
guild window. yesterday was all fine with the alliance chat, but you can
see on the screenshot the guild are lvl 0 and the date is faulse with
01.01.1970.

Am So., 26. Aug. 2018 um 18:15 Uhr schrieb Sio <notifications@github.com>:

**Comment by Natherul** [comment]
please upload a screenshot of your guild permission settings and/or contact me on discord
