### ISSUE TITLE
"Focused Offense"  tanks core tactic [emulator]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#1221]
it reduce toughness too (dont know if visual bug or influence the stat, but it's hard test it with the 25% armor debuff)

**Comment by Evildoor** [comment]
I don't see any difference in toughness on character sheet. Mobs hit naked (0 armor) tank with/without FO for same amounts of damage. Have not tested on players yet.

**Comment by Tesq** [comment]
stop behaviour like that from 3-4 patch , i close this
