### ISSUE TITLE
[Quest] The Sacellum Dungeons - Step 1

### ISSUE THREAD

**Issue by DanaBloodkiss** [WarEmu/WarBugs#12213]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

The quest text says I should speak to "Rotlung" in the Inevitable City to complete the quest. 

Actually behavior is that I have to open the door to the viper vit to complete the quest and then speak to Rotlung. 

I don't know if it's a bug or expected. 

Steps to reproduce the problem:

Take the quest "The Sacellum Dungeons" from the quest giver "Gilden Rekrutierer".

Screenshots/Videos or archive.org evidences:

![horsegirl_012](https://user-images.githubusercontent.com/8588899/44628915-1d0e8e00-a949-11e8-81ed-26dfef99261c.jpg)

**Comment by sioding** [comment]
fixed next patch
