### ISSUE TITLE
AP Regen breaks randomly

### ISSUE THREAD

**Issue by adamversed** [WarEmu/WarBugs#12218]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

This has happened on 3 occasions across about 8 hours of play since the update on the 25th.  It occurs randomly during fight, ap will completely drain, as if flee has been pushed, which is what I thought had happened at first.  

It will then not regenerate, this includes after using /rel and respawn, ap still does not regenerate.  

Additionally when this last occurred I disabled all add ons, as you can see from the screenshot, tried /rel, still ap will not regenerate.  The only way of recovering from this is to exit game or port somewhere.

This is not the usual ap display bug you sometimes get.

Steps to reproduce the problem:

Unfortunately I have been able to nail down a consistent set of steps, my setup, computer and mod wise, has not changed in the last 6 months.  I don't use nerfed buttons, so there's no funkiness going with conditions.

Screenshots/Videos or archive.org evidences:

just after respawn
![1 just after death](https://user-images.githubusercontent.com/7112849/44656327-5817cc80-a9f0-11e8-935b-4c0be0b50939.jpg)

addons now disabled and /rel used
![2 addons disabled](https://user-images.githubusercontent.com/7112849/44656328-5817cc80-a9f0-11e8-970f-10028092ff40.jpg)

attacking near by mob to show not ui issue
![3 proof not a display bug](https://user-images.githubusercontent.com/7112849/44656329-5817cc80-a9f0-11e8-8965-2340ed36c411.jpg)

**Comment by adamversed** [comment]
Further update, I just noticed it think its still stuck in the middle casting, I tried to port and it stated a message "you may not log out while casting"

**Comment by Kaelang** [comment]
As this is a seemingly important flaw with Combat Mechanics, I am tempted to leave this open to be investigated. That being said, this is also almost 2 years' old and a myriad of changes have come into the game. If an issue of this magnitude was still happening - considering the new, larger population RoR has, I'm confident it would be reported more frequently. This, however, is the only report I can see with any information relating to this issue. 

I am going to close this for now - however if you are still playing the server, and you are experiencing this issue with the recent updates, please re-open a fresh report and I'll look to have someone read into this further.
