### ISSUE TITLE
Missing mobs: Saphery Public Quest Trial by fire

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#12212]
Expected behavior and actual behavior:
There should be mobs in 20535:20505 in saphery for stage 1 of PQ Trial by fire, including Impetuous Apprentice, which you need to kill for t3 DE epic quest Honorable Deceit.
Location is empty of all mobs with exception of 3 named champions needed for other quests.

Steps to reproduce the problem:
You can just visit location to see for yourself.

Screenshots/Videos or archive.org evidences:
![1 1](https://user-images.githubusercontent.com/42712833/44627282-d5c9d280-a933-11e8-9247-819bb77d1890.png)
![1 2](https://user-images.githubusercontent.com/42712833/44627283-d5c9d280-a933-11e8-9c8b-49a01d083f05.png)

**Comment by sioding** [comment]
This is a known problem we can not fix atm. Please wait for the next restart of the server.

**Comment by tcosmaz** [comment]
The public quest is not yet fixed.!
![nausica_003](https://user-images.githubusercontent.com/45011451/48430189-ff460d80-e76e-11e8-8b62-a2a3ad07d58b.jpg)

**Comment by Lheana** [comment]
A server restart CAN fix it, but it can also NOT fix it. Wait for a boot, and hope it fixes it.
