### ISSUE TITLE
High Elf Chapter 6 Burden of the Land

### ISSUE THREAD

**Issue by SparkyTheOld** [WarEmu/WarBugs#12211]
I was doing this quest on my White Lion (named Thaldaris) as I noticed something odd (in my opinion) and here's why. 

Expected behavior and actual behavior: The requirement to complete the quest is to kill "Spitesteel Dark Elves" while only "Spitesteel Brigands" actually contribute to quest completion (but killing "Spitesteel Reavers" does not) and since the requirement states that you need to kill 8 "Spitesteel Dark Elves" any "Spitesteel" Dark Elf npc to kill should get you closer to completion instead of only one specific npc.

Steps to reproduce the problem: Start the quest "Burden of the Land" (first step) - go to the spot with said "Spitesteel Dark Elves" and kill 1 each of "Spitesteel Brigand" and "Spitesteel reaver".

Screenshots/Videos or archive.org evidences:
https://i.imgur.com/qcjtY57.jpg (First after killing "Spitesteel Reaver")
https://i.imgur.com/hW2St15.jpg (Second after killing "Spitesteel Brigand")

Not a big issue since it doesn't render the quest unable to complete but it does slow down progress a bit.

**Comment by sioding** [comment]
Thanks for the report. I´va have changed the quest description to make it a bit clearer since we can net set kill XXX or XXX or XXX in one questobject now.
