### ISSUE TITLE
Deathwing Missing 

### ISSUE THREAD

**Issue by Mehem** [WarEmu/WarBugs#12223]
Issue: This bestiary unlock for Giant Bats should be triggered by killing 'Deathwing', a giant bat champion level 40, in Chaos Wastes, inside 'Caves of Terror' (44.6k 3.5k). Deathwing is missing.

Expected behavior and actual behavior: Deathwing should be at around (44.6K, 3.5K) in Chaos Waste inside "Caves of Terror" and is missing. He usually appears with a spider in the same location, and only the spider appears.

Steps to reproduce the problem: Spider was killed 3 times and Deathwing did not appear after the spider respawned twice.

Screenshots/Videos or archive.org evidences:
![mehhem_000](https://user-images.githubusercontent.com/40651834/44697258-cc259500-aa2f-11e8-98cc-d7cec402d8d5.jpg)

**Comment by sioding** [comment]
Sorry can not reproduce. Deathwing is in his cave. Please check again.

**Comment by Lheana** [comment]
Just checked on live, the bat is there. Maybe the boot of yesterday fixed it.
