### ISSUE TITLE
[Marauder] Ability Ferocious assault

### ISSUE THREAD

**Issue by Throatripper** [WarEmu/WarBugs#12225]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: Tooltip states a buff to strenght and toughness by 170 (with 13+ points spent in monstro tree. So my basic strenght and toughness should be increased by said amount, but it increases it by far more. 

Steps to reproduce the problem: Use the skill, im in a PvE area so no bolster present.

Screenshots/Videos or archive.org evidences: https://imgur.com/a/8uZZgMu

**Comment by sioding** [comment]
To make sure its not a paperdoll problem - please add screenshots with ".getstats" output. Thanks

**Comment by Throatripper** [comment]
I tried it and it seems you are correct. I was not aware of this, sorry for taking up your time
