### ISSUE TITLE
Abilities not working in combat

### ISSUE THREAD

**Issue by Andreirex** [WarEmu/WarBugs#12229]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: Sometimes during combat my character becomes inactive, cant even use pots, cant relog cant, use any ability.

Steps to reproduce the problem: As far as I remember this happens  during combat, twice today in half an hour, yesterday once and I don't remember if I was in combat already.

Screenshots/Videos or archive.org evidences: I will attach a screenshot to see my hotbar grey, and abilities that aren't grey cant be used.
![union_001](https://user-images.githubusercontent.com/42803432/44782884-93e19c00-ab80-11e8-8af5-64fa343e76d6.jpg)

**Comment by adamversed** [comment]
This looks like the ap bug I reported the other day, note your ap bar is empty.

**Comment by Andreirex** [comment]
Its not only ap bug, is not allowing you to do anything , not even to log out not to mention of using pots or anything else.

**Comment by grunbag** [comment]
Seems fixed already
