### ISSUE TITLE
[WL] Bug with Pounce

### ISSUE THREAD

**Issue by Tyrean** [WarEmu/WarBugs#1222]
Hi all !!

We got a bug whit pounce abilitie ! For example we can jump whit pounce on destro when they are staying on plateform or on rempart inside keep. So if we are making 3 WL and 3 Healers on party we can kill lot of destro rdps defending from rempart and Plateform . Please fix this issue 

Later all =) !

**Comment by Tesq** [comment]
also as wrote for champion challenge seems ingore root.

**Comment by wiscel** [comment]
Also noticed a few times. The WL can use Pounce whilst in mid-air. 

In scenario a WL jumps me, I punch him of the walls. Whilst flying in the air the WL (Thyme) uses Pounce again and he's back up the walls again :-/

**Comment by milosxe** [comment]
Being able to pounce while in mid air after a punt is how it worked on live, so I don't see that as a bug but as a feature. Same thing with being able to jump on keep walls. I think that it goes under the balancing issue.

**Comment by Evildoor** [comment]
Pounce while Champion's Challenge is active was fixed. Everything else is a balance issue and not a bug.
