### ISSUE TITLE
Character Selection - Trophies

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#12228]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

The expected behavior would be that slotted trophies would show up in the character selection screen. 

It's bugged because slotted trophies don't show up in the character selection screen. 

Steps to reproduce the problem:

Slot a trophie ingame and log out. You will see that you will see no trophie displayed in the character selection screen. 

Screenshots/Videos or archive.org evidences:

Equipped 3 trophies.
![8a04fe7a8242bfade0c6b513541f5a0d](https://user-images.githubusercontent.com/8588899/44753275-cdcd8680-ab1d-11e8-8dc9-74a2f3f85f57.png)

No trophies shown.
![789e110dbf282a045350bee86fec0be4](https://user-images.githubusercontent.com/8588899/44753319-f5245380-ab1d-11e8-9a88-ab01d7e922c6.png)

**Comment by MaxHayman** [comment]
Was fixed 05/01/2021
