### ISSUE TITLE
suspicius hack

### ISSUE THREAD

**Issue by Zoccolova** [WarEmu/WarBugs#12231]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Zoccolova** [comment]
I think Pg Meterpreter not correctly player, lvl 19 full heal when attack that pg.
im We lvl 32 rr43 and not most dmg at this character. plz verify

**Comment by sioding** [comment]
This is the wrong place for such things. Please get in contact with a GM while using the ingame ticket tool.
