### ISSUE TITLE
Apothecary Main items bought in Guild Hall cannot be used

### ISSUE THREAD

**Issue by ScooterMogens** [WarEmu/WarBugs#12230]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
The Apothecary Main items for lvl 25 bought in Guild hall (eg. Preserved Carious Chimerical Claw) can not be used in Apothecary skill although I have lvl 33. The items I find after Butchering works fine. When I click on the item in the backpack (both under Crafting Items and under the normal backpack) nothing happens. And I cannot move it to the right slot in Apothecary.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Duplicate of #10864
