### ISSUE TITLE
Stuck spot in SC Doomfist Crater

### ISSUE THREAD

**Issue by asdf92** [WarEmu/WarBugs#12237]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:not get stuck in object, got stuck in object

Steps to reproduce the problem:Agile escape into it was quite laggy aswell.

Screenshots/Videos or archive.org evidences:
https://imgur.com/a/r41NDuc

**Comment by sioding** [comment]
Have you been kicked in there?

**Comment by asdf92** [comment]
No

**Comment by sioding** [comment]
OK thanks - and sorry we can not remove that spot atm.
