### ISSUE TITLE
T4 Bag Drops for Zone Lock Bugged

### ISSUE THREAD

**Issue by JTr0n1c** [WarEmu/WarBugs#12239]
*Locked High Pass/Talabecland zone for Order at 2100 central time and zone did not give out bags despite awarding renown and notifying of "valiant effort". No rolls were given and usual notification did not happen. Character Name is: Erode 

Expected behavior and actual behavior: Bags should drop after zone lock.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
You report mention that NO ONE gets any bag on zone lock? Is that really true?

**Comment by JTr0n1c** [comment]
Yes, not a single person got a bag from high pass zone. It seems however to
be only isolated to that zone. Bag rolls were confirmed that to be working
in the next zone, Praag.

**Comment by sioding** [comment]
Well - we wait for the next server restart - maybe the bags are delivered then

**Comment by sioding** [comment]
These are manual locks cause of the lord problem. Its a decision of the GM/Lead who locks if bags are given out or not.

**Comment by sioding** [comment]
No answer for 18 day of the original poster. close
