### ISSUE TITLE
 2H Great axe of the Trollslayer is able to be slotted in off hand of slayer

### ISSUE THREAD

**Issue by Bonebrkr** [WarEmu/WarBugs#1223]
Noticed a bug on the slayer 2h where 2H axe can be used in off hand

![hogtooth_019](https://cloud.githubusercontent.com/assets/13813445/9569085/c1fd41b0-4f2c-11e5-9777-359d4c2c5c73.jpg)

**Comment by Silentguard** [comment]
Already reported.

**Comment by DanaBloodkiss** [comment]
Fixed in next update.
