### ISSUE TITLE
PQ stuck Temple of Heimkel

### ISSUE THREAD

**Issue by rhizo** [WarEmu/WarBugs#12233]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: 
PQ not advancing or is stuck because mobs to kill are nonexistent.
This is in the Chaos map / High Pass / NW Corner of the map.
Other quests depends on kills of these mobs like quest: The Blood Forge

Steps to reproduce the problem:
Problem is ongoing

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
This is a known issue we can not fix atm. Please wait for a server restart.
