### ISSUE TITLE
[Quest] Lost in Translation

### ISSUE THREAD

**Issue by Cymor** [WarEmu/WarBugs#12235]
Map tracking is showing at a wrong location.
![image](https://user-images.githubusercontent.com/42836336/44848895-a9c29000-ac58-11e8-8237-8fe7bfa3746e.png)
It should be
![image](https://user-images.githubusercontent.com/42836336/44848734-328cfc00-ac58-11e8-97ec-40bc49d25d14.png)

**Comment by Lheana** [comment]
Why do you think it should be there?

**Comment by Lheana** [comment]
Provide proof please

**Comment by Lheana** [comment]
Quest marker will be fixed with next patch. Nevertheless as it is an introduction to the Land of the Dead, the quest line has been deactivated with last patch.

**Comment by Cymor** [comment]
Thank you !

Regards,

**Comment by Cymor** [comment]
Sorry I've closed this.
Letting it up to you.
Thanks.

Regards,
