### ISSUE TITLE
Cult of Drakk PQ: Cinderfall - Dwarf Chapter 18

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#12238]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

1) Stage 1:
Captive Oathbearers should run away once you right click on them to free them. They remain stationary.

2) Stage 2:
A shield appears around a number of Brazier of the Dragon scenery items. Within, cultist priests appear, and a Bloodthirster also appears. PQ stage has a timer in which you have to kill 8 priests and 8 Bloodthirsters. The priests exit the shield when you target them, the Bloodthirsters appear outside of these and respawn. Priests do not. There are only 7 Brazier of the Dragon items, making it not possible to kill the 8 priests needed to complete this stage. The priests also remain stood upright and frozen when you kill them.

Can't test Stage 3 because of the above issue.

Steps to reproduce the problem:

1) Animate them to flee and disappear.

2) Not sure the shield should remain a barrier at this point, rather be present during Stage 1 and disappear during Stage 2. Drop one more Brazier of the Dragon in this PQ so that there are 8, and there is an additional Priest there to kill. Include an animation to show the priest falling when they are slain.

Screenshots/Videos or archive.org evidences:

**Comment by Lheana** [comment]
For the 1. it's not possible for now.
There are 8 Braziers, don't know which one you are missing, maybe the one on the broken bridge. For the barriers, they are destroyable, have you tried to attack them?

**Comment by Senthoi** [comment]
That's probably it. I'll go and take another look for it tomorrow. Thanks Lheana!

**Comment by Senthoi** [comment]
Hi Lheana, yes, can confirm that other brazier is on the broken bridge. Will retest the PQ over the weekend to check the barriers.

**Comment by sioding** [comment]
No answer for 13 days - close
