### ISSUE TITLE
loot rolls

### ISSUE THREAD

**Issue by velkos4ever** [WarEmu/WarBugs#12244]
loot rolls got a bit confused yesterday.
![nighteye_116](https://user-images.githubusercontent.com/16551075/44946266-d06ffa80-ae01-11e8-8072-4075645f3afd.jpg)
![nighteye_119](https://user-images.githubusercontent.com/16551075/44946273-f09fb980-ae01-11e8-914d-a7668e400493.jpg)

**Comment by sioding** [comment]
should be fixed now
