### ISSUE TITLE
Beastlord quest: Skarlok

### ISSUE THREAD

**Issue by Weaklen** [WarEmu/WarBugs#12242]
Beastlord Skarlok boss lair seems bugged since he is not there and no corpse. 

![neterox_000](https://user-images.githubusercontent.com/42882291/44941549-52c7d280-ada0-11e8-98e6-13bade850264.jpg)

**Comment by sioding** [comment]
He will be back after server restart.Would be nice to know if any error messages were given when he died.

**Comment by Weaklen** [comment]
well we killed all 4 other bosses and missed only him so i really dont know...

**Comment by sioding** [comment]
But he was back after restart - so nothing we can reproduce here now. No chance to reproduce an error means no chance to fix it. Would be great to have a report from the guys who tried to kill him and seen the thrown errors.
