### ISSUE TITLE
Removal of Live Event

### ISSUE THREAD

**Issue by DanaBloodkiss** [WarEmu/WarBugs#12243]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

**You stated that you remove all stuff from old Live events. There are many Live Events NPCs and GOs still in the game. All the NPCs and GOs in the screenshot below should be removed then. It's in the Citadel in the Inevitable City on the right side.** 

Screenshots/Videos or archive.org evidences:

![horsegirl_000](https://user-images.githubusercontent.com/8588899/44944622-55471e00-adda-11e8-8b9d-911eb7e0c214.jpg)

**Comment by sioding** [comment]
fixed with patch from 08.09.2018
