### ISSUE TITLE
Bug: Bestial Token drop (High pass)

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#12246]
If you kill Killing Frost champion Yhetee (High pass 10k:45k) it gives you article to Tome of knowledge, BUT Bestial token, which should be reward for killing him is listed as "???" and does not appear in inventory.
![5](https://user-images.githubusercontent.com/42712833/44948489-fa87e380-ae26-11e8-8447-71e842fb0a5d.png)
![6](https://user-images.githubusercontent.com/42712833/44948490-fa87e380-ae26-11e8-9253-fb066ff0e361.png)

**Comment by Lheana** [comment]
Please stop opening reports for this. ToK unlock "Approprietely Named" does not give Bestial Token, but allow you to claim a cloak: https://wiki.returnofreckoning.com/index.php/Appropriately_Named
**Before opening a report related to ToK, ALWAYS verify your information on wiki and follow instructions of RoR Wiki.**

**Comment by Rockalypse** [comment]
Oh, sorry.
