### ISSUE TITLE
bugged buffed dmg in rvr

### ISSUE THREAD

**Issue by Andreirex** [WarEmu/WarBugs#12245]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:his procs and dmg where 5x higher than normal, only the subjugator proc was over 1k dmg,can be seen that everything was not ok.You can see my dmg 300+ crit on agonising wound...

Steps to reproduce the problem: I jumped on a slayer and simply I was hitting like in a rock while his dmg was not normal.
![unionn_001](https://user-images.githubusercontent.com/42803432/44947172-124c7100-ae01-11e8-9208-4744247c4c40.jpg)
![unionn_002](https://user-images.githubusercontent.com/42803432/44947176-18425200-ae01-11e8-91d2-836dd38b3ef8.jpg)

Screenshots/Videos or archive.org evidences:

**Comment by Andreirex** [comment]
happened again this time vs a BW and AM 
![unionn_003](https://user-images.githubusercontent.com/42803432/44947243-22188500-ae02-11e8-9d46-c469408bfbae.jpg)
![unionn_004](https://user-images.githubusercontent.com/42803432/44947244-22188500-ae02-11e8-8684-77cc4d1a691a.jpg)
![unionn_005](https://user-images.githubusercontent.com/42803432/44947245-22188500-ae02-11e8-9834-a3b9b8abae59.jpg)

**Comment by Andreirex** [comment]
NO is not near WC. All happened near our Keep in Troll country

**Comment by grunbag** [comment]
Proc have been fixed already
