### ISSUE TITLE
"Blast Wave" chosen [skill][emulator]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#1224]
the woudns debuff work fine but in between the value after the debuff and 25% of player hp it seems the skill remove too much damage,

for exemple 
1k life >>>debuff>>>> 750

but if 
1k max but i have lost hp until  750 >>> debuff >>>>  750 

it should not reduce further other hp.

I dont know if it's the skill damage or  the wounds debuff but sometimes it can further reduces hp, it seems like random value the more you get close to mid of hp bar it get more,
My test mate told me he lost 600 hp due to the skill damage (or debuff) when he had lik 50% hp.
It's strage as the  damages i get show on combat log are very low ( think the corect one) and always different by the one my test mate told me he recived ( from like 2 points in difference until 600 hp in difference).

**Comment by ozarmidrashim** [comment]
I can't see anything in the code to support this hypothesis.
