### ISSUE TITLE
Bug: Bestial Token drop (Saphery)

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#12248]
If you kill Slashbeak champion Cockatrice (Saphery 58k:28k) it gives you article to Tome of knowledge, BUT Bestial token, which should be reward for killing him is listed as "???" and does not appear in inventory.
![7](https://user-images.githubusercontent.com/42712833/44948801-f8288800-ae2c-11e8-9f14-20ec35ab13af.png)

**Comment by Lheana** [comment]
Please stop opening reports for this.
**Before opening a report related to ToK, ALWAYS verify your information on wiki and follow instructions of RoR Wiki.**
