### ISSUE TITLE
Bug: Bestial Token drop (Badlands) 

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#12250]
If you kill Elke Raub (Badlands 38k:18k) it gives you article to Tome of knowledge, BUT Bestial token, which should be reward for killing him is listed as "???" and does not appear in inventory.
![8](https://user-images.githubusercontent.com/42712833/44948935-e0063800-ae2f-11e8-8ae5-06f0e3868ee2.png)
![9](https://user-images.githubusercontent.com/42712833/44948936-e0063800-ae2f-11e8-90ba-9548f30ae83b.png)

**Comment by Lheana** [comment]
Please stop opening reports for this.
**Before opening a report related to ToK, ALWAYS verify your information on wiki and follow instructions of RoR Wiki.**
