### ISSUE TITLE
random duplicated items after disconect

### ISSUE THREAD

**Issue by velkos4ever** [WarEmu/WarBugs#12253]
hello i was playing in a scenario and i got disconected for a moment..i loged back and my inventory was full with the same items in all the empty spaces(item name"precursor punchas")
![nightsnob_042](https://user-images.githubusercontent.com/16551075/44950048-0a172480-ae47-11e8-89ff-cb17c379384d.jpg)

**Comment by XmatXergon** [comment]
Had that bug aswell once in Praag after zone lock

**Comment by MaxHayman** [comment]
Going to assume this is fixed. If not please reopen.
