### ISSUE TITLE
Cannot attack targets

### ISSUE THREAD

**Issue by Makali524** [WarEmu/WarBugs#12254]
While questing in Avelorn, I am killing blademasters with a polearm blackguard. When I get in proper distance with the polearm, I go to attack the target and I get error messages saying I cannot attack the target but I still am able to. Some of the skills are red but they can still be used. Although Taunt is about a 50/50 ratio on whether it works or not in this situation.

**Comment by sioding** [comment]
Some screens for it?

**Comment by sioding** [comment]
No answer since 16 days.  Close
