### ISSUE TITLE
Squigherder insta summon abbility bugged

### ISSUE THREAD

**Issue by Dobzse** [WarEmu/WarBugs#12252]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: blow up/eat your squig to instant cast new squig, instead of instant summon your pet you have to cast a new one

Steps to reproduce the problem: blow up or eat your pet, instead of instant summon your pet you have to cast a new one

Screenshots/Videos or archive.org evidences:

**Comment by Dobzse** [comment]
![pocok_001](https://user-images.githubusercontent.com/41837044/45018618-b6fdc700-b02a-11e8-87a8-5dfd6129dd5c.jpg)
![pocok_002](https://user-images.githubusercontent.com/41837044/45018619-b6fdc700-b02a-11e8-94f7-1e35e5580a22.jpg)
![pocok_003](https://user-images.githubusercontent.com/41837044/45018621-b7965d80-b02a-11e8-8eed-b9eeb5764f19.jpg)
![pocok_000](https://user-images.githubusercontent.com/41837044/45018622-b7965d80-b02a-11e8-9523-5cf978bf49ff.jpg)

**Comment by Dobzse** [comment]
as you can see on the screenshots its not instant i had to cast it

**Comment by ManBearSquig** [comment]
IIRC you have to summon a different squig from the one you ate/blew up for it to be instant which is intended behaviour and was how it worked on live.

**Comment by notre4ror** [comment]
The "instant cast" feature doesn't work on eating the squig neither blowing up the pet, that feature stop working time ago doesn't matter wich pet you try to summon after eating/blowing the pet (the used/consumed pet goes on CD).

**Comment by grunbag** [comment]
Fixed at Next patch
