### ISSUE TITLE
Battle Fatigue increasing when using Flight Master between empires

### ISSUE THREAD

**Issue by cheersandbeers** [WarEmu/WarBugs#12258]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Expected: Stacks of Battle Fatigue remaining the same when using the Flight Master.
Actual behavior: My group and I died back in High Pass to teleport back to town, we got two stacks of Battle Fatigue, when we then used the Flight Master to get to the next area (Avelorn, I think) we zoned in with x4 Battle Fatigue. After that we teleported a couple more times and got more stacks every time.

Steps to reproduce the problem:
I just reproduced it by dying in High Pass and then teleporting to Avelorn.
After a little bit of testing, it looks like it only happens when teleporting between empires, going to other places within the same empire does not appear to trigger this effect.

Screenshots/Videos or archive.org evidences:
![x3 battle fatigue](https://user-images.githubusercontent.com/42915590/44959115-b2a4a300-ae9e-11e8-8c1b-bf054b79c0c5.png)
![x5 battle fatigue](https://user-images.githubusercontent.com/42915590/44959116-b33d3980-ae9e-11e8-821b-444042c0fae0.png)

**Comment by cheersandbeers** [comment]
OK, it actually appears to also happen when going between chapters within the same Empire. It's when we get the longer load screen.

**Comment by cheersandbeers** [comment]
I've been able to recreate this twice fully from different empires and many more times teleporting between places to stack... stacks.

Visiting the healer does not fix it either. I removed all stacks twice and then teleported to a different chapter and got stacks back.

Will test again after timer on this one runs out. Going to clear stacks with healer beforehand though, see if they come back.

![x2 battle fatigue after clearing stacks](https://user-images.githubusercontent.com/42915590/44959230-ef24ce80-ae9f-11e8-9eff-fd991677a405.png)

**Comment by cheersandbeers** [comment]
Nope, the stacks did not come back after letting the timer run out, even after using the Healer. The issue seems to be the timer keeps running, something like the effect time gets cleared from the status bar but still runs in the background.

Healing and teleporting is getting expensive, let me know if you'd like further testing but I'm going to stop for now.

Thank you!

**Comment by Uglegutt** [comment]
This also happens when entering pve instances. Confirmed in Gunbad. Solithex instance.

**Comment by ozarmidrashim** [comment]
fix pending

**Comment by cheersandbeers** [comment]
What's it take to get one of those Griffon tokens?

**Comment by Natherul** [comment]
this should have been fixed by now closing.
