### ISSUE TITLE
Sanctified Bullets tactic WH

### ISSUE THREAD

**Issue by Andreirex** [WarEmu/WarBugs#12257]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: If you take the heal tactic from the tree it supposed to heal you 
for 100%, well you don't even have to slot it out cause the tactic heals you anyway so basically you run with 5 tactics. Not fair honestly.

Steps to reproduce the problem:You just need to spamm trial by pain and youll see it doing the job :) Ill attach some pics.

Screenshots/Videos or archive.org evidences:

**Comment by Andreirex** [comment]
![union_002](https://user-images.githubusercontent.com/42803432/44957607-a7b43780-aecb-11e8-9b6c-61fd6d5363da.jpg)
![union_003](https://user-images.githubusercontent.com/42803432/44957608-a7b43780-aecb-11e8-9478-3f81abb24f66.jpg)

**Comment by sioding** [comment]
It would be great to see real tests on real enemys. These dummys are not a good proof for problems with abilities.

**Comment by Andreirex** [comment]
oh God....

**Comment by Andreirex** [comment]
whoever doesn't know or understand the mechanics please don't comment.
![union_004](https://user-images.githubusercontent.com/42803432/44988053-4a7abd80-af81-11e8-92a7-f29c8f20241a.jpg)

**Comment by Andreirex** [comment]
O
![unionn_007](https://user-images.githubusercontent.com/42803432/44988851-f45b4980-af83-11e8-93c7-267d7a3f90cb.jpg)
n the other hand, Witch Elf has same tactic but doesn't bugs out.

**Comment by sioding** [comment]
Watch your words @Andreirex  - i asked nicely.

**Comment by Andreirex** [comment]
Watch my words?  IS an advice for all people who aren't good enough about this game to say anything about mechanics, better is to shut up and not to make stupid comments. I've discovered 4 bugs in 2 days 3 posted , I think is better for those who "are in charge" of wats left of this game to take a look into.
And wats about this this threat , who the fuck you think you're talking to you're pets at home? Fuck off mister gangster , and if you're part of this DEV team resign cause you are shit material.

**Comment by wargrimnir** [comment]
Sioding is performing his job by asking for additional details. Abuse of staff will not be tolerated.

You can serve 3 days of exile in-game for this. I would suggest you mind your manners when addressing staff in the future.

**Comment by ozarmidrashim** [comment]
timing issue with recent changes to apply buffs instantly, affects more than just this tactic. fix pending.

**Comment by sioding** [comment]
fixed with patch from 08.09.2018
