### ISSUE TITLE
Bug: Bestial Token drop (Ostland)

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#12251]
If you kill Sheen Gloomleaf champion Dryad (Ostland 8k:15k) it gives you article to Tome of knowledge, BUT Bestial token, which should be reward for killing him is listed as "???" and does not appear in inventory.
![10](https://user-images.githubusercontent.com/42712833/44949004-4cce0200-ae31-11e8-829b-a3a03831d0ff.png)
![11](https://user-images.githubusercontent.com/42712833/44949005-4d669880-ae31-11e8-907e-eef1cbfa6d21.png)

**Comment by Lheana** [comment]
Please stop opening reports for this.
**Before opening a report related to ToK, ALWAYS verify your information on wiki and follow instructions of RoR Wiki.**
https://wiki.returnofreckoning.com/index.php/Items_(Rewards) -> Read the Note of this page.
