### ISSUE TITLE
Marauder Wrecking Ball

### ISSUE THREAD

**Issue by HtGeist** [WarEmu/WarBugs#12265]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
as tooltip says spin around and hit all within 30ft actual spin around and only hit the mobs infront of you up to 30ft away 

Steps to reproduce the problem:just pulled random low mobs had some behind and some infront..only the ones infront got hurt

Screenshots/Videos or archive.org evidences:
![jormgar_003](https://user-images.githubusercontent.com/16508090/45073779-f7347680-b10a-11e8-96f1-73520ac1d66b.jpg)
![jormgar_004](https://user-images.githubusercontent.com/16508090/45073784-01ef0b80-b10b-11e8-9be4-1eeb78a12a1a.jpg)

**Comment by XmatXergon** [comment]
The tooltip says:
"You spin in a circle with your club arm extended, aimlessly ... to all targets withing 30 feet IN FRONT of you for up to 3 seconds."
Which means, u will hit targets IN FRONT of you, not AROUND you. I know that spinning part may be confusing but thats how this ability work. 
I'm pretty sure if u want to hit all targets around you, you would have to spin your camera, its similar behavior to Raze Morale 2 ability on tanks.

**Comment by FranTiz-Undici** [comment]
Agreed with XmatXergon.
Yeah, the animation it's misleading but this is a "Cone" ability, like Mouth of Tzeentch, just to remain in Marauder class; it's not a "Circle" ability like, for example, Wild swing of the Slayer.

**Comment by HtGeist** [comment]
Well shouldnt it be hitting 360 given the power of other 13 point abilities? or give an immunity to disarm etc like nope not going in there to disarm?

**Comment by Torquemadra** [comment]
Tooltip is clear in that its "in front of you" if you want 360 degree you will need make balance proposal and make a case for it.
