### ISSUE TITLE
Mourkain Temple Guards moving Out of Warcamp and Staying Out

### ISSUE THREAD

**Issue by Luuca** [WarEmu/WarBugs#12264]
**Expected behavior**: Scenario Guards at spawn point on Order side stay up top and if an enemy player gets too close, they kill that enemy player and never leave the warcamp.  

**Actual behavior:** Scenario Guards at spawn point on Order side physically move out and away from their position in the warcamp if an enemy player gets too close, they kill that enemy player and then stay exactly where they killed the player - in the pvp area - never going back to their position in the warcamp. IF a second player gets too close, the Spawn Guard will run over to that player, kill him, and stay there. This creates a chain effect of Spawn Guard killing enemy players while slowly working his way to the middle of the SC zone. 

Steps to reproduce the problem: I have only seen this while playing Destruction in Mourkain Temple. I got within 20 feet of the warcamp, the guard ran down, kille dme and stayed where he was. same scenario, another player got close, the guard ran to him and killed him, and again stayed where he was. 

Screenshots/Videos or archive.org evidences: I have screenshots, will post tonight when I am able.

**Comment by Elhoej** [comment]
Same thing happened with the WC guard in Ekrund the other day.

**Comment by sioding** [comment]
fixed with patch from 08.09.2018
