### ISSUE TITLE
Book of Binding ports wrong

### ISSUE THREAD

**Issue by chouxfleur** [WarEmu/WarBugs#1226]
Since Greenskins map are working my book of binding ports me somewhere in Marshes of madness no matter im bound to ostland warcamp

**Comment by Tesq** [comment]
happened to me too, but after unlock both wc, tome and fly master gave me not anymore trouble.

**Comment by Evildoor** [comment]
This problem was present during first days of T2 Greenskin patch and affected the flight masters as well, but i'm pretty sure it was fixed. Closing this until (and if) someone states otherwise.
