### ISSUE TITLE
Chapter Town Merchant

### ISSUE THREAD

**Issue by LordCrist** [WarEmu/WarBugs#12262]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Class gear sold from chapter town merchants have 1 talisman slot in them, which is great. However the gear sold for Slayer Class has no talisman slots in them, is this done on purpose?

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![merchant gear](https://user-images.githubusercontent.com/42968000/45033361-4d79ba80-b022-11e8-8886-34ebc499c917.jpg)

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 08.09.2018
