### ISSUE TITLE
Destruction Avelorn Quest: Those Who Serve

### ISSUE THREAD

**Issue by aegomez82** [WarEmu/WarBugs#12263]
The quest calls for the blowing of a horn to summon a bloody sun NPC. The horn works, but the NPC does not appear. I noticed this was an issue that was ostensibly fixed, but the horn is not summoning the NPC as of today.

**Comment by Lheana** [comment]
It worked for me, don't know what was wrong in your case. Anyway all quest line needed a correction and rework, that I did.

**Comment by sioding** [comment]
fixed with patch from 08.09.2018

**Comment by sioding** [comment]
fixed with patch from 08.09.2018
