### ISSUE TITLE
WL Pounce on siege weapons

### ISSUE THREAD

**Issue by Drysill** [WarEmu/WarBugs#12268]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: With my WL, from ground floor i can use Pounce on enemy siege weapons deployed by enemy players on the walls of enemy keep and jump there.

Steps to reproduce the problem: I have done it twice already

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
And why should it not work?

**Comment by sioding** [comment]
Aye - from the groundfloor to the siege weapons above - now i got it. Thanks.

**Comment by sioding** [comment]
OK got a message from my lead dev. This is intended - it also works for the SH pounce things.
