### ISSUE TITLE
Flying tree in Barak Varr

### ISSUE THREAD

**Issue by Gideon404** [WarEmu/WarBugs#12274]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Trees should be on the ground.  Trees hovering high in the air are surely a sign of Chaos corruption.

Steps to reproduce the problem:

Go to the coordinates and look up at the sky.  I've probably walked under this thing a hundred times without ever looking at the sky.

Screenshots/Videos or archive.org evidences:

![image](https://user-images.githubusercontent.com/16654707/45184832-0eb15380-b220-11e8-8f17-dc567029cfff.png)

**Comment by lilimx** [comment]
fixed with patch 04/11/2021
