### ISSUE TITLE
Leveling up in renown does not grant renown points until relog

### ISSUE THREAD

**Issue by Rydiak** [WarEmu/WarBugs#12275]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
When you level up a renown rank, instead of awarding you a renown point to spend, the game rewards you with zero renown points.  However, when you log out of your character and log back in the game grants you the renown point.  I've also had guild members say this same bug applies to leveling character levels and mastery points, though I've not tested that yet myself.

Steps to reproduce the problem:
Level up in renown rank.  Attempt to spend a renown rank point at the renown NPC and get told you have no points to spend.

Screenshots/Videos or archive.org evidences:
![rydiak_139](https://user-images.githubusercontent.com/15963532/45204651-8180f580-b245-11e8-95fe-7820dc701e79.jpg)  -- "You have no renown rank points to spend."
![rydiak_140](https://user-images.githubusercontent.com/15963532/45204686-a07f8780-b245-11e8-8237-f25c808d0a5b.jpg) -- Using AnywhereTrainer (this also is accurate on the Renown NPC) to show no renown rank points available.
![rydiak_141](https://user-images.githubusercontent.com/15963532/45204735-c86eeb00-b245-11e8-80b6-0524b01cb03d.jpg) -- Relogging shows 1 Available renown rank point.

**Comment by Kaelang** [comment]
This no longer happens in the latest version of RoR - was able to spend points before relog.
