### ISSUE TITLE
Caemris Sharpspear kill collector does not match his description

### ISSUE THREAD

**Issue by Gideon404** [WarEmu/WarBugs#12273]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

More of a minor issue than a bug.  His tome unlock says he's a shadow warrior.  He looks a lot like a swordmaster.  He looked like a swordmaster on live and it did not make sense there either.

Steps to reproduce the problem:

Not that kind of issue.

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/16654707/45184318-88e0d880-b21e-11e8-8554-0994bf02abfd.png)

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
fixed with patch from 08.09.2018
