### ISSUE TITLE
Destro quest "Green is Best"

### ISSUE THREAD

**Issue by Touket** [WarEmu/WarBugs#12270]
There is no repop of "reikland trueshots" mobs who are part of the QP "Rain of Fire" and where you need to kill 15 for the quest "Green is Best" on destro side. And there is only 12 mobs of this kind on the area. You must complete next phases to make them repop. There is also no repop of some "reikland cannoneer".
That make the quest really long. Thx for next player who will pass by this step ;)

**Comment by Touket** [comment]
forget to precise where is it..... it's on chaos chapter 20

**Comment by sioding** [comment]
Well - this is not a real "bug" - but i got you - doing the PQ completly twice would make the qust a bit long. So the compromiseis that i reduce step1 of the quest from 15 to 12 kills - so you can finish the PQ if you want to - or just follow the quest. fixed next patch.

**Comment by sioding** [comment]
Fixed with patch from 18.09.2018
