### ISSUE TITLE
Puple Bags Stuck in One Reward

### ISSUE THREAD

**Issue by Alfinnete** [WarEmu/WarBugs#12277]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
If the drop chances are all items within bags are the same, 15x same item in a row is highly unlikely for a working random generator.

Steps to reproduce the problem:
I have two characters with repeated reward problem since both could roll purple, a BO and a Chosen, both of them pass 15 purple bags and all repeat a single reward, Chosen GAxe, and BO shield.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
I know that you feeling someone is mocking you - or the system does not work, but bag generation is the same for all bags - there is extra one for the purple bags. I would say: bad luck... this is the real reason:
https://qph.fs.quoracdn.net/main-qimg-1987655064b07cb374ecea67874fa547.webp

So sorry - we checked it but everything is fine.
