### ISSUE TITLE
Dark Elf Ch 7 PQ "The Griffon Gate" T2 Dark Elf Epic Quest Step 12

### ISSUE THREAD

**Issue by Bgjp5150** [WarEmu/WarBugs#12278]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: To be honest I dont remember playing this PQ so I am not sure what the expected behavior is, but I would think there should be something there to interact with to move the PQ along.  It is on stage one which says "Eagle Claws Destroyed", there is nothing to interact with, there are four commanders in the PQ area but killing them does nothing to advance the PQ.

Steps to reproduce the problem:  I have left the area and came back many times, I have relogged as well and so far nothing

Screenshots/Videos or archive.org evidences:

**Comment by Lheana** [comment]
You seem to describe not really clearly the issue where PQ spawns don't appear, even if you have the PQ tracker. So related to #10862

**Comment by Bgjp5150** [comment]
So if I use .pq reset it should reset the NPC’s?  I’ll give it a try. 

Brad

**Comment by Lheana** [comment]
You can not use this command, this is for RoR staff only

**Comment by Bgjp5150** [comment]
Not sure how I could describe it any better, the PQ is not working.  I've been there when several other people showed up also working on the epic quest and nobody else could figure out how to get the quest working.  Not sure what more information I could provide.

**Comment by Lheana** [comment]
It's a known issue, that we can not fix for now. Check after server reboot to see if the PQ is working, since it is not a constant issue.

**Comment by Bgjp5150** [comment]
Ok cool, Thanks.  Much appreciated.
