### ISSUE TITLE
Dworrag Coinbringer flightmaster merging with his flightpad

### ISSUE THREAD

**Issue by Gideon404** [WarEmu/WarBugs#12272]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Minor issue but this NPC should probably be standing on his platform rather than standing inside it.

Steps to reproduce the problem:

No steps required, he's just there.

Screenshots/Videos or archive.org evidences:

![image](https://user-images.githubusercontent.com/16654707/45181716-1e786a00-b217-11e8-8b71-fd9816c485cd.png)
![image](https://user-images.githubusercontent.com/16654707/45181742-3819b180-b217-11e8-8369-bfc15e0d51ab.png)

**Comment by Lheana** [comment]
Usually inconstant issue that can appear and can be fixed with a boot.

**Comment by Gideon404** [comment]
Ok, thanks.  I am happy to close this if you want me to.

**Comment by sioding** [comment]
Since we had that issue bevor on the same flightmaster: #10611

I spoke to him to fligh a little bit higher.

**Comment by sioding** [comment]
fixed with patch from 08.09.2018
