### ISSUE TITLE
Tactics don't appear on login

### ISSUE THREAD

**Issue by Green-Wolf** [WarEmu/WarBugs#1228]
Each time you log in tactics that you last had on don't appear, minor bug but i then forget about them quite alot!

**Comment by Tesq** [comment]
It's a strange cos tactics even if not show are slott and if you change them to slot 2 and then again to slot 1 they appear and even if not show they actually work.

**Comment by Green-Wolf** [comment]
I'll test that when i log in tomorrow, im pretty sure i was logging in and had no tactics and my eagle shot was taking 2 seconds(should be 1 with no quarter)

**Comment by Tesq** [comment]
my absorb tactic worked even if not show maybe only passive tactics work

**Comment by Green-Wolf** [comment]
Checked today, when relaxing on shadow warrior they defiantly not 'hidden' they just don't work.

**Comment by Evildoor** [comment]
Consolidating the empty tactic bar problem in https://github.com/WarEmu/WarBugs/issues/81.
