### ISSUE TITLE
my gear not showing up for other people

### ISSUE THREAD

**Issue by velkos4ever** [WarEmu/WarBugs#12287]
hello i have gear on my char and almost all of the people don't see me wear it
other player point of view:
https://cdn.discordapp.com/attachments/487980372890484746/487980568689115137/unknown.png
my point of view
![nighteyes_711](https://user-images.githubusercontent.com/16551075/45254823-4c7cbc00-b387-11e8-9e09-3e4b0e9ae431.jpg)

**Comment by sioding** [comment]
Well yes - this happens sometimes - the same things happens on NPC - they are also naked sometimes. a restart or rezone will fix it. Nothing we can fix now - cause  of low prio. Sorry.

**Comment by velkos4ever** [comment]
i would't have posted this if it was for 1 time.this has been going for weeks now.but tnx for the responce
