### ISSUE TITLE
Black land after new patch 08.09.2018

### ISSUE THREAD

**Issue by OgiWanBG** [WarEmu/WarBugs#12288]
Hello,
After todays patch, when I am teleported somewhere via book/helicopter I see the ground black.
It happens to every land I teleport High Pass, Altdorf etc etc.

Please find my picture below.
![optimuss_028](https://user-images.githubusercontent.com/42701165/45255298-f90d6c80-b38c-11e8-855b-5890a9270f30.jpg)

**Comment by Natherul** [comment]
shut down game and patcher and restart, some files are not loaded correctly and a second run of patcher solves it
