### ISSUE TITLE
SW didn't get their bow dps applying to melee skills.

### ISSUE THREAD

**Issue by Kweedko** [WarEmu/WarBugs#12285]
Expected behavior

SW  get their bow dps applying to melee skills.(on WAR half of bow DPS aply to melee skills as an offhead weapon for them)

Actual behavior:

SW didn't get their bow dps applying to melee skills. 

Steps to reproduce the problem:

Remove bow lok at melee skill

Screenshots/Videos or archive.org evidences:

![meleewilly_000](https://user-images.githubusercontent.com/13465031/45253059-2f8dbc00-b37a-11e8-874a-452b69a826e4.jpg)
![meleewilly_001](https://user-images.githubusercontent.com/13465031/45253060-2f8dbc00-b37a-11e8-8bdc-fc8e01d02d6d.jpg)
 
You can see tha only ballistic stat applied to skill but not the dps of weapon it self

I bet it's the same for SH, ENGI

**Comment by sioding** [comment]
Just to make sure its not a paperdoll problem - can we please have the same screens with ".getstats" output?

**Comment by Kweedko** [comment]
Get stats give you nothing, if you want it do it youself, instead of waiting me to do it, cause it's conunter productive go create a new char and look.
