### ISSUE TITLE
Too many mastery points available on White Lion

### ISSUE THREAD

**Issue by altharion11** [WarEmu/WarBugs#12297]
Expected behavior and actual behavior:
Too many mastery points available on White Lion when doing repecs. 

Steps to reproduce the problem:
Spec mastery points including the new Oaktoppler tactic. When respecing points the tactics and abilities are not removed. When you then do a respec all the points/abilities up to Oaktopperler are then free.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
I can not reproduce that - tried my best - can you please give more info´s ?

**Comment by altharion11** [comment]
https://www.youtube.com/watch?v=jv0_EF67BDQ&

**Comment by sioding** [comment]
Thanks for the videos. I have removed them here - for some obvious resons. :)

**Comment by altharion11** [comment]
Now where's my chicken mount.

**Comment by sioding** [comment]
Fixed with patch from 18.09.2018
