### ISSUE TITLE
pet`s damage is not counted to scenario summary

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#1229]

**Comment by Evildoor** [comment]
It seems that pet (and i think squigs, turrets and demons present the same problem) counts as a separate npc fighting enemies, so apart from this it can also take away your exp/renown/influence/drops if it gets a killing blow.

**Comment by Evildoor** [comment]
Removed a "Scenario" label since it's a general problem not tied to scenarios.

**Comment by Evildoor** [comment]
According to #2367, pet kills now grant XP.

**Comment by Tiggonos** [comment]
topic is misleading cause its a general problem with pets und varios stages. also IMHO its not a minor problem, especially with epic quests, stalker etc. its tedious when a turret kills the hero and the whole group or even WB doesnt get the quest finished.

**Comment by Natherul** [comment]
this is fixed now
