### ISSUE TITLE
Blue loot bag lost in mail

### ISSUE THREAD

**Issue by tomaslumba** [WarEmu/WarBugs#12298]
Not sure if there is a Point to report this but i lost a blue (T2-T4) bag in the mail. Have gotten bags since the one was lost and was waithing server reboot to resolve this. Was a restart today but didn't get the bra. 

Anything to do? 

Kind regards

**Comment by sioding** [comment]
Sorry but we do not give out any bags who are not delivered. I know that sounds kinda unfair, but if we would do it - we have to log every single bag who was won - and if the bag was used. The GM would have to check that log and hands out a new one. Its too much work for a free2play game. So please - wait for the next one.

**Comment by tomaslumba** [comment]
not a problem, thx for the quick replay - the grind is on! 

Kind regards!
