### ISSUE TITLE
Warrior Priest - Hastened Divinity

### ISSUE THREAD

**Issue by Frostlatte** [WarEmu/WarBugs#12291]
The Tactic "Hastened Divinity" of the Warrior Priest do not renew if you critical hit the target again... but the buff of 50% speed should be given every time you critical hit an enemy. 

The Buff need to run out, before he can activate again. 

before it was correct:

https://www.youtube.com/watch?v=4kkJB1gIgfw

Best Greetings

Morgon /Luthmoor

**Comment by sioding** [comment]
Fixed with patch from 29.09.2018
