### ISSUE TITLE
Decayed Flesh Disk stopped summoning

### ISSUE THREAD

**Issue by Sandskid** [WarEmu/WarBugs#12290]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior: Decayed Flesh Disk stopped summoning after death. Log off/ log on didn't solve the problem. Restarting the game/launcher didn't solve the problem. Location: Dragonwake 

Steps to reproduce the problem: I've been killed on keep, I've resurrected at our keep and since then I haven't been able to summon it. The other disk was working fine.
UP: only zone change solved this problem

Screenshots/Videos or archive.org evidences:
https://youtu.be/OuKHkQ_ihOo

**Comment by Sandskid** [comment]
Same thing happened after I was just afk in another location (Talabecland). After I returned back to the game, I wasn't able to summon this disc.

**Comment by Sandskid** [comment]
Problem have been fixed by reaching PvE lvl 40

**Comment by Natherul** [comment]
I was unable to replicate issue. If the problem persist please comment and Ill reopen the ticket and investigate further. thanks for the report.
