### ISSUE TITLE
Ebon Flame can't complete first step

### ISSUE THREAD

**Issue by Wyvernmoon** [WarEmu/WarBugs#12292]
Clicking on book in first step "Tale of Houses" does not complete step.  T4 Dark Elf Epic.

![tale](https://user-images.githubusercontent.com/41122586/45260635-7e5b4600-b3ba-11e8-9f0f-da43e59cdec2.jpg)

**Comment by Lheana** [comment]
Loot the item Tales of Houses, and right-click on it in the Quest Items section of your inventory...

**Comment by sioding** [comment]
No answer since 10 days. Close
