### ISSUE TITLE
For the quest "Everchosen" the portal is not visible or useable

### ISSUE THREAD

**Issue by aberation** [WarEmu/WarBugs#12300]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:Portal to use no portal available

Steps to reproduce the problem:Provide portal

Screenshots/Videos or archive.org evidences:

**Comment by Wyvernmoon** [comment]
No portal...
![image2](https://user-images.githubusercontent.com/41122586/46845304-eaa9da80-cda8-11e8-87ef-665cd6cf2def.jpg)

**Comment by Lheana** [comment]
This quest has been deactivated with patch of 16/02/2019.
