### ISSUE TITLE
Mail bugged?

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#12306]
I tried to send a few talismans from one character (Xheevah) to another (Nasty). The item is being send it seems, it's no longer in backpack. But when I log to the character who is supposed to receive the item there is no mail at all

Steps to reproduce the problem:

Tried loggin off and on again

**Comment by HtGeist** [comment]
send another mail to same toon,i had problems too not getting mail,sent more stuff and like unclogging the drain 3 mails pop..
