### ISSUE TITLE
elf quest "shades" in shadowlands camp skyblade's hold

### ISSUE THREAD

**Issue by slaughterk1n** [WarEmu/WarBugs#12305]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:
Quest guide text sends player to wrong location for quest goal.  

Quest guide text should say "use light of isha in CAVE south of Matherin"  Instead it says "use light of isha in CAMP south of Matherin" which makes the quest almost impossible to finish since the light of isha is not in the camp, its in a cave.  I was just lucky and stumbled on the correct location.

Steps to reproduce the problem:
just read the text, then look where the quest goal is.

Screenshots/Videos or archive.org evidences:

**Comment by Lheana** [comment]
In real you had to interact with a GO that was not called 'Light of Isha' at all to complete the quest, hence it was not related to the quest, and the description was fine.
I corrected the quest so that it is closer to how it is meant to work.

**Comment by sioding** [comment]
Fixed with patch from 18.09.2018
