### ISSUE TITLE
Stealthed and NPC not resetting

### ISSUE THREAD

**Issue by DanaBloodkiss** [WarEmu/WarBugs#12302]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

**I think when a WE or a WH go into stealth the NPC should reset but actually when you stealth the npc still follow you.** 

Steps to reproduce the problem:

**Log a Witch Elf. Fight a npc -> run away -> go into stealth. NPC not resetting.** 

Screenshots/Videos or archive.org evidences:

/

**Comment by sioding** [comment]
Hey - thanks for the report. Can you please add a proof from goof ord AoR that shows this behavior? It´s not that i don´t trust you - but without some evidences your "I think" is not enough. Thanks.

**Comment by DanaBloodkiss** [comment]
Hello sioding :)

https://www.returnofreckoning.com/forum/viewtopic.php?f=15&t=28360&p=322773#p322773

Here is the confirmation. 

Greetings

**Comment by Natherul** [comment]
this is something that we did not implement by choice. Thanks for the report however.

(ofc this does not mean we might not choose to implement it in the future).
