### ISSUE TITLE
Squig Herder "taste like chicken" and "Farty squig" not instant summon

### ISSUE THREAD

**Issue by albensambo** [WarEmu/WarBugs#12303]
*Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.*

Expected behavior and actual behavior:

Expected : Ability goes off with tool tip damage/heal then allows for instant summon of next pet that is not on CD
Actual: ability goes off with damage/heal with "NO" instant summon just regular cast time

Steps to reproduce the problem:

Any SH can do it

Screenshots/Videos or archive.org evidences:

none taken as any level SH with appropriate ability can test easily

**Comment by XmatXergon** [comment]
this bug still exist
https://plays.tv/video/5c3cdae77afb5fd995/farty-squig-ability-bug

**Comment by Simtexx** [comment]
This ability is still bugged!

**Comment by wargrimnir** [comment]
Don't bump on the bugtracker please. It's not going to get fixed until we figure out how.

**Comment by grunbag** [comment]
Fixed at Next Patch

**Comment by sioding** [comment]
fixed with patch from 23.02.2019
