### ISSUE TITLE
[Sorc] Surging Pain range higher than 30ft

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#1231]

**Comment by ozarmidrashim** [comment]
![sp](https://cloud.githubusercontent.com/assets/6764164/9575241/e909e9d6-4fc5-11e5-9ec1-679135704ef9.png)

**Comment by Silentguard** [comment]
Tested with WH finisher range check.

**Comment by Evildoor** [comment]
Closing per Aza's screen.
