### ISSUE TITLE
Unable to choose dye location for Dominator Shoulders

### ISSUE THREAD

**Issue by vikingofmars** [WarEmu/WarBugs#12319]
![image](https://user-images.githubusercontent.com/37393516/45599220-8b2cfa80-b9b5-11e8-8759-2fac5ec0a581.png)

Attempting to dye Choppa Dominator Shoulders with Chaos Black Dye results in a confimration message without an option to choose which area to dye.

- Skurrga 'Eadcleava of Black Toof Clan

**Comment by sioding** [comment]
Some items can not be dyed cause of client restrictions. I try to verify that.

**Comment by Kaelang** [comment]
![image](https://user-images.githubusercontent.com/60117106/82151897-d7e56a80-9855-11ea-8886-1b4f6ac5d03e.png)

Closing.
