### ISSUE TITLE
Lockout-timer

### ISSUE THREAD

**Issue by rekkir** [WarEmu/WarBugs#12313]
The lockout is ignored simply by reloading ui. 

To reproduce this bug open your character screen, click to show lockout timers and reload UI. 
All your lockouts will disappear.

**Comment by sioding** [comment]
Thanks for the report. Is it the same with a relog or is the lockout visible again? Are you able to fight the same boss you got your lockout before?

**Comment by sioding** [comment]
No answer for 28 days - close
