### ISSUE TITLE
You will no unmounted if you sell the mount

### ISSUE THREAD

**Issue by Vladvon** [WarEmu/WarBugs#12314]
hi my name is Kayzk (chosen)
I'm not good at English.

ride on mount 
　　↓
sell the mount
　　↓
Mount is ride on 

![mount](https://user-images.githubusercontent.com/42826843/45583945-ebfcfa00-b905-11e8-86b4-ff13c333ded1.jpg)

**Comment by sioding** [comment]
fixed with patch from 17.11.2018
