### ISSUE TITLE
The server closed your connection

### ISSUE THREAD

**Issue by Astromin21** [WarEmu/WarBugs#12310]
I got kicked with a character due the fact i was too long afk. 
Since then always when i try to log in this Char again i get the message: The server has closed your connection;you have been disconnected, and background blacks out.

Still can login all my other chars

**Comment by sioding** [comment]
HeyHo - thanks for the report but this bugtracker is only for ingame problems. If you can´t login at all please use our forum or get in contact with a GM on our discord: discord.gg/G9jDWgv
