### ISSUE TITLE
No Mushroom at 'Seeing Green'-Quest

### ISSUE THREAD

**Issue by Blackstaroid** [WarEmu/WarBugs#12318]
Hi there,
as mentioned in the issue's header there is a problem with the Greenskin's quest 'Seeing Green', which is that you don't get the actual mushroom to interact with the herdstone. I've read that it is fixed, but obviously it's still bugged :(. 

Kind regards!

**Comment by Lheana** [comment]
Have you tried just interacting with the herdstone to see if it completes the quest?

**Comment by Twitchiz** [comment]
The heardstone for quest does exist in game however its at the wrong location. I think its in the badlands which is tier 3.

**Comment by Draxonfly** [comment]
yeah it is 'not fixed'. I can't complete it. Says use the Mushroom in your inventory near the heardstone'
The location the quest point yo towards, has Stones with the chains on them (I believe there are meant to be the heardstones) but they are not clickable. Nothing in the quest area is clickable, and you have no mushroom in your innovatory. 
so yeah, Quest is still broken.

**Comment by Lheana** [comment]
We can not implement the quest the way it is meant to be yet, moreover the Herdstone had been mysteriously deleted.
Hence I replaced the Herdstone at its original place, and created a GO 'Mushroom' that I placed at the bottom of the Herdstone. You will now have to interact with the Mushroom to complete the objective.

**Comment by sioding** [comment]
fixed in patch 22.09.2018
