### ISSUE TITLE
Spirits of the Shadow Chaos Chap 5 PQ loot bug

### ISSUE THREAD

**Issue by Cylwen** [WarEmu/WarBugs#12322]
**Expected behavior and actual behavior:**
Pocket item should appear rarely in PQ loot.
Pocket item "Shining Ring" appears in most or around half PQ kill loot.
Bag may fill up before quest can be completed.
Numerous confirmation messages appear after every loot.

**Steps to reproduce the problem:**
Kill Sprite and loot.

**Screenshots/Videos or archive.org evidences:**
![bug report](https://user-images.githubusercontent.com/38857938/45607858-84c08080-ba92-11e8-96f2-2e3bcea93251.jpg)
Screenshot shows many Shining Ring items collected from PQ.

**Comment by sioding** [comment]
Click NO if you don´t wanna have it. Its part of a quest and ppl need it to finish the quest. Its up to you to decide what you are rolling for. So sorry - no bug.
