### ISSUE TITLE
Server range of skills not equal to client range of skills.

### ISSUE THREAD

**Issue by Kweedko** [WarEmu/WarBugs#12323]
Actual behavior:
Server range of skills not equal to client range of skills.
Expected behavior 
Server range of skills equal to client range of skills.

Steps to reproduce the problem:
Go to the edge of ranged skill distance - when ranged skills on panel turn usable, try to fire skill - it doesn't fire- but panels says than that you can fire it.

It's kinda tricky to catch that distance it's on the edge of radius of skills.

That's why on live your skills continue to build when half time of cast is done.

Screenshots/Videos or archive.org evidences:

Instants casts best choice for reproducing. Tried on my SW probably other classes have the same problem cause it lays in the core system of range detection.

**Comment by grunbag** [comment]
Server range is a bit higher than client range .
