### ISSUE TITLE
Invisible water In Talabecland

### ISSUE THREAD

**Issue by doombot696** [WarEmu/WarBugs#12324]
Just pointing out there is invisible water by the horned tower in talabecland. To find this glitch just stand by the door and then proceed to go down the steps, you should see puddles of the same texture that you find when entering water. Video for reference:

**Comment by sioding** [comment]
I can not see any video - can you please add it?

**Comment by doombot696** [comment]
How do i add mp4 video?

**Comment by sioding** [comment]
Use youtube for upload or something like https://www.sharedvid.com/ or or or

**Comment by Rockalypse** [comment]
2 weeks passed
