### ISSUE TITLE
Kotbs - Critbuff not working 

### ISSUE THREAD

**Issue by salamisocke** [WarEmu/WarBugs#12332]
the 2h critbuff tactic, overpowering swing, doesnt work anymore since last patch.
the tooltip in the tacticslot and in skilltree says: "Arcing Swing will now additonally make enemies 0% more likely to be critically hit" (should be 10%)

even the debuff on the enemies only show up as wounds debuff, not showing the increased chance to be crit anymore

**Comment by Torquemadra** [comment]
display issue only, fixed next client push
