### ISSUE TITLE
[WH] Blessed Bullets of Confession not working.

### ISSUE THREAD

**Issue by Bamboozeled** [WarEmu/WarBugs#12337]
Expected behavior and actual behavior:
When switching Bullets. Blessed Bullets of Confession take AP but do not show up on Buffs or when using finishers. Other Bullets seems fine and can be switched to but whenever switching to Blessed Bullets of Confession nothing comes up.

Steps to reproduce the problem:

Switched Bullets numerous times and reloadui and logged in and out and nothing.

**Comment by Torquemadra** [comment]
missed a client setting, set a fix, requires a timer till future client push
