### ISSUE TITLE
WL Tactic Bug : Pack Synergy

### ISSUE THREAD

**Issue by Zzephy** [WarEmu/WarBugs#12334]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior: The WL tactic Pack Synergy is in Career Abilities and not in Mastery Abilities. It's not given like the other abilities and it needs to spend 1 Mastery point to train.
It should be given or display in one of the mastery trees.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![zzeph_003](https://user-images.githubusercontent.com/43386906/45709172-a51c3800-bb83-11e8-9561-c511c631e32e.jpg)

**Comment by k0ut4l1** [comment]
This issue has been solved #12326

**Comment by sioding** [comment]
Duplicate of #12326
