### ISSUE TITLE
WL bonus pet stats are broken

### ISSUE THREAD

**Issue by Mausini** [WarEmu/WarBugs#12336]
Expected behavior and actual behavior:
If I change stances or put of or on equip, the damage of the pet should change.
Damage stays always the same, no matter what I wear or what I skill or whatever.

Buff of pet shows 100/100 in TTT or TTK, no matter what I wear or skill.
TTH shows flat 50 no matter what I wear or skill

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Mausini** [comment]
Don't know what you are planning with the class and when the changes will come but in the state of WL right now, this is a MAJOR bug and gamebreaking for the WL class.

**Comment by Natherul** [comment]
this should have been fixed as of now. 

Issue was compacted by wrong information on tooltips
