### ISSUE TITLE
Lava debuff is not going off after respawn

### ISSUE THREAD

**Issue by Rokatord** [WarEmu/WarBugs#12346]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

When you fall into the lava at Tor Anroc, you will be slowly and start to burn. But as soon as I live again, I still have that effect.

Steps to reproduce the problem:

Jump into the lava and release it.

Screenshots/Videos or archive.org evidences:

![wholamli_002](https://user-images.githubusercontent.com/43446066/45826822-7c1bb480-bcf5-11e8-9d19-cf5ee5ad68ee.jpg)

(Would be cool if I finally got a Manticore)

**Comment by sioding** [comment]
Fixed with patch from 29.09.2018
