### ISSUE TITLE
Quest Name: Sore Feel

### ISSUE THREAD

**Issue by Vladvon** [WarEmu/WarBugs#12343]
Talabecland
Quest Name: Sore Feel
It is a quest to find Valgrum.
Troll is underlaying the He.
Troll can not be selected.
But when I attack with AOE, the troll has come alive.

![kayzk_022](https://user-images.githubusercontent.com/42826843/45805326-745e0f00-bcf9-11e8-805b-f25db286c91f.jpg)

![kayzk_025](https://user-images.githubusercontent.com/42826843/45805344-82ac2b00-bcf9-11e8-9562-dbb735f72ca0.jpg)

![kayzk_027](https://user-images.githubusercontent.com/42826843/45805512-d74fa600-bcf9-11e8-81a2-64979066bbc3.jpg)

**Comment by sioding** [comment]
Hm don´t see the bug ight now cause you get the questobject Valgrumfound done - but i will have a look at it

**Comment by sioding** [comment]
ok - checked that - this troll is important for the quest lore - so i don´t touch him - buuut i set him invulnerable - so he won´t get any dame from AoE spells anymore.

**Comment by sioding** [comment]
fixed in patch 22.09.2018
