### ISSUE TITLE
The Naked Bug

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#12341]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

UPDATE 21/09/18
Spoke to various players who display this issue. 
Black Guard Azoreal is wearing Mercenary gear on its own. Has a pocket item equipped.
Chosen Brezerk is wearing Conqueror gear with BL chest piece appearance. He switched to Mercenary appearance on top of Conq chestpiece, and I could then see his armour. A third player said though that he suddenly then appeared naked on their screen.
I tried replicating all of this on my sorceress, Ithilsyn. Did not appear naked to anyone in the vicinity. Seems to be a problem with files loading up rather than the gear itself?
A guess here, but could it be to do with the update of graphics on group members reticule that Yali announced in the 19th August Client changelog? (at least for the missing chest piece issue. The fully naked bug has been around for over a year at least)

Expected behavior and actual behavior:

Seems to be two problems here. 

1. From time to time, a player appeared unclothed; dressed in their underwear only, despite wearing armour in game. 

2. Some players appear partially clothed, although on females even their top underwear vanishes with this bug leaving, to put it tactfully, little triangles over their nipples (!!). The rest of the armour appears. This appears from what I gather, to affect those wearing the Conqueror body. So far I have witnessed this on the Shadow Warrior, Black Guard, Chosen, Archmage, and White Lion. The WL I questioned in detail about this is wearing the Silver Oak lair body as appearance gear over his Conq, but others seem to have the standard body on so not certain that this is adding to the problem.

Steps to reproduce the problem:

1. The fix for this is to unequip then re-equip the cloak.

2. The player needs to relog from the game to get rid of this, although it does not always work.

Seems the armour files aren't loading up correctly on peoples' screens. 

Screenshots/Videos or archive.org evidences:

1. Images illustrating this problem

![ithilsyn_266](https://user-images.githubusercontent.com/22262165/45770711-0eab4d80-bc3b-11e8-80b6-f498bafd47fa.jpg)

![senthoi_021](https://user-images.githubusercontent.com/22262165/45770899-942efd80-bc3b-11e8-8678-b8cfff3f9fc5.jpg)

2. Images illustrating this problem

![senthoi_026](https://user-images.githubusercontent.com/22262165/45771116-2afbba00-bc3c-11e8-92ff-01e4a4ec338e.jpg)

![senthoi_050](https://user-images.githubusercontent.com/22262165/45771155-3fd84d80-bc3c-11e8-80b4-e92af72d427e.jpg)

![senthoi_089](https://user-images.githubusercontent.com/22262165/45821904-36092580-bce2-11e8-8883-b452588a6bce.jpg)

**Comment by MaxHayman** [comment]
Should be fixed next patch

**Comment by sioding** [comment]
fixed with patch from 08.12.2018
