### ISSUE TITLE
KotBS: Shining Blade proc 10 sec

### ISSUE THREAD

**Issue by Goldenboy88** [WarEmu/WarBugs#12358]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
In the tooltip of Shining Blade it says, "for the next 5 seconds", but on my Character the timer says 10 seconds. Do not know which one is intended, or where the mistake seems to be.

Screenshots/Videos or archive.org evidences:
![ulfwernher_000](https://user-images.githubusercontent.com/43515676/45927762-44507f00-bf38-11e8-81f4-7a5ebb550831.jpg)
![ulfwernher_001](https://user-images.githubusercontent.com/43515676/45927763-44507f00-bf38-11e8-817b-489c3453dbdf.jpg)
![ulfwernher_005](https://user-images.githubusercontent.com/43515676/45927764-44507f00-bf38-11e8-9497-114de32639cb.jpg)

**Comment by Torquemadra** [comment]
Should be 5s, thanks for report.

**Comment by XmatXergon** [comment]
Also it proc on any range attack/ability beside DOT, as i posted it here:
https://github.com/WarEmu/WarBugs/issues/12201,
either Tooltip is wrong because it says "On next Melee attack" or ability proc on range abilities incorrectly.

**Comment by sioding** [comment]
Fixed with patch from 29.09.2018
