### ISSUE TITLE
Cleansing an Empire (Last Mission) - Boss in Wrong/Unattackable Place

### ISSUE THREAD

**Issue by Nikolaes** [WarEmu/WarBugs#12352]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Boss is normally at the very top of the tower in Unterbaum Castle, but he (Eustasius Lang) is standing in the corner of the room where the final boss of the PQ is. However, he is not attackable. Tried through melee, range, and AOEs. Could not get a hit to pull him. Screenshots below. Unable to finish final quest.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

![cae last mission 2](https://user-images.githubusercontent.com/43499009/45918657-5a870e00-be58-11e8-88d2-b780f5c7fc9f.jpg)
![cae last mission 3](https://user-images.githubusercontent.com/43499009/45918658-5a870e00-be58-11e8-8e4e-633ceef8aea9.jpg)
![cae last mission 1](https://user-images.githubusercontent.com/43499009/45918659-5a870e00-be58-11e8-90e2-8a095a69ad64.jpg)

**Comment by Nikolaes** [comment]
No this isn't happening to any other NPC.

I'm confused as to when you tried him as he is still standing in front of me. Did you test it on a test server?

He's still right here, In the wrong place still. He should be one floor up even if I could hit him.
![nikolaes_011](https://user-images.githubusercontent.com/43499009/45918855-deda9080-be5a-11e8-89ca-7866f3f3184e.jpg)

**Comment by Lheana** [comment]
Yes tried on test server, and just killed him on live.

**Comment by Lheana** [comment]
After I could kill him without problem, he is back to his right place.

**Comment by Nikolaes** [comment]
Okay good. Unfortunately, I abandoned, thinking I could repick the quest from the NPC, because the quest said something about use an item. So I can't get the quest back, so I can't further test for you. Sorry.
