### ISSUE TITLE
Lion Home PQ Not Progressing

### ISSUE THREAD

**Issue by john-blaine** [WarEmu/WarBugs#12351]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
After completing first stage of Lion Home public quest, the second quest should allow you to kill the "Lion Guardians". However, no lion guardians appear and no matter how many mobs (lions, stalkers, hunters, boss) you kill, the progress in that second stage does not tick up. It is therefore impossible to complete the quest.

Steps to reproduce the problem:
Just try to complete the Lion Home Public Quest in Chrace (the 2-3 player one south of ORvR).

If you find this was a true bug and want to give me a token, my account is Sanctus57, I normally play sanctusthepale or sanctusblade chars

**Comment by Lheana** [comment]
Works fine. Maybe you have to search better.
As a reminder, here is the area of the PQ:
![anaehll_120](https://user-images.githubusercontent.com/11537611/45918656-9e930680-be8a-11e8-82da-2cf2cd4e221d.jpg)

**Comment by john-blaine** [comment]
Terribly sorry, I must have missed them
