### ISSUE TITLE
PQ Duraz Dok

### ISSUE THREAD

**Issue by zibiman** [WarEmu/WarBugs#12359]
Expected behavior and actual behavior:there are 2 Friendly npcs spaowns at 3d stage near door they attaking the PQ npc when i pull them from the door and kill 1 from them then PQ stuck at 9/10 cant finish pq then

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
fixed with patch from 08.10.2018
