### ISSUE TITLE
Cloak Colour bugged

### ISSUE THREAD

**Issue by Uthwe** [WarEmu/WarBugs#12355]
Hi,

I'm wearing normal precursor cloak without alternative appearance.  When I log in with guild heraldry unchecked it shows guild heraldry. Then I check and uncheck guild heraldry and my cloak shows the colour i dyed it, but for everyone else it shows white. Doesn't matter what I do or how i dye the cloak it either shows white (on other people's computers) or the guild heraldry. 

Friend has the same issue.

thanks.

**Comment by MaxHayman** [comment]
Hi can you check this after this weeks update.

**Comment by Uthwe** [comment]
Hi Max,

thanks for all your work, but I quit the game a few months ago.

Peace

**Comment by sioding** [comment]
fixed with patch from 08.12.2018
