### ISSUE TITLE
Can't retake canceled quest, until relog.

### ISSUE THREAD

**Issue by Kweedko** [WarEmu/WarBugs#12366]
Actual behavior:
Can't retake canceled quest, until relog.

Expected behavior 
You can retake canceled quest, after abandoned it without a relog.

Steps to reproduce the problem:

1. Take quest from questgiver
2. Abandon It
3. Interact with questgiver Again - there is no quest to retake
4. Relog - there is a quest to retake.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Thanks for the report, but this is working as intended.

**Comment by Kweedko** [comment]
are you fucking kidding me need to relog for taking the quest - it's work as intended?

**Comment by sioding** [comment]
Watch your words - last warning for you.
Back to the topic: you can also wait 5 minutes with no relogging and then you can take the quest again. Its our way to prevent power leveling since our exp per mob change in patch 04/08/2018
