### ISSUE TITLE
 [Engineer] Trench fighting + auto-attack

### ISSUE THREAD

**Issue by rhix112** [WarEmu/WarBugs#12369]
Why engi's tactic Trench fighting dont buff auto-attack, i tested it and dps the same.

**Comment by sioding** [comment]
Please add your testing screens.

**Comment by rhix112** [comment]
its grants 15% dps if under 45 feets of target, it should buff aa

**Comment by sioding** [comment]
your screenshots please.

**Comment by rhix112** [comment]
![asurion_002](https://user-images.githubusercontent.com/31020540/46004850-96221200-c0bc-11e8-9148-9e259e62c172.jpg)
![asurion_003](https://user-images.githubusercontent.com/31020540/46004851-96221200-c0bc-11e8-9b9c-1286f2e3e4fc.jpg)

**Comment by Torquemadra** [comment]
Why should it? Did it on live?

**Comment by rhix112** [comment]
ye ofcourse, engi's buff stuck 40% working with aa and this buff should

**Comment by sioding** [comment]
@rhix112  - any prrof for this like a old patchnote or video or something?

**Comment by sioding** [comment]
If you want to change things like this please create a proposal here: https://www.returnofreckoning.com/forum/viewforum.php?f=78
