### ISSUE TITLE
NPC does not reset properly

### ISSUE THREAD

**Issue by Rokatord** [WarEmu/WarBugs#12361]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

If killed by the war camp guards, they should be reset.

If the guards were accidentally pulled in front of the Order War Camp, they will not reset. One of the guards remains very close to the climb to the battlefield target.

Steps to reproduce the problem:

Pull a guard. Release. Pull him again. Release. Pull him again.....

Screenshots/Videos or archive.org evidences:

NORMAL
![rokathhord_000](https://user-images.githubusercontent.com/43446066/45928862-68b55700-bf4a-11e8-9af5-9cbdc95a80de.jpg)

Step 1 to bug it:
![rokathhord_002](https://user-images.githubusercontent.com/43446066/45928875-84b8f880-bf4a-11e8-9682-04f5934bf75a.jpg)

Step 2 to bug it:
![rokathhord_003](https://user-images.githubusercontent.com/43446066/45928880-9ac6b900-bf4a-11e8-8051-9b42ff9611fd.jpg)
Very frustrating. So you can not perform any strategic maneuver properly.

Best regards from Rokatord!

**Comment by XmatXergon** [comment]
Yes, that happens in a lot Warcamps or even Chapters that are close to RvR zone. I think its caused after patch which made NPCs MOVING back to their orginal position instead TELEPORTING as it was ealier.

**Comment by MaxHayman** [comment]
It might be fixed in a patch coming soon. I'll let you know once its live.

**Comment by Natherul** [comment]
same as https://github.com/WarEmu/WarBugs/issues/12208
