### ISSUE TITLE
Dying in "Port of Barak Varr" chapter, respawn in RvR Warcamp

### ISSUE THREAD

**Issue by Loutrattitude** [WarEmu/WarBugs#12364]
**Expected behavior and actual behavior:**
Dying in the "_Port of Barak Varr_" Chapter 8 (Rank 16-17) in "_Barak Varr_" map ( Greenskin pairing) respawn the player in the "_Foultooth's Warcamp_" (RvR Warcamp of the same map). Player should respawn near the Chapter 8, where the healer is (approx. 56k-26k).

**Steps to reproduce the problem:**
Dying anywhere in the zone will respawn the player at the wrong location. Tested with 3 different characters at 3 different locations (the 3 different PQ located in this area)

**Screenshots/Videos or archive.org evidences:**
![portofbarakvarrespawn](https://user-images.githubusercontent.com/27932747/45950658-0ec39880-c001-11e8-9f08-9cfa569a39c9.jpg)

**Comment by Kweedko** [comment]
There is alot of places like this where you dying in chapter and respawning in RVR warcamp.

**Comment by Kabucoror** [comment]
set the correct respawn locations for the whole map with next patch

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
