### ISSUE TITLE
SW Bullseye tact not procing form dots crit ticks

### ISSUE THREAD

**Issue by Kweedko** [WarEmu/WarBugs#12363]
Actual behavior:
SW Bullseye tact not procing form dots crit ticks

Expected behavior and 
SW Bullseye tact procing form dots crit ticks like on live

Steps to reproduce the problem:

use the tact, apply a dot skill on target wait it crit

Screenshots/Videos or archive.org evidences:

**Comment by Kweedko** [comment]
> OK @Kweedko - thanks again for a report - but again...you didn´t added any proof for your statement that it worked on live. Please add it.

"Whenever you critically hit an enemy, your chance to critically hit is increased by 20% for 5 seconds, but you also become 10% more vulnerable to being critically hit." - key word WHENEVER. 

What proof you need more - trying to find a proc from crit of dot(without direct dmg spam after that) in 5 years ago closed game in youtube video where almost nobody not using this tact, with shitty resolutions and abysmal interfaces where you cant see a thing that they are using?

It's counter productive - whats a point of you being here like not trying yourself to find a proof that i'm wrong.

Every time there is situation like this - i'm less and less want to post a bugreports. It's a BUGREPORT - you are in role of QA - it's your work to get proofs, don't shift you duties on players.

**Comment by sioding** [comment]
Duties? QA role? My work to get proofs? I would kindly suggest to read this one again:
https://www.returnofreckoning.com/forum/viewtopic.php?f=2&t=13607

**Comment by grunbag** [comment]
Proc or abilities that trigger damage only works with direct damage dealt .
