### ISSUE TITLE
Marauder Item with %block

### ISSUE THREAD

**Issue by withfakemail** [WarEmu/WarBugs#12362]
Just got an item from a Lootbag that is Marauder locked but has 2% block

Btw i posted this on a trashmail account because i won`t post here anything with my real one.

Screenshots/Videos or archive.org evidences:
http://www.bilder-upload.eu/show.php?file=fd6007-1537722853.jpg

**Comment by sioding** [comment]
Fixed with patch from 29.09.2018

**Comment by sioding** [comment]
Fixed with patch from 29.09.2018

**Comment by sioding** [comment]
Fixed with patch from 29.09.2018
