### ISSUE TITLE
[choppa] Wear em down tactic not working as intended

### ISSUE THREAD

**Issue by Titoos** [WarEmu/WarBugs#1236]
This tactic should return 25% of your rage, so literaly it should give you 25 rage, to allow you to use E-Blow instantly, but it gives around 15 rage instead, so it's useless now.

**Comment by ozarmidrashim** [comment]
That tooltip wording is some of the worst I've ever seen.

**Comment by Silentguard** [comment]
Should actually return you to fury at 25 career mechanic points.

**Comment by Evildoor** [comment]
I confirm, on live WHO it set you to 25 rage regardless of your current rage.

**Comment by ozarmidrashim** [comment]
Yeah, I understand the report is correct, hence why I marked at as High Priority. Just generally raging against the tooltip here.
