### ISSUE TITLE
Khaine's Embrace: Khaine's Wrath not killing Engineer Turrets

### ISSUE THREAD

**Issue by dbddhkpuka** [WarEmu/WarBugs#12370]
Expected behavior and actual behavior:

When Khaine's Wrath is brought forth, every player inlcuding their pets inside the detonation radius should be killed.
At least for Engineer turrets placed inside this area this is not the case. The turret gets no damage at all and stays active the whole time and can be used further when returning.
(I entitled the report with turret only because I wasn't able to test it with other pet classes, yet.)

Steps to reproduce the problem:

Place a turret near one of the flags, wait for detonation, return to it.

Screenshots/Videos or archive.org evidences:

No yet, will try to make a video this evening (EU).

This behaviour can be used to place a pet constantly near the flags to guard it, making it harder to cap the flag in the first place, plus for turrets you can place them let's say on top of some objects, where only RDPS can reach them.

**Comment by dbddhkpuka** [comment]
Here is the video now: https://youtu.be/g34UrBxWEz4

**Comment by thorbolt80** [comment]
The magus pet don't die also

**Comment by sioding** [comment]
fixed with patch from 17.11.2018
