### ISSUE TITLE
[SM skill] Phantom blade do not stack with Vaul's mastery point.

### ISSUE THREAD

**Issue by kam19080** [WarEmu/WarBugs#12372]
I found that, the Phantom blade will not upgrade after i use the mastery point in Vaul's tree.

It's still 47 wounds when the vaul's point in 1 and 15.

Is it normal or a bug?

**Comment by sioding** [comment]
Can we please see your testing screenshots?

**Comment by kam19080** [comment]
Full mastery point in vaul:
[https://ibb.co/j6znxU](url)

Zero master point in vaul:
[https://ibb.co/c4EgP9](url)

**Comment by sioding** [comment]
Ok thats the tooltip you are talking abaout, but whats with the real damage? Have you tested it?

**Comment by kam19080** [comment]
I tested the real healing, 

0 mastery point:
https://ibb.co/gTkb99

12 mastery point:
https://ibb.co/jSOrbp

Its got different, so that its just the description of skill (bugged).
The real effect of skill is in good condition.

Thank you so much

**Comment by sioding** [comment]
Thanks for testing it.
