### ISSUE TITLE
Book of binding

### ISSUE THREAD

**Issue by ililith** [WarEmu/WarBugs#12373]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Bound myself to Rallymaster in the Kadrin Valley WC (destruction)
when I use the Book I end up in Thundemountain WC

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
You have bound to the wrong rally master. This is the correct one:
![image](https://user-images.githubusercontent.com/18517842/46038946-c0032500-c10c-11e8-83cd-ec27aec39add.png)

We know that problem - but we can not fix it atm.
