### ISSUE TITLE
quest order side black crag chapter 21 name : death from above

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#12374]
the next step of "death from above" : you must kill blackclaw in the red area in BC

I killed all monsters in the area and they didn't grant the quest. (blackclaw feeder)
![thorbolt_458](https://user-images.githubusercontent.com/16274785/46042562-fd1fe500-c115-11e8-93e0-f55c0dd97fb6.jpg)

![thorbolt_459](https://user-images.githubusercontent.com/16274785/46042608-1759c300-c116-11e8-981a-751effde9832.jpg)

**Comment by Lheana** [comment]
Look up on the top of the statue.
