### ISSUE TITLE
[RvR] RAM goes through doors during siege.

### ISSUE THREAD

**Issue by XmatXergon** [WarEmu/WarBugs#12375]
Expected behavior and actual behavior:
RAM should not get through doors during siege.
Imho, after last patch that upgraded RAM HP, it also somehow affected his possibility to go through doors.
Enemy (RAM operators) cant use RAM after it goes through doors and opposite side (defenders of keep) can easily kill RAM inside.

Steps to reproduce the problem:
Try to deploy RAM on spot, with carrier approach doors in different angles or carrier get punted/knocked away w/o getting dismounted, not sure.
Also so far i experienced its happening for Destro side, not sure if that also happen for order.

Screenshots/Videos or archive.org evidences:
![xergov_079](https://user-images.githubusercontent.com/37849311/46048381-5e9d7f00-c129-11e8-82fd-87fc8304dbd3.jpg)
![xergof_020](https://user-images.githubusercontent.com/37849311/46048382-5f361580-c129-11e8-91a6-c9d999aedd43.jpg)

**Comment by XmatXergon** [comment]
I think it also related to that situation, somehow Order player could pull Destro ram and carry it.
https://plays.tv/video/5baf9ec5a90e07015a/ram-bug

**Comment by Natherul** [comment]
I have not seen this in a while now, please comment if it happens again and Ill reopen the ticket and investigate further.
