### ISSUE TITLE
[Harvest of Fear] Quest

### ISSUE THREAD

**Issue by Vladvon** [WarEmu/WarBugs#12377]
I'm sorry.
It's not a big bug
The quest [Harvest Fear]
requires you to find Radcliff Shoerner
But Quest Waypoint is in a different place.

![ss](https://user-images.githubusercontent.com/42826843/46062810-ecb74b00-c1a5-11e8-911e-9d053fc008ec.jpg)

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
Fixed with patch from 29.09.2018
