### ISSUE TITLE
[Respec bug] some spells (auras,buffs) stay after respec and save their values

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#12385]
They also saves their "values" based on amount of points spent in the tree. Example: Spec full tree (15 pts), turn aura/buff on, respec, aura/buff will save it value.

<img src="https://monosnap.com/image/yhUnFbhsOhSFMWK5jvwmCwPpAApLlv.png">

https://www.youtube.com/watch?v=R9wzm3VLVEU

tested on chosen, BW, kotbs

**Comment by Natherul** [comment]
I tested just now with a chosen and it does in fact cancel the auras. If there is a specific buff please tell what one.

atm its not coded for other then aura effects. So it should disable kotbs, chosen, doks and wp auras.

**Comment by Nfkillz** [comment]
bw https://www.youtube.com/watch?v=i333rYwhHdM

**Comment by sioding** [comment]
fixed with patch from 27.10.2018
