### ISSUE TITLE
Greenskin quest tooltip incorrect

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#12386]
Expected behavior and actual behavior:
quest name : the powers that be ( second(?) chain step )
ToK tip says any Oathbearers.
only Oathbeaer Miner kills are counting.
quest area : greenskin chapter 16. mobs are in Ambush Canyon PQ area.

Screenshots/Videos or archive.org evidences:
![gs_quest](https://user-images.githubusercontent.com/19988772/46259279-5458f780-c512-11e8-84e5-b7c4d062491a.jpg)

**Comment by Lheana** [comment]
For now we can not set objectives like any Oathbearers, like the quest is meant to work, that's why it has been set that way.

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
