### ISSUE TITLE
[WE] influence raward DvsG RvR T3

### ISSUE THREAD

**Issue by DieSidhe** [WarEmu/WarBugs#12388]
Blackteef's Boyz Greenskeen Black Fire Pass War Camp influence raward RvR t3 DvG
Cant get a reward from NPC Gark da Crusha
![111](https://user-images.githubusercontent.com/43729142/46261481-ce7e8180-c4fc-11e8-8e0f-c2a377840041.jpg)
![222](https://user-images.githubusercontent.com/43729142/46261483-d6d6bc80-c4fc-11e8-97a1-4ccdaeaf480b.jpg)

**Comment by sioding** [comment]
This is a know issue we can not fix atm. Please use the rally master in badlands.
