### ISSUE TITLE
(BO) Chance block

### ISSUE THREAD

**Issue by TwettY** [WarEmu/WarBugs#1238]
Dear admins I understand everything but after your corrections Black orcs block markups hardly falls even tactics on the block is !!!! Please solve the problem !!!!

**Comment by ozarmidrashim** [comment]
When posting bug reports, please stick to the facts and leave the emotions and "please solve the problem / please fix!" part out.

There's supposedly a problem with the scenario shield for BO.

**Comment by TwettY** [comment]
То Есть вы считаете правильным что я в стойке держать строй идет одни париравани и укланения и то через раз, а блока нету вобще после последних ваших исправлений! В то время когда ордену бью вщит у меня поним высакивает блок! Еще поставил тактику на блок 10% и 5% и вобще нету эфекта!! Я уже молчу что танкам каким то волшебным образом пробивают по 700 урона!!!

**Comment by TwettY** [comment]
So you think I'm right in the front to keep the operation going, and some pariravani uklaneniya and then after a time, and just do not have the block after your latest patch! At a time when the Order beat vschit my understanding vysakivaet block! Another tactic to put a block of 10% and 5%, and just do not have effect it !! I'm not talking the tank somehow magically penetrate 700 damage !!!

**Comment by Evildoor** [comment]
If i understand correctly, there was a problem with 0 block rating on BO's shield from scenarios (lvl 20), which is fixed now.
