### ISSUE TITLE
Avelorn keep disconnect

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#12384]
Every time I get near keep gates there is a chance of disconnect if I look in their direction
It feels is if some object is loading in which leads to crash.Deleting Cache folder have not helped.

**Comment by Rockalypse** [comment]
As I kept expiriencing this bug in other locations I figured that thats not object which made me disconnect, but something in graphical settings - if you are playing on "ooo, shiny" graphic preset - there is good chance of game closing itself, when alot of models are being loaded in same time. "fastest framerate" option solves the problem.

**Comment by sioding** [comment]
already fixed
