### ISSUE TITLE
NPC - Faldan Roughwold should be a woman

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#12383]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
By reading the text, it is easy to surmize that Faldan should be a female npc, as she talks of her husband.
Actual, is a male NPC.

Steps to reproduce the problem:
Talabacland 22k,49k

Screenshots/Videos or archive.org evidences:
https://ibb.co/gZVgWp

**Comment by sioding** [comment]
Fixed with patch from 29.09.2018

**Comment by gittoaster** [comment]
looks like this NPC has reverted to male again.

**Comment by Lheana** [comment]
The quest that is shown is the introduction of the quest, it's not what Faldan is meant to say.

**Comment by Lheana** [comment]
And the quest giver is a woman, so everything is fine. Faldan is meant to be a man.
