### ISSUE TITLE
GreenSkin Quest Marker

### ISSUE THREAD

**Issue by Kiplin1999** [WarEmu/WarBugs#12387]
Expected behavior and actual behavior: Quests are showing up complete after accepting, if you interact you can't complete the quest but the option is there. Not a major problem as you can still go do the quest and return to complete.

Steps to reproduce the problem: Carry on.

Screenshots/Videos or archive.org evidences: I never took a screen but problems occur on the first greenskin quest where you would spawn back in day.

**Comment by Lheana** [comment]
#8000
