### ISSUE TITLE
Beastlord: Khorgash in a wall

### ISSUE THREAD

**Issue by Nikolaes** [WarEmu/WarBugs#12391]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Khorgash expected to be in the corner of the cave. He is deep in the walls, unable to be touched.

Steps to reproduce the problem:

Waited. Tried to pull from the wall. Could not reach

Screenshots/Videos or archive.org evidences:

![nikolaes_017](https://user-images.githubusercontent.com/43499009/46324750-110a9180-c5c3-11e8-8ed7-89947be78db4.jpg)
![nikolaes_018](https://user-images.githubusercontent.com/43499009/46324751-110a9180-c5c3-11e8-8cc4-23618a3458c1.jpg)
![nikolaes_019](https://user-images.githubusercontent.com/43499009/46324752-110a9180-c5c3-11e8-8b43-6eaf27b9459d.jpg)

**Comment by sioding** [comment]
Checked on dev server - everythring is fine - you have to wait for a server reboot of the live server
