### ISSUE TITLE
[shaman] tooltip bugs

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#12396]
Expected behavior and actual behavior:
1. Fury of Da Green
tooltip shows 0 healing amount.
skill icon missed mechanic effect, green fire.
![shaman_fury](https://user-images.githubusercontent.com/19988772/46371723-1dc2de80-c6c4-11e8-89d5-a6869e34cc6b.jpg)

2. Big Waaagh!
tooltip shows 0 damage.
3. Sticky Feetz
skill's in Da Green path but tooltip says Path of Mork.
![shaman_tooltip1](https://user-images.githubusercontent.com/19988772/46371897-8d38ce00-c6c4-11e8-9769-6218d3d6029a.jpg)

**Comment by grunbag** [comment]
Fixed on Next Patch

**Comment by sioding** [comment]
fixed with patch from 09.03.2019
