### ISSUE TITLE
Dragon's Bane quest - Invalid ....

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#12398]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Quest (see Screenie) shows clearly the bug.. Invalid Scenario...

Steps to reproduce the problem:
Talk to Saelir Haleril Eataine Ch16.

Screenshots/Videos or archive.org evidences:
https://ibb.co/bzd5ie

**Comment by sioding** [comment]
Since this Scenario is not available the only solution is to disable the quest atm. thanks for the report.

**Comment by sioding** [comment]
fixed with patch from 08.10.2018
