### ISSUE TITLE
Issue with guild tactic slots

### ISSUE THREAD

**Issue by Goodblades** [WarEmu/WarBugs#12399]
Issue is with our guild tactics we trained a new tactic point and it is now showing the only available tactics to be slotted are Enhanced glory 2 and 3 and enhanced training 3 all other slots are unavailable but shows we trained enhanced fame 3 but will not allow us to slot the other tactic. We have 3 slots available but doesnt show as a purchased tactic on the purchased guild tactics but does show on our show tactics under purchased

Character name Goodblades
Guild Emo Bunnies 
Rank 13 guild

**Comment by sioding** [comment]
Can you please add a screenshot for this ?

**Comment by Goodblades** [comment]
![screenshot 2](https://user-images.githubusercontent.com/43801929/46394330-72f3f580-c6ae-11e8-9654-ea5d43920411.png)
![screenshot 3](https://user-images.githubusercontent.com/43801929/46394370-8a32e300-c6ae-11e8-88f1-0aef45a3a489.png)

**Comment by sioding** [comment]
well - thanks for the screens - but that doesn´t help to understand it. You are allowed to slot one statbuff/defensivebuff/offensivebuff on a standard. I tried the same as you and can not reproduce it on my own:
![image](https://user-images.githubusercontent.com/18517842/46398049-4bc01700-c6f4-11e8-9f2e-6d793641e909.png)
On your screen i see the Enhanced Fame on the purchased card but not available as a tactic - is that the problem you described?

**Comment by Goodblades** [comment]
Sorry, basically yes enhanced fame is not available to slot even though we trained it and it is showing enhanced glory 2 and 3 are both showing up instead. this happened when we trained enhanced training 3 and enhanced glory 3. Thanks for help hope its easier to understand was pretty late for me!

**Comment by Natherul** [comment]
please confirm if this is still and issue. I am unable to replicate this issue
