### ISSUE TITLE
[Oil] mechanics of some classes increase range and damage of oil

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#12394]
Slayer/choppa mechanics increase oil damage

turret of engy/deamon of magus increase oil damage and range 

https://clips.twitch.tv/ThirstyFancyFloofYee

**Comment by Natherul** [comment]
Partly fixed in upcoming patch, Damage should not be increased HOWEVER I could not replicate any range increase.

**Comment by sioding** [comment]
fixed with patch from 08.10.2018
