### ISSUE TITLE
"Rogni Ironsight" not giving "Gnoblar Huntin" quest

### ISSUE THREAD

**Issue by Filsiss** [WarEmu/WarBugs#12397]
Hi Team,

It seems Rogni Ironsight (Altdorf Library) doesn't give "Gnoblar Huntin" quest anymore.
I'm adventure rank 34 and I never took this quest before.

![image](https://user-images.githubusercontent.com/43795613/46375120-d96b1a80-c692-11e8-9eb1-d0663dc983fb.png)

Can someone help ?

Thanks in advance,

**Comment by sioding** [comment]
correct. the quest is available with level 35
