### ISSUE TITLE
Book of Binding & Flight Master Bugs

### ISSUE THREAD

**Issue by Green-Wolf** [WarEmu/WarBugs#1239]
When in marshes of madness and i use book of binding it teleports me under the swamp (With Book set the Troll country warcamp (Order).

When in Troll country warcamp and flying to marshes of madness it teleports me to a random place in Ostland.

**Comment by Tesq** [comment]
also if you fly/book from ic when moving  to dwarf  you usually arrive at destination, while ideed fly from dwarf to emp or viceversa create these type of random teleport issues.

**Comment by ozarmidrashim** [comment]
Fixed in next patch (some code designed to allow pets to cross between regions was coming in and resetting the zone to the original one.)

**Comment by Green-Wolf** [comment]
Awesome, loving the explanations too :)
