### ISSUE TITLE
White Lion Trained To Hunt 50% attk speed boost disappearing 

### ISSUE THREAD

**Issue by carmine3161** [WarEmu/WarBugs#12405]
Expected behavior: 50% attack speed boost is on as long as trained to hunt is your active training

Actual behavior: turns off every time you re summon pet, this can be annoying in a fight when your pet dies and you re summon it and don't notice yourself missing the 50% attack speed boost 

Steps to reproduce the problem:
have pet die / un sommon and then resummon (must have pack hunting tactic on)

Screenshots/Videos or archive.org evidences:
https://www.youtube.com/watch?v=r-ld4cOvva8&feature=youtu.be

**Comment by sioding** [comment]
fixed with patch from 14.10.2018

**Comment by Runiez** [comment]
its back again :)

**Comment by ttbrizio** [comment]
It's back and it's annoying :P

**Comment by sioding** [comment]
Please don't use the bugtracker as a forum nor do we need bumps on the reports to make sure they are recognized

**Comment by grunbag** [comment]
fixed
