### ISSUE TITLE
Trophy / Belts invisible / Not showing

### ISSUE THREAD

**Issue by Lasenza** [WarEmu/WarBugs#12403]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Expected behavior - belts and trophies show for charcaters in game. Actual Behavior - some trophies bought with bestial tokens not showing,  belts appear to be the same also , possible sync error as unequipping and re equipping belt made it appear for both parties. Of note , Re equipping belt and getting them to appear made some trophies appear but not all appear (rivals trophy appeared , as did sigil of the tormentor and dragonseye pendant , although the pendant showed in the wrong location)

Steps to reproduce the problem:
trophies that dont show as follows - torture tools, rune of dominion , sigil of the tormentor, dragonseye pendant (equipped on a lvl 31 DoK) , Rivals Trophy , Skinning blade & tainted claw (equipped on lvl 35 w/e) , noticed in Inevitable city whilst characters were partied as we'd just bought new trophies. Belts that were invis as follows - steadfast bladebelt with senlathin bladebelt appearance.  Fangharhese Vilecord - no alternate appeance , (belts were rvr rewards) 

Screenshots/Videos or archive.org evidences:
![43101102_678091779241155_1847145140565573632_n](https://user-images.githubusercontent.com/43828623/46437710-e996fe80-c753-11e8-9033-0f51d70d3df8.jpg)
![43153053_2208681159369467_442553254086180864_n](https://user-images.githubusercontent.com/43828623/46437711-e996fe80-c753-11e8-82a4-0f7719254490.jpg)
![lasenza_006](https://user-images.githubusercontent.com/43828623/46437712-ea2f9500-c753-11e8-9d92-3684c2d612a2.jpg)
![lasenza_007](https://user-images.githubusercontent.com/43828623/46437713-ea2f9500-c753-11e8-92aa-54b10be94921.jpg)
![42977587_537054933383790_7855540272950673408_n](https://user-images.githubusercontent.com/43828623/46437714-ea2f9500-c753-11e8-85b9-3748fe7a5633.jpg)
![43040048_586495578432782_5648527875716939776_n](https://user-images.githubusercontent.com/43828623/46437715-ea2f9500-c753-11e8-8ede-c7950c8bf7d5.jpg)

**Comment by MaxHayman** [comment]
Should be fixed in next patch

**Comment by sioding** [comment]
fixed with patch from 08.12.2018
