### ISSUE TITLE
Unstackable dyes.

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#12409]
There are two absolutely identical dye items with different Item codes, so they are not stackable as they should be.
![veszal_126](https://user-images.githubusercontent.com/42712833/46569377-cee3a600-c95c-11e8-89f2-fb48e3e6f955.jpg)
![veszal_125](https://user-images.githubusercontent.com/42712833/46569379-cee3a600-c95c-11e8-9d0f-e9434ade4816.jpg)

**Comment by sioding** [comment]
Hm where did you get them? Drop/Vedor/PQ Loot/Quest?

**Comment by sioding** [comment]
already fixed
