### ISSUE TITLE
[Zealot] Transference not healing on Waves of Chaos

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#12401]
Expected behavior and actual behavior:
![trans](https://user-images.githubusercontent.com/40274248/46432659-1399f200-c74f-11e8-80cb-6fdda4c6b6ee.jpg)
![woc](https://user-images.githubusercontent.com/40274248/46432724-37f5ce80-c74f-11e8-9cc5-95c1843cda0b.jpg)

With _Transference_ equiped you should be healed by half of your direct-dmg. The dmg-effect of WoC doesn't seem to be effected though.

Steps to reproduce the problem:

Equip both tactics and hurt a target with WoC.

![trans-woc](https://user-images.githubusercontent.com/40274248/46432859-93c05780-c74f-11e8-9792-583c8340dea0.jpg)

**Comment by Laurentz18** [comment]
Sadly, I do not recall that on live Waves of Chaos could proc Transference. But considering how weak WoC is and how generally meh the rituals are this could be a nice addition to actually make it worth taking especially now that WoC cannot trigger AP regen off of Innervation Ritual.

**Comment by grunbag** [comment]
Transference add a heal on direct damage , and doesn’t affect proc or tactic that trigger damage
