### ISSUE TITLE
Dagger of crushed Foes / Stats

### ISSUE THREAD

**Issue by zibiman** [WarEmu/WarBugs#12406]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![ahhhh_005](https://user-images.githubusercontent.com/16434526/46508862-cd708b80-c83f-11e8-916b-51d428c4f1b4.jpg)

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
fixed with patch from 27.10.2018
