### ISSUE TITLE
[Conquerer] Boots and Gloves not tradable

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#12402]
Boots and gloves of all RvR/SC-Sets are _Bind on **Equip**_ and so can be traded.
Only the boots and gloves of the Conquerer-Set are _Bind on **Pickup**_.

![conq-bop](https://user-images.githubusercontent.com/40274248/46433068-31b42200-c750-11e8-9270-45498130d38a.jpg)
Only got Dominator as a reference (same tier), but the other sets can easily checked at the vendors.

**Comment by sioding** [comment]
Sorry but this is not a bug - it is intended. BiS gear will be BoE until new BiS gear is released.
