### ISSUE TITLE
Powered Etchings

### ISSUE THREAD

**Issue by Toldavf** [WarEmu/WarBugs#1241]
Currently the snare tied to the tactic is uncleansable. Not sure if its intentional, if not I recommend changing it to a curse from a debuff.

**Comment by ozarmidrashim** [comment]
Whatever type is given by the client is the type we use on the server. Until we can change the types on the client, that won't change.

**Comment by Tesq** [comment]
how  in the icons player buff/debuff ui label the snare? 

debuff, damage, curse ......?

If it's show as debuff/damaging it's is not cleanse able.
