### ISSUE TITLE
Rally point bug

### ISSUE THREAD

**Issue by Sandskid** [WarEmu/WarBugs#12414]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior: when you set your rally point to Praag wc, you actually spawn @ Chaos Wastes wc

Steps to reproduce the problem: set your rally point to Praag wc and try to use a book of binding

Screenshots/Videos or archive.org evidences:

**Comment by Lheana** [comment]
There are 2 rally masters in Praag WC, you just have to talk to the right RM to set your rally point to Praag.
For now we can not do better, here is the reason: #10992
