### ISSUE TITLE
Ancient Stag not a Stag

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#12413]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Avelorn, 58109:25297. There's a neutral dryad marked as an Ancient Stag.

Steps to reproduce the problem:

Rename as Ancient Dryad.

Screenshots/Videos or archive.org evidences:

![ulralys_171](https://user-images.githubusercontent.com/22262165/46573990-b0999c80-c994-11e8-8378-99b741bb8231.jpg)
![ulralys_172](https://user-images.githubusercontent.com/22262165/46574000-c3ac6c80-c994-11e8-8613-6c42ae8e965f.jpg)

**Comment by Lheana** [comment]
This has been fixed many patches ago.

**Comment by Senthoi** [comment]
Thanks Lheana, I'd forgotten all about this! ;)
