### ISSUE TITLE
The Drakk Revealed

### ISSUE THREAD

**Issue by Sinrman** [WarEmu/WarBugs#12415]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

- Checked, no open tickets on this quest

Expected behavior and actual behavior: 

Expected -Free 5 prisoners to complete. Kill Drakk Wardens to loot keys to free prisoners.

Actual-  Drakk Wardens have no keys.  Just click on cage to free. Freed 20 prisoners and none counted toward quest. They only counted toward PQ completion.  Killed every Warden in area, no keys.

This is in a PQ area (The Cult of Drakk). You can see in my screenshot I freed 20 prisoners in PQ but none counted for quest. I almost completed the PQ except for the Hero at end. I let the PQ reset and tried again with no luck. I even relogged.

![gunnr_003](https://user-images.githubusercontent.com/42098334/46576819-80083180-c999-11e8-8f1e-96d652691bb8.jpg)

![gunnr_002](https://user-images.githubusercontent.com/42098334/46576796-8e098280-c998-11e8-9450-73adc7988db0.jpg)

**Comment by Lheana** [comment]
You can complete the quest by just talking to the dwarves inside the cages once they are open.
Nevertheless, I set the quest like the PQ, you will now have to click on the cages to open them.
Concerning the keys that Drakk Warden are meant to drop, the PQ is also meant to work that way but we can not make it that way for now.

**Comment by sioding** [comment]
fixed with patch from 08.10.2018
