### ISSUE TITLE
[PQ] Cult of the Magus

### ISSUE THREAD

**Issue by oetterer** [WarEmu/WarBugs#12410]
Concerning qp "Cult of the magus", Empire Chapter 11

When advancing to Stage II, no enemies are spawned, thus making it impossible, to
* advance the pq to stage III
* solve empire chapter 11 quest "An Army Marches", which needs you to kill monsters from stage II

**Comment by Lheana** [comment]
Read the description of the stage ... You have to go inside this cave:
![lheana_004](https://user-images.githubusercontent.com/11537611/46571964-7f15d680-c97e-11e8-9f00-daef46d6a521.jpg)
