### ISSUE TITLE
[Smugglers Weapons] BO-Weapons missing at merchant

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#12429]
All Subjogator weapons should be avaible as Smugglers-Version, also all Subjos should be tradable.
-The smugglers version of the Bigchoppa(2h sword) is missing.
-You can trade in 5 dif Subjogator items for the 1h Sword (incl. two cloaks?)
-You can trade only 4 (3 each) items for Shield, 2h-Hammer and Cloak (1h sword, shield and 2h-hammer)

![smugglers1](https://user-images.githubusercontent.com/40274248/46618704-8a086c80-cb20-11e8-9bbb-68a64f7c4bd0.jpg) ![smugglers2](https://user-images.githubusercontent.com/40274248/46618705-8a086c80-cb20-11e8-8b31-5e513668445c.jpg)

**Comment by Torquemadra** [comment]
Because the Cleava is also used by the choppa so its trade has additional options to facilitate both the BO and the Choppa.
