### ISSUE TITLE
[QUEST] Tricks of the trade

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#12422]
Quest tricks of the trade is broken in several ways:
*You can't target listed mob (30:35) properly and can only agro him by AOE
*This mod does not drop head listed in quest
![veszal_129](https://user-images.githubusercontent.com/42712833/46582491-64ac2d80-ca50-11e8-910d-8ceca90e41de.jpg)
![veszal_128](https://user-images.githubusercontent.com/42712833/46582492-64ac2d80-ca50-11e8-8557-9b7c4de481d5.jpg)
![veszal_127](https://user-images.githubusercontent.com/42712833/46582493-64ac2d80-ca50-11e8-8d0d-03014fafb0e1.jpg)

**Comment by Lheana** [comment]
You could complete the quest by just killing the Prisoner right next to the quest giver.
Nevertheless, I modified the quest so that Prisoners inside carts now drop the item needed.

**Comment by sioding** [comment]
fixed with patch from 14.10.2018
