### ISSUE TITLE
Black Orc Right in the Jibblies

### ISSUE THREAD

**Issue by HtGeist** [WarEmu/WarBugs#12427]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:expect it to just debuff ws with no tactic slotted it knocksdown mobs and in rvr punts the tactic to make that happen takes effect even tho its not slotted handing out immunities in rvr.

Steps to reproduce the problem:
dunno use right in the jibblies without slotting the tactic.

Screenshots/Videos or archive.org evidences:
![teefgrinda_052](https://user-images.githubusercontent.com/16508090/46591925-72ad8d00-cae8-11e8-921a-b90cfa20542b.jpg)
![teefgrinda_053](https://user-images.githubusercontent.com/16508090/46591932-7e00b880-cae8-11e8-9bac-884237629871.jpg)
![teefgrinda_054](https://user-images.githubusercontent.com/16508090/46591946-8d800180-cae8-11e8-8682-2c75676b9495.jpg)

**Comment by Scophis** [comment]
_Right in da jibblies_ was changed some time ago to act like on live. Knocking up/interupting in RvR and Knocking down in PvE.  Not sure about the immunities, though.

**Comment by HtGeist** [comment]
But they ruined a ws debuff with it...short distance..nobody ever went i wanna punt this guy,but i dont want him to go over the edge,short is fer kickin gits around warcamp..it was the most useless tactic ever to slot,now if it was super punt,so in middle of sc i could aim for our warcamp and launch the guy to the guards,maybe...still other tactics more needed.

**Comment by Scophis** [comment]
It's not meant as a punt (without tactic), it should just work as an interupt in RvR, even if the target has immunities up. The kick is just a funny little animation ;)
I tried to figure out if itself grants immunities, but it's hard to see in RvR. 
In PvE however it's a knockdown and grants immunity.

**Comment by Torquemadra** [comment]
All KB in pve are knockdowns due to NPCs not all having animations to facilitate knockbacks. Please confirm this to be an issue in PvP because it shouldnt grant immunities but should always interrupt.

**Comment by HtGeist** [comment]
![teefgrinda_061](https://user-images.githubusercontent.com/16508090/46734306-05068a00-ccbd-11e8-858d-1250b4cd52b2.jpg)
![teefgrinda_062](https://user-images.githubusercontent.com/16508090/46734321-0e8ff200-ccbd-11e8-9a9f-1c535603499b.jpg)
![teefgrinda_063](https://user-images.githubusercontent.com/16508090/46734341-1b144a80-ccbd-11e8-9e2d-80e546bdef5c.jpg)
Seems to be fine in rvr tubby stunty didnt get immunity atleast...he didnt even get up into eye height,guessing they got alot of junk in the trunk (anvils,gyrocopters etc..) or gravity is just super fond of those lil things.

**Comment by sioding** [comment]
Thanks for the retest in RvR - i guess this can be closed now?!

**Comment by HtGeist** [comment]
Yea sure close it my concerns must have been brought about by pug sc enviroment..where someone has been throwing immunities about like candy at a kids party.
