### ISSUE TITLE
[Dye] Midnight blue does not apply

### ISSUE THREAD

**Issue by Jaycub** [WarEmu/WarBugs#1242]
Midnight Blue dye does not apply to any armor piece and is consumed in the process. Have tried it on 3 different pieces of gear across 2 characters on both realms.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
