### ISSUE TITLE
New Allies, New Enemies! Praag

### ISSUE THREAD

**Issue by Sinrman** [WarEmu/WarBugs#12423]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

- Checked, no current open tickets on this quest.

Expected behavior and actual behavior:

Expected - Free 4 captive Smiths
Actual - There are only 2 Smiths. You will get "Already Talked to" if you try to free them multiple times. Waited 10 min and they did not reset. But if you log out and log back in you can free them again to complete.
![gunnr_004](https://user-images.githubusercontent.com/42098334/46583392-c43c1600-ca1b-11e8-97a7-94a8bb58719c.jpg)

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by lilimx** [comment]
fixed with patch 03/08/2022

**Comment by graffernsl** [comment]
WOW! so unexpected. thx a lot!
