### ISSUE TITLE
friendly oil in enemy keep

### ISSUE THREAD

**Issue by velkos4ever** [WarEmu/WarBugs#12426]
![nighteye_171](https://user-images.githubusercontent.com/16551075/46587515-600a6800-ca96-11e8-958e-c5df281c22ba.jpg)
![nighteye_172](https://user-images.githubusercontent.com/16551075/46587516-600a6800-ca96-11e8-846c-ff40a9bca8a8.jpg)
![nighteye_173](https://user-images.githubusercontent.com/16551075/46587517-600a6800-ca96-11e8-982d-358fc1a4db71.jpg)

**Comment by Natherul** [comment]
this should not be pospsible anymore, if the issue persist please comment again and Ill reopen and investigate
