### ISSUE TITLE
Quest Bred, Fed and Led

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#12421]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Did check

Expected behavior and actual behavior:

Expected behavior:
No "Finished quest" Indicator on Thordis Valdar, Also in in-line help should be:

* Kill Lounging Bandit 0/6
* List of Collaborators Recovered

Actual behavior:
On stage when You must kill Serpent Fang Bandits, there is a "Finished quest" Indicator on Thordis Valdar, even, when it;s not Finished.
Also In-line help there is:

List of Collaborators Recovered
Kill Sperpents Fang Negociator
* Kill Lounging Bandit 0/6

Steps to reproduce the problem:

Take the quest and proceed

Screenshots/Videos or archive.org evidences:

//////

I don't know what's the idea for the repeated sentances in in-line help. i.e. in quest Useless there is:
Verminkin Clanrat Tail
* Verminkit Clanrat Tail 0/1.

There is a repetition in many quests. Is this intended?

**Comment by Lheana** [comment]
Fixed the quest markers.
Concerning the fact that the mark of finished quest appears even when the quest is not finished yet: #8000

**Comment by sioding** [comment]
fixed with patch from 14.10.2018

**Comment by StaH84** [comment]
Lheana, I know I should report only one thing. How can I contact You to explain what I mean?

**Comment by Lheana** [comment]
You can send me a PM on forum. Nevertheless, I think I fixed what you reported (see above my previous messages). Don't hesitate to send me a PM if you still wish to.
