### ISSUE TITLE
"Messin' Wif Da Stunties" quest Invalid GameObject

### ISSUE THREAD

**Issue by Loutrattitude** [WarEmu/WarBugs#12420]
Expected behavior and actual behavior:
The quest "Messin' Wif Da Stunties" given by "Odug Hut-Bur" in "Kadrin Valley" RvR WarCamp (Destruction) has incorrect description.

Steps to reproduce the problem:
Finish the previous quest the Kadrin Valley NPC give (located in Gromril Junction in RvR lake), and this quest has incorrect description.

Screenshots/Videos or archive.org evidences:
![questkvwc](https://user-images.githubusercontent.com/27932747/46580922-90b6b700-ca2e-11e8-9bc7-e676b108ab37.jpg)

**Comment by sioding** [comment]
fixed with patch from 14.10.2018
