### ISSUE TITLE
Sky's the Limit (Altdorf)

### ISSUE THREAD

**Issue by Sinrman** [WarEmu/WarBugs#12424]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

-Checked, no current open tickets.

Expected behavior and actual behavior:

Expected - Get 10 "Wealthy Merchants" to sign petition. 

Actual - Must have the name "Wealthy Merchant" above the NPC to count.  I tried all other Merchants, Nobles and Townsfolk but, only "Wealthy Merchants" worked.  The problem is there are only 2 "Wealthy Merchants" in Altdorf and they do not reset unless you log out and log back in. So you must relog 5 times to complete quest.
![gunnr_007](https://user-images.githubusercontent.com/42098334/46583478-b9828080-ca1d-11e8-8555-3a762a42c246.jpg)
![gunnr_006](https://user-images.githubusercontent.com/42098334/46583479-bc7d7100-ca1d-11e8-8a21-9a12caaac03b.jpg)
![gunnr_005](https://user-images.githubusercontent.com/42098334/46583480-bedfcb00-ca1d-11e8-8d42-94f67b361ad9.jpg)

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Sinrman** [comment]
Yes, that is why I submitted them back to back.

**Comment by Lheana** [comment]
The real objective of the quest should be to talk to any merchant in Altdorf. The quest has been modified as we can not implement it that way yet.

**Comment by sioding** [comment]
fixed with hotfix from 28.01.2019
