### ISSUE TITLE
[BO} save me hide

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#12438]
not sure if ti was intentionaly change this way but anyway, save me hide do not apply the buff for reduces for 4 sec the magical dmg to whole group it just buff your toughness; reporting this in case as the tooltips still say it should debuff magical dmg for 4 sec.

both icon in buff ui for the magic debuff component is missing (is not the toughness one) and get stats tell nothing about the eff be there

so either tooltips need to be update or skill be fix

**Comment by Torquemadra** [comment]
Tooltip is clear

"Increases your Toughness by {COM_1_VAL0} for 20 Seconds. Group members within 100 feet will take only 80% incoming magic damage for the next 4 seconds."

Which means YOU get a toughness boost and your GROUP gets a incoming magic damage reduction, the player casting it does NOT benefit from the incoming magic damage reduction portion.

Ability functions correctly.
