### ISSUE TITLE
[Chosen] Can`t equip Crusher of the Wicked

### ISSUE THREAD

**Issue by pfs2222** [WarEmu/WarBugs#12435]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Lv.19 Chosen, bought Crusher of the Wicked in AH. It is type axe, chaos, moin.rank 15 . Cannot equip it, in description "Axe" is typed in red.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![wulfrigk_000](https://user-images.githubusercontent.com/30259009/46784403-41be9980-cd2e-11e8-923c-cb7c19704612.jpg)

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
fixed with patch from 27.10.2018
