### ISSUE TITLE
[Smugglers Weapons] DoK cloack missing at merchant

### ISSUE THREAD

**Issue by pikara** [WarEmu/WarBugs#12431]
DoK cloack "Subjugator's Greatcloack" (STR version) not in buy list. U can only change it for other items.

![takhi_012cloack](https://user-images.githubusercontent.com/19285502/46632177-0f544700-cb4a-11e8-949e-ddafa59d0c73.jpg)

**Comment by Torquemadra** [comment]
Subjugator's Greatcloak is a BG item.

**Comment by pikara** [comment]
Well, i take that pic from my DoK. If here is no STR cloack for DoKs maybe need remove the option? 

![takhi_012](https://user-images.githubusercontent.com/19285502/46697088-21022100-cc14-11e8-8e0b-26a5b6e6c116.jpg)
