### ISSUE TITLE
The Eagle's Claw

### ISSUE THREAD

**Issue by Sinrman** [WarEmu/WarBugs#12432]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

- Checked, no open tickets currently.

Expected behavior and actual behavior: 

Expected- Speak with Prince Eldrion to complete quest.

Actual - Speaking to him does not complete Eagle's Claw quest.  Was able to take and complete other quests from Prince Eldrion but this one quest will not complete.
Abandoned quest and tried again. No marker above Prince Eldrion's head after retaking quest. Talked to him. Still could not complete. 

![gunnr_008](https://user-images.githubusercontent.com/42098334/46703203-bb9a3a00-cbeb-11e8-9307-61b46fda31a2.jpg)
![gunnr_009](https://user-images.githubusercontent.com/42098334/46703206-c0f78480-cbeb-11e8-9c6e-4a4c791305fe.jpg)

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Sinrman** [comment]
Saw the fix in the patch so I tried it and it worked! Thanks for quick work and all you do!

![gunnr_011](https://user-images.githubusercontent.com/42098334/46916355-db7c8580-cf7e-11e8-822b-7ff5de50651e.jpg)

**Comment by sioding** [comment]
fixed with patch from 14.10.2018
