### ISSUE TITLE
Chop Fasta! affects Infernal Wave

### ISSUE THREAD

**Issue by Lefze** [WarEmu/WarBugs#12437]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Chop Fasta! (BO and Choppa variant) should not affect Sorcs Infernal Wave. It currently does.

Steps to reproduce the problem:

Have a choppa/BO pop the buff, spam IW.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
And why should it not affect Infernal Wave - did i miss somethin in the patch notes?

**Comment by Lefze** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=23117&hilit=Chop+Fasta

Here you have the actual patch.

**Comment by sioding** [comment]
Well - your linked patch says something about Chop Fasta but definitly not that it doesn´t affect IW. I will ask @Torquemadra about that.

**Comment by Lefze** [comment]
Abilities unaffected by this cooldown reduction effect are as follows:
- Rending Blade
- Da Waaagh! Is Coming
- Shades of Death
- Infernal Wave is affected but will not be reduced to less than 5s if using the tactic Neverending Agony

Heres the snippet you were looking for.

**Comment by sioding** [comment]
Ah ok. Thanks.

**Comment by ragafury** [comment]
just confirmed on live server.
works with the choppa version of chop fasta exclusively.
BO version doesn't work.
It's still a bug however.

**Comment by kalmatar** [comment]
Both CD decreasers from Choppa and Black Orc are capable of reducing IW cd down to 0 sec. Which makes it extremely potent ranged bomb weapon in right hands. 
Just not sure if this is random "bug" or possible ninja-"balancing" by devs done for unknown reasons.

**Comment by sioding** [comment]
![infernal_wave](https://user-images.githubusercontent.com/18517842/52975820-40316c00-33c7-11e9-8d15-5430bbeeb5e3.PNG)

**Comment by Marawo** [comment]
Infernal wave does have a minimum CD of 5 seconds right now. 
Altough when equipped with the tactic Neverending Agony and under the effect of either Choppa or Borc Cooldown reduction abilities the correct cooldown timer is not displayed.
The CD clock doesn't show up after use and leads to cunfusion as to why the ability doesn't trigger.

**Comment by Lefze** [comment]
@sioding Above screenshot is not related, that screenshot stems from someone messing up the ability to the point where it threw an exception. The issue at hand is something completely else, and may or may not be fixed by now judging on the above comment, but I know for a fact that it has been bugged and abused hard in-game for months until now without any mention in patchnotes so would be surprised if it's suddenly fixed.

**Comment by sioding** [comment]
It is fixed now so i can close this one here. Thanks for reminding me on that report @Lefze
