### ISSUE TITLE
WL Pet keeps flames of rhuin even when BW leaves party

### ISSUE THREAD

**Issue by carmine3161** [WarEmu/WarBugs#12436]
Expected behavior and actual behavior: Flames of rhuin vanishes from pet when BW leaves party. Pet is keeping the enchantment.

Steps to reproduce the problem: Have a BW in party use Flames of Rhuin near pet, kick BW from party and pet should still have FoR while you have lost it.

Ye is the name of the pet

Screenshots/Videos or archive.org evidences:
![syebella_025](https://user-images.githubusercontent.com/19709971/46818434-150e8000-cd36-11e8-9331-e2a3844d8534.jpg)![syebella_026](https://user-images.githubusercontent.com/19709971/46818464-29527d00-cd36-11e8-80df-afedac9603a7.jpg)

**Comment by grunbag** [comment]
It has been fixed few patch ago
