### ISSUE TITLE
[WL] blindside

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#12439]
skill should only be able to be fired if you are positione on the rear or the back of the target, but it can be fire even in front of it (skill still stay grey out , but if you press 2 times it get fire out) tested now on my wl.

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format.

**Comment by Tesq** [comment]
steps:

log wl, go towards any mob /player in front of him, press blindside 2 times,--->skill get used....

idk what proof i should give you i just tried it this not need confirmation the skill dont have server side a positional check it's obvious, i tried also choppa positional skill in pve shortly and it's not have this problem on any mob in pve, so for sure it must be a specific skill problem of blindside.

**Comment by sioding** [comment]
Well - a screen or video would be nice to see if maybe a style which needs to stand behind someone is also useable if you stand in front of him. Asking for a proper evidence is not something to annoy you as a reporter of a bug - it is helpful for the team member to check if its really a bug. Now the team member have to reproduce it - which consumes time. Thants OK - but - it would take less time with some better evidences.

**Comment by Tesq** [comment]
as you can see the skill enlight only when youa re on side of rear  no matter teh distance

![selum_001](https://user-images.githubusercontent.com/7527415/46906765-41c6c100-cf09-11e8-9516-6b280ea28794.jpg)

when you mvoe in front part of the enemy line of sight the skill gray out (aka should not be usable)

![selum_002](https://user-images.githubusercontent.com/7527415/46906767-41c6c100-cf09-11e8-9ef4-e2467211e2af.jpg)

this is to show time frame
![selum_003](https://user-images.githubusercontent.com/7527415/46906768-41c6c100-cf09-11e8-9526-6c3498e33474.jpg)

now post 2 AA i do from the front blindside ( 50 dmg as reported in combat log before third auto atatck happen plus other times i used blindside ...

![selum_004](https://user-images.githubusercontent.com/7527415/46906769-425f5780-cf09-11e8-93e3-d8cf701633f6.jpg)

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 20.04.2019

**Comment by sioding** [comment]
Fixed with patch from 27.04.2019
