### ISSUE TITLE
Empire quest Rooting out Corruption can't get into Inn

### ISSUE THREAD

**Issue by huntergregg2** [WarEmu/WarBugs#1243]
For the quest Rooting out Corruption, in Bohsenfels, we are to enter the Inn and speak to Innkeeper Bischof. There was a door that opened, then there was a level to open the door to the Inn, now there are neither so this quest cannot be completed.

**Comment by Reggaewaldo** [comment]
Verified the door not working.

**Comment by Kushido** [comment]
Fixed on dev
