### ISSUE TITLE
[Quest/Trophy] Stuntiez iz fer Stuffin / Dhar Case

### ISSUE THREAD

**Issue by Jaycub** [WarEmu/WarBugs#1244]
After completing the quest "Stuntiez iz fer Stuffin" in mount bloodhorn in order to obtain a trophy I choose the "Dhar Case" (the trophy for sorc my class) and was rewarded with nothing.

http://www.warbits.com/gold-items-4874-Dhar-Case.html

**Comment by Reggaewaldo** [comment]
Looking into this.

**Comment by Evildoor** [comment]
Closing since #1704 has more info about the problem.
