### ISSUE TITLE
[Shaman] Sticky Feetz ability no mastery point scaling

### ISSUE THREAD

**Issue by th3m** [WarEmu/WarBugs#12443]
The recently moved ability of Sticky Feetz in Path of Da Green mastery tree doesn't scale up when adding mastery points on the tree. It stays at level 25 no matter what, for a lvl 40 toon.

The tooltip when you highlight the ability still refers as Path of Mork, so i guess that's the reason why.

**Comment by sioding** [comment]
Thanks for the report. Can you please add your testing screens ?

**Comment by th3m** [comment]
Sure and no problem.

This bug also exists on the ability Geddoff! and on the tactic Nuthin' But Da WAAAGH! too.

Providing the screenshots:
![bug](https://user-images.githubusercontent.com/4617902/46904123-2d260100-cee8-11e8-87b8-ab6e47504a82.jpg)
![bug2](https://user-images.githubusercontent.com/4617902/46904126-31eab500-cee8-11e8-871d-bf9e879b2b6a.jpg)
![bug3](https://user-images.githubusercontent.com/4617902/46904127-34e5a580-cee8-11e8-83ff-48e4f4b9c051.jpg)

**Comment by th3m** [comment]
Just to clarify because i saw the label of the topic, it is not only tooltip the problem.

When you actual cast those abilities, they are being casted at those base levels even if you have spent points on their mastery trees.

That is easy noticeable if you cast Sticky Feetz on an enemy and watch the elemental debuff number.

**Comment by grunbag** [comment]
Issue is fixed already
