### ISSUE TITLE
Portal in Chaos Wastes 

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#12447]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Portal Chaos Gateway at 57410:44783 not working.

When clicking on this portal, it will transport you to a "floating island" above which looks down over Black Vesper. There is up there another portal, which you click to return back down to ground level. This portal on the ground level is now not working.

Steps to reproduce the problem:

Reactivate it to have it working as it was a couple of weeks ago.

Screenshots/Videos or archive.org evidences:

Current state:

![portal bug](https://user-images.githubusercontent.com/22262165/46915356-5e630780-cfa2-11e8-8fdc-4b4b35bde191.png)

![ulralys_174](https://user-images.githubusercontent.com/22262165/46915358-72a70480-cfa2-11e8-98e7-e784630bfce5.jpg)

Previously:

Go through this...
![ulralys_021](https://user-images.githubusercontent.com/22262165/46915362-8d797900-cfa2-11e8-83a1-93c015ba7de6.jpg)

Appear up here here... (you return to ground level by travelling back through this one and emerging at the one on ground level)
![ulralys_023](https://user-images.githubusercontent.com/22262165/46915368-a550fd00-cfa2-11e8-9510-4fd0294209b2.jpg)

**Comment by Lheana** [comment]
Your screenshot clearly says that you can not use the portal because you are in combat.

**Comment by Senthoi** [comment]
You're quite right. Ugh. I'd killed all the mobs and assumed it was safe to go. That'll teach me for bug hunting before coffee. Thanks Lheana.
