### ISSUE TITLE
Goradian the Creator, College steps

### ISSUE THREAD

**Issue by Daedalusmbj** [WarEmu/WarBugs#12449]
For the Quest Goradian the Creator, on the steps Kill Mad Wizards in the Bright College.

only 4 apprentices can be found in the college, all on ground level. None of them become hostile on interact, they just perform a generic voice blurb.

Have tried leaving and re entering the college, leaving and restarting game. nothing helped.

**Comment by Lheana** [comment]
Known issue, we do our best to understand and fix it.

**Comment by MaxHayman** [comment]
@Lheana did I fix this issue?

**Comment by Daedalusmbj** [comment]
Just confirmed ingame. Mad Wizard present and killable. Quest could be advanced and next step started wit taking the book to Felix Jaegar.

Thanks for the fix :)

**Comment by Lheana** [comment]
Yes @MaxHayman on live it works. I have corrected a bit the quest, will be implemented with next patch :)

**Comment by sioding** [comment]
fixed with patch from 05.11.2018
