### ISSUE TITLE
Rough Gunbad Ruby

### ISSUE THREAD

**Issue by edavoc** [WarEmu/WarBugs#12446]
The rough gunbad ruby has less stats then all the other rough gems. 
It has 23 str 12 wounds and 52 to all resists. All the other gems have 28 of a stat 12 of another and 52 resist all.
The ruby is missing 5str when compared to the rest of the gems.

**Comment by edavoc** [comment]
![aedrik_003](https://user-images.githubusercontent.com/16967436/46911225-1224b280-cf23-11e8-95da-e97169567029.jpg)
![aedrik_004](https://user-images.githubusercontent.com/16967436/46911226-1224b280-cf23-11e8-8899-a3cdc54c7dac.jpg)

**Comment by sioding** [comment]
fixed with patch from 27.10.2018
