### ISSUE TITLE
[Zealot] All Zealots dmg abils  - have 25% lower dmg than they sould - looks like not sloted Divine Fury "-25%" your dmg, and sloted - only push it to 100% insead of 125.

### ISSUE THREAD

**Issue by Kweedko** [WarEmu/WarBugs#12445]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Wind of Insanity - do not benefit from tact Divine fury(+25% dmg).  
As you see tool tip dmg 393 and dmg to target is 395 - not near the 494dmg it sould be with the tactic.

Steps to reproduce the problem:

Hit the target calculate dmg.

Screenshots/Videos or archive.org evidences:

![leapingtoad_024](https://user-images.githubusercontent.com/13465031/46907852-93377600-cf32-11e8-9a01-8821f67aa783.jpg)

**Comment by Scophis** [comment]
Did some tests on the target dummies in IC.

WoI benefits from DF...
![woi_1](https://user-images.githubusercontent.com/40274248/46914024-1fc84f80-cf98-11e8-9f51-a2a2d685c897.jpg)

...but the tooltips indeed seem to be off:

(with DF on)
![woi_df_on](https://user-images.githubusercontent.com/40274248/46914034-4090a500-cf98-11e8-8b66-2a0639583865.jpg)

with and without Harbinger, always showing the same damage value
![woi_hod](https://user-images.githubusercontent.com/40274248/46914043-4d14fd80-cf98-11e8-8b54-e62d2477e41f.jpg)


It looks like the tooltip values aren't properly recalcultated for DF and HoD, even /rel doesn't help.

**Comment by Kweedko** [comment]
tool tips on live never included DF buff in calculations. 
According to CareerBuilder - base dmg of WOI is 172 without any points in tree + my 180+ dps from int - is more then 350 raw. - looks like without DF is  -25% with it is -25 and +25 at the same time.

**Comment by Scophis** [comment]
Let's see if I got this right^^ You mean that the base-dmg of a zealot is 25% lower as it should be; but with DF you reach the value you should have without it? Because you negate the missing 25% base-dmg.

**Comment by Kweedko** [comment]
not for all skills i guess(channel, scourge, dot and other looks fine (tooltip dmg + 25% with tact at dummys ), but maybe for some other too.

**Comment by Laurentz18** [comment]
I probably missed this because of all the tooltip and paperdoll inconsistencies. Correct, at live the DF boost didn't show up in tooltip. Here I have gotten into the habit of dropping and restarting Harbinger every time I zone because I'm paranoid it is affecting my damage. But yes the damage feels a bit low. On live with full aoe I was always in the top damage for SCs, but here I am struggling. Frequently outdpsed by single target dps AMs and Shammies now. Even with a good guard and heals allowing me to be in the fight constantly I'm struggling to put out damage.

**Comment by grunbag** [comment]
Fixed at next patch
