### ISSUE TITLE
Can't Leave the Sewers in Altdorf

### ISSUE THREAD

**Issue by Pyrune** [WarEmu/WarBugs#12459]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
After defeating a the lord in the sewer, you should be able to leave and the respective quest should update.

Update 10/17/2018 03:03 EST
I found that if you enter one specific entrance of the sewers you cannot leave. However, all other entrances will allow you to leave.

The party is trapped in the sewers and the quest doesn't update

Steps to reproduce the problem:

Update 10/17/2018 03:03 EST
Follow the map location in the screenshots to problem entrance and attempt to leave

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Any screenshot whith error messages? Are you still in combat?

**Comment by Gideon404** [comment]
Not personally had an issue with sewer quests but the exit portal in the third wing has never worked. There is no error message.

**Comment by Pyrune** [comment]
I am no longer in the area. Until I get a warband together to clear the sewer. Here are screenshots of me trying to exit 2 different entrances. The sewer is not cleared, but I can exit all other areas that I enter (map screenshot included) 
<img width="960" alt="map location of where i can t exit screenshot 2018 10 17 - 02 46 57 54" src="https://user-images.githubusercontent.com/44217833/47067704-41078680-d1b8-11e8-815f-2c66f2187997.png">
![Uploading Error message when
![map location of where i can exit](https://user-images.githubusercontent.com/44217833/47067806-81670480-d1b8-11e8-910b-2a1a8c09963d.png)
 I attempt to exit Screenshot 2018.10.17 - 02.42.46.97.png…]()

**Comment by Pyrune** [comment]
Here is a screenshot of the error message I get when I try to exit after entering the above mentioned entrance.
<img width="960" alt="error message when i attempt to exit screenshot 2018 10 17 - 02 42 46 97" src="https://user-images.githubusercontent.com/44217833/47067991-14a03a00-d1b9-11e8-9e9a-1ac40fa2ba35.png">

**Comment by Pyrune** [comment]
Here a map location that if I enter, I can leave with no issues.

![map location of where i can exit](https://user-images.githubusercontent.com/44217833/47068042-34376280-d1b9-11e8-9175-721f65384047.png)

**Comment by Pyrune** [comment]
> 
> 
> Not personally had an issue with sewer quests but the exit portal in the third wing has never worked. There is no error message.
> 
> I can't remember combat status but the instance was completely clear and this has been probably 4 or 5 runs.

The problem is that if you use that specific entrance, you cannot exit anywhere.

**Comment by grunbag** [comment]
can't reproduce the issue, probably a combat bug
