### ISSUE TITLE
Guards in Destro wc @ Black Fire Bassin

### ISSUE THREAD

**Issue by Sandskid** [WarEmu/WarBugs#12450]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior: guards in destro wc in Black Fire Bassin are not reacting to order players

Steps to reproduce the problem: 

Screenshots/Videos or archive.org evidences: http://funkyimg.com/i/2M6Jj.jpg

**Comment by Lheana** [comment]
I saw them numerous times killing order when they were too close.
