### ISSUE TITLE
White Lion Shred and Lion's Roar

### ISSUE THREAD

**Issue by Roedor78** [WarEmu/WarBugs#12456]
**Expected behavior and actual behavior:**
White Lions Train to Threaten - When "Shred" (armor reduction) is applied on enemy it make 20s debuff. 
This debuff is removed by other debuff "Lion's Roar". I don't know that is only removed on list of enemy debuffs or it removed this completly.

It's confirmed by my friend on his 40lvl WL

**Steps to reproduce the problem:**
...

**Screenshots/Videos or archive.org evidences:**
on screnshot You will see attack of lion and sequences of debuffs:
Roedor_43 - Shred is applied
![roedor_043](https://user-images.githubusercontent.com/44190674/46999152-23d5a800-d125-11e8-9bfb-0ff9be12fcd4.jpg)
Roedor_44 - Leg tear is applied
![roedor_044](https://user-images.githubusercontent.com/44190674/46999190-45369400-d125-11e8-9a9a-1b50f6ae17d1.jpg)
Roedor_45 - Lion's Roar is applied and Shred removed
![roedor_045](https://user-images.githubusercontent.com/44190674/46999167-32bc5a80-d125-11e8-9e27-2bcfb7f959f3.jpg)

**Comment by grunbag** [comment]
i just tested on dev, it seems fixed, closing issue
