### ISSUE TITLE
Scalding Vomit (hex) not cleansable by WP

### ISSUE THREAD

**Issue by Gideon404** [WarEmu/WarBugs#12458]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

The debuff Scalding Vomit (id13074) which a lot of mobs in Gunbad use shows up as a hex.  Warrior Priest cleanse lights up but if you try to cleanse it the ability tries to go on GCD but fails, also fails to cleanse and does not go on CD.  Rune Priest in the group says he has no problems.  Maybe this debuff is not really a hex?

Steps to reproduce the problem:

Get vomited on by the troll boss or certain other mobs in Gunbad.  Spam WP cleanse and fail.  I had the Cleansing Power tactic slotted, if that makes a difference.

Screenshots/Videos or archive.org evidences:

![image](https://user-images.githubusercontent.com/16654707/47048793-50280d80-d193-11e8-80cf-343c53906200.png)

**Comment by sioding** [comment]
fixed with patch from 05.11.2018
