### ISSUE TITLE
[Witch Hunter] Van Horstmanns Speculum

### ISSUE THREAD

**Issue by Godzip** [WarEmu/WarBugs#1245]
"Van Horstmanns Speculum" is a instant cast, but everytime i activate it in combat i get a delay of about 1 - 1,5 seconds on all other skills. Same Problem with "Seal of Destruction".

**Comment by Silentguard** [comment]
You talking about WH\WE 5pts mastery abilities have no gcd, same as SW Vengeance. Would be nice if you find video from live with this. Must be true iirc.

**Comment by Godzip** [comment]
Heres a short clip where you can see the delay. directly after activating "Van Horstmanns Speculum"
i tryed to use "Absolution".
https://www.youtube.com/watch?v=5eGut9vRjjU&feature=youtu.be

**Comment by Silentguard** [comment]
Yes, looks like client dont set gcd but server do.
