### ISSUE TITLE
Channeling Abilities ( BW )

### ISSUE THREAD

**Issue by Shaerazade** [WarEmu/WarBugs#12464]
Hi deer staff, ( South France Player )

i got to report a bug on my BW,

i'll give you a short description to be as clear as possible :)

The BUG is that : if you use a CHANNEL ability (like RoF, FBBarrage or even Whithering Hat ) and if you die BEFORE the cast bar ends ... all these abilities remain active and keep hit / kill ennemies even dead. Feel free to msg me in-game or by mailbox.

PS : guess it's not Duplicate

**Comment by Natherul** [comment]
please provide more information, I was unable to replicate this with a BWs Rain of Fire.

**Comment by Shaerazade** [comment]
BWs FireballBarrage mainly 'End channeling upon Death'

But RoF can 'End channeling upon Death too', less often

Annhilate too, gotta check it on respec

**Comment by Shaerazade** [comment]
i'll try to get descent Combat log, this week

**Comment by Lefze** [comment]
Happens with Hand of Ruin and Shadow knives aswell, which are the two targeted channels of Sorc.
![image](https://user-images.githubusercontent.com/31864442/47272525-5cdba580-d587-11e8-9a2a-9dffcf87a78f.png)

**Comment by Shaerazade** [comment]
tyvm for log screenshot, i can't work on this for now
lot of work IRL

**Comment by Shaerazade** [comment]
i don't know for dessy side / i'm true ordo player and it will take me some day to grind r40 sorc for the tests.
But did u get it on GM side, we are 1 week from Ultimatum. any comments ?
Gotta AFK 3 days more, i'll check this on my return Asap.
I'll try to get more log for max of skill ( i mean annhilate and the Sorcerer spell mirror )

**Comment by Shaerazade** [comment]
![fbb](https://user-images.githubusercontent.com/44240445/47575881-66785b00-d943-11e8-89ea-fb3f5c31bc00.jpg)

FBB here

**Comment by Shaerazade** [comment]
Can't reproduce RoF and annhilate / Zone damage spell abilities.. for now.

**Comment by sioding** [comment]
ok - so i close this now. Thanks for the report.
