### ISSUE TITLE
Abilities Above Max Level in Altdorf Sewer

### ISSUE THREAD

**Issue by Pyrune** [WarEmu/WarBugs#12460]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
The lair maxes out at level 17 and all abilities gained above that level should be prevented from use.

Abilities gained above level 17 can be used in the sewer. The GUI states that the ability cannot be used, but the ability can be used and does damage. I was able to use all abilities, except for mount, without restriction

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Can you please add screenshots with your tests?

**Comment by Pyrune** [comment]
Both images show the use of abilities that are obtained above the level cap of the lair.
<img width="960" alt="war-64 screenshot 2018 10 17 - 02 43 11 68" src="https://user-images.githubusercontent.com/44217833/47068260-cc354c00-d1b9-11e8-91d4-9beaf9e909c5.png">
<img width="960" alt="war-64 screenshot 2018 10 17 - 02 43 18 89" src="https://user-images.githubusercontent.com/44217833/47068263-cdff0f80-d1b9-11e8-939e-c5ae25834991.png">

**Comment by Natherul** [comment]
should be fixed with the next patch, if not its a database issue :D

**Comment by sioding** [comment]
fixwed with patch from 21/10/2018
