### ISSUE TITLE
Quest - Corruption of desire.  stages slightly bugged

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#12461]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
I noticed this quest seemed to show incorrect quest indicators (above NPC head) during one stage.
The screenshot shows the quest giver marked as quest completed.

Steps to reproduce the problem:
quest taker corruption of desire from Friedrich Haelund in Empire Ch.6.

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/7898608/47058132-8310d800-d178-11e8-9e81-f33147d8416e.png)
https://ibb.co/jB0DFf

**Comment by sioding** [comment]
Thats a known problem - i guess you have to talk toFriedrich Haelung after talking to Hogar Putnam. Nothing we can fix now - sorry - but thanks for the report.

**Comment by gittoaster** [comment]
Curious as to why there is nothing you can do?  I thought we were past those dark days.
