### ISSUE TITLE
Sigmar's Call Should not have a 30 Day Decay

### ISSUE THREAD

**Issue by Luuca** [WarEmu/WarBugs#12465]
**Expected behavior and actual behavior:**
Sigmar's Call, the quest reward item, did not have a decay timer previously. It does now. 

I had previously earned the item on 3 characters. These three characters version of Sigmar's Call did not have a decay timer. After earning the item on my runepriest, I noticed (on or about 10-12-2018) that the item(s) for all my characters now had a 30 day decay timer. On my runepriest, I have used the item and it is counting down from 30 days. On other characters, I have not used the item and it still shows a 30 day decay, but is not counting down. I had previously used the item on the other characters. This tells me that at some point, the item was "reset" or changed and the decay timer was added. 

**Steps to reproduce the problem:**
Do the Quest and get the item. Do not use the item and see that the timer is there, but not actively decaying. Use the item and see that the decay timer starts. 

**Screenshots/Videos or archive.org evidences:**
Available upon request.

**Comment by Scophis** [comment]
Seems to work as intended as in patchmotes of 01.09.2018 : 
[Items]
Lheana
- Sigmar's Call and Viper's Return will now expire after 30 days and have a cooldown of 2h.

https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=28163&p=319733&hilit=viper#p319733

**Comment by Lheana** [comment]
This is intended. If one of your characters had the item before I set the expiration, then yes I know it does not expire, but these items are meant to expire.
