### ISSUE TITLE
WE Kisses (the buff) removed after each sc.

### ISSUE THREAD

**Issue by loodit** [WarEmu/WarBugs#12477]
TItle. Gotta reapply the kisses after each sc or inside sc. 
Since todays patch.

**Comment by Kweedko** [comment]
And Z marks, after every res in WC. This is beyond the comfortable play.

**Comment by sioding** [comment]
Thanks for the information. Please refrain from any personal feelings in a bugreport. Only the facts are important here. If you want to discuss how annoying it is or whats needed for a confortable play - please use the forum. Thats why i edited both comments.

**Comment by Natherul** [comment]
if you are bolstered this is intended behaviour. We cancel any buffs that are stranger then your level when you exit bolster.
