### ISSUE TITLE
/roll showing different numbers

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#12475]
I apologise if this has already been reported, but me and my party decided to do a /roll 100 for loot and we all saw different numbers for everyone.

Expected behavior and actual behavior:
we should all see the same numbers for the rolls, but we all see different rolled numbers

Steps to reproduce the problem:
have someone /roll 100 and see that you got different numbers

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Thanks for the report. Can you add screenshots from two persons to this report?

**Comment by Rockalypse** [comment]
Don't know if this is needed, but yes, we as RP guild encounter it all the time, so we have to roll and than PM results to eachother.

**Comment by MaxHayman** [comment]
Weird.

**Comment by sioding** [comment]
fixed with patch from 05.11.2018

**Comment by sioding** [comment]
fixed with patch from 05.11.2018
