### ISSUE TITLE
tracer round +15% crit engineer tactic not working anymore

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#12478]
The tactic isn't working anymore. Crit should be 29+15% = 44%
![thorbolt_487](https://user-images.githubusercontent.com/16274785/47278645-d8ab1180-d5ca-11e8-9de1-3ca6c194ff91.jpg)

**Comment by thorbolt80** [comment]
The issue seems fixed very weird. he does not show stats on .getstats.

**Comment by thorbolt80** [comment]
Same problem back tracer round should give in my build 25% + 15% = 40%
![Thorbolt_792](https://user-images.githubusercontent.com/16274785/54265265-325da980-4575-11e9-830d-f9b3a76dbfc8.jpg)

**Comment by grunbag** [comment]
it's not showing in get stats but the tactic works i just set it to 100% crit rate instead of 15% and i did crit on all attack.

**Comment by grunbag** [comment]
![crit](https://user-images.githubusercontent.com/24207191/54274960-b3bf3700-4589-11e9-955f-1a5f2ac4adb4.png)

**Comment by sioding** [comment]
Answer given - close
