### ISSUE TITLE
[Slayer] influence raward DvsG

### ISSUE THREAD

**Issue by knezekj** [WarEmu/WarBugs#1247]
Hallo, I have made dwarven vs Greenskins t2, chapter 9, PQ. And i choose this weapon:
![snorrri_005](https://cloud.githubusercontent.com/assets/13565283/9601774/19e83c5e-50a4-11e5-88b6-27d902f06a2c.jpg)

And how you can see no icon and hotbar not functional like without weapon. 
Thank you for answer and sorry for my bad english.

**Comment by DanaBloodkiss** [comment]
Fixed.
