### ISSUE TITLE
Quest: I Spy. Talabec. 

### ISSUE THREAD

**Issue by SODIX** [WarEmu/WarBugs#12471]
After that you return to questgiver Cecania, she can't finish quest because of WAR says you have no place in inventory, while you could have it.

Screenshots/Videos or archive.org evidences:
https://i.imgur.com/q9iBnOl.jpg

**Comment by Lheana** [comment]
Have you verified all your inventories?

**Comment by SODIX** [comment]
Yes, I did. She gives only one item, and I have a slot.

**Comment by Lheana** [comment]
Maybe you need more than 1 slot?

**Comment by SODIX** [comment]
No, it also tells: Unable to disassemble the item. It's a bug, INFA95%.

**Comment by Lheana** [comment]
Tried, had no issue.

**Comment by SODIX** [comment]
It's not a only THIS quest bug, but affect whole system if you have no empty place in inventory while close quest. Then you should relog, and everything will be OK. So closed.
