### ISSUE TITLE
Repeatable quest marker missing

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#12481]
the blue marker above npcs is not shown anymore ; instead the normal marker (green one) is displayed.
![gelindo_021](https://user-images.githubusercontent.com/17765890/47306372-869ad800-d62c-11e8-9c70-5a7732ff9f9c.jpg)

**Comment by MaxHayman** [comment]
Does the quest giver have a normal quest to give out too?

**Comment by zak68** [comment]
no

**Comment by zak68** [comment]
those two are both rvr repeteable quests: keep capture and player kills.
![immagine](https://user-images.githubusercontent.com/17765890/47403206-e4bcdd80-d748-11e8-8623-f03e66360593.png)

**Comment by zak68** [comment]
have to wait a reboot? 


Da: "Max Hayman" <notifications@github.com> 
A: "WarEmu/WarBugs" <WarBugs@noreply.github.com> 
Cc: "zak68" <bel0919@iperbole.bologna.it>, "Author" <author@noreply.github.com> 
Inviato: Sabato, 10 novembre 2018 13:25:15 
Oggetto: Re: [WarEmu/WarBugs] Repeatable quest marker missing (#12481) 



[ https://user-images.githubusercontent.com/1018809/48301296-a0209880-e4e3-11e8-90a0-afeb077853f9.png ] 
This should be right.

**Comment by MaxHayman** [comment]
It will be in on todays patch.

**Comment by sioding** [comment]
fixed with patch from 17.11.2018
