### ISSUE TITLE
Sewer Search: Master Moulder Vitchek

### ISSUE THREAD

**Issue by Luuca** [WarEmu/WarBugs#12487]
**Expected behavior and actual behavior:** I would expect the sonofabitch to actually be inside the instance, but twice now, he has not been. 

**Steps to reproduce the problem:** Run the instance. 

**Screenshots/Videos or archive.org evidences:** nope

**Comment by sioding** [comment]
Well ... i can see him:

![image](https://user-images.githubusercontent.com/18517842/47418275-19955880-d77a-11e8-9e77-42a8e3652dca.png)
