### ISSUE TITLE
Divine assault dont heal it what should on defensive target in keep bosses.

### ISSUE THREAD

**Issue by rieymdiele** [WarEmu/WarBugs#12489]
hello!!
Few days ago i check that my divine assaulT dont heals what it should on keeps trying to heal mates, not myself. i tough that were for battle debuffs or similar. but chekcing every day and diferent bosses and no battle debuffs, Divine assault heals aprox. a 30 % about dmg dealt to boss ,healing a mate instead the 350% dmg dealt what it should.
wating for news

a greeting and more more more hours of fun!!

Olakease 
WP R40 RR51

**Comment by sioding** [comment]
Thanks for the report. Please attach your testing screenshots.

**Comment by rieymdiele** [comment]
i dont get any screens now but will try to get some in the next siege

greetings!

**Comment by sioding** [comment]
maybe related to #12078

**Comment by Kweedko** [comment]
it's the same issue like with Z transference.

**Comment by rieymdiele** [comment]
![olakease_009](https://user-images.githubusercontent.com/44442347/47467501-e349ee80-d7f6-11e8-9193-b068e8355f83.jpg)
![olakease_012](https://user-images.githubusercontent.com/44442347/47467502-e3e28500-d7f6-11e8-9caf-6d92c1a1ffd9.jpg)
hello here the screenshots of issues about divine assault. not only fails healing and ally. fails too thealing myself

greetings!!

**Comment by sioding** [comment]
ok thanks for screens - put it together with #12078
