### ISSUE TITLE
Chosen tactic bug

### ISSUE THREAD

**Issue by DUSKANGEL** [WarEmu/WarBugs#1248]
I submit 2 jpeg files here with bug to check if its work properly need to do number of attacks and check how many critical hits enemy did to the chosen.  
![new bitmap image](https://cloud.githubusercontent.com/assets/12202629/9602462/6b476cb6-50b1-11e5-8b74-8566fd62544d.jpg)
![new bitmap image 2](https://cloud.githubusercontent.com/assets/12202629/9602478/8a1eccce-50b1-11e5-81c2-eea0a6ab52cf.jpg)

**Comment by ozarmidrashim** [comment]
Display issue.

**Comment by Evildoor** [comment]
https://github.com/WarEmu/WarBugs/issues/1182
