### ISSUE TITLE
Alliance Info missing some parts

### ISSUE THREAD

**Issue by exotlv** [WarEmu/WarBugs#12480]
Missing: List of Guilds
Missing: Name of Guild Leader

Expected behavior and actual behavior:
List of Guilds is shown and Guild Leader nicknames as well.

Steps to reproduce the problem:
Open Guild, Open Alliance Tab.

Screenshots/Videos or archive.org evidences:

![image](https://user-images.githubusercontent.com/8436809/47297721-9d3a3280-d61e-11e8-84e5-384db7c4ed3d.png)

**Comment by MaxHayman** [comment]
@exotlv This should be fixed. Can you confirm?

**Comment by exotlv** [comment]
@MaxHayman  confirm. It's fixed. 
Checked on my account: Erihon.

**Comment by MaxHayman** [comment]
Great!
