### ISSUE TITLE
[WH] new ability, Hammer of Faith

### ISSUE THREAD

**Issue by XmatXergon** [WarEmu/WarBugs#12482]
Expected behavior and actual behavior:
New ability appear w/o information in patch notes.

Steps to reproduce the problem:
Hard to say, only common thing i found out is that other WH with RR 80+ got this ability aswell.

Screenshots/Videos or archive.org evidences:
![wh new ability](https://user-images.githubusercontent.com/37849311/47306653-5142ba00-d62d-11e8-802a-ca991f1c68d1.png)

https://plays.tv/video/5bcd3512211a9da5ed

**Comment by grunbag** [comment]
It has been removed I think ?

**Comment by grunbag** [comment]
It was a test and has been removed
