### ISSUE TITLE
Magus Moral 4 doens't reset points

### ISSUE THREAD

**Issue by Mazzacane** [WarEmu/WarBugs#12488]
I found today that on my Magus moral 4 "firewyrm of Tzeentch" can be used without using moral points. I tryed using it and after moral 3 "Scintillating Energy". Both worked.
Regards,

Mazzacane

**Comment by sioding** [comment]
I can not reproduce it - are you sure the server was in a stable situation when this seems to work? No lags/other problems? If we are not able to reproduce the problem we can not fix it.

**Comment by Mazzacane** [comment]
I try again in few minutes and i'll tell you

⁣Prima di stampare questa e-mail, pensa all'ambiente ** Please consider the environment before printing this e-mail.

Marco Cerretani
Via Aurelia Nord 36, Braccagni
58100 Grosseto, Italy
Tel. 331/1244013
  
Ai sensi del DLGS 196/2003 e sue successive modifiche e integrazioni, si precisa che il presente messaggio e tutti i suoi allegati, sono riservati a uso esclusivo del destinatario. E' pertanto vietata la copia, la diffusione e la rivelazione, anche parziale, delle informazioni contenute a persone
non autorizzate dallo stesso destinatario. Chi ricevesse per errore questo messaggio o ne venisse in possesso senza esplicito consenso da parte del destinatario , è pregato di restituirlo al mittente e di provvedere all' immediata cancellazione di tutto il contenuto compresi gli eventuali allegati.

Inviato da BlueMail ​

Il giorno 24 Ott 2018, 10:36, alle ore 10:36, Sio <notifications@github.com> ha scritto:

**Comment by Mazzacane** [comment]
K just tryed now in ic on target dummies. Charged until m4 the fired both 4 and 3 in sequence

⁣Prima di stampare questa e-mail, pensa all'ambiente ** Please consider the environment before printing this e-mail.

Marco Cerretani
Via Aurelia Nord 36, Braccagni
58100 Grosseto, Italy
Tel. 331/1244013
  
Ai sensi del DLGS 196/2003 e sue successive modifiche e integrazioni, si precisa che il presente messaggio e tutti i suoi allegati, sono riservati a uso esclusivo del destinatario. E' pertanto vietata la copia, la diffusione e la rivelazione, anche parziale, delle informazioni contenute a persone
non autorizzate dallo stesso destinatario. Chi ricevesse per errore questo messaggio o ne venisse in possesso senza esplicito consenso da parte del destinatario , è pregato di restituirlo al mittente e di provvedere all' immediata cancellazione di tutto il contenuto compresi gli eventuali allegati.

Inviato da BlueMail ​

Il giorno 24 Ott 2018, 10:36, alle ore 10:36, Sio <notifications@github.com> ha scritto:

**Comment by sioding** [comment]
Sorry - but you can not fire a M4 thats not implemented yet. Double checked - and close.

**Comment by sioding** [comment]
*removed personal data thanks @zak68
