### ISSUE TITLE
[Quest] The Sewers of Altdorf

### ISSUE THREAD

**Issue by tog89** [WarEmu/WarBugs#12493]
Expected behavior and actual behavior:
Turn in quest with target NPC Rhanz Folner.  Cannot turn in quest with NPC and quest text has error in the ToK entry:

Invalid NPC - 
50432,ObjId=86374

Steps to reproduce the problem:
![tog_050](https://user-images.githubusercontent.com/38359697/47479538-1db18c80-d7f3-11e8-8956-420d26816a67.jpg)

Screenshots/Videos or archive.org evidences:

**Comment by Lheana** [comment]
Hm checked, everything is fine.
![lheanaa_000](https://user-images.githubusercontent.com/11537611/47517254-eb05a380-d887-11e8-9323-d94791269b72.jpg)

Maybe you should abandon the quest and retake it.
