### ISSUE TITLE
[RP] Rune of Nullification doesn't work on Rune of Cleaving, Rune of Warding

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#12496]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
The Tactic Rune of Nullification is a Tactic to put a Healdebuff on an target if it is hit with a critical hit.
https://ror-career-builder.herokuapp.com/career/rune-priest/s?l=40&r=40&tl=4&mp=14&pA=11&pB=0&pC=0&m1=false&m2=false&m3=false&m4=false&ma=&mm=&mt=3872&t=

Idea is to build a RP with a lot of Magical Crit to put it on your opponents.
Although at the moment the Healdebuff doesnt work on Dot Attacks it seems like Rune of Cleaving, Rune of Warding (Granted Ability form Oathrune of Warding)

Steps to reproduce the problem:
Get the tactic, hit targets with tactic and Rune of Cleaving that you dont target to not interfer with your auto attacks.

Screenshots/Videos or archive.org evidences:
![balin_160](https://user-images.githubusercontent.com/14627932/47533364-b60f4600-d8b3-11e8-85ba-c511ce7f309c.jpg)
Explanation:
The Goblin is hit with 361 Critical Magical Damage and should get the Healdebuff.

![balin_161](https://user-images.githubusercontent.com/14627932/47533439-01295900-d8b4-11e8-803f-b1023c78baea.jpg)
In this Screen the Healdbuff is applied with a critical Hit on Rune of Might. Which is an instant AoE Attack.

With Rune of Nullification not working on Rune of Cleaving and Rune of Battle not getting an increased Range from Extended Battle Tactic: https://github.com/WarEmu/WarBugs/issues/11546
The Aoe Healdebuff RP is currently broken.

**Comment by sioding** [comment]
Take a look at this #11285.
It is working as intended.
