### ISSUE TITLE
Archmage ability: funnel essence broken

### ISSUE THREAD

**Issue by rekkir** [WarEmu/WarBugs#12498]
**Expected behavior and actual behavior:**

Expected my target to be healed by somewhat close to tooltip values but he was not healed at all. 

I know Aza buffed the ability by increasing the healing by 100%, then this was probably removed in shadow and broke the ability.

Funnel essence now only work with yourself(the caster) as the target.

**Steps to reproduce the problem:**

Easy to reproduce, target someone and try to heal them.

**Comment by sioding** [comment]
Thanks for the trport. Please add your testing screenshots.

**Comment by sioding** [comment]
No testing screenshots since 13 days. Close.
