### ISSUE TITLE
Flasfire tactic

### ISSUE THREAD

**Issue by Shaerazade** [WarEmu/WarBugs#12508]
Hi all Dev-team,
 i'm south French player, live player.
 i noticed some fixes on 'Flashfire tactic' u made already but.. did u really expect 'BW to cast while moving' ?
 i noticed recently that when Flashfire procs => Build-time is reduced by 50% instead of tooltip => instant cast

Steps to reproduce the problem:

 But the point is that ' While Flashfire Tactic Proc Buff 'i can 'cast while Moving', i checked forum and chit-chat post but can't find any related talks so here i post a report
know if it is attempted or smallfixes classed fact, or correct report to improve the Project.
 it will be very hard to screen it, vidéo sound better but i lack skills/tools for that.

Screenshots/Videos or archive.org evidences:
'On work'

 Tyvm for answer et matter on the post.

**Comment by sioding** [comment]
Hey - thanks for the report - but yes flashfire is working as intended. Please check the official wiki for such questions: https://wiki.returnofreckoning.com/index.php/Bright_Wizard#Class_Changes

**Comment by Shaerazade** [comment]
ok tyvm,

feel free to block/delete post

PS : i posted by mistake into ' Code report bug too ' < delete it please
