### ISSUE TITLE
AP regen turned off AP @ zero after halloween event quest...

### ISSUE THREAD

**Issue by jundii** [WarEmu/WarBugs#12506]
_Expected behavior // actual behavior:_

Regeneration of ap // not regen ap.... to do any action // no action 

_Steps to reproduce the problem:_

Basic solo zealot play in scenarios

_Screenshots/Videos or archive.org evidences:_

My screen shots did not go into folder, I can't find them.

**Comment by jundii** [comment]
Basically I zoned into the sc (Khaine's Embrace) and buffed (btw still need to buff after EVERY zone change still). I ran to first BO about noticed I had about 37 AP on my zealot and no regen. The animation for flash heal was going off, but nothing was happening. I couldn't auto-attack ppl at flag. I couldnt mount.  I took multiple screenshots (saw the text tht I did so). Nothing.

**Comment by sioding** [comment]
Tried to reproduce that but no chance for that. Is this still a problem?

**Comment by sioding** [comment]
No answer since 29th of october. Close
