### ISSUE TITLE
Alternative appearance missing.

### ISSUE THREAD

**Issue by Tholkienn** [WarEmu/WarBugs#12507]
Expected behavior and actual behavior:

This hammer, Apostle's Battlehammer of Rigor , for wp, probably the T3 sc one, can't be aplicate as an alternative appearance.

Seems to have one like all others weapons of sc.

Steps to reproduce the problem: Try to applicate it as appearance.

Screenshots/Videos or archive.org evidences:
![aniomed_178](https://user-images.githubusercontent.com/13720388/47612904-adba3500-da84-11e8-9d92-3d88aea38d8f.jpg)

**Comment by Rubyeclipse-war** [comment]
@Tholkienn Thanks for flagging this. It's been many years since this ticket was opened, but after some testing it looks like this item can properly have alternate appearances applied, so this ticket should be complete! Closing it now.
