### ISSUE TITLE
LotD , Instadeath bug

### ISSUE THREAD

**Issue by backinwar** [WarEmu/WarBugs#12502]
Hello ,
When on the quest "The Ritual" (part of the Zombocalypse event), i fell into what appears a acid pool, a small distance from the quest marker. A message in my chat said " You have managed to trigger the instadeath code from the river mortis, please screenshot your death and send to the devs on the bugtracker.
There are now rewards in Land of the Dead"
I've included my screenshot. Hope it helps.

![mephiroth_002](https://user-images.githubusercontent.com/14232512/47605446-42824b80-da0f-11e8-9114-1fc22054c991.jpg)

![mephiroth_003](https://user-images.githubusercontent.com/14232512/47605451-4dd57700-da0f-11e8-89fb-901d38a09f4b.jpg)

**Comment by sioding** [comment]
Thanks - but .... #12501
