### ISSUE TITLE
Halloween Quest-Row (Time Is Of The Essence+) No Quest Marker for Witch Elf

### ISSUE THREAD

**Issue by Zaccar20** [WarEmu/WarBugs#12514]
Greetings,
i got some very crazy bug with my Witch Elf (Aeedys, lvl40 rr51)

**Expected behavior and actual behavior:**
If you take the quest "Time Is Of The Essence" and following ones you should get transform into
a zombie and looking for the Candys with the quest tracker on the map.

_What happend on my Witch Elf:_
If i take the quest "Time Is Of The Essence" and following ones i get transform into
a zombie and looking for the Candys but theres not a single questmarker on the map!

I try to /reload , take the quest again and relog mulitble times but its dont chance somethink.
Also i dont useing any other map markers at same time.
And i can not click the "Show on Map"-Button.

**Steps to reproduce the problem:**
Create a Witch Elf and try if. Maybe its just me maybe its for all WE the same.

On my Zealot or DoK this quest work fine. So i guess its a Class issuse.

Screenshots/Videos or archive.org evidences:

![aeedys_000](https://user-images.githubusercontent.com/12786673/47710953-565ac700-dc34-11e8-8ffd-87bbe7e1ef61.jpg)

![aeedys_001](https://user-images.githubusercontent.com/12786673/47710981-670b3d00-dc34-11e8-884f-f4d5531af80a.jpg)

![aeedys_002](https://user-images.githubusercontent.com/12786673/47710985-6b375a80-dc34-11e8-87bf-1847a24b98f9.jpg)

**Comment by Lheana** [comment]
Activate the first square on your map next to the name of the quest.

**Comment by Zaccar20** [comment]
Can not do that,
its always auto unactivate themself

**Comment by Lheana** [comment]
Open your Tome of Knowledge -> Quests -> Click on the name of the quest -> Activate Mark on Map.
If it still auto desactivates, then search for a quest that has Mark on Map activated, desactivate it, then retry to activate for Time is off the Essence.

**Comment by Zaccar20** [comment]
Work now.
Thank you! =)
