### ISSUE TITLE
Crashing to Login / Unplayable

### ISSUE THREAD

**Issue by SuchaNiceboy** [WarEmu/WarBugs#12512]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

I just downloaded game and created a character (Chosen). I get to play for about 15 minutes when game crashes. After the first crash, now whenever I zone into the world from character screen the game crashes out to login screen within 1 minute. 

Steps to reproduce the problem:
Login into game. Select character. Enter world. Game crashes.

Screenshots/Videos or archive.org evidences:
Due to nature of crash there is nothing to show. There is no pop up window.

**Comment by SuchaNiceboy** [comment]
I replaced the audio file and now it doesn't crash.

**Comment by sioding** [comment]
Thanks for the Information. So case is closed - and yes - we know the problem with the audio file. Sorry for that - a new downloadable version is already in planning.

**Comment by bwroussel** [comment]
@SuchaNiceboy, Did you just re-download the whole game, or is there somewhere to just get the audio file? I am having the same issue.

**Comment by SuchaNiceboy** [comment]
No, i just replaced the audio file. You can find the audio.mpv file on the
forum message boards. Simply download it from the link shared and then
paste into the folder and it will replace it.

Fixed my issue, haven't crashed since.
