### ISSUE TITLE
Squigherder T2 Chaos RvR Inf advanced reward jewel have wrong stats.

### ISSUE THREAD

**Issue by AlistaireCrowley** [WarEmu/WarBugs#1251]
As stated above. The 2nd jewel choise is have wounds when it shoudl have ballistic. Attached a screenshot. There should be 12 Ballistic

Best regards

![oddjobb_005](https://cloud.githubusercontent.com/assets/10405430/9608080/d99cd906-50cc-11e5-8ab9-16019ffc5d5a.jpg)

**Comment by milosxe** [comment]
Issue has been fixed.
![shiz_000_cr](https://cloud.githubusercontent.com/assets/13332067/9975787/73bb83ca-5ec9-11e5-8d80-58bcfd6044fd.jpg)
