### ISSUE TITLE
"Where things go worse" quest the spider biscuits is bugged cant be picked up.

### ISSUE THREAD

**Issue by yusett** [WarEmu/WarBugs#12515]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Lheana** [comment]
Order or destro side?

**Comment by Lheana** [comment]
No answer, and event is finished, so closing the ticket.
