### ISSUE TITLE
stuck as chicken in Nordland (order)

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#12517]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
have been stuck as a chicken in Nordland in PvE area.  ---
It seems chickening code is acting like zombie code?

Steps to reproduce the problem:
I'm not sure.  I just logged in when near Nordland crypts area and have been stuck ever since.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
What means "stuck" - you can not move or teleport?

**Comment by gittoaster** [comment]
Stuck meant 
-after death respawned as chicken
-after shutdown and relogging (full program close) login as chicken

I ran as chicken all the way to Grimmenhagen(starter areas) to Arnholdts flight master and ported to another zone fixed it.

**Comment by sioding** [comment]
Duplicate of #10794
