### ISSUE TITLE
Quest: Morr's Bane

### ISSUE THREAD

**Issue by playys** [WarEmu/WarBugs#12516]
**Expected behavior and actual behavior:**
Expected: Killing 3 Risen Trader mobs would complete the requirements for the quest.
Actual: Killing Risen Trader mobs doesn't count towards the quest progress. 

**Steps to reproduce the problem:**

1. Accept the quest Morr's Bane at ~(37000,37215) in Altdorf. 
1. Try to complete it by killing Risen Trader mobs nearby.

**Note:**
Not sure if related to #2311, as it's the same quest name but the requirements are different.

**Screenshots/Videos or archive.org evidences:**
![morr_bug_1](https://user-images.githubusercontent.com/44623739/47756777-622da400-dc9b-11e8-9ef2-7d0a324d5b86.png)
![morr_bug_2](https://user-images.githubusercontent.com/44623739/47756779-65289480-dc9b-11e8-8a09-84eecd43ff69.png)

**Comment by Lheana** [comment]
This belongs to the same quest chain, but it's not the same quest.

**Comment by playys** [comment]
@Lheana, can't repro this today after server restart. I'm thinking my char might've been "stucked" in warband status even though I was not grouped while I was doing this yesterday.

**Comment by boss21** [comment]
Not getting credit for killing risen traders

**Comment by Lheana** [comment]
Were you grouped when you tried?
