### ISSUE TITLE
[quest] ebon flame

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#12518]
something strange occurred at step 6 
"STEP 6
Kill some mobs at 35.7k/62.7k.
    Kill Indhrian Wolfmoon
    Kill Iriorl Wolfmoon
    Click on the Song of Years in the Tower's underground.
Return to Telethir Bloodbrow." 
i roamed that damn tower several times, killing all mobs and clicking every clickable item and the 2 npcs and the book were not here. 
tried after relogging, after completing that pq just outside that cursed tower and nothing changed: no wolfmoon guys and no book.
only after being grouped with a dok (ty Evilelleii) i was able to complete that step since npcs and book popped up; wiki doesn't mention any group prerequisite, i don't know what i could have done wrong.

**Comment by sioding** [comment]
Tried it on my own and can not reproduce that.

**Comment by zak68** [comment]
ccould you place me back to step 5 ?

**Comment by Lheana** [comment]
No it's not possible.
Maybe you had to leave and come back to the PQ several times to trigger it (may happen).

**Comment by zak68** [comment]
thank you for this information.

**Comment by Lheana** [comment]
There is no problem with these NPCs, I just checked and they are where they are meant to be. 
![Anaehll_431](https://user-images.githubusercontent.com/11537611/63853592-67cb4780-c99b-11e9-99d1-a29f7cb39dbd.jpg)

Moreover, they are not related to the PQ, so completing or not the PQ won't change the fact that they are here or not.
Only thing I can tell you is search harder.

**Comment by zak68** [comment]
As a lone tank i feel your pain.

**Comment by Austherus** [comment]
> There is no problem with these NPCs, I just checked and they are where they are meant to be.
> 
> Moreover, they are not related to the PQ, so completing or not the PQ won't change the fact that they are here or not.
> Only thing I can tell you is search harder.

I'll 

> There is no problem with these NPCs, I just checked and they are where they are meant to be.
> 
> Moreover, they are not related to the PQ, so completing or not the PQ won't change the fact that they are here or not.
> Only thing I can tell you is search harder.

Thanks for the screenshot, I'll check again with a friend once she's of high enough level.
