### ISSUE TITLE
[double spawn NPC] Grimmenhagen Farmer

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#12522]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Double spawns of Grimmenhagen Farmer

Steps to reproduce the problem:
Nordland 28k 49k

Screenshots/Videos or archive.org evidences:
https://ibb.co/kqLOF0

**Comment by Lheana** [comment]
Due to the script for a quest, but the quest has been disabled.
