### ISSUE TITLE
Gunbad Influence Reward, Warrior Priest wrong stats

### ISSUE THREAD

**Issue by lilimx** [WarEmu/WarBugs#12528]
Expected behavior and actual behavior:
The third influence rewards for Warrior Priest has intelligence stats.

Screenshots/Videos or archive.org evidences:
![wp_cassock](https://user-images.githubusercontent.com/23266079/47875496-fbcd9080-de16-11e8-8506-ef07aef95941.jpg)
![wp_helm](https://user-images.githubusercontent.com/23266079/47875503-fec88100-de16-11e8-9524-96f1e55bc134.jpg)

**Comment by sioding** [comment]
Thanks for the report. Fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 05.11.2018
