### ISSUE TITLE
[Engineer] Turret Self-Destruct ain't workin

### ISSUE THREAD

**Issue by Halhammer** [WarEmu/WarBugs#1252]

**Comment by Evildoor** [comment]
Is there any special conditions? After some tests i've managed to find only one - the ability does nothing if you are not in combat (tested on non-aggressive mobs).

**Comment by Evildoor** [comment]
This is pretty much the same as https://github.com/WarEmu/WarBugs/issues/1256, so i'm closing this one since 1256 has more information and Azarael self-assigned himself to it. Will change the name  of 1256 to include Engi's ability as well.
