### ISSUE TITLE
quest xp

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#12520]
seems that has not been reported yet (i haven't been able to find a similar entry) ... 
it's only a visual bug
at the quest giver
![immagine](https://user-images.githubusercontent.com/17765890/47769796-68447480-dcdd-11e8-88bd-5240a867b386.png)
at the quest finisher
![immagine](https://user-images.githubusercontent.com/17765890/47769844-9033d800-dcdd-11e8-8af4-caaed905ba74.png)
real outcome
![immagine](https://user-images.githubusercontent.com/17765890/47769873-a6419880-dcdd-11e8-8808-6909c77fb32d.png)

**Comment by Natherul** [comment]
Known issue and something we are discussing internally on how we should proceed with it.
