### ISSUE TITLE
T3 to T2 portal in Dwarf dont working

### ISSUE THREAD

**Issue by Oldneko** [WarEmu/WarBugs#12536]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
The Portal of T3 Badland to T2 MoM cant use (no replay)

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![fucq_011](https://user-images.githubusercontent.com/43213086/47950656-72de6280-df98-11e8-8103-431fb9c5f77f.jpg)

**Comment by Lheana** [comment]
Works fine, you should try again, and verify you aren't in combat.

**Comment by sioding** [comment]
No answer since 3rd of november. Close
