### ISSUE TITLE
[Engineer] Tracer Rounds tactic not working

### ISSUE THREAD

**Issue by GK111** [WarEmu/WarBugs#12534]
> Tactic 'Tracer Rounds' will should increase your chance to critically hit by 15%

tactic doesn't give any bonus

here proof:

![1245780770](https://user-images.githubusercontent.com/24727277/47950394-a900ef80-df62-11e8-9964-02bc6d8106c6.png)

**Comment by globalgame** [comment]
ozarmidrashim commented on 30 Nov 2015
This tactic is implemented differently than normal and will not show in getstats.

i tested in duel with mara ...
Mara had 0% chance to be critically hit i had from tracer rounds 15% crit chace only and NO CRIT HITS AT ALL !! so i can say tracer rounds broken or its useless tactic .... pls fix it

screens above

**Comment by GK111** [comment]
> 

> i tested in duel with mara ...
> Mara had 0% chance to be critically hit i had from tracer rounds 15% crit chace only and NO CRIT HITS AT ALL !! so i can say tracer rounds broken or its useless tactic .... pls fix it
> 
> Tests made due to the fact that in gameplay time , when I used this tactic, I did not see an increase the frequency of critical hits
> 
> screens above
> 
> https://officialrorbuilder.herokuapp.com/career/engineer/s?l=40&r=40&tl=4&mp=14&pA=0&pB=0&pC=11&m1=false&m2=false&m3=false&m4=false&ma=&mm=&mt=3678&t=
> 
> another one old issue
> #4836
> #2050
> 
> ozarmidrashim commented on 30 Nov 2015
> This tactic is implemented differently than normal and will not show in getstats.
> 
> p.s omg for 3 years this tactic not working properly , poor engis ))

tactic broken after 27/10/2018 patch http://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=29003

before 27/10/2018 patch tactic was ok ( +15% range crit in .getstats)

**Comment by grunbag** [comment]
I works , it just not display in get stats
