### ISSUE TITLE
Вылеты из сюжетов

### ISSUE THREAD

**Issue by Tueday** [WarEmu/WarBugs#12539]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Зхожу на бг( сюжет или война) и у меня вылетает игра

Steps to reproduce the problem:
Все абсолютно стандартно

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
In english please
