### ISSUE TITLE
Game crashes repeatedly at Ravenraid camp in Norsca.

### ISSUE THREAD

**Issue by Tiredofpickingnames** [WarEmu/WarBugs#12533]
Expected behavior and actual behavior:  I expect to be able to move around at the camp.  I rode into the camp and the game crashed.  Now if I move or even just rotate in place with the mouse the game crashes.  The game does not crash if I stand there and do nothing.  At this point my character is stuck there since he literally can't move without an immediate crash of the game.

Steps to reproduce the problem:  Go to the Ravenraid camp in Norsca.  Move or turn with the mouse at the Ravenraid camp and the game crashes back to the desktop every time.  I repeated this about 5 times with the same result every time.

Screenshots/Videos or archive.org evidences:

**Comment by Harun4o** [comment]
Very similar problem here - While I have no issue at the Blessed Gathering Camp, the moment I get close to Festenplatz, the client crushes. Tried both 32/64 bit client, same thing. If I stay (and move) anywhere else - no problem.

I had to reinstall the whole client earlier today, so I am with completely fresh, updated client - so the client shouldn't be the issue.

Thanks in advance!

**Comment by Tiredofpickingnames** [comment]
Yeah, my install was brand new yesterday as I decided to come back and see what was new with the game.

**Comment by sioding** [comment]
Have you tried this here:

https://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=28927

**Comment by Harun4o** [comment]
> Have you tried this here:
> 
> https://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=28927

It seems to have worked for me, thanks!

**Comment by Tiredofpickingnames** [comment]
I made a reply earlier saying the file at the link you provided fixed the problem.  Now I don't see my reply in this ticket.  No idea what happened to it.  Problem solved.  Thanks sioding!
