### ISSUE TITLE
Quest "Toasting Giants" (Cinderfall, Destruction) not completeable

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12542]
The quest objective "Oathbearer Dwarfs" can't be fulfilled because the dwarfs don't count.

Expected behavior:
Killing dwarfs raises counter.

What I tried:
I killed every single dwarf at the quest location (Flamerock mine) outside and inside of the mine including every step of the PQ.

Result:
Counter still at 0/10.
Second quest objective works fine.

![quillog_002](https://user-images.githubusercontent.com/30193675/47963151-38bca180-e028-11e8-9845-d5eba906c5cb.jpg)

**Comment by Lheana** [comment]
Thanks for report, will be fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 05.11.2018
