### ISSUE TITLE
Big Claw - perma slowdown

### ISSUE THREAD

**Issue by Roedor78** [WarEmu/WarBugs#12540]
**Expected behavior and actual behavior:**
Big Claw (SH ability) should snare by 9s.
I have two times that it give me permanent snare - timer go to 0.0 and this stay on me. 
After my death this still was on me. I check .getstats and I have speed 60.

Only relog will help

**Steps to reproduce the problem:**
??

**Screenshots/Videos or archive.org evidences:**
On this two images look on clock - as you see ability is still on me and is 0.0
![roedor_046](https://user-images.githubusercontent.com/44190674/47955804-8cce7400-df9d-11e8-8e1d-d4601bd9039d.jpg)

![roedor_047](https://user-images.githubusercontent.com/44190674/47955780-51cc4080-df9d-11e8-9401-3495bba04d9d.jpg)

Here I not have ability but my speed is 60 - i'm still snared
![roedor_048](https://user-images.githubusercontent.com/44190674/47955781-5264d700-df9d-11e8-84ea-c1b21ee0a451.jpg)

**Comment by Natherul** [comment]
Im collating all tickets to one. This is probably related to the one that I just referenced therefor Im closing this ticket. Thanks for the report
