### ISSUE TITLE
Leather mask of the Gobbo

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#12549]
Of all masks that you can buy with tokens only gobbo mask has ability on it, with same mechanic that is on one that can be droped during event rvr, BUT it has no day countdown on it. Ability works, just tested it.
![mask](https://user-images.githubusercontent.com/42712833/48025378-48d19f80-e154-11e8-89fc-5e6b017975a4.png)

**Comment by Natherul** [comment]
should be fixed as of last reboot
