### ISSUE TITLE
Nordland Crash

### ISSUE THREAD

**Issue by Bowldancer** [WarEmu/WarBugs#12541]
**Expected behavior and actual behavior:**
Flying to Nordland with a destro character causes the game to crash.
Relogging the same character afterwards causes a crash.
Spamming /stuck during loading screen makes relogging possible again.

**Steps to reproduce the problem:**
-Flying with an Order char doesn't cause a crash as far as i tested 
  but i crashed on my first try with my Shaman flying from   IC to Nordland.
- Second Flight with my Shaman crashed again. Did /stuck 6 times and was fine afterwards
- Book of Binding to Nordland causes no crash
- Flying from Praag to Nordland causes a crash too so it is not the starting location.

**Comment by sioding** [comment]
I tried hard to reproduce that with more than a shaman - and i can´t. When did you downloaded the client? Is it a fresh one?

**Comment by Moragor** [comment]
I can confirm this problem. Today I created a new character (Rodira on destro side). I flew from the Norsca chapter 2 camp to Mt. Bloodhorn (Greenskin T1) and after the lock to Nordland. No problem. From Nordland I went to the Elves T1 and then back to Nordland at which point the problem occured. The loading screen ended with a crash to desktop. I tried to restart three times with this character, every time CTD.

I joined RoR 3 weeks ago and downloaded the client at this time.
In the past 3 weeks I created 5 characters, every toon flew to Nordland multiple times without any problem before.

**Comment by Bowldancer** [comment]
I think this was just a server related issue. Since the server crash and server restart i have no more issues flying to Nordland and the complaining threads on the forum and posts in the ingame channels have stopped. I am sorry i acted hasty opening this ticket.
