### ISSUE TITLE
problem in the overflow of the bag

### ISSUE THREAD

**Issue by odalia01** [WarEmu/WarBugs#12544]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

hello the overflow of my bag is bug I have room in the bag but 4 bug object

Steps to reproduce the problem:

so to have this problem it was enough to have your bag full and I make magic and bug recovery

Screenshots/Videos or archive.org evidences:
![odalia_077](https://user-images.githubusercontent.com/44757062/47970999-d944ad00-e08c-11e8-9876-65ba88c8e3c2.jpg)

**Comment by sioding** [comment]
Are you using filters for the nags?

**Comment by Nfkillz** [comment]
drag and drop items to your bank

**Comment by odalia01** [comment]
ok thx Nfkillz
