### ISSUE TITLE
Can't open Bags and Ability Windows

### ISSUE THREAD

**Issue by ShockParade** [WarEmu/WarBugs#12548]
Hi guy
Cannot open the bag nor the ability windows with any character and i dont see the item description at the quest dealer

Here's a pick but its a bit usless cuz i cannot make you see the problem
<a href="http://it.tinypic.com?ref=20utlvr" target="_blank"><img src="http://i63.tinypic.com/20utlvr.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

Thank you for the attention

**Comment by Torquemadra** [comment]
close client, restart launcher, repeat a couple of times and try again

**Comment by sioding** [comment]
No answer since 5th of november. Close
