### ISSUE TITLE
crashing game

### ISSUE THREAD

**Issue by Tueday** [WarEmu/WarBugs#12543]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
The game is crashing when i join rvr or scenario every time

Steps to reproduce the problem:
usual gameplay. It begins 1 day ago

Screenshots/Videos or archive.org evidences:

**Comment by Tueday** [comment]
yes


> Have you tried this here:
> 
> https://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=28927

**Comment by sioding** [comment]
OK - then i would like you to follow these 20 options:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=20075

Sorry but - i can not reproduce your problem - and without any errormessages we can not help at all.

**Comment by Tueday** [comment]
> OK - then i would like you to follow these 20 options:
> https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=20075
> 
> Sorry but - i can not reproduce your problem - and without any errormessages we can not help at all.

ty for help, i do something wrong with soundpack, but now everything is ok.
