### ISSUE TITLE
Caledor woods scenario

### ISSUE THREAD

**Issue by SilentMorbus** [WarEmu/WarBugs#12546]
![nurn_000](https://user-images.githubusercontent.com/28198207/48002812-eacd9980-e10c-11e8-866d-dfb0c9fdb4f0.jpg)
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Scenario freeze and instead of crash or else i found myself alone as you can see from screenshot

Steps to reproduce the problem:
no idea,scenario just freeze

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Can not reproduce that. Strange
