### ISSUE TITLE
"Corruptin Retribution" (chosen)[emulator][skill]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#1254]
The skill refresh itself every time you def, this make the skill not heal under focus, cos it tick after 1 sec and so if you get lot's of def you never get heal once, also it didn't refresh on officials.
Also 2nd and 3rd ticks seems happen very close to each other.

**Comment by osium** [comment]
yes this will never proc now if you are getting hit from multiple sources
