### ISSUE TITLE
Mail disappears if sent to a character which never logged on

### ISSUE THREAD

**Issue by Tyrean** [WarEmu/WarBugs#1255]
Evening !!

I have i big problem i do a trade wiht Tesq he send me Dire purple shroud + 33Toughness and i send to him my golds but tesq receive my gold and me me nothing from the mail box ! 

trade Screenshot :
http://hpics.li/ae50fa2

**Comment by xyeppp** [comment]
The mailbox system can bug out occasionally and not deliver your item - it has been this way for months. The item will either be there after a server restart, or it got lost in a vacuum.

**Comment by Tyrean** [comment]
Thank Xyepp but i give him 200g and i got nothing for me ...

**Comment by Tesq** [comment]
It was sent with a cod anyway. Don't know if change something

**Comment by Tyrean** [comment]
Tesq i have your mail in may mail box but impossible to take the Dire because i send you my golds Whitout COD checked . We need to re trade ....Sroory its my bad .

**Comment by Tesq** [comment]
i have some pc problem, i will have to rea-intall window, also ia lredy used some of those money, the bst you can do is click on return button to send me back the mail then i send you teh back directly with out "cod". I hope to be back in game in max 2 days.

**Comment by Evildoor** [comment]
Was this resolved?

**Comment by xyeppp** [comment]
Not really. 
If you send something to your alt that you have not logged in yet, the mail will disappear. Once you log the alt and relog, the mails will go through.

**Comment by Evildoor** [comment]
You mean a brand new lvl 1 character, on which you've never logged in yet?

**Comment by xyeppp** [comment]
Not sure. Would have to double-check it.

**Comment by Evildoor** [comment]
Status?

**Comment by xyeppp** [comment]
Yeah. If you don't log your brand new character at least once, no mail will go through because it's never initialized.

**Comment by sioding** [comment]
Tested this on my own. Created a new Character and did NOT logged in. Send with another char a mail and after that logged in the first time with the new generated char. Mail is available. So this is not an active issue anymore. Close
