### ISSUE TITLE
Crashes in Capitol Event Scenarios - constellation

### ISSUE THREAD

**Issue by rakels** [WarEmu/WarBugs#12553]
Sometimes when dying in the new city scenarios there wilI be a disconnect to character screen along with a quitter debuff. I think i found the constellations when it is happening and when not (atleast i was able to reproduce it every time i tried).

_Steps to not get dc's:_

- equip one of the masks
- queue up for the new sc's
- wait for invite and don't dare to change your head gear (even not when changing it again before entering the sc)
- no dc's on death when wearing on of the masks

_Steps to get dc's:_

- equip one of the masks
- queue up for the new sc's
- change your head gear (even just swapping for another mask) before or during the sc will result on crashes on death (with or without wearing the mask)

will try to reproduce both instances and upload a video on it (could take a little)

**Comment by Natherul** [comment]
this issue should have been fixed as of 2 days ago, please confirm

**Comment by rakels** [comment]
just tested it- works in both constellations now
