### ISSUE TITLE
Halloween Sword skin doesn't work for Shadow warrior

### ISSUE THREAD

**Issue by Shaeamus** [WarEmu/WarBugs#12558]
Expected behavior and actual behavior:

SW sword skin for halloween event wont apply appearance to SW swords.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Can you please add screenshots? We need to know which sword you would like to change with the event sword appearance.

**Comment by Shaeamus** [comment]
![sophiiaa_005](https://user-images.githubusercontent.com/44904003/48305504-38714a00-e4f1-11e8-8344-317e190c092c.jpg)

I'm trying to apply the Halloween sword over the 45 Renown sc sword.  See text in bottom left about the problem (in the screenshot.

**Comment by sioding** [comment]
This should be fixed.
