### ISSUE TITLE
Sewers of Altdorf Master Moulder Vitchek

### ISSUE THREAD

**Issue by Mercenery** [WarEmu/WarBugs#12552]
When attacking Master Moulder Vitchek he will disaper and leave a massage in the chat.
![mercenery_004](https://user-images.githubusercontent.com/16096191/48088671-e08dc700-e202-11e8-9d4a-5ebcda8b0ec0.jpg)

**Comment by Hargrim** [comment]
This should be fixed next patch (Saturday).
