### ISSUE TITLE
[Shadow Warrior] Enchanted Arrows

### ISSUE THREAD

**Issue by Ripliel** [WarEmu/WarBugs#12555]
Expected behavior:
Correct tooltip must show the amount of debuff.
Actual behavior:
It shows nothing. But it does reduce corp resistance (was tested and confirmed)
![qre](https://user-images.githubusercontent.com/16005849/48153638-ce318d00-e2d7-11e8-8798-e99c5a492042.PNG)
![qwre](https://user-images.githubusercontent.com/16005849/48153644-d12c7d80-e2d7-11e8-9b33-4ea60a8cdc5a.PNG)

Steps to reproduce the problem:
Take the tactic.
Use Acid Arrow.
Nor skill itself nor debuff don't change their tooltip.

**Comment by dalen** [comment]
This tactic has changed since then and is fixed now
