### ISSUE TITLE
Permanent heal debuff

### ISSUE THREAD

**Issue by Minipuce** [WarEmu/WarBugs#12567]
All outgoing heals are down to 50% even when the debuff has gone. Like the snare bug, we have to log out to get back normal heals.

**Comment by Minipuce** [comment]
All outgoing heals are down to 50% even when the debuff has gone. Like the snare bug, we have to log out to get back normal heals.

**Comment by sioding** [comment]
Thanks for the report but it´s missing some important informations. When, where, what - and please: Add screenshots for it. With this single sentence no dev is able to reproduce the problem.

**Comment by Minipuce** [comment]
Well, I'm a runepriest (so it was order side), and it was this morning in rvr field (Talabecland-High pas). I don't know exactly when it happened. There were many squigs herder in the game and lots of debuff heal everywhere.
But when i wanted to heal my partners who had not any debuff on them i saw that my heals where only 50%. We went back to the warcamp, to be quiet, and i tried again on me, on a slayer and on an ironbreaker : all of my heals skills where 50% (i tried Grungni' gift and Rune of restoration) (saw it in my log : the amount of overheal). I don't know really if it was a problem with my outgoing heals, or if everyone had a permanent debuff incoming heal. Screenshots will not help you : we had nothing on us (no debuff, no buff, nothing). Just the amount of the heals in the log were half the normal amount.  That's it. I don't know what i can do more to explain. Many healers saw that too.

**Comment by sioding** [comment]
I do play a healer every evening on my own - and i never saw that. Without being able to reproduce that - it will be really hard to fix it. I will have a look at it on my own - and maybe other healers can have a look at it too. I let this issue open for 14 days - but tbh if no one is able to reproduce it...

**Comment by Minipuce** [comment]
Well if it happens again i will take screenshots of my log. I hope this will not.

**Comment by Minipuce** [comment]
"it is somehow connected to rune of breaking malfunction."
No, I didn't use rune of breaking at all.

**Comment by sioding** [comment]
Oh good - so we can link this issue to the other. Thanks @Morksezstop for referencing.

**Comment by Minipuce** [comment]
No this is not good to link this issue with this one because the issue i'm reporting is also for other healers and not ony for RP. At the moment i have the same issue, in Kadrin valley. The amount of my heals are again 50% normal. I took a screenshot. You can see that the keg of MacBernick (an engineer) heals correctly. But my heals on him, on me and on Hogun the Ironbreaker are 50% normal. I can join also a screenshot from Hogun : he still has a witch elf debuff "kiss of death" that is not removed. We have a seriously problem of permanent debuff heal.
![minipuce_125](https://user-images.githubusercontent.com/39655844/48357791-b2443780-e699-11e8-93e6-e991f21b3fbc.jpg)
https://media.discordapp.net/attachments/509457162674765824/511565250131263489/Hogun_069.jpg?width=963&height=542
https://cdn.discordapp.com/attachments/509457162674765824/511566174899929091/Hogun_070.jpg

**Comment by Minipuce** [comment]
Another time, this bug happened : "outgoinghealx0.5". No clue at all what is the source of the problem. Not even sure it comes from a destro class.
https://media.discordapp.net/attachments/512450317414039563/514623621382012931/unknown.png?width=741&height=666
