### ISSUE TITLE
[SH]Tactic "Shootin'Wlf Da Wind" 

### ISSUE THREAD

**Issue by Vladvon** [WarEmu/WarBugs#12565]
"Shootin'Wlf Da Wind" 
There are times when it does not work
①It does not work if come back to dead
②After the scenario is over
![sh](https://user-images.githubusercontent.com/42826843/48311484-d34a5100-e5e3-11e8-9512-dc346147450e.jpg)

**Comment by sioding** [comment]
Hey - thanks for the report. Do we speak about the tooltip which is not updated or a real range problem?
Is the tooltip ok after leaving the scenario? Would be great to have that screenshot too.

**Comment by Vladvon** [comment]
yes real range problem

**Comment by sioding** [comment]
A tooltip is what you are referencing on your first screenshot. If you hover over an ability and a little window appears - thats a tooltip. Thanks for creating a video - please upload it to youtube and give us a link for it.

**Comment by Vladvon** [comment]
ok.
I'll upload it when I take a bug

**Comment by Vladvon** [comment]
Movie Uploaded

https://www.youtube.com/watch?v=vR1obhvNcKI&list=PLAzdW_QvJOkmB-cdaAxmnC8Jilu0jk7eo&t=0s&index=2

After Movie① ⇒ Movie②
Movie② is bug

Movie① (08:20)small bug.

**Comment by grunbag** [comment]
Tactic have been fixed already and refresh correctly now
