### ISSUE TITLE
SH Big Claw snare can't be cleansed

### ISSUE THREAD

**Issue by Sulorie** [WarEmu/WarBugs#12561]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior: SH using squig armor can use Big Claw to snare a target for 9 sec. The skill has damage type, therefore cleansing ailment has no effect.

Steps to reproduce the problem: Getting hit by Big Claw, trying to cleanse with Cleansing Light, which cleanses other SH debuffs because of ailment type. No effect. Buffhead shows the debuff as being  cleanseable, because it probable expects SH debuffs to be cleansed.

Other SH debuff skills like cooldown increaser have damage type too, not sure if the same issue persists there or the debuff got a separate type.

Screenshots/Videos or archive.org evidences: No screenshots because the issue should be obvious. :)

**Comment by grunbag** [comment]
Fixed already
