### ISSUE TITLE
[Quest] Masks of Corruption

### ISSUE THREAD

**Issue by tog89** [WarEmu/WarBugs#12564]
Expected behavior and actual behavior:

When I have met the requirements of the Masks of Corruption by Assassinating 100 Masked Players and attempt to turn in the quest, the Wild-Eyed Guiltseeker will not provide a reward and gives the text from the original stage 1 quest when you get the mask.  The quest does not complete.  No reward is listed in the Quest Text.

Steps to reproduce the problem:

As the quest does not complete, the error persists and is reproducible on a re-log.

Screenshots/Videos or archive.org evidences:
![tog_060](https://user-images.githubusercontent.com/38359697/48307822-0c6abe80-e51b-11e8-876f-28ac3c237a1c.jpg)
![tog_061](https://user-images.githubusercontent.com/38359697/48307824-0ffe4580-e51b-11e8-8f74-b0ce0c668a3b.jpg)

**Comment by sioding** [comment]
Thanks to @Lheana  -  this will be fixed with the next patch.

**Comment by sioding** [comment]
fixed with patch from 17.11.2018
