### ISSUE TITLE
[Magus and Engi] Instability/Self-Destruct is not firing properly

### ISSUE THREAD

**Issue by Renork** [WarEmu/WarBugs#1256]
It sometimes works, it sometimes doesn't. If you summon your pet/resummon and attempt to use instability immediately after, the pet will either stay alive or die without knocking down people. The pink horror has a very small chance of knocking down others compared to the blue fiend and flamer. It "sometimes" works after the pet has been up for over 7+ seconds, but usually only 1-2 people are knocked down. I tested it today vs. an IB, WP, AM (no cc used, no immunity) and it didn't work, and later in sc's by running into the order flag (needed to test it on multiple players with no immunity). It's amazing when it works but it doesn't seem to work the majority of the time.

**Comment by Renork** [comment]
Update: It looks like the ability itself will go on cooldown (60s) even if it doesn't fire properly.

Example: Summon Flamer, cast instability = flamer doesn't explode and ability goes on cooldown.

**Comment by knightningale90** [comment]
Not sure what causes it but it doesn't fire most of the time. 
![chronostasis_010](https://cloud.githubusercontent.com/assets/14324838/10029758/59864ad2-61a6-11e5-99c5-703655bad14e.jpg)
It went down to cd 2s ago, the pet was still alive and well, and the gor was not kd'ed.

**Comment by Evildoor** [comment]
From my brief observations, the ability fails to work when you are out of combat.

**Comment by knightningale90** [comment]
It is possible that out of combat is one of the times where it doesn't fire properly. In addition tho, it sometimes doesn't fire in combat in pvp situaion because I have tried it and it didn't kd people when they don't have immunity on :)
