### ISSUE TITLE
Quest: For the Empire! Praag Ch. 18

### ISSUE THREAD

**Issue by Sinrman** [WarEmu/WarBugs#12562]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_

- Checked, there are no current open issues with this quest.

Expected behavior and actual behavior:

Expected: Gather arms from fallen Empire warriors/ find Empire corpse/standard Jerkin

Actual: There are no Empire corpse to be found in area designated on map. Only Terrified citizens and Wounded Defenders. Interacting with them do not further the quest.
- Searched outside of map marked area and unable to find empire corpses.

![gunnr_025](https://user-images.githubusercontent.com/42098334/48302312-b79a5a00-e4c0-11e8-8ff0-ba13a54426d5.jpg)
![gunnr_026](https://user-images.githubusercontent.com/42098334/48302313-ba954a80-e4c0-11e8-99dc-c8a89926b218.jpg)
![gunnr_027](https://user-images.githubusercontent.com/42098334/48302315-bd903b00-e4c0-11e8-8d37-9e40cae21471.jpg)

.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Lheana** [comment]
Thanks for report, will be fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 17.11.2018
