### ISSUE TITLE
Intruder Giantslayer (item bug)

### ISSUE THREAD

**Issue by Sandskid** [WarEmu/WarBugs#12563]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior: In Altdorf Sewers you can loot an axe for Slayer, which can be used either both hands or off hand and has 2h damage and 2 slots for talies. I think the ability to use it as an offhand is a bug.

Steps to reproduce the problem: 

Screenshots/Videos or archive.org evidences: http://funkyimg.com/i/2N18j.png

**Comment by sioding** [comment]
Thanks for report. Fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 17.11.2018
