### ISSUE TITLE
[Quest] [Annihilation] Reiksguard Defenders are not spawning anywhere; quest cannot be completed

### ISSUE THREAD

**Issue by Eggs** [WarEmu/WarBugs#12577]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Expected them to appear outside Chapter 22 Keep; completed "fields" PQ to level 3 and did multiple clears of surrounding mobs checking for PH before moving inside and doing the other 2 PQs in the keep to level 3 while clearing nearby mobs as well. All told, spent about 5 hrs farming several adjacent areas. No defenders anywhere.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Lheana** [comment]
Epic quest has been reworked, but not all changes have been pushed on live. Have to wait for next patch to be fixed.

**Comment by sioding** [comment]
fixed with patch from 17.11.2018
