### ISSUE TITLE
[The Ebon Flame] t4 Dark Elf epic line also broken Keeper of the Way MIA

### ISSUE THREAD

**Issue by Eggs** [WarEmu/WarBugs#12579]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Keeper is supposed to be behind the wall at the orb, on the roof at the orb, or in the center of the shrine guarded by 2 champs. The keeper is not in any of those places, and I've checked a couple of days in a row.

Also, if you click the orb, it takes you to the roof. If you click that orb, it takes you to a room with an NPC and two doors. Exiting either of the doors ports you across the zone and instakills you.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Lheana** [comment]
He is correctly there
![anaehll_396](https://user-images.githubusercontent.com/11537611/48432233-189d8880-e774-11e8-9ab2-8a9020a8d895.jpg)
Maybe he had a walk and reboot fixed it.
