### ISSUE TITLE
Stuck as chicken in IC.

### ISSUE THREAD

**Issue by faithneverdiesaway** [WarEmu/WarBugs#12574]
Expected behavior and actual behavior:
Was finished with zombie quest chain. I was no longer a zombie and then the game crashed. I came back in as a zombie. I tried to leave the zombie state by flagging myself in a PVP island. I became a chicken. I have remained a chicken since, in all zones I fly to. I was still a chicken when the zombie timer finished counting down.

Steps to reproduce the problem:
Become a zombie, crash game, become a chicken, and then stay a chicken.

Screenshots/Videos or archive.org evidences:
A screenshot is attached. 
![chicken in ic](https://user-images.githubusercontent.com/44961072/48329938-af950400-e5ff-11e8-85be-837f6ad3d774.png)

**Comment by Lheana** [comment]
Maybe we can close it @sioding as the zombie quest was only an event?

**Comment by sioding** [comment]
yes - event done - so: close
