### ISSUE TITLE
Wrong stat on bw imperator set .

### ISSUE THREAD

**Issue by Tholkienn** [WarEmu/WarBugs#12573]
Expected behavior and actual behavior: bw imperator shoulder have a bonus on weapon skills.
Seems to have to be another stat, like initiative.
No melee spec on this char was working, seems to be a mistake.

**Comment by wargrimnir** [comment]
It's going to take us some time to develop a melee spec, but we're working on it.,

**Comment by wargrimnir** [comment]
I don't see this, assuming it's already been fixed.
