### ISSUE TITLE
Annihilation

### ISSUE THREAD

**Issue by BLOODCLART** [WarEmu/WarBugs#12578]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by BLOODCLART** [comment]
can not hand in the first part of the quest Radulf is not in the cave

**Comment by Lheana** [comment]
Epic quest has been reworked, but not all changes have been pushed on live. Have to wait for next patch to be fixed.
Anyway you can turn in the quest to the original spawn at the PQ Vulgar Display of Power.
