### ISSUE TITLE
Lines of code popping up in my chat window

### ISSUE THREAD

**Issue by Aebell** [WarEmu/WarBugs#12575]
The last week or so I have been experiencing lines of code popping up in my chat box, it looks like it's tied to other players close by pulling mobs (about 95% of the time it's in a major city). Attached is a screenshot of it happening when another player pulls a named troll in Troll Country. Also for reference I don't play with any addons or anything, nothing on my computer is interfering with the game in any way.

![fyngolfin_005](https://user-images.githubusercontent.com/44963666/48333898-d0fcec80-e60d-11e8-8bc8-297aadeaf501.jpg)

**Comment by sioding** [comment]
You can deactivte that by using the chat filter. If you hover over the chat you see a "General" - right click on it - and you see "Filter". Deactivate channel 9 - its our "addon control channel".
