### ISSUE TITLE
Scenario Crash - Character Screen UI

### ISSUE THREAD

**Issue by ArxCaeli** [WarEmu/WarBugs#12576]
Expected behavior and actual behavior:
Joining scenarios usual way - join all.
expected - no problems
actual - Some times (don't know why/random) instead of joining to sc it showing me login hud without background. Then teleports me to altdorf with same hud (see picture). Plus gives me sc debuff. Can't play after without restarting the client.

Steps to reproduce the problem:
join sc, get bug.

Screenshots/Videos or archive.org evidences:
![scbugsmall](https://user-images.githubusercontent.com/4072674/48371723-92594780-e68a-11e8-8101-45736336f741.jpg)
http://i68.tinypic.com/2gvltmr.jpg

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/11224
