### ISSUE TITLE
Quest Unmasking the Enemy

### ISSUE THREAD

**Issue by Oldneko** [WarEmu/WarBugs#12584]
![fucq_015](https://user-images.githubusercontent.com/43213086/48483633-57f0d580-e857-11e8-8bed-718522290030.jpg)
Quest Unmasking the Enemy Step4 
'the Orb' is disappeared and can't continue this quest

**Comment by nuraiii** [comment]
I have the same problem ! No orb...

**Comment by ElateGeoduck** [comment]
Hello!
That's it - no orb detected!

**Comment by Lheana** [comment]
Quest will be fixed with next patch.

**Comment by sioding** [comment]
fixed with patch from 17.11.2018

**Comment by Oldneko** [comment]
hi, Sio

that quest don’t move yet, after Orb’s step.
Zepher cant fly and I cant continue this quest

Jun Mito as Oldneko

**Comment by nuraiii** [comment]
working ! I can go on :)

**Comment by Lheana** [comment]
Verify your quest inventory to complete the different steps of Epic Quest, it has been fullly reworked.
Wiki will soon be updated with correct information
