### ISSUE TITLE
[Choppa] <<Morale level 4>> Stomp Da Yard

### ISSUE THREAD

**Issue by Dikilenyarrak** [WarEmu/WarBugs#12582]
When i login back to the game, i see that 'Stomp Da Yard' morale ability has lost again. So i have to take it again from trainer... My idea is it might be related to level 39 Annihilator set, which gives +1 Wrecka ability bonus. Because when i took that gear set, it didn't give that bonus and i had to reset talents, after that earned it...

**Comment by sioding** [comment]
Sorry - i don´t get it. If you wear the complete Annihilator set and your have trained the M4 it ist lost on every login? Or ist it lost when your just change your gear?

**Comment by sioding** [comment]
No answer since 27 days. Close
