### ISSUE TITLE
Slayer Pirates/Rumguards Scavenging Bug

### ISSUE THREAD

**Issue by Lindisfarne** [WarEmu/WarBugs#1258]
It seems that the slayers in the PQ "Long Drong and the Slayer Cove" in Barak Varr chapter 9, are giving more scavenging xp than they should. You can level straight to 200 scavenge on them and they give 1 level scavenge on 1 to 5~ mobs killed. The mobs are Slayer Pirates and Slayer Rumguards, they're level 18-20 so i don't think they should give so much scavenge xp. Not exactly a huge bug, but i figured i should report.

**Comment by wargrimnir** [comment]
Was never able to confirm this.
