### ISSUE TITLE
impossible to get out from the sewer close to bright wizard college

### ISSUE THREAD

**Issue by Oceanman69** [WarEmu/WarBugs#12580]
Expected behavior and actual behavior:

i enter in sewer close to bright college wizard and was unable to get out, even after death /rel etc

Steps to reproduce the problem:

enter the sewer alone and try to get out

Screenshots/Videos or archive.org evidences:

![bohm_000](https://user-images.githubusercontent.com/44948395/48424379-cef87200-e762-11e8-9291-77e96810907b.jpg)
![bohm_001](https://user-images.githubusercontent.com/44948395/48424380-cef87200-e762-11e8-858c-718ee8eec2c2.jpg)
![bohm_002](https://user-images.githubusercontent.com/44948395/48424381-cf910880-e762-11e8-8664-301622d6bc06.jpg)
![bohm_003](https://user-images.githubusercontent.com/44948395/48424382-cf910880-e762-11e8-8864-0a68d78eed31.jpg)
![bohm_004](https://user-images.githubusercontent.com/44948395/48424384-d0299f00-e762-11e8-8e90-2412319f3a52.jpg)
![bohm_005](https://user-images.githubusercontent.com/44948395/48424385-d0299f00-e762-11e8-98fb-04aff05a825e.jpg)

**Comment by Oceanman69** [comment]
it says unvailable area try later

**Comment by Oceanman69** [comment]
it says unavailable area
try later

**Comment by sioding** [comment]
Are you sure you aren´t in combat anymore?

**Comment by Oceanman69** [comment]
sure i tryed with being killed by a champion in the area and respawn to the NPC at the entrance
and still not working

**Comment by Lheana** [comment]
Have you tried the other exit?

**Comment by Lheana** [comment]
Portals for this instance were all disabled, reenabled it, so will be fixed with next patch.

**Comment by sioding** [comment]
fixed with patch from 17.11.2018
