### ISSUE TITLE
WL [Leonine Frenzy] do less damage as expected

### ISSUE THREAD

**Issue by admaska2** [WarEmu/WarBugs#12587]
Expected behavior and actual behavior:

[Leonine Frenzy] does 361 damage on the target dummy - Damage according to skill description 418

Bug similar to https://github.com/WarEmu/WarBugs/issues/12335

![leonine](https://user-images.githubusercontent.com/43276959/48545120-7392c500-e8c5-11e8-9412-514eddee3a11.png)

**Comment by grunbag** [comment]
Fixed already
