### ISSUE TITLE
bug with slayer career tactic takin'chances

### ISSUE THREAD

**Issue by Oceanman69** [WarEmu/WarBugs#12586]
Expected behavior:

first tactic of the path of the skavenslayer heals you when active

and actual behavior:

sometimes it bugs i had to deconect and reconect to fix the problem

Steps to reproduce the problem:

try it

Screenshots/Videos or archive.org evidences:

don t have screenshot cause can t be significative but i check in chat section "my heals" and before the disconection no heals tik after reconection it was working and tiks appear on the channel

**Comment by sioding** [comment]
Where did this problem occur? Are you level 40 or was it when you were bolstered? How should we reproduce that? Thats why screenshots are important. Please try to reproduce that and bring in screenshots when you found howand when. I have no idea how a dev can fix that without more informations.

**Comment by sioding** [comment]
No answer since 26 days. Close
