### ISSUE TITLE
Grimmenhagen Farmers giving influence rewards?

### ISSUE THREAD

**Issue by Phineasfreak1** [WarEmu/WarBugs#12589]
Not sure how it happened, but all of a sudden, Grimmenhagen farmers want to give out influence rewards. Such hard workers they are, toiling away relentlessly.....

Screenshots/Videos or archive.org evidences:
![ulatek_001](https://user-images.githubusercontent.com/45086647/48595688-d2872700-e923-11e8-9047-784e80d18ba8.jpg)
![ulatek_000](https://user-images.githubusercontent.com/45086647/48595705-e0d54300-e923-11e8-9fca-d674a71cd65c.jpg)

**Comment by Lheana** [comment]
This has been fixed a while back.
