### ISSUE TITLE
Quest Da All Powerful

### ISSUE THREAD

**Issue by Gwendis** [WarEmu/WarBugs#12593]
Hello,

I found a Quest-bug in Ekrund, Destruction side.

The quest: Da All Powerful.

You have to do:
*Friedrich Krause's Medallion - 1/1   ->No problem
*Kill Red Raider Adept - 0/3         -> There are no of this mobs in the area and zone, only there are Red Raider Robber and Red Raider Knifer.

Thanks
Ingame name: Alexcia

**Comment by Lheana** [comment]
Adepts are right next to Friedrich, near the big tent.
I restored original objective that should be to destroy Pilfered Crates.

**Comment by sioding** [comment]
fixed with patch from 15.12.2018
