### ISSUE TITLE
Wrong amount of action points

### ISSUE THREAD

**Issue by DaWAAAGH** [WarEmu/WarBugs#12590]
I have noticed that players have wrong amount of natural action points, asked about this in advice chat and Malvaine mentioned that renown ranks added extra action points for players in live (25ap at rr65 and another 25ap at rr75)(I know this is not live). Current amount of action point is 250 but at renown rank 80 players should have 300 action points already. There is some proofs in youtube, old rr80 WAR videos show 300ap and not 250ap and rr >75 with 275ap.
Not sure if this is intended here or just long forgotten thing.

https://www.youtube.com/watch?v=1S-Pi0WZCOU <---rr80 with 300ap
https://www.youtube.com/watch?v=iqF0W540pbg <---rr80 with 300ap
https://www.youtube.com/watch?v=KHRdRWAQD10   <--- rr73 with 275ap
https://www.youtube.com/watch?v=1PzKoS99TKc <---rr64 with 250ap (poor quality but you if you look at ap bar you can see somehow 250)

My choppa below with 250ap at rr84:
![choppa rr84](https://user-images.githubusercontent.com/16031857/48612231-09475680-e991-11e8-8a79-3017e205ee36.jpg)

**Comment by Natherul** [comment]
this is something we have not implemented by design.
You can buy more AP pool from the renown trainer should you desire. 

Thanks for the report
