### ISSUE TITLE
can't finish the quest "spotting trouble" in altdorf

### ISSUE THREAD

**Issue by Oceanman69** [WarEmu/WarBugs#12596]
hi,

Expected behavior and actual behavior:

take quest to pnj "watchmen terrence located in altdorf docks 31.26/21.79
the quest says "search the floating corpse at the edge of the docks"

you ll find it a bit further on the docks below the edge floating on the river 31.27/24.99

you can clic on it but nothing happen

can't finish the quest
![leopolld_000](https://user-images.githubusercontent.com/44948395/48657890-b0cb9400-ea38-11e8-8c5f-90fee39b62e4.jpg)
![leopolld_001](https://user-images.githubusercontent.com/44948395/48657891-b0cb9400-ea38-11e8-9c98-0468d5d5b4c2.jpg)
![leopolld_002](https://user-images.githubusercontent.com/44948395/48657892-b1642a80-ea38-11e8-9427-458569c8f6fc.jpg)
![leopolld_003](https://user-images.githubusercontent.com/44948395/48657893-b1642a80-ea38-11e8-9463-dbf384237eb1.jpg)
![leopolld_004](https://user-images.githubusercontent.com/44948395/48657894-b1642a80-ea38-11e8-88ad-0c7ac82d0b9c.jpg)

thanks

in game kotbs named leopolld

**Comment by Lheana** [comment]
This has been fixed with patch of today. The GO Floating Corpse now drops an item called 'Family Crest'.
