### ISSUE TITLE
Aura Spread failure

### ISSUE THREAD

**Issue by Skutrug** [WarEmu/WarBugs#1259]
As a chosen, if I look at the Warband interface and try to join a warband but did not succeed, I get a message saying "Aura spread failure" which prevents me from running any aura until I relog.

**Comment by ozarmidrashim** [comment]
Interesting. I was wondering where that bug was coming from.

**Comment by Skutrug** [comment]
Well,

I sure hope you fix it quick :-) 

It must be somehow related to the WB interface - if you cannot join (full, but with the buggy WB display it says there are openings) then it triggers the aura spread refusal.

The problem is... it also affects your aura, so relog is required.

Good luck fixing

Fred

**Comment by Skutrug** [comment]
It's fixed :-) Well done!
