### ISSUE TITLE
Anyone Have a Can Opener? ToK unlock

### ISSUE THREAD

**Issue by Sinrman** [WarEmu/WarBugs#12594]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Checked tickets, there is a closed ticket #11049 that sorta has same issue. But said was fixed in patch

Expected behavior and actual behavior:

Expected: According to Wiki: 
Anyone Have a Can Opener? is a Tome of Knowledge Bestiary entry for Living Armor.

Instructions: Order & Destruction
No access to Isle of the Dead for now 

Kill 30 'Living Armors' at the Destruction PQ 'Ritual of Metal' on the Isle of the Dead at 13.8k 26.8k for this unlock.

Actual: Killed 30, then 50, then 100. No unlock "Anyone Have a Can Opener?"

![gunnr_034](https://user-images.githubusercontent.com/42098334/48633782-a0a8ab80-e989-11e8-8c83-12609235d19a.jpg)
![gunnr_035](https://user-images.githubusercontent.com/42098334/48633790-aacaaa00-e989-11e8-9745-b0f8f9e21fc0.jpg)
![gunnr_036](https://user-images.githubusercontent.com/42098334/48633810-bb7b2000-e989-11e8-9897-af0e73c0c6e9.jpg)

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Sinrman** [comment]
Sorry, I assumed as you stated in the other ticket: 

Lheana (Dec 26, 2017)
Thanks for reporting it, fixed next patch. I advice you not to try to do the other kill unlocks for Living Armor until next patch as there were **other errors that I also corrected.**

plus, Thorbolt80 in the other ticket has this title unlocked in his/her screenshot so I assumed it was working.

So can I contact someone to update the Wiki to reflect this unlock has not been implement yet?

thanks for all your help and hard work.

**Comment by Lheana** [comment]
Other errors did not include this unlock.
I have aldready corrected the wiki ;)
