### ISSUE TITLE
Doombolt Cast Time

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#12599]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Cast time for Doombolt should display 3 sec. Currently showing as 1.5 sec in action bar. When you activate this ability it still of course takes 3 sec to cast, and when hovering mouse over ability during it being cast, you will see on action bar that it says 3 sec again.

Steps to reproduce the problem:

Just tweak the stats on display to show 3 sec not 1.5.

Screenshots/Videos or archive.org evidences:

![db](https://user-images.githubusercontent.com/22262165/48660953-429bc700-ea62-11e8-9439-32751a03f7f6.png)

When casting, you will see it is correctly 3 sec
![db2](https://user-images.githubusercontent.com/22262165/48660954-4891a800-ea62-11e8-96bb-01e54875f2e2.png)

At this point, icon in action bar also shows 3 sec
![db3](https://user-images.githubusercontent.com/22262165/48660957-4f201f80-ea62-11e8-94b9-956d78c68931.png)

**Comment by Torquemadra** [comment]
not sure what the issue is here, my doombolt shows 3s cast in tooltip and castbar as per client, the only way that should change is under the effect of a cast time reduction ability such as focused mind

**Comment by Senthoi** [comment]
Thanks for looking at this, I have Close Quarters equipped at the moment as a tactic that would reduce cast times by 50% when within a certain range. But when I am just stood doing nothing, and hover the mouse over Doombolt on the Action Bar it shows as having a 1.5 second cast time. I might be reading this incorrectly, but I would have expected this to read as 3 secs? The ability is working as I would expect it to though.

**Comment by kalmatar** [comment]
Close Quarters equipped gives -50% cast to all spells when hovering mouse over them. Then depending if client thinks target is within 20ft of you at that second, it will also apply that effect - otherwise not so it will give standard 3 sec cast.

**Comment by Senthoi** [comment]
Ahhh, that explains it. Thank you Kalmatar. Whilst I was not targeting anything the explanation makes sense. There were attackable mobs nearby.
