### ISSUE TITLE
Ironclad T1 Bolster Missing

### ISSUE THREAD

**Issue by Rivenspeak** [WarEmu/WarBugs#12600]
Was just in Ironclad scenario T1 and there was no bolster showing on either side.  Based on damage dealt/taken, it doesn't appear bolster was in effect at all.

**Comment by markytheoz** [comment]
17th of March 2019 and this scenario is still in the rotation and still not bolstering.

**Comment by sioding** [comment]
We don't need bumping on the bugtracker.
