### ISSUE TITLE
attacked by 'Fire Trap' in Altdorf, near flycorps.

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#12605]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Expected - not to be attacked by this thing.
Actual - Attacked by this Fire Trap invisible enemy.
I do believe my Against All Odds must have attacked this which was previously hidden.
Steps to reproduce the problem:
Use AAO near Altdorf flycorps

Screenshots/Videos or archive.org evidences:
https://image.ibb.co/eKdnX0/firetrap.png

**Comment by Lheana** [comment]
Should be fixed with next patch.

**Comment by sioding** [comment]
fixed with patch from 24.11.2018
