### ISSUE TITLE
[SW] Assault Stance Bug

### ISSUE THREAD

**Issue by Ripliel** [WarEmu/WarBugs#12609]
Expected behavior:
Assault stance applies without any problem.

Actual behavior:
Assault stance can't be used from non-stance condition.
[Video evidence](https://youtu.be/4MjNiIXerz0)

Assault can be entered only from another stance like Scout, for example.
The issue happened in new City Dungeons. 
May be related to:
Dungeon.
Resurrection.
Being killed by boss.
Being killed with active stance.

**Comment by grunbag** [comment]
It still happen ?

**Comment by Ripliel** [comment]
Haven’t noticed again.
