### ISSUE TITLE
Slayer/Choppa positional not scaling

### ISSUE THREAD

**Issue by blakokami** [WarEmu/WarBugs#12608]
The abilities spine crusher and go for da soft spot are not scaling off of the left tree like they should. They just got reverted to the left tree so it probably just needs to be hotfixed. Tested with 0 points in tree and with varying points in left tree and the damage is the same.

**Comment by Torquemadra** [comment]
absolutely does, checked and verified on dev and live.

https://i.imgur.com/YV0FdoT.jpg
https://imgur.com/qUDxweF
