### ISSUE TITLE
[Warpblades] Master Moulder Skrot.

### ISSUE THREAD

**Issue by Ripliel** [WarEmu/WarBugs#12603]
Damage mitigation bugs on both bosses.
![afasfasf](https://user-images.githubusercontent.com/16005849/48664086-6be04580-eaaa-11e8-8419-b5efad3c22e2.PNG)

Debuff reaches silly numbers like 100% slow.
![gdasf](https://user-images.githubusercontent.com/16005849/48664088-6d117280-eaaa-11e8-8247-74508dcd1187.PNG)

Also double spawn happens 
![asd](https://user-images.githubusercontent.com/16005849/48664162-b7dfba00-eaab-11e8-9379-ce94fb71fd73.PNG)

**Comment by grunbag** [comment]
check brauk HP, he should stay between 60% and 50% asap.
