### ISSUE TITLE
Encounter in progress

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#12606]
There is problem with new dungeons - encountered by us in BE. When we wiped aggro of boss stayed triggered with no target (could see on aggro meter), so when one of us had to log out - he was spawned outside and could not get in, getting outside with full group and reassembling party ahve not helped.
![veszal_327](https://user-images.githubusercontent.com/42712833/48665215-e1084680-eabb-11e8-9108-7f8d7e7526e1.jpg)

**Comment by grunbag** [comment]
something for nalgol

**Comment by sioding** [comment]
fixed with patch from 24.11.2018
