### ISSUE TITLE
[Quest] Worthy of service (The Shadowlands, destro) Quest marker switched/missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12617]
The quest marker for "List of Marks" is at the position of "Kill Shadowsting", while the Marker for "Kill Shadowsting" is missing.
It is also a bit unclear that "List of Marks" is completed by talking to the quest giver since originally it was done via quest item.

![worthy of service](https://user-images.githubusercontent.com/30193675/48674611-6e947680-eb4e-11e8-857a-06244e121505.jpg)

**Comment by sioding** [comment]
fixed with patch from 24.11.2018
