### ISSUE TITLE
[Quest] Reversal of Fortune (The Shadowlands, destro) multiple bugs

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12615]
The quest marker for "Skyherald Message" is missing.
The second problem is the the general position bug of NPCs that can occur in RoR. When killing the bird mid air it is often not lootable because the dead body in client doesn't match the position in server. I recommend to change quest objective to "on kill" instead of "looting item"

![reversal of fortune](https://user-images.githubusercontent.com/30193675/48674511-64be4380-eb4d-11e8-9ac6-af5a5e043819.jpg)

**Comment by sioding** [comment]
Thanks for the report. As far as i see you are in a report creating rage :) I do appreciate this - but please: only one problem per report. It is not always the same developer who can handle problem 1 as well as problem 2.

**Comment by Moragor** [comment]
Ok, I'll do that in the future.

**Comment by Lheana** [comment]
Set the quest markers. Also activated and corrected the whole quest line.
About the NPC who is flying, it's a bird, so he is meant to fly ... I did not have any problem looting him, the only advice I can give is not to one shot the warhawk to give him time to go down.

**Comment by sioding** [comment]
fixed with patch from 24.11.2018
