### ISSUE TITLE
[Engineer] Ruin set has wrong 4 pieces bonus

### ISSUE THREAD

**Issue by nocturnalguest** [WarEmu/WarBugs#12610]
After Server patch notes of 17/11/2018 and implementations of new gear model Ruin 4 piece set bonus bugged out.

Expected behavior and actual behavior:
Now it adds a point to Rfileman tree, which is Mercenary set task. It should be +1 for Grenadier tree, not Rifleman.
Steps to reproduce the problem:
All sets of this tier has different +1 for all three Mastery trees. Engineer now has only 2 instead of 3.

Screenshots/Videos or archive.org evidences:
<img width="1152" alt="2018-11-18 1" src="https://user-images.githubusercontent.com/17257194/48672189-afd35900-eb43-11e8-9abe-d30ac33d0f55.png">
<img width="1152" alt="2018-11-18" src="https://user-images.githubusercontent.com/17257194/48672190-b06bef80-eb43-11e8-972c-3912c5951412.png">
<img width="1152" alt="2018-11-18 2" src="https://user-images.githubusercontent.com/17257194/48672191-b06bef80-eb43-11e8-89d6-f0dace07f4fe.png">

**Comment by grunbag** [comment]
Ruins set has been review ; the stats and bonus have changed last patch

**Comment by nocturnalguest** [comment]
> 
> 
> Ruins set has been review ; the stats and bonus have changed last patch
So Engineer being the only one class having a duplication on this tier of sets in terms of  points to mastery tree is intended, correct?
