### ISSUE TITLE
[Quest] Disenchanting the Stone (2) (The Shadowlands, destro) Quest marker mising/Quest description wrong

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12619]
The quest marker for this quest is missing.
The quest description says "Travel northwest", but the the Altar is actually southwest of the quest NPC.

![disenchanting the stone_2](https://user-images.githubusercontent.com/30193675/48674778-56255b80-eb50-11e8-9855-2457c2de9193.jpg)
![disenchanting the stone_2_2](https://user-images.githubusercontent.com/30193675/48674780-5c1b3c80-eb50-11e8-87ab-756eec8e62c9.jpg)

**Comment by Lheana** [comment]
This is because you aren't meant to turn in the quest to the NPC, but by examining the journal in the inventory, which can not be implemented yet.
