### ISSUE TITLE
[Quest] Land of Shadows (The Shadowlands, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12611]
The quest markers for Moroirl Shdowdancer and Celedaine Duskbringer are missing. The marker for Endhrios Silentfall disappears after killing him leaving it unclear where to search for the others.

![land_of_shadows](https://user-images.githubusercontent.com/30193675/48674281-c335f280-eb4a-11e8-9848-e81fbf487ab5.jpg)

**Comment by Lheana** [comment]
Quest markers are fixed. I also restored original objectives, thus you may need to abandon and retake the quest.

**Comment by sioding** [comment]
fixed with patch from 24.11.2018
