### ISSUE TITLE
[Quest] The misguided of Nagarythe (The Shadowlands. destro) End quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12616]
The end-quest marker for the NPC to turn in the quest is missing.

![the misguided of nagarythe](https://user-images.githubusercontent.com/30193675/48674555-d0a0ac00-eb4d-11e8-9af4-173e9d4a7fab.jpg)

**Comment by Lheana** [comment]
This quest marker is not missing. Maybe you could not see it because you logged out.
