### ISSUE TITLE
[Quest]Destruction of Spirit (The Shadowlands, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12614]
The quest marker for the second objective "Gloombridge Terrors" is missing.

![destruction of spirit](https://user-images.githubusercontent.com/30193675/48674390-deedc880-eb4b-11e8-94e6-c173cf8bbfc8.jpg)

**Comment by sioding** [comment]
fixed with patch from 24.11.2018
