### ISSUE TITLE
[Minor bug][Quest] Sacking of Nordland (Nordland, destro) non quest object fulfills quest objective

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12629]
The quest objective "Kindling set ablaze" can be fulfilled by using a random kindling, for example the ones at the PQ "Suderholm" in Norsca.  Not a big Problem, but I thought I report it to be sure.

![sacking of nordland](https://user-images.githubusercontent.com/30193675/48688345-1731ed00-ebc6-11e8-87b7-924f709ac0dc.jpg)

**Comment by sioding** [comment]
fixed with patch from 1.12.2018
