### ISSUE TITLE
[event][destru] city dungeons influence & related

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#12625]
influence bar of new dungeons reset every time i enter inside em and no rewards get show; additonaly kill part of the event are not saved , exemple i was 6/12 exited from the dungeons and it reset; the visit part instead remained saved. idk if this happen to on order side aswell

**Comment by grunbag** [comment]
It’s a test we actually made with event tok page . No reward yet it will be fixed at next event . Thanks for the feedback
