### ISSUE TITLE
[Quest] Becoming the Unseen (The Shadowlands, destro) Quest marker mising

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12620]
The quest marker for the objective "Kill dawnbreak scout" is missing.

![becoming the unseen](https://user-images.githubusercontent.com/30193675/48674837-fbd8ca80-eb50-11e8-8100-119831ee5217.jpg)

**Comment by sioding** [comment]
fixed with patch from 24.11.2018
