### ISSUE TITLE
[Quest] Green is Best (Reikland, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12623]
The quest marker for this quest is missing. With the vague description it is pretty unclear what exactly to bash here.

![warboss](https://user-images.githubusercontent.com/30193675/48675142-88858780-eb55-11e8-8ca1-efd2aceea76a.jpg)

**Comment by AmidalaEstellanor** [comment]
Checking

**Comment by Cygre** [comment]
Marker still missing

**Comment by Lheana** [comment]
That's why it is still open...
