### ISSUE TITLE
[itiem][chosen] sentinel chaos seal jewelry

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#12624]
i dropped this jewelry called sentinel  chaos seal but is blue colored and dosent appear to have the set bonuse but when i wear both this and sentinel helm i visual recive the +1 on the set bonuses; (.getstats show is only visual and the set bonus is not reward at all ) which lead to :: 

![tesq_350](https://user-images.githubusercontent.com/7527415/48675185-44df4d80-eb56-11e8-89f3-eb6ba348faa5.jpg)
![tesq_351](https://user-images.githubusercontent.com/7527415/48675186-44df4d80-eb56-11e8-9acc-c9a051b8153b.jpg)

A-should be gold named and show the set bonuses as the expected behaviour for being part of the set (if it is)  which do not
B-it have a similar name to the real sentinel set jewelry, for error or lack of imagination and it end to visual bug it.

**Comment by grunbag** [comment]
there is no sentinel set jewerly

**Comment by grunbag** [comment]
it's a place holder, the real last bonus will come later
