### ISSUE TITLE
[Quest] Becoming the Unseen (The Shadowlands, destro) too few NPCs

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12621]
For the quest you must kill 3 Dawnbreak Hunters, but in the quest area there is only a single one, so you have to wait for respawn. I recommend adding two more Hunters.

![becoming the unseen](https://user-images.githubusercontent.com/30193675/48674879-9fc27600-eb51-11e8-92ac-2314442bd3da.jpg)

**Comment by Lheana** [comment]
This is because there are several camps where you can find them. Waypoints for these places will be shown with next patch.
