### ISSUE TITLE
{Quest] Thrill of Power (Chrace, destro) quest markers mising

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12622]
The markers for the four ""XYZ" Ley Stone Placed on Rubric" objectives are missing.

![quillog_008](https://user-images.githubusercontent.com/30193675/48675119-24fb5a00-eb55-11e8-9f1a-7d923a5dc423.jpg)

**Comment by sioding** [comment]
fixed with patch from 24.11.2018
