### ISSUE TITLE
City Dungeon Lockouts

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#12626]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

I would expect that once you receive a lockout after completing a City Dungeon, you then cannot re-enter for the duration of the lockout. You can currently re-enter, despite having a lockout yourself, by joining a party led by a player who does not have a lockout. So you can enter a dungeon as many times as you like at the moment as long as you pick a group leader without a lockout.

Seems to be the case with Bilerot Burrows and Bloodwrought Enclave - haven't been on Order today yet.

(Edit: I had a snooze before posting this - saw it seems to have already been mentioned in the RoR Discord so you're on it!)

Steps to reproduce the problem:

Set the lockouts so that only those players without a lockout can enter the dungeons.

Screenshots/Videos or archive.org evidences:

**Comment by grunbag** [comment]
Fixed at next patch

**Comment by Senthoi** [comment]
That's terrific, thank Grunbag
