### ISSUE TITLE
SH: Horned Pet Attacking its owner

### ISSUE THREAD

**Issue by Eybala** [WarEmu/WarBugs#12637]
Expected behavior and actual behavior: 

my loyal pet that sticks by my side (mans best friend) VS My horned devil squig that attacks me at random to the point i have to resummon another pet or die slowly

Steps to reproduce the problem:

have to summon other pets that are non useful in current builds (melee), , and ponder around for 15 sec for recast hoping u dont get jumped. tried numerous ways to stop it :) 

which also makes it hard, due to the fact  of the issue/bug with our pets Insta summon ability after using "tastses like chicken" and " farty Squig" where they are 2 sec stand still casts for the last 2 months? (intended)?

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Duplicate of #12216
