### ISSUE TITLE
[Quest] Prove your Worth (Nordland, destro) Qest marker missplaced

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12631]
The quest marker for the objective "Kill Salzenmund Champion" is at the wrong position, it should be at the same position as the gravestone marker since the champion is right beside the gravestone.

![prove your worth](https://user-images.githubusercontent.com/30193675/48688778-e488f400-ebc7-11e8-9531-8c86c306dcfa.jpg)
![prove your worth_2](https://user-images.githubusercontent.com/30193675/48688787-e94da800-ebc7-11e8-94c1-3efb4fc6b0a2.jpg)

**Comment by sioding** [comment]
fixed with patch from 1.12.2018
