### ISSUE TITLE
[Quests] Order city instances

### ISSUE THREAD

**Issue by Ondorie** [WarEmu/WarBugs#12638]
The quests:
- The threat from Necromancer Malcidious
- The threat from Tobias The Fallen
- The threat from Lecor Twins
- The threat from  Grey Seer Quol´tik
- The threat from  Warlock Peenk
keep resetting after logging off

**Comment by Hargrim** [comment]
Hi,

What you mean resetting? Like you get 1 kill, you log off and log back in and it's back to 0?

**Comment by raptrr** [comment]
No further information provided, closing issue
