### ISSUE TITLE
[Quest] Insurrection (Nordland, destro) Quest marker switched

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12632]
The quest markers for the objective "Speak with Conrad Schulman" and "Watch the Inner Gate" are switched.

![insurrection](https://user-images.githubusercontent.com/30193675/48688926-7f81ce00-ebc8-11e8-845d-93510fa3a935.jpg)

**Comment by sioding** [comment]
fixed with patch from 1.12.2018
