### ISSUE TITLE
[Quest] The Corruption Within (Ostland, destro) Quest marker missplaced/missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12633]
The quest marker for "Find Bloodthorn" is at the position where Fungal Rot and Shimmerweed, but not Bloodthorn is found, while the marker at the actual position for Bloodthorn, at the PQ "Reaper's Circle", is missing.

![the corruption within](https://user-images.githubusercontent.com/30193675/48689219-b99f9f80-ebc9-11e8-85e6-1abb1b041919.jpg)

**Comment by sioding** [comment]
fixed with patch from 1.12.2018
