### ISSUE TITLE
Target Dummies in IC not attackable

### ISSUE THREAD

**Issue by acidicrain** [WarEmu/WarBugs#12643]
Expected behavior and actual behavior:

Target dummies were attackable

Steps to reproduce the problem:

Try striking the dummies, no attack is triggered
only rock ard is avalable but as seen in vid its to triggering anything, rest of skills not usable when target dummy targeted.

Screenshots/Videos or archive.org evidences:
https://youtu.be/OXo5THxBb3U

**Comment by sioding** [comment]
fixed with patch from 24.11.2018
