### ISSUE TITLE
Female DoK in character creation won't open eyes

### ISSUE THREAD

**Issue by b-wun** [WarEmu/WarBugs#12647]
Expected behavior and actual behavior:
Female Disciple of Khaine should have their eyes open while creating a character.
They only have their eyes open while playing the opening animation, then they close them.

Steps to reproduce the problem:
Log in, select create, select dark elf, select DoK, select female

Screenshots/Videos or archive.org evidences:
![screenshot_000](https://user-images.githubusercontent.com/45181902/48732381-65b5b900-eca4-11e8-9ad6-36d634914883.jpg)
![screenshot_001](https://user-images.githubusercontent.com/45181902/48732382-65b5b900-eca4-11e8-9738-8530d8cd8a3d.jpg)
![screenshot_002](https://user-images.githubusercontent.com/45181902/48732384-65b5b900-eca4-11e8-87a2-e12337a9adf1.jpg)

**Comment by Kaelang** [comment]
No longer happens on current version of ROR.
