### ISSUE TITLE
AM Conq belt has armor on it

### ISSUE THREAD

**Issue by tigerungen** [WarEmu/WarBugs#12648]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Conq belt for AM has over 700 armor on it

Steps to reproduce the problem:
Remove the armor? :)

Screenshots/Videos or archive.org evidences:

**Comment by wargrimnir** [comment]
Fix pending.

**Comment by sioding** [comment]
fixed with patch from 24.11.2018
