### ISSUE TITLE
Go for da spot spot Scaling

### ISSUE THREAD

**Issue by blakokami** [WarEmu/WarBugs#12646]
This ability for Choppa is still scaling off the middle tree instead of left tree.

https://cdn.discordapp.com/attachments/309846429369630720/514164720102670336/Domantis_010.jpg

https://cdn.discordapp.com/attachments/309846429369630720/514164376371200000/Domantis_013.jpg

**Comment by Torquemadra** [comment]
Thank you, should be fixed on live now but may require a boot.

**Comment by sioding** [comment]
fixed with patch from 24.11.2018
