### ISSUE TITLE
 PQ Foul Ruins Stage 2

### ISSUE THREAD

**Issue by darkbiff** [WarEmu/WarBugs#12649]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Stage 2 cannot be completed as the pillars cannot be attacked and destroyed.
Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Lheana** [comment]
Related to #12643 will be fixed with next patch.
