### ISSUE TITLE
[WP] Sigmar's Radiance is unusable as it now requires a shield

### ISSUE THREAD

**Issue by Rydiak** [WarEmu/WarBugs#12657]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Warrior Priest Grace ability Sigmar's Radiance is now requiring a shield to be equipped before being usable.  Warrior Priests cannot equip shields, meaning the ability (and thus Grace as a spec) is unusable.

Steps to reproduce the problem:
Attempt to use Sigmar's Radiance.  The ability will not function and the icon will remain red.

Screenshots/Videos or archive.org evidences:
![rydiak_157](https://user-images.githubusercontent.com/15963532/48764746-283a3700-ec76-11e8-9f03-c68de750f981.jpg)

**Comment by sioding** [comment]
Thjanks - will be hotfixed today.

**Comment by Natherul** [comment]
should be fixed now
