### ISSUE TITLE
Sentinel Boyz' Chain

### ISSUE THREAD

**Issue by Iamwithstupid** [WarEmu/WarBugs#12652]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Sentinel jewelry for Black Orc is a part of Sentinel Inquisitor kit - Witch Hunter? set. Gives no set bonus on equip for Black Orc. Also marked as ''Jewelry 3'' - can go only to 3rd jewelry slot.

Steps to reproduce the problem:
Make Black Orc jewel part of Black Orc Sentinel set.

Screenshots/Videos or archive.org evidences:

![untitled](https://user-images.githubusercontent.com/36380568/48743706-e789f000-ec6c-11e8-9bc1-1c4641172799.png)

**Comment by wargrimnir** [comment]
3rd slot is intended. Witch hunter is not. Will review, thanks.

**Comment by wargrimnir** [comment]
This was corrected some time ago.
