### ISSUE TITLE
Can't open "special bag".

### ISSUE THREAD

**Issue by Rincevvind** [WarEmu/WarBugs#12659]
Won a special loot bag, can't open it, menu simply not appearing. 
Have 2 bags already. 

Expected behavior and actual behavior:
Ability to open it and getting my cow pie.

Steps to reproduce the problem:
Right click on bag, nothing happens

Screenshots/Videos or archive.org evidences:

**Comment by Luuca** [comment]
I have the same issue. SOme info that may or may not be relevant:
When I got the loot bag initially, it bugged out my bags. As in, it looked as if I only had 2 bag slots purchased and would have to re-buy the other two. When that happened, I logged out of game, closed game, deleted cache folder, and logged back in. 

Once back in, my bags were fine, but Special Loot bag would not open. Both of these bags were received through the mail - if that helps.

**Comment by sioding** [comment]
fixed
