### ISSUE TITLE
Loryndaal - Public Quest Destruction Dark Elf Chapter 16

### ISSUE THREAD

**Issue by Spacepoitre** [WarEmu/WarBugs#12651]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior: on Loryndaal - Public Quest Destruction Dark Elf Chapter 16 stage II, 3 dragon orb must be destroyed, but you can't use attack on it. The orb can be targeted, but you can't do any damage on it

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Lheana** [comment]
Related to #12643 will be fixed with next patch.
