### ISSUE TITLE
Shaman- Scuse me, Sticky feetz scaling.

### ISSUE THREAD

**Issue by Iamwithstupid** [WarEmu/WarBugs#12655]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Scuse me was moved from Path of da Green to Path of Gork but it's damage and debuff value will still scale with point spent in Path of da Green.
Sticky feetz was moved from Path of Mork to Path of da Green but will still scale with points spent in Path of Mork,

Steps to reproduce the problem:
Assign abilities to correct Mastery.

Screenshots/Videos or archive.org evidences:

**Comment by Sulorie** [comment]
Sticky feetz doesn't scale at all in Mork tree. Scuse Me! scales again with da Green.

**Comment by grunbag** [comment]
it seems to work for me on dev now
