### ISSUE TITLE
[WP] Divine Assault and Divine Strike Healing for Less than Tooltip

### ISSUE THREAD

**Issue by Rivenspeak** [WarEmu/WarBugs#12658]
Divine Assault appears to heal for only 100% of damage dealt, not 350% as in the tooltip. (damage 226, heals 157)
Divine Strike appear to only by healing for 30% of damage dealt, not 100% as in the tooltip. (damage 160, heals 31)

These should not be affected by 20% heal reduction from tactics (and even then, the math doesn't work out)

![drystheim_002](https://user-images.githubusercontent.com/45123644/48777942-f5a63380-eca1-11e8-96ab-2207e8a28d5f.jpg)
![drystheim_000](https://user-images.githubusercontent.com/45123644/48777969-02c32280-eca2-11e8-8ff0-d1f5c436a7a8.jpg)

**Comment by sioding** [comment]
This is intended on the lord. So sorry - no bug.
