### ISSUE TITLE
Oppressor and Vanquisher tokens cannot be down converted

### ISSUE THREAD

**Issue by Skullgrin** [WarEmu/WarBugs#12653]
In the latest hotfix notes(dated 19/11/2018) it was stated that 

- New Scenario Currency can now be converted down to 5 Conqueror's Emblems
- New RvR Currency can now be converted down to 1 Conqueror's Medallion

After checking the new merchant that sells Oppressor items I determined that there were no conversion purchases through him as seen in the following screen shots - 

![thargrimm_310](https://user-images.githubusercontent.com/40448982/48749383-f7d3a800-ec37-11e8-8467-3c5068e04100.jpg)
![thargrimm_311](https://user-images.githubusercontent.com/40448982/48749387-fc985c00-ec37-11e8-8751-a7f442f1381d.jpg)

Looking at the descriptions on the tokens themselves reveals that you should be able to convert that at the Oppressor or Vanquisher Quartermaster  - 

![thargrimm_322](https://user-images.githubusercontent.com/40448982/48749497-74ff1d00-ec38-11e8-99a3-28f7791ca5c3.jpg)
![thargrimm_323](https://user-images.githubusercontent.com/40448982/48749503-7892a400-ec38-11e8-8289-a7fd12df5119.jpg)

The Vanquisher Quartermaster has no way to do this, and the Oppressor Quartermaster DOES NOT exist in Inevitable City.

Additionally I asked about this in the patch notes thread and was told by Hargrim (on page 9 of the thread) that they could be converted using Shift + Right Click. This does not work, as it is used to split a stack apart. I also tried variations of this using alt, ctrl, and shift while left, center and right clicking. None worked for converting the tokens.

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
fixed with patch from 24.11.2018
