### ISSUE TITLE
Shaman- 'Ey 'Quit Bleedin' does not scale with mastery

### ISSUE THREAD

**Issue by Iamwithstupid** [WarEmu/WarBugs#12654]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
'Ey 'Quit Bleedin' does not scale with mastery points spent in Path of Mork. The healing value of this ability is always maxed.

Steps to reproduce the problem:
make 'Ey 'Quit Bleedin' scale with mastery.

Screenshots/Videos or archive.org evidences:
![untitled](https://user-images.githubusercontent.com/36380568/48761007-3d33bc00-ecb0-11e8-8e5f-d42ca18eff2d.png)
![untitled2](https://user-images.githubusercontent.com/36380568/48761054-5c324e00-ecb0-11e8-9655-6c88412bf3ef.png)

**Comment by Torquemadra** [comment]
core ability which is not affiliated to any tree and never has been so unaffected by mastery points
