### ISSUE TITLE
[Quest] Head of the Line (Ellyrion, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12664]
The quest markers for the objectives "Kill Crethois Velthrai" and "Kill Larathwen Velthrai" are missing.

![head of the line](https://user-images.githubusercontent.com/30193675/48785564-3e331080-ece5-11e8-9f85-3416a3e95185.jpg)

**Comment by sioding** [comment]
fixed with patch from 08.12.2018
