### ISSUE TITLE
Bright Wizard - Vanquisher / Oppressor

### ISSUE THREAD

**Issue by Zarbix** [WarEmu/WarBugs#12661]
Hey there,

Noticed the stats on the BW sets are slightly off. For example, the Vanquisher belt is missing initiative that the Sorcerer version has.

Also the Oppressor chest says +2 critical hit rate, and needs to be changed to match the normal critical hit rate language.

That's all for now, though I'll try to find any more problems.

Thks!

**Comment by sioding** [comment]
fixed with patch from 08.12.2018
