### ISSUE TITLE
T4 Elf Epic Quest: Unmasking the Enemy; Final boss does not appear

### ISSUE THREAD

**Issue by swolefrankieg** [WarEmu/WarBugs#12660]
Based on the wiki:
https://wiki.returnofreckoning.com/index.php/High_Elves_T4_Epic_Quest_Unmasking_the_Enemy
I am on step 15.

According to this post:
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=26951&p=304937&hilit=unmasking#p304937
The quest NPC is supposed to be at 14.7k, 41.9k but he does not appear for me.

![npc 1](https://user-images.githubusercontent.com/45204151/48779929-05625e00-ed1c-11e8-8aa9-9d5085fe775c.png)
![npc 2](https://user-images.githubusercontent.com/45204151/48779930-05faf480-ed1c-11e8-9961-6e84d6b95e93.png)
![npc 3](https://user-images.githubusercontent.com/45204151/48779931-06938b00-ed1c-11e8-8cd5-2b74d901023b.png)
![npc 4](https://user-images.githubusercontent.com/45204151/48779933-06938b00-ed1c-11e8-950a-c54cb9e11231.png)
![npc 5](https://user-images.githubusercontent.com/45204151/48780142-8ae60e00-ed1c-11e8-82c7-a931bc2e8d01.png)

**Comment by Lheana** [comment]
It was noted on the previous patch notes that the whole Epic Quest had been reworked. Follow the quest marker as its goal is to indicate the location to complete the quest, and I do see it on your last screenshot.
I even updated RoR Wiki with new instructions: https://wiki.returnofreckoning.com/index.php/High_Elves_T4_Epic_Quest_Unmasking_the_Enemy

**Comment by swolefrankieg** [comment]
Didn't the NPC get moved out of that area since the PQ was made harder than normal?

**Comment by Lheana** [comment]
Maybe but the main idea is not to have to complete stages of hard chap 22 PQs to be able to complete a quest. You don't need to complete the first stage, you can avoid some NPCs passing behind some buildings, then you pull some NPCs but should be doable.

**Comment by swolefrankieg** [comment]
Are you ingame now? Can you help me out? I have been looking for this dude for 2 days now.

**Comment by Lheana** [comment]
Where are you searching? Inside the quest marker?

**Comment by swolefrankieg** [comment]
If you insist that he's there that's where I plan to look.
If you have a second can you PM swolefrankieg ingame?
