### ISSUE TITLE
[Quest] Silence Their Cries (Ellyrion, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12662]
The quest marker for the objective "Ellyrian Reavers" is missing.

![silence their cries](https://user-images.githubusercontent.com/30193675/48784899-e1832600-ece3-11e8-9dab-3ca4ff9fa088.jpg)

**Comment by Kabucoror** [comment]
Fixed next patch.

**Comment by sioding** [comment]
fixed with patch from 1.12.2018
