### ISSUE TITLE
[Quest] An Inconvenient Truce (Ellyrion, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12665]
The quest marker for the objective "Ellyrian Watchers" is missing.

![an inconvienient truce](https://user-images.githubusercontent.com/30193675/48785694-87836000-ece5-11e8-9f8d-7982d3cf727d.jpg)

**Comment by sioding** [comment]
fixed with patch from 08.12.2018
