### ISSUE TITLE
[Quest] As a Matter of Fact (Ellyrion, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12667]
The quest marker for the objective "Kill Arkaneth Watcher" is missing.

![as a matter of fact](https://user-images.githubusercontent.com/30193675/48785857-ddf09e80-ece5-11e8-9c14-6d1d7b089bfb.jpg)

**Comment by sioding** [comment]
fixed with patch from 08.12.2018
