### ISSUE TITLE
[Quest] As a Matter of Fact (Ellyrion, destro) Wrong NPC linked to quest objective

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12669]
Killing an "Arkaneth Watcher" completes the objective "Arkaneth Watchcaptain" which is a separate NPC in the area.

![as a matter of fact](https://user-images.githubusercontent.com/30193675/48786161-8272e080-ece6-11e8-9d89-d771a339af82.jpg)

**Comment by sioding** [comment]
fixed with patch from 08.12.2018
