### ISSUE TITLE
[NPC] Ferentuil the Free, (Ellyrion) Hostile towards allies

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12663]
The champion mob Ferentuil the Free attacks surrounding mobs, I'm not sure if this is intended.

![ferentuil](https://user-images.githubusercontent.com/30193675/48785338-d67cc580-ece4-11e8-8991-58ea2ff3014d.jpg)

Position:
![ferentuil2](https://user-images.githubusercontent.com/30193675/48785355-dda3d380-ece4-11e8-9ea1-20f5f13bf8d2.jpg)

**Comment by sioding** [comment]
Fixed with patch from 19.01.2019
