### ISSUE TITLE
[Scenario] Gates of Ekrund : impossible take flag

### ISSUE THREAD

**Issue by freezeheart** [WarEmu/WarBugs#12678]
![gateofekrund20181120](https://user-images.githubusercontent.com/43251697/48807232-2d9e8c80-ed1d-11e8-9499-565589b94066.png)
This evening, in the scenario nobody can take the flag. 
The scenario finish when the timer is down.

**Comment by Natherul** [comment]
Will be fixed on the next server restart.

**Comment by sioding** [comment]
fixed with patch from 24.11.2018
