### ISSUE TITLE
[Quest] Defender's Defeat (Avelorn, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12673]
The quest marker for the objective "Kill Lothern Crest Blade" is missing.

![deffenders defeat](https://user-images.githubusercontent.com/30193675/48786849-f6fa4f00-ece7-11e8-8629-d4c1274c6106.jpg)

**Comment by sioding** [comment]
fixed with patch from 15.12.2018
