### ISSUE TITLE
Onslaught Wardshoes (Sorcerer) has "Ranged Power" instead of "Magic Power"

### ISSUE THREAD

**Issue by Talladego** [WarEmu/WarBugs#12675]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Sorcerer boots "Onslaught Wardshoes" has the bonus "18 Ranged Power".
Expected bonus would be "Magic Power"
Checked with .getstats

Steps to reproduce the problem:
Equip Onslaught Wardshoes and check .getstats

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/45210243/48791825-f4e9bd80-ecf2-11e8-994b-7e3de2ad0f23.png)

![image](https://user-images.githubusercontent.com/45210243/48791881-18ad0380-ecf3-11e8-9740-ba26624c1c4d.png)

**Comment by sioding** [comment]
fixed with patch from 1.12.2018
