### ISSUE TITLE
[Tooltip/Function] Warrior Priest - Sigmar's Shield

### ISSUE THREAD

**Issue by Rydiak** [WarEmu/WarBugs#12676]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Very minor, but Sigmar's Shield currently drains RF when struck, not per second as the tooltip states.  Since .ab changelist is gone, there is currently no way to see the changed ability behavior other than using Sigmar's Shield in combat and seeing the difference for yourself.

Steps to reproduce the problem:
Sigmar's Shield has a different use in combat than the tooltip states.  Use the ability and compare to the stated tooltip.

Screenshots/Videos or archive.org evidences:
![rydiak_159](https://user-images.githubusercontent.com/15963532/48794951-129e2f00-ecc1-11e8-9377-fcec820bbc19.jpg)

**Comment by Rydiak** [comment]
I played around with Sigmar's Shield so more, and the ability appears to be double-dipping on RF.  It is currently draining 15 RF *per second* in ADDITION to 10 RF *per time you are struck*.  Something is very goofy with the ability.

**Comment by sioding** [comment]
fixed with patch from 1.12.2018
