### ISSUE TITLE
[Quest] Silence Their Cries (2) (Ellyrion/Avelorn, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12670]
The quest marker for this quest is missing.

![silence their cries2](https://user-images.githubusercontent.com/30193675/48786239-b5b56f80-ece6-11e8-8853-e4513b6f4e0d.jpg)

**Comment by Kabucoror** [comment]
Fixed with next patch.

**Comment by sioding** [comment]
fixed with patch from 1.12.2018
