### ISSUE TITLE
[Quest] Tor Elyr Must Fall (Ellyrion, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12671]
The quest marker for the objective "Ellyrian Defenders" is missing.

![tor elyr must fall](https://user-images.githubusercontent.com/30193675/48786436-29577c80-ece7-11e8-8361-669f36edee1a.jpg)

**Comment by sioding** [comment]
removed a comment which wasn´t helpful. This is not the forum guys.

**Comment by Kabucoror** [comment]
the whole quest chain will be fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 08.12.2018
