### ISSUE TITLE
[Quest] Silence Their Cries (3) (Ellyrion/Avelorn, destro) NPC missing or not linked

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12683]
The NPC for this quest seems to be missing or is not correctly linked to the quest objective. Due to the missing quest marker (see https://github.com/WarEmu/WarBugs/issues/12670 ) it is hard to say where to look for him, but I searched the whole road from its beginning in northern Ellyrion to southern Avelorn and couldn't find him. There are high elf messenger NPCs in Ellyrion near the portal to Avelorn, but killing them multiple times did not count for the quest.

![quillog_002](https://user-images.githubusercontent.com/30193675/48872694-96076f80-edea-11e8-835b-0132bedb55bc.jpg)

**Comment by Kabucoror** [comment]
will be fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 08.12.2018
