### ISSUE TITLE
[Public Quest]Raven Host Vanguard(Order, Empire Ch1)

### ISSUE THREAD

**Issue by KVasEC** [WarEmu/WarBugs#12685]
If the boss kills an NPC in the third stage, the quest does not end and the reward is not given.

**Comment by WO-RoR-Exile** [comment]
Still an issue. 12/03/2019.

![Argog Bug](https://user-images.githubusercontent.com/58471571/70051222-44192e00-1596-11ea-917a-adcba6b76bfb.png)
