### ISSUE TITLE
[Conqueror] Melee and Heal Critical value nerfed to 1% instead 2%

### ISSUE THREAD

**Issue by XmatXergon** [WarEmu/WarBugs#12680]
Expected behavior and actual behavior:
After releasing new sets Oppressor and Vanquisher, stats on Conqueror got nerfed.
But Critical value on Boots for Ranged and Magical classes got changed from 3% to 2% (on Tanks 2% Block) where on Boots for Melee DPS and Healing classes Critical value got changed from 3% to 1%.

Steps to reproduce the problem:
N/A

Dominator looks fine.

Screenshots/Videos or archive.org evidences:
![xergoam_022](https://user-images.githubusercontent.com/37849311/48816001-d3afbe00-ed40-11e8-9c5d-7b0dc45f57d7.jpg)
![xergoam_033](https://user-images.githubusercontent.com/37849311/48816002-d3afbe00-ed40-11e8-8d6a-a5cb034fc8a5.jpg)
![xergoam_032](https://user-images.githubusercontent.com/37849311/48816003-d4485480-ed40-11e8-85c4-44480b965660.jpg)
![xergoam_031](https://user-images.githubusercontent.com/37849311/48816004-d4485480-ed40-11e8-887e-00103207a54c.jpg)
![xergoam_030](https://user-images.githubusercontent.com/37849311/48816005-d4485480-ed40-11e8-9f12-98c69f9708cb.jpg)
![xergoam_029](https://user-images.githubusercontent.com/37849311/48816006-d4485480-ed40-11e8-9c3c-bb969983e77c.jpg)
![xergoam_028](https://user-images.githubusercontent.com/37849311/48816007-d4485480-ed40-11e8-8b58-78f82d9ee96f.jpg)
![xergoam_027](https://user-images.githubusercontent.com/37849311/48816008-d4485480-ed40-11e8-84b3-5e58327357f5.jpg)
![xergoam_026](https://user-images.githubusercontent.com/37849311/48816009-d4e0eb00-ed40-11e8-91e0-95b4a11cbc3c.jpg)
![xergoam_025](https://user-images.githubusercontent.com/37849311/48816010-d4e0eb00-ed40-11e8-9a0a-bfcf492f6888.jpg)
![xergoam_024](https://user-images.githubusercontent.com/37849311/48816011-d4e0eb00-ed40-11e8-9b5b-58c515d18d8d.jpg)
![xergoam_023](https://user-images.githubusercontent.com/37849311/48816012-d4e0eb00-ed40-11e8-8f02-b06aada6addc.jpg)

**Comment by wargrimnir** [comment]
Fixed with Saturday push
