### ISSUE TITLE
Black Guard - Unstoppable Fury Tactic

### ISSUE THREAD

**Issue by cturk** [WarEmu/WarBugs#12682]
This has been a discussion on forums and on wiki a few times. However, those times did not have video evidence like we do.

**This tactic has been reported twice on github 2016:** 
https://github.com/WarEmu/WarBugs/issues?utf8=%E2%9C%93&q=unstoppable+fury

**On the forums:**
https://www.returnofreckoning.com/forum/search.php?keywords=unstoppable+fury

**Problem:** 
BG tactic should be ignoring the detaunt and it's not.

**Expected behavior and actual behavior:**

     **Expected:** detaunts are dispelled automatically when applied to you
     **Actual Behavior:** Detaunt uneffected supplied from tactic.

**Steps to reproduce the problem:**
Detaunt a BG. BG MUST have the tactic slotted.

**Screenshots/Videos or archive.org evidences:**
Large Clip: https://www.twitch.tv/videos/338908891

Those commited to the testing are are Oberyn, Cxt

**Comment by Torquemadra** [comment]
yeah... 33 minute video isnt getting looked through. first 2 minutes are literally nothing. and it seems to work just fine for me because it purges detaunts when applied to you

**Comment by cturk** [comment]
Ok thanks Torq for your feed back.
