### ISSUE TITLE
Low Level Choosen in T4 - Raze hitting by 353 per hit

### ISSUE THREAD

**Issue by exotlv** [WarEmu/WarBugs#12681]
Choosen - LvL26.
M2 - Raze
Hitting 353 with boolster. I think it's wrong. 

Expected behavior and actual behavior:
AR: Raze hitting by 353 per hit
ER: 300 or 206 as Morale info says.

Steps to reproduce the problem:
Choosen lvl 26. Go T4, get boolster. Build M2(Raze) and start hitting enemy. You hitting by 353 per hit.

Screenshots/Videos or archive.org evidences:
![nohire_001](https://user-images.githubusercontent.com/8436809/48834051-77bb5880-ed85-11e8-9ad6-ccb9d1236aff.jpg)

**Comment by Torquemadra** [comment]
Bolster boosts low levels past normal parameters
