### ISSUE TITLE
Disatrous  Cascade returns NullReference

### ISSUE THREAD

**Issue by acidicrain** [WarEmu/WarBugs#12687]
Expected behavior and actual behavior:
No error message, actual behaviour error message(see pic)

Steps to reproduce the problem:
dieing while using soc cascade

Screenshots/Videos or archive.org evidences:

![poxi_000](https://user-images.githubusercontent.com/28633576/48920834-9449b480-ee9b-11e8-8d27-c718d4c3b3cc.jpg)

**Comment by grunbag** [comment]
fixed a while ago
