### ISSUE TITLE
T3 elf rvr boots

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#12688]
T3 elf rvr influence boots, one has an an empty talisman slot and the other doesnt.

Expected behavior and actual behavior:

They should both have the talisman slot.

**Comment by sioding** [comment]
Well - this doesn´t help at all. Please add a screenhot or at least the name of the items.

**Comment by Xicoz** [comment]
hello the items are "Ghrond's Tramplers" and "Qhaysh Tramplers" I hope this helps.

**Comment by wargrimnir** [comment]
Added tali slots where appropriate.

**Comment by sioding** [comment]
fixed with patch from 1.12.2018
