### ISSUE TITLE
Inevitable Power - Librarians Blood Tome

### ISSUE THREAD

**Issue by FixitFastah** [WarEmu/WarBugs#12691]
Oi, thought time for some pve. Picked up this quest, did the pq's and slipped into the tower I needed to find some bloody tome. Finding this tome is not the problem, picking it up is...

Tried relog, checked my bags, but clicking it won't work. The tome floats but does not complete the quest.

**Comment by Lheana** [comment]
Maybe you completed the quest and you just need to turn in it?
A screenshot would be helpful.

**Comment by Lheana** [comment]
Also please read the quest, it clearly says what you are meant to do: Take the Blood Tome from the Kulian Librarian

**Comment by FixitFastah** [comment]
I have read the quest, I have miss read it too. I thought it's inside the tower(as on live, as shown on screen the book is still there), but it's near the tower. And yes there is a blood Librarian nearby now I need to find a way out of this tower. Sorry to bother you, but your quest descriptions are mostly not that accurate(for instance there is no Mob named Kulian Librarian but Bloody Librarian) and my miss reading it made it worse. Finished and closed.
![glubz_047](https://user-images.githubusercontent.com/45132446/48946882-6f068600-ef2f-11e8-9489-c0992ea8b68d.jpg)

**Comment by Lheana** [comment]
Tip: To leave this tower, there are Coil Ropes that will port you out of the tower.

**Comment by FixitFastah** [comment]
Thanks, but I jumped ><
