### ISSUE TITLE
[Ability][Runepriest]Rune of Fortune vs Rune of Striking damage value

### ISSUE THREAD

**Issue by voina817** [WarEmu/WarBugs#12696]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Rune of Striking damage is higher than Rune of Fortune?
or is tooltip wrong? 

Steps to reproduce the problem:

if tooltip is right, I think Rune of Fortune deals more damage than Rune of Striking.

Screenshots/Videos or archive.org evidences:
![runepriestability](https://user-images.githubusercontent.com/22410215/48967953-81fe8080-f02b-11e8-8b33-2d0fbf7385b1.png)
![runepriestability1](https://user-images.githubusercontent.com/22410215/48967955-888cf800-f02b-11e8-8204-1890ee0da805.png)
![runeoffortunedmg](https://user-images.githubusercontent.com/22410215/48967957-8e82d900-f02b-11e8-9d8a-7bb8805b160a.png)
![runeofstrikingdmg](https://user-images.githubusercontent.com/22410215/48967959-92166000-f02b-11e8-8a1d-c30e6bbc3ba0.png)

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 03.08.2019
