### ISSUE TITLE
Duplication of Subjugator Items

### ISSUE THREAD

**Issue by Folgrimma** [WarEmu/WarBugs#12698]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Expected Behavior: Exchange the Subjugator item in bag for the other desired item. - -  
Actual Behavior: Was able to duplicate items when exchanging. (Originally I had only the 1handed weapon, and exchanged it for the 2 handed.)

Steps to reproduce the problem:
Exchange once for the item. Then proceed to Exchange that item again for another. Ended up with both items without the cost of losing one.

Screenshots/Videos or archive.org evidences:

![desktop screenshot 2018 11 24 - 07 12 36 24](https://user-images.githubusercontent.com/40577289/48969201-b2590700-efb8-11e8-8728-ab23e8cb40fc.png)
![desktop screenshot 2018 11 24 - 07 12 41 76](https://user-images.githubusercontent.com/40577289/48969204-b553f780-efb8-11e8-8be7-81138a434026.png)
![desktop screenshot 2018 11 24 - 07 34 40 24](https://user-images.githubusercontent.com/40577289/48969423-855a2380-efbb-11e8-9f07-cd2a842944cd.png)

**Comment by Folgrimma** [comment]
@MaxHayman it was the subjugator exchange vendor/ I wouldn't try it as its pretty much a duplication of items.

**Comment by Folgrimma** [comment]
I forgot to post another picture i'll edit it

**Comment by Folgrimma** [comment]
> Am I missing something
> https://www.dropbox.com/s/hpcz5ocpvcxejjk/2018-11-24_17-22-08.mp4?dl=0

No its about the same as I did, Not sure how I managed to bug it out exactly.

**Comment by Kaelang** [comment]
If this issue persists on the live environment, please re-open this issue - as this looks to have been fixed in recent patches.
