### ISSUE TITLE
[Dungeon] you cant go in dungeon or final boss chamber with different lockouts

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#12694]
i was in party with blackguard. I have lockouts on left and mid wings. BG has a lockout just on mid wing bosses. And we couldnt go in one instance toghether to run right wing and kill right wing final boss.  i got the message "Your instance lockout doesnt match the instance you are trying to enter"
my screenshot:
<img src="https://monosnap.com/image/MVStI3uVtC3uueAZmaz7NwUmjHBcbp.png">
BG:
<img src="https://monosnap.com/image/G0bvU6SQUO5V4VmoaBT58m4dYGRP13.png">

**Comment by sioding** [comment]
Can you please test it again to make sure the latest patch  didn´t fixed it?

**Comment by grunbag** [comment]
Who were the party leader ?

**Comment by Nfkillz** [comment]
i was in both cases (sh Apache)

**Comment by Nfkillz** [comment]
i think it was fixed with new lockout system
