### ISSUE TITLE
Quest : Defend Harvest Shrine!

### ISSUE THREAD

**Issue by loonbg** [WarEmu/WarBugs#127]
Now when you kill player will detect it

`UPDATE quests_objectives SET Entry =49802,ObjType = 5,ObjCount = 10,Description = 'Defend against Enemy Players',ObjID = 16935828 , Quests_Objectives_ID = UUID() WHERE Guid=4809;`

![tester_001](https://cloud.githubusercontent.com/assets/7444156/2939054/29001812-d934-11e3-8b8e-10f7e51c766a.jpg)

**Comment by Reggaewaldo** [comment]
Unsure if the area is correct for this and other kill quests in general. I do not have time to login and check now. Can anyone confirm ?

**Comment by Evildoor** [comment]
Closing this since everything is fixed apart from area detection, which is impossible for now.
