### ISSUE TITLE
Empowered Transfer tactic doesn't influence Consume Essence

### ISSUE THREAD

**Issue by Culdu** [WarEmu/WarBugs#12700]
Expected behavior and actual behavior:

The Tactic Empowered Transfer should improve the healing output of Consume Essence, but doesn't influence it at all.

Steps to reproduce the problem:

Use Style with and without tactic

Screenshots/Videos or archive.org evidences:
![empoweredtransfer](https://user-images.githubusercontent.com/14928735/48969685-5fa43d00-f002-11e8-800e-bdd560a3144b.jpg)

after the invaldi target part starts the attack with slotted tactic

**Comment by Rydiak** [comment]
Just for comparison's sake, I tested Grace of Sigmar with Sigmar's Radiance and it *does* work, so this seems to affect DoKs only.

**Comment by sioding** [comment]
fixed with patch from 1.12.2018
