### ISSUE TITLE
[Tooltip] WP - Prayer of Righteousness has deprecated speedboost text

### ISSUE THREAD

**Issue by Rydiak** [WarEmu/WarBugs#12702]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Prayer of Righteousness has the test text for the 20% speedboost still on the tooltip, which is now deprecated.

Steps to reproduce the problem:
View Prayer of Righteousness tooltip.

Screenshots/Videos or archive.org evidences:
![rydiak_164](https://user-images.githubusercontent.com/15963532/48971154-c9f5b700-efdb-11e8-9535-179c8abdd1a2.jpg)

**Comment by sioding** [comment]
fixed with patch from 1.12.2018
