### ISSUE TITLE
Change Oppressor Emblems to Conquror Emblems

### ISSUE THREAD

**Issue by Frostlatte** [WarEmu/WarBugs#12704]
In the Patchnote you announced a Changerate from Oppressor Emblems to Conqueror Emblems of 1 to 5.

So i changed my 29 Oppressor for the Box of Conqueror Emblems an get only a Change of 1:1 what wasnt proclaimed in the Patchnotes :-/   

With this Changerate i didnt change my Opp. Emblems... feels like a bit of decieving 

Greetings

Luthmoor

**Comment by sioding** [comment]
I do not see anything about a conversion rate in the patchnotes - anyway - this is the wrong place to discuss it. Please use our forum for that.
