### ISSUE TITLE
[Witch Hunter][Tactique][Seeker's Triumph]

### ISSUE THREAD

**Issue by Layinolias** [WarEmu/WarBugs#1270]
The Seeker's Triumph Tactique do not work's.
Effect of this tactique :
( Seeker's Balde ignore 50% of the target's armor ans cd -5s)
For the 50% i don't  really no but the the 5s less on the CD that doesn't works.

**Comment by milosxe** [comment]
Confirmed. From testing on NPCs I don't think that this tactic works at all (no armor ignore and no cd reduction).
Also 
![shh_000_cr](https://cloud.githubusercontent.com/assets/13332067/9976088/711882cc-5ed7-11e5-8424-bb6cbd92b334.jpg)
