### ISSUE TITLE
WP Block Rate

### ISSUE THREAD

**Issue by Frostlatte** [WarEmu/WarBugs#12703]
IThe Patchnote said that the shields get ca 20% Blockrate of Tanks... so most of shields have about 70 - 77 Blrockrate...

...but the 20% are on the Blockcalculation too!

So with a 77 Blockrate you should have a chance to Block of: 4,4 % 

If you equip the Shield you only get a Chance to Block of 0,9 (0,88%) = 20% of 4,4 so you reduce the Blocking ability twice -80% Blockrate +  -80% Chance to Block.... what makes a shield closly useless.

Hope you will fix this..

Link Tanking Calc with 77 Blockrate
https://tools.idrinth.de/tank/?dN=0&a0l=40&d0l=40&d0a=0&d0pr=0&d0cr=0&d0sr=0&d0er=0&d0i=1&d0ccr=0&d0bv=77&d0bm=0&d0ws=0&d0pm=0

Greetings Luthmoor

**Comment by Rydiak** [comment]
![rydiak_167](https://user-images.githubusercontent.com/15963532/48971338-c3683f00-efdd-11e8-809c-16802fb086a1.jpg)

Getstats is showing me with a 0+2% (from Buckler of the Smuggler) block chance.

**Comment by wargrimnir** [comment]
This is intended, and we're keeping an eye on how it works out with the various other ways you can stack block.
