### ISSUE TITLE
[Function] WP Tactic - Grace of Sigmar is not buffing Divine Strike

### ISSUE THREAD

**Issue by Rydiak** [WarEmu/WarBugs#12706]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Tactic Grace of Sigmar is not currently buffing Divine Strike in any fashion, though this may just be a tooltip error that includes Divine Strike in the tactic because Divine Strike has no base heal, and its leech heal is 100% (versus the tactic which increases Sigmar's Radiance leech to 75%).

Steps to reproduce the problem:
Slot tactic Grace of Sigmar and use Divine Strike.  Compare to Divine Strike without Grace of Sigmar slotted.

Screenshots/Videos or archive.org evidences:
![rydiak_168](https://user-images.githubusercontent.com/15963532/48971461-a2085280-efdf-11e8-937a-18d1ee6a6d8a.jpg)  - Divine Strike without Grace of Sigmar (hits for 351, heals for 351)

![rydiak_169](https://user-images.githubusercontent.com/15963532/48971473-d0862d80-efdf-11e8-9bcb-44ea293cb444.jpg) - Divine Strike with Grace of Sigmar (hits for 351, heals for 351)

**Comment by Rydiak** [comment]
Just noticed that my bugreport here is a WP mirror of the same issue affecting DoKs: https://github.com/WarEmu/WarBugs/issues/12700

**Comment by Torquemadra** [comment]
Its a tooltip error at this point

**Comment by sioding** [comment]
fixed with patch from 1.12.2018
