### ISSUE TITLE
[Tooltip] WP - Tactic - Intimidating Repent still references Orison of Grace

### ISSUE THREAD

**Issue by Rydiak** [WarEmu/WarBugs#12701]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Post 11/24/18 patch, all other references to the "Orison" system for Warrior Priests have been removed except for Intimidating Repent, which still references Orison of Grace.

Steps to reproduce the problem:
View the tooltip for tactic Intimidating Repent.

Screenshots/Videos or archive.org evidences:
![rydiak_162](https://user-images.githubusercontent.com/15963532/48970846-0c68c500-efd7-11e8-868b-38dc9794f8e2.jpg)

**Comment by sioding** [comment]
fixed with patch from 1.12.2018
