### ISSUE TITLE
Onslaught BW Boots with +range power

### ISSUE THREAD

**Issue by Shaerazade** [WarEmu/WarBugs#12707]
Please can you fix Onslaugh BW Boots,

i don't think the '+18 Ranged power' was expected
+ there is no INT on this : /

Expected behavior and actual behavior:

Steps to reproduce the problem:
ReEdit needed / Fix stats

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/44240445/48972293-96407e80-f027-11e8-923c-3232217de43c.png)

**Comment by wargrimnir** [comment]
Fixed, along with magus/sorc variants. Ready for next hotfix push.

**Comment by sioding** [comment]
fixed with patch from 1.12.2018
