### ISSUE TITLE
Disappearing BB/BE Bosses

### ISSUE THREAD

**Issue by Iamwithstupid** [WarEmu/WarBugs#12710]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Bosses in BE/BB randomly disappear after a wipe. Happened to Barakus in BE and Cauldron Boss in BB.
Have tabed Barakus somewhere behind the wall outside of dungeon. Cauldron boss was nowhere found. Reforming party, reentering did not fix the issue.

Steps to reproduce the problem:
cant know.

Screenshots/Videos or archive.org evidences:
![untitled](https://user-images.githubusercontent.com/36380568/48973645-74a5be00-f04c-11e8-8e89-03dba2951cfb.png)

**Comment by grunbag** [comment]
It’s fixed
