### ISSUE TITLE
Empty Heart

### ISSUE THREAD

**Issue by Iamwithstupid** [WarEmu/WarBugs#12711]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Item against Barakus in BE - Empty Heart is 1 hour cooldown which doesnt even show.

Steps to reproduce the problem:
fix cooldown

Screenshots/Videos or archive.org evidences:

**Comment by grunbag** [comment]
reduced to 5 min cd
