### ISSUE TITLE
Black Orc Slog pq froze at 5/30 killed

### ISSUE THREAD

**Issue by Beerburps** [WarEmu/WarBugs#12717]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
The dwarf chap 14 pq "black orc slog" has frozen up on stage 1 at 5/30 orcs killed.  Additional kills neither advance the counter nor reward influence.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Thanks for the report but this can only be fixed with a server restart cause we do not reset PQ´s.
