### ISSUE TITLE
Chosen abilites moving around

### ISSUE THREAD

**Issue by Gatoka** [WarEmu/WarBugs#1271]
Hello, my name is Gatoka and that is my character name in game. The issue that I have been experiencing on every login is that my 1 and 2 abilities change from what I had them when I started playing and also my 0,-, and = button. This happened both with running just the basic mod config with game and enabling the mods that are set as extras with the game. I have them locked and when it is unlocked. Spoke with another Chosen having the same issue and even seemed like another class was having similar issues. Please feel free to message me if you have any further questions. Thanks!

**Comment by Evildoor** [comment]
Does this problem still persists? It was a common issue weeks ago, then the devs implemented some fixes and it ceased for the most part, although i remember running into it once.

**Comment by Evildoor** [comment]
The problem indeed persists, run into it several more times. I will use https://github.com/WarEmu/WarBugs/issues/1488 as a main ticket for this, since i've already made some explanations here.
