### ISSUE TITLE
Squig Herder tactic bug need fixing & other abilities

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#12715]
Hello
First, I would like to thank you for keeping this game alive, I know many people share the same expericne& feeling with me and today I would like to report bugs for Squig Herder class : 

1. Tactics:  [ Clever Stabbin' ]: 

it says all of your Path of Big Stabbin' abilities cost 35% fewer action points. but when I checked my spec line trees I saw 3 paths and these paths are Path of Big Shootin' , Path of Bouncing , Path of Quick Shootin'.
there is no Path of Big Stabbin'

![image](https://user-images.githubusercontent.com/42385505/48981793-20055000-f0eb-11e8-9914-2502aba1dd1d.png)

![image](https://user-images.githubusercontent.com/42385505/48981796-25fb3100-f0eb-11e8-8d3c-44ff2373dd5f.png)

2. Abilities : [ Taste Like Chicken ] : 
it says you eat your squig, gaining 393 health for the next 10 second. the next different squig other than the one that was just eaten will be summoned instantly I tried this ability a lot  in ORVR, SC`s , and while leveling when the pet dies nothing get summoned and when I tried to summon other pet it wasn't instant as said there was a casting time and it can be interrupted

![image](https://user-images.githubusercontent.com/42385505/48981799-357a7a00-f0eb-11e8-8b13-47fe7ea07f15.png)

3. Abilities : [ Farty Squig ] : 
it says you cause your pet to explode, dealing 374 damage to enemies within 30 feet. for the next 10 seconds, the next different squig other than the one that just exploded will be summoned instantly.

this issue is the same as the above ability, I tried it a lot  and nothing is getting summoned instantly there is always a cast time and it can be interrupted 

![image](https://user-images.githubusercontent.com/42385505/48981802-432fff80-f0eb-11e8-922d-74e94b3dfd72.png)

4 Squig armor : 
if I am in SC with squig armor ability and the SC is done after the loading screen I get back with no squig armor on while all my bar is changed to the abilities for squig armor I have to turn on squig armor and turn it off every time to fix this issue

this is what i found out am new to this class and been leveling it for the past days 
 thank you for making this game alive  and people like me are enjoying playing it

5 Summoning pet: 

the cast is 1 sec and when the cast is complete there is a 1-sec delay for animation  which make it 2 sec and if I moved pet get unsummoned 

Regards
Yakyaky Squig Herder

**Comment by sioding** [comment]
Hey - thanks for your first report. 3 from your 4 issues are already reported. Please follow the rules for the bugtracker, which can be found here: https://github.com/WarEmu/WarBugs
Especially the last rule is important: 
*One issue per ticket
Only report one issue per ticket as multiple issues within one ticket is harder to track and harder to address.

**Comment by Tazo83** [comment]
[img]https://i.imgur.com/4zVEzzP.jpg[/img]

> Hey - thanks for your first report. 3 from your 4 issues are already reported. Please follow the rules for the bugtracker, which can be found here: https://github.com/WarEmu/WarBugs
> Especially the last rule is important:
> *One issue per ticket
> Only report one issue per ticket as multiple issues within one ticket is harder to track and harder to address.

well I didn't know I searched and couldn't find any, am new to this bug tracking reports I did added another one on the same post should I make a new one for it  or is fine 

for future reports, I will make sure its 1 issue per a ticket.

thank you
