### ISSUE TITLE
High Pass Savage Skulltaker

### ISSUE THREAD

**Issue by Nurgleburgle** [WarEmu/WarBugs#12714]
There's a Savage Skulltaker just standing on top of a tent in the first Khorne camp at High Pass. This isn't an important issue but get it when you have the chance.
![high pass](https://user-images.githubusercontent.com/45332777/48979547-864d8c80-f071-11e8-8478-f4a6e2ac385b.png)

**Comment by sioding** [comment]
fixed with patch from 1.12.2018
