### ISSUE TITLE
Marauder damage dont scale with strength increase

### ISSUE THREAD

**Issue by DUSKANGEL** [WarEmu/WarBugs#1272]
Hi, i noticed that my marauder do very low damage to enemy players, i run some tests with switching tactics removing strength rings and i found that my skills do same damage with 500 strength or 633. While ability damage show me  bigger numbers on character stats, in real there is no difference. (Tested all  hits on NPS in IC with different skills.)

**Comment by DUSKANGEL** [comment]
All fixed after i got my mara to lvl 24

**Comment by Evildoor** [comment]
Seems to be the part of general problem, which i described in
https://github.com/WarEmu/WarBugs/issues/1007
Closing this.
