### ISSUE TITLE
[Scenario] Black Crag Keep : flag missing

### ISSUE THREAD

**Issue by freezeheart** [WarEmu/WarBugs#12722]
Hi,
in scenario Black Crag Keep, the flags (left and right) are missing.
I did not see the middle one.
![bug_blackcragflag1](https://user-images.githubusercontent.com/43251697/49016389-3d3b2c80-f186-11e8-9e42-3e4226156c64.png)
et
![bug_blackcragflag2](https://user-images.githubusercontent.com/43251697/49016449-6c519e00-f186-11e8-8f35-4c07dbd73a0d.png)

**Comment by Natherul** [comment]
will be fixed on next server restart

**Comment by Kaelang** [comment]
Closed as fixed.
