### ISSUE TITLE
Chicken can use cannons

### ISSUE THREAD

**Issue by SecretsOTheP** [WarEmu/WarBugs#12724]
Expected: Chickened players are able to interact with, but not fire siege weaponry. (ie; near Nordland WC)
Actual: Chickens are able to interact with, and able to fire siege weaponry. (ie; near Nordland WC)

Steps to reproduce the problem: 
Enter a T1 RvR zone with a level 16+ player
Enter a cannon or artillery near the warcamp
Observe that the chickened player can fire the cannon or artillery

Screenshots/Videos or archive.org evidences: N/A

**Comment by sioding** [comment]
fixed with patch from 30.12.2018
