### ISSUE TITLE
Dark Elf Ch 19 - Caladain's Furnace PQ stage 2 misspelling

### ISSUE THREAD

**Issue by OneRabidSquig** [WarEmu/WarBugs#12729]
![barktoof_003](https://user-images.githubusercontent.com/40903608/49055182-552da300-f1bc-11e8-8729-c8b7603da8e6.jpg) 
Stage 2 of this PQ has a small misspelling in the objective, it says Flame of Vault but the actual object is Flame of Vaul.

**Comment by Lheana** [comment]
But you have to topple 2 Flames of Vault, that's why there is a -s. It is like when you have to kill several Elves, the objective is Elves as there are more than one to kill.

**Comment by OneRabidSquig** [comment]
I'm not referencing the Flames vs Flame part, I understand that. I'm talking about Vault vs Vaul, one dwarfs put treasure in and the other is an elven god. I should've highlighted the extra T more in the original, sorry about that.

**Comment by sioding** [comment]
fixed with patch from 1.12.2018
