### ISSUE TITLE
Raze (morale 2 , didn't check for all morales) can't cancel a flag cap in sc

### ISSUE THREAD

**Issue by zageen** [WarEmu/WarBugs#12723]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Expected behiavor :
the damage of raze should cancel the tag (need confirmation for all Morales), can't test in real conditions (even kotbs and chosen aura cancel )

Actual behavior : 
raze dmg don't cancel the tag.

Steps to reproduce the problem:

Get to Black fire bassin or kaine embrace , grind morales , ennemies take the flag , raze , ennemies still tagging without cancel.

Screenshots/Videos or archive.org evidences:

(to be updated)

**Comment by sioding** [comment]
fixed with patch from 15.12.2018
