### ISSUE TITLE
[RP] Rune of Immolation has wrong damage type

### ISSUE THREAD

**Issue by AxelF17** [WarEmu/WarBugs#12734]
Rune Priest's Rune of Immolation (main DoT) is incorrectly classified as 'damaging' rather 'ailment'. This means it can be cleansed by all healers rather than just DoK and Shaman.

All other RP DoTs are ailments (Rune of Cleaving, Rune of Iron, Rune of Fate etc), and the corresponding Zealot DoT (Warp Reality) is a Hex, as are all other Zealot DoTs.

**Comment by Torquemadra** [comment]
What you mean is it CANT be cleansed by any healer because its not typed.

**Comment by AxelF17** [comment]
Aah ok, as you were then - nothing to see here! ;)

**Comment by sioding** [comment]
Fixed with patch from 02.03.2019
