### ISSUE TITLE
T4 loot bag dissapearence's

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#12730]
- I won a Golden loot bag from an rvr zone, and never received it after flying to another zone, I was told to wait until server restart because it got stuck in the mail, I couldn't find any other reports of this problem.

Steps to reproduce the problem:
Win a loot bag in rvr zone, fly to another zone before the bag is mailed to you

Screenshots/Videos or archive.org evidences:
I have no screenshots, but heard this is a common problem.

**Comment by sioding** [comment]
We have a forum thread for this, but i am really sure you will get your bag with the next patch. A simple restart won´t help at all here. The main prolem for this is that we can not reproduce it. I know your pain - especially when its a golden bag.
