### ISSUE TITLE
sentinel quest have 2 boots for SM

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#12731]
Expected behavior and actual behavior:
quest name ' the threat from tobias the fallen' have 2 boots as reward for SM.
not sure if it really gives 2.

Screenshots/Videos or archive.org evidences:

![sentinel_quest](https://user-images.githubusercontent.com/19988772/49062207-98d4eb00-f256-11e8-95e0-eb46ebdfce90.jpg)

**Comment by grunbag** [comment]
fixed at next patch
