### ISSUE TITLE
Dok [Devour Essence]

### ISSUE THREAD

**Issue by Vladvon** [WarEmu/WarBugs#12732]
There are times when can not use it if select an Friendly,Object

message:Invalid Target
I could not recover several times and died....

]Shining Banner selected]
![vlodvan_029](https://user-images.githubusercontent.com/42826843/49067585-d55d1280-f267-11e8-839d-2850b6e3e750.jpg)

Movie:
https://www.youtube.com/watch?v=T8PIVhnRX6g&t=0s&index=3&list=PLAzdW_QvJOkmB-cdaAxmnC8Jilu0jk7eo

**Comment by grunbag** [comment]
Its working on Player ally , not friendly object or friendly NPC . The massage : invalid target is correct .
