### ISSUE TITLE
Bilerot Plaguebeast Blocking the cauldron and making it unclickable

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#12735]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

after killing the monster the body should disappear but it's not and the corpse of the monster is blocking the cauldron which makes it unclickable and caused the group to die

Steps to reproduce the problem:

killing the monster in the same location that he is standing at or killing the monster near the end of the cave where the cauldron Spawn

Screenshots/Videos or archive.org evidences:
 
![image](https://user-images.githubusercontent.com/42385505/49096669-12330480-f27c-11e8-8966-b3f40cfbe229.png)

![image](https://user-images.githubusercontent.com/42385505/49096834-7786f580-f27c-11e8-8821-73827afa2733.png)
****

**Comment by Hargrim** [comment]
Thanks for report.

Fixed in next server patch, NPC will disappear after 100ms from the moment of death.
