### ISSUE TITLE
[WH/WE] Close Combat tactic

### ISSUE THREAD

**Issue by XmatXergon** [WarEmu/WarBugs#12748]
Expected behavior and actual behavior:
Close Combat tactic should get triggered by any direct melee attack but its not getting triggered by AutoAttacks, abilities like RazorStrike/Slice and SilenceTheHeretic/ThroatSlitter while you hit target that is in MeleeRange 5ft away.

Steps to reproduce the problem:
Hit target dummy with AutoAttacks, abilities like RazorStrike/Slice and SilenceTheHeretic/ThroatSlitter.

Screenshots/Videos or archive.org evidences:
Didn't record but can provide if necessary.

![closecombat](https://user-images.githubusercontent.com/37849311/49273461-4e7d8500-f475-11e8-8bb4-fd68549d04da.png)

**Comment by XmatXergon** [comment]
https://youtu.be/svo-v-BkKTs

**Comment by grunbag** [comment]
AA don't trigger it, fixed other abilities

**Comment by sioding** [comment]
fixed with patch from 13.07.2019
