### ISSUE TITLE
Guild for character works really strange

### ISSUE THREAD

**Issue by exotlv** [WarEmu/WarBugs#12744]
Info: When I logged in with my character. I see that **Not in a guild.**. Also I see Guild message in chat. Weird.
After 10s, Guild updated and now shown that I'm in guild and message: Your Guild Has earned rank 40!
Also, when I change zone all the time I got this message: Your Guild Has earned rank 40!

Expected behavior and actual behavior:
Character shown in guild and message: Your Guild Has earned rank 40! - not appear

Steps to reproduce the problem:
Login as user, check Guild modal popup. 
Change zone and check for message

Screenshots/Videos or archive.org evidences:

![erihon_037](https://user-images.githubusercontent.com/8436809/49215934-93041480-f3d2-11e8-88b3-8341cad59640.jpg)
![erihon_038](https://user-images.githubusercontent.com/8436809/49215935-939cab00-f3d2-11e8-8e00-fd082115abab.jpg)

**Comment by sioding** [comment]
Thanks for the report, but this is intended. This workaround fixed login issues for a lot of players.
