### ISSUE TITLE
Squiq Herder Moral 4 (Cooldown Problem)

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#12741]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

60 second cooldown is expected when you use it  but actual behavior is 5 minute cooldown 

![image](https://user-images.githubusercontent.com/42385505/49118391-16c7df00-f2b5-11e8-8d14-e30d26f5a6f3.png)
****
Steps to reproduce the problem:

just use the moral 4 and the cooldown is 5 minute and not 60 second

Screenshots/Videos or archive.org evidences:

![image](https://user-images.githubusercontent.com/42385505/49118494-7f16c080-f2b5-11e8-83be-cd3608274c14.png)

**Comment by Iamwithstupid** [comment]
it was changed to 5 min when moved to core, thats intended

**Comment by Tazo83** [comment]
since am new to this class and am testing many abilities to see how do they work ... I didn't know that it was changed to 5 min, in that case then tooltip needs to be fixed and changed from saying 60s to 5 minute 
so anyone who plays the class won't get a misleading information, in my case I was in the middle of the fight in the Open RVR and I used this moral and then I was stuck 5 minutes without being able to use any moral

**Comment by grunbag** [comment]
fixed already
