### ISSUE TITLE
"Satchel of Conqueror's Emblems"

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#12740]
Expected behavior and actual behavior:
Hello, I apologize if this has been brought up to you already, I couldn't find any other reports of it, the satchel of conqueror emblem(s) is only converting one oppressor emblem into 1 conqueror emblem, when usually a satchel holds 5 I thought, if its working as intended I apologize but I feel as if though they satchel should just be renamed from "Satchel of Conqueror's Emblems" to "Conqueror emblem" as to not mislead people like me.

Steps to reproduce the problem:
buy and convert the "Satchel of Conqueror's Emblems".

**Comment by sioding** [comment]
Hey - thanks for the report. It is definitly working as intended - the plan is to bring in a 5:1 conversion when new scenario weapons are out. So the satchel is incorrect for the next few weeks - but OK after the weapon release.
