### ISSUE TITLE
character create

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#12746]
if you do a character create, then you decide to cancel it and not make the character, you cannot play any of your character's until you relaunch the game
Expected behavior and actual behavior:
when you hit play it should log your character in, but the button just becomes disabled.

Steps to reproduce the problem:
click create a character, cancel out of it before finishing the character creation process, then click play on one of your characters, button should become disabled and the only button that will work is quit game.

Screenshots/Videos or archive.org evidences:

![image](https://user-images.githubusercontent.com/44329952/49246872-846e2b00-f3db-11e8-9b52-bb54f3d7463b.png)

**Comment by Kaelang** [comment]
This no longer happens - tested and was able to login fine.
