### ISSUE TITLE
Sigmars Crypt Arch Lector

### ISSUE THREAD

**Issue by Trikpriest** [WarEmu/WarBugs#12747]
Final boss in Sigmars Crypt Arch Lector Ver and Zak dont reset on wipe, group was stuck outside with the red walls over doors, tried to zone out and back in but get the message "there is an encounter in progress you cannot enter" while whole group is outside

**Comment by grunbag** [comment]
Don’t release one by one , wait for everyone and do it all together until we can find a better solution

**Comment by grunbag** [comment]
Fixed a while ago
