### ISSUE TITLE
[Quest] A Head Above the Rest (Talabecland, destro) Quest marker switched

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12757]
The quest markers for the objectives are at the wrong positions.

![a head above the rest](https://user-images.githubusercontent.com/30193675/49292288-26aa1380-f4ad-11e8-9c3b-62d1214ed0b7.jpg)

**Comment by sioding** [comment]
fixed with patch from 15.12.2018

**Comment by SODIX** [comment]
Text should be fixed, its' not in Blood Steppes High Pass, but Riverholm Talabec.
