### ISSUE TITLE
Healers get stuck in animation when healing NPCs.

### ISSUE THREAD

**Issue by Rilos** [WarEmu/WarBugs#1275]
Warrior Priests get stuck in healing animation when healing NPCs.

**Comment by Evildoor** [comment]
Not exclusive to WP. I do believe that on live it was impossible to heal NPCs (besides keep lords and other similar ones), so your cast should be cancelled.

**Comment by Milkyn** [comment]
This little fix should be a temp. solution.

**Comment by Luth-RoR** [comment]
Fixed.
