### ISSUE TITLE
[Quest] Cold Hard Steel (Talabecland, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12753]
The Quest marker for the objective "Crafted Steel Sword" is missing.

![cold hard steel](https://user-images.githubusercontent.com/30193675/49291861-e007e980-f4ab-11e8-8ca7-56c8693d8a14.jpg)

**Comment by sioding** [comment]
fixed with patch from 15.12.2018
