### ISSUE TITLE
[Quest] Forgiveness is Divine (Talabecland, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12758]
The quest marker for the objective "Kill Witch Hunter Interrogator" is missing.

![forgiveness is divine](https://user-images.githubusercontent.com/30193675/49292405-712b9000-f4ad-11e8-96f6-19079692c2ed.jpg)

**Comment by sioding** [comment]
fixed with patch from 15.12.2018
