### ISSUE TITLE
[Quest] The Bloody Maul (Troll Country, destro) Quest marker mising

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12750]
The quest marker for the objective "Kill Brigant Ambusher" is missing.

![the bloody maul](https://user-images.githubusercontent.com/30193675/49291435-9965bf80-f4aa-11e8-9b22-7d1a3a0a9f20.jpg)

**Comment by sioding** [comment]
fixed with patch from 15.12.2018
