### ISSUE TITLE
[Quest] Frothing at the Mouth (Troll Country, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12751]
The quest marker for the objective "Kill Ghourna'r" is missing.

![frothing at the mouth](https://user-images.githubusercontent.com/30193675/49291525-efd2fe00-f4aa-11e8-94a5-544f4c4cf29a.jpg)

**Comment by sioding** [comment]
fixed with patch from 15.12.2018
