### ISSUE TITLE
SH disarm doesn't work

### ISSUE THREAD

**Issue by Zzeppenn** [WarEmu/WarBugs#1276]
Sometimes it takes several attempts to even cast the ability successfully (buttonmashing), and when it finally does it won't disarm players.

**Comment by Renork** [comment]
Sounds very similar to the magus knockdown situation.

**Comment by magter3001** [comment]
Yeah, wasn't fixed in last update. Very frustrating as you said, buttonmashing doesn't help as it uses the cooldown but doesn't disarm the player. Even if you tell your pet to attack the player, the ability still won't go off to save your life.

**Comment by magter3001** [comment]
Anyone know of a work around to make disarm work? Really frustrating to not be able to use it when we should have the ability to.

**Comment by ozarmidrashim** [comment]
DT! incorrectly had a 5ft range for the buff to be applied to the SH.

Since DT! works by applying an event buff to the Squig which fires the disarm whenever the Squig deals direct damage, I'm assuming that the above was the issue.

**Comment by magter3001** [comment]
That actually might be it, the 5ft thing... Will test it later.

**Comment by Evildoor** [comment]
Seems to be fixed, i was disarmed by that at least once. Closing.
