### ISSUE TITLE
[Quest] A Claim to Power (Saphery, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12768]
The quest marker for the objective "Kill Windmare Unicorn" is missing.

![a claim to power](https://user-images.githubusercontent.com/30193675/49293575-d6cd4b80-f4b0-11e8-94f3-23343f031f4d.jpg)

**Comment by Lheana** [comment]
This quest and its quest line have been fully reworked, and quest markers, fixed

**Comment by sioding** [comment]
fixed with patch from 30.12.2018
