### ISSUE TITLE
SH set bonuses doesnt convert ballistic to strength

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#12776]
Expected behavior and actual behavior:
Squig herder set bonuses of ballistics isn't properly converting into strength as it should. 

Steps to reproduce the problem:
see the stats of strength and ballistics as you put on more set pieces.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Please add your testing screenshots.

**Comment by Xicoz** [comment]
I have none, it was discussed In advice channel today and someone requested that a bug report be filled out so I offered, my apologies.

**Comment by sioding** [comment]
Thank you for opening this report - but when other ppl discuss that - please encourage them to create that report. Without testing screens its not helpful for the devs. I close this one here.
