### ISSUE TITLE
WE bugg pet!

### ISSUE THREAD

**Issue by BFGka** [WarEmu/WarBugs#12779]
I have an invisible lion and he gives me all the buffs. plz fix it. tyvm

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/45288988/49326246-2a9f6980-f571-11e8-9edb-318314c6da76.png)

**Comment by sioding** [comment]
Can you please some more informations like when did the issue appears and what did you do? A simple screen with a "please fix it" isn´t helpful and the devs need a chane to reproduce the problem to fix it.

**Comment by BFGka** [comment]
np!-summon a lion and use one of its three characters, in my case it is + 5%
 crit damage, tactic+76strength and fly over to the rvr zone. he disappears and the buffs remain and it turns out as if he is with you only invisible and immortal..

**Comment by grunbag** [comment]
Max fixed it already
