### ISSUE TITLE
Name change / more than 10 chracters

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#12772]
Expected behavior and actual behavior:
You can initially create a character with more than 10letters, but if you do a name change it doesn't allow more than 10. It should allow you to have the same length name as if you just created the character.

Steps to reproduce the problem:
Name change to something more than 10 characters long.

Screenshots/Videos or archive.org evidences:

**Comment by Natherul** [comment]
inconsistency will be addressed on next update

**Comment by MaxHayman** [comment]
@sioding this was fixed in a hotpatch

**Comment by sioding** [comment]
Thanks @MaxHayman  aaand close.
Fixed in Hotfix from 02.12.2018
