### ISSUE TITLE
Squig Herder Vanquisher Boots named incorrectly

### ISSUE THREAD

**Issue by Condemer** [WarEmu/WarBugs#12774]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

![image](https://user-images.githubusercontent.com/45501430/49320847-97f7bf80-f4c9-11e8-90ee-56dbdba4df26.png)

**Comment by sioding** [comment]
fixed with patch from 08.12.2018
