### ISSUE TITLE
Item stays in Backpack after salvaging

### ISSUE THREAD

**Issue by Heyho18** [WarEmu/WarBugs#1278]
Hi,

today i traded with a guildmate a couple of items for salvaging.
One of them is now stuck in my backpack and can't be moved to another slot in my inventory. The Issue with that item is that it can be salvaged endlessly. It just won't dissappear.
Item name: Butcher's Keysash.
Char name: Threxx

I don't think it's a bug with the item.I reckon something went wrong during the trade. We couldn't reproduce it so i can't say what went wrong exactly.

**Comment by Evildoor** [comment]
This item is still in your inventory?

**Comment by Heyho18** [comment]
yes it's still in there.

**Comment by Kaelang** [comment]
Salvaged the item with no problems. Would likely need additional steps to replicate such issue. If this issue still persists, i.e. the item is still salvagable on the latest version of RoR without removing the item. Please re-open a new ticket.
