### ISSUE TITLE
WE Vanquisher set bonus not working properly

### ISSUE THREAD

**Issue by berkaykunut** [WarEmu/WarBugs#12785]
With WE Vanquisher set as 4th piece bonus "Vicious Strikes" i need to get 110 Weapon skill bonus from procs but if i have "pierce armor" abilitys' weapon skill buff on me this proc does nothing and my weapon skill stays the same.

**Comment by Torquemadra** [comment]
abilities dont stack, procs included, it will use the highest value.

**Comment by berkaykunut** [comment]
So whats the point of giving witch elves a proc they already have as an ability? WHs can full benefit from vanquisher sets.
