### ISSUE TITLE
new DoK skill "Blood of my Blood" 

### ISSUE THREAD

**Issue by Toppitop** [WarEmu/WarBugs#12782]
dat not work 
![pokuri_001](https://user-images.githubusercontent.com/33959177/49330421-68b38200-f59f-11e8-8dd2-2ce112cd95eb.jpg)

**Comment by Torquemadra** [comment]
you need to be flagged for rvr as well as your team mates, its a weird bug we are working on and effects a couple of other things

**Comment by Scophis** [comment]
Same for WP #12790

**Comment by dalen** [comment]
This was fixed awhile back actually
