### ISSUE TITLE
strange calculation of critic damage for wh

### ISSUE THREAD

**Issue by harkerkane** [WarEmu/WarBugs#12783]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
critic damage of razor strike or torment on wh should be double of damage with the tactic fanatical cleansing but sometimes the damage are way less than double. 

Steps to reproduce the problem:
make non critic and critic damage and compare the two numbers

Screenshots/Videos or archive.org evidences:

![harkerkane_002](https://user-images.githubusercontent.com/45519748/49331540-061ab000-f5b8-11e8-855a-74fa8123d1a6.jpg)
![harkerkane_000](https://user-images.githubusercontent.com/45519748/49331550-1df23400-f5b8-11e8-9369-d5b4d831f5cf.jpg)

**Comment by XmatXergon** [comment]
@harkerkane 
There is not enough data you could be affected by many thing like default or strong debuff or anything else...
Last time I checked on target dummies it was all fine always same critical damage.

**Comment by sioding** [comment]
Sorry but this report does not have enough data to let it through the qualitygate and directly to to the devs. We need more data than 3 hits per screenshot to investigate something like this. You are welcome to bring another report with more data and .getstats output and and and ... but i am sorry - for this report it´s a _no_
