### ISSUE TITLE
Dark Elves T4 Epic Quest The Ebon Flame STEP 13 bugged

### ISSUE THREAD

**Issue by deysawme** [WarEmu/WarBugs#12780]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:Clicking on Orb of Souls after killing Rianmmar Jadeheart to comblete objective.
There is no Orb of Souls in inventory before or after killing Rianmarr Jadeheart!

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:https://imgur.com/a/wlEFhI7

**Comment by Lheana** [comment]
When have you started the epic quest?

**Comment by deysawme** [comment]
i dont play a lot 4 days ago i think

**Comment by deysawme** [comment]
and i keep trying until today to make it work... nothing helps

**Comment by deysawme** [comment]
and quest is not posible to finish then for me?

**Comment by Lheana** [comment]
For now, no, will see for a fix

**Comment by sioding** [comment]
fixed with patch from 02.02.2019
