### ISSUE TITLE
Remaking character with same name

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#12787]
Expected behavior and actual behavior:
i managed to make a DoK with the name of "Dracula", (somehow that wasn't taken), then decided to delete him, and remake because I accidently made it a female DoK, but as I went to recreate the character it said name was already taken, then I proceeded to try and add "Dracula" to my friends list, and it popped up as no player found, I apologize if this is working as intended, but it seems that when a name is chosen, even if deleted stays in the database of names.

Steps to reproduce the problem:
make a character with the name (any name), delete that character, try to make another character with the exact same name.

Screenshots/Videos or archive.org evidences:
this is the only screenshot I could think of to take, its me screenshotting that there is no Dracula player found.

![image](https://user-images.githubusercontent.com/44329952/49336442-de334880-f5c7-11e8-91d9-fbce0ca0692f.png)

**Comment by sioding** [comment]
This isknown and intended. Characternames are cached and this cache will be purged when the next restart of the server is done. So whenever you delete a character you need to wait until the next patch to reuse that name.
