### ISSUE TITLE
T2 Greenskin Epic quest: Boss Huntin'

### ISSUE THREAD

**Issue by losvtranse** [WarEmu/WarBugs#12792]
The very first quest asks to kill 10 Hammerstriker Rangers, but killing any amount of them doesn't count for the quest. Me and my friend can confirm it. 
My journal:
![2018-12-03 00 53 53](https://user-images.githubusercontent.com/16538643/49345475-78fa5880-f696-11e8-92c8-38bb3ae5f3fd.png)
![2018-12-03 00 54 49](https://user-images.githubusercontent.com/16538643/49345477-7b5cb280-f696-11e8-9d0d-304dcc59cbe8.png)
My friend's journal:
![default](https://user-images.githubusercontent.com/16538643/49345504-db535900-f696-11e8-8700-b469d71a134d.png)

**Comment by losvtranse** [comment]
We discovered that they don't count towards the quest only in group - when we disbanded and killed some they did count and when we remade the party they stopped.

**Comment by wargrimnir** [comment]
This is related to powerleveling restrictions as discussed in Discord. Intended.
