### ISSUE TITLE
[Quest] The Ties that bind

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#12794]
Even as quest is checked highlighted are remains on map and you cannot give quest in.
![veszal_401](https://user-images.githubusercontent.com/42712833/49346205-d47d1400-f69f-11e8-86bb-bc4202883f0a.jpg)
![veszal_400](https://user-images.githubusercontent.com/42712833/49346206-d47d1400-f69f-11e8-83a8-042c09566a86.jpg)

**Comment by sioding** [comment]
fixed with patch from 30.12.2018
