### ISSUE TITLE
[Quest] A little compensation

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#12793]
The NPC mentioned in quest can't be found in highlighted area
![veszal_399](https://user-images.githubusercontent.com/42712833/49346132-dbefed80-f69e-11e8-997c-f5c637d2c353.jpg)
![veszal_398](https://user-images.githubusercontent.com/42712833/49346133-dbefed80-f69e-11e8-8020-80ed181375ac.jpg)

**Comment by sioding** [comment]
fixed with first patch of the year 2019 (05.01.2019)
