### ISSUE TITLE
T1 Black orc reward norsca

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#12791]
Expected behavior and actual behavior:
Both the "Festenplatz Pillager Boyz" Chain and "Fesentplatz Pillager Dark Band"  influence rewards for the Black Orc in T1 norsca RVR influence rewards have the exact same stats.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/44329952/49342401-a60c2400-f620-11e8-85d6-52b0517a0ec9.png)
![image](https://user-images.githubusercontent.com/44329952/49342410-b0c6b900-f620-11e8-976d-7eb98cb84f71.png)

**Comment by wargrimnir** [comment]
Dark Band is a BG accessory, probably missing class requirement so it shows up for anyone. Will check it.

**Comment by sioding** [comment]
fixed with patch from 08.12.2018
