### ISSUE TITLE
Gold bug

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#12799]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

reporting this on behalf of a friend this is what happened with him done a name change and reloaded ui
he spoke with gm & money got fixed anyway am just reporting the issue here

Steps to reproduce the problem:

name change then reloadui issue

Screenshots/Videos or archive.org evidences:

![image](https://user-images.githubusercontent.com/42385505/49376209-94597800-f717-11e8-83bb-c06b5d9d0603.png)

**Comment by wargrimnir** [comment]
So he didn't actually receive anything, he just got a corrupted packet and got nothing?

**Comment by Tazo83** [comment]
well I think ya he just told me the money is fixed and he already spoke to a GM in game

**Comment by sioding** [comment]
OK so - close.
