### ISSUE TITLE
[Quest] Forest Foe (Ostland, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12802]
The quest marker for the objective "Kill Branchwraith Ylis" is missing.

![forest foe](https://user-images.githubusercontent.com/30193675/49392499-e954b880-f72e-11e8-9af9-34f8f1f9f42a.jpg)

**Comment by Kabucoror** [comment]
fixed next patch

**Comment by sioding** [comment]
fixed with patch from 15.12.2018
