### ISSUE TITLE
[Quest] Setting the Trap (Ostland, destro) Quest marker mising

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12803]
The quest marker for the objective "Regimental Scouts" is missing.

![setting the trap](https://user-images.githubusercontent.com/30193675/49392641-549e8a80-f72f-11e8-8207-1e50e7428402.jpg)

**Comment by AmidalaEstellanor** [comment]
Felde refugees and Regimental Scouts are all together in the same zone,so in the same marker around the PQ

**Comment by Moragor** [comment]
Sure, but the marker disappears when the refuges are killed leaving no marker for the scouts. By the standards set by latest fixed and overhauled quest each objective gets its own marker, even if the overlay.

**Comment by Moragor** [comment]
This apparently has been fixed and rolled out, so the ticket can be closed.
![setting the trap_corrected](https://user-images.githubusercontent.com/30193675/50541358-7ced9d80-0ba4-11e9-859c-2f0951847dd0.jpg)

**Comment by sioding** [comment]
fixed with patch from 30.12.2018
