### ISSUE TITLE
City instances - Order - entering bug

### ISSUE THREAD

**Issue by Ondorie** [WarEmu/WarBugs#12800]
The portal to the instances won´t let me enter, even though I own the full redeye set, my tome has it registered.
It says, I do not meet the requirements for entering.
Also I have a negative (-8hours) lockout for a warp blade tunnle

**Comment by sioding** [comment]
Can you please add screens from your lockout tab? Thanks.

**Comment by Ondorie** [comment]
Lockout tab is fine now.
