### ISSUE TITLE
[Quest] Desire for Corruption (Ostland/Troll Country, destro) Quest marker missing/misplaced

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12805]
The quest marker for "Enemy Player" is at the location where "Find Rusted Chest" should be. "Enemy Player" can be achieved in the whole open RvR space.

On a side note: The quest is spread over three pages in the ToK, but page two is empty. Is this a problem I should report in the future? I know there are others like this.

![desire for corruption](https://user-images.githubusercontent.com/30193675/49393051-8532f400-f730-11e8-8ebb-b649b8508dbe.jpg)
![deire for corruption 2](https://user-images.githubusercontent.com/30193675/49393064-89f7a800-f730-11e8-8183-60317391f5de.jpg)

**Comment by Kabucoror** [comment]
will be fixed on next patch.

To your empty pages. I never noticed such a problem, maybe it's a settings thing.

**Comment by sioding** [comment]
fixed with patch from 15.12.2018
