### ISSUE TITLE
4th set bonus Vanquisher Shaman

### ISSUE THREAD

**Issue by NihilAbalham** [WarEmu/WarBugs#12807]
Hello, hello,

For Shaman, the 4th Vanquisher set bonus does not work, the buff never starts. His name is exuberance.

Have a good day ! Thank you !

**Comment by sioding** [comment]
Hey. Thanks for your report. Please add your testing screens or video for it.

**Comment by NihilAbalham** [comment]
[](https://www.youtube.com/watch?v=Wb2PDc6eUH4&feature=youtu.be)

**Comment by NihilAbalham** [comment]
https://www.youtube.com/watch?v=Wb2PDc6eUH4&feature=youtu.be

**Comment by Minipuce** [comment]
Hello.
Exuberance is not a buff because it is not something over time.
On a direct heal you have 10% chance to recover 35 AP.
So when you do a direct heal, your action point bar can up by 35 points. And that's all. Have an eye on it and you will see it. It is normal not to see a buff then.

**Comment by NihilAbalham** [comment]
Ohh, crap... Thanks Minipuce.

**Comment by sioding** [comment]
aaand close. Thanks @Minipuce
