### ISSUE TITLE
Lockouts not listed

### ISSUE THREAD

**Issue by Nefarian78** [WarEmu/WarBugs#12806]
Lockouts randomly stop being listed in the Lockout Tab. They still are present though.

Reloading the UI doesn't do anything. to make them appear again, logging out is required.

I don't know what is causing the bug or how to reproduce it. Nothing out of the ordinary happened to me in days. No CTDs or anything.

**Comment by sioding** [comment]
Did you tried the command ".lockout" ?

**Comment by Nefarian11** [comment]
> Did you tried the command ".lockout" ?

I tried it, after multiple people in my group said it did not work for them, and in fact, it didn't do anything.

**Comment by sioding** [comment]
Thanks for the reply.

**Comment by Kaelang** [comment]
.lockout is now working. Closing.
