### ISSUE TITLE
[Gunbad] 1st boss leftwing

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#12808]
As you have 2 bosses spawned at same time you have easy way to bug them:
1) you pull them with healer
2) tank pulls squig from you on the edge of reset zone
3) everyone who gets wyvern aggro runs to reset zone

Probable solution:
Make both bosses reset if one resets.
![image](https://user-images.githubusercontent.com/42712833/49464669-981af680-f80c-11e8-88c8-a07ecdc59ced.png)

**Comment by grunbag** [comment]
ok closing
