### ISSUE TITLE
SW: Redeye Set bonus

### ISSUE THREAD

**Issue by Siegureboy** [WarEmu/WarBugs#12819]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Auto attack speed increased, should show on paper doll 1.8; shows on paper doll 27.4
NOT sure if it is a display issue or actually not functioning in game. When hitting a target in Altdorf it seems to work as intended, but is not displaying correctly. Odd thing is, that the + 10% auto attack haste displays on character properly from the Onslaught gloves and the Conqueror shoulders.

Steps to reproduce the problem:

Equip enough Redeye pieces to achieve + 25 auto attack haste

Screenshots/Videos or archive.org evidences:

https://imgur.com/a/HayTfLM

**Comment by sioding** [comment]
Yes we have issues with the paperdoll - but as you already said it seems to work properly and your getstats autoput also show the correct stats. I will close this report here cause there is no issue with the set itself - its a paperdoll issue we already know. Anyhow - thanks for the report.
