### ISSUE TITLE
Zealot Redeye 5-Peice Bonus Not Working

### ISSUE THREAD

**Issue by wwright72** [WarEmu/WarBugs#12813]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
The 5-peice bonus is supposed to give 88 intelligence but it actually gives 8 intelligence.

Steps to reproduce the problem:
I screen-capped my ".getstats" with & without the redeye proc.

Screenshots/Videos or archive.org evidences:
Without
![without](https://user-images.githubusercontent.com/29286837/49547764-41172f00-f8a9-11e8-81ea-8fbba4722440.jpg)
With
![with](https://user-images.githubusercontent.com/29286837/49547770-43798900-f8a9-11e8-94f0-ce62fc15c850.png)

**Comment by wargrimnir** [comment]
This is normal. You probably had a buff or potion running that grants 80 INT which negates much of the proc bonus

**Comment by wargrimnir** [comment]
You can use something else aside from the INT pot

**Comment by wwright72** [comment]
Without the int from the bonus the set ends up being worse than just stacking random influence gear & lower ilvl 2-peice bonus'. It's quite disappointing that this cool idea isn't worth using. :C 

Sorry last post, I know this is probably a balance discussion for another place.

**Comment by sioding** [comment]
Thanks - so i do not need to lock this here. Would be great if you move the discussion to the forum.
