### ISSUE TITLE
Ball and Chain

### ISSUE THREAD

**Issue by Tameth24** [WarEmu/WarBugs#12815]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

[Screenshot 2018-11-27 23.18.56.zip](https://github.com/WarEmu/WarBugs/files/2651313/Screenshot.2018-11-27.23.18.56.zip)

Expected behavior and actual behavior:
Hello! My order Character Belgravia appears to me like a normal robed AM. But for everyone else, I appear clothless and have a huge ball & chain! This is the only character that is affected this way. I have tried relogging, even gave her a break. Last I played Belgravia was on Nov 27, that is when it all started. I was in Dragonwake - I did some PVP and PVE that night. It has come to the point where everyone asks me what wrong or how i did that but I appear normal in my screen.
I would really appreciate your help in this matter.
Thank you

Steps to reproduce the problem:
I do not know what I did, I only know it started on November 27, that is when we first saw this issue.

Screenshots/Videos or archive.org evidences:
One of the screeshots was taken by a friend on Nov. 27. This was in Dragonwake. That is where you see the chain cross the screen. Apparently there is a huge ball at the end of the chain.
The second screenshot is one I took of myself today (Dec 5) in Altdorf. I look perfectly normal (to me!).

**Comment by sioding** [comment]
The "naked" problem will be fixed next pach. Can you please add a screenshot with your character window open ?

**Comment by Tameth24** [comment]
Hi, Thank  you for your prompt response! i am looking forward to the next patch then :)
here is the screenshot you asked for. Please let me know if you need further information
Thanks again!

![screenshot 2018-12-06](https://user-images.githubusercontent.com/45643858/49617015-d802ea80-f980-11e8-9caa-7bb48eb26aa2.png)

**Comment by Tameth24** [comment]
Hi, Thank  you for your prompt response! i am looking forward to the next patch then :)
here is the screenshot you asked for. Please let me know if you need further information
Thanks again!

![screenshot 2018-12-06](https://user-images.githubusercontent.com/45643858/49617015-d802ea80-f980-11e8-9caa-7bb48eb26aa2.png)

**Comment by MaxHayman** [comment]
Hi @Tameth24, could you check when you are next on as it should be fixed.
