### ISSUE TITLE
"Lost Blade"

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#12814]
Expected behavior and actual behavior:
One of the influence rewards for DoK in T1 Nordland for RvR rewards cannot be correct, ones stats are much higher than the others, items are "Lost Blade" and "Festenplatz Pillager Xiphos".

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/44329952/49554183-a1659b00-f8c0-11e8-968d-72ee4259c10b.png)

**Comment by wargrimnir** [comment]
Xiphos should be the DoK specific weapon. Blade is for Blackguard.
Made the changes to stats and values, anyone that was using a blade will now have a xiphos, vice versa, with corrected stats.
