### ISSUE TITLE
[RvR] Warcamp guards do not reset properly after being pulled

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12812]
If a player comes too close to an enemy warcamp the NPC guards try to kill him as intended, the problem is that afterwards the guards often don't go back to their position. The guards stay at the position where they killed the player, outside of the warcamp. If the guards repeatedly get pulled they can come quite far out of the warcamp.
A popular example is the cannon battery BO in Ekrund, Order players often flee to the nearby warcamp and Destro players then pull the guards which can bug all the way up the hill close to the BO flag. In extreme cases this allows ranged Order players to attack people at the flag while being protected by a onehitting guard.

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
fixed with patch from 08.12.2018
