### ISSUE TITLE
Instant Kill after jumping

### ISSUE THREAD

**Issue by CuriousJim83** [WarEmu/WarBugs#12810]
I was just in the Golden Tor PQ in Blighted Isle Dark Elf Chapter 3 region.  I was just jumping out of a nest and as soon as I landed outside the nest I was killed instantly.  There were no mobs attacking me and no long drop.  I was just jumping out of a nest and landing on the ground outside the nest.

**Comment by sioding** [comment]
This is a know problem since the AoR times - if the client thinks you will not land properly after a jump you will die. This happens also sometimes for the guys who always likes to jump on every singe world object they can. So simetimes you are owned by a stone - or like while jumping out of the nest. I guess no error message was given to you correct?

**Comment by CuriousJim83** [comment]
Yes, that is correct.  It was just an instant death and the usual respawn prompt.  I'm surprised it's taken me this long to come across this bug in that case XD lol!

**Comment by sioding** [comment]
OK with no given errormessage its the bug i mentioned. I will talk to Nath if he can do something on this - but i´m not very hopeful. Both relams loss a lot of characters cause the stone/nest or whatever won... Anyway - thanks for the report.

**Comment by CuriousJim83** [comment]
Thanks mate, anything you can do would be greatly appreciated :-)!!

**Comment by Rydiak** [comment]
I always trip and die on the broken ledge that acts as a staircase up to the upper capture points from the middle capture point in Gates of Ekrund. This is a very old bug.

**Comment by Natherul** [comment]
This is in fact a very old bug and not something that I believe we can fix in the current state as client is sending data that you have fallen longer then you have in actuality.

**Comment by CuriousJim83** [comment]
Haha that's possible Rydiak XD lol!  Thanks anyway for looking into it mate.  It's greatly appreciated.  It just confused me as it was the first time I came across it.  And thank you for keeping us informed about it :-)!!
