### ISSUE TITLE
Redeye Reapa nullreference

### ISSUE THREAD

**Issue by Nefarian11** [WarEmu/WarBugs#12828]
Expected behavior and actual behavior:

Reapas throw nullreferences when something related to damage over time happens and despawn

Steps to reproduce the problem:

It's not clear what causes the nullreference, only that it has to do with damage over time. Try to apply a dot to one or let theirs (if they have one) do damage.

Screenshots/Videos or archive.org evidences:

![nullref](https://user-images.githubusercontent.com/23102638/49691310-8fddf680-fb3f-11e8-9c81-42096cfe599f.JPG)

**Comment by grunbag** [comment]
fixed at next patch
