### ISSUE TITLE
missing potions from RVR vendors

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#1282]
atm the only vendor that sell potions are the t2 sc weapon (dont know if it's the same for order)

But potions should be sell by all tiers vendor, this make only ppl in lv 12-21 able to buy em

**Comment by Evildoor** [comment]
Same with order.

**Comment by Tesq** [comment]
as additional information  potion were buyable with also meddallions.

**Comment by Reggaewaldo** [comment]
I think that this is live on the dev server. Will need to verify.

**Comment by Evildoor** [comment]
T3 emblem vendor now sells potions. T1 emblem vendor and medallion vendors do not.

**Comment by Tesq** [comment]
uhm on live also t1 vendor sold wounds potion and ap potion

**Comment by wargrimnir** [comment]
RvR vendors should be fully stocked.
