### ISSUE TITLE
Gunbad - Solithex not using pit of shades, at all

### ISSUE THREAD

**Issue by Nefarian11** [WarEmu/WarBugs#12829]
Solithex doesn't use his pit of shades, at all during the fight.

Dwarf Add spawned correctly, and both him and the boss behaved correctly.

I don't have video proof. before the patch it worked correctly so i didn't even think about it. GM Gambero was present during the fight and can confirm that the boss was not behaving correctly

**Comment by grunbag** [comment]
fixed at next patch
