### ISSUE TITLE
Dark Elves T3 Epic Quest Saphery Trial by Fire PQ

### ISSUE THREAD

**Issue by wildwindblows** [WarEmu/WarBugs#12826]
Hi,

I was doing Dark Elf T3 Epic Quest today and i realized that there was no mob in Saphery Trial by Fire PQ ( Kill 8 Impetuous Aprentice in Step 10). I waited for mobs for ages but nothing happened. Therefore Dark Elves Honorable Deceit T3 epic quest not doable right now.

These are some screenshots show area and location on the map.
![map](https://user-images.githubusercontent.com/45720515/49690332-39bd8300-fb40-11e8-8944-3c270f8d78b8.png)
![tbf_1](https://user-images.githubusercontent.com/45720515/49690333-39bd8300-fb40-11e8-8588-9573af7fbb2b.png)
![tbf_2](https://user-images.githubusercontent.com/45720515/49690334-39bd8300-fb40-11e8-986e-9cd6d2e7665a.png)

Sincerely yours.

**Comment by sioding** [comment]
I see a PQ Tracker - this is a known issue which we can not fix atm. Sorry you have to wait for a server restart this maybe will fix the problem. Anyway - thanks for the report.
