### ISSUE TITLE
Bug : double damage from sorcerer ??

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#12824]
Hello,

As you can see  all damages are double : word of pain 5 333 ! (3362) 1971 mitigated
chillwind 1426 (530 mitigated) and so on....

Even on the dummy in Altordf with no resist no toughness you never reach this insane amount of damage.
![thorbolt_584](https://user-images.githubusercontent.com/16274785/49688911-85a90180-fb19-11e8-990d-6beac5cafe6c.jpg)

**Comment by Torquemadra** [comment]
double damage buff when you cap both points on logrins forge.
