### ISSUE TITLE
Dark Elf T3 Epic Quest Step 10 Trial by Fire PQ

### ISSUE THREAD

**Issue by wildwindblows** [WarEmu/WarBugs#12825]
Hi,

I was doing dark elf epic quest and i realized that there was no mob in Saphery Trial by Fire PQ. I waited for ages spawm any mob but this was not happened

These are some screenshoots show the pq's area:
![map](https://user-images.githubusercontent.com/45720515/49690172-79cf3680-fb3d-11e8-90f3-2b7fb1fd2cbb.png)
![tbf_1](https://user-images.githubusercontent.com/45720515/49690173-7a67cd00-fb3d-11e8-82c9-bcf1d6c5c8e3.png)
![tbf_2](https://user-images.githubusercontent.com/45720515/49690174-7a67cd00-fb3d-11e8-82b6-d078b42337d7.png)

**Comment by sioding** [comment]
I see a PQ Tracker - this is a known issue which we can not fix atm. Sorry you have to wait for a server restart this _maybe_ will fix the problem. Anyway - thanks for the report.
