### ISSUE TITLE
DoK Covenant of Tenacity

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#12821]
Expected behavior and actual behavior:
my Covenant of Tenacity is not increasing armor as much as it is supposed to.

Screenshots/Videos or archive.org evidences:
without it
![image](https://user-images.githubusercontent.com/44329952/49626381-3ccd3d80-f99f-11e8-8327-0cdb497b9145.png)

with it
![image](https://user-images.githubusercontent.com/44329952/49626395-4d7db380-f99f-11e8-9669-73f1a8ed1791.png)

**Comment by sioding** [comment]
let me guess: you have used a armor pot?

**Comment by Xicoz** [comment]
yes sir I did

**Comment by Torquemadra** [comment]
it doesnt stack with armour potions, whichever is greater will be the value you gain

**Comment by sioding** [comment]
So you got your answer - its not a bug - i close this report here.
