### ISSUE TITLE
T1 Dwarf Advanced reward bugged. (Not selectable)

### ISSUE THREAD

**Issue by CreepFingers** [WarEmu/WarBugs#12834]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Select reward.  Reward not selectable

Steps to reproduce the problem:
relogged, still not selectable

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Hm - sorry not enough informations. T1 Dwarf is a good start. Do we speak about RvR Influence or a chapter influence ? And if yes - which chapter?  Can you please add more informations?

**Comment by CreepFingers** [comment]
Witch Hunter
________________________________

**Comment by Lheana** [comment]
Please provide a screenshot cause I don't understand what the issue is exactly.

**Comment by raptrr** [comment]
No further information was give. Closing
