### ISSUE TITLE
[NPC] Greenskin chapter 9: Quest giver "Ugra" is missing his quest giver symbol

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12836]
The quest giver "Ugra" in the ch 9 Greenskin camp has no quest giver symbol above his 'ead like usual.

![duzgat_015](https://user-images.githubusercontent.com/30193675/49788773-85338500-fd2a-11e8-9dc0-68264c7b4a55.jpg)

**Comment by Lheana** [comment]
That's because they are mounted, it is an issue that happens with every mounted NPC.

**Comment by Lheana** [comment]
See #13194 for the general issue with mounted quest givers.
