### ISSUE TITLE
Honor Restored mission

### ISSUE THREAD

**Issue by Ironkodiak** [WarEmu/WarBugs#12833]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
And close. Please create a report with something inside.
