### ISSUE TITLE
No Quest credit for 2 Beast Lord bosses

### ISSUE THREAD

**Issue by Trikpriest** [WarEmu/WarBugs#12838]
Finally managed to find 2 BL bosses up last night ran a guild group but no one in party got credit for either kills, Khorgash Manbreaker and Skarlok, have a screen shot of the Skarlok kill but not Khorgash, 
![skarlok](https://user-images.githubusercontent.com/45471842/49790064-418a4c80-fd25-11e8-9a26-cd048f1e51d3.jpg)

**Comment by Kaelang** [comment]
The Beastlord Questline is now working as intended. This could have been fixed in a patch between 2018 to today, however if you are still having such issues please re-open a report.
