### ISSUE TITLE
Wrong Armor value on Archmage Mercenary Shoulder

### ISSUE THREAD

**Issue by Bowldancer** [WarEmu/WarBugs#12839]
The Archmage Mercenary Shoulder has an armor value of 708, which is the equivalent of heavy armor.

![zensei_000](https://user-images.githubusercontent.com/22199775/49796625-7dc9a700-fd3d-11e8-8e55-02f79b945468.jpg)

**Comment by AmidalaEstellanor** [comment]
Checking

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with first patch of the year 2019 (05.01.2019)
