### ISSUE TITLE
[Duelist's Ornament of Conquest]

### ISSUE THREAD

**Issue by insultus** [WarEmu/WarBugs#12837]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Something inside of the report would be great.

**Comment by insultus** [comment]
[Duelist's Ornament of Conquest] is a renown merchant item that is currently salvagable

**Comment by sioding** [comment]
Aha - nice. And its a problem because?

**Comment by sioding** [comment]
No answer for 10 days. close
