### ISSUE TITLE
Gunbad - 'Ard Ta Feed multiple issues

### ISSUE THREAD

**Issue by Nefarian78** [WarEmu/WarBugs#12842]
Expected behavior and actual behavior:

Issue 1: Enrage not going away:

After using the gems when being told to by the /monster say the Enrage buff should go away, but it doesn't. Even after the /monster say gives the message saying that the "monstruos squig calms a bit", making the boss impossible to kill due to 5k+ aoe stomps or vomit

Issue 2: 'Ard Snack weird behavior:

Before the patch the 'Ard Snacks always followed 'Ard Ta Feed and he would eat them, healing himself.
After the patch, the 'Ard Snacks sometimes will randomly despawn, not heal boss after being eaten, get stuck on/follow the slime bubbles, start following the squig hordes, follow players or follow the boss. I honestly do not even know what their correct behavior is anymore. 

Steps to reproduce the problem:

Our group tried that boss for over 1.30hrs and each time both issues were present during the fight

Screenshots/Videos or archive.org evidences:
![21fafxxzv](https://user-images.githubusercontent.com/23102638/49847897-b7002680-fdd2-11e8-9506-e3d3c9038a84.JPG)
![faf21r11r21](https://user-images.githubusercontent.com/23102638/49847903-ba93ad80-fdd2-11e8-9eec-98425aef520c.JPG)
![f21xz](https://user-images.githubusercontent.com/23102638/49847908-bf586180-fdd2-11e8-8c71-5cabbca5bf03.JPG)

**Comment by Hargrim** [comment]
Fixed, should be available on next patch or hotfix, probably Saturday.
