### ISSUE TITLE
warband distant

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#12845]
Expected behavior and actual behavior:
in my warband it is showing me as distant, and everyone near me as distant except for 2 people, I know this bug has been a problem before, and I thought it had been fixed, so I figured should put out this bug report, I apologize if I am wrong.

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/44329952/49909757-d2584980-fe45-11e8-91dc-2999c0593e7b.png)

**Comment by MaxHayman** [comment]
Has anyone experienced this recently?

**Comment by Xicoz** [comment]
I still experience it from time to time

**Comment by raptrr** [comment]
Can we get another feedback on this?
