### ISSUE TITLE
T3 Epic Quest (Will of the Warboss)

### ISSUE THREAD

**Issue by Folgrimma** [WarEmu/WarBugs#12846]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Expected: Killing the Champion mob Ironguard Riksson completes quest stage.
Actual: The quest does not complete upon killing the NPC.
Screenshots: First one shows me attacking the npc, Second one after the npc has died and that the quest has not completed

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/40577289/49931051-38af8d00-fe83-11e8-8258-1f9515d8b318.png)
![image](https://user-images.githubusercontent.com/40577289/49931078-4c5af380-fe83-11e8-850e-4f4428d32494.png)

**Comment by Lheana** [comment]
You were grouped, it does not complete quests when you are grouped.
