### ISSUE TITLE
Crash during Siege

### ISSUE THREAD

**Issue by Wutdoumin** [WarEmu/WarBugs#12848]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Normally the game should not crash during the siege to a keep, unfortunetly during a siege the game crash, fluid game normally

Steps to reproduce the problem:
Sieging a keep

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Thanks fpr the report but we can not help here. Please check this thread to get some tipps for reducing lags and crashes: https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=20075
