### ISSUE TITLE
char become disabled

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#12840]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

was fighting in rvr and died ... after release i shoud respawn and be able to move

Steps to reproduce the problem:

orvr in bfp just 10 min ago died did release and i couldnt move and all abilities become greyout

Screenshots/Videos or archive.org evidences:

[Video](https://streamable.com/bvj9k)

**Comment by sioding** [comment]
Duplicate of #10682
