### ISSUE TITLE
The Shoulders of Heroes

### ISSUE THREAD

**Issue by Carhillion** [WarEmu/WarBugs#12847]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
The statue of Spongel required to complete "The Shoulders of Heroes" is missing
![elume_006](https://user-images.githubusercontent.com/45575531/49952116-75739680-ff0c-11e8-9c1e-8a0fb50e3de8.jpg)

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Lheana** [comment]
Will be fixable when event statues will be removed.

**Comment by sioding** [comment]
fixed with patch from 15.12.2018
