### ISSUE TITLE
XP/Renown/Inf split not working

### ISSUE THREAD

**Issue by Green-Wolf** [WarEmu/WarBugs#1284]
It seems that the new split system isn't working (sometimes?). Just killed a guy with 2-3 others while ungrouped and did about half the damage and didn't get anything.

**Comment by Evildoor** [comment]
The problem still persist in RVR? (scenarios are different case) I remember participating in kills while being solo and receiving rewards.

**Comment by Evildoor** [comment]
No response, closing.
