### ISSUE TITLE
[Quest] The Sewers of Altdorf, 3rd step

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#12841]
quest objects have strange hp 
compared to other objects in 1st and 2nd steps.
you have to hit it 100 times ( with skills ) literally.
with group you still need almost 1 min to destroy it. 
it took more time than heroes.
check this plz.

![sewer_bombs](https://user-images.githubusercontent.com/19988772/49805968-d62e9200-fd99-11e8-982f-a86f34e8b572.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 15.12.2018
