### ISSUE TITLE
[Dungeon] [Gunbad] Mobs disapear with DoT

### ISSUE THREAD

**Issue by Poussky** [WarEmu/WarBugs#12844]
I've trying to search if this issue was already posted, but I've not found anything... Sorry if it's already in charge.

Expected behavior and actual behavior:

Redeye Reapa gobs disapear when using my SwordMaster using skills with DoT. Not trying with other class, and I'm not sure if he disapear after ticks of DoT or just after using a skills (see video below). I've trying with 5 or 6 Reapa and all disapear with the same message "NullReferenceException was thrown from DamageOverTime. This object will be destroyed." but I'm not sure about skills I used against them and I don't know how to translate them in english.

Steps to reproduce the problem:

1. Take a swordmaster
2. Fight against Redeye Reapa in the right wing of Gunbad
3. He disapear with some skills.

Screenshots/Videos or archive.org evidences:

https://youtu.be/L_k-aMb74xw

**Comment by grunbag** [comment]
Duplicate . I fixed this for next patch . Thanks for reporting anyway !
