### ISSUE TITLE
Scenarios Not Filling Last Spots

### ISSUE THREAD

**Issue by Zarbix** [WarEmu/WarBugs#12852]
Expected behavior and actual behavior:

When a scenario starts and has room for more players (for example, Order has 12, Destro has 10) the missing spots should be filled as people join the queue.

Instead, sometimes, the open spots will never fill, and the scenario will be imbalanced until ends. I've confirmed with multiple players that they are queued up for the scenario specifically, and are not getting in.

The problem may be tied to people either dropping the queue when it pops, or letting the timer expire. This is unrelated to not enough people queuing.

Interestingly, if the imbalanced team loses more people to crashes or them leaving, those new spots will be filled (Using the above example, if Destro goes down to 8, and 4 players are queued up, 2 people will get in to bring them back to 10, but they will never go to 12).

Thank you for looking into this, hopefully my post was clear!

**Comment by sioding** [comment]
As far as i know the open spots will only be filled with queued ppl for a certain time at the beginning of a scenario. But i will ask Nath on this. Thanks for the report.

**Comment by Zarbix** [comment]
Thank you for the fast response! 😀

**Comment by sioding** [comment]
Hey @Zarbix - Natherul checked the code on that and doesn´t found anything on it that would prevent queued players from joining. My guessed reason was a wrong one too.So sorry - no bug found.  I close this one here.
