### ISSUE TITLE
Gold Bag Bug

### ISSUE THREAD

**Issue by Badboykiller123** [WarEmu/WarBugs#12854]
Sorry to bother you but I won a gold bag today and I never received it in the mail after we locked Barak Varr and Marsh Maddness and I throught it was a bug and logged back in and nothing was in a my mail box. I submitted my screen shot I took of it.

Screenshots/Videos or archive.org evidences:
https://imgur.com/a/4AyMmqp

![dreadmonster_012](https://user-images.githubusercontent.com/45886616/50034032-060fac80-ffc9-11e8-8971-fbdf747336c5.jpg)

**Comment by sioding** [comment]
This happens sometimes and we are not able to reproduce it. Wait for the next patch - you should get your bag with the server restart. BUT - sometimes you even got no bag on the restart - YES it happens (not really often) and thats bad luck. Please understand that we do not give out bags in this case.

**Comment by sioding** [comment]
I reopen this one. Can you please give a feedback if you get the bag after the next restart?

**Comment by sioding** [comment]
No answer since 15.12.2018 - Close
