### ISSUE TITLE
Empty scenarios / scenario not filling

### ISSUE THREAD

**Issue by Nefarian78** [WarEmu/WarBugs#12853]
Expected behavior and actual behavior:

The scenario should fill itself when there are free spots, but lately this has not been the case. Scenarios will be empty or won't be filled when you're missing some players.

Steps to reproduce the problem:
Unknown, but it's happening frequently. The only theory i have is that the scenario is saving spots to players that have refused or missed the queue, like when choosing the "yes but give me a minute" option. Only it saves the spot indefinetly.

In the screenshot a premade was clearly supposed to enter, but they probably missed the queue and resulted in the scenario being empty the entire time. The population imbalance mechanism still worked correctly and the scenario closed shortly after.

Screenshots/Videos or archive.org evidences:

![2q1r1f1f21f1](https://user-images.githubusercontent.com/23102638/50019701-ecc02d80-ffd3-11e8-89d3-5c692bb1d5f8.JPG)

**Comment by sioding** [comment]
This is alredy checked from @Natherul in #12852 - Close
