### ISSUE TITLE
Renown Abilities Visual Bug for Knight of the Blazing Sun

### ISSUE THREAD

**Issue by Beerbuffet** [WarEmu/WarBugs#12859]
New renown ability that doesnt work.  Im assuming its appearance is unintentional

https://cdn.discordapp.com/attachments/514612840766636034/523535997334585344/Sleepykk_034.jpg

**Comment by sioding** [comment]
I can not reproduce that. Can you please do not use the advaced renown trainer addon - try again and come back with new screenshots?

**Comment by sioding** [comment]
No answer since 15.12.2018 - Close
