### ISSUE TITLE
BW sorc wh dots not doing damage at the end of the timer.

### ISSUE THREAD

**Issue by EarlLemon1985** [WarEmu/WarBugs#12858]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
,Boiling blood, word of pain, burn away lies etc do not do the damage they are supposed to when the timer runs out.

Steps to reproduce the problem:
Happens every time.

Screenshots/Videos or archive.org evidences:

**Comment by Dekata** [comment]
Yes, the same

**Comment by sioding** [comment]
Can you please check that again after incoming hotfix?
