### ISSUE TITLE
[Marauder] Lack of Intelligence

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#1285]
While I am aware that Marauders don't need intelligence for most of their abilities (not sure if Mutated Energy uses it), I do think they should have some. I have tested this with all mutations and have not had any change in it. 
![rezalevadgib_000](https://cloud.githubusercontent.com/assets/13975292/9674363/cafb32ee-5275-11e5-8249-62a137b0bf0a.jpg)

Thank you

**Comment by CaptainoftheHarem** [comment]
I have attached my marauders naked stats as well (also the hit points seem a bit low for a 14 but that may just be a lack of perspective)
![rezalevadgib_001](https://cloud.githubusercontent.com/assets/13975292/9674562/acca640a-5277-11e5-80f1-6ba6a023a8f6.jpg)

**Comment by CaptainoftheHarem** [comment]
And I just leveled up and everything went to the expected levels

**Comment by Toldavf** [comment]
There's a joke in here somewhere :package:P

**Comment by Evildoor** [comment]
Seems to be the part of general problem, which i described in
https://github.com/WarEmu/WarBugs/issues/1007
Closing this.
