### ISSUE TITLE
Glomp da' Threat Boss. No loot. No credit for some players. Random assigned lockouts from Gunbad.

### ISSUE THREAD

**Issue by dramze** [WarEmu/WarBugs#12850]
We were in this for hours today. No GM to help nor appeal answered yet. Not one party member received anything as consolation. This is a very commonly attempted boss. Please fix this bug along with the other Heros in Gunbad before players give up altogether

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by WAR2014** [comment]
I'm not sure this bug maybe/maybe not link with the OP but here is another bug I found this early morning. At order side quest name "The Threat from Glomp", I can't return the quest after the boss killed. So there's nothing I can get from quest reward. Please see the attached screenshot reqards this quest bug (PS. the GUI was used T.chinese - /l 8):
![The Threat of Glomp](https://user-images.githubusercontent.com/17757461/57740779-c9bdb500-76fc-11e9-9a2f-486b6999eea4.PNG)
I had choose helmet as my reward but when tick the done, nothing happen. 

Would any Dev member can spare few valuable times review and fix this bug?

Much appreciatied for all your hard works to made this game better and better!

Cheers,

**Comment by raptrr** [comment]
@dramze please provide information about lockouts / kill confirmation. We need these information to check what might have caused the problem.

@WAR2014 this is a whole new thing, if it's still a problem/bug, please open another Issue and we will review it. Thanks.
