### ISSUE TITLE
[salvaging] some weapons can't be salvaged

### ISSUE THREAD

**Issue by Tyramissoux** [WarEmu/WarBugs#1286]
as soon as there's a "or offhand" it can't be salvaged - all mainhand only weapons work

**Comment by MKorin** [comment]
In old war you can salvage items from vendor too

**Comment by Tyramissoux** [comment]
Right now, it's too time consuming (the grind is real!) or expensive to get salvaging up to a high lvl (spent about 150g so far) to actually have a chance for lvling talisman making beyong 130+.

**Comment by Reggaewaldo** [comment]
I feel this needs to looked at.

Refresh me here though, on live server all items that were of greater quality than green could be salvaged, right ?

**Comment by Tyramissoux** [comment]
Yes, even RVR items. But not all of them. The ones of higher quaility definitely.

Right now, the auction house is almost empty for low lvls on destro side, leading to fresh players getting steam-rolled even more.

**Comment by Reggaewaldo** [comment]
I have now made all Wepons, Armor , Jewelry that is of rarity green or more that does not require any RR to be able to use, to be salvageable. This might change in the future so that we enable salvaging on RR eq but not as of now.

Closing.
