### ISSUE TITLE
Gunbad influence rewards unavailable

### ISSUE THREAD

**Issue by LunarF0X** [WarEmu/WarBugs#12863]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Unable to choose influence rewards in Gunbad

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

![cargil_011](https://user-images.githubusercontent.com/45575531/50046909-8531dd00-00bc-11e9-87d7-10a903e13ece.jpg)

**Comment by nocturnalguest** [comment]
Issue is still present. And to add more - advanced rewards for Ironbreaker are missing
![Wahr_037](https://user-images.githubusercontent.com/17257194/60399103-86ae8880-9b68-11e9-93ef-7863e14cc824.jpg)

**Comment by grunbag** [comment]
That’s for @Wargrimnir

**Comment by Kaelang** [comment]
Gunbad rework has since been completed and a lot of these issues will have now been addressed as per the recent rework. Please re-open this ticket if the issue persists.
