### ISSUE TITLE
Scenario: Black fire basin 

### ISSUE THREAD

**Issue by rekkir** [WarEmu/WarBugs#12860]
Expected behavior and actual behavior:
Clicked on flag, waited for the bar to fill but could not pick up the objective.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

Couldn't drag in my video of it

**Comment by rekkir** [comment]
apparantly same case in Tor Anroc, couldn't check it due to pesky dark elves but the orb remained on the ground for the whole SC.

**Comment by Natherul** [comment]
should be fixed after the hotfix thats applied now
