### ISSUE TITLE
RR potion buff is getting removed

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#12861]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Potion should stay full timer

Steps to reproduce the problem:

used an RR increase potion and few hours later i checked the buff is gone

Screenshots/Videos or archive.org evidences:

**Comment by Natherul** [comment]
Im currently in the process of testing a fix fro this on my local machine

**Comment by Natherul** [comment]
should be fixed after the hotfix thats applied now
