### ISSUE TITLE
[BB] Boss reseting

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#12862]
We had problem last night while doing Greater of Nurgle boss in BB instance:
Everything went smooth until stomach phase, then weirdness began - after we killed his innards there were 3 outcomes:
1) he spawn on the other end on the room and slowly walk to group, when he reaches he just repeats his stomach pull
2) spawning next to group and doing the same
3) reseting to 100%

As I know he should be stunned after innards are killed, so described behavior we faced looks bugged.

**Comment by grunbag** [comment]
It’s fixed
