### ISSUE TITLE
Mail COD seems to be broken

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#12870]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

i got myself 40pot armor from a guy selling in chat and he did sent COD and i hit accept  and i didnt get any pots and lost the money

Steps to reproduce the problem:

as stated below happened to me just 20 min ago

Screenshots/Videos or archive.org evidences:

N/A

**Comment by sioding** [comment]
Can you please add charnames so we can search in the logs?

**Comment by Tazo83** [comment]
yes char name is Yakyaky on  destro
