### ISSUE TITLE
Tree of Beards PQ ToK unlock

### ISSUE THREAD

**Issue by Sinrman** [WarEmu/WarBugs#12875]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

- Checked tickets: Tree of Beards PQ ToK unlock #10567 is **closed**.
- Checked wiki: No page available
Expected behavior and actual behavior:

Ticket 10567 says it all. Trying to not open duplicate ticket but Lheana stated in 2017 that these bugs were not able to be fixed because you did not have client control so he/she closed the ticket. Now that you do have client control may we reopen these tickets?
Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

![gunnr_045](https://user-images.githubusercontent.com/42098334/50124070-9e579c80-0228-11e9-8c86-c751d2992a6e.jpg)

**Comment by sioding** [comment]
I am sorry i DO close this one  but reopen the original one.
