### ISSUE TITLE
scavenging/salvaging

### ISSUE THREAD

**Issue by knezekj** [WarEmu/WarBugs#1287]
Hi i have level 70 scavenging and when i want scavenge mob lvl 10 it writes that my skill is to low.

And Salvaging i cannot learn.

Thank you for answer.

**Comment by Thorgatin** [comment]
https://github.com/WarEmu/WarBugs/issues/1280

**Comment by Evildoor** [comment]
Scavenging was fixed.
Learning two gathering skills on one character is not allowed, IIRC.
