### ISSUE TITLE
Enhancement Suggestion: AH Mail recipient name

### ISSUE THREAD

**Issue by deLunel** [WarEmu/WarBugs#12874]
Suggest 'enhancement' to mail:
When a transaction in Auction House has occurred every character can see there is a mail but not for which character. Would it be possible to show the name of receiving character somehow?
Currently only way is to log each character to see which one is the actual recipient.

Thanks for bringing this amazing game back to life!

**Comment by Torquemadra** [comment]
Suggestions goes on the forums ;) Bugtracker just for bugs ;)
