### ISSUE TITLE
Engi's crit hit tactic

### ISSUE THREAD

**Issue by globalgame** [WarEmu/WarBugs#12878]
I know already was another issue tracer rounds but i tested in duel with mara ...
Mara had 0% chance to be critically hit  i had from tracer rounds 15% crit chace only and NO CRIT HITS AT ALL !! so i can say tracer rounds broken or its useless tactic ....

**Comment by sioding** [comment]
OK - first of all: Thanks for the report. But tbh: Please give as much information as you can do. Name the tactic - 23 classes with hundreds of tactics.. Then add your testing screens - and if you are sure another report is open: Then do not open another one - add you comment to the original one. Please edit your report.

**Comment by globalgame** [comment]
![war 2018-12-18 13-38-23-19](https://user-images.githubusercontent.com/24555848/50148781-0e663100-02c2-11e9-9b1b-446085d89ac6.png)
![war 2018-12-18 13-38-27-74](https://user-images.githubusercontent.com/24555848/50148783-0e663100-02c2-11e9-8beb-df5864d19ad0.png)
![war 2018-12-18 13-38-33-43](https://user-images.githubusercontent.com/24555848/50148784-0e663100-02c2-11e9-9e02-f1f17cd7607a.png)

https://officialrorbuilder.herokuapp.com/career/engineer/s?l=40&r=40&tl=4&mp=14&pA=0&pB=0&pC=11&m1=false&m2=false&m3=false&m4=false&ma=&mm=&mt=3678&t=

**Comment by GK111** [comment]
https://github.com/WarEmu/WarBugs/issues/12534

**Comment by sioding** [comment]
Thx @GK111
