### ISSUE TITLE
Satchel of Conqueror's Emblems Converting into something else

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#12879]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Satchel of Conqueror's Emblems should convert into conquerors emblem by spending oppressor coins but i got 1240 officer medal

Steps to reproduce the problem:

i spent all my oppressor coin around 120 something like that  and convert them then went to buy the weapon and couldn't and when i checked I was shocked that i don't have enough  emblem and i ended up having 1240 Officer Medalian 
Screenshots/Videos or archive.org evidences:

Check the logs for Character name Yakyaky in destro  ...

**Comment by Tazo83** [comment]
![yakyaky_060](https://user-images.githubusercontent.com/42385505/50171645-09c26c80-0304-11e9-863b-a67ba5054c51.jpg)


in this screen shot you can see that i dont have any opressor coin and i have 1240 officer Medal after opening all the Satchel of Conqueror's Emblems bags

**Comment by Tazo83** [comment]
is it possible to get my oppressor coin back or convert them for the correct amount of Conqueror

**Comment by sioding** [comment]
Emblems don´t convert into Medaillions - and i was so kind to test it - it works fine. If you convert an opressor emblem you get an conqueror emblem. And YES you get 1 comqueror per 1 oprressor. This is fine as it is - its a design decision.

**Comment by Tazo83** [comment]
@sioding atleast check my logs i dont know how i ended up with the wrong coin or the wrong medal as you mentioned  am rr66 and i did many SC and pvp and spent just 10 min ago i spent all my opresser coin into this satchel bag which you can confirm from checking my logs and after opening them all i ended up with this wrong convert  logs will  show that am saying the truth

**Comment by sioding** [comment]
Sorry but there will be no log check cause there is no bug. Believe me or not - if we really would face a problem like this the bugtracker would be flooded with tickets. My best guess is you changed the wrong currency or you haven´t checked your inventory correctly.

**Comment by Tazo83** [comment]
i dont have anyother way to prove that i am not lying here only log can show the truth and am asking for justice atleast let someone check the log i cannot lose more than 100 opressor coin in second for a bug giving me 1240 of the wrong medal am not suppose to have 

i hope you can understand my point and my feeling right now after losing everything and gaining nothing

**Comment by Tazo83** [comment]
well you have a point there but there is no merchant to spend oppressor coin and convert them except 1 merchant which should give back conq emblem ... first i said maybe i did the wrong bag then i checked all npc and only 1 npc with oppressor coin to convert and its the emblem one thats why i put screen shot of my inventory 
@sioding

**Comment by sioding** [comment]
ok i do stop that here.
