### ISSUE TITLE
Medallion icons are not showing

### ISSUE THREAD

**Issue by crazyturkme** [WarEmu/WarBugs#12876]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
I cant see vanquisher, sentinal and oppresor emblem's icons. Can you please fix it? or tell me how to fix it?

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/45875969/50128419-f5d82580-0285-11e9-9260-c9052c06c390.png)

**Comment by crazyturkme** [comment]
I will post more screenshots when i login to game. 

Character names 
Rr70 sorc Rzjka
Rr70 mara Poncik

**Comment by sioding** [comment]
awsome - looking forward for it. thanks

**Comment by crazyturkme** [comment]
![1](https://user-images.githubusercontent.com/45875969/50179130-4fd4fb80-0317-11e9-87f4-186627914854.jpg)
![2](https://user-images.githubusercontent.com/45875969/50179143-55cadc80-0317-11e9-988a-bb722ed1e545.jpg)

**Comment by Torquemadra** [comment]
What launcher are you running? Because you are missing files which should get picked up. You can do this

1. Close launcher and reopen and see if it is resolved.
2. Delete interface.myp and redownload the files.
3. Delete data.myp and redownload the files.

**Comment by sioding** [comment]
aaaand done by lead. This would be exactly my advise. Please give a feedback if its fine after that.

**Comment by crazyturkme** [comment]
nope doesnt work for me. I tryed all

**Comment by sioding** [comment]
since you are alone with that problem and you are sure you´ve followed torque´s advice - i can only suggest to make a complete reinstall of the game. I know it sounds sad - but after all it´s the only reason. make sure you use the latest launcher and follow our install intructions here: https://www.returnofreckoning.com/join.php#download
