### ISSUE TITLE
[BE] Last boss door

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#12872]
looks like after server restart all doors to bosses reappear so you cannot get in even if prerequsite boss was killed before restart.

In our case it happened like this - we killed Korthuk boss on tuesday but wiped on last boss, so decided to do it next day. There was patch Tuesday evening. On friday when we entered instance all mobs have respawned, door to last boss ahve respawned, but Korthuk boss did not, so there was no way to get to the boss.

![veszal_449](https://user-images.githubusercontent.com/42712833/50056952-09e03200-0175-11e9-8d46-6bde3ebcaace.jpg)

**Comment by sioding** [comment]
already fixed
