### ISSUE TITLE
double credit for kill from player character

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#12880]
Sometimes I got double credit for killing player, same when I died, other players got double credit
![thorbolt_595](https://user-images.githubusercontent.com/16274785/50184102-5ca42000-0314-11e9-8917-cd02bd907c46.jpg)
![thorbolt_596](https://user-images.githubusercontent.com/16274785/50184117-662d8800-0314-11e9-9cbf-01bb847c713b.jpg)

**Comment by sioding** [comment]
As far as i can see thats a addon problem cause i only see one "You have been slain by...". Thats the phrase the server sends. Since we do not give out addon support on the BT you have to speak to sulle for this by using the forum.
