### ISSUE TITLE
'Beer' - ToK unlock

### ISSUE THREAD

**Issue by Sinrman** [WarEmu/WarBugs#12883]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

- No open tickets
- According to Wiki - Unlocks for Order - 'Beer'
Interact with the 'Keg of Beer' (48k 58.9k) at the corner of a ruined tower inside Dwarf Chapter 12.

Expected behavior and actual behavior:

- Expected: Interact with 'Keg of Beer' to trigger ToK unlock

- Actual: Interacting with 'Keg of Beer" does not trigger unlock. Tried relogging and restarting game, no change.

Screenshots/Videos or archive.org evidences:

![gunnr_049](https://user-images.githubusercontent.com/42098334/50264902-7744ca80-03e2-11e9-9d98-e33fdf324a45.jpg)
![gunnr_050](https://user-images.githubusercontent.com/42098334/50264903-7744ca80-03e2-11e9-8be4-53b181e1a243.jpg)

**Comment by sioding** [comment]
fixed with hotfix
