### ISSUE TITLE
[Item] Excavator's Darkstaff

### ISSUE THREAD

**Issue by Kabucoror** [WarEmu/WarBugs#12890]
The sell price is maybe too high for a green lvl 38 item.

![unbenannt](https://user-images.githubusercontent.com/45296624/50347382-a6b81c00-0535-11e9-92fb-50de4252ec64.PNG)

**Comment by wargrimnir** [comment]
Will review

**Comment by wargrimnir** [comment]
These were indeed a bit high. Adjusted.
