### ISSUE TITLE
[Pocket Item] Fear in a Bottle from "What do we have here" doesn't work

### ISSUE THREAD

**Issue by notre4ror** [WarEmu/WarBugs#12893]
- Expected behavior and actual behavior:
  The tooltip of this pocket says it's grants 4 toughness to all party members and it does nothing when used from action bar.

- Steps to reproduce the problem:
  Get the unlock from Troll Country at 3.5k/54k 
  Get the item from the IC vendor
  Equip it
  Use it (from the action bar, since right click equips it)
does nothing (I cannot get any info from the debug ui window).

**Comment by Lheana** [comment]
No reward of ToK unlock is meant to give bonus. This ability will be removed with next patch.

**Comment by sioding** [comment]
fixed with patch from 30.12.2018
