### ISSUE TITLE
Quest: Local Beliefs - can trigger altar before quest item looted

### ISSUE THREAD

**Issue by Thaodan** [WarEmu/WarBugs#12892]
Empire Ch 19
Expected behavior and actual behavior:
In the Quest Local Beliefs the altar in the cave can be clicked before the silver that should be placed there is looted.
That removes the area marking to collect the liver.

Steps to reproduce the problem:
1. Dont loot the liver.
2. Click on the altar.
3. See result.

**Comment by Kabucoror** [comment]
Will be fixed with next patch. Aslo enabled the follow up quest, so take a look back at the Slain Bear ;)

**Comment by Thaodan** [comment]
Than also look at the quest bevore, all other bears are still shown as pending quest givers.

**Comment by Lheana** [comment]
This won't be fixed with next patch. Nevertheless, if you run a bit far from the bears and you come back, they should no longer have the orange icon.

**Comment by sioding** [comment]
fixed with patch from 30.12.2018
