### ISSUE TITLE
The threat from Barakus the Godslayer quest

### ISSUE THREAD

**Issue by Palitelj** [WarEmu/WarBugs#12896]
As you can see on picture I can choose between dye and not 1 but 2 sentinel hats. Not sure if it is just visual because I still need 2 more kills on boss.

![skkar_002](https://user-images.githubusercontent.com/21026133/50374522-bbf18100-05ef-11e9-9257-d9b69ce24066.jpg)

**Comment by Lheana** [comment]
Thanks for the report, this will be fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 30.12.2018
