### ISSUE TITLE
New .lockout system and no offer to loot drops on Masta Mixa boss

### ISSUE THREAD

**Issue by ChipsWC** [WarEmu/WarBugs#12899]
Expected behavior and actual behavior:
Steps to reproduce the problem:
No one has lockout on Masta Mixa boss in party (neither for any boss of Gunbad)
Kill Masta Mixa.

Expected : Validate the Masta Mixa boss in Gunbad for quest, roll on drops, get the lockout on Masta Mixa
Actual : Validate boss for quest, get the lockout, no roll on drop because there are lockouts in party.

Screenshots/Videos or archive.org evidences:
Chat screenshots 
https://ibb.co/HBsLCc3

**Comment by sioding** [comment]
hopefully ok after hotfix. would be great to have a feedback afzer the patch

**Comment by ChipsWC** [comment]
going to try it out right now

**Comment by Hargrim** [comment]
Looking into it.

**Comment by ChipsWC** [comment]
ok looks like fix worked.

**Comment by ChipsWC** [comment]
did not have time to check if i had lockout on Masta Mixa before 2nd server restart but i got quest validation and drops have been rolled correctly, without any error message.

**Comment by sioding** [comment]
Ok seems to be fixed now. Thanks for the report and the tests.

**Comment by ChipsWC** [comment]
So it seems to correctly work now : got the lockouts and rolled on boss drops.
The .lockout command helped a lot on understanding what was going on. Good job.

Additional problem : Whirlwing Axe of White Lion was bugged inside Gunbad and oneshoting anything. Maybe linked to another issue after recent patch.
