### ISSUE TITLE
WL crit me through Try an Hurt Me wif natural 0% to be crit

### ISSUE THREAD

**Issue by vikingofmars** [WarEmu/WarBugs#12891]
Expected behavior and actual behavior: 

I used Try an Hurt Me which reduces targets chance to crit by 100% for 10 seconds. I have a natural 0% chance to be crit. I still got crit for 1500 dmg. 

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

<img width="960" alt="wl op" src="https://user-images.githubusercontent.com/37393516/50355362-6f894100-051c-11e9-952e-73ff4712da59.png">

Skurrga Eadcleava

**Comment by Torquemadra** [comment]
Cull the weak always crits, unstoppable force meet immovable object.
