### ISSUE TITLE
No quest marks in Talabec camp.

### ISSUE THREAD

**Issue by SODIX** [WarEmu/WarBugs#12905]
Just found a black hole in Talabec, this quests on screenies have no mark when you done them.
<blockquote class="imgur-embed-pub" lang="en" data-id="vc2u5Ew"><a href="//imgur.com/vc2u5Ew">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>
<blockquote class="imgur-embed-pub" lang="en" data-id="tKjU303"><a href="//imgur.com/tKjU303">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by Lheana** [comment]
It must be because you logged out after completing the quests, in this case, end quest marker no longer appears.

**Comment by Lheana** [comment]
Also please, give the names in english next time.
