### ISSUE TITLE
[white lion] brute force not working after pet summon (Patch notes 22/12/2018)

### ISSUE THREAD

**Issue by Ravaiz** [WarEmu/WarBugs#12907]
brute force tactic equipped, strength bonus applied.

unsummon pet or pet dies, loose strength bonus from brute force. Have to remove tactic and reslot tactic to gain the strength bonus again.

**Comment by admaska2** [comment]
Tactics Use : Brute Force, 50 % degats Crits , Flanking , Speed Training

![wl bug](https://user-images.githubusercontent.com/43276959/50377627-00e1db80-0621-11e9-9152-a44b7d16952a.png)

I tested with Other tactics on the Dummy and Only Speed Training Work

**Comment by Natherul** [comment]
should be addressed by next hotfix

**Comment by sioding** [comment]
fixed with patch from 30.12.2018
