### ISSUE TITLE
Guild recall scroll issue : 

### ISSUE THREAD

**Issue by Oldneko** [WarEmu/WarBugs#12900]
After new patch, I cant be back to guild house.
![nikuq_014-2](https://user-images.githubusercontent.com/43213086/50375570-ace7ee80-0642-11e9-9ab4-96138009c3a4.jpg)

**Comment by Oldneko** [comment]
Maybe, Guild house issue.
I cant enter there in walk

**Comment by sioding** [comment]
can you retest it please? i can not reproduce that.

**Comment by Oldneko** [comment]
I just login now.
It is good to get in Guild house, thanks.
