### ISSUE TITLE
WL 1 HIT BUG !

### ISSUE THREAD

**Issue by Jubok21** [WarEmu/WarBugs#12915]
WL got a aoe with a 1 Hit Bug :) he kill all in an 1 hit

**Comment by Jubok21** [comment]
If he Use a pet and change his talents he got a bug and 1 hit all mobs and nps and enemys with 65k dmg,..  
with the spell whirling axe... im not sure how its work... or you need armor or other things.. but i thing its a combo of pet talents and the attacke

**Comment by Rockalypse** [comment]
Looks like it is same thing that hit me in SC, providing screenshot in case it will help: 
![veszal_4741](https://user-images.githubusercontent.com/42712833/50379614-27bf0280-065f-11e9-971f-b687f248bf57.jpg)

**Comment by Torquemadra** [comment]
hopefully resolved, advise if not the case

**Comment by Jubok21** [comment]
thing got fixed :)
