### ISSUE TITLE
Bestial Tokens...

### ISSUE THREAD

**Issue by Jubok21** [WarEmu/WarBugs#12917]
the bestial tokens are really buggy on Order... i make 9 Bosses for Bestial tokens but get only 2 rewards... need to be fixed :) Thx

**Comment by sioding** [comment]
Thanks for the report but its not helping at all. Please be more precise which one you did and when you are not receiving your token.

**Comment by Lheana** [comment]
Please as you can read before posting a report, verify RoR Wiki before posting something related to ToK.
You may think you should have had Bestial Token, but it's not the reward of the unlock. For more information, please read the Note on top of the page: https://wiki.returnofreckoning.com/index.php/Items_(Rewards)

**Comment by sioding** [comment]
No answer since 22 days - Close
