### ISSUE TITLE
WL: Redeye Mane is a helm

### ISSUE THREAD

**Issue by Meleesorc** [WarEmu/WarBugs#12914]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Expected behavior: Redeye Mane should be shoulders
actual behavior: Redye Mane is a helm

Steps to reproduce the problem:
Equip Redeye Mane

Screenshots/Videos or archive.org evidences:
![redeye mane bug](https://user-images.githubusercontent.com/46076248/50379108-96886580-0637-11e9-94f6-4799fcaaf65c.png)

**Comment by Kabucoror** [comment]
On dev server they are shoulders

**Comment by sioding** [comment]
No answer for 16 days. Close.
