### ISSUE TITLE
Selecting Keg Tapper event reward does not give it in inventory

### ISSUE THREAD

**Issue by Evilmariel** [WarEmu/WarBugs#12912]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Selecting the lvl 40 Keg Tapper Reward from Champion Bjornir and clicking "Select".
Does not produce a Keg Tapper item in my inventory

Steps to reproduce the problem:
Select the lvl 40 Keg Tapper Reward as a lvl 40 zealot from Champion Bjornir and clicking "Select".

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/46075524/50378544-b3ef0c80-0602-11e9-8bfe-0917aa73efbe.png)

![image](https://user-images.githubusercontent.com/46075524/50378559-219b3880-0603-11e9-91e5-b111f7dbfc7c.png)

![image](https://user-images.githubusercontent.com/46075524/50378561-311a8180-0603-11e9-8ae9-a76ddbf2d99d.png)

**Comment by MaxHayman** [comment]
Fixed on next boot
