### ISSUE TITLE
Party Keg from Event does not activate to be used 

### ISSUE THREAD

**Issue by Evilmariel** [WarEmu/WarBugs#12913]
Expected behavior and actual behavior:
Right Click item "Party Keg" and I would expect it to place a keg on the ground my party and I could use for a xp/renown buff. But the keg does not appear and no status bar appears to cast it or anything.

Steps to reproduce the problem:
Right Click item "Party Keg" in City or RvR zone (tried both)

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/46075524/50378605-1ac0f580-0604-11e9-8f55-d2bb20b000f7.png)

**Comment by Xicoz** [comment]
ctrl right click will set it down

**Comment by Evilmariel** [comment]
ah okay, ctrl + right click does use it; I did not see the subtext on item
