### ISSUE TITLE
[vendor] shift-buy of armor -> gold gone, items not there

### ISSUE THREAD

**Issue by Tyramissoux** [WarEmu/WarBugs#1291]
If you try to buy more than one armor item via shift-buy, you won't get any items and your gold, equal to the total amount, is gone, too. 
Destro side.
New RR vendor.

**Comment by Radiantknight** [comment]
I Confirm.
Shift+rght clicked belt, wanted to get couple
entered the number, hit ok
Placed the icon in inventory (warning popped-up, not wearable item) nothing happened.
process repeated for every purchased item.
Result - gold lost, items not gotten.

**Comment by Evildoor** [comment]
Confirmed. This happens to any non-stackable item when you buy more than one at once. Same for gold and emblems.

**Comment by Luth-RoR** [comment]
Seems to be fixed.
