### ISSUE TITLE
[Quest] Recklessness (Avelorn, destro) Quest marker misplaced

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12911]
The quest marker for this quest is northeast of the warcamp, but the NPC you're supposed to talk to is in the warcamp itself.

![lodariel_001](https://user-images.githubusercontent.com/30193675/50377608-b1031480-0620-11e9-8398-68d5194b2d62.jpg)

![lodariel_000](https://user-images.githubusercontent.com/30193675/50377609-b5c7c880-0620-11e9-8fda-8d04e802497e.jpg)

**Comment by Kabucoror** [comment]
will be fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 30.12.2018
