### ISSUE TITLE
fireworks

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#12918]
Expected behavior and actual behavior:
if moving and you use a firework, it wont go off, it will just delete the item and it wont count towards quest, not a big problem, but pretty annoying lol

Steps to reproduce the problem:
I used blue fireworks and moved

Screenshots/Videos or archive.org evidences:
wasn't recording and screenshots cant help with this

**Comment by sioding** [comment]
Not a big - working as intended. Close

**Comment by Xicoz** [comment]
I'm genuinely confused, so it's supposed to delete the item? Shouldn't it just cancel the cast and you still keep the item untill you actually use it?
