### ISSUE TITLE
Ul Grod the Devourer

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#12928]
Expected behavior and actual behavior:
when you kill this Giant for the new event, you cant loot him sometimes, happens with other giants as well

Steps to reproduce the problem:
keep killing him and sometimes he glitches out

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/44329952/50386237-b6a43d00-06a8-11e9-908d-9b99158dec93.png)

**Comment by Xicoz** [comment]
![image](https://user-images.githubusercontent.com/44329952/50386268-16024d00-06a9-11e9-98fe-a53dc1b8262d.png)

happened again (solo killing and I have the golden hand when scrollin over body) so I have loot rights

**Comment by kejek** [comment]
I've noticed this happening if I swing and kill him after being knocked into the air. Not sure if just coincidence, but three times that I've killed him while flying through the air I couldn't loot.

**Comment by Lheana** [comment]
Event is no longer active.
