### ISSUE TITLE
Didn't receive goldbag 

### ISSUE THREAD

**Issue by StribjornRedwake** [WarEmu/WarBugs#12924]
hey Guys after Zone lock in talabecland 20 mins ago im not receifing my goldbag via ingame Mail 
i try to relogg /reloadui didn't workout would be nice if u can help me out here

**Comment by sioding** [comment]
Wait for the next server restart. These things happens sometimes. Normally the bags are delivered with the next restart. If not please help us with adding your ingame name here so we can have a look in the logs. But only if you not get the bag with the next restart.Thanks

**Comment by StribjornRedwake** [comment]
thank you for quick response !

**Comment by sioding** [comment]
No answer since 22 days - Close
