### ISSUE TITLE
Armor & Stat Potion buffs not showing

### ISSUE THREAD

**Issue by Evilmariel** [WarEmu/WarBugs#12927]
Expected behavior and actual behavior:
Use armor and stat potion; timers and buffs should remain displayed on UI.

Upon mounting or dying the timers/buffs disappear but the effect remains. 

Steps to reproduce the problem:
Use armor and stat potion and mount/die. May also happen on zoning?

Screenshots/Videos or archive.org evidences:
Str potion is showing but armor potion is not; it blinked for a second that my armor pot had 31mins remaining but armor pot buff disappeared when I mounted

![image](https://user-images.githubusercontent.com/46075524/50385376-aab57c80-06a2-11e9-9898-2b9fec6fb179.png)

**Comment by Natherul** [comment]
![image](https://user-images.githubusercontent.com/3688166/50423427-5f8f9b00-0855-11e9-857b-3d91f42033f7.png)
Unable to replicate this bug

**Comment by Evilmariel** [comment]
Hmm happened again as soon as I entered an SC one of my pots visually disappeared; popped fresh pots right before. Maybe its an issue with Pure UI.
![image](https://user-images.githubusercontent.com/46075524/50446253-23564c00-08e2-11e9-8e82-19585dad17ef.png)

Stats are still in effect at least

Before Pot:
![image](https://user-images.githubusercontent.com/46075524/50446261-2fdaa480-08e2-11e9-97f0-a0559055470c.png)

After:
![image](https://user-images.githubusercontent.com/46075524/50446266-39fca300-08e2-11e9-85d5-1c94763c406e.png)

**Comment by Evilmariel** [comment]
relogged and now its not happening when joining scenarios or aynthing /shrug

**Comment by MurkinUnderbush** [comment]
This is happening to me too the past 2 days. Have screen shots of before and after taking armor potions and there being no difference in the stats. My potions are 60 minute duration yet I just levelled to 19 and my armor potion which had 39mins remaining disappeared.

**Comment by Kaelang** [comment]
This no longer happens on the latest version of RoR.
