### ISSUE TITLE
Map & Mini Map Icons missing

### ISSUE THREAD

**Issue by kejek** [WarEmu/WarBugs#12923]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
I should be able to see merchants, mailbox, trainers, and group and warband members on the map and mini map. Currently I am unable to see anything on my level 40 Black Orc, Jeks. I have checked my settings and all options are checked. This does not happen on any of my other characters, and a full reinstall of the game seems to not help (so probably not a cache/user interface setting). I've also disabled addons to see if they had any affect.

Steps to reproduce the problem:
I'm unsure how to get this to happen. But it seems to follow my character jeks around.

Screenshots/Videos or archive.org evidences:
![jeks_005](https://user-images.githubusercontent.com/3529051/50382910-aec3a900-0666-11e9-8a4e-4f5cfd5a78ad.jpg)
![jeks_006](https://user-images.githubusercontent.com/3529051/50382912-b5eab700-0666-11e9-8287-4b4e571b8735.jpg)

**Comment by Jethammer** [comment]
I have same problem on my 25 lvl SM, Jetz. I have done same moves, reinstal the game, disable addons, but nothing helps. :(

**Comment by bigle1010** [comment]
I am having the same issues i have reloaded reset UI and nothing also found others online with the same issue

**Comment by bigle1010** [comment]
Any ideas on a fix for this i did a complete reinstall and still same issue and this makes game unplayable

**Comment by sioding** [comment]
don´t push reports. you may have noticed the day? Devs do also have familys....

**Comment by sioding** [comment]
I found a workaround on my side: Cancle the Quest "Pub Crawlers" - relog and all icons are back on the minimap

**Comment by Torquemadra** [comment]
Set profile to share in interface/profiles then rename your profile here \user\settings\Martyrs Square\PLAYER NAME log back in, then in interface/profiles map back to it worked for me.

**Comment by kejek** [comment]
Can confirm the work around, it also works completing the quest.

**Comment by MaxHayman** [comment]
Anyone still having this issue?
