### ISSUE TITLE
My sell panel for auction house

### ISSUE THREAD

**Issue by zageen** [WarEmu/WarBugs#12925]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Expected behavior: I can see only what I sell!
Actual behavior : my sell panel is link to someone else : it still show what i sell , but i show what someone else sell too ( it change over time so i supose that's not a visual bug).

Steps to reproduce the problem:

Open my "sell" panel , saw a lot of item i don't posess, interract with thm , error message , wait 2 day , see some item idspear and some more appear. Still can interract with MY items.

Screenshots/Videos or archive.org evidences:

![zag bug sell panel 01](https://user-images.githubusercontent.com/16636201/50384427-de090300-06c4-11e9-9d07-60c9a821d525.jpg)
![zag bug sell panel 02](https://user-images.githubusercontent.com/16636201/50384428-df3a3000-06c4-11e9-8b36-0e5af93ae894.jpg)
![zag bug sell panel 03](https://user-images.githubusercontent.com/16636201/50384430-e103f380-06c4-11e9-8474-747814fadbde.jpg)
![zag bug sell panel 04](https://user-images.githubusercontent.com/16636201/50384432-e3fee400-06c4-11e9-8ccf-e0b4aaaa60e1.jpg)
![zag bug sell panel 05](https://user-images.githubusercontent.com/16636201/50384434-e5c8a780-06c4-11e9-90c6-ec7bce9e40db.jpg)

**Comment by MaxHayman** [comment]
Whats your character name?

**Comment by zageen** [comment]
Zag

**Comment by MaxHayman** [comment]
Should be fixed next patch

**Comment by Kaelang** [comment]
This should now be fixed. Please re-open if issue persists.
