### ISSUE TITLE
 (Archmage) Balance Essence; can't move and cast even with high magic stacks

### ISSUE THREAD

**Issue by Memztron** [WarEmu/WarBugs#12921]
Expected behavior and actual behavior: Balance Essence with high magic stacks allows you to walk and cast. Right now it cancels when you start walking.

Screenshots/Videos or archive.org evidences: https://gyazo.com/a2897b28eacd0d20793825f2cc87cb16

**Comment by Memztron** [comment]
Same thing in bgs, just did this gif on closest enemy target, a rat.

**Comment by Torquemadra** [comment]
thanks, fixed next boot

**Comment by sioding** [comment]
fixed with patch from 30.12.2018
