### ISSUE TITLE
Quest Pub Crawlers

### ISSUE THREAD

**Issue by Lestrigon78** [WarEmu/WarBugs#12939]
Good day!
Today I ran into a problem with the passage of Pub Crawlers. Missing 1 of the objects on assignment. In this case, the earlier two characters this quest was completed. It was also seen that other players could not find this object. Please solve this problem.

ingame Nickname - Lestrigon

![lestrigon_000](https://user-images.githubusercontent.com/34790154/50394857-67760f00-0771-11e9-86a5-e4cf6709a9a4.jpg)

**Comment by Lheana** [comment]
Seems like it will be fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 30.12.2018
