### ISSUE TITLE
Reikland Factory Pathing Imbalance

### ISSUE THREAD

**Issue by Jaycub** [WarEmu/WarBugs#1293]
Order's placement of their forward most guard denies access to that side of the map via the top ramp, whereas destro's guard is far back enough order can use the top of the ramp to head to either the steam tank plant or warehouse via the routes coming from the destro spawn.

**Comment by Reggaewaldo** [comment]
I feel your concern. I will verify this and come up with a balanced solution.

**Comment by wiscel** [comment]
Today 2 White Lions were just running to the destro L56 Champ in the scen, the npc just stood there and did nothing. So, I tried with my sorc to go the Order side, as soon as I step on the ramp in the middle Im dead.
