### ISSUE TITLE
Corrupted Candy

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#12937]
Expected behavior and actual behavior:
Corrupted candy must still be on the loot tables, just found 2 of them in t1 rvr.

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/44329952/50388118-b02abb00-06d2-11e9-803a-e9afb07122da.png)

**Comment by Lheana** [comment]
It has been fixed.
