### ISSUE TITLE
Threat / Hate Reduction list 

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#12936]
Received this from a user a while back, seems there's some coding needed to get it implemented correctly. Adding to bugtracker per Torque's request for proper tracking and assignment. I have not verified these personally, but initial checks on a couple abilities seem to indicate the report is correct.

In general, detaunt should be reducing current hate by 50%, several other abilities should have a similar effect.

Careers:
Runepriest - Rune of Preservation - doesn't have "reduce hate" portion in tooltip.
             Grimnir's Shield doesn't affect hate. Tooltip states that "you generate almost no hate". Should work for both attacks and heals.
             For some reason Runepriest's attacks generate hate based on actual dealt damage not counting in anything that was mitigated.
Slayer - Distracting Roar - doesn't reduce hate
Engineer - Addling Shot - doesn't reduce hate
Bright Wizard - Smoke Screen - doesn't reduce hate
Witch Hunter - Get Thee Behind Me - doesn't reduce hate
Warpriest - Repent - doesn't reduce hate
Shadow Warrior - Distracting Shot - doesn't reduce hate
Archmage - Dissipating Hatred - doesn't reduce hate
           Walk Between Worlds - doesn't reduce hate
White Lion - Trained to Threaten - permanent buff that allows to gain only 25% hate with tactics Threatening Distraction. Doesn't require pet to be alive.
             Nature's bond generate no threat
             Submission doesn't reduce hate
Sorceress - Dread Aspect - doesn't reduce hate
Witch Elf - Enchanting Beauty - doesn't reduce hate
DoK - Terrifying Vision - doesn't reduce hate
Marauder - doesn't reduce hate
Magus - Horrifying Visions - doesn't have "reduce hate" portion in tooltip.
Zealot - Embrace the Warp doesn't affect hate. Tooltip states that "you generate almost no hate". Should work for both attacks and heals.
         Chaotic Blur - doesn't have "reduce hate" portion in tooltip.
Choppa - Outta My Face - doesn't reduce hate
Shaman - Look Over There - doesn't reduce hate
         Stop hittin' Me - doesn't reduce hate
Squig Herder - Don't Eat Me - doesn't reduce hate

Core:
Focused Offense - should generate 15% less hate. Doesn't work neither for attacks or heals
Subtlety - should reduce hate generation from heals by 25%. Doesn't work on heals. Works on attacks.
Goblin race tactic - Whazat Behind You?! - when procs heals generate 25% less hate

Common:
All detaunt abilities cause !generate! 50% less hate with detaunted mob. Which is totally useless for DPS classes.
Pet attacks generate no threat
Pet attacks don't break detaunt

**Comment by grunbag** [comment]
Fixed already
