### ISSUE TITLE
[BB]Lockouts

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#12930]
Long story short - we had no lockouts as group and killed first and second BB boss with no propblem and with loot.
Than whan we reached third one - on kill whole party got message that we killed boss we already had lockout and so no inf, no loot, nothing.
![unknown](https://user-images.githubusercontent.com/42712833/50387014-314e7600-0704-11e9-9ce9-4ce048bb4fcd.png)
![veszal_479](https://user-images.githubusercontent.com/42712833/50387010-1d0a7900-0704-11e9-8bca-8ef5b3db8a9e.jpg)

**Comment by Rockalypse** [comment]
Same with last boss.
![veszal_481](https://user-images.githubusercontent.com/42712833/50387137-301e4880-0706-11e9-9fd5-f667cd854b15.jpg)

**Comment by Rockalypse** [comment]
![veszal_482](https://user-images.githubusercontent.com/42712833/50387142-42988200-0706-11e9-976b-19c4347f9675.jpg)

**Comment by Rockalypse** [comment]
Can only speculate - It seems that current lockout restriction does not identify which lockouts you have in group for instance you are in. So when after first boss it sees that group has more than 2 lockouts (all 6 people have 1 or 2 - it thinks triggers), so you have no loot.

**Comment by anarchypark** [comment]
same happened in crypt. after necromancer kill which was no problem, 
next 2 bosses bugged and said we had lockout and prevented drop and kill counts.

**Comment by sioding** [comment]
already fixed
