### ISSUE TITLE
Burrows and Bloodwrought quest

### ISSUE THREAD

**Issue by Palitelj** [WarEmu/WarBugs#12945]
As you can se on picture, we killed all bosses but kill doesnt count for Bartholomeus the Sickly in new quest for talisman. We got loot and kill count in regular quest for Sentinel piece tho.

![skkar_007](https://user-images.githubusercontent.com/21026133/50406906-5c50cc80-07cd-11e9-8e84-97a9aa8e1f42.jpg)

**Comment by grunbag** [comment]
Still not fixed ?

**Comment by Kabucoror** [comment]
works fine on dev

**Comment by spacestarkid13** [comment]
Got this issue recently. No lockouts, fresh run and one boss kill didn't count for quest, but did count for lockouts.

![Warhammer Online - Age Of Reckoning Screenshot 2021 07 01 - 18 48 08 44](https://user-images.githubusercontent.com/16030337/124154258-ff20ea80-da9d-11eb-8500-662eb3481ee3.png)
