### ISSUE TITLE
Pack Hunting isn't removed upon removing tactic

### ISSUE THREAD

**Issue by SecretsOTheP** [WarEmu/WarBugs#12943]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior: 

Expected: Pack Hunting's 50% autoattack speed is removed on swapping the tactic out.
Actual: Pack Hunting's 50% autoattack speed is not removed on swapping the tactic out.

Steps to reproduce the problem: 

1) Equip the pack hunting tactic.
2) Unequip the pack hunting tactic and replace it with speed training.
3) Observe the buff bar, .getstats, and your pet's movement speed to notice that both Speed Training and Pack Hunting are applied as buffs.

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/319552/50404993-5c74ac00-077c-11e9-9bb6-febcbfb36e2b.png)

**Comment by Farlopa** [comment]
hi, i alredy report that the last week and my post was just closed with out comments and nothing

**Comment by SecretsOTheP** [comment]
This bug cropped up again. It was posted with comments. See here:

https://github.com/WarEmu/WarBugs/issues/12864#issuecomment-449585748

**Comment by sioding** [comment]
fixed with patch from 30.12.2018
