### ISSUE TITLE
Character Select Issue

### ISSUE THREAD

**Issue by Volaous** [WarEmu/WarBugs#12948]
So im pretty certain this is a new one 
![help me](https://user-images.githubusercontent.com/46114466/50408001-2f8ebc00-07b1-11e9-87f4-502ee28eedd4.png)
I was just selecting characters and was on my chosen but chose to play my warrior priest

**Comment by sioding** [comment]
And could you reproduce that?

**Comment by Volaous** [comment]
I could not in fact. Tried a few times but it never happened again

**Comment by sioding** [comment]
If you are - in any circumstances - able to reproduce it. please leave a comment here.
