### ISSUE TITLE
T1 Str pot removal when entering/exiting SC

### ISSUE THREAD

**Issue by merfp27** [WarEmu/WarBugs#12947]
In T1, the "Lasting potion of muscle" gets removed from character when entering or exiting a scenario.

It is not just a visual bug, as stats on character screen show a drop in STR and the armor buff remains.

![licwidswords_000](https://user-images.githubusercontent.com/46113768/50407426-dcaf0780-07a4-11e9-86ee-4b0427182cde.jpg)

![licwidswords_001](https://user-images.githubusercontent.com/46113768/50407429-e89ac980-07a4-11e9-80e1-8a74c1c764f0.jpg)

**Comment by Torquemadra** [comment]
paperdoll isnt 100% reliable, you would need to type .getstats while targetting yourself to have true values, the function is set correctly in DB and is on other potions which have not been reported

**Comment by sioding** [comment]
No answer since 20 days - Close
