### ISSUE TITLE
Live Event items can be obtained more than once

### ISSUE THREAD

**Issue by Folgrimma** [WarEmu/WarBugs#12949]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Expected: Receive influence reward once!
Actual: Able to claim influence reward multiple times. 

Steps to reproduce the problem:
Return to the Live Event influence npc and claim the item again.

Screenshots/Videos or archive.org evidences:

![image](https://user-images.githubusercontent.com/40577289/50417932-2f5ce380-07e6-11e9-880b-fce1ada0d843.png)
![image](https://user-images.githubusercontent.com/40577289/50417943-384db500-07e6-11e9-8fee-3dcf31098325.png)
![image](https://user-images.githubusercontent.com/40577289/50417946-3d126900-07e6-11e9-8c82-82c42264062f.png)
![image](https://user-images.githubusercontent.com/40577289/50417947-426fb380-07e6-11e9-805a-1312f84d11fe.png)

**Comment by MaxHayman** [comment]
Hello,

Can this still be done? I should have put in a fix for this a few days ago.

**Comment by sioding** [comment]
Hey @MaxHayman 
yes its still possible.

**Comment by Folgrimma** [comment]
@MaxHayman Can confirm still possible.

**Comment by Tyramissoux** [comment]
Keg Tapper can be claimed after each server restart as well. Cooldown is also refreshed.  (see screen)

![kegtapper](https://user-images.githubusercontent.com/13544944/50736298-34456e00-11bc-11e9-9839-0bf794ba061a.PNG)

Idea for the future: have a set date to exterminate the event slot items. Have them last from one event to the other (or a set date) and then just purge them all.

**Comment by MaxHayman** [comment]
Would this happen on relog? or when still in game?

**Comment by Tyramissoux** [comment]
Obtaining the Keg Tapper? That's bound to server restarts same as the other event items. If you just relog, you can't claim it again.
Tested this a few minutes ago because I know there was a restart today and now I own three Keg Tappers with different cooldowns.

**Comment by Folgrimma** [comment]
No all items are able to be obtained after relog I've tested this recently again.

**Comment by MaxHayman** [comment]
Should be fixed a few weeks ago.
