### ISSUE TITLE
Scavenging in group

### ISSUE THREAD

**Issue by amaurybrisou** [WarEmu/WarBugs#1294]
Hi all, thanks for all the work you do.

It appears that if someone isn't scavenger and is grouped with scavenger players, they can't scavenge mobs even if they had the killing blow.

Thanks

**Comment by amaurybrisou** [comment]
anyone has faced this problem ?

**Comment by MKorin** [comment]
If mob is killed by some1 who dont has scavenging, no1 can scaveng

**Comment by Luth-RoR** [comment]
Should work now.
