### ISSUE TITLE
Renown abilities - Improved flee rank 1

### ISSUE THREAD

**Issue by floatn** [WarEmu/WarBugs#12953]
I've learned Improved flee rank 1, it's displayed in charecter abilities window, but there's no effect.
The flee ability still lasts 10 seconds, instead of 15 seconds.

**Comment by grunbag** [comment]
it's disabled check wiki

**Comment by floatn** [comment]
Wiki, actually, states it as enabled ability. If you check it:
[Changes from Live: Renown Abilities > **Working** Renown Abilities > Actives > Improved Flee](https://wiki.returnofreckoning.com/index.php/Improved_Flee)
