### ISSUE TITLE
DoK - Path of Sacrifice

### ISSUE THREAD

**Issue by insultus** [WarEmu/WarBugs#12954]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by insultus** [comment]
all skills in the Path of Sacrifice tree have a minimum requirement of level 26. Pillage Essence obtainable at 21 doesnt appear to work or at least throws up an error "Your level is too low to use this ability"
![bollock_001](https://user-images.githubusercontent.com/35734524/50432261-8535a680-0920-11e9-837c-261070ecf772.jpg)

**Comment by Torquemadra** [comment]
it will still work a client value need ammending

**Comment by grunbag** [comment]
already fixed
