### ISSUE TITLE
Mercenary chest and officer emblem weapon for Swordmaster have ballistic skill on them.

### ISSUE THREAD

**Issue by elchewy** [WarEmu/WarBugs#12957]
The mercenary chest and officer emblem weapon have ballistic skill on them with is a stat-type is not correct for Swordmasters.  See screenshots

![elswordy_002](https://user-images.githubusercontent.com/46167620/50454067-61d12280-0945-11e9-85a9-b0bee4b1a9a0.jpg)

![elswordy_003](https://user-images.githubusercontent.com/46167620/50454111-a6f55480-0945-11e9-8ffb-05f8d2a77403.jpg)

**Comment by Torquemadra** [comment]
Falcata are for SW, use the Blade.

**Comment by Kabucoror** [comment]
Changed the Stats on the Chest to match it with the other Tank Merc Chests

**Comment by sioding** [comment]
Fixed with patch from 12.01.2019

**Comment by sioding** [comment]
Fixed with patch from 12.01.2019

**Comment by sioding** [comment]
Fixed with patch from 12.01.2019
