### ISSUE TITLE
chicken T1 bug in T4

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#12950]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

after turning into chicken you should be able to turn back if you teleport out of the zone but its not working 

Steps to reproduce the problem:

i stepped into t1 from the PVE side not warcamp (tried and was ok) side and once i turned into chicken i turned back fast and went to t4 and i was still chicken and that should be fixed  tried everything the only relog worked
did it twice and twice i wasnt able to turn back so i recorded the video on the second test

Screenshots/Videos or archive.org evidences:

[Video of the Bug](https://streamable.com/vwuy8)

**Comment by sioding** [comment]
fixed with patch from 30.12.2018
