### ISSUE TITLE
Ring of the horned rat

### ISSUE THREAD

**Issue by zageen** [WarEmu/WarBugs#12958]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

wanted to slot a lvl 24 134 armor tali in the ring
expected behavior : talisman is slotted and give the bonuses
actual behavior: Normal talisman cant be slotted in !

Maybe the jewel slot (since sentinel release) is a "special slot" , so only sentinel jewel can be slotted? (this item is 40 can't heppen)

try it with the band of doomsday (ring) to test?

Screenshots/Videos or archive.org evidences:

![zag_009](https://user-images.githubusercontent.com/16636201/50454291-d6f12780-0946-11e9-97dd-087a4011043d.jpg)
![zag_011](https://user-images.githubusercontent.com/16636201/50454306-eff9d880-0946-11e9-81fd-681677e606d2.jpg)

**Comment by Mausini** [comment]
You can only slot a talisman with a level requirement equal or smaller then the rings one.

**Comment by Kaelang** [comment]
Working as intended. 

![image](https://user-images.githubusercontent.com/60117106/82151241-753e9f80-9852-11ea-8fee-562592ecd4b9.png)
