### ISSUE TITLE
[Minor issue] Morale/tactics healing does not provide XP/RR

### ISSUE THREAD

**Issue by OldPlayer** [WarEmu/WarBugs#1295]
If healer uses healing morale (M1 usually), he does not get XP/RR for the healed target.
Same happens with tactics that provide additional healing, like Isha's Encouragement (Cleanse also heals the target)., no XP/RR for the target healed that way.

**Comment by Evildoor** [comment]
Don't know about tactics, but morales seem to be fixed. Anyone has info on tactics?

**Comment by Evildoor** [comment]
Since nobody reported anything on this point, i presume this was fixed.
