### ISSUE TITLE
Shroud of Magnus now totally reduce dmg from undefendable ability's

### ISSUE THREAD

**Issue by NabaroNya** [WarEmu/WarBugs#12959]
https://youtu.be/Fhw7wmJ9rQY
For example "Bolt of Change". Patch 22/12/2018. This is not in the patchnotes and skill description. Even m1 does not protect against such skills, cuz "undefendable".

**Comment by grunbag** [comment]
Fixed for next patch

**Comment by sioding** [comment]
fixed with patch from 13.07.2019
