### ISSUE TITLE
PRAAG Quest falling stars : Yegor Kovalyov

### ISSUE THREAD

**Issue by Gwlad** [WarEmu/WarBugs#12967]
NPC does not spawn at PQ location indicated, which is location for other : Tankred Pain, also required for the quest.

**Comment by sioding** [comment]
I can see him:

![image](https://user-images.githubusercontent.com/18517842/50519276-623efa00-0aba-11e9-9e42-ee54762d49c8.png)

But to be honest - i don´t really get the problem. Please explain it in more than 1 sentence.

**Comment by sioding** [comment]
No answer since 17 days - Close
