### ISSUE TITLE
[Quest] the sewers of altdorf 

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#12961]
speaking with npc Rhanz Folner doesn't update quest.

Screenshots/Videos or archive.org evidences:
![tok_sewer_0](https://user-images.githubusercontent.com/19988772/50463856-4e6b9900-09d1-11e9-8e3f-94b6cbe91f4d.jpg)

**Comment by Kabucoror** [comment]
Seems ok on dev server. Try to abandon and retake the quest.

**Comment by sioding** [comment]
and close.
