### ISSUE TITLE
[PQ] Contribution (dps\heal)

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#12962]
During my ~20 Gunbad runs I've noticed that it is far harder for healer to get purple/gold bag, than it is for dps.
On my healing DoK I got it only once and probably due to dps from Devour Essence, while as DPS it is almost always gold/purple with rare occasion of blue.
I dont realy know how I can provide sufficient enough proof for such thing, as at time I have not made screenshot of each bag roll, and I won't probably go gunbad as much anymore, but still, from my subjective point of view problem is presented as I was able to get redeye boots (or were it gloves?) only at the end of my Gunbad journey, after I got everything else, but shoulders. And to do that I had to roll as DPS DoK.

**Comment by sioding** [comment]
Hey @Rockalypse - thanks for the report. But to be honest - its not that you do not get any contribution in a PQ - its more that you feel like its too less compared to a DPS to have a real chance for higher bags correct? I am not sure this is the right place to discuss it. You don´t report a bug cause you get contribution - you just feel it should be more/or changed. For me its more a suggestion than a bugreport but i will try to get a clarify from a source dev for it.

**Comment by Natherul** [comment]
contribution works for healing in PQs and subsequently in instances. From the runs with my guild I can say that in that group there is no issue as it evens out who gets loot. 

Thanks for the report but I see nothing there that needs changing.
