### ISSUE TITLE
glitch under map in IC

### ISSUE THREAD

**Issue by Crindaz** [WarEmu/WarBugs#12969]
In IC at 28039 / 34332 are kegs and i jumped on 1 and i stuck in the keg then i typed /stuck and logged out then i logged back in and i went behind the gate 
![ones_007](https://user-images.githubusercontent.com/45179842/50514482-bb009980-0a9e-11e9-99c0-355a802b75e2.jpg) this gate but under the ground 
 
i wasnt able to send the video i posted it on youtube  https://youtu.be/q5bUO4CF1ZE

**Comment by sioding** [comment]
Hey - thanks for the report but to be honest we can not fix every glitch that brings you into these situations. you have the double /stuck or you get ported when you fall - thats ok and enough for it. That doesn´t mean we do try to fix those things - especially when they break the gamesyle but in this situation it does not - so sorry - i do close this now.
