### ISSUE TITLE
Renown Rank fall to 0 after SC

### ISSUE THREAD

**Issue by Oldneko** [WarEmu/WarBugs#12965]
same issu as a closed one
0 Renown after disconnecting from SC #4517 

Expected behavior and actual behavior:

renown rank is fall to rank 0 after sc win

Steps to reproduce the problem:
SC (Black Fire Basin) win and  Career rank 25 ding
Leaving sc caused me to get player select screen
I choose same character to play 
repop in altdorf (same place befor joining sc)

Screenshots/Videos or archive.org evidences:

![nekomusume_003](https://user-images.githubusercontent.com/43213086/50493303-f465e480-0a5f-11e9-941e-9c9d7eda2bd0.jpg)

![nekomusume_004](https://user-images.githubusercontent.com/43213086/50493332-2119fc00-0a60-11e9-84a7-4a9618e01bd4.jpg)

**Comment by Natherul** [comment]
Known display issue, your not actually the lower rank. Gaining a single point of renown syncs this up. Also for future reports hiding your name does not make it easier to find out more information. Thanks however for the report.
