### ISSUE TITLE
[Currency] New currency. 

### ISSUE THREAD

**Issue by Ripliel** [WarEmu/WarBugs#12974]
People have started to get currency which should not be implemented yet (I believe).
![unknown 1](https://user-images.githubusercontent.com/16005849/50536686-0763dc00-0b68-11e9-8be7-465b33c4b211.png)
![sealofthefaithful](https://user-images.githubusercontent.com/16005849/50536688-092d9f80-0b68-11e9-8818-b3c7bfd62395.png)

**Comment by notre4ror** [comment]
I got mine killing a low lvl Heroe.

**Comment by Lheana** [comment]
These items should no longer drop with next patch

**Comment by sioding** [comment]
fixed with patch from 30.12.2018

**Comment by tazdingo** [comment]
i recieved this as a drop today, killing nordland hero

**Comment by Lheana** [comment]
This? Can you be more precise?

**Comment by tazdingo** [comment]
> 
> 
> This? Can you be more precise?

i was lvling a fresh knight and notice i had a "seal of the missioner" in my inventory. only hero i had killed was ludvit in nordland

**Comment by Lheana** [comment]
Found where it came from: 2 Empire quests was giving automatically a Seal of the Missioner.
Will be fixed with next patch.

**Comment by sioding** [comment]
Fixed with patch from 02.03.2019
