### ISSUE TITLE
Quest: Good help is hard to find / unable to loot Tythos 

### ISSUE THREAD

**Issue by LunarF0X** [WarEmu/WarBugs#12971]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Unable to loot Tythos in the Bilerot Burrow

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

![carhillion_031](https://user-images.githubusercontent.com/45575531/50524715-5f5afe00-0ae8-11e9-931e-9930d6d691b3.jpg)
![carhillion_032](https://user-images.githubusercontent.com/45575531/50524717-6124c180-0ae8-11e9-9b9b-60d0a16fbe5f.jpg)

**Comment by grunbag** [comment]
Are you supposed to kill him ?

**Comment by Carhillion** [comment]
I guess that you should simply click on his body

**Comment by Cygre** [comment]
confirmed, corpse is here, but can't click or select the body on the floor, so no loot

**Comment by Lheana** [comment]
Indeed NPCs are usually there for a reason.
Tythos will be targetable with next patch, and should not be a problem when you fight the boss.

**Comment by sioding** [comment]
Fixed with patch from 03.08.2019

**Comment by sioding** [comment]
Fixed with patch from 03.08.2019
