### ISSUE TITLE
[BE] Rage of Khorne cant be cleansed with sever blessing ability

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#12977]
this buff has Blessing type but cant be cleansed by WE or Chosen

<img src="https://monosnap.com/image/zVapA8JyGC0T3BaMr8a0qZgmVJbGhF.png">

**Comment by sioding** [comment]
Talked to @grunbag about this and it´s intended. You have lost the damage race and the boss enraged. You should have an item from the miniboss before which you have to use here.
