### ISSUE TITLE
Repeatable quest marker missing

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#12973]
don't know why but this npc doesn't show the correct icon; in elf t2 "Faran Darkcloud", the analogue npc  (kills and keep), seems fine, as per #12481
![chimp_005](https://user-images.githubusercontent.com/17765890/50535168-47669700-0b47-11e9-9ab3-bc7d2f376b87.jpg)

**Comment by sioding** [comment]
Fixed next patch
![image](https://user-images.githubusercontent.com/18517842/50536881-961d2c80-0b59-11e9-840a-23ca7bc4c077.png)

**Comment by sioding** [comment]
fixed with patch from 30.12.2018
