### ISSUE TITLE
Von Rhine's Express

### ISSUE THREAD

**Issue by VonEpic** [WarEmu/WarBugs#12978]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
[Nordland] Killing Von Rhine does not complete objective "Kill Von Rhine"

Steps to reproduce the problem:
Took quest, abandoned quest, took quest again. Issue persists.

Screenshots/Videos or archive.org evidences:

**Comment by Lheana** [comment]
Works fine for me
![anaehll_409](https://user-images.githubusercontent.com/11537611/50542062-3a7f8d00-0bb3-11e9-9bff-0796e00864f3.jpg)

**Comment by Moragor** [comment]
I made this quest two days ago and I can confirm it working without problem.

**Comment by VonEpic** [comment]
Is there a level cap on who can complete it?

**Comment by Lheana** [comment]
No

**Comment by Lheana** [comment]
Maybe you were grouped, try out of a group

**Comment by sioding** [comment]
No answer for 21 days. Close
