### ISSUE TITLE
[PQ] Caledor Fortress

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#12976]
When you complete first stage the magic shield on door should dissapear, but it does not - we were able to kill door with AOE but still could not get in.
![veszal_494](https://user-images.githubusercontent.com/42712833/50540096-94288d00-0b9c-11e9-943f-5079876c1be3.jpg)

**Comment by Rockalypse** [comment]
Small update. Shield stil does not dissapear, but door is completely unattackable, so PQ cannot be done past stage 1.

**Comment by Lheana** [comment]
The issue with the barrier not disappearing after the second stage, should be fixed. And the door will be attackable again with next patch.

**Comment by sioding** [comment]
fixed with hotfix from 05.06.2019
