### ISSUE TITLE
[Quest] Assist the Daemoncaller (Norsca, destro) Quest objective doubled

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12979]
The quest objective  for this quest appears twice in the quest log. One of them works normally, the other gets autocompleted when receiving the quest.

![assit the deamoncaller 1](https://user-images.githubusercontent.com/30193675/50541396-5f6d0380-0ba5-11e9-89d4-fcad7c8db96e.jpg)
![assit the deamoncaller 2](https://user-images.githubusercontent.com/30193675/50541397-60059a00-0ba5-11e9-80ca-96fc54eab60c.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with first patch of the year 2019 (05.01.2019)
