### ISSUE TITLE
Burn Armor doing additional damage to keep bosses.

### ISSUE THREAD

**Issue by macredbaron** [WarEmu/WarBugs#12975]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
- Should do damage when keep lord performs a melee attack.

- Does many ticks of damage when keep lord casts "Be Gone"

Steps to reproduce the problem:
-Use Burn Armor so the debuff is on keep lord when he casts "Be Gone"

Screenshots/Videos or archive.org evidences:
![redbambina_000](https://user-images.githubusercontent.com/46230093/50539116-adb4df00-0b72-11e9-8281-eeeb13f3519b.jpg)
![redbambina_001](https://user-images.githubusercontent.com/46230093/50539117-adb4df00-0b72-11e9-87f2-54a968e8d879.jpg)
![redbambina_002](https://user-images.githubusercontent.com/46230093/50539118-adb4df00-0b72-11e9-8f38-cb05eeaa8d21.jpg)
![redbambina_003](https://user-images.githubusercontent.com/46230093/50539119-ae4d7580-0b72-11e9-8a6d-e8ba9bc0d2bb.jpg)
![redbambina_004](https://user-images.githubusercontent.com/46230093/50539120-ae4d7580-0b72-11e9-9234-d74ba38a3e33.jpg)
![screenshot_000](https://user-images.githubusercontent.com/46230093/50539122-ae4d7580-0b72-11e9-8490-020996576e15.jpg)

**Comment by macredbaron** [comment]
Few more from a different Keep boss
![redbambina_005](https://user-images.githubusercontent.com/46230093/50539796-5e74ab80-0b7e-11e9-90c2-75e670395a2c.jpg)
![redbambina_006](https://user-images.githubusercontent.com/46230093/50539797-5e74ab80-0b7e-11e9-8dd0-1cc64088c136.jpg)
![redbambina_007](https://user-images.githubusercontent.com/46230093/50539798-5f0d4200-0b7e-11e9-8e6e-cbeb1686c212.jpg)

**Comment by sioding** [comment]
Thanks - enough screens. The keep lords fights are special some abilities do not work like they do in other fights and thats intended. I will try to get the burn armor massive spam checked by a dev.

**Comment by grunbag** [comment]
Fixed for next patch
