### ISSUE TITLE
 trophy Vendor in ic dont sell the stuff that ror wiki says

### ISSUE THREAD

**Issue by Crindaz** [WarEmu/WarBugs#12970]
in IC in the libary the vendor Disciple Venomstung dont sell the stuff that i should get and doesnt even sell trophy i killed 1001 empires and i dont get / see the item at the vendors list and at the other i also cant find it

**Comment by Crindaz** [comment]
it should sell Empice Eradicator, One pip

**Comment by sioding** [comment]
fixed with patch from 30.12.2018
