### ISSUE TITLE
level up in rvr bolster

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#12972]
Expected behavior and actual behavior:
this was a problem before but was fixed, and is now a problem again, if you level up in rvr, you lose all benefits of bolster until you leave and come back, which is very inconvenient mid fight.

Steps to reproduce the problem:
level up in rvr with bolster

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/44329952/50531688-287aed00-0ad4-11e9-9f69-2ee1fa722e35.png)

**Comment by sioding** [comment]
fixed with patch from 30.12.2018
