### ISSUE TITLE
[NPC] Alvar (Quest: The Dark One, Norsca, destro) Hostile towards allies

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12986]
The NPC Alvar in Skaldbjorn in Norsca is hostile towards his allies. He is separated from other NPCs so usually it is no problem, but when pulling multiple enemies to fight them with AoE they start fighting each other.

https://streamable.com/cpxgv

**Comment by sioding** [comment]
fixed with patch from 30.12.2018
