### ISSUE TITLE
[Quest] A Norse Bargain (Nordland, destro) Debug quest object could be removed since original object is working

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12983]
I assume for debug reasons a lockbox was added right next to the quest giver, however the original lockbox near the windmill (PQ) is fully working and has a quest marker. The debug object could be removed to restore the original quest with all its sweet walking.

![a norse bargain](https://user-images.githubusercontent.com/30193675/50541537-5f223780-0ba8-11e9-8489-7e4387650fe3.jpg)

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
fixed with patch from 30.12.2018
