### ISSUE TITLE
[Quest] Wyrmbreaker Ch.20

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#12982]
Part of quest that leads you PQ The Senthoi Pool recquires you to:
*enter pool
*use item
*kill summoned mob

In current situation you are only able to use item, neither entering the pool registrating in quest entry, nor dragon appears when you use item.
![veszal_497](https://user-images.githubusercontent.com/42712833/50541507-63eee780-0bb8-11e9-8116-eb8f749803c1.jpg)
![veszal_499](https://user-images.githubusercontent.com/42712833/50541508-63eee780-0bb8-11e9-813c-458563fa49a6.jpg)

**Comment by Lheana** [comment]
There is no good way to implement this last step of the Epic Quest for now.

**Comment by Nekkbraka** [comment]
patch from 23/03/2019
- Wyrmbreaker: You are now able to read the Drakesinger Scroll only while targeting a Brazier Flame
- Wyrmbreaker: You are now able to place the Vile Dragonhelm on the Darktalon Dragon only while targeting and standing close to him


its still broken on last part.

**Comment by Lheana** [comment]
Maybe you need to stand closer to the Dragon

**Comment by notre4ror** [comment]
I've done recently the Epic quest "inevitable power", wich works fine if you done it alone.

You can do the same "trick" in this quest, 
instead of clicking an item in the backpack, put an object on the pool to sumon the Npc, 
you can do that while the devs finds another way to implement the original way.

**Comment by gobo-WarWizKing** [comment]
> I've done recently the Epic quest "Prophecy", wich works fine if you done it alone.
> 
> You can do the same "trick" in this quest,
> instead of clicking an item in the backpack, put an object on the pool to sumon the Npc,
> you can do that while the devs finds another way to implement the original way.

Not sure what you mean by "put an object in the pool". Drag something from you backpack to the pool > destroys object. Past that, I'll just put this quest on hold.

**Comment by notre4ror** [comment]
I mean istead of giving an object, put that object directly on the pool to click it.
Like the quest i'm saying, there is a mirror, you click it and spawns a mob in that place.
