### ISSUE TITLE
[Quest] The Dark One (2) (Norsca, destro) Quest markers missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12981]
The quest markers for the objectives "Find Bloody Pike", "Kill Norse Marauder" and "Kill Norse Picket" are missing.

![the dark one 3](https://user-images.githubusercontent.com/30193675/50541468-dce54380-0ba6-11e9-8cc6-28379b0d54d7.jpg)
![the dark one 4](https://user-images.githubusercontent.com/30193675/50541469-dd7dda00-0ba6-11e9-8a09-1ef966a90b3f.jpg)

**Comment by sioding** [comment]
@Kabucoror - i tried to set the questmarker in step one - but its not ok. please control also step 1 of the quest. This step - i did setup the questmarker but maybe they are also wrong. Please get in touch with @Lheana. I do stop working on that

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with first patch of the year 2019 (05.01.2019)
