### ISSUE TITLE
[Quest] Marked (2) (Nordland, destro) Original quest might be restored

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12985]
Currently looting the Temple Moneyhandler fulfills both quest objectives. Originally the objective "Forged Temple Records" was fulfilled by using the looted Temple Records in the inventory. Since using quest objectives works now (it was implemented in other quests I reported) the quest might be restored to its old glory.

![marked 2](https://user-images.githubusercontent.com/30193675/50541729-e3c28500-0bab-11e9-9e9e-3b79ef95ce30.jpg)

On a side note, the whole "Marked" quest line looks like one of the quest lines that "has been corrected and reworked" in the past few weeks (e.g. most of the quest have identical loot). I cant verify this but one of the database fairies might take a look at it :) .

**Comment by Kabucoror** [comment]
fixed with next patch. I removed the loots of some quests, your still able to get all three in this quest line
fyi atm it's not possible to turn in a quest by using an item and thanks for your many reports :)

**Comment by sioding** [comment]
fixed with first patch of the year 2019 (05.01.2019)
