### ISSUE TITLE
[Quest] The Dark One (Norsca, destro) Quest marker missing/misplaced/doubled

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12980]
The quest marker for the objective "Find Bloody Pike" appears twice at different positions while the markers for the other two objectives are missing.

![the dark one 1](https://user-images.githubusercontent.com/30193675/50541439-56c8fd00-0ba6-11e9-955b-e747271e824c.jpg)
![the dark one 2](https://user-images.githubusercontent.com/30193675/50541440-56c8fd00-0ba6-11e9-88c1-d54abbd4fe48.jpg)

**Comment by sioding** [comment]
@Kabucoror  - forgot this one ? Afaik is also fixed next patch

**Comment by sioding** [comment]
fixed with first patch of the year 2019 (05.01.2019)
