### ISSUE TITLE
Mork's Buffer doesn't work on group members after patch 

### ISSUE THREAD

**Issue by Yadizz** [WarEmu/WarBugs#12989]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Liczersky** [comment]
It wasn't for a wile, now it does.

**Comment by sioding** [comment]
so it is fixed or not ?

**Comment by Liczersky** [comment]
It works, I don't know was it fixed or was it just very long lag, but it works now
