### ISSUE TITLE
Innkeeper Bischof

### ISSUE THREAD

**Issue by JYELtheREAL** [WarEmu/WarBugs#1298]
He seems to be behind a closed door cause the door to the Inn cannot be opened

http://www.warbits.com/gold-quests-1197-Rooting-out-Corruption.html

**Comment by Evildoor** [comment]
I confirm. It was possible to talk to him before, now the door cannot be opened and there is no lever, therefore quest is impossible.

**Comment by Evildoor** [comment]
Found that this was already reported. https://github.com/WarEmu/WarBugs/issues/1243
