### ISSUE TITLE
[Quest] Marked (Nordland, destro) Quest objective duplicated

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12984]
The quest objective "Speak to Rat Catcher Thomas" is twice in the quest log, but you only have to speak him once (which completes the quest).

![marked](https://user-images.githubusercontent.com/30193675/50541618-e2905880-0ba9-11e9-8c5a-41e9e85387af.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with first patch of the year 2019 (05.01.2019)
