### ISSUE TITLE
[Tactic] Longer and Stronger (Choppa, Path of da Wrecka unlock) Tactic not working after a loading screen

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12987]
After equipping the tactic it worked as it should, but after I died and had a loading screen it wasn't doing anything anymore. You can see this in the following video, the tactic is equipped, but no heal is received.
https://www.youtube.com/watch?v=BJw7k18foXE&

I could reproduce this problem by dying some more (due to the lack of heal ಠ_ಠ). There seems to be a workaround by removing the tactic and reequipping it.

**Comment by sioding** [comment]
Does that also happen when you move in another zone like in avelorn or is it only on loading screens?

**Comment by Moragor** [comment]
It's strange, I'm no longer able to reproduce the problem, not even if I reenact the original situation 1:1. Must have been a temporary server hiccup that got fixed on restart.

**Comment by sioding** [comment]
OK @Moragor - i do close this one here. If you ever see this again it would be great to have a comment here.
