### ISSUE TITLE
[Disciple of Khaine] Devour essence skill

### ISSUE THREAD

**Issue by glasshands** [WarEmu/WarBugs#1299]
The tooltip says its got a range of 10 feet but it looks more like 30 feet.
![window_001](https://cloud.githubusercontent.com/assets/14142017/9701087/2fefd80e-53d8-11e5-89a7-30bf78057e8b.jpg)
I can hit that enemy form there.
I don't know if i am an idiot and missing something but that seems like it is larger than 10 feet to me.

**Comment by ozarmidrashim** [comment]
Fixed in next.
