### ISSUE TITLE
[Quest] A Weapon of Doom (2) (Caledor, destro) Quest end marker shown during quest, not at the end

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12999]
The quest end-marker for the NPC to turn in the quest is shown during the quest and disappears when the objective is fulfilled. Should be the other way around.

![a weapon of doom 2](https://user-images.githubusercontent.com/30193675/50554379-8fa5c680-0cb9-11e9-97c7-d275e15dcb2b.jpg)

**Comment by sioding** [comment]
Fixed with patch from 12.01.2019
