### ISSUE TITLE
[Quest] An Eye for Trouble (Caledor, destro) Invalid quest objective (Quest broken)

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12992]
The objective for this quest is broken, the quest can't be finished.

![an eye for trouble](https://user-images.githubusercontent.com/30193675/50554169-fe812080-0cb5-11e9-950f-eecbfeeea8a7.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with first patch of the year 2019 (05.01.2019)
