### ISSUE TITLE
[Quest] To Kill a Mage, Or Three (Caledor, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12997]
The quest markers for the objectives "Kill Direndys Draketongue" and "Kill Maledor Firestep" are missing.

![to kill a mage or three](https://user-images.githubusercontent.com/30193675/50554319-b3b4d800-0cb8-11e9-8abe-6c50a64c1c1d.jpg)

**Comment by sioding** [comment]
Fixed with patch from 12.01.2019
