### ISSUE TITLE
[Quest] A Taste of Their Own Medicine (Caledor, destro) Bolt thrower doing too few damage

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12994]
According to the description you should kill Drakeblade Attackers with the Eagle Claw. However the Eagle Claw does too few damage to kill them, they run towards you and then reset. You have to fight them the usual way to finish the quest.

![a taste of their own medicine](https://user-images.githubusercontent.com/30193675/50554233-5704ed80-0cb7-11e9-8292-7f47f7f62bbd.jpg)

Sidenote: "Speak to Captured Eagle Claw" should rather be "Use the Captured Eagle Claw".

**Comment by Kabucoror** [comment]
Corrected everthing else in this quest chain.
@sioding NPC damage is nothing DB related afaik

**Comment by Kabucoror** [comment]
Made the related NPC killed by one shot.
fixed with next patch

**Comment by sioding** [comment]
fixed with first patch of the year 2019 (05.01.2019)
