### ISSUE TITLE
[Quest] A Weapon of Doom (Caledor, destro) Quest end-marker shown during quest, not at the end

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12998]
The quest end-marker for the NPC to turn in the quest is shown during the quest and disappears when the objective is fulfilled. Should be the other way around.

![a weapon of doom 1](https://user-images.githubusercontent.com/30193675/50554370-6ab15380-0cb9-11e9-9a41-d19a418f8fe6.jpg)

**Comment by sioding** [comment]
Fixed with patch from 12.01.2019
