### ISSUE TITLE
[Quest] Unicorn Giblet Soup (Dragonwake, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12996]
The quest markers for the objectives "Speak to Zirbag Skibb" and "Unicorn Giblets" are missing.

![unicorn giblet soup](https://user-images.githubusercontent.com/30193675/50554290-3e490780-0cb8-11e9-8518-1b58cb0f9773.jpg)

**Comment by sioding** [comment]
fixed with first patch of the year 2019 (05.01.2019)
