### ISSUE TITLE
[Quest] Conquering the Isle (Caledor, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12995]
The quest markers for the objectives "Kill Drake Mage" and "Kill Erisina Fireheart" are missing.

![conquering the isle](https://user-images.githubusercontent.com/30193675/50554269-eca07d00-0cb7-11e9-8e4f-7b49215bdd15.jpg)

**Comment by Kabucoror** [comment]
whole Epic Quest will be available with next patch.

**Comment by sioding** [comment]
fixed with first patch of the year 2019 (05.01.2019)
