### ISSUE TITLE
[Quest] An Eye for Trouble (2) (Caledor, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#12993]
The quest marker for the objective "Wary Wavebreakers" is missing.

![an eye for trouble 2](https://user-images.githubusercontent.com/30193675/50554181-4dc75100-0cb6-11e9-9847-37267e31d6cd.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with first patch of the year 2019 (05.01.2019)
