### ISSUE TITLE
"Silencing the Cannons" does not have cannons quest item

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#13]
The cannons for doing the quest "Silencing the Cannons" are missing. Without them, the quest cannot be completed.
![silencing the cannons](https://cloud.githubusercontent.com/assets/7492543/2882561/08e922c4-d490-11e3-9113-c13147c99042.png)

**Comment by Reggaewaldo** [comment]
Tested this OK this quest you are not supposed to use the canons just kill the mobs for the quest.

This can be closed.

As a sidenote the cannons are properly spawned now.
