### ISSUE TITLE
[itiem](destru) wrong itiem interaction

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#130]
we should not suppose be able  to interact with order world objects ( edited as asked from#110)
![c6b31b72-d781-11e3-99ef-ecc29e53ec0e](https://cloud.githubusercontent.com/assets/7527415/2949401/76b01d3e-da0e-11e3-9c16-f716c5f215f6.jpg)
![cf2d0074-d781-11e3-8014-aedb5a1f4e48](https://cloud.githubusercontent.com/assets/7527415/2949402/76b482d4-da0e-11e3-8832-aceb14dfbc70.jpg)

**Comment by Razielhell** [comment]
You can't interact now. Added a check so only Order can interact/attack.
