### ISSUE TITLE
Blue oRvR loot bag won't open

### ISSUE THREAD

**Issue by LeighAnneS** [WarEmu/WarBugs#13006]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Got a blue bag in the mail yesterday. Coudnt open it. Relogging didn't help. Got another bad today and it opened fine. 

Steps to reproduce the problem:

See above 

Screenshots/Videos or archive.org evidences:

**Comment by Oldneko** [comment]
same issue occur to me.
but I dont remember I have got blue bags by this character in RvR or PQs recently.
SS above show bellow.


![chibineko_005](https://user-images.githubusercontent.com/43213086/51904786-e4487880-2402-11e9-9831-30807d814932.jpg)

**Comment by sioding** [comment]
Already fixed
