### ISSUE TITLE
Cannot Talk in /Advice (Spanish)

### ISSUE THREAD

**Issue by Kung-Tay** [WarEmu/WarBugs#13003]
I cannot type in /advice chat with the spanish pack. when i change it to english it allows me to writte at this chat. In Spanish "Advice" its "Consejo", but when i try to use /con it doesn't react.

**Comment by MaxHayman** [comment]
Seems to be the client is telling us the command it unknown before we receive it server side. I will get someone to have a look.

**Comment by Kaelang** [comment]
This should now be fixed. Please re-open if issue persists.
