### ISSUE TITLE
(Quest) Endin' da Feast 0 Destro Ch9 Barak Varr

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#1300]
Quest instructs to eliminate Shore and Coast Salamanders. Only Coast Salamanders are counted. Also, tracking shows up on Shore, but not on Coast.

http://i.imgur.com/a6qIRnq.png Quest description
http://i.imgur.com/uxBqpAT.png Shore Salamander
http://i.imgur.com/Gr8RQ2k.png Coast Salamander

**Comment by Reggaewaldo** [comment]
Looked it up and one live it seemed to feature both with 8 kills on both.
Added the Coast Salamander and made the requirement to kill 8.
