### ISSUE TITLE
Sewer Search quest

### ISSUE THREAD

**Issue by alxxqp** [WarEmu/WarBugs#13004]
The 2-nd step of the quests where you need to kill 15 enemy players in different zones OR in an Empire vs. Chaos SC's dont count enemy kills in scenarios. (not sure if Sacellum quests behave like that as well)

2 screenshots:
https://imgur.com/a/UwV7zvu

**Comment by alxxqp** [comment]
Seems like the issue is only with High Pass Cemetary scenario. Got the kills from Reikland Hills sc.

**Comment by Kabucoror** [comment]
Fixed with next patch. Added Reikland Factory too

**Comment by sioding** [comment]
fixed with first patch of the year 2019 (05.01.2019)
