### ISSUE TITLE
Sentinel Gloves Stats ?

### ISSUE THREAD

**Issue by Alvendo** [WarEmu/WarBugs#13007]
Hi,

Sentinel Gloves and Only this set item has "Intelligence" exist a reason for that? or its a "buggy stat"?

I saw it after dropping in Dungeon

Steps to reproduce the problem:

Fixt Int from the Sentinel Gear - to Toghness i think
![sentinel int](https://user-images.githubusercontent.com/25006922/50568384-4e60f580-0d51-11e9-85ce-2784eb6f393d.jpg)

Screenshots/Videos or archive.org evidences:

**Comment by wargrimnir** [comment]
Nothing buggy here. Your class uses intelligence, it gets those stats on all kinds of gear.
