### ISSUE TITLE
Sacellum questgiver NPC Anmorta Arhinosa not working

### ISSUE THREAD

**Issue by Alfred19** [WarEmu/WarBugs#13009]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.

I think i missed nothing.

**Expected behavior and actual behavior:**

The NPC should give the 5th Quest for the sacellum dungeons.
NPC doesnt, making Keepers Set unobtainable in the end

**Steps to reproduce the problem:**

Go to IC 414:383 or vipers pit and try to pick up the quest.

**Comment by Kabucoror** [comment]
fixed with next patch, but viper pit is working right now

**Comment by sioding** [comment]
fixed with first patch of the year 2019 (05.01.2019)
