### ISSUE TITLE
RvR Quest Chaos Wastes - The Fight Against Madness

### ISSUE THREAD

**Issue by Sinrman** [WarEmu/WarBugs#13002]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Expected - Capture a keep in Chaos Wastes

Actual - No credit for capturing keep.

Steps to reproduce the problem: You can see in chat section that I captured Zimmeron's Hold in Chaos Wastes but recieved no credit for quest.  Was in warband from the beginning of attack on keep through dpsing the lord from 100% to 0.
![gunnr_000](https://user-images.githubusercontent.com/42098334/50560987-d6042100-0ccb-11e9-85cd-ece433d10932.jpg)

Screenshots/Videos or archive.org evidences:

**Comment by Kabucoror** [comment]
with next patch both keeps in a T4 zone should count.

**Comment by sioding** [comment]
Fixed with patch from 19.01.2019
