### ISSUE TITLE
Pounce can be used to get on some keeps

### ISSUE THREAD

**Issue by SecretsOTheP** [WarEmu/WarBugs#13015]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior: Pounce works to get on walls at some keeps (ie; north keep in praag, on the outer wall on the right side facing the keep)
Actual behavior: Pounce does not work for climbing walls

Steps to reproduce the problem: 
1) Have an enemy player stand at the edge of the wall
1a) Position your player near the oil on the ground where the terrain slightly points up
2) Pounce at the enemy player
3) Be catapulted up on the keep walls

This works for both WL, SM and Squig Herder pounce abilities

The z difference at which you can pounce needs to be adjusted a few meters.

Screenshots/Videos or archive.org evidences: N/A, but can provide if needed

**Comment by dalen** [comment]
Fixed by 2020-09-09 patch
