### ISSUE TITLE
Magus pet summons with different amounts of abilities

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#13011]
Issues should be unique. Check if someone else reported 
Expected behavior and actual behavior:
the magus pet in low levels spawns without any skills and sometimes with 2 skills, making it very inconvenient if you fight in an SC and you have to resummons your pet mid fight to find out you have to summon it again if you want the 2 skills, and this has undoubtedly gotten me killed many times, id say its a 50/50 if it will have skills or not.

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/44329952/50577206-d7773b80-0de8-11e9-86a8-fc5dcedfe31b.png)

**Comment by grunbag** [comment]
Fixed with previous patch
