### ISSUE TITLE
Unable to turn in The Power of War

### ISSUE THREAD

**Issue by vikingofmars** [WarEmu/WarBugs#13018]
Expected behavior and actual behavior:

 I have completed The Power of War but on attempt to turn in i get an error saying: "Cannot salvage. Inventory overflowing. Open backpack to remove overflow." My backpack is not full.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

<img width="960" alt="pow1" src="https://user-images.githubusercontent.com/37393516/50599448-27eba900-0e7c-11e9-8bc6-0756bfb463df.png">

<img width="960" alt="pow2" src="https://user-images.githubusercontent.com/37393516/50599468-34700180-0e7c-11e9-9bfd-5bb91b59dc31.png">

~ Skurrga 'Eadcleava

**Comment by Lheana** [comment]
Must be you Currency Items inventory which is full

**Comment by sioding** [comment]
Can you please give us a screenshot from your currency bagpack?

**Comment by sioding** [comment]
solved. Close
