### ISSUE TITLE
T1 Chicken

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#13013]
Expected behavior and actual behavior:
I flew to t1 as a 40bo and instantly got turned into a chicken, then left went to a non RVR part of Mount Bloodhorn where I remained a chicken, trying to get to the gutslime lair as a chicken, I died many times via 1shot by mobs, frustrated at being a chicken for 30minutes I logged out for several hours, logged back in, still a chicken. recent patch notes say this was fixed, but i'm still struggling with it badly, please fix so I can do the gutslime lair. I attached a SS of me outside the RVR zone after logging back in from a 3+ hour break to still being a chicken.
 
Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/44329952/50580963-a0218280-0e1a-11e9-8bc9-a39fad36c8bd.png)

**Comment by Xicoz** [comment]
maybe 30minutes later of sitting here in game, not being able to unflag from rvr and still bein a chicken.
![image](https://user-images.githubusercontent.com/44329952/50581004-f7bfee00-0e1a-11e9-908b-b78f094c84d3.png)

**Comment by gittoaster** [comment]
I experience same issue now in Nordland/Order.  Try to go to windmill PQ and try unlog/relog, die and I respawn as a chicken again.
Before this was only occurring in the starter area, now it seems all across starter zone?

**Comment by sioding** [comment]
fixed with patch from 06.07.2019
