### ISSUE TITLE
Cant enter city instance

### ISSUE THREAD

**Issue by Treygus** [WarEmu/WarBugs#13019]
Cant enter any BB/BE when i have full red eye. have relogged and still cant get in and have it equiped.

![49388137_636011440135482_8140306478805286912_n](https://user-images.githubusercontent.com/46328350/50608019-21cceb00-0ec3-11e9-8184-e92868a932cf.jpg)
![49673870_2103971989686641_6770034507757125632_n](https://user-images.githubusercontent.com/46328350/50608025-25f90880-0ec3-11e9-8c1e-862628118c8d.jpg)

**Comment by sioding** [comment]
Can we please see a screenshot from your tok with the redeye set open?

**Comment by Treygus** [comment]
I will when I'm back home.

**Comment by Treygus** [comment]
This what you wanted?
![49371957_224295478459774_8269841674545397760_n](https://user-images.githubusercontent.com/46328350/50649959-1a671980-0f77-11e9-896f-fdd3415864a4.jpg)
![49592431_1023939421139616_4569789187980525568_n](https://user-images.githubusercontent.com/46328350/50649966-1dfaa080-0f77-11e9-8c7d-c8541bb07159.jpg)

**Comment by sioding** [comment]
Thanks

**Comment by Treygus** [comment]
Just an update I was able to get into to bb/be before wards was added, I did have 1 part sentinel.
![jpeg_20181118_152437](https://user-images.githubusercontent.com/46328350/51036671-b4494a80-15a5-11e9-8990-8acc48617f65.jpg)

**Comment by Treygus** [comment]
Just tried a right wing gunbad run and killed the last boss but no update or anything. Still cant enter bb/be.

**Comment by Hargrim** [comment]
Well it should work. Make sure to take of and equip again the Redeye set. Do you have The Redeye title available in ToK? Also, you can press this button to take screenshots: 

![image](https://user-images.githubusercontent.com/16460565/51792311-82dc9b80-21af-11e9-8534-14bda610e45c.png)

**Comment by Torquemadra** [comment]
Tested on Rihard, Toks are missing for the complete set and title, problem identified, over to source.

**Comment by Treygus** [comment]
Any news on this problem? really want to move on with my pve gear.

**Comment by Lest0r** [comment]
Can you find out about solving the problem?

**Comment by Treygus** [comment]
Hangrim fix this for me, I'm able to enter BB/BE now.

**Comment by Lest0r** [comment]
On my character, the problem has been preserved, there is no title for the full set and does not allow it in the dungeon

**Comment by Treygus** [comment]
Try speaking to Hargrim on discord might be able to help

**Comment by Lest0r** [comment]
No, you can go to the discord, as there is a big problem with the language-)

**Comment by Kaelang** [comment]
Are you still experiencing these problems?

**Comment by Treygus** [comment]
No I'm not anymore after it was fixed by Hargrim.
