### ISSUE TITLE
Game wont load in character

### ISSUE THREAD

**Issue by Osheybo** [WarEmu/WarBugs#13012]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Game loads in character
Game crashes while loading even after typing /stuck in the loading screen

Steps to reproduce the problem:

Just attempting to load in

**Comment by sioding** [comment]
No answer for 17 days. Close.
