### ISSUE TITLE
Siege weapon / can not use abilities when it dies

### ISSUE THREAD

**Issue by Liczersky** [WarEmu/WarBugs#13017]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
If you use siege weapon and it has been damaged, you can not use any skill. Effect persist until you die and respawn or resurrect.

Steps to reproduce the problem: Get in the siege weapon, stay until it is completely damaged. Try to use any skill.

Screenshots/Videos or archive.org evidences:

**Comment by Natherul** [comment]
this should have been fixed since a few patches. if not please report back
