### ISSUE TITLE
RVR reward splitting no rewards

### ISSUE THREAD

**Issue by Green-Wolf** [WarEmu/WarBugs#1301]
When I killed someone in RVR solo just now there were no rewards at all, no xp, inf or renown.

**Comment by Green-Wolf** [comment]
happened a few more times again, defiantly something wrong here.

**Comment by Natherul** [comment]
just did a whole scenario, I can confirm. I got no renown and no xp -.-

**Comment by Natherul** [comment]
you need to manually join the scenario group for any renown and xp gain to work in Scenario... .

**Comment by Stavoz** [comment]
No space in the wb, solod someone to almost dead and some stole the death blow (1 ability) and recieved 0 xp, 0 rp, 0 inf.

**Comment by SharpiesOfWar** [comment]
I had this happen today. I was in the rvr lake solo and found another player in the open. I soloed the player and killed him but got no xp, rp, inf. He was full health when I started attacking him and no one else was around. I was in Nordland and it happened near the docks.

**Comment by Luth-RoR** [comment]
This happens due to custom code to prevent players from kill trading. No bug, intended.
