### ISSUE TITLE
file so many...

### ISSUE THREAD

**Issue by BaebSae** [WarEmu/WarBugs#13024]
File downloads 171702. Is there something wrong? Originally? Or are you having trouble setting up? I used an official file.

![12323](https://user-images.githubusercontent.com/46365117/50674255-daac3a80-1027-11e9-81e8-759fd332975d.PNG)

**Comment by sioding** [comment]
Sorry but this is not a bug. Pease use out forum for these things: https://www.returnofreckoning.com/forum/viewforum.php?f=4
