### ISSUE TITLE
[Quest] Bloodfeather (Troll Country, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13028]
The quest marker for the objective "Kill Teleir Featherwhisper" is missing.

![bloodfeather](https://user-images.githubusercontent.com/30193675/50678699-50041500-1000-11e9-80ce-b60ebdcb5ebe.jpg)

**Comment by sioding** [comment]
Fixed with patch from 12.01.2019
