### ISSUE TITLE
Altdorf Sewers - heros oneshotted

### ISSUE THREAD

**Issue by l2hart** [WarEmu/WarBugs#13021]
Hello,
today during visiting the Altdorf severs w our party noticed (as we think) bug, during hero fight he sudenly died like leathal strike (he had 80% hp). During full severs run almost all heroes was killed that way. Group members was: slayer/witchhunter/2x bright wizzard/archmage/rune priest. Those "lethal" kills wasnt intentional just happend.

Cheers
ur slayer

**Comment by sioding** [comment]
Hey guys - or whoever this reads. We need more information on this problem. Would be great to see a video with things like this happen cause its kinda hard to reproduce it.

**Comment by l2hart** [comment]
It will be hard to reconstruct. But... as i talked with WH he said he did severs run again after we did it together and that didnt happend again so conclusion is thats the bug of slayer or BW skills/ability. I will try to make some run to check is it me and then give here feedback.

**Comment by l2hart** [comment]
During todays run i didnt notice oneshot kill so it must be BW bug

**Comment by sioding** [comment]
Thanks for the feedback. Since its not really reproducable we aren´t able to "fix" it. Since i scan every incoming report - i will take care if a new message comes in with this behaviour.
