### ISSUE TITLE
[Quest] Dregs of Vengeance (Troll Country, destro) Quest marker mising

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13025]
The quest markers for the objectives "Kill Order Handgunner" and "Kill Order Swordman" are missing.

![dregs of vengeance](https://user-images.githubusercontent.com/30193675/50678464-11ba2600-0fff-11e9-98c0-d2a031a9a1ab.jpg)

**Comment by sioding** [comment]
Fixed with patch from 12.01.2019
