### ISSUE TITLE
[Quest] A Cold Heart (Troll Country, destro) Quest markers mising

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13027]
The quest markers for the objectives "Examine the Ancient Urn" and "Bleeding Heart Dagger" are missing.

![a cold heart](https://user-images.githubusercontent.com/30193675/50678574-a0c73e00-0fff-11e9-89aa-d91243b7a56c.jpg)

Side note: This quest might be a candidate for a rework, but I don't know if anything could be done at the moment.

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
