### ISSUE TITLE
[Scenario] Death at start in Tor Anroc

### ISSUE THREAD

**Issue by Tyramissoux** [WarEmu/WarBugs#1302]
When entering Tor Anroc at start, you often (not always) drop dead after loading as destro. Maybe stuck dmg? http://www.twitch.tv/tyra_missoux/v/14626378 Starting spawn point seems to be misplaced sometimes.

**Comment by Evildoor** [comment]
Sometimes you just take damage and survive. According to combat log, it's Lava damage.

**Comment by wargrimnir** [comment]
No longer an issue.
