### ISSUE TITLE
Abilities not working correctly. Witch Elf & Zealot

### ISSUE THREAD

**Issue by 4cobbi** [WarEmu/WarBugs#1303]
Zealot ability Breath of Tzeentch does not work correctly. It does not knock back players or knockdown mobs.

Witch Elf ability Heart Render Toxin does not apply the correct wounds debuff according to blood lust. Regardless of how many stacks of blood lust you have it always places the amount from having 1 stack of blood lust.

**Comment by ozarmidrashim** [comment]
None of the knockdowns affect mobs - BoT works on players.
