### ISSUE TITLE
[Quest] Hopeslayer (Troll Country, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13030]
The quest marker for the objective "Kill Trovolek Seer" is missing.

![hopeslayer](https://user-images.githubusercontent.com/30193675/50678827-d91b4c00-1000-11e9-872c-c834ae9d7965.jpg)

**Comment by Lheana** [comment]
Thanks for report.
Will be fixed with next patch. I also changed the number of kills required

**Comment by sioding** [comment]
Fixed with patch from 12.01.2019
