### ISSUE TITLE
[Quest] Mourning Beauty (Talabecland, destro) Quest markers need overhaul

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13035]
The existing quest marker contains additional text which does not belong there while the second marker is missing.

![mourning beauty 1](https://user-images.githubusercontent.com/30193675/50679675-c0ad3080-1004-11e9-8747-68dcd485b429.jpg)
![mourning beauty 2](https://user-images.githubusercontent.com/30193675/50679679-c30f8a80-1004-11e9-84a2-c3de31cd339a.jpg)

**Comment by sioding** [comment]
Fixed with patch from 12.01.2019
