### ISSUE TITLE
[Quest] Killing Frenzy (Troll Country, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13031]
The quest marker for the objective "Blighted Trolls" is missing.

![killing frenzy 1](https://user-images.githubusercontent.com/30193675/50678905-37482f00-1001-11e9-93eb-23eea3f5cc5f.jpg)
![killing frenzy 2](https://user-images.githubusercontent.com/30193675/50678911-3adbb600-1001-11e9-82f8-7de7f440b6d6.jpg)

**Comment by sioding** [comment]
Fixed with patch from 12.01.2019
