### ISSUE TITLE
[Quest] "Rat Men?" Altdorf. Dungeon sewer.

### ISSUE THREAD

**Issue by Paleolog77** [WarEmu/WarBugs#13039]
Killing questmobs not up the quest.
![paleo_002](https://user-images.githubusercontent.com/23325288/50681488-bbf47680-101c-11e9-9137-517ab98c38f9.jpg)

**Comment by Lheana** [comment]
Works fine for me
![lheawll_004](https://user-images.githubusercontent.com/11537611/50684198-ecd0ad80-1014-11e9-887e-79f7ad3eccb3.jpg)

**Comment by sioding** [comment]
ok i close this one here. its enough to have this one open #13038 for the group and questobject problem
