### ISSUE TITLE
[Quest] "Spotting Trouble" Altdorf. Dungeon sewer.

### ISSUE THREAD

**Issue by Paleolog77** [WarEmu/WarBugs#13038]
Killing questmobs not up the quest.

![paleo_000](https://user-images.githubusercontent.com/23325288/50681267-f27dc180-101b-11e9-8ca1-d5541442bddc.jpg)

**Comment by Lheana** [comment]
Works fine for me.

**Comment by Paleolog77** [comment]
Confirm, quest up in solo, but not up in party (1st screenshot).
![paleo_001](https://user-images.githubusercontent.com/23325288/50685822-cc601d80-102b-11e9-9ab4-c6f0b65d1f0e.jpg)

**Comment by Paleolog77** [comment]
Conducted additional research on this issue. Possible the most likely cause of the problem: the bug was discovered when passing in the full group and the group was a player at a much lower level than the mobs.

**Comment by Lheana** [comment]
#12470
