### ISSUE TITLE
[Item] Scout's Emblems hard to get due to T2+T3 merge

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13037]
I was playing a Marauder mainly by doing SCs and hunting quest bugs and witnessed a problem, due to the T2+T3 SC merge I solely got Soldier's Emblems, no Scout's Emblems. Since SCs yield less renown than open RvR and breaking down Soldier's Emblems requires RR20 it's hard to get T2 SC items before you're eligible for T3 SC items. This problem was also confirmed by a guild mate.
My recommendation: Lower the RR needed to break down Soldier's Emblems to Scout's Emblems to RR10 as long as T2 and T3 SCs are merged.

![scouts emblem](https://user-images.githubusercontent.com/30193675/50680502-3e267000-1008-11e9-91a8-12a366ca2f5f.jpg)

**Comment by Kabucoror** [comment]
The RR requirement is lowered to 15 with next patch

**Comment by sioding** [comment]
Fixed with patch from 12.01.2019
