### ISSUE TITLE
[Quest] Questionable Motives (Troll Country, destro) Quest item not implemented

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13032]
According to the quest description you should use the "Burning Drought" in your inventory, but instead the objective completes on the first kill. Since quest items are usable now this can be restored.

![questtionable motives](https://user-images.githubusercontent.com/30193675/50679058-0e746980-1002-11e9-90a7-9ec038956248.jpg)

**Comment by sioding** [comment]
Fixed with patch from 12.01.2019
