### ISSUE TITLE
[Gunbad] Broken Looting 

### ISSUE THREAD

**Issue by Ripliel** [WarEmu/WarBugs#13043]
Expected behavior and actual behavior:
You loot the boss - get a gear.

WP in the group used the portal before we could loot the corpse, Then the body changed its location and became impossible to loot. After some time such message appeared in the chat and no one got the loot (Only one guy in the group had a lockout for this boss)
![ripliel_164](https://user-images.githubusercontent.com/16005849/50693069-f246eb80-1046-11e9-9d87-3e8c66b8d17b.jpg)
![drop](https://user-images.githubusercontent.com/16005849/50693074-f6730900-1046-11e9-87cc-24a39a3f5023.PNG)

**Comment by grunbag** [comment]
fixed already
