### ISSUE TITLE
[Quest] Half-Men (High Pass, destro) Quest markers missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13046]
The quest markers for the objectives "Kill Oathbearer Miner" and "Kill Oathbearer Warrior" are missing.

![half men](https://user-images.githubusercontent.com/30193675/50702041-02af9400-1050-11e9-9401-4a767eddbf2e.jpg)

Note: One of the miners is down at the frozen lake, make sure the marker includes him.

**Comment by sioding** [comment]
Fixed with patch from 19.01.2019
