### ISSUE TITLE
[Quest] Rate of Attrition (High Pass, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13044]
The quest markers for "Kill Kulian Black Knight", "Kill Kulian Bonearcher" and "Kill Kulian Bonewarrior" are missing.

![rate of attrition](https://user-images.githubusercontent.com/30193675/50701869-65546000-104f-11e9-9e26-d9bcabcd8544.jpg)

**Comment by sioding** [comment]
Fixed with patch from 12.01.2019
