### ISSUE TITLE
[Weapon] Titan's Bigloppa of Brutality

### ISSUE THREAD

**Issue by Tyrean** [WarEmu/WarBugs#1304]
Evening !

I have a bug Whit this weapon i cant slot 1 strengh and 1 Toughness Talis on this weapon ! Equip desequip and relog dont working.

**Comment by Evildoor** [comment]
This problem still persists? Are you sure that it is some new bug tied to item, and not the general problem that sometimes your talisman window bugs out and you have to exit game (exit completely, not relog) and log in again?

**Comment by Evildoor** [comment]
2 weeks, no response... I guess the problem was fixed.
