### ISSUE TITLE
[UI] All quest end-markers disappear on logut

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13047]
Not sure if this was reported before, at least I couldn't find a ticket. However, Lheana mentioned it in ticket https://github.com/WarEmu/WarBugs/issues/12616.

The problem is, that the quest end-markers which show the position of the NPCs to turn in quests disappear on logout. Neither turning the quest markers off and on again nor /reloadui seem to fix this problem.

Position markers after completing some quests:
![end marker 1](https://user-images.githubusercontent.com/30193675/50702566-90d84a00-1051-11e9-9e1c-3ca051b4074a.jpg)

Markers are gone after a relog:
![end marker 2](https://user-images.githubusercontent.com/30193675/50702582-9cc40c00-1051-11e9-8d95-9c84645869dd.jpg)

Related: The markers in the NPC dialog window of quests affected by the bug are gray instead of orange. Normally only uncompleted quests are gray.
![end marker 3](https://user-images.githubusercontent.com/30193675/50702715-09d7a180-1052-11e9-9b56-8f0e9f02cd3f.jpg)

**Comment by MaxHayman** [comment]
Fixed next patch

**Comment by sioding** [comment]
fixed with patch from 29.6.2019
