### ISSUE TITLE
[Quest] Beasts for the Raven God (Talabecland, destro) Possibly wrong NPC assigned to quest

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13042]
This quest was always a bit tedious since it only had two hounds but you needed five (according to https://github.com/WarEmu/WarBugs/issues/2741 originally 10). Now there is only one hound left, forcing you to wait 4 times for respawn. The second hound apparently was removed when the quest "Battlestained" (2nd(?) in quest line) was re-implemented with the patch from 15/12/2018 to which the Steelfang Hound actually belongs.

I just can't imagine, that this is the right NPC to kill in this quest.

![erdhall_000](https://user-images.githubusercontent.com/30193675/50686876-52299c00-101f-11e9-8946-196ae9168c09.jpg)
![erdhall_001](https://user-images.githubusercontent.com/30193675/50686879-548bf600-101f-11e9-9aab-407500322a1f.jpg)
![erdhall_002](https://user-images.githubusercontent.com/30193675/50686884-581f7d00-101f-11e9-8752-4eca88f32008.jpg)
![erdhall_003](https://user-images.githubusercontent.com/30193675/50686887-5b1a6d80-101f-11e9-8e15-7fdcdaa09d5b.jpg)

**Comment by Lheana** [comment]
Several NPCs will now count toward the quest:
- Savage Gorehide Boar
- Gorehide Boar
- Deathridge Shriller
Note nevertheless that for now only one will be displayed for the name of the objective, but the three count.

**Comment by sioding** [comment]
Fixed with patch from 12.01.2019
