### ISSUE TITLE
[Quest] "Poor Gustav!" Altdorf. Dungeon sewer. Bug #1.

### ISSUE THREAD

**Issue by Paleolog77** [WarEmu/WarBugs#13040]
Killing questmob not up the quest.
![paleo_003](https://user-images.githubusercontent.com/23325288/50681775-bd726e80-101d-11e9-8734-9e1beb822f29.jpg)

**Comment by Lheana** [comment]
Works fine for me
![lheawll_007](https://user-images.githubusercontent.com/11537611/50684314-55b82580-1015-11e9-94cd-c6f759ccc0dd.jpg)

**Comment by sioding** [comment]
ok i close this one here. its enough to have this one open #13038 for the group and questobject problem
