### ISSUE TITLE
[Quest] "Poor Gustav!" Altdorf. Dungeon sewer. Bug #2.

### ISSUE THREAD

**Issue by Paleolog77** [WarEmu/WarBugs#13041]
Active quest not show on map (middle sewer).
![paleo_004](https://user-images.githubusercontent.com/23325288/50681871-01657380-101e-11e9-9bde-a7d987a10a4f.jpg)

**Comment by sioding** [comment]
fixed with first patch of the year 2019 (05.01.2019)
