### ISSUE TITLE
[Quest] The Scrying Game (Caledor, destro) NPC offering two quests with the same name at the same time

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13048]
The NPC "Vashnar" is offering two quests with the same name at the same time. Identical names usually are usually used in chained quests.

![quillog_001](https://user-images.githubusercontent.com/30193675/50705986-c9315580-105c-11e9-8263-e68de546e40e.jpg)

**Comment by sioding** [comment]
Fixed with patch from 19.01.2019
