### ISSUE TITLE
[Keg's End] Giant kills/Fireworks not updating quest.

### ISSUE THREAD

**Issue by Eggs** [WarEmu/WarBugs#13052]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Steps to reproduce the problem:
Killed multiple giants; launched 10+ of each type of firework from various keeps. Not updating.

Screenshots/Videos or archive.org evidences:

![image](https://user-images.githubusercontent.com/44992609/50722685-fb52be00-1115-11e9-9da8-e863957b6e68.png)

**Comment by geezereur** [comment]
I think its the same bug I have but I have it with /boast players.

**Comment by Morksezstop** [comment]
same as OP + drink dwarf beer

**Comment by Morksezstop** [comment]
all works fine for me now

**Comment by sioding** [comment]
nice - so i close this one.
