### ISSUE TITLE
WE ruthless assault hit for 12 times instead of 6 / generates blood lust

### ISSUE THREAD

**Issue by kyranria** [WarEmu/WarBugs#13057]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
after the patch note 05/01/2019, ruthless assault hit for 12 times instead of 6

<a href="https://imgur.com/19RvBwA"><img src="https://i.imgur.com/19RvBwA.jpg" title="source: imgur.com" /></a>
Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Can you please give us another screenshot not on Target Dummys? Thanks.

**Comment by kyranria** [comment]
was fixed but we have a new bug.
Now when we use ruthless assault it doesn't consumes blood lust and instead it generates blood lust

**Comment by Torquemadra** [comment]
fixing
