### ISSUE TITLE
wrong categorie of tactic battle command

### ISSUE THREAD

**Issue by Tholkienn** [WarEmu/WarBugs#13059]
Expected behavior and actual behavior: supress tactic is list as a defensive.

Steps to reproduce the problem: have to be a offensive one.

Screenshots/Videos or archive.org evidences:
https://cdn.discordapp.com/attachments/505645610225893376/531153829996265481/unknown.png

**Comment by grunbag** [comment]
It reduce your chance in being crit hit so it’s defensive
