### ISSUE TITLE
Lvl 24 SC weapon incorrect DPS

### ISSUE THREAD

**Issue by Jaycub** [WarEmu/WarBugs#1305]
Both these weapons give me the same DPS, yet the SC one should be giving me more. Picture explains it better than I can. 

http://www.mediafire.com/convkey/99fc/exheehzf6iyxbmgzg.jpg

**Comment by Silentguard** [comment]
Did you checked real dmg with this weapons?

**Comment by Evildoor** [comment]
Tested this (without talismans), tooltips properly differ.
