### ISSUE TITLE
[Gear] Sentinel set bugged out

### ISSUE THREAD

**Issue by Kalasznikov** [WarEmu/WarBugs#13055]
Expected behavior and actual behavior:
Part of my sentinel set lost their stats - Gloves, Belt and chest pieces miss their stats - they are left only with Armor and talisman slot. The Helmet and Shoulders seems to be fine.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![kalasznikov_002](https://user-images.githubusercontent.com/46399903/50725164-b1f47580-10f9-11e9-884d-6b6565c3edc4.jpg)

The problem occured after last patch, I presume it can have something to do with it.

**Comment by Kabucoror** [comment]
Stats are back on next patch or hotfix

**Comment by sioding** [comment]
Fixed with patch from 12.01.2019
