### ISSUE TITLE
DOK: Covenent of vitality overrrides Armor pots and vice versa

### ISSUE THREAD

**Issue by Sorkhatani** [WarEmu/WarBugs#13056]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior: Armor pots and Cov of vitality should be separate. Vitality is a lifetap, not the armor covenent.

Steps to reproduce the problem:
Put up armor pot or covenent of vitality, then fire up the other. They replace one another

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
We can not reproduce tha - please bring in some screens or a video for it.

**Comment by sioding** [comment]
No answer for 14 days. Close
