### ISSUE TITLE
Guild Standard

### ISSUE THREAD

**Issue by richbob11** [WarEmu/WarBugs#13054]
When I attempt to deploy the guild standard (I am guild lead, lvl 26 guild) I get the message "not in a guild"  Also can not assign standard bearers.  Option is greyed out, 0 are assigned.

**Comment by grunbag** [comment]
Use .standard command on the player you want to be standard bearer

**Comment by richbob11** [comment]
Thank you for the quick reply.

    On Saturday, January 5, 2019, 5:37:28 AM MST, grunbag <notifications@github.com> wrote:  
 
 
Use .standard command on the player you want to be standard bearer
