### ISSUE TITLE
[Quest] Heralds of Defeat (Caledor, destro) Wrong NPCs

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13068]
The Summersong Watcher, which according to the quest description should be a Shadow Warrior, uses a lvl3 stunty as model. Normal level in this zone is around 33.

![quillog_007](https://user-images.githubusercontent.com/30193675/50730139-2d7c1400-1146-11e9-9399-6b982975f6ad.jpg)
![quillog_008](https://user-images.githubusercontent.com/30193675/50730140-2e14aa80-1146-11e9-8346-526118daaf06.jpg)

**Comment by Lheana** [comment]
I already corrected the appearance of this NPC when I was working on other quests in this area, so this will be fixed with next patch.
I also reworked this quest and the following quests will be available.

**Comment by sioding** [comment]
Fixed with patch from 19.01.2019
