### ISSUE TITLE
[Morale Skill] Champion's Cahllenge: Both players under the influence of the skill are still able to use Keep (postern) doors

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13063]
If you root an enemy player within the range of a keep door with Champion's Challenge he is still able to use the door to get inside. On the other hand you can root an enemy player for example bellow the oil and use the door to get inside to safety. None of this breaks the root.

**Comment by sioding** [comment]
Fixed with patch from 12.01.2019
