### ISSUE TITLE
[Quest] Securing a Future (2) (Caledor, destro) Quest might be restored

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13069]
Instead of collecting runes from different Elfs like the description says you have to kill one type of Elf. You might be able to restore this quests to its former glory.

![quillog_009](https://user-images.githubusercontent.com/30193675/50730184-0d992000-1147-11e9-84af-7aa587290536.jpg)

**Comment by sioding** [comment]
Since we can not assign more NPC Type´s to one questobject it´s kinda hard to change - but maybe the DB devs knows a better way.

**Comment by sioding** [comment]
Fixed with patch from 19.01.2019
