### ISSUE TITLE
[NPC/Quest] Securing a Future (Caledor, destro) NPCs spawned inside ship instead on deck

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13067]
Some of the NPCs for this quest spawned inside the bodies of the two ships and are unreachable.

![quillog_006](https://user-images.githubusercontent.com/30193675/50730111-af1f7200-1145-11e9-91bc-002388df006c.jpg)
![quillog_005](https://user-images.githubusercontent.com/30193675/50730112-b47cbc80-1145-11e9-894a-04a2a640da79.jpg)

**Comment by sioding** [comment]
Fixed with patch from 19.01.2019
