### ISSUE TITLE
[Quest] Heart Attack (Caledor, destro) stray map marker

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13065]
There is a stray map marker (pic3) in southern Dragonwake for this quest. The true Map marker (pic2) is the one in Caledor.

![quillog_001](https://user-images.githubusercontent.com/30193675/50730023-26ec9d00-1144-11e9-8b9c-1f6c59af98e5.jpg)
![quillog_002](https://user-images.githubusercontent.com/30193675/50730024-27853380-1144-11e9-9edd-500eb5e688be.jpg)
![quillog_003](https://user-images.githubusercontent.com/30193675/50730025-27853380-1144-11e9-9d38-b8529c216f87.jpg)

**Comment by sioding** [comment]
Fixed with patch from 19.01.2019
