### ISSUE TITLE
Incorrect quest icons priority on quest giving NPC

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#1306]
This is a general bug, on live when you complete a quest the red blob area should disappear, and a new indicator with the orange quest icon should show up. Also, quest indicators on the map show green (Quests Available) as a priority, when they should show orange (Quest Complete).

For example, a low level order quest once complete is still present on the map, and no turn in point is shown.
http://i.imgur.com/z6Gj1D2.png

The turn in mob is nearby, and has the completed quest.
http://i.imgur.com/JqLmrji.png

But because he has quests available, he shows up as a green dot on the map, and only when he can be seen on the minimap.
http://i.imgur.com/r6yX1Je.png

**Comment by Evildoor** [comment]
First issue must be fixed individually for each quest (therefore this ticket will be used only for the second issue, with Orange-Green priority), and we don't know how to do it yet.

**Comment by Evildoor** [comment]
Second issue was fixed at some point.
