### ISSUE TITLE
[Quest] What Lies Within (Dragonwake/Isle of the Dead, destro) Quest marker misplaced

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13072]
The quest marker for this quest is too far north. Use the player arrow as reference for the true position

![quillog_013](https://user-images.githubusercontent.com/30193675/50730256-5fdb4080-1149-11e9-8eb3-60e0a2fd8c02.jpg)
![quillog_014](https://user-images.githubusercontent.com/30193675/50730257-5fdb4080-1149-11e9-9215-cb5e5db4d277.jpg)

**Comment by sioding** [comment]
Fixed with patch from 19.01.2019
