### ISSUE TITLE
[Quest] Worth Dyeing For (Caledor, destro) Not all quest NPCs assigned

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13076]
According to the quest description all of the lizards should drop the quest item but actually only one (rare) of the three types of lizard does. This can be quite a hassle since killing accidentally pulled wrong lizards advance the PQ and if the lizards despawn on Stage 2 you have to make the PQ and the wait for it to restart.

![quillog_018](https://user-images.githubusercontent.com/30193675/50730349-94e89280-114b-11e9-9837-713d79f11ac8.jpg)

**Comment by sioding** [comment]
Since we can not assign more NPC Type´s to one questobject it´s kinda hard to change - but maybe the DB devs knows a better way.

**Comment by sioding** [comment]
Fixed with patch from 12.01.2019
