### ISSUE TITLE
command .standard not working

### ISSUE THREAD

**Issue by Tholkienn** [WarEmu/WarBugs#13079]
Expected behavior and actual behavior: .standard "name" romve abilitie to hold banner in guild pannel

.standard "name" don't remove abilitie to hold banner and give message "you guild is not allowed any more standard bearers"

Steps to reproduce the problem:.standard "name " on someone who have the abilitie in guild.

**Comment by sioding** [comment]
Nope - this command is only for giving the bearer rights. You can remove them by rightclicking on the the the char on the guild roster  with "Unassign Standard Bearer"

**Comment by Tholkienn** [comment]
Ok thx.
