### ISSUE TITLE
[UI/Buff] Against All Odds shows a different % value on the own buff indicator than on the friendly target buff indicator

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13077]
The AAO buff on a player's own buff indicator shows at most times a false (usually too high) value. The value differs from the value of a friendly target which seems to be the true value. "Friendly target" includes selecting one self which I claim to be a proof for the problem since one can not have two different AAO values at the same time ;) .

**Comment by Natherul** [comment]
its simply because the application of AAO is not directly dynamic and the shift of AAO can happen before its refreshed on all players.

**Comment by Natherul** [comment]
correct, thanks for the report. I had forgotten about this ticket when I addressed the issue.
