### ISSUE TITLE
[Quest] Carrying the Flame (Dragonwake/Isle of the Dead, destro) Quest marker misplaced

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13071]
The quest marker for this quest is slightly too far north.

![quillog_012](https://user-images.githubusercontent.com/30193675/50730236-04a94e00-1149-11e9-95ee-753ab06c39c8.jpg)

**Comment by sioding** [comment]
Fixed with patch from 19.01.2019
