### ISSUE TITLE
Land Mine/Demonic Infestation

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#1307]
According to an in-game report, these abilities disappear immediately after being cast when the player is not flagged as in-combat. On live, you could stack several of these which would detonate when NPC/Players walked over them.

**Comment by Radiantknight** [comment]
really? I can keep up to 4 of those little fellas at once. Always did that while waiting for BO to tick

**Comment by wargrimnir** [comment]
This guy must have been having a character specific issue. I've seen Magi in game today dropping DI without being in combat.
