### ISSUE TITLE
[Quest] Bringer of Darkness (Dragonwake/Isle of the Dead, destro) Quest marker misplaced

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13073]
The marker for this quest is a bit too far north. This is a bit confusing since the Black Fire Torches can't be used until stage 2 of the PQ.

![quillog_015](https://user-images.githubusercontent.com/30193675/50730282-f1e34900-1149-11e9-8ae1-ed5eb98cbdc3.jpg)

**Comment by sioding** [comment]
Fixed with patch from 19.01.2019
