### ISSUE TITLE
[Quest] Gathering Darkness (Dragonwake, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13075]
The quest marker for the objective "Kill Dragon Shadow Stalker" is missing.

![quillog_017](https://user-images.githubusercontent.com/30193675/50730327-0bd15b80-114b-11e9-9345-3592844461a1.jpg)

**Comment by sioding** [comment]
Fixed with patch from 19.01.2019
