### ISSUE TITLE
[Quest] Shadow Hunting (Caledor/Isle of the Dead) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13074]
The quest marker for the objective "Seals of Hysh collected" is missing.

![quillog_016](https://user-images.githubusercontent.com/30193675/50730309-8c438c80-114a-11e9-9d8c-ef608eb58ff9.jpg)

Side note: The existing quest marker might also be misplaced a bit since this seems to be a general problem in the Isle. Haven't checked this yet though.

**Comment by Moragor** [comment]
Addendum: The existing quest marker is too far north. Also, the quest end-marker is shown during the quest instead of after completing the objectives.

**Comment by sioding** [comment]
Fixed with patch from 19.01.2019
