### ISSUE TITLE
[Quest] Breaking the Flame (Dragonwake/Isle of the Dead, destro) Quest marker misplaced

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13070]
The quest marker for this quest is too far north. Use the player marker as reference for the true position.

![quillog_011](https://user-images.githubusercontent.com/30193675/50730218-851b7f00-1148-11e9-9545-ca0c560b0073.jpg)
![quillog_010](https://user-images.githubusercontent.com/30193675/50730219-877dd900-1148-11e9-8a03-6469fac393fd.jpg)

**Comment by sioding** [comment]
Fixed with patch from 19.01.2019
