### ISSUE TITLE
RVR Bolster Removes Potion Effect

### ISSUE THREAD

**Issue by Rivenspeak** [WarEmu/WarBugs#13082]
Expected Behavior: Strength potion should persist through death in the RvR lakes.
Actual Behavior: Potion appears in warcamp, but seems to disappear once RvR bolster is applied.

Entered/exited CW warcamp several times.  First screenshot is unbolstered with 22min remaining on strength pot.  Second screenshot is after receiving RvR bolster.  Clicked on myself several times to see if effect appeared under defensive target (i.e., visual bug).  It does not appear.

![drystal_003](https://user-images.githubusercontent.com/45123644/50741766-c4d97980-11cf-11e9-9461-e261525b74c2.jpg)

![drystal_004](https://user-images.githubusercontent.com/45123644/50741774-ec304680-11cf-11e9-9701-604563262c47.jpg)

**Comment by sioding** [comment]
Can you please check it with .getstats if the buff is really gone or is it only a visual thing on the paperdoll?
Please attach screens with .getstats output

**Comment by sioding** [comment]
No answer for 12 days. Close
