### ISSUE TITLE
[Beastlord] Mapmarker for token missing

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#13083]
After completing the class-specific killquests for the BL-Tokens I noticed that there a neither mapmarker for the NPCs, nor that they are listed in the overview on the map. 
(CW serves only as an example, but they are missing on all quests)
 

Screenshots/Videos or archive.org evidences:

![bl2](https://user-images.githubusercontent.com/40274248/50742312-7f39a280-1209-11e9-9279-a17c3ad6d8d6.jpg)

**Comment by Kabucoror** [comment]
All finisher are marked with the next patch. Bosses remain hidden.

**Comment by Scophis** [comment]
Great, thx

**Comment by sioding** [comment]
Fixed with patch from 12.01.2019
