### ISSUE TITLE
Relog needed for accessing new RR mastery point

### ISSUE THREAD

**Issue by Tyramissoux** [WarEmu/WarBugs#13080]
_**Expected behavior and actual behavior:**_
Reached RR60 and wanted to spend the new point at the mastery trainer in IC. When talking to NPC, no point was available. Relogged and the point was suddenly accessible for spending. Might just be UI related. Didn't try to /rel.

_**Steps to reproduce the problem:**_
Let someone ding a mastery point granting RR and see if the point is there immediately or if relogging is neccessary.

**Comment by Kaelang** [comment]
Did not have to relog to spend renown. Please re-open if issue persists.
