### ISSUE TITLE
Quests autocomplete if you walk away during completion

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#1308]
According to an in-game report, it is possible to complete the final step of this quest line without selecting a reward. Needs testing.

**Comment by Radiantknight** [comment]
It can be done with many quests. Just try walking away with reward selection dialog still open or hit Esc button. Happened couple of times on other quests to me.

**Comment by wargrimnir** [comment]
Sure, but does it complete the quest when you walk away? The event quests are a bit of a special case because they were added into the game, there might be some underlying issues with them.

**Comment by Radiantknight** [comment]
I need to level some char to level 8 to confirm, can't say for sure now about this particular quest. With it not being repeatable, kind of hard to goof around

**Comment by Reggaewaldo** [comment]
Anyone tested that confirm the issue ?

**Comment by Reggaewaldo** [comment]
Tested, It is true if you walk away the quest autocompletes and you are left with no reward.

Raising prio and tagging emulator since it might be related to core coding.

**Comment by Reggaewaldo** [comment]
Just to be clear, other quests are affected as well.

**Comment by nalgol** [comment]
fixed next patch
