### ISSUE TITLE
[Beastlord] WH-Kill quest not showing as completed in tome

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#13084]
As the title says

Screenshots/Videos or archive.org evidences:

![bl 1](https://user-images.githubusercontent.com/40274248/50742331-ce7fd300-1209-11e9-9429-302572c72434.jpg)

**Comment by Lheana** [comment]
Have you relogged since you killed the boss?

**Comment by Scophis** [comment]
Yes.
Killed all Bosses on mon or tuesday, completed the first kill quest the same day and took the class specific ones. Those I completed on Sunday.

**Comment by Lheana** [comment]
This happens when you relog after you completed a quest without having turned it in.
@sioding This is for core devs, maybe something is not correctly saved.

**Comment by Scophis** [comment]
@Lheana Logged in today and now no quest at all is marked as completed, definitaly something broken there

**Comment by Lheana** [comment]
#13047
