### ISSUE TITLE
Daemonic Chill Cooldown

### ISSUE THREAD

**Issue by Ripliel** [WarEmu/WarBugs#13081]
Expected behavior and actual behavior:
Daemonic chill should have 0 sec cooldown now.

It has 45 sec cooldown right now.

Steps to reproduce the problem:
Use the skill.

Screenshots/Videos or archive.org evidences:
![sdfdsf](https://user-images.githubusercontent.com/16005849/50740920-603a1100-1207-11e9-9763-01c582a7c596.PNG)

**Comment by Torquemadra** [comment]
fixed direct live
