### ISSUE TITLE
Faith Is Madness T4 Epic Quest Disappearing At Stage 12

### ISSUE THREAD

**Issue by Godhead9** [WarEmu/WarBugs#13097]
I was just doing the quest Faith Is Madness till i reached stage 11 , gave the quest and when i had to go do the staage 12 it just disappeared from my quests, i cant even find it on quest tracker and when i go to the npc where you get it , it s not even there to start it all over, please help.

**Comment by Lheana** [comment]
Talk to The Stranger at the Empire Chapter 22, that's where you stopped.
