### ISSUE TITLE
[Warrior Priest] Apostle's Tome of Glory doesn't regenerate Fury

### ISSUE THREAD

**Issue by lilimx** [WarEmu/WarBugs#13090]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
The Tome doesn't recover fury (in combat + out of combat).

Steps to reproduce the problem:
Slot the tome, and consume fury.

Screenshots/Videos or archive.org evidences:
Video: https://youtu.be/pTKOuRtiRQE

**Comment by Kabucoror** [comment]
works fine for me on dev, with only the tome slotted. Can you add your whole equipment?

**Comment by lilimx** [comment]
Okay. This is rly strange. It works now. 
Made this video ~10 minutes after I bought this book. 
Did some tests after the post and it didn't still work, but now....everythings fine. 

-lock 👍

**Comment by sioding** [comment]
OK - thanks for the feedback. Close
