### ISSUE TITLE
[UI][Buff] Buff icons randomly disappearing when getting or losing other (unrelated) buffs

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13095]
This problem appeared with the patch from 22/12/18 when "- Redid the buff handling code." and "- Potions and other effects that persist through logouts should now be sent on login so you should no longer need to target yourself." went live.

You can see it in this video (tested without addons): https://www.youtube.com/watch?v=i6SrMrwMlKA&

Mainly affected by this problem are (to my observations) potion buffs and the Battle Fatigue debuff (maybe any (de)buff that persists trough a logout).
Receiving any buff has the chance to make the icon of affected buffs disappear. This can temporarily be fixed by targeting oneself, but it doesn't work 100% and some buffs stay hidden until "other things change".
Actual stats are not affected by this bug, at least not in my tests.

**Comment by sioding** [comment]
Thanks for the report but i merge this with #12295 - no need to have different reports for the UI/Buff Icon Problem
