### ISSUE TITLE
[Magus][Skill] Minion skill description not matching Unholy Empowerment buff

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13094]
The Skill description of a Magus' minions says they empower you by 4% every 2s for a maximum of 20% (5 stacks), but actually they give you 5% for a maximum of 40% (8 stacks).

![aggerond_002](https://user-images.githubusercontent.com/30193675/50829201-f1ae9d80-1343-11e9-8966-06dc4241d1ab.jpg)
![aggerond_001](https://user-images.githubusercontent.com/30193675/50829204-f2dfca80-1343-11e9-9e8f-ca73efe9b39c.jpg)
![aggerond_000](https://user-images.githubusercontent.com/30193675/50829207-f410f780-1343-11e9-927d-9f48fac627e3.jpg)

The same bug might exist for Engies.

**Comment by Scophis** [comment]
Afaik all magus deamon /engie turret tooltip are outdated. The values are off and the bonus effects (in/decreased, dot-speed and aoe range) are missing. 
Until the removal of .abchangelist you could check those things, but it seems it has been overlooked to adapt the tooltips.
