### ISSUE TITLE
[Squig Herder] Squig Leap ability

### ISSUE THREAD

**Issue by elk76** [WarEmu/WarBugs#13093]
When you are in Squig Armor stance, the "Squig Leap" ability has a cooldown of 10.0s
if you use  the "All By Meself" tactic, the cooldown of "Squig Leap" is reduced to 0.0s but in the tactic description is indicated only "You deal 25% more damage when you have no pets present"

**Comment by Moragor** [comment]
I assume the tactic works like the WL equivalent. The cooldown is removed with no pet active, but still present if you summon a squig.

**Comment by elk76** [comment]
Tested with or without pet
the "All By Meself" tactic, is sufficient to reduce the cooldown to 0.0s

**Comment by Scophis** [comment]
Patch notes from 06/072018 "Tactic - All By Meself - Now additionally reduces the cooldown of Squig Leap by 10s." 

https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=27274&hilit=all+by+meself#p308847

Was part of the melee-squig-remake.
Probably a wrong tooltip.

**Comment by elk76** [comment]
may be the reduction of cooldown by 10s should be described in the tactic
my issue regards the combination of squig and tactic. 
In details: 
- Horned squig summoned
- Attack the target with Horned squig, and use Squig Frenzy and Git em!
- Bounce on target using "Squig Leap" and explode the squig with "Farty Squig"
- Continue the fight without squig using the 25% of damage bonus from tactic

may be the tactic should be more similar to WL tactic in which you are unable to summon the squig

**Comment by fagio1989** [comment]
> may be the tactic should be more similar to WL tactic in which you are unable to summon the squig

Or maybe not because it's not the proper mirror of the WL
