### ISSUE TITLE
Standard - Able to plant banner inside Wall

### ISSUE THREAD

**Issue by SunsetCNTK** [WarEmu/WarBugs#13092]
- Problem;

You are able to put standard inside of the wall preventing it from being taken for both yourself and enemies.

- Steps to reproduce the problem:

Run to wall, face-plant to it and drop banner

- Screenshots/Videos or archive.org evidences:

![vanguard_001](https://user-images.githubusercontent.com/16652212/50792451-5676e300-12c5-11e9-8845-e3563ccb81a4.jpg)
![vanguard_000](https://user-images.githubusercontent.com/16652212/50792452-570f7980-12c5-11e9-825a-815970398941.jpg)

**Comment by MaxHayman** [comment]
Fixed a few weeks ago
