### ISSUE TITLE
[Quest] Holy Flame (Chaos Wastes EMP Ch20)

### ISSUE THREAD

**Issue by Twistbane** [WarEmu/WarBugs#13091]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior: In a cave you must find Living Ice, once you have found one, you can just spam it to find all 10, instead of finding one at a time.

Steps to reproduce the problem: Go to Cave, Interact with Living ice multiple times.

Screenshots/Videos or archive.org evidences:

No Screenshots as I completed the quest, attached is the location though.

![war bug report 1](https://user-images.githubusercontent.com/46457241/50786945-e8262680-12ac-11e9-9e56-bc1aed39f16c.PNG)

**Comment by Kabucoror** [comment]
On dev it has a 2 min CD, like intended.

**Comment by Scophis** [comment]
Can confirm that at least one iceshard has no cd.
It's the first on the left side when entering the cave.

![confirm 1](https://user-images.githubusercontent.com/40274248/50992162-b4e6d000-1516-11e9-9537-939e4f86db29.jpg)

**Comment by Kabucoror** [comment]
Tested it on live with a friend. He was after the 3rd able to click it multiple times, I have to do it at 10 different. It seems account dependend.
Despite, the quest gets a correction with the next patch to make it work like on official(looting items).
This should fix the problem.

**Comment by sioding** [comment]
Close
