### ISSUE TITLE
[quest](destru) "Worthy Battle"

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#131]
cannot interact with 
![tesq_003](https://cloud.githubusercontent.com/assets/7527415/2949625/d9b128c2-da10-11e3-9d34-dadf8f7decde.jpg)
![tesq_010](https://cloud.githubusercontent.com/assets/7527415/2949635/f48a62d0-da10-11e3-8385-7dabcc3b423d.jpg)

**Comment by Reggaewaldo** [comment]
I made it so that the first part includes returning to Surtsen the Deceiver in that you "can not find Valtar".

Will verify the questline functionality later.

**Comment by Reggaewaldo** [comment]
Tested OK.

Closing.
