### ISSUE TITLE
PQ trovolek Chaos Chapter 8

### ISSUE THREAD

**Issue by comps101** [WarEmu/WarBugs#13100]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:  on stage 2 the fires should have a delay before being able to click them again, 1 fire can be clicked on multiple times in succession allowing you to finish the stage in seconds.

Steps to reproduce the problem: try all the fires at stage 2, one of them can be clicked over and over again.

Screenshots/Videos or archive.org evidences:

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/14893
