### ISSUE TITLE
Resists are calculated on dot application, not on dot tick

### ISSUE THREAD

**Issue by Illiyara** [WarEmu/WarBugs#1310]
If you dot someone then debuff their resistances, the dot's damage won't update to reflect their lower resistance. Conversely, if you debuff someone, then apply a dot just before it runs out, the dot will continue to to tick as if the  debuff was still on the target, even after the debuff expires.
Confirmed with Storm of Cronos and Wrath of Hoeth.

**Comment by Illiyara** [comment]
As of now, this is still bugged.

**Comment by Evildoor** [comment]
I don't know for sure, but check the explanations in #1444, maybe they can answer your question.
