### ISSUE TITLE
Uncoherent damage

### ISSUE THREAD

**Issue by tquere** [WarEmu/WarBugs#13102]
Hello, I am a Whitch Hunter and hunt mainly solo.
Very often, I experience the same situation that I cannot understand.
In the case here, I am trying to kill a lvl 40 AFK marauder that is pretty close to his WC.
(He was a little bit too close actually since a guard OS me after 3 sec)
But before the guard hit me, I was able to start my DPS rotation.
The guy was afk, and look at my 2 skilled damage. (Each one should do around 10x or 20x this value)
Their amount is ridiculous but the auto attacks are quite fine.
It happens to me a lot and I dont have any clue to understand what is happening here.
Do u have a clue ?

Thanx.

**Comment by tquere** [comment]
![silke_002](https://user-images.githubusercontent.com/32341239/50880420-9d0c3080-13de-11e9-9fce-8895d982da54.jpg)

**Comment by sioding** [comment]
Warcamp situations aren´t a good example. If this happens "a lot" please bring in a video or screenshot from the fight itself not from your respawn - thanks.

**Comment by tquere** [comment]
Sorry ... I dont get it.
Why are this not a "good example" ?
I find the screen pretty clear by itself and if you can provide me with any explanation, I'll accept it happily.
Are there some hidden buff/debuff near WC that could explain that ?
Or are there any explanation that could explain the difference between auto-attack damage and skills damage ?
Because basically all you are saying here is, "near WC, it doesnt count... give me another example"

**Comment by sioding** [comment]
If this happens ONLY in fights you have near a warcamp - YES there are hidden buffs to prevent WC camping. If this also happens in other fights we need more screenshots. Sorry - my questions wasn´t clear enough.

**Comment by tquere** [comment]
"YES there are hidden buffs to prevent WC camping"
Ok, good enough for me and Thanx for the answer.

Just strange that it is an "hidden" buff since I think it would be more efficient to really display the buff.
I fought many times near WC and always thought those were "bugs" .. So it never prevented me from retrying ever and ever. So the "preventing part" of the buff doesnt seem to work well.

**Comment by sioding** [comment]
Question answered - close.
