### ISSUE TITLE
Character stuck in Gunbad

### ISSUE THREAD

**Issue by insultus** [WarEmu/WarBugs#13118]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Please wait for the restart on this morning and give us a feedback if you can login again.

**Comment by insultus** [comment]
GM managed to relocate it to the nearest hub. All good now

**Comment by sioding** [comment]
Nice - thanks for the feedback.
