### ISSUE TITLE
Overpowering Swing Removes Strength Aura

### ISSUE THREAD

**Issue by edavoc** [WarEmu/WarBugs#13111]
When slotting or switching to the kotbs tactic Overpowering swing it deactivates your press the attack aura(strength), making you have to reactivate the aura every time you want to use the tactic.

**Comment by sioding** [comment]
Does this happens while you are bolstered or are you on a level 40 char?

**Comment by edavoc** [comment]
on a lvl 40 character. It always switches the aura off when you slot the tactic.

**Comment by sioding** [comment]
Fixed with patch from 12.01.2019
