### ISSUE TITLE
[Chosen] Dreadful Agony

### ISSUE THREAD

**Issue by osium** [WarEmu/WarBugs#1311]
kills cause by dreadful agony do not seem to count as kills for the player

**Comment by Evildoor** [comment]
Tested this on mobs - it writes in chat "You killed mob" and lets me loot money and items. Was this fixed, or it is only bugged in PVP? (Can't test that now)
Visual bug - this aura is not displayed on Chosen as it should. KotBS's All Out Assault works properly in this regard.

**Comment by osium** [comment]
as far as I could tell it was only an issue in pvp

**Comment by ozarmidrashim** [comment]
If this skill were bugged in PvP, so too would AAO! be, as well as any other skill that deals proc damage.

I'll fix the visual effect later.
