### ISSUE TITLE
[NPC] Uthorian Ravager in KV are marked as vendor

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#13113]
Seems like I found secret Meeting of Uthorian "Vendors" ;)

KV 8k/45k

![bug1](https://user-images.githubusercontent.com/40274248/50994196-ed3cdd00-151b-11e9-882d-28cfe0f2fc53.jpg)

**Comment by sioding** [comment]
Fixed with patch from 12.01.2019
