### ISSUE TITLE
Skilled Tactics don´t implement

### ISSUE THREAD

**Issue by Molotch571** [WarEmu/WarBugs#13115]
On both of my chars (one order, one chaos) won´t the skilled tactics implement in my setup. They don´t add to my other abilities automatically and I can´t extract them manually from the book too. It´s just like they dont exist and weren´t skilled at all. I tried unlearn and respec etc. , issue won´t fix by itself. Pls look over this

**Comment by sioding** [comment]
If we really would have a problem with tactics in that way we would have a lot of tickets about it here. Can you please add some screenshots which shows the problem?

**Comment by Molotch571** [comment]
![lievas_002](https://user-images.githubusercontent.com/46501339/51024186-16478700-1589-11e9-8fab-40d52ae2ba37.jpg)
![lievas_003](https://user-images.githubusercontent.com/46501339/51024187-16e01d80-1589-11e9-8773-b8748dc437dd.jpg)
 Here you see the open tactic book with the path abilities next to the taktics skilled at the tactic teacher. As you can see, the so far existing active tactic isnt implemented in the book to extract it for use.

**Comment by sioding** [comment]
Well - you don´t have skilled them. Tactitcs cost a point. Click on it to get it - its not enough to spend points in the tree - if you wanna have some ability or a tactic you have to click on it too.
