### ISSUE TITLE
[quest] a newfound urgency

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#13112]
all bolt trowers in the quest area are not attackable; they can be selected but have no hps.
![chimp_015](https://user-images.githubusercontent.com/17765890/50962595-e20d9100-14ca-11e9-8de5-8d02115249ec.jpg)

![immagine](https://user-images.githubusercontent.com/17765890/50962756-43356480-14cb-11e9-8df7-24e394f6bd9b.png)

![immagine](https://user-images.githubusercontent.com/17765890/50962808-58aa8e80-14cb-11e9-9559-e6502fd1b1e9.png)

![immagine](https://user-images.githubusercontent.com/17765890/50962841-68c26e00-14cb-11e9-90ed-a0a59574248b.png)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 19.01.2019
