### ISSUE TITLE
[Guild] Standard bearer assignment not working

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13124]
I have the rights to assign the standard bearer in my guild, but the option for it is grayed out. Unassigning a bearer worked fine. Guild is lvl 24 and we have bearer rights left (at the moment only one is assigned).

![quillog_000](https://user-images.githubusercontent.com/30193675/51079691-b9a0b500-16cb-11e9-92eb-96c2a973f452.jpg)
![quillog_001](https://user-images.githubusercontent.com/30193675/51079693-bdccd280-16cb-11e9-89b1-a6a6ff093f93.jpg)

**Comment by Natherul** [comment]
the gray out is not related to settings of the guild but a part of a packet thats send to the client about the status of the guild. That packets data should be sent as to not gray out the button as long as said guild is at level 5 or higher

**Comment by Scophis** [comment]
Same problem here, can't assign the titles, eventough I'm the guildleader (inluding the needed rights) and only one title asigned.

**Comment by Natherul** [comment]
going to add back the command as a workaround for the next patch.
Scophis what guild?

**Comment by Scophis** [comment]
Paechter des Wahnsinns; destro, rank 25

**Comment by geezereur** [comment]
Same here Guild Leader of both Order Guild Hunters Association   and destro guild Chimera Ants its greyed out for me also.

**Comment by Natherul** [comment]
In the next patch there is also an update to the information sent to the client that seems to fix this issue. Please post back if it does not after the patch.

**Comment by Scophis** [comment]
Great thx

**Comment by sioding** [comment]
Fixes are deployed. I will leave this report open for feedback until next patch.

**Comment by Scophis** [comment]
Did a quick check, works now for me ^^ Thx for fixing

**Comment by sioding** [comment]
Close now.
