### ISSUE TITLE
Cave in

### ISSUE THREAD

**Issue by osium** [WarEmu/WarBugs#1312]
the knockdown animation from cave in is stuck on the player until they die any time you stop moving you fall to the ground and it overrides a majority of your combat animations

**Comment by ozarmidrashim** [comment]
Doesn't happen for me.

**Comment by osium** [comment]
id say like 50% of the time if not more after getting hit with cave in I will get stuck in the knocked down animation I can still move around and use abilities but whenever I stop moving I will flop back down on the ground and most of my combat animations will bug out anyone on destro side and attest to this

**Comment by Tesq** [comment]
client side bug, happening due to "latency" between internet and other pc components, it can happen to other visual effects like, silence , bw ingite, all KD etc.

**Comment by Thorgatin** [comment]
Yes, what tesq wrote. This was sometimes the same on the mythic server(s).

**Comment by ozarmidrashim** [comment]
Closing per Tesq as unfixable by us.
