### ISSUE TITLE
[DoK] Vanquisher shoulders

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#13128]
Cannot say for sure if it is intended change or just error crawled in somewhere - reporting in case of second - but looks like from release of Vanquisher set (thought it was changed in last patch, but in accordance with backups of minmaxing tool - it was there from get go) DoK Vanquisher shoulders have no Willpower on them.

Here, just in case is comparison of current stats (left) and prepatch stats (right) if it will be of help.
![image](https://user-images.githubusercontent.com/42712833/51083343-aa505480-1729-11e9-9c3c-c01c89efc3bb.png)

**Comment by wargrimnir** [comment]
This is correct on my internal sheet.
