### ISSUE TITLE
[Quest] The Ritual of Murder (Caledor/Isle of the dead) Quest marker shenanigans

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13122]
The two quest marker for this quest are switched with each other and the quest end-marker is shown during the quest instead of after completing the objectives. Also, there is a second end-marker at the camp far west in Dragonwake that doesn't seem to belong there (the quest is turned in Caledor).

![quillog_003](https://user-images.githubusercontent.com/30193675/51079537-1484dd00-16c9-11e9-92cb-7a9026e9c15b.jpg)

**Comment by Lheana** [comment]
This will be fixed with next patch.
Nevertheless the end marker in Dw at the Chapter 17 is correct as the second part says to turn in the quest there.

**Comment by sioding** [comment]
fixed with patch from 27.01.2019
