### ISSUE TITLE
Lion Guardian missing in Lionhome Lodge

### ISSUE THREAD

**Issue by ShotsOnTarget** [WarEmu/WarBugs#13125]
There weren't any "Lion Guardian" NPCs in the 2nd stage of this PQ Lionhome Lodge - Public Quest Destruction Dark Elf Chapter 4

Expected there to be 4 once the Hunters etc had been killed in stage 1. We looked around the area, couldn't see any.

Steps to repeat: Complete Stage 1.

![mainline_000](https://user-images.githubusercontent.com/5008942/51079755-1ba9ec00-16c5-11e9-91b6-2a954f5325b4.jpg)

**Comment by Lheana** [comment]
Just tried on live, works fine.
The PQ area is big, be sure you checked whole area:
![anaehll_415](https://user-images.githubusercontent.com/11537611/51084492-c86a8480-172a-11e9-9dd5-6090712185b3.jpg)

**Comment by sioding** [comment]
No answer since 21 days. Close
