### ISSUE TITLE
[ORvR][Event] Golden Stein/Battle brew backpack still in game

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13123]
The golden Stein from the Keg End event is still in game and working, found it multiple times in CW.

**Comment by Moragor** [comment]
Addendum: The backpack also still drops.

**Comment by sioding** [comment]
Golden Stein is deactivated next patch.

**Comment by Lheana** [comment]
Battle Brew Backpack won't drop anymore with next patch

**Comment by sioding** [comment]
Fixed with patch from 19.01.2019

**Comment by sioding** [comment]
![image](https://user-images.githubusercontent.com/18517842/51431804-8f507980-1c2e-11e9-90bb-e0a3bf404b24.png)
... still there

**Comment by sioding** [comment]
fixed with patch from 27.01.2019
