### ISSUE TITLE
Battle standard sell price

### ISSUE THREAD

**Issue by imagifault** [WarEmu/WarBugs#13133]
Expected behavior and actual behavior:
Battle standard costs 80 silver and should be sold to vendor for lesser or same amount; instead it is sold for 2 gold

Screenshots/Videos or archive.org evidences:

![1](https://user-images.githubusercontent.com/19153315/51090383-ef08d980-1783-11e9-90c5-6bd6ee718ee7.png)
![2](https://user-images.githubusercontent.com/19153315/51090384-ef08d980-1783-11e9-9b0e-ab8cb3ceae5d.png)
![3](https://user-images.githubusercontent.com/19153315/51090382-ef08d980-1783-11e9-8cc8-f2ac6f7a1b79.png)

**Comment by sioding** [comment]
Thanks for the report. Closed due to obvious reasons
