### ISSUE TITLE
[UI] Action Bar Disappearing

### ISSUE THREAD

**Issue by FinalTidus21** [WarEmu/WarBugs#13138]
Expected behavior and actual behavior:

You expect your hot bar to be able to be used when you log on. When you log on, a part of your hot bar is not usable.

Steps to reproduce the problem:

Log onto RoR and after you select a character, alt tab out and surf around. Doing this will reproduce the problem. Ensuring you do not alt tab out while logging in after the character select screen will ensure you bypass the problem.

Screenshots/Videos or archive.org evidences:

**Comment by Kaelang** [comment]
Doesn't seem to happen on latest version of RoR - please re-open if issue persists. Tried and tested.
