### ISSUE TITLE
[Quest] Mourning Beauty (Talabecland, Destro) - Quest not working

### ISSUE THREAD

**Issue by cute-pony** [WarEmu/WarBugs#13139]
- Quest-mob "Knight of the Rose" is not present
- gathering Corpsetallow flower is not working

**Comment by Lheana** [comment]
From previous patch notes: The quest line has been reworked.
So now, quest mob Knight of the Rose is behind the bell, and you can only complete the objective for Corpsetallow when the one for killing Knight of the Rose is completed
