### ISSUE TITLE
[SM] Sudden Shift do not get the effect of whispering wind's 5s cd deduction buff?

### ISSUE THREAD

**Issue by kam19080** [WarEmu/WarBugs#13130]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior: 
Whispering wind has a buff of 5s cd deduction, but it do not have a effect of sudden shift. Cause sudden shift is a 5s cd skill, but it still have 5s cd after having the 5s cd deduction of whispering wind's buff.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

![image](https://user-images.githubusercontent.com/19576098/51085640-55d3c600-1777-11e9-8108-22c6e339816f.png)

1) as u can see sudden shift is a 5s cd skill

![image](https://user-images.githubusercontent.com/19576098/51085713-40ab6700-1778-11e9-8885-13c9552824e8.png)

2) and also you can see there is a 5 cd cool down reduction of whispering wind's buff

![image](https://user-images.githubusercontent.com/19576098/51085705-1d80b780-1778-11e9-9a96-96400fd680b6.png)

3) you can see. When i am having the buffer of whispering wind, my sudden shift still on colddown

**Comment by Torquemadra** [comment]
its a mechanic so no
