### ISSUE TITLE
[armor glitch] Deathwhisper Greathelm missing graphics

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#13131]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Check the screenshot which shows this piece with no graphics where there should be a helm.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
https://ibb.co/R0CnMF1

**Comment by Torquemadra** [comment]
shows appearance for me, are you sure you took the tick out of the "hide helm" option on the character window?

**Comment by gittoaster** [comment]
might be to do with female dwarf.  my IB has longer hair.  when I make sure not to hide the helm it shows like in the screenshot.

**Comment by Torquemadra** [comment]
I see it, swapped the model out, new one kind of cool, tyvm.

**Comment by sioding** [comment]
fixed with patch from 27.01.2019
