### ISSUE TITLE
Sorc casting "Hand of Ruin" while dead

### ISSUE THREAD

**Issue by Balior** [WarEmu/WarBugs#13137]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Hand of Ruin channel continues after death (like ticket #5621 from May 2016).
Quote of #5621: "Hand of Ruin continues to channel, and deal damage, after death. In my particular instance, I committed suicide by killing myself with Backlash as I was casting it."
Same happened to me on 14.01.2019

Channel should stop with my death.
![casting while dead](https://user-images.githubusercontent.com/19497402/51138673-04dcd400-1842-11e9-8ec1-4777408bbaeb.jpg)

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Kaelang** [comment]
Tested and channel no longer damages once the Sorc is dead.
