### ISSUE TITLE
Changes to SoR addon last patch

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#13135]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Noticed some notes on SoR in recent patch notes..  I also noticed now in SoR in RoR that the keeps are often showing as 'locked' when in fact they aren't.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

https://ibb.co/bv3HL5G

**Comment by Moragor** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=66&t=22771&start=90#p340192

**Comment by sioding** [comment]
Thanks for the report but we do not track addons here. Please use our forum for addon problems.

**Comment by gittoaster** [comment]
It wasn't for the addon.  Read the patchnotes?
"- Updated the SoR string thats sent to include AAO information. This does mean that you will need to update your SoR addon."

Anyway.

**Comment by Moragor** [comment]
Yes, you have to wait for a new SoR update as things got optimized. Mind the link I posted above.

**Comment by gittoaster** [comment]
thx Moragor.
