### ISSUE TITLE
Character Bugged After Name Change.

### ISSUE THREAD

**Issue by Flemantwitch** [WarEmu/WarBugs#13132]
Hi,i've been told to write a ticket here by Corque.

After i changed my name from Reirbarg to Fleman on my Engineer 40/52 my character appears to have gotten bugged.

I've participated in two oRvR zones now ( CW / Praag ) Been there since the opening of the zone until lock roaming with WB's and Capping BO's, Fighting etc.

But after the lockout i kept getting a roll of 1, 0 contribution whatsoever. and if i type .bag - The Values dont change at all. as if i were sitting in Altdorf for the entire event.

Spent a solid 3 Hrs in those zones. surely this can't be correct :/

Thanks for reading this. 

Fleman

**Comment by MaxHayman** [comment]
Hey Fleman,

Just checking was this fixed after the server reboot?
