### ISSUE TITLE
[Quest] Crushing Stone (Reikland, destro) quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13149]
The quest marker for the objective "Kill Stoneclan Alehelm" is missing.

![moragor_005](https://user-images.githubusercontent.com/30193675/51231769-de638980-1964-11e9-9ff6-f733957c617e.jpg)

Sidenote: The number of kills seems a bit high for the number of Dwarfs of each type in the area. I assume on live multiple Dwarf types were assigned to an objective. Maybe there is potential for optimization.

**Comment by Lheana** [comment]
Quest markers will be fixed with next patch.
About objectives:
- I added spawns of Stoneclan Bombarders
- Restored original objective and count for the other objective

**Comment by sioding** [comment]
fixed with patch from 27.01.2019
