### ISSUE TITLE
[Quest] Glories Past and Present (3) (Reikland, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13148]
The quest marker for the objective "Raven's Crest Obtained" is missing.

![moragor_003](https://user-images.githubusercontent.com/30193675/51231641-7f9e1000-1964-11e9-8ef1-d252d3beea45.jpg)
![moragor_004](https://user-images.githubusercontent.com/30193675/51231642-8036a680-1964-11e9-8987-8759c813e821.jpg)

**Comment by sioding** [comment]
fixed with patch from 27.01.2019
