### ISSUE TITLE
[Quest] Coddle Souleater (Reikland, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13145]
The quest marker for the objective "Kill Sigmarite Warblade" is missing.

![moragor_000](https://user-images.githubusercontent.com/30193675/51231461-df47eb80-1963-11e9-8e01-99e4bb67f8b9.jpg)

**Comment by sioding** [comment]
fixed with patch from 27.01.2019
