### ISSUE TITLE
Sprinting on mount

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#13144]
Expected behavior and actual behavior:
sprinting on a mount will not dismount you, wont let you get your skills back, and not let you get off your mount

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/44329952/51225891-6cfaeb00-1912-11e9-877a-8640a2d77810.png)

**Comment by Xicoz** [comment]
this might have just been server lag, but took over a minute for it to stop

**Comment by wargrimnir** [comment]
729 seconds to stop actually. Cleared up on it's own. Will keep an eye on it.
