### ISSUE TITLE
[Quest] Rewards for the Faithful (Reikland, destro) Quest marker missing / containing redundant text

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13155]
The quest marker for the objective "Kill Reikland Militia Bowman" is missing.
The marker tooltip for the Commander contains text about Milita, but is not actually a multi objective marker. Both marker tooltips also contain redundant text that is afaik not used in recently fixed quests.

![moragor_013](https://user-images.githubusercontent.com/30193675/51236728-2ee1e380-1973-11e9-825c-2f1de1917583.jpg)
![moragor_014](https://user-images.githubusercontent.com/30193675/51236729-2ee1e380-1973-11e9-933e-0b6e2bd6fcd1.jpg)

**Comment by sioding** [comment]
fixed with patch from 27.01.2019
