### ISSUE TITLE
[Quest] Heart of Strength (Reikland, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13152]
The quest marker for the objective "Kill Sigmarite Henchman" is missing.

![moragor_008](https://user-images.githubusercontent.com/30193675/51235406-af064a00-196f-11e9-8657-17b038c15606.jpg)
![moragor_009](https://user-images.githubusercontent.com/30193675/51235407-af064a00-196f-11e9-818c-c69e1f7e4198.jpg)

**Comment by sioding** [comment]
fixed with patch from 27.01.2019
