### ISSUE TITLE
[Quest] Press the Attack (Reikland, destro) Quest not working

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13156]
Apart from misplaced and missing quest markers the lantern you're supposed to use are not interactable or missing. There are peasants in the area, including the fields far east, but none of them counts for the kills or drops "parts".

![moragor_015](https://user-images.githubusercontent.com/30193675/51241307-d106c900-197d-11e9-8662-64c301468c53.jpg)

**Comment by Kabucoror** [comment]
with next patch you are able to smash the mentioned lanterns

**Comment by sioding** [comment]
fixed with patch from 27.01.2019
