### ISSUE TITLE
[Quest] "Burrows & Bloodwrought" you cant retake the quest again in 7 days to get token

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#13159]
talisman has vanished and there is no quest
<img src="https://monosnap.com/image/OV2WWuoSD3rvB9L2Kgwwl4C1UV0Sn0.png">

<img src="https://monosnap.com/image/Gbyrh9JZfXHetyN0cXzr8yOCRYhJat.png">

**Comment by Kabucoror** [comment]
The RepeatableTime doesn't start to count after a boot, if the counter hasn't finished before the boot. In this case you are never be able to take the quest again.

**Comment by Torquemadra** [comment]
Confirmed

**Comment by MaxHayman** [comment]
This should now be fixed.

**Comment by Nfkillz** [comment]
I cant take it agian on SH (apache) but i could take it on BG.. I have done this quest by SH about 3-4 weeks ago.
probably this quest is still bugged

**Comment by MaxHayman** [comment]
Was fixed @sioding

**Comment by sioding** [comment]
Already fixed.
