### ISSUE TITLE
[Quest] A Simple Request (Reikland, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13150]
The quest marker for the objective "Followers of Morr" is missing.

![moragor_006](https://user-images.githubusercontent.com/30193675/51235233-415a1e00-196f-11e9-81c5-5b3bbf4de382.jpg)

**Comment by Lheana** [comment]
The quest has been reworked: If you have not finished it yet, you'll need to abandon the quest and retake it.

**Comment by sioding** [comment]
fixed with patch from 27.01.2019
