### ISSUE TITLE
[Quest] Crushing Stone (2) (Reikland, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13153]
The quest marker for the objective "Kill Rugni Stonebrow" is missing. You can find him at the shooting range.

![moragor_010](https://user-images.githubusercontent.com/30193675/51235498-effe5e80-196f-11e9-8357-1144bbf10f3e.jpg)

**Comment by sioding** [comment]
fixed with patch from 27.01.2019
