### ISSUE TITLE
[Quest] Imminent Victory (Reikland, destro) Quest marker misplaced

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13154]
The quest marker for the objective "Kill Silversong Bladesinger" is too far southwest. A majority of the quest NPCs is in the area I circled on the map.

![moragor_011](https://user-images.githubusercontent.com/30193675/51236075-7cf5e780-1971-11e9-9203-31b0f0f96777.jpg)
![moragor_012](https://user-images.githubusercontent.com/30193675/51236076-7cf5e780-1971-11e9-8b8e-43d240f3c28f.jpg)

**Comment by sioding** [comment]
fixed with patch from 27.01.2019
