### ISSUE TITLE
[quest] Justice be Done - LOTD quest

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#13163]
Expected behavior and actual behavior:
This quest seems to be a LOTD quest which (I thought) they are all supposed to be disabled/removed.
quest giver =Irkul Grudgebearer (Altdorf Library)

Expected - this quest should be disabled

Actual - this quest is available but LOTD is not.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Kabucoror** [comment]
The whole questline will be deactiveted with next patch till LotD opens once again.

**Comment by sioding** [comment]
Fixed with patch from 19.01.2019
