### ISSUE TITLE
[Merchant] - pocket item 'left hand' no costs associated

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#13164]
Expected behavior and actual behavior:
Expected -items at merchants to have a cost or item prerequisite
Actual - see screenshot.  no item prerequisite

Steps to reproduce the problem:
See merchant in Altdorf Library 'Library Assistant'.

Screenshots/Videos or archive.org evidences:
https://ibb.co/f8PLL9y

**Comment by Lheana** [comment]
It's intended, you buy it when you have the unlock triggered by the Right Hand (item right above).
It's a workaround as the unlock can not be implemented like live yet.
