### ISSUE TITLE
My character bugged in dungeon

### ISSUE THREAD

**Issue by deathgrowl666** [WarEmu/WarBugs#13162]
My character bugged in gunbad (Black Orc name:deathgrowl)  
![screenshot_000](https://user-images.githubusercontent.com/37968087/51346786-225ea780-1aa7-11e9-9c64-faeb21355679.jpg)
![screenshot_001](https://user-images.githubusercontent.com/37968087/51346787-225ea780-1aa7-11e9-9a49-ade16964fa78.jpg)
![screenshot_002](https://user-images.githubusercontent.com/37968087/51346789-225ea780-1aa7-11e9-8c3c-26090770ff50.jpg)
![screenshot_003](https://user-images.githubusercontent.com/37968087/51346791-22f73e00-1aa7-11e9-8db3-d5c5671b1099.jpg)

**Comment by sioding** [comment]
Thanks for the ticket, but we can not help here. Please log another character and create a ticket for a GM.
