### ISSUE TITLE
[BG] Enraged Beating. Critcal hits dont restore 10 hate

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#13168]
For every noncritical hit you get 5 hate (35 total):
<img src="https://monosnap.com/image/A3Wg66x3VCqeY75rgIf7xbHekQrzCQ.png">
The same amount with 3 critical hits:
<img src="https://monosnap.com/image/1zXXfB8Vqf4UKIfOnrYxE0FrDK2Dd6.png">

**Comment by Torquemadra** [comment]
confirmed

**Comment by sioding** [comment]
fixed with patch from 27.01.2019

**Comment by Nfkillz** [comment]
it wasnt fixed. I tested it after patch

**Comment by xaraxdestr** [comment]
my BG still has this issue, it is just 5 hate per hit even when crit

**Comment by sioding** [comment]
No need to bump open bugreports. They are pulled if a dev has time to fix it.

**Comment by grunbag** [comment]
Fixed on next patch

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019

**Comment by Nfkillz** [comment]
still dosnt work properly
[img]https://monosnap.com/image/neDUzkOmetzEejHkF9Nz67shHZAvSP.png[/img]
