### ISSUE TITLE
Raven Host Vanguard

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#13173]
Expected behavior and actual behavior:
2/5 times of doin this PQ, when you kill argog he doesn't give the PQ update, and never respawns, making you wait 10min for the PQ to reset

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![image](https://user-images.githubusercontent.com/44329952/51446497-8e742200-1cd8-11e9-8acb-aba5d642426a.png)

**Comment by Xicoz** [comment]
True, but that's not the problem here, its just killing it to quickly I think

**Comment by sioding** [comment]
Duplicate of #12685
Sorry guys i do merge these problems into one report. No need to have two for it. I know it looks like two different things - but it isn´t.

**Comment by WO-RoR-Exile** [comment]
Still an issue. 12/03/2019.
![Argog Bug](https://user-images.githubusercontent.com/58471571/70051339-73c83600-1596-11ea-88ec-5c07934de8c2.png)
