### ISSUE TITLE
Order getting ganked by order

### ISSUE THREAD

**Issue by Resteloin** [WarEmu/WarBugs#13177]
Unsure if it is bug, cheat or just a developer testing stuff; I got ganked by a witch hunter while I was playing an order character. Screenshot of the combat log below.

I do not think I need to add, pretty self-explanatory.

https://imgur.com/KEwyL2s

Resteloin

**Comment by sioding** [comment]
Thanks for the report - but you are right. Thats a developer test of a new class. So - no bug but i know it seems weird.
