### ISSUE TITLE
[BG] Morale Away, Cretins!

### ISSUE THREAD

**Issue by Learchus** [WarEmu/WarBugs#13171]
Hello, 
As you can see in the pictures, morality does not work.
I can not drag the morale into the action bar, not into the moral bar.

Sorry for the bad english, but I hope I could clarify with the pictures what my problem is.

![malekys_000](https://user-images.githubusercontent.com/46866638/51440433-5a443580-1cc7-11e9-827f-f8bbbd87eeb2.jpg)
![malekys_001](https://user-images.githubusercontent.com/46866638/51440435-5ca68f80-1cc7-11e9-81e1-3ae5c0979bde.jpg)
![malekys_002](https://user-images.githubusercontent.com/46866638/51440438-5f08e980-1cc7-11e9-8eb4-be61fce255ca.jpg)
![malekys_003](https://user-images.githubusercontent.com/46866638/51440440-616b4380-1cc7-11e9-9dd2-ef6e891cc056.jpg)
![malekys_004](https://user-images.githubusercontent.com/46866638/51440441-629c7080-1cc7-11e9-98b6-011241b5d507.jpg)
![malekys_005](https://user-images.githubusercontent.com/46866638/51440442-64663400-1cc7-11e9-91a6-61e24413ddbe.jpg)
![malekys_006](https://user-images.githubusercontent.com/46866638/51440444-65976100-1cc7-11e9-9e80-9b4e021a7000.jpg)

**Comment by Kabucoror** [comment]
Moral "Away, Cretins!" is not set as rank 2 moral, so you can't slot it. 
Confirmed

**Comment by Torquemadra** [comment]
Found issue fixed next patch

**Comment by sioding** [comment]
fixed with patch from 27.01.2019
