### ISSUE TITLE
KotBS Path of Glory not granting skills

### ISSUE THREAD

**Issue by jhomrocky** [WarEmu/WarBugs#13175]
An introduction:

This this is technically two in one but they kind of go hand in hand...hope that isn't an issue. Basically, the points and skills placed in Path of Glory are bugged, further details in the next section.

Details:

Placing 3 or 4 points in Path of Glory correctly shades the "Sunfury" core ability to Green, yet does not actually grant the ability. Placing 5 points (which should grant the "Now's Our Chance!" Path of Glory aura makes both skills Red like they are not chosen, and neither skill shows up in the abilities book. 

Evidence:

4 points spent, green "Sunfury" skill, not in book (would be between page 3 and 4 in my case)::

Page 3 ends with Sunder:

[img]https://i.imgur.com/4uDiqms.png[/img]

Page 4 starts with Taunt:

[img]https://i.imgur.com/WK29FJG.jpg[/img]

Both of them Red and no "Now's Our Chance!" in spellbook:

[img]https://i.imgur.com/PTkr9Vv.png[/img]

Additional Information:

I don't really have any additional information honestly. This is super weird.

How to reproduce the bug:

Steps to reproduce are basically in the details of the issue. I've tried respeccing multiple times yet I can't get the skills to be available (+ the other 1 possible extra point in Path of Conquest in the post I made right before this)

Thanks! Hope this was enough info.

**Comment by jhomrocky** [comment]
Hi, maybe I'm just missing something then. Do I have to do something beyond spending the mastery skill points? Because after dumping all into the Path of Glory I don't have the skills available.

**Comment by sioding** [comment]
Its not enough to spend the point into the tree - you need to click on the ability/tactic you would like to have. They also costs a point.

**Comment by jhomrocky** [comment]
Thanks!!
