### ISSUE TITLE
Karl Franz has incorrect (Dwarf) dialogue.

### ISSUE THREAD

**Issue by Maxim416** [WarEmu/WarBugs#13178]
Expected behavior and actual behavior:

I expected Emperor Karl Franz to say something Empire related, and in character, not talking about Grungni and mountain holds.

Steps to reproduce the problem:

Talk to Karl Franz in Altdorf for the first time. 

Screenshots/Videos or archive.org evidences:

![image](https://user-images.githubusercontent.com/46887784/51464915-553ac100-1d6f-11e9-81c4-df5d22bfc90a.png)

**Comment by Natherul** [comment]
Should have been fixed with the patch from yesterday
