### ISSUE TITLE
Combat Hammer of the Subjugator cant be trade for Smuggler´s Warmantle

### ISSUE THREAD

**Issue by Rhungk** [WarEmu/WarBugs#13174]
The option at the merchant Han Lea for trading the Combat Hammer of the Subjugator (1h weapon for dps WP) has no option to trade it for the cloak, there is no option to trade it, just the options of the Sledge, Battlehammer, the Tome and the Buckle, but none for the Combat Hammer.     

Screenshoots here: https://imgur.com/a/yHjJwGT

**Comment by Torquemadra** [comment]
added next patch, thanks

**Comment by sioding** [comment]
fixed with patch from 27.01.2019
