### ISSUE TITLE
PQ Ch22 Empire "All the King's Men": In Shock debuff

### ISSUE THREAD

**Issue by elk76** [WarEmu/WarBugs#13179]
In the Empire Public Quest Ch22 "All the King's Men" (Destro side), in the Stage V (final boss fight versus Kurt Helborg), some player got the debuff "In Shock". 
- The duration of this debuff is 30min. 
- The player is unable to move or act
- The debuff is not cleansable
may be it should be fixed
I have screenshot if you need it

**Comment by grunbag** [comment]
Kill Kurt knights adds , the player that got DB is informed on screen that he is granted with ability Help friend (like zealot granted abilities). Use this ability to cleanse in shock debuff on the affected player

**Comment by elk76** [comment]
We didn't notice it
We will test it next time
thx mate

**Comment by sioding** [comment]
Answer given - thx @grunbag - Close

**Comment by Scophis** [comment]
Did the Chap22 yesterday and after a wipe the "In Shock!" debuff stayed. I and some other players had a greyed out hotbar and got the message "You are disabled" eventhough we still could use skills.
