### ISSUE TITLE
Endless Pandemonium not working (Tactic) (Magus) 

### ISSUE THREAD

**Issue by Leunour** [WarEmu/WarBugs#13181]
Tactic states:
Pandemonium will now reapply its damage effect 50% of the time after it ends or is removed.

Applying it to enemies in RvR: Never reapplied.
Applying it to target dummies in  the Undercroft: Never reapplied.
Applying it to Forlorn Souls in the Inevitable City: Never reapplied.

(The tactic was on while testing, yes.)

**Comment by Leunour** [comment]
I can get the RvR pictures too, it takes some time.

![leunour_027](https://user-images.githubusercontent.com/46898684/51493884-ff8a0700-1db6-11e9-8929-3fa4c48133dc.jpg)
![leunour_028](https://user-images.githubusercontent.com/46898684/51493887-01ec6100-1db7-11e9-81d1-12e14479b086.jpg)
![leunour_029](https://user-images.githubusercontent.com/46898684/51493893-057fe800-1db7-11e9-8aa0-b6e9116d4edd.jpg)
![leunour_030](https://user-images.githubusercontent.com/46898684/51493899-06b11500-1db7-11e9-97f5-5609abf748d8.jpg)

**Comment by Leunour** [comment]
Target dummies. 

![leunour_031](https://user-images.githubusercontent.com/46898684/51494412-dcf8ed80-1db8-11e9-9409-5ac30281e212.jpg)
![leunour_032](https://user-images.githubusercontent.com/46898684/51494416-dff3de00-1db8-11e9-87de-00f33d11c305.jpg)
![leunour_033](https://user-images.githubusercontent.com/46898684/51494419-e2563800-1db8-11e9-9c13-dfe195f32419.jpg)

**Comment by sioding** [comment]
Thanks for the screenshots. I have removed the confirm labels - but tbh: i expected sceenshots with combat logs - not just single damage numbers. Maybe it´s enough for the dev who will pull this.

**Comment by Leunour** [comment]
Target dummies combat log.
![leunour_041](https://user-images.githubusercontent.com/46898684/51555401-d2515d80-1e77-11e9-8732-87f12d288111.jpg)
![leunour_042](https://user-images.githubusercontent.com/46898684/51555415-d8473e80-1e77-11e9-9696-96ffe0fcd5e8.jpg)
![leunour_043](https://user-images.githubusercontent.com/46898684/51555480-f614a380-1e77-11e9-8916-e9972f027434.jpg)

**Comment by Leunour** [comment]
Whoops, >.<

**Comment by Neutrinoo** [comment]
I confirmed this as well.  Just use pandemonium about 50 times and it never reapplies.

**Comment by grunbag** [comment]
fixed at next patch

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
