### ISSUE TITLE
Can't disband group when leader, if no one else is in group.

### ISSUE THREAD

**Issue by Maxim416** [WarEmu/WarBugs#13182]
Expected behavior and actual behavior:

No option to leave group - stupid crown over my head no option to disband or leave.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

![image](https://user-images.githubusercontent.com/46887784/51505973-6bd62c00-1df2-11e9-82a2-e25d83de6d26.png)

**Comment by sioding** [comment]
So is it only the crown that disturbs? Can you join other groups or warbands?

**Comment by Maxim416** [comment]
Could not join other groups or Warbands. I just mentioned the crown as a visual indicator that I was still classed as being in a group.

**Comment by sioding** [comment]
Hm strange - thanks for the feedback.

**Comment by Maxim416** [comment]
Does this mean I get one of those bug report tokens for the griffon mount in Altdorf?

**Comment by sioding** [comment]
>Anyone who asks for a Griffon or Manticore mount will not receive one, regardless of whether the report would otherwise be eligible.

**Comment by Maxim416** [comment]
Hey man what's wrong with you? Seriously. A simple no would work fine, you freak. Me and a friend reproduced this bug but forget trying to help you fix anything anymore, loser.

**Comment by Lheana** [comment]
We can not accept this kind of behavior. There are rules that you can find on forum. The answer of Sioding was not aggressive, while yours is.
NEVER do it again.

**Comment by sioding** [comment]
I lock the conversation at this point. TBH: It was just a quote from here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by MaxHayman** [comment]
@Kaelang Maybe this was caused by someone making an open group? Maybe close?

**Comment by Kaelang** [comment]
Tried replicating this on live and was unable to - likely fixed in the interim.
