### ISSUE TITLE
DoK bugged influence reward (RvR)

### ISSUE THREAD

**Issue by Ryanfawkez** [WarEmu/WarBugs#1318]
The 3rd influence reward for DoKs in Barak Varr/Marshes of Madness, is a choice of 4 swords, but instead of there being 2 purple and 2 blue swords, there's only 1 purple sword and 3 blue ones.

The 3rd blue sword, Alcadizaar's Edge, should have 29.0 DPS instead of 22.0, +20 toughness instead of 15, +20 wounds instead of +15, have its level and renown rank requirement set to 18, and be granted a talisman slot. Also, the correct naming of this sword should be 'Fangbreaker Painblade', as the purple influence rewards are always either 'Karaz' or Fangbreaker', while the Painblade in this influence set is used for defensive stat items.

**Comment by Evildoor** [comment]
Same problem in Elves' paring - 3 blue swords.

**Comment by jonyjones** [comment]
And what about the proc that reduce movement speed with small dot?

**Comment by Evildoor** [comment]
Aaand the same problem in T3.

**Comment by Meralors** [comment]
Fixed GS/dwarf T2 reward and Elf T2 reward

**Comment by jonyjones** [comment]
Should make another ticket for proc on these weapon?

**Comment by Evildoor** [comment]
No. Procs are not implemented in ROR yet.
