### ISSUE TITLE
Mara Vanq 4 pce Bonus 

### ISSUE THREAD

**Issue by puremage0493** [WarEmu/WarBugs#13183]
Expected behavior and actual behavior: Vanq Mara 4 pce bonus should reduce toughness, but with corruption ability already applied they do not stack. 

Steps to reproduce the problem: Apply corruption and attack until 4pce bonus shld be applies. 

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Thanks for the report - but sorry no bug. A proc on a set is an ability which do not stack with another ability.
