### ISSUE TITLE
Blue Bags

### ISSUE THREAD

**Issue by jebca** [WarEmu/WarBugs#13189]
Hello, I have a problem with blue bags from the rvr zones, namely in all my career on this character I won 10 blue bags. in the first I won the genesis remnant and in the remaining nine genesis shard. Do you have everything fine with your calculator? it might be useful to create npc where you can exchange unnecessary fragments.
Thank you and best regards
ps. in game nick - Erfe (if you wanna check somthing...)

**Comment by sioding** [comment]
Thanks for the report - but thats the way RNG works. If you would like to suggest something, please use the forum for it: https://www.returnofreckoning.com/forum/viewforum.php?f=15
