### ISSUE TITLE
[Zealot/RP] Mark of Remaking (and Possibly Oath Rune of Sanctuary)

### ISSUE THREAD

**Issue by Kaori1** [WarEmu/WarBugs#13187]
I did not see this very minor bug listed on here and I am not aware of any patch notes that refer to this at all. I also do not play RP so I cannot say for sure if this bug affects them as well. 

**-Expected behavior:** 
When using this mark it places a 60m buff on the player that will provide toughness and allow them to rez themselves. Declining the self-rez will allow you to respawn normally and keep the buff to use at a later time. Cooldown is 10m.
**-Actual behavior:** 
When dying with this mark/buff on, its timer will be immediately set to 10m regardless of how much time was actually left on the buff. 
*At first I assumed that this was so that you would not be able to wait a full 60m to rez yourself but isn't that what the 10m respawn timer is for? Even if someone rezs you normally, if you allow that 10m respawn timer to count down you'll still be kicked back to respawn as far as I can tell. 

**-Steps to reproduce the problem:**
Use mark of Remaking and die to anything.

**Comment by Zomega-WAR** [comment]
https://github.com/WarEmu/WarBugs/issues/8138

**Comment by lilimx** [comment]
dublicate / related to #8138
