### ISSUE TITLE
Merchant - Enslaved pack mule

### ISSUE THREAD

**Issue by benitoben20** [WarEmu/WarBugs#13193]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
I visit the merchant Gagdush and i'm seeing that he's selling twice the enslaved pack mule. Not sure if this is intended.
![mashdat_002](https://user-images.githubusercontent.com/16641170/51769151-3eb6a180-20b0-11e9-980c-e1f28fabc0fe.jpg)

Greetings

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Kabucoror** [comment]
Removed one of them from the vendor. You can still use both ot them.

**Comment by sioding** [comment]
fixed with hotfix from 28.01.2019
