### ISSUE TITLE
Quest - Crazy Gits invalid tracker

### ISSUE THREAD

**Issue by benitoben20** [WarEmu/WarBugs#13191]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
The quest tracker indicate that the zone on the right of the orange dot (completed quest) is where you can find tasty mushroom. The mushrooms can be found inside a cave, where my indication is.
![mashdat_001](https://user-images.githubusercontent.com/16641170/51768736-23976200-20af-11e9-958f-5fc07e880c1e.jpg)

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with hotfix from 28.01.2019
