### ISSUE TITLE
Potion - Initiate's fleeting corporeal screen potion

### ISSUE THREAD

**Issue by benitoben20** [WarEmu/WarBugs#13195]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
The potion, Initiate's fleeting corporeal screen, is given, as a reward, at the end of the quest "Gettin' Underfoot" and sadly, the potion doesnt have any effets for the moment. The quest giver is Snouts. 
The potion was mentionned in the thread #3838 as well, but the thread is closed and the potion is still given. Not sure if it is intended.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![mashdat_003](https://user-images.githubusercontent.com/16641170/51769889-395a5680-20b2-11e9-8bb8-e830da4863aa.jpg)

**Comment by sioding** [comment]
since we have an open ticket for it i do close this one - thanks for the report. it is mentioned in the remaining ticket.
