### ISSUE TITLE
Quest - 'Boars is Da Best'

### ISSUE THREAD

**Issue by benitoben20** [WarEmu/WarBugs#13196]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
In the quest Boars is Da Best, you need to feed 3 ravenous wolfs but they are neutral and only kill them. Would it be possible to make some of them friendly ?

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![mashdat_005](https://user-images.githubusercontent.com/16641170/51770738-b981bb80-20b4-11e9-8b2e-2fa3a8b117bb.jpg)
![mashdat_006](https://user-images.githubusercontent.com/16641170/51770739-b981bb80-20b4-11e9-911a-1e07ee579261.jpg)

**Comment by sioding** [comment]
I do not see a problem here. you are supposed to kill three wolves - which are neutral - and thats fine. Click one of them and do your job. But i see another problem. @Kabucoror the sequence seems to be wrong. It seems he have fed the board before he killed the wolves. Can you please have a look at it?

**Comment by benitoben20** [comment]
My bad, i did not read the whole quest line. I tought that since you needed to feed the boars, it was the same with the wolves. As a suggestion, maybe add "killed" after the ravenous wolves ?

**Comment by sioding** [comment]
fixed with hotfix from 28.01.2019
