### ISSUE TITLE
Keybind/Icon problem

### ISSUE THREAD

**Issue by Seilleas** [WarEmu/WarBugs#13197]
The problem is simple and does not need photo evidence because its just not possible through photos since its a command problem.
The matter of the problem is that I today have  downloaded and started playing the game only to find i cannot access my Bag nor Abilities tab(neither through keybinds V,B nor through manual click on the icon)

Obviously have tried changing the keybinds, /reloading the game, starting the game .exe anew and so, but to no avail.

Looks to me as if it has happened after i dragged my....i would call it progress of objectives list(not yet sure what it is called) from the spot it was as i started the game first, the top middle of the screen(image below). However i havent tried opening my bag nor use the ability tab before moving the list away (which was no small trouble either, had to window the game,reload and carefully inch by inch drag the list away since it was overlayed by other function icons like main menu, character tab and so on)

![barproblem](https://user-images.githubusercontent.com/47046220/51780212-00030480-210d-11e9-874c-dd34efb4a2eb.png)

As my friend who has introduced me to the game never heard of this sort of problem i am reporting it as a bug. I hope it gets resolved or i get some tips. 

Thank you

**Comment by Silentguard** [comment]
Restart launcher and game. I had same problem. Update hasn't complite but launcher anyways let me to start client.

**Comment by sioding** [comment]
Thats it - your game isn´t really patched to the end. Thanks for the answer @Silentguard - @Seilleas close the game and the launcher and restart the launcher to get the rest patched.
