### ISSUE TITLE
[Quest] Legend and infamy

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#13190]
There is no mark on map for Selarya.
After you finish 10 lion hunters kill part - all marks dissapear.
![morseth_001](https://user-images.githubusercontent.com/42712833/51765509-07b0b200-20e9-11e9-9063-0140475c4ff4.jpg)
![morseth_000](https://user-images.githubusercontent.com/42712833/51765511-08494880-20e9-11e9-8cfd-32e8fa122bc6.jpg)

**Comment by sioding** [comment]
fixed with hotfix from 28.01.2019
