### ISSUE TITLE
Bad T2 RvR Influence Reward (Dwarf vs. Greenskins)

### ISSUE THREAD

**Issue by Antalor** [WarEmu/WarBugs#1319]
So, at Elite Reward there is One Handed Sword and Two Handed Sword

one handed - Karaz Longsword
Actually Stats : 
+ 20 Strenght
+ 20 Weapon Skill
+ talisman slot

 It's should be 
New Stats : 
+ 20 Toughness
+ 20 Wounds
+ talisman slot 
--------------------------------------------------------------------------------------------
two handed sword - Fangbreaker Claymore
Actually Stats : 
+ 40 Toughness
+ 40 Wounds

It's should be 
Stats : 
+ 40 Strenght
+ 40 Weapon Skill
+ talisman slot
+ talisman slot

Greetings.

**Comment by Evildoor** [comment]
While this suggestion makes sense, it should be taken into account that there is (locked for now) elven t2 zone which also has weapons.

**Comment by wargrimnir** [comment]
Don't make things up and pretend it's a bug. This is not the proper place for suggestions. These weapons do not have talisman slots, because they're supposed to have procs instead.
http://warhammeronline.wikia.com/wiki/Karaz_Longsword
http://warhammeronline.wikia.com/wiki/Fangbreaker_Claymore

**Comment by M0rf** [comment]
The stats are correct, the changes you listed are the influence rewards for the tier 2 zone we dont have yet, Elf.
@wargrimnir all the purple weapon influence rewards have tali slots be it 1 slot for 1h and 2 slots for 2h aswell as a proc, the wiki just doesnt show it.

**Comment by Antalor** [comment]
I sorry. I thinked if most one handed weps are for tanking (except only tank classes) then it should have a tough/wounds and two handed (maked for deal bigger dmg) should have strenght/weapon skill
Greetings

**Comment by Antalor** [comment]
But anyway there is missing a tali slot for two handed

**Comment by wargrimnir** [comment]
Dok Karaz and Fangbreaka Keep are in DvG, that's why the items are named as such. I'll go dig around on the wayback machine at wardb and see if I can find these. We do have a pretty big problem with having a reliable source of information.

**Comment by Reggaewaldo** [comment]
This source claims that there is 1 talisman slot on the weapon:
http://www.arsenalofwar.com/items/Order/Karaz%20Longsword

So I have verified that is the case in the DB. I have yet to find a reliable source for the 2h weapon.

**Comment by Meralors** [comment]
Added talisman slots. Stats are what they should be.
