### ISSUE TITLE
Potion - Initiate's fleeting potion of clout

### ISSUE THREAD

**Issue by benitoben20** [WarEmu/WarBugs#13192]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
The potion, Initiate's fleeting potion of clout is a quest reward at the fist camp of the Orc Area, but it doesn't have any stats or effects. It was mentionned in the issue #3838 but the item is still given, as a reward, for a completed quest. Can't recall the quest name but the quest giver is Crankz.
![mashdat_000](https://user-images.githubusercontent.com/16641170/51768975-c5b74a00-20af-11e9-9947-a360d2ac0e8d.jpg)

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
since we have an open ticket for it i do close this one - thanks for the report. it is mentioned in the remaining ticket.
