### ISSUE TITLE
Harbringer Hatchet alternate appearance

### ISSUE THREAD

**Issue by Fabreese** [WarEmu/WarBugs#13200]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
It's impossibile to change the appearance because this weapon (WL weapon) is considered both hands and off hand.

Steps to reproduce the problem:
Change the weapon to both hands only.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
fixed with patch from 27.01.2019
