### ISSUE TITLE
Teleported to Aldorf on login

### ISSUE THREAD

**Issue by Dasnusnu** [WarEmu/WarBugs#13204]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
I was killed in nordland. I then Respawned and then exited the game and let the timer count down. i then logged back in not long after and spawned it with a black screen then i appeared in Altdorf. it looks like my book of binding also was used as it was counting down.
also i checked for related issues but i dont seem to see one that matches what i see. I am also Registered on the ROR forum.

Steps to reproduce the problem:
I was killed in PVP near stage 4 in Nordland.
Respawned
Hit esc and clicked exit game.
wast about 10 minutes then i logged back in and got a black screen then teleported to altdorf

Screenshots/Videos or archive.org evidences:
sadly no video

**Comment by sioding** [comment]
I can not reproduce that. Can you please go to another rally master and set a new rally point? If there is no errormessage nor any chance to reproduce it - we can not fix it. There are some situation where you will be thrown back to the capital but nothing what you said. I will leave this report open for two weeks - maybe you can reproduce that and give more informations about this.

**Comment by Dasnusnu** [comment]
I tried making it happen again. I cannot get it to repeat and I was able to rebind to a new rally point. If I somehow figure out how to do it again I will repost the issue. My guess is I maybe logged back in under the map and got tossed to a new point or I spaced and logged off fast enough that my position in the world was not saved.

**Comment by sioding** [comment]
Thanks - and close
