### ISSUE TITLE
WL Ability Brutal Pounce damage does not match tooltip

### ISSUE THREAD

**Issue by hollodrim** [WarEmu/WarBugs#13207]
The tooltip says 530 damage, but the actual damage is 133. I think this has been posted before here, but I figure I'd repost it since the patch notes today said: 

" If you find an ability that does not match the tooltip damage versus actual value, is not a critical hit, and is not taking into consideration melee power (melee power does NOT show up on a tooltip) please report it on the bugtracker"

This skill has been bugged for a very long time now and has been posted here, but no reply on it. Thanks

**Comment by sioding** [comment]
Ok - i this time i bring the old ones into the newest report and close the old things. Thats doesn´t mean they are gone - thats why i mention them here. 
#8789 and #12335

**Comment by hollodrim** [comment]
I can confirm in that post you just linked that WL [Leonine Frenzy]  also deals a lot less dmg than the tooltip shows

**Comment by SecretsOTheP** [comment]
Anything that triggers off of the pet will display incorrect tooltips. We have a fix for this in the works.

**Comment by sioding** [comment]
Fixed with patch from 02.02.2019
