### ISSUE TITLE
Siege weapon / ability problem 

### ISSUE THREAD

**Issue by Gorgutzz** [WarEmu/WarBugs#13203]
Expected behavior and actual behavior:
When you enter the catapult and fire it and then exit it, abilities are not usable and you cannot call mount.

Steps to reproduce the problem:
Enter the Black Crag Scenario, enter the catapult in the Destruction spawn area and then exit it. 

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Was able to reproduce it and made a video to show the problem. Would be nice if you can do that on your own next time - it helps the devs a lot. BTW: It works fine if you hit the "leave" button of the siege weapon -  the only way to get in the situation you describe is to walk from the weapon without hitting that button.

https://www.youtube.com/watch?v=kAGtc_Ygxuo

**Comment by Natherul** [comment]
should have been fixed since a few patches. if the problem persist please report back
