### ISSUE TITLE
Emporers mandate sSergeant Polk

### ISSUE THREAD

**Issue by Dasnusnu** [WarEmu/WarBugs#13205]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
When complete the emporers mandate questline. at the first two parts involving Sergent Polk the reward options are the same for each part of the quest. i get offered the same two axes and the same potion.
I am a dwarf ironbreaker if it makes a difference. Game name is Dasnusnu

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

![war_2019-01-26_22-34-14](https://user-images.githubusercontent.com/47071014/51796114-d7d1df00-21ba-11e9-91f9-5d6e1cbb2e60.png)

**Comment by Dasnusnu** [comment]
![war_2019-01-26_22-37-24](https://user-images.githubusercontent.com/47071014/51796120-fafc8e80-21ba-11e9-9ccd-a2b5880f349e.png)

**Comment by Dasnusnu** [comment]
![war_2019-01-26_22-40-21](https://user-images.githubusercontent.com/47071014/51796179-63e40680-21bb-11e9-83aa-b4679f6fcaab.png)

**Comment by Dasnusnu** [comment]
![war_2019-01-26_22-42-30](https://user-images.githubusercontent.com/47071014/51796199-ad345600-21bb-11e9-87c0-31b437a0bf29.png)

**Comment by Kabucoror** [comment]
will be fixed with next patch

**Comment by Dasnusnu** [comment]
Thank you guys are awesome for bringing this game back.

**Comment by sioding** [comment]
fixed with hotfix from 28.01.2019
