### ISSUE TITLE
[Tooltip] Zealot dmg doesn't match

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#13209]
As stated in the patch from 27.01.19 the Tooltip-dmg should be matching the dmg done.
On the Zealot it's still off on some skills.
The small difference in TC is should be caused by the 15 magic-power while the harbinger is on, but I'm not sure what causes it when harbinger is turned off, as it is converted to heal-power.

![tooltip_dmg_zealot_1](https://user-images.githubusercontent.com/40274248/51801014-93852400-2238-11e9-8663-b60f915e2ebe.jpg)
![tooltip_dmg_zealot_2](https://user-images.githubusercontent.com/40274248/51801015-941dba80-2238-11e9-896e-e4513d15a355.jpg)

**Comment by SecretsOTheP** [comment]
Can you please re-test on the training dummies in IC? That will help me figure out if the mitigation values are simply wrong.

**Comment by Scophis** [comment]
Quick test, same results
![tooltip_dmg_zealot3](https://user-images.githubusercontent.com/40274248/51803607-6b58ed80-2257-11e9-8157-31b2bf5eb7c3.jpg)

**Comment by Scophis** [comment]
Tactics are RestoBurst, Warping the Spirit, Blessing of Chaos and Chaotic Force. Non of these should influence my dmg (except crit-rate).
Get the same values without tactics as well

**Comment by SecretsOTheP** [comment]
This is due to the client not reflecting Harbinger correctly in the game client.

I'll see if I can get this aligning properly, will be in patch notes when fixed.

**Comment by Scophis** [comment]
Glad if I can/could help

**Comment by grunbag** [comment]
fixed at next patch

**Comment by sioding** [comment]
Fixed with patch from 02.03.2019
