### ISSUE TITLE
On Your Guard aura deletes mobs

### ISSUE THREAD

**Issue by RonnJeremy** [WarEmu/WarBugs#13206]
Expected behavior and actual behavior:
On your guard should deal damage not outright vaporise mobs

Steps to reproduce the problem: 
Get hit by any mob while having On Your Guard aura on

Screenshots/Videos or archive.org evidences:
https://imgur.com/a/qpz1vgS

**Comment by sioding** [comment]
Fixed with patch from 02.02.2019
