### ISSUE TITLE
Player pets and group buffs

### ISSUE THREAD

**Issue by Chopmasta** [WarEmu/WarBugs#13202]
Expected behavior and actual behavior:

As of the patch on 01/19/19 player summoned pets (tested with squig pets & white lion pet) no longer receive group buffs from group mates such as shaman's Morks buffer, shaman's 'ere we go, knight/chosen auras, the white lions own Pack Assault ability does not effect his own pet.

Patch notes state - Pets are once again immune to aoe healing. these buffs are separate from AoE healing, as such i believe this is a bug.

Steps to reproduce the problem:
group with another player and cast a group buff, it will not effect a groupmate's pet

Screenshots/Videos or archive.org evidences:
Example of Squig pet not being effected by shaman's Morks buffer resist buff & 'ere we go
https://youtu.be/FN8CtG_xzZ0

Example of WL pet not being effected by the players Pack Assault ability
https://youtu.be/mzn1GNIbR54

**Comment by Torquemadra** [comment]
you are incorrect, the pets should not gain player buffs, they are not part of the group.
