### ISSUE TITLE
crafting supplies unavailable on t2 vendors

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#1320]
all others dont offer anything. inconvienient as you have to buy at least container from them.

**Comment by Reggaewaldo** [comment]
Hi, can you please give me an example of a vendor in T2 that does not offer this and I will look into it.

Thanks in advance.

**Comment by Tiggonos** [comment]
Sure. Its basically any craft supply merchant in t2. This one for example in Ostland Order Camp:
![mago_001](https://cloud.githubusercontent.com/assets/13809443/10188284/68114ac6-675e-11e5-8b3b-0a6adf10f66b.jpg)

**Comment by Evildoor** [comment]
Changed the name, since T3 was released and i've seen T3 vendors with crafting goods, IIRC.

**Comment by vove-RoR** [comment]
Not only t2 vendors lack crafting materials. NPC named Erwin Kruger is located in Altdorf and also sells nothing even though his title says "Craft Supply Merchant".
![untitled](https://cloud.githubusercontent.com/assets/16596013/12204879/032d844c-b62f-11e5-9f16-24cb29c3b5d3.jpg)

**Comment by Evildoor** [comment]
#2476 is for Kruger.

**Comment by vove-RoR** [comment]
@Evildoor found another one, this time in T3, there is crafting supplies vendor in Hergig Landing named Hugo Boehm. He sells nothing.

![untitled](https://cloud.githubusercontent.com/assets/16596013/12223258/fa2cd748-b7c9-11e5-8187-d9035122439c.jpg)


Maybe we could create it as a checklist or something where people add vendor and the ones fixed get scratched from it? (to avoid opening many issues concerning same thing)

**Comment by vove-RoR** [comment]
Found another one in Raven's End (Voltz Reifsneider). At the moment I cannot find a vendor who would be selling crafting supplies. Everytime I have to buy new mats I go to T1 zone.

![untitled](https://cloud.githubusercontent.com/assets/16596013/12223302/0473ad20-b7cb-11e5-87b8-278683a641f9.jpg)

**Comment by Evildoor** [comment]
Opening different issues allows the devs to fix them individually with clear indication of what was fixed or what was not. Otherwise, they have either to fix them all at once, which may not be an option, or add comments like "i fixed this dude and that dude, but not that dude", which is clunky. That's why you should make individual issues for different vendors.

**Comment by vove-RoR** [comment]
ok, I will create a new one for those two

**Comment by Evildoor** [comment]
#2791 - link to new ticket made by @vove-RoR, if needed.

**Comment by DanaBloodkiss** [comment]
Fixed all Craft Supply Merchants. Fixed in next.
