### ISSUE TITLE
CD Timers randomly working

### ISSUE THREAD

**Issue by CarltonMaxwell** [WarEmu/WarBugs#13212]
Ever since 2 patches ago I've noticed that the cooldown timers on my abilities sometimes shows sometimes they don't.  I originally thought the abilities were messed up cause I'm clicking ( or hot keys) and they wouldn't fire, but it was because the timers were not showing the remaining time for cd.

Expected behavior and actual behavior:  Should see timer on icon for CD

Steps to reproduce the problem:  It's very random but certainly a new issue for me.  Seen more in combat than not.

Screenshots/Videos or archive.org evidences:  Please see attached example for FP (WE)  It's hard to show but the icon does glow when in effect as it should but after it completes icon looks perfectly ready for usage  and its not of course (CD in effect).  Thanks!
![pleazures_010](https://user-images.githubusercontent.com/47084172/51803492-6118fe00-221b-11e9-8335-1cc2bb7e3671.jpg)
![pleazures_009](https://user-images.githubusercontent.com/47084172/51803493-6118fe00-221b-11e9-920b-de4f74abf37f.jpg)
![pleazures_008](https://user-images.githubusercontent.com/47084172/51803494-6118fe00-221b-11e9-9fd9-f546200a3085.jpg)
![pleazures_007](https://user-images.githubusercontent.com/47084172/51803495-6118fe00-221b-11e9-934a-eaed8f3269a7.jpg)
![pleazures_006](https://user-images.githubusercontent.com/47084172/51803496-6118fe00-221b-11e9-8851-043175d50210.jpg)
![pleazures_011](https://user-images.githubusercontent.com/47084172/51803497-6118fe00-221b-11e9-9022-0e11436800ec.jpg)

**Comment by SecretsOTheP** [comment]
When you say this happened 2 patches ago, does that mean this was happening 2 weeks ago?

**Comment by CarltonMaxwell** [comment]
I'm almost positive it started 2 patches ago (2 weeks) if you include today's.  If not has to be the one 3 weeks ago.

**Comment by Kaelang** [comment]
This seems more like a failed patch / download issue as opposed to a server-side problem. And I'm confident this no longer effects live versions of RoR. If this issue persists, please consider re-opening the issue with replication steps.
