### ISSUE TITLE
[Zealot] Last tick on Deamon Spittle is lower

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#13210]
The dmg on dots should be even on all ticks, but in this case the last tick is lower than those before. (Also tooltip mismatching #13209 )

![ds-ticks](https://user-images.githubusercontent.com/40274248/51802073-59bb1a00-2246-11e9-9720-e925d80ae12e.jpg)

**Comment by SecretsOTheP** [comment]
Definitely related to https://github.com/WarEmu/WarBugs/issues/13209, closing as dupe

**Comment by Scophis** [comment]
#13209 is about mismatching tooltips, this is about the strange dmg-patern that is applied

**Comment by SecretsOTheP** [comment]
They are both related. When we fix one, we'll be fixing the other. The paperdoll that contains your character's stats is the reason the tooltip / damage doesn't align. Harbinger is enabled by default when you log in and is not turning off properly, hence why you see damage disparities in Demon Spittle.

**Comment by Scophis** [comment]
I'm really looking forward for a fix on Harbinger, might solve a lot of other problems zealots have ^^
