### ISSUE TITLE
[Chosen] "Touch of Palsy"

### ISSUE THREAD

**Issue by WARchosen** [WarEmu/WarBugs#13213]
After Patch Notes 27/01/2019 ability [Chosen] "Touch of Palsy" 
![warchosen_000](https://user-images.githubusercontent.com/18600019/51803771-0b634680-2259-11e9-92e6-2b0946e13354.jpg)
the dot damage say when the enemy move it will deal 99 spirit damage every half of sec but instead it deal 2 time more 
![warchosen_001](https://user-images.githubusercontent.com/18600019/51803835-a65c2080-2259-11e9-8e6b-3b66e6fedb50.jpg)
![warchosen_002](https://user-images.githubusercontent.com/18600019/51803840-ab20d480-2259-11e9-9917-e50718a774c0.jpg)
![warchosen_003](https://user-images.githubusercontent.com/18600019/51803855-ede2ac80-2259-11e9-820c-1f885309b693.jpg)
![warchosen_004](https://user-images.githubusercontent.com/18600019/51803856-efac7000-2259-11e9-8b99-dabede2ce7c6.jpg)
![warchosen_005](https://user-images.githubusercontent.com/18600019/51803858-f20eca00-2259-11e9-976f-ac061ab2a5d0.jpg)

**Comment by sioding** [comment]
Can you please activate the timestamp in your chatlog and do some tests again?

**Comment by WARchosen** [comment]
![warchosen_008](https://user-images.githubusercontent.com/18600019/51806130-5c356800-2276-11e9-8dd3-6d74148624c4.jpg)
![warchosen_007](https://user-images.githubusercontent.com/18600019/51806133-648da300-2276-11e9-9131-7ccaf24f5abc.jpg)
![warchosen_010](https://user-images.githubusercontent.com/18600019/51806181-090fe500-2277-11e9-806c-ed22c4a692dc.jpg)

**Comment by Skullgrin** [comment]
Your time stamped images show Touch of Palsy hitting twice per second, as the ability is supposed to.

**Comment by WARchosen** [comment]
so they fix this ?? because i never had that damage earlier

**Comment by WARchosen** [comment]
Soo New patch here and the damage of dot still not fixed 
![warchosen_020](https://user-images.githubusercontent.com/18600019/51926962-ca069e80-23f2-11e9-985e-706b9a830fb3.jpg)
![warchosen_021](https://user-images.githubusercontent.com/18600019/51926965-ce32bc00-23f2-11e9-9cbc-be6ddd789166.jpg)

the dot damage increase with strength
![warchosen_024](https://user-images.githubusercontent.com/18600019/51927058-f4f0f280-23f2-11e9-92da-0a3d8d17bdaa.jpg)
![warchosen_025](https://user-images.githubusercontent.com/18600019/51927071-fde1c400-23f2-11e9-915f-0d51ac143851.jpg)

**Comment by WARchosen** [comment]
it's fixed now report can be closed
