### ISSUE TITLE
T2 order epic quest Chasing Oathgold - step 1 bugged

### ISSUE THREAD

**Issue by Hanceth** [WarEmu/WarBugs#13216]
Expected behavior and actual behavior:

The first quest in this order epic quest line "Chasing Oathgold" starts at dwarf warcamp chapter 5 (quest giver is Dainna Fornbili). The quest task is to kill 10 bog zombies closeby. The actual behavior and the bug is that the kills of bog zombies nearby dont count towards the quest. Expected beahvior is, that killing these bog zombies counts towards the quest.

We tried several times, solo and in party, zombies closer to the warcamp and zombies further away, even after a clean server restart the bug was stil there.

I checked ticket database.
Ticket #12342 is also for the same quest, but for a later step.

Steps to reproduce the problem:

Take the quest and try to fullfill it.

Screenshots/Videos or archive.org evidences:

Here is one screenshot while trying to do this quest.
On the left side in the chat log u see that just one bog zombie got killed by my char.
On the right side u see, that the quest is still at 0/10 bog zombies.

![hanciy_011](https://user-images.githubusercontent.com/22872475/51806184-0f05c600-2277-11e9-80c3-62073c14a713.jpg)

**Comment by sioding** [comment]
Thanks for the ticket - Kab will take care of it.

**Comment by Lheana** [comment]
You were grouped -> due to group issue when doing quest

**Comment by Hanceth** [comment]
I can confirm this now.
When I am solo => the zombie kills count
When I am in group => the zombie kills dont count

**Comment by Lheana** [comment]
#12470
