### ISSUE TITLE
Chalice/Tome no resource gain after changing items

### ISSUE THREAD

**Issue by Nellemosen** [WarEmu/WarBugs#13226]
Tested the Chalice of Repose (t4 reward) in combat and it doesnt give any soul essence. My Scourge does regen soul essence in combat, but Chalice of Repose doesnt.

Don't have video of it, and pictures wont show it.

**Comment by Kabucoror** [comment]
Unequip the Chalice and re-equip it and it works as it should. @Nellemosen 

If you switch a Chalice or a Tome with the same effect on, the second item doesn't use its effect.
