### ISSUE TITLE
Blood of my Blood issue with heal crit 

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#13227]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

yesterday i tried having max healing crit and i was testing my healing abilities until i reached this Blood of my Blood ability  ... after many hours of testing i never seen this ability crit even once so i decide to do another testing
as for today did the test again the ability is on 30s cooldown seems like it doesn't crit  

Steps to reproduce the problem:

equip a shield  and join grp and hit the ability

Screenshots/Videos or archive.org evidences:

**Comment by Tazo83** [comment]
i checked my log folder the combat log file is there but when i opened the file it was empty i think my logs are disabled or something i will check into issue again so i can provide you with combat log

**Comment by Torquemadra** [comment]
Because it doesnt crit, never ever will, its a unmitigated heal which is unaffected by heal debuffs in any form.
