### ISSUE TITLE
I deleted my Character Name and try to remake it with the same name. 

### ISSUE THREAD

**Issue by Reconsniper** [WarEmu/WarBugs#13223]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior: The database isn't deleting the character name from the character list when you chooses to delete a character but say yes to save the profile so you can reuse it if you want to make a character with the same name. Then when you attempts to create a character using that same name. It is rejected and claims the character name is a duplicate. I have lost a few names do to his bug.

Steps to reproduce the problem: try to relog and all so loged want waited a few days and retry with no luck.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Thanks for the answer boss. @Reconsniper just wait for the next patchday and you will be able to use this name again. Normally we do the scheduled restarts on saturday or sunday.

**Comment by Reconsniper** [comment]
I have and some of the names I used 4 weeks ago I still cant use. But I will wait for another sever restart again. lol Thanks
