### ISSUE TITLE
Hotbar Abilities lockout

### ISSUE THREAD

**Issue by Reconsniper** [WarEmu/WarBugs#13222]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior: Sometimes when you port back form a PQ you Can't use your Abilities on your hotkey bar. This also happens sometimes in RvR and SO's when you die and release sometime you cant use your abilities on our hotbar. 

Steps to reproduce the problem: You have to log out and back in to fix it or run out and die again and re-spawn.

Screenshots/Videos or archive.org evidences: I don't know how to take a Screenshots or Videos of in game stuff.

**Comment by sioding** [comment]
Heyho - Thanks for the report but this will be hard to reproduce. Since you don´t see any errormessages or you gave a specific situation this comes from. If we can not reproduce it - we can not fix it. I will leave this report open for two weeks - maybe another player have this problem too and knows how to reproduce it. Sorry that i do not have a better information for you.

**Comment by Reconsniper** [comment]
This has happen to a friend of mine all so in game. It happens a lot when you die in a scenario or port back out of a scenario. All so when you die out in RvR and have to release, you cant use any of your hotkey abilities. I have all so be ported back to the spot where your Character starts coming out of a scenario at lvl 38 lol

**Comment by SecretsOTheP** [comment]
Did you accidentally click on a siege engine running out of the warcamp? I've done that a few times using the healer in Chaos Wastes.

**Comment by Reconsniper** [comment]
No the hotbar just locks out from time to time. I have only had it happen to my white lion 

On Wednesday, January 30, 2019 E Spause <reply@reply.github.com> wrote:

Did you accidentally click on a siege engine running out of the warcamp? I've done that a few times using the healer in Chaos Wastes.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

Sent from AOL Mobile Mail

**Comment by Reconsniper** [comment]
Here is a video of the hotbar lockout

Sent from AOL Mobile Mail
On Monday, January 28, 2019 Sio <reply@reply.github.com> wrote:

Heyho - Thanks for the report but this will be hard to reproduce. Since you don´t see any errormessages or you gave a specific situation this comes from. If we can not reproduce it - we can not fix it. I will leave this report open for two weeks - maybe another player have this problem too and knows how to reproduce it. Sorry that i do not have a better information for you.

**Comment by sioding** [comment]
Thanks for the answer but you can´t attach videos via email. Can you please upload it on youtube and link it here?

**Comment by theHalta** [comment]
Also when I start the game and immediately Alt-Tab, my F1-F12 and Ctrl+<x> abilities will not work. Very reproducable for me.

**Comment by sioding** [comment]
No answer for 26 days from the OP - close
