### ISSUE TITLE
WE Throwing Dagger

### ISSUE THREAD

**Issue by kyranria** [WarEmu/WarBugs#13235]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
After the patch note 27/01/2019 Throwing Dagger now scale with STR

Screenshots/Videos or archive.org evidences:
with Brute Force
<a href="https://imgur.com/ErHxauR"><img src="https://i.imgur.com/ErHxauR.jpg" title="source: imgur.com" /></a>
without Brute Force
<a href="https://imgur.com/wkJZ53l"><img src="https://i.imgur.com/wkJZ53l.jpg" title="source: imgur.com" /></a>

**Comment by SecretsOTheP** [comment]
Should be on ballistics skill.

@Torquemadra

**Comment by Torquemadra** [comment]
fixed direct on live, thanks

**Comment by sioding** [comment]
Fixed with patch from 02.02.2019
