### ISSUE TITLE
[Chosen] Wrong item appearance

### ISSUE THREAD

**Issue by elk76** [WarEmu/WarBugs#13234]
One of the reward in a quest from Ch19 in Praag has wrong appearance
The quest (4 steps chain quest) started in CH18 in Praag, second step in Ch19, third step in Praag warcamp and then back to Ch19 to get the reward
this is the helm with wrong appearance (WH apperance)
let me know if you need to know also the name of the quest
![eyvind_001](https://user-images.githubusercontent.com/46483570/51969789-96208d00-2475-11e9-9161-286a08504337.jpg)

**Comment by Torquemadra** [comment]
thank you

**Comment by sioding** [comment]
Fixed with patch from 02.02.2019
