### ISSUE TITLE
Lost mail

### ISSUE THREAD

**Issue by MadKirbyLV** [WarEmu/WarBugs#13231]
A message sent to Baldreich from my alt Thaenia containing 5 gold and several ballistic skill talismans has been lost and did not arrive. Will the items get sent back, if they did not arrive to the recipient? 

This is the first time my mail has failed to send, so I guess the bug is probably related to just random server errors.

**Comment by Torquemadra** [comment]
try sending another mail with an item to that person and see if they both arrive please

**Comment by MadKirbyLV** [comment]
Thank you, it worked!
