### ISSUE TITLE
Whirling Pin don't work (SW)

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#1323]
Hi, I played a scenario today and this wasn't working for me not once, and by not working I mean I don't get thrown backward.

thx

**Comment by magter3001** [comment]
Did you snare anyone in the process?

**Comment by Nfkillz** [comment]
yes Whirling Pin don't work as on live. When target has snare immune Whirling Pin can be used)

**Comment by ozarmidrashim** [comment]
RoR Whirling Pin will not punt you if there is no enemy target within 30ft.

**Comment by Radiantknight** [comment]
Tried yesterday, was working fine, unless some patches changed it.
No enemies = no jump
Enemies = jump back

**Comment by gittoaster** [comment]
I see it is not working when your enemy is snared=incorrect afaik.

recreate - eye shot->whirling pin

the correct behavior should be - will not work when self is snared

**Comment by Evildoor** [comment]
Tested on SH. Stop Runnin -> Sticky Squigz works properly (punts you). Closing.
