### ISSUE TITLE
Quest - Pulling a Fast One

### ISSUE THREAD

**Issue by joekraken** [WarEmu/WarBugs#13232]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Expected that the npc, named Purser Stringfellow, exists in the zone Reikland, near coordinates (7100, 62900).
Actual behavior is that the npc doesn't exist and the quest can't be completed.
The quest is called "Pulling a Fast One" from zone Reikland.

Steps to reproduce the problem:
Have the quest active and then go to speak with the npc, Purser Stringfellow in Heinrich Estate.

Screenshots/Videos or archive.org evidences:

**Comment by Kabucoror** [comment]
The NPC is hostile and in a Beastlord area, so it is possible he is sometimes killed.
Despite, the rest of this Quest line was not doable. 
Fixed with next patch.

**Comment by sioding** [comment]
fixed with pacht from 09.02.2019
