### ISSUE TITLE
Quest - The Enemy you Know

### ISSUE THREAD

**Issue by Rottgutz** [WarEmu/WarBugs#13233]
Expected behavior and actual behavior:

Quest is not working. Killed the named mob it wanted me to kill in quest description. Ceremonial sword needed to complete said quest is not dropping.

Steps to reproduce the problem:

Kill mob, item won't drop.

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with pacht from 09.02.2019
