### ISSUE TITLE
Quest upper level limits don't work for quests

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#1324]
This is something that is good and bad from different perspectives, as at some time allows the players more quests to do.  
However the PvP quests are a concern (T1 quests) when at T2.

Some of the kill quests should be considered to have upper level limit?

eg. keep the class kill quest (even though bugged atm) but add limit to the RvR quests for the tier.

**Comment by Evildoor** [comment]
Uh, you mean that it is possible to squeeze a small amount of xp and money out of every 5-25 kills in T2 by flying to T1 zones and turning the quests in? Is this a problem?

**Comment by gittoaster** [comment]
as all of t2 comes online then it won't make sense for rvr quests except
for scenario quests and class quests.
/p

**Comment by Reggaewaldo** [comment]
I understand your concern. I will have a look at it and see if we will prioritize it.

**Comment by Reggaewaldo** [comment]
After doing some calculations I have determined that we skip this for now since it does not make much difference. If we somewhere along the line feel that this is an issue (T3/T4) we can come back to it.
