### ISSUE TITLE
Dungeons: Sewers of Altdorf

### ISSUE THREAD

**Issue by ProsperoTempest** [WarEmu/WarBugs#13245]
Not deblostered when entering Sewers of Altdorf Dungeon solo or in a party
Expected behaviour: debolsetered to appropriate level 
Actual behaviour: Stay level 40 with access to all abilities

Steps to reproduce the problem:  Enter the dungeon 

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Duplicate of #13169
