### ISSUE TITLE
Inability to target Daemonic Coquette mobs

### ISSUE THREAD

**Issue by petro-morozov** [WarEmu/WarBugs#13243]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
![burlaka_006](https://user-images.githubusercontent.com/29775556/52055355-dfe9a000-2567-11e9-8273-84455c1af100.jpg)
![burlaka_009](https://user-images.githubusercontent.com/29775556/52055389-f4c63380-2567-11e9-930c-c27d8016b122.jpg)
![burlaka_010](https://user-images.githubusercontent.com/29775556/52055393-f7288d80-2567-11e9-8841-9a30f38a49a4.jpg)
![burlaka_011](https://user-images.githubusercontent.com/29775556/52055412-00195f00-2568-11e9-984a-044d31b31390.jpg)

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with pacht from 09.02.2019
