### ISSUE TITLE
RP's ability bugs movement speed after death.

### ISSUE THREAD

**Issue by spacestarkid13** [WarEmu/WarBugs#13247]
When you confront a Rune Priest, getting snared and then die, you have your movement speed bugged after resurrection. Snare about 40% that can be removed only after relogin.
Unfortunately I can't name a certain ability or tactic, or say If it's even RP's fault, because there were several fights with multiple enemies. But in every case there was a presence of dps-RP.

**Comment by sioding** [comment]
Thanks for the report but if we do not see any screens or videos - or you can say the name of the skill which occurs this problem we can not reproduce it. Kinda hard to fix it. I will leave this report open for two weeks - would be great to get more informations for it.

**Comment by Warmasta** [comment]
I think this is a first tactic in Path of Valaya called Immolating grasp. Today one priest slowed us with a friend forever. So check this tactic if possible.

**Comment by spacestarkid13** [comment]
Here's a screen of recent fight with the same bug after respawning. Dps-RP again. I don't know, can it help?

![mashka_048](https://user-images.githubusercontent.com/16030337/52541356-0ba92900-2da5-11e9-8702-48f2cbfa6874.jpg)

**Comment by grunbag** [comment]
It seems fixed I can’t reproduce
