### ISSUE TITLE
[BO] "YOU WOT!?!!!" ability not working as intended ?

### ISSUE THREAD

**Issue by Skullboila** [WarEmu/WarBugs#13241]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Was making a try with the "YOU WOT!?!!!" ability on a target dummy and realised that it may not 
work as the tooltip suggests.
The problem i found out is that when enabled, while armor increase by 30%, defences by 15%, resistances remain the same ( should increase by 30% as per tooltip ).
Further find attached 2 screenshots while testing the ability on target dummy.
![you wot before](https://user-images.githubusercontent.com/47211668/52050339-efadb800-2558-11e9-8919-7cfd47258113.jpg)
![you wot after](https://user-images.githubusercontent.com/47211668/52050348-f805f300-2558-11e9-8963-4d142a07837f.jpg)
![you wot before](https://user-images.githubusercontent.com/47211668/52050392-18ce4880-2559-11e9-983b-b579b049fb1e.jpg)
![you wot after](https://user-images.githubusercontent.com/47211668/52050409-22f04700-2559-11e9-853c-f7e362fa0b99.jpg)

Thanks for the info in advance.

Best Regards
D.M.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Thanks for the ticket. The paperdoll isn´t correct sometimes. Can you please repeat the tests and show ist the .getstats output in the chat?

**Comment by Skullboila** [comment]
Good afternoon again, 

just had the test with .getstats and now shows the correct values of the increase in resistances also.

Thanks a lot for the help, keep up the good work.

best regards
D.M.

**Comment by sioding** [comment]
Thanks for the retest - close for now
