### ISSUE TITLE
[SW] Barrage and Opportunistic Strike

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#13240]
Expected behavior and actual behavior:
from changelog 01/09/2018
Barrage got snare effect.
Opportunistic Strike is usable at scout stance.
both work fine but icons are not showing correctly on skill bar.

Barrage 
snare debuff icon is not showing on debuff window. 
in tooltip, skill is damage. not ailment.
i don't think it's cleansable.
it's 5sec, tooltip shows 0sec.

Opportunistic Strike
it's usable on scout stance but icon is not highlighted.
and tooltip remained saying it's only usable on assault stance.

Brutal Assault
it doesn't work on scout stance.
tooltip says it's usable on scout and icon is highlighted on scout.

**Comment by sioding** [comment]
Fixed with patch from 02.02.2019
