### ISSUE TITLE
No bag roll after zone lock

### ISSUE THREAD

**Issue by Agrokulture** [WarEmu/WarBugs#13257]
Expected behavior and actual behavior:
Order have just locked MoM but received no bag roll.

Steps to reproduce the problem:
Unsure

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Well without more informations its kinda hard to find the problem. How about the aao status? Any Errormessages? Some screenshots that help?

**Comment by sioding** [comment]
No answer since 24 days. close
