### ISSUE TITLE
Domination - Howling Gorge

### ISSUE THREAD

**Issue by grant-musick** [WarEmu/WarBugs#13256]
Expected behavior and actual behavior:

AB: Domination timer against your team (for the opposition) in Howling Gorge keeps ticking even after you plant the bomb.

EB: Domination timer for opposition in Howling Gorge should stop ticking if your team plants the bomb.

Steps to reproduce the problem:

1) Get Domination timer going against you.
2) Plant the bomb.

**Comment by grant-musick** [comment]
Also just had this happen in Talabec Dam sceanrio. Order was up Order was at 220 or so about 15 and the dom timer started. We planted the bomb at about 270 but the dom timer just kept ticking to give them uncontested win.

**Comment by Natherul** [comment]
Domination has changed how its handled since this ticket. So Im going to close this. Please make new ticket if there are other issues with domination
