### ISSUE TITLE
[Gunbad] Glomp da Squig Masta's "Acidic Muck" damage radius significantly larger than visual representation

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13255]
Glomp da Squig Masta in Gunbad left wing has this "Acidic Muck" AoE damage puddle which has visually around the same size as the "Sticky Feetz" puddle of the Shaman, but the damage radius is around **three times** as large. You can see it in this video:
https://www.youtube.com/watch?v=VPqz7mt_h18&feature=youtu.be

This makes the fight quite unfair.

**Comment by grunbag** [comment]
Fixed at next patch
