### ISSUE TITLE
New introduced stats doesn't show on description

### ISSUE THREAD

**Issue by notre4ror** [WarEmu/WarBugs#13251]
Expected behavior and actual behavior:
The "3% Armor penetration" stat is greyed and at the top of the tooltip on the SH Vanquisher chest instead of being at the bottom and yellow. (not tested if the stat works or not)

Steps to reproduce the problem:
Go to the merchant and mouseover the item.

**Comment by Kabucoror** [comment]
it is only a visual thing, affect invader too

**Comment by Kabucoror** [comment]
same goes for #13590

**Comment by Kabucoror** [comment]
already fixed on live client
