### ISSUE TITLE
SM: Phoenix's Wing ability bug

### ISSUE THREAD

**Issue by Meleesorc** [WarEmu/WarBugs#13259]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior:
Phoenix's Wing should only hit target once.

Actual behavior:
Phoenix's Wing hits multiple times on one target

Steps to reproduce the problem:
Use Phoenix's Wing

Screenshots/Videos or archive.org evidences:
![llara_035](https://user-images.githubusercontent.com/46076248/52165360-ce370280-26f7-11e9-8b59-d25fa4e90e61.jpg)

**Comment by Meleesorc** [comment]
![llara_036](https://user-images.githubusercontent.com/46076248/52165591-c2007480-26fa-11e9-9763-750b5f1360c7.jpg)

**Comment by Meleesorc** [comment]
![untitled](https://user-images.githubusercontent.com/46076248/52165732-57e8cf00-26fc-11e9-95d1-90e1fe6a6fcc.png)

**Comment by sioding** [comment]
Hotfix for it... done.
