### ISSUE TITLE
battle objective crash

### ISSUE THREAD

**Issue by TalilaTzatziki** [WarEmu/WarBugs#13253]
Expected behavior and actual behavior:
When moving onto a Battle Objective in open RvR, the game crashes. There is an audio queue for every time it crashes, where the in-game music becomes a series of distorted beeps a few seconds beforehand. Is it specifically the music.  This has been tested in Troll Country and Caledor with the same effect, on multiple Battle objectives in and out of Warbands. It always crashes.

Steps to reproduce the problem:
Move onto a battle objective in open RvR.

Screenshots/Videos or archive.org evidences:
This video shows it clearly.
https://www.youtube.com/embed/c7AWapoEymM

**Comment by SecretsOTheP** [comment]
Try reinstalling your game. I cannot seem to replicate the issue.

**Comment by Moragor** [comment]
Your Audio.myp file is corrupted, get a working one from here: https://www.returnofreckoning.com/forum/viewtopic.php?p=332519#p332519

**Comment by sioding** [comment]
Problem answered. Close
