### ISSUE TITLE
PQ Phoenix Eye in Etaine stage1 can be finished too fast

### ISSUE THREAD

**Issue by baroke** [WarEmu/WarBugs#13254]
Expected behavior and actual behavior:
At Stage 1 of the PQ you are supposed to claim 5 different objectives.
What you can do instead is just click fast on the same flag 5 times

Steps to reproduce the problem:
Click on top of the Shining Banner really fast, with the hand cursor.

Screenshots/Videos or archive.org evidences:
https://youtu.be/NkwRQ2KUyAs

**Comment by Lheana** [comment]
#13100

**Comment by sioding** [comment]
since we have a mentioned problem i close this one. That doesn´t mean we do not fix it but there is no need to have more than one report open for the same issue.
