### ISSUE TITLE
Tactics bugging out

### ISSUE THREAD

**Issue by dave2278** [WarEmu/WarBugs#1325]
If Jagged edge procs and you swap jagged edge for another tactic jagged edge still procs.

**Comment by ozarmidrashim** [comment]
I see no reason to change that?

**Comment by magter3001** [comment]
Tested it myself, recreating it if you will and no luck with having jagged edge proc if I don't have it slotted. If you can specify clearly what you did to create this situation, it would be easier to fix it.

**Comment by Evildoor** [comment]
I agree with comments above. Can you explain, please, how exactly you can do that? I have no success with proccing Jagged Edge when it is not slotted, and i can't see any way to bug it out without bugging out any other tactic. There were cases with some tactics, but they were tied to War Bellows/Coventans/whatever, while Edge is just tied to your crits in general.

**Comment by Evildoor** [comment]
No response in 2 weeks. Closing this until someone points out the way to reproduce this bug.

**Comment by Zealote** [comment]
Think this is the same issue, and it's related to tactics in slot 1 changing when you zone (not the tactic *set*, as in going from set 1 to 2, but the actual tactics in 1 reverting to what was slotted previously):

Started with Rugged and You Got Nuffin' tactics on BO, joined sc, then after leaving sc I was back to having "I'm Da Biggest" and "Rugged" slotted (the two that were there before I purchased You Got Nuffin to test it). My wounds and toughness were increased from those two tacs, but I was also getting You Got Nuffin regen procs.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
