### ISSUE TITLE
[WE] Elixir of the Cauldron doesnt protect from BW's root

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#13267]
Screenshots/Videos or archive.org evidences:

https://youtu.be/pqANDJPGFkk

**Comment by grunbag** [comment]
Fire cage is a CC not an attack and can’t be disrupted like most roots

**Comment by Nfkillz** [comment]
ok lets talk about balance now. Why does WH's magic immune protect from Sorc and Magus roots

**Comment by sioding** [comment]
oh no we will not @Nfkillz

**Comment by grunbag** [comment]
Both shroud of magnus and elixir of the cauldron works the same . For a root immune use Fleet-Footed
