### ISSUE TITLE
Witch Elf ability Wracking Pains bugged

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#13266]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

ability should fire after Enfeebling Strike

Steps to reproduce the problem:

stealth > Enfeebling Strike >  Wracking Pains 

Screenshots/Videos or archive.org evidences:
[VIdeo showing the bug](https://streamable.com/84p67)

**Comment by Torquemadra** [comment]
at 8 seconds on your video you can clearly see wracking pains is upon the lost soul.

**Comment by Tazo83** [comment]
so its working fine just there wsct addon is not reading it as the rest of the abilities ... today i will try to log on and do another testing and i will post my feedback here

**Comment by sioding** [comment]
Thanks for the feedback but i close this one here. Maybe Sullemunk can help you with the addon.
