### ISSUE TITLE
[Engineer] Strafing Run is undefendable

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#13261]
https://www.youtube.com/watch?v=2fDtcgLBG8c&feature=youtu.be

**Comment by Nfkillz** [comment]
WE used m1 and didnt dodge knock back. Strafing Run is ranged attack.

**Comment by Torquemadra** [comment]
confirmed, fixed next patch

**Comment by sioding** [comment]
fixed with patch from 09.02.2019
