### ISSUE TITLE
[Squig Herder] Tactic "All By Meself"

### ISSUE THREAD

**Issue by nohh** [WarEmu/WarBugs#13264]
Tactic "All By Meself" does not increase damage by 25% when pet is absent.

**Comment by sioding** [comment]
Can we please see your testing screenshots?

**Comment by Scophis** [comment]
Can confirm, discovered just the same. It makes no difference if you equip the tactic or not. (Tested on Dummies and NPCs in IC)

**Comment by tseyu7401** [comment]
is it the bug able to fix? I m still waiting to be a single squig herd!

**Comment by sioding** [comment]
Don't bump on the bugtracker please. It's not going to get fixed until we figure out how.
