### ISSUE TITLE
tactic "no quarter" that does not work

### ISSUE THREAD

**Issue by mactatane** [WarEmu/WarBugs#13269]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

hello, after having tested this tactic I found that it did not reduce the casting time of the wing eye shot

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Can you please add your testing screenshots/videos?

**Comment by Torquemadra** [comment]
Works fine
