### ISSUE TITLE
War Report timer giving wrong timer amount

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#13265]
Expected behavior and actual behavior:
It states 20 min timer until re-use.
After using the war report feature to teleport, timer now says 49710d until I can use it again.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Rydiak** [comment]
Relogging also seems to clear the issue, but reloading does not.

**Comment by gittoaster** [comment]
It seems to not bug right away, but after some time (eg. 10 min in one play session) no logging.
