### ISSUE TITLE
NPC - Maliriir

### ISSUE THREAD

**Issue by benitoben20** [WarEmu/WarBugs#13262]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
In Eataine, there is a unicorn, Maliriir thats his hostile towars the elves.
See in the picture

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![wodnargyl_001](https://user-images.githubusercontent.com/16641170/52168926-7cde4180-26fe-11e9-95b8-5920a74bb69f.jpg)

**Comment by sioding** [comment]
fixed with pacht from 09.02.2019
