### ISSUE TITLE
Archmage tactics Wild Healing

### ISSUE THREAD

**Issue by A1pharius** [WarEmu/WarBugs#13260]
Archmage  tactics say: Wild Healing - Whenever you critically heal someone, your healing abilities will cost 50% less action points for 10 seconds. 
On fact - abilities cost 35% lesws action points for 10 seconds.

**Comment by sioding** [comment]
Can we see your testing video please?

**Comment by qualteia** [comment]
![image](https://user-images.githubusercontent.com/16740013/52169376-57e4d100-26f4-11e9-9e3b-05ef794c581f.png)
Not sure about the actual calculation or if its just the tooltip

**Comment by A1pharius** [comment]
![50](https://user-images.githubusercontent.com/47281644/52170553-189a9c80-2755-11e9-8137-b5de9c33cd24.jpg)
tooltip say this,

**Comment by Sulorie** [comment]
This is no bug, it got intentionally changed to 35%, down from 50%. The tooltip just wasn't fixed.

**Comment by grunbag** [comment]
Fixed at Next patch

**Comment by sioding** [comment]
Fixed with patch from 02.03.2019
