### ISSUE TITLE
[PQ] Executioner's Blade in Caledor

### ISSUE THREAD

**Issue by Emerosa** [WarEmu/WarBugs#13277]
I went to Executioner's Blade PQ in Caledor and the First Stage is: Prison Camp Liberated 0/3. I've spent quite a bit of time trying to figure out if it wanted me to open the individual cages or the large pit (Screenshots provided). It seems that both options don't work, I tried clicking the cages, trying destroying the cages, talking to the (Good) NPC's, and killing all the bad NPC's but to no avail. 

![altador_006](https://user-images.githubusercontent.com/28827833/52180975-74e3d780-27ba-11e9-8b56-a5a3676bf926.jpg)
![altador_007](https://user-images.githubusercontent.com/28827833/52180976-74e3d780-27ba-11e9-96e0-27e3b64e72b2.jpg)
![altador_008](https://user-images.githubusercontent.com/28827833/52180977-74e3d780-27ba-11e9-853d-69052083b65d.jpg)
![altador_009](https://user-images.githubusercontent.com/28827833/52180978-74e3d780-27ba-11e9-9eba-4f0b5db2422b.jpg)

Expected behavior and actual behavior: You're suppose to liberate camps and achieve progress, instead no progress is made no matter what is done.

Steps to reproduce the problem: Go to Executioner's Blade PQ in Caledor and try to open the large pit, individual cages, talking to (Good) NPC's and killing all bad NPC's to get progress.

Screenshots/Videos or archive.org evidences: Provided

**Comment by sioding** [comment]
No bug here. So: Close
