### ISSUE TITLE
[SW] NoQuarter - changing stance disable it

### ISSUE THREAD

**Issue by XmatXergon** [WarEmu/WarBugs#13276]
Expected behavior and actual behavior:
After changing stance back to Scout tactic should still work but it doesnt, only way to fix is get out of combat and slot tactic again.

Steps to reproduce the problem:
Slot NoQuarter tactic in Scout stance, change to Assault or Skirmish stance, change again to Scout stance.

Screenshots/Videos or archive.org evidences:
when its working:
![xergos_085](https://user-images.githubusercontent.com/37849311/52180140-c0aa7700-27e2-11e9-9b0c-fbfc8bbfb401.jpg)

after changing stances it doesnt work anymore:
![xergos_086](https://user-images.githubusercontent.com/37849311/52180134-affa0100-27e2-11e9-9257-7457d54a5867.jpg)

**Comment by Torquemadra** [comment]
tested, seems fine, can you try to monitor and advise further

**Comment by sioding** [comment]
No reaction since 23 days. close for now
