### ISSUE TITLE
mobs teleporting back

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#13278]
Expected behavior and actual behavior:
all monsters (near the "The Storm is Coming" PQ anyways) are teleporting backwards 20yards while in combat, and this happens ever 2seconds or so until the mob is so far away from you that it de-aggros making it impossible to kill anything, and stops me from doing the PQ. I apologize for not having any recordings of this, also screenshots don't really help in this scenario.

**Comment by Kabucoror** [comment]
Works fine for me on live and on dev server.

**Comment by sioding** [comment]
No answer since 19 days. close
