### ISSUE TITLE
Leaping Alteration (Zealot)

### ISSUE THREAD

**Issue by Vigfuss** [WarEmu/WarBugs#1327]
Since the latest patch I noticed Leaping alteration was only showing up on my friendly target, and not spreading to the group.  I didn't check today but on Friday and Saturday it was not working right.

**Comment by ozarmidrashim** [comment]
Fixed a bug not long ago where if LA and RoS jumped to a pet, an exception would be thrown and they'd stop. Does the issue persist?

**Comment by ozarmidrashim** [comment]
Closing as have heard nothing back and issue wasn't present on test server.
