### ISSUE TITLE
[SW] Powerful Draw

### ISSUE THREAD

**Issue by Ripliel** [WarEmu/WarBugs#13279]
The tactic stops working once you leave SC/change zone. 

![ripliel_185](https://user-images.githubusercontent.com/16005849/52181806-3294b780-2807-11e9-83dd-492d4e4fcade.jpg)
![ripliel_184](https://user-images.githubusercontent.com/16005849/52181807-33c5e480-2807-11e9-9175-6bbf3a878ad3.jpg)

**Comment by sioding** [comment]
Duplicate of #12902
