### ISSUE TITLE
[Gunbad] Loss of textures in Lord Solithex fight

### ISSUE THREAD

**Issue by elk76** [WarEmu/WarBugs#13272]
We started the fight with the boss Wight Lord Solitex
at the beginning of phase 1 (giants spawn) all texutures vanished

![eyvind_047](https://user-images.githubusercontent.com/46483570/52174610-bd899980-2796-11e9-9494-f6ab69c9e003.jpg)
![eyvind_051](https://user-images.githubusercontent.com/46483570/52174611-bf535d00-2796-11e9-81c4-b4e3f3979172.jpg)

**Comment by grunbag** [comment]
Fixed at next patch
