### ISSUE TITLE
Can't turn in supplies to warcamp flag drop off.

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#13275]
Expected behavior and actual behavior:
If I understand correctly, supplies are able to turn in at the warcamp flag.

Actual - can't turn in at warcamp flag, but can turn in at keep flag drop off (which is opposite faction).

Steps to reproduce the problem:
Played in CW as Order.

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
You can only drop supplies in there if your own keep has fallen. Was it? No screenshot in this report which would help.
