### ISSUE TITLE
Magical salvaging

### ISSUE THREAD

**Issue by nohh** [WarEmu/WarBugs#13274]
Is it normal that conqueror/dominator items (helmet, gloves) salvaging to 200 blue fragment?

**Comment by sioding** [comment]
Sorry but the bugtracker is not for "is it correct that..." things. Try the forum/discord/ingame for such things. I don´t wanna sound rude - but imagen if all players use the BT to get their individual answer for a question they have. The devs won´t be able to fix things. So sorry... close.

**Comment by gittoaster** [comment]
All those items on live gave purple 100% with salvaging.  It was that way on RoR but it has changed around time when dungeons were starting to be implemented.

**Comment by gittoaster** [comment]
Today I salvage a Genesis jewelry and it gives me a white fragment.
Genesis Remnant of Scholar -> Dense Jet Stone.  (white!)
