### ISSUE TITLE
overflow item

### ISSUE THREAD

**Issue by lenideni1** [WarEmu/WarBugs#13288]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by lenideni1** [comment]
can't clear overflow items in my bag .  in game name is Vodkaa

**Comment by SecretsOTheP** [comment]
Known issue. Move an item to your bank from overflow to clear it up.

**Comment by SecretsOTheP** [comment]
https://github.com/WarEmu/WarBugs/issues/11937
