### ISSUE TITLE
(WP ITEM Bugged)   The Bastion Tome  

### ISSUE THREAD

**Issue by Jubok21** [WarEmu/WarBugs#13281]
![sigi](https://user-images.githubusercontent.com/19917328/52185260-e3a64c80-281d-11e9-9b59-7c00daa3cb4b.png)
The Bastion Tome (Offhand / Charm) Lv 23

the Item got an Righteous Fury reg 8 but its not work on this item :(

**Comment by sioding** [comment]
No its not. I guess you have used another 8 RF tome before and just swappend to this one. This is a known bug. You can not swap - you need to put it into your inventory and then on your char again. You will see it works fine.
