### ISSUE TITLE
[Sentinel Bonus] Arise (resist to stun or knockdown) doesnt work

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#13282]
<img src="https://monosnap.com/image/wM9ChXD5uQe1QBdvciAoRUusuxW0FI.png">

i dont know how to confirm it but we did 10 tests and  I was knocked10 times (33% chance to resist).

**Comment by Torquemadra** [comment]
because its not IGNORE KD, its RESIST KD, by which it means if you are hit by a 3s KD you will be KD for 2 seconds, if you are hit by a 6s stagger you will be staggered for 4s.
