### ISSUE TITLE
Sentinel aspis Bugged.

### ISSUE THREAD

**Issue by Myrmer9247** [WarEmu/WarBugs#13283]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior: Guess it shouldve any Stats. It didnt have for anyone of us.
![myrmerino_002](https://user-images.githubusercontent.com/36338066/52202256-445d7580-286e-11e9-82bd-5826914a2035.jpg)

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with pacht from 09.02.2019
