### ISSUE TITLE
Wilhelm IV - Keep Lord keeps bugging and healing back (Reikland)

### ISSUE THREAD

**Issue by Ysil** [WarEmu/WarBugs#13280]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Keep lord fighting and acting properly in the public RVR quest

Steps to reproduce the problem:

Gather a big enough warband and try to kill the bugger (ha ha!)

Screenshots/Videos or archive.org evidences:
https://i.imgur.com/PLkHVeo.jpg
@Chuwack comment

**Comment by sioding** [comment]
No - Never ever. It was the same problem at all. No real tank - and if a tank was on it - he got no heal. Close.
