### ISSUE TITLE
Raven Host Vanguard PQ

### ISSUE THREAD

**Issue by xero180** [WarEmu/WarBugs#13287]
This PQ is bugged and will not progress past stage 2

**Comment by sioding** [comment]
Duplicate of #12685

**Comment by WO-RoR-Exile** [comment]
Still an issue. 12/03/2019.
![Argog Bug](https://user-images.githubusercontent.com/58471571/70051424-9eb28a00-1596-11ea-8f13-3a3b50b483cb.png)
