### ISSUE TITLE
[Slayer] Breaking Point does not work with Cleft In Twain 

### ISSUE THREAD

**Issue by Ripliel** [WarEmu/WarBugs#13285]
Expected behavior and actual behavior:
The tactic should affect all skills of the tree (increase the crit chance).

Steps to reproduce the problem:
Slot the tactic when you have 0 crit chance. 
Use Cleft In Twain.
Get zero crits.

Screenshots/Videos or archive.org evidences:
I've tested it for 10 mins (120 hits+) applying the skill every 5 seconds.
My target had 0 chance to be critically hit when I had 0 chance to crit and only Breaking Point tactic being slotted. I tested it with Pulverizing Strike before and it did increase the crit rate (I got 11%) BUT with Cleft In Twain I got 0 critical hits. 

![riplin_001](https://user-images.githubusercontent.com/16005849/52211043-c020e780-2899-11e9-9477-e4932c9a2d74.jpg)

**Comment by Torquemadra** [comment]
confirmed and fixed next patch

**Comment by sioding** [comment]
fixed with patch from 09.02.2019
