### ISSUE TITLE
Slaughter (Slayer Tactic) Not working

### ISSUE THREAD

**Issue by CrimsonFenris** [WarEmu/WarBugs#13286]
Expected behavior : Equip Slaughter tactic, and see a 5 AP reduction cost from skill when Furious, and a 10 AP reduction when Berserk.

Observed behavior : Equipping slaughter tactic is not working at all.

I tested in combat situation on a keep lord during several minutes, and using various skills, and there is absolutely no AP cost reduction from being in either furious or berserk state.

On the other hand, Gudrun's warcry is correctly lowering AP costs, and using it in combination of Slaughter Tactic doesnt make the latter working either.

**Comment by CrimsonFenris** [comment]
I test it right now on Altdorf dummies, it's working... Last time it failed was attacking a keep Lord, will further test this to check if it happens again.

**Comment by grunbag** [comment]
It works fine for me too , upload a video with more evidence
