### ISSUE TITLE
[Quest] The Price of Failure (2) (Dragonwake, destro) One pike completes all three quest objectives

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13298]
Clicking one spike completes all three objectives.
This robs the player of the accomplishment of clicking two additional times. 😮 

![the price of failure 2](https://user-images.githubusercontent.com/30193675/52341092-f5504580-2a11-11e9-941c-5f3616e80e77.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 09.02.2019
