### ISSUE TITLE
Sentinel Rune Priest

### ISSUE THREAD

**Issue by deathkylem** [WarEmu/WarBugs#13292]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
+21 Healing power not works, is giving +21 willpower that its not the same

Steps to reproduce the problem:
Getstat and bonus magic

Screenshots/Videos or archive.org evidences:
![runebard_010](https://user-images.githubusercontent.com/38692556/52332215-4fdda780-29fa-11e9-9519-f6b497f98b41.jpg)
![runebard_011](https://user-images.githubusercontent.com/38692556/52332216-50763e00-29fa-11e9-8555-be629265d3f4.jpg)
![runebard_012](https://user-images.githubusercontent.com/38692556/52332217-50763e00-29fa-11e9-86c6-15676b0f940b.jpg)
![runebard_013](https://user-images.githubusercontent.com/38692556/52332218-50763e00-29fa-11e9-9ad1-9138fe0fb4e0.jpg)

**Comment by deathkylem** [comment]
Sorry my bad, the problem is so much worse, gloves gives intel bonus but not gives willpower+talisman stat and the healing power is double, gives -->+21 healing power +21 willpower. The item is working so bad.

**Comment by Torquemadra** [comment]
theres no heal power in that .getstats, this is a visual paperdoll issue
