### ISSUE TITLE
[Quest] The Price of Failure (Dragonwake, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13296]
The quest markers for the objectives "Alex Volkenschein's Head" and "Grogan Blackhammer's Head" are missing.

![the price of failure 1](https://user-images.githubusercontent.com/30193675/52340970-968acc00-2a11-11e9-82e0-cc1842d4d2b3.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 16.2.2019
