### ISSUE TITLE
[Quest] Race Against Time (Dragonwake, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13294]
The quest markers for the objectives "Kill Dragoncourt Lancer" and "Kill Dragoncourt Noble" are missing.

![race against time](https://user-images.githubusercontent.com/30193675/52340720-cf767100-2a10-11e9-89e6-aaf3a06c8a51.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with pacht from 09.02.2019
