### ISSUE TITLE
[Choppa] Bleed Em Out (Damage Numbers too high)

### ISSUE THREAD

**Issue by nohh** [WarEmu/WarBugs#13290]
Is it normal that choppas began to do damage?

![bleed](https://user-images.githubusercontent.com/19315739/52256811-3d476d80-2929-11e9-91e5-9c358a914ac7.jpg)

**Comment by Ripliel** [comment]
![actual](https://user-images.githubusercontent.com/16005849/52304218-4aa13e00-29a3-11e9-8010-b99099115fe5.PNG)
tested during several pug SCs. 
Average crit is 469 and max crit (on pets or debuffed light armour target) is 2085. 
Non-crit ticks are 249 and last one 1021 (same as highest crit: pets, debuffed non-guarded targets).

**Comment by Torquemadra** [comment]
it should not, hotfixed ability to previous state until it can be rebuilt correctly

**Comment by Jinxypie** [comment]
Maybe you didnt noticed, but but the first screen is dmg on target dummy. In reality you never got more than 2k on the last tick AFTER 10 SECONDS not being cleansed.

**Comment by grunbag** [comment]
Fixed on next patch

**Comment by sioding** [comment]
fixed with patch from 09.03.2019
