### ISSUE TITLE
[Salvaging] Critical Failure

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#1329]
4-5 in a row on orange, 2 on yellow, not too much?

**Comment by Titoos** [comment]
Its RNG so its never too much. 
But if Im correct on official even failure gave you chance to levelup. Which is good in terms of learning from mistakes.

**Comment by Radiantknight** [comment]
Well, go for green to be safe, cheezus. Not a bug anyway

**Comment by magter3001** [comment]
Titoos is correct, on Live you would level up even if you fail on orange and yellow salvageable items. Also RvR gear bought from vendors could be salvaged on Live.

**Comment by Evildoor** [comment]
4-5 failures in a row is well within usual RNG unfairness. Difference with live implementation is another problem, and i'm sure devs are aware of it. Therefore, closing this.
