### ISSUE TITLE
[Quest] Into the Furnace (Dragonwake, destro) Quest marker switched

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13299]
The quest markers for the two objectives are switched.

![into the furnace](https://user-images.githubusercontent.com/30193675/52341414-c4244500-2a12-11e9-83b6-fdc531f4c2dd.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 16.2.2019
