### ISSUE TITLE
[Quest] The List (Dragonwake, destro) Quest marker problems

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13295]
The marker for one objective is missing, one is doubled and all three are at the wrong position.

![the list](https://user-images.githubusercontent.com/30193675/52340861-372cbc00-2a11-11e9-8059-af232b200bd0.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with pacht from 09.02.2019
