### ISSUE TITLE
[Quest] Misplaced Rivalries (Dragonwake, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13293]
The quest markers for the objectives "Kill Dragon Dusk-Walker" and "Kill Dragon Shadow" are missing.

![misplaced rivalries](https://user-images.githubusercontent.com/30193675/52340639-90482000-2a10-11e9-974a-de33518d3930.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with pacht from 09.02.2019
