### ISSUE TITLE
BB Ssrydian Morbidae hit for 65534 dmg

### ISSUE THREAD

**Issue by xaraxdestr** [WarEmu/WarBugs#13308]
We were at Ssrydian Morbidae and the debuff already stacked high, so in the end I hit the boss for 1 dmg but after that i hit him for 65534 dmg and he died... 
![knochenfraktur_000](https://user-images.githubusercontent.com/45398873/52498354-e49dfc00-2bd8-11e9-856a-edd0708d5129.jpg)

**Comment by grunbag** [comment]
Fixed at next patch
