### ISSUE TITLE
Double damage from ability

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#13301]
Nordwatch SC
WL's ability Coordinated strike hits 2 times from player and 2 times from pet.
![veszal_579](https://user-images.githubusercontent.com/42712833/52370078-1d1bc980-2a63-11e9-92b0-8faf459ff073.jpg)

**Comment by Rockalypse** [comment]
![veszal_581](https://user-images.githubusercontent.com/42712833/52375765-80acf380-2a71-11e9-96a2-5a3fd049f1fb.jpg)

**Comment by Torquemadra** [comment]
right, thats what it does so long as the pet is within 30ft.
