### ISSUE TITLE
Supplication ticks

### ISSUE THREAD

**Issue by theHalta** [WarEmu/WarBugs#13305]
Expected behavior and actual behavior:
Stopping Supplication (and the DoK equivalent) immediately after starting the channel should only give the WP 1 tick of RF. Right now it gives 2.

Steps to reproduce the problem:
1) Get low RF.
2) Cast Supplication and instantly jump
3) You will get 2 ticks instead of 1.

Screenshots/Videos or archive.org evidences:
https://i.gyazo.com/f77a1ef8b643ca4cc7744dd3806e6c57.gif

**Comment by lilimx** [comment]
I want something to add:

1. You get the same result, when you using "esc" instead of "jump"
2. It only occures right after a Supplication tick.
