### ISSUE TITLE
[Quest] Without Sanction (Eataine, destro) Suboptimal NPC assignement / Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13307]
For the objective "Defenders of house Steelwind" the NPC "Steelwind Silver Helm" is assigned. I could only find three of them, scattered over a large area and you need to kill 12.
"Steelwind Sword-Dancer" would be a better choice since there are a lot of them in the quest area or use the multi NPC workaround since the quest asks for general "Defenders".

![quillog_000](https://user-images.githubusercontent.com/30193675/52487985-30dc4280-2bbf-11e9-96b9-799e51d64b54.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 23.02.2019
