### ISSUE TITLE
[Quest] Bragging rights quest Chaos wastes Bringer of disease unkillable

### ISSUE THREAD

**Issue by IxanderousI** [WarEmu/WarBugs#13309]
The quest requires me to kill this npc bringer of disease but can only target, cannot use any abilities on it, have tried aoe, taunting, nothing works.
![bashgutz_001](https://user-images.githubusercontent.com/25346641/52508985-5cc2ec80-2bee-11e9-99e8-25a19bd180ca.jpg)

**Comment by Lheana** [comment]
I could not reproduce it.
The right place of this NPC is a bit more at the center of this "camp", at the right top of your screenshot.
