### ISSUE TITLE
GTDC wrong range

### ISSUE THREAD

**Issue by Jinxypie** [WarEmu/WarBugs#13306]
Expected behavior and actual behavior: expected 40ft range, current range is shorter.

Steps to reproduce the problem: stay 40ft from mob, cast GTDC and nothing will happen, then cast something else with same range like Yer all bleeding now and mob get hit.

Screenshots/Videos or archive.org evidences:
![bouchac_084](https://user-images.githubusercontent.com/47429816/52434544-dcc65500-2b0f-11e9-8d9c-4f56375b057a.jpg)
![bouchac_082](https://user-images.githubusercontent.com/47429816/52434545-dcc65500-2b0f-11e9-944f-56824bad2b0d.jpg)

**Comment by Torquemadra** [comment]
Incorrect, cone ranges are too long.

**Comment by sioding** [comment]
We have the answer from a dev. Close.
