### ISSUE TITLE
[Quest] The Great Hunt (Eatanine, destro) Quest not completable

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13300]
You're supposed to kill the quest giver, but faction switching is not implemented. This was reported in the past, but the tickets were closed. Since other quests of this kind were fixed with workarounds this might be done here too.

![the great hunt](https://user-images.githubusercontent.com/30193675/52341924-4103ee80-2a14-11e9-9a54-37506ec249c0.jpg)

**Comment by Kabucoror** [comment]
Workaround fix with next patch.
Ticket remains open.

**Comment by sioding** [comment]
fixed with patch from 09.02.2019
