### ISSUE TITLE
[Chosen] Marauder appearance helm

### ISSUE THREAD

**Issue by elk76** [WarEmu/WarBugs#13310]
one of the rewards for the Chosen in PQ Ch15 in Black Crag has the appearance of the Marauder
![eyvind_055](https://user-images.githubusercontent.com/46483570/52518370-f53a8a80-2c49-11e9-9939-1a4cf34b442d.jpg)
![eyvind_054](https://user-images.githubusercontent.com/46483570/52518371-f5d32100-2c49-11e9-905c-8594fe2ca828.jpg)

**Comment by Torquemadra** [comment]
ty

**Comment by sioding** [comment]
fixed with pacht from 09.02.2019
