### ISSUE TITLE
[Weapon] 2h weapon dps in a 1h weapon

### ISSUE THREAD

**Issue by elk76** [WarEmu/WarBugs#13311]
The last reward of PQ Ch10 in BFP is a one-hand axe (available for Mrarauder and Chosen) but the dps is of a 2h axe

![eyvind_059](https://user-images.githubusercontent.com/46483570/52518407-6bd78800-2c4a-11e9-8e30-b8e7c2fe4e79.jpg)
![eyvind_058](https://user-images.githubusercontent.com/46483570/52518408-6bd78800-2c4a-11e9-9612-059d4028cbb6.jpg)
![eyvind_057](https://user-images.githubusercontent.com/46483570/52518409-6bd78800-2c4a-11e9-88df-66400c989cff.jpg)

**Comment by Torquemadra** [comment]
thanks

**Comment by sioding** [comment]
fixed with pacht from 09.02.2019
