### ISSUE TITLE
Sentinel heater shield have no stat (city capital dungeon order side)

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#13317]
Sentinel Heater Shield have no stat.

**Comment by thorbolt80** [comment]
![thorbolt_642](https://user-images.githubusercontent.com/16274785/52523070-95fe6980-2c8d-11e9-9f47-1c185e7e7ce8.jpg)

**Comment by Kabucoror** [comment]
it is already fixed, please look at actual patch notes
