### ISSUE TITLE
[Quest] Vindication (2) (Eataine, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13315]
The quest marker for the objective "Find Staff of Songstorm" is missing.

![quillog_010](https://user-images.githubusercontent.com/30193675/52522163-d7891780-2c81-11e9-8559-868613094b39.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 09.02.2019
