### ISSUE TITLE
[Quest] Vindication (Eataine, destro) Quest marker needs fixing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13313]
I think there was an attempt to make a multi objective quest marker, but it wasn't done properly.

![quillog_002](https://user-images.githubusercontent.com/30193675/52522139-7eb97f00-2c81-11e9-8648-fdc4ab0f859a.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 09.02.2019
