### ISSUE TITLE
No renown buff from Standard

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#13318]
Here on  the BO tick 41.
With standard 5% renown buff should be 41+5% = 43. Buff remainn the same 41
![thorbolt_646](https://user-images.githubusercontent.com/16274785/52523122-29d03580-2c8e-11e9-90f8-0b6578014240.jpg)
![thorbolt_647](https://user-images.githubusercontent.com/16274785/52523127-32c10700-2c8e-11e9-8dc4-7f0eed10b268.jpg)

**Comment by grunbag** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 13.07.2019
