### ISSUE TITLE
[Quest] A Torment Unending (Eataine, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13314]
The quest marker for the objective "Defile the Plaques of Honor" is missing.

![quillog_009](https://user-images.githubusercontent.com/30193675/52522158-b32d3b00-2c81-11e9-946b-9ff08598c4fa.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 09.03.2019
