### ISSUE TITLE
[Ability] Active defences procs twice

### ISSUE THREAD

**Issue by elk76** [WarEmu/WarBugs#13312]
The ability Active defences procs twice combining Overlord and Vanquisher sets 

![puparuolo_108](https://user-images.githubusercontent.com/46483570/52518440-e0122b80-2c4a-11e9-955a-b48f5bde714b.jpg)
![puparuolo_112](https://user-images.githubusercontent.com/46483570/52518441-e0aac200-2c4a-11e9-8a3e-4c591525ca5c.jpg)
![puparuolo_109](https://user-images.githubusercontent.com/46483570/52518442-e0aac200-2c4a-11e9-8bda-e461665780a6.jpg)

**Comment by funnytroll** [comment]
Different proc name(one from being hit another on hit) thats why twice but supposedly bonus they give not stacking with each other

**Comment by elk76** [comment]
It is correct
Tested with .getstats and I see only+7% increased (one ability active)

**Comment by sioding** [comment]
Correct means this problem is solved or not? It should not stack - so does it?

**Comment by elk76** [comment]
I tested it, the increment is only of 7% with both active defences up (so They don't stack)
![puparuolo_117](https://user-images.githubusercontent.com/46483570/52522958-35226180-2c8c-11e9-9315-f6589d6fbcad.jpg)
![puparuolo_119](https://user-images.githubusercontent.com/46483570/52522959-381d5200-2c8c-11e9-9b7e-dffd3511f5b5.jpg)

**Comment by sioding** [comment]
Nice so this can be closed here.
