### ISSUE TITLE
[T2 KEEPS]

### ISSUE THREAD

**Issue by Radiantknight** [WarEmu/WarBugs#1332]
Keeps don't flip now at all, seems the new thing bugged them out

**Comment by ozarmidrashim** [comment]
Flip time 20min

**Comment by Radiantknight** [comment]
oh, ok, but you get reward upon taking it...do you get 2nd part after? needs changelog with description on site

**Comment by ozarmidrashim** [comment]
The reward is given 1 min after taking it to prevent standing around for 20 minutes.
