### ISSUE TITLE
Instant disconnects in RvR

### ISSUE THREAD

**Issue by Gorrry** [WarEmu/WarBugs#13328]
Hello,
i decided to create this issue because i didnt find any other issue related to my problem.
Here is the problem: Whenever i approach a battle objective or join a scenario,i'm getting disconnected.The  
disconnection is straight and instant and the application closes.As long as i stay away from the battle objectives in rvr lakes,the game runs without any problems.
However,sometimes after several disconnects(15+),the game starts running and i dont experience any disconnection issues.
Today the problem persists since i logged into the game(approx 3 hours) and this fact forced me to ask for help.
Any opinion or suggestion would be appreciated.
If any GM read this issue and has the will to help,it would be appreciated as well.

thanks in advance!

**Comment by gittoaster** [comment]
just a suggestion but you should follow one of the performance tweaking listed in this thread.
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=20075

**Comment by sioding** [comment]
Thanks to @gittoaster - thats the place where you get help for this problem. The bugtracker here is only for server releated ingame problems.
