### ISSUE TITLE
Raven host vanguard

### ISSUE THREAD

**Issue by Origin57** [WarEmu/WarBugs#13323]
This Public Quest is blocked and the timer for restar can't begin after death of Father Sigwald . 
Well we can't finish or restart this Public Quest .

**Comment by sioding** [comment]
Thanks for the report but this is already reported. #12685

**Comment by WO-RoR-Exile** [comment]
Still an issue. 12/03/2019.
![Argog Bug](https://user-images.githubusercontent.com/58471571/70051445-ac680f80-1596-11ea-8d89-e31c0c3646a6.png)
