### ISSUE TITLE
Fastah Squig! not working

### ISSUE THREAD

**Issue by RollypollyXtreme** [WarEmu/WarBugs#13320]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:Everytime i click fastah squig mount it says it requires squig armor, wich im already in, theres 2 other SH with the same problem, heres a screenshot too. Oh, also its only been that way ever since the patch today. Also first time reporting a bug so im sorry if its messy haha.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:
![fastahsquig](https://user-images.githubusercontent.com/47482424/52524241-f7601180-2c68-11e9-8298-a45a3f2fff0b.jpg)

**Comment by Natherul** [comment]
should be fixed with the hotfix just pushed.
