### ISSUE TITLE
[Quest] Destro/Eataine - The Ties that Bind

### ISSUE THREAD

**Issue by thevanburenboys** [WarEmu/WarBugs#13333]
The Uthorin informant that is summoned via the well cannot be interacted with as she doesn't pop the quest window when right-clicked. Tried summoning different npcs 5+ times, none could be interacted.

![qaurik_000](https://user-images.githubusercontent.com/34468938/52528786-a1718500-2ccd-11e9-94db-a3599db9ea6d.jpg)

**Comment by Kabucoror** [comment]
works fine for me, on dev and on live

**Comment by thevanburenboys** [comment]
Hello, ty for the response. I tried it today and it's working fine. Not sure what the issue was...

**Comment by sioding** [comment]
close cause of the response
