### ISSUE TITLE
[PQ] Army of faith - Locked in Monastry

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#13337]
If you are inside the Monastry while the PQ resets, you can't leave it anymore as a barrier blocks the way out. You'll have to use a teleport or wait till next step 3.

![door_barrier](https://user-images.githubusercontent.com/40274248/52532487-520b7300-2d26-11e9-856e-c9c84ecf90c5.jpg)

**Comment by Lheana** [comment]
Use the keys on your left.
![anadok_012](https://user-images.githubusercontent.com/11537611/52533156-0231a980-2d30-11e9-9f20-0b42a6c51f0d.jpg)

**Comment by Scophis** [comment]
Damn...to easy ^^
