### ISSUE TITLE
[PQ] Army of Faith - Door attackable

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#13338]
You can damage the Monastary Door, destroying it doesn't have any effect though.

![door_attack](https://user-images.githubusercontent.com/40274248/52532509-a9a9de80-2d26-11e9-849a-ad81f8392882.jpg)

**Comment by Lheana** [comment]
I don't get it ... What's the issue?

**Comment by Scophis** [comment]
Not sure if scenic GOs are supposed to be attackable. If so, and it's intended as a part of the PQ to break the door open, it's bugged the other way round, because you can open the doorway by clicking it.

**Comment by Lheana** [comment]
The door is no longer attackable, this has been fixed with recent changes on GOs.
