### ISSUE TITLE
(BO) Chance block 2

### ISSUE THREAD

**Issue by TwettY** [WarEmu/WarBugs#1333]
Dear Administrators I understand that a lot of work and all that but where once again gone on the block orcs. Understand and that the tank does not tank again !!! Thanks tactics yet what that is but alas not as it was before the restart !!! Without tactics block markups rare !!!

**Comment by Thorgatin** [comment]
wut?

**Comment by TwettY** [comment]
I understand that the answer can not wait just broke our unit and all !!! And as the Day 2 play without a shield !!!! You are about to correct their mistake?

**Comment by Evildoor** [comment]
If i understand correctly, there was a problem with 0 block rating on BO's shield from scenarios (lvl 20), which is fixed now.
