### ISSUE TITLE
Untargetable mobs

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#13339]
This is a somewhat widespread issue that I have observed lately where groups of mobs are untargetable. It is the same issue that was fixed in the latest patch for one kind of monsters:
https://github.com/WarEmu/WarBugs/issues/13243
The mobs are only targetable through the auto target function when they attack but they can not be looted after they are killed.
One of the mobs is already mentioned here (the Ellyrian Steed): https://github.com/WarEmu/WarBugs/issues/13336 but there are many more mobs with the same problem so I will just write them all here.

Ellyrion:
Ellyrian Steed - Coord: (5k, 27k) Also in the nearby area slightly north of these coordinates
Ellyrian Reaver - Coord: (5k, 27k) Two sitting near a campfire

Chaos Wastes:
Chaos Spawn - Coord: (4k, 16k) Can be found in less numbers across the destro side of CW
Skeleton Titan	- Coord: (3k, 22k) Spawns at stage 3 of PQ: Lonely Tower

Saphery:
Arkaneth Guard - Coord: (8k, 25k) Spawns at stage 2 in PQ: Recompense
Mistress Alliessa - Coord: (8k, 25k) Last hero boss in stage 4 of PQ: Recompense

If I find any more I will continuously add them to this list during the coming week.

**Comment by sioding** [comment]
Thanks for the report but please do _NOT_ add them to this report. We need to have one report per issue. Thats not done to make it harder here but easier for the devs.

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 23.02.2019
