### ISSUE TITLE
(Moral) Web of Shadows damage reduced

### ISSUE THREAD

**Issue by spacestarkid13** [WarEmu/WarBugs#13330]
I thought it belongs here. Looks like 
Immaculate Defense is able to reduce damage from Web of Shadows (WE's 2nd moral).

![mashka_046](https://user-images.githubusercontent.com/16030337/52528048-c0c7dc80-2ce4-11e9-8e9e-a253d47483d1.jpg)

1200-75%=300.  I don't know what else can give 75% damage reduction.

**Comment by Natherul** [comment]
immacule defense is also a morale.

Normally morale are non mitigatable BUT since immacule defense IS also morale, this is intended. And is in fact a M4 so better morale ability
