### ISSUE TITLE
Bonus 6 Beastlord Engeneers

### ISSUE THREAD

**Issue by chookinou** [WarEmu/WarBugs#13332]
Expected behavior and actual behavior:

Bonus 6 pieces of the Lord of the Beasts engineer: ballistic gains 4 points instead of 84. The buff indicates 84pts of ballistics won but in the stat the gain is only 4.

Screenshots/Videos or archive.org evidences:

https://www.noelshack.com/2019-06-7-1549766454-chookinou-000.jpg
https://image.noelshack.com/fichiers/2019/06/7/1549766543-chookinou-002.jpg

**Comment by sioding** [comment]
Am i right that i see a 80 ballistic buffpotion in your screens? The beaslord bonus will not stack with your potion. So sorry - no bug.
