### ISSUE TITLE
[Quest] Destro/Eataine - Sign of the Times

### ISSUE THREAD

**Issue by thevanburenboys** [WarEmu/WarBugs#13334]
Quest asks to find Aeylen Sunblade and kill him for Tyrion's message in the PQ area. The NPC is nowhere to be seen in the area indicated in the map. In fact, the whole PQ area is mostly empty.

![qaurik_001](https://user-images.githubusercontent.com/34468938/52528814-6facee00-2cce-11e9-9b67-2c21c09f616b.jpg)
![qaurik_002](https://user-images.githubusercontent.com/34468938/52528815-73407500-2cce-11e9-9ec5-89a776e00ac3.jpg)

**Comment by sioding** [comment]
Empty PQ´s are a know issue we can not fix atm. Sorry but you have to wait for the next server reboot.
