### ISSUE TITLE
[T2 Epic Quest] a LORDS GAME Step 18 NPC won't accept quest

### ISSUE THREAD

**Issue by IxanderousI** [WarEmu/WarBugs#13343]
STEP 18
Go deep on south and find Sharpened Pike (at 4,7k-47,2k), then use it Speak with Lord Kohrith Bloodbane

I cannot hand in the quest to the npc, does nothing when i click on him, this was after clicking on the sharpened pike, the npc then vanishes, reloging allows the npc to appear but still does not allow me to hand in quest.

**Comment by mrSVS** [comment]
Same. NPC Lord Kohrith Bloodbane not accept quest.

**Comment by Kabucoror** [comment]
Related to #12180

**Comment by Lheana** [comment]
As I reworked this epic quest, this step should be fixed with next patch.

**Comment by sioding** [comment]
fixed with patch from 23.02.2019
