### ISSUE TITLE
Bw's Withering Heat

### ISSUE THREAD

**Issue by Valehorn** [WarEmu/WarBugs#1334]
Hello.
Cannot see ability's cd(its missing).
Similarly:
1.Absent snair's effect after first tick(2-3 sec).Only if you focus on it.
2.Ability can be spamming(lol).

**Comment by Silentguard** [comment]
Ability have 2 effects. First is channeling itself with 'damaging' type. Second is snare effect with 2 sec timer. Each channeling tick update snare duration timer.

**Comment by Thorgatin** [comment]
https://github.com/WarEmu/WarBugs/issues/1292

**Comment by ozarmidrashim** [comment]
The only IDs for Withering Heat are Damaging (damage) and Debuff (snare).

**Comment by Thorgatin** [comment]
So the snare is uncleansable.

**Comment by Silentguard** [comment]
Yea, i could be wrong about its type.
