### ISSUE TITLE
Guild Level achievement 

### ISSUE THREAD

**Issue by Jokerloz** [WarEmu/WarBugs#13345]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

every time i zone in the guild is saying i leveled my guild .

Steps to reproduce the problem:
Just zone in and/or change zones 

Screenshots/Videos or archive.org evidences:

![joker_011](https://user-images.githubusercontent.com/10342124/52553122-90e60b00-2db0-11e9-8035-648c4a215431.jpg)

**Comment by sioding** [comment]
This is not a bug - its intended. The guild packet informations is being sent with a delay to fix other guild problems. You you have to live with the situation atm.

**Comment by Jokerloz** [comment]
okay. asked other people didn't have the issue no need to be rude about it...
