### ISSUE TITLE
[Choppa] Bleed em out's Strength scaling.

### ISSUE THREAD

**Issue by Ripliel** [WarEmu/WarBugs#13349]
The ability has no contribution from strength.

Screenshots/Videos or archive.org evidences:
249 strength VS 950 strength -- you can see it clearly on the first and second to last ticks where no crits, rage modificators and etc happened. Even weapon's DPS does not contribute. 

![249 str](https://user-images.githubusercontent.com/16005849/52582570-88d4ac80-2e3e-11e9-816e-c1f39d3523b7.PNG)

950 strength
![950 str](https://user-images.githubusercontent.com/16005849/52582576-8b370680-2e3e-11e9-98af-9482aef56648.PNG)

**Comment by Torquemadra** [comment]
never has had
