### ISSUE TITLE
Morale Gain Praag Garnison of Skulls

### ISSUE THREAD

**Issue by Lideric** [WarEmu/WarBugs#13342]
At inner Keep Garnison of Skulls Kotbs and Choosen Auras (like On your Assault) can hit Blood Icons to gain Moral Boost.
![lid_005](https://user-images.githubusercontent.com/32113223/52539387-f1a82000-2d7d-11e9-8cda-551e93c836c9.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 23.02.2019
