### ISSUE TITLE
Ghastly Tooth collection 

### ISSUE THREAD

**Issue by Myrmer9247** [WarEmu/WarBugs#13350]
So i encountered this grey item with itemlevel today and its the first time seeing this. Not a Biggie, but i guess its also easily solved. Just close if its not worth the work. Loot in Bloodwrought enclave, screenie attached. 
![ganja_013](https://user-images.githubusercontent.com/36338066/52601094-f93ef600-2e5d-11e9-89cc-5b1152572092.jpg)

**Comment by wargrimnir** [comment]
These appear to have a sell price of 1s87c
