### ISSUE TITLE
Faith Is Madness Disappearing From Quest Tracker

### ISSUE THREAD

**Issue by Godhead9** [WarEmu/WarBugs#13356]
So i dont remember in which step i ve left the quest, but it disappeared one day without any reason or cause so i am not able to get my 1h weapon since i ve completed the other 2 quests.

![godhead_003](https://user-images.githubusercontent.com/46496255/52672946-f6103c80-2f27-11e9-9c86-01a3b997957b.jpg)
![godhead_004](https://user-images.githubusercontent.com/46496255/52672948-f8729680-2f27-11e9-84fa-afa9e777a70c.jpg)

Please reset my quests or something so i can pick it up and thank you.

**Comment by Lheana** [comment]
Duplicate of #13097
