### ISSUE TITLE
If you use siege weapon and take a scenario, you can not use any skill.

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#13354]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
If you use siege weapon and take a scenario, you can not use any skill. Effect persist until you die and respawn or resurrect.

Steps to reproduce the problem: Get in the siege weapon, take a scenario. Try to use any skill.

Screenshots/Videos or archive.org evidences:

**Comment by Natherul** [comment]
this issue should be fixed with the next patch

**Comment by Natherul** [comment]
fixed as of todays patch
