### ISSUE TITLE
Report a player 

### ISSUE THREAD

**Issue by Origin57** [WarEmu/WarBugs#13352]
Hello i just want to tell you to ban the detruction player MRGLASS ! This player use a hack for damage or something like this . He can instant any class in the game and he never have any cast , he can use all sorcerer dark elf in instant . See the screen join . 
![boufiole_003](https://user-images.githubusercontent.com/47485936/52646491-271a4e00-2ee3-11e9-9e5f-6f08f1cb3b93.jpg)

Thanks for your work and good continuations !

**Comment by SecretsOTheP** [comment]
Get crit reduction. Also I don't think this is a bug. Please stop spamming bug reports with people you die to.
