### ISSUE TITLE
No influence buff from Standard

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#13355]
With standard +5% renown for example you don't get any influence buff for example 1000 tick influence from crypt or warpblade tunnel should be 1000 +5% = 1050. It's only 1000 with Sandard

**Comment by sioding** [comment]
We have this one here too for renown: #13318

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 13.07.2019
