### ISSUE TITLE
[Gunbad] No damage in the trench

### ISSUE THREAD

**Issue by elk76** [WarEmu/WarBugs#13358]
Greetings,
we noticed that in the left wing in the last PQ at stage IV, the last boss "Foul Mouf da 'ungry" doesn't deal damage if people stay inside the trench

![eyvind_066](https://user-images.githubusercontent.com/46483570/52699742-c2103800-2f76-11e9-9023-0ac9bf35d787.jpg)
![eyvind_068](https://user-images.githubusercontent.com/46483570/52699747-c50b2880-2f76-11e9-8923-cccc0b48fc4a.jpg)

**Comment by grunbag** [comment]
fixed already
