### ISSUE TITLE
Chosen Auras broken

### ISSUE THREAD

**Issue by Verithan** [WarEmu/WarBugs#1335]
Aura spread failure, relogged to fix and it continues to happen. Horse got deleted last restart, second time it happened. I bought it the first time but I cant continue to keep rebuying my mounts. ingame name is Vero

**Comment by GreatHarlequin** [comment]
I'm having this problem too on my KotBS. Only 1 aura works and clicking on another gets an error, "Aura spread failure - one of your auras was removed."

**Comment by Evildoor** [comment]
I've played my KotBS and had no problems. This problem still persists for you two?
@Verithan - when reporting something, create separate tickets for separate problems, in this case auras and horse.

**Comment by GreatHarlequin** [comment]
No, I think it was a one off bug.
