### ISSUE TITLE
Flashing Claws White Lion tactic

### ISSUE THREAD

**Issue by yacoucou** [WarEmu/WarBugs#13351]
Hi, having issue with this tactic, not increasing parry (pet summoned ofc) at all.
Neither in getstats or statdoll or character stats.
Made tests with friends too, seems it dont work at all.

**Comment by sioding** [comment]
Hi - thanks for the report. Can you please attach your testing screenshot with the .getstats output? Thanks.

**Comment by Torquemadra** [comment]
works fine, you need pet out as tooltip says.

**Comment by funnytroll** [comment]
For me too
![troliel_010](https://user-images.githubusercontent.com/47090873/52703197-dceea680-2f8e-11e9-9c92-fc9333725482.jpg)
![troliel_009](https://user-images.githubusercontent.com/47090873/52703199-dceea680-2f8e-11e9-9db8-e95bd3dac623.jpg)
