### ISSUE TITLE
[Scenario] Short lags in Nordenwatch after each kill

### ISSUE THREAD

**Issue by Tyramissoux** [WarEmu/WarBugs#1336]
Today, a small lag occured whenever someone from my grp killed an enemy player in Nordenwatch. Can't say whether it affects any other SCs but it also happened to my grp mates.
Destro side.

**Comment by magter3001** [comment]
Happens from time to time... not sure how to recreate the bug but I think it only effect player kills.

**Comment by Silentguard** [comment]
Damn, i thought its only me get freezes. But as i noticed it happens at any sc.

**Comment by ozarmidrashim** [comment]
2-5 second lag will occur when the server performs a generation 2 garbage collection - this is happening very frequently due to a memory leak in the emu. Will be fixed soon.

**Comment by Silentguard** [comment]
Dont mean long lags, its a very short freezes about 0.5-0.7sec when some player dies.

**Comment by magter3001** [comment]
Yeah, the lags are about .5 seconds and happen after every kill, including orvr. Restarting client seems to fix it so don't know if that info helps or not.

**Comment by Silentguard** [comment]
Enemy addon turn off helps btw. Dont know what was changed in ror, probably some addon parser issue.

**Comment by Evildoor** [comment]
Does this still occurs? Many memory leaks were fixed since the report time.

**Comment by Evildoor** [comment]
No response, closing.
