### ISSUE TITLE
[Black Guard] Crimson Death Bugged

### ISSUE THREAD

**Issue by Warmasta** [WarEmu/WarBugs#13362]
Black Guard used only one skill (Crimson Death) and killed everyone around.

Dont know what happend but skill seems bugged.

 
![unknown](https://user-images.githubusercontent.com/47497345/52755400-dd2e8680-300e-11e9-82a6-264ec8a7bc6b.png)

**Comment by sioding** [comment]
Hm this screen is a start - but is it reproducable? Was it near a warcamp?

**Comment by Warmasta** [comment]
I dont have BG 40lvl so i cant reproduce it. It was near BO. Maybe this is a special case, anyway i just found this case strange and shared.

**Comment by sioding** [comment]
Since its no further testing has been made and we aren't able to judge the situation by one screenshot i will clsoe this now. whenever you finde mor information - don't hestitate to come with it and i'll reopen this one.
