### ISSUE TITLE
Character traversing Walls

### ISSUE THREAD

**Issue by MrShampi** [WarEmu/WarBugs#13364]
When I played  last time, i notice a severe bug that could be game breaking.
I saw players can negligates wall/traversing them.   So i think this is a real bug.
and so physics dont have to be negigated.

Expected behavior and actual behavior:
Player normally cant traverse walls on keeps.
character traversing wall. so certainly spells.

Suggestion:
chorecting the physics.

Screenshots/Videos or archive.org evidences:
![bug](https://user-images.githubusercontent.com/47632071/52786901-7d5ecc80-305c-11e9-8672-4937736e54e4.JPG)

**Comment by Lheana** [comment]
The player does not seem to walk through walls, it's just half of his mount which is inside the wall.

**Comment by sioding** [comment]
Thanks for the report but this isn´t a bug. The character model is not going through the walls. What you see is already mentioned by @Lheana .

**Comment by MrShampi** [comment]
yep but its still a bug.
and noticeable.
