### ISSUE TITLE
[Chosen][Ability] Corrupting Horror prevents activation of third aura

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13366]
Since the last patch Chosens are not able to activate a third aura if Corrupting Horror is already active.
Reproducible: Yes
Steps: Activate two auras, one of them must be "Corrupting Horror". Use a third aura, it will not activate.
Workaround: Activate Corrupting Horror as third aura.

**Comment by Torquemadra** [comment]
fixed

**Comment by sioding** [comment]
fixed with patch from 16.2.2019
