### ISSUE TITLE
Bestial Token(Order)

### ISSUE THREAD

**Issue by Jubok22** [WarEmu/WarBugs#13361]
Bridge Troll /  Troll Country                 No Token
Khuraakk Might-Horns /  Avelorn       No Token

miss now 2 tokens on my char Sigmarpriester :(

**Comment by Lheana** [comment]
Well it seems like you did not read rules before opening the ticket.
**Check RoR Wiki before opening a ticket related to Tome of Knowledge.**
The unlocks these NPCs trigger don't give bestial token.
https://wiki.returnofreckoning.com/index.php/Takes_its_Toll
https://wiki.returnofreckoning.com/index.php/Bossy_Beastie
