### ISSUE TITLE
High Amount of Renown and Influence

### ISSUE THREAD

**Issue by Foxrion** [WarEmu/WarBugs#13365]
This issue have happened twice.
Both times i have been Assisting in the kill.

![rr](https://user-images.githubusercontent.com/47640995/52806562-9b8ef180-3089-11e9-854e-6bb98b079666.PNG)

The values described in the SS was NOT given, infact noone.
I was rank 61 before the message appeared.
I had also maxed INF before the message

**Comment by Moragor** [comment]
Its a UI bug. On login rarely the XP/RR/inf values are not loaded correctly, you basically have 0 renown in the UI for the current level. If you now get any renown the whole amount of renown you already own for that level gets displayed.

**Comment by sioding** [comment]
Answer already given. Thanks to @Moragor
