### ISSUE TITLE
healthy oil

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#13360]
accidental testing reveals that the DoK skill "consume essence" is capable of healing oil (but only when the oil is NOT the defencive target), i assume this also applies to the WP equivalent skill and to other siege engines, i also checked to see and no rend soul does not heal the oil

**Comment by sioding** [comment]
Thanks for the report. Fix pending.

**Comment by sioding** [comment]
fixed with patch from 16.2.2019
