### ISSUE TITLE
NUrgling healdebuff in Bilerot Burrow

### ISSUE THREAD

**Issue by panodill** [WarEmu/WarBugs#13367]
Healdebuff from Nurglings get stuck even after cleanse. Have to relog to remove

Expected behavior and actual behavior:
Nurglings healdebuff people for 50% outgoing heal
After cleanse the 50% outgoing healdebuff should be gone but it is not removed for real, only on UI.
It get stuck and only way to get rid of it is to relog. 
Started after patch 09/02/2019 as far as i know.

Steps to reproduce the problem:
Get healdebuffed from Nurgling and then check .getstats after debuff is cleansed. Dont know if its on every healdebuff or random.

Screenshots/Videos or archive.org evidences:
https://i.imgur.com/WbBHz2e.jpg

**Comment by Torquemadra** [comment]
and the ability is called?

**Comment by grunbag** [comment]
Diseased bellow

**Comment by grunbag** [comment]
Disabled the ability until proper fix

**Comment by panodill** [comment]
its not disabled

**Comment by sioding** [comment]
fixed with patch from 09.03.2019
