### ISSUE TITLE
Kicked to Desktop when entering Nordenwatch area

### ISSUE THREAD

**Issue by Adimarchus** [WarEmu/WarBugs#13369]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Skeeze, rank 8 SH
Expect to be able to participate in Nordenwatch RvR
When I leave the warcamp and head into Nordenwatch, I get kicked to desktop upon getting close to Festenplatz.

Steps to reproduce the problem:
Logged back in, retried. Tried lowering video settings. Tried taking alternate route into RvR area.

Screenshots/Videos or archive.org evidences:

**Comment by Adimarchus** [comment]
Same thing happens at Mount Bloodhorn...get close to an objective, kicked to desktop.

**Comment by sioding** [comment]
Seems like you have a corrupted soundfile. This will fix your problem: https://returnofreckoning.com/forum/viewtopic.php?p=326158#p326158

**Comment by Adimarchus** [comment]
That worked, thank you!
