### ISSUE TITLE
Issues/bugs of invasions

### ISSUE THREAD

**Issue by fagio1989** [WarEmu/WarBugs#13379]
Expected behavior and actual behavior:
- Not be able to enter the invasion instance, but you can use the aoe through the barrier and been magnetized in.
- RR Respawn Farming at the spawn (there's no healer as well inside the enclosure).

Screenshots/Videos or archive.org evidences:
https://streamable.com/wz67m

**Comment by fagio1989** [comment]
hope that could be helpful for ur work, cheers!

**Comment by Natherul** [comment]
1 bug per report. also some of it has been fixed now.
