### ISSUE TITLE
Stick the Sticker

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#13374]
On wiki it is said that there is Champion on both order and destro sides.
https://wiki.returnofreckoning.com/index.php/Stick_the_Sticker
But one at 44k 6k, or 41k 4.7k Caledor coordinates is not there.

**Comment by Lheana** [comment]
To make it clear, the section "Original instructions" is just an information of how it is meant to work (how it worked on official).
To trigger the unlock, follow the instructions (section Instructions).
