### ISSUE TITLE
pots

### ISSUE THREAD

**Issue by Areanda** [WarEmu/WarBugs#1337]
the pots dont have cooldown timer so i can click 30 heal pots in a row for absolute nothing..but still lose pots.. noticed this while missclicking a skill and spamming on my pots >< lost like 45 pots in less then 1 min

**Comment by Evildoor** [comment]
Tested this, it seems only happening when you are dead - and that case was already reported:
https://github.com/WarEmu/WarBugs/issues/1168
Closing.
