### ISSUE TITLE
Marked buff problem

### ISSUE THREAD

**Issue by rycko2b** [WarEmu/WarBugs#13372]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Hello. The Marked buff from conqueror set (shadow warrior) only gives 20pts instead of 100.
When I am at 980ballistic, when the buff comes, I only go up to 1000.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Let me guess something - you already used a ballistic potion that buffs you 80 ballistic for 60 minutes. am i right?

**Comment by rycko2b** [comment]
Hi,

Yes Indeed, is it the potion that makes it bug ? how ?

Eric PETITET
Village
20212 ALANDU

________________________________
De : Sio <notifications@github.com>
Envoyé : Friday, February 15, 2019 6:48:46 PM
À : WarEmu/WarBugs
Cc : rycko2b; Author
Objet : Re: [WarEmu/WarBugs] Marked buff problem (#13372)


Let me guess something - you already used a ballistic potion that buffs you 80 ballistic for 60 minutes. am i right?

**Comment by sioding** [comment]
It is not a bug. It is working as intended. We don´t want that both things stack here.

**Comment by rycko2b** [comment]
I can understand, but why doesn’t it goes to 1050 then, which is softcap. Was just wondering
Eric PETITET
Village
20212 ALANDU

________________________________
De : Sio <notifications@github.com>
Envoyé : Saturday, February 16, 2019 10:46:30 AM
À : WarEmu/WarBugs
Cc : rycko2b; Author
Objet : Re: [WarEmu/WarBugs] Marked buff problem (#13372)


It is not a bug. It is working as intended. We don´t want that both things stack here.
