### ISSUE TITLE
Guild Roster doesn´t show any other members

### ISSUE THREAD

**Issue by Reconsniper** [WarEmu/WarBugs#13377]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
When I log in any of my toons  the Guild tab only shows the I'm the only one in the guild and the only one on atm 

Steps to reproduce the problem: Log in any of my toons and hit the Guild tad it dosn't show any guild member in the guild but the toon I have logged in atm  

Screenshots/Videos or archive.org evidences: sorry don;t know how to do a screenshot

**Comment by sioding** [comment]
Thanks for the report but it would help to have more informations than the subject. My own guild tab is working fine so i close this one here. You are welcome to create a new ticket with more information or a screen which shows the problem.

**Comment by Reconsniper** [comment]
I edited it LOL sorry

**Comment by sioding** [comment]
Can you please add a screenshot?

**Comment by Sandskid** [comment]
Its a well known issue. Once you've logged in, you see only yourself in guild roster. To see others you have to /rel every time you log in.

**Comment by Kaelang** [comment]
Looks like a duplicate compilation for the older report here https://github.com/WarEmu/WarBugs/issues/1438

Merging.
