### ISSUE TITLE
T3 Des Epic weapon quest. Honorable Deceit

### ISSUE THREAD

**Issue by Nemesiah** [WarEmu/WarBugs#13376]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Honorable Deceit t3 epic quest. Kill high elves throughout Jade Strand of Avelorn.
location Avelorn  6666, 36831  
Kill shining swift arrow
Kill veteran seablade

Steps to reproduce the problem:
Kill shining swift arrow mobs give warning of not attackable - but can still target it and killed
Kill veteran seablade -  mobs can't be targeted, but can be killed by aoe only, cant be targeted to loot after kill either.

Screenshots/Videos or archive.org evidences:

![nemasiah_002](https://user-images.githubusercontent.com/47683300/52894887-f563f880-31fc-11e9-9ccb-0a608e68c7a4.jpg)

**Comment by NorKalli** [comment]
Mobs are now target-able and attack-able

**Comment by sioding** [comment]
fixed with patch from 09.03.2019
