### ISSUE TITLE
Salzenmund stage 1 crate can be selected multiple times

### ISSUE THREAD

**Issue by VoljiKelagar** [WarEmu/WarBugs#13373]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by VoljiKelagar** [comment]
On the Salzenmund PQ stage 1 you can select the crate multiple times to progress the PQ at 50463,54730 on the map.

**Comment by Kabucoror** [comment]
same problem as  #13524

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/14893
