### ISSUE TITLE
Alternative ways to bypass the fortress limit

### ISSUE THREAD

**Issue by Tyrvar** [WarEmu/WarBugs#13380]
Expected behavior and actual behavior:
Limited numbers in Fortresses with a hardcap to prevent going above the limitation on numbers. This can be bypassed for defenders by using the WAR Report to teleport into the Fortress. Not tested this as an attacker.

Steps to reproduce the problem:
Whilst the fortress is full and hardcap enabled to prevent additional defenders/attackers, use the WAR report to teleport to "enemy engaged at Butcher's Pass" or any other fortress that is engaged. This will teleport you to the top of the keep.

Screenshots/Videos or archive.org evidences:

**Comment by Natherul** [comment]
fix for that coming.
