### ISSUE TITLE
RVR status bug

### ISSUE THREAD

**Issue by funnytroll** [WarEmu/WarBugs#13381]
Hi,today after patch i stay in pve zone without rvr status and get killed by destro
In this ui, rvr status show on right side of screen where unit frame(3 screenshot)

![trolgar_076](https://user-images.githubusercontent.com/47090873/52902149-fbb69c80-321d-11e9-94f7-92c1e9d11464.jpg)
![trolgar_077](https://user-images.githubusercontent.com/47090873/52902150-fbb69c80-321d-11e9-9d16-000f45a57cb5.jpg)
![trolgar_078](https://user-images.githubusercontent.com/47090873/52902194-b9418f80-321e-11e9-85e9-7f05e3b50c65.jpg)

**Comment by sioding** [comment]
Kinda strange. I was at the same place as you was - and got no rvr flag. Tried to get attacked by tester - won´t work. So its not reproducable. KInda hard to fix something that we can´t reproduce. Would be great if you or others find more information on this or how it could be verfied.

**Comment by sioding** [comment]
No answer for 16 days. close
