### ISSUE TITLE
[Fortress] Butcher's pass low lvl players

### ISSUE THREAD

**Issue by elk76** [WarEmu/WarBugs#13388]
In the last fight in Butcher's pass, I saw many low lvl players, despite the 40/40+ restriction.
I asked to a guild member to try some test
I noticed that the restriction works if you try to reach the fortress from the RvR, whereas if you use the WAR report you can skip the restriction

![puparuolo_123](https://user-images.githubusercontent.com/46483570/52905546-0bdd7480-323c-11e9-890d-bd065f5bf305.jpg)
![puparuolo_124](https://user-images.githubusercontent.com/46483570/52905548-0e3fce80-323c-11e9-99f8-09ba525779c0.jpg)
![puparuolo_125](https://user-images.githubusercontent.com/46483570/52905550-10099200-323c-11e9-8d93-00e6645e192c.jpg)

**Comment by sioding** [comment]
I am quite sure these below40 characters found a way to the fortress area we haven´t closed now like warreport or some mountain to slide down.

**Comment by Natherul** [comment]
indeed, unforseen methods of entrance was used and should have been closed by now. If more are discovered please make a specific report on where said entry was from
