### ISSUE TITLE
Abilities/Attacking

### ISSUE THREAD

**Issue by JoshLJustice** [WarEmu/WarBugs#1338]
This is something that has happened on every character I have made and it only really seems to happen in pvp. When I'm attacking someone and I'm having to be mobile and move to keep up with the enemies, my abilities will often not want to work. I can literally be right behind an enemy and I can spam a skill such as the slows or anything instant cast, yet my characters will twitch like they want to but nothing. It's like I have to stand still to use an ability, and if I do that they either get more distance or I can't get away. Any help would be greatly appreciated.
Not sure if it's a known bug or what
:)

**Comment by Radiantknight** [comment]
Melee char? It's common problem. For the time being, try jumping simultaneously with using skill, works good especially versus jumping players. It is connected to bad sync on position update, and jumping/strafing makes server update info more frequently.

**Comment by JoshLJustice** [comment]
I believe someone told me it was from the server being in Europe, and where I live in the states it causes be to lagg behind a little.
I think I can manage until they get it fix :P

**Comment by Evildoor** [comment]
Known issue. https://github.com/WarEmu/WarBugs/issues/981
