### ISSUE TITLE
Horrors of War  - Raven Marauders

### ISSUE THREAD

**Issue by boss21** [WarEmu/WarBugs#13382]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Expected: Get credit for killing Raven Marauders as part of quest

Actual: Not getting credit for killing Raven Marauders as part of quest

Steps to reproduce the problem:

Step 1. Get Horrors of War quest from Grimmenhagen Village
Step 2. Go to area shown and attack raven marauders

Screenshots/Videos or archive.org evidences:

**Comment by boss21** [comment]
This is weird, but if you turn your RVR flag on and right click as a chicken you get credit. Noticed this same concept for other quests. Also, for other quest's I've had in altdorf, if I am in a party with someone who's done the quest, then I cant do it.

**Comment by sioding** [comment]
The "is in a party" thing is known and something thats on the list to fix. The others you said is new to me. Can you please have an example where you can´t get a credit and with turning on the rvr flag you can?

**Comment by sioding** [comment]
No answer for 16 days. Close
