### ISSUE TITLE
quest order side Ellyrion : into the flames

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#13383]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
There is no red mark on the map after finishing the first part of the quest
(kill 10 enemy blackguards= the red mark should be at chapter 8 Ellyrion
![thorbolt_696](https://user-images.githubusercontent.com/16274785/52902560-c0fb3700-3212-11e9-9db2-b63a57dba9a8.jpg)
 (chapter 8 Ellyrion)
Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Lheana** [comment]
End quest marker is set. You must have logged out after you completed the quest.
So related to #13047

**Comment by HeiLei1994** [comment]
I'm having issues with this quest, the map doesn't show an area/where to go to kill the Blackguards.

**Comment by Lheana** [comment]
This is because it's everywhere you will find an enemy Blackguard.

**Comment by HeiLei1994** [comment]
Okay, do you mean the dark elves in general or a specific mob called "Blackguard" that exists everywhere? Because I've already finished the zone, and nothing have registered.
Thanks for your quick response!

**Comment by Lheana** [comment]
Enemy players who are blackguards.

**Comment by HeiLei1994** [comment]
Ah okay, you meant pvp haha.
Thanks for clearing up the misunderstanding.
Cheers!
