### ISSUE TITLE
CTD when loading character

### ISSUE THREAD

**Issue by Xetesk** [WarEmu/WarBugs#13384]
When attempting to log into my Chaos Chosen character it crashes to desktop every time before the load is completed. It is just this character, I have tried multiple more. I have deleted my cache, my user settings and even completed a fresh install. I attempted the "/stuck" option during loading screens. This originally moved me from Nordland to Norsca, to no avail. Upon contacting a Mod in-game who moved my character to IC, same result. Character was logged in successfully last night with no issues.

**Comment by Raull01** [comment]
Xetesk, I have the same problem!!I deleted the character profile-did not help.don't know what to do.

**Comment by sioding** [comment]
I am sorry but the bugtracker won´t help you here at all. I would suggest you use the forum for such questions. Look at this board: https://www.returnofreckoning.com/forum/viewforum.php?f=4
