### ISSUE TITLE
Fortress Butchers Pass prison

### ISSUE THREAD

**Issue by panodill** [WarEmu/WarBugs#13385]
Enemy players can damage me when in prision cage in Butchers Pass as defender.

Expected behavior and actual behavior:
Should not take damage when in cage. Abilities that are ground target damage us, like Rain of Fire and napalm.

Steps to reproduce the problem:
Be in cage, BW do rain of fire on you.

Screenshots/Videos or archive.org evidences:
https://i.imgur.com/K8Eyssb.jpg

**Comment by anazarelle** [comment]
https://image.noelshack.com/fichiers/2019/07/7/1550384626-anazarelle-008.jpg

See many non lvl 40 in fortrss

**Comment by sioding** [comment]
@anazarelle i will delete your comment - we can´t have more than one problem per report. so please do not highjack other reports. create your own one.

**Comment by Natherul** [comment]
this should have been fixed in the hotfix late last night
