### ISSUE TITLE
forteress butcher's pass 126 des vs 109 order glitch near barrier

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#13387]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
You have a glitch to the east of the barrier so destro and order can pass and Jump in Butcher's pass
so destro 126 order 109
![thorbolt_701](https://user-images.githubusercontent.com/16274785/52905255-e3ec1200-3237-11e9-9ccb-90caa67262f7.jpg)

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by panodill** [comment]
https://i.imgur.com/nJtgcfk.jpg
https://i.imgur.com/ZrdHQBf.jpg

**Comment by Kabucoror** [comment]
You can't do that anymore

**Comment by dalen** [comment]
@Kabucoror tried it today. Still very possible.

Same issue as this:
https://github.com/WarEmu/WarBugs/issues/13427
https://github.com/WarEmu/WarBugs/issues/13428

**Comment by sioding** [comment]
fixed with patch from 23.02.2019

**Comment by dalen** [comment]
Tried it after 2019-02-23 patch, and it is still possible, so this needs to be reopened.
