### ISSUE TITLE
No healer in fort to cleanse Battle Fatigue

### ISSUE THREAD

**Issue by panodill** [WarEmu/WarBugs#13386]
No healer in fortress as defender or attacker in Butchers pass, have not been in other forts.

Expected behavior and actual behavior:
Should be a healer to remove the woundsdebuff. There is none.

Steps to reproduce the problem: Die, look around for healer in panic because artillery is comming :D

Screenshots/Videos or archive.org evidences:

**Comment by sioding** [comment]
Sorry but the bugtracker is not the placer for suggestions. Please move to the forum with this wish.

**Comment by Natherul** [comment]
and btw this is very much intended.
