### ISSUE TITLE
[Gunbad][NPC]/[Quest] Disgraced Chipfang has a quest icon but does not offer a quest

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13389]
The Snotling "Disgraced Chipfang" in Gunbad right wing (destro) has a quest icon, but clicking on him does not open a dialog window.
Confirmed by all 6 party members.

![moragor_000](https://user-images.githubusercontent.com/30193675/52906479-05a3c400-324d-11e9-8346-6e2aa64d5287.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 23.02.2019
