### ISSUE TITLE
Sentinel Jewelry

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#13392]
Just noticed weird thing that you cannot equip sentinel jewelry in any slot but third.
![1313312](https://user-images.githubusercontent.com/42712833/52915406-c628b680-32e4-11e9-8b50-038b870dda25.PNG)
![veszal_636](https://user-images.githubusercontent.com/42712833/52915409-ccb72e00-32e4-11e9-843c-f768acee0814.jpg)

**Comment by wargrimnir** [comment]
Not a bug
