### ISSUE TITLE
Tanks Staggers

### ISSUE THREAD

**Issue by Tobias26** [WarEmu/WarBugs#13391]
Expected behavior and actual behavior:
According to the tootip of stagger, he must stun the target for 5 seconds, but it is the tanks he stuns only for 3 seconds.

**Comment by CrimsonFenris** [comment]
Are you sure the target was not using any faster recovery tactic (50% less duration on stagger, kd and disarm effects) ?
I know Slayers can use it (Stoutness of Stone), maybe other tank classes got it as well (IB if its a racial trait).

**Comment by Tobias26** [comment]
Yes, I'm sure, because I saw these three seconds on me a lot of times.

**Comment by jonomurphy** [comment]
This was changed to 3 seconds quite some time ago, and simply means that the tooltips will need to be changed to reflect this.

**Comment by grunbag** [comment]
Fixed at Next Patch

**Comment by sioding** [comment]
Fixed with patch from 02.03.2019
