### ISSUE TITLE
fortress lord pull groundfloor and get killed

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#13396]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Yesterday destro send just a black orc to pull the lord then the lord was at the ground floor and killed in 2 minutes.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Natherul** [comment]
fix pending next hotfix. I was a doofus last attempt I did and missed an obvious variable.

**Comment by thorbolt80** [comment]
This morning during order attack the lord was also pulled on ground floor. (butcher pass)

**Comment by Natherul** [comment]
this has been addressed once more, please to comment back if it still does not work
