### ISSUE TITLE
Error message during fort lock

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#13390]
2nd Butcher's Pass siege. Everyone got renown but there was no bagroll, with this message. After it I think roll was triggered manually by team.
![veszal_627](https://user-images.githubusercontent.com/42712833/52907490-6940e800-3273-11e9-9e44-25f607d4031d.jpg)

**Comment by Natherul** [comment]
should have been fixes as of the hotfix later that night
