### ISSUE TITLE
Devastate (Slayer, Middle Tree, 9 pts.) debuff duration too short

### ISSUE THREAD

**Issue by Bowldancer** [WarEmu/WarBugs#13393]
Expected behavior and actual behavior:
Wound debuff duration is supposed to be 10 seconds but it is only 8 seconds long.

Steps to reproduce the problem:
Hit something and see that the debuff timer starts at 8 seconds.

**Comment by grunbag** [comment]
Fixed at next patch

**Comment by sioding** [comment]
Fixed with patch from 02.03.2019
