### ISSUE TITLE
Sorc Invader Helmet missing main stat (Intelligence)

### ISSUE THREAD

**Issue by Aeriell** [WarEmu/WarBugs#13409]
I just dropped an Invader piece set (helmet) for my Sorc (Pizzabomb) this morning.
I noticed it is missing a stat bonus (most likely intelligence).

You can find attached the screenshot of the evidence (in relation with the Conqueror one)

![pizzabomb_002](https://user-images.githubusercontent.com/22699329/53018931-e2973100-3453-11e9-9cb1-35923d68eb3a.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by Aeriell** [comment]
Is it worth a manticore? :) (wishing haha)

**Comment by SecretsOTheP** [comment]
Not even close.

**Comment by sioding** [comment]
Fixed with patch from 02.03.2019
