### ISSUE TITLE
order wc marsh of madness spawn point not protected 

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#13405]
![thorbolt_737](https://user-images.githubusercontent.com/16274785/52995216-3e44c880-341a-11e9-9fcf-9030db50181d.jpg)
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
The war camp was attack by destruction 38.41 you should add a gard to protect the respawn point around this place
![thorbolt_743](https://user-images.githubusercontent.com/16274785/52995096-f02fc500-3419-11e9-911e-fd9148beaff6.jpg)
![thorbolt_741](https://user-images.githubusercontent.com/16274785/52995153-0d649380-341a-11e9-9f46-b9002acd40d6.jpg)

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Lheana** [comment]
This should have been fixed with the patch of today.
