### ISSUE TITLE
Somewhat repeatable vendor issue getting different items on buy back.

### ISSUE THREAD

**Issue by Valdisr** [WarEmu/WarBugs#13402]
I didn't see anything on here exactly with same issue I had, but anyways. Selling items to Lady Something by Nina the collector of kills in Troll country as a lvl15 DoK, I sold a cloak to her and realized I needed it, so when I bought it back instead of the cloak I got a SH mount. This had happend earlier this day and I got a brown dye or something inocous and didnt think much of it until later. I still have the mount thing in my inventory and havent sold it in case yall needed to see it or whatever

Disciple of Khaine, Name: Valdisr, Dead Cell guild.

**Comment by MaxHayman** [comment]
@sioding does this happen with any vendor?

**Comment by Valdisr** [comment]
No, it was a vendor in troll country dont remember what name offhand country

**Comment by sioding** [comment]
Hm kinda hard to reproduce with missing informations. Do you remember if it was in the warcamp?

**Comment by Kaelang** [comment]
No further information was provided. Closing.
