### ISSUE TITLE
forteress have no barrier and no ram auto attack

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#13400]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Today order after losing versus destro at  forteress the zone flip to black crag then we take black crag another time then we arrive at butcher pass they were no barriers and no auto attack ram.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Maleus1979** [comment]
Also some players and champion NPCs at fortress were invulnerable.

**Comment by Natherul** [comment]
this should have been fixed in yesterdays fix.
