### ISSUE TITLE
Pierce defenses debuff stacks

### ISSUE THREAD

**Issue by Tobias26** [WarEmu/WarBugs#13401]
Expected behavior and actual behavior:
Pierce defenses debuff caused by the same tactics of eng/squig can stack. As a result, if the character is attacked by several eng/squigs, he get many same debuffs, and his defensive parameters can be reduces by 30%, 45% and more.

**Comment by thorbolt80** [comment]
This is not a bug it was same on live server

**Comment by Tobias26** [comment]
Ok, let's do everything so that with the same mechanics, and the four chosens will reduce your toughness by 480 and incoming healing by 100%. This is nonsense, the same debuff may not be imposed several times.

**Comment by SecretsOTheP** [comment]
Don't think these are additive on the server. Can you .getstats while having two debuffs on you?

**Comment by Tobias26** [comment]
I haven't used getsats, but in the character window I saw the reduction characteristics by 30%, 45%, and so on. In the case of a 45% reduction, all attacks hit me, as if the chances of blocking, parrying and dodging were really reduced to zero.

**Comment by SecretsOTheP** [comment]
The paperdoll isn't reliable. If you can, please check the .getstats command.

**Comment by Tobias26** [comment]
Getstats shows effect from one debuff only. But getstats can be bugged too, look at my crit chance here^
https://www.youtube.com/watch?v=4MEdrQWJwjk&feature=youtu.be

**Comment by grunbag** [comment]
Get stats is the one you should trust
