### ISSUE TITLE
Tower of The Elves Chaos Chapter 14 no NPCs

### ISSUE THREAD

**Issue by Schmaaaan** [WarEmu/WarBugs#13403]
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
There were no Elves to kill that were needed for the first stage of the Public Quest.

Steps to reproduce the problem:
So far i cant find any of the Crystalgrow Elves that are needed for the Quest.

Write "Schmaaaan" for more information ingame

Screenshots/Videos or archive.org evidences:

**Comment by Lheana** [comment]
#10862
