### ISSUE TITLE
[IB] Punishing blow damage is too high

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#13408]
tooltip and dmg (without taunt):
Screenshots/Videos or archive.org evidences:
<img src="https://monosnap.com/image/R05WhjzEy3Rdx1anFXd3nC4BcY5DG1.png">
def tank dmg:
<img src="https://monosnap.com/image/I7fS3OC50EDXn8fmkwsr6x3bEw1vlf.png">

PS: hello all IBs who still think to report this or not

**Comment by grunbag** [comment]
Fixed at Next Patch

**Comment by sioding** [comment]
Fixed with patch from 02.03.2019
