### ISSUE TITLE
maw of madness forteress no portal to enter

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#13404]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
Order took chaos waste but no portal to enter forteress  but the maw of madness door took damage see screenshot. I guess isn't implemented yet?
![thorbolt_733](https://user-images.githubusercontent.com/16274785/52994928-739ce680-3419-11e9-9bcd-d97bafe3a04f.jpg)

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Natherul** [comment]
this has been fixed, thanks for the report
