### ISSUE TITLE
Madcap weapons: sell price

### ISSUE THREAD

**Issue by elk76** [WarEmu/WarBugs#13417]
Greetings,
last night in Gunbad, I noticed that the sell price of Madcap weapons obtained from Purple Bag (PQ) is very high (about 10gold) compared to similar weapons like Subjugator

![eyvind_069](https://user-images.githubusercontent.com/46483570/53093737-93ff9a80-3518-11e9-9637-e138e4b291ee.jpg)
![eyvind_070](https://user-images.githubusercontent.com/46483570/53093738-93ff9a80-3518-11e9-92b7-0604c5b608b5.jpg)

**Comment by wargrimnir** [comment]
Subjugator/Smuggler items probably shouldn't have a sell price at all. They're acquired from purple bags. Sell price on Madcap items are correct. Either way the value of these items for talisman makers should be considerably higher than 10g anyway.
