### ISSUE TITLE
[Crypts] Problems with lockouts

### ISSUE THREAD

**Issue by Sandskid** [WarEmu/WarBugs#13411]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior: We entered the Altdorf Crypts, but we forgot that we all had lockouts. There were mobs inside, and we killed them. When we arrived to boss, he wasn't there. At that moment we've figured out that all of us had lockout. We left the Crypts and waited for lockouts to disappear. When we've entered again, there were no mobs and no boss. We've tried to change a leader (from the same group) -> nothing have changed. Then we decided to take another player (not from this group) as a leader, entered the dungeon, removed this player and took back a player from the main group. Mobs were visible for the group that entered with the new leader, but for the player that was taken instead of the new leader there were still no mobs and no boss, however we all were in the same mirror. Now both us and a new leader have no mobs and no bosses inside.

Steps to reproduce the problem: enter the Crypts with the group with lockouts, kill mobs, leave, wait untill lockouts dissapear and enter this dungeon again.

Screenshots/Videos or archive.org evidences:
http://funkyimg.com/i/2RxaZ.png

**Comment by grunbag** [comment]
fixed alrerady
