### ISSUE TITLE
No Renown XP after locking Caledor

### ISSUE THREAD

**Issue by bugsformount8** [WarEmu/WarBugs#13416]
Order side locked Caledor just now and there is no renown xp reward for locking, Only a bag roll

**Comment by bugsformount8** [comment]
Apparently you don't get any metals or seals also

**Comment by bugsformount8** [comment]
Also last note, I'm sure you don't get XP and rewards for locking Black Crag also. I'll confirm if and when we lock BC

**Comment by sioding** [comment]
I merge these two reports cause it seems to be an iessie for all zones before the fortress
Duplicate of #13413
