### ISSUE TITLE
Missing mailbox

### ISSUE THREAD

**Issue by Vezper** [WarEmu/WarBugs#13410]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
I am not sure if this is an actual bug, so i am sorry in advance for wasted time. I have noticed that the mailbox in Norsca camp is missing. I am not sure if this was intentional or not, so i have decided to report it as a bug. The mailbox used to be next to a merchant , not far from trade skill trainers.
as i said, it isn't a big deal, and it might have been intentional, so thanks in advance for your reply and help.

Steps to reproduce the problem:

Screenshots/Videos or archive.org evidences:

**Comment by Kabucoror** [comment]
added a mailbox in Norsca CH 2, with next patch

**Comment by Vezper** [comment]
Many thanks ! Vessper.

**Comment by Vezper** [comment]
Just to let you guys know, mail boxes not appear to be working anywhere after latest patch, cheers.

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
