### ISSUE TITLE
No Renown XP after locking Chaos Waste in the last 3 times

### ISSUE THREAD

**Issue by bugsformount8** [WarEmu/WarBugs#13413]
Order side locked CW 2 times yesterday, and again just now. There is no renown xp reward for locking, Only a bag roll

**Comment by Rydiak** [comment]
Can confirm.  Got a bag roll, but did not get any renown nor medallions/seals.

![rydiak_368](https://user-images.githubusercontent.com/15963532/53068093-bf44a400-349c-11e9-9505-f5c30530c493.jpg)

**Comment by bugsformount8** [comment]
Caledor didn't give any renown xp also after lock. I'm guessing Black Crag doesn't give xp either

**Comment by Rydiak** [comment]
I got a gold bag from Caledor, but no medallions/seals nor renown again. I am assuming this is bugged when leading into a Fortress.

**Comment by bugsformount8** [comment]
Yeah that's what it sounds like

**Comment by bugsformount8** [comment]
Saw a hotfix today. We locked CW but still no renown xp reward

**Comment by Rydiak** [comment]
![rydiak_379](https://user-images.githubusercontent.com/15963532/53156008-f80b7880-3583-11e9-8d92-dee3a77faacb.jpg)

Yep, CW locked again and no renown/medallions/seals.
