### ISSUE TITLE
Birds of a Feather, Elf Tier 1 Quest bugged

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#13412]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Upon completing this quest you should be able to select one item and obtain it. You can click the item, click complete, but the reward is not issued and the quest giver still has the yellow circle above her head.

Steps to reproduce the problem:

Allow quest completion.

Screenshots/Videos or archive.org evidences:

![volyar_000](https://user-images.githubusercontent.com/22262165/53052349-607c2c00-3496-11e9-9110-f0a9cb85e18d.jpg)

**Comment by Senthoi** [comment]
I revisited this tonight in game. After travelling through again and clicking the banners, it worked and I was able to complete this quest. Seems to have resolved itself.

**Comment by Lheana** [comment]
Yes, you could not pick the rewards as you hadn't completed the quest.
