### ISSUE TITLE
[RvR] Butcher Pass not open after BC lock.

### ISSUE THREAD

**Issue by XmatXergon** [WarEmu/WarBugs#13419]
Expected behavior and actual behavior:
After order lock Black Crag campaign should push progress to Butcher Pass (Greenskin Fortress) but instead for some reason it pushed to Thunder Mountain.

Steps to reproduce the problem:
Lock Black Crag for Order (maybe same happens when Destro lock Kadrin Valley).

Screenshots/Videos or archive.org evidences:
![xergom_114](https://user-images.githubusercontent.com/37849311/53103004-13976480-352d-11e9-9233-616ec8fc23c2.jpg)
![xergom_115](https://user-images.githubusercontent.com/37849311/53103011-15f9be80-352d-11e9-97bb-4a8776383df4.jpg)

**Comment by SecretsOTheP** [comment]
This is because of the code that was broken that I pointed out. @Natherul
