### ISSUE TITLE
[RvR] Fortress: Fell Landing barrier skip.

### ISSUE THREAD

**Issue by XmatXergon** [WarEmu/WarBugs#13420]
Expected behavior and actual behavior:
Barrier should fully block players from reaching fortress Fell Landing through PvE/Terrain.
Barrier can be skipped by climbing mountain at 61k 26k.

Steps to reproduce the problem:
Lock Caledor for Order and check barrier.

Screenshots/Videos or archive.org evidences:

![xergos_154](https://user-images.githubusercontent.com/37849311/53104103-0f6c4680-352f-11e9-95c3-ea33129432de.jpg)
![xergos_153](https://user-images.githubusercontent.com/37849311/53104105-0f6c4680-352f-11e9-9b32-cffebcf75288.jpg)
![xergos_152](https://user-images.githubusercontent.com/37849311/53104106-0f6c4680-352f-11e9-8099-dad22b5c6bb9.jpg)
![xergos_151](https://user-images.githubusercontent.com/37849311/53104107-1004dd00-352f-11e9-9039-6677ced91257.jpg)
![xergos_150](https://user-images.githubusercontent.com/37849311/53104108-1004dd00-352f-11e9-9b29-0fa743b12ffd.jpg)

**Comment by Mictlan818** [comment]
Zone: The Maw is only supposed to let level 40's to spawn/port in.
As a level 22 Marauder, I was poking around its PvE area as the Fortress was active, jumped off a cliff (32k 62k.7) died and found myself spawned in its prison. Was let out by some Destro and even got the RR/Exp tick.

![screenshot 7](https://user-images.githubusercontent.com/47844974/53151884-05ffd000-3569-11e9-9fb9-a9ebe2d4dc38.png)

![themaw2](https://user-images.githubusercontent.com/47844974/53152017-5bd47800-3569-11e9-8dfe-35e624d0efd1.JPG)
![themaw3](https://user-images.githubusercontent.com/47844974/53152023-5f67ff00-3569-11e9-9c64-bad1d328233f.JPG)
![themaw4](https://user-images.githubusercontent.com/47844974/53152037-6727a380-3569-11e9-8311-78ff5f4fc4ad.JPG)

**Comment by dalen** [comment]
Similar issue at Butcher's Pass: https://github.com/WarEmu/WarBugs/issues/13427

**Comment by dalen** [comment]
In the maw you can actually get in alive as well using a bit of semi-advanced mountain climbing. Starting around 48,1 in Chaos wastes, just west of where a mob is standing on the cliffs. Then walk on top of the mountain ridge around the menagerie and drop down in fortress.

**Comment by Kabucoror** [comment]
was not able to get there
and pls don't mix problems like that on one ticket

**Comment by dalen** [comment]
Created a separate ticket for the PvE route to the Maw: https://github.com/WarEmu/WarBugs/issues/13534

**Comment by dalen** [comment]
And a separate one for the menagerie+die+respawn way into the Maw: https://github.com/WarEmu/WarBugs/issues/13535

**Comment by XmatXergon** [comment]
OK, seems like skipping barrier is not worth anymore.
If you dont go through portal you wont be participant in PQ and you wont get any loot from Fortress.

Only problem is, some groups still can get in to make number difference and farm ppl.

**Comment by Kabucoror** [comment]
If you enter a fort not through the portal, you will get ported out. So this is not longer an issue.
