### ISSUE TITLE
Permanent mastery

### ISSUE THREAD

**Issue by Aebell** [WarEmu/WarBugs#13425]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
I go to respecialize my masteries, one mastery point stays in the left tree while all my other points are refunded. It's happening on all my characters.

Steps to reproduce the problem:
It's happening with all my characters, I'm not sure how I could reproduce it

Screenshots/Videos or archive.org evidences:

![heimdahl_000](https://user-images.githubusercontent.com/44963666/53221997-b67cdb00-3620-11e9-8d44-f60d6b748bfb.jpg)

**Comment by sioding** [comment]
Thanks for the report. Have you checked your set bonuses? Some sets give an extra point on a mastery line. Please add a screenshot with with a mouse hovering over one of your set items.

**Comment by sioding** [comment]
No answer for 20 days. Close
