### ISSUE TITLE
Territorial Aggression stops squig herder from summoning squig

### ISSUE THREAD

**Issue by Ohwaitno** [WarEmu/WarBugs#13423]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:
When using territorial Aggression it should allow me to have a squig pet summoned

Steps to reproduce the problem:
Just try to summon a Squig pet with the tactic slotted

Screenshots/Videos or archive.org evidences:

**Comment by Lefze** [comment]
That's exactly how it's supposed to work. You loose the ability to summon pet, but the armor buff is moved from being tied to pet being alive directly to the player. In addition you get the damage buff and 0 sec CD Squig Leap.

It's just the melee version of ABM.

**Comment by grunbag** [comment]
It work as intended
