### ISSUE TITLE
Fortress portal can be bypassed in Butchers Pass

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#13427]
**Expected behavior and actual behavior:**

You should be required to go through portals for Fortress population checks. But for the Butchers Pass fortress you can walk from PvE over a mountain and drop down into the fortress zone behind the barrier. Thereby bypassing any population check.

**Steps to reproduce the problem:**

Walk roughly where the purple line is. Drop down behind barrier at in the Butchers Pass zone.

Screenshots/Videos or archive.org evidences:

![black_crag_map](https://user-images.githubusercontent.com/7400/53237312-ad2e5580-3696-11e9-8198-64fd302a4339.png)

**Comment by sioding** [comment]
fixed with patch from 23.02.2019

**Comment by dalen** [comment]
@sioding This is actually still possible

**Comment by Kabucoror** [comment]
dublicate of #13471, which is fixed today
