### ISSUE TITLE
Bypass Fortress Barrier in Black Crag without using portal

### ISSUE THREAD

**Issue by bugsformount8** [WarEmu/WarBugs#13428]
There's a way to get through the Fortress shield barrier without using the portal. It's useful because of Destro ganking near the portal. Screenie is at the bottom, but it's not exact. Basically you just go up the hill and keep going and there will be an open area on top of the hill to jump into the Butcher's Pass

https://i.imgur.com/xsCEfRE.jpg

**Comment by dalen** [comment]
Was like 1 min before you :) https://github.com/WarEmu/WarBugs/issues/13427

**Comment by sioding** [comment]
fixed with patch from 23.02.2019
