### ISSUE TITLE
[Scavenging] in Altdorf / IC

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#1342]
Destro can scavenge 33-34 lvl mobs in IC, order cant in Altdorf

**Comment by Radiantknight** [comment]
Well, order could scavenge lvl25 mobs and getting tali making past 134 from the start, ain't so?
Also, not  many do this, because, like I said, not many did get their tali making past 134, making this scavenging useless.

**Comment by Evildoor** [comment]
Not a bug. Such things should be discussed on forums.
