### ISSUE TITLE
People in Fortress jail can still use abilities

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#13426]
**Expected behavior and actual behavior:**

While being in jail you should be out of the fight. But you can for example heal people trying to free you. So to stop a tank from freeing people can be very difficult if there's a couple of healers in the jail.

**Steps to reproduce the problem:**

Get jailed in fort, use ability like normal from inside jail while being unkillable.

**Comment by sioding** [comment]
Discussed in discord - closed

**Comment by dalen** [comment]
I think you misinterpreted that discussion. Natherul said that this was indeed a bug but raising the cast time of the lever is a feature request, not a bug.

**Comment by sioding** [comment]
ah ok - got it the wrong way

**Comment by sioding** [comment]
fixed with patch from 23.02.2019
