### ISSUE TITLE
Fortress lord, Gromtusk Da Ravager, is facing the wrong way

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#13434]
**Expected behavior and actual behavior:**

He should be facing the door, not have his back against the door and the attackers.

**Steps to reproduce the problem:**

Go to Butcher's Pass lord room entrance.

**Screenshots/Videos or archive.org evidences:**

![zhapp_001](https://user-images.githubusercontent.com/7400/53261897-775c9180-36d5-11e9-846f-e16f7626af43.jpg)

**Comment by Lheana** [comment]
It seems fine. Note that if he is pulled or if a player talks to him, Gromtusk may turn.
