### ISSUE TITLE
[WH] ticks of BAL dont break stagger 

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#13437]
**Screenshots/Videos or archive.org evidences:**
https://youtu.be/tCnwwDt3YFA
<img src="https://monosnap.com/image/249zz9kqaRAXIUdJlY2vIsepRx6m5h.png">

**Comment by Scophis** [comment]
Is this only with BAL or dots in general?

**Comment by Nfkillz** [comment]
probably all melee dots

**Comment by grunbag** [comment]
FIXED with next patch
