### ISSUE TITLE
[WL] leap

### ISSUE THREAD

**Issue by Radiantknight** [WarEmu/WarBugs#1343]
Excuse me, but is he supposed to leap on keep walls with this ability? They overuse it a lot anyway, but jumping up 1-2 floors isn't that healthy for keep defense.

**Comment by Silentguard** [comment]
Cool feature imo.

**Comment by wiscel** [comment]
Even when punch a WL of the wall with sorc 2 moral, they use the jump again in midair and they're back on the walls again. Don't think WL could do that when WAR was live.

**Comment by Evildoor** [comment]
https://github.com/WarEmu/WarBugs/issues/1222
