### ISSUE TITLE
[SM] SM medium punt is not medium

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#13438]
**Screenshots/Videos or archive.org evidences:**
<img src="https://monosnap.com/image/dR7CEgSDlapUL1dHzLi5dLsG6AFlw0.png">
SM punt: https://youtu.be/kAA13pakkxI

now you can compare it with BG medium and long punts (30 and 60 hate)
<img src="https://monosnap.com/image/AgYarBYfJXzsZtKT4iyv1wy0aS83mU.png">
medium: https://youtu.be/6zS7G_GqET4
long: https://youtu.be/HmQq7qwTnYw

as you can see SM punts further than BG with long knockback

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 13.07.2019
