### ISSUE TITLE
Quest bug at Drok's Fist Chaptor 12 Greenskin

### ISSUE THREAD

**Issue by TobyYang486** [WarEmu/WarBugs#13433]
when return quest names below (there are 2) won't complete the quest.
"Crushin' Dem All"  &  "Gobbos in da Trees"
Quest location: GREENSKIN Ch12, Black Fire Pass at Drok's fist. (both of them are)
Thanks.

**Comment by Lheana** [comment]
Could you be more precise? As I had no problem turning in the quests.
