### ISSUE TITLE
[WH] snap shot is undefendable

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#13435]
**Screenshots/Videos or archive.org evidences:**
https://www.youtube.com/watch?v=TLQK46vnT3c&feature=youtu.be

p.s: probably WE has the same issue

**Comment by grunbag** [comment]
Not sure what told you i was undefendable

**Comment by Nfkillz** [comment]
i got damaged when using m1

**Comment by grunbag** [comment]
I think the skill use strength and need to be parried not dodged

**Comment by Nfkillz** [comment]
it should be dodged like all throwing dagger/axe abilities. You can see at the end of video how choppa's throwing axe was doged (0:19)

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 20.04.2019

**Comment by sioding** [comment]
Fixed with patch from 27.04.2019
