### ISSUE TITLE
[Tooltip] BO - Youz see me blok' dat'?! shows wrong ICD

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#13432]
As far as I know the ICD has been changed to 10 sec on RoR, as stated in the [wiki](https://wiki.returnofreckoning.com/index.php/Morale_Pumps_%26_Morale_Drains)

![ysmbd](https://user-images.githubusercontent.com/40274248/53251350-b4685a00-36bc-11e9-9c8e-f925c88c683f.jpg)

**Comment by grunbag** [comment]
Fixed at Next Patch

**Comment by sioding** [comment]
Fixed with patch from 02.03.2019
