### ISSUE TITLE
Didnt get contribution after zone lock

### ISSUE THREAD

**Issue by Cypena** [WarEmu/WarBugs#13441]
Hi

So i spent 2 hours in ostland, killing people, ressing friends, healing the bois, capturing bo's and defending the keep. while in a party.
The zone then locks, and i was in a loading screen to hand in my "this is war" quest in talabecland.
My party members then talked about getting renown points and bags.
so im just wondering if this is working as intended?

Thanks in advance
Cypen Destruction.

**Comment by raptrr** [comment]
So, you were in loadingscreen when the zone locked?
Just one time or did it happen another time?
