### ISSUE TITLE
[Quest] Pile it Up! (Mount Bloodhorn, destro) Quest needs rework

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13448]
"Gorkified Statue" has two quest markers and to fulfill this objective you have to click on the left statue, the middle one does not work. Haven't tested the right one.

![pile it up](https://user-images.githubusercontent.com/30193675/53292720-1c0acc00-37c7-11e9-89cd-f4286bee0255.jpg)

**Comment by Lheana** [comment]
Markers will be fixed with next patch.
About the statues, I tested all 3 all it works fine. Note that there is an order in the objectives, maybe you did not complete the previous objectives to gorkify the dwarf statue.

**Comment by sioding** [comment]
Fixed with patch from 02.03.2019
