### ISSUE TITLE
Sorc Keeper Helm

### ISSUE THREAD

**Issue by kayinzel** [WarEmu/WarBugs#13446]
**Expected behavior and actual behavior:**
Helm does not register as the 5th piece of the set for the bonus

**Steps to reproduce the problem:**
to reproduce have a sorc of at least 17 put on the full keeper set with a spare helm of any sorts

**Screenshots/Videos or archive.org evidences:**
2 screenshots showing evidence
![tarakashi_003](https://user-images.githubusercontent.com/12803950/53289788-a6701300-3768-11e9-929b-f3ac3e370fc5.jpg)
![tarakashi_002](https://user-images.githubusercontent.com/12803950/53289789-a6701300-3768-11e9-95ed-16a1f58c3128.jpg)

**Comment by wargrimnir** [comment]
Fixed next patch

**Comment by wargrimnir** [comment]
Oh hey Paul :D

**Comment by sioding** [comment]
Fixed with patch from 02.03.2019
