### ISSUE TITLE
[WL] internal cd of Leonine Frenzy is not 2 sec

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#13442]
**Screenshots/Videos or archive.org evidences:**
<img src="https://monosnap.com/image/lVCkMQ5gHWKf21VvEw3PgJvpU5kJFt.png">
<img src="https://monosnap.com/image/zIsCIMOCkx2M1yaKPIXWGIWTlAz53n.png">

**Comment by grunbag** [comment]
It will not trigger more than once every seconds now .

**Comment by sioding** [comment]
Fixed with patch from 02.03.2019
