### ISSUE TITLE
Gamebreaking bomb spamming

### ISSUE THREAD

**Issue by kalevale123** [WarEmu/WarBugs#13447]
Absolutely gamebreaking bomb spamming bug in the new Scenario Thunder Valley

**Expected behavior and actual behavior:**
Shouldn't be spammable

**Steps to reproduce the problem:**
add a cooldown timer, so  it's not spammable 👍 

**Screenshots/Videos or archive.org evidences:**

Video of issue:
https://www.youtube.com/watch?v=tiSXDvl2D4c&feature=youtu.be

**Comment by Kaelang** [comment]
Video unavailable - please re-open if issue persists.
