### ISSUE TITLE
An enemy skill/attack makes your character invisible

### ISSUE THREAD

**Issue by bugsformount8** [WarEmu/WarBugs#13444]
It just happened now, I got attacked on my SW and my character is now invisible. I'm not able to see my character but others are able to. I'm not sure which attack did it because there was a lot of ppl around attacking. Maybe someone here know what caused it

**Comment by sioding** [comment]
Should be fixed now. I leave this open for some days. Please don't hesitate to give a feedback if its not fixed.

**Comment by sioding** [comment]
fixed with patch from 09.03.2019
