### ISSUE TITLE
Lasting Renown Boost re-applying

### ISSUE THREAD

**Issue by SunsetBlade** [WarEmu/WarBugs#13445]
**Expected behavior and actual behavior:**
From the patch notes:
-Contribution will no longer be removed from other characters on your account on swapping to the underdog side.
-Instead, a 1h 50% XP/RR/INF buff will be applied when swapping sides to the underdog side when Realm Lock is enabled for the faction you were formerly contributing on.
NOTE: Same-faction character switches and swaps when realm lock is NOT enabled will still remove all contribution

**Steps to reproduce the problem:**
(This is what I did).

1. Participate in TM ORVR on Destruction.
2. Switch to Order for 3+ hours, in CW and Fortress (Did not step foot in TM)
3. Enter TM, the new "Lasting Renown Boost" is applied as we had 20% AAO.
4. Leave TM by: 
- taking a scenario pop,
- by book of binding and flying back in,
- by releasing and running back in
5. Buff is reapplied, despite the fact that order seems to have a higher population, but it is kind of close.

**Screenshots/Videos or archive.org evidences:**
![old](https://user-images.githubusercontent.com/10728325/53289775-66109500-3768-11e9-8ade-53c98290ca75.png)
![refreshed](https://user-images.githubusercontent.com/10728325/53289773-66109500-3768-11e9-8e21-e0e17b0f5f56.png)
![again](https://user-images.githubusercontent.com/10728325/53289774-66109500-3768-11e9-8a6f-d40fd200eee1.png)

**Comment by turki79** [comment]
got the buff and in kv when walked below the bridge buff timer refreshed back to 1h again

**Comment by SecretsOTheP** [comment]
Intentional. As long as you are on Order you should get the buff.
