### ISSUE TITLE
Casting time reduction from ES isn't applyed when target is getting closer while casting

### ISSUE THREAD

**Issue by Vrierst** [WarEmu/WarBugs#1344]
When using Expert Skirmisher tactic in a SW character, the time reduction never happens, if your target is more than 20 feet from you, and it gets closer than 20 feet while you are still casting the abbility. In "other servers" (you know what I mean), the 50% casting time reduction happened, if you were still casting the abbility when your target got closer, even when you were more than 20 feet away from your target. In this case, the time reduction was applyed to the rest of the current casting time in the moment when your target got closer enough. Check it, please, although I know it is difficult to develop because of the server lag. Thank you for your kindness and may Isha bless you!

**Comment by grunbag** [comment]
The way you describe is not the way it was working on live neither
