### ISSUE TITLE
[Quest] Skulls and Sorcery (Mount Bloodhorn, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13455]
The quest marker for the objective "Find Pile of Skulls" is missing.

![skulls and sorcery](https://user-images.githubusercontent.com/30193675/53292944-6d1cbf00-37cb-11e9-80a6-05eb076d6a6b.jpg)

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
