### ISSUE TITLE
[Quest] Show dem Wot's Wot (Mount Bloodhorn, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13453]
One or more quest markers are misisng (messed up my notes :P ).

![show dem wots wot](https://user-images.githubusercontent.com/30193675/53292924-0a2b2800-37cb-11e9-8e3e-fd3e2f39683f.jpg)

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
