### ISSUE TITLE
[Quest] Harnessing a Vision (Mount Bloodhorn, destro) Quest needs rework

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13450]
The quest marker for the objective "Find Meat Barrel" appears twice, while "Find Shiny Mushroom" is missing.
"Speak to Wounded Bloody Sun Boy" is not the original wording for the third objective if I remember correctly, it was something like "Collect Pus From a Wounded Bloody Sun Boy".

![harnessing a vision](https://user-images.githubusercontent.com/30193675/53292785-b9b2cb00-37c8-11e9-9dc9-e7f2317f55ac.jpg)

**Comment by Lheana** [comment]
The quest markers will be fixed with next patch, and the quest has been reworked.
Indeed, Wounded Bloody Sun Boyz are meant to give item Orc Ichor, however we can not implement it that way for now, so this objective is unchanged.

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
