### ISSUE TITLE
[Quest] Da Stick's da Fing (2) (Mount Bloodhorn, destro) Quest marker missing+

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13457]
The quest marker for the objective "Rebelin' Orcs" is missing.

![da sticks da fing2](https://user-images.githubusercontent.com/30193675/53292962-bff67680-37cb-11e9-93fa-23cbf91ecfa1.jpg)

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
