### ISSUE TITLE
[Quest] Goblin Grab (Mount Bloodhorn, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13454]
The quest marker for the objective "Slinking Wood Chippas Found" is missing.

![goblin grab](https://user-images.githubusercontent.com/30193675/53292934-4199d480-37cb-11e9-9925-6b754d758745.jpg)

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
