### ISSUE TITLE
[Quest] Down in da Slop (Mount Bloodhorn, destro) Quest needs rework

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13451]
The quest marker for the objective "Dregrot's Teef" is missing". The objective also gets completed at the same time as "Stunty Boot" (by clicking one of the mud piles), I think you had to use both piles in the area for this quest on Live.

![down in a slop](https://user-images.githubusercontent.com/30193675/53292842-98061380-37c9-11e9-8ab1-d66c93a30547.jpg)

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
