### ISSUE TITLE
[Quest] Skulls and Sorcery (2) (Mount Bloodhorn, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13458]
The quest marker for the objective "Find Tobias Mueller" is missing.

![skulls and sorcery2](https://user-images.githubusercontent.com/30193675/53292975-e61c1680-37cb-11e9-9a64-37196d60d77f.jpg)
![skulls and sorcery2_2](https://user-images.githubusercontent.com/30193675/53292976-e61c1680-37cb-11e9-9ebe-39b68c018b08.jpg)

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
