### ISSUE TITLE
[Quest] Stunties an' their Beards (Mount Bloodhorn, destro) Quest marker doubled

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13452]
The quest marker for the objective "Kill Ironmane Thunderer" appears once at the correct position in form of a multi objective marker and once at the Chapter 2 Warcamp, where it shouldn't be.

![stunties an their beards](https://user-images.githubusercontent.com/30193675/53292896-6f324e00-37ca-11e9-88ba-015d6a50ee79.jpg)

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
