### ISSUE TITLE
[Quest] Stupid Dead Stunties (Mount Bloodhorn, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13459]
The quest marker for the objective "Irontoe Ancestors" is missing.

![stupid dead stunties](https://user-images.githubusercontent.com/30193675/53292995-0c41b680-37cc-11e9-819e-e4815a4948f8.jpg)

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
