### ISSUE TITLE
[Quest] Da Stick's da Fing (Mount Bloodhorn, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13456]
The quest marker for the objective "Mine Bat Killed" is missing.

![da sticks da fing](https://user-images.githubusercontent.com/30193675/53292956-9a696d00-37cb-11e9-89fd-199f27579d40.jpg)

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
