### ISSUE TITLE
Slayer weapon bug, 2H + 1H weapon at the same time.

### ISSUE THREAD

**Issue by 4cobbi** [WarEmu/WarBugs#1346]
Please fix, slayers are hitting way too hard. Please see images attached.

![bug](https://cloud.githubusercontent.com/assets/14143395/9749057/6e838e2c-563e-11e5-8a99-2123d0334085.jpg)
![bug2](https://cloud.githubusercontent.com/assets/14143395/9749063/72183bfa-563e-11e5-931f-94bc80e0ba93.jpg)

**Comment by Silentguard** [comment]
Looks my slayer still distrubing ppl even if dont play him.

**Comment by 4cobbi** [comment]
If it were indeed your slayer you were playing today and have seen you playing SC'S as well. SO BS.

**Comment by pootato** [comment]
@Silentguard If you're not playing it, then I guess you wouldn't mind telling us how you did it so they can fix?

**Comment by Reggaewaldo** [comment]
Tried to reproduce but did not work. Please get back if the problem is still present.

Closing.
