### ISSUE TITLE
[Quest] Smashin' Heads (Mount Bloodhorn, destro) Quest needs rework

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13462]
The quest marker for the objective "Speak to Grozzit" is missing. Also, you're supposed to kill two named squigs, but there is only one.

![smashin heads](https://user-images.githubusercontent.com/30193675/53293042-e49f1e00-37cc-11e9-97d2-e71e9b7af5ab.jpg)
![smashin heads1_2](https://user-images.githubusercontent.com/30193675/53293043-e49f1e00-37cc-11e9-93ad-e9ab3f8fd7a5.jpg)

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
