### ISSUE TITLE
[Quest] No One Says No to Grumlock (Mount Bloodhorn, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13461]
The quest marker for the objective "Scartusk's Bruisas" is missing.

![no one says no to grumlok](https://user-images.githubusercontent.com/30193675/53293015-6b9fc680-37cc-11e9-9929-347c864c2444.jpg)

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
