### ISSUE TITLE
[Weapon] 1h appearance on 2h weapon

### ISSUE THREAD

**Issue by elk76** [WarEmu/WarBugs#13468]
I know that this weapon was fixed recently in the last Patches (issue #13311)
but the 1h appearence still remained
![eyvind_073](https://user-images.githubusercontent.com/46483570/53296210-e556a500-380a-11e9-98f8-9e5c70879751.jpg)

**Comment by kyranria** [comment]
it should be a 1h and not a 2h so it's normal about the appearance.

**Comment by elk76** [comment]
time ago it was 1h, but with stats of 2h. 
So from last patch, it was fixed and now it is 2h but with 1h appearance

**Comment by wargrimnir** [comment]
This appears to be set as a 1h weapon again.
