### ISSUE TITLE
The Maw Fortress is bugged. No barrier and no ram at entrance

### ISSUE THREAD

**Issue by bugsformount8** [WarEmu/WarBugs#13466]
Unlocked The Maw Fortress not too long ago and there is no barrier and no ram

**Comment by sioding** [comment]
It seems your weren´t enough ppl to unlock the maw. The campaign only goes forward if there are enough on the open lake. I guess another zone was open - so the maw didn´t open for you. Thats not really a bug cause the campaign is exactly working like that. I will ask Nath if its intended - especially with the forts. Cause tbh. If there aren't enough in the lake you will never kill the fort lord.

**Comment by bugsformount8** [comment]
Okay. There were about 40+ Destro and 60+ Order when we unlocked The Maw. Sorry no screenshot of zonepop

**Comment by Natherul** [comment]
If I get it right then yes its intended. 

Same unlocking mechanics is in play for forts, so if there is too few players to keep an additional zone open and you lock say CW when MOM is also open then CW will lock and there will be no maw fight.
