### ISSUE TITLE
"Holmsteinn Revisited" (PQ) and "Deadly Task" (Quest) are broken.

### ISSUE THREAD

**Issue by RasCaelestis** [WarEmu/WarBugs#13479]
I'm trying to do the Chaos Chapter 2 quest "Deadly Task" and the correct NPCs, Nordland Scouts, aren't spawning. 

This quest overlaps with the PQ "Holmsteinn Revisited" and the "Holmsteinn Supplies" you need to interact with are also missing. 

I just did these quests yesterday on another character and they were working fine. Not sure what caused the glitch, but it seems to be a pretty recent issue. I think the NPCs and items disappear on the second stage of the PQ, but it's currently stuck on Stage 1, so it's impossible to continue or move on. 

![image](https://user-images.githubusercontent.com/47956519/53308853-67c67f80-3872-11e9-9d4e-dc14600dee27.png)

**Comment by sioding** [comment]
This is a known issue we can not fix atm. You have to wait for a server restart.
