### ISSUE TITLE
cannot salvage items no choice too!

### ISSUE THREAD

**Issue by creator0000** [WarEmu/WarBugs#13473]
![belgaras_000](https://user-images.githubusercontent.com/47520653/53301403-096cb300-3818-11e9-8e1f-b2fcf2f4916e.jpg)
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

![belgaras_001](https://user-images.githubusercontent.com/47520653/53301405-0c67a380-3818-11e9-850a-fba2ce4b03c4.jpg)
![belgaras_003](https://user-images.githubusercontent.com/47520653/53301409-0ffb2a80-3818-11e9-9aa3-487f26a037e4.jpg)

**Comment by Moragor** [comment]
I had a similar problem with apothecary, running the launcher a few more times to download more patches fixed it. Salvaging is also working for me.

**Comment by wargrimnir** [comment]
These items are flagged as salvageable.
