### ISSUE TITLE
Treachery of Kin quest in charce giving crazy rewards

### ISSUE THREAD

**Issue by bobeer86** [WarEmu/WarBugs#1347]
Treachery of Kin - dark elf t1, chrace: quest requires you to click on corpses of 5 dead arkaneth soldiers, but instead of granting a quest item it gives you t2 staff that looks like its scenario weapon - screenshots attached. It does it 5 times, so after you finish quest you have 5 of those. They cant be used since they require being of empire race, but still a surprise....

![1](https://cloud.githubusercontent.com/assets/14189089/9749809/a09930d6-565e-11e5-864e-7a4aad516059.PNG)
![2](https://cloud.githubusercontent.com/assets/14189089/9749811/a0a31a06-565e-11e5-909c-fd2f0d83e0b1.PNG)
![3](https://cloud.githubusercontent.com/assets/14189089/9749812/a0a441ce-565e-11e5-902a-314a2c5b7983.PNG)
![4](https://cloud.githubusercontent.com/assets/14189089/9749810/a0a113aa-565e-11e5-8ff2-103e70fc457a.PNG)

**Comment by Tyramissoux** [comment]
Oh from there I got the items... on the day, these weapons were introduced into the game, I had several Empire SC weapons in my quest backpack. Two hammers, five swords. Already reported that I posess them on my Disciple. 
Always wondered where they came from.

**Comment by bobeer86** [comment]
well, I sold mine, kept 1 piece in case item id or something is needed....guess I'm 60s richer due to bug ;)

**Comment by Tyramissoux** [comment]
Well, you can still salvage them buuuuuut it would be bugusing.

**Comment by Tyramissoux** [comment]
Tested this a bit. If you salvage those weapons, the counter for arkaneth crests goes down. Did this to figure out if you can salvage magic crit - nope, doesn't work. :/

**Comment by Reggaewaldo** [comment]
This has been fixed in the DB and the staff should no longer appear after next update.

This can now be closed.

**Comment by dfumagalli** [comment]
Hello,

I don't know if the "next update" has been applied yet. Because not only I keep getting these blue items, but even if the quest is completed, the Kilraena Dreamlasher NPC won't take it.

**Comment by Evildoor** [comment]
Amount of resurfacing bugs with quests, Palace Guards, etc, which were marked as resolved makes me suspect that somewhere an old DB commit was applied by mistake...

**Comment by Meralors** [comment]
Should be fixed for real now! Live next update ;)
