### ISSUE TITLE
Butcher's Pass entrance.

### ISSUE THREAD

**Issue by ilferro** [WarEmu/WarBugs#13471]
Hello.
I would have been able to enter Butcher's Pass through pve route, skipping the portal. I can prove with some screenshots.
![faber_415](https://user-images.githubusercontent.com/16581052/53300727-4aca8600-384b-11e9-993f-88afaaf4985d.jpg)
![faber_417](https://user-images.githubusercontent.com/16581052/53300728-4b631c80-384b-11e9-8d9e-a1087d4177e5.jpg)
![faber_418](https://user-images.githubusercontent.com/16581052/53300729-4b631c80-384b-11e9-8458-bdcf144321e9.jpg)
I hope I have been helpful and thanks for your hard work.

**Comment by Kabucoror** [comment]
This should have been fixed with patch from 23.02.19

**Comment by XmatXergon** [comment]
Yes, its still possible.

**Comment by ilferro** [comment]
But is intended?

Il lun 25 feb 2019, 13:28 Matthew Mateusz <notifications@github.com> ha
scritto:

**Comment by Kabucoror** [comment]
missed the second way to get there. fixed with next patch

**Comment by ilferro** [comment]
I'm glad that I could help.

Il lun 25 feb 2019, 20:30 Kabucoror <notifications@github.com> ha scritto:

**Comment by sioding** [comment]
Fixed with patch from 02.03.2019
