### ISSUE TITLE
Im turning invisible during battle

### ISSUE THREAD

**Issue by Malykhai** [WarEmu/WarBugs#13475]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
I am not supposed to turn invisible during battle. But I'm turning invisible. Noone else is invisible to me.

**Steps to reproduce the problem:**
Not sure if a skill or spell is causing this, but it only happens during battle

**Screenshots/Videos or archive.org evidences:**

**Comment by Abodam** [comment]
Can be replicated on Magus by exploding Deamon pet - Skill - Instability.
Must be in combat, not 100% sadly, probably needs more conditions.
Video: [](https://streamable.com/ekcn3)

**Comment by grunbag** [comment]
Fixed
