### ISSUE TITLE
[Item] Vanquisher Mantle

### ISSUE THREAD

**Issue by theHalta** [WarEmu/WarBugs#13478]
**Expected behavior and actual behavior:**
Vanquisher Mantle is missing Willpower, while the rest of the set has it.

**Screenshots/Videos or archive.org evidences:**
![image](https://user-images.githubusercontent.com/16519808/53306358-e502ec00-3894-11e9-932b-973e96cd94c4.png)

**Comment by wargrimnir** [comment]
These are intended to have toughness.
