### ISSUE TITLE
Issue at Chaos starting zone 

### ISSUE THREAD

**Issue by newchosen** [WarEmu/WarBugs#13474]
Hi there,

everytime i try to walk accros the bridge to go to Thorshafen and attack a mob i get kicked out of the game immediatly. I am trying out the game and would love to play so i would be incredibly thankfull for any help. :)

**Comment by Moragor** [comment]
Your audio archive is likely corrupted, get a working one from here and replace the one in your game folder.
https://returnofreckoning.com/forum/viewtopic.php?p=326158#p326158

**Comment by newchosen** [comment]
thank you i will try :)

**Comment by sioding** [comment]
Answer given - close
