### ISSUE TITLE
Book of Binding

### ISSUE THREAD

**Issue by Sensitey** [WarEmu/WarBugs#13482]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Book of Binding's cooldown is supposed to prevent players from teleporting for 60 minutes after it is used. But, it is possible to bypass the cooldown by simply clicking it even though the icon shows the cooldown timer.

**Steps to reproduce the problem:**

1- Use book of binding.
2- Use flight master to teleport to another location.
3- Use book of binding while it has cooldown.
4- Repeat.

Personal experience: My book of binding is set to altdorf. I can not use book of binding in altdorf after teleporting to altdorf via book of binding. So, apart from the cooldown timer, usage of flight master may also have something to do with this bug.

**Screenshots/Videos or archive.org evidences:**

![screenshot 7](https://user-images.githubusercontent.com/47965287/53318529-6900a800-3884-11e9-9fb9-a385b957845f.png)

**Comment by Jonees123** [comment]
Every cooldown in the game resets on teleports, this is nothing new.
