### ISSUE TITLE
oil damage too high

### ISSUE THREAD

**Issue by acidicrain** [WarEmu/WarBugs#13487]
oil damage in etaane too high, 
posted pic on discord, from acidic shwoing fluf taking 1,5k damage with 1.5k mitigated

**Comment by acidicrain** [comment]
Normal damage has been around 800-900 with 800-900 mitigated, so oil was doing around double damage

**Comment by acidicrain** [comment]
https://cdn.discordapp.com/attachments/329292495336767488/549717160549941278/Fluf_000.jpg

**Comment by sioding** [comment]
So you said "normal damage" - any proof for this? Since there is nothing in the patchnotes related to oil damage - i guess there is no change made for it.

**Comment by CrimsonFenris** [comment]
Usual damage is around 1500 per tick total, nothing wrong about that...
Oil is meant to be dissuasive, goal complete most of the time ;)

**Comment by acidicrain** [comment]
here is oil damage on soc from a week ago
https://youtu.be/WyCI4pP_xgM

yopu can see if you focus on soc damage hitting for 980,  this is a soc with low toughness vs fluf BO Deftard, the mitigation on soc is about 500-600, so total damage output from oil comming at 1.5k total on initial video its comming in at 3k

**Comment by acidicrain** [comment]
just to calrify the issue. here is a video from last night, starts with keep in etiane where damage from oil around 800 then with same toon,  wb, group (i belive) damage 1.5k around.
https://youtu.be/uf6hf9hHd8Y

**Comment by pjz** [comment]
I can verify there's a large variance in oil damage - Iast night some oil hit me for 750ish per tick and some hit me for 1850 per.  I _suspect_ it was due to the rr/skill of the oil tipper, but of course cannot confirm.

**Comment by Natherul** [comment]
Closing this ticket, it has been addressed some time ago.
