### ISSUE TITLE
[Altdorf] Broken middle gate.

### ISSUE THREAD

**Issue by XmatXergon** [WarEmu/WarBugs#13484]
**Expected behavior and actual behavior:**
You should be able to click on gate to open it.
2nd Middle Gate doesn't work/not clickable.

**Steps to reproduce the problem:**
Altdorf middle gate leading to WarQuarters/Fortress.

**Screenshots/Videos or archive.org evidences:**
![image](https://user-images.githubusercontent.com/37849311/53335289-63927480-38fb-11e9-8c88-8a399bc2a568.png)
![image](https://user-images.githubusercontent.com/37849311/53335517-f3382300-38fb-11e9-8481-630774565979.png)
![image](https://user-images.githubusercontent.com/37849311/53335530-fcc18b00-38fb-11e9-9ac1-6aeab3dac6b4.png)

**Comment by Kabucoror** [comment]
works fine for me

**Comment by Scophis** [comment]
It seems to be broken from time to time, but no clue under what circumstances. In most cases I doesn't work when you're coming from the North.

 ![drengur_020](https://user-images.githubusercontent.com/40274248/53839559-29c70b00-3f98-11e9-9e32-18d96129cc6f.jpg)
_Can't interact with the gate_

**Comment by Kabucoror** [comment]
try it again after next patch, pls

**Comment by XmatXergon** [comment]
https://youtu.be/oLOxMbdsPOo

**Comment by Kabucoror** [comment]
It's ok now
