### ISSUE TITLE
Swordmaster Dmgs/Mitigation

### ISSUE THREAD

**Issue by fagio1989** [WarEmu/WarBugs#13486]
Hello everyone, 
since the last time SM was bugged and you fixed it something has changed in this character damages.

**Expected behavior and actual behavior:**
With 4500~ armor, 195 Toughness and 24,5% Spirit Red Damages I expect to mitigate something.

Actually the mitigation of some skills is broken, seems not effected by toughness or resist or both in some cases. 
(Linked screen and video below)

Screen:
![sm dmgs](https://user-images.githubusercontent.com/46511136/53355836-40cb8480-392a-11e9-995d-03bb29520598.jpg)
Video:
https://streamable.com/26kv5

**Comment by SecretsOTheP** [comment]
Armor doesn't protect against spiritual damage. 195 toughness is why you're being hit so hard. Get more toughness and you will mitigate more damage. Keep in mind their primary stat adds to the damage and your mitigation from spiritual is not a flat amount reduced.

**Comment by fagio1989** [comment]
*Disclaimer* Nothing against this person, I just never saw these damages by the SM before the latest patches, so that's why I ask.

Imagine the same damages made with a 2H sword, even Dazzling Blow (snare skill on the chosen) is doing 600dmgs with 1h non crit

**Comment by wargrimnir** [comment]
This isn't a discussion platform. Confirm you actually have a bug before you post it here. If you're not sure, find out first, whether it's through testing or working with someone more skilled at a class than yourself.
