### ISSUE TITLE
Invader medallion

### ISSUE THREAD

**Issue by Schjellerup** [WarEmu/WarBugs#13485]
i was not in the fortress zone ( lvl 33 was leveling) and i got 4 medalions when destro tog the fortress , i think thats is a bug as i was not in the fighting for fortress,

Thanks for bringing Warhammer online to live again , a big RoR fan :)

Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment]
Fixed with patch from 02.03.2019
