### ISSUE TITLE
How do I get back the green balls on the map , so I know where my wb is at ?

### ISSUE THREAD

**Issue by lenideni1** [WarEmu/WarBugs#13497]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by lenideni1** [comment]
How do I get back the green balls on the map? so I know where my warband is at. >

**Comment by sioding** [comment]
Sorry but the bugtracker isn't a support tool. Please try our ingame /advice channel or the #advice channel in our discord.
