### ISSUE TITLE
[Epic Quest] T2 DE 

### ISSUE THREAD

**Issue by Kroatan** [WarEmu/WarBugs#13492]
T2 Epic Quest DE 
step 12 Shadowland no need of monsters
~7600 ~61000

**Comment by Lheana** [comment]
I don't understand your report sorry.

**Comment by sioding** [comment]
me too. Can you please bring in more information to your report? Otherwise no dev is able to take care of it. Thanks.

**Comment by Tallanvor1** [comment]
Griffon gate pq still isnt working

**Comment by Lheana** [comment]
Duplicate of/related to #10862
