### ISSUE TITLE
 Sorcerer Frozen and Chill  Spells  Bugs

### ISSUE THREAD

**Issue by MrShampi** [WarEmu/WarBugs#13496]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Demonic COld and Frozen touch applied to allu

This buffs was not applied to my party members, so  my buffing jobs was not working.

**Steps to reproduce the problem:**
Casting the Spell testing if the Buffs are appearing/working

**Screenshots/Videos or archive.org evidences:**
Sending the evidence on a  highlight of my replay video:
https://www.twitch.tv/videos/387254833

**Comment by sioding** [comment]
Let me guess. You wasn't flagged but your group members were or vice versa?

**Comment by MrShampi** [comment]
none of us we were flafgged we were doing PvE  so no need to be flagged to RvR

**Comment by sioding** [comment]
ok - i will try to reproduce it.

**Comment by sioding** [comment]
Tried and i can not reproduce it. Its fine on my side. Can anyone give any hints to reproduce it?

**Comment by sioding** [comment]
No answer since 27 days. close
