### ISSUE TITLE
deathbringer, quest

### ISSUE THREAD

**Issue by bobeer86** [WarEmu/WarBugs#1349]
deathbringer, chrace, dark elf t1 - quest sends you to kill npc galdreth lonetree and pick up midnight crystal hes defending, mob is in tor achare, and kill registers properly, but there is no midnight crystal to loot.

**Comment by Reggaewaldo** [comment]
The change has now been added to the DB so that the crystal is dropped of the mob. The change will carry over with the next hotfix.

Closing.
