### ISSUE TITLE
Quest : Tipping the Balance : Helglaive forces not tagged for quest

### ISSUE THREAD

**Issue by Jerloldrartolf** [WarEmu/WarBugs#13495]
**Expected behavior and actual behavior:**
Killing any mob with description like 'helglaive%' in quest area north of Chapter 21 who are part of quest 'Tipping the Balance' should trigger increase in forces slain.
Increase only occurs when slaying Deathlance.

**Steps to reproduce the problem:**
Pick up quest : Tipping the Balance
Go to Quest area North of high elf chapter 21 : Drakestar's Lament.
Kill Helglaive Bloodshade or Helglaive Punisher
Take note that Kill count has not increased.

**Comment by sioding** [comment]
Have you been in group as you did the quest?

**Comment by Jerloldrartolf** [comment]
I was solo in this quest. Not in a group or WB.

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 09.03.2019
