### ISSUE TITLE
[Engineer] Self-destruct ability (knockdown) is undefendable

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#13491]
<img src="https://monosnap.com/image/a1FalbBAylNb6rfgfb8AXU4gMkd1EY.png">

**Comment by grunbag** [comment]
Not sure what I should look . I see self destruct KD icon but dunno what makes it undefendable

**Comment by kyranria** [comment]
u should look the moral 1 100% dodge

**Comment by Nfkillz** [comment]
sorry that i didnt comment the screenshot. WE was knocked in morale1 (100% parry/dodge)

**Comment by grunbag** [comment]
Does CC can be dodge/disrupt/parry or ln’y Damage component ?

**Comment by Nfkillz** [comment]
idont know exactly but i think it should be dodged

**Comment by grunbag** [comment]
checked client setting, it always been underfendable even on live

**Comment by grunbag** [comment]
fixed with next patch
