### ISSUE TITLE
Don`t Hit Me!

### ISSUE THREAD

**Issue by rutssS** [WarEmu/WarBugs#13493]
Squid Herder skill

While trying to use skill "Dont`t Hit me!" in squid armor it says "NOT USABLE WHILE INSIDE YOUR SQUID ARMOR" while still doing damage and going on cooldown while in squid armor.

**Comment by grunbag** [comment]
Thé ability never been usable in SA

**Comment by grunbag** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 13.07.2019
