### ISSUE TITLE
Renown rank reset to 72 at fortress

### ISSUE THREAD

**Issue by IxanderousI** [WarEmu/WarBugs#13498]
Needs investigation my character Bashgutz was already renown rank 72 and upon level up it reset to 72, this happened when i was at a fort defence today at fells landing so could be related.

**Comment by sioding** [comment]
Sorry bit the discord is not a personal support channel. If you face such an issue you felt is happening - please create an appeal while clicking the quition mark inside the game.

**Comment by IxanderousI** [comment]
I don't see it as a personal support channel i am reporting a bug, anyway i submitted an appeal now, hopefully gets fixed cause i don't want it to happen again to me.
