### ISSUE TITLE
[Quest] Bloodforge quest tooltip

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13504]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Tooltip for the quest should match the discreption on Tome of Knowledge. There is also wrong mention of 
"Valaska Recoverd"

**Steps to reproduce the problem:**

Take the quest and check the tooltip

**Screenshots/Videos or archive.org evidences:**
![bjoorn_004](https://user-images.githubusercontent.com/18528095/53599245-07ec1380-3ba7-11e9-81ae-6abcd7f8ce4e.jpg)

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
