### ISSUE TITLE
Slayer base aoe skills range seems bugged.

### ISSUE THREAD

**Issue by rekkir** [WarEmu/WarBugs#13508]
I expect this to be a frontal cone ability, and to reach the lengths described on the tooltips.

**Steps to reproduce the problem:**
Flurry w accuracy had ridiculous horizontal range and onslaught is even worse. They hit targets way out of my assumed range. Is this how cones work now?

**Screenshots/Videos or archive.org evidences:**

https://youtu.be/PxHDufFjtPs?t=18

**Comment by grunbag** [comment]
Next patch Aoe will be fixed
