### ISSUE TITLE
Wrong DPS value on Shrouded Hatchet

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#13502]
**Expected behavior and actual behavior:**

Shrouded Hatchet has wrong DPS value (1h value instead of 2h value) and it says it can be used in off hand.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

![falinieth_000](https://user-images.githubusercontent.com/7400/53575554-166c0800-3b72-11e9-8230-ef711c6d2d0a.jpg)

**Comment by wargrimnir** [comment]
Stats corrected next patch

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
