### ISSUE TITLE
[mara] ferocious assoult [ability]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#13501]
skill should buff 190 to BOTH toughness and str as per tooltip but it only buff tough for 190 while it buff str for 110 instead, 

cheked on getstat too it increase only 110 so it's not visual as you can see from char sheet with no buff + getstat with buff (867 +110 = 977)

![draznicht_003](https://user-images.githubusercontent.com/7527415/53564572-8c16aa80-3b57-11e9-8b19-d2e7bca4053f.jpg)
![draznicht_004](https://user-images.githubusercontent.com/7527415/53564571-8c16aa80-3b57-11e9-8dc2-9ea94249fcfe.jpg)

**Comment by sioding** [comment]
And you are sure you haven't used a strength buff potion? i'm quite sure i see it in your screenshots. It will never stacks with a buff potion.

**Comment by Tesq** [comment]
you right, my bad ; it was late when i looked at this
