### ISSUE TITLE
[NPC] Lilja Shadowdrinker

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#13503]
Very minor issue here, but figured it was worth noting. The NPC Lilja Shadowdrinker has what looks like missing text/words when you try to talk to him. He's the Chaos "Kill Collector" NPC in Trollhaugen in Troll Country. 

![image](https://user-images.githubusercontent.com/47956519/53590950-e831fc80-3b60-11e9-82dc-8065328d4dbe.png)

**Comment by Lheana** [comment]
This should have been fixed with the patch of today.
