### ISSUE TITLE
[Quest] spirits for the raven god

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13505]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Tooltip of the quest does not match the discription in Tome of Knowledge

**Steps to reproduce the problem:**

Take the quest and check the tooltip

**Screenshots/Videos or archive.org evidences:**
![bjoorn_005](https://user-images.githubusercontent.com/18528095/53599487-93fe3b00-3ba7-11e9-986b-49c183c6cbfd.jpg)

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
