### ISSUE TITLE
[Slayer] Backstyle Spine Crusher shows as always enabled

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#13500]
**Expected behavior and actual behavior:**
The Slayer backstyle Spine Crusher should be greyed out/disabled when not behind an enemy. Currently the ability shows as always active/possible to use. However is does not fire off when not behind someone. This is highly confusing during fights as nothing happens when you press the button.

**Steps to reproduce the problem:**
Just log onto a Slayer

**Screenshots/Videos or archive.org evidences:**
![cimbo_017](https://user-images.githubusercontent.com/16117730/53511566-021c0280-3ac1-11e9-901a-dc87fcbdd7f0.jpg)

**Comment by grunbag** [comment]
It will need a client change

**Comment by Neil0r** [comment]
same problem. the mirror skill on choppa works well.

**Comment by grunbag** [comment]
Fixed
