### ISSUE TITLE
[Quest] The Raven God's Tithe (Ostland, destro) Kill quest not counting kills

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13512]
The counter is not rising even though I made many kills in Ostland.
The other kill quest for 50 Dwarfs/Elfs/Humies from the Ostland warcamp was working normally, so I definitely made valid kills.

![moragor_000](https://user-images.githubusercontent.com/30193675/53669023-f9b8f880-3c75-11e9-8c0b-684a04fcd14c.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 09.03.2019
