### ISSUE TITLE
[BB] 50% heal debuff after defeating first boss

### ISSUE THREAD

**Issue by xaraxdestr** [WarEmu/WarBugs#13513]
after defeating the first boss in BB we got an "invisible" 50% heal debuff
You have to relog to get rid of it

happens the last time i did this ini too.

And now we wiped on endboss and the same issue again.

Only relog helps

**Comment by xaraxdestr** [comment]
no we killed the boss after relog, then i have the debuff again

after relog and before boss kill i heal for 388 (Khaine's vigor) 
after boss kill i heal for 194 (khaine's vigor)

**Comment by panodill** [comment]
i made report on this 3 weeks ago, nothing been done yet. Its the nurglings debuffing you and it does not go away.

**Comment by grunbag** [comment]
It should be disabled , well I’ll look into it again

**Comment by grunbag** [comment]
Fixed at next patch

**Comment by grunbag** [comment]
Fixed at next patch

**Comment by sioding** [comment]
fixed with patch from 09.03.2019
