### ISSUE TITLE
[Gates of Ekrund] Getting Stuck in Order Warcamp

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#13511]
**Expected behavior and actual behavior:**
Expected behavior: Not getting stuck in a fucking camping fire when falling out of the warcamp  in Gates of Ekrund
Actual behavior: Getting stuck in a fucking camping fire when falling out of the warcamp in Gates of Ekrund

**Steps to reproduce the problem:**
Jump out of the warcamp in gates on ekrund

**Screenshots/Videos or archive.org evidences:**
![cimbia_014](https://user-images.githubusercontent.com/16117730/53656456-91f1b600-3c53-11e9-841b-2a63e7119359.jpg)

**Comment by wargrimnir** [comment]
How about you don't jump into the fucking campfire, and don't spam our fucking bugtracker with your fucking foul language.

User error, not a bug.

**Comment by Cimbas** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=15&t=21019#p231821

**Comment by wargrimnir** [comment]
You got stuck on a campfire that's out in the open. We're looking for things you get stuck on that aren't obvious or make no sense.
