### ISSUE TITLE
[Public Quest] - Badlands >>Revoltin' Gobbos<<

### ISSUE THREAD

**Issue by Charlsetta** [WarEmu/WarBugs#13514]
The questline seems to get to final stage and spawn loot before stage one is completed in the UI. Then once completed the UI doesnt reset, and i am able to loot 2x boxes in the time for 1 reset. I hope this made sence

**Comment by Charlsetta** [comment]
The questline seems to get to final stage and spawn loot before stage one is completed in the UI. Then once completed the UI doesnt reset, and i am able to loot 2x boxes in the time for 1 reset. I hope this made sence

**Comment by Charlsetta** [comment]
Not that im complaining - It's wonderful 👍

**Comment by Charlsetta** [comment]
![ror bug](https://user-images.githubusercontent.com/48141245/53673672-55d94800-3c89-11e9-9fdf-6dae285ed1d5.png)

**Comment by Kaelang** [comment]
Upon testing, Stage 2 only triggered once all 125 Goblins were killed correctly as per the tracker. Please re-open issue if you are able to replicate on a live environment as it looks like this is working as intended.
