### ISSUE TITLE
T3 scenario weapon on WP

### ISSUE THREAD

**Issue by Lestrigon78** [WarEmu/WarBugs#13510]
Good day!
Today, after buying a T3 book on the WP at level 29 for scenario medals, I discovered a problem: the proc does not work with this item. Namely: there is no recovery of fury.
Thus, to use this item is not possible.
I had to return to the reward for the epic quest, which works as it should.
Please pay attention to this problem.

https://pastenow.ru/68f05988b31adca644bf0eb7efbbe2e2
https://pastenow.ru/f15a986068b7bff738fad003eb834bb6

**Comment by wargrimnir** [comment]
Blue books should only Regen 6 anyway. Will check on it.

**Comment by dalen** [comment]
@wargrimnir all the higher tier (RR29+) scen books are blue but have +8RF/s.

But I'm pretty sure this specific item works for me.

**Comment by sioding** [comment]
Switching the tome doesn't help - relog doesn't help. You have to move the item into your backpack and back on the character. That mean really: No switching. RF regen stops when you do this. a know issue we can not fix atm. can you please test it?

**Comment by sioding** [comment]
So not a job for warg - this is a sourcecode job - but i leave this on warg since he wanna check something

**Comment by wargrimnir** [comment]
This may be fixed, please confirm after the patch.

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
