### ISSUE TITLE
[WP/DoK] AoE is now line-AoE instead of conical-AoE

### ISSUE THREAD

**Issue by SnoxxBT** [WarEmu/WarBugs#13520]
related to Patch from 02/03/2019

Smite on WP and Essence Lash on DoK are Line-AoE now.
That was never the case on live servers, and the vfx clearly shows a conical-AoE.
Both should be changed to conical-AoE.

**Comment by grunbag** [comment]
fixed at next patch

**Comment by sioding** [comment]
fixed with patch from 09.03.2019
