### ISSUE TITLE
Invader set bonus 6 spelling mistake

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#13529]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

it says 500 Heath Point should be Changed to  Health and not Heath

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**
![image](https://user-images.githubusercontent.com/42385505/53688393-4a9f1e80-3d54-11e9-8a3d-6a03a5afd4b6.png)

**Comment by grunbag** [comment]
Fixed on next patch

**Comment by sioding** [comment]
fixed with patch from 09.03.2019
