### ISSUE TITLE
[Tactic] Wild Healing

### ISSUE THREAD

**Issue by qualteia** [WarEmu/WarBugs#13521]
**Expected behavior and actual behavior:**
EB: Tactic should proc on crit heal, and reduce AP costs by amount listed in the tooltip (50%)
AB: Tactic procs on crit heal, and AP costs are NOT reduced at all

**Steps to reproduce the problem:**
Cast crit heal, verify tactic has procd, watch AP amounts and verify the amount of AP for an ability (in the GIF I showed Lambent Aura which is 30AP) and confirm that the AP consumed is 100%, instead of 50%.

**Screenshots/Videos or archive.org evidences:**
https://i.imgur.com/uhHdIJ7.gifv

**Comment by grunbag** [comment]
Just tested on dev . The abiltiy is working as intended , reducing any heal ability AP cost by 50% for 10 seconds
