### ISSUE TITLE
Magus knockdown not working

### ISSUE THREAD

**Issue by Rokrag** [WarEmu/WarBugs#13525]
magus knockdown instability does damage but doesn't knockdown, I checked engi and it works fine

**Comment by grunbag** [comment]
You mean animation or targets are not disabled ?

**Comment by Rokrag** [comment]
they aren't being disabled

**Comment by grunbag** [comment]
Fixed at next patch

**Comment by sioding** [comment]
fixed with patch from 09.03.2019
