### ISSUE TITLE
[keep quest] - Securing the front

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#13531]
**Expected behavior and actual behavior:**
expected - keep rvr quests should accept whichever keep is the enemy keep as option (either)
Quests states to capture any keep but the quest check asks to capture Ardor of Light.  We took Pillars of Remembrance and the quest didn't complete.

**Steps to reproduce the problem:**
accept quest and capture enemy keep.

**Screenshots/Videos or archive.org evidences:**

**Comment by wargrimnir** [comment]
I don't see any issue with the construction of this quest. It's flagged to give credit for both Arbor of Light and Pillars of Remembrance.
