### ISSUE TITLE
The Maw barrier skip

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#13534]
**Expected behavior and actual behavior:**

In the maw you can actually get in using a bit of semi-advanced mountain climbing. Starting around 48,1 in Chaos wastes, just west of where a mob is standing on the cliffs. Then walk on top of the mountain ridge around the north of the menagerie and drop down in fortress.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by Kabucoror** [comment]
should be fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 09.03.2019
