### ISSUE TITLE
Barrier skip in the Maw by dying in the menagerie

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#13535]
**Expected behavior and actual behavior:**

If you die in the menagerie in the maw zone by for example jumping off a cliff you will respawn in the actual fortress zone.

**Steps to reproduce the problem:**

While there is an active siege in the maw, walk to the menagerie, jump off a cliff and die, respawn.

**Screenshots/Videos or archive.org evidences:**

**Comment by Kabucoror** [comment]
If you enter a fort not through the portal, you will get ported out. So this is not longer an issue.
