### ISSUE TITLE
Guild news keep getting cleared

### ISSUE THREAD

**Issue by Ponzac** [WarEmu/WarBugs#13533]
This is a vital part of the guild as it shows activity and hard to keep or invite new players to keep the guild running if they think its inactive. It worked just fine untill the patch that cleared old guild news.

**Expected behavior:** Show the happenings in guild

**actual behavior:** Shows for 30mins and then gone

**Steps to reproduce the problem:** Level up a character renown or rank, invite someone to guild, kick someone. wait 30mins and its cleared.

**Screenshots/Videos or archive.org evidences:**

![image](https://user-images.githubusercontent.com/14014058/53695515-d64c9580-3dbc-11e9-84d0-f9dfc6f72d0d.png)

**Comment by MaxHayman** [comment]
Fixed next patch.

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019

**Comment by sioding** [comment]
The guild news are back - thanks - but the latest news needs shown on the windows - not the first.

![image](https://user-images.githubusercontent.com/18517842/54869818-3cb24b80-4d9e-11e9-8ad1-bb79b00bb4f7.png)

![image](https://user-images.githubusercontent.com/18517842/54869824-4b006780-4d9e-11e9-9bfe-5bd696ceae88.png)

**Comment by MaxHayman** [comment]
Fix pending

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
