### ISSUE TITLE
Fortress Jail

### ISSUE THREAD

**Issue by Furrikson** [WarEmu/WarBugs#13532]
Hello,

In Fell Landing prison order perma hits us with aoe engi and bw spells. I die 2 times in the jail, killed by Fixxer Napalm Granade 
![killed in fortres jail](https://user-images.githubusercontent.com/19292844/53692984-5cef7b80-3d99-11e9-8ee7-736455330525.jpg)
![second death](https://user-images.githubusercontent.com/19292844/53692995-8e684700-3d99-11e9-850c-6372f9933f62.jpg)

**Comment by timoteiz** [comment]
Please add to the bug report the following:

- Choppa and marauder can pull inside.
- Sorc, Mara, choppa and magus aoe can hit us outside.

also note that on photo 2 the user has as enemy target Tibdum who is at 89% life.. proving my point number 2 .

**Comment by EssentialOrder** [comment]
whatever happens outside the jail also happening from inside the jail...Also the cage lever need to be defended ...SOLUTION : put the cage lever 50 feet away from cage if you can't do something else

**Comment by sioding** [comment]
ok guys - i lock this one here. The tracker is not the forum.

**Comment by sioding** [comment]
This is fixed
