### ISSUE TITLE
[Forts] Disconnect reservation does not actually function

### ISSUE THREAD

**Issue by Rydiak** [WarEmu/WarBugs#13538]
![rydiak_393](https://user-images.githubusercontent.com/15963532/53704317-613f8700-3de1-11e9-89f1-c005c8929556.jpg)

Was healing WB in defense of Reikwald, in the lord room, and crashed out.  Reconnected to the game and immediately tried for 5 minutes to try to rejoin the fort via portal, only to receive the "You cannot help your fortress as your realms resources are depleted." message.

Then received the "Your reservation for the fortress has expired." message.

**Comment by Natherul** [comment]
same as https://github.com/WarEmu/WarBugs/issues/13536
