### ISSUE TITLE
{quest} Decadent Slaughter mutilated livestock not giving credit

### ISSUE THREAD

**Issue by sanielion** [WarEmu/WarBugs#13540]
The Mutilated sheep at the marked for finding the clue is not giving credit for the quest. It is clickable but upon clicking on it, nothing changes, quest tracker doesn't give credit, and the sheep doesn't become unclickable.

**Comment by sioding** [comment]
For what quest?

**Comment by sanielion** [comment]
Decadent Slaughter....

**Comment by sanielion** [comment]
in chaos chapter 11

**Comment by sioding** [comment]
ah ok - the first two words were meant as the quest name - sorry too early

**Comment by sanielion** [comment]
its okay, i could have structured it better

**Comment by Lheana** [comment]
You must have completed the other objective (kill NPCs) to complete the one for the Mutilated Sheep.

**Comment by sanielion** [comment]
i did complete the kill portion first, and clicking the mutilated sheep did nothing.

**Comment by Lheana** [comment]
Were you grouped when you tried?

**Comment by Lheana** [comment]
Works fine for me
![anash_015](https://user-images.githubusercontent.com/11537611/53754465-4e49b700-3eb4-11e9-9814-3a09d3917255.jpg)

**Comment by sanielion** [comment]
when i first tried i was in a group, dropping the group did not allow me to get credit. could have been left over group bug that happens with certain quests

**Comment by Lheana** [comment]
Then I close this issue.
