### ISSUE TITLE
Thickmuck Pit

### ISSUE THREAD

**Issue by Furrikson** [WarEmu/WarBugs#13542]
Hello,

Today i was stuck in Thickmuck Pit in lord room. Run down from 3rd floor and then stuck in the wall,
/stuck command  did not help.

![bug](https://user-images.githubusercontent.com/19292844/53717919-f2eadb00-3e59-11e9-8303-3798f4788c53.jpg)

**Comment by sioding** [comment]
Thanks for the report but this is nothing we can fix - and i wasn't able to reproduce it. Whatever happend - seems to be only on your personal situation.
