### ISSUE TITLE
dye merchant money bug

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#13547]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

said the cost of my dye is 5 gold and by mistake, i did click it more than once and i lost like from 139 gold to 19Gold as shown in the video below you can see my money on the top bar 

this happened to me before and i didnt have anything to prove but this time i got it recorded and i cannot afford to lose more money  in 2-5 sec 

**Steps to reproduce the problem:**

just clicked on accept more than once 

**Screenshots/Videos or archive.org evidences:**

**https://clips.twitch.tv/MoldyCautiousOstrichNinjaGrumpy?tt_medium=clips_api&tt_content=url**

**Comment by sioding** [comment]
Sorry but this is not a bug. If you click accept you need to pay. Maybe i don't get why you think this is a bug - please try again to describe why you think this is a bug.

**Comment by Tazo83** [comment]
the bug is the cost 
says 5g but it did take 100 gold in 2-3 clicks ... when it should cost 5g per click so max with 2-3 clicks is 10-15gold and not over 100 gold

**Comment by MaxHayman** [comment]
@Tazo83 Why did you click it more than once?
@sioding We could add a throttle to dying. Like i did for item purchases.

**Comment by sioding** [comment]
Since there is no answer i would suggest you do that throttle thingy @MaxHayman. Assign you this one.

**Comment by Kaelang** [comment]
Isn't really a bug - just tested - takes the gold each time you click, so you must've been hammering the 'Accept' button extremely fast to lose that amount of gold. Click it once.
