### ISSUE TITLE
Lanric nordland's quest crash

### ISSUE THREAD

**Issue by kish4n** [WarEmu/WarBugs#13545]
**Expected behavior and actual behavior:**

Crash when i talk to Lanric, on the Nordland's lanric quest(Beginning quest)

**Steps to reproduce the problem:**
talk to Lanric on the ground=>crash

**Comment by sioding** [comment]
If we have a generic problem with quests we would have a lot of reports with such things here. I am sure this is something on your side. Please follow this thread https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=20075 or ask for help in our technical forum.
