### ISSUE TITLE
Fortress Contribution

### ISSUE THREAD

**Issue by Zoggof** [WarEmu/WarBugs#13541]
I joined during late Stage 2 as Destro attacking in Stonewatch at approx. 1:23AM Altdorf Time 3rd March 2019. Was present during Lord death and received no medallions nor bag roll.

**Comment by sioding** [comment]
did you get the renown on def or win?

**Comment by Zoggof** [comment]
No renown on win, simply the message that the Keep Lord has fallen.

**Comment by sioding** [comment]
Duplicate of #13605
