### ISSUE TITLE
[Quest] Lost blessings

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13556]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Expected behavior: Tooltip should match the ToK text
Actual behavior: Ii doesn't

**Steps to reproduce the problem:**

Take the quest

**Screenshots/Videos or archive.org evidences:**
![bjoorn_012](https://user-images.githubusercontent.com/18528095/53834608-c59e4a00-3f8b-11e9-9998-0cac81c1b8db.jpg)

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
