### ISSUE TITLE
[WP/AM] Same ability name "Gift of Life"

### ISSUE THREAD

**Issue by XmatXergon** [WarEmu/WarBugs#13552]
**Expected behavior and actual behavior:**
Abilities should have unique names.
WarriorPriest Morale4 from Salvation path has same name as Archamage resurrecting ability Gif of Life.
I propose that either WP's M4 should be changed to maybe something like "Sigmar's Blessing" or Archamage resurrecting should be changed to "Gift of Isha" or "Isha's Gift".

**Steps to reproduce the problem:**
N/A

**Screenshots/Videos or archive.org evidences:**
![giftoflife](https://user-images.githubusercontent.com/37849311/53823293-c75b1400-3f71-11e9-8210-6fa8b0742f27.png)

**Comment by sioding** [comment]
As mentioned in discord. The BT is not for suggestions. Please use our forum for it: https://www.returnofreckoning.com/forum/viewforum.php?f=15
