### ISSUE TITLE
PVE monster one shotting players in chrace

### ISSUE THREAD

**Issue by karalis880** [WarEmu/WarBugs#13557]
Rimewing eagle monster next to balance quest in Chrace is untargeable and one shots players.

**Comment by karalis880** [comment]
actually the birds are all over chrace

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by karalis880** [comment]
Thanks also would i be able to get a bug report token for this so i can get
the griffon mount.

**Comment by sioding** [comment]
No sorry. Special mounts will be given out on serious (gamebreaking) bugs or when you bring in a significant amount of good reports of a long time. So don't stop bringing in good reports - maybe some day you will get a special mount.

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
