### ISSUE TITLE
[Quest] 'Wolves is da Best' 

### ISSUE THREAD

**Issue by bealmador** [WarEmu/WarBugs#13553]
**Expected behavior and actual behavior:**
Just like the Quest 'Boars is da Best', in this quest you are supposed to slay three boars and then feed the boar meat to the wolves. however, unlike with the wolf meat from the 'Boars is da Best' quest, the Boar meat item "Chunk of Meat" is not usable and therefore the quest can't be completed.

**Steps to reproduce the problem:**
Pick up the quest, and try using the item looted from the boars, just as described in the quest text.

**Screenshots/Videos or archive.org evidence:**
![quest_log](https://user-images.githubusercontent.com/39677933/53832766-5161a780-3f87-11e9-8362-df6e44f89496.PNG)
![chunk of meat](https://user-images.githubusercontent.com/39677933/53832792-5aeb0f80-3f87-11e9-8d94-fa949f3021e0.PNG)
![quest](https://user-images.githubusercontent.com/39677933/53832804-64747780-3f87-11e9-9d9c-f8a98cfaeb66.PNG)

**Comment by Aarimal** [comment]
Item from the other quest isn't working. And still Chunk of Meat is not usable.

**Comment by Lheana** [comment]
The item Chunk of Meat was an error, it was an item dropped by any boar, and not related to any of these two quests. I corrected the drop of this item.
I also reworked and corrected the quest to work as it should.

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
