### ISSUE TITLE
[Quest] Outacst's Gem

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13555]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Issue 1: Quest tooltip
Expected behavior - should be the same as text in ToK
Actual behavior - text is incorrect

Issue 2: Quest mark 
Expected behavior: Quest mark should stay until You slay Blackwind Wights and Blackwind Guardian
Actual behavior: Quest mark disappears after killing Blackwind Guardian

**Steps to reproduce the problem:**

Issue 1: Take the quest
Issue 2: Kill Blackwind Guardian

**Screenshots/Videos or archive.org evidences:**

Issue 1:
![bjoorn_009](https://user-images.githubusercontent.com/18528095/53833896-f1203500-3f89-11e9-8ba7-81311b34fac4.jpg)

Issue 2:
![bjoorn_011](https://user-images.githubusercontent.com/18528095/53833944-0d23d680-3f8a-11e9-89c3-e804ff636c47.jpg)

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
