### ISSUE TITLE
Shadow Warrior Bug with ranged crit to melee

### ISSUE THREAD

**Issue by Anauka** [WarEmu/WarBugs#13566]
There is an issue with the assault spec for Shadow Warrior Mastery If you put on all of your ranged crit gear before switching into assault stance you get the full amount of crit. This is working functionally however you can switch out the ranged crit gear and still retain the crit for the duration of the scenario or how ever long your alive in the open world. I was testing this out and it is still doing the same thing. If this is working as intended and is ok to do then I apologize

**Comment by grunbag** [comment]
I don’t understand what you mean here

**Comment by raptrr** [comment]
@Anauka can we get an update or another explanation?
I've put this on 2 Week Ultimatum now and monitor it.

**Comment by Anauka** [comment]
Sure I havn't played the game in awhile but basicly what you would do is put tactics into your melee crit and it would convert your melee crit to ranged crit after you did this you could change your tactics back to what they were originally and keep the ranged crit from the melee tactics that give you crit. I havn't played the game in some time but I could give it a download to check if this is still an issue.
________________________________

**Comment by raptrr** [comment]
@Anauka would really appreciate it :)
If possible provide some screenshots or video, that would help a lot.
