### ISSUE TITLE
[terrain] Caledor ->Fall Landing

### ISSUE THREAD

**Issue by Elflord123** [WarEmu/WarBugs#13567]
MAIN VIDEO - PLS SEE! 

https://youtu.be/j3XH8y9nT6w

Text. The system is designed so that there is a calculation of murder in the danger zone. However, it is necessary to extend this zone. Here's why: (video) I press "Flee"and manage to swim in the last second, it's very Important!
Very few people know this.
Zealot can swim out with the rune of resurrection itself. Resurrect and swim to Fell Landing.
The rest of the group may die and he will resurrect them. Up to 24 people ( 1 WB)
The number of those in the zone will thus be unlimited
However, I have to prove it to You when there will be active Fall Landing. This is the first step!

And step two. Nothing complicated here, showed in detail the point where you can jump on the site and run to the Fort.

https://youtu.be/ksFKVBJqoa4

**Comment by Elflord123** [comment]
MAIN VIDEO - PLS SEE! 

https://youtu.be/j3XH8y9nT6w

**Comment by sioding** [comment]
this is fixed
