### ISSUE TITLE
[Fort] Null Reference Exceptions

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#13562]
During Fell Landing siege appeared 2 times atleast
![unknown](https://user-images.githubusercontent.com/42712833/53911464-86452b80-4067-11e9-9f29-e527db91ce5a.png)
![unknown](https://user-images.githubusercontent.com/42712833/53911473-8c3b0c80-4067-11e9-8ad1-fdf04d1e202b.png)

**Comment by Rockalypse** [comment]
![unknown](https://user-images.githubusercontent.com/42712833/53917824-826cd580-4076-11e9-9e82-2bef211dd47e.png)

**Comment by Elflord123** [comment]
MAIN VIDEO - PLS SEE! 

https://youtu.be/j3XH8y9nT6w
