### ISSUE TITLE
[Quest] Desecration , Destruction T1 Norsca

### ISSUE THREAD

**Issue by MiguelVitta** [WarEmu/WarBugs#13569]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
I got the Quest Desecration, went to the Amund's Barrow, killed the undead to get to the coffin. But it doens't work, I click on the spades on the floor, on the coffin, nothing happens. Am I doing something wrong? Both spades and coffin appear to be without any health when targeted, so maybe they should recover the health and are not doing it? 

**Steps to reproduce the problem:**
Simply take the quest and go to Amund's Barrow and try to click on the objects.
![quest problem - spades](https://user-images.githubusercontent.com/28876999/53984869-fb147600-40f8-11e9-9919-404d5a38b9fb.PNG)

![quest problem - coffin](https://user-images.githubusercontent.com/28876999/53984878-ff409380-40f8-11e9-948c-2b9c124d4584.PNG)

**Screenshots/Videos or archive.org evidences:**

**Comment by Lheana** [comment]
Sorry but yes you are doing something wrong. Like the quest describes, you must retrieve the greatsword from Amund's Remains. So search for an object called Amund's Remains.

**Comment by MiguelVitta** [comment]
Thanks! Will search for the object.
