### ISSUE TITLE
Tome of the Smuggler - Not providing passive RF

### ISSUE THREAD

**Issue by Nikolaes** [WarEmu/WarBugs#13564]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

8 RF passive in combat per second 

**Steps to reproduce the problem:**

Relogged, /rel, exchanged items, multiple zones. Can't seem to get it to generate.

**Screenshots/Videos or archive.org evidences:**

Pictures showing being in combat, not doing anything for 10 seconds, no RF regen

![nikolaes_028](https://user-images.githubusercontent.com/43499009/53913680-df8e6a00-4029-11e9-8b96-9f8c3dfc6014.jpg)
![nikolaes_029](https://user-images.githubusercontent.com/43499009/53913681-df8e6a00-4029-11e9-8d23-aada756c73e5.jpg)
![nikolaes_030](https://user-images.githubusercontent.com/43499009/53913682-df8e6a00-4029-11e9-8b50-eee43d11f22a.jpg)
![nikolaes_031](https://user-images.githubusercontent.com/43499009/53913683-e0270080-4029-11e9-9633-0bac49cdad05.jpg)
![nikolaes_032](https://user-images.githubusercontent.com/43499009/53913684-e0270080-4029-11e9-903e-e1f129c23596.jpg)

**Comment by sioding** [comment]
Switching the tome doesn't help - relog doesn't help. You have to move the item into your backpack and back on the character. That mean really: No switching. RF regen stops when you do this. a know issue we can not fix atm. can you please test it?

**Comment by Nikolaes** [comment]
That worked. Haven't encountered that yet. Thanks!
