### ISSUE TITLE
[terrain] BlackCrag -> ButcherPass

### ISSUE THREAD

**Issue by rekkir** [WarEmu/WarBugs#13561]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

I saw an orc jump up here a while back, chased him and reported it. Now I retried but there is still a way in. Thx for keeping at it guys! :) just a lil more walls and we r good.

**Screenshots/Videos or archive.org evidences:**
https://youtu.be/L_x5jp06jm4?t=52

**Comment by NorKalli** [comment]
patched the hole

**Comment by sioding** [comment]
fixed with patch from 09.03.2019
