### ISSUE TITLE
Gunbad (Quest Reward [kill])

### ISSUE THREAD

**Issue by Jubok22** [WarEmu/WarBugs#13563]
Hey i thing it need to be Fixxed.

Do today 3 Times Gunbad and got no Quest Reward for the Boss :-( its really bad if you try to farm the set and you get nothing for your class from the boss do now the Left Boss 4 Times but only 1 Time Quest reward... and all time no GM onlinte to Help :(

**Comment by sioding** [comment]
Can you please add a character name and the time you did the boss - so that the devs can check if something is in the logs?

**Comment by Jubok22** [comment]
Today 1 Time in the Morning... Yesterday 1 Time too at Evening..   but dont know the time...  and some day ago... dindt now anymore...

**Comment by sioding** [comment]
and a character name?

**Comment by Jubok22** [comment]
do now Glomb Da Suig herder3- 4 times i thing got 1/3...    Ard da Feed 2 Times but got only 1/3   Soli work all time :) 2 Kills 2/3   and masta Mixa work too i thing 2/3 too :)

It was with the Character Heilige

**Comment by Jubok22** [comment]
![kill gunbad](https://user-images.githubusercontent.com/32957323/53912974-74a95700-405a-11e9-99bf-8145835b71a5.png)


this is from today i thing but the other one i do not a pic :(

**Comment by Jubok22** [comment]
![no quest again](https://user-images.githubusercontent.com/32957323/53917338-94de1380-4064-11e9-89ba-aeac66c9714e.png)


and no Kill QUest again... Masta Mixa still 2/3 :(   its not funny anymore... spent so much time in the dungen and all time no encounter,,,,

**Comment by grunbag** [comment]
Screenshot your party lockout with .lockout

**Comment by Hargrim** [comment]
This should be fixed.
