### ISSUE TITLE
[QUEST] Disenchantig the Stone

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#13579]
Part where you need to Kill Master Tadrilian and read his journals bugged - You cannot read journal he drops to check quest entry - rightclicking, double clicking, doing it without group and getting new item have not helped.

**Comment by Rockalypse** [comment]
Strangely enough, gaining quest Item from another quest soved it. Ticket can be closed.

**Comment by sioding** [comment]
You can always close your own tickets if you think its fixed - but not problem for me to do it for you

**Comment by Rockalypse** [comment]
Oh, did not know I can do that. Only see Edit button on top, but thats not it.

**Comment by sioding** [comment]
Now you can see the "Reopen and commet" button down below - if its open you can close it with that button.

**Comment by Lheana** [comment]
Just for information, the objective where you have to read the journal should be the last one as the item enables to turn in the quest and take the next part. Thus you can only complete this objective when you have killed the 6 Lorekeepers.
