### ISSUE TITLE
Martyr's Blessing RF requirement tooltip

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#13573]
**Expected behavior and actual behavior:**

The tooltip says 20 RF/s in blue text and 10RF/s in the actual tooltip text. One of them is wrong I guess.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

![iaioernt_000](https://user-images.githubusercontent.com/7400/54030844-31abc880-41ad-11e9-9614-6fdbf296ed95.jpg)

**Comment by grunbag** [comment]
Fixed at next patch. it's 20

**Comment by sioding** [comment]
fixed with patch from 09.03.2019
