### ISSUE TITLE
[Quest] Show 'em How to Waagh.

### ISSUE THREAD

**Issue by Maleus1979** [WarEmu/WarBugs#13570]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Quest it not completable in Mount Gunbad i tried to speak to npc Grobbag and click on complete and nothing happens, I tried relog and go out and in instance as well.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by Kaelang** [comment]
Gunbad rework has since been completed and a lot of these issues will have now been addressed as per the recent rework. Please re-open this ticket if the issue persists.
