### ISSUE TITLE
Untargetable

### ISSUE THREAD

**Issue by Jiawnally** [WarEmu/WarBugs#13577]
The Uthorian Corsairs in the Blighted Lands for the mission 'Storm the Beach' are currently untargetable, making the mission impossible to do.
![Faarvalor_000](https://user-images.githubusercontent.com/48191709/54062562-c70e8300-41d4-11e9-9164-9074e7ce43af.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
