### ISSUE TITLE
[Quest] Thrill of power (Chrace, destro)

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#13574]
In part when you need to place leystones on Rubics, neither clickink rubicks, nor clicking leystones in inventory gives quest entries.

**Comment by Lheana** [comment]
Were you grouped?

**Comment by Rockalypse** [comment]
No

**Comment by Lheana** [comment]
Indeed there was an error.
Anyway the quest will be reworked with next patch to work as it should. I advice to destroy the 4 Ley Stones, abandon the quest and retake it.

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019

**Comment by Lheana** [comment]
How do you try to complete the quest exactly?

**Comment by Gwendis** [comment]
> 
> 
> How do you try to complete the quest exactly?


I have 4 leystone in bag.
than go to the south to the 4 rubics, but cant click it on the 4 round disks that laying on the stones.

**Comment by Lheana** [comment]
You are meant to use the Ley Stones from your inventory standing close to each of the 4 rubrics.
I advice you to destroy the Ley Stones from your inventory, abandon the quest and retake it so that the quest works properly.
