### ISSUE TITLE
Artistry of War - Artillery Crew missing

### ISSUE THREAD

**Issue by Daxramas** [WarEmu/WarBugs#13572]
I had completed the previous parts of the Artistry of War chain, which required you to speak to various NPC's and then return to the quest giver (I have abandoned and retried this quest a number of times to confirm it was not a single event).

I had reached a part of the chain that required me to talk to 'artists' NPC's nearby. 

Seen here:
![bug1](https://user-images.githubusercontent.com/48343700/54011385-35544500-41d7-11e9-805d-b19091dc4a7d.jpg)
![bug2](https://user-images.githubusercontent.com/48343700/54011402-44d38e00-41d7-11e9-9da7-059886a823de.jpg)

Upon reaching the supposed location for these Artists I was unable to find any NPC's except for standard guards.
Seen here:
![bug3](https://user-images.githubusercontent.com/48343700/54011448-6df41e80-41d7-11e9-904c-76cf4cc763ae.jpg)

At the back of the quest area were 2 NPC's which I assume are the artists in question, however they are nameless, un-clickable, and don't show any information when hovering over them with my mouse.
Seen here:
![bug4](https://user-images.githubusercontent.com/48343700/54011568-de9b3b00-41d7-11e9-890b-666c228b597a.png)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
