### ISSUE TITLE
Backpack Doesn't Load Correctly

### ISSUE THREAD

**Issue by Blazehawk** [WarEmu/WarBugs#13581]
My entire backpack loads incorrectly, not allowing me to see or interact what items I have in my backpack.
It only affects this specific character and my others are just fine.

I've tried dying, entering another zone, and closing then relaunching the game yet the problem still persists on my warrior priest.

![Bugged Backpack](https://user-images.githubusercontent.com/48390413/54075274-468e6780-4252-11e9-96e6-4238b1240b5f.PNG)

**Comment by Ssynchrotron** [comment]
I started playing this game yesterday and I'm having a very similar problem. My backpack is not showing my items and it has a white background on it. When I try to click on any tab in the backpack window it changes colors and freezes, only letting me close and open the screen.


![Untitled](https://user-images.githubusercontent.com/50468421/57494284-dd04f680-729e-11e9-8771-0b1aa0c7518c.jpg)


Here's the things I tried to do to solve or diagnose the problem:

- Typing /rel on the chat does not solve the problem, it only reverted the window to its previous bugged state with the white screen.
- Disabling addons didn't work.
- Deleteting the Cache folder of the game didn't work.
- Closing the game and running the RoRUpdater didn't work.

- **When I change characters the new one does not have a bugged backpack.**
- My character with inventory problems also happens to be low level (11, order) like OP.

I was thinking that we might have looted a bugged item which is now causing the problem, but it's just a hypothesis.

**Comment by Bloodlet** [comment]
Having this issue now as well.

**Comment by Bigkasakin** [comment]
The same is happening with me, I cannot use quest items also

**Comment by xpander69** [comment]
Closing this super old report. To fix the issue:
-Clear the cache folder
-Remove everything from  WAR user folder ( WARNING! you will lose all your addon configurations)
