### ISSUE TITLE
Character struck

### ISSUE THREAD

**Issue by BWerde** [WarEmu/WarBugs#13585]
**Expected behavior and actual behavior:**
The expected behavior is not to block the character. Currently, the behavior of continuing the movement.

**Steps to reproduce the problem:**
to walk by mistake in the area and pass behind the chair

**Screenshots/Videos or archive.org evidences:**
![xDDDDDDD](https://user-images.githubusercontent.com/48395537/54078605-323a8100-42cb-11e9-8c4b-05d26412c9a3.jpg)

**Comment by sioding** [comment]
Nothing for the bugtracker sorry. Just use double /stuck to get out of it.
