### ISSUE TITLE
Trolls and the Stars quest

### ISSUE THREAD

**Issue by panodill** [WarEmu/WarBugs#13589]
Quest in t2 bugged. Name Trolls and the Stars in chapter 8

**Expected behavior and actual behavior:**
Kill a mob to get a book, hes stuck in a rock so cant kill him.

**Steps to reproduce the problem:**
try to do quest.

**Screenshots/Videos or archive.org evidences:**
https://i.imgur.com/XKePvv8.jpg

**Comment by panodill** [comment]
After server restart the NPC was possible to kill.

**Comment by NorKalli** [comment]
moved him a tad just to be safe
