### ISSUE TITLE
[Keep lord] After lord get taunted out of keep, he do not return

### ISSUE THREAD

**Issue by ReaperKirusha** [WarEmu/WarBugs#13588]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
after lord get taunted out of keep,and then kill his target, he should return to his place in a keep

**Steps to reproduce the problem:**
get hit a lord by any AOE ability and he will run to that player, after killing it he do not return and stay in the place of ,murder

**Screenshots/Videos or archive.org evidences:**

https://imgur.com/4ao9BQH
this happened in ostland at 1:44 PM

and similar thing happened 1 hour before in Caledor, order's players couldnt find a lord, bc he was outside

**Comment by ReaperKirusha** [comment]
same thing happened again, i ve spotted this at 10:34 am server time in Black Fire Pass
![Khanzul_002](https://user-images.githubusercontent.com/22665819/54346776-8052da00-4667-11e9-92cf-5ac878350fb9.jpg)

**Comment by sioding** [comment]
1. try to fix this is being set for next patch.

**Comment by XmatXergon** [comment]
https://youtu.be/YtU6A94i8VY

**Comment by sioding** [comment]
Patch done - i let this one open. Please report keep lords that don't come back to their spawn point

**Comment by sioding** [comment]
![image](https://user-images.githubusercontent.com/18517842/56489169-17ba1100-64e1-11e9-93e9-c3b3d28732f6.png)

**Comment by Natherul** [comment]
another attempt coming next patch, the lords seems very unwilling to return back to his fort... they must be planning a vacation....

**Comment by sioding** [comment]
Fixed with patch from 27.04.2019
