### ISSUE TITLE
[Quest] Duelist

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13595]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

I don't know is it really an issue, but there are two quests with the same name but with other targets. Or maybe next step is obtainable earlier?

**Steps to reproduce the problem:**

Take the quest.

**Screenshots/Videos or archive.org evidences:**

![Bjoorn_028](https://user-images.githubusercontent.com/18528095/54087412-e8957900-4352-11e9-8f76-c29035f9441a.jpg)

**Comment by Kabucoror** [comment]
previous quest was missing for step 2. fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
