### ISSUE TITLE
[Quest] Ascension

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13597]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected behavior and actual behavior:

Expected behavior: Tooltip should match the ToK description.
Actual behavior: It doesn't

Steps to reproduce the problem:

Take the quest

**Screenshots/Videos or archive.org evidences:**

![Bjoorn_030](https://user-images.githubusercontent.com/18528095/54087509-bf291d00-4353-11e9-955c-1e8e1cce8030.jpg)

**Comment by sioding** [comment]
fixed with patch from 06.04.2019
