### ISSUE TITLE
[Quest] Rooting out the reminder

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13598]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Expected behavior: Tooltip should match the ToK description.
Actual behavior: It doesn't

**Steps to reproduce the problem:**

Take the quest

**Screenshots/Videos or archive.org evidences:**

![Bjoorn_031](https://user-images.githubusercontent.com/18528095/54087526-f4ce0600-4353-11e9-99cf-456386d12e02.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
