### ISSUE TITLE
[Quest] Twisted

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13593]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Issue 1:
Expected behavior: Quest description match the ToK one
Actual behavior: it doesn't

Issue 2:
Expected behavior: Quest marker stays on quest area until You kill all mobs
Actual behavior: Quest marker disappears after killing Bloodletter K'thar

**Steps to reproduce the problem:**

Take and follow the quest

**Screenshots/Videos or archive.org evidences:**

Issue 1:
![Bjoorn_021](https://user-images.githubusercontent.com/18528095/54087237-1f6a8f80-4351-11e9-99d0-1febab304597.jpg)

Issue 2:
![Bjoorn_026](https://user-images.githubusercontent.com/18528095/54087244-25f90700-4351-11e9-9b9a-15da6ba4c593.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
