### ISSUE TITLE
[Quest] Paranoid Raven Games

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13594]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Issue 1:
Expected behavior: There should be a quest marker with target: Rugger Skullfork on the map
Actual behavior: There isn't

Issue 2:
Expected behavior: There should be a quest marker above Onnister Preul
Actual behavior: There isn't

**Steps to reproduce the problem:**

Take and follow the quest

**Screenshots/Videos or archive.org evidences:**

Issue 1:

![Bjoorn_023](https://user-images.githubusercontent.com/18528095/54087345-31006700-4352-11e9-9348-78abacfa6227.jpg)

Issue 2:
![Bjoorn_024](https://user-images.githubusercontent.com/18528095/54087346-31006700-4352-11e9-871b-124ee4d7fc65.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
