### ISSUE TITLE
Damage of the guard not mitiged by the guardian.

### ISSUE THREAD

**Issue by Kryeghz** [WarEmu/WarBugs#1359]
Hello,

After some tests we see an issue on the damages of the spell guard of the tanks.

Normaly the damage taken by the guardian should be mitiged by his own armor / thoughness but it's not the case nowaday.

To check that two things : 
- check in the log the damage take by the guarded and by the guadian with different armor / thoughness and the two amounts are equals.
- A screen from our tank combat log where we can see the damage of the guard has no mitigation : http://postimg.org/image/41hkuq12z/full/ instead of normal damage : http://postimg.org/image/qei3ognyd/full/

Just ask me if you want more details.

Thanks for your help. =)

**Comment by ozarmidrashim** [comment]
False report.
