### ISSUE TITLE
[Quest] Grimclan trail

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13592]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Expected: Tooltip match the ToK desciption
Actual: it doesn't

**Steps to reproduce the problem:**

Take the quest

**Screenshots/Videos or archive.org evidences:**

![Bjoorn_018](https://user-images.githubusercontent.com/18528095/54086979-e7fae380-434e-11e9-8fc0-19bf4f091498.jpg)

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
