### ISSUE TITLE
[Quest] Lost in Time

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13591]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Expected: tooltip match ToK desciption
Actual: it doesn't

**Steps to reproduce the problem:**

Take the quest

**Screenshots/Videos or archive.org evidences:**

![Bjoorn_017](https://user-images.githubusercontent.com/18528095/54086956-b1bd6400-434e-11e9-9581-97d49022dd3d.jpg)

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
