### ISSUE TITLE
[Item] Echelon Chaosaxe (1-H)

### ISSUE THREAD

**Issue by Skutrug** [WarEmu/WarBugs#1360]
The echelon Chaosaxe available at level 25 from the IC vendor has a talisman slot but does not accept tali in it and freeze the talisman fusing windows.

**Comment by Evildoor** [comment]
I do believe this is a general problem rather than specific weapon problem, happened to me several times on different items. So far exiting (not just going to character selection, exiting completely) the game and logging in again helped.

**Comment by Evildoor** [comment]
2 weeks, no response... Closing unless someone proves that this is not a general problem with talisman window and has something to do with the item mentioned.
