### ISSUE TITLE
Off Hand Weapon Procs

### ISSUE THREAD

**Issue by Farlopa** [WarEmu/WarBugs#13606]
I was testing autoattacks with subjugator as ofhand weapon,did more than 100 autoattacks on dummy and Subjugator proc never activates,ye ofc is a 5% for proc but in 100 aa never activate 1 single proc? maybe is a bug and i just gonna report it for someone to check it cause maybe is bug or maybe i just has no luck with that weapon.
Proc name: Concussion X

https://imgur.com/a/pLfkIWh

**Comment by grunbag** [comment]
works fine
![concusion X](https://user-images.githubusercontent.com/24207191/54491351-357ecf80-48be-11e9-93b2-e42c1f5b366c.png)

**Comment by grunbag** [comment]
closing
