### ISSUE TITLE
[Quest] 'Kill Dem All'

### ISSUE THREAD

**Issue by bealmador** [WarEmu/WarBugs#13604]
**Expected behavior and actual behavior:**
I am unable to turn the quest 'Kill Dem All' in Barak Varr in after having completed it. Nothing happens when I click on "complete."

**Steps to reproduce the problem:**
Accept the quest and try turning it in.

**Screenshots/Videos or archive.org evidences:**
![Capture](https://user-images.githubusercontent.com/39677933/54099022-8b7fde80-43b7-11e9-9cfa-ab22bde7eb26.PNG)
![Capture2](https://user-images.githubusercontent.com/39677933/54099030-933f8300-43b7-11e9-94f0-65d746d0eb8c.PNG)
![Capture3](https://user-images.githubusercontent.com/39677933/54099035-98043700-43b7-11e9-8a4f-703ea5bfe3e1.PNG)

**Comment by bealmador** [comment]
Had a chat with Norkalkilla, the quest is not fixable by just changing values in the DB. He said he knows how to fix it though.

**Comment by sioding** [comment]
fixed with patch from 06.04.2019
