### ISSUE TITLE
Respecialize Renown Points Bug

### ISSUE THREAD

**Issue by Dobzse** [WarEmu/WarBugs#13603]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Unable to spend any renown points while having available renown points.
While trying to resolve the bug I ended up with zero points.

**Steps to reproduce the problem:**
Respecialize at renown trainer. After reading in chat: "You don't have enough points." I ended up with having no renown points at all.

**Screenshots/Videos or archive.org evidences:**
![Xalzius_125](https://user-images.githubusercontent.com/41837044/54096629-e6f89f00-43ac-11e9-8fbb-4ba06d73ab5f.jpg)
![Xalzius_126](https://user-images.githubusercontent.com/41837044/54096630-e95af900-43ac-11e9-8f40-4ec9f9820a8f.jpg)

**Comment by sioding** [comment]
Hm tried to reproduce that - but wasn't able to. Please add more information / or a video how you was able to get into this.

**Comment by Scophis** [comment]
I had the same issue at the Weekend and was able to recreate it.

-Talk to the Renown Trainer as ususal _(I'm using the AdvancedRenownTrainer-Addon)_
-optional: reset your spend points
![RR_Trainer1](https://user-images.githubusercontent.com/40274248/54301028-6dd09600-45be-11e9-85b0-5a29ff146587.jpg)
-Spread some points
-Deselect the trainer-NPC
-Click "Train"
![RR_Trainer2](https://user-images.githubusercontent.com/40274248/54301033-70cb8680-45be-11e9-8a45-fb4ab0fc139d.jpg)
-The Skills you've put points into will turn green, but won't give a bonus
-RR-Point-counter resets to your max-value again
-Reopen the Trainer-window
-Click Respecialize, while having the NPC in target.

Your Points should now jump to 0/0. 
![RR_Trainer3](https://user-images.githubusercontent.com/40274248/54301038-732de080-45be-11e9-9c0e-bcecf7040686.jpg)

So far only a relog to char-selction fixed this for me.
