### ISSUE TITLE
[Fortress] Batcher's Pass - respawn bug

### ISSUE THREAD

**Issue by Elflord123** [WarEmu/WarBugs#13607]
Order us killed, but we're resurrecting not in cage, but on 4 floor.

![image](https://user-images.githubusercontent.com/48329663/54139656-1c47d000-4433-11e9-8edc-7c7ff70fb41a.png)

**Comment by Azerreth** [comment]
Had the same issue last night in elf; We went at it for at least forty minutes. Then when the fort was taken, we got no rewards once so ever.

**Comment by Elflord123** [comment]
yes and no rpll :(

**Comment by sioding** [comment]
The bugtracker is not a forum. Please stick to the topic if you want to add things. A bump or another problem which highjacks the report isn't helpful

**Comment by Natherul** [comment]
Does this happen anymore? Because I am unable to replicate this issue
