### ISSUE TITLE
Black orc - Yer Nothin`

### ISSUE THREAD

**Issue by Iamwithstupid** [WarEmu/WarBugs#13601]
**Expected behavior and actual behavior:**
Black Orc morale 4 - Yer Nothin from Boss tree does not fuction as stated. It only applies a DoT effect and morale debuff effect is not applied.

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment]
Can we please see your testing screenhots/videos?

**Comment by Iamwithstupid** [comment]
https://www.youtube.com/watch?v=sg_c5wy5F9M

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
