### ISSUE TITLE
Scenario Disconnect

### ISSUE THREAD

**Issue by EssentialOrder** [WarEmu/WarBugs#13614]
When scenarios pop ...i press Join i get logout to the character selection or disconnect and when i login ,i'm at Altdorf with 10min penalty ,  also if i'm in a party with someone else before that happen, i remain at party after the reconnect or relogin
Cheers

**Comment by sioding** [comment]
Please rmove your audio.myp and load it again. https://returnofreckoning.com/forum/viewtopic.php?p=326158#p326158
