### ISSUE TITLE
[TheMaw] cant join fortress but getting RP and Roll

### ISSUE THREAD

**Issue by xaraxdestr** [WarEmu/WarBugs#13618]
I did not have a reserved spot. I stand in front of portal and clicking it (getting message for reserved spots or depleted ressources)
Then P2 starts and I was not getting any message at all at portal while clicking the portal.
So I left.

Then the lord dies and I was getting 75k RPs, 10k influence and 4 invader while standing in IC. I was also able to roll (place 99, no loot)

there must be something wrong.

**Comment by Tazo83** [comment]
same happened to me exactly as the above post

**Comment by xaraxdestr** [comment]
you referenced both issues with the other and closed both. Dunno if intended.

**Comment by sioding** [comment]
this should be fixed
