### ISSUE TITLE
T1: Nordlands locks, but other pairings wont open after that. BO's are locked and cant be captured.

### ISSUE THREAD

**Issue by zhomp** [WarEmu/WarBugs#1361]

**Comment by ozarmidrashim** [comment]
Which pairing did the game say would unlock next?

**Comment by zhomp** [comment]
I saw no message at all, but might have missed it, was midfight. After lock in Nordland me and another dude went to Elf & Orc pairing, trying to capture BO's, but they were all locked. Tried it a couple of times till Nordland was unlocked and we went there back.

**Comment by Evildoor** [comment]
I'm pretty sure i've seen at least one DvG lock in T1. Closing.
