### ISSUE TITLE
2x weekend exp not working in party

### ISSUE THREAD

**Issue by acidicrain** [WarEmu/WarBugs#13611]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
2x experience given when pve party not getting mob grinding

**Steps to reproduce the problem:**
kill mob in pve on own get 1000 approx exp
kill mob in group of two get 660 approx exp

**Screenshots/Videos or archive.org evidences:**

**Comment by wargrimnir** [comment]
XP is split in groups. You could have just asked in advice chat.
