### ISSUE TITLE
place where you can be stuck fell landing 

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#13616]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
fell landing 45.26
![Thorbolt_790](https://user-images.githubusercontent.com/16274785/54172374-1c20f200-447e-11e9-8fe7-6e45d123bc6f.jpg)
![Thorbolt_791](https://user-images.githubusercontent.com/16274785/54172394-2c38d180-447e-11e9-9be2-67bc5d01e0e2.jpg)

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
