### ISSUE TITLE
[Quest] 'Gnobble-Hide' and 'Ultimate Mushroom'

### ISSUE THREAD

**Issue by bealmador** [WarEmu/WarBugs#13615]
This problem has been reported as early as April 2017 but the person describing the issue provided no screenshots and only listed half of the problems.
old thread: https://github.com/WarEmu/WarBugs/issues/9473

**Expected behavior and actual behavior:**
The quest requires you to hunt down a mob, get the item it drops and return to the quest giver. However, I am unable to find the mobs. I tried killing squigs around in the area but none of them drop the item required so I think the actual required mob is missing.

Also, the quests only reward 120 experience. Other quests in the area reward experience in the range from 7,000 to 9,000. It also shows the quest as completed on the map, but the quest is not completable and the items required are also still showing as 0/1.

**Steps to reproduce the problem:**
Pick up the quest and try to acquire the item by killing the (nonexisting) mob that drops it.

**Screenshots/Videos or archive.org evidence:**
![Capture](https://user-images.githubusercontent.com/39677933/54166665-8d54ab00-4466-11e9-933a-586e70fe4a51.PNG)
![Capture2](https://user-images.githubusercontent.com/39677933/54166671-90e83200-4466-11e9-9e5a-23dcb9100feb.PNG)
![Capture3](https://user-images.githubusercontent.com/39677933/54166672-947bb900-4466-11e9-83d5-91e61bfb1da6.PNG)

**Comment by Gwendis** [comment]
Already some news about this 2 quest?
Are this mobs already running around?
Thanks

**Comment by sioding** [comment]
don't bump on reports please

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 10.06.2019
