### ISSUE TITLE
Half hp bug.

### ISSUE THREAD

**Issue by Theyseememaruading** [WarEmu/WarBugs#1362]
Normally outside of rvr bolsters my mara has around 2000 health. Recently i've noticed coming out of a rvr zone (which puts me at around 3.5k) and losing the bolster puts me at around 950 health. I tried to logging, relogging, and restarting the client in general, but i havnt seen many results yet. If anyone could help i'd be much appreciated.

**Comment by Stinkypants** [comment]
This is a known bug for Mara's. I believe your stats return to normal once you level your toon past 17.  Somewhere around there.

**Comment by milosxe** [comment]
https://github.com/WarEmu/WarBugs/issues/1007

**Comment by Evildoor** [comment]
Seems to be the part of general problem, which i described in
https://github.com/WarEmu/WarBugs/issues/1007
Closing this.
