### ISSUE TITLE
[SM] Crashing Wave VFX

### ISSUE THREAD

**Issue by Ripliel** [WarEmu/WarBugs#13620]
**Expected behavior and actual behavior:**
SM's skill Crashing Wave should have a special VFX which it had on Live.

![SM CW](https://user-images.githubusercontent.com/16005849/54194049-6761f180-44cc-11e9-8dcc-4d9c060decd9.PNG)

https://youtu.be/mBzNR-NMBmg?t=218 

RoR server:
https://drive.google.com/open?id=1urKAZDFRafdfGUb9Q17DA5-Nqghqn1_X

**Comment by Ripliel** [comment]
2H VFX:
![2h VFX](https://user-images.githubusercontent.com/16005849/54203338-288b6600-44e3-11e9-850a-9e8a4c22e792.PNG)
https://youtu.be/mBzNR-NMBmg?t=297

**Comment by grunbag** [comment]
Fixed at next patch

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
