### ISSUE TITLE
Wrong name on Sigmar's Vision buff

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#13625]
**Expected behavior and actual behavior:**

The buff that you get from the ability "Sigmar's Vision" is named "Sigmar's Grace" instead of matching the ability name. Makes it difficult to identify in the aura addon for example.

This bug was actually present on live as well, but would be nice to fix.

**Steps to reproduce the problem:**

Use Sigmar's Vision and check your buffs.

**Screenshots/Videos or archive.org evidences:**

Pictures of the buffs from both abilities

![grace](https://user-images.githubusercontent.com/7400/54211121-0bee2e80-44e1-11e9-92ae-b7361236def1.png)
![vision](https://user-images.githubusercontent.com/7400/54211130-0ee91f00-44e1-11e9-8e3b-d8685a6519ce.png)

**Comment by grunbag** [comment]
Fixed for next patch

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
