### ISSUE TITLE
2h warriorpriest dealt an insane amount of dmg

### ISSUE THREAD

**Issue by rekkir** [WarEmu/WarBugs#13627]
Issues should be unique. Check if someone else reported
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
 
I expected to slowly widdle down the dark elf tank but I absolutely destroyed him instead, happened in t2 empire while Praag was open. Had 400% aao. My damage to him was absolutely bonkers

**Steps to reproduce the problem:**

I logged in, spawned in  TC keep w destro lord on me, i used [Sigmar's vision] and [Sigmar's shield] and got the heck out of there. When most lord and other NPC's were resetting I popped [Divine Assault] on one of the minions and got back some HP. 
I kept the visual appearance of [Sigmar's Shield] buff and went to Crypts BO. There i encountered and completely destroyed a lvl 40 BG. 

**Screenshots/Videos or archive.org evidences:**

![combat log](https://user-images.githubusercontent.com/28030187/54240847-8d64b180-451f-11e9-96e1-a7dcfe89fb2f.jpg)

![tactics](https://user-images.githubusercontent.com/28030187/54241384-07496a80-4521-11e9-9c0d-a0ca2b0b242f.jpg)

UPDATED WORKING YOUTUBE LINK: https://youtu.be/CsvcNeqxVX4

**Comment by XmatXergon** [comment]
no video available, where was the fight ? maybe u got Warcamp buff ?

**Comment by rekkir** [comment]
Fight was on the stairs into Crypts. updated w working youtube link

**Comment by grunbag** [comment]
This bo is near warcamp so I guess so

**Comment by rekkir** [comment]
If I  got wc buff it was from destro warcamp, kinda strange

**Comment by sioding** [comment]
No more things added here - seems not reproducable. Sorry we can not fix things we can not reproduce. If anyone have more Informations for this add it here and i will reopen this one - but for now: close
