### ISSUE TITLE
[Quest] 'Pile On'

### ISSUE THREAD

**Issue by bealmador** [WarEmu/WarBugs#13629]
This quest has been reported as not working properly before, however, I believe it was working just as intended and instead has been broken.
First mention: https://github.com/WarEmu/WarBugs/issues/8193

**Expected behavior and actual behavior:**
For this quest you are supposed to a) kill a mob *(Boozraz Waaazzug)* and b) interact with an object *(Big Trophy Pile)*. They are marked on the map to be in two different locations (see screenshot). Boozraz is nowhere to be found, I ran across the whole area and found interestingly only one other mob that seems to belong next to his pile, but was somewhere completely different in the midst of dwarfs (Giznash).

Also, clicking the *Big Trophy Pile* does not give any quest update. It still shows as 0/1.

**Steps to reproduce the problem:**
Try finding Boozraz. Try interacting with the Trophy pile.

**Screenshots/Videos or archive.org evidences:**

Location of the trophy pile. Notice: Giznashes boys are around here, but not Giznash.
![trophy pile location](https://user-images.githubusercontent.com/39677933/54247568-c14cd080-4539-11e9-8b58-61a3ad767285.PNG)

Giznash's location:
![Giznash location](https://user-images.githubusercontent.com/39677933/54247623-f527f600-4539-11e9-90b8-310e3b5dc270.PNG)
![Giznash](https://user-images.githubusercontent.com/39677933/54247627-f822e680-4539-11e9-8678-581318b8ddba.PNG)

Markings on the map for this quest:
![quest marking](https://user-images.githubusercontent.com/39677933/54247650-0b35b680-453a-11e9-9917-6f29b763151c.PNG)

**Comment by Lheana** [comment]
Everything you describe is INTENDED, and fits with the story of the quest. This quest says nowhere to kill Giznash. To fit with the quest, you have you kill Boozraz before being able to complete the objective for the Trophy Pile.
There is no problem with Boozraz, he is where he is meant to be, and inside the quest marker.
![Anaehll_416](https://user-images.githubusercontent.com/11537611/54272802-ad7a8c00-4584-11e9-8593-2fce63efb0dc.jpg)
![Anaehll_417](https://user-images.githubusercontent.com/11537611/54272819-b3706d00-4584-11e9-99d8-5e0090ccd1d9.jpg)

**Comment by bealmador** [comment]
That is very odd, I stopped by there yesterday at least 5 times to see if he was there, and he wasn't. I know it says nowhere that Giznash is supposed to be slain whatever, I also never claimed it did. All I said that it **"seems"** that he is at the wrong location, given that his boys "Giznash's Boyz," "Giznash's Big Basha" and "Giznash's Fighta" are all around the Big Trophy Pile.

**Comment by Lheana** [comment]
If you read the whole quest line, you'll understand why he is not near his boyz.
