### ISSUE TITLE
[Fortress] NullReferenceExpection SetPVPFlag

### ISSUE THREAD

**Issue by lilimx** [WarEmu/WarBugs#13623]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Hey,
quite after the fortress lord died, I've got this message (marked on the screenshot).
Btw. I didn't receive any Invader medaillons or roll and only ~4k RR, if this is related.

Keep: Butchers Pass
Date: 12/3/2019
Time of kill: ~14:00 CET

**Screenshots/Videos or archive.org evidences:**
![Lillet_106](https://user-images.githubusercontent.com/23266079/54203605-d8a4a300-44d2-11e9-938d-bee0c837de66.jpg)

**Comment by raptrr** [comment]
https://github.com/WarEmu/WarBugs/issues/13562

**Comment by Natherul** [comment]
This is a long time ago and I think all such issues have been fixed. If not please report back on a new ticket.
