### ISSUE TITLE
Range increase not applying.

### ISSUE THREAD

**Issue by DangerDanman** [WarEmu/WarBugs#13626]
**Expected behavior and actual behavior:**
I should gain an increase of 25% for path of changing on my magus with daemonic reach, Which put tzeeks sandstorm at 100 when i am standing near my pet on magus who increases me to 120 it doesn't budge. Instead the pet removes the daemonic reach bonus and slowly builds me back to 100 ft. So in conclusion daemonic reach + 8 stacks pet buff = 100 ft for tzeeks sandstorm. This is happening to all skills on magus. Including on my SH when i spawn my Gas squig his Path of quick shooting range bonus Vanish's.

**Steps to reproduce the problem:**
Go to Orvr Die Respawn Go to fight spawn pet and look at your reach on spells, This only happens sometimes infact over the last 3 days about a handful of times to me. Everytime you die it resets and either bugs up or does not, To fix re apply your tactics. IE RVR full pet stacks with 25% extra reach = a 120 tzeek storm and 98 ft on the pandomneum. Die respawn setup again and it may  only be 100 feet this time . No debuffs. I al;so notice after rez's it can bug up as well. My SH is afflicted with the same curse occasionally enough to notice.

**Screenshots/Videos or archive.org evidences:**
![Reach](https://user-images.githubusercontent.com/48450821/54225543-4a302180-44d2-11e9-9976-2d35293cda17.png)

**Comment by DangerDanman** [comment]
Invesitage the second tactic slot, I just swapped for chaotic attunement and put it in second slot. My pink horror now takes time to cast for some reason. It may be the second tactic slot bugging up my daemonic reach was there and so was my SH's path of the quick shooting range increase ability.

**Comment by grunbag** [comment]
Does it still happen ? I can’t reproduce

**Comment by DangerDanman** [comment]
I would have to log in to check, when it would happen I would die respawn summon pet and range would either be correct or not applying the tactic after. Sh did same to me with the range increase squig it would null the range tactic. I saw In patches a fix for some debuffs persisting after death could have been that without the debuff icon.

**Comment by grunbag** [comment]
Tactic have been fixed and refresh correctly now
