### ISSUE TITLE
Magus greenskin t2 influence rewards wrong?

### ISSUE THREAD

**Issue by wonderbloob** [WarEmu/WarBugs#1363]
It seems the Magus T2 influence rewards are incorrect. They prioritize stats like weapon skill, willpower, and initiative  instead of intelligence wounds or toughness.

**Comment by M0rf** [comment]
Just because the stats on certain items do not fit with how you or the class is intended to be played doesnt make them wrong.
Try searching on some of the warhammeronline db sites to make sure what you are claiming is correct.

**Comment by Evildoor** [comment]
I do believe this is one of the cases when logic should be favoured over  original stats in original game. Initiative is a fine defensive stat but WS and WIL are almost worthless to magus, so they should be replaced.

**Comment by M0rf** [comment]
I agree with u Evildoor, there are alot of items that have strange stats but the effort to change all these items and balance them on class mirrors to avoid the bias comments is very time consuming and i would think way down the list of things to do right now.

**Comment by wonderbloob** [comment]
When other classes like the zealot get a helm with 3 stats and 2% critical chance from their influence reward and the magus helm gets only 3 stats and no additional critical stat, it leads me to believe that the items may be incorrect/missing stats. I understand and agree that this is by no means a dire issue, but this website is designed to report bugs, therefore that's what I feel like I am doing.

**Comment by Evildoor** [comment]
Well, i'm not asking to fix all items in the game. The priority rather depends on the item's importance, so while PVE influence is not much of a deal, crucial PVP items (from PVP vendors, for example) are completely different story. However, even not important items deserve to be reported.

**Comment by wonderbloob** [comment]
agreed. and i believe the devs want to recreate this game to its entirety, meaning no report is too small!!

**Comment by Reggaewaldo** [comment]
Please provide the item name and I will look it over when I have the time.

**Comment by Ryanfawkez** [comment]
Most of these items were already altered to have initiative on them over weaponskill, I still had to edit the +10 and +14 weaponskill on Ironclad Whipsash and Karaz Whipsash to +10 and +14 initiative respectively.
