### ISSUE TITLE
Waargh! Frenzy bug

### ISSUE THREAD

**Issue by coconutman112** [WarEmu/WarBugs#13636]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Nobody knows what the "Waargh! Frenzy" tactic should be doing, but apparently the description intends to increase it's damage but it won't heal anymore.

**Steps to reproduce the problem:**

Equip the trait > hit mobs > see if the damage even changes

**Screenshots/Videos or archive.org evidences:**

![image](https://user-images.githubusercontent.com/48526197/54295512-870b1f80-4589-11e9-80dc-1a87047634c2.png)

**Comment by sioding** [comment]
Can you please add your testing screenshots from the combatlog? Thanks

**Comment by Scophis** [comment]
As far as I know this is a "relic" of the last shaman/AM-Mechanic, where you could cast ITT and FoDG on the move it you had build WAAAGH! Points. It dealt a fixed dmg value and added a WIL-based heal-component. With this tactic it would "only" deal dmg and heal via lifetap. With the reversal of this mechanic the tactic is atm useless. 
(I hope I didn't miss one of the many changes to Sham/AM-mechanic though)

**Comment by coconutman112** [comment]
Basically it works for Fury of Da Green but not I'll take that

I will take screen shots in a bit

**Comment by coconutman112** [comment]
![image](https://user-images.githubusercontent.com/48526197/54300371-19fc8780-4593-11e9-8d00-6e569f63ece0.png)

With tactic

![image](https://user-images.githubusercontent.com/48526197/54300436-3993b000-4593-11e9-8422-f532b9b05c09.png)

Without the tactic

**Comment by Scophis** [comment]
_Edited my prior comment_

Did some test and the only thing the tactic does, is to remove the base-heal of FoDG.
![FoDG1](https://user-images.githubusercontent.com/40274248/54303930-6318ff80-45c4-11e9-8617-a1d1f3fe4f40.jpg)
![FoDG2](https://user-images.githubusercontent.com/40274248/54303932-64e2c300-45c4-11e9-8da8-2875a9110b34.jpg)

ITT is not effected by it
![IIT](https://user-images.githubusercontent.com/40274248/54303968-762bcf80-45c4-11e9-8a55-b4b4bda924b6.jpg)

FodG isn't castable on the move at any time.
ITT is castable on the move only with "Gork-Waagh" Points, no matter if tactic is slotted or not

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 13.07.2019
