### ISSUE TITLE
Combat Hammer of the Smuggler can't be bought with Buckler of the Subjugator

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#13638]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

It should be possible to trade a Buckler of the Subjugator to a Combat Hammer of the Smuggler. But instead you need a Buckler of the Smuggler. And you can't buy a Buckler of the Smuggler with a Buckler of the Subjugator.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

![Lotharic_022](https://user-images.githubusercontent.com/7400/54315389-3671e180-45de-11e9-911a-c3978b66ca19.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
