### ISSUE TITLE
Sentry's heater of solemnity texture is flipped

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#13634]
**Expected behavior and actual behavior:**

The texture is flipped/mirrored horizontally on the Sentry's heater of solemnity. As it has the text "Myrmidia" on it it looks a bit odd when that is backwards.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

![InkedLotharic_016_LI](https://user-images.githubusercontent.com/7400/54280755-829a3300-4598-11e9-8bda-f04ce60642a6.jpg)
![Lotharic_020](https://user-images.githubusercontent.com/7400/54280767-875ee700-4598-11e9-9c29-8dbff1f267ab.jpg)

**Comment by wargrimnir** [comment]
Maybe that's so they can see you coming in their rearview mirror.

Good eye.

**Comment by dalen** [comment]
Fixed for next patch

![image](https://user-images.githubusercontent.com/7400/81542166-82e8b680-9374-11ea-8d1a-ca31a9f1b7aa.png)

**Comment by Kaelang** [comment]
Fixed as of 13/05/2020 patch. Please re-open if issue persists.
