### ISSUE TITLE
[Quest] 'Meeting da Quota' and 'Spider Legs'

### ISSUE THREAD

**Issue by bealmador** [WarEmu/WarBugs#13630]
Exactly the same problem as described here: https://github.com/WarEmu/WarBugs/issues/13615 just with different quests in a different area. The problem seems to be related to roaming mobs.

**Expected behavior and actual behavior:**
The quest requires you to hunt down a mob, get the item it drops and return to the quest giver. However, I am unable to find the mob.

Also, the quests only reward 140-160 experience. Other quests in the area reward experience in the range from 9,000 to 18,000. It also shows the quest as completed on the map, but the quest is not completable and the items required are also still showing as 0/1.

*Note: Even though 'Dirty Rotten Crawlas' seems to be related/linked to this (same quest giver, same little 140 exp and also showing as completed on the map before it's actually completed) this quest is completable!*

**Steps to reproduce the problem:**
Pick up the quest and try to acquire the item by killing the (nonexisting) mob that drops it.

**Screenshots/Videos or archive.org evidences:**
![Capture](https://user-images.githubusercontent.com/39677933/54249279-cf9deb00-453f-11e9-8fc2-39e174b9a0f0.PNG)
![Capture2](https://user-images.githubusercontent.com/39677933/54249282-d3317200-453f-11e9-9e49-2c277d7691a3.PNG)
![Capture4](https://user-images.githubusercontent.com/39677933/54249284-d6c4f900-453f-11e9-9607-45eae6b0e45b.PNG)

**Comment by dalen** [comment]
The low XP seems to be a problem on all the Apothechary quest givers on both factions.

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 15.06.2019

**Comment by sioding** [comment]
fixed with patch from 22.6.2019
