### ISSUE TITLE
WB buged

### ISSUE THREAD

**Issue by Elflord123** [WarEmu/WarBugs#13637]
I ran the WB, and when the server lag, there was this bug, I can't get out of the WB and be the animation on the group. Although I am in the WB. After a request that would have kick me. the problem of group display to the left has not disappeared.
![image](https://user-images.githubusercontent.com/48329663/54310434-68d20d80-45e3-11e9-8d5d-e566058489d9.png)
![image](https://user-images.githubusercontent.com/48329663/54310455-77202980-45e3-11e9-90a4-67182c1a94bc.png)
![image](https://user-images.githubusercontent.com/48329663/54310493-87d09f80-45e3-11e9-84cd-1a5697bd856d.png)

**Comment by sioding** [comment]
Well - when this happens inside a big lagspike - it will be hard to reproduce it. If someone can add more informations how this would be reproducable - it would be great. Did a relog fixes everything?

**Comment by Elflord123** [comment]
Yes, after the relog everything was fine.
I was able to reproduce it twice. It was the second time, the first was on my choppa. I died, but could to flee, but could not attack. The symptoms were still the same, which I wrote about above
Also, when the movement appeared and disappeared inscription: + combat-combat, and the death timer would resume.

![image](https://user-images.githubusercontent.com/48329663/54419245-062e5e00-4718-11e9-85be-a5c7c0bc97a9.png)
![image](https://user-images.githubusercontent.com/48329663/54419317-2d852b00-4718-11e9-9303-59cc4c15f30f.png)
![image](https://user-images.githubusercontent.com/48329663/54419343-3e35a100-4718-11e9-8274-689ff85d8ec0.png)

**Comment by sioding** [comment]
Well the second issue you decribed is completly different than the first one. Sorry but this doesn't help at all. I'm thankfull for every report that is made but it should be stick at the topic and we should be able to reproduce it - otherwise we have a bunch of "weird" things we can not get fixed.

**Comment by sioding** [comment]
No answer since 13 days. close
