### ISSUE TITLE
Fortress portal uses reservation even if you can't enter because you are in combat

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#13644]
**Expected behavior and actual behavior:**

When trying to enter fortress in combat, you get an error message, but your reservation is still used. After that you can't enter.

**Steps to reproduce the problem:**

1. Get a fortress reservation
2. Get in combat
3. Click fortress portal

**Screenshots/Videos or archive.org evidences:**

![Lotharic_026](https://user-images.githubusercontent.com/7400/54357984-952b6f80-465f-11e9-8190-0c859844c9b8.jpg)

**Comment by dalen** [comment]
Haven't verified it, but this was fixed by hotfix 3 and can be closed, right @Natherul?

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
