### ISSUE TITLE
[quest] thorns

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#13648]
griffon cannons are unattackable
![Orkodisel_007](https://user-images.githubusercontent.com/17765890/54377773-26154180-4686-11e9-9d8b-9c63fdf0e50d.jpg)
![Orkodisel_008](https://user-images.githubusercontent.com/17765890/54377772-257cab00-4686-11e9-8122-7236945c326a.jpg)
keg's working fine

**Comment by Kabucoror** [comment]
fixed with next patch. pay attention now to the correct objective order ;)

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
