### ISSUE TITLE
Attacks are always parried while jumping

### ISSUE THREAD

**Issue by Elflord123** [WarEmu/WarBugs#13646]
Randomly I went on your Twinkie, and he was in the lair of the boss. Wanted to kill myself about it, and resp in the wc. However noticed a pattern: If you jump while you attack the boss, then the whole attack is parry. Thus I alone, constantly hitting the space key and the attack, brought the boss up to 76%. While I didn't kill order sm. 

![image](https://user-images.githubusercontent.com/48329663/54367068-d1bc9280-4682-11e9-9cb6-4fbd1c2bbda5.png)
![image](https://user-images.githubusercontent.com/48329663/54367125-eac54380-4682-11e9-833b-5210efa7f131.png)

**Comment by sioding** [comment]
Did you tested it on other npc´s too? can you add some screens from these tests?

**Comment by Elflord123** [comment]
No, I didn't manage to repeat it on other NPCs, but it was amazing

**Comment by sioding** [comment]
No answer for 29 days. Close

**Comment by Elflord123** [comment]
I can't try this. Interesting bugg
