### ISSUE TITLE
[SW] Assault Stance - All Ballistic Skill bonuses not converted to Strength

### ISSUE THREAD

**Issue by CrimsonFenris** [WarEmu/WarBugs#13642]
**Expected behavior and actual behavior:**
Expected : Ranged bonuses from items being converted in Melee bonuses, ie. Ballistic skill to Strength.
Actual behavior :  Missing Bonuses from items (not converted from BS to Str).

**Steps to reproduce the problem:**
Equip Gear and bonuses, stats are missing in Strenght.

**Screenshots/Videos or archive.org evidences:**
I should get at least 854 Strength total: 
172 (base) + 442 (BS from gear+set bonuses) + 120 (Instinctive Aim) + 120 (Stance bonus) = 854.
There are 55 ballistic skill bonus not converted to Str for some reason...
For information I run full Conqueror, 3 pieces Beastlord, Subj. weapons, the 3 Genesis jewelry you see on picture, and one +20 BS talisman.
No renown invested in either Ballistic or Strength abilities.

![Tanaryon_bugassault1](https://user-images.githubusercontent.com/40425011/54351260-686f5c00-464f-11e9-9541-6f83f07429b9.jpg)

**Comment by grunbag** [comment]
Unequip pièce one by one and try to find which one is not converted

**Comment by CrimsonFenris** [comment]
My bad. I redid calculations and found I confused the WS bonus from beastlord 3 pieces to BS, so the 55 pts difference...
All gear bonus is working fine with assault stance.

You can close the thread, sorry for the false alarm... :/
