### ISSUE TITLE
RP (Tactic Bugged?) Immolating Grasp

### ISSUE THREAD

**Issue by Jubok22** [WarEmu/WarBugs#13643]
The Tactic say: Each tick of Rune of Immolation has a 25% chance to drain 30 Action Points from the target and snare them by 40 % for 5 secends.

but it proc only if i cast em on enemy not got a chance to proc with each tick of the dot.

Test it now on the Dummys but its not proc  if the dot is allready on a player... only the first cast can proc.

and thing its not drain AP too.
![RP DOT TEST](https://user-images.githubusercontent.com/32957323/54354624-6c06e100-4657-11e9-9a87-90514e8a178d.png)

**Comment by grunbag** [comment]
![immolating grasp](https://user-images.githubusercontent.com/24207191/54456926-50d3c880-4760-11e9-9dc8-c13a6e5ea4b1.png)
i just tested and it works fine
