### ISSUE TITLE
[FORT] Reset

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#13649]
Dwarven fort have reseted as Maw fort (which was done in same time) ended.
As encounter with phases worked till last phase - SoR stoped recongnising Stonewatch as active after Maw locked (middle of second stage), which I assume means that objectives like doors and ETC stopped spamming in system chat for SoR to pick up data, and that means that zone was falsely active after Maw ended.

**Comment by MaxHayman** [comment]
I looked at the logs and should have fixed the thing which caused this.

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
