### ISSUE TITLE
[PQ] Blind Justice Hard Public Quest Dark Elf Chapter 21 | Rank 39 | Advanced Rewards 

### ISSUE THREAD

**Issue by D4W0lf** [WarEmu/WarBugs#13641]
I tried to go to this PQ to farm, as I've done with my Chosen a couple years ago or more, the Ruin set.
But when I was arrived, there was nobody and nothing start. No timer, no mob to kill, nothing...
Have I forget or miss anything ?

**Comment by Lheana** [comment]
Try to walk inside the PQ, leave it and come back.

**Comment by sioding** [comment]
No answer since 14 days. close
