### ISSUE TITLE
Throwing arm tactic ocassionally not initialising

### ISSUE THREAD

**Issue by Jerloldrartolf** [WarEmu/WarBugs#13657]
**Expected behavior and actual behavior:**
When tactic = throwing arm is equipped, grenadier ability should be increase 35% range.
In screenshot, I have 65ft range for Napalm, and this is default without tactic.

The range if the tactic was working = 81ft.

This is for all grenadier abilities, but I used napalm as an example for the screenshot.

This is not only GUI as when planting the napalm, the range is the same as my LandMine, which is 65ft.

Tactic is equipped in RVR.
I am near my turret as from screen shot, I have 8x damage as proof I am in range of turret.

**Steps to reproduce the problem:**
Not sure.
Think tactic initialises on entering a region  or RVR area so could be something to do with entering a zone or RVR area.(Pure speculation)

Workaround is to unequip and ReEquip tactic.
screenshot attached.
![WH rangeissue](https://user-images.githubusercontent.com/48033566/54477194-65b26980-47fd-11e9-9b4e-51e19d5bf2c3.png)

**Screenshots/Videos or archive.org evidences:**

**Comment by grunbag** [comment]
What turret do you use ?

**Comment by Jerloldrartolf** [comment]
Apologies for not including this.
Bombardment turret.
From the screenshot, you can see 8x bonus so I am within range of this turret.

**Comment by grunbag** [comment]
Ok , try to use a grenade on target dummies at max range without the tactic sloted . Then equip the tactic and try the same grenade a bit further

**Comment by Jerloldrartolf** [comment]
just to be sure, the tactic does work, 
Also, the tactic does seem to work even when I don't have a turret.
just sometimes when I have a look, it doesnt seem to have initialised.
I will do some test, 
changing zones, using book, using book from rvr zone,
respawning and checking after respawn etc.

screenshot below just to show that lack of turret has no effect on range.
![WH rangeissue](https://user-images.githubusercontent.com/48033566/54477694-f8ed9e00-4801-11e9-9317-0591964a9c02.png)

**Comment by Jerloldrartolf** [comment]
I was killed in battle and respawned in WC. Range =65 as per screenshot below.
![WH rangeissue](https://user-images.githubusercontent.com/48033566/54477756-8af5a680-4802-11e9-8832-15de0505dec2.png)
I then built a turret and range is still 65.
![WH rangeissue2](https://user-images.githubusercontent.com/48033566/54477802-0d7e6600-4803-11e9-9f97-bc88d81689e1.png)

So seems like throwing arm is not initializing properly after respawn?

**Comment by grunbag** [comment]
Throwing arm is not linked to your turret

**Comment by grunbag** [comment]
![A76AB035-C82E-43C1-B8AA-78E797D25AA5](https://user-images.githubusercontent.com/24207191/54478178-ba5ee000-480f-11e9-9021-fe5ca40966d5.jpeg)
![9AA65806-24DE-4D7D-803F-5A103966E1B0](https://user-images.githubusercontent.com/24207191/54478180-baf77680-480f-11e9-803f-c52b9a080362.jpeg)
You are probably mistaken with gun turret

**Comment by Jerloldrartolf** [comment]
thanks, So the issue exists outside of the turret.
I will do the testing without the turret then. 
Incidentally, the description does not match the description I have on my client.

![WH rangeissue2](https://user-images.githubusercontent.com/48033566/54478280-4836cd00-4808-11e9-9385-90165e2a07f4.png)

**Comment by grunbag** [comment]
yes tooltip is not updated

i tested right now and grenade are 81ft range with throwing arm
![flashbang](https://user-images.githubusercontent.com/24207191/54478316-fe061980-4810-11e9-85e9-d2c30fa07c38.png)

**Comment by Jerloldrartolf** [comment]
yes. it fails to boost occasionally.
I just did a quick travel and was working.
As per screenshots it does occur. 
But can you assign to me for steps to repro. Having trouble figuring this one out and may be a while.

**Comment by grunbag** [comment]
i can't reproduce, when this exactly happens?
