### ISSUE TITLE
Genesis set of the Everlasting should be allowed for WP/DoK

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#13655]
**Expected behavior and actual behavior:**

As WP and DoK can have shields now, it would be good it the genesis set of the everlasting was changed to also be available for those classes.

Not entirely sure if the current situation is intentional or just something that was missed when changing DoK & WP. But as it might be the latter I'm reporting it as a bug.

**Comment by sioding** [comment]
Sorry dalen but the BT is not for suggestions. Please use our forum for this. https://www.returnofreckoning.com/forum/viewforum.php?f=15

**Comment by dalen** [comment]
Created a forum topic instead: https://www.returnofreckoning.com/forum/viewtopic.php?f=15&t=30822
