### ISSUE TITLE
Talisman replacement

### ISSUE THREAD

**Issue by Stinkypants** [WarEmu/WarBugs#1365]
I was not able to place a new talisman over my old one in my current gear.  Only truly problematic for the rvr influence items that you can only receive once. I think it's supposed to be that you can plop a new talisman in but it will destroy the old one.

**Comment by M0rf** [comment]
i had no problem replacing armor talis with toughness talis on my gear, both vendor and rvr influence, i suggest relogin or moving the tali/item u are trying to slot it in around in your inventory.

**Comment by magter3001** [comment]
Are you trying to put a level 20 tally in <20 gear?

**Comment by Evildoor** [comment]
What's the state of this problem? It still persists? None of the comments above helped?
Also - when a problem with talisman windows occurs, i suggest completely exiting the game and launching it again rather than just logging out and back in. This was the case for me several times.

**Comment by Stinkypants** [comment]
The window is buggy but I found I was accidently putting in too high a level talisman for the gear. I thought it was the character level that responded to the level of talisman.
