### ISSUE TITLE
[weapon] Mara and Chosen reward of PQ Ch10 in BFP

### ISSUE THREAD

**Issue by elk76** [WarEmu/WarBugs#13651]
Time ago, the last reward for Marauder and Chosen of PQ Ch10 in BFP was a one-hand axe with broken stats (2-handed axe dps)
this was fixed some patches ago (issue #13311) changing the axe from one-hand to 2-handed
now the marauder cannot use it
this axe should be a one-hand axe with appropriated stats

**Comment by wargrimnir** [comment]
Screenshot please

**Comment by elk76** [comment]
this is the weapon before the fix
![Eyvind_059](https://user-images.githubusercontent.com/46483570/54471558-4abf0580-47bb-11e9-92c5-c8de08d1466c.jpg)
this is the weapon after the fix
![Eyvind_101](https://user-images.githubusercontent.com/46483570/54471569-688c6a80-47bb-11e9-9564-487aed954d11.jpg)
![Hamund_041](https://user-images.githubusercontent.com/46483570/54471571-6c1ff180-47bb-11e9-9f6e-89a03a336ed5.jpg)

in addition, atm the wepona is a 2-hands weapon with 1-hand appearance
![Eyvind_072](https://user-images.githubusercontent.com/46483570/54471598-ad180600-47bb-11e9-91c8-64aa7974bb4d.jpg)

**Comment by NorKalli** [comment]
set to 1h, stats/dps adjusted accordingly

**Comment by sioding** [comment]
Fixed with patch from 11.05.2019
