### ISSUE TITLE
Fort - resp bag

### ISSUE THREAD

**Issue by Elflord123** [WarEmu/WarBugs#13659]
If you get to the area of the Fort is not through the portal (checked on the basis of the past issues https://github.com/WarEmu/WarBugs/issues/13567 ). Then resurrected on the 3rd floor, not in a cage
![Elflord_034](https://user-images.githubusercontent.com/48329663/54480758-8dc1bd00-483d-11e9-9daa-06078bbe579f.jpg)
![Elflord_033](https://user-images.githubusercontent.com/48329663/54480761-931f0780-483d-11e9-9682-9fc36135a08c.jpg)

**Comment by sioding** [comment]
Thanks for the report we have a pending fix for that.

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
