### ISSUE TITLE
Elve campaign doesn't lock properly to fort

### ISSUE THREAD

**Issue by Dottina** [WarEmu/WarBugs#13653]
Not lock and loot bag in Caledor ,Fort not open

**Comment by Dottina** [comment]
![image](https://user-images.githubusercontent.com/33136435/54473614-64bc1080-47da-11e9-8c7f-accf463824cc.png)

**Comment by raptrr** [comment]
https://github.com/WarEmu/WarBugs/issues/14608

**Comment by Natherul** [comment]
this was long time ago and I think all such issues has been fixed if not then please open a new ticket.

Just note however that if a realm locks 2 fortresses then the entire campaign does reset and any active zones will close with no rewards.
