### ISSUE TITLE
[Quest] Eaten Away

### ISSUE THREAD

**Issue by knthrak** [WarEmu/WarBugs#13654]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Quest hand-in point is NPC Faldan Roughwold.  NPC is hostile NPC at the top of the relevant belltower.  After killing and looting NPC in part of two quest does not update and hand-in icon remains over the body of Faldan Roughwold until it respawns as a hostile again

**Steps to reproduce the problem:**
Travlled to belltower target area, fought up the twoer completing all required kills of rotting x mobs.  NPC is at top of tower to hand quest in, orange dot for hand in appeared.

**Screenshots/Videos or archive.org evidences:**

![Capture](https://user-images.githubusercontent.com/48619966/54474424-abd8ee80-4838-11e9-9637-48919ada42f6.PNG)

**Comment by Lheana** [comment]
For this step you are not meant to kill him, you are meant to talk to him. To do so, search for him on the floor just below.

**Comment by Bloodlet** [comment]
This is still happening.

**Comment by Lheana** [comment]
He is
![Lheanaa_004](https://user-images.githubusercontent.com/11537611/84872398-24ed7400-b082-11ea-910e-fb176c65bdc2.jpg)

**Comment by Bloodlet** [comment]
That's not the floor "just below". The floor just below has one staircase, cannons all around, one small side room with 3 mobs in the main room and one in the small side room.

**Comment by Lheana** [comment]
As a reminder, **the Bugtracker is made for issues, it is not a game support**. I was nice to give clues about where to find the NPC, but if you aren't able to search in a tower for an NPC, I can not do anything for you.
