### ISSUE TITLE
[Buff] Fierceness stack with set proc

### ISSUE THREAD

**Issue by funnytroll** [WarEmu/WarBugs#13656]
Is it right that skill fierceness(102 ws) stacking with vanq proc on sly (110 ws) ?
https://youtu.be/_3tyPQXrnxk

**Comment by sioding** [comment]
Can we please see some .getstats output cause the paperdoll ist really reliable.

**Comment by funnytroll** [comment]
Getstats show only strong proc,you can close issue.

**Comment by sioding** [comment]
nice - thanks
