### ISSUE TITLE
Tank Invader set bonus 6 and 7

### ISSUE THREAD

**Issue by gomdor38** [WarEmu/WarBugs#13667]
hey I´m Gazuaa the Black Orc.
Here report about issues of Tank Invader.

·Invader set bonus 6 - It seems not properly triggered, lower than 10% as shown in video.
                                    ( Popped on 19th-30th block in the video )
·Invader set bonus 7 - Seems not working as in video.

Video link
https://youtu.be/2u7ZmauZ18A

**Comment by grunbag** [comment]
I can’t watch your video. I just tested tank 7pc and it worked fine

**Comment by sioding** [comment]
Video link corrected - but when grunbag said he tested it and it works - no need to hold this one open.

**Comment by grunbag** [comment]
On you’re video i can see mending wounds proc

**Comment by grunbag** [comment]
![mending wounds](https://user-images.githubusercontent.com/24207191/54515744-4d596080-495d-11e9-8c75-31ef470e2053.png)
![shield spikes](https://user-images.githubusercontent.com/24207191/54515745-4d596080-495d-11e9-823b-ae443b48b941.png)
