### ISSUE TITLE
hold the line 

### ISSUE THREAD

**Issue by footpatrol2** [WarEmu/WarBugs#13666]
Hold the line ability should not be limited to the AoE limit of 9 player's. It did not act like this on AoR.

At the moment hold the line is limited to 9 player's.

Hold the line had no limit on how many player's it could affect. It was only limited by it's directional cone.

**Comment by sioding** [comment]
Any proof for this?

**Comment by grunbag** [comment]
on live there was no target cap, we chose to cap it to 9 targets on RoR.
