### ISSUE TITLE
Double inf in Sigmar Crypts didnt count in inf bar

### ISSUE THREAD

**Issue by Doenny** [WarEmu/WarBugs#13669]
Hi,

we just finished crypts now, when the double xp inf rp event was extended, we saw after kill each boss the double inf text pop 2x1000 inf, but when we checked inf bar, it counted only as 1000 inf.

Is there a way to refund it? Its obvious with the extension event the crypts were not affected.

Here is the screenshot of server time, our party and inf bar.
https://imgur.com/a/n4B2YZQ

Thank you

**Comment by sioding** [comment]
This is a design decision. We do not add more influence in dungeons when x2 weeks or days are running.
