### ISSUE TITLE
Challenge shout

### ISSUE THREAD

**Issue by footpatrol2** [WarEmu/WarBugs#13660]
Challenge shout ability should not be limited to the AoE limit of 9 player's. It did not act like this on AoR. 

At the moment challenge shout is limited to 9 player's. 

Challenge shout had no limit on how many player's it could affect. It was only limited by it's directional cone.

**Comment by sioding** [comment]
Any proof for that?

**Comment by sioding** [comment]
No answer for 27 days. Close
