### ISSUE TITLE
Minor bug: [KotBS] Emperor's Champion: Incorrect duration/tooltip information

### ISSUE THREAD

**Issue by Jaboody** [WarEmu/WarBugs#13665]
**Expected behavior and actual behavior:**
The tooltip indicates the morale 2 working for 30 seconds, but in actuality the duration in-game is around 15 seconds. 

I am not sure if the spell is supposed to last so long (30 seconds on a 1 minute cooldown, sure seems like a lot) or if the tooltip information is just incorrect.

**Comment by fierdal** [comment]
I tested it as well its only 15 secs so tool text is wrong.

**Comment by Evilmariel** [comment]
Tooltip still shows 30seconds and buff duration is only 15 seconds. Which is correct?
