### ISSUE TITLE
Eatine respawn in bottom floor, WE's camping abuse

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#13664]
**Expected behavior and actual behavior:**
I have been respawning on the Eatine Arbor of Light keep bottom floor instead of the 2nd floor.  3 we's are seen hear abusing.

**Steps to reproduce the problem:**
die in rvr near Arbor of Light as Order.

**Screenshots/Videos or archive.org evidences:**
https://ibb.co/wrmQHL3

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
