### ISSUE TITLE
SH: All By Myself NOT WORKING 

### ISSUE THREAD

**Issue by freshour** [WarEmu/WarBugs#13671]
**Expected behavior and actual behavior:**
It should boost your damage by 25%. It is not doing anything

**Steps to reproduce the problem:**
Slot tactic, watch nothing happen

**Screenshots/Videos or archive.org evidences:**
NOT SLOTTED 
https://imgur.com/WbmtOE4
[img]https://i.imgur.com/WbmtOE4.jpg[/img]

SLOTTED
https://imgur.com/gg3UtH6
[img]https://i.imgur.com/gg3UtH6.jpg[/img]

**Comment by grunbag** [comment]
Do you have territorial aggression sloted ?

**Comment by grunbag** [comment]
Fixed for next Patch

**Comment by freshour** [comment]
I did not have territorial aggression on.  In that picture I had the tactic that increases str/ws/bal and reduces toughness + shootin with da wind.

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
