### ISSUE TITLE
Inability to use Mastery Path Career Tactic (AM)

### ISSUE THREAD

**Issue by Archon1012** [WarEmu/WarBugs#13675]
I have checked the other threads, as well as looked upon the Forums but found nothing that addressed the issue I wish to present. I apologize beforehand for any oversight on my end in that regard. 

After reaching a high enough level with my Archmage I proceeded to invest in the Path of Isha mastery tree. The first available node is the "Bolstering Boon" 

Upon acquiring the career tactic it was immediately blacked out and told me "This ability is not usable at your current level." The required level for the Tactic continues to change, but at maximum it is always a level below what I am. The next ability after it, "Magical Infusion" works without any problems whatsoever. I tried to see if it was related to a Mastery Path bonus I received from gear, but that wasn't the case. The only time it worked properly was when I received a bolster from entering oRvR.

I've made screenshots and hope they help in some way. 

I re-specialized once more to see if the issue was on my end. It told me the level required was 18
![Celenor_006](https://user-images.githubusercontent.com/48692102/54553824-5bd26700-49b3-11e9-91ec-a9c9d91eb0f0.jpg)

I purchased the tactic, now at level 19, telling me It isn't usable at my level.
![Celenor_007](https://user-images.githubusercontent.com/48692102/54553834-5ffe8480-49b3-11e9-8076-0ef7d95b3d87.jpg)

I purchased Magical Infusion, it immediately entered the bar and could be used without an issue.
![Celenor_008](https://user-images.githubusercontent.com/48692102/54553847-64c33880-49b3-11e9-8a78-c9330e440ca4.jpg)

This is what is looks like for me now. Level requirement 21, and still greyed/red and unable to use it.
![Celenor_009](https://user-images.githubusercontent.com/48692102/54553854-68ef5600-49b3-11e9-8b88-65a6374b1091.jpg)

Thank you for your time.

**Comment by Rydiak** [comment]
Just for clarification, ability level is not the same as level requirement.  Most likely is the tactic has an erroneously high level requirement, like 25+, but that won't show on the tactic itself.  Probably from before recent changes to AM mastery trees.

**Comment by Archon1012** [comment]
I see. Please forgive the misunderstanding then. I hope this was helpful in some regard nonetheless.

**Comment by Jerloldrartolf** [comment]
Similar issue with Shaman - Pass it on. I can purchase it as a rank 17 but cannot use even though tooltip says it is level 17.

**Comment by Kaelang** [comment]
As of 22/04/2020 this should have been fixed. Please re-open this report if you find you are still having issues.

- Edited some Level requirements on spec abilities tooltip from Ror made abilties . This caused some abilties to turn red even if they were accessible.
