### ISSUE TITLE
Sanctified Ground quest in Ostland

### ISSUE THREAD

**Issue by aesoprockzz** [WarEmu/WarBugs#13672]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Last step of the quest you have to defeat Tomas the Champion and restore the statue... but the statue isn't clickable. It highlights, but it doesn't interact at all. https://i.imgur.com/NvavvHO.jpg

**Steps to reproduce the problem:**
Last step of the quest you have to defeat Tomas the Champion and restore the statue... but the statue isn't clickable. It highlights, but it doesn't interact at all. https://i.imgur.com/NvavvHO.jpg

**Screenshots/Videos or archive.org evidences:**
https://i.imgur.com/NvavvHO.jpg

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
