### ISSUE TITLE
Harbinger of Doom ability bug.

### ISSUE THREAD

**Issue by Gygrax** [WarEmu/WarBugs#13676]
I think I found a bug with the Zealot's Harbinger of Doom ability. Whenever I zone in to another area, while Harbinger of Doom is still active from the previous zone, it would auto convert back to healing stats instead of dps stats. I have to toggle off and toggle back on in order to get back the dps stats again. Plus it is not emitting Harbinger of Doom powering sound effect.

With buff active and correct stats
![Bug example 1](https://user-images.githubusercontent.com/48693166/54556133-983f9c00-498e-11e9-8f6e-25ab79d0a573.png)

Zoned into another area with reverted healing stats while buff is active.
![Bug example 2](https://user-images.githubusercontent.com/48693166/54556178-b3121080-498e-11e9-9b8a-21faa07fedcc.png)

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 03.08.2019
