### ISSUE TITLE
[Ability] Hold the line! keeps failing to activate

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13670]
During the PvP fight this evening the activation of "Hold the line!" failed countless times. Every time it happened a debug message appeared in the chat (see picture). Sometimes several seconds passed until I could activate it.

![Moragor_001](https://user-images.githubusercontent.com/30193675/54498521-e5792a80-4908-11e9-9e99-71540d6d3089.jpg)

**Comment by grunbag** [comment]
fixed already
