### ISSUE TITLE
immortal bound & gagged

### ISSUE THREAD

**Issue by pew1** [WarEmu/WarBugs#13687]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Died close to the red zone blocker in butcher pass when i press release i didnt go to jail just instant ressurection on the spot nobody can hurt me but i cant use any abilities even book.
You are bound and gagged message every time. Even tried the cage lever nothing.

**Steps to reproduce the problem:**
Try and die very close to the red zone blocker butcher pass near the attacking side portal.

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment]
Any screenshots from it?

**Comment by sioding** [comment]
No answer for 24 days. Close
