### ISSUE TITLE
Login Server Connection Issue

### ISSUE THREAD

**Issue by Deadto0** [WarEmu/WarBugs#13686]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
For the past day I could not connecto to login server and have resinstalled the game and it seems that I can not connect is there a fix for this??

**Steps to reproduce the problem:**
Reinstalled and Restarted PC

**Screenshots/Videos or archive.org evidences:**
![2019-03-19](https://user-images.githubusercontent.com/48745875/54661026-ea1f1980-4a95-11e9-8446-13a373ce0ded.png)

Could not connect to Login server

**Comment by xSheet** [comment]
have you tried connecting through a vpn?

**Comment by sioding** [comment]
Sorry but the bugtracker is only for ingame bugs. You can find some help while using our forum: https://www.returnofreckoning.com/forum/viewforum.php?f=4
