### ISSUE TITLE
Eidolon's Armor never spawns

### ISSUE THREAD

**Issue by darksoulscrazed** [WarEmu/WarBugs#13681]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Pretty sure this dude's supposed to have clothes. Is it a phase or something?

**Steps to reproduce the problem:**
I entered the area after playing the Ruinous Powers public quest a few times. The Eidolon spawned, but his armor didn't. I tried to wait a while to see if they would eventually spawn, but after a good few minutes they were still missing

**Screenshots/Videos or archive.org evidences:
![Screenshot (3)](https://user-images.githubusercontent.com/48695417/54631359-3d6f7880-4a52-11e9-9026-1ad60c6f24f1.png)
![Screenshot (4)](https://user-images.githubusercontent.com/48695417/54631368-43fdf000-4a52-11e9-90b7-28be3e2ff213.png)
![Screenshot (5)](https://user-images.githubusercontent.com/48695417/54631428-60019180-4a52-11e9-8e20-7f60318e83fb.png)

**

**Comment by Kabucoror** [comment]
It is only a visual thing, like sometimes players appear naked.
