### ISSUE TITLE
Fortress in Butcher's Pass will load you to IC

### ISSUE THREAD

**Issue by Carnagehunts** [WarEmu/WarBugs#13688]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

3/19/2019 Butcher's Pass Pifen Chosen rr54

I died during the flag stage in Butcher's Pass. After respawn I was in third floor of keep when as soon as I moved was immediately teleported to Inevitable City. I then tried to go back to portal and keep playing in fort, but to my surprise it acted as if I had no reservation for being removed from fortress run. 

**Steps to reproduce the problem:**

Die during flag stage, respawn in Butcher's Pass keep and move. I did nothing else and bam ported to Inevitable City. Mind you not the reservation teleport, I got moved to my bind location as if I had used my book to leave, which I didn't.

**Screenshots/Videos or archive.org evidences:**

I can't put screenshots of a loading screen.

**Comment by Natherul** [comment]
the only time a teleport would happen in the version before test was either on zone in for the first time into a fort zone OR if you triggered the afk mode. Either way its been removed  since of the test and should it happen again please make a new ticket with as much information as possible
