### ISSUE TITLE
WP/DOK Redeye 4pc Bonus

### ISSUE THREAD

**Issue by edavoc** [WarEmu/WarBugs#13682]
At the moment the 4 piece bonus for redeye, (armor buff), is far too low for its place in the set and its item level. For a comparable bonus the mercenary set, for these same classes, is 472 armor for the 3 piece, while redeye is 264 armor for a 4 piece. Mercenary is a lower item level and a lower required bonus it should not have a higher value then redeye. 
Since I don't know the calculation for allocating the stats on item sets I can not verify that the bonus is wrong, but in relation to the only other set with armor as a bonus this value looks incorrect. 
![Ludwicht_006](https://user-images.githubusercontent.com/16967436/54646185-b1bb1380-4a74-11e9-9059-6c1bdb7352cf.jpg)
I think the bonus should be at least 500 armor maybe 550 due to also being a 4 piece instead of a 3.

**Comment by wargrimnir** [comment]
Definitely low.

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
