### ISSUE TITLE
problem with the reputation points in the inexorable city.

### ISSUE THREAD

**Issue by lucasspipperi** [WarEmu/WarBugs#13685]
when I'm in the inexorable city, and I reset the reputation points, first I will not let myself get more points, and second when I respecialise all the points were erased, I have nothing, I thank the help from now on.

**Comment by sioding** [comment]
Well - read this more than one time but i do not get it. Can you please try to explain it in other words - maybe screenshot would help.

**Comment by Jerloldrartolf** [comment]
I think the issue is that on occasion, if you leave the RP training window open for too long, it times out and then clicking the respec button does not take effect.

**Comment by Scophis** [comment]
Maybe something like this? #13603

**Comment by sioding** [comment]
No answer for 24 days from OP. Close
