### ISSUE TITLE
Magus Soul Leak is to weak a morale 4 to be worth anything.  No one uses it.

### ISSUE THREAD

**Issue by Neutrinoo** [WarEmu/WarBugs#13695]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by Neutrinoo** [comment]
The Magus Morale 4 Soul Leak in the Havoc tree is never slotted.  It's too weak for the time it takes to apply.  Can you amp up the morale and make it worth slotting?


![image](https://user-images.githubusercontent.com/18320036/54798045-1d47e100-4c2d-11e9-80fb-6a674ae6a163.png)

**Comment by sioding** [comment]
The bugtracker is not for suggestions. Please use our forum.
