### ISSUE TITLE
Auction house issue

### ISSUE THREAD

**Issue by nohh** [WarEmu/WarBugs#13693]
I lost some dominator items on AH. Instead, I see several other items that I did not put up for auction, and moreover, I can not cancel this auctions. Errors in the chat window when I try to cancel.

![auction_error](https://user-images.githubusercontent.com/19315739/54778893-e4a50900-4c26-11e9-9593-b098451851ec.jpg)

**Comment by sioding** [comment]
Duplicate of #12925
