### ISSUE TITLE
[quest] Echoes of War - Order.  Finuval Plains?

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#13698]
**Expected behavior and actual behavior:**
NPC Fenrelis Minithain, Avelorn
Actual - this quest task asks the player to participate in the battle of Finuval Plains..  '
Expected.  I'm not sure..  Maybe they meant Reikland Hills?

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**
https://ibb.co/Vgm8X26

**Comment by dalen** [comment]
Likely a scenario that was never fully implemented on live, like Black Crag Fort.

**Comment by Kabucoror** [comment]
Deactivated this quest for now with next patch

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019

**Comment by grunbag** [comment]
This Scenario is Lost Temple of Isha, Funival Plains is an old name for this scenario

**Comment by sioding** [comment]
@Kabucoror back to you

**Comment by Kabucoror** [comment]
Quest is back with next patch and has the right name

**Comment by sioding** [comment]
Fixed with patch from 13.04.2019
