### ISSUE TITLE
Shut Yer Face (silence)

### ISSUE THREAD

**Issue by theHalta** [WarEmu/WarBugs#13709]
The silencing ability Shut Yer Face does not silence spells.

https://clips.twitch.tv/AliveTransparentUdonDogFace
You can see the orange hand icon, that's Healing Hand. I cast it on both myself and the runepriest while silenced.

**Comment by grunbag** [comment]
Fixed at next patch

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019

**Comment by grunbag** [comment]
Fixed for next patch

**Comment by sioding** [comment]
Fixed with patch from 27.04.2019
