### ISSUE TITLE
Griffon Outpost bugged

### ISSUE THREAD

**Issue by jd002181** [WarEmu/WarBugs#13700]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Expected behavior:  successfully complete Griffon Outpost PQ.

Actual behavior:  After I defeated my first order handgunner, all of the mobs disappeared making it impossible to complete.

**Steps to reproduce the problem:**

Unsure.

**Screenshots/Videos or archive.org evidences:**

**Comment by Kabucoror** [comment]
PQ works fine for me
