### ISSUE TITLE
Loading zone 18343 / Payment information - after patching

### ISSUE THREAD

**Issue by Latemoon83** [WarEmu/WarBugs#13705]
There must be something wrong. I get always dc after 10 seconds.

![screenshot_016](https://user-images.githubusercontent.com/33985355/54866247-bda71e00-4d71-11e9-890a-e52b9172b8e2.jpg)

All NPC's and Player's are disappeared after 10 sec. too.

And the other Problem is this:

![Latemoon_027](https://user-images.githubusercontent.com/33985355/54866582-e0d3cc80-4d75-11e9-8683-d74de873f897.jpg)

Any Ideas? :)

**Comment by MaxHayman** [comment]
Does this happen after the restart?

**Comment by Latemoon83** [comment]
Everything fine now, thank you!

**Comment by MaxHayman** [comment]
Please reopen this if this happens again.

**Comment by raptrr** [comment]
https://github.com/WarEmu/WarBugs/issues/15163

**Comment by MaxHayman** [comment]
This should be fixed now. Please reopen this if this happens again.
