### ISSUE TITLE
SE/RF regen stops sometimes without knowing why

### ISSUE THREAD

**Issue by Evasar** [WarEmu/WarBugs#13707]
Reequip, sell\buyback , relog does not fix it.

**Comment by sioding** [comment]
Switching the chalise doesn't help - relog doesn't help. You have to move the item into your backpack and back on the character. That mean really: No switching. SE regen stops when you do this. a know issue we can not fix atm. can you please test it?

**Comment by Evasar** [comment]
Yes put to backpack and back on character helps

**Comment by sioding** [comment]
I leave this one open and move it over to source department - cause we have a workaround - but a fix would be better.

**Comment by sioding** [comment]
Duplicate of #13226
