### ISSUE TITLE
Server stops communicating with client after login.

### ISSUE THREAD

**Issue by Fizzrib** [WarEmu/WarBugs#13706]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Expected: Login to game, business as usual.
Actual: After getting messages of Guild rank, server no longer fully communicates with client. NPC and players begin to disappear.

**Steps to reproduce the problem:**
Login with main character. Only happens to main, all alts do not seem to experience the issue.

**Screenshots/Videos or archive.org evidences:**
YouTube Video of issue: https://youtu.be/gZjp7R0BXD8

![Fizzrib_006](https://user-images.githubusercontent.com/48859392/54866781-36908080-4d46-11e9-9deb-65e84be319f7.jpg)
![Fizzrib_011](https://user-images.githubusercontent.com/48859392/54866782-3a240780-4d46-11e9-946e-168b6f774763.jpg)

**Comment by lucaoc** [comment]
same problem

**Comment by MaxHayman** [comment]
Fix in progress

**Comment by MaxHayman** [comment]
Let me know if it happens anymore.
