### ISSUE TITLE
Absorb and Armor Pots share cooldown

### ISSUE THREAD

**Issue by rakels** [WarEmu/WarBugs#13701]
It seems that Absorb (Lasting Aversion Potion / Potent Lasting Aversion Potion) and Armor Potions (Lasting Stanchion Unguent/Potent Lasting Stanchion Unguent) share the same cooldown- i think that this is not intended.

Short vid instead of screenshots:

https://youtu.be/Xxw50PguxH4

**Comment by sioding** [comment]
Hey - thanks for the report. Both Pots are usable - they share the same cooldown - if you want a change for it - please use our suggestions forum.
