### ISSUE TITLE
AoE Sorc 5/7 Invader

### ISSUE THREAD

**Issue by TheOGScav** [WarEmu/WarBugs#13702]
Not sure if that is by design but 5/7 invader bonus doesn't work with direction or 360 spells, (e.g. Ice Spikes, Surging Pain) At least, the tool tip needs to be updated. 

PS: the 10 ft range increase.

**Comment by sioding** [comment]
Can we please see your testing screenshots?

**Comment by grunbag** [comment]
It increase range , not radius

**Comment by TheOGScav** [comment]
No need for screen shots. Just look at Disastrous Cascade, range should be "self," with 5/7 it's 10ft. How does that make any sense is beyond me.

**Comment by TheOGScav** [comment]
PS: also Pit of shades DOES NOT benefit from 10ft increase although the tool tip says 90ft, now.

**Comment by grunbag** [comment]
Again there is no bug . AoE Abilities doesn’t have Range , it’s radius and invader doesn’t increase radius.
