### ISSUE TITLE
"Sacrifice" Warrior priest Healing Grace Healing skill (Bucklar needed to use)

### ISSUE THREAD

**Issue by Watchoni** [WarEmu/WarBugs#13719]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
The Warrior priest healing skill "Sacrifice" should heal allies while the WP takes damage, but currently it just deals DMG to the WP and no healing for party members.

**Steps to reproduce the problem:**
Just use the skill.

**Screenshots/Videos or archive.org evidences:**
No screenshots nor video its just bugged and needs a fix.

**Comment by grunbag** [comment]
it works, chat log heal is bugged and heal appears as damage instead of heal. but you groupe mates (gourp member but not yourself) are healed for the intended value
