### ISSUE TITLE
Spell effect tick timer

### ISSUE THREAD

**Issue by theHalta** [WarEmu/WarBugs#13712]
Spell tick timers reset when you cast the spell again on the same target who already has it.

E.g.: If I spam-cast Healing Hand (WP HoT) on a target, the tick timer will keep getting reset and they will never get healed.

How it should work:
The tick timer should persist even when the spell effect is reapplied. Any changes to the caster's stats should also be reflected on the renewed spell effect.
E.g.: Cast Healing Hand with 1000 willpower, the tick timer is 3s. When it reaches 0.5s left, I recast HH with 1100 willpower. The next tick should be 0.5 sec later (persistent), and it should heal with the new WP value.

**Comment by grunbag** [comment]
first tick happens after 3 sec , so if you refresh it before this time no heal will be applied on your target
