### ISSUE TITLE
Imperative Spirit

### ISSUE THREAD

**Issue by theHalta** [WarEmu/WarBugs#13716]
The WP Vanquisher 4p bonus Imperative Spirit does not proc off of HoTs when it should.
The tooltip reads: "On Heal - 10% chance......"
compared to e.g. Invader's 6p tooltip: "On DIRECT Heal: 5%....."

**Comment by grunbag** [comment]
on direct heal and on heal is the same. it's just mythic spelling and RoR spelling difference
