### ISSUE TITLE
Can't join WB or grp

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#13713]
During Fortress def i wanted to switch to another WB. But as I clicked on the invitation it disapered and from there on I couldn't join any grp, nor can I see invitations.

Sadly I have no Idea what caused this

**Comment by Kaelang** [comment]
Could have been a UI error, was you able to join groups after you logged off / back online? Appreciate this has been a while but I'm working through a backlog. Any further information you have to support this issue could be useful.

If you're no longer experiencing this, I'll go ahead and close the report in 2 weeks.

**Comment by Kaelang** [comment]
No further information - closed.
