### ISSUE TITLE
Terrible Stuck point

### ISSUE THREAD

**Issue by SATANICOMODERNO** [WarEmu/WarBugs#13720]
This point at Ironskin Skar is horrible, i can't do nothing to get out of this hole. No commands work here nor book or logging off. 

![image](https://user-images.githubusercontent.com/14305777/54883718-63788c80-4e47-11e9-97e9-f341777ef9c9.png)

**Comment by Kabucoror** [comment]
Blocked with next patch

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
