### ISSUE TITLE
herald

### ISSUE THREAD

**Issue by waikiss** [WarEmu/WarBugs#13722]
My guild leader Magnesial tryies to set up a guild heraldry. The game take him 10 gold but change only the colour, not the symbol. Then he tryies to do it a second time and it took him 200 gold with no change in heraldry. Please fix this issue and give him back money. Thank You

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment]
Duplicate of #10417
