### ISSUE TITLE
Fort entrance (gate and teleport)

### ISSUE THREAD

**Issue by Ladycaska** [WarEmu/WarBugs#13726]
I have joined in to a warband for fight in to the fort. When I reached the portal (my warband was already into the fort) i was attacked by others destro player who are waiting for the entrance. I can't use the teleport (cause i was in combat) and then i have lost the opprotunity to play the fort battle.
It's possible to automatically remove the combat flag when you reach the portal? In this way you can use the teleport.

(Sorry for my broken English)

**Comment by sioding** [comment]
Thanks for your ticket. Please understand that we need to split suggestions from bugs. The BT here is for bugs only. You can put your suggestion in our forum: https://www.returnofreckoning.com/forum/viewforum.php?f=15
