### ISSUE TITLE
Slayer character lost all Area Influence

### ISSUE THREAD

**Issue by backinwar** [WarEmu/WarBugs#1372]
Hey guys, i logged in with my slayer "Darkslayer" and i saw that all Area Influence in T2 zones where 0 plus i cant gain anymore influence from objectives. If you have the time could you please check into my issue. Don't know if anyone else has the same problem, but i hope you can help me.
Thank you for all the great work you are doing, take care:)

**Comment by Evildoor** [comment]
The problem still persists?

**Comment by Evildoor** [comment]
No confirmation, closing for now.
