### ISSUE TITLE
[WL] Slashing Blade wrong tooltip

### ISSUE THREAD

**Issue by ChaplainObvious** [WarEmu/WarBugs#13721]
Tooltip says that ability should cost 50 AP, while in reality it costs 35.

Easy to reproduce with any addon that displays numerical value of AP pool.

Screenshot of me using the ability, you can see that after use i have 215 AP, instead of 200.
![image](https://user-images.githubusercontent.com/39135994/54932112-5208b080-4f2b-11e9-9749-5ee056409516.png)

**Comment by grunbag** [comment]
Fixed for next patch

**Comment by sioding** [comment]
fixed with patch from 01.06.2019
