### ISSUE TITLE
unusable skills after getting on siege weapon

### ISSUE THREAD

**Issue by Illrathor** [WarEmu/WarBugs#13724]
Problem:
Should you end a scenario while on a siege weapon you find that you can not use any of your abilities.  Even reloading UI and using a flight master or your book of binding you load a new zone will not fix the issue.

**Steps to reproduce the problem:**
You have to die or relog the character to fix the issue.

**Screenshots/Videos or archive.org evidences:**

**Comment by TherealSouper** [comment]
I have the same issue except I can't mount my horse or use my book.  So I just have to run toward some enemies and hope they fight me while I stand there and do nothing.  Pretty annoying and it sometimes happens to me when I am talking to an npc while I accept an SC or if I just die sometimes I will randomly spawn with the bug.  Most of the time it has to do with SCs though but carries through to whatever you do until you die or reload the game.  Not able to reload UI or use the flight master to fix it.

**Comment by TherealSouper** [comment]
![Hamatime_000](https://user-images.githubusercontent.com/49039190/55180352-d17ec580-515f-11e9-893a-850205ab45c6.jpg)

A photo of me casting a spell and it instantly fails just before it is suppose to go off.  Your instant abilities don't work.  Your horse doesn't work.  Your book of binding doesn't work.  etc.

**Comment by geezereur** [comment]
same here i was using a hell blaster in scenario and after could not use any abilities.

**Comment by Natherul** [comment]
this should have been fixed since a few patchs back. If it persist please report back.
