### ISSUE TITLE
Pillaging

### ISSUE THREAD

**Issue by WildRuss** [WarEmu/WarBugs#13728]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by WildRuss** [comment]
Cant click chests i have got 3 but not registering so seems bugged

**Comment by Lheana** [comment]
Duplicate of #13711

**Comment by Gwendis** [comment]
Can confirm it, after chests reset, you can click on it, but you dont get the registed 3/3
