### ISSUE TITLE
BW tactic: Smoldering Embers

### ISSUE THREAD

**Issue by Aluviya** [WarEmu/WarBugs#13729]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
**Expected behavior:**
When Ignite, Boiling Blood, and Slow Boil **end** **or** **are** **removed**, there is a 25% chance that they will re-kindle, **reapplying** themselves to the target once again. Be cautious, though, for you will build Combustion and have a chance to cause an Explosion each time that they are reapplied!
**actual behavior:**
Tactic seems to not work anymore (used to work a while ago). The abilities mentioned above are never reapplied on end or removal. I have tested it in PvE and also in PvP last night during many Sc's and open RvR fights.

**Screenshots/Videos or archive.org evidences:**
Check the video where i applied the 3 abilities mentioned while using the tactic.
Video Link:
https://drive.google.com/file/d/1ToKI4H0Yn7JxorAzdkGnk1pEjIhu2sAH/view?usp=sharing

**Comment by Kabucoror** [comment]
Tested on dev 5 mins long not a single reapply.

**Comment by grunbag** [comment]
Fixed at next Patch

**Comment by geezereur** [comment]
Same with Endless Pandemonium for the magus can you guys fix that to plz.

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
