### ISSUE TITLE
Skulls and Sorcery - Hidden Chest problem

### ISSUE THREAD

**Issue by Aarimal** [WarEmu/WarBugs#13738]
In that quest you need to find a Hidden Chest. Chest is at the Sharpthorn Mine. But after looting it, it won't apply as the part of the quest. Item is in your bag but quest log dosen't see it. I've try to complete it by talking to Ranklot, but that doesn't work.
![Skulls and Sorcery problem](https://user-images.githubusercontent.com/48496225/55118671-65fd0f80-50ef-11e9-92d5-eb120ec3de83.jpg)

**Comment by Lheana** [comment]
You must loot the Hidden Chest AFTER you had the key (it's logic, you must have the key to open the chest and loot it). So try again now that you have the key.

**Comment by Aarimal** [comment]
I simply throw away one chest and quest was completed. Yet, taking chest after looting the key didn't work.

**Comment by Lheana** [comment]
You can see on your screenshot that the 2 chests are **before** the key, which means you looted them before you had looted the key.
Also, I have set this whole quest and I have tested it on my own several times, it works fine when you do things on the right order.
