### ISSUE TITLE
keep lords stay outside of inner keep

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#13736]
![LORD_BUG](https://user-images.githubusercontent.com/19988772/55052745-548b1780-509d-11e9-885a-142b2aedf362.jpg)

happened in BC and DW.
BC 4am, DW 6am in altdorf time.

if attackers wiped, lord don't reset to his place but stay outside.

**Comment by sioding** [comment]
Duplicate of #13588
