### ISSUE TITLE
SW parry bug + screenshots

### ISSUE THREAD

**Issue by ethilia** [WarEmu/WarBugs#13732]
**Expected behavior and actual behavior:**
I know there has already been a report on that in 2017 but I took a step to make some trials with a friend to reproduce the bug on my SW. I decided to go for a 877-997 Weaponskill build and I noticed that my parry chance is close to 10-20% instead of 46-51% as the tooltip reports. Furthermore I specced with the RR training for parry reaching a 65+% parry and again my parry rate was between 10-20%. Somethins is wrong with how parry chances are calculated for the SW. We made trials with the WEs parry chance and with Choppa parry and their reported values were the reported ones.
I also tried using the formulas refered to in this article to better estimate parry chance.
https://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=23384
defense% = 100% x (defender's defensive stat + 26.25 x % modifiers) / (attacker's offensive stat + 2625)
**Defenders stat** is 877 and 757 WS on assault and skirmish stance respectfully. 
**%modifier** is 13% and 3% on assault and skirmish stance respectuflly
**attackers offensive stat** is 784str (the WEs str)
attacker has 0% parry strikethrough from his gear.

**Steps to reproduce the problem:**

I made trials with a friend's WE using autoattack and spammable skills to determine the real average parry chance. His str is 784 and has 0% parry strikethrough from gear.
My parry on assault stance is 46.4% and my WS 877
7 out of 42 hits were parried which equals **16.67% actual parry rate**
(tooltip reports 46.4)
Using the formula for parry provided on the discussion above I calculated the parry chance as the following:
parry%= 100% x (877+26.25x13)/(784+2625)=**35.7%** expected rate

![7 to 42](https://user-images.githubusercontent.com/48962457/55022577-8b145400-5003-11e9-80dd-bd5e0e51c970.jpg)

It crossed my mind that maybe the assault stance bonuses are faulty so i tried the same in skirmish stance with 757 WS and 31.8% parry

4 out of 43 hits were parried which equals **9.3% actual parry rate**
(tooltip reports 31.8%)
Using the formula
parry%=100% x (757+26.25x3)/(784+2625)=**24.5%** expected rate

![4 to 43](https://user-images.githubusercontent.com/48962457/55022726-e34b5600-5003-11e9-9799-e9e733e8edb9.jpg)

If we take the formula into account (which is the most proper way to calculate the parry rate). The actual parry rate is **half** than the supposed parry rate.

Now, holding a MSc in electrical and computer engineering and a MBA I do realize that 85 tries are not a sufficient speciment to determine a proper statistic. 
Still the results are way too far from the safety margin. Actual parry rate being half than the expected parry rate is too big of a difference to be owed to a statistical error on that specimen.

The bug may be owed to stance switching and recalculating the parry chance. I am at your disposal to make any trials needed in the future to help resolve this issue.
Kind regards,
Ethilia

**Comment by sioding** [comment]
Thanks for the report. I am not sure if the tests you did are enough - 43 tries are way too less to make sure something is fine but i let it through. Maybe @grunbag can have a look at it.

**Comment by Lefze** [comment]
Your WS / Enemy STR * 0.075 * 100 + (parry-strikethrough). You are using the wrong formula, as the changes were reverted.

**Comment by grunbag** [comment]
This is something for secrets

**Comment by Lefze** [comment]
Works as intended. Obviously a few points off, but chalk it up to low sample size.

**Comment by ethilia** [comment]
According to that formula the parry chance is correct. Made some more trials today. It works as intended. I am deeply sorry for waisting your time :(

**Comment by ethilia** [comment]
Thank you very much for the interest
