### ISSUE TITLE
Mail bugged

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#13731]
Hello today I send 6 talismans from my Swordmaster (Oshikuruh) to my White Lion (Purrity). When I logged my WL the items did not arrive. I waited a few minutes but nothing happened. I relogged to my Swordmaster to check the backpack, but the items were not in the backpack.
Quit the game again, logged my WL, no items in mail. I then contacted a GM he said to send some junkitems. 
Those junkitems arrived 3 hours later in the mail but not the talismans I send earlier. Should I wait till server reboot, or this is a known bug?

**Comment by sioding** [comment]
First of all - did you sent some junk items from the swordmaster again or from a complete other char? Would you try this again from a complete other char and give some feedback?

**Comment by wiscel** [comment]
Yes, I send from the SM to my WL. 

I did what you asked and send some junk from my SW (Alastrelle) to my WL, no mail :-/

**Comment by sioding** [comment]
Hm can you please also add the charactername and the ~time you sent the mail? maybe its something in the logs.

**Comment by wiscel** [comment]
The character name is Purrity (to this character I've send the items). I've send the talismans this afternoon. Not sure about the time, somewhere between 13.00 and 16.00 CET

**Comment by sioding** [comment]
Thanks

**Comment by coxie87** [comment]
I experienced this as well. However, I noticed that when I sent mail from my Chosen (Erenhelm) to my Shaman (Tagazid), the mail did not arrive. When I sent the mail, I did not capitalize the name of the character.

When I sent mail back from Tagazid to Erenhelm, I did capitalize the name and the mail arrived immediately.

This just happened about 1335MDT on 2019/09/21.

**Comment by raptrr** [comment]
https://github.com/WarEmu/WarBugs/issues/12306

**Comment by Natherul** [comment]
Should have been fixed with the patch from yesterday
