### ISSUE TITLE
Destro KV Chapter 22 Hard PQ Slayer Keep

### ISSUE THREAD

**Issue by Abodam** [WarEmu/WarBugs#13737]
There is a issue with first stage when killing dwarfs defenders on Onslought CH22 Hard PQ in KV.

Killing defenders outside main black paved path does not count towards PQ kill total.

**Comment by Kabucoror** [comment]
All related NPC's count as they should and they are enough to complete stage 1. Note that we can add only a few different NPC's to the counter. But thanks for your report.
