### ISSUE TITLE
Fightin chance tactic disappeared 

### ISSUE THREAD

**Issue by Franhaetta** [WarEmu/WarBugs#13734]
According to all my colleagues, my engineer Ullhird should have learned the Fightin Chance tactic at rank 33, but even being in the 40th rank I do not own it being an essential part of my character, I attach images of the three tactical pages to prove it.
![Ullhird_000](https://user-images.githubusercontent.com/48967102/55033335-3aa4f280-5013-11e9-95f4-366941abe14d.jpg)
![Ullhird_001](https://user-images.githubusercontent.com/48967102/55033345-3f69a680-5013-11e9-87d9-1da2b491da25.jpg)
![Ullhird_002](https://user-images.githubusercontent.com/48967102/55033354-42649700-5013-11e9-8099-edf4c4312a29.jpg)

**Comment by grunbag** [comment]
Isn’t it runa de la forja?

**Comment by Franhaetta** [comment]
no, Fightin Chance in spanish is Oportunidad de luchar/pelear, runa de la forja is forge rune/rune of forge

**Comment by Franhaetta** [comment]
Runa de la forja gives extra life point to my turrets

**Comment by grunbag** [comment]
I need to check DB , ask other engi if they have the same issue

**Comment by Franhaetta** [comment]
I've been asking all the engineers in my guild, they all confirmed that they have and in fact they use this tactic

**Comment by grunbag** [comment]
Try /language 1

**Comment by Franhaetta** [comment]
ok, rune of the forge has changed to opportunity to fight, but it does not have the effect it should, it is supposed to increase my BS, WS and S in exchange for lowering my thougness, instead it puts a shield to my turret

**Comment by Franhaetta** [comment]
I'm sorry I just checked that it has the right effect but it has an erroneous description.

**Comment by grunbag** [comment]
Interesting , you have a old removed tactic from early 2008. I’ll check Spanish language .

**Comment by Franhaetta** [comment]
in english i can see the correct tatctic with the correct description, Thanks for the help, and yes in spanish i have the older tactic, thaks for the support

**Comment by grunbag** [comment]
Np
