### ISSUE TITLE
[SW] Vanquisher Body armor +3% armor Pen. Incorrect display

### ISSUE THREAD

**Issue by CrimsonFenris** [WarEmu/WarBugs#13730]
**Expected behavior and actual behavior:**
+3% Armor Penetration from Shadow Warrior Vanquisher's Tunic (body piece) is not correctly displayed on item tooltip (value is displayed first and greyed out).
Value is taken into account when doing .getstat with a separated line, but isnt correctly reflected in character sheet (see screenshots switching BL Tunic with Vanquisher one).

The value is falsely reported in Statdoll addon as +3 Intelligence (value unmodified looking at getstat).

![Tanaryon_041](https://user-images.githubusercontent.com/40425011/55009075-4b894000-4fe2-11e9-8f40-2cb2bad9561c.jpg)
![Tanaryon_042](https://user-images.githubusercontent.com/40425011/55009081-4d530380-4fe2-11e9-8905-2afaa066a666.jpg)

**Comment by Kabucoror** [comment]
duplicat of  #13251
