### ISSUE TITLE
[DoK] Invader jewelry

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#13743]
As Invader set for dok was changed to be healer set - "Reduced Chance to be Parried" bonus on jewelry piece remained, and as it is offensive, not healing stat I think it was forgotten to be changed.
![dok](https://user-images.githubusercontent.com/42712833/55233255-0f9be800-5239-11e9-9bc1-2b2f5052b17f.PNG)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 05.05.2019
