### ISSUE TITLE
mailbox is not working.

### ISSUE THREAD

**Issue by VSikhvart-modus** [WarEmu/WarBugs#13747]
Cant open mails after Patch 30.03

**Expected behavior and actual behavior:**

Mailbox is working and could see mails

**Steps to reproduce the problem:**
Click on Mailbox - not working

**Screenshots/Videos or archive.org evidences:**

**Comment by MaxHayman** [comment]
Destro order? SS of mailbox plz

**Comment by VSikhvart-modus** [comment]
@MaxHayman  Destro. All mailboxes, in all zones

**Comment by JustDust1** [comment]
have the same problem, destro side

**Comment by MaxHayman** [comment]
Will be pushed live soon.

**Comment by sioding** [comment]
Fixed with Hotfix from 31.03.2019
