### ISSUE TITLE
Wrong Class in gold bag

### ISSUE THREAD

**Issue by xaraxdestr** [WarEmu/WarBugs#13741]
Don't know if reproducable but i got a Gold Bag in Avalorn today as a lvl 19 sorc and got Archmage Loot in it.

![Knochenhaufen_001](https://user-images.githubusercontent.com/45398873/55159881-5a96fc00-5162-11e9-9f79-89b3e4433e7d.jpg)

**Comment by sioding** [comment]
Duplicate of #11739

**Comment by Muurloen** [comment]
Happened to me today.

![Emuurlat_000](https://user-images.githubusercontent.com/50267777/61174890-4558a880-a56c-11e9-8f2b-e0a2753311dc.jpg)
