### ISSUE TITLE
Armor replacing Weapons

### ISSUE THREAD

**Issue by MrShampi** [WarEmu/WarBugs#13744]
**Expected behavior and actual behavior:**

the armor is xhowing in inventory despite of weapons on equiped inventory and when comparing weapons.
nb: im using clsetgoblins addons but 1st time ot make me that kind of bug
**Steps to reproduce the problem:**
going to the character window  or  to any gear vendor and look the weapons.

**Screenshots/Videos or archive.org evidences:**

![bug](https://user-images.githubusercontent.com/47632071/55251684-72997900-5251-11e9-8033-a8e81813c7e8.JPG)

**Comment by sioding** [comment]
¯\_(ツ)_/¯
Following your steps to reproduce it and i can't do it. Please be more precise how you get into this situation.

**Comment by sioding** [comment]
No answer for 15 days. Close
