### ISSUE TITLE
choppa 7 set invader bonus not showing up in tooltip

### ISSUE THREAD

**Issue by grimskul** [WarEmu/WarBugs#13745]
hello choppa invader 7 set bonus is not showing up in the armor pen on my charcter 
![Grimskul_005](https://user-images.githubusercontent.com/49084561/55270381-5fe46b80-5274-11e9-9779-c4f5807c9caf.jpg)

![Grimskul_006](https://user-images.githubusercontent.com/49084561/55270388-7094e180-5274-11e9-8917-de95f2daea80.jpg)

**Comment by grimskul** [comment]
I forgot to add that as you can see i am beserk in both screenshots full invader i also checked getstats and it didnt show up as well.

**Comment by grunbag** [comment]
It’s not armor pen , it ignore 20% of enemies armor

**Comment by sioding** [comment]
Thanks for the report. Answer is given - close.
