### ISSUE TITLE
[game object] Big pile

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#13748]
Wild Throphy pile appeared on road in BC.
![Veszal_696](https://user-images.githubusercontent.com/42712833/55276715-eac27600-5307-11e9-8924-6ab86ca9eb01.jpg)
![Veszal_697](https://user-images.githubusercontent.com/42712833/55276716-eac27600-5307-11e9-943a-56472453ca31.jpg)

**Comment by sioding** [comment]
Fixed with Hotfix from 31.03.2019
