### ISSUE TITLE
Harvest Shrine cart in t1 nordland is too big

### ISSUE THREAD

**Issue by 0xAB51NTH** [WarEmu/WarBugs#13754]
**Expected behavior and actual behavior:**
Expected: Cart is small normal and good
Actual: Its big like it was designed to transport 32 black orcs into order warcamp

**Steps to reproduce the problem:**

Go to harvest shrine in nordland rvr

**Screenshots/Videos or archive.org evidences:**

![image](https://user-images.githubusercontent.com/47013267/55278386-e5ffc100-530b-11e9-9741-d46dcfa3102a.png)

**Comment by sioding** [comment]
Fixed with Hotfix from 31.03.2019
