### ISSUE TITLE
IC Mokai Warp-Changed unknown rally master

### ISSUE THREAD

**Issue by Nixra** [WarEmu/WarBugs#13756]
![ICRally](https://user-images.githubusercontent.com/49102680/55279731-18042980-52f2-11e9-845d-baead1732c5a.png)

When attempting to set rally point with Mokai Warp-Changed it will say Unknown Rally Point NPC (2001547). He also shows Influence rewards while have nothing available.

**Comment by Kabucoror** [comment]
That's because he is not a real Rally Master and you are not supposed to set a rally point on him. Also he does have a reward, it's the sentinel jewel from the city dungeons.
Nevertheless, thank you for the report.
