### ISSUE TITLE
CH22 Easy Pq The Defiled Anvil Untouchable Stones

### ISSUE THREAD

**Issue by Lithliel** [WarEmu/WarBugs#13751]
**Expected behavior and actual behavior:**
5 stones in stage 2 should be killable. They are not. Can't use skills on them

**Steps to reproduce the problem:**
Just do first stage of PQ.

**Comment by Kabucoror** [comment]
works fine for me on dev

**Comment by Scophis** [comment]
working on live as well
![stone](https://user-images.githubusercontent.com/40274248/55686806-17a90580-5966-11e9-91bf-93826a5bba60.jpg)

Maybe it was a relic from the GO-changes, that got fixed in the meantime
