### ISSUE TITLE
[SC Soldier Weapons]

### ISSUE THREAD

**Issue by osium** [WarEmu/WarBugs#1375]
the damage is not calculating properly on the new SC weapons my Ravage is at 248 dmg with the Echelon Axe that has a dps of 32 and str of +42 now when I equip the solider sword with a dps of 36 and a +38 str it is still 248 dmg another strange thing was even without the str tali in the sword for some reason the dmg was locked at 248

**Comment by Evildoor** [comment]
https://github.com/WarEmu/WarBugs/issues/1305
Looks similar...

**Comment by Evildoor** [comment]
Tested this on dev server (but without talismans) - tooltips and real damage properly differ when weapon is changed.
