### ISSUE TITLE
[PQ Ch22] Runic Ward are unattackable

### ISSUE THREAD

**Issue by elk76** [WarEmu/WarBugs#13757]
In KV PQ Ch22 at stage III the Runic Ward are unattackable

**Comment by Kabucoror** [comment]
works fine for me on dev

**Comment by elk76** [comment]
Saturday 30th march we did a full run of all PQs (reik, eataine and KV). Only Reik worked. Eataine was bugged in the last stage: we could not interact with orbs on fountains.

In KV, we could not complete the stage III because we could select runic wards, but we could not attack them (single attack or aoe)

may be it is fixed with last patch. We will try another run this week end and I will let you know

**Comment by elk76** [comment]
I tested it now on DEV server and It worked.
may be the issue is solved with last patch (mail box and item issue)
