### ISSUE TITLE
[World Object] Cannon Battery T1 Ekrund HUGE DEFENCES

### ISSUE THREAD

**Issue by NorthernAxe** [WarEmu/WarBugs#13759]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
The spikes are supposed to be small and decorative. They are currently functioning as an actual palisade, blocking off the western approach.

**Steps to reproduce the problem:**
Visit 55k, 9.5k in Ekrund

**Screenshots/Videos or archive.org evidences:**
![image](https://user-images.githubusercontent.com/48163534/55281884-f14cef80-52ff-11e9-83c5-5ab73588067d.png)
![image](https://user-images.githubusercontent.com/48163534/55281887-f742d080-52ff-11e9-9d29-e1914222630b.png)

**Comment by Kabucoror** [comment]
fixed with hotfix from 31.3.19
