### ISSUE TITLE
Spiders in Silken PQ are level 40 again

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#13758]
**Expected behavior and actual behavior:**

PQ is level 12-13. Spider mobs are now level 40.

**Steps to reproduce the problem:**

Please lower mob level to suit the PQ

**Screenshots/Videos or archive.org evidences:**

![Aasgeir_032](https://user-images.githubusercontent.com/22262165/55281760-3c332b00-5331-11e9-8bfb-50a9ec2796f5.jpg)

![Aasgeir_033](https://user-images.githubusercontent.com/22262165/55281765-40f7df00-5331-11e9-854e-9880ce45ed41.jpg)

**Comment by Lheana** [comment]
Thanks for reporting it. It will be fixed with next patch.

**Comment by sioding** [comment]
Fixed with Hotfix from 31.03.2019

**Comment by Senthoi** [comment]
Thank you!
