### ISSUE TITLE
[Quest] The Threat from Tobias The Fallen

### ISSUE THREAD

**Issue by tog89** [WarEmu/WarBugs#13760]
**Expected behavior and actual behavior:**
Killing the Sigmar's Crypts wing boss, Tobias the Fallen should update the kill quest The threat from Tobias The Fallen.  When I am in groups that kill Tobias, the gear quest is not updating the kill counter, the quest has been stuck at 1/4 for 6 runs now.  I have checked and been in groups with some lockouts and not Tobias, some with lockouts for Tobias and groups with no lockouts.  I have never had a lockout for Tobias when running it, but have had other lockouts in the 6 runs I have completed.

**Steps to reproduce the problem:**
Enter Sigmar's Crypts and kill tobias the fallen with the quest in my tracker.

**Screenshots/Videos or archive.org evidences:**
None.  I will document on my next run.

**Comment by grunbag** [comment]
Hargrim Fixed quest recently
