### ISSUE TITLE
Tome Unlock - For the Greater Gor doesn't seem to work

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#13768]
**Expected behavior and actual behavior:**

I killed Drahamesh, but did not get the  "For the Greater Gor" tome unlock. I made sure to kill all the other gor surrounding him to guarantee I got the killing blow. But still no unlock.

At around 7,18k in Praag.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

![Lotharic_044](https://user-images.githubusercontent.com/7400/55288979-43554a00-53c0-11e9-9d84-26eebba2edff.jpg)

**Comment by dalen** [comment]
Related to https://github.com/WarEmu/WarBugs/issues/13767, but two different issues with this mob.

**Comment by Lheana** [comment]
So **ONCE AGAIN** as it is noted when you open a ticket: **Verify RoR Wiki before posting something related to ToK unlocks**
I don't know why you think that Drahamesh is meant to give an unlock. Refer to RoR Wiki https://wiki.returnofreckoning.com/index.php/For_the_Greater_Gor

**Comment by dalen** [comment]
Sorry about that, my bad. Pretty sure this is the first Tome unlock ticket I have posted though.

He was listed in the Tome Titan addon as giving the unlock, and on this RoR wiki page it also lists Praag as a location for it: https://wiki.returnofreckoning.com/index.php/Beastman,_Gor

**Comment by Lheana** [comment]
You are right, sorry for my first answer.
On the Hammer Wiki this NPC is not mentionned, but in add on Tome Titan, he is mentionned.
I will investigate it a bit further.

**Comment by dalen** [comment]
This page lists both the kadrin valley mob and the praag mob for it: http://eq2.zam.com/wiki/Tier_4_%28Bestiary_Unlock_Guide%29

**Comment by sioding** [comment]
fixed with patch from 10.06.2019
