### ISSUE TITLE
Drahamesh, Bestigor hero in Praag is hostile to other beastmen

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#13767]
**Expected behavior and actual behavior:**

This beastman hero mob around 7,18k in Praag is hostile to his fellow beastmen which seems a bit odd.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

![Lotharic_044](https://user-images.githubusercontent.com/7400/55288958-fa9d9100-53bf-11e9-8346-e056e435d9a5.jpg)

**Comment by dalen** [comment]
![Lotharic_044](https://user-images.githubusercontent.com/7400/55288957-f2ddec80-53bf-11e9-85cd-e642cc147def.jpg)

**Comment by NorKalli** [comment]
Drahamesh won't attack his friends anymore

**Comment by sioding** [comment]
Fixed with patch from 11.05.2019
