### ISSUE TITLE
[Craft] "Scavenging" level 25 – The termination of development the skill level, after reaching skill level: 25.

### ISSUE THREAD

**Issue by DeusExMachine** [WarEmu/WarBugs#1376]
I tried to describe in detail the situation in the picture accompanying the post:
![scavenging](https://cloud.githubusercontent.com/assets/14233141/9819418/430c0796-58f1-11e5-8b23-845537237908.jpg)

Correct it, please. Thank you for attention.

**Comment by DeusExMachine** [comment]
Several posts on similar cases:
#1366
#1371

**Comment by noisestorm** [comment]
Crafting should work again with the next hotfix that goes live. Bug was found and also the leveling should be smoothed out a bit for early levels.
