### ISSUE TITLE
What in the name of Sigmar is this? Is it even right?

### ISSUE THREAD

**Issue by SATANICOMODERNO** [WarEmu/WarBugs#13765]
Is the first time I see this creature in game since I got back. This creature is enormous and blocks vision what makes even  harder to target the enemy under it. I ask for devs review this ability with some attention (if it's any kind of ability, morale or tactic because i really don't know). 

![image](https://user-images.githubusercontent.com/14305777/55285180-b7f69d00-535c-11e9-92cb-241fa447ef89.png)

**Comment by sioding** [comment]
It's the M4 of a magus: Firewyrm of Tzeentch. Should be gone after 16 seconds.
