### ISSUE TITLE
Missing quest: Desecration

### ISSUE THREAD

**Issue by gorahn** [WarEmu/WarBugs#13763]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Quest: 'Desecration' missing from Merchant NPC Havlr in Chaos CH2 area

**Steps to reproduce the problem:**
Interact with NPC with character that has not accepted the quest previously

**Screenshots/Videos or archive.org evidences:**

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 06.04.2019
