### ISSUE TITLE
T-Blasting and WL pet.

### ISSUE THREAD

**Issue by TheOGScav** [WarEmu/WarBugs#13778]
Sorc's T-blasting NOT effecting WL's pet. WL gets punted away, no KD/punt to pet.

**Comment by sioding** [comment]
Can we please see your testing screenshots/videos?

**Comment by TheOGScav** [comment]
Ofc ya can get a screen shot, let me just live for more than 3 secs vs a WL.

Plus, I doubt a single screenshot would show anything. Need a small 5 sec clip. And I was told not to xrealm and ask for 1v1 for testing purposes 'cause it's considered RR farming.

**Comment by Scophis** [comment]
As long as you don't kill each other, it shouldn't be a problem. Also you just have to test the effect on the pet.

**Comment by sioding** [comment]
no answer for 22 days. close
