### ISSUE TITLE
(BO) BLOCK BLOCK BLOCK 

### ISSUE THREAD

**Issue by TwettY** [WarEmu/WarBugs#1377]
Administrators already tired I ask that you have repaired the unit on the black orcs, I understand that you do not care that the dreams as you play for beavers but ispravte already tired to die like an ordinary rag !!!

**Comment by Thorgatin** [comment]
Srsly dude, no one can understand this google translate jabber, so devs probably don't know what you want. I recommend to ask a friend to translate your problem(s), so non-thelepathic-gifted people can read it.

**Comment by ozarmidrashim** [comment]
Closed for stupidity.
