### ISSUE TITLE
[Items] BL set bonuses

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#13771]
Not sure if it is intentional or not but BL set bonuses for BG-IB and BO-SM pairings are not mirrored in terms of 5 and 6 piece bonuses.
Of these sets BG and SM have disrupt, while BO and IB have parry.
As this kind of difference can only be found on BL, while all other sets are similar for mirror classes - I report it here.

**Comment by wargrimnir** [comment]
This is intentional.
