### ISSUE TITLE
zone flip and keep renown not receiving

### ISSUE THREAD

**Issue by Raithes** [WarEmu/WarBugs#13775]
I help take CoF keep in Dragon wake and did not receive any renown/influence or exp or loot/coin and zone flipped.   helped kill destroy outside of keep and court yard and nothing either.   Have been having issues of the same on multiple characters.

![Raiths_000](https://user-images.githubusercontent.com/49134728/55298946-8504e580-53fe-11e9-9ae7-c42a6d4217b9.jpg)
![Raiths_000](https://user-images.githubusercontent.com/49134728/55298952-9221d480-53fe-11e9-9d38-c63df1ac2cfc.jpg)
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by Kaelang** [comment]
Please can you confirm if you are still experience this issue with the myriad of changes implemented since this report was listed?

**Comment by Raithes** [comment]
Thank you for the speedy reply.  This was opened March 31, 2019.    You can close this since over a year has pasted.   Thank you
