### ISSUE TITLE
Pandemonium bugged - does damage with no dot on a target

### ISSUE THREAD

**Issue by Chaos1414** [WarEmu/WarBugs#13774]
It seems that "Endless Pandemonium" tactic for Magus might be bugged. The tactic seems to do what its supposed to (50% chance to reapply pandemonium) that part works, however I'm noticing that occasionally pandemonium will continuously tick on a target even without the dot even applied.. so it endlessly ticks on a target until they die, which leaves me in combat even if I'm miles away from them. If you have anymore questions let me know and I'll try to answer them/provide any resources you may need.

**Comment by Chaos1414** [comment]
![Chaosm_005](https://user-images.githubusercontent.com/49132957/55336632-43f6ea80-546b-11e9-909d-f59d15bcd5d0.jpg)

![Chaosm_006](https://user-images.githubusercontent.com/49132957/55336676-596c1480-546b-11e9-82fd-016a6498ade0.jpg)

![Chaosm_007](https://user-images.githubusercontent.com/49132957/55336702-64bf4000-546b-11e9-8290-31749328aca0.jpg)

![Chaosm_015](https://user-images.githubusercontent.com/49132957/55336851-99cb9280-546b-11e9-9038-78bb1dcfdd05.jpg)

First 3 taken a second apart from the previous, except for _015 that was taken about 10 secs after the others
Another case:
![Chaosm_018](https://user-images.githubusercontent.com/49132957/55336967-d1d2d580-546b-11e9-950a-4cd5cdc0786e.jpg)

![Chaosm_020](https://user-images.githubusercontent.com/49132957/55336998-df885b00-546b-11e9-8975-240d9ed9c4fa.jpg)

![Chaosm_021](https://user-images.githubusercontent.com/49132957/55337006-e44d0f00-546b-11e9-8eb5-b95530443288.jpg)

**Comment by Chaos1414** [comment]
I ran across the "Sunoffire" guy like 10 mins later and he's still ticking for damage... keeping him and I in combat. 
![Chaosm_000](https://user-images.githubusercontent.com/49132957/55337509-d350cd80-546c-11e9-9546-8a1e414a00ec.jpg)

![Chaosm_001](https://user-images.githubusercontent.com/49132957/55337520-d9df4500-546c-11e9-9f28-cd6bde26e10a.jpg)

**Comment by Chaos1414** [comment]
![Chaosm_008](https://user-images.githubusercontent.com/49132957/55343175-94287980-5478-11e9-9365-d3ccf6e8fa47.jpg)

**Comment by Chaos1414** [comment]
https://clips.twitch.tv/FlaccidHorribleLeopardBlargNaut

**Comment by sioding** [comment]
Thanks we have enough evidences for now.

**Comment by grunbag** [comment]
Buffline doesn’t appears when it reapply

**Comment by Chaos1414** [comment]
But it never stops ticking is my point, it will go on until they die.. and shouldn't the DoT be shown anyways?

**Comment by Chaos1414** [comment]
It's a 25% chance to reapply itself, however after 5 mins and it's still ticking? That seems wrong, that would mean it would have to reapply itself so many times in a row.. almost impossible, and to happen on multiple targets in a short amount of time... something is surely wrong with it.

**Comment by deathkylem** [comment]
![Horlvaf_029](https://user-images.githubusercontent.com/38692556/55521097-927cd280-567f-11e9-9b4e-422c897ea46d.jpg)
Altdorf....xD

**Comment by grunbag** [comment]
Fixed at next patch

**Comment by sioding** [comment]
fixed with patch from 06.04.2019
