### ISSUE TITLE
[RvR] Finishing a fortress resets other zones

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#13770]
Today our warband went to the Shadowlands when Reikwald opened and non of us got a reservation. We sieged the keep and killed the lord and were about to lock the zone when the fortress lord died and the zone reset. There was no bag roll or XP given.

**Comment by zak68** [comment]
happened today 13/4 around 8 am cet in elf t2 while butcher pass fort was active; order was sieging keep, and lord was bugged standing outside. they destroyed the door and finally managed to wipe us. we returned to the keep just to find outside door up with order trapped inside; typing .rvr showed that fort siege was over and BC zone was open again.

**Comment by gittoaster** [comment]
Today.  We were in TC RvR when Butcher Pass was locked by Order.
In TC both realms were leveling the Keeps to 1 star, after the Butcher Pass Lock, Keep ownership swapped, and the Order Keep's resources were reset, although Destruct Keep resources remained.

Expected - the Dwarf/Greenskin zones should be only realm affected, but as shown in screen shot, it mentions Empire pairing as well.

https://ibb.co/s1fCrYP

**Comment by Natherul** [comment]
if 2 forts are locked for the same realm then the campaign resets. So should the same realm lock the second fort while you are locking another zone then you wont get anything, Sorry but this is how the campaign is designed

**Comment by Moragor** [comment]
This was about something different, but it seems to be fixed anyways.
