### ISSUE TITLE
[PQ] The Well of Sar-Saroth

### ISSUE THREAD

**Issue by tog89** [WarEmu/WarBugs#13779]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
High Elf Chapter 16 Normal PQ  The Well of Sar-Saroth.  Stage II is to destroy four cornerstones but you cannot attact the cornerstones.  AoE, pets or direct damage will not effect the cornestones.  The cornerstones are selectable and you can target them.  You can also right click them to no effect.

**Steps to reproduce the problem:**
Bring pq to stage 2, kill guarding spirit wolves, attempt to destroy cornerstones.

**Screenshots/Videos or archive.org evidences:**
![Psymonson_007](https://user-images.githubusercontent.com/38359697/55306338-81328c80-5419-11e9-87da-b16608241d6f.jpg)

**Comment by sioding** [comment]
Fixed with patch from 13.04.2019
