### ISSUE TITLE
BoP item got lost because of BAG full

### ISSUE THREAD

**Issue by Dobzse** [WarEmu/WarBugs#13772]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Won the loot Sentinel Helm from Boss.

**Steps to reproduce the problem:**
Had no spaces in my bag due to the amount of trash loot from the instance.

**Screenshots/Videos or archive.org evidences:**
![Xalzius_133](https://user-images.githubusercontent.com/41837044/55296479-5ac12100-541a-11e9-8223-0517077c7549.jpg)
![Xalzius_134](https://user-images.githubusercontent.com/41837044/55296483-5e54a800-541a-11e9-8a0a-734467e7302e.jpg)

**Comment by Dobzse** [comment]
Could you please restore somehow my Sentinel helm ?

**Comment by sioding** [comment]
Sorry but we do not restore items. You have to make sure your bagpack isn't full before you go into a dungeon.
