### ISSUE TITLE
BW | Backlash exception

### ISSUE THREAD

**Issue by Thorgatin** [WarEmu/WarBugs#1378]
Killing yourself with Detonate seems to throw always an exception.

**Comment by ozarmidrashim** [comment]
Killing yourself with the backlash from having used Detonate, or?

**Comment by Thorgatin** [comment]
Yes, it seems happen always when i use detonate on low life and kill myself through backslash caused by the ability.
![cinderella_010_crop](https://cloud.githubusercontent.com/assets/8567481/9833601/cd7023c6-599c-11e5-985c-b713a54432d1.jpg)

**Comment by ozarmidrashim** [comment]
We need to test this on the dev server.

**Comment by Thorgatin** [comment]
KK

I made a complete combat log screenshot when it happens:

![cinderella_012_crop](https://cloud.githubusercontent.com/assets/8567481/9836468/88c9d094-5a1b-11e5-83f9-eab75e0e25f9.jpg)

**Comment by Thorgatin** [comment]
Happens also when using other abilities and killing yourself trough backlash:

![2015-09-14_00002_crop](https://cloud.githubusercontent.com/assets/8567481/9846369/1003586c-5ad2-11e5-8d27-92f87039af42.jpg)
