### ISSUE TITLE
Sticky Mushroom Hex

### ISSUE THREAD

**Issue by Aluviya** [WarEmu/WarBugs#13788]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Sticky Mushroom is an ability from the Goblin Mobs in Midwing Gunbad. The Tooltip says it's a hex - so i asume that a healer should be able to cleanse it - like almost every debuff in game. With my Archmage i wasn't ever able to remove it - even though AM can remove hex.

**Screenshots/Videos or archive.org evidences:**
Check the Screenshot.
![Stickymushroom](https://user-images.githubusercontent.com/17249318/55396978-7d9c2400-5545-11e9-8a83-76c83c8e4801.jpg)

**Comment by grunbag** [comment]
fixed withg next patch

**Comment by Kaelang** [comment]
Fixed as of 13/05/2020 patch. Please re-open if issue persists.
