### ISSUE TITLE
Hated Kin, using Slyth Extract does nothing

### ISSUE THREAD

**Issue by pjz** [WarEmu/WarBugs#13786]
**Expected behavior and actual behavior:**

Expected: using the Slyth extract on Merdia Fensong should check off that box
Actual: it doesn't

**Steps to reproduce the problem:**

Find the manbane, get the slyth extract, sneak over behind the rock behind Merdia.  In quest inventory, click on the Slyth extract to pick it up, then right-click on her.  The cursor changes to a dagger... but the quest step isn't checked off.  Clicking again makes her attack you.  Killing her also doesn't check off the quest step.

**Comment by Lheana** [comment]
How do you try to complete the quest exactly?

**Comment by pjz** [comment]
What would you like to know?  

Here's exactly what I did - if it's not exact enough, let me know which steps need more detail and I'll add more.

  1. Obtain the Slyth Toxin
  2. Find Merdia Fensong
  3. Get close to her (she's non-agro (orange))
  4. Open Quest Inventory
  5. Left Click on Slyth Toxin - you're now holding it
  6. Right Click on Merdia with Slyth Toxin

At this point I expected that step of the quest to be done, as it is described as "Use the Syrth Toxin on Merdia Fensong."  Instead, the cursor turned into a dagger, and clicking on her again made her attack me.

**Comment by Lheana** [comment]
You simply have to use the item in your inventory **targeting** Merdia.

**Comment by pjz** [comment]
Ah! That did it, thanks!  Note that that method didn't work when having to use the gloves on the corpse in... that other quest :)

**Comment by Lheana** [comment]
These quests have been changed to work that way some weeks ago, maybe it was before it got changed.
