### ISSUE TITLE
Received precursor item for wrong realm

### ISSUE THREAD

**Issue by Zoggof** [WarEmu/WarBugs#13781]
Received a BW precursor item on my BO last night during RvR on March 31st

![Zoggof_017](https://user-images.githubusercontent.com/23256143/55309825-9efc0200-54aa-11e9-8abe-d17c42333819.jpg)

**Comment by Zurbak** [comment]
Can confirm I've recieved order Precursor on Destro as well since the last patch.

**Comment by sioding** [comment]
Was this only something from yesterday or does they drop today too?

**Comment by Zurbak** [comment]
Today

man. d. 1. apr. 2019 19.30 skrev Sio <notifications@github.com>:

**Comment by Zoggof** [comment]
Only happened on the night I reported it, I haven't seen any cross realm items since.

**Comment by sioding** [comment]
Thanks for the feedback. Close
