### ISSUE TITLE
Righteous Fury getting drained

### ISSUE THREAD

**Issue by Warfare80** [WarEmu/WarBugs#13795]
Last week my RF on my WP have been drained without me using any RF consuming skills.
First i thought it was some normal lag issue, but then a friend had same issue.
I have seen it 4 times in 3 days. 

First time was during a WB fight (i thought it was lag)
Second time we fought a shaman with friends.
Third time was i fighting a shaman and sorc (this time i was in grace specc and i was solo,not in group)
Fourth time i fought solo against shaman and a sorc.

Could there be a bug with shaman (maybe combined with sorc) AP drain skill,wich allow them to even drain RF?

I have checked combat log but did not find anything strange.
I have never had this issue before.

Regards,

Warfare80

**Comment by sioding** [comment]
Thanks for the report but its kinda vague - i am not sure how we should be able to reproduce it. If anyone can give more information about this ... please do

**Comment by sioding** [comment]
no answer for 25 days. close
