### ISSUE TITLE
not a bug - legend and infamy

### ISSUE THREAD

**Issue by knthrak** [WarEmu/WarBugs#13796]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
'Central spike' object in legend and infamy quest chain is incredibly hard to find because it is sitting in long grass.  two players spent close to 10 minutes searching the area back and forth until one player got stuck on the item to find it.

**Steps to reproduce the problem:**

Per picture - spike is very hard to see.

**Screenshots/Videos or archive.org evidences:**

![central spike](https://user-images.githubusercontent.com/48619966/55551443-8730b200-5726-11e9-9c53-6781f1be90f0.png)

**Comment by sioding** [comment]
fixed with patch from 06.04.2019
