### ISSUE TITLE
Auras from Chosen

### ISSUE THREAD

**Issue by lordhomungus** [WarEmu/WarBugs#13794]
The Auras of the Chosen are not always active but it shows as active in the Skillbar.
Sometimes its shows that they are 4 auras active but non is.
Other Times it shows non active but there are 3 active.
and sometimes it doubles the Auras

**Comment by sioding** [comment]
Thanks for the report but its kinda vague - i am not sure how we should be able to reproduce it. If anyone can give more information about this ... please do

**Comment by Stebraul** [comment]
I know what he's talking about, they still have the ring around them in the skill bar as if they are active, but when targeting yourself they don't appear as buffing you, indicating they're falsely showing as active in the skill bar.

**Comment by lordhomungus** [comment]
the bar shows that there are auras active for example but they are not. and some times they active and non in the bar is my mate had 4 auras active and they showed active its a little bit broken with active and non active

**Comment by sioding** [comment]
And still no chance to reproduce it with your informations. we need more help

**Comment by sioding** [comment]
No answer since 28 days - close
