### ISSUE TITLE
Quest loot: Sea Guard Sashes

### ISSUE THREAD

**Issue by knthrak** [WarEmu/WarBugs#13790]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Item Sea guard sash must be collected *5 for quest Guards of the Sea in Chrace.  Item continues to drop even after collecting all 5 sahes cluttering quest inventory

**Steps to reproduce the problem:**
Get quest (DE chapter 3), kill seaguard >5 times

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment]
fixed with patch from 06.04.2019
