### ISSUE TITLE
Cannot use abilities after using the cannon in scenario talabec Dam.

### ISSUE THREAD

**Issue by Nexz89** [WarEmu/WarBugs#13798]
**Expected behavior and actual behavior:**

- Expected behavior is to be able to use abilities after releasing the cannon in the spawn point of the scenario Talabec Dam.

- The actual behavior is that after using the cannon in the spawn area, the abilities cannot be used on the character.

**Steps to reproduce the problem:**

Nothing works till you die once in the scenario.

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment]
Duplicate of #13203
