### ISSUE TITLE
Runepriest attack visuals do not disappear unless log off. happens every time on all chars.

### ISSUE THREAD

**Issue by deLunel** [WarEmu/WarBugs#13792]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Would expect visual to disappear after attack wears off. Dont know name but I figure staff will know the ability as very distinct visual

**Steps to reproduce the problem:**
I dont play order but since happens every time I am hit with whatever it is and I hear other people say happens to them as well should be v easy to replicate.

**Screenshots/Videos or archive.org evidences:**
Trying to attach screenshot (am not computer literate)
![Wot_000](https://user-images.githubusercontent.com/26348163/55429350-8dd6f200-558b-11e9-9696-6fa323e962a2.jpg)

**Comment by grunbag** [comment]
Anyone could give me this ability name?

**Comment by grunbag** [comment]
Can’t reproduce

**Comment by grunbag** [comment]
i fixed it i think previously
