### ISSUE TITLE
Quest Reward Not Awarded

### ISSUE THREAD

**Issue by Ben572** [WarEmu/WarBugs#1379]
Upon completion of the quest "A Son's Sacrifice" the choice of several trophies are offered as a reward. I selected the "Holy Relic" trophy and hit complete - and when I looked in my bags, the trophy was not given to me. I don't suppose there's any way to get it back, is there?

**Comment by Reggaewaldo** [comment]
This is a know bug and we are looking into it.

Refering to autocompletion #1308

**Comment by Evildoor** [comment]
Closing since #1704 has more info about the problem.
