### ISSUE TITLE
Skill Pandemomium tiks forever/Guard dmg even miles away from my mate

### ISSUE THREAD

**Issue by JustDust1** [WarEmu/WarBugs#13793]
Was guarding my teammate Lionmilk.

And got guard dmg with no enemies around in the warcamp. Even died from it.

![Ashtat_006](https://user-images.githubusercontent.com/49010900/55453936-2d24d500-55de-11e9-990b-b1e0e7f27e9e.jpg)

**Comment by JustDust1** [comment]
seems to be a bug with prolonged combat, cant get out of combat, still taking dmg.

Pandemonium might have something to do with it, got msg that pandaemonium hitted me.

**Comment by JustDust1** [comment]
Did happen to me again, Pandemonium tiked forever till i died, there is definately a bug with this magus ability

**Comment by JustDust1** [comment]
there might be two bugs with that pandemoium ability, did take dmg from guard even when my guard target was far away from me.

**Comment by sioding** [comment]
Duplicate of #13793
