### ISSUE TITLE
[Gunbad Left] Portal to boss room sometimes teleports to Altdorf

### ISSUE THREAD

**Issue by Slaynot** [WarEmu/WarBugs#13799]
**Expected behavior and actual behavior:**

The portal that leads to the boss room in left wing sometimes teleports you in Altdorf instead of in the boss room as it should.

It seems pretty random as it can happen multiple time in row on the same character or not at all.

**Steps to reproduce the problem:**

Take the portal that leads to the boss room in gunbad left wing.

**Comment by Hargrim** [comment]
Some occurrences of this were fixed, we are still looking into some more examples or ways to reproduce this.

**Comment by grunbag** [comment]
fixed already

**Comment by Rydiak** [comment]
Happened again. Reopening.

**Comment by Kaelang** [comment]
Another patch was pushed 20/05. Please update if this issue persists.

**Comment by Kaelang** [comment]
Closing as issue does not look like it's continuing post-patch.
