### ISSUE TITLE
Character Issues. Always appear next to healer upon login.

### ISSUE THREAD

**Issue by Fizzrib** [WarEmu/WarBugs#13800]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Only happens with character named "Wankytank", other characters function normally.
Expected: Log out in while character in one location, log back in to character in same location.
Actual: Log out anywhere in zone, log back in next to healer.

**Steps to reproduce the problem:**

Logging out / logging in

**Screenshots/Videos or archive.org evidences:**

https://imgur.com/a/YoYgVER

**Comment by raptrr** [comment]
still happening to your char @Fizzrib ?

**Comment by Fizzrib** [comment]
Unsure. Haven't had time to play in quite a few months.

**Comment by raptrr** [comment]
Can you, if your time allows, give it another try? And, if possible, record it? Thanks :)
