### ISSUE TITLE
T2 Greenskin Epic quest: Boss Huntin'

### ISSUE THREAD

**Issue by insultus** [WarEmu/WarBugs#13806]
Unable to continue past step 8 of this quest chain

**Expected behavior and actual behavior:**
Quest hand in and unable to "talk" to the npc

**Steps to reproduce the problem:**
Abandoned the quest and picked it up again with the same result

**Screenshots/Videos or archive.org evidences:**
![Bolloked_000](https://user-images.githubusercontent.com/35734524/55669667-b4659780-58c1-11e9-99fc-a4dd51c8ec5d.jpg)

**Comment by Bengen2019** [comment]
I'm having the same problem

**Comment by Oldneko** [comment]
same problem for me too

**Comment by sioding** [comment]
Fixed with patch from 13.04.2019
