### ISSUE TITLE
[WH] [Abilitie] Blessed Bullets of Confession

### ISSUE THREAD

**Issue by Elratie** [WarEmu/WarBugs#1380]
has a 5s timer at the moment but should be 10s like the rest

**Comment by Evildoor** [comment]
Uh, what "the rest"? Bullets of Purity - 10 sec, Bullets of Confession - 5 sec, Bullets of Cleansing - instant effect, and it was this way on live. Check the client tooltips.

**Comment by Thorgatin** [comment]
http://waronlinebuilder.org/#career=wh;
