### ISSUE TITLE
RVR Loot Delivery

### ISSUE THREAD

**Issue by Crothus** [WarEmu/WarBugs#13804]
I believe you now have to stay within an RVR zone until the PQ timer finishes to receive loot. After winning a bag yesterday and booking out of a zone it never materialized. Today I had a bit of time early and played for a bit, came back hours later after zone had flipped (I had logged in zone) and collected my bag 'o poo. Later after locking BC I moved immediately to SL after winning a bag. It also never showed. That's a gold and a blue I've missed.

**Comment by sioding** [comment]
Thanks for the report but its definitly not the reason why bags are missing - i do always zone out of the flipped one to the next - and got my bags - and sometimes i don't get it. There is something wrong - yes - but more than one had a look into into it and atm we can't hand out a fix for it. Wait for the next server restart and 98% of all bags are delivered. Some are still missing ...
