### ISSUE TITLE
Forest Foe incorrect mob name.

### ISSUE THREAD

**Issue by TenThousand1** [WarEmu/WarBugs#13809]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Expected to go to the marked area to search for and kill Gloomsap Spites as the quest tracker says. I received credit for the Spites by killing Gloomsap Skitterfiends. 

**Steps to reproduce the problem:**
Accept quest Forest Foe. Travel to area. Kill Gloomsap Skitterfiend and notice how you attain kill credit for Gloomsap Spites.

**Screenshots/Videos or archive.org evidences:**
![Banis_024](https://user-images.githubusercontent.com/49353584/55676702-d863b180-589e-11e9-80c6-a305f74b9ecb.jpg)

**Comment by Kabucoror** [comment]
Gloomsap Spites means Glooamsap Skitterfiend and Gloomsap Gloomsap Fiend should count. So everything is fine here.
