### ISSUE TITLE
Icon from Redeye Gloves

### ISSUE THREAD

**Issue by Ghatisgob** [WarEmu/WarBugs#13805]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
The icon from Redeye Bracers is a chest and not gloves as it should be. 
*Edit : I just saw that when you put the redeye gloves with the wrong icon as appearance, it changes the gloves AND the chest appearance.*

**Steps to reproduce the problem:**
Having Redeye gloves from Magus

**Screenshots/Videos or archive.org evidences:**
https://imgur.com/a/hzeKJKV

**Comment by grunbag** [comment]
fixed for next patch
