### ISSUE TITLE
Repeteable animation while Stunned

### ISSUE THREAD

**Issue by arcasis** [WarEmu/WarBugs#13816]
Issue: Repeteable hability animations while Stunned .

Class: RunePriest

Habilities:  All of them, casteables and instant.

Description of issue: When you get stunned and the animation begins(when your character lie on floor) you can spam any hability , the animation and all the effects begins to repeat everytime you push a hability. It should be blocked as I remember from official.

Sorry no screenshoots can be attached as I have a Issue with my Screenshots and I get lost them. Will try to update soon as possible.

**Comment by grunbag** [comment]
Where did it happened

**Comment by sioding** [comment]
Fixed with patch from 27.04.2019
