### ISSUE TITLE
holmstein revisted PQ bug

### ISSUE THREAD

**Issue by edpeachtree** [WarEmu/WarBugs#13812]
I understand the issue has been resolved in the past, but it again appears to be bugged, unable to loot the supplies to advance. Oddly this is also affecting the Deadly Task quest, as the needed NPCs will not spawn.

**Comment by Lheana** [comment]
This hasn't been fixed, this is the same issue as #10862.
Sadly nothing we can fix for now. Wait for a server restart, and hope it fixes it.
