### ISSUE TITLE
[Quest] Out of favor: Conquering the Raven

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13814]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Actual:

Issue 1:
Quest tooltip don't match the description i ToK

Issue 2:
Can't turn-in completed quest to Egil Liferender

Expected:

Issue 1:
Quest tooltip should match the ToK and should go like this:
Speak to Griffon Myrmidon 0/1
Kill Griffon Myrmidon 0/5
Kill Griffon Pikeman 0/2
Kill Griffon Vindicator 0/3

Issue 2:
After killing last of the mobs and "questioning" Myrmidon, quest marker should disappear and quest should be turnable.

**Steps to reproduce the problem:**

Take the quest

**Screenshots/Videos or archive.org evidences:**
![Bjoorn_048](https://user-images.githubusercontent.com/18528095/55682923-0c3fe500-593a-11e9-8a25-b604b3574ab6.jpg)
![Bjoorn_052](https://user-images.githubusercontent.com/18528095/55683051-7ad17280-593b-11e9-9a24-efab8e812951.jpg)

**Comment by sioding** [comment]
Fixed with patch from 13.04.2019
