### ISSUE TITLE
Honoring the Fallen Quest cannot be completed due to looting issues.

### ISSUE THREAD

**Issue by Carnifex-Xiii** [WarEmu/WarBugs#13818]
Honoring the Fallen Quest is bugged and you cannot loot the Gems of Protection from the Dead Combatants.

**Expected behavior and actual behavior:**
Should be able to loot the Dead Combatants to progress the quest.

**Steps to reproduce the problem:**
Do the quest, will not be able to loot the Gems of Protection.

**Screenshots/Videos or archive.org evidences:**

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 13.04.2019
