### ISSUE TITLE
Crashing right after loading screen when trying to log in game with my old character

### ISSUE THREAD

**Issue by ThePyre** [WarEmu/WarBugs#13817]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Hello

Whenever I try to log in with an old characer I havent played for a long time, the game crashes to desktop right after the loading screen. I made an alt character and he logs in fine. I have tried the /stuck command and I still ctd

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment]
Thanks for the report but the bugtracker is for ingame problems only. You can get technical support here: https://www.returnofreckoning.com/forum/viewforum.php?f=4 and for your problem it seems to be better to write a report for the GM's ingame with another character.
