### ISSUE TITLE
Redeye icon/appearance

### ISSUE THREAD

**Issue by Hanceth** [WarEmu/WarBugs#13813]
**Expected behavior and actual behavior:**

I want to report a few minor issue on the recent redeye armor changes (Keeper and Redeye sets now have a appropriate appearance according to their level in RoR.) that i didnt find in bugtracker yet. I only observed this for my ironbreaker, didnt check other classes.

1) Redeye Klad (chest for ib): wrong icon, it shows a helmet
2) Redeye Klad (chest for ib): no appearance if you wear this chest (naked dwarf appearance). Nevertheless, the appearance can be changed to e.g. rare fortune klad in the appearance tab.
3) Redeye Greathelm (helmet for ib): the appearance of this item is different if you are in game (there is a new appearance after the latest change, looks similiar to rare fortune) or if you are in the login screen (there is still the appearance of redeye before the latest change, that is a helmet with 2 small horns). 

**Steps to reproduce the problem:**

For 1) have a look at the item in your backpack.
For 2) just equip / reequip the specific item
Fpr 3) Equip the item, and relog to char screen.

**Screenshots/Videos or archive.org evidences:**

For 1) and 2):
![Hanceson_027](https://user-images.githubusercontent.com/22872475/55681772-8ec0a880-592a-11e9-8d16-238a5a6625f1.jpg)

**Comment by grunbag** [comment]
fixed for next patch

**Comment by sioding** [comment]
Fixed with patch from 13.04.2019
