### ISSUE TITLE
Squig lobba in the PQ Da Orkwerks Stage II are untargetable

### ISSUE THREAD

**Issue by AshuranRhapsody** [WarEmu/WarBugs#13811]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Squig lobba in the PQ Da Orkwerks Stage II are untargetable makes the PQ unbeatable.

**Steps to reproduce the problem:**
Stage II of the Orkwerks PQ in High Elf Chapter 15

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment]
Fixed with patch from 13.04.2019
