### ISSUE TITLE
[Fortress] Lord bugged

### ISSUE THREAD

**Issue by elk76** [WarEmu/WarBugs#13828]
I noticed (for 2 times) that lord bugged in the lord room. He was freezed and did not attack
This happened once defending Butcher pass and another time attacking Reikwald

![Puparuolo_206](https://user-images.githubusercontent.com/46483570/55807018-bc9c1d80-5ae1-11e9-9e1e-e2ce1837fbf2.jpg)
![Puparuolo_205](https://user-images.githubusercontent.com/46483570/55807019-bd34b400-5ae1-11e9-8deb-a9dbf2ec209d.jpg)

**Comment by Torgrimmerr** [comment]
I'm going to drop a note in this issue. Today at 5:25 am est. the Keep Lord in Troll Country, did the same issue, but I will add he came outside of keep and attacked WB with keep door still up will ram hitting door still attack players outside keep freely. Sorry did not react in time to take screenshot. :(

**Comment by sioding** [comment]
Sorry these are two different issues - the Fort Lord freezed and does not attack anyone - the keeplord did it. And for the keeplord outside the inner keep doing things and do not return on his place is another ticket open.

**Comment by Torgrimmerr** [comment]
Ok i'm sorry i misunderstood, is there another ticket already opened for this bug or should i create a ticket then?
Josh

**Comment by sioding** [comment]
This should be fixed.
