### ISSUE TITLE
Smashing for Runty Gits Quest

### ISSUE THREAD

**Issue by Zalamir** [WarEmu/WarBugs#13826]
Smashing for Runty Gits Quest is bugged no one can finish quest im Zalamir the BG on Destro
thanks

**Comment by sioding** [comment]
Well - thanks for the ticket but i don't get the problem. Can you please be more specific?

**Comment by Zalamir** [comment]
Hi, the quest is bugged and cannot be able to hand it in so one can i think you may need to check it.regards
    On Tuesday, 9 April 2019, 12:02:52 BST, Sio <notifications@github.com> wrote:  
 
 
Well - thanks for the ticket but i don't get the problem. Can you please be more specific?

**Comment by Lheana** [comment]
This quest works fine. You must turn it in to the quest giver: Grumlok.
