### ISSUE TITLE
RvR Table/Chart/Map

### ISSUE THREAD

**Issue by Torgrimmerr** [WarEmu/WarBugs#13829]
The RvR map on the right of the screen the % number next to the fill up bars on all lakes in all tiers keep blanking and changing every few secs.

They should be steadily increasing as the battle goes on with each side gaining points. 

This time I'm on my lowie, 6 lvl Rune Priest. in Tier 1. Just toggle window on interface and watch the fireworks. I will include two screenshot. the first is one moment and the next screenshot 2 secs later with the numbers totally changed. Dxdiag is included as well.

Josh

![Map one](https://user-images.githubusercontent.com/49354178/55834515-1d2e5900-5ae8-11e9-8b6e-178df0d9137e.PNG)
![map 2](https://user-images.githubusercontent.com/49354178/55834559-38996400-5ae8-11e9-8ff5-e3e2fdb94e88.PNG)
[DxDiag.txt](https://github.com/WarEmu/WarBugs/files/3060950/DxDiag.txt)

**Comment by sioding** [comment]
Please use actual version of  RoR SoR: https://tools.idrinth.de/addons/ror_sor/

**Comment by Torgrimmerr** [comment]
Thank you
