### ISSUE TITLE
Auction house / duplicate items

### ISSUE THREAD

**Issue by okraslayer** [WarEmu/WarBugs#1382]
Purchased an item via the auction house and claimed the item... came back a day later and I had forgot to delete the letter from inbox. I go back and accidentally hit "take items" and the item is placed within my bag once again even though I have it equipped on my char.

**Comment by nalgol** [comment]
is this still the case?

**Comment by okraslayer** [comment]
I have not had it occur again. I left the duplicate item in my bags. Shoulders for WH. 
Date: Sun, 4 Oct 2015 13:43:42 -0700
