### ISSUE TITLE
Gunbad -  boss bugged

### ISSUE THREAD

**Issue by Elflord123** [WarEmu/WarBugs#13839]
If you go to gunbad, inside to the boss on the mounts and attack the boss without Dismounting, the animation mounts is not lost.
![image](https://user-images.githubusercontent.com/48329663/55903862-3f52d480-5bd7-11e9-985e-261af0eb1eb6.png)
![image](https://user-images.githubusercontent.com/48329663/55903882-44b01f00-5bd7-11e9-92eb-6e38428b9c04.png)
![image](https://user-images.githubusercontent.com/48329663/55903895-4bd72d00-5bd7-11e9-9179-d2fe7476c038.png)

**Comment by Kaelang** [comment]
Can no longer mount due to Terror debuff.
