### ISSUE TITLE
Npc/Monster dont can get in Target

### ISSUE THREAD

**Issue by magilb** [WarEmu/WarBugs#13830]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
I Dont get target the little Monster(Beacon Gnoblar) in the Scrennshot. My Pet the Squig but can kill them

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

![Hahrss_002](https://user-images.githubusercontent.com/49466877/55849987-052af980-5b29-11e9-8bad-57fa5d981c91.jpg)

**Comment by sioding** [comment]
Fixed with patch from 13.04.2019
