### ISSUE TITLE
Died for no Reason.

### ISSUE THREAD

**Issue by magilb** [WarEmu/WarBugs#13831]
![Hahrss_009](https://user-images.githubusercontent.com/49466877/55850226-eb3de680-5b29-11e9-8f67-615e2da8bb7d.jpg)

Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Just get DMG von my own and died instant. see the Scenshot.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**
![Hahrss_010](https://user-images.githubusercontent.com/49466877/55850167-add95900-5b29-11e9-9bcb-81e4454fdc7b.jpg)
![Hahrss_011](https://user-images.githubusercontent.com/49466877/55850177-b762c100-5b29-11e9-8d34-5a2e885ca2aa.jpg)

**Comment by magilb** [comment]
![Hahrss_009](https://user-images.githubusercontent.com/49466877/55850337-4ec81400-5b2a-11e9-957d-8a820cd2d115.jpg)

**Comment by sioding** [comment]
This is a known one - the terrain is the hardest one to conquer against. Don't jump on everything you see might help - but only might - sometime you trip over a smill nothing and you die.
