### ISSUE TITLE
Gunbad-Boss , not attackable-report

### ISSUE THREAD

**Issue by magilb** [WarEmu/WarBugs#13832]
![Hahrss_012](https://user-images.githubusercontent.com/49466877/55850389-833bd000-5b2a-11e9-9103-a7ef209e1b61.jpg)
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment]
Fixed with patch from 13.04.2019
