### ISSUE TITLE
QUEST PQ bug

### ISSUE THREAD

**Issue by Florcituzz** [WarEmu/WarBugs#13845]
**Expected behavior and actual behavior:**
Expected: to "kill" the empire wagon destroyed.
Actual: cant "kill" it.

**Steps to reproduce the problem:**
Go to the final fase of the PQ Reik River Bandits at Reikland.

**Screenshots/Videos or archive.org evidences:**

![bug](https://user-images.githubusercontent.com/48547251/55941456-a6dd4400-5c18-11e9-8887-57094175dede.jpg)

**Comment by sioding** [comment]
Fixed with patch from 13.04.2019
