### ISSUE TITLE
Renown Advancement : Displayed spent points , no abilities in abilities tab

### ISSUE THREAD

**Issue by Jerloldrartolf** [WarEmu/WarBugs#13846]
**Expected behavior and actual behavior:**
renown advancement spent points must equal the sum of abilities trained
Take note that the ability window does not have multiple pages and so those are all that are displayed.
**Screenshots/Videos or archive.org evidences:**
![Capture](https://user-images.githubusercontent.com/48033566/55949558-c8efba00-5c4a-11e9-817b-b5529d7057c3.PNG)

**Steps to reproduce the problem:**
Dont know.
I just looked at the values and they should not be 30.
I am guessing that this is a missing requirement/ validation that could be triggered when initiating conversation with the renown ability trainer.

**workaround:**
I guess respec would be the workaround.(Just respeced and my spent went to Zero and available where to zero as also attached below)
![Capture after respec](https://user-images.githubusercontent.com/48033566/55949717-2b48ba80-5c4b-11e9-8c3c-ca6b6d666661.PNG)
)

**Comment by sioding** [comment]
Can you test it again please? Stand near (i mean really near) the trainer and have him targeted ( don't lose the target ). Train again and check if its all good

**Comment by Jerloldrartolf** [comment]
Cant re-pro. On this occasion it works.

**Comment by sioding** [comment]
good - thanks for the retest - thats the way it should work cause we need to make sure no one gets the wrong renownpoints/abilities
