### ISSUE TITLE
Kotbs solar flare m4

### ISSUE THREAD

**Issue by fierdal** [WarEmu/WarBugs#13842]
I play a kotbs (fierdal) and my m4 solar flare says it is supposed to take away all of the enemies moral in 30 yards. Just tested it with a friend of mine who has a 40 destro it doesnt take away the moral at all. I might be a bug or just broken. I first started noticing it when we were attacking the fort and i used it on the right side watching from my corpse I saw them using there morals and that got me thinking to a previous issue I had which i will also be posting about. But the m2, emperors champion says it increase your stats for 30 secs but it only for 15 did a test on that one as well but ill make another post for that.

**Comment by sioding** [comment]
Can we please see your and your friends testing screenshots with visible combat logs?

**Comment by fierdal** [comment]
Of course we went back out and tested it again here are the before and after screenshots from my order (fierdal) the blue knight, and a destro alt from a friend on order (flamers) the before shows me the knight with m4 morals and the after shows me hitting him in the combat log with the moral (solar flare) it says it takes away all the moral of enemies in 30 feet but in his screenshots (which he will post) he still has his moral.
![Screenshot (3)](https://user-images.githubusercontent.com/34845292/55971537-add37900-5c4f-11e9-8b6e-2a41ef3b1fc7.png)
![Screenshot (5)](https://user-images.githubusercontent.com/34845292/55971585-c3e13980-5c4f-11e9-964e-142e4ed93075.png)

**Comment by FlamersBW** [comment]
Here are the screenshots from the other side who got hit by M4, screenshot before shows at full morale and screenshot after shows M3+ ready. 

Before
![Miva_006](https://user-images.githubusercontent.com/49529558/55972024-56eb9500-5c8b-11e9-82ef-8ba461a03aec.jpg)

After
![Miva_008](https://user-images.githubusercontent.com/49529558/55972069-6cf95580-5c8b-11e9-8987-96233d9ee98d.jpg)

**Comment by sioding** [comment]
Nice - Thanks for the additional work and the screens.

**Comment by grunbag** [comment]
Fixed at next patch

**Comment by sioding** [comment]
Fixed with patch from 11.05.2019
