### ISSUE TITLE
Wrong loot in gold back from Butcher's Pass Fort

### ISSUE THREAD

**Issue by MaximillianDiE** [WarEmu/WarBugs#13844]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
I (Maxximillian BW) was sent a gold bag in the mail after Order took Butchers Pass.  When I opened it up it contained Vanquisher Boots/5 Vanq medals which was clearly wrong as it should have contained invader gear/medals.  Here is a screenshot of the open mail and the open bag that was attached to it showing this.

**Steps to reproduce the problem:**
1. Do a fort
2. Win a bag
3. Find the wrong tier rewards in it.

**Screenshots/Videos or archive.org evidences:**
![Mailbox 1](https://user-images.githubusercontent.com/47707958/55939583-78e01a00-5c81-11e9-975d-8faac0d3bcd9.png)

**Comment by dalen** [comment]
It seems like the mail's always say the next zone instead of the zone the bag is actually from. So that's a bag you won in Black Crag most likely.

**Comment by MaximillianDiE** [comment]
I have never seen a bag say the next zone and I have received quite a few now (rr73, 6 piece invader now on my main), but I have heard of other people getting Vanq gear in invader bags from forts so unlikely.  Best to report an issue like this and let the devs look into it.

**Comment by Natherul** [comment]
Should have been fixed with the patch from yesterday
