### ISSUE TITLE
Arcing Power doesn't work on DoTs

### ISSUE THREAD

**Issue by Kaspi123** [WarEmu/WarBugs#1384]
Tactics Arcing Power does not work with abilities: Radiant Gaze and Law of Conductivity

**Comment by ozarmidrashim** [comment]
Arcing Power is implemented as an event handler listening for direct damage from any ability scaling with Intelligence that the Archmage uses. Radiant Gaze and Law of Conductivity are both DoTs.

**Comment by ozarmidrashim** [comment]
Forum thread confirms that this ability shouldn't work with DoTs - closing per that.
