### ISSUE TITLE
Floating mutilated sheep.

### ISSUE THREAD

**Issue by weasy** [WarEmu/WarBugs#13852]
Mutilated sheep in Talebecland and Serpant's Fang Bandits PQ floats .

**Expected behavior and actual behavior:**
For sheep to lay on the ground instead of over goblin's head.

**Steps to reproduce the problem:**
Walk to Sheep and see it float.

Reporting Character Weasy

**Comment by Lheana** [comment]
See #15189 for the general issue with floating GOs.
