### ISSUE TITLE
[Quest] Tomes of Knowledge

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13857]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Expected behavior:
There should be a quest marker above Eredican

Actual behavior:
There isn't

**Steps to reproduce the problem:**

Take the quest and follow.

**Screenshots/Videos or archive.org evidences:**

![Gwarnhil_001](https://user-images.githubusercontent.com/18528095/56060212-76a3bb80-5d66-11e9-95be-6b780a2946b6.jpg)

**Comment by Lheana** [comment]
This has been fixed several patches ago. The NPC needed to be updated upon accepting the quest.
