### ISSUE TITLE
[Apothecary] Special Squig Bits

### ISSUE THREAD

**Issue by Jonees123** [WarEmu/WarBugs#13851]
![kuva](https://user-images.githubusercontent.com/47939256/55990658-ec4d5000-5cb0-11e9-8e56-cdff4eaf6b56.png)
This item works as the description says (Multiplier), but it says Extender on top.

**Comment by Kabucoror** [comment]
actually they are Multiplier
fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 27.04.2019
