### ISSUE TITLE
Problem with Tactic Sorceless: Tapping the Dark

### ISSUE THREAD

**Issue by Diezhix** [WarEmu/WarBugs#13855]
Hi,

This tactic proc when i dont using it.

![InkedXihzeid_010_LI](https://user-images.githubusercontent.com/38187436/56022438-fc464d80-5d0b-11e9-99e5-fb872aa1f824.jpg)

Thanks you

**Comment by Diezhix** [comment]
![Xihzeid_014](https://user-images.githubusercontent.com/38187436/56024281-f8b4c580-5d0f-11e9-80b6-c8f0a04991f4.jpg)

can be using in party. I have 5 tactics on

**Comment by grunbag** [comment]
Fixed at previous patch
