### ISSUE TITLE
[Quest] Sins of the past

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13858]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Expected:
Quest tooltip should match ToK:
Quest Waypoint
* Kill Dark Spites 0/6

Actual:
It doesn't

**Steps to reproduce the problem:**

Take the quest

**Screenshots/Videos or archive.org evidences:**

![Gwarnhil_000](https://user-images.githubusercontent.com/18528095/56060349-def29d00-5d66-11e9-8da1-3ca9c0ee0ffa.jpg)

**Comment by sioding** [comment]
fixed with patch from 10.06.2019
