### ISSUE TITLE
Aura Spread Failure

### ISSUE THREAD

**Issue by Gargatyk** [WarEmu/WarBugs#1385]
Trying to enter a WB as Chosen and getting the "The party is full." message removes all Chosen auras and doesn't allow to use them further, saying "Aura spread failure - one of your auras was removed." when you try to use one. 
Entering and the leaving any other WB (Maybe this'll work with party too) fixs this problem.

**Comment by kiefer79** [comment]
Same on WP

**Comment by kiefer79** [comment]
![aura_spread](https://cloud.githubusercontent.com/assets/3509209/9861276/85ca0b86-5b31-11e5-8afc-13a7f855e276.jpg)

**Comment by Skutrug** [comment]
The bug is still here - still related to an attempt to join a WB/Group that is full. Joining and leaving a scenario and relogging are the only two methods known to remove the bug once started.

**Comment by Kushido** [comment]
didnt realize it started to be on chosen after i tried to join wb or not
but yesterday i couldn't activate any aura in ORvR instead of only one with healing reduction (3rd tree)
relog not fixing this problem
only if i join sc - my auras starting to work properly
after sc ended and i was back to ORvR - auras also started to work properly

**Comment by wiscel** [comment]
Have the same on my DoK, it happens to me in TC/Ostland zone, it removes the DoK Covenant.

**Comment by taccr** [comment]
This bug happens only when the client warband window shows available slots:
e.g. 23/24 players.
If someone else joins the warband during that time and you don't refresh the warband window it will trigger this bug.

It does not happen when the window displays a full party (24/24).

**Comment by danissrv** [comment]
Any update with this?

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
