### ISSUE TITLE
[Quest] Silencing Hans

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13868]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Expected:
Quest tooltip should say:
Quest waypoint
* Corruptive Tomes Burnt 0/1

Actual:
It doesn't

**Steps to reproduce the problem:**

Take the quest

**Screenshots/Videos or archive.org evidences:**

![Gwarnhil_014](https://user-images.githubusercontent.com/18528095/56084114-ac13dc00-5e2e-11e9-97c4-c937d4bbd527.jpg)

**Comment by sioding** [comment]
Fixed with patch from 15.06.2019
