### ISSUE TITLE
[Quest] A Difficult Choice

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13861]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected:
Quest tooltip should match ToK:
Quest Waypoint
* Wounded Calumel Citizen healed 0/1

Actual:
It doesn't

**Steps to reproduce the problem:**

Take the quest

**Screenshots/Videos or archive.org evidences:**

![Gwarnhil_006](https://user-images.githubusercontent.com/18528095/56060663-cc2c9800-5d67-11e9-9258-69a6e9b3b130.jpg)

**Comment by sioding** [comment]
fixed with patch from 10.06.2019
