### ISSUE TITLE
[Quest] Long Overdue

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13869]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Expected:
Quest tooltip should say:
Quest Waypoint
* Find Eosthir Thornwrath 0/1

Next Step tooltip:
Quest waypoint
* Speak with Warden Teriel 0/1

Actual:
It doesn't

**Steps to reproduce the problem:**

Take the quest

**Screenshots/Videos or archive.org evidences:**

![Gwarnhil_015](https://user-images.githubusercontent.com/18528095/56084137-0dd44600-5e2f-11e9-972a-14e872304efc.jpg)

Next step:
![Gwarnhil_025](https://user-images.githubusercontent.com/18528095/56084614-a241a700-5e35-11e9-9c39-c4d5aef142a9.jpg)

**Comment by sioding** [comment]
Fixed with patch from 15.06.2019
