### ISSUE TITLE
Potion without buff

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13862]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected:
Issue 1:
Quest tooltip should match ToK:
Quest Waypoint
* Cold Ones 0/5

Issue 2:
Quest should give some good potion reward

Actual:
Issue 1:
It doesn't

Issue 2:
There is a useless potion reward

**Steps to reproduce the problem:**

Take the quest

**Screenshots/Videos or archive.org evidences:**

Issue 1:
![Gwarnhil_009](https://user-images.githubusercontent.com/18528095/56060847-41986880-5d68-11e9-88b6-942c0f83c3c4.jpg)
Issue 2:
![Gwarnhil_007](https://user-images.githubusercontent.com/18528095/56060869-4bba6700-5d68-11e9-84b0-c867ade90788.jpg)

**Comment by Lheana** [comment]
The quest part will be fixed with next patch. Item one is not fixed.
