### ISSUE TITLE
Invader bonus for wh

### ISSUE THREAD

**Issue by rhix112** [WarEmu/WarBugs#13867]
Invader bonus 5 and 7 doesn't work at all, plz check it

![Feroze_000](https://user-images.githubusercontent.com/31020540/56083806-9f918280-5e32-11e9-9815-d748237ee26d.jpg)
![Feroze_001](https://user-images.githubusercontent.com/31020540/56083807-9f918280-5e32-11e9-8cd3-782d07c0cd87.jpg)

**Comment by grunbag** [comment]
I dot see what is not working

**Comment by rhix112** [comment]
look there is no any change on dps aa 220 first screen and another screen with no 5 bonus, there same dps 220

**Comment by rhix112** [comment]
7th bonus invader didn't do anything, i tested him no any damage on parry or block

**Comment by grunbag** [comment]
Fixed for next patch
