### ISSUE TITLE
[Quest] Decisive Imbalance

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13864]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Expected:
Issue 1:
Quest tooltip should match ToK:
Quest Waypoint
* Arkaneth Warriors 0/4
* Arkaneth Reapers 0/4
* Arkaneth Enforcers 0/4

Issue 2:
Quest marker should stay until You kill all described mobs in the area

Actual:
Issue 1:
It doesn't

Issue 2:
Quest marker disappears after killing Arkaneth Warriors

Steps to reproduce the problem:

Take the quest

Screenshots/Videos or archive.org evidences:

Issue 1:
![Gwarnhil_013](https://user-images.githubusercontent.com/18528095/56063178-d56d3300-5d6e-11e9-9839-685d23a8bdf7.jpg)

**Comment by sioding** [comment]
fixed with patch from 10.06.2019
