### ISSUE TITLE
[Quest] Hope Renewed

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13860]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

Expected:
Quest tooltip should match ToK:
Quest Waypoint
* Speak with Prince Eldrion  0/1

Actual:
It doesn't

**Steps to reproduce the problem:**

Take the quest

**Screenshots/Videos or archive.org evidences:**

![Gwarnhil_003](https://user-images.githubusercontent.com/18528095/56060493-4dcff600-5d67-11e9-9951-f29e4fe6844d.jpg)

**Comment by sioding** [comment]
fixed with patch from 10.06.2019
