### ISSUE TITLE
[RvR] Door repair not functional on downed door

### ISSUE THREAD

**Issue by Skarx** [WarEmu/WarBugs#13874]
Hello,
**Expected behavior and actual behavior:**
Returning supplys repair door that has been damaged, but once a door is down, it doesn't seem to repair at all. We returned more than  supplys in TM tonight, and nothing happened (with Cature and Huguenon WBs).
Also didn't work in Shadowland and Praag (for Destros)

It also means we aren't able to rank up keeps that has a downed door

**Steps to reproduce the problem:**
Destroy the door and return supplys to repair it

**Screenshots/Videos or archive.org evidences:**
No videos taken sorry

Thank you,
Skr

**Comment by sioding** [comment]
fixed with patch from 20.04.2019
