### ISSUE TITLE
[Quest] A Light Across Ulthuan

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13873]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Expected:
Quest tooltip should say:
Quest Waypoint
* Speak to Kyrinn Silversea 0/1

Actual:
It doesn't

**Steps to reproduce the problem:**

Take the quest

**Screenshots/Videos or archive.org evidences:**

![Gwarnhil_024](https://user-images.githubusercontent.com/18528095/56084638-08c6c500-5e36-11e9-9f63-507c5bc2ba88.jpg)

**Comment by sioding** [comment]
Fixed with patch from 15.06.2019
