### ISSUE TITLE
[Quest] Tireless Honor

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13872]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Expected:
Issue 1:
I'm not sure but I think that after killing 3 Arkaneth Corsairs, I should be able to speak to one of Mournfire brothers. Quest mark points out the Geran Mournfire.

Issue 2:
Quest tooltip should say:
Quest waypoint
* Fight off Arkaneth Corsairs 0/3

Actual:
Issue 1:
After killing Corsairs quest mark appears on map to speak with Geran Mournfire, but I cannot.

Issue 2:
Tooltip is wrong

**Steps to reproduce the problem:**

Take the quest and kill Arkaneth Corsairs

**Screenshots/Videos or archive.org evidences:**
Issue 1:
![Gwarnhil_023](https://user-images.githubusercontent.com/18528095/56084565-0c0d8100-5e35-11e9-8f2f-0ae8fe7b7afe.jpg)

**Comment by sioding** [comment]
Fixed with patch from 15.06.2019
