### ISSUE TITLE
[Zealot] Ritual of ...

### ISSUE THREAD

**Issue by bozzax** [WarEmu/WarBugs#1387]
If you click ritual and place it out of range (seems to be a range check here unknown range) it misfires but gets CD (on ability)

**Comment by Evildoor** [comment]
I confirm (have not tested all of them though). Maybe RP's Master Runes share this problem.

**Comment by Evildoor** [comment]
Now, if you place ritual out of range, it will be placed at the nearest point in range. Closing.

**Comment by Evildoor** [comment]
#1118.
