### ISSUE TITLE
[Quest] Shadow Vantage

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13871]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Expected:
Issue 1:
There should be two Keenbow scouts, One watching Ark, and one watching barracks.
The one implemented is ok but after clicking on him only "Black Ark Reports 1/1" should trigger.
The second one should be around 52K 16K, and after clicking on him "Arkaneth Barracks Reports 1/1" should trigger finishing the quest.

Issue 2:
There should be two quest marks. One near the Ark (implemented) saying:
Quest waypoint
* Black Ark Reports 0/1
The second one near barracks saying:
Quest waypoint
* Arkaneth Barracks Reports 0/1

Actual:
Issue 1:
There is only one scout near Ark, that after clicking finishes the quest.

Issue 2:
Quest tooltip is incorrect

**Steps to reproduce the problem:**

Take the quest.

**Screenshots/Videos or archive.org evidences:**

![Gwarnhil_021](https://user-images.githubusercontent.com/18528095/56084518-314dbf80-5e34-11e9-9154-b9a8600b9d38.jpg)
![Gwarnhil_022](https://user-images.githubusercontent.com/18528095/56084519-314dbf80-5e34-11e9-92cd-9f7ef6b8ed63.jpg)

**Comment by Lheana** [comment]
The two scouts are already correctly spawned.

**Comment by sioding** [comment]
fixed with patch from 10.06.2019
