### ISSUE TITLE
Horrible lag in server, umplayeable.

### ISSUE THREAD

**Issue by Florcituzz** [WarEmu/WarBugs#13876]
*Expected behavior and actual behavior:**
To play without lag, or not a lot… xD

**Steps to reproduce the problem:**
Just connect, and every min you Will have like 5646874531 ms lag, we are right now about to go fort on elfs, and the server crashed to server select / char server twice.
Cant play with this lag, all of us are in the same situation.

**Screenshots/Videos or archive.org evidences:**
Havent evidences, but all people are talking about that in the chat.

**Comment by Florcituzz** [comment]
I think there are something wrong with the patch of today, because it is happening 10 hours ago, aprox.

**Comment by Florcituzz** [comment]
![bug](https://user-images.githubusercontent.com/48547251/56090808-911c8880-5e7d-11e9-8e66-17081bfdb5e4.png)
people saying "server is dying" "my screen stuck", etc etc

**Comment by Florcituzz** [comment]
And now it crashed to char select 3rt time in a row.

**Comment by wargrimnir** [comment]
We're aware. Stop spamming the bugtracker.

**Comment by Natherul** [comment]
should have been fixed now
