### ISSUE TITLE
[Marauder] Tactic Corrupted Edge not functional

### ISSUE THREAD

**Issue by Alfred19** [WarEmu/WarBugs#13877]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
>done, nothing open

**Expected behavior and actual behavior:**
>Using tactic should grant 160Str + 160Ini
>Does not

Verified with .getstats and Character window

**Screenshots/Videos or archive.org evidences:**
![Instability](https://user-images.githubusercontent.com/37483326/56090649-36972280-5ea5-11e9-8474-640c0f0ebb88.jpg)

**Comment by DanskuL** [comment]
Does work.
https://youtu.be/i5TJguPqSkI
you're probably not in the correct stance, you're also linking Growing Instability which is the complete wrong tactic.

**Comment by Alfred19** [comment]
Pretty embarrasing. I t seems i had a bit too less sleep this day.
Sry for the trouble, closing.
