### ISSUE TITLE
[Tooltip] Chop fasta! CD still shows 60sec

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#13880]
The CD of Chop fasta! has been lowered to 40s with last patch. Seems like the tooltip has been overlooked.
![cfcd](https://user-images.githubusercontent.com/40274248/56097125-aed70580-5ef0-11e9-85cb-0055cfcb0887.jpg)

**Comment by grunbag** [comment]
I am away for the week , but it will be fixed

**Comment by sioding** [comment]
Fixed with patch from 27.04.2019
