### ISSUE TITLE
no influence at sumit suppies t2-t4 

### ISSUE THREAD

**Issue by Enoelxx** [WarEmu/WarBugs#13883]
When somebody submits the Supplys in T2-4 Areas to the keep or flag at WC there is no Influence is generated

![Enoo_097](https://user-images.githubusercontent.com/19532295/56126125-be029580-5f7a-11e9-80fa-29c0fc9afdb5.jpg)

**Comment by sioding** [comment]
fixed with patch from 20.04.2019
