### ISSUE TITLE
[Quest] Stunties is fer stuffin' - Wrong order of objectives

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#13889]
**Expected behavior and actual behavior:**

The quest objectives on this quest has to be completed in the wrong order, you can't get dwarf first and then put in barrel.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

![Zhapp_010](https://user-images.githubusercontent.com/7400/56167214-de147200-5fd7-11e9-8f26-c235c75ea5d7.jpg)

**Comment by sioding** [comment]
fixed with patch from 20.04.2019
