### ISSUE TITLE
Show of Power trophy quest broken

### ISSUE THREAD

**Issue by Judart** [WarEmu/WarBugs#1388]
When you chose 5+ reward got nothing. First 4 reward trophy works fine.

**Comment by Thorgatin** [comment]
And which quest (name etc. pp.)?

**Comment by Judart** [comment]
Norsca "Show of power" it's destro quest. But there 1 quest in each zone I will find and tell later.

**Comment by Judart** [comment]
Quest was ok befor trophy patch. Every character can take only 1 trophy wich able only for their race and another one which was able for all. Now in rewards you can chose all trophy but work only 4 first...

**Comment by Judart** [comment]
Destro: The Blighted Isle, npc Karaa Ravenseer, quest "Birds of a Feather";
Norsca, Madgr the Soulreaper, "Show of power";
Mount Bloodhorn, Mugrush Gutsticka, "Stunties is fer Stuffing".
Order: Nordland, Jakob Hebel, "A son's Sacrifice";
Ekrund, Borgor Firenson, "Digger's duds";
The Blighted Isle, Grunda Aleheart, Seems quest "Reluctant Hand" was giving tropyes trophies in off WAR but now only gold in rewards.

**Comment by Reggaewaldo** [comment]
Thank you very much for the report, this is currently being worked on by one of the team members and will be working soon.

Closing.

**Comment by Ryanfawkez** [comment]
Fixed in next patch. All trophies have been fixed to their appropriate race, so that there's a maximum of 4 choices.
