### ISSUE TITLE
[Quest] A head apart: can be done in wrong order

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#13888]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

The objectives of this quest can be completed in wrong order, should have to kill first to collect the head.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

![Zhapp_011](https://user-images.githubusercontent.com/7400/56166976-3d25b700-5fd7-11e9-8fc6-94463fa16cf9.jpg)

**Comment by sioding** [comment]
fixed with patch from 20.04.2019
