### ISSUE TITLE
The quest, Bait an' Bash! is bugged. Quest giver won't give the required item.

### ISSUE THREAD

**Issue by LordRhinark** [WarEmu/WarBugs#13882]
**Expected behavior and actual behavior:**

Expected: Gilkor Smashjaw gives Humie Meat upon quest acceptance, which is required to lure out and kill a Hungry Grove Wolf at the Sacred Grove.

Actual: Gilkor Smashjaw doesn't give the item, thus you are unable to complete the quest. The item neither shows up in the backpack under quest items, nor under inventory items. Talking to him again doesn't give the item, and abandoning and re-accepting the quest doesn't help either.

**Steps to reproduce the problem:**

1. Accept the quest, Bait an' Bash! from Gilkor Smashjaw at Kromar in Mount Bloodhorn.

2. Go to the Sacred Grove.

3. Attempt to lure out a Hungry Grove Wolf without Humie Meat.

**Screenshots/Videos or archive.org evidences:**

![Azglum_000](https://user-images.githubusercontent.com/49635572/56116283-b84e8500-5f65-11e9-8b8f-f9226fee70ff.jpg)

**Comment by Lheana** [comment]
You can complete the quest by killing the NPC that is mentionned.

**Comment by Lheana** [comment]
I have reworked the quest so that you will now have to bait the wolf with the Sack of Humie Meat.

**Comment by LordRhinark** [comment]
I just logged on and tried to abandon and re-accept the quest. Gilkor still wouldn't give the Humie Meat, but going down to the Sacred Grove, I did find the Hungry Grove Wolf standing out in the open.

I don't know if it was also there yesterday, but I only found it today. I killed it, and the quest was completed, so hooray for me I guess.

Still, the quest giver refuses to hand over the Humie Meat, even after you reworking it.

**Comment by Kabucoror** [comment]
you have to wait until the next patch

**Comment by LordRhinark** [comment]
Well, considering I did complete the quest without even having to use the Humie Meat, I don't have to wait at all, but it's nice to hear that it will at least work for others from now on.

Well, if "from now on" is after the next patch has dropped at least. I'm still relatively new around here, so I don't know the exact way that issues are handled.

**Comment by sioding** [comment]
fixed with patch from 20.04.2019
