### ISSUE TITLE
[Chap22] Damma Skar - Mount bugged with Terror-Debuff

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#13887]
We wiped during the bossfight, so I released and rod back.  Entering the Boss-area and getting the "Terror"-Debuff I also I got the notification " You are to terrified to mount your mount". At this point I was unable to dismount, but could use all my skill while on the back of my horse. Some others got this problme, too, but couldn't use skills.

_casting on mount with "Terror"-Debuff_
![mount-terror](https://user-images.githubusercontent.com/40274248/56164456-0482df00-5fd1-11e9-9ef3-78c027dce151.jpg)

**Comment by Natherul** [comment]
should be fixed as of today
