### ISSUE TITLE
DPS value Combat Hammer of the Subjugator

### ISSUE THREAD

**Issue by Marawo** [WarEmu/WarBugs#13885]
**Expected behavior and actual behavior:**
Combat Hammer of the Subjugator has the wrong DPS value,
it should be 54,4 like every other 1h subjugator weapon.

**Screenshots/Videos or archive.org evidences:**

![](https://i.imgur.com/ADsFQdj.png)

**Comment by Rydiak** [comment]
Looks like it was given Smuggler's DPS after the Smuggler nerf.  Good catch!

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 05.05.2019
