### ISSUE TITLE
[Quest] Unable to restart Will of the Warboss

### ISSUE THREAD

**Issue by Stebraul** [WarEmu/WarBugs#13896]
I started and completed the second stage (clicking on the Griffon Banner) of "Will of the Warboss" but dropped the quest before turning it into Mebunt in GS Ch11. I want to complete the quest now but I am unable to begin the stage again by speaking to Bruk in GS Ch10.

**Comment by Stebraul** [comment]
Just to be clear I have clicked on the Griffon Banner but dropped the quest soon after.

**Comment by Lheana** [comment]
Provide screenshots of your list of quest in your ToK and of the NPC Bruk.

**Comment by Stebraul** [comment]
![WAR1](https://user-images.githubusercontent.com/48854612/56262907-c2c86600-60ae-11e9-8306-c5786709d0cd.jpg)
![WAR2](https://user-images.githubusercontent.com/48854612/56262909-c4922980-60ae-11e9-9eea-de886ca3f3f2.jpg)
![WAR3](https://user-images.githubusercontent.com/48854612/56262912-c65bed00-60ae-11e9-9728-c15b096afb18.jpg)
![War4](https://user-images.githubusercontent.com/48854612/56262919-cc51ce00-60ae-11e9-97b3-227ca56e95a1.jpg)

**Comment by Lheana** [comment]
I see no reason why you could not take the quest, DB is correctly set. Maybe try to see if Mebunt gives you the quest.

**Comment by Stebraul** [comment]
I did, I figured maybe I had gotten further than I thought, no dice with him either

**Comment by sioding** [comment]
so everythings done now?

**Comment by Stebraul** [comment]
I don't know how you got that impression, no, nothing has changed, I still can't complete the quest at all

**Comment by Stebraul** [comment]
Still can't complete the quest, IDK if anyone can force the quest to be restarted for me or anything?

**Comment by Lheana** [comment]
Closing, the issue has been found.
