### ISSUE TITLE
[Quest] A Simple Request (Reikland, destro): mobs don't count

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#13892]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

It seems like none of the mobs here count towards the Followers of Morr.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

![Falinsil_003](https://user-images.githubusercontent.com/7400/56168859-ae1b9d80-5fdc-11e9-9a6f-129a838a2eba.jpg)

**Comment by Lheana** [comment]
You must loot them, they drop blood as mentioned in the quest.

**Comment by sioding** [comment]
no answer for 13 days. close
