### ISSUE TITLE
Swordmaster T1 Sc shield

### ISSUE THREAD

**Issue by Heyho18** [WarEmu/WarBugs#1389]
Hi,

The senario SM Shield "Shieldbearer's Pavise of Devotion" is missing the 1% block and should normaly be the item "Shieldbearer's Pavise of Merit" ( ID 5500039 ) as seen here   http://www.arsenalofwar.com/items/Order/Shieldbearer's%20Pavise%20of%20Merit

The Devotion one is normaly the t2 sc shield ( ID 5500239 ) http://www.arsenalofwar.com/items/Order/Shieldbearer's%20Pavise%20of%20Devotion

G'day

**Comment by herrmarek** [comment]
Shieldbearer's Pavise of Devotion cannot equip

**Comment by Reggaewaldo** [comment]
Fixed so that stats are correct, name is correct and it can be equiped. Implemented the change on the DB server. It will carry over with the next hotfix.

Closing.
