### ISSUE TITLE
[Scenario] Battle for Praag, Canons

### ISSUE THREAD

**Issue by Aluviya** [WarEmu/WarBugs#13893]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
The canons to repulse attackes back from the spawncamp are destroyable (Destruction Canons - can't confirm for Order). I am not sure if that is intendend but seems to me kinda unfair for the defenders beeing unable to leave the spawn point because they lack any additional damage by canons.

**Screenshots/Videos or archive.org evidences:**

**Comment by Aluviya** [comment]
![Galaxyglitter_019](https://user-images.githubusercontent.com/17249318/56171282-fd65cc00-5fe4-11e9-959e-d54863ea8741.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 27.04.2019
