### ISSUE TITLE
[Quest] Smashin' Heads: Doesn't spawn troll

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#13890]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

This quest should spawn a troll to kill, but it isn't there so the quest can't be completed.

This is the follow up quest to the one mentioned in https://github.com/WarEmu/WarBugs/issues/13462

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

![Zhapp_013](https://user-images.githubusercontent.com/7400/56167424-64c94f00-5fd8-11e9-97e1-2dc822ca46b7.jpg)

![Zhapp_014](https://user-images.githubusercontent.com/7400/56168703-39e0fa00-5fdc-11e9-86dc-02afcff30f7a.jpg)

**Comment by Lheana** [comment]
When you face the gobbo, look on your right, behind the bushes.

**Comment by dalen** [comment]
I tried tab targeting in the area. But will try again tonight, thanks for looking into it.
