### ISSUE TITLE
Problem with Renown skill points

### ISSUE THREAD

**Issue by Raskrage** [WarEmu/WarBugs#13891]
Hello! I am 16 renown lvl, but I have only 14 renown skill points. Is it bug?
Sorry, for bad English.
Thank you! 

Screen:
![Bozter_001](https://user-images.githubusercontent.com/49660762/56168511-10c46780-5fe4-11e9-90ef-885ed7fd0d0a.jpg)

**Comment by dalen** [comment]
You can't assign more renown points than your current level (before level 40)

**Comment by Raskrage** [comment]
> You can't assign more renown points than your current level (before level 40)

Thank!
