### ISSUE TITLE
Witch Elf's Sever Limb, Ineffective

### ISSUE THREAD

**Issue by synacyror** [WarEmu/WarBugs#13899]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Sever Limb:
Expected - A precise Crippling attack that deals 638 damage and disarms your target for 4 seconds, making them unable to use melee or ranged weapons.
Actual behavior - Does not disarm them

**Steps to reproduce the problem:**
Initiating the skill does not properly disarm the opponent.

**Screenshots/Videos or archive.org evidences:**
![sever_limb_ineffective](https://user-images.githubusercontent.com/49698591/56246977-3a1edb00-6058-11e9-80cf-01fee65ef7ef.jpg)

I play Witch Elf often and I had suspicions that Sever Limb was ineffective at times but was never sure... I was 1 on 1 against a Swordmaster (2h) and initiated the Sever Limb skill, however he was still able to continuously use melee attacks. In the screenshot, you can see the timeline of his attacks and he launched multiple melee attacks within the 4 seconds that Sever Limb is expected to disarm an opponent. I have died to multiple melee classes due to this bug.

Reported by Fun of Destruction

**Comment by synacyror** [comment]
![sever_limb_ineffective2](https://user-images.githubusercontent.com/49698591/56448902-5032d280-62c8-11e9-89b6-3109df811b0a.jpg)
Adding this to show that this happens on more than one occasion.

**Comment by grunbag** [comment]
That’s because the damage component and the disarm component are on 2 different line . It’s made this way so if your target is immune to disarm , they still get damage part of sever limb .
