### ISSUE TITLE
[Quest] Tradition of War

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13897]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Expected:

Issue 1:

Quest tooltips:

Step 1:
Quest waypoint
* Obtain Glowing Shards 0/3

Step 2:
Quest waypoint
* Place Offerings 0/1

Step 3:
Quest waypoint
* Defeat Aspect of Hysh 0/1
* Defeat Aspect of Chamon 0/1
* Defeat Aspect of Ghyran 0/1
* Defeat Aspect of Azyr 0/1
* Defeat Aspect of Ulgu 0/1
* Defeat Aspect of Shyish 0/1
* Defeat Aspect of Aqshy 0/1
* Defeat Aspect of Ghur 0/1

Step 4:
Quest waypoint
* Scepter of Ulrien 0/1

-------

Issue 2:
I don't know if You can, but can You advance the quest using ground object? If You can, after Placing the offerings, You should fight the aspects.

**Steps to reproduce the problem:**

Take and follow the quest

**Screenshots/Videos or archive.org evidences:**
![Gwarnhil_000](https://user-images.githubusercontent.com/18528095/56240945-eed6ed80-6094-11e9-9159-a968bb6671e1.jpg)
![Gwarnhil_011](https://user-images.githubusercontent.com/18528095/56240954-f4343800-6094-11e9-85b7-8020a61cfe86.jpg)
![Gwarnhil_013](https://user-images.githubusercontent.com/18528095/56240968-f72f2880-6094-11e9-97fb-cd710fdaab03.jpg)
![Gwarnhil_014](https://user-images.githubusercontent.com/18528095/56240973-f9918280-6094-11e9-948f-546bccac0c0c.jpg)

**Comment by sioding** [comment]
Fixed with patch from 15.06.2019
