### ISSUE TITLE
[Quest] Artistry of War

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13904]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

I don't know if it is intended, but there are some Uthorin Corsairs lying on the floor marked as orange mobs. SOme spawn red at the beach. I think all Uthorin Corsairs should be red, and You should kill red mob on the stairs near Artists or at the beach.

**Steps to reproduce the problem:**

Go and check the surroundings of High Elf Chapter 2

**Screenshots/Videos or archive.org evidences:**

![Gwarnhil_010](https://user-images.githubusercontent.com/18528095/56313503-08d70580-6153-11e9-8ee3-aca4a7fb2114.jpg)

**Comment by Lheana** [comment]
Intended.
