### ISSUE TITLE
[Quest] Storm the beach

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13903]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Expected:
1.Quest tooltip:
Quest waypoint
* Uthorin Corsairs killed 0/10
* Uthorin Raiders killed 0/10

2. Quest marker should disappear after killing all mobs

Actual:
1. Wrong tooltip
2. Quest marker disapperas after killing Uthorin Corsairs

**Steps to reproduce the problem:**

Take and follow the quest

**Screenshots/Videos or archive.org evidences:**
![Gwarnhil_002](https://user-images.githubusercontent.com/18528095/56313166-3a030600-6152-11e9-883d-62b5d325179c.jpg)

**Comment by sioding** [comment]
Fixed with patch from 15.06.2019
