### ISSUE TITLE
Magus tactic daemonic pact dont work

### ISSUE THREAD

**Issue by chazzwozza** [WarEmu/WarBugs#13909]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by grunbag** [comment]
No infos please write it properly

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format.

**Comment by sioding** [comment]
No answer for 22 days - close
