### ISSUE TITLE
[Questline] Cruelty to Animals

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13906]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

*Expected*

Step 1:
Tooltip:
Quest Waypoint
* Find SIgns of the Dark Elves 0/1

Step 2:
1. Tooltip:
Quest Waypoint
* Harpies killed 0/3
* Cold Ones killed 0/2

2. Quest marker on map should disappear after killing all mobs, not just harpies.
3. The are two Swale Mares in the area, and the second one has orange quest marker always on. There should be only one giving the quest.

**Steps to reproduce the problem:**

Take and follow quest.

**Screenshots/Videos or archive.org evidences:**

![Gwarnhil_004](https://user-images.githubusercontent.com/18528095/56314873-92d49d80-6156-11e9-955d-f7683dad8ed8.jpg)
![Gwarnhil_019](https://user-images.githubusercontent.com/18528095/56314875-9536f780-6156-11e9-9e6d-a927689433ae.jpg)
![Gwarnhil_020](https://user-images.githubusercontent.com/18528095/56314878-97995180-6156-11e9-9444-e6831d47d2a2.jpg)

**Comment by Lheana** [comment]
Quest markers will be fixed with next patch. For the other unicorn spawns that still have orange icon, it is quite minor, if you walk far and come back, everything will be fine. Will be fixed one day.

**Comment by sioding** [comment]
Fixed with patch from 15.06.2019
