### ISSUE TITLE
Character disappeared

### ISSUE THREAD

**Issue by GreatHarlequin** [WarEmu/WarBugs#13901]
I logged on and noticed my R40 Warrior Priest called JOSILINDE has disappeared. I noticed a few days ago she was on the character ´screen in her underpants and thought it was just a server bug. Now she's totally disappeared.

Please bring her back. She was my lvl200 apo and cultivating alt.

Account login = VILHELMINA

p.s. I logged onto another order alt, who was in the same guild, and the guild news tracker (Averland Greatswords) says she "left" the guild on 11/04/19 @ 18:29:55

**Comment by sioding** [comment]
Thanks for the ticket but this does not belong to the bugtracker cause we do only cath ingame bugs here. Maybe ( and i mean really maybe ) warg can check what happens.
