### ISSUE TITLE
[Questline] Among the Shadows

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13907]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Expected:

Step 1:
Tooltip:
Quest Waypoint
* Talk to Yrsol Whisperwing 0/1

Step 2:
1. Tooltip:
Quest Waypoint
* Find Cold Campfire 0/1
2. Quest should advance from this on it's own, not necessary to retrn to Yrsol

Step 3:
Tooltip:
Quest Waypoint
* Find Prince's Guard 0/1

Step 4:
Tooltip:
Quest Waypoint
* Speak with Cithmiril Ironlance 0/1

Step 5:
1. Tooltip:
Quest Waypoint
* Scout Plain of Bone 0/1
2. Since You can use quest items in areas I suggest creating a Pile of Bone in the area, or give some quest item to use in the area of Pile of Bone

Step 6:
1. Tooltip
Quest waypoint:
* Kill Blacksand Harpy 0/3
* Kill Blacksand Renders 0/3

2. Quest marker should disappear after killing all mobs
3. Blacksand Harpys are also in Blighted isle at 59K, 47K, but not Renders. After killing Blacksand Harpys my questmark on the map disappeared and I didn't know where to find Renders.

Step 7:
Tooltip
Quest waypoint:
* Lay Line Map 0/1

Step 8:
1. Tooltip
Quest waypoint:
* Bloodfueled Devotees 0/5
* Find Fresh Sacrafice 0/1

2. Quest marker should disappear after completing all of the agenda.

Step 9:
Should continue.

*Actual :*
Step 2:
You have to return to Yrsol to conctinues the Quest
Step 5:
This step autadvance. You only have to talk with Cithmiril Ironlance
Step 6:
2. Quest marker disappears after killing Blacksand Harpys
Step 8:
2. Quest marker disappears after killing Bloodfueled Devotees
Step 9:
Quest finishes without reward.

**Steps to reproduce the problem:**

Take and follow the quest

**Screenshots/Videos or archive.org evidences:**

![Gwarnhil_006](https://user-images.githubusercontent.com/18528095/56316113-c533ca00-6159-11e9-8244-8aa4246394a5.jpg)
![Gwarnhil_012](https://user-images.githubusercontent.com/18528095/56316114-c6fd8d80-6159-11e9-921d-c98d380ebcd5.jpg)
![Gwarnhil_019](https://user-images.githubusercontent.com/18528095/56316131-cebd3200-6159-11e9-89a1-4d99c4f7a405.jpg)
![Gwarnhil_024](https://user-images.githubusercontent.com/18528095/56316140-d381e600-6159-11e9-98be-957b5d4125b8.jpg)
![Gwarnhil_028](https://user-images.githubusercontent.com/18528095/56316148-d5e44000-6159-11e9-9211-59cefd469d6a.jpg)
![Gwarnhil_021](https://user-images.githubusercontent.com/18528095/56441056-ffcd6c00-62eb-11e9-85d9-cd8db4737d4f.jpg)
![Gwarnhil_022](https://user-images.githubusercontent.com/18528095/56441062-0360f300-62ec-11e9-90e1-70b42f738938.jpg)
![Gwarnhil_023](https://user-images.githubusercontent.com/18528095/56441064-052ab680-62ec-11e9-9e43-87397f8a91fe.jpg)

**Comment by axisd** [comment]
Actually:

Step 6:
Tooltip
Quest waypoint:
* Kill Blacksand Harpy 0/3
* Kill Blacksand Renders 0/3
Quest marker should disappear after killing Harpy

![Sarhel_004](https://user-images.githubusercontent.com/2901788/58008621-73ce8000-7af5-11e9-9c9d-c95adfbede57.jpg)

**Comment by sioding** [comment]
fixed with patch from 22.6.2019
