### ISSUE TITLE
Joining scenario teleported me to IC and UI changed as if i was logged out

### ISSUE THREAD

**Issue by andrasragany** [WarEmu/WarBugs#13908]
![loggedoutui](https://user-images.githubusercontent.com/39407087/56339609-381b6000-61af-11e9-9fe2-2c26384428f4.png)

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment]
Duplicate of #11224
