### ISSUE TITLE
kotbs kick

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#1390]
when the damage part is absorbed the kick doesnt work either. IMHO original behavior was it kicked anyway.

besides: kotsb kick seems to be blocked/parried etc. much more often then other classes kick. (besides it sucks from the beginning ^^^)

**Comment by ozarmidrashim** [comment]
You're very sure about this? I thought I fixed this a long time ago, because if this were bugged it would mean that snares wouldn't go off against targets with shield effects.

**Comment by Tiggonos** [comment]
i will fraps it tonight to verify. (right now i cant exclude that dmg was absorbed AND kick parried/blocked at the same time).

**Comment by ozarmidrashim** [comment]
The damage will be parried or blocked before it is absorbed, and the kick component should hit if the damage does.

**Comment by Tiggonos** [comment]
after reviewing my videos: it only looked like absorb was the problem though it seems the kick randomly doesnt kick even if the target is not imune. THOUGH: on slow forwarding my videos i often encountered the target got imune half a second before i kicked. in lifeplay it still looks like target is not imune. I have one vid showing target definitly not imune yet not being kicked even in slow motion in video.

I will close this and reopen after more proof.
