### ISSUE TITLE
[Questline] Restoring harmony

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13902]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Expected beahvior:

Step 1:
Quest tooltip:
Quest Waypoint
* Speak with Spirit of Thanalorn 0/1

Step 2:
Quest tooltip:
Quest Waypoint
* Extinguish Pyres 0/3

Step 3:
Quest tooltip:
Quest waypoint
* Speak with Warden Teriel 0/1

**Steps to reproduce the problem:**

Take and follow the quest

**Screenshots/Videos or archive.org evidences:**

![Gwarnhil_001](https://user-images.githubusercontent.com/18528095/56312940-a4677680-6151-11e9-8362-e7ee81e97bd5.jpg)
![Gwarnhil_008](https://user-images.githubusercontent.com/18528095/56312946-a8939400-6151-11e9-942d-d2c8ecdd20fe.jpg)
![Gwarnhil_009](https://user-images.githubusercontent.com/18528095/56312949-aaf5ee00-6151-11e9-863d-be3bb1433a45.jpg)

**Comment by sioding** [comment]
Fixed with patch from 15.06.2019
