### ISSUE TITLE
[Questline] Eyes of Shadow

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13905]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

*Expected:*

Step 1:
Tooltip:
Quest Waypoint
* Speak with Arremar Swiftblade 0/1

Step 2:
Tooltip:
Quest Waypoint
* Speak with Haladhrel Sternbrow 0/1

Step 3:
Tooltip:
Quest Waypoint
* Speak with Larineth Spearsong 0/1

**Steps to reproduce the problem:**

Take and follow the questline

**Screenshots/Videos or archive.org evidences:**

![Gwarnhil_003](https://user-images.githubusercontent.com/18528095/56313884-f4dfd380-6153-11e9-9cbc-b4f78fa161b7.jpg)
![Gwarnhil_018](https://user-images.githubusercontent.com/18528095/56313888-f6a99700-6153-11e9-94bc-ce8739b57347.jpg)
![Gwarnhil_027](https://user-images.githubusercontent.com/18528095/56313894-f8735a80-6153-11e9-8e21-fd86d723797d.jpg)

**Comment by sioding** [comment]
Fixed with patch from 15.06.2019
