### ISSUE TITLE
[Quest] Green River

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13913]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

*Expected:*
1. Tooltip
Quest waypoint
* Saphery Lake Sample 0/1

2. We should be directed to Saphery to take the sample

*Actual:*
2. Quest is autocompleted after clicking on Ostelle Blackwood

**Steps to reproduce the problem:**

Take the quest

**Screenshots/Videos or archive.org evidences:**
![Gwarnhil_004](https://user-images.githubusercontent.com/18528095/56439669-35bc2180-62e7-11e9-9be0-893a105a22fe.jpg)
![Gwarnhil_006](https://user-images.githubusercontent.com/18528095/56439672-3785e500-62e7-11e9-8caf-f3e7352e4e26.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch
Note: This quest is from a wandering NPC, so don't expect a marker if you finished the quest objectives.

**Comment by sioding** [comment]
Fixed with patch from 11.05.2019
