### ISSUE TITLE
[Questline] Tools of War

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13916]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

*Expected:*

Step 1:
Tooltip:
Quest waypoint
* Speak with Victor Gersten 0/1

Step 2:
Tooltip:
Quest waypoint
* Speak with Haladhrel Sternbrow  0/1

Step 2:
1. Tooltip:
Quest waypoint
* Speak With Griffon Siegemaster 0/1

2. Griffon Siegemaster should hav orange questmark above his head.

Step 3:
Griffon cannon should fire.

*Actual:*

Step 3:
Griffon cannon turns into rubble.

**Steps to reproduce the problem:**

Take and follow the quest

**Screenshots/Videos or archive.org evidences:**

![Gwarnhil_008](https://user-images.githubusercontent.com/18528095/56440453-baa83a80-62e9-11e9-97a7-b99cf648885c.jpg)
![Gwarnhil_010](https://user-images.githubusercontent.com/18528095/56440456-bc71fe00-62e9-11e9-91c5-6cc391c935a9.jpg)
![Gwarnhil_011](https://user-images.githubusercontent.com/18528095/56440458-bed45800-62e9-11e9-8f80-1a084c222111.jpg)
![Gwarnhil_012](https://user-images.githubusercontent.com/18528095/56440460-c09e1b80-62e9-11e9-80ce-48da4e716054.jpg)
![Gwarnhil_013](https://user-images.githubusercontent.com/18528095/56440469-c267df00-62e9-11e9-9133-49c61d79047a.jpg)

**Comment by sioding** [comment]
fixed with patch from 22.6.2019
