### ISSUE TITLE
[Quest] Proper Servants DE T1

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#13911]
Quest consists of 2 parts, of which second part was repeatable. 
Right now you can only do it only once.

NPC: Beastmaster Khelrith
Location: Chrace 8k - 1k

![quest](https://user-images.githubusercontent.com/42712833/56426423-f67ada00-62c0-11e9-83d4-9dedef32a5ef.jpg)
![quest2](https://user-images.githubusercontent.com/42712833/56426426-f7ac0700-62c0-11e9-8c06-82584e68e084.jpg)

**Comment by Lheana** [comment]
Intended.
