### ISSUE TITLE
[WP] Soulfire

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#1391]
This ability has several issues:
1) It deals more damage than it should by tooltip, currently it says 450 per 9 seconds on my character, but actually it does 3*230=690. No tactics slotted.
2) Its cast is interrupted by movement - was not like this on live.
P.S. My DoK is not lvl 25 yet, so i don't know if this applies to Fell Sacrifice.

**Comment by Evildoor** [comment]
Cast(2) fixed in 16.09.2015 patch.

**Comment by ozarmidrashim** [comment]
Damage still bad?

**Comment by Evildoor** [comment]
Damage is still too good, to be accurate.
![soulfire](https://cloud.githubusercontent.com/assets/11015074/9927016/3e14b356-5d23-11e5-9772-2a02532b6759.jpg)
3 ticks, 158+33=191 each, 191*3=573 > 438 by tooltip. No tactics slotted.
Hmmm, just a wild guess - Aza, does your implementation has weapon DPS scaling? Because the tooltip makes me think that this skill has no DPS scaling: Sledge of Conguest(36.3 DPS, 65 STR with talisman) gives more tooltip damage than Sentry Sledge(45 DPS, 52 STR with talisman).

**Comment by Evildoor** [comment]
Now the damage is a bit lower than it should, but not by much, something like 3-5% - not reopening this. Just curious - @ozarmidrashim , was my guess about DPS scaling correct? Or something else caused the problem?
