### ISSUE TITLE
[NPC] Ostelle Blackwood

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13914]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

*Expected:*

NPC should be traveling between Chapter 2 and Sternbrow's Lament.

*Actual:*

1. There are two NPC with this name in Blighted Isle, one located at 45K, 32K, second 47K, 41,5K
2. The second one has marker of Starfire Quest even, if it's not completed.
**Steps to reproduce the problem:**

Go to the Chapter 2 High Elves and speak with NPC

**Screenshots/Videos or archive.org evidences:**
![Gwarnhil_006](https://user-images.githubusercontent.com/18528095/56439800-b9760e00-62e7-11e9-9ff1-08ef062ed3c5.jpg)
![Gwarnhil_007](https://user-images.githubusercontent.com/18528095/56439804-bb3fd180-62e7-11e9-855e-d65942467ca2.jpg)
![Gwarnhil_004](https://user-images.githubusercontent.com/18528095/56440015-651f5e00-62e8-11e9-9972-9b3be242c73c.jpg)

**Comment by Kabucoror** [comment]
Npc is moving with next patch

**Comment by sioding** [comment]
Fixed with patch from 11.05.2019
