### ISSUE TITLE
[Quest] Elusive Quarry

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13918]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

*Expected:*
Tooltip:
Quest waypoint
* Speak with Morithwen Nightwhisper 0/1

**Steps to reproduce the problem:**

Take the quest.

**Screenshots/Videos or archive.org evidences:**

![Gwarnhil_018](https://user-images.githubusercontent.com/18528095/56440770-cfd19900-62ea-11e9-9dce-6845e42f0e03.jpg)

**Comment by sioding** [comment]
fixed with patch from 22.6.2019
