### ISSUE TITLE
[Quest] Southern Tracks

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13919]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

*Expected:*
Tooltip:
Quest waypoint
* Speak with Caduin Goldbough 0/1

**Steps to reproduce the problem:**

Take the quest.

**Screenshots/Videos or archive.org evidences:**
![Gwarnhil_019](https://user-images.githubusercontent.com/18528095/56440855-2212ba00-62eb-11e9-9145-b3bb9e11ff9a.jpg)

**Comment by sioding** [comment]
fixed with patch from 22.6.2019
