### ISSUE TITLE
[Quest] Hidden Talons

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13915]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

*Expected:*

1. Tooltip:
Quest waypoint
* Serrated Talon 0/5

2. Serrated Talons should be quest items, not regular items.

**Steps to reproduce the problem:**

Take and follow the quest

**Screenshots/Videos or archive.org evidences:**

![Gwarnhil_005](https://user-images.githubusercontent.com/18528095/56440164-e840b400-62e8-11e9-9670-7ce4d89270c0.jpg)
![Gwarnhil_014](https://user-images.githubusercontent.com/18528095/56440169-eaa30e00-62e8-11e9-9cc8-6ea30ce6190b.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch
Note: This quest is from a wandering NPC, so don't expect a marker if you finished the quest objectives.

**Comment by sioding** [comment]
Fixed with patch from 11.05.2019
