### ISSUE TITLE
[Quest] Facing the Onslaught

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13917]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

*Expected:*
Tooltip:
Quest waypoint
Speak with Kyrinn SIlversea 0/1

**Steps to reproduce the problem:**

Take the quest.

**Screenshots/Videos or archive.org evidences:**

![Gwarnhil_017](https://user-images.githubusercontent.com/18528095/56440723-926d0b80-62ea-11e9-81f0-63da7c7434f6.jpg)

**Comment by sioding** [comment]
fixed with patch from 22.6.2019
