### ISSUE TITLE
[Questline] A New Way

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#13912]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

*Expected:*

Step 1:
1. Tooltip:
Quest Waypoint
* Kill Uthorin Bloodshade 0/1
* Kill Uthorin Stalkers 0/3
2. Quest mark should disappear after killing all mobs

Step 2:
Tooltip:
Quest Waypoint
* Speak with Yrsol Whisperwing 0/1

Step 3:
1.This is the tricky one. Since You cannot script and spawn waves of mobs I suggest these options to advance with the quest:
a. Kill some mobs in the area
b. Use Eagle Claw Bolt Throwers to shot down some Harpys
c. Spawn mobs by clicking the Eagle Claw Bolt Thrower

2. Tooltip should be corrected regarding of options above

*Actual:*
Step 1:
Questmark disappears after killing Uthorin Bloodshade

Step 3:
1. You have to click on Eagle Claw Bolt Throwers to advance
2. Tooltip is useless.

**Steps to reproduce the problem:**

Take and follow the quest

**Screenshots/Videos or archive.org evidences:**
![Gwarnhil_000](https://user-images.githubusercontent.com/18528095/56439419-3dc79180-62e6-11e9-8e82-9a79891e8d55.jpg)
![Gwarnhil_001](https://user-images.githubusercontent.com/18528095/56439422-3f915500-62e6-11e9-8616-1dbd1d3b9fb4.jpg)
![Gwarnhil_002](https://user-images.githubusercontent.com/18528095/56439424-415b1880-62e6-11e9-922c-3273b2c2cffe.jpg)
![Gwarnhil_003](https://user-images.githubusercontent.com/18528095/56439425-428c4580-62e6-11e9-9775-bbad164d40dc.jpg)

**Comment by sioding** [comment]
Fixed with patch from 15.06.2019
