### ISSUE TITLE
[RVR Quest]Truth of WAR! and Da Boyz of Waaagh!

### ISSUE THREAD

**Issue by Alfred19** [WarEmu/WarBugs#13929]
Truth of WAR! looks like its supposed to count kill in Elf T4, counts Kills in Dwarf T4. 
Questgiver is In Dragonwake.

Da Boyz of Waaagh! does the same but the other way around, it counts kills in Elf T4.
Questgiver is in Thunder Mountain.

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by Alfred19** [comment]
Thanks

**Comment by Alfred19** [comment]
You guys do great job btw <3

**Comment by sioding** [comment]
Fixed with patch from 27.04.2019
