### ISSUE TITLE
SC you are dead

### ISSUE THREAD

**Issue by noazmog** [WarEmu/WarBugs#13926]
When I was killed by players during sc, I could not respawn at all.

![Elrae_004](https://user-images.githubusercontent.com/49399287/56463238-86f41000-63d0-11e9-8e87-ead036486da4.jpg)

**Comment by sioding** [comment]
Thanks for the report but this happens sometimes ( an did also in AoR imes ) Hit STRG+U to reload ui and the respawn window will appear.
