### ISSUE TITLE
Easter Eggs not visible

### ISSUE THREAD

**Issue by Malykhai** [WarEmu/WarBugs#13924]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
I get smell messages several times, search the area, and find nothing. I enter another smell area, search the area, find nothing. Other players are reporting the same issue as well.

**Steps to reproduce the problem:**
I exit and enter different "smell" areas

**Screenshots/Videos or archive.org evidences:**

**Comment by Lheana** [comment]
Give coord and zone

**Comment by Malykhai** [comment]
I was in Caledor from DE Ch16 to Malryo's Rest PQ

**Comment by Lheana** [comment]
Walked there, did not have any message, so I guess someone found it.
