### ISSUE TITLE
Desecration Quest missing map marker

### ISSUE THREAD

**Issue by Sollessa** [WarEmu/WarBugs#13922]
For the quest "Desecration" in Chaos Chapter 2 from the Sorcerer's Axiom the quest is missing a map marker for the sword objective.

**Comment by Lheana** [comment]
Everything is fine with this quest
![Anaehll_160](https://user-images.githubusercontent.com/11537611/56456760-21246b80-6371-11e9-9c73-cb995032b8a8.jpg)
