### ISSUE TITLE
[Server Lag] Possible reason

### ISSUE THREAD

**Issue by Algenubi** [WarEmu/WarBugs#13920]
I found a possible reason for server lags/crash. There is an item called 'Ungor talisman', dropped from beastmen. It can be equipped into pocket slot for unlock, and also this item is stackable. If you have few ungor talismans, you are able to equip whole stack in your pocket. While in pocket, it shows you the only talisman equipped, while actually you have few talismans in one pocket.

Each time when I equipped stack of talismans, server has huge lags as if it's going to crash. All mobs disappeared around me, and people in global chat said the same. Maybe this is coincidence, but maybe this is one of lags origin.

I presume the lags appear when any player equips stack of any items into pocket slot, or maybe any other slot, while any slot may contains only single item.

**Comment by Natherul** [comment]
This issue is fixed since a few weeks. You should not be able to stack equippable items and the code now prevents this and ask for a report on those items as they are wrongly set in the DB
