### ISSUE TITLE
WP Bug Mastery Reset

### ISSUE THREAD

**Issue by wReknell** [WarEmu/WarBugs#13923]
Ever since the new patch a couple of hours ago i Always have one Point in path of salvation Right after resetting.

Wanted to quest some using 2h Spec and was wondering why i Always get that Point ;o

Warrior Priest - lvl 28

![WarBug](https://user-images.githubusercontent.com/49813867/56458327-68b4f280-6385-11e9-8188-305e387a3c1b.jpg)

**Comment by Kabucoror** [comment]
You probably wear a set with +1 in path of salvation

**Comment by wReknell** [comment]
Indeed i do, thanks :) 

So it's just a wierd interaction
