### ISSUE TITLE
Fortress: Fell Landing - Savezone not save

### ISSUE THREAD

**Issue by Latemoon83** [WarEmu/WarBugs#13928]
Dear Supporter, 

the spwanpoint after the fortress is not save. Dessis farming us.

![Latemoon_030](https://user-images.githubusercontent.com/33985355/56470743-f35f2580-6449-11e9-9afe-38a6490e3f33.jpg)

Sincerely yours

Late

Happy Easter!

**Comment by sioding** [comment]
Hey - thanks for the report - but fort respawn points aren't supposed to be "safe". If you have to release - your realm needs to make sure the respawn point is safe.
