### ISSUE TITLE
[Ability]  Down Ya Go! not useable

### ISSUE THREAD

**Issue by Krumlok** [WarEmu/WarBugs#1392]
"Your current level is too low to use this ability"

That's what it says; I can't use the KD.
Screenshot taken
![bugreport](https://cloud.githubusercontent.com/assets/14275335/9850420/c58b4daa-5af2-11e5-82a5-dc6560dae54d.jpg)

**Comment by Evildoor** [comment]
Have you tried actually using it on mobs? There were similar issues, and abilities were firing off despite warnings. And i'm pretty sure my friend told me today about using Down Ya Go on his BO... Sorry, can't ask him right now.

**Comment by Krumlok** [comment]
Just tried it. It does work. Sorry for making this useless ticket :(

**Comment by Evildoor** [comment]
Sadly, it seems that this kind of bugs will remain with us, because it is client side if i understand correctly. Way to go, Mythic, putting useless checks into your game...
