### ISSUE TITLE
Old Event Item

### ISSUE THREAD

**Issue by Sistermary** [WarEmu/WarBugs#13927]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Keg Event item.  I was looking on the NPC and it let me claim the items again today and equip.
To be fair I un-equiped and is in my bag. on my Character Sistermary.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment]
Thanks for the report but its OK - you can not claim it again. Now the server noticed you got it. Was a bug during Keg End Event.
