### ISSUE TITLE
Stone of Ecelsion DE Chpt 7 PQ phase 2

### ISSUE THREAD

**Issue by knthrak** [WarEmu/WarBugs#13938]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Phase 2.  Should be able to attack shields over archmages and destroy them.  Shield is not attackable and has no hitpoints, right clicking on item also does not activate it.  Appears to be repeat of problem fixed in 2017 #4891
 

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

![bug](https://user-images.githubusercontent.com/48619966/56632341-b2ab1a80-669c-11e9-9251-02d290667371.jpg)

**Comment by sioding** [comment]
Fixed with patch from 27.04.2019
