### ISSUE TITLE
Sentinel dungeon soft lockout

### ISSUE THREAD

**Issue by barfyman92** [WarEmu/WarBugs#13939]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Hey there i could rly use some help. Got stuck in a bad id inherited from former group leader. My group was in a clean dungeon and I am with them but like a ghost. cant hit or see any of the mobs THEY see, all I could see were corpses are from the previous ID. 

The mobs they saw did not even react to my presence.

**Steps to reproduce the problem:**

What happened was previous lead had lockout in the warlocks tunnel, they cleared to boss (couldnt find him obviously) then they leave for other tunnel with gray seer, while they clear they kick lead and inv me. We clear it out, go back to the warlocks tunnel and that's where the problem happened. We all had the bad dungeon ID from former lead. 

We attempted to fix this by me going on my alt and enter the tunnel solo. Once I got a fresh ID I invite my teammates. They all enter, then I relog on my original toon, and get invited and enter. But the bad ID sticked to me (only!). Seems only those invited by the dungeon ip creator got to unbug dungeon.

**Screenshots/Videos or archive.org evidences:**

**Comment by grunbag** [comment]
fixed already
