### ISSUE TITLE
BlackOrk - You got nuffin-healticks not affected by willpower

### ISSUE THREAD

**Issue by Pandurini** [WarEmu/WarBugs#13937]
unlike stated in the patchnotes, willpower does not affect the healing done by you got nuffin-tactic.

i tested it on my black orc, using full vanq with toughness-talis and full conq with 5x22wp-talis for comparison and added +80wp-potion as well.

with the tactic slotted and 14points up in boss-tree, the healticks were coming in for 99, no matter what i did to my willpower.
then i thought that it might be capped at 99 (for whatever reason) and respecced only 3points into boss-path + you got nuffin-tactic, with the result of healticks coming in for 74, again with no change of value when raising my willpower.

trying to find a way to get a benefit on the healing out of willpower, i discovered another somewhat buggy thing about the tactic:
going back to my old specc, i then saw that the healticks still were coming in for 74 and since i knew it could be higher, i reslotted the tactic. that made the hot ticking for 101 (15points in boss this time) again, but could still not be modified by willpower in any way, no matter what combo i tried with gearing & slotting the tactic.

hopefully this helps.
o/

**Comment by grunbag** [comment]
Thanks for the report I’ll test again

**Comment by deLunel** [comment]
Adding to the above, I tested adding willpower on my BO via renown, adding all Resolve I - V renown spec (ie +120 wp) and there is NO change in ticks at all from You Got Nuffin'.    cheers

**Comment by grunbag** [comment]
Fixed for next patch

**Comment by sioding** [comment]
Fixed with patch from 27.04.2019
