### ISSUE TITLE
Overflow Backpack - liniments

### ISSUE THREAD

**Issue by blakokami** [WarEmu/WarBugs#13932]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Can't get rid of overflow backpack items when you open a liniment crate

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by Lheana** [comment]
Put the items of the overflow backpack in your bank.
