### ISSUE TITLE
[Quest] Dat Glomp's a Threat

### ISSUE THREAD

**Issue by blakokami** [WarEmu/WarBugs#13931]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Should be giving contribution if you kill the Glomp boss (left wing gunbad) but it hasn't given me credit twice in a row. All 3 other gunbad quests have given me contribution. It is unique to left wing.

**Steps to reproduce the problem:**
Do left wing gunbad

**Screenshots/Videos or archive.org evidences:**
https://cdn.discordapp.com/attachments/315329749323087885/569698994863996929/Drakirah_003.jpg

**Comment by Lheana** [comment]
When being solo, this quest works fine. So related to #12470
