### ISSUE TITLE
Empire Chapter 6 Influence Reward BW - Staff of the Trollslayer not equipable

### ISSUE THREAD

**Issue by blockhead6767** [WarEmu/WarBugs#13941]
Empire Chapter 6 Influence Reward for Brightwizard ( Staff of the Trollslayer) cant be equiped.
The Problem is that it is listed as "Both Hands or Off Hands".

I know its only a tiny minor problem but i wanted to check it for the skin and found the issue.

**Comment by sioding** [comment]
Fixed with patch from 27.04.2019
