### ISSUE TITLE
[Tooltip] Engie-Turrets missing buff explenation

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#13949]
On RoR the turrets do buff more than just the damage you deal. Befor you could check those boni with _.ab change_, but this command has been removed a while ago. Right now you only can check them on the CarrerBuilder, it's a bit confusing, especially for new players.
(Probably the same accures to the Magus' pets aswell)

![Turret_ingame](https://user-images.githubusercontent.com/40274248/56805445-5cb7ad80-6829-11e9-8e71-b32df389dde1.jpg)
![Turret_CB](https://user-images.githubusercontent.com/40274248/56805451-62ad8e80-6829-11e9-9660-3278917b1c36.jpg)

**Comment by grunbag** [comment]
both are available

**Comment by Scophis** [comment]
That's true, but it's a frequently asked question of new engie players, why .e.g their skills' range "suddenly" is shrinking. with the flame turret out.

**Comment by Natherul** [comment]
this has been fixed some time ago. Thanks for the report.
