### ISSUE TITLE
DoK  - Gale-Runner's Gorget Helm appearance bug

### ISSUE THREAD

**Issue by GreatHarlequin** [WarEmu/WarBugs#13945]
My R11 DoK wears the Gale-Runner's Gorget, which in-game looks like a throat piece. But logging out, it looks like some sort of Sorc's helm. I hope this is not another bug that causes my alt to disappear off the server.

[On character](https://imgur.com/gallery/PDLWGH9)

[On character select screen](https://imgur.com/gallery/svDMXOV)

**Comment by wargrimnir** [comment]
I miss the "Weird Stuff" label we used to have. No idea why this would show up as a sorc helm.

**Comment by Kaelang** [comment]
This item retains it's appearance on logout.

![image](https://user-images.githubusercontent.com/60117106/82149043-e596f200-984d-11ea-9bd1-51cdcc829599.png)


Please re-open if issue persists.
