### ISSUE TITLE
Fields of woe: Bug with the weapon carts

### ISSUE THREAD

**Issue by davems5557** [WarEmu/WarBugs#13940]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
The event had already been started, with 9/10 carts destroyed. As a member of the Chaos faction, I wanted to steal some glory and loot. I wandered a dead field, with dead folk everywhere, and every cart was destroyed. there was no respawning of any NPCs or destruction targets.

**Steps to reproduce the problem:**
Hard to say, I encountered the bug in its natural habitat. I would assume it would involve killing everything.

**Screenshots/Videos or archive.org evidences:**

![Nightflak_001](https://user-images.githubusercontent.com/49965215/56702017-7e574e80-66dc-11e9-8ec6-75fcfcd8e423.jpg)
![Nightflak_002](https://user-images.githubusercontent.com/49965215/56702018-7e574e80-66dc-11e9-98d5-b2b1bb333e86.jpg)
![Nightflak_003](https://user-images.githubusercontent.com/49965215/56702019-7e574e80-66dc-11e9-8ffe-5dfd9a0c7930.jpg)
![Nightflak_000](https://user-images.githubusercontent.com/49965215/56702020-7e574e80-66dc-11e9-92f6-e64fc55ec100.jpg)

**Comment by davems5557** [comment]
also, why is this here mixed with some level 7 dudes?
![Nightflak_004](https://user-images.githubusercontent.com/49965215/56702829-a648b100-66e0-11e9-8e45-2d76ebda867f.jpg)
When I first found that, I was walking past to a low-level quest.

**Comment by Lheana** [comment]
Search harder. There are 10 Weapon Wagons, PQ area is large.

**Comment by davems5557** [comment]
Sorry for being a bother then, thought that I had seen a problem.
