### ISSUE TITLE
Quest Mobs being attacked by aggressive mobs close to them 

### ISSUE THREAD

**Issue by Vatrasha** [WarEmu/WarBugs#1394]
for example: The Dark One - "Braewold" keeps getting attacked and killed by mobs surrounding him (quick respawn). If they add in and do too much dmg he can not be looted for the quest item.

Same goes for "Isolde The Defender" on a later quest around the Wild Huntsmen - also in T1 Empire.

**Comment by Vatrasha** [comment]
Simon Hirtzel (The Corruption Within)

**Comment by Evildoor** [comment]
Changelog 17.02.2016
[Other Changes]
- Adjusted mobs around Isolde the Defender to stop them murdering her before destro could.

**Comment by Natherul** [comment]
checked all these mobs and they are fine atm and not attacked by anyone
