### ISSUE TITLE
[GameObject] Lever on Ironclad (BO) not functional

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#13948]
Probably this lever is part of a quest, but it was always fun to sound the horn after capturing the Ironclad-BO. Atm it's not activatable .

![wrong_lever_kronk](https://user-images.githubusercontent.com/40274248/56804964-d189e800-6827-11e9-91bc-4b90a054a384.jpg)

**Comment by Lheana** [comment]
Well it's not really a bug ... But with next patch you will be able to have fun clicking on this object to sound the horn.

**Comment by sioding** [comment]
fixed with patch from 25.05.2019
