### ISSUE TITLE
Order Caledor PQ ch 22 hard

### ISSUE THREAD

**Issue by funnytroll** [WarEmu/WarBugs#13943]
Well, screenshot tell everything )
https://imgur.com/345VUCp

**Comment by sioding** [comment]
Well - not for me. Please descibe to problem

**Comment by funnytroll** [comment]
Thinks its random,sometimes its bug, sometimes no
In that day we did it 2 times,one try loot is bugged

**Comment by sioding** [comment]
And again: Whats the problem?

**Comment by sioding** [comment]
No answer since 24 days. Close
