### ISSUE TITLE
[AM] Empowered Lores - tactic

### ISSUE THREAD

**Issue by Chudas** [WarEmu/WarBugs#13946]
career tactic Empowered Lores which says: Whenever you critically hit with an ability that builds either force or tranquility, you will gain one additional point. Tactic can not trigger more than once every 3 sec; i do not think it is working properly. Healing spells, which build tranquility points or spend force points, when they critically heal it builds two points, but do not spend two point. And spells, which build force points or spend tranquility points same issue. It works only when building up either force or tranquility.

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format.

**Comment by Chudas** [comment]
I am sorry, but i can not provide any screenshots/video for such issue. I can post here some screenshots, but they will not tell you much, because high magic points do not show in combat log.  
I tried it in rvr lakes, pve and pve while flagged for rvr as well. The thing is, that it only works when i am using spells to build up any high magic. Does not work when i critically hit/heal someone when i need to spend these points.

**Comment by sioding** [comment]
Tbh: I don't get it. Maybe a video would help to see what you mean.

**Comment by sioding** [comment]
No answer for 14 days. Close
