### ISSUE TITLE
Please, improve the boxes.

### ISSUE THREAD

**Issue by Blad1** [WarEmu/WarBugs#13944]
Boxes that are obtained from the flag appear in textures (in the wall) and can not be collected. Location is Bugman's Brewery T3 DWARF Black Fire Pass.

https://photos.app.goo.gl/ysCon664WaD1o4W77

**Comment by MaxHayman** [comment]
I have a solution I think.

**Comment by MaxHayman** [comment]
This should have been fixed. I fnot please reopen.
