### ISSUE TITLE
The Postern Doors of Forts

### ISSUE THREAD

**Issue by synacyror** [WarEmu/WarBugs#13953]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Expected:
"This postern door is barred. To gain access, you must bypass it with an ability, or destroy the associated main door and lower the fortresses' rank to three."
Actual behavior: Even with associated main door (fortresses' have no ranks), you cannot enter the Fort through a postern door unless you use the ability to do so.

**Steps to reproduce the problem:**
Attempt to enter postern door whilst the associated main door is down.

**Screenshots/Videos or archive.org evidences:**
![Fun_037](https://user-images.githubusercontent.com/49698591/56844577-5f38f800-6867-11e9-9894-5dc4547be4fd.jpg)
![Fun_038](https://user-images.githubusercontent.com/49698591/56844578-5f38f800-6867-11e9-89f3-85dcf5a424af.jpg)

Reported by Fun of Destruction.

**Comment by sioding** [comment]
my best guess: this is intended. Since i don't find any why in the forum i leave this answer open for Nath to decide it.

**Comment by Natherul** [comment]
very much intended. Only sneaky bypass skills should be possible on forts, no other sneaking in.
