### ISSUE TITLE
Exporting profile

### ISSUE THREAD

**Issue by Kushido** [WarEmu/WarBugs#1395]
Created BW, exported profile from my KotBS all ok.
Created IB, exported profile from BW and on my skill panels i had BW skills (like Fireball and etc). They're not working ofc, but as i remember like it worked in official version - your skill bars just going to be clear of any skills except the basic ones (like "Flee" skill).

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
