### ISSUE TITLE
I cannot move stacked items in crafting bag. Says they cannot be equipped.

### ISSUE THREAD

**Issue by Grendel1892** [WarEmu/WarBugs#13958]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment]
fix is pending

**Comment by Phineasfreak1** [comment]
Happening to me as well.

**Comment by trovmar** [comment]
me too.  I cannot equip stacked talismans or convert apothecary plants to seeds when the items stacked.
same error

**Comment by sioding** [comment]
hotfix done

**Comment by Tazyr** [comment]
Hey ! 
I had an issue when trying to equip talismans today. It wasn't possible as the talismans were stacked. The game told me to report this bug here.
Thanks !

**Comment by sioding** [comment]
You can not equip talismans - they need to go into items - not on persons

**Comment by Tazyr** [comment]
Sorry for the confusion that’s what I meant. I cannot slot them on my weapons or Armor because they are stacked.
