### ISSUE TITLE
[WL] Pounce while enemy is in stealth

### ISSUE THREAD

**Issue by Psychoxell** [WarEmu/WarBugs#13959]
It is possible to use pounce again and again while an enemy goes during fight into stealth.

other abilities are not able to use. and the enemy is invisible for me

**Comment by grunbag** [comment]
stealth has a cast time you are still visible during this time, i guess you can pounce at them

**Comment by Psychoxell** [comment]
No, the player was in fight and go into steath. I count not see him after that. only the focus is not gone and it was possible to use the pounce on this hidden player.

**Comment by grunbag** [comment]
How did you targeted a stealthed target

**Comment by Psychoxell** [comment]
1. Target a Witch elf who is not in stealth.
2. After the WE go into stealth all abilities are not useable on this person isntead of Pounce.

**Comment by Psychoxell** [comment]
2.a The WE have to go in stealth, when this we is in your target.
