### ISSUE TITLE
WP Invader set

### ISSUE THREAD

**Issue by Silverhand10** [WarEmu/WarBugs#13957]
First the jewelry 2% reduce chance to be parried as you can see below i am pretty sure that this should be reduction of being critically hit or reduced amour penetration.

[img]https://i.imgur.com/v234LL5.jpg[/img]

The 6 piece bonus absolve I - On direct heal 5% chance to remove a Hex, Curse or Ailment of your heal target is not working.

I tried to clean the envenomed fangs ailment of Blood Stalker mob in High pass WC and acidic spit hex of slavering in the PQ The Foitid Plains ( CH10 ) and it is not working, i tried for a good 10 minutes in each mob all the direct healing skills that i have and also the hots.

In my opinion this bonus is a little weak maybe if it was 10~15% chance to proc would be better, 5% is like 1 time every 3 full cast group heal with full group in a totally random way, i would exchange this for the 5 piece bonus Reactionary of Conqueror set or Imperative Spirit of Vanquiser set.

**Comment by Kabucoror** [comment]
corrected the stats, the rest is for @grunbag

**Comment by grunbag** [comment]
fixed for next patch

**Comment by sioding** [comment]
fixed with patch from 01.06.2019

**Comment by Mac1ek** [comment]
This bug is fixed ? I still see 6th bonus doesn't cleans.
