### ISSUE TITLE
Tier 3 High Elf Epic Quest

### ISSUE THREAD

**Issue by Franhaetta** [WarEmu/WarBugs#13956]
At the 13th step of the chain of quests, we have to use the object "Tear of Isha", to break the collar of two NPCs, i use it with  Gorgluk Foulbreath at 56k/8.2k, and it works, but whith the second objective, Ulvarr Scorchspell at 55.5k/33.2k it doesn't works.

![Ullhird_003](https://user-images.githubusercontent.com/48967102/56848504-52111d00-68ea-11e9-9ddd-362745f46618.jpg)
![Ullhird_004](https://user-images.githubusercontent.com/48967102/56848506-563d3a80-68ea-11e9-8b76-56cabde6d12b.jpg)

**Comment by Lheana** [comment]
Use it on him without pulling him

**Comment by Franhaetta** [comment]
Just do it, doesnt work.
![Ullhird_006](https://user-images.githubusercontent.com/48967102/56851992-9ebe1d80-6915-11e9-8a7c-77ec1e8b5216.jpg)
![Ullhird_007](https://user-images.githubusercontent.com/48967102/56851994-a1207780-6915-11e9-8c5d-4a7ab47a8efb.jpg)

**Comment by Lheana** [comment]
Stand closer

**Comment by Franhaetta** [comment]
if i stad close i will pull him.

**Comment by Lheana** [comment]
There is a range around the NPC for using the item, so if you pull him, he may be out of this range as it is based on his normal location.

**Comment by Franhaetta** [comment]
ok, lets try near his location.

**Comment by Franhaetta** [comment]
ok, it works near the original location, thanks for the atention.

**Comment by sioding** [comment]
\o/ and the bugtracker is once again a support tool.
