### ISSUE TITLE
DoTs don't stop after the Duel ended 

### ISSUE THREAD

**Issue by DanaBloodkiss** [WarEmu/WarBugs#13967]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

DoTs should stop after the duel end. 

DoTs dpn't stop after the duel ended and will kill you when you have low life. 

**Steps to reproduce the problem:**

Do a duel, dot your enemy and win. Then you see that the enemy still get damage over time.

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment]
hotfix done
