### ISSUE TITLE
Squigherder Big Claw seems odd

### ISSUE THREAD

**Issue by Zzzzorch** [WarEmu/WarBugs#13964]
Greetings, played my Squigherder today, and it seems the 'Big Claw' skill seems to bugs a bit? The picture looks totally different and also the tooltip tells me something about Myrmidias Blessing.., also the numbers seem kind of odd to me.

Kind regards, Zorch

Here a Screenshot!
![Shavedshark_002](https://user-images.githubusercontent.com/50074414/56863630-290b8d80-69b9-11e9-8bcf-0919eb275673.jpg)

**Comment by grunbag** [comment]
Fixed for next patch

**Comment by Zzzzorch** [comment]
Awesome, thanks a lot! That was fast.
