### ISSUE TITLE
Duel Observer NPC gets hit by area damage and attacks you

### ISSUE THREAD

**Issue by DanaBloodkiss** [WarEmu/WarBugs#13966]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Duel Observer shouldn't be hit by damage. 

**Steps to reproduce the problem:**

Do area damage around the Duel Observer. He will attack you. 

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment]
hotfix done
