### ISSUE TITLE
[ITEM] Hatchet of the Ravener does not have 2h Great Axe values

### ISSUE THREAD

**Issue by Vancerus** [WarEmu/WarBugs#13969]
**Expected behavior and actual behavior:**
lvl 38 purple Hatchet of the Ravener has low dps/stats while displayed as Off Hand as well.
Comparison to a blue 2h axe in screenshot.

**Screenshots/Videos or archive.org evidences:**
![bug](https://user-images.githubusercontent.com/14907399/56864510-8f95a900-69c3-11e9-8f5e-5e0c1e856cbc.png)

**Comment by synacyror** [comment]
The item itself isn't supposed to be a Great Axe but instead a 1h. The name indicates a 1h and the stats match that of what a 1h would have.

**Comment by Vancerus** [comment]
I personally think the appearance, race and everything is closer to a WL weapon than a Slayer one.
But either way, this right now is not right.

**Comment by wargrimnir** [comment]
It should have 2h stats for WL.

**Comment by dalen** [comment]
This seems to be a general issue with WL Hatchets, see also https://github.com/WarEmu/WarBugs/issues/13502

I guess Hatchets were at some point intended to be 1h weapons for WL as WL has dual wield ability.

**Comment by Kabucoror** [comment]
correct stats with next patch

**Comment by sioding** [comment]
fixed with patch from 05.05.2019
