### ISSUE TITLE
Colours from Eastern Event switching Problem

### ISSUE THREAD

**Issue by lordhomungus** [WarEmu/WarBugs#13968]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

I cant not switch them in my bag from slot to slot geting an error message that i cannot equip them cause they stacked but i just want to switch the place in the bag

**Steps to reproduce the problem:**

tried to switch the places in my bag to manage them a bit but the colours cant be switched

**Screenshots/Videos or archive.org evidences:**
![Bug](https://user-images.githubusercontent.com/49230138/56864145-3297f400-69bf-11e9-8752-f4395f36954c.png)

**Comment by sioding** [comment]
Duplicate of #13958
