### ISSUE TITLE
options to convert medallions and buy potions for medals are gone

### ISSUE THREAD

**Issue by Garrthax** [WarEmu/WarBugs#13960]
before patch, we can convert higher medallions to lower and we can buy health and action points potions for them both at quartermasters ... its all gone now (tested only on order side and at every quartermaster)

![ascasc](https://user-images.githubusercontent.com/49390790/56854746-f2436200-693b-11e9-9826-a917d78df305.jpg)

**Comment by Kabucoror** [comment]
You forgot to check Misc on, afterwards you see them.
