### ISSUE TITLE
Cannot equip an item that is sacked

### ISSUE THREAD

**Issue by Zaphologist** [WarEmu/WarBugs#13965]
Hello,

i just tried to sort my inventory and when i tried to move anything in it, that has at least 2 items stacked i cant move it and a message appears:

"Cannot equip an item thats stacked.
Please report this to the Bugtracker."

So i did. 
Hope i could help you guys out with this situation.

Best wishes
Zaph

**Comment by Senthoi** [comment]
Having this too. It's doing this when I try to move any multiple items, and also won't let me transfer them into the bank vault.

(Trying to transfer into vault)
![Ulralys_195](https://user-images.githubusercontent.com/22262165/56864573-e5fee980-69bb-11e9-956b-f68fed4a6858.jpg)

(Trying to just move items in backpack)
![Ulralys_196](https://user-images.githubusercontent.com/22262165/56864575-e9927080-69bb-11e9-8fc4-f583bdc20ce2.jpg)

**Comment by sioding** [comment]
hotfix already done
