### ISSUE TITLE
[Fortress] Reikwald 

### ISSUE THREAD

**Issue by funnytroll** [WarEmu/WarBugs#13974]
Before this error fort go properly and SoR show active fort. But when this error shown SoR dont display active fort and it bugged(no lock when timer end ) Maybe its not a real issue )
https://imgur.com/FFukd7x

**Comment by sioding** [comment]
i leave this one open for that fortress don't end problem.

**Comment by Natherul** [comment]
could I have more information on this one? 

I dont think this is an issue anymore but either way Im not sure I understand the issue

**Comment by funnytroll** [comment]
You can close it)
