### ISSUE TITLE
Imortal Squig 

### ISSUE THREAD

**Issue by Phalquan** [WarEmu/WarBugs#13979]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Well first time filling this thing out, so not sure how to it right, and its a small but funny bug 💃 

I am a proud squig herder, cuz my squig from yesteday are still running in Scorceres apox, its running from the rally master to the top the hill and bag, good little squiggy!

However i feel like its worth reporting, even though i might loose my little squiggy !

His name is Squiggy the 43th as many has come befoure him, however none have become as impactfull as him, so please put him to sleep, but do it grently, he was a good squig.

I have a new squig now and i can take the loss.

Love, a proud squig owner.

**Steps to reproduce the problem:**

Remove the bugged squig that keeps being there even if i go away.

**Screenshots/Videos or archive.org evidences:**

Sorry no fraps, but i am sure you can find him, hes hard to miss

**Comment by sioding** [comment]
There are more than one of this immortal squigs. Maybe the DB Devs can find them.

**Comment by Kabucoror** [comment]
Thanks for your report.

Unfortunately, I could not find your runaway squiggy.
Even otherwise, there was no ownerless creature.

He may have disappeared in one of those mysterious events where everything goes dark.

Sincerly, someone who love his squigs well-done
