### ISSUE TITLE
No active zone at the moment only T1

### ISSUE THREAD

**Issue by EssentialOrder** [WarEmu/WarBugs#13977]
After Stonewatch fortress opened and never closed all zones except t1 are not active

**Comment by sioding** [comment]
This is a known problem - if not enough ppl are online to open up a second zone it will be like this. This is a bad one we know - especially when the fort zone bugs out. So its generally not a bug - to make sure another zone is always open when a fort runs - nvertheless how many ppl are online would be a suggestion. Please use our forum for it - the bugtracker is for bugs only.
