### ISSUE TITLE
Box of tier 1 Medallions doesn't open

### ISSUE THREAD

**Issue by Kjetl** [WarEmu/WarBugs#1397]
I purchased a boc of tier 1 medallions using a tier 2 med.  It is supposed to open using control+right click amd give you 5 tier one medallions.  Nothing happens with control+right click (either control -- don't remember if warhammer cares about R vs L control).

**Comment by russellbarron** [comment]
This is a known issue and will be addressed in the next patch.

**Comment by Reggaewaldo** [comment]
Tested OK on dev server, will be added in next patch as.

Closing.
