### ISSUE TITLE
[Engi] New Phosphourus Shell as of 27/04/2019

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#13972]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Patchnotes say the Ability should mirror Magus Ability. And the Tooltip ingame says it should fire a mortar shell EACH second.
Tests show it does fire a Mortar Shell at the beginning and then every 2 Seconds. Testing on NPCs show maximum 4 Shells in 6 second cast.
Also it has no Snare apply if it is a real mirror of the Magus ability. The Snare is not noted in the Tooltip though.

Also in conjunction with Flame Turret the Flame Turret increases Target Cap and decrease the range of the Mortar Shells. BUT it doesn't increase the radius of the 20feet splash like the Flame Turret does on Acid or Fragmentation Grenade.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by grunbag** [comment]
Thanks for the report. The snare component is not in the tooltip but works.

How does Tzeentch Firestorm radius works with pet bonus ?

**Comment by grunbag** [comment]
Tzeentch Firestorm : 

Creates a great column of wind and flame that deals 243 spirit damage every 2 seconds to all targets within 20 feet of the area, and snares them by 20%. This spell requires a high amount of concentration and you will be set back by .5 seconds whenever hit.

**Comment by grunbag** [comment]
Fixed tooltip for next patch
