### ISSUE TITLE
Toughness not works for all dots

### ISSUE THREAD

**Issue by komar9220** [WarEmu/WarBugs#13978]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Toughness works incorrectly for periodic damage.
190 Toughness = -14% damage from direct and -2.5% damage from dots.

**Screenshots/Videos or archive.org evidences:**

https://www.youtube.com/watch?v=x9kj7qufdSw

**Comment by sioding** [comment]
Well - the paperdoll and its issues. Did you compared your shown number with the numbers you get while doing a ".getstats" on your own?

**Comment by komar9220** [comment]
> Хорошо - бумажная кукла и ее проблемы. Сравнивали ли вы показанный вами номер с числами, которые вы получили, выполняя «.getstats» самостоятельно?

yes, everything was completely checked

**Comment by komar9220** [comment]
> Well - the paperdoll and its issues. Did you compared your shown number with the numbers you get while doing a ".getstats" on your own?

yes, everything was completely checked

**Comment by Rydiak** [comment]
Toughness is NOT a percent damage reduction, but rather a flat DPS reduction that is modified by offensive stat coefficients. You would need to know the coefficient of the ability striking you and multiply the Toughness DPS reduction by that, and then modify it based on the duration/number of hits/ticks you receive from the DoT.

**Comment by gomboni** [comment]
Then it would make more sense for toughness to be more effective on ticks from dots and it does seem like it is not

**Comment by wargrimnir** [comment]
It is working correctly.

What you want is every single dot tick to be fully affected by toughness. 
That's ridiculous. Your 702 damage mitigation would reduce a dot tick of Radiant Gaze from 584 to 65 damage dealt.

Instead what happens is that a dot has a full value which looks like (AS AN EXAMPLE) 1800 damage over 15s @3s intervals (5 ticks), toughness mitigates that 1800 by 700, bringing it down to 1100, then the dot damage is distributed to each tick afterwards. That would look like 220 damage (140 mitigated) and be an effective reduction of 56%. The lower the initial value of the dot, the higher the effective reduction. For very high damage/long duration dots, they would appear to have even less reduction.

This isn't the exact order of operation, but it should be enough for you to get a basic understanding of it.
