### ISSUE TITLE
Overprotective tactic

### ISSUE THREAD

**Issue by Parallell86** [WarEmu/WarBugs#13971]
`Overprotective` tactic - Ironbreaker (modified to match the requested report profile)

**Expected behavior and actual behavior:**

The tactic is supposed to procc damage on the opponent hitting your Oath friend. (with a 25% chance)

Overprotective tactic deals damage to your Oath friend when they use self-damaging abilities (Slayer with Reckless Gamble ability)

**Steps to reproduce the problem:**
Put Oath friend on a slayer , slayer activate Reckless Gamble ability. Hit something...the self damaging should procc Overprotective hence dealing damage to the Slayer.

**Screenshots/Videos or archive.org evidences:**

![Jarbreaker_003](https://user-images.githubusercontent.com/44731969/56868168-06946700-69ef-11e9-8b00-51446e345b52.jpg)

**Comment by Parallell86** [comment]
![Jarbreaker_003](https://user-images.githubusercontent.com/44731969/56868159-f4b2c400-69ee-11e9-88ee-b57e336005d9.jpg)

**Comment by rekkir** [comment]
related to this; since reckless gamble ability counts as direct dmg dealt by slayer to himself, it also proccs abilities like quick-escape.

**Comment by Parallell86** [comment]
You may also want to check if the BW's combustion proccs Overprotective and therefore damaging the BW further.

**Comment by Parallell86** [comment]
5 days and not even a response. why bother? its just a broken tactic on order.

**Comment by sioding** [comment]
Calm down - as you can see more than 1500 open tickets are inside the bugtracker. nd just to remind you: The same rules apply on the bugtracker as they hit the forum. So up to you - you closed your own ticket so this will never see a dev.

**Comment by Parallell86** [comment]
Lesti made a report on Phosporous Shells after me, and he got enough responses.

I main IB and felt neglected trying to get the broken tactic to your attention. Overprotective is an important tactic and atm it cant be used with Reckless gambling and probably not Funnel Power on BW because they use damage source from the host and punish the host with Overprotective.

Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows 10

________________________________
Från: Sio <notifications@github.com>
Skickat: Friday, May 3, 2019 4:23:01 PM
Till: WarEmu/WarBugs
Kopia: Parallell86; State change
Ämne: Re: [WarEmu/WarBugs] Overprotective tactic (#13971)


Calm down - as you can see more than 1500 open tickets are inside the bugtracker. nd just to remind you: The same rules apply on the bugtracker as they hit the forum. So up to you - you closed your own ticket so this will never see a dev.
