### ISSUE TITLE
"Angry marsh root" very high sell price. Is it bug? 

### ISSUE THREAD

**Issue by Raskrage** [WarEmu/WarBugs#13970]
The Angry marsh root 175 lvl is sold to vendor for 5 silver 50 copper, but Savage Marshroot 200 lvl is sold for 10 copper.  
The simple cultivation of the Angry marsh root 175 allows you to earn a lot of gold without making potions for sale.
Sorry for my English.
![Bozter_016](https://user-images.githubusercontent.com/49660762/56866307-50298580-69e0-11e9-8e99-9931e8050632.jpg)
![Bozter_017](https://user-images.githubusercontent.com/49660762/56866311-53247600-69e0-11e9-8333-ed9071be3dfc.jpg)
![Bozter_018](https://user-images.githubusercontent.com/49660762/56866315-561f6680-69e0-11e9-8067-d0b5feb7e2f0.jpg)

**Comment by Kabucoror** [comment]
correcetd with next patch

**Comment by sioding** [comment]
fixed with patch from 05.05.2019
