### ISSUE TITLE
Minor Loot Bag Won't Open

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#13973]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

I've received a minor loot bag in the game mail. Upon opening the post and taking the item, it's put it in my backpack, but when I click on it in the backpack to open the bag as normal, nothing happens. I've also tried to drag the backpack window around my screen to see if it responds, but the backpack window won't move at all. Not sure if the second issue is related? Have shut the game down and restarted it after restarting the launcher, to no effect.

**Steps to reproduce the problem:**

Not sure

**Screenshots/Videos or archive.org evidences:**

![Ithilsyn_051](https://user-images.githubusercontent.com/22262165/56868756-c208cb80-69ee-11e9-88d4-c3e5c3c7c96f.jpg)

**Comment by sioding** [comment]
When did you get it? The mail you pulled it out have some important informations for us.

**Comment by sioding** [comment]
No answer for 12 days. Close

**Comment by Senthoi** [comment]
(sorry for not replying - I'd missed the response somehow - I tend to delete the in game mails as soon as I retrieve the item so can't advise - but deleted the bag now, this hasn't repeated since)
