### ISSUE TITLE
Stuck in Fell Landing Fort

### ISSUE THREAD

**Issue by no0kiee** [WarEmu/WarBugs#13982]
I've got stuck in fortress lord room in Fell Landing, when lord punted me behind the table with chair, i was untargetable not even could be damaged by aoe lord abilites behind this chair, game messeges in chat about stuck as a proof on a screenshot attached below.
Screenshot:
https://i.imgur.com/yJtlhEl.jpg

**Comment by NorKalli** [comment]
easy fix, plugged them up

**Comment by sioding** [comment]
fixed with patch from 05.05.2019
