### ISSUE TITLE
lvl 20  chalice

### ISSUE THREAD

**Issue by dremmyt** [WarEmu/WarBugs#13987]
it  doesnt regen essenses
![image](https://user-images.githubusercontent.com/26573867/56992516-e73e3b00-6ba2-11e9-8d17-a1219a420639.png)

**Comment by Garrthax** [comment]
i remember this chalice from live, was same

**Comment by ghostlydemonfox** [comment]
had same on WP changed the chalice and reloaded the game

**Comment by dalen** [comment]
unequipping it and equipping it again usually fixes the issue.

**Comment by sioding** [comment]
thx @dalen
