### ISSUE TITLE
Shrine of Tzeentch - Hero not attackable by DD

### ISSUE THREAD

**Issue by ghostlydemonfox** [WarEmu/WarBugs#13980]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page
Tzeentchian artifact cant be attacked or hit by single dmg only aoe is this normal ?? hard PQ highpass
shut be able to target and nuke it
**Expected behavior and actual behavior:**

everytime you do the PQ
**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment]
OK - if you would read your own report: Would you know: Which PQ is being meant?Whats the real problem is? This isn't really enough - please bring in more informations.

**Comment by ghostlydemonfox** [comment]
PQ high pass 24-25Hard shrine of Tzeentch 
on last stage you cannot target hero boss only way to kill it is via AOE or front aoe even if you get the target you cannot single target dmg it only way to kill it is via aoe.
this is the only PQ i have seen like this.

**Comment by sioding** [comment]
great. thanks.

**Comment by sioding** [comment]
fixed with patch from 05.05.2019
