### ISSUE TITLE
Sanctified Oil and Shroud of Magnus

### ISSUE THREAD

**Issue by Garrthax** [WarEmu/WarBugs#13985]
WH skills Sanctified Oil and Shroud of Magnus shares same cooldown. When I use Oil, I got Oil effect and both Oil and Shroud go on cooldown, when I use Shroud, I got Shroud effect and both Shroud and Oil go on cooldown.

after using oil -
![image](https://user-images.githubusercontent.com/49390790/56957924-fd1f1200-6b48-11e9-839d-06f9a747d5f6.png)

after using shroud -
![image](https://user-images.githubusercontent.com/49390790/56957977-2475df00-6b49-11e9-9d31-34c28a11a19f.png)

**Comment by sioding** [comment]
Not sure if this is intended ...

**Comment by dalen** [comment]
Pretty sure that is intentional, WE Elixirs and WH Relics share cooldowns with each other.

**Comment by Garrthax** [comment]
Oil is not considered as relic, so its supposed to have separated cooldown.

![image](https://user-images.githubusercontent.com/49390790/56981884-3f177a80-6b80-11e9-9c76-d1576d10cd25.png)

**Comment by Kabucoror** [comment]
Sry, but all 5 point abilities for WH and WE share the same cooldown. Santified Oil is a replacement for van Horstmanns Specelum, which is/was a relic. So the real problem is a incorrect tooltip.

**Comment by Garrthax** [comment]
ok, its little bit weird, because of real usage of oil as escape, we really need both as counter to overpowered shamans, that dont lost target and beam us even in oil effect

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 13.07.2019
