### ISSUE TITLE
[Fortress] Ineffective cell release - Fell Landing

### ISSUE THREAD

**Issue by synacyror** [WarEmu/WarBugs#13983]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Expected behavior: Releasing persons from the cell should release them in front of the cell
Actual behavior: Releasing persons from the cell releases them into the old location and in turn spawns them in the midst of the r55 champions, rendering the cell lever ineffective/useless

**Steps to reproduce the problem:**
Right-click the lever of the cell > Players inside cell get teleported to the old cell release location (which is in the midst of the r55 champs) > They die instantly and get ported right back into cell

This occurred in Fell Landing

**Screenshots/Videos or archive.org evidences:**
![ineffectivelever1](https://user-images.githubusercontent.com/49698591/56936087-32c0ee00-6aaa-11e9-857d-46c703a38f94.jpg)
![ineffectivelever2](https://user-images.githubusercontent.com/49698591/56936088-32c0ee00-6aaa-11e9-9160-15ec202eadf1.jpg)

Reported by Fun of Destruction.

**Comment by wargrimnir** [comment]
Well shit... That's my fault.

**Comment by sioding** [comment]
fixed with patch from 05.05.2019
