### ISSUE TITLE
Quest: Bearing a Grudge

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#13986]
**Expected behavior and actual behavior:**

The quest does not track the second objective of it of finding the Recods of Scout Ragnarson

**Steps to reproduce the problem:**

Complete the first objective of the quest of killing 6 Brune Scavengers, and the map tracker of the quest disappear entirely.

**Screenshots/Videos or archive.org evidences:**

https://www.subeimagenes.com/img/valaye-001-2024148.jpg

**Comment by Ootootoo** [comment]
I forgot to add my forum name: Ototo

**Comment by Ootootoo** [comment]
![Valaye_002](https://user-images.githubusercontent.com/50114048/56998363-f0c7a300-6ba2-11e9-85fa-faa1dc3aed47.jpg)
I don't thonk that I must open a new issue for the same trouble in diff quest, but feel free to correct me. There are 2 more dwarf quests without map tracking: "Reinforcements" and "Gyrocopter Down", in the stages that can be seen in the screenshot attached.

**Comment by Kabucoror** [comment]
fixed with next patch

only one report per quest chain please

**Comment by sioding** [comment]
fixed with patch from 05.05.2019
