### ISSUE TITLE
[WL] Pounce attack sequence

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#13981]
**Expected behavior and actual behavior:**
attack sequence is Pounce then next skill.
but 2nd skill land first before Pounce. 
in screenshot, first highlight is normal behavior.
second highlight is attack sequence issue.

**Steps to reproduce the problem:**
1. use pounce
2. use next skill within 1.1 GCD timing.
3. second skill become first skill.

**Screenshots/Videos or archive.org evidences:**
![pounce GCD](https://user-images.githubusercontent.com/19988772/56931796-32613b00-6b1c-11e9-98ec-cc8a3cf55d19.jpg)

**Comment by grunbag** [comment]
There is nothing weird here . Unless you want pounce to ignore distance and deal damage before landing

**Comment by anarchypark** [comment]
hitting second melee attack before landing gap closer seem weird to me.
but i follow dev's judgement. had to ask b4 erasing from my mind. :)

**Comment by sioding** [comment]
hm... seems to be answered. Close

**Comment by grunbag** [comment]
It’s not that I don’t want to fix it but think about it : 
WL use pounce at 40 ft with 1.5 second flight time . During the flight time , GCD is over so WL can use a new ability and press it before landing . This ability will trigger before pounce . Unless GCD should be blocked during pounce
