### ISSUE TITLE
Chapter 1 Chaos: Useless Potions

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#13990]
**Forum name**

Ototo

**Related Issues**

Can't find one, but seems strange that nobody have reported this before. Feel free to close it if so.

**Expected behavior and actual behavior:**

The quests that can be seen in the screenchot have useless potions as rewards. I tried a red one, with no apparent effect.

**Steps to reproduce the problem:**

Take the quests of Norsca Chapter 1 Chaos.

**Screenshots/Videos or archive.org evidences:**

![Naggarythe_000](https://user-images.githubusercontent.com/50114048/57014431-01f6cb00-6c08-11e9-9765-3d6e87ff5cb9.jpg)

**Comment by sioding** [comment]
fixed with patch from 01.06.2019
