### ISSUE TITLE
lvl 12 in T1 orvr

### ISSUE THREAD

**Issue by TheRejected** [WarEmu/WarBugs#1399]
I was in T1 orvr zone as lvl 11, went to npc in C3 choas (left orvr zone/warcamp) to finish a quest and ding went to lvl 12 (still rvr flaged), then i could go back to T1 orvr and fight without changing into chicken.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
