### ISSUE TITLE
DESTRO QUEST "A Norse Bargain"

### ISSUE THREAD

**Issue by Hauclir** [WarEmu/WarBugs#140]
![hauclir_000](https://cloud.githubusercontent.com/assets/7598530/3020193/9ffc56ac-df9b-11e3-95be-634d82fd7d5d.jpg)
NPC QUEST GIVER: Werner Dustermann
Unable to interact with prison cage to free Werner to get key

**Comment by Reggaewaldo** [comment]
I have made a change to the Quest finisher for part 1 with ID 40040. This was usually completed by looting the corpse.

I will check this later to verify full function of part 2 with ID 40041.

**Comment by Reggaewaldo** [comment]
Function is verifierd as working. I have also added the name of the NPC you report to.
