### ISSUE TITLE
Chat Text when claiming bo is wrong

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#1400]
says "forces of destruction have taken bo xy" when order does it and vice versa.
![mago_002](https://cloud.githubusercontent.com/assets/13809443/9860825/b578aafc-5b2e-11e5-86cd-5b913608b45f.jpg)

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
