### ISSUE TITLE
Duel is not ending when one of the duelling people is logging out/ disconnecting 

### ISSUE THREAD

**Issue by DanaBloodkiss** [WarEmu/WarBugs#14004]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

A duel should end when an opponent is logging out/ disconnecting or crashing. 

It does not end when someone is logging out/...

Also when the one log in back the second person needs to relog because he can't use any abilities and it seems like the game is freezen for him. 

**Steps to reproduce the problem:**

Start a duel and one have to log out or crash and log back in. 

**Screenshots/Videos or archive.org evidences:**

**Comment by Kaelang** [comment]
The duel system has been reworked. Please re-open if issues persist in the new Garden zone.
