### ISSUE TITLE
While being in a duel my opponent can see me in stealth

### ISSUE THREAD

**Issue by DanaBloodkiss** [WarEmu/WarBugs#14005]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

I don't know if it is expected but the opponent can see a we or a wh while being in a duel in stealth like normally. 

**Steps to reproduce the problem:**

Do a duel against a we or a wh. 

**Screenshots/Videos or archive.org evidences:**

**Comment by ChristianTucker** [comment]
Can confirm this as a problem.

**Comment by Kaelang** [comment]
The duel system has been reworked. Please re-open if issues persist in the new Garden zone.
