### ISSUE TITLE
Inevitable Power - High Pass

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#14009]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

When I reach the stage to kill 3 Savage Flesh Hounds and 1 Savage Bloodletter, all are bringing up the pop up notification on my screen that I killed these mobs. However, the Bloodletter is not ticking off in the quest in my ToK - within the quest page itself. On the quest summary page, it's marking off as complete. The quest is not registering as completing so I can't claim it. I've killed 2 Bloodletters now, and have returned to N'rarch anyway to see if anything happens, but nope.

**Screenshots/Videos or archive.org evidences:**

![IP1](https://user-images.githubusercontent.com/22262165/57184663-a4d47100-6eb6-11e9-9dc1-7f507d5e5730.png)
![IP2](https://user-images.githubusercontent.com/22262165/57184665-aa31bb80-6eb6-11e9-8b60-7dc371c7bd51.png)
![IP3](https://user-images.githubusercontent.com/22262165/57184667-adc54280-6eb6-11e9-9ccc-94ab1c610df4.png)

**Comment by Lheana** [comment]
Were you grouped?

**Comment by Senthoi** [comment]
No, there was a second group in the area though - I'm wondering if they caused damage to the Bloodletters it may impacted on this?

**Comment by Senthoi** [comment]
I'll try it again when it's quieter out there and see if anything changes

**Comment by Senthoi** [comment]
Thinking back, there -was- a level 40 running around.

**Comment by Lheana** [comment]
So ... worked?

**Comment by Senthoi** [comment]
I tried it again today after the patch, and it all worked fine. o/
