### ISSUE TITLE
[SLAYER] Subj Weapons Proc & Retribution

### ISSUE THREAD

**Issue by Muurloen** [WarEmu/WarBugs#14006]
I believe that the Subjugator weapon procs are hitting slayers that use them while using the retribution ability. It seems to be random of when it hits the user.

**Expected behavior and actual behavior:**
Expected behavior - procs only land on the enemy.

Actual behavior - random procs on the slayer.

**Steps to reproduce the problem:**
Have subjugator weapons equipped, have targets in front of you, activate retribution.

**Screenshots/Videos or archive.org evidences:**
![Muurlat_000](https://user-images.githubusercontent.com/50267777/57179817-9dc24a00-6e47-11e9-8e20-98a46f6b9b50.jpg)

![Muurlat_002](https://user-images.githubusercontent.com/50267777/57179835-c9ddcb00-6e47-11e9-95dd-816a12255aac.jpg)

-edit-
It might have something to do with Reckless Gamble. Beating on dummies some more with other abilities, I noticed that it happened during a wild swing,
![Muurlat_003](https://user-images.githubusercontent.com/50267777/57180078-ad8f5d80-6e4a-11e9-86bb-265f4c394623.jpg)

**Comment by grunbag** [comment]
Fixed
