### ISSUE TITLE
Odd stats on Gunbad influence rewards for AM

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#14002]
**Expected behavior and actual behavior:**

The AM Elite influence rewards in Gunbad have melee stats.

Similar issue as https://github.com/WarEmu/WarBugs/issues/12528

**Screenshots/Videos or archive.org evidences:**

![Falinaeth_002](https://user-images.githubusercontent.com/7400/57149807-dcff8500-6dcc-11e9-8946-c9acda766a1b.jpg)
![Falinaeth_003](https://user-images.githubusercontent.com/7400/57149809-dec94880-6dcc-11e9-9f22-f218ea80d73d.jpg)

**Comment by wargrimnir** [comment]
Wow. Those were a damn mess. Corrected stats on 16 items from these influence rewards.

**Comment by sioding** [comment]
fixed with patch from 25.05.2019
