### ISSUE TITLE
Bloody Sun lobber in lob it good!

### ISSUE THREAD

**Issue by Youk83** [WarEmu/WarBugs#14007]
In the green skin strarting zone the quest "lob it good!" could not be done cause of the Bloody sun lobber not working, neither are the lobber gits like said in a previous ticket

**Expected behavior and actual behavior:**
Expected: Lob me to the quest zone 
Actual : let me next to the lobber

**Steps to reproduce the problem:**
Tried to right click / left clik on on the differents lobbers and NPC in the zone with no effects

**Screenshots/Videos or archive.org evidences:**

**Comment by Lheana** [comment]
The lobber is not working for now, nevertheless you can reach the area from southeast, climbing the mountains.
