### ISSUE TITLE
T3 Elf Epic Quest - Control

### ISSUE THREAD

**Issue by evillution** [WarEmu/WarBugs#14011]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

was meant to break the collar but it is not.

**Steps to reproduce the problem:**

T3 Elf Epic Quest - Control , Step 13 , Quest item not working on both NPC

**Screenshots/Videos or archive.org evidences:**

![Afking_000](https://user-images.githubusercontent.com/35712605/57185624-7d12f680-6f12-11e9-8e99-73ad5552147d.jpg)

**Comment by Lheana** [comment]
Stand close to their location.

**Comment by CrimsonFenris** [comment]
Hello, found out clicking on both NPC still wont work, even before aggro, or very close to them.
Tried everything to make both NPC and item clicking working, no effect whatsoever...

**Comment by Lheana** [comment]
The quest works. You have to use the item **targeting the NPC and standing quite close** to their location.
