### ISSUE TITLE
BL Book (destro)

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#14013]
Has wrong icon after patch. (order icon for destro)
![SIGMARisNOgo](https://user-images.githubusercontent.com/42712833/57194957-bae53e80-6f55-11e9-9353-9ad4567057b4.PNG)

**Comment by wargrimnir** [comment]
ugh, why do people mess with things...

**Comment by Lheana** [comment]
Ups I fixed it few patches ago without seeing there was a report for it. So I close it.
