### ISSUE TITLE
Chosen Auras when entering RvR zones

### ISSUE THREAD

**Issue by srwallac** [WarEmu/WarBugs#14018]
I noticed that, while playing my Chosen in T1 Nordland, when I have my auras on in either the camps or PvE zones, then enter the RvR zone, they end and must be re-applied.

When going from RvR to camp or PvE zones, they remain on, as expected.  It's only when heading into RvR zone and it occurs immediately upon entering the zone, with no regard to the countdown to being flagged.

**Comment by sioding** [comment]
This is intended - you get bolstered in RvR and that means every buff will be removed and you have to reapply them
