### ISSUE TITLE
Borealis has 2h stats, but is a 1h Sword

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#14016]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Stats are much higher than they should be for a 1h sword

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

![Lotharic_109](https://user-images.githubusercontent.com/7400/57195378-f3831900-6f51-11e9-9fd0-4e7acca44c96.jpg)

**Comment by NorKalli** [comment]
fixed with patch

**Comment by sioding** [comment]
Fixed with patch from 11.05.2019
