### ISSUE TITLE
Guildbug is back

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#14019]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Changing Zones, entering SCs, Logging in should be without Disconects.
The old Guildbug was fixed a while ago with the joining of your guild after changing the zone 20 seconds later. It was a total and complete fix for all disconects while logging in, changing a zone, or joining a SC. Since this fix was reverted all the mentioned Disconects are back and I get a disconect at every second SC, Loggin In attemp or chaning the zone.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by Natherul** [comment]
going to lower amount of logs sent again. If this does not work after next patch let me know and I will add delay back in again

**Comment by LestiArdisson** [comment]
> 
> 
> going to lower amount of logs sent again. If this does not work after next patch let me know and I will add delay back in again

I will test after next Saturday.

**Comment by sioding** [comment]
fixed with patch from 19.05.2019

**Comment by LestiArdisson** [comment]
Please reopen the bug ticket as the guildbug is still active.
I need something like 6-8 tries to logon or change a zone.

It was fixed back then when guild infos were send 20 seconds after logon.

**Comment by Natherul** [comment]
on next patch we delay the sending again with 30 seconds but only on logins. Rest loads (as they seem fine for players?) instantly.

**Comment by Natherul** [comment]
small change, will be apparent on how its changed on the next patch. But in short a neater way to delay some of the sending has been made

**Comment by sioding** [comment]
fixed with patch from 29.6.2019
