### ISSUE TITLE
New SC bucklers for WP have wrong strike through value 

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#14014]
**Expected behavior and actual behavior:**

Shieldbearer's Buckler of Reverence & Sentry's Buckler of reverence have wrong strike through value. They should have 8%, just like other purple bucklers and like the DoK bucklers.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

![Lotharic_108](https://user-images.githubusercontent.com/7400/57194973-7f467680-6f4d-11e9-98bb-bf60e7743a8a.jpg)
![Lotharic_107](https://user-images.githubusercontent.com/7400/57194974-81103a00-6f4d-11e9-86bc-22b0808c3a0a.jpg)

**Comment by NorKalli** [comment]
fixed

**Comment by sioding** [comment]
Fixed with patch from 11.05.2019
