### ISSUE TITLE
Buckler of Envoy is missing proc

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#14017]
**Expected behavior and actual behavior:**

The buckler of Envoy is missing a proc which all other city influence weapons have.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

![Lotharic_111](https://user-images.githubusercontent.com/7400/57195952-3c3dd080-6f58-11e9-95ad-88d4b3076f79.jpg)

**Comment by sioding** [comment]
Fixed with patch from 11.05.2019
