### ISSUE TITLE
[BG] Filled with Fury Tactic

### ISSUE THREAD

**Issue by Stophy22** [WarEmu/WarBugs#14027]
**Issues should be unique:** Already checked and no other issues have reported it yet, not sure if intended or not. Bolstering Anger does not trigger Filled with Fury tactic, "Increases crit chance by 15% whenever you expend hate to attack" Yes I know the keyboard here is attack, but Shield of Rage, another ability which is not an attack but expends hatred does trigger the proc of Filled with Fury. 

**Expected behavior and actual behavior:**
Expected behavior: Bolstering Anger triggers Filled with Fury(tactic). I deleted the part that said it cannot retrigger til its ended. That was a lie and probably result of lack of sleep while reporting a bug last night. 

Actual Behavior: Filled with Fury is never proc'd by the first use/cost and any subsequent cost of Bolstering Anger, but ability like Shield of Rage will trigger Filled with Fury tactic Proc.

**Steps to reproduce the problem:**
Im making a forum post to see if this is intended or not, if it is intended nothing needs to be changed, but also if it is im going to suggest that it behaves how shield or rage does, the only other skill that costs hatred that doesn't proc Filled with Fury is Driven by Hate, which in all honestly don't think should proc Filled with Fury other than the fact that it costs 40 hate, which could arguably be reason enough.

**Screenshots/Videos or archive.org evidences:**
I have a video but github doesn't seem to accept mp4. So here are some screenshots

First I use Shield of Rage to show the proc happening.
![1st screenshot](https://user-images.githubusercontent.com/23489906/57207271-999e4580-6f89-11e9-8ba9-50b92b3b7350.PNG)

Second I use Bolstering anger to show it doesn't proc.
![2nd screenshot](https://user-images.githubusercontent.com/23489906/57207274-9b680900-6f89-11e9-8503-fe31f3c1f61c.PNG)

Thank you for your time :)

**Comment by grunbag** [comment]
Shield of rage shouldn’t proc it if it’s not an attack

**Comment by grunbag** [comment]
After checking shield of rage is a hate  attack and bolstering anger is a self heal . So everything is working as intended here

**Comment by Stophy22** [comment]
How is it a hate attack? It’s a defensive shield that uses hate. Bolstering anger is a self heal that uses hate? How does attack come from shield of rage? Honestly just curious

**Comment by grunbag** [comment]
Using hate doesnt mean its an attack . It proc when you deal damage when you use a hate ability . One is healing you (no damage and no proc) and the other is a damage over time (so it can proc on damage dealt)

**Comment by Stophy22** [comment]
I’m still confused as to what is a damage over time. BGs only dot is crippling anger which doesn’t use hate at all. Regardless I understand how the tactic works and what Abilites proc it and no further explanation is needed. 

Albeit, bolstering anger is a heal over 30 seconds and shield of rage is a shield over 10 seconds. They’re both defensive hate consuming Abilites and only one procs Filled with Fury. It Doesn’t truly make sense why one procs it and one doesn’t. Same tree, same resource, both defensive abilities. One is healing (no damage and no proc) one is shielding you (no damage and a proc)

**Comment by grunbag** [comment]
Ah yes my mistake . I misread tooltip. I’ll check it again and probably don’t make any proc for both
