### ISSUE TITLE
more stats on staff caster dps scenario than other weaps

### ISSUE THREAD

**Issue by kyranria** [WarEmu/WarBugs#14020]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

<a href="https://imgur.com/VjC8drl"><img src="https://i.imgur.com/VjC8drl.jpg" title="source: imgur.com" /></a>

**Comment by NorKalli** [comment]
fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 11.05.2019

**Comment by sioding** [comment]
Fixed with patch from 11.05.2019
