### ISSUE TITLE
Harrower - chosen weapon - proc won't trigger

### ISSUE THREAD

**Issue by Parocw** [WarEmu/WarBugs#14022]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Pilfer proc never trigger

**Steps to reproduce the problem:**
make pilfer great again

**Screenshots/Videos or archive.org evidences:**

**Comment by grunbag** [comment]
Need more infos

**Comment by sioding** [comment]
No answer since 25 days. close
