### ISSUE TITLE
WL Hunter stance

### ISSUE THREAD

**Issue by Farlopa** [WarEmu/WarBugs#14025]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Wl hunter stance is shared his proc with all group members

**Steps to reproduce the problem:**
Make a group change to hunter stance and its done all members has the hunter stance buff

**Screenshots/Videos or archive.org evidences:**

**Comment by grunbag** [comment]
Fixed at next patch

**Comment by sioding** [comment]
Fixed with patch from 11.05.2019
