### ISSUE TITLE
Barber Surgeon still broken

### ISSUE THREAD

**Issue by Ryanfawkez** [WarEmu/WarBugs#1403]
Another trivial appearance glitch; but the Barber Surgeon in both the Inevitable CIty and Altdorf haven't been working for weeks now. I remember a time when it DID; right before the T1 and T2 vendors were re-added.

**Comment by Krumlok** [comment]
Then something must have broken it. IDK what could it exactly be, though.

**Comment by Runulf** [comment]
The barber surgeon still don't work, it's impossible to check out

**Comment by nalgol** [comment]
o_O it never worked i just added the window popup but never implementet the function

**Comment by Ryanfawkez** [comment]
Nalgol, it was functional (somehow) upon my return to the game, somewhere in August. Then, after a few patches, it was probably reverted to your applied settings (I think after the blue/purple fragment scavenging for regular mobs was done)

**Comment by Armond-Hammer** [comment]
As of 1/3/2016 Still not functional Window pops up but no thing happens when Check Out is clicked.

**Comment by Evildoor** [comment]
Barber partially fixed now - relog to apply new appearance.
