### ISSUE TITLE
Choppa Invader Helmet

### ISSUE THREAD

**Issue by Jonees123** [WarEmu/WarBugs#14032]
Invader Skully should give 3% armor penetration, but it gives +3 intelligence instead.
![kuva](https://user-images.githubusercontent.com/47939256/57246330-b1d39a80-7045-11e9-9193-b530d7536ed7.png)
![kuva](https://user-images.githubusercontent.com/47939256/57246433-eb0c0a80-7045-11e9-8ae0-3f5faaa8aec1.png)
![kuva](https://user-images.githubusercontent.com/47939256/57246535-2b6b8880-7046-11e9-8aa1-a008e3749245.png)

**Comment by kyranria** [comment]
use .getstat to see % armor pen from item

**Comment by Jonees123** [comment]
I guess it's working as intended then, getstats shows armor pen, but not the +3 intelligence it adds.
