### ISSUE TITLE
AM 7pcs. Invader proc 

### ISSUE THREAD

**Issue by Galaxyshine** [WarEmu/WarBugs#14030]
The 7 pieces bonus proc of the invader set for AM is not triggered for the following abilities from the path of Isha:

- Mistress of the Marsh
- Prismatic shield

*no screen, because no trigger ;)

In addition, it feels that the increased crit value of this proc is NOT existent.

The first heal was **with** active proc
The second heal was **without** proc

![7pce proct](https://user-images.githubusercontent.com/50300648/57316478-2c5bf300-70f6-11e9-9044-1ff280ee3b3e.jpg)

AND

In the buff display the crit increase is showen with 25%.

![7pce proct](https://user-images.githubusercontent.com/50300648/57318323-59120980-70fa-11e9-9a40-d1725db5213a.jpg)

**Comment by Galaxyshine** [comment]
In addition, it feels that the increased crit value of this proc is NOT existent.

The first heal was with active proc
The second heal was without proc

7pce proct

AND

In the buff display the crit increase is showen with 25%.

7pce proct

**Comment by Galaxyshine** [comment]
*added issue

**Comment by grunbag** [comment]
tooltip is wrong, it's not 25% but 12%

**Comment by grunbag** [comment]
fixed for next patch

**Comment by sioding** [comment]
Fixed with patch from 11.05.2019
