### ISSUE TITLE
Chosen Auras

### ISSUE THREAD

**Issue by Zlatish** [WarEmu/WarBugs#14038]
Class: Chosen

Skill: Auras

Issue: Hot bar indicates 3 active chaos auras, however portrait buffs show more than 3 active auras if cycled through.
![ChosenBug](https://user-images.githubusercontent.com/50371683/57308280-fb6fc400-70dd-11e9-8f06-10b2503c605a.png)

User: Yorgin

**Comment by sioding** [comment]
Duplicate of #13794
