### ISSUE TITLE
New scenario weapons [squig herder] Strength instead of ballistic 

### ISSUE THREAD

**Issue by IxanderousI** [WarEmu/WarBugs#14040]
New scenario weapons incorrect stat distribution, sentrys stabba of anathema and sentrys shoota of anathema showing strength stats instead of ballistic, if the intention is perhaps for the purposes of being used for melee squig builds, squig armor already converts ballistic to strength so perhaps this is oversight or just simple mistake.
![Wrong](https://user-images.githubusercontent.com/25346641/57335235-de58e680-7119-11e9-8877-5026585efc0e.png)

**Comment by sioding** [comment]
Fixed with patch from 11.05.2019
