### ISSUE TITLE
[Dungeon] Warpblade Tunnels wrong Dye reward

### ISSUE THREAD

**Issue by XmatXergon** [WarEmu/WarBugs#14045]
**Expected behavior and actual behavior:**
Reward from completing quest in Warpblade Tunnels on Order side should contain Legendary Dye not normal one (as does Sigmar Crypts quests and all Destro city dung quests).

**Steps to reproduce the problem:**
Pickup quests in docks in Altdorf to check reward.

**Screenshots/Videos or archive.org evidences:**
![image](https://user-images.githubusercontent.com/37849311/57370666-f91a7200-7190-11e9-888d-f8de10118b3b.png)

**Comment by NorKalli** [comment]
rare dyes added

**Comment by sioding** [comment]
Fixed with patch from 11.05.2019
