### ISSUE TITLE
[Quest] Crypts and Tunnels

### ISSUE THREAD

**Issue by Chudas** [WarEmu/WarBugs#14049]
During yesterday evening we have done full run of city dungeons to complete quest [Crypts & Tunnels]. The run went smoothly without any problem. At the end i checked my ToK and i was missing one kill but i got lockout for it. 

<img width="481" alt="Snímek obrazovky (1)" src="https://user-images.githubusercontent.com/12033869/57435393-9337f400-723d-11e9-9e00-ca096e679440.png">

**Comment by sioding** [comment]
And did you screend also the yellow spam? On every boss you see if there are some credit problem with the yellow server spam in chat.

**Comment by Chudas** [comment]
No i didn´t. This screenshot is from day after we have done the run. The run went perfect and during Warlock Peenk encounter nothing went wrong, whole party stayed alive. Thats why i wasn´t paying much attention to the quest. Alter run i just logged off.

**Comment by dalen** [comment]
This is likely from the same run that I shared in the #tester channel

**Comment by grunbag** [comment]
Hargrim Fixed it recently
