### ISSUE TITLE
High lag and server disconnection constantly.

### ISSUE THREAD

**Issue by SATANICOMODERNO** [WarEmu/WarBugs#14046]
Since May 7th I'm having a terrible experience in game due the high lag spike where game gets frozen and the constantly server disconnection. I've checked my internet directly with my internet company, but yet the lag and disconnection persist. I have the 64bits option enabled on launcher and my game had no problem before the day I mentioned above. 
I'm running without options to bring game stable again, so I'm opening this issue hoping I can get some help.

**Comment by sioding** [comment]
Sorry but the bugtracker is for ingame problems only - not for client problems. please use our tech support forum
