### ISSUE TITLE
[PQ] Fireforges camp: crates are not attackable

### ISSUE THREAD

**Issue by KarimaRada** [WarEmu/WarBugs#14044]
**Expected behavior and actual behavior:**
At the stage #1, you have to destroy 10 supply crates. However, you cannot do this because most of the crates are not attackable. When you try to hit them, you receive a message "Target is not attackable":
![crate1](https://user-images.githubusercontent.com/50321390/57369839-0bec7100-71a8-11e9-9f8a-7a6ece296803.jpg)

There are however two crates at 19078, 10602 that you CAN hit:
![crate2](https://user-images.githubusercontent.com/50321390/57369943-55d55700-71a8-11e9-9999-3378d34a7f33.jpg)
But the rest of the crates aren't hittable.

**Steps to reproduce the problem:**
Just go to the PQ and try to attack any of the crates in the main area.

**Screenshots/Videos or archive.org evidences:**
Please see the screens above.

Thank you for your time!

**Comment by sioding** [comment]
fixed with hotfix from 05.06.2019
