### ISSUE TITLE
Tank city inf weapons, pilfer

### ISSUE THREAD

**Issue by edavoc** [WarEmu/WarBugs#14041]
The pilfer proc on the new city dungeon epic weapons for tanks is incorrect. The value on the tooltip states pilfer steals 150 health, in game when the proc occurs the value is only 112.
![Aedrik_013](https://user-images.githubusercontent.com/16967436/57342425-fd04b080-710c-11e9-94a4-cdab099cf250.jpg)

**Comment by grunbag** [comment]
You’re level 40?

**Comment by edavoc** [comment]
Yes

**Comment by edavoc** [comment]
Did not have the onslaught pilfer activated either.

**Comment by NorKalli** [comment]
Please be specific in your posts, give me an exact name of a weapon with the broken pilfer on it

**Comment by edavoc** [comment]
Fate of Tolya is the weapon, but i think its all tank 2hands with the pilfer proc. I have confirmation from a swordmaster that his pilfer was 112 as well.

**Comment by grunbag** [comment]
fixed for next patch

**Comment by sioding** [comment]
fixed with patch from 01.06.2019
