### ISSUE TITLE
inf reward wrong career

### ISSUE THREAD

**Issue by Lermartes** [WarEmu/WarBugs#14047]
Festenplatz Pillager Dark Band influence reward  tier 1  
got it on a zealot but it changed from career:zealot to career:blackguard

charactername with this issue: Corex

**Comment by NorKalli** [comment]
need item name and/or screenshot

**Comment by Lermartes** [comment]
![20190509_124016](https://user-images.githubusercontent.com/50427974/57447796-1f571500-7258-11e9-9392-8773d1848e41.jpg)

**Comment by wargrimnir** [comment]
It was fixed. Previously it did not have a class requirement so it showed up for all classes as an option. Feel free to destroy it.
