### ISSUE TITLE
WP hammer 2h sc 

### ISSUE THREAD

**Issue by kyranria** [WarEmu/WarBugs#14050]
main hand instead of greatweapon also speed weap 3.4 instead of 3.8

<a href="https://imgur.com/6d7w924"><img src="https://i.imgur.com/6d7w924.jpg" title="source: imgur.com" /></a>

**Comment by dalen** [comment]
oh, lol, could create pretty strong grace specs with that :)

**Comment by NorKalli** [comment]
correct me if I'm wrong but all 2h weapons are main hand only. speed is fixed though.

**Comment by dalen** [comment]
No, compare with 2h in https://github.com/WarEmu/WarBugs/issues/14052 it says "Both hands" and "Great Nammer".

**Comment by sioding** [comment]
Fixed with patch from 11.05.2019
