### ISSUE TITLE
Class Mechanic Dropping

### ISSUE THREAD

**Issue by Manatikik** [WarEmu/WarBugs#14058]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Class mechanics that give buffs/stances are dropping randomly. Also getting group mate's mechanic such as dropping Assault Stance and gaining Trained to Hunt on SW,

**Steps to reproduce the problem:**

Random, happen all the time but often on zone swaps.

**Screenshots/Videos or archive.org evidences:**

![tth on sw](https://user-images.githubusercontent.com/19319894/57512352-9e843180-72c8-11e9-9efe-6449838d2e25.png)

EDIT: Seem's to be tied to Trained to Hunt specifically. When resummon the pet with TTH up you drop other mechanics. Doesn't seem to happen with TTK

**Comment by Ootootoo** [comment]
Seems the same that this one: https://github.com/WarEmu/WarBugs/issues/14003

I presume that it has nothing to do with bolster then, cause that character is level 40.

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 11.05.2019
