### ISSUE TITLE
Eataine RvR Quests

### ISSUE THREAD

**Issue by GhostNHZ** [WarEmu/WarBugs#14057]
The RVR Quest from Lanril Elderborn in the WC Eataine is not possible to activate. With right click on Lanril nothing happend.

Greetz Sandaran

**Comment by GhostNHZ** [comment]
![Sandaran_000](https://user-images.githubusercontent.com/37695079/57509292-26d3f800-7304-11e9-9027-6efa8607c48c.jpg)

**Comment by Lheana** [comment]
Works fine for me.

**Comment by sioding** [comment]
No answer since 25 days. close
