### ISSUE TITLE
Apostle's Sledge  of Reverence is missing icon (WP RR61 heal 2h hammer)

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#14052]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Apostle's Sledge  of Reverence is missing item icon

**Screenshots/Videos or archive.org evidences:**

![Lotharic_123](https://user-images.githubusercontent.com/7400/57450713-82987580-725f-11e9-9e7d-c55655879181.jpg)

**Comment by sioding** [comment]
Fixed with patch from 11.05.2019
