### ISSUE TITLE
[Blackguard] Punt ability Exile bypassing block

### ISSUE THREAD

**Issue by Antismar** [WarEmu/WarBugs#1405]
Tested in scenario - m2 active 100% block - everything blocked except punt. Was facing enemy bg. It did not get registered in combat log even.
2nd test in pve - prearranged. m2 morale, facing enemy, all abilities blocked from bg except exile. It got registered this time.

Also exile damage seems bugged - it was hitting for 1 damage (~130 mitigated) while other abilities from that bg were hitting for ~30-50 damage at least.

**Comment by Evildoor** [comment]
Hmm, something tells me that this problem may be similar to https://github.com/WarEmu/WarBugs/issues/1124.
