### ISSUE TITLE
[Fort] Gaining 30k renown on failed defense.

### ISSUE THREAD

**Issue by abelbrian2002** [WarEmu/WarBugs#14056]
You gain 30000 renown from capturing Fell Landing. Unfortunately this was from a failed Fort defense.

It is the same amount of renown for a successful fort capture.

**Comment by abelbrian2002** [comment]
![30k from failed defense](https://user-images.githubusercontent.com/50473574/57501012-71755600-72ab-11e9-96a5-ef2da0c4b70a.jpg)

**Comment by abelbrian2002** [comment]
Same thing is happening on failed Fort Capture.

**Comment by abelbrian2002** [comment]
![Fort fiz](https://user-images.githubusercontent.com/50473574/57576295-e5396f00-7421-11e9-86b4-d4f52fd234a4.png)
Looks like a ninja fix happened

**Comment by Natherul** [comment]
fortresses always give the amount of rr on completion no matter result
