### ISSUE TITLE
Quest: Nobility: Quest item drop issue.

### ISSUE THREAD

**Issue by Scutarius91** [WarEmu/WarBugs#14053]
Blighted Robe does not drop.

**Comment by Lheana** [comment]
Tested, works fine. Check your quest inventory, and try solo to be sure only you can drop the item.

**Comment by sioding** [comment]
No answer since 25 days. close

**Comment by Etaew** [comment]
I have this issue, after killing the Blight Belivers in large numbers, and having 10/10 kills on the Nobility quest, there is no Blighted Robe in my quest inventory to click. I am solo. Have tried logging in and out and killing again, have not tried abandoning quest and restarting.
