### ISSUE TITLE
No Credit for boss kills in BE

### ISSUE THREAD

**Issue by xaraxdestr** [WarEmu/WarBugs#14054]
Full group, 5 player without lookout, 1 player with full lockout on 5 bosses.
We did BB and every boss counted towards kill quests.
We did BE and no boss counted towards kill quests. (they got influence)
The guy with lockout didn't have the killing blow.

**Comment by sioding** [comment]
Can i please see a screen of the .lockout command and the yellow spam you got after the kill?

**Comment by xaraxdestr** [comment]
hmm didnt screen lookout (will do this if happens again)
I just got a screen after 1st kill BE

![Knochenschwert_000](https://user-images.githubusercontent.com/45398873/57485065-088dde00-72ab-11e9-93e6-237640a09b15.jpg)

**Comment by raptrr** [comment]
@xaraxdestr did it happend again? Any new info? :)
