### ISSUE TITLE
Guard damage

### ISSUE THREAD

**Issue by joschika77** [WarEmu/WarBugs#1406]
Toughness and/or armor BUFFS (Example: IB) on target have no effect on incoming guard damage.
This would be mitigated, or is this wrong?

Yesterday testet on Mobs and Enemy.

**Comment by Evildoor** [comment]
https://github.com/WarEmu/WarBugs/issues/1359
Guard damage cannot be mitigated, only blocked/parried.

**Comment by joschika77** [comment]
How many base block chance has an applied shield? 50%? The display will show 0%

**Comment by Thorgatin** [comment]
Green shields should have about 20% iirc (depending on level).

**Comment by joschika77** [comment]
thx @Luth

**Comment by Thorgatin** [comment]
You can check it here, if needed:
http://tools.idrinth.de/tank/?
