### ISSUE TITLE
BB Bartholomeus issues

### ISSUE THREAD

**Issue by Magicarpe4242** [WarEmu/WarBugs#14069]
We did it yesterday and everything was smooth but today we faced many issues.

Group is getting wrecked by AoE damages, like around (2or3 ) * 2 k damages. 

Adds didn't spawn on main tank.

Gonna link combat log to make my point

![bug](https://user-images.githubusercontent.com/50532359/57575735-c7cfc980-7450-11e9-9851-e65033555421.png)

**Comment by biglimey** [comment]
Getting crit in pve is almost certain death.  Are you 0% chance to be crit in this screenshot?

**Comment by NorKalli** [comment]
Just tried the dungeon, same issue. Nurglevomit 100% crit

**Comment by grunbag** [comment]
Pull adds away from group with second tank

**Comment by grunbag** [comment]
It should be fixed already
