### ISSUE TITLE
Dwarf chapter 15 quest does not give needed quest item

### ISSUE THREAD

**Issue by CaptainSeal** [WarEmu/WarBugs#14060]
At certain point (step 3) quest "Organ Donors" requires you to launch Box of Explosives quest item on the nearest ridge. Quest item is missing.

**Expected behavior and actual behavior:**
Be able to found quest item in inventory to use it and proceed.
Actual: unable to find quest item.

**Steps to reproduce the problem:**
Proceed with quest "Organ Donors" in dwarf ch15 util step 3 that requires you to launch box of explosives on the nearest ridge.

**Screenshots/Videos or archive.org evidences:**

**Comment by Lheana** [comment]
Thanks for report, will be fixed with next patch.
Note that you will have to abandon and retake the quest to receive the item.

**Comment by sioding** [comment]
Fixed with patch from 11.05.2019
