### ISSUE TITLE
Stricken Voices and T-blasting.

### ISSUE THREAD

**Issue by TheOGScav** [WarEmu/WarBugs#14066]
Not really a bug but I don't think it is working as intended. Stricken Voices is an AoE silence but will also punts away if it crits with T-blasting 'cause it's under Path of Destruction. If it is a design issue, simply make it a core ability.

**Comment by sioding** [comment]
Sorry - bugtracker is for bugs only. If you wanna change something please use our forum.

**Comment by TheOGScav** [comment]
k
