### ISSUE TITLE
[SH] Finish'em off low damage

### ISSUE THREAD

**Issue by notre4ror** [WarEmu/WarBugs#14078]
**Expected behavior and actual behavior:**
My tooltip says "deals 1233 damage if target is below 30% hit points or 733 damage otherwise"

I've tested against NPC lvl 40, with armor and ini debuf up on the target, and it's doing stable normal 1050 damage (sometimes less) and max crit i saw was for around 1500 damage (1233*1,5 = 1849 expected damage)

BS: 935
WS: 635
Tactics used: Pick on yer own size, Masterfull aim, piercing defenses and Shoting wif da wind.
NPC tested: Wyverns, Salkers and others from black crag.
Pet: Gas 

Thanks.

**Comment by grunbag** [comment]
just tested on dev : my tooltip says 1174 damage if target is below 20%
i hit the target for 1068 damage. (624 + 444 mitigated)
