### ISSUE TITLE
[Quest] An Army Marches - Missing quest Item inventory

### ISSUE THREAD

**Issue by IxanderousI** [WarEmu/WarBugs#14070]
The quest is currently bugged, it states you have to Kill 5 Magi Seers then open your quest inventory to activate an item in it, no item has appeared in inventory and thus quest cannot be completed. 

Quest objective shows as...

Kill 5 Magi Seers 0/5
Ogre-Magi connection 0/1

**Comment by Lheana** [comment]
You have to kill the Magi to complete the first objective (seems obvious) and they drop the item for second objective and to turn in the quest.

**Comment by Lheana** [comment]
You have to examine the item, as explained in the quest.

**Comment by IxanderousI** [comment]
Read what i wrote, i completed the objective and did not get an item to click on to complete objective.

**Comment by Lheana** [comment]
Magi drop the item. If you killed the 5 and haven't looted it yet, then you may have been unlucky, so keep killing them, they will drop it.

**Comment by Lheana** [comment]
No answer for 20 days, I close this.
