### ISSUE TITLE
no invader reward after crash in fort

### ISSUE THREAD

**Issue by mursaat1337** [WarEmu/WarBugs#14072]
Hello, I did the fort tonight for defense of The Maw, Orkalli and my guildmate Ainsdottr can vouche for me and I have a screenshot of after i crashed and it did not give me my reward. I had 33 medallions and should of had 37 for the fort contribution. I know it feels like im missing more evidence but those players who were in that fort saw me do jail defense and can vouche that i was there.
![dc after lord died no meds](https://user-images.githubusercontent.com/50028473/57577907-7bd05500-744f-11e9-97e3-04dfccf77eac.JPG)

**Comment by Natherul** [comment]
currently you need to be ingame once forts conclude to get rewards, this is how its currently done and will probably change later but for now thats the reason.

**Comment by randallbcotter** [comment]
I had this happen as well. It would be great if you could receive them in the mail for your contribution. 3 FREAKING CRASHES during the fort tonight.

**Comment by Natherul** [comment]
this has already been added as of yesterday however it can take up to a server restart for the mails to arrive. Ill leave this open until next patch and if you dont have the mail after next reboot @randallbcotter then please reply back here.

**Comment by Natherul** [comment]
this should no longer be an issue.
