### ISSUE TITLE
[cosmetic] 2h sword with 1h appearance

### ISSUE THREAD

**Issue by Skullgrin** [WarEmu/WarBugs#14074]
Item 'Greatsword of Exult' has a 1h appearance but is a 2h sword.
![Thargrimm_773](https://user-images.githubusercontent.com/40448982/57578812-67408c80-7450-11e9-8022-66ba88dffc0c.jpg)

**Comment by NorKalli** [comment]
fixed

**Comment by sioding** [comment]
fixed with patch from 19.05.2019
