### ISSUE TITLE
Abilities that are off global cooldown display as not used on toolbar when activated in quick succession

### ISSUE THREAD

**Issue by Seraphror** [WarEmu/WarBugs#14073]
![Seraphene_002](https://user-images.githubusercontent.com/23730185/57578043-d0c19a80-7452-11e9-9032-6dae317d3098.jpg)
![Seraphene_003](https://user-images.githubusercontent.com/23730185/57578044-d6b77b80-7452-11e9-8298-417fb224a177.jpg)

I'll try to describe this as best possible, refer to screenshot for an idea of what to expect.

It appears that when using two abilities that are off the global cooldown in quick succession/at the same time, bugs out the second ability used. The ability will be on cooldown but highlighted on the toolbar and presented as being available/not on cooldown.

For example in my case, if I activate Feinted Positioning first and Elixir of shadows second but at roughly the same time, feinted positioning will display as being on cooldown but elixir of shadows not.

This is most bothersome when using a nerfed button sequence for a common WE/WH opener. For example, Placing a Nerfed buttons sequence of FP and EoIP and then Pistol Whip/Heartseeker on the same key will result in heartseeker not being able to activate after activating on the same key as EoIP; EoIP will display as not being on cooldown, and the character will attempt to use it and fail at activation thus resulting in not being able to activate Heartseeker in the sequence.

If this was done to intentionally cripple Nerfed Buttons I could understand; however, the bug will still manifest when using Feinted positioning and an elixer in quick succession when those abilities are on seperate keys (in my screenshot's case, 4 and Q) Either way, a cooldown display bug will be present.

On my screenshots refer to Elixir of Shadows binded to Q being surrounded by an activation border but not reverting to cooldown state after activation.

-S

**Comment by Seraphror** [comment]
Just wanted to add, for what its worth, I tested this on WH relics as well. Same issue so it seems not to be isolated on just one class.

**Comment by grunbag** [comment]
It’s client limitation can’t edit this
