### ISSUE TITLE
[cosmetic] 2h sword that is also off hand

### ISSUE THREAD

**Issue by Skullgrin** [WarEmu/WarBugs#14075]
The item 'Dragonslayer Claymore' is usable in both hands and is also tagged to be used off hand.
Due to it's being tagged off hand, it cannot be used cosmetically, and seems to be a unique appearance item.

![Thargrimm_772](https://user-images.githubusercontent.com/40448982/57578870-1bdaae00-7451-11e9-809f-70245567d9e9.jpg)

**Comment by wargrimnir** [comment]
Corrected Dragonslayer 2h weapons to be Main hand only

**Comment by sioding** [comment]
fixed with patch from 25.05.2019
