### ISSUE TITLE
 Zealot endgame renown wep missing +AP/crit

### ISSUE THREAD

**Issue by vcastanza** [WarEmu/WarBugs#14079]
**Issue:**
The new Zealot 1H RR wep for healers is missing the +AP or +reduction in being critically hit. The intel 1H variant appears fine. These bonuses are available in the Dok/WP/AM/Shaman/RP sets.

Here is the intel based 1H (notice the +3AP)
[Nihilist's Skinflayer of Anathema](https://i.imgur.com/fLRTPiK.png)

Here is the one for healer (notice lack of + anything)
[Apostle's Skinflayer of Anathema](https://i.imgur.com/IrRHlWQ.png)

For reference, here is the Dok equiv:
[Apostle's Xiphos of Anathema](https://i.imgur.com/jlScFBj.png)

**Suggestion:**
Add a +3AP or +1% reduction in being critically hit to this item

Item names that need fixing:
Zealot item Name = "Apostle's Skinflayer of Anathema"

Update:  RP bonus actually appears fine.  This is solely a Zealot item issue.

**Comment by sioding** [comment]
fixed with patch from 19.05.2019
