### ISSUE TITLE
Enginieer - Flak Jacket and Burn Slave skills (BUG)

### ISSUE THREAD

**Issue by Qwacit** [WarEmu/WarBugs#14076]
Flak Jacket and Burn Slave Skills exclude each other since last patch from 11.05.19

**Comment by dalen** [comment]
Burn Salve, not Burn Slave. They are not Chaos Dwarves! :)

**Comment by Qwacit** [comment]
Hahaha In fact, you're right :))) I'm sorry for the mistake. But this bug not always revealed, sometimes, as I noticed

**Comment by grunbag** [comment]
for me it work fine i can cast both on myself
