### ISSUE TITLE
Can't equip axe on Choppa

### ISSUE THREAD

**Issue by SODIX** [WarEmu/WarBugs#14083]
I got two axes from vendor, but can't equip it for no reasons. I think it's a bug. See screenshots here:
<a href="https://ibb.co/xY700Jb"><img src="https://i.ibb.co/xY700Jb/Gruntag-004.jpg" alt="Gruntag-004" border="0"></a> <a href="https://ibb.co/Wvfq0wD"><img src="https://i.ibb.co/Wvfq0wD/Gruntag-005.jpg" alt="Gruntag-005" border="0"></a> <a href="https://ibb.co/TcTYdD7"><img src="https://i.ibb.co/TcTYdD7/Gruntag-006.jpg" alt="Gruntag-006" border="0"></a> <a href="https://ibb.co/hdcmP3j"><img src="https://i.ibb.co/hdcmP3j/Gruntag-008.jpg" alt="Gruntag-008" border="0"></a>

**Comment by grunbag** [comment]
You’re trying to equip a 2h weapon with a 1h weapon . It’s not possible . You need to slot 2 1h weapon or 1 2h weapon

**Comment by SODIX** [comment]
Got it, thanks.
