### ISSUE TITLE
Sentinel Soul vendor is out of order

### ISSUE THREAD

**Issue by rekkir** [WarEmu/WarBugs#14089]
**Expected behavior and actual behavior:**

Wanted to exchange my influence weapon for another. Went to the vendor, unequipped my weapon, checked the "are you sure you want to do this" and accepted, but my weapon remains in my inventory and there is no soul either.

**Steps to reproduce the problem:**

Do as I did above :) 

Thx

**Comment by NorKalli** [comment]
Costs 40 gold, can't display in the vendor though for some reason

**Comment by rekkir** [comment]
OH damn really! thanks man, wish i knew earlier. Ha!

**Comment by NorKalli** [comment]
Sentinel souls now have a prompt in their description as to warn you that they cost 40 gold.

**Comment by sioding** [comment]
fixed with patch from 19.05.2019
