### ISSUE TITLE
BW tactic Close Quarters bugged

### ISSUE THREAD

**Issue by LadyCereus** [WarEmu/WarBugs#14086]
Close Quarters is bugged for me as of the last few days. In melee range, my casting times are no shorter. If I remove the tactic then add it back to the slot, sometimes it will work for a few spells. After I kill a few enemies, it goes back to not working.

Also related:  Fueled from Within doesn't seem to be working correctly either.  Flame Shield is still doing 105 damage to attackers, rather than the enhanced amount.

**Comment by sioding** [comment]
Can we please see your testing screenshots?

**Comment by LadyCereus** [comment]
Thanks for the reply.  As of today it seems to be fine.  If the issue happens again will post here.

**Comment by grunbag** [comment]
you need to select a target within range to make it work

**Comment by sioding** [comment]
Answer given - Close
