### ISSUE TITLE
Keep lords unkillable

### ISSUE THREAD

**Issue by Danszilver** [WarEmu/WarBugs#14088]
Last report of this bug has been about 2 years ago, so lets try this again:

**Expected behavior and actual behavior:**
Keep lord aggro and hp resets every .5 seconds and is therefore unkillable. Keep lord keeps resetting and running back to the middle of the floor resetting aggro and hp.

Keep lord should not reset aggro and hp.

**Steps to reproduce the problem:**
Any keep in tier 4, not sure about other tiers. Have not been able to check. I heard it was a problem with all *HERO* lord types, therefore forts are not affected?

**Screenshots/Videos or archive.org evidences:**
![Ninetyfour_000](https://user-images.githubusercontent.com/50529499/57697893-93c4f600-7654-11e9-97e0-e44d2640d127.jpg)
![Ninetyfour_001](https://user-images.githubusercontent.com/50529499/57697904-96275000-7654-11e9-829c-74edc6bbe226.jpg)
![Ninetyfour_002](https://user-images.githubusercontent.com/50529499/57697905-97587d00-7654-11e9-85a5-33bbce018361.jpg)

**Comment by sioding** [comment]
We know it and @Natherul is on it - but its not that easy as it seems. We know that its something important and the GM team helps at everytime we can. Please be patient - we hotfix it as fast as we have some clue whats going wrong.

**Comment by Natherul** [comment]
This is now fixed and verified fixed on the server. Thanks for the report
