### ISSUE TITLE
Missing nameplate

### ISSUE THREAD

**Issue by Ciremyk** [WarEmu/WarBugs#14084]
**Expected behavior and actual behavior:**

Chaos Chapter 13 Keep of Asavar Kul PQ mobs "Kulian Bonewarrior" are missing nameplates. 

**Steps to reproduce the problem:**

No addons involved.

**Screenshots/Videos or archive.org evidences:**
![Ciremya_000](https://user-images.githubusercontent.com/18365612/57627755-e17c2880-7598-11e9-9611-d6c6aafe47b8.jpg)

**Comment by sioding** [comment]
fixed with patch from 19.05.2019
