### ISSUE TITLE
[Item] Chapter 4 Chaos Proving Grounds rewards

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#14099]
**Expected behavior and actual behavior:**

One of the influence rewards has empty stats. Only checked as Witch Elf.

**Steps to reproduce the problem:**

Speak with the rally master of chapter 4 chaos.

**Screenshots/Videos or archive.org evidences:**

![Hagganeth_000](https://user-images.githubusercontent.com/50114048/57845205-6e0d2d80-77c9-11e9-8ff1-ad06458be7d4.jpg)

**Comment by wargrimnir** [comment]
Freezing band was not set for Sorc, added stats and career requirement.
This also affected Black Orc, Choppa, and Shaman rewards as those were set incorrectly. They are all flagged with correct careers and stats now.
WE should now only see Mirrored Ring, which has correct stats.

**Comment by sioding** [comment]
fixed with patch from 25.05.2019
