### ISSUE TITLE
Quest: Praag "Deaf ears"

### ISSUE THREAD

**Issue by axisd** [WarEmu/WarBugs#14094]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Hi,
active quest is not marked on the map
Thnx

**Screenshots/Videos or archive.org evidences:**
![war_bug_deaf](https://user-images.githubusercontent.com/2901788/57839198-e75b4f00-77ce-11e9-8478-c3d1defa6e88.jpg)

**Comment by sioding** [comment]
fixed with patch from 25.05.2019
