### ISSUE TITLE
[Quest] Crypts and Tunnels  (can not repeated)

### ISSUE THREAD

**Issue by kam19080** [WarEmu/WarBugs#14093]
After i finish the quest, i cant get the quest from the quest giver....

Is it bugged?

**Comment by NorKalli** [comment]
quest name?

**Comment by sioding** [comment]
That is the Questbname @NorKalli  - i wouldn't let reports open which are not complete: Crypts & Tunnels

**Comment by kam19080** [comment]
Quest name: [Crypt & Tunnels]

**Comment by Lheana** [comment]
It is repeatable. Nevertheless, as mentioned in the quest, you can only take it every 7 days.

**Comment by sioding** [comment]
answered. Close
