### ISSUE TITLE
Elite Influence Rewards Chaos t12 , Choosen

### ISSUE THREAD

**Issue by Internetbaron** [WarEmu/WarBugs#14095]
Hello,

Elite Influence Rewards for Chosen in Chaos Chapter 12 has one Item with wrong Stats.

Itemname: Falchion of Insanity
Both Hands
Great Sword
Item Level:24

33.3 Dps    <---- one handed weapon dps but its supposed to be a 2 handed weapon.
19 Strength
30 Thoughness

-> One handed weapon Stats , comparable with the other Elite influence reward of one handed weapon but the only 2 hander was way more stats.

You are doin an awesome job guys.

**Comment by wargrimnir** [comment]
Corrected stats, dps, and requirement for 2h skill.

**Comment by sioding** [comment]
fixed with patch from 25.05.2019
