### ISSUE TITLE
Lionheart Tactic in Path of Hunter Tree

### ISSUE THREAD

**Issue by monster1305** [WarEmu/WarBugs#14091]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by monster1305** [comment]
Yesterday I tried picking up the "Lionheart" tactic on my White Lion. The spell "Lion's Fury" still needed the target to be cursed although i picked up the tactic in tactic slot. And it seems like it did not increase the damage at all. My WL is named "Ripguts".

**Comment by sioding** [comment]
Can we please see your testing screenshots?

**Comment by monster1305** [comment]
Today i tried the tactic again and seems to work correctly. I doubt that the addon called "NerfedButtons" was causing the problem. I remember that i did set a condition that prohibits pressing when "the target is not cursed". Thanks anyway, I guess that was my mistake.
