### ISSUE TITLE
DESTRO QUEST "Welcome Back: On the Battlefield"

### ISSUE THREAD

**Issue by Hauclir** [WarEmu/WarBugs#141]
![hauclir_002](https://cloud.githubusercontent.com/assets/7598530/3020418/bc3a811a-df9e-11e3-9bc5-049b33ff63b4.jpg)
NPC Quest Giver: Raven Warmonger
He does not give you the False Reports like he should to place on the Empire Courier
![hauclir_001](https://cloud.githubusercontent.com/assets/7598530/3020450/2ff85794-df9f-11e3-914d-ec23cfcd19e7.jpg)
Empire Courier to be determined if interactable once given the False Reports

**Comment by Damiel126** [comment]
The quest shouldn't be able to work the way it originally did.

It was originally triggered by right clicking the false reports while close to the Empire Courier rather than interacting with the courier itself.

I expect that would be a use_go function for the item...

**Comment by Reggaewaldo** [comment]
Closing since we can't currently fix.
