### ISSUE TITLE
[Quest] [Item] Prove your worth

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#14100]
**Expected behavior and actual behavior:**

In the  quest for destruction chapter 4, the rewards seems to not be tied to an specific class, meaning that you can choose, apparently, all possible rewards that are class-dependant, and they are also empty of armor and stats of any kind.

**Steps to reproduce the problem:**

Checked as Sorceror. Take the quest and complete it, then turn the quest.

**Screenshots/Videos or archive.org evidences:**

![Naggarythe_000](https://user-images.githubusercontent.com/50114048/57845487-03a8bd00-77ca-11e9-8c73-9b6cf3c3c06f.jpg)
![Naggarythe_001](https://user-images.githubusercontent.com/50114048/57845488-03a8bd00-77ca-11e9-8512-21721a0016ae.jpg)
![Naggarythe_002](https://user-images.githubusercontent.com/50114048/57845490-03a8bd00-77ca-11e9-9b33-705ec7e637fd.jpg)
![Naggarythe_003](https://user-images.githubusercontent.com/50114048/57845491-04415380-77ca-11e9-998b-4bae9d172b25.jpg)

**Comment by sioding** [comment]
fixed with patch from 19.05.2019
