### ISSUE TITLE
Flanking tactic applied to subjugator procs

### ISSUE THREAD

**Issue by Farlopa** [WarEmu/WarBugs#14103]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
When u hit the dummy in front as u can see in the first screnshoot the damage of conclusion X is 360 the supossed real damage from the proc but on second screenshoot u can see the damage now is 414 and thats the damage from 360*15/100 = 54(flanking damage bonus)54+360=414the damage of proc with flaking tactic.

**Steps to reproduce the problem:**
Just equip the flanking tactic

**Screenshots/Videos or archive.org evidences:**
No Flanking damage apllied
https://imgur.com/a/oEiQYHy
With flanking damage
https://imgur.com/a/XueuX42

**Comment by grunbag** [comment]
flanking increase all outgoing damage
