### ISSUE TITLE
[Blackguard] Shield and Parry Tactics.

### ISSUE THREAD

**Issue by Folgrimma** [WarEmu/WarBugs#14105]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Expected: Slotting the tactics, Shielded by Hate, and Anger drives Me should increase both parry and block per hatred.

Actual: If tactics are slotted away from each other or are not the first tactics slotted, the one slotted first will take precedence and disallow the other from stacking.

**Steps to reproduce the problem:**
Slotting tactics separately or not slotting them first. 

**Screenshots/Videos or archive.org evidences:**

![Desktop Screenshot 2019 05 17 - 03 19 24 04](https://user-images.githubusercontent.com/40577289/57917993-2206cb00-7853-11e9-910f-d904c910ec8f.png)

![Desktop Screenshot 2019 05 17 - 03 19 28 27](https://user-images.githubusercontent.com/40577289/57918005-28954280-7853-11e9-8397-d82bb81a002e.png)

[Images with tactics slotted together.]---

![Desktop Screenshot 2019 05 17 - 03 24 45 98](https://user-images.githubusercontent.com/40577289/57918145-68f4c080-7853-11e9-9f2b-780e55d5e518.png)

![Desktop Screenshot 2019 05 17 - 03 24 51 06](https://user-images.githubusercontent.com/40577289/57918178-75791900-7853-11e9-92f0-ee3195b75815.png)

**Comment by Folgrimma** [comment]
I also suspect its the same with the disrupt tactic, but i'm not able to test all 3 at the same time.

**Comment by sioding** [comment]
can you please check .getstats output?

**Comment by Folgrimma** [comment]
Hm i'm unable to recreate the issue after relog. I'll assume it was just a visual bug that wasn't displaying it correctly on the character screen and close the issue.
