### ISSUE TITLE
[Quest] Travel-NPC: Rodric Grace

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#14101]
In ref to #6187
I got all three quest from Rodric in Ostland and could complete "Testing the Waters" by simply talking to him again.

**Comment by Lheana** [comment]
This quest has never been said as fixed, only Wolfbane.

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 01.06.2019
