### ISSUE TITLE
Marauder Stances Randomly Disappearing

### ISSUE THREAD

**Issue by gmiles67** [WarEmu/WarBugs#14106]
Marauder stances, particularly Gift of Monstrosity, randomly disappear. The visual status remains (arm is still 'transformed'), but the stance has been removed. It commonly happens when resurrecting, but not always, but it happens almost 100% when leaving a war camp. I res, check the Gift, reapply it if missing and it then disappears when crossing the WC boundary into the RVR zone. Monstrosity is far more liable to drop than Savagery or Brutality. It can also happen randomly at BOs and forts. Today at Lobba Mill in BC, I had to repeatedly reapply Gift of Monstrosity as it applied then disappeared at least 5 times in a row, before the Gift 'stuck'.

Because there is no visual clue - the arm doesn't change appearance - you have to continually monitor the stance bar and look for greyed out abilities to determine if you are in the correct stance or not.

**Comment by sioding** [comment]
Are you level 40?

**Comment by gmiles67** [comment]
I am now, but this has been my experience through levelling.

**Comment by Folgrimma** [comment]
My brother has been experiencing this with SW stances as well. I'll test this on both classes and post pictures.

**Comment by sioding** [comment]
Thanks for the answer - does it happens now - since you are level 40?

**Comment by gmiles67** [comment]
I will test that out later today. Only dinged 40 yesterday.

**Comment by gmiles67** [comment]
Tried it out over the past 2-3 hours at 40 and can confirm that it did not happen, so it seems it's only something that impacts while levelling

**Comment by sioding** [comment]
OK thats (sadly) working as intended - and we have no fix for it rn.
