### ISSUE TITLE
[Quest] Wolfbane, wrong NPC location marked

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#14102]
Got the quest from the NPC Rodric Grace in Ostland and killed the wolves in 
Nordland.
After finishing it the marker for turning the quest in is located inside a PQ in Nordland, while the NPC is actually standing near the "Grey Lady Coaching Inn". (Emp Chap2)
![1](https://user-images.githubusercontent.com/40274248/57845920-520e8980-77d3-11e9-88b0-63dc40d0d23e.jpg)
![2](https://user-images.githubusercontent.com/40274248/57845921-52a72000-77d3-11e9-8eca-34a30d399581.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 01.06.2019
