### ISSUE TITLE
static siege cannons on destro keeps in T4 

### ISSUE THREAD

**Issue by romanki11** [WarEmu/WarBugs#14108]
Currently I have found many different static cannons at destro keeps ( cause I play destro ) not dealing any dmg after the shot is being fired, however I do not understand how this problem occured, may be due to the reason of the wall being in the light of sight, but it was not dealing damage on other occasions as well.  And I dont know if it is the same issue for order cause I only play destro, however I assume they might experience the same problem.

**Comment by sioding** [comment]
You need LoS to your groundtarget to deal damage. That is working as intended.
