### ISSUE TITLE
Not working Order trophy list

### ISSUE THREAD

**Issue by Ryanfawkez** [WarEmu/WarBugs#1410]
Hi, I'm currently going through all the obtainable Order trophies from the T1 Empire quest. So far I've been unable to obtain the following trophies:

- Slayer's 'Dwarven Spade'
- Engineer's 'Portable Gyrocopter'
- Ironbreaker's 'Oath Anvil'
- Runepriest's 'Runesmith, First Order'
- Witch Hunter's 'Holy Relic'
- All class 'Empire Sun Emblem'

I'm not sure why the items won't spawn in your inventory after completing the quest, but it's damn frustrating when you only have a limited amount of tries to get one (only 3 trophy quests exist in the game).

The following list of trophies that you can get from the quest have their appearance missing since they're unable to be attached to any part of your armor:

- Shadow Warrior's 'Marker Badge'
- Swordmaster's 'Lesser Phoenix Order'
- White Lion's 'Dragon Order'
- All class 'Herald'

Seems that all Order trophies are broken just like how the the Destruction trophies are; they don't have a property set to be slotted anywhere on the armor. It gives you that red X in the top left corner, indicating it can't be placed on either the shoulders or the belt.

The following trophies aren't even available from the quest, but they should be added, made obtainable and have their appearance fixed to accommodate the rest of the classes:

- Archmage's 'Traveler's Tome'
- Warrior Priests' 'Holy Codex'
- Bright Wizard's 'Aqshy Candles'

**Comment by Reggaewaldo** [comment]
Thank you very much for the report, this is currently being worked on by one of the team members and will be working soon.

Closing.
