### ISSUE TITLE
Scenario Issues (+Talabec Damn)

### ISSUE THREAD

**Issue by Handzz** [WarEmu/WarBugs#14109]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Queue getting stuck and taking abnormally long time to bring players into scenarios.

Multiple bombs typically required to win scenario in under 10 minutes.

Scenario begins as normal. First bomb blows. Scenario score continues to count to 500 even without second bomb being placed on dam. 15 kills for  + 1 bomb = scenario win for team, less than 5 minutes.

**Steps to reproduce the problem:**

Queue for scenario. Play specifically Talabec Dam

**Screenshots/Videos or archive.org evidences:**

Unable to provide.

**Comment by Kaelang** [comment]
Does not seem to happen in latest versions of RoR.
