### ISSUE TITLE
server restart/patch

### ISSUE THREAD

**Issue by GregoryShv** [WarEmu/WarBugs#14114]
before rebooting the server, if you divide the thing, the initial quantitywill return after the server is started.

action on the example of an officer medallion:
we have [1000] pieces, perform stack split [1] and [999], after starting the server we get 2 stack - initial [1000] and [999] which we stack split.

**Comment by Kaelang** [comment]
Appreciate this is an older report - however the lack of information here makes this almost impossible to replicate without having to guess what this report is for. Please re-open with more information if this issue persists.

Closing.
