### ISSUE TITLE
Gates of ekrund bug , was able to fall through building and be in the walls like i was wall hacking

### ISSUE THREAD

**Issue by Yikesz** [WarEmu/WarBugs#14110]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

went to stand on the middle bo , a black orc was basically on top of me and then one of orders ranged dps classes with a displacement made me go up but where the block orc was on top of me i stalled hitting him and it pushed me through the floor down into the building.

**Steps to reproduce the problem:**

I have no idea how to prevent this , maybe a coding fix?

**Screenshots/Videos or archive.org evidences:**

https://gyazo.com/548eb1abc2e313d8185ed1e117eb6411

**Comment by sioding** [comment]
where is the place (i mean exactly) you fall through the texture?

**Comment by Yikesz** [comment]
almost directly in the middle of the BO that is the center BO. Maybe a little to the left of it.

**Comment by Yikesz** [comment]
Possibly can be done on both sides of the center bo with a bigger character or even character on top of you , not sure as this would take someone on the other realm to try and recreate this purposely.

**Comment by Yikesz** [comment]
> where is the place (i mean exactly) you fall through the texture?

I'd have to get in a gates of ekrund scenario again and take a screenshot gimme some time idk how long itll take

**Comment by sioding** [comment]
Sorry but without a screen or something we can't help here. Close
