### ISSUE TITLE
Problem with ingame chat (Cyrillic fonts)

### ISSUE THREAD

**Issue by Kushido** [WarEmu/WarBugs#1411]
Having some problems with russian letters in chat.
My mate downloaded game client from website, installed it and he can see if someone/he writing something in chat on russian.
I redownloaded and reinstalled game client and still have problem. If someone writing something on russian i see only free spaces in chat, but can see "," "?" etc.
But i can type on russian and other ppl can read it. Might it be a problem with missing some of the fonts in windows directory or something?
![kushidobw_000](https://cloud.githubusercontent.com/assets/14280617/9885058/e3371222-5beb-11e5-841f-6cc88fb23002.jpg)

**Comment by Silentguard** [comment]
You need to select chat font with cyrillic support. Myriad pro works for me.

**Comment by Kushido** [comment]
Yep, changing font in chat settings works fine. Age of Reckoning font not support russian cyrillic i guess. Cronos pro too not working well with cyrillic. Only Myriad.
