### ISSUE TITLE
Fury of Da Green

### ISSUE THREAD

**Issue by cfabr** [WarEmu/WarBugs#14119]
![Hudiz_000](https://user-images.githubusercontent.com/50782391/57975172-a593f980-79c4-11e9-95ad-02b1e0dd36f9.jpg)

Hello,
So i have been testing out the shaman lifetap tree, especially fury of da green, and as you see the tooltip doesn't quite fit the actual output. Instead of a 5 sec CD, it has a 7 sec CD (ability is lowest row, second on the left). And instead of doing the 1556 heal + 50% of the total inflicted damage (should be 1848 heal output) it only does a 1392 heal output ... Well thats pretty much it for now >.<

**Comment by grunbag** [comment]
fixed already
