### ISSUE TITLE
[BO] Ya Missed Me

### ISSUE THREAD

**Issue by Killham** [WarEmu/WarBugs#14116]
![0ya missed me](https://user-images.githubusercontent.com/18173840/57973742-58109000-79b6-11e9-9a6f-0e0bd29c23a8.jpg)
Description in tooltip on enemy bugged and after cheking on mobs this ability doesn't reduce physical damage at all.
![2ya missed me](https://user-images.githubusercontent.com/18173840/57973829-71660c00-79b7-11e9-807d-be6ce32874b6.jpg)
![3ya missed me](https://user-images.githubusercontent.com/18173840/57973830-71fea280-79b7-11e9-9a7e-cd25323b215b.jpg)

**Comment by grunbag** [comment]
it works, but you are testing on mob AA. auto attack doesn't damage type, and ya missed me works only on physical damage
