### ISSUE TITLE
[item] Solution

### ISSUE THREAD

**Issue by jed3213** [WarEmu/WarBugs#14113]
Engineering hammer from epic quest t4 (Solution) cant have appearance another hammer and cannot be applied to other hammers.
![hammer](https://user-images.githubusercontent.com/50764683/57966139-ff5dda80-7956-11e9-8441-78d79b4fb45c.png)

**Comment by Ootootoo** [comment]
There are two kinds of weapons for Engis slots: One-handed and Two-handed. In example you have in the ranged slot Guns, which are 1h, and Rifles, which are 2h. Happens the same with spanner-hammers. You can't alternate apperance from one type to the other. Have you checked that both are of the same type?

**Comment by jed3213** [comment]
I think you're wrong, 2h and 1h is just a visual (on engis). All the spanner have a hammer type, with all other weapons everything is fine except for this. He is the only one who has the type of main hand (I checked the vendors)

**Comment by wargrimnir** [comment]
Set to main hand only.

**Comment by sioding** [comment]
fixed with patch from 25.05.2019
