### ISSUE TITLE
[BO] Savin' Me Hide.

### ISSUE THREAD

**Issue by Killham** [WarEmu/WarBugs#14115]
![1savin me hide](https://user-images.githubusercontent.com/18173840/57973691-978aac80-79b5-11e9-994b-38e9d5f6a707.jpg)
This parametr should apply to the black orc himself too.
![0savin me hide](https://user-images.githubusercontent.com/18173840/57973715-f0f2db80-79b5-11e9-8c7b-763f7db45d2f.jpg)
Right now it doesn't.

**Comment by sioding** [comment]
Duplicate of #8044
