### ISSUE TITLE
oppressor emblems can be exchanged for medalions.

### ISSUE THREAD

**Issue by silodin** [WarEmu/WarBugs#14124]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
opp Emblems ->  conq Emblems
opp Emblems -> conq medalions

**Steps to reproduce the problem:**
Buy a box of 5 conq medalions for 1 oppressor emblem

**Screenshots/Videos or archive.org evidences:**
https://imgur.com/a/frbvFZV

**Comment by sioding** [comment]
fixed with hotfix
