### ISSUE TITLE
Help - exchange opressor emblems to conqueror emblems (Fail)

### ISSUE THREAD

**Issue by vitordl1** [WarEmu/WarBugs#14128]
Spent 55 Opressor Emblems believing that I would receive Conqueror Emblems as it says on patch but received 275 Conqueror Medallions instead!  :(

"Oppressor Emblems may now be exchanged for Conqueror Emblems at their appropriate vendors at a 1:5 exchange rate."

can I have my Opressors back and purge the Conqueror Meds? 

Insightnow - Archmage

**Comment by sioding** [comment]
The problem is fixed - and no you don't get any currency back
