### ISSUE TITLE
Target Dummy not affected by "Napalm Grenade"

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#14121]
The dummies aren't taking any damage from _Napalm Grenade_ eventhough the "debuff" is showing up on them 

![t-dummy_napalm](https://user-images.githubusercontent.com/40274248/57979946-6ac1ae00-7a24-11e9-81ec-c82ab2bf28cf.jpg)

**Comment by grunbag** [comment]
Target dummies are not character (player or npc) they are game object
