### ISSUE TITLE
File signature bad: data/bin/abilitycomponentexport.bin

### ISSUE THREAD

**Issue by carramar84** [WarEmu/WarBugs#14129]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

Run the program, and crash.

File signature bad: data/bin/abilitycomponentexport.bin

**Screenshots/Videos or archive.org evidences:**
![image](https://user-images.githubusercontent.com/50808909/57987739-18b17480-7a86-11e9-963c-17c053c4d9d1.png)

**Comment by sioding** [comment]
Just delete it and patch again please
