### ISSUE TITLE
[Tactic] "Extra Powder" doesn't increase radius of "Fragmentation Grenade"

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#14120]
Did some testings on my Engie and discovered that this tactic apears to be broken (again? #8265)

I attacked the marked dummy on the left with _Frag-Grenade_ and _Acid Bomb._ As you can see _Frag-Grenade_ got apllied to three dummies, (same as whithout tactict) while acid bomb hits one more target.

Both skills share the same base radius and therefor should be affected in the similar way by the tactic.
![frag acid1](https://user-images.githubusercontent.com/40274248/57979865-6fd22d80-7a23-11e9-83fe-01d9705d8dde.jpg)

**Comment by grunbag** [comment]
Fixed for next patch

**Comment by sioding** [comment]
fixed with patch from 25.05.2019
