### ISSUE TITLE
[QUEST] Beyond the griffon gate

### ISSUE THREAD

**Issue by QualQuekl** [WarEmu/WarBugs#14137]
It's not possible ton continue this quest after killing Alleria Brightcaller, the quest asks to read incantation but nothing happens when you do it in your inventory at quest item.
The quest can't be completed.
![2019-05-20_140924](https://user-images.githubusercontent.com/50831495/58020666-15ab9800-7b09-11e9-9a3d-716a4ad9b175.png)

**Comment by Lheana** [comment]
You must use the Incantation targeting the vault to open it.

**Comment by MidiDEVS** [comment]
This Quest is still bugged.

In my Screenshots you can see me targeting the "Vault" ('Ellyrian Rolls' Chest).
The Result with interacting with the Chest is that i get multiple Items, wich first do not count. After beeing in proximity to the Chest you get additional Items but the Quest is still visible in the Map and countet as unsolved.

![Lyzshiry_002](https://user-images.githubusercontent.com/13495078/59270310-6ff3d080-8c51-11e9-8165-3784ca991233.jpg)
![Lyzshiry_000](https://user-images.githubusercontent.com/13495078/59269987-a9780c00-8c50-11e9-8356-402783532724.jpg)
![Lyzshiry_001](https://user-images.githubusercontent.com/13495078/59269988-a9780c00-8c50-11e9-96df-0a72195084f6.jpg)

**Comment by Lheana** [comment]
This quest works if you complete it in the right order. You must first loot the Incantation, then read it targeting the vault, to loot the Ellyrian Rolls.
Just for information, you have done the quest, so you are able to turn it in.
