### ISSUE TITLE
The Maw Fort Renown XP Bug <30k regardless of win/loss

### ISSUE THREAD

**Issue by keunglh** [WarEmu/WarBugs#14139]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Forts regardless of win/loss should award a 30k renown tick. At least on my UI you are awarded a smaller renown reward between 3-6k, and then the static 30k renown. However, in two recent experiences at The Maw (Destro Fort in Empire/Chaos), when the lord was taken down within 10 minutes of stage 3, it appears that the 30k renown tick was bugged and was not awarded fully. First set of screenshots were from 5/16/2019,  first as at Maw, the second at Fell Landing where the full 30k renown reward was given. Both lords were defeated relatively quickly within the first push. 

![3 3k renown fort tick](https://user-images.githubusercontent.com/14348489/58026711-b0da4880-7adc-11e9-829b-0d9c7361d100.PNG)
![full renown fort tick](https://user-images.githubusercontent.com/14348489/58026712-b0da4880-7adc-11e9-9618-66f9d4d640ca.PNG)

This follow screenshot was from 5/18/2019, during the double exp weekend, again at the Maw, where the lord was defeated within the first 10 minutes of stage 3. I don't have the exact time, but order was able to successful clear and wipe during the 1st organized push. I asked some destro streamers during the same day, and I believe that destro also did not receive the full 30k renown tick either. 

![5 8k renown fort tick](https://user-images.githubusercontent.com/14348489/58026811-ef700300-7adc-11e9-8a21-8e7a15ec9de1.PNG)

**Steps to reproduce the problem:**
Seems to be mainly a Maw issue when the lord is taken down too quickly? I'm not sure if it is an intended anti-zerging mechanism, but it happened in two situations.

**Screenshots/Videos or archive.org evidences:**
Screenshots attached above.

**Comment by keunglh** [comment]
![image](https://user-images.githubusercontent.com/14348489/58067699-e79f7580-7b53-11e9-8eab-10b349fec790.png)

Just a Stonewatch defense from today, 5/20/2019. 

I do not believe there was ever any mention of an antizerging/malus mechanic that also applied in forts? Maybe there is, but I guess clarification would be appreciated whether or not this is intended or not. 

Thank you

**Comment by keunglh** [comment]
![image](https://user-images.githubusercontent.com/14348489/59733053-2fc4bd00-9212-11e9-9989-3522780c945e.png)

June 18th, 2019. Evening Fell Landing Fort. Took a few attempts, only got 168 renown.

**Comment by Natherul** [comment]
fortresses dont award 30k baseline. Its based on number of kills in the area which is capped at 30k.
