### ISSUE TITLE
Ard ta Feed Contribution Bug

### ISSUE THREAD

**Issue by Esperflame** [WarEmu/WarBugs#14133]
Ard ta Feed has a bug that he punts you out of his contribution zone. I was there, I fought the boss, I helped kill the boss. But because he punted me super far away from him and died right after I landed, I was robbed of my red eye chest piece for the second time meaning I have to wait yet again another 3 days for something I earned last week.

**Expected behavior and actual behavior:**
I expected to get my kill contribution but instead was given nothing.

**Steps to reproduce the problem:**
Ard ta Feeds contribution range is smaller than his punt range. To reproduce get punted by hard to feed across the map and if he dies you don't get contribution.

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment]
Duplicate of #13563
