### ISSUE TITLE
No invader icon for 6 piece ability called Precision.  Does not appear on target dummy.  Cannot tell if it actually works.

### ISSUE THREAD

**Issue by Neutrinoo** [WarEmu/WarBugs#14132]
Load 6 piece Invader on a magus.

Go to the target dummy.   I'm not sure if dummys have any disrupt at all so maybe this is the problem.
Note that you can crit all you want but you do not see a "precision" proc indicator. 

Expected behavior is that you'd get a visual queue when target is debuffed with 20% disrupt strike through.

**Comment by grunbag** [comment]
Tested it works fine

**Comment by grunbag** [comment]
![precision](https://user-images.githubusercontent.com/24207191/58365086-87943080-7ebf-11e9-8ad3-87f7472f115a.png)

**Comment by Neutrinoo** [comment]
I tested it a again.   I actually saw it work!  BUT GUESS WHAT - I was not wearing full Invader when it proc'd.     Better yet when i put full invader on it wouldn't proc again.  So something still broke or the % chance sucks.

**Comment by Neutrinoo** [comment]
![image](https://user-images.githubusercontent.com/18320036/58397190-e40d6200-801d-11e9-9ff6-0d24701ac41f.png)


I'm telling you something is fucked up with the ability.   I see it once then I have to reset my armor again to see it again.  Some times I see it appear and quickly disappear then I see crap like this.  Something looks tripped up with the timer or buff display.

**Comment by Neutrinoo** [comment]
![image](https://user-images.githubusercontent.com/18320036/58397257-2636a380-801e-11e9-802e-401f59a42b63.png)

The armor set comment doesn't say anything about 60sec timer

**Comment by Neutrinoo** [comment]
Does a pet ability count as the next ability cast?

**Comment by grunbag** [comment]
There is a 60s timer so your have 60s to cast your next abilities that will have +20% chance
