### ISSUE TITLE
[Quest] The Blighted Isle - "Lessons Learned"

### ISSUE THREAD

**Issue by axisd** [WarEmu/WarBugs#14134]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Hi,
active quest is not marked on the map
Thnx

**Screenshots/Videos or archive.org evidences:**
![Sarhel_003](https://user-images.githubusercontent.com/2901788/58007396-e0944b00-7af2-11e9-99e0-212ec388c59e.jpg)

**Comment by axisd** [comment]
mb map mark hide after complete part of quest...

**Comment by sioding** [comment]
fixed with patch from 22.6.2019
