### ISSUE TITLE
[Sorceress] Pit of Shades

### ISSUE THREAD

**Issue by Skoupie** [WarEmu/WarBugs#1413]
You can cast it normally, but sometimes it doesnt get interrupted when you move. You can even be completely out of range but it keeps dealing damage.

**Comment by Thorgatin** [comment]
Same with "Rain of Fire". If you move and actually disrupt the channeling gtaoe, the enemies still get damaged for the full duration, even if they moved out of the former gtaoe field.

**Comment by ozarmidrashim** [comment]
Can you reproduce this reliably?

**Comment by Thorgatin** [comment]
Yes, almost 100% (depends a little on, when you start to move to break the channeling as it seems).

I tested this only on pve enemies though.

**Comment by Skoupie** [comment]
Just tested it on pve, the channeling doesnt break when you move. On pvp though sometimes it breaks  and some others it doesnt. (Apologies, cannot run fraps on my laptop).
