### ISSUE TITLE
Dye

### ISSUE THREAD

**Issue by Sindarella** [WarEmu/WarBugs#14135]
I Just got my Annihilator Gear for my DOK, and was trying to dye my body armor, The torso part is the only part that will dye. The dress itself stays purple. This is the first time I've had this issue. I tried using dyes in my inventory, and at a merchant. It just won't change.

Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment]
Well - tried to reproduce it - but i can dye it. You need to add more informations about this.

**Comment by Sindarella** [comment]
Ok i have one, of the armor before, with a 1 st area and a 2nd area, and
one with both areas, and my dress is still purple..

**Comment by Kaelang** [comment]
Image wasn't uploaded to back this claim. Tested and had no issues, similar to Sioding. Please re-open if you're still having this issue.
