### ISSUE TITLE
All quest lost map mark after partyaly complete

### ISSUE THREAD

**Issue by axisd** [WarEmu/WarBugs#14136]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
I apologize in advance for my terrible English
subj.
maybe I'm a loser, but all the quests that I take disappear from the map as soon as I partially perform them.

**Steps to reproduce the problem:**
take any quest from 2+ parts (for example kill 5 harpies and 6 spiders). kill spiders - quest disappears from the map

**Comment by Lheana** [comment]
Please don't do it. Open a ticket with precise issue: What quest exactly? What the exact issue is? And one issue per report.

**Comment by axisd** [comment]
I do that.
#14134 - https://github.com/WarEmu/WarBugs/issues/14134
#14094 - https://github.com/WarEmu/WarBugs/issues/14094
#13907 - https://github.com/WarEmu/WarBugs/issues/13907 (my last comment but all the quests in this storyline behave as described above)

I think this is a global problem

**Comment by Lheana** [comment]
It's a problem several quests have yes, but that can not be fixed all at once, thus we need one report per issue to fix issues one by one, quest by quest.

**Comment by axisd** [comment]
Ok. Close this.
one report per issue
