### ISSUE TITLE
System is not sending bags for zone lock

### ISSUE THREAD

**Issue by SATANICOMODERNO** [WarEmu/WarBugs#14130]
It's the second time I don't receive a bag for zone lock in my mail. Before server reset for patch fix Avelorn was locked and I got a gold bag, but again I got nothing in my mail. Is there something possible to do or this bug will persist and we will keep losing our bags after zone lock?

Character name: Aliranna - WL

**Comment by sioding** [comment]
Well - sometimes these thinks happen when the server will be restarted. the personal bag bonus prevents you from not getting enough bags.
