### ISSUE TITLE
Lost items

### ISSUE THREAD

**Issue by SATANICOMODERNO** [WarEmu/WarBugs#1414]
Hi. It's the first time i write here. My problem is that I'm losing the items on my inventory. It's the second character that lost a rare weapon. Now happened with my AM called Bondage. I had the Fangbreaker Highstaff and when I changed into Doom-Caller Windstaff to play as dps yesterday, the Fangbreaker was in my inventory. Today, when i logged in the staff have vanished from it.

**Comment by Evildoor** [comment]
Unfortunately, i was informed that dev policy is "No refunds" for now.
