### ISSUE TITLE
Gunbad quests issue

### ISSUE THREAD

**Issue by rhix112** [WarEmu/WarBugs#14159]
My friend - Tiriastrasza has end quest 3 times for helm redeye in Gunbad and he could't pick only helm, he had to choose both rewards. And after it he didn't found helm in backpack, can plz somehow restore this helm, cus 3 more times farm Gunbad will be insane
https://cdn.discordapp.com/attachments/575670641978638352/580816563624738837/Tiriastrasza_010.jpg
https://cdn.discordapp.com/attachments/575670641978638352/580816559338029064/Tiriastrasza_009.jpg

**Comment by Kabucoror** [comment]
Tested it and it works fine for me, also I could not choose 2 items for the helm quest.

note: We don't restore any items. Never.

**Comment by rhix112** [comment]
He couldn't finish quest without take both rewards !

**Comment by Lheana** [comment]
So is it fine now?

**Comment by Lheana** [comment]
No answer for 21 days, I close this.
