### ISSUE TITLE
[Quest] Dat Ard ta Feed's a Threat - Cannot hand-in upon completion.

### ISSUE THREAD

**Issue by HeliodromusROR** [WarEmu/WarBugs#14158]
**Expected behavior and actual behavior:**
The Gunbad Mid boss quest "Dat Ard ta Feed's a Threat":

After getting the 3/3 kill to complete the quest, going back to the NPC and selecting either 1, or both the rewards does not complete the quest. The quest is listed as orange 3/3 for completion, but it cannot actually be handed in, or the rewards obtained.

**Steps to reproduce the problem:**
Kill 'Ard ta Feed 3 times for 3 kill completions, go hand in the quest.

**Screenshots/Videos or archive.org evidences:**
https://www.youtube.com/watch?v=y0DafAqR5kE&feature=youtu.be

**Comment by Lheana** [comment]
I would suggest you to try after a server restart cause I tested on my own, and it works fine.

**Comment by HeliodromusROR** [comment]
What if the issue persists?

**Comment by Lheana** [comment]
Only thing I see would be to abandon the quest and retake it.

**Comment by sioding** [comment]
No answer for 12 days. close
