### ISSUE TITLE
Shaman - Apostle's blasta of anathema - can't be equipped

### ISSUE THREAD

**Issue by BuzzShaman** [WarEmu/WarBugs#14152]
This weapon is now correctly listed as a staff, instead of as a 1 handed sword like it was upon release - but it still cant be equipped.
![Buzzbuzz_026](https://user-images.githubusercontent.com/50312373/58140271-90111080-7c0c-11e9-80be-c137af6fc686.jpg)

**Comment by wargrimnir** [comment]
This was flagged incorrectly as Convertable, not sure what that means. Probably fixed it.

**Comment by sioding** [comment]
fixed with patch from 25.05.2019
