### ISSUE TITLE
Quest: Redemption High Pass

### ISSUE THREAD

**Issue by tester352** [WarEmu/WarBugs#14153]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Turn in quest Redemption from High Pass to Scholar Anselma in Altdorf, to get next part of the quest Redemption. Talk to Scholar Anselma again to continue the quest line.

After Talking to Scholar Anselma to continue the quest line, you click accept on her quest and then it nothing happens and the quest dissapears.
**Steps to reproduce the problem:**
After taking the quest Redemption somewhere around Empire Ch.11 and following the quest line until it takes you to Altdorf to speak with Scholar Anselma, it becomes broken and disappears after accepting the next part of the quest line from her.

**Screenshots/Videos or archive.org evidences:**
![Matttheus_001](https://user-images.githubusercontent.com/14897323/58138390-e3329580-7c03-11e9-9ac5-0a00576cc787.jpg)

**Comment by tester352** [comment]
Just an update. After reaching level 40 I was able to speak with her again and continue the quest Redemption back into high pass. I will be going to speak to Corporal Armsten in EMP. CH.10 and see if the rest of the quest can be completed as normal. Not sure if it's intended to only be able to continue along this quest after lv 40.

**Comment by tester352** [comment]
Update #2 The rest of the quest line was able to completed as normal.

**Comment by Lheana** [comment]
Yep I already knew the issue was that the level requirement was set to 40 for this step. Thus I already fixed it, will be pushed on live with next patch.

**Comment by sioding** [comment]
fixed with patch from 25.05.2019
