### ISSUE TITLE
Two zones in one pairing 

### ISSUE THREAD

**Issue by sioding** [WarEmu/WarBugs#14151]
Sometimes two zones are open in one pairing:
![image](https://user-images.githubusercontent.com/18517842/58126124-7e326c00-7c12-11e9-811a-4ffd18197638.png)

That leads into a couple of problems - if the t2 zones will be captured while a fight in the t3 zone  run - it will reset the t3 zone. We need to make sure that only one zone is open in a pairing.

**Comment by wargrimnir** [comment]
Additional thoughts

This may be related to when zone population changes the threshold of available zones. I noted shortly after this last incident the population in T4 was slightly over 600. If there's a different section of code that chooses pairings for this variable it should match the same logic as a pairing lock or zone capture.

**Comment by Natherul** [comment]
this should no longer be an issue with the new campaign in effect.
