### ISSUE TITLE
dye name duplicate

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#14157]
light purple dye
medium purple dye
each of them have 2 different color.
it's 4 colors.
they don't stack but have same name.

**Comment by Rubyeclipse-war** [comment]
Hi @anarchypark - this is a very late reply, but thank you for letting us know on this bug! 

As part of the recent Dye overhaul and name fixes, this bug should now be fixed. You should see an (O) for Order or (D) for Destruction in these dye names. If any other dye issues pop up, just let us know.
