### ISSUE TITLE
doors not working in ostland

### ISSUE THREAD

**Issue by Natherul** [WarEmu/WarBugs#1415]
I have found 2 doors that does not work now in Ostland making some quests impossible, the ones I have found so far is: the tower at the bells of war PQ and the gates at ferlagen cemetary

**Comment by Reggaewaldo** [comment]
Confirmed.

Cords (X, Y):
Bell tower - 9585, 36161
Ferlagen cementary - 9539, 24438

Can also be added that the crypt at Ostland is also affected 61749,60701.

**Comment by CaptainoftheHarem** [comment]
I can also confirm the aforementioned doors not working, as well as the following doors:
Coordinates (x,y)
Cemetery north of Ferlangen 9395, 24000
Cemetery north of Ferlangen 9325, 22180
Gate near Gerstmann Crypt 30074, 16865
Gerstmann Crypt 30729, 18612

**Comment by Meralors** [comment]
Fixed Bell tower door, still working on cemetary ones

**Comment by Meralors** [comment]
Every doors should be working in Ostland now.
