### ISSUE TITLE
[Quest] dungeon boss kill reward choose 2

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#14156]
some quest are rewarding both gear and dye. other's rewarding only one.
2 rewards choice
gunbad -
the threat from 'ard ta feed
the threat from solithax
the threat from glomp
and same version of destro.
warpblade tunnel -
the threat from grey seer quol'tik

rest are choose only 1.

**Comment by Kabucoror** [comment]
original choice count (1) will be restored on next patch

**Comment by sioding** [comment]
fixed with patch from 25.05.2019

**Comment by anarchypark** [comment]
just noticed destro version is bugged.
![quest2](https://user-images.githubusercontent.com/19988772/60403053-1b4dd080-9bd3-11e9-9acf-14d245f022cb.jpg)
