### ISSUE TITLE
PQ: Shrine of Tzeentch, High Pass

### ISSUE THREAD

**Issue by tester352** [WarEmu/WarBugs#14155]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Have to click shard of change 16/16 times to complete part 2 of the PQ

Can repeatedly click shard of change to complete part of the PQ when you should only be able to click each shard of change once.

**Steps to reproduce the problem:**
Repeatedly click shard of change to complete step 2 of the PQ

**Screenshots/Videos or archive.org evidences:**
![Matttheus_004](https://user-images.githubusercontent.com/14897323/58142221-3b719380-7c14-11e9-8068-b27fa43906ee.jpg)

**Comment by Kabucoror** [comment]
Some chars have this wierd bug. There is nothing we can do about it.
