### ISSUE TITLE
Subjugator's Greatcloak (Dark Elf variant) - Cleanse usable whilst in bags & unequipped.

### ISSUE THREAD

**Issue by HeliodromusROR** [WarEmu/WarBugs#14150]
**Expected behavior and actual behavior:**
The cleansing ability of this item should (?) be usable only when equipped.
Instead, the cleanse ability of this item can be used whilst unequipped, essentially acting as an unlimited cleansing potion (... that removes 1 effect on a 30' timer).

**Steps to reproduce the problem:**
Equip the cloak into the armour slot, drag it onto the action bar, then remove the item in the armour slot with another cloak. Press the cleansing ability of the item on the action bar.

*Note*: In the video, disregard the cooldown number on the Cloak item, I had reset it by flying from a zone.
**Screenshots/Videos or archive.org evidences:**
https://www.youtube.com/watch?v=lkKv67dTABA&feature=youtu.be

**Comment by Tazo83** [comment]
been like that for a long time as an item in ur inventory can be used with no equip just like how pots works

**Comment by sioding** [comment]
Sorry - working as intended
