### ISSUE TITLE
Kadrin Valley Keep

### ISSUE THREAD

**Issue by tester352** [WarEmu/WarBugs#14166]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Staircase should be placed so as to be able to walk up it.

Staircase is clipped into building and unusable in terms of being able to climb up it. I watched many players try to walk up it and then proceed to jump to get over it.
**Steps to reproduce the problem:**
Go to Kazad Dammaz keep in Kadrin Valley and go to this point on the outer wall and attempt to walk up it.

**Screenshots/Videos or archive.org evidences:**
![Matttheus_011](https://user-images.githubusercontent.com/14897323/58317342-960d1a00-7de3-11e9-8532-1b244f55cfa0.jpg)

**Comment by sioding** [comment]
something we have since retail - but good that someone made a report for it. thanks

**Comment by tester352** [comment]
Ya hahaha, I wonder if it's fixable.

**Comment by Lheana** [comment]
I confirm it's fixable, and will be fixed with next patch.

**Comment by Lheana** [comment]
This was fixed with the patch of 26/08/2020.
