### ISSUE TITLE
New character with no weapon and can't logout

### ISSUE THREAD

**Issue by Kushido** [WarEmu/WarBugs#1416]
Created new character (Slayer). Login into game, after first time hitting "play" button game switched on loading screen and after some moments switched back to character selection screen. Second time i pressed "play" it lets me in game. But my character have nothing in backpack (even no book) and no weapon. Aslo no basic mount.
And the second problem - i can't logout cos system saying that i'm dead.
![kurshaa_002](https://cloud.githubusercontent.com/assets/14280617/9916057/3a045826-5cc3-11e5-8cc2-719a0fb4ac46.jpg)

**Comment by Kushido** [comment]
Killed game process with task manager. Relauched the game. On selection screen character now have weapon. Login into game - have weapon, book and mount.
![kurshaa_003](https://cloud.githubusercontent.com/assets/14280617/9916193/e60ff846-5cc3-11e5-8463-e066f3ab4fe5.jpg)

**Comment by Kushido** [comment]
Same problem if creating Engineer.

**Comment by Evildoor** [comment]
I confirm. Created engi - same problem. The chat on first loading says NullReferenceException was thrown from Load. Cinematic and tutorial only play on third loading into game (after killing the process).
Created chosen - same problem.

**Comment by Kushido** [comment]
this problem you have on every (mb no all but on most classes) new character you've created, cos yesterday i saw minimum few msgs in chat about problem with "you are dead" and you have no armor/weap and can't logout

**Comment by nalgol** [comment]
was a problem with null pointer from renown spec
