### ISSUE TITLE
[Spell] Sorcerers Chilling Gusts dmg is less than the tooltip

### ISSUE THREAD

**Issue by bealmador** [WarEmu/WarBugs#14164]
**Expected behavior and actual behavior:**
Chilling Gusts dmg is only about half of what the tooltip says.
has been reported here https://github.com/WarEmu/WarBugs/issues/4351 and solved before but I guess it's back.

**Steps to reproduce the problem:**
using Chilling Gusts talent and applying Chillwind to a target.

**Comment by sioding** [comment]
Can you please add your testing screenshots?

**Comment by bealmador** [comment]
Screenshot:
![chiling gusts](https://user-images.githubusercontent.com/39677933/58294993-2ab84d80-7dcd-11e9-832f-b296a1b8c5ce.PNG)

**Comment by grunbag** [comment]
fixed for next patch

**Comment by sioding** [comment]
fixed with patch from 25.05.2019

**Comment by grunbag** [comment]
It deal the right damage (+20 is nothing) and proc never crit
