### ISSUE TITLE
[SH] Shrapnel Arrer animation delay acts as cast time

### ISSUE THREAD

**Issue by zulnam** [WarEmu/WarBugs#14165]
**Expected behavior and actual behavior:**
Shrapnel Arrer is an instant cast. However, due to the animation delay the ability takes over 1 second to actually fire. This was reported previously as [fixed](https://github.com/WarEmu/WarBugs/issues/10290), but it is still present.

**Steps to reproduce the problem:**
1. Invest 6 points in Path of Big Shooting, up to Shrapnel Arrer.
2. Activate ability on any enemy target.

**Comment by grunbag** [comment]
yes animation last 1 sec, but you can't cast anything during this time du to GCD, and you can't be interupted so it's not an issue at all

**Comment by sioding** [comment]
Answer given - close
