### ISSUE TITLE
Witch Elves Heart Seeker and kiss of Agony

### ISSUE THREAD

**Issue by zoso85** [WarEmu/WarBugs#14161]
![Trammpled_002](https://user-images.githubusercontent.com/50939158/58226652-edbb6f00-7d6a-11e9-8ee4-9bec66c5dfe5.jpg)
I think Kiss of Agony is broken
I was in a scenario where i was disabled by Witch elf's Heart seeker (HS)  as soon as i came out of it  i took 2 steps and was disabled again not by Heart Seeker but Kiss of Agony (KoA),  according to the carreer builder KoA is not meant to disable, unless changes were made that i could not find.
But you can see from the included screen capture.

**Comment by grunbag** [comment]
i can't reproduce
