### ISSUE TITLE
[Quest] The Devil Inside

### ISSUE THREAD

**Issue by Aluviya** [WarEmu/WarBugs#14168]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
According to the quest description you use the Sigmarite Pendant on the Crazy Peasant (works) - But then nothing happens, you only the the credit for the step. There is no Deamon to cleanse. Killing the NPC doesn't help either (also i believe this NPC should not be attackable until the pendant is used).
**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

![Aluvya_006](https://user-images.githubusercontent.com/17249318/58340672-aa393180-7e4c-11e9-965e-693255318ef1.jpg)
![Aluvya_005](https://user-images.githubusercontent.com/17249318/58340754-d9e83980-7e4c-11e9-9893-d3da557beb23.jpg)

**Comment by Lheana** [comment]
The quest works fine. You simply have to use the Pendant on the NPC **before** killing it.
For the script part: #10555

**Comment by Aluviya** [comment]
I used the Pendant before killing her, abandoned and tried the quest again - by using the pendant only the first quest step counts.

**Comment by Aluviya** [comment]
Tried actually a third time (abandon - take the quest again).... this quest is definately not working.

**Comment by Kabucoror** [comment]
Did it right now without a issue.
![Kabuco_042](https://user-images.githubusercontent.com/45296624/58350615-ae724880-7e66-11e9-9c54-200f5e138986.jpg)

**Comment by Lheana** [comment]
@Aluviya Must be related to being grouped issue. Try to kill the NPC without being grouped.

**Comment by Aluviya** [comment]
Indeed.... sorry to bother you is related to  #12470
