### ISSUE TITLE
[Quest] Dogs of War

### ISSUE THREAD

**Issue by Aluviya** [WarEmu/WarBugs#14169]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
I would like to reactive this topic:
https://github.com/WarEmu/WarBugs/issues/11447
The Guard is still nowhere to be found. 

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by Lheana** [comment]
Sioding reopened the ticket, so this one is not needed.
