### ISSUE TITLE
Public Quest Bug

### ISSUE THREAD

**Issue by ghostlydemonfox** [WarEmu/WarBugs#14167]
PQ Chaos ruins (hard) in high pass stage 1, where one of the power stones didnt count and is stuck at 24/25 makeing it impossiable to finsih stage 1

**Comment by Lheana** [comment]
Well there are 25 Power Stones, so without knowing what prevented one to count, we can not do anything.

**Comment by ghostlydemonfox** [comment]
i had the same error whit anorther PQ where mobs didnt count got fixed just by restarting the server

**Comment by Lheana** [comment]
It's quite sure you will be able to go further in the PQ with next restart.
But as I said, without knowing how the kill does not count, we can not fix it.

**Comment by tester352** [comment]
I was able to do the PQ today. Sometimes the pq just bugs out for a day or so. Try again ghostlydemon and see if you can finish it.
