### ISSUE TITLE
[Spell] Sorcerer Chillwind and Ice Spikes doesn't crit

### ISSUE THREAD

**Issue by bealmador** [WarEmu/WarBugs#14163]
**Expected behavior and actual behavior:**
Chillwind and Ice Spike should be able to crit, especially since they are affected by the backlash mechanic. However, both spells don't seem to crit. ever.

**Steps to reproduce the problem:**
Hitting anything with Chillwind or Ice Spike

**Comment by sioding** [comment]
Can you please add your testing screenshots?

**Comment by bealmador** [comment]
Not really sure how I would prove this with a screenshot but here are two of a) my combat log with Chillwinds on a target dummy, no crits. And b) my character crit stats. Combined with 35% crit chance from Dark Magic that leaves me with 57% crit chance and yet there isn't a single one.
![nocrit](https://user-images.githubusercontent.com/39677933/58294627-7b2eab80-7dcb-11e9-93ab-e7ee92a5a01f.PNG)
![nocrit2](https://user-images.githubusercontent.com/39677933/58294629-7ec23280-7dcb-11e9-963e-228e0e30ae8f.PNG)

**Comment by TheOGScav** [comment]
Confirmation video: https://youtu.be/sm082N7kJOg

**Comment by grunbag** [comment]
fixed for next patch

**Comment by sioding** [comment]
fixed with patch from 25.05.2019
