### ISSUE TITLE
Quest: Home Invasion, Altdorf

### ISSUE THREAD

**Issue by tester352** [WarEmu/WarBugs#14162]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

I understand this issue has been posted before a year ago. But this issue is current.

**Expected behavior and actual behavior:**
The ruffians inside of Paul Burkhardt's home are to be killed for the completion of this quest.

The ruffians are untargetable and only killable through means of AoE
**Steps to reproduce the problem:**
Start the quest Home Invasion in Altdorf, precede into the home and attempt to target the Ruffians through tab targeting or clicking does not work.

**Screenshots/Videos or archive.org evidences:**
![Matttheus_012](https://user-images.githubusercontent.com/14897323/58262050-7a543600-7d47-11e9-963b-5d3b7091a915.jpg)

**Comment by sioding** [comment]
fixed with patch from 25.05.2019
