### ISSUE TITLE
Quest bug

### ISSUE THREAD

**Issue by fixfax86** [WarEmu/WarBugs#14174]
The Quests "One too Many" in Avalorn is bugged.. Manus Seren doesnt count when you kill him at Wood Choppas Camp. And "Baby Gustav" in Sewers dos not count either.. can I get a Griffon mount for that?

**Comment by sioding** [comment]
Have you been in group while killing the NPC´s ? If yes - try it solo again. And sorry no griffon for this.

**Comment by Lheana** [comment]
And please, **one issue per report**.

**Comment by Lheana** [comment]
You have to loot the NPC to save Baby Gustav.

**Comment by fixfax86** [comment]
okay thanks.. what kind of Bugs rewards Griffon mount?

Den lør. 25. maj 2019 kl. 13.09 skrev Lheana <notifications@github.com>:

**Comment by sioding** [comment]
These mounts are given only for serious issues, which are not obvious, and which significantly threaten either the security and stability of the server or its economy.

**Comment by sioding** [comment]
answer given - close
