### ISSUE TITLE
[Quest] The Pale Eye

### ISSUE THREAD

**Issue by Aluviya** [WarEmu/WarBugs#14170]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Killing the Pale Eye Burglar's do not contribute to the quest anymore.
![Aluvya_008](https://user-images.githubusercontent.com/17249318/58347963-83382b00-7e5f-11e9-9292-fed45b1b83b4.jpg)

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by Lheana** [comment]
Quite sure it must be related to #12470. If you can, try when not being grouped.

**Comment by Aluviya** [comment]
Yes indeed, was related to  #12470, sorry to bother you.

**Comment by Lheana** [comment]
No worries.
Note that this is a general issue we don't know yet how to fix. So if a quest where you have to kill an NPC is not working, it's probably the reason.
