### ISSUE TITLE
Wrong Medallion Reward

### ISSUE THREAD

**Issue by Rivenspeak** [WarEmu/WarBugs#14173]
Lvl 32/RR 33 and I'm getting soldier medallions instead of officer medallions for holding RVR objectives

![Drystzyk_001](https://user-images.githubusercontent.com/45123644/58359479-9fcd6680-7e51-11e9-8a8f-cc2f8356d40a.jpg)

**Comment by Kaelang** [comment]
No longer relevant due to Currency rework.
