### ISSUE TITLE
Bloodlord weapon issues

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#14175]
Here are various Bloodlord weapons that have issues:

This is missing a strength bonus
![Lotharic_153](https://user-images.githubusercontent.com/7400/58367104-69d4c480-7edb-11e9-8761-4305a75229de.jpg)

This is also missing a strength bonus
![Lotharic_151](https://user-images.githubusercontent.com/7400/58367117-a56f8e80-7edb-11e9-81dd-522ea09b8cce.jpg)

This is also missing a strength bonus
![Lotharic_150](https://user-images.githubusercontent.com/7400/58367121-b02a2380-7edb-11e9-9989-db4559ea0a05.jpg)

this has str, melee power & melee crit instead of BS, ranged power & ranged crit
![Lotharic_146](https://user-images.githubusercontent.com/7400/58367123-b4eed780-7edb-11e9-88f7-09fd8740e0e3.jpg)

this has str, melee power & melee crit instead of BS, ranged power & ranged crit
![Lotharic_148](https://user-images.githubusercontent.com/7400/58367136-d94ab400-7edb-11e9-9742-6d7e1852ac03.jpg)

This has wrong strike through, 6% instead of 8%
![Lotharic_149](https://user-images.githubusercontent.com/7400/58367143-e798d000-7edb-11e9-96be-4928f9fdef13.jpg)

This has wrong strike through, 6% instead of 8%
![Lotharic_145](https://user-images.githubusercontent.com/7400/58367146-ecf61a80-7edb-11e9-9184-c51fb7029ef0.jpg)

**Comment by wargrimnir** [comment]
Fixed, also got the book/chalice that were missing regen.
