### ISSUE TITLE
[Quest] Goradian The Creator

### ISSUE THREAD

**Issue by Aluviya** [WarEmu/WarBugs#14171]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
The only way to "interact" with the Mad Wizard ist to kill him, so there is no way to fulfill the 2nd quest requirement.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**
![Aluvya_009](https://user-images.githubusercontent.com/17249318/58349379-5c7bf380-7e63-11e9-9aab-453cb799f049.jpg)

**Comment by Lheana** [comment]
Again, must be related to #12470.

**Comment by Aluviya** [comment]
Indeed, it is related to  #12470 sorry to bother you twice, worked without party.
