### ISSUE TITLE
Mount cost in Grimmenhagen Village didn't change

### ISSUE THREAD

**Issue by Kushido** [WarEmu/WarBugs#1417]
In first village NPC with mounts still have 5 Gold as price for mount 
![kurshaa_004](https://cloud.githubusercontent.com/assets/14280617/9916388/c8c3c41a-5cc4-11e5-8cd3-0359d9b83bc3.jpg)

**Comment by Reggaewaldo** [comment]
This has been corrected in the database and can be marked as resolved..
