### ISSUE TITLE
Guilty Soul hitting for 16k

### ISSUE THREAD

**Issue by Lefze** [WarEmu/WarBugs#14179]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

See screenshot.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

![image](https://user-images.githubusercontent.com/31864442/58369553-54bc5d80-7efc-11e9-962c-6fcb925d9c72.png)

**Comment by NabaroNya** [comment]
![Nerv_011](https://user-images.githubusercontent.com/32055507/58369598-550d2680-7f05-11e9-808f-3740d1b4eacb.jpg)

**Comment by Shiversdd** [comment]
![Shiversx_009](https://user-images.githubusercontent.com/18085484/58369609-6ce4aa80-7f05-11e9-9813-85ab7becc04a.jpg)

**Comment by Handzz** [comment]
Also hit me for a pile.
![GuiltySoul18k1](https://user-images.githubusercontent.com/34697047/58370162-929b9080-7ec0-11e9-9a2b-35d1901ab467.jpg)

**Comment by SunsetCNTK** [comment]
can hit up to 30k on Aldorf dummy

![Untitled](https://user-images.githubusercontent.com/16652212/58371676-a02e3600-7f13-11e9-93a0-d32cd3099ae9.png)

**Comment by Kylashandra** [comment]
![bugpg](https://user-images.githubusercontent.com/51028086/58371960-e0db7e80-7f16-11e9-95ab-b3e614e0e67f.jpg)

**Comment by sioding** [comment]
its deactivated now until fix

**Comment by sioding** [comment]
fixed
