### ISSUE TITLE
Floating rock in Butcher's Pass

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#14185]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

At the order Warcamp at the butcher's Pass fortress, one of the rocks are floating in the air since last patch.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment]
![image](https://user-images.githubusercontent.com/18517842/58372183-36655a80-7f1a-11e9-9142-9f09f9f41e71.png)

**Comment by Lheana** [comment]
This was a temporary issue that has been fixed.
