### ISSUE TITLE
Salvagable rvr jewelry

### ISSUE THREAD

**Issue by malvic1** [WarEmu/WarBugs#14187]
**Expected behavior and actual behavior:**

Item should not be salvagable 
all other items are non salvagable from these vendors

**Steps to reproduce the problem:**

Dominion Steelhide in The Inevitable City "Veteran Renown Gear Merchant" sells the item Duelist's Pallium of Dominion @r13 rr9 which is salvagable

![ror_bug](https://user-images.githubusercontent.com/26604707/58375498-85c87c80-7f54-11e9-8f03-b5b677e72018.png)

**Comment by wargrimnir** [comment]
After review, it appears most of the consignment gear assigned to these merchants is set to salvageable, the ones that are missing need to be updated.

If you can provide a list of item and renown level along with the common name I can update them.

**Comment by malvic1** [comment]
Guess you mean the bind on equip items, is this something that differs from AoR? Since no silver/gold bought vendor items could be salvaged?

**Comment by malvic1** [comment]
NPC: Dominion Steelhide

Defender's Chain of Dominion R13/RR9
Gladiator's Ornament of Dominion R13/RR9
Duelist's Pallium of Dominion  R13/RR9
Martyr's Fragment of Dominion R13/RR9
Sage's Signet of Dominion R13/RR9
Marksman's Choker of Dominion R13/RR9
Literati's Hoop of Dominion R13/RR9
Gladiator's Chain of Conquest R18/RR12
Duelist's Ornament of Conquest R18/RR12
Martyr's Pallium of Conquest R18/RR12
Sage's Fragment of Conquest R18/RR12
Defender's Signet of Conquest R18/RR12
Marksman's Choker of Conquest R18/RR12
Literati's Hoop of Conquest R18/RR12


NPC: Martial Steelhide

Martial Shroud of Brawn R36/RR25
Martial Wrap of Skill R36/RR25
Martial Cape of Perseverance R36/RR25
Martial Shawl of Discipline R36/RR25
Martial Cloak of Volition R36/RR25
Martial Cape of Accuracy R36/RR25
Martial Shawl of Insight R36/RR25
Vanguard Shroud of Brawn R40/RR28
Vanguard Wrap of Skill R40/RR28
Vanguard Cape of Perseverance R40/RR28
Vanguard Shawl of Discipline R40/RR28
Vanguard Cloak of Volition R40/RR28
Vanguard Cape of Accuracy R40/RR28
Martial Badge if Vikutuib R33/RR23
Martial Jewelry of Brawn R33/RR23
Martial Earring of Skill R33/RR23
Martial Symbol of Perseverance R33/RR23
Martial Chaplet of Discipline R33/RR23
Martial Buckle of Accuracy R33/RR23
Martial Cord of Insight R33/RR23
Vanguard Badge of Volition R38/RR26
Vanguard Jewelry of Brawn R38/RR26
Vanguard Earring of Skill R38/RR26
Vanguard Symbol of Perseverance R38/RR26
Vanguard Chaplet of Discipline R38/RR26
Vanguard Buckle of Accuracy R38/RR26
Vanguard Cord of Insight R38/RR26


NPC: Sentry Steelhide

Sentry Shroud of Brawn R26/RR18
Sentry Wrap of Skill R26/RR18
Sentry Cape of Perseverance R26/RR18
Sentry Shawl of Discipline R26/RR18
Sentry Cloak of Volition R26/RR18
Sentry Cape of Accuracy R26/RR18
Sentry Shawl of Insight R26/RR18
Echelon Shroud of Brawn R30/RR21
Echelon Wrap of Skill R30/RR21
Echelon Cape of Perseverance R30/RR21
Echelon Shawl of Discipline R30/RR21
Echelon Cloak of Volition R30/RR21
Echelon Cape of Accuracy R30/RR21
Echelon Shawl of Insight R30/RR21
Sentry Horn of Volition R23/RR16
Sentry Medals of Brawn R23/RR16
Sentry Locket of Skill R23/RR16
Sentry Link of Perseverance R23/RR16
Sentry Knot of Discipline R23/RR16
Sentry Bangle of Accuracy R23/RR16
Sentry Pin of Insight R23/RR16
Echelon Horn of Brawn R28/RR19
Echelon Medals of Skill R28/RR19
Echelon Locket of Perseverance R28/RR19
Echelon Link of Discipline R28/RR19
Echelon Knot of Volition R28/RR19
Echelon Bangle of Accuracy R28/RR19
Echelon Pin of Insight R28/RR19



This is every Bind of Equip items from the Destruction vendors in Inevitable City that you can buy for money

**Comment by wargrimnir** [comment]
Pretty clear pattern here that accessories are not salvageable. Will be easy enough to update.

Thanks

**Comment by malvic1** [comment]
Also I noticed another vendor bug for salvageing, Decimator set only Boots salvagable.
Scout's emblem set all 3 pieces salvagable but Obliterator chest is NOT salvagable.
Devastator Helm, Chest and shoulders are not salvagable but the soldier emblem set all pieces are salvagable.

**Comment by wargrimnir** [comment]
Set the rest of these to salvageable

**Comment by Lheana** [comment]
Fixed with patch of 02/11/2019.
