### ISSUE TITLE
Mi horse is very fast 120% speed

### ISSUE THREAD

**Issue by kenshinoscuro33** [WarEmu/WarBugs#14181]
My horse is moving more fast. it twice more fast than others horses. 
Thanks

**Comment by Lheana** [comment]
Name of the mount please.

**Comment by kenshinoscuro33** [comment]
Pj: Ayaname
Horse: Blue roan elven steed

**Comment by Lheana** [comment]
Seems fine to me. Provide a screenshot or a video.

**Comment by sioding** [comment]
checked it also - everything ok. as lheana said: pls bring in some evidences

**Comment by kenshinoscuro33** [comment]
https://youtu.be/-U4Ay9-ckUw

**Comment by kenshinoscuro33** [comment]
Problem solved. Thanks for it.
