### ISSUE TITLE
Unable to access Warpblade Tunnels or Sigmar Cripts

### ISSUE THREAD

**Issue by qualteia** [WarEmu/WarBugs#14184]
**Expected behavior and actual behavior:**
Expected behavior: As per Grunbag post 360814, we should be able to access Sentinel Dungeons without the wards requirements.
Actual behavior: Not able to enter, warning message saying "Dungeon is accessible only to players who completed Redeye set from Gunbad dungeon located in Badlands"

**Steps to reproduce the problem:**
Try to enter Sigmar Crypts or Warpblade Tunnels

**Screenshots/Videos or archive.org evidences:**
https://imgur.com/LsObX8X
https://i.imgur.com/WZYuUKM.png

**Comment by grunbag** [comment]
It will be opened next week

**Comment by sioding** [comment]
Answer given - i close this one - just wait that week.
