### ISSUE TITLE
Character continously falling

### ISSUE THREAD

**Issue by tlukacs** [WarEmu/WarBugs#14186]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**
Character is stuck between a Bastion and a rock in Reikland, based on the animation it1S falling constantly, while the height of the character doesnt change.

As the character is considered moving, I can't use tome nor /stuck command.

Please take note of this bug, and help with freeing out my character Krazius, thanks.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment]
moved you to a safe place
