### ISSUE TITLE
[item] Solution and other spanners

### ISSUE THREAD

**Issue by jed3213** [WarEmu/WarBugs#14188]
Solution and many others spanners(i am found from epic quest/sentinel soul/Spanner of the Smuggler) have "Main hand" type(THIS IS WRONG). In this game all normal spanners/hammers have "Main hand or Off hand" type. This problem of different hands types does not allow to use the appearance between themselves, i think the last patch just broke even more spanners/hammers. 
![Hammer — копия (4)](https://user-images.githubusercontent.com/50764683/58377209-c12e6f80-7f83-11e9-8096-753ca6816769.png)
![Sentinel Soul](https://user-images.githubusercontent.com/50764683/58377210-c4c1f680-7f83-11e9-96d6-f507d50c6ccf.png)
![Hammer](https://user-images.githubusercontent.com/50764683/58377211-cc819b00-7f83-11e9-8f1a-748497184a19.png)
![Hammer — копия](https://user-images.githubusercontent.com/50764683/58377213-cf7c8b80-7f83-11e9-931b-c18c2c182a05.png)
![Hammer — копия (2)](https://user-images.githubusercontent.com/50764683/58377214-d2777c00-7f83-11e9-8e73-6833e5befd97.png)
![Hammer — копия (3)](https://user-images.githubusercontent.com/50764683/58377215-d4413f80-7f83-11e9-9750-0019e5a9ecdf.png)

**Comment by wargrimnir** [comment]
These seems to be a far shorter list of spanners that are flagged incorrectly as either hand, engineers can only use these as main hand. Slayers would use an offhand spanner, but they don't need any with Ballistic. Will update the ones necessary to be Main Hand only.

**Comment by jed3213** [comment]
> These seems to be a far shorter list of spanners that are flagged incorrectly as either hand, engineers can only use these as main hand. Slayers would use an offhand spanner, but they don't need any with Ballistic. Will update the ones necessary to be Main Hand only.

Spanners have binded to engineers career and slayers cant use him, do you think it's ok to deprive engineers of other hammers appearance?

**Comment by sioding** [comment]
fixed with patch from 01.06.2019
