### ISSUE TITLE
Shaman Sentinel Ring

### ISSUE THREAD

**Issue by Kurama363** [WarEmu/WarBugs#14182]
Sentinel set for Shaman is a healing set but the jewel has int on it. 

Can it be changed to wp since no other sentinel piece has int. And also since the upcoming Bloodlord set will be a dps set.

Thanks.

**Comment by wargrimnir** [comment]
These were indeed intended to be healing rings. Fixed.

**Comment by sioding** [comment]
fixed with patch from 01.06.2019
