### ISSUE TITLE
Sorc, tactic, chilling gust

### ISSUE THREAD

**Issue by TheOGScav** [WarEmu/WarBugs#14180]
Still doesn't crit nor is effected by Dark Magic:

https://youtu.be/C9DOXE-z_EE
https://youtu.be/LgtSK-3Kylg

PS: Still does the wrong dmg, now is 472 instead of 457.

**Comment by sioding** [comment]
Duplicate of #14164

**Comment by TheOGScav** [comment]
Dark Magic is NOT mentioned in previous ticket.
