### ISSUE TITLE
[Zealot] Tzeentch's Cordial

### ISSUE THREAD

**Issue by alubert** [WarEmu/WarBugs#14190]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
If its ToK related, please check the wiki before posting: 
https://wiki.returnofreckoning.com/index.php/Main_Page

**Expected behavior and actual behavior:**

Tzeentch's Cordial dont crit at all after pach.

**Steps to reproduce the problem:**

**Screenshots/Videos or archive.org evidences:**

**Comment by sioding** [comment]
Please add your testing screenshots

**Comment by alubert** [comment]
![Hurubek_000](https://user-images.githubusercontent.com/51048211/58383027-f497eb00-7fd1-11e9-952d-b2d69c999351.jpg)

**Comment by sioding** [comment]
Duplicate of #14243

**Comment by Ghatisgob** [comment]
I tested it also and the HoT never crits
