### ISSUE TITLE
[SW] Expert Skirmisher and Lileath's Arrows.

### ISSUE THREAD

**Issue by Ripliel** [WarEmu/WarBugs#14194]
**Expected behavior and actual behavior:**

Lileath's Arrows Skill has 2 seconds cast and works smoothly without Expert Skirmisher Tactic.
But when you slot the tactic, Lileath's Arrows get 1 second cast and weird freeze in the end. I guess, it's a result of an old poor bandaid fix.

Expected behaviour should be: Lileath's Arrows with Expert Skirmisher Tactic should have 2 seconds cast without freezes and 1 second cast should happen only when there is an enemy in 20 ft range.

https://youtu.be/XtLx4FZpqY0

**Comment by grunbag** [comment]
is it fixed ?
