### ISSUE TITLE
PQ: Pillage and Plunder Stage II broken

### ISSUE THREAD

**Issue by SODIX** [WarEmu/WarBugs#14191]
Wagons don't counts when I burn it.

<a href="https://ibb.co/yWd7hjP"><img src="https://i.ibb.co/yWd7hjP/Gruntag-010.jpg" alt="Gruntag-010" border="0"></a>

**Comment by Lheana** [comment]
You have to destroy them, which means attacking them.

**Comment by Moragor** [comment]
I just tested this, I'm confirming this PQ as completable. Note: The wagons can be destroyed in stage 1, this easily happens when using AoE damage. To make them count in stage 2 they need to "respawn" first and get destroyed again.

**Comment by sioding** [comment]
Thanks @Moragor - close
