### ISSUE TITLE
Invader set bonus 6 for AM

### ISSUE THREAD

**Issue by Koinzzell** [WarEmu/WarBugs#14193]
The Invader set bonus 6  for AM is bug:

When I am using a heal I lost ALL the buff that I have and this is cause by the bonus 6 pieces of the Invader set.

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format.

**Comment by Koinzzell** [comment]
You just need to equip 6 invader pieces, put some buff on you then heal yourself or somebody else and then you will see that all your buffs have desappear

**Comment by grunbag** [comment]
Which buff ?

**Comment by Koinzzell** [comment]
All kind of buffs and healing on time

**Comment by grunbag** [comment]
I need buff type

**Comment by sioding** [comment]
Wow ... would a screenshot or video help...

**Comment by Koinzzell** [comment]
Sorry for the delay, here the video:
https://www.youtube.com/watch?v=1P2VlSjURgk

**Comment by grunbag** [comment]
Fixed
