### ISSUE TITLE
[Quest] Nurgling Huntin' (Black Fire Pass, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14217]
The quest marker for the objective "Nurglings" is missing.

![nurgling huntin](https://user-images.githubusercontent.com/30193675/58387914-68a8b200-8017-11e9-9caf-6cdba3bb9fdb.jpg)

**Comment by Lheana** [comment]
This has been fixed with the patch of 31/03/2021.
