### ISSUE TITLE
AM/Shammy Dot Heal

### ISSUE THREAD

**Issue by knightningale90** [WarEmu/WarBugs#1421]
Problem 1:
After slotting divine fury, the heals from the dots of AM and shammy (Transfer force/ Bleed fer' me) are affected by divine fury, therefore it heals for 120% only (150%x80%). This was the mechanism before certain patch back on live, and after some time they changed it so that the dot heal is not affected by the divine fury tactic, only pure heals would be affected by it. If the dev team is aiming at bringing the old system back, feel free to ignore this one :)

Problem 2:
When the dot crits, the heal does not get the multiplier from the critical dot damage. That means the heal completely ignores the fact the dot has a crit and heals for the same amount as it is when there is no crit.
here is a screenshot of the test log
![drtinygreen_075](https://cloud.githubusercontent.com/assets/14324838/9925297/32d8b1c2-5d3c-11e5-8280-619d2cfa0a6d.jpg)

Thank you for your attention!

**Comment by Tyramissoux** [comment]
That heal is negative dmg and shouldn't be affected by any heal debuffs. Sometimes I feel that M2 aoe heal is also affected by debuffs but can't prove it atm.

**Comment by Evildoor** [comment]
Can someone clarify - AM's similar skill has this problem? I tested Divine Assault on WP, it works properly.

**Comment by ozarmidrashim** [comment]
Lifetaps of any kind are never affected by heal debuffs of any kind - they don't go through the normal heal system, they act on the character's HP directly.

**Comment by Silentguard** [comment]
Aza, check screenshot, this dot should heal 150% of dmg dealt but it heals only 129hp instead of 160.

**Comment by ozarmidrashim** [comment]
Yes, I know. That I didn't comment on that means that it was a legitimate bug and is fixed.

**Comment by ozarmidrashim** [comment]
Also fixed an issue causing Morale heals to trigger direct heal events.
