### ISSUE TITLE
[Quest] Unlikely Places (Ostland, destro) quest not completable

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14214]
There is no quest item given to the player. Talking to the quest giver gives 1/3 progress, but clicking him again just gives the message "Already spoken with" and no further progress.

![unlikely places](https://user-images.githubusercontent.com/30193675/58387845-3185d100-8016-11e9-978f-f56ad57b8072.jpg)
![unlikely places 1-2](https://user-images.githubusercontent.com/30193675/58387846-334f9480-8016-11e9-8df7-408c87e063df.jpg)

**Comment by Lheana** [comment]
This has been fixed with patch of 06.10.2019

**Comment by Lheana** [comment]
You now receive the Xplodie Potion, so this part is completable.
