### ISSUE TITLE
[NPC] Thardkrik Pilots not targetable (Black Fire Pass)

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14212]
The Thardkrik Pilots needed for the Quests "Groundin' da Fliers" and "Kopta Krusha" in BFP are not targetable and can therefore only be killed by AoE damage.

![groundin da fliers](https://user-images.githubusercontent.com/30193675/58387802-79f0bf00-8015-11e9-8ae6-fbc88566c946.jpg)
![kopta krusha](https://user-images.githubusercontent.com/30193675/58387803-7c531900-8015-11e9-8073-9c08c6bc1b98.jpg)

**Comment by sioding** [comment]
fixed with patch from 10.06.2019
