### ISSUE TITLE
[PQ] Fireforge's Camp, Stage 1 (The Badlands, destro) only 2 Supply Crates attackable

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14219]
Out of the 10-ish supply crates in the area only two are actually attackable which forces one to wait for respawn over and over.

![fireforges camp](https://user-images.githubusercontent.com/30193675/58388079-043b2200-801a-11e9-81a0-b0b0e58a43c0.jpg)

**Comment by Lheana** [comment]
Duplicate of #14044
