### ISSUE TITLE
[Quest] Shaman Circle (Black Fire Pass, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14218]
The quest marker for the objective "Blighted Gorhorns" is missing.

![Shaman circle](https://user-images.githubusercontent.com/30193675/58387934-9beb4100-8017-11e9-9450-e0293ca6fff2.jpg)

**Comment by Lheana** [comment]
This has been fixed with the patch of 31/03/2021.
