### ISSUE TITLE
 [NPC] Non targetable NPCs on the quest"Two Heads are Better Than One" (Black Fire Pass)

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14216]
At least one of the target NPCs in this quest is accompanied by not targtable NPCs (don't know the name coz I can't target them).

![two heads are better than one](https://user-images.githubusercontent.com/30193675/58387893-1798be00-8017-11e9-970f-4c24af786ee7.jpg)

**Comment by sioding** [comment]
fixed with patch from 10.06.2019
