### ISSUE TITLE
Lector twins spawn extra Zakarai in lag spikes

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#14229]
**Expected behavior and actual behavior:**

Every time there is a lag spike during the lector twins fight, an extra Zakarai is spawned, making the boss impossible to complete.

**Steps to reproduce the problem:**

Do this boss during server lag. It it 100% reproducible in that situation.

**Testing Screenshots/Videos/Evidences (always needed):**

![Lotharic_168](https://user-images.githubusercontent.com/7400/58388582-0b196300-8021-11e9-951f-1e44d9e07ef4.jpg)

**Comment by CrimsonFenris** [comment]
Wow you got 3 Zakarai, nice :p

Happened to our group too some weeks ago, zakarai had been spawned a second time during a lag spike. Had to reset boss, obviously.

**Comment by Hargrim** [comment]
Should be fixed after patch on Saturday 01.06.2019.
