### ISSUE TITLE
[Quest] Press the Attack (Reikland, destro) Cannon damage too low

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14222]
Since the lanterns were fixed in https://github.com/WarEmu/WarBugs/issues/13156 they cannons can't kill the Elfs on the ship anymore. The remove like 10% health, then the Elfs run towards the player and get killed by the warcamp guards. You have to fight them in the water or use an ability like Squig Leap to get on board. Also only three of the 5 Elfs on board are the wanted "Silversong Bladesinger" forcing one to wait for respawn to complete the quest.

![press the attack](https://user-images.githubusercontent.com/30193675/58388187-d22abf80-801b-11e9-8424-9b604293b4c8.jpg)

**Comment by Lheana** [comment]
This has been fixed several patches ago.
