### ISSUE TITLE
Getting 1shot by artifact in MT

### ISSUE THREAD

**Issue by nefarit** [WarEmu/WarBugs#1422]
This happened to me several times in MT when picking up the bauble from its spawn or a dead player, far from any faction spawn and it kills me with 123456 damage the first tick after I pick it up. It's not a game mechanic, it's a bug. Hopefully you'll locate it a.s.a.p

**Comment by Evildoor** [comment]
Status? I've encountered it several times, but that was long ago.

**Comment by Evildoor** [comment]
No response, closing for now.
