### ISSUE TITLE
[Quest] Time to Waaagh! (3) (Kadrin Valley, destro) Three objectives, one click and end marker misisng

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14228]
The three objectives are done with a single click (and two of them are identical). The quest end marker on Gazbag is also missing.

![time to waaagh 3](https://user-images.githubusercontent.com/30193675/58388411-b5dc5200-801e-11e9-8386-048e55383015.jpg)

**Comment by lilimx** [comment]
fixed with patch 22/12/2021
