### ISSUE TITLE
[Quest] Time to Waaagh! (2) (Kadrin Valley, destro) Quest end marker misisng

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14227]
The end marker for the NPC to turn in the quest is missing.

![time to waaagh2](https://user-images.githubusercontent.com/30193675/58388381-60a04080-801e-11e9-8561-0df4be759115.jpg)

**Comment by lilimx** [comment]
Fixed with Patch 19/12/2021
