### ISSUE TITLE
[Quest] Out of Favor: Leashing the Waaagh! (Thunder Mountain, destro) Too few mobs/counter too high

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14224]
You have to "remind" 10 gobbos, but there are only 8 of them. "Reminding" them again after respawn shows an "Already spoken with" message and doesn't give further contribution.

![leashing the waaagh](https://user-images.githubusercontent.com/30193675/58388264-08b50a00-801d-11e9-9369-a1435abf9435.jpg)
![leashing the waagh 1-2](https://user-images.githubusercontent.com/30193675/58388289-3ac66c00-801d-11e9-8cda-5467018d22c2.jpg)

**Comment by bosli42** [comment]
Bump.
I just found this quest (readded?), and this still happens. I waited for more than 10 minutes, but the spoken-to tag timer seems very long or even permanent, preventing the quest to be completed.

**Comment by valkeera** [comment]
Counter seems to get reset after server restart at least, that's how I was able to complete the quest.

**Comment by lilimx** [comment]
fixed with patch 13/01/2022
