### ISSUE TITLE
[Quest] Out of Favor: Leashing the Waaagh! (2) (Thunder Mountain, destro) Quest marker misisng

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14225]
This quest has no quest markers.

![leashing the waagh 2](https://user-images.githubusercontent.com/30193675/58388314-8c6ef680-801d-11e9-9856-d9a10053f43d.jpg)

**Comment by lilimx** [comment]
fixed with patch 13/01/2022
