### ISSUE TITLE
[Quest] Time to Waaagh! (Kadrin Valley, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14223]
This quest does not have a quest marker.

![time to waaagh](https://user-images.githubusercontent.com/30193675/58388227-6eed5d00-801c-11e9-98cf-669a6ad83bad.jpg)

**Comment by Lheana** [comment]
This step of the quest will be disabled with next patch.

**Comment by lilimx** [comment]
Fixed with patch 19/12/2021
