### ISSUE TITLE
Missing WE headgear

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#1423]
Witch Elf has no available headgear of Conguest (lvl 19 green from vendors, i believe it should be called Hexveil Of Conguest).
http://www.arsenalofwar.com/armor/Destruction/Hexveil%20of%20Conquest

**Comment by Reggaewaldo** [comment]
Item added as it was on live.
Referance: http://war.mmodb.com/items/hexveil-of-conquest-94822.php

Closing.
