### ISSUE TITLE
Keep Objective Track shows "The War Has Moved To"... while RvR active

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#14239]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**
I've been seeing this more lately don't know why
expected - Keep Objective Tracker should not be showing this message while RvR active
actual - shows that the "War has moved to Inevitable City"

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**
https://i.ibb.co/sFfb4F3/keep-obj.jpg

**Comment by sioding** [comment]
This happens since forts have been implementet. Thanks for the report.
