### ISSUE TITLE
[NPC] Leftover NPC from MVP event in IC

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14237]
One of the Conspirator NPCs from the Mask event was left in IC outside the Apex where the horrified/enraged souls are. Its AI seems to be broken, he/she does not fight when attacked.

![Conspirator](https://user-images.githubusercontent.com/30193675/58389708-0b1f6000-802d-11e9-97dd-552ff32d437e.jpg)

**Comment by Ootootoo** [comment]
Took me 10 minutes to kill it for 4000 exp at level 20, so I can confirm this. I found it funny though ;)

**Comment by sioding** [comment]
fixed with patch from 01.06.2019
