### ISSUE TITLE
[Quest] The Wind of Change (2) (IC/Ellyrion, destro) Quest needs rework

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14245]
- The quest marker for the objective "Wellspring of Caledon Contaminated" is missing.
- No quest item is given to the player when the quest starts. This might make the quest uncompletable, though I could not verify this because I'm nut sure where this Wellspring is.

![wind of change 2](https://user-images.githubusercontent.com/30193675/58442011-467e6500-80e7-11e9-8bcf-c499c87463dd.jpg)

**Comment by Ademai** [comment]
![image](https://user-images.githubusercontent.com/10104679/125135143-d1284f80-e108-11eb-910b-7fb1e5b2cc3e.png)

First part is doable. Still no quest item (Mephitic Dust) and no idea where Wellspring of Caledon is. Closest is 'Well Springs' just south east of Cascades of Thunder.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/14838
