### ISSUE TITLE
Ork twohanders from PVP vendor

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#1424]
The following twohanded weapons from vendor have DPS of onehanders (or a bit less/more):
Sentry Big Choppa - 30.3, should be 45.
Echelon Big Choppa - 35.6, should be 52.2. This one also gives only 76 stats, should be 89-90 like Echelon Deathaxe/Glaive.
Martial Big Choppa - 40.8, should be 59.5.

**Comment by Reggaewaldo** [comment]
Sentry Big Choppa, seems to be correct with this reference:
http://www.arsenalofwar.com/items/Destruction/Sentry%20Big%20Choppa

Echelon Big Choppa, was incorrect and was changed in stats and to be 1h according to this reference:
http://www.arsenalofwar.com/items/Destruction/Echelon%20Big%20Choppa

Martial Big Choppa , had the incorrect model so I changed that but the stats are correct according to:
http://www.arsenalofwar.com/items/Destruction/Martial%20Big%20Choppa

Closing.

**Comment by xyeppp** [comment]
* The following weapons had lower than intended DPS, and have had their DPS increased to a value appropriate to their level: Badmoon Mace, Ruggog's Shootah, Martial Trollsplitter, Echelon Trollsplitter, Sentry Trollsplitter, Passwatch Windblade, Militia Choppa, Martial Big Choppa, Vanguard Big Choppa, Echelon Big Choppa, Sentry Big Choppa, Big Choppa of Dominion

1.2 Patch Notes, something to keep in mind.

**Comment by Reggaewaldo** [comment]
Xyeppp, Thanks for the contribution. I have reopened this to be sure that we see this through.

**Comment by Evildoor** [comment]
Added proper stats and model to Echelon axe. Fixed DPS of all 3.
