### ISSUE TITLE
Champion Spider Mob not attacking

### ISSUE THREAD

**Issue by Jandeporas** [WarEmu/WarBugs#14249]
**Expected behavior and actual behavior:**
I was farming some spiders in black crag zone (42k - 54k to be precise) and I decided to use my spiked squig to pull spiders and kill them away from other mobs using squig armor mode.

Normal rank spiders aggroed my squig normally but champion spider don't attack back.

**Steps to reproduce the problem:**

Go to Black Crag 42k - 52k as a squig herder, use your spiked squig to attack champion spiders while under squig armor mode, they don't attack back (???)

From previous times I've been there those champion spiders used to have a range acid attack, seems like a malfunction of such attack might be blocking their AI behavior somehow...

**Testing Screenshots/Videos/Evidences (always needed):**

![Tadpoledancer_397](https://user-images.githubusercontent.com/36811878/58451331-4eec9500-8113-11e9-8019-13f5adf08f10.jpg)

**Comment by Lheana** [comment]
Hm I have no problem attacking these NPCs ...

**Comment by Jandeporas** [comment]
You might not have a problem but some of these spiders do, some are braindead:

https://www.youtube.com/watch?v=_tCLFjP7Mmw

Again, this is not really a problem because the AI of the spider goes numb and doesn't attack back, resulting in advantageous situation for the player but I doubt that's intended behavior.

**Comment by sioding** [comment]
fixed with patch from 10.06.2019
