### ISSUE TITLE
Zealot - tzeentch's cordial not critting

### ISSUE THREAD

**Issue by porterrr** [WarEmu/WarBugs#14243]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.

https://github.com/WarEmu/WarBugs/issues/14190 - this was open but its been closed

**Expected behavior and actual behavior:**

heal isnt critting

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/40496651/58440183-4888f980-80d0-11e9-806f-b559f460dfd8.png)

**Comment by sioding** [comment]
Well this guy closed his own ticket /shrug

**Comment by grunbag** [comment]
fixed for next patch

**Comment by sioding** [comment]
fixed with patch from 01.06.2019
