### ISSUE TITLE
[Quest] BO scouting quests at all RvR warcamps unlock at the wrong level

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14247]
The scouting quests at every warcamp unlock at lvl 40, even in Tier 1.

Some examples:
Nordland, T1
lvl 33 no quest
![Aggerond_007](https://user-images.githubusercontent.com/30193675/58442864-8432bc00-80ee-11e9-891e-fe18d2dfe060.jpg)
lvl 40 offers scouting quest
![Whikna_008](https://user-images.githubusercontent.com/30193675/58442869-8a289d00-80ee-11e9-8f60-f54ff912faf1.jpg)

Marshes of Madness, T2
lvl 33 no scouting quest
![Aggerond_008](https://user-images.githubusercontent.com/30193675/58442865-8432bc00-80ee-11e9-8c92-fd9ec3a26503.jpg)
lvl 40 Gits n' Armor scouting quest
![Whikna_010](https://user-images.githubusercontent.com/30193675/58442871-8e54ba80-80ee-11e9-9167-8c850db19d29.jpg)

**Comment by Lheana** [comment]
Quests given by Vilkynn and Guzzle have now the correct minimum level requirement.

**Comment by sioding** [comment]
fixed with patch from 10.06.2019
