### ISSUE TITLE
New issue with chillwind and Absorb...

### ISSUE THREAD

**Issue by TheOGScav** [WarEmu/WarBugs#14240]
Chillwind takes now 6 secs to actually start kicking in dmg.

![Icii_056](https://user-images.githubusercontent.com/46210669/58396811-cf2bd100-8013-11e9-999f-6596faf348c9.jpg)
![Icii_057](https://user-images.githubusercontent.com/46210669/58396816-d3f08500-8013-11e9-9716-37299c28ee69.jpg)

video/s coming:
https://youtu.be/OBCm2s-6rOo
https://youtu.be/BBSF7wRw-i0

Look at at :30 sec and :00 at the end. 

Never mind, clock is wrong. But it does take 3 secs to trigger, same as Absorb... Both those dots should trigger immediately. No reason for this stealth nerf. Something doesn't feel just right. Not even sure how this effects Shadow of Disaster if it triggers 3 secs past cast (is the debuff triggered from 0-9 sec or 3-12?) . Ya have 3 tactics that depend on Chillwind, this needs attention.

PS: Not to mention this gives a 3 sec window for these spells to be cleansed without doing any dmg.

PS2: Ice Spikes might be also iffy: https://youtu.be/-FwYGSYUscQ

**Comment by grunbag** [comment]
nothing has changed for those abilities

**Comment by TheOGScav** [comment]
> 
> 
> nothing has changed for those abilities

Then those are bugged from the very beginning  and no one chked.

**Comment by grunbag** [comment]
almost all dot don't tick on application.
