### ISSUE TITLE
lost temple of fail

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#14242]
lost temple of isha scen appears to have become seriously unbalanced in orders favour - destro now has a new starting location some way behind the original one, which im guessing order dosnt share because they were at least 200 feet ahead of us in the initial charge towards the flag (not had a chance to play it as order yet), and possibly a problem that order does share, the scenario winning quest apparently cant be completed since it involves killing an npc that dosnt seem to exist

**Comment by sioding** [comment]
Someone changed the spawn points?

**Comment by MightyPhred** [comment]
update : ive now played the scenario on an order character as well as a destro one, both spawn points have changed to being inside a tent - but the destruction one is significantly further away from the objective, and the scenario winning quest for order makes no mention of killing an npc, all you have to do is win the scenario to complete the quest

**Comment by MightyPhred** [comment]
further update : just won the scen and handed in quest, the reward does work, and it is giving oppressor emblems

**Comment by Kaelang** [comment]
Suggestions as opposed to a bug.
