### ISSUE TITLE
[Quest] Horn Heads (Black Fire Pass, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14248]
The quest marker for the objective "Kill Grrlac" is missing.

![Horn heads](https://user-images.githubusercontent.com/30193675/58443761-52bcef00-80f4-11e9-93bc-9ea8e387a899.jpg)

**Comment by Lheana** [comment]
This has been fixed with the patch of 07/04/2021.
