### ISSUE TITLE
Unterbaum Cemetary PQ Stage 3  CH.14 Empire

### ISSUE THREAD

**Issue by Elluette** [WarEmu/WarBugs#14255]
When you arrive at stage 3 of the public quest. The boss, "Podgore the Leaking"  Spawns multiples of itself. They are standing inside eachother and the PQ cannot be cleared normally because of the massive amounts of damage they put on a tank at once.
![Screenshot_60](https://user-images.githubusercontent.com/51149782/58533498-928be100-819d-11e9-9ba2-024cec4804c9.jpg)

**Comment by Lheana** [comment]
Tested, works fine, I only get 1 Podgore the Leaking. Maybe this was due to some lags.

**Comment by Elluette** [comment]
Yeah I saw a few other times trying with my friend that it only happened once apparently.
