### ISSUE TITLE
[Quest] Explosive Solutions (Black Crag, destro) Quest markers switched

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14252]
The quest markers for the two objectives are switched.
Also, it is possible to "put the burnrock in barrels" before obtaining it from the Morkfang Madboys.

![explosive solutions](https://user-images.githubusercontent.com/30193675/58471560-71e36d00-8144-11e9-980d-c064b0b33753.jpg)

**Comment by Lheana** [comment]
This has been fixed with the patch of 28/04/2021.
