### ISSUE TITLE
[Zealot] ... Focus of brutality

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#1425]
These items have missing stats:
Apostle's Focus of Brutality - 17 WIL, should be 20.
Nihilist's Focus of Brutality - 17 INT, should be 20; 12 WOU, should be 14.
Sources:
https://gaarawarrgabs.wordpress.com/2010/06/03/the-weapons-of-war
http://www.arsenalofwar.com/items/Destruction/Apostle's%20Focus%20of%20Brutality
http://www.arsenalofwar.com/items/Destruction/Nihilist's%20Focus%20of%20Brutality

**Comment by Reggaewaldo** [comment]
This has now been corrected in the DB according to linked source.

This can be marked as resolved.
