### ISSUE TITLE
[Quest] Tag, You're Dead (Black Crag, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14251]
The quest marker for the objective "Redmand Stunties" is missing.

![tag youre dead](https://user-images.githubusercontent.com/30193675/58471401-11543000-8144-11e9-938a-9123f9d66f7d.jpg)

**Comment by Lheana** [comment]
This has been fixed with the patch of 20/04/2021.
