### ISSUE TITLE
[Item] Phantasm and Demonrend procs

### ISSUE THREAD

**Issue by Shiversdd** [WarEmu/WarBugs#14250]
New Phantasm and Demonrend weapons gives old procs on 80 wounds instead of 110 .
I think it's a problem with all the weapons with the buff +Preservation .

![Neferat_013](https://user-images.githubusercontent.com/18085484/58471107-ce965600-814b-11e9-8ce8-c84433fae4e7.jpg)

**Comment by grunbag** [comment]
fixed already
