### ISSUE TITLE
[Quest] Dirty Deeds (Thunder Mountain/Cinderfall, destro) Quest item not implemented

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14268]
Morg Skinripper isn't giving a quest item to the player, instead " Examine Skinripper's Map" is completed by clicking him.

![dirty deeds](https://user-images.githubusercontent.com/30193675/58550067-437d9480-820d-11e9-88d6-5a50d0cfa093.jpg)

**Comment by lilimx** [comment]
Fixed with Patch 22/07/2021
