### ISSUE TITLE
[Quest] Smashin' da Bony Stunties (Thunder Mountain/Cinderfall, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14264]
The quest marker for the objective "Kill Deathly Engineer" is missing.

![smashin da bony stunties](https://user-images.githubusercontent.com/30193675/58549278-6eff7f80-820b-11e9-8e2d-63a709c88457.jpg)

**Comment by lilimx** [comment]
Fixed with Patch 22/07/2021
