### ISSUE TITLE
[Quest] Stunties for da Forge (Thunder Mountain, destro) Not working as intended

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14262]
According to the description you should use a quest item on a blacksmith, but no quest item is given to the player. Instead the quest completes after killing and looting him.

![stunties for da forge](https://user-images.githubusercontent.com/30193675/58548962-be917b80-820a-11e9-8425-9ae8d9524aa0.jpg)

**Comment by lilimx** [comment]
related/dublicate: #14262

**Comment by lilimx** [comment]
related/dublicate: #18839
