### ISSUE TITLE
Titan's Blood Ward of Anathema - Wrong name & stats

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#14269]
**Expected behavior and actual behavior:**

This shield should match the WP equivalent "Shieldbearer's Buckler of Reverence", but it has wrong name and stats. It should be called "Shieldbearer's Blood Ward of Anathema", and have the stats of the WP shield.

**Testing Screenshots/Videos/Evidences (always needed):**

![Dalen_014](https://user-images.githubusercontent.com/7400/58565172-8e5bd400-822e-11e9-90de-eddd13649b68.jpg)

**Comment by dalen** [comment]
The "Sentry's" variants match as they should:

![Dalen_015](https://user-images.githubusercontent.com/7400/58565327-cebb5200-822e-11e9-89bf-5057598e608a.jpg)

**Comment by sioding** [comment]
fixed with patch from 01.06.2019
