### ISSUE TITLE
Chosen aura collision

### ISSUE THREAD

**Issue by Gargatyk** [WarEmu/WarBugs#1426]
When you try to activate a Chosen aura, it wouln't work if there is an another Chosen within aura range, who has the same aura already active

**Comment by ozarmidrashim** [comment]
Correct handling is that both auras should apply, but only the strongest is used?

**Comment by Silentguard** [comment]
It will be fair enough. Also would be great to make additional effects persist auras priority, like +10% inc crit tac from kotbs str aura. As one per target instance.

**Comment by osium** [comment]
"Correct handling is that both auras should apply, but only the strongest is used?" that is correct
