### ISSUE TITLE
Troll Country PQ Lursa's Blight stuck on stage 1

### ISSUE THREAD

**Issue by Gremn** [WarEmu/WarBugs#14270]
**Expected behavior and actual behavior:**
For my understanding there should spawn Rot Priests but they don't.
The PQ is stuck in stage 1 because of this.

Also couple hours ago I didn't get credit for killing Rot priests for quest "Blighted Ambition"
when there were still few rot priests left.

**Steps to reproduce the problem:**
No idea it was this way when I came to the zone.

**Testing Screenshots/Videos/Evidences (always needed):**
Image of the zone being cleared of rot priests and stuck at stage 1 of the PQ:

https://imgur.com/a/c9bq1ww

**Comment by Lheana** [comment]
I could not reproduce this, Rot Priests respawn correctly.

**Comment by Lheana** [comment]
No answer for 17 days, I close it.
