### ISSUE TITLE
Supply?!?

### ISSUE THREAD

**Issue by TheOGScav** [WarEmu/WarBugs#14276]
Are supplies working as suppose to?!?

https://youtu.be/W970Zx8lL6w 

...or am I missing something?

**Comment by wargrimnir** [comment]
If you need help with game mechanics, go to the forums. Don't spam the bugtracker unless you can provide proof required to fix something,

**Comment by TheOGScav** [comment]
It would be nice to have those game "mechanics" displayed ingame actually... Some ppl don't have time to chk the weekly changes.
