### ISSUE TITLE
[Gunbad] Strange debug message when talking to NPCs

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14278]
When talking to some NPCs at the entrance of Gunbad this messages appear in the chat:

![Moragor_002](https://user-images.githubusercontent.com/30193675/58705728-5aa8b780-83b0-11e9-8054-9009e0ca1210.jpg)

**Comment by Hargrim** [comment]
Not an issue, this is debug information that need to be send to me in case you don't get quest credit and you think you should get it.
