### ISSUE TITLE
[RP/Zealot] silence doesn't scale from int

### ISSUE THREAD

**Issue by dshdf1** [WarEmu/WarBugs#14279]
**Expected behavior and actual behavior:**
Actual behaviour: RP/Zealot silence ability (Spellbinding Rune/Tzeentch's Lash)  ATM doesnt scale from Int (neither from int items nor class stat mechanic conversion) at all
also spell does less damage than tooltip says

Expected: it should scale with stats as any other dmg spell
**Steps to reproduce the problem:**
Use silence on any target

**Testing Screenshots/Videos/Evidences (always needed):**
(https://user-images.githubusercontent.com/51263689/58748341-f7865600-847f-11e9-8089-c622b8be5023.png)
stat difference between casts is about 350 int. tooltip says "395 ele dmg over 4 s."

**Comment by grunbag** [comment]
Fixed with next patch
