### ISSUE TITLE
item no stats Vestments of the Purifier

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#1427]
Quest reward item - order Quest - Missions - Class - RP Item name Vestments of the Purifier -descriction - no stats on item

**Comment by Reggaewaldo** [comment]
The item has been tuned to feature the same stats as it featured in game according to online sources:

http://war.mmodb.com/items/vestments-of-the-purifier-92406.php
http://www.warbits.com/gold-items-28023-Vestments-of-the-Purifier.html

This is now resolved as the change has been saved to the DB.
