### ISSUE TITLE
[NPC] Dragonblessed Ferkath (Cinderfall) NPC attacked by allies

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14289]
Dragonblessed Ferkath in southeast Cinderfall gets attacked and killed by surrounding NPCs. This is especially problematic since he is needed for the quest [Betta Booms].

![dragonblessed ferkath](https://user-images.githubusercontent.com/30193675/58752274-96c14280-84ac-11e9-9956-4b8590da6d94.jpg)

**Comment by sioding** [comment]
fixed with patch from 10.06.2019
