### ISSUE TITLE
[Quest] Faith is Madness: Missing map tracker

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#14283]
**Expected behavior and actual behavior:**

In this step, if you take any of the crystals, the map tracker dissapear entirely

**Steps to reproduce the problem:**

Reach this step in this quest chain and pick only one of the shards.

**Testing Screenshots/Videos/Evidences (always needed):**

![Marajade_001](https://user-images.githubusercontent.com/50114048/58750904-a67e5e00-848f-11e9-8c03-895d70386a52.jpg)

**Comment by Ootootoo** [comment]
Can confirm that this issue has been fixed.

**Comment by Kaelang** [comment]
Fixed in todays patch.
