### ISSUE TITLE
[NPC] Unattackable mob in the middle of the road in Eataine

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#14284]
**Expected behavior and actual behavior:**

Same as here: https://github.com/WarEmu/WarBugs/issues/14280
which was in turn the same as here: https://github.com/WarEmu/WarBugs/issues/13991

**Steps to reproduce the problem:**

Select this NPC, location can be seen in the map attached, and try to attack it

**Testing Screenshots/Videos/Evidences (always needed):**

![Marajade_010](https://user-images.githubusercontent.com/50114048/58750927-08d75e80-8490-11e9-91b4-fc3a3b692c17.jpg)

**Comment by sioding** [comment]
fixed with patch from 10.06.2019
