### ISSUE TITLE
[NPC] Silver Helms missing the horse model

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#14285]
**Expected behavior and actual behavior:**

Not a big deal, but kind of weird to see these Silver Helms, and even their named Captain, without a horse model.

**Steps to reproduce the problem:**

Go to the location that can be seen in the map attached and see a group of knights that are mounting invisible horses. Thats actually very Elfy ;P

**Testing Screenshots/Videos/Evidences (always needed):**

![Marajade_008](https://user-images.githubusercontent.com/50114048/58750981-a468cf00-8490-11e9-9912-3ceddb5f289b.jpg)

**Comment by Lheana** [comment]
They are not missing a horse, this is an emote that makes them flying. From what I can see, nothing to fix here, seems intended.

**Comment by Ootootoo** [comment]
I dont think so. Maybe was a mistake by Mythic, but indeed Silverhelms are like these:

https://www.google.com/search?q=caledor+silverhelm&tbm=isch&source=iu&ictx=1&fir=Y5L-8wCOhqgaRM%253A%252CoL5F79t88G3PQM%252C_&vet=1&usg=AI4_-kTp008mvMEKacPx_AWsL0j4--ZO0g&sa=X&ved=2ahUKEwik7L_GutbiAhXNxoUKHfpFAsMQ9QEwAHoECAAQBA#imgrc=Y5L-8wCOhqgaRM:
