### ISSUE TITLE
Zealot New Patch - BB/BE INF rewards not equippable

### ISSUE THREAD

**Issue by hogo2hogo** [WarEmu/WarBugs#14287]
(Zealot) After today's patch, I am unable to equip the BB/BE influence reward "dreadful Horror" & "Trepidation" are not possible to be equipped.

I was using it yesterday without issues, seems to be patch related bug.

I have full redye, tried to re-equip the items after relog too, still nothing happened.

**Comment by grunbag** [comment]
Is it fixed ?

**Comment by hogo2hogo** [comment]
sorry for late reply.

no, as of today it hasnt been fixed (i dont know if later today a patch is coming)

**Comment by grunbag** [comment]
Any error message in chat ?

**Comment by hogo2hogo** [comment]
not that i can see, i had most message filters (system general,error etc) enabled but nothing popped up. i will try filtering everything to active and reply again tomorrow

**Comment by hogo2hogo** [comment]
Error that pops up in chat says, "You don't have the required tome of knowledge entry to equip this item..  same message for both"
sorry for not spotting it sooner.

**Comment by grunbag** [comment]
fixed for next patch

**Comment by sioding** [comment]
Fixed with patch from 15.06.2019

**Comment by sioding** [comment]
fixed with patch from 22.6.2019
