### ISSUE TITLE
[PQ] [NPC] The Shrine of Teclis: unattackable mobs

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#14280]
**Expected behavior and actual behavior:**

Same as here: https://github.com/WarEmu/WarBugs/issues/13991

**Steps to reproduce the problem:**

Try to attack the NPCs

**Testing Screenshots/Videos/Evidences (always needed):**

![Marajade_004](https://user-images.githubusercontent.com/50114048/58750669-45558b00-848d-11e9-98b5-6234c3384c26.jpg)
![Marajade_005](https://user-images.githubusercontent.com/50114048/58750670-45ee2180-848d-11e9-977d-0e734a93a2db.jpg)
![Marajade_006](https://user-images.githubusercontent.com/50114048/58750671-45ee2180-848d-11e9-9be4-87778fa239e8.jpg)
![Marajade_007](https://user-images.githubusercontent.com/50114048/58750672-45ee2180-848d-11e9-9b13-6af497c33f52.jpg)

**Comment by sioding** [comment]
fixed with patch from 10.06.2019
