### ISSUE TITLE
[ITEM] [Tier1] Black Guard: Dark Elf RvR Influence Reward Discrepancy

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#14281]
**Expected behavior and actual behavior:**

Both Rewards should be pretty much similar, but seems that one of them is at least a couple levels above the range, or one is one level below

**Steps to reproduce the problem:**

As a Black Guard, check Tier1 influence rewards from Dark Elf RvR zone.

**Testing Screenshots/Videos/Evidences (always needed):**

![Dathenor_000](https://user-images.githubusercontent.com/50114048/58750800-800bf300-848e-11e9-88f9-d038cd33e056.jpg)

**Comment by Ootootoo** [comment]
Look specifically at the armour count of both items anc compare with a same level green one that i have equipped.

**Comment by sioding** [comment]
fixed with patch from 13.07.2019
