### ISSUE TITLE
[Quest] Soup's On (Thunder Mountain/Cinderfall, destro) Too few NPCs

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14288]
The quest requires 16 Neophytes to be killed, but there are only 6 in the cave.

![soups on](https://user-images.githubusercontent.com/30193675/58752213-80ff4d80-84ab-11e9-8798-e814505dc387.jpg)

**Comment by lilimx** [comment]
Fixed with Patch 22/07/2021
