### ISSUE TITLE
[Salvaging]

### ISSUE THREAD

**Issue by Radiantknight** [WarEmu/WarBugs#1428]
There's a bug with salvaging, which was 'kinda' fixed. There was a salvageable echelon belt for sorc, which I reported to Github, but now ALL echelon gear is salvageable. Item level was removed from echelon gear, but salvaging somehow persisted, so you can salvage it with any level of salvaging skill. It's just white, meaning it doesn't fail, but it's an easy way to level salvaging and get green frags of anywhere between 1 and 150.

**Comment by Tiggonos** [comment]
cant confirm for order side only back is salvagable and is red for me as my skill is to low.

**Comment by DanaBloodkiss** [comment]
Fixed.
