### ISSUE TITLE
Preservation does not proc

### ISSUE THREAD

**Issue by Mercenery** [WarEmu/WarBugs#14292]
After the patch today changed  Aggravation to Preservation on the epic quest weapons does not proc. I tested it with the Ninth Peak weapon on my sw. The on being hit effect to increase wound by 72 for 20 sec does not proc when hit by an enemy.

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format.

**Comment by DillPickle420** [comment]
I ran into CW, holding the Warsong and let a bunch of mobs hit me. It never procced. I put on my conq armor (which has the +100 preservation proc) and did the same. It procc'ed every 20-25 seconds. So preservation works for conq, but not for Warsong.

**Comment by Mercenery** [comment]
If you equip conq and the weapon you have twice the same effekt. And as far as i found out it proccs the higher effekt so it is the conq one

**Comment by sioding** [comment]
answer is given - close
