### ISSUE TITLE
[Bastion] Thar'Ignan Boss

### ISSUE THREAD

**Issue by flannelok** [WarEmu/WarBugs#14296]
Left Wing Bastion Boss - Thar'Ignan
Can't be aggro after main tank is pulled in to the roots. Tryed him several times so when MT is flying he can use skils but Boss just ignore it. He switching to random player and almought insta kill him. Probably some aggro issue.

**Comment by grunbag** [comment]
That’s intended , second tank need to taunt him back , and move him away from tossed player . Rest of the group need to kill bloodsnouts ASAP

**Comment by flannelok** [comment]
Its agroed randomly, as i told taunt at this moment just not working at all, If this random think is on 2 tank its okey, other way you have just -1 dps, or -2 and+25%(for every dead person) boss heal, with 1 dps its just not impossible to do.

**Comment by flannelok** [comment]
Okey one more think we found is probably timings on knocks, its sometimes happend that he pull people to fast, we get 2 persons in roots at the same time.

**Comment by grunbag** [comment]
The punt happen every 5% so if 2 pull occurs at the same time you dps him too fast :)
Only main tank is tossed down to the pit , second tank can use taunt at this moment cause boss drop all Aggro on main tank . Make sure you have both tank on top of Aggro list

**Comment by grunbag** [comment]
It’s working as intended
