### ISSUE TITLE
Bastion Stair Scroll isn't Working

### ISSUE THREAD

**Issue by Manatikik** [WarEmu/WarBugs#14290]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**

Teleport to Bastion Stair entrance. Does not work.

**Steps to reproduce the problem:**

Try to use scroll/

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
This has been fixed it with hotfix of 03.06.2019
