### ISSUE TITLE
Bonus stat from renown ability not registering.

### ISSUE THREAD

**Issue by Rilos** [WarEmu/WarBugs#1429]
Just trained up to 3-4 trained +Initiative on my WP and it didn't show up on my character screen.  I tried relogging, but the issue persists.

Is this just not registering on the character stat screen, or are the + stats on renown ability just not being added?

**Comment by xyeppp** [comment]
Renown abilities are not fully implemented yet.

**Comment by Evildoor** [comment]
Xyeppp is correct. Patchnotes also stated: "(Renown abilities do not work yet)". Closing.
