### ISSUE TITLE
[Quest] Ogres is Stupider (Thunder Mountain/Death Peak, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14298]
The quest marker for the objective "Wastebandit Excavators" is missing.

![ogres is stupider](https://user-images.githubusercontent.com/30193675/58754751-b1f57780-84d7-11e9-9f1f-0a13ee1e2ab6.jpg)

**Comment by lilimx** [comment]
Fixed with Patch 06/08/2021
