### ISSUE TITLE
[Quest] Hot Headed (Thunder Mountain, destro) Quest needs rework

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14299]
This quest completes by talking to the quest giver again. Since quest items work now it can be restored.

![hot headed](https://user-images.githubusercontent.com/30193675/58754792-0f89c400-84d8-11e9-8563-5c6c2776987b.jpg)

**Comment by lilimx** [comment]
Fixed with Patch 06/08/2021
