### ISSUE TITLE
[NPC] Deathly Warrior (Cinderfall) NPCs don't have a nametag

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14291]
The Deathly Warriors at the position of the quest [Smashin' da Bony Stunties] do not have a name displayed above their head. They can be targeted though.

![deathly2](https://user-images.githubusercontent.com/30193675/58752328-4dbdbe00-84ad-11e9-91c2-b1c048b6526e.jpg)
![deathly3](https://user-images.githubusercontent.com/30193675/58752329-4dbdbe00-84ad-11e9-97b9-0e7c065d1258.jpg)
![deathly1](https://user-images.githubusercontent.com/30193675/58752327-4dbdbe00-84ad-11e9-8ce9-068da0ff687b.jpg)

**Comment by sioding** [comment]
fixed with patch from 10.06.2019
