### ISSUE TITLE
No rolls in Forts...

### ISSUE THREAD

**Issue by TheOGScav** [WarEmu/WarBugs#14295]
This is beginning to happen too often: 
![Bluth_005](https://user-images.githubusercontent.com/46210669/58754114-78008300-848f-11e9-9cc6-53857ecf8523.jpg)

**Comment by Jonees123** [comment]
It's just a visual bug and you wont be winning any bags on the losing side anyway.

**Comment by TheOGScav** [comment]
> 
> 
> It's just a visual bug and you wont be winning any bags on the losing side anyway.

Funny, I don't win on the winning side either...

**Comment by Jonees123** [comment]
You are rolling, just can't see it when that happens... I once won a gold bag when that happened to me.
Winners get +750 added to their rolls, while losers get +100, so it is very unlikely for majority of the winners to roll less than 100, while you roll the max 750 on the losing side.

**Comment by sioding** [comment]
This is answered. Close
