### ISSUE TITLE
[Quest] Tunnels and Trinkets (Thunder Mountain, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14301]
The quest marker for the objective "Kill Grigsnot" is missing. This is a good candidate for a multi-quest marker.

![Tunnels and trinkets](https://user-images.githubusercontent.com/30193675/58754816-98086480-84d8-11e9-8930-1f35af29874f.jpg)

**Comment by lilimx** [comment]
Fixed with Patch 13/08/2021
