### ISSUE TITLE
[Quest] Water Stunties Good Fer? (Kadrin Valley, destro) Quest item not implemented

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14308]
This quest completes by talking to the quest giver again. Since quest items are working now it can be restored.

![water stunties good fer1](https://user-images.githubusercontent.com/30193675/58755048-04389780-84dc-11e9-9633-939cd5ad05b2.jpg)

**Comment by lilimx** [comment]
Fixed with Patch 20/08/2021
