### ISSUE TITLE
[UI] Map display bug on login

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14307]
Since the patch from the 25. Mai 2019 on around 50% of my logins the map shows a black overlay on all the areas that have been discovered (fog of war removed). This usually only affects the map of the active area on login.

![map bug](https://user-images.githubusercontent.com/30193675/58755006-61801900-84db-11e9-96d9-a6f649d07eb5.jpg)

**Comment by Kaelang** [comment]
This no longer impacts the latest version of RoR. Please update your client and re-open if this issue persists.
