### ISSUE TITLE
[Quest] No Fire in the Forge (Thunder Mountain/Death Peak, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14302]
The quest marker for the objective "Find Skoragrimm's Weapon Rack" is missing.

![no fire in the forge](https://user-images.githubusercontent.com/30193675/58754833-ce45e400-84d8-11e9-896b-472e4d8ff345.jpg)

**Comment by lilimx** [comment]
Fixed with Patch 13/08/2021
