### ISSUE TITLE
[Quest] Delving in the Deep (Thunder Mountain/Death Peak, destro) Too few NPCs

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14304]
Only the "Disciples" count for this quest and there are only 5 of em. Since you need to kill 12 the multi-NPC kill workaround could be implemented here.

![Delving in the deep](https://user-images.githubusercontent.com/30193675/58754879-73f95300-84d9-11e9-8859-0a3ecaca0ac3.jpg)

**Comment by lilimx** [comment]
Fixed with Patch 06/08/2021
