### ISSUE TITLE
[Quest] Raising Chomp (Thunder Mountain, destro) Quest item not implemented

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14306]
Currently you have to kill Chomp instead of using a rope on him. I know NPC escort is not implemented yet, but not killing the Squig you have to catch is an improvement :).

![raising chomp](https://user-images.githubusercontent.com/30193675/58754973-eae31b80-84da-11e9-85da-bfb9e9fd270f.jpg)

**Comment by lilimx** [comment]
Fixed with Patch 13/08/2021
