### ISSUE TITLE
[Quest] Water Stunties Good Fer? (2) (Kadrin Valley, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14309]
The quest markers for the objectives "Pipes Destroyed" and "Pumps Destroyed" are missing.

![water stunties good fer2](https://user-images.githubusercontent.com/30193675/58755058-32b67280-84dc-11e9-81cd-4df6a1cd2bf2.jpg)

**Comment by lilimx** [comment]
Fixed with Patch 20/08/2021
