### ISSUE TITLE
[Quest] Sticks and Stones (Thunder Mountain, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14300]
The quest marker for the objective "Stonecrusher Ironguts" is missing.

![sticks and stones](https://user-images.githubusercontent.com/30193675/58754803-465fda00-84d8-11e9-9064-585afea20bc7.jpg)

**Comment by lilimx** [comment]
Fixed with Patch 13/08/2021
