### ISSUE TITLE
Unable to take quests inside Bastion Stairs

### ISSUE THREAD

**Issue by Abodam** [WarEmu/WarBugs#14317]
As Destruction:
Unable to take any quests inside Bastion Stairs (confirmed by Skorri as intended location for this) from Jodis Wolfscar. Clicking NPC and nothing happens. 

Tested by multiple people with different characters.

Only able to take quests outside - Praag 56k 2k - same npc as inside Jodis Wolfscar and able to take all quests here.

Not sure if intended or bugged.

**Comment by Hargrim** [comment]
Fixed.
