### ISSUE TITLE
Blurring shock hitting lord several dozen times/second for full dmg

### ISSUE THREAD

**Issue by silodin** [WarEmu/WarBugs#14318]
**Expected behavior and actual behavior:**
Blurring shock should hit keep lord once and apply the debuff, it instead hits several times/second for the full dmg. this only works on lords.

**Steps to reproduce the problem:**
Hit a keep lord with Blurring Shock and watch the dmg numbers fly faster than they can load on screen.

**Testing Screenshots/Videos/Evidences (always needed):**
could not get a video recording working but here is a SS with time stamps: https://gyazo.com/865ce967b5fc38bc30cc25092ece93ab

**Comment by grunbag** [comment]
i can't reproduce
