### ISSUE TITLE
[World Object] Valve moves vertically, even after correct animation is working again

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14312]
The valves needed for the quest [Water Stunties Good Fer?] move up on use, even after last weeks patch restored the original animation.

https://streamable.com/2vvn5
![water stunties good fer3](https://user-images.githubusercontent.com/30193675/58755177-7a3dfe00-84de-11e9-9e1c-3af2a6665532.jpg)

**Comment by Lheana** [comment]
See #15189 for the general issue with floating GOs.
