### ISSUE TITLE
[Quest] Architect of Fate (2) (Kadrin Valley, destro) Quest autocompletes

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14314]
This quest completes by talking to the quest giver again. I don't know if and how well this quest can be restored, if not the ticket is for future reference.

![architect of fate2](https://user-images.githubusercontent.com/30193675/58755245-13b9df80-84e0-11e9-9c58-b9945135d4ba.jpg)

**Comment by lilimx** [comment]
Fixed with Patch 20/08/2021
