### ISSUE TITLE
[Quest] Architect of Fate (Kadrin Valley, destro) Patrolling NPC not patrolling

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14313]
Okari Helmcleaver is not patrolling along with some slayers as the flavor text intends. Instead he stands alone on a rock, slightly outside of the quest marker. Since NPCs can patrol again this quest could be restored (or at least the quest marker moved a bit).

![architect of fate1 1](https://user-images.githubusercontent.com/30193675/58755222-6f379d80-84df-11e9-8d0a-c5de511770e8.jpg)

**Comment by lilimx** [comment]
Fixed with Patch 20/08/2021
