### ISSUE TITLE
[Quest] Horn Heads (2) (Kadrin Valley/Black Fire Pass, destro) Quest on wrong quest giver

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14311]
I'm pretty sure this quest should not be on a quest giver in KV (Rotnob, 59k, 55k). Quest location and turn in is in BFP and the booty is level 27 (KV is 38-40). There's also another quest with the same name in BFP, so I assume its a broken quest chain.

![Horn heads2 1](https://user-images.githubusercontent.com/30193675/58755136-cb012700-84dd-11e9-95f2-b1f7fb7f88a4.jpg)
![Horn heads2 2](https://user-images.githubusercontent.com/30193675/58755137-cb012700-84dd-11e9-8108-df8b78e363e5.jpg)
![Horn heads2 3](https://user-images.githubusercontent.com/30193675/58755138-cb012700-84dd-11e9-9d41-76053b965098.jpg)

**Comment by Lheana** [comment]
This has been fixed with the patch of 07/04/2021.
