### ISSUE TITLE
[BASTION] BloodLord Wingmantle for zealot is invisible

### ISSUE THREAD

**Issue by Navgoroth** [WarEmu/WarBugs#14319]
Shoulders for zealot have an invisible skin, and the icon of the item is a belt.

![Drudkha_002](https://user-images.githubusercontent.com/51286910/58759570-805acb80-852c-11e9-812d-4e566e8e4a52.jpg)

**Comment by grunbag** [comment]
Ok I’ll fix it for next patch

**Comment by grunbag** [comment]
Fixed already
