### ISSUE TITLE
[Bastion Stair] Zekaraz the Bloodcaller getting Instakilled by altar

### ISSUE THREAD

**Issue by Nefarian78** [WarEmu/WarBugs#14321]
**Expected behavior and actual behavior:**

Boss gets a stacking damage buff that has to be cleansed/removed by using an Altar in the middle of the room that requires skulls found inside the alcoves in the boss area. Using the altar instantly kills the boss. We picked up all the skulls first and then used the altar. Maybe it has something to do with that?

**Steps to reproduce the problem:**

Just use the altar after grabbing a skull

**Testing Screenshots/Videos/Evidences (always needed):**

Bug can be easily replicated just by clicking on the altar with a skull in your inventory. Also i didn't expect that would happen and took no evidence

**Comment by raptrr** [comment]
I've done BS last week and everything was normal, no insta gib or other strange stuff.
Put on 2 Week Ultimatum.
