### ISSUE TITLE
[Bastion Stair] Influence Gain

### ISSUE THREAD

**Issue by Jonees123** [WarEmu/WarBugs#14327]
We killed Thar'lgnan and got 2x 1k influence ticks, but ToK is only showing 1k.
![kuva](https://user-images.githubusercontent.com/47939256/58767101-656d7300-858f-11e9-8141-f0e0b85dd92d.png)
![kuva](https://user-images.githubusercontent.com/47939256/58767112-761de900-858f-11e9-863c-cb438720e7d0.png)
Same thing with mid bosses 2x 1k ticks from both of them and only 2k influence gained in total.
![kuva](https://user-images.githubusercontent.com/47939256/58783093-c1b0b100-85e8-11e9-90f1-8351720deb5b.png)
![kuva](https://user-images.githubusercontent.com/47939256/58783119-d4c38100-85e8-11e9-80ce-7de21adefe2f.png)
![kuva](https://user-images.githubusercontent.com/47939256/58783128-ddb45280-85e8-11e9-89dc-ca945c6cf01a.png)

**Comment by dalen** [comment]
You are only supposed to get 1k influence, so end result is correct. I'm not sure why log says influence twice though.

**Comment by Jonees123** [comment]
Really? It takes forever to get the last reward if that's the case.

**Comment by Jonees123** [comment]
BS takes way longer than BB/BE for example and you only gain 4k influence from all of the wings in total.

**Comment by dalen** [comment]
Yes, it will take a while. BB/BE is probably the exception of being really quick though. Much faster than Crypts & Tunnels.

**Comment by grunbag** [comment]
Bb/be is an exception , due to the small size of the dungeon . All other dungeon will be long and BB/BE can’t be the reference .
