### ISSUE TITLE
[Bastion Stair] Bloodmoon jewelry. 

### ISSUE THREAD

**Issue by Ripliel** [WarEmu/WarBugs#14322]
![BM1](https://user-images.githubusercontent.com/16005849/58762357-0f310d80-8558-11e9-9d9d-e4af812ce42e.PNG)
![BM2](https://user-images.githubusercontent.com/16005849/58762358-10fad100-8558-11e9-8d54-98145bcc5c4a.PNG)

Bloodmoon jewelry appears to be a part of Bloodlord set which, I suppose, is incorrect.

**Comment by sioding** [comment]
fixed with patch from 10.06.2019
