### ISSUE TITLE
kill Adr ta feet  not count for quest

### ISSUE THREAD

**Issue by Grobbok** [WarEmu/WarBugs#14326]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**

**Ard ta Feed has a bug that he punts you out of his contribution zone. I was there, I fought the boss, I helped kill the boss. But because I was some away from him it not count for quest. After we killed boss I still have 0/3 but I have lockout on this boss

Expected behavior and actual behavior:
I expected to get my kill contribution but instead was given nothing.

Steps to reproduce the problem:
Ard ta Feeds contribution range is smaller than his punt range. To reproduce get punted by hard to feed across the map and if he dies you don't get contribution. 

**Testing Screenshots/Videos/Evidences (always needed):**
![Grobbok_556](https://user-images.githubusercontent.com/51300118/58767080-ccd2f500-8586-11e9-856e-770268c1c814.jpg)

**Comment by Hargrim** [comment]
You need to be within 150 fr from the kill to get the quest contribution. This is expected behavior, closing.
