### ISSUE TITLE
[Bastion Stair][Influence Reward][Bloodlord Bows(SW)] Same but different?

### ISSUE THREAD

**Issue by Bejkon** [WarEmu/WarBugs#14325]
These two bows are rewards for the SW from bastionstairs, i cant seem to spot a difference apart from the name, intended?

![Bloodlord Warbow](https://user-images.githubusercontent.com/35146895/58765637-5da0d500-8575-11e9-81d0-e259872a3d01.JPG)
![Bloodlord Longbow](https://user-images.githubusercontent.com/35146895/58765648-60032f00-8575-11e9-9ac1-dc2210a64c70.JPG)

**Comment by CrimsonFenris** [comment]
Yes, shouldnt there be 2 variants like for swords ? 
One +melee -ranged, the other +ranged -armor/toughness ?

**Comment by NorKalli** [comment]
Bloodlord warbow has 3 dodge strikethrough and +2 BS and no longer has any crit

**Comment by sioding** [comment]
fixed with patch from 10.06.2019

**Comment by Bejkon** [comment]
Fixed for 1st inf tier. 

2nd inf tier Warbow still is the same as the Longbows.
