### ISSUE TITLE
[Bastion Stair][Influence Reward][Bloodlord Blade(SW)] Melee stats instead of ranged

### ISSUE THREAD

**Issue by Bejkon** [WarEmu/WarBugs#14324]
There seems to be a misshap with the Bloodlord Blade. Or ive just found one of the "fact-check-test items".

The combo of stats/proc doesnt make much sense when you compare it to the Bloodlord Falcata.

I guess stats were intended to be ranged(BS etc, see Falacata) instead of melee(STR etc). Guess based on the fact that this is the way basically all other SW weapons are designed.

If the str/melee stats are intended, the procs should be swapped. Makes little sense as it stands.

![Bloodlord Blade](https://user-images.githubusercontent.com/35146895/58764736-393ffb00-856b-11e9-9b01-f8c007703698.JPG)
![Bloodlord Falcata](https://user-images.githubusercontent.com/35146895/58764740-4e1c8e80-856b-11e9-8178-4ea530919100.JPG)
![k](https://user-images.githubusercontent.com/35146895/58764744-54126f80-856b-11e9-9186-c47c6efa4466.JPG)

**Comment by wargrimnir** [comment]
Falcata is SW weapon
Blade is SM weapon

Falcata proc is correct because SW does ranged damage. Their other stats convert when in melee stance.

**Comment by Bejkon** [comment]
should the Blade be available to pick as a SW then? THese are both options for me on the SW, same as the two, statwise identical, bows.

I dont mind if it is, as i could then stack 5+5% dmg from diffrent "procs", just seems odd still.

**Comment by grunbag** [comment]
It doesn’t stack

**Comment by Bejkon** [comment]
Thats ok.

Question is if the Blade(SM wep as per Wargs post) should even be an option for SWs at the inf reward guy in BS. If thats intended, then there is no bug. 

I guess it is as it should be judging by the issue being closed. 

Thanks for the time taken, just wanted to make sure.<3
