### ISSUE TITLE
Mount Gunbad "The Threat from Glomp"

### ISSUE THREAD

**Issue by fixfax86** [WarEmu/WarBugs#14329]
I Didnt get the Kill count from killing, "Glomp da Squig Herder" in "The Threat from Glomp".. two times even!

**Comment by Hargrim** [comment]
Do you have lockout for this boss? Can you show me screenshot of the lockout page for your character and results of the .lockout command?

**Comment by Hargrim** [comment]
And how fresh is this statement? I fixed this 2 patches ago, I hope.

**Comment by fixfax86** [comment]
Dont know.. got the gear by looting.. its just a heads up/feedbackm that it
is a little buggy.. maybe I can complete the quest later!

Den man. 3. jun. 2019 kl. 18.03 skrev Hargrim <notifications@github.com>:

**Comment by raptrr** [comment]
@fixfax86 were you able to complete it by now?

**Comment by fixfax86** [comment]
yes, but it happens once in a while that I/one dont get a tick from a kill!
