### ISSUE TITLE
Caledor Keep "Hatred's Way" is rebuilding it's door too fast

### ISSUE THREAD

**Issue by rekkir** [WarEmu/WarBugs#14332]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**

Expect doors to remain down for more than 10 minutes. it was rebuild after killing oil twice, I estimate 10-15 minutes.

No supplies were run in as we had surrounded them and were ifghting on both postern and main door.

**Steps to reproduce the problem:**

Not sure how. But this is not seldom, it happens actually more often than not on this keep. So I suggest tracking this keep in particular since it seems to have issues.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by sioding** [comment]
This is not a keep problem. If you don't manage to attack the inner door after the outer one is down - AND the defenders get ressources through your attacker line - well then the door will be up again. Seems like ONE ressource came through your line. So this is a design decision. If you want some changes for it - make a suggestion thread in our forum.
