### ISSUE TITLE
[Quest] T3 epic Will of the Warboss

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#14336]
Find Boom Powder - 0/10 step.
Boom Powder only spawns at stage 2 of hard PQ Kolaz Umgal.
and also part of stage 2 objective.
to open stage 2 you have to kill 85 npc.
it's actually more hard and time consuming than t4 epics.
i think it's difficulty is bugged.

**Comment by sioding** [comment]
TBH: I leave this open - BUT its not a bug. May @Lheana or @Kabucoror decide what todo.
