### ISSUE TITLE
Lost Temple of Isha SC Quest

### ISSUE THREAD

**Issue by Zoggof** [WarEmu/WarBugs#14331]
Quests asks to kill an unknown NPC. I've abandoned the quest twice and retaken it and I still get it the same quest asking to kill 'Eacraka.

![Untitled141](https://user-images.githubusercontent.com/23256143/58802295-23f0cc80-8650-11e9-8e19-4b7bab5b4550.png)

**Comment by sioding** [comment]
fixed with patch from 10.06.2019
