### ISSUE TITLE
[Quest][BASTION] The threat from Thar'Lgnan

### ISSUE THREAD

**Issue by Koinzzell** [WarEmu/WarBugs#14333]
**Expected behavior and actual behavior:**
This quest is suppose to give as reward the highmantle of bloodlord OR a Dye but currently for ArchMage the highmantle is not as rewards

**Steps to reproduce the problem:**
Take the quest as AM

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/51057710/58818068-7f5d9300-862d-11e9-8661-f35002976f9d.png)

**Comment by sioding** [comment]
fixed with patch from 10.06.2019
