### ISSUE TITLE
Ostland ToK - Loathsome Rat Men

### ISSUE THREAD

**Issue by Silveravo** [WarEmu/WarBugs#14330]
ToK unlock Loathsome Rat Men in Ostland 51,8k 51,8k is impossible to do. Skaven is visible, it gets highlited as an item when unminimizing game, but it's simply uncklickable. I tried to do it from different angles, using different cameras, but it's simply broken. 

I know it's small thing, but resolving it should be very simple, and I personally love ToK unlocks, so I decided it's worth writing about. 

![Silveravo_019](https://user-images.githubusercontent.com/51322873/58799677-36deaf00-8606-11e9-9e0d-c1297af5e926.jpg)
![Silveravo_012](https://user-images.githubusercontent.com/51322873/58799678-37774580-8606-11e9-92e0-93f520fdf95d.jpg)
![Silveravo_013](https://user-images.githubusercontent.com/51322873/58799679-37774580-8606-11e9-8565-dfa6735a9d9f.jpg)
![Silveravo_014](https://user-images.githubusercontent.com/51322873/58799680-37774580-8606-11e9-8bdc-0bbe2e175605.jpg)
![Silveravo_017](https://user-images.githubusercontent.com/51322873/58799684-380fdc00-8606-11e9-9bfe-1b54d1048621.jpg)
![Silveravo_018](https://user-images.githubusercontent.com/51322873/58799685-380fdc00-8606-11e9-979d-ba26f98382d9.jpg)

Thank you for your effort to make this game greater every time I come around to check on it.

**Comment by Lheana** [comment]
Thanks for the report. You will be able to click on it again with next patch.

**Comment by sioding** [comment]
fixed with patch from 10.06.2019
