### ISSUE TITLE
[ORvR] Debug spam before zone lock

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14338]
When a zone is about to lock the chat suddenly gets spammed with an error message (see screenshot). I'm not 100% sure, but I think this happens when all four BOs are taken by the locking faction, instead of just the required three. From the time stamp you can see it happens multiple times per second.

![Balver_000](https://user-images.githubusercontent.com/30193675/58837917-4ccb8e80-865d-11e9-9449-889786f7eb9c.jpg)

**Comment by Natherul** [comment]
Next patched I moved some code around to hopefully get rid of this message. We will close ticket on next patch but if it happens again please post back here and we will reopen it

**Comment by sioding** [comment]
Fixed with patch from 03.08.2019
