### ISSUE TITLE
Choppa Pull

### ISSUE THREAD

**Issue by synthrocker** [WarEmu/WarBugs#14342]
GTDC seems to not place immunity, can be pulled multiple times while in air, also is undefendable.

**Comment by sioding** [comment]
"Seems to" is not enough fpr this bugtracker sorry. Please provide as much evidence as you can give - that includes screen/videos or whatever that helps the dev to get the problem and reproduce it. Thanks.

**Comment by Parallell86** [comment]
its common knowledge that vhoppa pull is undefendable, and doesnt trigger immunity. choppa pull, plus endless zealot punt + marauder pull, since the marauder pull is the only thing triggering immunity Im afraid.. yepp. work as intended.

**Comment by sioding** [comment]
Correct - answer given - close

**Comment by Parallell86** [comment]
Bullshit.

Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows 10

________________________________
Från: Alexander Eckert <notifications@github.com>
Skickat: Wednesday, June 5, 2019 7:39:41 AM
Till: WarEmu/WarBugs
Kopia: Parallell86; Comment
Ämne: Re: [WarEmu/WarBugs] Choppa Pull (#14342)


Correct - answer given - close
