### ISSUE TITLE
[Quest] Show Em' Who's Boss (Kadrin Valley, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14348]
The quest marker for the objective "Battlegut Bulls" is missing.

![show em whos boss](https://user-images.githubusercontent.com/30193675/58964735-ae037700-87af-11e9-9977-8a818c09c409.jpg)

**Comment by Rockalypse** [comment]
Will be fixed next patch

**Comment by Natherul** [comment]
should be fixed as of today
