### ISSUE TITLE
Supplies bugged at Sanctuary of Dreams - Eataine

### ISSUE THREAD

**Issue by SATANICOMODERNO** [WarEmu/WarBugs#14346]
The Sanctuary of Dreams in Eataine generates all supply boxes inside the wall and the invisible prim next to the wall which doesn't allow us to take the supplies.

![image](https://user-images.githubusercontent.com/14305777/58925252-3d137f00-871d-11e9-91fb-5f0461912351.png)

**Comment by sioding** [comment]
Duplicate of #14274
