### ISSUE TITLE
[Quest] Chariots Aflame (Kadrin Valley, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14349]
The quest marker for the objective "Burning ember" is missing. Also, the carts can be set aflame before getting the ember.

![chariots aflame](https://user-images.githubusercontent.com/30193675/58964914-fae74d80-87af-11e9-8156-332584be2c15.jpg)

**Comment by Rockalypse** [comment]
Will be fixed next patch.

**Comment by Natherul** [comment]
should be fixed as of today
