### ISSUE TITLE
Character Gold Bag bugged

### ISSUE THREAD

**Issue by lucaoc** [WarEmu/WarBugs#14341]
my character is bugged, I got 3 golden bags since renowm 52 and the 3 came exactly the same piece, please check it out for me if it's not bugged, it's very frustrating.

Character : Jorginho (White Lion 58)
thankful

**Comment by sioding** [comment]
We all face that "thing" called RNG:
https://www.random.org/analysis/dilbert.jpg

Since this is a global system there is no chance for one character being "bugged". Close
