### ISSUE TITLE
Bolstering in Gunbad

### ISSUE THREAD

**Issue by Araniya** [WarEmu/WarBugs#14345]
I didn't find any report about this and just wanted to let you know. I was in Gunbad after last Hotfix and it seems like Bolstering didnt work how it should be. 2 partymembers were 31+ the rest were 40 and those two didnt get bolstered. Sorry for my bad english.

**Comment by Hargrim** [comment]
Possibly visual bug. Could you do .getstat before and after entering Gunbad and show us the results here?

**Comment by Araniya** [comment]
Sorry I cant cause it was random party and I´m lvl 40.

**Comment by Skarx** [comment]
Hello,

I did Gunbad yesterday and I had the same issue with the bolster (lvl 32). 

I actually had the correct stats (in my char sheets I had around 850 toughness) but the NPCs were hitting me for around 15k to 20k damages. Sometimes it was written 40 on my character portrait, but it disappeared when entenring a public quest (I still had the stats in the char sheets though).

I was also unable to hit any mobs above lvl 41 (they were blocking everything) and I was doing little to no damages to others.

I guess it could be some damage scalability that wasn't working properly on the bolster ? (I asked the other tank what he had in combat log, and it was maybe around 1k damages for the same skills the NPCs used)


I hope it helps
Best regards

**Comment by Mercenery** [comment]
Problem still exist. Did it yesterday with my lvl 31 bo. I was debolstered to lvl 23. Cant hit most the mobs cause they blocked all my skills.

**Comment by sioding** [comment]
fixed with patch from 10.08.2019

**Comment by Wraythbw** [comment]
Went in to attempt Gunbad on Tuesday 8/13/2019. The Bolster was boosting me to 40. Bolster was only working partially. Targets that were level 40 were able to be hit without a problem. Any NPCs lvl41 were about 50% chance whether they would be block or not. LVL42 NPC's were 100% block. Still an active issue with Bolster that needs looked into. Will try to get SS's on my next attempt.
