### ISSUE TITLE
Fortress Population

### ISSUE THREAD

**Issue by Ripliel** [WarEmu/WarBugs#14344]
Fort from a week ago.
![no aoo2](https://user-images.githubusercontent.com/16005849/58918054-6211ed00-8731-11e9-9e3d-3f09834136e5.PNG)
Most recent fort.
![aao2](https://user-images.githubusercontent.com/16005849/58918056-62aa8380-8731-11e9-8a0b-a539b9dd37ab.PNG)
![no aao](https://user-images.githubusercontent.com/16005849/58918059-65a57400-8731-11e9-9db3-7ef841a8962b.PNG)

It's happened several times that defenders didn't get AAO and pop numbers were quite close. 

Might be something wrong with numbers so more defenders get inside or less attackers can join the fort.

**Comment by sioding** [comment]
Sorry but you will never be able to see real numbers because of hidden and anon players. Be sure nearly every fort has a staff member in it who checks the numbers. They are OK.

**Comment by Natherul** [comment]
As sio stated a player who is not member of staff wont see the correct data.

Also there are cases where we cannot enforce the pop with 100%, one such example is where when there is the right pop and then attackers disconnect and nobody rejoins.

In my personal experiences with fort pops there is no issue.
