### ISSUE TITLE
[Quest] Unleash the Waaagh! (Kadrin Valley, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14347]
The quest marker for the objective "Kill Gamni Steelshot" is missing.

![unleash the waaagh](https://user-images.githubusercontent.com/30193675/58964583-74cb0700-87af-11e9-8755-416743c2ee61.jpg)

**Comment by Rockalypse** [comment]
Will be fixed next patch

**Comment by Natherul** [comment]
should be fixed as of today
