### ISSUE TITLE
Tor Anroc (and prbly. Mourkain): out of combat with orb

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#1434]
when you have the orb you should never get out of combat.

**Comment by ozarmidrashim** [comment]
How is it possible to get out of combat with the orb? It deals damage to you at intervals.

**Comment by Evildoor** [comment]
It is possible. Orb deals damage, but it does not puts you in combat.

**Comment by ozarmidrashim** [comment]
Damn, yeah - it's precalculated damage. I'll fix it.
