### ISSUE TITLE
[NPC] Smoky (Kadrin Valley) Surrounding NPCs are hostile

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14352]
Smoky, the boar needed in the quest [A Litl' Smoky], gets killed by the surrounding NPCs upon spawn. To complete the quest you have to wait for respawn and keep the spearman off of him.

![a lil smoky](https://user-images.githubusercontent.com/30193675/58965614-29195d00-87b1-11e9-9838-761d30a8116d.jpg)

**Comment by sioding** [comment]
fixed with patch from 10.06.2019
