### ISSUE TITLE
[Quest] Prize of War (The Blighted Isle, destro) Quest breaking bug

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14353]
The Moonwidow Necklace can be looted before doing the first two objectives, however it does not count towards the third quest objective since they have to be done in order. The chest can't be looted a second time, so the quest has to be cancelled and restarted.

![prize of war](https://user-images.githubusercontent.com/30193675/58966140-063b7880-87b2-11e9-862e-48103a9fb1c5.jpg)
![prize of war2](https://user-images.githubusercontent.com/30193675/58966141-063b7880-87b2-11e9-8f99-72875b53dfa0.jpg)

**Comment by Lheana** [comment]
This is quite intended. You must loot the key before being able to open the chest, and thus loot the Necklace. You can loot it even after, but you just have to wait for the GO to reset. The only issue is you can click on the GO to loot it before having the key.

**Comment by Lheana** [comment]
I close this as we are already aware of it, and can not fix it yet.
