### ISSUE TITLE
echoes from the present

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#14359]
t2 high elf epic quest "echoes from the past" cannot progress beyond its first stage - killing the quest enemy drops the quest item but does not credit the kill
![bug](https://user-images.githubusercontent.com/16922842/59022179-29633800-8845-11e9-8468-278e9f7d9f1f.png)

**Comment by Lheana** [comment]
Were you grouped when you killed them? If yes, then try again without being grouped.

**Comment by MightyPhred** [comment]
i vaguely recall trying to assemble a gunbad team this morning so i probably was grouped at the time, now im not and the kill credit works
