### ISSUE TITLE
[rvr] keep lord self destructing / crash

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#14357]
![Chimp_051](https://user-images.githubusercontent.com/17765890/59008868-e9dc2200-882b-11e9-8d98-6dbb7c4b9da5.jpg)
..and him disappeared. 
After something like 15 mins doors went up automagically while the keep lord was still missing.

**Comment by Natherul** [comment]
this is an old issue that does not apply as the cause of that appearance has been fixed.
