### ISSUE TITLE
[NPC] Naked NPC

### ISSUE THREAD

**Issue by Slaynot** [WarEmu/WarBugs#14351]
Seems like the Royal Quartermaster at the RvR token NPCs in Altdorf (20100, 49500) was stripped of her clothes last patch.

She might catch a cold if nothing is done !

![Capture](https://user-images.githubusercontent.com/29149033/58965125-5b768a80-87b0-11e9-8bc4-252f2beedb66.JPG)

**Comment by Lheana** [comment]
This is just visual and unconstant issue. Sometimes you see the NPC naked, if you leave and come back they will be dressed again.
