### ISSUE TITLE
IB Bloodlust weapon from city dungeon influence

### ISSUE THREAD

**Issue by funnytroll** [WarEmu/WarBugs#14361]
No proc or you delete from IB weapon,because my kotbs have  analog weapon and it with proc?
https://imgur.com/ngPOV7R

**Comment by Esperflame** [comment]
I also noticed Bloodlust's Proc is just gone. It used to say something like 10% on being hit: Lifesteal 150.

**Comment by SecretsOTheP** [comment]
Fix pending, someone made a typo!

**Comment by sioding** [comment]
fixed with patch from 29.6.2019
