### ISSUE TITLE
[Quest] Destruction from within (Chaos Wastes, destro) Quest broken

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14365]
This quest has no quest markers and you get no quest item.

![destruction from within](https://user-images.githubusercontent.com/30193675/59108738-e9cb4780-893b-11e9-8c23-4b81452452c5.jpg)
 Its also not assigned to a zone.
![zones](https://user-images.githubusercontent.com/30193675/59108750-edf76500-893b-11e9-8440-aaa55fa5c579.jpg)

**Comment by Natherul** [comment]
fixed as of patch just now
