### ISSUE TITLE
[Quest] Meat of the Matter (Chaos Wastes, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14363]
The quest marker for the objective "Find Glyph of Quyl-Isha" is missing.

![meat of the matter](https://user-images.githubusercontent.com/30193675/59108465-35312600-893b-11e9-9931-900751410cbb.jpg)

**Comment by Rockalypse** [comment]
Seems that quest objectives and markers were redone at some point. Closing this one.
![meat](https://user-images.githubusercontent.com/42712833/72217351-bf7ae180-353d-11ea-9615-7140ce8b9c35.PNG)
