### ISSUE TITLE
[Quest] Eye of da bear (Praag, destro) Assigned to wrong zone

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14367]
This quest is assigned to Chaos Wastes, but it takes place in Praag. It also has no quest marker.
Also, it should have a travel quest icon.

![eye of da bear](https://user-images.githubusercontent.com/30193675/59109106-bccb6480-893c-11e9-9ebb-e7dcc14b2b25.jpg)
![zones](https://user-images.githubusercontent.com/30193675/59109108-bccb6480-893c-11e9-91e7-c7ac2387b998.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

was half done

**Comment by sioding** [comment]
fixed with patch from 10.06.2019
