### ISSUE TITLE
[Quest] All Stomped Out (High Pass, destro) Quest marker missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14362]
The quest markers for the objectives "Bonestomper Butcher's Head" and "Kill Bonestomper Tainted" are missing.

![all stomped out](https://user-images.githubusercontent.com/30193675/59108369-fe5b1000-893a-11e9-9156-ecad0508940c.jpg)

**Comment by Rockalypse** [comment]
Will be fixed next patch.

**Comment by Natherul** [comment]
should be fixed as of today
