### ISSUE TITLE
[Quest] In da Sky (Reikland, destro) Quest marker and zone assignement missing

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14366]
This quest has no Quest marker and it's not assigned to a zone. It should also have a travel quest icon.

![in da sky](https://user-images.githubusercontent.com/30193675/59108881-3e6ec280-893c-11e9-87ea-faacc3269f15.jpg)
![zones](https://user-images.githubusercontent.com/30193675/59108882-3e6ec280-893c-11e9-88b3-8ea65eb7b137.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 10.06.2019
