### ISSUE TITLE
"Kill players" quests are ignoring kill locations

### ISSUE THREAD

**Issue by Rilos** [WarEmu/WarBugs#1436]
Park your character on owned keeps with the quest to defend the keeps from the keep lord and you will fill up the kill count while inside of a scenario.

**Comment by Evildoor** [comment]
You don't need to park yourself anywhere. For now, all the quests "kill enemy players" count ANY player kills made anywhere.

**Comment by Evildoor** [comment]
Fixed in T4 patch.
