### ISSUE TITLE
Gunbad, missing item

### ISSUE THREAD

**Issue by pawel2001** [WarEmu/WarBugs#14378]
Hello,
I was with the Gunbad team today, we made the middle wing, we killed the last boss, the last boss dropped 2 sets items, one for the archmage and one for the witch hunter, the witch hunter got his thing, no, everyone in the team used the pass option. I am asking for help in my case. I attach a photo confirming the killing of the boss.
ps. I also used the option of creating an appeal in the game (CSR appeal) I do not know if it works or not.
![Erfe_011](https://user-images.githubusercontent.com/51489596/59120780-961a2780-8956-11e9-879a-244b1c7b33ce.jpg)

**Comment by Kaelang** [comment]
The staff team do not perform item recoveries. Your screenshot also doesn't identify what happened with the item, for example rolls and who should've been granted said item.

**Comment by Kaelang** [comment]
The Gunbad Rework has concluded, please re-open a new ticket if future issues persist.
