### ISSUE TITLE
[Quest] [World Object] Altar in Praag falsely offering a quest

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14372]
The altar in the Praag destro warcamp is offering the quest [Chosen]. This quest is part of a quest chain in Troll Country and should not be offered here.

![Drachdon_016](https://user-images.githubusercontent.com/30193675/59110030-81319a00-893e-11e9-8945-a336490a89c5.jpg)
![Drachdon_017](https://user-images.githubusercontent.com/30193675/59110032-81319a00-893e-11e9-92b3-0af28c4109f5.jpg)

**Comment by sioding** [comment]
fixed with patch from 10.06.2019
