### ISSUE TITLE
[Quest] Falling Stars (Praag, destro) Quest marker switched

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14377]
The quest markers for "Kill Yegor Kovalyof" and "Kill Tankred Paine" are switched.

Side note: Is it possible to give "Kill Nogora Stonebender" one of these "inside cave" quest markers? The current marker is a bit misleading.

![falling Stars](https://user-images.githubusercontent.com/30193675/59111139-b7701900-8940-11e9-915d-508fbc6159d4.jpg)
![falling stars2](https://user-images.githubusercontent.com/30193675/59111140-b7701900-8940-11e9-8127-9ad5557ffd5b.jpg)

**Comment by Lheana** [comment]
The quest markers will be corrected with next patch, and a cave quest marker, set ;)
