### ISSUE TITLE
scenario group issues in/out of party

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#1437]
HI, I noticed some concerns when using the scenario party interface.. I don't know if it's client/server etc.

If you join the scenario and join a party and leave a party multiple times (or on occasion) that you can show on the GUI as in party but not be in the party (eg no party effects working).

steps to recreate
join sc
join sc party via interface window
leave and join different parties mid scenario

different factors are probably involved in getting stuck 'out' of party, not able to join a party is the result in the scenario.

**Comment by Evildoor** [comment]
Hmmm. So far i've only observed the opposite effect - that you exist in scenario party, you get group heals/party buffs, you can be guarded, but you are not shown in party frames - therefore, it is difficult for your party to notice your hp being low or target you. This can be done by joining the scenario party which gets full after you clicked "Join" button but before you actually joined it.

**Comment by Tesq** [comment]
it can happen even if you leave partys ( being guarded may be the cause) and start a new sc, seems bit better after last party fix btw.

**Comment by gittoaster** [comment]
also just some notes about this.  I've noticed this behavior don't know if it's related or not..

join rvr warband 
take sc
zone 0 is the result

In scenario, as Evildoor mentions the cause seems to start in joining a full party, or maybe some lag/latency when 2 or more people join the last slot at the same time?

maybe same thing happens in both rvr wb and sc party?

best
