### ISSUE TITLE
RP Absorb Taktik without animation ;(

### ISSUE THREAD

**Issue by domi23072015** [WarEmu/WarBugs#14385]
Hello. The tactic at Rp Absorb. Unfortunately, without animation. The Zelo comes with a red bubbel every Proc. Unfortunately, nothing at rp. Except the buff in the bar

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 29.6.2019

**Comment by domi23072015** [comment]
Is not work...

**Comment by grunbag** [comment]
Wait for next patch

**Comment by domi23072015** [comment]
thanks ;)
