### ISSUE TITLE
[Item][Armor] Vanquisher Chewtop (SH) tooltip has some stray text

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14384]
The marked text in the picture should not be there I think.

![Quillog_000](https://user-images.githubusercontent.com/30193675/59152599-9c3c0100-8a47-11e9-97ce-370c948d446c.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 10.06.2019
