### ISSUE TITLE
Stuck in falling motion

### ISSUE THREAD

**Issue by fixfax86** [WarEmu/WarBugs#14380]
My character "Frendir" is stuck in falling motion at Thunder Mountain near Warcamp! can I get a Griffon Mount Token for that?

**Comment by Lheana** [comment]
No.
And you need to be more precise about where you are stuck. Also I am not sure here is the place for what you need, if you want someone to take you out of there.

**Comment by sioding** [comment]
I moved that guy to a safe place - next time let him open the bugreport with a screen from the stuck place maybe we can do something against it. And for sure get no mount token for it.

**Comment by fixfax86** [comment]
okay, I have installed an Coordinates addon now.. thats practical.. what
kind of bug does it take to get a Griffon mount Token?

Den lør. 8. jun. 2019 kl. 13.33 skrev Alexander Eckert <
notifications@github.com>:
