### ISSUE TITLE
DWARF STORYLINE CH5 PQ - Axerust Peak

### ISSUE THREAD

**Issue by Tibdum** [WarEmu/WarBugs#14386]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**

2nd Stage of PQ is not working, Cannot interact with the Altars. They have 0 HP and they are not attackable.

**Steps to reproduce the problem:**

Tried to attack them from different angles, interact with them from different angles and nothing happens. 

**Testing Screenshots/Videos/Evidences (always needed):**
![Tibdum_578](https://user-images.githubusercontent.com/47664666/59155546-74bf5580-8a94-11e9-830d-3a1ca62e39c9.jpg)

**Comment by sioding** [comment]
Fixed with patch from 15.06.2019
