### ISSUE TITLE
Improved Flee

### ISSUE THREAD

**Issue by Lefze** [WarEmu/WarBugs#14389]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**

Level one increases duration by 5 seconds, level two makes it not drop all your AP.

Neither of these work, but they are still shown in the trainer window and speccable.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by grunbag** [comment]
i need to know if it has been removed intentionally

**Comment by wargrimnir** [comment]
Yes, there are several renown abilities that were intentionally left unimplemented. This is one of them.

**Comment by sioding** [comment]
Please check our wiki - and you can see which of them are working and which not
