### ISSUE TITLE
Bastion Stairs Skull Lord Var'ithrok

### ISSUE THREAD

**Issue by panodill** [WarEmu/WarBugs#14383]
**Expected behavior and actual behavior:**
I expected to get kill credit even if punted when he died. I did not get kill credit on quest, but got loot from boss

**Steps to reproduce the problem:**
Be knocked away when he gets killed

**Testing Screenshots/Videos/Evidences (always needed):**
https://i.imgur.com/2YBfNUP.jpg

**Comment by funnytroll** [comment]
Today do full run,after kill Skull Lord Var'ithrok dont get influence,loot,quest progress
May be because lag happened,dont know

**Comment by Tosher85** [comment]
I have the same issue. Did 4 full runs all quests are comleted except this one.
