### ISSUE TITLE
A Lords' Game: Step 17, quest item does not drop

### ISSUE THREAD

**Issue by MrRedKnox** [WarEmu/WarBugs#14387]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**
It is expected to drop the head of Harbringer Evriel. But she does not drop it.

**Steps to reproduce the problem:**
Killing her does not make the item drop.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
Just tested it, the head correctly drops. Be sure not to be grouped, as the other player may have looted it.
![Anaehll_163](https://user-images.githubusercontent.com/11537611/59192204-022ca380-8b82-11e9-8012-0a90edc58650.jpg)

**Comment by MrRedKnox** [comment]
I just got it as well. Seems like she only drops one head! Sorry for the false alarm. 

Thanks for looking into it! <3
