### ISSUE TITLE
High Elf T3: Avelorn PQ Ritual of Corruption Bug

### ISSUE THREAD

**Issue by MrStretchz** [WarEmu/WarBugs#14398]
Hi, 

For this public quest, On Stage 3 you need to "Destroy the Alter of the Bloodfury" upon clicking it, the alter breaks but the PQ doesn't update to say you destroyed it and makes it impossible to complete the PQ.
![Alter](https://user-images.githubusercontent.com/51711908/59284393-147f0e00-8c64-11e9-9aa1-d4503d4055d1.JPG)

**Comment by sioding** [comment]
Fixed with patch from 15.06.2019
