### ISSUE TITLE
zealot's Tzeentch's Talon not working and Storm of Ravens

### ISSUE THREAD

**Issue by zoso85** [WarEmu/WarBugs#14396]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**
Storm of Raven is not doing the damage as intended, if you look at the screenshot, i have to crit 3 times to get close to the intended damage  i know Wargrimmir commented on #13936  and I quote (4 times is correct. The tooltip value may not be correct, but we do try to get close, which it seems to be.)  I dont know what figure is close but 498 and 666 difference is not close.

Secondly Tzeentch's Talon's debuff of Armor and resistance is not activating even thought the icon is visible as you can see in the after screenshot. But if you look at the damage done while the icon is active and 2.4 sec to go, the damage is the same as not having it on.

![before](https://user-images.githubusercontent.com/50939158/59257591-93cb0c80-8c79-11e9-90a9-9980d159dd1e.jpg)
![after](https://user-images.githubusercontent.com/50939158/59257592-93cb0c80-8c79-11e9-9313-9c2d201b4567.jpg)

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by wargrimnir** [comment]
Target dummies don't have armor or resistance.
