### ISSUE TITLE
[Ability] "Vortex", the granted skill of a Zealot's Mark of the Vortex shows a wrong range

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14394]
The skill the skill hits targets 30 feet around the player, but the range shows 100 feet like on a targeted skill.

![Quillog_000](https://user-images.githubusercontent.com/30193675/59238856-d9e38a00-8bff-11e9-827c-9715b948c1eb.jpg)

**Comment by grunbag** [comment]
100 is range 
30 is radius 

Those are 2 different things

**Comment by Moragor** [comment]
I know, but this skill does not have a range. The ability activates on the player character, its not a targeted skill.

**Comment by grunbag** [comment]
fixed
