### ISSUE TITLE
[Quest] Spoils of War (Nordland, destro) Quest needs investigation

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14393]
This quest completes by talking to the quest giver again. However, the really strange part is that you get a Griffonslayer's Mantle by **accepting** the quest. I don't think this is intended.

![Moragor_000](https://user-images.githubusercontent.com/30193675/59238557-e87d7180-8bfe-11e9-8d94-0dea5d7cb5eb.jpg)
![Moragor_001](https://user-images.githubusercontent.com/30193675/59238558-e9160800-8bfe-11e9-9ede-b1ccc7579313.jpg)

**Comment by sioding** [comment]
Fixed with patch from 15.06.2019
