### ISSUE TITLE
[Map/Area] Stuck point outside Nordland RvR warcamp (destro)

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14392]
Right west of the the camp is a point that can get you stuck without a chance to escape other than 2x /stuck.

![Krillit_002](https://user-images.githubusercontent.com/30193675/59238401-48bfe380-8bfe-11e9-8647-dcb54c67a724.jpg)
![Krillit_003](https://user-images.githubusercontent.com/30193675/59238402-48bfe380-8bfe-11e9-9eb6-8cf3713d55a6.jpg)

**Comment by sioding** [comment]
fixed with patch from 22.6.2019
