### ISSUE TITLE
[Bastion Stair] Bloodlord Set Bonuses are wrong.

### ISSUE THREAD

**Issue by XmatXergon** [WarEmu/WarBugs#14403]
**Expected behavior and actual behavior:**
Bloodlord Bonuses for Knight should not contain Ranged stats.
Bloodlord Bonuses for Engi should not contain Inteligence.
Bloodlord Bonuses for RP should not contain Melee stats.

**Steps to reproduce the problem:**
N/A

**Testing Screenshots/Videos/Evidences (always needed):**
Knight:
![bloodlord_knight](https://user-images.githubusercontent.com/37849311/59350699-07722580-8d1d-11e9-9fff-b27cc5abf435.png)
RP:
![bloodlord_rp](https://user-images.githubusercontent.com/37849311/59350703-0a6d1600-8d1d-11e9-9d87-50ff05eed4a7.png)
Engi:
![bloodlord_eng](https://user-images.githubusercontent.com/37849311/59350801-4607e000-8d1d-11e9-8a17-58091bc9847b.png)

**Comment by wargrimnir** [comment]
Starting to feel like someone is intentionally making more work for me

**Comment by wargrimnir** [comment]
Fixed with the patch
