### ISSUE TITLE
[Bastion Stair] Bloodlord Weapons wrong bonus.

### ISSUE THREAD

**Issue by XmatXergon** [WarEmu/WarBugs#14404]
**Expected behavior and actual behavior:**
Ranged weapons should increase range damage not melee for Engineer.
This is wrong for Engineer, Shadow Warrior and Squig Herder.
For Shadow Warrior and Squig Herder there should be 2 types of weapons one for Melee one for Range.

**Steps to reproduce the problem:**
N/A

**Testing Screenshots/Videos/Evidences (always needed):**
![bloodlord_weap_eng](https://user-images.githubusercontent.com/37849311/59350963-9b43f180-8d1d-11e9-95e4-a62ddded0db8.png)

**Comment by gittoaster** [comment]
Same problem with 2 AM weapons Bloodlord Windstaff (2 identical rewards)

**Comment by Ysaran** [comment]
Just noticed that 2 out of 4 choppa's bloodlord weapons have same bonus, is this intended?
![Zputakatarro_040](https://user-images.githubusercontent.com/47554048/61984107-432e2980-b003-11e9-94f7-7d2876ce41b2.jpg)
![Zputakatarro_039](https://user-images.githubusercontent.com/47554048/61984114-4d502800-b003-11e9-8880-6f5c384220dc.jpg)

**Comment by grunbag** [comment]
Yes, this is to give you the opportunity to take twice the same weapon
