### ISSUE TITLE
quest reward disrepancy

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#14402]
the quests "devoted" (order) and "to the hunt!" (destro), both repeatable quests from chapter 7 in the realm respective chaos zones are giving different dye-rewards, the order quest offers a choice of four grey-quality dyes, whereas the destruction quest offers a choice of 2 green-quality and 2 grey-quality dyes, in spite of the fact that they have the same names, the dyes are different colours, and i think that quest may actually be the only reliable source of the grey quality dyes in the entire game (so just to make sure, im suggesting that the destro quest be changed to 4 grey quality dyes, which i personally think are better than the green quality ones it currently offers)
![ssss (1)](https://user-images.githubusercontent.com/16922842/59331850-ceba5800-8cec-11e9-8d80-1e773165e50a.jpg)

**Comment by sioding** [comment]
fixed with patch from 19.10.2019
