### ISSUE TITLE
[Quest] The Sacellum Dungeons

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#14401]
Last stage of quest tell you to find and talk to Nurgling inside middle instance.
Norgling that is there has different name and talking with him does not check quest.
![quest1](https://user-images.githubusercontent.com/42712833/59325669-9b77c900-8cec-11e9-9747-2b878b996a7d.PNG)
![quest2](https://user-images.githubusercontent.com/42712833/59325671-9ca8f600-8cec-11e9-9b31-d673fc1cdd4a.PNG)
![Veszal_089](https://user-images.githubusercontent.com/42712833/59325677-a29ed700-8cec-11e9-8653-09aa2c8b35f5.jpg)

**Comment by Lheana** [comment]
You don't have to talk to a Nurgling, but to the NPC you have already talked to before for this quest line, inside the arena.

**Comment by Rockalypse** [comment]
@Lheana than it seems that marker on map is wrong, as you take it in left, not bottom dungeon.
