### ISSUE TITLE
Ward fragment tasks in ToK are outdated & inaccurate

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#14406]
**Expected behavior and actual behavior:**

The tasks listed in ToK should reflect what's actually needed, but instead they contain outdated tasks that never get ticked off.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

This is for an unlocked fragment (slightly brighter green):

![Lotharic_211](https://user-images.githubusercontent.com/7400/59353358-1360e600-8d23-11e9-9f56-1c1a6d20bf32.jpg)

**Comment by Natherul** [comment]
was already fixed yesterday but needs client push. Code got in early to fix another backend thing.

**Comment by Scophis** [comment]
![wards](https://user-images.githubusercontent.com/40274248/59564844-da3eb380-904b-11e9-9ec4-507191bdccc6.jpg)
the new requirements are in, but some old "relics" seem to be still around

**Comment by sioding** [comment]
Fixed with patch from 15.06.2019

**Comment by Scophis** [comment]
My screenshots are from today 16.06.

**Comment by Natherul** [comment]
please open a new ticket on it because its not directly related. However this is something that I have not found where its stored yet so its not going to be fixed right now.

**Comment by Scophis** [comment]
done
