### ISSUE TITLE
T2 EMP WP influence reward has wrong crit stats

### ISSUE THREAD

**Issue by xaraxdestr** [WarEmu/WarBugs#14407]
The first T2 influence rewards for a WP has the crit stats mixed up. heal gloves have melee crit and melee gloves have heal crit.

![Dirtytwohander_001](https://user-images.githubusercontent.com/45398873/59368578-e02c5000-8d3e-11e9-83d4-d5a3a1282561.jpg)
![Dirtytwohander_000](https://user-images.githubusercontent.com/45398873/59368579-e02c5000-8d3e-11e9-8082-195d7358038c.jpg)

**Comment by wargrimnir** [comment]
90% sure it was like that on live. Feel free to dig up that corpse to show otherwise.

**Comment by dalen** [comment]
yup, a remnant from the time when Mythic thought that just splitting stats into two different styles of play would make it valid hybrid spec gear.

**Comment by sioding** [comment]
answer is given - close
