### ISSUE TITLE
[Bastions Stairs] BW gloves missing stats

### ISSUE THREAD

**Issue by BomblingTV** [WarEmu/WarBugs#14400]
The Brightwizard Bloodlord gloves seem to have a line of stats missing. Based of the stat sheet linked on the forum pre-release of BS. So I understand if the stats have been shuffled around since then. Just wanting to check the gear is on Live with the correct values. As several of the pieces have different stat values on the sheet. But still some of them are exactly the same.

However the Gloves on BW seemed to be the most off:
https://imgur.com/a/V3pTDCd

**Comment by wargrimnir** [comment]
Found these, the rest of the casters had the same issue, healers too. At least it was just the initiative missing I suppose. Fixed next patch.

**Comment by sioding** [comment]
fixed with patch from 06.07.2019
