### ISSUE TITLE
Magus Invader armor 6 and 7 piece bonus

### ISSUE THREAD

**Issue by Vicgrim** [WarEmu/WarBugs#14418]
![invader2](https://user-images.githubusercontent.com/51807854/59479506-fb45af80-8e65-11e9-817c-d2e97c67f862.jpg)
6 and 7 piece bonus dont works on dots tick. its works only for instant damage abilities
Red Wind ability (3 instant hits) automatically activate and cancel 6 piece buff

**Comment by wargrimnir** [comment]
Procs generally only activate on direct casts, rend winds is a direct cast that hits three times. I don't see anything wrong here.

**Comment by Vicgrim** [comment]
its little strange because indigo fire of change activate 6 piece buff (precision) but don't cancel them. indigo fire of change hits 4 times and only difference with rend winds, indigo - Channeled Spell
and if indigo activate buff (not only from first hit) why dots ticks dosnt activate buff

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 29.6.2019
