### ISSUE TITLE
Wrong Bloodlord Body piece for Engineer

### ISSUE THREAD

**Issue by Tibdum** [WarEmu/WarBugs#14411]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**

The Bloodlord Bulwark is assigned to Runerobes Runepriest Set instead of Engineer Work Kit like the other items

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/47664666/59412199-95095000-8dc5-11e9-896c-5a35e0120f1c.png)

**Comment by wargrimnir** [comment]
Fixed last patch
