### ISSUE TITLE
[Quest] Unholy - Missing map marker

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#14419]
**Expected behavior and actual behavior:**

This quest is missing a map marker.

The quest itself was fixed in https://github.com/WarEmu/WarBugs/issues/6408 but the map marker is still missing.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Lotharic_217](https://user-images.githubusercontent.com/7400/59499356-8c814a00-8e97-11e9-9f1f-ff7a94973eaf.jpg)

**Comment by Rockalypse** [comment]
Will be fixed with next update

**Comment by Natherul** [comment]
should be fixed as of today
