### ISSUE TITLE
Mara/Slayer Subjugator and Smuggler weapons

### ISSUE THREAD

**Issue by hardstylexsl** [WarEmu/WarBugs#14412]
I noticed something odd when looking at Subjugator and Smuggler weapons. On order you can wear two kinds of Smuggler weapons that each have a unique proc:
![slsm](https://user-images.githubusercontent.com/51748940/59433953-d5c79000-8dea-11e9-9e57-e64da34b604d.png)

On destru all Smuggler variants and the Subjugator weapon itself have the same proc:
![marasm](https://user-images.githubusercontent.com/51748940/59433886-b3ce0d80-8dea-11e9-824b-2521d04216b0.png)

This seems like a pretty huge difference in power especially since some slayer dots (I only tested Inevitable Doom) trigger procs on each tick:
![combat](https://user-images.githubusercontent.com/51748940/59433999-f2fc5e80-8dea-11e9-9aa9-a2c92e349e1c.png)

I'm not sure if this is a bug or intended to work that way but I thought I'd report it anyway.

**Comment by Lheana** [comment]
Fixed with patch of 02/11/2019.
