### ISSUE TITLE
Terrible Embrace

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#14415]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**

target get pulled to the player .. the current issue i tested on targets standing on keep and not moving hitting me while i try to cast on him the pull on him
**Steps to reproduce the problem:**

Terrible Embrace the cast bar get canceled auto or go to half or quarter of the way then canceled and i have to press it again seems to happen a lot when taking damage

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Tazo83** [comment]
https://clips.twitch.tv/ThankfulGenerousDunlinKappa

https://clips.twitch.tv/PiliablePleasantTeaPicoMause

https://clips.twitch.tv/AveragePlausiblePeachMikeHogu

**Comment by Tazo83** [comment]
another video showing the bug even when the cast completed nothing happened

https://clips.twitch.tv/PleasantRoughTortoiseAsianGlow

**Comment by grunbag** [comment]
You mean you get set back ?

**Comment by Tazo83** [comment]
i mean the casting bar move back for example 50% then getting hit and casting bar is back to 20% plus u can see in the video i spammed the ability on many targets and more than enough duration but not even single one got pulled

**Comment by grunbag** [comment]
being set back on casting spell is normal
