### ISSUE TITLE
PVE Kick should knock down

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#1442]
right now does nothing. original behaviour was that a kick did a knock down to mob. (if not imune to it)

**Comment by milosxe** [comment]
That's right. And even the tool tips on some abilities say the players will be knocked back, and mobs will be knocked down.

**Comment by Evildoor** [comment]
Also, mobs ignore snares.

**Comment by ozarmidrashim** [comment]
They don't. They're just faster in comparison to players and have glitched walk. I just tested that on my dev server.
