### ISSUE TITLE
Duplicating Vanquisher Medallions

### ISSUE THREAD

**Issue by toffikx** [WarEmu/WarBugs#14422]
Hello!

"Duplicate Vanquisher medallions"

**Expected behavior and actual behavior:**

Bought vanq chest for 280 meds yesterday. Today those 280 meds are back while i still have chest.

**Steps to reproduce the problem:**

I wanted to see if it's a visual bug of some kind but it's not. The medallions works fine, as in that I could buy a new vanquisher piece for the duplicated ones.
I was thinking about posssible reasons as to why this happened, from my side. I am not specially good with computers and I dont use any "weird" programs, and I certainly have not used anything odd/new when that happened. All I can say is that I run with a modified client from the Return of Reckoning forums, aimed to enhance game stability and performance. I've been running this client for months though, and guess those two things don't share a common link. 

Cheers!

**Testing Screenshots/Videos/Evidences (always needed):**

![Faaceshaper_009](https://user-images.githubusercontent.com/49347536/59532510-4a80f400-8ee9-11e9-9dff-2cb4cc7d396d.jpg)
![Faaceshaper_008](https://user-images.githubusercontent.com/49347536/59532584-7d2aec80-8ee9-11e9-9a83-a54b3e81a9f3.jpg)
![Faaceshaper_010](https://user-images.githubusercontent.com/49347536/59550275-f3baff00-8f68-11e9-840f-cab3cf7b75fd.jpg)
![Faaceshaper_011](https://user-images.githubusercontent.com/49347536/59550277-f74e8600-8f68-11e9-910a-a57b90e903ae.jpg)
![Faaceshaper_012](https://user-images.githubusercontent.com/49347536/59550279-f9184980-8f68-11e9-91a2-6a2eec16a4a9.jpg)

**Comment by Kaelang** [comment]
Likely based on a restart which pulled back your tokens however did not do a check for items purchased from said tokens. 

Please re-open if this issue is persisting.
