### ISSUE TITLE
Destro getting 4 medallions for Fort win

### ISSUE THREAD

**Issue by wingedmedic** [WarEmu/WarBugs#14429]
Patch stated that winners would get 6 Invader medallions. Destro won a recent fort and still received the usual 4 medallions. Will attempt to win the next fort to see if the problem is still going on.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

[https://imgur.com/a/rFim3Pq](url)

**Comment by wingedmedic** [comment]
https://imgur.com/a/rFim3Pq

**Comment by sioding** [comment]
fix pending

**Comment by sioding** [comment]
Already hotfixed
