### ISSUE TITLE
[NPC] Bloody Sun Shaman in the Undercroft in IC does not have a name tag

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14424]
This shaman near the traders has no name above his head.

![Krillit_000](https://user-images.githubusercontent.com/30193675/59545674-04945200-8f22-11e9-9159-151783132a95.jpg)
![Krillit_001](https://user-images.githubusercontent.com/30193675/59545675-04945200-8f22-11e9-8adb-a9943bd43b02.jpg)

**Comment by sioding** [comment]
fixed with patch from 22.6.2019
