### ISSUE TITLE
Spell info does not show after patch.

### ISSUE THREAD

**Issue by monster1305** [WarEmu/WarBugs#14427]
Spell info/tactic info does not show after patch. Tried /reload and relog.

![Keyoberyn_008](https://user-images.githubusercontent.com/48641801/59555390-eda13e80-8fb9-11e9-839d-8878128ac666.jpg)
![Keyoberyn_009](https://user-images.githubusercontent.com/48641801/59555391-eda13e80-8fb9-11e9-85ef-5ec61ec5ac31.jpg)
![Keyoberyn_007](https://user-images.githubusercontent.com/48641801/59555392-eda13e80-8fb9-11e9-9714-bc59c7c59e95.jpg)

**Comment by monster1305** [comment]
Tried it on character Keyoberyn / Blackguard.

**Comment by monster1305** [comment]
![Keyraven_000](https://user-images.githubusercontent.com/48641801/59556099-bd5f9d00-8fc5-11e9-9130-bb4ed3cb4d46.jpg)
![Keyraven_002](https://user-images.githubusercontent.com/48641801/59556100-bd5f9d00-8fc5-11e9-88c6-02311a6a97e9.jpg)
Tried it on another toons as well. Still the same thing.

**Comment by sioding** [comment]
Should be fixed - just close the game and the launcher - and start again.
