### ISSUE TITLE
[Ability] Black Guard .Abilities after learning are not displayed in the book

### ISSUE THREAD

**Issue by Anern** [WarEmu/WarBugs#14426]
I learned skills and do not see them in the book of spells

https://photos.google.com/album/AF1QipPSrNi6vYmlh5j6nbdDPb9xQ2ORWSxQR-mdb8O-/photo/AF1QipPogM3ztFdIj36fmfkc0RIUASELekRpraBCgY_x

https://photos.google.com/album/AF1QipPSrNi6vYmlh5j6nbdDPb9xQ2ORWSxQR-mdb8O-/photo/AF1QipPMvFRiAl6UIyEvgAqU-mjkF3fo5xI4I9xivggG

https://photos.google.com/album/AF1QipPSrNi6vYmlh5j6nbdDPb9xQ2ORWSxQR-mdb8O-/photo/AF1QipPfWDIItBeY60v02w8iff_X0CBTyJcquhfOg4og

https://photos.google.com/album/AF1QipPSrNi6vYmlh5j6nbdDPb9xQ2ORWSxQR-mdb8O-/photo/AF1QipNPxzXUNg0qsVEJqeoAm1BkpGiyldzG0ERK-e_B

https://photos.google.com/album/AF1QipPSrNi6vYmlh5j6nbdDPb9xQ2ORWSxQR-mdb8O-/photo/AF1QipM7dyMnewgFOiofnqUXEWcFwLvO7Y19q4pqdA1y

https://photos.google.com/album/AF1QipPSrNi6vYmlh5j6nbdDPb9xQ2ORWSxQR-mdb8O-/photo/AF1QipOKmk5Rd5r9-zETZs6fmmyYNNC6A9Wu1RDEitla

https://photos.google.com/album/AF1QipPSrNi6vYmlh5j6nbdDPb9xQ2ORWSxQR-mdb8O-/photo/AF1QipNtES9vYgRdDPA4nfHmvWnG5BQmC-oJDqSJFApg

https://photos.app.goo.gl/87LFJDVQC9jXRdVN7

**Comment by Scophis** [comment]
You have to spend an extra mastery-points on the skills/tactics itself.

**Comment by sioding** [comment]
Answer given. Close
