### ISSUE TITLE
Bloodlord Runesash belt not counted in RunePriest set

### ISSUE THREAD

**Issue by Grognir** [WarEmu/WarBugs#14423]
**Expected behavior and actual behavior:**
When equipping five bloodlord item on me I was surprise to see only 4 out of 7 bonus set. It seems that the Bloodlord Runesash is not considered to be equiped whereas it is (see screenshot)

**Steps to reproduce the problem:**
Equipe the 5 bloodlord item i have, and each time the belt is not taken into account and i get 4 bonus only
![bloodlord set](https://user-images.githubusercontent.com/44229673/59544794-b416f780-8f15-11e9-9c45-7fcf6c3ac35e.JPG)

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by sioding** [comment]
fixed with patch from 22.6.2019

**Comment by Grognir** [comment]
The 5 item procurement is still in grey as if it was inactive whereas I confirme the +4% damage receive proc sometimes
