### ISSUE TITLE
[Ability][Arch Mage] Cleansing Light

### ISSUE THREAD

**Issue by Aluviya** [WarEmu/WarBugs#14421]
**Expected behavior and actual behavior:**
"Cleansing Light" Path of Isha ability scales on the Path of Asuryan.
In addition the tactic "Apotheosis" also seems to scale on the Path of Asuryan (even though there is no gain for it - since it only makes Cleansing Light to AoE ability). It shows always the level of the Path of Asuryan if you take it.
**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Aluvya_016](https://user-images.githubusercontent.com/17249318/59530995-34713480-8ee5-11e9-9689-e715ee7f854f.jpg)
![Aluvya_017](https://user-images.githubusercontent.com/17249318/59530996-34713480-8ee5-11e9-9777-51ea46b9f1a0.jpg)

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 29.6.2019
