### ISSUE TITLE
Falling Damage on Inevitable City pathway

### ISSUE THREAD

**Issue by Dkrewe** [WarEmu/WarBugs#14430]
While jumping down some "steps" in IC, I took a large amount of fall damage out of nowhere. 

Jump down the steps at the same approximate location at the screenshot to duplicate the issue.

![Velkhara_001](https://user-images.githubusercontent.com/51872114/59559489-40302a00-8fbd-11e9-9d29-87dea4d0aa96.jpg)
![Velkhara_002](https://user-images.githubusercontent.com/51872114/59559490-40302a00-8fbd-11e9-8a54-11cda176e65c.jpg)

IGN is Velkhora.  Username on forums is Szeff.  email associated with my account is sdyson06@gmail.com please let me know if you need any further details.

**Comment by sioding** [comment]
This happens since AoR - sorry but the warhammer is a dangerous game. :) 
tbh: You will die sometimes while you jump an rocks or jumping don a little edge - nothing we can fix right now - it just happens.
