### ISSUE TITLE
[BG] City Dungeon Inf Shield

### ISSUE THREAD

**Issue by Ripliel** [WarEmu/WarBugs#14437]
BG has two shields with equal stats.

This one should have different stats:
![Riphael_100](https://user-images.githubusercontent.com/16005849/59597162-e1c09400-9101-11e9-98c7-ff31c5151899.jpg)
They should be the same as SM's shield with the same proc:
![Arfi_009](https://user-images.githubusercontent.com/16005849/59597208-f3a23700-9101-11e9-923d-dc620fdc5c3c.jpg)

**Comment by sioding** [comment]
fixed with patch from 22.6.2019
