### ISSUE TITLE
[Blackguard] Force of Fury - Not sure crit chance modifier's working(?)

### ISSUE THREAD

**Issue by Zealote** [WarEmu/WarBugs#1443]
Tested on lvl 22 yeti.

Number of crits / total attacks, without FoF: 12/100, 27/93, 12/104, 10/103, 16/100 = 77/500 = 15.4%

With FoF at 90+ hate (-45% crit chance), just tested repeatedly during the 10s buff: 7/50 (14%), 14/70 (20%), 17/90 (18.9%), 13/55 (23.6%), 15/74 (20.3%) = 66/339 = 19.5% (assume the fact it's actually increased is just random)

If the numbers in this thread: http://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=879&p=10392&hilit=stat+calculations#p10392 apply to mobs and are roughly accurate, with 127 ini my chance to be crit by a lvl 22 should be about 17% I believe so the values above seem reasonable (if FoF isn't having an effect).

I wouldn't have thought there'd be a difference between mobs/players since it's a self-buff that's sposed to affect all inc attacks, but either way any confirmation/denial on whether it's actually working (and I've missed sth obvious :P) would be great.

Just to clarify: I'd guess any mob of a certain lvl has the same base chance to crit you (based on your initiative), so if, e.g., it were 20%, with a -45% reduction at 100 hate, it shouldn't crit you at all during the buff period should it?

**Comment by ozarmidrashim** [comment]
Combination of bad critical hit calculation and wrong sign of critical hit reduction on this ability.
