### ISSUE TITLE
Character abilities

### ISSUE THREAD

**Issue by fixfax86** [WarEmu/WarBugs#14439]
Some abilities doesnt seem to work properly. The damage over time in the Ironbreaker's "Heavy Blow" and "Binding Grudge" doesnt seem to Count Properly.. "Guarded Attack"'s Armor buff doesnt count properly, it only counts 200 armor bonus! And The Shadow Warrior's tactic "Expert Skermisher" doesnt seem to work properly, there is a latancy time when Under/near 20 feet. maybe bacause the game is not fast enough to figure out where and when Players or creatures move.. wich makes "expert skermisher" almost useless!

**Comment by sioding** [comment]
Hey - thanks for the ticket but:
Please: Only one problem per ticket AND add some testing screens/videos for the problem you bring in. Check if someone else already reported it before opening the ticket.
