### ISSUE TITLE
Instructors boon is removen on bolstering

### ISSUE THREAD

**Issue by Alfred19** [WarEmu/WarBugs#14431]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**

Using Instructors boon potion should run for the whole 60mins.
Once player passes under a bridge or steps into oRvR zone it gets cleansed if player is below r40. (CD for reuse is 5mins)

**Steps to reproduce the problem:**

Buy Instructors Boon from Quatermaster, use it on char <40 go into zone where bolster is active.

**Testing Screenshots/Videos/Evidences (always needed):**

did it like 10 times with character r16- 21

**Comment by Alfred19** [comment]
If it is intended behaviour pls at last remove CD

**Comment by sioding** [comment]
Is the bufficon removed - or the buff itself? Can you check that while using .getstat and show us some output?

**Comment by Alfred19** [comment]
The buff itself was removed. I checked it back then, but did not screenshot it.
However, i cant recreate it anymore.

Before i had the buff running died in RvR, released, Buff was removed, Healed battle fatigue, activated instructors boon, stepped into RvR zone, Buff was removed again. This doesnt work now.
I will keep an eye on this.

**Comment by sioding** [comment]
OK thanks put it back in here is you see somehing strange, Close until that
