### ISSUE TITLE
Prevented exp gain 2019/06

### ISSUE THREAD

**Issue by Syzlakee** [WarEmu/WarBugs#14433]
So after multiple kills i've finnaly decided enough is enough and i want a solution to this problem when you kill someone that gives you experince i had huge amount of issues with this the last double exp because i killed players and i did not get any exp made it impossible as a solo player to enojoy the game

**Expected behavior and actual behavior:**
If i kill someone with 400% aao i should be able to get 5x the normal gains however as of right now its not allowing it because the system is bugged... and gives you an error message saying 
You somehow gained an amount of xp larger then the system allows (122k) in this case this gain was prevented

**Steps to reproduce the problem:**
Raise the Xp gain so u can actually get teh full use of the AAO....

**Testing Screenshots/Videos/Evidences (always needed):**

![prevent1](https://user-images.githubusercontent.com/6264128/59566135-18dc6a00-905c-11e9-9b60-fbdff414a3d9.png)
![prevent2](https://user-images.githubusercontent.com/6264128/59566148-45908180-905c-11e9-9685-fbf796427c2c.png)
![prevent3](https://user-images.githubusercontent.com/6264128/59566151-49240880-905c-11e9-91e9-b32495175c3d.png)
pr
![prevent4](https://user-images.githubusercontent.com/6264128/59566152-4f19e980-905c-11e9-829b-2152692f9da3.png)

**Comment by sioding** [comment]
This is not a bug - it is a decision. If you want to change this make a thread in our suggestion forum.

**Comment by Syzlakee** [comment]
I was talking to a CM earlier and he said it was a bug but maybe hes just misstaken then but good to know so when its 400% aao is should just not play the game?? kinda bizzare if you ask me should in that case cap teh AAo to 300%?

**Comment by sioding** [comment]
A bug itself - is something that is not working properly. The xp cap should prevent getting a huge amount of xp. We had some problem in the past that needed to create this cap. So the part of the code that prevents getting too much xp works quite fine. You want a change for this may it be someting like "i find a hard cap ok - but i want to have the maximum of the xp not nothing" or "the hard cap is crap - i want to have everything". All fine - but the code itself is fine - and its not buggy. If you want a change - you are really welcome on our suggestion forum.

**Comment by Syzlakee** [comment]
Im not impossible i tottaly agree and see the point of getting 120k for a kill is to much however i think like everything from 20-70 should be possible in those cases i agree 100% that getting 120 or 240k during a double is not acceptble
