### ISSUE TITLE
CHoppa NEW SC Weapon appearance issue

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#14435]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**

i cannot change the weapon appearance in game i tried with 2 different weapon appearance 

![image](https://user-images.githubusercontent.com/42385505/59572770-fd9f4800-90b7-11e9-9978-6d09cc84c694.png)

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by wargrimnir** [comment]
This is not a bug. Pay attention to your weapon. It needs to MATCH with the one you want to set as appearance. If you're trying to match a sword that uses EITHER hand vs a sword that uses only MAIN hand, you cannot apply appearance.
