### ISSUE TITLE
Issua with Crypts Boss

### ISSUE THREAD

**Issue by rhix112** [WarEmu/WarBugs#14438]
Boss kill doesn't counted for me - Necromancer from Crypts, full grp without lockouts

![Faiz_001](https://user-images.githubusercontent.com/31020540/59623780-c2475c80-913d-11e9-98ea-c325e7fe1526.jpg)

**Comment by sioding** [comment]
Any error message - were you alive and in range while you killed Malcidious?

**Comment by sioding** [comment]
No answer for 11 days. close

**Comment by grunbag** [comment]
fixed already
