### ISSUE TITLE
[Choppa] Spender Ability SPEC - Furious damage doesn't work properly

### ISSUE THREAD

**Issue by Ywhi** [WarEmu/WarBugs#14440]
Damage of  SPEC Spender of Choppa doesn't work properly (75% damage doesn't apply on furious stage)
- No More Helpin'
- Tired Already
- Keep on Choppin'
- etc ...

You can see on the left screen, No more helpin" in berserk stage (-1570 - 50%) damage and on the right screen i am in furious stage and i only do (1373- 25% damage instead of the 75%)

Damages work properly with  No-spec spenders

![Choppa](https://user-images.githubusercontent.com/51972885/59719609-170dd480-921d-11e9-9424-73b8c5de6e7f.jpg)

**Comment by grunbag** [comment]
I need combat log in chat . Cause I don’t see if there is crit or not

**Comment by Ywhi** [comment]
Left - Berserk Stage
Right - Furious Stage

![Combatlog](https://user-images.githubusercontent.com/51972885/59759825-32b2c280-9291-11e9-8178-803880e34c23.jpg)

**Comment by Ywhi** [comment]
Is it enough ?

**Comment by grunbag** [comment]
I tested and bonus worked fine . Do you run any specific tactic ?

**Comment by grunbag** [comment]
Or are you full invader ?

**Comment by Ywhi** [comment]
I use pent up rage but i tried with and without and it is the same.  (i don't use Wot rules?)
I still do more damage in Berserk stage than Furious stage with all the exhaust ability of spec (Keep on Choppin" / No more helpin / Tired Already). Damage works properly with choppa "base exhaust skill" like "Weakin Killa" or Reckless blow

**Comment by grunbag** [comment]
I tried all of them and my bonus is correctly applied .

**Comment by Ywhi** [comment]
Mmh... I don't know i keep trying and i just do more damage in Berserk(red) stage than Furious(yellow) stage with those abilities : /. (like the screen)

**Comment by grunbag** [comment]
I asked another choppa to try this , waiting for him

**Comment by Ywhi** [comment]
Ok i tried without stuff (only 2H) / tactic, no change on my side, still do more damage in berserk than furious.

**Comment by grunbag** [comment]
Other choppa is asked to test deal more damage in furious than red . Try it naked

**Comment by Ywhi** [comment]
![Nostufftactic](https://user-images.githubusercontent.com/51972885/59948011-1b313080-946f-11e9-9243-ab5db80f745c.jpg)

Left - Furious Stage
Right - Berserk Stage

**Comment by grunbag** [comment]
This is really weird , I can’t reproduce your bug . Only no more helping?

**Comment by Ywhi** [comment]
"No more Helpin" and "Tired already". (Did you guys nerf me ? ;P)

**Comment by grunbag** [comment]
Others are fine ?

**Comment by Ywhi** [comment]
Yep Keep on choppin works fine ( didn't try Wot's da rush tho)

**Comment by grunbag** [comment]
Ok I’ll try to test it more tonight

**Comment by grunbag** [comment]
You’re right , no more helping is broken

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by Ywhi** [comment]
Nice "No more Helpin" and "Tired Already" ? 

Thanks

**Comment by grunbag** [comment]
Yes
