### ISSUE TITLE
High Elf Chapter 15: Minor Map Bug with the quest "Shoddy Shipwrights"

### ISSUE THREAD

**Issue by MrStretchz** [WarEmu/WarBugs#14448]
For this quest you need to plant 3 Boom Kegs on 3 crates that are each located on a ship wreck.

The map shows the red area in which you need to do this, however after you place the 2nd Boom Keg, the red area marker on the map disappears 

Location of the 3rd quest where I haven't clicked it yet
![Gearstrike_004](https://user-images.githubusercontent.com/51711908/59862644-0d9a7e80-937b-11e9-9892-3316e08436a6.jpg)

Red area marker missing (top right location where I'm standing) when I haven't touched it yet
![Gearstrike_006](https://user-images.githubusercontent.com/51711908/59862646-0e331500-937b-11e9-9c33-4795a69863fd.jpg)

Quest in question
![Gearstrike_005](https://user-images.githubusercontent.com/51711908/59862645-0d9a7e80-937b-11e9-9030-56f9fe3acf7e.jpg)

This is only a minor map bug and does not prevent the quest from progressing or turning it in.

**Comment by Lheana** [comment]
I fixed this with last patch when I reworked the quest line.
