### ISSUE TITLE
Zealot mark of the Spell Destroyer

### ISSUE THREAD

**Issue by Vicgrim** [WarEmu/WarBugs#14449]
![Zealot mark 3](https://user-images.githubusercontent.com/51807854/59866407-282d2180-9394-11e9-9b32-5381bcd9a78e.jpg)
 Zealot mark of the Spell Destroyer dosent incaress Willpower, only intiative!
![zealot mark](https://user-images.githubusercontent.com/51807854/59866466-4eeb5800-9394-11e9-9c54-f62b4504530c.jpg)
i used vortex mark and have 688 willpower 200 intiative
 
![zealot mark 2](https://user-images.githubusercontent.com/51807854/59866651-c8834600-9394-11e9-9d12-039503859474.jpg)

Butt after buff Mark of the Spell Destroyer i have only +50 intiative and my willpower still 688

**Comment by wargrimnir** [comment]
Ability buffs don't stack. What other source of willpower buff do you have? I see two other potions there.

**Comment by wargrimnir** [comment]
RIP
