### ISSUE TITLE
BB - last boss big bugged!!!

### ISSUE THREAD

**Issue by Elflord123** [WarEmu/WarBugs#14444]
If you died at the last boss to 20% and rose again at the beginning of the dange, the boss will still attract you and after this stage you would be back in the lair of the boss and will be able to hit him

**Comment by sioding** [comment]
Dunno what that means - maybe Grunbag knows more.

**Comment by Elflord123** [comment]
See pls video.

If you die on the boss to 20% ( stage of attraction) and rise at the beginning of danzhe, the boss will automatically attract you to all, then you will reappear at the boss and get loot and influence

https://youtu.be/I02HEr9pdOM
https://youtu.be/I02HEr9pdOM
https://youtu.be/I02HEr9pdOM

**Comment by grunbag** [comment]
fixed already
