### ISSUE TITLE
[Fort] Contribution

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#14447]
**Expected behavior and actual behavior:**
this was contribution window.
![fort_contr1](https://user-images.githubusercontent.com/19988772/59850868-35eba280-93a6-11e9-87a5-a2e98a3cb682.jpg)

destro was winning in stage 2. 
5 flags tick happened 2~3 times. 
stage 3 was ended in 5min.
top contributor was IB on losing side. with strange difference from 2nd.
someone commented on chat that it's because he spammed prison lever
but can't confirm it.
i was capping flags mainly in stage2 but never met him.
destro was winning battles.
it seems prison lever were possible source.
zone was shining way.

**Comment by Aluviya** [comment]
Can confirm this. I have seen Herkku running around the fort, but not specifically taking party of the scenario. In a order won Fort he rolled a Gold Bag with very high base contribution.
![Aluvya_019](https://user-images.githubusercontent.com/17249318/59882915-cbd9fa00-93b3-11e9-871f-4d49b270b3eb.jpg)

**Comment by Nfkillz** [comment]
todays fort in BC
<img src="https://monosnap.com/image/HZdWdTd5mK2nXPaUfq2EDMQzeLHpWw"/>

**Comment by Aluviya** [comment]
This feels very intentionally abused to me....

**Comment by Natherul** [comment]
this has been fixed for some time now. Did not know there was a ticket. Thanks for the report.
