### ISSUE TITLE
Sigmar Hammer's Fall Through Ground

### ISSUE THREAD

**Issue by Manatikik** [WarEmu/WarBugs#14446]
Ran in to the chair in Sigmar's Hammer and fell for a while to my death.

![sgimar fall through](https://user-images.githubusercontent.com/19319894/59830137-3e879e80-92fc-11e9-9db0-2ad53fe63b44.png)
![sigmar dead](https://user-images.githubusercontent.com/19319894/59830141-40516200-92fc-11e9-9b48-3f69dbdf0a0e.png)

**Comment by sioding** [comment]
Nothing we can fix here - but: thanks for the report. Sometime we can do something at this - but ... not here.
