### ISSUE TITLE
[Tooltip] Horned Squig - "Head Butt" says KB instead of KD

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#14457]
Tested it with a guildmate, the squig knocks it's target _down_ and not _back_, as stated in the tooltip. 
Also I'm not 100% sure, but shouldn't it be shattering a blessing? [Patch Notes 06/07/2018](https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=27274&hilit=head%20butt#p308847)
![Gangan_010](https://user-images.githubusercontent.com/40274248/59928537-43a13680-943f-11e9-9f66-811930d21b66.jpg)

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 29.6.2019
