### ISSUE TITLE
Guild bug is still active - Blocking players from Logon.

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#14459]
Please reopen the bug ticket as the guildbug is still active.
I need something like 6-8 tries to logon or change a zone.

It was fixed back then when guild infos were send 20 seconds after logon.

Related bugreport is here, but needs reopening and more solving:
[https://github.com/WarEmu/WarBugs/issues/14019](url)

**Comment by sioding** [comment]
Duplicate of #14019
