### ISSUE TITLE
AM Invader Set bonus issue

### ISSUE THREAD

**Issue by Latemoon83** [WarEmu/WarBugs#14451]
Dear Supporter,

there is an issue with the 5% crit-healing setbonus. Both Set's give 5% crit heal, but when i change the 6 Set pieces, the invader set gives only 3% crit heal.

Vanquisher Set:

![Latemoon_Van-set1 (2)](https://user-images.githubusercontent.com/33985355/59872686-9b399680-939a-11e9-9f98-bc63fc550d77.jpg)
![Latemoon_van-set2 (2)](https://user-images.githubusercontent.com/33985355/59872715-abea0c80-939a-11e9-80dd-5261b8f1a617.jpg)

Invader Set:

![Latemoon_inv-set1 (2)](https://user-images.githubusercontent.com/33985355/59872764-c7551780-939a-11e9-80d1-47eca621e1e4.jpg)

![Latemoon_inv-set2 (2)](https://user-images.githubusercontent.com/33985355/59872774-cb813500-939a-11e9-85f0-0793b1fbf2b1.jpg)

Or i forgot something?

Sincerely yours...

Latemoon

**Comment by Aluviya** [comment]
Did you check the overall crit% from all pieces? Might be smaller on Invader.

**Comment by Latemoon83** [comment]
Yes... I'm sorry...
