### ISSUE TITLE
Can't cancle items from auction 

### ISSUE THREAD

**Issue by Werterconverter** [WarEmu/WarBugs#14458]
Link to screenshoot:
https://i.imgur.com/rf6sWLO.png

Left bottom chat box you have system errors. I can't remove items - no matter blue or green.

But... I'm was able to remove items I've put less then 24h ago. Only "old" items - 3+ day are stuck there.

**Comment by MaxHayman** [comment]
Weird, this should only happen if the item doesn't belong to you etc. I will look into this.

**Comment by Werterconverter** [comment]
Okey - I've resolve this. Those were items on my other chars auction and after 2-3 relogin I've found which one had them in auction house.

**Comment by MaxHayman** [comment]
What were your character names? were they similar?

**Comment by oXJerXo** [comment]
I was having this problem today. I saw this post and realized that I must have had items from two different characters posted in the auction house (Jerez and Jerezz). I was unable to cancel the listings as Jerez posted by Jerezz, but once I logged in as Jerezz it let me cancel the items. I don't recall posting anything as Jerezz, but I may have. Let me know if you need any further information.

**Comment by Kaelang** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/1103.
