### ISSUE TITLE
Sharing a quest reset the quest progress!

### ISSUE THREAD

**Issue by DanaBloodkiss** [WarEmu/WarBugs#14454]
**Expected behavior and actual behavior:**

(Witch Elf on Destro side.)

Expected: If you share a quest only the group member or player near you who does NOT have the quest should get the quest. 

Actual: Everyone even the people who already have the quest get the quest and it resets the quest progress of the people! I lost my BB and BE quest progress for killing the different heroes... 

**Steps to reproduce the problem:**

Take the BB or BE quests. Kill a hero and then someone share the quest to you. You will lost your one kill count. 

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
This should be fixed as of the 20/05 patch. Please re-open if issue persists.
