### ISSUE TITLE
Bloodlord AM set 6 pc

### ISSUE THREAD

**Issue by Koinzzell** [WarEmu/WarBugs#14455]
**Expected behavior and actual behavior:**
The current 6 pieces bonus seems to not work correctly.
On hit it you have 10% of chance to apply an increase damage incoming of 4%.
But this could not be apply when I apply (and so hit) dots on the target.
Also, it is not working with radiant burst, storm of cronos or dissipating energy. Those cast should enable us to apply the increase damage incoming of 4% in zone or it is not the case. Is it normal? 

**Steps to reproduce the problem:**
Take 6 pieces bloodlord, radiant burst as tactic and hit targets with dots and skills explain as above.

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/51057710/59926423-93313380-943a-11e9-9c68-c74bf4addc25.png)

**Comment by Koinzzell** [comment]
Also is it normal that the gauntlet have only 3 stats ? (see attaching screenshot)

![image](https://user-images.githubusercontent.com/51057710/59953594-22f9d080-9481-11e9-98c3-e7ff41eeaed4.png)

**Comment by grunbag** [comment]
proc works only on direct damage usually, so it's not a bug
