### ISSUE TITLE
Can't buy SC Weapon

### ISSUE THREAD

**Issue by Zaxx0nd** [WarEmu/WarBugs#14453]
Can't buy the SC Oppressor Weapon on BW.
![SC_Weapon](https://user-images.githubusercontent.com/19254707/59887538-9c59cc00-9378-11e9-81c8-32f07f21bc3d.PNG)

**Comment by dalen** [comment]
You need both the emblems and the previous weapon in your inventory.

**Comment by sioding** [comment]
Answer given - close
