### ISSUE TITLE
[Bastion Stairs] Portal before last boss in the mid wing teleports in wrong place

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#14456]
<img src="https://monosnap.com/image/32HyrEaiOueplyWJrUci1hbqbqvOVg"/>
You are ported in place from where you cant go out and you have to relog and run again from start.

**Comment by Nfkillz** [comment]
in fact you just stay in place that you can see in the screen shot but you cant use portals

**Comment by grunbag** [comment]
i don't understand the issue

**Comment by raptrr** [comment]
@Nfkillz , as @grunbag stated, he does not understand the issue and I've run BS recently and did not encounter your posted problem. So I will put this on 2 Week Ultimatum and  gonna close it afterwards.
