### ISSUE TITLE
[Forts] Contribution after DC

### ISSUE THREAD

**Issue by Ripliel** [WarEmu/WarBugs#14464]
4 out of 6 people from the group are in list of top contribution.

2 got DCed during the fort (everyone was inside when the fort finished)

We were doing almost the same stuff since it was a one group roaming so conclusion is simple: 
DC resets your contribution. 
![contribut](https://user-images.githubusercontent.com/16005849/59966214-aa971c00-9521-11e9-8a7e-73fdb98e854e.PNG)

**Comment by Natherul** [comment]
DCs does not reset contribution. I wont go into the details on contribution as it can make it gameable. Though I can think of a few reasons why this discrepancy happened.
