### ISSUE TITLE
chalice of the smuggler dont regen essence

### ISSUE THREAD

**Issue by Wachlarz** [WarEmu/WarBugs#14465]
https://www.youtube.com/watch?v=0tUoeMpeg84

**Comment by Wachlarz** [comment]
Somthing change now Smuggler work, but  Malfeasance chalice dont work

**Comment by sioding** [comment]
Remove it from you caracter and put it back on. DON'T CHANGE IT WITH ANOTHER . Its a known bug which is already reported
