### ISSUE TITLE
Tomb of Deathsword - Chaos Chapter 18 - Target marked as not attackable.

### ISSUE THREAD

**Issue by plebeiancrusher** [WarEmu/WarBugs#14462]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**
On Stage 3 of the Public Quest "Tomb of Deathsword" in Chaos Chapter 18, Inquisitor Lutz should be attackable without any notification.  Instead, Inquisitor Lutz shows as being not attackable despite actually taking damage.

**Steps to reproduce the problem:**
Attain Stage 3 of the "Tomb of Deathsword" Public Quest, and fight Inquisitor Lutz.

**Testing Screenshots/Videos/Evidences (always needed):**
![Norendithas_011](https://user-images.githubusercontent.com/50555776/59963721-0d0dff00-94c5-11e9-9d0d-ca340d0c1739.jpg)
![Norendithas_012](https://user-images.githubusercontent.com/50555776/59963722-0d0dff00-94c5-11e9-9068-9533bda64edf.jpg)

**Comment by sioding** [comment]
fixed with patch from 27.07.2019
