### ISSUE TITLE
Engi Annihilator set bonus is off-spec instead of main spec

### ISSUE THREAD

**Issue by Necredz** [WarEmu/WarBugs#14468]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**
All the other RvR sets provide bonus to Ballistics except this one.  Looks like the SC Mercenary set has those bonuses instead, and the other sets there provide the Toughness bonuses. 

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**
I have provided screenshots of the current Annihilator set, as well as the current Mercenary set.
This will show what the bonuses are at the moment.

Annihilator
![Gadgitz_000](https://user-images.githubusercontent.com/52136959/59980536-488ff280-95c5-11e9-9afd-3a32e9d28396.jpg)

Mercenary
![Gadgitz_001](https://user-images.githubusercontent.com/52136959/59980537-4d54a680-95c5-11e9-86ba-6a8c3b4e3878.jpg)

**Comment by dalen** [comment]
Isn't this the case for all DPS classes?

**Comment by wargrimnir** [comment]
This is not a bug. Don't post it on the bugtracker.
