### ISSUE TITLE
AM Invader 7 part Bonus

### ISSUE THREAD

**Issue by Lithliel** [WarEmu/WarBugs#14466]
Expected: As bonus state 10% chance to increase crit heal by 9% and crit heal value by 12% on any Isha tree skill.
Actual: Bonus trigger at EVERY Isha tree skill thats 100% chance to proc. It also refresh itself. 

**Steps to reproduce the problem:**
Just have full Invader AM who cast skills from Isha tree. Nothing else.

**Testing Screenshots/Videos/Evidences (always needed):**
I cant make video. I'm not familiar with programs and stuff but made a series of screenshots with AOE heal spam with no time between casts. As we see buff is all time up and refreshing. 
![Kellanved_060](https://user-images.githubusercontent.com/46072429/59974857-399f4500-95b1-11e9-87a2-bd58453b9f92.jpg)
![Kellanved_061](https://user-images.githubusercontent.com/46072429/59974860-3c9a3580-95b1-11e9-88a9-3955406fae2c.jpg)
![Kellanved_062](https://user-images.githubusercontent.com/46072429/59974862-3f952600-95b1-11e9-84cd-e2c784a8939d.jpg)
![Kellanved_063](https://user-images.githubusercontent.com/46072429/59974863-41f78000-95b1-11e9-9dd3-296cd18684b7.jpg)
![Kellanved_064](https://user-images.githubusercontent.com/46072429/59974865-4754ca80-95b1-11e9-9476-21b1aa2748ef.jpg)
![Kellanved_065](https://user-images.githubusercontent.com/46072429/59974866-49b72480-95b1-11e9-80fe-6efa000c00b4.jpg)
![Kellanved_066](https://user-images.githubusercontent.com/46072429/59974868-4cb21500-95b1-11e9-8309-0c1fa003025a.jpg)
 And no. Im not that lucky to get 6 times proc with 10% chance to proc :P

**Comment by Lithliel** [comment]
oh.. and on state of realm we can see timer on objective in first 4 screenshots :)

**Comment by grunbag** [comment]
Fixed for next patch

**Comment by sioding** [comment]
fixed with patch from 29.6.2019
