### ISSUE TITLE
Throat Bite

### ISSUE THREAD

**Issue by userkilller** [WarEmu/WarBugs#14460]
Throat Bite doesn't apply damage to its target, only silence component is applied.

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format.

**Comment by kyranria** [comment]
not a bug, https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=30165

Hotfix - Throat Bite - Damage component removed.
