### ISSUE TITLE
Tier 1 Epic Quest - Among the Shadows, incomplete

### ISSUE THREAD

**Issue by lilimx** [WarEmu/WarBugs#14463]
Hey,

after you introduce the new T1 Epic Quest - Among the shadows, i'll try to complete the quest. After step ~10 (not quite sure). I should talk to **Gaelnielle Whitewing** (Charce - Chapter 4), the quest chain suddenly ends without a following quest nor loot.

I took a look at the RoR wiki and found this:
https://wiki.returnofreckoning.com/index.php/High_Elfs_T4_Epic_Quest_Among_the_Shadow
which told me, that there must be a kill quest, given from **Gaelnielle Whitewing**, which I have never gotten. (I even found and killed Lirith Darksong but nothing happend)

![Lillet_182](https://user-images.githubusercontent.com/23266079/59964457-727fe100-9501-11e9-9c10-b79e3ed7723b.jpg)

**Comment by Lheana** [comment]
Firstly, instructions on RoR Wiki haven't been updated yet, will be done asap.
Then, from what I can see, the step where you stopped is one starting from an object. Try to interact with Memory Stone at Major Landmark "The Everstar Stone".

**Comment by Lheana** [comment]
Note: Instructions have been updated on RoR Wiki.

**Comment by lilimx** [comment]
hey,
 
thank you for updating the wiki. So the problem is, after I turn in step 12 and spoke to Gaelnielle Whitewing, I don't get any further quest. I've tried to click on the stone, which one you mean, but nothing happen. I've got the clicky hand, but nothing rly happend. 

![Lillet_183](https://user-images.githubusercontent.com/23266079/59967911-ab37ae80-9531-11e9-966b-23c12f19cda3.jpg)

**Comment by lilimx** [comment]
hey,

thank you for the wiki update. After I turn in step 11 (_Then speak to Gaelnielle Whitewing at High Elf Chapter 4_) I didn't recieve the quest for step 12. So I've tried to reproduce your suggestion to interact with the Memory at Major Landmark "The Everstar Stone, but nothing happend. The same with the 'Memory Stone' outside the Flamescale Caverns. I've got the clicky hand to interact but nothing more.


![Lillet_183](https://user-images.githubusercontent.com/23266079/59968029-82b0b400-9533-11e9-8841-165726354d70.jpg)
_'Memory Stone' outside the Flamescale Caverns_


![Lillet_185](https://user-images.githubusercontent.com/23266079/59968032-88a69500-9533-11e9-8398-ffa4bf8e38a5.jpg)
_'Memory Stone' at the Major Landmark 'The Everstar Stone'_

**Comment by Lheana** [comment]
Then try to interact with the Rubric of Betrayal.

**Comment by lilimx** [comment]
hey,

I've clicked on the Rubic and he glows but nothing more. Then I killed Lirith Darksong, but no reaction from Gaelnielle Whitewing.

![Lillet_187](https://user-images.githubusercontent.com/23266079/59968356-ea1d3280-9538-11e9-8f61-a7838d91e145.jpg)

**Comment by Lheana** [comment]
Indeed I made a mistake, my fault.

**Comment by sioding** [comment]
fixed with patch from 29.6.2019
