### ISSUE TITLE
Sorc's staffs from City Dungeons.

### ISSUE THREAD

**Issue by Ripliel** [WarEmu/WarBugs#14469]
Both influence staffs have almost equal stats with equal procs.
Not sure if it's supposed to be like this. 
![Meridin_071](https://user-images.githubusercontent.com/16005849/59980736-91b26780-9602-11e9-9dd0-0f18a78cff1f.jpg)
![Meridin_072](https://user-images.githubusercontent.com/16005849/59980737-92e39480-9602-11e9-94c3-1f9b168c0512.jpg)

**Comment by wargrimnir** [comment]
Not correct, and staffs are supposed to have 2 procs. I'm looking into this...

**Comment by wargrimnir** [comment]
Added missing procs

**Comment by sioding** [comment]
fixed with patch from 10.08.2019
