### ISSUE TITLE
Sewer Search: Resist & Bite displays incorrect kill count.

### ISSUE THREAD

**Issue by plebeiancrusher** [WarEmu/WarBugs#14461]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**
The quest indicates that five enemy players must be killed, but the actual requirements are set to 15 players being killed.  The Destruction-equivalent quests all require the five enemy player kill count.

**Steps to reproduce the problem:**
Accepted the Sewer Search: Resist & Bite quest in Altdorf on a rank 15 character.

**Testing Screenshots/Videos/Evidences (always needed):**
![Yorvak_001](https://user-images.githubusercontent.com/50555776/59963624-d5eb1e00-94c3-11e9-899f-dbc9b8a04608.jpg)
![Yorvak_002](https://user-images.githubusercontent.com/50555776/59963625-d7b4e180-94c3-11e9-898f-2f52d3015c29.jpg)

**Note:**
I saw there was another Sewer Search quest related to this but that the kill count was not the question, but why the counts were not working in certain areas.

**Comment by sioding** [comment]
Fixed with patch from 06.10.2019
