### ISSUE TITLE
The heritage of War, The shame of war, The fallen of war.. missing rewards.. seal of the exemplar/paragon..

### ISSUE THREAD

**Issue by fixfax86** [WarEmu/WarBugs#14472]
seal of the exemplar/paragon rewards missing in these quests mentioned in thread title.. is it a bug or removed on purpose.. was rewarded on earlier date..

**Comment by Kabucoror** [comment]
The quests you mentioned never rewarded them. You mean The Grudges of WAR etc.

**Comment by fixfax86** [comment]
Nevermind, I just thaught so..
