### ISSUE TITLE
Tar covered mug should not be bind on pickup

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#14473]
**Expected behavior and actual behavior:**

Trash item with no purpose, so it shouldn't be bind on pickup.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Lotharic_225](https://user-images.githubusercontent.com/7400/60056104-0effda00-96e0-11e9-9997-393d80281e90.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 23.07.2019
