### ISSUE TITLE
Serpent's Passage objective not restarting upon entering the spawn

### ISSUE THREAD

**Issue by faktorfaktor** [WarEmu/WarBugs#14475]
**Expected behavior and actual behavior:**
I ran into the spawn on Serpent's Passage while carrying the part and the part did not reset even though it definitely should.

**Steps to reproduce the problem:**
just run into the spawn (destro) with the part

**Testing Screenshots/Videos/Evidences (always needed):**
i dont have a video of it happening but a gm witnessed it so u can ask him that it really happened https://i.imgur.com/ZD6DoJ8.jpg

**Comment by grunbag** [comment]
That was me , I'll move the guard and spawn point on the boat for next patch .

**Comment by faktorfaktor** [comment]
ok, i legit didnt mean to abuse any bug at all i just assumed the flag always resets like in every other scenario

**Comment by grunbag** [comment]
I thought it was a bug but in fact it seems nothing is done to prevent that so my mistake , I apologise for the warning . I'll try to find a solution for next patch

**Comment by grunbag** [comment]
warcamp is moved back for next patch

**Comment by sioding** [comment]
fixed with patch from 29.6.2019
