### ISSUE TITLE
quest no bats in Fellwing Cave 

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#1447]
for this quest On Fell Wings.. Order in MoM.

This cave at 49000,40300 seems like it is missing the bats required to complete the quest 
On Fell Wings.

thx

**Comment by Reggaewaldo** [comment]
That my dear sir is because the bats are in another castle . . . ehm cave. See attached screenshot.
![map](https://cloud.githubusercontent.com/assets/13517919/10005437/8f69540e-60b7-11e5-8f8c-2a66eaeaf0ee.png)

Verified functionality. 

Closing.
