### ISSUE TITLE
[Quest] Crushing stone (2)

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#14477]
Rugni Stonebrow can be killed and drops head. But when you put it on pike quest objective does not complete.
Locations of pikes:
56,0-35,4
52,7-33,6
54,1-35,0
55,4-34,1

**Comment by Rockalypse** [comment]
![Veszal_132](https://user-images.githubusercontent.com/42712833/60137494-c0217580-97af-11e9-896a-0b8e87d711e3.jpg)

**Comment by Lheana** [comment]
As mentioned in the quest, you must pike it on **a pike at the top of the castle**.

**Comment by Rockalypse** [comment]
@Lheana yes, have to read through quest description slower. Ones on top of steps work. Got confused because map mark was whole castle territory and those mentioned were placed conviniently nearby.
