### ISSUE TITLE
Bloodlord Herald (Bastion Stair Influence Shield) unique bonuses bug.

### ISSUE THREAD

**Issue by Erwelin** [WarEmu/WarBugs#14476]
This shield should increase damage bonus by 5% and decrease armor and toughness by ??%

![The Shield](https://user-images.githubusercontent.com/46405832/60123909-79536180-9756-11e9-8d85-864294ece8ba.jpg)

The damage bonus works fine but armor gets decreased by 10% and toughness stays the same.

.getstat w/o the shield

![no shield](https://user-images.githubusercontent.com/46405832/60123971-a0aa2e80-9756-11e9-8ab5-5889364494c8.jpg)

.getstat w the shield

![Bloodlord Herald Equipped](https://user-images.githubusercontent.com/46405832/60123976-a43db580-9756-11e9-8512-72dee8079749.jpg)

**Comment by grunbag** [comment]
I'll fix that tomorrow

**Comment by dalen** [comment]
> The damage bonus works fine but armor gets decreased by 10% and toughness stays the same.
> 

isn't your toughness actually increased by 5% in the second screenshot?

healing seems increased by 5% as well btw. Seems reasonable to fix https://github.com/WarEmu/WarBugs/issues/14323, but not sure if all weapons should increase both damage & healing by 5%.

**Comment by SecretsOTheP** [comment]
> 
> 
> > The damage bonus works fine but armor gets decreased by 10% and toughness stays the same.
> 
> isn't your toughness actually decreased by 1% in the second screenshot? It should be 669 (629+40), but is 662.
> 
> healing seems increased by 5% as well btw. Seems reasonable to fix #14323, but not sure if all weapons should increase both damage & healing by 5%.

Toughness in the 2nd screenshot is reduced by 0.1% - it should be decreased by 10% instead.

**Comment by grunbag** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 29.6.2019
