### ISSUE TITLE
[quest] The queen mother's blade

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#14471]
There is quest in Eataine with mentioned name, it can be taken from Debris pile inside Spirits of Eataine PQ.
Reward is grey Item with no properties.
![Veszal_120](https://user-images.githubusercontent.com/42712833/60038875-1adaa480-96be-11e9-9626-a7da05979893.jpg)
![Veszal_122](https://user-images.githubusercontent.com/42712833/60038876-1adaa480-96be-11e9-8f06-a0564d81a780.jpg)
![Veszal_121](https://user-images.githubusercontent.com/42712833/60038877-1b733b00-96be-11e9-980d-a9bbad369cbd.jpg)

**Comment by Lheana** [comment]
This is intended, every easter egg quest gives this kind of rewards, and it was like that on official.
