### ISSUE TITLE
Ritual of Corruption Public Quest Bug

### ISSUE THREAD

**Issue by JoelKirkby** [WarEmu/WarBugs#14478]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**
Expected: Public quest to spawn 2 monsters , Satalora Terrorclaw, Vathrix Lifebleeder, and Destroy the Altar

Actual: Doesn't spawn either of the two monster

**Steps to reproduce the problem:**
Stage 3 of the public quest. Complete stage 2 to reproduce problem

**Testing Screenshots/Videos/Evidences (always needed):**
![Runecrafting_003](https://user-images.githubusercontent.com/39950909/60143827-4cff0b80-977d-11e9-8b4d-941a65dbcc99.jpg)

Screenshot is no spawns

**Comment by Lheana** [comment]
Not bugged at all, you just haven't searched at the right place. Search harder.
