### ISSUE TITLE
[PQ] Dragon's Blessing - Many of the Dragon bones can't be attacked

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#14486]
**Expected behavior and actual behavior:**

out of the 15 Dragon Bones in stage 1 only 4 seem to be attackable. And they don't respawn, so you can't complete this PQ without destroying all of them.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Lotharic_233](https://user-images.githubusercontent.com/7400/60294975-df8cdf80-9922-11e9-82f8-b0668c03c9e5.jpg)

**Comment by Tibdum** [comment]
Can confirm
![Tibdum_595](https://user-images.githubusercontent.com/47664666/60295340-29c68e80-992c-11e9-9eca-d742978d4c96.jpg)
![Tibdum_596](https://user-images.githubusercontent.com/47664666/60295341-2a5f2500-992c-11e9-813d-9d7b41fe0396.jpg)

**Comment by sioding** [comment]
fixed with patch from 06.07.2019
