### ISSUE TITLE
DWARF STORYLINE CH16 PQ - Gates of Grung Grimaz

### ISSUE THREAD

**Issue by Tibdum** [WarEmu/WarBugs#14480]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

Expected behavior and actual behavior:

After killing once the Bolt Throwers, they respawned with 0 HP and the sword cursor changed into a hand. 

Steps to reproduce the problem:

I tried from various positions to interact with them, even tried to AoE. Same thing. You click them, they disappear and no quest update

Testing Screenshots/Videos/Evidences (always needed):

![Tibdum_593](https://user-images.githubusercontent.com/47664666/60156414-2e3c5b80-97f5-11e9-92b6-aaff1a4bf38a.jpg)
![Tibdum_594](https://user-images.githubusercontent.com/47664666/60156416-2e3c5b80-97f5-11e9-8dc3-2a4b8a7d147b.jpg)

**Comment by sioding** [comment]
fixed with patch from 06.07.2019
