### ISSUE TITLE
[Game Object] Tomb of Hannarr

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#14481]
Tomb of Hannarr is object that you have to interract with during one of greenskin quests in chapter 20.
Right now it is located in two places - 59-48 on side of the road and in great cave in Baradum PQ nearby with ancestral guard and etc. Seems like pbject that is placed on side of road is duplicate and mistake.

**Comment by Lheana** [comment]
Thanks for the report, indeed this spawn has nothing to do here. Will be fixed with next patch.

**Comment by sioding** [comment]
fixed with patch from 29.6.2019
