### ISSUE TITLE
[Vendor] Skullspiltta Badaxe Royal Quartermaster

### ISSUE THREAD

**Issue by Sh4ndox** [WarEmu/WarBugs#14489]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**
I have 45 Invader Medallions and try to buy Invader Change Gem that costs 43 Invader Medallions, after confirm nothing happens, still have 45 Medallions and no item in my backup. No message was displayed on chat window. 
Just to add I play Chosen RR 64, so also have the requeriment to equip it.
Didn´t try to buy any other item since I want to use the medallions for this one.
When repeat it 3 times game auto closed, so I restart the launcher and log again, and same thing happens.

**Steps to reproduce the problem:**
NPC on Destro side IC Citadel. Try to buy a Invader Change Gem (Chosen class) having the necessary Medallions.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by wargrimnir** [comment]
The gem can only be purchased after the rest of the set is completed. This is intended.
