### ISSUE TITLE
Bug on Guild Banner

### ISSUE THREAD

**Issue by Liamelx3m** [WarEmu/WarBugs#14488]
Hi,
I wanted to report this bug:
I can't place my guild banner, keep telling me I'm not in a guild, but I'm the GM of the Steel Clan.

waiting for an answer,
Sincerely.
Lelaell Liamel

**Comment by sioding** [comment]
And you are the banner bearer? We need screenshots

**Comment by sioding** [comment]
No answer since 1 month - close
