### ISSUE TITLE
item no stats Salutary Clogs

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#1449]
item no stats Salutary Clogs

RP item.

**Comment by Evildoor** [comment]
And?
http://war.mmodb.com/items/salutary-clogs-63036.php
http://www.warbits.com/gold-items-25928-Salutary-Clogs.html
There are white items in the game, which don't give stats.
http://www.warbits.com/gold-quests-1451-Encroaching-Darkness.html
Look at this quest, it gives similar white statless boots to everyone.

**Comment by gittoaster** [comment]
just sayin, it's a quest reward not a trash item.

/p
