### ISSUE TITLE
Beerthirstin' squigs in engine Number Nine are not targetable

### ISSUE THREAD

**Issue by scrrugga** [WarEmu/WarBugs#14495]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**
t1 dwarf - Ekrund side - engine number nine pq -  Squigs spawned in the last part of the pq should be target able.
Unable to target them

**Steps to reproduce the problem:**
get to the third part of the pq after the broken barrels that can be spam clicked, then you'll be unable to target the squigs.
white lion pets can though!

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/52348057/60382915-78e7fd00-9aad-11e9-90b3-a93e796819d6.png)

**Comment by sioding** [comment]
fixed with patch from 06.07.2019
