### ISSUE TITLE
[Bastion Stair] Chorek the Unstoppable - DC Jail

### ISSUE THREAD

**Issue by Zoggof** [WarEmu/WarBugs#14498]
If you get sent to prison by the fire sprites on Chorek the Unstoppable in Bastion Stair, there is a high chance you will get disconnected on leaving jail. This leads to the potential of missing kill contribution for quest or loot drop. Has happened multiple times when talking with others.

**Comment by Kaelang** [comment]
This doesn't seem to happen on the live versions of RoR - please re-open this issue if you are still experiencing such DC's as this report has not been referenced, or echoed across the community since you first uploaded this almost a year ago.
