### ISSUE TITLE
Bug masks. 

### ISSUE THREAD

**Issue by Elflord123** [WarEmu/WarBugs#14491]
I can't change my appearance. Bug masks, is it possible to replace?
![Knyaz_010](https://user-images.githubusercontent.com/48329663/60356387-7916c880-99d9-11e9-8cb9-28ae807a3784.jpg)

**Comment by grunbag** [comment]
what are you trying to do exactly?

**Comment by Elflord123** [comment]
to replace the exterior of the helmet on these masks. It can't be done

**Comment by grunbag** [comment]
Give me the mask name

**Comment by Elflord123** [comment]
[Mask of the Bloodletter], [Gaping Skull Mask],[Delicate Silver Mask] , [Face of the Unborn]

**Comment by grunbag** [comment]
You want to add the mask appearance on your help appearance ?

**Comment by Elflord123** [comment]
Yes, but gives an error in the photo it is shown in the chat

**Comment by grunbag** [comment]
Cause it’s blocked by the client

**Comment by Elflord123** [comment]
What should I do? These masks I got for the event

**Comment by grunbag** [comment]
Why you want to equip them ?

**Comment by grunbag** [comment]
Maybe a coder can help you

**Comment by sioding** [comment]
Wait for the next event we hand out masks.
