### ISSUE TITLE
Dyre the Heartrender, initial destro quest-giver, not working.

### ISSUE THREAD

**Issue by lordgigan** [WarEmu/WarBugs#14499]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**
Expect to accept the quest she offers. But, not able to accept it.

**Steps to reproduce the problem:**
Clicking the quest yields no result. Nothing happens.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by MaxHayman** [comment]
This was fixed in a live hotfix at around 10pm server time.

Thanks for the report.
