### ISSUE TITLE
[ITEM] Equerry's Waraxe

### ISSUE THREAD

**Issue by Fikatind** [WarEmu/WarBugs#145]
This weapon should be a two handed Axe, not one hended. and as you see on a SS im using two hended weapon with one hended.
![fikatind_032](https://cloud.githubusercontent.com/assets/7502763/3109753/2c1d03c2-e69d-11e3-9108-0b272f456c79.jpg)

**Comment by Evildoor** [comment]
Great weapons are working now. Mentioned item is a proper twohander. Closing.
