### ISSUE TITLE
Scenario - Black Crag Keep spawn is inside of a mountain.

### ISSUE THREAD

**Issue by plebeiancrusher** [WarEmu/WarBugs#14503]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**
When entering the Scenario you are supposed to spawn on the road near the Orks as a Destruction player.  Currently it is spawning you off the road inside of a mountain.

**Steps to reproduce the problem:**
Upon entering the Black Crag Keep scenario as a Destruction player, you are dropped into water inside of a mountain near the road.  This happens when re-spawning from death as well.

**Testing Screenshots/Videos/Evidences (always needed):**
![Norendithas_028](https://user-images.githubusercontent.com/50555776/60391311-886d4300-9ab9-11e9-8524-22066a1a03b9.jpg)
![Norendithas_029](https://user-images.githubusercontent.com/50555776/60391312-886d4300-9ab9-11e9-82ca-4a8988ac646c.jpg)
![Norendithas_030](https://user-images.githubusercontent.com/50555776/60391313-886d4300-9ab9-11e9-8517-516e09a13e87.jpg)
![Norendithas_031](https://user-images.githubusercontent.com/50555776/60391314-899e7000-9ab9-11e9-8053-86bc7b3543f5.jpg)
![Norendithas_032](https://user-images.githubusercontent.com/50555776/60391315-899e7000-9ab9-11e9-8563-20040b242ba4.jpg)

**Comment by Lheana** [comment]
I could not reproduce it. Please tell if it still happens.

**Comment by sioding** [comment]
No answer since 26 days. Close
