### ISSUE TITLE
Interrupting with knockback skills

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#1450]
Successful knockbacks caused an interrupt on live.

**Comment by gittoaster** [comment]
I was noticing something strange with cast abilities getting stuck on being interrupted.  
I don't know what was causing it.

**Comment by Tesq** [comment]
no they don't, cast alredy started finished

**Comment by ozarmidrashim** [comment]
This issue is disputed. Please indicate the correct handling.

**Comment by Evildoor** [comment]
Ok, since @Tesq says that knockbacks should interrupt channeled abilities only, i started rummaging through youtube videos. Results so far:
https://www.youtube.com/watch?v=qwoEbbW3rZc - shaman video. At 1:53 Bunch o Waaagh gets interrupted by Engi knockback. Even though we agree on this point, i'm including this just to be sure that channeled abilities are interrupted.
https://www.youtube.com/watch?v=tJdkmQ0xsBs - sorc video. At 6:54 - knockback and no interrupt of Doombolt due to Focused Mind. At 7:38 - WL pull, no interrupt of Doombolt.
https://www.youtube.com/watch?v=48GyjRxs4Xs - magus video. At 6:30 - Bolt Of Change interrupted by KotBS knockback.
Any additional clarifications are welcome.
