### ISSUE TITLE
Bestial Token Trophies being restricted to specific races per faction(Greenskin vs Chaos)

### ISSUE THREAD

**Issue by Tyrannicus** [WarEmu/WarBugs#14508]
Why can't Greenskins buy the Unshaven Skull trophy? I had these heads on my Greenskin belts when the game was live. 

In the picture montage in the link below, a Goblin is clearly shown sporting an Unshaven Skull. I had 3 of these heads on both my Shaman and Squig Hunter when the game was live. Goblin with unshaven head is shown in the 2nd row from top, dead center. The tooltip even says "Orc, Goblin, Dark Elves, Chaos". 

Please address this bug. If it's a conceptual change with RoR, please reconsider this design change. 

https://www.returnofreckoning.com/forum/viewtopic.php?t=10828

**Comment by grunbag** [comment]
I’ll check that

**Comment by Tyrannicus** [comment]
Are bug report tokens still a thing? I found a vendor today that requires a bug report token and was wondering if this reporting forum is the venue for such tokens. Thx

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 13.07.2019
