### ISSUE TITLE
Purple loot bag not in mailbox after capturing south keep in Praag

### ISSUE THREAD

**Issue by Karrangus** [WarEmu/WarBugs#14509]
Hello,

Yesterday, we have captured the south keep in Praag. I won a Purple loot bag.
After that, we lock Praag.
But I didn't receive it in my mailbox.
And this morning, I received only a "Minor lot bag" on my mail box !

Maybe I must wait a 24 hours after the lock of the Praag ?
Can you fix it ? or send me an other Purple loot bag ?

Thank you, have a nice day.

Karrangus from Destruction side.

**Comment by sioding** [comment]
this is a known issue. You have to wait for the next server restart. 98% of all missing bags are delivered on that restart. Some are lost - the personal bag bonus prevents you from not getting enough bags. So hope for the next restart.
