### ISSUE TITLE
Sigmar's Shield not working

### ISSUE THREAD

**Issue by Minotaureus** [WarEmu/WarBugs#14501]
At 21 I selected Sigmar's Shield the first skill in Path of Grace tree for Warpriests. The skill says Im too low level to use even though it says its a lvl 20 skill. I do not have issues with the equivalent skill in the other 2 trees. I tried relogging several times with no luck.

**Comment by Minotaureus** [comment]
![Minotaureus_001](https://user-images.githubusercontent.com/52360417/60389630-8049df00-9a8a-11e9-98b3-10145028a36f.jpg)

**Comment by Minotaureus** [comment]
After some testing the skill does in fact work. But remains "red" on my tool bar.

**Comment by dalen** [comment]
This has been fixed as far as I can tell
