### ISSUE TITLE
New Recruits Quest Chaos

### ISSUE THREAD

**Issue by GarussAcine** [WarEmu/WarBugs#14500]
Title:

Quest not starting after interacting with the quest giver.

An introduction:
After completing the New Recruits quest on my original character, I logged into my second character and was unable to start this quest.
I am able to speak with the quest giver but it doesn't activate once selected.
I have logged out and exited game and this didn't change anything.
I skipped the quest line and was able to complete other quests further in the game.
Came back and was still unable to access this starting quest.
Created another chaos character and the issue still remains.
Created a greenskins character and the black orc was able to activate the quest.
After creating the new greenskin character I was able to access the quest on the new chaos characters.

Details:
So speaking with the quest giver should result in the quest being activated.

Evidence:

![image](https://user-images.githubusercontent.com/52358850/60388615-ed08ad80-9a79-11e9-9b47-e651236f9e9d.png)

![image](https://user-images.githubusercontent.com/52358850/60388677-98196700-9a7a-11e9-9864-de79b4c3a650.png)

**Comment by MaxHayman** [comment]
This was fixed in a live hotfix at around 10pm server time.

Thanks for the report.
