### ISSUE TITLE
[T1][Chrace][PQ] Blackwood Hill Garrison

### ISSUE THREAD

**Issue by Aluviya** [WarEmu/WarBugs#14518]
**Expected behavior and actual behavior:**
Some lvl 63-lvl 64 Warsieges spawn along (and sometimes inside) the actualy PQ relevant Reaper Bolts
![Aluvya_044](https://user-images.githubusercontent.com/17249318/60724331-63a02200-9f36-11e9-9600-cbc02479fbc7.jpg)

**Comment by sioding** [comment]
fixed with patch from 06.07.2019
