### ISSUE TITLE
RP armor proc without animation

### ISSUE THREAD

**Issue by domi23072015** [WarEmu/WarBugs#14517]
If the Zelo is the hot on it and the amor proc procen does so a golden animation with the sound accordingly. Unfortunately there is no animation at Runi. As soon as the buff is displayed in the bar, the zelo says that the armor pierce is reduced by 10%. The rp buff in the bar is only the amor number but not the 10%.

**Comment by sioding** [comment]
fixed with patch from 13.07.2019
