### ISSUE TITLE
wounds debuff doesnt go away

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#1451]
thounderous blow debuff persists through death and with 0 seconds forever. (normally have 7030 life).
same with master rune of furry buff.

![mago_012](https://cloud.githubusercontent.com/assets/13809443/9977824/ff63d90e-5f14-11e5-9af6-b0294c1a6d60.jpg)

**Comment by Tiggonos** [comment]
prbly same:

https://github.com/WarEmu/WarBugs/issues/1435

**Comment by Evildoor** [comment]
Closing per #1435.
