### ISSUE TITLE
Texture bug in order's Fort

### ISSUE THREAD

**Issue by Azufelo** [WarEmu/WarBugs#14512]
Hi, 

There are angles in order's Forteresse that if you jump from 1st floor or 2nd floor, you got stuck inside. You can't move away. Doing /Rel or /stuck didn't work too. 
Sometimes a quick 2x /stuck work or you need to be killed.

**Comment by sioding** [comment]
Sorry but this doesn't help. We need screenshot from the places you have been stucked in.

**Comment by sioding** [comment]
No answer since 1 month - close
