### ISSUE TITLE
displayed and acting as dead

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#14511]
got instakilled after being resurrected and found myself in this limbo where ui says you've plenty of health, still getting heals and damage, while you're splatted on the ground unable to move/cast (ui says "you are dead") and the respawn dialog does not appear: maybe similar to #11407.

![Chimp_063](https://user-images.githubusercontent.com/17765890/60483084-49471980-9c94-11e9-8f82-adc3ea634bb7.jpg)

**Comment by sioding** [comment]
Yes it seems the same - so i close this one and leave it metionend in #11407
