### ISSUE TITLE
Escape Key not working

### ISSUE THREAD

**Issue by Ninhi** [WarEmu/WarBugs#14514]
Escape was working prior to Alt-Tabbing out of the game. After coming back into the game by clicking on the icon in Task Bar the ESC key is no longer working. I have not had the issue prior to this.

After exiting out using the Main Menu option and logging back in the ESC key worked.

**Comment by wargrimnir** [comment]
The client doesn't manage keybinds like that. It was more likely your OS not re-hooking after alt-tabbing. Use Borderless Windowed mode, it's faster anyway.

Not a client issue.
