### ISSUE TITLE
Bloodlord Claymore issue

### ISSUE THREAD

**Issue by dadkkak** [WarEmu/WarBugs#14513]
Hey, just got the first inf weapon - Bloodlord Claymore - on Kotbs, but I can't equip it. I got full sentinel and can equip Bloodlord armor, but i'm missing gloves for the full ward. Is that a bug or I should be able to equip Claymore only when I complete the rest of BL armor? On WH I could get full BL before the 2 weaps, so I didn't have the chance to test it. Thanks

**Comment by sioding** [comment]
Duplicate of #14496
