### ISSUE TITLE
Npc missing in Kazad Gromar 

### ISSUE THREAD

**Issue by Murthor** [WarEmu/WarBugs#14515]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**  There is an Npc missing in Kazad Gromar I don't recall his name but he is supposed to be next to the npc called Mornina Rocksworn, There is no body there to signify a dead npc, there is simply no npc there period. 

**Steps to reproduce the problem:**  There are no steps, the npc is just not there. 

**Testing Screenshots/Videos/Evidences (always needed):**  
![Murthor_003](https://user-images.githubusercontent.com/52479032/60561584-06338780-9d22-11e9-87b3-6128762c5cbb.jpg)

**Comment by sioding** [comment]
Well this will be tricky to find the npc you are missing. Any more information you can give for the database devs`? Like what he is doing? maybe a quest he usually gives? otherwise it will be hard.

**Comment by Murthor** [comment]
He is a merchant and a quest giver I believe.

**Comment by Kabucoror** [comment]
Probably you mean Burli Durinsson, he is one of the crafting quest giver and walks along the main road in dwarf t4.

**Comment by sioding** [comment]
answer given - close
