### ISSUE TITLE
[T3][Talabecland][PQ]Unterbaum Cemetary Stage II

### ISSUE THREAD

**Issue by Aluviya** [WarEmu/WarBugs#14520]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**
The carts can be "used" in order to activate a visual burning effect, but doesn't count for the PQ step unless you attack and destroy the carts
![Aluvya_036](https://user-images.githubusercontent.com/17249318/60725250-e6c27780-9f38-11e9-9005-e6d5f6dc0c41.jpg)

**Comment by Lheana** [comment]
Well you are meant to destro them so there is no problem completing the PQ...

**Comment by sioding** [comment]
answer given - close
