### ISSUE TITLE
Soldier's Healing Draught is healing for a negative value (dealing self dmg)

### ISSUE THREAD

**Issue by chouxfleur** [WarEmu/WarBugs#1452]
![Uploading 001.jpg…]()

Killed myself with Soldiers Healing draught on Nordenwatch in a duell with an IB

**Comment by milosxe** [comment]
Can you reupload the screenshot, please?

**Comment by Halhammer** [comment]
![gundoom_051](https://cloud.githubusercontent.com/assets/13981830/9978470/08bc5d52-5f31-11e5-8b64-20121352925e.jpg)

**Comment by Halhammer** [comment]
Eh the '-' is hard to see but it reads 'minus 1100'

**Comment by milosxe** [comment]
I confirmed the issue. Potion of Healing is healing for a negative value of 1100.
![shiznit_005](https://cloud.githubusercontent.com/assets/13332067/9978512/690d00e2-5f33-11e5-9448-841a665e3026.jpg)

**Comment by chouxfleur** [comment]
how u guys upload the screenshot . i get always this
![Uploading 001.jpg…]()

**Comment by ozarmidrashim** [comment]
Notes to taggers:

- Any issue with a skill or skill-like ability (item effects) should be tagged as Ability
- Any issue tagged as Ability should be assigned to me
