### ISSUE TITLE
[T1][Chrace][PQ] Elisia Step II

### ISSUE THREAD

**Issue by Aluviya** [WarEmu/WarBugs#14524]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**
This PQ used to work ( i am very sure, since i have the Tome entries) however clicking on the Southern Uthorin Banner doesn't provide any credit to the Step anymore- so can't continue the PQ to Step III
![Aluvya_038](https://user-images.githubusercontent.com/17249318/60731531-14fb8380-9f48-11e9-8607-db0abcf6d8bd.jpg)

**Comment by sioding** [comment]
fixed with patch from 06.07.2019
