### ISSUE TITLE
[Gunbad] Broken roll on "Shadowweb Spawning Grounds"-PQ

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#14528]
After completing the PQ "Shadowweb Spawning Grounds" in the middle wing we got the message "You didn't contribute enough,..." and than this showed up.
![broken_roll](https://user-images.githubusercontent.com/40274248/60737375-da4f1680-9f5a-11e9-9da4-d4e48f3b52c8.jpg)
(rolled for 200+ rewards?)

No roll was shown, the window stayed until the timer ran out. Nevertheless we all could loot the box and got bags.

**Comment by sioding** [comment]
Not sure if this is a real thing. As far as i remember - that was the time the complete server does weird things

**Comment by Scophis** [comment]
Don't know either^^ It's not acting normal, so it goes on the Bugtracker ;)
We did the run last Thursday (04.07) around 8pm altforf-time.

**Comment by raptrr** [comment]
@Scophis did it happen to you again by this date? :)

**Comment by Scophis** [comment]
Happened at least once again, but it's been a while since I went to GB.
Gonna try to get a run this week.

**Comment by raptrr** [comment]
Ok, nice. Thanks in advance.
