### ISSUE TITLE
[AM][Ability] Magical Infusion

### ISSUE THREAD

**Issue by Aluviya** [WarEmu/WarBugs#14526]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**
The description to this ability(mouseover) seems not to match the ability description on a target. Is it either 20 % or 25 %? I can't test it.
![Aluvya_044](https://user-images.githubusercontent.com/17249318/60735114-6741a200-9f52-11e9-92e6-af398776f8ac.jpg)
![Aluvya_043](https://user-images.githubusercontent.com/17249318/60735115-6741a200-9f52-11e9-982b-958395922802.jpg)

**Comment by grunbag** [comment]
25% is correct value

**Comment by sioding** [comment]
fixed with patch from 13.07.2019
