### ISSUE TITLE
[T3][Talabecland][PQ] Meuselbach Farm Stage II

### ISSUE THREAD

**Issue by Aluviya** [WarEmu/WarBugs#14521]
**Expected behavior and actual behavior:**
Again, "Wagons burned" only counts if you attack and destroy the wagons. Just clicking on them activates a burning, visual effect (which doesn't count).

![Aluvya_035](https://user-images.githubusercontent.com/17249318/60725841-5a18b900-9f3a-11e9-9727-ce73707635ab.jpg)

**Comment by Lheana** [comment]
You are meant to destroy the wagons, so nothing prevents you from completing the PQ.
