### ISSUE TITLE
[T4]Wounds debuff awarded for entering Gates Scenario from PVE Warcamp

### ISSUE THREAD

**Issue by Tyrannicus** [WarEmu/WarBugs#14527]
Character level is 34. I was crafting in a PVE Warcamp and picking up a Beastlord quest. Hadn't been in combat at all and hadn't died in several hours so no chance of wounds debuff. 

Upon entering Gates of Ekrund scenario I received a 10 minute wounds debuff.

**Comment by sioding** [comment]
Not sure if this is a real thing. As far as i remember - that was the time the complete server does weird things. i leave this open for two weeks - maybe it happens again.

**Comment by sioding** [comment]
As is said - no more info for this so: close
