### ISSUE TITLE
Bloodrage Talisman

### ISSUE THREAD

**Issue by Lefze** [WarEmu/WarBugs#14535]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**

Strikethrough talismans from Bastion Stair/Gunbad quests cannot be slotted.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/31864442/60758910-409c6d80-a01d-11e9-909d-a58d2f99c511.png)

![image](https://user-images.githubusercontent.com/31864442/60758907-37130580-a01d-11e9-928b-32a2ae56bc94.png)

**Comment by wargrimnir** [comment]
Added Talisman flag and made Unique Equipped

**Comment by sioding** [comment]
fixed with patch from 10.08.2019
