### ISSUE TITLE
[Crafting] Can't move  "Plague-touched High-Cap Toody's Hat" to crafting bag

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#14530]
As the title says^^ 
![Bixo_022](https://user-images.githubusercontent.com/40274248/60738196-c22cc680-9f5d-11e9-836e-59c421b9897c.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 19.10.2019
