### ISSUE TITLE
Annihilator Chest Piece/Choppa

### ISSUE THREAD

**Issue by MuzaMeis** [WarEmu/WarBugs#14534]
Recently purchased the Annihilator chest piece for choppa class. Except the healing function on it('60 hp every 4 secs') doesn't work at all, tested it many times. Un-equiping, logging out, switch out pieces. Nothing seem's to make it work. Nobody on advice knows why.

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format.

**Comment by MuzaMeis** [comment]
Someone just alerted me that it does NOT show up in the combat log. It just happens in the background, I see it's working now.
