### ISSUE TITLE
Bastion Stairs Bloodlord Daemonstaff

### ISSUE THREAD

**Issue by panodill** [WarEmu/WarBugs#14537]
I know there was other report on this but it was closed.

****Expected behavior and actual behavior:****
Cant equip my staff from Bloodlord, it does say i need Tomb of Knowledge entry to equip.
i have full ward, even have bloodlord armor on me.

**Steps to reproduce the problem:** 
Try to equip.

**Testing Screenshots/Videos/Evidences (always needed):**
https://i.imgur.com/vSHxiuz.jpg

**Comment by wargrimnir** [comment]
Couldn't find anything wrong with this one. Someone might have fixed it already.

Check pls

**Comment by grunbag** [comment]
I fixed it already
