### ISSUE TITLE
x2 Bloodlord Axe (Slayer) equipped missing bonus

### ISSUE THREAD

**Issue by Niateneri** [WarEmu/WarBugs#14538]
Hello
When you equip 1 Bloodlord Axe everything is alright and works properly
If you try to equip 2 Bloodlord Axes at the same time, 2nd weapon bonus ability (+5% DMG, - wounds and -armor) does not work - only bonus ability from 1 weapon.
2nd weapon stats apply properly
Is that a bug or is it intended?
![Rysze_005](https://user-images.githubusercontent.com/52612088/60761705-a6f1b200-a056-11e9-87e0-7e7870a09dd3.jpg)
![Rysze_006](https://user-images.githubusercontent.com/52612088/60761706-a78a4880-a056-11e9-8c67-f87bb198380f.jpg)
![Rysze_007](https://user-images.githubusercontent.com/52612088/60761707-a78a4880-a056-11e9-8487-9ca32eca8939.jpg)
![Rysze_004](https://user-images.githubusercontent.com/52612088/60761708-a78a4880-a056-11e9-94f8-e52e20584dcd.jpg)

**Comment by wargrimnir** [comment]
Intended. Same bonuses typically don't stack.
