### ISSUE TITLE
Engineer Turret 65ft range instead of 100ft

### ISSUE THREAD

**Issue by Jaycub** [WarEmu/WarBugs#1453]
Tested by standing directly on top of turret, seems to only fire if you are within 65ft (acid bomb) but will not fire at any higher ranges when the pathing is valid (gun blast will work).

Only tested gun turret.

**Comment by Jaycub** [comment]
Another engineer in game was able to confirm the same thing.

**Comment by milosxe** [comment]
Same with Spiked and Gas Squig. They always go to ~65 ft range to attack. Can be easily tested in PvE. In <65 ft they attack straight away, without moving. In 65 to 100, they move closer.

**Comment by bobeer86** [comment]
Id vote against fixing those while los check isn't implemented. last thing we need in keep sieges is getting blown to pieces through walls from even longer range.

**Comment by Jaycub** [comment]
It's always been 100ft, just the recent patch seemed to break it. The armor debuff attached to the turret is central to the engineers ability to deal single target damage atm, and leaving it gimped at 65ft is a huge nerf.

**Comment by ozarmidrashim** [comment]
Currently the database tool used by a number of people to interact with the DB recognises the "Ranged" field as a boolean. I'll need to let Nal know that it should be changed to an integer. Until then I can't do much about this one.

**Comment by Evildoor** [comment]
Seems to be fixed (at least on dev server), i was able to hit mobs with gun turret while being at Gun Blast distance.
