### ISSUE TITLE
[Item] Matchlock of the Ravener

### ISSUE THREAD

**Issue by Algenubi** [WarEmu/WarBugs#14532]
Item named 'Matchlock of the Ravener' is an Empire pistol, so that's it's wh weapon. Its stats are: weapon skill, ballistic skill, parry. I think that ballistic skill should be replaced by strength.

![Ainudallire_005](https://user-images.githubusercontent.com/20935691/60757587-4e4df500-a015-11e9-8f42-b6418e767111.jpg)

**Comment by wargrimnir** [comment]
Empire pistols should indeed have strength, corrected 15 items that I found.

**Comment by Algenubi** [comment]
Is it already applied? I see no changes in game.

**Comment by sioding** [comment]
fixed with patch from 13.07.2019
