### ISSUE TITLE
[Highelf Chapter 5] Two Quests did not work

### ISSUE THREAD

**Issue by Lindiranae** [WarEmu/WarBugs#14545]
**1. Questname: Shades**
Had to kill Uthorin Deathstalkers and Silentblades. Kill many of both in the marked area but they did not count.

**2. Questname: Balance Renewed**
Had to kill Cold Ones and Free Animals. Killed all Cold Ones but in the whole marked area there are no traps with animals to free.

**Comment by sioding** [comment]
Thanks for the report. Next time please: one problem per report.

**Comment by Lheana** [comment]
I guess you were grouped when you tried to do these quests?

**Comment by Lindiranae** [comment]
No I was solo when i tried. No group.

**Comment by Lheana** [comment]
For the trap, I can only advice you to search harder.
For the quest Shades, there was a mistake, it will be fixed with next patch.

**Comment by Lindiranae** [comment]
Thanks for your help. =)

I checked the Quest "Balance Renewed" with another of my Chars today and found a trapped animal just in the moment as i reached area. I will try to do it again tomorrow with my SW.  :-)

**Comment by iwka53** [comment]
i have been searching area for like 20 minutes.. no trapped animal..just one stag in a trap but i couldnt clicked it..please please dont tell it was this bugged stag..

**Comment by Lindiranae** [comment]
Ok now it works with my SW. But it is exactly one trap in the whole area. All other stags are walking around or stand still without any  trap. 

![Alorelle_000](https://user-images.githubusercontent.com/52664952/61183568-237e2500-a643-11e9-8868-75ba3d2c1d89.jpg)

**Comment by Lheana** [comment]
Indeed you have to free this stag by clicking on the trap.

**Comment by sioding** [comment]
fixed with patch from 23.07.2019
