### ISSUE TITLE
Chasing Oathgold T2 Dwarf Epic Quest

### ISSUE THREAD

**Issue by Krathin225** [WarEmu/WarBugs#14544]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**
The quest is to go talk to Dormir Karakshot but when you arrive the NPC is no where to be found where ever you look within the search area thus you cant progress the quest line

**Steps to reproduce the problem:**
Goto 55000-59000 and the NPC you need to talk to is not there or anywhere around it

**Testing Screenshots/Videos/Evidences (always needed):**
![Arnhuldt_000](https://user-images.githubusercontent.com/52640713/60776706-18377080-a0fc-11e9-86fb-9388e121f38e.jpg)

**Comment by Lheana** [comment]
Related to #10862.
The best you can do is wait for a server restart and check if NPCs of the PQ are correctly spawned.
