### ISSUE TITLE
Gunbad rally master

### ISSUE THREAD

**Issue by Lefze** [WarEmu/WarBugs#14549]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**

Gunbad rally master doesn't work. Doesn't have the icon over her head, and can't choose rewards, even though I have completed the whole bar.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/31864442/60909768-5f01a380-a27f-11e9-9578-c85f3073db68.png)

**Comment by Kaelang** [comment]
Gunbad rework has since been completed and a lot of these issues will have now been addressed as per the recent rework. Please re-open this ticket if the issue persists.
