### ISSUE TITLE
Fort Eataine able to continue playing After being in jail

### ISSUE THREAD

**Issue by Estigia59** [WarEmu/WarBugs#14541]
Hi, today I found out while being in prison after being killed by a destro player, I couldn't go back to Altdorf with the Book but actually I was able to log off the game, be in Altdorf and enter the fort again and continue playing, my invitation was saved and I was not in prison anymore. 
Thanks a lot for the job You are doing! 
Sorry for the quality of the images, couldn' t save any screenshots. I tried again today to see if actually there was a bug and yes, again i could log out after being in jail and log in again and appeared in the fort.

Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**
![66256559_478988592846822_5966403915736940544_o](https://user-images.githubusercontent.com/29825413/60852256-3209ae00-a1f7-11e9-9686-2d2623653414.jpg)
![66290393_478988542846827_28723985361403904_o](https://user-images.githubusercontent.com/29825413/60852263-39c95280-a1f7-11e9-8db5-5e4e828cf1a3.jpg)

**Comment by Natherul** [comment]
logging off should teleport you to the capital and remove you from the fortress. This means someone else can take your place before you get back. As such this is not an issue

**Comment by Dekoupwar** [comment]
Happen to me few days ago, but wasn't the exact same thing. I crashed at the end of stage 1 and come back during stage 2
Was respawning all the time on the roof during stage 2 and stage 3 unstead of jail
