### ISSUE TITLE
KOBS/Chosen permanent auras !

### ISSUE THREAD

**Issue by Tyrean** [WarEmu/WarBugs#1454]
Evening all ,

I dont know if you are working on it but those 3 pemanent auras from Knight is really boring it wasn't same on live server you just have 1 auras permanent or 3 whit 5 sec timer if you swap all time whit twister for exemple ! This issue make some class so OP .

**Comment by milosxe** [comment]
This is not a bug. With Twister addon they would get the same effect.
If you want to discuss balancing issues with this mechanic, please use the forums.
For example http://www.returnofreckoning.com/forum/viewtopic.php?f=15&t=3510
