### ISSUE TITLE
missing invader Medallions in Fort scenario "The Maw"

### ISSUE THREAD

**Issue by fixfax86** [WarEmu/WarBugs#14547]
Hello, I only got 4 Invader Medallions in Fort Siege at "The Maw, I would like the remaining 2 medallions reimbursed, thanks! The siege ended at around 23.30 Copenhagen time..

**Comment by sioding** [comment]
Did your faction won? Characternames please.

**Comment by fixfax86** [comment]
Yes we won, cant remember the character names specificly... It happened a
second time, jut a few minutes ago, in "Fell Landing! I took Screenshot
this time..

Den tir. 9. jul. 2019 kl. 10.51 skrev Alexander Eckert <
notifications@github.com>:

**Comment by sioding** [comment]
Good - add them please

**Comment by fixfax86** [comment]
here is the screenshot

Den tir. 9. jul. 2019 kl. 19.09 skrev Alexander Eckert <
notifications@github.com>:

**Comment by Natherul** [comment]
Not sure why this is a ticket.

First off the bonus 2 medallions are not on the same row so you would see 2 different messages of invader medallions added. And the bonus is currently ONLY for attackers who wins as people were throwing zones to get to a defense where they would have an easier time to win.
