### ISSUE TITLE
[Tactic][Zealot]"Glimpse of Chaos"

### ISSUE THREAD

**Issue by Aluviya** [WarEmu/WarBugs#14554]
**Expected behavior and actual behavior:**
The ability "Glimpse of Chaos" is aquired at lvl 16, while the tactic that is connected to it is gained at lvl 15 -  Why should a Zealot get a Tactic which is completely of no use before having the connected ability to it?- Seems a bug to me.
![Luviya_005](https://user-images.githubusercontent.com/17249318/60994755-672a1380-a351-11e9-87fe-b5c0281c2565.jpg)

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 13.07.2019
