### ISSUE TITLE
Sell option is not working in vendors after destructing an item

### ISSUE THREAD

**Issue by bajituka** [WarEmu/WarBugs#14556]
1. Open a vendor and your inventory
2. Sell an item
3. Destroy an item (for example, the one that can't be sold) by drag'n'dropping it outside your inventory
4. Try to sell another item

Actual result: right click does nothing, so you have to reopen vendor's store
Expected result: item is sold right away

**Comment by teemyy** [comment]
You most likely targeted ground instead of the NPC vendor when destroying an item-> causing the sell function to not work. Re-targed the vendor and it should work as intended. Same stuff with mailboxes etc.

**Comment by sioding** [comment]
No answer since 24 days - close
