### ISSUE TITLE
Slayer’s Wild Swing

### ISSUE THREAD

**Issue by Ripliel** [WarEmu/WarBugs#14558]
The skill seems to have lower damage in tooltip when actual numbers are higher. 
During the test such numbers as 1030 and higher did happen, for example. 
But according to calculations based on tooltip, damage must vary from 586.25 to 775.25. 
https://cdn.discordapp.com/attachments/500338404978851840/598472300643221525/Gazbe_004.jpg

**Comment by Ripliel** [comment]
Also AP cost doesn’t match client: tooltip - 55, actual - 45.

**Comment by sioding** [comment]
fixed with patch from 13.07.2019
