### ISSUE TITLE
Black Dragon champion despawns

### ISSUE THREAD

**Issue by Skullgrin** [WarEmu/WarBugs#14555]
Went to Cinderfall last night to hunt some dragons, but when I finally found the flight path of the dragon and made my way up to fight it the black dragon champion would despawn every time I would attempt to attack it.

Screenshots of my map location and the mob in question can be found at https://imgur.com/a/hSNGBAQ

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 23.07.2019
