### ISSUE TITLE
Skull Thumper / Blurring Shock

### ISSUE THREAD

**Issue by 0berhofer** [WarEmu/WarBugs#14551]
There is an inconsistency with how Skull Thumper and Blurring Shock work.
Skull Thumper never crits:
https://i.imgur.com/paqrfAp.png
Blurring Shock can crit:
https://i.imgur.com/p6grHcp.png

**Comment by Lefze** [comment]
Just to make it clear in case someone misses it, on the Blurring Shock screenshot, the actual Blurring Shock proc is the thing called "Shock", which didn't crit. Only application damage did critical damage there.

**Comment by grunbag** [comment]
Fixed With next patch

**Comment by sioding** [comment]
fixed with patch from 13.07.2019
