### ISSUE TITLE
Gunbad - no quest kill reward

### ISSUE THREAD

**Issue by Getku** [WarEmu/WarBugs#14550]
I did kill "Dat Glomp's a Threat" third time. I didnt get any quest complete "announcement"

There were no lockouts for the boss for any of us, but there were many server lag issues.
Can i have my shoulders finally, as a DPS mara its hard to find group anyway... This happened about  9:00 PM server time. In my group was Chosen, WE, 2 x DoK and BG + me (marauder)

- Lonkero

**Comment by sioding** [comment]
Thanks for the report. I miss the screenshots - but for the shoulders i can give you a negative answer. We don't give anything out cause of a lag/bug or whatever. You can run the wing again - even when is hard to find a group. If you have any screens - please attach it. I leave it open - not sure if a dev can use it for something.

**Comment by Getku** [comment]
I dont think devs can use screenshot for killed boss and no quest kill announcement for anything....

Kinda frustrating since i have full sentinel in my bank but cant use it, im rr 68 and still have conq gear since 4 times shoulders and 2 times belt from vanq massive bag. 

You can close this WarBug if you cant do anything about it. I will play  this game again sometime.....
