### ISSUE TITLE
wrong Purple bag

### ISSUE THREAD

**Issue by Virukk** [WarEmu/WarBugs#14559]
Hello,
i won a purble bag from maw today but inside i found vanq medallions instead of Invader.
![purplebagwrong](https://user-images.githubusercontent.com/52797598/61073830-89d23000-a416-11e9-8640-5982bffff83e.jpg)

**Comment by Rockalypse** [comment]
As I understand bags from prefort zones are named wrong. That was bag from chaos wastes.

**Comment by Virukk** [comment]
it may have gone like this. In fact, after the victory in the fort, the roll was bugged and I couldn't see if I had won anything. After a while I realized that a purple bag had arrived in the mail and when i read MAW I thought it was from Fort.

Thank you

**Comment by sioding** [comment]
answer given - close
