### ISSUE TITLE
[WP SOULFIRE] not affected by Silence

### ISSUE THREAD

**Issue by Vancerus** [WarEmu/WarBugs#14563]
**Expected behavior and actual behavior:**
Soulfire is an offensiv 1sec DoT cast of a Warrior Priest, therefore should be affected by Silence, which it is ignoring.

**Steps to reproduce the problem:**
Get silenced by an enemy or a mob that silences (bats for example, see video)

**Testing Screenshots/Videos/Evidences (always needed):**
https://photos.app.goo.gl/i2m95oniEUJ1zsUX9

**Comment by grunbag** [comment]
Soulfire is affected by disarm not silence

**Comment by Vancerus** [comment]
aha. Any particular reason for that cast to be affected by disarm and not silence?

**Comment by grunbag** [comment]
It was the case on live , damage is disarmed and heal is silenced I think
