### ISSUE TITLE
[BG] Crimson Death Stackable

### ISSUE THREAD

**Issue by Vancerus** [WarEmu/WarBugs#14567]
**Expected behavior and actual behavior:**
Crimson Death making the enemy 10% more likely to be hit. Working like that, but able to stack it with 2 BGs to 20%

**Steps to reproduce the problem:**
Get 2 BGs to do Crimson Death.

**Testing Screenshots/Videos/Evidences (always needed):**
https://photos.app.goo.gl/ko3PymZE1Yzc3XbZ9

**Comment by sioding** [comment]
fixed with patch from 23.07.2019
