### ISSUE TITLE
No ability bolstering in rvr zone

### ISSUE THREAD

**Issue by fixfax86** [WarEmu/WarBugs#14562]
Hello. My Abilities are not getting bolstered in rvr zone at the moment.. they got bolstered yesterday.. fx my Character Frenduen's Aura's/commands is not Bolstered to Rank 40!
![Frenduen_000](https://user-images.githubusercontent.com/51016115/61108868-c7b96d80-a483-11e9-8407-88d1cdba4899.jpg)

**Comment by fixfax86** [comment]
![Frenduen_001](https://user-images.githubusercontent.com/51016115/61108884-d2740280-a483-11e9-87cb-0df7126449b1.jpg)
![Frenduen_002](https://user-images.githubusercontent.com/51016115/61108885-d2740280-a483-11e9-8420-1c22204027fa.jpg)

**Comment by fixfax86** [comment]
![Frenduen_003](https://user-images.githubusercontent.com/51016115/61109236-b886ef80-a484-11e9-8819-03b41906a290.jpg)
![Frenduen_004](https://user-images.githubusercontent.com/51016115/61109237-b886ef80-a484-11e9-92c1-11c54a62058f.jpg)
![Frenduen_005](https://user-images.githubusercontent.com/51016115/61109238-b886ef80-a484-11e9-8f74-09945bb987de.jpg)

**Comment by fixfax86** [comment]
I dont know about the Damage abilities, but the Commands, Perseverance a not getting bolstered!

**Comment by sioding** [comment]
Well - none of your screenshots shows me a running aura. please reanable the aura if you are in a arae which assign the bolster and check again.

**Comment by fixfax86** [comment]
wierd

Den lør. 13. jul. 2019 kl. 12.46 skrev Alexander Eckert <
notifications@github.com>:

**Comment by sioding** [comment]
no answer for 24 days. close
