### ISSUE TITLE
'crypts and tunnels' quest bugged (city dungeon)

### ISSUE THREAD

**Issue by rainlily-ssoul** [WarEmu/WarBugs#14560]
name: lilypop(runepriest)
******

I finished full city dungeon and killed all the boss there, can check it on my lockout window as in screenshot below. But when I checked the kill quest, it's not completed. 
I couldn't get kill credits for 3 boss which on my lockout (verrimus, tobias the fallen, necromancer malcidious). hope can be fixed as soon as possible.

![Lilypop_068-1](https://user-images.githubusercontent.com/52802431/61086781-bc0f7c00-a46e-11e9-8697-fe9549ef1daa.jpg)

**Comment by sioding** [comment]
more screenshots? were you dead on the missing encounters?

**Comment by rainlily-ssoul** [comment]
nobody died at the dungeon, ofc including me. I was not dead st any boss. and more screenshot needed...? please tell me what screenshot needed more. dungeons were already finished before days.

**Comment by rainlily-ssoul** [comment]
Lockout is gone but still bug not fixed, I just decided to abandon old bugged quest and get new one. Quest completed without bug on this run. I couldn't get the reward of last lockout sadly, btw at least became to know not always bugged on me 😒☺

**Comment by sioding** [comment]
Well - we need somehow more information on this for the next time - maybe .lockout screens and exact times the dungeon run was made for some logfile researches. i will close this now cause it worked fine after reassign the quest
