### ISSUE TITLE
Guild Group ORvR Quest

### ISSUE THREAD

**Issue by Zaebis032** [WarEmu/WarBugs#14569]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**
Expected behavior - Guild quest for ORvR "Unity Against Destruction" done by guild group of 6 taking Avelorn Keep and locking zone gives quest completion. 

Actual behavior - Guild quest for ORvR "Unity Against Destruction" done by guild group of 6 taking Avelorn Keep and locking zone did not give quest completion.

**Steps to reproduce the problem:**

Create a group of 6 guildies and zone lock  Avelorn to see if quest will complete.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Natherul** [comment]
I noticed now that the quest text is missing one vital component. The guild needs to be contributing to the warfront by either claiming a keep or just being part of the warfront in the other way the guild pays

**Comment by onemantankwall** [comment]
Wanted to add Scenario and Pve quests are also bugged. pve only seems to give credit for Bastion end bosses.

**Comment by Natherul** [comment]
> Wanted to add Scenario and Pve quests are also bugged. pve only seems to give credit for Bastion end bosses.

Not for this ticket, make a new one. However it should count for any bosses that adds lockouts

**Comment by sioding** [comment]
fixed with patch from 23.07.2019
