### ISSUE TITLE
[Ostland-NPC] Wrong spawn location for Odric Gebauer (11 Champion, Hostile to Order)

### ISSUE THREAD

**Issue by DyseMcLay** [WarEmu/WarBugs#14574]
**Expected behavior/Problem**
The NPC Odric Gebauer is spawning in inaccessible part of the zone, at approximately 14,500; 35,500, E SE of the Ferlangen Cemetary marker on the Ostland map.

I don't know where this NPC is supposed to spawn, or if it's even important for any quests/tome unlocks etc. but thought it was odd that is was spawning on a mountain ridge that players can't (or aren't supposed to) access. I only got up there by sort of cheesing a relatively sheer ledge, but I'm fairly certain this area isn't supposed to be accessed

**Steps to reproduce the problem:**
Go to the aforementioned location in Ostland and he should be right there. I've killed him several times and he respawns in the exact same spot.

**Testing Screenshots/Videos/Evidences (always needed):**
![Chofer_001](https://user-images.githubusercontent.com/52871378/61178219-19f6ad80-a5ae-11e9-9a47-f5da8cf68dc7.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 23.07.2019
