### ISSUE TITLE
[Guild Quests] - Mounts not working

### ISSUE THREAD

**Issue by Xuvap** [WarEmu/WarBugs#14572]
Hello,so I did the guild quests with my guild today,I decided to buy the "Ruby Daemon Red Exalted Steed" Mount and when I put it on my hotbar, I spam click on it and nothing happens.
![tester](https://user-images.githubusercontent.com/52868169/61176560-af983a00-a5ba-11e9-8296-9c175723668f.png)

**Comment by grunbag** [comment]
Wait for a server restart .
