### ISSUE TITLE
Weekly guildquest not completing on orvr locks

### ISSUE THREAD

**Issue by BomblingTV** [WarEmu/WarBugs#14575]
Yesterday in EU prime we had an almost full guild-only warband. And atleast 2/4 groups were guildies only. When Highpass, and later Praag locked and we got bag rolls. None of us who had picked up the weekly guild-quest for orvr locking completed.

Got a bastion stairs run in 4hours and can check if the pve version counts. But all of them should be working, ofc.

**Comment by sioding** [comment]
Duplicate of #14569
