### ISSUE TITLE
New mounted bug

### ISSUE THREAD

**Issue by Elflord123** [WarEmu/WarBugs#14570]
Incorrect designation of the actual speed
![Elflord_043](https://user-images.githubusercontent.com/48329663/61174107-7b198380-a5a4-11e9-964d-d729e54acb6e.jpg)
![Elflord_044](https://user-images.githubusercontent.com/48329663/61174108-7d7bdd80-a5a4-11e9-9320-bda74cd877ff.jpg)

**Comment by grunbag** [comment]
Tooltip will be fixed at next patch to 60%

**Comment by sioding** [comment]
fixed with patch from 23.07.2019
