### ISSUE TITLE
Disciple of Khaine assigned to jewelry items named "Waaagh Beads" with int main stat

### ISSUE THREAD

**Issue by Tyramissoux** [WarEmu/WarBugs#14577]
Waaagh beads items appear in all level ranges as jewelry and are either mainly int, willpower or a mix of both.

**_Expected:_**
 Classes assigned should be Zealot, Shaman, Sorcerer and Magus for jewelry with pure int as main stat

_**Actual atm:**_ 
Zealot, Shaman, Disciple of Khaine are assigned to int main jewelry

For the jewelry with willpower as main stat, the assigned class combo is correct. Only the ones with int as main stat are unfittingly assigned.

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/13544944/61183785-c3d54900-a645-11e9-9263-f6775750ef68.png)
![image](https://user-images.githubusercontent.com/13544944/61183795-d8194600-a645-11e9-84b2-2608f7428e47.png)
![image](https://user-images.githubusercontent.com/13544944/61183816-0c8d0200-a646-11e9-9756-9a04c3ccb9e1.png)
![image](https://user-images.githubusercontent.com/13544944/61183820-1ca4e180-a646-11e9-9c4a-9e33100f615c.png)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 23.07.2019
