### ISSUE TITLE
Chapter 9 Order Elf camp has farmable lvl 30 mobs

### ISSUE THREAD

**Issue by Halhammer** [WarEmu/WarBugs#1458]
The chapter 9 camp in Ellyrion (Reaversprings) has lvl 28-30 mobs that destro is farmin and scavenging at the moment, the destro camp on the other side only has regular 19-20 mobs...

**Comment by Reggaewaldo** [comment]
Can you please include the name on the mobs if possible ?
Thanks in advance.

**Comment by milosxe** [comment]
![boa_000_cr](https://cloud.githubusercontent.com/assets/13332067/9982033/98b41c36-5fce-11e5-9d82-1905e15fb9be.jpg)
![boa_001_cr](https://cloud.githubusercontent.com/assets/13332067/9982032/98b3b9d0-5fce-11e5-951e-4f01bcd5d83d.jpg)
![boa_002_cr](https://cloud.githubusercontent.com/assets/13332067/9982031/98b1e79a-5fce-11e5-9da7-88efa8c9b319.jpg)
![boa_003_cr](https://cloud.githubusercontent.com/assets/13332067/9982034/9912718c-5fce-11e5-8fd3-ee33fc27fb54.jpg)

**Comment by Reggaewaldo** [comment]
Thanks for taking the time to include the picture of all the names, now I know that this is about. This is however as is intended & as it was on live and thus we will not make any change.

Closing.
