### ISSUE TITLE
[WH] Shroud of Magnus (100% disrupt) protects from Sorc and Magus roots

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#14584]
<img src="https://monosnap.com/image/d26xqvrQ7DKDNkUYKvPvhFVnf2SkXI"/>

https://github.com/WarEmu/WarBugs/issues/13267

P.S.: on live Shroud of Magnus and Elixir of the Cauldron gave defence from roots (magus,sorc and bw)

**Comment by grunbag** [comment]
I see your WH rooted

**Comment by Nfkillz** [comment]
magus roots:
<img src="https://monosnap.com/image/IqG3CkvqVBym7rGvnVTNUr2KftkmmP"/>

**Comment by grunbag** [comment]
Ok thanks I’ll check it

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 23.07.2019
