### ISSUE TITLE
[Magus] Instability (knockdown) can be defended

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#14585]
<img src="https://monosnap.com/image/VMTgTL2HL1hvfbec2lbxwkmxPJrYpF"/>
<img src="https://monosnap.com/image/IqG3CkvqVBym7rGvnVTNUr2KftkmmP"/>

i dont know how it should work but the same ability of Engineer is undefendable (https://github.com/WarEmu/WarBugs/issues/13491)

**Comment by grunbag** [comment]
like other issue with shroud of magnus, this will be fixed with next patch

**Comment by grunbag** [comment]
after digging more into the client setting, it appears that both engineer and magus cc can be disrupted.

**Comment by Nfkillz** [comment]
nice! but why engineer cc can be disrupted? its strange. should be dodged or parried

**Comment by grunbag** [comment]
Sorry I explained it wrong , magus disrupt engineer dodge

**Comment by Nfkillz** [comment]
sounds logic now! thank you!
