### ISSUE TITLE
Character Missing Everything Bug

### ISSUE THREAD

**Issue by anickolas2002** [WarEmu/WarBugs#14587]
So, after a couple months of inactivity, I decide to hop on, and my level 40 chosen by the name of Fargahith is completely void of weapons, armor, items, currency, quest items,  skills, everything. And my tome of knowledge is also empty. I notice my character is still visible via the armory, with his armor displayed there. Is there a way to restore my characters possessions?

![Screenshot (1)](https://user-images.githubusercontent.com/52913452/61205871-03cc1880-a6a6-11e9-9b89-31c318e86f85.png)
![Fargahith_000](https://user-images.githubusercontent.com/52913452/61205895-0e86ad80-a6a6-11e9-94dd-10429be7d701.jpg)
![Fargahith_001](https://user-images.githubusercontent.com/52913452/61205898-10e90780-a6a6-11e9-8c92-74ac3608ef62.jpg)
![Fargahith_002](https://user-images.githubusercontent.com/52913452/61205907-134b6180-a6a6-11e9-9e69-5c1b12100bbb.jpg)

**Comment by Kaelang** [comment]
GM's don't restore lost items - however I don't believe that this was the result of a simple 'bug'.

I appreciate this report was listed back in July 2019 however if you have any further information to support this report, such as if your characters belongings have returned, I'll re-open this report.
