### ISSUE TITLE
DoK Invader 7 piece bonus 

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#14583]
Following skills from Dark Rites tree does not seem to proc 7 piece bonus:
Soul Shielding
Khaine's vigour
Fist of Khaine
Covenant of Tenacity

Tested all skills for around half an hour in IC - have not got procs from these, all that are not mentioned work fine.

**Comment by wargrimnir** [comment]
Correct, it only procs from heals. It's a heal crit proc. It works like this for all healers.

Khaine's Vigor is a group heal, which is excluded from procs.

**Comment by Rockalypse** [comment]
@wargrimnir Understood, can this ticket be reopened for correction of tooltip?
Thank you for explaining how it works, but current proc description states that all abilities from Path of Dark Rites can trigger proc, which is incorrect.
![tooltip](https://user-images.githubusercontent.com/42712833/61230830-89e27080-a733-11e9-9a7b-147c437e8db8.PNG)
