### ISSUE TITLE
No renown after Fort's completion and no medallions

### ISSUE THREAD

**Issue by pobratim** [WarEmu/WarBugs#14589]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**

Good day.There is no renown for completion on Forts during 2-3 days.I missed like 120-150 k renown cause of this.Everything was alright 2-3 days ago.I dont need an invader set.I already have it.Im there at Forts only for fun and renown.So its unpleasant for me.Please fix this bug or tell me what i have to do.

**Steps to reproduce the problem:**

Im always active at Forts and im tryin to do my best everytime.Going frags ,supports and etc.

**Testing Screenshots/Videos/Evidences (always needed):**

Forgot about to make some screenshots.Ill do it at next Fort.If this bug gonna be my guest again...

**Comment by Natherul** [comment]
This is consistent with not having enough contribution. I can say that kills do not currently count for contribution and I wont say the limit on whats needed to hit this. But suffice to say the barrier is very low.
