### ISSUE TITLE
[T4 Chaos PQ] Gates of Praag - Stage 1 (Normal) 

### ISSUE THREAD

**Issue by Rucent** [WarEmu/WarBugs#14599]
**Expected behavior and actual behavior:**
The first stage of this PQ requires you to kill a number of enemies and destroy 5 barricades. The barricades don't give credit when right clicked on to destroy them and cannot be attacked with skills/spells.

**Steps to reproduce the problem:**
Assuming a server restart doesn't solve the problem, right click on them or try to attack them.

**Testing Screenshots/Videos/Evidences (always needed):**
[https://youtu.be/xYbyUMrLTTk](url)

**Comment by sioding** [comment]
fixed with patch from 27.07.2019
