### ISSUE TITLE
New mounts - resetting decay via vendor

### ISSUE THREAD

**Issue by SunsetCNTK** [WarEmu/WarBugs#14597]
**Expected behavior and actual behavior:**
The new warhorses [Guild mounts] can be sold at vendors and bought back to reset the decay

**Steps to reproduce the problem:**
Just sell the mount and buy back to reset the decay to 7 days again

**Testing Screenshots/Videos/Evidences (always needed):**
I
![Aryanne_006](https://user-images.githubusercontent.com/16652212/61318084-879c1700-a804-11e9-9277-9ec9b4dc82d7.jpg)
II
![Aryanne_008](https://user-images.githubusercontent.com/16652212/61318082-879c1700-a804-11e9-8fac-5a285b1de286.jpg)
III
![Aryanne_009](https://user-images.githubusercontent.com/16652212/61318083-879c1700-a804-11e9-8dbe-17ec9d076bc8.jpg)

**Comment by Natherul** [comment]
this has been fixed, thanks for the report
