### ISSUE TITLE
auto-destruction

### ISSUE THREAD

**Issue by ricko2b** [WarEmu/WarBugs#14596]
Hi, 
had an issue during a RvR event. After dying during battle, released corpse, and almost auto-killed myself with buffs, without doing anything, was standing at respawn point next to healer NPC.
![Capture d’écran (1)](https://user-images.githubusercontent.com/52974178/61317109-9f729b80-a802-11e9-8e39-f426f148d51f.png)

**Comment by Kaelang** [comment]
Without more information as to how to replicate such issue, this report won't assist with identifying, and fixing the bug. Please re-open if this issue persists with more information.
