### ISSUE TITLE
No Renown or Tokens for Lossing Fort (as attacker)

### ISSUE THREAD

**Issue by Marxxxy** [WarEmu/WarBugs#14590]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**
No Fort renown and Tokens after loss attacking Fell Landing

**Steps to reproduce the problem:**
Nothing happens after timer resets. Rolls occur however.

**Testing Screenshots/Videos/Evidences (always needed):**
Nothing to show.

**Comment by Natherul** [comment]
This is consistent with not having enough contribution. I can say that kills do not currently count for contribution and I wont say the limit on whats needed to hit this. But suffice to say the barrier is very low.
