### ISSUE TITLE
Stop Hittin’ Da Runts + Loudmouth Interaction

### ISSUE THREAD

**Issue by Zoggof** [WarEmu/WarBugs#14598]
Stop Hittin’ Da Runts (SHDR) Tactic : You gain 40AP every time one of your war bellow triggers.

When you equip the tactic Loudmouth alongside SHDR however, the 40AP will only be gained if you have an enemy target selected. If you don’t have a target selected, SHDR will not restore any AP and effectively be a useless tactic.

What should be happening: AP should be restored on each war bellow proc regardless of having a target selected or not.

Evidence: Will upload video once home.

**Comment by sioding** [comment]
Wait for the video

**Comment by grunbag** [comment]
without loudmouth it restore ap even if you don't have a target selected?

**Comment by Zoggof** [comment]
Without loudmouth the tactic restores AP with or without a target as intended. It seems Loudmouth is the only thing that messes things up when used with SHDR.
Video below:
https://www.youtube.com/watch?v=Ou6O0LBh-rw

**Comment by Zoggof** [comment]
For some reason I can't seem to recreate the bug anymore and it seems to be working perfectly now. Perhaps there was something else causing it, maybe one of the other tactics. Closing for now.
