### ISSUE TITLE
[Highelf Chapter 6] Thirst for Knowledge - Laurilions Lament

### ISSUE THREAD

**Issue by Lindiranae** [WarEmu/WarBugs#14592]
You had to touch Laurilion´s Lament, and kill the spawning Zuraen Blackgull.

I´ve done this quest with two chars, and always had to touch Laurilion´s Lament three times, 
because Zuraen Blackgull spawns at 1st and 2nd always partly inside the stone and cannot be attacked. 

So I had to stand and wait until the Lament has its reset and had to kill all enemys in respawn around me. 

Maybe it is possible to prevent him from spawning inside the stone? 

![Belthania_001](https://user-images.githubusercontent.com/52664952/61229190-07a07f00-a728-11e9-812e-e0cd0ae80016.jpg)

**Comment by Kaelang** [comment]
This should now be fixed. Please re-open if issue persists.
