### ISSUE TITLE
[Reikland-NPC] Wrong spawn location for Lorvan The Sacrificer (31 Champion, hostile to Order)

### ISSUE THREAD

**Issue by DyseMcLay** [WarEmu/WarBugs#14594]
**Expected behavior and actual behavior:**
Found Lorvan the Sacrificer in an inaccessible area (just like my recent post) in Reikland, at approx. loc 1,600; 40600. Looks like he might belong in the underground PQ below, just a guess though.

**Steps to reproduce the problem:**
Go to above loc and he's right there. I killed him a few times and he kept respawning exact same spot.

**Testing Screenshots/Videos/Evidences (always needed):**

![Chofer_002](https://user-images.githubusercontent.com/52871378/61267821-0dfe1d80-a75f-11e9-8616-49794384eb27.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 23.07.2019
