### ISSUE TITLE
Bastion Stair Lockout

### ISSUE THREAD

**Issue by Zoggof** [WarEmu/WarBugs#14602]
After completing a full run of the middle wing of Bastion Stair (including killing the Skull Lord), I am locked out of the other wings mini bosses (both left and right)  despite not running them.

**Comment by sioding** [comment]
Anny errormessages when you try to use the portal?

**Comment by Zoggof** [comment]
![yikes dude](https://user-images.githubusercontent.com/23256143/61518252-73e2f180-aa4c-11e9-8414-521b5a181a23.png)

Yellow are the bosses which I didn't do.
Red is the wing which we completed. 
I can still enter the portals to left and right wing with no error message.

**Comment by grunbag** [comment]
Someone in your party shared the lockout

**Comment by Zoggof** [comment]
I wasn't aware you could share lockouts. Is that intended?

**Comment by Issard** [comment]
is this really intended ? it could be abused to speed up influence runs by a *lot*

**Comment by sioding** [comment]
Hm? how?

**Comment by Issard** [comment]
i joined a pug party , we killed Urf afterwards the party disbanded. logged in one day later (created a new party) and i suddenly also had lockout on all demibosses , hence only needing to kill the main bosses , resulting in sub 1h run

**Comment by sioding** [comment]
And the problem is? Since you only get influence from the last boss - and you still need to kill him for that and get your lockout afterwards i don't get the problem - yes you don't have to kill the bosses before but /shrug

**Comment by raptrr** [comment]
Sounds like, as @grunbag already stated, a lockout-share to me. Unless there is anything else, I'll put this on 2 Weeks Ultimatum.
