### ISSUE TITLE
[ToK] Redeye-Set not showing in Armory

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#14604]
![Drengur_052](https://user-images.githubusercontent.com/40274248/61550242-3c774380-aa52-11e9-8e37-a898c5d8deab.jpg)
Equipped the redeye-shoes and helm, but both do not show up in the ToK-armory

**Comment by Rockalypse** [comment]
Have to add that it is true for all sets.
You need to have set pieces in inventory for them to show in ToK

**Comment by Lheana** [comment]
This should have been fixed several patches ago.
