### ISSUE TITLE
Marauder Sent weapon Chimera's bane Proc

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#14609]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**

i have been trying to see the proc on this weapon so i did alot of testing on the dummy and never saw one proc then i tried my subjugator weapon Concussion X was working fine 

both weapon proc have the same chance 5% but Chimera's bane Proc never worked

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by grunbag** [comment]
it proc i just tested it. You can't make it proc on dummies cause it proc when you hare hit. and dummies don't attack
