### ISSUE TITLE
High Elf Chapter 8 quests bugged

### ISSUE THREAD

**Issue by CptVinicius** [WarEmu/WarBugs#14603]
The boss Tuffcrusha (Quest: Challenge a Champion) is nowhere to be found in his marked area. Noone could tell me anything helpful about him and his quest.
The Cold One Slime (Quest: The price of Survival) can not be found in the DE camp. Also no advice available.

I did not know where else to put that, but I vaguely remember those 2 being there when I dropped the game over a year ago.

**Comment by Lheana** [comment]
First: One issue per report.
Quest line Challenge a Champion has already been fixed/reworked on dev server, will be on live with next patch.
About the quest The Price of Survival, maybe your quest marker is not activated, but it's easy to find, nothing really special. Just find Cold One Slime.

**Comment by sioding** [comment]
fixed with patch from 23.07.2019
