### ISSUE TITLE
[Item] 7/7 Invader-Proc, Ironbreaker

### ISSUE THREAD

**Issue by Irvid** [WarEmu/WarBugs#14605]
### Expected behaviour:
**(7 Piece Bonus) - Intimidation - When you block, all members of your group within 100ft except you will become 5% less likely to be Critically hit for 10 seconds.**
### Actual behaviour:
**The proc is entirely dysfunct.**

### Reproduction:
**Self-explanatory.**

### Evidence:
![bugreport](https://user-images.githubusercontent.com/53101727/61571282-7d8f4800-aa92-11e9-824f-6c75cc35862c.png)

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 27.07.2019

**Comment by Irvid** [comment]
As of 01.08.2019, the proc (still) doesn't work. I've jumped through the hoops of testing it in every environment again, there is no trace of the proc. None of the people I played with saw it on their buffline (likey they would see the SM 7/7 invader proc) or noticed a change without of the relevant stat through .getstats either (so it's not just a lack of buffline icon, sadly).

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 17.08.2019
