### ISSUE TITLE
[Fort] rewarded 8 medals

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#14617]
reikwald server time 6~7PM +-
destro win and i got 8 medals as DoK.
![fort_8medals](https://user-images.githubusercontent.com/19988772/61651603-2935d380-acf1-11e9-806f-426a0a96b96e.jpg)
i remember number of invader medals and it was actual 8 medals.

**Comment by Natherul** [comment]
This has not happened since and should not be an issue. If it happens again please report back and we will reopen the ticket.
