### ISSUE TITLE
T3 Epic Quest: Ancient Horror not working at step 14. 

### ISSUE THREAD

**Issue by Lethandrius** [WarEmu/WarBugs#14615]
**Expected behavior and actual behavior:**

EDIT: Quest is working properly, I just got confused because the Wiki is not updated with the new steps that you need to do to complete the quest.

The quest is working properly. Sorry for any inconvenience. 
_______________________________________________________________________________________________________________

As the Wiki says: 

"STEP 14
Kill the NPC Unholy Power (Champion lvl 27) and click on the big Stone Plinth behind him. at 58k/14.6k. 

Return to Elgrum Stoutgirth when complete. "

**Steps to reproduce the problem:**

At the step 14, you cannot click on the big Stone Plinth behind Unholy Power. The cursor doesn't change to the "hand" when you need to activate/click something.

1. Killing Unholy Power first then click the stone: Doesn't work.
2. Clicking the stone first then killing Unholy Power: Doesn't work.
3. Remove all pets/turrets and kill it without AoE, only single target: Doesn't work.
4. Kill with turrets/pets and/or using AoE: Doesn't work.
5. Relog use /relo use /reload or closing the client completely/relaunch: Doesn't work.
![3](https://user-images.githubusercontent.com/37417558/61602838-cfee7700-ac00-11e9-95d8-d31f7eb03fbe.png)

The quest at step 14 cannot be completed thanks to this bug. 

**Testing Screenshots/Videos/Evidences (always needed):**

![1](https://user-images.githubusercontent.com/37417558/61602679-26a78100-ac00-11e9-9008-f350cc40795c.png)
![2](https://user-images.githubusercontent.com/37417558/61602681-26a78100-ac00-11e9-824f-d60ad324139a.png)

**Comment by Lheana** [comment]
So I close it.
