### ISSUE TITLE
[Quest] Thrill of Power

### ISSUE THREAD

**Issue by Skullgrin** [WarEmu/WarBugs#14618]
In the quest Thrill of Power you are given a Ley Stone that you are to use at 4 compass points and then kill a mob. The mob is kill-able, however the Ley Stone cannot be used at any of the 4 rubrics in the quest area. Images regarding where the quest and map area it is located in can be found here https://imgur.com/a/35iCa02 .

**Comment by Lheana** [comment]
You must use the item targeting the Rubrics and standing close it.

**Comment by Skullgrin** [comment]
Revisited this quest and stood directly on top of the rubrics with them targeted while right and left clicking the ley stone. 3 of the 4 rubrics were activated (twice) however they did not show as completed via the quest tracker and the western rubric would not activate at all. Screenshot here https://imgur.com/a/eqX6MnF .

**Comment by Lheana** [comment]
In fact the "target" is not the rubric, but the big stone. So use it standing close to the big stone and it will work.

**Comment by Skullgrin** [comment]
Ok, got this to work, still it is odd the way the targeting works on it. =P
