### ISSUE TITLE
Norsca PQ - Altar of the Bloodbane - Doesn't work

### ISSUE THREAD

**Issue by KoffeFPS** [WarEmu/WarBugs#14611]
Norsca PQ - Altar of the Bloodbane - Doesn't work

Tried x3 times, doesn't go past phase 1 

21/07/2019

ty

**Comment by Lheana** [comment]
Works fine for me 
![Lheanaa_003](https://user-images.githubusercontent.com/11537611/61591676-c4338e00-abc9-11e9-8105-671be638dd1b.jpg)

**Comment by sioding** [comment]
No answer for 16 days - close
