### ISSUE TITLE
[Ability] Binding Grudge; bugged damage application.

### ISSUE THREAD

**Issue by Irvid** [WarEmu/WarBugs#14614]
This just happened in a Howling Gorge scenario:
![Weirdness](https://user-images.githubusercontent.com/53101727/61594675-d7a52000-abee-11e9-8a56-4580e1d25580.png)
**Updated screenshot to include deathblow.

It resulted in the oneshot of the player, needless to say I have absolutely no idea what happened there.

**Comment by grunbag** [comment]
Negative value bug . Fixed already
