### ISSUE TITLE
Shaman - Fury of da green - healing value/tooltip mismatch.

### ISSUE THREAD

**Issue by Iamwithstupid** [WarEmu/WarBugs#14612]
Fury of da green spell has a tooltip of healing for 50% of damage dealt plus a fixed healing value.
However FODG will never heal for values specified in ability tooltip.
Example:
 tooltip: 50% damage + 1536 health
 damages for 324 and heals for 1399 health (expected 1698 or more due to healing power is not in a tooltip calculation) 
 healing will also not increase when damaging multiple targets.

[Screensava_019](https://user-images.githubusercontent.com/36380568/61588854-c2a69d80-abaa-11e9-8ba9-2fae67041cae.jpg)

**Comment by grunbag** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 23.07.2019
