### ISSUE TITLE
Sent Message with Gold From Alt to Main, never received

### ISSUE THREAD

**Issue by p12om3th3us** [WarEmu/WarBugs#14610]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**
Sent Message with Gold From Alt to Main, never received. Sent about 21G 20JUN19 @ approx 0800PM. 

**Steps to reproduce the problem:**
Used mailer to send to character "Zharroth" Log into character and did not receive anything. Had to send another 

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/40395026/61586169-b33c3b80-ab3b-11e9-8bc4-fb4694c4350e.png)

**Comment by sioding** [comment]
send another item ... 99% of the mails will be delivered with it
