### ISSUE TITLE
Broken Spirits Stage II - Uproot Shadowthorn 0/25

### ISSUE THREAD

**Issue by glxracer** [WarEmu/WarBugs#14613]
Broken Spirits Public quest in Shadowlands

**Expected behavior: Right click Shadowthorn roots to up root
actual behavior:: Right click shadowroot, root resets, but does not add to the quest

**Steps to reproduce the problem:** Happens everytime I have tried this PQ

**Testing Screenshots/Videos/Evidences (always needed):**
before: 
![Celebrinbor_000](https://user-images.githubusercontent.com/52716245/61591332-c7138c00-ab93-11e9-9efd-5ad12acf01dd.jpg)

after: 
![Celebrinbor_001](https://user-images.githubusercontent.com/52716245/61591335-d266b780-ab93-11e9-87f6-46fbcafc3ad1.jpg)

**Comment by sioding** [comment]
fixed with patch from 23.07.2019
