### ISSUE TITLE
Bloodlord AM 7 pieces

### ISSUE THREAD

**Issue by Koinzzell** [WarEmu/WarBugs#14628]
**Expected behavior and actual behavior:**
The 7 bloodlord pieces bonus for AM: On hit you have 10% to deal 150 damages to a secondary target within 30 feet of your target.
The problem it does not proc.

**Steps to reproduce the problem:**
Equip the full set bloodlord (7/7) and hit the target dummy with direct damages.

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/51057710/61664100-5e7ef900-acd2-11e9-82e9-b095def687ce.png)

**Comment by grunbag** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 27.07.2019
