### ISSUE TITLE
[Crypts & Tunnels] Divine Mend massive heal amount

### ISSUE THREAD

**Issue by Sciberr** [WarEmu/WarBugs#14629]
An introduction:
<what the bug is and the effects it has or hasn't (if any)>
 - Divine Mend on WP healing over 7k HP

Details:
<Detailed information regarding the bug and what the result is. This will include what the ACTUAL outcome should be (if it was working correctly).>
- Nearing the end of this boss I noticed that my healing was OBSURD and it turns out it was! 

Evidence:
<Generally I always include visual evidence of the bug. A screenshot or video as visual aid.>
 - I noticed this crazy healing so I made a video of it. At 1:20 in the video you see I get a 7k+ heal. https://youtu.be/j_bUK3vs5PU

Additional Information:
<Anything I would feel would benefit the dev member reading my bug report>
 - Maybe this isn't a but... maybe its just "working as intended"

How to reproduce the bug:
<If the bug is something that requires an input from the user or a few steps to recreate it. I would write how to recreate the bug.>*
- Sorry I do not know how it happened or why it was happening.

**Comment by grunbag** [comment]
Probably due to the bug of negative value , it has been fixed
