### ISSUE TITLE
[Quest] Orcy Vandalism

### ISSUE THREAD

**Issue by Skullgrin** [WarEmu/WarBugs#14627]
There a several problems with this quest, one of the two powder kegs isn't attack-able, the Bugman's barrels have been changed to water barrels and are not attack-able, and the cannons are also not attack-able. Image evidence can be found here https://imgur.com/a/4477cgR .

**Comment by Skullgrin** [comment]
Updated images, somehow the others didn't upload https://imgur.com/a/32mON6G

**Comment by Lheana** [comment]
Tip: You can directly update the images on the report. To do so, click on the text below to attach files.

**Comment by cooler-SAI** [comment]
Confirm the bug! can't finish quest.! Cannons can't be brake!

![Vikkz_002](https://user-images.githubusercontent.com/812439/63540336-958c3880-c524-11e9-98b9-a1e31cad0863.jpg)

**Comment by cooler-SAI** [comment]
![Vikkz_003](https://user-images.githubusercontent.com/812439/63540431-bbb1d880-c524-11e9-9cf8-2b461d7e44b7.jpg)

**Comment by Lindiranae** [comment]
I have the same problem with this quest. 
It is given to me in Greenskin Chapter 10, but the Cannons for it are shown at Chapter 11 near the BlackFirePass Warcamp.
I walked to them, destroyed them, but they didnt count for the Quest. 

![Hellschkriem Orcy Vandalism 01](https://user-images.githubusercontent.com/52664952/69482843-93d25980-0e20-11ea-835f-26a8ac4af91c.jpg)
![Hellschkriem Orcy Vandalism 02](https://user-images.githubusercontent.com/52664952/69482844-93d25980-0e20-11ea-9004-241c3a7f820f.jpg)
