### ISSUE TITLE
No tokens with fortress

### ISSUE THREAD

**Issue by Lestrigon78** [WarEmu/WarBugs#14634]
After the end of the defense of the fort (loss), my character once again did not receive an award (4 tokens).
I would like to receive a refund in the amount of 4 tokens for participating in the defense of the fortress.
https://pastenow.ru/66SM1 - to lock
https://pastenow.ru/66SM7 - after lock
p.s. Fortress Shining Way

**Comment by sioding** [comment]
We do not give out any refunds. I will leave this open - maybe @Natherul can introduce something to let the players know they don't get any medal if their contributions is too low.

**Comment by Natherul** [comment]
can do. Will add message to players if this is the case
