### ISSUE TITLE
Name Register Window

### ISSUE THREAD

**Issue by Ciiliea** [WarEmu/WarBugs#14636]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**

When you apply a last name to your character the window is called "Name Registrar" (At least for order)

**Steps to reproduce the problem:**

Go to the ABC npc

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by sioding** [comment]
Don't get it ... and the bug is what?

**Comment by sioding** [comment]
No answer for 14 days - close
