### ISSUE TITLE
Karrig the Despoiler Beastlord Quest

### ISSUE THREAD

**Issue by Chijinjanai** [WarEmu/WarBugs#14635]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**

Expected: Karrig the Despoiler from Chaos chapter 17 should hand out one of the Beastlord quests.
Actual: He does not give out the quest and after some time disappears entirely.

**Steps to reproduce the problem:**
Relogged several times. Same issue occurs.

**Testing Screenshots/Videos/Evidences (always needed):**

![Lishalia_019](https://user-images.githubusercontent.com/53235673/61740796-5eb7dc80-ad44-11e9-9938-c6dee1f0bb28.jpg)
![Lishalia_021](https://user-images.githubusercontent.com/53235673/61740991-c8d08180-ad44-11e9-9509-0e1270daed2d.jpg)

**Comment by Lheana** [comment]
Hm it's fine for me.
![Anaehll_429](https://user-images.githubusercontent.com/11537611/61789844-0224f200-ae16-11e9-8fa1-fe0001c9a4ec.jpg)

**Comment by Chijinjanai** [comment]
Checked it out today, looks like he is back and working for me too. Thanks for taking the time and checking it out.

**Comment by Lheana** [comment]
So I close it.
