### ISSUE TITLE
HIGH ELF CH6 easy PQ

### ISSUE THREAD

**Issue by iwka53** [WarEmu/WarBugs#14631]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by iwka53** [comment]
stage 2 bugged..thornes cant be collected :(

**Comment by Lheana** [comment]
You talk about PQ 'Broken Spirits'. So duplicate of #14613. This has been fixed with the patch of yesterday.
