### ISSUE TITLE
[Quest] The Sewers of Altdorf - Dwarf Character

### ISSUE THREAD

**Issue by Lindiranae** [WarEmu/WarBugs#14630]
I should travel to Altdorf to speak to "Bawon Sanmdi". 
The Text says, I should talk to "Rhanz Folner".

In the whole Warcamp-Area there is no Bawon Sanmdi, and to Rhanz Folner 
I cannot talk, no option for it.
![Grimmhilda_000](https://user-images.githubusercontent.com/52664952/61695917-a33b7c00-ad34-11e9-87dd-d44a5a1da337.jpg)

**Comment by Lheana** [comment]
Have you tried abandoning and retaking the quest?

**Comment by sioding** [comment]
No answer for 14 days - close
