### ISSUE TITLE
[Item][Potion] Potent Lasting Reinforcing Unguent gives too much armor

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14639]
The Potent Lasting Reinforcing Unguent (lvl 32) gives 880 armor, the lvl 35 and 38 equivalent however only give 742 and 825 respectively. I don't have a lvl 30 one to compare.

![Moragor_004](https://user-images.githubusercontent.com/30193675/61827497-f9a7d800-ae64-11e9-9932-5832cbe6746f.jpg)
![Moragor_002](https://user-images.githubusercontent.com/30193675/61827507-fe6c8c00-ae64-11e9-8387-820958dad6a3.jpg)
![Moragor_003](https://user-images.githubusercontent.com/30193675/61827509-fe6c8c00-ae64-11e9-8771-752bf399b089.jpg)

**Comment by grunbag** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 27.07.2019
