### ISSUE TITLE
My character has dissapeared.Been playin few hours ago and it was alright.

### ISSUE THREAD

**Issue by pobratim** [WarEmu/WarBugs#14632]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**

Just logged to play on my 29 lvl wp character.But there is no wp at my characters list.Name-Siberianman.I had 3 characters now i see only 2 of them.How it can be?

**Steps to reproduce the problem:**
Its very unpleasant.Cause my wp already have actual armor with best armor tals and 100 g mount has already bought...Is it possible to restore this character somehow?
![screenshot_000](https://user-images.githubusercontent.com/42023389/61714152-ce3cc480-ad62-11e9-9790-667272ffb670.jpg)You can see there is only tank and wh.And no wp as it never existed.

**Testing Screenshots/Videos/Evidences (always needed):**
I dont know what screenshots i must send here...

**Comment by pobratim** [comment]
![Orthodoxia_002](https://user-images.githubusercontent.com/42023389/61714516-b6b20b80-ad63-11e9-97b5-513983d08b25.jpg)
You can see in guilds chat that i logged today on this character-Siberianman.Gained 37 rr this morning.

**Comment by sioding** [comment]
This is nothing for the bugtracker. Create an ingame ticket. The WP name you have given isn't in the armory - so it seems like you deleted it on your own. However - this bugtracker is for bugs not for support questions. Please open an appeal ingame.
