### ISSUE TITLE
Mastery points

### ISSUE THREAD

**Issue by fixfax86** [WarEmu/WarBugs#14644]
Hello, im in doubt about the number of mastery point you get, I have submitted some screenshots showing that I have 28 Mastery points.. I have been sure while I played this game that I have 27 mastery points available at rank 40.. because I checked the ROR career builder, it shows 26 Mastery points but in game 27 points. So I remember to build the masteries on that Mastery calculator, with one 1 mastery point missing.
![Unur_000](https://user-images.githubusercontent.com/51016115/61892702-a9845080-af0c-11e9-95bf-1e5a91256272.jpg)
![Unur_001](https://user-images.githubusercontent.com/51016115/61892703-a9845080-af0c-11e9-87ad-0cd404066797.jpg)
![Unur_002](https://user-images.githubusercontent.com/51016115/61892704-aa1ce700-af0c-11e9-9196-eb2bfa7d3fad.jpg)

**Comment by fixfax86** [comment]
![Frendir_001](https://user-images.githubusercontent.com/51016115/61893424-53181180-af0e-11e9-9dd2-bf02f38de12f.jpg)
![Frendir_002](https://user-images.githubusercontent.com/51016115/61893425-53181180-af0e-11e9-850e-70243451dd92.jpg)
![Frendir_003](https://user-images.githubusercontent.com/51016115/61893426-53b0a800-af0e-11e9-9c99-68942f3c6236.jpg)

**Comment by fixfax86** [comment]
However I only got 26 on this character..
![Fhaine_000](https://user-images.githubusercontent.com/51016115/61893796-34fee100-af0f-11e9-8e75-8811ca080e23.jpg)
![Fhaine_001](https://user-images.githubusercontent.com/51016115/61893797-34fee100-af0f-11e9-801c-c66b6459452c.jpg)
![Fhaine_002](https://user-images.githubusercontent.com/51016115/61893798-35977780-af0f-11e9-9338-d4e10358e128.jpg)

**Comment by sioding** [comment]
Please check if your set items grants a masterypoint.

**Comment by fixfax86** [comment]
There is no additional mastery points from set items..

**Comment by grunbag** [comment]
What I your set ? Ruins ?

**Comment by fixfax86** [comment]
its a mix of set items, with no extra mastery points on neither of the characters presented..

**Comment by Skullgrin** [comment]
Are the characters you are comparing all the same Level and Renown Rank? You get Mastery points at the following Levels/Renown Ranks...

1 point  at Levels 11, 13, 15, 17, and 19
1 point at Levels 21 thru 40
1 point at RR40, RR50, RR60 and RR70

...for a grand total of 29. If you are comparing characters of different Levels and Renown Ranks then you will have a different number of mastery points on each of them.

**Comment by fixfax86** [comment]
okay that explains it, thanks..
