### ISSUE TITLE
[Forts] The Maw

### ISSUE THREAD

**Issue by Sciberr** [WarEmu/WarBugs#14640]
An introduction:
<what the bug is and the effects it has or hasn't (if any)>

- The Maw is locked even though we locked Chaos Waste.

Details:
<Detailed information regarding the bug and what the result is. This will include what the ACTUAL outcome should be (if it was working correctly).>

- Fort isn't opening even though we locked the zone. This happened on the fort we opened before Reikwald. 

Evidence:
<Generally I always include visual evidence of the bug. A screenshot or video as visual aid.>

- Made a short video showing The Maw locked even though Chaos Wastes is locked. https://youtu.be/mfc7bzhAVhM

Additional Information:
<Anything I would feel would benefit the dev member reading my bug report>

- N/A

How to reproduce the bug:
<If the bug is something that requires an input from the user or a few steps to recreate it. I would write how to recreate the bug.>*

- I don't know how to replicate it or why it is happening now.

**Comment by Natherul** [comment]
collecting both to same
https://github.com/WarEmu/WarBugs/issues/14641
