### ISSUE TITLE
[Forts] Fell Landing no portal

### ISSUE THREAD

**Issue by Sciberr** [WarEmu/WarBugs#14641]
An introduction:
<what the bug is and the effects it has or hasn't (if any)>

- The next zone right after Chaos Waste bugged yet again the fort is broken.

Details:
<Detailed information regarding the bug and what the result is. This will include what the ACTUAL outcome should be (if it was working correctly).>

- This time the portal is missing to enter.

Evidence:
<Generally I always include visual evidence of the bug. A screenshot or video as visual aid.>

- Made a video on missing portal. https://youtu.be/Gc3AAv98HbY

Additional Information:
<Anything I would feel would benefit the dev member reading my bug report>

- #Feelsbadman

How to reproduce the bug:
<If the bug is something that requires an input from the user or a few steps to recreate it. I would write how to recreate the bug.>*

- N/A

**Comment by Natherul** [comment]
this was probably down to a previous issue with lords and the campaign saving. Closing this ticket for now and will reopen if it happens once more.
