### ISSUE TITLE
Ugrog's Rage's various bugs

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14648]
Expected behavior and actual behavior:
On Stage II of the Public Quest Ugrog's Rage, some barrels are stuck underground, also they do not disappear when you pick them up nor give any kind of feedback, which feels weird. The enemies that show up are not targetable nor lootable after death, and are also stuck underground before they start attacking. I could only defeat them because of my squig pet.

Steps to reproduce the problem:
Just play through the Public Quest's stage II and you'll meet the issues.

Testing Screenshots/Videos/Evidences (always needed):
![Gerksie_004](https://user-images.githubusercontent.com/53320075/61919482-2c68d380-af2c-11e9-80a6-15bc4e233dcd.jpg)
![Gerksie_005](https://user-images.githubusercontent.com/53320075/61919483-2d016a00-af2c-11e9-812b-a6b2f26caa65.jpg)

**Comment by Lheana** [comment]
Next time, one issue per report please.
Different issues will be fixed with next patch.

**Comment by Austherus** [comment]
Understood.

**Comment by sioding** [comment]
fixed with patch from 27.07.2019
