### ISSUE TITLE
Sc T1 slayer's 2H weapon wron price

### ISSUE THREAD

**Issue by Kushido** [WarEmu/WarBugs#1464]
It cost 10 medals instead of 20 (tried to buy it with only 10 medal in my bag and it works)
![kushidos_000](https://cloud.githubusercontent.com/assets/14280617/9991226/de0af42e-6070-11e5-9817-162b994f5fd1.jpg)

**Comment by milosxe** [comment]
Pls don't open this issue again. It has already been reported. Closing once again.
https://github.com/WarEmu/WarBugs/issues/1080
