### ISSUE TITLE
Chaos and Empire NPCs just staring at each other in Norsca

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14658]
Expected behavior and actual behavior:
These two guys are just sitting there without fighting, I'm pretty sure they should be.

Steps to reproduce the problem:
Just find them.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_013](https://user-images.githubusercontent.com/53320075/61991363-5b16a500-b025-11e9-81df-d033875775c4.jpg)
![Austherus_014](https://user-images.githubusercontent.com/53320075/61991364-5b16a500-b025-11e9-8d5e-863f1bb5b757.jpg)

**Comment by sioding** [comment]
The spearmen are part of a quest - and the war breaker is a guard. Its kinda weird yes - maybe the spearman can be moved - but right now its not a bug. I leave this open for the DB department to decide.

**Comment by Austherus** [comment]
Understood. I just had this weird impression, never saw this kind of behaviour on the live game back in the day.

**Comment by Lheana** [comment]
Not issue, if these NPCs were fighting each other, Spearmen would be permanently one shooted by the 55 champions.
