### ISSUE TITLE
NPC in Norsca missing part of his head/hair/helmet

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14657]
Expected behavior and actual behavior:
This NPC named "War Merchant" is naked (not sure if he's supposed to be) and missing part of his head/hair/helmet. He is sitting next to the bridge to where you burn the houses.

Steps to reproduce the problem:
Just find him, he'll be there with his unfinished brain surgery.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_010](https://user-images.githubusercontent.com/53320075/61991338-ef343c80-b024-11e9-87be-f5f27352e964.jpg)
![Austherus_011](https://user-images.githubusercontent.com/53320075/61991339-ef343c80-b024-11e9-91f5-5b372160f5d7.jpg)
![Austherus_012](https://user-images.githubusercontent.com/53320075/61991340-efccd300-b024-11e9-8456-ebdaea0e1e7b.jpg)

**Comment by Lheana** [comment]
It's specific to the model of the item he wears sometimes.

**Comment by Zomega-WAR** [comment]
Need to retexture the top part to look like a brain

**Comment by Kaelang** [comment]
Fix was added on February 23rd patch. Please re-open if issue remains.
