### ISSUE TITLE
"Down in Da Slop" quest

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14651]
Expected behavior and actual behavior:
The squigs are supposed to be corpses, but they are alive and well.

Steps to reproduce the problem:
Just get to the area and you'll see the living bastards.

Testing Screenshots/Videos/Evidences (always needed):
![Gerksie_014](https://user-images.githubusercontent.com/53320075/61923157-583e8600-af39-11e9-8632-588b36c048d8.jpg)
![Gerksie_015](https://user-images.githubusercontent.com/53320075/61923158-583e8600-af39-11e9-85a6-5f54c5224e37.jpg)

**Comment by sioding** [comment]
fixed with patch from 27.07.2019
