### ISSUE TITLE
NPC behaviour at the dwarven walls in Mount Bloodhorn's greenskin side

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14650]
Expected behavior and actual behavior:
These guys just sit there in front of each other and do nothing. The orc does attack one of the characters in front of him, nothing else. This also happens on other areas where they are supposed to be fighting each other. Should I report each area individually?

Steps to reproduce the problem:
Just go there and watch them.

Testing Screenshots/Videos/Evidences (always needed):
![Gerksie_007](https://user-images.githubusercontent.com/53320075/61921959-46f37a80-af35-11e9-9688-160ae2766428.jpg)
![Gerksie_008](https://user-images.githubusercontent.com/53320075/61921960-46f37a80-af35-11e9-8745-6da15303af7e.jpg)
![Gerksie_009](https://user-images.githubusercontent.com/53320075/61921961-46f37a80-af35-11e9-92e5-3520e3ac8dd3.jpg)

**Comment by Lheana** [comment]
You report that other dwarves don't attack the orc?

**Comment by Austherus** [comment]
Yes, neither side is attacking each other, they just stand there.

**Comment by Lheana** [comment]
They just fight each other when they are close to each other, and nothing breaks the LoS.
