### ISSUE TITLE
Pitiless Strike's icon (Black Guard's skill)

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14653]
Expected behavior and actual behavior:
The icon for Pitiless Strike disappears when it's not ready to be used. Once you have enough build up and can use it, it's icon reappears.

Steps to reproduce the problem:
I have the impression it was always visible at first, but after using it a few times and them switching it's position with another skill, the problem started happening.

Testing Screenshots/Videos/Evidences (always needed):
Visible
![Austherus_003](https://user-images.githubusercontent.com/53320075/61991083-b6469880-b021-11e9-9650-86d918b1c506.jpg)
Invisible
![Austherus_004](https://user-images.githubusercontent.com/53320075/61991084-b6469880-b021-11e9-87d9-082066410843.jpg)

**Comment by Moragor** [comment]
It doesn't disappear, it's grayed out. Look closely.

**Comment by grunbag** [comment]
You need to have 20 hatred

**Comment by Austherus** [comment]
Yeah I just realized that, it's just the colors that didn't gray out well, my bad.
