### ISSUE TITLE
Empire Spearmen not attacking

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14661]
Expected behavior and actual behavior:
Some empire spearmen in Norsca are not attacking the player. They are located in the first area after the bridge, where you have to burn the houses.

Steps to reproduce the problem:
Stand in front of them

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_022](https://user-images.githubusercontent.com/53320075/61991495-39b6b880-b027-11e9-9923-6ed7a5c4a834.jpg)
![Austherus_023](https://user-images.githubusercontent.com/53320075/61991496-3a4f4f00-b027-11e9-8166-f66e5fd98aa6.jpg)

**Comment by sioding** [comment]
No really a bug - its the starter area where players should learn to play. but again - leave this open for the DB department

**Comment by Moragor** [comment]
Orange name means they're neutral. Neutral characters don't attack a player unless they are attacked, which on this pictures is not the case since their health bar is not showing.
