### ISSUE TITLE
Empire courier in Norsca not moving

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14665]
Expected behavior and actual behavior:
The empire courier used in the quest None Shall Escape Us is just standing there, I'm pretty sure he should be moving back and forth around the area he's standing at.

Steps to reproduce the problem:
Getting to him is enough to see he doesn't move.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_002](https://user-images.githubusercontent.com/53320075/62000311-5fd16c80-b0aa-11e9-8808-169cf77207be.jpg)
![Austherus_003](https://user-images.githubusercontent.com/53320075/62000312-5fd16c80-b0aa-11e9-9e27-588b783bd6db.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 06.10.2019
