### ISSUE TITLE
Ruinous Power public quest boss (stage III)

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14660]
Expected behavior and actual behavior:
The boss to this public quest spawns behind the players, it should spawn at the center of the summoning circle instead, while the npcs summoning it should react to it (I don't really remember what should happen to them).

Steps to reproduce the problem:
Get to the third stage of the Ruinous Power public quest, in Norsca.

**Testing Screenshots/Videos/Evidences (always needed):**
![Austherus_017](https://user-images.githubusercontent.com/53320075/61991459-b5fccc00-b026-11e9-8189-270942cbf412.jpg)
![Austherus_018](https://user-images.githubusercontent.com/53320075/61991460-b6956280-b026-11e9-9371-5259c85d9e19.jpg)
![Austherus_021](https://user-images.githubusercontent.com/53320075/61991461-b6956280-b026-11e9-8992-c82ab25d1f49.jpg)

**Comment by sioding** [comment]
Fixed with patch from 03.08.2019
