### ISSUE TITLE
Engi, bugmans best and lightning rod

### ISSUE THREAD

**Issue by M0rf** [WarEmu/WarBugs#1466]
Both should be unattackable and would be nice if they were unable to be targeted, use to run in to the problem on live where you would tab target and it would go back and fourth between bugmans best when more then 1 was deployed.

**Comment by Evildoor** [comment]
Unattackable by order - wasn't it fixed?
https://github.com/WarEmu/WarBugs/issues/1401

**Comment by M0rf** [comment]
To be clear they should be unattackable by destruction.

**Comment by Evildoor** [comment]
Are you sure? IIRC, it was possible to attack and destroy them, though i may be wrong. Anyone can clarify?

**Comment by milosxe** [comment]
You can forget about tab targeting when 2 engies deploy their turrets, bugmans and rods, and not to mention if they put a mine on the ground. It makes them hard to click target too.

**Comment by M0rf** [comment]
It would be very difficult to find a clip where it shows them being unattackable, i will try, however i am 100% sure on live you could not attack them.

**Comment by Silentguard** [comment]
Moreover rod and beer was untargetable on live. Mythics did a hot fix for it iirc after patch release.

**Comment by Halhammer** [comment]
Yea I'm also sure they weren't attackable. Only landmines and turrets were.

**Comment by ozarmidrashim** [comment]
No idea how to make monsters unattackable or untargetable.

**Comment by Evildoor** [comment]
Well, i'm not sure, but maybe we can tinker something? Is it possible to make the lighting rod behave like ground aoe ability? Pit of Shades(without channeling of course)/Napalm, for example? If yes, then we also need to attach some effect to it, to make it visible. If there is no way to separate the rod effect from its spawn as a monster, then we can make the ability to produce 2 effects:
1) Ground aoe.
2) Spawn of rod as a monster which does nothing apart from standing and producing its effects, can be killed, but the corpse remains until the end of effect, and then gets removed.

**Comment by Silentguard** [comment]
Can you make it same as guards on keeps unattackable? Also mobs marked as 'dead' can not be targeted by tab, this ones which looks as dead bodies.

**Comment by Evildoor** [comment]
According to #5395, these objects are now unattackable, but still can be targeted.

**Comment by ozarmidrashim** [comment]
Finally solved this crap.
