### ISSUE TITLE
[Standard] Spam abilities

### ISSUE THREAD

**Issue by elk76** [WarEmu/WarBugs#14663]
I tested yesterday in RvR and today in Gunbad
when you get the standard from the ground and keep moving, you can spam both abilities (Invulnerabile and SLAM). No CD

I'm sorry, I did not recorded a video, but I can do next time. Atm I have several sequential screenshots
![Cocoziello_113](https://user-images.githubusercontent.com/46483570/61998394-a2e20e80-b0af-11e9-97b5-c4ec65e04c2f.jpg)
![Cocoziello_120](https://user-images.githubusercontent.com/46483570/61998395-a2e20e80-b0af-11e9-8937-07727db0ddd5.jpg)
![Cocoziello_123](https://user-images.githubusercontent.com/46483570/61998392-a2497800-b0af-11e9-951d-704c74dbe56e.jpg)
![Cocoziello_129](https://user-images.githubusercontent.com/46483570/61998404-c5742780-b0af-11e9-90a0-7a2fbabcea7a.jpg)

**Comment by grunbag** [comment]
fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 03.08.2019
