### ISSUE TITLE
The Joys of War NPCs not reacting to anything

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14668]
Expected behavior and actual behavior:
There's so many of them (almost too many it feels like), and they aren't doing anything, there's supposed to be some action going between dark and high elves here to add to the feeling of an ongoing conflict, instead it just feels like you are shooting at dummies.

Steps to reproduce the problem:
Getting to the area is enough to see the issue.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_011](https://user-images.githubusercontent.com/53320075/62000363-ae333b00-b0ab-11e9-8606-141e61e7e1e1.jpg)
![Austherus_012](https://user-images.githubusercontent.com/53320075/62000364-aecbd180-b0ab-11e9-93b8-d03f9c84c815.jpg)
![Austherus_013](https://user-images.githubusercontent.com/53320075/62000365-aecbd180-b0ab-11e9-9362-ddf4500ceca2.jpg)

**Comment by sioding** [comment]
Sorry the bugtracker is for bugs not for QoS changes. Suggestions are welcome in our forum.

**Comment by Austherus** [comment]
Understood.
