### ISSUE TITLE
The Blighted Isle dragons not interacting

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14669]
Expected behavior and actual behavior:
These guys should be fighting each other, I remember this very clearly. Instead, they are just staring.

Steps to reproduce the problem:
The quest Birds of a Feather can get you to the area quickly, but you can see them from the ground too, nothing specific is needed to reproduce it.

**Testing Screenshots/Videos/Evidences (always needed):**
![Austherus_014](https://user-images.githubusercontent.com/53320075/62000388-30236400-b0ac-11e9-81b4-a847e0a02de5.jpg)

**Comment by Lheana** [comment]
Like for other reports, just a minor thing, QoL thing, not an issue.
