### ISSUE TITLE
Dark elf banner at the beginning of The Blighted Isle not clickable

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14667]
Expected behavior and actual behavior:
You can click the banners at the other two destruction starting areas, but not this one, which means you can't hear the cool little voiceover specific for the dark elfs.

Steps to reproduce the problem:
Try clicking on it.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_009](https://user-images.githubusercontent.com/53320075/62000357-2cdba880-b0ab-11e9-986e-37e033ddaec4.jpg)
![Austherus_010](https://user-images.githubusercontent.com/53320075/62000358-2cdba880-b0ab-11e9-84c0-13624c7f3ebc.jpg)

**Comment by Lheana** [comment]
Well I don't know why this GO has been added. I removed it.
