### ISSUE TITLE
Spires of Narthain public quest issue with the dragons

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14670]
Expected behavior and actual behavior:
On stage 2, the NPCs do not Interact with the dragon, they just stare and pretend. On stage 3, the black dragon disappears and the golden dragon appears on it's place, I"m sure there was supposed to be more interaction and movement between them than that, instead of just the teleporting around. There's very little immersion or engagement with the lack of interaction between all the parts involved.

Steps to reproduce the problem:
Completing the stages is enough to observe all that.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_015](https://user-images.githubusercontent.com/53320075/62000436-4e3d9400-b0ad-11e9-8cde-e7498f6ea65c.jpg)
![Austherus_016](https://user-images.githubusercontent.com/53320075/62000437-4e3d9400-b0ad-11e9-8cb7-7dc7ae2da1ed.jpg)
![Austherus_017](https://user-images.githubusercontent.com/53320075/62000438-4e3d9400-b0ad-11e9-8a02-ab2614f1c2b6.jpg)

**Comment by sioding** [comment]
Sorry the bugtracker is for bugs not for QoS changes. Suggestions are welcome in our forum.
