### ISSUE TITLE
Animals around the Shrine of Lore/House of Lore in The Blighted Isle

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14678]
Expected behavior and actual behavior:
This is from the point of view of a Dark Elf character. The Eagles (Crag Great Eagle) keep attacking the high elf enemies, they are not targetable by the player normally (only through waiting for the auto-attack to target them for you). The same thing happens with the unicorns in that area, Can't target, and they attack the high elfs if they get in their reach. They are also not lootable.

Steps to reproduce the problem:
Moving into their aggro reach is enough to notice the bug.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_002](https://user-images.githubusercontent.com/53320075/62020923-41976980-b19b-11e9-9aff-8d36f2b8de2f.jpg)
![Austherus_005](https://user-images.githubusercontent.com/53320075/62020924-41976980-b19b-11e9-8188-73f779b14461.jpg)
![Austherus_007](https://user-images.githubusercontent.com/53320075/62020925-42300000-b19b-11e9-8a63-5e427a80feea.jpg)
![Austherus_011](https://user-images.githubusercontent.com/53320075/62020926-42300000-b19b-11e9-8660-58cfedf5deb0.jpg)

**Comment by sioding** [comment]
Fixed with patch from 03.08.2019
