### ISSUE TITLE
Stormriver's End PQ, Stage II (Hard) Bugged

### ISSUE THREAD

**Issue by penguinity** [WarEmu/WarBugs#14673]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**

Shyish Eye PQ tooltip reads "The Eye is weakened, kill it!" and it is the objective for Stage II of the PQ. Unable to complete the PQ due to this issue.

When targeting/attacking the Eye, error reads "Target is already dead." or "Invalid Target."

**Steps to reproduce the problem:**

PQ unable to be completed. Did try several options to complete, like opening closed doors in the area (to look for "special weapons", etc) and killed single mob near the Eye to try and trigger an event.

**Testing Screenshots/Videos/Evidences (always needed):**

![Vickey_005](https://user-images.githubusercontent.com/53207508/62013166-d75fd400-b15c-11e9-8657-0beab4e00b89.jpg)

**Comment by sioding** [comment]
fixed with patch from 10.08.2019
