### ISSUE TITLE
NPC Champions (Black Crag) Ulfgor and Korggran spamming Chat with scripts

### ISSUE THREAD

**Issue by Fulkren** [WarEmu/WarBugs#14671]
![ss1](https://user-images.githubusercontent.com/53387375/62001827-acbf3e00-b0be-11e9-95c9-b1d7bd075ddb.png)
 

Noticed this with both NPC Champions.

**Comment by sioding** [comment]
Thats channel 9 - we do use it as a tech channel for addons. just filter the channel
