### ISSUE TITLE
[BG] Using of Enrage Beating breaks Career points display

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#14672]
Last hit of Enrage Beating breaks Career window. It shows nothing instead of hate points. After  next hit (AA or any ability) hate points are showed again

<img src="https://monosnap.com/image/05i0BbMKEU6zKmEFUxhlFlazVBlS15"/>

**Comment by grunbag** [comment]
You mean it doesn’t grant hate during channel for non crit ?

**Comment by grunbag** [comment]
i have no bug

**Comment by Nfkillz** [comment]
no it grants hate but Career window shows nothing until next hit that generates hate

**Comment by grunbag** [comment]
I can’t reproduce

**Comment by xaraxdestr** [comment]
I was able to reproduce it. After channel it show 0 hate and will be shown again after next AA or hit.
100 Hate before channel
0 Hate after channel
100 Hate after next Auto Attack

![Knochenschild_035](https://user-images.githubusercontent.com/45398873/62128435-b4583000-b2d4-11e9-8ca5-083cc55c6ac3.jpg)
![Knochenschild_036](https://user-images.githubusercontent.com/45398873/62128441-b7532080-b2d4-11e9-912b-dbc157bfe294.jpg)

**Comment by grunbag** [comment]
So I you don’t have a target selected to hit when channel ends career resource bug ?

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by Nfkillz** [comment]
ty <3

**Comment by sioding** [comment]
Fixed with patch from 03.08.2019

**Comment by Nfkillz** [comment]
it s still buged

**Comment by grunbag** [comment]
It works fine for me

**Comment by grunbag** [comment]
I see the issue fixed

**Comment by Nfkillz** [comment]
now it works better but still bugged if enraged beating is interrupted. To reproduce: use EB than jump and your career resource bar will show 0
