### ISSUE TITLE
Warhammer of the March

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#1467]
This IB's weapon from Empire chapter 2 influence is "Both Hands or Off Hand", should be "Both Hands".

**Comment by Reggaewaldo** [comment]
I can not find any information that it should be a 1h ? When I check the DB the DPS + model point towards it being a 2hander. Can you confirm with a source that it should be a one hander ?

**Comment by Evildoor** [comment]
Not onehander, twohander.

**Comment by Reggaewaldo** [comment]
Perfect, then it is as it should be in the DB. Change will roll over to live after next patch.
