### ISSUE TITLE
The Watchtower Public Quest - Stage II issue

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14676]
Expected behavior and actual behavior:
The mages sitting at the conduit areas are not targetable nor lootable. I managed to target them and finish them off probably because of my auto-attack helping with targeting them, but otherwise it's impossible. I found a similar, older report of this bug but it was about the guards. In my case, the guards were normally targetable, the mages were the problem;

Steps to reproduce the problem:
Get to stage II of the PQ and attack any of the mages defending the conduit places.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_006](https://user-images.githubusercontent.com/53320075/62016132-9ed4f000-b186-11e9-86e8-ce43e719f782.jpg)
![Austherus_007](https://user-images.githubusercontent.com/53320075/62016133-9ed4f000-b186-11e9-9080-c82ce31186e6.jpg)
![Austherus_008](https://user-images.githubusercontent.com/53320075/62016134-9ed4f000-b186-11e9-8649-e91467e03020.jpg)

**Comment by sioding** [comment]
Fixed with patch from 03.08.2019
