### ISSUE TITLE
Nimosar Public Quest - Stage II

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14675]
Expected behavior and actual behavior:
The braziers that must be destroyed are wrongly interactable. If you click them they get the visual of being destroyed, but that doesn't count towards advancing the PQ, making it very confusing. I saw another player trying the PQ and them leaving because it didn't work for him either. You can of course attack them, which will complete the stage, but the fact that they can be clicked and falsely "destroyed" when you click them makes it very confusing.
They also respawn after a while, which I'm not sure is supposed to happen.

Steps to reproduce the problem:
Get to Stage II of the PQ and click on the braziers, you'll notice they change but do not count towards completion. Them attack them, you'll notice they now count once they are dead. Confusing.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_003](https://user-images.githubusercontent.com/53320075/62016001-e73fde00-b185-11e9-8acc-5172d9b7a38a.jpg)
![Austherus_004](https://user-images.githubusercontent.com/53320075/62016003-e7d87480-b185-11e9-9850-962cc2e4cfe2.jpg)
![Austherus_005](https://user-images.githubusercontent.com/53320075/62016005-e7d87480-b185-11e9-9476-e4c368af1a17.jpg)

**Comment by Lheana** [comment]
Nothing that prevents from completing the PQ, so I close it.
