### ISSUE TITLE
Destruction of the Weak: "Kill Refugee Fighters" does not count all refugees.

### ISSUE THREAD

**Issue by DavidENishball** [WarEmu/WarBugs#14689]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**
The quest in the Marauder starting zone "Destruction of the Weak" only grants credit when killing Refugee Handgunner.  No credit is granted for Refugee Spearman or Duelists

Expected: Credit is granted for killing any enemy with "Refugee" in its name.

**Steps to reproduce the problem:**
Create a new Chaos Marauder.
Advance the story to the second rally point
Accept the quest "Destruction of the Weak" to kill 8 Refugee Fights
Kill a Refugee Spearman or Refugee Duelist.
-> notice that the quest does not advance.
Kill a Refugee Handgunner
-> notice that the quest advances.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
Hm sorry but your report is not clear. You talk about a quest called "Destruction of the Weak", but there is no quest called like that. There is a PQ nevertheless, but Spearmen and Duelists already both count toward the PQ.
So I guess you talked about the quest 'Nowhere to Hide', if that's the case, NPCs will both count for the quest after next patch.

**Comment by sioding** [comment]
Fixed with patch from 06.10.2019
