### ISSUE TITLE
Goldenwing Eyas quest - Goldenwing Enemies

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14681]
Expected behavior and actual behavior:
The creatures "goldenwing eyas" have a "completed quest" icon on their head when you are tasked to interacting with them, which is very strange and confusing (the pattern is to have that only on quest givers). One of them also gets underground sometimes.

Steps to reproduce the problem:
Get to the stage of the quest in which you have to Interact with them.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_003](https://user-images.githubusercontent.com/53320075/62038171-a2d73100-b1cb-11e9-9fae-89adccc4af8e.jpg)
![Austherus_004](https://user-images.githubusercontent.com/53320075/62038172-a2d73100-b1cb-11e9-8121-6f2c8b552986.jpg)

**Comment by Lheana** [comment]
That's because they are quest finisher.

**Comment by Austherus** [comment]
Understood, but that's not how it was supposed to be.
