### ISSUE TITLE
Dreamshade Forest Public Quest - Stage I

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14680]
Expected behavior and actual behavior:
Disarmed traps rearm after a little while, but they do not count as another trap when disarm (I don't think they should anyway). The problem here is that, because they rearm, you can never know which ones have been already disarmed, and end up interacting endlessly with the same few traps. In my case, it was stuck at 19/20 traps disarmed, I just gave up.

Steps to reproduce the problem:
Get to the PQ during stage I.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_000](https://user-images.githubusercontent.com/53320075/62037789-d9607c00-b1ca-11e9-882b-6a467bc16494.jpg)
![Austherus_001](https://user-images.githubusercontent.com/53320075/62037790-d9607c00-b1ca-11e9-82e2-0909f7742e5e.jpg)

**Comment by Lheana** [comment]
With next patch, traps will despawn when they are destroyed.
Nevertheless, note that there are 20 traps, and they don't respawn, so you will still have to search for them.

**Comment by sioding** [comment]
fixed with patch from 10.08.2019
