### ISSUE TITLE
Goldenwing Eagles and Goldenwing Fliers

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14683]
Expected behavior and actual behavior:
These guys are really hard to attack. The game will act as if they are out of reach or "too close", not allowing you to attack them. You can see that the numbers on your skills are not lit, which means they are supposed to be out of reach, even if you can actually attack them; the player character doesn't even get on battle stance. Also happens to so many other NPCs I'm encountering as I advance through Dark Elf chapters.

Steps to reproduce the problem:
Doesn't happen to all of them, but to a lot of them, so you might need to look around for a bit

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_008](https://user-images.githubusercontent.com/53320075/62038813-d5cdf480-b1cc-11e9-97b7-689cf60db410.jpg)
![Austherus_009](https://user-images.githubusercontent.com/53320075/62038814-d5cdf480-b1cc-11e9-845f-c34100abb98b.jpg)
![Austherus_010](https://user-images.githubusercontent.com/53320075/62038815-d5cdf480-b1cc-11e9-85d1-8fdad39b2245.jpg)
![Austherus_011](https://user-images.githubusercontent.com/53320075/62038816-d6668b00-b1cc-11e9-944f-2acb6f8abce7.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 10.08.2019
