### ISSUE TITLE
NPCs not attackable outsite Gon'Seraph PQ

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14686]
Expected behavior and actual behavior:
These high elfs guarding a carriage looking thing are not attackable, not even clickable. They'll suddenly start attacking after you stand around for a while, but they will suffer from the same problem as many other enemies in the area: they can't be looted and they'll be considered "not attackable" by the player, even though you can attack them after they start attacking.

Steps to reproduce the problem:
Try selecting them and attacking them.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_016](https://user-images.githubusercontent.com/53320075/62039642-7a046b00-b1ce-11e9-9147-7251c0d4feef.jpg)
![Austherus_017](https://user-images.githubusercontent.com/53320075/62039645-7a9d0180-b1ce-11e9-9de0-55cd884ae547.jpg)
![Austherus_018](https://user-images.githubusercontent.com/53320075/62039646-7a9d0180-b1ce-11e9-8135-4f07f7e743c5.jpg)

**Comment by sioding** [comment]
fixed with patch from 10.08.2019
