### ISSUE TITLE
Naked NPC

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14684]
Expected behavior and actual behavior:
The Blighted Isle, chapter 2, in the camp with the big tent. The dude is naked.

Steps to reproduce the problem:
He is naked.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_012](https://user-images.githubusercontent.com/53320075/62039156-7de3bd80-b1cd-11e9-9559-a23a366d0a62.jpg)

**Comment by Lheana** [comment]
Unconstant issues, NPCs may appear naked sometimes, but if you run away and come back he will be dressed again.
