### ISSUE TITLE
The Corruption Within quest

### ISSUE THREAD

**Issue by xyeppp** [WarEmu/WarBugs#1468]
Simon Hirtzel is being continously killed by a higher level hero named Oswald Striker, resulting in the quest being nearly impossible to complete. 
Few dead-alive bodies on the ground around him as well.

**Comment by Reggaewaldo** [comment]
Will take a look at this and try to keep em of each others throat.

**Comment by Reggaewaldo** [comment]
Did some testing and the faction will not change properly might require a server restart to verify functionality, Will do some more testing later on.

**Comment by Meralors** [comment]
Been fixed a while ago, closing.

**Comment by sanka22** [comment]
This npc is dead and does not respawn.

**Comment by VonEpic** [comment]
The NPC Simon Hirtzel remains dead/un-re-spawned.
