### ISSUE TITLE
Prize of War quest, can't talk to NPC

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14685]
Expected behavior and actual behavior:
I'm supposed to talk to Urathos Baneblade after searching the Noble's Chest, but the quest doesn't point to him, neither can I talk to him even if I try. I thought I had to talk to someone else at first, but there's nothing at all on the map.

Steps to reproduce the problem:
Finish the step that takes you to the Noble's Chest.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_013](https://user-images.githubusercontent.com/53320075/62039374-f64a7e80-b1cd-11e9-8ebf-b798fc46e772.jpg)
![Austherus_014](https://user-images.githubusercontent.com/53320075/62039375-f6e31500-b1cd-11e9-8965-85457cade38c.jpg)

**Comment by Lheana** [comment]
You are not meant to talk to him, the quest finisher is the noble's chest. So interact with it again.
