### ISSUE TITLE
IndexOutOfRangeException ...flood

### ISSUE THREAD

**Issue by lilimx** [WarEmu/WarBugs#14688]
Hey,
for about a week I see a flood of spam every time a zone locks (or seconds before) for Order. Can't confirm this happened while a destro lock (didn't noticed that)

Im standing in the zone while I get flooded. Can confirm this happend in:
Caledor (to Fell Landing)
![Belgracine_000](https://user-images.githubusercontent.com/23266079/62050791-44817100-b212-11e9-8da4-3176ae4d15e4.jpg)

Avelorn/Saphery locked (to Dragonwake)
Friday 26.7.2019
![Liline_000](https://user-images.githubusercontent.com/23266079/62051256-4697ff80-b213-11e9-9389-61b932e38796.jpg)

and in Black Crag (to Butchers Pass)....but this time the spam was even worse.
Monday 29.7.2019
![Liline_002](https://user-images.githubusercontent.com/23266079/62050903-827e9500-b212-11e9-873f-8dacbf7c13c7.jpg)

**Comment by sioding** [comment]
fixed with patch from 10.08.2019
