### ISSUE TITLE
[Item] Witch Elf Bloodlord Adornment Alternate appearance can't be applayed

### ISSUE THREAD

**Issue by kalliantribe** [WarEmu/WarBugs#14694]
**Expected behavior 
I should be able change appearance of my Bloodlord Adornment (Bastion Stairs influence cloak)

and actual behavior:**
Alternative appearance can't be apply
May be because it has "two hands" property (should be "back" property)
**Testing Screenshots/Videos/Evidences (always needed):**
![Bloodlord Adornment](https://user-images.githubusercontent.com/53464000/62106237-67ad2e80-b2ad-11e9-8bae-8a5245baa04c.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 10.08.2019
