### ISSUE TITLE
Dark elf sorcerer special emote

### ISSUE THREAD

**Issue by roxyrevolver** [WarEmu/WarBugs#14699]
The special emote for dark elf sorcerer is messed up . You can see the wire frame of the effect and the animation gets stuck even if you go into battle or ride your mount . The only way to end the animation is to exit the game

**Comment by roxyrevolver** [comment]
The special emote for dark elf sorcerer is messed up . You can see the wire frame of the effect and the animation gets stuck even if you go into battle or ride your mount . The only way to end the animation is to exit the game

**Comment by sioding** [comment]
Duplicate of #8129
