### ISSUE TITLE
BB - final boss bugged!

### ISSUE THREAD

**Issue by Elflord123** [WarEmu/WarBugs#14690]
See pls video.

If you die on the boss to 20% ( stage of attraction) and rise at the beginning of danzhe, the boss will automatically attract you to all, then you will reappear at the boss and get loot and influence

https://youtu.be/I02HEr9pdOM
https://youtu.be/I02HEr9pdOM
https://youtu.be/I02HEr9pdOM

**Comment by Lheana** [comment]
No need to open a new ticket, if you wanna add information, just comment your previous one: #14444.
