### ISSUE TITLE
Channel failure to cast if target buff list is full

### ISSUE THREAD

**Issue by Qrazy** [WarEmu/WarBugs#1469]
The BW ability Withering Heat is sometimes failing to cast on keep doors and keep lords. I've tried to find a way to reproduce this but it seems random when it happens.

Example, I cast two dots on keep door, try to use WH, it fails. No dots on the door/lord, fails. I can try again with dots or no dots, it may or may not cast. It doesn't seem to be a range issue as I can stand near (1-2 feet) the door/lord and it either casts or it doesn't. Some weird LoS bug perhaps?

**Comment by Qrazy** [comment]
Just to clarify, I am not out of AP when this does or doesn't happen.

**Comment by ozarmidrashim** [comment]
This is because buffs are spammed against Keep Doors and Keep Lords. If their buff list is full, your attack won't go off.
