### ISSUE TITLE
Dlack Dragon Resets now

### ISSUE THREAD

**Issue by Skullgrin** [WarEmu/WarBugs#14691]
The Black Dragon Champion from bug #14555 no longer despawns, however he constantly resets to full health. It appears that he responds to your attack, then loses focus on you and attempts to fly away (reseting his health) then attacks again if you continue to attack him.

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 10.08.2019
