### ISSUE TITLE
Terror debuff and hidden snare debuff near the bank in Altdorf

### ISSUE THREAD

**Issue by Tragus90** [WarEmu/WarBugs#14697]
Snare persist after debuff expires.

![Wolfang_000](https://user-images.githubusercontent.com/51726548/62175743-00d85580-b33f-11e9-8c20-44768486c1a6.jpg)

**Comment by grunbag** [comment]
it seems it happened because you were in the sewers

**Comment by Scophis** [comment]
experienced 
![Drengur_055](https://user-images.githubusercontent.com/40274248/63964555-a47c6900-ca97-11e9-844d-b467a2d1e422.jpg)
the same strange terror-debuffing  in that area. haven't been in a dungeon before though.
