### ISSUE TITLE
Divine Warding - WP Tactic

### ISSUE THREAD

**Issue by RinenX** [WarEmu/WarBugs#14698]
**Expected behavior and actual behavior:**
Divine warding procs on direct heal crit.
When you learn the skill and add to tactics for the **first time**, it will proc on your first direct heal crit. 
Before relogging, tested direct heals on self and others for a few minutes but Divine Warding never proced on crit.
Divine Warding did not start procing again until I re-logged.

**Steps to reproduce the problem:**
Attempted to zone to fix issue and it did not correct itself. 
Had to relog for the proc to work again.
Reset all mastery points, logged off, re-learned skill and issue did not return.

**Testing Screenshots/Videos/Evidences (always needed):**
Pictures not taken during the first time I learned skill. Skill definitely did not proc again until I re-logged.

**Comment by grunbag** [comment]
i can't reproduce, it correctly proc on all my crit heal
