### ISSUE TITLE
renown

### ISSUE THREAD

**Issue by lameth321** [WarEmu/WarBugs#14695]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

its only i have 37 to renown and only can expend 30 points. Ty for all, and good job.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by sioding** [comment]
And your level is? Some screenshots?

**Comment by sioding** [comment]
No answer since 27 days. close.
