### ISSUE TITLE
Some Bloodlord Items I can equip without wards and others I can't.

### ISSUE THREAD

**Issue by Mizoverlord** [WarEmu/WarBugs#14692]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**
I can Equip my bloodlord Chest, Gloves and boats, But not belt Jewlery or Pistol from BS dungeon

**Steps to reproduce the problem:**
Please allow me to equip all the bloodlord gear, Not sure why I was able to equip some and not the rest,  I have received enough Inf to buy the weapons, but can't equip them.  Like i said in my previous post.  PVP Armor should also be another way to unlock wards in PVE.

For example, Equipping a full set of Invader will allow you to used a full set of Bloodlord.  This way players don't have to be strickly pve or pvp.  and as dungeons become old news, players can still earn wards from PVP and not have to wait 3 weeks for 1 group of gunbad to wear gear 3 wards higher.   I want to continue to enjoy dungeons and get more gear.

**Testing Screenshots/Videos/Evidences (always needed):**
Maserati Order WH RR 78

**Comment by sioding** [comment]
Any error message?

**Comment by wargrimnir** [comment]
You need to complete wards from the previous dungeon to wear items in the next dungeon. Items that can currently be equipped without wards needs to be fixed.

**Comment by sioding** [comment]
fixed with patch from 10.08.2019

**Comment by Mizoverlord** [comment]
This is good but unfortunate, I purchased and place many talisman in my blood lord armor and can no longer equip.  I understand this is how it’s supposed to be but shouldn’t I receive a griffin mount for bringing this bug that allowed some to equip (including myself) bloodlord gear without wards.
