### ISSUE TITLE
Reikland Hunting the Hunters Noble Vinzenz can´t be attacked

### ISSUE THREAD

**Issue by mrharleyking** [WarEmu/WarBugs#14700]
In Reikland at the puplic quest: Hunting the Hunters there is Noble Vonzenz who we need to kill for the Annhilation Quest. but he can´t be attacked.
![Quinzel_008](https://user-images.githubusercontent.com/53540524/62245950-f4a5d400-b3e2-11e9-9758-29e17237497b.jpg)
![Quinzel_007](https://user-images.githubusercontent.com/53540524/62245951-f4a5d400-b3e2-11e9-8ade-73babb8d93d6.jpg)

**Comment by Lheana** [comment]
Well maybe someone pulled him at the top and the location was confusing, but I just checked and he is where he is meant to be: at the bottom of the tower.
