### ISSUE TITLE
character select not loading

### ISSUE THREAD

**Issue by izmatik** [WarEmu/WarBugs#14706]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**
my character select screen no longer loads. once the game opens and logs in, it goes to a black screen with a chat box that says, " searching for allies..." and stays.  I have restarted and reinstalled the game but nothing fixes this. I have made a second account and it works perfectly. I am hoping to get the original account recoverd.

**Steps to reproduce the problem:**

everytime I log in

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by sioding** [comment]
Please ask in our tech forum for help. The bugtracker is only for ingame problems.
