### ISSUE TITLE
Zealot Invader 7 piece proc

### ISSUE THREAD

**Issue by CoffeeForAll** [WarEmu/WarBugs#14702]
Expected behaviour:
Path of Alchemy abilities have a 10% chance to proc "Deep Scheming".

Actual behaviour:
The buff "Deep Scheming" procs from all healing and damaging abilities (Path of Witchcraft, Path of Dark Rites included), as well as the mount and buffs.

Reproduction:
Equip full invader and use abilities.

Evidence:

Set bonus
![Aronax_085](https://user-images.githubusercontent.com/28750021/62288059-d5975880-b45b-11e9-91a4-ceef9e341d39.jpg)

Dust of Pandemonium (Path of Dark Rites)
![Aronax_084](https://user-images.githubusercontent.com/28750021/62287770-1b075600-b45b-11e9-96e2-d4ae8052c72b.jpg)

Dark Medicine (Path of Witchcraft)
![Aronax_083](https://user-images.githubusercontent.com/28750021/62287882-6883c300-b45b-11e9-88e8-0188062d91d4.jpg)

Tzeentch's Cordial (core heal over time)
![Aronax_093](https://user-images.githubusercontent.com/28750021/62288946-c6b1a580-b45d-11e9-8c49-df791612fd06.jpg)

Mark of the Spell Destroyer
![Aronax_094](https://user-images.githubusercontent.com/28750021/62290073-b222dc80-b460-11e9-94e5-50bd7c463f5f.jpg)

Harbinger of Doom
![Aronax_097](https://user-images.githubusercontent.com/28750021/62290773-696c2300-b462-11e9-81c2-bec845e2798d.jpg)

Summoning Mount
![Aronax_096](https://user-images.githubusercontent.com/28750021/62290281-45f4a880-b461-11e9-947c-f51c6d87fbb8.jpg)

**Comment by sioding** [comment]
Fixed with patch from 03.08.2019

**Comment by CoffeeForAll** [comment]
I'm sorry, but the problems still exists
