### ISSUE TITLE
[Warrior Priest] Tactic: Guilty Soul

### ISSUE THREAD

**Issue by Bejkon** [WarEmu/WarBugs#14705]
Edit: I think i solved this one on my own. I was overlooking the fact i had DF slotted, and used 1.25 as base value instead of 1. When I took my damage without DF and multipled with 1.45(DF+GS) it all basically checks out. My bad!

The dmg bonus % per stack seem to be 4, rather than 5 when testing. At the same time, .getstats shows 5% as per tooltip. Exciting Mysteries!
![Guilty Soul](https://user-images.githubusercontent.com/35146895/62336326-1cbf3100-b4d0-11e9-85b2-bd4819416571.JPG)

Is my math wrong? Am i missing something else? Can getstats even be wrong? Is the ability bugged and buffing less than intended?

To reproduce: simply slot the tactic, hit dummies with wrath abilities, compare dmg numbers between diffrent amounts of buff stacks, also check getstats at diffrent stacks if wanted/needed.

Below is a pic of my combat log, To make it easier to read ive added numbers on the left at the first timestamp with a new amount of stacks:
![Guilty Soul Bug](https://user-images.githubusercontent.com/35146895/62335855-c94be380-b4cd-11e9-8623-ef950d0df9e0.png)

And here is .getstats from each stage:

0stack
![Master3Damage 0 stack](https://user-images.githubusercontent.com/35146895/62336073-e208c900-b4ce-11e9-80cb-b3743fa64094.jpg)

1stack
![Master3Damage 1 stack](https://user-images.githubusercontent.com/35146895/62336078-eaf99a80-b4ce-11e9-9bb5-4a37e980478d.jpg)

2stack
![Master3Damage 2 stack](https://user-images.githubusercontent.com/35146895/62336082-f220a880-b4ce-11e9-91ff-6d9b84b629ed.jpg)

3stack
![Master3Damage 3 stack](https://user-images.githubusercontent.com/35146895/62336085-f8168980-b4ce-11e9-9963-467d6e6fc12d.jpg)

4stack
![Master3Damage 4 stack](https://user-images.githubusercontent.com/35146895/62336088-fd73d400-b4ce-11e9-8f0b-b0efe8ea3148.jpg)

As you can see, this would suggest the tactic is working as intended, yet 702 * 1.2 is not 814 and 814/702 is closer to 1.16... Spooky, right?

/Bejk

**Comment by Irvid** [comment]
Just in case, considering Target Dummy stats and resulting crit chances:

Crit damage multiplier is a range not a constant ~ it should be about 0.35-0.5, iirc.
Meaning, the variance you noticed could be attributed to this range, instead of Guilty Soul's buff component being dysfunctional.

**Comment by Bejkon** [comment]
Ok, did some more numbers, think i figured it out.

The above tests where all run with DF slotted. Did tests with DF unslotted and then GS did actually increas damage with 20% at max stack. 561dmg at 0stack, 674 at 4stack.

So it seems like its a thing with how they both stack.
They seem to both look at a base hit without tactics buffing dmg.
561+561*0.25+561*0.2=813,45 which is close enough to my 814 considering WAR seems to like rounding up.

IF this is the way its intended to be, then there is no problem i guess. Im not sure if this is the way dmg% stacks across the board, maybe its the same for slayer mechanic + flanking, AM mechanic + DF, WL Flanking+Revenge, GWM + FO for tanks, etcetc. havent thought about it before, will need to go check.
