### ISSUE TITLE
The Guild cannot invite me

### ISSUE THREAD

**Issue by Alice0016** [WarEmu/WarBugs#14708]
My character is called Niniell and I would like to enter the "Cavalieri X Caso" guild but no authorized member can do it because the window to accept the invitation does not appear.
Other mine characters can be invited and enter the guild.
Please help me :(
Thanks

**Comment by Lheana** [comment]
Are you currently in a guild?

**Comment by Alice0016** [comment]
No am not

**Comment by Alice0016** [comment]
Oh my god, thanks and sorry
