### ISSUE TITLE
Bastion stair Inf went backwards

### ISSUE THREAD

**Issue by Nuelar** [WarEmu/WarBugs#14703]
So, after completing two wing of bastion, my inf didnt go up at all.. was at 30k. ported to IC, now says 28k? I don't have any screen shots.. besides the one that says I was supposed to get Inf from the kill.... figured I'd just have to do it again regardless.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by sioding** [comment]
No screens - no timestamps - no names. Dunno how we can help here. Please give more information in here and i will reopen this one.
