### ISSUE TITLE
Fritz Meinrich

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14704]
Expected behavior and actual behavior:
This guy has no animation.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_002](https://user-images.githubusercontent.com/53320075/62327317-aea24c00-b486-11e9-9298-8818660888e5.jpg)
![Austherus_003](https://user-images.githubusercontent.com/53320075/62327318-af3ae280-b486-11e9-9e1d-bf6007540dda.jpg)
![Austherus_004](https://user-images.githubusercontent.com/53320075/62327319-af3ae280-b486-11e9-8b8e-d8731a7ffaf0.jpg)

**Comment by sioding** [comment]
fixed with patch from 10.08.2019
