### ISSUE TITLE
Unequipping bloodlord weapon removes buff even if second equipped weapon is also bloodlord weapon

### ISSUE THREAD

**Issue by Ztil** [WarEmu/WarBugs#14707]
**Expected behavior and actual behavior:**

**Expected behaviour:** 
If equipping 2 blood lord weapons and then unequipping one the 5% damage buff and armor/toughness debuff should still remain. 

**Actual behaviour:** 
When equipping 2 blood lord weapons and then unequipping one the buff is removed even though you still have one weapon equipped which should provide the buff. 

**Steps to reproduce the problem:**
As described above

**Testing Screenshots/Videos/Evidences (always needed):**
n/a

**Comment by grunbag** [comment]
Unequip a weapon with a buff associated will remove the buff on you. If you equip 2 Bloodlord only one stack is added to yourself . But if you unequip one of them it will cleanse the Bloodlord buff from you . It’s intended this is how weapons buff works . You need to unequip both then equip one only . The same thing happen if you equip 2 weapons with same proc and unequip one of them
