### ISSUE TITLE
Trail of Darkness in Chrace is Bugged (Quest)

### ISSUE THREAD

**Issue by Ercenberth** [WarEmu/WarBugs#14709]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Make sure you've checked the wiki before you post something ToK related:
https://wiki.returnofreckoning.com/

**Expected behavior and actual behavior:**
When you reach Chrace Border, Eastern Cliffs and Western Cliffs you should scout 'em for the mission but, When you explore the area, nothing happens. 

**Steps to reproduce the problem:**
Liraenor Nightwisper (elf chapter 3) gives you the Mission to explore the area around chrace but, when you reach the areas, nothing happens and you cannot complete the mission.

 

**Testing Screenshots/Videos/Evidences (always needed):**
![Nolgor_005](https://user-images.githubusercontent.com/22793740/62393556-cce17800-b56a-11e9-8612-cfe5933cde73.jpg)
![Nolgor_006](https://user-images.githubusercontent.com/22793740/62393570-d539b300-b56a-11e9-842c-ff88b8a9dade.jpg)
![Nolgor_007](https://user-images.githubusercontent.com/22793740/62393583-d834a380-b56a-11e9-85ce-0470a6d6398b.jpg)

**Comment by Lheana** [comment]
You must use the item given by the quest giver 'Dark Elf Forces Report' at the different places.
