### ISSUE TITLE
Engineer Bulwark of the Beast Lord

### ISSUE THREAD

**Issue by Vrafthudnir** [WarEmu/WarBugs#14701]
![Vrafthudnir_001](https://user-images.githubusercontent.com/22417511/62252595-98977b80-b3f3-11e9-8bdc-413d5286d49d.jpg)

Cant complete the Setbonus of Beastlord Set for the Engi because the Bulwark had a German discription and doesnt count when i put it on.. Always be gray and only 4 setpieces shown.. didnt had the book already.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Vrafthudnir** [comment]
So changed it to the english Client, had the german running. It works on the english one but sadly not on the german one.
![Vrafthudnir_002](https://user-images.githubusercontent.com/22417511/62314256-e3b49b80-b492-11e9-8cdd-c17be374a448.jpg)

**Comment by sioding** [comment]
We had that before - you get the bonus - its just not visible in the client. a .getstats will show them
