### ISSUE TITLE
No Campaign Reset Yesterday [Approximatly 1AM] UTC+2

### ISSUE THREAD

**Issue by Ywhi** [WarEmu/WarBugs#14714]
Here's a screen when the Butchers Pass's Fortress lord fell and should reset the campaign. In case, if  it can help.

Order Won The Maw in the morning.

Shining Way was open at the same time aswell.

![unknown (1)](https://user-images.githubusercontent.com/51972885/62410241-8419d580-b5e3-11e9-9cf0-81b690fde8e9.png)

**Comment by Natherul** [comment]
this should no longer be an issue. Many nullrefs have been addressed with the lord since this tickets creation
