### ISSUE TITLE
Stone of Ecelsion Public Quest - Stage II

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14710]
Expected behavior and actual behavior:
During stage II, one of the Tether Stones cannot be targeted, rendering the Public Quest impossible to complete.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_007](https://user-images.githubusercontent.com/53320075/62408717-6dec2500-b5a3-11e9-896b-00ebe31d26fe.jpg)
![Austherus_008](https://user-images.githubusercontent.com/53320075/62408718-6dec2500-b5a3-11e9-9135-2142332563cd.jpg)
![Austherus_009](https://user-images.githubusercontent.com/53320075/62408719-6dec2500-b5a3-11e9-85ea-33e40951f9b2.jpg)

**Comment by sioding** [comment]
fixed with patch from 10.08.2019
