### ISSUE TITLE
Postpatch Rune of Breaking/Harbringer of Doom conversion bug

### ISSUE THREAD

**Issue by dshdf1** [WarEmu/WarBugs#14715]
**Expected behavior 
Toggling on stance: wp converts into int, etc
Toggling off stance: int converts into wp, etc
 actual behavior:**
. getstats and combat log values : Toggled off stance atm is not converting int into wp at all( or just splitting your whole amount of int+wp by 50/50% into both, not sure). Toggling on is working as intended
Tooltip and statdoll show values as conversion is fully correct, but combat log values confirm .getstats data

**Steps to reproduce the problem:**

compare getstat and combat log values with statdoll and tolltip

**Testing Screenshots/Videos/Evidences (always needed):**
Left picture is Rune of Breaking -off, right one - Rune of Breaking On
https://imgur.com/a/V3OWOUT

**Comment by grunbag** [comment]
Wait for client patch

**Comment by grunbag** [comment]
fixed with next reboot
