### ISSUE TITLE
Rune of Breaking

### ISSUE THREAD

**Issue by globalgame** [WarEmu/WarBugs#14717]
RP's Rune of Breaking after patch has bug if location changes or join scenario then player getting wrong stat of intelligence than before to fix it need to turn off Rune of Breaking and make it active again !

Tested getstats changes and damage also was diffrent

**Comment by globalgame** [comment]
still broken even after next patch

**Comment by grunbag** [comment]
You mean when you are using flight master or when you are zoning (walking between High pass and talabecland for exemple)

**Comment by globalgame** [comment]
any scroll book fligh master any port

**Comment by grunbag** [comment]
Ok thanks

**Comment by globalgame** [comment]
![WAR 2019-08-19 05-24-20-45](https://user-images.githubusercontent.com/24555848/63233614-dee53b00-c239-11e9-874e-6c6da6fba026.jpg) Rune of breaking getstats intelligence before porting and after used guild scroll from Praag
first 634 int after ported 275 int and dmg less also

**Comment by globalgame** [comment]
after patch 24/08/2019 still the same and boring... why did touch without knowledge and tests?

**Comment by sioding** [comment]
First strike sweetie. Giving constructive feedback is very much welcome - but this is way over the line.

**Comment by grunbag** [comment]
We haven’t fixed anything yet

**Comment by raptrr** [comment]
https://github.com/WarEmu/WarBugs/issues/14832

**Comment by globalgame** [comment]
it seems it can be closed cause solved
