### ISSUE TITLE
Zealot/RP. Wrong willpower numbers

### ISSUE THREAD

**Issue by TheWarXL** [WarEmu/WarBugs#14719]
Wrong numbers of willpower on the character view on zealot and runepriest

![Screenshot_2](https://user-images.githubusercontent.com/53687034/62421267-c4db2280-b6a7-11e9-885c-f41005dc322d.png)
![Screenshot_3](https://user-images.githubusercontent.com/53687034/62421268-c573b900-b6a7-11e9-9c73-dfe0d9e28671.png)
![Screenshot_4](https://user-images.githubusercontent.com/53687034/62421269-c573b900-b6a7-11e9-8f95-78f8d9d42235.png)
![Screenshot_5](https://user-images.githubusercontent.com/53687034/62421270-c573b900-b6a7-11e9-81ca-5355697b723a.png)

**Comment by grunbag** [comment]
Need a server restart to be fixed . Duplicate
