### ISSUE TITLE
Demonstration of the Runic Shield issue

### ISSUE THREAD

**Issue by Coeno1979** [WarEmu/WarBugs#1471]
First of all, i have to thank the devs for this amazing return of WAR. Thanks a lot. This game is a dream. Now, i bring you a video where you can see that Runic Shield absorbs all magic attacks, melee included. But in RoR it only avoids spells, so you have to fix this. Switch HD quality and read the combat log in this minutes:

3:40 VIDEO TIME (16:30:33 combat log). The IB has not other absorption buffs than the Runic Shield, and you can see that it absorbs Chosen Rending Blade (spirit damage). Notice that it doesnt absorb the Autoattack (because Runic Shield only absorbs magic damage)

3:42 VIDEO TIME (16:30:35 combat log). It absorbs Chosen Ravage. 

Here is the video: https://www.youtube.com/watch?v=jMMscxnij1M

**Comment by Evildoor** [comment]
It is nice that you provided a video, but there is a report about this skill already, you should have posted it here: https://github.com/WarEmu/WarBugs/issues/1430
So i'm closing this ticket and quoting you in the linked issue. Please, make any future discussion about this problem in https://github.com/WarEmu/WarBugs/issues/1430
