### ISSUE TITLE
Can't salvage items.

### ISSUE THREAD

**Issue by Croathis** [WarEmu/WarBugs#14723]
I saw a few posts about this issue, but no comments or any way to resolve the problem so... posting this issue. I'm trying to salvage for my professions in talisman making but running into the issue of not being able to salvage my items. When I attempt to salvage, the magical salvaging window opens and it's blank, I try clicking accept anyway and nothing happens.

I scrolled over to show that the item IS salvageable.
![Angrymonk_000](https://user-images.githubusercontent.com/53713240/62430414-17d1cb80-b6e2-11e9-82a4-ff988f21d43c.jpg)

Window opens with no material list of what the item will be salvaged into.
![Angrymonk_001](https://user-images.githubusercontent.com/53713240/62430423-2c15c880-b6e2-11e9-98a0-6279b6d6dd83.jpg)

I click accept anyway.....
![Angrymonk_004](https://user-images.githubusercontent.com/53713240/62430443-56678600-b6e2-11e9-840c-fc02739ba62d.jpg)

Back to square 1. Nothing happened.
![Angrymonk_003](https://user-images.githubusercontent.com/53713240/62430439-4f407800-b6e2-11e9-9c32-7b98a092a111.jpg)

I just want to be able to do these professions so if this could be addressed/fixed or if I'm personally doing something wrong, please let me know / help me and other players out! Thanks.

**Comment by Blumenpeter** [comment]
Hi  Croathis, 
have you found a answer of these problem?  if yes can you help me i have the same. THX
