### ISSUE TITLE
[Engi] tactic "Extra Ammo" doesnt work. 

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#1472]
The tinkerer path tactic "extra Ammo" http://waronlinebuilder.org/#career=eng;0;0;3;;;3:;;0:0:0:0:
Doesnt increase AP regeneration als it should. 
According to another engineer it works sometimes. And it worked in the past.

**Comment by Evildoor** [comment]
Tested, seems to be working, and even restores 30 AP per 2 seconds instead of 20. Can you think of  any special conditions which cause the tactic to bug out?

**Comment by ozarmidrashim** [comment]
Fixed range and AP value, which were swapped. This ability will only affect 9 people at a time.

Unless I see a confirmation I'll close this tomorrow.
