### ISSUE TITLE
Respecialize issue - Black Guard, Path of Malice

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14726]
Expected behavior and actual behavior:
When respecializing my Black Guard, a single skill point remained. No matter what I did, it always remained there. I tried, picking different skills, moving to a new area, even a server reset didn't fix it.

Steps to reproduce the problem:
I can't say for sure. I was in Inevitable City when I logged in, went to the NPC that you can see on the screenshot and tried to respecialize. One screenshot shows how my points were distributed prior to respecialization, the other shows it after, with the remaining unremovable skill point.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_000](https://user-images.githubusercontent.com/53320075/62446007-103d1180-b738-11e9-9638-847165971bd5.jpg)
![Austherus_001](https://user-images.githubusercontent.com/53320075/62446008-103d1180-b738-11e9-97ee-353a14e3d54b.jpg)

**Comment by sioding** [comment]
Check your gear - you'll get an extra point as a setbonus or on an item.

**Comment by Austherus** [comment]
Thanks sioding, that was the problem. Sorry for wasting your time.

![Austherus_000](https://user-images.githubusercontent.com/53320075/62489898-5f1d9200-b79e-11e9-8a6b-0c803018ebef.jpg)
![Austherus_001](https://user-images.githubusercontent.com/53320075/62489900-5f1d9200-b79e-11e9-847f-834e0d5516e1.jpg)
