### ISSUE TITLE
I can use Bloodlord without the full sentinel

### ISSUE THREAD

**Issue by Layinolias** [WarEmu/WarBugs#14722]
Hello,
Like the tittle say, i can use bloodlord shard without have the full sentinel shard
Shard i have :
Full conqueror, Bestlord, Vanquisher, Invader

2 shard of sentinel Helm et belt
2 shard of Bloodlord Gloves et Boots

**Comment by wargrimnir** [comment]
Duplicate report, already fixed next patch.
