### ISSUE TITLE
Empty Backpack

### ISSUE THREAD

**Issue by LordCrist** [WarEmu/WarBugs#14725]
I didnt know what title to give this. I just wanted you to be aware of this should it happen again.

I placed a Warped Battle Standard in the lake, then I took a SC pop. I came out of the SC, picked up the Standard, which didnt show as having been picked up, so i tried to put it away, which was unsuccessful. I then switched zone via Flight Master when i landed I checked my Backpack and all five bags were completely empty. I relogged to see if it was just being buggy and still empty backpack, No mount/Book of Binding, nothing all  inventory items gone. Just wanted to let you know. I have no desire to try and replicate this for you.

Thanks,
Shampagne

**Comment by Kaelang** [comment]
Appreciate this is an older report - however the lack of information here makes this almost impossible to replicate without having to guess what this report is for. Please re-open with more information if this issue persists.

Closing.
