### ISSUE TITLE
Blue Lvl 16 High Elf Mounts

### ISSUE THREAD

**Issue by Itmritual** [WarEmu/WarBugs#14728]
The level 16 blue Elven Mare is not available in the Guild Tavern for High Elves. But, the other two colors, red and blank pinto, are available. I've seen people with the blue Elven Mares but it isn't up for sale in the guild quartermaster. The level 16 blue Elven Mare should be in the Guild Tavern's quartermaster, but it's not. Instead, there is another brown one which you can find with the normal quartermasters. 

![Miitzie_000](https://user-images.githubusercontent.com/31557076/62495534-2c769800-b7a4-11e9-97b6-cca5c4972b33.jpg)
The vendor in the Guild Tavern selling the rank 38 colored Elven Mares.^
![Miitzie_002](https://user-images.githubusercontent.com/31557076/62495683-ad359400-b7a4-11e9-9ebc-7245d2489c36.jpg)
The vendor selling the Elven Mares.^
![Miitzie_001](https://user-images.githubusercontent.com/31557076/62495541-2ed8f200-b7a4-11e9-8200-6acac2be8c36.jpg)
The vendor selling the Elven Steeds.^

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 19.10.2019
