### ISSUE TITLE
[WH] Ability: Declare Anathema

### ISSUE THREAD

**Issue by Bejkon** [WarEmu/WarBugs#14727]
Tut, will keep it short n sweet this time.

Ability is currently possible to defend agains, something that was never a thing in the past and havent been mentioned in any patch note. This cancels both the stagger and the spunt.

To reproduce:

Get lvl40 WH and a buddy with high parry or mdps m1, stack as much parry as possible on the buddy, use DA a few times. depending on what kind of buddy, and how much parry he produced, you should see DA getting parried and the WH left with nothing but a CD and a sad face.

The case might be the same for WEs mirror of the ability, I cant say for sure.

Pic:
![LÖLÖLÖLÖLÖL](https://user-images.githubusercontent.com/35146895/62477597-99406100-b7a9-11e9-9aed-1795ddd17899.JPG)

/Bejk

**Comment by grunbag** [comment]
fixed with last patch
