### ISSUE TITLE
Can't send mails anymore

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14739]
Expected behavior and actual behavior:
I've been sending talismans to new players the last few days, the problem started when I tried to respond to a "thank you" mail from one of them, pressing the send button didn't do anything. I thought it was just on my side, that the mail was sent anyway, but right now trying to send more talismans and the same happens, the item is never sent, the message just sits there after I press send.

Steps to reproduce the problem:
As far as I can tell, it always happens now, I just can't send mails anymore,

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_002](https://user-images.githubusercontent.com/53320075/62643848-3ec91100-b91f-11e9-8d10-674e1fd22bec.jpg)

**Comment by rameden** [comment]
I had this bug happen to me the other day. If you close the mailbox and reopen it you should be able to send / reply.

**Comment by Austherus** [comment]
> I had this bug happen to me the other day. If you close the mailbox and reopen it you should be able to send / reply.

Do you remember doing something else other than close/reopen? Not even logging out does it for me. I'll have to try again next time I'm on.

**Comment by lilimx** [comment]
Hey,
pls take care if you want to send a message you are still targeting the mailbox. (Can't see on this pic that you are targeting the mailbox)

**Comment by sioding** [comment]
answer given - close
