### ISSUE TITLE
Assistant Eversight not targetable

### ISSUE THREAD

**Issue by Alfred19** [WarEmu/WarBugs#14734]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**

NPC should be able to interact with.
NPC Assistant Eversight walks randomly into wall making interaction impossible.

**Steps to reproduce the problem:**
Go to IC 2456,3366 and watch NPC -should not take longer that one minute till he disappears in wall.

**Testing Screenshots/Videos/Evidences (always needed):**
![Unbenannt](https://user-images.githubusercontent.com/37483326/62550743-0a941880-b86b-11e9-8ef5-b82b46d525a8.jpg)

**Comment by sioding** [comment]
fixed with patch from 10.08.2019
