### ISSUE TITLE
Terathal Shardblade the Rally Master

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14737]
Expected behavior and actual behavior:
I can't pick the first influence reward from him. He's Dark Elf chapter 7, just like Ralkuth (Ralkuth was missing his first rewards, I repórter it a while ago), so maybe it's related?

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_002](https://user-images.githubusercontent.com/53320075/62641710-9e70ed80-b91a-11e9-9da5-60b672ccd302.jpg)
![Austherus_003](https://user-images.githubusercontent.com/53320075/62641711-9f098400-b91a-11e9-9fec-f10278f1df2c.jpg)

**Comment by sioding** [comment]
There is a difference between a missing influence item and an item which is not claimable.

**Comment by Lheana** [comment]
Terathal Shardblade is not the rally master of Dark Elf Chapter 7, but the rally master of T2 RvR High Elf VS Dark Elf (that's why he is in the warcamp...).
You can not pick up the first influence reward because you have just claimed it yet.
