### ISSUE TITLE
Squig herder Gas pet is healing order players instead of destruction

### ISSUE THREAD

**Issue by Torete-war** [WarEmu/WarBugs#14730]
**Expected behavior and actual behavior:**
Squig herder Gas pet has an ability named "Spore Cloud" which in tooltip says in a 30 feets space around the target, ability will heal any of the Squigs pets and the Battle Squig (Squig armor form) included for XX amount.

That ability was bugged for years, not healing anyone, either pets or Squig Armor, now in an attempt to be fixed, the problem has gone even further.... The ability is not healing squigs or Squig armor because **instead is healing ORDER PLAYERS.**

Since some week ago, i noticed the gas squig herder pet was droping green numbers around my order players target and i started check the combat log in chat, which just confirmed what i thought (the ability which should have heal destruction, was healing an Slayer, Kotbs, etc)

**Steps to reproduce the problem:**
Just summon a Gas Squig herder pet and send it to attack order players, you will notice the green numbers in screen and the brown ones in combat log (in combat log, doesn't appear as green numbers, but in pet attacks is marked as "your pet HEALS XXX for"

**Testing Screenshots/Videos/Evidences (always needed):**

-Ability tooltip:

https://imgur.com/ojhdDLf

-Combat log with screenshoot healing order players:

https://imgur.com/mK2UjWu

And the players healed by the Squig herder pet ability "Spore cloud" are:

Younghash (witch hunter lvl 40 renow 72)
Ogisam (Slayer lvl 40 renow 78)
Mayaa (WP lvl 37 renow 52)
Zeabis (Slayer lvl 40 renow 80)
Trolar (Ironbreaker lvl 40  renow 81)
Suicune (Kotbs lvl 40 renow 82)

You can check the classes of the players healed in that screenshoot in forum armory section, and you will see the Squig herder Gas pet is healing order instead of destruction.

**Comment by grunbag** [comment]
fixed
