### ISSUE TITLE
Fort visual bug it appears

### ISSUE THREAD

**Issue by Harkanor** [WarEmu/WarBugs#14735]
Hello,
Just took part in the Maw fort (Harkanor, BG).
After destro started wiping in Lord's room, i escaped trough postern and went to jail to see if other destro and i could free the others. I turned around jail close to the barrier between Fort and cw trying to be sneaky. Order spotted me and i got killed there. When releasing in respawned outside, right where i died. I was not able to attack nor to be attacked. I just stood there among Order just in front of jail. Could even go inside Order's wc. Got the message "you are bound and gagged..." so i assume i was considered as in jail without appearing being in it. Might be related to where i died, close to that barrier.

**Comment by Natherul** [comment]
do you have a picture or can you take a picture with the exact spot shown?

**Comment by Kaelang** [comment]
No additional information was provided - and I'm confident this was the similar issue which was patched in a recent hotfix. If this issue persists please re-open with additional information.
