### ISSUE TITLE
Guild mount issue

### ISSUE THREAD

**Issue by Cygre** [WarEmu/WarBugs#14732]
I bought 3 days ago a guild mount, after getting 2 tokens. Since i bought it i have been unable to use it. It says RR60 , i'm RR66 . Maybe it's only that kind of mounts ? ( the disks )
When i click on it, nothing happen. Server have been restarted since i bought it.
![Sans titre](https://user-images.githubusercontent.com/52246102/62538821-07d9f900-b854-11e9-9f81-0a9be7706c02.png)

**Comment by grunbag** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 17.08.2019
