### ISSUE TITLE
Sarava Scornblade the Rally Master

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14738]
Expected behavior and actual behavior:
She's missing her first influence rewards.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_005](https://user-images.githubusercontent.com/53320075/62642049-50a8b500-b91b-11e9-8fce-f1887cad15c3.jpg)

**Comment by sioding** [comment]
Thanks for all the reports you made the last days - but please start searching before posting.

**Comment by sioding** [comment]
Duplicate of #4821
