### ISSUE TITLE
Can not Log in

### ISSUE THREAD

**Issue by Sigbertus** [WarEmu/WarBugs#14746]
Sry for opening that issue again

but ill got the problem that i can not log in at any one of my chars

i tryed on different tirs and low level chars too

i conekt to the server , go to the char screen and select a char 
if i press the play button ill  get a 15 sec loading screen and then iam back on the char selection screen

please help
Thanks

**Comment by Sigbertus** [comment]
edit:       i logged out in Altdorf

**Comment by pobratim** [comment]
I cant enter RoR too.At any chars.

**Comment by sioding** [comment]
fixed with patch
