### ISSUE TITLE
Missing Basic Influence Reward - Empire Ch. 8

### ISSUE THREAD

**Issue by Croathis** [WarEmu/WarBugs#14748]
There's no basic influence reward for the Empire Chapter 8.

![Stormschaos_000](https://user-images.githubusercontent.com/53713240/62820131-8325fe00-bb25-11e9-9852-36aa03f30bcc.jpg)

Completed influence, collected Advanced and Elite reward, but Basic reward is missing.
![Stormschaos_001](https://user-images.githubusercontent.com/53713240/62820198-68a05480-bb26-11e9-9f7e-73562ad538c2.jpg)

**Comment by sioding** [comment]
Duplicate of #12095
