### ISSUE TITLE
11 attacks in 1 sec

### ISSUE THREAD

**Issue by noobwarrior** [WarEmu/WarBugs#14741]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**

a slayer gave me 11 attacks missed in a sec as you can see in Chat 

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Relife_158](https://user-images.githubusercontent.com/53536809/62715242-66dc7100-ba00-11e9-99d3-d3ddc3fa1d13.jpg)

**Comment by noobwarrior** [comment]
if desired, I have more pictures of other players who also make 6-14 attacks in one sec

**Comment by grunbag** [comment]
You were affected by 2 slayer dot (inevitable doom and onslaught) , deepwound is the only attack he casted this sec and it proc reckless gamble , flame of rhuin and prayer of righteousness , then his AA proc them as well. Nothing wrong here , it’s just dot and proc
