### ISSUE TITLE
Ostland PQ Silkens Stage II is broken

### ISSUE THREAD

**Issue by phudlow** [WarEmu/WarBugs#14740]
**Expected:** Should increment "Eggs destroyed" counter when an egg is right clicked and destroyed during Stage II of Silkens PQ.

**Actual:** Egg is visibly destroyed, but the counter is never incremented.  After killing 10 of the eggs (the amount required to start Stage III), Stage III does not start.

![bug_silkens](https://user-images.githubusercontent.com/5643955/62654859-a37f6e00-b915-11e9-9735-49246fb2e96d.png)

**Comment by Lheana** [comment]
Have you tried attacking them?

**Comment by phudlow** [comment]
That worked.

**Comment by phudlow** [comment]
That worked.  Although right clicking cocoons progresses the first stage, the second stage requires attacking the eggs, although right clicking has a visible break effect.  This is probably working as intended.
