### ISSUE TITLE
Balaghir Whiteblaze not present in High Elf Chapter 8 

### ISSUE THREAD

**Issue by chris639** [WarEmu/WarBugs#14744]
"Blood on the Leaves" quest in High Elf chapter 8 requires talking to Balaghir Whiteblaze. Hes not 
present in the camp
[Tylas_000](https://user-images.githubusercontent.com/53569788/62757648-9b245180-ba41-11e9-81b6-9c2d18ed21bf.jpg)

**Comment by Lheana** [comment]
Indeed, as the quest says, Balaghir is in Avelorn 'in the Shining Guard warcamp overlooking Gaen Mere. '. Quest markers will be corrected with next patch.

**Comment by chris639** [comment]
I totally missed the part where it said "Averlorn" i read over that numerous times and still missed it. I did see Gaen Mere but had no idea where that is. Thanks for the response

**Comment by sioding** [comment]
fixed with patch from 10.08.2019
