### ISSUE TITLE
The Tome of Subjugator does not regenerate Fury.

### ISSUE THREAD

**Issue by Frejulf** [WarEmu/WarBugs#14745]
https://youtu.be/dZwHur3Y1J0

Recorded it happening. Just dropped the Tome in a keep, and noticed it doesn't generate 8 fury/sec.

**Comment by sioding** [comment]
put the tome into your backpack - DON'T switch it with another one - and use it again. 
It will work quite fine.

**Comment by CrimsonFenris** [comment]
Just experienced this bug too. if it's common to all tomes, should it not be fixed by now ?
