### ISSUE TITLE
Trojan associated with login procecedure

### ISSUE THREAD

**Issue by GitHubImp001** [WarEmu/WarBugs#14743]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**

I click on the return of reckoning icon, to start the launcher.  It asks if I "want to let the following program make changes on the computer", and select yes.  The next popup window, where I'd normally click login, comes up, but another window from my antivirus program Malwarebytes, notifies me that a trojan is associated with the login.  The web server box stays red, the login server is yellow.  The connect box stays greyed out.

**Steps to reproduce the problem:**
Screenshots, leaving the window up for awhile to see if it goes through anyway, cancelling all the associated windows with warhammer, stopping other apps from running, getting the trojan warning again.  

**Testing Screenshots/Videos/Evidences (always needed):**

When I try to attach the file, the bottom of this input section gives the error "Something went really wrong, and we can't process that file. Try again."  However, I sent this error initially to your facebook page, and you can find the screenshot there.

**Comment by GitHubImp001** [comment]
![warrorerror1a](https://user-images.githubusercontent.com/53919381/62739927-d0a64c00-b9fb-11e9-8359-8c2b1f4a35e3.jpg)

**Comment by GitHubImp001** [comment]
When I go to your website to try to re-download the installer, https://launcher.returnofreckoning.com/RoRInstaller.exe 
It fails to load the website with the error:  

Secure Connection Failed

An error occurred during a connection to launcher.returnofreckoning.com. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

================
And also in Malwarebytes, I get an error about the trojan again:  

Malwarebytes
www.malwarebytes.com

-Log Details-
Protection Event Date: 8/8/19
Protection Event Time: 5:09 PM
Log File: 2f530694-ba29-11e9-b1a1-40f02ff82228.json

-Software Information-
Version: 3.8.3.2965
Components Version: 1.0.613
Update Package Version: 1.0.11922
License: Premium

-System Information-
OS: Windows 7 Service Pack 1
CPU: x64
File System: NTFS
User: System

-Blocked Website Details-
Malicious Website: 1
, , Blocked, [-1], [-1],0.0.0

-Website Data-
Category: Trojan
Domain: launcher.returnofreckoning.com
IP Address: 104.24.12.77
Port: [62176]
Type: Outbound
File: D:\Program Files\Mozilla Firefox\firefox.exe



(end)

**Comment by sioding** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=32901&p=370930&hilit=Trojan#p370930
