### ISSUE TITLE
Joined Finished Scenario/Empty World

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14752]
Expected behavior and actual behavior:
I joined a Scenario after the timer to join it was almost over. Once I was in, it was empty, the match was over, with the enemy team winning. I couldn't leave, so I waited for the timer to run out. Once it did, I was teleported to Norsca (I wasn't in Norsca when I queued), and there were no NPCs around at all. Logging out fixed the issue, but I thought I should report in case this has any relevance.

Steps to reproduce the problem:
I think what happened is that by waiting too long to accept it, I joined the Scenario after it was won by the enemy (order), and that is what caused the issue.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_000](https://user-images.githubusercontent.com/53320075/62824677-1f78f080-bb78-11e9-9369-7d9663cc09fd.jpg)
![Austherus_001](https://user-images.githubusercontent.com/53320075/62824678-1f78f080-bb78-11e9-8b18-248fd476b5ac.jpg)
![Austherus_002](https://user-images.githubusercontent.com/53320075/62824679-20118700-bb78-11e9-8ba1-a6619c3c4e92.jpg)
![Austherus_003](https://user-images.githubusercontent.com/53320075/62824680-20118700-bb78-11e9-847a-0c5121050720.jpg)
![Austherus_004](https://user-images.githubusercontent.com/53320075/62824681-20118700-bb78-11e9-8138-74001be2b3aa.jpg)
![Austherus_007](https://user-images.githubusercontent.com/53320075/62824683-20aa1d80-bb78-11e9-8a4f-954a88fd5d01.jpg)
![screenshot_000](https://user-images.githubusercontent.com/53320075/62824684-20aa1d80-bb78-11e9-8e79-0dd0b2fb006e.jpg)

**Comment by Kaelang** [comment]
Due to a disconnect from the server, without being fully removed / kicked from the game.
