### ISSUE TITLE
Revoltin' Gobbos Public Quest - Stage I

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14754]
Expected behavior and actual behavior:
Most of the goblins don't count towards the objective. Considering you need 125 dead gobbos, I can't imagine how long it would take, even with a full party.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_011](https://user-images.githubusercontent.com/53320075/62824864-dd50ae80-bb79-11e9-8218-f75863d3322e.jpg)
![Austherus_012](https://user-images.githubusercontent.com/53320075/62824865-dde94500-bb79-11e9-888c-7eca3fb8a356.jpg)

**Comment by Lheana** [comment]
Not much we can do about it for now.

**Comment by Kaelang** [comment]
Fixed in latest versions or RoR.
