### ISSUE TITLE
Gibs's Sneaky Strike hits you for 4000 damage. (1404 mitigated)

### ISSUE THREAD

**Issue by TheWarXL** [WarEmu/WarBugs#14751]
Maw of madness scenario. 1974 armor (rune priest)
Single hit from Gibs (SH)

![Screenshot_2](https://user-images.githubusercontent.com/53687034/62824420-0424da00-bba6-11e9-9fbd-fcd846844808.png)

**Comment by grunbag** [comment]
Fixed
