### ISSUE TITLE
Sorcerer Grip of Fear

### ISSUE THREAD

**Issue by dave2278** [WarEmu/WarBugs#1475]
When a tank uses Juggernaut the tanks that uses it will become stuck permanently

**Comment by ozarmidrashim** [comment]
Not replicable on the test server. If you reported this because you saw it happen to me in game, then bear in mind that you don't need to actually report serious bugs that I have personally witnessed.

**Comment by ozarmidrashim** [comment]
Haven't seen this happen again, so closing this.
