### ISSUE TITLE
Wicked Things - Missing text string in the last dialogue 

### ISSUE THREAD

**Issue by Cl3arSky** [WarEmu/WarBugs#14757]
After finishing the Wicked Things quest, in the last panel before accepting the reward, he refers to me as "-<RACE>"-thing, previously when taking the quest he referred to me as Goblin-thing or so.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**
Take the Wicked Things quest and return the bag.

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/53981934/62826728-edd84780-bbc0-11e9-998d-44c49cf25d4b.png)

**Comment by Lheana** [comment]
Thanks for the report, it will be fixed with next patch.

**Comment by sioding** [comment]
fixed with patch from 17.08.2019
