### ISSUE TITLE
WP "Guilty Soul" tactic

### ISSUE THREAD

**Issue by Bladepower** [WarEmu/WarBugs#14766]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**

Every time you critically hit with a Path of Wrath ability (Bludgeon for example) it should proc a dot on enemy and a buff on you, instead, nothing happens, the tactic is completely not working.

**Steps to reproduce the problem:**

Just slot the tactic and try to crit with any Path of Wrath ability.

**Testing Screenshots/Videos/Evidences (always needed):**

![Bladehammer_014](https://user-images.githubusercontent.com/53433798/62907054-62bba500-bdac-11e9-902c-36b1fbffe786.jpg)

As you can see I crit with Bludgeon and neither the dot or the buff appear with Guilty Soul sloted.
In the screen, I use a target dummy for an easy screenshot but happen in both PVE and PVP as well.

**Comment by grunbag** [comment]
it works fine for me.
