### ISSUE TITLE
Marauders ability charge

### ISSUE THREAD

**Issue by demonzar1** [WarEmu/WarBugs#14765]
After patch of 11/8/19 Marauders ability charge is not working like before.

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format.

**Comment by demonzar1** [comment]
after patch the animation is like flail and charge together 50/50.ty

**Comment by demonzar1** [comment]
I don't know how to make a video but is an animation bug of the skill.

**Comment by grunbag** [comment]
fixed with next patch

**Comment by demonzar1** [comment]
thank you grunbad

**Comment by sioding** [comment]
fixed with patch from 17.08.2019
