### ISSUE TITLE
BUG prison shining Way

### ISSUE THREAD

**Issue by romcoll85** [WarEmu/WarBugs#14769]
hello, during the shining way fortress taking I discovered a bug! My character was put in prison. At this moment my computer has had a propleme. I crash the game and restart. My character appeared in altdorf in front of the shining way portal. I clicked on the portal and my character was more in prison but in the fortress!
In order to check the bug, I died another time. my character returned to prison, I crashed the game and relaunched and found myself in the fort. hoping that it can help.
I was with my engi 'BRICOOL'

Cordialy

**Comment by Natherul** [comment]
should be fixed as of today
