### ISSUE TITLE
Mobs not targetable in Ritual of Metal PQ

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#14761]
In Isle of the Death there is a PQ on destro side named Ritual of Metal where you can't target the mobs you need to kill in the second stage of the PQ.
The mobs are called Guardian of Iron, Guardian of Copper, Guardian of Silver and Guardian of Gold.

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 24.08.2019
