### ISSUE TITLE
Resource boxes spawn in unclickable locations in T4 Dwarfzones

### ISSUE THREAD

**Issue by BomblingTV** [WarEmu/WarBugs#14767]
Resource boxes spawning at Dolgrund's Cairn in KV
And at Karak Palik in TM, spawn inside the Battleobjective and is not clickable for the mostpart unless 2-3 or more boxes have pushed the next spawn so far out that you can reach it

https://imgur.com/a/23HTZoo

**Comment by raptrr** [comment]
https://github.com/WarEmu/WarBugs/issues/15282

**Comment by dalen** [comment]
![Valreci_048](https://user-images.githubusercontent.com/7400/72884261-22226900-3d06-11ea-9ccc-397bf4d2c56f.jpg)
