### ISSUE TITLE
Patch 10-8/19: Melee Squig ability problems have increased

### ISSUE THREAD

**Issue by Rildetarma** [WarEmu/WarBugs#14763]
The issue with Ard Noggin animation no longer working as before, but either not showing, or being some other animation has been recognized (50% of the time it is the animation of Big Claw). It was to be fixed in a hotflix.  As of 11/8, it remains messed up.

Further, from the Hotfix new issues:

- Really Bad Gas has no animation and apparently, no damage now .  It activates with no affect.

-The Tool Tip for Ard Noggin now states it does 0 damage.  

- Drop That animation has changed to the animation of Really Bad Gas

**Comment by grunbag** [comment]
Really bad gas is working , ard noggin is Just visual and Will be fixed for next patch
