### ISSUE TITLE
Mail disappeared

### ISSUE THREAD

**Issue by Lerilla** [WarEmu/WarBugs#14768]
sended amail today.  8:0024 o'clock i had it in my mail, you can see the text in the screen, and at 8:00:37 it disappeared. But i never take the stuff out of the mail. Relog doesnt work.

![Allyselle_027](https://user-images.githubusercontent.com/16804997/62919130-05baf180-bda2-11e9-9b52-83fa97dee55b.jpg)

**Comment by sioding** [comment]
just send a mail from another toon to the target and both will arrive
