### ISSUE TITLE
Bauble in Tor Anroc disappears after player dies.

### ISSUE THREAD

**Issue by Rilos** [WarEmu/WarBugs#1476]
Happened today in Tor Anroc level 21 max scenario.  A tank was holding it and then poof.

![borda_010](https://cloud.githubusercontent.com/assets/14109685/10008226/796c8b2a-609a-11e5-82c1-001e584dc7d3.jpg)

**Comment by Evildoor** [comment]
From my experience it is different for different players - i mean, it seems that the artifact is invisible to some players and visible to others.

**Comment by Tesq** [comment]
sometimes it also fall down in texture, it happen cos the sc have a bad texture spot near order wc and sometimes you can also fall down if are not aware.
But that dosen't matter as artifact reset after 30 sec on the ground.

**Comment by Evildoor** [comment]
Some additional info - it seems that the artifact position is sometimes different on client and server sides. I've noticed many times that when you die with artifact it can appear under your character when you resurrect (even on respawn), but you cannot pick it up. However, at least once it was possible to do the following:
1) Hold the artifact.
2) Die.
3) Get resurrected by a healer, artifact spawns under you feet near healer's position.
4) Run to the place where you've died and where the map shows artifact is, but it is not here.
5) Click the "fake" artifact which still lies near healer's position and successfully pick it up.
