### ISSUE TITLE
is that normal.?

### ISSUE THREAD

**Issue by noobwarrior** [WarEmu/WarBugs#14762]
Here are a few pictures of fight in my opinion were not clean..

![Relife_009](https://user-images.githubusercontent.com/53536809/62834176-09873080-bc49-11e9-8162-2cc488555f5f.jpg)
6 att.from a AM in 1sec..aha ok...badjoke 
![Relife_074](https://user-images.githubusercontent.com/53536809/62834320-a7c7c600-bc4a-11e9-8a9e-6935ad034a84.jpg)
8 att from a BW
![Relife_083](https://user-images.githubusercontent.com/53536809/62834342-ef4e5200-bc4a-11e9-9d3c-1241eb3db2d1.jpg)
the same BW only this time 9 att

![Reallife_002](https://user-images.githubusercontent.com/53536809/62834368-494f1780-bc4b-11e9-99b0-9088f68d6882.jpg)
![Reallife_004](https://user-images.githubusercontent.com/53536809/62834384-b662ad00-bc4b-11e9-8d58-87315d3c9290.jpg)
because of such a similar action I got 7 days ban
![Relife_097](https://user-images.githubusercontent.com/53536809/62834411-19ecda80-bc4c-11e9-8bd7-158ab3671ba0.jpg)
next AM 5att. in 1sec..
![Relife_137](https://user-images.githubusercontent.com/53536809/62834548-85d04280-bc4e-11e9-8087-10983f366f19.jpg)
![Relife_120](https://user-images.githubusercontent.com/53536809/62834582-e9f30680-bc4e-11e9-89e1-dd887fcf93ce.jpg)

hat's not normal most attacks come from his pet in 1sec

![Relife_127](https://user-images.githubusercontent.com/53536809/62834485-aea40800-bc4d-11e9-8b72-d71cc35ed6f5.jpg)
and that's the best so far with 14 att in 1sec 

![Relife_158](https://user-images.githubusercontent.com/53536809/62834619-638af480-bc4f-11e9-8810-79fb7875d651.jpg)
Balnazar*BW 11att in 1sec
![Relife_067](https://user-images.githubusercontent.com/53536809/62834679-3ab72f00-bc50-11e9-83ba-1525d809d7ec.jpg)
AM 7 att in 1sec..

**Comment by Lheana** [comment]
Do you wanna report players you think are cheating or an issue?

**Comment by grunbag** [comment]
It’s called Proc , AA (and dual weird AA on some of your screenshot) and dot. And yes pet have abilities and AA too in addition of pet master AA. Also , CS hit you 4 time in a sec , similar to Squig Herder git them when you and pet hit the same target .

**Comment by noobwarrior** [comment]
and what about the 14att .. from engi or the AM's 6-7 att

**Comment by wargrimnir** [comment]
What about it?

Why don't YOU go research HOW these abilities work before wasting the time of staff members on the bugtracker? If you don't know what a dot is, or how flight time works, or how cast time works, then you're just going to keep complaining about it? Knock it off. There's nothing wrong here aside from your comprehension of the game.
