### ISSUE TITLE
SA, ABM disabled yes, but TA not proc'n now

### ISSUE THREAD

**Issue by CarltonMaxwell** [WarEmu/WarBugs#14760]
I know the issue the with ABM and TA stacking insanely, but after testing this morning TA is not processing the 25% damage increase either.  Thanks!

**Comment by grunbag** [comment]
TA does not show outgoing damage in get stats , but damage is increased . Test ard noggin with and without TA

**Comment by CarltonMaxwell** [comment]
Thank you for clarification.
