### ISSUE TITLE
[Slayer][Abilities] Shatter Limbs

### ISSUE THREAD

**Issue by Lestrigon78** [WarEmu/WarBugs#14774]
Good day!
The skill of Shutter Limbs slayer imposes an increase in the preparation time of an opponent’s skills by 1 sec for each enemy affected. Thus, the minimum time by which the preparation of enemy skills is increased should be 1 second. 
https://pastenow.ru/6DVEF
As you can see in the video, if one target falls under this slayer skill, then the minimum timer is not activated (only the GCD is valid). 
https://youtu.be/ixYryP3yWyM
At the same time, the skill correctly gives an increase in the preparation time of skills, starting from 2 opponents affected. I ask developers to pay attention to the incorrect operation of the Shutter Limbs slayer ability and fix the problem in the nearest hotfixes.
Thank you

**Comment by grunbag** [comment]
1 sec Cd is added but it’s probably lost in the GCD
