### ISSUE TITLE
[Ability] Divine Aid. Incorrect description.

### ISSUE THREAD

**Issue by Lestrigon78** [WarEmu/WarBugs#14772]
Good day!
The warrior priest "Divine Aid" skill has an incorrect description.
According to the description, additional recovery of health is carried out for 10 seconds, while the real time is 5 seconds.
https://pastenow.ru/6DOXA
https://pastenow.ru/6DOXF
I ask you to pay attention to this discrepancy and correct it in the nearest hotfixes.
Thank you

**Comment by Nemesiah** [comment]
I just noticed this as well, the other issue is the hot value is not correct. the amount of healing that is received is not what is stated in the tooltip. it is vastly less.

![Nemie_082](https://user-images.githubusercontent.com/47683300/63211647-8c265900-c13d-11e9-94c6-23238a48dfb0.jpg)

**Comment by Lestrigon78** [comment]
> I just noticed this as well, the other issue is the hot value is not correct. the amount of healing that is received is not what is stated in the tooltip. it is vastly less.
> 
> ![Nemie_082](https://user-images.githubusercontent.com/47683300/63211647-8c265900-c13d-11e9-94c6-23238a48dfb0.jpg)
You're absolutely right. Both the duration and amount of healing in the tooltip are incorrect.

**Comment by grunbag** [comment]
Dot tooltips seems broken it shouldn’t be 3k

**Comment by Nemesiah** [comment]
Indeed. 3k would be serriously op. Lol but a girl can dream right. :p

**Comment by grunbag** [comment]
Yeah ! It should be 10 times less if I recall I’ll check client

**Comment by grunbag** [comment]
fixed

**Comment by sioding** [comment]
fixed with patch from 24.08.2019
