### ISSUE TITLE
Knife of Calamitous Fervor

### ISSUE THREAD

**Issue by Alfred19** [WarEmu/WarBugs#14770]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**
Equipment should have some use.
This one is for melee-zealot apparently.

**Steps to reproduce the problem:**
Win purple bag oRvR pre-r40

**Testing Screenshots/Videos/Evidences (always needed):**

![1](https://user-images.githubusercontent.com/37483326/62930517-dbc2f880-bdbc-11e9-8143-901aa911b162.jpg)

**Comment by sioding** [comment]
hm ? what about witch elfs?

**Comment by wargrimnir** [comment]
It's flagged for Chaos. Will fix.

**Comment by sioding** [comment]
meh - didn't looked at that :/

**Comment by sioding** [comment]
fixed with patch from 17.08.2019
