### ISSUE TITLE
Pack of "Swordmaster of Hoeth" west of Dark Elf Ch.14 unattackable, but agro

### ISSUE THREAD

**Issue by pjz** [WarEmu/WarBugs#14775]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

Kind of like #2789, but they're still un-attackable, though they're no longer lying down.  They seem even _more_ unattackable, in that (contrary to the comment on #2789) even with them targetted, when my magus attempts to throw 'Glean Magic' or 'Flickering Red Fire' at them, I just get the 'Target is unattackable' message, and they are unaffected.

Nearby 'Archmage of Hoeth' mobs _are_ attackable, however.

**Expected behavior and actual behavior:**
Expected:
If they can attack me (which they do, if I get too close), I should be able to attack them.
Actual:
They're unattackable.

**Comment by sioding** [comment]
fixed with patch from 17.08.2019
