### ISSUE TITLE
False "duplicate or invalid name" issue

### ISSUE THREAD

**Issue by pkubin** [WarEmu/WarBugs#14771]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**
I tried to create a character with a name from another character i deleted earlier.

So in short a character reroll with the same name. I get the message "You have entered a duplicate or invalid name. Please enter a new name."

The name is not taken by any other character or player because no character with that name is found in the armory.

I restarted the game client and also waited for a server restart but the name remains not available.

**Steps to reproduce the problem:**
Create a character and delete it. Then create a new character with the same name.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
Wait for the weekly patch, and the name will be available again.
