### ISSUE TITLE
Bloodlord 7th bonus ( Choppa ) 

### ISSUE THREAD

**Issue by Nekkbraka** [WarEmu/WarBugs#14776]
Alright guys, the bonus givs only 30 Str instead 110. Wounds bonus and crit works well. Some photos:

1) original whit no buffs
https://cdn.discordapp.com/attachments/566350265842663425/611543685611651092/Nekkbraka_212.jpg

2) Str buff only 30 bonus
https://cdn.discordapp.com/attachments/566350265842663425/611543683325493279/Nekkbraka_213.jpg

**Comment by sioding** [comment]
Tahst happens when you are using a str pot. it will not stack.
