### ISSUE TITLE
enchanted arrows

### ISSUE THREAD

**Issue by normanis** [WarEmu/WarBugs#14777]
enchanted arrows dont bypass enemy resistances its saids bypass all resistences and festered arrows deal elemental damage. byt in real its do nothing. screens is from dummies byt in real pvp they do same deal even less elemental damage. as u see i use only balistic and enchanted arrows in pics no ather tactics. i didnt know i have auto attack on scout tree ( even that deal bigger dps)
![Tauriela_001](https://user-images.githubusercontent.com/23311386/63111576-a70a9900-bf96-11e9-9345-91318eaa6197.jpg)
![Tauriela_002](https://user-images.githubusercontent.com/23311386/63111577-a70a9900-bf96-11e9-9b27-a135658f581c.jpg)
![Tauriela_003](https://user-images.githubusercontent.com/23311386/63111578-a7a32f80-bf96-11e9-8dcf-65792bc2aee6.jpg)

**Comment by normanis** [comment]
its cant bee npc/dummies dont have magic resistences

**Comment by normanis** [comment]
tested squig and he have same problem

**Comment by grunbag** [comment]
Target dummies have no Def stats, so nothing to bypass

**Comment by grunbag** [comment]
They don't bypass toughness

**Comment by sioding** [comment]
Please bring screenshots from real fights - not against the dummys.

**Comment by normanis** [comment]
well in first why need dummies if they dont have even minimum protection. (dont understand why they are there than). and i checked same abilities in .................. somwhere else . so maby they work as intended. byt 270 damage its really crappy.  rdps sw same for squig is so shitty that i thought its bug and posted it here.  i never thought bypass all resistences and abilitie from elemental hit so WEAK. sorry i posted it tooked your time
p.s same abilitie on my squig is even 30% less dps. (he have aoe pet so its balance with sw aoe).

**Comment by grunbag** [comment]
They are here for you to test damage and rotation
