### ISSUE TITLE
Striking the source

### ISSUE THREAD

**Issue by glxracer** [WarEmu/WarBugs#14773]
Character: Celebrinbor L40 Shadow Warrior
Quest: Striking the source
Area: Avelorn

Issue: 
I tried to start the quest, which I have done before with no issues, and it seems to automatically abandon the quest (Video attached)
![Celebrinbor_005](https://user-images.githubusercontent.com/52716245/63010420-5b4fd680-be54-11e9-96ee-e9435cf905e7.jpg)
![Celebrinbor_006](https://user-images.githubusercontent.com/52716245/63010445-660a6b80-be54-11e9-8202-508fdfe5996f.jpg)
![Celebrinbor_007](https://user-images.githubusercontent.com/52716245/63010455-6c98e300-be54-11e9-8704-10c9de622535.jpg)

[Uploading Striking the source.zip…]()

**Comment by glxracer** [comment]
It also places a new Sceptre of the winds in my Quest items, I now have 9 of them...

**Comment by sioding** [comment]
fixed with patch from 17.08.2019

**Comment by glxracer** [comment]
It also places a new Sceptre of the winds in my Quest items, I now have 9 of them...

**Comment by Lheana** [comment]
It's not a problem, they will all be removed when you will have finished the quest.
