### ISSUE TITLE
Mobs in IC, road to citardel r6 after last patch

### ISSUE THREAD

**Issue by Alfred19** [WarEmu/WarBugs#14789]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**
Mobs used to be r36-~39
They are r6 now- nothing about it in the Patchnotes

**Steps to reproduce the problem:**

Go IC 303,276, target Mobs

**Testing Screenshots/Videos/Evidences (always needed):**
![Unbenannt11111](https://user-images.githubusercontent.com/37483326/63209985-85212b80-c0e8-11e9-9b8c-d2f96831e12e.jpg)

**Comment by wargrimnir** [comment]
Ah, forgot to add that to the patch notes. Thanks.

We got rid of mobs you could easily farm inside of capitals a long long time ago, these were missed until someone reported getting renown from them, but it was just residual healing renown.
