### ISSUE TITLE
Guild RVR Zone Lock Quest

### ISSUE THREAD

**Issue by Lerilla** [WarEmu/WarBugs#14782]
![Lerilla_202](https://user-images.githubusercontent.com/16804997/63193125-f3280d00-c06c-11e9-846f-c600c4b9d6c0.jpg)
![Lerilla_206](https://user-images.githubusercontent.com/16804997/63193202-1e126100-c06d-11e9-9b1d-4292d1710f3f.jpg)

We took the guild Quest last weekend and tried to finish it totday in two zones. .t2 emp and t3 elves we typed .guildinvolve but it isnt finisehd yet

**Comment by sioding** [comment]
I start with the database department - but maybe its more than a config problem.

**Comment by Lerilla** [comment]
![Lerilla_208](https://user-images.githubusercontent.com/16804997/63195574-48ffb380-c073-11e9-994f-5e6198099288.jpg)
![Lerilla_209](https://user-images.githubusercontent.com/16804997/63195575-48ffb380-c073-11e9-91e9-50fc19b34be2.jpg)
 and again

**Comment by Kabucoror** [comment]
this seems something for @Natherul

**Comment by Natherul** [comment]
found the issue and it should be fixed in the next patch

**Comment by sioding** [comment]
fixed with patch from 24.08.2019
