### ISSUE TITLE
running-speed dot reduce errors

### ISSUE THREAD

**Issue by noobwarrior** [WarEmu/WarBugs#14780]
since few days enters the error with me on if i suffer a reduce run dot he does not run out 
I have to restart my game every time..

![Relife_203](https://user-images.githubusercontent.com/53536809/63149816-79106d80-c005-11e9-847f-5b3c7aaa58d2.jpg)

here you can see after the dot

![Relife_204](https://user-images.githubusercontent.com/53536809/63149843-89284d00-c005-11e9-9616-6ede5fe8e42c.jpg)
and here after the restart

**Comment by sioding** [comment]
Any chance to see the name of the dot?

**Comment by noobwarrior** [comment]
Unfortunately, no
also does not know from whom it is caused

**Comment by noobwarrior** [comment]
can only guess..sry

**Comment by grunbag** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 17.08.2019
