### ISSUE TITLE
Worn Mail Spaulders cannot be equipped

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14785]
Expected behavior and actual behavior:
It's medium armor, but it doesn't say I shouldn't be able to equip it. When I try to use it, I get the "You could not move Worn Mail Spaulders" message.
I even get the prompt about it being bound to me.

Steps to reproduce the problem:
It's a drop at the area the screenshot was taken.

Testing Screenshots/Videos/Evidences (always needed):
![Kollurion_000](https://user-images.githubusercontent.com/53320075/63207705-2dab9d00-c0a1-11e9-8160-ae895d27622c.jpg)
![Kollurion_001](https://user-images.githubusercontent.com/53320075/63207711-3603d800-c0a1-11e9-9e8c-a2b5243337db.jpg)

**Comment by Kabucoror** [comment]
There is no problem because even if you say yes you can't equip it and thus it won't be bound to you. The warning always appears before the check if you can equip it happens.

**Comment by Austherus** [comment]
Understood. The issue was with the fact that the item doesn't say who should wear it, making it confusing for players the first time.
