### ISSUE TITLE
NPCs at bridge to Snotwood

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14787]
Expected behavior and actual behavior:
They are not interactable. They don't attack, they can't be attacked nor clicked.

Testing Screenshots/Videos/Evidences (always needed):
![Kollurion_006](https://user-images.githubusercontent.com/53320075/63207778-6e57e600-c0a2-11e9-94a2-6e37465dab4f.jpg)
![Kollurion_007](https://user-images.githubusercontent.com/53320075/63207779-6ef07c80-c0a2-11e9-9483-b0d87380234a.jpg)
![Kollurion_008](https://user-images.githubusercontent.com/53320075/63207780-6ef07c80-c0a2-11e9-8bfe-b74094126d65.jpg)
![Kollurion_009](https://user-images.githubusercontent.com/53320075/63207781-6ef07c80-c0a2-11e9-8b4d-9e3d14914de6.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 24.08.2019
