### ISSUE TITLE
Ironclaw Camp Public Quest - Stage I

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14786]
Expected behavior and actual behavior:
Enemies are not granting influence. I found it reported and fixed, but the issue persists.

Testing Screenshots/Videos/Evidences (always needed):
![Kollurion_002](https://user-images.githubusercontent.com/53320075/63207750-dbb74700-c0a1-11e9-91ff-7d2e1493bb6d.jpg)

**Comment by Kabucoror** [comment]
It works fine for me.

**Comment by Lheana** [comment]
The issue is just that the chapter you see when you are inside the PQ is not the one of the PQ. But the PQ provides influence for the correct chapter.
