### ISSUE TITLE
Gunbad Bolster Not Functioning

### ISSUE THREAD

**Issue by Wraythbw** [WarEmu/WarBugs#14781]
Went in to attempt Gunbad on Tuesday 8/13/2019. The Bolster was boosting me to 40. Bolster was only working partially. Targets that were level 40 were able to be hit without a problem. Any NPCs lvl41 were about 50% chance whether they would be block or not. LVL42 NPC's were 100% block. Still an active issue with Bolster that needs looked into. Will try to get SS's on my next attempt.

**Comment by grunbag** [comment]
Which mob is 42?

**Comment by sioding** [comment]
No answer for 15 days. Close
