### ISSUE TITLE
The Phoenix Eye Public Quest - Stage I

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14784]
Expected behavior and actual behavior:
You can just click repeatedly on the same banner and the stage will be completed in a sec, it should count only one click for each banner.

Testing Screenshots/Videos/Evidences (always needed):
![Austherus_006](https://user-images.githubusercontent.com/53320075/63207671-95151d00-c0a0-11e9-9b5e-6ba3e76de2da.jpg)

**Comment by Kabucoror** [comment]
Some chars have this wierd bug. There is nothing we can do about it.
