### ISSUE TITLE
Talabec Dam - No Respawn option

### ISSUE THREAD

**Issue by Rivenspeak** [WarEmu/WarBugs#14796]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**

Expected Behavior:
After dying, you should be given the prompt and button to respawn.

Actual Behavior:
You just lay there dead with no respawn option.

**Steps to reproduce the problem:**

Can't reproduce since I can't respawn, but multiple people have this issue.  Most near the bomb drop site, so it may have something to do with getting killed by the bomb.  Bomb exploding caused my death -- I could respawn fine before.

**Testing Screenshots/Videos/Evidences (always needed):**

![Drysteer_000](https://user-images.githubusercontent.com/45123644/63224074-1b0e9200-c18d-11e9-9eee-8f1d39a7f9c2.jpg)

**Comment by Rivenspeak** [comment]
Update:

Confirmed it's still happening.  Not necessarily by bomb drop-off site.

You get kicked from scenario and also get quitters debuff.

![Drysteer_001](https://user-images.githubusercontent.com/45123644/63224274-dfc19280-c18f-11e9-9ee0-9de664d86c6f.jpg)

**Comment by Natherul** [comment]
related to https://github.com/WarEmu/WarBugs/issues/14797 should be fixed now
