### ISSUE TITLE
shaman* Invader 7 set bonus

### ISSUE THREAD

**Issue by noobwarrior** [WarEmu/WarBugs#14791]
![Relife_206](https://user-images.githubusercontent.com/53536809/63212023-709c5d80-c0ff-11e9-81a2-1dff218da31c.jpg)

that's how my stats look like before I do something

![Relife_207](https://user-images.githubusercontent.com/53536809/63212031-7f831000-c0ff-11e9-90d4-6c8b3b7d3d47.jpg)

it works every time even if I use the animal I have a 100% chance

**Comment by noobwarrior** [comment]
I wanted to say that it is a 100% chance and not 10%

**Comment by noobwarrior** [comment]
I would not be surprised if it is the same with the other class
and they do not say anything because the error is op

**Comment by Lheana** [comment]
Indeed it was set to 100%, thanks for the report. I fixed it on dev and on live just now.
