### ISSUE TITLE
Abilities suddenly not firing in SC anymore

### ISSUE THREAD

**Issue by Tyramissoux** [WarEmu/WarBugs#14798]
**Steps to reproduce the problem:**
Good question. No idea.
Can't exactly tell when it started. Maybe after a death. 
Tried reloading UI multiple times.
Tried to die and get surrected.
Tried to die and just respawn. 
Nothing worked in SC itself. 
Had to relog to be able to use abilities again.

**Testing Screenshots/Videos/Evidences (always needed):**
https://www.youtube.com/watch?v=-jD5ZZDw-_U&feature=youtu.be

**Comment by Natherul** [comment]
probably related to https://github.com/WarEmu/WarBugs/issues/14797 as game gets stuck in a loop
