### ISSUE TITLE
Gork´II fix it bug

### ISSUE THREAD

**Issue by noobwarrior** [WarEmu/WarBugs#14794]
as you see here becomes to me promised
![Relife_208](https://user-images.githubusercontent.com/53536809/63221315-94ab7d80-c197-11e9-855e-417471ce1e4a.jpg)
 the truth is the dot heal stops just 5 seconds but look yourself
![Relife_211](https://user-images.githubusercontent.com/53536809/63221333-e0f6bd80-c197-11e9-99af-376a73ecec91.jpg)
would be nice if I could get the 3k

**Comment by grunbag** [comment]
The duration seems to be shortened for faster tick so you gain less heal over time. I guess it need to be 10 sec again to gives 3000 health but I have to check client

**Comment by noobwarrior** [comment]
not know myself for that matter but the payers speak for themselves..it is not 3k.. sry for my bad english

**Comment by noobwarrior** [comment]
then would mean that would tick with 600 ..and as you can see .. only 109

**Comment by xaraxdestr** [comment]
yes it only last for 5 sec instead of 10sec as tooltip mentioned. also the 5 ticks together only heal 1/5 of the total value mentioned
3k also seems to be too high comparing to other heals

**Comment by grunbag** [comment]
Yes tooltip seems bugged, 3000 is higher than healing 13pts hot ability

**Comment by noobwarrior** [comment]
So it's just a display error..
and I have been looking forward...damn.. xD

**Comment by noobwarrior** [comment]
now sometimes serious that makes the cure ineffective at such stats at such stats 500 immediately and 109 ea.sec
my opinion..

**Comment by grunbag** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 24.08.2019
