### ISSUE TITLE
IndexOutOfRangeException was thrown from CheckDomination 

### ISSUE THREAD

**Issue by Tyramissoux** [WarEmu/WarBugs#14797]
Multiple pets had this exception thrown in Talabec Dam scenario (see screen - left it uncropped for timestamp in Waaaghbar). 
Killcount for SC was also off (other screenshot). Didn't count properly. Damage and heal counting seemed fine, though.

![Bikinibabe_035](https://user-images.githubusercontent.com/13544944/63224268-0b5d7080-c1c2-11e9-99b6-6118f1a92088.jpg)
![image](https://user-images.githubusercontent.com/13544944/63224271-1fa16d80-c1c2-11e9-895b-024b69d1f5b7.png)

**Comment by Natherul** [comment]
fixing this now, hotfix dropping in 25 mins
