### ISSUE TITLE
LOST GENESIS FRAGMENT

### ISSUE THREAD

**Issue by Elciel123** [WarEmu/WarBugs#14795]
I won blue bag in Reikland 17/8/19.

Opened bag 18/8/19 - Genesis fragment inside, yay!

Tried to extract item with genesis merchant open, item + bag vanished. NOT destroyed. 

ACCOUNT:  AREANDA
email of account: sorcbeast808@gmail.com

Toon who won the fragment , the Witch Hunter

**Comment by Lheana** [comment]
Maybe it sold it because you had both bag and vendor opened?

**Comment by sioding** [comment]
No answer for 10 days: Close
