### ISSUE TITLE
ORVR Bue Loot Bag won't open

### ISSUE THREAD

**Issue by Ninhi** [WarEmu/WarBugs#14809]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

This issue was open in the past, but was closed. I have a Blue Loot Bag which will not open. It has been in my inventory for about a week.

**Expected behavior and actual behavior:**

I am not able to duplicate the issue. Other loot bags both RVR and PQ's are opening.
**Steps to reproduce the problem:**

![image](https://user-images.githubusercontent.com/52477822/63306909-7db17c00-c2ba-11e9-801c-c865f844df51.png)

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by sioding** [comment]
You can destroy this bag - when we don't get the onformation when this bag handed out to you ( exactly which lock / pq / whatever ) we can not help. Especially when you are not able to duplicate the issue on your own.
