### ISSUE TITLE
[Quest] Grand Deceptions

### ISSUE THREAD

**Issue by lilimx** [WarEmu/WarBugs#14802]
Hey,

tried to take in the quest "Grand Deceptions" to Livia Aselta at the Bastion Stairs entrance room, but she doesn't react to the quest. She only gives me the "Power Within" - Bastion Stairs Quest.
Even abandon and retake the quest doesn't work.

Start of the Quest (Praag chapter 17):
![geber](https://user-images.githubusercontent.com/23266079/63252767-b7f62b80-c270-11e9-9cf0-8745cb15d89a.png)

Livia Aselta reaction:
![quest](https://user-images.githubusercontent.com/23266079/63252792-c80e0b00-c270-11e9-84d9-c240af95e395.png)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 14.09.2019
