### ISSUE TITLE
T4 Lair Bosses  Need / Greed / pass options are not working .  

### ISSUE THREAD

**Issue by Kagurra** [WarEmu/WarBugs#14805]
Even if a party member selects Greed / pass / or need  it doesn't work all the time . It happens often enough where someone gets both items / or the wrong class gets and item that was greed/ pass by that player and and needed by another / the correct Class  .

**Comment by sioding** [comment]
No screenshots - no information when / what / how... sorry but how should we help with missing informations. Please add them.

**Comment by sioding** [comment]
No answer since 10 days. Close
