### ISSUE TITLE
running-speed dot reduce errors (is back)

### ISSUE THREAD

**Issue by noobwarrior** [WarEmu/WarBugs#14801]
![Relife_218](https://user-images.githubusercontent.com/53536809/63228084-b421c500-c1ee-11e9-9cc0-4756a245b93d.jpg)
is back the mistake

**Comment by noobwarrior** [comment]
in this fight an RP, WP, AM and WL was involved
exactly who it was I can not say..sry

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by noobwarrior** [comment]
now I know it the mistake is made by the RP caused..!! here's a picture
![Relife_235](https://user-images.githubusercontent.com/53536809/63610707-5b7d6e00-c5da-11e9-8e95-016fec5b332d.jpg)
The name of the player was Miniwage's

**Comment by sioding** [comment]
fixed with patch from 24.08.2019
