### ISSUE TITLE
Liniment of Unfettered Zeal Not Giving Accurate Healing Power

### ISSUE THREAD

**Issue by keunglh** [WarEmu/WarBugs#14807]
**Expected behavior and actual behavior:**
The liniment tooltip states that it should increase healing power by 50, however, looking at the character sheet, it appears that it is only gaining a +10 HPS in Healing Power instead.

**Steps to reproduce the problem:**
Look at Healing Bonus before and after liniment use.

**Testing Screenshots/Videos/Evidences (always needed):**
![Liniment Healing Power](https://user-images.githubusercontent.com/14348489/63281719-e8d76000-c272-11e9-9350-78c5bdd7b63b.PNG)
![Liniment Healing Power 2](https://user-images.githubusercontent.com/14348489/63281718-e8d76000-c272-11e9-9072-e3f656f38731.PNG)
![Liniment Healing Power 3](https://user-images.githubusercontent.com/14348489/63281717-e8d76000-c272-11e9-9ef9-c7f51e0a3e8d.PNG)

**Comment by sioding** [comment]
All fine with it - so close
