### ISSUE TITLE
Engineer 5 Piece conqueror not stacking correctly

### ISSUE THREAD

**Issue by rameden** [WarEmu/WarBugs#14816]
**Expected behavior and actual behavior:**
The Engineer's 5 piece bonus for the Conqueror, marked, reads: "On Hit: 25% chance to reduce the target's initiative by 100 while increasing your ballistic skill by 100 for 10 seconds."  However if the player is using a ballistic skill potion the bonus only adds the difference on proc.

**Steps to reproduce the problem:**
- Be an Engineer
- Equip 5 piece conqueror set
- Use "Lasting Potion of Accuracy" Potion
- On training dummies get "marked" to proc
- Verify increase of only 20 ballistic skill from bonus

**Testing Screenshots/Videos/Evidences (always needed):**
Before Marked proc:
![Tinks_005](https://user-images.githubusercontent.com/1105847/63398219-e8d27f80-c39a-11e9-8ee0-067ffb0d1ee1.jpg)

After Marked proc:
![Tinks_006](https://user-images.githubusercontent.com/1105847/63398218-e8d27f80-c39a-11e9-8bb7-572ed2b07b48.jpg)

As you can see the increase from "Marked" was only 20 BS, not 100 BS.

**Comment by GK111** [comment]
> As you can see the increase from "Marked" was only 20 BS, not 100 BS.

working as intended
