### ISSUE TITLE
Hellblaster dmg too high?

### ISSUE THREAD

**Issue by xaraxdestr** [WarEmu/WarBugs#14815]
we just had a siege in KV and i normally i get hit by 1,5k from a hellblaster, this time i get hit by 3,2k and then 5 sec later again 3,6k

![Knochengit_007](https://user-images.githubusercontent.com/45398873/63385023-6ea4f980-c3a0-11e9-8028-5955fd4f4a52.jpg)

**Comment by Natherul** [comment]
should be addressed with the next patch

**Comment by sioding** [comment]
fixed with patch from 24.08.2019
