### ISSUE TITLE
Got stuck in a hole that is impposible to get out of at Butcher's Pass

### ISSUE THREAD

**Issue by Kagurra** [WarEmu/WarBugs#14811]
near the Battle objective on the ledge there is a small hole too difficult to see unless you fall in it that there is no possible way to get out of . One of your staff members got me out of it . the staff member's name was Gambero . The map coordinance are 37574 , 20651 .  The hole is on the ledge in between some very large rocks sticking out of the ledge .

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 06.10.2019
