### ISSUE TITLE
No rewards from Butcher Pass

### ISSUE THREAD

**Issue by IceandFire1985** [WarEmu/WarBugs#14827]
Im just finish Butcher Pass fort.
At the end i didnt get any renown or medals for it.
![No renown no medals](https://user-images.githubusercontent.com/19292844/63593890-4b9f6300-c5b5-11e9-8e57-fb4434f7390b.jpg)
![Bez tytułu](https://user-images.githubusercontent.com/19292844/63594693-6b378b00-c5b7-11e9-95ba-c3273d96d72a.jpg)

**Comment by sioding** [comment]
Thats not a bug - you didn't contributed enough. Next fort - next chance. Help defending/attacking the fort with capturing BOs etc.

**Comment by IceandFire1985** [comment]
Are u kidding me? I was in that fort from begining, play with wb on stage 2 and 3. And leave main door push with all order. And after this u tell me it was no bug and i didn't contributed enough?
