### ISSUE TITLE
Not able to pick the Raven Pendant trophy reward

### ISSUE THREAD

**Issue by Cl3arSky** [WarEmu/WarBugs#14825]
**Expected behavior and actual behavior:**
Clicking the trophy for the reward then pressing OK simply closes the window while the quest giver still has got the "quest complete" book above his head, not getting the reward. The rewards on the 1st row work but not on the last as seen in the pic.

**Steps to reproduce the problem:**
Finish the quest Show of Power from Madger The Soulreaper then try to pick the raven trophy from the second row

**Testing Screenshots/Videos/Evidences (always needed):**

![Clearsky_000](https://user-images.githubusercontent.com/53981934/63580073-47af1900-c594-11e9-8a4d-78759b8d27db.jpg)

**Comment by sioding** [comment]
Fixed with patch from 06.10.2019
