### ISSUE TITLE
AM*Cleasing light* to OP

### ISSUE THREAD

**Issue by noobwarrior** [WarEmu/WarBugs#14820]
if I think about it this is a mistake and belongs here es geht um die fehigkeit der AM
It allows to remove any dots and even corabilities I as a shaman can not do anything ..
everything I do is removed 1 sec .. do not think it is so intended the damage from the AM is ok but if i can not do anything except watch how i'm killed .. it's just the one skill that makes the AM so op ... removing any attacks or anything else..last word from me..
equal Rights we should also be able to remove dots from AM*or she must not remove from us.
sorry for my bad english..

**Comment by sioding** [comment]
Sorry - but the bugtracker is not the place to discuss balance things. Please use our balance board for these issues.
