### ISSUE TITLE
Chaos Ch 22 Easy PQ Fields of Reikland - unattackable peasants

### ISSUE THREAD

**Issue by pjz** [WarEmu/WarBugs#14824]
**Expected behavior and actual behavior:**
Reikland Peasants in the Fields of Reikland PQ agro on me, I should be able to attack them, but I can't initiate hostilities other than by getting close.  Even then, some of my abilities don't show as 'ready' against them; I mostly have to rely on AoE when fighting them, and I intermittently get a 'Target is not attackable' message (which is the same that I get when i try and throw a knife at them or something)

Fighting Reikland Patrol works just fine.

**Comment by sioding** [comment]
fixed with patch from 31.08.2019
