### ISSUE TITLE
Quest Bugs

### ISSUE THREAD

**Issue by Reekit** [WarEmu/WarBugs#14837]
Quests Destruction Side

The Wind of Change - Ellyrion Chapter 8 - Mephitic Dust doesn't spawn in your quest bags. (starts in inevitable city cathedral)

Those Who Serve - Saphery Chapter 13 - Horn doesn't spawn in bags. (starts in chapter 13)

The Vessel of Azorgaron - Cinderfall - The quest text is bugged Invalid GameObject - QuestID 20734. You go to the location (47113,62157) and kill the mob and the chest is unlootable. (starts in inevitable city cathedral)

Character name - Reekit on Destruction

**Comment by sioding** [comment]
10. One ticket per issue 

Only report one issue per ticket as multiple issues within one ticket is harder to track and harder to address.
