### ISSUE TITLE
Chaos ch20 NPC bug

### ISSUE THREAD

**Issue by Kelthrai** [WarEmu/WarBugs#14830]
Hello! Humanoid NPC's in Reikland Chaos ch20 currently when turned to 0 HP does not have the death animation but is suspended in the air as a typical scarecrow, idk if this is across all npc's after the reset but it is atleast affecting the empire ones in this area.

**Comment by sioding** [comment]
Please restart your game and he launcher - should be fixed with it. give a feedback if not please

**Comment by sioding** [comment]
no answer for 11 days: close
