### ISSUE TITLE
BW/Sorc Invader 7piece proc

### ISSUE THREAD

**Issue by BomblingTV** [WarEmu/WarBugs#14833]
**Expected behavior and actual behavior:**
Before I begin. I would like to underline this is a bugreport on an UNINTENTED bug that is turning out to be for the better and fixes Realm-imballance between Sorc & BW's ways of getting their 7piece invader proc. I hope I can make the case for this unintented useage to stay, and just a tooltip change on the actual sets will be the outcome.

7piece bonus reads: " 

> _All of your Path of **Immolation** abilities hae a 10% chance to increase you critical hit rate by 9% and critical damage by 12% for 9seconds"_

However, on Live(RoR) the proc occures on all ability useage and not just on Immolation spells.
This is unintented, but it also fixes the imballance between ways an AoE BW can proc his 7piece bonus compared to a Sorc who have a spamable AoE ability in their middlemastery tree with zero second cooldown. Ergo Sorc have a supperior way to obtaining this powerful proc simply because of Icespikes being a Calamity masterytree. 
I adressed this issue several months ago in feedback topic, but nothing was made of it (bottom post by Wonshot page1):

https://www.returnofreckoning.com/forum/viewtopic.php?f=15&t=30722

This is a case of an unintented bug, that I report with the hopes of you letting the actual bug stay in the game based of the realm-imballance reaspons adressed in that feedback post. Or make the proc a 10% chance on hit for all abilities to bring both the Sorc and BW on the same level without having one reign suprime. Or leave the bug as it is, and simply change how the tooltip reads:
"10% chance on use for all abilties"

**Testing Screenshots/Videos/Evidences (always needed):**
https://clips.twitch.tv/InspiringBeautifulHummingbirdRuleFive
(Flamebreath is a Conflag ability, ice spike is a Calamity based ability)

**Comment by wargrimnir** [comment]
This was fixed quite a while ago with a code update. The function to respect mastery trees wasn't quite implemented when the set was created.
