### ISSUE TITLE
swordmaster tactic bolstering enchantment

### ISSUE THREAD

**Issue by wosz** [WarEmu/WarBugs#1483]
tactic bolstering enchantment not getting boost from willpower or healing the correct value in tool tip

**Comment by Evildoor** [comment]
Uh, am i missing something? I always thought that this tactic has no willpower scaling, and the client tooltip (same with/without willpower jewelry) verifies it. The difference with tooltip exists though.

**Comment by wosz** [comment]
well alot of other class healing tactic and spells did/do like the dark elf tactic and all/most of the bg/ib healing scales with willpower just putting it out there just in cace

**Comment by wosz** [comment]
but yes i have 260 over ten sec i only get 4 tic of 46
