### ISSUE TITLE
order quest hall of the crimson shroud stage 3 cant destroy or interact with stone of the shyish

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#14845]
![Thorbolt_034](https://user-images.githubusercontent.com/16274785/63652449-74179080-c760-11e9-9176-14cb3fda2baa.jpg)
cant destroy or interact with the stone so you cant finish the quest

**Comment by sioding** [comment]
fixed with patch from 31.08.2019

**Comment by Paleolog77** [comment]
Another problem. I can kill the stone, but Vedric von Heilbroner it is impossible to attack
![2021-11-14_16-51-38](https://user-images.githubusercontent.com/23325288/141684218-a0f5c687-f5c9-4bcd-8ae5-40edf1cf2795.png)
.

**Comment by Lheana** [comment]
Don't hesitate to open a new ticket when the ticket has been closed because it was fixed.

**Comment by lilimx** [comment]
related dublicate to #19640
