### ISSUE TITLE
quest order side dominion of khaine DW stage 3 bug

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#14843]
You should killbloodfury hags but he doesn't count (screenshot see below) so you can't go on stage 4

![Thorbolt_062](https://user-images.githubusercontent.com/16274785/63652262-724ccd80-c75e-11e9-932c-4fde44059a7b.jpg)

**Comment by sioding** [comment]
fixed with patch from 31.08.2019
