### ISSUE TITLE
Destruction - Those Who Serve - Saphery Chapter 13

### ISSUE THREAD

**Issue by Reekit** [WarEmu/WarBugs#14847]
I found the horn and blew it at the empire camp. The NPC spawns but you can't interact with him to finish.

https://imgur.com/OJj4Gsr

**Comment by Lheana** [comment]
Increased the area around the NPC to talk to him and complete the objective.
You should still be able to complete the quest if you stand closer to the NPC.

**Comment by sioding** [comment]
fixed with patch from 31.08.2019
