### ISSUE TITLE
Quest- An Ounce of Prevention  cant examine goblin fetish in the quest inventory

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#14848]
so cant complete the quest
![Thorbolt_043](https://user-images.githubusercontent.com/16274785/63652670-18023b80-c763-11e9-82ce-24bb2dd22f08.jpg)

**Comment by Lheana** [comment]
This is because you are meant to use the Chimeral Charm on an Orc before being able to examine the fetish, as it is the 'quest finisher'.
