### ISSUE TITLE
Cult of Drakk PQ: Cinderfall - Dwarf Chapter 18 stage 5 you can kill merona but doesn't count 0/1

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#14846]
![Thorbolt_005](https://user-images.githubusercontent.com/16274785/63652517-572f8d00-c761-11e9-9179-7bc8912fe311.jpg)

**Comment by sioding** [comment]
Hm i see "you have slain Merona..." on your screenshot. Whats the real problem?

**Comment by thorbolt80** [comment]
yes we slain in but doesn't count. Merona 0/1 look at the screen on the top right

**Comment by Lheana** [comment]
I think there was an issue with the NPC not being correctly targetable.
Nevertheless, note that you have to kill the NPC twice, as Merona comes back with her dragon when she is defeated.

**Comment by sioding** [comment]
fixed with patch from 31.08.2019
