### ISSUE TITLE
Domination Starting and Breaking

### ISSUE THREAD

**Issue by Manatikik** [WarEmu/WarBugs#14853]
If you meet the kill requirements for domination it starts it and then immediately ends it if you have less than the 50% more points and continues to start and stop Domination.

![domination](https://user-images.githubusercontent.com/19319894/63670694-b52c9680-c79a-11e9-8262-6e9419d320c7.png)

**Comment by Natherul** [comment]
going to close this ticket with whats happening on next patch. If it in the future becomes a problem again then please post back here and it will be reopened.
