### ISSUE TITLE
Burnbeard's Oath Public Quest - Stage I

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14851]
Expected behavior and actual behavior:
These NPCs aren't reacting to each other.

Testing Screenshots/Videos/Evidences (always needed):
![Kollurion_007](https://user-images.githubusercontent.com/53320075/63656269-07a08f80-c768-11e9-8591-f6415b0bd0fa.jpg)
![Kollurion_008](https://user-images.githubusercontent.com/53320075/63656270-07a08f80-c768-11e9-9cfb-83d2c622ae1d.jpg)

**Comment by sioding** [comment]
fixed with patch from 31.08.2019
