### ISSUE TITLE
Burnbeard's Oath Public Quest - Stage II

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14852]
Expected behavior and actual behavior:
Impossible to complete stage. Can't attack objectives; interacting with them brings up their "destroyed" animation but doesn't count for the PQ.

Testing Screenshots/Videos/Evidences (always needed):
![Kollurion_009](https://user-images.githubusercontent.com/53320075/63656299-77af1580-c768-11e9-82a2-62370b50df9d.jpg)
![Kollurion_010](https://user-images.githubusercontent.com/53320075/63656300-77af1580-c768-11e9-9765-11c26ae5d16e.jpg)
![Kollurion_011](https://user-images.githubusercontent.com/53320075/63656301-7847ac00-c768-11e9-969f-377a9ce7753e.jpg)
![Kollurion_012](https://user-images.githubusercontent.com/53320075/63656302-7847ac00-c768-11e9-9527-e9a2f9bc02bb.jpg)

**Comment by sioding** [comment]
fixed with patch from 31.08.2019
