### ISSUE TITLE
Skill Fleet-Footed

### ISSUE THREAD

**Issue by Heyho18** [WarEmu/WarBugs#1485]
The Witch Elf Skill " Fleet-Footed " doesn't work as intended. It won't remove snare or roots.

**Comment by Evildoor** [comment]
@ozarmidrashim 's comment in https://github.com/WarEmu/WarBugs/issues/1484 makes me think that this is an issue with root ability rather than root removal abilities, which he already made fix for: https://github.com/WarEmu/WarBugs/issues/1482.
