### ISSUE TITLE
SHAMAN Fury of da green fails to heal all targets

### ISSUE THREAD

**Issue by Iamwithstupid** [WarEmu/WarBugs#14857]
**Expected behavior and actual behavior:**
Fury of da green fails to heal  targets within 20 feet around target if target is yourself, no one except caster will never be healed.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Screensava_024](https://user-images.githubusercontent.com/36380568/63706067-376a9880-c837-11e9-9339-6fdd3583e285.jpg)
![Screensava_025](https://user-images.githubusercontent.com/36380568/63706173-6a149100-c837-11e9-9570-ef9b05edf282.jpg)

**Comment by Grumug** [comment]
Bump.Ability still not working after 1 year.

**Comment by lilimx** [comment]
Fixed with Patch 22/07/2021
