### ISSUE TITLE
Renown Weapons

### ISSUE THREAD

**Issue by Rizzla27** [WarEmu/WarBugs#14850]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.
I am wanting to obtain the Sentry's Sword of Anathema for my Chosen, however, to do so, I need to get the Sentry's Crusher of Tyranny, not only does it cost 750 conqueror emblems - but my Chosen can't even use a hammer ?. Is this right, that I have to get a weapon I can't use in order to get the Anathema sword?
![Korge_000](https://user-images.githubusercontent.com/54510976/63654818-573a8780-c777-11e9-996a-77362b7be2c6.jpg)

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kabucoror** [comment]
fixed with next patch
Note: The Sentry's Sword of Anathema was declared wrong and has been transformed into Titan's Sword of Anathema as the def version doesn't exist, even for the previous tier.

**Comment by sioding** [comment]
fixed with patch from 14.09.2019
