### ISSUE TITLE
[Zealot] Warp reality does the same damage with/without Harbringer of doom

### ISSUE THREAD

**Issue by notre4ror** [WarEmu/WarBugs#14856]
**Expected behavior and actual behavior:**
Expected a gain on dps when switching to "dps", but Warp reality is doing the same damage with or without Harbinger toggled

**Steps to reproduce the problem:**
Cast "Warp reality" on a dummy, toggle harbringer and cast another "Warp reality" to the next dummy, watch the same base damage ticking on both.

**Comment by sioding** [comment]
And your testing screenshots?

**Comment by sioding** [comment]
No answer for 11 days: Close
