### ISSUE TITLE
Defend Wrath's Resolve not showing?

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14867]
Expected behavior and actual behavior:
The quest isn't showing up on the Lord to be picked, and I don't have it either.

Testing Screenshots/Videos/Evidences (always needed):
![Lokhairos_002](https://user-images.githubusercontent.com/53320075/64001078-715cc880-cadd-11e9-84fc-f0e24fdf8a96.jpg)
![Lokhairos_003](https://user-images.githubusercontent.com/53320075/64001079-71f55f00-cadd-11e9-8883-ba52ac1918cb.jpg)

**Comment by sioding** [comment]
My best guess: You have too many open quests. We are facing weird situations with quests if you have ALOT open. Please close the ones you don't follow anymore and try it again.

**Comment by Austherus** [comment]
I deleted a few quests, including some of the "Defend" ones but still couldn't see it. All other quests in the game are visible.

**Comment by Austherus** [comment]
Tried again a few times, no luck. Deleting quests didn't make it appear.

**Comment by sioding** [comment]
Fixed with patch from 28.09.2019
