### ISSUE TITLE
sentry's stilletto bug

### ISSUE THREAD

**Issue by sournoise** [WarEmu/WarBugs#14861]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by sournoise** [comment]
don t reduce armor penetration

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format.

**Comment by sioding** [comment]
no answer for 10 days: Close
