### ISSUE TITLE
Shady Dealing Quest in Inevitable City

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14864]
Expected behavior and actual behavior:
This quest is given by the wrong NPC. You can see it's Skub the goblin talking on the text, and the objectives also make it very clear it's not the Chaos guy. Not sure if the quest is supposed to be hidden, but it doesn't appear over the head of any NPC either, I clicked on Panevg out of curiosity and got it started.

Testing Screenshots/Videos/Evidences (always needed):
![Lokhairos_004](https://user-images.githubusercontent.com/53320075/63832495-4a6c8e00-c947-11e9-9131-c326af0ac1a0.jpg)
![Lokhairos_005](https://user-images.githubusercontent.com/53320075/63832496-4a6c8e00-c947-11e9-8b6d-b65a48c4d4fe.jpg)

**Comment by lilimx** [comment]
fixed with patch 21/07/2022
