### ISSUE TITLE
Renown Rewards from Zone Locks, Forts.

### ISSUE THREAD

**Issue by bashmasta** [WarEmu/WarBugs#14862]
There are now Renown EXP rewards after a zone locks in RvR or after a Fort is finished. 
Double checked with guildmates, they also didn't get any renown from the mentioned activities. 
Bag rolls and a rewards are working as intended.

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format.

**Comment by bashmasta** [comment]
I am closing the issue, since it isn't happening anymore. After server restart, everything is back to normal. In any future issues, I will to gather as much evidence as I can.
