### ISSUE TITLE
Khaine Embrance SC invasion

### ISSUE THREAD

**Issue by Nekkbraka** [WarEmu/WarBugs#14860]
Helloo, is this allowed to be made in Khaine Embrance?  Isnt it a bug or something ? 
https://cdn.discordapp.com/attachments/615892179352682518/615892594848956416/Nekkbraka_219.jpg

**Comment by sioding** [comment]
Don't get whats the problem - and the screen doesn't help either. Can you please describe the problem in more words?

**Comment by sioding** [comment]
Maybe one of the DB department can check if there are enough guards protecting the spawn area.

**Comment by Lheana** [comment]
I see nothing that needs to be changed here.
