### ISSUE TITLE
the way to explode behind the walls of the keeps in*Saphery*

### ISSUE THREAD

**Issue by noobwarrior** [WarEmu/WarBugs#14865]
![Relife_237](https://user-images.githubusercontent.com/53536809/63854391-5f740c00-c99d-11e9-9a1b-7770089cc657.jpg)
Here one Begins..Something difficult is not something for Beginners
![Relife_238](https://user-images.githubusercontent.com/53536809/63854536-a4983e00-c99d-11e9-839a-46ae3bc03bed.jpg)
when you're on top just keep running left along the invisible wall
![Relife_239](https://user-images.githubusercontent.com/53536809/63854624-d90bfa00-c99d-11e9-944a-39621c6687c0.jpg)
and you're in there

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 06.10.2019
