### ISSUE TITLE
[Quest] BO-Scouting quests in elf t2 autocomplet

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#14873]
The quests to scout the four BOs in Elf T2 are completed on accepting them. 

![Zkyr_010](https://user-images.githubusercontent.com/40274248/64073445-440b4880-cc9e-11e9-9211-8382d3734db9.jpg)

(It seems it was mentioned some time ago, but was closed due to no response #4438)

**Comment by Lheana** [comment]
Duplicate of #6872
