### ISSUE TITLE
Guild Mount quest (rvr)

### ISSUE THREAD

**Issue by Rockalypse** [WarEmu/WarBugs#14878]
Today we were as guild group in TM during lock, group was part of warband, for some reason quest have not triggered.
Edit: We were in zone from start, ran boxes and was fighting during whole keep siege (in regards to contribution made).

![Morseth_007](https://user-images.githubusercontent.com/42712833/64295633-46a9be80-cf7a-11e9-9ec3-769c016049ff.jpg)
![Morseth_004](https://user-images.githubusercontent.com/42712833/64295644-51645380-cf7a-11e9-9231-2e8e3305d420.jpg)

**Comment by Rockalypse** [comment]
![Morseth_006](https://user-images.githubusercontent.com/42712833/64295685-7658c680-cf7a-11e9-959c-4874803ab8b5.jpg)
(lock itself)

**Comment by Natherul** [comment]
I have stated this many times now, guild contribution is not contribution as killing, its the paying money to get buff in lake, thats called guild contribution. That or keep claiming is whats needed.
