### ISSUE TITLE
Getting teleported to Inevitable City while Fort Siege

### ISSUE THREAD

**Issue by herkboy** [WarEmu/WarBugs#14871]
I want to report teleporting from FORT defence event to Inevitable City while doing nothing to cause it. The past Forts are like this. I cant play the event anymore. Can you investigate into it?
Character name : Mrsparkles Black Orc.
Last time it happened around 14:38 31/8/19 (greek time zone), another time happened yesterday on my previous Fort attempt and after that was like 3-4 days ago on the pre-previous attempt. An these are not the only times it happened. It feels it is like this the past period 80% of the time.
I cant post any picture or proof from it since i just get teleported to IC and the game just 'resets'. Not trying to claim anything, i just want to play fort, and i am really mentally demoralized with this issue.
The only way to make this post believable is to ask for ppl to vouch that i am saying the truth since i am playing with friends that witness this issue.

Please look into this. Thank you for your time.

**Comment by bashmasta** [comment]
I can confirm this happened to him in at least 4 consecutive forts.

**Comment by Carthage123** [comment]
Can also confirm these occurrences in all 4 of the last attempts we have tried to play fort at the same time.

**Comment by mousias** [comment]
Confirm this as well, and he was not afk.

**Comment by Lutzgaroth** [comment]
Indeed, it happens quite often, a very annoying issue. 
I wonder if it is connected to players spamming the portal to snatch a spot.

**Comment by Austherus** [comment]
Do you have the habit of setting yourself to AFK manually? The same thing happened to me today and it was caused by having AFK turned on.
The game doesn't turn it off when you move if it was set manually, so once Fort begins it kicks you out. Trying to get in again kicks you instantly.

**Comment by herkboy** [comment]
no, /afk is not a case. not using it at all. i am getting cicked after 5 - 8 mins so this is not the case

**Comment by herkboy** [comment]
btw i managed to play 1 fort yesterday so it is something rng triggering it. the problem is that if it is a bug or something it happens really often to me. like REALLY often compaired to other people i asked if 
 they have the same issue. all that seem to have the same issue they get kicked once per 7-10 forts though i get it like 7-8 per 10 forts the past two weeks

**Comment by sioding** [comment]
I am really not sure how this can be haunted down nor how it ever can be reproduced. If this would be an error which hits a lot of ppl we had a better chance but this one seems to be a problem on your side.
Did you ever tried to use a VPN to play?

**Comment by Natherul** [comment]
getting teleported out is not done at all with forts anymore as the test is active.

Before a teleport was only issues from the fort if you were triggered afk or you loaded into the zone as your last location.

If this issue persist please open a new ticket and fill in as much information as you can.
