### ISSUE TITLE
Lasting Scorching Blast Potion can be applied after death

### ISSUE THREAD

**Issue by Tyramissoux** [WarEmu/WarBugs#14876]
Discovered that the aoe dmg potion (Lasting Scorching Blast Potion) is applied after death. 
Was wondering what triggered to get back in combat after lying dead on the ground for over a minute and saw a new debuff. Didn't look at the combat log, though. 
Needless to say, if you're an elven carpet, you shouldn't get affected by any types of debuffs anymore.

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/13544944/64203583-10920f00-ce94-11e9-8c00-7aaddf07b8ab.png)

**Comment by Natherul** [comment]
Should have been fixed with the patch from yesterday
