### ISSUE TITLE
[Quest] Devoted from Caravella Betz not repeatable on some characters

### ISSUE THREAD

**Issue by CornerbackAC** [WarEmu/WarBugs#14874]
**Expected behavior and actual behavior:**
The Quest "Devoted" from "Caravella Betz" in Empire Chapter 7 is not repeatable anymore on some chars.
Expected: Quest is repeatable on all characters, **as it was some time ago (didnt play for a while, and on those 2 chars it simply wasn't available anymore, while on the 3rd it still was)**
Actual: Quest is only repeatable on one of my three characters

**Steps to reproduce the problem:**
No idea. Just stopped being repeatable on 2 of my 3 chars.

Char where it is not repeatable:
![g1](https://user-images.githubusercontent.com/11341460/64074220-e3353d80-cca8-11e9-8ee2-4509f92cfa24.jpg)

Char where it is repeatable:
![s1](https://user-images.githubusercontent.com/11341460/64074222-e9c3b500-cca8-11e9-8734-91b2c91766ad.jpg)
![s2](https://user-images.githubusercontent.com/11341460/64074224-e9c3b500-cca8-11e9-8f5e-d3cf45ae2e0a.jpg)
![s3](https://user-images.githubusercontent.com/11341460/64074225-e9c3b500-cca8-11e9-9075-28adac76baf0.jpg)

**Comment by Kabucoror** [comment]
It is still repeatable, maybe on some point it wasn't for a short time. If this happened and you completed the quest you can't repeat them anymore on those chars.
