### ISSUE TITLE
Cannot play 10sec return windows

### ISSUE THREAD

**Issue by Inconnuee** [WarEmu/WarBugs#14877]
I just reinstalled the game with all the steps i did before to play but i take a windows return after 10sec playing 
Isaw some posts on it but no issues i know the game is not the stablest game we all saw 
But may something happened with the last patch cause i can't play since 

config 

Intel(R) Core(TM) i7-2700K CPU @ 3,50GHZ
16 Go RAM
Double SSD
Geforce GTX 650

All works well

**Comment by sioding** [comment]
This bugtracker is only for ingame problems. So sorry you are wrong here... buuut this is a well known issue which is more than once documented on the forum.
