### ISSUE TITLE
Engineer / magus pet  is moving 

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#14889]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**

engineer and magus pet are not movable and they can be teleported to the caster by using the insta teleport ability 
just now after the server restart/patch i can see the pet is moving and chasing enemy while the engineer is behind shooting his flame pet is chasing me into the warcamp 

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by MaxHayman** [comment]
Which Zone are you in?

**Comment by Tazo83** [comment]
![image](https://user-images.githubusercontent.com/42385505/64475315-dc676880-d189-11e9-9ccf-e572ff0b3974.png)

![image](https://user-images.githubusercontent.com/42385505/64475320-e4bfa380-d189-11e9-8d8f-e159ca86f604.png)


![image](https://user-images.githubusercontent.com/42385505/64475322-ef7a3880-d189-11e9-9f19-22cf6b3015a3.png)

**Comment by Tazo83** [comment]
nordland  now fighting this lol

**Comment by MaxHayman** [comment]
Would you be able to check another region?

**Comment by Tazo83** [comment]
if u are in game u can teleport to me in nordland and see this is happening now we are at the warcamp and this pet is diving us 

i will check different zone but this is happening now i can film it :D

**Comment by Tazo83** [comment]
![image](https://user-images.githubusercontent.com/42385505/64475354-93fc7a80-d18a-11e9-9155-b0ad8412b88f.png)

![image](https://user-images.githubusercontent.com/42385505/64475358-9959c500-d18a-11e9-9a26-7cdf1c4afc16.png)


![image](https://user-images.githubusercontent.com/42385505/64475361-a4acf080-d18a-11e9-81d0-3fad2c3d880a.png)

i dunno what is causing the issue but i saw magus blue horor pet acting the same maybe because of the  Pathing patch 

[General]

- Pathfinding for NPCs/Pets/etc is now enabled in Nordland and Norsca only. We expect there to be some some effects on classes balance, specifically those with pets. Before we generate navigation meshes for other zones we would encourage people to test and check out the Pathfinding Info/Feedback thread HERE.
