### ISSUE TITLE
Quest: A sticky situation in Nordland 

### ISSUE THREAD

**Issue by eisenhans** [WarEmu/WarBugs#14881]
Quest steps don't continue correctly. You get the quest from Lena Scherer at WC, but when you click on the cocoon at webworks that has her father inside, you cannot continue normally. On live, you clicked the cocoon, freed the father, then went back to Lena to get your reward. In ROR, you click the cocoon, have to ride back to Lena, who now has the dialogue the cocoon should have given you, then go back to the cocoon AGAIN, click it again, can now free the father as you were supposed to do, then go back to Lena for the reward.

**Comment by Lheana** [comment]
This should be fixed with patch of 22/02/2020.
