### ISSUE TITLE
Beastlord book

### ISSUE THREAD

**Issue by IceandFire1985** [WarEmu/WarBugs#14888]
Hello,
After this patch, beastlord book is broken, i cant use it ( its equip on me )

Regards 
![Bez tytułu](https://user-images.githubusercontent.com/19292844/64474634-d5375f00-d177-11e9-8886-0777aabddee6.jpg)

**Comment by Natherul** [comment]
I need mroe information, the change does send a message. I just tested the book on my BG and it works fine

**Comment by IceandFire1985** [comment]
As i know problem is on some classes, some ppl can use it some cant

**Comment by IceandFire1985** [comment]
i cant use on my slayer, friend cant use on SM, another can use on WP

**Comment by Natherul** [comment]
issue is because there is 2 slots for pockets, if you move it to the other slot its working. A fix is pending

**Comment by IceandFire1985** [comment]
ok, thx for solve

**Comment by sioding** [comment]
fixed with patch from 14.09.2019
