### ISSUE TITLE
Gametime error message during dungeon

### ISSUE THREAD

**Issue by Grendel1892** [WarEmu/WarBugs#14885]
During BS Dungeon I got the following message " Account time will expire in 2049, you have chosen the account time playable model" then I crashed from game.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Grendel1892** [comment]
trying to link screenshot..

**Comment by Grendel1892** [comment]
https://i.imgur.com/rXJSVIH.jpg[/img

**Comment by MaxHayman** [comment]
Looking at where this message comes from it appears to be a malformed payload when we were doing some tests.

Closing for now.
