### ISSUE TITLE
don't possible log my ib and delog

### ISSUE THREAD

**Issue by Saintpastissier** [WarEmu/WarBugs#14884]
Hello i have a little bug after a tp at Black FirePass my computer have crash the game and  my ib is logged on the server but it's not possibleplay with this. (not deconnect on server)
![screenshot_029](https://user-images.githubusercontent.com/42912867/64338052-fe71b700-cfe0-11e9-90f0-6bbfea577794.jpg)
![Barakabar_010](https://user-images.githubusercontent.com/42912867/64338053-fe71b700-cfe0-11e9-8c3b-4277a025599c.jpg)

and it's possible for me connect other perso but don't release my main or disconnect

**Comment by Lheana** [comment]
Type /stuck twice in a row during the load when you try to connect with your IB.

**Comment by Saintpastissier** [comment]
ok si sa fonctionne pas car je n'ai pas d'ecran de chargement?

**Comment by Lheana** [comment]
Contacte un GM

**Comment by Saintpastissier** [comment]
deja essayer mais il n'y en a pas de connecter depuis hier soir

**Comment by Lheana** [comment]
Faut être patient et attendre qu'il y en ait un alors. Par contre le Bugtracker n'est pas fait pour discuter de ce genre de choses, donc si tu as d'autres questions, c'est soit sur discord soit sur le forum.

**Comment by Saintpastissier** [comment]
je pensais que c'etait un bug desole

**Comment by sioding** [comment]
You should be able to login again.

**Comment by Saintpastissier** [comment]
Thx For you're help :) .
