### ISSUE TITLE
Starting abilities appear on the first action bar after relog/zone change/etc

### ISSUE THREAD

**Issue by Rilos** [WarEmu/WarBugs#1488]
I play a WP and suffer black screens occasionally  from alt tabbing. When I load the game up again, my hotbar is messed up.  It usually happens with my path of wrath abilities and my career hot.

The skills that are messed up are, castigation, weight of guilt, smite, and healing hand.  These skills are replaced by a couple other abilities on the hotbar.

_edit_ also, my tactic likes to reset itself to a blank tactic slot.

**Comment by Reggaewaldo** [comment]
@Rilos if you are frequently alt tabbing, might I suggest that you try to use fullscreen window mode. It will put less strain on the game client when Alt + Tab is used.

Apart from that this is a tad over my knowledge about the game client, but it should AFAIK save the settings into your character profile. Someone with a bit more knowledge will have to check up on this.

**Comment by Rilos** [comment]
I actually had this happen to me when I logged in regularly.  Everything on my normal hotbar that has to do with my Main spec and core abilities were replaces like the description I gave.

![borda_013](https://cloud.githubusercontent.com/assets/14109685/10047109/879a73ec-61da-11e5-8904-e47371f1ec79.jpg)
vs
![borda_014](https://cloud.githubusercontent.com/assets/14109685/10047114/8cab9136-61da-11e5-8403-7ff7b59b93e2.jpg)

**Comment by Evildoor** [comment]
Aha. From the look of the screens it seems that this is a known bug which puts your starting (given at lvl 1) skills (4 on WP here on 1-2-3-4 + Flee on 0) on your first panel. This bug occurred pretty often in the past, then in some patch most causes were fixed, but sometimes it returns, like we can see here. The workaround is to bind your preferred abilities to 1-2-3-4 and 0 with something - for example, Nerfed Buttons addon. Other workaround is not to use the first panel, only 2-5. Unfortunately, i can't help with tactics.
