### ISSUE TITLE
Salzenmund PQ - Stage I, Frightened Peasant

### ISSUE THREAD

**Issue by Austherus** [WarEmu/WarBugs#14880]
Frightened Peasant is an NPC type that cowers around the various corners of Salzenmund. He's not interactable at all, but if an AoE touches him, he'll attack and follow the player around. There's no way of fighting back as he's not interactable, leading the player to die from his blows or from pulling more enemies while trying to escape him. The trip back is really long, which makes the whole thing very frustrating.

![Vaukannus_003](https://user-images.githubusercontent.com/53320075/64319668-4bc73780-cf93-11e9-91aa-53e0370bbcfe.jpg)
![Vaukannus_004](https://user-images.githubusercontent.com/53320075/64319670-4c5fce00-cf93-11e9-97f8-4ab32d3950b7.jpg)
![Vaukannus_005](https://user-images.githubusercontent.com/53320075/64319671-4cf86480-cf93-11e9-892b-b6fe76623b9a.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 14.09.2019
