### ISSUE TITLE
Quest Encroaching Darkness in Nordland

### ISSUE THREAD

**Issue by eisenhans** [WarEmu/WarBugs#14882]
Quest steps don't continue correctly. You get the quest from the Sigmarite Acolyte at around 34, 28. When you click on the sack at the Burning Windmill PQ, you cannot continue normally. On live, you clicked the sack, got hints to the next step (going to The Norse Are Coming PQ), then went back to the Acolyte to get your reward. In ROR, you click the sack, have to ride back to the Acolyte, who now has the dialogue the sack should have given you, then go to The Norse Are Coming as you were supposed to do, then go back to the Acolyte for the reward.

**Comment by Natherul** [comment]
should be fixed with patch as of today
