### ISSUE TITLE
Beastlord Mantle of the Stag cannot be dyed

### ISSUE THREAD

**Issue by Grock-r** [WarEmu/WarBugs#14886]
*I looked and i couldn't find any previous tickets about this*

**Expected behavior and actual behavior:**
The cloak is [marked as 'cannot be dyed'](https://i.imgur.com/vaITIzm.jpg) despite the fact that its appearance [does support dyes](https://i.imgur.com/mzqdL1D.jpg) if you apply it to another cloak.

[Better look with brighter dyes](https://i.imgur.com/vY5Atpk.jpg) (Go Fasta and King Blue)
Notice the markings on the skull and the horns - they are not visible without dye.

This cloak is a best-in-slot for a slayer and handful of other classes, being stuck with default colors on all cloak apperances really sucks...

Since we have client control nowadays I'm really hoping this issue can be fixed, thanks!

**Comment by grunbag** [comment]
We can’t fix it yet
