### ISSUE TITLE
Magus crit tactic

### ISSUE THREAD

**Issue by globalgame** [WarEmu/WarBugs#14898]
Chaos Unleashed tactic does not effect most of Havoc abilities!

I did not see any differences of my critical hits when this tactic is active. 

Tested in two ways Chaos Unleashed tactic with 0% crit chance and with 20% crit chance and almost nothing no changes.

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format.

**Comment by globalgame** [comment]
Abilities of Havoc: Indigo Fire of Change, Baleful Transmogrification, Withered Soul.

It was dummy in IC then 40 lvl Champion also i watched how often it happens in rvr/sc for a week i tested it.

**Comment by globalgame** [comment]
and about Wild Changing crit tactic for Path of Changing i do not know i ever did not use it at all maybe also ....

**Comment by sioding** [comment]
Please add your testing screenshots

**Comment by globalgame** [comment]
i gave u proof from my words after detailed test for sreens need again respec for that time to do them i want to play instead sorry maybe later

**Comment by globalgame** [comment]
![WAR 2019-09-08 23-35-58-32](https://user-images.githubusercontent.com/24555848/64493461-2a16ca80-d289-11e9-8185-ccb7eac7f6ff.jpg)

**Comment by globalgame** [comment]
maybe this tactic works not for all abilities of Havoc but guess for Flickering Red Fire it works

**Comment by CornerbackAC** [comment]
![Xeyron_042](https://user-images.githubusercontent.com/11341460/64493865-fab28e80-d285-11e9-98dd-ae3bf2157eb5.jpg)
![Xeyron_041](https://user-images.githubusercontent.com/11341460/64493866-fb4b2500-d285-11e9-8661-1de7f2a4a062.jpg)

Did some more testing. apparently the tactic doesnt work on the dots. Not sure about BoC.

**Comment by CornerbackAC** [comment]
Also not too convinced about IFoC. 40% crit was with the tactic, 35% without.
![Xeyron_043](https://user-images.githubusercontent.com/11341460/64494044-351d2b00-d288-11e9-8783-ceb03db25ff1.jpg)
![Xeyron_044](https://user-images.githubusercontent.com/11341460/64494045-351d2b00-d288-11e9-868d-f98f22238fb5.jpg)

**Comment by globalgame** [comment]
possible some mistakes with dummy because dummy has not crit reduction

**Comment by Dekoupwar** [comment]
The tactic seems to work as follow : 
Increase your critical rate by 15% of your curent critical rate 

https://zupimages.net/viewer.php?id=19/48/k35t.jpg
https://zupimages.net/viewer.php?id=19/48/jkzt.jpg

21% crit without : 21*15/100 = 3
21+3 = 24% crit

**Comment by globalgame** [comment]
Hm if it gives % to your critical hit rate so why in this way Flickering Red Fire and Red Wings do crit damage with just crit tactic without any other personal crit chance?

**Comment by Dekoupwar** [comment]
Well if I am right, crits depend on your % to crit, AND your target's % to be crit
How much chance to crit does the caster have (with and without tactic and how much chance to be crit does the target have ? 

If 1 of the 2 answer is > 0, I think you have the answer
