### ISSUE TITLE
Engi Redeploy causes NullReferenceException from CalculPin

### ISSUE THREAD

**Issue by Grock-r** [WarEmu/WarBugs#14892]
Character name is Kardell
Was happening in Caledor, not T1. I suppose pet tries to get geodata, but it only exists in Nordland/Norska.

Using Redeploy with an active turret causes you to lag (you can still move around and use abilities, but nothing happens), after about 20 seconds you freeze for a moment and either crash to character select or get this:

https://i.imgur.com/w5Yy1qi.jpg
![w5Yy1qi](https://user-images.githubusercontent.com/24813035/64476694-07a68380-d19b-11e9-8c46-cb7339cdb8ed.jpg)

Related to this: https://github.com/WarEmu/WarBugs/issues/14890
I don't see crash or NullReferenceException referenced here: https://github.com/WarEmu/WarBugs/issues/14889

**Comment by sioding** [comment]
fixed with patch from 14.09.2019
