### ISSUE TITLE
Glomp da Squig Masta -- Invisible adds/puddles and abilities not working

### ISSUE THREAD

**Issue by lokiusus** [WarEmu/WarBugs#14894]
**Expected behavior and actual behavior:**

Boss rotation includes spawning puddles and adds. Both are not appearing for party members even with highest visual settings/effects on all. Sometimes adds will show for one member but will be invisible for others. Adds can damage party members who cannot see them.

Additionally - abilities are not showing as applied in the UI for the caster (specifically noted BG Guard/ Shaman HoTs). 

**Steps to reproduce the problem:**

Unclear. May just be a broken boss after new patch. I'll try to reproduce with a different party later today. 

**Testing Screenshots/Videos/Evidences (always needed):**

Main tank took a video of the issue. He'll be commenting on thread with link when uploaded. 

![Sarr_008](https://user-images.githubusercontent.com/55027530/64477210-a49af980-d166-11e9-8e11-ebeef27c65c4.jpg)
![Sarr_007](https://user-images.githubusercontent.com/55027530/64477214-ae246180-d166-11e9-9fed-007f06a93927.jpg)

**Comment by MightyPhred** [comment]
https://www.youtube.com/watch?v=3biR8kllwho&feature=youtu.be

**Comment by sioding** [comment]
This should be fixed with the hotfix today - please give feedback if not.

**Comment by MightyPhred** [comment]
killed him, seems to be working fine

**Comment by sioding** [comment]
thx.
