### ISSUE TITLE
Quest Daemonic Strength

### ISSUE THREAD

**Issue by MCMacDaddy** [WarEmu/WarBugs#14895]
Unable to interact with the 'Ammunition' pile.  Able to select and fire the Hellcannon, but no damage is done to the Dwarf Gyrocopters, making the quest impossible.

**Comment by Moragor** [comment]
Confirming the problem. It seems to be a pathfinding issue, the copter can't calculate a valid path and resets. I was able to kill some of the copters, but not others.

**Comment by Lheana** [comment]
Well I could easily kill 2 gyrocopters to complete the quest...

**Comment by sioding** [comment]
Fixed with patch from 06.10.2019
