### ISSUE TITLE
[RR Spec] Vigor does not work

### ISSUE THREAD

**Issue by Krumlok** [WarEmu/WarBugs#1489]
![bug](https://cloud.githubusercontent.com/assets/14275335/10023871/781f76dc-6154-11e5-9b5c-3660c234e81e.png)

As you can clearly see on the picture, the wounds stat updates on the char page but it's not correctly applied

**Comment by Krumlok** [comment]
NVM. After a quick hotfix, it works.

**Comment by Evildoor** [comment]
Can be fixed by unequipping and equipping any item with wounds.
