### ISSUE TITLE
Troll flesh

### ISSUE THREAD

**Issue by kpihuss** [WarEmu/WarBugs#14891]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**
I Can't equip this if stacked

**Steps to reproduce the problem:**
Equip Troll flesh

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/54821994/64475918-29970a80-d189-11e9-9d77-3537f03ad6b3.png)
![image](https://user-images.githubusercontent.com/54821994/64475927-39aeea00-d189-11e9-96c2-9636737dd127.png)

**Comment by sioding** [comment]
Fixed with patch from 28.09.2019
