### ISSUE TITLE
[Slayer] [Gudrun's Warcry]

### ISSUE THREAD

**Issue by Fikatind** [WarEmu/WarBugs#149]
Rank 12
Core ability, BuFF

Your groupmates are inspired by your eagerness to fight. Your group's abilities cost 25% fewer Action Points for 20 seconds.

Only animation is working,

**Comment by Thorgatin** [comment]
The ability increase the tooltip AP cost of other abilities atm, but doesn't increase/decrease any costs at all (according to wsct):
Before warcry:
![thorgatin_031_crop](https://cloud.githubusercontent.com/assets/8567481/6268061/e48a0634-b849-11e4-8232-fee0c52f1076.jpg)
After warcry:
![thorgatin_033_crop](https://cloud.githubusercontent.com/assets/8567481/6268064/f1607050-b849-11e4-88e2-a3d865d2b27c.jpg)
WSCT AP regen after flurry usage:
![thorgatin_035_crop](https://cloud.githubusercontent.com/assets/8567481/6268079/13bd823c-b84a-11e4-9f72-87d6c74f84b3.jpg)
