### ISSUE TITLE
[Item] Pious Gladiator Ring has strange Item-Type

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#14902]
The requirements for this accessory are set as "both hands" and "great accessory", but it can be equipped as usual.
![Zkyr_029](https://user-images.githubusercontent.com/40274248/64491072-29b80880-d264-11e9-9979-4c581130158f.jpg)
 Quest-Reward in Talabec Chap 14.

**Comment by sioding** [comment]
Fixed with patch from 28.09.2019
