### ISSUE TITLE
Problem inventory in dungeons gunbad

### ISSUE THREAD

**Issue by Saintpastissier** [WarEmu/WarBugs#14903]
Hello i have a problem . In the dungeon (Gunbad) i have loot win lost (it's my second time have the problem

)
![Briseorcks_041](https://user-images.githubusercontent.com/42912867/64493272-68f35300-d27e-11e9-9578-cf74c0722ce3.jpg)

would this problem come from my bugger inventory in full. or is this a problem related to Gunbad
![Briseorcks_042](https://user-images.githubusercontent.com/42912867/64493307-c7b8cc80-d27e-11e9-8d48-dcdbf221da20.jpg)

**Comment by sioding** [comment]
You better make yure you inventory isn#t that cluttered wheren you are entering a dungeon. You can move the Overflow Item to you personal bank to get it. We don't give out any missed loot. So its not a real bug at all - i close this one here.

**Comment by Saintpastissier** [comment]
ok no problem for object it's not the problem . now my inventory is clean . but my personal bank is encombrate by the object and it's not possible destroy or move
