### ISSUE TITLE
[Pathfinding test] More pathing bugs

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#14906]
Here are some clips I recorded during testing: https://streamable.com/s8522

1st: Pet/NPC not using a direct path, probably a bad navmesh. Beach at bottom left Norsca map (see minimap). Occurrence: Very rare
2nd: NPC visibly walking towards the player, but its true position for combat calculation stays at the squig. From the scrolling combat text you can see he hits the squig, not me. Occurrence: 30-40% of all fights with melee enemies that got engaged by my squig.
3rd: Like 2, but with rubberbanding. Occurrence: Rare
4th: Like 2 but with random reset. Occurrence: Very rare

**Comment by MaxHayman** [comment]
Going to close this as a lot was changed since this patch. Please reopen if you still have issues.
