### ISSUE TITLE
Epic quest bug

### ISSUE THREAD

**Issue by Altarion4** [WarEmu/WarBugs#14907]
The epic mission CONTROL ( t3 elf ) this bug, it sends me to kill two bosses to give me their two necklaces and destroy them, but I kill them and they don't give me the necklaces they give me the tear of isha object that is from the previous mission, thank you and sorry the inconvenience.

**Comment by Lheana** [comment]
Hm it seems like you have not understood the quest well. You don't have to kill these NPCs, you have to use Tears of Isha on them. See https://wiki.returnofreckoning.com/index.php/High_Elves_T3_Epic_Quest_Control#STEP_13
