### ISSUE TITLE
Deliberate disruption of the castle’s attack.

### ISSUE THREAD

**Issue by Lestrigon78** [WarEmu/WarBugs#14912]
Today, during the siege of the castle in Praag, the Grungeor character deliberately thwarted the castle’s attack by intercepting a ram and setting it in front of the gate. He motivated it by the fact that it was his ram. Please apply disciplinary action to the specified player.
https://youtu.be/j2Tvz9IE1kg

**Comment by maksshram** [comment]
I witnessed this incident . Please punish this player for deliberate failure of the attack of the castle . He thwarted the attack for more than 20 minutes .

**Comment by sioding** [comment]
wrong place to report it. This behavior needs a GM - not a bugtracker. Since i was the GM who worked on the ingame tickets regarding this issue it doesn't need to be reported again. Next time: Ingame appeal - not the bugtracker please.
