### ISSUE TITLE
Bloodlord Andsplate Black Orc 7pc Bonus

### ISSUE THREAD

**Issue by elk76** [WarEmu/WarBugs#14917]
I equipped the piece but the 7pc Bonus is not active

![Puparuolo_283](https://user-images.githubusercontent.com/46483570/64727920-3ba2e100-d4da-11e9-9635-f3987e85f9ca.jpg)

**Comment by DypfrystBram** [comment]
Thanks! - I just made a post about it. They can use the pic too i guesss

**Comment by sioding** [comment]
Fixed with patch from 28.09.2019
