### ISSUE TITLE
why did not I receive a RR + level up

### ISSUE THREAD

**Issue by noobwarrior** [WarEmu/WarBugs#14915]
I fought and won against the AM *

![Relife_261](https://user-images.githubusercontent.com/53536809/64673733-3ceaf400-d46f-11e9-9ba8-b0168433b194.jpg)

As you can see there is also that I became RR84
but that can only be a mistake since I have been RR84 for weeks already

![Relife_258](https://user-images.githubusercontent.com/53536809/64673925-c69ac180-d46f-11e9-9ca9-ce3bddb90f54.jpg)
the picture was taken yesterday..there you can see my rr bar

**Comment by noobwarrior** [comment]
or will I be downgraded to 83 ??
and if why.?

**Comment by Natherul** [comment]
If you see the outrageous amount gained thats the visual bug where your client thought for a second you were at 0 renown and attempted to give you the difference to reach your right rank. You were not actually lower. Its just visual and an issue between client and server

**Comment by Natherul** [comment]
same issue as https://github.com/WarEmu/WarBugs/issues/10401
