### ISSUE TITLE
Epic quest (CONTROL) 

### ISSUE THREAD

**Issue by Altarion4** [WarEmu/WarBugs#14911]
I already tried to use the object tears of isha in the 2 NPCS without attracting them and in their area and the quest still does not work :) I try it all I have experience since the original game was released years before its closure and I like to report bugs just to help To make the game comfortable for everyone, sorry I still don't know how to put videos or screenshots here, thanks. :)

**Comment by Lheana** [comment]
It works:
![Lheana_096](https://user-images.githubusercontent.com/11537611/65433067-9ca4b000-de1c-11e9-9483-8705f0b859d9.jpg)
But to make it easier, the range will be increased with next patch.

**Comment by sioding** [comment]
Fixed with patch from 28.09.2019
