### ISSUE TITLE
T1 Empire PQ

### ISSUE THREAD

**Issue by Itmritual** [WarEmu/WarBugs#14927]
The T1 Empire PQ is not currently working as you can see from the screenshot. There are no npc's and it says it's not reseting for a weird amount of time that isn't ticking.
![Vylenn_000](https://user-images.githubusercontent.com/31557076/64921865-07f3df80-d796-11e9-8c97-53e04cb85a68.jpg)

**Comment by sioding** [comment]
should be fixed with server restart right now
