### ISSUE TITLE
[fort] reservation erased

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#14926]
**Expected behavior and actual behavior:**
I didn't have reservation when zone locked.
but entered fort after original reservation expired around 9:00 timer.
inside the fort, I had siege weapon glow graphic bug on my screen, had to relog.
upon relog loading screen i got kicked to character selection window once.
on second relog i spawned in front of portal but couldn't get in fort.
it said ' too many attackers ~ '
reservation was erased. or never was there.

**Comment by sioding** [comment]
sounds for me like working as intended - you did't had a reservation but you was able to get in after reservation timer went down. then you decided to relog - dunno why you should be able to re-enter.

**Comment by Natherul** [comment]
reservations were not intended to work that way. Either way next patch has some adjustments for reservations.
