### ISSUE TITLE
[Quest] The Sacellum Dungeons | Can't turn in!

### ISSUE THREAD

**Issue by Sciberr** [WarEmu/WarBugs#14924]
An introduction:
The quest NPC is dead so I can't turn in this chain quest for the Sacellum Dungeon.

Details:
I should be able to turn in the quest.

Evidence:
https://youtu.be/7MVugL_bSNs

Additional Information:
Also why does all those mobs get pulled from outside of their rooms please fix.

How to reproduce the bug:
To reproduce bug get the NPC killed.

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 28.09.2019
