### ISSUE TITLE
problem of stat

### ISSUE THREAD

**Issue by Saintpastissier** [WarEmu/WarBugs#14929]
![Briseorcks_051](https://user-images.githubusercontent.com/42912867/64923866-81172500-d7de-11e9-8519-311f325d800e.jpg)
![Briseorcks_050](https://user-images.githubusercontent.com/42912867/64923867-81172500-d7de-11e9-9f9f-df5a7fbd57b7.jpg)
![Briseorcks_049](https://user-images.githubusercontent.com/42912867/64923868-81172500-d7de-11e9-8405-c94861618157.jpg)
![Briseorcks_048](https://user-images.githubusercontent.com/42912867/64923869-81afbb80-d7de-11e9-8a78-f53fe37a4334.jpg)
![Briseorcks_047](https://user-images.githubusercontent.com/42912867/64923870-81afbb80-d7de-11e9-8075-c3710576b366.jpg)

they are a problem for statistique resist and block/parry etc (with buff other people)

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format.

**Comment by sioding** [comment]
No answer for 13 days - close
