### ISSUE TITLE
[Item] IB Gloves from Gold bag | IM A BLACK ORC!?!

### ISSUE THREAD

**Issue by Sciberr** [WarEmu/WarBugs#14925]
An introduction:
I got ironbreaker gloves from a gold bag when im a black orc.....

Details:
I should be getting black orc items.....

Evidence:
https://youtu.be/nMN9TfEstmM

Additional Information:
Please keep working hard to satisfy our most delicious desires! 

How to reproduce the bug:
Secretly be a IB spy inside a BO corpse >:D

**Comment by sioding** [comment]
Duplicate of #11739
