### ISSUE TITLE
[Witch Hunter] Blessed Blade tactic and BAL last tick

### ISSUE THREAD

**Issue by convexte** [WarEmu/WarBugs#14923]
Looks like Blessed Blade (50% armpen for 3 secs after finisher) tactic dont affect last tick of the Burn Away Lies ability.Tested it in duel (WH vs WP in Altdorf), then tried WH vs BG in oRvR.Absolution was used right before last BAL tick just to enable tactic self-buff on WH, look at this mitigation.This is wrong.
![bal_test](https://user-images.githubusercontent.com/42184160/64871495-cad90180-d65e-11e9-98c2-82c0883dc648.jpg)

**Comment by globalgame** [comment]
Execuations Requires Accusations so Execuation is spending of Accusation.

Blessed Blade - your armour penetration is increased by 50% for 3 second
after successful of your Execuations.

WH gets 50% armor penetration after spending of Accusation and ending damage from Burn Away Lies it's not spending of Accusation !

**Comment by convexte** [comment]
WH gets 50% armor penetration after spending of Accusation and ending damage from Burn Away Lies it's not spending of Accusation !

thats why i said:

 "Absolution was used right before last BAL tick just to enable tactic self-buff on WH"
Absolution is the finisher wich spending Accusations, right?

**Comment by Uchoo** [comment]
Why don't you have time stamps enabled? The mitiation numbers before the final tick show some variance. Are you sure that you timed it correctly?

Right above, you have ticks of Burn Away Lies hitting about 25% mitigation, then the last tick is hitting against over 60% mitigation. It look as if you mistimed the Absolution.

**Comment by convexte** [comment]
Ye, thats my fault i have no time stampts.WH used Absolution right before BAL last tick, and im saying it 3 times here.
But still, everyone can reproduce it and test it by themself instead of useless discussing.I have WH, i have tank on destro side, if you want to test it - just tell me.

**Comment by globalgame** [comment]
Dummy test and all working fine Blessed Blade tactic works all time when you spending of Accusation even if after last BAL tick when you use Absolution !

**Comment by globalgame** [comment]
I think also for sure need screen dmg with active Blessed Blade buff to see that

**Comment by Uchoo** [comment]
The reason I ask is because I know the last tick of BaL happens after the debuff expires so it could be very easy to mistime it. Can you test again with timestamps?

**Comment by Uchoo** [comment]
I can offer a Destro tank to help test at some point if you need help.
