### ISSUE TITLE
A cold heart quest: object respawn timer

### ISSUE THREAD

**Issue by Aanathema** [WarEmu/WarBugs#14932]
**Expected behavior and actual behavior:**
In the Troll country, quest "A cold heart", the "Ancient Urn" object takes too long to respawn. 
I have been there 2 times with parties and both times we left because it took too much time to wait for the "Ancient Urn" to respawn.
We waited atleast 5 min for it to respawn but it did not.
I would say for Expected behavior to respawn more quickly.

**Steps to reproduce the problem:**
Take the quest and check the spawn timers. (??)
"Ancient Urn" map cordinates are 32179,34345

**Testing Screenshots/Videos/Evidences (always needed):**
![69816969_1599297906868233_7690734281789800448_n](https://user-images.githubusercontent.com/55383380/64945295-e3bcff00-d878-11e9-9d92-95f4ed6a9a4f.jpg)
![a cold heart](https://user-images.githubusercontent.com/55383380/64945791-07cd1000-d87a-11e9-923c-0f7b0ef8b6b0.jpg)

**Comment by Lheana** [comment]
Reduced the respawn timer to 2 min.
Note that a message appears above the urn when it's too soon to make spawn the NPC again.

**Comment by sioding** [comment]
Fixed with patch from 28.09.2019
