### ISSUE TITLE
wildfire seems to do have only two ticks dot and doing 33 % less damage

### ISSUE THREAD

**Issue by harkerkane** [WarEmu/WarBugs#14937]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**

wildfire should have three tick on activation which do 765 damage (on my char) but at activation only two ticks appears for 482 damage

**Steps to reproduce the problem:**

slot wildfire and make it proc

**Testing Screenshots/Videos/Evidences (always needed):**

![Pyrosius_005](https://user-images.githubusercontent.com/45519748/65012356-0e19c580-d928-11e9-9a97-fe0df5b4f78f.jpg)

**Comment by wargrimnir** [comment]
3 ticks next patch

**Comment by Natherul** [comment]
fixed as of patch just now
