### ISSUE TITLE
Bank/Appearance 

### ISSUE THREAD

**Issue by trivoid** [WarEmu/WarBugs#1493]
When using "Plundered Chestplate" while it's in my bank for an alternate appearance it changes to another item (Gladiator's chain of conquest) and makes my marauder look naked.

Works fine via inventory.

![india_000](https://cloud.githubusercontent.com/assets/14798760/10037929/dfacc768-61b4-11e5-8484-4d1bb006fbab.jpg)
![india_001](https://cloud.githubusercontent.com/assets/14798760/10037930/dfad77da-61b4-11e5-9a46-edfdce57debd.jpg)
![india_002](https://cloud.githubusercontent.com/assets/14798760/10037928/dfaca47c-61b4-11e5-9c0f-49dbcd42355c.jpg)

**Comment by Evildoor** [comment]
Tested this, seems to be independent from class/item.
Side note - until fix this can be used to emulate requested by some people (me included) but not implemented yet feature to hide any piece of equipment via items with invisible models.

**Comment by Tesq** [comment]
yea cool to hear :D

**Comment by Lheana** [comment]
It seems like now you need to have your items in your inventory to change the appearance. So this is no longer an issue.
