### ISSUE TITLE
[ui] warbands composition displayed incorrectly

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#14938]
this happened in CW ; initially all was fine ,then
![Chimp_095](https://user-images.githubusercontent.com/17765890/65045034-5d7ae880-d95e-11e9-8d57-a18326d7ac17.jpg)
(second wb was displayed as having only one member that was a rank 0 bo leader)

and it was not affecting only me
![Chimp_098](https://user-images.githubusercontent.com/17765890/65045073-6ff52200-d95e-11e9-8fcf-9edbc0ed9340.jpg)

porting to another zone and going back did not solve the issue.

time to file this bug and go back to the game , the issue automagically resolved itself.

**Comment by MaxHayman** [comment]
I think i fixed this a few months ago. Please reopen if this is not the case.
