### ISSUE TITLE
Shaman Invader 7th piece

### ISSUE THREAD

**Issue by Xotesede** [WarEmu/WarBugs#14946]
It had already been posted but it's supossed to be solved as the ticket is closed, yet the bug is still there. Whenever you use other skills, doesn't have to be a skill of Mork, it has the chance to proc. Got the proc yesterday when using the mount.

https://youtu.be/7Md925aGtes
Go to minute 4 to skip all the non-related stuff. I actually thought I got the procc by using the pot but when checking the video you can see it's with the mount.

**Comment by wargrimnir** [comment]
This should have been corrected some time ago.
