### ISSUE TITLE
fel sacrifice leave black squre when used

### ISSUE THREAD

**Issue by acidicrain** [WarEmu/WarBugs#14949]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**
no black squre

**Steps to reproduce the problem:**
on dok cast fel scarifice

**Testing Screenshots/Videos/Evidences (always needed):**

https://youtu.be/MJTkp0qNDis

**Comment by sioding** [comment]
The video does not help - nor is your description. Please try again.

**Comment by acidicrain** [comment]
ok uploaded wrong video , sorry about that but it did give some more info.
Tested fel sacrifice in IC worked correctly. Went to KV and black sqare appeared around me for the duration of fel sacrifice

https://youtu.be/6qjSz8g-p4A

**Comment by Kaelang** [comment]
This no longer happens on live. Please re-open if issue persists with more information.
