### ISSUE TITLE
Can't kill champion: Onyxmaw. In target but no attack

### ISSUE THREAD

**Issue by exotlv** [WarEmu/WarBugs#14945]
Found a champion, could target him but can't attack

**Expected behavior and actual behavior:**
Actual: Cant kill champion
Expected: Could kill champion

**Steps to reproduce the problem:**
Location: CW - 43400 / 63395

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/8436809/65302454-e6269e00-db83-11e9-9840-91e15e68f2cc.png)

**Comment by Lheana** [comment]
This NPC is in fact inside the cave under the mountains. He will no longer roam with next patch, hoping this will fix it.

**Comment by sioding** [comment]
Fixed with patch from 28.09.2019
