### ISSUE TITLE
Siege weapons profit from Ws stat

### ISSUE THREAD

**Issue by Marawo** [WarEmu/WarBugs#14948]
Expected behaviour:
Siege weapons should not scale with any stats or mechanics apart from incoming damage % increase.
Actual behaviour:
Siege weapons (Oil, Cannons) take the users armorpenetration value resulting in extreme damage values for high WS classes and negligible damage values from low ws classes.

Steps to reproduce the problem:
Take damage from siege weapons and observe the combatlog. Compare migitation values between different siege weapon users. Migitation should be different depending on the useres armorpen value.

Evidence:
![siege weapon oil damage](https://user-images.githubusercontent.com/29643742/65373375-fff7dc00-dc7c-11e9-8706-81800e6c4bd8.png)
A similar pattern can be observed from cannons.

Suggestion for a fix:
Implement either a dummy WS/armorpen value for siege equipment or a rebalanced unmigitateable damagevalue.

Note: 
Any names that show up in the posted combatlogs are solely used for situation comprehension purposes.

**Comment by sioding** [comment]
Fixed with patch from 28.09.2019
