### ISSUE TITLE
[ui] open wb tooltip showing wrong data

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#14943]
upon entering a rvr zone, a tooltip is now displayed in the upper left region of the screen; but open wbs in "nearby" tab shows different results.
![Chimp_099](https://user-images.githubusercontent.com/17765890/65259567-26930700-db05-11e9-8df0-b594df441a2e.jpg)

**Comment by MaxHayman** [comment]
This change was made but playrs prefeer using the open warband window to show all world groups.
