### ISSUE TITLE
Bugusers

### ISSUE THREAD

**Issue by vobex15** [WarEmu/WarBugs#14954]
Sistah
![screenshot_001](https://user-images.githubusercontent.com/54207654/65390670-e2ed0700-
![Antifriz_034](https://user-images.githubusercontent.com/54207654/65390820-9950ec00-dd6a-11e9-91f3-c062b71d0908.jpg)

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by sioding** [comment]
First of all: Call a GM if you think someone is doing weird things. The bugtracker is only for ingame bugs only. And: Give us please screenshots in english
