### ISSUE TITLE
Undeserved blessing - Elixir of Blessing not working

### ISSUE THREAD

**Issue by iiiLollo** [WarEmu/WarBugs#14956]
![Shaliza_002](https://user-images.githubusercontent.com/15178815/65417785-322f4800-ddfb-11e9-8d9d-228024dc56d4.jpg)

Upon reaching the camp, I tried the following:
- interacting with the Cook Pot 
- interacting with Basket of Food 
- using Elixir of blessing from inventory near Cook Pot
- using Elixir of blessing from inventory near Basket of Food

None of this actions triggers the "Poison Foodstores" required by the quest.
"Cook Pot"
![Shaliza_003](https://user-images.githubusercontent.com/15178815/65417786-32c7de80-ddfb-11e9-8e8c-8b919fd5f26f.jpg)
"Basket of Food"
![Shaliza_004](https://user-images.githubusercontent.com/15178815/65417787-32c7de80-ddfb-11e9-87f1-0490c341c178.jpg)

**Comment by Lheana** [comment]
Try using the Elixir of Blessings **targeting** the Basket of Food.
