### ISSUE TITLE
[Influence] Dwarf Chap 15 - low stats on "Armbraces of Rage"

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#14953]
The stats on the gloves seem to be lower than intended, espacially in comparison to the boots

![Dwarf chap 15](https://user-images.githubusercontent.com/40274248/65387746-91814f80-dd4a-11e9-967d-81fc49250e60.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 06.10.2019
