### ISSUE TITLE
Warband Lead Settings Not Working

### ISSUE THREAD

**Issue by Itmritual** [WarEmu/WarBugs#14955]
The last two times I've led a Warband on my AM, it doesn't allow me to switch people from group to group or make the group private. It also doesn't show me the people in the warbands when I hover over them. This obviously makes it hard to lead.
![Miitzie_015](https://user-images.githubusercontent.com/31557076/65394915-648c6700-dd61-11e9-9970-cc47b6281acc.jpg)
![Miitzie_016](https://user-images.githubusercontent.com/31557076/65394918-68b88480-dd61-11e9-93fc-6a83b1aeedaf.jpg)

**Comment by MaxHayman** [comment]
This should be fixed. Please reopen if not.
