### ISSUE TITLE
Character stuck in Scenario unable to log in

### ISSUE THREAD

**Issue by Runninronin** [WarEmu/WarBugs#14967]
Character shows logged into Talabec Dam Scenario at log in screen.

As soon as Play is hit, character is stuck on the Searching for Allies Screen.

Scenario manager issues?

![bug2](https://user-images.githubusercontent.com/55218361/65746089-72285080-e0c3-11e9-9dee-26473f7e3030.png)
![bug](https://user-images.githubusercontent.com/55218361/65746096-78b6c800-e0c3-11e9-9161-32bba5c034f9.png)

Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by sioding** [comment]
fixed with scenario manager restart
