### ISSUE TITLE
[Quest] Unlikely Places | Quest just vanishes?

### ISSUE THREAD

**Issue by Sciberr** [WarEmu/WarBugs#14968]
An introduction:
I click accept on the quest Unlikely Places and have to use 3 potions in battle but I don't get any quest to do so...

Details:
I should be getting a quest to show my progress.

Evidence:
In the video I show myself turning in the quest before it since its a chain, accepting the quest after and nothing happens it just vanishes.
https://youtu.be/uZea-iz0l4E

Additional Information:
N/A

How to reproduce the bug:
N/A

**Comment by Kabucoror** [comment]
The original level requierment for the last step was to high.
Will be fixed with next patch.

**Comment by sioding** [comment]
Fixed with patch from 06.10.2019
