### ISSUE TITLE
Shadow Warrior - Assault stance and Marked gear trait

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#14962]
As Assault stance description says: While in the Assault stance, your ranged prowess item stats will counts towards your melee prowess in 1 to 1 conversion.
'Marked' trait comes from gear only, what it does: with every hit you have 25% chance to reduce enemy's Initiative by XX and increase your Ballistic skill by YY for ZZ seconds.
And, logically, while in the Assault stance this trait must give you both Ballistic skill and Strength or only Strength at least.
But it gives Ballistic skill only, that is useless for melee SW, since he need Strength.
Tests: out of Assault stance, in Assault stance and in Assault stance + Marked proc (+84 Ballistic skill in this case)
No any tactics has been slotted - to make tests clear.

![2019 09 25-17 54](https://user-images.githubusercontent.com/16439840/65614113-bcc0a480-dfbf-11e9-8528-dc695a8adf29.jpg)

The Marked trait has been found on two sets: Beastlord and Conqueror. Maybe, somewhere else, not sure.

![2019 09 25-18 00](https://user-images.githubusercontent.com/16439840/65614114-bcc0a480-dfbf-11e9-9c08-def6fa2cc5a1.jpg)

Please consider to fix this.

**Comment by SilverWF** [comment]
Just a little addition.
I didn't tested, but most likely, the same would be with this sets for Squig Herders and their skill Squig Armor

**Comment by SilverWF** [comment]
> 
> 
> Just a little addition.
> I didn't tested, but most likely, the same would be with this sets for Squig Herders and their skill Squig Armor

I've tested it at my Squig Herder and full Conqueror gear.
It works the same in the Squig Armor - adds only BS, but not Str.

**Comment by grunbag** [comment]
It convert stats 1-1 from items stats only , not from buff / tactic etc .
