### ISSUE TITLE
[Quest] Traveling Quest, "Price of Pride" offers no reward

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#14969]
The traveling NPC in Orc/Dwarf-Zone used to reward you with ingredients to craft colors on completing the quest. But atm you just get 150xp for turning the quest in

![TNPC_PoP](https://user-images.githubusercontent.com/40274248/65764957-30c98c80-e127-11e9-80f7-f9472d0695b7.jpg)

**Comment by Kabucoror** [comment]
On dev the ingredient is shown and you get it as reward.
Did you get it anyway?

**Comment by Scophis** [comment]
Nope didn't get anything except 150xp

**Comment by Scophis** [comment]
Tried multiple times, but got no ingredient. 
Checked the other quests and I have the same problem there. Looks like Burli doesn't want to share with me anymore.
![KV](https://user-images.githubusercontent.com/40274248/65915892-a27a3280-e3d4-11e9-8f77-b01db6227e4e.jpg)
![TM](https://user-images.githubusercontent.com/40274248/65915909-ac039a80-e3d4-11e9-8d7d-0f5588aa479b.jpg)
In CW though it's seems to be working 
![CW](https://user-images.githubusercontent.com/40274248/65915938-ba51b680-e3d4-11e9-9edc-09cff0480488.jpg)

**Comment by Kabucoror** [comment]
ok, I have the same problem on live. 
Let me know if it's still a problem after the next patch.

**Comment by funnytroll** [comment]
Have the same problem only exp in rewards
https://imgur.com/a/FE3iK1Q

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 19.10.2019
