### ISSUE TITLE
weapons salvage items

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#1497]
only staff and zealot dagger can be salvage wepon side

EDIT: also BG spear are salvagable

seems also some random weapons re salvagable but the most of the other type aren't

**Comment by Evildoor** [comment]
You mean that on destruction side no weapons aside from mentioned two can be salvaged at all? Glaives, bows, etc from all sources are unsalvageable?

**Comment by Tesq** [comment]
yep

**Comment by Reggaewaldo** [comment]
Has now been fixed, will rollover with next patch.

We have decided to not make gear/weapons that require RR to be salvageable for now. This might change in the future.

Closing.
