### ISSUE TITLE
[Item] Dysfunctional Engineer 6pc Invader proc.

### ISSUE THREAD

**Issue by Irvid** [WarEmu/WarBugs#14979]
The 6pc Invader proc is apparently dysfunctional ~ there is neither a buffline nor .getstats indication.

I've tested it on dummies and NPCs (with and without /rvr tag), aswell as throughout several PvP sessions (including /duels), for an extended period of time - with pretty much every direct damage ability available to me (just in case there is supposed to be limitation similar to that of the 7pc).

![Invader6pc](https://user-images.githubusercontent.com/53101727/65823889-23172280-e25f-11e9-9a88-347aded7de53.png)

**Comment by Kabucoror** [comment]
It actually works and it looks like this in your buffline.
![proc](https://user-images.githubusercontent.com/45296624/65968254-2aa71900-e463-11e9-9082-67679fe06c9b.PNG)

**Comment by Irvid** [comment]
> 
> 
> It actually works and it looks like this in your buffline.
> ![proc](https://user-images.githubusercontent.com/45296624/65968254-2aa71900-e463-11e9-9082-67679fe06c9b.PNG)

It started working after I've equipped the last piece of invader today (05.10.2019), before that I haven't seen the buff once since I've acquired (+2 months) and tested the 6pc bonus. 

You might still wanna have a look an see whether it's tied to some ward/unlock w/e.
