### ISSUE TITLE
Runepriest : AP ritual 100% working

### ISSUE THREAD

**Issue by Ghatisgob** [WarEmu/WarBugs#14989]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**
Master Rune of Fury (AP Ritual of Rune Priest)
Normally this spell has a 20% chance of proc, nowadays it has 100% chance of proc.

**Steps to reproduce the problem:**
Use AP ritual in left tree

**Testing Screenshots/Videos/Evidences (always needed):**
Ridaleth video :
https://www.youtube.com/watch?v=1ZCSz-7QAzU

**Comment by wargrimnir** [comment]
This was fixed in the patch today. Unable to reproduce on dev.
