### ISSUE TITLE
Bane Shield

### ISSUE THREAD

**Issue by Davjen** [WarEmu/WarBugs#14988]
Bane shield tooltip is saying "Lashing 101spirit damage at ANY enemies who hit you.

Actually out of a pack of mobs/enemies only 1 enemy is getting hit by the baneshield and not all the others 

In this screenshoot u can see only 1 mob getting the damage return from bane shield and not everyone.

![image](https://user-images.githubusercontent.com/55961996/65840174-cd518180-e315-11e9-8c88-2ed0a0fe97d0.png)

**Comment by wargrimnir** [comment]
Turn on timestamps and I'll bet it has a consistent cooldown. Without an internal cooldown, this ability would be very broken.

**Comment by Kabucoror** [comment]
no answer for 15 days. close
