### ISSUE TITLE
Multiple single item in blue bag of PQ "Siege of Bohsenfels"

### ISSUE THREAD

**Issue by Olibryus** [WarEmu/WarBugs#14983]
The same item proc three time in a bag of "Siege of Bohsenfels" public quest.

![Olibryus_001](https://user-images.githubusercontent.com/55948449/65832500-df570400-e2c4-11e9-8239-bd2b5b6cb873.jpg)

**Comment by Natherul** [comment]
should be fixed with patch as of today
