### ISSUE TITLE
Gromril Crossing 

### ISSUE THREAD

**Issue by Carcharadon** [WarEmu/WarBugs#14985]
in the Gromril crossing SC , the Order faction can cap mid Before Destruction can make it to the mid flag giving a very unfair advantage in the SC. thx 

Carcharadon

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by sioding** [comment]
No bug here - and tbh: i have seen it the other way more than once.
