### ISSUE TITLE
[Tactic] Rugged appears red?

### ISSUE THREAD

**Issue by Sciberr** [WarEmu/WarBugs#14980]
An introduction:
The tactic rugged is now level 16 why does it appear red as if I cannot use it even though I still can?

Details:
It shouldn't be red...

Evidence:
https://youtu.be/6TfQRmjWjuQ

Additional Information:
N/A

How to reproduce the bug:
N/A

**Comment by Scophis** [comment]
It was stated in the patchnote-thread by Natherul: 
"Red icons will still work and we have identified where the issue is but its not fixed yet" 
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=33459&start=10#p376659

**Comment by Natherul** [comment]
fix coming next client patch

**Comment by Natherul** [comment]
should be fixed by now
