### ISSUE TITLE
Greenskin CH5 PQ easy

### ISSUE THREAD

**Issue by iwka53** [WarEmu/WarBugs#14998]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by iwka53** [comment]
there is no pile of goods to destroy

**Comment by Lheana** [comment]
There are 8 Piles of Goods that you can destroy for this PQ.

**Comment by iwka53** [comment]
ok, my bad, i put it wrong..they are there, but cant be destroyed.. exactly, they can be destroyed, but it doesnt count to PQ :( it is still destroyed 7/8..

**Comment by Lheana** [comment]
You just need to find the 8th.
