### ISSUE TITLE
[Quest] Missing marker for "Pushing Southwards" in BC

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#14993]
Missing marker 
![Pushing_Southwards](https://user-images.githubusercontent.com/40274248/65917525-cf7c1480-e3d7-11e9-878e-e1f73c732f56.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 06.10.2019
