### ISSUE TITLE
T1 trophy quest, greenskin

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#14991]
**Expected behavior and actual behavior:**
T1 trophy quest for greenskin have total 5 rewards.
one is dark elf trophy. i can't pick 4th greenskin trophy.
choppa cris.
all 3 pairing's same.
plus DE quest doesn't work.  it didn't give quest item.

**Testing Screenshots/Videos/Evidences (always needed):**
![trophyQ](https://user-images.githubusercontent.com/19988772/65889233-dc9b0280-e3db-11e9-8228-42c6d309de85.jpg)

**Comment by sioding** [comment]
Fixed with patch from 06.10.2019
