### ISSUE TITLE
[Quest] Self-Fulfilling Prophecy (Isle of Dead): Can't talk to NPC

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#14996]
To complete the quest you have to interact with the stone and talk to the summond NPC. 
The NPC though is stuck in the stone and you can't talk to him. 
After a while the NPC vanishes and can't be resummoned.
![Sffp_1](https://user-images.githubusercontent.com/40274248/65946650-e6058880-e436-11e9-8fda-75b986c06cfb.jpg)
![Sffp_2](https://user-images.githubusercontent.com/40274248/65946653-e7cf4c00-e436-11e9-9792-7ecb235f32d9.jpg)

**Comment by Lheana** [comment]
About the NPC spawning inside the GO, there is nothing we can do now. If after like 2 min, you can not interact with the Stone again, then abandon and retake the quest.
