### ISSUE TITLE
[NPC] Horses wandering on roof

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#14994]
Noticed some strange behaviour in Kreuznach (Reikland 9k/34k), the influence of chaos seems to reach further.
![RL_Kreuznach_9k_34k](https://user-images.githubusercontent.com/40274248/65917738-5fba5980-e3d8-11e9-956d-03495b7a31d5.jpg)

**Comment by sioding** [comment]
Fixed with patch from 06.10.2019
