### ISSUE TITLE
[Witch Elf] Masterful Treachery tac having an effect without speccing

### ISSUE THREAD

**Issue by Zealote** [WarEmu/WarBugs#1500]
Getting the 10s +15% dmg buff (12pt tac, 3rd tree) out of opener without speccing/equipping (not enough points to get it yet anyway).

It does affect actual dmg as well.

**Comment by Evildoor** [comment]
Ah, so it affects every WE even without them speccing into this tactic... And i was going to ask the devs if they added 1 point to 30rr or somewhere else...
