### ISSUE TITLE
Missing Influence

### ISSUE THREAD

**Issue by Lindiranae** [WarEmu/WarBugs#15004]
Hello, 
i was at Chaos-Wastes battle, finished half an hour ago, and I got more than 25K Influence after killing the Lord. System told me at the moment i got it "Influence complete". The Vendor says "Not enough Influence", not even enough for 1 Point of it. I dont know what happended to my 25K Influence? Any chance for me to get it? :) 

Regards
L.
![Xaradia_001](https://user-images.githubusercontent.com/52664952/66259808-640abc00-e7b6-11e9-89bd-4fc58b64e889.jpg)

**Comment by Lheana** [comment]
Screenshot of your RvR influence bar please.

**Comment by Lindiranae** [comment]
![Xaradia_002](https://user-images.githubusercontent.com/52664952/66260314-5b69b400-e7bd-11e9-9e04-81b99d5acd7e.jpg)

**Comment by Lheana** [comment]
I don't know what happened, and there is not much information to try to understand and reproduce the issue.
I leave @sioding deal with it, but even if your influence has been lost, you won't get it back.

**Comment by sioding** [comment]
Anhand deiner Screenshots kann ich nicht sehen, wie viel Einfluss du bekommen haben sollst, oder aber warum dieser nicht gut geschrieben sein soll. Für die Devs ist es so nicht möglich etwas zu fixen - da man es nicht nachstellen kann. Vielleicht schaffst du es das nächste Mal einen Screenshot direkt beim Lock zu machen um dann Dinge besser zu sehen. Wie Lheana es aber auch schon geschrieben hat: Wir schreiben keine "verlorenen" Dinge gut - dafür sind diese einfach auch zu einfach wiederholbar.

**Comment by Lindiranae** [comment]
Huhu,

 

ok, kein Problem, danke für die schnelle Antwort. Da ich überwiegend RvR mache, kriege ich den Einfluss schon wieder zusammen. Es hat mich nur sehr irritiert daher wollte ich zumindest einmal nachgefragt haben. ;)

 

Gruss

L.

 

 

Gesendet: Sonntag, 06. Oktober 2019 um 16:31 Uhr
Von: "Alexander Eckert" <notifications@github.com>
An: WarEmu/WarBugs <WarBugs@noreply.github.com>
Cc: Lindiranae <sutekh@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [WarEmu/WarBugs] Missing Influence (#15004)


Anhand deiner Screenshots kann ich nicht sehen, wie viel Einfluss du bekommen haben sollst, oder aber warum dieser nicht gut geschrieben sein soll. Für die Devs ist es so nicht möglich etwas zu fixen - da man es nicht nachstellen kann. Vielleicht schaffst du es das nächste Mal einen Screenshot direkt beim Lock zu machen um dann Dinge besser zu sehen. Wie Lheana es aber auch schon geschrieben hat: Wir schreiben keine "verlorenen" Dinge gut - dafür sind diese einfach auch zu einfach wiederholbar.
