### ISSUE TITLE
BG Brutal Smash bonus not accumulative with potion

### ISSUE THREAD

**Issue by skype01** [WarEmu/WarBugs#15000]
Hi,
I m a BG and i use "Brutal Smash" for bonus on the strengh (increased of 108) and willpower.
I don't know if a bug or normal but these bonus are not accumulative with a potion.

For exemple, 
- with a potion of strengh (+100) mysstrengh is 414 
- with a potion of strengh + Brutal Smash is strengh is 422 

![20191001_potionforce00](https://user-images.githubusercontent.com/56041031/65985180-98fad400-e481-11e9-920f-71f97051d687.png)
![20191001_potionforce01](https://user-images.githubusercontent.com/56041031/65985181-99936a80-e481-11e9-9ad1-5afcd490726b.png)

If it's normal sorry for the disturbance.

**Comment by Kabucoror** [comment]
All correct here, they don't stack.
