### ISSUE TITLE
Cant get quest for da glomp in gunbad under lvl 40

### ISSUE THREAD

**Issue by xaraxdestr** [WarEmu/WarBugs#15003]
See screenshot. You can take every kill quest for bosses in gunbad beside the one for left wing endboss. (if not lvl 40) this happens with lvl 36 and 38,
![Knochenhexe_006](https://user-images.githubusercontent.com/45398873/66137138-ed768e80-e5fc-11e9-98c4-48c3429daf9e.jpg)

**Comment by sioding** [comment]
Fixed with patch from 06.10.2019
