### ISSUE TITLE
Shadow Warrior items

### ISSUE THREAD

**Issue by seraxes** [WarEmu/WarBugs#15018]
The equipable items are wrong for the Shadow Warrior class, elf shields are "Useful" and some of the elf swords aren't equipable. Worlds drops, renown gear swords are the examples I found.

The character was created about 2 weeks ago, this issue may be related to newly created characters.

![sw-bug2](https://user-images.githubusercontent.com/16610103/66476931-25675100-ea97-11e9-90e7-092e06da114d.jpg)

![sw-bug1](https://user-images.githubusercontent.com/16610103/66476793-c0abf680-ea96-11e9-8e2b-81bde36877bb.jpg)

**Comment by sioding** [comment]
Duplicate of #14905
