### ISSUE TITLE
[Skill] SW / SH leap backward

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#1501]
On official SW and SH jump off didnt work if target had root / snare immune like Sigil of Sigmar

**Comment by Evildoor** [comment]
There are plenty of reports for these abilities.
https://github.com/WarEmu/WarBugs/issues/745
https://github.com/WarEmu/WarBugs/issues/811
https://github.com/WarEmu/WarBugs/issues/1003
https://github.com/WarEmu/WarBugs/issues/1323
Use one of them if you have something to add. I'look through them and try to consolidate them into one when i'll have time and opportunity.
