### ISSUE TITLE
Unable to log into one Character

### ISSUE THREAD

**Issue by Runninronin** [WarEmu/WarBugs#15013]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:** Trying to log into my Destruction character, Kutyu.  Instead I'm getting an error on the log screen.

Was kicked while trying to fly to Dragonwake, and haven't been able to log into the character.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![bug1](https://user-images.githubusercontent.com/55218361/66282907-f4b0cd00-e886-11e9-8b66-ec573ac23a18.png)
![bug-2](https://user-images.githubusercontent.com/55218361/66282911-fbd7db00-e886-11e9-9117-20c43855843c.png)

**Comment by Bepheth** [comment]
Get quite the same problem here :  I can't log any of my high or dark-elf characters located in elven zones. 
![image](https://user-images.githubusercontent.com/56254249/66303048-6d04a600-e8fa-11e9-825c-bad5327ca906.png)
and 

![image](https://user-images.githubusercontent.com/56254249/66303136-9de4db00-e8fa-11e9-905e-3408aab385a3.png)

The only character I can play is my BlackGuard, who is in the Destro capital : 

![image](https://user-images.githubusercontent.com/56254249/66303210-d389c400-e8fa-11e9-82d8-35cdcaa6bd34.png)

**Comment by Psychoxell** [comment]
you guys tried double "/stuck" command in the loading screen after selecting your character? Normally that help and you will ported to norland (on Order Side)

**Comment by Runninronin** [comment]
Where do you type the command after selecting the character?

**Comment by Psychoxell** [comment]
Press "Enter" -> "/stuck" -> "Enter" and this again during the next 10 seconds.
You will not see the chat

**Comment by Runninronin** [comment]
there does not seem to be any change.  Will the character's starting location change on the load screen?

**Comment by Runninronin** [comment]
Oh, there was a new error after trying it.

![bug4](https://user-images.githubusercontent.com/55218361/66315862-3e77d280-e8dc-11e9-9320-38ea4a0bdc58.png)

**Comment by Bepheth** [comment]
No change at all : At each try, my location is the same (elven zones), i 
got the loading screen with the description of the zone and... wooch, go 
back to my PC desk.

Le 07/10/2019 à 15:26, Runninronin a écrit :

**Comment by Bepheth** [comment]
omg... :)

Seems it 's getting worse.

Le 07/10/2019 à 15:27, Runninronin a écrit :

**Comment by Bepheth** [comment]
You did it ! It works. All my characters are "unlocked".

Thank you very much for your answers, your reactivity and your kindness.

Greetings,

Le 07/10/2019 à 14:52, Matthias Kühl a écrit :

**Comment by Bepheth** [comment]
The /stuck command was the solution. I didn't thought we could enter a command while not in game.

Thanks again for your answer.

**Comment by Bepheth** [comment]
After a fex try, the news are'nt not so good as i mentionned before.

Yes, the /stuck command works but... Everytime i try to go to the elvish lands, whoever character may be, the game crashes as before : directly to my PC desk, with no error messages.

Kind of weird.

**Comment by sioding** [comment]
So the problem with @Runninronin is done - to the other guy: please don't hijack others reports - especially when you get other errorcodes or / see another behaviour. So i close this one here - cause the OP is fixed.
