### ISSUE TITLE
The shoulders of heres - quest / Gephank

### ISSUE THREAD

**Issue by Drobis** [WarEmu/WarBugs#15016]
Do not know if i can not find it or if it is a bug, but there is not statue of Gephank. So i can not finisf the quest The Shoulders of Heroes. 
![image](https://user-images.githubusercontent.com/56319680/66428798-03c68500-ea17-11e9-98f5-19e99f13e496.png)

**Comment by sioding** [comment]
fixed with patch from 12.10.2019
