### ISSUE TITLE
6 Piece Bonus*Beastlord*bug*

### ISSUE THREAD

**Issue by noobwarrior** [WarEmu/WarBugs#15011]
get only 4 int and not the 84 int

![Rlife_005](https://user-images.githubusercontent.com/53536809/66269195-fc03b680-e845-11e9-96d3-0ca020753c7e.jpg)
my current status was + 80 int pot
![Rlife_006](https://user-images.githubusercontent.com/53536809/66269200-19d11b80-e846-11e9-8d2a-6f78f04af944.jpg)
that when I receive the bonus

**Comment by SilverWF** [comment]
I believe, there is several buffs that didn't stack with each other, like pots, procs and RP/Zealot buffs

**Comment by sioding** [comment]
And thats ok cause youhave a INT pot used. They should not stack. Close
