### ISSUE TITLE
T2 epic quest Echoes from the past bug.

### ISSUE THREAD

**Issue by dihanin** [WarEmu/WarBugs#15012]
T2 epic quest from elf , Echoes from the past. the bug happened after defeat Laeth'r Snarlwhip champion 17 without completed quest.

**Comment by Lheana** [comment]
Your quest did not complete while you killed the NPC?

**Comment by dihanin** [comment]
yes, and I did killed twice and clicked NPC. nothing happen , and quest stuck now

**Comment by Lheana** [comment]
Please provide a screenshot. Also, are you grouped when you try to complete the quest?

**Comment by dihanin** [comment]
This is prtscn web address:
https://drive.google.com/file/d/1unZdOUwk8r-KgK0Cjh9A7hlsE6tYpsZT/view?usp=sharing
And I didn't grouped. i'm solo.

**Comment by Lheana** [comment]
This is because killing this NPC is not the objective of this quest.
