### ISSUE TITLE
BG's SC weapon giving armour

### ISSUE THREAD

**Issue by Zealote** [WarEmu/WarBugs#1502]
Know it's been mentioned about other weaps and there was a fix but Sentry's Painblade of Cruelty is still granting 360 armour (which does reduce actual dmg taken).

It might be worth checking each weap individually if poss in case any others have slipped through the net.

**Comment by xyeppp** [comment]
It's not just the BG weapons, DoK healing weapon does the same for example as well.
This issue has been raised up a few times already. A lot of SC weapons give 360 armor, should check them all.

**Comment by osium** [comment]
it's all the solider sc weapons however their damage also does not calculate properly so if your going to fix the armor please fix the damage calculation that is completely borked

**Comment by Joiez** [comment]
Slayer 2h and AM 2h weapon don't have hidden armor bonus, unless you have a 2h BO weapon with bonus Osium i'd say only 1h weapons are buged or atleast not all t3 weapons have hidden armor bonus

**Comment by Reggaewaldo** [comment]
Armor has been removed from the: Sentry's Painblade of Cruelty

**Comment by Reggaewaldo** [comment]
Armor has been removed from items from IID: 5500481 to 5500525.

(Item's that where not supposed to have it.)
