### ISSUE TITLE
4x destro rams at the same time on the Order Keep

### ISSUE THREAD

**Issue by Psychoxell** [WarEmu/WarBugs#15029]
**Expected behavior and actual behavior:**
Expected behavior: 1 Ram
actual behavio: 4 Destro Rams

Zone: Thunder Mountain: 12.10.2019 21:50

**Steps to reproduce the problem:**
I dont know

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/46071136/66707125-2a98fa00-ed3c-11e9-84a7-fc9a578ce332.png)

**Comment by Psychoxell** [comment]
22:45 again
Thunder Mountain
![image](https://user-images.githubusercontent.com/46071136/66707524-0f30ed80-ed42-11e9-8a06-1ce468e559bd.png)

**Comment by Psychoxell** [comment]
22:48 Same Zone
![image](https://user-images.githubusercontent.com/46071136/66707551-6d5dd080-ed42-11e9-8d93-8ca085256b8e.png)

**Comment by Psychoxell** [comment]
![image](https://user-images.githubusercontent.com/46071136/66707565-b9a91080-ed42-11e9-8e4c-a977d6775381.png)

**Comment by Natherul** [comment]
what rank was the keep at? Its technically possible atm to get 4 rams

**Comment by Psychoxell** [comment]
I think it was a 2 star keep from the destruction. But i am not 100% sure. So i will close this ticket and will reopen it if i see it again and its not a 4 star keep. Thanks for your reply.

**Comment by Psychoxell** [comment]
If found my screen shot in the pc. Destro Keep was 0 Star.
![Unbenannt](https://user-images.githubusercontent.com/46071136/66761763-eecd7400-eea4-11e9-9e7c-5d42094dae69.png)

**Comment by Natherul** [comment]
one of the possibilities this worked is now fixed pending.

**Comment by sioding** [comment]
fixed with patch from 28.10.2019
