### ISSUE TITLE
Character naming glitch/abuse

### ISSUE THREAD

**Issue by OndeTv** [WarEmu/WarBugs#15021]
**Expected behavior and actual behavior:**

Expected behaviour:
Character names only consist of legal characters, and the character creator as well as the changename feature should check for and/or clear any illegal input.

Observed behaviour:
Person seemingly had a carriage return in the name.

Observed issues:
- The character was untargettable by interface addons. Normal mouseclick targetting still worked.
- The character could not be kicked from a warband. The warband had to be reformed to remove the person
- I suspect a name such as this could potentially cause a multitide of other problems

**Steps to reproduce the problem:**
- Unknown. My guess would be that the person either copy pasted the name from another application or perhaps used f ex a unicode escape sequence or similar. It could also have been a bug that happened unintentionally.

**Testing Screenshots/Videos/Evidences (always needed):**
Screenshot of the name in question, a chosen on destro side: https://i.imgur.com/OaQYunn.png

**Comment by sioding** [comment]
fixed with patch from 19.10.2019
