### ISSUE TITLE
[Quest] Faith in Madness - Wrong marker-location

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#15026]
Step 8.
Marker should be at Chap 21, but it's placed further north.
![Zkyr_047](https://user-images.githubusercontent.com/40274248/66682101-75e7d580-ec74-11e9-9efe-604806f227fd.jpg)

**Comment by Rockalypse** [comment]
Will be fixed next patch

**Comment by Natherul** [comment]
should be fixed as of today
