### ISSUE TITLE
Slayer - reckless gamble not working properly

### ISSUE THREAD

**Issue by komar9220** [WarEmu/WarBugs#15023]
**Expected behavior and actual behavior:**

"reckless gamble" don't up your damage from furious and berserk

**Steps to reproduce the problem:**

enrage should increase "reckless gamble" damage by 25% and 50%

**Testing Screenshots/Videos/Evidences (always needed):**

![Pochemu_016](https://user-images.githubusercontent.com/44377813/66640752-355f6c00-ec22-11e9-83b5-edffb51d35f9.jpg)

![Pochemu_019](https://user-images.githubusercontent.com/44377813/66640920-76578080-ec22-11e9-909a-8398f2464273.jpg)

![Pochemu_020](https://user-images.githubusercontent.com/44377813/66641008-95eea900-ec22-11e9-8910-15e5df1cecaa.jpg)

**Comment by barfyman92** [comment]
they tried fixing this ability + riposte and make it scale, this broke reckless gamble and made it procc a whole bunch of stuff even on yourself.

here is the related ticket
https://github.com/WarEmu/WarBugs/issues/13994#issue-439808208

**Comment by wargrimnir** [comment]
This is how it works now.
