### ISSUE TITLE
Trophy (Destro) - Chattelbind - no longer wearable

### ISSUE THREAD

**Issue by GreatHarlequin** [WarEmu/WarBugs#15027]
My Witch Elf used to wear the trophy, Chattelbind, which look like a pair of handcuffs when worn (so PERFECT for a Witch Elf.)

Logged on today and the trophy was in my bag and I'm now unable to wear it anymore.

I know it's trivial, but you HAVE to look good on the battlefield. ;)

Cheers!

**Comment by Lheana** [comment]
Nothing wrong with this, Chattelbind is now restricted to Blackguards only, like it should be.
