### ISSUE TITLE
 The Essence of the Fallen

### ISSUE THREAD

**Issue by Reconsniper** [WarEmu/WarBugs#15022]
The Quest  The Essence of the Fallen is Missing the Dwarf Skull. I have search all over the area in Cinderfall that is marked on the map and did not find the deanimated skeleton for the Dwarf Skull. I did find the other 2. This quest is missing the 3rd part for the Dwarf Skull.
![Yogibear_000](https://user-images.githubusercontent.com/47046345/66609765-e238db00-eb87-11e9-8e0e-de08edafc6c2.jpg)

**Comment by Lheana** [comment]
Nothing is missing here. Search harder.
