### ISSUE TITLE
[AM] Transfer Magic

### ISSUE THREAD

**Issue by blechkautz** [WarEmu/WarBugs#15020]
If you slot Transfer Magic (AOE AP Drain) it should drain 30 Ap from all targets every 3 seconds. But at the moment it only drains 10 every 3 seconds. In the Video, the first one is without the tactic, draining 60 ap every 3 seconds like it should, the second one is with it draining only 10 ap.
https://youtu.be/7qytkMuJFiU

**Comment by grunbag** [comment]
fixed with next patch

**Comment by Lheana** [comment]
It should have been fixed with the patch of today.
