### ISSUE TITLE
Keep Defense Quest(Defend Wrath's Resolve) Bug

### ISSUE THREAD

**Issue by Cesi-123** [WarEmu/WarBugs#15035]
Since I believe two patches ago there has been an issue turning in the quest to defend Wrath's Resolve in Caledor.  The quest is able to be picked up and credit is able to be gained toward it, however you are unable to turn it in.  The NPC for it will not allow you to turn it in once completed, and the quest tracker sends you to Reikwald.  I went out to Reikwald to take screenshots of the quest directing you there, the map showing where the turn in is, and there being no NPC to turn the quest in at.  I do not know if this affects Order, but Destruction is unable to complete the quest at this time.

https://cdn.discordapp.com/attachments/462359378687688706/632991328615137313/unknown.png

https://cdn.discordapp.com/attachments/462359378687688706/630626001570758676/unknown.png

https://cdn.discordapp.com/attachments/462359378687688706/630626038556262400/unknown.png

https://cdn.discordapp.com/attachments/462359378687688706/630640737494499358/unknown.png

https://cdn.discordapp.com/attachments/462359378687688706/630640779681071104/unknown.png

**Comment by sioding** [comment]
fixed with patch from 19.10.2019
