### ISSUE TITLE
No rewards issued after winning fort

### ISSUE THREAD

**Issue by p12om3th3us** [WarEmu/WarBugs#15031]
Expected: Issue Invaders medals, RR, & loot role.
Actual: Sever crash and no rewards after login

-Killed Fort lord @ Stonewatch, resulted in server crash

On Sunday Oct 6th approx 630pm Destro won the fort Stonewatch. Upon Killing the Lord the server crashed. After logging back in the campaign was reset and no rewards were issued. Confirmed same result by other attendees. Requesting to be granted Invader medallions, RR, and loot rolls from winning Fort.  On account "p12om3th3us" on character "Zharroth Kinslayer."

Submitted via GM appeal prior but was instructed to use bugtracker.

**Comment by Natherul** [comment]
if a server crash occurred there is no way that the server can dish out rewards or save that into the database. 

Also as a general note we dont give any items here, thats solely up to GMs discretion. This is just for finding and eradicating bugs.

**Comment by Natherul** [comment]
no more comments, closing ticket
