### ISSUE TITLE
Warcamp Resource Drop issue

### ISSUE THREAD

**Issue by Zalamir** [WarEmu/WarBugs#15036]
Hi Doglog here from Destro side.
 I have been aware of a issue within the war camps in the RvR Zones, When you pickup a Resource you can hand them in at the keep, but it does not allow you to hand it in at war camp at any Certain time... this has been happening and i see new players trying to hand in supplies for there Zone and they cannot and i have to whisper them to tell them you can only hand them in at keep, so i am just addressing this now to let you all know of this Bug issue.
Regards
Doglog

**Comment by sioding** [comment]
The ressource drop at the warcamp (we are talking about t2-4) is only usable when the own keep is captured. Yes its different - but not a bug. If you wanna change it you are more than welcome in our suggestion forum.
