### ISSUE TITLE
Bug with staff

### ISSUE THREAD

**Issue by Wagrash** [WarEmu/WarBugs#15030]
I cant change talisman in my staff
![Gimbur_000](https://user-images.githubusercontent.com/16164209/66708100-13fe9d00-ed54-11e9-96c1-1d82b87bd77d.jpg)
![Gimbur_001](https://user-images.githubusercontent.com/16164209/66708101-13fe9d00-ed54-11e9-9c1a-0bda5d7ddca9.jpg)
![Gimbur_002](https://user-images.githubusercontent.com/16164209/66708102-13fe9d00-ed54-11e9-907e-99388de2ba92.jpg)

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Wagrash** [comment]
relog doesnt help

**Comment by Lheana** [comment]
To be clear, what do you wanna do exactly? You wanna put 2 willpower talis on the same staff?

**Comment by Wagrash** [comment]
I tryed to change +18 will on +23 will
Okay, I find solution - I took one small tali on wounds
