### ISSUE TITLE
Boss kill not registering 

### ISSUE THREAD

**Issue by Docglue** [WarEmu/WarBugs#15039]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:** 

We just killed Arathremia in Mount Gunbad. And the game didn't register her death and didn't reward and loot for the kill. This is now preventing us from progressing to the next boss in this area since the portal isn't disappearing 

**Steps to reproduce the problem:** 

None taken since there is a lock out and I dont have a group to go in and kill her again 

**Testing Screenshots/Videos/Evidences (always needed):**

![Docgluetank_004](https://user-images.githubusercontent.com/56568170/66791818-1698f800-eef6-11e9-958b-691da2b2ee12.jpg)

In this screen you can see her dead and you can see the counter in the top right corner says she isn't dead and is still counting down.

**Comment by sioding** [comment]
This is not a bug - its a player behaviour problem. Just make sure the bos didn't get killed by one of the spawned NPC´s and you don't have a problem. Correct aggro management helps  a lot here.
