### ISSUE TITLE
Replacing talismans of same type no longer possible

### ISSUE THREAD

**Issue by Eivonz** [WarEmu/WarBugs#15032]
It is no longer possible to replace/overwrite talismans of same type in gear.

Related to patch released 12/10-2019.

Example:

1 Slotted talisman of +101 armor, can no longer be overwritten be a talisman of same type.
![image](https://user-images.githubusercontent.com/40267298/66712699-e3912000-eda0-11e9-99f0-4113e4a3268e.png)

**Comment by sioding** [comment]
fixed with patch from 19.10.2019
