### ISSUE TITLE
New Patch Bug 13/10/2019 - Game Close 

### ISSUE THREAD

**Issue by Zalamir** [WarEmu/WarBugs#15034]
Hi Doglog Choppa Destro side
Since the new update has taken place, i have had a issue and many others have, where you are in a big fight and the game loses connection and kicks you to your home screen and the game closes.
Can you check to see if you can produce a hotfix for this @Natherul Requested me to Report this to Bugtracker. Date today 13/10/2019
Regards
Doglog

**Comment by sioding** [comment]
TBH i am not sure about the fact that Nath said put this in a report, cause this will be more than hard to reproduce. Maybe he will find "things" in the logs but it would be nice to have some exact date+time so one of the devs can have a chance to find something.

**Comment by Zalamir** [comment]
Yesterday about 2:35pm

**Comment by sioding** [comment]
:) what timezone? and to make it more valueable - you said "many others" - since this is the only report about it - its... sorry but we need more information. I will leave it open for two weeks - if no more input is given to reproduce it, i have to close it

**Comment by Zalamir** [comment]
2:30pm English time from uk, and many others in advice chat have been crashing since new update

**Comment by Tazo83** [comment]
i can confirm this issue am getting a lot of disconnect in middle of SC or sometime when i click join SC i get lost connection and am back to character select screen and of course with Quitter debuff
