### ISSUE TITLE
Beastlord quests bugged and tokens missing

### ISSUE THREAD

**Issue by BuzzShaman** [WarEmu/WarBugs#15037]
My mara, Zymran, had 3 tokens from the beastlord questions, and the 2 quests for the last two lair boss kills, dissapear from inventory and ToK.     I also cant re-get any of those quests again from the questgivers.   please help :)

**Comment by sioding** [comment]
Quests don't vanish without interaction. The description is not enough to reproduce it. Name of the quests are missing - the ones you've already done - and the ones you are "missing". At the end - i don't believe that these quests are going "boom" bei themself. IF we had these problems the bugtracker would explode.

**Comment by Kabucoror** [comment]
no answer for a month. close
