### ISSUE TITLE
Grey Sir Quol'Tik (Skaven dungeon)- No loot attribution after loot window

### ISSUE THREAD

**Issue by tekkytekk** [WarEmu/WarBugs#15047]
Hello,
Yesterday, we killed Grey Sir Quol'Tik with my group (10/19/19), he dropped Kotb sentinel helm and WH sentinel hat.
Nobody but me needed during the loot roll for the WH sentinel hat.
The kotb appeared in my bags (after greed roll) and the WH never appeared (nor in the chat window). The WH has never been attributed.
I've got screenshot to prove it... Is there any chance I get my hat again ?

Thank you

**Comment by tekkytekk** [comment]
![Tekky_098](https://user-images.githubusercontent.com/56788576/67158329-202bc100-f337-11e9-818a-7a6f32ff2c61.jpg)

**Comment by grunbag** [comment]
this happend when ppl have lockout
