### ISSUE TITLE
Improper Medallions Rewarded

### ISSUE THREAD

**Issue by Flavor-burst** [WarEmu/WarBugs#15040]
**Expected behavior and actual behavior:**

Seemingly people rr51 and over drop Conq when they are killed instead of at least Vanq.

**Steps to reproduce the problem:**

Killed some rr80 dudes 'n stuff.

**Testing Screenshots/Videos/Evidences (always needed):**

_RR 80+_
![image](https://user-images.githubusercontent.com/39884574/66936658-14c15880-f00c-11e9-87b9-c0658ec0c863.png)

_RR 80+_
![image](https://user-images.githubusercontent.com/39884574/66936738-328ebd80-f00c-11e9-8ed9-356a423ed472.png)

_Skorpion is over rr60 and Itv is over 50_
![image](https://user-images.githubusercontent.com/39884574/66937764-0ffda400-f00e-11e9-891b-5c1798eff0cc.png)

**Comment by SecretsOTheP** [comment]
It's only a chance at giving a Vanquisher drop. Working as intended.
