### ISSUE TITLE
Warrior Priest Mastery Tactic Divine Jusice doesn't work.

### ISSUE THREAD

**Issue by Rilos** [WarEmu/WarBugs#1504]
Tested it out today.  The tactic is supposed to do % more damage for Prayer of Righteousness, which has a 20% chance to do extra damage for you and everyone affected by the prayer.  The tactic is part of the Path of Wrath tree for Warrior Priests.

**Comment by ozarmidrashim** [comment]
Correction: It doesn't refresh the existing buff, if any.
