### ISSUE TITLE
[Ability] Malignant Strike

### ISSUE THREAD

**Issue by Lindiranae** [WarEmu/WarBugs#15041]
My Dps BG is not able to use the skill "Malignant Strike" while equipt with the Death-Dealer´s Glaive.

Requirement for the skill is to wear a twohanded weapon, the Glaive is, but the skill is always grey and unusable while wearing it.

In the Moment i switched to Bandit´s Glaive it becomes usable.

![Xorna_000](https://user-images.githubusercontent.com/52664952/67071980-35acb980-f184-11e9-9efe-9e41c1ac0de7.jpg)
![Xorna_001](https://user-images.githubusercontent.com/52664952/67071982-35acb980-f184-11e9-8595-d011b32d2bc6.jpg)

**Comment by Kabucoror** [comment]
it's only visual, you are able to use it

**Comment by wargrimnir** [comment]
This was fixed by adding the appropriate Skill to the weapon itself. They were added only using Career. I was not aware of that interaction in the client.

**Comment by Lheana** [comment]
Fixed with patch of 02/11/2019.
