### ISSUE TITLE
[NPC] Silversong Bladsingers in Reikland give the "Target is not attackable" message.

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#15044]
The Silversong Bladesingers at the position you can see on the Minimap give the "Target is not attackable" Message, even though they are part of a quest.

![Rodira_001](https://user-images.githubusercontent.com/30193675/67146195-0633a500-f289-11e9-9463-36742f778a51.jpg)

**Comment by sioding** [comment]
fixed with patch from 28.10.2019
