### ISSUE TITLE
Travel time to target are completely wrong in Squig herder

### ISSUE THREAD

**Issue by Torete-war** [WarEmu/WarBugs#15046]
I have been testing in IC dummies and in NPC, that the travel time to target in Squig herder abilities like "Run ´n shoot" are completely wrong, respect what abilities travel time was in live servers.

Run ´n shoot it is supouse to have a much faster travel time to target, testing in IC dummies and NPC the ability needs 3 seconds to reach target at max distance.
But watching a video from Age of reckoning server in youtube, we can see that the travel time in live server was way faster, than it is in Return of reckoning...

Can be easy tested in return of reckoning, go with your Squig herder to a city dummie and test the travel time is around 3 seconds.

Now, look at this video...the run and shoot travel time to target was like 0,5 sec at max distance or almost instant whith mid distance, the level and equipment doesn't matter, it is about a game mechanic and abilities not matching the real travel time to target.

Example: minute 2:28 look at the distance the Slayer is... and look at the travel time of Run 'n shoot hit (1051 damage hit)
In RoR that travel time takes 3 seconds, the diference it is HUGE and gamebreaking for the class.

PD: probably this is not the only ability in Squig herder which have the travel time to target set completely wrong.

[https://www.youtube.com/watch?v=AcNHwWDJKmA](url)

**Comment by Kaelang** [comment]
A lot of skills have recently been updated to effect visual travel time.

Please re-open if the issue persists.
