### ISSUE TITLE
Quest: "The bloody maul" offers the same rewards

### ISSUE THREAD

**Issue by Aanathema** [WarEmu/WarBugs#15042]
The quest is located at the TROLL COUNTRY at the north base.

**Expected behavior and actual behavior:**
The rewards should be different, so as to be a real choice.

**Steps to reproduce the problem:**
Just pick up the quest and check the rewards.

**Testing Screenshots/Videos/Evidences (always needed):**
![pic1](https://user-images.githubusercontent.com/55383380/67089625-c9947a80-f1b0-11e9-83de-e27276ab98bc.jpg)
![pic2](https://user-images.githubusercontent.com/55383380/67089626-c9947a80-f1b0-11e9-83f7-de09df4d2ad1.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 19.10.2019
