### ISSUE TITLE
[NPC] Non targetable NPCs at Glittering Citadel PQ in Eataine

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#15049]
At the chapter 22 PQ Glittering Citadel in Eataine (dstro side) are two types of NPC that are hostile but not targetable/don't have a name plate. One of them are the Eagles, the other are the Floating Sword and Shield Training Dummies.

![Rodira_000](https://user-images.githubusercontent.com/30193675/67168707-12ae1f80-f3a7-11e9-837b-7142b4f88035.jpg)

**Comment by sioding** [comment]
fixed with patch from 28.10.2019
