### ISSUE TITLE
T3 elf Control (epic quest)

### ISSUE THREAD

**Issue by Lnternsmite** [WarEmu/WarBugs#15052]
on the Saphery side of the quest, the second half of epic quest t3 elf - Control.

Break Gorluks collars
 
I have killed him 5 times and nothing procs
 
Breaks Ulvar, i get the collar break at first kill

this is the second time i go through this quest mob and the exact thing happens, theres no fixed amount of times, it just random . one time was 4, this time it has been 5 so far ( im currently in it)

**Comment by Lheana** [comment]
The quest says nowhere you have to kill these NPCs.
Use the Tear of Isha on them, exactly like the quest says.
