### ISSUE TITLE
[Tooltip] Flashfire states wrong reduction

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#15055]
![flashfire](https://user-images.githubusercontent.com/40274248/67388389-d5a97f00-f598-11e9-9f09-b8d398431aa7.jpg)
FF was changed to a 50% reduction, not instant anymore 
see: https://wiki.returnofreckoning.com/index.php/Bright_Wizard#Class_Changes

**Comment by Natherul** [comment]
should be fixed by now
