### ISSUE TITLE
I have to change the name of my character each time I connect

### ISSUE THREAD

**Issue by Neiv91** [WarEmu/WarBugs#15059]
![prob_WAR_newName](https://user-images.githubusercontent.com/56964682/67486748-dca1c180-f66c-11e9-9250-7691b4ddb1d2.PNG)

In the character menu, every time I connect my black orc, I have to change his name.
I alternate each time with "Krough" and "Khroug"

**Comment by MaxHayman** [comment]
Fixed. Let me know if you have anymore issues.

**Comment by Neiv91** [comment]
It works! Thanks!
