### ISSUE TITLE
Cannot join party/party not showing when joining scenario late

### ISSUE THREAD

**Issue by Rilos** [WarEmu/WarBugs#1505]
Most aggravating bug in the game.  If you join a scenario late, you cannot join a party.

The party window also doesn't show when you use the mini map button.

**Comment by Evildoor** [comment]
Are you sure that this is not connected to known bug when you can't see party members, and try to join a party which turns out to be full? If it is connected, then it has nothing to do with being late.

**Comment by Rilos** [comment]
No, every time it's happened to me the scenario has already started.

**Comment by magter3001** [comment]
Someone in my guild had an issue with the addon FixGit. If you got this, try disabling it and see if that fixes it.

**Comment by Rilos** [comment]
No, I don't use fixgit.

**Comment by gittoaster** [comment]
try joining the 2nd or 3rd party as a workaround.

**Comment by Stefanosgr18** [comment]
Yes you cant join any party if you late to join scenario.

**Comment by Luth-RoR** [comment]
Should be fixed.
