### ISSUE TITLE
2 fort portal on top of each other

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#15054]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**
portal should be separated and not be on top of each other

**Steps to reproduce the problem:**

2 fort in same time from order attacking 2 zone and captured them then 2 portal spawn on top of each other

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/42385505/67333952-1918d480-f52a-11e9-8727-d07ed84b172c.png)

![image](https://user-images.githubusercontent.com/42385505/67333974-21710f80-f52a-11e9-9010-0462b4352f50.png)

![image](https://user-images.githubusercontent.com/42385505/67334049-3f3e7480-f52a-11e9-8daa-6fc3639845f8.png)

**Comment by Kyouaku** [comment]
Destro had this again tonight for the maw

**Comment by Natherul** [comment]
fixed this for future patches. Also system for entry into forts may change in the coming future

**Comment by Natherul** [comment]
should be fixed by now
