### ISSUE TITLE
Game crashes on respawn, flying to other zones, using scrolls

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#15066]
Hello, since the last 2 weeks the game crashes when:

- I fly to a different zone
- I use scroll to guildhall, Gunbad, BS or IC
- (and since today) the game crashes when I click respawn after being killed.

I already did a clean Win 10 install, downloaded the game anew. Got all latest drivers, etc.

**Comment by sioding** [comment]
Nothing we can help here and the bugtracker is only for ingame things. You can find a tread in our forum that give some tipps to avoid crashes.
