### ISSUE TITLE
War Story Storylines

### ISSUE THREAD

**Issue by TiberiusD** [WarEmu/WarBugs#15060]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**

From some time now (I don't remember if it was like that on live or not, I could see that Destruction Storylines are available for Order characters also. Is it intended or is it a bug?

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Bug0000](https://user-images.githubusercontent.com/32936075/67497787-27303780-f687-11e9-9189-26f06808624c.PNG)

**Comment by Lheana** [comment]
Order characters should not be able to unlock chapters/wc for Destro, and vice versa. So it's intended.
