### ISSUE TITLE
Wrong Sword Model for Warrior Priest

### ISSUE THREAD

**Issue by Nekkbraka** [WarEmu/WarBugs#15068]
![bug](https://user-images.githubusercontent.com/47920948/67637505-161b3c80-f8ba-11e9-96b5-6e6fedb4000d.jpg)

Its a 1h hammer whit 2h Sword appearence. 

![bug2](https://user-images.githubusercontent.com/47920948/67637643-4dd6b400-f8bb-11e9-86fe-68e1d2b40808.jpg)

**Comment by Rockalypse** [comment]
Should be fixed next patch.

**Comment by sioding** [comment]
fixed with patch from 28.10.2019
