### ISSUE TITLE
None Shall Pass 30 sec CD

### ISSUE THREAD

**Issue by Eversoris** [WarEmu/WarBugs#15065]
[BG Skill] None Shall Pass is a channel ability that increase block by 50% with 30sec cooldown, 20ap/sec.
[BO Skill] Can't Hit Me is a channel ability that increase block by 50% with no cooldown. 15ap/sec.

Shouldn't NSP have zero cooldown and cost 15ap/sec same as CHM?

![NSPvsCHM](https://user-images.githubusercontent.com/38785407/67611040-11119c80-f797-11e9-9799-f4356ce7af6c.jpg)
(Images are from career builder. In-game NoneShallPass have 30seconds cooldown).

**Comment by wargrimnir** [comment]
Not a bug.

Both abilities work the way they're described.
