### ISSUE TITLE
T1 Cannon Doing Way too Much

### ISSUE THREAD

**Issue by Itmritual** [WarEmu/WarBugs#15063]
Now I may be wrong about this, but this tank went on a Cannon and one shot me and a bunch of other people. It hit me for 1900 damage in t1. It also one shot a Maradaur, Zealot, and someone else.

![Veneficium_002](https://user-images.githubusercontent.com/31557076/67531589-3fa54f80-f691-11e9-8fbf-2b5cc67bb5be.jpg)
![Veneficium_003](https://user-images.githubusercontent.com/31557076/67531602-4c29a800-f691-11e9-8088-474cd6e5876b.jpg)

**Comment by Itmritual** [comment]
Apparently it's also silent according to another person (I don't play with sound)

**Comment by Itmritual** [comment]
His kill count is at 19 from just killing people on cannons - lvl 15 tanks included.

**Comment by sioding** [comment]
Not a bug you were way too near a warcamp - you better don't farm near a WC - you will see this damage near all WC
