### ISSUE TITLE
I dragged invader jewlry to my baf, got a shoulder peice instead 

### ISSUE THREAD

**Issue by Kyouaku** [WarEmu/WarBugs#15064]
Hello! I found out I had enough invader tokens to complete my set, so I went to buy them all and I got the normal pieces just fine. I dragged and dropped all of them in my bag, because Xtose said there was a bug if you just right clicked them, and I wanted to be sure I did this right ha. 

I didn't realize I had to equip the pieces before I could by the jewelry, and went to just buy it last. I dragged it and put it into my bag, in the 2nd bag area I think, and when I did it I ended up with a shoulder piece. I was as careful as I could possibly be through all of this, as I spent so long farming this stuff up =/

**Comment by raptrr** [comment]
https://github.com/WarEmu/WarBugs/issues/15089

**Comment by Kaelang** [comment]
Unable to replicate such issue and haven't seen any similar reports. Sounds like user-error. If you are able to suggest otherwise and/or means to replicate this as a bug within the game, please re-open the ticket.
