### ISSUE TITLE
Dwarf smuggler 2H weapon has incorrect DPS

### ISSUE THREAD

**Issue by Skullgrin** [WarEmu/WarBugs#15074]
The Subjugator, Doomsday and Smuggler weapons are supposed to be identical (with 79.9 DPS), however the dwarf 2H smuggler hammer instead has a DPS of 77.9. I suspect this to be a typo introduced when the smuggler weapons were added to the game. A screen shot showing this disparity can be found at https://i.imgur.com/3ew8KjX.jpg

**Comment by Flavor-burst** [comment]
This was changed a while back in a patch. It's purposefully lower dps since you didn't win it from a bag.

**Comment by Skullgrin** [comment]
Would like to see the patch note indicating this, as I don't recall seeing it.

**Comment by Skullgrin** [comment]
Would like to see the patch note indicating this, as I don't recall seeing it. Found this patch note from 3/23/19 https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=30934&hilit=smuggler  but it seems to indicated that all three should be identical. also all other 2H weapons of this variety for other classes  that I've come across also have 79.9 as the DPS.

**Comment by Flavor-burst** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=30934&hilit=smuggler

![image](https://user-images.githubusercontent.com/39884574/67725972-a80a6e80-f9ba-11e9-82cf-8c24bf1df6c3.png)
