### ISSUE TITLE
Spider Cape dont have model ( Coppa class )

### ISSUE THREAD

**Issue by Nekkbraka** [WarEmu/WarBugs#15077]
![Nekkbraka_271](https://user-images.githubusercontent.com/47920948/67728288-79e15a80-f9cb-11e9-9376-d82307428d72.jpg)

**Comment by Tazo83** [comment]
![image](https://user-images.githubusercontent.com/42385505/67724732-ff2b3600-f9f0-11e9-9f61-83311c786280.png)

**Comment by MaxHayman** [comment]
I'll leave this open but the asset will be coming soon.

**Comment by Tesq** [comment]
it's for all classes btw

**Comment by Lheana** [comment]
This has been fixed.
