### ISSUE TITLE
Event quest not granting credit/wins

### ISSUE THREAD

**Issue by Flavor-burst** [WarEmu/WarBugs#15078]
**Expected behavior and actual behavior:**
I have spent around 50g doing this quest (The Odds of a Gamble) at the pool in front of the AH in Altdorf and haven't won  / gotten credit once. If it's a 1 in 5 chance to win, then SURELY ~500 attempts and not winning is practically a statistical improbability. I have also used the other pool, won, and not received credit.

Additionally, if someone else is clicking on the same apple, it will take your money while also denying you the attempt.

**Steps to reproduce the problem:**
Clicked on apples, lost tons of gold.

**Testing Screenshots/Videos/Evidences (always needed):**

Here's my gold when starting the quest:

![image](https://user-images.githubusercontent.com/39884574/67723034-24984f80-f9b1-11e9-88bd-89162bc17dd4.png)

Here's my gold, now: 

![image](https://user-images.githubusercontent.com/39884574/67723059-3679f280-f9b1-11e9-9b2b-992fd4617026.png)

**Comment by Flavor-burst** [comment]
Additionally, this isn't a "me" issues, since a few other people have experienced the same thing.

**Comment by Flavor-burst** [comment]
![image](https://user-images.githubusercontent.com/39884574/67723317-fcf5b700-f9b1-11e9-8788-bc3577b0494b.png)

tbh, I don't think anyone is winning a this pool, which seems crucial for the quest to be completed.

**Comment by Flavor-burst** [comment]
Just to add, I have both relogged and left the zone and I am still getting the same results.

**Comment by Flavor-burst** [comment]
Also of note: I HAVE won at this pool, but that was when I was completing the event task, and not during the activation of the quest.

**Comment by Flavor-burst** [comment]
Update: I have finally been able to complete it, but it entailed NO ONE being there, and clicking EVERY single apple in the pool.

![image](https://user-images.githubusercontent.com/39884574/67728539-ee180000-f9c3-11e9-885b-3f0880d04f3b.png)

**Comment by MaxHayman** [comment]
Message me on discord MaxHayman#8344
