### ISSUE TITLE
Most quests don't give any money as reward

### ISSUE THREAD

**Issue by sandreid** [WarEmu/WarBugs#1507]
As far as I know, most quests in live gave some kind of silver, when you completed them. I even think most of them did on RoR up until the Renown Specs were fixed (was it yesterday?). 
But now most quests (Ostland, Shadowlands, Troll Country etc) only gives experience and sometimes an item as well. The only quests that still gives money now are the "Speak to X" quests.

**Comment by Reggaewaldo** [comment]
Good observation, Can you just put some examples in here so that I can have a look that way. Would help very much !

**Comment by Evildoor** [comment]
No response. Also, i don't know about PVE, but most of the PVP-related quests (kill players, fly from warcamp A to warcamp B and speak to NPC) give money. Closing until someone actually provides the quest names.
