### ISSUE TITLE
NEW Event Reward NPC is Bugged

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#15076]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.
**Expected behavior and actual behavior:**

npc should give a new rewards but showing last year keg event still

**Steps to reproduce the problem:**

i reached advanced reward and i cannot take my spider cap

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/42385505/67720542-40b5e400-f9e5-11e9-9059-4b2ee1cf91cc.png)

**Comment by SecretsOTheP** [comment]
Wrong NPC, That's for keg's end. Not a bug.
