### ISSUE TITLE
Renown points bug

### ISSUE THREAD

**Issue by Draftman48** [WarEmu/WarBugs#15075]
Renown point glitch - i do not know how this occurs but in the last 2 days it has happened to myself and my friend. It allows you to spend the points and then when you press train it credits you with same amount of points so it allows you to max out your renown on char potentially. As a side bug it wont let you spend points on  mastery trainer and just says your at maximum.  I am guessing alot of players wont be honest and report this bug guys.   If this has been helpful for you can i be credited my mount on my Iron breaker  - solous.  
Great game btw
Thanks 
Draftman

**Comment by Scophis** [comment]
Do you check with .getstats if you got the stats for real? 
There is a similar known bug, that the rr-trainer bugs out when not targeting the npc while you press train. But it's only a visual bug and resets after a relog. see #13603

**Comment by Natherul** [comment]
I need more details, if possible video, though if you do this please send it to me on disccord personally and not here.

**Comment by Draftman48** [comment]
Hi...its random and i did not video it unfortunately as wasnt sure why it
happens...it basically reset my spent points so i could keep using them.  I
respecced and logged off and it wouldnt repeat.

I hope that helps

Draftman
