### ISSUE TITLE
Bug in merchant invader ring

### ISSUE THREAD

**Issue by Valdarys** [WarEmu/WarBugs#15089]
Yesterday, when I went to buy the invader jewel, I had to make two clicks with a question included if I was sure I wanted to buy it, to my surprise a helmet appeared in my bag (I already had the whole set except the ring), lost the 37 medals that equate to the helmet and without being able to get the jewel. I hope for a solution to that, thanks.

**Comment by wargrimnir** [comment]
Did you have "The Invader" title already? It's a requirement to buy the ring.

**Comment by Valdarys** [comment]
Yes
![1573488425895](https://user-images.githubusercontent.com/56538548/68601997-cc2f7a80-04a5-11ea-81f5-427ed64f649e.jpg)
