### ISSUE TITLE
[Item] Barbed Kahle trophy cant be equiped anymore

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#15082]
The Barbed Kahle trophy can't be equipped on my marauder, even though the requirement is Race: Chaos and nothing else.

![Drachdon_000](https://user-images.githubusercontent.com/30193675/67861944-84ae0380-fb21-11e9-895b-c172111e4c8a.jpg)

**Comment by Lheana** [comment]
Not an issue, class restriction has been set on several trophies like it was on official.

**Comment by Moragor** [comment]
In this case the tooltip needs to be fixed.

**Comment by Lheana** [comment]
Are there any trophy IG that have career restriction?

**Comment by Lheana** [comment]
Career restriction should appear with next patch on trophies.

**Comment by Natherul** [comment]
should be fixed as of today
