### ISSUE TITLE
Can read enemy /say chat

### ISSUE THREAD

**Issue by bschmucker225** [WarEmu/WarBugs#15080]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

I didn't see anyone else posting on this so I thought I would.  

**Expected behavior and actual behavior:**

Enemy /say should be hidden.  It is not.  

**Steps to reproduce the problem:**

Talking in /say

**Testing Screenshots/Videos/Evidences (always needed):**
Read the /s conversation between Thrurbim (one of my characters) and Railroadman (destro character)
.  
<img width="353" alt="enemyslashsay" src="https://user-images.githubusercontent.com/45979606/67739712-9e8c0100-f9d0-11e9-87d4-396b08331e73.PNG">

**Comment by Natherul** [comment]
spooky
