### ISSUE TITLE
Opposing Faction items dropping

### ISSUE THREAD

**Issue by Skullgrin** [WarEmu/WarBugs#15087]
Since the last patch the loot tables seem to have been corrupted and now armor and weapons meant for the opposing faction are dropping, at least on the order side. I noticed this while farming level 39-40 squigs in Black Crag. Out of the 6 items that dropped while farming, 5 were for destruction classes. Screen shots of the items dropped are at - 

https://i.imgur.com/eiwj5f9.jpg
https://i.imgur.com/hnlAIgu.jpg
https://i.imgur.com/olSdXlZ.jpg
https://i.imgur.com/DC8Tm8I.jpg
https://i.imgur.com/vCtgfK0.jpg
https://i.imgur.com/BxYyg33.jpg

**Comment by wargrimnir** [comment]
I found some discrepancies in the event push. Whether clearing up those items fixes the incorrect drops, we will find out next patch.

**Comment by Lheana** [comment]
I guess this is fine now.
