### ISSUE TITLE
Image of object error

### ISSUE THREAD

**Issue by Farlopa** [WarEmu/WarBugs#15088]
Yesterday all was okey but this morning when i log in game that happens to my subjugator weapon.
I dont knwo how happens but its there

https://imgur.com/a/1vwuAkU

**Comment by Lheana** [comment]
Server has been patched, is the issue still there?

**Comment by Farlopa** [comment]
yes it is

**Comment by Lheana** [comment]
Are you using another appearance for your weapon?

**Comment by Farlopa** [comment]
looks like this is the appearance but i dind´t put it there hah just appear when i log this mroning.
https://imgur.com/a/WGGqKl3

**Comment by Lheana** [comment]
I ignore how you had this item, but as a SW you should not be able to equip it. I guess that if you remove it from your appearance, it will fix everything

**Comment by Farlopa** [comment]
i ignore that too but ye if i unskin that all go to normally but that object still been bugged with a no correspondent skin

**Comment by Lheana** [comment]
Can you reequip it now?
