### ISSUE TITLE
Stingy Jack Quest line not completing in Event Log

### ISSUE THREAD

**Issue by Lardglob** [WarEmu/WarBugs#15081]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**
**Expected**: 
Finish first part, talking to Bawon in Crypt should finish Tavern Rumors.
Finish the 6:th entry, The Odds of a Gamble, should fill criteria in quest log.
**Actual**:
Did not complete Tavern Rumors.
Was able to continue with Convince the Unconvinced.
Was able to progress to The Odds of a Gamble and complete it.
The Odds of a Gamble, nor any other entry, was updated in Event quest log.

**Steps to reproduce the problem:**
Completed Tavern Rumors on first try. Made two tries on Convince until I found Jack.
Completed the rest within the time limits on first try.
Completed quest 12 hours ago from writing this post. Have re-logged and restarted several times.

**Testing Screenshots/Videos/Evidences (always needed):**

![Lardglob_000](https://user-images.githubusercontent.com/57138155/67766241-4a276680-fa4e-11e9-9c82-4406d2def6cd.jpg)

**Comment by Lardglob** [comment]
Addition: After relog, quest log 2 to 5 was filled(as well as the Tombstones and Scream and Howl), but not 1 and 6. Unable to access Herald or continue with repeatable quests.

**Comment by MaxHayman** [comment]
Can you message me on discord MaxHayman#8344

**Comment by demonzar1** [comment]
I have the same problem

**Comment by Lardglob** [comment]
Resetting the first quest didn't solve the issue. Since step two is finished(for me atleast), the quest target (Bawon) is not there any more(Crypt), so I am unable to finish the first step(Tavern Rumors). He's not in the Char & Bones either, nor Jack for that matter.
I guess the only solution is to reset the quest line entirely, but we haven't gotten around doing that yet(been a bit out of sync with gm's online time because of kids and work and all that other unimportant stuff :P )

**Comment by Iamwithstupid** [comment]
I have same problem missing only 6th entry The Odds of Gamble

**Comment by Lardglob** [comment]
After a little dev help restarting the questline, I was able to complete everything. Had to relog still to receive the event log update, and the last quest bug was my bad, thinking the quest line was over since I didn't receive a new quest from the drinking part, automatically. Thanks for the help, Max!
