### ISSUE TITLE
[Bloodlord Runesash Runepriest] Doesn't count as pieces bonus.

### ISSUE THREAD

**Issue by Misteria** [WarEmu/WarBugs#15085]
Hello,
It seems the Bloodlord Runesash doesn't count in bonus pieces. 
![image](https://user-images.githubusercontent.com/57212731/67929250-2a628080-fbbd-11e9-9d3b-60b3596a0c1a.png)
In this picture, I have 5 Bloodlord pieces with the belt, but I have only 4 bonus. And we can see, even if the belt is equiped, it's not green in the list.

**Comment by Lheana** [comment]
Fixed with patch of 02/11/2019.
