### ISSUE TITLE
Vanquisher vendor in Altdorf

### ISSUE THREAD

**Issue by deryls82** [WarEmu/WarBugs#15095]
Hello, The vendor in Altdorf asks for conqueror's emblem instead of vanquisher emblem
![bug](https://user-images.githubusercontent.com/57384062/68179923-0377c600-ff92-11e9-8202-03ba065a1d39.png)

**Comment by Rydiak** [comment]
Those are the Conqueror weapons.  The NPC just has an incorrect title.  The Vanquisher vendor is further south, past the target dummies.

**Comment by Lheana** [comment]
This should have been fixed with patch of 22/02/2020.
