### ISSUE TITLE
Killed instantly when killed someone in SC College of Corruption

### ISSUE THREAD

**Issue by xaraxdestr** [WarEmu/WarBugs#15093]
If you kill someone near the flag in SC College of Corruption you will be killed instantly with message: "You killed someone in their spawn and the gods are angry with your dishonor"

![Knochenschild_044_1](https://user-images.githubusercontent.com/45398873/68157472-ff29b980-ff4d-11e9-8703-b2b99e8e7bbf.jpg)

**Comment by Natherul** [comment]
should be fixed as of today
