### ISSUE TITLE
Eletromagnet pulling behind walls.

### ISSUE THREAD

**Issue by Nekkbraka** [WarEmu/WarBugs#15096]
Ok guys...

Since yesterday i noticed Magnet skill is pulling ppl in higher places like Praag elevated places and Battle of Praag Mid walls.

-First pic you can see me behind the wall , a tank in front and zealot on the right. ( both are ok to be pulled cause of no cover)
![pull1](https://user-images.githubusercontent.com/47920948/68238214-7a8b7980-ffe7-11e9-9003-d8849f4a87cd.jpg)

-Second pic we can see clearly  me, tank and zealot pulled to the same spot.
![pull2](https://user-images.githubusercontent.com/47920948/68238317-b1618f80-ffe7-11e9-9315-2a5e2d6b045e.jpg)

**Comment by wargrimnir** [comment]
Masterful artwork, but this sort of report will need a video to provide necessary details.

**Comment by Natherul** [comment]
also same as https://github.com/WarEmu/WarBugs/issues/10889
