### ISSUE TITLE
can`t see my buggage

### ISSUE THREAD

**Issue by ScubiDoo** [WarEmu/WarBugs#15099]
i can`t see my buggage. when i opened it, it doesn`t show me any items and its very shifted in itself. it happened after a server restart before yesterday.

![Scubi_000](https://user-images.githubusercontent.com/57476267/68371843-de28ba80-013f-11ea-8747-5b80ef664e6e.jpg)

**Comment by Kabucoror** [comment]
There are some files missing. Run the launcher again should fix the problem.
