### ISSUE TITLE
High Elves T3 Epic Quest Control

### ISSUE THREAD

**Issue by Kiefergruss** [WarEmu/WarBugs#15092]
I'm not able to perform step 13 from the wiki from subjects epic quest which is:

Travel to Saphery,
use the item 'Tear of Isha' on NPCs:
- Gorgluk Foulbreath at 56k/8.2k
- Ulvarr Scorchspell at 55.5k/33.2k
Speak to Irendar Goldenbrook at the Chapter 13 when done. 

Neither on Gorgluk nor on Ulvarr the item Tear of Isha is working.
Tried this with two different characters on different machines without success.

br
![Meves_001](https://user-images.githubusercontent.com/56954283/68131164-d63d0080-ff1c-11e9-8c2f-0e9882d2e93e.jpg)

**Comment by Lheana** [comment]
![Uploading Lheana_116.jpg…]()
