### ISSUE TITLE
Crash in Sturmvall

### ISSUE THREAD

**Issue by NikotinKilla** [WarEmu/WarBugs#15097]
**Expected behavior and actual behavior:**
When playing as Chaos Chosen, game constantly crashes when entering Sturmvall location (crossing the bridge after Chaos camp). Before crash there is (sometimes) scratching sound coming from earphones. 
Note, that it seems that game crashes only around location with peasant houses burning. Moving around that zone (approx. 20-50 meter away) is ok. 

**Steps to reproduce the problem:**
1. Launch game as Chosen in Sturmvall in area near burning houses (Sturmvall_1.png)
2. Wait 5-15 seconds
3. Observe crash appear (Sturmvall_2.png)
Repro rate is 100% on my PC

**Testing Screenshots/Videos/Evidences (always needed):**
![Sturmvall_2](https://user-images.githubusercontent.com/57453104/68317695-3de18000-00c4-11ea-8b6e-020a88e2c965.png)
![Sturmvall_1](https://user-images.githubusercontent.com/57453104/68317696-3e7a1680-00c4-11ea-9cf5-5c51be359494.png)
[DxDiag (3).txt](https://github.com/WarEmu/WarBugs/files/3815670/DxDiag.3.txt)
[debug.log](https://github.com/WarEmu/WarBugs/files/3815680/debug.log)

**Comment by Lheana** [comment]
It must be related to your files and it's not a general issue. Please read our forum for game support.
