### ISSUE TITLE
Read "Say" chat from other side

### ISSUE THREAD

**Issue by xaraxdestr** [WarEmu/WarBugs#15094]
As Destro you can read "Say" chat from order player since last patch. Don't know if this is intended.

As example you see chat from Imightprotect which is a Runepriester while i'm on my BG:

![Knochenschild_045_1](https://user-images.githubusercontent.com/45398873/68158346-ba9f1d80-ff4f-11e9-9711-2732a3d9e8bc.jpg)

**Comment by Lheana** [comment]
It is intended.
