### ISSUE TITLE
Outta my way has collision detection now

### ISSUE THREAD

**Issue by NANYABIDNESS** [WarEmu/WarBugs#15090]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**

Outta my way should (and did ) knock people  down when you run through them. 
Now you just run into them and stand there

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by raptrr** [comment]
Can you provide some kind of Video and/or screenshots?
