### ISSUE TITLE
Zealot Lashing Waves Tactic Not Working

### ISSUE THREAD

**Issue by Itmritual** [WarEmu/WarBugs#15091]
The Zeal's Lashing Waves tactic is not working. When I equip it, I get an error message saying "Nonexistent Tactic: 8599 Lashing Waves". It's in my chat in the screenshot linked below.
![Mitzie_030](https://user-images.githubusercontent.com/31557076/68100257-13f64680-fe95-11e9-827c-cbf8d30984ff.jpg)

**Comment by Scophis** [comment]
see #11439

**Comment by Natherul** [comment]
fixed as of patch just now
