### ISSUE TITLE
Liniment

### ISSUE THREAD

**Issue by turki79** [WarEmu/WarBugs#15109]
i use Liniment after joining sc i lose it

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by turki79** [comment]
also a ws and str drop by 150 but maybe its visual bug

**Comment by raptrr** [comment]
Can you provide some kind of screenshots? Best would be UI & more with your stats.
E.g.: Your .getstats without potions / liniment and with (before and after SC as well)
