### ISSUE TITLE
apothecary dont work 

### ISSUE THREAD

**Issue by ssdomenicanes** [WarEmu/WarBugs#15100]
on both sides order and destro i cant lvl apothecary higher than lvl 25, for each potion i have to restart the whole game and if its a green one i got nothing in inventar if crit blue pot i got 1 extra try bevore restart game again ...

**Comment by ssdomenicanes** [comment]
i have testet a lot ... if i take some other seeds to change maybe from str to int it will work.. ty

**Comment by raptrr** [comment]
Can you provide some more information (eg. screenshots). Like what kind of seeds & so on?
