### ISSUE TITLE
Sentinel Boots Missing

### ISSUE THREAD

**Issue by Itmritual** [WarEmu/WarBugs#15107]
I was in a BB/BE run and it dropped the Sent boots for me. My backpack was full but it still said I received it when I didn't. The three boots in the bottom right corner of my inventory are not Sent, it's the Vanq, Bloodlord, then Vanq (Yes, two) boots. I have also checked my bank but no boots.
![Mitzie_040](https://user-images.githubusercontent.com/31557076/68506218-21b22000-0237-11ea-8f24-a8b2bdbca0a4.jpg)

**Comment by Kabucoror** [comment]
If we would have a general problem with loot rolls the bugtracker would be full of it. I let this open for two weeks maybe someone has the same problem.
Note: We don't hand out any items of whatever reasons.
