### ISSUE TITLE
Mara grab

### ISSUE THREAD

**Issue by yacoucou** [WarEmu/WarBugs#15104]
The marauder grab seems have been reworked ?

Now, since you re in range and launch the grab, target is inevitably grabed to you even if they run 200 feet away.
Is that working as intented ? 
I'm playing mara myself and can't blame this boost ... but feeling bad pulling players from 150/200 feets :=)
enjoy

**Comment by Rydiak** [comment]
It is certainly possible to run out of the range of Terrible Embrance, as I do it constantly.  The tooltip range is 65ft, but I don't know if that is the  max distance at which you can activate the ability on a player, or the max distance the target can run before they out-range it.

**Comment by wargrimnir** [comment]
I'll need to see this repeatable, It should release when they run out of range. If the situation was laggy then anything could happen.

**Comment by lasabur** [comment]
Its also still pulling through terrain , ill get some ss

**Comment by SilverWF** [comment]
Can confirm this. 
Just get in range to start cast, right after animation has started, turn away and run from target, while casting. 
Your target can run away from you too.
When animation would be ended - your target would fly to you, even if there will be visible huge distance between you two, like 100 or even more.
Did this by myself at scenarios or in rvr, and also being the victim of such mega pulls.
Most likely related to all movement changes made so far.

**Comment by BomblingTV** [comment]
Not sure if this is the case you are mentioning, but it seemed and felt aweful to be on the recieving end of a pull like that
https://clips.twitch.tv/BelovedAltruisticInternBIRB

**Comment by dalen** [comment]
This has been fixed now
