### ISSUE TITLE
Can't use high lvl items in new SC bracket

### ISSUE THREAD

**Issue by tomaslumba** [WarEmu/WarBugs#15108]
Hi, im lvl 39 and can't use lvl 38 potions and mounts in SC. Prolly beqause of the new bracket system.

This is for sure a game breaking bug xD

Kind regards!

**Comment by tomaslumba** [comment]
Also nullified my potions i had Active before joining SC.

**Comment by SecretsOTheP** [comment]
Fixed in a future hotfix.

**Comment by tomaslumba** [comment]
Great, thx a lot :) 

Now about the game-breakingness of this… - any bug-token-mount on the horizon? :)

Keep up the great work!
