### ISSUE TITLE
Shadow warriors stances

### ISSUE THREAD

**Issue by Elfacho** [WarEmu/WarBugs#15116]
Hello, shadow wariors stances arent changed properly. When i try to switch one of them, especially during scenarious, it doesnt work, skills which dont need stance are avalaible, but the wanting stance dont be switched. It happens sometimes, not everytime. But it confusing and depends on efectivness in pvp. Please, help with this techical problem, sw is my favorite class in this game and i wouldnt want to change it.

**Comment by raptrr** [comment]
Please provide some kind of screenshot or video (best)? Is there a sepcial order in  switching stances or random?

**Comment by raptrr** [comment]
https://github.com/WarEmu/WarBugs/issues/8878
