### ISSUE TITLE
[Item] Blackguard trophy missing for the quest Birds of a Feather

### ISSUE THREAD

**Issue by Moragor** [WarEmu/WarBugs#15110]
The Dragonseye Pendant should be Black Guard exclusive, but it's equipable for all races. This is one of the class trophies from the starting area that recently have been class restricted.

![Sorelia_000](https://user-images.githubusercontent.com/30193675/68532955-1557c100-0324-11ea-90af-1dd492874565.jpg)

**Comment by Lheana** [comment]
No, it is meant to be general for all destro races ([Dragonseye Pendant](https://web.archive.org/web/20131027233013/http://war.allakhazam.com/db/quest.html?warquest=42012) / [Dragonseye Pendant](https://web.archive.org/web/20080916100123/http://www.wardb.com/item.aspx?id=88856)).
Nevertheless the trophy for blackguard was missing for this quest, so I added it.

**Comment by Natherul** [comment]
fixed as of patch just now
