### ISSUE TITLE
Serpent's Passage, stuck at spawn camp

### ISSUE THREAD

**Issue by Dekoupwar** [WarEmu/WarBugs#15114]
This PnJ prevent us to use the stairs because of collision, and when you want to jump near him, you can get stuck

![Crachwar_010](https://user-images.githubusercontent.com/25211854/68543453-7da3b280-03b7-11ea-9022-8b422ec01a0d.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by Natherul** [comment]
fixed as of patch just now
