### ISSUE TITLE
Issue with new fort contribution error message

### ISSUE THREAD

**Issue by CornerbackAC** [WarEmu/WarBugs#15111]
Many players in chat are reporting that they are getting the following message in chat after a fort (Reikwald) just started and people entered the zone from Altdorf or Reikland:
"Since you fled from this fort prior you cannot gain any contribution in this fort"

**Apparently its just a visual bug. We still got rewards!**

**Expected behavior and actual behavior:**
Expected: Message only is shown when you really fled from this fort before
Actual: Message is shown to everyone entering the zone

**Steps to reproduce the problem:**
Enter Reikwald when fort is attacked

**Testing Screenshots/Videos/Evidences (always needed):**

![bug](https://user-images.githubusercontent.com/11341460/68535600-f158a780-0344-11ea-914d-b91b936e088f.PNG)

**Comment by Moragor** [comment]
Fort just ended, we got Renown, Medals and Contribution for the loot roll, so it's just a display error.

**Comment by geezereur** [comment]
I did not get any medals this fort......

**Comment by Natherul** [comment]
as stated the message is always displayed currently and is only visual (there is a block but message is unrelated).

Next patch the message will only be sent if true.

**Comment by Natherul** [comment]
fixed as of patch just now
