### ISSUE TITLE
Apostle's Chalice of Anathema no essence regen in rvr

### ISSUE THREAD

**Issue by RonanWar** [WarEmu/WarBugs#15115]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

Dok 40-74rr.Have problem whis Apostle's Chalice of Anathema!In rvr Apostle's Chalice of Anathema  do not gain 8 soul essence!

**Comment by Kabucoror** [comment]
Unequip and reequip the chalice then it should work
