### ISSUE TITLE
 "Surrender Scenario?" vote bug

### ISSUE THREAD

**Issue by Rotan4403** [WarEmu/WarBugs#15128]
Hi o/

In RoR game i got/found a vote bug.

Before when the vote worked this vote window will faded after end that scenario. 
But now sticked on my monitor...

At the last day 2019.11.11. i played so many run of scenario whit my Witchelf, my desto side ppl started "Surrender Vote" some times. Than it worked fine. 

But today when i logged on whit my Witchelf and started to reorder my UI in LayoutEditor (i was doesnt moved anything just checked the list window) and when i left the LayoutEditor ("no" save)
there will be the "Surrender Scenario" window popped out, and sticked! (It's seems working, coz when i click "yes" or "no" the system give me message. But doesnt happening any more thing.)

Than i logged out and logged in whit my Shammy, he is already got the "Surrender Scenario" vote window (sticked&bugged one).

Than i relog back to my Witchelf, her too instantly got too the "Surrender Scenario" vote window... 
And sticked it... on my monitor... 

I tryed to clicked spamm the "yes" there will be i got crashed...
I think clicked on it 10x times, than the picture freezed.
Next for some minutes i couldn't enter to game. (Logging Window was full blacked & crashed the game again. Message: Authentication failure.. or something like this.) 

Some minute gone, than i succes reentered the game. 
BUT... the "Surrender Scenario" vote window in there instantly... looks like sticked on me. 
(Today i wasn't in any scenario.)

![Vilverin_717](https://user-images.githubusercontent.com/57659211/68655170-ced6b200-052f-11ea-8841-504771bc7b97.jpg)

![Venzo_000](https://user-images.githubusercontent.com/57659211/68655186-dac27400-052f-11ea-8de5-e1158803ac59.jpg)

![Vilverin_718](https://user-images.githubusercontent.com/57659211/68655195-df872800-052f-11ea-89f8-045ea9494534.jpg)

Thank you in advance for your help.

**Comment by sullemunk** [comment]
should be fixed with the automatic 1.1 update
