### ISSUE TITLE
Renown Points

### ISSUE THREAD

**Issue by colintgallagher** [WarEmu/WarBugs#15121]
My character, Roshdon, is RR 23 Chosen and at Arinbjorn Frostheart in the IC it let me spend 60 RR points.
![Roshdon_001](https://user-images.githubusercontent.com/56422919/68550474-0549eb00-03d1-11ea-8270-b3cc0ad8a850.jpg)

**Comment by Natherul** [comment]
seems to be same as https://github.com/WarEmu/WarBugs/issues/15075
