### ISSUE TITLE
high pass cemetery scenario spawning point no protection from guard

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#15123]
Destruction (and may be order?) can attack the scenario spawning point without guard reaction and attack players freely.
![Thorbolt_223](https://user-images.githubusercontent.com/16274785/68567892-679afe00-045a-11ea-9fc5-7d9ab64f44b1.jpg)

**Comment by Kabucoror** [comment]
protected with next patch

**Comment by thorbolt80** [comment]
Hello, since the last update there is no more guard as in 2019
![Thorbolt_016](https://user-images.githubusercontent.com/16274785/98447960-36b2df00-2129-11eb-859f-b7de0fa596a7.jpg)
![Thorbolt_015](https://user-images.githubusercontent.com/16274785/98447963-3b779300-2129-11eb-8068-27685933814f.jpg)

**Comment by dalen** [comment]
That is outside the spawn though. There's two other exits as well that can be used
