### ISSUE TITLE
Kotbs Auras 

### ISSUE THREAD

**Issue by IceandFire1985** [WarEmu/WarBugs#15124]
After last patch i notice some problems with Auras. 
On my lowlvl kotbs i need to remember to rebuff auras after every wc/pve/sc. Today i find that aftec sc i accidentally turn on 4 auras, and all 4 stay activ only on me ( part member got only 3 ). 
![4x auras ](https://user-images.githubusercontent.com/19292844/68590529-0a6d6f80-048f-11ea-8df1-befc6531dfa2.jpg)
After notice it i join sc, and on it i cant pop any aura. To remove bug i need to relog, but after this i need to get bolster and still can broke auras again and again. 
![0 auras ](https://user-images.githubusercontent.com/19292844/68590545-15c09b00-048f-11ea-9a8a-01048b2cec7d.jpg)

**Comment by Natherul** [comment]
need more information, if you do getstats are the stats added? 

Also the removal of auras when bolstering debolstering is currently NEEDED as we cannot recalculate buffs on the fly to be lower or higher levels. Otherwise someone might go into rvr at low lvl, use an aura and then go pve and have a OP aura active

**Comment by IceandFire1985** [comment]
on 4x auras 3 def auras was on me and my party member, and we both got stasts increse. the dmg aura was activ only on me, -> u can see " you have slain rats " on chat every 3 sec on second ss before i join sc.

**Comment by IceandFire1985** [comment]
I do some tests. The problem is Focus Mending. 
U can see that on sec ss i have activ 4x auras, but it happend only when i pop Stay Focus with Focus Mending on Bolster, and then i will back for non RvR area. U got all in this ss's.
![0x auras](https://user-images.githubusercontent.com/19292844/68594779-9041e880-0498-11ea-93d7-a2be3ab72dca.jpg)
![4x auras ](https://user-images.githubusercontent.com/19292844/68594782-933cd900-0498-11ea-8550-c645c2af71c4.jpg)

**Comment by Natherul** [comment]
fixed as of patch just now
