### ISSUE TITLE
[NPC] ashen scaledrake

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#15136]
in TM wc, ashen scaledrake mobs cannot be attacked; even guards ignore them.
![Chimp_113](https://user-images.githubusercontent.com/17765890/68929835-67b63900-078d-11ea-8258-434de8f26cf4.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by Natherul** [comment]
fixed as of patch just now
