### ISSUE TITLE
0 xp, 40 renown, no quest for winning serpents passage (screenshot included)

### ISSUE THREAD

**Issue by OndeTv** [WarEmu/WarBugs#15139]
![image](https://user-images.githubusercontent.com/56400920/68974432-0c1d9700-07f1-11ea-8efa-574d0f3d5301.png)

I played as Helligonden, zealot.
As you can see something is clearly wrong in this picture.

Edit with a more proper report:

Expected behaviour:
Gaining renown, experience and currency from winning a scenario.

Actual behaviour:
Gaining only 40 renown, no expecience, no currency from winning a scenario. Also, the scenario quest could not be picked up for me. For a guild member who had the quest, it could not be turned in. Also at least one person on the losing side appears to have received winning rewards.

**Comment by OndeTv** [comment]
How is this closed @raptrr ?

Those two issues are different. In the issue you referrence, values are correct except for duration. In this example values are wrong, but duration is correct. Only similarity is that rewards were not received, but they might be different bugs.

You might know something i do not making the issues similar, so i am just replying to make sure the cases are indeed the same.

**Comment by raptrr** [comment]
@OndeTv : I will have a deeper look today. Closed does not mean we won't check / work on it anymore. We just try to reduce the amount of tickets to have a better overview and be able to react faster and more precise.
