### ISSUE TITLE
Trophy Assignment: Barbed Khale

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#15130]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**

The Barbed Kahle was acquired from the Quest on the Blighted Isle where you speak to Karaa Ravenseer in Blighted Isle, coordinates 11100:17300 - I believe it is called "Birds of a Feather"? Upon completing the quest, this Trophy was one of the items that you could choose with a Chaos character. It's appearing today as an item for a Magus and will no longer allow you to wear it unless you're that class.

**Steps to reproduce the problem:**

Please restore to "Chaos" rather than class specific

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/22262165/68868324-40109380-06ef-11ea-88bf-fea35e718591.png)
![image](https://user-images.githubusercontent.com/22262165/68868376-574f8100-06ef-11ea-99c5-d72c1558ccaa.png)

**Comment by Lheana** [comment]
No sorry, this is how this trophy is meant to be [Barbed Kahle](https://web.archive.org/web/20080916100102/http://www.wardb.com/item.aspx?id=88802)

**Comment by Senthoi** [comment]
That's fair enough! Thanks Lheana
