### ISSUE TITLE
Strong Finish Tactic (Choppa)

### ISSUE THREAD

**Issue by oxo777** [WarEmu/WarBugs#15133]
**Expected behavior and actual behavior:**
Strong finish should add 15% critical rate when wielding a 2h weapon, but the extra crit is not showing up on character sheet or .getstats  (it has done previously and changed to this state after last patch)

**Steps to reproduce the problem:**
equip/unequip the tactic and nothing changes

**Testing Screenshots/Videos/Evidences (always needed):**
![Oxo_044](https://user-images.githubusercontent.com/57766345/68877569-304c7b80-06fe-11ea-823a-5e0323b2c40c.jpg)

**Comment by grunbag** [comment]
situational crit rate boost never show in get stat
