### ISSUE TITLE
Shining way respawn to third floor.

### ISSUE THREAD

**Issue by lasabur** [WarEmu/WarBugs#15137]
Shining way fort defenders respawn to third floor instead of jail. So to be farmed 

In all other forts defenders respawn to jail on third stage

**Comment by lasabur** [comment]
Same happening in Stonewatch, is this intended?

**Comment by Natherul** [comment]
same issue as https://github.com/WarEmu/WarBugs/issues/13607

**Comment by SilverWF** [comment]
This is still happens at every fort
