### ISSUE TITLE
Bolstering is brioken

### ISSUE THREAD

**Issue by Eweon** [WarEmu/WarBugs#15138]
Yesterday evening I played in Caledor with my lvl 19 engie. After a death I didnt get the bolstering bonus. A few ohter players had the same problem. So I decided to play scenarios. Same problem. After a death the bolstring buff is away. Staying with 2800 hitpoint and doing no damage in RVR or scanarieo. I try to relog or log on another toon. Nothing helps. Today I loged in, dont get the bolstering buff again if I move into any RVR zone.

**Comment by Natherul** [comment]
fixed as of patch just now
