### ISSUE TITLE
Tzeentch's Lash + Lashing Weaves = permanent Silence and DOT

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#15142]
Started to happen right after today's patch with "Lashing Waves tactic has been fixed and enabled"

When hit by this skill with tactic slotted, the victims becomes permanently silenced and suffering from DOT
It lasts till relog

**Comment by SilverWF** [comment]
Tested: death doesn't removes that silence and DOT

**Comment by Kaloell** [comment]
FYI: The tactic has been disabled and can't be trained right now.
![image](https://user-images.githubusercontent.com/29151272/68996055-36289500-0895-11ea-8940-aa9bf902de61.png)
