### ISSUE TITLE
Blast wave persist if it's killing blow[emulator][chosen]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#1514]
blast wave if used as last killing blow persist after death, maybe it's due the fact that it try to damage and then debuff, it should debuff and then damage, this way maybe that would not happen.

**Comment by Evildoor** [comment]
Hmmm. Maybe this is related to
https://github.com/WarEmu/WarBugs/issues/1435
https://github.com/WarEmu/WarBugs/issues/1451

**Comment by ozarmidrashim** [comment]
"maybe it's due the fact that it try to damage and then debuff, it should debuff and then damage, this way maybe that would not happen."

Blast Wave hasn't done this for a long time now - it debuffs first and then applies the damage.

**Comment by Tesq** [comment]
duno so
