### ISSUE TITLE
Can't get into Altorf from Reikwald

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#15140]
Expected is to be able to use the door to get into Altdorf.
Actual.  Nothing to click on the Altdorf main door.
note- there is a bell beside the door to click on, but does nothing.

thank you

**Steps to reproduce the problem:**
In Reikwald at Altdorf main gate.  Try to use door to portal.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kabucoror** [comment]
There will be no way to get into the city over fortresses. The bell is for some future content.
