### ISSUE TITLE
I can't Login my Engineer Character.

### ISSUE THREAD

**Issue by Yorumungando** [WarEmu/WarBugs#15147]
My Engineer name Yorumungando can't login. I asked 2 GM for help. I only see my character change zones and still auto quit game when login. Hope someone fix this bug.

**Comment by raptrr** [comment]
Try the following:
"First clear Cache folder. Start game. After character selection do /stuck twice at the loading screen."
And see forums:

https://www.returnofreckoning.com/forum/viewtopic.php?f=2&t=30920

**Comment by Yorumungando** [comment]
worked thank you

**Comment by raptrr** [comment]
https://github.com/WarEmu/WarBugs/issues/15150
