### ISSUE TITLE
Black Guard - Elite Training

### ISSUE THREAD

**Issue by skype01** [WarEmu/WarBugs#15148]
I'm a Black Guard and i used "Elite Training" (Path of Anguish)

"Elite Training" allows parry the 4 next attacks.

I have no problem in PVE but regulary in PVP in scenario, impossible to work it.

I cant' click on but i can use all my attacks. 

It seems that an opponent's attack prevents his operation.

Faced with this instability, I prefer not to use it anymore.

**Comment by raptrr** [comment]
Please provide some more information, such as screenshots or (best) video. By this information so far I cannot do much

**Comment by raptrr** [comment]
@skype01 : I got confirmation from @Natherul that this is working **fine** on his char.

**Comment by skype01** [comment]
Thank you for your interest. 
I took over "Elite training" (because i had given up) and currently no problems.
Can you wait a little days before closing that i continue my tests ?

**Comment by raptrr** [comment]
Yes, this will be open for another 13 days. After this time and no further reports I will close this issue.
