### ISSUE TITLE
Squig Herder Spiked pet ability Poisoned Spine is incorrectly flaged effect other time

### ISSUE THREAD

**Issue by Torete-war** [WarEmu/WarBugs#15144]
I reported this some years ago, the bug was fixed and now is not working as intended other time

The Spiked Pet ability Poison Spine it should be asigned as an Ailment as tootip say, but the ability is hiting the NPC'S and not flagging itself as an ailment

The Squigh herder needs the enemy target which it is already with an ailment on it, if he wants to be able to cast the heal debuff ability "Rotten arrer"

Attacking an NPC only with Spiked Pet and manualy clicking ability Poison Spine, the target is hit with pet's Poison Spine ability, but the Rotten Arrer ability is unable to beign used because the pet's "Poison spine" it is not flagged as an ailment or the game don't read it as ailment.

**Picture**
[https://ibb.co/cvkbrhq](url)

Example in picture:
Me unable to use the heal debuff on target and an big alert appearing telling me "Target must be Ailing" when in reality the target already should have been ailing with the pet's Poison Spine ability DoT during 5 seconds.

Update:
After test it in npc, i can see the poison spine pet ability is asigned other time as -curse- when this was already fixed in my old report which explain this pet ability should be flagged as an Ailment instead.
Now is broken other time and flaged as a curse, when it should be an ailment.

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by Lheana** [comment]
It should have been fixed with the patch of 28/03/2020.
