### ISSUE TITLE
Empowered Transfer does not affect Devour Essence

### ISSUE THREAD

**Issue by Kaloell** [WarEmu/WarBugs#15141]
The Disciple of Khaine tactic "Empowered Transfer" does not affect the ability Devour Essence. It states that it increases all healing from lifetaps. Devour Essence is a lifetap. The tactic does affect Rend Soul and Consume Essence.

![image](https://user-images.githubusercontent.com/29151272/68992887-cbb22d80-0871-11ea-81e0-332ed58eba8d.png)

To reproduce:
Get a DoK,
Train both Devour Essence and Empowered Transfer.
Use Devour Essence on the same mob, once with Empowered Transfer and once without.
Compare healing done in the combat log.

Video:
https://youtu.be/3bgWBs0rPRc
With Empowered Transfer: Devour Essence hits for 170 damage and heals for 85.
Without Empowered Transfer: Devour Essence hits for 170 damage and heals for 85.
It should heal for 25% more (about 106).

**Comment by xaraxdestr** [comment]
After the recent change to the tactic "Empored Transfer" it is still not working. 
![Knochenschwert_051](https://user-images.githubusercontent.com/45398873/82822292-d1826e80-9ea5-11ea-81fe-7b4e9daaca3d.jpg)

**Comment by Kaloell** [comment]
This seems to be working now after the latest patch.
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=40906&sid=27c29f638f05de6a21b87c1e13b7adea#p436215

**Comment by meatcomputer** [comment]
This still doesn't appear to be working.
