### ISSUE TITLE
Terrifying aura tactic not working (aoe detaunt)

### ISSUE THREAD

**Issue by Do0mforce** [WarEmu/WarBugs#15151]
the aoe detaunt is  clearly not working as intended pls check it. Tactic is slotet and as seen in the Video only the singel detaunt got apleyed 
[https://plays.tv/video/5dd306cbf1a43df5ef/850-crit-with-detaunt-full-deff-speck-gg-game](url)

**Comment by Rydiak** [comment]
You detaunted the Runepriest.  Was he over 30ft away from the WL attacking you?

**Comment by Rydiak** [comment]
I've had a couple issues recently with tactics not actually working when first slotted.  Try changing to another tactic group and then change back and see if that changes anything.

**Comment by raptrr** [comment]
Just tested it, working fine. As @Rydiak said, there are some issues with buggin tacs out right now.
Gonna close this.
