### ISSUE TITLE
Blade Master has several glitches with mounts.

### ISSUE THREAD

**Issue by Rilos** [WarEmu/WarBugs#1515]
![bladesung_000](https://cloud.githubusercontent.com/assets/14109685/10077449/5b90ba3e-62ae-11e5-8ea3-dd2bbae1cb25.jpg)

The first time I mounted, I stood on my mount instead of sitting.  The next bug I found is when I was jumping, my character stood up like in the picture.

I mounted after killing an enemy and with my perfect balance skill ready to be used, I took the screenshot showing me in position like I was going to attack on top of my horse.

Also, when I click on an enemy, my horse and I breathed like I was not mounted.

**Comment by Reggaewaldo** [comment]
I would like to know if more players are affected by this.

**Comment by coxie87** [comment]
I was also affected while playing my KOTBS

**Comment by Evildoor** [comment]
Isn't it a client-sided issue which happened in original WAR too? If yes, we can't do anything about it.

**Comment by Evildoor** [comment]
Closing since nobody objected to my assumption.
