### ISSUE TITLE
[Greenskin Chapter 11] Quest: Gotta Nosh

### ISSUE THREAD

**Issue by Lindiranae** [WarEmu/WarBugs#15169]
I had to smash "Recovered Supply Crates"... These are part of the PQ "Fireforges Camp".
But the supplys count only for the PQ and not for the Gotta Nosh Quest. 

![Hellschkriem Gotta Nosh 01](https://user-images.githubusercontent.com/52664952/69482894-45718a80-0e21-11ea-9c2d-6a60d76e0eb7.jpg)
![Hellschkriem Gotta Nosh 02](https://user-images.githubusercontent.com/52664952/69482895-45718a80-0e21-11ea-9e6f-d6ddc3c95fa9.jpg)

**Comment by Kabucoror** [comment]
I have no problems "smashing" them. With the quest active you should be able to use the crates, which should count for the quest and afterwards they can be destroyed for the PQ

**Comment by Kabucoror** [comment]
fixed with next patch
