### ISSUE TITLE
[Sound Issue] RP - Rune of Breaking

### ISSUE THREAD

**Issue by Bajlk** [WarEmu/WarBugs#15162]
Can you disable that (disturbing) sound while Rune of Breaking is active, please?

**Comment by raptrr** [comment]
@Bajlk Can you provide video/sound footage of that? I'm on my RP right now and have no issues.

**Comment by Bajlk** [comment]
> @Bajlk Can you provide video/sound footage of that? I'm on my RP right now and have no issues.
> EDIT: Just found out what you meant. Ingame-Sound adjustment is possible tho

If I adjust it all the sounds decrease, not just the one from Rune of Breaking.

**Comment by raptrr** [comment]
As this is not a bug, I'm gonna close this. Suggestions can be posted into the forum.

Cheers

**Comment by Bajlk** [comment]
I don't think that anyone has something against this change and so an suggestion in the Forum will get no attention.
