### ISSUE TITLE
Quest "Gnoblar Hunt"(T4 accessory ToK unlock "Sum of the Whole") - missing gnoblars in Cinderfall

### ISSUE THREAD

**Issue by Alsar01** [WarEmu/WarBugs#15165]
Every guide says certain gnoblars suppose to be here but only one ogre walks around instead

![WAR-64 2019-11-22 11-50-21](https://user-images.githubusercontent.com/57969390/69411702-7f0d9d00-0d1e-11ea-937a-25f8c7266da1.png)
![111](https://user-images.githubusercontent.com/57969390/69411387-eaa33a80-0d1d-11ea-9555-362d79a47aec.png)
![222](https://user-images.githubusercontent.com/57969390/69411391-ed9e2b00-0d1d-11ea-8eaa-9fe58cc495d9.png)
![WAR-64 2019-11-22 10-59-25](https://user-images.githubusercontent.com/57969390/69411397-f262df00-0d1d-11ea-81db-0adca9c86d67.png)
![WAR-64 2019-11-22 10-58-52](https://user-images.githubusercontent.com/57969390/69411443-0c042680-0d1e-11ea-9c69-9ba157740c9b.png)

**Comment by Lheana** [comment]
They are related to the PQ, so they appear if a destro comes to trigger the PQ, and apparently no destro came there when you searched.
