### ISSUE TITLE
Chat spammed with "Region Server"-Messages

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#15167]
During the last days I noticed that my chat was getting spammed with these messages. Sometimes they are send every few seconds, sometimes there a bigger timegaps in between. 
The channel is "System General" . 
Did a test with a standard ui-profile without any addon active. (RoR_SoR was disabeled shortly after reload)
![Gangan_013](https://user-images.githubusercontent.com/40274248/69426562-d404df80-0d2d-11ea-927e-d6d4a2d4a680.jpg)
![Scophis_045](https://user-images.githubusercontent.com/40274248/69426944-b1bf9180-0d2e-11ea-9f04-61d872070234.jpg)

**Comment by MaxHayman** [comment]
Character name?

**Comment by Scophis** [comment]
Scophis Zealot

**Comment by raptrr** [comment]
https://github.com/WarEmu/WarBugs/issues/15188
