### ISSUE TITLE
Zealot annihilator hands+shoulder: Wrong stat contribution

### ISSUE THREAD

**Issue by OndeTv** [WarEmu/WarBugs#15164]
Expected behaviour:
Zealot annihilator wingmantle should give 25 willpower
Zealot annihilator handwraps should give 23 willpower

Actual behavious:
Zealot annihilator wingmantle gives 43 willpower
Zealot annihilator handwraps gives 37 willpower

Character used: Helligonden, zealot

.getstats, naked, no tactics, no willpower/int renown skills:
![image](https://user-images.githubusercontent.com/56400920/69345279-29c78200-0c71-11ea-94d0-13bf918dcc11.png)

.getstats, as first example but with annihilator wingmantle adding +43:
![image](https://user-images.githubusercontent.com/56400920/69345460-7612c200-0c71-11ea-85b6-196224038548.png)

.getstats, as first example but with annihilator handwraps adding +37:
![image](https://user-images.githubusercontent.com/56400920/69345611-ae1a0500-0c71-11ea-8e2a-6b1b3cc0bb13.png)

I have tested with and without my current full gear setup (and many combinations), in and outside of harbinger of doom, and the discrepancies fit these 2 exact pieces regardless of combination. They only show with .getstats though. The paperdoll numbers are hopelessly wrong most of the time.

Now, reporting this is somewhat with a heavy heart. On one hand i want to help fix all the bugs i encounter, so reporting this is great. However, noticing these two bugs makes me wonder how many other pieces of gear out there have similar issues.

Ideally, every piece of common gear from annihilator and up should be rechecked and verified and have all issues found corrected. Otherwise, as i suspect there are many pieces like the two i just reported, class balancing makes little sense if the gear isn't even reliable. So it is my hope that you will go through all items to correct them. But i do not think you will. Which is why i was very hesitant to report this in the first place.

Regardless, now it is reported and my conscience is clear. I hope the staff rechecks all the common sets for both factions on your end to make sure yours is too ;)

Edit:
If you are wondering, the two pieces of gear has +19 wounds talismans on them which reflect correctly in .getstats.

**Comment by dalen** [comment]
But Shoulders have 18 int & 25 willpower, outside of Harbinger of Doom that is all converted to willpower, so 43 willpower.

Gloves have 14 int & 23 willpower -> converted to 37 willpower.

So this is correct behavior.

**Comment by OndeTv** [comment]
I hate to admit it, but you are right.
To make sure, i just logged in to check the rest of the annihilator set. Outside of the shoulders and gloves mentioned, only the boots have both willpower and int as well. When i did the tests however, i was wearing vanquisher boots in my default set.

In short, a huge oversight on my part and the items are indeed working as intented in conjunction with harbinger of doom. My apologies.

Closing the issue :)
