### ISSUE TITLE
Fort '~not enough contribution~' message missing

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#15160]
in the end of Shining Way, as order having 100+ aao,
other order members got rewards but i didn't.
thought my contribution was low.
but couldn't find the message this time. i've met it before few times, i know what it looks like.
 
i died near jail at last moment and respawned on the top of inner keep.
maybe respawn bug is related to reward bug?

![fort_bug](https://user-images.githubusercontent.com/19988772/69258151-85f1be00-0bff-11ea-8de9-032c70391809.jpg)

**Comment by Natherul** [comment]
if that is the case a message is sent, however its easy to miss as its sent before all the RVR messages and its (like most error messages) not sent on the RVR filter but the user error filter.
