### ISSUE TITLE
Ongoing issues with Bolstering in Scenarios

### ISSUE THREAD

**Issue by Povel** [WarEmu/WarBugs#15179]
In Scenarios the Bolstering function only works half the time, applies to all scenarios.

https://i.imgur.com/tbYXYUq.png

https://i.imgur.com/lFccD5Y.png

**Comment by Kaelang** [comment]
Appreciate this is an older report - however the lack of information here makes this almost impossible to replicate. Please re-open with more information if this issue persists.

I've ran multiple scenarios on lower level toons and never seen any issues with Bolster on the recent version of RoR. 

Closing.
