### ISSUE TITLE
[Career Builder] Unshakable Focus morale for Squig Herders

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#15174]
The Career Builder shows, that Squig Herder has morale 2 Unshakable Focus, while in fact, they didn't have it for long ago
Please fix

**Testing Screenshots/Videos/Evidences (always needed):**
![img-2019-11-24-16-46-00](https://user-images.githubusercontent.com/16439840/69495608-ec196200-0ed9-11ea-9bc8-bae227fb430a.png)

**Comment by Kabucoror** [comment]
This doesn't belong here. There you go: https://github.com/dalen/RoRBuilder/issues
