### ISSUE TITLE
Unable to paste links

### ISSUE THREAD

**Issue by Evilbenji821** [WarEmu/WarBugs#15171]
**Expected behavior and actual behavior:**

Expected: Linked Quest in chat for player to view.
Actual: Nothing is being linked into the game.

**Steps to reproduce the problem:**

Copy/Paste links from Wiki Page to Game.

**Testing Screenshots/Videos/Evidences (always needed):**

![Screenshot_109](https://user-images.githubusercontent.com/50061449/69489496-ede61580-0e46-11ea-9a46-f4aa47d134e2.png)
![Screenshot_112](https://user-images.githubusercontent.com/50061449/69489534-71a00200-0e47-11ea-9890-c3a97256d779.png)
![Screenshot_113](https://user-images.githubusercontent.com/50061449/69489535-7369c580-0e47-11ea-8a4d-5a515e0dd646.png)

**Comment by Kaelang** [comment]
This is now working. Able to test using rewards from wiki.
