### ISSUE TITLE
[Zealot] 7p Invader bonus can't be triggered with path of Alchemy abilities

### ISSUE THREAD

**Issue by 0berhofer** [WarEmu/WarBugs#15176]
Deep Scheming doesn't work: https://www.youtube.com/watch?v=SYFagf6u_KY

**Comment by SamejimaMamimi** [comment]
It incorrectly triggers on Path of Witchcraft (Dark Medicine)

**Comment by wargrimnir** [comment]
This is intended to proc from the Path of Alchemy, but was flagged incorrectly in the DB and should function correctly in the next update.

**Comment by Natherul** [comment]
should be fixed as of today
