### ISSUE TITLE
Healing potion salvagable

### ISSUE THREAD

**Issue by Snowy1066** [WarEmu/WarBugs#15178]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**

I expect only equipment to be salvageable but I can salvage [Fleeting Elixir of Restoration][Fleeting Elixir of Mending]  but [Fleeting Elixir of Remedy] is not, but that could be due to it being to high for my skill level

**Steps to reproduce the problem:**

I Just did a normal salvaging. After doing this once the potions no longer show as salvageable nor can they be salvaged but if I relog they revert back to being salvageable.

**Testing Screenshots/Videos/Evidences (always needed):**

Use magical Salvaging on the potion
![Deandius_000](https://user-images.githubusercontent.com/58155734/69507295-eb102100-0f29-11ea-8664-af46e33ab0fe.jpg)
![Deandius_001](https://user-images.githubusercontent.com/58155734/69507302-f19e9880-0f29-11ea-8bd1-4585431f22e4.jpg)
![Deandius_002](https://user-images.githubusercontent.com/58155734/69507336-1135c100-0f2a-11ea-9e1f-4974602fabfe.jpg)

**Comment by Nekkbraka** [comment]
Healing potions are working like they were equipable itens, so every time if you have it on skill bar it shows a pop up asking if you want to equip them..

**Comment by Snowy1066** [comment]
> Healing potions are working like they were equipable itens, so every time if you have it on skill bar it shows a pop up asking if you want to equip them..

Once I had salvaged one they started to working correctly and I could drink them.

**Comment by raptrr** [comment]
On my game it seems fixed, can you confirm?

**Comment by Snowy1066** [comment]
> On my game it seems fixed, can you confirm?

Checked and it appears to be fixed Healing potions I am no longer able to salvageable and the potions can be drunk.

**Comment by Snowy1066** [comment]
Looks like this has been fixed do I close it?

**Comment by pikara** [comment]
It happens with more pots and other stuff like talismans. Once u salvage 1, all stack back to normal. If u move the item in u bag it back to normal also.
