### ISSUE TITLE
[Squig Herder] Chewtop of the Mercenary not fully dye able

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#15172]
**Expected behavior and actual behavior:**
Expected: this item must be fully dye able
Actual: Upper part can not be dyed

**Steps to reproduce the problem:**
Equip this item and try to dye it

**Testing Screenshots/Videos/Evidences (always needed):**
![2019 11 24-08 45](https://user-images.githubusercontent.com/16439840/69490360-bce20100-0e97-11ea-8b62-210191879328.jpg)

**Comment by Kaelang** [comment]
![image](https://user-images.githubusercontent.com/60117106/82127206-b7f86d00-97a9-11ea-8e43-e6956a12113e.png)
Both parts can be dyed. 

Closing.
