### ISSUE TITLE
Officer's Healing Potions, costs too much

### ISSUE THREAD

**Issue by fixfax86** [WarEmu/WarBugs#15182]
Hello, I dont know why, but the Officer's Healing Potions costs triple the amount of emblems as they usually do
![Fhaine_000](https://user-images.githubusercontent.com/51016115/69570996-52c57b00-0fc1-11ea-9b0c-f69d8857ec02.jpg)
?!

**Comment by Rydiak** [comment]
Those are the ones from SC emblems.  The ones from ORvR medallions are the cheaper ones.

**Comment by fixfax86** [comment]
okay thanks
