### ISSUE TITLE
Somehow got 11.5 k or so gold ingame.

### ISSUE THREAD

**Issue by Zxul** [WarEmu/WarBugs#15183]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**

Didn't really expect that one.

**Steps to reproduce the problem:**

Might be related- there was apparently a lag in Reik, and one of AH sellers disappeared (appeared later). Opened AH window with the other one, apparently pressed on something, and got the following message:
"You receive 130884 gold. 74 silver, and 45 brass coins.
Your account's play time will expire at 8:00:30 AM. You have chosen the time- deduction payment model. Each hour, 5 points will be deducted."

Had 1600 or so gold before on that toon, so 11.5 k or so gold actually received.

Also there seems to be opened some public quest scoreboard window with no participants. 

Will see if the gold remains after relog.

Edit: After relogging, gold seems to go back to normal- additional screenshot attached.

**Testing Screenshots/Videos/Evidences (always needed):**

https://img.techpowerup.org/191125/lxul-018.jpg
https://img.techpowerup.org/191125/lxul-020.jpg

After relog:

https://img.techpowerup.org/191125/lxul-023.jpg

**Comment by MaxHayman** [comment]
This may have been a packet corruption issue which has been fixed since.
