### ISSUE TITLE
Norse Sea dog spawning twice in one area.

### ISSUE THREAD

**Issue by Rilos** [WarEmu/WarBugs#1518]
![bladesung_001](https://cloud.githubusercontent.com/assets/14109685/10078436/b00a8fbe-62b2-11e5-9ccb-be3bbd69008c.jpg)

![bladesung_002](https://cloud.githubusercontent.com/assets/14109685/10078439/b56af02a-62b2-11e5-90ab-a1e9faf8fc4d.jpg)

**Comment by Evildoor** [comment]
https://github.com/WarEmu/WarBugs/issues/1448
