### ISSUE TITLE
Beast Lord Token - No quest Available

### ISSUE THREAD

**Issue by aquamercy** [WarEmu/WarBugs#15180]
A few months ago I turned in my beast lord quest in Praag right before a reset. When I logged back on my token was not in currency but the quest was not available anymore.  I would like the chance to have my book for the +2xx armor bonus. I have been told that resetting quests for everyone is the only possibility and to post bug here.
So here I am posting.
Thanks
Aquamercy (Starbear AM is the one with issue)

Issues should be unique. 
--- This has been reported before and fix was to reset all.

**Expected behavior and actual behavior:**
--- I expected to have my token after server reset. It was not there. Quest to redo praag beastlord is not available.

**Steps to reproduce the problem:**
--- Be an idiot and turn in a quest right before restart.

**Testing Screenshots/Videos/Evidences (always needed):**
--- pic of me having 4/5 beastlord token.

Thank you for your time

**Comment by Lheana** [comment]
Nothing can be done for this issue. Sadly you turned in the quest right before a server restart, the quest is considered as done but it seems like you did not get the token.
