### ISSUE TITLE
Floating Objects

### ISSUE THREAD

**Issue by CircuitByrd** [WarEmu/WarBugs#15189]
_I see two other floating objects reports for other objects elsewhere in the world (a rock and a sheep). Not sure how widespread this is or whether or not these should be tagged as related._

**Expected behavior and actual behavior:**
In Nordland, in the Order tutorial area, there are two quest related objects floating a ways off the ground and table respectively. One of these is the target for the quest Of Honor and Glory, in the tavern.

**Steps to reproduce the problem:**
Visit the location, see the floating objects.

**Testing Screenshots/Videos/Evidences (always needed):**
![Nordland-Bugs-3-FloatingBook-ofhonorandglory](https://user-images.githubusercontent.com/26975895/69702290-79b0a980-10b4-11ea-9abf-67370f25bd6c.png)

![Nordland-Bugs-2-FloatingPaper-ofhonorandglory](https://user-images.githubusercontent.com/26975895/69702371-b54b7380-10b4-11ea-8875-405022a7da4d.png)

**Comment by Lheana** [comment]
This should have been fixed some weeks ago.
