### ISSUE TITLE
[Epic Quest] Control

### ISSUE THREAD

**Issue by Bajlk** [WarEmu/WarBugs#15187]
Zolthran Horrorthorn is missing.
![Zolthran](https://user-images.githubusercontent.com/58007137/69669501-4826e680-1092-11ea-8c24-1c457b209755.jpg)

**Comment by Lheana** [comment]
She is not missing. Search harder.

**Comment by Bajlk** [comment]
> She is not missing. Search harder.

Very unprofessional.
NPC is not in the marked area, so where is it?

**Comment by Lheana** [comment]
Firstly, if I were you, I would be more respectful and prudent about how you talk to the team.
Secondly, in case you did not understand, the Bugtracker is not made to help players find NPCs they don't find. Bugtracker is made for **game** issues, not **player** issues. The NPC is inside the quest marker, so search harder.
I also lock this report.
