### ISSUE TITLE
[ui] open parties and warbands window displaying strange data

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#15185]
reporting this since other players stated to be affected by the same problem.
![Chimp_116](https://user-images.githubusercontent.com/17765890/69646635-6f68be00-1068-11ea-8693-4e840c8fdeef.jpg)
porting to ic solved the problem.
it happened on 25/11 around 19:30 cet

**Comment by zak68** [comment]
it happened again on 29/11 11:00cet; curious thing is that it only affected my pg stationed in IC but not another parked in Eataine.

**Comment by MaxHayman** [comment]
Should be fixed in next patch
