### ISSUE TITLE
Whoosha Boy's PQ (Dwarf lvl 37)

### ISSUE THREAD

**Issue by graffernsl** [WarEmu/WarBugs#15186]
In the first part you need to collect "Coils of Beard Rope".
They do not respawn after taking them, which means their number is limited. Moreover, one rope is outside the PQ zone. Therefore, it is impossible to complete the first part of the quest.
![Graffer_004](https://user-images.githubusercontent.com/58138563/69647984-7fd66400-107b-11ea-890c-2b227ad7018f.jpg)
![Graffer_005](https://user-images.githubusercontent.com/58138563/69648020-8fee4380-107b-11ea-8d73-e2512271ea50.jpg)
I feel it must either return the ropes to the quest zone, or give them the opportunity to respawn. Thanks!

**Comment by Kabucoror** [comment]
fixed with next patch
