### ISSUE TITLE
Region server is no longer available

### ISSUE THREAD

**Issue by OndeTv** [WarEmu/WarBugs#15188]
![image](https://user-images.githubusercontent.com/56400920/69689178-8939ed80-10c8-11ea-88b0-c6c3d608b206.png)

So this has been going on for days. It might have been reported before (although i have not seen it), but if not, now it is.

Expected behaviour:
Region server working as intended, and not producing errors

Actual behaviour:
See screenshot

**Comment by CircuitByrd** [comment]
Confirming. Not sure if it's universal, regional, or affecting specific users, but I see this same behavior.
I assume it's referring to the Region chat channel, which appears to accept messages even while it is reporting no longer available. It's unclear what effect if any this is actually having, apart from the spammy message.
