### ISSUE TITLE
During Nordland Quest "Hearts and Minds", Farmers Change Gender and Strip Naked

### ISSUE THREAD

**Issue by CircuitByrd** [WarEmu/WarBugs#15193]
Severity: Minor (quest complete-able, just not behaving as expected)

**Expected behavior and actual behavior:**
Can't recall for sure how this worked years ago in live, but expected behavior would be the NPC turns and attacks you as is. If re-spawned as hostile, with a generally similar appearance. Instead, after talking to the pitchfork wielding, often female farmer, they vanish, and are replaced by a naked male farmer who proceeds to punch you.

**Steps to reproduce the problem:**
Grab Hearts and Minds quest in starter area of Nordland (Order). Interact with Grimmenhagen Farmers.

**Testing Screenshots/Videos/Evidences (always needed):**
![2019-11-27 08_53_24-Warhammer_ Age of Reckoning, Version 1 4 8, Copyright 2001-2012 Electronic Arts,](https://user-images.githubusercontent.com/26975895/69734103-0cbd0400-10f4-11ea-9d05-c67bba6206da.png)

**Comment by CircuitByrd** [comment]
Interestingly, after being defeated, the corpse is replaced with one matching the original farmer.

**Comment by Lheana** [comment]
The quest has been disabled, so it's no longer an issue.
