### ISSUE TITLE
Not getting rewards from fort because not being a part of the fortress internally

### ISSUE THREAD

**Issue by BertildaEngelgard** [WarEmu/WarBugs#15199]
![error](https://user-images.githubusercontent.com/44665575/69767616-3296e700-118e-11ea-8b79-983c6e0acaac.png)
I entered a fort before lord died in previous zone (KV). Just went north from order wc. Maybe I was still unflagged after entering fort zone (not sure) An error started appearing right after our party got renown points and continued after every kill. So no rolls/medals and some ridiculous amount of rp for taking zone like 20 or smth

**Comment by Natherul** [comment]
Thanks for these reports. So far I can see everyone that had issues entered before fort started. I have found an issue with that and corrected it.

Ill keep this ticket open for a bit though to collect any more bugreports on the issue if there is other entrypoints that are also having issues

**Comment by IceandFire1985** [comment]
From 2 day i got same situation. yday and today I was on keep def in KV, then go stonewatch from order wc after KV lord down, but before lock. Was on fort full time, geting some flags on s2, and fight all s3 till win fort. No rewards ( 1.8k renown, no medals no rolls )

**Comment by Natherul** [comment]
noticed there is still some issues with adding players to the fort if they enter the zone before fort starts, I added more checks for next patch

**Comment by Natherul** [comment]
There still seems to be issues for people who runs into the zone before fortress starts. I have yet to replicate this since my last change and Im on a week off. In the meantime I suggest if you see this message or dont want to risk it to enter fort zone AFTER the fort has entered stage 1

**Comment by raptrr** [comment]
https://github.com/WarEmu/WarBugs/issues/15276

**Comment by raptrr** [comment]
https://github.com/WarEmu/WarBugs/issues/15273

**Comment by Natherul** [comment]
next patch an attempt for further fix is done and as such message is changed. The new message will be fine if you see once but if you see it more then it needs reporting.

**Comment by Natherul** [comment]
so its live now. Please do report back if its still an issue with the latest change. As in I want to know regardless from you. If the message is shown, is it shown once or more and do you get rewards in the end?

**Comment by Natherul** [comment]
noticed that there was an issue today with the debug message about issues with contribution as some people could be in the back of the fortress (not participating) but still getting the message. This has been addressed since.

**Comment by Kaelang** [comment]
The 27/05 patch has addressed some contribution issues / porting issues with forts. Please re-open if this is issue persists.
