### ISSUE TITLE
Fortress missing rewards

### ISSUE THREAD

**Issue by Ysaran** [WarEmu/WarBugs#15191]
**Expected behavior and actual behavior:**
well, you should defend a fortress and when it ends you should receive 4 meds, some Vanq meds, 2 Seals, some RP and the lootbag roll but this didn't happened.
As soon lord died campaign resetted and i received no RP, no invader meds, no Vanq meds, no Seals and i didn't seen any lootbag roll.
i would add that it has not appeared the usual "your contribution is too low", in the chat there was only the message that appear when zone reset.

**Steps to reproduce the problem:**
it was in stonewatch, i was on order side with my slayer r65. i entered vis Reikwald portal, i joined a wb and waited on the north flag, the one near the Dwarf Capital doors. i waited here until some destru approached us and i've done one kill and i died once. i respawned in keep and i went to the south-east flag, i capped the flag and i fled on the stair to avoid beeing killed. from the wall i ran to the fort without dieing. here i triyed to collect some kills jumping from fort on destu going around solo. at the end of the second stage i collected 4 kills and only 1 death.
as soon 3rd stage started destru dry pushed and we wipped. we respawned in jail and i waited to fort to ends. i'm not sure but i think that the whole defence lasted around 20 mins.

**Testing Screenshots/Videos/Evidences (always needed):**
i took no screenshot or video. when i received no rewards i was too upset to think about this kind of proofs. the next time i will try to provide some evidences

**Comment by Natherul** [comment]
was the debug message shown when you killed players?

**Comment by Ysaran** [comment]
As far as I remember the debug message was added after the fortress. So no, no message

**Comment by Natherul** [comment]
ah right, then Ill close this one and hope it was the same issue. If not and you get the same symptom but without the message please open a new report.
