### ISSUE TITLE
Rafeus the Mottled

### ISSUE THREAD

**Issue by Johnnywiz** [WarEmu/WarBugs#15195]
This NPC is bugged and won't interact with my toon consequently I can't complete the quest "The wall will not fail". He's located in Kedrin Valley around 19005, 2410.
Nothing I tried could induce him  to aggro. Quitting the game had no effect.
![Nyteknight_001](https://user-images.githubusercontent.com/58268123/69745021-3fd5b680-1139-11ea-911c-72d1bfa69d59.jpg)

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**
![Nyteknight_001](https://user-images.githubusercontent.com/58268123/69745045-51b75980-1139-11ea-8c48-de59e18a5229.jpg)
![Nyteknight_002](https://user-images.githubusercontent.com/58268123/69745059-5845d100-1139-11ea-930d-dcd325b037cc.jpg)

**Comment by raptrr** [comment]
Is it still happening? Because earlier today we had an issue with pathing and fixed it asap. 
Can you check one more time and give me feedback?
