### ISSUE TITLE
No contribution/bag roll/medals at Stonewatch

### ISSUE THREAD

**Issue by starfkr** [WarEmu/WarBugs#15201]
Saw in the /T4 that destro were getting the KV keep down fast.
Flew there got flagged for RvR. 
Keep got locked, i went north to get safe into Stonewatch fort.

After stage one, the following was speammed until stage 3 was done:

(http://bakfullaangorakatter.com/Starfkr_stonewatch.jpg) 

I didn't receive a thing... no medals or bag roll.

**Comment by Natherul** [comment]
same as https://github.com/WarEmu/WarBugs/issues/15199
