### ISSUE TITLE
Pack Hunting tactic 50%aa glich again

### ISSUE THREAD

**Issue by Farlopa** [WarEmu/WarBugs#15208]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**

Free 50%aa on whatever stance u want to play

**Steps to reproduce the problem:**

1-take pack hunting tactic
2-set up 2 dif. tactic pages,one with tactic other with out
3-use hunter stance see if u has the 50%aa buff
4-switch to the page with out tactic
5-u will lose your stance and the buff
6-switch back to page with tactic and now u will get insta hunter stance with buff
7-change to the stance u want to play with buff and dont change it or u will lose the glich
8-now u can be in guardian stance with 50%aa from pack hunting 

**Testing Screenshots/Videos/Evidences (always needed):**

https://imgur.com/a/keShZak

**Comment by Turrin66** [comment]
Can confirm this is accurate and repeatable

**Comment by grunbag** [comment]
fixed with next patch

**Comment by Lheana** [comment]
It should have been fixed with the patch of today.
