### ISSUE TITLE
Random RR tic

### ISSUE THREAD

**Issue by Carcharadon** [WarEmu/WarBugs#15202]
was on my healer in Gunbad and got a random renown tic for a absurd amount of renown  Images attached for char name and tic , ok i cant attach the image files for some reason but i have them /

thew tic was for 151345 RR at 20;04;53 server time and the char was  Selachimorpha

**Comment by raptrr** [comment]
Can you upload it somewhere and attach the link? Would help us.

**Comment by Carcharadon** [comment]
got a email to send them too , i don't know if they are too big or what, but I cant seem to upload them to the forums either.

**Comment by Carcharadon** [comment]
![Selachimorpha_007](https://user-images.githubusercontent.com/55959616/69815828-c2ec2080-11bc-11ea-874c-920dea807457.jpg)
![Selachimorpha_007s](https://user-images.githubusercontent.com/55959616/69815838-c8e20180-11bc-11ea-908c-1195ae66ec85.jpg)

**Comment by Lheana** [comment]
2 questions:
- Firstly did you really get this renown, or were you already rr63?
- Secondly, had you a log out like while loading one of the gunbad instances?
About the small tics of 20 renown, one of your team mates must have done PvP before gunbad, and healing them gave the few renown they still could give.

**Comment by Carcharadon** [comment]
Yes I got it , I was not 63  ,I thought I was only 61 yet.

No i was kicked to IC but about 3 tries before the one i got the tic on , Also i had not done any RVR or even been to a RVR lake in 3 days on that Character.

this was our 3rd attempt and i had been healing party for a hour with no tics up to this one and no one els in our group got it.

**Comment by grunbag** [comment]
fixed already
