### ISSUE TITLE
Only 1 Damage Taken during Scenario

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#1520]
Today i experienced the following bug with my Choppa Zankz:

In a scenario i took only 1 damage from any damaging source.
![zankz_003](https://cloud.githubusercontent.com/assets/14824601/10079334/b91a8e92-62e9-11e5-8bee-ddbbc11c9f12.jpg)

I will reset my renown skills, maybe the problem is there?

Cheers
Bainwulf aka. Zankz

**Comment by Tesq** [comment]
report what you specced into so that they can uderstand where the bug generated from

**Comment by Nfkillz** [comment]
mb its trouble with bolster and you was hit by lvl 1-5 toon

**Comment by Bainwulf** [comment]
I'm specced like:
Vigor (Wounds):
1 Renown spent
3 Renown spent
6 Renown Spent

Might (Strength):
1 Renown spent

At this time I was level 10 with no points spent on the career tree.

Cheers

**Comment by Evildoor** [comment]
Seen similar problem discussed on forum, maybe this happens when you get negative toughness stat.

**Comment by Luth-RoR** [comment]
Shouldn't happen anymore.
