### ISSUE TITLE
"You are not part of this fort" - Patch fix didn't work.

### ISSUE THREAD

**Issue by LittlefishSail** [WarEmu/WarBugs#15206]
**Expected behavior and actual behavior:**
Patch Notes indicate "- Fixed an issue where walking in before fort started prevented you from getting contribution."  I tested this just a few minutes ago in Shining Way, and it's still not fixed.  Walked in from Eataine right after lord fell, but before zone flip.  Played the entire fort in a WB, got well over 30 kills (went from 0-30 on the Beastlord kill quests), and got spammed with Natherul's "You are not part of this fort" message, again, the entire time.  Final result - 488 renown, and 1 Officer's Medallion?  Screenshots below.  Played on character MacDougall, KotBS R32/RR45.

**Steps to reproduce the problem:**
N/A

**Testing Screenshots/Videos/Evidences (always needed):**

![Macdougall_003](https://user-images.githubusercontent.com/17417016/69843034-b2c35800-1233-11ea-8b9c-77b26c65b0a0.jpg)
![Macdougall_012](https://user-images.githubusercontent.com/17417016/69843044-b951cf80-1233-11ea-9fbd-2e114a53bcad.jpg)
![Macdougall_020](https://user-images.githubusercontent.com/17417016/69843050-c2db3780-1233-11ea-9fa9-3fa9724abadb.jpg)

**Comment by Natherul** [comment]
so same as https://github.com/WarEmu/WarBugs/issues/15199

closing, keep all these tickets in the same meta ticket.
