### ISSUE TITLE
"You are not part of this fort" message in Reikwald

### ISSUE THREAD

**Issue by LittlefishSail** [WarEmu/WarBugs#15203]
**Expected behavior and actual behavior:**
Posting per Natherul from the Forums.  Defended Reikwald as Order successfully 25 minutes ago.  Entered through Altdorf portal, about 3 minutes before stage 1 even started.  Started receiving the yellow "Not part of this fort" message as soon as the fort started, and kept getting it throughout the whole fort (lost count, but probably got the message 50+ times.)  I played the whole fort with a very strong 6-man (not at all because of me), picked up 9 Vanq medallions, 20+ Conq, and enough renown for a full level (44 to 45), so it would be hard to say there wasn't enough participation.  If it matters, we got 1 or 2 flags, too.  Reward for the whole fort was 45 renown and no medallions.  I took a dozen screenshots from the first message to the end of the fort.  I'll just post beginning and end, with a single middle, but if more shots will help, let me know.  Thanks, and good luck finding the bug(s).  -MacDougall/KotBS R31/RR45

**Steps to reproduce the problem:**
N/A

**Testing Screenshots/Videos/Evidences (always needed):**

![Macdougall_004](https://user-images.githubusercontent.com/17417016/69778636-176aae00-1173-11ea-9fe6-80de89b2cc1d.jpg)
![Macdougall_009](https://user-images.githubusercontent.com/17417016/69778689-3d904e00-1173-11ea-9503-afac7712f609.jpg)
![Macdougall_028](https://user-images.githubusercontent.com/17417016/69778704-4c770080-1173-11ea-9d2e-0cff5f241db1.jpg)

**Comment by Natherul** [comment]
same as https://github.com/WarEmu/WarBugs/issues/15199
