### ISSUE TITLE
Squig herder pet

### ISSUE THREAD

**Issue by Cruella01** [WarEmu/WarBugs#15213]
Squig herder range pets fails to attack a lot of the time, even if i have line of sight and it has line of sight it will no longer attack if someone hides behind a tiny pebble or flag poll. Once its been line of sighted it stops attacking. Which means that you cannot use drop that even though you're still being chased and have line of sight. Their damage is also extremely sad when the off chance they do get an attack off. 

Steps to fix revert to live.

Sorry cant provide a video....

**Comment by Kaelang** [comment]
Pets now look to manoeuvre terrain to approach LoS and continue attacking. If you are able to replicate this issue with a recording, please re-open the problem as I had no issues whilst testing this.
