### ISSUE TITLE
Lifetap heals not working correctly on keep lords

### ISSUE THREAD

**Issue by CornerbackAC** [WarEmu/WarBugs#15218]
**Expected behavior and actual behavior:**
Expected: When hitting a keep lord with a lifetap heal, e.g. Consume Essence, players get healed for the amount stated in the tooltip (in this case 100% of dmg dealt)
Actual: the amount healed is much lower than stated (see screenshot)

**Steps to reproduce the problem:**
Hit keep lord with Consume Essence (or any other lifetap heal)

**Testing Screenshots/Videos/Evidences (always needed):**
![bug](https://user-images.githubusercontent.com/11341460/69959741-21d8cf00-1508-11ea-9e89-3ffa3960ac25.PNG)

**Comment by Rydiak** [comment]
Sadly it isn't documented anywhere (recently at least), but lifetaps suffer a *major* reduction in healing when attacking a Lord.

**Comment by Kaelang** [comment]
As of 29/04/2020 this should now be fixed. Please re-open if issues persist.
