### ISSUE TITLE
[Items] Talisman Stone doesn't work

### ISSUE THREAD

**Issue by ShockParade** [WarEmu/WarBugs#15210]
Evening! 
Got a problem with the talisman stone: when i try to put that in every object the game say 
"Cannot equip an item thts stacked. Please report to the bugtracker"

Any help or advice?
Thanks!

**Comment by raptrr** [comment]
Bugtracker is not there to ask for help or advise. It's to track bugs so we can fix them. Help and advice, you can get from the forum.
This might still be a bug, so please provide more information. Which ingredients, etc..
Best would be screenshots or videos.
