### ISSUE TITLE
Chars buggy|German

### ISSUE THREAD

**Issue by Blackplaic** [WarEmu/WarBugs#15215]
Kurze Frage an alle Deutschsprachigen Spieler/GM's Ich kann seit Tagen mich nicht mehr mit verschiedenen Chars einloggen und bräuchte da mal hilfe.^^
ein paar chars funktioniern noch aber bei der hälfte fliege ich immer wieder raus 
Danke im vorraus. :)

**Comment by Kabucoror** [comment]
Bei solchen Problemen bitte direkt einen GM anschreiben. 
Sioding ist ein Deutscher.
Ansonsten im Bugtracker immer Englisch^^.

**Comment by Blackplaic** [comment]
okay danke dir :)

**Comment by Kabucoror** [comment]
gern :)
