### ISSUE TITLE
Campaign Reset 

### ISSUE THREAD

**Issue by Ysaran** [WarEmu/WarBugs#15211]
**Expected behavior and actual behavior:**
Campagn should reset after one faction lock two forts. but if two forts are going on at the same time and one them lock then campaign reset

**Steps to reproduce the problem:**
open two forts at the same time and then lock one if them

**Testing Screenshots/Videos/Evidences (always needed):**
couldn't provide any evidences

**Comment by CornerbackAC** [comment]
Can confirm this. Happened multiple times already.

**Comment by Natherul** [comment]
if one is already previously locked for one realm and next one that locks is locked for the same realm then the last fort will close with no rewards and campaign reset. This is not a bug but been stated would happen with the campaign system we have. Once city sieges are in it will change slightly but currently this is not a bug

**Comment by CornerbackAC** [comment]
@Natherul but it also happened when no fort was previously locked and two forts were open at the same time. if one ended, the campaign also reset.

**Comment by Ysaran** [comment]
I report the bug because there were no forts locked. There were all three zone open and there were two forts going on at the same time. When one fort locked then campaign restarted. This is not working as intended
