### ISSUE TITLE
mail item disappeared

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#15212]
i sent 2 items in 1 mail, from witch elf to zealot
witch elf gears - Gnawbone's Throatlatch and Corset of the Silvered Oak
only 1 item arrived, Corset.
Gnawbone's ~ (shoulder) was missing.

**Comment by raptrr** [comment]
Try to resend another mail (with some item you dont need e.g.) and see if it arrives? Else wait some hours and it might appear?

**Comment by Oldneko** [comment]
same thing occur to me yesterday(4 Dec, around 22-23pm in Japan)
I sent some Talisman making items (125 Curio and some others, I think) from Scavanger character(Nekomusume) to Talisman making Lv200 character(Nikuq)
When I relog to Nikuq to get that Curio , timing was just Fort starting, I got a message in chat window "1 message in mail box", but no mail can be arrived.

sorry my poor English

**Comment by anarchypark** [comment]
yes it had appeared. 
i might have sent Corset alone before.
and 2 items mail were stuck right after.
got confused. my bad
