### ISSUE TITLE
The shadowlands: Beyond the griffon gate quest

### ISSUE THREAD

**Issue by Vhpikachu** [WarEmu/WarBugs#15221]
After trying and failing to complete the beyond the griffon gate quest in the shadowlands, I abandoned it to pick it up again to reset it but am unable to re accept the quest as it hasn't poped up in the camp above Hassia Bloodspiller's head. Not sure why it has done this as other quests i've abandoned and retaken up have been fine.

**Comment by Lheana** [comment]
When a quest is abandoned, you can take it again from the NPC if :
- The NPC was the quest finisher/starter
- If the previous step has been turned in using an item
For many other quests like this quest line, you turn in the quest to a GameObject. So you simply have to find this GO and interact again with it to retake the quest.
