### ISSUE TITLE
Lady Krueger NPC missing for T3 Epic Quest Inevitable power

### ISSUE THREAD

**Issue by vikingofmars** [WarEmu/WarBugs#15223]
Issues should be unique. Check if someone else reported 
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**

The NPC "Lady Krueger" is missing/not respawning to continue the epic quest "Inevitable Power"

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/37393516/70033233-09ef6280-157d-11ea-80f1-5443f923296c.png)

**Comment by Lheana** [comment]
For some reasons Lady Krueger was under the castle. She has now correctly respawned.
