### ISSUE TITLE
Hearts and Minds NPC Spawn Issue

### ISSUE THREAD

**Issue by Baron-Sogz** [WarEmu/WarBugs#15220]
The quest Hearts and Minds in Nordland, Order side. 

**Expected behavior and actual behavior:**
The quest involves speaking to NPCs to rally them to the cause, and occasionally they will turn aggressive and attack. All the NPCs are spawning in two large clumps very close to each other, which means it is very difficult to get credit tags on the aggressive NPCs as they are almost instantly killed by the other NPCs. 

**Steps to reproduce the problem:**
Go to the field North West of Grimmenhagen where the quest takes place. 

**Testing Screenshots/Videos/Evidences (always needed):**
![Warburton_001](https://user-images.githubusercontent.com/58440095/69981859-14810c00-152b-11ea-9954-e1a063d6c5fd.jpg)
![Warburton_000](https://user-images.githubusercontent.com/58440095/69981875-1d71dd80-152b-11ea-81dd-44de9503d43b.jpg)

**Comment by Lheana** [comment]
The quest has been disabled, so it's no longer an issue.
