### ISSUE TITLE
Bug on gunbad quest art da feed

### ISSUE THREAD

**Issue by Inconnuee** [WarEmu/WarBugs#15225]
Hi here,

We just down art' da feed for the 3rd time for me and when i go to valid the quest i took the chest and valid the quest, nothing anormal but
In my inventory that gave me the tincture...
Chest was my last piece in gunbad so i took care to take the good reward and that tincture appear in my bags...

**Expected behavior and actual behavior:**

Valid the quest and get the red eye chest

**Steps to reproduce the problem:**

Guess do and retry to valid the quest again but that took me 1 month to up grp and loot that boss

**Testing Screenshots/Videos/Evidences (always needed):**

![Chest red eye](https://user-images.githubusercontent.com/54858232/70096836-4b891780-1628-11ea-9577-064a4cf21de9.png)

**Comment by Lheana** [comment]
When I click on the chest, I get the chest and not the dye. I leave it open for 2 weeks.

**Comment by Inconnuee** [comment]
I see but how can that arrive? lag server? there is the screen dont know how this happend 
but was a long farm (finding group etc my guild group was here just for help me to get that piece 
guess you can understand how i can be disapointed ...

Is there an exchange possible with game master ? cause i really dont need that tincture hope you can understand i know the server is laggy maybe i click on a bad laggy moment server really dont know but just want to get that piece and stay definitely away from that gunbad xD

**Comment by Lheana** [comment]
I have no idea how it could have happened, except from an error when you chose the rewards.
No there is no exchange possible. And even if we understand it may take time to do the quest again, the quest is repeatable, so nothing prevents you from getting the chest.

**Comment by Inconnuee** [comment]
Ok but why took a tincture if the chest is the last piece i need ?
Can understand some manip can be hard but seriously i dont know what answer to you the server is really laggy any fort make freeze the server ^^ so if i have to do that quest again it will make me crasy :D

**Comment by Kabucoror** [comment]
Finished the quest right now and had no issues in picking up the chest.

**Comment by ChicagoJoe999** [comment]
I finished the quest, selected chest, got tincture.  Am a WP Bamatu.  May be selection issue with a particular class?

**Comment by Inconnuee** [comment]
You got the same problem chicagojoe999? i cant really help you cause im asking too why this appened 
sorry for your loot mate i know how it's frustating

**Comment by Inconnuee** [comment]
> I have no idea how it could have happened, except from an error when you chose the rewards.
> No there is no exchange possible. And even if we understand it may take time to do the quest again, the quest is repeatable, so nothing prevents you from getting the chest.

Thx for your answer lheana this is principally my job and my life who dont give me many time to do this dungeon as the player who need is quite rare i think i will put the game on the side for a bit time to think to something else ty
