### ISSUE TITLE
Blue "Sentinel" weapons and cloaks have too low sell price

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#15229]
**Expected behavior and actual behavior:**

Blue sentinel cloaks and weapons have very low sell prices. I would expect them to at least have a higher sell price than the green "Precursor" items which typically sell for 56-76 silver.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Falinsil_065](https://user-images.githubusercontent.com/7400/70162400-e253e380-16bd-11ea-8796-88e0f4922dff.jpg)
![Falinsil_064](https://user-images.githubusercontent.com/7400/70162405-e41da700-16bd-11ea-8ab8-5ee4cfaebc59.jpg)

**Comment by Kaelang** [comment]
This has been address in todays patch.
