### ISSUE TITLE
Missing reward from fort

### ISSUE THREAD

**Issue by sherlock-edholmes** [WarEmu/WarBugs#15239]
I came to shinning way destro warcamp before eaitiene lock from the last bo. I try to gank some order at uthorin siege camp. I got a chat massage from the game it wrote I didn't got any reward and I should bugreport it with details how I came fort.
It was a yellow massage from the system. If you need more information plz write me I try to help. If you don't need at all and this massage was useless  then sorry.

**Comment by sredddd** [comment]
Same issue. 'you are not part of this fortress' message upon fort starting. 

Failed our keep defense in chaos wastes. Then failed to push while they were on lord. Walked into The Maw when chaos wastes lord was ~30%. Was there the entire time and the yellow 'not part of fort, no rewards' spam randomly.

**Comment by Natherul** [comment]
same as https://github.com/WarEmu/WarBugs/issues/15199
merging
