### ISSUE TITLE
Trail of Darkness quest in Chrace bug

### ISSUE THREAD

**Issue by valkeera** [WarEmu/WarBugs#15235]
Right-click on the Dark Elf Forces Report quest item in indicated quest waypoints doesn't advance the quest.

This might've stopped working about a week ago, I was previously able to complete this quest with different characters.

![Cirthanir_000](https://user-images.githubusercontent.com/58527250/70168819-e38b0d80-16c9-11ea-9120-ac7726ba6baa.jpg)

**Comment by Lheana** [comment]
You just have to stand at the right place inside the quest marker to use the item.
