### ISSUE TITLE
Scaly Skin: Cannot Equip an Item That's Stacked, Please Report This to the Bugtracker

### ISSUE THREAD

**Issue by DayleD** [WarEmu/WarBugs#15241]
Scaly Skin stacks, and is not usable when stacked.

**Expected behavior and actual behavior:**

I expect to be able to use scaly skin.  I don't know if it was ever meant to drop more then once.

**Steps to reproduce the problem:**
Kill fire lizards in the fire lizard cave in 'The Blighted Isle' until multiple skins drop.
Right click skins.
Error message will display.

**Comment by CircuitByrd** [comment]
![scalyskin](https://user-images.githubusercontent.com/26975895/70344620-bcdeeb00-181f-11ea-8985-06f573019fe2.png)

**Comment by Lheana** [comment]
Please open a new report for the message that appears.
The Scaly Skin will no longer be stackable with next patch, thus you'll be able to equip it to trigger the title of the unlock.

**Comment by valkeera** [comment]
Btw this happens to all stackable items that are "equippable" - e.g. shining rings or bat wings for the pockets, or talismans that are stacked and you want to fuse them into equipment. Workaround is to "un-stack" them first by Shift+right click.
