### ISSUE TITLE
[Item] BW t2 inf rewards missing stats

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#1524]
[Spite's Ashboots ]
http://www.arsenalofwar.com/armor/Order/Spite's%20Slippers
Also name of the item seems wrong.

[Ashboots of Thunder]
http://www.arsenalofwar.com/armor/Order/Ashboots%20of%20Thunder

**Comment by Evildoor** [comment]
Side note - IIRC, many other classes have this problem with missing stats for ORVR influence.

**Comment by Meralors** [comment]
Fixed those items, live next patch
