### ISSUE TITLE
Sankara Respawns with 0 second delay

### ISSUE THREAD

**Issue by DayleD** [WarEmu/WarBugs#15240]
Hi, first bug report, please forgive any formatting issues.

Sankara, a lizard NPC in the Fire Crystal Caverns, respawns immediately.
I don't mean rapidly, but a 0 second delay.  By the time I'm looting the corpse, it's attacking me again.  Only choice are flee or die.

**Expected behavior and actual behavior:**
I expect at least fifteen seconds between respawns, but this NPC is somehow set to 0 seconds.

**Steps to reproduce the problem:**
Kill Sankara. 

**Testing Screenshots/Videos/Evidences (always needed):**
Forgive me, I don't know how to record video, programming isn't my background.

**Comment by CircuitByrd** [comment]
I can confirm this. They spawn much faster than other mobs in the area. Blighted Isle, just west of the Thanalorn Forest PQ.

**Comment by Lheana** [comment]
I killed the lizard several times and I could not reproduce it. I leave it open for 2 weeks in case where you have more information.
