### ISSUE TITLE
No token received for fortress

### ISSUE THREAD

**Issue by Screwgrim** [WarEmu/WarBugs#15244]
Hello, I have done the fortress of Shinning Way and received 0 token for. 
I played my squig herder.
It is not the first time that this happens....
Could you look at the reason what this happened? and give me the 4 tokens for the attack (lost) ?
Thank you

**Comment by raptrr** [comment]
1.) You need to provide some more information, like char name, time / date. 
Did you get the yellow server msg.? Maybe you just did not contribute enough to earn a reward.
2.) We don't hand out any rewards / token / gold, etc.

**Comment by raptrr** [comment]
https://github.com/WarEmu/WarBugs/issues/15246
