### ISSUE TITLE
No token in Fort

### ISSUE THREAD

**Issue by petocask** [WarEmu/WarBugs#15246]
Hello,

I did one forteress this mornig but i don't have a token, the forteress eataine win but i dont i receive my 6 tokens.

Could you send me then please. i play this forteress this caracter "frapadingue"

**Comment by raptrr** [comment]
1.) No, we don't hand out any tokens / currency / loot, etc.
The Bugtracker is for reporting issues and bugs, not to ask for loot.

2.) You received the yellow server message?
Maybe you just did not contribute enough to earn a reward.
