### ISSUE TITLE
Quest: "Sea Guard Memorial" does not appear on minimap.

### ISSUE THREAD

**Issue by DayleD** [WarEmu/WarBugs#15242]
The quest Sea Guard Memorial can be obtained by clicking on the book at The Blighted Isle around 45584, 23345, but it doesn't show a green icon on the minimap.

**Expected behavior and actual behavior:**
I expect to see available quest givers on the minimap, but this one is hidden.

**Steps to reproduce the problem:**

Have not yet completed the quest "Sea Guard Memorial".  Approach the questgiver (a book).  See minimap.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
GameObjects are not meant to have a green icon for quests. Only NPCs do.
