### ISSUE TITLE
[City Siege] After a draw in stage 3 one king should be killed

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#15257]
**Expected behavior and actual behavior:**

After a draw in stage 3 you get a message that the defenders has killed the king. But he isn't actually killed. Instead he just continues fighting.

**Testing Screenshots/Videos/Evidences (always needed):**

![Lotharic_297](https://user-images.githubusercontent.com/7400/70398771-15c8a200-1a1f-11ea-9cd9-8dca9229261a.jpg)

**Comment by MaxHayman** [comment]
Thanks
