### ISSUE TITLE
City Siege Libraly Chaos Portal

### ISSUE THREAD

**Issue by Vicgrim** [WarEmu/WarBugs#15259]
Only one man can interact chaos portal at the same time. And group cannot summon "npc" because if you move away for 10-20 ft from portal "summoning buff" was disappeared
 
![Vicgrimm_017](https://user-images.githubusercontent.com/51807854/70399037-f6874000-1a31-11ea-96a2-2315c6097f55.jpg)

**Comment by MaxHayman** [comment]
The buff disappearing if you get too far away is intensional.

However the multiple interacts needs to be fixed.
