### ISSUE TITLE
Multiple scenario issues post-patch

### ISSUE THREAD

**Issue by Rydiak** [WarEmu/WarBugs#15251]
Scoreboards aren't updating while the scenario is active (but they do update at the end).
Leave Scenario button on scoreboard is non-functional at the end of the scenario.
Scenarios are not kicking you out after the 1:30 timer once a scenario has ended.  You have to book out.
After you book out you are still stuck in the Scenario party and cannot queue again (clicking the scenario button simply brings up the scoreboard from the scenario you just left).
After you book out you are still considered in combat, and cannot log-off (have to force-close the game).

**Comment by raptrr** [comment]
Should work again, please open a new issue if new stuff comes up.
