### ISSUE TITLE
[City Siege] Champion killed before stage 3 started made it stuck

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#15256]
**Expected behavior and actual behavior:**

One of the destruction champions didn't use Army recall at the end of stage 2 and got killed before stage 3 started. That meant there was only 3 champions to kill in stage 3, so it was impossible to complete the stage and kill the king.

Players should probably not be made into champions before stage 3 actually starts.
It would also be good if army recall was automatic.

**Steps to reproduce the problem:**

Kill a champ when stage 2 ends, but before stage 3 starts.

**Comment by MaxHayman** [comment]
Thanks for information
