### ISSUE TITLE
City Siege no warband interface

### ISSUE THREAD

**Issue by Vicgrim** [WarEmu/WarBugs#15254]
No warband interface in Altdorf, if you dont have some addons you dont see another group players and some times dont see other players on map.
![Vicgrimm_020](https://user-images.githubusercontent.com/51807854/70398403-0c920200-1a2c-11ea-820d-b0de72b0a4ef.jpg)
![Vicgrimm_025](https://user-images.githubusercontent.com/51807854/70398481-05b7bf00-1a2d-11ea-85e7-1e6c7cc478e9.jpg)

**Comment by sullemunk** [comment]
The city sieges is counted as a scenario and uses the scenario party interface and not the usual warband interface

**Comment by Vicgrim** [comment]
yes, sorry its my fault i forget to chek SC intarface settings.  but i actualy have party tickets in group selector and i didnt change nothing before Altdorf.  I played SC a few min ago and i can saw another groups. Maybe its dosnt works beacuse Altdorf is not regular SC. 
![iterfase](https://user-images.githubusercontent.com/51807854/70400248-00617100-1a3b-11ea-9d46-c82b437a8af2.jpg)
