### ISSUE TITLE
No granted ability

### ISSUE THREAD

**Issue by Cupid619** [WarEmu/WarBugs#15258]
During phase 3 when all other could port to Karl Franz with a granted ability, I had none to follow them. I checked stance bar and granted abaility bar but I had only the zealot buff.
I had finaly to die to get ported into the palace room with the others and Karl Franz

**Comment by MaxHayman** [comment]
You can optionally walk to the palace, but I will look into this.

**Comment by Cupid619** [comment]
The palace door was closed at this moment. No way to enter trough the door

**Comment by MaxHayman** [comment]
Should be fixed
