### ISSUE TITLE
City Siege respaun farming.

### ISSUE THREAD

**Issue by Vicgrim** [WarEmu/WarBugs#15255]
After siege has been failed, other players can farm you on respawn point
![Vicgrimm_030](https://user-images.githubusercontent.com/51807854/70398673-e91c8680-1a2e-11ea-9d13-fdb681cf3241.jpg)
https://youtu.be/oFFrYpIfafg

**Comment by MaxHayman** [comment]
The scenario automatically closes after 2 minutes.
