### ISSUE TITLE
[City siege] BW classmechanic as Champion bug + feedback&bugs

### ISSUE THREAD

**Issue by BomblingTV** [WarEmu/WarBugs#15266]
First of all this was my point of view from middle of stage2 and onwards with selfcommentary:
https://www.twitch.tv/videos/518979000?t=00h47m52s
(20minuts of end of stage2+3 fighting and going in blind while reacting to the objectives and scripts+mechanics)
Here is a list of issues I experienced or saw occure in the instance I was in

- partymembers in the scenario-groups had bugged UIs and couldnt see some of our groupmembers on their Enemy addon UI and had to manually find them in the sea of people to click on them to guardswap/heal our group. From stage1 get-go point and onward. (from guild healer's PoV: https://media.discordapp.net/attachments/578367847588167701/653514161514610698/Lilypop_.jpg?width=968&height=409 )
- Stage1 in Altdorf players can punt and get punted into the east side of the map and be taken out of the fight for good, or untill player killed. (suggest barrier along the river) https://imgur.com/a/YY4ULy9
- Stage 1+2 one player got player punted and got stuck. https://imgur.com/a/rf3UxFO
- Stage 1 Altdorf Libary we saw some yellow announcement text about 6players needed to summon lord of change, never happend. not sure if the attacers just didnt try or not working.
- Stage 2 Lord pathing seemed odd the lord resat his pathing at one point as shown in the VOD i linked. And then proceeded to disappear after reaching the middle bo top of the stairs and suddenly we reached Stage3
- Stage2 transitioning into Stage3. While there was a 1min transitioning timer the Champion players were still selected and could be killed/kill while the timer was counting down before stage3 began.
- Stage3 Champion player's Healthbar was really really akward for healers as the massive hp pool showed the Champ-players to be close to death, then stable, then close to death. (suggestion uppon getting seletected as champion you get full health of the 100k/100k)
- Stage3 Brightwizard's Class mechanic "Combustion" seemed to be resetting to 0 constantly and pretty much made the Champeon BW deal very very little damage

-Stage 3 mechanics feedback:
Both realms got champions selected, the shamen died before stage3 even begun. The Granted ability was showing on my UI, it was also working (I guess?) but do we even need this, it seemed like alot of additional lag with screenshakes and extra meteorors flying all over the place.
The additional stats from being a champion maybe worked, was hard to tell as my combustion was close to 0 if i wasnt prema building +20 with flamebreath. I didnt see any instances where my damage was increased vs normal players and vs champion players it seemed meh at best too.

After all 4 Attacking champeon from Destruction had been defeated our champeons could correctly attack their king, while our normal players could do aoe attacks but not autoattack or singletarget to get him down.

While the instance was ended the winning side could continue to farm kills at the respawnpoint for Destro. Also Aoe attacks was going through the barrier(assume pulls work too!) while stage3 was on going.

After getting kicked from the instance the Champeon buff and stats remained on my BW in the orvr lakes.

**Comment by MaxHayman** [comment]
A lot of these have been fixed, pleas repost any further issues individually.
