### ISSUE TITLE
No token in forteress

### ISSUE THREAD

**Issue by petocask** [WarEmu/WarBugs#15265]
Hello, 

I do a forteress at instant in voie etincellante (elf) it's finish at 8h52 and i don't have receive a token, it's a second time, i finish 168 at roll, i receive 3566 xp, 530rr but i dont receive my 4 token invader....

What is a probleme with my caracter, it's a big bug ??

Last forteress not 6 token, this forteress not 4 token... my caracter is bugged for have token in forteress ?

Please help me, 45 minuts for dont touch token...

Thanks

My name caracter : Frapadingue (black orc)

**Comment by petocask** [comment]
I have win the fortess at shining way and i contrib on 2 flags and most kill, aggro lord and i dont have no rr, no experience and no token. Please help me. what is a probleme ??

**Comment by raptrr** [comment]
Did you receive the "yellow server message"? Did you really participate in the loot roll when the lord was killed?

Can you, next time it happens, make some screenshots of rolls, inf/xp gain, etc or provide a short video clip?
