### ISSUE TITLE
Raising Potion making and bugs found

### ISSUE THREAD

**Issue by Stinkypants** [WarEmu/WarBugs#1526]
This will be a work in progress. So far what I've found is the multiplier, improved crit chance, and extender materials do not appear to work. Also as of this writing I can only make rank 5 potions using skill level 50 materials. The healing potions are weird though, they pop out as rank 25 and those can be made with skill level 25 materials.

**Comment by Stinkypants** [comment]
Oh, forgot to mention that the improved chance, multiplier, and extender materials are not consumed on use.

**Comment by Stinkypants** [comment]
Just reached skill level 75 of potion making, the extender worked but the potions I received were for rank 35. This was using skill level 75 materials. Also I cannot reap certain plants. The Goldweed stabilizer plant cannot be reaped for seeds and resin.

**Comment by Stinkypants** [comment]
Okay, my first round of potions used butchering materials to create the rank 35 potions. I just used plants from cultivating and received rank 10 potions for skill level 75 materials.

**Comment by Stinkypants** [comment]
Molotov potions can be made and provide skill ups but do not appear in my inventory.

**Comment by Stinkypants** [comment]
Wispy Dandelion skill level 75 just gave me a rank 40 action potion.

**Comment by Stinkypants** [comment]
Several materials from butchering and cultivation cannot be vendored. They have a list of no sell price.

**Comment by Stinkypants** [comment]
Not receiving gore from butchering and also scavenging produces watering cans iirc.

**Comment by Stinkypants** [comment]
Should be able to get soil from one of the gathering skills also, I cannot remember which however

**Comment by Kushido** [comment]
so yea, [Glinting Goldweed] and [Prickly Goldweed] stabs cant be converted to seed, tooltip have info about possible converting, but by pressing "Ctrl+right click" nothing happening

**Comment by Kushido** [comment]
[Sullen Marsh Root] not converting to seeds back, same with goldweed

**Comment by Kushido** [comment]
trying to craft 150 and 175 healing potions (1lvl container+150/175ingr+3stabs)
skill lvl going up, but have no potions in my backpack

**Comment by Kushido** [comment]
tried to craft 50/75lvl ingr for healing potions - same, ingridients disapearing and i have no potions in my backpack
if i buy main ingr for healing potion - i can craft it and have healing potion in my backpack
but im using 1lvl container+1lvl ingr+1 stab 50lvl = healing potion for lvl 25 characters

**Comment by TheRealReginn** [comment]
Healing potions made with Spumepetal do not craft.  The resources are used up, but the product does not get produced.

**Comment by nalgol** [comment]
goldweed is fixed heal and ap potion making is fixed aswell

**Comment by Kushido** [comment]
at 200lvl Apothecary you can craft ok only HP/AP potions with 1lvl main ingr (with 200lvl stab and multiplier) for 25lvl character
using other main ingr for this type of potions will give you nothing except ingridients spending

**Comment by nalgol** [comment]
i just tryed at lvlv 200 apo all hp main ingredeances from 25 - 200 every one create the right potion ?

**Comment by knightningale90** [comment]
Hello guys. I asked the people that I know and it seems that no one is getting any special moments from cultivating lv 200 seeds. If my memory serves right, the lich purple or a certain red dye come from a special moment from growing lv. 200 seed, so I wonder if it is bugged?

**Comment by GreatHarlequin** [comment]
Anyone else get their cultivating freezing and not being able to harvest? Sometimes I cultivate for 15 mins but often it only lasts 5mins before freezing and I need to log off and back on again.
