### ISSUE TITLE
Karl Franz Fight at city siege

### ISSUE THREAD

**Issue by Talossar** [WarEmu/WarBugs#15261]
**Expected behavior and actual behavior:**
Actually the fight should be at the throne room but instead Karl Franz can be pulled/aggroed to the Destruction's spawn allowing the attackers to kill him without any interference from the defenders.

**Steps to reproduce the problem:**
Reach the final step of the scenario of Altdorf siege and taunt/challenge Karl Franz or just aggro him with healing skills.

**Testing Screenshots/Videos/Evidences (always needed):**
Please see the video attached on the link where clearly you can see KF getting pulled and killed on attacker's respawn.

https://www.twitch.tv/videos/518980158?t=1h4m26s (Thanks to PnP twitch stream :D)

**Comment by MaxHayman** [comment]
The pulling of Karl needs to be fixed.

However where the stage 3 battle happens depends on the outcome of stage 2.

**Comment by Talossar** [comment]
> The pulling of Karl needs to be fixed.
> 
> However where the stage 3 battle happens depends on the outcome of stage 2.

My only experience has been as attacker and we pushed to the castle for the final battle dunno if this issue will happen aswell if the attackers fails on the previous stage.

**Comment by MaxHayman** [comment]
Fixes and changes have happened since then. Please repost any further issues.
