### ISSUE TITLE
Capital Siege Bug

### ISSUE THREAD

**Issue by Fiirkraag** [WarEmu/WarBugs#15260]
Good day

Char: Warpriest. 40/78
Nickname: Tiot

Stage 3 of city siege. One of heroes, Engra, reached WC. I become champion. But had only my real HP at start, about 8k, not full champion HP. Was killed near our WC. After release still had champions 107k+ hp in max. When was attacked later my HP constantly jump between max hp and real leftover. Become unkillable.

**Comment by Natherul** [comment]
should be fixed with patch as of today
