### ISSUE TITLE
City siege, teleport bug in stage 3

### ISSUE THREAD

**Issue by Ladycaska** [WarEmu/WarBugs#15263]
Expected behavior and actual behavior:

During stage 3 i was suddenly teleported in the Nordland map. I was alone, no mob or npc. I have tried to use the teleport from the book but my respawn was in the middle of a blue sky... then i have tried to use guild recall scroll, /stuck or reload ui but nothing happened. I could not read the chat cause a message of allarm has been continually repeated and all the others messages disappear.

I was forced to do alt+F4 and close the game.

Steps to reproduce the problem:

I don't know, it happened suddenly and I didn't do anything special

Sorry but i couldn't take a screenshot

**Comment by MaxHayman** [comment]
Fixes and changes have happened since then. Please repost any further issues.
