### ISSUE TITLE
City Stage Bug name in one instante 

### ISSUE THREAD

**Issue by Gagaddon** [WarEmu/WarBugs#15264]
**Expected behavior and actual behavior:**

I was in Dellano and got a pop to join city stage while im was qq from altdorf ,  but game crash when im was in the logging page. when back in game was in praag but it seems that my name was in a instance because someone ask me to change groups, what im could not do because we arent in same place/instance. Im back qq thinking to back to their instante and was able to join in again but it was a diferent instance with different people while my name was still showing up in the first instance that im was trying to joining in earlier. 
So apologize for any incovenience.

*Steps to reproduce the problem:**

Somehow be kick or crash from game teleports you to your book binding spot and not to you original city pop/place. And qq again sends you to a different one instance,  while your name still show in the first one instance that you was trying to join in.

**Comment by MaxHayman** [comment]
Fixed.
