### ISSUE TITLE
Don't RR on my caracter

### ISSUE THREAD

**Issue by petocask** [WarEmu/WarBugs#15269]
Hello,

On my character I find myself in dream to have no rr each time I kill a character order. I get 1RP each time. The name of my character is "Frapadingue" black orc lvl 30 r 44.

Which also means that in fortress I do not get any more contribution, neither rr nor token.

Can you help me please understand why?

**Comment by raptrr** [comment]
Are you playin in Eataine right now? If so, Order has 200% AAO.
