### ISSUE TITLE
City Siege portal to BO

### ISSUE THREAD

**Issue by Vicgrim** [WarEmu/WarBugs#15262]
Only one man can use portal to BO at the same time.  You cant use portal and fast go to BO when anybody use it. its litlle strange because  City Siege time has limited and you need to stay in queue to teleport.
![Vicgrimm_022](https://user-images.githubusercontent.com/51807854/70399254-795cca80-1a33-11ea-8eef-b83381d666fc.jpg)

**Comment by MaxHayman** [comment]
Thanks for this
