### ISSUE TITLE
[Blackorc] Loudmouth Tactic - Critical chance not working

### ISSUE THREAD

**Issue by neviorusso88** [WarEmu/WarBugs#15268]
The Loudmouth Black Orc Tactic (damage when War Bellow triggers) damage can't critical hit, as showed in the video

https://www.youtube.com/watch?v=YirvzLfWHZ0&feature=youtu.be

**Comment by raptrr** [comment]
Procs and tactics are not supposed to crit / gain stats. This is intended and was part of a patch back some time.
