### ISSUE TITLE
Fort xrealm block not working.

### ISSUE THREAD

**Issue by Tushii** [WarEmu/WarBugs#15274]
Just did Shining way fort (11:00am GMT 10/12) and had the message "you are not a part of this fort and as such will not receive any reward".  Can only assume this is the new xrealm block as I've never had this message before but it should never have been shown.

My choppa (Splatter) was the first char I'd logged into, didn't swap from any other char, not even another destro char.  Joined the fort by running through the rvr zone from Eataine warcamp.  Obviously fort ended and I missed out on the rr and medals

**Comment by Natherul** [comment]
no, that message is not part of xrealm block but it is to debug an issue where some players do not get rewards because they did not get added correct internally to the fort. The META ticket for this is https://github.com/WarEmu/WarBugs/issues/15199
