### ISSUE TITLE
PvE Quests: Shadowlands (Re-Usable Quest Objectives for Many PQs/Quests)

### ISSUE THREAD

**Issue by CircuitByrd** [WarEmu/WarBugs#15278]
**Expected behavior and actual behavior:**
In the quest Mirelen's Lost in the first PvE camp in the Shadowlands for Order, the player is tasked with rescuing some citizens of Mirelen from the dark elves. They're found in cages surrounded by enemies. Pretty typical. Expected behavior is that you have to free ten individuals by clicking on their cages (after fending off the captors).

Actual behavior is that you can right click on the same cage 10 times with no delay. Suggest adding a short timer before the cage can be re-used, as is in place on many other quests.

**Steps to reproduce the problem:**
Acquire Order PvE quest in Shadowlands, go to indicated area, click on cage 10 times and complete quest.

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/26975895/70741155-4c810f80-1ce0-11ea-94c9-ad1e26fc6c98.png)

**Comment by CircuitByrd** [comment]
This issue may be more widespread, and affect all quests with specific objective types. I found the Ch. 6 Easy PQ's stage 2 (uproot shadowthorn) works the same way. A single item can be clicked repeatedly with no delay to satisfy the quest.

![image](https://user-images.githubusercontent.com/26975895/70815844-e229a700-1d93-11ea-9a03-08126bcf5d8a.png)

**Comment by CircuitByrd** [comment]
One more for good measure. Stage 2 of the Easy Ch. 7 Order Shadowlands PQ. Same issue. I expect it's pretty widespread, though not *all* useable objects act this way. Most remove your interaction ability after one use.
![image](https://user-images.githubusercontent.com/26975895/70820345-0c806200-1d9e-11ea-90b6-e2526f2dfcb4.png)

**Comment by CircuitByrd** [comment]
And this one.
![image](https://user-images.githubusercontent.com/26975895/70820394-3043a800-1d9e-11ea-8c2e-ab211a78face.png)

**Comment by Lheana** [comment]
Please one issue per report next time.
The main (first) issue reported will be fixed with next patch. The 3 other issues are not the same issue, it's a general issue with PQ gameobjects.

**Comment by CircuitByrd** [comment]
Apologies Lheana, I initially thought the issue was with a single public quest, then found a series of others. Is there already an bug filed for the general PQ object issue? I can't find one. If not, I'm happy to create it.

**Comment by Lheana** [comment]
There are several reports for different PQs, so we are aware of the issue, and will fix it asap.
