### ISSUE TITLE
Huge Bug Black Orc "You wot" Increase Armor Debuff By 30% !

### ISSUE THREAD

**Issue by admaska2** [WarEmu/WarBugs#15279]
"You wot" 

![you wot](https://user-images.githubusercontent.com/43276959/70768901-9bbe5300-1d67-11ea-9fe8-1b5a3e701874.png)

The Bug is : It Increase By 30 % Evry Armor debuff you have On you !

https://recordit.co/imiPwaafET
https://recordit.co/JYP6b5nY6D

For WL 1820 armor debuff insteed of 1400 ( 1400 X 30% = 1820)
Same for demolishing strike

5869 - 1820 = 4049

![](https://cdn.discordapp.com/attachments/631852077047480330/654897048411308042/younot_nodebuff.png)

![](https://cdn.discordapp.com/attachments/631852077047480330/654897051506704404/youwot_debuff.png)

Its Maybe the Same for RESIST debuff !!!  i dont have test

**Comment by raptrr** [comment]
I got confirmation, that this is working as intended.

**Comment by admaska2** [comment]
Lol Nice balance
