### ISSUE TITLE
City siege additional unexpected lvl 55 mobs

### ISSUE THREAD

**Issue by acidicrain** [WarEmu/WarBugs#15270]
in altdorf there are 55 level mobs around the equipment sellers, would not expect these there as they can be easily used to  pull a wb into the area.

**Expected behavior and actual behavior:**
mobs not to be presant

**Steps to reproduce the problem:**
they were in the instance.

**Testing Screenshots/Videos/Evidences (always needed):**

https://youtu.be/4G5TL84gBuE

**Comment by MaxHayman** [comment]
These will be removed in a future revision

**Comment by MaxHayman** [comment]
Closing for now
