### ISSUE TITLE
My bug tracker mount is not account wide

### ISSUE THREAD

**Issue by tester352** [WarEmu/WarBugs#15275]
It's not in account entitlements, can this be changed, thank you.
![Matttheus_086](https://user-images.githubusercontent.com/14897323/70563618-8f19df00-1b5c-11ea-8bc8-db6800bc15c9.jpg)

**Comment by tester352** [comment]
https://media.discordapp.net/attachments/593870352585588824/600923665835622400/Matttheus_074.jpg?width=1202&height=677

**Comment by tester352** [comment]
![this is my mount](https://user-images.githubusercontent.com/14897323/70564874-f173df00-1b5e-11ea-9858-02fda4e64d3f.png)

**Comment by Natherul** [comment]
this sohould not be in the bugtracker, its not a bug. Please contact me directly on Discord.
