### ISSUE TITLE
Order Players hacking?

### ISSUE THREAD

**Issue by Goliathus-Git** [WarEmu/WarBugs#15271]
https://imgur.com/QrXB3pn

**Comment by Rydiak** [comment]
Since you gave no other information, I am going to assume this was near a Warcamp.

**Comment by raptrr** [comment]
Just the Log does not help us. Where did it happen? Like @Rydiak mentioned, this might be close to a Warcamp.

Provide more information, else I'm gonna close this in 2 weeks.
