### ISSUE TITLE
Buying stack of non usable items loses your money

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#1527]
reproducable:

go to vendor, use shift to buy stack of e.g. 10 items that are not usable to you. Warning apears "this is not usable, still buy" click yes, items dissapear so does the money the 10 items would cost.

**Comment by Evildoor** [comment]
I do believe this is the same problem: https://github.com/WarEmu/WarBugs/issues/1291

**Comment by Tiggonos** [comment]
yes, sorry
