### ISSUE TITLE
Placeholders in Linked Quest Descriptions

### ISSUE THREAD

**Issue by CircuitByrd** [WarEmu/WarBugs#15272]
**Expected behavior and actual behavior:**
Expected: When clicking on the link for a quest, whatever appropriate description/details should be shown in the box that pops up.

Actual: When clicking on the link for a quest, placeholder text shows for the short and detailed descriptions. Objectives show up fine.

**Steps to reproduce the problem:**
Click on a linked quest to preview it. May be specific to certain quests. Extensive testing not carried out.

**Testing Screenshots/Videos/Evidences (always needed):**
![2019-12-09_18-59-44](https://user-images.githubusercontent.com/26975895/70486167-6fc87680-1ab6-11ea-955b-d57d4e0336e5.png)

**Comment by Lheana** [comment]
This has been fixed.
