### ISSUE TITLE
Knockback interrupt[emulator]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#1528]
knockback shouldn't interrupt casting but only channeling, it worked well until today or eysterday so far.

**Comment by ozarmidrashim** [comment]
https://github.com/WarEmu/WarBugs/issues/1450 has been reopened. Discuss there.

**Comment by taccr** [comment]
Punts did interrupt unless you had FM up.
Very important for chain interrupting resses.

**Comment by Tesq** [comment]
i checked, my bad it does interrupt you can close.
