### ISSUE TITLE
PvE Quest: Shadowlands - Enduring Hatred - Friendly Mobs Attack Player (Can't be Attacked)

### ISSUE THREAD

**Issue by CircuitByrd** [WarEmu/WarBugs#15280]
**Expected behavior and actual behavior:**
During the Order Shadowlands quest: Enduring Hatred, you are sent to harvest crystals in a cave full of both hostile dark elves, and their friendly/neutral thralls. If an AOE ability is used, the friendly servants take damage and begin attacking you, while still not being hostile/attackable directly. The only way to get them to stop is to run far enough that combat ends, or kill them using solely AOE abilities.
Expected behavior is that of all other friendly entities: being unable to be damaged by player's AOE.

**Steps to reproduce the problem:**
Go to cave, use an AOE ability. I don't believe the quest itself is directly involved.

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/26975895/70774031-ad3f3500-1d3e-11ea-92c0-63f010cbba4f.png)

**Comment by Kabucoror** [comment]
fixed with next patch
