### ISSUE TITLE
Loot roll not recieved

### ISSUE THREAD

**Issue by Bahlthazar** [WarEmu/WarBugs#15284]
I recently killed the fleshrender lair boss in kv, and won the roll on said loot (Dark band of the fleshrender), but the item never appeared in my bags or came in the mail. I had available bag space, I didn't dc, nothing out of the ordinary, but I never received the item.

I contacted a gm immediately afterwards, they told me to use the in-game ticket system, then when the ticket was finally answered they told me to use the bugtracker.

![Bahlthazar_104](https://user-images.githubusercontent.com/58861102/70824299-97b22580-1da7-11ea-8411-895407ab3b72.jpg)

**Comment by raptrr** [comment]
Maybe wait for a server restart and report back, if the item came via mail?

**Comment by raptrr** [comment]
We had plenty of restarts, can you confirm if you got the mail?
