### ISSUE TITLE
[Zealot] bugget weapon preservation proc.

### ISSUE THREAD

**Issue by alubert** [WarEmu/WarBugs#15283]
![Hurubek_001](https://user-images.githubusercontent.com/51048211/70797536-ffb33c80-1da4-11ea-918b-6efcec67f85d.jpg)

Bloodlord influence weapon "Evil" is bugget.
As you see on print screen wounds proc increase wounds only 80 not 110 like "Perservation" tooltip.

**Comment by alubert** [comment]
My bad. Ofc its BB/BE inf weapon.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/14920
