### ISSUE TITLE
Invader vendor missing in Reikwald (outside Altdorf during City siege)

### ISSUE THREAD

**Issue by dbddhkpuka** [WarEmu/WarBugs#15292]
**Expected behavior and actual behavior:**

Since all other vendors grouped by RvR and SC gear are in the area (6k, 4k) in Reikwald I would exspect the Invader vendor to be somewhere, too, but there is none.

**Steps to reproduce the problem:**

Go to Reikwald during Altdorf siege.

**Comment by Rydiak** [comment]
The vendor that sells Oppressor emblem weapons is not present either.

**Comment by Kaelang** [comment]
Intended - Invader / Sov gear stays in the City during sieges.
