### ISSUE TITLE
[CITY SIEGE] Tchar'zanek seems confused

### ISSUE THREAD

**Issue by DanskuL** [WarEmu/WarBugs#15298]
Expected behavior:
if you pull the last boss in the City siege to far he'll reset to a certain point in the middle of the room
Actual behavior:
He'll gets stuck in the door turning and resetting constantly
**Steps to reproduce the problem:**
Pull Tchar'zanek outside the door to the throne room and enjoy.
Possible cause? both bosses seem to lack a reset point to which they reset which allows for them to get stuck outside their area of influence, which then keeps resetting him indefinitely many times.

**Testing Screenshots/Videos/Evidences (always needed):**
MaxHayman fixed it in the SC IC 4 by moving him

**Comment by MaxHayman** [comment]
Tchar will no longer be aggroed around and continue fighting Karl
