### ISSUE TITLE
IC Undercroft SC test

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15297]
**Expected behavior and actual behavior:**
When entering the sc you have to click the gates to exit out of spawn. 
Actual: The gates are clickable for others but not for that 1 unlucky person therefor trapping them in spawn.

**Steps to reproduce the problem:**

que for Undercroft sc try to leave spawn

**Testing Screenshots/Videos/Evidences (always needed):**

![Notaaoesorc_011](https://user-images.githubusercontent.com/43802105/70872097-0e4b5080-1f6b-11ea-85d3-59ec7c1b42cd.jpg)

**Comment by pikara** [comment]
Same happened to me. 
All i did where move ahead before time get to 0 and got ported back.
