### ISSUE TITLE
IC City Test: Portals to bypass Emissary funnel

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15296]
**Expected behavior and actual behavior:**
After order takes the slaneesh/BE bos 2 portals appear allowing for access to back ways to Emissary statue to break the gate funnel

![](https://www.photofunny.net/descarga.php?f=images/201912/16/1868315758199613252_.jpg)

. When actually running into the portals kicks you out into the Maw.

**Steps to reproduce the problem:**

Run into the portals 

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by MaxHayman** [comment]
Fixed yesterday
