### ISSUE TITLE
City Siege - Atldorf - Fell the Palace Door

### ISSUE THREAD

**Issue by Maltoon** [WarEmu/WarBugs#15293]
Destro PUG WB completed capturing the points around the city as well as "Pillage the City".
However we were not able to complete the "Palace Door" or "Burn the city" (due to Order extinguishing the fires) or "Kill enemy players".
I couldn't see the Summary due to using VinylUI setup (Summary was shown after leaving the city instance) but once the timer counts down without these completed should make the scenario harder rather than delay the stage, correct?

![2019-12-15 20_27_27-Warhammer_ Age of Reckoning, Version 1 4 8, Copyright 2001-2012 Electronic Arts,](https://user-images.githubusercontent.com/58115479/70868509-70ab4d80-1f79-11ea-8377-74becb08d2c6.jpg)

**Comment by MaxHayman** [comment]
The main objective was destroying the palace door, which I have fixed for next test
