### ISSUE TITLE
City Siege Test: Scenario Party button disappears after closing it

### ISSUE THREAD

**Issue by ChrisRBe** [WarEmu/WarBugs#15291]
**Expected behavior and actual behavior:**
* Entered Altdorf defense
* SC party window was open
* Closed SC party window
* Button to reopen is not visible on minimap
* /rel does get it back

**Steps to reproduce the problem:**
not tested

**Testing Screenshots/Videos/Evidences (always needed):**
![bug_1](https://user-images.githubusercontent.com/31167512/70867996-152e8f00-1f7c-11ea-9184-8ea3ab342680.png)

**Comment by Kaelang** [comment]
This has been addressed in todays patch.
