### ISSUE TITLE
Scenario objetives bugged

### ISSUE THREAD

**Issue by Talossar** [WarEmu/WarBugs#15299]
**Expected behavior and actual behavior:**
Some scenario's objetives are not working as intented, for example in Mourkain's temple if the item is reset (cuz someone went too close to his respawn with the item) not everyone will be able to see it again to pick it up at middle, and on Serpent passage were totally unable to pickup the item at all.

**Steps to reproduce the problem:**
Join an scenario with an "pick up objetive" (Khaine's embrace, Serpent passage, Mourkain's temple, etc...) and play it, usually after fist deliver or objetive reset it will get buggy.

**Testing Screenshots/Videos/Evidences (always needed):**
As you can see on the screenshots there weren't option to click on the objetive, the destro team was unable to pick up the objetive and that turned it into a free win for order side. (I understand this bug can work for each side, not crying about order win)

![Gitgudboyz_001](https://user-images.githubusercontent.com/58671918/70924736-58dfd200-202a-11ea-9537-561d020e22c0.jpg)
![Gitgudboyz_000](https://user-images.githubusercontent.com/58671918/70924737-58dfd200-202a-11ea-95f7-87f2677f819d.jpg)

**Comment by MaxHayman** [comment]
'twas hotfixed yesterday
