### ISSUE TITLE
3 morals in one time

### ISSUE THREAD

**Issue by Kirpich-74** [WarEmu/WarBugs#15294]
http://ipic.su/img/img7/fs/Masterok_027.1576442630.jpg

**Comment by raptrr** [comment]
Did it hit you 3 times? Or did you just look into the combatlog?
Maybe it was some kind of lag, that caused the log to be confused?

**Comment by Kirpich-74** [comment]
I watched  after the fight.there were a lot of different morals and I died almost instantly.

**Comment by raptrr** [comment]
So maybe it was just server lag and/or log error.
I'm gonna close this in 2 weeks, unless it happens to you again.
