### ISSUE TITLE
PQ boxes unlootable

### ISSUE THREAD

**Issue by hiddenagenda** [WarEmu/WarBugs#15290]
after the patch on 12/15/2109 the PQ boxes have become unlootable, have to wait to recieve the bags in the mail
![Grumbullz_005](https://user-images.githubusercontent.com/35900446/70867968-61ec7880-1f30-11ea-8bd7-5f529110d7ab.jpg)

**Comment by Lheana** [comment]
Works fine for me, Are PQ chests still untargetable for you?

**Comment by hiddenagenda** [comment]
this was fixed at some point  a short while ago, not sure when, sorry forgot to close the ticket
Jeff Norwick 

    On Friday, January 3, 2020, 08:07:40 AM PST, Lheana <notifications@github.com> wrote:  
 
 
Works fine for me, Are PQ chests still untargetable for you?

**Comment by Lheana** [comment]
No worries, then I close the ticket.
