### ISSUE TITLE
Box of Vanquisher's Medallions dosnt binde to pickup

### ISSUE THREAD

**Issue by Vicgrim** [WarEmu/WarBugs#15302]
**Expected behavior and actual behavior:**
Box of Vanquisher's Medallions fo 1 and 5 invader medallions dont binde to pickup
Its strange because all others boxes - binde to pick up.
they can be mailed. this way you can dress other characters (not only your own) in Vanquisher
or farm alot of purple talimaking ingredients.
**Steps to reproduce the problem:**
 buy box of Vanq and post mail to any charater.
**Testing Screenshots/Videos/Evidences (always needed):**
![Vicgrim_007](https://user-images.githubusercontent.com/51807854/70938977-5b592080-2058-11ea-8d53-e48671d53a54.jpg)
![Vicgrimm_035](https://user-images.githubusercontent.com/51807854/70939003-66ac4c00-2058-11ea-93cf-5217eff13377.jpg)

**Comment by MaxHayman** [comment]
@wargrimnir

**Comment by Vicgrim** [comment]
?

**Comment by Kabucoror** [comment]
fixed with next patch
