### ISSUE TITLE
City Siege: Champion hp bar

### ISSUE THREAD

**Issue by Vicgrim** [WarEmu/WarBugs#15309]
When I became a champion. my hp bar was stuck at 41k out of 107k. And when Order started attacking me, it started jumping from the minimum to the maximum.

Maybe this is due to the treatment applied to me or the skills that increase my HP  like Aegis of Orange Fire.

https://youtu.be/LWB3_IfzXGc
![hp bar](https://user-images.githubusercontent.com/51807854/71038695-7482cf80-2133-11ea-8d68-82bbf180f27c.jpg)

**Comment by Natherul** [comment]
should be fixed with patch as of today
