### ISSUE TITLE
WP prayer and tactic not registering the right damage.

### ISSUE THREAD

**Issue by Rilos** [WarEmu/WarBugs#1530]
Prayer of Righteousness paired with the damage tactic hits for a random amount instead of the 200 stated on the tactic.  

Of all of the times I hit someone, it wasn't a solid number.  It fluctuated somewhere between 120 and 140.

Tactic is Divine Justice. *edit* just tested it in PVE, works fine.  When I tested it I was in a scenario.

**Comment by Evildoor** [comment]
So, in PVP the fluctuation was caused by resists/guard/challenge/whatever, right?

**Comment by Rilos** [comment]
I didn't think of that. Perhaps you're right.

**Comment by Evildoor** [comment]
Ok, then i'm closing this.
