### ISSUE TITLE
Tor anroc lava death lights up revive button on self.

### ISSUE THREAD

**Issue by Rilos** [WarEmu/WarBugs#1531]
![borda_016](https://cloud.githubusercontent.com/assets/14109685/10118128/0175f67c-643e-11e5-9198-f125f2fc7e35.jpg)

**Comment by ozarmidrashim** [comment]
I think we need a whole new tag for how trivial this is.

**Comment by Rilos** [comment]
Just an excuse to jump into the lava I guess.

**Comment by Evildoor** [comment]
I'm not exactly sure, but it is possible that it was this way on live. Regardless of that, i don't see any reason at all why anyone should waste their time to fix this - grey icon or active icon, dead healers cannot use abilities, end of the story. Closing.
