### ISSUE TITLE
'Ere We Go' Guild bug, no one can talk/communicate in guild.

### ISSUE THREAD

**Issue by Nantroxss** [WarEmu/WarBugs#15314]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**
Join guild and try to speak in guild or have someone type a message while in guild.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by raptrr** [comment]
Did you guildleader set the rights correct?
You can disable a flag which allows players to chat in /g.

Can you make sure, this flag / role is set up correct?
