### ISSUE TITLE
Faewulf's Rest PQ unwinnable.

### ISSUE THREAD

**Issue by Velfirenze** [WarEmu/WarBugs#15310]
**Expected behavior and actual behavior:**

In the public quest Faewulf's Rest (Empire Ch.3 Normal PQ), Stage 2: Summoning stone interactable scenery must be destroyed by clicking on them. The scenery is interactive and does appear to break.

Breaking the stones awards no progress in the PQ. Destroying a stone should advance the completion ahead by one each. It does not.

**Steps to reproduce the problem:**

Participating in the PQ to achieve Stage 2 and then clicking a Summoning Stone.

**Testing Screenshots/Videos/Evidences (always needed):**
No screenshot available to display a lack of progress.

**Comment by Kabucoror** [comment]
you have to destroy them by attacking the stones
