### ISSUE TITLE
4 Vanq Reward for The Maw Fort

### ISSUE THREAD

**Issue by keunglh** [WarEmu/WarBugs#15311]
**Expected behavior and actual behavior:**
Should have received 4 Invader Medallions, but I received 4 Vanq Medallions instead. Occurred NA evening, The Maw Fort, 12/17/2019 (12/18/2019 for them EU folks)

**Steps to reproduce the problem:**
N/A - I joined the fort within the last 20 minutes, destro was steamrolling order so we couldn't cap any flags. Other people did receive 4 vanq as well, but it seems the majority received 4 invader medallions. 

If it's a matter of contribution, I do not think there was anything ever announced or mentioned in patch notes that the medallion rewards would be a tiered system based on contribution (?) not even sure if that's what happened. 

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/14348489/71057681-29f95700-2123-11ea-90ce-af6d3f99021d.png)

**Comment by Natherul** [comment]
not an issue but some code that was meant for next week may have gotten in this one. Will be in next weeks note
