### ISSUE TITLE
Squig Herder: Path of Quick Shooting ability "Run Away!" unable to be used in squig armor

### ISSUE THREAD

**Issue by Terpskadai** [WarEmu/WarBugs#15319]
The Squig Herder mastery ability "Run Away!" is unable to be used while in squig armor with an active pet.  Requirements for this ability only list "Requires an active pet" with no indication it should not be usable while in squig armor.

**Comment by grunbag** [comment]
There is a onscreen text and the ability is greyed in squig armor . Indications are clear
