### ISSUE TITLE
Guild Vault Issue

### ISSUE THREAD

**Issue by Beastyone** [WarEmu/WarBugs#15326]
Our guild is Rank 12 according to the Guild rank 3 level unlocks we should have unlocked 60 available slots for use, instead we have a total of 20 only after purchasing the second tab for 100g. No one in the guild including the owner can unlock the 60 we should have had at rank 3. I received 1 reply when I submitted a ticket. The reply read, " What level is your Guild?"

**Comment by raptrr** [comment]
Can you name your guild please? And provide some screenshots or a video?

**Comment by Indeciski** [comment]
Adding video:
https://www.youtube.com/watch?v=AauVaxxS8l8&feature=youtu.be

Please let me know if there is anything else that you would find helpful.

Thanks!

**Comment by Natherul** [comment]
The text is misleading but its working as intended with regards to number of slots you have. Only issue would be that you cant press the unlock button to buy more slots though this may be down to missing access right and money available for the character.

**Comment by Indeciski** [comment]
Sorry for the misunderstanding. I am the guild leader so permissions shouldn't be an issue, and I figured that the guild vault would operate the same as your personal vault, in that if I click the 'lock' icon, it would give me some kind of feedback, both with a pop up window indicating how much gold I need to unlock, as well as an audio cue, neither of which happen. I saw that 2 more rows in the first tab have been unlocked, but I am still unable to unlock any myself, and as far as I know no members unlocked them.

**Comment by Indeciski** [comment]
I would guess that a GM or someone was able to unlock two of the rows, but I still am unable to unlock any as the guild leader. Could I just hand a pile of gold to a GM to have the rest of the rows unlocked? No idea what the costs of each unlock are
