### ISSUE TITLE
Reikwald Portal Icons no longer show

### ISSUE THREAD

**Issue by ngx83922** [WarEmu/WarBugs#15323]
You can't see the Portal Icons in Reikwald anymore.

**Comment by raptrr** [comment]
Works for me. 
Can you send a screenshot?

**Comment by ngx83922** [comment]
> Works for me.
> Can you send a screenshot?

https://s19.directupload.net/images/191220/9gqlxqb8.jpg

**Comment by ngx83922** [comment]
Since todays patch they back.
