### ISSUE TITLE
De-mount[emulator]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#1532]
maybe it was a dev choice,  not sure; i post it anyway: atm dots make you de-mount, but they shouldn't

https://www.youtube.com/watch?v=Xu2Xj7ynofM

dps dok mount and bw ignite do not make him de-mount.

Only direct hit should have chance to de-mount you

**Comment by Silentguard** [comment]
Not direct only. Applying dots also triggers onAttack events on live. Also RoR mounts de-mounts you onDamage instead of onAttack.

**Comment by Tesq** [comment]
anyway, you understand what i mean, if it's  development choice you can close this, otherwise it need to be look.

**Comment by Rilos** [comment]
When Shadow Warriors mount they make an arrow shooting sound.
