### ISSUE TITLE
Not getting Contribution in Fort Char : Rhaegal

### ISSUE THREAD

**Issue by Althesian** [WarEmu/WarBugs#15325]
2nd now this occured : When i enter the fort ( During fights even ) I keep getting a yellow message stating 

There was an issue trying to give you contribution. trying to fix the problem: If it persists, report on the bugtracker.

Twice now i havent gotten any invader medallions. :/ and i've been fighting at flags, capping the flag, etc.

**Comment by Natherul** [comment]
same as https://github.com/WarEmu/WarBugs/issues/15199
