### ISSUE TITLE
Accepting Ranked Scenario crashing the game

### ISSUE THREAD

**Issue by Keula** [WarEmu/WarBugs#15324]
**Expected behavior and actual behavior:**
Sometimes when you accept the ranked scenario it crashes the game. The crashed player will seem to be in the scenario according to scenario groups/scoreboard. Because of them still being "in the scenario" no replacement can join making it essentially 5v6.

**Steps to reproduce the problem:**
No idea seems to happen randomly.

**Testing Screenshots/Videos/Evidences (always needed):**
Forgot to take screenshots of it actually happening(i'll try to add later if/when it happens again), but i had this weird thing happen today while queueing for ranked scenario:
![Alteredheal_001](https://user-images.githubusercontent.com/32713875/71190927-19b1bb00-228e-11ea-89cc-756d3fe5b768.jpg)
Maybe related? Also there was no scenario pop-up which seemed weird

**Comment by Kaelang** [comment]
Please re-open if this issue persists, there have been a lot of changes made to scenarios over the past few weeks to address this issue.

**Comment by dalen** [comment]
I found one issue that might have been causing this. Fix for it in next patch.
