### ISSUE TITLE
Solo ranked SC queue randomly drops

### ISSUE THREAD

**Issue by nat3s** [WarEmu/WarBugs#15338]
I'm getting removed from solo ranked SC queue a lot. No quitter debuff or anything, i just randomly stop being queued for ranked SC all of sudden. I can re-queue straight away.

I have a theory that this is the reason why most solo ranked SC are 4v6 and 5v6. I think the random drop from queue is actually an invite to a ranked SC that never makes its way to the players client. They can re-queue immediately, but the SC they would have joined is now short a player. Would explain why 2 full teams of 6 is so rare.

**Comment by SecretsOTheP** [comment]
Are you going AFK at any point in queue?
