### ISSUE TITLE
No invader medailons for Fortresses

### ISSUE THREAD

**Issue by boltars** [WarEmu/WarBugs#15331]
Hi, i already play 4 fortresses without any invader reward.
There is screenshots from last one, before and after the fight. I didnt get any yellow messages about loot.
![Ellexl_009](https://user-images.githubusercontent.com/59069243/71278151-120a1900-2357-11ea-8527-7798ab61ac1c.jpg)
![Ellexl_006](https://user-images.githubusercontent.com/59069243/71278172-1c2c1780-2357-11ea-891c-3195f3189785.jpg)

I know there are atlest 2 topics about this issue here [https://github.com/WarEmu/WarBugs/issues/15244](url) and here [https://github.com/WarEmu/WarBugs/issues/15246](url)
**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Natherul** [comment]
This is not an issue and will be clear once patch notes comes. Apparently something that was meant for this coming patch snuck in with a hotfix.
