### ISSUE TITLE
.... my items finally randomly could be taken off but now i cant buy the rr61 weapon when i meet all reqs

### ISSUE THREAD

**Issue by Yikesz** [WarEmu/WarBugs#15335]
**Expected behavior and actual behavior:**the full issue is in the title

**Steps to reproduce the problem:**No idea honestly

**Testing Screenshots/Videos/Evidences (always needed):**

![](https://i.gyazo.com/6efab4d500f46182caea842c3e04d9d2.jpg)

![](https://i.gyazo.com/d01f36fa1647728b41317dd6cc4e745b.jpg)

**Comment by raptrr** [comment]
Please attach a screenshot with the pre-needed weapon in your inventory as well and hover over it with your mouse.

**Comment by Lheana** [comment]
No confirmation after more than 2 weeks: close.
