### ISSUE TITLE
more item bugs

### ISSUE THREAD

**Issue by Yikesz** [WarEmu/WarBugs#15334]
**Expected behavior and actual behavior:** i try to equip or dequip items again and its not lettingme relogging doesnt help it.

**Steps to reproduce the problem:** uhh script probably needs fixed i guess

**Testing Screenshots/Videos/Evidences (always needed):**

https://gyazo.com/78c27d4f4ba24214a78a454c63db4d21

**Comment by raptrr** [comment]
Are you queued for ranked sc?

**Comment by Lheana** [comment]
No confirmation after more than 2 weeks: close.
