### ISSUE TITLE
Public quest chest contribution bug

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#1533]
![vlodar_027](https://cloud.githubusercontent.com/assets/7527415/10120481/67cb505c-64bb-11e5-961e-c72406a5d82f.jpg)
pubblic chest roll popped from nowhere before lost connection/lag server moment in ic

happened at 14:51 gmt+1 _ 26/09/15

**Comment by Evildoor** [comment]
Packet corruption, i believe. #1810
