### ISSUE TITLE
I have lost a character

### ISSUE THREAD

**Issue by Screwgrim** [WarEmu/WarBugs#15333]
Hello, 
Today when i came on my account i saw that one of my characters didnt appear.....
I tried to send him a mail and received the message "that recipient doest not exist within your realm"
The name of this character is Zankalash a magus lvl 5 and i didnt know the reason why he is gone...i had gold, gems and items on him....
Could you look at what happened please?
Thank you
![screenshot_000](https://user-images.githubusercontent.com/57125293/71299232-ae9ade00-238c-11ea-8a0a-63cd159ff6b5.jpg)
![Squigstink_000](https://user-images.githubusercontent.com/57125293/71299240-b78baf80-238c-11ea-88d5-a7ee3e942a7a.jpg)
![RoR User settings](https://user-images.githubusercontent.com/57125293/71299354-53b5b680-238d-11ea-93d0-e4937260cfd5.png)

**Comment by MaxHayman** [comment]
The character had been deleted.

https://www.returnofreckoning.com/armory.php?character_id=1234490&character_name=Zankalash5DFCB196

Contact a game master in game to get it recovered.

**Comment by Screwgrim** [comment]
Hello, I let a message to a Game Master and i hope that this character will
come back.
I dont know the reason why this character was deleted because it is not my
decision.....
Thank you

Le sam. 21 déc. 2019 à 08:56, Max Hayman <notifications@github.com> a
écrit :
