### ISSUE TITLE
City Que Bug

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15341]
**Expected behavior and actual behavior:**
Expected: Run into portal que and enter altdorf
Actual: Walk into portal recieve message can't que. But able to solo que into instance through scenario quer 

**Steps to reproduce the problem:**

Walk into altdorf portal after 2nd fort

**Testing Screenshots/Videos/Evidences (always needed):**

![](https://cdn.discordapp.com/attachments/467120396966297611/658223826034884640/20191222_021344.jpg)

**Comment by MaxHayman** [comment]
Yeah this wasn't meant to happen.
