### ISSUE TITLE
Fort: Gold bags appears to contain multiple pieces of Invader armor

### ISSUE THREAD

**Issue by ChrisRBe** [WarEmu/WarBugs#15343]
* Get a gold bag in fort
* Open bag

**Expected behavior and actual behavior:**
- Expect to have the choice of one Invader piece
- Actually see 5 Invader pieces (of the same slot) inside

**Steps to reproduce the problem:**
Get a gold bag in fort

**Testing Screenshots/Videos/Evidences (always needed):**
![bug_3](https://user-images.githubusercontent.com/31167512/71328576-91474a80-2519-11ea-9e2a-58cfc21e9a53.png)

**Comment by Lheana** [comment]
The reason is you also get the rewards of lesser bags.

**Comment by ChrisRBe** [comment]
Hi @Lheana, 
just for clarification.
I could have selected any of those 5 boots and I would have gotten them? Or what would happen if I do **not** take the last ones?
