### ISSUE TITLE
Invader Shoulders Fully Undyeable for Black Orcs

### ISSUE THREAD

**Issue by Folgrimma** [WarEmu/WarBugs#15344]
So I don't know if its been brought to anyone's attention, but the shoulders are fully undyeable for Black Orcs. Not even being able to apply a dye to it even if you were to place a different appearance on it. I have found a work around to dye it, but I'd thought i'd bring it up. 

![Desktop Screenshot 2019 12 23 - 02 47 05 86](https://user-images.githubusercontent.com/40577289/71350780-4df7d680-252f-11ea-812c-a9dc6bb8a489.png)

![Desktop Screenshot 2019 12 23 - 02 47 16 32](https://user-images.githubusercontent.com/40577289/71350793-551ee480-252f-11ea-8861-98a61ab5b8cb.png)

Workaround: Equip a dyeable shoulder piece, dye the item and before confirming reequip the invader shoulders. 
Workaround for vendor dyes: Click dye all.

**Comment by Folgrimma** [comment]
So just making a secondary comment. I'm not talking about the item being undyeable I know that. I'm talking about it not allowing you to dye the item at all. So for example i'm wearing the invader pieces but have it changed to a different appearance. I can't dye the item because it tells me the item can't be dyed.

**Comment by Kaelang** [comment]
Was able to dye Invader Shoulders fine - please re-open if issue persists.
