### ISSUE TITLE
Ranked SC points arent working correctly

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#15356]
**Expected behavior and actual behavior:**
kill someone, gain 50 points for team score, killed 2 people, got 50 score total, enemy team also has 2 kills, but has 100 score (no flag cap). 

**Steps to reproduce the problem:**
No idea what happened to cause this, I assume just kill people and see if score goes up or not.
![Betamale_001](https://user-images.githubusercontent.com/44329952/71452062-5aa24780-2746-11ea-97eb-ae228126776a.jpg)

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by raptrr** [comment]
Maybe someone died to guards / guard damage / fall damage?

**Comment by Xicoz** [comment]
no, both deaths were BW"s and nowhere near guards, and no possible way to die from fall damage cause they both had killing blows scored on them in the Scorebord

**Comment by Kaelang** [comment]
The Ranked Scenario system has been revamped since Season 1 launched - if this issue persists please re-open this problem as it no longer seems to be in effect.
