### ISSUE TITLE
Issue with Name Display with Guild Leavers

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#15354]
**Expected behavior and actual behavior:**

When a player leaves the guild, it comes up in the Guild News window in the Profile page. Their name in white with a note to say they have left the guild. Of late, we've seen a guild message to give this notification but it also adds some additional text to their name. The character ID perhaps? This seems to have started with the patch that rolled out the City Sieges. If you need it, my guild is Kar Khadath Regiment, ID 1864

**Steps to reproduce the problem:**

Tweak the coding so this doesn't appear

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/22262165/71450716-0f486300-275f-11ea-934d-c9687e1fcafb.png)

**Comment by Natherul** [comment]
this is not really a bug but its how we now mark deleted characters. They are renamed with the additional characters to allow for restoration and not cause name collisions.

**Comment by Senthoi** [comment]
Thank you for clarifying!
