### ISSUE TITLE
Magnet/Rift differs greatly

### ISSUE THREAD

**Issue by Pumatouch** [WarEmu/WarBugs#15351]
Engineer's Magnet and Magus's Rift abilities differ greatly in one regard. The matter is an implemented delay to the ability firing off. Read from Forum below:

https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=28510&p=325232&hilit=Magnet+delay#p325232
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=33822&p=380391&hilit=Magnet+delay#p380391

The issue is this: If Magnet is supposed to have a delay, it ought to apply to Rift also. 
**_Right now Engi Magnet has a delay of almost 2 seconds. Magus Rift has no such delay._** 

![](https://media.giphy.com/media/jqNQB5cMT07zye7fkz/giphy.gif)

![](https://media.giphy.com/media/RIenHlWV3r54DkUnzZ/giphy.gif)

**Comment by Natherul** [comment]
at a later patch its noted that it was reversed to match animation. This is not a bug but intended.

**Comment by SilverWF** [comment]
> 
> 
> at a later patch its noted that it was reversed to match animation. This is not a bug but intended.

It's clearly visible, that Engi has instant magnet, while Magus - delayed one. Just look closely at gifs.

**Comment by Natherul** [comment]
yes but look at the actual animations, the pull effect lines up as it is right now. Hence its fully intended.

**Comment by Pumatouch** [comment]
Looking at the actual animations of the Magus, it looks like he starts a ritual whereupon dust and smoke seems to gravitate towards him, after which an orb-like explosion of energy occurs. One could argue that the orb-like explosion is the actual pull occuring if one were to look at animations, instead of the ritual at the beginning of the cast, as it is now, neglecting all subsequent animations that occur. It matches pretty good with 2 seconds as well. It almost seems as intended, this, on the magus as well.
