### ISSUE TITLE
Flags can be captured when they shouldn't in certain scenarios

### ISSUE THREAD

**Issue by gomboni** [WarEmu/WarBugs#15359]
**Expected behavior and actual behavior:**

In certain scenarios (gromril crossing and battle for praag for instance) it is possible to sneaky cap the flags near the warcamps after a comeback. 

**Steps to reproduce the problem:**

Let the enemy unlock the flag closest to your warcamp, proceed to capping back the contested flags. Then one enemy can go to the previously unlocked flag near the wc and capture it. It also nets a lot of points over time.

**Testing Screenshots/Videos/Evidences (always needed):**

![one](https://user-images.githubusercontent.com/6848848/71482583-b2eb4f00-2803-11ea-8584-e41e7fe1a4c4.png)

![two](https://user-images.githubusercontent.com/6848848/71482597-c7c7e280-2803-11ea-89bc-d5eabe6f32d2.png)

**Comment by gittoaster** [comment]
Notice some really strange things with the flags today, flag was missing from Repair Depot, and then after that Number 9 should of opened up but it didn't
![gromril](https://user-images.githubusercontent.com/7898608/71851578-bc8a7780-308b-11ea-8259-844a604fb093.png)

I also noticed in Caledor Woods that the flag was missing to me but another player was able to cap it.

**Comment by gittoaster** [comment]
The flags appear normal until this happens:
-start match
-order capture center, opening Pile flag  
-destro cap Pile and push back to Bridge, then to No 9.
at that point, the flags are totally screwed.  Happened 3 times to me know

**Comment by Natherul** [comment]
should be fixed as of today
