### ISSUE TITLE
Inventory blank

### ISSUE THREAD

**Issue by Isupold** [WarEmu/WarBugs#1535]
If I press hotkey "B" , Inventory is blank and If I try to switch to quest or currency it seems inventory window crashed.
I allready deactivated all add ons, no solving for this kind of problem.

Problem appears after last "patch" for increase off RR.

**Comment by Reggaewaldo** [comment]
Can you please try to download the client again ? It sounds as if the files are corrupted, I have seen this happened before and a downloading the client fixed that.

**Comment by Isupold** [comment]
Problem solved: Switching UI to another char and back get's it working.

**Comment by Evildoor** [comment]
Looks like a one-time local problem which was resolved. Closing.
