### ISSUE TITLE
*Urgent* Guild Master Character Deletion.  Members of guild lose all items

### ISSUE THREAD

**Issue by Wolfsiege** [WarEmu/WarBugs#15350]
I just discovered a crippling Bug.  If a guild master character is deleted, all characters within the guild will be completely stripped of all items and builds.  Inventory is completely empty.  Characters log in to game, are dead once loaded in, forced to respawn.
![Gahl_000](https://user-images.githubusercontent.com/59191439/71396865-59a3d580-25e1-11ea-8f7c-3cc9b9ad431f.jpg)
  Checked and verified across multiple alts within guild.  

Please help.  Characters are near unplayable due to loss of gear.

![Etherreyn_002](https://user-images.githubusercontent.com/59191439/71396665-a89d3b00-25e0-11ea-9efe-90bb5693ef60.jpg)
![Krompus_000](https://user-images.githubusercontent.com/59191439/71396757-016cd380-25e1-11ea-928f-705800f1d2e7.jpg)
![Krompus_001](https://user-images.githubusercontent.com/59191439/71396758-05005a80-25e1-11ea-967f-039fc25c255a.jpg)

**Comment by Natherul** [comment]
will be fixed on the next patch, thanks for the report and even though you were right in the assessment this time, please refrain from adding words like urgent or critical. These are assigned by the BT manager

**Comment by Natherul** [comment]
noticed that I also did not address the lack of gear. The gear is not gone but simply the character does not load right with this issue active.

on another note, can you please contact me on discord?
