### ISSUE TITLE
You got a blue bag for orvr in etaine

### ISSUE THREAD

**Issue by Peppi1992** [WarEmu/WarBugs#15352]
Hey guys, I fought the whole evening and get a lot of kills and I got the loot Information about a blue bag when it locked... I was fucking happy because I just Dinged to 40... But there Was nothing in my backpack or in my Mailbox... Seems like a Bug or something. So maybe it was just shown but is Not correct or it is correct but the bag never mailed to me? Even if it was just a Bug and the Information was Not correct, What is with the roll Bonus?! I mean, there were Not soo many ppl fighting there and the Chance to get one bag Was high. I get a lot of kills and ganked many ppl... I am just heavily confused now. Greetings Peppi

**Comment by raptrr** [comment]
Did it arrive now? Might have needed a server restart, can you confirm?

**Comment by Peppi1992** [comment]
Y. Its there. Thx a lot :)

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________
