### ISSUE TITLE
RvR-Quests not working correctly

### ISSUE THREAD

**Issue by ngx83922** [WarEmu/WarBugs#15353]
This quests never work correctly regardless if I accept them all at the time:

![rvrq](https://user-images.githubusercontent.com/59058934/71450698-0bb8da00-2767-11ea-8703-1ab5492be91c.jpg)

**Comment by gittoaster** [comment]
They work for me.  You also have to be in the same pairing or zone specific.

**Comment by raptrr** [comment]
All working fine for me as well.
Gonna leave this open for another 2 weeks, if some1 else reports back that issue

**Comment by ngx83922** [comment]
> They work for me.  You also have to be in the same pairing or zone specific.

Oh, each quest can just be done in the zone where I accept it?

**Comment by ngx83922** [comment]
> You also have to be in the same pairing or zone specific.

Oh, each quest can just be done in the zone where I accept it?

**Comment by Lheana** [comment]
WAR is Upon Us! and The Gears of WAR! both work fine, I tested them on my own. They work in T2 and T3 zones that are active.
