### ISSUE TITLE
[Witch Hunter] ignoring "Burn away lies" 10sec cd

### ISSUE THREAD

**Issue by sudo-null** [WarEmu/WarBugs#15363]
Player somehow ignores 10sec cooldown of "Burn away lies" ability.

![111](https://user-images.githubusercontent.com/31512747/71555040-ee2a8f80-2a48-11ea-8fc8-171d8aa4687e.jpg)
![222](https://user-images.githubusercontent.com/31512747/71555043-f08ce980-2a48-11ea-9708-42d2b76ccd73.jpg)

**Comment by raptrr** [comment]
Just tested it and looks fine for me. Combat-Log can be inacurate as well.
