### ISSUE TITLE
Missing Fort Rewards

### ISSUE THREAD

**Issue by TD323** [WarEmu/WarBugs#15360]
Engi named Bregitta, ran successful defenses at Shining Way 3x and at Stonewatch 1x with no invader medallions received. I did get RR rewards.

**Comment by raptrr** [comment]
Did you receive the yellow server message? Did you participate in the bag rolls? Provide some Screenshots next time this occurs please.

**Comment by TD323** [comment]
I did get the server message and participate in the loot rolls, but didn't
win anything either time. I noticed I did receive Invaders last night at
Reikwatch, so hopefully the issue is fixed now.

**Comment by raptrr** [comment]
https://github.com/WarEmu/WarBugs/issues/15199

**Comment by TD323** [comment]
[image: Bregitta_050.jpg]
[image: Bregitta_051.jpg]
[image: Bregitta_052.jpg]

Screenshots are of my bag @ the Maw this morning, during loot roll, and
after. This is now the 7th fort where I did not receive Invaders. Going
before/after it starts doesn't seem to be an issue for me.

**Comment by raptrr** [comment]
I'm gonna reopen this issue, so you can upload the screenshots.

**Comment by raptrr** [comment]
Please re-do, as they did not get uploaded

**Comment by TD323** [comment]
Thanks!

Screenshots are of my bag @ the Maw this morning, during loot roll, and
after. This is now the 7th fort where I did not receive Invaders. Going
before/after it starts doesn't seem to be an issue for me.

**Comment by TD323** [comment]
![Bregitta_050](https://user-images.githubusercontent.com/53658267/71550088-4ce30100-2996-11ea-85d3-0e0b872952b2.jpg)
![Bregitta_051](https://user-images.githubusercontent.com/53658267/71550089-4ce30100-2996-11ea-894c-ac216fdbb510.jpg)
![Bregitta_052](https://user-images.githubusercontent.com/53658267/71550090-4d7b9780-2996-11ea-89b4-a56a24e52605.jpg)

**Comment by raptrr** [comment]
So, as I just checked your character in the armory, it might be that you were too low of a RR to get invader rewards by the time you issued this ticket.

"- Fortress rewards now scale with RR rank up to invader. So if you are below rr 50 you will get lower rewards from a fort."

Doesn't say it's not an issue but gonna close this one here again as it's referring to another one.
Thank you for uploading the pictures tho.
