### ISSUE TITLE
Marauder "pumelers of the undoing"

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#15368]
**Expected behavior and actual behavior:**
theirs a glove drop for marauders called "pummelers of the undoing", and it makes gloves invisible, and it also has the icon of boots, I do like the idea of hiding gloves though lol.

![Dracula_007](https://user-images.githubusercontent.com/44329952/71568382-6e261900-2a8c-11ea-9199-04994d9670a5.jpg)
![Dracula_008](https://user-images.githubusercontent.com/44329952/71568416-aded0080-2a8c-11ea-9ee1-b69fd38b09b2.jpg)

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kabucoror** [comment]
fixed with next patch
