### ISSUE TITLE
tor anroc: orb doesnt dismount you

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#1536]
even when taking damage.
![mago_015](https://cloud.githubusercontent.com/assets/13809443/10124002/6c47ef94-6549-11e5-974e-07759e46bd9d.jpg)

![mago_016](https://cloud.githubusercontent.com/assets/13809443/10124004/7509f708-6549-11e5-93c6-069b8a85dca5.jpg)

**Comment by Tesq** [comment]
righ you not suppose to be able to mount when you bear an artifact
