### ISSUE TITLE
Jail War report for forts.

### ISSUE THREAD

**Issue by tstoumbaugh** [WarEmu/WarBugs#15366]
It makes you become invincible when you war report out of jail

-MrPuddin

**Comment by tstoumbaugh** [comment]
![image](https://user-images.githubusercontent.com/1322392/71559465-9a558180-2a1b-11ea-88da-d5395b8e0e3b.png)

**Comment by tstoumbaugh** [comment]
@Natherul Do i get a griffin? :)))))))

**Comment by raptrr** [comment]
"Anyone who asks for a Griffon or Manticore mount will not receive one, regardless of whether the report would otherwise be eligible.
..."

Can be found here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)
