### ISSUE TITLE
64 Bit as 32 Bit?

### ISSUE THREAD

**Issue by ngx83922** [WarEmu/WarBugs#15373]
It is using 64 Bit as 32 Bit?

![6432](https://user-images.githubusercontent.com/59058934/71597678-72157200-2b44-11ea-8f4f-878c6020bba9.jpg)

**Comment by Natherul** [comment]
bugtracker is used for bugs, not questions.

**Comment by ngx83922** [comment]
Isn't this a big bug?

**Comment by Natherul** [comment]
I dont see any bug here. I see a question

**Comment by ngx83922** [comment]
I'm sure you know what I mean.
