### ISSUE TITLE
X Realm possible gaming breaking bug.

### ISSUE THREAD

**Issue by Beastyone** [WarEmu/WarBugs#15374]
According to the patch notes if I want to change from Order to destro I should have have to wait 90mins before being able to play as destro. But if i close out my game completely I'm able to log back in and only have between a 7-20min wait time before being able to play on destro.  Pic 2 is logging out from order, Pic 1 is after closing game and launcher and showing lock time to play.

![ror2](https://user-images.githubusercontent.com/59069826/71607113-4d1d0100-2b3c-11ea-8b57-860afb0443c9.PNG)

![ror](https://user-images.githubusercontent.com/59069826/71607086-1e068f80-2b3c-11ea-8208-8812f2cd8783.PNG)

**Comment by Oculta** [comment]
Hello it´s not only this .... if you lock long enough on and off and on u bug out the system and can get in without any timer ... i have tested it now 4 times and it worked after 4-5 times relogging ... pls fix ...

**Comment by MaxHayman** [comment]
This should be fixed now. If not please reopen.
