### ISSUE TITLE
"Hulking Brute" marauder tactic

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#15379]
**Expected behavior and actual behavior:**
tactic claims to increase both toughness and initiative by 160, but only increases toughness.

**Testing Screenshots/Videos/Evidences (always needed):**

![Dracula_013](https://user-images.githubusercontent.com/44329952/71645338-6dfc6800-2c9c-11ea-8301-f2a8ef567c66.jpg)

![Dracula_014](https://user-images.githubusercontent.com/44329952/71645340-72c11c00-2c9c-11ea-8c31-743a9016328e.jpg)

**Comment by raptrr** [comment]
Please use the command ".getstats" for stats-check like that.
The Char-screen can have issues and might not show the real stats.
Please try and check, make new ss and come back here if its still an issue.

**Comment by Xicoz** [comment]
oh ok, its working thank you, sorry
