### ISSUE TITLE
Tome got reset

### ISSUE THREAD

**Issue by BertildaEngelgard** [WarEmu/WarBugs#15371]
Got a full tome reset after latest patch. All quests, influence, event progress and other stuff gone. Restart didn't help. Character's rr and mastery points reset also.

**Comment by Gronkort** [comment]
I have this problem too. Even influence in instances like BB/BE. All gone.

**Comment by Hulkenngi** [comment]
Having the same issue on one of my characters, started a new destro character the other day, Im sure I completed all the quests in Nordland and a few other places, today I were able to take the quests again and I still got the rewards from completing them earlier.

**Comment by BertildaEngelgard** [comment]
Checked after todays patch. Everything is back to normal

**Comment by Gronkort** [comment]
Dito.

**Comment by Hulkenngi** [comment]
Still not normal. My event progression got reset, I could pick the stage 1 reward earlier, now it says I havent even completed enough to reach the dyes + my renown and mastery points got reset once again.

**Comment by raptrr** [comment]
@Hulkenngi only 1 issue per ticket.

**Comment by Troelsnap** [comment]
Charactername Snapheal.

My ToK got reset - all my quests removed, all my influence removed from all zones - my spec and renown spec got reset. All quest progression reset (were on the last step on the BeastLord quests - I can now reobtain the starting quest again).

All zones are now unexplored.

**Comment by raptrr** [comment]
https://github.com/WarEmu/WarBugs/issues/15422

**Comment by Kaelang** [comment]
Closing as looks to be patch related, see 'after todays patch everythings back to normal'
