### ISSUE TITLE
Knightly Riders - Public Quest Destruction Chaos Chapter 11 - Stage II

### ISSUE THREAD

**Issue by xpander69** [WarEmu/WarBugs#15376]
**Knightly Riders PQ second stage. Cannons don't count towards the PQ progress. They will remain 0/4 **

**To reproduce. Try clicking the cannons on second stage. They show the animation that you broke them, but doesnt count towards the objective**

![ss_31122019_09 43 11](https://user-images.githubusercontent.com/1345116/71616577-a4b08080-2bbf-11ea-9549-14e5c577a99f.png)
Screenshot where the second stage is stuck at

**Comment by Lheana** [comment]
You have to destroy the cannons, which means attacking them.

**Comment by xpander69** [comment]
Ohh, the animation is misleading then. When you touch it, it shows its destoyed model.
