### ISSUE TITLE
HP Regeneration from items does not works

### ISSUE THREAD

**Issue by Durhim** [WarEmu/WarBugs#1538]
t3 dwarf's shield for scenario emblem has "+80 HP every 4 seconds" but it is not working

**Comment by Evildoor** [comment]
Also, it should give 20 HP per 4 sec rather than 80. Source:
http://www.arsenalofwar.com/items/Order/Sentry's%20Defender%20of%20Sanctity

**Comment by Durhim** [comment]
ok, but  it doesn't work even for "+20 hp". Is it possible to implement this kind of generation in combat log ? And thanlks a lot for all your work !

**Comment by Reggaewaldo** [comment]
Since the item has been changed to now implement 20 HP Regen this is no longer a DB issue. Flagging this as Emulator.

**Comment by mammoths87** [comment]
any updates on this being fixed? Not working on the devastator chest 40 hit points per sec for chosen. Neither on the shield with 20 hit points

**Comment by genisaurus** [comment]
Fixed in recent patch.
