### ISSUE TITLE
Bad textures after bug reporting

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#15381]
**Expected behavior and actual behavior:**
every time I submit a bug report, I come back into the game with textures looking horrible, and have to completely restart client to fix. /reloadui doesn't fix the problem

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Dracula_015](https://user-images.githubusercontent.com/44329952/71645948-4231b000-2ca5-11ea-8486-c808efb5072c.jpg)

**Comment by raptrr** [comment]
Not sure this is game-related. I'm doing it right now and everything is fine for me 100% of the time.

**Comment by Xicoz** [comment]
weird it might not be, but it happens to me everytime I do, and only when I open up the bugtracker link from in game, and it makes it gradually worse every time, my guy was starting to lose his arms after 3

**Comment by raptrr** [comment]
But it is impossible these 2 are connected and can somehow interact with each other. Prolly some kind of driver issues or OS-related I'd guess
