### ISSUE TITLE
Boots appearance on gloves, witch elf

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#15385]
When doing some quests in Chaos Wastes on witch elf I found these gloves that have the appearance of boots. When equipped you get a different appearance of boots and your gloves disappear.

![glovesboots](https://user-images.githubusercontent.com/16590792/71724554-f1e75900-2e30-11ea-998b-aa850eecaae3.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch
