### ISSUE TITLE
City Scenario TEST (problems and suggestions)

### ISSUE THREAD

**Issue by sniperseal** [WarEmu/WarBugs#15382]
During the first phase, we managed just to cap the first 2 flags since they are basically free to cap. The third one was not even a thing since they were too strong for our comp. We were 18 and they were 16.
I don't know if the duration of the phases was just that long for the test, but you should add an option to surrender, or some way to win faster if you are dominating.

Also, when you get the buff that makes you giant, raising your hp to over 100k, you should make us start with full health, otherwise healers are gonna need 2 minute to fully heal you to max hp.

The performance were pretty good, no lag at all from my experience.

Also i don;t know how rewards will be tuned, but we got 3 invader medallions (they are called invader crest when you get it fix it ) for a well over 20 minute scenario where we basically were afk for 15 minute. But we probably will be able to know more about that later in the future. 

Thank you for the work. Fogna

**Comment by MaxHayman** [comment]
Fixes and changes have happened since then. Please repost any further issues.
