### ISSUE TITLE
Dead Loot Rolls

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#15380]
**Expected behavior and actual behavior:**
When your dead if you roll for loot in a WB, the game doesn't register your roll, it doesn't take it as a pass, need or greed, it just closes the window. Not sure how to screenshot this, but it is very easy to reproduce.

**Comment by Kaelang** [comment]
Duplicate of https://github.com/WarEmu/WarBugs/issues/6885.
