### ISSUE TITLE
Discordant Winds changes the damage type of Morals

### ISSUE THREAD

**Issue by DanskuL** [WarEmu/WarBugs#15399]
**Expected behavior**
Morals are damage are unmitigated and cannot crit.
**actual behavior**
Moral damage does spirit damage, is mitigated and can crit.
**Steps to reproduce the problem:**
Slot Discordant Winds build any dmg moral (tried with Raze)

**Testing Screenshots/Videos/Evidences (always needed):**

![Ravnkveder_009](https://user-images.githubusercontent.com/11351234/71768405-ed48a080-2f15-11ea-8f46-64f9f9309e07.jpg)

**Comment by DanskuL** [comment]
it works as it should without Discordant Winds slotted. (Rondul made me write this)

**Comment by Natherul** [comment]
should work as of the patch this morning
