### ISSUE TITLE
Chosen tanks not able to use guard with discordant winds tactic

### ISSUE THREAD

**Issue by crazyturkme** [WarEmu/WarBugs#15391]
So after the new patch chosens are not able to use guard skill if you are using discordant winds tactic, it keeps crashing the game.
![1](https://user-images.githubusercontent.com/45875969/71763141-37fff380-2ee9-11ea-8f2a-fefaf416644d.png)
![2](https://user-images.githubusercontent.com/45875969/71763150-5534c200-2ee9-11ea-9ca9-e5a15c1011db.png)

**Comment by Natherul** [comment]
server restarting to fix it now
