### ISSUE TITLE
runefang

### ISSUE THREAD

**Issue by normanis** [WarEmu/WarBugs#15397]
look my sreenshots

![Iana_004](https://user-images.githubusercontent.com/23311386/71766117-29273a00-2f05-11ea-92f3-33869c986b1a.jpg)
![Iana_005](https://user-images.githubusercontent.com/23311386/71766118-29273a00-2f05-11ea-9a23-1547ebe4f595.jpg)

**Comment by raptrr** [comment]
If you wanna refer to the stats, please provide screenshots with the .getstats command, as the npc stat screen can show wrong stats.

**Comment by normanis** [comment]
i cant show get stats under attack beckause mob all the time hit me.

**Comment by normanis** [comment]
if its just visual bug than its easy fix

**Comment by SecretsOTheP** [comment]
confirmed, @Natherul will have to fix
