### ISSUE TITLE
RR-dyes same as the "Dye-Items" options at the vedors

### ISSUE THREAD

**Issue by lilimx** [WarEmu/WarBugs#15394]
Hey,

according the last Patch-Notes 4.1.2020
"- Added a unique, buyable-for-50g-each dye for every 2 Renown Ranks, starting at Renown Rank 82 and ending at Renown Rank 100."
The problem is, some colors aren't really unqiue.

![1](https://user-images.githubusercontent.com/23266079/71764820-24568c00-2eed-11ea-8909-2d1da0d17500.jpg)
![2](https://user-images.githubusercontent.com/23266079/71764821-27517c80-2eed-11ea-9f1c-f6cd7e68c2a5.jpg)

all colors in the yellow frame are able to buy/dye at the every vendor with the "Dye-Items" option, for less and without any RR-restriction.

For example "Codex Grey":

![codex_grey](https://user-images.githubusercontent.com/23266079/71764837-667fcd80-2eed-11ea-8cfd-0e075a7752ba.png)
50g from the sepcial dye vendor

![lol_grey](https://user-images.githubusercontent.com/23266079/71764842-70a1cc00-2eed-11ea-90f9-2ba77426c45c.png)
same color for 2g instead for 50g.

**Comment by SecretsOTheP** [comment]
We'll swap them out. Knew I was forgetting a use case for these.

**Comment by lilimx** [comment]
fixed with patch 11.1.2020

~close
