### ISSUE TITLE
Weird bugs after  last patch

### ISSUE THREAD

**Issue by Oculta** [WarEmu/WarBugs#15395]
Hello Dev Team,

after last patch i noticed some weird bugs in the ui ... 

1. Channeling abilities dont work proper, this means my focused fire isnt channeling for the full duration.

2. Bufffood and Buffs in genaeral are gone after porting in other areas 

3. After logging first mount up are very delayed and sometimes frozen.

4. Bufffood changes randomly to the last used buffood. example i used ballistic pots and after flying to kadrin i have toughness in.

i hope this will help ....  

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Oculta** [comment]
Next BUG:

no Autoroll functionality

![Snipeshot_001](https://user-images.githubusercontent.com/31412693/71765775-b1eba900-2ef8-11ea-9fc8-987c9d7d1083.jpg)

No warband are shown in detail

![Snipeshot_002](https://user-images.githubusercontent.com/31412693/71765796-dcd5fd00-2ef8-11ea-8370-3c09e6adb6e5.jpg)

**Comment by raptrr** [comment]
only 1 bug report per issue please!
If you do it like this, its hard to get them fixed properly while having an overview who to adress or when its fixed.

**Comment by raptrr** [comment]
Tested all of them right now, could not reproduce any of the mentioned ones.
Please confirm if its fixed or just an ui issue on your side OR if others had similar problems

**Comment by Oculta** [comment]
OK .... sry next time i will report only 1 issue per ticket

**Comment by gittoaster** [comment]
The exit scenario scoreboards is blank for me ATM.

**Comment by raptrr** [comment]
@gittoaster Known issue.

**Comment by CornerbackAC** [comment]
Can confirm the channel/cast bar bug. If a target breaks line of sight while you are casting/channeling, you get stuck in the animation with a full cast bar.

**Comment by CornerbackAC** [comment]
@raptrr  Can confirm the channel/cast bar bug. If a target breaks line of sight while you are casting/channeling, the ability doesnt go through and you get stuck in the animation with a full cast bar.

**Comment by raptrr** [comment]
https://github.com/WarEmu/WarBugs/issues/15412

**Comment by gittoaster** [comment]
> 
> 
> @raptrr Can confirm the channel/cast bar bug. If a target breaks line of sight while you are casting/channeling, the ability doesnt go through and you get stuck in the animation with a full cast bar.

My testing showed that you only have to move while casting to cause this issue, line of sight break is not required.  
Test - Res skill on dead ally then start moving...
