### ISSUE TITLE
TOK Planting a seed while a chicken doesnt work

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#15398]
He should be working since today patch but you get no TOK unlock.
![Thorbolt_395](https://user-images.githubusercontent.com/16274785/71768310-5e3b8880-2f15-11ea-9db9-0f858339809a.jpg)

**Comment by Natherul** [comment]
collecting all these in:
https://github.com/WarEmu/WarBugs/issues/15421
