### ISSUE TITLE
Chosen guard is breaking the game and needs fixed asap

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#15392]
placing guard on anyone with a chosen atm is crashing the client.
![Betamale_012](https://user-images.githubusercontent.com/44329952/71763379-f0ee1000-2ea0-11ea-97bd-25c1eda578f2.jpg)
![Betamale_013](https://user-images.githubusercontent.com/44329952/71763380-f51a2d80-2ea0-11ea-952a-cc86888c44da.jpg)

**Comment by crazyturkme** [comment]
already reported

**Comment by Natherul** [comment]
and already fixed
