### ISSUE TITLE
[Quests][Order]Grimmenhagen Burning

### ISSUE THREAD

**Issue by Idrinth** [WarEmu/WarBugs#154]
This Quest is currently unlocking too late. It should unlock at the point, where the other quest from Lanric unlocks, unlocking that one once done.

Also see http://warhammeronline.wikia.com/wiki/Lanric

**Comment by Reggaewaldo** [comment]
Made an adjustment to interact with the Villagers as this was not being tracked.

Will verify function when I have access to the Test server client.

**Comment by Reggaewaldo** [comment]
Function verified.

Quest works.
