### ISSUE TITLE
Ranked Scenarios - it's possible to change the tactics while being queued or in the scenario

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#15404]
After recent patch the players are able to change their tactics (and probably equipment as well) while being queued in ranked scenarios and even within the scenarios itself. Please note previously any changes were prohibited if the player was queued or was in the scenario.

Repro steps:
1. Queue for ranked scenario
2. Change tactics
3. Wait for scenario to pop up
4. Change tactics while in scenario
![rankedsc](https://user-images.githubusercontent.com/59511907/71769490-7bc31f00-2f22-11ea-9f2f-9b0fa3a351a5.gif)
*sorry for abruptly cut off gif at the end, it's still visible that I swapped tactics set in there

**Comment by szejoza** [comment]
Checked equipment and it's properly locked (out of sc but while in a queue) but the tactics issue stands valid

**Comment by SecretsOTheP** [comment]
This is intentional. You can change tactics freely when in a ranked solo scenario. We don't check tactics anymore for determining if someone is a tank or healer.
