### ISSUE TITLE
TOK Butchering while a chicken doesn't work

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#15403]
He should work since the last patch

**Comment by thorbolt80** [comment]
![Takaron_001](https://user-images.githubusercontent.com/16274785/71769250-e4a89800-2f1e-11ea-9321-1e3e70f9c164.jpg)

**Comment by Natherul** [comment]
there is no such TOK

**Comment by Natherul** [comment]
apparently internal DB was wrong, ToK is getting added later

**Comment by Natherul** [comment]
collecting all these in:
https://github.com/WarEmu/WarBugs/issues/15421
