### ISSUE TITLE
Mailbox Bug

### ISSUE THREAD

**Issue by ngx83922** [WarEmu/WarBugs#15409]
It often shows you have a message in your Inbox or your Auction mailbox, regardless if you really have on.

![mail](https://user-images.githubusercontent.com/59058934/71769943-42d97900-2f27-11ea-8af3-a4c540831a5f.jpg)

**Comment by Lheana** [comment]
Duplicate of #1109

**Comment by ngx83922** [comment]
Is this bug since 2015?

**Comment by Lheana** [comment]
Seems like, surely from the start of RoR. Description of the bugs are the same.
