### ISSUE TITLE
Scenario scoreboard blank after patch

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#15405]
**Expected behavior and actual behavior:**
scenario scoreboard should be populated by players
actual -  no players are on the scoreboard

**Steps to reproduce the problem:**
Play scenario (I played Order T4)

**Testing Screenshots/Videos/Evidences (always needed):**
https://ibb.co/R0Xm8jn

**Comment by raptrr** [comment]
https://github.com/WarEmu/WarBugs/issues/15411

**Comment by dalen** [comment]
Some of the errors being logged:

![Falinsil_129](https://user-images.githubusercontent.com/7400/71778692-41549300-2fb1-11ea-87f3-583f1fb34d87.jpg)

**Comment by dalen** [comment]
The various info commands don't seem to output anything. `.uiscstatus` & `.rankedscstatus`. Is the issue that they require higher privileges to work?

**Comment by Natherul** [comment]
its an issue with a client update where a method invoked had its name changed but client did not get the update. Will be addressed in next client patch

**Comment by Natherul** [comment]
should be addressed as of this morning
