### ISSUE TITLE
engis safe spotting to disrupt supplies

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#15419]
in TM theres a wall engis can get on, that lets you safe spot from zergs and disrupt supply runs by shooting and greifing the supply box runners, there is no clear path on this wall, it just takes a few weird jumps, id recommend adding a barrier around the top of the tower so people cant jump off of it onto other safe spots.
![Nooblit_008](https://user-images.githubusercontent.com/44329952/71774851-a077c080-2f3b-11ea-84dd-f9c6c5c974be.jpg)

**Comment by Lithliel** [comment]
No wierd jump. Tower entrance is on pve camp side. So you can enter there. Same for other side.

**Comment by Ootootoo** [comment]
Clearly not a bug.

**Comment by Kabucoror** [comment]
It is not too hard to get there thus it remains as it is.
