### ISSUE TITLE
Squid herder - Path of big shootin' missing?

### ISSUE THREAD

**Issue by Andical** [WarEmu/WarBugs#1541]
http://3.1m.yt/Npkxxn-tr.jpg

After spending all points in "Path of big shootin'" i notice nothing from there can be found either ability book or bought from npc...
Nothing from there can be obtained: Tactics or abilities.

In my case that ability "Poison arrer" with 892 dmg would make a huge diference...

**Comment by Evildoor** [comment]
Not a bug. You don't get Poison Arrer by spending 9 points - you have to put additional, 10th point, into ability itself. Same thing applies to all other skills and tactics.
