### ISSUE TITLE
Reserve System teleport not kicking in

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15413]
**Expected behavior and actual behavior:**

Expected Behavior: Enter Fell Landing fort without reservation get ported to city.
Actual behavior: Enter fort without reservation get message saying you don't have reservation and ques you for reservation but does not teleport you out of fort.
(interesting added note:) Guildy  and 9 others entered Fell Landing before flip and got booted to Maw without reserves as intended but then was able to reenter right away via portal without 2nd teleport.
**Steps to reproduce the problem:**

Enter fort without reservation 

**Testing Screenshots/Videos/Evidences (always needed):**

![Notaaoesorc_021](https://user-images.githubusercontent.com/43802105/71772192-9ee2d400-2f0c-11ea-80bb-fece75315da7.jpg)

**Comment by Natherul** [comment]
there was an error that stopped fort from working properly that should have been fixed as of 1h ago. This is probably related. If issue persist please open again
