### ISSUE TITLE
Festive Stag mount - glitches to run on hind legs

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#15414]
**Expected behavior and actual behavior:**
expected - mount should not get stuck in animation
actual - mount gets stuck in animation

**Steps to reproduce the problem:**
not 100% sure but it is common right now due to Kegs End

**Comment by gittoaster** [comment]
![stag](https://user-images.githubusercontent.com/7898608/71772307-2d038e00-2efe-11ea-9509-7f87aa689b76.png)

**Comment by gittoaster** [comment]
Sorry, attached wrong image in first post.  Could not delete it.  ty

**Comment by Rydiak** [comment]
It happens when you are in combat or target an enemy to flag for combat.

**Comment by Kaelang** [comment]
Closing as this is a rendering problem that Goblins can also suffer from.
