### ISSUE TITLE
Festive Stag - decay timer is not changing with the time

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#15416]
Decay timer is not changing as the time passes. I obtained it a couple of days ago (at least on a 30th of december) so it shouldn't be still at 30days (guild recall reward from doing sacellum dungeon worked fine and displayed decay timer properly).
Added screenshot showing todays status. As a confimation I can only add a screenshot from 30th of december where I've got this mount on an action bar (second screenshot)

![Kharibdis_003](https://user-images.githubusercontent.com/59511907/71773381-4fc48f80-2f5c-11ea-800c-d438a5e327ea.jpg)

![Kharibdis_000](https://user-images.githubusercontent.com/59511907/71773409-df6a3e00-2f5c-11ea-9eb4-2ac4a296fff2.jpg)

Repro steps:
1. Obtain Festive Stag
2. Wait at least a full day
3. Notice the decay timer is still at 30 days

**Comment by Kabucoror** [comment]
fixed with next patch
