### ISSUE TITLE
deadmans boyz chain

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#15424]
this item cant be equipt even though im high enough level and RR and its for my class.
![Nooblit_012](https://user-images.githubusercontent.com/44329952/71793682-7d184880-3003-11ea-86ec-bb71518ec4a0.jpg)

**Comment by raptrr** [comment]
Can you try to slot it onto another jew. slot?

**Comment by Kabucoror** [comment]
This item is unique, this means you can't equip 2 of them. Can't tell it for sure by your ss, but it could be you already wearing a deadmans boyz chain.

**Comment by Xicoz** [comment]
no im not, and yes I tried raptrr

**Comment by Kabucoror** [comment]
I can slot it in any jewlery slot I want and checking your char via armory you wear it.
