### ISSUE TITLE
[Gaping Skull Mask] Can't be applied as an alternate appearance?!

### ISSUE THREAD

**Issue by Sciberr** [WarEmu/WarBugs#15425]
**An introduction:**

The mask Gaping Skull Mask can't be applied as an appearance.

**Details:**

Every other mask works perfectly fine so this should as well. 

**Evidence:**

https://youtu.be/9Kk1DqZxt3w

**Additional Information:**

N/A

**How to reproduce the bug:**

Get Gaping Skull Mask then attempt to apply it as an alternate appearance into your helm slot.

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by Natherul** [comment]
this should be fixed when login server has been fixed
