### ISSUE TITLE
Fort Rewards

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#15433]
Forts aren't giving rewards to most participants, not sure why, I have been reserved every fort I've done, lead the WB inside, tanked the lords the whole fight, and yet at the end I get no RR, no xp, and no rewards. this has happened to me three times in a row.

**Comment by Natherul** [comment]
this means you somehow was not part of the fortress in the intended way. During the last 24h we have done numerous fixes to address this. please report back if its still not fixed after this message
