### ISSUE TITLE
Leaving Altdorf City Siege Scenario Bug

### ISSUE THREAD

**Issue by Luitpoldi** [WarEmu/WarBugs#15432]
When inside an Altdorf City Siege scenario, using the Book of Binding will make the rejoin scenario window pop up.  Dismissing the window with a decline will loop the rejoin window to pop up again.  The window keeps popping up if you choose to decline.  If you do nothing and let the timer run down, the window pops up again and starts the countdown again.

**Comment by MaxHayman** [comment]
Fixes and changes have happened since then. Please repost any further issues.

**Comment by MaxHayman** [comment]
Fixes and changes have happened since then. Please repost any further issues.
