### ISSUE TITLE
[Crafting] Upon cultivating the 200er Balistik Seed you dont get 200 Balistik plants.

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#1543]
[Crafting] Upon cultivating the 200 Balistic Seed you dont get 200 Balistic plants, but 1  Molotov plants.
![lesti_095](https://cloud.githubusercontent.com/assets/14627932/10162462/add67c9c-66ab-11e5-96f5-44cfa586ec7e.jpg)
![lesti_096](https://cloud.githubusercontent.com/assets/14627932/10162463/adda6c6c-66ab-11e5-901d-92eab7d5cbbf.jpg)

**Comment by Reggaewaldo** [comment]
This has now been fixed and the change should be implemented on the live server with next rollout.

Closing.
