### ISSUE TITLE
Lost Ranks

### ISSUE THREAD

**Issue by Latnemurtsni** [WarEmu/WarBugs#15434]
Leveled to Rank 8 took a break game logged me out, when I logged back in I was Rank 6, is there a way I can get this back?

**Comment by kjeldorn** [comment]
I got the same problem, was CR11 back to CR6.

**Comment by Cryolesion** [comment]
I was also rolled back from level 10 to level 5, everything was rolled back including gold, items etc.

**Comment by GKMoggleMog** [comment]
Lost hours of levels overnight. Logged out at level 7 around 10PM CST and logged in at around 9:30 AM CST to find I was back down to level 4. Still have the armor I got while playing last night. I'm not sure if I lost money like others.

I am an Order Ironbreaker Dwarf. Leveled through RVR mostly in the battlegrounds and some time in RVR lakes. Took a few quests in the camps next to RVR lakes.

**Comment by Meffen** [comment]
I have the same Problem with my Magus 12->5

**Comment by MaxHayman** [comment]
This should have been fixed with a patch. If not please reopen.

**Comment by Meffen** [comment]
Lost Ranks Magus lvl 12 to 5 Name: Bremfunken
