### ISSUE TITLE
Confirmation when buying Keeper set

### ISSUE THREAD

**Issue by bosli42** [WarEmu/WarBugs#15437]
Over the time I heard from quite a few people that they accidentally bought the same Keeper set gear twice, locking them out to get the other pieces because the quests cannot be repeated, and them having to contact GMs.

To help especially new players, when buying the Keeper set with tokens, there really should be the same prompt we get when trading Subjugator items or Sentinel / scenario weapons, just to make sure.

(Was not sure if I should post this as a Bug here or as a suggestion in forum, but since this is once-or-never gear unlike scenario weapons, it's a bug to me)

**Comment by sioding** [comment]
![image](https://user-images.githubusercontent.com/18517842/72221177-5b194b80-3558-11ea-80de-641b030c224c.png)
already implemented

**Comment by Kaelang** [comment]
Closed
