### ISSUE TITLE
Porting issue when two fortress are contested

### ISSUE THREAD

**Issue by Viperstongue** [WarEmu/WarBugs#15431]
**Expected behavior and actual behavior:**
When two fortress are contested at the same time (one being Empire), it's not possible for defenders to port to the second one if they don't have reservation for the first one.
This  allows attackers to farm the second one in a blitz, without defenders, then get back to the first one.

**Steps to reproduce the problem:**
2 fortress contested at the same time, the first one being Empire 
eg : first : Reikwald,  second : Shining way

Didn't get a reservation for reikland, but for Shining Way yes.
Walked from Eataine to Shining way, been teleported to Reikwald but landed in "zone 0" then got ported back to Altdorf.
Getting through Altdorf portal had the same result (zone 0 -> back to Altdorf).
Trying to use portal from Stonewatch to Shining way got the same result (Reikwald loading screen, zone 0 then back to Altdorf).
All wb members encoutered the same issue.

**Testing Screenshots/Videos/Evidences (always needed):**
![WAR-64 2020-01-07 00-36-34](https://user-images.githubusercontent.com/59586802/71859046-c8a72100-30ed-11ea-9d95-e41dc5496a44.png)

**Comment by Natherul** [comment]
should not be an issue after the patch just now
