### ISSUE TITLE
Cant enter Reikwald Fortress as Attacker

### ISSUE THREAD

**Issue by xaraxdestr** [WarEmu/WarBugs#15442]
I logged in and saw that Reikwald was open. I ride to Reikwald to get a place in Queue. I got a reservation spot but was ported back to The Maw. Making my way back to Reikwald the Reservation expired and i was put back to The Maw.

**Comment by Natherul** [comment]
need more information, whats your realm, how did you enter (from riding from what zone and so on)

**Comment by xaraxdestr** [comment]
Logged in as Destro., Fort was at beginning of P2. I was riding from Reikland to Reikwald and getting the message that I was put in queue. But instead of being ported in front of Reikwald in Reikland (like in other forts) I was ported to The Maw. Then I got the message that I had a reservation (5min) and tried to ride back to Reikwald via IC. Due to riding time and Order on the way I was too late and my reservation expired but then the same issue happens again. Put into queue but ported to The Maw.

**Comment by xaraxdestr** [comment]
today it worked for me as attacker with reservation from zone before (Reikland) but people in chat still facing the same issue and are ported to The Maw.

**Comment by Natherul** [comment]
should be fixed as of today
