### ISSUE TITLE
Forts Reservations

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#15440]
Regardless if I get a reservation notification or not, it doesn't let me enter fort without running into it and getting zoned out 10+ times. idk if the face im lvl 25 and rr 39 has anything to do with this or not.

**Comment by mforeman15** [comment]
I tried to enter Reikwald after my reservation expired, but I was teleported out to the Maw. Earlier I was just teleported to the edge of the zone.

**Comment by Natherul** [comment]
More fixes are coming with next patch so Im going to close this for now but if it persist after next patch please do make a new ticket.
If you make a new ticket though please enter more information, what realm are you? what fort was it and so on. Just stating that reservations did not work does not help much sadly.
