### ISSUE TITLE
Minor Instructor's Boon (EXP reducing scroll) keeps falling off in between entrance and exits of scenarios

### ISSUE THREAD

**Issue by Povel** [WarEmu/WarBugs#15444]
Had multiple cases now where the Exp Reducing Scroll keeps falling off making me have to put another one on, this happens on literaly every single character I play.

I had a theory first that it only happens when you apply them inside of scenarios but that theory was proven wrong, so now I literaly have no idea. All I know is this shit sucks because 30 silver for a thing that can just randomly stop working between scenarios gets really expensive quickly. Definetly needs fixing. 

Please look into these if possible.

**Comment by Kaelang** [comment]
Tried multiple times in various scenarios and the buff never dropped for me. If this persists moving forward, please re-open this ticket.
