### ISSUE TITLE
[KOTBS][tactics][Gilded Shield] Shield Equip check only happens once

### ISSUE THREAD

**Issue by zulnam** [WarEmu/WarBugs#15448]
Expected:
Once selected, Guilded Shield will grant disrupt boost based on whether a shield is equipped or not.

Actual:
Shield check only happens once. After that disrupt boost (or lack of, if selected with no shield) remains unchanged.

STR:
[with boost]
1. equip shield.
2. select Guilded Shield tactic.
3. check disrupt stat.

[without boost]
1. unequip shield.
2. select Guilded Shield tactic.
3. check disrupt stat.

Screenshots:
![Steyner_000](https://user-images.githubusercontent.com/19802847/72018760-ec46a480-3270-11ea-995b-87a9de14713f.jpg)
![Steyner_001](https://user-images.githubusercontent.com/19802847/72018761-ec46a480-3270-11ea-95b4-6df16ef67a04.jpg)

**Comment by Natherul** [comment]
also @zulnam please contact me on discord

**Comment by Natherul** [comment]
this should be fixed when login server has been fixed
