### ISSUE TITLE
tactics resets on login

### ISSUE THREAD

**Issue by xaraxdestr** [WarEmu/WarBugs#15458]
When i login all my 4 tactics on slot 1 are empty and not concidered in stats. If i hover over the slots i see all 5 tactic slots are filled, even slot 1. If i select it again it shows up and is concidered in stats.

![Knochenschild_082](https://user-images.githubusercontent.com/45398873/72203874-fedbfc00-3471-11ea-8602-0d778985f7a7.jpg)
![Knochenschild_083](https://user-images.githubusercontent.com/45398873/72203877-03081980-3472-11ea-955f-d0de4c4a84f7.jpg)

**Comment by Natherul** [comment]
this should be fixed when login server has been fixed
