### ISSUE TITLE
[Squig Herder] both Territorial Aggression and Sneaky Stabbin tastics have no effect on autoaattack damage.

### ISSUE THREAD

**Issue by dshdf1** [WarEmu/WarBugs#15454]
Expected behavior 
mSH tactics "territorial aggression" and "sneaky stabbin" should increase "melee attacks damage by 25%" and "damage by 15% when 45 feet away from target" respectively
Actual behavior
both tactics somewhy dont affect autoattacks at all, while they should increase it according to wording in descriptions
**Steps to reproduce the problem:**
attack dummy, check numbers, slot tactics, attack again.

**Testing Screenshots/Videos/Evidences (always needed):**

![Безымянный](https://user-images.githubusercontent.com/51263689/72192550-41bcb600-3417-11ea-8c62-102dc3a50647.png)
1st and 2nd AA's with both tactics equipped, 3rd without both, damage is the same.

**Comment by grunbag** [comment]
Melee attacks doesn’t include autoattack . It only affect melee abilties
