### ISSUE TITLE
Apothecary bugging after 1 make

### ISSUE THREAD

**Issue by shadrach03** [WarEmu/WarBugs#15455]
I just started apothecary and after hitting level 25 I am only able to craft 1 potion of a type before it bugs and wont allow me to craft another.

Reload ui, switching ingredients or changing zones doesn't seem to clear the issue.  

Relogging the character in seems to allow me to make 1 more potion before locking up the ability to craft again.

**Comment by meowfurion** [comment]
Same issue.  Apothecary level 61.  I make one potion attempt, it succeeds, doesnt' create the potion in my inventory, I gain a skill point, then the skill totally stops working unless I completely relog.  It may be good to give this one priority attention.  I am volunteering to be the primary potionmaker for our 6 man team and I can't level it up past what it is now without a relog each time.

**Comment by MaxHayman** [comment]
Might be fixed after this patch. If not please reopen.
