### ISSUE TITLE
Special Delivery In Talabecland

### ISSUE THREAD

**Issue by SPRVatis** [WarEmu/WarBugs#15451]
The box is missing so you can't finish the quest.

**Comment by Confederatus** [comment]
"Iron box" still nothing to be found.

**Comment by Wesleth** [comment]
https://www.youtube.com/watch?v=57z7f4KZxTc

(lag is my end, disregard)

**Comment by ibahalwan** [comment]
I also experienced the same issue.

**Comment by Kaelang** [comment]
This should have been fixed as of 27/05/20. Please re-open if issue persists.
