### ISSUE TITLE
Scenario is Not Ending.

### ISSUE THREAD

**Issue by Itmritual** [WarEmu/WarBugs#15457]
The Scenario I'm in is not ending. Destro got to 500 points but it didn't end. The timer has also run out and it didn't end. I got the notification over 3 minutes ago that Order was outnumbered and it still hasn't ended. Now Destro has started a Surrender vote and won it 6/0 but it says that 6 votes were needed to end it. I'll put the picture of the ended, won, and surrendered Scen that I'm still sitting in.
![Agoniist_003](https://user-images.githubusercontent.com/31557076/72202757-370f1a80-3431-11ea-8973-3c2a2346bce7.jpg)

**Comment by Itmritual** [comment]
I just left through the exit and it didn't give me the quitter debuff, just thought I'd point that out. And I don't think I need to mention that everyone is level 2 now before they log in..

**Comment by lijebin** [comment]
yeah we got same issue is bug to 
![Frostitan_000](https://user-images.githubusercontent.com/17027595/72204469-3dde7180-34b3-11ea-8b6a-daa94ebcd9bc.jpg)

**Comment by Natherul** [comment]
this should be fixed when login server has been fixed
