### ISSUE TITLE
Conquering The Isle Quest has typo

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#15456]
The quest Conquering the Isle says Uglu when it's supposed to be Ulgu, like the mobs surrounding the quest area are called Shadow of Ulgu. The mob that has to be killed is also named with the typo.
![uglu](https://user-images.githubusercontent.com/16590792/72194995-93157700-3410-11ea-8a66-ac7378432d78.jpg)

**Comment by ElMosquito** [comment]
To be added, the mob that is to be killed has the same typo.

**Comment by Lheana** [comment]
Thanks for the report, it will be fixed with next patch.

**Comment by Natherul** [comment]
should be fixed as of today
