### ISSUE TITLE
Several Quests in Destruction start area Norsca gone since patch 11/1/2020

### ISSUE THREAD

**Issue by Thauredhel** [WarEmu/WarBugs#15462]
Expected: The same quests available as yesterday (10/1/2020)
Actual: Several of them are not available anymore.

Reproduce:
Start new character on Destruction side, 
Do "New Recruits" for Dyrre the Heartrender,
"Prove Yourself" and "Assist the Daemoncaller" for Skurlog Blackhorn,
"The Heart of Battle" and "Training Course" for Kaltira the Daemoncaller"

then

Seer Thaena does not give "The Heart of Battle"(1) part where you go to the Thorshafn cemetary at 42.1 19.1 and kill "Thorshafn Ancestor"s. It gave a bone questitem you had to click on at the cemetary.
Madgr the Soulreaper does not give "The Soulreaper" nor his followup quest "Show of Power". The latter is extra bad since it gives the first trophies on Destruction side :( 

I think Madgr's quests are chained after Thaena's.

(1) Yes, it has the same name as the previous quest.

**Comment by Lheana** [comment]
It's intended, the Chaos chapter 1 is being reworked to be in line with how quests were on official. It means some quests are disabled.

**Comment by Thauredhel** [comment]
Ok, I didnt see anything in the patch notes about it.

**Comment by Lheana** [comment]
Yes, it is WIP, so it was not mentioned in the patch notes yet.
