### ISSUE TITLE
NO controbution for Stonewatch fort 1/11/20 11:30ish EST

### ISSUE THREAD

**Issue by Cirronia** [WarEmu/WarBugs#15461]
Kept getting a message saying there was an error in calculating my contribution, and it told me to report it here, i didnt get any renown or invaders for the fort win.  help! 

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Natherul** [comment]
then how did you enter the fort? When entering did you get any message? Currently there is no information here to help you.

**Comment by Cirronia** [comment]
Not super bothered by it, but walked in from KV.  Super buggy fort, lagging real bad.  the message in the chat box kept popping up so i made a report.  Don't care about the renown or medals there will always be another one but server told me to let you know about it so i did :).

**Comment by dalen** [comment]
This should be fixed in the  latest patch (from 2020-02-15). Please open a new ticket if you can still reproduce this.
