### ISSUE TITLE
[Visual Bug] Animation bug after being knocked down

### ISSUE THREAD

**Issue by Krumlok** [WarEmu/WarBugs#1546]
Please, enjoy the images. An image is worth a thousand words :)

![bugtracker1](https://cloud.githubusercontent.com/assets/14275335/10177327/e420c5f2-66f9-11e5-8b17-69ca41daeceb.png)

![bugtracker2](https://cloud.githubusercontent.com/assets/14275335/10177328/e42169b2-66f9-11e5-94ff-690f78808211.png)

Basically, after being knocked down, your char is stuck in the "KD'ed" pose (only when you remain still) and when you walk, your char walks "hugging" like poa Krumlok is shown in da image.

**Comment by Evildoor** [comment]
https://github.com/WarEmu/WarBugs/issues/1312
Experienced this bug myself several times. Unfortunately, linked issue states that we cannot fix this. Closing.
