### ISSUE TITLE
High Elf Fort Jail 

### ISSUE THREAD

**Issue by noobwarrior** [WarEmu/WarBugs#15468]
The prison in Fort Fights is useless because people are away teleporting out, the effect of the jail is gone
![Relife_353](https://user-images.githubusercontent.com/53536809/72218803-6ad86600-353f-11ea-9cb9-48bc88fbb939.jpg)
![Relife_354](https://user-images.githubusercontent.com/53536809/72218806-6ca22980-353f-11ea-864a-db297d6aeeaf.jpg)
![Relife_355](https://user-images.githubusercontent.com/53536809/72218808-6e6bed00-353f-11ea-9a17-4943cd8c2872.jpg)
![Relife_356](https://user-images.githubusercontent.com/53536809/72218810-71ff7400-353f-11ea-8a87-ddf09e070cc1.jpg)
how you can see this well..

**Comment by noobwarrior** [comment]
the error in the game works in every jail not only in the high elf fort jail.!!!!!!!

**Comment by Kaelang** [comment]
This issue has since been fixed. Please re-open if issue persists.
