### ISSUE TITLE
Since yesterday patch TOK Scavenging while a chicken don't give the Title: Pecked Over, anymore

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#15466]
It was working fine last week but after yesterday patch doesn't work anymore
![Thorbolt_401](https://user-images.githubusercontent.com/16274785/72215945-a7459b00-351a-11ea-9c57-556d2912620d.jpg)

**Comment by Natherul** [comment]
was never added before, its added for next patch

**Comment by thorbolt80** [comment]
Working perfectly thanks ! Now the 38/38 unlocks for tradeskills whacky works
