### ISSUE TITLE
Poor me has ranked premade MMR, while never joining premade Caledor Woods

### ISSUE THREAD

**Issue by M0rw47h** [WarEmu/WarBugs#15463]
Never qued for premade Caledor Woods, yet I've higher rating for premade than 1500, since today* patch:
https://imgur.com/RDMTBbx

**Comment by Natherul** [comment]
There was a small issue with the MMR generation and its been solved. Your MMR will stay but wont actually give you any rewards weekly. Playing ranked will adjust it over time and as such will normalize.

The gains of MMR on non ranked SCs should have been fixed now
