### ISSUE TITLE
Pounce z axis problems post Patch : 11th January 2020

### ISSUE THREAD

**Issue by Goliathus-Git** [WarEmu/WarBugs#15465]
**Expected behavior and actual behavior:**
Using "Pounce" to leap to the target providing conditions are met. 

Sometimes the ability successfully executes and other times it fails. 

**Steps to reproduce the problem:**
Drafted in a mate to help with this, Tried using "Pounce" on different terrains and surfaces i.e walls/hills/slopes.

**Testing Screenshots/Videos/Evidences (always needed):**

https://www.youtube.com/watch?v=8PLTPJeZLGs
https://www.youtube.com/watch?v=fkob0k2VGhc
https://www.youtube.com/watch?v=zuJlHXZ7BKc
https://www.youtube.com/watch?v=QgUkalyNLKY

Apologies for the links but couldn't convert to a usable file.

**Comment by Natherul** [comment]
This is intended and not a bug. we have impemented a Z axis requirement as leaps are not allowed to bypass any keep walls. Its currently set to just block the lowest keep wall access.

**Comment by Goliathus-Git** [comment]
Thank you for your reply.

 I am confused though when you say, "Can also add that we added a block to use any such ability while in the air as well, so jumping and using it will also fail and is intended." In my 2nd link, I am using Pounce whilst in the air, so just for clarification, it has been Hotifxed since I raised this post?

**Comment by Natherul** [comment]
that would be a bug then as serverside block such a cast if it detects that your in the air.

**Comment by Goliathus-Git** [comment]
Ah okay, so can leave this now knowing it's been brought to your attention? 

I'm not sure how it affects SM's and SH's pounces, Haven't got those classes to test unfortunately
