### ISSUE TITLE
Discordant winds still changes the damage type of certain morals

### ISSUE THREAD

**Issue by DanskuL** [WarEmu/WarBugs#15460]
Related to: https://github.com/WarEmu/WarBugs/issues/15399
**Expected behavior**
Moral damage should be pure damage.
**actual behavior**
Does spirit damage and is affected by mitigation and taunt

**Steps to reproduce the problem:**
Slot Discordant winds and use Raze/Demolishing Strike

**Testing Screenshots/Videos/Evidence**

![Ravnkveder_014](https://user-images.githubusercontent.com/11351234/72207286-280f8300-3498-11ea-9549-ab8fa3d6d07f.jpg)
![Ravnkveder_015](https://user-images.githubusercontent.com/11351234/72207287-280f8300-3498-11ea-9ca7-f191c10dfe74.jpg)

**Comment by Vontyl** [comment]
22/3/2020
This is still strange behavior.
Fighting WP, WH and WL with Discordant Winds slotted, was in keep in BFP, fighting near postern :
![discordant_raze](https://user-images.githubusercontent.com/60270903/77250711-02e28200-6c4a-11ea-9f3b-398a4658494e.png)

**Comment by Kaelang** [comment]
Discordant Winds has been removed in todays patch.
