### ISSUE TITLE
DoK patch wounds 

### ISSUE THREAD

**Issue by Wachlarz** [WarEmu/WarBugs#15469]
Patch wounds this skill have 5 sec cd, but i see i can use this skill more often, like 1 sec. Not always, but often, essense go down, debuffs clensed. First time i see this in bb/be, but i see this in sc too.

**Comment by bosli42** [comment]
Did you have a Black Orc in your group? They can reduce their group's cooldown by 5 seconds, making you able to spam it.

**Comment by Wachlarz** [comment]
Ok i must test it more

niedz., 12.01.2020, 15:11 użytkownik Zyv <notifications@github.com> napisał:

**Comment by raptrr** [comment]
Any new info on the ticket?

**Comment by Wachlarz** [comment]
I think work fine. I have bo or choppa in party

niedz., 9.02.2020, 17:34 użytkownik raptrr <notifications@github.com>
napisał:
