### ISSUE TITLE
Marauder's axe alternate appearance.

### ISSUE THREAD

**Issue by lethewyvern** [WarEmu/WarBugs#15471]
I found 2 chaos axes(Scythe of Insanity and Pick of the Irruptor) which cannot be used for alternate appearance, because of error: "The chosen appearance cannot be applied to Chaosaxe of the Subjugator because the appearance is not the same type." Same error getting with Bloodlord Chaosaxe and Titan's Chaosaxe of Anathema. Also i tried to use these axes for alternate appearance for hammer - same error.
![Shaqattak_078](https://user-images.githubusercontent.com/57109035/72219942-5d39d500-356d-11ea-8b75-29edcf6c5d32.jpg)

**Comment by bosli42** [comment]
"Main Hand" only weapons are a different type (Chosen based) than "Main Hand or Off Hand" weapons (Marauder based), which is causing the error. You should be able to use them on each other, as they are both Main Hand only weapons.

Not sure if it's intended.

**Comment by lethewyvern** [comment]
> "Main Hand" only weapons are a different type (Chosen based) than "Main Hand or Off Hand" weapons (Marauder based), which is causing the error. You should be able to use them on each other, as they are both Main Hand only weapons.
> 
> Not sure if it's intended.

Yea, you are right - its working to use them on each other. Also i check my storage and have found more stuffs like that, dont know if this ok. It seems chosens have much more variety with alternate appearance options.
