### ISSUE TITLE
MMR 

### ISSUE THREAD

**Issue by robswalker68** [WarEmu/WarBugs#15474]
Until today my MMR has been showing 0 for both Solo Q and Group Q.  This is correct i think as i played 1 sc a number of weeks ago and never entered a group Q.  Today my MMR is showing, in the TOK, as 1359 & 1369 for the Solo Q and Group Q respectively.  While nice to have, I presume a bug?

**Comment by Natherul** [comment]
https://github.com/WarEmu/WarBugs/issues/15463
