### ISSUE TITLE
Maargren the Frenzied in Shadowlands spawns twice

### ISSUE THREAD

**Issue by valkeera** [WarEmu/WarBugs#15470]
There are two instances of the champion Maargren the Frenzied in Shadowlands, close to each other (hopefully it's visible on the screenshot)

![Cirthanir_001](https://user-images.githubusercontent.com/58527250/72218963-061e0b00-3541-11ea-8af1-25cc2470eba6.jpg)

**Comment by valkeera** [comment]
I saw this npc only once now, so it was probably fixed with the last patch as well.

**Comment by Lheana** [comment]
I disabled the other spawn but I need time to make her walk like she should. That's the reason why I kept this ticket open, not to forget :)
