### ISSUE TITLE
Apprentice Lerauk in Shadowlands spawns twice

### ISSUE THREAD

**Issue by valkeera** [WarEmu/WarBugs#15476]
There are two instances of the champion Apprentice Lerauk in Shadowlands, close to each other.

![Cirthanir_003](https://user-images.githubusercontent.com/58527250/72222406-9457b880-3564-11ea-9229-1fc926bf841c.jpg)

**Comment by Lheana** [comment]
This should have been fixed with patch of 22/02/2020.
