### ISSUE TITLE
Ranked weekly rewards everyday!

### ISSUE THREAD

**Issue by Iamwithstupid** [WarEmu/WarBugs#15477]
**Expected behavior and actual behavior:**
Ranked weekly rewards yesterday for 81 match
Ranked weekly rewards today for 101 match

**Steps to reproduce the problem:**
dunno
![Untitled](https://user-images.githubusercontent.com/36380568/72228126-b07f4800-35ac-11ea-8a42-a0cfe28e3d11.png)

**Comment by SecretsOTheP** [comment]
When the system first went in, there was a bug handing out rewards too early. This is corrected now and will only distribute rewards every Monday Altdorf time.

The behavior you are seeing is intended. Please update the ticket if you get rewards tomorrow.

**Comment by Iamwithstupid** [comment]
btw.... Did not happen on my other character who has plenty of ranked played too, only got the first letter.

**Comment by Iamwithstupid** [comment]
> 
> 
> When the system first went in, there was a bug handing out rewards too early. This is corrected now and will only distribute rewards every Monday Altdorf time.
> 
> The behavior you are seeing is intended. Please update the ticket if you get rewards tomorrow.

no rewards anymore

**Comment by raptrr** [comment]
@SecretsOTheP can you recheck?

**Comment by SecretsOTheP** [comment]
Fixed.
