### ISSUE TITLE
Ilrenk Bloodtaker in Shadowlands spawns twice

### ISSUE THREAD

**Issue by valkeera** [WarEmu/WarBugs#15475]
There are two instances of the champion Ilrenk Bloodtaker in Shadowlands, close to each other.

![Cirthanir_002](https://user-images.githubusercontent.com/58527250/72222388-696d6480-3564-11ea-8e10-96f2ebcaa546.jpg)

**Comment by Lheana** [comment]
This should have been fixed with patch of 22/02/2020.
