### ISSUE TITLE
BlackOrc Beastlord Armor

### ISSUE THREAD

**Issue by Goermsi** [WarEmu/WarBugs#15484]
I wear the parts of the Beastlord set, but not all set bonuses are credited correctly.
In my opinion this is because 5/6 parts are translated into English, but the chest is translated into German. In total the last part is missing, probably because of the translation.

**Comment by Ootootoo** [comment]
Have you tried the command .getstats to confirm that the bonus is not being added? The character sheet is notoriously buggy when it comes down to add gear stats.

**Comment by Goermsi** [comment]
Yepp! Ur right Dude. Just a buggy character sheet. Sorry for the disrupt!!

**Comment by Kabucoror** [comment]
Set bonuses can be wrongly displayed if you use another language than english.
