### ISSUE TITLE
Multiple crafting ingredients in single inventory slot

### ISSUE THREAD

**Issue by WaltKey** [WarEmu/WarBugs#1548]
Once i em loot some buggy stuf, everything stopped working. Everything in the video.

https://youtu.be/L7zWLFYT_mA

**Comment by LestiArdisson** [comment]
Is salvaging your first gathering skill, or had you some other gathering skill before and used .respec?
I had a bug that I .respeced my scavenign and had 4 bags full of crafting stuff.
After respec I lost the 3 extra bags, but the items in there were allways there. After I gathered culitvation bag, I got the lost items who were there out of sight. Maybe this is something connected?

**Comment by Vladimir2020** [comment]
I used respec, but no. Bug hapens then I got in the bag some bugged (phantom) ittem. Used respec several times, but nothing change.

**Comment by Csernobog** [comment]
click all empty space (in order) in your bag or left side close and open bag again.

I many time find my lost item in the empty space....click and appear:)))
