### ISSUE TITLE
Focussed mending and impossible to use aura. 

### ISSUE THREAD

**Issue by Meenexx** [WarEmu/WarBugs#15487]
Hi,

I have a KOTBS level 27. When i use the tactic focussed mending and i use my aura "stay focused!" with any other aura and with bolster, all is ok on the begining. But when I die, i lost 2 au my aura other than "stay foccused". And i cannot use any aura after that. And even i desactivate my "stay foccused" (who are not desactivate after i die), I cannot activate that aura after that.

That bug do not appear when I do not use focussed mending tactic. It do not appear when you use stay focussed without bolster.

It is frustrating do not have aura and you are KOTBS. This is our core ability.

Thanks you.

**Comment by Kaelang** [comment]
Merging this with https://github.com/WarEmu/WarBugs/issues/16085.
