### ISSUE TITLE
locked for 90min for wierd reason.

### ISSUE THREAD

**Issue by ctesjbuvf** [WarEmu/WarBugs#15492]
hello, i accidentally clicked play on my order lowlvl char i'm a destruction player... now i'm just locked for 88min for being on a lowlvl for liturally 2 Seconds.

**Comment by dalen** [comment]
Not a bug, if you switch sides you are locked from switching again for 90 minutes. See https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=34652&sid=aecc420c5b2f3b367345579217c9a8a2

**Comment by ctesjbuvf** [comment]
yes but atleast dont do so if you log in for 1min or 20 seconds you will be locked, thats just annoying.

**Comment by Ootootoo** [comment]
Irrelevant. Annoying or not, it's the way it is, and works as described in the notes. This is for bugs, not for personal opinions.
