### ISSUE TITLE
Choppas can one-shot a slayer that has Reckless Gamble activated by punting him on walls

### ISSUE THREAD

**Issue by Choppabully** [WarEmu/WarBugs#15494]
**Expected behavior and actual behavior:**

Expected: A Choppa should not one shot a slayer from full HP when punting him over walls while the slayer has Reckless Gamble skill activated.
Actual: A Choppa can one shot a slayer regardless of his HP and defenses if he punts the slayer on wall while the slayer has Reckless Gamble skill activated.

**Steps to reproduce the problem:**

Take a slayer and a choppa, have the slayer activate Reckless Gamble and enter combat with the choppa. The choppa has to punt the slayer in such a way in which the slayer would land on a wall. The slayer will be dead instantly even from full hp. The issue does not happen all the time.

In the combat log it appears that I was annihilated by Reckless Gamble or even the following thing: 

You have been slain by Choppabully (this is my character's name).

I will try to excuse myself for not playing Choppa before, therefore I have no idea of his abilities. I only know that the issue happens when a choppa punts me and has a 50% reproduction rate. The following issue happened me already a couple of times and it was very frustrating. It happened in fort twice and when I was soloing in RvR about 3 times. 

**Testing Screenshots/Videos/Evidences (always needed):**

![Choppabully_003](https://user-images.githubusercontent.com/59963650/72528627-384aa800-3874-11ea-965d-bca860c2c51a.jpg)

**Comment by pikara** [comment]
Choppa dont have any punt, other char have punt u while fighting the chopa. On screen i see u hit the choppa and u reckless Gamble dmg u back as it say in tool tip it will do. Same happen with BW and sorc, but with lot more dmg taken (very comun see then self blow).
Also i see u have x2 rs, that cut u wounds, u not using pots and hiting a rr91 choppa on full rage (check mitigation), no suprise u die fast.

**Comment by Kaelang** [comment]
I'm closing this for the time being. If you are experiencing issues with classes and/or tactics please recreate a new report. I appreciate your detail, however some of this is mistaken based on class knowledge, i.e. Choppa's having punt etc.
