### ISSUE TITLE
[KOTBS][Commands] Auras cannot be activated after dying in RvR when Bolster is in effect

### ISSUE THREAD

**Issue by zulnam** [WarEmu/WarBugs#15493]
Expected:
Upon dying in RvR, kotbs can reenable all auras that were reset due to respawning outside RvR lake and losing Bolster.

Actual:
No auras can be activated anymore. Auras that are not affected by Bolster ('Stay Focused!') are still present and can be deactivated, however they cannot be activated again afterwards.

[Note] Issue usually occurs after 2nd or 3rd death. First death is usually fine.
[Note2] Issue was also reproduced in Scenarios (where Bolster is in effect).
[Note3] Can be fixed by relogging however requires player to constantly log in/out of game. Something not possible when sometimes in a warband.

STR:
_Prerequisites: Kotbs viable for T2+ RvR lakes that has not yet hit lvl 40 (and is affected by Bolster)._

1. In a Warcamp, activate 3 auras.
2. Join the RvR lake.
3. Die 2/3 times.
4. Attempt to activate auras.

**Comment by zulnam** [comment]
Update:

After abandoning Stay Focused! (and the tactic related to it) the issue is not reproducible anymore. 

This makes me believe that actually **the issue revolves around receiving/losing Bolster along with having Stay Focused! activated along with Focused Mending tactic.**

**Comment by Kaelang** [comment]
Potentially due to the tactic requiring a certain level and the issue we had previously where bolster effected certain abilities (see: Firestorm). This has since been fixed.

I have tried to replicate this issue with no effect - please re-open if issue persists and I'll re-evaluate.
