### ISSUE TITLE
Redeye shows in Armory but does not grant ward or title

### ISSUE THREAD

**Issue by Timmitz** [WarEmu/WarBugs#15496]
Redeye shows in Armory but does not grant ward or title

Natherul already saw that ToKs in db are missing

![Eadcheeze_070](https://user-images.githubusercontent.com/36116924/72615391-ddc55080-3934-11ea-8515-9adfe055e3e3.jpg)
![Eadcheeze_071](https://user-images.githubusercontent.com/36116924/72615395-e158d780-3934-11ea-898c-c923a7556afe.jpg)

**Comment by Natherul** [comment]
should be fixed as of today
