### ISSUE TITLE
Auction house mail bugged

### ISSUE THREAD

**Issue by Jaycub** [WarEmu/WarBugs#1549]
After trying to purge my AH to re list everything at lower prices I went to my mailbox to find this: http://www.mediafire.com/view/c7qdyd0h45j7049/Shlomo_041.jpg

Log off / client restart did not fix it, the only thing I haven't tried is waiting for a server reset/patch to see if that will fix it.

probably had ~400-600 messages (undeleted but read/received) already in there, is there a cap or something?

**Comment by Evildoor** [comment]
Seems similar to https://github.com/WarEmu/WarBugs/issues/557 to me...

**Comment by Jaycub** [comment]
Ah I only searched in game support forum :(

So it would seem that I did go over the cap, was reading through the thread and im not sure how to remedy this though.

**Comment by Evildoor** [comment]
Seems so.

**Comment by defleshed2** [comment]
I have the same problem on my toon "defleshed" can you fix please!

**Comment by defleshed2** [comment]
Hello is someone looking at this?

**Comment by Stefanosgr18** [comment]
![war 2015-12-22 10-40-00-78](https://cloud.githubusercontent.com/assets/16375224/11951324/b20a6c04-a898-11e5-87a6-3cae70741487.jpg)

**Comment by Evildoor** [comment]
Closing per rules of the bugtracker.
