### ISSUE TITLE
Tie Ranked Match MMR Gains/Losses

### ISSUE THREAD

**Issue by Flavor-burst** [WarEmu/WarBugs#15491]
**Expected behavior and actual behavior:**
No mmr movement on a tie (from either side) is the expectation.

Order seems to lose mmr on a tie.

![image](https://user-images.githubusercontent.com/39884574/72463052-63fc5e00-37a0-11ea-9e43-0235e7973d98.png)

![image](https://user-images.githubusercontent.com/39884574/72463093-75de0100-37a0-11ea-91e9-21b2a4be5855.png)

**Comment by dalen** [comment]
Most likely due to getting a tie against players with lower MMR than you. The system would have expected you to win against lower MMR players, so a tie is considered a bad result in that case.

**Comment by dalen** [comment]
was actually a bug, supposedly fixed now though `-Draws will no longer count as destruction wins for matchmaking rating calculations.`

**Comment by Kaelang** [comment]
Closing as fixed.
