### ISSUE TITLE
Xrelm lockout not working

### ISSUE THREAD

**Issue by Meleesorc** [WarEmu/WarBugs#15497]
**Expected behavior**

"The lock is only applied when you switch realm. If you played last night on Order and today you log into Order there will be no lock applied. If you then switch to Destruction then you will be locked to Destro for 90 mins.

So if you log back in to the last realm you played you won't be locked."

**Actual behavior:**

You get locked even though you haven't swapped sides.

**Steps to reproduce the problem:**

1. Log into Destro, play for more than 90 mins
2. log out, and then back into destro. (without swapping to order) Realise you are locked for another 90 mins.

**Comment by Ootootoo** [comment]
Not a bug, imo, that's exactly how it is supposed to work.

**Comment by Kaelang** [comment]
This is working as intended.
