### ISSUE TITLE
IB - Tactics reset on log off. 

### ISSUE THREAD

**Issue by Saddarak** [WarEmu/WarBugs#15508]
Every time I log in with my Ironbreaker the tactics icons are missing and obviously they don't take effect. I have to add them manually each time. Furthermore at random times and with no apparent reason either the icons disappear or they are there alright but the tactics don't apply/don't work. Obviously this has serious effects on my gameplay...
![Screenshot 2020-01-20 17 48 41](https://user-images.githubusercontent.com/58730536/72740411-466b3200-3bae-11ea-9e16-8ea3e7642bb9.png)
![Screenshot 2020-01-20 17 48 49](https://user-images.githubusercontent.com/58730536/72740412-4703c880-3bae-11ea-9370-d7b8d1bf42b1.png)

**Comment by Kaelang** [comment]
Closing and merging with a more detailed report of this issue https://github.com/WarEmu/WarBugs/issues/15857.
