### ISSUE TITLE
Controlling the enemy ram

### ISSUE THREAD

**Issue by Cesi-123** [WarEmu/WarBugs#15502]
Yesterday in TM I was able to take control of the Destruction ram while on Order.  I had the ram targeted through the outer keep door.  I went outside to attack it then accidentally right clicked it and the door quickly in succession.  When I went inside I had control of the ram and they weren't able to use it to attack.  Attached is a picture of my being inside of the keep with control of the Destruction ram as an Order character.  Once I realized what was going on I released the ram, but it was a bit 

https://cdn.discordapp.com/attachments/584848073491087398/667817987704750081/unknown.png

**Comment by pikara** [comment]
Same happened to me but as destro and taking order ram. Same case, i click door to get out and hit ram but instead i get control of it.

**Comment by Cesi-123** [comment]
This bug was used again in KV by Order to deny Destruction the ability to even get on the ram.  It kicks off all the people already on the ram and denies them the ability to get back on it.  This was used by some Order player to stop us from being able to siege.

https://cdn.discordapp.com/attachments/462359378687688706/669975735846305802/unknown.png

https://cdn.discordapp.com/attachments/462359378687688706/669975867686125578/unknown.png

**Comment by Natherul** [comment]
should be fixed as of today
