### ISSUE TITLE
Morale 4 Ress for all heal classes

### ISSUE THREAD

**Issue by Zalamir** [WarEmu/WarBugs#15500]
Hi
Just been made aware that the morale 4 ress is not working as intended on all heal classes.. I have done tests of this. I tried to ress in RvR PvE and all can not be ressed with m4 ress.. please can you check this issue as it is happening to all players.
thanks
regards
Doglog

**Comment by raptrr** [comment]
Working for me. Maybe any1 else has the same issue?

**Comment by raptrr** [comment]
No further information, closing this issue.
