### ISSUE TITLE
Instant crash

### ISSUE THREAD

**Issue by Burntheday202** [WarEmu/WarBugs#15506]
Just recently started playing, started a human warrior priest. can only get about 30 seconds into the game before the app crashes with no error code or any indication that anything was wrong.

**Comment by jefflindholm** [comment]
Played in the past came back to play some with some free time, and have same issue regardless of character. Shut down most services.

**Comment by nnnnNATHANnnnn** [comment]
add the entire warhammer folder into ur antivirus software, don't use avast or it breaks the game, run in 64 bit, and check out these posts. https://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=19867 --------- https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=20075

**Comment by nnnnNATHANnnnn** [comment]
@jefflindholm if you followed the links I posted and ready them fully and you still can't get ur game to work I rec u to reinstall a new copy, but don't delete the old one, no reason to until u know its broke. then patch the new one you download, if it works it means the game prob had some error when u patched it the first time.

**Comment by Kaelang** [comment]
No further information has been provided since the last comment and this is not a game issue. If you're having problems with launching the game please refer to the forums for general / technical support.
