### ISSUE TITLE
[Quest] [T3 Epic] [Dark Elf] Honorable Deceit: missing quest mark for the stage linked

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#15509]
**Expected behavior and actual behavior:**

No map mark. Maybe a bit old as I found this in my HD and remember it. I can't seem to find anything related to it open or closed though.

**Steps to reproduce the problem:**

Reach this step in this quest

**Testing Screenshots/Videos/Evidences (always needed):**

![Dathenor_004](https://user-images.githubusercontent.com/50114048/72744342-4a468680-3ba5-11ea-9276-d44bd49ddc9b.jpg)

**Comment by Lheana** [comment]
Please read the quest (or the instructions on RoR Wiki), you should figure out why there is no end quest marker.
