### ISSUE TITLE
[Choppa] Invader hat has extra stats

### ISSUE THREAD

**Issue by gobo-WarWizKing** [WarEmu/WarBugs#15501]
**Expected behavior and actual behavior:**
Expect to equip gear and receive the stat bonus listed on said gear.
Actually, putting on the choppa Invader helmet (29 str, 13 tou, 18 ini) also provides a bonus to my Intelligence stat, +3 Int points.

Str	BS	Int	Tou	WS	Ini	WP	W
221 	98 	74 	147 	172 	196 	123 	518    no gear, tactics, or renown points
250  98 	77	160 	196 	214 	123 	518    invader helm, nothing else

**Steps to reproduce the problem:**
I tried this with multiple hats and found it reproduced in:
221 	98 	74 	147 	172 	196 	123 	518    no gear, tactics, or renown points
250  98    76    166 195   196  123  536    Bloodlord Skully 229 str, 19 tou, 18 wound

+2 Int points.

I tried this with all hats in my possession and did not find any other discrepancies.
Sets with correct stats: Devastator, Annihilator, Conqueror, Vanquisher, Sentinel, Ruin, Mayhem, Duelist, Mercenary, Redeye, Keeper's, Beastlord.
Collected hats (PQ, drops, etc) with correct stats: Gale-Runner's Skully, Ravager's Skully, Skully of the Deathbringer, Skully of the Fist.

I did not try to reproduce this with any other piece of armor or equipment.

![Kaputcha_001](https://user-images.githubusercontent.com/41939212/72671243-40cdea80-39fc-11ea-9e1f-3b56e0662444.jpg)
![Kaputcha_002](https://user-images.githubusercontent.com/41939212/72671244-44617180-39fc-11ea-8e2b-dbbc0b5fe41c.jpg)
![Kaputcha_003](https://user-images.githubusercontent.com/41939212/72671248-46c3cb80-39fc-11ea-93ee-7709fe52b8de.jpg)
![Kaputcha_005](https://user-images.githubusercontent.com/41939212/72671260-6529c700-39fc-11ea-94be-5fb201aa8995.jpg)

**Comment by Kabucoror** [comment]
Please provide a .getstats screenshot for the raw stats, the character sheet can be buggy.

**Comment by gobo-WarWizKing** [comment]
Using .getstats there is no difference, so looks like a character sheet bug. Thanks.
![Kaputcha_001](https://user-images.githubusercontent.com/41939212/72686312-27827800-3aa8-11ea-9e76-3117c42e2d8f.jpg)
![Kaputcha_002](https://user-images.githubusercontent.com/41939212/72686314-294c3b80-3aa8-11ea-818e-bb9613f0bf8b.jpg)
![Kaputcha_003](https://user-images.githubusercontent.com/41939212/72686315-2bae9580-3aa8-11ea-8c34-926600b01387.jpg)
