### ISSUE TITLE
[INFLUENCE REWARD] [EMPIRE] Chapter 16: Great disparity in level from potions to equiptment

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#15511]
**Testing Screenshots/Videos/Evidences (always needed):**
![Ototo_013](https://user-images.githubusercontent.com/50114048/72746841-0fdfe800-3bab-11ea-8b40-fff60a38ff71.jpg)
![Ototo_014](https://user-images.githubusercontent.com/50114048/72746843-0fdfe800-3bab-11ea-9486-2b843ada7de4.jpg)

**Comment by Lheana** [comment]
I am not really sure it's a real issue. Would need to check how it was on official.

**Comment by Kaelang** [comment]
Potion levels don't correlate to item levels. I.e. A level 1 potion will get you through until the next rank of potions open. You don't look for level 6-7 potions. 

If you think a change needs to be made, please use Suggestions & Feedback as initially this looks to be working as intended with separate rewards per influence tier.
