### ISSUE TITLE
stabilizing potions

### ISSUE THREAD

**Issue by gebajger** [WarEmu/WarBugs#1551]
The maximum ingredient level you could stabilize  with 1 (lvl200) resin/goldweed was lvl100 on live (lvl150 vial, lvl200 apo), so you could make up to lvl25 potions with extender and multiplier.
In RoR I can only do that up to lvl 75 main ingredient (lvl 20 potions)

**Comment by russellbarron** [comment]
Check to see if the passive Power/Stability bonuses for achieving certain apothecary levels are properly implemented. From HammerWiki (http://warhammeronline.wikia.com/wiki/Apothecary/Modifiers):
*An Apothecary Skill of 150 or greater applies a +1 stability bonus to any concoction.*

Current DB Values:
lvl 100: Spumepetal: -12 stability
Artisan's Glass Vial: +2 Stability
lvl 200 Goldweed: +10 Stability

Ergo, the +1 passive stability bonus must be missing

**Comment by gebajger** [comment]
I think it's the vial....both lvl100 and lvl150 vials have 4 stab value apparently

**Comment by gebajger** [comment]
It's fixed now

**Comment by nalgol** [comment]
should be fixed since last patch
