### ISSUE TITLE
[PQ] [EMPIRE] Chapter 21, PQ "Madness": 2nd stage can't be completed

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#15512]
**Expected behavior and actual behavior:**

You aren't be credited for the dead of the champion named Rolfgar Changewarden, so the PQ can't be completed.

**Steps to reproduce the problem:**

Reach second step of this PQ and proceed to kill this champion in the 2nd floor of the PQ.

**Testing Screenshots/Videos/Evidences (always needed):**

![Ototo_015](https://user-images.githubusercontent.com/50114048/72747082-97c5f200-3bab-11ea-93c3-8bb8026f7a70.jpg)

**Comment by Natherul** [comment]
should be fixed as of today

**Comment by Ootootoo** [comment]
It is. Tried it yesterday and works. Thanks :)
