### ISSUE TITLE
Unable to use skills in SC

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#15519]
I had a tank in the ranked SC who was apprently unable to use any skills. On my screen it looked like he had deployed a standard.
![Cimbia_022](https://user-images.githubusercontent.com/16117730/72932383-f92ec200-3d5f-11ea-82a0-b6bd739bafff.jpg)

On his screen he supposedly didnt see the standard. As you can see none of us recieved any standard buffs. He also couldnt stash the standard because that appears to be forbidden in scenarios.

**Comment by raptrr** [comment]
Would help to get his screenshots here as well and some info from him.

**Comment by raptrr** [comment]
No further information, closing this issue.
