### ISSUE TITLE
[KOTBS][Tactics] Banish Darkness does not reduce Repel Darkness cooldown

### ISSUE THREAD

**Issue by zulnam** [WarEmu/WarBugs#15518]
Expected:
When activated, Banish Darkness should reduce Repel Darkness ability cooldown to 10s.

Actual:
Although tooltip timer is reduced to 10s, actual gameplay cooldown is still 20s.

[Note] Issue was reproduced on a level 35 kotbs.

[Prerequisites] Have 'Show Cooldown Text' interface option activated.

STR:
1. Activate Banish Darkness tactic.
2. Use Repel Darkness ability (pve or pvp).
3. Observe given cooldown.

![Steyner_013](https://user-images.githubusercontent.com/19802847/72921745-c1b21c80-3d43-11ea-8364-856dd3e0289e.jpg)

**Comment by CrimsonFenris** [comment]
This tactic require 2H sword to fully work (and get the cd reduction). Sadly it's still not mentioned in the tooltip, and we need to know patchnotes from 2018 or 2019 to know that... :/

**Comment by zulnam** [comment]
Damn. Is there no way to update the Tooltip?

**Comment by SilverWF** [comment]
Tooltip is still shows wrong info
