### ISSUE TITLE
Ability Rumpage bypass Morale Confusing Movements

### ISSUE THREAD

**Issue by smistrz** [WarEmu/WarBugs#15529]
Please check this behavior as skill with 20s. duration and 30s. cooldown (Rumpage) shouldn't bypass morale with 7s. duration and 60s. cooldown (Confusing Movements).
Moreover as I remember from life server, there was 1 rule in force:
hierarchy of applications: skill < tacktic < morale.
After checking please share results and information when it will be solved.
Thank you in advance.

**Comment by Kaelang** [comment]
I'll need more information here to forward this over. Please can you supply tooltips and video evidence if possible to imply what you're insinuating is broken.

Thanks.

**Comment by Kaelang** [comment]
No further information provided - closed.
