### ISSUE TITLE
[Tooltip] Incosnsistency between bug tracker Mount tooltip and buff

### ISSUE THREAD

**Issue by zulnam** [WarEmu/WarBugs#15528]
Expected: Bug Tracker Mount tooltip and mount buff should specify the same speed.

Actual: Bug Tracker Mount tooltip specifies speed is 70% while mount buff is 60%.

[Notes] First WAR problems. 😄 

STR:
1. Get bug tracker mount (like a boss).
2. Mount your mount.
3. Inspect mount tooltip and mount buff.

![Steyner_017](https://user-images.githubusercontent.com/19802847/73032592-6c573780-3e37-11ea-9c1e-59945bb8f0b3.jpg)
![Steyner_018](https://user-images.githubusercontent.com/19802847/73032593-6c573780-3e37-11ea-883e-071f1696ba97.jpg)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/13663
