### ISSUE TITLE
'There was an error adding contribution to you' - Message during Reikwald.

### ISSUE THREAD

**Issue by Kaelang** [WarEmu/WarBugs#15521]
**Expected behavior and actual behavior:**

Expected: Contribution gains as normal. Reservation to function properly. 

Actual: No contribution is given for any action taken, I receive a Reservation when I'm ported to Reikwald after finishing Reikland, and then 'Your reservation has expired' once the fort starts. I died after our third attempt, 10 minutes left of the Fort, and was ported out, then given another reservation. When I died the fourth time, I rezzed at the war camp. (Meaning no cont was provided for the first 35 minutes of the entire map.

**Comment by Wiedehopf-bit** [comment]
Same issue here, message says to post what i did while getting the message.

I was a warband, Reikland, shortly before riding through the right gate (~15s after fort-start), message popped up 2x in 2 Minutes ('Failed to get on contributi**A**tion list, post @ bugtracker what you did'). No Contribution, no reward, no final exp/rr after Fort.
Today, 18:30 UTC +1, Reikwald

**Comment by dalen** [comment]
This should be fixed in the  latest patch (from 2020-02-15). Please open a new ticket if you can still reproduce this.
