### ISSUE TITLE
[quest] out of control

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#15523]
there are two lvl 26 "Talonblade Leader" mobs and none of them drops the "Raven host banner".
![Amidalo_009](https://user-images.githubusercontent.com/17765890/72955420-331db980-3d9c-11ea-8557-f805c79979f6.jpg)

instead banner is dropped when you kill a lvl 26 "Bloodrage Champion".
![Amidalo_011](https://user-images.githubusercontent.com/17765890/72955685-3e251980-3d9d-11ea-967d-d843f908f216.jpg)

ps: and you get a loot roll too ;)

**Comment by Kaelang** [comment]
As of 29/04/2020 this should now be fixed. Please re-open if issues persist.
