### ISSUE TITLE
Messing invader/Vanquiser medallions from Riekwald fort two times in a row. 

### ISSUE THREAD

**Issue by Drixxi** [WarEmu/WarBugs#15524]
Hi
On tuesday and monday I was in fort Riekwald but didnt get medallions or loot rolls. First fort we won- no medallions or loot roll. Second fort we loose but no medallions or loot roll. I got RP but nothing else. 

I made a GM appeal but got answer to make a bug report here instead. 

Is it possible to fix this? Maby get medallions?

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

<!--
Note that game critical and game breaking bugs may award a manticore/griffon (realm specific) at the leads discretion

**Comment by koopycommander** [comment]
Did you also get the lower left corner text "Something has gone wrong when attempting to add contribuation[sic] to you, please report on the bugtracker the circumstances of you entering the fort."?

I helped push with warband for hours and got nothing. I understand how you feel.
![no_contribuation](https://user-images.githubusercontent.com/60247399/73042233-559fe900-3e15-11ea-8c32-81581839281c.PNG)

**Comment by Drixxi** [comment]
Not what I saw, and i’ve never seen that text...

Weird but when I entered the zone for one of the two forts it said I got a reservation for 5 min. And after a while it said the 5 min reservation had passed. But that was when we were way in game for taking the fort.

Med vänlig hälsning
Robin Ljunggren



24 jan. 2020 kl. 04:20 skrev Chaos_Buddy <notifications@github.com<mailto:notifications@github.com>>:


Did you also get the lower left corner text "Something has gone wrong when attempting to add contribuation[sic] to you, please report on the bugtracker the circumstances of you entering the fort."?

I helped push with warband for hours and got nothing. I understand how you feel.
[no_contribuation]<https://user-images.githubusercontent.com/60247399/73042233-559fe900-3e15-11ea-8c32-81581839281c.PNG>

**Comment by koopycommander** [comment]
I get the "Reservation has expired" I think every time in the middle of
assaulting. But I have gotten the expired text and gotten medals. Not
saying there's no connection, there could be.

**Comment by raptrr** [comment]
1. we dont hand out any meds.
2. maybe you did no contribute enough?
3. did you enter the fort b4 it started?

**Comment by raptrr** [comment]
No further information, closing this issue.
