### ISSUE TITLE
Missing invaders reikwald

### ISSUE THREAD

**Issue by gantie91** [WarEmu/WarBugs#15525]
Out of the last 4 fort attacks, i only gained invader medallions on my squig herder wotzgit for two of them.

Sent a bug report in game and got a response from a GM to make a bug report here. dont know if its possible to gain the 8 medallions now or not but thought id give it a shot.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Likely contribution based - please re-open with additional information if you are able to replicate this moving forward.
