### ISSUE TITLE
Missing Invader Medallions from Reikland Fort Defense

### ISSUE THREAD

**Issue by Swampdog1824** [WarEmu/WarBugs#15520]
In the Reikland Fort Defense I was part of on the evening (US Central time) of 21 JAN 2020 I received no Invader medallions on my Swordmaster (name: Innowe).

I do not know if this is rank related, or part of the glitch that had been mentioned a handful of fixes past.

Also not asking to be gifted missing Invader medallions, just want to bring the concern forward to be fixed if it is a bug.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
The 27/05 patch has addressed some contribution issues / porting issues with forts. Please re-open if this is issue persists. 

Further to this - rewards have been changed.
