### ISSUE TITLE
Talabec Hill Barricades

### ISSUE THREAD

**Issue by colintgallagher** [WarEmu/WarBugs#15527]
The barricades put on the hill by Talabec keep can be jump-spammed through, I got in right at this area.
![Sarnai_028](https://user-images.githubusercontent.com/56422919/73031774-081e7e80-3e0b-11ea-8883-d71521924c01.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by Natherul** [comment]
should be fixed as of today
