### ISSUE TITLE
Fort contribution bug

### ISSUE THREAD

**Issue by GreatHarlequin** [WarEmu/WarBugs#15537]
Just entered Reikwald Fort on Des alt (GRISCHNAK). Got in straight away, just before the fort starts I got a system message saying,

"Something has gone wrong when attempting to add contribution to you, please report on the bugtracker the circumstances of you entering the fort."

I just sat in Reikland until zone locked and followed WB straight into Reikwald. No problems getting in.

![Grischnak_000](https://user-images.githubusercontent.com/13045932/73093121-2c975b00-3ede-11ea-86c8-5a13a3551adf.jpg)

**Comment by raptrr** [comment]
Did you get a fort reservation message?

**Comment by GreatHarlequin** [comment]
Sheesh, it was so long ago I can't remember. I don't recall noticing a message on my screen or in chat.

**Comment by raptrr** [comment]
Im gonna leave this open for 14 days, next time it happens, please have a look

**Comment by GreatHarlequin** [comment]
Will do.

**Comment by dalen** [comment]
This should be fixed in the  latest patch (from 2020-02-15). Please open a new ticket if you can still reproduce this.
