### ISSUE TITLE
Missing blue bag from successful T2 Elf RvR attack

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#15532]
Character name: Zomega

**Expected behavior and actual behavior:**

I won a blue loot bag after destruction captured T2 elf (screenshot attached showing the roll). I wasn't near the keep so I waited for it to be mailed to me. I moved to the next zone and it still didn't appear (the mail icon on the screenshot is bugged from the AH - I'll raise another ticket if I can't find an open one).

I have since had mail come through for auctions while online, and while offline I had my rewards for capturing Elf T3 come through (tokens and a green bag - I had to leave mid campaign so it was rolled for when offline) but the blue bag didn't come through.

**Steps to reproduce the problem:**

N/A

**Testing Screenshots/Videos/Evidences (always needed):**

![Zomega_008](https://user-images.githubusercontent.com/60266177/73083444-16c86c80-3ec3-11ea-86ae-2aa893ccf1e1.jpg)

**Comment by RoR-Zomega** [comment]
Update: the bag had arrived after I logged in this morning at 25-01-2020 10:40 UTC (I logged out 24-01-2020 at about 19:00 UTC).

I'm leaving this open in case you want to investigate what caused the delay in the bag being sent. Also, if it was sent manually then thank you :)

**Comment by Natherul** [comment]
Should have been fixed with the patch from yesterday
