### ISSUE TITLE
[Engineer] [Bumgans Keg] Nullreference Exception and no Keg deployed.

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#1553]
After trying to deploy the Bumgans Kegg Tinkerer Ability, the Keg says its Nullrefrence in Saychat.
And no Keg is deployed.
After Relog there is still no Keg deployed, but it doesn't say the text.

**Comment by ozarmidrashim** [comment]
Probably affects every ability which requires a position
