### ISSUE TITLE
Mork's Blasta incorrect proc buff value

### ISSUE THREAD

**Issue by lethewyvern** [WarEmu/WarBugs#15531]
Mork's Blasta proc "Preservation" should increase Wounds by 110, infact it gives only 80 Wounds.
![Bubblech_052](https://user-images.githubusercontent.com/57109035/73082707-c7e2fd00-3eeb-11ea-915f-fcb52c6447a5.jpg)
---
![Bubblech_054](https://user-images.githubusercontent.com/57109035/73082732-d03b3800-3eeb-11ea-98ef-0946b24c1b9e.jpg)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/15283
