### ISSUE TITLE
KOTBS - Arcing Swing

### ISSUE THREAD

**Issue by ngx83922** [WarEmu/WarBugs#15530]
Sometimes 2h weapons show Arcing Swing greyed out as like you can't use the skill.

**Comment by Ootootoo** [comment]
It requires the use of a 2h weapon.

**Comment by ngx83922** [comment]
> It requires the use of a 2h weapon.

I know.
It seems fixed since todays patch without marking this thread or telling us in the patch notes.

**Comment by ngx83922** [comment]
> It requires the use of a 2h weapon.

I know, edited it.

**Comment by Kaelang** [comment]
Need more information, such as level, equipped items, screenshot of ability etc.

**Comment by Kaelang** [comment]
No further information - closed.
