### ISSUE TITLE
[SC] The Eternal Citadel matchmaking

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#15539]
it has matchmaking rule for pug.
dps tank, dps heal getting true tank heal slots.
![sc_Eternal Citadel](https://user-images.githubusercontent.com/19988772/73117513-09c28080-3f8a-11ea-8dc4-d10ab9839482.jpg)
dok was dual wield. full dps tree.

**Comment by Kaelang** [comment]
Since fixed.
