### ISSUE TITLE
Caledoor Woods UI/stuck bug at end

### ISSUE THREAD

**Issue by toffikx** [WarEmu/WarBugs#15546]
**Expected behavior and actual behavior:**

Couldn't leave after Caledor Woods ended. Had to unstuck, but was still in combat, still in party group, chat and still with scenario tracker frames after.

**Testing Screenshots/Videos/Evidences (always needed):**

![Faaceshaper_067](https://user-images.githubusercontent.com/49347536/73129372-5afe5e80-3fe2-11ea-875c-990f088afc6d.jpg)

**Comment by Kaelang** [comment]
As Caledor Woods is no longer used for the Ranked Scenarios, I'm going to close this up for now as this looks to be Scenario / System related and there's been a magnitude of changes with the Scenario system in the past few weeks.

Please re-open if this issue persists in the new maps.
