### ISSUE TITLE
Fort contribution bug

### ISSUE THREAD

**Issue by bezlikiy87** [WarEmu/WarBugs#15543]
Got in straight away, just before the fort starts I got a system message saying,

"Something has gone wrong when attempting to add contribution to you, please report on the bugtracker the circumstances of you entering the fort."

I just sat in Reikland until zone locked and followed WB straight into Reikwald. No problems getting in.

![Bezlikiy_005](https://user-images.githubusercontent.com/60247043/73121704-ea2d5700-3f8d-11ea-985b-209312a9fe48.jpg)

**Comment by raptrr** [comment]
Did you get a fort reservation?

**Comment by raptrr** [comment]
No further information, closing this issue.
