### ISSUE TITLE
Squig Herder Pets

### ISSUE THREAD

**Issue by Stinkyweed** [WarEmu/WarBugs#1554]
Ranged Disarm is designed to go off on pets next attack.  On live it wentirely off on any pet special or auto attack.  On RoR it only fires off on pet special, if at all.  This results in a long delay between ability selection and execution.

Pet specials. Pets are not attacking with both specials as they are available from cooldown. You can force a pet to use its first special when it's avaliable by selecting the ability on the bar.  The second ability is not used at all. I tested by having my pet attack monsters as I spammed the second ability...it never triggered through multiple tests.  Is there a way to force the pets to use both abilities on cooldown?

Pet range seems to have changed.  Originally on RoR they would go wherever, which was terrible.  Now, ranged pets stay close to the squig all the time. On live, they could wander a bit away and attack from greater than 100ft distance...probably twice that. Now they seems to be tethered closer to herder and limited to herder max distance.  My guess is that this was intended though.

Shrapnel Arrer is not instantaneous, as compared to Explosive Arrer. There is an animations left over  and a lag to select next ability.

**Comment by Evildoor** [comment]
Please, make 1 report per issue next time.

**Comment by ozarmidrashim** [comment]
Drop That!! listens for the DirectDamageDealt event which fires from direct damage of any kind, including the AA. All auto attacks in the game go through this same path - player, pet or NPC.

**Comment by ozarmidrashim** [comment]
Regarding pet specials - I'm playing a WL right now and the pet is using all of the specials it has. The code is the same for SH.

**Comment by Stinkyweed** [comment]
Can we get someone to confirm in game about SH pet specials? They used to both work in RoR, now the first one only works.

**Comment by Silentguard** [comment]
Confirm. SH pet is broken like was said in op post. Also after pet death he lose abilities and you even cant force use it.
