### ISSUE TITLE
RVR Guild Quest Broke

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15547]
**Expected behavior and actual behavior:**

Expected to complete on zone lock after all conditions are met.
Actually doesn't give credit for zone lock since new patch tried with 4 different zones.

**Steps to reproduce the problem:**

Meet conditions and lock zone.

**Testing Screenshots/Videos/Evidences (always needed):**

![Meatballsub_025](https://user-images.githubusercontent.com/43802105/73132273-7d8e7880-3fde-11ea-9711-887ddbe28e9d.jpg)

![Meatballsub_027](https://user-images.githubusercontent.com/43802105/73132264-63549a80-3fde-11ea-9af1-795d8d4801fc.jpg)

**Comment by Natherul** [comment]
should be fixed as of today
