### ISSUE TITLE
Mandred's Hold Pounce locations

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15549]
**Expected behavior and actual behavior:**

Expected not to pounce there per say of lead dev. 

**Steps to reproduce the problem:**
pounce there

**Testing Screenshots/Videos/Evidences (always needed):**

![Meatballsub_028](https://user-images.githubusercontent.com/43802105/73139809-8c554980-4037-11ea-8c9e-4f2606eba223.jpg)
![Meatballsub_029](https://user-images.githubusercontent.com/43802105/73139811-90816700-4037-11ea-9e89-aeb7c18a05e0.jpg)

**Comment by Natherul** [comment]
should be fixed as of today
