### ISSUE TITLE
Fortress Contribution

### ISSUE THREAD

**Issue by GabrielB08** [WarEmu/WarBugs#15540]
I asked in game to leave a bug report describing how i entered the fortress. It told me the game failed to count my contribution.

I entered from Reikland by mount when the outer doors had already opened; I arrived late. I was in a warband at the moment, and most of the members were already not inside, except for the leader. When crossing the border there was first a "lag" where I fell back a few meters. The second time crossing the border immeadiately after the first attempt, I got in. A window said I was reserved a spot for 5 minutes. After fighting for a while, I got a message that my reservation had expired. I believe it was after this I noticed the message that my contribution failed.

I hope this helps, and thank you for all the amazing work you've done! I'm here if you need anything else.

**Comment by dalen** [comment]
This should be fixed in the  latest patch (from 2020-02-15). Please open a new ticket if you can still reproduce this.
