### ISSUE TITLE
Burning Oil is doing more damage since last patch?

### ISSUE THREAD

**Issue by Kaelang** [WarEmu/WarBugs#15545]
We was able to survive the Oil during previous sieges, yet since today 26/01/20 the oil is ticking for 3k and practically one shotting tanks using the Ram. (I believe it's double ticking)

I'm not sure if this is intended, but it definitely feels much much stronger than previous.

Replicated by sitting under oil and reviewing damage taken. 

Currently on Karag Karag (Thunder Mountain) keep, but has been happening all over.

**Comment by Scophis** [comment]
It's intentional 
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=35001&start=30#p388414
