### ISSUE TITLE
Kazad Dammaz keep pounce locations 

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15558]
**Expected behavior and actual behavior:**
expected to not be able to pounce on walls per lead dev

**Steps to reproduce the problem:**

climb tree/outer wall to pounce

**Testing Screenshots/Videos/Evidences (always needed):**

![Meatballsub_012](https://user-images.githubusercontent.com/43802105/73141504-4a81ce80-404a-11ea-9917-18f6e6bc405c.jpg)
![Meatballsub_041](https://user-images.githubusercontent.com/43802105/73303220-9fa11a00-41db-11ea-9dad-59d6d57737fd.jpg)

![Meatballsub_014](https://user-images.githubusercontent.com/43802105/73141505-4d7cbf00-404a-11ea-945c-e84325f5ce81.jpg)

**Comment by Natherul** [comment]
should be fixed as of today
