### ISSUE TITLE
Stoneclaw Castle pounce location

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15553]
**Expected behavior and actual behavior:**
Expected to not be able to pounce on the wall per lead dev

**Steps to reproduce the problem:**

pounce on target on wall

**Testing Screenshots/Videos/Evidences (always needed):**

![Meatballsub_005](https://user-images.githubusercontent.com/43802105/73140429-6f704480-403e-11ea-8fbe-cfb3e79661f7.jpg)

**Comment by Natherul** [comment]
should be fixed as of today
