### ISSUE TITLE
Gnol Baraz pounce location 

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15554]
**Expected behavior and actual behavior:**
Expected to not be able to pounce on walls per lead dev

**Steps to reproduce the problem:**
pounce on target on wall

**Testing Screenshots/Videos/Evidences (always needed):**

![Meatballsub_006](https://user-images.githubusercontent.com/43802105/73140524-62a02080-403f-11ea-9522-49783563954d.jpg)

**Comment by Natherul** [comment]
should be fixed as of today
