### ISSUE TITLE
Spites Reach pounce location

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15552]
**Expected behavior and actual behavior:**

Expected to not be able to pounce on wall per lead dev

**Steps to reproduce the problem:**
climb tree and pounce 

**Testing Screenshots/Videos/Evidences (always needed):**

![Meatballsub_003](https://user-images.githubusercontent.com/43802105/73140244-7302cc00-403c-11ea-8a9c-ca94af58ea7e.jpg)
![Meatballsub_004](https://user-images.githubusercontent.com/43802105/73140249-7c8c3400-403c-11ea-95e4-a4f820bc5a1b.jpg)

**Comment by Natherul** [comment]
should be fixed as of today
