### ISSUE TITLE
Karaz Drengi keep pounce location

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15559]
**Expected behavior and actual behavior:**
expacted to not be able to pounce on walls per lead dev

**Steps to reproduce the problem:**

pounce on target or siege wep

**Testing Screenshots/Videos/Evidences (always needed):**

![Meatballsub_015](https://user-images.githubusercontent.com/43802105/73141584-53bf6b00-404b-11ea-88b5-d98a713d97b0.jpg)
![Meatballsub_016](https://user-images.githubusercontent.com/43802105/73141586-5621c500-404b-11ea-8d98-74e2afc8bdaf.jpg)

**Comment by Natherul** [comment]
should be fixed as of today
