### ISSUE TITLE
Southern Garrison wall pounce location

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15556]
**Expected behavior and actual behavior:**

expected to not be able to pounce onto wall per lead dev

**Steps to reproduce the problem:**
climb outer wall pounce

**Testing Screenshots/Videos/Evidences (always needed):**

![Meatballsub_011](https://user-images.githubusercontent.com/43802105/73140960-29b67a80-4044-11ea-8a3b-b43b170c1fb2.jpg)

**Comment by dalen** [comment]
Fixed by the 2020-09-09 patch
