### ISSUE TITLE
StoneTroll Keep pounce location

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15550]
**Expected behavior and actual behavior:**

expected not to be able to pounce on wall per lead dev.

**Steps to reproduce the problem:**
climb rock and pounce 

**Testing Screenshots/Videos/Evidences (always needed):**

![Meatballsub_030](https://user-images.githubusercontent.com/43802105/73139956-27025800-4039-11ea-89a5-7e4fbb2f04b5.jpg)
![Meatballsub_031](https://user-images.githubusercontent.com/43802105/73139959-2964b200-4039-11ea-9e62-d0a30ed2a0d8.jpg)

**Comment by Natherul** [comment]
should be fixed as of today
