### ISSUE TITLE
Fang Breaka Swamp pounce location

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15551]
**Expected behavior and actual behavior:**

Expected not to be able to pounce on wall per lead dev

**Steps to reproduce the problem:**

climb tree and pounce 

**Testing Screenshots/Videos/Evidences (always needed):**

![Meatballsub_001](https://user-images.githubusercontent.com/43802105/73140134-020ee480-403b-11ea-9de2-8a86256bbd94.jpg)
![Meatballsub_000](https://user-images.githubusercontent.com/43802105/73140138-089d5c00-403b-11ea-9e12-d4baf2df5db5.jpg)

**Comment by Natherul** [comment]
should be fixed as of today
