### ISSUE TITLE
Ghrond's Sancristy pounce locations

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15555]
**Expected behavior and actual behavior:**

expected to not able to pounce onto walls per lead dev

**Steps to reproduce the problem:**

run up outer wall pounce anywhere around the back side of inner because walls are too close.

**Testing Screenshots/Videos/Evidences (always needed):**

![Meatballsub_007](https://user-images.githubusercontent.com/43802105/73140794-7f8a2300-4042-11ea-8b0f-ebb45a905709.jpg)
![Meatballsub_008](https://user-images.githubusercontent.com/43802105/73140795-81ec7d00-4042-11ea-8541-c8f14ba128f1.jpg)
![Meatballsub_009](https://user-images.githubusercontent.com/43802105/73140800-8a44b800-4042-11ea-9201-55dbc0b7b98c.jpg)
![Meatballsub_010](https://user-images.githubusercontent.com/43802105/73140805-8dd83f00-4042-11ea-9fb3-513e5e15b7bf.jpg)

**Comment by dalen** [comment]
Fixed by the 2020-09-09 patch
