### ISSUE TITLE
Wrath's Resolve keep pounce locations

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15562]
**Expected behavior and actual behavior:**
expected not to be able to pounce on wall per lead dev

**Steps to reproduce the problem:**

climb rocks pounce walls

**Testing Screenshots/Videos/Evidences (always needed):**

![Meatballsub_023](https://user-images.githubusercontent.com/43802105/73142104-ac453700-4050-11ea-9638-629ab7caf57e.jpg)
![Meatballsub_022](https://user-images.githubusercontent.com/43802105/73142107-aea79100-4050-11ea-9324-4113b8579174.jpg)
![Meatballsub_025](https://user-images.githubusercontent.com/43802105/73142110-b5360880-4050-11ea-8ae2-61eaae311f17.jpg)
![Meatballsub_024](https://user-images.githubusercontent.com/43802105/73142111-b830f900-4050-11ea-9d5a-1c4e5c6bec42.jpg)

**Comment by Natherul** [comment]
should be fixed as of today
