### ISSUE TITLE
Karak Karag keep pounce locations

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15560]
**Expected behavior and actual behavior:**

expected to not be able to pounce onto walls as per lead dev

**Steps to reproduce the problem:**

climb rocks pounce target

**Testing Screenshots/Videos/Evidences (always needed):**

![Meatballsub_018](https://user-images.githubusercontent.com/43802105/73141803-db0dde00-404d-11ea-8064-1be80e302c9e.jpg)
![Meatballsub_017](https://user-images.githubusercontent.com/43802105/73141811-df39fb80-404d-11ea-886d-007ba052b867.jpg)
![Meatballsub_019](https://user-images.githubusercontent.com/43802105/73141814-e3661900-404d-11ea-9c87-9dc45a085ef3.jpg)
![Meatballsub_020](https://user-images.githubusercontent.com/43802105/73141815-e52fdc80-404d-11ea-9713-834bc136d0a7.jpg)

**Comment by Natherul** [comment]
should be fixed as of today
