### ISSUE TITLE
Drakebreakers Scourge keep pounce locations

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15561]
**Expected behavior and actual behavior:**
expected not to be able to pounce on/bypass walls

**Steps to reproduce the problem:**

find target pounce passed wall

**Testing Screenshots/Videos/Evidences (always needed):**

![Meatballsub_021](https://user-images.githubusercontent.com/43802105/73141963-2a084300-404f-11ea-94cd-9387f0b3852f.jpg)

**Comment by Natherul** [comment]
should be fixed as of today
