### ISSUE TITLE
Unbound and damageable while in jail

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15564]
**Expected behavior and actual behavior:**

Expected to be bound in jail and immune to dmg.
Actually: takes dmg and able to use abilities once released into jail.

**Steps to reproduce the problem:**

Release into jail. 

**Testing Screenshots/Videos/Evidences (always needed):**

![Meatballsub_027](https://user-images.githubusercontent.com/43802105/73161315-e3e3cb80-40b0-11ea-9358-4b0d8d88618c.jpg)

**Comment by Kaelang** [comment]
This was addressed and fixed in a recent patch. Please re-open if issue persists.
