### ISSUE TITLE
[Fort] contribution message

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#15566]
![Fort_message](https://user-images.githubusercontent.com/19988772/73235933-ca877000-41d3-11ea-83ef-c177d3a336a0.jpg)

1. got reservation as chosen
2. changed toon to zealot
3. entered fort
4. got reservation queue popup and teleported back to old portal location
5. still could enter fort
6. got 'wrong' message on flag capture
7. release respawn location was outside of fort ( east bridge of reikwald )
8. re-enter teleported to old portal location and reservation popup again
9. after reservation expired popup, no more 'wrong' message, everything back to normal
10. maybe it's after respawn and re-enter, not sure
11. got rewards at the end

**Comment by robswalker68** [comment]
Similar to this, but slightly different circumstances:

1. Logged on 1 minute into Reikland Siege 28/01/2019 (char: Alixr)
2. Used War Report to teleport to Reikwatch
3. Entered Fort in Stage 2, with no reservation message.
4. Received messages about contribution not being applied and to log on Bug tracker
5. 10/15 minutes into Stage 2.  Received a reservation ticket with the normal 5 mins to use message
6. Continue to get messages about non contribution.
7. If I died I would be teleported to co-ords 32768,3612.  If I ran over the bridge I would be teleported to Reikland @ 21991,64852 and could enter the fort.
8. 5 mins into the begin of Stage 3 I received a message that my reservation ticket had expired
9. 5 mins to the end of stage 3 I got another reservation ticket
10. Did not receive contribution or medals as contribution too low.  Not an issue by the way

**Comment by dalen** [comment]
This should be fixed in the  latest patch (from 2020-02-15). Please open a new ticket if you can still reproduce this.
