### ISSUE TITLE
T1 oRvr Empire Lair - Heals not applying while in Boss lair

### ISSUE THREAD

**Issue by ouronlyplanb** [WarEmu/WarBugs#15571]
T1 oRvR Empire Lair - Heals were not applying while we were in the Boss lair.

We (Destro) tried 2 different healers, and none of them could use direct heals in the Empire T1 Lair.

We also saw a group of order come in, and watched at the WP panicked about his heals not going off.

The animations, effects and buffs for Heals of Time spells seemed to work. But none of the direct healing worked.

This was NOT the case in the other 2 lairs that we did. 

Cheers
Rowduck.

**Comment by Kaelang** [comment]
Tested on dev - heals are working in the lair.

Closed.
