### ISSUE TITLE
Invader doesnt work

### ISSUE THREAD

**Issue by Guerra-warhammer** [WarEmu/WarBugs#15577]
The Zealot Invader prog from the 7. set-item doesnt work. Deep Scheming never prog so i get no buff/healboni oder anything stay in the combat log about this prog.

[URL=https://www.bilder-upload.eu/bild-3824b3-1580322670.jpg.html][IMG]https://www.bilder-upload.eu/thumb/3824b3-1580322670.jpg[/IMG][/URL]

or 

https://www.bilder-upload.eu/bild-3824b3-1580322670.jpg.html

i dont know what screen you need for that bug, i think its esay to see for the devs :)

**Comment by CrimsonFenris** [comment]
Same issue with SW invader set (see https://github.com/WarEmu/WarBugs/issues/15503). Guess with destru issue it will get more visibility... :/

**Comment by Kaelang** [comment]
![image](https://user-images.githubusercontent.com/60117106/82151836-86d57680-9855-11ea-9181-d6ef58f803fa.png)

Closed.
