### ISSUE TITLE
TOK for Killing 1K pegesus no longer rewards cloak (infinite sadness)

### ISSUE THREAD

**Issue by nnnnNATHANnnnn** [WarEmu/WarBugs#15570]
I killed 1000 pegesus for the cloak cause I thought it would look nice on my toon, and it didn't give me the cloak. Relog didn't fix it :l    

![Goremagala_006](https://user-images.githubusercontent.com/56577119/73320613-bc961700-41f4-11ea-8dc5-892159f77524.jpg)

**Comment by Lheana** [comment]
That's because you have to buy it.

**Comment by nnnnNATHANnnnn** [comment]
thank you for the response I had no idea
