### ISSUE TITLE
Will of the Warboss

### ISSUE THREAD

**Issue by Dragothurch** [WarEmu/WarBugs#15573]
Hi !
When need 10 wine and 1 typso priesterstadt guard, the guard bugged. When i kill, not count and cant finish this step in questline. Thx.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
Were you grouped when you tried to complete this quest?
