### ISSUE TITLE
Fort bag loot

### ISSUE THREAD

**Issue by Dragothurch** [WarEmu/WarBugs#15572]
Hi !
Sry for my english. I dont know this bug or normal but today won gold bag in fort and i find 3 or 4 belt in bag. Maybe new system for chose 1 loot from bag what need for me and bugged and cant chose or i dont know what is this. And belt got long time. So pls change something this loot system or repair the bug. Other thing. Brutal lag on fort, unplayable the game. Thx for answer, nice work on game

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Natherul** [comment]
should be fixed with patch as of today
