### ISSUE TITLE
Zealot - [Visual] Droping willpower to 0 while in Harbinger of Doom

### ISSUE THREAD

**Issue by notre4ror** [WarEmu/WarBugs#15579]
**Expected behavior and actual behavior:**
After un-equiping gear the base stats have to remain.
base inteligence: 196
base willpower: 221

If you un-equip the gear before toggling Harbinger of Doom you got the base int (196) and the base willpower (221), but if you do that with Harbinger toggled, your willpower drops to 0 on the character window, .getstats still show the base willpower (221)

**Steps to reproduce the problem:**
Equip some gear, un-equip that gear without using Harbinger and you'll get 221 willpower on your character window.
Equip some gear, toggle Harbringer of doom, un-equip the gear and you have 0 willpower on your character window  (not on getstats).

**Testing Screenshots/Videos/Evidences (always needed):**

Base stats:
![imagen](https://user-images.githubusercontent.com/17686095/73389828-44ebe900-42d5-11ea-88c8-a06edf2b40f9.png)

0 Willpower, Harbinger toggled, no gear equiped.
![imagen](https://user-images.githubusercontent.com/17686095/73389875-5af9a980-42d5-11ea-977b-309bb3bbd740.png)

**Comment by raptrr** [comment]
Please provide screenshots with the .getstats command and post them here. char screen can bug out.

**Comment by raptrr** [comment]
No further information, closing this issue.

**Comment by notre4ror** [comment]
Sorry for the late answer, but i already state that on .getstats it's ok, so i can't provide new information, and as the title says it's "Visual".

" .getstats still show the base willpower (221)"

"Equip some gear, toggle Harbringer of doom, un-equip the gear and you have 0 willpower on your character window (not on getstats)."

**Comment by grunbag** [comment]
0 willpower with harbinger of doom is correct , all your wp is converted into Intel . Same does harginger of change does with intel to wp

**Comment by dalen** [comment]
@grunbag isn't it supposed to only convert stats from gear?
Not convert base stats, tactics & buffs.

**Comment by grunbag** [comment]
True , but it seems to Be a client bug when you have no gear , I can’t redo mythic client component for this calculation
