### ISSUE TITLE
[Pve] [Achievements] Bloodlord set

### ISSUE THREAD

**Issue by Killham** [WarEmu/WarBugs#15582]
**Got my 6 piece Bloodlord Set, without cloak, like 2 days ago, put in on the character**:
![Gobinrood_003](https://user-images.githubusercontent.com/18173840/73405329-a8413f80-4304-11ea-92bc-dd92f92940c9.jpg)
![Gobinrood_000](https://user-images.githubusercontent.com/18173840/73405370-bb540f80-4304-11ea-8867-85f85d79a5d1.jpg)
**But doesnt get superior ward and achieve with title in ToK(even after planty relogs)**:
![Gobinrood_001](https://user-images.githubusercontent.com/18173840/73405515-2867a500-4305-11ea-8332-07e23c6df056.jpg)
![Gobinrood_002](https://user-images.githubusercontent.com/18173840/73405521-2c93c280-4305-11ea-9274-43120e52d349.jpg)

**Comment by Natherul** [comment]
functionally the same as https://github.com/WarEmu/WarBugs/issues/15496
