### ISSUE TITLE
Garrison of Skulls pounce locations

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15587]
**Expected behavior and actual behavior:**
Expected to not be able to pounce onto walls per the lead dev. 
I'd like to note that this keep has many MANY multiple locations as such I'll be providing multiple SS for it if somethings not clear just get with me.

**Steps to reproduce the problem:**

go to the location and pounce

**Testing Screenshots/Videos/Evidences (always needed):**

![Meatballsub_048](https://user-images.githubusercontent.com/43802105/73511268-b77ac880-43aa-11ea-8447-52b20d2c857d.jpg)
![Meatballsub_049](https://user-images.githubusercontent.com/43802105/73511282-c06b9a00-43aa-11ea-8ba2-0ca9263d06fa.jpg)
![Meatballsub_000](https://user-images.githubusercontent.com/43802105/73511372-0de80700-43ab-11ea-940b-e078ecffae50.jpg)
![Meatballsub_051](https://user-images.githubusercontent.com/43802105/73511395-193b3280-43ab-11ea-94a1-3a28469c9b32.jpg)
![Meatballsub_052](https://user-images.githubusercontent.com/43802105/73511402-20624080-43ab-11ea-961a-06d21968281d.jpg)
![Meatballsub_053](https://user-images.githubusercontent.com/43802105/73511420-28ba7b80-43ab-11ea-94d4-413e41f25be7.jpg)
![Meatballsub_054](https://user-images.githubusercontent.com/43802105/73511431-307a2000-43ab-11ea-90f3-65cc028f9dba.jpg)
![Meatballsub_055](https://user-images.githubusercontent.com/43802105/73511439-37a12e00-43ab-11ea-9afd-2330480eb636.jpg)
![Meatballsub_057](https://user-images.githubusercontent.com/43802105/73511463-4851a400-43ab-11ea-8740-a9f044a84a67.jpg)
![Meatballsub_058](https://user-images.githubusercontent.com/43802105/73511479-5273a280-43ab-11ea-8047-83811f4657e2.jpg)
![Meatballsub_043](https://user-images.githubusercontent.com/43802105/73511518-7afb9c80-43ab-11ea-9424-d4e4ce8e0013.jpg)
![Meatballsub_042](https://user-images.githubusercontent.com/43802105/73511531-7e8f2380-43ab-11ea-8a22-d6f370a6d48b.jpg)

![Meatballsub_001](https://user-images.githubusercontent.com/43802105/73511654-1260ef80-43ac-11ea-8801-17326488e153.jpg)
![Meatballsub_044](https://user-images.githubusercontent.com/43802105/73511660-1bea5780-43ac-11ea-88b2-034ed3ea4dfd.jpg)

**Comment by Natherul** [comment]
should be fixed as of today
