### ISSUE TITLE
Not able to count my contribution to get into fort

### ISSUE THREAD

**Issue by starfkr** [WarEmu/WarBugs#15580]
Had contribution and all of the suddenly lost it:

https://cdn.discordapp.com/attachments/525044032498434049/672169529777979392/image0.jpg

**Comment by aksashinmu** [comment]
I have the same problems these days. 
I am not able to count my contribution to get into fort.

![error-Uggut](https://user-images.githubusercontent.com/60447980/73394131-9d55c300-42a2-11ea-8492-4a809cc5118a.png)

**Comment by squeegiefreak** [comment]
Same issue 31/01/2020 
![image](https://user-images.githubusercontent.com/12853897/73530911-116aa500-4422-11ea-804a-a13ad601b592.png)

**Comment by dalen** [comment]
This should be fixed in the  latest patch (from 2020-02-15). Please open a new ticket if you can still reproduce this.
