### ISSUE TITLE
[AM] wild healing ap reduction [ability]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#15586]
the ap reduction you recive  is lower than the ap cost show on skill icons; for exemple:

boom of hysh --> cost show on skill 23 while buff /  from 250 ap after skill i drop to 221 (so payed 29)
healing energy --> cost show on skill 28 while buff /  from 250 ap after skill i drop to 215 (so payed 35)

it happen on all heals, you pay slight more than the 50% reduction you should have while under effect of wild healing

**Comment by kalmatar** [comment]
Wild Healing was nerfed from 50% to 35% or so back in august-september 2018, tooltip info is wrong or someone just changed tooltip but forgot to adjust the nerf since then. 
35%, as the tooltip should be, explains why 45 AP cost ability uses 29 AP.

**Comment by Tesq** [comment]
if it is so then tactic tooltips need adjsutement
