### ISSUE TITLE
[SCENARIO] [PUG] Current PUG scenario, Gates of Ekrund, unavailable to queue in

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#15581]
**Expected behavior and actual behavior:**

When you click the scenario button to enter a queue, Gates of Ekrund, that is the scenario listed when you enter the command .pug, is not part of the list of scenarios, at least on order side.

**Steps to reproduce the problem:**

AFAIK, login in order, try to search the current PUG scenario, Gates of Ekrund, and it's nowhere to be found.

**Testing Screenshots/Videos/Evidences (always needed):**

Irrelevant. Nothing to capture cause there is nothing there. Sorry.

**Comment by Natherul** [comment]
fixed on the server now, a field was missed in update of the database so the weekly (monday) automated rotation rotated the pug SC out of rotation
