### ISSUE TITLE
[BB] Bilerot Sickness without "Gag Self"

### ISSUE THREAD

**Issue by bosli42** [WarEmu/WarBugs#15583]
In the IC dungeon Bilerot Burrow, it's extremely common to end up with the Bilerot Sickness without the "Gag Self" special skill to get rid of it.

In a run I did yesterday as well as about 2 weeks back, I paid very close attention the whole time and always used the skill immediately when it popped up. About 3/4 it removed the debuff, but the rest the debuff persisted after using the skill.

I suspect that it gets instantly reapplied by the maggot that spawns when you use it, or that you can even end up with multiple stacks of it even though the interface doesn't show it. If Gag Self is used immediately and again after the 5 second cooldown, it's possible to get rid of two Sickness debuffs in a row, but in two cases yesterday I still had a third debuff, and the Gag Self ability vanished before the second 5s cooldown was over.

I like that you only have a certain time limit to "gag yourself" or you are stuck with it for a bit, but I'm pretty sure it's not working as intended since the debuff makes healing on the long casters (shaman and zealot) extremely hard, and kind of a gamble.

If the cause for multiple / persisting Sickness' can't be found, I suggest to either give immunity for a short time after using the Gag so it wouldn't reapply, to remove the cooldown timer of the skill, or even to grant the skill to all players the whole time so they can just use it whenever they need to (though that would defeat the time limit, and it could spawn endless maggots).

**Comment by Kaelang** [comment]
Fixed as of 13/05/2020 patch. Please re-open if issue persists.
