### ISSUE TITLE
Zimmeron Keep Pounce Location

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15588]
**Expected behavior and actual behavior:**

Expected to not be able to pounce onto keep wall per lead dev

**Steps to reproduce the problem:**

go to location and pounce

**Testing Screenshots/Videos/Evidences (always needed):**

![Meatballsub_046](https://user-images.githubusercontent.com/43802105/73512392-0d516f80-43af-11ea-836b-e6108523ad91.jpg)

![Meatballsub_045](https://user-images.githubusercontent.com/43802105/73512375-fdd22680-43ae-11ea-8747-e579073e340a.jpg)
![Meatballsub_047](https://user-images.githubusercontent.com/43802105/73512404-17736e00-43af-11ea-84d9-bb5084d0c705.jpg)

**Comment by Natherul** [comment]
should be fixed as of today
