### ISSUE TITLE
NullReferenceException causes Order's keep lord in Praag to delete itself

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#15593]
During the siege of the order keep in Praag at midnight 1st February 2020 the lord said this in chat while it was being attacked (both doors were down):

[00:08:05] [Inquisitor Renquest] says: NullReferenceException was thrown from InflictDamage. This object will be destroyed.

A few seconds after that the lord vanished at 79% health remaining. We have not been able to find a way to make it respawn. Currently 137 destro sitting in Order's keep hoping the Keep Lord will reappear :)

**Comment by MaxHayman** [comment]
This should be fixed.
