### ISSUE TITLE
Apothecary materials used, skill increased but no potion made

### ISSUE THREAD

**Issue by shadrach03** [WarEmu/WarBugs#15598]
The last issue of not being able to use apothecary seems to be resolved after the patch, but now potions aren't reliably being produced in my bag when crafting.

I was crafting potions with lvl 1 bottles, lvl 25 str seeds and 2 level 25 resin.  

After skilling up to 50 i checked my bag and noticed that only the critical successes that produced a blue potion where in my bag with no other potions present.

I then tried with lvl 50 seeds and resins with a similar result.  Materials consumed, skill gains occurring but no potions being left in my bag.

The second time i stopped before getting a critical success so I didn't see if a blue potion would end up in my inventory.

**Comment by Natherul** [comment]
had my guildie just test and worked fine for him, please provide more information

**Comment by shadrach03** [comment]
![apoth bug 1](https://user-images.githubusercontent.com/59751410/73597924-3250fa00-44f7-11ea-8900-7dded9bdd9ca.png)
![apoth bug 2](https://user-images.githubusercontent.com/59751410/73597926-3715ae00-44f7-11ea-9744-1c4a541c1e84.png)


Just logged in to try it out again. starting with just 3 blue potions from testing earlier.

Added lvl 1 bottle, lvl 50 str seed, 2 lvl 50 resin, crafted until my log showed a critical success while gaining skills and using resources with each crafting attempt.

The only potion was another of the same blue str potion that was added to my inventory earlier during crafting. No other potions resulted or notifications of success or failure in the log.

**Comment by Natherul** [comment]
yes, this item does not currently exsist that you are trying to make, its been added on the next update. Though Each such occurrance needs to be fixed if there are more, meaning exact potion and materials needs to be checked. I will add code tomorrow to help with notifying what its attempting

**Comment by Natherul** [comment]
should have been fixed with the hotfix

**Comment by shadrach03** [comment]
It appears everything is working well now.  I managed to skill up apothecary to the 170's today from 31.

Thanks for looking into this.
