### ISSUE TITLE
WH/WE Mechanic isn't working properly

### ISSUE THREAD

**Issue by Haojun-Phalanx** [WarEmu/WarBugs#15592]
Some WH/WE abilities builds "combo points/bloodlust/accusation" even they are defended.
Normally combo builder abilities shouldn't give combo points if they are defended.

WH Test:
https://www.youtube.com/watch?v=7Jye8X5jBy4&feature=youtu.be

Fervor, Torment, Pistol Whip don't give Accusation but Razor Strike does.

WE Test:
https://www.youtube.com/watch?v=YY2z0K1DP44&feature=youtu.be
Agonizing Wounds, Envenomed Blade,  Slice builds but Black Lotus Blade doesn't.

**Comment by SilverWF** [comment]
Checked some old Live videos
https://youtu.be/EL6AC59p4QM?t=50 (several strikes got blocked)
https://youtu.be/6gdhaTzpg74?t=201 (Pistol Whip got parried and didn't give accusition)
https://youtu.be/rOMvmt9dyy8?t=27 (AW got parried)
Hao is right

**Comment by grunbag** [comment]
fixed with next patch
