### ISSUE TITLE
Noteworthy persons

### ISSUE THREAD

**Issue by vafra32** [WarEmu/WarBugs#15594]
**Expected behavior and actual behavior:**

Talking to Kathandris Skysiege in the shadowlands don't effect to Noteworthy persons
Same thinks for Seleis Soronil and Lord Vilkareth in Avelorn.

**Steps to reproduce the problem:**

Take the fly to the shadowlands
Talk to Kathandris Skysiege
There is no effect on Noteworthy persons. Kathandris Skysiege is not validate.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/60542803/73591946-25cba200-44f5-11ea-8a12-49ba2569197a.png)

**Comment by Lheana** [comment]
Thanks for the report, but next time please open one report per issue (like one for each NPC in this precise case).
It will be fixed with next patch.

**Comment by Natherul** [comment]
should be fixed with patch as of today
