### ISSUE TITLE
Stonewatch ATK / DEF Population Bugged.

### ISSUE THREAD

**Issue by Kaelang** [WarEmu/WarBugs#15600]
It seems there are too many defenders being allowed into forts currently. 

22:39 UK GMT - Stonewatch.

I've heard this happened on a previous for yesterday too.

![Capture](https://user-images.githubusercontent.com/60117106/73600093-a5805d80-4543-11ea-8afb-0a2b7e6e96b0.PNG)

**Comment by Natherul** [comment]
when this was reported we had some issues with forts not properly working at all. Thus causing the issues. Those changes should have been addressed and further addressed this coming patch. If the problem persist please report back and Ill reopen the ticket.
