### ISSUE TITLE
There are several lizards that do not respawn in KV

### ISSUE THREAD

**Issue by AngelSirodey** [WarEmu/WarBugs#15602]
Since the last patch, there are several lizards that do not reappear in the Kadrin Valley around 31166, 34195.

There are two here that do not respawn:
![Yummydooh_003](https://user-images.githubusercontent.com/31651569/73600158-c4cfb880-454c-11ea-80c8-38513508129e.jpg)

Here one;
![Yummydooh_004](https://user-images.githubusercontent.com/31651569/73600173-eaf55880-454c-11ea-866e-9d6f9704a02a.jpg)

And here anotherone: 
![Yummydooh_005](https://user-images.githubusercontent.com/31651569/73600180-fea0bf00-454c-11ea-8811-2555440f001d.jpg)

**Comment by Kabucoror** [comment]
for me they respawn all after ~2 min

**Comment by AngelSirodey** [comment]
Now the respawn of the lizards seems to be well. Probably it was something temporaly but there were some lizards that didn't appear por a long time that day. 
Thanks for the help and sorry for the inconvenience.
