### ISSUE TITLE
[FORT] [STONEWATCH] Zone influence bugged

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#15603]
**Expected behavior and actual behavior:**

Participating in Stonewatch should reward influence towards Dwarf T4 zone. It instead rewards influence for Chapter 19 dwarf. 

**Steps to reproduce the problem:**

Participate in Stonewatch as Order and complete it with contribution enough to get rewarded somehow.

**Testing Screenshots/Videos/Evidences (always needed):**

I wasn't fast enough with the confusion, sorry.

**Comment by Lheana** [comment]
This should have been fixed with patch of 22/02/2020.
