### ISSUE TITLE
Gold bag from Stonewatch Fortress attack had five Invader Footwraps in it

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#15607]
"You won this bag at 02-02-2020 5:25:08 UTC" from successfully attacking Stonewatch Fortress.
Bag: Gold
Career: Zealot

**Expected behaviour and actual behavior:**

Actual behaviour: when I opened my gold bag reward in it were were 5 entries for the same Invader Footwraps along with other items (no other Invader items).

Expected behaviour: Unsure. It shouldn't have an extra 4 duplicated items but I don't know if it was supposed to have a choice of 5 different Invader items for the Zealot or just the Footwraps in it.

**Steps to reproduce the problem:**

Win a gold bag on the Zealot in Stonewatch fortress.

**Testing Screenshots/Videos/Evidences (always needed):**

I thought I took a screenshot but it seems I forgot. Sorry :(

**Comment by Natherul** [comment]
should be fixed with patch as of today
