### ISSUE TITLE
WE: Fleet Footed cancels Elixir speed buff

### ISSUE THREAD

**Issue by desizt** [WarEmu/WarBugs#15606]
So Fleet Footed skill for Witch Elf, is to remove snares and roots.

If you use Fleet Footed when you have Elixir of Shadows movement speed buff, it also removes the speed buff(s), not just snares/roots.

Seems wrong.

Thanks.

**Comment by Ootootoo** [comment]
In live server all speed buffs toggle off when you used any skill. Seems to be the case here. Probably better to simply updated tooltips of the skills.

**Comment by Nekkbraka** [comment]
Try using Flee first and then Speed buff.. Works in Choppa.

**Comment by Ootootoo** [comment]
> Try using Flee first and then Speed buff.. Works in Choppa.

Well, that is a bug if they stack. You aren't supposed to have more than one speed buff at a given time.

**Comment by grunbag** [comment]
work as intended, use first snare immune before charge
