### ISSUE TITLE
no icon def

### ISSUE THREAD

**Issue by Esclade** [WarEmu/WarBugs#15605]
cant see certain items icons like shields for DoK and opressor,vanquisher currencies 
![64b826510a518c1d41daae1aefd22757](https://user-images.githubusercontent.com/60480134/73605236-badda200-45ac-11ea-9fdf-6fe857556f2e.png)

**Comment by Lheana** [comment]
Name of the items please.

**Comment by Esclade** [comment]
> Name of the items please.
Basically all the DoK shields such as bloodlord ward,
![4e54f230309a64ef71360dffb97232b3](https://user-images.githubusercontent.com/60480134/74821150-390fa780-5314-11ea-9a76-7b6c6c2b213b.png)

Vanquisher Pummelers
![fb89e52b83e820e532067be179cc4f96](https://user-images.githubusercontent.com/60480134/74820598-6019a980-5313-11ea-92b7-15cf720b680b.png)

Sentinel Pummelers
![senti](https://user-images.githubusercontent.com/60480134/74821461-b76c4980-5314-11ea-8ee3-8f8f4806c733.png)

Opressor and Vanquisher Tokens

**Comment by Lheana** [comment]
These item icons are correctly set:
![Anadok_016](https://user-images.githubusercontent.com/11537611/75074413-eee91a80-54fb-11ea-92fd-6dab0393b246.jpg)
This issue must be due to something that has not been correctly updated on your side.

**Comment by Esclade** [comment]
oke thank you
