### ISSUE TITLE
Battle at Logrin's Forge - Scenario Quest Bug.

### ISSUE THREAD

**Issue by Kaelang** [WarEmu/WarBugs#15608]
You should pick the quest up, then hand in at the respected city before being able to pick the quest up a second time. I've just managed to pick up the quest 3 times (on separate SCs) and hand 3 quests in to Kaige Mortem in Altdorf.

> I'm not sure if I can pick up multiple quests in the SC and turn in for a huge amount of emblems but I'll check next time I'm in the SC.

You can't. ^

 Currently I believe you can simply run multiple Logrin Forges and pick a new quest up each time, regardless of if you already have it completed, awaiting handin. 

**Steps to reproduce the problem:**

Go to Logrin's Forge, win the SC, do not hand the quest in, re-queue for Logrin's Forge and pick up a new quest. Return to city and hand in multiple turn-ins at once. 

![LORGRIN FORGE](https://user-images.githubusercontent.com/60117106/73609735-a27b8080-45c8-11ea-92fe-149201922b07.PNG)

**Comment by Kabucoror** [comment]
Did you pick them up during leveling? Because there are different quests for different level ranges.

**Comment by Kaelang** [comment]
> Did you pick them up during leveling? Because there are different quests for different level ranges.

Potentially, I hadn't handed them in for a while. I believe they have been picking between 28-33 however.
