### ISSUE TITLE
XP rewards in T2/T3 The Undercroft seem broken.

### ISSUE THREAD

**Issue by Kaelang** [WarEmu/WarBugs#15612]
**Expected behavior and actual behavior:**

The winning team should receive substantially more experience for a win. However, currently the losing team receives almost as much XP via the XP bonus.

You can test by joining a game, and losing. You can therefore farm this to level fast.
![xp broken](https://user-images.githubusercontent.com/60117106/73615729-885e9400-4602-11ea-9368-8a4c6fb40fbf.PNG)

**Comment by dalen** [comment]
Scenarios with similar end result scores gives loosing side around that level.

![Falinirya_013](https://user-images.githubusercontent.com/7400/73616432-91a42c80-4613-11ea-92be-86acb028f0ca.jpg)
