### ISSUE TITLE
IC Siege Stage 3: Order players unable to teleport through barrier to King Fight

### ISSUE THREAD

**Issue by Rubyeclipse-war** [WarEmu/WarBugs#15614]
**Expected behavior and actual behavior:**

**Expected Behavior**:  During I.C. City Siege, all Order players can teleport through the barrier to participate in the Stage 3 Fight against enemy champions/king.

**Actual Behavior:**
Only Order's 4 champions are teleported into the fight area. 

All other Order players unable to enter. Destro players are all able to enter normally. 

After being manually teleported by dev, Order players who die and release are still unable to enter again. 

**Steps to reproduce the problem:**
(Unsure on all details, but here is the Siege info leading up to): 
**IC Phase 1:** Order Won with 100% victory / all flags.
**IC Phase 2:** Order won again as Gormann arrived at the Gates. Other pair of champions (Volkmar and the destro champ) both still alive at the time.
**IC Phase 3:** Bug appeared immediately after Champions selected

**Testing Screenshots/Videos/Evidences (always needed):**
![IC Stage 3 Fight Bug 1](https://user-images.githubusercontent.com/60584990/73616052-84f7e800-45c3-11ea-94ce-5bbf5174c0e6.jpg)
![IC Stage 3 Fight Bug 2](https://user-images.githubusercontent.com/60584990/73616055-8cb78c80-45c3-11ea-870a-1df3cca81fd1.jpg)

_Thank you for looking into this! Was fun to fight in I.C. again after many years._

**Comment by MaxHayman** [comment]
Fixes and changes have happened since then. Please repost any further issues.
