### ISSUE TITLE
[Shaman] WAAAGH! 

### ISSUE THREAD

**Issue by Valfaras** [WarEmu/WarBugs#1561]
Hi, i start the alpha yesterday and I create a shaman.

The basic speciality of shaman "WAAAGH!" dont work. The waaagh meters increase but the casting speed bonus dont work.

For exemple, after 5 heal, the next offensive spell would be an instant spell but it dont work.

Thanks

**Comment by Evildoor** [comment]
Known problem, closing. https://github.com/WarEmu/WarBugs/issues/933
In fact, casting speed works, but there is a problem with client-server communication: for example, at 5 points your spell instantly hits (you can see damage/healing), but your character still does the casting animation, which you can interrupt by casting something else. Yes, it's clunky, but no better fix exists for now.
