### ISSUE TITLE
UI Progression Bars for BO's in The Undercroft don't update in real time.

### ISSUE THREAD

**Issue by Kaelang** [WarEmu/WarBugs#15613]
**Expected behavior and actual behavior:**

The bar should slowly run down and then go into neutral, then progress into your realm. However, the bar stays a solid colour, then turns neutral, then turns into your color. You can't track how close / far away you are from capping.

**Steps to reproduce the problem:**

Run over a BO in The Undercroft and look at progression made. (I'm Order for picture purpose)

![progression bar](https://user-images.githubusercontent.com/60117106/73615912-931a2880-4604-11ea-9100-7012cd2ecae0.PNG)

**Comment by dalen** [comment]
I tested this locally, and it worked as it should for me. But I have made some changes to related code here, so might be those changes that have fixed it. So will mark it as fix pending.

**Comment by Natherul** [comment]
should be fixed with patch as of today
