### ISSUE TITLE
- Added the tome unlocks for completing scenarios of each race. the unlock is BESTIARY unlock?

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#15619]
it's a bestiary unlock? something wrong?
![Thorbolt_478](https://user-images.githubusercontent.com/16274785/73616645-4c352e80-4616-11ea-83e2-dcff47d1493e.jpg)

**Comment by Natherul** [comment]
this is the correct behavior. If you look in your tome you will see that the SC unlocks are under the races in bestially.
