### ISSUE TITLE
IC citysiege Attack feedback 02-02-2020

### ISSUE THREAD

**Issue by BomblingTV** [WarEmu/WarBugs#15618]
Alrighty then,

Rallybottom to get from Caledor to The Maw: Worked
Leader of a 18man warband queuing up at portal in The Maw: Worked.
Loading into the same instance: Worked.

Now, what didnt work was the UI. I dont have VinyUI and a very default customade UI with light elements and havnt had issues with this UI for previous IC + Altdorf tests. But same issue as I reported from a guildie on my last citysiege feedback on here.
Footage of showing the issue: https://clips.twitch.tv/CorrectPatientRadishGrammarKing

Stage1 mechanics went fine, attacking realm could attack NPCs, use portals to flank center Battleobjective, they flipped blue as they should and we eventually destroyed the gate to win stage1.
Dieing and respawning using the banners during this stage worked, and so did the Granted Ability Rally to get back in the Safezone for preparation time.

Stage2: One or several NPC lords did make some loops on their pathing but did overall take the correct paths and did end up reaching the gate and destroy it for attackers to win the stage.
https://clips.twitch.tv/IntelligentMistyYogurtResidentSleeper

Middle Battleobjective3 didnt flip from Red to Blue after the attacking two lords succesfully bypassed it and went on their pathing further towards the remaining BOs and the gate eventually: https://clips.twitch.tv/SarcasticLachrymosePepperSSSsss

Stage3: While in preparation from stage2 to stage3. A few defenders found their way into the attackers Preparation room, not sure if this was on purpose, something they had to do to get into their own preproom or what the backstory was:
https://clips.twitch.tv/AssiduousRudeMushroomRaccAttack

Stage3 begun, Champeonroles assigned and 3-4 Attackers got automatically ported outside to the Throneroom while the rest of the attackers didnt get automatically ported or could click on the portal (thanks Max for helping us one by one):
https://clips.twitch.tv/EndearingLivelyYakinikuAsianGlow

Stage3 damageoutput, healing etc seemed normal but I didnt check it too much in depth, nothing seemed outrageous. Champions dealt normal damage to small players and additional damage to Enemy Champions. King could be attacked correctly after 4 Defending champs were killed and the stage ended in attacking-realm victory. Also no granted abilities were spotted on the Champions during stage3 (good imo)

No renown tick was awarded uppon killing enemy NPC lords, or on stage completion. (20k renown per lord kill on Live)

The whole footage from when IC was opened up can be found over here if you need more information: https://www.twitch.tv/videos/545894438?t=01h12m36s

**Comment by dalen** [comment]
I think everything here is fixed now or fixed in todays patch.
