### ISSUE TITLE
Kind of a big one

### ISSUE THREAD

**Issue by KenniFrem** [WarEmu/WarBugs#15621]
Hi team the bug im reporting is as follows, if you as a shadowwarrior switches from one stance to assultstance. you are then able to switch your gear to something that contains strengh, and you will be able to keep your balistic stats that were trandformed into strengh PLUS the new strengh stats i cant emagine that this is intended Kindly Regards

**Comment by raptrr** [comment]
Can you provide some screenshots with the .getstats command? Did you check char screen stats only?

**Comment by raptrr** [comment]
No further information, closing this issue.
