### ISSUE TITLE
I will show you how to avoid death in battle without a client crash.

### ISSUE THREAD

**Issue by Tonych1981** [WarEmu/WarBugs#15628]
Hey!
I will show you how to avoid death in battle without a client crash.
https://youtu.be/vSpsymyzoSw
The video shows that you can leave your guild in battle. Then you spoil the capital, thereby avoiding death. There is a player who used this bug, made a separate video for him.

**Comment by Natherul** [comment]
should be fixed with patch as of today

**Comment by Tonych1981** [comment]
ok, thx!
