### ISSUE TITLE
Fell Landing: able to re-enter fortress after fleeing jail

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#15624]
4th February 2020 at 05:45-ish UTC.

**Expected behavior and actual behavior:**

I ended up in the fortress chail for Fell Landing (destro defend this one). I used by book of binding to flee the jail. However, I was then able to reenter the fortress zone by coming in via Caledor. A message was logged in chat saying "Since you fled from this fort prior you cannot participate in this fortress" however I was not teleported out of the fortress. I ran past the order camp by hugging the mountains and ended up easily getting back into the fortress.

I don't know if it teleports you out if you try to enter from the back of Fell Landing but it seems the forced teleport is missing if you cross the border from Caledor to Fell Landing.

I didn't get any Invader rewards but my contribution pre-death was so low (arrived during stage 3 and spent most of it dead just outside of LOS for a res) I wouldn't expect it anyway.

**Steps to reproduce the problem:**

1) Fell Landing defense as destruction
2) Get to stage 3
3) die and release so you end up in jail
4) Use book to escape jail
5) Use a flight master and travel to Caledor
6) Run from the Caledor warcamp through the RvR lake to the Fell Landing fortress zone while stage 3 is still active
7) See the message in chat: "Since you fled from this fort prior you cannot participate in this fortress" but you won't be teleported
8) Keep running back into the fortress

**Testing Screenshots/Videos/Evidences (always needed):**

Screenshot was taken after the fortress had ended but it shows the system message received. I was still in Fell Landing. I crossed the border when stage 3 still had some time remaining on it.

![Zomega_034](https://user-images.githubusercontent.com/60266177/73718198-c4cde500-4713-11ea-811d-93e08e99323b.jpg)

**Comment by Natherul** [comment]
should be fixed with patch as of today
