### ISSUE TITLE
No reward and strange reservation pop up

### ISSUE THREAD

**Issue by hellc95** [WarEmu/WarBugs#15627]
Last night I was in wb and we locked Black Crag. I assumed you needed to be 40/40 to enter forts so I ported out after lock. I was then told you can enter at any level (I was 30/31 maybe) so I went there. Stage 1 had just finished, and as soon as I walked in the reservation popped up (it didn't previously, I just assumed I had one since we locked the zone and there were less than 50 people at the time). After 5 minutes a pop up informed me that my reservation had expired, while I was in the fort, and when we won I recived no reward at all (no roll, no exp, no renown). So, I assume the system wasn't able to understand I entered the fort in time? Or I hadn't any reservation to begin with and it was given to me because not enough people were there? Ofc I'm not asking for rewards, it was satisfactory enough to kick some orchish ass, but I looked and din't find any similar bug reported. Hope this is useful, gl

**Comment by zoso85** [comment]
Same thing happened to me it asks you in chat to submit a bug report explaining how you entered.
Well today i was in a WB waiting for zone to lock with the rest of the WB on the border of CW and Maw, when everyone got disconnected. After relogging and entering the Maw,  i got the reservation message, and later the reservation has expired message nothing else. At every BO capture i was getting the error message something about cannot calculate contributions  ??.  I also died 4 times in stage 3  thinking i was going to get ported to jail, only to find that i was ported to the Maw campsite able to re-enter.  I also did not get any renown or XP and loot. this has happened quite a few times the end result being the same.

**Comment by dalen** [comment]
This should be fixed in the  latest patch (from 2020-02-15). Please open a new ticket if you can still reproduce this.
