### ISSUE TITLE
Guild Warped Standard Won't Deploy

### ISSUE THREAD

**Issue by Kruelistik** [WarEmu/WarBugs#15626]
Our guild is rank 14 and is experiencing issues when trying to deploy the warped battle standard. Haven't been able to use our standard at all yet due to an error saying our guild hasn't advanced enough to access the standard. Please advise!
![20200203_002922](https://user-images.githubusercontent.com/59073711/73752308-b6d98d80-472e-11ea-8b40-870778251c52.jpg)

**Comment by MaxHayman** [comment]
This should be fixed. Please reopen if not.
