### ISSUE TITLE
Guild Heraldry Issue

### ISSUE THREAD

**Issue by Kruelistik** [WarEmu/WarBugs#15625]
When I chose the heraldry for my guild Unsainted it didn't take, after a re-log, I tried again and only the pattern and colour took but not the emblem. I re-logged again and even spent the 100g trying to get the heraldry to implement. Still after many tries I can't get the emblem I choose to stay. Please advise/fix and maybe reimburse :D

**Comment by Kaelang** [comment]
Duplicate of https://github.com/WarEmu/WarBugs/issues/9791.
