### ISSUE TITLE
fell landing no contribution 

### ISSUE THREAD

**Issue by Bregual** [WarEmu/WarBugs#15623]
each time i participate in capping a fortress flag i receive a message telling me there was an issue applying contribution to my character and to report the incident to bug tracker. at the end of the fort i also received no rewards or exp. the issue has taken place in 2 separate forts now.

**Comment by Bregual** [comment]
looked and didn't see another instance of this issue sorry if i missed one

**Comment by Natherul** [comment]
same as https://github.com/WarEmu/WarBugs/issues/15199
