### ISSUE TITLE
Hammer of the Sentinel - Stat bug

### ISSUE THREAD

**Issue by Antalor** [WarEmu/WarBugs#15630]
Hey.
Hammer of the Sentinel for Dwarfs grants Willpower which is obviously a bug! :)
![senti_hammer](https://user-images.githubusercontent.com/13917674/73981776-4a7bab80-4933-11ea-8fde-dd8894965eae.png)

Greetings!

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by Natherul** [comment]
should be fixed with patch as of today
