### ISSUE TITLE
[WL] Trained to hunt proc : wrong debuff icon

### ISSUE THREAD

**Issue by CrimsonFenris** [WarEmu/WarBugs#15633]
**Expected behavior and actual behavior:**
Trained to Hunt "Stance" got a damage proc (tick of 3s) ; this proc is displaying the icon of "trained to Threaten" (a roaring lion) instead of matching trained to hunt icon (an camouflaged lion), wich can be a bit confusing especially since glowing border on active training is often buggy (When changing Training, both appear to be active).

**Steps to reproduce the problem:**
Use "Trained to Hunt" stance and watch proc on target.

**Testing Screenshots/Videos/Evidences (always needed):**
![Fenryon_004](https://user-images.githubusercontent.com/40425011/74075226-b46a8280-4a11-11ea-99fb-223f88ee6ce0.jpg)

**Comment by grunbag** [comment]
Fixed already
