### ISSUE TITLE
Curative Genesis set missing set bonuses

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#15638]
**Expected behavior and actual behavior:**

Since the patch that added the city sieges, the Curative Genesis set has lost it's set bonuses. I've confirmed via .getstats as well.

Other Genesis sets unchecked.

**Steps to reproduce the problem:**

Look at and/or equip the Curative Genesis set on a healer.

**Testing Screenshots/Videos/Evidences (always needed):**

![Zomega_051](https://user-images.githubusercontent.com/60266177/74090193-8aac6c80-4aa0-11ea-9270-bf34208f1497.jpg)

**Comment by wargrimnir** [comment]
fixed live
