### ISSUE TITLE
Zealot: Fatemaker Sovereign set missing all set bonuses

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#15637]
**Expected behavior and actual behavior:**

When viewing the items in the Fatemaker Sovereign set at the merchant, no set bonuses are displayed for any of the items. This is in contrast to the Fatewalker set which shows the bonuses.

**Steps to reproduce the problem:**

Look at the items at the merchant in the citadel.

**Testing Screenshots/Videos/Evidences (always needed):**

![Zomega_050](https://user-images.githubusercontent.com/60266177/74090067-86cc1a80-4a9f-11ea-83cc-6e644d5bbd75.jpg)

**Comment by wargrimnir** [comment]
fixed live
