### ISSUE TITLE
Armor on T1 & T3 Scenario Weapons

### ISSUE THREAD

**Issue by Culdu** [WarEmu/WarBugs#1563]
Several (can't try all) SC Weapons have armor on it, that just completly kills class balance, pls remove that soon.

**Comment by Evildoor** [comment]
I thought the armor was removed. Maybe some weapons were overlooked... And maybe the fix is on the dev server, but not on live yet. I'll ask the database team to take a look.

**Comment by Reggaewaldo** [comment]
This has been fixed in ticket #1502 and will carry over to the live server with next fix.
Thanks for reporting again.

Closing.
