### ISSUE TITLE
Ranked Scenario can't Tag

### ISSUE THREAD

**Issue by zageen** [WarEmu/WarBugs#15642]
**Expected behavior and actual behavior:**

As the title say, can't tag.

**Steps to reproduce the problem:**

No real Steps , tried many thing , forced update again , switch gear , tried with other eligible char ( doesn't work too), Worked perfectly fine some day ago.
Got no error message, no system message , all channel on

**Testing Screenshots/Videos/Evidences (always needed):**

Link to the différents char :

https://www.returnofreckoning.com/armory/character/495078
https://www.returnofreckoning.com/armory/character/496154
https://www.returnofreckoning.com/armory/character/795748

**Comment by zageen** [comment]
Update : tried on another computer , can't tag...

**Comment by SecretsOTheP** [comment]
Not sure what 'tag' is.

Do you mean queuing?

**Comment by zageen** [comment]
Yes, queing , i tried more things today actually: 
-get a 1500+ standard sc mmr 
-do more than 10 sec

Still cant queue

**Comment by zageen** [comment]
Dunno what you did , i changed nothing , but i can queue again. 
FIXED , thanks !
