### ISSUE TITLE
+15 critical damage taken on some warlord and sovereign sets

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#15649]
Some Warlord and Sovereign sets have +15 critical damage taken.
Pretty sure, it must be -15 critical damage taken
This 'bonus' at Sovereign set for Warrior Priest and Warlord set for Runepriest and Archmage

**Testing Screenshots/Videos/Evidences (always needed):**

![2020 02 09-14 09](https://user-images.githubusercontent.com/16439840/74101431-bdab3a80-4b4a-11ea-8473-792e9ecfdceb.jpg)
![2020 02 09-14 30](https://user-images.githubusercontent.com/16439840/74101436-c56adf00-4b4a-11ea-97f5-382dbaa69d3b.jpg)

**Comment by Lheana** [comment]
This has been fixed with the patch of 21/03/2020.
