### ISSUE TITLE
Won gold bag as Witch Elf in first live city - Defensive Set was only option in bag

### ISSUE THREAD

**Issue by Kymix21** [WarEmu/WarBugs#15646]
Won gold bag as Witch Elf in first live city on the server. When I won gold bag, my only option to choose from, as a Witch Elf, was the defensive set Sovereign Belt.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by keunglh** [comment]
I'm pretty sure that's intended - it's RNG drop

**Comment by dalen** [comment]
It randomizes between the three sets or gives the option to take crests instead.
