### ISSUE TITLE
Getting send out of fort

### ISSUE THREAD

**Issue by Daemon89** [WarEmu/WarBugs#15644]
After farm tru zones whole night we finaly gotten to elven fort last night.
i was i all the zone fight with keep lord and transporting boxes.....
I at first didnt get any reservations, but after walking into he zone i got in for some reason...
After about 30 seconds after the gates where down i got my message that i got a reservation for 5 minutes etc... (witch was strange because i alrdy was in the fort)

After standing next to some flags and trying to get some kills the systeem give me a message with:
Something has gone wrong when trying to add contribution to you.

After i got this message 2 times i suddenly got teleported out of the fort into etaine...
not being able to get back in....
not getting my 6 invader emblems for winning...

i really hope you guys can fix this issue, didnt make sence at all, and i missed out on Loot, RR And invader emlems ....

Greetings Deamon, Magus 

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by dalen** [comment]
This should be fixed in the  latest patch (from 2020-02-15). Please open a new ticket if you can still reproduce this.
