### ISSUE TITLE
Didn't Receive Gold Bags in City Stage 3

### ISSUE THREAD

**Issue by Tankbeardz** [WarEmu/WarBugs#15645]
Abrupt and I did not receive our bags for stage 3.  We couldn't loot the chest and we received no mail.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Stage3](https://user-images.githubusercontent.com/60835681/74096810-96645700-4ad1-11ea-9c7e-7a7dee7361ed.jpg)

**Comment by Fngar** [comment]
Same Issue. If it helps with log tracking, I was on "Purpl" in Instance 1

**Comment by raptrr** [comment]
Maybe they get sent via mail after a server restart, can you come back to the ticket after a restart?

**Comment by Zunig** [comment]
My gold bag from s3 arrived after server restart but it does contain warlord set piece, not a sov. Im rr82.

**Comment by SecretsOTheP** [comment]
> 
> 
> My gold bag from s3 arrived after server restart but it does contain warlord set piece, not a sov. Im rr82.

You receive a random piece of (warlord, sov, alt sov) as per the description on the forums.

**Comment by Tankbeardz** [comment]
Yep it seems to have arrived now.  Thanks.
