### ISSUE TITLE
[WP] Warlord Cassock (Body) +4% Block

### ISSUE THREAD

**Issue by keunglh** [WarEmu/WarBugs#15640]
**Expected behavior and actual behavior:**
N/A

**Steps to reproduce the problem:**
N/A

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/14348489/74090932-32ad4000-4a77-11ea-88d8-f409ec562fb8.png)

**Comment by RoR-Zomega** [comment]
What's the issue with it? Warrior Priests can take shields now.

**Comment by keunglh** [comment]
2H DPS set shouldn't need block. Alternate sovereign is the melee heal set for WP

**Comment by admaska2** [comment]
http://returnofreckoning.com/forum/viewtopic.php?f=8&t=35185&p=389831#p389831

I personally think the bonus set on the warlord should be on the Sovereign gear! And the Sovereign bonus sets on the Warlord gear.

I see a lot of defensive stats On the Warlord so Could be a shield spec, and a lot of offensive stats on the sovereign 

So I personally think the bonus set on the warlord should be on the Sovereign gear! And the Sovereign bonus sets on the Warlord gear.

**Comment by admaska2** [comment]
![Dps spec dok](https://user-images.githubusercontent.com/43276959/74200234-aa8d8d00-4c66-11ea-95c4-bc9843ab96c5.png)

As you can see in the Sovereign Gear a lot a dps stats STR Main a lot of crits so it could be for Dps dok not for Shield spec

![warlord](https://user-images.githubusercontent.com/43276959/74200819-3bb13380-4c68-11ea-843c-29ce5557d4d5.png)

In the second screen as you can see warlord have full defensive stats ! Tougness is main here with a lot of crit armor reduction so definitively the warlord gear is shield spec 

So mistake is just about the bonus of the gear the bonus set on the warlord should be on the Sovereign gear! And the Sovereign bonus sets on the Warlord gear.

**Comment by admaska2** [comment]
How soon can we expect a change Wargrimnir, on this Sovereign and Warlord sets for the dok ?
