### ISSUE TITLE
Warpriest Sovereign Set from Live with screenshot

### ISSUE THREAD

**Issue by Fiirkraag** [WarEmu/WarBugs#15650]
Good time of year.

Real Warpriest sovereign set bonuses from live screenshot:
1) +85 willpower
2) +85 wounds
3) +5% crit heal chance
4) 10% chance to get +130 heal power for 10s from heal
5) 10% chance to get +60 career resourses in 3s  from heal 
6) Absolute preservation. Granted skill for 10s with 1 min cooldown, making your party immune to crit attacks.

And set jewelry giving +2 c.r. in sec.

![WP sovereign](https://user-images.githubusercontent.com/58671836/74102007-51880100-4b61-11ea-84aa-8ee3916f61fa.jpg)

**Comment by dalen** [comment]
Sets are not the same as on live. Conq or invader aren't the same either.
