### ISSUE TITLE
Currentfort, entering circumstances

### ISSUE THREAD

**Issue by andrasragany** [WarEmu/WarBugs#15657]
My reservation expired like 30 sec before reached fort, tried to go in several times, and the 5-6th succeded.
![image](https://user-images.githubusercontent.com/39407087/74112605-6636ba00-4b9e-11ea-9382-d04cfdd23b95.png)

**Comment by andrasragany** [comment]
Character: Bicska

**Comment by Natherul** [comment]
probably solved this case for next patch

**Comment by Natherul** [comment]
Should have been fixed with the patch from yesterday
