### ISSUE TITLE
Empire Quest "Amber Blossom" bugged

### ISSUE THREAD

**Issue by Haulvarn** [WarEmu/WarBugs#15651]
Apparently the quest Amber Blossom is bugged, since the flowers you're supposed to pick simply aren't there.

I requested the help of 2 more experienced players than myself, and they verified that the location I was in was correct, but the Flowers weren't there. To make sure they hadn't just been picked by other players I waited in the location for a considerable amount of time.
![image](https://user-images.githubusercontent.com/60846915/74103413-1fb86f80-4b4c-11ea-9ce4-07f353536855.png)

**Comment by Lheana** [comment]
This quest has been disabled few patches ago, like the flowers.
