### ISSUE TITLE
Gold bags in city sieges are empty 

### ISSUE THREAD

**Issue by DanskuL** [WarEmu/WarBugs#15659]
**Expected behavior and actual behavior:**
Winning a gold bag always yields a gear piece of sovereign/warlord.

Some of the gold bags are empty and contain only medallions 

**Steps to reproduce the problem:**
Enter a city siege and win a gold bag.

**Testing Screenshots/Videos/Evidences (always needed):**
https://cdn.discordapp.com/attachments/676387071002279948/676389349314658305/citysiegegoldbagroll.png

https://cdn.discordapp.com/attachments/676387071002279948/676389381636096000/citysiegegoldbagopening.png

Reported to me by the account philippn296 he/she provided extra information:

"so to the backstory of this bag, i was in city siege and got a gold bag in stage 1, a purple in stage 2 and a gold in stage 3 again ':D
in gold bag 1 i had a reward, sovereign cloak"

**Comment by RoR-Zomega** [comment]
As per the guide on https://www.returnofreckoning.com/forum/viewtopic.php?f=11&t=35164 the gold bags only contain loot if you won that stage. Did your friend win or lose stage 3? If they lost stage 3 then it's not a bug.

**Comment by DanskuL** [comment]
Waiting for further confirmation from other players that might have experienced the same issue

**Comment by Manatikik** [comment]
Happened to me on Order stage one on Fenryl; missing Sov Cloak

**Comment by noobwarrior** [comment]
same Problem..
![Relife_370](https://user-images.githubusercontent.com/53536809/75623636-36cb0a00-5bac-11ea-9df6-a1c43282e8c3.jpg)

**Comment by RoR-Zomega** [comment]
@noobwarrior All items have been removed from gold bags for the time being due to a bug in contribution.
