### ISSUE TITLE
[Zealot] Toggling Harbinger of Doom on/off affects DoTs/HoTs already cast

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#15656]
I'm not sure if this is a bug or working as intended. I'm reporting it anyway just so the correct behaviour can be logged.

**Expected behavior and actual behavior:**

If I cast a DoT with Harbinger of Doom turned off and then turn on Harbinger, the damage of the DoT ticking on the enemy increases due to the conversion of willpower to intel. I would expect the ticks of existing DoTs/HoTs to remain the same and only new casts to use the new stats. I'm not sure how this was handled on live and/or whether this is an implementation issue with RoR.

If I cast a DoT with Harbinger of Doom turned on and then turn it off, the ticks of the DoT I cast are lowered.

If I cast a HoT with Harbinger of Doom turned off then turn it on, the heal values become lower as willpower is turned into intel.

If I cast a HoT with Harbinger of Doom turned on and then turn it off the heal value increases.

All of the screenshots below are different ticks of the same cast.

**Steps to reproduce the problem:**

Cast DoT on target dummy or HoT on yourself / another player and then turn Harbinger on and off.

**Testing Screenshots/Videos/Evidences (always needed):**

[DOT] Demon Spittle: Harbinger on (193) then off (146) in the same cast:
![Zomega_053](https://user-images.githubusercontent.com/60266177/74108740-43dc7680-4b75-11ea-82ff-f2a02aea47bb.jpg)
![Zomega_054](https://user-images.githubusercontent.com/60266177/74108745-45a63a00-4b75-11ea-97a3-40b990284f02.jpg)

[DOT] Warp Reality: Harbinger on (212) and then off (142) in the same cast:
![Zomega_055](https://user-images.githubusercontent.com/60266177/74108757-666e8f80-4b75-11ea-8004-dea59fc7e85b.jpg)
![Zomega_056](https://user-images.githubusercontent.com/60266177/74108762-68d0e980-4b75-11ea-8dd8-f369bbdb6087.jpg)

[DOT] Tzeentch's Lash: Harbinger on (119) and off (91) in the same cast. This skill ticks quickly so it's all in one screenshot.
![Zomega_058](https://user-images.githubusercontent.com/60266177/74108784-91f17a00-4b75-11ea-9444-3b5cbadb8e57.jpg)

[HOT] Tzeentch's Cordial: Harbinger on (340) and off (410) in the same cast. Combat log used so all in one screenshot.
![Zomega_061](https://user-images.githubusercontent.com/60266177/74108827-c82ef980-4b75-11ea-8bba-24dca09ab96a.jpg)

[HOT] Leaping Alteration: Harbinger off (262) and on (223) in the same cast. Combat log used so all in one screenshot.
![Zomega_063](https://user-images.githubusercontent.com/60266177/74108847-eac11280-4b75-11ea-8db2-be4d00679246.jpg)

**Comment by SecretsOTheP** [comment]
Intentional.
