### ISSUE TITLE
Altdorf City Siege - Stage 1 Bug, Destro Won Instead of Order

### ISSUE THREAD

**Issue by keunglh** [WarEmu/WarBugs#15653]
**Expected behavior and actual behavior:**
In Altdorf 4, Stage 1 - Order won, however only received 1 Royal Crest. System message said that Destro won the fight.

**Steps to reproduce the problem:**
N/A

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/14348489/74105588-de609980-4b24-11ea-8c4d-d5800d0e1abd.png)

**Comment by MaxHayman** [comment]
Pushing live
