### ISSUE TITLE
Shadowlands Mirelen PQ bugged on stage III

### ISSUE THREAD

**Issue by centurionusa** [WarEmu/WarBugs#15655]
Killed Hero but the kill didn't register.  It still said kill Mirelen 0/1.  After the time of the stage ran out and then the reset timer the PQ was stuck on PQ status finished.

**Comment by Lheana** [comment]
The PQ works fine for me. Killing Lord Azurael completes the last stage.

**Comment by Lheana** [comment]
No answer, ticket closed.
