### ISSUE TITLE
[Zealot] Base dmg of Zealot skills lower than similar skills on other careers.

### ISSUE THREAD

**Issue by Kweedko** [WarEmu/WarBugs#15654]
Here some exaples:
Storm of Ravens with  932 int and 199.6 dmg bonus hits with SoR 622 dmg per tick(according to tooltip it's must did 3092 dmg  - so 4 ticks for 622 is  2448 that not near th tooltip(and this with +25% tact), not counting the "magic power" which not affects tooltip), while shammy - with 600 int strikes 800+ per tick whith Bunch of Waagh.
![image](https://user-images.githubusercontent.com/13465031/74106994-8e69ed00-4b8d-11ea-8d3c-989c68405caf.png)

Sourge hits 855 with 658 on tooltip -  at the same time similar skill on shammy Brain Busta hits 805(with 300 int differrece ) - it's about 120 raw dmg (300 int / 5 * 2 sec cast = 120 ) and with 25% tact it's a huge 150 dmg gap.
![image](https://user-images.githubusercontent.com/13465031/74107253-ca9e4d00-4b8f-11ea-8f5d-251237b7194d.png)

Tzeentch's lash is 222 per tick 888 total - acording the tooltip it's 765 base dmg, so with 25% tact it' sould be 956+("magic power" crumbs)
![image](https://user-images.githubusercontent.com/13465031/74107353-af800d00-4b90-11ea-9697-1d90be51cbb5.png)

Caotic Agitation 660(with +25% tact ) per tick and 510 on tooltip while Tzeench Frieshtom 630 raw and have a sanre effect.

Rite of Agony - 396 with 5 sec cd, while spammable Deamonic Lash  is 417+ with the same amount of int on magus.

**Comment by Kaelang** [comment]
You're comparing a healer, with hybrid DPS and pure DPS classes.

This belongs on the Suggestions & Feedback section of the forum.
