### ISSUE TITLE
Squig herder pet not working in duel

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#15667]
**Expected behavior and actual behavior:**
pressing attack button or using the short cut key for pet attack should work in duel i tested the pet attack on monster before duel and it was working fine but while in duel nothing works
i also tested all kind of pets all have the same issue 
and i tried changing the pet to all stances and nothing worked

**Steps to reproduce the problem:**

dueling 

**Testing Screenshots/Videos/Evidences (always needed):**

[Video](https://streamable.com/0h2mh)

**Comment by Kaelang** [comment]
The duel system has been reworked. Please re-open if issues persist in the new Garden zone.
