### ISSUE TITLE
Zealot: Unique appearance of Warlord gear is mostly Conqueror gear

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#15665]
**Expected behavior and actual behavior:**

According to wargrimnir in https://www.returnofreckoning.com/forum/viewtopic.php?f=11&t=35199 the Warlord and Sovereign equipment should all be unique appearances and not found on other equipment. However the screenshot of the Zealot in Warlord gear which can be found at the start of that thread matches Conqueror gear almost exactly. The belt is definitely different and I don't yet have the Conqueror help to check that but the shoulders, chest, gloves and boots are identical to the Warlord set.

**Steps to reproduce the problem:**

Eqiup Zealot Conqueror gear and then Warlord gear and compare the differences.

**Testing Screenshots/Videos/Evidences (always needed):**

Zealot warlord (from thread):

![](https://i.imgur.com/ZcvZyHb.jpg)

Zealot conq (my character, missing helm):

![Zomega_073](https://user-images.githubusercontent.com/60266177/74244339-2cb69980-4cd9-11ea-96d7-f023f9701602.jpg)

**Comment by Tesq** [comment]
i think it's meant this way, doomflayer + warpforged belt + sov back for warlord appereance , while main sov is sov from live and off sov is warporged from live

**Comment by RoR-Zomega** [comment]
Cosmetic appearances have all changed since this report so it's no longer applicable.
