### ISSUE TITLE
After stage 3 victory the loot chests are not interactable

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#15660]
**Expected behavior and actual behavior:**

In both sieges I've been in the loot chests after stage 3 have been impossible to loot from. I tested both of them (in both order and destro spawn)

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Lotharic_372](https://user-images.githubusercontent.com/7400/74147485-9f554580-4c03-11ea-908b-a39d5e793f63.jpg)

**Comment by Kaelang** [comment]
Stage 3 Victory boxes are now lootable.
