### ISSUE TITLE
Tank (Knight) 6pc is not proccing

### ISSUE THREAD

**Issue by synthrocker** [WarEmu/WarBugs#15668]
Knights 6pc invader is not proccing, 10% chance on block to heal for 500 and regen AP. I've blocked 1000s of times and it has not procced (Ive unequiped and requipped my armor as people have stated and nothing)

**Comment by CrimsonFenris** [comment]
Tested yesterday with my KotBS against multiple lv25 mobs ; the heal proc is working (not sure about 10% though, looks like less), couldnt test the AP regen (colliding with natural regen wich is fast) but guess it works too.

**Comment by Kaelang** [comment]
Procs are working - tested.
