### ISSUE TITLE
City siege bag

### ISSUE THREAD

**Issue by Dragothurch** [WarEmu/WarBugs#15661]
Hi !

Today doing my first city siege. I win green bags in all stage. I can loot the bag from 1st stage but 2nd and 3rd stage cant loot bag .Thx for answer nad/or repairing .

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by dalen** [comment]
Duplicate of https://github.com/WarEmu/WarBugs/issues/15660
