### ISSUE TITLE
Dire Shielding tactic [chosen][ability]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#15671]
tactic increase duration to 17 sec for bane shield but regarding working on others in 30 feet radius it will work on other aswell only if you have a def target tabbed alredy

ankward part is for friendly target seems work into 40-50 feet range instead 30 while for others is maybe less

if friendly target tab is more away than 40-50 feet he wont get buff but other around you will

edit: there was this shammy in ic where i was testing this, he called sceros dosent matter how many times i tried and how ..skill wont work on him so this is strange.

In wb it work consistently tough, but as said require to have a def target or it wont work on allies.

expected behaviour: raw per tactic tooltip, press bane shield should now buff you and all ppl in 30 feet

**Comment by grunbag** [comment]
fixed with next patch

**Comment by Lheana** [comment]
It should have been fixed with the patch of today.
