### ISSUE TITLE
Stonewatch fort glitched entry

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#15676]
**Expected behavior and actual behavior:**
As destro you don't have a reservation attacking Stonewatch fort so you get placed in the queue, you try to enter several times and it keeps teleporting you back.

You can moonwalk your way into the fort by holding S, the contribution system bugs out and ask you to report this on github so you do.

**Testing Screenshots/Videos/Evidences (always needed):**

![Whiteguilt_081](https://user-images.githubusercontent.com/36811878/74374992-d7b17b00-4ddf-11ea-9dc4-2d954f5e0be0.jpg)

**Comment by mousias** [comment]
Same happened to me without "moonwalk" i try sometimes to join in, there was a ganking wb outside so after respawn i joined in and in the end of stage 2 i got same message. 
Character name (Aesop)
![Clipboardxx](https://user-images.githubusercontent.com/23142740/74565132-33fbd280-4f79-11ea-9bad-4dc905158d62.jpg)

**Comment by dalen** [comment]
This should be fixed in the  latest patch (from 2020-02-15). Please open a new ticket if you can still reproduce this.
