### ISSUE TITLE
Mailbox: game sending incorrect number of unread messages to client (new issue)

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#15674]
**Expected behavior and actual behavior:**

Disclaimer: I've only tested this with receiving 1 normal mail and 1 AH mail. I don't know how it behaves with higher numbers.

As of the reboot on 12th February 2020 the game now tells the client that it has both normal mail and AH mail unread whenever one of those is received. Example: if your mailbox is completely empty and you receive a normal piece of mail then it tells you that you have 1 normal mail and 1 auction house mail unread. Likewise if you receive 1 auction house mail when the mailbox was empty then the server is telling the client that you have one of each mail unread.

Once you read the actual mail you received a new notification is sent saying zero types of each mail are unread.

The good news is that the server now tells you when you have zero unread AH mails (previously it would send notifications for 1+ but not for when the final mail was read) so with a bit more testing it looks like the AH mail icon bug could now be fixed (#10440 #8263 #1109)

**Steps to reproduce the problem:**

1) Have a fully empty mailbox
2) Receive one mail in total from any source (have someone either mail you something, buy something from the AH or have one of your AH items bought)
3) Check the notification in chat about numbers of mail. It should say 1 normal mail and 1 AH mail are unread
4) Open the mail you received
5) Check the new notification in chat

**Testing Screenshots/Videos/Evidences (always needed):**

I only noticed this was happening after the fact so screenshots are a bit bad. My mailbox was fully empty at the time and I sold something on the AH. I get notification through that I have 1 unread message in my general inbox and 1 unread in the auction mailbox. Upon opening the AH mail (there was no other mail) and taking the gold a new message comes through saying I now have zero unread in both.

![Zomega_074](https://user-images.githubusercontent.com/60266177/74349199-c9e20280-4dab-11ea-901c-47417825185a.jpg)

**Comment by dalen** [comment]
yes, it seems it is counting all mail as unread now and belonging to both categories. Will create a fix for it for next patch.

**Comment by Natherul** [comment]
Should have been fixed with the patch from yesterday
