### ISSUE TITLE
Cloak dye Bloodlord

### ISSUE THREAD

**Issue by karrik1978** [WarEmu/WarBugs#15672]
Good afternoon!
Faced such a problem:
it is impossible to dye the cloak from the set of the Bloodlord.
The screenshot shows (on the left) that after receiving the cloak, it was painted in the color of Order of the Gryphon Black. That is, the cloak could be painted. Currently, an attempt to repaint a cloak or remove a color completely leads to an error (on the right in the screenshot). We are seeing a clear mistake. Please take this moment into account and fix it in the nearest hotfixes.
Thank you for attention.
https://pastenow.ru/b3ecd5741fc85b3940de4dbb9cfe0182

**Comment by lilimx** [comment]
Hey,

could you reupload the picture?
