### ISSUE TITLE
Gates of Ekrund: It is possible to stand on top of middle flag (float way above map)

### ISSUE THREAD

**Issue by malexcauthen** [WarEmu/WarBugs#15670]
**Expected behavior and actual behavior:**
Just got done playing a Gates of Ekrund scenario. I punted a sorc off the top of a ledge and the sorc landed on top of the middle flag. It gave the appearance of floating in the air. As we did not have any range in this scenario, we were unable to kill the sorc until they moved off the top of the flag. 

**Steps to reproduce the problem:**
Would be pretty hard for players to reproduce this as you have to line the punt up perfectly off of the ledge. In order to reproduce this though you just need to move a character to the top of the flag.

**Testing Screenshots/Videos/Evidences (always needed):**
Screenshot taken from a ledge.
![Zakgrin_003](https://user-images.githubusercontent.com/55412017/74303610-197aec80-4d20-11ea-82c0-b563b3426a4a.jpg)

Screenshots from down below
![Zakgrin_006](https://user-images.githubusercontent.com/55412017/74303647-37e0e800-4d20-11ea-8a2c-0f6ff80db3bb.jpg)

![Zakgrin_004](https://user-images.githubusercontent.com/55412017/74303638-2f88ad00-4d20-11ea-83ce-e7c5a6d0ef53.jpg)

**Comment by Lheana** [comment]
I see no real issue here: You can punt someone on the flag.

**Comment by malexcauthen** [comment]
I see it as a bug that likely isn't a high priority and will not happen often. The player can stay up there as long as they like and are actually unkillable if you do not have a ranged class on your team which was the case in this scenario. Not to mention having a sorc in a place that can't be reached is devastating. It also meant that is was impossible to take the middle flag after the eventually captured it haha...
