### ISSUE TITLE
DoK Sovereign Armor Sets have the wrong stats on them for DPS/Heal/Def Shield builds.

### ISSUE THREAD

**Issue by MeJenniV92** [WarEmu/WarBugs#15678]
**Expected behavior and actual behavior:**

The set bonuses are mixed up on the different Sovereign sets. I'm aware Someone posted a detailed information on the forums and on another github post, but it was under another class (Warrior Priest). So I'm posting it here in its proper place in the proper thread title just incase it wasn't seen:

**_Credit goes to admaska2:_**

As you can see, the Sovereign gear has a lot of dps stats "For example, STR is the main stat", a lot of crits etc ... So, the Sovereign gears are made for the DPS spec. In other words, the bonuses sets are wrong:

![title1](https://user-images.githubusercontent.com/60991375/74388160-c431f000-4d9e-11ea-9abc-6205c99537d7.jpg)

In the second screen, you can see Warlord gear has full defensive stats! "For instance, Toughness is the main stat", with a lot of crit/armor reduction %block, so definitively the Warlord gears are made for the Shield spec, the bonuses sets are wrong to:

![title2](https://user-images.githubusercontent.com/60991375/74388199-e4fa4580-4d9e-11ea-8e73-611425b4ed20.jpg)

So, it's just about the bonuses set of the gear; the bonuses set on the Warlord should be on the Sovereign gear! And the Sovereign bonuses set on the Warlord gear.

(In addition, the +16 willpower on the Warlord ring seems wrong too).

**Comment by dalen** [comment]
The off spec sovereign set is the melee heal set, and block has already been moved there. Warlord is the DPS set.

The 7pc bonuses are still mixed up between the sets though.
