### ISSUE TITLE
Bug/Eploit City Stage 2

### ISSUE THREAD

**Issue by tomaslumba** [WarEmu/WarBugs#15684]
Dessy were able to hurt our NPC Champs before Stage 2 began and it didn't reset, so S2 began with one champ beeing 45% in Health and the other one at 91%.

Pls make them reset when stage 2 Begins.

Kind regards.
![Karlbathos_007](https://user-images.githubusercontent.com/17112647/74522221-15ff8500-4f1b-11ea-87a9-599002248c0f.jpg)

**Comment by Choppabully** [comment]
I can confirm this is happening all the time, usually destro can aoe the champs near to red barrier and they can also pull through barrier.
![Gdragonn_062](https://user-images.githubusercontent.com/59963650/74577931-784b9a80-4f9a-11ea-8fff-dfbb3c706a67.jpg)

**Comment by Choppabully** [comment]
![Gdragonn_054](https://user-images.githubusercontent.com/59963650/74577950-8dc0c480-4f9a-11ea-9383-8c132e657692.jpg)

**Comment by Ootootoo** [comment]
![Marajade_025](https://user-images.githubusercontent.com/50114048/74578064-5f3aed80-4f8a-11ea-9fcd-3d95c58fe17e.jpg)

**Comment by Ootootoo** [comment]
also i have screenshots with several very well known forum names that more than likely have read this issue and abused it. I don't want to name shame, but i can give the screenshots with the scoreboards as a prove if required.

**Comment by keunglh** [comment]
![destro killing champ](https://user-images.githubusercontent.com/14348489/74587963-36345000-4fbe-11ea-99af-c50c866df497.PNG)
![destro killing champ 2](https://user-images.githubusercontent.com/14348489/74587966-37fe1380-4fbe-11ea-9919-266395edb5ea.PNG)

I was told to include a screenshot of the scoreboards.

**Comment by Natherul** [comment]
Should have been fixed with the patch from yesterday
