### ISSUE TITLE
[Bastion Stairs] Using a pet to trigger the boss will make it bug out and remove its mechanics 

### ISSUE THREAD

**Issue by Choppabully** [WarEmu/WarBugs#15688]
**Expected behavior and actual behavior:**

Using a pet to trigger the boss on attacking it and then challenging the boss with tank should not remove the boss mechanics.

Summoning a pet and commanding it to attack the boss and after the pet dies, having a tank challenging the boss, will cause the boss to bug out and ignore its designed mechanics, making it to stop aoe or summon adds, etc.

**Steps to reproduce the problem:**

1. Get a career that can summon pets such as: Engineer for Turret pet and White Lion for Lion pet.
2. Get to the boss after clearing trash mobs and summon your pet.
3. Order the pet to attack the boss while running away from the boss at the same time, to avoid getting aggro after the pet dies.
4. When the pet gets killed by the boss, order main tank to challenge the boss and soon after jump on the boss with the rest of the party.
5. It can be noticed that the boss bugs out and stops spawning adds or doing aoe that would otherwise make it harder to kill and from this point onward, it's a DPS race to kill the boss and the boss is easier to kill.

(for example a boss that used aoe that could kill all the team in under 3 seconds now stops using aoe and is behaving like a simple mob)

**Testing Screenshots/Videos/Evidences (always needed):**

I didn't actually take a video of the bug (cause screenshots can't describe the issue well), but I have some chat logs from my team who reproduced this bug. Hope they help you understand the issue. 

In the screenshots, we were at the boss called Chorek the Unstoppable, from right wing. After using the steps to trigger the bug, the boss stopped summoning his dogs pets that would make him very hard to kill.

This bug occurs on 80% of the bosses from Bastion Stair, it doesn't work only on two of them.

![3](https://user-images.githubusercontent.com/59963650/74578753-2c4f2480-4f9f-11ea-9287-7d22b877268d.jpg)
![1](https://user-images.githubusercontent.com/59963650/74578754-2d805180-4f9f-11ea-982f-ee94b3d4cca8.jpg)
![2](https://user-images.githubusercontent.com/59963650/74578755-2e18e800-4f9f-11ea-9e2e-d956967e8184.jpg)

**Comment by dalen** [comment]
This bug was fixed
