### ISSUE TITLE
City siege - stage3 - 3 destru champions

### ISSUE THREAD

**Issue by indal-andal** [WarEmu/WarBugs#15685]
3-4 hours ago, Altdorf #6 , somehow we had 3 champions only:

chosen: thargrimm
WE: foxxof
dok: Elvasoul

After asking our renown rank in chat I (Mimons RR84 marauder) expected to be a champion but didnt happen.

I wasnt in any group or warband when i joined the instance, but i think most of us were solo too becouse we only had x3 2htanks 

I've tried checking manually the players renown rank in the armory and coudlnt find some players but at least 3-4 destru DPS were RR84.

pic: https://i.imgur.com/YmHTwcY.png
vid: https://www.youtube.com/watch?v=9biTZ4OwW6g

**Comment by Ootootoo** [comment]
AFAIK, renown rank has nothing to do with being a champ or not. AFAIK, only contribution to the city counts.

**Comment by MaxHayman** [comment]
Fixes and changes have happened since then. Please repost any further issues.
