### ISSUE TITLE
[Zealot] With changing the location Harbringer of Doom stops woking

### ISSUE THREAD

**Issue by Kweedko** [WarEmu/WarBugs#15694]
Steps:
Toggle on HoD got to SC or flight to other location - use skills - skills will do dmg = dmg without HoD on but HoD counted as Toggle on - as result you have to spend 20sec cd to reenable it.

**Comment by RoR-Zomega** [comment]
#15181

**Comment by raptrr** [comment]
As @RoR-Zomega already linked, so I'm gonna close this.
