### ISSUE TITLE
[SC] [Minor] Eternal Citadel throne off-center

### ISSUE THREAD

**Issue by bosli42** [WarEmu/WarBugs#15696]
The throne object in the Eternal Citadel scenario is off center,
Please move it, it's distracting once noticed.
![Zyv_170](https://user-images.githubusercontent.com/18313892/74590777-de273900-5011-11ea-957f-756bf1029448.jpg)

**Comment by wargrimnir** [comment]
Pretty sure that's intentional for specifically that reason.

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by Lheana** [comment]
This should be fixed with patch of 22/02/2020.
