### ISSUE TITLE
[WORLD] [ORVR] Caledor spot to go underground

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#15690]
**Expected behavior and actual behavior:**

In the spot linked you can bug yourself to enter the underground eire of Caledor. Haven't checked, but maybe you can attack from this spot, as I have died misteriously a couple times here with no enemies in sight.

**Steps to reproduce the problem:**

Move to the cliff from the upper bridge in Wrath's Resolve

**Testing Screenshots/Videos/Evidences (always needed):**
![Marajade_016](https://user-images.githubusercontent.com/50114048/74582332-54944e80-4fb2-11ea-9aef-1bd52a475c5e.jpg)
![Marajade_017](https://user-images.githubusercontent.com/50114048/74582333-56f6a880-4fb2-11ea-9887-28fedafe3a6d.jpg)
![Marajade_018](https://user-images.githubusercontent.com/50114048/74582335-59590280-4fb2-11ea-8c5c-d89770c230d5.jpg)
![Marajade_019](https://user-images.githubusercontent.com/50114048/74582336-5a8a2f80-4fb2-11ea-8576-39573791575d.jpg)

**Comment by Kabucoror** [comment]
Can you provide a video or a more detailed explenation, please, on which spot you bug into the wall. I can't reproduce it.

**Comment by Ootootoo** [comment]
> Can you provide a video or a more detailed explenation, please, on which spot you bug into the wall. I can't reproduce it.

Sadly my computer can't keep up with RoR and a video recorder.

In the natural bridge formed from a fallen stone that oversees the north passage from the east keep, Wraith's Resolve, just walk to the wall mounted and you will glitch to the position shown in the shots. The bridge that i speak of can only be accessed from inside the keep, slightly to the west of the end of the outter wall.

**Comment by Ootootoo** [comment]
The approximate entering location can be seen, from below, in the 1st screenshot. is that rock that can be seen at the right.

**Comment by Kabucoror** [comment]
I still can't manage to glitch into this wall. How reliant can you use this glitch?
