### ISSUE TITLE
Destro access BW College 

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15700]
**Expected behavior and actual behavior:**
When order barrier goes down in altdorf after king death in stage 3 city siege destro can run into portal which takes you to LIVE bw college. 

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![](https://cdn.discordapp.com/attachments/491424146241224705/678410942890901514/Meatballsub_012.jpg)

![](https://cdn.discordapp.com/attachments/491424146241224705/678410906987790347/Meatballsub_011.jpg)

![](https://cdn.discordapp.com/attachments/491424146241224705/678410967410802688/Meatballsub_013.jpg)

**Comment by MaxHayman** [comment]
Fixed
