### ISSUE TITLE
[HERO] [LAIR] [PVE] Silveroak missing respawn timer

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#15709]
**Expected behavior and actual behavior:**

Feel free to close this if this was only meant for Beastlord bosses: Seems that Silveroak doesn't have the timer on respawn that other Heros have. As u can see in the screenshots, seems like he has been dead for hours without a respawn.

**Steps to reproduce the problem:**

Check the body of Silveroak in his lair in Norsca.

**Testing Screenshots/Videos/Evidences (always needed):**
![Liruda_000](https://user-images.githubusercontent.com/50114048/74617298-5847e280-5124-11ea-8e66-84e23f83b937.jpg)

**Comment by Razielhell** [comment]
Apparently OP means that there must be a Respawn Timer Debuff by the time Lair Bosses die.

**Comment by Lheana** [comment]
Lair bosses don't respawn immediately nor within 30 min. A screenshot of Silveroak dead does not prove anything about him not respawning.

**Comment by Ootootoo** [comment]
I meant the timer that, in example Beastlord bosses, most heros have. Tried to be clear about it, sorry if i fail.

**Comment by Lheana** [comment]
Lair bosses are not meant to have this buff.
