### ISSUE TITLE
Lost item putting in talisman

### ISSUE THREAD

**Issue by Myrdothilore** [WarEmu/WarBugs#1570]
I had just sent over some shoulders for my zealot from my main that I bought from the AH
When I logged onto him, I tried to put a talisman in it and it never went in. T
Then I tried to exit the window and it wouldn't close.
I relogged and the window was still up.
When I hit escape the window closed and the item was gone. 
First pic when window wouldn't close initially.
https://www.dropbox.com/s/61e0az1a2iruqd4/Myrdothilore_002.jpg?dl=0
Me trying to hit escape button
https://www.dropbox.com/s/1ms4x7l6ueb9e29/Myrdothilore_003.jpg?dl=0
After relogging the window was still up and wouldn't close.
https://www.dropbox.com/s/1s7dm8ul670v8zb/Myrdothilore_004.jpg?dl=0
I hope that I can get this item back and that the bug will be fixed. ;) goodluck!

**Comment by Myrdothilore** [comment]
It's working now and I got the item back, after I exited the game completely and loading in, the window was still up so I added in a talisman and it clicked fuse and it gave me the item back with the talisman inside it. ;)

**Comment by Evildoor** [comment]
Known issue, "exiting the game completely" is exactly the way i recommend to deal with it for now. Surprisingly, i've not found any ticket describing this problem (in general, not incorrect particular ones), so i'll leave this one open.

**Comment by ArnauPrat** [comment]
I had the same problem with a renown scenario weapon. When reloged, the talisman window appeared. Just fuse the talisman and the item appeared again.

**Comment by Evildoor** [comment]
It seems that something was improved here. Now if the talisman window gets bugged, closing it returns the item to your inventory, so you can try again until it works, without exiting the game. Nice.

**Comment by Evildoor** [comment]
I suppose that this can be closed, have not run into problems in this regard for some time.
