### ISSUE TITLE
IC stage3 punts on champions

### ISSUE THREAD

**Issue by BomblingTV** [WarEmu/WarBugs#15707]
**Expected behavior and actual behavior:**
Useing punts/pushest to kill them with fall damage seems to be a thing for IC citysiege, but only in phase 1+2. Phase3 clearly have walls on the bridge to avoid Champions not getting killed by one ability.

**Steps to reproduce the problem:**
Having a class with longrange punt and push champion players over the cornerside of the bridge in IC throneroom, and let them die to fall damage and lose 1 champion for the objective based battle.

**Testing Screenshots/Videos/Evidences (always needed):**
https://www.twitch.tv/videos/553174022?t=00h41m23s
3 total punts were made on champions. Myself and it worked, later on towards the Magus and he bugged out and didnt lose his champion role and was stuck inside Destro defender barrier (Max dragged him out) and other order DPS-champ got punted to the side too later on.

**Comment by MaxHayman** [comment]
We changed collission in the throne room. Let me know if this is still an issue.
