### ISSUE TITLE
[SM] Haeven's Blade doesn't buff resistance only buff armor.

### ISSUE THREAD

**Issue by Kweedko** [WarEmu/WarBugs#15719]
subg 
according the tooltip - if u strike with resistance dmg(lots of skills on sm is "Spirit dmg") - you group buffed with rez buff - but it doesn't happen -  reproduced with spam of Enclousering Blow on mob.

**Comment by dalen** [comment]
It buffs you with resists if your target uses magic attacks, not if you do.

>You enchant your blade with the spirit of the heavens. Whenever you strike a target with a melee attack, there is a 25% chance that you will increase your group's defenses **against one of the damage types that your target uses**. For physical damage, your group's armor is increased by 618, and for resistance damage, that resistance is increased by 236. This effect persists for 10 seconds.

**Comment by Kweedko** [comment]
"Whenever you strike a target with a melee attack" you quoted it yourself  - whenever you strike - if it's a tooltip problem?

**Comment by dalen** [comment]
yes, whenever you strike it buffs defences *against one of the damage types that your target uses*.

Not based on the damage type you used. It is based on the damage type your target uses.

**Comment by Kweedko** [comment]
> yes, whenever you strike it buffs defences _against one of the damage types that your target uses_.
> 
> Not based on the damage type you used. It is based on the damage type your target uses.
Tooltip says otherwise

So if i hit SH it buffs corpreal cause SH uses Festering arrow, elemental cause of expodin' arrer and armor casue of other attacks?
