### ISSUE TITLE
Hastend Dismissal 2h and 1h weapons cd

### ISSUE THREAD

**Issue by AngryVaran** [WarEmu/WarBugs#15714]
Last month i have an issue with Hastend Dismissal tactic while wearing shield ad 1h weapon.
As i know, on RoR server this tactic isnt bound to 1h or 2h wepons. But cd of Repel with 2h weapon is correctly worked, while 1h repell still have 20 seconds cd with Hastend Dismissal tactic. Range of toss correctly worked with both types of weapons ( 1h and 2h).

Hastend Dismissal tactic shoud reduce cd of Repel wiht any weapons.

![Skane_148](https://user-images.githubusercontent.com/61160917/74678592-7a953b00-51cc-11ea-9d14-231dee7f4b55.jpg)
![Skane_149](https://user-images.githubusercontent.com/61160917/74678597-7cf79500-51cc-11ea-8a1a-f7f7146a8379.jpg)
![Skane_150](https://user-images.githubusercontent.com/61160917/74678598-7d902b80-51cc-11ea-8b8b-7304d8e4183a.jpg)
![Skane_151](https://user-images.githubusercontent.com/61160917/74678599-7d902b80-51cc-11ea-86c1-ecbb1769f861.jpg)
![Skane_152](https://user-images.githubusercontent.com/61160917/74678601-7e28c200-51cc-11ea-80c1-6b32935c702b.jpg)
![Skane_153](https://user-images.githubusercontent.com/61160917/74678602-7ec15880-51cc-11ea-970b-4461d8326437.jpg)
![Skane_154](https://user-images.githubusercontent.com/61160917/74678604-7ec15880-51cc-11ea-8e20-5b4007a81da2.jpg)

**Comment by Kabucoror** [comment]
It is working as intended only the tooltip is wrong. In RoR wearing a 2h weapon reduces the cd of your punt ability by 50%.

**Comment by AngryVaran** [comment]
> It is working as intended only the tooltip is wrong. In RoR wearing a 2h weapon reduces the cd of your punt ability by 50%.

No its not. I use this tactic in 24v24 Vll Legion and FMJ fight, in almost all forts and smallscale rvr for a four month before. I didnt see any patch note about this tactic before. If i'm wrong, please give me link to patchnotes when devs change this tactic.

**Comment by RoR-Zomega** [comment]
It changed in 2007 and is also listed in the Chosen changes on the Wiki.

Wiki: https://wiki.returnofreckoning.com/index.php/Chosen
Patch: https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=23117#p258569

**Comment by Tesq** [comment]
Sadly old patch note which any disagree with still as intended tought.
