### ISSUE TITLE
City Seige, Stage 3 Spawn Bug

### ISSUE THREAD

**Issue by wingedmedic** [WarEmu/WarBugs#15718]
Recent city seige, Altdorf, ran smooth. Stage 3, When destro died, they died again in spawn when their rez timer was up. Some members died multiple times in this fashion.

I cannot replicate it currently.

I did not take any pictures.

We were in altdorf 3

**Comment by RoR-Zomega** [comment]
I can confirm this happened to me too (same instance and faction - destro in Altdorf 3. To give a few more details of what had happened:

1) One of the order champions had been killed when the bug first hit (Bombling)
2) The time left on stage 3 was between 18-19 minutes
3) Resurrections worked fine, it was only if a player released and reappeared back in the spawn point did the bug happen.
4) Upon reappearing in spawn the player was instantly killed. I stupidly didn't check the combat log to see what triggered it. This forced them to sit out the entire respawn timer again (20+ seconds). We couldn't pick people up with res as the healers were either on the other side of the spawn barrier or caught in the same loop.

Unsurprisingly this led to a very quick loss as the majority of the warband was locked out for match for nearly a minute between the two respawn timers.

**Comment by dalen** [comment]
> when their rez timer was up

Do you mean the respawn timer? Not the 1 min timer from a ress?

**Comment by RoR-Zomega** [comment]
It's the respawn timer. I.e. the grey window comes up saying you're dead and you click release. A black box then appears with a countdown to when you will respawn.

When this countdown hit zero we were teleported to the respawn place (correct) and immediately killed again (bug). Like, one shot insta-dead. We then had a new grey window giving us the option to release followed by another black-box respawn countdown. Some people got stuck in this loop for a couple of times.

**Comment by BomblingTV** [comment]
Hello, in an attempt to help showing this bug. Or atleast confirm it, here is my stream VOD from the instance where this happend:
https://www.twitch.tv/videos/553883314?t=02h32m00s

From the linked  timestamp pay attention to the yellowish-Meleesquigherder on the ground respawning and count in your head 43 sec in before you see all of destro coming out of the respawn. Clearly if they had respawned when this corpse had disappeared from the ground and ASAP rushed to help their champion players under heavy attack they would had shown up to help assist their champs.

Hope this helps, sorry for the bug guys wish it wouldnt had happend.

**Comment by dalen** [comment]
https://clips.twitch.tv/SourCrypticKumquatNomNom

**Comment by RoR-Zomega** [comment]
The siege of Altdorf that occured at about 15:00 GMT has had a large number of reports in chat of this bug occuring. Each time it's the same setup: win stage 1 and 2, stage 3 happens in the palace, respawn bug occurs and causes a loss.

**Comment by dalen** [comment]
Has anyone checked what the combat log says when you get killed? Fall damage? Guard damage?

**Comment by MaxHayman** [comment]
This should be fixed please reopen if that is not the case.
