### ISSUE TITLE
[City Siege] IC Stage 1 gate dies in seconds

### ISSUE THREAD

**Issue by bosli42** [WarEmu/WarBugs#15712]
In the last IC siege, the destruction gate died apparently for no reason extremely quickly.

When we killed the cannoneers, the door was below 80%, then when order arrived shortly after, it was back up at 90% (we checked and were surprised that it healed for some reason). We fought order for not even two minutes, none of them attacked the door except a few AoE's, and it died. The sundragon could not be spawned, so the only thing hitting it was a new wave of cannoneers and very few AoE's. It seems like the stage was no longer defendable at this point, when it definitely should be.

It can be checked in Zunig's stream, at about 3:26:00 they engage us at the gate:
https://www.twitch.tv/videos/553092542?t=03h26m00s

**Comment by Tesq** [comment]
It happened in another istance 2 days ago. I dont know if order can attack it or it die like cannons were doing pre last fix when simply an ordet get close to it.

**Comment by dalen** [comment]
This is fixed now AFAIK
