### ISSUE TITLE
DoK Warlord 4th set bonus is blank

### ISSUE THREAD

**Issue by Esclade** [WarEmu/WarBugs#15727]
cant see any bonus not even a placeholder like " 1 willpower " 
![warlordi](https://user-images.githubusercontent.com/60480134/74823369-a5d87100-5317-11ea-9d8b-9f0879b24f44.png)

**Comment by wargrimnir** [comment]
This should be corrected already, please confirm.

**Comment by Esclade** [comment]
yes fixed thank you.
