### ISSUE TITLE
Bloodfist Rock Siege Merchant

### ISSUE THREAD

**Issue by colintgallagher** [WarEmu/WarBugs#15723]
Whenever Bloodfist Rock in Thunder Mountain is the Order keep, the siege merchant doesn't spawn in the outer wall main gate tower. I've checked multiple times, made sure a dps didn't kill him, ect. He's just never there. Or I'm just a blind idiot and he's somewhere else.

**Comment by Lheana** [comment]
This should have been fixed with patch of 22/02/2020.
