### ISSUE TITLE
Participating in fort siege without permition.

### ISSUE THREAD

**Issue by Kweedko** [WarEmu/WarBugs#15728]
You can climb the moutain in Shining Way and paticipate in for attack/defence
![image](https://user-images.githubusercontent.com/13465031/74852121-ff638e80-535d-11ea-8d12-dc9d7d393aec.png)
![image](https://user-images.githubusercontent.com/13465031/74852384-4e112880-535e-11ea-83d4-46e79ea3c768.png)

While invesigating i saw a lot of Order standing there - behind the  fort second wall, if they heal helped to kill trough the wall othe orders who battling for the fort they recive bags and contribution for the fort.(probably come throug portal)

That work for destro too - if you kill somebody in shining way zone it counts as participating in siege.

![image](https://user-images.githubusercontent.com/13465031/74852876-fde69600-535e-11ea-855b-0e327e4bc0f9.png)

**Comment by dalen** [comment]
Does this really let you participate though? It should just port you out, the same as if you passed into the fort across the zone border.

**Comment by Kweedko** [comment]
If u come from PVE zone without a reservation, whilst you don't come closer to fort walls u not be teleported, and yet u can still find a kill in zone(Order always hanging behind the fort) and paricipate in roll and rewards

**Comment by Kaelang** [comment]
The 27/05 patch has addressed some contribution issues / porting issues with forts. Please re-open if this is issue persists.
