### ISSUE TITLE
Minor: NPCs weird stances at West Praag

### ISSUE THREAD

**Issue by Aanathema** [WarEmu/WarBugs#15729]
**Expected behavior and actual behavior:**
NPCs should have a regular pose as the rest have,
The arms of the NPCs seems to be off.

**Steps to reproduce the problem:**
Go to the co-ordinates 50026 - 59463.

![Windrangerrr_007](https://user-images.githubusercontent.com/55383380/74856298-99214080-534a-11ea-8875-6cf7fa69c657.jpg)
![Windrangerrr_008](https://user-images.githubusercontent.com/55383380/74856338-a4746c00-534a-11ea-8a2c-1a99c8d4f4b6.jpg)

**Comment by Lheana** [comment]
This should have been fixed with patch of 22/02/2020.
