### ISSUE TITLE
Moving items between inventory/banker is not working

### ISSUE THREAD

**Issue by ropuch** [WarEmu/WarBugs#1572]
Title is self-explanatory: one needs to drag item to/from bank by hand, which is quite uncomfortable (because autostack-same-items not working, in case you're adding the same stackable item that already is in bank, you need to find it first and manually drag item to stack). I'd say it's Interface/Items Low Prio bug ;-)

**Comment by ropuch** [comment]
I'd say it's Interface/Items Low Prio bug ;-)

**Comment by Kushido** [comment]
back in days it works by right clicking on item in backpack and it moves to bank first free slot or filling already same item in bank as stack

**Comment by nalgol** [comment]
fix is on git
note trying to automove items from bank to backpack will not work client is not sending any packet if you do that
