### ISSUE TITLE
no contribution in fort

### ISSUE THREAD

**Issue by Gwelthaz** [WarEmu/WarBugs#15721]
got a message from server saying i had an issue in fort , and having no contribution and report it to bug tracker.. so here i am
Indeed twice, no RR , no medalions.
no idea why, i had RR, captured flags and participating in kills.

**Comment by avalus** [comment]
Did you have a reservation (the popup saying it lasts 5min showed up) or you forced your way in ?

**Comment by Gwelthaz** [comment]
i had reservation yes.

**Comment by raptrr** [comment]
Did it show any other server-sides message, like "failed to add contribution..."?

**Comment by Gwelthaz** [comment]
server said :
" Something has gone wrong when attempting to add contribution to you, please report on the bugtracker the circumstances of you entering the fort."

**Comment by dalen** [comment]
were you inside fort before it started?

**Comment by Gwelthaz** [comment]
i had reservation, went to the fort, but i died at the begining of the map by a destro gank team, and respawned in fort.

**Comment by Natherul** [comment]
same as https://github.com/WarEmu/WarBugs/issues/15199
