### ISSUE TITLE
Typo in "Gust of Apphire Haze" fragment

### ISSUE THREAD

**Issue by valkeera** [WarEmu/WarBugs#15737]
Purple lvl 100 fragment should've been probably named "Gust of Sapphire Haze".

![Nifelda_000](https://user-images.githubusercontent.com/58527250/74975914-1969a380-5428-11ea-9f43-715a70f697c8.jpg)

**Comment by Lheana** [comment]
It should have been fixed with the patch of 28/03/2020.
