### ISSUE TITLE
Thrallseekers PQ: Fallen Lion becomes unfallen

### ISSUE THREAD

**Issue by valkeera** [WarEmu/WarBugs#15738]
During stage 3 of the Thrallseekers PQ, some of the fallen White Lions suddenly rise to life, occasionally attacking nearby enemies.

![Caiquenil_012](https://user-images.githubusercontent.com/58527250/74976268-b593aa80-5428-11ea-849b-056744f025e8.jpg)

**Comment by Lheana** [comment]
These Lions will be invulnerable with next patch, which should prevent them from standing up. If they still do, then it's related to a general issue with emotes that are not always displayed.

**Comment by Lheana** [comment]
This should have been fixed with patch of 22/02/2020.

**Comment by valkeera** [comment]
I found a few more instances with White Lions standing up during stage 2 and stage 3 of this quest (whereas they were lying still during stage 1).

This guy near the slave pen got up at stage 2:
![Caiquenil_002](https://user-images.githubusercontent.com/58527250/75117136-1dd3cd80-566f-11ea-8716-157b2ffd95d6.jpg)


And these two at stage 3:
![Caiquenil_003](https://user-images.githubusercontent.com/58527250/75117140-21675480-566f-11ea-8d0e-a058bdbc11ed.jpg)

**Comment by Lheana** [comment]
"If they still do, then it's related to a general issue with emotes that are not always displayed."
