### ISSUE TITLE
Quest: Unholy - marker stays on map

### ISSUE THREAD

**Issue by Aanathema** [WarEmu/WarBugs#15730]
**Expected behavior and actual behavior:**
The marker where you should go for the quest remains on the map when you complete it before turning it in, when it should be replaced by the turn-in (only the turn in marker to be shown on map - not both at the same time as it is this case).

**Steps to reproduce the problem:**
Take quest and before turning it in, watch the map for the markers.

**Testing Screenshots/Videos/Evidences (always needed):**
![1](https://user-images.githubusercontent.com/55383380/74857815-eb636100-534c-11ea-80ac-3dfaf1d7de7d.jpg)
![2](https://user-images.githubusercontent.com/55383380/74857822-ee5e5180-534c-11ea-8a18-a5681cd693dd.jpg)

**Comment by Kaelang** [comment]
This should've been fixed with a recent patch.
