### ISSUE TITLE
[Chat] Guild Tax rate chat spam

### ISSUE THREAD

**Issue by CrimsonFenris** [WarEmu/WarBugs#15733]
I got this issue again, already fixed last year (https://github.com/WarEmu/WarBugs/issues/13576), but looks like reborn from its ashes...

I think this is related to changing zones and entering/exiting scenarios : each time we got ported to a new zone, chat display the guild tax rate, and in the end it clutters the chat like this :
![Fenrilyon_004](https://user-images.githubusercontent.com/40425011/74877719-32118500-5366-11ea-823c-f3be6e834289.jpg)

Of course it can be disabled in channels options, but it's a system notice and doing so will prevent important notices as well (like server restart and admins warnings).

**Comment by raptrr** [comment]
Reopening #13576 and closing this one.
