### ISSUE TITLE
Duplicate Precious flask in Elf chapter 1

### ISSUE THREAD

**Issue by valkeera** [WarEmu/WarBugs#15739]
The "Precious flask" for the Mysterious M.B quest is present in 2 places in Elf chapter 1.

![Caiquenil_002](https://user-images.githubusercontent.com/58527250/74976444-05727180-5429-11ea-8996-9f723e4c680f.jpg)

![Caiquenil_003](https://user-images.githubusercontent.com/58527250/74976464-0a372580-5429-11ea-81a9-4cbfe64c1018.jpg)

**Comment by Lheana** [comment]
On official these 2 spawns were also possible (see [here](url=https://web.archive.org/web/20130517145103/http://warhammeronline.wikia.com/wiki/Precious_Flask)). So I close this
