### ISSUE TITLE
Praag: Southern Garrison outer wall oil location still not fixed

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#15746]
**Expected behavior and actual behavior:**

Expected: as per the closure of #15675 the oil on the outer wall of the Southern Garrison keep in Praag should no longer have range/LOS issues. However after the patch destruction still have issues targetting the oil with 100ft abilities on order-owned zero-star keeps.

No other ranks tested and I don't know if it differs when order attack.

**Steps to reproduce the problem:**

1) Have Southern Garrison owned by order in the campaign
2) Spawn oil on outer walls
3) Attempt to hit it with 100ft abilities on a Sorcerer (those are the ones I saw jumping along with my Zealot).

**Testing Screenshots/Videos/Evidences (always needed):**

Same as in #15675.

**Comment by raptrr** [comment]
As mentioned, the linked one will be the open one
