### ISSUE TITLE
PQ dont work

### ISSUE THREAD

**Issue by panodill** [WarEmu/WarBugs#15758]
PQ dont work after reset of server around 21:00 servertime 2020-02-22

**Expected behavior and actual behavior:**
PQ dont count kills

**Steps to reproduce the problem:**
kill a mob in a pq

**Testing Screenshots/Videos/Evidences (always needed):**

https://i.imgur.com/ucQhQAB.jpg

**Comment by Lheana** [comment]
This should have been fixed with the patch of today.
