### ISSUE TITLE
Items lost in AH.

### ISSUE THREAD

**Issue by Tholkienn** [WarEmu/WarBugs#15751]
I have 4 items who appear in my AH selling list, but i can't cancel the auctions, and they not appear when i make a research on this specific item.

**Comment by raptrr** [comment]
Can you provide some screenshots of the items in the AH?

**Comment by Tholkienn** [comment]
Yes!
![1](https://user-images.githubusercontent.com/13720388/75468718-f1c98c80-598d-11ea-930f-8fa0445db341.png)
![2](https://user-images.githubusercontent.com/13720388/75468731-f8580400-598d-11ea-9b28-9307c1c73298.png)
You can see the name char, jthe price and the violet tali in auction list, and i don't appear in real ah list

**Comment by raptrr** [comment]
Can you right-click them to cancel?
Else you might have to wait a little bit longer until it runs out.

**Comment by Tholkienn** [comment]
I cant and you see on screen i have made a research on this item, he is not in sale.

**Comment by Kaelang** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/1103.
