### ISSUE TITLE
[Chosen] Seeping Wound will not critically hit

### ISSUE THREAD

**Issue by Killamanjaro** [WarEmu/WarBugs#15753]
**Expected behavior and actual behavior:**
Expected: Seeping Wounds should allow for a critical hit, that it doesn't is a bug.

Actual: Seeping Wounds will not critically hit (regardless of how many attempts on the target dummy, multiple Chosens). 

**Steps to reproduce the problem:**
Attack a target dummy (0 mitigation target) or any target.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/61355379/76029919-fc8aa100-5efa-11ea-8a3a-19ed61bf2c2e.png)

**Comment by Killamanjaro** [comment]
This ability total damage, when reduced by average toughness (~-50 damage) and magic mitigation (~25%) is only hitting a real target for ~900*.75-50 = 208 every 3 secs. 

Proof of crit on live,

![image](https://user-images.githubusercontent.com/61355379/76030874-2ee8ce00-5efc-11ea-88db-40aad2582189.png)

![image](https://user-images.githubusercontent.com/61355379/76030894-38723600-5efc-11ea-8235-e43c3786e16f.png)

**Comment by Killamanjaro** [comment]
The equivalent attack from KOTBS (Viscous Slash) applies an initial hit of damage, interrupts, and critically hits.

Thank you for your help.

**Comment by grunbag** [comment]
fixed with next patch. note that it could crit only on the dot part but the proc damage part will never crit .

**Comment by Lheana** [comment]
It should have been fixed with the patch of 28/03/2020.
