### ISSUE TITLE
pve quest bug

### ISSUE THREAD

**Issue by normanis** [WarEmu/WarBugs#15754]
pve quests dont show up if i have dungeon quests up
![Kulls_002](https://user-images.githubusercontent.com/23311386/75096466-86a44280-55a8-11ea-9c70-7c702f60a9dd.jpg)
![Kulls_001](https://user-images.githubusercontent.com/23311386/75096467-87d56f80-55a8-11ea-95c3-ec3386f91f05.jpg)
![Rhaenysa_037](https://user-images.githubusercontent.com/23311386/75096470-93289b00-55a8-11ea-951b-af2df843171b.jpg)
![Rhaenysa_038](https://user-images.githubusercontent.com/23311386/75096472-93c13180-55a8-11ea-9b23-4813f91a43ac.jpg)
i shared 2 diferent characters. 1 dont have quests at all

**Comment by Lheana** [comment]
Or you simply have already completed these quests.
1. I tested with the dungeon quests you have:
![Lheana_125](https://user-images.githubusercontent.com/11537611/75098951-55ce0880-55bc-11ea-964b-dff2f8041542.jpg)
![Lheana_126](https://user-images.githubusercontent.com/11537611/75098953-5d8dad00-55bc-11ea-8796-2887b3fb4de3.jpg)
2. You have the proof on your screenshot that you can see the quests
![image](https://user-images.githubusercontent.com/11537611/75098956-6f6f5000-55bc-11ea-9482-e94d80ba16ec.png)
