### ISSUE TITLE
With new patch new tooltip bug

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15755]
**Expected behavior and actual behavior:**
expected to say 3s instead of 5s since todays nerf.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/43802105/75097249-0cef6300-556e-11ea-8ceb-55a8fc1eb722.png)

**Comment by grunbag** [comment]
Fixed already
