### ISSUE TITLE
Unable to purchase T1 RvR set (Decimator)

### ISSUE THREAD

**Issue by PeasantWoman** [WarEmu/WarBugs#1575]
Was unable to purchase 'Decimator tramplers' for 3 Recruits Medallions on my Marauder, I am LV8 / RR8 with 8 Recruits Medallions in the screenshot but was given 'You do not meet the requirements to purchase this item.' error when it requires Lv7 / RR 7.

http://i.imgur.com/n4vQUo2.jpg

**Comment by Zealote** [comment]
Those are SC emblems in your backpack, I think, rather than Recruit's Medallions :P

**Comment by PeasantWoman** [comment]
Oh, my mistake. Closing.
