### ISSUE TITLE
Zealot oppressor set, set bonusess doesn't benefit the career.

### ISSUE THREAD

**Issue by Kweedko** [WarEmu/WarBugs#15768]
![image](https://user-images.githubusercontent.com/13465031/75109442-04b62700-5645-11ea-8602-87566ebd3e91.png)

6 piece bonus is reduction of cast times due to most of Zealot, abillies is instant or channeled this bonnus does't benefit any spec of DDZ.

4 piece piece bonus is reducing attacker stats and increacing ini  - which is not bad if you don't die in 2 gcd but whith the cloth career - it's almost imposible uleast you have a guardbot and pocket healer.
Looks like set was designed to be a semi defencive - when DDHealers lack not the defence but the + dmg stuff.

suggestion is to change it to pure attacker set with bonuses like DD careers have - to real benefition to a career and worth of having a full set(atm. RP and Zeals never wearing a full sets cause of uslees setbonuses - 3 or 2 set mixing is always beter in term of set bonuses and stats). 
Atm/ ther is a gear gap for thi career besides the other problems - semigood set are Red Eye and Bloodlord - and after that only a Soverign - which left you with 57-78 RR gear gap - since there is no ddsets in this ranks. 

a Magic casters  - sine AP is a problem on DDZ
![image](https://user-images.githubusercontent.com/13465031/75109694-90c94e00-5647-11ea-9236-20aa9f7aecba.png)

or a simmilar to melee DD - steal thougness + int

![image](https://user-images.githubusercontent.com/13465031/75109709-bfdfbf80-5647-11ea-9641-047b8bd2eccc.png)

**Comment by RoR-Zomega** [comment]
Again, this tracker is for bugs not balance (read the front page)

**Comment by Kabucoror** [comment]
suggestions go into forums
