### ISSUE TITLE
NPC Respawn rates are at least 2x vs live

### ISSUE THREAD

**Issue by xpander69** [WarEmu/WarBugs#15769]
From what i gathered through searching old Youtube videos, the respawn rates are at least 2x faster in RoR

**Steps to reproduce the problem:** Just try to kill any mob in the world, they respawn within 1 minute usually, when you are killing your level mobs

**Testing Screenshots/Videos/Evidences (always needed):**
https://youtu.be/OASZWy9XRwU

this is just one example.

**Comment by xaraxdestr** [comment]
remember, this is not live ;)

**Comment by xpander69** [comment]
> remember, this is not live ;)

yes, but new player experience is pretty bad when the respawns are that quick, when a player decides to do PvE a bit... and i thought RoR tries to be as close as official as possible, with better class balance than on live

**Comment by dalen** [comment]
One of the videos stops before the mob respawns in the other video. So not sure if that actually shows anything.

**Comment by xpander69** [comment]
> One of the videos stops before the mob respawns in the other video. So not sure if that actually shows anything.

Its because im not the creator of the video and he walks away from there, its just to show that its longer than in RoR. In RoR the mob spawned twice during this time. Old videos are hard to find that aren't edited sadly. There are few where people say that the respawn times are about 5 min, but those are specific to some public quest areas.

**Comment by Lheana** [comment]
Respawn of NPC was usually different depending on NPCs on official.
If you wanna test, here are good [videos](https://www.youtube.com/watch?v=GqPkCUSqfl8&list=PLLwm_WijfDzqZptoBicBW4wVfIC2ZV75D&index=1) of official, you have from T1 up to T4. You can record the respawn timer of each NPC.

**Comment by xpander69** [comment]
> Respawn of NPC was usually different depending on NPCs on official.
> If you wanna test, here are good [videos](https://www.youtube.com/watch?v=GqPkCUSqfl8&list=PLLwm_WijfDzqZptoBicBW4wVfIC2ZV75D&index=1) of official, you have from T1 up to T4. You can record the respawn timer of each NPC.

Thanks i will check those. The thing is that the starting zone ones are a bit faster respawn, since they changed all races to start on the same zones, but later tiers its slower respawn, but yeah there are special cases also, like PQ ones and just important persons have different respawn rates than regular grind mobs...

**Comment by Natherul** [comment]
This is not a bug but was added intentionally. We have discussed it internally quite recently but for now decided to keep the high respawn rate
