### ISSUE TITLE
Wrong stats on zealot ddweapons/offhands

### ISSUE THREAD

**Issue by Kweedko** [WarEmu/WarBugs#15767]
1. Hp per sec(which is usless for ddz) - instead of magic power. (since RP got the same problem)

![image](https://user-images.githubusercontent.com/13465031/75106679-e6e6c300-5640-11ea-8e57-11da7f3f9d7c.png)
![image](https://user-images.githubusercontent.com/13465031/75106682-efd79480-5640-11ea-8330-5f45caff8abb.png)

________________________________________________________________________________________________________

2. +3moral(which is usless for ddz) insead of + 3ap(which is crucial for ap starving ddz)

![image](https://user-images.githubusercontent.com/13465031/75106748-67a5bf00-5641-11ea-8e36-3b5b689627a5.png)

While RP don't have this problem since he hava a satff with +6 ap
![image](https://user-images.githubusercontent.com/13465031/75106758-860bba80-5641-11ea-8ee4-526e9ea02bee.png)

_________________________________________________________________________________________________________

3. There is no sentinel offhand with big amount of Int+willpower, so  you can't maximise dmg output buy equiping them - while RP got a 2 differnt  staves with maxed stats.

![image](https://user-images.githubusercontent.com/13465031/75109263-b9e7df80-5643-11ea-844e-1a69901cab33.png)
That one don't even have an Int nor Willpower

![image](https://user-images.githubusercontent.com/13465031/75109318-d2f09080-5643-11ea-9498-6a1c1ef1ccaf.png)
That one don't have a Willpower

![image](https://user-images.githubusercontent.com/13465031/75109374-f287b900-5643-11ea-8652-4c1868685ef5.png)

That one don't have an Int.

![image](https://user-images.githubusercontent.com/13465031/75109228-5eb5ed00-5643-11ea-8f17-1a2d6a7a5b80.png)

**Comment by Ootootoo** [comment]
It's called dump stats and all end-game items/gear/weapons have it for pure balance purposes. Sometimes is more noticeable than others. If you would only have main stats stockpiling up, rr80 players with end-game gear would be unkillable juggernauts or DPS monsters, which is exactly the opposite concept of balance.

100% not a bug, and definitely not a balance trouble with RP as they only get to choose 1 item and can't double talismans.

**Comment by Kweedko** [comment]
> It's called dump stats and all end-game items/gear/weapons have it for pure balance purposes. Sometimes is more noticeable than others. If you would only have main stats stockpiling up, rr80 players with end-game gear would be unkillable juggernauts or DPS monsters, which is exactly the opposite concept of balance.
> 
> 100% not a bug, and definitely not a balance trouble with RP as they only get to choose 1 item and can't double talismans.

RP can doble talismas cause they have same mechanic like Z - just put int and wp talaismans.

First argument also invalid pure dd have on items maxed DD stat if they 2 handers, or just can equip 2 simmilar items - like choppa, mara etc.

**Comment by Ootootoo** [comment]
They can only double talismans for 100% mechanic based ones, but can't double armor, toughness, initiative, etc... only can "double" for willp/Intel due to class mechanics.

I would love you to show me a DPS weapon or combo with, counting just what you have slotted, not the ones that you refer to, that actually provides more: 18+26+18+31+15+15=113 main stats with 18 talis only so you can add 12 more points from maxed talismans to a total of 125 main stat points, 2% crit, and 6 class resources/second, and only having 19+22=41 dumped stats.

**Comment by Kweedko** [comment]
> They can only double talismans for 100% mechanic based ones, but can't double armor, toughness, initiative, etc... only can "double" for willp/Intel due to class mechanics.
> 
> I would love you to show me a DPS weapon or combo with, counting just what you have slotted, not the ones that you refer to, that actually provides more: 18+26+18+31+15+15=113 main stats with 18 talis only so you can add 12 more points from maxed talismans to a total of 125 main stat points, 2% crit, and 6 class resources/second, and only having 19+22=41 dumped stats.

Im not sure what you trying to say, that Zealot is unbalanced to RP(but RP got more dd stats on same weaps) or that all careers that have dual weilding >  2handers, is if that recomend you to post on ballance forum, it's nothin to do with this wrong stats on items?

**Comment by Ootootoo** [comment]
I'm pointing that you are the one using the bugtracker as a balance forum to make pass a non-existent balance question as a bug. If you have troubles with stats of a weapon you post them there. Here belongs something like a **Zealot item having strength** , not your perception of what a correct stat should be when is clearly not pointless for the class. If your class can use a stat, then is not a bug, which is exactly what I said. And if your class can only use 2h weapons you get a very low increase in main stats cause of the inability to set 2x talismans.

You know what? What pissed me off was that you didn't stopped, but added a lot more and more reports of your perception of stats and tried to make them pass for bugs. There are like 5 of them. **Not a single freaking bug** , just you saying "in my opinion this item should be..." or "the actual DPS class (which you conveniently forgot to say that can't rez, emergency heal, etc...) has it better that my hybrid, and I want my hybrid to be as powerful as main DPS, so this should be...", and then you have the balls of steel to tell me to go to the balance forum for pointing it out?!?

My apologies to the moderation team for this incident. You have my word that I will remain silent in the future when I see these kind of things going, but today I need to explode a bit. Sorry.

**Comment by Kweedko** [comment]
> I'm pointing that you are the one using the bugtracker as a balance forum to make pass a non-existent balance question as a bug. If you have troubles with stats of a weapon you post them there. Here belongs something like a **Zealot item having strength** , not your perception of what a correct stat should be when is clearly not pointless for the class. If your class can use a stat, then is not a bug, which is exactly what I said. And if your class can only use 2h weapons you get a very low increase in main stats cause of the inability to set 2x talismans.
> 
> You know what? What pissed me off was that you didn't stopped, but added a lot more and more reports of your perception of stats and tried to make them pass for bugs. There are like 5 of them. **Not a single freaking bug** , just you saying "in my opinion this item should be..." or "the actual DPS class (which you conveniently forgot to say that can't rez, emergency heal, etc...) has it better that my hybrid, and I want my hybrid to be as powerful as main DPS, so this should be...", and then you have the balls of steel to tell me to go to the balance forum for pointing it out?!?
> 
> My apologies to the moderation team for this incident. You have my word that I will remain silent in the future when I see these kind of things going, but today I need to explode a bit. Sorry.

It's an issue tracker, and you completly ignored other items in this issue, turning this issue in to flame war, just cause u don't like it. Balance issue is still issue and same roles should be treated the same, pure dd still will be pure dd with their benefits. I suggest u to play DDZ or DDRP to realise that there is stacked over yeas lots of issues that needs to be adressed. And this issue just a little tweak to help them in their gear progress whi is currently far from optimal.

**Comment by RoR-Zomega** [comment]
> It's an issue tracker, and you completly ignored other items in this issue, turning this issue in to flame war, just cause u don't like it. Balance issue is still issue and same roles should be treated the same, pure dd still will be pure dd with their benefits. I suggest u to play DDZ or DDRP to realise that there is stacked over yeas lots of issues that needs to be adressed. And this issue just a little tweak to help them in their gear progress whi is currently far from optimal.

This is the bug tracker. It is called the bug tracker on the front page of the project: "Return of Reckoning - Bugtracker Repo".

Sometimes items with the wrong stats are supposed to be put on here, for example the Zealot DPS Sovereign set has healing stats on it which is clearly a mistake, but in your example for it to be a bug you'll likely need to show that the stats are a mistake as opposed to not optimal, e.g. if there was a logical progression and then one item was completely messed up.

Obviously it's down to the devs to decide whether these items are incorrect and they were supposed to have different stats on them.

**Comment by Kweedko** [comment]
> Sometimes items with the wrong stats are supposed to be put on here, for example the Zealot DPS Sovereign set has healing stats on it which is clearly a mistake, but in your example for it to be a bug you'll likely need to show that the stats are a mistake as opposed to not optimal, e.g. if there was a logical progression and then one item was completely messed up.

There is a logical progression on SC weapons  - and frist two cases is about that(moral istead of ap, +hhp istead of magic power - like on all other SC waepons). 

Third is all about - uneven stats on equal item complects - Z dagger + offhand  - compare to RP staff.

**Comment by RoR-Zomega** [comment]
The Zealot offhand is a charm and all charms (WP, DoK and Zealot) follow the same progression of having +morale instea of +AP on the Oppressor versions. The Zealot's combined main/charm stats often differ from the Runepriest's staff stats as they follow different progression.

Here's another example using the Subjugator weapons:

Runepriest Staff: https://www.returnofreckoning.com/armory/item/1848
Zealot Dagger: https://www.returnofreckoning.com/armory/item/1884
Zealot Focus: https://www.returnofreckoning.com/armory/item/1883

Zealot gains extra crit and has wounds instead of init.

**Comment by Kabucoror** [comment]
suggestions go into forums
