### ISSUE TITLE
Fort Pop not capping at 20% for defenders

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15765]
**Expected behavior and actual behavior:**
Expected that only 20% of defenders can gain access to fort, instead entire population is able to get inside and defend ignoring reservation and population cap

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/43802105/75104826-1ced5e00-55d3-11ea-8240-c29ae9030174.png)

**Comment by bosli42** [comment]
While I thought this is the case too, I'm pretty sure the population also counts all the defending players right behind the gate to the portals trying to get in. Their point of walking in and getting teleported out is completely inside the fort zones, not at the zone border like attackers, so their population number cannot be shown correctly.

Not 100% sure, needs GM/Dev confirmation.

**Comment by SilverWF** [comment]
Zonepop addon shows whole zone population
While actual fort area is smaller than corresponding zone
So not all players, that Zonepop has found, are in the actual fort.
This is obvious.

**Comment by onemantankwall** [comment]
> Zonepop addon shows whole zone population
> While actual fort area is smaller than corresponding zone
> So not all players, that Zonepop has found, are in the actual fort.
> This is obvious.

Just because it's obvious doesnt mean 20% defender pop is working when it comes down to it they had no aao and equal if not more numbers within the fort itself. Not long ago you could bypass barrier by simply running in twice throwing number balance I wouldn't create this if things didnt seem off.

**Comment by Natherul** [comment]
zonepop is not valid. As stated it shows total players in zone which is not corresponding with reality. SoR will in the future show total pop of forts as well pending an addon update.
