### ISSUE TITLE
Karaz Drengi keep defense kill quest objective to kill players at Kazad Dammaz

### ISSUE THREAD

**Issue by Qorth** [WarEmu/WarBugs#15764]
When playing Destruction character and Karaz Drengi is Destruction owned, the keep lord at Karaz Drengi offers kill quest for enemy players 0/25 killed at Kazad Dammaz.

**Comment by Lheana** [comment]
Has this been fixed with hotfix of today?

**Comment by Qorth** [comment]
Unable to confirm.  Keep is Destruction owned as of 2/23/2020 23:46 EST, but is populated with Order NPCs including Lord (Kolbjorn Ironcleave).  https://imgur.com/AVWufHy

**Comment by SilverWF** [comment]
Similar was there #15575

**Comment by raptrr** [comment]
as mentioned, similar one is linked. gonna close this one
