### ISSUE TITLE
Warpblade Tunnels/Sigmar Crypts

### ISSUE THREAD

**Issue by Emerosa** [WarEmu/WarBugs#15760]
I had the pleasure of doing Warpblade Tunnels/Sigmar Crypts with a group today and found that the bosses weren't giving any loot (still loot from the champs, random screenshot attached for no boss loot). Also in the Sigmar Crypts the two Zealot bosses after they were killed one had respawned (the one the left I believe, sorry no screenshot) and in Warpblade Tunnels the Rat Ogre boss spawned when the other boss was killed so we had to deal wit two of them (see screenshot). Also forgot to mention, none of the kills counted toward the quests as well

![Lindara_005](https://user-images.githubusercontent.com/28827833/75100546-06c4ab00-559d-11ea-90f2-c510dd63795e.jpg)
![Lindara_006](https://user-images.githubusercontent.com/28827833/75100547-075d4180-559d-11ea-87d4-886d4e610f17.jpg)

**Expected behavior and actual behavior:** Bosses give loot/Bosses give none, Double boss spawn, Boss spawn again after death

**Steps to reproduce the problem:**Kill Bosses

**Testing Screenshots/Videos/Evidences (always needed):** Attached

**Comment by Emerosa** [comment]
Also forgot to mention, none of the kills counted toward the quests as well

**Comment by Lheana** [comment]
Has this been fixed with the hotfix of today?

**Comment by kalmatar** [comment]
did Destro city dungeons today, loot and kill credits for quest were working fine. Apparently this was yesterdays bug which got fixed sometimes last evening or night in some server reboot.

**Comment by Lheana** [comment]
Ok then I close the ticket.
