### ISSUE TITLE
Nordland T1 Order Warcamp

### ISSUE THREAD

**Issue by Luitpoldi** [WarEmu/WarBugs#15763]
You can enter the order nordland warcamp by jumping up here.  You were able to do this on destro in the live game and kill people and npcs.  I used an order toon to illustrate, but I'm sure destro can get in here too, as the high level warcamp guards are far enough away.
![nordland_order_wc](https://user-images.githubusercontent.com/59587770/75103038-20202400-55aa-11ea-8b98-3b12f6c2fb2b.jpg)
![nordland_order_wc2](https://user-images.githubusercontent.com/59587770/75103039-20b8ba80-55aa-11ea-92a2-0b4d21612019.jpg)
![nordland_order_wc3](https://user-images.githubusercontent.com/59587770/75103040-21515100-55aa-11ea-8bf0-799a2f613d54.jpg)
![nordland_order_wc4](https://user-images.githubusercontent.com/59587770/75103041-21515100-55aa-11ea-87f1-4f3c337d67d5.jpg)
![nordland_order_wc5](https://user-images.githubusercontent.com/59587770/75103042-21e9e780-55aa-11ea-8f96-36d612a5e4fe.jpg)
![nordland_order_wc6](https://user-images.githubusercontent.com/59587770/75103043-21e9e780-55aa-11ea-899d-0e4b22905a29.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by Lheana** [comment]
This should have been fixed with the patch of today.
