### ISSUE TITLE
[WITCH ELF] [TACTIC] Frenzied Mayhem has no effects

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#15776]
**Expected behavior and actual behavior:**

The tactic Frenzied Mayhem for Witch Elf should be a pick from level 27 onwards, but apparently can't be picked as its marked in red, and if you slot it, there is no effect whatsoever on the character. Tested with .getstats and not with character sheet.

I tried to slot the tactic only, without anything else, and still the troubles persists, even when relogging the game.

Maybe this bug is related to level instead of the tactic itself, so if someone could confirm with a level 40 WE, that would be awesome, thanks.

**Steps to reproduce the problem:**

Reach level 27 as WE, get Frenzied Mayhem Tactic, slot it and test it.

**Testing Screenshots/Videos/Evidences (always needed):**
Normal crit rate without Bloodlust:
![Hagganeth_009](https://user-images.githubusercontent.com/50114048/75117274-e4e42a80-5667-11ea-97ca-faa00f22a5eb.jpg)
Crit rate unaffected even having 5 Bloodlust (according to tactic tooltip it should be increased by 25% now):
![Hagganeth_010](https://user-images.githubusercontent.com/50114048/75117285-06451680-5668-11ea-81ab-be3f4fb85392.jpg)

**Comment by Ootootoo** [comment]
Updated info: 1st, I'm sorry, but I made a mistake. The increase should be of 3% per bloodlust, so 15% at 5 bloodlust. 2nd, the tooltip itself seems to be completely wrong in-game. I checked in Warbuilder and in Career Builder, and they return a completely different tooltip that the one that I screenshots without reading.

**Comment by Ootootoo** [comment]
Update 2: So I turned level 31 and all of a sudden the tactic works. Also I have to say that it was in the 3rd tactic slot, and still is there, and that I didn't specifically slot it to check, but instead removed the other 2 tactics. So, my guess is something off with the extra tactic slot.

**Comment by agemennon675** [comment]
Can you inform me here if some of your tactics doesnt work at level 35-36 in scenarios or rvr when bolstered

**Comment by Ootootoo** [comment]
Finally level 35, tactic seems to work... and I say "seems" loosely, cause can't confirm 100% from both .getstats and experience. Seems either random, or not implemented in the use of frenzies, or depending in all parts of a frenzy to deal damage, or... I can't really point out at what makes the tactic work or not.

**Comment by agemennon675** [comment]
My experience was like this, whenever I get into scenarios I get bolstered and bolster gets removed from me at the beginning, because you no longer get bolstered after certain level lvl35-36-37... causing all my buffs to be removed and all my tactics needs re-equipping, if I re-equip my tactics they work, if I dont they dont work. I think the problem is bolster applies and gets removed after certain level

**Comment by grunbag** [comment]
I don’t understand the issue .
