### ISSUE TITLE
[QUEST] [T1 EPIC] [DARK ELF] Legend and Infamy, unable to follow up this stage

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#15777]
**Expected behavior and actual behavior:**

The quest ask for a specific type of NPC to be killed to get an item. The NPC type in question doesn't drop such item, making any progress further in the chain impossible.

**Steps to reproduce the problem:**

Reach the step listed in the screenshot.

**Testing Screenshots/Videos/Evidences (always needed):**
![Tropica_000](https://user-images.githubusercontent.com/50114048/75117390-d5b1ac80-5668-11ea-8fe0-ab8496899eab.jpg)

**Comment by Lheana** [comment]
I guess you were just unlucky for the loots. Try to kill more ambushers.

**Comment by Ootootoo** [comment]
Like incredibly unlucky cause I killed lots of them... and I mean LOTS...

**Comment by Lheana** [comment]
Drop chances are set to 10%.

**Comment by Ootootoo** [comment]
Over 50 mobs killed to add to the amount that I killed the other day, I finally got the item. I may be the unluckiest person seems....
