### ISSUE TITLE
Healers DD Soverign set bonuses not simmilar to magic caster DD.

### ISSUE THREAD

**Issue by Kweedko** [WarEmu/WarBugs#15770]
Since Zealot and other cloth healers are magic casters in ther dd specs - they deserve being treated like one.

Atm 
7 piece bonuse just adding +crit whithout +critpower and even this 7% istead of 10% like casters.
8 piece rediced chance to distrupt - instead of flat +15% crit dmg.

On live cloth healers have the same sets as magic dd - cuase of blance, here - this bonuses creating even further gap between magic DD and DD healers. 

![image](https://user-images.githubusercontent.com/13465031/75109999-557c4e80-564a-11ea-9f04-b247ac03f0e7.png)

![image](https://user-images.githubusercontent.com/13465031/75110038-b4da5e80-564a-11ea-91b2-3751c3a07c04.png)

**Comment by Kabucoror** [comment]
suggestions go into forums

**Comment by Kweedko** [comment]
> suggestions go into forums

so it's intendend 7 pc  bonus weaker than magedd similar bonus?
