### ISSUE TITLE
[QUEST] [NPC] [MINOR] Essence of the Fallen quest giver has random pathfinding

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#15778]
**Expected behavior and actual behavior:**

The NPC giver of this quest required to unlock a jewelry piece has a very erractic pathfinding, and I personally has to wait well over 5 minutes for him to leave the interior of a wall to take this quest. In every other respect, everything is fine, just the pathfinding inside the Lyceum in the Inevitable City seems very odd and makes very difficult to locate and interact with some NPCs.

As siad, mostly an annoyance.

**Steps to reproduce the problem:**

Stay in the Lyceum for roughly 15 mins and around 5 of them you will see impossible to interact NPCs due to being inside the wall, transitioning somewhere that will return an unreachable message, and more oddities.

**Testing Screenshots/Videos/Evidences (always needed):**
![Dathenor_007](https://user-images.githubusercontent.com/50114048/75117488-b10a0480-5669-11ea-97bd-a5489255868c.jpg)
![Dathenor_006](https://user-images.githubusercontent.com/50114048/75117489-b2d3c800-5669-11ea-8cc7-1c65a6e8e1d4.jpg)
![Dathenor_005](https://user-images.githubusercontent.com/50114048/75117490-b5ceb880-5669-11ea-959f-386f89a87087.jpg)

**Comment by Lheana** [comment]
This should have been fixed with the patch of today.
