### ISSUE TITLE
[QUEST] [T3 EPIC] [CHAOS] Inevitable power rewards for elves, at least.

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#15775]
**Expected behavior and actual behavior:**

The quest should reward usable weapons based in the class of the character. At least for Witch Elves it allows a reward based in ¿race? which is non-functional for them. One of the choices of rewards is a sword.

**Steps to reproduce the problem:**

Complete the last step of Inevitable Power as Witch Elf

**Testing Screenshots/Videos/Evidences (always needed):**
![Hagganeth_007](https://user-images.githubusercontent.com/50114048/75117182-21635680-5667-11ea-8f62-7ee975774ed8.jpg)

**Comment by Lheana** [comment]
This should have been fixed with the patch of today.
