### ISSUE TITLE
Sorc Ice Spikes works not as described

### ISSUE THREAD

**Issue by Elthendeath** [WarEmu/WarBugs#1578]
Skill "Ice Spikes" is not working like described! It should be a 65 ft front-AoE Dot, actually it works as normal Dot.

**Comment by Evildoor** [comment]
Are you sure about this? I asked my friend who plays sorc, he says that it's AoE.

**Comment by ozarmidrashim** [comment]
Willing to bet this is a false report

**Comment by milosxe** [comment]
Works fine for me.
