### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by necropanda777** [WarEmu/WarBugs#15788]
GOT A MESSAGE OF REPORTING A BUG THAT DIDNT ALLOW  TO ADD ME THE CONTIBUTION FOR THE LOCK IN CALEDOR, BEFORE ENTERING FORT. I WAS BEHIND THE KEEP IN BETWEEN CALEDOR AND THE FELL LANDING. ATM I M IN FORT, IT LET ME IN, BUT I GOT A MESSAGE THAT MY RESERVATION WAS EXPIRED, IT DIDNT EVEN KICK ME FROM FORT. 
 

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Natherul** [comment]
same as https://github.com/WarEmu/WarBugs/issues/15199
