### ISSUE TITLE
The whole WB got contribution for fort... i didn't

### ISSUE THREAD

**Issue by starfkr** [WarEmu/WarBugs#15781]
I was in the WB/Ally WB and entered the Reikland the same time as everyone in the WB.

23/24 got into Reikwald, i was the only one left out.

![Nbh_003](https://user-images.githubusercontent.com/58277587/75120991-4cae6b80-5690-11ea-818c-9b96c67c6485.jpg)

**Comment by starfkr** [comment]
This yellow message came up once more while standing and waiting.

**Comment by starfkr** [comment]
![Nbh_003](https://user-images.githubusercontent.com/58277587/75121033-b7f83d80-5690-11ea-8393-a94f8a0b17ea.jpg)

**Comment by starfkr** [comment]
...and a 3rd time.

![Nbh_005](https://user-images.githubusercontent.com/58277587/75121069-00176000-5691-11ea-95d8-528fc245b4b8.jpg)

**Comment by raptrr** [comment]
Did you enter the fort area before the zone lock/flip?

**Comment by Natherul** [comment]
same as https://github.com/WarEmu/WarBugs/issues/15199 but with a twist
