### ISSUE TITLE
City Siege missing champions stage 3

### ISSUE THREAD

**Issue by bosli42** [WarEmu/WarBugs#15785]
We had only 3 destro champions and only 2 order champions in our instance.

On our side, we were missing the tank champ, and a blackguard crashed either at the stage transition or at the beginning of stage 3, so that might have to do something with it.
![Zyv_186](https://user-images.githubusercontent.com/18313892/75124481-c570f000-56af-11ea-967b-8cc840f6e403.jpg)
![Zyv_187](https://user-images.githubusercontent.com/18313892/75124476-c1dd6900-56af-11ea-978e-4c2c0dac08c4.jpg)

**Comment by bosli42** [comment]
From today's IC siege
![Zyv_195](https://user-images.githubusercontent.com/18313892/75190167-028cbf00-5750-11ea-90fd-d4c315e1f4d5.jpg)

**Comment by gittoaster** [comment]
No champs for us in Altdorf last night (pacific) for destro or order, after hotpatch 5

**Comment by MaxHayman** [comment]
This should be fixed, please let me know if this is not the case.
