### ISSUE TITLE
Item from Warrior Priest starter quests can't equip

### ISSUE THREAD

**Issue by Dkrewe** [WarEmu/WarBugs#15780]
The quest reward item "Cracked Slipshoes of Fortification" is not able to be equipped. 

![Drohkor_002](https://user-images.githubusercontent.com/51872114/75118257-6c607800-562d-11ea-90f1-321ae2e47b6f.jpg)
![Drohkor_000](https://user-images.githubusercontent.com/51872114/75118259-6cf90e80-562d-11ea-8c72-91e856b2221d.jpg)
![Drohkor_001](https://user-images.githubusercontent.com/51872114/75118260-6d91a500-562d-11ea-9c50-427f5258d985.jpg)

**Steps to reproduce the problem: Do the initial few quests of Order on a Warrior Priest, obtain the item from the quest reward after speaking to the trainer, and then try to equip the new boots. 

I know this is a fairly minor bug as this item is quickly replaced, just figured it would give new players a bad impression of the game if they encounter a bug like this in their first 10 minutes of game play.

**Comment by Lheana** [comment]
This should have been fixed with the patch of today.
