### ISSUE TITLE
Ability to attack inside keep in CW - Wrath's Resolve

### ISSUE THREAD

**Issue by TomSzczurowski** [WarEmu/WarBugs#15794]
**Expected behavior and actual behavior:**
People ontop of the Wrath's Resolve walls should be able to LOS ranged DPS. Rock in screenshot below removes the ability to LOS. Additionally, WL are able to pounce onto enemy players in the keep from the rock as well.
**Steps to reproduce the problem:**
Using a WL, mount, run up the rock. Select a player and pounce
**Testing Screenshots/Videos/Evidences (always needed):**
Rock is in screenshot below. Unable to record on my device.

**Comment by TomSzczurowski** [comment]
![image](https://user-images.githubusercontent.com/47514501/75212268-81c6d500-57da-11ea-8f54-1ba662fd9439.png)

**Comment by dalen** [comment]
Fixed by the 2020-09-09 patch
