### ISSUE TITLE
Jug of Corn Whiskey quest doesn't advance

### ISSUE THREAD

**Issue by valkeera** [WarEmu/WarBugs#15792]
After accepting the "Jug of Corn Whiskey" quest, clicking on the jug doesn't advance it to the next stage and it's not possible to complete it.

![Eloki_000](https://user-images.githubusercontent.com/58527250/75193813-40d9ac80-5757-11ea-80d9-f4512d44b5fc.jpg)

**Comment by Lheana** [comment]
I guess that after you have interacted with the object to take the quest, you have to wait a bit to be able to click on it and loot it.

**Comment by valkeera** [comment]
You're right, the loot dialog window with the jug will appear after you click on the object after 4 minutes or so (although there is no indication that you need to wait in the quest description itself, which was wha confused me).

![Eloki_004](https://user-images.githubusercontent.com/58527250/75383660-0d288f00-58dd-11ea-9590-6b43a4962d1b.jpg)

**Comment by Lheana** [comment]
As the quest can be completed, I close the ticket. I understand it may be a bit annoying to have to wait, it will be fixed one day, but it's not a high priority.
