### ISSUE TITLE
Champs in city siege are selected from overall players instead of factions

### ISSUE THREAD

**Issue by CornerbackAC** [WarEmu/WarBugs#15790]
**Expected behavior and actual behavior:**
Expected:
1 tank, 1 mdps, 1 rdps & 1 healers is selected as champ from each faction.

However, in our latest IC raid, there was a bug with the champs in step 3.
Only 4 champs were selected in total, which resulted in one instance having 2 destru champs vs 2 order champs and another ini with 1 order champ vs 3 destru champs.
Based on the archtypes (BG, WE, dps AM and WP in the first one mentioned, DPS AM, Zealot, Squig and Chosen? in second one) I assume the 4 champs are selected randomly from the overall player pool instead of each faction.

**Steps to reproduce the problem:**
Participate in IC raid.

**Testing Screenshots/Videos/Evidences (always needed):**
We got wasted, so I somehow forgot about screens :(

**Comment by MaxHayman** [comment]
This should be fixed.
