### ISSUE TITLE
City Siege: DoK classified as "Ranged DPS" in stage 3 (IC)

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#15791]
**Expected behavior and actual behavior:**

Addiktion is specced as a melee DPS DoK (as opposed to healer spec). When this player was chosen to be a champion the message that came up stated that Addiktion had been chosen as the **ranged** DPS champion.

In addition, only 2 champions were picked for each side but there are other tickets open about that bug.

**Testing Screenshots/Videos/Evidences (always needed):**

![Zomega_155](https://user-images.githubusercontent.com/60266177/75187261-a02cc200-5741-11ea-819f-b4392b359f95.jpg)

**Comment by dalen** [comment]
This was fixed a few patches ago
