### ISSUE TITLE
[Scenario] Black Crag Keep - destruction quest giver is out of bounds before scenario begins

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#15806]
**Expected behavior and actual behavior:**

The destruction NPC who gives the "Conqueror the Black Crag Keep" quest (the one that awards tokens for winning) is located outside of the spawn area. This means when you go to him to try and take the quest during the countdown before the scenario starts you will be teleported away from him and put back in spawn. This compares to the quest givers in other scenarios which can be safely interacted with from the spawn area.

The NPC is named "Black Crag Keep Bloody Sun Warmaster" and needs to be moved a couple of metres towards the destro spawn area to stop the players from being teleported away.

**Steps to reproduce the problem:**

1) Any destruction character
2) Black Crag Keep scenario
3) Walk up to the "Black Crag Keep Bloody Sun Warmaster" near spawn during the countdown before the scenario starts.
4) Get teleported away while trying to take the quest.

**Testing Screenshots/Videos/Evidences (always needed):**

This is about the maximum range needed to interact and I was teleported away from it. The countdown just hit zero so it's kept me in place for this picture. If the NPC was moved to my player's location in the screenshot then it should fix the issue.

![Zomega_158](https://user-images.githubusercontent.com/60266177/75341785-15f17480-588d-11ea-98f2-80bc2632597f.jpg)

**Comment by Lheana** [comment]
It should have been fixed with the patch of 28/03/2020.
