### ISSUE TITLE
AAO overwriting buffs

### ISSUE THREAD

**Issue by bobeer86** [WarEmu/WarBugs#1580]
AAO buff seems to overwrite whatever buff is cast first on a character and replace it with itself. when recasting buff, AAO vanishes only to reappear and overwrite again in few seconds.

so far verified on shammy with resistance buff (after it gets overwritten resists on char sheet lower to base stats) and dok covenants (no changes on char sheet).

**Comment by wargrimnir** [comment]
This can be closed. Visual bug only, no longer occurring.
