### ISSUE TITLE
Zone 0 bug after attempting to use Book of Binding to return to IC after Altdorf siege.

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#15807]
Disclaimer: this happened on 21/2/20 at 2:53 GMT but I forgot to bug report it at the time.

**Expected behavior and actual behavior:**

My Book of Binding is set to the Rally Master in the Apex in the IC. When I used the book during an an Altdorf siege I was taken to "Zone 0". This zone had a skybox but nothing else, I was continuously falling and the chat window was spammed with "The Winds of Change blow strongly in uncharted territory, and have transported you back to your capital." Eventually I managed to load a proper zone but I cannot remember if I used /stuck or what (sorry, it was late and a few days ago!!)

I cannot remember if I used the book at the end of stage 3 while still in Altdorf or if I had been teleported out of the city and dumped in Norsca first.

**Steps to reproduce the problem:**

Use the book of binding either at the end of a stage 3 city siege while still in Altdorf and/or try again if teleported to Norsca after the city siege.

**Testing Screenshots/Videos/Evidences (always needed):**

![Zomega_126](https://user-images.githubusercontent.com/60266177/75347315-67533100-5898-11ea-8914-72bc399b96cf.jpg)

**Comment by RoR-Zomega** [comment]
Found another screenshot. Apparently the game thought I had loaded into the Apex even though I was in Zone 0 (check scrolled up chat log).

![Zomega_128](https://user-images.githubusercontent.com/60266177/75347470-b1d4ad80-5898-11ea-90f0-d51856dba977.jpg)

**Comment by RoR-Zomega** [comment]
Previous Zone 0 bugs: #10254 #7058 #6831 #6080 #5789 #4794 #4677 #3842 #1655 #1412

**Comment by RoR-Zomega** [comment]
Same again just now. Some more detailed circs.

Victory in Altdorf on all 3 stages (I am on destruction). Rather than leaving through the portal at the end I just waited and got teleported to Norsca. I then used the book of binding to go to IC and entered the same Zone 0 as above along with the same message in chat.

**Comment by MaxHayman** [comment]
This should be fixed in the last week. Let me know if this is not the case.
