### ISSUE TITLE
"Encounter still in progress" Can't reenter instance

### ISSUE THREAD

**Issue by xaraxdestr** [WarEmu/WarBugs#15800]
It happens to us on Sunday, as we where in gunbad at art da feed. We wiped sometimes and then we cant reenter bossroom "encounter still in progress" while everyone died in instance and stand in front of portal. Relog and rebuild the grp doesnt work.

Today we had the same issue in BB too. Wiped at first boss BB and the the barrier at entrance was active and did not go away. We relogged and stand in front of instance and cant enter "encounter still in progress". All tries with relog and changing leader didnt work. In the end we had to change a toon and do the same again.

![WAR-64 2020-02-25 20-05-551](https://user-images.githubusercontent.com/45398873/75287245-5237bd00-581a-11ea-9918-3f75774a78d5.png)

**Comment by Lheana** [comment]
This should have been fixed with the patch of today.
