### ISSUE TITLE
Rename problem

### ISSUE THREAD

**Issue by Skprime** [WarEmu/WarBugs#15819]
So 1 month ago I changed my SW from Skprime to Iskpl, right now I'm elegible to a new rename and I requested it. When I want to change name to my SM to "Skprime" the name is already taken. In the armory if I search the name my SW pops out even tho he's called Iskpl right now

**Comment by MaxHayman** [comment]
Looking at the database i assume you managed to resolve this issue.

**Comment by Skprime** [comment]
I've actually not. There's no character named Skprime and the name is still unavailable. I had to rename the toon "Skprme" witgout the i.
I'd love to have Skprme named Skprime...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
