### ISSUE TITLE
Order Chapter 1 PQ not completing.

### ISSUE THREAD

**Issue by Naelar** [WarEmu/WarBugs#15817]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**
This happened last night, as well.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
I need more details: Which PQ? What happened exactly?

**Comment by dalen** [comment]
Likely it is due to the "Nordland Peasant" mobs near the PQ getting the killing blow on the boss. A fix for this is pending.

**Comment by dalen** [comment]
Also duplicate of https://github.com/WarEmu/WarBugs/issues/12685
