### ISSUE TITLE
my name show that im was starting a siege, but i wasnt

### ISSUE THREAD

**Issue by Gagaddon** [WarEmu/WarBugs#15813]
![Gagaddon_063](https://user-images.githubusercontent.com/52387005/75394273-8b316980-58ce-11ea-8e70-e74b534470d6.jpg)

**Comment by Razielhell** [comment]
Same thing happened to me today i can confirm the exact same message with my characters' name.

**Comment by Confederatus** [comment]
Same weird thing whas in Praag.

**Comment by Lheana** [comment]
This should have been fixed with the patch of today.
