### ISSUE TITLE
Black Orc 6 piece bonus for Offensive Sovreign is +2 to S/B mastery

### ISSUE THREAD

**Issue by Babanim** [WarEmu/WarBugs#15816]
It should be +2 to Path of Da' Brawler

Not Path of Da' Toughest which is already covered by defensive sov

![offsov](https://user-images.githubusercontent.com/57642385/75405810-bcb13180-58dc-11ea-9af8-f5e8a48833da.png)

Thank you for looking into this.

**Comment by Lheana** [comment]
This has been fixed with the patch of 21/03/2020.
