### ISSUE TITLE
PQ Tracker is not updating

### ISSUE THREAD

**Issue by HandsomeWes** [WarEmu/WarBugs#15810]
**Expected behavior and actual behavior:**
Looting objects does not work about 8 out of 10 of the times

**Steps to reproduce the problem:**

Looting any object in the open world

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/61509187/75357730-210acb80-58b2-11ea-853f-0175e161f08b.png)

**Comment by Ootootoo** [comment]
They may be in "cooldown" if it's about Public Quests or Quests items. Every interaction procs a cooldown on them for the next use, so you may not be able to interact if someone else did recently. This cooldown is very short and should not be a problem but an annoyance.

**Comment by HandsomeWes** [comment]
It happens when I am alone in PQs as well, with no other people around to loot them.

**Comment by Lheana** [comment]
I need more details than just "Looting objects does not work about 8 out of 10 of the times". Is it when you try to complete a quest? A PQ? Or nothing, you just see a GO you can click on and nothing happens?

**Comment by HandsomeWes** [comment]
The objects I cannot use are objects required for quests or PQs. An example is the Banner you have to claim in the western part of the Order tier 1 zone. Clicking this banner while being the only one in the PQ did not trigger any response, even though this was a named objective for the PQ.

**Comment by Lheana** [comment]
Name of the quest please.

**Comment by HandsomeWes** [comment]
That specific PQ was Ruins of Schloss von Rubendorff, in Nordland.

**Comment by Lheana** [comment]
I tested, and this seems like a general issue with PQ tracker that is not updated when changing stage. If you leave the PQ and enter again, you'll see the PQ went into stage 3 for the example of the PQ Ruins of Schloss von Rubendorff.
