### ISSUE TITLE
Influence deleted after severrestart/ not able since to get influence 

### ISSUE THREAD

**Issue by airkbug** [WarEmu/WarBugs#1581]
hi , this happend about 1, 5 weeks ago ... i was playing northland pvp and after restart all influence was gone . i w8ted some days now in hope it would get fixed by relogs or some other way but now i still have the same problem . so far it looks like i can not gain any influence anywhere . some parts of the warstory in my tome are also not displayed . the char is Astora / order and its only on her so far , the otehr chars work just fine . plx help :P

**Comment by sioding** [comment]
**Thanks for the report.** Since there is no confirmation, i will close this now. Please make sure to follow the bugtracker rules which you can find here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)
