### ISSUE TITLE
T1 vendor twohanders

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#1582]
Many two handed weapons(Militia, Of Vengeance) from T1 vendors have only 1 talisman slot. Should be two, like all twohanders (non-LOTD, with slots). Source says that 1 talisman is correct:
http://www.arsenalofwar.com/items/Destruction/Big%20Choppa%20of%20Vengeance
http://www.arsenalofwar.com/items/Destruction/Deathaxe%20of%20Vengeance
http://www.arsenalofwar.com/items/Order/Militia%20Claymore
But other ones have two, few examples:
http://www.arsenalofwar.com/items/Order/Waraxe%20of%20Vengeance
http://www.arsenalofwar.com/items/Order/Chraceaxe%20of%20Vengeance
http://www.arsenalofwar.com/items/Order/Claymore%20of%20Vengeance

**Comment by Reggaewaldo** [comment]
I made the change you requested since we had other things to balance those items according to.

**Comment by Reggaewaldo** [comment]
Closing.
