### ISSUE TITLE
[Bastion Stair] Unable to progress the "Infinite Patience" quest

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#15827]
**Expected behavior and actual behavior:**

The "Infinite Patience" quest requires you to use the Chosen Spear (inventory) on the Khornate Altar in the middle wing of Bastion Stair. When you reach the altar trying to use the Chosen Spear does nothing. You can click on the altar but it doesn't update the quest.

I would expect either using the spear or just interacting with the altar while the spear is in your quest items would be enough to progress the quest.

**Steps to reproduce the problem:**

Take the quest Infinite Patience, try to use Chosen Spear / Khornite Altar in BS middle wing.

**Testing Screenshots/Videos/Evidences (always needed):**

![altar](https://user-images.githubusercontent.com/60266177/75567460-7b8a6000-5a49-11ea-8006-de235963167a.jpg)

**Comment by Kabucoror** [comment]
Did you use it on the correct stair?

**Comment by RoR-Zomega** [comment]
That screenshot was from the Steps of Ruin (mid wing) which matches what is listed in the quest. Is there more than one Khornate Altar in that wing?

**Comment by Kabucoror** [comment]
well, you pass three stairs until the 3rd mini boss. Be sure you are on the right one the quest mentions.

**Comment by RoR-Zomega** [comment]
Okay I'm locked out of BS for 3-4 days. If you're happy to leave this open I'll try it again next time I go through and reply back with my findings to make sure I'm not being an idiot.

**Comment by RoR-Zomega** [comment]
After coming through the portal after killing the second boss (the Bloodletter and his summoned Flesh Hound).

First room: "Khornite Altar" flashing in the middle. Right clicking it doesn't work. Using the spear from backpack doesn't work.

Second room: has a fire pit in the middle. Nothing to interact with, using the spear in the pit does nothing.

Third room: this is the mini boss room. No altar to interact with.

I couldn't see any quest marker in the middle wing for this either.

**Comment by Kabucoror** [comment]
added a marker with next patch

you find the correct kohrne alter after Doomspike
