### ISSUE TITLE
Reikland Keep not accepting resource supplies

### ISSUE THREAD

**Issue by IxanderousI** [WarEmu/WarBugs#15823]
The Order keep currently in reikland right now will not accept supplies at the resource drop point, its currently labled as destruction, i have tried this twice with two different supplies and another player reported the same. Currently order cannot upgrade keep and its stuck at zero stars.

![Krantz_038](https://user-images.githubusercontent.com/25346641/75492562-f141ed80-59af-11ea-9b78-6d21d61927f3.jpg)

**Comment by Kaelang** [comment]
Tested & working as intended. Please re-open if you can replicate the issue.
