### ISSUE TITLE
[Bastion Stair] Unable to progress the "Power Within" quest

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#15828]
**Expected behavior and actual behavior:**

This quest requires you to kill 3 named champions in the Path of Fury (right wing): Fallen Knight Niederlitz, Fallen Knight Roemer and Fallen Knight Matthieu. Each champion should drop a specific item for the quest. Yesterday we killed all 3 champions and none of them dropped the items. I know for sure I was the person who looted 2 out of 3 of the champions so I would get the item.

The quest text does not imply that the drop chance is random.

Alternate fix: rather than requiring 6 runs to complete the quest (each person needs the item so that means a party running BS will need to kill them 6 times so each person gets it), could the quest progression trigger be based on killing the NPC rather than looting them?

**Steps to reproduce the problem:**

Kill these 3 champion NPCs in the right wing of Bastion Stair.

**Testing Screenshots/Videos/Evidences (always needed):**

Sorry none taken :(

**Comment by Kabucoror** [comment]
fixed with next patch

Actual workaround for dungeons: 3 items per kill and they appeare in loot roll
