### ISSUE TITLE
[Scenarios] Soldier emblems as reward for 30-39 lvls

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#15821]
When finishing mid tier scenarios, players of lvl30-39 are still getting soldier emblems as reward - 1 to 8 soldier emblems (depends on activity and winner side).
Pretty sure, it must be officer emblems, because all scenario gear of 30+ lvl (weapons 34 and 39 lvl, Mercenary set 35 lvl) are purchasable for officer emblems.
This makes gathering proper gear for mid tier players as pretty hard.

**Expected behavior and actual behavior:**
Expected: officer emblems
Actual: Soldier emblems

**Steps to reproduce the problem:**
Get character of 30-39 lvl
Play scenario
Check rewards after it ends

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by LTP-Blackroot** [comment]
Also experiencing this issue. Can't acquire mercenary gear. [
![image](https://user-images.githubusercontent.com/62046021/76494449-44358f00-640b-11ea-8bfd-420aee0a9635.png)
](url)

**Comment by LTP-Blackroot** [comment]
+1

**Comment by Kaelang** [comment]
This should have been fixed as of 27/05/20. Please re-open if issue persists.
