### ISSUE TITLE
tactics wearing out

### ISSUE THREAD

**Issue by Ysaran** [WarEmu/WarBugs#15839]
**Expected behavior and actual behavior:**
everytime that i log-in or that i come out of SC all my tactic slot are emptied or filled with random tactic. the issue seems to appears only on my IB, all my other characters are unaffected.

**Steps to reproduce the problem:**
log-in or come out of SC

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Tazo83** [comment]
yea came to report this issue and found this topic and another one 

so thats + confirm tactics are not working after loading screen 
other topic with same issue 💯 
https://github.com/WarEmu/WarBugs/issues/15857

having this issue on squiq too

**Comment by raptrr** [comment]
Can you try to provide a screenshot before and after it happening? maybe with timestamps?

**Comment by Ysaran** [comment]
I hope this can be usefull, if it isn't then tell me and i will try to gather nore precise information.

![tactic_before](https://user-images.githubusercontent.com/47554048/75861937-63766000-5dfe-11ea-8730-68166b7bcfd7.png)
![tactic_after](https://user-images.githubusercontent.com/47554048/75862012-84d74c00-5dfe-11ea-80c5-2dcfdb145e20.png)

**Comment by DypfrystBram** [comment]
https://youtu.be/Fsi0_CqMaiM

**Comment by DypfrystBram** [comment]
Made a short video^ its not super annoying but probably should be fixed fast - Can be used as an empty slot and can use any one of the sets even when in que for ranked etc

**Comment by Kaelang** [comment]
Closing and merging with a more detailed report of this issue https://github.com/WarEmu/WarBugs/issues/15857.
