### ISSUE TITLE
[NPC] [GUARD] Chapter 16 elf in Eataine missing one level 55 champ

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#15832]
**Expected behavior and actual behavior:**

All perimeter should be guarded by 55 champs, but apparently one of them in this chapter is a lvl39 normal mob.

**Steps to reproduce the problem:**

Target the NPC that can be seen in the scrrenshot.

**Testing Screenshots/Videos/Evidences (always needed):**
![Lambrusco_002](https://user-images.githubusercontent.com/50114048/75579470-d3cb5d00-5a5d-11ea-89dd-42e326794d31.jpg)
![Lambrusco_001](https://user-images.githubusercontent.com/50114048/75579479-d5952080-5a5d-11ea-82aa-5cfafe9ce042.jpg)

**Comment by Lheana** [comment]
This should have been fixed with the patch of today.
