### ISSUE TITLE
Bug with T1 Elf epic quest

### ISSUE THREAD

**Issue by nitrez** [WarEmu/WarBugs#15830]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by nitrez** [comment]
Ok - evidently I just couldn't do the Everstar lake memory stone first - had to do the flamescale first and then the everstar became interact-able. May want to look into it.

**Comment by Lheana** [comment]
Fyi it works as intended.
