### ISSUE TITLE
Oil on enemy keep

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#15838]
can spawn oil on enemy keeps

![Nooblit_039](https://user-images.githubusercontent.com/44329952/75602003-bb236d00-5a86-11ea-9ba4-30bd7ec738d4.jpg)

**Comment by Ootootoo** [comment]
It's your realm keep: The keeps are randomized in every zone reset, and in this instance the dwarf-looking keep was awarded to destro while the ork-looking keep was awarded to order. May happen otherwise too.

**Comment by Kaelang** [comment]
No longer happens on live. Please re-open if issue persists.
