### ISSUE TITLE
[ITEM] [DoK] Shrouded Greencloak avaliable to equipt in DoK

### ISSUE THREAD

**Issue by Ootootoo** [WarEmu/WarBugs#15833]
**Expected behavior and actual behavior:**

DoK doesn't use the intelligence stat, and this cape should not allow DoKs to use it.

**Steps to reproduce the problem:**

Use the item shoted in a DoK.

**Testing Screenshots/Videos/Evidences (always needed):**
![Tropica_005](https://user-images.githubusercontent.com/50114048/75579699-518f6880-5a5e-11ea-935d-ed758aecfd7a.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch
