### ISSUE TITLE
Faction Guards wearing incorrect Uniform colors

### ISSUE THREAD

**Issue by Krumlok** [WarEmu/WarBugs#1583]
![bug](https://cloud.githubusercontent.com/assets/14275335/10267664/235489d8-6a9d-11e5-9a66-dc4693396a4e.png)

![bug2](https://cloud.githubusercontent.com/assets/14275335/10267666/452c929e-6a9d-11e5-947e-bac5dcb12bdf.png)

![bug3](https://cloud.githubusercontent.com/assets/14275335/10267684/1eafd544-6a9e-11e5-8d45-add6b8600a43.png)

Not sure if this is only happening to me, but I don't see the reglamentary Faction uniform in the Faction guards. It happens for both Destro and Order. 
In Order's case, instead of the usual BLUE, (Imperial), their uniforms are dyed red. (Reikland strikes back?)  You can see how the elf uniform is dyed on the photo. I don't know about dwarves.
In Destruction's case, instead of the usual BLACK (Chaos), their uniforms are dyed blue. I don't know about Orcs or Druchii.

**Comment by nalgol** [comment]
this are the correct colors i added them the last patch all those colors are from packet sniffs and should be right 

aka chaos is tzeentch aka blue go in ic into the arena there you find paquechosen in green armor for nurgle

**Comment by Krumlok** [comment]
Are you sure, Nalg? I mean, they don't make any logical sense Lorewise. Or ingame.

I have seen Druchii. They are wearing red too, which is kinda...rare. House Ulthorin's color is Purple.

High elves wearing red and blue...well..hm...doesn't make sense lorewise at all.
Imperial Soldiers, well, you could say...yeah, if they were from Reikland (Red/white uniform). But the Empire army represented ingame is the Order of the Griffon, aka blue. So..no.

**Comment by nalgol** [comment]
well i can just tell you i got the info from packt sniffs

**Comment by Reggaewaldo** [comment]
The high elf warden colors are wrong, I know that memory about the ingame NPC and lorewise.

The Packets are probably correct but out values might not match live e.g. live color 5 = white, our color 5 = purple or something along the lines of that.

Do we have any printscreen to back up the colors and i can change em back to what they should be ?

**Comment by Krumlok** [comment]
Well Reggae, I don't have any screen before the color change, but i'm 100% sure that the High Elf Warden is wearing the standard SM lvl 13-19 PvP gear (conquest). So it's the white / blue of Saphery.
Then there's the BO Elf Sergeant which is wearing SM sentry gear(lvl 25).

I'm 95% sure that the colors are wrong. And I think that what happened is what Reggae just said: different color values.  It must be that.

Regarding the Imp soldiers: the correct color is shown in this vid (skip to minute 2:45) -it's the Griffon blue-
https://www.youtube.com/watch?v=MYh8LzIK5KQ

**Comment by Reggaewaldo** [comment]
Thanks for the extensive info! I will have a look and make the changes if possible.

**Comment by nalgol** [comment]
changes would be to the db team then i just enabled that we can use colors

**Comment by Reggaewaldo** [comment]
Yes exactly Nalgol, I will see if I can make the tests on dev server tonight.

Well done on enabling the colors btw.

**Comment by Meralors** [comment]
Fixed those npc colors. If anyone find more please post their name and what their normal color should be.
