### ISSUE TITLE
[Bastion Stair] "The Bastion Stairs" quest missing quest text and particulars text

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#15836]
**Expected behavior and actual behavior:**

Story section just says "Text here".
Particulars section just says "Particulars here".
Requirements section is fine.

Please note I noticed this on 13th Feb (screenshot is from that date) but forgot to bug report it at the time so apologies if this has since been fixed.

**Steps to reproduce the problem:**

Take the repeatable quest "The Bastion Stairs"

**Testing Screenshots/Videos/Evidences (always needed):**

![quest](https://user-images.githubusercontent.com/60266177/75589928-07b17d00-5a74-11ea-8dbd-ef10824500c5.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch
