### ISSUE TITLE
Able to use toughness and willpower pots at the same time

### ISSUE THREAD

**Issue by Zealote** [WarEmu/WarBugs#1584]
You couldn't use any of the 'core' stat potions, including toughness, together afaik.

![wp tough pots](https://cloud.githubusercontent.com/assets/10598420/10267741/08b1876a-6a99-11e5-93e1-9665afa0c2b6.png)

I briefly tried to use str/bal ones at the same time, as well as spirit/corp resistance ones but it (rightly) didn't work; I don't have any tough ones to try though unfortunately. Don't know if it's a general issue with tough pots, i.e., you can always use them with str/int/bal ones, or if there's a specific bug that let's you do it.

**Comment by nalgol** [comment]
thoughness is on a seperated timer somehow i used those from packet sniffs

**Comment by Zealote** [comment]
Does that mean it's impossible for it to be wrong if it's from the packets? As I remember it, ppl usually used two pots at a time, armor + offensive stat/wp or armor + tough. 3 or more pots was usually lini + armor + stuff like zephyr tonic (and whatever else I've forgotten). I def don't remember being able to use, e.g.,  str/tough/armor; could be mistaken obviously but I'd be really surprised tbh :P

**Comment by Evildoor** [comment]
My memory says the same thing as @Zealote . It was armor(or sometimes one of the resistances) + stat potion.

**Comment by ozarmidrashim** [comment]
The available potion buffs will now be grouped as Heal / Core Stat Buffer / Armor/Resist buffer.
