### ISSUE TITLE
invisble oil in Ghrond's Sacristy

### ISSUE THREAD

**Issue by Bregual** [WarEmu/WarBugs#15850]
oil is killing players without being spawned or visible on the inner keep. outer keep oil was up and manned but players at the inner door were dying. not sure if this was from the outer door oil or from invisible oil on the inner keep. time was 10:17 mountain time if that helps.

**Comment by Bregual** [comment]
the issue happend a second time this time the outer oil and inner oil were down but players were killed by burning oil

**Comment by raptrr** [comment]
We need more information about that issue.
Which keep, which faction, screenshots and stuff. Please provide this.

**Comment by Bregual** [comment]
it was just ghronds sacristy now it is also charon's keep in chaos waists. im only noticing it when playing order. i haven't run into invisible oil on destro side as of yet. as far as a picture im not sure what to screen shot i will try to get a shot of the oil not being there next time it happens

**Comment by Bregual** [comment]
It appears to happen most often when the oil is being spawned for the first time on any given wall. for charon's keep the outer oil was invisible the first time that it was spawned but visible after. the inner oil was also invisible on first spawn but not on any others.

in Ghrond's Sacristy it was invisible on sever occasions through out the fight so im not sure if it is first spawn only or keep specific

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/15849
