### ISSUE TITLE
Can not log in after crush

### ISSUE THREAD

**Issue by Khazgoroth** [WarEmu/WarBugs#15854]
Hi,

Last night during IC event I got a crash. Tried to relogg again but I realized the following problem.
Every time when I cliscreen is freezes and every time I see the picture what I send you attached on the 2nd screenshot. 

While I'm on the loading screen i used 2 times the old /stuck trick but nothing. 

I can log in with my other characters except this one. This /stuck command is working very well with my other characters except this one. 

While I'm on this freezed screen i can click on the other options: settings, servers, quit etc-etc. Every time when I restart launcher the screen freezes.

It started about 20 hours ago.

Waiting for your reply.

Br, 

Gharros Hellscream

![screenshot_001](https://user-images.githubusercontent.com/61706891/75705135-0d4cd400-5cbb-11ea-8a9a-17c5732495d9.jpg)
![screenshot_000](https://user-images.githubusercontent.com/61706891/75705727-433e8800-5cbc-11ea-82f4-f0e098d635cf.jpg)

**Comment by raptrr** [comment]
How many times did you retry? There are some issues, where you have to retry quite often.
Was the siege still running when you crashed or was it finished?

**Comment by Khazgoroth** [comment]
Hi raptrr,

I tried it approximately 20-25 times to relogg with my Choppa. I crashed during the city siege, in stage 3.

**Comment by MaxHayman** [comment]
Should be fixed. please reopen if not.
