### ISSUE TITLE
quest: "Allure of rage". Incorrect quest marker on map

### ISSUE THREAD

**Issue by Vicgrim** [WarEmu/WarBugs#15855]
**Expected behavior and actual behavior:**
Quest marker dont show correct quest mobs location.  it's a Tempest Horn PQ mobs.
 **Testing Screenshots/Videos/Evidences (always needed):**
 
![Vicgrimm_010](https://user-images.githubusercontent.com/51807854/75711597-bacde080-5cd7-11ea-8ea8-b41b39bb4595.jpg)
 
![alure](https://user-images.githubusercontent.com/51807854/75712303-c66dd700-5cd8-11ea-9b1a-bc451d632bad.jpg)

**Comment by Lheana** [comment]
Thanks for the report, this will be fixed with next patch.
