### ISSUE TITLE
Tome of Knowledge:  killcount bug "Twisted Marshfangs"

### ISSUE THREAD

**Issue by Vicgrim** [WarEmu/WarBugs#15866]
**Expected behavior and actual behavior:**
 wolves "Twisted Marshfang" (Troll Country) count as giant spiders and wolves in the kill counter. It`is not serious but still.

**Steps to reproduce the problem:**
**Testing Screenshots/Videos/Evidences (always needed):**
 
 https://youtu.be/A8Jdla24iHE

**Comment by Lheana** [comment]
The Twisted Marshfangs don't count as both spiders and wolves, you have just killed different NPCs, including Marshfang Howlers who correctly count as wolves.
The Twisted Marshfangs in Troll Country will correctly count as wolves. The ones found in Marshes of Madness will correctly be spiders and count as it.
