### ISSUE TITLE
LOTD content in game

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#15860]
**Expected behavior and actual behavior:**
Land of the dead is not yet released and there is npc that show content for land of the dead 

**Steps to reproduce the problem:**

talk to the NPC

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/42385505/75731464-c1bd1900-5d00-11ea-8889-0984cb82fb17.png)
****

**Comment by bosli42** [comment]
The same popup happens on the Expedition Quartermasters outside of city when siege happens, while the ones inside city when not sieged are regular flight masters.
