### ISSUE TITLE
Oppressor 4th Set Bonus - Zealot

### ISSUE THREAD

**Issue by Hyronen** [WarEmu/WarBugs#15862]
Hello,

So the 4th set bonus for zealot is Endure, increase initiative by 110 while getting hit, its actually increasing it only by 60 initiative instead.

https://imgur.com/a/UWr9DNA

**Comment by RoR-Zomega** [comment]
Your buffs are showing the purple circle of "Mark of the Spell Destroyer" which increases your initiative. The two buffs won't stack. It looks like you were already receiving +50 init when you did the test.

**Comment by raptrr** [comment]
Like @RoR-Zomega already mentioned: these buffs wont stack with eachother.
