### ISSUE TITLE
NPCs on the kill plane in the Inevitable City

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#15869]
**Expected behavior and actual behavior:**

Some random daemon NPCs have been misplaced in the Inevitable City and are sitting on the kill plane (i.e. the thing that kills you when you fall off the map) in the middle of nowhere. Map coordinates are approx 36k x 30k.

**Steps to reproduce the problem:**

Go to coordinates 36k x 30k (between the arena and Viper's Pit) and go to the very bottom of the zone "under" the map.

**Testing Screenshots/Videos/Evidences (always needed):**

Location:

![Zomega_071](https://user-images.githubusercontent.com/60266177/75842293-d3b5bf00-5dc7-11ea-8d3f-6ea9c08e3581.jpg)

Screamer and horror daemon NPCs:

![daemons](https://user-images.githubusercontent.com/60266177/75842361-f942c880-5dc7-11ea-8a33-188f5783bf7d.jpg)

**Comment by Rockalypse** [comment]
looks like it is no longer there
