### ISSUE TITLE
Dok sovereign of souldrinker (chalice set) incorrect set bonuses

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#15864]
reporting this since some bonuses are incorrect for the chalice set and it has not been fixed like other sov atm.

4th piece bonus - it say + 15% critical dmg taken instead "reduces" or "minus" or being another set bonus

7th piece bonus - on block restore ap (this is a set bonus for the "shield set" and should not be here at all ) most  likely as all other healer set it should be a rec proc like "recover 30 meccanic " or so  chance to proc on heal or direct hit.

8th piece bonus -  cannot be check if not wearing all set but it should be check if is the correct one aswell at this point.

**Comment by SilverWF** [comment]
Similar for Order healers  #15649

**Comment by Lheana** [comment]
This has been fixed with the patch of 21/03/2020.
