### ISSUE TITLE
city siege double Queue/ double Instance/ double contrybution

### ISSUE THREAD

**Issue by Gunlingers** [WarEmu/WarBugs#15861]
Today after the server restart and the following city siege, we tried to queue as 2 separate guild groups. Both group leaders ran into the Portal to start the queue. As we waited for an instance to pop up, time went on and on and soon all other players waiting there disappeared. We then made one of the groups to a WB and invited the ones from the other group. We opened the WB and went into the 
portal again to queue as a WB with 3 full groups then.

Inside Instance 15 we started to switch groups and gather at emperor’s circle to buff. While we waited, the Group 1 that formed the initial WB got a second Instance Pop and 5 players clicked to join, in the believe that it would just make the popup disappear. 
The whole group got instantly ported into Instance 16. The Instance was then 24vs24+5
The +5 Players got bugged out groups, showing the Instance 15 groups in group window.
And the Instance 15 Players on the map. The +5 group in Instance 16 were still in Step 1, when
Instance 15 lost Step 1. And suddenly the +5 group in Instance 16 got the army recall buff, the loot roll and Bags from Instance 5. After Step 1 of Instance 16, the +5 group also got the loot roll
and Bags from Instance 16.

It seems like a Queue as a Group will not be terminated when switching the Group into a WB and queueing again. 

Expected behavior and actual behavior: Queue as a group should be canceled when forming a Warband and queueing again.

Steps to reproduce the problem:
- Build 2 separate groups
- Queue both for City siege at the same time
- From one of the groups into a Warband and invite everyone from the other group
- Start a new Queue as the Leader of the Warband (who queued the group before)
- Inside the city siege click to join, if a second City pop appears

**Testing Screenshots/Videos/Evidences (always needed):
sadly, no screenshots were taken doe to the chaotic situation in game and in voice.

**Comment by dalen** [comment]
Seems to be similar to https://github.com/WarEmu/WarBugs/issues/15847
