### ISSUE TITLE
Players with "dead" animation

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#1586]
Today i've noticed that some players are moving/fighting/etc while being displayed as lying dead on the floor. I'm pretty sure that this has nothing to do with https://github.com/WarEmu/WarBugs/issues/1312, since i've observed this issue in T1 scenarios with no knockdown effects.

**Comment by Reggaewaldo** [comment]
This issue surfaced after the recent server crashes. Confirmed in T2 scenarios during early hours (05 - 07 AM).
