### ISSUE TITLE
Camera Zoom/Mouse Scroll

### ISSUE THREAD

**Issue by olisteph90** [WarEmu/WarBugs#15863]
The mouse scroll either zooms me all the way in, or zooms me all the way out. Same for chat, or any other kind of menu that requires scrolling; it either scrolls all the way to the top, or all the way down. If I want it to stop at a certain point it does not stop, instead it automatically jumps back down or up depending on where I started from. This has made it impossible to set up the camera, or to look at and change certain settings in the in game menus.

**Comment by SilverWF** [comment]
Maybe it's related to your mouse wheel settings? Like "scroll 1-2 pages" etc

**Comment by raptrr** [comment]
Does this also happen when scrolling the menu / settings?
Seems like its related to you mouse and not the game itself
