### ISSUE TITLE
[Fortress] Population caps break after mass disconnect?

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#15875]
**Expected behavior and actual behavior:**

During the defense of Butcher's Pass on 29th February 2020 at 19:18 GMT a lot of players (almost everyone?) disconnected. As players logged back in, those who did not previously have a reservation for the fort were allowed in as the population numbers in the fort were still very low. However, the players previously in the fort when they disconnected were able to log back in and remain in the fort along with all the people who had just gained an invite.

Expected behaviour: if you disconnect during a fort siege then there should be a short-ish grace period where your reservation remains valid and only you can take up that slot. After that grace period expires the reservation is offered to another player and if you then log back in you are teleported out of the fortress fight.

Note that when I was a player who was able to get into the fort after disconnecting and I didn't have a reservation before (I was stuck outside). I got a debug error message as well as a reservation usage message (in screenshots).

edit: this was "confirmed" by having people on voice comms who had reservations prior to the disconnect be able to log back into the fort and participate after the mass DC well after it had filled up and a queue was forming again to enter the fort.

**Steps to reproduce the problem:**

1) Fill fortress with players
2) Disconnect half of them
3) Have new players enter the fortress now the population is under max
4) Have the disconnected players log back in. They are also able to participate in the fortress.

**Testing Screenshots/Videos/Evidences (always needed):**

Gained a reservation and debug error message upon successfully entering the fort from the rear entrance after the mass disconnect:

![fort](https://user-images.githubusercontent.com/60266177/75854875-00c69980-5de9-11ea-8333-ae4e9d11b023.jpg)

**Comment by Kaelang** [comment]
The 27/05 patch has addressed some contribution issues / porting issues with forts. Please re-open if this is issue persists.
