### ISSUE TITLE
Full T4 Empire Influence - Item "Circlet of the First" (Helm lvl38) cannot be claimed

### ISSUE THREAD

**Issue by Irunae** [WarEmu/WarBugs#15877]
Hello,

On my character Irina, an order Archmage, I have my full T4 Empire influence but I cannot claim for the item named "Circlet of the Fist", an Helmet lvl 38.

I asked help from a GM who could not help me. He killed the NPC and also did some checks.
But I still cannot claim the item even if I have T4 full influence. Any T4 influence rally NPC work for me.

My account name is Conta if it helps you to identify my account.

Thank you for your help.
Best regards,
Irina

**Comment by Lheana** [comment]
I tested it and I could take the Circlet of the Fist. Please provide screenshots.

**Comment by Irunae** [comment]
Hello, please find a screenshot herewith. I can't take any of the influence items:

![image](https://user-images.githubusercontent.com/61795541/77309358-cde33780-6cfc-11ea-9629-a094d773d312.png)

**Comment by Lheana** [comment]
Please provide a screenshot where you have your mouse on your influence bar like:
![Lheana_137](https://user-images.githubusercontent.com/11537611/77309697-65e12100-6cfd-11ea-8bb7-966b85f32a57.jpg)

**Comment by Irunae** [comment]
Hi,
You can find below the screenshot

![image](https://user-images.githubusercontent.com/61795541/77416938-e454c600-6dc4-11ea-9bcd-e5f4860332d2.png)

**Comment by Lheana** [comment]
That's not what I asked, Please send a screenshot **with your mouse ON your influence bar in your Tome of Knowledge**. The reason is that you must have already taken the advanced reward for ORvR T4 Empire VS Chaos.

**Comment by Lheana** [comment]
Exceptionally, I checked the live DB, and the live DB says you have already claimed the basic, advanced and elite influence rewards of ORvR T4 Empire VS Chaos. So no game issue here.
And before you ask, if you have deleted or sold your influence reward, you won't recover it.
