### ISSUE TITLE
BattleField Objective NullReferenceException system message

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#15878]
destro forces attacked order keep in praag at around 18;00 cet
suddently chat was flooded by a system message
![Agilulfo_005](https://user-images.githubusercontent.com/17765890/75904302-3ac48980-5e43-11ea-89df-89aa3d71dc01.jpg)
i think that the spam ended when defenders destroyed the ram but, sadly, i cannot confirm that.

**Comment by dalen** [comment]
This has been fixed now.
