### ISSUE TITLE
[Apothecary] Potion bug

### ISSUE THREAD

**Issue by bozzax** [WarEmu/WarBugs#1588]
You can add 3x stabilisers from a 4 stack and use it for a 20 stack. First potion reduces the 4 stack to 1 but the Apothecary window has 3 slots filled. The remaining 19 don't use stabilisers

**Comment by satexas** [comment]
Related: Apothecary is making the incorrect pots, started within last 24 hours.

Blistered Spumepetal Seed (25, Healing) + 1 Blistered Spumepetal (25) + 2 Slimy Arboreal Resin (25) + 1 Sandy Fusk (25) is making "Draught Of Balming, level 5 425 health potion" (non crit, normal)

It SHOULD be making : "Draught of Aid, level 25, 924 health potion" (non-crit, normal)

**Comment by satexas** [comment]
Update #2 - It's possible ALL Apoth is now making wrong pot... as level 50 ingrediants are now making the same level 1 pots... "Draught of Balming".

**Comment by nalgol** [comment]
this will be fixed next update
lvl 25 ingredeances should make lvl 5 pots it was wrong before
