### ISSUE TITLE
Desecration Quest Bug

### ISSUE THREAD

**Issue by Whackadoo** [WarEmu/WarBugs#15889]
**Expected behavior and actual behavior:**
Amund's Grave is supposed to have the ancestral sword in it. But in my experience, the grave is either not respawning the sword or the grave isn't able to be interacted with at all.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
It works fine, maybe a player has interacted with the Amund's Remains before you tried.
