### ISSUE TITLE
Quest Reward bug : Restless Vengeance reward (item with incorect texture)

### ISSUE THREAD

**Issue by Vicgrim** [WarEmu/WarBugs#15884]
**Steps to reproduce the problem:**
After completing the quest "Restless Vengeance ", the player must receive gloves for his class (in my case, the marauder) but he get some "order texture gloves".  Maybe KoBS/Ironbraker or War Priest texture. 

**Testing Screenshots/Videos/Evidences (always needed):**
 
![Vicgrimm_017](https://user-images.githubusercontent.com/51807854/75929643-18059580-5e82-11ea-812e-438112008662.jpg)
and fight stanse of true warior of chaos) 
![Vicgrimm_018](https://user-images.githubusercontent.com/51807854/75929652-1e940d00-5e82-11ea-9529-98b2b7daaf84.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch
