### ISSUE TITLE
Quest Reward: Ancient Power Reborn - order boots texture on destro.

### ISSUE THREAD

**Issue by Vicgrim** [WarEmu/WarBugs#15887]
**Steps to reproduce the problem:**
For quest " ancient power reborn" chaos ch18 i got "Daemon Tramplers"  on my marauder.
Daemon Tramplers looks like KoBS bots.)
 

**Testing Screenshots/Videos/Evidences (always needed):**
 
![Vicgrimm_021](https://user-images.githubusercontent.com/51807854/75935223-b9dfaf00-5e8f-11ea-9fe1-f1d8b7b79e3d.jpg)
![Vicgrimm_020](https://user-images.githubusercontent.com/51807854/75935322-f8756980-5e8f-11ea-99c9-81ae653bc5bc.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch
