### ISSUE TITLE
preventing lockout by jumping in last sec makes everyone else fade away

### ISSUE THREAD

**Issue by Gunlingers** [WarEmu/WarBugs#15881]
Expected behavior and actual behavior: 
Normally if you jump while in the process of logging off, you stop the logout and stay in game.
However, since last week it occurs sometimes, that if the remaining time is <1, the jump will not properly prevent one from the logout process. The Player will remain in the World, but every other 
Player, NPC and interactive Objects in general will fade away. The Player is technically logged out and can no longer move items in his inventory or interact with the Mailbox etc. From that moment on a normal log out is no longer possible and the game has to be crashed to fix the situation.

Steps to reproduce the problem:
Start logging out wait till the timer reaches 1 or 0 and jump.

Testing Screenshots/Videos/Evidences (always needed):
![Grolllinger_001](https://user-images.githubusercontent.com/54162117/75922358-22fcfd80-5e63-11ea-81f0-ea54acc25a7c.jpg)

All NPCs gone.

**Comment by dalen** [comment]
This has been patched in a hotfix.
