### ISSUE TITLE
Public Quests:  Sundered Fortress Hard Public Quest Chaos Chapter 17 bug

### ISSUE THREAD

**Issue by Vicgrim** [WarEmu/WarBugs#15882]
**Expected behavior and actual behavior:**
Sundered Fortress Hard Public Quest Chaos Chapter 17
On stage 2 player need to destroy mortars. But they cannot be destroyed.  
**Steps to reproduce the problem:**
Got to Public Quests: Sundered Fortress Hard Public Quest Chaos Chapter 17 and kill mobs to activate stage 2. On stage 2 you cannot to destroy mortars.
detail in the video below

**Testing Screenshots/Videos/Evidences (always needed):**
https://youtu.be/iuunHXA97ss

**Comment by Kabucoror** [comment]
fixed with next patch
