### ISSUE TITLE
cannot join a WB Player name is not showing

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#15893]
**Expected behavior and actual behavior:**

when u press the open parties and Warbands windows you shoud be able to see the open group and join them but this time the guy had no name and rank is 0 first time i see this i also clicked on join many time nothing happened

**Steps to reproduce the problem:**

![image](https://user-images.githubusercontent.com/42385505/76005316-e3461c80-5f1b-11ea-9d7e-eb0bca1d54de.png)

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by gittoaster** [comment]
For me (Order) I am not seeing any warbands at all on in this GUI
![wb missing](https://user-images.githubusercontent.com/7898608/76130918-4f2e9080-5fc1-11ea-8de7-291dec199075.jpg)
or white shown here.
![warb](https://user-images.githubusercontent.com/7898608/76130921-52298100-5fc1-11ea-8662-6d8e0c361042.jpg)
ty

**Comment by gittoaster** [comment]
I'll suggest that perhaps that person is on your ignore list?  therefore working correctly?  Just a

**Comment by gittoaster** [comment]
When I was warband leader I noticed I became "0" when looking at my own warband, then soon as I left, everything seemed to be showing up again.
![zero](https://user-images.githubusercontent.com/7898608/76479320-9d300380-63c8-11ea-8dcf-22b46e803a80.jpg)

**Comment by MaxHayman** [comment]
Fixed with next hotfix.
