### ISSUE TITLE
Beastlord hunt: Slayers bugged

### ISSUE THREAD

**Issue by sn3jk** [WarEmu/WarBugs#15894]
I have not noticed an exact copy of my issue, however ive seen multiple cases that have been similar.

**Expected behavior:**
Turn in quest and get the Beastlord Token. 
Note: My friend turned in the kill boss quest for snizzort and he got another variant. He is Black ork and his quest was "Beastlord hunt: Engineer", not Slayer.
Maybe its different for different classes?
 
**and actual behavior:**
Had the quest completed but couldnt turn it in at npc. no gray or orange quest (npc name Boldug). I tried relog/reload but nothing. I tried to abandon quest and now i cant pick any quest up.
Note: I first completed the snizzort quest back in fall/winter 2018. I also picked up the follow up in that timeperiod. I am not sure if i hade the quest completed back then or if i completed it the last couple of days, this might be causing some problems?

**Steps to reproduce the problem:**
Maybe not reproduce exactly, but i was able to turn in the ursa quest and pick up the followup (the ursa quest i also picked up 2018.
I was also able to turn in the one in CW (npc brolgr). This quest was also picked up in 2018. I am however not sure if it was completed back then or now, same as above.

**Testing Screenshots/Videos/Evidences (always needed):**
![beastlord missing token](https://user-images.githubusercontent.com/16905775/76007891-0f0ed580-5f0f-11ea-9b75-cd6554e7b0c1.jpg)
![Beastlord questgiver](https://user-images.githubusercontent.com/16905775/76007896-1209c600-5f0f-11ea-947b-10fbcd3bf5c0.jpg)

**Comment by Kabucoror** [comment]
The Slayer version was from the previous Bestlord quests some years ago. BL Hunt: Snizzort is the actual one with Engineers as follow up. So you have already done this probably.
