### ISSUE TITLE
[BW] Sov Inferno 7piece bonus not working

### ISSUE THREAD

**Issue by BomblingTV** [WarEmu/WarBugs#15891]
Hello,

The 7piece setbonus doesnt seem to be functioning, or atleast not show the icon above the target when applied (i didnt test damage numbers I only looked for the icon)
https://imgur.com/a/GsoF2Yq

After beating on the dummies for about 20minuts and not getting a single proc. I desited to slap on the old Overlord set to confirm if the proctype was still only when you have a target selected. And the overlord proc worked when i used Directdamage spells such as "Sear, Nova, Meltdown, Burning Iron, Fireball etc"
But not on abilities such as "Scorched Earth, Annihilate" eventhough I checked all of the dummies after a full channel, and I made sure to have my primery dummy targted during the test.

Conclusion: The offensive sov 7piece bonus is not showing the icon above targets when/if it procs and might not be working at all.
The overlord 2piece set with simular conditions only proc on whoever you have targeted, and only on Direct damage spells and not AoE or channelspells, not even when you keep the target targeted.

I assume all procs on the new Royal sets with this type of wording might be affected.

**Comment by BomblingTV** [comment]
Update: our guildie now has the full set, and tested the Granted 8piece ability. it reads "10% increase radius" is this correct? 10% out of 30feet(33feet total) is barely noticable after testing it on neutral mobs and dummies. and will not be a bonus worth breaking Gear mixing to obtain.

**Comment by BomblingTV** [comment]
So after latest patch and some changes to the HealerArchtype sets, I went back and tested on the dummies once again. Either untill I got a 7piece proc or after 100 hits on the dummy with each ability:

-Sear: works
-Nova: works
-Fireball: works
-Meltdown (morale damage): Didnt work

-Choking Smoke aoe silence: Worked by only on the dummy i had targeted not on affected aoetarget
-Feiryblast: Worked by only on the dummy i had targeted not on affected aoetarget
-Fireball Barrage: Worked by only on the dummy i had targeted not on affected aoetarget

-Scorched Earth: Didnt work not even on dummy I had targeted
-Flamebreath: Didnt work not even on dummy I had targeted
-Annihilate:  Didnt work not even on dummy I had targeted
-Rain of Fire:  Didnt work not even on dummy I had targeted

**Comment by grunbag** [comment]
it works on direct damage not aoe damage
