### ISSUE TITLE
Crashing/getting kicked out of scenario during load screen into a weird in-game character selection menu

### ISSUE THREAD

**Issue by Nefarian78** [WarEmu/WarBugs#15899]
**Expected behavior and actual behavior:**

Game either kicks or crashes during the loading screen for scenarios and leads to a weird bug. It always results in a deserter penalty.

**Steps to reproduce the problem:**

Unknown. Started happening randomly since City Siege patch was dropped. It's happening more often lately,  at least once every 10 scenarios.

**Testing Screenshots/Videos/Evidences (always needed):**

![gamecrash](https://user-images.githubusercontent.com/23102638/76088406-4b4a4080-5fb8-11ea-8ef7-beca78197057.JPG)

**Comment by bosli42** [comment]
I can confirm this, happened to a handful of players I know and myself. It usually occurs when the game disconnects you on loading screen and wants to throw you into character selection, but at the same time was done loading the zone. You are able to walk around, but the normal game UI won't show up, you can't use any of the main menu buttons on screen and have to crash the game.

**Comment by Kaelang** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/12576.
