### ISSUE TITLE
City Siege Champ

### ISSUE THREAD

**Issue by TheOGScav** [WarEmu/WarBugs#15897]
Became a Champ during a city siege with my Sorc, couldn't leave the SC, forced crash the game. Now, I can't log back in with that toon.

This was my 10ish siege, can't tell if it is due to the fact I became a champ or something else (1st time champ).

https://www.youtube.com/watch?v=sUS1AGoPz5I&feature=youtu.be

PS:  https://www.youtube.com/watch?v=gCJte10wGBU&feature=youtu.be

PS2:  I was able to log back in only after the server restarted.

**Comment by MaxHayman** [comment]
Should be fixed. Reopen if not.

**Comment by TheOGScav** [comment]
TY, Max.
