### ISSUE TITLE
Chicken problem

### ISSUE THREAD

**Issue by Aesphodel** [WarEmu/WarBugs#15905]
I'm turned into chicken in Norsca and Nordland while outside of ORvR zone
![Mazile_000](https://user-images.githubusercontent.com/61890210/76125721-752e5200-600e-11ea-9ae7-a577cc8f7118.jpg)

**Comment by raptrr** [comment]
Also can happend if you get flagged for RvR somehow. Did you interact with some T1 player?

**Comment by RoR-Zomega** [comment]
The red RvR flag icon is by his player portrait.

**Comment by raptrr** [comment]
Indeed it is.
Lets wait for his answer tho.

**Comment by MaxHayman** [comment]
Fixed
