### ISSUE TITLE
Downconversion from Officer's to Soldier's Emblems has a renown cost higher than anything you can buy with Soldier's Emblems

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#15906]
**Expected behavior and actual behavior:**
The item [Satchel of Soldier's Emblems] should be purchaseable by players still needing items from Soldier's Emblems. However, it currently requires RR30 to use, making it impossible to downconvert higher emblem drops until you're already overleveled for the gear. 

Same issue applies to Satchel of Soldier's Medallions. 

**Steps to reproduce the problem:**
Buy the item with a character below RR30
![Cruzealot_004](https://user-images.githubusercontent.com/1183293/76126906-a6078a80-6000-11ea-84ca-d56a557c7041.jpg)

**Testing Screenshots/Videos/Evidences (always needed):**
![Cruzealot_004](https://user-images.githubusercontent.com/1183293/76126906-a6078a80-6000-11ea-84ca-d56a557c7041.jpg)

**Comment by Kaelang** [comment]
Devastator gear gives level 29 gear. You're not 'overlevelled' by needing 30 to downgrade your tokens.

This is working as intended and has the same design as all other gear.
