### ISSUE TITLE
Knight of the Blazing Sun aura bug + workaround

### ISSUE THREAD

**Issue by WellmadeKnight** [WarEmu/WarBugs#15901]
Pre-level 40 KotBS aura bug issue.

**Expected behavior and actual behavior:**
Knight auras should be usable at any point in time but will become disabled for future use upon leaving scenario's. I am assuming the cause to be bolstering as this is the only place I have experienced the issue.

**Steps to reproduce the problem:**
Upon leaving any scenario with auras toggled on, they will become disabled and can no longer be used, this continues into future scenario's and any other type of content.
rather than re-logging which many players have suggested which can be tedious after some time, toggling all auras off during the scenario scoreboard screen at the end of a match **BEFORE** you leave will prevent them from becoming bugged.
You will have to repeat this at the end of each scenario.

**Comment by dalen** [comment]
you can just toggle them twice afterwards to turn them on again. No need to relog.
