### ISSUE TITLE
Warlord Carapace not healing

### ISSUE THREAD

**Issue by Skullgrin** [WarEmu/WarBugs#15909]
The Warlord Carapace for Chosen is supposed to heal you for 80 points of health every 4 seconds. It is not healing at all. To test this I equipped the Piece of armor and attacked the champion beastman in IC. as the followings screenshot shows, no healing was done by the armor over about 30 seconds.

![Thargrimm_304](https://user-images.githubusercontent.com/40448982/76137170-fe398f00-5ff6-11ea-9707-f21ebafbfe14.jpg)

To Replicate this simply put on the armor and try it yourself.

Edit: Just checked .getstats and it is showing up there as HealthRegen 20 , it just doesn't seem to be working properly.

![Thargrimm_312](https://user-images.githubusercontent.com/40448982/76137330-d2b7a400-5ff8-11ea-81f2-2a745888e610.jpg)

**Comment by Iamwithstupid** [comment]
20 is a correct value (per 1 second)
hp regen will not show as heal in combat log.
it is working, watch ur healthbar for changes
working on my black orc.

**Comment by Kaelang** [comment]
HP Regen isn't calculated as heals for the Combat Log. As per above comment, this looks to be working. Please re-open if you are able to highlight further evidence to support this item has a problem.

Thanks.
