### ISSUE TITLE
Spells cast through jail barrier

### ISSUE THREAD

**Issue by colintgallagher** [WarEmu/WarBugs#15907]
Not sure if it applies to other classes, but certain Magus spells can be cast through the barrier in jails and damage players, both ways. 
![Sarnai_054](https://user-images.githubusercontent.com/56422919/76135274-60909080-5ff3-11ea-935f-7b41b19183c0.jpg)

![Sarnai_058](https://user-images.githubusercontent.com/56422919/76135287-8322a980-5ff3-11ea-9259-ed5e4f3ec0f5.jpg)

**Comment by Kaelang** [comment]
Players are now, correctly, unable to attack from within, and damage from outside. 

Please re-open if issue persists.
