### ISSUE TITLE
Tactics reset everytime I log onto my tank

### ISSUE THREAD

**Issue by Syracus84** [WarEmu/WarBugs#15917]
So i got this issue like 2 weeks now. Everytime when i log onto my Tank (Ragdor) the Tactics are always reset. Means that the tactic slots are empty. I have to click on tactic Slot 1 so they are filled again everytime.

On the other Characters everythings fine. It's only my tank that has the Issue.

Edit:
Even my Hotbars change back how it was before when I change the rows between 1 and 5.

**Comment by DypfrystBram** [comment]
If you need a bigger reason to jump on this one and fix it - you can basically use this bug to have access to any tactic setup even if you are in ranked scs

**Comment by raptrr** [comment]
Duplicate of https://github.com/WarEmu/WarBugs/issues/15839

**Comment by DypfrystBram** [comment]
[https://youtu.be/Fsi0_CqMaiM](url)
