### ISSUE TITLE
Komnor Bronzemug gives infinite influence

### ISSUE THREAD

**Issue by Geisthund83** [WarEmu/WarBugs#15910]
![Waaghndaz_000](https://user-images.githubusercontent.com/55026914/76137982-e2db7d80-6010-11ea-9ba7-07c6f71f6a71.jpg)

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

Clicking his corpse repeatedly gives you infinite/max influence

**Comment by Lheana** [comment]
From what I understand, this is the same issue as #15885
