### ISSUE TITLE
No warbands shown in interface

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#15912]
**Expected behavior and actual behavior:**
expected - player can login and see open warbands to join in GUI
actual - while in Caledor as Order no warbands can be seen, or searched.
This happened before Mar 07 patch and after it.  Seemed to start last week sometime

**Steps to reproduce the problem:**
login to Caledor or perhaps Elf as order and try to join open warband

edit - I noticed that before the patch I could still search for warbands, today I cannot.

**Testing Screenshots/Videos/Evidences (always needed):**
![wb missing](https://user-images.githubusercontent.com/7898608/76145516-e4bc3580-603e-11ea-94ea-c2ca583b085c.jpg)
![wb missing](https://user-images.githubusercontent.com/7898608/76145519-e84fbc80-603e-11ea-8059-85e9545553be.jpg)

**Comment by gittoaster** [comment]
Current work around is to use the search feature to try and narrow and see if that works.
![search](https://user-images.githubusercontent.com/7898608/76169285-d4d24d80-6133-11ea-8eb3-4f1d799c4481.png)

**Comment by MaxHayman** [comment]
Fixed with next hotfix.
