### ISSUE TITLE
Public Quest: Wrong loot in Chapter 7 PQs gold bags for Ironbreaker

### ISSUE THREAD

**Issue by Cr3nshaw** [WarEmu/WarBugs#15915]
Chapter 7 PQs in Shadowlands and Barak Varr have wrong loot in gold bags. Played as ironbreaker and got chaos 2h axe twice and 1h orc axe once.

**Expected behavior and actual behavior:**

It should drop very rare 2h for dwarf instead of chaos.
EDIT: Also added 1h orc axe that dropped from same PQ gold bag.

**Steps to reproduce the problem:**

Complete "Bar Dawazbak" or "The Dragon Gate" PQs in Barak Varr and Shadowlands

**Testing Screenshots/Videos/Evidences (always needed):**
![Mordin_244](https://user-images.githubusercontent.com/10353875/76154068-54c9ca80-60d6-11ea-9bec-f279f5854602.jpg)
![Mordin_242](https://user-images.githubusercontent.com/10353875/76154072-5c896f00-60d6-11ea-8b34-375e7afae145.jpg)
![Mordin_246](https://user-images.githubusercontent.com/10353875/76154278-f0a90580-60d9-11ea-94fd-f30484b7c944.jpg)

**Comment by Kaelang** [comment]
A recent fix was sent to hopefully stop this from happening moving forward. Please re-open if you find the issue persists.
