### ISSUE TITLE
[Tactic] (Slayer) Fierce Might producing chat warning

### ISSUE THREAD

**Issue by Gunlingers** [WarEmu/WarBugs#15925]
[Tactic] (Slayer) Fierce Might producing system warning to player chat while doint crit dmg on low life.

Expected behavior and actual behavior:
Fierce Might increases critical bonus dmg by 10% for every 10% lost health. When at under 10% health and on critical hitting an enemy, the system seems to count the bonus crit dmg rate as
suspicius(hack induced)

Steps to reproduce the problem:
As a Slayer, Skill Fierce Might, Rune of Absorbtion and take Moral 1 Untouchable.
- attack an NPC and let him hit you down to under 10% health.
- activate Moral 1 Untouchable, to not get killed.
- use Rune of Absorbtion to do dmg and heal for dmg done
- System will give out chat warning of ''sucspiciusly high crit dmg rate of 300.xxxxx% to 400.xxxxx% 

Testing Screenshots/Videos/Evidences (always needed):
![Grolllinger_004](https://user-images.githubusercontent.com/54162117/76170388-c7dc4b00-6181-11ea-984e-63c08fb289fb.jpg)

**Comment by SilverWF** [comment]
Can confirm.
Also, warnings shows just impossible values, like 700%+ cit value, while the max possible for slayer with this tact and <10% HP would be just 250%

**Comment by SecretsOTheP** [comment]
This was patched live #19893
