### ISSUE TITLE
100+ Renownpoints Hack/Cheat under Level 10

### ISSUE THREAD

**Issue by Fearce83** [WarEmu/WarBugs#15920]
My friend used the Career Trainer while under level 10. We can not reprogress it but for some reason he is now at 130 Renownpoints and under level 10! He can also spend all these points and with that people will have a huge advantage over others. You need to check your Database if theres more people with these Amounts of Points because it was just an accident happend to him. This could happen to everyone!

**Comment by Kaelang** [comment]
Please can you provide more information, such as what led up to this happening, what the Character name is, what Class this happened on etc

**Comment by Kaelang** [comment]
No further information - closed.
