### ISSUE TITLE
Hard framedrop when entering T1 Nordland area as lvl40 after debolster

### ISSUE THREAD

**Issue by Choppabully** [WarEmu/WarBugs#15923]
**Expected behavior and actual behavior:**

A higher level player who is meeting the conditions to be debolstered during the T1 Norland event and enters the rvr area after exiting the warcamp will encounter a very hard framedrop of about 10 seconds when he is debolstered to level 15.

It happens backwards too, if you go out of rvr area and you are debolstered, once you reach the Nordland warcamp to be turned into level 40 again, you also get a very hard framedrop

**Steps to reproduce the problem:**

1) meet the conditions to be debolstered into T1 Nordland, as per event description
2) exit the warcamp from Nordland and head into rvr area
3) notice very hard framedrop

or 

1) meet the conditions to be debolstered into T1 Nordland, as per event description
2) exit the warcamp from Nordland and head into rvr area
3) get away from rvr area and return to the warcamp to be turned lvl 40 again
4) notice very hard framedrop

**Testing Screenshots/Videos/Evidences (always needed):**

I will post screenshot with the place where it happens, between warcamp and rvr area

![Choppabully_249](https://user-images.githubusercontent.com/59963650/76166497-a2424800-6167-11ea-9ec9-996ac9b5f208.jpg)

**Comment by agemennon675** [comment]
This happened to me, also any bolster I got or when bolster removed game freeze, it might be because server population

**Comment by Kaelang** [comment]
This is due to the large stat upgrade / character changes that bolster provides, it takes the client a second or two to catch up to a whole bunch of changes made in an extremely short amount of time.
