### ISSUE TITLE
No Warbands shown in Open Parties and Warbands interface

### ISSUE THREAD

**Issue by Choppabully** [WarEmu/WarBugs#15921]
**Expected behavior and actual behavior:**

expected - player can enter Open Parties and Warbands window and see open warbands to join.
actual - after the most recent server restart, no warband can be seen or searched.
Using /rel or /reload ui doesn't fix the issue.

**ALSO, if the player manages to get into a warband by manual invite to warband, he cannot see theparty windows of the warband due to this bug. Using the commands mentioned before doesn't fix the issue. If you open Open Parties and Warbands window and go to Manage window and try to manual tick on each party to make it show up, it doesn't work. This will be included in last screenshot**

**Steps to reproduce the problem:**

login in and try to join open warband
press /rel or /reload ui and notice the issue is not fixed

**Testing Screenshots/Videos/Evidences (always needed):**

![Choppabully_243](https://user-images.githubusercontent.com/59963650/76162141-4b2a7c00-6143-11ea-9e33-cc2d3de48829.jpg)
![Choppabully_244](https://user-images.githubusercontent.com/59963650/76162143-4bc31280-6143-11ea-8dc9-e47b0045e2a8.jpg)
![Choppabully_245](https://user-images.githubusercontent.com/59963650/76162192-c724c400-6143-11ea-8a32-9afd00f7052d.jpg)

**Comment by Choppabully** [comment]
Seems like the devs fixed it in 30 minutes after I posted it here so it can be closed. Everything works fine now.

**Comment by gittoaster** [comment]
duplicate report of https://github.com/WarEmu/WarBugs/issues/15912

**Comment by MaxHayman** [comment]
Fixed in next hotfix
