### ISSUE TITLE
Infinate Salvage

### ISSUE THREAD

**Issue by Grothnar** [WarEmu/WarBugs#15929]
After the server shutdown today 3/8/2020 when I logged back in an item in my inventory I went to salvage failed to be destroyed using the salvage skill but still yielded the materials and allowed me to continuously salvage the item.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by raptrr** [comment]
Please contact me on discord: theysii#4972
