### ISSUE TITLE
[Fort] Very low renown reward

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#15926]
Today Order took the Maw fort.
Me and my party has a fight at most BOs on it, made lots of kills at all stages and also attacked lord.
There was 160 order attackers and 120+ destro defenders.
When the fort was ended we got very low renown reward: I've got 1900 renown, my mates got from 3k to 7k renown.
(we all got 6 invader meds too)
This is joke, especially if remember about x2 event.
We all fought in the Chaos Wastes before fort, for a full time and got our reservation immediately after zone lock.
My character was Jerboa (WL 40/60)
Other guys was 40/70+

At fort before (Stonewatch defense) we are successfully defended it and got full renown reward btw.

**Expected behavior and actual behavior:**
Exp: get 30k*2 renown as minimum
Act: Got 10 times lower.

**Steps to reproduce the problem:**
No idea, play RVR maybe?

**Testing Screenshots/Videos/Evidences (always needed):**
Not really needed.

**Comment by Kaelang** [comment]
This should have been fixed as of 27/05/20. Please re-open if issue persists.
