### ISSUE TITLE
SW Hotbar slot one bugged

### ISSUE THREAD

**Issue by TheOGScav** [WarEmu/WarBugs#15930]
https://www.youtube.com/watch?v=xG39XqIAzjE&feature=youtu.be

Can't put any abilities in slot one, 1st bar while in Assault Stance, rest two stances work fine, only while in assault. Only Bar 1, slot 1.

PS:  Same for Mara: https://www.youtube.com/watch?v=EYh6ai--9Ks&feature=youtu.be

**Comment by dalen** [comment]
This is a bug in the addon Morale Circle, see https://www.returnofreckoning.com/forum/viewtopic.php?f=66&t=22089&p=393721&hilit=moralecircle#p376140

**Comment by TheOGScav** [comment]
TY
