### ISSUE TITLE
Butchering: Lizard Mobs

### ISSUE THREAD

**Issue by ropuch** [WarEmu/WarBugs#1593]
Hi,

This is duplicated/follow-up to already closed bug #1511 - I don't know if devs are notified with comments on "Closed" issues, so I've decided to open new one. Please close it if this duplicate is not needed.

Long story short: while butchering lizards, one quite often get non-pickable item with no icon (sshot in #1126). Shortly after bug was closed ("lizzard thoungs where missing in db"), I've noticed few things.

First: it doesn't seem like missing icon, those strange items are quite different:
For example:
Flameripper Salamander/ Fireschredder Salamander when butchered sometimes will give non-pickable items (number in [] is uniqueID field, seems like some PrimaryKey value)
[186850]Enslaved Pack Mule
[84059]Whispering Pyre Ivy Seed 
[2010868]Stompas of Conquest 
[87487]Thin Lizard Hide 
[84225]Prickly Goldweed Seed 
[157861]Draught of Allaying 
[3030073]Waxy Ichor 

Second: "randomness" of those items seems to be kinda broken, if non-pickable items show up, they come in "waves": first several [84059] in a row, then several [84225] in a row, etc. 

Cheers!
ropuch

**Comment by nalgol** [comment]
hm

well the butchering code is quite simple it checks for the subcreature type in this case 30

 case 30:
                            Rand = (byte)((float)StaticRandom.Instance.NextDouble() * 100f);

                            if (Rand < 50)
                                Gathering = 3030020;   //
                            else
                                Gathering = 3030110;   //
                            Gatheringprof = 1;
                            break;

so 50 / 50 to either get toungs or scales

**Comment by Evildoor** [comment]
FYI - people are notified of comments in closed tickets.

**Comment by ropuch** [comment]
@Evildoor: thanks, I'll remember that.
 
@nalgol:
Item 3030020 (mentioned in Gathering code) is Shattered Scale, lvl 1 scale.

I've just realised, I didn't stated exactly what mobs I'm trying to butcher.
They are 18-20 lvl Salamanders, and the proper scale from them are:
Lvl 75 scale: [3030023]Brittle Scale
Lvl 100 scale: [3030024]Worn Scale

Strange thing is now I get non-picable item with id [3030024], which makes no sense because I have several normal 30300024 Scales in my backpack.
I took full dump of both items, but they're the same (id, uniqueid, icon, name etc) - the only difference is timestamp field:

Good 75 scale:  timestamp [number]1744
Wrong 75 scale: timestamp [number]1450

Anyway, since gathering algorithm is 50/50, I'll just accept those no-icon-items as: you rolled no scale loot instead of: you should get scale, but you won't ;-)

Cheers!
ropuch

**Comment by nalgol** [comment]
nono it needs to be the lvl 1 scale ^^ i calculate the right item id from that one based on the mob lvl they followup so i just do some id + x

**Comment by ropuch** [comment]
Ok, I'm not really aware of RoR database/server code etc., just guessing ;-) All I have is data I can pull from TargetInfo/SystemData/GamaData tables and old War-Emu code/DB. I can assist in gathering data for bug solving (full table dump included), just let me know what information is required [;

Cheers!

**Comment by ropuch** [comment]
OK,

**Comment by ropuch** [comment]
Shame on me -  this "issue" is actually me relying on data, which I did not verify.
It turns out that "random-strange-unique-ID" I got were some CraftValueTip.LastItem ID, not really corresponding to actual itemData in LootBag. Sorry for wasting your time.

Here's output DUMP_TABLE(EA_Window_Loot.lootData) taken with "no-icon" item in opened loot window (somehow I can't attache files, so wall of text here). The  uniqueID = 0.

(table) 1 = table: 50B77710
   (wstring) description = 
   (number) iLevel = 0
   (number) maxEquip = 0
   (table) slots = table: 51E89DC0
   (number) equipSlot = 0
   (table) races = table: 525AD2A8
   (number) tintB = 0
   (number) armor = 0
   (number) level = 0
   (number) timeLeftBeforeDecay = 0
   (number) blockRating = 0
   (number) iconNum = 0
   (number) rarity = 1
   (number) capacity = 0
   (number) marketingVariation = 0
   (table) flags = table: 46F2C4C0
      (boolean) 1 = false
      (boolean) 2 = false
      (boolean) 3 = false
      (boolean) 4 = false
      (boolean) 5 = false
      (boolean) 6 = false
      (boolean) 7 = false
      (boolean) 8 = false
      (boolean) 9 = false
      (boolean) 10 = false
      (boolean) 11 = false
      (boolean) 12 = false 
      (boolean) 13 = false
      (boolean) 14 = false
      (boolean) 15 = false
      (boolean) 16 = false
      (boolean) 17 = false
      (boolean) 18 = false
      (boolean) 19 = false
      (boolean) 0 = false
   (wstring) name = 
   (boolean) broken = false
   (number) timestamp = 0
   (number) customizedIconNum = 0
   (number) marketingIndex = 0
   (number) renown = 0
   (boolean) isTwoHanded = false
   (boolean) decayPaused = false
   (number) uniqueID = 0
   (number) speed = 0
   (number) craftingSkillRequirement = 0
   (number) sellPrice = 0
   (number) cultivationType = 0
   (number) dyeTintB = 0
   (number) dyeTintA = 0
   (number) tintA = 0
   (number) tier = 0
   (number) currChargesRemaining = 0
   (number) trophyLocation = 0
   (table) enhSlot = table: 5369E8E0
   (table) bonus = table: 463899D8
   (number) numEnhancementSlots = 0
   (number) type = 0
   (boolean) boundToPlayer = false
   (wstring) customizedIconName = 
   (number) id = 0
   (number) dps = 0
   (table) craftingBonus = table: 4DE898E8
   (number) trophyLocIndex = 1
   (table) careers = table: 4D43E150
   (boolean) isNew = false
   (boolean) bop = false
   (number) noChargeLeftDontDelete = 0
   (number) stackCount = 0
   (number) itemSet = 0
   (boolean) isRefinable = false
   (table) skills = table: 52C6B398

**Comment by mursie** [comment]
I am having issues with lizard mobs for butchering.  It continuely brings up a "no icon" loot all popup box that will not go away and the completion of the butchering mob never is allowed to finish because the actually looting of the no-icon item can't occur.  Seems to just be lizard mobs.

**Comment by hoppolek** [comment]
The same problem applies to Stonewood Cockatrice and Petrifier in Avelorn.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
