### ISSUE TITLE
Scenario quest nordenwatch is disappered and cannot be taken again

### ISSUE THREAD

**Issue by agemennon675** [WarEmu/WarBugs#15932]
**Expected behavior

Scenario quest should be available to be taken from the quest giver in the scenario when you dont have it already

 and actual behavior:**

Scenario quest nordenwatch is disappered and cannot be taken again.

**Testing Screenshots/Videos/Evidences (always needed):**

Here is the evidence

![Aschwind_000](https://user-images.githubusercontent.com/22632862/76238585-1f8dbb80-6241-11ea-9665-cfa4dad22880.jpg)
![Aschwind_001](https://user-images.githubusercontent.com/22632862/76238593-21f01580-6241-11ea-8a8a-d3cebe1e534a.jpg)
![Aschwind_002](https://user-images.githubusercontent.com/22632862/76238599-23214280-6241-11ea-95fb-0ad3e165d712.jpg)

**Comment by gittoaster** [comment]
try to restart RoR fully and that should help

**Comment by agemennon675** [comment]
> try to restart RoR fully and that should help

You are joking right ? Restart wont fix everything.. for  the record, I tried it already

**Comment by Kabucoror** [comment]
everthing fine on database side

**Comment by agemennon675** [comment]
> everthing fine on database side

I contacted GM's both in game and on discord, with these same screenshots, I told them the quest was working fine for everyone else except me and my friend who was there with me when server crashed 2 days ago, we both cannot get Nordenwatch scenario quest for our characters for 3 days now, GM's told me to make an appeal here, if this is Dubious what is the next step for me ?(Delete the character that is not working ?)  I am seeking help, not trying to to point out bugs, please help me

**Comment by Kabucoror** [comment]
I just made a note that this issue is not a genreal one and a very misterious too. Since you are still at leveling you will be able to pick up the quests with higher rewards for nordenwatch later.

**Comment by dalen** [comment]
What's the name of the character?

**Comment by dalen** [comment]
the quest is actually in a bugged state for your character in the DB. We will delete the quest on your character in next reboot (soon) and make a code fix for it later.

**Comment by Lheana** [comment]
What's the name of the char of your friend?

**Comment by agemennon675** [comment]
Name of my Character is Aschwind, (my friend already deleted his and made a new one, I kept the character to help you guys resolve this issue if it was general issue(it seem not)), Thank you very much for your time :)

**Comment by dalen** [comment]
Made a fix that will clear up any similarly bugged quest records on login.
