### ISSUE TITLE
Failed to join SC, got intro screen overlaid onto character

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#15933]
**Expected behavior and actual behavior:**
Queued for Nordenwatch, accepted pop. Got briefly booted back to intro screen. Pressed Play and returned to game with the Main menu options overlaid over my character. Expected behavior is to be put into the scenario. 

**Steps to reproduce the problem:**
Not sure how to reproduce, happened randomly while queueing for Nordenwatch

**Testing Screenshots/Videos/Evidences (always needed):**
![Forkrul_018](https://user-images.githubusercontent.com/1183293/76249225-2fa69a80-6243-11ea-949a-df876c5ceb16.jpg)

**Comment by gittoaster** [comment]
sounds like game needs to be restarted.

**Comment by Kaelang** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/12576.
