### ISSUE TITLE
Tok unlock at once the following titles

### ISSUE THREAD

**Issue by Gagaddon** [WarEmu/WarBugs#15937]
![Gagaddon_088](https://user-images.githubusercontent.com/52387005/76286261-65b63f80-6280-11ea-9ffd-082348d3cf11.jpg)
<!--

Tok have also unlock the following titles at once, when im log at game , screenshots available

**Comment by Vayra** [comment]
Yes, looks like a bunch of achievements were just implemented. Suddenly got the X Tome Unlocks ones last night .

**Comment by dalen** [comment]
yes, implemented those titles and achievements. So for players that had already reached that amount of influence/tome unlocks you get them immediately on login.

For new characters they will get unlocked as you progress.
