### ISSUE TITLE
Invisible wall trap

### ISSUE THREAD

**Issue by yugistar1** [WarEmu/WarBugs#15938]
![2020 03 10-02 37 png](https://user-images.githubusercontent.com/31774888/76290124-9f834800-6278-11ea-93c4-8af1c2e5fa32.jpg)

 If you try jumping off the cliff from the corner of the tower. You seem to fall into a invisible wall that you cant leave or die. I watched a white lion attack me for 10 minutes and took zero damage. I was not the only person to fall into this. Half of my war band fell into it and we all had to force /stuck to get out.

Note: This spot in on the North East corner of the outside (chaos waste) Charon's keep tower cliff wall.

**Comment by gittoaster** [comment]
Can please either upload a better image and/or precise coordinates.

**Comment by raptrr** [comment]
Like @gittoaster mentioned, provide some more information. Just this and the little minimap are not enough to get some proper testing
