### ISSUE TITLE
Tok Completed 2000 tome unlocks I got the unlock but not the title

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#15936]
the title should be :Title: The Overachiever, XP: 66
![Thorbolt_607](https://user-images.githubusercontent.com/16274785/76284871-b341a500-629e-11ea-99cb-ed852a88698f.jpg)

**Comment by dalen** [comment]
Same as for https://github.com/WarEmu/WarBugs/issues/15935

At least for me, the title shows up in the titles "Achievements" section anyway. But seems like they are not linked up properly in the client.

**Comment by Lheana** [comment]
Duplicate of #15935
