### ISSUE TITLE
Siege Weapons

### ISSUE THREAD

**Issue by TheOGScav** [WarEmu/WarBugs#15948]
Can only spawn siege wpns at postern.

https://www.youtube.com/watch?v=oXkTE7-vUq0&feature=youtu.be

**Comment by Kaelang** [comment]
Tested, was able to spawn a siege weapon outside Main.

Closing.

**Comment by TheOGScav** [comment]
> 
> 
> Tested, was able to spawn a siege weapon outside Main.
> 
> Closing.

Did ya watch the vid closely?
