### ISSUE TITLE
City Stage 2 being skipped

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#15949]
**Expected behavior and actual behavior:**
If the defender wins stage 1 but lost the BO that summons the Cannoniers they continue to spawn until the warlord takes the bo. If the Cannoniers  kill the palace doors after stage 1 it'll skip stage 2 completely giving no rewards or anything.  

**Steps to reproduce the problem:**

defender win stage 1 but cannoniers kill palace gate in between stage 1 and 2.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by MaxHayman** [comment]
Fixed pending patch
