### ISSUE TITLE
Down Bolster UnBolster No Bolster

### ISSUE THREAD

**Issue by GrimTitan** [WarEmu/WarBugs#15947]
**Expected behavior and actual behavior:**
Joining a Scenario and being Bolstered in rank. 
If joining from the Nordland RvR Lake during the Event where Higher ranks can compete, joining a Scenario does not register a higher rank, or bolster you. I could, even at Rank 25, no longer use my mount in the Scenario as it still classed me as a 15 rank from the RvR lake. 

**Steps to reproduce the problem:**

Be 16+ in rank, go to RvR Lake in Nordland during event, join a scenario.

**Testing Screenshots/Videos/Evidences (always needed):**
https://clips.twitch.tv/ObliviousFamousKuduRitzMitz

**Comment by GrimTitan** [comment]
https://clips.twitch.tv/UglyTransparentPuffinOptimizePrime

More proof

**Comment by Kaelang** [comment]
As this event has now ended, I am going to go ahead and close up this report. _If_ the scenario makes a return in the feature, and this issue persists, please feel free to re-open the report.
