### ISSUE TITLE
Tzeentch's Firestorm, magus mastery ability unable to be cast in Scenarios

### ISSUE THREAD

**Issue by SaldekMaugs** [WarEmu/WarBugs#15941]
**Expected behavior and actual behavior:**
The mastery ability Tzeentch's Firestorm wouldn't cast in a Nordenwatch scenario but worked fine in the open world, tested it in two scenarios before speccing away from it, there were other people who tried as well and also couldn't cast the ability in scenarios other than Nordenwatch, I think the other ones were Tor Anroc and Phoenix Gate that were tried. 

**Steps to reproduce the problem:**

tried casting it in multiple places at my feet on flat land up hills on flags on enemies but it didn't cast anywhere. was rank 25ish 

**Testing Screenshots/Videos/Evidences (always needed):**
can't recreate it now, but a couple other people have mentioned it as a problem, if I see anyone say it again I'll ask them to video or SS the problem.

**Comment by ElMosquito** [comment]
I have the same problem, only that the skill doesn't work when I'm bolstered in rvr. It works in pve without bolster but not in pvp areas.

**Comment by grindbox** [comment]
the problem happens both in rvr and scs, everytime you get bolstered. pretty annoying

**Comment by Seeky91** [comment]
Same problem here, I can't use firestorm when fighting. I tried with addons disabled, it's not working too.

**Comment by grunbag** [comment]
What is the error message ?

**Comment by Seeky91** [comment]
There is no error message.

**Comment by Hellalukard** [comment]
Same Problem here.

**Comment by grindbox** [comment]
no error messege. the casting just breaks or did not even happens

**Comment by Vdovics** [comment]
Same issue here. Anytime I am bolstered skill cancel it casting without any message. Common its reported 3 weeks ago and still no fix...

**Comment by CyphDK** [comment]
Not sure if it is another bug, but it can be cast while moving in pve, of course only when bolster isn't on.

**Comment by ChristerGustavsson** [comment]
@CyphDK if you have a summoned Flamer, Changing skills can be cast while moving. Otherwise I just came here to see if this was reported. Just got the ability on my rank 27 Magus and was a bit disappointed with the result. 

Can confirm that it seems to be related to the bolster buff, it works like a charm in PVE but not in RVR.

**Comment by porterrr** [comment]
still bugged

**Comment by grunbag** [comment]
Does it works at level 29 ?

**Comment by grunbag** [comment]
Fixed

**Comment by porterrr** [comment]
currently 26 doesnt work when bolstered

**Comment by Kaelang** [comment]
Fix Pending means it will be updated in the next patch.

**Comment by Kaelang** [comment]
As of 29/04/2020 this should now be fixed. Please re-open if issues persist.
