### ISSUE TITLE
Missing appearance: Outlaw's Stompas

### ISSUE THREAD

**Issue by monster1305** [WarEmu/WarBugs#15946]
Item called "Outlaw's Stompas" is missing appearance. 
My Character: Keychopz

Screenshots taken
![Keychopz_004](https://user-images.githubusercontent.com/48641801/76356859-b16ff400-6327-11ea-9c48-19f0450e2e72.jpg)
![Keychopz_005](https://user-images.githubusercontent.com/48641801/76356866-b46ae480-6327-11ea-9f09-d41c9780127c.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by monster1305** [comment]
Can i get a manticore now? x)
