### ISSUE TITLE
Low Level Dungeon Scaling 

### ISSUE THREAD

**Issue by nekkabaw** [WarEmu/WarBugs#15950]
Me and my friends went to the Scallum Dungeons after doing some RVR Scenarios, half of us got scaled up to level 48, while some stayed at a lower level. I am not sure what caused us to scale only in this instance. I tried zoning out and I got reset back to my normal level. For some reason this instance dungeon is scaling some players making the dungeon pretty trivial to complete. Hope this helps.

![dungeons](https://user-images.githubusercontent.com/48853638/76437957-94fba800-6377-11ea-9880-62f16da27766.PNG)
eport,

**Comment by MaxHayman** [comment]
Should be fixed with most recent patch. Please reopen if not.
