### ISSUE TITLE
Good Stunties is Dead Stunties (Destruc, Barak Varr) NPC spawned in mountain and unattackable

### ISSUE THREAD

**Issue by Morbus47** [WarEmu/WarBugs#15952]
The quest asks you to kill 4 Sea Gunners and obtain the hand of Felgrund Harmirsson, however Felgrund spawns in the mountain at roughly 60075/29680 (right above the dwarf head stone carving) and is completely unattackable, making it impossible to complete the quest.

**Comment by Kabucoror** [comment]
Felgrund stands on top of the wall, maybe he didn't reset properly after someone accidently pulled him.
