### ISSUE TITLE
City Siege: Stuck in City Siege after end.

### ISSUE THREAD

**Issue by Vicgrim** [WarEmu/WarBugs#15959]
**Steps to reproduce the problem:**
When City Siege will be ended you can stuck into them (not get ported). /unstuck or /reload command doesn't help. All you can do its a read chat.) 
This was already happened. If client will be closed access to character will be lost until the next server reboot because you will stuck on login screen ( other characters will be available)

P.S. -  last time when its happened, and now I was queued with group and be a leader

**Testing Screenshots/Videos/Evidences (always needed):**
 ![Vicgrimm_025](https://user-images.githubusercontent.com/51807854/76507573-17f72e00-645e-11ea-935f-b4073869c4b8.jpg)
![loging](https://user-images.githubusercontent.com/51807854/76507695-470d9f80-645e-11ea-9278-e0a09092fc28.jpg)

**Comment by MaxHayman** [comment]
Fixed
