### ISSUE TITLE
High amount of renown points spent on low level characters

### ISSUE THREAD

**Issue by hyffa** [WarEmu/WarBugs#15956]
Started playing this game with 2 friends and so far this has happened to all 3 of us and it's giving quite an unfair advantage. My lvl 20 WP has 65 renown points spent and both of my friends have 80+ points spent in their trees.

The game randomly resets your mastery points & renown points and when going to the renown trainer to relearn passives your "Available points" just stays at your characters max at all times. 

https://streamable.com/6dcvc This is what it looks like when you try to learn passives from the trainer

After learning everything I could from the trainer and then restarting the game these are the renown points that "stuck" to my character. https://streamable.com/qtne0

As for what I was doing before I realized my renown was reset was literally just spamming SC's in the main city and turning in victory quests.

**Comment by dalen** [comment]
I think that is a UI bug in the advanced renown trainer addon, that you age not actually getting all those abilities.

Can you verify by doing a `.getstats` before and after training all of them?

**Comment by hyffa** [comment]
When this happened to my friends they did not have any addons installed, if you look at the second streamable I show the renown trainer without any addon and there's only a handful of passives that persisted on logout. My character is now locked at 65 points, I do not gain any points by leveling anymore and yes according to .getstats they are very real

**Comment by hyffa** [comment]
https://i.gyazo.com/65d943097636e9679212d2b040cac884.jpg renown window + .getstats of my friend with 85 points spent, he had this at around level 12~
