### ISSUE TITLE
Pet Attacking on Passive 

### ISSUE THREAD

**Issue by nekkabaw** [WarEmu/WarBugs#15957]
https://imgur.com/a/CthaBqf

I couldn't attack the video so i made a imgur clip, but as you can see I am mounted and my pet is doing damage. I put him on passive he is still attacking. I am not sure why. 

The picture you can see i am mounted, pet is on passive, and he is attacking. the damage numbers as well as the pets ability is on the target dummy. 

![bug2](https://user-images.githubusercontent.com/48853638/76477904-ffd2d080-63c3-11ea-8288-fdd24dbac9f9.PNG)

**Comment by SilverWF** [comment]
Are you sure you aren't using any pet addons, like LoyalPet or PetAssist?

**Comment by Kaelang** [comment]
Please can you send a link to video you had prepared for this report?

**Comment by Kaelang** [comment]
Closed - no further information provided.
