### ISSUE TITLE
Kotbs aura and toughness potions

### ISSUE THREAD

**Issue by Krazis** [WarEmu/WarBugs#1596]
I have found that the kotbs aura is over riding the stat boost of the toughness potion. For example if i consume a toughness potions and then activate my aura, the boost to my toughness stat is equivalent to my toughness aura boost (54) minus the potion boost (32). It is therefore is only giving an increase of 22, rather than of 54. 

I have not checked with other auras and stat potions nor have i checked with destruction side. 

Regards, Gerv

**Comment by ozarmidrashim** [comment]
http://ut-serv.ldg-gaming.eu/azarael/Kernigget_000.jpg
http://ut-serv.ldg-gaming.eu/azarael/Kernigget_001.jpg
http://ut-serv.ldg-gaming.eu/azarael/Kernigget_002.jpg
http://ut-serv.ldg-gaming.eu/azarael/Kernigget_003.jpg
http://ut-serv.ldg-gaming.eu/azarael/Kernigget_004.jpg

**Comment by Krazis** [comment]
Are they not supposed to stack with each other?

**Comment by Tesq** [comment]
auras didn't stack on live, same apply for dok armor buff, BO/sm gropu buff.

**Comment by Krazis** [comment]
Thanks Tesq, I did not know that, cheers for the heads up.
