### ISSUE TITLE
Karak Karag Oil emplacement LOS issue, Thunder Mountain

### ISSUE THREAD

**Issue by Desitri** [WarEmu/WarBugs#15969]
**Expected behavior and actual behavior:**

Oil emplacement should be targetable and attackable by range classes from ground level. Range classes could only engage oil  by jumping and applying instant attacks.

**Steps to reproduce the problem:**

Go to Karak Karag and attack Oil emplacement from ground level

**Testing Screenshots/Videos/Evidences (always needed):**

![Soulstress_005](https://user-images.githubusercontent.com/61955502/76681205-c56f6a80-6633-11ea-8cd6-e4c0ad6800c9.jpg)

**Comment by RoR-Zomega** [comment]
#15675

**Comment by raptrr** [comment]
Linked one is the open one. Closeing this one
