### ISSUE TITLE
Didn't receive rewards

### ISSUE THREAD

**Issue by masterhaywardian** [WarEmu/WarBugs#15965]
Won 2 rewards. 1 Epic, 1 massive bag. Left area and didn't receive either of them by mail

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by raptrr** [comment]
Did you receive them now?

**Comment by Lheana** [comment]
No answer: ticket closed.

**Comment by masterhaywardian** [comment]
Yup, all good. Thanks!

**Comment by Lheana** [comment]
Perfect
