### ISSUE TITLE
Rune-bound Chest Gives Instant Progression to Chapt 18 Rewards

### ISSUE THREAD

**Issue by JohnK75** [WarEmu/WarBugs#15962]
**Expected behavior and actual behavior:**

The Rune-bound Chest in Chapt 18th Dwarf (Thunder Mountain/Cinderfall, Order) area at approximately 59.5K / 13.3K.

Expected Behavior - I think is to complete a quest.

Actual Behavior - If you click the chest repeatedly it will max out your progress bar towards the Dwarf Chapt 18 Rally Master rewards in Thunder Valley.

**Steps to reproduce the problem:**

I did not have any quests for the area, but was working on a jewelry unlock when I came across the chest. I noticed when I repeatedly clicked the chest, it max'd out my Chapt 18 progress slider. 

**Testing Screenshots/Videos/Evidences (always needed):**

![Cinderfall_Bug_01](https://user-images.githubusercontent.com/35406553/76591739-40634480-64bf-11ea-957d-56ff036da5b5.jpg)

**Comment by Kabucoror** [comment]
It doesn't give any influence to me

**Comment by Lheana** [comment]
When did you experience that?

**Comment by JohnK75** [comment]
Hello,

I believe it's been 4 or 5 days now. I originally posted a day (or 2) after experiencing it via in-game bug tracker, but then about a day or two later received a message about I needed to use the github bug tracker, then about a day after getting that email in-game, I posted the bug report here. I would of posted sooner, but my time was limited and I've been trying to maximize my x2 XP event on getting as much RR XP as possible lol.

To elaborate further...

I was attempting to get to the cave in that area for one of the jewelry unlocks. I had to kill a number of Orcs in the area to get there safely. It's very possible I had cleared stage one of the area by killing Orcs, but I clearly past stage two and three by spam clicking the rune-bound chest. The only reason I was clicking the chest, was because this game is similar (to me at least) to SWTOR and they always had loot chests in random world locations, so I thought maybe this had loot in it, but instead it progressed my stage meter. I wish I would of recorded that bit for sure, but I was too tired of clearing out Orcs and wasn't sure if more would spawn again soon, so I quickly clicked the rune-bound chest multiple times once I saw my meter progress, then I ran into the cave to get the jewelry unlock.

I hope that helps!

**Comment by Lheana** [comment]
I tried this several minutes ago on live, and I did not receive any influence. Please try again and comment here to tell if it still happens for you.

**Comment by JohnK75** [comment]
When this happened to me. I clicked it as many times as I could to see how bugged it was. For me, it filled and completed my progress for Chapt 18 Dwarf. Which is why I reported it.

This was on Live when this occurred for me.

**Comment by JohnK75** [comment]
My class is an Ironbreaker... if that matters?

**Comment by Lheana** [comment]
I had already understood what your issue was, but it has been fixed with the patch of last week. So please, try again, and the issue should no longer occur.
