### ISSUE TITLE
Dragonwake Gold Bag gave t1 chest for Zealot while on a BW

### ISSUE THREAD

**Issue by sshabel** [WarEmu/WarBugs#15964]
Fairly straightforward:
I participated in a dragonwake flip and got a gold bag on my bright wizard. I went to loot the bag and it contained a tier two zealot chest piece.

![screenshot](https://user-images.githubusercontent.com/23587466/76662885-bb773a00-6555-11ea-919f-e3643e0224c2.jpg)

**Comment by raptrr** [comment]
Did you get them now, after patch / server restart?

**Comment by sshabel** [comment]
I did not.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by sshabel** [comment]
Am I ever going to get my loot from this bag or is it never going to happen?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Lheana** [comment]
No, there is no recovery.
Nevertheless you did not really answer the question of raptrr: Did you get the bag now, after patch / server restart?

**Comment by Kaelang** [comment]
Closed - no additional information provided.
