### ISSUE TITLE
Pretty Bugged character

### ISSUE THREAD

**Issue by noobystyler1995** [WarEmu/WarBugs#15978]
My character is an Archemage lvl 20 CR, today I logged in and it has no items in the inventory or paperdoll but in character selection, it is wearing a full robe, exp bugged.
![help1](https://user-images.githubusercontent.com/62188643/76690081-cb048a80-660a-11ea-86c9-be464e029cfa.png)

https://streamable.com/ohuc1

**Comment by sinesensu9253** [comment]
Welcome to the club. :)
