### ISSUE TITLE
WP Guilty Soul Tactic Doesn't work on Dots in Wrath Tree

### ISSUE THREAD

**Issue by Ekundu01** [WarEmu/WarBugs#15970]
**Expected behavior and actual behavior:**
![image](https://user-images.githubusercontent.com/50953486/76682067-2022ab00-65cf-11ea-80c4-f4024294f584.png)

Tactic states - Anytime you crit with a direct damage path of wrath ability you do x damage over time for 9 secs and get a Blessing that increases your path of wrath abilities by 5% stacks up to 4 times.

Guilty Soul increases the damage on direct damage but Dots do not get this increase. Soulfire and the Dot portion of Castigation Do not get any boost in damage from the stacks even if recasted while you have the damage bonus. Both of these abilities are in the wrath tree.

It also doesn't increase the damage on Prayer of Righteousness. This may be intended but throwing it out there just incase.

Also the Dot damage that comes from Guilty Soul can't crit and doesn't get the damage boost from stacks either. Not sure if that is intended or not.

**Comment by Lheana** [comment]
This has been fixed with the patch of 21/03/2020.
