### ISSUE TITLE
One of my characters reset to level 1.

### ISSUE THREAD

**Issue by sinesensu9253** [WarEmu/WarBugs#15975]
I was a level 22 White Lion/Renown Level 19 last night when I logged off. I logged in this morning and literally everything has been reset on this single character to level 1. He lost all of his gold and items. He still has suggested friends from when he was leveling. He lost all his friends on his list as well. It even kept his face, hair, jewelry. The hair color changed and it put a circlet on him. So obviously it still has some prerecoginition of the character. Anyways, I would reallllllllly appreciate getting this character back. I was making him my main character.
![screenshot_000](https://user-images.githubusercontent.com/62182809/76686203-bc58ac00-65e7-11ea-8517-1712e773f03f.jpg)
![Sinesensu_000](https://user-images.githubusercontent.com/62182809/76686204-bebb0600-65e7-11ea-987b-01fe5309e5f7.jpg)

**Comment by MaxHayman** [comment]
When did you create the character?

**Comment by sinesensu9253** [comment]
> When did you create the character?

The previous night.

**Comment by raptrr** [comment]
Im sorry to inform, that we don't restore or hand out gear etc.
We will investigate what might have happend tho.

**Comment by sinesensu9253** [comment]
> Im sorry to inform, that we don't restore or hand out gear etc.
> We will investigate what might have happend tho.

So you can just delete people's shit and then say you won't fix it? Y'all are fucked up man.

**Comment by sinesensu9253** [comment]
Don't bother investigating. I'm quitting this game, and I will be taking all of my friends with me. Have a good day, assholes.
