### ISSUE TITLE
Officer Medalions not dropped from winning SC at rank 39 (level) for Destruction side

### ISSUE THREAD

**Issue by Vandal20** [WarEmu/WarBugs#15973]
When completing a SC and wining as destro at rank 39 you should get officer medallion instead you only get soldier medallion. And when you reach rank 40 it just goes on and drops the max medallion for you so it basically skips officer.

**Comment by MaxHayman** [comment]
@SecretsOTheP Could you look into this please?

**Comment by wargrimnir** [comment]
I believe this is because t3 scens are only allowed to drop t3 currency, and t4 scen currency is gated based on renown rank.

If you had lower renown, it would probably give you officer emblems.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/15821
