### ISSUE TITLE
Ironclaw Goblins give incorrect error msg when attacked

### ISSUE THREAD

**Issue by Tiggyish** [WarEmu/WarBugs#15979]
When attacking Ironclaw Goblins in Eklund, I got a "Target Is Not Attackable" error message each time I cast a spell even though it was in fact attackable -- it took damage, died, counted for its quest, etc.. 

![image](https://user-images.githubusercontent.com/62189894/76691115-7100c680-6604-11ea-91a9-4d67eb0a6512.png)

 My character was a Level 4 Runepriest.

**Comment by Tiggyish** [comment]
Just had the same issue when attacking a Lobber Git.

**Comment by Lheana** [comment]
Then please open a bug report per NPC.

**Comment by Tiggyish** [comment]
Will do! Thank you :)

**Comment by Lheana** [comment]
This has been fixed with the patch of 21/03/2020.
