### ISSUE TITLE
Issues with character (randomly dying, looks like i lost everything)

### ISSUE THREAD

**Issue by Luxxie69** [WarEmu/WarBugs#15974]
Was fine until patch but looks like i've lost everything but asked around people are saying i have my gear, every other alt i have is fine and working but when i relog AM it has skills from the alt (cannot use the skills on AM) i also randomly die and people can rez me i have tryed relogging/restarting afew times nothing seems to work
![1](https://user-images.githubusercontent.com/32314969/76684103-15810980-6601-11ea-927d-886c82623d88.png)
![2](https://user-images.githubusercontent.com/32314969/76684104-17e36380-6601-11ea-9f56-4aa8fe2a32b4.png)
![3](https://user-images.githubusercontent.com/32314969/76684105-19ad2700-6601-11ea-9c40-281421d6e597.png)

**Comment by Xissc** [comment]
I'm also having this issue, have tried all the steps above. All other characters seem fine. Character Kaithina

**Comment by VanVorqs** [comment]
This has happened to me also, Logged in this morning in Altdorf on my AM, Completely Naked, Bags Empty, Renown Rank set to 0, I can be dead and walking around.
![Ded](https://user-images.githubusercontent.com/62190242/76691420-524b1000-6696-11ea-902c-cc98af0ec1b7.jpg)
I do look normal to other people though, just to me I'm running around Butt-Naked.
My Mastery Tree no longer Exists, it's just blank. "Path of None"
![None](https://user-images.githubusercontent.com/62190242/76691455-7575bf80-6696-11ea-8a07-882e6c25dfee.jpg)
Character is Kelrion

**Comment by MaxHayman** [comment]
Are you guys all in the guild "LULREZ"?

**Comment by VanVorqs** [comment]
We all are, yes.

**Comment by shaneh7** [comment]
Ya I'm having the same issue. I'm also in LULREZ. Created my char few days ago, just tried to log in and everything described above is happening to me.

**Comment by VanVorqs** [comment]
For anyone else, I just fixed this by leaving the guild and relogging.

**Comment by Luxxie69** [comment]
Can also confirm leaving guild then relogging fixes the issue. Is the guild safe to join back after or is the guild bugged ?

**Comment by MaxHayman** [comment]
Should have been fixed shortly after this happened.

**Comment by VanVorqs** [comment]
Hey Max,

It was, thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
