### ISSUE TITLE
Overspend at renown trainer

### ISSUE THREAD

**Issue by Rogots** [WarEmu/WarBugs#15983]
My witch elf is RR42 which from my knowledge should allow me to spend 42 points at the renown trainer. However, yesterday I was able to spend about 100 points at the trainer which is most likely a bug.
Anyone else experienced the same?

**Comment by raptrr** [comment]
Can you provide some more information, like char name, CR, screenshots

**Comment by dalen** [comment]
There is a bug in the advanced renown trainer addon that makes it look like you can buy much more renown abilities than the server actually lets you buy. This is likely just that.

**Comment by Rogots** [comment]
I actually had all the buffs mentioned under my spells/skills and also my stats were increased by what I had skilled.
I actually was able to skill 170+ points. Unfortunately I havent screenshotted it and removed it to not be banned. However, if someone is able to still see it, char name is Volia.
