### ISSUE TITLE
Crashing after 10 seconds of loading in.

### ISSUE THREAD

**Issue by TurboTrodan** [WarEmu/WarBugs#15988]
I have seen issues similar to this on the forums, however the files to fix this lead me to dead links. This is why I am making this post. 

**Expected behavior and actual behavior:**
Whenever I load into my character, everything is fine until it crashes 10 seconds later. This may be due to an audio problem I have add before where weird glitchy sounds were made and then it crashed, but that doesn't happen anymore. The problem might be that one of the audio files are corrupted but I don't know.

**Testing Screenshots/Videos/Evidences (always needed):**
https://youtu.be/-pDhIZm3KeM (I would send it in a file format but the video file isn't accepted by the website)

P.S - I don't know if this is supposed to be in Technical support or bugtracker, so I just put it here.

**Comment by Kaelang** [comment]
If you're still experiencing this, please create a thread in Technical Support.
