### ISSUE TITLE
Sorc LvL 15 Tactic not gained on level

### ISSUE THREAD

**Issue by zhentil** [WarEmu/WarBugs#15984]
https://builder.returnofreckoning.com/career/sorcerer

**Comment by raptrr** [comment]
Provide further information or im gonna close this

**Comment by zhentil** [comment]
Not sure what I can add, upon gaining level 15 I did not receive the sorc tactic grasping darkness, it was not added as a skill, I spoke to another lvl 15 sorc and they did not have it either. It did show up before this as at the career trainer. I thought that maybe the fact my RR was higher than my actual level might contribute but the other sorc was not a higher RR

**Comment by zhentil** [comment]
nvm the career builder has it listed wrong
