### ISSUE TITLE
[Destruction] List of Trophy Quest bugged rewards

### ISSUE THREAD

**Issue by Krumlok** [WarEmu/WarBugs#1598]
Working:
- Special Shrooms
- Dragonseye Pendant
- Barbed Kahle
- Chattelbind

Not working (Means the item is not given as a quest reward, it's equal to selecting no reward, nothing shows up on inv after clicking one of these options)
- Raven Pendant
- Dark Hatched
- Changed Hatched
- Feedin' Time
- Vilecord Teeth
- Dhar Scroll

-Orc Trophy

(All the credit for the list goes to Razid1987)

**Comment by Krumlok** [comment]
Forgot to put the "Orc Trophy" in the Not Working list

**Comment by Evildoor** [comment]
Closing since #1704 has more info about the problem.
