### ISSUE TITLE
Squid herder head vanishing

### ISSUE THREAD

**Issue by zirock32** [WarEmu/WarBugs#15982]
Squig Herders head keeps disappearing when I die in squig armor, its the puple squig armor. I stuck with a redish orange squid till I relog and get my head back. This just started happening yesterday night.
[Doc1.docx](https://github.com/WarEmu/WarBugs/files/4333829/Doc1.docx)

**Comment by Kaelang** [comment]
Please use an image hosting website, or put pictures directly into Github to highlight the problem.

**Comment by Kaelang** [comment]
Closed.

**Comment by Cammykins7** [comment]
I can say it still happens and was shown by a 2018 post. https://github.com/WarEmu/WarBugs/issues/12566
