### ISSUE TITLE
Bought Anathema weapon, never got it...!?!?!

### ISSUE THREAD

**Issue by Getku** [WarEmu/WarBugs#15980]
I grinded SC to buy my anathema weapon! I traded my lvl41 renown weapon and 750 Opressor Emblem to "Apostle's Xiphos of Anathema" When i pressed yes to the trade i lost my 750 Emblems and My rr41 renown weapon but NEVER got my rr61 "Apostle's Xiphos of Anathema" 

I DONT wanna grind anyomre SC for this character

--- Punahilkka rr80 DoK
00:45 15 march 2020

**Comment by Kaelang** [comment]
I tagged this up 9 days ago, however after reviewing this again I'm honestly not sure what we can do with this report. I know many DoK's who have purchased their Anathema without issues, myself included.

I'm going to switch the tags to a 2 week ultimatum and hopefully you are able to provide some more steps to replicate such issue.

Thanks.

**Comment by Getku** [comment]
Its okay, i dont play anymore of this game coz of frustation and lack of player service/help.
