### ISSUE TITLE
Inevitable City Siege (Stage 2): pathing issue with Patriarch Thyrus Gormann

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#15990]
**Expected behavior and actual behavior:**

Patriarch Thyrus Gormann travels from order's spawn to the Khorne area. Once the Khorne area has been captured he will then move on to the middle objective point. However he has a pathing bug where while in the Khorne area he will double-back on himself for no reason, delaying the time it takes to get to the middle objective.

The screenshot shows the world and map location of the error. He will walk up this path as if he is leaving the Khorne area but upon reaching the top of the incline he will turn 180 degrees and walk back down it. When he's nearly left the rocky floor he'll 180 again and walk back and begin to properly make his way to the middle objective.

**Steps to reproduce the problem:**

Watch the pathing of Patriarch Thyrus Gormann on stage 2 of the IC siege.

**Testing Screenshots/Videos/Evidences (always needed):**

![patriarch](https://user-images.githubusercontent.com/60266177/76713672-49038700-671a-11ea-8cc3-b43b5ff55f45.jpg)

**Comment by Zomega-WAR** [comment]
@lilimx This was fixed in https://www.returnofreckoning.com/forum/viewtopic.php?p=469929&hilit=Patriarch+Thyrus+Gormann#p469929

I'm not closing it as last time you got upset when I closed my tickets ;)

**Comment by lilimx** [comment]
@Zomega-WAR Im pleased with your progress
