### ISSUE TITLE
Stonewatch Fortress: Prison can be guarded by people waiting in Kadrin Valley

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#15997]
**Expected behavior and actual behavior:**

Due to the close proximity of the prison in Stonewatch fortress to the border with Kadrin Valley and the fact that the front door of the prison faces the border, the destruction players waiting to get into the zone are able to provide assistance (damage and heals) during jail break attempts by order.

Players not part of the fortress should not be able to interfere with the fight and that includes helping prevent jailbreaks.

If the prison was rotated 180 degrees then the people waiting in KV wouldn't be able to provide any meaningful assistance.

**Steps to reproduce the problem:**

Go to the border between Kadrin Valley and Stonewatch during a fort siege and see how close the prison is.

**Testing Screenshots/Videos/Evidences (always needed):**

On the border looking at the prison:

![border1](https://user-images.githubusercontent.com/60266177/76715282-9e906180-6723-11ea-9b52-3b313d9a1eab.jpg)

Healing the defenders and attacking order trying to jail break while I am in KV:

![border2](https://user-images.githubusercontent.com/60266177/76715328-dac3c200-6723-11ea-941d-4da4fd7a8e6f.jpg)

A Magus using the tornano ability on the lever meaning it cannot be pulled by order (no order were actually trying at the time):

![border3](https://user-images.githubusercontent.com/60266177/76715341-e7e0b100-6723-11ea-8b7e-359b1e5f48cf.jpg)

**Comment by Kaelang** [comment]
This treads a fine line but I'm going to take this as more 'Feedback' than a 'Bug'. Although a nuisance, there isn't any issue with the functionality of the fort and/or zone line. The main object in question here is the placement of the prison. 

You can write a post on the Suggestions & Feedback section of the forum here: https://www.returnofreckoning.com/forum/viewforum.php?f=15
