### ISSUE TITLE
Blighted Isle: bolster message spam

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#15991]
**Expected behavior and actual behavior:**

I attempted to debolster in the Blighted Isle but messed up the requirements (my fault). Upon turning into a chicken I noticed my chat log was being spammed with the following message every 2 seconds: "As bolster was removed your buffs have been removed"

It should probably send this message once and then never again until the next time you chicken.

**Steps to reproduce the problem:**

Enter the Blighted Isle above R16 while not meeting the requirements to debolster so you turn into a chicken.

**Testing Screenshots/Videos/Evidences (always needed):**

![bolster](https://user-images.githubusercontent.com/60266177/76713819-48b7bb80-671b-11ea-8e0e-1e18219f5091.jpg)

**Comment by Kaelang** [comment]
Doesn't seem to happen anymore. Please re-open if you can provide more information and replication steps.

![image](https://user-images.githubusercontent.com/60117106/82158573-b0f05e00-9880-11ea-88aa-683ae158cbea.png)
