### ISSUE TITLE
City Siege (both cities, stage 1): cannons have no collision meaning players hide inside them

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#15998]
**Expected behavior and actual behavior:**

The static cannons that must be protected / killed during stage 1 of the city siege have no collision. This means they are very regularly used to hide in when shooting the cannons (defenders), healing during a fight (both sides - I've seen order and destro healers hiding in the same cannon) and when attacking the cannon (attackers).

When defending this leads to the situation that you cannot tell if your cannons are being attacked just by looking at them (especially if effects are off due to lag/performance/etc) - you need to get close enough for tab targeting to work to see if anyone is inside them.

If the cannons were made solid (shouldn't cause any issues as unlike in RvR these cannons cannot be moved) then these glitches would be resolved but it would still create some interesting gameplay regarding positioning around the cannons.

**Steps to reproduce the problem:**

Stage 1 of any city siege: walk upto a cannon and keep walking. You will end up inside.

**Testing Screenshots/Videos/Evidences (always needed):**

Hiding for heals. The blue icon is over my head:

![cannon](https://user-images.githubusercontent.com/60266177/76715655-33e02580-6725-11ea-8291-24bf0c2dd495.jpg)

**Comment by MaxHayman** [comment]
This is a limitation of the game client. Additionally this isnt a bug.
