### ISSUE TITLE
Random name generator does not work.

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#16]
When clicking on the Random name button, during character creation. No name is generated and the button becomes grey.
![random name generator](https://cloud.githubusercontent.com/assets/7492543/2882654/334d313a-d491-11e3-90d5-b56cbe17de51.png)

**Comment by bhcain** [comment]
Not even it just not working but when you click it the button is out of function and after that any names you try to include in your character are "already used", if you reset the game it works just fine.

**Comment by akanieski** [comment]
I think I've made a fairly decent name generating procedure. (https://gist.github.com/akanieski/46b0c5692014dde862d6)

Also tweaked the Random Name Generator Handler to make sure it doesn't give you names that already exist.

See my commit (https://github.com/akanieski/WarEmu/commit/3fb911b5a2d329016571f99cd6dc25078ec8b756)
