### ISSUE TITLE
Oil pragg outerdoor

### ISSUE THREAD

**Issue by Wolfstreet123** [WarEmu/WarBugs#16008]
**Expected behavior and actual behavior:**

U cant hit it from normal range

**Steps to reproduce the problem:**
The oil seems to be to far back, so u cant hit it

**Testing Screenshots/Videos/Evidences (always needed):**

<There is issue with the range on the order keep, outerdoor in pragg

**Comment by Kaelang** [comment]
The oil can be attacked fine.
