### ISSUE TITLE
CTD when group inviting guildie

### ISSUE THREAD

**Issue by Myrdothilore** [WarEmu/WarBugs#1600]
My game keeps crashing to desktop when I invite a guildie to my group. As soon as he accepts the invite I CTD. This just started happening after I saw a magus in ostland flying around with a dwarf under his feet instead of the disk. I think it is related but I'm not sure, it could be a coincidence. 

EDIT:
https://www.dropbox.com/s/rzaf3h26myd4dg4/Myrdothilore_015.jpg?dl=0
ss of magus, the crash happened when we were already in a group. Now it happens everytime he hits accept.

EDIT:
I turned off all the addons and it still crashed to desktop

EDIT:
now it seems to be working correctly, but I would advise someone to look further into this. me and my guildie had just demolished two premade scenerios in a row, and this happened shortly after that. It could be a hack of some kind.

**Comment by Myrdothilore** [comment]
https://www.dropbox.com/s/rzaf3h26myd4dg4/Myrdothilore_015.jpg?dl=0
ss of magus, the crash happened when we were already in a group. Now it happens everytime he hits accept.

**Comment by Myrdothilore** [comment]
I turned off all the addons and it still crashed to desktop

**Comment by Myrdothilore** [comment]
now it seems to be working correctly, but I would advise someone to look further into this. me and my guildie had just demolished two premade scenerios in a row, and this happened shortly after that. It could be a hack of some kind.

**Comment by Evildoor** [comment]
I confirm this (part about crashing, not about mount) - my friend had this problem yesterday when i tried to invite him or he tried to invite me. It seems that it was specific to one character - we had this problem when tried to play sorc (his) + magus, but not with bg + choppa. However, we had no problems playing the first duo week ago, or two weeks ago.

**Comment by WAR-Tyr** [comment]
Yesterday i tried joining a warband in T4 and constantly crashed to desktop. I figured out this happenend only if my character was in a different zone. I was in Altdorf the warband leader was in Praag. After travelling to the zone, i was able to join the wb without any issues.
