### ISSUE TITLE
altdorf NPC missing

### ISSUE THREAD

**Issue by dihanin** [WarEmu/WarBugs#16009]
I use stroll from TM to Altdorf , then when I came back , altdorf NPC is missing. I try to relog 3 times, and use RoRUpdater.exe twice , it still not working . 
I asked someone player, he said it's bothering him a while , until he go to check others quarter NPC(not at market square) then back, market square NPC just show up. 
he said don't know why either.
https://drive.google.com/file/d/14RNnWsOGAZfKoqLUfP85nHVwxyuRPOql/view?usp=sharing

**Comment by Lheana** [comment]
Same issue as #15960
