### ISSUE TITLE
Head of the Viper - Eataine (Order)

### ISSUE THREAD

**Issue by Wesleth** [WarEmu/WarBugs#16016]
couldnt upload video to here, so https://youtu.be/pmyKnmHQ_Qc instead

**Expected behavior and actual behavior:**
Expected - Quest updates
Actual - Doesnt! Captured defenders do not update when freed. Tried melee, ranged, etc etc. Resetting quest, nothing works.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
The quest will be fixed with next patch. However I can not explain your issue with destroying cages, it works fine for me.

**Comment by Wesleth** [comment]
I think that was a display error at the start there, id only just logged on
and was lagging slightly.

Thanks so much for your time, wonderful work you guys are doing

**Comment by Lheana** [comment]
This has been fixed with the patch of 21/03/2020.
