### ISSUE TITLE
BagBug?

### ISSUE THREAD

**Issue by deni3331** [WarEmu/WarBugs#16011]
Hey there dear RoR GM-s and palyers!

I've read trough the forums, but not seen this issue yet (Sorry if I missed it, I am a human also :D.)

The problem is happened with me the 2. time. I am a new player, and when I first played RvR at low lvl, after a big Wipe my bag lost all of it's contet. My horse, portal tome all gear. And now it happened again, and I got printscreens too. After a wipe in RvR I lost all of my items from my bags.
After 3 times relogging/reloading, my items are still missing, but to proove I have something in there (had) my transmogs are still on me. (2. pic) Next to this, I can not pick up items/get them out of my bag. It's like it's sealed. 

Please help me with this issue.

Tank you for you work.

PaterMortheim

**Comment by deni3331** [comment]
![asd2](https://user-images.githubusercontent.com/62246936/76761442-b998bb00-678f-11ea-9247-e2d3634098bc.png)
![asd](https://user-images.githubusercontent.com/62246936/76761451-bc93ab80-678f-11ea-9472-9b99e7274901.png)

**Comment by Kaelang** [comment]
Are you able to replicate this? And/or have your items returned after the hotfix/patch that followed?

**Comment by Kaelang** [comment]
No further information - closed.
