### ISSUE TITLE
Gunbad  '' No shirt  , no shoes ,  no boots  ,big problem.'' Quest doesn't work.

### ISSUE THREAD

**Issue by halilkagan** [WarEmu/WarBugs#16010]
Gunbad dungeon '' No shirt  , no shoes ,  no boots  ,big problem.'' quest doesn't work. Even I picked the boot reward doesn't let me take it. 
![Bug 1](https://user-images.githubusercontent.com/62245823/76758480-cc64bd00-679a-11ea-8e1b-92650a66e3ae.jpg)
![Bug 2](https://user-images.githubusercontent.com/62245823/76758484-d090da80-679a-11ea-9278-89d33b2288c7.jpg)
![bug 3](https://user-images.githubusercontent.com/62245823/76758494-d5558e80-679a-11ea-90fb-851db352fdbd.jpg)

**Comment by Vayra** [comment]
It says select 2, pick both rewards.

**Comment by Lheana** [comment]
No answer: ticket closed.
