### ISSUE TITLE
[Lair Boss] lvl 39 Metoh, the big Yethee doesn't drop gear and hasn't correct characteristics.

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#1602]
In Troll Country is the Lair Boss Metoh. After killing him he doesnt drop any of the gear he should. Epic lvl 39 gear.

Also his characteristics are way of, comared what the have to the wikipedia entry.
He makes 16.500 damger per hit, but should do 2800.

**Comment by milosxe** [comment]
You should ignore the dmg numbers cause they may be true, but for r40 characters.
He used to drop stuff, cause I can still see some items that drop off him on destro AH. Maybe his loot pool was changed with the hero farming fix.

**Comment by Reggaewaldo** [comment]
I shall look into it when dev server is up and running.

**Comment by LestiArdisson** [comment]
Thanks, I will try to kill then one hero boss after the next to see what they drop.
And as for the damage of 16k, most heros I have encuntered do that much.
Only Morra wasnt tested by me, but someone told me that she does 2800 per hit.
So maybe her data is correct.

**Comment by Torquemadra** [comment]
Loot table fine, damage caused against a lvl 40 character is fine. This can be closed.
