### ISSUE TITLE
City Siege (both cities): Stage 2 heroes not visible on the mini-map.

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#16026]
**Expected behavior and actual behavior:**

Expected: on live the heroes of stage 2 (Engra, Patriarch, etc) had icons that appeared on the minimap so you could keep track of their location.

Actual: on RoR the minimap icons for these heroes have not been implemented yet.

**Steps to reproduce the problem:**

Look at the map during stage 2 of a city siege. There should be 4 moving icons on the map that represent the NPCs you need to escort.

**Testing Screenshots/Videos/Evidences (always needed):**

This video at 2:22; https://www.youtube.com/watch?v=sFwvYomfK0o

Screenshot of the above. Notice the 4 skulls (2 red 2 blue) which reprent the locations of the 4 heroes.

![skull](https://user-images.githubusercontent.com/60266177/76807815-87ae4580-67dd-11ea-8ec9-5d03e222a155.png)

**Comment by MaxHayman** [comment]
Interesting. I did not know about this.

**Comment by Zomega-WAR** [comment]
Closing as this has since been implemented.
