### ISSUE TITLE
Inventory Bug - Having a full inventory and looting stackable items

### ISSUE THREAD

**Issue by Kalthea** [WarEmu/WarBugs#16024]
**Expected behavior and actual behavior:** If you have a full inventory, and attempt to loot an item that you already have, and is stack-able, you will be unable to loot that item due to the game stating that your inventory is full.

**Steps to reproduce the problem:** Get a full inventory with one stack-able item in it, and get another one of the stack-able items from a mob. Upon looting, you will be prompted that your bag is full.

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/62267423/76814249-a4904c00-67d0-11ea-9208-3cdf7e06afdd.png)
As you can see, my chat log says to remove overflow, but I already have a stack of Rotting Flesh under my mouse cursor.

**Comment by Lheana** [comment]
You can right-click on the item in the loot window, it will stack the item.

**Comment by Kaelang** [comment]
No further information provided. Closing this report as has been answered.
