### ISSUE TITLE
Dueling Bug, Health regeneration continues throughout duel.

### ISSUE THREAD

**Issue by ChristianTucker** [WarEmu/WarBugs#16027]
**Expected behavior and actual behavior:**
**Expected:** During a duel the participating parties should be combat flagged, which stops health regeneration.
**Current:** Players are not combat flagged, and health regeneration continues throughout the duel. This makes some duels impossible to complete at lower levels, as both parties are simply immortal.

**Steps to reproduce the problem:**
Just duel someone and watch for health regen, very noticeable in T1.

**Comment by Xicoz** [comment]
this is still a problem :( been trying to setup a duel tournament for months now and still no luck because of this bug

**Comment by Kaelang** [comment]
The duel system has been reworked. Please re-open if issues persist in the new Garden zone.
