### ISSUE TITLE
Dat Makes Me Dizzy/Hurried Restore ignores immunity and doesnt apply one either

### ISSUE THREAD

**Issue by Zunig** [WarEmu/WarBugs#16028]
Insta ress tactics should grant standard 30s immunity upon first ress if caster didnt had one.
Additionally, if caster already gained immunity, tru use of said tactic or during combat naturally, every next ress shouldnt cause stun effect but allow free ress without additional penalty.

Thats the way they used to work on live server and frankly thats the only reason to take them at all. 
Currently every ress, even with immunity, apply new 3s stun to the caster, making it into useless tactic and negating its intended purpose.

**Comment by bosli42** [comment]
That was changed on purpose to counter rez-spamming without getting stunned. The tactic still is quite powerful in many situations, especially in warband play.

**Comment by Zunig** [comment]
Cant see hows that usefull with such massive nerf and how its fair for anyone to receive stuns without immunities.

**Comment by bosli42** [comment]
It's a rez that cannot be set back or interrupted and the players is back in the fight 3 seconds earlier. It still has it's place, the live version was just plain stupid OP for warband fights, and it's a good thing they changed that.

**Comment by Zunig** [comment]
Thats your opinion ;)

**Comment by Lheana** [comment]
I am sure rezzing someone with the insta rez tactic was not granting an immunity, and I see no reason it should be that way.

**Comment by Zunig** [comment]
No reason? Receiving cc effects grants immunity, its kinda basic rule with exception only for zealot aoe kb and recently added sh aoe kb.  Every other stun/kb in game gives immunity. So i see no reason why this one shouldnt.

**Comment by Lheana** [comment]
The Bugtracker is for game bugs, suggestions go to the forum.
