### ISSUE TITLE
The Maw: Mailbox remains in The Maw when IC is not under siege

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#16021]
**Expected behavior and actual behavior:**

When the Inevitable City is under siege a lot of the NPCs spawn outside in The Maw for the duration of the siege. The mailbox is there too. When the city is not being sieged the NPCs correctly vanish from The Maw but the mailbox remains.

**Steps to reproduce the problem:**

Go to The Maw area shown in the screenshots below when the IC is not being sieged. The mailbox will still be there.

**Testing Screenshots/Videos/Evidences (always needed):**

![Zomega_009](https://user-images.githubusercontent.com/60266177/76806906-96472d80-67da-11ea-9efe-2affc893aaa0.jpg)
![Zomega_010](https://user-images.githubusercontent.com/60266177/76806907-97785a80-67da-11ea-8a6c-9a4d57cb1ec1.jpg)

**Comment by Kaelang** [comment]
This has been addressed in todays patch.
