### ISSUE TITLE
Visual Bug - Knight of the Blazing Sun Auras

### ISSUE THREAD

**Issue by Kalthea** [WarEmu/WarBugs#16022]
**Expected behavior and actual behavior:** When you activate the Auras on your Knight of the Blazing Sun (KotBS), it is expected to create a particle effect on your character that makes them glow depending on which auras you have active, as seen here:
![image](https://user-images.githubusercontent.com/62267423/76806481-e19c1480-67b7-11ea-8366-14b1de1ba0a8.png)

However, when you activate the auras, you simply get the glowing effect of turning on the ability at your feet, and then the aura doesn't properly show up until you change areas through a loading screen (/reloadui doesn't work).
![image](https://user-images.githubusercontent.com/62267423/76806726-9d5d4400-67b8-11ea-99d4-d42da4f353af.png)

To top it all off, it seems to function perfectly fine in Altdorf for some reason. This issue has only been observed in Troll Country, Norsca, and Nordland so far.

**Steps to reproduce the problem:** Go to any of the above listed locations that are not Altdorf, and activate the KotBS auras. Then, take flight to another location that forces a loading screen to get the particles to appear.

It should also be noted that his functions in reverse as well, as seen here where I have no auras active, but still have the particles on.

![image](https://user-images.githubusercontent.com/62267423/76806888-01800800-67b9-11ea-8353-508d7934b9fe.png)

**Comment by grunbag** [comment]
It’s due to zoning reload effect

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/8245
