### ISSUE TITLE
Sweeping Razor/Broad Severing doesnt respect its own target limit

### ISSUE THREAD

**Issue by Zunig** [WarEmu/WarBugs#16029]
Those tactics suppose to allow WE/WH to hit 2 additional targets. Instead they allow to hit unlimited amount of enemies in 25 feet radius.

Hovewer considering those classes wb performance maybe this bug should have been changed into feature.

**Comment by Gunlingers** [comment]
it is feature and intended like it is on slayers flurry tactic.

**Comment by Zunig** [comment]
> it is feature and intended like it is on slayers flurry tactic.

Sorry, what about flurry?

**Comment by Gunlingers** [comment]
the aoe caps got increased. So all dps skills that can be made to aoe by tactic got that aoe cap increased too, if they use the tactic.

**Comment by Zunig** [comment]
I was not aware of that. Thanks for info.
