### ISSUE TITLE
Stuck on loading screen after warpblade tunnel group instance

### ISSUE THREAD

**Issue by waerter** [WarEmu/WarBugs#16020]
**Expected behavior and actual behavior:**
Hi there,
I was with a group in the warpblade tunnel (near the bank) at the first boss. (the one with the lightnings) After we put it down I couldn't move. Thereupon it was said that this is a known bug and I only had to relog. Unfortunately I haven't been able to log in to any of my characters since then. The loading screen for the corresponding area comes every time, and after 30 seconds I come back to the character selection screen.

**Steps to reproduce the problem:**
I can currently reproduce this with any of my characters. My account name is waerter and the character the problem started with is Randae.

**Testing Screenshots/Videos/Evidences (always needed):**
I think you've seen the loading screen too often, so I'm not going to attach it here. If you need any log files you would have to tell me where to look or what to switch on.

**Comment by Kaelang** [comment]
Sounds like your character crashed during the run. If this happens you can type [enter] /stuck [enter] /stuck whilst on the load screen to force your character back to the T1 zone. If you are able to replicate this issue please could you provide further information / steps so the team could investigate further.

**Comment by Kaelang** [comment]
Closed - no further information provided.
