### ISSUE TITLE
Ram despawned after using a Skaven tunnel

### ISSUE THREAD

**Issue by Llauron** [WarEmu/WarBugs#16039]
On the map Black Fire pass, I spawned a ram and passed the nearest Skaven tunnel (Withered Skaven Tunnel) while towing it. Once on the other side, the ram had despawned (I checked both side) and in the following minutes, I couldn't cast any offensive abilities while mounted until I dismounted manually.

**Expected behavior and actual behavior:**
Ram should still be here after passing the tunnel.

**Steps to reproduce the problem:**
1. Spawn a ram at Gnol Baraz Keep.
2. Tow it to the Withered Skaven Tunnel.
3. Pass the tunnel and see if the ram is still here.

**Testing Screenshots/Videos/Evidences (always needed):**
Tried to reproduce the bug while recording it worked. Left the ram 3 minutes inside the keep while fighting/waiting for other players and ram despawned another time..

**Comment by Kaelang** [comment]
"Tried to reproduce the bug while recording it worked."

Does this mean this isn't a bug, or that you have a video?

**Comment by Kaelang** [comment]
Closed - No further information.
