### ISSUE TITLE
Typo in Karl Franz speech in city siege

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#16035]
**Expected behavior and actual behavior:**

Should be "brightly", not "britghtly"

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Lotharic_447](https://user-images.githubusercontent.com/7400/76976556-6a3fbf80-6934-11ea-81d8-d16afe7429e2.jpg)

**Comment by Lheana** [comment]
This has been fixed with the patch of 21/03/2020.
