### ISSUE TITLE
"Hulking Brute" Career Tactic Doesn't Affect Stats Properly

### ISSUE THREAD

**Issue by kekarino** [WarEmu/WarBugs#16033]
**Expected behavior and actual behavior:**
When I assign the career tactic "Hulking Brute" to my career tactic bar it doesn't immediately increase my base toughness and initiative by 160 as it claims it will. The career tactic "Brute Force" increases my Strength by 160 and it immediately increases my base strength by 160 when I add it to my career tactic bar. My only conclusion is that the career tactic "Hulking Brute" isn't working properly, as a similar tactic that raises a base stat does so seamlessly.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![ROR bug](https://user-images.githubusercontent.com/62340532/76965793-490ead00-68fb-11ea-8520-116d84bab1b2.png)

**Comment by Alfred19** [comment]
Just guessing since its a common mistake... are you in the correct mutation?

**Comment by grunbag** [comment]
It works fine if you have the right mutation
