### ISSUE TITLE
Respec bug

### ISSUE THREAD

**Issue by fornicator** [WarEmu/WarBugs#1603]
I used my book of binding on my BW Poopn to get back to breurs encampment.  On arrival I was immediately chickened as I should have been.  I went to the trainer and respecialized my mastery points and trained up to unlock spreading flames.  Upon exiting the menu I noticed I was no longer a chicken, but was flagged for RvR.  I then proceeded to the RvR lake to test out if I had broken something by trying to use abilities on players.  I was indeed able to kill players 20 levels lower than me, circumventing the chicken system. Killing me awarded 481 rp to the enemy

**Comment by milosxe** [comment]
It has probably to do with the respec clearing every buff and debuff, and that seems to include chicken debuff too.

**Comment by ozarmidrashim** [comment]
Confirm @ milosxe.

**Comment by Tiggonos** [comment]
ah that explains the irradical advice chat about unkillable players in t1 yesterday well done for reporting this!
