### ISSUE TITLE
Water mount bug

### ISSUE THREAD

**Issue by Teefz** [WarEmu/WarBugs#16037]
Entering shallow water (deep enough to dismount you) will visually remove your mount, but you are able to keep the movement speed from mounting. Thus allowing you to run super fast.
**Expected behavior and actual behavior:**

Entering water should dismount you and remove movement speed buff.

**Steps to reproduce the problem:**

1. Mount up and find water.
2. Jump in and out of water.
3. Profit.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Nenolia** [comment]
I made a short video after I got the bug

[water mount speed bug.zip](https://github.com/WarEmu/WarBugs/files/4431341/water.mount.speed.bug.zip)
