### ISSUE TITLE
forum Armory base function totaly broken,

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#16038]
There are several issues with forum armory atm

-if you look for a character by partialy imput the name sometimes it wont find it (need complete name)
-if trying view a char like , lf tesq it will open nothing
-cannot find itiem i have equipped if i lf in the armory database, for exemple lf sovereign only give 4 results in total.

NB this started to happen from 1 week ago, i reporting now cause i tough it was being updated and such so was something normal but atm it's a bit long is in this state and it feel like something gone wrong

**Comment by Lheana** [comment]
Armory is offline for now, it's intended.
