### ISSUE TITLE
Deathblow

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#1604]
This quest cannot be completed - it properly counts your attempt to speak with Kesida Garalond (and goes into "completed" state with orange icon), but when you click "Complete" in dialog with her, the dialog closes and nothing happens.

**Comment by Reggaewaldo** [comment]
I will have to check this ingame, cause it looks ok in the DB.

**Comment by Meralors** [comment]
Quest fixed ;)
