### ISSUE TITLE
Close Quarters (BW) Tactic not working 

### ISSUE THREAD

**Issue by emailkook** [WarEmu/WarBugs#16049]
Yesterday I put on Close Quarters and was testing it out in open PvP trying the single target bolt and AoE bolt targets and their cast times were still the same. The requirement is within 20ft but I would be in near melee range to test it and it was still casting on its normal cast time.

**Comment by gittoaster** [comment]
it's working tested on bright wizard

**Comment by Lheana** [comment]
It's working, I close the ticket.
