### ISSUE TITLE
Terrifying Foe Black Guard Bug

### ISSUE THREAD

**Issue by admaska2** [WarEmu/WarBugs#16042]
![Terri](https://user-images.githubusercontent.com/43276959/77066875-3f14a900-69e4-11ea-95c5-ac4308fd6c36.png)

This Tactics Doesn't work, 

Tested on the dummie with a .getstat at 100 hate

At 0 hate I have 203 tougness, and at 100 hate stil have 203
Doesent affect the the tougness at all .

![terri2](https://user-images.githubusercontent.com/43276959/77067041-9450ba80-69e4-11ea-9d46-1a0e5bb6ff37.png)

**Comment by Tesq** [comment]
you need to buff yourself using the skill hatefulls trike, it's not an automatic increase/decrease based on hate, it work fine on my bg.
