### ISSUE TITLE
Chrace & Blighted Isle not giving rp/xp/inf rewards for lock

### ISSUE THREAD

**Issue by Kanuovael** [WarEmu/WarBugs#16043]
Twice in past day, Tier 1 DE vs HE lock not giving XP/RP/INF rewards, even for locking team.
![Lock1](https://user-images.githubusercontent.com/62399501/77102695-a126db80-69ef-11ea-839b-fb576132f409.png)
Pictured after lock
![Lock2](https://user-images.githubusercontent.com/62399501/77102767-ba2f8c80-69ef-11ea-8e1d-7ce856396cfa.png)
Picture following lock
![Lock3](https://user-images.githubusercontent.com/62399501/77102813-d29fa700-69ef-11ea-8f44-e8367dcd6fe4.png)
Others saying the same

**Comment by Kaelang** [comment]
This looks to have been addressed. Please confirm if you are still not receiving any rewards from Chrace / Blighted Isle.

**Comment by Kaelang** [comment]
No further information - closed.
