### ISSUE TITLE
Butcher´s Pass Lord Riposte 

### ISSUE THREAD

**Issue by Pin3appleror** [WarEmu/WarBugs#16045]
![Film TV 2020-03-19 23_32_31](https://user-images.githubusercontent.com/62404761/77120823-0bfd0480-6a3a-11ea-9796-1d66efd68e14.png)

**Comment by Pin3appleror** [comment]
Insta death by riposte

**Comment by dalen** [comment]
I guess you used blurring shock on the lord

**Comment by Pin3appleror** [comment]
Yes

**Comment by fagio1989** [comment]
I was about to post it too, the skill says "it will take additional X spirit dmgs", so there's no reason he does riposte on a damage add, and if he should for any reason should be on the one who attacked him
