### ISSUE TITLE
Minor problems with mail and vendors

### ISSUE THREAD

**Issue by Endenlen** [WarEmu/WarBugs#16046]
Mail: if I click on "reply" before to get the loot out, the items are stucked and I need to close and reopen the mail to get them out.

Vendors: if I destroy an item with the vendor's window open, I'm not able to sell items anymore. I need to close the window and reopen it.

**Comment by Kaelang** [comment]
I have just tested this. I am able to speak to a vendor, delete an item, and still sell to the vendor. And I am also able to click 'Reply' and then 'Take Items'.

Please can you confirm if you are still having this problem.

**Comment by Kaelang** [comment]
No further information - closed.
