### ISSUE TITLE
Did not receive quest item!

### ISSUE THREAD

**Issue by Kilrathi01** [WarEmu/WarBugs#16052]
I completed the "Bossy Beastie" and was not given the beast token.

**Steps to reproduce the problem:**

Tried killing him again and nothing.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
Are you talking about a quest or an unlock?

**Comment by Kilrathi01** [comment]
The quest item, I was supposed to get beast token and didn’t. I got the unlock.

Sent from Yahoo Mail for iPhone


On Saturday, March 21, 2020, 2:31 PM, Lheana <notifications@github.com> wrote:




Are you talking about a quest or an unlock?

**Comment by Lheana** [comment]
You seem confused. I think you are talking about Bestial Token, which is not a quest item at all. Moreover, completing the ToK unlock Bossy Beastie does not give a Bestial Token as reward.
As said in the text when creating a Bugtracker ticket, **refer to RoR Wiki for anything related to Tome of Knowledge**.
