### ISSUE TITLE
Champs challenge

### ISSUE THREAD

**Issue by M0rf** [WarEmu/WarBugs#1605]
Was fine not long ago but recently you have been able to ch ch someone after they have been punted(cant punt someone while in ch ch), it is greyed out but still able to be used. Clarification from someone else would help with this but im sure i have seen ppl get out of ch ch with focus mind, again was fine not long ago.

**Comment by Evildoor** [comment]
There is a ticket about this skill: https://github.com/WarEmu/WarBugs/issues/1167. Discussion should be made there.
