### ISSUE TITLE
[IC] Stage2 defenders can exit portal before stage starts

### ISSUE THREAD

**Issue by BomblingTV** [WarEmu/WarBugs#16054]
**Expected behavior and actual behavior:**
In Altdorf the Defenders are ported back to their Spawnbarrier in all stages. But in IC the defenders are not ported back if they have used their Granted ability Army-recall and then exit the barrier (or jump off the cliff (unsure about if the main issue is the barrier is clickable or if they can just jump off the side to the "bridge") Basicly meaning an organized force can set-up an instant attack on the NPC lords down south at the attackers spawn point, unintendedly and without mirror for how Altdorf behaves.

This can be used to setup an ambush at Outcrop BO where a SH Kaboom can punt an entire loading Order-warband off the nearby edge while the attackers load, or by having Destro defenders have momentum by attacking the 2Order NPCs south and snowballing their wincondition of if all 4 lords die, the defenders win the stage.

**Steps to reproduce the problem:**
Stage2 IC
Defenders use Granted Ability
Defenders leave their spawn point to avoid getting automatically summoned back in during preparation time period.

**Testing Screenshots/Videos/Evidences (always needed):**
https://www.twitch.tv/videos/571796949?t=03h26m21s
You can even see Destro know how this works, from how they spread the knowledge how to avoid getting ported back in /sc chat. Within this timestap 1minut before you can also see how the Destro players can click on the spawn barrier to exit, as it is not behaving in Altdorf for the defenders.

**Comment by dalen** [comment]
He used army recall, so then he won't get teleported back at 30s mark.

The issue is that destro can exit the barrier between state 1 and stage 2.

**Comment by dalen** [comment]
You are not supposed to get teleported if you have used army recall already. But the issue here is that destro can exit the barrier before stage 2 starts.
