### ISSUE TITLE
Royal Crest item tooltip

### ISSUE THREAD

**Issue by Antalor** [WarEmu/WarBugs#16050]
**Expected behavior and actual behavior:**
Royal Crest item tooltip gives us information that we can convert this item into another (Invader Crest I believe) but it does not work at all. 

**Steps to reproduce the problem:**
Well, I don't know what is Dev's plan about this one, if it should work in it's state or it's just a bug / some kind of spoiler which work as intended and conversion will eventually be added in the future. 

**Testing Screenshots/Videos/Evidences (always needed):**
![royal crests](https://user-images.githubusercontent.com/13917674/77155053-392ece80-6a9d-11ea-9ed4-44d01a3a5cec.png)

Best Regards.

**Comment by Vayra** [comment]
It is supposed to convert into Warlord's Crests (which then convert down into Invader), which are not currently implemented.

**Comment by MaxHayman** [comment]
removed convertable notice
