### ISSUE TITLE
Control - Step 14

### ISSUE THREAD

**Issue by HeiLei1994** [WarEmu/WarBugs#16053]
Control Epic Tier 3 quest High Elf

I killed Raedhyn the Scarred at 49k/56.4k.
He drops an 'Orb of Sight', examine it to turn in your quest. 

However when I was about to start the next part, I got attacked by a walker (damn you Graroth...) and moved my character and lost the quest window. I tried to kill Raedhyn again but he won't drop the orb again, is there a way for me to continue the epic quest/start next part?

**Comment by Lheana** [comment]
You are able to restart the quest where you stopped it by talking to the last NPC that gave a step of this quest line.

**Comment by HeiLei1994** [comment]
Thank you, you are correct.
