### ISSUE TITLE
city siege stage 2

### ISSUE THREAD

**Issue by Bugzer** [WarEmu/WarBugs#16057]
last city siege i was in IC siege 1 where in stage 2 both faction killid all heroes but destro won it i thought it should be a tie game when all heroes die could a gm or dev look into it?

**Comment by keunglh** [comment]
if all NPC champs die, defenders win

**Comment by Bugzer** [comment]
gm gambero told me diffrent and past city use to be a tie so they change it?

**Comment by MaxHayman** [comment]
Defenders win if all lords are destroyed
