### ISSUE TITLE
[City Siege][IC] Destro Lords are attackable much earlier

### ISSUE THREAD

**Issue by bosli42** [WarEmu/WarBugs#16059]
In Altdorf, the moment the enemies lords can be attacked seems to be more or less the same. However in IC, the destruction Lords leave their safe area much earlier (maybe about 10 seconds? not sure), giving order the chance to DPS them faster.

**Comment by MaxHayman** [comment]
In Altdorf the Order Lords leave immediatly which mirrors this instance where in IC the Destruction Lords leave immediatly.
