### ISSUE TITLE
Sentinel Influence weapon - Exchange for Sentinel Soul impossible

### ISSUE THREAD

**Issue by Irunae** [WarEmu/WarBugs#16067]
Hi,
I would like to exchange my "Juvenile" sentinel influence weapon for a "sentinel soul" at the merchant but it does not work when i validate.
I never equiped this "Juvenile" weapon.
Here is the a screenshot.

![image](https://user-images.githubusercontent.com/61795541/77248023-9611bc80-6c36-11ea-85e9-bd64b4f7f471.png)

**Comment by Lheana** [comment]
That's because you need 40 gold too. When you click on "Buy" you should have the message "You don't have enough money to buy that." that appears in your chat.
![Lheawll_006](https://user-images.githubusercontent.com/11537611/77308914-02a2bf00-6cfc-11ea-8885-1a00f3c068a1.jpg)

**Comment by Irunae** [comment]
Thank you !
