### ISSUE TITLE
Nordland quest "A Son's Sacrifice" - Empire racial trophy quest is missing/bugged.

### ISSUE THREAD

**Issue by empiresun14** [WarEmu/WarBugs#16060]
Hello, it seems that quest 'A Son's Sacrifice' is missing or it's bugged. Older characters possess trophies from this quests but none of newer ones which were created in past few weeks. The quest should be obtainable in Nordland from NPC "Scrivener Elwin" in Grimmenhagen Village, from which Empire characters would get racial trophies (Empire Sun Emblem, Holy Codex etc) at level 2. Following quest line did not open it, as it should be.

**Comment by Lheana** [comment]
The quest has been disabled several weeks ago to be in line with the latest changes on official on starting areas.

**Comment by empiresun14** [comment]
I see, thanks for reply. Ps. Will those changes be implemented on dwarf/elf starting areas for their racial trophy, cause those quests are still available? Thanks in advance. @Lheana

**Comment by admanb** [comment]
Are these intended to be permanently inaccessible or is there a plan to replace this quest line?

As a side question, I'm guessing similar quests were removed from the other factions?

**Comment by Lheana** [comment]
This quest has been disabled to be in line with the latest changes made on official to the chaos and empire starting areas. But similar quests in greenskin, dark elf, high elf and dwarf must still be available.
