### ISSUE TITLE
My charcater is not gaining Renown when killing players

### ISSUE THREAD

**Issue by TheFibrewire** [WarEmu/WarBugs#16062]
My character Arhar, an Iron breaker is unable to gain renown while killing players in both scenarios and open world. It was fine until the server restart happened. Kindly fix this. My character is level 10 and RR is just 8 so its not capped.

**Comment by Lheana** [comment]
Please provide screenshots.

**Comment by Kaelang** [comment]
No screenshots provided. Issue closed.
