### ISSUE TITLE
Issue with "Control" quest

### ISSUE THREAD

**Issue by 2dnyakawaii** [WarEmu/WarBugs#16066]
Ive done all the requirements, but NPC doesnt respond.

![Beardedrock_003](https://user-images.githubusercontent.com/62499482/77246319-1d5f3000-6c37-11ea-8d3f-1aea3db8db93.jpg)

**Comment by Lheana** [comment]
That's because you don't turn in this quest by talking to an NPC.

**Comment by 2dnyakawaii** [comment]
am i dumb or? how should i turn in this quest?
![Beardedrock_004](https://user-images.githubusercontent.com/62499482/77250499-6922d100-6c59-11ea-91b7-f4728c7f7965.jpg)

**Comment by Lheana** [comment]
Bugtracker is not made for player support. It is made for game issues. So find help from players or from the RoR Wiki.

**Comment by 2dnyakawaii** [comment]
well ty for the answer
