### ISSUE TITLE
Constant Crashing out of game on one character

### ISSUE THREAD

**Issue by ArKreoss** [WarEmu/WarBugs#16063]
Title:

Constant game crash when playing Chaos Warrior Character Hollowcore - created before December 2019

An introduction:

When I play on the character Hollowcore; a level 8 Chaos Warrior - the game constantly crashes after a random time period; either 10 seconds through to 3 minutes.

Details:

I recently came back to the game after a hiatus - and now when I play my Chaos Warrior Hollowcore he gets randomly disconnected after a random time period; and moved between zones at random? I've been moved back to the Chaos starting zone, the chapter 2 warcamp, the inevitable city and beyond. 

Evidence:

Unable to provide visible evidence as all it would be is a log in screen? No error codes are shown on the dc.

Additional Information:

N/A

How to reproduce the bug:

Log in as the character and play.

**Comment by ArKreoss** [comment]
I've attached a log from the game - I honestly dont know if it helps or not; but looking at it seems to show a line in the log where the server appears to be removing me (unless I am wrong which it probably is because I dont know error codes!)
[login.032220.Log](https://github.com/WarEmu/WarBugs/files/4364923/login.032220.Log)

**Comment by ArKreoss** [comment]
Also - now the game crashes whenever I load another character and go into a SC. I have followed the forum post on stopping crashes by turning everything either off or down - but its still happening.

**Comment by Lheana** [comment]
The Bugtracker is not made for crashing issues. Please read our tech forum, or ask for advice in our discord.
