### ISSUE TITLE
Game crashes on name registrar Accept

### ISSUE THREAD

**Issue by baklavoth** [WarEmu/WarBugs#16068]
I've been playing RoR for a while, but I've never attempted to register a last name. Upon doing so, I am getting a consistent crash.

**Steps to reproduce:**
Log on to my account and my Knight of the Blazing Sun character ("Garcia"). Approach the name registrar in front of the palace in Altdorf. Enter a desired last name ("Torquemada", so a lengthy one) and press Accept. Perhaps a string length issue? "Garcia Torquemada the Knight of the Blazing Sun" is perhaps too long for some tome entries. Just an idea.

**Expected behavior:**
Last name is successfully added to the character.

**Actual behavior:**
Game crashes with the message "The server has closed your connection. This could be because the server is restarting, or because you were removed by the server staff". However, the server is running and a server reset is not in place. Upon next login, the last name was not added to my character. This behavior is consistent for me.

**Screenshots:**

![Garcia_004](https://user-images.githubusercontent.com/62516626/77256495-05a39e00-6c6f-11ea-9045-1e2b4ae53cba.jpg)

![message](https://user-images.githubusercontent.com/62516626/77256563-60d59080-6c6f-11ea-8ba7-ebf6589f8e50.png)

**Comment by Lheana** [comment]
It's intended: you can not set this as last name. It's not due to the length of the name, but due to the name itself.
