### ISSUE TITLE
Dwar Tieer 4 Influence reward

### ISSUE THREAD

**Issue by Fearoshima** [WarEmu/WarBugs#16064]
Finished Tier 4 Influence reward on Fearoshima, went to choose my elite reward and my Influence expirience was set back to 0 without being able to pick elite reward.

**Comment by Fearoshima** [comment]
Dwarf Zone

**Comment by Lheana** [comment]
Screenshot?

**Comment by Fearoshima** [comment]
Sorry, I was wrong, I was a few points short and didn’t notice. I want to thank for your quick reply and say sorry for my mistake.

**Comment by Lheana** [comment]
Ok then I close the ticket.
