### ISSUE TITLE
probleme d'objet

### ISSUE THREAD

**Issue by kainoby** [WarEmu/WarBugs#16071]
bonjour j ai un soucis avec le bonus de set sur les piece genesis qui ne fonctionne pas sur reste de la genese du guerisseur et aspect de la gene du guerisseur le bonus de set +2 ne fonctionne pas 

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
Screenshots?

**Comment by kainoby** [comment]
envoyé : 23 mars 2020 à 11:34de : Lheana <notifications@github.com>à : WarEmu/WarBugs <WarBugs@noreply.github.com>cc : kainoby <boullen.aurelie@orange.fr>, Author <author@noreply.github.com>objet : Re: [WarEmu/WarBugs] probleme d'objet (#16071) Screenshots?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Lheana** [comment]
Mais encore ?

**Comment by kainoby** [comment]
et bien les bonus de set ne sont pas prit en comptes on les vois en griser c est normal ???envoyé : 24 mars 2020 à 15:19de : Lheana <notifications@github.com>à : WarEmu/WarBugs <WarBugs@noreply.github.com>cc : kainoby <boullen.aurelie@orange.fr>, Author <author@noreply.github.com>objet : Re: [WarEmu/WarBugs] probleme d'objet (#16071) Mais encore ?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Lheana** [comment]
J'ai demandé des screenshots, merci.

**Comment by Kaelang** [comment]
Closed, screenshots were not provided.
