### ISSUE TITLE
[Quest] Order T2 Epic Quest <The Greater of Two Evils> disappeared from Quest Log

### ISSUE THREAD

**Issue by xSamanar** [WarEmu/WarBugs#16079]
Hello,

Summary:
Didn't accept new quest stage from quest item's window because character moved - quest has disappeared from Tome of Knowledge/Quest Log.

Exact steps:
[https://wiki.returnofreckoning.com/index.php/Empire_T2_Epic_Quest_The_Greater_of_Two_Evils](url)

1. I have followed the quest chain to Stage 12:

> Click on Doctor Wirt's Clothes at 21.4k/40.6k to make spawn the Nurgle Chaos Spawn. Kill him to recover the Doctor Wirt's Journal.

> Examine the Journal in your quest inventory to turn in your quest.

2. I killed the Nurgle Spawn and received quest Item in my Inventory (Quest Items tab).
3. I clicked on <Wirt's Journal>, quest window correctly popped-up.
4. I was attacked and moved my character before I could read & accept the quest.
5. Quest window closed, quest item (Journal) was removed from my Inventory & Quest has disappeared completely from my Quest log.

At this stage I tried to kill the quest mob again to see if it drops the Quest item again - it didn't. I'm unable to cancel the last stage of quest to try it again because the quest is completely removed from my log. I'd appreciate your assistance if possible, since I was almost at the end of the whole quest chain.

Best regards,
Sam (Tazarr in-game)

PS. My wife was doing the quest with me on her character and she moved on to the next stage without any issues (she was able to click & accept the quest when quest window appeared).
PS2. Please find below screenshot showing my Quest log with The Greater of Two Evils missing.

![Tazarr_011](https://user-images.githubusercontent.com/62568034/77357870-2d673480-6d49-11ea-9847-b506e19f27f5.jpg)

**Comment by Lheana** [comment]
I'll give the same answer as #16053: You are able to restart the quest where you stopped it by talking to the last NPC that gave a step of this quest line.

**Comment by WAR2014** [comment]
Confirmed OP, the quest now buggy at the beginning. Quest NPC - Edmund Kraemer, quest disappeared. Require fix accordingly. Thanks!
![T2 Empire Epic buggy at beginning, no quest show on NPC](https://user-images.githubusercontent.com/17757461/83319014-c2bd0280-a27d-11ea-8ddb-06b206559957.PNG)

**Comment by Lheana** [comment]
And have you tried interacting with the corpse?

**Comment by WAR2014** [comment]
There's no corpse, the NPC was alive, and he just stood at front of the house (see the attached screenshot above).

**Comment by Lheana** [comment]
Your answer proves you haven't read the instructions of RoR Wiki, otherwise you would know what corpse I am talking about. Read it, and you'll know what corpse I am talking about, then everything should be fine.

**Comment by WAR2014** [comment]
Oh, probably you're right. Since my last T2 epicquest was nearly 12 mths ago, something may changed or my mistaken memory. I'll check more details again. Thanks so much for response. Please close the case.
