### ISSUE TITLE
slayer rampage doesnt work properly

### ISSUE THREAD

**Issue by amazinga** [WarEmu/WarBugs#16078]
The ability rampage should durate 20 seconds when you are in furious..duration are 10 sec instead
thank you

**Comment by Killamanjaro** [comment]
The ability is functioning normally, 10 secs (if furious) and 20 secs (if bezerk).

**Comment by RoR-Zomega** [comment]
The career builder states "if you are Furious, increase duration to 20 seconds".

**Comment by grunbag** [comment]
it works as intended. furious = yellow and berserk = red
