### ISSUE TITLE
The Ebon Flame( T4 epic quest line) buged

### ISSUE THREAD

**Issue by fakadokia** [WarEmu/WarBugs#16077]
It seems bug when i have to kill Riannmar Jadehart. In a youtube video is in another location and now its somewhere at mountain or underground . ive been there and there is nothing.

![Hadik_023](https://user-images.githubusercontent.com/46252156/77353582-8337de80-6d41-11ea-9a93-e2b3ef18ad87.jpg)

**Comment by Lheana** [comment]
Don't trust the old video. Trust the RoR Wiki.

**Comment by fakadokia** [comment]
Im at the red zone and its nothing there...

**Comment by Lheana** [comment]
The Bugtracker is made for **game bugs** not for player support. **Refer to RoR Wiki** is the last thing I'll tell about this ticket.
