### ISSUE TITLE
Caledor Woods not popping

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#16076]
**Expected behavior and actual behavior:**
expected - Caledor Woods should pop during high pop times, no fortress/city times
actual - I have been trying to get CW pops for solo ranked on some of my rr70+ toons this past week, sat and Sunday I tried queuing for a couple of hours but nothing popped.
It may be working as it's supposed to be but right now this part of the game is not accessible for it's intended use.
**Steps to reproduce the problem:**
T4 Caledor queue during high pop times.

**Comment by Kaelang** [comment]
The ranked queue wasn't necessarily the most popular so there is a tonne of variables into play with this report. That being said, the Ranked Scenario has recently switched to Maw of Madness and has been promoted across multiple channels. The Ranked queue should now be popping.
