### ISSUE TITLE
Earned XXX gold achievments

### ISSUE THREAD

**Issue by rakels** [WarEmu/WarBugs#16074]
Sending gold between two characters counts towards the "Earned xxx gold during your career" unlocks each time you take the gold out of the mail.

To reproduce:
- send gold from char A to char B via Mail
- Take gold out on char B
- Mail gold from char B to char A
- repeat until unlock triggers

**Comment by Lheana** [comment]
It worked that way on official too, not sure it's a real bug.

**Comment by dalen** [comment]
yes, at the moment all sources of receiving gold counts towards the unlock, including receiving it through mail or player trade. Also unsure if it is a bug or feature :)

**Comment by Lheana** [comment]
It is not a bug, we close the ticket.
