### ISSUE TITLE
Quest - Dangerous Delicacies - Poisonfin fillet does not spawn

### ISSUE THREAD

**Issue by haliphax** [WarEmu/WarBugs#16072]
**Expected behavior and actual behavior:**
Quest should spawn 3 food items. Cold One Curry and Raven Pie both spawn, but Poisonfin Fillet does not.

**Steps to reproduce the problem:**
Accept the Dangerous Delicacies quest from Rohesia Koch.

**Testing Screenshots/Videos/Evidences (always needed):**
![Screenshot from 2020-03-22 16-08-29](https://user-images.githubusercontent.com/745888/77260720-bf8f1000-6c57-11ea-83f5-747e7cd1f696.png)

**Comment by Lheana** [comment]
Same issue as #15960
