### ISSUE TITLE
Warhammer Online ROR Bug Trade skills RESOLUTION POSTED HERE

### ISSUE THREAD

**Issue by ZTFFF** [WarEmu/WarBugs#16084]
Please help!

![Warhammer ROR bug Trade Skills](https://user-images.githubusercontent.com/62587397/77395385-d62c8880-6d77-11ea-9a7a-afb6236f9a39.png)
![Warhammer ROR bug Trade Skills 2](https://user-images.githubusercontent.com/62587397/77395396-d9c00f80-6d77-11ea-8ee6-c2dbb577f12a.png)
![Warhammer ROR bug Trade Skills 3](https://user-images.githubusercontent.com/62587397/77395400-dcbb0000-6d77-11ea-8d01-fd3da2c48f4f.png)

**Comment by ZTFFF** [comment]
Hello. This is the character I was hoping to level up and play with. Unfortunately, I have spent about 6 hours on this issue so far and I'm very sad and frustrated. Everyone in advice chat has tried to help but I'm not sure anyone understands the issue. This character is 18 and is unable to learn a trade skill.  I went to learn a trade skill at level 15 and faced this problem, worked with it for a few hours and gave up, leveled some more, came back, and the issue never resolved itself. I am assuming I waited to long to train the trade skill and activated a "BUG" or a "GLITCH" of some sort. I have gone to Altdorf city "Main order city" and the 2nd elf starting city and every "Trade skill" trainer says the same thing.  As the screenshots show there is no option to learn any skill and it only has the selection for "Goodbye".  In my trade skills section on the character I have no matching abilities and therefore I have never trained anything.  I have no ability to reset.  Upon logging into lower level characters they had no problem learning a "Trade skill."  It is only this character that is facing an issue.

**Comment by Lheana** [comment]
Please try the [commands](https://wiki.returnofreckoning.com/index.php/Commands) to unlearn your gathering/crafting skills.

**Comment by ZTFFF** [comment]
The respec commands for gathering and crafting do not work.

**Comment by ZTFFF** [comment]
This appears to be some kind of BUG likely triggered from trying to learn professions once I had leveled some rather than at the beginning of the game in low level content. Unfortunately, I have exhausted all the typical solutions available.

**Comment by ZTFFF** [comment]
As you can see from the images I have no gathering or crafting skills. This is where the bug presents itself.  I never had any to begin with, the game won't let me learn any.

**Comment by ZTFFF** [comment]
IF ANYONE IS LOOKING FOR A SOLUTION AND HAS THIS SAME PROBLEM.  IT IS A BUG. 

 **I HAVE FOUND A WAY TO RESOLVE THE BUG ON MY OWN**

IF YOU ARE FACING THIS SAME PROBLEM PLEASE TAKE YOUR CHARACTER TO ALTDORF CITY. ON THE RIGHT AND LEFT HAND SIDE OF THE GALLOWS THERE ARE VENDORS IN TENTS THAT WILL STILL ALLOW YOU TO LEARN TRADE SKILLS AND RESPEC TRADE SKILLS.  THERE IS A BUG WHICH AFTER YOU REACH A CERTAIN LEVEL WILL NOT ALLOW YOU TO TRANE TRADE SKILLS FROM STARTER CITIES. AGAIN, GO THE VENDORS IN ALTDORF CITY IN TENTS AROUND THE GALLOWS.  I WILL ATTACH SCREENSHOTS LATER IF I HAVE TIME. 

.
