### ISSUE TITLE
SW stances drops randomly

### ISSUE THREAD

**Issue by Uglegutt** [WarEmu/WarBugs#16086]
-->

**Expected behavior and actual behavior:**
Expected behaviour; stances sticks until new stance is chosen

Actual behaviour; Stance drops randomly and abilities grey out in non stance fashion. 

**Steps to reproduce the problem:**
Log in, play, experience bug. Happens randomly, some days often per play session, other days happens rarely. 

**Testing Screenshots/Videos/Evidences (always needed):**
It is very hard to capture unless recording, which I dont do.

**Comment by grunbag** [comment]
Does it happen after zoning ?

**Comment by Uglegutt** [comment]
Sorry for the late reply. Yes it happens after zoning, especially in scenarios, but it also a longtime after zoning. It happens in and out of combat, and does not seem to be related to lag. I did take a screenshot, but it doesent show much. To get stances back i need to pick a new stance twice. And then not the original stance that was lost. Hope this helps.

**Comment by azpe** [comment]
You can reproduce this issue: (Level lower than 40)
-Move to ORVR where you can gain Agains All Odds buff
-Before you leave the Warcamp, activate any stance.
-Leave the Warcamp and move into ORVR.
-You'll gain AAO buff and you will lose your current stance.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16238
