### ISSUE TITLE
The Fulcrum - Dragonwake Quest

### ISSUE THREAD

**Issue by HeiLei1994** [WarEmu/WarBugs#16080]
Nothing states how to "stop" the rituals, I have been killing all kinds of cultists, but nothing registers.
No problem with destorying the tome.
Not sure if I'm missing something or if it is bugged.

**Comment by Lheana** [comment]
Are you a ranged class?

**Comment by HeiLei1994** [comment]
No, a SM

**Comment by Lheana** [comment]
I can complete the objective for stopping the ritual. Have you killed the NPC around the tome?

**Comment by HeiLei1994** [comment]
Yes, I did that before I could destoy the tome, weird

**Comment by Lheana** [comment]
Try killing them when standing closer to the tome.

**Comment by HeiLei1994** [comment]
I'll give it a try, maybe it is because I taunt away one mob at a time

**Comment by Lheana** [comment]
Yeah, there is a circle around the tome to complete the objective for killing the NPCs. The perimeter will be increased with next patch.

**Comment by HeiLei1994** [comment]
Yes, seems to be working when standing close to the tome, thank you
