### ISSUE TITLE
"Legend and Infamy" Blighted Isle DE Chapter 3

### ISSUE THREAD

**Issue by doregore** [WarEmu/WarBugs#16083]
**Expected behavior and actual behavior:**
Quest mobs should drop quest item; they don't.

**Steps to reproduce the problem:**
Get to Step 6 of the quest.

**Testing Screenshots/Videos/Evidences (always needed):**
![Untitled](https://user-images.githubusercontent.com/57435741/77392180-a478e900-6d9a-11ea-8d58-f6c23cb2b7b1.jpg)

**Comment by Lheana** [comment]
Keep killing them, it's a drop chance.
