### ISSUE TITLE
Land of Shadows quest issue

### ISSUE THREAD

**Issue by eyecourt** [WarEmu/WarBugs#16081]
Quest Target: Celedaine Duskbringer is inside the cliff, below her spawn location.
![Evilynda_000](https://user-images.githubusercontent.com/62572502/77363530-7e126980-6d18-11ea-92f7-2ff6516e2ef5.jpg)

**Comment by Lheana** [comment]
Someone pulled the NPC and he was stuck inside the ground. He has now correctly respawned.
