### ISSUE TITLE
Dwarf Ch 12 Quest "Welcher" missing interactable object

### ISSUE THREAD

**Issue by Aesir** [WarEmu/WarBugs#16096]
Welcher requires you to go to the CH 12 PQ Grimbeard Station to get an item from a crate but there are no crates around that are interactable . I believe I've found the one it's supposed to be as it looks different from the rest but it is not targetable or interactable in any way. 

![Solabreaker_000](https://user-images.githubusercontent.com/447759/77486203-5ab8ee80-6dec-11ea-8966-ceedc7f73d5d.jpg)

During the 2nd stage of the PQ, which requires interacting with other nearby crates, it raises off the ground. While it is still not interactable, I think this indicates that it is indeed the crate for the quest as this is common for interactable quest objects. 

![Solabreaker_002](https://user-images.githubusercontent.com/447759/77486237-6a383780-6dec-11ea-83f2-dd884ebd635e.jpg)

Crate should be made interactable and should give "Helmuth's Effects" or otherwise advance that quest step.

**Comment by Kaelang** [comment]
Correct GO is now there.
