### ISSUE TITLE
Mailbox -  I can not send a letter on the first attempt

### ISSUE THREAD

**Issue by DmitriyMaksimovich** [WarEmu/WarBugs#16095]
Nothing happens after clicking on the send button. Title, subject, attachments is correct.
To send a letter, you need to reopen the mailbox without closing the inventory, and then send the letter again.

**Comment by Aesir** [comment]
The workaround I've found for this is to open your inventory before accessing the mailbox.

**Comment by RoR-Zomega** [comment]
You need to have the mailbox selected when you press send.

**Comment by emailkook** [comment]
I had the same issue. You have to keep the mailbox targeted.
