### ISSUE TITLE
Dwarf Ch 12 PQ, Grimbeard Station Stage 1, Wrong NPC names

### ISSUE THREAD

**Issue by Aesir** [WarEmu/WarBugs#16094]
In stage 1 of the Dwarf CH 12 PQ Grimbeard Station, the PQ quest asks you to kill 60 "Bloody Sun Bommas" but they don't exist. The actual enemy that needs to be killed are "Bloody Sun Basha". A very minor annoyance.

**Comment by Lheana** [comment]
'Bloody Sun Bommas' designates the group of greenskins you have to kill, like 'Bloody Sun Boyz'. They are called that way because the bosses are both some 'Bommas'.
