### ISSUE TITLE
[AM] True magic is not increasing range 

### ISSUE THREAD

**Issue by Zaldra5** [WarEmu/WarBugs#16090]
True magic is the 8 piece bonus from the Sovereign set for Archmages from cities, only just got the final piece a day or so, but the ability seems to not be working.

so most of the DPS abilities of the Archmage are 100ft range this when the ability is used it should increase the range of all abilities by 20% for 10 seconds which should be 20 more feet but it just seems to go on cooldown and do nothing.

Its fairly easy to test, just find max range then take a step or two more than use True magic

**Comment by Zaldra5** [comment]
I hopped on to test the fix this morning after the patch, sadly it's still doing the same thing as before. My abilities will light up like I have range for about 2 seconds after using True Magic but won't let me cast anything and after I try to cast it will show that I am out of range again.

**Comment by Lheana** [comment]
It should have been fixed with the patch of 28/03/2020.
