### ISSUE TITLE
Mara actionbar bug

### ISSUE THREAD

**Issue by DmitriyMaksimovich** [WarEmu/WarBugs#16092]
https://github.com/WarEmu/WarBugs/issues/15071
Still actual. Cant replace 1 ability, only for path of brutality.
![Dimakss_003](https://user-images.githubusercontent.com/46728779/77484585-f887da00-6e3b-11ea-930c-cea60ef50701.jpg)

**Comment by SilverWF** [comment]
This is well known bug and it's related to Morale Circle addon only.
Check addon page for solutions https://tools.idrinth.de/addons/moralecircle/
