### ISSUE TITLE
the price of failure quest

### ISSUE THREAD

**Issue by Melkoril** [WarEmu/WarBugs#16098]
quest give is at Tamorir's Malice in Dragonwake, Dark Elf Chapter 18
the first part of the quest works, but then you get a second quest of the same name to go kill three leaders of the servants rebellion
When you kill the servants, it counts them as killing dwarves, since when I killed one it gave me an accomplishment of killing 100 dwarves.
Then when you bring the heads back to the camp and put them on the spike, even though you put them on all three spikes, it doesn't register all three have been put on spikes
[bug report.docx](https://github.com/WarEmu/WarBugs/files/4378816/bug.report.docx)

**Comment by Lheana** [comment]
Stand closer to the pike, and it will work.

**Comment by Melkoril** [comment]
You're right.  That worked.  Thanks.
