### ISSUE TITLE
Training Course Quest

### ISSUE THREAD

**Issue by pixie126** [WarEmu/WarBugs#1610]
This quest will not complete.  I can talk to Viktor Riese to turn it in, but it won't complete.  Nordland, Empire Chapter 1.

**Comment by Reggaewaldo** [comment]
I have now made the change in the DB so that you leave the quest to Seer Thaena as the quest text descibes.

**Comment by Evildoor** [comment]
Still bugged according to #2124

**Comment by Ryanfawkez** [comment]
On Oct 16, Reaggeawaldo fixed the Destruction named quest "Training Course" (ID 51824); not the Order named quest "Training Course" (ID unknown due to duplicate database entry.)

Will check Order quest by searching by start NPC.
