### ISSUE TITLE
Lasting Eruption Blast Potion hotbar displaying wrong # of items in bag

### ISSUE THREAD

**Issue by Snifflebutts** [WarEmu/WarBugs#16100]
**Expected behavior and actual behavior:**
Expected to display the available amount of the items in the user's bag
Actually display the amount of items in the user's bag with a "1" as prefix

**Steps to reproduce the problem:**
Any amount after 10 blast potions available in backpack

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/62215736/77534889-9c7d8e00-6eed-11ea-9dcc-fa03c2894192.png)
![image](https://user-images.githubusercontent.com/62215736/77534893-a0111500-6eed-11ea-82aa-4848bb23bbc4.png)
![image](https://user-images.githubusercontent.com/62215736/77534918-b4eda880-6eed-11ea-9efc-36e10fc94b61.png)

**Comment by Lheana** [comment]
Do you have 10 of this potion in your bank?

**Comment by Nefarian78** [comment]
Happens to me all the time aswell. No potions in bank.

**Comment by Snifflebutts** [comment]
I never keep them in my bank as I constantly using them, and I just did a check as well, none in bank.

**Comment by Snifflebutts** [comment]
> Do you have 10 of this potion in your bank?

No, I checked, and I would never put them in bank anyway since I buy them and use on the go

**Comment by Kaelang** [comment]
![image](https://user-images.githubusercontent.com/60117106/82149082-1c6d0800-984e-11ea-82aa-ec66e480662d.png)
![image](https://user-images.githubusercontent.com/60117106/82149090-24c54300-984e-11ea-9715-dfb0c04fc7cf.png)
![image](https://user-images.githubusercontent.com/60117106/82149101-34448c00-984e-11ea-9728-3532fa901341.png)

Tried to replicate in multiple situations and was unable to trigger this. Please can you re-open if this issue remains persistent with additional replication tips.
