### ISSUE TITLE
Cannot open Loot Bag

### ISSUE THREAD

**Issue by Betadan6843** [WarEmu/WarBugs#16102]
Unable to open Greater Loot Bag in my bags

**Expected behavior and actual behavior:**
Expected: Right click bag and it opens
Actual: Right click bag and nothing happens

**Steps to reproduce the problem:**
I'm guessing here...
Log out with a loot bag in your inventory

**Testing Screenshots/Videos/Evidences (always needed):**
https://youtu.be/pByWYO13Xww

**Comment by Kaelang** [comment]
Where did you get this back from?

Also - have you tried to clear your cache / relog? Is the bag still not opening?

**Comment by Kaelang** [comment]
No further information - closed.
