### ISSUE TITLE
Dragonwake didnt lock when 5 stars

### ISSUE THREAD

**Issue by accNumber13** [WarEmu/WarBugs#16109]
Today Dragonwake didnt lock when 5 stars and all BO's where holded for 20 minutes, also keep progress bar didnt disappear and keep continued to rank up.

unfortunately i did not take the screenshots ((

**Comment by Kaelang** [comment]
The 5* feature looks to be working as intended for the past few weeks. If Order/Destro take any BO, the timer will reset. 

Please return with further information if this happens again in the future.
