### ISSUE TITLE
gunbad mid wing issue

### ISSUE THREAD

**Issue by turki79** [WarEmu/WarBugs#16101]
![Turki_000](https://user-images.githubusercontent.com/45051573/77541530-d763cf80-6eb5-11ea-9660-f85ed5127894.jpg)
after killing wight lord solithex's we go and and we cant move to the squig boss pq reset and there is this barrir check the image

**Comment by turki79** [comment]
redid mid again started with the squig boss and still the barrire is back up so we cant get to wight lord solithex's

![Turki_001](https://user-images.githubusercontent.com/45051573/77549094-78f01e80-6ec0-11ea-9642-41397dbdce82.jpg)

**Comment by Lheana** [comment]
Duplicate of #16034
