### ISSUE TITLE
BE dungeoun influence problem

### ISSUE THREAD

**Issue by wildwindblows** [WarEmu/WarBugs#16106]
Hello,
I've join the BE dungeon with a group and we killed first boss and earn 1k influence from it. After first boss killed group disbaded. One day later, I found an another group and we killed all bosses. Although I have no lockout for last boss, it didn't give me inf. Therefore, I decided to bugtracker it. 
Thanks.

**Comment by Kaelang** [comment]
Did you receive loot / anything from the last boss? Did you die during the fight? Would need more information validate this issue.

**Comment by Kaelang** [comment]
No further information provided - closed.
