### ISSUE TITLE
You can bypass the 40/40 namechange requirements on an alt character. 

### ISSUE THREAD

**Issue by Kaelang** [WarEmu/WarBugs#16107]
I believe you need 40 CR / RR to change your characters name. However, after using the name change command, I was able to change my alts character name. I'm not sure if the token system is meant to be account wide, but this means those with alts who are 40/40 can name change other characters. 

I changed Kaelangfarmer to Kaelangfarm (level 1 marauder).

**Comment by wargrimnir** [comment]
The token system is account wide, it should be restricted to one token per month.

**Comment by Kaelang** [comment]
Probably fine then - I thought it was char bound.
