### ISSUE TITLE
Wyrmbreaker quest Chapter 18 Dark Elf

### ISSUE THREAD

**Issue by Melkoril** [WarEmu/WarBugs#16112]
There is a scroll quest item that you get called Drakesinger Scroll.  You are supposed to read this scroll "over" the brazier in the PQ Dragonwatch Falls, and I think it is supposed to complete the quest and give you a new quest.  I got the new quest, and completed it.  I got the new quest when I read the scroll near the brazier.  But it didn't complete the Wyrmbreaker Quest.

The quest directions just say "read the scroll" but you can click the quest item as many times as you want, as close to the brazier as you want, but it doesn't complete the quest.

![bug_report_Wyrmbreaker](https://user-images.githubusercontent.com/59775887/77715914-deb8d500-6faa-11ea-970b-e748b26da8ee.png)

**Comment by Melkoril** [comment]
This is also the case whether you the brazier targeted or not:  nothing.

**Comment by Lheana** [comment]
Have you tried:
- using the Scroll in your inventory while targeting a brazier?
- interacting with a brazier?

**Comment by Melkoril** [comment]
Yes, I tried both.  Unfortunately whatever you do it doesn't seem to work.

**Comment by Lheana** [comment]
It works fine for me.
![Anash_024](https://user-images.githubusercontent.com/11537611/77761455-5e40b580-7038-11ea-9f89-7e58470e745a.jpg)

**Comment by Melkoril** [comment]
Ok, that's good.  But, since it doesn't work for me, can you update the quest as completed in my toon.  Otherwise I am going to have this quest sitting there forever with no way to complete it.

**Comment by Lheana** [comment]
There is no reason you can not complete this quest.

**Comment by Melkoril** [comment]
Well, as I explained, for my toon, this quest is bugged.  It's great that its not bugged for someone else, but that doesn't really fix the bug.

**Comment by Lheana** [comment]
Because there is surely no bug.

**Comment by Melkoril** [comment]
But if I am doing the exact same behavior as you are saying to do, and nothing is happening, then obviously there is a bug.

**Comment by Lheana** [comment]
Show me a screenshot.

**Comment by Melkoril** [comment]
Ok will do after work.  Thank you very much for your time and attention.  I really do appreciate it.

**Comment by Melkoril** [comment]
Ok you are right.  It's not bugged.  My bad.  It worked.  Thank you.
