### ISSUE TITLE
Special Delivery - Talabecland - Order

### ISSUE THREAD

**Issue by Wesleth** [WarEmu/WarBugs#16111]
https://www.youtube.com/watch?v=57z7f4KZxTc (lag is my end)

**Expected behavior and actual behavior:**
Expected - Iron Box collectible, or drops from named mob.
Actual - Doesnt

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
Like for your previous report for the exact same thing, the ticket is closed because there is already another ticket for the same issue: duplicate of #15451

**Comment by Wesleth** [comment]
Previous one didn't have a video. Was told that helps get it fixed quicker.
Apologies

**Comment by Lheana** [comment]
Thanks, but in this case, send the video by commenting on the original ticket.

**Comment by Wesleth** [comment]
Aha! Genius! On it
