### ISSUE TITLE
Peak's Edge/A Prod In the Right Direction - Order

### ISSUE THREAD

**Issue by Wesleth** [WarEmu/WarBugs#16110]
https://www.youtube.com/watch?v=KiK6kySnyOY

**Expected behavior and actual behavior:**
Expected - Mobs spawn, quest completable.
Actual - No mobs spawn, cant complete quest or PQ associated.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
Duplicate of #15156
