### ISSUE TITLE
Tok- Finishing PQs +unarmored variant Not working (patch note 21/3/2020)

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#16117]
I tried unarmored PQ no unlock on Tok. i did it more than 10.

May be you could have a look?

Thank you !

**Comment by dalen** [comment]
This was likely due to a bug that cleared participants from PQs after you completed them, unless you walked out of the PQ area and entered again each time you finished it.

A patch is coming tomorrow.

**Comment by Lheana** [comment]
It should have been fixed with the patch of today.
