### ISSUE TITLE
Choppa/Slayer Wounds difference on Sov set 

### ISSUE THREAD

**Issue by Ghatisgob** [WarEmu/WarBugs#16128]
The wounds difference was made on purpose or its a "bug" ?

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Capture](https://user-images.githubusercontent.com/25305100/77825274-797af600-7108-11ea-9109-e0426e92b0af.PNG)
![Capture1](https://user-images.githubusercontent.com/25305100/77825277-7c75e680-7108-11ea-943c-1b915d880538.PNG)

**Comment by wargrimnir** [comment]
Was corrected already.
