### ISSUE TITLE
Scenario join Failure

### ISSUE THREAD

**Issue by Raegor** [WarEmu/WarBugs#16124]
Hey,

recently i have the following issue when playing warhammer. I get a scenario pop, i click accept and get the quitter. Getting the "Scenario join failure: No pending scenario." message in chat. Never had this issue before, but now it happends to me at every 10th scenario or so.

![InkedSpitzohrklopfa_035_LI](https://user-images.githubusercontent.com/42284326/77823008-1c774400-70f8-11ea-9baf-b132878f76da.jpg)

I used an addon to queue for scenarios which i deleted but this didnt solve the problem. Still getting this error.

**Comment by Kaelang** [comment]
Which scenario was you trying to queue for?

**Comment by Raegor** [comment]
Sorry dont know, i usually queue for all of them or at least 3

**Comment by Raegor** [comment]
> Which scenario was you trying to queue for?
Sorry dont know anymore, usually i queue for all of them or atleast 3

**Comment by Kaelang** [comment]
Without knowing what scenario is giving this error, we wouldn't be able to look to replicate the problem. If you continue to have this issue, and are able to identify what is the cause of the message, you are free to open a new report.

Thanks.
