### ISSUE TITLE
Fall damage is EXTREMELY sensitive. 

### ISSUE THREAD

**Issue by Kaelang** [WarEmu/WarBugs#16126]
Report of people jumping from some stairs in IC and being taken to 50%. See attached screenshot from before and after a small jump.

I'm not sure if this is intentionally strong but seems quite excessive. 

![unknown](https://user-images.githubusercontent.com/60117106/77824675-577b7680-70fc-11ea-8d6f-286628864a6a.png)
![image](https://user-images.githubusercontent.com/60117106/77824696-711cbe00-70fc-11ea-8d7a-af587a4787c4.png)

**Comment by Kaelang** [comment]
![image](https://user-images.githubusercontent.com/60117106/77824818-42ebae00-70fd-11ea-827a-2f55d5b41262.png)
![image](https://user-images.githubusercontent.com/60117106/77824822-47b06200-70fd-11ea-9215-fdc30caec885.png)

**Comment by Kaelang** [comment]
Could be overtuned, but this will definitely change the oRVR gameplay. Counter pushes from keeps likely won't happen as often, or be as successful. But thought I'd share just incase this isn't intentional values.

**Comment by Kaelang** [comment]
![image](https://user-images.githubusercontent.com/60117106/77825079-f73a0400-70fe-11ea-911a-bfa407239818.png)
![image](https://user-images.githubusercontent.com/60117106/77825083-fdc87b80-70fe-11ea-8073-9400aec23ff9.png)

Final screenshot - but this side jump is hitting harder than some brighty bombers ^^

**Comment by Lheana** [comment]
The fall damage has been reviewed to be more in line with official. So I am not sure this is a bug.

**Comment by Kaelang** [comment]
> The fall damage has been reviewed to be more in line with official. So I am not sure this is a bug.

Very true, could likely be the correct values. Just thought I'd share incase it's overtuned.

**Comment by Kaelang** [comment]
Running off rather than jumping does seem to significantly reduce damage taken.

**Comment by MaxHayman** [comment]
It's calculated at the acceleration you have when you impact the ground. If you jump you start falling at a higher point.

**Comment by Kaelang** [comment]
> It's calculated at the acceleration you have when you impact the ground. If you jump you start falling at a higher point.

Ah thank you Max. I'll close this up now, just wanted to bring some attention. No more mount speed run jumps!

**Comment by dalen** [comment]
> > It's calculated at the acceleration you have when you impact the ground. If you jump you start falling at a higher point.
> 
> Ah thank you Max. I'll close this up now, just wanted to bring some attention. No more mount speed run jumps!

in next patch the "Died from falling while on a mount" will be in game though :D
