### ISSUE TITLE
[The Ebon Flame] T4 Dark Elf Epic Quest: Teleport out of the Map.

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#16120]
Hello,
i searched for a Bug Report but couldn't find one for this issue. If it's a duplicate, please delete this Post.

There is a Bug in the T4 Dark Elve Epic Quest, after the fight with Riannmar Jadehart. If you go through the Door of Flame, you get to a Place outside of the Map called Dagerous Territory. No Map available.

Best regards,
Arasjel

![Arasjel01](https://user-images.githubusercontent.com/62779101/77810938-7693ed00-7097-11ea-8d19-3ddcaa595b2c.png)
![Arasjel02](https://user-images.githubusercontent.com/62779101/77810943-7c89ce00-7097-11ea-8546-57b8c6d6ac7d.png)

**Comment by Lheana** [comment]
I thought I could fix it, but it's not possible for now. So it will stay that way. Anyway, you are just at the edge of Eataine when you leave the Flameshrine, so not a big issue.

**Comment by Lheana** [comment]
This has been fixed few patches ago.
