### ISSUE TITLE
One Manling's Rubbish - Order Quest - Black Crag

### ISSUE THREAD

**Issue by Wesleth** [WarEmu/WarBugs#16129]
https://www.youtube.com/watch?v=_M-qaiJYoDU

**Expected behavior and actual behavior:**
Expected - Cave open, item discoverable
Actual - Cave sealed by magical barrier, persists throughout all stages of PQ and during downtime between

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
Your video is set to private.

**Comment by Wesleth** [comment]
Fixed, apologies

**Comment by Wesleth** [comment]
How do I close this? Im an idiot. Decided to swing by it on my way to Snizzort, theres ANOTHER cave, totally separate from the PQ, named similarly. The quest text is confusing and possibly misleading, but the cave to the NORTH of the quest marker area is fully explorable and the item can be found within.

Apologies to waste your time.
