### ISSUE TITLE
Wrong Emblem awarded after SC Victory

### ISSUE THREAD

**Issue by Ltrico** [WarEmu/WarBugs#16123]
Hello !
Since yesterday on my Ironbreak 37/40 (now 38/41) whenever winning a Scenario I am awarded with (7) Soldier's Emblem instead of Officer's Emblem. As you can imagine it's quite a handicap towards equiping my character :(.
I messaged GM Srul in game who confirmed it's most likely a Bug. Apparently Same bug happened years ago.

My Character is Narlik Torkinson.

Thanks for the hard work lads !

**Comment by LTP-Blackroot** [comment]
+1

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/15821
