### ISSUE TITLE
Glomp

### ISSUE THREAD

**Issue by Balddr** [WarEmu/WarBugs#16122]
Hello I did Gunbad left wing yesterday and we got to Glomp, we wiped and the instance reset, also locking us out from reentering the boss room,, just thought id let you know:)

Might have had to do with one of our players leaving and us inviting a new one, im not sure

**Comment by Kaelang** [comment]
Likely related to inviting a new player who had not completely the pre-requisites to enter the boss room. This essentially stops people from forming groups, clearing to the final boss and then 'selling' the lockout to other groups of people. 

If you head back into Gunbad Left - a good way to test this for confirmation is to form your 6 man, clear the content, kick one player and reinvite that player and see if the portal goes red then. If this happens, this is a bug, if this doesn't happen, it looks to be intended.

Thanks.

**Comment by Kaelang** [comment]
No further information - closed.
