### ISSUE TITLE
"Double XP/RR"

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#16132]
instead of 100% RR gain, yall set it to 10%, as shown in SS, I have +35, 25% of which is from my RR pots
![Dracula_040](https://user-images.githubusercontent.com/44329952/77833215-a4197e80-7109-11ea-9a69-e32ec3fcafb8.jpg)

**Comment by wargrimnir** [comment]
You're bolstered. Check your buffs.

X2 is a server code setting, not a client side buff.

**Comment by Xicoz** [comment]
but why is getstats showing +100 for xp, and only 10 for RR?

**Comment by wargrimnir** [comment]
:|

Check Your Buffs.
You have 25% renown from the potion
You have 10% renown and XP from zone control
You probably have 100% XP from bolster
