### ISSUE TITLE
DC to character select --> Relogged into this...

### ISSUE THREAD

**Issue by bschmucker225** [WarEmu/WarBugs#16130]
**Expected behavior and actual behavior:**

Regular Login to character.

**Steps to reproduce the problem:**

This one is not going to be easy to reproduce.  

Character name Runeloc:

1) logged in
2) got DC'd to character select
3) re logged into same character without starting client over
4) rapid flashing of overall lighting and below screenshots upon login.  All persisted until I forced a crash (logging out wasn't working). 
5) relogged and everything is normal.  

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/45979606/77828992-4cb0e980-70dc-11ea-9fbb-1241aa32f977.png)

![image](https://user-images.githubusercontent.com/45979606/77828994-520e3400-70dc-11ea-8387-2d308c7dbd5d.png)

![image](https://user-images.githubusercontent.com/45979606/77828998-58041500-70dc-11ea-98fc-25b65275513d.png)

**Comment by Garnerr** [comment]
This is being caused by the recent patch. I had the same issues, but it's seemed to have died down now.

**Comment by Kaelang** [comment]
Are you still experiencing this, or have recent patches solved this for you too?

**Comment by Garnerr** [comment]
Sorry for the late response, but yes this problem has been fixed since then. It was only happening an hour or so after the patch that day. You weren’t able to claim any of the items even though it was just a bunch of humble jumble written in the tool tip.
