### ISSUE TITLE
Armor talisman +164 and 100 gold missing

### ISSUE THREAD

**Issue by bloodmeat4370** [WarEmu/WarBugs#16131]
Hello. I have an issue with my armor talisman that i purchased from auction house,its missing after rollback. 
Basically i borrowed 100 gold to purchase 2 x +164(200 gold a piece) armor talismans from a friend and he sent me the gold over the mail.
I bought the talismans and after few minutes you guys rolledback the server(20 am CET+1) and now my 100 gold that i borrowed from a friend is missing,and it is not in my mail(but the email is in my mailbox,and its blank). I have received 100 gold from transaction back,but my friend say the rollback did not return his money. 
Also the second armor +164 talisman that i bought is missing from my backpack.
I wouldnt writte a bug report if i just had my armor talisman in backpack,but sadly i dont.Im a new player and I dont have alot of gold going around,so can you guys sort this out please.Thx

**Comment by Lheana** [comment]
Sadly this kind of things happen right before a restart. It's a known issue, that might be fixed one day. But there won't be any recovery.
