### ISSUE TITLE
Reikwald + Fell Landing Fortress Population Scaling broken as of 3/28 patch

### ISSUE THREAD

**Issue by Rubyeclipse-war** [WarEmu/WarBugs#16138]
**Expected behavior and actual behavior:**

**Expected Behavior:**
As players from both teams queue, fortress scaling should allow some players in on each side, as it has done in previous weeks.

**Actual Behavior:**
Beyond an initial batch of 40-50 players, no players from either realm are allowed in, even after the fortress begins following the 5-min prep period.

**Steps to reproduce the problem:**

1. Participate in open RvR prior to fortress
2. Queue for Fortress as it pops

**Testing Screenshots/Videos/Evidences (always needed):**

![fort scaling 2](https://user-images.githubusercontent.com/60584990/77839062-74c93880-712e-11ea-96e5-bc1cc0816b9b.png)
![scaling](https://user-images.githubusercontent.com/60584990/77839064-77c42900-712e-11ea-84c5-0f6b0fd63cbb.png)

----

Thanks for looking into this! 
- Ruby

**Comment by SilverWF** [comment]
And after several minutes it got lowered even less: to 44 vs 37

**Comment by Rubyeclipse-war** [comment]
Confirmed this is also happening in Fell Landing. (Updated title to reflect.) Looks like it may be present for multiple forts, if not all.
![fell scaling](https://user-images.githubusercontent.com/60584990/77843016-bb7a5b00-714d-11ea-8445-815b21fc3feb.png)

**Comment by Kaelang** [comment]
This looks to have been addressed as recent forts have not had this issue. I will keep this open temporarily, should this issue reoccur in the near future please report through this Issue and I'll tag/assign accordingly.

**Comment by Kaelang** [comment]
No further information - closed.
