### ISSUE TITLE
The Ebon Flame: T4 Dark Elf Epic Quest: Killed Riannmar Jadehart, clicked on Door, Quest did not update

### ISSUE THREAD

**Issue by kigutsu** [WarEmu/WarBugs#16134]
I was trying to finish the Ebon Flame T4 Dark Elf quest and after killing Riannmar Jadehart, I clicked on my orb, and then I clicked on the Doors of Flame and it ported me out facing the Keeper of the Way, but not within aggro range.  I did not receive credit, nor was I able to go to Lyrithea Marakar to finish the quest.

I killed Riannmar Jadehart more than 3 times afterwards (even though I do not have the orb anymore), tried to open the door without being in combat, and the same thing occurred.  I cannot receive credit for "Approach the Doors of Flame"

**Comment by kigutsu** [comment]
![EbonFlameBug](https://user-images.githubusercontent.com/62815709/77834799-bc939400-711d-11ea-8a6e-84a6d869b8b2.png)
Here is the place I am ported to every time after doing the quest

**Comment by Lheana** [comment]
Thank you for the report, it will be fixed with next patch.

**Comment by kigutsu** [comment]
Thank you so much!  I really appreciate how quick this was! <3 <3

**Comment by Lheana** [comment]
It should have been fixed with the patch of today.
