### ISSUE TITLE
Engineer - Bombardment Turret sound

### ISSUE THREAD

**Issue by empiresun14** [WarEmu/WarBugs#16139]
Hello, this morning I've noticed that bombardment turret auto-attack sound is the same as gun turret auto-attack, in fact it doesn't shoot grenades (beside its own ability which works fine) but bullets. 
Is this working as intended or did something happen overnight?

**Comment by Kaelang** [comment]
Are you able to record a video, with sound, for this report?

**Comment by Kaelang** [comment]
Closed - no further information provided.
