### ISSUE TITLE
Gunbad Left Wing

### ISSUE THREAD

**Issue by Bartig** [WarEmu/WarBugs#16145]
On the last Boss from the Left Wing, the ability with Acidic Muck´s Acidic Muck - there is a issue with it, i was there with my Runepriest and i can Stun the Pit with my "Rune of Binding" so it does no more Damage to us and that the whole time on every spawning Pit  :)

**Comment by Kaelang** [comment]
Please can you supply additional evidence to support this, such as combat log / video of the encounter etc.

**Comment by Bartig** [comment]
The Pit spawns and i can tab target it, there is a Buff for 60-70 second i dont know exactly but i can stun the Pit and the Buff is gone and after that we take no damage in the area if the pit.
I stay longer in the area of the Pit but i did not take any damage.

![Bartig_004](https://user-images.githubusercontent.com/62862059/80030922-3b93a680-84e9-11ea-9a20-62337215f919.jpg)
![Bartig_007](https://user-images.githubusercontent.com/62862059/80030924-3c2c3d00-84e9-11ea-86ad-25e0749abaea.jpg)
![Bartig_006](https://user-images.githubusercontent.com/62862059/80030925-3cc4d380-84e9-11ea-8fbd-6a216dea84ba.jpg)
![Bartig_005](https://user-images.githubusercontent.com/62862059/80030926-3cc4d380-84e9-11ea-82c9-bff80eaac0fa.jpg)

**Comment by Kaelang** [comment]
Thank you.

**Comment by grunbag** [comment]
fixed with next patch

**Comment by Kaelang** [comment]
Fixed as of 13/05/2020 patch. Please re-open if issue persists.
