### ISSUE TITLE
Squig Herder Tactic: "He's A Biggun" not functioning

### ISSUE THREAD

**Issue by Rildetarma** [WarEmu/WarBugs#16147]
Sir,

The Squig Herder tactic: "He's A Biggun" is not working.  It doesn't increase the squig's strength and toughness by 160.

**Comment by Kaelang** [comment]
Please could you provide a character screen screenshot before and after slotting the tactic?

**Comment by Rildetarma** [comment]
![Hes a Biggun added](https://user-images.githubusercontent.com/15988204/80317745-6d8f5c00-87ba-11ea-851d-7925f87dda88.jpg)
![No Hes a Biggun](https://user-images.githubusercontent.com/15988204/80317750-71bb7980-87ba-11ea-9c6b-0682bcd86061.jpg)
![Test two Hes a Biggun added](https://user-images.githubusercontent.com/15988204/80317753-75e79700-87ba-11ea-9f51-9828b4dd6132.jpg)
![Test Two No He's a Biggun](https://user-images.githubusercontent.com/15988204/80317755-78e28780-87ba-11ea-9c26-fe3770f6c693.jpg)



Sir,

Attached are four screen shots.  Two with He's a Biggun slotted, and two without.  There is no clear discernible difference between the examples.  The tactic He's a Biggun is not functioning.

**Comment by Rildetarma** [comment]
Please let me know if you need anything else for this to be corrected.

Thanks

**Comment by grunbag** [comment]
Pet stat only increase autoattack. Their abilites damage are calculated from your stats
