### ISSUE TITLE
[Ability] Engineer turret double damage

### ISSUE THREAD

**Issue by bezlikiy87** [WarEmu/WarBugs#16141]
The character under the nickname Gniffte, bugs the turret on a double damag per second
![Bezlikaya_0171](https://user-images.githubusercontent.com/60247043/77851182-4310aa00-71e0-11ea-8a1e-506fc1900ba8.jpg)

**Comment by Kabucoror** [comment]
You are referring to the ability Machine Gun which hits twice per second, so everything is working fine.
