### ISSUE TITLE
Running through water mounted will visibly dismount you, but you keep the speed / buff. 

### ISSUE THREAD

**Issue by Kaelang** [WarEmu/WarBugs#16146]
If running through water on a mount should dismount you, visibly, the buff should be removed - removing the speed increase. However currently, it stays on, making it look like people are speed hacking (due to moving on foot at +60%). 

**Steps to reproduce the problem:**

Run through water whilst mounted. 

![image](https://user-images.githubusercontent.com/60117106/77911735-38f6b600-7289-11ea-9431-155e67f261d9.png)

**Comment by Lheana** [comment]
Duplicate of #16037
