### ISSUE TITLE
Double C&T influence reward

### ISSUE THREAD

**Issue by ilferro** [WarEmu/WarBugs#16149]
I was able to get two items instead of one only from basic C&T reward npc. 
I attach photos.
![Faber_757](https://user-images.githubusercontent.com/16581052/77923580-eb874280-72a2-11ea-9548-9b9f8747ee87.jpg)

**Comment by Kaelang** [comment]
Did you receive both items from 1 Reward NPC?

**Comment by ilferro** [comment]
Exactly. Selected one, then changed my mind but received both.

Il gio 23 apr 2020, 02:58 Kaelang <notifications@github.com> ha scritto:

**Comment by Kaelang** [comment]
Hm, I've just tried to pick two items up from the NPC in IC and was only able to get 1. Which NPC did you go to?

**Comment by Kaelang** [comment]
Also - was this the first time you picked up the reward? I know you can take 1 reward from each NPC, so it could simply be giving you two rewards from one, and then none from the other. Can you test that for me?

**Comment by ilferro** [comment]
Those similar to a WH under the temple of sigmar.

Il gio 23 apr 2020, 19:14 Kaelang <notifications@github.com> ha scritto:

**Comment by ilferro** [comment]
I received them from the same npc, btw didn't know I could be able to get
more than one reward from different npc. I'll test it as soon as I can log
in. Thx

Il gio 23 apr 2020, 19:15 Kaelang <notifications@github.com> ha scritto:

**Comment by Kaelang** [comment]
Thanks let me know.

**Comment by Kaelang** [comment]
Closed - No further information.
