### ISSUE TITLE
Captured Keep winning loot not sent

### ISSUE THREAD

**Issue by Raikoed** [WarEmu/WarBugs#16144]
I won a purple bag from a rvr keep win and waited and kept playing in more keep wins today march 29. I also won a green bag and was able to get that bag pls help me retrieve my purple bag

**Comment by Raikoed** [comment]
This is on my white lion characters name is Raikoe

**Comment by Dreig666** [comment]
Yesterday Won a Gold Loot bag (Forget time/zone), and today a Purple Bag ( for AM Praag EST).  Neither showed up in my mail

**Comment by Kaelang** [comment]
Would need more information - that being said, you should receive delayed bag rewards after a server reset. Can you confirm if you received these following the recent server restarts?

**Comment by Kaelang** [comment]
No further information - closed.
