### ISSUE TITLE
Zealot Renown tactic manipulation not procing 

### ISSUE THREAD

**Issue by fakeplastictea** [WarEmu/WarBugs#16154]
I could not find one in a search.

**Expected behavior and actual behavior:**

25% of the time with direct healing damage offensive target for 25% of the value of the heal, not procing in combat.

**Steps to reproduce the problem:**

see video

**Testing Screenshots/Videos/Evidences (always needed):**

https://www.youtube.com/watch?v=ViQx0CmKrCQ&t=

**Comment by RoR-Zomega** [comment]
It's healing done, not overheal done. Each heal cast you healed 0 as you were at full life so no damage was done to the hostile target.

**Comment by grunbag** [comment]
Answered closing
