### ISSUE TITLE
Magus Officer's sets

### ISSUE THREAD

**Issue by AlmondTheCrazy** [WarEmu/WarBugs#16151]
Hello, I was checking all possible Magus sets today and I found one thing interesting, which curious me.
I don't know if that's true, but once, someone said, that Emblems set if you off spec and Medallions set in your main spec.
So, as I was checking all sets I went to Officer's sets and what took my attention
- Officer's Emblem set is main spec (Havoc)
https://i.postimg.cc/W3R1Syk5/merc.png
- Officer's Medallion set is off spec (Demonology)
https://i.postimg.cc/C5X8h5qN/ani.png

Exploring all other sets, it's like change only appear in one set, which is Officer.
I don't know if that's supposed to be like that, or that a mistake.

Thanks for your attention. 
Have a pleasant day :)

**Comment by Kaelang** [comment]
Scenarios and RvR provide gear for separate specs. 'Main Spec' often refers to the meta at the time, not necessarily game functionality. Some specs require SC's to gear optimally, some require RvR.
