### ISSUE TITLE
Nordenwatch Bug

### ISSUE THREAD

**Issue by lyonier** [WarEmu/WarBugs#16150]
Look this video... i dont know if is a bug.. but is so boring
https://youtu.be/-fKnoV-4PiY

**Comment by Vayra** [comment]
Did a destro player DC on the flag earlier? Had a similar bug on the Fortress flag a while back when a player DC'd on the flag and kept us from contesting it for the rest of the game.

**Comment by Lheana** [comment]
It should have been fixed with the patch of today.
