### ISSUE TITLE
Ironbreaker Oath Friend doesnt apply buff

### ISSUE THREAD

**Issue by marq888** [WarEmu/WarBugs#16157]
Hi,

There i got problem with oath friend buffs. In SC oathed friends don't got any buffs from me. They're in party, in range, they're oathed but still no buff on enemy hit.

Greetings

**Comment by Kaelang** [comment]
Need more information - you say they don't have any buffs, but they're oathed, but they don't get the buff? Slightly confused here.

**Comment by Kaelang** [comment]
Closed. No further information provided.
