### ISSUE TITLE
Auction house in reikwald bugged

### ISSUE THREAD

**Issue by bloodmeat4370** [WarEmu/WarBugs#16159]
My auction house in reikwald wont let me search for items. The search button appears ''grey'' and I cant press it,nor I can see my listed auctions.
Screenshost:
http://prntscr.com/rpvdla
http://prntscr.com/rpve5p

Any help on this issue is greatly appreciated.

**Comment by bloodmeat4370** [comment]
A new bug appeared related to my character. It seems when I list +20 talismans in auction house,they dont appear for sale.

**Comment by dalen** [comment]
You need to keep the auctioneer as friendly target. A fix for that is coming in next patch though.

**Comment by bloodmeat4370** [comment]
i have had auction house npc as a friendly target and i can open the auction house but i cannot search for items coz the '' search '' button appears grey.

**Comment by bloodmeat4370** [comment]
I have had auction house npc as a friendly target but i still cannot search for items coz the search button appears grey.

**Comment by MaxHayman** [comment]
If this is still happening after the latest patch please reopen.
