### ISSUE TITLE
Guild Vault New Tab Cost is Broke

### ISSUE THREAD

**Issue by Richardwarhawk** [WarEmu/WarBugs#16155]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by grayla** [comment]
We are a level 17 guild and we also have this problem.. 10 slots tab 1 and 10 slots tab 2 and the unlock button does not respond so we cannot add more... based on guild level I think we should have more slots available but we are new to game so this might be incorrect.  Art of Execution guild - GL  Mitsuru.   I am an officer in the guild.

**Comment by Rubyeclipse-war** [comment]
This issue has been opened already. Here's the link to the original report:

https://github.com/WarEmu/WarBugs/issues/15848
