### ISSUE TITLE
HE CH22 Tor Sethai - PQ mobs

### ISSUE THREAD

**Issue by HeiLei1994** [WarEmu/WarBugs#16152]
I am a bit confused on the strength of these mobs,

- Deathclaw Warrior - "Regular" mob but seems to me to have the strength of a champion level mob, in both health and damage.

- Deathclaw Bloodshot - "Regular" mob but seems to have champion level of health, but hits like a "wet noodle" = hits like a "regular" level mob.

- Deathclaw Frenzier - "Regular" mob with regular health, can hit hard perhaps champion level not sure on this one, so might be correct.

I am new to WAR, so I don't know/can't compare it to retail whether or not the last high elf chapter has stronger mobs or not.

**Comment by Vayra** [comment]
The ch22 Hard PQs in all pairings are buffed compared to live and require a warband to complete. In return they drop pieces from a higher level set called Onslaught.

**Comment by HeiLei1994** [comment]
Alright thanks!
