### ISSUE TITLE
resource drop in war camps

### ISSUE THREAD

**Issue by accNumber13** [WarEmu/WarBugs#16166]
UPD: Video proof
i opened the topic earlier and i got an answer: 

"Lheana commented 8 days ago
The wc resource drops are no longer used."

But i still can drop supplies at CW war camp.

**Testing Screenshots/Videos/Evidences (always needed):**

![2222222222222222222222222](https://user-images.githubusercontent.com/62439044/78077640-6179cf80-73b1-11ea-87f2-74df15d23f5b.png)
![1111111111111111111111111111111111111](https://user-images.githubusercontent.com/62439044/78077642-62126600-73b1-11ea-8b4b-b2c0519f3aaf.png)

[bandicam 2020-04-02 11-55-30-287.zip](https://github.com/WarEmu/WarBugs/files/4419948/bandicam.2020-04-02.11-55-30-287.zip)

**Comment by Lheana** [comment]
Did it drop the supply or clicking on the flag did nothing?

**Comment by accNumber13** [comment]
it drops supplies properly

**Comment by accNumber13** [comment]
I recorded video today, but i can't add it here

**Comment by accNumber13** [comment]
recorded and added a video (zip archive in attached files)
