### ISSUE TITLE
[WP] 7pc Main Sovereign: Acute Fury

### ISSUE THREAD

**Issue by theHalta** [WarEmu/WarBugs#16168]
**Expected behavior:**
- Regenerate RF over 3s.
- It should proc off of HoT ticks.

**Actual behavior:**
- It gives 45 RF all at once at the end of the buff's duration.
- It only procs off of direct heal casts. (Touch of the Divine gives it 6 chances per cast in a full group).

**Testing Screenshots/Videos/Evidences (always needed):**

https://youtu.be/KTP2hPUjoes?t=31
0:31-0:41
You can see how he doesn't get any cast off, but the proc goes off **twice** from HoT ticks.
![Image](https://i.imgur.com/EXrIb0C.png)

https://youtu.be/KTP2hPUjoes?t=108
1:48-1:55
He only casts HoT spells while running, and it procs multiple times.

**Notes:**
The same should apply for the Onslaught proc since I think it's the same ability.
The same should apply for the DoK version, I don't have one currently to test.

**Comment by Tesq** [comment]
it never proced on live on hot, only wapforged crit stuff procced on hot and was bug

**Comment by grunbag** [comment]
Fixed the overtime regen . And yes it proc only on directheals
