### ISSUE TITLE
Bag not arriving in mailbox even after waiting 24 hours

### ISSUE THREAD

**Issue by aendam** [WarEmu/WarBugs#16163]
Won a bag at a keep but could not get back to the keep in time and it has never arrived in the mail.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by SilverWF** [comment]
Happens.
You should wait for server restart to gt it.

**Comment by Lheana** [comment]
Exactly, wait for a server restart.
