### ISSUE TITLE
Warlord Greatcloak Cannot Be Dyed

### ISSUE THREAD

**Issue by Xalak** [WarEmu/WarBugs#16167]
![Cannot_Be_Dyed](https://user-images.githubusercontent.com/16090807/78083986-e510cd80-736b-11ea-9d5d-87ac7c60d83f.jpg)

**Comment by grunbag** [comment]
Most sovereign and warlord cloak cannot be died

**Comment by Xalak** [comment]
The Sovereign BG cloak is able to be dyed, as should the Warlord cloak.
