### ISSUE TITLE
Sentinel weapon proc

### ISSUE THREAD

**Issue by Syzlakee** [WarEmu/WarBugs#16177]
First off all id like to apologize for my english and i hope it is understandble.

Hello i'd like to report something thats very odd and is kinda unfavourble for the swordmasters comparing to all other tanks that have the same weapon however there weapon have a a slower auto attack speed (and that auto attack speed is crucial for someone who wants to go dps spec )  the slower the higher hits with auto attacks )  

**Expected behavior and actual behavior:**
Remake the Crimsonwind so it have the same attack speed 3.6 and stats (equal) like all the 5 other tanks **possible change of stats** to match the other weapons out there but thats another topic 

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**
[img]https://i.imgur.com/RA7B8Hm.png[/img]
<!--

**Comment by Kaelang** [comment]
Fine line between this being a bug, or a suggestion. I'll keep this tagged as an issue for now until one of the devs can address.

**Comment by Syzlakee** [comment]
Clearly a bug considering that all other tanks have 3.6 while sms 2.7?

**Comment by Kaelang** [comment]
Left it tagged and open for the confirmation. :)

**Comment by wargrimnir** [comment]
Here's the list of two handers that are not 3.6s


Aster
Fate of Lileath
Favor of Lileath
Rod of the Silver
Solarbeam
The Anvil
The Black Death
Ovast
Bloodspray
Disdain
Harrower
Uncanny Cane
Liverlopper
Corrupted
Abhorrence
Maelstrom
Maltreatment
Premeditated
Massive Hemorrhage
Bloodlust
Doomfire
Afterlife
Decadence
Firebug
Emberdrake
Willpower
The Sight
Pride
Heresy
Spirit of the Djinn
Sinistar
Gork's Blasta
Docta Whomstick
Phantasm
Da Big Big Chop Chop
Despair

I changed it anyway along with the KotBS 2h sword as those were the only greatswords that were 2.7s

Was it intended to be that way? Perhaps. Speed rating doesn't matter for overall damage, only DPS does.

**Comment by Syzlakee** [comment]
mhm i appriciate the help but i remember from live it was 3.6 but of course it matters for white hits and if ur using a timer addon for swing timers it helps alot im loseing like 400 dmg per swing compare to the 2.7 but i do appriciatre the help sir Thanks

**Comment by Kaelang** [comment]
As of 22/04/2020 this should now be fixed.

Please re-open this issue if you are still experiencing issues.
