### ISSUE TITLE
blast, headshot!

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#16175]
Chosens blast wave skill is producing an instant kill effect on all the skaven mobs in the new scenario (Im guessing its the wounds debuff component which causes this, but I havent tested)

Also the WL's pull and pounce skills can cause players to pass through the halfway barrier, I assume this also applys to counterpart skills on destruction characters

**Comment by Kaelang** [comment]
As the scaven event / Ratnarok SC has now concluded, I'm going to go ahead and close this report. If the scenario / event makes a return and you find a similar issue, feel free to re-open the report.

Thanks.
