### ISSUE TITLE
Nordenwatch wrong guard allocation

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#1617]
![tesq_228](https://cloud.githubusercontent.com/assets/7527415/10403025/c0690a80-6e7d-11e5-8c9a-f92119faa372.jpg)
![tesq_229](https://cloud.githubusercontent.com/assets/7527415/10403029/c8f0b748-6e7d-11e5-913e-c90146443ab8.jpg)

**Comment by Torquemadra** [comment]
fixed
