### ISSUE TITLE
Witch Hunter - Vanquisher Shoulders

### ISSUE THREAD

**Issue by Kymix21** [WarEmu/WarBugs#16188]
Witch Hunter Vanquisher Shoulders are showing no appearance at all, as if I wasn't wearing shoulders.

**Comment by Choxofchix** [comment]
![image](https://user-images.githubusercontent.com/63601194/79158993-e03b2780-7e09-11ea-9683-faa20c3a0599.png)

**Comment by Kaelang** [comment]
![image](https://user-images.githubusercontent.com/60117106/82053488-58b93080-96b5-11ea-8f06-6c324b3f6d84.png)
![image](https://user-images.githubusercontent.com/60117106/82053507-61aa0200-96b5-11ea-9640-2d3973bbb3f2.png)

Closing for now - if issue persists, please re-open.
