### ISSUE TITLE
Quest Nordland The Doctor's Orders: rewards bugged for Warpriest

### ISSUE THREAD

**Issue by kigutsu** [WarEmu/WarBugs#16189]
The quest The Doctor's Orders in Nordland will not let you turn the quest in unless you have accepted the "Doctor's Potion of Willpower" as your pick as a Warpriest.  Level 9 warpriest tried to turn in and get the armor potion, then strength potion, and then Willpower one worked.  When I opened my inventory I had gotten both the Doctor's Potion of Willpower and Doctor's Potion of Strength as rewards.
![Doctor's potion of strength](https://user-images.githubusercontent.com/62815709/78181746-dccf9580-7432-11ea-8051-b221576fa394.png)
![Doctor's potion of willpower](https://user-images.githubusercontent.com/62815709/78181754-df31ef80-7432-11ea-9ae1-3342badd409f.png)

**Comment by Lheana** [comment]
It's not a bug, you can choose 2 rewards.
