### ISSUE TITLE
Swordmaster "perfect defenses" tactic

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#1618]
It dosen't show the blocK/parry value in character menu, so i dont know if it a visual bug or it don't work, but after test it in combat it dosent seems to modify my block/parry chance at all.

**Comment by ozarmidrashim** [comment]
Use .getstats instead of the char menu for this.

**Comment by Evildoor** [comment]
@ozarmidrashim , may i ask stupid question? How exactly and in which chat should ".getstats" be used? Is it restricted to dev server?

**Comment by Tesq** [comment]
if i have that add on i will try it tomorrow.

**Comment by ozarmidrashim** [comment]
It's not an addon - it's a command :P

**Comment by Tesq** [comment]
mm on which chat i suppose to use that command

.getstats

don't work in my chats

**Comment by Evildoor** [comment]
You should target yourself while typing in "say".

**Comment by Tesq** [comment]
it work i close this

**Comment by Evildoor** [comment]
Fixed, closing.
