### ISSUE TITLE
Chaos Chapter 10 PQ World Object Spammable

### ISSUE THREAD

**Issue by Alcsouls** [WarEmu/WarBugs#16199]
in the easy PQ stage 2 you can finish it in like a min if you do not engage but have the knight tagetet just click the firer and repeat at house!
![Alcsouls_001](https://user-images.githubusercontent.com/63056448/78256644-1bc81e80-74f9-11ea-9ef8-b59b79ec63b5.jpg)
![Alcsouls_002](https://user-images.githubusercontent.com/63056448/78256651-1e2a7880-74f9-11ea-876a-d9292d2de536.jpg)
![Alcsouls_003](https://user-images.githubusercontent.com/63056448/78256656-1f5ba580-74f9-11ea-9b3d-d6a1e2532dbd.jpg)
![Alcsouls_004](https://user-images.githubusercontent.com/63056448/78256664-21bdff80-74f9-11ea-913e-29b73f2b809f.jpg)

**Comment by Alcsouls** [comment]
![Alcsouls_001](https://user-images.githubusercontent.com/63056448/78256788-4b772680-74f9-11ea-8eff-9b64c4e7c894.jpg)
![Alcsouls_002](https://user-images.githubusercontent.com/63056448/78256791-4dd98080-74f9-11ea-8755-c0ced29f2527.jpg)
![Alcsouls_003](https://user-images.githubusercontent.com/63056448/78256800-4fa34400-74f9-11ea-961e-a582b86f208b.jpg)
![Alcsouls_004](https://user-images.githubusercontent.com/63056448/78256808-52059e00-74f9-11ea-9ac2-41e3a377be92.jpg)

**Comment by Kaelang** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/14893 as reports are related to spammable objects.
