### ISSUE TITLE
BO Bloodlord helm equippable without greater ward

### ISSUE THREAD

**Issue by stmarrow** [WarEmu/WarBugs#16195]
**Expected behavior and actual behavior:**

My BO can equip BL helm despite not having any ward. Does not work with hands. Don't have any other pieces to test with. Similar to #14432

**Testing Screenshots/Videos/Evidences (always needed):**

![Orgruz_016](https://user-images.githubusercontent.com/51999525/78226519-1bfdf500-74cc-11ea-8b1b-71bf8417c7ed.jpg)

**Comment by Lheana** [comment]
You haven't equipped the sentinel set?

**Comment by stmarrow** [comment]
No. Nor Redeye. The SS is supposed to show that I don't have greater ward unlocked.

**Comment by Kaelang** [comment]
As of 22/04/2020 this should now be fixed.

Please re-open this issue if you are still experiencing issues.
