### ISSUE TITLE
quest.

### ISSUE THREAD

**Issue by Japzor** [WarEmu/WarBugs#16192]
Greeting.

Iam new here but really like the game :) But i having som troble with some quest.
Cleansing an Empire in Talabecland - The 3 things u need to find are a pain in the a.. dont think it is bug. but haven't found them jet :/
Special Delivery in Talabecland - The Smith dont drop the iron box, think it is bug.
A prod in the Right Direction in Death Peak  - There are no troll there, think it is bug.
Btw keep up the good work.
regards
Japzor

**Comment by Lheana** [comment]
Please read the text when you create a ticket.
"Issues should be unique. Check if someone else reported the issue first, and please don't report duplicates.
Only ONE issue in a report."
You reported 3 issues in 1 report, and each issue you reported are already reported.
