### ISSUE TITLE
Casting abilities rendered instant cast through modifiers cannot be casted while moving

### ISSUE THREAD

**Issue by sullemunk** [WarEmu/WarBugs#1619]
Zealots Scourged ability does not let you cast it while moving when the tactic "scourged warping" procs (the animation plays but the spell won't fire off)

Player need to stand still in order to make it do damage.
iirc it was possible to cast while moving on live servers when the tactic procced

**Comment by Evildoor** [comment]
Part of the general problem with implementing similar things which make something instacast. At least in this case you only have to stand still for a split second, and don't get annoying client-sided cast bar, like with AM/Shaman mechanic...

**Comment by Evildoor** [comment]
This problem is better than before, but still not fixed completely. You have to stop for a split second to use the instacast ability.

**Comment by Evildoor** [comment]
Works properly on live server, but not on dev server (at least AM mechanic).
