### ISSUE TITLE
bug dye vanquisher shoulders of choppa

### ISSUE THREAD

**Issue by grimstuck** [WarEmu/WarBugs#16193]
hello before the patch of today i can choose the dye of my vanquisher shoulders on my choppa 

but now i cant and i have this message : 
![ccc](https://user-images.githubusercontent.com/63030421/78205211-da555600-749b-11ea-95d1-814e6f1761a2.PNG)

my shoulder already have my last dye what i have appliqued 
![sdsd](https://user-images.githubusercontent.com/63030421/78205256-fa851500-749b-11ea-82ac-c75a602d3e56.PNG)

when i change the appearance of my shoulder , the new shoulder cannot be dye and she stuck with the dye already applied on it 

![cxccxc](https://user-images.githubusercontent.com/63030421/78205371-3f10b080-749c-11ea-8678-e61cdaf9e062.PNG)

![dsdsdqs](https://user-images.githubusercontent.com/63030421/78205333-2accb380-749c-11ea-9c45-21dd33696df3.PNG)

when i use scouring argent for delete dye i got again this message : 
![ccc](https://user-images.githubusercontent.com/63030421/78205409-551e7100-749c-11ea-8bbf-4ae0095a499d.PNG)

thx have a good day :) 

ps : sorry for my bad english i'm french . 

Azgedo

**Comment by LestiArdisson** [comment]
Not a sollution to the bug, but there is a workaround.

Remove all items on your char.
Only wear the shoulders.
Then go to the vendor to dye item and select: "Dye all items."
This will change the dye on your shoulders.

**Comment by grimstuck** [comment]
Hello i already do this , vanquisher shoulder can no longer be dye since the last patch

**Comment by grimstuck** [comment]
https://www.youtube.com/watch?v=g__lxxSYl_s&feature=youtu.be

**Comment by Kaelang** [comment]
You can still dye the shoulders - just not using a Primary dye

Closed.
