### ISSUE TITLE
Bastion Stairs lockout

### ISSUE THREAD

**Issue by Menany** [WarEmu/WarBugs#16197]
So yesterday I cleared Bastion Stairs right wing and today im trying to clear mid wing, but it its locked out for me even tho i`ve never been there before.

![Bastion Stairs](https://user-images.githubusercontent.com/63044819/78233345-dc3c0b00-74d5-11ea-823f-d98524c79f12.png)

**Comment by Kaelang** [comment]
Was your party leader locked out?

**Comment by Kaelang** [comment]
Closed - no further information provided.
