### ISSUE TITLE
White Lion's lion dissapears

### ISSUE THREAD

**Issue by Enkeimaru** [WarEmu/WarBugs#16190]
Since the new patch, the lion dissapears randomly.

it dissapears when random when i stand still, afk, mount, dismount, fight.

my class and build is unplayable now, i lose too much dmg playing like this.

**Comment by CrimsonFenris** [comment]
Noticed that too. 
Usually the pet vanish after going out or visual draw range, but more than often, it also appears after being told to stop the attack and return before too far away.
Sometimes it vanishes when inside a structure (like we are standing on top of a wall, the pet staying in the room/wall underneath, and vanish randomy.

Using both loyalpet and petassist, and speed training assist (to ensure faster return), but still pet is unreliable....

**Comment by Kaelang** [comment]
If this was happening as you're describing, this would be a much louder issue.

Please can you confirm if this is still happening, and if so please could you provide some video evidence of this happening if possible?

Thanks.

**Comment by Kaelang** [comment]
No further information provided - closed.
