### ISSUE TITLE
Tzeentch's Firestorm

### ISSUE THREAD

**Issue by Dizzltron00** [WarEmu/WarBugs#16194]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Dizzltron00** [comment]
at lvl 26 - 33 renown.. casting the "Tzeentch's Firestorm" from the mastery tree as a magus is bugged.
in Rvr it just wont go off.. but in pve where im not bolstered it works just fine.
Character name is Dizzlgus

**Comment by Vdovics** [comment]
Same issue. It was already reported 10 March.

Evidence: https://imgur.com/a/jYlZZjx

**Comment by Kaelang** [comment]
Looks like a bolster issue. Duplicate of https://github.com/WarEmu/WarBugs/issues/15941.
