### ISSUE TITLE
Item purchased when told not to.

### ISSUE THREAD

**Issue by epruitt1** [WarEmu/WarBugs#16196]
I was looking at the Main Sov set on the Sovereign Quartermaster when I accidently clicked on the Sovereign Back Piece, which I already had, and was prompted with a box asking if I was sure I wished to purchase it. I said NO I did not want to purchase the item. After closing the vendor window I found that I had the additional Sovereign Back Piece and the royal crests used regardless.

**Comment by Kaelang** [comment]
I'll leave this open for validation on test but I'm curious to see results as the feature, from my knowledge, doesn't function on an item-by-item basis.

**Comment by Kaelang** [comment]
Tested on both main sov and off-sov. Pressing No does not purchase the item.

Closed.
