### ISSUE TITLE
[ToK] "Finished 10 PQs ranked #1" unlocks wrong reward

### ISSUE THREAD

**Issue by Grock-r** [WarEmu/WarBugs#16191]
Should unlock "The Tan Pouch" with gold bag icon
But instead, lets you to pick "The Green Pouch" with white bag icon at the vendor, and not any other

Unlock page:
![WAR-64 2020-04-01 23-55-39](https://user-images.githubusercontent.com/24813035/78185897-79feee00-7474-11ea-8709-2c5ae956f19d.png)

Rewards page:
![WAR-64 2020-04-01 23-55-47](https://user-images.githubusercontent.com/24813035/78185941-8a16cd80-7474-11ea-8b99-7a5f83e979f5.png)

Bought item:
![WAR-64 2020-04-01 23-56-02](https://user-images.githubusercontent.com/24813035/78185952-8f741800-7474-11ea-98f8-667ae1f882ce.png)

**Comment by Kaelang** [comment]
Fixed as of 13/05/2020 patch. Please re-open if issue persists.
