### ISSUE TITLE
Tilean Stupor debuff effect does not match tooltip

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#16201]
**Expected behavior and actual behavior:**
The Tilean Stupor debuff for the Korthuk the Raging fight in Bloodwrought Enclave does not match the tooltip. The actual in-game debuff is +5s cooldown, while the tooltip says +2. I'm not sure which is supposed to be the correct one, but one of them is wrong. 

**Steps to reproduce the problem:**
Fight Korthuk the Raging and look at the tooltip when you get debuffed by Tilean Ale. 

**Testing Screenshots/Videos/Evidences (always needed):**

![Forkrul_024](https://user-images.githubusercontent.com/1183293/78272835-4f617380-750e-11ea-8967-6b8f6bfe59fb.jpg)

See tooltip text vs cooldown on Khaine's Embrace.

**Comment by grunbag** [comment]
2 seconds is correct one .
