### ISSUE TITLE
morale damage

### ISSUE THREAD

**Issue by rycko2b** [WarEmu/WarBugs#16200]
Hi, just to put there that the morale 4 from Squig Herder is not doing the damage intended (even if it's already a stupid m4...). Morale damage are fixed damage, not random, or not more,; not less. 
![Leonasse_010](https://user-images.githubusercontent.com/26632001/78270419-17a4fc80-750b-11ea-8ea4-b118fce3b261.jpg)

**Comment by Vayra** [comment]
They're fixed per level. If it's an M4 it should be tied to the specific tree, so if they have a set with +levels in that tree it could increase damage above the normal lvl 40 damage.
This looks like 2 squig herders with +1 and +2 levels to the tree.

**Comment by Kabucoror** [comment]
Morale damage scales with level and with a character rank below 40 you will get bolstered to a higher level. Thus this is normal.
