### ISSUE TITLE
Altdorf Sewers. Master Moulder Vitchek

### ISSUE THREAD

**Issue by ThePhantom593** [WarEmu/WarBugs#16204]
After a wipe the Mysterious Halfling quest giver killed the boss and we didn't even get credit for the quest.

![Dwallar_003](https://user-images.githubusercontent.com/63072117/78293496-ec310a80-7528-11ea-8484-36788538c3e2.jpg)

**Comment by Lheana** [comment]
The best thing that can be done is to prevent this NPC from attacking and being affected by attacks.
