### ISSUE TITLE
PQ - Destro - Ironclaw Camp - Invisible Stages

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#16207]
![Ironclaw PQ Bug 3](https://user-images.githubusercontent.com/18690551/78304267-54252800-750c-11ea-96f1-b47539b39edb.png)
![Ironclaw PQ Bug](https://user-images.githubusercontent.com/18690551/78304268-54bdbe80-750c-11ea-9909-38508a0ac311.png)
![Ironcal PQ Bug 2](https://user-images.githubusercontent.com/18690551/78304270-54bdbe80-750c-11ea-808b-a7cdb471d41f.png)

**Expected behavior and actual behavior:**

Can't see stages. Tested other PQs and seemed limited to only Ironclaw Camp. Relogged. No change.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
It works fine for me.
