### ISSUE TITLE
lost all items

### ISSUE THREAD

**Issue by indilzar** [WarEmu/WarBugs#16219]
after crach city lost all items from bag
![Indilzar_001](https://user-images.githubusercontent.com/63124466/78399479-a003ca00-75fd-11ea-816a-e997da0fc022.jpg)

**Comment by Kaelang** [comment]
Does /reload work? It seems to work for a number of people who have spoke about this in advice etc.

**Comment by Kaelang** [comment]
Closed due to no further information.
