### ISSUE TITLE
Half-Eaten Mushroom

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#1621]
This trash item has no price and cannot be sold to vendor.

**Comment by Reggaewaldo** [comment]
Where does it drop ? What level on the mobs ?

**Comment by Evildoor** [comment]
Dwarf chapters 1-2. Goblins and/or snotlings, IIRC.

**Comment by Meralors** [comment]
Set sell price of Half-eaten Mushroom to 40 copper to match other items of same level range.
Can close issue ;)
