### ISSUE TITLE
[Gunbad] Can't get influence items

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#16217]
I've completed Gunbad influence on my WL, but rally master still don't allows me to pick any of reward
Not sure about other classes

**Expected behavior and actual behavior:**
Exp: being able to chose reward
Act: it's not available

**Steps to reproduce the problem:**
Go to Gunbad, do PQs to gain influence, check Rally master

**Testing Screenshots/Videos/Evidences (always needed):**
![2020 04 03-18 24](https://user-images.githubusercontent.com/16439840/78377901-e85cc100-75d8-11ea-844b-000d9fca570e.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch
