### ISSUE TITLE
8/8 Witch Hunter Sovereign ability "Enough!"

### ISSUE THREAD

**Issue by dadkkak** [WarEmu/WarBugs#16212]
I tested the WH 8/8 Sovereign skill and I'd like to know if the range of the megapunt is a bug or intended. 
In short: Enough! is way stronger than the BG superpunt: i did a lot of tests and the ability sends people literally on the moon, with a 5-6 seconds flight (about half of nordenwatch map). 
Is this correct?

**Comment by grunbag** [comment]
Fiwed with next patch
