### ISSUE TITLE
box of conquerors medallions

### ISSUE THREAD

**Issue by necropanda777** [WarEmu/WarBugs#16211]
CDC in game nickname.
i just opened 1 box of conqueror's emblems and instead of 25 it gave me only 1 med.
satchel worked, it gave me 5 medallions
p.s. just opened a new issue cause the older one i found was closed

**Comment by wargrimnir** [comment]
Values for these are assigned in sourcecode, not DB

**Comment by Kaelang** [comment]
Tested both of these (medallions and emblems) and both gave 25.

Please re-open if issue persists.
