### ISSUE TITLE
Flag bug

### ISSUE THREAD

**Issue by Signvard** [WarEmu/WarBugs#16215]
Hello
I am writing this message to you simply to report a visual bug on the flags of the scenario which remains blue when we take them and they pass in neutral. I suspect that it is not annoying in terms of gameplay but I recognize that it can be disturbing when you are inside.
Sorry for my very bad English
Cordially.

**Comment by Lheana** [comment]
Please provide screenshots or video, and give more details like in what sc, what flag.

**Comment by Signvard** [comment]
I saw this on Norden Watch and Thunder Valley mainly. I try to make sure to film it and I come back to you.
________________________________
De : Lheana <notifications@github.com>
Envoyé : vendredi 3 avril 2020 16:06
À : WarEmu/WarBugs <WarBugs@noreply.github.com>
Cc : Signvard <parflodu60@hotmail.fr>; Author <author@noreply.github.com>
Objet : Re: [WarEmu/WarBugs] Flag bug (#16215)


Please provide screenshots or video, and give more details like in what sc, what flag.

**Comment by Signvard** [comment]
It is therefore necessary to look at the level of the tag which remains blue while the red gauge evolves. I show it with the mouse.
https://imgur.com/a/2ziuxHY

**Comment by Signvard** [comment]
If necessary I can do the same on the Order side, I noticed the same problem there but suddenly reversed.
