### ISSUE TITLE
KotBS Auras

### ISSUE THREAD

**Issue by j3crow** [WarEmu/WarBugs#16210]
My KotBS auras have been acting weird. The visual effect has been acting sporadic, sometimes on, sometimes not; even when the buff icons indicate they are on.

Also, it looks like I can have 4 auras on simultaneously. I will try and capture a screenshot.

My account is j3crow

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by j3crow** [comment]
It looks like its not repeatable. It appears it was a one-time thing. It occurred right as I leveled, and received the next aura skill. However, as soon as I stopped all auras, and re-started them, I could only do three at a time.

The aura visual effect is still acting funny. But I think its just cosmetic. Certainly not a priority, but I like the effect of them  :-)

**Comment by Kaelang** [comment]
You've stated that you can no longer replicate this issue. That being said please can you provide more information as to what level you was, what aura you had learned and which ones you had stacked during the time you ran 4 simultaneously?

**Comment by Kaelang** [comment]
Closed. No further information provided.
