### ISSUE TITLE
Invader medallions are missing

### ISSUE THREAD

**Issue by Deyotar** [WarEmu/WarBugs#16227]
Hello. Yesterday during the siege Inevitable City i had 24 invader medallions.
After restarting the server i have 10 invader melallions.
Lost all medalions that i have made in the course of the day.
Can something be done about it?

**Comment by Kabucoror** [comment]
No, sorry. Yesterday at city siege was a bug which repeatatly granted royal/invader crests.
"Invader and Royal currency has been reset to the prior backup, approximately 12 hours ago. That's the best we can really do!" explanation from Wargrimnir yesterday.

**Comment by Deyotar** [comment]
Too bad. Thanks
