### ISSUE TITLE
[Chosen] 13 pt ability Oppression not gaining stat contribution

### ISSUE THREAD

**Issue by Killamanjaro** [WarEmu/WarBugs#16223]
The Chosen 13 point ability 'Oppression is not gaining stat contribution.

**Expected behavior and actual behavior:**
The ability should be hitting for ~580 (pre mitigation) at max Str (1050)

**Steps to reproduce the problem:**
Hit anything / anyone with Oppression. The damage is very low (not under the effect of challenge, etc.).

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/61355379/78411642-f1985e80-75d5-11ea-879d-48cafe7e2394.png)

![image](https://user-images.githubusercontent.com/61355379/78411676-1391e100-75d6-11ea-9af8-a9ce4104a8a0.png)

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by Killamanjaro** [comment]
Thank you Grunbag!
