### ISSUE TITLE
Problem with Standard Bearing

### ISSUE THREAD

**Issue by Kilrathi01** [WarEmu/WarBugs#16225]
So my guild is level 5 and we unlocked our first banner. I purchased one, assigned its slot. Made two players standard bearers. Gave them warped banners. But when they tried to use it, the game tells them that the guild has not unlocked this requirement? I don't understand why it telling us that if we already hit lvl 5 as a guild.

**Expected behavior and actual behavior:**
Given the following message: **_"Your guild hasn't advanced enough to access that standard, standard tactic slot, or standard post yet."_**

**Steps to reproduce the problem:**
I tried it on my own character and received the same message.

![Kilchoppa_000](https://user-images.githubusercontent.com/62448354/78417230-1dc7d580-75fe-11ea-97ee-c0cc5114a5ad.jpg)

**Comment by Kaelang** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/16032.
