### ISSUE TITLE
cultivating  level 25 seeds

### ISSUE THREAD

**Issue by heavensfury** [WarEmu/WarBugs#16228]
when cultivating level 25 seeds{any level 25} all i am getting back is either critical failure to be expected! some times but more to the point i am always getting level 1 in this case i am getting level 1 swaying dandedragon .so in short anything  i am cultivating at my level  i am receiving  level 
![Chopchopfury_000](https://user-images.githubusercontent.com/62149671/78422329-69a66900-7656-11ea-86e2-7fd13b0749e1.jpg)
![Chopchopfury_001](https://user-images.githubusercontent.com/62149671/78422332-6dd28680-7656-11ea-811e-d89f092c0544.jpg)

1 from harvesting !!!!

**Comment by Kabucoror** [comment]
provied informations please, otherwise I close this

**Comment by Kaelang** [comment]
What seed do you get from breaking down the Swaying Dandedragon?

**Comment by Kaelang** [comment]
Closed - no further information provided.
