### ISSUE TITLE
[Choppa] Offensive Sov missing stat

### ISSUE THREAD

**Issue by Killamanjaro** [WarEmu/WarBugs#16222]
The Sov Chest of the Berserker is missing -3 AP/S. The equivalent Chest 'of the Flurry' has the full +4 AP/S. 

**Expected behavior and actual behavior:**
The Sov Chest of the Berserker should have +4 AP/S. It has +1 AP/S.

**Steps to reproduce the problem:**
Look at item and using Pure, see the AP regen is -3 compared to the Flurry.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/61355379/78411494-76cf4380-75d5-11ea-815d-57d0900b326f.png)

**Comment by Killamanjaro** [comment]
The Berserker chest has +8 Str and +7 Wep Skill. Not sure if +15 stat = +3 AP/s

Thank you

**Comment by wargrimnir** [comment]
Different items have different stats. These stats are correct for each piece.
