### ISSUE TITLE
Particular character multiple crashes

### ISSUE THREAD

**Issue by Horusaximand** [WarEmu/WarBugs#16237]
Hello.
My character - Horusaximand (81rr chosen) has problem with crashes. After I join a big group he often crash. And after I log on, he continue to crash for about 10 times in a row untill it calm down. I think it might be the issue with particular character or because he has huge amount of items in the bank - I have no idea. Switch to other characters does not help at all.
Other characters dont have this problem. I tried to download another game files - same problem.
Can you check him please - it might be an issue on server.
Best wishes.

**Comment by Kaelang** [comment]
Are you running your client on 64 bit mode? Open your launcher, settings in the top right, click '64 bit'. Tends to fix most crashes. Alternatively, you can look through some of threads here to see if there's any support available on the Technical Support subsection of the forum? https://www.returnofreckoning.com/forum/viewforum.php?f=4

**Comment by Horusaximand** [comment]
Hello. 
Seems like it works HOWEVER another issue arrised - with 64 bit launcher graphics lowered, I can not change textures paramete, and if I put maximum - there some visual problems.
