### ISSUE TITLE
Fortress tokens

### ISSUE THREAD

**Issue by Aindolur** [WarEmu/WarBugs#16235]
**Expected behavior and actual behavior:**
Winning and losing a fort I was under the impression that you would get 6 invader tokens for the win and 4 tokens for the loss.
I did enough to get a roll on the fortress and I did not receive any tokens after the fortress was completed. 
Why is this not producing tokens? I ran one two nights ago but the server was rolled back and i understand not having them now. However  i ran one last night and still no tokens were generated...
![Aindolur_002](https://user-images.githubusercontent.com/63126956/78454692-dd487600-7656-11ea-932a-d8ad3adf46ad.jpg)

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Did you get a reservation? Sometimes you can bug yourself into the fort by running through, without getting the popup. In this instance, you won't receive any tokens.

**Comment by Aindolur** [comment]
I think I did get a reservation but maybe not. I was told that you guys don’t replace lost items anymore.
How do we prevent this from happening again seeing as this is end game gear essentially and I would be wasting my time in the
Fortress.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Kaelang** [comment]
The safest way to participate into forts is to wait for the reservation popup on your screen. Attempting to glitch your way through the zone line replicates issues like this. You highlighted that you might not have received a reservation - in this case - this is why you didn't receive any rewards.

And correct, the team don't replace lost items. 

Closed for now.
