### ISSUE TITLE
'Flames of fate' morale (900 dmg) dealt 1541 dmg

### ISSUE THREAD

**Issue by DmitriyMaksimovich** [WarEmu/WarBugs#16236]
![Dimakss_048](https://user-images.githubusercontent.com/46728779/78456069-59b87480-76aa-11ea-98f7-7ba0cf6063da.jpg)

**Comment by kalmatar** [comment]
being near own warcamp will buff all outgoing dmg, including morales. its to prevent enemy camping defenders warcamp, and receiving shitton of more dmg from people fighting around their own warcamp area
