### ISSUE TITLE
Uncultured Swine mount summonable while carrying flag in Phoenix Gate

### ISSUE THREAD

**Issue by Thienri** [WarEmu/WarBugs#16232]
It doesn't give you the animation, but it does give you the +60% movement buff. It does appear you can be 'dismounted' if hit with it though. Tried two different instances and it worked both times.

![Gotzak_003](https://user-images.githubusercontent.com/62931030/78445601-f0247000-7681-11ea-96c1-8c9c09375ec9.jpg)

**Comment by Thienri** [comment]
PS: Wyvern acts the same, but without the icon under the HP bar.

**Comment by Kaelang** [comment]
Sounds like event mounts aren't being classified as mounts for the purpose of running SC objectives. Will tag this up.

**Comment by Kaelang** [comment]
This should be fixed now.
