### ISSUE TITLE
Gunbad jewlery from mini bosses

### ISSUE THREAD

**Issue by barfyman92** [WarEmu/WarBugs#16233]
Rare and epic jewlery quipment from mini bosses lack class restrictions so anyone can need roll on any loot regardless if the stats are useful for them. 

I asked in discord and got this confirmed as a bug by wargrimnir.

**Comment by wargrimnir** [comment]
The gemstones (ruby, amber, diamond, etc) are intended to have no class requirement. I thought you were talking about something else.
