### ISSUE TITLE
Quest - Dangerous Delicacies - Raven Pie can't be interacted with

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#16239]
**Expected behavior and actual behavior:**

Three dishes spawn, first two can be interacted with fine, but Raven Pie can't be right-clicked on to give credit.

**Steps to reproduce the problem:**
Take quest and try to interact with dishes

**Testing Screenshots/Videos/Evidences (always needed):**

![Dangerous Delicacies ](https://user-images.githubusercontent.com/18690551/78460879-b1e37c80-7692-11ea-961e-93f995e9833a.png)
![Dangerous Delicacies 2](https://user-images.githubusercontent.com/18690551/78460883-bc9e1180-7692-11ea-9852-c11c29fb9b0c.png)

**Comment by Kaelang** [comment]
This is working now.
