### ISSUE TITLE
SC Ratnarok - pathing issue

### ISSUE THREAD

**Issue by Derail92** [WarEmu/WarBugs#16241]
Dear Devs - 

Issue - Ratnarock SC Skaven pathing into Order "goal" room. The skaven mobs will walk across the second floor bridge/hallway and teleport into the glowing goal area resulting in a point. They teleport when approaching a flat wall near a barrel. Please see screenshot below for specific location.

**Expected behavior and actual behavior:**

Expect Skaven to path normally to goal area vs teleporting from second floor.

**Steps to reproduce the problem:**

Simply allow Skaven to approach Order goal without intervention to reproduce.

**Testing Screenshots/Videos/Evidences (always needed):**

![Rerail_001](https://user-images.githubusercontent.com/63175146/78464732-2bd33000-76aa-11ea-8c18-378390018496.jpg)

Respectfully submmitted,

Derail

**Comment by Kaelang** [comment]
As this event has now ended, I am going to go ahead and close up this report. _If_ the scenario makes a return in the feature, and this issue persists, please feel free to re-open the report.
