### ISSUE TITLE
[Quest] An Innocent Man

### ISSUE THREAD

**Issue by Sacropedia** [WarEmu/WarBugs#16240]
First of all, I'm unsure if this is the right place to post, but I asked on Discord and was told to make a report for verification whether it's a bug or not.
The main issue is that I don't know whether there SHOULD be a follow-up quest or not.

**Expected behavior and actual behavior:**
Expected: Completing quest "An Innocent Man" in Altdorf by talking to Heilgar Barth in the Clank. Get quest window for follow-up quest. Accept new quest, then go talk to Heilgar Barth (or another NPC) in a different location to complete.
Actual behaviour: Quest window for new quest offered by Heilgar Barth disappears before I have time to read or accept the new quest. Heilgar Barth offers no quest / has no dialogue anymore.

**Steps to reproduce the problem:**
Talk to Warin Foerster in Altdorf to begin the quest chain. Complete the quest An Innocent Man by giving the Loaf to Heilgar Barth. See if he offers a follow-up quest or not, and if the window disappears after a few seconds of idling. None of the NPCs involved in the chain offer a quest so I can't test it without making a completely new character.

**Testing Screenshots/Videos/Evidences (always needed):**
![RoR_possible_bug](https://user-images.githubusercontent.com/63174055/78464210-b174d100-76e6-11ea-8db6-624d79bb8e47.png)

**Comment by valkeera** [comment]
Observation: next stage of this quest will unlock after the character reaches level 40.

**Comment by Kaelang** [comment]
Confirmed above, the final quest in the chain is level 40.
