### ISSUE TITLE
64 bit launcher graphics issue

### ISSUE THREAD

**Issue by Horusaximand** [WarEmu/WarBugs#16246]
Hello. 
I have 64 bit system. If I launch the game with high graphics and turned on post process and lightmaps, graphics works strange. In addition, if I try to change anything, textures always go low, I cannot improve them, and texture cache is on zero. In 32 bit there is no issues, and textures can be improved. 
Best wishes.

**Comment by Kaelang** [comment]
When you say strange, what happens? Can you screenshot?

**Comment by Horusaximand** [comment]
Here. I tested this - it goes if post processing is on.
![IMAGE ISSUE 1](https://user-images.githubusercontent.com/20398365/78553426-091c5500-782b-11ea-82e6-63d2504fca4d.png)
![IMAGE ISSUE 2](https://user-images.githubusercontent.com/20398365/78553434-0ae61880-782b-11ea-93e0-f46a07016daf.png)

**Comment by Kaelang** [comment]
Have you looked for support on the Technical Support subsection of the Forums? I've just replicated the settings you have listed and I don't have any issues.

**Comment by Kaelang** [comment]
Closed. No further information provided.
