### ISSUE TITLE
Talisman.

### ISSUE THREAD

**Issue by Japzor** [WarEmu/WarBugs#16242]
Look like this Skill is bug atm, can only use fist lvl item cant use 25 even if i got 35 i skill.

**Comment by Lheana** [comment]
You need a level skill of 50 to use the level 25 crafting items.

**Comment by Lheana** [comment]
Can you provide more information? Like what item are you trying to use, screenshots, etc.

**Comment by Kaelang** [comment]
Closing as no further information was provided.
