### ISSUE TITLE
Baby gustav

### ISSUE THREAD

**Issue by Japzor** [WarEmu/WarBugs#16243]
The quest in the swers where u have to find Baby Gustav is maybe bug, cant find him anywhere and it my 10 try now :( also rat meat :P

**Comment by Kabucoror** [comment]
Can you pls be more precise which quest do you have the problem with.

**Comment by Lheana** [comment]
Read the text of the quest, it will give you clues about how to save Baby Gustav.

**Comment by Kaelang** [comment]
Closed - no additional information provided and potential solutions given.

**Comment by mythyrylfalcon** [comment]
Quest title is "Poor Gustav." Requirements are to "Slay the Warprot Kidnapper." I've done this more than 6 times in the last 2 weeks and it hasn't completed once.

**Comment by JapzT** [comment]
Im having the same issue. killed him alot of times. never a baby.

**Comment by Lheana** [comment]
Do you have Baby Gustav in your quest inventory? Were you grouped when you killed the NPC?

**Comment by JapzT** [comment]
Hi,

﻿No nothing in me bag. (He drops nothing) and Yes with a group.

**Comment by Japzor** [comment]
Ok Will try ones more then

Sendt fra min iPhone

Den 1. maj 2020 kl. 19.33 skrev JapzT <notifications@github.com>:

﻿

Hi,

﻿No nothing in me bag. (He drops nothing) and Yes with a group.
