### ISSUE TITLE
Selfheal after Szenario Marauder

### ISSUE THREAD

**Issue by Saroras** [WarEmu/WarBugs#16247]
Hello, after a scenario the Marauder's selfheal is at the level of the respective scenario. It will only return to normal when you change your arm or die.

![normal Selfheal](https://user-images.githubusercontent.com/63188758/78472787-e5c6ac80-773b-11ea-9c82-83af7bb87f50.jpg)

![after sz selfheal](https://user-images.githubusercontent.com/63188758/78472792-ed865100-773b-11ea-83fc-0568e0c6a633.jpg)

**Comment by Kaelang** [comment]
Can you include the tooltip please?

**Comment by Kaelang** [comment]
Closed. No further information provided.
