### ISSUE TITLE
Icehearth BO bug

### ISSUE THREAD

**Issue by Aindolur** [WarEmu/WarBugs#16259]
**Expected behavior and actual behavior:**
when engaged with destruction at ice hearth battle objective I was pulled by a marauder across the pathways to a higher ledge and it ported me on top of the mountain range.
![Aindolur_003](https://user-images.githubusercontent.com/63126956/78520538-33670780-7784-11ea-8709-c020691cdfed.jpg)

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Would need more information as to where you was standing when you was pulled, where the mara was when they pulled you etc.

**Comment by Aindolur** [comment]
I was on the lower platform as you ran past the flag deeper into the mines near the edge. The Mara was on the higher elevation near the edge and when he did the pull to him it put me into the pit.
Does that help explain?
If not I will try and get a screenshot using a order placement character for the mara

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Kaelang** [comment]
A screenshot would support replicating the report. It's likely a simple world object clip, but without something to go off, there's not much we can do. Will leave the 2 week / confirmation request up there.

**Comment by Kaelang** [comment]
Closed. No further information provided.
