### ISSUE TITLE
Apostle's Tome of Zeal no fury regen

### ISSUE THREAD

**Issue by shamequa** [WarEmu/WarBugs#16258]
Just purchased titled charm and used in multiple SCs and just spaming group heals in Altdorf.  Never has it regened fury either in or out of combat.  Swapping back and forth between it and Apostle's Tome of Rigor, Rigor works fine.

Thanks,
Shinndigg

**Comment by Kaelang** [comment]
Removing the Tome of Zeal and re-equipping it still doesn't trigger any regen?

**Comment by shamequa** [comment]
I found a fix but there is still a bug. U have to first clear your time slot, then drag, not click, the book into the slot.  The lvl 40 blue book is the same also.
________________________________

**Comment by Lheana** [comment]
This has been fixed with the patch of 08/05/2021.
