### ISSUE TITLE
Stonewatch Fortress Gate

### ISSUE THREAD

**Issue by saupreusse** [WarEmu/WarBugs#16254]
problem:
The Gate at 16k/60k in Stonewatch through which order is supposed to enter the fortress zone is not working. With 500 destro in the zone its impossible to make your way to the fortress and i lost my reservation twice after hours spend in kadrin valley. pretty unfair and frustrating. 
on top of that ryan and I were installing invisible walls on all of the mountainside 2 years ago which makes it impossible to take a pve route to the fortress. So I kinda was digging my own grave here^^

possible fix:
restore functionality of the gate at 16k/60k in stonewatch and/ or remove the invisible walls that I installed on the mountainsides that have no use nowadays anyway. sure would help a ton. there were at least 3 other guys also trying to go to fort standing in front of closed doors, so i guess im not the only one who would like to see this fixed :) all other zones have pve routes to them aswell so i guess there shouldnt be a problem.

**Comment by Kaelang** [comment]
There are other methods to getting into the fort. This looks to be a suggestion / feedback rather than a valid bug report. If you'd like to reopen this as a suggestion, please use the forums.
