### ISSUE TITLE
Destruction can access order rvr warcamp in Reikland

### ISSUE THREAD

**Issue by Caskada95** [WarEmu/WarBugs#16257]
**Expected behavior and actual behavior:**
Destruction can't pass the wall near order warcamp

**Steps to reproduce the problem:**
Just go through the gap in the wall

**Testing Screenshots/Videos/Evidences (always needed):**

![Caskada_027](https://user-images.githubusercontent.com/63212458/78511562-4ee30a00-77a6-11ea-90c1-a7f48b362934.jpg)

**Comment by Kaelang** [comment]
Should be fixed in 06/05/20 patch - please re-open if issues persist.
