### ISSUE TITLE
City Siege: backfill doesn't always occur if someone doesn't join the instance.

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#16266]
**Expected behavior and actual behavior:**

This has happened to our warband twice now. We have queued for the city as a 24-man group and the window popped up asking each person to join the instance. 23 people accepted but 1 person was AFK both times so they didn't join.

This person's slot was not back-filled by a solo queuer meaning we were fighting with 23 people for the duration of the instance. Things we have tried to resolve the issue are:

1) Getting the person who was AFK to queue solo while still in the warband. They did not get an invite.
2) Getting the person who was AFK to queue solo after leaving the warband. They did not get an invite.
3) Getting someone else to queue solo after the siege started. That person did not get an invite to our instance either.
4) Getting someone else to join the warband after the siege started and then queue solo. That person did not get an invite to our instance either.

I believe both times the warband queued up as the queues opened so it could be that there were no solo players in the queue at the time, but then the game is failing to keep checking to see if the instance can be back-filled after that first failed attempt. This is pure conjecture but we've had people miss the invite when we've queued later and they were back-filled just fine.

The most recent time we had someone miss the invite and NOT get back-filled was "Altdorf 3" on Monday 6th April at about 7am GMT or so. We were attacking (destruction).

**Steps to reproduce the problem:**

Queue up with 24 people immediately as the queues open. When the instance invite window pops up, have one of the 24 ignore it and let it just vanish natrually (i.e. don't press decline). Sometimes you will get backfill, othertimes not.

**Testing Screenshots/Videos/Evidences (always needed):**

Scenario parties for the entire siege. One person was missing and not replaced.

![Zomega_091](https://user-images.githubusercontent.com/60266177/78594864-f57be900-7840-11ea-851b-77f43cfa4e8f.jpg)

**Comment by lilimx** [comment]
Fixed with Patch 24/02/2022
