### ISSUE TITLE
Conspirator of Destinies / Unity against Destruction  quests are bugged 

### ISSUE THREAD

**Issue by Zunig** [WarEmu/WarBugs#16267]
Those 2 quests to aquire guild coin from participating in zone lock as a 6 man guild group are currently bugged in a odd way. If your group is in zone, it doesnt matter if you actively participate, guild involve or anything else, quest wont be accounted. 
But if your 6 man guild group is inside dungeon while your realm locks the zone quest completion occurs even if your group had 0 participation in the lock itself.

**Comment by Kaelang** [comment]
Merged with https://github.com/WarEmu/WarBugs/issues/15591.
