### ISSUE TITLE
Gunbad respawn bug, possibly other dungeons

### ISSUE THREAD

**Issue by Zunig** [WarEmu/WarBugs#16265]
Havent tested other dungeons, but right now in Gunbad when you die during boss fight you can respawn and you will stay inside boss room, allowing to freely continue the fight.

**Comment by RoR-Zomega** [comment]
Happens in BS and BE as well (might also be BB but I've not experienced it). It will also often cause the instance to bug out with terror / boss fight barriers not dropping after the fight is over (especially if there was a full wipe) and full respawns of mobs happening.

**Comment by Kaelang** [comment]
Hi,

Which boss' are you able to do this on, and do you have any further information to assist with replicating the problem?

**Comment by Zunig** [comment]
Hello, it seems that after Gunbad totally broke this issue is gone.
