### ISSUE TITLE
Warlord - Sovereign cloaks dyable incosistent

### ISSUE THREAD

**Issue by bosli42** [WarEmu/WarBugs#16261]
I can't dye my BGs Warlord cloak, while both Sovereign cloaks can be dyed. They share the exact same skin, so all of them should be dyable. It is likely that other classes have the same problem (while some classes can't dye their cloaks at all).

**Comment by Kaelang** [comment]
There are two closed reports with similar reports, essentially the response here is that some of the cloaks in-game physically cannot be dyed and was scripted this way by Mythic. For reference, please see this report https://github.com/WarEmu/WarBugs/issues/16182.

Thanks.
