### ISSUE TITLE
Dwarf PQ - Destruction Faction Rewards

### ISSUE THREAD

**Issue by RangeCreed** [WarEmu/WarBugs#16262]
Dwarf chapter 5 PQ *Foul Ruins * offering destruction faction gear in loot bag instead of order.

Completed this PQ twice and both times was offered destruction faction gear as an option inside 1st place PQ's bags,  so unsure if this is just related to the loot table for this specific bag or the PQ in general.

![Warhammer Online  Age of Reckoning Screenshot 2020 04 05 - 19 51 42 50](https://user-images.githubusercontent.com/3491652/78582557-5c8fa280-782d-11ea-9bc2-9774f345c255.png)

![Warhammer Online  Age of Reckoning Screenshot 2020 04 05 - 19 53 34 07](https://user-images.githubusercontent.com/3491652/78582591-69ac9180-782d-11ea-9ef1-937060aa043b.png)

**Comment by Lheana** [comment]
I guess that was a temporary bug with items that got fixed with a server restart.

**Comment by Kaelang** [comment]
Fixed as of 13/05/2020 patch. Please re-open if issue persists.
