### ISSUE TITLE
Cannot interact with anything in game.

### ISSUE THREAD

**Issue by Cote82** [WarEmu/WarBugs#16268]
I cannot interact with anything in the game. Clicking Flight masters, Rally Masters, Vendors, Portals. They all do nothing. I have tried to disable all add-ons to see if there were issues with the addons but the issue persists. I've logged out and exited the game, but that does not work either, and I have tried to clear my cache folder. None of these things work I'm simply stuck unable to fly or interact with anything in the game for no apparent reason. This is persistent in all of my characters as well.

**Comment by Lheana** [comment]
This is not a game issue; for game support please use our forum.
