### ISSUE TITLE
Guild Vault Opens on my screen when another guildie opens it

### ISSUE THREAD

**Issue by Malykhai** [WarEmu/WarBugs#16271]
This never happened to me before, but now it seems to be happening all the time. The Guild Vault Opens on my screen when another guildie opens it. I can be in Dragonwake in the middle of RVR and the Guild Vault will just pop open while I'm fighting. I've asked in guildchat when this happens and it's always another guildmember accessing the vult at that moment.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Sounds like https://github.com/WarEmu/WarBugs/issues/11954.
