### ISSUE TITLE
Cleansing an Empire quest - Step 13

### ISSUE THREAD

**Issue by Drayne69** [WarEmu/WarBugs#16278]
The task: 
Kill 4 Mindless Guard and 8 Mindless Farmer in the cemetery at 39.8k/41.6k.

Return to Lucius Hausen when complete. 

The bug: If you kill the mindless farmers, the quest does not approve the kill points, you need to kill the mindless peasents. 

![kép](https://user-images.githubusercontent.com/63293860/78668393-e3e71f80-78da-11ea-9a56-31b603550a59.png)

**Comment by CrimsonFenris** [comment]
Noticed that as well, but this quest is still bugged a few stages later, without being able to complete (missing items to click), see https://github.com/WarEmu/WarBugs/issues/15441
