### ISSUE TITLE
Teleport on being resurrected by a healer in different zone

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#1627]
Today i died in RVR near the borderline of Troll Country/Ostland (between the two warcamps, closer to destro), got resurrected by a healer, clicked "accept" and was teleported to the top of Troll Country map (something like 30500, 900).

**Comment by Tesq** [comment]
happened to me too, tough it was a random bug.

**Comment by Abolition** [comment]
Yeah that happened to me today, too.

**Comment by hoppolek** [comment]
If someone res a player over the zone borderline, the player gets teleported to the healer's coordinates but on the dead player's map. I've seen it happen several times at the Avelorn/Saphery border.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
