### ISSUE TITLE
Crafting Bug

### ISSUE THREAD

**Issue by RaersChen** [WarEmu/WarBugs#16275]
https://studio.youtube.com/video/m8TIjMGWRPw/edit
https://studio.youtube.com/video/wl12MuHzCsU/edit

ID in Game : Sunoffire

**Comment by Gunlingers** [comment]
And how did you stack 360 Goldweed?

**Comment by RaersChen** [comment]
Hi Sir,

Please check the vedio by below

https://youtu.be/FL0DHV1JOdc



Gunlingers 於 2020/04/10 下午 06:42 寫道:

**Comment by Kaelang** [comment]
I can't open the first two links, only the third video, which doesn't highlight what you're trying to report. Please provide more information as to what this report is for.

**Comment by Kaelang** [comment]
Closed. No further information provided.
