### ISSUE TITLE
Scenario: Eternal Citadel - Broken Order Portal

### ISSUE THREAD

**Issue by Dalsie** [WarEmu/WarBugs#16283]
**Expected behavior and actual behavior:**
Portal to take to the main arena, but nothing happens when contact with portal.
Portal behind allows to exit scenario

Destro seems to be able to obtain points as normal.

**Steps to reproduce the problem:**
Attempt to run through portal

**Testing Screenshots/Videos/Evidences (always needed):**
![1](https://user-images.githubusercontent.com/22501546/78676632-9bc9fc00-78de-11ea-80ea-dcf84f19c10b.jpg)
![2](https://user-images.githubusercontent.com/22501546/78676637-9c629280-78de-11ea-92cd-93fd3a854370.jpg)

**Comment by Kaelang** [comment]
Just played this and had no problems. Please re-open if you're still experiencing issues.
