### ISSUE TITLE
Rain of Fire stacking/Bright wizard BW

### ISSUE THREAD

**Issue by Poisonedshotz** [WarEmu/WarBugs#16289]
**Expected behavior and actual behavior:**
Targeted ground aoe's should not be able to stack multiple times from multiple caster BWs

**Steps to reproduce the problem:**
Unknown

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/63316382/78711613-40e7d300-78e5-11ea-9da3-b306dcdef0c8.png)
Image by Illuminati on the RoR forums

**Comment by kalmatar** [comment]
you start with Zareb ROF area
you take a step maybe one direction, enter Naen ROF area
you take step back to Zareb ROF area
this ROF ends, or you enter Nuketown ROF area

without video all above can be explained by you walking from one place to the next place, even if its 1ft of movement. or under lag conditions, server somehow assumes you are in movement, but might not have been.

**Comment by Vdovics** [comment]
I will try to record evidence, but its most obvious in Fort siege. Was staying at the backdoor and took huge amount of damage with combat log showed at least 2 rain of fire hits in same second from 2 different person.

**Comment by Kaelang** [comment]
Will keep this open whilst you aim to record evidence. There's rumours circulating about this, but without some solid evidence to support a report I can't necessarily move it further.

**Comment by Kaelang** [comment]
Closed. No further information provided.
