### ISSUE TITLE
Fury of da green / Energy of Vaul imbalance

### ISSUE THREAD

**Issue by cimator** [WarEmu/WarBugs#16284]
Expected behavior and actual behavior: 
Fury of da green and Energy of Vaul are exactly mirrored abilities for Shaman and AM on 13th point of lifetap tree, so with same build, they should heal for the same. However Energy of Vaul's base healing is lower than fury of da green.
Ability heals for X amount +%50 of total damage inflicted (Im saying X because the tooltip value has been way off for some time)

Screenshots;
![fodg heal](https://user-images.githubusercontent.com/17130290/78698295-c92c9f00-790a-11ea-8b08-7fa48bb31254.jpg)

This is the FoDG healing; 1243 total heal - 169(%50 of 337 total damage), puts it at 1074 base healing amount.

![EoV heal](https://user-images.githubusercontent.com/17130290/78698477-16107580-790b-11ea-90f7-6fa1d5bde509.jpg)

This is the EoV healing; 1547 total heal -592 (%50 of 1185 total damage), puts it at 955 base healing amount.

Result;  Fury of da green heals for 1074 + %50 of damage inflicted, Energy of Vaul heals for 955 + %50 of damage inflicted.

Note that this test was done with the same build for both classes without any heal buffs or debuffs, casting both at 1 mechanic point, and the same willpower+healing power for both classes. (although this wouldnt matter anyway since the healing on this ability doesnt scale with any stat, including willpower)

Conclusion on why this happens; either the base healing value on EoV is just wrong, or it might be because EoV doesnt scale with mastery points in that tree, or doesnt scale as much as Fury of da green. I can test if the scaling with mastery points is the problem, if needed.

**Comment by grunbag** [comment]
fixed with next pat ch

**Comment by cimator** [comment]
Closing, tested it after todays patch, looks like you guys fixed it already, thanks :D
