### ISSUE TITLE
something has gone wrong when attempting to add contribution to you, please report on the bugtracker the circumstances of you entering the fort

### ISSUE THREAD

**Issue by xFailsafeNY** [WarEmu/WarBugs#16286]
![image](https://user-images.githubusercontent.com/18269402/78707863-332f4f00-78df-11ea-9f6a-51ba7cfea6f0.png)

**Comment by Kaelang** [comment]
Needs more information - what was you doing that lead up to this?

**Comment by xFailsafeNY** [comment]
I walked into a fort after a zone flip.

**Comment by Kaelang** [comment]
That's apparent. However this is not able to be replicated without more information. Which fort was in, what did you do beforehand, did you get a reservation, was you solo, was you in a pug etc.

Bug reports are here to investigate issues that are being raised, not to give the development team minimal information to use to test to see where the issues come from.

If you experience this again, please open a report with a full and detailed explanation of steps which will allow the team to replicate said issue - or at least know where to begin.

For now, I'm going to close this.

**Comment by cooler-SAI** [comment]
we are back,@xFailsafeNY , wanna join? https://github.com/Shmerrick/ProjectWAR
