### ISSUE TITLE
Bag roll isnt poping up, and im missing the loot

### ISSUE THREAD

**Issue by Hypina** [WarEmu/WarBugs#16287]
Hello

This is happening last few day to me and its realy frustrating. (sorry for the strong words)
When i dontribute to a zone where we actualy siege a keep, get it and lock it. I do not get the popup for bag roll at all. Also i dont get any main. 
As you can clearly see in the video, i have enough contrubution to join the fort siege but i do not get any reward for the keep. This happend so many times for me. Please take a look into it :-) 

thx

https://www.youtube.com/watch?v=uaroIziH8nA

**Comment by Kaelang** [comment]
In your chat log it says that you rolled on the bag and your change to roll higher moving forward is increased. Can you confirm if you've received any bags since this report?

**Comment by Kaelang** [comment]
Closed. No further information provided.
