### ISSUE TITLE
Mara Thunderous blow cooldown wrong (again?)

### ISSUE THREAD

**Issue by Squanchbob** [WarEmu/WarBugs#16292]
Mara Thunderous blow cooldown wrong (again?)
![Снимок экрана (138)](https://user-images.githubusercontent.com/63323228/78728292-9e107280-793f-11ea-9fcb-ff96514a3580.png)
![Снимок экрана (137)_LI](https://user-images.githubusercontent.com/63323228/78728301-a5378080-793f-11ea-8896-51a5cad47353.jpg)

**Comment by Stompah** [comment]
Still wrong....
![Cleganes_000](https://user-images.githubusercontent.com/68201609/87254964-718f5980-c44c-11ea-80a5-daf6796bf274.jpg)

**Comment by grunbag** [comment]
Seems fixed already
