### ISSUE TITLE
Mix of Login server and Altdorf

### ISSUE THREAD

**Issue by Niafangobis** [WarEmu/WarBugs#16291]
Hello,

I crashed in MoM, instead of going in the choice character screen I had this.
I could moove around Altdorf, nothin happened when I pressed other buttons.

![Niafangi_001](https://user-images.githubusercontent.com/63320844/78722924-b9bd4e00-792a-11ea-8252-e37dbb4c25d3.jpg)

**Comment by Kaelang** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/11224.
