### ISSUE TITLE
Talabec/Passwatch Castle Leap-to-Wall spot

### ISSUE THREAD

**Issue by colintgallagher** [WarEmu/WarBugs#16294]
![Sarnai_023](https://user-images.githubusercontent.com/56422919/78734502-7658e480-7916-11ea-9f02-0b7decc02d4a.jpg)
![Sarnai_026](https://user-images.githubusercontent.com/56422919/78734516-7eb11f80-7916-11ea-9389-6b80665602d3.jpg)

You can spam-jump up onto the spikes from below, then any class with a leap/pounce can get onto the walls.

**Comment by dalen** [comment]
Fixed by the 2020-09-09 patch
