### ISSUE TITLE
Invalid player behavior

### ISSUE THREAD

**Issue by Gimmen** [WarEmu/WarBugs#16299]
Constant curses and insults of other players in the Russian chat in Russian from the player Unna. I attach screenshots.
![Farlanda_200](https://user-images.githubusercontent.com/36737290/78755582-11d36f00-7982-11ea-82f8-809fca5d0a08.jpg)
![Farlanda_201](https://user-images.githubusercontent.com/36737290/78755586-13049c00-7982-11ea-8498-28f250c85b17.jpg)

**Comment by Lheana** [comment]
The Bugtracker is made for **game issues**. To report players, please contact our GMs.
