### ISSUE TITLE
CTD in orvr WB while resurrecting 

### ISSUE THREAD

**Issue by Myrdothilore** [WarEmu/WarBugs#1629]
I was in a WB doing some open rvr on my zealot and as soon as the resurrect I cast on a player finished the game crashed to desktop. I was in BV doing a keep siege when this happened, and there were two wb's of destro there and maybe 2 wb's of order defending the keep from us.

**Comment by Luth-RoR** [comment]
I suspect the known random (mass-)CTD that happens sometimes in mass fights.
