### ISSUE TITLE
Witch Hunter Sovereign Justicar hat is purple

### ISSUE THREAD

**Issue by Shukiden** [WarEmu/WarBugs#16293]
Self explanatory. 
![purple hat](https://user-images.githubusercontent.com/62631317/78728765-126df600-78ed-11ea-9e0b-6f8d125a930f.png)

**Comment by wargrimnir** [comment]
This appears correct in the DB to me

**Comment by Kaelang** [comment]
Should be fixed in 06/05/20 patch - please re-open if issues persist.
