### ISSUE TITLE
Guild bank slot requires over 50k gold

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#16297]
**Expected behavior and actual behavior:**
Normally the beginning guild  vault slots aren't that expensive. Now they are insanely randomly overpriced.

**Steps to reproduce the problem:**

make a guild open its bank vault once unlocked.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/43802105/78746249-f2115c00-792b-11ea-85c8-37edfd404862.png) 
![image](https://user-images.githubusercontent.com/43802105/78746288-081f1c80-792c-11ea-8821-acc8b59c4a20.png)

**Comment by jlpdiez** [comment]
Ours are bugged too and it's not a new issue, been seeing them like that for like 3 weeks. Buying a new page is ok it seems. Quite annoying.
![Ettenhard_244](https://user-images.githubusercontent.com/3782057/79022260-d00f1800-7b7d-11ea-85d6-26648894fecb.jpg)
![Ettenhard_245](https://user-images.githubusercontent.com/3782057/79022269-d56c6280-7b7d-11ea-874c-f02ddfcac673.jpg)
![Ettenhard_246](https://user-images.githubusercontent.com/3782057/79022277-dc937080-7b7d-11ea-86da-b91a2cc5cf15.jpg)

**Comment by Sandskid** [comment]
![Clip2net_200505014623](https://user-images.githubusercontent.com/20923238/81020767-40097900-8e72-11ea-8ecd-d05c62702f08.png)

Same issue

**Comment by Rivenspeak** [comment]
Ours is also bugged.
![Drysthorn_005](https://user-images.githubusercontent.com/45123644/82050525-4673ce00-9686-11ea-845a-b9540583298a.jpg)

**Comment by avalus** [comment]
![image](https://user-images.githubusercontent.com/6005224/82349067-f1bfb280-99f9-11ea-80b7-b59db6c1d57d.png)
![image](https://user-images.githubusercontent.com/6005224/82349128-0734dc80-99fa-11ea-9aa6-a61f2b0c6cd5.png)

**Comment by Roxylee** [comment]
![image](https://user-images.githubusercontent.com/66108052/83227688-c869f980-a152-11ea-937a-82f01e563add.png)
since this is an ongoing issue for about 2 months now, is anything being done or has anything been done yet? this is quite annoying to have this happen. I mean come on, 50k+ gold for the SECOND slot in the first vault? A little outrageous and wasn't like this before.....would like to see it fixed soon. Not 2 years from now.

**Comment by MaxHayman** [comment]
Fixed in hotfix today

**Comment by Rivenspeak** [comment]
The hotfix appears to have fixed the amount, but it doesn't allow actual purchase of the expanded spots.

Expected Action:
Clicking OK will add new slots

Actual Action:
Clicking OK just closes dialog box with no slots added

![Drysthorn_011](https://user-images.githubusercontent.com/45123644/83753706-c44d4880-a638-11ea-80f0-69f0b8b01890.jpg)
