### ISSUE TITLE
[WH] Razor strike + sweeping razor tactic NOT building any combo point/accusations

### ISSUE THREAD

**Issue by dadkkak** [WarEmu/WarBugs#16302]
As topic says: since 8/4/2020 patch, with sweeping razor tactic equipped the skill Razor Strike doesn't build any accusation/combo point. I hope this is not intended because it will make the tactic basically useless.

**Comment by dadkkak** [comment]
Ps. This is while hitting targets (dummies)

**Comment by dadkkak** [comment]
I can confirm it doesn't work on characters either

**Comment by grunbag** [comment]
Without tactic it build accusation ?

**Comment by dadkkak** [comment]
Yes it does

**Comment by grunbag** [comment]
Fixed with next reboot
