### ISSUE TITLE
Ironbreaker "furious reprisal" have bug if you change map

### ISSUE THREAD

**Issue by windchan1983** [WarEmu/WarBugs#16304]
Ironbreaker "furious reprisal" have bug if you change map

**Comment by Kaelang** [comment]
See https://github.com/WarEmu/WarBugs/issues/15857. Can you confirm if Furious Repirsal works if slotted in a different tactic slot?

**Comment by windchan1983** [comment]
I try to place it in1st slot, it is fine now
But the skill is slot 4 is bug .....

**Comment by Kaelang** [comment]
Thanks for confirming, seems related to https://github.com/WarEmu/WarBugs/issues/15857. Closing.
