### ISSUE TITLE
War Story - Sentinel Story Line

### ISSUE THREAD

**Issue by Glopfel** [WarEmu/WarBugs#16300]
**Expected behavior and actual behavior:**

Hi there,

I've done BE zone many times until now but i can't see BE Story Line for Influence Rewards (Sentinel Change Ring). I've uploaded the screenshot of my War Report, the Sentinel Set items i've gathered so far and also my active Sentinel Set Quests.

Thanks in advance.

**Testing Screenshots/Videos/Evidences (always needed):**

![Lays_000](https://user-images.githubusercontent.com/63346136/78774283-2709c700-799d-11ea-8c6b-cd0f2b65832d.jpg)
![Lays_001](https://user-images.githubusercontent.com/63346136/78774768-d181ea00-799d-11ea-947c-140c9a761a4e.jpg)
![Lays_003](https://user-images.githubusercontent.com/63346136/78774798-dc3c7f00-799d-11ea-89ff-b15c323ffa8a.jpg)
![Lays_004](https://user-images.githubusercontent.com/63346136/78774801-dd6dac00-799d-11ea-86ac-b0fe6b5e8933.jpg)
![Lays_005](https://user-images.githubusercontent.com/63346136/78774803-de064280-799d-11ea-926f-f8603384e9d2.jpg)
![Lays_006](https://user-images.githubusercontent.com/63346136/78774804-de9ed900-799d-11ea-9461-763feed09bd7.jpg)
![Lays_007](https://user-images.githubusercontent.com/63346136/78774809-de9ed900-799d-11ea-9f7a-16f0b15cfc0f.jpg)
![Lays_002](https://user-images.githubusercontent.com/63346136/78774810-df376f80-799d-11ea-8f4b-ade4620f7767.jpg)

**Comment by Kaelang** [comment]
Are you still experiencing this? Have you tried clearing your cache in the RoR directory?

**Comment by Glopfel** [comment]
> Are you still experiencing this? Have you tried clearing your cache in the RoR directory?

Sadly, even after clearing everything inside the Cache folder in RoR main directory i still can not see anything except Bastion Stairs and Gunbad.

**Comment by Kaelang** [comment]
This could be related to a corrupt file. I've just checked and the BB/BE Influence Reward is visible for me. 

![image](https://user-images.githubusercontent.com/60117106/79745399-1bed5a00-8300-11ea-8424-b0056a2f41bb.png)

For troubleshooting purposes - would you mind trying to reinstall the client and it's game files to see if this problem is on your side, rather than server-side?

**Comment by Glopfel** [comment]
> This could be related to a corrupt file. I've just checked and the BB/BE Influence Reward is visible for me.
> 
> ![image](https://user-images.githubusercontent.com/60117106/79745399-1bed5a00-8300-11ea-8424-b0056a2f41bb.png)
> 
> For troubleshooting purposes - would you mind trying to reinstall the client and it's game files to see if this problem is on your side, rather than server-side?

Sure, i will try reinstalling the game after a clean uninstall.

**Comment by Glopfel** [comment]
> This could be related to a corrupt file. I've just checked and the BB/BE Influence Reward is visible for me.
> 
> ![image](https://user-images.githubusercontent.com/60117106/79745399-1bed5a00-8300-11ea-8424-b0056a2f41bb.png)
> 
> For troubleshooting purposes - would you mind trying to reinstall the client and it's game files to see if this problem is on your side, rather than server-side?

It's fixed now, as you said, might have been due to some corrupt file in my RoR directory. Thanks. :)
