### ISSUE TITLE
No More skills/Tactics after Patch.

### ISSUE THREAD

**Issue by Tsunade92** [WarEmu/WarBugs#16301]
WHen relog we dont have anymore skills/tactics :).

![image](https://user-images.githubusercontent.com/63303595/78787303-730f3880-79aa-11ea-82f5-de0e59c08b9c.png)

**Comment by Kaelang** [comment]
Fully reload your launcher / client. It's been hotfixed.

**Comment by Kaelang** [comment]
Closing as this was fixed during the patch.
