### ISSUE TITLE
Auction house - posted items are not shown in AH

### ISSUE THREAD

**Issue by Garrthax** [WarEmu/WarBugs#16303]
Tested both with and without mods, but result is same - when i post items to ah, they are not shown in auction list at all.

![image](https://user-images.githubusercontent.com/49390790/78790868-6c36f480-79af-11ea-978c-92d8ccb97cd1.png)
![image](https://user-images.githubusercontent.com/49390790/78790876-70631200-79af-11ea-9827-cdecd861ad41.png)

**Comment by Kaelang** [comment]
Can you confirm which items you are trying to post? And are they leaving your bag?

**Comment by Garrthax** [comment]
they are not in bag and it only happens with lasting stachion ungunet

**Comment by Garrthax** [comment]
btw look at forum, there are plently of ppl with same problem

**Comment by Clemmongrab** [comment]
I'm having the same problem, also with Stanchion Ungents.
![AH bug_1](https://user-images.githubusercontent.com/64180319/80053396-734b2000-84e2-11ea-85d7-adc758b5476f.png)
![AH bug_2](https://user-images.githubusercontent.com/64180319/80053401-747c4d00-84e2-11ea-937c-fc89fc1a8361.png)

**Comment by Garrthax** [comment]
looks like problem is when we undercut price, for higher than lowest price in ah i see them

**Comment by Clemmongrab** [comment]
I tried posting for higher than lowest price, still doesn't show.

![AH bug_1](https://user-images.githubusercontent.com/64180319/80110862-c6ee5580-8544-11ea-9646-e79d03f2758d.png)
![AH bug_2](https://user-images.githubusercontent.com/64180319/80110867-c8b81900-8544-11ea-9b21-f6fa3b6dbb84.png)

**Comment by Skylynx82** [comment]
I am also having this issue.  When I put 660 armor pots up for sale it comes out of my bag, money taken as auction fee but it doesn't show up in the for sale list not matter what price i set it to. I can cancel auction and get them back just doesn't show on for sale list

**Comment by Kaelang** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/14566.
