### ISSUE TITLE
AM EoV (Energy of Vaul) - not healing others when self-selected as defensive target

### ISSUE THREAD

**Issue by keunglh** [WarEmu/WarBugs#16309]
**Expected behavior and actual behavior:**
EOV is supposed to aoe heal around the defensive target. However, when you select yourself as the defensive target, it does not aoe heal.

**Steps to reproduce the problem:**
Select yourself as defensive target and stand by others within your 20 ft range and cast EOV. 

**Testing Screenshots/Videos/Evidences (always needed):**

![EOV myself](https://user-images.githubusercontent.com/14348489/78806746-bd7fbd80-7988-11ea-8498-3e63ed4baa7a.JPG)
![EOV others](https://user-images.githubusercontent.com/14348489/78806748-bf498100-7988-11ea-89ef-d89c53e95f47.JPG)

**Comment by cimator** [comment]
Can confirm same bug on shaman fury of da green aswell

**Comment by Garrthax** [comment]
any news? still persist on shaman at last

**Comment by Grumug** [comment]
Any update to that?Ability still not working as intended when the defensive target is the caster.

**Comment by NabaroNya** [comment]
I can confirm this bug at this moment

**Comment by yuaa2** [comment]
still bugged.....

**Comment by Undrsiege** [comment]
Still isssue exists

**Comment by lilimx** [comment]
Fixed with Patch 22/07/2021
