### ISSUE TITLE
Scenarios are bugged, Destro gets all flags in the start.

### ISSUE THREAD

**Issue by Korize1** [WarEmu/WarBugs#16305]
**Expected behavior and actual behavior:**

Expected, for the flags to be empty.
Actual, Destro has all of them pre-capped while joining a Fresh scenario.

**Steps to reproduce the problem:**

Just join it.

**Testing Screenshots/Videos/Evidences (always needed):**
https://media.discordapp.net/attachments/329292495336767488/697462295336452106/unknown.png

**Comment by Kaelang** [comment]
Can confirm this happens in Gromril Crossing. All neutral BO's are set to represent Destruction, leading to the points generating throughout the game for Destruction.
