### ISSUE TITLE
Purple seed disappeared after game crash

### ISSUE THREAD

**Issue by HotshotCLG** [WarEmu/WarBugs#16318]
I had the purple wounds + mcrit seed and it disappeared from my inventory after a disconnect. I found the seed during a gunbad run a day ago.

https://i.imgur.com/xOWqodF.png

I'm not sure what caused it.

**Comment by HotshotCLG** [comment]
Character name: HotshotGG

**Comment by Kaelang** [comment]
Unsure how to suggest a replication, however in regards to the item, the team don't involve themselves in recoveries. Did the item return at any point?

**Comment by Kaelang** [comment]
Closed. No further information provided.
