### ISSUE TITLE
Gunbad PQ's and Respawn Issue

### ISSUE THREAD

**Issue by Eryal** [WarEmu/WarBugs#16316]
During todays Gunbad middle wing run we cleaered the bosses and Ard to Feed, however leaving the boss instance all mobs we back up and the entrance to Solithex was red and unbable to be accessed. 

Upon dying anywhere in Gunbad you also returned to the start area rather than the nearest healer and had to fight the mobs all over again.

**Comment by Lheana** [comment]
Was it before or after the patch of yesterday?

**Comment by Eryal** [comment]
This was 8/4/2020 after the patch.

**Comment by gerard86** [comment]
i dont think the current situation in gunbad is what the devs intended i think there are multiple bugs, for example the mobs respawn too fast, so if wiped on pq bosses, need to reclear trash and hero mobs like mixas of left wing respawn which is not intended im sure

**Comment by gerard86** [comment]
also all respawns are back at the start of the instance with means a full reclear per wipe

**Comment by XmatXergon** [comment]
made fast vid from dev server
https://youtu.be/8RfMzHTit8Y

pretty much showing random pulls of mobs from far away
and instant respawn of some already killed mobs
also, when u finish end boss and u port out through barrier, it will respawn all mobs u killed before

**Comment by grunbag** [comment]
Fixed already
