### ISSUE TITLE
Gunbad mid wings a gazillions mobs spawn.

### ISSUE THREAD

**Issue by sparksumo** [WarEmu/WarBugs#16317]
Gunbad as you decending mid wings a gazillions mobs spawn attacking palyers from everywhere.

![A gazillion mobs in GB](https://user-images.githubusercontent.com/63373403/78833150-65fa4580-79ba-11ea-9b9e-347d6ca13049.png)

**Comment by acidicrain** [comment]
https://youtu.be/77wCkS0xkLY
