### ISSUE TITLE
Gromril Crossing and Praag Scenarios start with Destro in control of all Flags.

### ISSUE THREAD

**Issue by SetchDreskar** [WarEmu/WarBugs#16311]
**Expected behavior and actual behavior:**
The flags should start at a neutral position for both sides.

**Steps to reproduce the problem:**
Has been every instance of GC and Praag I have been in so far, so it is a constant issue at least on my end.

**Testing Screenshots/Videos/Evidences (always needed):**
https://clips.twitch.tv/AltruisticFrozenStar4Head - GC Bugged

https://clips.twitch.tv/GoldenAlertPeachSMOrc - Praag Bugged

**Comment by dalen** [comment]
This was fixed in the hotfix
