### ISSUE TITLE
[SW] m4 morale is stuck on action skill bar

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#16310]
![stuck](https://user-images.githubusercontent.com/19988772/78805793-d924ab80-79fc-11ea-88be-6804689e0f38.jpg)

basic m4 hail of doom is stuck inside my action skill bar.
it's bind on #1 key of assault stance.
i can't remove it or replace.
tried deleting character setting ( ror/user/settings/Martyrs Square/~ )
but it's still there. and skill is fire when m4 is rdy.

today after patch, all my action skills were removed from skill bar.
except that m4 in assault stance 1 key.

it's been there quite long actually. i don't remember how it got there though. 
other morales i can't put on skill bar as it shouldn't.
i think i put assault m4 there when it was free skill with long CD.

if it's not bug, any idea how to fix it?

**Comment by dalen** [comment]
It is a bug in the Morale Circle addon. I think it is fixed in the latest version of that addon though.
