### ISSUE TITLE
Punishing knock IB tactic broken

### ISSUE THREAD

**Issue by plutobhg** [WarEmu/WarBugs#16313]
Punishing knock heal debuff will apply in ORvR but not in scenario

**Comment by Kaelang** [comment]
See https://github.com/WarEmu/WarBugs/issues/15857. Can you confirm if Punishing Knock works if slotted in a different tactic slot?

**Comment by plutobhg** [comment]
Howdy, 
I did some testing and if i reset my tactics each time I zone it works, so something is possibly bugged with this character profile 
    On Sunday, April 19, 2020, 10:12:39 AM PDT, Kaelang <notifications@github.com> wrote:  
 
 


See #15857. Can you confirm if Punishing Knock works if slotted in a different tactic slot?

**Comment by Kaelang** [comment]
Thanks for the confirmation. Looks to be related to both https://github.com/WarEmu/WarBugs/issues/12902 and https://github.com/WarEmu/WarBugs/issues/15857. I'm going to close this for now to keep things compiled together. I've referenced this listing in the other issues quoted.
