### ISSUE TITLE
No bag in mailbox from city siege

### ISSUE THREAD

**Issue by Chudas** [WarEmu/WarBugs#16326]
Dear support,

I have been in city siege today (9th of april 2020), instance number 14, with runepriest Ublian, and on 3rd stage i have won a bag. Like a minute or so, after rolls, i have been teleported out of the city, so i couldn't loot my bag. I hoped, that the bag will arrive by malbox, but nothing happened. I tried to re-log and wait a bit more, but nothing. Any possibility you could fix this? Thank you, Ublian.

**Comment by Lheana** [comment]
The Bugtracker is not a support, it is made for game issues.
You will surely receive your bag after a server restart.
