### ISSUE TITLE
SH pounce on city stage 2 boss

### ISSUE THREAD

**Issue by Horusaximand** [WarEmu/WarBugs#16327]
Hi. While using pounce on boss in city stage 2 – SH falls under the ground and dies.

**Comment by Horusaximand** [comment]
I happened in IC siege, order boss was in the central objective fighting destr boss,

**Comment by Kaelang** [comment]
Would need more information if the team was going to attempt to replicate. Screenshots of locations etc next time you're in a city if possible.

**Comment by Horusaximand** [comment]
It happened once, a month ago. Probably, this issue is closed for now
