### ISSUE TITLE
game crashing

### ISSUE THREAD

**Issue by segarson** [WarEmu/WarBugs#16328]
today when i tried to enter tor anroc with two different chars both times the game crashed yesterday i got in fine i looked at changing my video inputs did that and the game still crashed

**Comment by Lheana** [comment]
The Bugtracker is for game issues only. For game support, please use our forum. As a note, try to close and restart your launcher, maybe something did not update correctly.

**Comment by segarson** [comment]
I have done that several times in of in and try to do tor anroc as it transfor to it it crashes every time I did have this problem to the last up date

Sent via the Samsung Galaxy S7 active, an AT&T 4G LTE smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
