### ISSUE TITLE
Gunbad influence after the PQ removal

### ISSUE THREAD

**Issue by Tibdum** [WarEmu/WarBugs#16329]
Now since the PQs in Gunbad got removed, what will happen with the influence bar and the rewards?

Will them be removed aswell or will be redesigned?
![gunbad](https://user-images.githubusercontent.com/47664666/78932036-7e985780-7aaf-11ea-8c55-c3dc3b64f4ad.png)

**Comment by dalen** [comment]
It will likely give influence in a similar way to City dungeons or Bastion stairs. But Hargrim & Grunbag will decide I think

**Comment by Hargrim** [comment]
Influence added.
