### ISSUE TITLE
Missing Character Itangi

### ISSUE THREAD

**Issue by buffel73** [WarEmu/WarBugs#16324]
Hi

After the last patch my swordmaster " Itangi" is missing.

Please assist

Regards

**Comment by Kaelang** [comment]
Not necessarily a bug. Make sure you are logged into the correct account.

**Comment by buffel73** [comment]
I have only one account.
here is screenshot of all my user file
![Annotation 2020-05-03 180014](https://user-images.githubusercontent.com/63406655/80919035-16fcc180-8d68-11ea-9d15-ea6e00503c8c.png)

**Comment by Kaelang** [comment]
Click left/right on character pages.

**Comment by buffel73** [comment]
Hi still not there
