### ISSUE TITLE
Gunbad left wing boss barrier permanently red

### ISSUE THREAD

**Issue by GrayDorian** [WarEmu/WarBugs#16333]
After the latest Gunbad patch, the left wing boss door to Glomp da Squig Masta does not open even if all other boss mobs prior have been downed (ol Greenwingz and his squig partner, Foul Mouf, Nurgle boss, the troll, the other goblin with the squig prodding hand)

The boss barrier stays red and there is no way to enter the final zone. Tried this with three different group combinations with the players here: GuyMontag (me), Mettius, Lirance, Washer, Piratelife, Aremdor, Raulod, Solfar

**Expected behavior and actual behavior:**
Expectations were Gunbad left wing boss lair opening after PQ objectives complete - tried to complete all kills despite the PQ not happening, and killed all bosses

Actual behavior was the boss door still being red

**Steps to reproduce the problem:**
Enter Gunbad, go down left wing, fight the bosses in this order (Wyvern and Squig, Troll, Nurge Beast, Foul Mouf, Horrible goblin next to Foul Mouf), attempt to zone into Glomp da Squig Masta's lair

**Testing Screenshots/Videos/Evidences (always needed):**
https://user-images.githubusercontent.com/63432349/78951866-379f6780-7a99-11ea-9fc4-c925d6c53a44.png

**Comment by engharat** [comment]
Gunbad mid have similar issue, but in our case the spider/goblin boss did not spawn at all. we moved forward because there was no barrier, but also the big ghost boss was missing(and final boss portal was red obviously).

**Comment by Hargrim** [comment]
Fixed with Gunbad PQ redesign.
