### ISSUE TITLE
Cannot add talisman to some equipment

### ISSUE THREAD

**Issue by cormeister** [WarEmu/WarBugs#16336]
My WP (Execortioner) is currently level 18. I am attempting to add the level 16 talisman (Minor Talisman of the Contender) to two pieces of gear: Fighter's Bandolier of Dominion and Obliterator Shankboots. But, this talisman will not add to the gear. From the talisman window after shift-clicking on the gear, I drop the talisman stack or single talisman into the slot and nothing happens. I was able to add this talisman to other gear that I have (including the other pieces of the Obliterator set) but not these two pieces of gear. I'm not sure if I'm doing something wrong or if this is a bug. Thanks!

**Comment by RoR-Zomega** [comment]
The talisman's item level cannot be higher than the item level of the piece you are putting the talisman into. Looking at the armour the item level of that talisman is 16 while the item level of the Bandolier is only 13, meaning the talisman is too high for it.

However, the item level of the Obliterator Shankboots is 21 which means the talisman should slot into it. Going by your report it looks like it could be bugged for the boots only.

**Comment by cormeister** [comment]
Hello! You're absolutely right. The talismans are higher level than all of my gear, including the boots (which are level 15). So that's what the issue is here. Sorry! I'll close out the report. Thanks!
