### ISSUE TITLE
Camera clipping through walls inside Praag northern keep

### ISSUE THREAD

**Issue by Snifflebutts** [WarEmu/WarBugs#16331]
**Expected behavior and actual behavior:**
Walls blocking camera pans
Actual, clipping through walls

**Steps to reproduce the problem:**
Panning camera into these walls
Staircase from bottom straight into lord's room, right wall as you move up
Main staircase to the outter of lord's room, the roof at the turn on stair

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/62215736/78945287-4d497700-7b03-11ea-9092-399c169c6530.png)
![image](https://user-images.githubusercontent.com/62215736/78945317-5c302980-7b03-11ea-93b5-52a987e893e1.png)

**Comment by Kaelang** [comment]
See https://github.com/WarEmu/WarBugs/issues/10813.
