### ISSUE TITLE
RR61 Emblem Books/Chalices have wrong stats

### ISSUE THREAD

**Issue by saupreusse** [WarEmu/WarBugs#16349]
Problem:
So the RR61 Warrior Priest Books and DOK Chalices are really bad compared to their 16renown levels lower predecessors. Atm there is no reason at all to buy these items since they dont do anything better than the rr45 books/chalices.

Screenshot:
https://pasteboard.co/J2zG951.png

Solution:
Buff the RR61 Books and Chalices for a good amount. Give them more healing power, more wounds and more willpower.

**Comment by Kaelang** [comment]
The stats are different which is enough to suggest these aren't necessarily bugged. That being said, I'll tag this up and wait for verification from one of the team.

**Comment by wargrimnir** [comment]
These have an additional 3 morale per second. That more than makes up for the difference in level.
