### ISSUE TITLE
Gunbad Right Wing Boss Entarance Blocked?Red

### ISSUE THREAD

**Issue by Eryal** [WarEmu/WarBugs#16345]
We killed all 3 PQ Bosses and all small bosses on the 3rd PQ (Redeye Masta's and Shaman Vaerboom) 
and the door for the Masta Mixa was still red and we could not enter.

![Eryall_002](https://user-images.githubusercontent.com/63373185/79032919-fc3c9000-7ba1-11ea-8f0f-985becc80e8c.jpg)

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Hargrim** [comment]
This is fixed with PQ redesign in Gunbad.
