### ISSUE TITLE
Easter Wyvern egg hunt 

### ISSUE THREAD

**Issue by NSKaneda** [WarEmu/WarBugs#16343]
Mill in the middle of Empire PQ in Troll Country, ~7.5k, 38.8k has 6 eggs high out of reach (squig kaboom's not high enough to reach it from fence), no branches, rocks or ropes to jump on, no hole at the bottom of the mill - there's no way to get those eggs without flying

![Burszui_109](https://user-images.githubusercontent.com/22037960/79029992-348aa100-7b97-11ea-81c1-023a7a4cfc6e.jpg)
![Burszui_110](https://user-images.githubusercontent.com/22037960/79029994-35bbce00-7b97-11ea-8564-feaf49e416e7.jpg)
![Burszui_111](https://user-images.githubusercontent.com/22037960/79029997-36546480-7b97-11ea-9137-9fcd31ae0ae3.jpg)

**Comment by Kaelang** [comment]
As this event has concluded, I'm going to remove this for the time being. If this persists if the event comes around again, please re-open the issue.
