### ISSUE TITLE
Bug that insta kills you upon clicking a wyvren egg

### ISSUE THREAD

**Issue by Cote82** [WarEmu/WarBugs#16354]
So this bug wasn't a matriarch spawn it was from killing the egg. normally you do 30,000 damage to the egg however this bug caused me to do 30,000 damage to myself instantly killing me. I attached a photo of my combat log to show what happened.

![Malignaant_007](https://user-images.githubusercontent.com/63259956/79054810-eb6d3800-7bfc-11ea-8ff9-a16772720548.jpg)

**Comment by Garnerr** [comment]
You are in "dangerous territory" which kills you after being there for a little bit.

**Comment by Lheana** [comment]
Where you out of common map, i.e. in dangerous territory?

**Comment by Garnerr** [comment]
Yes, you can see it on his minimap.

**Comment by Lheana** [comment]
Right then ticket closed.
