### ISSUE TITLE
/reload is OP atm

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#16355]
upon spamming /reload, things got weirder and weirder. first I got over 3mil XP(when im already 40)
, then tons of RR... then this.... 
![Nooblit_042](https://user-images.githubusercontent.com/44329952/79055607-01d2be00-7c14-11ea-9642-c03522721308.jpg)

**Comment by Xicoz** [comment]
didn't mean to block my name btw, im Nooblit in game blackorc

**Comment by Kaelang** [comment]
Pretty confident that this is only on your side, i.e. if you went to purchase anything with that gold, the game would tell you you can't afford it. Similarly with your renown points - can you spend unlimited renown points at the trainer?

**Comment by Kaelang** [comment]
No further information provided. Closed.
