### ISSUE TITLE
Eastern Wyvern Matriarch

### ISSUE THREAD

**Issue by Cote82** [WarEmu/WarBugs#16353]
I have killed the Eastern Wyvern Matriarch twice, even received loot from both kills, but neither kill gave credit for the live event.

**Comment by Desitri** [comment]
I have the same issue, GM stated they would not help and to post here instead

**Comment by Cote82** [comment]
Yeah preventing me from finishing the event and getting the event item which really sucks, but oh well I guess.

**Comment by GhostOntro** [comment]
Same here. Needs to be fixed soon. The event is ending.

**Comment by Kaelang** [comment]
This event has now ended and this requirement was removed shortly beforehand.
