### ISSUE TITLE
The Bloody Maul

### ISSUE THREAD

**Issue by wrymn** [WarEmu/WarBugs#16351]
**Expected behavior and actual behavior:**
Click on the stone in that cave, NPC should spawn. NPC can be killed and quest completed.

**Steps to reproduce the problem:**
Click on the stone in that cave, NPC should spawn. NPC spawns half way into a terrain and is unkillable, but is the objective of this quest.

**Testing Screenshots/Videos/Evidences (always needed):**
no screenshot needed

**Comment by Lheana** [comment]
Click on it again, sooner or later you'll be able to attack him.

**Comment by wrymn** [comment]
> Click on it again, sooner or later you'll be able to attack him.

I cannot click on it again. I have also tried to relog, you cannot click on it because clicking on it the first time made that objective marked as complete.

**Comment by Lheana** [comment]
Abandon the quest and retake it
