### ISSUE TITLE
Ellyrion Chapter 9 PQ 'The Well Springs' Stage II

### ISSUE THREAD

**Issue by KySaber** [WarEmu/WarBugs#16358]
G'day,

As shown in the video below, on stage 2 you can just spam click one item to rush the third stage.
https://youtu.be/zDfI1n2uGtc

Cheers!
Tesila/Alithinar

**Comment by Kaelang** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/14893 as reports are related to spammable objects.
