### ISSUE TITLE
Item missing [Titan's Warhammer of Sanctity]

### ISSUE THREAD

**Issue by BenzZeb** [WarEmu/WarBugs#1635]
Hi,
I Buy Titan's Warhammer of Sanctity with 210 sc token.
This item is not in my bag,and i have no token now,i don't know what happened...
Can you send me another please ?

Benzz/IronBreaker/LvL 26/ Rr 33/ Guild CCM

It's GM Temperon who say me to post here for my request.

regards

**Comment by Evildoor** [comment]
Unfortunately, i was informed that dev policy is "No refunds" for now.
