### ISSUE TITLE
PQ Rain of Fire in Reikland Stage IV bugged

### ISSUE THREAD

**Issue by TKOEF1112** [WarEmu/WarBugs#16350]
When I hit Stage IV, I have to burn 3 tents, but when I right click a tent and see it visually burn down, I don't get credit for it and thus cannot complete that PQ.

**Comment by Lheana** [comment]
Have you tried attacking it?

**Comment by TKOEF1112** [comment]
> Have you tried attacking it?

It's not attackable.  You have to right click burn it.

**Comment by Lheana** [comment]
That's because you have to use the Torches to make burn the tents.
