### ISSUE TITLE
cheating people report (Harrwin)

### ISSUE THREAD

**Issue by dihanin** [WarEmu/WarBugs#16357]
destroy marader , name Harrwin is cheating confirmed. 
I don't know how he did. but he HP recover abnormal (level 30) 
there is impossible like that.

**Comment by dihanin** [comment]
Renown rank 86 tank and warlord gears, full defensive specify with both hands defensive scenario weapon(83.1 dps). drinks 1832+2748 healing potion and 125+183 AP potion.
and I am sure I attacked over 15k ~20k dmg on him.
(is that meaning lvl 30 mara HP 3 times? I guess) 
that lvl 30 mara (Harrwin)still can recover HP and kill me. 
If this results GM accepted it . I have nothing to say, and there's no necessary to reply for this issue.
I believe some ppl  do some tricks. but this guy is too absurd and  unacceptable.

**Comment by Kaelang** [comment]
The bug tracker isn't for reporting players bud. Contact a GM via PM on the Forums or through Discord if you want to send a report. You'll need evidence prepared if you would like them to investigate.

**Comment by Gunlingers** [comment]
Mara has a tactic ''Deady clutch'', making his 5 sec CD 10 sec duration heal debuff ''tainted claw''
to prevent you from getting 50% heal of any source. And stealing 50% of ALL heal you get.
Every point of self heal/reg Health Pot you use or Heal from skill you get is Cut in half and shared betwean you and him.

''Renown rank 86 tank and warlord gears'' No Clue of what enemy Classes can do, but running around with High end Gear and X2 pumped up RR.

**Comment by dihanin** [comment]
Apparently you are agree a lvl 30 mara can kill a 86 tank (14k HP include
postions).
And you are clearly to let me understand it's a "new rule", because since I
play from 2009~2020 never happen before.
and no matter how I detailed to explain what happened.

Thank you for reply.
and There's no more any question or any issue in the future.



Gunlingers <notifications@github.com> 於 2020年4月12日 週日 下午8:29寫道：

**Comment by Lheana** [comment]
Like Kaelang said, the Bugtracker is made for **game issues**, it is not made to report player. GameMasters are here for that.
