### ISSUE TITLE
WP tactic

### ISSUE THREAD

**Issue by rycko2b** [WarEmu/WarBugs#16360]
Hello, 

I noticed that the tactic "Fanaticism" on Warrior Priest is bugged, it doesn't give the 10% parry/disrupt bonus at all. Is it normal?
and this character is taking heavy damage from everything (t2-t3 scenarios so you know), never seen such damages taken , even on my BW or AM, which wear clothes. 
So , or my character is bugged, or destros still overpowered, both are annoying to play with.

Thanks
Issues should be unique. Check if someone else reported
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Rydiak** [comment]
Could you provide any evidence beyond anecdotal balancing complaints?

Try un-slotting Fanaticism, target your character with no other character targeted, and type .getstats in chat. See what your Parry is. Then slot Fanaticism and repeat the above, seeing if your Parry changed.

**Comment by rycko2b** [comment]
Il already dis the change, unslot, remastered, logout/login... Nothing changes, Fanaticism still doesn't affect the stats.Le 12 avr. 2020 19:15, Rydiak <notifications@github.com> a écrit :
Could you provide any evidence beyond anecdotal balancing complaints?
Try un-slotting Fanaticism, target your character with no other character targeted, and type .getstats in chat. See what your Parry is. Then slot Fanaticism and repeat the above, seeing if your Parry changed.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

Le 12 avr. 2020 19:15, Rydiak <notifications@github.com> a écrit :
Could you provide any evidence beyond anecdotal balancing complaints?
Try un-slotting Fanaticism, target your character with no other character targeted, and type .getstats in chat. See what your Parry is. Then slot Fanaticism and repeat the above, seeing if your Parry changed.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

Le 12 avr. 2020 19:15, Rydiak <notifications@github.com> a écrit :
Could you provide any evidence beyond anecdotal balancing complaints?
Try un-slotting Fanaticism, target your character with no other character targeted, and type .getstats in chat. See what your Parry is. Then slot Fanaticism and repeat the above, seeing if your Parry changed.

**Comment by Rydiak** [comment]
Can you post screenshots of .getstats, with and without Fanaticism slotted?

**Comment by rycko2b** [comment]
I can't right nos, will do asapLe 12 avr. 2020 20:00, Rydiak <notifications@github.com> a écrit :
Can you post screenshots of .getstats, with and without Fanaticism slotted?

**Comment by rycko2b** [comment]
Here they are.

The critical bonus ppears, but not the dodge/disrupt, which causes almost instadeath in Sc/rvr because it’s more like i’m around 0% dodge/disrupt/parry

Eric PETITET
Village
20212 ALANDU

De : Rydiak<mailto:notifications@github.com>
Envoyé le :dimanche 12 avril 2020 20:00
À : WarEmu/WarBugs<mailto:WarBugs@noreply.github.com>
Cc : rycko2b<mailto:bozincu@hotmail.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [WarEmu/WarBugs] WP tactic (#16360)


Can you post screenshots of .getstats, with and without Fanaticism slotted?

**Comment by Rydiak** [comment]
You didn't link any photos to github, but you might also want to re-read what avoidance Fanaticism buffs.

**Comment by rycko2b** [comment]
![Boombastick_002](https://user-images.githubusercontent.com/26632001/79093894-fdaeb980-7d55-11ea-9dbf-af8c0013fab0.jpg)
![Boombastick_003](https://user-images.githubusercontent.com/26632001/79093898-00a9aa00-7d56-11ea-878d-82d67582677e.jpg)

**Comment by Rydiak** [comment]
I can clearly see Fanaticism buffing Parry on your stat doll.  You need to read the tactic again.

**Comment by grunbag** [comment]
This tactic increase parry , not dodge disrupt . Your stats are Correctly increased . 
![16CA720F-3D98-4431-AB49-99FA6F707463](https://user-images.githubusercontent.com/24207191/79095878-e4a90700-7d5b-11ea-98bc-02c5fb28bace.jpeg)
