### ISSUE TITLE
Raven Host Vanguard Bug

### ISSUE THREAD

**Issue by DolemRedrik** [WarEmu/WarBugs#16361]
Hello.
The issue is with the first PQ on the Empire side ¨Raven Host Vanguard¨
![Dolem_001](https://user-images.githubusercontent.com/63555662/79075497-d8b83900-7cb8-11ea-8c5d-940f010f496d.jpg)
As you can see, the mobs needed for the first stage are missing, so you cant do it.

**Comment by Lheana** [comment]
Just checked, the NPCs are there. Please reopen if the issue happens again.
