### ISSUE TITLE
Wyvern Egg hunt error

### ISSUE THREAD

**Issue by GreeneGiant** [WarEmu/WarBugs#16364]
Hello, 
I was given an error when trying to interact with an egg I found. My avatar became stuck in the searching stance and this error appeared in the chat window:

NullReferenceException was thrown for HandleEvent

Thanks!

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
As this event has concluded, I'm going to remove this for the time being. If this persists if the event comes around again, please re-open the issue.
