### ISSUE TITLE
Purple seed disappear on crash server 13/04 12h45

### ISSUE THREAD

**Issue by Darkavenger-Fureur** [WarEmu/WarBugs#16366]
Hello,

During the 12:45 server crash on 04/13/2020 my purple seeds disappeared. I was cultivating when the server crashed.
When I reconnected my seeds disappeared, I no longer have them.
Can you give them back to me please?

Golden Serissa Seed
Nightshade Seed
and because you are the best give the Black Hellebore Seed :)

Character: Darkavengers

Best regards and thanks

**Comment by Lheana** [comment]
There will be no recovery. Sadly these are the kind of things that happen when the server crashes.
