### ISSUE TITLE
No invader or vanquisher on successful CW lock as Destro.

### ISSUE THREAD

**Issue by iiiLollo** [WarEmu/WarBugs#16362]
In the Chaos Wastes Defense I was part of on the defending force and locked at 19.08 CEST.
I was in a warband,  we roamed for more than 2 hours, killed quite some people and we participated in taking the keep.

Killing the lord dead paid us renown,

After the look only some of us rolled for bags, and and the listed people dind't receive any vanq/conq on lock nor the invader token.

Characters:

- Bungalove (white bag)
- Sesshumaru
- Jacobb 
- Gahric
- Zbrako (white bag)
- Upa (green bag)
- Tozush (green bag)

Keep for order: Zimmeron's Hold
Keep for destro: Charon's keep

**Comment by Kaelang** [comment]
Similar to https://github.com/WarEmu/WarBugs/issues/15945.
