### ISSUE TITLE
[City] Unusually high amount of Royal crests dropping after stage 1

### ISSUE THREAD

**Issue by CrimsonFenris** [WarEmu/WarBugs#16368]
Right after finishing city stage 1 (**losing today in Order side - Instance n°12 - around 13:54 GMT+1**), I dropped many royal crest (see screenshots).

I'll count them (retrieving my normal loot 3 for all stage lost, + 1 white, 1 green and 1 gold (only white bag used) and will not spend them in the meanwhile (will be obvious cheating).

**EDIT : Appears to be 176 tokens (instead of 3), wich means 173 too much.**

Looks like it happened ppl crashed (not my case), and until the last couple seconds of first stage, I was igniting a tent (counter was about 3s left for stage, and my action finished about hald a second before end of stage). Stage counter went from 0s to 2s (maybe increasing from ignition action), and roll didnt appeared right after. After couple seconds, stage 1 finished and we can see our rolls (gone from 1st to 10th, no screenshot).
![Fenryon_031](https://user-images.githubusercontent.com/40425011/79120044-22c11d80-7d92-11ea-810e-ad8f52a0b23c.jpg)
![Fenryon_030](https://user-images.githubusercontent.com/40425011/79120046-23f24a80-7d92-11ea-82e3-8f1e40d20a6b.jpg)
![Fenryon_033](https://user-images.githubusercontent.com/40425011/79120048-25bc0e00-7d92-11ea-86c4-67849456354a.jpg)

**Comment by Kaelang** [comment]
I believe this was hot-fixed during this siege.

**Comment by dalen** [comment]
this has been fixed
