### ISSUE TITLE
Melee SH counts as a ranged DPS for purposes of selecting a city champion

### ISSUE THREAD

**Issue by Rydiak** [WarEmu/WarBugs#16373]
This city has a champion Choppa and a champion melee SH, meaning the melee SH was treated as a ranged DPS when champion selection was made.

![Rydiak_020](https://user-images.githubusercontent.com/15963532/79137929-4035bd80-7d79-11ea-9d76-e63397f1bfc8.jpg)
![Rydiak_022](https://user-images.githubusercontent.com/15963532/79137935-41ff8100-7d79-11ea-8a01-754db9b8d26f.jpg)

**Comment by Kaelang** [comment]
As of 22/04/2020 this should now be fixed.

- Melee Squig Herders & Assault Shadow warriors now counts as MDPS for ranked solo and hero selection in cities.

Please re-open this if you are still experiencing this.
