### ISSUE TITLE
Camera randomly stuck

### ISSUE THREAD

**Issue by Snifflebutts** [WarEmu/WarBugs#16379]
**Expected behavior and actual behavior:**
Expected: Camera to follow the character
Actual: Randomly get stuck while the character still doing their things

**Steps to reproduce the problem:**
No clue, 2nd time this happened and both time didnt have anything in common

**Testing Screenshots/Videos/Evidences (always needed):**

https://www.youtube.com/watch?v=rZR2_AMyE68&feature=youtu.be

**Comment by Kaelang** [comment]
Duplicate of https://github.com/WarEmu/WarBugs/issues/15340.
