### ISSUE TITLE
[White Lion] bugs i've found so far

### ISSUE THREAD

**Issue by thullonse** [WarEmu/WarBugs#1637]
1. double tapping the Summon pet button will re-summon the Lion with 100% hp
2. using trained to Hunt / to Kill followed by trained to Threaten wont override  the pet abilitys, instead you will get 3 abilitys by train to Hund / to Kill which you can use manually and in the background the Lion can still use the abilitys of trained to Threaten automatically
3. abilitys used by the Lion dont have a GCD, they can be activated at the exact same time
4. Natures Bond will keep you in combat(?) so you continue to build up morale
5. if you use Pounce on an enemy who passes through a keep door you will land inside the keep aswell
6. pet abilitys set on auto use have a delay of 5-20 seconds in between each ability

**Comment by milosxe** [comment]
Can you please make a separate ticket for each issue?

**Comment by thullonse** [comment]
done :)
