### ISSUE TITLE
Cant log into a character the selection screen

### ISSUE THREAD

**Issue by Aindolur** [WarEmu/WarBugs#16378]
**Expected behavior and actual behavior:**
When I finished a city tonight I was trying to leave the instance and it wouldnt port me out.
I was unable to chat in either guild or advice. I closed the client and launcher to restart the game and I am unable to log into that character. I will just get stuck at the character selection screen and when i hit play it does nothing. I was able to log into an alt character. Please help.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![screenshot_000](https://user-images.githubusercontent.com/63126956/79192292-af48fb80-7de5-11ea-885e-07c4d83e98ed.jpg)

**Comment by Kaelang** [comment]
Are you still unable to login to the game?

**Comment by Aindolur** [comment]
Appears that my character has been reset. I am able to get back into the game.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
