### ISSUE TITLE
Alternative appearance doesn't apply from items in bank.

### ISSUE THREAD

**Issue by brbzl** [WarEmu/WarBugs#16385]
**Expected behavior and actual behavior:**
Expected to work the same way as it works with the items in backpack. 
Other items work normal way. (Didn't check all though).
Appearance didn't apply, only next text in chat.
(Also with a back appearance on 2nd screen.)

**Steps to reproduce the problem:**
Open your bank storage and try to apply item's appearance from item which is stored in bank.
![bug1](https://user-images.githubusercontent.com/63316662/79251738-3b602f00-7e89-11ea-9ffd-88b47eae7d5d.png)
![bug2](https://user-images.githubusercontent.com/63316662/79251743-3c915c00-7e89-11ea-9a46-f8ab4e730870.jpg)

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
I see no issue here, you have to have the item in your inventory to apply the appearance.
