### ISSUE TITLE
Lost Rally Master in Ellyrion

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#16388]
**Expected behavior and actual behavior:**

There's a KOBS level 17 champion in Ellyrion (Captain Becker) on Destro side PVE. Not sure if he's quest related, but he has Rally Master as his title as if he should be in a chapter camp.

**Steps to reproduce the problem:**

Remove the title if he's part of a quest line, otherwise delete

**Testing Screenshots/Videos/Evidences (always needed):**

![Volyar_145](https://user-images.githubusercontent.com/22262165/79265240-b9263980-7e8d-11ea-8c25-d752d4b4038a.jpg)
![Volyar_143](https://user-images.githubusercontent.com/22262165/79265250-bcb9c080-7e8d-11ea-8840-8323f0cbcd1c.jpg)

**Comment by Kaelang** [comment]
Should be fixed in 06/05/20 patch - please re-open if issues persist.
