### ISSUE TITLE
Blasting Cart Capping

### ISSUE THREAD

**Issue by raynerfritz** [WarEmu/WarBugs#16382]
**Expected behavior and actual behavior:**
When you cap at blasting cart at Thunder Valley SC right beside the flag you suddenly fall from the ground. I saw a rectangle field of lava i receive lava damage and i died, I panned my view i can see other characters when i look up. I forgot to screen cap it because i immediately ressed.

**Steps to reproduce the problem:**
i did not try it again because i need to log out.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Duplicate of https://github.com/WarEmu/WarBugs/issues/13715.
