### ISSUE TITLE
Ram die too fast

### ISSUE THREAD

**Issue by jonhyw** [WarEmu/WarBugs#16397]
Evening, 

We at Praag, and ram looks so squishy. Die in seconds, i think somenhing is wrong. Please, can you verify if something is wrong? Thank you so much.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
You'd need more information. Such as Ram %, population in Praag, what's happening when health is dropping, video clip if possible etc.

**Comment by Kaelang** [comment]
Closed. No further information provided.
