### ISSUE TITLE
No BB BE in legendary locales.

### ISSUE THREAD

**Issue by monster1305** [WarEmu/WarBugs#16398]
Character: Keyyas

Issue: Even tho had cleared BB BE several times, can't see them in legendary locales and can't track my influence progression. This has been like this forever.
![Keyyas_068](https://user-images.githubusercontent.com/48641801/79389875-64f78400-7f77-11ea-953e-35f0bf5f304e.jpg)

**Comment by Kaelang** [comment]
This sounds similar to a report here: https://github.com/WarEmu/WarBugs/issues/16300#issuecomment-618940099

This was fixed by reinstalling the client. Could you give this a go please?

**Comment by monster1305** [comment]
Solved by reinstalling the client. Thanks.

24 Nis 2020 Cum 18:02 tarihinde Kaelang <notifications@github.com> şunu
yazdı:

**Comment by Kaelang** [comment]
No worries.

Closed.
