### ISSUE TITLE
Cannot log in after city / black screen

### ISSUE THREAD

**Issue by awmc82** [WarEmu/WarBugs#16390]
After city ended last night (4/13 NA) my character Raisingkhaines was able to move around but no actions could be taken (cast spells, type, interact with objects). I wait for about 10 minutes and then decided to close the application. I tried to log in after and but I got a black screen. I closed application again and tried to log on an alt which worked just fine. A friend of mine had the same issue (just didn't log out) and a GM was able to port him out. I messaged the same GM and was told to wait till after the city is over. Once over I could log back in and all should be good. Once city was over I tried and same thing. 
.
As you can see my character is still in "The Inevitable City"
![screenshot_000](https://user-images.githubusercontent.com/31575199/79273457-9fbec680-7e68-11ea-8eaf-ab0096a3e5cf.jpg)

I clicked play and after about 10 seconds of waiting I get this screen
![screenshot_002](https://user-images.githubusercontent.com/31575199/79273541-c7ae2a00-7e68-11ea-8700-a9375f22721f.jpg)

Any and all help would be great to fix this as I know others all also having this issue. Thanks in advance!

**Comment by Kaelang** [comment]
Please can you confirm if you are now able to login?

**Comment by awmc82** [comment]
Yes, after the reset I was able to log into my character again. Thanks.
