### ISSUE TITLE
[White Lion] lion abilitys have no gcd

### ISSUE THREAD

**Issue by thullonse** [WarEmu/WarBugs#1640]
abilitys used by the Lion dont have a GCD, they can be activated at the exact same time

**Comment by ozarmidrashim** [comment]
Should be impossible - lions cast through the same system players do, and the cast will be blocked if the GCD is running

**Comment by thullonse** [comment]
easy to reproduce: bind the lions abilitys to 1 2 3 and smash the keys as fast as possible. if you are fast enough the abilitys are all on the same cooldown and debuffs are shown on the enemy aswell
