### ISSUE TITLE
Warlord Rend Ring [Marauder] No Resistances

### ISSUE THREAD

**Issue by Foofmonger** [WarEmu/WarBugs#16406]
Hello, 

I saw a bug report that said the Slayer Warlord ring has no resistances. Much like that issue, I've noticed the Marauder's "Warlord Rend Ring" currently has no resistances.

Not sure if display issue in tooltip or actual functionality issue, as I don't actually have the ring.

Thank you

**Comment by SilverWF** [comment]
Same for WL's and, pretty sure, any other Warlord ring

**Comment by Kaelang** [comment]
As of 22/04/2020 this should now be fixed. 

Please re-open this issue if you are still experiencing problems with the item. If you aren't seeing the stats visibly update, you may need to clear your game cache. 

Thanks.
