### ISSUE TITLE
Beastlord: Bramble Witch Bugged

### ISSUE THREAD

**Issue by chook06** [WarEmu/WarBugs#16404]
After several checks, I note that since the last update the boss Bramble witch does not repop any more. no body on the ground.

**Comment by RoR-Zomega** [comment]
The body will vanish when a timer on it expires, but then it still doesn't respawn for a random period after this (I've been told it's random between 0 minutes to 30 minutes or 0 minutes to 60 minutes; not sure which is correct). You might've been visiting it during this period.

**Comment by Kaelang** [comment]
I've seen multiple people in /5 forming groups for Bramble Witch.

**Comment by emailkook** [comment]
We just did her few days ago. So is popping

**Comment by Kaelang** [comment]
Closing.
