### ISSUE TITLE
You can not start the game, offers to rename.

### ISSUE THREAD

**Issue by Fokus88** [WarEmu/WarBugs#16403]
When you click the "Play" button, a message box is displayed "Rename Your character has a duplicate name. Please rename your character."
![screenshot_006](https://user-images.githubusercontent.com/63793238/79458335-556d4f00-7ffa-11ea-89bf-90a52bf43e73.jpg)

Re-entering the name does not help.
![screenshot_011](https://user-images.githubusercontent.com/63793238/79458709-de848600-7ffa-11ea-88ae-37db6c7fb5aa.jpg)

![1](https://user-images.githubusercontent.com/63793238/79458793-02e06280-7ffb-11ea-89c1-146ea7da2b8d.PNG)

**Comment by Kaelang** [comment]
Likely force renamed from staff.

**Comment by Fokus88** [comment]
Can a game be deleted?

**Comment by Kaelang** [comment]
Unsure what you mean by that?

**Comment by Fokus88** [comment]
There is no way to play for RP, so you need to delete the game and forget about ROR.

**Comment by MaxHayman** [comment]
The character was flagged for a rename by a game master. You will need to chose a new name for your character.

**Comment by Fokus88** [comment]
Why was this done?

**Comment by Lheana** [comment]
It was done because your name is against our ToS.
Btw, one more comment on this ticket that is **not** a game issue, and it will be locked.

**Comment by Fokus88** [comment]
Unreasonable blocking of the character and the subsequent threat, as is true.
As always, GMs play for destruction.
Thank you for not being able to solve the simplest questions.

**Comment by Lheana** [comment]
You character is not blocked, you just need to rename him cause it seems like you did not read our ToS.
As promised, this ticket is now locked.
