### ISSUE TITLE
Reservation timer for Fortress not long enough

### ISSUE THREAD

**Issue by Seluzz** [WarEmu/WarBugs#16408]
I moved to KV after we lost keep in DW.
Then i got a spot for Fortress, and ported from KV to CW by using book. 
Ported to Altdorf and ran south. And when i entered Shining, 2 seconds from door or so, my reservation dropped...
So it seems like it cant be done in 5 mins due to load times and such.

**Comment by RoR-Zomega** [comment]
Not a bug. Try the suggesgtions forums: https://www.returnofreckoning.com/forum/viewforum.php?f=15

**Comment by Kaelang** [comment]
See above link - this feature looks to be working as intended.
