### ISSUE TITLE
Error calculating contribution after zone lock

### ISSUE THREAD

**Issue by xanniez** [WarEmu/WarBugs#16409]
**Expected behavior and actual behavior:**
Hello, my character name is xannie. Today I was defending Eataine for few hours with my party. Eventually when I died and our Lord in keep was about to get killed, I used a guild scroll and went to defend Shining Way fortress. 
When Eataine locked (around 11:30am Europe Time) I got teleported out from Shining Way, while all my party got reservation. 
I also got a message saying the following:
 "Something has gone wrong when attempting to add contribution to you, please report on the bugtracker the circumstances of you entering the fort."
"More DEBUG information for the bugtracker"
"Currentfort: Shining Way"

I didn't get renown either , unlike all my party.

Also, despite being in Shining Way when the zone closed (so one of the first in the queue), I didn't get reservation at any moment.

Could you look into it please?

Please let me know if you need further information.

Kind regards
![IMG_2583](https://user-images.githubusercontent.com/63848418/79557679-3f679900-80a3-11ea-9a4c-989a74c7aeac.jpg)

**Comment by Kaelang** [comment]
You didn't receive a reservation for the fort, and managed to bug yourself into the instance by walking through the zoneline (sometimes the game will allow you access regardless of a pop-up prompt). This essentially leads you to be in the fort physically, but the system doesn't acknowledge you as a valid participant and therefore reduces all your contribution down to 0. 

If you don't see the reservation pop up, don't risk playing the fort as you won't get any rewards without a res.

**Comment by xanniez** [comment]
Hello, 
I apologize, probably didn't explain myself really good.
The issue was on counting the contribution from Eataine. By the time Eataine locked, I was in Shining Way already. All my party (we were together all the time) got the pop up saying they got reservation and I got kicked out to the border instead, getting the message that there was an error adding my contribution (from Eataine).
I couldn't get into the fortress after it was "active", so I didn't play in it.

If you say that I should stay in a zone until it completely locks, and then try to move to the fortress when it gets opened, I will do so, but going there before the previous zone is locked (when is about to) is a common behaviour and I didn't see anyone getting the error I got today, so I don't think it was expected.

Again, thank you so much for the reply.


Kind regards

**Comment by Kaelang** [comment]
So, my currently hypothesis is as follows:

Someone in your warband killed a player in Shining Way (likely a roaming / escaping Order player) which gave you the debug error. For example, your warband is reserved for the fort, and you've managed to bug your way into the instance. The warband killed a member which gave contribution towards Shining Way as it opened, however as you haven't been reserved, you didn't receive the contribution. 

Would be a coincidence, but it makes sense.

If you was ported out of the zone, you wasn't reserved, which would refer back to my original reply as to how you managed to get into the zone.

Could this have been the case?

**Comment by xanniez** [comment]
I was able to reproduce the issue doing exactly the same than the first time.
1) I died in Eataine Order Keep
2) I respawned, and used a Guild Scroll.
3) I went to Shining Way via Altdorf>Reikwald, and went into Shining way while Eataine was still not locked (Destro was killing Keep Lord)
4) As soon as Eataine locked and Shining Way opened, I got the same error message in chat and got kicked out from the fortress (I was the only one in party again with this issue, and we didn't kill any destro while inside). I also, again, didn't receive any medallion or renown for defending Eataine.
![Xannie_000](https://user-images.githubusercontent.com/63848418/79644147-5099ce00-81a7-11ea-83e7-35dff986839d.jpg)

**Comment by xanniez** [comment]
Hello, don't want to spam, just giving extra info in case is useful.
Today I went straight to Shining Way before Eataine was locked. When Shining Way siege started, I got the error message again, but this time I didn't get kicked out (and same happened to another party member).
We were able to participate in the fort without contribution or reservation, when we died we were spawning inside the keep, and when it ended, I received the usual rewards (rr and crests).
Issue only seems to be when you are in Shining Way before the siege starts. It doesn't happen with other fortresses.

**Comment by xanniez** [comment]
![Xannie_002](https://user-images.githubusercontent.com/63848418/79792572-6d710580-834f-11ea-8ec4-a0feb9b614b7.jpg)
![Xannie_004](https://user-images.githubusercontent.com/63848418/79792586-6fd35f80-834f-11ea-8619-9fdbe28e9d0a.jpg)

**Comment by FCT-ROR** [comment]
This is still the same issue as all the references.
I think it has to do that low levels get in the fort while they shouldnt.
Hope this helps.

**Comment by SetchDreskar** [comment]
I am just gonna bump this then, though in my case I had a reservation, got the pop up for it and everything, died, was ported out of Reikwald when I rezzed and was then given the error message when I ran all the way from the pve area.

Once again, I had a reservation.

So it seems even if you go in while having a reservation you can be derped by the system.

**Comment by Kaelang** [comment]
This should have been fixed as of 27/05/20. Please re-open if issue persists.
