### ISSUE TITLE
Did not receive Massive Loot Bag in IC scenario for stage 3

### ISSUE THREAD

**Issue by mijalwe** [WarEmu/WarBugs#16400]
**Expected behavior and actual behavior:**
Expected to receive bag in mail.

Did not receive bag in mail

**Steps to reproduce the problem:**
Unknown

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Try to send a mail to your main from an alt character - if not, bags are usually received after a reset.

**Comment by Kaelang** [comment]
Did you receive your bag after the latest reset?

**Comment by mijalwe** [comment]
I wasn't aware there was one, so I guess not.  Is there a way to check for
the future?

**Comment by Kaelang** [comment]
If you win a bag during the IC City Siege, Stage 1-3, you can pick them up from the chest or they will come to your mailbox. Your initial report stated you was expecting a bag, but didn't receive one.

**Comment by mijalwe** [comment]
Correct.  I was asking about a way to know when the server resets.  Nothing
has come yet from mailing from an alt toon.

**Comment by Kaelang** [comment]
Ah - makes sense. Following the next patch release, please let me know if the bag arrives through your mail.

**Comment by mijalwe** [comment]
Okay, thanks

**Comment by mijalwe** [comment]
I tried again after this last update and sent another mail from an alt.
Bag has not arrived.

**Comment by Kaelang** [comment]
Did you actually win a bag in the last stage? Only 12 people get bags.

**Comment by mijalwe** [comment]
Yeah, pretty sure it said I placed first.  I think I posted an approximate
time the stage ended in the initial appeal if you guys can pull up a log.

**Comment by Kaelang** [comment]
Ok cheers - merging with a similar report and closing this one up.

As a side note - we don't get involved with recoveries of lost items etc. 

https://github.com/WarEmu/WarBugs/issues/16323

**Comment by mijalwe** [comment]
Really, okay.  If there's nothing to be done about not recieving rewards,
you could've said that right away 10 days ago.

**Comment by Lheana** [comment]
I advice you not to talk to team members like that.
You also could have had a look to all the reports where people have lost items, you would have seen that we don't do recoveries.
