### ISSUE TITLE
SW stance bug

### ISSUE THREAD

**Issue by Dragothurch** [WarEmu/WarBugs#16401]
Hi!
SW stance totaly bugged. If i go in sc or use mount in sc, some skill go grey inactive status and cant use say:need stance for skill but the stance active. Sometimes mount down and the game automatical turn off stance. Sometimes change stance and after back to my main stance(melee) but not change castbar for active stance skill!
Pls check, very unplayable when under fight change stance the game and cant use my skill, thx

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Please could you provide more information about abilities used and sequencing. A video would be helpful here.

**Comment by Deazel06** [comment]
Hi guys, i noticed on one of the patch notes you attempted to fix this bug. I just want to report for me at least, this is still happening. It seems to start when joining / leaving scenarios, and at other random times. Sadly i cant even play my shadow warrior anymore its soo bad. 
I turned off all ad-dons to default settings to make sure it wasn't related but the problem Persisted.

**Comment by Kaelang** [comment]
Closed. No further information provided.  - There is a separate report that is open investigating this issue.
