### ISSUE TITLE
[Dragon's Bane] Can get into enemy's spawn 

### ISSUE THREAD

**Issue by Sciberr** [WarEmu/WarBugs#16415]
**An introduction:**

Doing a little bit of parkour along the side of the map can allow you to move all the way around giving you access into the enemy's spawn.

**Details:**

Can get into enemy's spawn by going outside of the intended area.

**Evidence:**

https://youtu.be/M3_UV2TdYoY

**Additional Information:**

N/A

**How to reproduce the bug:**

Jump out of the intended area and run all the way around to the enemy WC then jump in and proceed the torture.

**Comment by dalen** [comment]
I just added a few guards that will prevent spawn camping at least. Will add some invisible walls later

**Comment by MaxHayman** [comment]
Patched in today
