### ISSUE TITLE
[White Lion] Natures Bond morale buildup

### ISSUE THREAD

**Issue by thullonse** [WarEmu/WarBugs#1641]
Natures Bond will keep you in combat(?) so you continue to build up morale

**Comment by ozarmidrashim** [comment]
Confirmation request regarding proper interaction with respect to combat state when healing your own pet

**Comment by thullonse** [comment]
just tested it again. even if you are out of combat and just use Natures Bond you will immediately gain morale as long as the buff stays active

**Comment by milosxe** [comment]
https://www.youtube.com/watch?v=xSAVm3vmCt0

You can see the morale bar filling up. It's the same issue that we had before (and still maybe) when heals in general gave you morale without putting you in combat.

**Comment by thullonse** [comment]
thanks for the video thats exactly what i meant

**Comment by ozarmidrashim** [comment]
The question wasn't whether the issue existed - it was about how healing a pet which is in combat should handle with respect to putting yourself in combat (which is the prerequisite for morale build)
