### ISSUE TITLE
Solo Ranked Scenarios

### ISSUE THREAD

**Issue by Chudas** [WarEmu/WarBugs#16412]
After new patch, solo ranked scanarios are making instances for one or two people, as piture below shows. Typing .ranked or .rankedscstatus into chat, shows that 10-13 instances are active, but when some instance finishes only one or two people again appear in queue. 

 https://prnt.sc/s19b09

**Comment by Kaelang** [comment]
I think the scenario has been removed from the queue. Can you confirm if you can still see, and queue for the ranked SC?

**Comment by Chudas** [comment]
Yes, i see. It is no longer there.

**Comment by dalen** [comment]
The actual bug is fixed. But we disabled the scenarios for now until next time we do a hotfix.
