### ISSUE TITLE
Weekend Event Scenario buff

### ISSUE THREAD

**Issue by M0rw47h** [WarEmu/WarBugs#16411]
Weekend Event Scenario buff stays on character after finishing Dragon's Bane.

How to reproduce:
Que and finish Dragon's Bane.

![Nowy projekt (6)](https://user-images.githubusercontent.com/35219756/79565300-bb1c1280-80b0-11ea-9242-57059e73b9cb.png)

**Comment by Kaelang** [comment]
If you type /reload, does the buff get removed? And could you confirm through XP log if you are still receiving the bonus XP regardless of being in the scenario?

**Comment by dalen** [comment]
This should get fixed in the hotfix now along with a few other smaller tweaks.
