### ISSUE TITLE
Can't get trade skills in Altdorf

### ISSUE THREAD

**Issue by Thrashnar** [WarEmu/WarBugs#16414]
Hey, checked the other trade skill posts and didn't see this.

I tried getting trade skills in Altdorf and I can't seem to get one.  As you can see from my screenshots, I don't have the skill, click on the trainer, select the dialog, click accept, and then I still don't have the skill.  I have no other trade skills learned and it does this with all trade skills.

Ideas? Thanks.

![Thrashnar_000](https://user-images.githubusercontent.com/63876623/79606446-9bd8b180-80bf-11ea-95b7-6bac8791dd36.jpg)
![Thrashnar_001](https://user-images.githubusercontent.com/63876623/79606447-9c714800-80bf-11ea-9bb0-4cf8959057a3.jpg)
![Thrashnar_002](https://user-images.githubusercontent.com/63876623/79606438-9a0eee00-80bf-11ea-8be3-719d8ef9a957.jpg)
![Thrashnar_003](https://user-images.githubusercontent.com/63876623/79606441-9aa78480-80bf-11ea-96b5-8cdfd89487c3.jpg)
![Thrashnar_004](https://user-images.githubusercontent.com/63876623/79606443-9b401b00-80bf-11ea-9fd5-31ca5ce2e011.jpg)
![Thrashnar_005](https://user-images.githubusercontent.com/63876623/79606445-9bd8b180-80bf-11ea-9573-f39919fb6d38.jpg)

**Comment by Thrashnar** [comment]
I've tried this with addons on and off, doesn't work either way,  I just want to be able to scavenge things and make pots!

**Comment by Kaelang** [comment]
It's saying 'are you sure you want to unlearn your scavenging skill' as if you already have the skill. Have you tested if you're able to scavenge anything?

**Comment by Thrashnar** [comment]
> It's saying 'are you sure you want to unlearn your scavenging skill' as if you already have the skill. Have you tested if you're able to scavenge anything?

I don't have the skill.  I am unable to even select something TO scavenge it.

**Comment by Thrashnar** [comment]
Jesus....we can just delete this.  Fixed. *facepalm*

**Comment by Kaelang** [comment]
What was the fix? So I'll be able to pass the info on. You can close this issue down yourself.

**Comment by Kaelang** [comment]
Apparently the fix here was to reset the Rally Master to a different bind spot. Placing 2 week ultimatum for confirmation.

**Comment by Kaelang** [comment]
Closed. No further information provided.
