### ISSUE TITLE
Character count increase for Calendar

### ISSUE THREAD

**Issue by rameden** [WarEmu/WarBugs#16413]
Is it possible to get the character count for the calendar event description increased? Currently it sits at 99 which makes it a bit hard to provide a useful description.

**Comment by Kaelang** [comment]
More so a suggestion that a flaw in functionality - you can review the suggestions forum here: https://www.returnofreckoning.com/forum/viewforum.php?f=15

**Comment by rameden** [comment]
Ah my apologies. Wasn't sure where to post it. Thank you.
