### ISSUE TITLE
Bag missing CAPITAL

### ISSUE THREAD

**Issue by Fealle** [WarEmu/WarBugs#16418]
Following the capital of 04/17/2020, I did not receive my bag of gold by post. moreover I tried to send 3 items to a member of my guild, he did not receive it. Can you help me please ? Name of my character in game! Fealle

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
The mail will likely come after the next reset.

**Comment by Kaelang** [comment]
Did you receive the bag after the earlier reset?

**Comment by Fealle** [comment]
Hello :)
Yes it s perfect , thanks you very much .Have a good day !
    Le dimanche 19 avril 2020 à 16:31:30 UTC+2, Kaelang <notifications@github.com> a écrit :  
 
 


Did you receive the bag after the earlier reset?

**Comment by Kaelang** [comment]
Awesome, I'm going to go ahead and close this up.
