### ISSUE TITLE
[White Lion] pounce through keep doors

### ISSUE THREAD

**Issue by thullonse** [WarEmu/WarBugs#1642]
if you use Pounce on an enemy who passes through a keep door you will land inside the keep aswell

**Comment by Evildoor** [comment]
Changed the name a bit to avoid confusion with this issue and already reported/discussed elsewhere issue about jumping onto keep walls.

**Comment by ozarmidrashim** [comment]
This can't be fixed. The logical option to fix this would be to perform a serverside LOS check to the target, but keep doors are excluded from LOS at the moment.

**Comment by Skutrug** [comment]
I just experienced it, going through a postern door - all it takes is to initiate the pounce prior to the enemy player clicing on the door, and as he passes through, so does the pouncing WL.

**Comment by Evildoor** [comment]
Fix pending since 19 days ago, so i suppose that this was implemented in some patch and the ticket wasn't closed for some reason.
