### ISSUE TITLE
ROR Aegis

### ISSUE THREAD

**Issue by noobwarrior** [WarEmu/WarBugs#16425]
got the item from the last event *Eastern Wyvern*
![Relife_401](https://user-images.githubusercontent.com/53536809/79644856-e899b680-81ab-11ea-8a2a-8c0068f2cc44.jpg)
I have 30 min cooldown after using it but as soon as the time is up I can use it again my question is is that this object is infinitely usable or is it a mistake?

**Comment by Garnerr** [comment]
You can use it an unlimited amount of times.
