### ISSUE TITLE
Quest Encroaching Darkness III 

### ISSUE THREAD

**Issue by adotor-9** [WarEmu/WarBugs#16422]
After killing the Norse Sea Dogs and finding Pater Allard, I go back to the Sigmarite Acolyte but it does not give me part IV. I can't even talk to the Sigmarite Acolyte.

Hope it can be fixed,
Abrid

**Comment by Kaelang** [comment]
This was listed back in 2016 on this issue https://github.com/WarEmu/WarBugs/issues/5331. The workaround suggested was to speak with the Sigmarite Acolye. However as you've stated you have tried this, I'll tag this up as a Quest issue and keep the issue Open for the time being.

**Comment by Lheana** [comment]
You turn in the quest by interacting with Pater Allard.
