### ISSUE TITLE
Gunbad : respawn problem

### ISSUE THREAD

**Issue by Enarion** [WarEmu/WarBugs#16423]
In Gunbad at the end of the middle bridge they are 2 gobs , after killing them , when you kill the next gob the 2 on the bridge respawn . If you kill them again the others gob after the brige respawn also. It seem to be an infinite loop.

**Comment by Kaelang** [comment]
There's a few bugs listed for Gunbad over the past few days, see here: https://github.com/WarEmu/WarBugs/issues/16316 and https://github.com/WarEmu/WarBugs/issues/16317. 

This sounds like the one already listed (16316). 

They have been assigned to devs.
