### ISSUE TITLE
My quest was not counted in Gunbad

### ISSUE THREAD

**Issue by darkdesert05** [WarEmu/WarBugs#16426]
Greetings Everyone,

Nickname: Whitepunch

My problem is the way Gunbad. We're entered in gunbad 2 times and we are managed to cut left wings the last boss today. But it didn't count my quest. Can you help me with this? I don't have any videos, but I talked to gm he told me to write with you today. Thanks for your help me. 

![Lastboss left](https://user-images.githubusercontent.com/63924499/79647508-edb13280-81b8-11ea-9439-c65882e0e283.jpg)

**Comment by Kaelang** [comment]
Sounds similar to https://github.com/WarEmu/WarBugs/issues/16407 - Likely an issue with the Gunbad boss' in general. There's quite a few open issues relating to Gunbad currently.

**Comment by emailkook** [comment]
We just finished Gunbad on Order (Spelll) and got zero quest credit on EVERY middle boss. This is my first time doing Gunbad. Also everyone in group didn't get any quest credit. For one player it would've been their 3/3 attempt. That's a lot of time and effort to get zero credit and players kept from their progression towards Greater Ward. We were locked out still on top of that.

Gunbad also doesn't allow opting out of Gold Bags. We had 3 players opt out of gold even while on the boss they'd do it, still gave them all the gold bags through out the encounter.

**Comment by Kaelang** [comment]
Please could you provide the quest names with trackers not working.

**Comment by emailkook** [comment]
> Please could you provide the quest names with trackers not working.


![](https://user-images.githubusercontent.com/50253609/79701757-4a6a2700-8265-11ea-96ea-4a73e4a44c7b.jpg)

That screenshot I took has the name of the 4 quests which mention “threat”

**Comment by Tyrean1** [comment]
We have had all of the above happen to our group, just cleared all wings and last bosses didn’t update on quest tracker after kill for anyone. Also cannot opt out of gold bags as either no option to (on last boss) or just rolls and you win even if you were opted out.

**Comment by Nefarian78** [comment]
Just happened to my group. Quest credit was not given upon killing Masta Mixa. I did receive the bag in the mail from killing him though.

**Comment by Brutinho** [comment]
![Amelios_086](https://user-images.githubusercontent.com/36603560/80318575-1b116800-87d9-11ea-8822-b73601420a6d.jpg)
Did not get quest contribution from boss kills. Only took SS on the first kill (Left wing), Right and Mid wing same story.

**Comment by emailkook** [comment]
Well aware devs know about the issue and hoping they can fix the kill credits. It’s really killing the gear grind when only 1 piece drops at a time and locked out. You got many players just waiting for GB so hopefully it should be prioritized on their list.

**Comment by Hargrim** [comment]
This is resolved and will be fixed with next patch.

**Comment by Kaelang** [comment]
As of 29/04/2020 this should now be fixed. Please re-open if issues persist.
