### ISSUE TITLE
Purple loot bag from lock in dragonwake

### ISSUE THREAD

**Issue by Bochr** [WarEmu/WarBugs#16420]
Hello 
I was playing my level 40 engineer in dragonwake, defending keep. Destro took keep and locked zone.

I was so lucky to get a purple loot bag from lock.

When i open loot bag it contains the choice of 5 soldier medallions, Deadman's work gloves(Blue level 18) and Deathwhisper Bulwark, please help. I will not pick a choice in bag for now.

![Ladiesman_000](https://user-images.githubusercontent.com/63914713/79640229-b890ea00-8190-11ea-965f-cf488818a55a.jpg)

**Comment by Kaelang** [comment]
The rewards from the bags are based on your Renown rank. You're currently level 32. You would need 40/41+ for T4 gear rewards.

**Comment by Bochr** [comment]
Then why have i received genesis cloak?

lør. 18. apr. 2020 17.11 skrev Kaelang <notifications@github.com>:

**Comment by Kaelang** [comment]
I _believe_ Genesis can drop from 40 CR, but the RvR medallions / gear is from RR.

**Comment by Bochr** [comment]
And what kind o reward is a bag with level 18 and 22 gear?😀

lør. 18. apr. 2020 17.12 skrev Bo Christiansen <bochr82@gmail.com>:

**Comment by Kaelang** [comment]
Players typically aim for higher renown, than a high career rank, to make sure they remain geared throughout the process.

**Comment by Kaelang** [comment]
Please confirm post renown 40 if you're still receiving low level rewards.

**Comment by Bochr** [comment]
I Will when i get one

søn. 19. apr. 2020 16.26 skrev Kaelang <notifications@github.com>:

**Comment by Kaelang** [comment]
Closed - no further information provided.
