### ISSUE TITLE
Dragons Bane Bomb - Can carry whilst mounted on Event mounts. 

### ISSUE THREAD

**Issue by Elcour** [WarEmu/WarBugs#16427]
While you take the bomb, you can mount with the event mount(dragon), but not with a normal mount.

// Elcour

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Confirmed this has happened to me too. I can mount whilst on my Event Mount, but on any other mount I'm unable to do so.

**Comment by redhat1990** [comment]
Ya this is very verifiable, although i think redhat1990  should get the flying manticore mount for this bug report. OR both awarded.,

**Comment by MaxHayman** [comment]
Shold be fixed.
