### ISSUE TITLE
Gunbad entrance portal

### ISSUE THREAD

**Issue by torlan-hub** [WarEmu/WarBugs#16421]
NOTE: I've searched through the issues and did not find one about ths, so decided to report it.

**Expected behavior and actual behavior:**
Gunbad entrance portal on exit, should let you get out of the instance. Actually it does not.
It responds with this error, instead : "This portal's jump destination (62928168) does not exist."

**Steps to reproduce the problem:**

Went into Gunbad  of Gunbad with my Magus(name : Orunz) to complete a quest("Question Not His Great Will", had to talk to Grotuz), then checked on the merchants and was just trying to get out but could not. Do not know if this is a real bug, but I'd rather report it than not. Thanks for checking!

**Testing Screenshots/Videos/Evidences (always needed):**

![Orunz_000](https://user-images.githubusercontent.com/61749492/79642003-41ad1e80-819b-11ea-9a7e-ce367022d12a.jpg)

**Comment by grunbag** [comment]
Fixed already
