### ISSUE TITLE
Bilerot Burrow: Diseased Bellow debuff bug

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#16434]
**Expected behavior and actual behavior:**
The debuff Diseased Bellow from the Nurglings in BB says they reduce healing done by 50% (ie outgoing healing). However, they reduce both outgoing and incoming healing by 50%. 
See screenshots below for tooltip text and heal being reduced by 50% (Khaine's Invigoration normally heals for ~1200). 

**Steps to reproduce the problem:**
Go into BB and fight Nurglings, either the regular ones or the ones spawned by the Bile Lord. Notice both incoming and outgoing healing is debuffed. 

**Testing Screenshots/Videos/Evidences (always needed):**

![Forkrul_028](https://user-images.githubusercontent.com/1183293/79699042-199de800-828d-11ea-8703-790d4d4e88c1.jpg)
![Forkrul_029](https://user-images.githubusercontent.com/1183293/79699043-1b67ab80-828d-11ea-870f-dc79ab6306e2.jpg)

**Comment by Kaelang** [comment]
Are you able to get combat logs of heals received by those with the debuff, cast by someone without the debuff?

If you have a 50% **outgoing** healing debuff, and cast a heal, then the individual receiving the heal will receive 50% reduced healing. That being said, if you do not have a debuff, but the individual is still receiving 50% reduced healing, then there is either an issue with the ability, or the tooltip.

**Comment by grunbag** [comment]
I don’t see any issue : your outgoing healing is reduced by 50%, which mean you target will receive 50% less heal from you

**Comment by Vayra** [comment]
in the 1st screenshot with  I (Forkrul) don't have the debuff, only my target (Bladeh) does.

**Comment by Vayra** [comment]
After some more testing it seems there is no outgoing component to the debuff, only incoming. So it's more a case of unclear tooltip, should probably specify the type of debuff more clearly.

**Comment by grunbag** [comment]
fixed with next patch

**Comment by Kaelang** [comment]
Fixed as of 13/05/2020 patch. Please re-open if issue persists.
