### ISSUE TITLE
Bane sheild and tactic

### ISSUE THREAD

**Issue by Carcharadon** [WarEmu/WarBugs#16433]
Bane sheild and its tactic do not seem to be doing damage correct, with the tactic slotted group mates show the buff but do not seem to be proccing damage to the attackers , the Maw Ranked is where this is happening 
-->

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Are you able to post combat logs / screenshots etc? Is this only happening in the Maw (Ranked Solo) or other scenarios too?

**Comment by Carcharadon** [comment]
![Carcharadon_005](https://user-images.githubusercontent.com/55959616/79700814-3242d980-825e-11ea-91d6-3f3ab5b7296c.jpg)
![Carcharadon_007](https://user-images.githubusercontent.com/55959616/79700819-353dca00-825e-11ea-8d14-7e03baf282f7.jpg)
![ww](https://user-images.githubusercontent.com/55959616/79700820-3838ba80-825e-11ea-855e-e000c5099e08.jpg)
![www](https://user-images.githubusercontent.com/55959616/79700823-3a027e00-825e-11ea-9e7f-0abecb92bd81.jpg)

**Comment by Carcharadon** [comment]
I dont know if these help , it seems to be working better now tho

**Comment by Carcharadon** [comment]
![Carcharadon_006](https://user-images.githubusercontent.com/55959616/79700894-64ecd200-825e-11ea-9b87-b7a988a1201f.jpg)

**Comment by grunbag** [comment]
I don’t see your teammates with the buff icon

**Comment by grunbag** [comment]
I need a combat log from your teammate , your combat log doesn’t tell if their bane shield proc

**Comment by Carcharadon** [comment]
thats what im getting at the tactic is slotted im well with in 30 feet of most of my team and it was not going on them

**Comment by Carcharadon** [comment]
well it is a solo  i have no clue who my mates where this morning , it seems to be workiing now i just ran a few more games , something is off tho or not right

**Comment by grunbag** [comment]
Onnyour sceeenshot , the blackguard seems to have it

**Comment by grunbag** [comment]
The proc damage your team mates do when they have your bane shield is not credited to you . Don’t wont appears in your combat log .
