### ISSUE TITLE
Screen flashing, can't get it to stop

### ISSUE THREAD

**Issue by Thrashnar** [WarEmu/WarBugs#16432]
https://www.youtube.com/watch?v=us_19c1lfoQ

As seen in the video above, my monitor is flashing on all screens of the game.  I have tried rebooting the game, my computer.  I've run the game in both 32 and 64.  I was running Reikland last night, had a lag spike, and then all of a sudden this started happening.  I can't get it to stop and asking in advice/guild/alliance isn't coming up with a solution.

Help please.

**Comment by Thrashnar** [comment]
No idea what happened, but it appears to be working after the server reboot.  If I have the issue again I will commend.

**Comment by MaxHayman** [comment]
Very weird, if it happens again please try running in windowed mode.
