### ISSUE TITLE
The maw ranked not giving 25 medals 

### ISSUE THREAD

**Issue by Carcharadon** [WarEmu/WarBugs#16435]
only getting parcial medals for 500 wins 
![Carcharadon_008](https://user-images.githubusercontent.com/55959616/79700800-1b9c8280-825e-11ea-875a-c824caeb1420.jpg)

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by dalen** [comment]
if it ends early (before 6 min mark) you don't get full rewards
