### ISSUE TITLE
Gunbad: Can't opt out of Gold bags / DPS Contribution / No quest credit

### ISSUE THREAD

**Issue by emailkook** [WarEmu/WarBugs#16436]
We did GB middle wing today and at least 3 players opt'd out of Gold bags and they would still win them. They tried pre-opting out and also opting out during the encounter. Also attempted to opt in and opt out to change it up and they still won a gold bag through out the center wing we did. 

Should be able to reproduce the problem but just doing it with a group and opt out of gold bags in advance and see it'll still go to them. 
---
Quest for the boss kills is also not being awarded. We clear the whole middle wing and no one in group got quest credit for ANY of them.

Screen shot added shows all 4 bosses "Threat" quests didn't give the kill credit.

![Spelll_019](https://user-images.githubusercontent.com/50253609/79701757-4a6a2700-8265-11ea-96ea-4a73e4a44c7b.jpg)

DPS really gets very low contribution every boss, so DPS trying to get bags and it's going to the ones Opting out just makes it worse in the current state.

First time doing GB as trying to go for Inf weapon reward from BS and lack of Opt out, Quest being rewarded and low DPS contribution makes the system extremely difficult to get the Greater Ward.

**Comment by Kaelang** [comment]
Hi emailkook,

For the sake of keeping this bug-tracker organised, please can you open these reports as separate issues. I appreciate these are all related to Mount Gunbad, however separate developers work on separate aspects.

The Quest Credit issue you have listed has already been reported here: https://github.com/WarEmu/WarBugs/issues/16426 So there's no need to reopen this one. 

The contribution system looks to be working as intended, as supported by the report here: https://github.com/WarEmu/WarBugs/issues/12962 - Naturally this was a healer suggesting the contribution is flawed, and that DPS are always getting the bags. I don't see a reason to re-open this as a report following from the developer response, but do so as you wish. 

Opting out of gold bags - Although this report https://github.com/WarEmu/WarBugs/issues/13976 isn't necessarily gunbad related, it relates to PQ's. However I'm happy to review this if you wish to open this as it's own report.

Thanks,
Kaelang. 

Thanks.
