### ISSUE TITLE
Gunbad Wings: no credit kill, no last boss corpse to loot, and insane damage

### ISSUE THREAD

**Issue by engharat** [WarEmu/WarBugs#16438]
Well, that run has been a nightmare. I'll start from the damage. the green puddles spawned by 
the squig herder boss do probably 3x the damage of before. 2x the damage of any other puddle in the game. 1 second moving out from them is enough to kill full invader offtank RR73. moreover, after first adds phase, the boss shooted on a full invader RR69 healer insta killing him.
I was able to do that boss with a party full of anni people which knows the fight, and now a party full of RR 60-70 invader people wiped 10 times.
Then, we managed to kill him, and the boss corpse disappeared, so no item loot.
Finally, no credit kill for the quest (but still lockout!)
I don't know how to produce any evidence for that, but you can check Crimsonmistrss quest which did the boss with us and she is still at 0/3 kills.

Edit:
the quest which did not get credit kill is Dat Glomp's A Treat, even if looking at other reports it seems all gb quests are bugged.
I think only one people got the kill, so maybe the bug is involving last-hit kill?

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Addressing the quest section of this report - this has been reported on the Bugtracker and tagged up.

Addressing the damage section of this report - please can you verify with combat logs so we can identify figures and ability names etc.

Addressing the last boss being lootable - There is a report of the body being moved from where the boss died, could this have been the case?

**Comment by engharat** [comment]
regarding boss damage - I will verify through combat logs as soon as the credit kill bug will be solved - sorry didn't had the thought to save the logs during last run.
Regarding the boss corpse, it is possible that the body have been moved and we didn't noticed it. I went to loot the coffer and got ported out of the lair as my mates. We didn't looked carefully in the room.

**Comment by Kaelang** [comment]
I'll keep the labels as they stand and once you're able to test this further I'll look to retag this issue and/or close it.

Thanks.

**Comment by engharat** [comment]
Some updates - we did gunbad mid yesterday, the boss corpse is not lootable anymore, but the item is given through gold bag pq system, so the loot seems to work like intended - but the opt out system is not working both for the final boss as well as the intermediate ones.  Moreover, no one got any credit kill from the boss for the quest.  Don't know if this report deserves another post so I'm writing it here, I'll report about gb left again in a couple of days. 
It would be cool if lockout could be removed until these naughty bugs are fixed! :) getting no item no credit kill but 3 days lockout is awful

**Comment by Estienne1985** [comment]
Sorry if i am redundant, just posting my issue here and under Ar'da feet category.
Needed my last kill on him to finish my red-eye set. Killed him with my party abou 20mins ago, but got no kill credit in my tome, so i can't get my chest piece. i still see 2/3 form "the threat from Ar'da feet" quest.
Can anyone help me pls?

**Comment by engharat** [comment]
![WhatsApp Image 2020-04-24 at 23 51 54](https://user-images.githubusercontent.com/16682919/80261376-8bf63a00-868a-11ea-99ba-a99a54bc2901.jpeg)
a snippet of combat damage from Dat Glomp's a Treat ( gb left last boss).
This is guard damage, so we can suppose it was a 2000hit already mitigated damage directed to the sorcerer which was guarded by the BG. The sorcerer has 0.0% chance to be crit and 2000 armour during that fight. And there was no puddle to kill the bg, so also the two other hits of ~500 each are coming from some boss attacks.
So, the boss has done in a quick frametime 2000+1000+1000 mitigated dmg to the sorcerer, whose damage got split by guard.

**Comment by Rydiak** [comment]
Can confirm that Glomp does not provide any kill credit, nor does he provide any loot drops.  Instead, a PQ roll is (I'm presuming being used as a substitute) made with gold bags being handed out instead.

**Comment by Hargrim** [comment]
Kill credit is fixed, there should be 2 gold bags available per boss and opt out is not possible, as per design.

**Comment by engharat** [comment]
Guys we just did GB left and no one got the credit kill... :-(

**Comment by Rydiak** [comment]
I wonder if it requires the weekly patch for the fix to be implemented.

**Comment by Kaelang** [comment]
Correct - the patch has not gone live yet.

**Comment by engharat** [comment]
Alright my bad, reading Hargrim comment I thought it was hot-patched without needing explicit patch. thank you for clarification, only pity is this damned 2 hours 17 hours lockout again xD

**Comment by Kaelang** [comment]
Added Fix-Pending so should give some clarity.
