### ISSUE TITLE
Warlord Ring for Slayer 

### ISSUE THREAD

**Issue by ravezaar** [WarEmu/WarBugs#16442]
Warlord Ring for Slayer lacking any resistance stats, can u remove ring from my bag and maybe get my Royals back or fix situation

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
This is a duplicate of https://github.com/WarEmu/WarBugs/issues/15677.

The team do not refund or recover any items.
