### ISSUE TITLE
Blasted Medallion Quest, CH20 Empire

### ISSUE THREAD

**Issue by HeiLei1994** [WarEmu/WarBugs#16445]
![med1](https://user-images.githubusercontent.com/62302329/79778578-3bed3f80-8339-11ea-98ba-b3553805bcda.jpg)
![med2](https://user-images.githubusercontent.com/62302329/79778583-3f80c680-8339-11ea-92f2-af83afc905a4.jpg)

There is no indicator, "red zone" is missing for where to look for the Medallion Shard.

**Comment by Kaelang** [comment]
Please can you provide screenshots, quest log, map, quest entry etc.

**Comment by HeiLei1994** [comment]
Have updated with pics

**Comment by HeiLei1994** [comment]
![med4](https://user-images.githubusercontent.com/62302329/79778897-c170ef80-8339-11ea-8dd7-388b5486a8f3.jpg)

**Comment by HeiLei1994** [comment]
Anyone know where to find it haha... or do I have to wait for a fix?

**Comment by Kaelang** [comment]
Ask in Game Support on the Forums or /advice.

https://www.returnofreckoning.com/forum/viewforum.php?f=5

**Comment by Kaelang** [comment]
Fixed in todays patch.
