### ISSUE TITLE
[Non-Gamebreaking][Visual Bug]marauder 5th invader set bonus

### ISSUE THREAD

**Issue by Esclade** [WarEmu/WarBugs#16443]
5th piece  visually bug my attack speed on character screen but it does work as intended.

https://gyazo.com/ab213d1a9a575f80c84a6dda112bbf8c

**Comment by Kaelang** [comment]
Please provide before and after screenshots of your Melee - Speed tab. With and without the 5 piece equipped.

**Comment by Esclade** [comment]
without 5piece equipped

https://gyazo.com/0914258aec1cfa56b835900b326b6f9d

with 5piece equipped

https://gyazo.com/cd15ea7e403f730ee7bb52abaa52e631

also with and without 5piece has same auto haste i didnt wear or unwear any piece that has auto attack haste (invader gloves) sorry for bad english and thanks

**Comment by Kaelang** [comment]
Hi - sorry, I'd need to see pictures of the stat tab to identify if the tab is actually being calculated. 

![image](https://user-images.githubusercontent.com/60117106/79815415-9c4fa180-8378-11ea-84a3-3eb5cc815786.png)

If you could upload this image, one without equipping the bonus, and then one after equipping the bonus. That would be great.

**Comment by Esclade** [comment]
Before

https://gyazo.com/934fb70724e4ee367f421431fb6614d5

After

https://gyazo.com/9cb69426b80408ffd51b061575cc91df

**Comment by Kaelang** [comment]
The two screenshots show a huge difference in stats, as if you was using a skill / buff / debuffed etc. Are you able to provide screenshots of you simply adding and removing the set bonus, without doing anything else on the character? 

Just to clarify, I only need you to remove the 5th piece of Invader gear, and add the 5th piece. The only stat I'm looking at is the Speed stat, which should change from your 5th piece bonus.

**Comment by wargrimnir** [comment]
There's a flag to force the stat type to be percentage. If that isn't set, it will show up as +15 instead of +15%. Set correctly it should work on the character sheet properly.

**Comment by Esclade** [comment]
https://streamable.com/7aurg3

**Comment by Kaelang** [comment]
> https://streamable.com/7aurg3

Thank you.

**Comment by Kaelang** [comment]
As of today's patch, this should now be fixed.

Please re-open this issue if you continue to experience problems.
