### ISSUE TITLE
Shaman, (Pass It On tactic) problem

### ISSUE THREAD

**Issue by AlmondTheCrazy** [WarEmu/WarBugs#16441]
It showing this and tactic is red, after I get that tactic
https://i.postimg.cc/Qxj0W8qv/1.png
log off - nothing, exit game and log back - nothing, learn again - nothing

I have +1 from armour set, but it make my Path of Mork path on 4 points and from CR17 I have one more, which I added to this tactic.
Weird thing is, I always add tactic in CR17 and none was red like this is.
11,13,15,17 - 4 points.
It my 5th character, which pass CR17 and all of them was learning tactic at CR17 with equipped armour set bonus. Never had that, like now.

**Comment by Kaelang** [comment]
What armour set are you wearing? Please can you submit a screenshot.

**Comment by AlmondTheCrazy** [comment]
https://i.postimg.cc/hjcwpLB1/2.png

**Comment by grunbag** [comment]
Need to edit the client min level

**Comment by AlmondTheCrazy** [comment]
So, I went to T2/3 SC and to oRvR and then it change red to green and it work
https://i.postimg.cc/xj6f57YM/3.png

**Comment by Kaelang** [comment]
As of 22/04/2020 this should have been fixed. Please re-open this report if you find you are still having issues.

- Edited some Level requirements on spec abilities tooltip from Ror made abilties . This caused some abilties to turn red even if they were accessible.
