### ISSUE TITLE
Dragon's Bane: Capture of BO not counting for Event

### ISSUE THREAD

**Issue by CprWAR** [WarEmu/WarBugs#16446]
Description:
The Event objective of capturing and holding the Commorancy throughout the remainder of the scenario, did not count as completed even after >10 positive tries.

Expected behavior and actual behavior:
Event objective should count as 1/1 after capturing and holding the Commorancy, however on character Cpr this was not the case. Therefore it was not possible to claim the final Event reward: the Renown potion.

Steps to reproduce the problem:
1. Participate in the Dragon's Bane scenario.
2. Capture and hold Commorancy BO until end of scenario.
3. Open tab Live Events in ToK and observe that capture was not counted.

Testing Screenshots/Videos/Evidences (always needed):
See screenshot below
![CommorancyNot CountingROR](https://user-images.githubusercontent.com/64031906/79778278-c7b29c00-8338-11ea-92bf-4dc6c4df99ea.jpg)

**Comment by dalen** [comment]
Your side needs to capture it first, and then hold it for the rest of the scenario for it to count.

I've completed all tasks, so it does work. But maybe it could be clarified a bit.

**Comment by CprWAR** [comment]
I am not claiming that it is a global issue, it seems it was a bug on my character. I can confirm that I did exactly this, probably 15 times: As soon as scenario started, I ran to the BO, took and managed to hold it to the end of the scenario.

**Comment by dalen** [comment]
Hmm, odd. I can take a look and see if I find something that could cause that.
