### ISSUE TITLE
Placed in mirror / empty scenario with active scoreboard / party.

### ISSUE THREAD

**Issue by bruhnorellux** [WarEmu/WarBugs#16447]
Queued for solo scenario on my SW, Xswiftblade.  Used the Queue Queurer V2.9 addon that comes with VinUI.  Got a queuepop for Morakin temple.  Was placed in party but teleported to my own uninhabited instance of Stonetroll Crossing.  Was unable to interact with anything in my instance.  at the completion of the instance I got the splash-screen popup with scenario stats for Morakin temple.  When I clicked Leave now, i was removed from group and teleported to an empty instance of Morakin Temple.  I had to use book of binding to leave the empty instance which gave me the 10 minute quitter! debuff.

**Expected behavior and actual behavior:**
To be placed in the same scenario as the rest of my party when you queue up for solo scenarios.

**Steps to reproduce the problem:**
Unknown / Unable to reproduce.  Will update thread if I am able to successfully reproduce the bug

**Testing Screenshots/Videos/Evidences (always needed):**
![WAR-64_4eDorohchb](https://user-images.githubusercontent.com/8151714/79794743-cd03ec80-8320-11ea-8c12-99dd25319d47.jpg)
![WAR-64_hXhmjLUA2O](https://user-images.githubusercontent.com/8151714/79794757-d42afa80-8320-11ea-9b9f-35d3a303f92b.jpg)
![WAR-64_w6EF9slvAO](https://user-images.githubusercontent.com/8151714/79794766-d68d5480-8320-11ea-8ce5-04e5a8b21c23.jpg)

**Comment by bruhnorellux** [comment]
Description:


Expected behavior and actual behavior:


Steps to reproduce the problem:

**Comment by dalen** [comment]
There were some changes in the latest patch that should fix various odd issues like this while switching region. I'll close this, can reopen if it still happens
