### ISSUE TITLE
Apothecary: Blotchy Smedleycap creates wrong intelligence potion.

### ISSUE THREAD

**Issue by magicthighs** [WarEmu/WarBugs#1644]
The level 25 intelligence seed Blotchy Smedleycap creates a Potion of Subtlety, which has a minimum rank of 35 to use and gives 72 int, instead of Potion of Guile, which has a minumum rank of 10 to use and gives 24 int.

**Comment by ropuch** [comment]
If you use CraftValueTip addon, you can invoke /craftvaluetip digest while hoovering over the fragment - this will give uniqueID with crafBonus table values - I think it will provide good info to start for devs [;

**Comment by magicthighs** [comment]
Thanks for the pointer, ropuch.

[84019]Blotchy Smedleycap Spore lvl0/0 craftingBonus[5=3,9=25,14=9,13=16,]

Info on the potion that was created:
[3000814]Lasting Potion of Subtlety lvl 35/36 bonus[1=(t=3,v=0,cTL=0,r=7906,tCT=300),]

Can't give the info on the potion that should have been created, because I can't create it, of course.

**Comment by genisaurus** [comment]
Fixed in next patch.

**Comment by Darishel** [comment]
When the level 10 intelligence potion crits, it makes a blue Potent Lasting Potion of Subtlety which is level 35.

**Comment by Damiel126** [comment]
Yep. Got the same result last night from a L25 ingredient. Not sure if it was a crit or a super crit - that would probably be worth checking.

![licksitbetta_014](https://cloud.githubusercontent.com/assets/10399547/16437682/3a5f6080-3dec-11e6-888c-fc6e1a7f0bc2.jpg)

**Comment by Paleolog77** [comment]
When i craft Blotchy Smedleycap, alchemy ingridient 25lvl
![1](https://cloud.githubusercontent.com/assets/23325288/20922578/b6377026-bbb9-11e6-97df-69c241973030.jpg)
i am getting 10lvl potions of intellegent
![2](https://cloud.githubusercontent.com/assets/23325288/20922587/bf7a2796-bbb9-11e6-8147-958d5e063d8a.jpg)
but when the crit comes i get potions of 35lvl
![3](https://cloud.githubusercontent.com/assets/23325288/20922614/d565e98c-bbb9-11e6-90f2-0c603425d0bf.jpg)
