### ISSUE TITLE
[WH] Dragon Gun has always the same bullet's implementation area

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#16440]
As ability description says, with 1 accusation AOE radius is 30 feet and with 5 of them - 48 feet
So, I thought, bullets should hit all affected targets in the same area
But, it seems that bullets hit area always remains at 30 feet from initial target

**Expected behavior and actual behavior:**
Exp: Bullets should hit all targets in the 30-48 feet area at 1-5 accusations
Act: Bullets hit targets in 30 feet area always

**Steps to reproduce the problem:**
Set up several targets
Build accusations
Use Dragon Gun with any bullets

**Testing Screenshots/Videos/Evidences (always needed):**
https://www.youtube.com/watch?v=bAypWv6vucY

**Comment by XmatXergon** [comment]
Hmm, i think this issue should be closed, as it seems it's not bugged anymore, or at least i was unable to reproduce this bug.

Here is video:
https://www.youtube.com/watch?v=6a-fcrmo5-o
