### ISSUE TITLE
Sovereign Bo 8 Pieces Bonus

### ISSUE THREAD

**Issue by Grumug** [WarEmu/WarBugs#16453]
The 8 Pieces set bonus remain even when the set is unequipped

I suppose this is not how it should work

I use closet goblin to swap sets and when i swap from full sovereign to bloodlord set the 8 piece bonus (absorb) is still available.

![8 Piece Bonus](https://user-images.githubusercontent.com/64093828/79890890-7372ef00-8400-11ea-9e8a-d250c963e430.jpg)

**Comment by Kaelang** [comment]
Could you upload the screenshot of the Sov 8 piece bonus? And are you able to test if the bonus still works and it's not just a visual error?

**Comment by Grumug** [comment]
![Grumug_000](https://user-images.githubusercontent.com/64093828/79892651-25131f80-8403-11ea-9d98-fea0b9217e81.jpg)

yes the bonus give the absorb even when another set is worn

**Comment by grunbag** [comment]
DOes it happened only with closet goblin ?

**Comment by Grumug** [comment]
No even if i switch set manually

**Comment by grunbag** [comment]
What happen if you unequip one’ sov piece

**Comment by Grumug** [comment]
Nothing the bonus remain and works

**Comment by grunbag** [comment]
Fixed

**Comment by Kaelang** [comment]
As of 22/04/2020 this issue has been fixed.

- Fixed an issue causing Sov and warlord 8 pc abilities not being removed after unequip one of the set piece.

Please re-open the issue if you are still experiencing this problem.
