### ISSUE TITLE
Apostle's Runestaff of Reverence

### ISSUE THREAD

**Issue by Verenduum** [WarEmu/WarBugs#16452]
**Expected behavior and actual behavior:**
The blue "Apostle's Runestaff of Glory" has +2% reduction in being critically hit whereas the 1200 emblem upgrade purple "Apostle's Runestaff of Reverence" doesn't have that stat. What's weird is in the armoury on the RoR site, it's listed as also having the crit reduction. But it isn't on the weapon in game.

Is this correct? Would be great if we can get the crit reduction added to the purple weapon too, otherwise the 1200 emblem upgrade seems a lot less worth it.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![sc staff](https://user-images.githubusercontent.com/64093137/79889517-694ff100-83fe-11ea-8482-e565d051ed1f.png)
![unknown](https://user-images.githubusercontent.com/64093137/79889522-6ce37800-83fe-11ea-95b4-6549560be6bf.png)
![unknown (2)](https://user-images.githubusercontent.com/64093137/79889523-6ead3b80-83fe-11ea-9db0-bc8b18545b0b.png)

**Comment by Kaelang** [comment]
As I mentioned on the forums, there's some obvious differences between the stats from the Armory and those in-game. I'll keep this open and tagged until someone with more knowledge on the specific item stat weight can comment as to which value reflection is correct.

**Comment by wargrimnir** [comment]
This has 6 AP instead of 2 crit reduction. These are the same for other healers.

If it's not worth it to you, don't buy it. Not a bug.
