### ISSUE TITLE
A Head for Intrigue

### ISSUE THREAD

**Issue by ChrisRBe** [WarEmu/WarBugs#16466]
**Expected behavior and actual behavior:**
As an order player I am able to interact with Balfarus' Lootbox and accept A Head for Intrigue quest. This should not be possible

**Steps to reproduce the problem:**
As an order player I am able to interact with Balfarus' Lootbox and accept A Head for Intrigue quest.

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/31167512/80011856-bb5f4800-84cc-11ea-8250-3e60989b7c39.png)

**Comment by Lheana** [comment]
The easter egg quests are accessible to all players, was that way on official. But yes, some of them can not be completed by both factions.

**Comment by dihanin** [comment]
> The easter egg quests are accessible to all players, was that way on official. But yes, some of them can not be completed by both factions.

hmmm
I did it to speak with quest NPC. and still can't resolve it.
https://drive.google.com/file/d/1xmco8hcqEvJj-q6Ph1W0RXJdnV6jFIVA/view?usp=sharing
