### ISSUE TITLE
Bolster and leveling up

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#1646]
If you level up while under effect of bolster in scenario it drops from you and do not reapplies until you zone/relog/etc. This renders you pretty much useless if you are a low level character in your tier.

**Comment by Evildoor** [comment]
Seems inconsistent. Today i lvled up on Tor Anroc and kept my bolster, then i lvled up on Mourkain Temple and lost bolster.

**Comment by Evildoor** [comment]
Seems to be fixed. Leveled up on different scenarios while retaining bolster, seen the same with other players.

**Comment by Blaqwar** [comment]
Happened to me today on my Sorc in Gates of Ekrund, went from level 1 to 2 and lost bolster. Was hitting like a wet noodle and was taking 200 damage from Shadow Warriors with 400 total HP. Rough

**Comment by Luth-RoR** [comment]
Screenshot would have been nice.

**Comment by Blaqwar** [comment]
Tried recreating the bug, deleted the previous sorc and made a new one, first try.

![cassiel_004](https://cloud.githubusercontent.com/assets/5108812/18436593/7c73fc72-78f9-11e6-9919-92d4ad6111e9.jpg)

Let me know if you need more screenshots or more info but it should be easy enough to recreate the bug yourself.

**Comment by Luth-RoR** [comment]
Thanks.

**Comment by Blaqwar** [comment]
This no longer happens, bolster is being correctly reapplied when leveling up in scenarios.
