### ISSUE TITLE
Squig Herder New Sovereign Granted Ability isn't shown. 

### ISSUE THREAD

**Issue by Teefz** [WarEmu/WarBugs#16469]
According to patch notes 22/04/2020: "- Builded new Granted Item Ability for Sov , Alt Sov and Warlord. In addition of current 8 pc ability bonus, the following new abilities will be dispatched into the 3 royals set"

However, Squig Herder defensive/offensive sov still has the same granted ability: 
![sovtest](https://user-images.githubusercontent.com/18510648/80019426-ccfa1d00-84d7-11ea-8209-64d2afc42d7f.jpg)

**Comment by Kaelang** [comment]
Hey Teefz,

Can you clear your cache and relog?

**Comment by Teefz** [comment]
> 
> 
> Hey Teefz,
> 
> Can you clear your cache and relog?

I did and it is still the same. 

Also, Warlord did seem to get changed:
![wltest](https://user-images.githubusercontent.com/18510648/80020012-a5578480-84d8-11ea-82df-c958de397171.jpg)

This leaves "Fettered Might - Your target will have their Action Point cost increased by 50% for 10s." to be added to the defensive sovereign I suppose.

**Comment by Kaelang** [comment]
Thanks.

**Comment by Kaelang** [comment]
As of 29/04/2020 this should now be fixed. Please re-open if issues persist.
