### ISSUE TITLE
[Magus] Infernal Pain tactic

### ISSUE THREAD

**Issue by magusgamer69** [WarEmu/WarBugs#16461]
The extra DoT provided by this tactic is worded as if it's a non-type damage, that means it's not supposed to be reduced armor/resistances. Only mitigated by the enemies toughness. It also means it is not supposed to be able to crit which it doesn't.

It is definitely being reduced by more than just toughness. Assuming it was spirit damage, I tested it on several ppl first w/o glean magic on them and after and it proved that spirit resistance was indeed reducing the damage.

This tactic is either suppose to deal spirit (and if so it should be able to crit), or it should be acting like potent enchantments from SM where it deals pure damage only mitigated by the targets toughness but cant crit etc...

either way this ability is bugged.

**Comment by Kaelang** [comment]
Although not directly related - this seems to be relevant to another report based on the Infernal Pain tactic's damage output listed here https://github.com/WarEmu/WarBugs/issues/11944.

I'm going to close this one up for now and mention it in the other report.
