### ISSUE TITLE
[Shaman] CR1 ability missing?

### ISSUE THREAD

**Issue by AlmondTheCrazy** [WarEmu/WarBugs#16467]
Hello. As I was looking inside the Career build for Shaman, I spot in **Path of Da Green** ability for CR1
https://i.postimg.cc/J04cjd51/Screenshot-31.png
Then I went into the game, log into my CR24 Shaman and that what I see in my **PoDG**
https://i.postimg.cc/TwyDVLK4/2.png

Is that ability got removed or moved to different CR?

**Comment by grunbag** [comment]
It’s a tooltip bug , it’s obtainable at career rank 30

**Comment by Kaelang** [comment]
As of 29/04/2020 this should now be fixed. Please re-open if issues persist.
