### ISSUE TITLE
Invader jewelry not bound to slot 4

### ISSUE THREAD

**Issue by Teefz** [WarEmu/WarBugs#16471]
According to patch notes 22/04/2020: "Invader Jewels are now bound to slot 4 like the other RvR set jewelry"

![invader](https://user-images.githubusercontent.com/18510648/80020595-96bd9d00-84d9-11ea-9f4b-cfcdbe28c30e.jpg)

Still able to slot them in Slot 1, 2, 3 & 4. Equip, re-equip doesn't matter. It is not locked. Cleared cache log and relogged as well.

**Comment by Kaelang** [comment]
This is currently known however I'll keep this issue live until future updates are provided.

**Comment by Kaelang** [comment]
Removed from the patch notes as it didn't get applied for this week. Guess we might want to look into code-removing items in unapproved slots before we do it. Lots of honest folk here pointing out an unintended potential bug.

-wargrminir

When this returns, if the issue persists please re-open an issue.

Thanks for reporting this either way.
