### ISSUE TITLE
[Runepriest] Rune of Restoration not benefitting from Mastery Points

### ISSUE THREAD

**Issue by toxickitteh** [WarEmu/WarBugs#16476]
**Expected behavior and actual behavior:**

Healing output increasing with points invested into Path of Grungni as stated in the Ability Training screen. The Healing output does not increase when points are spend in the Path of Grungni Tree for this ability.

**Steps to reproduce the problem:**

Compare Healing done with 0 and 15 points into Path of Grungni.

**Testing Screenshots/Videos/Evidences (always needed):**
15 Points
![Gustafsson_004](https://user-images.githubusercontent.com/64174160/80044607-5542e700-8505-11ea-88f9-229ee2f7af32.jpg)

0Points
![Gustafsson_005](https://user-images.githubusercontent.com/64174160/80044612-5aa03180-8505-11ea-92e6-2b1ebeea9470.jpg)

Thank you.

**Comment by Kaelang** [comment]
Hey - I don't have access to test this on a more in-depth scale, however I do have a level 11 RP.

I've just tried Rune of Restoration with 0 Mastery spent in the tree, and then added 1 point and trained.

![image](https://user-images.githubusercontent.com/60117106/80051677-af957500-8510-11ea-9eb9-1166a1395141.png)

**Comment by toxickitteh** [comment]
works correctly now, tested it both Fully geared and naked. Strange.
