### ISSUE TITLE
Bastion Stair - Kaarn the Vanquisher Boss corpse fell through floor.

### ISSUE THREAD

**Issue by msfleming1** [WarEmu/WarBugs#16475]
**Expected behavior and actual behavior:**
Boss corpse of Kaarn the Vanquisher fell through the platform floor and could not be looted

**Steps to reproduce the problem:**
![image](https://user-images.githubusercontent.com/59762020/80036108-09824480-84e9-11ea-96c0-4edc8e6ddb97.png)

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by grunbag** [comment]
You can loot it , assign a hot key to loot nearest
