### ISSUE TITLE
Pets: Turrets / Magus / Mines etc cause Indexoutofrange spam.

### ISSUE THREAD

**Issue by Opturs** [WarEmu/WarBugs#16474]
**Expected behavior and actual behavior:**
Expected behaviour, none
Actual behavior, text spam in game

**Steps to reproduce the problem:**
No idea, started after patch

**Testing Screenshots/Videos/Evidences (always needed):**

![Opturs_001](https://user-images.githubusercontent.com/64166589/80030252-3eda6280-84e8-11ea-847d-ca981e87a699.jpg)

**Comment by Opturs** [comment]
![Opturs_002](https://user-images.githubusercontent.com/64166589/80030421-777a3c00-84e8-11ea-9bf7-1ada10b4ebd0.jpg)

**Comment by Kaelang** [comment]
Was this triggered by an ability or anything? Or is it constant?

**Comment by Opturs** [comment]
Constant, getting it from pets, turrrets and what seems like named NPCs or players :/

**Comment by Kaelang** [comment]
Okay - thank you.

**Comment by Opturs** [comment]
Scrap the named NPC/players thing, cant find that reproduced, I might have been mistaken on that one, but seems all types of pets, landmines, turrets, demonic infestations ect ...

![Opturs_003](https://user-images.githubusercontent.com/64166589/80032141-0720ea00-84eb-11ea-925e-9140fc50fa09.jpg)

**Comment by Kaelang** [comment]
As of 29/04/2020 this should now be fixed. Please re-open if issues persist.
