### ISSUE TITLE
Engineer's gun turret lost an ability.

### ISSUE THREAD

**Issue by smaugthehobbit** [WarEmu/WarBugs#16472]
Before the update, the gun turret had 2 abilities.
After the update there's only 1 ability showing.
Image:
https://cdn.discordapp.com/attachments/329292495336767488/702582874896990230/unknown.png

To reproduce, roll an engineer and level it to lvl 3 and check the gun turret abilities.

**Comment by Kaelang** [comment]
What is/was the ability name?

**Comment by smaugthehobbit** [comment]
The ability is machine gun.
![image](https://user-images.githubusercontent.com/12082001/80027100-80b4da00-84e3-11ea-981f-d57d936b6f6e.png)

Here's the screenshot of the abilities of gun turret before the patch:
![image](https://user-images.githubusercontent.com/12082001/80026996-5fec8480-84e3-11ea-8bce-5a952fb6d745.png)

As you can see Machine gun is missing now.

**Comment by Sandskid** [comment]
My turret loosing 2 abilities (only autoattack left) every 2nd time it's spawned in a row

**Comment by Dasvadanya** [comment]
> The ability is machine gun.
> ![image](https://user-images.githubusercontent.com/12082001/80027100-80b4da00-84e3-11ea-981f-d57d936b6f6e.png)
> 
> Here's the screenshot of the abilities of gun turret before the patch:
> ![image](https://user-images.githubusercontent.com/12082001/80026996-5fec8480-84e3-11ea-8bce-5a952fb6d745.png)
> 
> After patch now:
> ![image](https://user-images.githubusercontent.com/12082001/80027240-be196780-84e3-11ea-9c87-6e364a3ed263.png)
> 
> As you can see Machine gun is missing now.

I'm having the exact same issue on my engineer.  Machine Gun disappeared off my pet action bar.  I lost an ability off my flame turret as well.

**Comment by grunbag** [comment]
Tested on dev , you correctly receive the machine gun ability at level 17
