### ISSUE TITLE
Maw of madness ranked sc doesn't finish and players get stuck in it

### ISSUE THREAD

**Issue by radumolnar** [WarEmu/WarBugs#16473]
**Expected behavior and actual behavior:**
Maw of madness sc should end when you reach 500 points or when the timer runs out

**Steps to reproduce the problem:**
Play Maw of madness ranked scenario
This has now happened to me twice, in 2 consecutive runs of the scenario.

In the first one my team reached 500 points but the scenario didn't end. It also didn't end when the timer ran out. A GM teleported us out.

In the second run the enemy had 200 points when the timer ran out. Again the scenario did not end, the timer just stopped at 0:00

**Testing Screenshots/Videos/Evidences (always needed):**
![Babanovac_001](https://user-images.githubusercontent.com/49276066/80024008-1736ca80-84e7-11ea-8616-c884ded42bb6.jpg)
![Babanovac_002](https://user-images.githubusercontent.com/49276066/80024011-19992480-84e7-11ea-8373-9d79a6300212.jpg)
![Babanovac_003](https://user-images.githubusercontent.com/49276066/80024014-19992480-84e7-11ea-813b-4811e8d14424.jpg)
![Babanovac_004](https://user-images.githubusercontent.com/49276066/80024016-1a31bb00-84e7-11ea-9ef6-22fcd9fb2522.jpg)
![Babanovac_005](https://user-images.githubusercontent.com/49276066/80024018-1aca5180-84e7-11ea-9455-0d4c5dafdb49.jpg)
![Babanovac_006](https://user-images.githubusercontent.com/49276066/80024020-1aca5180-84e7-11ea-9503-9e8771ed896d.jpg)

**Comment by Kaelang** [comment]
Hi - thanks for the report. The devs are working on a fix as per the announcement in-game.

**Comment by Kaelang** [comment]
As of 29/04/2020 this should now be fixed. Please re-open if issues persist.
