### ISSUE TITLE
GB Mid No Boss Quest Completion

### ISSUE THREAD

**Issue by randallbcotter** [WarEmu/WarBugs#16478]
I am 2/3 on Ard to Feed. We killed him, and the quest did not complete. I'm now locked out. If I don't get a gold bag I will never be able to complete it. Thanks
-Bloodroote

**Comment by randallbcotter** [comment]
https://cdn.discordapp.com/attachments/467120396966297611/702799530487447562/unknown.png

**Comment by Naincheux** [comment]
I got the same issue yesterday.

**Comment by wiscel** [comment]
We had the same thing yesterday with Glomb (left wing), we killed him but it didn 't add in the ToK, and the quest to kill him also didnt update.
![Nicebeaver_000](https://user-images.githubusercontent.com/11788060/80090582-04aca780-8560-11ea-96f8-b478a45ce917.jpg)

**Comment by Kaelang** [comment]
Duplicate of https://github.com/WarEmu/WarBugs/issues/16426.

There looks to be issues with all Gunbad Quests in general.
