### ISSUE TITLE
Summon Blue Horror

### ISSUE THREAD

**Issue by Billpullman** [WarEmu/WarBugs#16470]
**Expected behavior and actual behavior:**
Summon Blue Horror doesn't increase Dodge/disrupt chance of magus by any %

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Please can you provide .getstats / statdoll screenshots before and after summon.

**Comment by Billpullman** [comment]
After checking .getstats, it actually increases dodge/disrupt but doesnt't shows in character stats

**Comment by Kaelang** [comment]
The character stats screen can be misleading, but this is a known issue. As the ability is working as intended I'm going to close this for now. Thanks.
