### ISSUE TITLE
Dont load my char

### ISSUE THREAD

**Issue by Japzor** [WarEmu/WarBugs#16480]
It dont load my char :(
Regards 
Japzor

**Comment by GiGGibert** [comment]
same Problem... my chars are not loaded :( 

Regards GiGGi

**Comment by GiGGibert** [comment]
email adresse ingame is m1keEE@web.de

**Comment by Kaelang** [comment]
This is a bugtracker. Not a Technical Support forum.

Thread closed and locked.
