### ISSUE TITLE
Lack of rewards on the siege of the city

### ISSUE THREAD

**Issue by Gimmen** [WarEmu/WarBugs#16488]
Today 04/24/2020 did not receive rewards for winning the 3rd stage of the siege of the city. There was no bag drawing either. Farlanda character name

**Comment by Kaelang** [comment]
Hi - this is a duplicate of https://github.com/WarEmu/WarBugs/issues/16323.

I'm going to close this report for now. Appreciate the concern with lost bags etc, however the team don't get involved with recoveries / refunding lost items.
