### ISSUE TITLE
[City Siege] [Stage 2] Lords too fast

### ISSUE THREAD

**Issue by bosli42** [WarEmu/WarBugs#16489]
Since one or two weeks, the lords of stage 2 move way too fast. It was fine when it was still possible to slow them down, but now the only thing you can do is use Champion Challenge, which only works with order around. Even on knockdown, they just speed up afterwards to get back where they should be. When engaged with the enemy team, it is enough to AoE snare them all, and they can't keep up with the lord to get damage on him.
What this means, is if you are defender and an attacking lord gets past your lord after he died, it is almost impossible to kill him before reaching the gate unless either the enemy team doesn't engage you for some reason, or he still has a flag to cap and stand still for some time (which they usually don't have or can't because it was already capped by the other lord).

**Comment by Kaelang** [comment]
Hi - do you have any video / recording to support this? I've just finished a city personally and the lords movement speed seemed normal?

**Comment by bosli42** [comment]
I don't, but what is considered normal? It seems that they move about 90% of player speed, which is simply too much to have a chance at killing them after they get past mid. They heal back up fully, knock doesn't really slow since they speed up again, and your team gets snared by the attackers so you can't keep up with their lord. To actually win at this point of the stage, you would need to instantly AoE kill the enemy team twice (since they can port to flags), so you have enough time left to get the lord kill. We had 2 tanks use Champion's Challenge every time his immunity was off, and even with that our team could barely keep up with the lord due to constantly being slowed down by the enemy team.

**Comment by Kaelang** [comment]
What I'm saying is, they look like they're moving at an intended speed, as opposed to bugged or broken. Which would turn this from a bug report, to a suggestion / feedback idea - which belongs on the forum.

At this point, I wouldn't say the movement speed is fundamentally broken, as you know how many of these cities pop recently, and this is the first report of anything in terms of their mobiltiy. Which leads me to believe this is the latter (a suggestion / feedback).

On that note, I'm going to close this as an official bug report, and direct you to here: https://www.returnofreckoning.com/forum/viewforum.php?f=15&sid=6adfa977ad27694159794901d4b359b5 where I welcome you to open a thread.
