### ISSUE TITLE
Gift of Savagery

### ISSUE THREAD

**Issue by samy6901** [WarEmu/WarBugs#16483]
Hi,

i don't understand why the savagery's dot doesn't crit and why piercing bite doesn't apply with it ?

Thx for reading and responding

**Comment by Kaelang** [comment]
Gift of Savagery was edited to no longer crit as per this report: https://github.com/WarEmu/WarBugs/issues/4997

Piercing Bite does not apply to Gift of Savagery as it does not require a mutation. It is a mutation. See similar report here: https://github.com/WarEmu/WarBugs/issues/15083

I'm going to close this up now.
