### ISSUE TITLE
Bilerot Burrow: Bilerot Sickness ap regen

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#16485]
**Expected behavior and actual behavior:**
Bilerot Sickness states that it reduces action point *regen* by 20. However, it actually doesn't affect regen at all, but drains 20 AP per second. Which is very different, since it drains AP it takes it away even when AP regen is stopped. Like when you're casting a spell or during the GCD after using an ability. This should not be the case. It should be reducing your regen by 20, it should never actually take AP away from you (unless it somehow brings your total AP/s below 0). But even if it managed that, when AP regen is stopped, you should still not lose AP. 

Additionally, the granted ability to remove the debuff often disappears, making it impossible to remove until it goes away on its own. 

**Steps to reproduce the problem:**
Get Bilerot Sickness in BB and observe your AP going down while casting any spell with a cast time.

**Testing Screenshots/Videos/Evidences (always needed):**

Img showing tooltip and no granted ability
![Forkrul_033](https://user-images.githubusercontent.com/1183293/80153986-f04bc780-85be-11ea-9727-335cb789ffbb.jpg)

**Comment by grunbag** [comment]
It’s intended , I need to update the tooltip probably . The granted abiltiy last few sec , if you don’t cleanse yourself quick enough, the debuff will stay very longer
