### ISSUE TITLE
City Bagrolls issue

### ISSUE THREAD

**Issue by GK111** [WarEmu/WarBugs#16493]
stage 2 finished

destro players who never been in our city instance(you can see it in attached screenshot
![Crazyboss_000](https://user-images.githubusercontent.com/24727277/80215467-2c297000-8645-11ea-80d0-5f51187f66e2.png)
), they got roll for bags and crests.

**Comment by Kaelang** [comment]
Duplicate of https://github.com/WarEmu/WarBugs/issues/15846.
