### ISSUE TITLE
[ORVR] Spite's Reach Keep postern door

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#1649]
Postern door at Spite's Reach keep in the Shadowlands is unable to be used.

**Comment by Tesq** [comment]
should be only for destru as ostland postern and dwarf i assume

**Comment by Abolition** [comment]
Well, yes, it should only be usable for Destro. But currently it does not work at all. Which makes keep defences even harder since the only way in is to try to front door, or die close to the wall and pray for a rez.

**Comment by Tesq** [comment]
no i mean order can use postern on their keep while only destru can't on theirs

**Comment by Evildoor** [comment]
Changelog from 21.03.2016 (a bit late :P ).

[Keeps]

- Fixed all postern doors.
