### ISSUE TITLE
Armor Stats Debolstered

### ISSUE THREAD

**Issue by bataisflow** [WarEmu/WarBugs#16491]
**Expected behavior and actual behavior:**
Hi, I have a lvl 40/81 Kotbs. He is well geared- 3x sov, 2x warlord and 2x Invader. I also have an armor talisman of +124. All added up my armor should be 4099. The armor stats on this character have been reduced and fluctuating for some time.  I originally thought it was just a visual bug, but after reading some of the topics here I saw the command for .getstats and checked them.  The .getstats # verified that it was not a visual bug, but a character bug. Maybe a debolster on my armor somehow (previous nordland event)? In total, my armor is being reduced by a factor of .066999996 and instead of the correct 4099 it is (.getstats) 2746. Have you encountered this issue before? Any known fixes?

**Steps to reproduce the problem:**
I have switched armor and gotten the same result.  I checked .getstats each time. Every armor i put on gets debolstered by the above factor. 
![15877010682995813140690840617324](https://user-images.githubusercontent.com/64241960/80173923-49b3f680-85bf-11ea-959c-4cf8b4747047.jpg)
![15877011288819031883297077584029](https://user-images.githubusercontent.com/64241960/80173944-589aa900-85bf-11ea-9b45-7bb2062d9196.jpg)
![15877011492106061874597537391941](https://user-images.githubusercontent.com/64241960/80173971-65b79800-85bf-11ea-8016-2c5f98c15ee3.jpg)
![15877011735932459407778925930506](https://user-images.githubusercontent.com/64241960/80173991-6f410000-85bf-11ea-8e02-05a70e2ba39c.jpg)
![15877012001691665788188634916339](https://user-images.githubusercontent.com/64241960/80174056-93044600-85bf-11ea-9ea2-af1414133997.jpg)
![15877012460635073328925795933666](https://user-images.githubusercontent.com/64241960/80174068-9992bd80-85bf-11ea-84d4-6541e2995543.jpg)
![1587701264896264233750688220115](https://user-images.githubusercontent.com/64241960/80174088-a6171600-85bf-11ea-99ac-c3372e2ab73e.jpg)

**Testing Screenshots/Videos/Evidences (always needed):**

Screen shots above

**Comment by Kaelang** [comment]
Can you unequip and requip your armor?

**Comment by grunbag** [comment]
Did you went to the sewers ?

**Comment by bataisflow** [comment]
> Can you unequip and requip your armor?

I tried that. Equiped and unequiped and trued different armor.

**Comment by bataisflow** [comment]
> Did you went to the sewers ?

Not with this guy, no.

**Comment by Kaelang** [comment]
> > Did you went to the sewers ?
> 
> Not with this guy, no.

But was you in sewers prior to logging onto this character?

**Comment by bataisflow** [comment]
> > > Did you went to the sewers ?
> > 
> > 
> > Not with this guy, no.
> 
> But was you in sewers prior to logging onto this character?

I went with a diff tune, but the armor issue was already happening on the knight prior to that.

**Comment by bataisflow** [comment]
> > > > Did you went to the sewers ?
> > > 
> > > 
> > > Not with this guy, no.
> > 
> > 
> > But was you in sewers prior to logging onto this character?
> 
> I went with a diff tune, but the armor issue was already happening on the knight prior to that.

Actually, i might have checked out the sewer quests for some reason but did not go in...around the time this started happening.

**Comment by bataisflow** [comment]
Would going into the sewers now and out do anything to fix. Does it have something to do with 40s taking lower lvls through sewers? I remember reading a note that there would be penalties etc. To note, i just looked at the quests for my alt, but did not go in. I then went in with my alt...but weeks later.

**Comment by bataisflow** [comment]
![15879404464418572046924050831500](https://user-images.githubusercontent.com/64241960/80321628-8add1e00-87ec-11ea-857c-e9b6a52764c5.jpg)
I think it might be related to SCs somehow. This is my other toon. Just went into an sc, noticed my armor was lower for some reason, checked get stats and it's  been lowered. So have other stats. When i exited the sc it still had the debolster on as pictured in the screen shot.

**Comment by grunbag** [comment]
WHat level are you and which sc have you been in?

**Comment by bataisflow** [comment]
![15879415646943462409190046677414](https://user-images.githubusercontent.com/64241960/80321913-253e6100-87ef-11ea-9b2d-fe31a33f8158.jpg)

Now knights armor back to normal. This is what was previousely happening. Seems to fluctuate.

**Comment by Kaelang** [comment]
Appreciate you may have missed the previous question from grunbag. 

Please can you confirm your level, and what scenario you was in?

**Comment by bataisflow** [comment]
> WHat level are you and which sc have you been in?

Lvl 40 wl. SC was Mourkain Temple i believe.

**Comment by bataisflow** [comment]
> > WHat level are you and which sc have you been in?
> 
> Lvl 40 wl. SC was Mourkain Temple i believe.

Just happened again to my knight. Just did the nordenwatch sc. Checked my stats and my armor is debolstered again.
![15880778759694922474121219842113](https://user-images.githubusercontent.com/64241960/80488555-83bd2980-892c-11ea-98ec-a773ed9ee78f.jpg)
