### ISSUE TITLE
Another crack in the bridge to IC citadel you can stuck in.

### ISSUE THREAD

**Issue by heybaws** [WarEmu/WarBugs#16496]
![Shatterbot_006](https://user-images.githubusercontent.com/64266024/80218844-5e899c00-864a-11ea-9c30-3d90b31006c4.jpg)
![Pimpmyarm_000](https://user-images.githubusercontent.com/64266024/80218877-69dcc780-864a-11ea-83f9-eb5d235af925.jpg)
![Pimpmyarm_001](https://user-images.githubusercontent.com/64266024/80218901-73fec600-864a-11ea-9950-712bdbe90f60.jpg)
I noticed that you fixed the closest crack to citadel, but there is another one, during IC siege i was unable to use armyrecall inside.

**Comment by Kaelang** [comment]
Got stuck in here yesterday too! Thanks for the report, couldn't grab a screeny. Tagged up.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16961 Closing as this other report includes this, with additional information.
