### ISSUE TITLE
bug lock zone :bugreport by system 

### ISSUE THREAD

**Issue by Fealle** [WarEmu/WarBugs#16492]
Hello

another bug report system.
no contrib , no token invaders in fort MAWL :/

Regards
![fealle](https://user-images.githubusercontent.com/63900231/80195303-e99f6d80-861b-11ea-8efb-2e6cb65583de.jpg)

**Expected behavior and actual behavior:**

![fealle](https://user-images.githubusercontent.com/63900231/80195240-d4c2da00-861b-11ea-89d8-b2233cbde75e.jpg)

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
This screenshot is showing your combat log from when The Maw flipped, correct?

**Comment by Kaelang** [comment]
No further information.
