### ISSUE TITLE
Absorb formula is wrong after last patch

### ISSUE THREAD

**Issue by blechkautz** [WarEmu/WarBugs#16497]
**Expected behavior and actual behavior:**
Absorb should be before mitigation and you shouldn't be able to get crit, but right now, you mitigate first and can get crit.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![grafik](https://user-images.githubusercontent.com/30760089/80223388-82e47900-8648-11ea-84d3-89516f505e3e.png)

**Comment by Kaelang** [comment]
As of 29/04/2020 this should now be fixed. Please re-open if issues persist.

**Comment by blechkautz** [comment]
Still not fixed

**Comment by blechkautz** [comment]
Fixed, can be closed.

**Comment by blechkautz** [comment]
@Kaelang
