### ISSUE TITLE
don't got blue bag from taking praag keep

### ISSUE THREAD

**Issue by lijebin** [WarEmu/WarBugs#16498]
i was taking praag keep this evening and i got a roll of blue bug didn't get it in maibox even six to 8 hour late

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Send a mail to your character from an alt, give the delivery system a nudge.

If this doesn't help, you should receive your bag after the next reset.

**Comment by lijebin** [comment]
thanks you
