### ISSUE TITLE
Chosen Hastened Dismissal

### ISSUE THREAD

**Issue by blackabyss187** [WarEmu/WarBugs#16507]
**Expected behavior and actual behavior:**
The expected behavior is as the tactic is written:

![HastenedDismissal](https://user-images.githubusercontent.com/64327008/80287517-2cd30c80-8700-11ea-8456-ab52cc1dfd3c.jpg)

Hastened Dismissal       Buff
Core Ability                   Level 40
1 Slot Career Tactic      Self
Passive                         No Cooldown

![Repel](https://user-images.githubusercontent.com/64327008/80287520-32c8ed80-8700-11ea-92a6-8bc345a63090.jpg)

Reduces Repel's cooldown time by 50% and increases the length of the knockback.

**Steps to reproduce the problem:**
I am currently a lv 40 rr 56 Sword and Shield Chosen equipping this tactic, the knockback is increased, however, the cooldown remains 20 seconds even though the tooltip when equipped shows 10.  

**Testing Screenshots/Videos/Evidences (always needed):**
This is reproducible every time using the sword and shield, against any and all pvp opponents. However, I'm told by others that it does work as intended when using a 2H weapon, so this seems to be limited to only the when using a sword and shield.

**Comment by Kaelang** [comment]
Hi - this is working as intended.

Please see patch notes here: Tactic - Hastened Dismissal now grants the cooldown reduction of Repel only if you are weilding a Great Weapon, super punt effect remains regardless of weapon used.

Reference: https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=23117#p258569

Thank you.

**Comment by grunbag** [comment]
Updated the tooltip for next patch
