### ISSUE TITLE
Blight on the Forest (Kadrin Valley Quest) Missing NPC

### ISSUE THREAD

**Issue by Sprak2686** [WarEmu/WarBugs#16505]
There are a few bugged out npc's in this quest location, but "Arthon the Herald" is completely missing. Quest cannot be completed without him.

**Comment by Kaelang** [comment]
Please could you provide more information? Which NPC's specifically are missing as well as Arthon the Herald, where in KV is the quest located, and screenshots of where you're looking.

Thanks.

**Comment by Kaelang** [comment]
No further information - closed.
