### ISSUE TITLE
Cale ch22 no roll at end issue

### ISSUE THREAD

**Issue by Iskrul** [WarEmu/WarBugs#16506]
**The WB did wipe several times, however once final boss was killed a number of us didn't get contribution rolls or bags at the end. The PQ just went straight to the reset timer for us.**

**Try wiping multiple times before completion**

**Testing Screenshots/Videos/Evidences (always needed):**

Sorry I didn't take one until after I'd spoken to a GM, best I can do. I'm aware it doesn't constitute much and I'm aware there won't be any restitution, but there does seem to be a recurring bug.
![Byrnt_001](https://user-images.githubusercontent.com/51724523/80286452-897ef900-86f9-11ea-896d-dfa3696f5d55.jpg)

**Comment by Kaelang** [comment]
Hi - I'm going to merge this with the other two open CH22 'no bag roll' tickets so I can manage the reports better.

Please see https://github.com/WarEmu/WarBugs/issues/15569 and https://github.com/WarEmu/WarBugs/issues/15132.

Thank you for the report.

Closed.
