### ISSUE TITLE
Keep/Fort doors

### ISSUE THREAD

**Issue by ZendrikEH** [WarEmu/WarBugs#16502]
When playing RP and maybe other classes that have a tac to make abilitys undefendable ( potent runes on rp ) you can do keep/fort door dmg on my RP its around 2% per 15 seks

**Steps to reproduce the problem:**
slot Potent Runes in tactic bar then dot a keep/fort door
you can dmg the fort door with this bug

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by ZendrikEH** [comment]
note: i can kill a keep door solo with no ram =P

**Comment by ZendrikEH** [comment]
I am ingame on Apoteket if you have any questions

**Comment by Kaelang** [comment]
If you have screenshots / videos, please can you provide them?

**Comment by ZendrikEH** [comment]
Yeah ull sens it as soon as i comeback

Skickat från min iPhone

25 apr. 2020 kl. 14:22 skrev Kaelang <notifications@github.com>:

﻿

If you have screenshots / videos, please can you provide them?

**Comment by ZendrikEH** [comment]
Seems like singel target spells to keep doors was been patched while i was gone.
It was an easy bug to reproduce though, ill see if it works later.

Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows 10

Från: Kaelang<mailto:notifications@github.com>
Skickat: den 25 april 2020 14:22
Till: WarEmu/WarBugs<mailto:WarBugs@noreply.github.com>
Kopia: ZendrikEH<mailto:zendrik@hotmail.com>; Author<mailto:author@noreply.github.com>
Ämne: Re: [WarEmu/WarBugs] Keep/Fort doors (#16502)


If you have screenshots / videos, please can you provide them?

**Comment by ZendrikEH** [comment]
have some pics now 
![Apoteket_000](https://user-images.githubusercontent.com/64303726/80286352-49d10500-872b-11ea-80a0-33d46fd7ca50.jpg)
![Apoteket_001](https://user-images.githubusercontent.com/64303726/80286353-4b023200-872b-11ea-9f47-6bab3350f8e1.jpg)
![Apoteket_002](https://user-images.githubusercontent.com/64303726/80286356-4b023200-872b-11ea-81ee-ed18f58ab778.jpg)
![Apoteket_003](https://user-images.githubusercontent.com/64303726/80286357-4b9ac880-872b-11ea-9387-83266a1bb06a.jpg)
![Apoteket_004](https://user-images.githubusercontent.com/64303726/80286358-4b9ac880-872b-11ea-8921-8145c0dd65f1.jpg)
![Apoteket_005](https://user-images.githubusercontent.com/64303726/80286359-4c335f00-872b-11ea-8746-5d32057e735f.jpg)
![Apoteket_006](https://user-images.githubusercontent.com/64303726/80286360-4c335f00-872b-11ea-8489-612885718ab8.jpg)
![Apoteket_007](https://user-images.githubusercontent.com/64303726/80286362-4ccbf580-872b-11ea-960b-e9018419c5d7.jpg)
![Apoteket_008](https://user-images.githubusercontent.com/64303726/80286363-4ccbf580-872b-11ea-81f2-f20e3beed58e.jpg)
![Apoteket_009](https://user-images.githubusercontent.com/64303726/80286364-4d648c00-872b-11ea-9e36-a81cc1f21ddd.jpg)
![Apoteket_010](https://user-images.githubusercontent.com/64303726/80286365-4d648c00-872b-11ea-9d45-1d30b67d4d12.jpg)
![Apoteket_011](https://user-images.githubusercontent.com/64303726/80286366-4d648c00-872b-11ea-8267-28b07631a06d.jpg)
![Apoteket_012](https://user-images.githubusercontent.com/64303726/80286367-4dfd2280-872b-11ea-9172-ba970cfd2548.jpg)
![Apoteket_013](https://user-images.githubusercontent.com/64303726/80286368-4dfd2280-872b-11ea-9b2e-8e1185aa6cae.jpg)

**Comment by ZendrikEH** [comment]
im not doing full dmg either with dps on i can do around 200-300 dmg per tic

**Comment by ZendrikEH** [comment]
![Apoteket_014](https://user-images.githubusercontent.com/64303726/80288958-de436380-873b-11ea-8d60-775e6f2615c0.jpg)
![Apoteket_015](https://user-images.githubusercontent.com/64303726/80288959-df749080-873b-11ea-9b35-8254374e0f5e.jpg)
![Apoteket_016](https://user-images.githubusercontent.com/64303726/80288961-df749080-873b-11ea-9dfd-ee63cc75140f.jpg)
![Apoteket_017](https://user-images.githubusercontent.com/64303726/80288962-e00d2700-873b-11ea-8479-6568e9f1ac52.jpg)
![Apoteket_018](https://user-images.githubusercontent.com/64303726/80288963-e00d2700-873b-11ea-92fa-7c557fb611f4.jpg)
![Apoteket_019](https://user-images.githubusercontent.com/64303726/80288964-e0a5bd80-873b-11ea-820b-2cc4f81e0f9b.jpg)
![Apoteket_020](https://user-images.githubusercontent.com/64303726/80288965-e0a5bd80-873b-11ea-99d6-f95181d006dd.jpg)
![Apoteket_021](https://user-images.githubusercontent.com/64303726/80288966-e0a5bd80-873b-11ea-974e-a4da4524417c.jpg)
![Apoteket_022](https://user-images.githubusercontent.com/64303726/80288967-e13e5400-873b-11ea-93bd-c8be86cd2a7d.jpg)
![Apoteket_023](https://user-images.githubusercontent.com/64303726/80288968-e13e5400-873b-11ea-8605-a52e76422a9e.jpg)
![Apoteket_024](https://user-images.githubusercontent.com/64303726/80288969-e1d6ea80-873b-11ea-8cbd-1c8cebcf502f.jpg)
![Apoteket_025](https://user-images.githubusercontent.com/64303726/80288970-e1d6ea80-873b-11ea-95af-f9e4fae80277.jpg)
![Apoteket_026](https://user-images.githubusercontent.com/64303726/80288971-e26f8100-873b-11ea-99e8-bd9813781659.jpg)
![Apoteket_027](https://user-images.githubusercontent.com/64303726/80288972-e26f8100-873b-11ea-8f3e-aa308daa51ab.jpg)
![Apoteket_028](https://user-images.githubusercontent.com/64303726/80288973-e26f8100-873b-11ea-871d-1fcaa5d6722e.jpg)
![Apoteket_029](https://user-images.githubusercontent.com/64303726/80288974-e3081780-873b-11ea-931e-88a1cccde4ad.jpg)
![Apoteket_030](https://user-images.githubusercontent.com/64303726/80288975-e3081780-873b-11ea-8b9a-d85c44b60802.jpg)
![Apoteket_031](https://user-images.githubusercontent.com/64303726/80288977-e3a0ae00-873b-11ea-94d0-8062e7898e27.jpg)
![Apoteket_032](https://user-images.githubusercontent.com/64303726/80288978-e3a0ae00-873b-11ea-9833-12991ef32e4c.jpg)
![Apoteket_033](https://user-images.githubusercontent.com/64303726/80288979-e4394480-873b-11ea-903a-2ade01c1a326.jpg)
![Apoteket_034](https://user-images.githubusercontent.com/64303726/80288980-e4394480-873b-11ea-8792-14f054be0de9.jpg)
![Apoteket_035](https://user-images.githubusercontent.com/64303726/80288981-e4394480-873b-11ea-99da-0b073c567ca7.jpg)
![Apoteket_036](https://user-images.githubusercontent.com/64303726/80288982-e4d1db00-873b-11ea-9487-499ba877219d.jpg)
![Apoteket_037](https://user-images.githubusercontent.com/64303726/80288983-e4d1db00-873b-11ea-9c8d-ef23216345c5.jpg)
![Apoteket_038](https://user-images.githubusercontent.com/64303726/80288984-e56a7180-873b-11ea-93a3-3196f0bca16c.jpg)
![Apoteket_039](https://user-images.githubusercontent.com/64303726/80288985-e56a7180-873b-11ea-8e98-16a0cbfd802b.jpg)
![Apoteket_040](https://user-images.githubusercontent.com/64303726/80288986-e56a7180-873b-11ea-979b-d14f4991ae1b.jpg)
![Apoteket_041](https://user-images.githubusercontent.com/64303726/80288987-e6030800-873b-11ea-9dd7-dba40e755fea.jpg)
![Apoteket_042](https://user-images.githubusercontent.com/64303726/80288988-e6030800-873b-11ea-9408-573f691d28f5.jpg)
![Apoteket_043](https://user-images.githubusercontent.com/64303726/80288989-e69b9e80-873b-11ea-9965-1f6678b30f9a.jpg)
![Apoteket_044](https://user-images.githubusercontent.com/64303726/80288990-e69b9e80-873b-11ea-886b-918c75d6fdb7.jpg)
![Apoteket_045](https://user-images.githubusercontent.com/64303726/80288991-e7343500-873b-11ea-9486-ffd74fe64b85.jpg)

**Comment by ZendrikEH** [comment]
i have no pics on fort door but it does work there as well

**Comment by Kaelang** [comment]
This is great - thank you for supply these.

**Comment by ZendrikEH** [comment]
![Apoteket_046](https://user-images.githubusercontent.com/64303726/80289845-c1119380-8741-11ea-8208-646a5c8372cf.jpg)
![Apoteket_047](https://user-images.githubusercontent.com/64303726/80289846-c242c080-8741-11ea-8a03-8396101309fc.jpg)

**Comment by ZendrikEH** [comment]
ah oki works on all forts so far and its alot of dmg around 2% per 15 seks and it works on forts as well. ill stop taking screenshots now =)

**Comment by ZendrikEH** [comment]
just a quick update so that you can see that it works on forts

**Comment by Kaelang** [comment]
![image](https://user-images.githubusercontent.com/60117106/80747591-9ba6d000-8b1b-11ea-9a63-601de08d26bd.png)

Additional screenshot to be used whilst investigating.

**Comment by Kaelang** [comment]
This should have been fixed after the recent hotfix.

Cheers for the report.

**Comment by ZendrikEH** [comment]
![Apoteket_053](https://user-images.githubusercontent.com/64303726/81120736-a0a9bc00-8f2d-11ea-8281-5bf321ab3098.jpg)
![Apoteket_054](https://user-images.githubusercontent.com/64303726/81120740-a1dae900-8f2d-11ea-9297-66be6517f6e0.jpg)
![Apoteket_055](https://user-images.githubusercontent.com/64303726/81120742-a2737f80-8f2d-11ea-9359-8156bc8a6785.jpg)
![Apoteket_056](https://user-images.githubusercontent.com/64303726/81120743-a2737f80-8f2d-11ea-9ec0-49bbc074fdf7.jpg)
![Apoteket_057](https://user-images.githubusercontent.com/64303726/81120744-a30c1600-8f2d-11ea-909f-8b99ad19fae3.jpg)
![Apoteket_058](https://user-images.githubusercontent.com/64303726/81120747-a30c1600-8f2d-11ea-99cb-9738b54e49f3.jpg)
![Apoteket_059](https://user-images.githubusercontent.com/64303726/81120748-a3a4ac80-8f2d-11ea-889d-d7bdaca40b4c.jpg)
![Apoteket_060](https://user-images.githubusercontent.com/64303726/81120750-a3a4ac80-8f2d-11ea-910e-6c1a333c0ec9.jpg)
![Apoteket_061](https://user-images.githubusercontent.com/64303726/81120751-a43d4300-8f2d-11ea-9b2f-d33993db8c5a.jpg)
![Apoteket_062](https://user-images.githubusercontent.com/64303726/81120753-a43d4300-8f2d-11ea-8cae-f7ca8890bb4d.jpg)
![Apoteket_063](https://user-images.githubusercontent.com/64303726/81120754-a4d5d980-8f2d-11ea-95bd-cfba1cd1bd54.jpg)
![Apoteket_064](https://user-images.githubusercontent.com/64303726/81120755-a4d5d980-8f2d-11ea-81d9-c8f532919415.jpg)
![Apoteket_065](https://user-images.githubusercontent.com/64303726/81120757-a56e7000-8f2d-11ea-9423-07fba360dd06.jpg)
![Apoteket_066](https://user-images.githubusercontent.com/64303726/81120759-a56e7000-8f2d-11ea-9258-9b9491d06f58.jpg)
![Apoteket_067](https://user-images.githubusercontent.com/64303726/81120760-a6070680-8f2d-11ea-8624-f55903c8ebf2.jpg)
![Apoteket_068](https://user-images.githubusercontent.com/64303726/81120761-a6070680-8f2d-11ea-8e25-5bebac535351.jpg)
![Apoteket_069](https://user-images.githubusercontent.com/64303726/81120762-a69f9d00-8f2d-11ea-8ebb-10eb125982ba.jpg)
![Apoteket_070](https://user-images.githubusercontent.com/64303726/81120763-a69f9d00-8f2d-11ea-8f98-e9315ccb4533.jpg)
![Apoteket_071](https://user-images.githubusercontent.com/64303726/81120764-a7383380-8f2d-11ea-8a5b-af318762f0a5.jpg)
![Apoteket_072](https://user-images.githubusercontent.com/64303726/81120766-a7383380-8f2d-11ea-813a-73139c6925f9.jpg)
![Apoteket_073](https://user-images.githubusercontent.com/64303726/81120769-a7d0ca00-8f2d-11ea-9b45-70945ca12304.jpg)
![Apoteket_074](https://user-images.githubusercontent.com/64303726/81120770-a7d0ca00-8f2d-11ea-861b-7b80d393957b.jpg)
![Apoteket_075](https://user-images.githubusercontent.com/64303726/81120772-a8696080-8f2d-11ea-9ed0-be1e799e51c1.jpg)
![Apoteket_076](https://user-images.githubusercontent.com/64303726/81120776-a8696080-8f2d-11ea-9d7e-245442f3b031.jpg)
![Apoteket_077](https://user-images.githubusercontent.com/64303726/81120779-a901f700-8f2d-11ea-9047-0c26bd94512b.jpg)
![Apoteket_078](https://user-images.githubusercontent.com/64303726/81120780-a901f700-8f2d-11ea-8bdc-3da57f4e91ad.jpg)
![Apoteket_079](https://user-images.githubusercontent.com/64303726/81120781-a99a8d80-8f2d-11ea-9d02-024b6a16adb1.jpg)
![Apoteket_080](https://user-images.githubusercontent.com/64303726/81120782-a99a8d80-8f2d-11ea-9166-ddc4615fe886.jpg)
![Apoteket_081](https://user-images.githubusercontent.com/64303726/81120785-a99a8d80-8f2d-11ea-831f-ec7134a3cd05.jpg)
![Apoteket_082](https://user-images.githubusercontent.com/64303726/81120787-aacbba80-8f2d-11ea-965b-4639fe5c194e.jpg)
![Apoteket_083](https://user-images.githubusercontent.com/64303726/81120792-ab645100-8f2d-11ea-93fe-7f0aaefacf1b.jpg)
![Apoteket_084](https://user-images.githubusercontent.com/64303726/81120793-abfce780-8f2d-11ea-88df-99ad54e99e01.jpg)
![Apoteket_085](https://user-images.githubusercontent.com/64303726/81120794-abfce780-8f2d-11ea-8921-3277488c79db.jpg)
![Apoteket_086](https://user-images.githubusercontent.com/64303726/81120796-ac957e00-8f2d-11ea-939b-11b9aa70f10f.jpg)
![Apoteket_087](https://user-images.githubusercontent.com/64303726/81120799-ad2e1480-8f2d-11ea-8ba7-c62142380190.jpg)
![Apoteket_088](https://user-images.githubusercontent.com/64303726/81120800-ad2e1480-8f2d-11ea-9cec-369ef12f821b.jpg)
![Apoteket_089](https://user-images.githubusercontent.com/64303726/81120801-ad2e1480-8f2d-11ea-9142-87da1633d124.jpg)
![Apoteket_090](https://user-images.githubusercontent.com/64303726/81120803-adc6ab00-8f2d-11ea-84b9-5b488aa46bc1.jpg)

still works just fine , unless its a feature =)
