### ISSUE TITLE
No bag roll for two failed defences in Talabecland and The shadowlands.

### ISSUE THREAD

**Issue by Dixbe** [WarEmu/WarBugs#16508]
Today I have spent defending both Talabecland and The Shadowlands from the very start after city siege was over. 

I lead a warband through out this and was in each zone from the very starts, we took BO and I ran supplies as well as getting numerous kills. 

I would expect to either get:
1: A loot bag roll
2 :A message saying I didn't get a roll but my chances of getting one next time has been increased
3: A bag of cow poop. 

I did not get any of what is to be expected but I did get the Renown after we lost the areas.

Unfortunately I haven't got a screenshot of the chat log to show that I didn't get an increase for the next roll as I was advised by people to log off and close the launcher and log back in as that has sorted the issue for them in the past. (it has not for me)

**Comment by Kaelang** [comment]
I appreciate the frustration, however I'd need more information to do anything with this reliably. Screenshots of chat logs i.e. Renown ticks but nothing else. State of zones, for example AAO. Time spent in zones, what you was doing...

Did anyone else in the WB / area get rolls or was it just you?

I'll keep this open with a 2 week ultimatum. If you're experiencing this frequently, please collect evidence to support the issue within the next 2 weeks for me to tag this up and investigate accordingly.

Cheers.

**Comment by Dixbe** [comment]
I have gone through the game files and the chat logs don't save I take it?

As I will not be able to provide whats needs you can close this ticket. I will make sure if this happens again I will have all the evidence needed. 

Sorry for wasting time.

**Comment by Kaelang** [comment]
It's usually best to have screenshots or videos just to support claims - essentially so when we look to replicate we have the most information to go off. There really isn't much evidence here to support the team if they look to replicate on test.

I will go ahead and close this for the time being, but as mentioned if this happens again, grab a few screenshots and re submit the issue and I'll tag it up accordingly.

Thank you.
