### ISSUE TITLE
No bag recived

### ISSUE THREAD

**Issue by Jacobb1993** [WarEmu/WarBugs#16519]
Hi, I'm Jacobb and this oring at 12.56 I didn't recive a blue ag in my mail box. I write here cause I'm still waiting for recive a golden bag looted few days ago. Please let me know.
Issues should be unique. Check if someone else reported
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.
-->

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
What did you win the bag from? Usually there's a delay in the delivery service and a server restart / patch will typically fix the problem.

I'll tag this up and wait for the next patch / reset. Please can you confirm if you receive the bag following this.

Thanks.

**Comment by Kaelang** [comment]
Closing no further information given.
