### ISSUE TITLE
Tor Anroc - Multiple Quest Hand Ins

### ISSUE THREAD

**Issue by TaskUK** [WarEmu/WarBugs#16517]
I have experienced at least twice today the quest giver offering multiple quests for "Win Tor Anroc Scenario" on my character Isenheim (Dwarf Engie)

I was also able to hand the quest  in twice, one after the other at Altdorf fdr rewards.

**Expected behavior and actual behavior:**
Clicking on the quest giver shows the same quest offered twice, although it can only be accepted once.

**Steps to reproduce the problem:**
Approach and click quest giver, no other explanation, unsure why it occured

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Have you levelled through brackets? One quest could be from T1, the second quest from T2?

Please can you provide screenshots.

**Comment by TaskUK** [comment]
No I am T2, levelled 18 - 20 this AM, quest wasn't in log, i'll see if it reproduces this afternoon while i'm grinding SC's

**Comment by Kaelang** [comment]
Closing no further information given.
