### ISSUE TITLE
Typo in Emperor Karl Franz NPC dialogue

### ISSUE THREAD

**Issue by Deifact** [WarEmu/WarBugs#16515]
**Expected behavior and actual behavior:**
Speaking to Emperor Karl Franz, he says "I think Sigmar for every [Witch Hunter] that stands to defend the Empire.", presumably he is meant to say "I thank Sigmar for every [Witch Hunter] that stands to defend the Empire".

**Steps to reproduce the problem:**
Speak to Emperor Karl Franz NPC until he reaches the dialogue. I've not tested with other classes.

**Testing Screenshots/Videos/Evidences (always needed):**

![Nethic_000](https://user-images.githubusercontent.com/5096126/80304297-cf48c980-87ac-11ea-8fc1-e674ac45bec2.jpg)

**Comment by Kaelang** [comment]
As of 29/04/2020 this should now be fixed. Please re-open if issues persist.
