### ISSUE TITLE
[WP] Cleansing Power not making Purify cleanse group when targeting self

### ISSUE THREAD

**Issue by Rydiak** [WarEmu/WarBugs#16520]
While you have yourself targeted and cast Purify with Cleansing Power tactic slotted, you will only cleanse yourself.  While you have a group member targeted and cast Purify with Cleansing Power tactic slotted, you will cleanse the group _including_ yourself.

**Comment by CornerbackAC** [comment]
Same for DoK

**Comment by Rydiak** [comment]
This was not fixed in the 01/15/21 patch, just a heads up.

**Comment by Rydiak** [comment]
Fixed with a recent patch
