### ISSUE TITLE
[Choppa] Shrug it Off ability not working as intended.  

### ISSUE THREAD

**Issue by Jabbawockee84** [WarEmu/WarBugs#16528]
It creates no immunity to snares as it describes.  As melee I'm constantly CC'd.  This is obviously not working properly.  Tbh the ability should remove all CC; disable, knockdowns, disarm, snares, everything and then make player immune to CC for the 10 seconds.  It has a 60 second cooldown.  For a melee dps to actually dps for 1/6 of a fight isn't too much to ask.

**Comment by grunbag** [comment]
It prevent you to be cc , but it doesn’t remove a cc from you .

**Comment by Jabbawockee84** [comment]
> It prevent you to be cc , but it doesn’t remove a cc from you .

In my experience it certainly doesn't prevent any CC.  

Regardless, the ability description states it removes and prevents.  Which it does not.  I'm confident any Choppa who pays attention to their action bar would agree the ability is not working as intended.

**Comment by Kaelang** [comment]
Can you screenshot and supply the tooltip please?

**Comment by Kaelang** [comment]
Also - if possible, a video showing you using the ability, then being hit by a CC ability would really help here.

**Comment by Kaelang** [comment]
Closed - no further information.
