### ISSUE TITLE
Shooting players in rvr from camp without bolster leads to really weird numbers

### ISSUE THREAD

**Issue by Garrthax** [WarEmu/WarBugs#16522]
i think my lvl 19 shaman is broken ... and yes, that was actual damage
![image](https://user-images.githubusercontent.com/49390790/80317964-2a0f0f00-8807-11ea-9c82-8eff5f8ada4d.png)

**Comment by Kaelang** [comment]
Which RvR camp was you in?

**Comment by Garrthax** [comment]
eataine destro camp

**Comment by wargrimnir** [comment]
Stay away from enemy warcamps. That's intended.
