### ISSUE TITLE
No Contribution for Fort

### ISSUE THREAD

**Issue by Doomgrack** [WarEmu/WarBugs#16523]
**Expected behavior and actual behavior:**
Get contribution for fort. Game was unable to distribute contribution.

**Steps to reproduce the problem:**
I'm lvl 34 runepriest. I was on a tower of the fort of shining way. the keep lord of Eataine was going down. I was teleported to the fort waiting area and got the message that my contribution couldn't be allocated and I should submit a ticket.

**Testing Screenshots/Videos/Evidences (always needed):**

chat moved on too quickly.

**Comment by Kaelang** [comment]
If you was teleported out of the fort, you wasn't given a reservation. That being said, Shining Way has currently bugged out and the team are investigating what's happened - so this is likely an additional cause of the problem. 

I appreciate the report, however without screenshot evidence as to what the message said and/or steps to replicate such problem, there isn't necessarily anything we can do here. 

This being said, this sounds extremely similar to this report https://github.com/WarEmu/WarBugs/issues/16409 so I am going to close this up for now.

Thank you.
