### ISSUE TITLE
Magus: Blue Horror allows casting while moving

### ISSUE THREAD

**Issue by Ghoulsucc** [WarEmu/WarBugs#16529]
Magus' Blue Horror is not supposed to enable "cast while moving" on Path of Changing abilities. Currently Rend Winds, Pandemonium, Warping Blast, and Surge of Insanity can all be cast while moving.

This works on enemy mobs, players, and target dummies.

Video evidence: https://www.youtube.com/watch?v=7kgIrhAzmYY

**Comment by Kaelang** [comment]
Seems this was ping related - no longer happens, tested. Please re-open if you're still able to replicate this issue and I'll have a deeper look.
