### ISSUE TITLE
Some fragments for crafting don't work + remove the Essences + Curio when trying to select it

### ISSUE THREAD

**Issue by detrap** [WarEmu/WarBugs#16527]
Some fragments for crafting don't work + remove the Essences + Curio when trying to select it.

![Untitled](https://user-images.githubusercontent.com/64330047/80345092-ef12e700-88ab-11ea-812a-1eecf1bc7b66.png)

**Comment by Kaelang** [comment]
Are you able to record an evidence as to what you're doing and what happens? This doesn't really give me much to work with.

**Comment by Kaelang** [comment]
No additional information provided. Closing.
