### ISSUE TITLE
Drakebreaker Scourge keep doors are stuck trap after being destroyed

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#16525]
Some day we defended Drakebreaker Scourge (DW left keep) and I've got pulled outside by (I believe) choppa's pull.
But, my flight got finished inside one of the doors, so I was out of healers LOS to heal/res, but still being able to be attacked or healed by nontarget AOE skills.
I wasn't able to walk out of that door too.

_Pretty sure, most keeps has the same problem: after being destroyed, keep doors remains in the opened state, rather than just disappear and this lead to weird stuff, when players got trapped inside of it with pull skills._

**Expected behavior and actual behavior:**
Exp: destroyed doors are not traps for pulled players
Act: they are

**Steps to reproduce the problem:**
Break some keep door, pull your enemy inside of it

**Testing Screenshots/Videos/Evidences (always needed):**
![2020 04 26-03 12](https://user-images.githubusercontent.com/16439840/80327888-35cdf600-8846-11ea-9e13-262452201b0e.jpg)

Here I'm laying down inside of door (door texture aren't visible from inside) and healers can't see me (out of LOS) to res

**Comment by Kaelang** [comment]
Cheers for the report - this is a duplicate however of the report here: https://github.com/WarEmu/WarBugs/issues/12350

Closed.
