### ISSUE TITLE
Shining Way Jail Engineer Turrets work

### ISSUE THREAD

**Issue by Waaghnita** [WarEmu/WarBugs#16533]
**Expected behavior and actual behavior:**
I was in Jail at Shining Way and I was able to drop Engineer machine gun Turret and Flame turret. It worked very well. I could not shoot anyone with my weapon in hands. But my turrets killed to players. Are we supposed to be able to drop turrets in Jail?
April 27, 2020 11:05 EST.

**Steps to reproduce the problem:**
Be an Order Engineer and drop Turret in Shining Way Jail. I dropped the crate and it opened up and started shooting. I am sorry, I just felt like a jerk after it killed to Destro that were AFK. I was not sure if this is working as intended or broken? I have never tried to drop a turret in jail before.

**Testing Screenshots/Videos/Evidences (always needed):**

Sorry, I did not take any screen shots but I am sure you will be told it happened.

**Comment by Kaelang** [comment]
The jail / gag ability is now working as intended. Tried to replicate this and was unable to spawn any towers / attack anything.

Please re-open if this issue persists.
