### ISSUE TITLE
No Invaders/Royal Crest for Successful Defense of Reikwald

### ISSUE THREAD

**Issue by SetchDreskar** [WarEmu/WarBugs#16534]
The Reikwald defense at 11:30 Eastern Time [US] had me crash several times during it, but managed to get back to the defense twice from the crash, on the third time though I was put in the PvE area of Reikwald, had to travel back through altdorf and into Reikwald fort again, where I was killed instantly by destro.

I spent the remainder of the siege after surviving and helping to hold off three pushes, in jail. When we won the fort I was not given any invaders or royal crest for a successful defense of the fortress. I instead only received the 2 vanquishers and paragons.

My name is Setch in game if you need to see activity log of being in fort.

**Comment by Kaelang** [comment]
Do you have a screenshot of the 'rewards' being handed out at the end of the fort? I'd need to see what your ticks looked like alongside any rewards given.

**Comment by SetchDreskar** [comment]
Unfortunately no, so don't worry about giving the intended rewards just
noting it as a bug since forts seem to be really crash happy and making it
back in may lose you the medallions and crest you need.

**Comment by Kaelang** [comment]
Appreciate the frustration - but stability is something the team are working on consistently. There's a lot of resources to help with stability client-side on the forums if you believe you're experience more crashes than normal. 

As there's no information here to assist replicating crashing within forts, I'm going to close this one up. 

Thanks.

**Comment by SetchDreskar** [comment]
Well we may have come up with what might be doing it within our group, the
enemy addon though we can not 100% confirm it, those of us in the group
using said addon have had the crashes and those without have not. It will
take more testing obviously but we will see now that we have switched to
Squared if, for whatever reason, Enemy was the culprit.
