### ISSUE TITLE
Not enough contribution in Butcher's Pass defense

### ISSUE THREAD

**Issue by Portense** [WarEmu/WarBugs#16539]
I was in a 6 man group with guild members and we were on the defense. We played along the walls and tried to hold the front BOs. The gate dropped fast, and we were forced to go inside. The next stage, we defended postern and died when main was pushed along with everyone in the fort. In jail after the zone locked, we got a message saying, "Not enough contribution" and did not receive our 4 invader medallions.

**Comment by Kaelang** [comment]
I'd need a screenshot of the error message that you received. As well as whether or not you was reserved and/or how much you partook in the overall siege.

Can't do much with this report as it stands, so if you're able to provide more information that'd be great.

**Comment by Portense** [comment]
I don't have a screenshot, but we all had reservations. We played the entire duration of the fort, and no one AFKed.

**Comment by Kaelang** [comment]
Any yellow messages at all throughout?

**Comment by Portense** [comment]
No yellow message. The message was gray for me.

**Comment by Kaelang** [comment]
Personally - it sounds like you didn't contribute enough. If you're a 6 man on the walls as there's fights happening everywhere. And then you immediately die on the first push - you really didn't do anything in the fort. Tip: In stage 1, get as many tags as possible as opposed to waiting to try and cap flags.

Closing.
