### ISSUE TITLE
[PvE] BE boss Barakus - no armour buff in phase 3

### ISSUE THREAD

**Issue by elk76** [WarEmu/WarBugs#16536]
The last boss Barakus in BE does not trigger the armour buff at 30%
The screen text pop but no buff on him (so you do not need the Claw)

![Hamund_101](https://user-images.githubusercontent.com/46483570/80464768-8fafe800-893a-11ea-99f6-50a89d63b437.jpg)

**Comment by Kaelang** [comment]
BE has since been reworked, please re-open if issue persists.
