### ISSUE TITLE
Chapter 22 PQ Bug

### ISSUE THREAD

**Issue by originalcutie00** [WarEmu/WarBugs#16531]
I did lead 2 chapter 22 PQ's, the one in Reikland and the one in Eataine. After 1 wipe, we succeeded in killing the bosses and they didn't give loot to 90% of the warband. 2 people would get a roll but no one else got the loot.

**Comment by Kaelang** [comment]
Sounds similar to the report here: https://github.com/WarEmu/WarBugs/issues/15569

Typically looks to be related to deaths / wipes resetting contribution. 

I'll close this to keep things concise.
