### ISSUE TITLE
Reikwald fort bug text?

### ISSUE THREAD

**Issue by KySaber** [WarEmu/WarBugs#16535]
As per the screenshot, not sure what's going on, but I got a reservation and this message:
![11111](https://user-images.githubusercontent.com/26847385/80453179-18df1300-896b-11ea-8eb7-1e6b2a5cf38f.png)

Cheers!
Tes

**Comment by Kaelang** [comment]
Duplicate of https://github.com/WarEmu/WarBugs/issues/16409.
