### ISSUE TITLE
[NPC] Flight Masters in Destruction and Order Warcamps on the ground.

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#16548]
**Expected behavior and actual behavior:**

Expected:
All Flight Masters in Wracamps should hang in the air in order to easy click & travel for players.
Additionally I would place them 5ft lower for easier click when You are close with the whole bunch of players.

Actual:
Flight Masters in Destruction Warcamps in Ostland, Chaos Wastes, Praag are on the ground.
Flight Masters in Order Warcamps In Troll Country, Badlands, 

**Steps to reproduce the problem:**

Go to Warcamps mentioned above

**Testing Screenshots/Videos/Evidences (always needed):**

![WAR-64 2020-04-29 14-31-21](https://user-images.githubusercontent.com/18528095/80595322-d37f1c00-8a24-11ea-87d9-da46419f0997.png)
![WAR-64 2020-04-29 14-08-46](https://user-images.githubusercontent.com/18528095/80595303-cc580e00-8a24-11ea-80bc-f1d8b631138e.png)
![WAR-64 2020-04-29 14-29-05](https://user-images.githubusercontent.com/18528095/80595314-cfeb9500-8a24-11ea-806e-56c6fc85443e.png)
![WAR-64 2020-04-29 14-37-57](https://user-images.githubusercontent.com/18528095/80595445-0b865f00-8a25-11ea-8101-4fddad989311.png)
![WAR-64 2020-04-29 14-38-16](https://user-images.githubusercontent.com/18528095/80595458-0f19e600-8a25-11ea-8c34-383e06498621.png)

**Comment by Kaelang** [comment]
Should be fixed in 06/05/20 patch - please re-open if issues persist.

**Comment by StaH84** [comment]
I will check. Thank You.
If I check the Flight Mastera in War story chapters and report, will You fix them too?

**Comment by Kaelang** [comment]
@Lheana

**Comment by Lheana** [comment]
You can but:

- It's on the todo-list of the DB team to make them fly, so we are already aware of it
- And you'll need to create one ticket per flight master
