### ISSUE TITLE
City Stage 3 Mail_Bug// Sticky FeeTZ buggy!

### ISSUE THREAD

**Issue by hahrss** [WarEmu/WarBugs#16544]
Hi today i joned Uc city defence. And i didnt get my mayor loot bag in step 3 from the mailbox. And i hope i get new post with 4 Royalcrest because last city my full warband didnt get tokens and mail from step 3. (like 5 Days ago ) i hope their is a chance to get my mail cured and safe. (1 time Mail dont work for me) Thanks

Another thing ...Sticky feetz (jumping back from the class Squig Herder) didnt work like a couple Weeks or Mounths -> against WL-Pull (he always was working well to aviod WL PULL. i even cant cast the spell on the way to WL??why??) ..and the spell is a lot weaker to get away from players...so lets say the spells actuelly dont work well. Casting the spell give you cooldown from the spell but dont hit the enemy. Or you are stunnend. Form tank or whatever...and i mean the spell (like 4 months ago) was always working well. Sticky Feetz was a always a nice spell to aviod death..now its a lame spell wo dont work. I can send Material+ Video i you wish. How the Spells works now. Check it out please...so actuelly if you spell the cast right to a group you get cooldown from sticky feetz. But you get stunnend..so you get cooldown dont slow the group you are stunnd and likley dead with stun and you get cooldown on you sticky feetz and do not effect enemy group. ok i hope you take it serious. 

(lets say in all Sticky feetz need a little gets Fast again or something like this) 

Thanks a lot Hahrss 
Saludos ! 

(i can give Link from Zarbix stream with Lootbag step 3 i you wish)

**Comment by Kaelang** [comment]
There's two reports here, and neither of them have enough information / evidence to support the message you're trying to convey.

Please open two separate reports for each issue, with supporting screenshots / videos so that I can look into them properly.

Thanks.
