### ISSUE TITLE
Marauder Deeply Implated Tactic

### ISSUE THREAD

**Issue by baisus1995** [WarEmu/WarBugs#16540]
![Vykings_003](https://user-images.githubusercontent.com/64501044/80538870-1b635c00-89af-11ea-8bd6-04eef70bc460.jpg)
Deeply Implated Tactic Works Only on Brutality mutation
![Vykings_002](https://user-images.githubusercontent.com/64501044/80536948-d8ec5000-89ab-11ea-837e-51eb759a7291.jpg)

**Comment by Kaelang** [comment]
Screenshot of tactic please.

**Comment by Teefz** [comment]
![impale](https://user-images.githubusercontent.com/18510648/80620275-10a7d600-8a46-11ea-9ced-c1b4897c9f87.jpg)

@baisus1995 - It works. Like it should.

**Comment by Kaelang** [comment]
Confirmation please. @baisus1995

**Comment by baisus1995** [comment]
ye i didnt check that skill name ,my bad
