### ISSUE TITLE
[AM/Shaman] Energy of Vaul does not heal targets around caster if caster is the defensive target.

### ISSUE THREAD

**Issue by aralion1** [WarEmu/WarBugs#16545]
Tested by targeting self around two realm allies, and then one of them. 

![Sefir_009](https://user-images.githubusercontent.com/5519900/80559289-17353f80-89ab-11ea-8048-46ebe1818016.jpg)
![Sefir_010](https://user-images.githubusercontent.com/5519900/80559291-18666c80-89ab-11ea-9ce4-0f45f861403a.jpg)

**Comment by keunglh** [comment]
Reported here - https://github.com/WarEmu/WarBugs/issues/16309

**Comment by Kaelang** [comment]
> Reported here - #16309

Thanks - couldn't find this. Wasn't searching for EoV. 

Closing. 

Merged w/ https://github.com/WarEmu/WarBugs/issues/16309
