### ISSUE TITLE
Beastlord Bramble Witch heals no matter what

### ISSUE THREAD

**Issue by Andical** [WarEmu/WarBugs#16549]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

My character is Greygan, I have been trying to kill witch 2h now with different groups.
We know the strategy, we knock her down on Succumb phrase and taunt on SEEDS phrase.
But doesnt matter if we taunt instantly as shown in the video (my key 3) or right after, she heals no matter what. Can you please give the people shown in video the quest done? thanks
https://streamable.com/k9c569

**Comment by wargrimnir** [comment]
She can absolutely be beaten, if you need assistance, ask other players who have done so.
