### ISSUE TITLE
Healer sovereign - same granted ability?

### ISSUE THREAD

**Issue by Teefz** [WarEmu/WarBugs#16554]
From the Patch Notes 22/04/2020, which added the 'new' granted abilities for classes. There seems to be problem with the distribution of the granted abilities: (I haven't checked the order version, but I guess it might be the same issue)

DOK: Reaping - You instantly regain 120 Soul Essence.
Shammy: Absolute Preservation - You and your defensive target cannot be critically hit for 10 s.
Zealot: Favor of Tzeentch - A brief magical wind increases your chance to critically hit and heal by 10% for 10 seconds.

![dok sov](https://user-images.githubusercontent.com/18510648/80624313-c6c1ee80-8a4b-11ea-9ec2-208a1fc8de05.jpg)
![sham sov](https://user-images.githubusercontent.com/18510648/80624322-c9bcdf00-8a4b-11ea-9792-e5b81ea18270.jpg)
![zea sov](https://user-images.githubusercontent.com/18510648/80624327-cb86a280-8a4b-11ea-91b4-02b401ad13e6.jpg)

While DOK's might be happy with their 120 SE and shammy's getting the best one - by a large margain. Zealot's get the really short end of the stick? - All healers with a clue would want the anti crit. Anyone who played with that on live, surely remembers the OPness of it 😄 

This is intended?

**Comment by Kabucoror** [comment]
The BT is for bugs not for suggestions.
