### ISSUE TITLE
guild heraldry not saving for initial selection

### ISSUE THREAD

**Issue by 816384138** [WarEmu/WarBugs#16551]
**Expected behavior and actual behavior:**
Guild level is 15. <SmuG>
Trying to select guild heraldry lvl 10 guild tactic. 
Empire filter selected. Shape 2 (also tried 5 in case the first option was taken). Base color yellow. Pattern 33. Pattern color black. Emblem 38. 

When I go to click save, it asks me to confirm and it says Note: this will cost you 0 1717. I click save, and nothing changes. the banner still appears the same (Default) as well as my cloak. 

**Steps to reproduce the problem:**
I was told it costs 100g although it's not specified anywhere. I had 100g in inventory and saved but no change. I also tried putting it in guild vault and it did not save.

**Testing Screenshots/Videos/Evidences (always needed):**

![1](https://user-images.githubusercontent.com/64542895/80611861-cc461700-8a00-11ea-92bf-d23fb7163ccc.jpg)
![2](https://user-images.githubusercontent.com/64542895/80611869-cea87100-8a00-11ea-9cca-4c6c5ea7829d.jpg)
![3](https://user-images.githubusercontent.com/64542895/80611874-cfd99e00-8a00-11ea-85bb-cdd388f3972a.jpg)

**Comment by 816384138** [comment]
update: I completed the same instructions as above after hte patch today and it took 10 gold (i believe) and gave us the colors, pattern, but not the emblem (the weird baby) and gave us the base emblem! I retried thinking maybe I had done somethign wrong, and again the system took my gold (now 100g taken out) and still the WRONG emblem (base, not the weird baby)

**Comment by 816384138** [comment]
can someone just change the emblem for the guild? or could you reset and give back teh 110g?

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/9791
