### ISSUE TITLE
Zone 0 Blank Screen

### ISSUE THREAD

**Issue by Visitations** [WarEmu/WarBugs#1655]
I'm stuck with this blank screen after leaving an SC. I've tried disabling mods, using /stuck command, logging out, rebooting; no joy. I can't do anything with this toon till this is figured out. Posted a screenshot. I can play my alt just fine.

![rambone_000](https://cloud.githubusercontent.com/assets/15107257/10455977/a7bb3082-718c-11e5-885d-7708a901ea92.jpg)

**Comment by Evildoor** [comment]
Have you tried using /stuck twice? Doing ENTER - /stuck - ENTER during the loading screen?

**Comment by Visitations** [comment]
I tried it again and it worked. Must be hit or miss.
