### ISSUE TITLE
(Sticky Squigs) Squigherder// Mailbug

### ISSUE THREAD

**Issue by hahrss** [WarEmu/WarBugs#16553]
**Expected behavior and actual behavior:**

Hello i want to report that Sticky squigz dont work well against WL-Pull and other Enemys. Now i cant Counter WL-pull with Sticky squigz (what Years off playing this game was working) . And a Stun is now faster than StickySquigz what actuelly always works well to avoid death Squig Herder. 

My last Post actuelly got deleted ? why? 

And i didnt get a Purple loot Bag from step 3 City. I hope i get that Mail soon.

Greetings Hahrss
--> 

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Your previous report was closed, and replied to, as you posted two bugs in one post. Which is exactly what you've done here.

That being said, I'm going to give you the benefit of the doubt as the second one is easy to answer. You should receive your bag following this reset. 

Please can you record what you're trying to achieve with the ability outline in this report?

**Comment by hahrss** [comment]
Thank you for the fast answer! yes i got already my Bag. And other players too ! Thanks.

I try to record something (get a programm for it). i try to write it down for you tho understand. 

I try to explain the Problem better.
I play the SH now since a few Years.
Before, it was so, that when I get pulled by a White Lion,
i fly to the WL and was able to defend agains the Pull by using 
Sticky Squigs in the Moment when i am in 30ft of the WL.
By that i was able to conter the Pull and was pushed back to my old 
Position before the Pull.
That Counter is not working anymore.
Now I get pulled by the WL, get a Knock Down and will be bursted to 
Death.
I ask if this intended or if it is a Failure.
I can not record it because i dont know how to do it.
Hope i expained it well enough.

Greetings Hahrss

**Comment by grunbag** [comment]
Abilties casted in the air doesn’t work . You need to have your frets on the ground

**Comment by hahrss** [comment]
Sticky Squigz is a instant Spell should be work in the Air

**Comment by grunbag** [comment]
Same with pounce and wh/we self back punt , they can’t be used while in the air

**Comment by hahrss** [comment]
mhm. i checked it. i didnt know that it dont work in the Air... new change with last Patch?

**Comment by grunbag** [comment]
I think it’s like this since 2017

**Comment by hahrss** [comment]
Last week i can Do from my Squig Armor spell -> Kaboom and than in the Air-> Sticky Squigz
