### ISSUE TITLE
SW Triumphant Offensive set is missing 5th Bonus proc at Vendors

### ISSUE THREAD

**Issue by ravezaar** [WarEmu/WarBugs#16558]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Please provide more information.

**Comment by dbddhkpuka** [comment]
It's the same for more classes, Engineer (see screenshot) and others may have it, too.
On Armory the proc is shown.

https://cdn.discordapp.com/attachments/473366854023512065/705352548361699348/unknown.png

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16573
