### ISSUE TITLE
Order, public quest easy (black orc slog)

### ISSUE THREAD

**Issue by 816384138** [WarEmu/WarBugs#16552]
**Expected behavior and actual behavior:**
progression bugged. in stage1 and when I kill a bloody sun orc it does not register the kill and does not progress (stage 1 is to kill 30 bloody sun orcs)

**Steps to reproduce the problem:**
tried in different areas of the PQ
![1](https://user-images.githubusercontent.com/64542895/80622108-f18d5200-8a0d-11ea-9c3f-267dfb21279e.jpg)

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
Only the ones inside the cave (the PQ happens inside) count toward the PQ.
