### ISSUE TITLE
Intruder's Chalice

### ISSUE THREAD

**Issue by Caltaa** [WarEmu/WarBugs#16557]
Hello,

I recently ran Sacellum on my DoK and got the Intruder's Chalice offhand. It has the "you gain 6 Soul Essence every second" passive effect, the same as my current offhand, but it has better stats. The passive Soul Essence gain doesn't appear to be working.
![WAR 2020-04-29 12-02-17](https://user-images.githubusercontent.com/64550048/80630364-51392c80-8a11-11ea-9774-b43e931dab40.png)

**Expected behavior and actual behavior:**
Expected: Gaining 6 Soul Essence/second.
Actual: Not gaining any Soul Essence.

**Steps to reproduce the problem:**
Run Sacellum, get and equip item. Spam Soul Essence using abilities, and notice that you gain 0 Soul Essence while in combat, or the default 20/sec outside of combat. Can easily swap between this and a working offhand with Soul Essence regen to notice the extra you get from a correctly functioning item.

**Testing Screenshots/Videos/Evidences (always needed):**
Soul gain while broken offhand equipped:
![WAR 2020-04-29 11-59-35](https://user-images.githubusercontent.com/64550048/80630221-1f27ca80-8a11-11ea-8fe4-89849b9673be.png)
![WAR 2020-04-29 11-59-36](https://user-images.githubusercontent.com/64550048/80630231-2353e800-8a11-11ea-9610-6e3f8b65bd80.png)
![WAR 2020-04-29 11-59-37](https://user-images.githubusercontent.com/64550048/80630240-26e76f00-8a11-11ea-845e-59d608223847.png)

Soul gain while working offhand equipped:
![WAR 2020-04-29 12-03-10](https://user-images.githubusercontent.com/64550048/80630444-7b8aea00-8a11-11ea-8ab2-b6a4235b49ea.png)
![WAR 2020-04-29 12-03-11](https://user-images.githubusercontent.com/64550048/80630455-7e85da80-8a11-11ea-9def-efa061ac6537.png)
![WAR 2020-04-29 12-03-12](https://user-images.githubusercontent.com/64550048/80630460-8180cb00-8a11-11ea-839e-2b2e5c5b3ae3.png)

Hopefully this is enough information, please let me know if you need anything else.

**Comment by Kaelang** [comment]
Unequip and re-equip the item - it should work then.

**Comment by Caltaa** [comment]
Hello,

Tested both right-clicking from bags and dragging and dropping onto the Character Screen as you suggested, no change. Passive Soul Essence gain is still not functioning on this item.

**Comment by Caltaa** [comment]
Hello, an update.

I tested this again while in a scenario (Nordenwatch) and it appeared to be working in there. Once the scenario was over, I tested again in IC and inside the Sacellum dungeon, and confirmed it was working there as well. Maybe the changing of the zone triggered it to be working again?

Either way, I'm all good now, so this ticket can be closed.
