### ISSUE TITLE
Murderous Intent has been zeroed. 

### ISSUE THREAD

**Issue by Esclade** [WarEmu/WarBugs#16559]
murderious intent tactical suppose to give %10 parry %10crit
 before patch i had melee crit:36% , parry:27% 
after patch  melee crit:22% , parry:17%

https://streamable.com/uod269

**Comment by Kaelang** [comment]
![image](https://user-images.githubusercontent.com/60117106/80636231-03461800-8a55-11ea-99b4-493cf950c0ed.png)

Screenshot for relevance.

Appreciate the video, but please provide more information in the title and body next time.

**Comment by Kaelang** [comment]
I've just cross referenced this with my DoK, and I see the following.
![image](https://user-images.githubusercontent.com/60117106/80636330-34264d00-8a55-11ea-8ae7-86dd0a6042ff.png)

Please can you re-evaluate since the server has come back up?

**Comment by Esclade** [comment]
still same after server reset

**Comment by Kaelang** [comment]
Close out your game and launcher, re-launch and download the latest patch. Looks to be effecting a small group of people, but not everyone - leading me to think it was an issue with your launcher pulling the patch files.

**Comment by igvgithb** [comment]
Restarting the game does not help in my case. All of my tactics on chosen are stuck on 0. Crit reduction appears to be fine from .getstats, but there is no way to check the remaining tactics.

**Comment by Esclade** [comment]
re-launched multiple times. is there a way to download latest patch manually again?

**Comment by Kaelang** [comment]
I've uploaded my data.myp file to here: https://easyupload.io/q2q3q0

This has fixed the issue for a few other people. Make sure you make a copy of your current data.myp file just incase this does not solve the problem.

Let me know.

**Comment by Esclade** [comment]
fixed thanks
