### ISSUE TITLE
Soul Essence abilities perma-greyed out.

### ISSUE THREAD

**Issue by Thienri** [WarEmu/WarBugs#16564]
**Expected behavior and actual behavior:**
The abilities for the DoK that require the class resources are greyed out regardless of availability. They can still be used, but the message 'Requires x Soul Essence' appears every time. Also the numbers value for damage and healing on all skills is a flat 0

**Steps to reproduce the problem:**
Logged in after the 29/4 patch and it was like that.

![Teomyr_002](https://user-images.githubusercontent.com/62931030/80638680-81141e80-8a69-11ea-9fda-ae794534e30b.jpg)

**Comment by Kaelang** [comment]
Replace your data.myp file with this https://easyupload.io/q2q3q0

Make sure you create a backup just incase this switch doesn't work.

Please confirm.

**Comment by Thienri** [comment]
Confirmed. Logged in and they're back to normal. Thanks!
