### ISSUE TITLE
DoK off-Sovereign set piece %2 critical hit rate not applying[after patch]

### ISSUE THREAD

**Issue by Esclade** [WarEmu/WarBugs#16561]
before patch it was applying. 

https://streamable.com/sp45i0

**Comment by Kaelang** [comment]
Please use .getstats before and after equipping the gloves.

**Comment by Esclade** [comment]
https://streamable.com/dy3rwl

**Comment by grunbag** [comment]
Update your data.myp , check the topic on forum about abiltiy showing 0.

**Comment by grunbag** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37918

**Comment by Esclade** [comment]
nvm i was confused 22+14=36 its working.
