### ISSUE TITLE
Guard ability works through postern and keep/fort doors

### ISSUE THREAD

**Issue by detrap** [WarEmu/WarBugs#16569]
Guard ability works through postern and keep/fort doors. Guarded team member can go outside and can still be protected with guard.

![Screenshot 2020-04-30 06 32 10](https://user-images.githubusercontent.com/64330047/80644162-8e063180-8aac-11ea-9500-43309c2db1e2.png)

**Comment by Rockalypse** [comment]
Same as group heals guard does not check for LoS, only range.
