### ISSUE TITLE
Abilities changes - effecting main BW abilities

### ISSUE THREAD

**Issue by Uluthefiregod** [WarEmu/WarBugs#16560]
[Abilities]

- Abilities with a ground targeted dot effect will now properly deal DOT damage instead of Direct damage.
Ex.
Napalm Grenade
Dissolving Mist
Blast Potions

Youre fix for Ground ability changes also effect a lot of the BW skills. 
I found out its effecting the main BW bomb skills "Flamebreath" and "Annihilate"

Flamebreath and Annihlate should not be effected by this ability change, as theyre not a ground abilities.

These a BW abilities which always had start dmg to be able to put dmg out.

Just use Flamebreath on a PvE mob or RvR and you will see its not anymore doin any start dmg.
Same with Annihilate no start dmg.

Looking forward to a fix soon because BW basically useless without this two main abilities doin no dmg, its huge balance problem caused with this bugs.

If you have further questions please let me know.

BR,

Ulu

**Comment by Kaelang** [comment]
Tooltip screenshot please.

**Comment by Uluthefiregod** [comment]
[https://ibb.co/wM5bt6m](url)

**Comment by Kaelang** [comment]
Dissolving Mist and Napalm Grenade

- Base damage and Primary Stat Mult have both been increased significantly.

This is to follow up on changes last week that removed the ability for this damage to crit and deal proc damage. Testing with 1100 INT and damage buff from the pet, unmitigiated, Dissolving Mist deals about 700 damage every 2s at the third stage of the damage ramp. This should make this 13pt spec ability less trivial for PvP uses, but will still be monitored over the next patch to see if it is still over/underperforming.

Closed.
