### ISSUE TITLE
mail error

### ISSUE THREAD

**Issue by herrmarek** [WarEmu/WarBugs#1656]
i delete one toon,named Denisse, and created other with this name, when i mail some stuff for that toon, nothing mailed to this toon. I think it mailed to old toon, or mail is lost
restart of game dont help

**Comment by Evildoor** [comment]
Have you logged onto your newly created character at least once? Or you created them, logged onto your other character and mailed things?

**Comment by herrmarek** [comment]
i transfered stuff from old char.(1)| to other char. (2)then deleted that old character. created new one(3) with the same name. then i mailed from character(2)  to new one(3).
I transfered stuff to new one earlier then i first log in to that char. :(

**Comment by Evildoor** [comment]
Aha. Then it's a known issue(#1255). Sorry, we can't do anything here.
