### ISSUE TITLE
Solo Ranked SC not ending / SC+Scoreboard party bug

### ISSUE THREAD

**Issue by Teefz** [WarEmu/WarBugs#16562]
Solo Ranked SC not ending despite of having +10 kills (13 or 14?) and capping the flag.

After watching the VOD from the slayer pov, it seems that the SC just went for the full 15min before ending. 
POV from slayer: https://www.twitch.tv/videos/606005432 - 6h, 40min in.

*edit:* Don't know if it relevant, but this was a re-pop - got ported in and out of two sc's beforehand because they weren't filled up.

**Comment by Teefz** [comment]
Also, if you que for ranked solo and either team doesn't have enough players to start and the battle ends in tie, then the system re-ques you automatically - rightfully so. But you remain in a constant loop where you can't exit the SC summary page, have to close the client and relog. And after a minute you get a quitter debuff, but still unable to even bring up the list of Scenarios, the summary screen remains forever. 

*credit to Kmark101*

**Comment by Kaelang** [comment]
Adding additional information as this just happened to me also. Queued into a 7 Destro V 5 Order. Scenario reset as should, however I now see the group frames, and the game still thinks I am in a scenario (see 'Scenario Summary' and Enemy UI). 

I am still able to speak in /sc as if there was still an open instance. 

![image](https://user-images.githubusercontent.com/60117106/80664832-b6cbfe00-8a8f-11ea-998c-9942f76ab291.png)

**Comment by Teefz** [comment]
Addtionally, the following sc after the above ^ was also 5 vs 7. Scenario did not reset. Leaving 5 to fight 7 for full the duration and still didn't end when one side reached 500.

**Comment by Teefz** [comment]
Think there needs to be a ready check at the start of the SC. Just had another 5v6 scenario that didn't shut down, due to one of the tanks joining the SC as he flew, which booted him out of the SC and back to Capital. UI showed 6 people in the active SC, but there was only 5 and the game was allowed to continue.

**Comment by MaxHayman** [comment]
Should be fixed now. Please reopen if not.
