### ISSUE TITLE
Kotbs Morale 2 "Emperor's Champion" Tooltip is incorrect.

### ISSUE THREAD

**Issue by detrap** [WarEmu/WarBugs#16568]
Tooltip says 30 seconds,

Morale only lasts 15 seconds.
![InkedScreenshot 2020-04-30 06 26 09_LI](https://user-images.githubusercontent.com/64330047/80643770-f9033880-8aab-11ea-8c41-394eac327140.jpg)

**Comment by Kaelang** [comment]
Duplicate of https://github.com/WarEmu/WarBugs/issues/13665. a
