### ISSUE TITLE
patch problem 

### ISSUE THREAD

**Issue by kakless** [WarEmu/WarBugs#16566]
hy 
tactic all at 0 , skill PG grey , and my Engineer tatic  at 0 and texture character at broken. sreen =>>>

https://media.discordapp.net/attachments/696050708352466964/705148197374394428/sav.jpg?width=962&height=541

https://media.discordapp.net/attachments/696050708352466964/705147698919112784/screenshot_000.jpg?width=962&height=541

thx

**Comment by Kaelang** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37918
