### ISSUE TITLE
KOTBS skills, commands and tactic not working

### ISSUE THREAD

**Issue by daecadus** [WarEmu/WarBugs#16565]
**Expected behavior and actual behavior:**
Run Commands/Shouts - Shoulds see them pulse and show up as buffs under my portrait

Commands/Shouts Abilities or tactics not working on KOTBS, no tooltips or paperdoll bonus changes and all bonuses show increases from gear only (ie rugged for empire does not provide an increase.

**Steps to reproduce the problem:**
Log into game and its on by default.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/64555996/80639997-71281a80-8a28-11ea-846d-1b60f9d94604.png)
![image](https://user-images.githubusercontent.com/64555996/80640052-80a76380-8a28-11ea-8f35-4421869b46e9.png)

**Comment by Kaelang** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37918

Please confirm if this works.

**Comment by daecadus** [comment]
Works perfectly!  thank you Kaelang, Did I provide enough/Good info to assist?

**Comment by daecadus** [comment]
Also this fixed commands not working and/or providing bonuses.

**Comment by Kaelang** [comment]
The issue has been reported by a few people and seemed to get fixed by using the file I uploaded.

That being said, was refreshing to see a detailed issue report - thanks.

Closing.
