### ISSUE TITLE
Black Orc Actionbars Issue

### ISSUE THREAD

**Issue by lashwsmith** [WarEmu/WarBugs#16570]
**Expected behavior and actual behavior:**
Expected Behavior: When changing plans, the action bar icons are supposed to light up (not stay grayed out) based on the plan that is currently active. 

Current Behavior: After patch, the UI element on my Black Orc action bars stay greyed out regardless of the plan I am in. They are still functional, but the UI does not track/show what is available. This is occurring with my UI as well as with the UI completely disabled.

**Steps to reproduce the problem:**
Currently, any ability that changes a BO plan results in the behavior described.

**Testing Screenshots/Videos/Evidences (always needed):**

Issue with custom UI: https://streamable.com/huz860
Issue with all addons disabled: https://streamable.com/50pas1

**Comment by lashwsmith** [comment]
This is also happening on the Choppa when Berserk, the resource spenders are not showing as able to be used, but function.

**Comment by Kaelang** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37918

Please confirm if this works.

**Comment by lashwsmith** [comment]
Can confirm: that solved both the issue with action bars as well as potions/abilities showing 0 values
