### ISSUE TITLE
chosen sovereign back skin

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#16576]
after today patch 29/04 which changed something in some sov texture the sov back behave (move) totally differently and plastic (it strech way behind ya) than any other chosen back and from live implementation, it is totally ugly; idk if it was intentional but it is really ugly if a revert can happen please.

P.s: that change may be applied to banner back from bastion stairs instead as that would solve some issue with the banner behave like a cloth.

some image of the bug; it should be like image 3 but it keep move close and strench away like image 1-2; it should be all time like image 3 (when you move is even worst it slide half of it left and right if need more screen i can provide)

![Tesq_122 - Copia](https://user-images.githubusercontent.com/7527415/80657427-d5c49300-8a83-11ea-9351-80c243162166.jpg)

![Tesq_121](https://user-images.githubusercontent.com/7527415/80657425-d2c9a280-8a83-11ea-93f2-b91c8fb709c0.jpg)

![Tesq_119](https://user-images.githubusercontent.com/7527415/80657394-c5acb380-8a83-11ea-86ad-2bb15f4de567.jpg)

**Comment by grunbag** [comment]
I’m not sure to understand the issue

**Comment by Tesq** [comment]
it have to do the way the sov back move when you move around, if you try equip some skulls like i do on your belt back and try move around with different backs you will see that the sov back strech way too much on sides and behind you ( left part of the back) than other backs, it feel like a big chuck of plastic most of times, where texture go where they suppose not.
It stay also too far from your back from mid of it and bellow ; it is like the back is overfloating.... also when you are still there is a bit of floating effect; idk what happened but it happened after last patch

**Comment by grunbag** [comment]
Try to equip a 2h weapon and tell me if this behave the same

**Comment by Tesq** [comment]
same thing tested now

**Comment by grunbag** [comment]
Upload a picture where I can see clearly the issue

**Comment by Tesq** [comment]
![sovrano 2](https://user-images.githubusercontent.com/7527415/80813027-84262080-8bc9-11ea-845d-874b04a1358b.jpg)
![sovrano 1](https://user-images.githubusercontent.com/7527415/80813035-87b9a780-8bc9-11ea-93a8-e43ddb0dc8a9.jpg)

**Comment by Tesq** [comment]
also noted now that when you move around it lag for half a sec from a pose into another; it also bug in char screen

**Comment by grunbag** [comment]
Ill fix that with next patch

**Comment by Tesq** [comment]
thx

**Comment by grunbag** [comment]
It’s the same with both sov cloak (off and def) ?

**Comment by Tesq** [comment]
i duno, i only have def set so the bug is refered to that (yep forgot to mention it was def set sy)

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by Kaelang** [comment]
Should be fixed in 06/05/20 patch - please re-open if issues persist.
