### ISSUE TITLE
Shaman Vanquisher Shoulders and Overlord Shoulders have same Appearance

### ISSUE THREAD

**Issue by Sixmoons48** [WarEmu/WarBugs#16578]
**Expected behavior and actual behavior:**
Patch notes said all sets would have unique appearance, and i believe overlord shoulders once had a higher tier appearance
![WAR-64_2020-04-29_19-40-17](https://user-images.githubusercontent.com/21229715/80660526-8f564080-8a51-11ea-9bb0-f59d9dd0560d.png)
![WAR-64_2020-04-29_19-40-26](https://user-images.githubusercontent.com/21229715/80660536-93825e00-8a51-11ea-8143-1347c91ccbd0.png)
![WAR-64_2020-04-29_19-40-42](https://user-images.githubusercontent.com/21229715/80660538-954c2180-8a51-11ea-999d-2e506a937144.png)

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by grunbag** [comment]
We used all available appearance for the complete set . We chosen to give a classic appearance to overlord / imperator as it’s only a 2 set pieces .
