### ISSUE TITLE
Quest: Morning Beauty - Talabecland

### ISSUE THREAD

**Issue by NeoDedaro** [WarEmu/WarBugs#16571]
The chain Bell of morning beauty quest inside tower shinging as active object but can't be clickable to spawn boss.

**Comment by Kaelang** [comment]
Screenshot / Locations etc please.

**Comment by NeoDedaro** [comment]
![WH - Morning beauty](https://user-images.githubusercontent.com/64559051/80647551-f3d3c880-8a6e-11ea-855d-14098767b49b.png)
![WH - Morning beauty](https://user-images.githubusercontent.com/64559051/80647560-f6ceb900-8a6e-11ea-8cff-65e079b12c6a.png)

**Comment by NeoDedaro** [comment]
![WH - Morning beauty 2](https://user-images.githubusercontent.com/64559051/80647632-182fa500-8a6f-11ea-9bd9-dc122a8c4397.png)

**Comment by NeoDedaro** [comment]
![WH - Morning beauty 3](https://user-images.githubusercontent.com/64559051/80647744-490fda00-8a6f-11ea-8c01-3b71ac4de6ad.png)

**Comment by Lheana** [comment]
The NPC is correctly there, and the bell can be clicked with no issue.
