### ISSUE TITLE
Buffs don't show up

### ISSUE THREAD

**Issue by Warmaunz** [WarEmu/WarBugs#16574]
**Expected behavior and actual behavior:**
I should be able to see my buffs like guard or my kisses (on WE)

**Steps to reproduce the problem:**
I don't see some of my buffs.

**Testing Screenshots/Videos/Evidences (always needed):**
https://www.twitch.tv/videos/606477860

**Comment by Kaelang** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37918

This will fix this issue. 

Closed.
