### ISSUE TITLE
All tactics showing a 0 stat bonus?

### ISSUE THREAD

**Issue by Robosayles** [WarEmu/WarBugs#16577]
Hi!! All of my tactic slots seem to show a 0 stat bonus. Character page also does not show the bonus for skill it should. Ballistic Skill for example. Any help to fix this issue would be great!

**Comment by Kaelang** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37918&sid=f985b09473daf0a98940fc2c6b279c78
