### ISSUE TITLE
2 pieces of Sentinel gear are possible to equip without Lesser Ward.

### ISSUE THREAD

**Issue by lleri** [WarEmu/WarBugs#16587]
2 pieces of Sentinel gear are possible to equip without Lesser Ward: helmet and shoulders (all other are impossible to equip as it should be). Jewel not tested cause I don't have it.
![Kendinn_013](https://user-images.githubusercontent.com/19507091/80678544-c06f5900-8ac3-11ea-9fa8-c1ccda1c9e91.jpg)

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by Kaelang** [comment]
Should be fixed in 06/05/20 patch - please re-open if issues persist.
