### ISSUE TITLE
Appearance - Swordmaster Dominator Appearance

### ISSUE THREAD

**Issue by DoctorBatman** [WarEmu/WarBugs#16585]
The new updated appearances as of 04/30/20 did not fully apply to the Swordmasters kit. The Dominator set still uses the old appearance EXCEPT for the helm which has correctly changed as per the patch photos

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by Kaelang** [comment]
Should be fixed in 06/05/20 patch - please re-open if issues persist.
