### ISSUE TITLE
City Loot is bugged - White bags.

### ISSUE THREAD

**Issue by exotlv** [WarEmu/WarBugs#16588]
![image](https://user-images.githubusercontent.com/8436809/80689565-367cbb80-8ad6-11ea-83a4-3c19663867f4.png)
STage 1 - Win

**Comment by igvgithb** [comment]
Same for stage losses.

![image](https://user-images.githubusercontent.com/62517057/80691601-c91a5c00-8ad0-11ea-9447-1624a9c1386c.png)

**Comment by exotlv** [comment]
For all Stages etc.

**Comment by MaxHayman** [comment]
Fixed in hotfix.
