### ISSUE TITLE
Numeric Values "0"

### ISSUE THREAD

**Issue by maphyr** [WarEmu/WarBugs#16584]
All numeric values are "0" on potions, linaments, tactics and skills.  

Resist stats do not update after buffing resists.

**Comment by Khazanar** [comment]
I am having this exact same issue. I have relogged several times and tried multiple characters with the same results. Also, for some reason, the dye armor feature at NPC's became free.

**Comment by Kaelang** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37918

This should fix this problem.
