### ISSUE TITLE
Malwarebytes detected Ransomware in War-64.exe

### ISSUE THREAD

**Issue by centurionusa** [WarEmu/WarBugs#16580]
After the second (the small one that happened maybe 15-20 minutes ago) update today.  It said this file has the characteristics of Ransomware and quarantined it.  Just wanted to give you guys a heads up as I'm not sure why it did this and for folks that don't know how to un-quarantine a file they won't be able to play.

**Comment by Kaelang** [comment]
Need more information, such as what your anti-virus is etc.

**Comment by Kaelang** [comment]
Nevermind - saw Malwarebytes in the title.

Can you post this on the forums please to collect more information on if this was individual i.e. your AV, or more commonly spread? This isn't a game related bug, more of a potential security issue and/or over protective AV / anti-malware.

Thanks.

**Comment by centurionusa** [comment]
Will do.
