### ISSUE TITLE
Fort Entry/Contribution Bug

### ISSUE THREAD

**Issue by Faraso** [WarEmu/WarBugs#16583]
After Eatine locking for Destro side, I started moving toward Shinig Way fort and it let me enter although didn't look like it gave me an invitation. I was able to participate in the battle inside but each time I would capture a BO it would give me a message that I didn't get contribution.

![Tribiex_003](https://user-images.githubusercontent.com/19200794/80672149-91052000-8ab4-11ea-9a81-dc8439e2724e.jpg)

And when I died it threw me out.

**Comment by Kaelang** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/16409.
