### ISSUE TITLE
Fort contribution and bug messege

### ISSUE THREAD

**Issue by Dizzltron00** [WarEmu/WarBugs#16582]
took a screenshot of the fort..
i was in eatine the entire fight.. faught my ass off.
got into the fort, and happily playing and fighting, capping flags. running around.
after a while i got a msg that "Something has gone wrong when attempting to add contribuation to you, please report on the bugtracker..." after that msg, after a while i ended up dying. then it teleported me outside and couldn't get back in...

toon name : Dizzlblaze

**Comment by Kaelang** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/16409.
