### ISSUE TITLE
Appearance - Marauder Dominator Shoulder Apearance

### ISSUE THREAD

**Issue by Horusaximand** [WarEmu/WarBugs#16591]
Hello.
There is an issue with dominator shoulder apearance - it is invisible. Moreover, the head disapears as well, but helmet remains.
Best wishes.
![DOMINATOR SHOULDER MARA BUG](https://user-images.githubusercontent.com/20398365/80709161-a870f700-8b0e-11ea-9203-1ef5c419b098.jpg)

**Comment by Horusaximand** [comment]
In addition: If you removes showcase of helmet, instead of disappearing, it turns into another one (sentinel one). 





![DOMINATOR SHOULDER MARA BUG 2](https://user-images.githubusercontent.com/20398365/80709596-5bd9eb80-8b0f-11ea-83b1-8b37e0f354b5.jpg)

**Comment by grunbag** [comment]
All sc gears are broken and will be fixed for next patch

**Comment by Kaelang** [comment]
Should be fixed in 06/05/20 patch - please re-open if issues persist.
