### ISSUE TITLE
White bags at Altdrof defense issue

### ISSUE THREAD

**Issue by Desitri** [WarEmu/WarBugs#16590]
instead of getting the blue and purple bag i was rewarded with 2 white bags and i request that i get the tokens i was suppose to get please.
![Soulstress_028](https://user-images.githubusercontent.com/61955502/80693484-094bff80-8b0e-11ea-82ad-3007cc990a79.jpg)
![Soulstress_029](https://user-images.githubusercontent.com/61955502/80693489-0b15c300-8b0e-11ea-9848-d68c85c9b8cb.jpg)

**Comment by Kaelang** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/16588.

We don't recover / give out any items that have been lost and/or are missing.
