### ISSUE TITLE
Quyl-Isha Temple PQ

### ISSUE THREAD

**Issue by Blaqwar** [WarEmu/WarBugs#16598]
Several of the clickable objects in the second stage of the PQ (Stars of Isha/Marks of Isha) have multiple charges to the point where you can easily complete the PQ stage in a few seconds if you know which ones to click.

Screenshot below is just one of them.

![Camael_028](https://user-images.githubusercontent.com/5108812/80738242-fb4dad00-8b14-11ea-9283-d2bbe0e19cce.jpg)

**Comment by Kaelang** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/14893 as reports are related to spammable objects.
