### ISSUE TITLE
City siege - Invader meds instead of Royal crest

### ISSUE THREAD

**Issue by Sandinio** [WarEmu/WarBugs#16596]
Hello,

rr69 with full invader should get Royal crest in City siege, bag includes wrongly Invader meds.

(I got correctly Royal crests for stage, but it's wrong in bag)

![White bag is inv med instead of Royal Crest](https://user-images.githubusercontent.com/38884551/80730664-c126e000-8b01-11ea-9451-cbc00f0a09df.jpg)

**Comment by Kaelang** [comment]
[City Siege]

- You will now only recieve [Royal Crest] from City Sieges when you have the unlocked the Tome of Knowledge entry for equipping the Invader gearset, you will otherwise recieve [Invader Medallion].


------


Have you unlocked the ToK for full invader?

**Comment by Sandinio** [comment]
Yes, full invader with unlocked ToK.

I got correctly Royal crest as City siege stage reward (picture shows it), but it's wrong inside bag.

**Comment by engharat** [comment]
is it possible that you need both ToK and rr70+ to get royal crests?

**Comment by pkfsa** [comment]
Yes I had this same issue, I am full invader rr69 and I got invader medallion from loot bag (thankfully only a white one)

**Comment by Sandinio** [comment]
> 
> 
> is it possible that you need both ToK and rr70+ to get royal crests?

There is no rr requirement in patch notes and as you can see from screen shot I got Royals for stage.

**Comment by emailkook** [comment]
It’s always been RR70 to receive Royals. That was never changed from what I read. You don’t all of sudden get Royals at RR60 just because you got full invader early.

**Comment by MaxHayman** [comment]
Currently the change only effects the end of stage rewards not bag rewards.

**Comment by Sandinio** [comment]
Thanks for clarification Max
