### ISSUE TITLE
"0" Numeric Values

### ISSUE THREAD

**Issue by maphyr** [WarEmu/WarBugs#16597]
All tactics, abilities, potions, linaments have "0" numeric value.

My resists do not update in the character sheet when buffing +resists.

**Comment by Kaelang** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37918

**Comment by maphyr** [comment]
Eh, downloading shady files is the solution?

**Comment by Kaelang** [comment]
Your launcher likely pulled the files incorrectly from the patch. I uploaded my working data.myp file for those experiencing the issue. You could also redownload the full game through torrent if you'd prefer.

**Comment by maphyr** [comment]
Thank you.
