### ISSUE TITLE
Defended KV, got bag but no medals

### ISSUE THREAD

**Issue by tomaslumba** [WarEmu/WarBugs#16609]
![Kharlion_105](https://user-images.githubusercontent.com/17112647/80795107-dfd9b500-8b9b-11ea-95d2-b60fc8a53bdb.jpg)
Hiya, i (WL rr76) defended KV this morning but didn't have the oppertunity to stay to the zone lock, coz Life :)

When i relogged i had won a gold bag, not sure about rp, but no invader medals. 

Kind regards
K

**Comment by Kaelang** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/15134.
