### ISSUE TITLE
Bug on my KOTBS

### ISSUE THREAD

**Issue by Nafloin** [WarEmu/WarBugs#16601]
My Kotbs TAURKIN 
my magical auras don t give any bonus and don t appear to any member of group and on me
my sword blows and all abilities show like 0 damage on tool type
my gard ability don t appear on my target and me

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Nafloin** [comment]
and my tactics like endurance increase don t give bonus

**Comment by Kaelang** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=37947
