### ISSUE TITLE
Sorcerer - Conqueror 5-piece set bonus.

### ISSUE THREAD

**Issue by vargaas83** [WarEmu/WarBugs#16608]
The 5-piece set bonus for the Conqueror set on Sorcerer currently reads - "On hit: 25% chance to steal 0 toughness from your target for 0 seconds".

Seemed a little off, not sure if you've nerfed it or if it's bugged. Either way, would love a fix if needed.

**Comment by grunbag** [comment]
You need to update your data.myp

**Comment by grunbag** [comment]
https://discordapp.com/channels/329292495336767488/510872883309051956/705466753018495036
