### ISSUE TITLE
Ranked SCs can launch and play with less than 6v6

### ISSUE THREAD

**Issue by Rydiak** [WarEmu/WarBugs#16604]
Just had a game where both sides (Order and Destro) entered with only 5 players on each side.  Just before the game launched our Archmage left the game, leaving us 4v5.  The scenario began and continued to completion as a 4v5.  The KotBS on Order side never actually zoned into the SC.

![Rydiak_082](https://user-images.githubusercontent.com/15963532/80764350-1fee5880-8b06-11ea-8fa6-fbe3a0048f77.jpg)

**Comment by MaxHayman** [comment]
Should be fixed now. Please reopen if not.
