### ISSUE TITLE
Masterys doesn't work

### ISSUE THREAD

**Issue by Telesforoh** [WarEmu/WarBugs#16605]
Mastery training doesn't apply the habilities after I respecialized them.

**Put some habilities on the mastery tree, train them, and then erase them and place it again, it stops applying them. That happen with my Rune Priest, I ignore if happens in other characters
![IMG_20200501_010804](https://user-images.githubusercontent.com/64618174/80767472-4339f780-8b48-11ea-901e-5a22934a0c03.jpg)
**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
You need to actually select the abilities to train them. So for example, mastery 3 would require four points. 3 to climb there, and 1 to train.

**Comment by Telesforoh** [comment]
I'll check it, thanks and sorry for disturb you!
