### ISSUE TITLE
No contribution or rewards from Fort defense.

### ISSUE THREAD

**Issue by ringmuscle** [WarEmu/WarBugs#16606]
During Fort defense in *Stonewatch* when i captured BO, i kept getting spam yellow messages with "error adding contribution points, please submit a bug report on how you entered fort".

I had previously participated in *Kadrin Valley* battle, but entered *Stonewatch* before *Kadrin Valley* was locked. 

**Expected behavior and actual behavior:**
I successfully defended *Stonewatch* with my KOTB. I was expecting to get a roll, and some invader medallions, but got neither a roll or any medallions.

If i for some reason did not get a slot, i assume i would be kicked out.

**Steps to reproduce the problem:**
1. Fight in previous zone, to add some sort of participation for reserving slot.
2. Enter fort area, before previous zone is locked.
3. Capture BO, and successfully defend fort.
4. Receive no rewards.

**Comment by Sixmoons48** [comment]
I dont know if it means much but I had this same issue, I didn't get any invaders from caledor defense which is supposed to be new thing, and then went to chaos wastes to help defend keep, got reservation for maw and went there, after doing fort I only got 1k rp "for defending the maw" and no medallions or anything.

**Comment by Kaelang** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/16409.
