### ISSUE TITLE
Staggered after blocking Land Mine

### ISSUE THREAD

**Issue by Zealote** [WarEmu/WarBugs#1661]
![landmine](https://cloud.githubusercontent.com/assets/10598420/10482061/1293b254-726d-11e5-9201-806e83e6c113.png)

Not sure whether it's supposed to be undefendable (at least with block) or not? Also, does the same currently apply to other ranged cc, like Chosen/Knight stag, SW Eye Shot, engi/magus kb etc? I thought I remembered dodging Eye Shot on RoR but not sure now.

**Comment by Evildoor** [comment]
I'm not sure, but maybe this means that you are blocking Landmine effects separately - damage and CC. I remember seeing 2-3 blocks of the same CC ability in combat log.
