### ISSUE TITLE
Invader Crests Not Rewarded for Successful Defense of Pre-Fortress Zone

### ISSUE THREAD

**Issue by Varrgrim** [WarEmu/WarBugs#16617]
After Destruction successfully flipped the Caledor zone at approximately 2:48pm (EST), it appeared that most Destruction players, if not all, did not receive their 4 Invader Crests for defending said zone.  Below is a screenshot of an absence of the message that states Invader Crests were acquired.  Additionally, no Invader Crests were added to currency inventory.  

![Screenshot (6)](https://user-images.githubusercontent.com/64660664/80834267-59829a80-8bbe-11ea-8a31-e06c594d6d17.png)

**Comment by mythyrylfalcon** [comment]
Were you subject to Diminishing Returns due to faction population imbalance?

**Comment by Varrgrim** [comment]
I can confirm that there was a faction imbalance of an approximate 5 to 1 ratio on the high end and 4 to 1 ratio on the low end, both in favor of Destruction due to the majority of Order ORvR population being active in Kadrin Valley for most of the siege.  Does faction population imbalance affect acquisition of Invader Crests in this manner?

**Comment by Kaelang** [comment]
This report was pre-hotfix. Closing.

If this continues to happen, please open a new ticket.
