### ISSUE TITLE
Defended KV (again) only got 1 invader in bag

### ISSUE THREAD

**Issue by tomaslumba** [WarEmu/WarBugs#16619]
![Kharlion_107](https://user-images.githubusercontent.com/17112647/80840391-7d190580-8bfd-11ea-85d2-5679511174bb.jpg)
Hiya, had an issue with not getting any invader medals from a KV defence this morning on my lvl 76 WL and now tonite i defended KV again and this time i only got 1 invader medal in the mail, together with some vanq…. apparently other players got 4.... no idea why i didn't - can i be that both times i wasn't online for the acctual lock?

Screenie to show timestamp, but mail highlited is from the bag and not the medals.

Kind regards
K

**Comment by Kaelang** [comment]
I'm going to merge this with a similar report here: https://github.com/WarEmu/WarBugs/issues/16613
