### ISSUE TITLE
Last zone defense invader on logout

### ISSUE THREAD

**Issue by Shadowgurke** [WarEmu/WarBugs#16613]
The 4 invader crests that are awarded for defending the pre fortress zone do go into your mailbox if you log out before the zone locks. I would assume this is unintended

Expected behaviour:
Defending the last zone before a fortress grants you 4 invader crests, Logging out still gives you all the vanquisher medallions, but not the invader crests.

Cant really provide a screenshot of not getting something.

**Comment by mythyrylfalcon** [comment]
![image](https://user-images.githubusercontent.com/51804717/80824670-c896c980-8b93-11ea-81bf-bfab409d6e7d.png)
Screenshot of my experience. 1 Invader, not 4, post log out. Happened for multiple zones.

**Comment by Kaelang** [comment]
Please can you confirm what flips you was a part of?

And I think there may be a typo in your initial report, I'm assuming you was offline when the zone flipped and only received 1 Medallion?

**Comment by Kaelang** [comment]
No further information - closed.
