### ISSUE TITLE
Cleansing an Empire need to find Eustasius Lang

### ISSUE THREAD

**Issue by Japzor** [WarEmu/WarBugs#16615]
Cleansing an Empire need to find Eustasius Lang but dont get the "Instruments of Justice" that i need to use on him. Also when i Abandon the quet , and trry to take it agein some of my quest item get Doublecate.

**Comment by Lheana** [comment]
You receive the 3 instruments correctly when you accept the last step. But if you dont' have the instruments, it does not prevent you from completing the quest.

**Comment by Japzor** [comment]
Have try killing Jim without any luck, so no it does not work

Sendt fra min iPhone

Den 1. maj 2020 kl. 18.42 skrev Lheana <notifications@github.com>:

﻿

You receive the 3 instruments correctly when you accept the last step. But if you dont' have the instruments, it does not prevent you from completing the quest.

**Comment by Lheana** [comment]
It does work.
![Lheana_148](https://user-images.githubusercontent.com/11537611/80840028-b13ff680-8bfc-11ea-87d2-86defa21729e.jpg)

**Comment by Japzor** [comment]
Yeah just done it solo agein and it works maby becouse i Was in a grp someting happen?

Sendt fra min iPhone

Den 1. maj 2020 kl. 22.40 skrev Lheana <notifications@github.com>:

﻿

It does work.
[Lheana_148]<https://user-images.githubusercontent.com/11537611/80840028-b13ff680-8bfc-11ea-87d2-86defa21729e.jpg>

**Comment by Lheana** [comment]
Yes there is a known issue where killing NPCs does not always count when being grouped.
