### ISSUE TITLE
[Item] The Cloak of Sovereign (OFF) is bugged

### ISSUE THREAD

**Issue by elk76** [WarEmu/WarBugs#16614]
The Cloak of the off Sovereign of the Choppa is bugged
no appearance and purple item (no part of bonus set)

![Pummarola_064](https://user-images.githubusercontent.com/46483570/80813087-a0c25880-8bc9-11ea-876b-6ceca1a2df34.jpg)

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by Kaelang** [comment]
Should be fixed in 06/05/20 patch - please re-open if issues persist.
