### ISSUE TITLE
BO sov painboss - sholda bug

### ISSUE THREAD

**Issue by jinsu0716** [WarEmu/WarBugs#16618]
![unknown (1)](https://user-images.githubusercontent.com/64660606/80834120-114d9180-8c2b-11ea-84f6-d101ef7f49e6.png)

I know this doesn't change color.

But why is it impossible to color?
It won't color....help me plzz

**Comment by grunbag** [comment]
It seems to have the wrong appearance

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by Kaelang** [comment]
Should be fixed in 06/05/20 patch - please re-open if issues persist.

**Comment by Romanuzo** [comment]
Hey, have the same problem out there, shoulders doesn't show any dye at all
