### ISSUE TITLE
Marauder | most skills / abilities greyed-out and not usable

### ISSUE THREAD

**Issue by mbrun007** [WarEmu/WarBugs#16612]
**Expected behavior and actual behavior:**
**Expected:**
It is expected that the core abilities plus the mutation specific abilities are displayed in a colored way on the actionbar and usable.

**Actual:**
Most abilities greyed-out and not usable. See screenshot. The two with cooldown in screenshot are skilled in mastery and usable, even they are greyed-out. All other greyed are not usable regardless of selecting by mouse or through hotkey.

**Steps to reproduce the problem:**
Unclear, just happened after latest patch.

**Testing Screenshots/Videos/Evidences (always needed):**
What I have tried so far:
* download and replace of data.myp as in https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37918
* delete data.myp and let launcher redownload
* remove abilities from actionbar and add again
* several relogs and restarts of game
* disable all addons, reenable
* reset all keybindings, profile etc to defaults

![Shanks_002](https://user-images.githubusercontent.com/41704863/80802150-d148c900-8bae-11ea-96b7-b7dc6a240179.jpg)

**Comment by mbrun007** [comment]
Please let me know if I can provide any further information logs etc.

**Comment by Kaelang** [comment]
Do your abilities have values, or are they all 0?

**Comment by mbrun007** [comment]
All values are displayed correctly.
I got the "all values 0" error initially together with the here in described issue.
After replacing my local data.myp with the one you uploaded the "all values 0" error was gone. But not the error described here.

Data.myp used from here: https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37918

**Comment by mbrun007** [comment]
Did one more test:
Created a new marauder and played to Lvl 2 to get first mutation specific ability.
Visual and ability usage is fine and works as expected.

Loaded profile from my marauder with the issue but caused no problem.

Relogged several times to check it is repeatingly fine - no problem.

So it seems the issue is somehow character specific.

**Comment by Kaelang** [comment]
Can you delete your character profile and have the game re-create a fresh one and try that?

**Comment by mbrun007** [comment]
With character profile you mean something in game or some files on the disk?

**Comment by Kaelang** [comment]
C:\ReturnOfReckoning-March2020\Warhammer Online - Return of Reckoning\user\settings\Martyrs Square

**Comment by mbrun007** [comment]
OMG - I found the problem...
I did what you said and logged in. Looked like the problem is still there and I pushed the hotkey to use an ability.
Then I got the note on the screen that I need a weapon equipped in my main hand to use this ability. So I checked my equipement and saw that my main weapon disappeared...

Equipped it and error fixed...
I am sorry to wasting your time on that...
