### ISSUE TITLE
All chararacters disappeared from logging screen 

### ISSUE THREAD

**Issue by konradkonek** [WarEmu/WarBugs#16629]
Dear all,
After logging in to the game I can't see any of my characters.
To be honest - I can't do anything, can't even create a new one.
I've tried to log out and log in couple times. Still same issue.
I'm not sure what has happened.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/64707494/80890750-9b473a00-8cbf-11ea-8b60-da28f7b7f9c0.png)

<!-
![RoR](https://user-images.githubusercontent.com/64707494/80890794-f1b47880-8cbf-11ea-8080-d0b7a60de3df.PNG)

**Comment by ThanksDarwin** [comment]
I have the same Problem

**Comment by shamequa** [comment]
same here

**Comment by zgryvusek** [comment]
same here, restart didn't help

**Comment by Kaelang** [comment]
Is this still happening post-restart?

**Comment by konradkonek** [comment]
It seems it is fixed now for me. What has happened?

**Comment by Kaelang** [comment]
Probably a connection error when login was down.

Closing.
