### ISSUE TITLE
[skill] sticky feetz

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#1662]
cast while moving + out of range = no effect, only CD on skill

**Comment by Evildoor** [comment]
I do believe "moving" is unnecessary and "out of range" is enough to bug the skill out, like Land Mine or Ritual of Whatever. Ok, since someone finally clarified that SF/MotM also has this issue, i'm closing this and other similar tickets and consolidating everything concerning this issue in #1118.
