### ISSUE TITLE
Wrong Gold Bag Reward

### ISSUE THREAD

**Issue by Gestic** [WarEmu/WarBugs#16623]
After defending Eataine (which was lost) on destro side, around 430pm MST(-8 gmt) i won a gold bag reward. The bag contained a best item reward for swordmaster instead of blackguard.
![Zelraen_000](https://user-images.githubusercontent.com/22520336/80850253-c8b4ba80-8bcf-11ea-83b3-3df8b0f5cfb7.jpg)

**Comment by Kaelang** [comment]
- Fixed a bunch of items in loot bags that were wrongly assigned for another class; this issue concerned mainly Obliterator pieces

Please re-open if issue persists.
