### ISSUE TITLE
SC completion rewards

### ISSUE THREAD

**Issue by Zoraxle** [WarEmu/WarBugs#16627]
As a CR36 RR41 player i am still getting soldier emblems from a SC completion. I dont mean the quests or from defeating other players. i am talking about the emblems you receive upon completion of an SC. In the screenshots i attached i received 6 soldiers for completing the SC. IF there is going to be level 35 gear that requires officers then shouldnt i be at least getting officers?

![Zoraxle_000](https://user-images.githubusercontent.com/64702705/80871825-eed76a80-8c62-11ea-913a-40c0bd9b3fa6.jpg)
![Zoraxle_001](https://user-images.githubusercontent.com/64702705/80871828-f139c480-8c62-11ea-9f53-7887b87240a9.jpg)

**Comment by SilverWF** [comment]
Yep, old issue #15821

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/15821
