### ISSUE TITLE
Destruction chapter 19 influence bug

### ISSUE THREAD

**Issue by NSKaneda** [WarEmu/WarBugs#16626]
Influence for chaos chapter 19 (praag) is not adding up on inf bar or in ToK despite mobs and stages granting normal numbers.

**Comment by Lheana** [comment]
Please provide screenshots and the name of the PQ you are doing.

**Comment by NSKaneda** [comment]
Certainly. 

Chasing Shadows easy PQ and Sundered Fortress hard PQ.

![Sorkratez_003](https://user-images.githubusercontent.com/22037960/80867813-5a86fb00-8c96-11ea-8973-31b2033c2b76.jpg)
![Sorkratez_004](https://user-images.githubusercontent.com/22037960/80867814-5c50be80-8c96-11ea-9f79-05674e4a8090.jpg)

**Comment by Lheana** [comment]
For the PQ Chasing Shadows: #11218
For the PQ Sundered Fortress it's the same issue, both PQs correctly give influence for their chapter, i.e. chapter 17, but the chapter 19 is wrongly displayed when you are in these PQs. Both are known issues, so I close the ticket.
