### ISSUE TITLE
Bloodlord Helmet

### ISSUE THREAD

**Issue by Adeno89** [WarEmu/WarBugs#16631]
Currently you are able to equip Bloodlord helmet without having any Ward completed.
Just got my bloodlord helmet on my character Alexkuniva
was happy to be able to equip the helmet for the skin lol
![Alexkuniva_010](https://user-images.githubusercontent.com/64712037/80895174-96768c00-8ca7-11ea-8194-19b5c057a7da.jpg)

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Looks like this should've been fixed last patch, see https://github.com/WarEmu/WarBugs/issues/16195.

I'll keep this up for review.

**Comment by Adeno89** [comment]
Sorry did not see that post

**Comment by Adeno89** [comment]
I just tried equipping my blood lord shoulders and it work. Do you want a
screen shot?

**Comment by Kaelang** [comment]
Can you screenshot your ToK (for sent/redeye), and you with the items equipped please?

**Comment by Adeno89** [comment]
Sure

**Comment by Adeno89** [comment]
Does that one work better?

**Comment by Kaelang** [comment]
And you've not worn the Redeye / Sentinel gear at all? - Trying to determine if you have the ward, but the ToK isn't updating. Or you actually don't have the wards, and can still wear the helm.

**Comment by Adeno89** [comment]
I am missing redeye chest piece. I have all sentinel but I have not been
able to equip the set

**Comment by Adeno89** [comment]
see the text in chat when i try to equip bloodlord chest piece

**Comment by Adeno89** [comment]
I appreciate all the work you guys do. I used to play this game when I was
a teenager.
You guys do a better job than I ever experienced when the game was live.

**Comment by Adeno89** [comment]
![Alexkuniva_024](https://user-images.githubusercontent.com/64712037/80897966-b9af3480-8cc3-11ea-8625-7e2cba326a06.jpg)

**Comment by Adeno89** [comment]
![Alexkuniva_019](https://user-images.githubusercontent.com/64712037/80897981-d77c9980-8cc3-11ea-8852-76e5936583dc.jpg)

**Comment by grunbag** [comment]
It’s fixed for next patch

**Comment by Kaelang** [comment]
Should be fixed in 06/05/20 patch - please re-open if issues persist.
