### ISSUE TITLE
Shaman's Vortex aoe dot not working

### ISSUE THREAD

**Issue by Picklemyrickle** [WarEmu/WarBugs#16637]
Hi, shaman's aoe dot "Vortex", isn't working.
You target an enemy, click the spell but nothing happens, checked multiple times same result.
Other granted abilities do work.

https://imgur.com/a/PPBIySq

If anymore information needed, please elaborate.
Thanks

**Comment by Kaelang** [comment]
The screenshot doesn't really show anything. It's a 30 foot AoE around your character, not the enemy.

Please can you provide a video clip?

**Comment by Kaelang** [comment]
No further information.
