### ISSUE TITLE
Masks from Halloween 2017 use wrong equipment slot

### ISSUE THREAD

**Issue by Sjukob** [WarEmu/WarBugs#16638]
The masks are supposed to go into **pocket** slot, but for some reason they are now considered **helmets** instead. The issue seem to have appeared after the latest hotfix.
![rsaaergarehrayar](https://user-images.githubusercontent.com/64742590/80918864-08cb9700-8da2-11ea-8898-6447c8d7fef0.PNG)

**Comment by wargrimnir** [comment]
This is intended. They can be used as masks from the pocket slot during Halloween events. Afterward they are helmets.
