### ISSUE TITLE
Bloodlord Shoulders

### ISSUE THREAD

**Issue by Adeno89** [WarEmu/WarBugs#16635]
My Shaman Alexkuniva does not yet have full redeye. I have full sentinel but cant equip any of it
Bloodlord seems to be bugged to where you can equip the shoulders 
![Alexkuniva_019](https://user-images.githubusercontent.com/64712037/80914072-ec324f00-8d0e-11ea-9520-a4507effc6e5.jpg)

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Should be fixed in 06/05/20 patch - please re-open if issues persist.
