### ISSUE TITLE
Amulet of Ursun doesn't add stats.

### ISSUE THREAD

**Issue by Picklemyrickle** [WarEmu/WarBugs#16636]
Hi new live event item isn't working even with .getstats
shaman spell "vortex" aoe dot not working either.

https://imgur.com/a/8spXQej

**Comment by Kaelang** [comment]
Please open a separate report for the Vortex issue. I'll need more information that 'not working'.

I'm keeping this up for the Amulet of Ursun report and will be editing your title to reflect this.

**Comment by TenhiYT** [comment]
Works just fine. It shows up in .getstats as Critrating and not as Melee/Ranged/Magic/Healcrit. It doesnt show on the Charscreen thought.
