### ISSUE TITLE
Destruction of the weak public quest not spawning

### ISSUE THREAD

**Issue by marcusbragg** [WarEmu/WarBugs#16634]
The public quest destruction of the weak is not spawning any refugees therefore the public quest is currently stuck on stage one 1/40.

**Comment by Kaelang** [comment]
Spearmen and Duelists both count toward the PQ.

**Comment by marcusbragg** [comment]
Please note I’m aware of this but there are no mobs period that are spawning it’s bugged

**Comment by marcusbragg** [comment]
It’s all sorted out now with the hotfix today thank you very much
