### ISSUE TITLE
Got Booted from Fort after dying

### ISSUE THREAD

**Issue by m00s3m4n** [WarEmu/WarBugs#16648]
I joined Reikwald on my level 22 Toon from Altdorf. I got in initially just fine even without having participated in Reikland, got my reservation and all. 
However suddenly the following message started appearing in my chat: 
Something has gone wrong when attempting to add contribution to you, please report on the bugtracker the circumstances of you entering the fort.

![FortContribution](https://user-images.githubusercontent.com/28826389/80927081-aff90000-8d9b-11ea-84a9-7578082b53c3.PNG)

Thanks for looking into it.

**Comment by Kaelang** [comment]
Duplication of https://github.com/WarEmu/WarBugs/issues/16409.
