### ISSUE TITLE
Reikland RVR Two Rams on Destruction Side

### ISSUE THREAD

**Issue by Tyrsword** [WarEmu/WarBugs#16646]
At ca. 23.15 destruction side used two rams to attack the order keep.
Screenshots attached show one ram at the gate, and one set a little bit off, before it seemed like both were attacking the door.

![Jenja_015](https://user-images.githubusercontent.com/64754311/80926379-41b23e80-8d97-11ea-8a2a-6ec003d00bc4.jpg)
![Jenja_012](https://user-images.githubusercontent.com/64754311/80926383-4545c580-8d97-11ea-8765-267727094906.jpg)
![Jenja_013](https://user-images.githubusercontent.com/64754311/80926388-470f8900-8d97-11ea-8b96-753e18d84e1f.jpg)
![Jenja_014](https://user-images.githubusercontent.com/64754311/80926391-48d94c80-8d97-11ea-92ca-73669fde18de.jpg)

**Comment by TenhiYT** [comment]
Level 4 Keeps allow you to spawn 2 Rams. Its not a bug as far as I know. It probably IS a bug if they can both ram the door at the same time.

**Comment by Kaelang** [comment]
Isn't a bug, it's technically possible to have 3/4 up I think?
