### ISSUE TITLE
Maw of Darkness  Sc bugged

### ISSUE THREAD

**Issue by Lnternsmite** [WarEmu/WarBugs#16652]
Hello

 So about a few minutes ago I got disconnected out of the Maw of Darkness. Very Buggy, first we got a tie because a person didn't join so we were given a  re queue and a pop a few seconds later. The sc again had one less of our team but the scenario began it did not end on a tie, the game kept going even after it reached 500 hundred on the opposite side .

![Khenrac_003](https://user-images.githubusercontent.com/53047875/80928375-db66f500-8d71-11ea-87af-fd8a69fff6d9.jpg)

![Khenrac_004](https://user-images.githubusercontent.com/53047875/80928379-e6218a00-8d71-11ea-8f53-767c77c7a6b8.jpg)

![Khenrac_005](https://user-images.githubusercontent.com/53047875/80928384-e91c7a80-8d71-11ea-8633-e94ff89ff6e0.jpg)

Above are screen shots of the number of players, the comments show that after 500 was reached we got a message saying "sc will start in 30 seconds and then it has begun still at 500 point. id like to add that one opponent was not tagged for rvr until much later.

**Comment by Kaelang** [comment]
Should be fixed now - please reopen if the issue persists.
