### ISSUE TITLE
Entering Fell Landing without reservation

### ISSUE THREAD

**Issue by squeegiefreak** [WarEmu/WarBugs#16658]
I saw there is another issue with getting in with reservation, but I think this is a different issue. 

I just got on, and didn't contribute in in Caledor. I ran to the edge to wait to see if I could be in for reservation. I put run lock on while mounted on the Eastern Wyvern Hatchling Mount and run in repeatedly when I'm bored to make sure I don't get AFK. After being ported out several dozens of times, I started quickly tapping w, talking on discord while waiting. After a dozen times of that, I ported back to a point that let me in further. I continued tapping to see how far I could get until I was ported out, and it never happened I was fully in. I thought it might have been a fluke, so I had a guild mate without contribute try it, and it took about 10 minutes of trying, but he was also able to get in using this tap method, afterward we both received Medallions.

I will attempt to get a video the next fort, but this was the approximate position we got in with:
![image](https://user-images.githubusercontent.com/12853897/80942815-9b683800-8d9a-11ea-828f-1b7ca4ff71d4.png)

**Comment by Kaelang** [comment]
Looks related to https://github.com/WarEmu/WarBugs/issues/16115.

Closing.
