### ISSUE TITLE
Shadowchasm - Caledor High Elf Chapter 20

### ISSUE THREAD

**Issue by KySaber** [WarEmu/WarBugs#16653]
G'day,

Another PQ with a bugged interactable object. You can spam click the dark elf tents, giving you quick completion of the PQ and influence.

https://www.youtube.com/watch?v=mzswruXAhTc

Cheers,
Tes

**Comment by Kaelang** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/14893 as reports are related to spammable objects.
