### ISSUE TITLE
Ranked solo group bugged

### ISSUE THREAD

**Issue by Warmaunz** [WarEmu/WarBugs#16651]
**Expected behavior and actual behavior:**
My party should see me in party or in the scenario. I should see the party, too.

**Steps to reproduce the problem:**
I cannot see the party and I am not in the q for the game I am in. We lose because of this, because I am not in party, but I am in the game and I cannot move to party.

**Testing Screenshots/Videos/Evidences (always needed):**

https://www.twitch.tv/videos/610512932

**Comment by Kaelang** [comment]
We're aware of this issue and will likely be addressed in an upcoming hotfix / patch.

**Comment by dalen** [comment]
this was due to abilities being disabled live. Has been fixed now.
