### ISSUE TITLE
Action Point Drain and stuck in "casting" Status

### ISSUE THREAD

**Issue by Riggaknocka** [WarEmu/WarBugs#16650]
I am playing on my 31 Zealot in Dragon Wake RvR area and after casting a spell my action points completely drain and do not recover. I cannot mount and cannot log out because of "currently casting"

Also getting a barrage of "NullReferenceException was thrown from SendAbilityLevels" messages. (In screenshot)

Closed via Task Manager and logged back in with the same issue.
![Untitled](https://user-images.githubusercontent.com/64755846/80927669-5083fb80-8d6d-11ea-95bc-8040283b6a65.jpg)

**Comment by Kaelang** [comment]
Please see here: https://github.com/WarEmu/WarBugs/issues/16645.
