### ISSUE TITLE
City Siege Glitch

### ISSUE THREAD

**Issue by KySaber** [WarEmu/WarBugs#16655]
Not really sure how to describe this one. As shown, I ressed up, was inside our respawn location and suddenly got teleported back. It may have been the chopper pull, could have been a botched respawn, I have no idea.

https://www.youtube.com/watch?v=l0Vsxl2r7Zw

Sorry about all the reports, hope they're usefull!

Cheers,
Tes

**Comment by Kaelang** [comment]
Would need steps to replicate it.

**Comment by Kaelang** [comment]
No further information.
