### ISSUE TITLE
Quest: "Control" is buggy

### ISSUE THREAD

**Issue by TjReiny** [WarEmu/WarBugs#16656]
![Screenshot (6)](https://user-images.githubusercontent.com/32374834/80933919-0844f780-8dc6-11ea-910d-eea651cb964f.png)

**Expected behavior and actual behavior:**

The quest should register i got the Collar but well it does not.

**Steps to reproduce the problem:**

just do the quest, nothing special, u can grab the collar but it just wont register...

**Comment by Lheana** [comment]
It works as intended. The instructions of RoR Wiki should help you.
