### ISSUE TITLE
No Noteable Persons unlock in t2 dwarf

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#1665]

**Comment by gittoaster** [comment]
Some names for this:
Durrig Olfrinson
Murdogh Kadrikson
Barin Oathsmiter
Droki Redbeard
Balabin Thurarikson
Kurgan Ironfist
Estelle Meye
Grunlok Steelspade
Lokki Redbeard

**Comment by Evildoor** [comment]
You already made a report about this: #1445. Why create a new one?
