### ISSUE TITLE
[Guild] Still (or again) Can't Deploy Recruit's Standard

### ISSUE THREAD

**Issue by Sandskid** [WarEmu/WarBugs#16661]
Re-opening #13289 ticket, the problem still exists. 
![Clip2net_200504115109](https://user-images.githubusercontent.com/20923238/80949984-b7e98c00-8dfd-11ea-867e-6eb8d96a1a54.png)

**Comment by Kaelang** [comment]
I'll re-open https://github.com/WarEmu/WarBugs/issues/13289.
