### ISSUE TITLE
Fort Attacker vs Defender Ratio

### ISSUE THREAD

**Issue by xaraxdestr** [WarEmu/WarBugs#16665]
With nearly equal numbers in Reikwatch Defenders have a clear advantage with BOs that near the keep while destros spawning miles outside. You don't have any chance to take the Fort with that numbers. Is that number intended?
![Knochenfraktur_009](https://user-images.githubusercontent.com/45398873/80991813-e5076000-8e38-11ea-94a2-2833910201ab.jpg)

**Comment by Kaelang** [comment]
We're aware that the numbers looked off - however this doesn't help with trying to replicate the problem and/or find the cause of it.

Please can you provide any additional information help support recreation of this? 

Appreciate you raising awareness of the situation, but we need help with replicating it so we can look to fix it.

**Comment by xaraxdestr** [comment]
well i would love to help ya but i don't know how. I mean i don't know how order is able to get into the fort with that numbers. I saw many running in while we were on lord in reik so maybe they are in fort already when the zone locks and not ported out but that i dont know as destro,

**Comment by Vayra** [comment]
I would assume the increased number of defenders has something to do with the Fell Landing report made yesterday or the day before on how to get in without reservation.

**Comment by R3xz** [comment]
It is common knowledge for some people that it is possible to go to the fort before it pop and the vast majority of the time you will be given a reversation and won't get kicked out. I've tried this a couple times and every single time I was given a reservation even if I contributed very little in the previous zone. I knew for sure it was a bug but I thought someone mentioned that it was on the bug tracker already... hmmm

**Comment by Kaelang** [comment]
I believe this is based off of a similar report that the team are aware of and looking at - therefore I'm going to merge and close.

https://github.com/WarEmu/WarBugs/issues/16115
