### ISSUE TITLE
IC Siege: Skipped Stage 1 and bugged Lord in Stage 2

### ISSUE THREAD

**Issue by Rubyeclipse-war** [WarEmu/WarBugs#16660]
**Expected behavior and actual behavior:**
Our group queued as a 6-man for CIty and was one of the first groups to enter. (Joined Queue right as it opened.)

**Expected Behavior:** City progresses normally from stage 1-->2-->3

**Actual Behavior:** Upon loading in, there was an open treasure chest behind us. Once the stage began, we realized Stage 1 had been skipped entirely. The instance treated it as if defenders had held all points and attackers had not captured any. Both Lords (Volkmar and Gormann) suddenly appeared from the void and began to walk their respective paths.

Additional Bug: Upon dying at Emissary of the Changer, Gormann, perhaps feeling personally slighted at Order's missed chance to get flags in Stage 1, simply _willed himself back to life_ at Order Spawn, and began a direct bee-line straight towards the Emissary of the Changer BO for revenge. Bless him.

The city ended normally after Stage 3 with the king fight. 

In case it matters / helps: our instance was listed as IC #6.

**Steps to reproduce the problem:**
Unsure, but key notes on this one were:
- We queued as fast as possible, as a 6 man
- Chest appeared the moment we loaded in (guessing it was a stage 1 chest)

**Testing Screenshots/Videos/Evidences (always needed):**

![Silvite_152 (2)](https://user-images.githubusercontent.com/60584990/80944455-7aa1e180-8d9e-11ea-96cb-90ddbfb59836.jpg)
![Silvite_154 (2)](https://user-images.githubusercontent.com/60584990/80944575-bc328c80-8d9e-11ea-99b7-4f1af5b007e0.jpg)
![Silvite_155 (2)](https://user-images.githubusercontent.com/60584990/80944591-c6ed2180-8d9e-11ea-88d3-374d658e5f2e.jpg)

Thanks, and hope this helps!

**Comment by R3xz** [comment]
I wanted to add additional information that can confirm this bug, I don't have any proof/screenshot on this matter but I can provide detailed experience on what happened.

During IC stage 1 in the last city (the one with 28 total instances) our warband noticed a premature chest drop during the middle of stage 1.

We were assuming that the enemy team decided to surrender the fight somehow (not sure if its possible in city siege), but they had bad composition, died once and never tried as a team again during stage 1.

Shortly after the first wipe for the enemy we noticed the the chest drop notification, along with the invader/crest reward notification in chat. However, stage 1 was still in progress for all of us, so I assumed that it could've glitched out and was triggered from another instance.

When stage 1 was over, the chest notification popped as normal, and continued to stage 2 and 3 as usual.

**Comment by maedhrs** [comment]
Same issue in Altdorf 2 days in a row. Curiously, both are instance 8.
You can see the chest from stage 1 right as we zone into Altdorf and the scenario window shows both Order and Destro having 0 kills, damage, healing, etc so it's not like stage 1 happened and 1 side left before stage 2.

[Video of first occurrence](https://www.youtube.com/watch?v=XjvCu6utLhk&feature=emb_title)
[Video of second occurrence](https://www.twitch.tv/videos/615670572)

**Comment by Kaelang** [comment]
This should now be fixed.
