### ISSUE TITLE
DOK healer actions are greyed out when they shouldn't be and when i have full soul essence

### ISSUE THREAD

**Issue by brou0071** [WarEmu/WarBugs#16662]
![Untitled](https://user-images.githubusercontent.com/6666761/80964897-a4c7c380-8ddf-11ea-930f-6e88325b0883.png)

**Comment by Kaelang** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37918

Please try this - if this doesn't work, please use Game Support and/or Advice on Discord for help with this. It's not a bug, it's an issue with your game files and/or equipment.

**Comment by brou0071** [comment]
worked amazingly, thank you!
