### ISSUE TITLE
extremely high mmr and no pops

### ISSUE THREAD

**Issue by killiansat** [WarEmu/WarBugs#16669]
**Expected behavior and actual behavior:**
i got 1907 mmr in 8 ranked solo games with 0 losses. after that i stopped getting any ranked solo scs. 3 days 8+ hours online and 0 scs. also i m not in mmr rating. highest result(1st place) in the mmr solo table is 1836. 
(gms told me to post the problem here)
pls lower my mmr so i can get rating scs. or... fix the algorithm =)
anyway i d be very very happy if u solve this somehow. 
p.s. while i was writing this report, i got 1st in 3 days pop.. i won.. now mmr is 1933. HELP ME PLS!!!!

**Steps to reproduce the problem:**
8 wins
0 losses
1 death
20..30+ kills

![Ithappens_067](https://user-images.githubusercontent.com/64811265/81015663-ba80cb80-8e67-11ea-865d-b01903668d1e.jpg)

![111](https://user-images.githubusercontent.com/64811265/81015886-206d5300-8e68-11ea-83f0-5d79d6dfa158.jpg)

**Comment by Uluthefiregod** [comment]
HI i have same problem on my knight.

I played 3 games 3 wins and i have 1860 mmr and no pops. 

Please just remove the mmr barrier for open sc only when alot people in que.

https://ibb.co/6tdfJB9

BR,

Ulu

**Comment by Kaelang** [comment]
This isn't necessarily a bug - the team are aware of the MMR brackets and are monitoring proactively. There's been 3 hotfixes to edit the system in the background to allow for easier queues for those and the top, and the bottom, of the brackets.

Please write this on the Suggestions section of the forum.
