### ISSUE TITLE
hey i cant claim keep it say i dont have permission to claim im guild master and id 9-8-7-6 is maker so guild rank 6-9 can claim have 746 gold in guild vaulte

### ISSUE THREAD

**Issue by Bulwye** [WarEmu/WarBugs#16668]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Please use the template provided for more information.

**Comment by Antaiii** [comment]
I suspect it is the same issue as #16538

**Comment by acidicrain** [comment]
PnP guild leader encountered same issue. 
Was unable to claim keep,  got message saying he did not have rights. Guild has the ranks and permissions for claim set

**Comment by Kaelang** [comment]
Merging https://github.com/WarEmu/WarBugs/issues/16538
