### ISSUE TITLE
Armor Penetration from helm gives Intelligence instead

### ISSUE THREAD

**Issue by Shiversdd** [WarEmu/WarBugs#16664]
Armor Penetration from Invader and Sovereign helm (Choppa) gives 3 and 4 intelligence instead 
Without helm
![Killstomp_032](https://user-images.githubusercontent.com/18085484/80987263-79be8d80-8e3a-11ea-948d-dd10e9205001.jpg)
Invader helm 3% ap
![Killstomp_033](https://user-images.githubusercontent.com/18085484/80987570-e89be680-8e3a-11ea-9fbb-54d714229efc.jpg)
Sovereign helm 4% ap
![Killstomp_034](https://user-images.githubusercontent.com/18085484/80987772-357fbd00-8e3b-11ea-9e96-a9d4c500af68.jpg)

**Comment by Kaelang** [comment]
Please use .getstats and review stat changes - will need screenshots.

Thanks.

**Comment by Shiversdd** [comment]
getstats shows the correct values . Thanks for the answer.
![Killstomp_036](https://user-images.githubusercontent.com/18085484/81011291-5c041f00-8e60-11ea-9455-96760129c1d7.jpg)
