### ISSUE TITLE
Invaders granted in mail for last zone defence when conditions not met

### ISSUE THREAD

**Issue by ako1** [WarEmu/WarBugs#16675]
Participated in KV defence last night (PM 04/05/20) and logged off before completion. Upon logging in had a mail with 10x Vanquisher, 2x Paragon, 2x Invader.

Would not have got the invader if the zone flipped when I was logged in as I don't have Vanquisher chest/helm yet but seem to have received it as mail reward.

At least 2 others in t4 chat confirmed they got invaders in mail for same zone defence even though they don't meet requirements.

**Comment by alanparrish** [comment]
can confirm, i did some rvr in kv, praag etc last night but didnt finish any zone and logged off
when i logged back today i had 2 invaders in my mail while not having any vanq item unlocked
