### ISSUE TITLE
character bug

### ISSUE THREAD

**Issue by yusett** [WarEmu/WarBugs#16671]
Hello have a lvl 20 Shadow warrior in my account that when I log in with the character he has no gear, no skills, no items and he spawns dead please help with this I cant play on this character with this issue.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Please use Game Support, /advice and/or the Discord channel for help with this.  Without replication and/or knowledge of what this is (as a bug) the tracker can't do anything for you.
