### ISSUE TITLE
Tactic AM: Balanced mending doesnt work

### ISSUE THREAD

**Issue by Lemonpie1** [WarEmu/WarBugs#1667]
plain and simple it should give me 35% extra heal on others and 15% less on myself none of these effects works

**Comment by Evildoor** [comment]
Strange, i'm pretty sure i've already seen report about this somewhere... Can someone tell me exact name of the skill which this tactic affects? I can't access game or warbuilder right now.

**Comment by milosxe** [comment]
Skill is called Healing Energy. I'll check Shaman's mirror (Gork'll Fix It with Gork Fix'd It tactic).

**Comment by Evildoor** [comment]
Aha. No reports. Then i've mistaken.

**Comment by milosxe** [comment]
Shaman combo works fine.

**Comment by ozarmidrashim** [comment]
This works fine on the dev server.
