### ISSUE TITLE
[T1 SC's] 11lvl characters bolstering to 21lvl sometimes

### ISSUE THREAD

**Issue by Kushido** [WarEmu/WarBugs#1668]
I saw this bug only on Mourkain Temple
Lvl 11 characters sometimes bolstering to lvl 21, but not always, and not all.
On 2 sc's i get bolstered to lvl 21 as my 11 lvl zealot
on 11lvl i have 1570 HP, if im bolsted i have 2690 so i guess stats getting boosted and its not only visual bug
This annoying more because of WL pets (dont know about magus/squig), because if WL looks for me as "white" color, his pet looks for me as "deadly"
notice, i was too "bolsted" on this sc
![eru_000](https://cloud.githubusercontent.com/assets/14280617/10528885/de0f1858-73a1-11e5-929e-45154ca138ea.jpg)
![eru_001](https://cloud.githubusercontent.com/assets/14280617/10528884/de0eb8cc-73a1-11e5-88ce-3259b156ebd3.jpg)
![eru_002](https://cloud.githubusercontent.com/assets/14280617/10528883/de0e559e-73a1-11e5-9a85-87d321b57b05.jpg)

**Comment by Evildoor** [comment]
I've seen similar problem, but the bolster was to lvl 26 - however, i think it was a visual bug, since affected players were not unkillable / doing excessive damage.

**Comment by Kushido** [comment]
But pets, they don't looks like visual bug and have "Deadly" status for me when WL have "normal-equal" status

Will try to look for this bug on t2 SC's too, so it must be for 21lvl and maybe for 26lvl. Or we have this problem only on t1 sc's

**Comment by Evildoor** [comment]
Just saying - IIRC, on live my own pet was shown as "Deadly" to my WL under bolster.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
