### ISSUE TITLE
Sovereign Sholdaplates of the Painboss missing after patch.

### ISSUE THREAD

**Issue by Rucent** [WarEmu/WarBugs#16688]
**Expected behavior and actual behavior:**
I logged in 20-30 minutes ago and noticed my BO's (Waaaghyu) sov DPS shoulders were simply gone. I checked in my bank and the buyback windows just to be thorough, and they are nowhere to be found.

**Steps to reproduce the problem:**
???????????????????

**Testing Screenshots/Videos/Evidences (always needed):**
The shoulders are missing from the off-spec sov merchant as well as shown here in the video.
https://www.youtube.com/watch?v=SWD0JvyWkB8

Shows my shoulders on the armory.
https://i.imgur.com/vViW0wb.jpg

**Comment by blackfelon** [comment]
Same problem here, shoulders disappeared, and thank you Rucent for pointing that Armory database to make our claim believable !
https://www.returnofreckoning.com/armory/character/1234546

**Comment by Kaelang** [comment]
Out of curiosity, what is equipped in your shoulder slot on your character screen? have you noticed a stat change?

**Comment by Rucent** [comment]
My shoulder slot is empty, and the stats from the shoulders and 6% melee crit from the set bonus I should have are gone.

**Comment by blackfelon** [comment]
Slot empty, characater screen without shoulders, and vendor of Sov DPS does not sell the item either

**Comment by z0nkaT** [comment]
got the same prob logged in and even on my Char select window the shoulders were gone nowhere to be found

**Comment by MordecaiEth** [comment]
Mine as well.

**Comment by Nantroxss** [comment]
Sov jewel missing on my Chosen

**Comment by Nefarian78** [comment]
My shoulders also have completely disappeared. 

Additional random info and detail that maybe could be useful

Got those from a gold bag a few days after city release.

Never unequipped them after the appearance was changed from Warpforged to Alt-Sov.

Used dyes on the item before the appearnace got changed to Alt-Sov

Changed the shoulder's appearance with that of Defsov (Warboss set) before appearance was changed to Alt-Sov.

**Comment by und12** [comment]
my shoulders are gone too
https://www.returnofreckoning.com/armory/character/1254045

**Comment by herkboy** [comment]
Mrsparkles 'ere. Same, no shoulders of da painboss. Lets see how long will it take to be fixed.

**Comment by Waaghhabit** [comment]
Waaghhabi lost his shoulders of da painboss. What the ZOG is going on here!!!

**Comment by MordecaiEth** [comment]
All my fellow sov black orcs here I recognize your names. I hope they atleast address this situation today or give us some sort of follow up information. Keep calm and Waaaagh on.

**Comment by Kaelang** [comment]
To 'address' the situation - we know about the problem and the devs are looking into it.

**Comment by herkboy** [comment]
Any update on the issue?

**Comment by z0nkaT** [comment]
Update ?

**Comment by Kaelang** [comment]
If I was to update every bug report on here as requested, I'd have no time to assign any of them. The devs are aware of this issue and when there's an update on it - you'll get it.

**Comment by Kaelang** [comment]
Fixed as of 13/05/2020 patch. Please re-open if issue persists.
