### ISSUE TITLE
unable to enter game all chars booted out

### ISSUE THREAD

**Issue by acidicrain** [WarEmu/WarBugs#16689]
**Expected behavior and actual behavior:**

Expected Characters should be able to enter game
Actual: times out and kicked out. bot with trying a /stuck /stuck 

**Steps to reproduce the problem:**
login
Select any character of mine (same for all) 
attempt to enter game

**Testing Screenshots/Videos/Evidences (always needed):**

https://youtu.be/GMN-iK6istY

**Comment by Kaelang** [comment]
Installation / File problem - likely a corrupt world.myp based on patch potentially? 

Please use Technical Support. Ideally you'd try a redownload of fresh files.

**Comment by acidicrain** [comment]
reinstalled one character can login, rest can not.
tested again with old copy same. so nothing to do with instalation.

**Comment by acidicrain** [comment]
appears that i am able to log in chars until i login fluf. as soon as i log in fluf i am unable to load another character
