### ISSUE TITLE
Missing 2H Oppressor Sword 

### ISSUE THREAD

**Issue by bataisflow** [WarEmu/WarBugs#16687]
**Expected behavior and actual behavior:**
When I logged off last night my knight (Drshockaloo) was holding my 2h sword. When I logged on after the update, my knight was holding nothing and the oppressor sword is gone form all inventories. 

I have the 2H oppressor sword with increased crit for the knight. I had traded up all the other conq swords to get this with 1200 oppressor medallions. 

**Steps to reproduce the problem:**
Can't reproduce. Item is just missing.

**Testing Screenshots/Videos/Evidences (always needed):**

I will try and get a screenshot from some video from last night with my knight holding the sword.

**Comment by Kaelang** [comment]
"I will try and get a screenshot from some video from last night with my knight holding the sword."

I'll wait for this screenshot - thanks.

**Comment by bataisflow** [comment]
I am still awaiting an image. Hopefully my friend captured it. here is a screen shot of my knight with the previous sword at least (which i traded in for the oppressor sword). Does the system save images (in case my friend doesn't have a screenshot)? other ways to provide proof of purchase?

**Comment by bataisflow** [comment]
> "I will try and get a screenshot from some video from last night with my knight holding the sword."
> 
> I'll wait for this screenshot - thanks. 

Here are multiple screen shots from last night in kv with my guild wb. Sword should be recognizable in some of these screen shots.

**Comment by Kaelang** [comment]
Did this item ever return?

**Comment by bataisflow** [comment]
Sadly no. Is there anything that can be done? I loved that sword :o
