### ISSUE TITLE
Squig Herder: "Clever Stabbin'" tactic references a mastery that no longer exists

### ISSUE THREAD

**Issue by hunkyjimpjorps** [WarEmu/WarBugs#16686]
![image](https://user-images.githubusercontent.com/5170341/81196813-856e9900-8f8d-11ea-91bb-5d6b89a5708b.png)

"Path of Big Stabbin'" is now "Path of Bouncin'", so the name and description are out of date.  The tactic works properly, it's just a visual/textual mistake.

I saw that this issue was previously reported a couple times, but both tickets were closed for unrelated procedural reasons so I don't know if this is still something that the devs are aware of.

**Comment by Saxoprane** [comment]
Please correct this textual mistake, it's a bit confusing for new players

**Comment by mythyrylfalcon** [comment]
So to clarify, does this tactic effect Big Bouncin' then?

**Comment by hunkyjimpjorps** [comment]
It seems to. From: mythyrylfalconSent: Monday, June 15, 2020 12:55 PMTo: WarEmu/WarBugsCc: hunkyjimpjorps; AuthorSubject: Re: [WarEmu/WarBugs] Squig Herder: "Clever Stabbin'" tactic references a mastery that no longer exists (#16686) So to clarify, does this tactic effect Big Bouncin' then?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by grunbag** [comment]
This tactic is removed
