### ISSUE TITLE
Squig Herder Bloodlord 7th piece bonus does not work. 

### ISSUE THREAD

**Issue by Knowthyourself** [WarEmu/WarBugs#16693]
I have just completed bloodlord set for my Squig Herder today. I have run around 2 hours in rvr/scs  equipped full bloodlord set but it didn't trigger once. it seems to be broken. I have also relogged a few times thinking that my character might have bugged out but it didn't change anything.

**Comment by Kaelang** [comment]
Screenshot of the ability trigger, and if possible could you record yourself trying to proc it?

**Comment by Kaelang** [comment]
Closing no further information provided.
