### ISSUE TITLE
PQ Bag Reward - Wrong faction.

### ISSUE THREAD

**Issue by cybercee** [WarEmu/WarBugs#16698]
![Dratho_000](https://user-images.githubusercontent.com/64934352/81238649-6edd3780-8fb7-11ea-89b5-a1daa54ee34c.jpg)

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by cybercee** [comment]
got a blue bag that gave me a orc weapon when im a dwarf

**Comment by Kaelang** [comment]
Troll county zone lock reward?

**Comment by cybercee** [comment]
Yes. Not sure if I just accept the bag I just have it in my inventory.

**Comment by cybercee** [comment]
Not zone lock. Pq bag sorry

**Comment by Kaelang** [comment]
Which PQ?

**Comment by cybercee** [comment]
Welcome to troll country

**Comment by Kaelang** [comment]
Fixed as of 13/05/2020 patch. Please re-open if issue persists.
