### ISSUE TITLE
Stats are being bumped down in SCs.

### ISSUE THREAD

**Issue by Visitations** [WarEmu/WarBugs#1669]
My heals are being reduced after I have joined an SC. 

In this shot, Khaine's Invigoration is only healing me for 471 when it should be 533.

![visitations_002](https://cloud.githubusercontent.com/assets/15107257/10531413/5a26ef1a-737f-11e5-81e0-05378c4ba04f.jpg)

Restore Essence is only healing for 221 when it should be 231.

![visitations_003](https://cloud.githubusercontent.com/assets/15107257/10531434/a4885bca-737f-11e5-8f4b-a150c057fef6.jpg)

Out of SC, the heals are fine.

![visitations_007](https://cloud.githubusercontent.com/assets/15107257/10531526/e29fe5ee-7380-11e5-9915-d2d4fc857b6f.jpg)

![visitations_008](https://cloud.githubusercontent.com/assets/15107257/10531527/e8642026-7380-11e5-8072-ed7d59397f7a.jpg)

**Comment by Luth-RoR** [comment]
Bolster issue, should be fixed.
