### ISSUE TITLE
Rune of breaking not converting intelligence to willpower

### ISSUE THREAD

**Issue by Verenduum** [WarEmu/WarBugs#16695]
**Expected behavior and actual behavior:**
Rune of breaking when off should convert item bonuses of intelligence to willpower and when on should convert the bonuses of willpower to intelligence. 

At the moment this seems to only work when toggling on for willpower into intelligence. But not for intelligence to willpower. 

**Steps to reproduce the problem:**

Equip items with +intelligence and turn off rune of breaking. Results in the same amount of willpower! 

**Testing Screenshots/Videos/Evidences (always needed):**

Rune of Breaking Off - .getstats shows Willpower=222 (0 bonus) and Intelligence 298 (0 bonus)
![Rune of Breaking Off - Naked](https://user-images.githubusercontent.com/64093137/81233083-5c362300-8ff6-11ea-963b-71c3b237ef0e.PNG)
Rune of Breaking On - .getstats shows Intelligence=381  (83 bonus, ie +83 on staff)
![Rune of Breaking On - Naked](https://user-images.githubusercontent.com/64093137/81233512-13329e80-8ff7-11ea-8c92-01b8ead95e5c.PNG)

**Comment by grunbag** [comment]
Do you have a tactic that gives intel ? Cause it only convert stats from items

**Comment by Verenduum** [comment]
Nope I'll take a screenshot without the tactics equipped:

![Rune of Breaking Off - Naked no tactics](https://user-images.githubusercontent.com/64093137/81233805-c602fc80-8ff7-11ea-9932-47a4174cc21e.PNG)

**Comment by Verenduum** [comment]
What's weird is paperdoll seems to show it correctly but .getstats not.

**Comment by grunbag** [comment]
Only with the weapon? Trywith a gear piece

**Comment by Verenduum** [comment]
RoB off with only +26int ring. No willpower bonus at all...

![Rune of Breaking Off - Naked no tactics and int ring](https://user-images.githubusercontent.com/64093137/81234385-ef705800-8ff8-11ea-9d80-d3bd3117b4c2.PNG)

**Comment by Verenduum** [comment]
And here's how I noticed it: full willpower talismans build and bloodlord set with RoB off: 
![Rune of Breaking Off](https://user-images.githubusercontent.com/64093137/81234550-4a09b400-8ff9-11ea-84de-1db005035589.PNG)

And with RoB on same gear: 
![Rune of Breaking On](https://user-images.githubusercontent.com/64093137/81234584-5726a300-8ff9-11ea-83c7-1b02d8dd6366.PNG)

So on works because 934 intelligence and off doesn't because only 450 willpower (so the willpower is applying as bonus with it off but the intelligence isn't converting.

**Comment by Verenduum** [comment]
Quick update on this. 

So everything is working perfectly on zealot, just logged my 26 zealot to check it out: 
+INT converts to +WP :
![Zealot - Harbinger of Doom Off - Naked No Tactics +INT](https://user-images.githubusercontent.com/64093137/81386080-ba592800-9114-11ea-83a0-5a78a087de9a.png)

and +WP converts to +INT:
![Zealot - Harbinger of Doom On - Naked No Tactics +WP](https://user-images.githubusercontent.com/64093137/81386203-e7a5d600-9114-11ea-973d-19300577271f.png)

So this issue appears limited to runepriests.

**Comment by Opeteh** [comment]
> Quick update on this.
" So this issue appears limited to runepriests."

No it's not. Here is my Zaelot without a Charm:
![image](https://user-images.githubusercontent.com/69940910/90698308-aaf38a00-e280-11ea-8190-fccce857e72b.png)
Here with the Charm that should convert Inteligence to Willpower to give +95 total: (p.s. I gave game a time and relog to check if it works, it didn't).
![image](https://user-images.githubusercontent.com/69940910/90698493-21908780-e281-11ea-8959-5167a0179013.png)

**Comment by lilimx** [comment]
Hey,

I close this ticket, because Harbinger and Rune of Breaking working correctly.
If you're thinking it's broken somehow, please feel free to create a new ticket.
