### ISSUE TITLE
"restricted to Order for #" after logging off destruction character

### ISSUE THREAD

**Issue by awmc82** [WarEmu/WarBugs#16699]
**Expected behavior and actual behavior:**
-Expected behavior: Able to log off a destro toon and able to log onto another destro too

-actual behavior: logged off my BO and got a restriction to order side.

**Steps to reproduce the problem:**
Not sure how to reproduce as I just logged off like I normally do, in a zone I have logged off in before (CW), and did nothing different. 

**Testing Screenshots/Videos/Evidences (always needed):**
![screenshot_003](https://user-images.githubusercontent.com/31575199/81239202-c7b5cb80-8fc9-11ea-8447-e9b1dea764f6.jpg)

**Comment by Kaelang** [comment]
Did you play an order character 20 minutes ago?

**Comment by awmc82** [comment]
Nope, I have not played my Order character in like 3 weeks. I did log over after I got the restriction to see if it would reset it or make it locked to destro side. That did not happen though.

**Comment by Kaelang** [comment]
Merging https://github.com/WarEmu/WarBugs/issues/15557.

**Comment by awmc82** [comment]
![screenshot_004](https://user-images.githubusercontent.com/31575199/81314751-18bbd300-904f-11ea-873c-b2c7eb3e33c9.jpg)

Logged on this morning (have not been on for about 6 hours) to get "restricted to order" again. The last character I played was my Shaman.

**Comment by Kaelang** [comment]
Please comment on the merged report and don't duplicate comments.

Locking this.
