### ISSUE TITLE
Zealot harbinger of change to stagger bugged

### ISSUE THREAD

**Issue by pkfsa** [WarEmu/WarBugs#16691]
My mouse has programmable buttons and one of them is programmed to press harbinger and then after a short delay to press stagger. I can press it again afterwards to cancel harbinger. Prior to today's patch this sequence worked just fine. Here is a GIF of what happens https://gyazo.com/f27ed1c3de72c9d228a1f9e4afc6a453
I tested the same exact thing on my runepriest and find that it works just fine https://gyazo.com/be08d2942981316067424d2e1af5fa44

**Comment by grunbag** [comment]
Try it slowly

**Comment by pkfsa** [comment]
Yes it works slowly but that is not practical whatsoever

**Comment by grunbag** [comment]
Ill check for the delay

**Comment by RoR-Zomega** [comment]
The server forces a GCD delay between turning Harbinger of Doom on and being able to use another ability, and also when turning Harbinger of Doom off and being able to use another ability. The client doesn't respect this however and will play out the animation for the ability if used immediately after turning HoD on/off but the ability won't actually do anything (i.e. no damage, no healing, etc).

To test, go to the training dummy and setup HoD to be ability 1 and Tzeentch's Cry (instant-cast damage spell) to be 2. Target the dummy and quickly press 1 then 2. HOD will turn on, the animation and laser beam for Tzeentch's Cry will appear but no damage will happen. Tzeentch's Cry will not go on cooldown.

Then, do this again while HOD is turned on already, It will turn off HOD, display the ability animation and laser beam without doing damage, but this time it will also put the second ability used on cooldown even though it failed.

To my knowledge HOD has always been bound to the global cooldown. It also has a delay between being pressed and the stats actually updating (confirmed by doing a .getstats after pressing HOD and still seeing the old stats). If Rune of Burning works differently and is actually off the GCD then this is interesting and they probably should work the same.

As I said though, the client acts like HOD doesn't trigger a global cooldown; the delay appears to be enforced server-side only.

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by Kaelang** [comment]
Fixed as of 13/05/2020 patch. Please re-open if issue persists.

**Comment by pkfsa** [comment]
I have noticed a bug with Rune of Breaking on Runepriest where it sometimes does not activate. I have not figured out what causes this yet. https://i.gyazo.com/baead21179f445fd1c371def998f401f.mp4
