### ISSUE TITLE
character with sov alt shoulder wont load game

### ISSUE THREAD

**Issue by acidicrain** [WarEmu/WarBugs#16694]
**Expected behavior and actual behavior:**
expected to be able to get past loading screen.
can not get past loading screen.

found a person with similar problem.
comon to both was we were using sov shoudlers as alt apperance

my toon

https://www.returnofreckoning.com/armory/character/653309
Bloodlord shoulders with alt sov look

 https://www.returnofreckoning.com/armory/character/658604
invader with sov shouldlers

**Steps to reproduce the problem:**
log in, dont have toons with sov to try alt appearance with

**Comment by Kaelang** [comment]
Similar report to https://github.com/WarEmu/WarBugs/issues/16688 however the 16688 report has people able to login. Will keep this open as acidicrain has spoke to both myself and Sioding trying to help getting him online.

**Comment by acidicrain** [comment]
the similarity exists y, my too has those shoulders as alt appearance, they are also not shwoing in his picture. so  cause/solution might be similar

**Comment by MordecaiEth** [comment]
my dps sov shoulders have gone missing as well on my black orc - I posted it just a moment ago.

**Comment by z0nkaT** [comment]
my dps sov shoulders are missing to on my black orc

**Comment by Dayt-gif** [comment]
I also had sov alt on my char, i cannot log in at all

**Comment by Dayt-gif** [comment]
I also had sov alt on my char, i cannot log in at all. Problem started yesterday and is still in effect

**Comment by jinsu0716** [comment]
I have the same problem.
The item disappeared from the store, And an error appears in the game.
:(

**Comment by acidicrain** [comment]
Any news on the problem. Still can not get the black orc past loading screen

**Comment by Kaelang** [comment]
To 'address' the situation - we know about the problem and the devs are looking into it.

**Comment by Iamwithstupid** [comment]
can confirm, off sov BO shoulders gone.
make hp regen great again!

**Comment by Kaelang** [comment]
Fixed as of 13/05/2020 patch. Please re-open if issue persists.

**Comment by acidicrain** [comment]
can log in, so confirm closed
