### ISSUE TITLE
Screenshots are not working

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#16696]
When you press "print screen" it will take a screenshot, and you'll see it's working as you get a message in your text window to say "taking a screenshot". Today our group took a few screenshots, and all saw this message. But it hasn't saved it to the screenshots folder. We've checked the game files and can't see a new folder that this has gone to.

**Steps to reproduce the problem:**

Please advise where these are now being saved to, or if they're not working, put a fix in to get the screenshots to save to a folder again. Thanks!

**Testing Screenshots/Videos/Evidences (always needed):**

I wish I could, but it's not working!

Update, press Prt Sc whilst in the game then CTRL&V in another programme is a workaround for now. Although you need to minimise the game window and click on your desktop and do this if you want to include the chat box and interface too. I've added the detail of "Taking a Screenshot" so you can see it reports that this function is happening - despite not saving an image anywhere. 
![image](https://user-images.githubusercontent.com/22262165/81301035-6a288a00-9070-11ea-88bf-869d14ddadae.png)

**Comment by Kaelang** [comment]
Screenshots are working for me. Both chat-prompt in-game, and new screenshot in the screenshots folder.

**Comment by Senthoi** [comment]
I'm afraid it's still not working on my machine. I have run the repair tool on the launcher today, and tried again too. I've also tried Prt Sc with other programmes, which work fine.

Whandall (a guild member also experiencing this issue) has said that it is working for him now after the recent patch. I am waiting to hear back from a couple other guild members who had this same problem, and have asked them to report in here if it is still an issue.

**Comment by Senthoi** [comment]
Right, I found a fix. Seems it was the latest Windows update knocking permissions off. Just in case anyone else has this problem, here it is :) https://www.reddit.com/r/windows/comments/3q6r8j/windows_10_not_saving_screenshots/
