### ISSUE TITLE
Beastlord Skully for Choppa not showing after patch

### ISSUE THREAD

**Issue by AllahGolden** [WarEmu/WarBugs#16690]
The beast lord skully shows no cosmetic when in the armour slot or appearance slot
![Return Of Reckoning Screenshot 2020 05 06 - 13 10 58 04](https://user-images.githubusercontent.com/64919517/81207411-81e20e80-8f9b-11ea-8cb8-cde24973c284.png)
Steps to reproduce : Not sure as last night i had the bone jaw and logged in today and could not see it.

**Comment by Kaelang** [comment]
- Fixed an issue causing Choppa Beastlord helm being invisible.

Please re-open if issue persists.
