### ISSUE TITLE
[CHOPPA]

### ISSUE THREAD

**Issue by Kaya1106** [WarEmu/WarBugs#16706]
Don't know if the issue is still reported or not.
But it's a very annoying one in PvP.

While in Morale2 Focused Mind, I'm always pulled or aspi by Choppa while I'm supposed to be immune to all CC.

Do you know this bug ?

Can you fix it asap?

**Comment by Kaelang** [comment]
Pulls aren't listed in the list of effects that Focused Mind makes you immune to.
