### ISSUE TITLE
Bastion Stair - Kaarn the Vanquisher's skull mechanic not functioning

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#16704]
**Expected behavior and actual behavior:**

The mechanic for Kaarn is that skulls are supposed to spawn upstairs in the boss room. Failure to kill these skulls results in things happening such as him dropping persistant AOEs on the floor, gaining damage buffs and dropping aggro. However, during probably the last 3-4 runs I have done on Bastion Stair the skulls haven't spawned and the boss has become a simple "tank and spank" affair.

The mechanic where he goes crazy if pulled off his raised platform still seems to work fine.

**Steps to reproduce the problem:**

Fight Kaarn the Vanquisher (mid-wing boss - not the final boss in the ring of fire). Ensure all centre screen messages are enabled as this indicated when the skulls spawned. Assuming he bugs out again no messages will be displayed as no skulls are spawned.

**Testing Screenshots/Videos/Evidences (always needed):**

I'm not able to capture video of the bugged runs showing the mechanic failing.

**Comment by grunbag** [comment]
Just tested and it works fine

**Comment by grunbag** [comment]
Add more infos If you find how you bugged him
