### ISSUE TITLE
Tooltips not displaying number values.

### ISSUE THREAD

**Issue by Sahtka** [WarEmu/WarBugs#16709]
It has been a week or so since the tooltips on all of my abilities have shown all their values as 0. This is a little frustrating. I would like to know how much damage is done by an attack, how much healing is done by a heal, etc. It is hard to strategize or plan things without this knowledge. 

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Isn't a game bug - check Game Support on forums.
