### ISSUE TITLE
Magus Pink Horror stacks fall off at a range far less than 25ft (roughly 5-6)

### ISSUE THREAD

**Issue by Nazzywarhammer** [WarEmu/WarBugs#16705]
**Expected behavior and actual behavior:**
Pink horror demonic empowerment buff should last while youre within 25 feet of your pet, However it falls off at around 6 feet. I asked around for awhile and got absolutely 0 responses. I JUST started playing so I found it a little hard to believe this wasn't reported yet. but who knows. here we go.

This is a screenshot of me within pinkhorror range.

![Nazzy with stacks](https://user-images.githubusercontent.com/64950416/81264794-48db8580-8fff-11ea-85dd-d1be862ea3b6.jpg)

This is me outside of the pink horror range.

![Nazzy no stacks](https://user-images.githubusercontent.com/64950416/81264834-58f36500-8fff-11ea-8524-37d14b2ee707.jpg)

for point of reference this is me using a flamer instead to depict the 25 feet.

![flamerstacks](https://user-images.githubusercontent.com/64950416/81264879-66a8ea80-8fff-11ea-8b6f-c7245be74aba.jpg)

Now this is me outside of my flamer buff range.

![Flamenostacks](https://user-images.githubusercontent.com/64950416/81264903-6e688f00-8fff-11ea-8348-64908e20bf60.jpg)

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Nazzywarhammer** [comment]
EDIT: Please be aware the flamer in the middle is NOT my flamer, The flamer that has the target icon over it is mine :^)

**Comment by Kaelang** [comment]
- When you are within 26-50 feet of your daemon, you will neither lose nor gain Unholy Empowerment stacks.

The flamer in the picture isn't 25 feet away, probably closer to the 50 feet range.
