### ISSUE TITLE
MMR did not reset for season 1? Wrong mmr gains

### ISSUE THREAD

**Issue by keunglh** [WarEmu/WarBugs#16701]
Not really sure the best way to title this so change it as you see fit Mr. Dark Elf Lover. 

**Expected behavior and actual behavior:**
From what I have heard through the grapevine, when calculating MMR, you're supposed to relatively large swings in the first 10 or so matches until it stabilizes, and the more that you do eventually you're only going to be gaining or losing single digit points.

I'm about 5 ranked matches in this season, and I have not earned more than 6 mmr for a win. My MMR before the supposed reset was 1623, and after my first ranked win I jumped to 1628. Thinking I might have earned 1628, the next ranked that I won, I went up to 1630, so I only earned +2 mmr for my second ranked match?

Unless the MMR calculations was changed or something, I was expecting to get larger swings in my MMR, and be reset from 1500. 

**Steps to reproduce the problem:**
All I can ask is to potentially check through the matchmaking logs for my character? 

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/14348489/81249136-89c5a100-8fe3-11ea-87f1-0a08a6edfb2e.png)
![image](https://user-images.githubusercontent.com/14348489/81249161-9813bd00-8fe3-11ea-9f59-461932da9034.png)

**Comment by Kaelang** [comment]
The MMR is being looked at on an overall scale - and the devs are aware of the nuances within the system.

We won't be looking through individual cases.
