### ISSUE TITLE
Resist Buffs Not Working

### ISSUE THREAD

**Issue by maphyr** [WarEmu/WarBugs#16702]
I press "Prismatic Shield" and my resists do not change.  The last time this happened it is only a visual bug but when I type .getstats it is still the base resists.

**Comment by maphyr** [comment]
https://i.imgur.com/HoiW5Mn.png

**Comment by Kaelang** [comment]
I need pictures of the tooltip, before and after .getstats and other buffs you have on you.

**Comment by Kaelang** [comment]
Closing - no further information.
