### ISSUE TITLE
Opressing blow tactic not working properly

### ISSUE THREAD

**Issue by Bochr** [WarEmu/WarBugs#16714]
Chosen tactic giving 15% crit with great weapons dont display working. Please help
![Breakit_000](https://user-images.githubusercontent.com/63914713/81342950-63bc0180-90b4-11ea-8d2b-1de673b20b05.jpg)

**Comment by Kaelang** [comment]
Need a before and after picture, using .getstats

**Comment by Xicoz** [comment]
I replicated this, and getstats shows its working correctly as shown in SS's (character UI is only updating as 1%) 
![Daemon_006](https://user-images.githubusercontent.com/44329952/81462030-5adf3480-9175-11ea-9e70-be08b15ff2ff.jpg)
![Daemon_007](https://user-images.githubusercontent.com/44329952/81462037-66326000-9175-11ea-8c5a-b4f275937169.jpg)

**Comment by Bochr** [comment]
Yes you are right, its working

lør. 9. maj 2020 04.47 skrev Xicoz <notifications@github.com>:

**Comment by Bochr** [comment]
Thanks for help

lør. 9. maj 2020 10.42 skrev Bo Christiansen <bochr82@gmail.com>:
