### ISSUE TITLE
[Quest] Ascension

### ISSUE THREAD

**Issue by pthiel168** [WarEmu/WarBugs#16710]
During the Destruction Quest Ascension you need to kill 
Defense Councilor Greysword
Griffon Commander
Military Advisor Karagrim 

Killing the Griffon Commander does not register in the Quest line and the quest cannot proceed.

**Comment by Lheana** [comment]
It works fine for me.

**Comment by pthiel168** [comment]
I went to try again and it is still broken, see the attached screenshot:
![Paternarum_000](https://user-images.githubusercontent.com/8930990/81828932-5c5b8480-9508-11ea-8485-5249c140e19e.jpg)

**Comment by Lheana** [comment]
Kill him when inside the PQ area.
