### ISSUE TITLE
Riekwald Fort not advancing

### ISSUE THREAD

**Issue by mythyrylfalcon** [WarEmu/WarBugs#16717]
I was present in the Riekwald zone at the Rieland lock, but didn't receive a reservation. I went out the fortress doors toward Altdorf because I didn't have a Fort window on my State of the Realm add-on and was hoping that would prompt a refresh. I was then locked out of the fort and various parties indicated that the Fort stages didn't advance properly. I contacted Wargrimnir via Discord and advised him of the sitation. I have no further first hand knowledge.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/51804717/81371808-b219d200-90ad-11ea-91e9-a86f796abfec.png)

**Comment by Kaelang** [comment]
As stated in chat, the devs were online and aware of this - this ticket does not provide any further information to help replicating the issue so I'm closing this.
