### ISSUE TITLE
Discipline not converting via Breaking/Harbringer

### ISSUE THREAD

**Issue by DypfrystBram** [WarEmu/WarBugs#16719]
The tactic is getting treated differently than stats contributed by gear. 
https://imgur.com/yVqxWUd
https://imgur.com/i6wbcoH
First one - ability off without discipline
second - ability on without discipline
third one - ability on with discipline
forth one - ability off with discipline

**Comment by Verenduum** [comment]
That's correct, rune of breaking/harbinger only reflects stat bonuses on items, not tactics and not renown points. So this is working as intended.

**Comment by RoR-Zomega** [comment]
![image](https://user-images.githubusercontent.com/60266177/81386358-c80aaf80-910c-11ea-8456-7a235adf8ae2.png)

No mention of converting tactics in the ability description.

**Comment by wwright72** [comment]
I can confirm that runi conversion skill currently isn't converting int to wp.

**Comment by Kaelang** [comment]
If the RP version isn't working as intended - please open a new ticket.

**Comment by grunbag** [comment]
I fixed rp bug for next patch

**Comment by DypfrystBram** [comment]
I swear it was common knowledge it did convert. I bet you can go back not too long ago when it did.

**Comment by RoR-Zomega** [comment]
If it did then that was a bug :)
