### ISSUE TITLE
Orc Weapon as Rewards for  Order side Chapter 7 hard pq (Lissariel's Glade)

### ISSUE THREAD

**Issue by Lnternsmite** [WarEmu/WarBugs#16726]
![Khenrac_007](https://user-images.githubusercontent.com/53047875/81429195-71f93480-912b-11ea-8705-20c5961aeec3.jpg)

heres a screenshot of the orc axe in a gold bag for the chapter 7 pq.  I got excited for the look until it said "Race: ORC"

**Comment by Kaelang** [comment]
Fixed as of 13/05/2020 patch. Please re-open if issue persists.
