### ISSUE TITLE
Ranked 5v5 not aborted

### ISSUE THREAD

**Issue by M0rw47h** [WarEmu/WarBugs#16723]
Expected behavior: 
Game should be aborted due to lack of participants (less than 6v6).

Actual behavior:
Game started as 5v5 and continued until destruction has won.

Happened around 16 Altdorf time.

Testing Screenshots/Videos/Evidences (always needed):

![image](https://user-images.githubusercontent.com/35219756/81413492-d1643e00-9145-11ea-8c49-975f372d7fe1.png)

**Comment by Kaelang** [comment]
5v5's are currently going through as a still, balanced, match. This usually happens when 6v6 queue, and 1 from each side leave.

It's not perfect - but the devs know it's happening. Feel free to report this on Suggestions if you think a change needs to happen.
