### ISSUE TITLE
Full Vanq but no ToK Unlock.

### ISSUE THREAD

**Issue by crazyturkme** [WarEmu/WarBugs#16720]
Hello there,

as u can see i have full vanq gear but i didnt unlock the tok title. I cannot get inv meds from last zones also. Tryed to undress and reequip all but not worked.

I am Looking for Help

![11111](https://user-images.githubusercontent.com/45875969/81404119-762e4d80-913d-11ea-982e-c2c972be5ecc.png)

**Comment by Lheana** [comment]
It works fine for me. I guess something has not been correctly updated on your game, and it prevents you from seeing the new ToK unlocks.
