### ISSUE TITLE
No Vanquisher set unlock for invader medallions out of loot bags

### ISSUE THREAD

**Issue by Bargmeps** [WarEmu/WarBugs#16729]
Hello,
after my last two RvR rounds, my white lion Talesca received a golden and purple loot bag without any invader medallions in them despite me waring the full Vanquisher set. So I checked my Tome of Knowledge and saw that I had the title "The Vanquisher" but was lacking the achievement for the set despite wearing it. I took it off and on again but nothing changed.
Could You please fix my issue? I would like to be able to obtain the invader medallions out of the loot bag just like the new system is supposed to work.
My white lion is RR 68 and has the name Talesca.

With best regards.

![Talesca_033](https://user-images.githubusercontent.com/32279670/81443581-f53f7800-9175-11ea-898b-b56fd297a6d2.jpg)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16720
