### ISSUE TITLE
Squig Herder Bloodlord Ranged Weapon Has Melee Stats

### ISSUE THREAD

**Issue by WJamesLord** [WarEmu/WarBugs#16722]
The Bloodlord Shoota for Squig Herder has melee stats, which doesn't help much for a range spec squiggy.  Please see the attached image.
![Shoota](https://user-images.githubusercontent.com/2352429/81410485-cb9f3600-910e-11ea-815f-a085d1278adc.png)

**Comment by Kaelang** [comment]
If you're suggesting these stats could cater towards the RSH, please use the Suggestions forum.

**Comment by Kaelang** [comment]
Keeping this open for verification as per PM request.

**Comment by Kaelang** [comment]
![image](https://user-images.githubusercontent.com/60117106/82127482-d2334a80-97ab-11ea-918a-cc02f9200529.png)
There is a RSH weapon available in the same tier rewards.

Closing.

**Comment by WJamesLord** [comment]
Hey, K.

Yeah, I saw the other one after I picked the fail bow.  I just expected similar ranged stats.  Any chance I can swap bows?
________________________________
