### ISSUE TITLE
No xp from scenario kills at the moment

### ISSUE THREAD

**Issue by Tartuccio** [WarEmu/WarBugs#16728]
**Expected behavior and actual behavior:**
Not getting any xp from kills in scenarios, general chat seems to confirm that it's happening for everyone. Scenario win xp is still there.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Please provide a screenshot of your combat log / XP bar (before and after) whilst killing players to review if any XP is being given, without the visual cue.

**Comment by Tartuccio** [comment]
Scenario is Blood of the Black Cairn t1. 

https://cdn.discordapp.com/attachments/708373950547361876/708374024983412847/screen1.png
My xp at the start.

https://cdn.discordapp.com/attachments/708373950547361876/708374052913283072/screen2.png
After a kill.

https://cdn.discordapp.com/attachments/708373950547361876/708374076783067228/screen3.png
Some time later in the match, still at same renown/xp values.

**Comment by Kaelang** [comment]
Tested in Isha - looks to be working fine. Will test in Cairn.

**Comment by Vayra** [comment]
Blood of the Black Cairn, as an objective scenario, has kill xp and renown turned off during the game. You get a bonus of XP/renown at the end of the game based on your team's score and an 'estimated number of kills'. IE, it's an anti-farming feature.

**Comment by Kaelang** [comment]
Thought this report was across all Scenarios? Can you let me know if you've only been running Black Cairn?

**Comment by Tartuccio** [comment]
Yeah I was only doing Cairn. I had no idea there was such a thing for Cairn, never noticed. In that case can scrap this and sorry for wasting time.
