### ISSUE TITLE
Reikwald fort bug

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#16731]
Once riekland is captured by destroy, reikwald fort should activate, but doesn't, rams spawn, but don't do anything. SOR doesn't even pick it up, but people do still get reservations (as shown in SS)
![Daemon_005](https://user-images.githubusercontent.com/44329952/81460811-4b5bed80-916d-11ea-869d-bad77047cbf2.jpg)

**Comment by Mcnite** [comment]
I also received that bug for the Reikwalkd fort. This yellow bug message spammed aprox 40 times throughout the whole fort. 

I did not receive medallions or renown at the end.

![Fort Bug](https://user-images.githubusercontent.com/65054912/81461686-4c3b5200-9162-11ea-8532-e090622a77cc.png)

**Comment by Xicoz** [comment]
that yellow message is when you managed to get in without a reservation, which is why you didn't receive any rewards

**Comment by Kaelang** [comment]
The devs were made aware of this as it happened - as this does not provide any information as to how to replicate such issue I am going to close this.
