### ISSUE TITLE
Died in SC, No Respawn

### ISSUE THREAD

**Issue by TooMuchNotEnough** [WarEmu/WarBugs#16739]
**Expected behavior and actual behavior:**
Was playing normally, died while fighting marauder and witch elf. Respawn Counter did not show.
Exited game to get out of it. Do not know if it would persist after SC closes.

**Steps to reproduce the problem:**
Dont know.

**Testing Screenshots/Videos/Evidences (always needed):**

![Fieldsoffire_000](https://user-images.githubusercontent.com/65060683/81465454-27090c80-917f-11ea-8602-9c57bc2aafab.jpg)

**Comment by Kaelang** [comment]
When this happens, type /reload.
