### ISSUE TITLE
Gunbad - Dying and releasing during Glomp da Squig Masta respawned you immediately at your body, still in the fight

### ISSUE THREAD

**Issue by Rydiak** [WarEmu/WarBugs#16733]
Several of my party members and myself died during a fight with Glomp da Squig Masta, but upon releasing from body we were immediately respawned right where we died and back in the fight.  We still received a stack of the wounds debuff.

**Comment by Xicoz** [comment]
this also happened to my group

**Comment by Vayra** [comment]
This happens to all the end bosses in gunbad at the moment (including Solithex).

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16579
