### ISSUE TITLE
BE Portal

### ISSUE THREAD

**Issue by Badboykiller123** [WarEmu/WarBugs#16736]
We did all 3 bosses in BE dungeon on destro, but when we got to the last boss the portal was still up and we killed all the 3 bosses that have the items but nothing happened after we killed the three bosses.

**Comment by Kaelang** [comment]
Please follow the format when reporting bugs. Additional screenshots / replication notes need to be added.

**Comment by RoR-Zomega** [comment]
@Badboykiller123 going by the latest patch you need to now kill 4 bosses to get to Barakus the GodSlayer.

1)  Korthuk the Raging. This is the centaur hero with 2 centaur champions. This boss does NOT drop items needed for Barakus but needs to be killed anyway.
2) Culius Embervine. The skeleton boss. Drops one of the 3 items needed.
3) Sarloth Bloodtouched. The giant red dog/spawn boss. Drops one of the 3 items needed.
4) Yozig the Blooded. This boss used to be skippable but is now required as of the latest patch as a bug has been fixed. Drops one of the 3 items needed.

Before you only needed 2 items.

**Comment by Kaelang** [comment]
Closing.
