### ISSUE TITLE
Gunbad - Region Unavailable with teleport to city still exists

### ISSUE THREAD

**Issue by Rydiak** [WarEmu/WarBugs#16734]
When zoning into the final boss area of a Gunbad wing (this happened with left wing, in particular), the old Region Unavailable with a teleport to Altdorf occurred.  This was supposed to be fixed in a previous patch.

**Comment by Kaelang** [comment]
Please supply screenshots to support this issue.

**Comment by Rydiak** [comment]
![Rydiak_097](https://user-images.githubusercontent.com/15963532/81481047-fa8ed800-91f2-11ea-8d25-d7c556154a28.jpg)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/13799
