### ISSUE TITLE
Reik Fort  bug no contribution 

### ISSUE THREAD

**Issue by Mcnite** [WarEmu/WarBugs#16735]
I recieved this yellow text bug for the Reikwalkd fort. This yellow bug message spammed aprox 40 times throughout the whole fort. I received this bug pretty early on into the fort and it spammed throughout the entire fort.

At the end when the fort was completed/done, I did not receive medallions or renown at the end. My friend on discord in the fort as well received invader medallions and renown

![Fort Bug](https://user-images.githubusercontent.com/65054912/81461755-d4215c00-9162-11ea-97c4-dfe6233acf9d.png)

**Comment by EndlessPosts** [comment]
Ghemeyhas - Order

Same exact thing happened to me. I entered the fort right alongside the rest of my warband and most of them got contribution. I started getting the message shortly after the announcement that the fort wasn't working but it was being worked on and then we got another announcement that the UI was going to be wrong but that it would continue forward. 

I received no renown or medallions at the end. I'm hoping it's possible to get some compensation for the hours I pushed with the warband. I guess I should have clipped my entire screen but I just started playing this game and someone in the fort told me to just screenshot the message. 

![BugReport](https://user-images.githubusercontent.com/65055153/81461837-9f65d280-916b-11ea-8fc6-ca622e8d763f.PNG)

**Comment by Xicoz** [comment]
this happens if you somehow get into the fort without a reservation, its happened to me before (no rewards when this happens)

**Comment by EndlessPosts** [comment]
Did they ever compensate you or do you just spend all those hours with the war band to somehow not get a reservation with them and then in the end get no loot?

**Comment by Mcnite** [comment]
I have never been compensated.

**Comment by Xicoz** [comment]
no, but you get contribution from the zone before, once the zone is locked, no more contribution for you, if ya didn't earn the spot in there, then theres nothing to compensate for, just be happy you got the RR from kills in there id say :)

**Comment by EndlessPosts** [comment]
Whatever I guess, next to nothing makes sense in this game and the limited amount of information in the actual game doesn't help. Guess I'm done dabbling with this one.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16409
