### ISSUE TITLE
Fort bug No loot without bug message

### ISSUE THREAD

**Issue by Mcnite** [WarEmu/WarBugs#16737]
I did a fort again and this time had a reservation and no yellow bug error messages. Everyone got 30k renown and invader medallions. I did not receive anything.

Here is a screenshot of the fort ending and my logs with no medallion or renown messages.

![Fort no loot again](https://user-images.githubusercontent.com/65054912/81464072-9a0c8600-9173-11ea-80ed-593e61e71bc3.png)

I did a fort earlier (and posted a bug earlier) and received yellow bug messages. This time **I did not receive any error messages and still did not receive any renown or medallions.**

**Comment by Xindar702** [comment]
I would post a screenshot but everything Mcnite said happened to me as well. I made sure to get contribution in Eataine by capturing BOs and Keep Defense prior to heading over to Fort defense in Shining Way.

-Xindar

**Comment by Kaelang** [comment]
Did you get the reservation popup before the fort started - or did you simply run into the zone?

**Comment by Mcnite** [comment]
> Did you get the reservation popup before the fort started - or did you simply run into the zone? 

Yes, I received a reservation popup before the zone.

**Comment by Kaelang** [comment]
Likely did not contribute enough if other people received the rewards.

If this persists, please re-open the ticket with more information on how we're meant to replicate such issue. As highlighted in the chat box, other players received their rewards. Which essentially makes me believe your contribution wasn't high enough within the fort.

**Comment by Mcnite** [comment]
> Likely did not contribute enough if other people received the rewards.
> 
> 
> 
> If this persists, please re-open the ticket with more information on how we're meant to replicate such issue. As highlighted in the chat box, other players received their rewards. Which essentially makes me believe your contribution wasn't high enough within the fort.

I don’t mean to argue but I strongly believe that I definitely had enough contribution. I do not think that is the issue.  

I was with a warband the whole time participating, meanwhile there were afks who received renown and medallions. I’ll try to document everything next time I do a fort. 

It’s just odd that this has happened 2/2 times when doing forts (i have only done two forts ever), while I have heard of this bug from friends getting it once with the yellow bug message, with or without error messages I received 0 renown/medallions even with getting the reservation spot.

**Comment by Kaelang** [comment]
Which two forts, attacking or defending?

**Comment by Mcnite** [comment]
Defending reikwald and defending stonewatch

**Comment by Mcnite** [comment]
> Which two forts, attacking or defending?

Will I received compenstaion for the two forts? I never recieved medallions or any renown at all. 
I am not talking about the loot bags. I am talking about the invader/vanq medallions and 30k renown everyone gets at the end of the fort just from participating. 

Once again I strongly believe I participated enough as one of the main tanks of a warband.

**Comment by Kaelang** [comment]
There is no 'compensation' service. We're a volunteer project - by listing this report devs may be able to stop this happening moving forward.

**Comment by Mcnite** [comment]
> There is no 'compensation' service. We're a volunteer project - by listing this report devs may be able to stop this happening moving forward. 

Alright I just thought since yesterday reikwald fort was bugged and wasn’t starting yet 40 min later people still received invaders medallions as if they completed the fort

**Comment by Kaelang** [comment]
The 27/05 patch has addressed some contribution issues / porting issues with forts. Please re-open if this is issue persists.
