### ISSUE TITLE
Suicides and kills

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#1673]
Pretty old problem, but i've found no report for it. It is possible to suicide by taking falling damage, in which case attackers will be denied a kill, exp, renown, etc. I've not tested, but i'm pretty sure that same thing happens in other similar cases (jumping into lava, getting killed by guards, etc).

**Comment by MKorin** [comment]
Same for BW / Sorc self dmg death

**Comment by Evildoor** [comment]
Right. And Slayer/Choppa too.

**Comment by noisestorm** [comment]
Or lava.

**Comment by Evildoor** [comment]
Changelog 12th March 2016
- Kill credit will now be given for suicides.
