### ISSUE TITLE
Altdorf siege (9th May 2020): loot rolls for another instance were being sent to our screens

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#16745]
**Expected behavior and actual behavior:**

During our Altdorf siege we were recieiving notifications of loot rolls in another Altdorf siege. The loot roll window was not tied to the status of our city, i.e. we saw their loot rolls for the end of a stage while we were still in the middle of the stage.

The rolling for our own loot stages was fine, although they could've been broadcast to another instance (we don't know this).

**Steps to reproduce the problem:**

I have no idea.

**Testing Screenshots/Videos/Evidences (always needed):**

This is from stage 1. All of the people in this window were in another instance. Our instance's stage 1 had not ended yet (doors at 7% in our instance). We also saw similar loot roll windows for stage 2 and 3.

![roll1](https://user-images.githubusercontent.com/60266177/81469367-6d408900-91dc-11ea-8e12-60086128d906.jpg)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/15846
