### ISSUE TITLE
[SORC] CD reduction issue on Infernal Wave ability

### ISSUE THREAD

**Issue by Ararindys** [WarEmu/WarBugs#16746]
Usual CD of Infernal Wave: 10s --> ability works correctly every 10s

When there is no issue:
CD of Infernal Wave with Neverending Agony tactic and no other CD reduction bonus: 5s (Neverending Agony give 5s of CD reduction) --> ability works correctly every 5s
CD of Infernal Wave with BO CD reduction (Waaaaaaagh! ability + Mor' Choppin' Dem! tactic) and no other CD reduction bonus: 5s (BO give 5s of CD reduction) --> ability works correctly every 5s
CD of Infernal Wave with Choppa CD reduction (Chopp Fasta!) and no other CD reduction bonus: 5s (Choppa give 5s of CD reduction) --> ability works correctly every 5s

When the issue is observed:
CD of Infernal Wave with Neverending Agony tactic and BO CD reduction: no CD (5s reduction from Neverending Agony and 5s reduction from BO) --> ability doesn't work correctly (see description below)
CD of Infernal Wave with Neverending Agony tactic and Choppa CD reduction: no CD (5s reduction from Neverending Agony and 5s reduction from Choppa) --> ability doesn't work correctly (see description below)

Description of the issue (during the period in which there is normally no CD): 
It is possible to use it once at the beginning of the "no CD" period but after that the ability doesn't work correctly until the "no CD" period is over.
- Visually the ability is not recharging which allow us to think that the "no CD" period is well apply
- In reality, the spell is not "spamable" like it should be during this period and there is still a 5s CD

This kind of association of Choppa or BO with Sorc is essential to use correctly the power of an AOE Sorc. This issue is really disturbing and quite frustrating when we play an AOE Sorc and we try to create a good bombing group.

It could be really nice to solve this issue quickly.

Thanks

**Comment by Grock-r** [comment]
Your description is very confusing, but i am pretty sure IW was specifically nerfed a while ago so that its cd can't be reduced below 5 seconds

**Comment by Vayra** [comment]
IW is the only ability to my knowledge that's been nerfed to have a minimum cooldown of 5 seconds.

**Comment by Kaelang** [comment]
This is intended.
