### ISSUE TITLE
Ranked Solo SC Tie reward bugged

### ISSUE THREAD

**Issue by azpe** [WarEmu/WarBugs#16749]
**Expected behavior and actual behavior:**
At the end of Ranked SCs, if battle ends in a Tie, you should get 10 Triumphan Emblems, but sometimes you get just 5.

**Steps to reproduce the problem:**
Play Ranked Solo SC and if the batlle ended in a Tie you get 5 Triumphant Emblems instead of 10.

**Testing Screenshots/Videos/Evidences (always needed):**
https://streamable.com/fejdua

**Comment by Kaelang** [comment]
Games that end in 0-0 aren't classified as a tie, but a loss for both teams, which is where the reduced rewards come into play. If a game ends at 50-50 or 450-450 then a tie would claimed and appropriate rewards given.

Note: A 0-0 although classed as a 'loss' does not impact MMR as a loss. 

Thus, working as intended.
