### ISSUE TITLE
Briefly very rich

### ISSUE THREAD

**Issue by GreatHarlequin** [WarEmu/WarBugs#1674]
I was in a WB during a MoM keep take and we were killing lots of destro trying to get into keep. Lots of loot drops when all of a sudden I get a server message after someone killed a destro and it said, "You received 22552 gold."

O.O

I checked my bag and I had 22585 gold. I mentioned it advice chat, but then minutes later it was gone and I was back to my usual 33 gold.

Just wanted to report this in case I got banned for some reason.

**Comment by Evildoor** [comment]
Closing since #1810 is the same but has explanation.
