### ISSUE TITLE
Altdorf Stage 3 (palace): KOTBS can super-punt destro into the order spawn over the barrier

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#16744]
**Expected behavior and actual behavior:**

The barrier around the order spawn in the palace area is too low. This allows a KOTBS with the long knockback tactic to send people over the barrier and into the order spawn area.

**Steps to reproduce the problem:**

Place a destro character approx 3 metres away from the order spawn barrier and have a knight punt him directly towards the barrier with the tactic equipped.

**Testing Screenshots/Videos/Evidences (always needed):**

My corpse after getting super punted in.

![Zomega_309](https://user-images.githubusercontent.com/60266177/81468825-cbb83800-91d9-11ea-9e0e-d3f636e22ba8.jpg)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/15789
