### ISSUE TITLE
[BB] Maggotfiend boss didn't spawn and all doors were closed

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#16748]
**Expected behavior and actual behavior:**
Earlier today we killed Maggotfiend Urhil but didn't finish the instance due to inability to find healer. When we went back in later the boss didn't spawn and all doors were closed so we couldn't progress to next boss and complete instance.

**Expected:**
After killing the boss and coming back later, door should be open.

**Steps to reproduce the problem:**
Kill boss, leave instance, come back later and boss should be gone and no doors open.

**Testing Screenshots/Videos/Evidences (always needed):**

![Vayra_009](https://user-images.githubusercontent.com/1183293/81483882-a65f1480-9241-11ea-8f0d-b3b3cb4ab1dc.jpg)

**Comment by RoR-Zomega** [comment]
@Kaelang same issue as https://github.com/WarEmu/WarBugs/issues/15934. BB/BE don't reset properly if you leave them partially completed causing a soft-lock on progress.
