### ISSUE TITLE
Invader unlock not working

### ISSUE THREAD

**Issue by iantheace** [WarEmu/WarBugs#16747]
Hi, i have the full invader set but an unable to acheive the tome unlock - please see pic below. Have tried removing full set and re-equipping TNA. 

See pic below. This is also stopping me being able to get crests in citites due to the new change :(

![invaderbroken](https://user-images.githubusercontent.com/11569450/81477188-5024ae00-920e-11ea-9e7d-18dbd000a92f.png)

**Comment by Lheana** [comment]
Please show a screenshot of the set bonuses to prove that you have the whole set equipped.

**Comment by Kaelang** [comment]
Closing.
