### ISSUE TITLE
Altdorf Stage 3 (palace): LOS bugs on order barrier allow for unintended healing and hiding

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#16743]
**Expected behavior and actual behavior:**

This is a different issue to https://github.com/WarEmu/WarBugs/issues/15736 where AOEs can pass through the barrier.

If someone who is outside the barrier stands in the corner of the barrier the healers inside the barrier can gain LOS to the person outside and heal them with single target heals. This can be used to keep champions alive with strong heals that shouldn't be useable.

In addition, there are points along the outside of the barrier where players can push into and make themselves impossible to target by the enemy who are also outside the barrier.

**Steps to reproduce the problem:**

For the corner, the location is here:

![image](https://user-images.githubusercontent.com/60266177/81468666-d6be9880-91d8-11ea-88bc-a29bc64d5867.png)

Big blue line is the order barrier, "Healers" is the spawn area where the healers are, X is where the champ can stand to get single target heals.

To make yourself immune to targeting, push in against the barrier as order from the outside (you'll need to slide along to fight the right spots) and have someone as destro try to attack you with targeted abilities.

**Testing Screenshots/Videos/Evidences (always needed):**

Sorry, seems I didn't take a screenshot of the corner bug so I had to use the dodgy MS paint recreation.

**Comment by RoR-Zomega** [comment]
Here it is from the order POV. Blue cross in world and on the mini map.

![Zomega_309a](https://user-images.githubusercontent.com/60266177/81468888-15a11e00-91da-11ea-9cf5-5c3a64dd7c56.jpg)

**Comment by qualteia** [comment]
TO add to this, Magus and BO AOE seems to ignore barrier as well and will still be able to damage and pull players through it (though sadly I wasnt recording earlier when we were pulled through, this still shows the damage through the barrier). https://i.imgur.com/ceRufh9.gifv

**Comment by MaxHayman** [comment]
Should be fixed now please reopen if that is not the case
