### ISSUE TITLE
tooltip not working as intended

### ISSUE THREAD

**Issue by damnatius** [WarEmu/WarBugs#16752]
my tool tips for abilities are showing the ap cost,range,and cd time but its not displaying info about what an ability does.i have checked the forums under game issues,tech issues and bug reports and found nothing that matches this problem.my tool tips are checked in the user settings,i have run the repair option at log in screen,rest my ui and checked for some setting that may affect tool tips by reading the game manual.
i have tried taking screenshots but can find no folder in the ror files to upload them.

i dont know how this has happend so i can not recreate the problem.

if this is not a bug then i am sorry for having wasted your time.
                                                    many thanks :)

**Comment by Kaelang** [comment]
Use Game Support / Technical Support for these types of issues. It's a problem with your files.
