### ISSUE TITLE
"Someone in your group has the quitter debuff"

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#16754]
if you group que atm, you get warned that someone in your group has the quitter debuff (even when noone does), but it still lets you guys que, just throws that message out you X amount of times for however many SC's yall que for.
![Dracula_047](https://user-images.githubusercontent.com/44329952/81494602-c1e11400-926f-11ea-865b-b84c704df427.jpg)

**Comment by Kaelang** [comment]
Just tested this and queued all SC's without the trigger happening. Likely someone in your group either had Quitter (and was replicated based on how many SC's you joined) and/or someone had Quitter and the trigger hasn't reset.

Regardless, if you can record a video of you, and one other person, queuing for SC's and still receiving this error, please submit to this report.

**Comment by Xicoz** [comment]
I had been queing with this group for over 5+ matches and noone had it, but will try to replicate it :)

**Comment by Xicoz** [comment]
i just replicated via inviting a random person in my tier ,t1, (who didn't have quitter debuff) and queing all SC's with him. he also got the "someone in your group has the quitter debuff spam", and we were both still put in que ontop of it. this happens for every que for me(when grouped)
![Dracula_056](https://user-images.githubusercontent.com/44329952/81507532-b8819700-92c3-11ea-9923-fbbc6a499b8f.jpg)

**Comment by Garrthax** [comment]
confirming, we had same issue yesterday in guild scenario group

**Comment by agemennon675** [comment]
Can confirm, the message "Someone in your group has the quitter debuff" is happening but you can still que for scenarios

**Comment by Rydiak** [comment]
I believe this message pops up when trying to queue for Maw of Madness Ranked (Solo) while being in a group. Usually when using Queue Queuer or "Join All".

**Comment by Kaelang** [comment]
This has since been fixed.
