### ISSUE TITLE
"Something has gone wrong when attempting to add contribution to you..." - Fort

### ISSUE THREAD

**Issue by Cirmax** [WarEmu/WarBugs#16756]
![Enyo_000](https://user-images.githubusercontent.com/65120034/81500670-bdcdea00-92a1-11ea-8c68-079ac3ff5fcd.jpg)

**Expected behavior and actual behavior:**
Character name Enyo

Second time this has happened on this character.  Both times I was inside the fort at the time of the flip, did not receive a reservation confirmation but was not removed.  There were less than 200 total players on one side at the time.  Yellow message appears only when capping a flag or near a flag at time of being capped.

Received renown on kills, but end of fort received no medal or contribution.

The first time it happened it was in Reikland fort on May 8th 2020 when the GM had to come and manually advance and conclude the fort, some circumstances and same result

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16409
