### ISSUE TITLE
[CHOPPA] [SLAYER] Detaunt removes all the rage

### ISSUE THREAD

**Issue by Orgruk** [WarEmu/WarBugs#16751]
**"Outta My Face!"** the Choppas' detaunt now removes all the rage accumulated.

You'll find here attached a screenshot of the tooltip and ability effect.

![Orgruk_037](https://user-images.githubusercontent.com/65107497/81493331-d806c880-929f-11ea-97b6-ccdfc880f304.jpg)

**Comment by Orgruk** [comment]
And here's a short video of the detaunt's bug.

[https://youtu.be/gI4IqRo22sg](url)

**Comment by Kaelang** [comment]
"Also outta my face remove your rage since a long time." - Grunbag

Working as intended.
