### ISSUE TITLE
[Magus Pet] Flames of Change

### ISSUE THREAD

**Issue by Critos** [WarEmu/WarBugs#1675]
Flames of Change ( http://i.imgur.com/fidWyEk.png ) seems doesnt work properly. It hits, but only one time and doesnt apply any debuffs on target. АоЕ effect works, but also no debuffs.
Combat log http://i.imgur.com/fjXklVb.png

**Comment by ozarmidrashim** [comment]
Flames of Change is dealing its damage upfront instead of over time.
