### ISSUE TITLE
Zealot 8piece Warlord ability issue

### ISSUE THREAD

**Issue by Fizrash** [WarEmu/WarBugs#16750]
Ability works fine on other players, but as soon as I have none/myself as defensive target it simply refuses to cast/work.

**Comment by Kaelang** [comment]
Video / Screenshots please. Use the format provided.

**Comment by Fizrash** [comment]
[https://www.youtube.com/watch?v=1UYpE7qzqqA](url)

**Comment by grunbag** [comment]
fixed with next patch

**Comment by Kaelang** [comment]
Fixed as of 13/05/2020 patch. Please re-open if issue persists.
