### ISSUE TITLE
2 rams on KV door

### ISSUE THREAD

**Issue by Tazo83** [WarEmu/WarBugs#16757]
**Expected behavior and actual behavior:**

there should be only 1 ram available at the zone when someone spawn it and this time we got 2 rams on our keep
you can see in the screen shot 1 ram at 96 Health and other ram is at 77 Health

**Steps to reproduce the problem:**
i dunno how did order manage to get 2 rams at the same time

**Testing Screenshots/Videos/Evidences (always needed):**

![Tazthenextpup_054](https://user-images.githubusercontent.com/42385505/81501607-fd1c2b00-92e1-11ea-8d55-7bbce8696bd8.jpg)
![Tazthenextpup_055](https://user-images.githubusercontent.com/42385505/81501611-01484880-92e2-11ea-8d4c-7e4d718ff366.jpg)

**Comment by Kaelang** [comment]
Isn't a bug - 4* keep. Technically would be possible to have more.
