### ISSUE TITLE
[BB] NullReferenceException was thrown from OnEnterCombat

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#16759]
**Expected behavior and actual behavior:**
Using Gag Self in BB caused an endless stream of NullReferenceExceptions being thrown, dealing 500 damage in a frontal cone with each one.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Kalyth_012](https://user-images.githubusercontent.com/1183293/81509952-9e20db00-930e-11ea-84a6-6eab263cfb4d.jpg)

**Comment by Vayra** [comment]
It's happened twice for us, both times we used Gag Self near the right wing barrier. So might be something there.

After about 20 seconds of spewing the Exception the game booted me off the server.

**Comment by grunbag** [comment]
can't reproduce, reopen if it still happen
