### ISSUE TITLE
[SCENARIOS] Got kicked form the server

### ISSUE THREAD

**Issue by Sandskid** [WarEmu/WarBugs#16755]
Me, as well as my friends, are getting kicked from server when entering ~every forth T1 scenario. You've got sc pop-up, enter it - game crashes with "Server has closed you connection" pop-up. Of course you get quitter 10m debuff after re-log.

**Comment by Kaelang** [comment]
Played T1 scenarios from 1-16 yesterday and had 0 disconnects. Please check Technical Support / Game Support for help with this. Looks like a connection issue.
