### ISSUE TITLE
Fortress contibution

### ISSUE THREAD

**Issue by Vendatha** [WarEmu/WarBugs#16768]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by dalen** [comment]
You need to provide information about what the bug actually is.

**Comment by Vendatha** [comment]
<!--After being in the fortress for a couple of minutes i got text warning
"Something has gone wrong when attempting to add contribution to you, please report on the bug tracker"
I walked in the fortress and it kept my you have a reservation pop up on the screen even after dismissing it.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16409
