### ISSUE TITLE
Pull skills ignoring walls in fortress. (Butcher Pass)

### ISSUE THREAD

**Issue by azpe** [WarEmu/WarBugs#16763]
**Expected behavior and actual behavior:**
Pull skills must not ignore walls.

**Steps to reproduce the problem:**
Move to fortress, use any kind of AoE pull skill.

**Testing Screenshots/Videos/Evidences (always needed):**
https://streamable.com/syku8p

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16657
