### ISSUE TITLE
Guild leader achievement progression

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#16765]
for the achievements that require killing guild leaders(10, 100) you can progress through these achievements simply by dying as a guild leader.
![Dracula_063](https://user-images.githubusercontent.com/44329952/81521747-be03cf00-930d-11ea-9d2b-d37c1f8566f9.jpg)

**Comment by Kaelang** [comment]
This should be fixed as of the 20/05 patch. Please re-open if issue persists.
