### ISSUE TITLE
Guild coin quests.

### ISSUE THREAD

**Issue by makcuss** [WarEmu/WarBugs#16760]
Good day! I can’t understand why quest "Conspirator of destinies" is not executed. I have 84rr and have been to the rvr many times and have locked zones with my full guild wb and this quest has not been completed more than once. Please check and correct if possible. My other character performed this quest regularly. A similar situation with the quest "order ondone".

Destro/Lucymcclaine

**Comment by Kaelang** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/15591.
