### ISSUE TITLE
Guild Heraldry Emblem

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#16764]
when reserving a guild heraldry, it is very misleading. at guild rank 10 in rewards it lets you choose your guild heraldry (color/shape/pattern/emblem). then at 15 you get to wear it on your cloak but the emblem is missing, and at 20 it shows up. but the guild unlock for 20 shows as it only unlocks for banner's so a lot of guild masters are spending hundreds of gold at lvl 15 trying to keep buying their heraldry reservations because the misleading of the guild rank lvl 20 reward of emblem unlock for banners (when hovering over it) my suggestion is to make the guild 20 reward to say "banner/cloak emblem unlock" or something along those lines, because even at lvl 10/15 after reserving it, if you go back into your heraldry reservations, it shows as you never chose an emblem.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/9791
