### ISSUE TITLE
Pulling through fort walls - both factions (The Maw)

### ISSUE THREAD

**Issue by KySaber** [WarEmu/WarBugs#16766]
https://www.youtube.com/watch?v=xrOdNGtXinI&feature=youtu.be

As shown, the walls doing nothing to prevent pulls through the wall, happening to both factions from either sides.

Edit: Addtional info.
Seems like AOE damage can make it through als, with cleaving abilities etc damaging them on the inside. Magus/Choppa can pull order through to the inside, while engineers could pull destro outside, resulting in a botching fort take.

**Comment by KySaber** [comment]
Seems like AOE damage can make it through also.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16657
