### ISSUE TITLE
Acepting Ranked SC queue and DC will bring you 20 minutes quitter.

### ISSUE THREAD

**Issue by azpe** [WarEmu/WarBugs#16779]
**Expected behavior and actual behavior:**
Ranked SC pop, accept it then server closes your connection and then you have 20 minutes quitter.

**Steps to reproduce the problem:**
video is quite self explanatory

**Testing Screenshots/Videos/Evidences (always needed):**
https://streamable.com/m40exd

**Comment by Kaelang** [comment]
Will hopefully be fixed next patch - please re-open if issue persists. https://github.com/WarEmu/WarBugs/issues/15324
