### ISSUE TITLE
[RP] Invader stuff Jewel bugged

### ISSUE THREAD

**Issue by Kaya1106** [WarEmu/WarBugs#16770]
I try to unlock and afford/buy my invader jewel which cost 43 invader tokens, i have 43 tokens but it doesn't work when I click on it.
Neither error message or anything else.
(I have the rr levels ofc)

**Comment by Vayra** [comment]
Have you bought the full set first? You need the Invader Tome Unlock from equipping the armor first before you can buy the jewel.

**Comment by Kaya1106** [comment]
you mean buy all 6 pieces before the 7th jewel ?

**Comment by Kaya1106** [comment]
waste of token
bullshit
