### ISSUE TITLE
[NPC] Praag : Kislev Boyar

### ISSUE THREAD

**Issue by D4W0lf** [WarEmu/WarBugs#16774]
**Expected behavior and actual behavior:**
He is stuck in the wall.
Can't Aggro him.

**Steps to reproduce the problem:**
Walking at coord 22137,1063

**Testing Screenshots/Videos/Evidences (always needed):**

![Capture d’écran de 2020-05-11 16-01-41](https://user-images.githubusercontent.com/16599525/81570722-825e1900-9390-11ea-91e7-6f4a7a452a85.png)
![Capture d’écran de 2020-05-11 16-01-39](https://user-images.githubusercontent.com/16599525/81570725-838f4600-9390-11ea-8b68-4edf3dd4e2b0.png)

**Comment by Lheana** [comment]
Someone has pulled the NPC and he is now stuck there, but it's not where he spawns, so not much can be done.
