### ISSUE TITLE
Gates of Ekrund: Falling through Mid

### ISSUE THREAD

**Issue by Luuca** [WarEmu/WarBugs#1677]
Gates of Ekrund Scenario. After Getting to the Mid Flag, Just standing there, I fall through the floor into an area. I can run/ride out and around back up into the "normal" areas. 
Just a PITA when you are trying to flip the flag. This has happened twice. I will try to recreate it and get a video of it happening and post a link here.

**Comment by milosxe** [comment]
There are also a few spots around those boxes at the top floor where you can glitch and fall to that area. And probably attack the people out of nowhere if you're into that cheeky stuff.

**Comment by Luth-RoR** [comment]
Probably texture clipping issue/clientside.
