### ISSUE TITLE
[Public Quest] Chapter 3 : Macabre Fervor

### ISSUE THREAD

**Issue by D4W0lf** [WarEmu/WarBugs#16772]
I've made many times the entire quest and I can't validate the last objective.
[x] Flagellants
[x] Prophet of Doom
[ ] ???

**Comment by Kaelang** [comment]
Need more info.

**Comment by D4W0lf** [comment]
Which info ?
I've made the 3 objectives ans killed the last boss, in ToK I've always the ??? entry. Don't know what to say more.

**Comment by Kaelang** [comment]
Use the format provided.

**Comment by Vayra** [comment]
It seems like the War Story ToK unlock for completing stage 3 does not award properly

**Comment by D4W0lf** [comment]
**Expected behavior and actual behavior:**
All objectives in the ToK.
[x] Flagellants
[x] Prophet of Doom
[ ] ???


**Steps to reproduce the problem:**
Making the PQ.


**Testing Screenshots/Videos/Evidences (always needed):**

![Capture d’écran de 2020-05-11 14-27-52](https://user-images.githubusercontent.com/16599525/81561604-f5609300-9382-11ea-82c9-f8a6cf278937.png)

**Comment by Lheana** [comment]
It works fine for me. Try to be in the PQ area when you complete the stage.

**Comment by D4W0lf** [comment]
QP area is not well design... I have made a new test and kill the boss exactly where he pop... and didn't validate the objective.

**Comment by D4W0lf** [comment]
I did a new test and the boss is coming in way out of the PQ zone. We have to kite him to the right area for validation to take place.
Many npc come out of the PQ area in the others stages (1 and 2).

**Comment by Lheana** [comment]
We are aware of it, there is a ticket opened for that.

**Comment by D4W0lf** [comment]
ok np :D
