### ISSUE TITLE
"Encroaching Darkness" Quest bug

### ISSUE THREAD

**Issue by bseanwo** [WarEmu/WarBugs#16783]
In the quest "Encroaching darkness" in Nordland, when attempting to search the "Abandoned Sack" under the burning windmill, nothing happens when interacting with the sack - quest is not completable.

**Comment by Kaelang** [comment]
What part of the quest is this? There's a lot of reports of people completing this quest absolutely fine.

**Comment by Lheana** [comment]
Kill the horrors before interacting with the sack.
