### ISSUE TITLE
Fortress fight in butcher pass

### ISSUE THREAD

**Issue by CartoCoder** [WarEmu/WarBugs#16782]
I was fighting in BC with a WB and entered Butcher s Pass at the very beginning. I was there for the whole fight. thanks!
Something has gone wrong when attempting to add contribuation to you, please report on the bugtracker the circumstances of you entering the fort.
More DEBUG information for the bugtracker
Currentfort: Butchers Pass
Lehki killed Garazrinn in Butcher's Pass
Tanksur receives a Vanquisher's Medallion (
Annearche

**Comment by CartoCoder** [comment]
Something has gone wrong when attempting to add contribuation to you, please report on the bugtracker the circumstances of you entering the fort.
More DEBUG information for the bugtracker
Currentfort: Butchers Pass
Lehki killed Garazrinn in Butcher's Pass
Tanksur receives a Vanquisher's Medallion (

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16409
