### ISSUE TITLE
sound

### ISSUE THREAD

**Issue by Aps987** [WarEmu/WarBugs#16780]
About a week ago i had to re instal the launch program from the forum in order to enter the game. This proccess in itself took the best part of a day, it only took me a matter of minutes to load the game when i first started to play Return of Reckoning a few months back. After this new instal i am repeatedly disconnected when initially logging in. Once i am logged in my sound is overidden by a persistent ''tick tick tick'', much like a pendulm clock or a count down timer. The only way i have found to stop the repetitive noise is to turn my sound off, which isnt ideal. Any ideas on how to remdy this? Prior to this i had no issues with the game, everything was running fine.
Issues should be unique. Check if someone else reported
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Comment by Kaelang** [comment]
Please use the Technical Support section of the forums - the Bugtracker is for in-game bugs.
