### ISSUE TITLE
Stuck in keep door @ Charon's Keep

### ISSUE THREAD

**Issue by detrap** [WarEmu/WarBugs#16787]
![Screenshot 2020-05-13 06 50 46](https://user-images.githubusercontent.com/64330047/81744377-7ab08880-94e6-11ea-9306-8b5c732afcc8.png)

Pulled inside keep door then unable to move and unable to be targeted by healers for a rez. (Charon's Keep in Chaos Wastes).

This has happened in other keeps as well.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/12350
