### ISSUE TITLE
Black guard bug

### ISSUE THREAD

**Issue by Arkazaen** [WarEmu/WarBugs#16781]
I see that skill of black guard "pitilesstrike" don't work. I make a test with a friend who have a BG on my orders character it don't work, I retest with my BG on an other orders friend characters it don't work too, damage are same and thougness stay same and don't be down.

**Comment by Kaelang** [comment]
Need more information. Follow the format please. What is the skill meant to do? What does it do? How have you tested it? Do you have videos?

**Comment by AndrewSquared** [comment]
@Arkazaen hmu on Discord in general (@ShadowWAR) and I can help you test it out for screen shots. I have a BG with Pitiless Strike as well if you are only on Destro.

**Comment by AndrewSquared** [comment]
Tested with player, working as expected.

**Comment by Yami-Yagari** [comment]
Pitiless Strike does not have a text prompt on the applied hex on enemies.
