### ISSUE TITLE
Broom during quest By The Luck of... is unlootable

### ISSUE THREAD

**Issue by GusCubit** [WarEmu/WarBugs#16789]
Not the biggest bug in the world! During the 2nd part of By The Luck of... after talking to the Grey Wizard in the market, the Broom spawns. After killing it, it is not able to be looted. I believe its sprite is too low into the map to click.
![Broom](https://user-images.githubusercontent.com/65261113/81756155-dd882c80-94b2-11ea-9ba9-9bb3131647de.PNG)

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Set up a macro for Loot Nearest.
