### ISSUE TITLE
Slayer's armor

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#1679]
Some of the Slayer's items from t1 PVE have problems:
Chests missing model, for example: Dusty Leathers, Recruit's Leathers, Militia Leathers (from Empire PVE influence, not from PVP vendor! Same for the next items).
Militia Armbraces and Militia Chargers have swapped models - boots have gloves model and vice versa.

**Comment by DanaBloodkiss** [comment]
Fixed in next.

**Comment by Evildoor** [comment]
Well, while gloves and boots now have models going into proper places, these models look like 90% other slayer gloves and boots in T1, while before the fix they were unique...

**Comment by Evildoor** [comment]
![screenshot_014](https://cloud.githubusercontent.com/assets/11015074/11912676/90c456c2-a659-11e5-817a-1404dd3a1eff.jpg)

If someone wants to bother with this, here is how they looked like (they are still shown this way in character selection).
