### ISSUE TITLE
"Destruction controls the inevitable city"

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#16797]
as shown in the top right screen, sometimes after a siege, the red bar on top right of screen goes way off the meter.
![Dracula_068](https://user-images.githubusercontent.com/44329952/81818400-9a9a7900-94f3-11ea-9bcd-6003d1a6eadd.jpg)

**Comment by Kaelang** [comment]
Does a /reload work?

**Comment by Xicoz** [comment]
no, attempted that several times before posting, and this has happened more than a few times, but no other screen shots

**Comment by aaearon** [comment]
Reporting the same issue. This happened after zoning into Altdorf from Reikwald after the cities completed today, 14.05.2020 around 08:30 Europe. Like above, a /reload did NOT work.

![2020-05-14 08_46_03-Warhammer_ Age of Reckoning, Version 1 4 8, Copyright 2001-2012 Electronic Arts,](https://user-images.githubusercontent.com/812640/81902000-b53a2400-95bf-11ea-830a-bfda840dfffe.png)

**Comment by MaxHayman** [comment]
Seems to have fixed itself. Please reopen if not the case.
