### ISSUE TITLE
Killed by Blank Survey pop up

### ISSUE THREAD

**Issue by emailkook** [WarEmu/WarBugs#16791]
During a keep fight in Badmoon Keep, I dinged 37 while going upstairs. Caused the game to freeze then it had a Survey pop up (during siege mind you, don’t do that). I clicked on it and the window was blank. It ported me downstairs and killed me. When I released it or me in the warcamp instead of the keep. I have a video clip and you can see it had me floating when it came back from the freeze. 

**Expected behavior and actual behavior:**

Don’t give a survey in rvr zone, don’t be blank when I click on it and don’t kill me should be expected behavior.

Actual behavior posted above that paragraph.

**Steps to reproduce the problem:**

Not sure how to reproduce as I don’t know how they have the survey system coded.

**Testing Screenshots/Videos/Evidences (always needed):**

https://www.youtube.com/watch?v=ur3kXwSyC6E&feature=youtu.be

Clipped the whole incident other than the release.

**Comment by MaxHayman** [comment]
Is this still happening?

**Comment by emailkook** [comment]
No the next survey hasn’t done that. Haven’t seen another one in a while.

**Comment by Kaelang** [comment]
Closing as it's unlikely that the survey caused the death in that instance, probably some lag or DC - judging from your characters jittering movements.

Please re-open if something like this happens again.

**Comment by emailkook** [comment]
I leveled at the same time which as you know will pause the game then it
gave a blank survey. Mostly likely the leveling just happened to place me
floating on the stairs until it decided it doesn’t know what to do so it
just killed me instead.
