### ISSUE TITLE
White Lion shoulders dropping for Shaman.

### ISSUE THREAD

**Issue by Dixbe** [WarEmu/WarBugs#16799]
Thunder Mountain oRvR dropped shoulder piece for rolling while I was on my Shaman.

Expected behavior and actual behavior:
Destruction drops only.

Steps to reproduce the problem:
Item dropped after enemy kill while in oRvR 

Testing Screenshots/Videos/Evidences (always needed):
![Healaboi_000](https://user-images.githubusercontent.com/64327427/81833255-66e14280-9537-11ea-8cf3-1488aa8b0c7f.jpg)

**Comment by Kaelang** [comment]
- Fixed a bunch of items in loot bags that were wrongly assigned for another class; this issue concerned mainly Obliterator pieces

Likely impacted this - if not and the issue persists, please re-open.
