### ISSUE TITLE
Abilities lost most information since May 6th got worse with today's patch

### ISSUE THREAD

**Issue by Tuuvian** [WarEmu/WarBugs#16808]
https://returnofreckoning.com/forum/viewtopic.php?t=38140

Abilities lost most information since May 6th got worse with today's patch, and casting bar now reads <Unknown>.

**Expected behavior and actual behavior:**
Abilities should have full descriptions as they did before the May 6th patch but they do not.

**Steps to reproduce the problem:**
Just log in :).

**Testing Screenshots/Videos/Evidences (always needed):**
Would have loved to but PrintScreen although it does say taking a screenshot they cannot be found anywhere in my system. I could take phone pics I suppose if needed.

**Comment by Kaelang** [comment]
This is a problem with your files and installation - as descriptions haven't been changed. Working fine for 99.9% of players. Please use the forums for Game / Technical Support.
