### ISSUE TITLE
WL Loner tactic no longer equipable

### ISSUE THREAD

**Issue by adamversed** [WarEmu/WarBugs#16802]
**Expected behavior and actual behavior:**
Able to slot white lion loner tactic in one of the four available slots

**Steps to reproduce the problem:**
Load up any white lion character of sufficient level and try to assign Loner to one of the tactic slots.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/7112849/81840091-600afd80-9540-11ea-9345-6dd80c4b5980.png)

**Comment by Kaelang** [comment]
Judging by that screenshot, you already have it equipped.

Please upload a video

**Comment by adamversed** [comment]
I managed to get take a screenshot with it equipped by constantly clicking it and taking it at the right time, but its immediately removed.

**Comment by adamversed** [comment]
I dont have video recording facilities im afraid, but its pretty easy to reproduce.

**Comment by Kaelang** [comment]
Respec and try to equip once you've retrained.

**Comment by adamversed** [comment]
Same issue, i tried it with 0 points specced, 1 point specced and all points specced.

**Comment by adamversed** [comment]
if you have a tactic profile with it already equipped, switching to that profile will remove the tactic.

**Comment by Kaelang** [comment]
![image](https://user-images.githubusercontent.com/60117106/81840899-85e4d200-9541-11ea-84b5-a60f4969a4b3.png)
![image](https://user-images.githubusercontent.com/60117106/81840953-99903880-9541-11ea-9aed-0f97764dd32a.png)

Had no troubles with this tactic. Looks to be working fine. Potentially clear your cache / respec / try Game Support on the Forums. 

Closed.

**Comment by adamversed** [comment]
@Kaelang I still think theres an issue, I have cleared cache and disabled all add ons, with those disabled you can load with a profile that has loner, but if you then deselect it, you cant re add it.  I've installed a screen capture to show how to reproduce (I also respecced again)

video link - https://my.pcloud.com/publink/show?code=XZTN1dkZaSdq0VrRR9yF4mgnfpbpUzVJFFMy

Someone else has also reported this issue in the todays release thread, this prompted me to test it.

**Comment by Kaelang** [comment]
Please upload the video to a host, i.e. YouTube.

**Comment by adamversed** [comment]
https://youtu.be/Q6Go8Orn9Jk

**Comment by Kaelang** [comment]
Thank you.

**Comment by Kaelang** [comment]
Confirmed by #tester in Discord.

**Comment by Geettee64** [comment]
reloading ui does slot it but its doesnt fix it its broke even when you do the ui reload it doesnt enable the skill

**Comment by aloghides** [comment]
Also experiencing this bug

**Comment by SilverWF** [comment]
Another video https://youtu.be/iWVCx8WuoJA

**Comment by grunbag** [comment]
i don't have this issue on dev, it probably bad patched

**Comment by Anivia1** [comment]
Can confirm that this is an issue. I am having the same problem with my WL. It appears that the tactic is equipped. However, it is not showing on the Tactics bar and placing it on the bar also removes other Tactics Cannot confirm if the tactic still works, but this is quite a crucial bug as the Loner Tactic is crucial to Lion city dps spec.

**Comment by Qorth** [comment]
Confirming that this is an issue.  Cannot slot Loner.

**Comment by Geettee64** [comment]
why is this closed its still not working and it totally ruins the playstyle for both wb and city play

**Comment by Tazo83** [comment]
same i tried to equip that tactic and insta unequiped

**Comment by Kaelang** [comment]
This should now be fixed as of the 15/05 restart. Please let me know if issue persists.
