### ISSUE TITLE
patch 13 / 05/ 2020 fail update

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#16800]
fail patch with rorlauncher.exe; so i try see if rorupdayer will fix it instead; i recive an error and the launcher.exe got deleted

pasted error from rorupdater.exe

Error Downloading updater:
System.ComponentModel.Win32Exception (0x80004005): Accesso negato
   in System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   in System.Diagnostics.Process.Start()
   in RoRUpdater.MainWindow.gy3MwXQNt3w1CDbjGc(Object )
   in RoRUpdater.MainWindow.tYB114Sxk(Object  , DownloadDataCompletedEventArgs  )

still unable to patch or even start rorlauncher as it keep fail the update and get delet in process.; same happen with rorlauncher .exe taken from torrent download.

**Comment by Kaelang** [comment]
Use Technical Support on the Forums.

**Comment by Tesq** [comment]
> Use Technical Support on the Forums.

im suspended..... and there is also another error.....

Error Downloading updater:
System.UnauthorizedAccessException: Accesso al percorso 'C:\games\Warhammer Online age of reckoning\RoRLauncher.exe' negato.
   in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   in System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   in System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   in RoRUpdater.MainWindow.c7L3Zl71wSqG8TOaIO(Object , FileMode , FileAccess )
   in RoRUpdater.MainWindow.tYB114Sxk(Object  , DownloadDataCompletedEventArgs  )

**Comment by Kaelang** [comment]
Both of these issues can be fixed by following the Installation Guide. You don't need to post to search.

**Comment by Tesq** [comment]
never had these problems till the today patch but i'll look at instalaltion guide tough,

**Comment by Tesq** [comment]
> Both of these issues can be fixed by following the Installation Guide. You don't need to post to search.

nah cant see anything that point to these specific errors

**Comment by Kaelang** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=31241
