### ISSUE TITLE
Sorc - Shattered Shadows

### ISSUE THREAD

**Issue by Vauleen** [WarEmu/WarBugs#16809]
**Expected behavior and actual behavior:**
Expected:
Shattered Shadows should hit players surrounding the target even if it is blocked or disrupted. 

Actual
If the target blocks or disrupts Shattered Shadows then the surrounding players do not take or have a chance to take damage.  

Per the Tool-tip: You crush your foes under a blast of living shadow, dealing 109 spirit damage to your target and all other enemies within 20 feet of them.

**Steps to reproduce the problem:**

1. Target Player who is surrounded by other players (Tanks make this easy)
2. Use Shattered Shadows
3. If the target Player Blocks or Disrupts, the damage will not hit the players surrounding the target. 

**Testing Screenshots/Videos/Evidences (always needed):**

Bug:
![Shattered Shadows Bug](https://user-images.githubusercontent.com/3783156/81874261-88e4c000-954b-11ea-8ebc-83cd65af31d3.PNG)

Normal Damage:
![Shattered Shadows Expected](https://user-images.githubusercontent.com/3783156/81874327-a74abb80-954b-11ea-91dd-6fe54c25ec2d.PNG)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16546
