### ISSUE TITLE
Loner tactic for WL cant be slotted

### ISSUE THREAD

**Issue by Shiverman001** [WarEmu/WarBugs#16804]
Hello,today I played the game before the patch and everything was alright with my tactics,but patch have seem to made my tactics dissapear from their slots and the hotfix that followed after the patch made them back into their original slots but I was unable to slot my '' Loner '' tactic into any slot.I tried slotting it several times,tried deleting the cache,tried relogging but nothing seemed to work.
I have to mention i have respeced my character like 5 minutes before the hotfix update.
My character name:Shiverman
Thanks for the help in advance guys,cheers!

**Comment by adamversed** [comment]
@Kaelang ive added a video to the other ticket reporting this issue with further steps to reproduce https://github.com/WarEmu/WarBugs/issues/16802

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16802
