### ISSUE TITLE
SC - Missing Party Frames & Scoreboard Error.

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#16801]
some new SC bugs (screen shots say it all) 
![Dracula_070](https://user-images.githubusercontent.com/44329952/81839662-777cc300-950d-11ea-894a-74b4937b454f.jpg)
![Dracula_071](https://user-images.githubusercontent.com/44329952/81839687-7ea3d100-950d-11ea-8584-219b31815d3e.jpg)

**Comment by Kaelang** [comment]
Thanks - the team are aware of the problem with SC's. I'll keep this up for now considering a lot of people will likely be coming to the BT to post the same report, so probably best just to collect everything here.

**Comment by Xicoz** [comment]
yeah that's what I figured, also I forgot this gem (people don't show on map either)
![Dracula_072](https://user-images.githubusercontent.com/44329952/81840645-e9094100-950e-11ea-8175-98607632b3fb.jpg)

**Comment by Kaelang** [comment]
Should be fixed with restart - please re-open if issue persists.
