### ISSUE TITLE
Fort jail scroll not working

### ISSUE THREAD

**Issue by KySaber** [WarEmu/WarBugs#16818]
As shown in the video - after using the scroll to escape jail, the jail effects remain in place, unable to do anything.

https://www.youtube.com/watch?v=4wM2iL86j0k

Edit:
As Ruby as has mentioned, the jail effects for immunity are active outside the jail for damage, too.
https://www.youtube.com/watch?v=DQME6qHrmus Shown there.

**Comment by Rubyeclipse-war** [comment]
To add to this, as it just happened to my Kotbs (Dousetsu):

- After using the scroll, enemies are unable to target you.
- You are also unable to target enemies

I do not know if you are able to interact with things (like jail lever) as this was not tested. This occurred for me in the Stonewatch fort defense tonight.

**Comment by wargrimnir** [comment]
notified devs directly on this one. closing to hide the evidence.
