### ISSUE TITLE
Destro Fort Loot

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#16819]
upon us destro winning fort, we were surprised that order won first place loot (bombling a BW). isn't winning faction the one supposed to be getting loot?
![Dracula_082](https://user-images.githubusercontent.com/44329952/81893584-944be180-9573-11ea-9e7c-752a965797e7.jpg)

**Comment by Kaelang** [comment]
Based on roll and contribution. All players in the fort get rolls.
