### ISSUE TITLE
AAO not working and Diminishing rations debuff

### ISSUE THREAD

**Issue by daecadus** [WarEmu/WarBugs#16817]
**Expected behavior and actual behavior:**
Draqonwake appears bugged, Order is AAO - 40% but unable to use any supplies and has a constant Diminishing Rations debuff, though Order is outnumber 100 vs 160 Destro.  Reporting that Diminishing Rations is applying incorrectly,

**Steps to reproduce the problem:**

Be apart of warband and see if Diminishing Rations debuff applies if your side is outnumbered.
![Dimishing Rations](https://user-images.githubusercontent.com/64555996/81887304-6ad78980-9564-11ea-9676-bbbdd6fbad8e.png)

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Where is the image showing the population difference?

**Comment by Kaelang** [comment]
This looks to be related on the already active report of Diminishing Rations playing up - see https://github.com/WarEmu/WarBugs/issues/11508.

I'm going to merge the two together and make a note of this one.

Thank you for the report.
