### ISSUE TITLE
Forced fort entry without reservation w/ defender's door

### ISSUE THREAD

**Issue by Snifflebutts** [WarEmu/WarBugs#16816]
**Expected behavior and actual behavior:**
Expected: Prevents players without players without reservation
Actual: Able to force entry by repeatedly click on door at the right frame

**Steps to reproduce the problem:**
Try to enter fort through backdoor as defender, as you get teleported backward there's a tiny timeframe where you can click on the door and trick the game to port you in without reservation.

Something along the line as you get ported back, if you click on door, just as that happened, it queued 2 ports first backward and then to the other side of door. 

If you get killed and respawn instead of going to jail or spawn at the top, they game will port you outside to the cliff nearby as expected since you dont have reservation in the first place.

**Testing Screenshots/Videos/Evidences (always needed):**

https://youtu.be/AdJDcKXXR8k

**Comment by Kaelang** [comment]
Different tactic, same result - https://github.com/WarEmu/WarBugs/issues/16761

Merging.
