### ISSUE TITLE
Cheating Player is Invulnerable

### ISSUE THREAD

**Issue by blackabyss187** [WarEmu/WarBugs#16813]
The Bright Wizard Guelben ran out in the middle of a destruction war band during the Eatine fort defense on 13 May at 8:55 pm est bombing and aoeing us to death while being completely invulnerable. Many other people had this same issue with this individual prior to him running out; hence I was able to take a screenshot as he ran out.  With an entire war band focusing him, he could not take damage. Apparently the slayer Bhaic was also invulnerable, however, I was not able to get a screenshot of him.  

![Blackswordsman012](https://user-images.githubusercontent.com/64327008/81881229-9c992200-955d-11ea-964f-5482eb162473.jpg)

**Comment by Kaelang** [comment]
We're aware of this and devs have been made aware - closing so people don't attempt to recreate.
