### ISSUE TITLE
unkillable but silenced after using scroll in fort

### ISSUE THREAD

**Issue by xaraxdestr** [WarEmu/WarBugs#16826]
I was in prison in fort (Butchers Pass) as destro. I got a scroll into my bag where i could port out. After that i still wasn't able to cast anything nor mount. i was silenced as if still in prison. I was able to walk into the lord room full of order. They werent able to attack me not could i attack them.

**Comment by Kaelang** [comment]
Known issue - Closing as don't want people replicating. Devs are working on this.
