### ISSUE TITLE
Log into game, NPC/Players freeze, disappear, then D/C

### ISSUE THREAD

**Issue by awmc82** [WarEmu/WarBugs#16823]
**Expected behavior and actual behavior:**
- Expected Behavior: Able to load into game without disconnect.

- Actual behavior: Upon loading into the game other players and NPC will show on screen and moving just fine. After a few moments they will start to freeze and my character will not be able to cast any spells. Then the NPC/Players will disappear followed by my D/C. Have tried on multiple characters and same issue.

**Steps to reproduce the problem:**
N/A

- I have restarted client and computer but same issue. Have not done anything differently since last night (when I played last) and was working fine before I logged in this morning.

**Testing Screenshots/Videos/Evidences (always needed):**
[Bug 3.zip](https://github.com/WarEmu/WarBugs/files/4628195/Bug.3.zip)

This is a very brief video of what is happening. Have about 5 minutes of me logging in and it happening on another guy but file is to large to upload.

**Comment by Kaelang** [comment]
This isn't a bug - more of a technical issue. Please use the forums.
