### ISSUE TITLE
AoE Abilities going through walls

### ISSUE THREAD

**Issue by XmatXergon** [WarEmu/WarBugs#16827]
https://youtu.be/y6eLjeyApW0

As you can see in video, ppl getting pulled through walls. But i'm pretty sure its not only AoE pulls that works like this, basically any ability that doesn't require target is hitting currently through wall.

Pretty sure it started happening after last patch (13/05/2020)

I don't know if its Keeps/Forts issue or global thing.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16657
