### ISSUE TITLE
Lost item major purple bag altdorf siege phase 3

### ISSUE THREAD

**Issue by Rodakon** [WarEmu/WarBugs#16820]
good day, 

got this weird bug again but this time on my magus character Rodakon, my account name is Morzat

we just finished Altdorf siege phase 3 a few moments ago but instead of picking the bag a purple one i chased the order players into the city, the event ended without me picking the bag from the chest and this one never reached my ingame mail, had the exact same bug 1 month ago on my chosen character but that time it was on IC phase 3 and we had lost, the last time i submited a GM ticket and they fixed the issue and informed me to report bugs by these means

many thanks!

**Comment by Kaelang** [comment]
It will come after the next restart.
