### ISSUE TITLE
Item not appearing

### ISSUE THREAD

**Issue by SDarkSagaS** [WarEmu/WarBugs#16833]
The item "Sovereign Deathgirdle of the Dreadsword" (Chosen DPS set) is not appearing on character.

![Dola_096](https://user-images.githubusercontent.com/65378837/82003028-427c8780-9657-11ea-9b72-9ee70f18dcb8.jpg)

**Comment by Kaelang** [comment]
![image](https://user-images.githubusercontent.com/60117106/82051808-7b961580-96b2-11ea-9f2f-4304be229332.png)
![image](https://user-images.githubusercontent.com/60117106/82051824-82bd2380-96b2-11ea-9f36-af4a9e0ab976.png)
