### ISSUE TITLE
Scenario: Black Fire Basin

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#16838]
in this SC the flag doesn't seem to drop if held too long like in other SCs, or if you take to spawn. in this SC order grabbed the flag and just ran around with it for as long as possible near there spawn so that destro couldn't get the flag and catch up in points, I know with kegs for example, they will despawn/blow you up, tor anrok will give you "Cowardice" if taking the item to the spawn, and maw will kill you over time. (also when order finally decided to cap it, flag respawned near their cap)
![Dracula_097](https://user-images.githubusercontent.com/44329952/82055874-c306ac80-9686-11ea-842d-d88eca07419c.jpg)
![Dracula_099](https://user-images.githubusercontent.com/44329952/82055984-e6c9f280-9686-11ea-8ef6-ace4f48a5fa0.jpg)

**Comment by Kaelang** [comment]
![image](https://user-images.githubusercontent.com/60117106/82064327-8659a600-96c4-11ea-86d4-1bb2b475a50a.png)
![image](https://user-images.githubusercontent.com/60117106/82064345-8bb6f080-96c4-11ea-9716-27948950238a.png)

After 2 minutes of holding the flag, the user gets this debuff.

**Comment by Kaelang** [comment]
Also 
![image](https://user-images.githubusercontent.com/60117106/82064546-d2a4e600-96c4-11ea-9e51-a52c5223bf6c.png)

**Comment by Xicoz** [comment]
weird must have onbly been a onetime issue, hasn't replicated yet or anything
