### ISSUE TITLE
LOS check on NPCs

### ISSUE THREAD

**Issue by mursie** [WarEmu/WarBugs#1683]
NPC's in the keep do not respect LOS - aggro tables are having the NPC's pull from keep lord room onto balcony and hit player thru wall.

Issue:  I'm a lvl 16 white lion.  I use bypass defense and head up to 2nd level of keep.  Im on outer balcony and haven't even looked into keep lord room.  but am against the outer balcony wall.  I'm repeatedly killed by inner keep lord room NPC's that are aggroing to me because of proximity but shouldn't be aggroing do to LOS .

**Comment by gittoaster** [comment]
I've noticed that most all NPC don't respect LoS.  It's annoying, they obviously know about it.
