### ISSUE TITLE
Getting reward event Ekrund

### ISSUE THREAD

**Issue by JagwarLXXIll** [WarEmu/WarBugs#16846]
Hi, 

I can’t open the event ekrund to get my rewards at The NPC in Altdorf.

Thank you.

JagawarLXXIII

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by SilverWF** [comment]
Was about to create ticket
When there is too many events - you can't open the bottom one
![2020 05 09-16 15](https://user-images.githubusercontent.com/16439840/82113818-88be0d80-9761-11ea-9e77-b8294d91d9a0.jpg)

**Comment by Kaelang** [comment]
This should have been fixed in a recent patch.
