### ISSUE TITLE
Choppa - SoV berserker 4th bonus hided

### ISSUE THREAD

**Issue by Nekkbraka** [WarEmu/WarBugs#16842]
![bug sov](https://user-images.githubusercontent.com/47920948/82077112-3b846200-96b5-11ea-9ded-442acdd5825f.jpg)

and

Hided on Helmet too .. it gave a fake Weapon skill bonus .. 
![bug sov2](https://user-images.githubusercontent.com/47920948/82078949-6623ea00-96b8-11ea-847f-63ee1cbc62ff.jpg)

now a empty slot
![bug sov3](https://user-images.githubusercontent.com/47920948/82079061-91a6d480-96b8-11ea-9531-3c883a859832.jpg)

**Comment by Kaelang** [comment]
![image](https://user-images.githubusercontent.com/60117106/82081975-1a386b80-96df-11ea-9084-3470276676e4.png)
![image](https://user-images.githubusercontent.com/60117106/82082019-2e7c6880-96df-11ea-82a9-7809f4bcc572.png)

Both look fine to me. Sounds like a damaged patch / game file. Clear your cache and look to Game Support for help on the Forums.
