### ISSUE TITLE
PQ Loot Bags not level appropriate (Belts added 13/05)

### ISSUE THREAD

**Issue by Riggaknocka** [WarEmu/WarBugs#16841]
Playing in Chapter 7 of Elf pairing and solo'd Easy PQ, green loot bag dropped a lvl 30 rr 24 Blue belt. Other PQs in the pairing are dropping similar results of excedingly higher level gear (and possibly rarity above intended rewards?)

Picklesquick - SH
![Untitled](https://user-images.githubusercontent.com/64755846/82064219-74fba400-969a-11ea-9c55-1dd2257653e2.jpg)

**Comment by Lheana** [comment]
This item has been removed from the PQ loot bags with the patch of today.
