### ISSUE TITLE
[Forts] Loser side has the same priority roll

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#16845]
Destro just captured Shining Way and most destros didn't got proper reward, i.e. my magus Gimp got only 2300 renown (instead of 30k) and 4 invaders (instead of 6) for capturing fort and my final roll place was 286th - even under Order!
More than that, loser (Order) side got bag roll - in the final roll table at least 2 players with gold (!) bags was from Order: Shico and Gillerator

**Expected behavior and actual behavior:**
Exp: winning side gets more and better rewards
Act: it's not

**Steps to reproduce the problem:**
Just play forts

**Testing Screenshots/Videos/Evidences (always needed):**
Wasn't able to ss roll table - it disappeared while I checked names in Armory

**Comment by HalifKhan** [comment]
Was in the same Fort as SilverWF, Shining Way at about 2am EST. Similarly low renown and medallions for my Blackguard Aelifas,  and additionally it was my first time doing this Fort and didn't receive the title you'd receive from defeating the Shining Way keep lord. 

I also experienced this about two nights ago on my Black Orc at Stonewatch, where destruction won the fort siege but were treated for rewards as if we were the losing side, while order received the a lot of gold bag drops.

**Comment by Kaelang** [comment]
All players get a roll in the fort, regardless. Priority system or not, it's still possible for the other realm to get bags from a fort, win or loss.
