### ISSUE TITLE
[Warlord] Warlord ring for Warrior Priest. Armor penetration.

### ISSUE THREAD

**Issue by Waldhard** [WarEmu/WarBugs#16847]
**Expected behavior and actual behavior:**
Using the warlord ring should give you +3% armor penetration. This however does not seem to be the case.

On the paperdoll I get +3 intelligence instead of +3% armor penetration.
On .getstat command it will not show the intelligence, but the armor penetration will only show as part of the set down in the bottom, but the part next to weaponskill remains at the value that it had before using the ring. 

**Steps to reproduce the problem:**
Have attempted to equip and unequip multiple times with same result from .getstats and paperdoll. And yes, I have done a new .getstats upon changing the equipment. 

**Testing Screenshots/Videos/Evidences (always needed):**
Screenshots attached showing the paperdoll and the .getstats window with and without the ring.

![Waldhard_019](https://user-images.githubusercontent.com/65449561/82119171-a77dcd80-977c-11ea-8262-5b24635801b1.jpg)
![Waldhard_020](https://user-images.githubusercontent.com/65449561/82119172-acdb1800-977c-11ea-9fe9-b39d3f8b1437.jpg)
![Waldhard_021](https://user-images.githubusercontent.com/65449561/82119177-b19fcc00-977c-11ea-98fc-a424dff0f19f.jpg)
![Waldhard_022](https://user-images.githubusercontent.com/65449561/82119180-b5cbe980-977c-11ea-920e-eda17037dd7c.jpg)

* Edited for format.

**Comment by Nekkbraka** [comment]
Sov / BloodLord / Invader  all sets have relations with  Armor penetration  and all bugged... seems it hides for some reason and the iten copy and paste the fake bonus from other itens, just like you said.

**Comment by Kaelang** [comment]
Thanks for the detailed report - I've forwarded this over as it looks to be related to https://github.com/WarEmu/WarBugs/issues/14970.

I'm going to close this but have it mentioned in the older post and get some eyes on it.

Thanks again.

**Comment by Kaelang** [comment]
Your armor pen goes from 6-9 when you equip the ring, or am I missing something obvious here?

**Comment by Waldhard** [comment]
Indeed, the ring has +3% armor pen on it. But the paperdoll doesn't get any additional armor pen. Same goes for the set bonus that has the +6%.
