### ISSUE TITLE
Silence's (I think) visual effect endless on character

### ISSUE THREAD

**Issue by Balinorr** [WarEmu/WarBugs#16853]
Hello,

I' ve noticed that in rvr it happens a lot of time that after you get silenced, the visual effect of the silence on character do not drop after the ending and remain endlessy. Even after the death and even after deactivate the video effects it still remains. It disappears only when you change zone or log out.

Video: https://www.youtube.com/watch?v=QpwrR4OlnQU

![Balinor_028](https://user-images.githubusercontent.com/62892299/82132713-0aa24b00-97e3-11ea-91f4-89276cd228be.jpg)
![Balinor_029](https://user-images.githubusercontent.com/62892299/82132715-0bd37800-97e3-11ea-98cc-eea47c4ab4bd.jpg)
![Balinor_025](https://user-images.githubusercontent.com/62892299/82132717-0d04a500-97e3-11ea-97dd-a0a36b64e0a6.jpg)
![Balinor_026](https://user-images.githubusercontent.com/62892299/82132719-0e35d200-97e3-11ea-8c3e-acb9c0d8904f.jpg)
![Balinor_027](https://user-images.githubusercontent.com/62892299/82132721-0fff9580-97e3-11ea-943c-184a8edf2b8b.jpg)

**Comment by Kaelang** [comment]
I'd need to know the name of the Spell that causes this animation. I'll keep open for 2 weeks to see if you can let me know.

**Comment by Kaelang** [comment]
Closing as no additional information provided.
