### ISSUE TITLE
PQ mission credit ( npc kill and area range )

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#16859]
it doesn't give influence reward but quest credit is counting.
1. npc killing quest mobs.
if ally npc kills PQ mobs, there's no influence gain but PQ is updated.
ex) praag order ch19 Beasts of War
pull mobs to npc guard. 

2. pull mobs to outside of PQ area.
if you pull mobs far away until PQ tracker disappear,
killing doesn't reward influence but PQ is updated.
ex) CW order ch21 Madness

**Comment by Kaelang** [comment]
Both working as intended.

You don't get Influence if you wasn't participating in the kill / PQ.
Regardless of where the mob is killed, if it's a part of the PQ and is killed, the tracker will update.
