### ISSUE TITLE
commemorative plaque not interactive

### ISSUE THREAD

**Issue by coxie87** [WarEmu/WarBugs#1685]
In Ekrund, for the TOK entry where you must use the commemorative plaque at the bank, the item is not interactive.

Occurred 10/16/2015 - playing as Dunolindar

**Comment by Evildoor** [comment]
IIRC, no ToK mechanics are implemented for now besides notable NPCs and armor sets.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/5528
