### ISSUE TITLE
"Conquest of Kadrin Valley"

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#16856]
quest "Conquest of Kadrin Valley" is done, and showing as can be turned into him, but cant. (quest says turn into citadel in IC). Confusing, sat here for like 3 minutes wondering why I couldn't turn in the quest, he shouldn't display a turn in option / or made to where you can turn into him
![Dracula_102](https://user-images.githubusercontent.com/44329952/82134515-758d5b00-97be-11ea-85b4-6d7987e0b607.jpg)
![Dracula_103](https://user-images.githubusercontent.com/44329952/82134522-850ca400-97be-11ea-9d04-1cae2aebcf89.jpg)

**Comment by Kaelang** [comment]
Likely due to the location of the Keep Lord being triggered as in the enemy base (using live values). The lord shouldn't be in the Order keep.

Please try to hand-in when the rotation comes around and the lord is back in the correct keep.

**Comment by Xicoz** [comment]
will do, but regardless isn't this a bug, this should display regardless of what keep he is in

**Comment by Kaelang** [comment]
Which is why I haven't closed this report :)

**Comment by Xicoz** [comment]
> Which is why I haven't closed this report :)

ah ok, thought that's what the "2 week ultimatum" was for

**Comment by Kaelang** [comment]
This should have been addressed as of the 20/05/20 patch.
