### ISSUE TITLE
RVR .guildinvolve

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#16855]
not a big issue, but it says my guild vault has a ton more gold than we really do after involving my guild in a zone, as shown in chat of SS
![Dracula_100](https://user-images.githubusercontent.com/44329952/82132998-e414ed80-97ab-11ea-83e3-1877b357499a.jpg)

**Comment by Kaelang** [comment]
The system uses coins as opposed to gold. Not necessarily a bug, but if you'd like this to be changed into Gold/Silver/Copper etc, please use Suggestions and Feedback.
