### ISSUE TITLE
invaders reward edge zone

### ISSUE THREAD

**Issue by Tzakka** [WarEmu/WarBugs#16850]
Hello, my character name is Tzakka i didnt got any invader reward for zone lock Caledor 21.00 central europe time 16th may 2020 im sure i was on top 75% contribution. can u check if any bug occurred? i have spent so much time in the zone and is very annoying. this is not the first time this happen to me but this time im so sure i cant be on 25% lowest contribution. thanks

ps: i didnt even got the roll for the bag, which is very weird

**Comment by Kaelang** [comment]
Do you have the Vanq ToK unlock?

**Comment by Tzakka** [comment]
yes

**Comment by Kaelang** [comment]
Screenshots please.

**Comment by Tzakka** [comment]
https://ibb.co/74DQ5RN

**Comment by Kaelang** [comment]
Spoke to a few people in T4 and it seems Invaders did go out to people who defended, met the criteria and were in the top 75% of contribution. So the system in itself is working as intended. If you didn't get a bag roll, it suggests you didn't contribute enough, and/or you swapped characters and played a different toon in the same zone, resetting your contribution.

Regardless, system distributed the Invader tokens and looks to be working as intended. Make sure you double check criteria and contribute effectively. If it happens again - re-open with replication steps please.

**Comment by Tzakka** [comment]
normally i get the invaders reward, sometime occurred i didnt got it but i mean sometime i can be in lowest 25% this time im pretty sure is not the case :/

**Comment by Kaelang** [comment]
Messaged as I did - see above. Invaders went out.

**Comment by Tzakka** [comment]
i havent swapped characters either, i dont know man it very weird i have been in the zone for like 2 hours u can check the logs

**Comment by Tzakka** [comment]
there is no way u can check contribution? im not in a hurry like im not asking u guys to do it now but eventually in future, idk

**Comment by Kaelang** [comment]
It's possible to check contribution levels, but on an individual basis it's not something the team do. If the system looks to be working on a mass - scale and there's limited / no reports of it. It's typically user error as opposed to system based.

If there was a systematic failure, and a tonne of people started saying 'we got absolutely nothing' then it would be investigated.

**Comment by Tzakka** [comment]
ok, i get it, thanks im sorry just very frustrated for the time i spent but i appreciate your patience!
