### ISSUE TITLE
WTF is this shit?

### ISSUE THREAD

**Issue by TheOGScav** [WarEmu/WarBugs#16857]
Oil blocking ALL RDPS SH stuff?

https://youtu.be/T0uHrBmYrgc

**Comment by Rubyeclipse-war** [comment]
The oil is a higher level than you. (You are level 34, it is 40.) Pretty sure this makes it much more likely to block your attacks, like any normal NPC far above you. Once you're level 40 it should happen much less, and in the meantime your dots may still work.

Additionally, for future bugs that you are positive are bugs, please be sure to avoid ambiguous titles so the bugtracker manager and staff can understand the issue more quickly. (i.e. "Oil blocks all attacks" as title.)
