### ISSUE TITLE
Broken dunes PQ

### ISSUE THREAD

**Issue by Gervhart** [WarEmu/WarBugs#16860]
Today, 17.05.2020 at around 13.00 CET i could not finish the second stage of PQ Broken Dunes because objective (Font of Shyish) would not count towards the goal whether i use it or not.

**Comment by Kaelang** [comment]
Works fine. Right click to activate, then destroy it.

**Comment by Gervhart** [comment]
Ah okay.

вс, 17 мая 2020 г. в 14:51, Kaelang <notifications@github.com>:
