### ISSUE TITLE
Cannot DPS targets through open palace door in Altdorf

### ISSUE THREAD

**Issue by Neutrinoo** [WarEmu/WarBugs#16867]
In City fight use a range dps.  Go to a stage 1 Order palace door or Stage III lord room door.  Note that even though you can see a target through the door with line of sight you cannot dps the target.  You cannot use abilities like rift to pull targets through the doorway.   You cannot place a magus mine pet through the doorway.

**Comment by Vayra** [comment]
Yep, this has been reported a while back: #15750

**Comment by Kaelang** [comment]
Merging with older report https://github.com/WarEmu/WarBugs/issues/15750.

W
