### ISSUE TITLE
Fort Res

### ISSUE THREAD

**Issue by KySaber** [WarEmu/WarBugs#16862]
Sorry if it's already reported, as shown, entered and used my res, then got booted out just after and lost my fort entry.
![Fort Res](https://user-images.githubusercontent.com/26847385/82147250-d76ac500-9891-11ea-80c2-84ea1cea99f5.png)

**Comment by Kaelang** [comment]
The 27/05 patch has addressed some contribution issues / porting issues with forts. Please re-open if this is issue persists.
