### ISSUE TITLE
Maw fort issues

### ISSUE THREAD

**Issue by crazyturkme** [WarEmu/WarBugs#16870]
Just now WE (destro) won the maw fort however everytime when i die in the fort i respawn in maw ic gate and went back to fort que. additionaly after ending fort i got no bag roll no meds no rr. (had enough contr. lots kills capped flags) 

i dont have any screenshots or vids but it seems it a common issue. people will confirm me probably.

**Comment by ismetto84** [comment]
yes i can confirm it, i had the same issue. no rr no meds no bag roll
some one help?
Choppa / Magnog

**Comment by crazyturkme** [comment]
even tho i had fort reservation btw.

**Comment by Kaelang** [comment]
If your re-spawn isn't the same as others that are in the fortress, it means you have found a way into the Fort without having a reservation. If you don't have a reservation, you won't receive any RR/Meds/Loot.

Please re-open if you're able to provide evidence supporting you did have a reservation and there is something fundamentally broken here.
