### ISSUE TITLE
Not received my SC ranked token

### ISSUE THREAD

**Issue by Layinolias** [WarEmu/WarBugs#16871]
Hello,

I log on this morning, looking after my mail boxe for my SC ranked token, end i was surprise to don't see any on it.

i'v played many ranked this like week like 40, i relog many time but nothing more in my mail boxe.
some one have the same isue ?

Thx you for your work's

**Comment by Kaelang** [comment]
I received my tokens, amongst other people who have confirmed there's came through too. I guess you didn't meet the weekly requirements to receive the tokens.

**Comment by Layinolias** [comment]
What you mean about the weekly requirements ? i played ranked since day one, i play 158 sc (6v6 laderobard tell me that). the first 2 week i received my token like all :). i played at least 60 sc every week how can don't have the weekly requirements ? :)

**Comment by Kaelang** [comment]
What's your character name?

**Comment by Layinolias** [comment]
"Layinolias" in game :) "Lay" on forum

**Comment by Layinolias** [comment]
i can send screan of my bag for make the math about the number of token :) i have 2189 token 158 played 62 win 96 loose

**Comment by dalen** [comment]
This is likely due to the general unreliability of the mails, especially when switching zones. I made a fix now that should help with that. But hopefully this mail will arrive after a server restart.

**Comment by Layinolias** [comment]
Ok i wait after the next server restart for come back and telling you some news :) Thx you for your work's one more time :)

**Comment by Layinolias** [comment]
Well done !! i got it :) Nice Thx you for your work's !!!
