### ISSUE TITLE
Items Frozen in Crafting Bag

### ISSUE THREAD

**Issue by Whentballistic** [WarEmu/WarBugs#16876]
**I am unable to move Talisman Fragments in the second portion of my Bag.
![image](https://user-images.githubusercontent.com/65260294/82282837-b9b96080-9962-11ea-8853-47b73de7883d.png)**

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Can you move them after relogging?

**Comment by Whentballistic** [comment]
Hey Kaelang,

I attempted relogging, then reset the UI in the chat box. The UI reset
worked.
I totally forgot about the UI reset from the old WHoL.

Thanks for the quick response, I'll try to think things through a bit
longer before submitting a bug report.
I also want to tell y'all that I am really enjoying the new version.  Great
Job !!!!

**Comment by Kaelang** [comment]
No worries! /reload is a life saver sometimes.

Going to close this up, glad you're enjoying RoR.
