### ISSUE TITLE
Fort Rewards

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#16875]
winning a fort atm gives almost no RR and only 4 invader meds when should be 6 (I believe we are getting the rewards for a loss), see chat window for rewards
![Frankenstien_019](https://user-images.githubusercontent.com/44329952/82278705-70601580-9950-11ea-9668-78280e394f8f.jpg)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16384
