### ISSUE TITLE
1/6 Players recieved credit for Beastlord Khorgash

### ISSUE THREAD

**Issue by SkitZa** [WarEmu/WarBugs#16872]
2 players died one as Khorgash died and only 1 person in the party recieved credit out of 6 people.

Unsure of what caused it but have a video with the full fight & ends with showing 0/1 credit.

https://www.youtube.com/watch?v=nSPbfkW4p9E&feature=youtu.be (Sorry for the background music)

**Comment by SkitZa** [comment]
Squig was the only one who recieved credit he got knocked away as it died and he ran further away it dies at 0:45 in the video and the squig is kind of far away.

**Comment by Kaelang** [comment]
Likely a result of this report here: https://github.com/WarEmu/WarBugs/issues/12470

Merging so hopefully can work out causation at some point.
