### ISSUE TITLE
public quest objectives and influence bar not showing

### ISSUE THREAD

**Issue by coxie87** [WarEmu/WarBugs#1687]
My ui shows what chapter and region i am in, however it does not show the influence bar or the public quest objective.

Occurred 23:30 on 10/17/2015 playing as Gerik

**Comment by coxie87** [comment]
This is intermittent upon entering and leaving the zone.

**Comment by Evildoor** [comment]
Most public quests are not implemented properly, and so are things connected to them (like influence bar and objectives).

**Comment by Evildoor** [comment]
Changelog 25.02.2016

[Public Quests]

- The public quest window is working now. 
- The public quest counter is working now.
