### ISSUE TITLE
Gunbad Left first PQ missing a boss (Squig Crazy!)

### ISSUE THREAD

**Issue by Blaqwar** [WarEmu/WarBugs#16873]
As per title. The first PQ in  our Gunbad left run was missing one of the bosses (Gribblik da Stinka) and couldn't be completed.

I don't know if this is a direct result of the bug but none of the other PQ bosses were spawned. The instance for the final boss was open however and he was the only boss killed in the instance (as the lockout shows).

Strangely enough the Chaos Troll boss (Bilebane the Rager) was spawned but didn't give a lockout (not sure he is supposed to or not, just noting it in case it's valuable information).

![Camael_031](https://user-images.githubusercontent.com/5108812/82266707-b629d780-996a-11ea-8a33-baebc9b305c5.jpg)

**Comment by Kaelang** [comment]
Sounds like the player who lead the run was locked out of the instance.

**Comment by Blaqwar** [comment]
I had his assurance he wasn't locked out, asked twice. He claimed the same thing happened on his last run some days before.

But if you are confident that the issue was that the leader was locked out you may lock this. He could have been outright lying naturally.
