### ISSUE TITLE
Gunbad Quest "No Glove No Love" cannot be completed

### ISSUE THREAD

**Issue by Eddie84Style** [WarEmu/WarBugs#16874]
I finished the quest "No Glove No Love" by running the left wing 3 times on Destro side. The quest is checked as completed on both the Tome and on NPC but he wouldn't give me the reward. All i get is a window with "go back" and "goodbye" options

![1](https://user-images.githubusercontent.com/65578235/82275744-cbf7c680-9983-11ea-8436-2160c7d6baab.jpg)

![2](https://user-images.githubusercontent.com/65578235/82275750-d1551100-9983-11ea-8aa9-1f71be11dae4.jpg)

**Comment by Eddie84Style** [comment]
I just realized the quest is to be returned to another NPC, I was able to return it no problem, works fine - sorry ^^'

**Comment by Kaelang** [comment]
This should be fixed as of the 20/05 patch. Please re-open if issue persists.
