### ISSUE TITLE
BW & Slayer Cheating or Bug? FORT Siege

### ISSUE THREAD

**Issue by ismetto84** [WarEmu/WarBugs#16877]
BW & Slayer Cheating or Bug? 
FORT Siege
Destro can't attack BW and Slayer..
BW - Guelben / Slayer Bhaic

[<!--](https://www.youtube.com/watch?v=t607TvvXWoE)

**Comment by Kaelang** [comment]
Did this happen today, or is this an early video clip? A hotfix was pushed that should've stopped this happening.

**Comment by ismetto84** [comment]
14.05.2020
03:30 / 04:50 EU Time zone

**Comment by Kaelang** [comment]
This was hotfixed.
