### ISSUE TITLE
War Report: Teleport locations

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#16880]
War Report should send you to the warcamp, not some pve camp that's miles away. 
![Frankenstien_021](https://user-images.githubusercontent.com/44329952/82386762-d608dc00-99fa-11ea-9ee1-e16333e51ca0.jpg)

**Comment by Kaelang** [comment]
Duplicate https://github.com/WarEmu/WarBugs/issues/14916.
