### ISSUE TITLE
Quitter debuff (scenarios) after being disconnected

### ISSUE THREAD

**Issue by detrap** [WarEmu/WarBugs#16884]
Quitter debuff (scenarios) after being disconnected for two seperate reasons.

Quitter debuff after being disconnected once trying to join a scenario

Quitter debuff from the 'winds of change' notification once trying to join a scenario and ported back to the rally master in Altdorf.

**Comment by dalen** [comment]
Added another fix to avoid the winds of change stuff. Hopefully it fixes this. Open a new ticket if you still see it after this weeks patch.

**Comment by Kaelang** [comment]
This should be fixed as of the 20/05 patch. Please re-open if issue persists.
