### ISSUE TITLE
Sovereign Armor set 6 piece bonus not working properly

### ISSUE THREAD

**Issue by Jagosaa** [WarEmu/WarBugs#16888]
Sovereign Armor 6 piece bonus should add 2 mastery points to the appropriate mastery tree.
It does not.

![sov6piece](https://user-images.githubusercontent.com/65671464/82467054-dcb25480-9ac9-11ea-8a0c-6ab9d42224b5.png)

**Comment by Tripmeister** [comment]
Yeah same here by my WP

**Comment by Jagosaa** [comment]
Im suspecting it is not only sov armor, I believe this happens with every armor set that should add mastery points, but I've yet to confirm that.

**Comment by Syracus84** [comment]
Try taking off all your armor pieces without putting any points in skill tree. Log out, log back in, put armor pieces back on. The points should then appear in the Tree. Tried it on my WP and it worked.

**Comment by ChrisRBe** [comment]
![image](https://user-images.githubusercontent.com/31167512/82473321-ad9be300-9ac9-11ea-8376-e7067ddf3eab.png)

seing the same on SM Sov

**Comment by Kaelang** [comment]
Most likely related tp https://github.com/WarEmu/WarBugs/issues/16886. Closing for now.
