### ISSUE TITLE
Lost Keeper's set and tokens

### ISSUE THREAD

**Issue by raig100** [WarEmu/WarBugs#16889]
Hi! After the latest server crash i lost  3 king's tokens from altdorf sewers which i spent on keeper's set, which i dont see now as well, the quests have been completed. Can i have items\tokens\quests back? thanks in advance.

**Comment by Kaelang** [comment]
Sorry, we don't return any items lost due to restarts / crashes.

**Comment by raig100** [comment]
Can u start me back the quests i had?

**Comment by raig100** [comment]
coz i seem to have lost them as well

**Comment by Kaelang** [comment]
There's no game support for that at this time.
