### ISSUE TITLE
Target dummies having a couple bugs. 

### ISSUE THREAD

**Issue by nnnnNATHANnnnn** [WarEmu/WarBugs#16887]
For whatever reason target dummies no longer show up on unit frames as hostile target. Also, when I try to press escape to untarget it, it wont work, all I can do is run away and find a new hostile to target. I can still see the debuffs pop up above where my hostile target unit frame should be. 

https://www.youtube.com/watch?v=2PZXQq8Fh1U

**Comment by Kaelang** [comment]
Seems related to this https://github.com/WarEmu/WarBugs/issues/5060. Likely the dummy is in as a World Object which has bugs similar to this one.
