### ISSUE TITLE
[Zelot] Ritual of Lunacy now deals damage instead of heal

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#16885]
Ritual of Lunacy now deals damage instead of heal
Basically, instead of healing your group it deals the same amount of damage to you and your party
But chat message says it's healing for negative amount - basically, do damage
Happened after 20th may patch

**Expected behavior and actual behavior:**
Exp: heal from healing ritual
Act: it deals damage

**Steps to reproduce the problem:**
Place ritual and look

**Testing Screenshots/Videos/Evidences (always needed):**
![2020 05 20-17 31](https://user-images.githubusercontent.com/16439840/82459222-56454500-9ac0-11ea-9e2c-abdcbc0e9c51.jpg)
As you can see, my own ritual deals damage to me and my party member

**Comment by Kaelang** [comment]
Thanks - aware of this one. But will keep this open so people who are looking to report this, or the RP Equivalent (which is also sharing the problem) are made aware.

**Comment by SilverWF** [comment]
It also has mechanic of Dissolving Mist / Napalm grenade - increasing damage with time
![2020 05 20-17 40](https://user-images.githubusercontent.com/16439840/82459883-20ed2700-9ac1-11ea-9c6b-1c977194c9d6.jpg)

**Comment by Kaelang** [comment]
Sneaky Zealots & RP's and their voodo ways.

**Comment by Kaelang** [comment]
This should* be fixed as of the hotfix.
