### ISSUE TITLE
Reflexes is missing from my Renown Trainer skill list.

### ISSUE THREAD

**Issue by velenne** [WarEmu/WarBugs#16892]
**Expected behavior and actual behavior:**  I should see Reflexes (the +Parry ability) in the skill list when speaking to a Renown Trainer.  I seem to still retain my previously trained bonus to Parry in my character sheet's Defense page (Parry: 28.8(10.8 + 18)).  I am Takindra in-game and Faceplant#6440 on discord, if you need to see it online.

**Steps to reproduce the problem:** Be Witch Hunter.  Talk to Renown Trainer.  Check list.

**Testing Screenshots/Videos/Evidences (always needed):**

![](https://cdn.discordapp.com/attachments/329318147310223370/712711687123238953/unknown.png)

![](https://cdn.discordapp.com/attachments/329318147310223370/712711754765041764/unknown.png)

**Comment by Kaelang** [comment]
![image](https://user-images.githubusercontent.com/60117106/82478130-5ea17e00-9ac8-11ea-8c5b-fb35a42a9ad3.png)

Untick Hide unavailable Renown Abilities and look again please.

**Comment by velenne** [comment]
I did. That's what the top screenshot is from.

**Comment by Kaelang** [comment]
Do you have it maxed out?

**Comment by velenne** [comment]
No I believe I only had 3 levels of it.

**Comment by Kaelang** [comment]
Unsure - it might be worth checking Game Support on the Forums for additional advice. As I can see it on my Witch Hunter, on Live, I don't have reason to believe it's bugged from a server perspective so I'm going to close this up for the time being. If you provide additional evidence to support such issue I'll re-open.

Thanks.
