### ISSUE TITLE
[Sovereign Set Bonuses] 6 piece sovereign doesn't give bonus mastery points?!

### ISSUE THREAD

**Issue by Sciberr** [WarEmu/WarBugs#16898]
An introduction:

When equipping 6p sov I should automatically get 2 points into grace path but I don't.

Details:

I already tried re-logging, respeccing, taking off the gear and putting it back on and nothing works.

Evidence:

https://youtu.be/2mGEKC7YwwA

Additional Information:

N/A

How to reproduce the bug:

Equip 6p Sov

**Comment by Sciberr** [comment]
UPDATE : Things are really broken now lmao...

Details:

When I took off some of my sov it automatically maxed out my grace path? Then with the rest of my points im able to do so much more than whats supposed to be allowed.

Evidence:

https://youtu.be/FfWCtEqbllI

How to reproduce the bug:

Remove enough sov so you no longer get the 2 point bonus.

**Comment by velenne** [comment]
https://github.com/WarEmu/WarBugs/issues/16886

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16886
