### ISSUE TITLE
[Character] Stuck in sky and can't interact with char

### ISSUE THREAD

**Issue by Reggaewaldo** [WarEmu/WarBugs#1689]
Character: Chook (http://www.returnofreckoning.com/armory.php?character_id=169119&character_name=Chook)

Issue: Stuck in the sky. No texture on char. Can't see char online from other characters, Can recive whispers but not whisper back.

Tried to teleport character using GM commands but does not find character.

**Comment by xyeppp** [comment]
Zone 0, have to /stuck x2

Whenever you are put in zone 0 the server doesn't recognize you which is why you and I will be unable to help him with GM commands. He has to /stuck himself out of it twice.

**Comment by Reggaewaldo** [comment]
I will dubble-check but I'm pretty sure that /stuck was used 2 times in succession.

**Comment by Reggaewaldo** [comment]
Yes, Confirmed the player also tried with /stuck during loading screen aswell.

**Comment by Evildoor** [comment]
In some other ticket the player tried stuck, it failed, i told him to use it (i was unaware that he already tried), he tried again and it helped.

**Comment by xyeppp** [comment]
I'm willing to bet he is not using /stuck correctly as a lot of people are not. 
Cannot help him in any way if he doesn't /stuck (hit enter) /stuck (hit enter) again.

**Comment by chook06** [comment]
ok My character is not blocked. Thx a lot !!!

**Comment by Reggaewaldo** [comment]
Perfect, then i will close this one.
