### ISSUE TITLE
[Marauder] Defensive Sovereign (Hulker) 6 peice bonus (+2 monstro) not working? 

### ISSUE THREAD

**Issue by Bobolith** [WarEmu/WarBugs#16908]
**Expected behavior and actual behavior:**
The 6-piece bonus for the defensive Sovereign should give +2 to monstro tree. When i equip it i dont get the +2 to monstro as you can see from the attached screenshot.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Bobolith_007](https://user-images.githubusercontent.com/65730942/82591655-f8882a00-9b9f-11ea-8b6f-d2e3ff780819.jpg)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16886
