### ISSUE TITLE
[Ironbreaker] Ruin Gear Setbonus + 1 in Stone Tree is broken after Patch 20.05.2020

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#16902]
The Full Ruin Setup should give you 1 default Mastery Point in The Middle, Path of Stone Tree.
After the Patch on 20.05.2020 or the patch before that there isn't anymore this default point. 
I realized it when I was missing a key Ability.

**Steps to reproduce the problem:**
Get an Ironbreaker with a full Ruin Armor Set.

**Testing Screenshots/Videos/Evidences (always needed):**

![Thorin_064](https://user-images.githubusercontent.com/14627932/82551662-e5a23500-9b60-11ea-88a6-88c652074f5e.jpg)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16886
