### ISSUE TITLE
Reikguard Vanquisher's using CH22 abilities as normal NPC's. 

### ISSUE THREAD

**Issue by gorbane** [WarEmu/WarBugs#16907]
wargrim told me to report it here, the regular mobs at reiksguard training grounds are using chapter 22 mob abilities, almost instantly killing people, regular mobs not champs

![image](https://user-images.githubusercontent.com/65727007/82581530-b1c61000-9b5e-11ea-9e5e-c99e7e18df40.png)

**Comment by Lheana** [comment]
The Reiksguard Vanquishers, Protectors and Justicars **belong** to the chapter 22 hard PQ "All the King's Men", so no issue here.
