### ISSUE TITLE
BO skill bug

### ISSUE THREAD

**Issue by jinsu0716** [WarEmu/WarBugs#16903]
![unknown](https://user-images.githubusercontent.com/64660606/82564898-84a44c80-9bb4-11ea-8169-c5814649581f.png)

**Expected behavior and actual behavior:**
the use of many techniques

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![unknown](https://user-images.githubusercontent.com/64660606/82565020-b0bfcd80-9bb4-11ea-9098-eeb9093d784e.png)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16886
