### ISSUE TITLE
Bloodlord Weapon bug*2

### ISSUE THREAD

**Issue by noobwarrior** [WarEmu/WarBugs#16904]
at the moment i have armor of 2148 as you can see and when I put on the weapon I have 1933 armor
according to the rext on the weapon, i should cause 5% more damage and lose 5% toughness and armor as you can see it's a little bit more precise 10,01%
![Relife_456](https://user-images.githubusercontent.com/53536809/82569289-51e06100-9b80-11ea-88bd-bda44286988f.jpg)
![Relife_457](https://user-images.githubusercontent.com/53536809/82569298-560c7e80-9b80-11ea-87eb-1a73e3ba0948.jpg)

**Comment by grunbag** [comment]
Where do you see it reduce armor and toughness by 5% ?

**Comment by Kaelang** [comment]
This can be related to https://github.com/WarEmu/WarBugs/issues/16796.

**Comment by grunbag** [comment]
It’s intended the tooltip doesn’t mention how much it reduce armor and toughness , and 10% is intended value
