### ISSUE TITLE
Gained more xp than the system allows from fort, lost all the xp

### ISSUE THREAD

**Issue by Eleison** [WarEmu/WarBugs#16915]
I was defending a fort where i was in jail, decided to leave some seconds before it ended. I'm not sure what originally stopped me from getting xp, but I was in a loading screen when it ended so maybe that's why. Anyways I figured I would get the xp by relogging since that's what it does when you're not there to receive it, and sure enough I got all my RR then, however...
![WAR-64_FiPWBdxWUN](https://user-images.githubusercontent.com/896251/82633806-1f5b5600-9bca-11ea-9adc-73d63a0bd9cc.png)
It seems that I somehow had so much xp to receive that the game just cancelled all of it?
That message popped on relog, along with the RR xp i received

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16541
