### ISSUE TITLE
Fortress dont take me correct Renown, dont loot rolls bag and not invader medallion

### ISSUE THREAD

**Issue by mirage1cs** [WarEmu/WarBugs#16919]
Shining Way Fortress dont take me correct Renown (others 30k), dont loot rolls bag and not invader medallion

![error fortaleza](https://user-images.githubusercontent.com/65768372/82666399-2a4bd000-9c36-11ea-8d7b-ca3fbab438d2.jpg)

When the fortress started, the error that warned me of the problem and put the ticket appeared in the chat, but I did not capture it in time and I cannot rescue it.

(Sorry for my poor English, in case data is missing or if it is a repeated topic)

Thanks

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16409
