### ISSUE TITLE
KOTBS 6pc Sov bonus bugged

### ISSUE THREAD

**Issue by Drewsephy** [WarEmu/WarBugs#16918]
6pc bonus (+2 to vigilance tree) not properly applying

Here is a pic where I have specced 1 point into vigilance (which shouldn't be possible with bonus).  I had 0 points showing into the tree prior with full sov set equipped.

![image](https://user-images.githubusercontent.com/65766787/82662504-95c07e00-9bf3-11ea-8a62-b8c2157474a4.png)

Thank you

**Comment by Drewsephy** [comment]
Also please notice I have smashing counter available on my hotbar despite not having specced into it.  This bug may be more of a complex interaction than just the points in Vigilance tree

**Comment by Drewsephy** [comment]
Here I am just having used smashing counter not specced into.  

![image](https://user-images.githubusercontent.com/65766787/82663025-8857c380-9bf4-11ea-817b-42c742679fe0.png)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16886
