### ISSUE TITLE
Unable to hand in quest - Orange icon remains persistent. 

### ISSUE THREAD

**Issue by Kaelang** [WarEmu/WarBugs#16910]
I'm unable to hand in any Scenario quests in Tier 1. This was working fine up until recently - not too sure what's caused the problem, but it's present.

The orange icon above quests remains consistent, even after relogging. No rewards provided through initial attempt at turning in, and quests remain in my log.

At first, I thought this was just the one quest listed in my log - however since this was recorded, additional quests are unable to be turned in. 

Unable to provide replication steps at this time, as I'm unable to replicate it myself. 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/60117106/82596076-a09cf380-9b9e-11ea-8af4-5d61e622617a.gif)

Edit: After winning the Gates of Ekrund a second time, with this 'completed' quest in my log, I was able to hand this in, and subsequent quests.

**Comment by Xicoz** [comment]
this might be related (quest npc overhead is showing as not done, when it is)
![Nooblit_064](https://user-images.githubusercontent.com/44329952/82715126-5d528b80-9c57-11ea-96ee-91df9792733a.jpg)

**Comment by Xicoz** [comment]
quest giver isn't giving the overhead icon
![Nooblit_065](https://user-images.githubusercontent.com/44329952/82717385-69dbe180-9c61-11ea-9d87-2669636f59fe.jpg)

**Comment by Kaelang** [comment]
This should have been fixed as of 27/05/20. Please re-open if issue persists.
