### ISSUE TITLE
WP Purify + Cleansing Power tactic - not working when targeting self

### ISSUE THREAD

**Issue by Fuamatu** [WarEmu/WarBugs#16913]
**Expected behavior and actual behavior:**
Expected behavior - activate Purify skill with Cleansing Power tactic while self targeted and group cleanse 1 debuff for each member
Actual Behavior - activate Purify skill with Cleansing Power tactic while self targeted and only cleanses 1 debuff on self

**Steps to reproduce the problem:**
Group up. Get debuffed and follow instructions above for expected behavior

**Testing Screenshots/Videos/Evidences (always needed):**
Video file/zip file too large to upload but available as needed.
Not working:
![cap_Not Working_00_00_06_02](https://user-images.githubusercontent.com/63861624/82613900-85c58180-9b94-11ea-83b6-6d616c944cb7.jpg)
![cap_Not Working_00_00_05_01](https://user-images.githubusercontent.com/63861624/82613906-878f4500-9b94-11ea-8eea-ebca9fb7aabf.jpg)
GIF uploaded here https://gfycat.com/improbableultimatebasilisk

Working as intended:
![cap_Working_00_00_06_01](https://user-images.githubusercontent.com/63861624/82614101-02586000-9b95-11ea-9598-1536f88177cd.jpg)
![cap_Working_00_00_06_02](https://user-images.githubusercontent.com/63861624/82614106-03898d00-9b95-11ea-8d82-c536b4ee0e20.jpg)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16520
