### ISSUE TITLE
Quest icon above NPC's is flickering from completed (orange) to uncompleted (grey)

### ISSUE THREAD

**Issue by detrap** [WarEmu/WarBugs#16927]
Even though the quest is completed it, the icon above the head of the NPC will flicker from orange to grey to sometimes showing no icon. The scenario npc in altdorf and the npc in warcamp eatine that rewards seal of the exemplar have had these issues.

![Screenshot 2020-05-23 15 10 09](https://user-images.githubusercontent.com/64330047/82722186-b11cad80-9d07-11ea-80b3-bd90b2622a61.png)

**Comment by Kaelang** [comment]
Duplicate of https://github.com/WarEmu/WarBugs/issues/16910.
