### ISSUE TITLE
Full painting 50 coins

### ISSUE THREAD

**Issue by Librium1981** [WarEmu/WarBugs#16929]
![Fal_004](https://user-images.githubusercontent.com/65770198/82724729-d77b2280-9ce0-11ea-94b8-e7d5961adc83.jpg)

**Comment by Kaelang** [comment]
![image](https://user-images.githubusercontent.com/60117106/82730598-d48c2c00-9cf8-11ea-9a2b-a9dae8f9cb92.png)
Can confirm that Jewellery is now being taken into consideration with the 'Dye All' option, causing the increase in price.

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by Kaelang** [comment]
This should have been fixed as of 27/05/20. Please re-open if issue persists.
