### ISSUE TITLE
Rune of Battle not consistently working.

### ISSUE THREAD

**Issue by knightningale90** [WarEmu/WarBugs#1692]
Hello. The runepriest ability - rune of battle does not always work, no matter it is on an ally or on the caster, even if I stand very still during casting.
![centercross_083](https://cloud.githubusercontent.com/assets/14324838/10564733/5be43e56-75f1-11e5-9b28-7b401d1b5299.jpg)
![centercross_081](https://cloud.githubusercontent.com/assets/14324838/10564735/64f6a452-75f1-11e5-81bf-c4800cf19c49.jpg)

First picture shows that when it actually works, buffhead shows the icon with wsct showing the damage on rats coming from the ability. You can see the last ability on the second ability bar is on cd.

Second picture shows that when the ability goes straight to cd, nothing shown on buffhead and the same ability slot on the ability bar is on cd. 

Both instances are cast on myself. 
While it does seem to have a higher tendency not to work when no hittable targets are around, there is also a chance that it doesn't work when my ally or myself is surrounded by destro players. Not sure what the factors are but it is not consistently working. 

Would really appreciate it if devs can have a look at it :)

**Comment by ozarmidrashim** [comment]
Would fail to cast if no foes were in range.
