### ISSUE TITLE
Entering fort without reservation

### ISSUE THREAD

**Issue by s0undie** [WarEmu/WarBugs#16923]
I did a search for the exact phrase in title and it didn't come up with anything. 

As you noramlly lock an end zone it will give you a reservation or you can queue for forts. I entered the fort before the endzone locked. I was not given a reservation slot and that way i bypassed the queue. 

Be in fort area before the end zone locks

![image](https://user-images.githubusercontent.com/14369390/82709801-b8997380-9c81-11ea-8e73-fea018f0037f.png)

If this isn't a game break then what is?

Fort in question was Reikwald, i joined a wb, got xp/rr for kills, got killed and ressed, when i died and released i was teleported out.

**Comment by Kaelang** [comment]
See the bottom left, you won't get any rewards for the fort.

I appreciate you reporting this issue - however I'm going to merge it with the other. 

https://github.com/WarEmu/WarBugs/issues/16409
