### ISSUE TITLE
Shields for SW ( Scout Emblem Merchant)

### ISSUE THREAD

**Issue by Lnternsmite** [WarEmu/WarBugs#16922]
The picture below shows shields from the scout merchant to the SW. is this a way to say that shadow warriors will be Lothern Sea Guard now  XD???

![Finavar_000](https://user-images.githubusercontent.com/53047875/82707932-0e9ef480-9c4b-11ea-97bc-768c9eb2d80a.jpg)

**Comment by Kaelang** [comment]
Clear your game cache and try again - I don't see these items.

**Comment by Lnternsmite** [comment]
![Finavar_001](https://user-images.githubusercontent.com/53047875/82742036-00260b00-9d27-11ea-9b28-4a3643c0ec56.jpg)

No, so i went and manually look for the sword after clear cache.  the sword , i bought it and it doesnt equip, having red on sword
