### ISSUE TITLE
Should the Mighty Soul Tactic applies to morale?

### ISSUE THREAD

**Issue by detrap** [WarEmu/WarBugs#16926]
I thought tactics/abilities would not apply any effect to morale unless there is some cc immunities? The combination of mighty soul and raze can also do critical damage. Again not sure morale abilities should be doing critical damage as well.

Tooltip for Mighty Soul:
![Screenshot 2020-05-23 12 37 06](https://user-images.githubusercontent.com/64330047/82719944-49a83300-9cf2-11ea-936c-b235c1161da0.png)

Tooltip for Raze:
![Screenshot 2020-05-23 12 37 14](https://user-images.githubusercontent.com/64330047/82719962-5c226c80-9cf2-11ea-92ad-caf416eb58cf.png)

Effect in-game scenario:

![Screenshot 2020-05-23 12 31 41](https://user-images.githubusercontent.com/64330047/82719886-d0a8db80-9cf1-11ea-9d4f-482d20615ef7.png)
![Screenshot 2020-05-23 12 30 27](https://user-images.githubusercontent.com/64330047/82719890-d2729f00-9cf1-11ea-8a9e-974762833082.png)

**Comment by Rudmed** [comment]
I can also confirm that something appears to be wrong with the interaction between Mighty Soul and Morale Abilities. I decided to test it while out roaming and trying a small scale build when I dropped Demolishing Strike on a lower leveled choppa. Needless to say, I was surprised when I noticed that my damage log revealed that he was mitigating damage.

![Demolishing strike and mighty soul 1](https://user-images.githubusercontent.com/65800448/82721281-cd7a0500-9c89-11ea-93f2-7c8c5e3fdb6b.png)

**Comment by M0rw47h** [comment]
Today **Urgolf** found suspicious behaviour of Discordant Winds, which is more or less mirror to Mighty Soul. He found that it not only makes morale damage not morale anymore, as it gets affected by resistances and other damage reductions, but it also makes morale able to crit, same happens to damage dealt by Oil. Some screenshots bellow from his testing:

Discordant Winds:
![Nowy projekt (9)](https://user-images.githubusercontent.com/35219756/84653947-a3c1a000-af0e-11ea-8b9e-10e81e5bf18a.png)

Raze damage with Discordant Winds (tested by Urgolf):
![chosen raze](https://user-images.githubusercontent.com/35219756/84654316-3f531080-af0f-11ea-8d00-95a98f587ffa.jpg)

Oil damage with Discordant Winds (tested by Urgolf on me):
![Nowy projekt (11)](https://user-images.githubusercontent.com/35219756/84654547-b092c380-af0f-11ea-9f52-3f581d6e1369.png)
![Nowy projekt (11)](https://user-images.githubusercontent.com/35219756/84654650-dae48100-af0f-11ea-8967-4a76240a7903.png)
^^Damage got different numbers based on defensive abilities used like Vigilance or Gather Your Resolve! (resist aura).

Oil damage with Mighty Soul (tested by me on Urgolf):
![unknown (3)](https://user-images.githubusercontent.com/35219756/84655751-cc976480-af11-11ea-9961-5bbeae1e4930.png)
^^Once again damage affected by auras.

Raze damage with Mighty Soul on dummies, damage is same as they are just dummies but it does CRIT!:
![unknown (4)](https://user-images.githubusercontent.com/35219756/84655880-0e280f80-af12-11ea-99da-25bfd24b9f51.png)

**Comment by Rudmed** [comment]
I have additional confirmation regarding mighty soul. I went and smacked someone with a demolishing strike morale and if you take a look they are mitigating a small amount of the morale damage. Clearly, there appears to be something a little off about how it affecting all damage. The code might need to be narrowed down so Mighty Soul only affects skill and autoattack damage.

![image](https://user-images.githubusercontent.com/65800448/90581593-a0aa9080-e199-11ea-8082-1220995ab032.png)

**Comment by Kaelang** [comment]
Discordant Winds / Mighty Soul have been removed in todays patch.
