### ISSUE TITLE
60000 RR

### ISSUE THREAD

**Issue by Librium1981** [WarEmu/WarBugs#16921]
![Fal_002](https://user-images.githubusercontent.com/65770198/82669957-fe841680-9c44-11ea-9b3f-1afd90c984eb.jpg)

**Comment by Vayra** [comment]
Did a zone/fort lock or a keep get captured during the scenario? The scoreboard shows all renown gained during the scenario, not just from the scenario itself, so keep takes and zone locks can give weird results like that.

**Comment by Kaelang** [comment]
Judging from the SoR, I'm guessing he was a part of the fort prior, joined the scenario as the fort ended (gaining huge renown) and then progressed to complete the scenario with an inflated scoreboard.

Can you confirm if the fort ended whilst inside the scenario?

**Comment by Kaelang** [comment]
Closing.
