### ISSUE TITLE
Banish Darkness Tactic doesn't reduce the cooldown of Repel Darkness. Maybe distance is bugged too? 

### ISSUE THREAD

**Issue by Twicckk** [WarEmu/WarBugs#16925]
Banish Darkness Tactic doesn't reduce the cooldown of Repel Darkness. Maybe distance is bugged too? 

Check video attached, this is after a fresh log in after deleting my cache folder.

![ezgif-1-27c866fb553a](https://user-images.githubusercontent.com/63669306/82719331-1bcdda80-9c6f-11ea-845f-4a950a938457.gif)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/15518
