### ISSUE TITLE
Pulled inside Nordenwatch scenario fortress objective flag

### ISSUE THREAD

**Issue by McManlet** [WarEmu/WarBugs#16931]
Hi, moments ago I was pulled inside the flag in Nordenwatch and no matter how much I tried /stuck or .u I couldn't get out and the enemies couldn't target me with abilities. I tried mounting and wiggling but didn't want to book out of the match that we were winning even before I got stuck.

![Bug1](https://user-images.githubusercontent.com/65816564/82731590-c3e7b000-9d10-11ea-83cd-1a1702a972d5.jpg)
![Bug2](https://user-images.githubusercontent.com/65816564/82731592-c813cd80-9d10-11ea-9766-97d2083be9d9.jpg)
![Bug3](https://user-images.githubusercontent.com/65816564/82731595-ca762780-9d10-11ea-92ea-e66353050b45.jpg)

**Comment by MaxHayman** [comment]
Should be fixed with the new /suck logic.
