### ISSUE TITLE
Beastlord Taen does not show up (has no visuals)

### ISSUE THREAD

**Issue by Eddie84Style** [WarEmu/WarBugs#16939]
as you can see from the screenshot the "show item" is checked and I did not use any alternate appearence for it. I've had this item for many months now, so it dropped before the armor looks overhaul, if that is of any use. It was showing normally when I dropped it a long time ago, and I noticed this only today

![bl taen](https://user-images.githubusercontent.com/65578235/82742169-c3740700-9d5a-11ea-8cfc-bf6a7478b953.jpg)

**Comment by Kaelang** [comment]
This should have since been fixed.

**Comment by HeiLei1994** [comment]
The helmet is still missing.

**Comment by wargrimnir** [comment]
should look like this after the patch https://i.imgur.com/RKOdDIQ.png
