### ISSUE TITLE
Found a bug to avoid BS weapons minus effect ( armor /tougness)

### ISSUE THREAD

**Issue by crazyturkme** [WarEmu/WarBugs#16934]
Hey,

I checked previous reports about Bloodlord weapons but i didnt see similar topic about this issue so im opening new one.

As you know using bloodlord weapons give you - armor and -tougness but there is a bug/way to get rid of it. You can see the video below i explained detaily. Sorry for my Bad english but you will understand it.

This effect will last until you log off so you can do it again when you come back online. This might seen as a small bug but its still bug. 

I hope its enough to get mount ;) 
Cheers.

https://streamable.com/2i3thf

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16895
