### ISSUE TITLE
witchhunter

### ISSUE THREAD

**Issue by cececeliana** [WarEmu/WarBugs#16930]
hello with the latest version of moralecircel I could see that when I put myself in stealth mode the number 1 goes out bug and takes the same moral 4 for my WE
![Capture d’écran (22)](https://user-images.githubusercontent.com/38669943/82730443-0228a380-9d00-11ea-9934-37bf83fd35da.png)
![Capture d’écran (22)](https://user-images.githubusercontent.com/38669943/82730452-15d40a00-9d00-11ea-993c-20a64f4c2381.png)

 

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by SilverWF** [comment]
Well known bug related to the addon itself only
Check addon page for the solution or ask author to finally fix this.
https://tools.idrinth.de/addons/moralecircle/
