### ISSUE TITLE
[NPC] Devak Bloodbane - Visual is missing a chair. 

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#16936]
while its comical, I don't think this visual bug of him sitting backwards is intended
![Nooblit_069](https://user-images.githubusercontent.com/44329952/82739182-2a65d180-9d03-11ea-89a2-c302c3fc9fd8.jpg)

**Comment by Lheana** [comment]
His place is correct, something made him move maybe but not an issue here.
![Anaehll_179](https://user-images.githubusercontent.com/11537611/82755394-797b3780-9dd3-11ea-8372-170dd5e91675.jpg)
