### ISSUE TITLE
Quest-NPC in Warcamps show wrong icons

### ISSUE THREAD

**Issue by Malvaine** [WarEmu/WarBugs#16937]
**Expected behaviour: After accepting the repeatable quests in the t4-warcamps and from the keeplords (order), the icon above the quest-npc changes from blue to brownish and the icon on the mini-map, too.
Experienced behaviour: The colour of the icon above the npc and on the map changes constantly. Sometimes blue, sometimes brownis, although my char accepted the quest. It is irritating, because I always think that I haven't accepted the quest.

**Steps to reproduce the problem:** Enter a warcamp or a keep, accept the quest and just run around a bit or leave the area and return after a minute.

![Malvain_000](https://user-images.githubusercontent.com/57098865/82740682-6755b680-9d4b-11ea-8466-2c0049f18bbd.jpg)

I have accepted the quests - icon = blue

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16910
