### ISSUE TITLE
T1 Norsca repeatable scouting quest gives incorrect amount of exp.

### ISSUE THREAD

**Issue by Asderas27** [WarEmu/WarBugs#16942]
The T1 scouting quest in Norsca which requires you to scout 3 objectives gives 509 exp instead of 5090 as that is amount you get when completing repeatable scouting quests for Blighted Isle and Mount Bloodhorn
![T1 norsca](https://user-images.githubusercontent.com/65857081/82755616-5f048680-9df2-11ea-853c-a52def5802a1.jpg)
![T1 Mt Bloodhorn](https://user-images.githubusercontent.com/65857081/82755618-6330a400-9df2-11ea-9295-8add267673f0.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by Kaelang** [comment]
This should have been fixed as of 27/05/20. Please re-open if issue persists.
