### ISSUE TITLE
My contribution rank is always less than 15.

### ISSUE THREAD

**Issue by zlukich** [WarEmu/WarBugs#16949]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by zlukich** [comment]
I have played more than 20 citites, and have never contributed to reach more than 15 contribution rank(each stage), i think this is a bug.
Account name: Shootnik
Character name: Leviossaaa

**Comment by Kaelang** [comment]
City Contribution is working as intended and unless you can validate your reasoning behind why the contribution system is not working, I can't do anything with such report.

Thanks.
