### ISSUE TITLE
Securing the Pass Quest Bloody Sun Drummas

### ISSUE THREAD

**Issue by TingleSack** [WarEmu/WarBugs#16946]
**Expected behavior and actual behavior:**

When attempting to fight the Drummas with my Ironbreaker, I was unable to select them as a target. I had to stand next to the Drummas in order to agro them. I would then get error messages saying that the target couldn't be attacked however I was still able to use my abilities and kill them. I was then unable to loot their bodies.

**Steps to reproduce the problem:**

I went through this process with multiple Drummas and would wait for the ones that I killed to respawn and repeated the process.
[Return of Reckoning 2020-05-24 22-37-05.zip](https://github.com/WarEmu/WarBugs/files/4675000/Return.of.Reckoning.2020-05-24.22-37-05.zip)

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
You recorded your launcher in the video.

Please could you re-upload?

**Comment by Kaelang** [comment]
This should have been fixed as of 27/05/20. Please re-open if issue persists.
