### ISSUE TITLE
Reikwald not letting me in

### ISSUE THREAD

**Issue by SetchDreskar** [WarEmu/WarBugs#16947]
Got a reservation for Reikwald, fought in it, killed 6 destro with the alliance warband, got killed by the destro nascar, respawned in pve outside the door too Altdorf, used the beach to try and come back, was ported to the reikwald door and given the error...

Please let there be a fix for this at some point... getting booted out of fort when you had a reservation, and losing out on that renown and rolls is brutal.

![Big sad](https://user-images.githubusercontent.com/9970998/82776268-5f177d00-9e18-11ea-9d41-c66a57195e9c.png)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16409
