### ISSUE TITLE
Tracker's Mailcoat - Wrong Icon, and invisible

### ISSUE THREAD

**Issue by Jesden** [WarEmu/WarBugs#16959]
**Expected behavior and actual behavior:**
The Icon for the White Lion Chestpiece 'Tracker's Mailcoat' is of a pair of boots, and when equiped does not equip anything visually to the body slot. (the item is equiped and stats change appropriately however.

**Steps to reproduce the problem:**
Have relogged and reloaded ui to see if that would fix it, no positive result however.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/65976082/82938450-c43eb000-9f89-11ea-9acd-c729459a6838.png)
![image](https://user-images.githubusercontent.com/65976082/82938515-df112480-9f89-11ea-8aae-1eeb47aace87.png)
![image](https://user-images.githubusercontent.com/65976082/82938561-efc19a80-9f89-11ea-974d-43fb5a63fe8b.png)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by Kaelang** [comment]
This should have been fixed as of 27/05/20. Please re-open if issue persists.
