### ISSUE TITLE
Ability/Zealot/"Harbinger of Doom" - tooltips numbers not updating

### ISSUE THREAD

**Issue by Kushido** [WarEmu/WarBugs#1695]
When you turning on/off it you changing "stances", stats converting to each other.
But tooltips of any dmg skill/heal not updating by this.
If im turning on/off and trying to heal my self - its working properly. When its in dps stance - im healing less, if im in healer stance - its healing more (by looking in combat log).
So i guess its working well with dmg too?
And we just have visual bug in tooltips?

Also if im using HoT in healer stance and will switch to dps stance - it will tick as im in healer stance. If i'll HoT in dps stance and will switch to my healer stance - it will tick less, cos i put it on myself with less healing stats.
So its not scaling dynamic and this mechanic is right?

**Comment by Evildoor** [comment]
HoTs/DoTs ticking for the full duration using stats as they were at cast time are incorrect, but this matter is known, complicated and will remain unchanged for now (see #1444 for more details).

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
