### ISSUE TITLE
Diminishing Rations when we have AAO

### ISSUE THREAD

**Issue by SetchDreskar** [WarEmu/WarBugs#16953]
I did not catch this screenshot at first when we still had AAO but as you will notice even when we have even numbers with destro, neither side having AAO anymore, I still have the diminishing Rations debuff...

![Diminishing Rations when even](https://user-images.githubusercontent.com/9970998/82856951-86844d80-9edd-11ea-8482-4d1ac0ba5c9a.png)

Man this game got way buggier when ranked seasons came in didn't it?

**Comment by Kaelang** [comment]
This looks to be related on the already active report of Diminishing Rations playing up - see https://github.com/WarEmu/WarBugs/issues/11508.

I'm going to merge the two together and make a note of this one.

Thank you for the report.
