### ISSUE TITLE
[Magus] Dissolving Mist never crit

### ISSUE THREAD

**Issue by nohh** [WarEmu/WarBugs#16954]
![mist1](https://user-images.githubusercontent.com/19315739/82876067-dfd19880-9f40-11ea-9a2a-3c8651eb55ed.png)

![mist2](https://user-images.githubusercontent.com/19315739/82876077-e3fdb600-9f40-11ea-908b-fb7ff8648e65.png)

But Napalm able to crit:
![napalm](https://user-images.githubusercontent.com/19315739/82876101-ee1fb480-9f40-11ea-9074-5ab831248df4.png)

**Comment by Kaelang** [comment]
Dissolving Mist and Napalm Grenade

- Base damage and Primary Stat Mult have both been increased significantly.

This is to follow up on changes last week that removed the ability for this damage to crit and deal proc damage. Testing with 1100 INT and damage buff from the pet, unmitigiated, Dissolving Mist deals about 700 damage every 2s at the third stage of the damage ramp. This should make this 13pt spec ability less trivial for PvP uses, but will still be monitored over the next patch to see if it is still over/underperforming.

However - considering your Napalm is critting, I'm going to keep this open to see where the issue could potentially lie whilst I look to get verification.

Thanks.

**Comment by SilverWF** [comment]
Napalm still can crit
![img-2020-05-26-23-54-19](https://user-images.githubusercontent.com/16439840/82949418-3f18c280-9fac-11ea-958c-085653bc36a2.png)

**Comment by dalen** [comment]
This seems fixed now 
![image](https://user-images.githubusercontent.com/7400/98096584-39dd6f00-1e8c-11eb-881b-78a82dc5ab09.png)
