### ISSUE TITLE
Savage weapon offhand issue

### ISSUE THREAD

**Issue by wildwindblows** [WarEmu/WarBugs#16952]
Hello,
Altough "Savage" is Main Hand or Offhand weapon (tooltip say like this), I couldn't use it on off hand. For example, I want to use dual Savage but i can't use it for off hand like you saw on the screenshot below. I also tried different Sentinel weapon (Chimera's Bane)and no problem was encountered.

Thanks.

![resim](https://user-images.githubusercontent.com/45720515/82846881-af174200-9ef3-11ea-9348-8d420d245faa.png)

**Comment by Kaelang** [comment]
Unique-Equipped, you can't wear two.
