### ISSUE TITLE
Deathaxe of dreams

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#16956]
deathaxe of dreams is a 2hand axe and has the appearance of a 1hand sword
![Daemon_012](https://user-images.githubusercontent.com/44329952/82906974-a3e00880-9f2b-11ea-8aa4-eb8e8dbf14eb.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by Kaelang** [comment]
This should have been fixed as of 27/05/20. Please re-open if issue persists.
