### ISSUE TITLE
scenario vendor who sells triumphant vendor bugged?

### ISSUE THREAD

**Issue by warhammer2020** [WarEmu/WarBugs#16958]
hi

I started doing ranked scenarios from the patch of April 29th when they brought in the 2 new armours from the ranked solo scenario.
I have done nearly at least 2 scenarios a day since then with the occasional day or 2 i missed.
Anyways I have done over 60 scenarios. I can see how many scenarios i have done by logging onto the return of reckoning website and checking wins and losses. This is very accurate it seems, however it counts d/c as losses.
I have been checking both vendors and trying to buy items and It used to say.... you have only done 45 ranked scenarios. So all was good. However last week my scenario count got reset to zero.
I dont understand why. The season is supposed to be 6 weeks and i was expecting it around June 10th. I have definitely done the minimum required per week.
Was there some hidden reset or is it bugged? The website still shows I have done over 60. I am confused.
regards

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16785
