### ISSUE TITLE
Report Player

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#16968]
reporting a players message is nolonger working, when it says "are you sure you wish to report this message and click "Okay" nothing happens :( I can nolonger snitch on my realm mates.
![Daemon_019](https://user-images.githubusercontent.com/44329952/83078731-da0eac80-a03f-11ea-87bd-93ca82545b4e.jpg)

**Comment by Lheana** [comment]
I had confirmation from the GMs that the reports work fine, and they got your reports.
