### ISSUE TITLE
Guild Vault 4th tab not unlocked upon reaching guild rank 33

### ISSUE THREAD

**Issue by Asovrih** [WarEmu/WarBugs#16960]
As you can see in the screenshot we just hit rank 33 which should unlock the 60 slots for the 4th tab.
Incidentally, we did purchase the 1st row of the 4th tab before we reached rank 33.
![Grimnebulin_011](https://user-images.githubusercontent.com/65978354/82969036-a9296b80-9f9c-11ea-9c5a-b8180f481be3.jpg)

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Can you try running without addons?

**Comment by Asovrih** [comment]
I disabled all mods and re-enabled them 1 by 1 and the status of guild vault tab 4 never changed and only still had the top row open with no option to buy additional rows.  However, the option(text) to purchase additional rows in guild vault 5 DID appear after disabling the mod called MoveWindows.
![Grimnebulin_000](https://user-images.githubusercontent.com/65978354/83042574-ccd9c980-a00f-11ea-8eac-e04d35b7c796.jpg)
![Grimnebulin_001](https://user-images.githubusercontent.com/65978354/83042595-d19e7d80-a00f-11ea-9ef4-4d7213a84dfa.jpg)

**Comment by Kaelang** [comment]
From the screenshots, the guild level gave you access to Guild Vault 4, and also gives you the ability to purchase them. If there's nothing else, I'll close this up.

**Comment by Asovrih** [comment]
It did NOT give me the ability to purchase them.  Like I said in above post, despite disabling all mods, the status of guild vault tab 4 remains the same with NO option to purchase additional rows.
![Grimnebulin_002](https://user-images.githubusercontent.com/65978354/83044993-f8aa7e80-a012-11ea-89c4-1011e9d09843.jpg)
