### ISSUE TITLE
magical salvaging talisman makinhg  and map showing problems

### ISSUE THREAD

**Issue by antcharal** [WarEmu/WarBugs#16965]
hello 
i have 3 problems
1/ magical salvaging dont work in any of characters of my account.
    when i try to break an item i can not see the options of what matterials to choose .
2/ at talisman making window when i drop the matterials to make the talisman they r not visible.
3/ my map dont show proper
    
![magical salvaging problem](https://user-images.githubusercontent.com/66030018/83053765-e9025880-a059-11ea-85f5-6c11755c571b.jpg)
![map problem ](https://user-images.githubusercontent.com/66030018/83053776-eb64b280-a059-11ea-87ba-844b78ad7fcd.jpg)
![talisman making problem](https://user-images.githubusercontent.com/66030018/83053777-ebfd4900-a059-11ea-9d9e-ae560bf8d185.png)

**Comment by Kaelang** [comment]
This looks like an issue with the installation - or potentially the language file you're using.

Magical Salvaging is working for the rest of the community, so this looks to be an issue with your client. Please look to reinstall with working files and/or look for help on the forums.

**Comment by Blumenpeter** [comment]
Greating antcharal, 
did you found a a answer of these problem?  I have the same.

**Comment by antcharal** [comment]
@Blumenpeter 

If u want to save time just delete your client and install a "fresh" one..
And dont think backup your addons cause the problem was returning.
So ..one way road...fresh client and addons
