### ISSUE TITLE
Missing a Mastery Point at 40/40

### ISSUE THREAD

**Issue by Scabbyskinz** [WarEmu/WarBugs#16969]
**Expected behavior and actual behavior:** From the research I've done you're supposed to have 26 mastery points when you're 40/40. My Marauder (Aartix) has 25 and is unable to complete the build I desire.

**Steps to reproduce the problem:** Level a Marauder to 40, Check in with Career trainer, Check amount of points received.

Images attached show the 25 available points, Warbuilder (which could be wrong) build, and My career / renown ranks.

**Testing Screenshots/Videos/Evidences (always needed):**
![tree12pts](https://user-images.githubusercontent.com/62901679/83079817-8ff3ee00-a074-11ea-8280-9c7bfd6af16f.jpg)
![tree13](https://user-images.githubusercontent.com/62901679/83079823-93877500-a074-11ea-8af8-7d4103e2b58e.jpg)
![cr40rr40build](https://user-images.githubusercontent.com/62901679/83079826-96826580-a074-11ea-9b1e-5d0b08489cea.jpg)

**Comment by SilverWF** [comment]
Just to be sure: have you tried to relog?

**Comment by Scabbyskinz** [comment]
Hey there Alexander,
It has since been fixed but at the time I tried multiple options including:
Reloadui, Logging, and Relaunching the client.
Not sure why it suddenly fixed itself, But it happened on Patch Day that I
was able to get that point I was owed.

Many thanks
