### ISSUE TITLE
Character flagged as permanently Rooted

### ISSUE THREAD

**Issue by SetchDreskar** [WarEmu/WarBugs#16973]
As the title suggests, I was hoping the server restart would fix it, but it sadly has not.

![Character tagged as permanently rooted](https://user-images.githubusercontent.com/9970998/83087085-64660900-a05e-11ea-952b-5e9fbb5fcb93.png)

No idea how to fix it, my WH is the only one affected by it.

As a note, I have disabled CCTV, redone it. No fix.

Deleted CCTV, closed the game, redownloaded CCTV, enabled. No fix.

Tried multiple /rel just to hope. No fix.

**Comment by Kaelang** [comment]
Type .gm and contact a GM - see if they're able to kill you. Unfortunately there's no replication steps here so no way to look at identifying and fixing this issue.
