### ISSUE TITLE
No invader medallions from fortress

### ISSUE THREAD

**Issue by Tanatasa** [WarEmu/WarBugs#16977]
1 Royal
4 Vanquisher
![celoris](https://user-images.githubusercontent.com/66071634/83147296-2a4d4380-a100-11ea-9bca-adbe3e5075dd.png)

**Comment by Tanatasa** [comment]
![celoris 2](https://user-images.githubusercontent.com/66071634/83233096-df323f80-a196-11ea-993e-d800ca51d060.png)

**Comment by dalen** [comment]
Likely it is because you are below renown rank 50
