### ISSUE TITLE
Divine strike and sigmar's radiance potential misbehavior on block and parry

### ISSUE THREAD

**Issue by ninebeards** [WarEmu/WarBugs#16971]
**Expected behavior and actual behavior:**

Sigmar's radiance tooltip appears to indicate heal on attack with healing triggering even if parried or blocked, and that you get extra healing based on the damage which was actually dealt. "The power of sigmar erupts from your weapon, healing any of your groupmates within 100 feet for 85% of total ability damage plus 50% of the damage that you dealt." In duel testing Sigmar's radiance does not heal at all if the attack is blocked or parried.

Example:
Attack 1) Sigmar's radiance parried:
Raulond parried your Sigmar's Radiance.
No heal results

Attack 2) Auto attack, not relevant:
Raulond blocked your attack.

Attack 3) Sigmar's Radiance hits and heals as expected:
Your Sigmar's Radiance hits Raulond for 16 damage. (235 mitigated)
Your Sigmar's Radiance heals you for 0 points. (245 overhealed)

Divine strike tooltip text appears to be the opposite of Sigmar's Radiance, healing only the damage dealt: "The divine power of sigmar heals your defensive target and any allies withing 10 feet of them for 100% of the damage that was dealt". However when divine strike is parried or blocked, healing still occurs.

Raulond blocked your Divine Strike.
Your Divine Strike heals you for 0 points. (65 overhealed)
Your Divine Strike heals Brizhul for 0 points. (65 overhealed)

**Steps to reproduce the problem:**

Use divine strike and sigmar's radiance on target, wait for a block or parry, healing does or does not result based on ability used.

**Testing Screenshots/Videos/Evidences (always needed):**

**Sigmar's radiance block doesn't result in heal:**

![Mettius_021](https://user-images.githubusercontent.com/66043986/83086558-f57bb680-a043-11ea-92c2-eb26b77818bd.jpg)

**Divine strike healing on block which is appears it shouldn't**
![Mettius_022](https://user-images.githubusercontent.com/66043986/83086634-28be4580-a044-11ea-977e-82ea11799241.jpg)

**Comment by Rydiak** [comment]
Sigmar's Radiance has never, nor is it intended to, healed on an avoided attack.

**Comment by Rydiak** [comment]
![Rydiak_125](https://user-images.githubusercontent.com/15963532/83094258-ea864d80-a066-11ea-9dd8-55b7e22fc321.jpg)
![Rydiak_126](https://user-images.githubusercontent.com/15963532/83094262-ec501100-a066-11ea-8721-2b8651e56542.jpg)
![Rydiak_127](https://user-images.githubusercontent.com/15963532/83094267-efe39800-a066-11ea-8152-fd879a0a6fd4.jpg)

Can confirm.  Divine Strike is healing off of targets that block/parry its attack.

**Comment by Vayra** [comment]
Does it happen if you don't hit additional targets?

**Comment by ninebeards** [comment]
My example is divine strike only hitting one target.

**Comment by ninebeards** [comment]
![image](https://user-images.githubusercontent.com/66043986/83148247-93f03200-a0ad-11ea-8d28-c92504b7eae8.png)

**Comment by Kaelang** [comment]
Fixed in previous patch.
