### ISSUE TITLE
Character "Defense" stats not showing correctly

### ISSUE THREAD

**Issue by Helspyre** [WarEmu/WarBugs#1697]
I put a few points into parry and the stat on my character screen is still showing as zero. I've relogged and noticed no change.

Screenshot attached.
![ror_defensebug001](https://cloud.githubusercontent.com/assets/15188398/10568914/42ec1cca-75d3-11e5-8252-898e6a853cd1.jpg)

Not sure about other defensive stats but they may have the same issue.

I noticed a similar bug was reported and closed awhile ago, so maybe it was never fully resolved, or it has resurfaced.
https://github.com/WarEmu/WarBugs/issues/626

**Comment by Evildoor** [comment]
Not implemented yet. You can get your parry/block/whatever by targeting yourself and typing .getstats into Say (but you better do it in PVE, because i've noticed that bolster may increase your defence stats from renown points).

**Comment by Helspyre** [comment]
That works.  Thank you!
