### ISSUE TITLE
Quest "Cry Wolf" GS Chap 9

### ISSUE THREAD

**Issue by adriftsc** [WarEmu/WarBugs#16979]
The camp is called Mobash's place and is located in Barak Varr. It's the orc camp to the north. The bug is with multiple quests that has talismans as a quest reward. "Cry wolf" for example. When i try to pick the ballistic or intellect talisman nothing happens, it just closes the quest window. I can only complete the quest by picking the other talismans. This can't be correct right? Thanks guys love you for working on this amazing game!

**Comment by Lheana** [comment]
You talk about several quests that have this issue. You mention "Cry Wolf", but if there are other quests please create a new bug report mentioning each quest where you face this issue.
