### ISSUE TITLE
Invader Set - 6 Piece Bonus / Red Frenzy and 7 Piece Bonus - Overwhelm

### ISSUE THREAD

**Issue by ismetto84** [WarEmu/WarBugs#16975]
Choppa

Invader Set

6 Piece Bonus / Red Frenzy
Auto attack damage by %25 for 5 seconds, not change auto attack damage..

7 Piece Bonus / Overwhelm 
its not working, I can't see the extra %10 or %20 Armor Penetration

6 and 7 Piece Bonus, this is passive? or?

Thanks for giving time..

**Comment by grunbag** [comment]
Use .get stats , it works
