### ISSUE TITLE
Riekwatch OBJ's

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#16982]
OBJs arent showing on map correctly (2nd stage, all are controlled by one side or the other) 
![Daemon_026](https://user-images.githubusercontent.com/44329952/83184942-d20e4580-a0ef-11ea-9e3b-d50b009f549a.jpg)

**Comment by Kaelang** [comment]
The team are aware of the issue with Reikwatch and are investigating. Thank you for the report however.
