### ISSUE TITLE
PQ not updating, 

### ISSUE THREAD

**Issue by Jesden** [WarEmu/WarBugs#16988]
**Expected behavior and actual behavior:**
Public Quests are not updating to the correct stage, and no loot roll is awarded at the end of the PQ.

Despite participating in a public quest, the tracker is not updating, staying at the stage it is when entering the vicinity. Influence is still awarded for the kills however.

**Steps to reproduce the problem:**
Participated in 2 hard public quests twice each, Mirelen and Laurilion caves. Each time the problem persisted. 
Attempted to Reload UI, and general Reload through / commands, no effect.
Closed down the game and relogged, and still persisted.

Update - Tried Battle at Blood Fen. Same result regarding tracker not updating, however, loot roll was successful. However, it didn't seem to pick up one of my party

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/65976082/83311174-5226cf00-a206-11ea-84d9-e39fa44700b8.png)
![image](https://user-images.githubusercontent.com/65976082/83311863-72f02400-a208-11ea-9237-dd16872d81ee.png)
(another PQ tested, note the chest and the level of the PQ)
![image](https://user-images.githubusercontent.com/65976082/83311964-bba7dd00-a208-11ea-8faa-8b128e612297.png)
(SS showing influence gain)
![image](https://user-images.githubusercontent.com/65976082/83312176-5e605b80-a209-11ea-9107-72df38416f1c.png)
(updated stage but not the correct number of pillars)
![image](https://user-images.githubusercontent.com/65976082/83312560-9b791d80-a20a-11ea-8e92-b5ff49c6f663.png)
(stage 3 boss, stage 2 showing)
![image](https://user-images.githubusercontent.com/65976082/83312670-1e9a7380-a20b-11ea-82bd-e19522f32258.png)
(stage 4 boss, stage 2 showing)
![image](https://user-images.githubusercontent.com/65976082/83312688-2a863580-a20b-11ea-887d-9988bb3a57a5.png)
(PQ reset, but still showing stage 2)
![image](https://user-images.githubusercontent.com/65976082/83312853-d3cd2b80-a20b-11ea-9963-86d7e9271d50.png)
(another tested PQ)
![image](https://user-images.githubusercontent.com/65976082/83313276-6de1a380-a20d-11ea-8c0a-f90edcb6cd89.png)

**Comment by MaxHayman** [comment]
Hello,

Is this still happening after the patch yesterday?

Thanks,
Max

**Comment by Razielhell** [comment]
Looks fine now, behaving normally.
