### ISSUE TITLE
Spites Reach Lord

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#16983]
Spites reach lord just be chillin on 3rd floor instead of lords room
![Daemon_029](https://user-images.githubusercontent.com/44329952/83198394-b6fa0080-a104-11ea-855a-0acc2b96dd9c.jpg)

**Comment by Kaelang** [comment]
No idea what you mean with this.

**Comment by Xicoz** [comment]
the lord is on 3rd floor for no reason. instead of lords room

**Comment by Kaelang** [comment]
Does this happen everytime?
