### ISSUE TITLE
apothecary bugged

### ISSUE THREAD

**Issue by alyssonpaladini** [WarEmu/WarBugs#16992]
Was trying to level up apothecary.
After the server crashes, it suddenly bugged and everytime I try to make a potion it jamm the apothecary interface and you wont be able to click anymore any ingredient.
Check the error screenshot, trying to make HP draughts with spumpetal.

![Babybird_000](https://user-images.githubusercontent.com/27322347/83340505-45aa8100-a2af-11ea-8b84-1223466337b9.jpg)

**Comment by cheapbuster** [comment]
Same issue- Using Apprentice's Glass Vial, Putrid Animal Humor, Cloudy Water, Primal Zoic Gore, Crumbly Squig Bits

**Comment by Grunolf** [comment]
Same here, happened using : 
Artisan's glass vial
Firebreath scale (200)
Taut Gobswort (200)
Majestic Goldweed (200) x2

Error: 3002249 RESULT_OK

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16992

**Comment by Kaelang** [comment]
Please re-open if this issue persists. Recent hot-fix should've fixed this.
