### ISSUE TITLE
Alchemy does not work

### ISSUE THREAD

**Issue by Librium1981** [WarEmu/WarBugs#16994]
In the manufacture Lasting Stanchion Unguent  no resource wasted Firebreath Scale
![Logras_003](https://user-images.githubusercontent.com/65770198/83342465-7f53aa00-a2f8-11ea-8ad3-8b5b5a999b11.jpg)

Logras

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16992
