### ISSUE TITLE
Trash mobs in Crypt keep respawning

### ISSUE THREAD

**Issue by Tamtam-RoR** [WarEmu/WarBugs#16996]
I've been in a crypt run on 31/05, several packs of trash mobs keep respawning endlessly after kill about every 20 seconds.
This occurred with spiders, skeletons, and devotes/fanatic.s

Rushing inside into the dungeon, and kill 2-3 packs at a time, stops the respawning.
However the last pack of devotes wont stay killed and makes the last boss difficult or impossible to start.

Steps to reproduce the problem: 
Run into the dungeon, i guess

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16995
