### ISSUE TITLE
[DOK] Focused Mind and Blood Offering (possibly WP)

### ISSUE THREAD

**Issue by bozzax** [WarEmu/WarBugs#1699]
I think it used to work on Blood Offering so you could quick fuel up on SE with FM

**Comment by ozarmidrashim** [comment]
Trackers, please don't assign this to me unless confirmation is provided.

**Comment by Evildoor** [comment]
Uh, i've not used this on live, but... Isn't Blood Offering a channeled ability? If yes - was FM affecting any channeled abilities at all? I think not.

**Comment by ozarmidrashim** [comment]
It is a channeled ability, hence why I'm convinced this is false.

**Comment by milosxe** [comment]
Yes, it doesn't make sense that it works on channeled abilities.

**Comment by Tyramissoux** [comment]
Definitely did not work on live.

**Comment by bozzax** [comment]
I remember it incorrectly then, sorry
