### ISSUE TITLE
BB/BE dungeons lockout bug

### ISSUE THREAD

**Issue by wildwindblows** [WarEmu/WarBugs#16990]
Hello,
I experienced this bug two times. While I was doing BE dungeons with a group, server crashed and gave automaticaly lockout. You can find the related screenshot below. Altough we killed last BE boss, it didn't count for quest (We completed BB dungeons first and killed the first BE boss and than server crashed when we was killing one of the small boss).
Thanks.
![Rezero_459](https://user-images.githubusercontent.com/45720515/83337975-6e8b4000-a2c8-11ea-81f3-2c27bba869bb.jpg)

**Comment by Kaelang** [comment]
Server crashes have been known to disrupt dungeon / PvE runs. At this time there is nothing that can be done.

Thanks.
