### ISSUE TITLE
Keep Lord's don't aggro

### ISSUE THREAD

**Issue by colintgallagher** [WarEmu/WarBugs#16998]
Today after bypassing the postern in Thickmuck Pit while the inner keep door was being rammed, we accidentally hit the lord but he didn't aggro. So we just ran in and started hitting him, still nothing. He also took no damage and it didn't build any morale. Once the door came down he started taking dammage but still did not aggro or fight back. He did build morale.
![Sarnai_023](https://user-images.githubusercontent.com/56422919/83346411-19f8bc80-a2ea-11ea-9a64-aad017bba56c.jpg)

**Comment by Kaelang** [comment]
Did you essentially kill the lord without him doing anything then?

**Comment by colintgallagher** [comment]
We waited to see if he would aggro once inner came down but still nothing. The rest of order came in and we killed him. Then there were several server crashes in a row, each time just a few minutes after Thunder Mountain would unlock, I stopped playing for the night at that point.

I also remember seeing a message in T4 chat about the Dragonwake lord being bugged as well but I wasn't there for that myself.

**Comment by SilverWF** [comment]
Same just happened in the T3 elves keep - lord just stayed at center and did nothing, while huge zerg hit him around
Including special stuff, like self cleanse

**Comment by krubs-oss** [comment]
Confirm it was bugged for BFP and Averlorn. Everything else aggros except the keep lord who just stands AFK

**Comment by velenne** [comment]
Order is about to hit the keep in Troll Country if you want to see this live.

**Comment by velenne** [comment]
![image](https://user-images.githubusercontent.com/65675974/83684871-590a6480-a5ad-11ea-8f5f-eeb1e85947af.png)
Taken just now in T2 Empire

**Comment by velenne** [comment]
One more thing: FWIW, I believe this started with the patch that kicked off the Mourkain Temple scenario event last weekend.  Or right around there.  

It's still happening, too, and has become a point of strategic advantage to defenders.

~Takindra (Order)

**Comment by velenne** [comment]
Butcher's Pass Fort Lord was acting normally (attacking, etc) just now.

**Comment by MaxHayman** [comment]
Went live with hotfix.
