### ISSUE TITLE
Can't use Apothecary ("Something went wrong when attempting to make this item...")

### ISSUE THREAD

**Issue by Hegestratos** [WarEmu/WarBugs#16991]
After getting my cultivating skill up to level 50, I tried utilizing the newly available materials to brew some potions (current apothecary skill level: 34).  Once I try to do so (using a Apprentice's glass vial, a Cloudy Water and a either one or two Fretting Marsh Roots), I get an error message that reads: 

"Something went wrong when attempting to make this item, please report to the bugtracker that this happened, what materials were used and that result would have been: 3000200 RESULT_OK".

After this I cannot use the apothecary skill window whatsoever. I can't even move ingredients to each corresponding box. If I relog, I can try again, but I get the same error message when trying to brew. This happens with every ingredient now, so I can't brew anything.

![error](https://user-images.githubusercontent.com/66185509/83340009-bcdd1680-a2a9-11ea-9d3e-ff4c664d202b.png)

**Comment by zhentil** [comment]
I have had the same issue but I with code 197911 Result_Ok 
I was using Black Serissa, Fabricated Artisan's Glass Vial with x3 Majestic Goldweed when this occurred

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16992
