### ISSUE TITLE
[Scenario, Talabec Dam] Cannot respawn.

### ISSUE THREAD

**Issue by TilliRage** [WarEmu/WarBugs#17001]
While carrying bomb fell into the lake and died before coming out of the water. Could not respawn and my character's body appeared alive even though HP bar being 0. Cannot move only turn the character. 

![Tilirage_010](https://user-images.githubusercontent.com/66213697/83356592-c9c43d80-a36f-11ea-87ce-5fb637e4c608.jpg)

![Tilirage_011](https://user-images.githubusercontent.com/66213697/83356595-ce88f180-a36f-11ea-8b22-4cf2e9cb9e8b.jpg)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/10682
