### ISSUE TITLE
Textures not loading

### ISSUE THREAD

**Issue by Txarlyman** [WarEmu/WarBugs#17003]
![Tzulagh_006](https://user-images.githubusercontent.com/59922493/83356886-4f90ba80-a369-11ea-9296-b2e47c27c72c.jpg)

I'm having a problem wile loading the client, it crashes me to character selection many times after i click play, and when i finally get in textures aren't loading, even i can atack through wall that should be there foe everyone but because they aren'tloaded for me i have line of sight.

Thanks for you're time.

**Expected behavior and actual behavior:**

textures of walls and buildings are not loading and dont breack line of sight

**Steps to reproduce the problem:**

Just clicking "play" on chare selection

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by dalen** [comment]
can you try clicking the repair button in the launcher? Seems like one of the 3d models might have gotten corrupted.

**Comment by Txarlyman** [comment]
seems that fixed the problem, thank you very much. Have a nice day.

**Comment by dalen** [comment]
great
