### ISSUE TITLE
Witch Elf Heart Seeker

### ISSUE THREAD

**Issue by starrrk** [WarEmu/WarBugs#1700]
![heart seeker](https://cloud.githubusercontent.com/assets/15193926/10575915/90748068-7614-11e5-81e2-d07f850df3e4.png)
Heart Seeker is doing less damage than its supposed to. I've tested against same gors and different mobs aswell, this is the tool tip damage heart seeker (512) damage and slice (415) damage. HS hits for 193 70 migitated critically hits for 385 142 migitated while slice hits for 312 100 migitated critically hits for 625 201 migitated.

**Comment by Narcoticx** [comment]
It's the same for Wh, please fix that aswell.

**Comment by noisestorm** [comment]
+
