### ISSUE TITLE
T4 Epic Quest - The Ebon Flame

### ISSUE THREAD

**Issue by SoleSolace** [WarEmu/WarBugs#17009]
**Expected behavior and actual behavior:**

Expected behavior - Quest completes normally. 

Actual behavior - I killed the last boss (Riannmar Jadeheart), used the orb of souls, and the quest popped up. When I went through the portal, the pop up for the quest was gone, and the quest had been removed from my tome.

**Steps to reproduce the problem:**

Have the quest open while stepping through the portal? I'm not quite sure that's what happened because I was still looking at the rewards when I was transported by the portal.

**Comment by Lheana** [comment]
Nothing will be done for what you experienced. To finish the quest, take the last step from the last quest giver of this Epic Quest.
