### ISSUE TITLE
Texture not loading 

### ISSUE THREAD

**Issue by Txarlyman** [WarEmu/WarBugs#17002]
![Tzulagh_006](https://user-images.githubusercontent.com/59922493/83356588-62a28b00-a367-11ea-8aa3-1088619d4f7e.jpg)

I have problems loading my client, i have to do it again and again untill eventually its logs, and sometimes textures are not loading properlly, even i can atack through "walls". I say "walls" because even they are not loaded for me they are for the rest and i can atack even i shouldnt because my wall is not loeaded. Can you help me out?

Thanks.

**Comment by Kaelang** [comment]
We aren't support. Use the Forums.
