### ISSUE TITLE
Poor Gustav 

### ISSUE THREAD

**Issue by Japzor** [WarEmu/WarBugs#17004]
Quest Poor Gustav
Step 1.  Slay the Warprot Kidnapper    DONE
Step. 2 Get Baby Gustav 0/1  Do not drop !!! 
Have now try to do this quest like 20 time, and still no Baby Gustav.... 
This really suck :(

**Comment by Kaelang** [comment]
Baby Gustav has been shown to be working as intended. Read your quest for suggestions and consider asking on the forums or in /5.
