### ISSUE TITLE
The Sunken Keep - T2 Ostland warcamp quest

### ISSUE THREAD

**Issue by Morwar** [WarEmu/WarBugs#17000]
"The Sunken Keep" quest can not be accomplished. The mark on the map is misplaced.

![Morloh_000](https://user-images.githubusercontent.com/10424820/83352719-87860680-a345-11ea-8900-1c1a84af2c4d.jpg)

Thanks!

Mor

**Comment by Kabucoror** [comment]
fixed with next patch
