### ISSUE TITLE
Disappeared Eternal seed

### ISSUE THREAD

**Issue by Wildcuttah** [WarEmu/WarBugs#17006]
Good day. I am so upset. I had the Eternal Golden Serissa Seed and it disappeared from my inventory after a disconnect. 
Have I any chances to return it?
https://imgur.com/VkmQIta
![Wildcuttah_053](https://user-images.githubusercontent.com/66223112/83362364-67803280-a399-11ea-8f43-70a0ce665870.jpg)

**Comment by Kaelang** [comment]
We don't do returns. Sorry. 

If you're able to help identify why the item would've been removed that could help.

**Comment by k0ut4l1** [comment]
****Note: I do not know if Wildcuttah had the same issue with me.

Lost a purple seed too under these circumstances: Bag was full when the seed was ready to get harvest. Made some room in my bags to be able to harvest but the option wasn't available (harvest button did nothing). After reloging the seed was gone.

https://youtu.be/k1vMklb23ds

**Comment by Kaelang** [comment]
Closing as with no additional information on how to replicate such issue we would not be able to identify the problem.

**Comment by XmatXergon** [comment]
Same thing happen to me today.

Purple seed disappeared during harvesting, while my main bag was full. So plant got harvested but didnt gave me seed into inventory, cuz it was full (there was no room).

I believe thats very easy to replicate, can try do it on testers, but would need to get purple seed there 1st...

**Comment by turki79** [comment]
same thing happen to me i lost my purple seed that give willpower and healing power
