### ISSUE TITLE
Terror Debuff stays after boss in BS

### ISSUE THREAD

**Issue by Sivine** [WarEmu/WarBugs#17016]
**Expected behavior and actual behavior:**
At the end of the boss, the "Terror" debuff should be removed
At the moment the debuff stays after the boss is killed
It get removed only when dead, or porting zone

**Steps to reproduce the problem:**
In BS it was on pretty much any boss in BS, kill the boss, debuff does not remove

**Testing Screenshots/Videos/Evidences (always needed):**
https://imgur.com/OM2stdE

**Comment by Kaelang** [comment]
Terror is in effect whilst inside the room, did Terror drop when you left?

**Comment by Sivine** [comment]
It did not.

**Comment by dalen** [comment]
This should be fixed in a hotfix since then
