### ISSUE TITLE
(Bug)"cannot be used to customize appearance"

### ISSUE THREAD

**Issue by Mypain666** [WarEmu/WarBugs#17014]
Good afternoon. Please tell me why I can’t change the appearance on my raincoat and helmet using my event items [Battle Brew Backpack] [Face of the Unborn] [Leather Face] [Face-Eater's Mask]? I tried to change the appearance to different cloaks and a helmet, but it says to me that "Battle Brew Backpack cannot be used to customize appearance" Other players have no such problem. 'alternative appearance available' is on all things to which I want to apply appearance.My nickname in the game Mypain

**Comment by Kaelang** [comment]
If other players are able to do this without problem, then it's not a bug with the game. Please direct your query to Advice and/or the forums.
