### ISSUE TITLE
Mounted Combat

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#17013]
after the latest patch, being in combat doesn't dismount you

**Comment by Xicoz** [comment]
actually nothing does, nothing will dismount you

**Comment by velenne** [comment]
Dying does not dismount you.  Traveling.  Fighting.  Swimming.  The mounts are loyal across dimensions.

**Comment by mythyrylfalcon** [comment]
Additionally this is causing issues with siege engine transport. Towed siege engines don't disengage if you remove the "mount" buff.
![image](https://user-images.githubusercontent.com/51804717/83600371-477c7a80-a523-11ea-885a-0436120f268b.png)

**Comment by Kaelang** [comment]
A fix has been deployed to live - please re-open if issue persists.
