### ISSUE TITLE
Vanquisher Taen not displaying on Swordmaster

### ISSUE THREAD

**Issue by detrap** [WarEmu/WarBugs#17010]
Doesn't display a helm when equipping the Vanq Taen, not sure if this also is the issue with the oppressor helm since they are of the same design.

**Comment by Lheana** [comment]
Tested and the helm is correctly displayed. Be sure you don't have the "Show Item" disabled.

**Comment by detrap** [comment]
Still unable to see the helm displayed unfortunately, and I have never seen any SM with the Vanq helm displayed. I'll ask guildies when they are online to check for me as well.

**Comment by Lheana** [comment]
Then provide a screenshot.

**Comment by detrap** [comment]
![Screenshot 2020-06-07 06 25 12](https://user-images.githubusercontent.com/64330047/83953930-fdc7c300-a887-11ea-9487-d880dcb2f4de.png)
