### ISSUE TITLE
Quest: A Host Divided (Destro) - Collection Spot Bugged, Can't Complete Quest

### ISSUE THREAD

**Issue by witc0m** [WarEmu/WarBugs#17011]
**Expected behavior and actual behavior:**
Quest is collected in the middle of the Sacellum. It asks the player to go to Norsca to find 4 shrines and report back. Three of the shrines are working properly (screen included of a working shrine), however, a fourth one--Nurgle's Touch shrine--is bugged. It shows the alter, but it's not the right alter. There's no NPC around it, and it does not allow you to right click it for quest credit. I confirmed I am in the right area of the map, and searched everywhere for another shrine, but no luck. This bugged shrine is supposed to be the right one.

**Steps to reproduce the problem:**
Find the Nurgle's Shrine asset and plug it in. Or link this shrine to be usable and allow it to finish the quest. Also rename the target to Nurgle's Shrine.

**Testing Screenshots/Videos/Evidences (always needed):**
![Knuckles_000](https://user-images.githubusercontent.com/66286733/83471068-b7223500-a451-11ea-81f2-3deee72e0c42.jpg)
![Knuckles_001](https://user-images.githubusercontent.com/66286733/83471071-b7bacb80-a451-11ea-9349-096f2ee4eea3.jpg)
![Knuckles_002](https://user-images.githubusercontent.com/66286733/83471072-b7bacb80-a451-11ea-9290-ccdb74a44422.jpg)
![Knuckles_003](https://user-images.githubusercontent.com/66286733/83471073-b7bacb80-a451-11ea-802a-6150f04c200c.jpg)
![Knuckles_004](https://user-images.githubusercontent.com/66286733/83471075-b7bacb80-a451-11ea-8c7d-b6af93221cc4.jpg)

**Comment by Lheana** [comment]
The right altar is in the quest marker, it's just not the one you have found.
