### ISSUE TITLE
inconsistant auto attack damage on witch elf

### ISSUE THREAD

**Issue by starrrk** [WarEmu/WarBugs#1701]
i run the same blades on both hands with the same talismans everything is the same. Usually my attacks will do 162 against practic target but randomly one or more do 104-106. They crit for 325 but randomly one or more crit for 165. I did the test on multiple subjects. 

![auto](https://cloud.githubusercontent.com/assets/15193926/10576002/16e73a32-7615-11e5-8a72-9bb6f58ff925.png)

**Comment by ozarmidrashim** [comment]
Offhand proc.
