### ISSUE TITLE
NO Keep Lords are attacking - In Any Tier, For Any Side

### ISSUE THREAD

**Issue by velenne** [WarEmu/WarBugs#17019]
**Expected behavior and actual behavior:**
Normally the keep lords will aggro enemy players.  That does not seem to be the case.  It's been the case for several days now that NO keep lords are attacking players.  They just stand there and get beat on.

The other mobs in the keep will still act normally.  

I'm not sure about Fortress lords, but City lords acted normally.

**Steps to reproduce the problem:**
Go punch an enemy fort lord in the face.  He'll just stand there and turn the other cheek...until he dies.

**Testing Screenshots/Videos/Evidences (always needed):**
From yesterday (nevermind the mounted combatants, that was a separate bug).  Keep Lords still weren't attacking as of this morning.
![image](https://user-images.githubusercontent.com/65675974/83683018-52c6b900-a5aa-11ea-9146-eb0d0fe34b52.png)

IGN: Takindra (order)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16998
