### ISSUE TITLE
Ugly Face Quest in High Pass Chapter 11 (incorrect spelling)

### ISSUE THREAD

**Issue by detrap** [WarEmu/WarBugs#17026]
Quest has incorrect spelling of the animal.

![Screenshot 2020-06-05 11 23 51](https://user-images.githubusercontent.com/64330047/83828926-1bc8e280-a725-11ea-9ade-7577b2ffbef2.png)
![Screenshot 2020-06-05 12 04 28](https://user-images.githubusercontent.com/64330047/83828932-1ec3d300-a725-11ea-8d3b-f285a618672b.png)
![Screenshot 2020-06-05 12 04 47](https://user-images.githubusercontent.com/64330047/83828935-208d9680-a725-11ea-9004-5d1984e45b69.png)

Area for Quest is 12k,52k

**Comment by Lheana** [comment]
Thanks for the report, it will be fixed with next patch.

**Comment by Kaelang** [comment]
This should have since been fixed.
