### ISSUE TITLE
Guild Bank Re-Locked

### ISSUE THREAD

**Issue by Manatikik** [WarEmu/WarBugs#17024]
Our Guild Vault #1 Relocked all the rows under gold costs again (with items locked behind them). Did not happen before server crash of 4/6/20 - though we bought the pages out literally years ago so a rollback isn't the issue.

![image](https://user-images.githubusercontent.com/19319894/83739137-6dcd1380-a612-11ea-9e94-78682c783dff.png)

**Comment by Teefz** [comment]
Can confirm this issue on destro side as well.

**Comment by cheapbuster** [comment]
Also, buying a new row takes the gold but doesn't unlock anything

**Comment by MaxHayman** [comment]
Don't repurcahse the row. A fix has been produced and will be deployed with the next update.

**Comment by MaxHayman** [comment]
Went live with hotfix.
