### ISSUE TITLE
Just lost the vault 1 guild bank raw.

### ISSUE THREAD

**Issue by Layinolias** [WarEmu/WarBugs#17025]
Hello, when i go on my guild bank, i can't reatch ours vault1 raw. i let you see the pb on screan shot.
We have allready buy all the row in all vault.

Thx you for your help :)
![vault](https://user-images.githubusercontent.com/14100625/83800506-d1ede700-a6a7-11ea-8575-0dc841de55af.PNG)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17024

**Comment by Layinolias** [comment]
Okay, thx :)
