### ISSUE TITLE
Beast Lord Helmet Invisible when equiped

### ISSUE THREAD

**Issue by Vizio101** [WarEmu/WarBugs#17028]
On my 40/47 Swordmaster I completed the Beastlord quest that awards the helm.  When I equipped it there was no appearance of the helm.  I double and triple checked the "show item" box and made sure it was selected.  Even tried turning it on and off several times and it did not work.  I logged off and even closed the game entirely and still the helm does not have an appearance.  I tried several helms I had in bank and they all had there appearances, just not the Beastlord.  Not sure if relevant but all of the other Beastlord gear appearances work, just not the helm.  Thank you.

**Comment by Nozzqt** [comment]
For note, this problem also appears on the Vanquisher helmet for Swordmaster.

**Comment by wargrimnir** [comment]
Beastlord Taen
Vanquisher Taen
Oppressor Taen

These had modelid 4454 assigned, since this didn't seem to be working I assigned new appearances.

**Comment by Kaelang** [comment]
This should have since been fixed.

**Comment by Kaelang** [comment]
Re-opening as issue has been reposted: https://github.com/WarEmu/WarBugs/issues/17186
