### ISSUE TITLE
Cant claim a keep

### ISSUE THREAD

**Issue by Tenaciousbufhel** [WarEmu/WarBugs#17035]
Our guild is lv14.  We tried claiming Caledor keep. No combat near by, permissions are all set, enough gold in the guild bank. Tried claiming in the group and solo as a council and as a member. Messed with permissions, at one point gave permissions to everyone. Same result     
![image](https://user-images.githubusercontent.com/65429915/83923941-5183c080-a751-11ea-9c11-1debd55db476.png)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16538
