### ISSUE TITLE
White Lion Tactic On 1rst Tree Pack Hunting Doesnt Reduce 50%

### ISSUE THREAD

**Issue by Polycarpos13** [WarEmu/WarBugs#17038]
**Expected behavior and actual behavior:**
Pack Hunting should decrease 1/2 or 50% auto attack speed but it doesnt.

**Steps to reproduce the problem:**
You can fix the value so it works right.

**Testing Screenshots/Videos/Evidences (always needed):**
![Doomgod_008](https://user-images.githubusercontent.com/66499660/83930541-d21ddd80-a7a0-11ea-9e1c-8dd600e047f0.jpg)
![Doomgod_009](https://user-images.githubusercontent.com/66499660/83930544-d34f0a80-a7a0-11ea-857b-11a51a735393.jpg)
![Doomgod_010](https://user-images.githubusercontent.com/66499660/83930545-d518ce00-a7a0-11ea-8951-e7491b4bdd94.jpg)
![Doomgod_011](https://user-images.githubusercontent.com/66499660/83930547-d6e29180-a7a0-11ea-9cd0-201aa380c497.jpg)

3.4 / 2 = 1.7 not 2.3, thanks in prior..

Some little code i just came up with:
while(Pack Hunting == 1){
auto_attack.speed = auto_attack.speed * (1/2);
auto_attack.speed = auto_attack.speed * auto_attack_haste.bonus;
}
else
{
auto_attack.speed = auto_attack.speed * auto_attack_haste.bonus;
}

**Comment by SilverWF** [comment]
Yes, noticed that too
But 2.3 + 50% is 3.4 :)
It's reversal math right here
And to convert 1.7 to 3.4 you should multiply it by 2, so add 100%, which is wrong.

**Comment by Polycarpos13** [comment]
I get what you are saying but since weapon initial speed is 3.4 shouldnt be 50% weapon speed increase 1.7?

**Comment by Polycarpos13** [comment]
If pack hunting increases your attack speed by 50% this mean this: 3.4 +1.7 = 5.1 which means every 5.1 seconds it deals heavy damage whilst keeping it at 3.4 every 3.4 it hits lower dmg because of the weapon dps. Since it decreases your attack speed it means that you must hit every 1.7 seconds and deal faster dps but lower dmg cuz it s faster, this opens up that you have more chances to do a crit and deal more dps since you hit faster. thanks.

**Comment by Pearlpetalbee** [comment]
I tested both using my WL and Engi with auto haste % addition. 
The Speed in User interface is actually the new speed after adding the auto haste speed. 
The smaller the number is the second used every hit. That is faster, higher dps. 
The mob I tested is killed faster after using the tactic with addition of said 50% auto haste.

My Engineer weapon speed is 2.4, adding gear 10% auto haste, the speed said 2.2, further adding auto haste jewels by 15% addition, the Speed in UI is shown 1.9.  

My WL speed is 3.4 without Pack Hunting tactic. 
The autoattack speed is 3.4 (manual count 4 sec of autoattack) per hit.
After using the Pack Hunting tactic, the autoattack speed is around 2.3 (manual count 2 sec of autoattack) per hit.
50% auto haste added, the new speed should be 1.7.
Speed said 2.3 is only 30% auto haste added.
It is needed to check further.

**Comment by dalen** [comment]
if it reduced it from 3.4 to 1.7, that would be a doubling of auto attacks, in other words +100% auto attack speed.

**Comment by Polycarpos13** [comment]
I still cant understand the code behind it though.. for it to work right, i need time to experiment, once i find smth i ll post

**Comment by Pearlpetalbee** [comment]
100% auto attack speed means you have zero sec for each attack. Then it is impossible for animation. Thus, there may be a basic value to add it up for the delay of animation.

**Comment by Kaelang** [comment]
100% attack speed doubles your current. I.E 2.0 to 1.0. It doesn't reduce it by 100% to flat, it doubles your current.

**Comment by Polycarpos13** [comment]
Ok i think the value 2.3 is correct if we set auto_attack.speed = 1.0 and we can set it like 1.0 because one can say that we deal damage per 1 second.
So it goes like this:

main() {

float auto_attack.speed = 1.0;

float wep_attack.speed = 3.4;

while(Pack Hunting == 1){

float auto_attack_haste.bonus = 0.5;

float total_auto_attack.speed = auto_attack.speed + auto_attack_haste.bonus; // 1 + 0.5 = 1.5 //

total_attack.speed = wep_attack.speed / total_auto_attack.speed; // 3.4 / 1.5 = 2.26 or 2.3 //

}

}

Either way i got really confused since without a weapon your Speed falls to 0.0...

**Comment by Pearlpetalbee** [comment]
So your code need to add condition wep_attack.speed = 0, in case no weapon. :)
