### ISSUE TITLE
divine salesman

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#17036]
this extremely strange vendor window just popped up for no apparent reason during the siege of caledor, offering items of rather god-like power, lol
![god](https://user-images.githubusercontent.com/16922842/83929184-69c40180-a78a-11ea-886f-2372ac7b05d8.png)

**Comment by SilverWF** [comment]
Looks like GM items.

**Comment by Kaelang** [comment]
Was you able to do anything with the popup?

**Comment by MightyPhred** [comment]
other than taking the screenshot and having a good chuckle i didnt try

**Comment by MightyPhred** [comment]
that item thats highlighted was priced at about 21k gold, so i couldnt have afforded it even if the shop was actually functional

**Comment by dalen** [comment]
that looks like network packet corruption

**Comment by MightyPhred** [comment]
that would explain a lot, it did happen after a moment of lag
