### ISSUE TITLE
Problem with guild bank

### ISSUE THREAD

**Issue by karrik1978** [WarEmu/WarBugs#17030]
Good afternoon! After yesterday’s problems with the server, the Guild Starcom discovered a problem with the guild bank. It manifested itself in the following: in the first vault, all purchased cells disappeared. But that's not all. All the things (oils) that were in these cells disappeared. Please deal with the problem and return all lost. We thank you for your attention.
Screenshot - https://pastenow.ru/97WG0

**Comment by MaxHayman** [comment]
#17024
