### ISSUE TITLE
Zone Lock/Contri Reward Bug

### ISSUE THREAD

**Issue by exxt1** [WarEmu/WarBugs#17049]
Hello,
Ill just cut to the case.
Today i was doing Praag, was in that zone overall for quite time, ran around 7 supplies, then went on siege where i was from start to the end, got stalwart contribution announce after killing lord.
Then i went to cap BO and War Report to Eataine which was under attack.
The problem is, just when i used the War Report TP, zone locked, i teleported to Eataine with SoR showing that Chaos Wastes started, but didnt get any notification whatsoever about winning map in Praag, or that next zone is available, nothing at all. (Not even talking about rewards)
If i wasnt in that map long enough nor did enough stuff to get at least that cow pie, i wouldnt be reporting this, but when things are like this, i really beg you to look into this matter and fix the War Report TP or whatever caused this thing to happen.

![Kayleena_049](https://user-images.githubusercontent.com/66543486/83960034-7d539300-a884-11ea-8bb9-866a07d58f26.jpg)
![Kayleena_050](https://user-images.githubusercontent.com/66543486/83960040-82184700-a884-11ea-8c6a-2f580dc8648b.jpg)

(Sorry, was screening it a bit later, thought id get rewards in post)

**Comment by Kaelang** [comment]
I appreciate that you're reporting the issue, but you say yourself you have no idea what caused it. "i really beg you to look into this matter and fix the War Report TP or whatever caused this thing to happen."

It's likely you received the reward message during the load screen - and your bags bugged out somewhat. I'll keep this open for 2 weeks to see if this happens again, and if so if you can provide more information, but for the time being there's not much that can be done with this report.
