### ISSUE TITLE
Warrior Priest Gunbad Madcap Tome Doesnt Generate RF

### ISSUE THREAD

**Issue by Polycarpos13** [WarEmu/WarBugs#17043]
Madcap Tome doesnt generate 8 Righteous Fury per second.

![Progenitus_006](https://user-images.githubusercontent.com/66499660/83946316-a1798a80-a818-11ea-8d73-4718a87a7695.jpg)
![Progenitus_007](https://user-images.githubusercontent.com/66499660/83946322-a50d1180-a818-11ea-9a23-0d0370010409.jpg)
![Progenitus_008](https://user-images.githubusercontent.com/66499660/83946326-ab9b8900-a818-11ea-8b26-150006a5f105.jpg)
![Progenitus_009](https://user-images.githubusercontent.com/66499660/83946330-afc7a680-a818-11ea-9748-d9bf1f1bcf4e.jpg)

I hit a rat so i dont have out of combat regen of RF and test with 2 books. First 2 showcase Madcap Tome and last 2 pictures showcase other book which gives 8 RF as well but works as intended.

**Comment by Kaelang** [comment]
Similar effects on DoK's, you need to unequip and requip the item.
