### ISSUE TITLE
[Kotbs] Aura On Your Guard!

### ISSUE THREAD

**Issue by Killham** [WarEmu/WarBugs#17045]
Bugged out, can give you 3x or even more reflected tick damage in one time from 1 target damage like from ability and 2 melee attacks.
![Komrad_001](https://user-images.githubusercontent.com/18173840/83952471-bb7b9300-a841-11ea-9bfc-dd9b453dd4ad.jpg)

**Comment by Kaelang** [comment]
You hit with multiple abilities, so you got reflect damage from each.

**Comment by Killham** [comment]
@Kaelang do you even know what you talking about? Aura have 2 sec inner cooldown, and cant hit you more frequently than that.

**Comment by Kaelang** [comment]
@Killham Might've been good to write that in the bug report initially then.

**Comment by Killham** [comment]
This appear yesterday on t2-t3 scence, and when i hit party with aoe ability under this kotbs aura i get like 6x+(2or1)xautoattack reflect, imagine how damage it is. Right now its probably ok dont saw this bug today on t4 atleast.

**Comment by Shiversdd** [comment]
![WAR-64_Ku9St0gtKe](https://user-images.githubusercontent.com/18085484/85135524-e48b2300-b246-11ea-8f81-9404ecbc51f0.jpg)
The same thing happened to me when I beat one kotbs

**Comment by Shiversdd** [comment]
I emphasize that I hit one target (kotbs)

**Comment by Symbelmyne** [comment]
Just fought 30+ rank ktbs, that aura behave exactly like fixed Riposte tactic, whenever you do dmg it proc back aura dmg, on every AA + skill. Potentially bugged assuming Bane Shield and Riposte were fixed.
Reproduce? Take ktbs and hit it with AA and skill and watch 3 aura proc in every second.

**Comment by Tooni709** [comment]
It's still bugged. You can get hit mutiple times in seconds. There is no 2 sec internal cooldown. Please fix it

**Comment by Carcharadon** [comment]
![WAR-64 2020-08-19 01-08-04](https://user-images.githubusercontent.com/55959616/90598600-f5a9cf00-e1b8-11ea-9e5a-5542481be847.png)
![WAR-64 2020-08-19 01-04-17](https://user-images.githubusercontent.com/55959616/90598607-f80c2900-e1b8-11ea-9db4-bb62a4c9b474.png)

Still bugged , lvl 16 KOTBS on my lvl 40/72 MSH  look at the time stamps that is  ridiculous  bane shield wasnt half as bad as this and the chosens "mirror" aura cant do anything close to this  reflects magic range one wile knights is ALL melee or anykind kinda bull

**Comment by Carcharadon** [comment]
Also On your guard assigns the damage made by the player hit NOT the knight  ( see fraziers is a Sword master yet he hit me with on your guard )     Discordant fluctuation  all damage is assigned to the chosen running it NOT the individual characters it is on . ONY need to be assigned to the Knight alone and the 2 sec cool down added .         CONFIRM!

**Comment by PandaOrc** [comment]
Still bugged. Aint even fun playing lower tier scenarios on a melee class when every KOTBS has this due cause it destroys melee characters...
