### ISSUE TITLE
Beastlord Cloak/Mantle

### ISSUE THREAD

**Issue by Chester3000** [WarEmu/WarBugs#17044]
Beastlord quest Eataine Chapter 16 - Caradhrel Lightspinner for Warrior Priest. 

When picking up reward, the Beastlord Mantle of the Stag and Beastlord Cloak of the Skaven show the identical stats (strength + weaponskill) with no information on bonus set pieces (no indication as to how to pick between the healer set and the dps set for Warrior Priest).

**Expected behavior and actual behavior:**
Ability to distinguish between both rewards for Warrior Priest (Healer Cloak vs DPS Mantle)

**Steps to reproduce the problem:**
Beastlord quest reward Eataine Chapter 16 - Caradhrel Lightspinner for Warrior Priest

**Testing Screenshots/Videos/Evidences (always needed):**
![Beastlord-WP-Mantle-of-the-](https://user-images.githubusercontent.com/66531682/83952342-86495380-a7f5-11ea-9c57-2d4c8d702f3b.jpg)

**Comment by Grock-r** [comment]
Aren't they supposed to be identical with only cosmetic difference?

**Comment by Chester3000** [comment]
I won't deny that is entirely possible. I'm a returning player and found it odd that this wouldn't be available as either a choice between a DPS or Healer set for Warrior Priest.

**Comment by SilverWF** [comment]
Both items are absolutely identical for all classes.

**Comment by wargrimnir** [comment]
There's only one set bonus for Beastlord, the different back pieces are for appearance preference only.
