### ISSUE TITLE
Tome of Knowledge: Armory

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#17047]
i bellieve this is commonly known but couldn't find on bugtracker anywhere, tome of knowledge armory is very buggy and doesn't display which items you've unlocked if the items are currently in the bank (if you don't have the full set unlocked anyways). here is an example of the Vanq set
![Reborn_009](https://user-images.githubusercontent.com/44329952/83955745-11d5db00-a81c-11ea-96be-28bf57a8648a.jpg)
![Reborn_010](https://user-images.githubusercontent.com/44329952/83955746-126e7180-a81c-11ea-9e12-4c00ae9b944b.jpg)

**Comment by Xicoz** [comment]
as well as the belt doesn't even show up as an option in the armory

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/15597
