### ISSUE TITLE
Issue with Guild Vault 1

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#17041]
Good afternoon, Kaelang asked me to raise a new report for this one.

Vault 4 is fixed, and is letting us buy a new row now at the correct price. Unfortunately, Vault 1 is broken for us though. All of the rows besides the first one have disappeared. We used this to store potions, liniments, and some low tier blue items for our guildies. I've disabled addons to see if it shows up again, but it doesn't. I can see that I can buy the rows back again, which I can do, but am hoping for maybe a fix so that all our items aren't lost? Thanks team

**Steps to reproduce the problem:**

I'm not sure!

**Testing Screenshots/Videos/Evidences (always needed):**

This is what I see now in Vault 1
![image](https://user-images.githubusercontent.com/22262165/83944819-5c485f00-a7fe-11ea-9fb5-d2af1ae0f3c4.png)

This is how Vault 4 appears (all good!)
![image](https://user-images.githubusercontent.com/22262165/83944832-6ec29880-a7fe-11ea-9f16-7afcd376d800.png)

**Comment by Kaelang** [comment]
Guild Vault 1 will need to be repurchased - however in a future update guilds that have been effected will have the gold costs reimbursed. This is a result of the latest fix deployed to the vault costs. 

I'll keep this up until the hotfix is announced reimbursing, but for those curious as if to wait, or re-purchase. You can re-purchase.

Your items should be there, just behind the pay wall.

**Comment by Senthoi** [comment]
Thank you, yes the items reappeared once the rows were purchased.

**Comment by Kaelang** [comment]
Closing this as legacy.
