### ISSUE TITLE
Guild Vault 1 all rows except 1 are gone (follow-up of 15848)

### ISSUE THREAD

**Issue by dbddhkpuka** [WarEmu/WarBugs#17042]
As already mentioned in https://github.com/WarEmu/WarBugs/issues/15848#issuecomment-639825499
Guild Vault 1 only shows one row where there used to be five before the last patch.

Tested today a few hours ago.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17041
