### ISSUE TITLE
GUNBAD

### ISSUE THREAD

**Issue by Japzor** [WarEmu/WarBugs#17051]
We was in the instance and took the right way. after we just down there was some troll that we pull. The i got 13587 Gold and the game. will say thanks for it, but got log out and when i log m in agen all the gold was gone :(
But there is a bugt there where u can get a lot of gold if you are lucky......
Hope that it can help you fix it.
Regards 
Japor

**Comment by Kaelang** [comment]
Struggling to work out what happened after you got the gold? You say 'and the game' but nothing else.

It sounds purely visual, this can happen from time to time, but would be good to take a look myself if you can let me know which NPC it was.

**Comment by Japzor** [comment]
After we enter Gundbad we tog the right way, we kill some mobs and jump down. There are som trolls not the big one but the are in grp, and we pull like 3 grp of them and then it happens. over wise i can take a screenshot next time iam in GB. if that helps ?
Regards
Japor

**Comment by Japzor** [comment]
After i got the gold the game lag, and i it log me out. so i log back on aand the gold was gone :( hehe
But there was a text in the chat thta say you got like 13k or 15k cant remember. but it was alot.

**Comment by Kaelang** [comment]
Sounds like you crashed and visuals got distorted. Please re-open if you're able to replicate the issue.
