### ISSUE TITLE
The /target command

### ISSUE THREAD

**Issue by satexas** [WarEmu/WarBugs#1705]
The "/target" command is broken.

In the past, you could type "/target <name>" to a friendly or foe.
This command not working impacts in-game macros and combo-uses.

Related: You can right-click a characters name in chat and choose "Target", so the in-game premise still works.

**Comment by Tiggonos** [comment]
it works for friendly but not for foe, so i guess its deactivated on purpose.

**Comment by Tyramissoux** [comment]
Not implemented yet.

**Comment by Luth-RoR** [comment]
Seems like deactivated on purpose.
