### ISSUE TITLE
Salvage literally doesn't work

### ISSUE THREAD

**Issue by Loganmcginley** [WarEmu/WarBugs#17059]
I learned the salvage skill and it literally doesn't work, I am almost level 20 and it just never works. Maybe you can give me gold because I unlearn it and learn it and it still doesn't work. It's a really frustrating bug I just want to make money but your broken game literally will not allow it.
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by SilverWF** [comment]
Learning and unlearning crafting skills is free
you should open your abilities tab, find, drag and drop salvaging skill (it looks like green... something) on your hotbar, then press it - cursor would've changed to hammer, then press it on item, that you want to salvage.

**Comment by Kaelang** [comment]
Salvaging is working, there's guide to Salvaging online.
