### ISSUE TITLE
Champ Challenge bug (another one :D)

### ISSUE THREAD

**Issue by magter3001** [WarEmu/WarBugs#1706]
If you champ challenge someone as a tank while having the root/knockback immunity, the target that you challenge will be rooted but you will not be. This lets the tank freely roam around after using ChampChallenge while his target stays in place for 10 seconds. Funny Karma imo but a bug that needs to be fixed. :P

**Comment by Evildoor** [comment]
#1167 
There is a ticket for this skill already. And your "new" bug is mentioned here, too.
