### ISSUE TITLE
Vanquisher 4 piece set bonus proc and tooltip value mismatch

### ISSUE THREAD

**Issue by axelpl85** [WarEmu/WarBugs#17064]
For choppa it seems Vanquisher 4 piece proc Vicious Strikes increases WS by 80, while tooltip says it should be 110 WS.

![Kardax_003](https://user-images.githubusercontent.com/26859175/84073420-0d065800-a9d1-11ea-987e-baf7563b836f.jpg)

**Comment by Kaelang** [comment]
Please use .getstats to check.

**Comment by axelpl85** [comment]
Thanks from fast reply. did what you said.
Paperdoll and buff tooltip seem to be different from getstat

prebuff
![Kardax_004](https://user-images.githubusercontent.com/26859175/84178030-143a6e00-aa84-11ea-9f7e-d9c4f6e0c9a5.jpg)

after proc
![Kardax_005](https://user-images.githubusercontent.com/26859175/84178121-37fdb400-aa84-11ea-939e-20c883fb74b6.jpg)

**Comment by Kaelang** [comment]
Already listed issue with the proc.
