### ISSUE TITLE
Action Point Drain

### ISSUE THREAD

**Issue by IC2Piggies** [WarEmu/WarBugs#17066]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by IC2Piggies** [comment]
I am playing my lvl 29 Engi and when I go into any sc's my Action Points are immediately gone,,,,POOF for the rest of the sc. Can't do anything. Can you please fix asap? 
Thanks Much!

**Comment by Kaelang** [comment]
Are you able to use any abilities?

**Comment by IC2Piggies** [comment]
No, once u go in u do  like 2 moves n then all of a sudden poof u have no AP for the rest of the sc. there were many ppl in numerous sc’s that had the same problem as me.
