### ISSUE TITLE
Excavator Shinsteels don't show

### ISSUE THREAD

**Issue by Jesden** [WarEmu/WarBugs#17069]
**Expected behavior and actual behavior:**
No model is equiped to the character when the named items are equiped, though stats are updated as appropriate.

**Steps to reproduce the problem:**
reloading ui, relogging, re-equipping.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/65976082/84156238-2bb42f80-aa61-11ea-956b-41c0ce5b049d.png)
![image](https://user-images.githubusercontent.com/65976082/84156267-340c6a80-aa61-11ea-8a56-67f9284bea55.png)

**Comment by SilverWF** [comment]
I liked naked legs so much...

**Comment by Kaelang** [comment]
This should have since been fixed.
