### ISSUE TITLE
Swordmaster warlord 8pc skill

### ISSUE THREAD

**Issue by odoc7625** [WarEmu/WarBugs#17061]
<!--
Issues swordmaster 8pc on warlord set skill is wrong

**Comment by odoc7625** [comment]
![Rainia_059 (2)_LI](https://user-images.githubusercontent.com/66634766/84052951-1a3a2d00-a966-11ea-99e9-763b0fc38f16.jpg)

**Comment by odoc7625** [comment]
order tank set

**Comment by Kaelang** [comment]
Please reopen and follow the format - also please open separate reports.
