### ISSUE TITLE
Archmage bloodlord 7pc bonus not on set/blank

### ISSUE THREAD

**Issue by odoc7625** [WarEmu/WarBugs#17062]
![Lagathaw_000 (2)](https://user-images.githubusercontent.com/66634766/84054410-376ffb00-a968-11ea-9ac5-b7a601da39de.jpg)

**Comment by wargrimnir** [comment]
This proc is assigned correctly, the tooltip is missing.

**Comment by wargrimnir** [comment]
Tooltip was fixed in a recent patch.
