### ISSUE TITLE
Halls of Aenarion quest not spawning mobs for quest item.

### ISSUE THREAD

**Issue by Viceblazed** [WarEmu/WarBugs#17072]
**Expected behavior and actual behavior:**

-Expected: Open the 4 tomes, see Aenarion Eidolon, kill and loot essence for quest.
-Actual: Open the 4 tomes, nothing spawns, can't complete quest.

**Steps to reproduce the problem:**

-Pick up the quest "Halls of Aenarion".

**Testing Screenshots/Videos/Evidences (always needed):**

![hallsbug](https://user-images.githubusercontent.com/66689296/84172481-11bb2280-aa4a-11ea-8ee7-e4ddc087d66d.png)

**Comment by Lheana** [comment]
Aenarion Eidolon is spawned near one of the tomes

**Comment by Viceblazed** [comment]
I have reopened all 4 tomes multiple times with no spawns occuring.

**Comment by Lheana** [comment]
He does not spawn from the tomes for now.

**Comment by Viceblazed** [comment]
So the quest is currently unable to be completed?

**Comment by Lheana** [comment]
Read my first comment. This is my last answer, the Bugtracker is for issues, it's not a support.
