### ISSUE TITLE
swordmaster warlord 8pc 

### ISSUE THREAD

**Issue by odoc7625** [WarEmu/WarBugs#17071]
![Rainia_059 (2)_LI](https://user-images.githubusercontent.com/66634766/84163856-c80d1080-aa26-11ea-9389-b0a14bb5c282.jpg)

**Comment by Kaelang** [comment]
I closed your previous report because there was hardly any information, I also asked you to follow the format.

What exactly are you trying to show me here? The BT is so you can identify and inform of us bugs, not force us to play guessing games and work out what you're trying to tell us.

**Comment by odoc7625** [comment]
swordmaster has 8pc skill vaul guidance,other tank sets have desolation,swordmaster set is wrong,should have morale debuff also

**Comment by Kaelang** [comment]
Please move this to feedback on the forums.
