### ISSUE TITLE
restore essence / lingering restore essence [dok]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#1708]
the heal over time eff should happen once every 1 sec, atm the tick happen at 2/ 0 sec.

don't know if on wp happen the same.

**Comment by ozarmidrashim** [comment]
This /really/ doesn't matter.

**Comment by Tesq** [comment]
well if you never get any single one of your tick cos every time you use the heal the lingering eff refresh ... it matter..... and since you have to wait 3 sec with out being able to not st heal adn that is your main heal.

**Comment by ozarmidrashim** [comment]
People actually use the 55 AP / RF / SE heal?

Wow, WP and DoK must be a lot better off than I imagined.

**Comment by Tesq** [comment]
I used it until this moment....not to bias but we use both, the ap heal have a 5 sec coldown, and when all hot are active, you cleanse and your target still go down and then you loose heals due the fact how the lingering work.
It also matter cos the aoe heal have 1 sec cast and to heal st you need lingering tick to work fine.
As if they tick every 1 sec you can refresh it and the lingerig will still  heal.
It also matter due the crit chance x tick which dok/wp are based on.

**Comment by noisestorm** [comment]
+
