### ISSUE TITLE
winds of change affecting scenarios

### ISSUE THREAD

**Issue by archmagebugreport** [WarEmu/WarBugs#17085]
**Expected behavior and actual behavior:**

Accepted a tor anroc scenario, winds of change affected me and i ended up in capital city with quitter debuff. (not the first time this has happened to me)
![winds of change](https://user-images.githubusercontent.com/64746720/84298233-a03faa80-ab03-11ea-9c41-6b841a2049c6.jpg)

**Steps to reproduce the problem:**

hmmm not sure since winds of change is random spawn.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by MaxHayman** [comment]
@Kaelang Potentially fixed
