### ISSUE TITLE
Event celebration bug

### ISSUE THREAD

**Issue by Zarh01** [WarEmu/WarBugs#17098]
Live Envents Celebration  Kill the Snot doesnt get credit in ToK but the quest : the Beat the living Snot quest got the credit by killing the Snot.

![Ladyvox_060](https://user-images.githubusercontent.com/48692217/84415788-9016f080-ac13-11ea-9969-58ceb218e7cd.jpg)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17093
