### ISSUE TITLE
Fortress Cleaver(Chosen) weapon is missing the model.

### ISSUE THREAD

**Issue by Mornmagor** [WarEmu/WarBugs#17099]
**Expected behavior and actual behavior:**

The Fortress Cleaver should be visible in your hand when you equip it. Instead, it is invisible, like it is missing the model/graphic. 

It still is accounted for stats and you can use it normally to attack.

**Steps to reproduce the problem:**

Buy the Fortress Cleaver from the invader vendor in IC. Equip it and notice the missing appearance.

**Testing Screenshots/Videos/Evidences (always needed):**
![Mornmagor_000](https://user-images.githubusercontent.com/66797164/84423664-7a132b00-ac27-11ea-9378-a84365a78a1b.jpg)

**Comment by Lheana** [comment]
Works fine for me. Maybe you need to update your launcher.
