### ISSUE TITLE
Beat the Living Snot

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#17093]
getting kill credit for the living snot is impossible, killed 5+ times, even got the killing blow a couple times, and once with only my grp killing it. see chat channel to see the killing blow.
![Nooblit_085](https://user-images.githubusercontent.com/44329952/84337509-55ec1700-ab5f-11ea-8bbb-c899260d5fee.jpg)

**Comment by Kaelang** [comment]
It’s not impossible - however there is a potential fix in the works to make this easier.

**Comment by SilverWF** [comment]
Sadly, kill credit goes to the only party, that dealt the most damage on boss.
At least, it seems like that.

**Comment by Nerialis** [comment]
I have killed Snot and got update for quest but not pop in event tracker.

![image](https://user-images.githubusercontent.com/65090605/84368335-b74ecd00-abd5-11ea-94a8-67b2bd216c37.png)

**Comment by cheapbuster** [comment]
Same here 
![image](https://user-images.githubusercontent.com/66186711/84382373-6c878200-abe2-11ea-82d8-9a3fe690ed58.png)

**Comment by Lerilla** [comment]
same here
![Lerilla_234](https://user-images.githubusercontent.com/16804997/84397620-2391f680-abff-11ea-87cd-db3fac652890.jpg)

**Comment by Fuamatu** [comment]
Same Issue applies to kill credit on player pets - not getting credit for kills

**Comment by Kaelang** [comment]
As mentioned in the second post on here - a potential tweak is in the works.

**Comment by cheapbuster** [comment]
Will players with 10/10 quest retroactively have the Kill living snot task checks or do we have to do it all over again?

**Comment by cheapbuster** [comment]
Same problem still 
![image](https://user-images.githubusercontent.com/66186711/84487041-1b38ca80-ac96-11ea-99f5-7a5d349bef03.png)

**Comment by Nerialis** [comment]
Did the quest for second time, event still not completed. MADNESS ... :)

![image](https://user-images.githubusercontent.com/65090605/84511208-7b476500-acc6-11ea-8f2b-7b91dbbdffc1.png)

**Comment by Xicoz** [comment]
seems "getting credit for the kill" will fill 1 of 3 random different options, Event Unlock for "Kill 'The Living Snot", Event Quest Unlock "Kill The Living Snot", or get a ToK unlock for killing a "Great Unclean One"

**Comment by Kaelang** [comment]
An additional fix has been pushed for this. Please provide feedback.

**Comment by Kaelang** [comment]
Feedback ingame and discord suggests this is now working. Closed.

**Comment by cheapbuster** [comment]
I love all of you 
![image](https://user-images.githubusercontent.com/66186711/84583717-96fc5980-adf3-11ea-94bb-37ae22e5e874.png)
