### ISSUE TITLE
Zealot Mastery Ability Bug(since downtime)

### ISSUE THREAD

**Issue by Myrdothilore** [WarEmu/WarBugs#1709]
The mastery ability Ritual of Innervation doesn't work since the downtime. When I cast it from my zealot nothing happens, but the ability still goes in cooldown.

**Comment by Evildoor** [comment]
Are you testing it in IC?

**Comment by Myrdothilore** [comment]
yeah is that why it doesn't work?

**Comment by Evildoor** [comment]
Yes. IC has Z-axis issues, one of the consequences is problem with ground targeted abilities like Rituals. Tested it on my Zealot in Ellyrion, works fine. There is a ticket about IC already, so i'm closing this.

**Comment by Myrdothilore** [comment]
ok yeah It works outside IC, sorry and thanks.
