### ISSUE TITLE
Officer Coin items pricing

### ISSUE THREAD

**Issue by Broodling12** [WarEmu/WarBugs#17090]
**Expected behavior and actual behavior:**
the pricing on the 200 Crafting bottle and 200 talisman box are very different from two different vendors.  At Erwin Kruger (near town square) the 200 bottle is 100 officer coins, and the talisman box is 400 officer coins... But if you go to Al Azrae (officer coin vendor) the 200 bottle is listed at 10 officer coins and the 200 talisman box is listed at 40 officer coins.

**Steps to reproduce the problem:**

Open each vender

**Testing Screenshots/Videos/Evidences (always needed):**

![Broodling_001](https://user-images.githubusercontent.com/56246378/84334890-b889e680-ab50-11ea-8192-21ef377c2a9e.jpg)
![Broodling_002](https://user-images.githubusercontent.com/56246378/84334892-b9bb1380-ab50-11ea-961f-346e07f3275b.jpg)

**Comment by Kaelang** [comment]
Thank you for the report - I’ve removed this for the time being whilst a fix is deployed.
