### ISSUE TITLE
Vengeance of Nagarythe

### ISSUE THREAD

**Issue by Griffithfalcon** [WarEmu/WarBugs#17105]
**Expected behavior and actual behavior:**
- Must be being used in while moving, but after patch it can be used only while standing still.

**Steps to reproduce the problem:**
1. Make sw, run and try to use VoN (it doesnt)
2. Stay still and it can be used.

Note that game critical and game breaking bugs may award a manticore/griffon (realm specific) at the leads discretion however, asking for one instantly disqualifies you from this reward.
-->
8\10 critical, like its  really annoying in pvp.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17079
