### ISSUE TITLE
A few bugs :)) bring out the spray!

### ISSUE THREAD

**Issue by Drajika** [WarEmu/WarBugs#17107]
Been back since a few years break :D 

bug 1: playing as an engineer and the new twisted tower was fun! :D no pies cuz bug? but the bug i wanna tell u about now is in fight and just as the tower explodes i get 30k dmg done ! as in i did the explotion :D funny but i dont know if this is exploting the reknown/exp for doing this large dmgs in the explotions fire i clearly see a dmg tick of 30k dmg .

bug 2 : Destro madnessquest the walljumping in reikfortress to be able to ring the bell. its in the southeastern part of the river ppl walljump to get to altdorf for Bell. guessing it was ment to make ppl do fort and then city to be able to do that. 

bug 3 had some logg in bugs as i logg in on my Blackorc. the castle colours is switched and it happened i rann into orders to learn the hard way (Edge of an axe) that this fort was not destros . haha . well thats all :D i guess u know about the pie spawn trouble in twisted :D <3 thanks for keeping this awsome game alive <3

**Comment by Kaelang** [comment]
Please separate bugs into individual reports.

**Comment by Drajika** [comment]
@Kaelang Got 2 pictures of the Twisted tower explotion dmg 30k adds to my own dmg as a engineer got a picture of the number coming upp on screen in yellow and added to my dmg done in the stat list

**Comment by Drajika** [comment]
![Bug dmg scoreboard](https://user-images.githubusercontent.com/66838725/84526227-41ce2400-acdd-11ea-8267-8cd9ba0b52f4.png)
![bug dmg](https://user-images.githubusercontent.com/66838725/84526235-4692d800-acdd-11ea-8562-72cbdf38afa3.png)

2 pictures of when the 30k dmg happening. and scoreboard.

**Comment by Kaelang** [comment]
Closing this as you've opened a second report for this one.
