### ISSUE TITLE
Zealot CTD ability

### ISSUE THREAD

**Issue by Myrdothilore** [WarEmu/WarBugs#1710]
Was defending fang in MoM, when order kicked the door down and we were defending at the lord I cast Ritual of Innervation and I CTD instantly, it also CTD others in the wb who were in TS with me. 
Also when I got ingame I asked in advice if anyone else CTD and a handful of people said they did.

**Comment by Myrdothilore** [comment]
CTD twice in a row now while healing everyone at keep defence. Starting to think it's pretty fishy that I CTD while healing and when I come back in the keep is taken.

**Comment by Myrdothilore** [comment]
CTD again, and most the WB aswell defending shadowlands keep.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
