### ISSUE TITLE
Twisting Towers - Tentacle Pies

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#17101]
Tentacle Pies still aren't spawning in most SCs, I would be very surprised if anyone on the server has done this part of the SC yet, even if they did 30+ scenarios, I have only seen them spawn once, and drop from a player kill once. Unless it is intended to only spawn once out of every 15 SCs something is wrong, most people don't even know what to look for for this event.

**Comment by Xicoz** [comment]
I also found someone how has gotten up to 30 pie throws, but saying that he hasn't seen them spawn in recent SCs

**Comment by Rydiak** [comment]
Pies are definitely spawning as pickup items in the Twisted Tower SC. Could probably close this ticket.
