### ISSUE TITLE
Black ork dark elf shield

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#17103]
Black ork using a dark elf shield skin 

![Nooblit_098](https://user-images.githubusercontent.com/44329952/84447578-f8fb6a00-ac0d-11ea-922c-2415a7f5b87f.jpg)
![Nooblit_101](https://user-images.githubusercontent.com/44329952/84447198-082de800-ac0d-11ea-90b5-5db3246ddebb.jpg)

**Comment by Lheana** [comment]
I don't know how this player equipped this item, but it is correctly restricted to Blackguards
