### ISSUE TITLE
Tormented Harpy

### ISSUE THREAD

**Issue by luxferre51** [WarEmu/WarBugs#17109]
Hello ,
After have killed more than 25 tormented harpies, Always no loot the items for change against "Wind of change. 
I have 3 items on 4 on my WE, call "Baiser".

**Comment by Lheana** [comment]
I don't understand if this report is related to a quest, a ToK unlock or something else?
Please give details and screenshots, or the ticket will be closed.

**Comment by luxferre51** [comment]
not understand kaeland answer, same after google translate

**Comment by Lheana** [comment]
You're french?

**Comment by luxferre51** [comment]
oui

**Comment by Lheana** [comment]
Contacte-moi sur Discord ou sur le forum.

**Comment by luxferre51** [comment]
ok, je teste sur le forum

**Comment by luxferre51** [comment]
c'est envoyé sur le forum en mp
