### ISSUE TITLE
Live Event - WL/Engi Pet Kills

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#17100]
i believe this mechanic is the same as the snotling mechanic, i have killed infinite WL pets/engi pets (going out of my way to kill engi turrets/WL pets in warband fights), but currently i only have credit for 2 of each.

**Comment by Vayra** [comment]
For some reason it only counts your killing blows on the pets.

**Comment by MaxHayman** [comment]
This should be fixed. Please reopen if not.
