### ISSUE TITLE
Twisting Tower - Losing Points

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#17113]
If your team is holding both objectives, your team actually loses points, rapidly, if this is intended I apologize, my team went from 350 to around 200 very quickly.
![Nooblit_112](https://user-images.githubusercontent.com/44329952/84561355-4d3b4280-ad11-11ea-89d2-bcf6aeb50c13.jpg)
![Nooblit_113](https://user-images.githubusercontent.com/44329952/84561365-54fae700-ad11-11ea-98a2-2dcf35ce681b.jpg)

**Comment by Kaelang** [comment]
This is intended.
