### ISSUE TITLE
Madness reigns Tobias not spawning

### ISSUE THREAD

**Issue by mforeman15** [WarEmu/WarBugs#17117]
After killing hero, Tobias not spawning. Went through 3 times

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Need more information.

**Comment by AndrewSquared** [comment]
Tobias is no longer present at Gotland Advance in Norsca after completing the step previous in Madness Reigns quest line (killing abomination at PQ).

**Comment by Kaelang** [comment]
Thanks - we're aware. This should be fixed on the next boot.
