### ISSUE TITLE
Squig herder extending range tactic, stoped working after shadow warriors changes in the clone version

### ISSUE THREAD

**Issue by Torete-war** [WarEmu/WarBugs#17110]
With the new Shadow warrior changes, seems there has been some crossrealming issues causing the Squig herder extend range "Shooting wif da wind" stop working.

The tactic should be extending quick shooting range abilities a 50%, but right now is extending range a 0%, even the tooltip say the tactic extend range 0%.

Go npc and check it, buy tactic, equip tactic and the quick shooting abilities remain at 65 feets range instead of 98 feet, that it should be when equiped.

https://postimg.cc/gallery/LqjsJq6

**Comment by dalen** [comment]
This was fixed in a hotfix

**Comment by Zomega-WAR** [comment]
FYI this is still bugged. Tested today, with and without tactic the abilities remain at 65ft.
