### ISSUE TITLE
Nametags visible through walls by changing settings

### ISSUE THREAD

**Issue by Draahl** [WarEmu/WarBugs#17112]
Setting the following options caused nametags to become visible through fortress walls. Fixed itself after DC.

![WAR-64 2020-06-13 00-17-59](https://user-images.githubusercontent.com/66851481/84551925-6cd16b80-ad0f-11ea-91e7-e86b087ec70f.png)

**Comment by Kaelang** [comment]
I have a copy of the settings, dropped in dev chat for reference - taken off here.
