### ISSUE TITLE
Mobs not dying in multiple zones, throws NullReferenceException Error

### ISSUE THREAD

**Issue by ipnoom** [WarEmu/WarBugs#17116]
While questing and doing public quests in both troll lands and Black Fire Pass, I am encountering an error where mobs will appear to hit 0 hit points, but they will not die.  They then chase you until you can create enough separation for them to stop chasing.  They will not  leash back to there starting point and will stay at that point.  

When this occurs, my squig is despawned, with the errror, "NullReferenceException  was thrown from HandleEvent.  This object will be destroyed"

once the mob despawned as well as the squig

**Comment by Kaelang** [comment]
Can you give some NPC names / locations?

**Comment by ipnoom** [comment]
Thardrik Hammer that is located in the zone of the Thardrik Smashin PQ, doing it now to see if I can get the effect multiple times, it is random

**Comment by Kaelang** [comment]
If you can get a recording, that'll help.

**Comment by ipnoom** [comment]
I am not sure how to do that

**Comment by Kaelang** [comment]
Screenshots then please.

**Comment by ipnoom** [comment]
![Oddzlo_000](https://user-images.githubusercontent.com/23665426/84570618-796fb700-ad43-11ea-9cf0-b0c5248c9976.jpg)

**Comment by Kaelang** [comment]
You killed the NPC though, right? That's coming from 'Stout' and not the NPC?

**Comment by ipnoom** [comment]
In this case, the squig stayed but the mob disappeared, the next set I pulled, the squig was destroyed and the mob is just sitting in the road
![Oddzlo_001](https://user-images.githubusercontent.com/23665426/84570649-aa4fec00-ad43-11ea-93f1-c7bf9808d62c.jpg)

**Comment by ipnoom** [comment]
Seems that these bugs only occur when I have a pet squig summoned.  Killed about 20 mobs without error while not having a squig, but was getting an issue about every 4th "kill" with a squig pet summoned

**Comment by ipnoom** [comment]
The error seems to occur when the squig gets the killing blow.

**Comment by ipnoom** [comment]
Ok, here is a screenshot that shows 5 mobs that are bugged, 4 close up and the one in the distance is also bugged.  I can guarantee that the bug will occur if I get the squig pet to do the kill.  This is at the Thardrik Smashin' PQ in Black Fire Pass at 7:15AM pacific time.
![Oddzlo_004](https://user-images.githubusercontent.com/23665426/84571056-dc624d80-ad45-11ea-834b-589343419f43.jpg)

**Comment by Lheana** [comment]
I tested it, it seems fixed. Please comment if it happens again.
