### ISSUE TITLE
Madness Reigns quest to ring the bell outside IC is inaccessible

### ISSUE THREAD

**Issue by detrap** [WarEmu/WarBugs#17115]
Fort is owned and controlled by order but all the doors are closed with destro guards.

![Screenshot 2020-06-13 20 48 46](https://user-images.githubusercontent.com/64330047/84566819-8f1ec400-adb7-11ea-8f65-23132d788920.png)
![Screenshot 2020-06-13 20 48 30](https://user-images.githubusercontent.com/64330047/84566822-90e88780-adb7-11ea-9bae-c4c593dd3815.png)

**Comment by Kaelang** [comment]
Struggling to figure out where you are here - I don't see any guard guarding the Fortress door to IC.

**Comment by detrap** [comment]
Sorry, am outside the Maw entrance

**Comment by detrap** [comment]
City is available now quest will be doable
