### ISSUE TITLE
Unable to purchase Invader Weapons

### ISSUE THREAD

**Issue by Runninronin** [WarEmu/WarBugs#17121]
**Purchasing New Invader Weapon and unable to purchase and am reported to not have enough money.**

**/rel relogged into character, verified times and ToK unlocks.  Still reported not enough money.**

**Testing Screenshots/Videos/Evidences (always needed):**
![bugreport](https://user-images.githubusercontent.com/55218361/84583247-140bdc80-adbc-11ea-8157-919be70c5b32.jpg)

**Comment by sioding** [comment]
put the subjugator staff into your bagpack - don't wear it and it should work

**Comment by Kaelang** [comment]
You also don’t have enough money. 

See patch notes. 

(Were aware of the currency cap confusing players into thinking there’s no gold requirement to buy these items)
