### ISSUE TITLE
Twisting Tower xp is quite high and across the board

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#17122]
**Expected behavior and actual behavior:**
actual
XP after Twisting tower seems off.
expected 
normal values

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**
![TT](https://user-images.githubusercontent.com/7898608/84583742-f2f1be80-adb0-11ea-8a07-fcc337a05e81.jpg)

**Comment by Kaelang** [comment]
The XP / Renown in TT is working as intended.

**Comment by gittoaster** [comment]
That's not normal.  Please reopen.

**Comment by Kaelang** [comment]
You get enhanced XP reward at level 40 - there is also a 50% buff in the scenario.
