### ISSUE TITLE
Missing Influence in Dwarf T2

### ISSUE THREAD

**Issue by Telenfynddar** [WarEmu/WarBugs#1712]
My "new-to-t2"-chars can get influence in Dwarf-T2, but its not in the tome or at the rally master. None of the Equip is available there. Its my Engineer and my Runepriest.

**Comment by Reggaewaldo** [comment]
If you walk to the destro warcamp you Will unlock the inf rewards as a temp fix.

The unlock areas need to be switched.

**Comment by Telenfynddar** [comment]
Yeah, Problem solved. Never got that near to the wc ^^

**Comment by Mazic92** [comment]
I have the same problem, will try the tempfix tonight!
