### ISSUE TITLE
BB / BE after completion there is no influence.

### ISSUE THREAD

**Issue by Haciserdar** [WarEmu/WarBugs#17124]
Hello. Yesterday I complete both BE and BB got loot and even I got my talisman but I cannot get influence or see rewards on Influence NPC. I cannot see the influence in Tome of Knowledge too. What should I do?

![Haciserdar_001](https://user-images.githubusercontent.com/66898873/84591441-0f403a80-ae47-11ea-9dce-397a04d1980b.jpg)

**Comment by Kaelang** [comment]
Looks like a corrupt file in your download. Use Game Support / Technical Support - this isn't a flaw with the game.
