### ISSUE TITLE
Engie dots damaging keep door

### ISSUE THREAD

**Issue by Sivine** [WarEmu/WarBugs#17126]
**Expected behavior and actual behavior:**
Only ram should damage the door, here we had lots of engie dots damaging the door, it was dropping like nothing before.
It was the inner of Covnant of Flame in DW

**Steps to reproduce the problem:**
See above

**Testing Screenshots/Videos/Evidences (always needed):**
![dotengie](https://user-images.githubusercontent.com/62861645/84597445-5db00200-ae64-11ea-9eda-44fbda82b0cc.png)

**Comment by crazyturkme** [comment]
working as intended. buff order more pls

**Comment by Kaelang** [comment]
Thanks - I'm going to remove this to limit the spread of the information. Devs informed and confirmed on test server.
