### ISSUE TITLE
White Lion Invader Steelhelm Improper Stats

### ISSUE THREAD

**Issue by LucusAurelius** [WarEmu/WarBugs#17134]
The White Lion Invader Steelhelm is currently granting +3 Intelligence rather than than intended +3% Armor Penetration.

![image](https://user-images.githubusercontent.com/65376611/84656502-6c380100-aed8-11ea-9846-203f98a3045d.png)

![image](https://user-images.githubusercontent.com/65376611/84656607-8f62b080-aed8-11ea-928d-1fca7725e1d2.png)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/14970
