### ISSUE TITLE
Confusing Movements Morale Not Working As Intended

### ISSUE THREAD

**Issue by MaraIsTooNerfed** [WarEmu/WarBugs#17132]
While running into a SW, I managed to get enough morale to use M1 - Confusing Movements.
While doing so, I was still getting hit with both melee and ranged, although I was facing the SW, even more, being a bit behind him - so getting kited.
You can find the moment I used it, it starts with the first 2 parried attacks. Morale lasts for 7 seconds, but it seems it gets bypassed by both melee and ranged.
![Confusing movements](https://user-images.githubusercontent.com/66925719/84606473-c91ac380-aea6-11ea-8f34-769d236d73f2.jpg)

Further more, I would like you to check the numbers. Hitting me so hard even if I'm 2 sov and rest invader, with 2500 armor.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/13436
