### ISSUE TITLE
Ironbreaker knockdown issue scens

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#1713]
The Ironbreaker knockdown (don't know the name of the ability) is a real pain in scens. And the IB all know it, they go straight for casters in scens. The ability knocks you down for the rest of the scen. Only instant casts/dots work, cast longer than 1 sec don't work because you will be knocked down again. 

Only thing that will break the permanent knockdown is getting killed or suicide on npc. Hope this gets fixed soon.

**Comment by Evildoor** [comment]
Uh, are you sure about it? I've been knocked down by IBs many times, and noticed no problems besides occasional visual bug when character appears lying on the ground for the rest of the SC.
Anyone else can confirm this?

**Comment by wiscel** [comment]
It's not only visible bug. The lying down only stops when you do an instant cast. If you try to do 3 sec cast, within 1 second you're lying on your back again. I have some prn scrns of me and another guildie both lying down. Wished I had Fraps so I could upload a movie.

**Comment by Evildoor** [comment]
I do believe that your character is lying down - i've seen it myself many times. What i'm doubting is that it prevents you from casting, or interrupts your cast, or whatever. I've done at least 2 scenarios on my Zealot with this bug, and i can't remember having any problems healing my team. While it is possible that by circumstances i've never used long casts on these scenarios, ii'm not sure if i did or i did not.

**Comment by wiscel** [comment]
OK, I play Sorcerer. The other guildie it happened to was also a Sorc. Maybe it's not for all casters but Sorcs only?

**Comment by Myrdothilore** [comment]
I can confirm this has happened to myself and my friend in sc's and rvr, after the initial knockdown, our abilities will bug out, and we can't even use instant cast. It has a mind of its own, sometime it only last for a few minutes, other times it last the full sc. I was playing a SH, and Zealot when it has happened to me, my friend a SH, magus, chosen and sorc.

**Comment by Tesq** [comment]
do also to that when channeling?, cos on my dok i was able to use channeling with no problem, maybe is due the fact that i always right clikc my camera around and soe the animation always show as not KDed.

**Comment by Evildoor** [comment]
Run into this problem again, and still it is only visual for me. My Zealot got Cave Win-ed, for the rest of the sc she is lying down. When i press mass heal or something else, she stands up, casts it properly, and lies down again.

**Comment by Evildoor** [comment]
Still no confirmation on this bug being non-visual. And visual part should be fixed per #2717.
