### ISSUE TITLE
Magus Firewyrm of Tzeentch Morale 4

### ISSUE THREAD

**Issue by Warpmancer** [WarEmu/WarBugs#17135]
Magus' Daemonology Morale 4 ability, Firewyrm of Tzeentch, is not working. There was a thread about this a year ago when it was apparently fixed but it's broken again. Cannot provide screenshot because of the nature of the bug:

When pressing the button to use the ability, nothing happens, no matter the target(or no target) or distance. No morale is consumed, the icon briefly flashes the 60s cooldown as if it registered the use of the ability, but then goes back to being "usable". Very rarely, when spamming the button and constantly switching targets it does actually go off and summons the Firewyrm, which roars and despawns a second later, dealing no damage.

Would be nice if this Morale was fixed as it is actually very cool looking when it works.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/13697

**Comment by Warpmancer** [comment]
Does this mean you're still working on it or that it's not something on your agenda? The most powerful ability of a tree straight up not working is pretty dire imho.

**Comment by Kaelang** [comment]
It means it’s a duplicate and I’ve merged the two together.
