### ISSUE TITLE
Critical Hit Bonus paper doll error when wearing +Crit Hit Rating items

### ISSUE THREAD

**Issue by Rydiak** [WarEmu/WarBugs#17148]
![Rydiak_140](https://user-images.githubusercontent.com/15963532/84854592-a2d06180-b027-11ea-897c-9b7edeb33efd.jpg)
+Crit Hit Rating items are treated as multiplicative in terms of the tooltip for Critical Hit Bonus on the paper doll, as opposed to additive.  This makes some weird occurrences where 7% melee crit plus 10% critical hit chance (from Fanaticism) plus 2% Crit Rate (from Sovereign Martyr cloak) equals 17.34% critical hit bonus [ (7+10)*1.02 ], instead of the proper 19% [ 7+10+2 ].

**Comment by Rydiak** [comment]
Just to clarify, this appears to be a tooltip issue ONLY.

**Comment by lilimx** [comment]
Fixed with Patch 24/02/2022
