### ISSUE TITLE
Snot PQ giving wrong realm reward.

### ISSUE THREAD

**Issue by Dixbe** [WarEmu/WarBugs#17141]
The massive loot bags from finishing the living snot PQ are giving out the wrong realm pet.

**Expected behavior and actual behavior:**
Should be getting Destruction pet not an order one.

**Steps to reproduce the problem:**
Receive a massive loot back from the living snot PQ

**Testing Screenshots/Videos/Evidences (always needed):**
![hound](https://user-images.githubusercontent.com/64327427/84753909-8694dc00-afb7-11ea-9184-c7809a0da293.png)

**Comment by Kaelang** [comment]
This is a known issue. A vendor is soon to appear next to the herald allowing a transfer to the other pet. I’ll keep this open so those confused can see.

**Comment by Kaelang** [comment]
This was addressed with the new vendor.
