### ISSUE TITLE
Twisting tower bug after points drop to 0

### ISSUE THREAD

**Issue by ihqt** [WarEmu/WarBugs#17149]
**Expected behavior and actual behavior:**

Captured the lower control point ( Atrium ). After not being able to trigger the top floor explosion and points went to zero, went to capture the lower point again ( Atrium ). This time the control point was not interactable, so I was unable to capture the point. 

**Steps to reproduce the problem:**

1. capture control point ( your character )
2. lock control points
3. faction score to 0
4. try to recapture same control point again ( on same character )

**Testing Screenshots/Videos/Evidences (always needed):**
![twisting_tower_bug_2](https://user-images.githubusercontent.com/66976051/84876832-5cfbb380-b090-11ea-9179-d795e4ff7d82.png)
**It seems that screenshot doens't  include the cursor, so the evidence here is a bit insufficient.**

**Comment by Kaelang** [comment]
This was hotfixed.
