### ISSUE TITLE
Characters and mounted NPC standing on mount, mount sliding over ground

### ISSUE THREAD

**Issue by Rogots** [WarEmu/WarBugs#17144]
Hi all,

since the latest patch I have an issue that all my characters are standing on their mount.
Same applies for all other player (allied and enemies) and mounted NPCs.
While moving, the mount is sliding over the ground.
Ad-chat suggested clearing cache folder which didn´t help unfortunately. Deactivating
addons didn´t help either.

Thanks for any tip.

Rogi
![Bug Warhammer](https://user-images.githubusercontent.com/62203475/84822080-68ad9280-b01c-11ea-86f5-6132cabfebd6.PNG)

**Comment by Kaelang** [comment]
There are fixes for this on Discord / Forums. Move the directory out of Program Files.
