### ISSUE TITLE
Cant respec tradeskills.

### ISSUE THREAD

**Issue by vekanoi321** [WarEmu/WarBugs#1715]
I took 2 tradeskill that i didnt really wanted and now i cant change them in any way known to me. Please help i think this is a bug

**Comment by Evildoor** [comment]
What about typing ".respec Gathering" or ".respec Crafting" in Say chat?

**Comment by vekanoi321** [comment]
Tried several times, not working

**Comment by imneo58** [comment]
It is case sensitive. Not sure if that helps.

**Comment by vekanoi321** [comment]
Its with a slash right?

**Comment by noisestorm** [comment]
no with a PERIOD like is stated...

**Comment by vekanoi321** [comment]
Ahh im sry then gonna try it when i get home

**Comment by Zephonim** [comment]
I know I am not the OP, but this did work for me.

**Comment by Evildoor** [comment]
@vekanoi321 - status of this problem?

**Comment by vekanoi321** [comment]
All cool, didnt have the chance to play much tho i just reset the skills, didnt try to learn new

Date: Mon, 26 Oct 2015 06:35:58 -0700
