### ISSUE TITLE
[SW] Morale Drain Not Working As Intended

### ISSUE THREAD

**Issue by tcagrie79** [WarEmu/WarBugs#17152]
**Expected behavior and actual behavior:**
The Morale Drain on Barrage ability should be draining morale whle Vengeance of Nagarythe on.
But it does drain the amount (100 units) without Vengeance on.

**Steps to reproduce the problem:**
Just drop barrage on a destro char without Vengeance on

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
This should've been fixed with a recent patch.
