### ISSUE TITLE
hello i have problem with one quest i want to take epic quest from region dragonwake chapter 20 but when i come there npc who give that quest was bugged i cant take it i try to relog even i ask gm he say to me to spam here a problem thx 

### ISSUE THREAD

**Issue by Shomy83** [WarEmu/WarBugs#17154]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Hi - I’m going to need more specific information if I’m to look at asking for action on this. 

NPC names / quest stages / locations and screenshots please.

**Comment by Shomy83** [comment]
![epic quest 4](https://user-images.githubusercontent.com/67089608/85192178-d75f4a00-b2c1-11ea-9637-0ad35cbe844d.jpg)

**Comment by Shomy83** [comment]
![epic quest 3](https://user-images.githubusercontent.com/67089608/85192216-f9f16300-b2c1-11ea-900b-c5dd272d7181.png)

**Comment by Shomy83** [comment]
Location >>>>>>> Dragonwake Chapter 20
Quest >>>>> Epic quest <High Elfs>

**Comment by Kaelang** [comment]
NPC's often move away from their positions, sometimes server-later, sometimes bug related. They typically fix after a restart. Please re-open if issue remains persistent after the earliest reset.
