### ISSUE TITLE
Abusive Position at Mourkain Temple Scenario

### ISSUE THREAD

**Issue by Enjeremy** [WarEmu/WarBugs#17150]
In  the scenario,  there is a huge tree near the destro spawn, which provides sufficent space for 2 player to hide inside. If they do, the only way for order to get in line of sight is by standing with the back to the destro spawn. So the first problem is obvious: a player carrying the artifact is able to hide there, and the terrain provides a natural defense in all directions but one, which happens to be one from where he cannot be attacked probably because order has to worry about spwan mobs. Next second problem is, that the artifact will NOT reset, if the defending player stands there. So all destro has to do to win mourkain temple is to conquer the artifact once, then rush to the position and defend there, by guarding the ball carrier in place and focus heal him from spawn. this is broken

**Comment by bosli42** [comment]
The exact same position is available for order near their spawn and is used a lot.
Not sure if the spot can be healed from up top spawn, but at least from within guard attack range.

**Comment by Lheana** [comment]
Would need a screenshot as I don't see what tree it is.

**Comment by Kaelang** [comment]
Closing as no additional information provided.
