### ISSUE TITLE
Demonrend weapon proc give 80 wounds insted 110

### ISSUE THREAD

**Issue by Vicgrim** [WarEmu/WarBugs#17158]
Demonrend weapon proc "Preservation" on being hit give 80 wounds insteed 110

Expected behavior and actual behavior:
Expected: Preservation increases wounds by 110 as described in tooltip.
Actual: Preservation increases wounds by 80.
![magus wounds](https://user-images.githubusercontent.com/51807854/85026996-15555480-b182-11ea-9b89-26235c323a23.jpg)
![magus wounds 2](https://user-images.githubusercontent.com/51807854/85027034-20a88000-b182-11ea-8e19-8b53d93ead87.jpg)
![magus wounds 3](https://user-images.githubusercontent.com/51807854/85027061-269e6100-b182-11ea-9f9d-c8402e25fc49.jpg)

**Comment by RoR-Zomega** [comment]
https://github.com/WarEmu/WarBugs/issues/14920
