### ISSUE TITLE
spirit of the djinn weapon wounds proc "Preservation" dont work

### ISSUE THREAD

**Issue by Vicgrim** [WarEmu/WarBugs#17159]
Spirit of the djinn weapon wounds proc "Preservation" dont work.
 "Preservation" - on beeing hit incares 10% chanse to incares wounds by 110 for 20 sec.

Expected: 
Preservation increases wounds by 110 as described in tooltip.
Actual: proc dosnt work.

Steps to reproduce the problem:
Equip spirit of the djinn. Get hit.

Video:
 https://youtu.be/4UbSSAaoCmc

**Comment by RoR-Zomega** [comment]
What potion do you have? It won't stack with potions. Also, the proc is bugged and only buffs you for 80 (https://github.com/WarEmu/WarBugs/issues/14920) so if you had an 80 wounds liniment on then you wouldn't see any benefit at all.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/15283
