### ISSUE TITLE
Snot not spawning with active PQ

### ISSUE THREAD

**Issue by Jesden** [WarEmu/WarBugs#17155]
**Expected behavior and actual behavior:**
the PQ boss is not spawning despite the PQ saying it is active. Meter is present however. Means people cannot progress the quest, or indeed complete the event.

**Steps to reproduce the problem:**
tried multiple days, same issue. Chat reports it as being like this for multiple days.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/65976082/84995904-79592800-b144-11ea-83a6-592da553da5e.png)

**Comment by Kaelang** [comment]
This should have since been fixed.

**Comment by geezereur** [comment]
Seems like Snot dont spawn atm.

**Comment by Kaelang** [comment]
Thanks, will re-open this and look to address before event end.

**Comment by Chester3000** [comment]
![TheLivingSnot](https://user-images.githubusercontent.com/66531682/85083117-0379ae80-b18e-11ea-8884-cc5cc3f40ef6.jpg)

Current Status of The Living Snot.

**Comment by Chester3000** [comment]
Just letting you know, this is still broken

**Comment by Kaelang** [comment]
Thanks - we're aware. The report is still open.

**Comment by Kaelang** [comment]
And - closing this up. Should be fixed.
