### ISSUE TITLE
Garden of Qu'aph: Squig attacking people on the upper deck causes the guards to only kill the squig

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#17168]
**Expected behavior and actual behavior:**

If you are on the upper deck as a Squig Herder and tell your Squig pet to attack someone else on the upper deck, the NPC guards will eventually react but they only kill the squig. You can keep spawning more squigs and attacking with them and the guards won't ever attack you for it.

**Steps to reproduce the problem:**

1) Be Squig Herder
2) Summon any squig
3) Tell the squig to attack any order player on the upper deck.

**Testing Screenshots/Videos/Evidences (always needed):**

Preparing:

![Fotm_032](https://user-images.githubusercontent.com/60266177/85061312-873b9700-b19e-11ea-8e61-b77c41825357.jpg)

Attacking:

![Fotm_033](https://user-images.githubusercontent.com/60266177/85061331-8efb3b80-b19e-11ea-80c1-1d0963d70246.jpg)

Guard just killing squig:

![Fotm_034](https://user-images.githubusercontent.com/60266177/85061349-99b5d080-b19e-11ea-97aa-e233c145a630.jpg)

**Comment by Kaelang** [comment]
This was fixed in todays hotfix.
