### ISSUE TITLE
Fort population still broken

### ISSUE THREAD

**Issue by Agrokulture** [WarEmu/WarBugs#17165]
Currently in Fell landing and the population is 241 Attacker vs 226 Defenders.  Somehow to many defenders are getting in.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17164

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17166
