### ISSUE TITLE
Garden of Qu'aph: Squig Herder can stand on upper deck and have the pet attack people below. Guards don't react

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#17167]
**Expected behavior and actual behavior:**

The squig should not be able to target people who you are not duelling. Instead, you can stand on the upper deck and if someone below is in range you can tell the squig to attack them. The squig will jump into the arena and attack and the guards do nothing.

**Steps to reproduce the problem:**

1) Be a Squig Herder
2) Stand on upper deck at the edge overlooking the arena.
3) Have someone of the opposite faction standing directly below.
4) Summon any squig
5) Target the person below
6) Tell the squig to attack

**Testing Screenshots/Videos/Evidences (always needed):**

I'm above, Squig is attacking someone below. I am not flagged for any duels.

![Fotm_031](https://user-images.githubusercontent.com/60266177/85061013-0aa8b880-b19e-11ea-93eb-e22ef8cdfbd9.jpg)

**Comment by Kaelang** [comment]
This was fixed in todays hotfix.
