### ISSUE TITLE
Fort population issue as of the 18/06/2020 patch

### ISSUE THREAD

**Issue by Jesden** [WarEmu/WarBugs#17166]
**Expected behavior and actual behavior:**
The fort population is meant to be defenders at 75% of attackers as of the 10/06/2020 patch, This was correct in the earlier The Maw siege I participated in before todays patch (no picture due to not expecting an issue).

The current (in progress) Fell Landing siege has a defender population of 93% of attackers, being 18% higher than it should, with large active queues on both factions.

It may be an error where folks in the zone are kept in there and not counted towards the ratio?

**Steps to reproduce the problem:**
reloaded UI to see if it was an issue with SoR, population increased by 1 on Order side, and a decrease of 2 on Destruction, with queues increasing.

The previous fort I was in (same day) was 240/180 which is the correct ratio for that number of attackers.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/65976082/85060659-848c7200-b19d-11ea-8ea6-e73ce3feedd2.png)
![image](https://user-images.githubusercontent.com/65976082/85060676-8bb38000-b19d-11ea-856a-47080bc71f7b.png)

**Comment by Jesden** [comment]
I apologise, I did search for other issues, but I imagine they were raised between the search and my posting.

**Comment by Kaelang** [comment]
@Jesden No worries - a few came up at the same time and yours had additional information so I merged them into here.

There is a fix pending.

**Comment by Kaelang** [comment]
This was fixed in today's hotfix.
