### ISSUE TITLE
Garden of Qu'aph: Eternal Sentinel (Rank 40 lord) killed and not respawning

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#17163]
**Expected behavior and actual behavior:**

I would expect this guy to either be invincible or at least respawn after dying. He's been lying dead for about 10 minutes now.

**Steps to reproduce the problem:**

Kill the patrolling Eternal Sentinel NPC in the upper deck.

**Testing Screenshots/Videos/Evidences (always needed):**

![Zomega_421](https://user-images.githubusercontent.com/60266177/85054419-eba52900-b193-11ea-8a37-53ded350c3cf.jpg)

**Comment by Kaelang** [comment]
This was fixed in todays hotfix.
