### ISSUE TITLE
Invader 5 piece set bonus, Squig Herder

### ISSUE THREAD

**Issue by BogSniffa** [WarEmu/WarBugs#17173]
**Expected behavior and actual behavior:**
The five piece set bonus for SH invader is +10ft range, this appears to be intented for melee aswell as ranged attacks as the tooltip changes for melee attacks from 5ft to 15ft, and you can start the attack animation on a target from 15ft, However thats as far as it gets, no damage actually occurs, no global cooldown and combat is never actually entered.

**Steps to reproduce the problem:**
equip 5 piece of invaders on squig herder, enter squig armor, confirm melee attack tooltips have increased to 15ft, attempt to attack target dummy, mob, hostile target etc from 6-15ft distance.

**Testing Screenshots/Videos/Evidences (always needed):**

https://youtu.be/3xwBmNW2LMc

**Comment by Kaelang** [comment]
Range modifies impact Ranged Abilities - I believe this is a tooltip issue on melee attacks.

**Comment by Garrthax** [comment]
afaik sw inv set increases melee attacks range and it works perfectly

**Comment by BogSniffa** [comment]
If Garrthax is correct than the tooltip is correct but the range increase is not applying to melee for SH, If anyone has/ could get, a SW to confirm that would be helpful.

**Comment by Garrthax** [comment]
well, i was wrong, it worked before when invader was added

its same as squig now - only add range in skill tooltip, but no "real" range

**Comment by grunbag** [comment]
Can’t fix that
