### ISSUE TITLE
[Choppa] Choppa mechanic negatively impacting [Hurtin' Time]

### ISSUE THREAD

**Issue by Killamanjaro** [WarEmu/WarBugs#17185]
**Expected behavior and actual behavior:**
Expected: The Choppa mechanic does not improve the damage of [Hurtin' Time] but it is increasing the damage to the Choppa for using it while enraged. It should not be affected at all by Choppa mechanic (even negatively). 

Actual: The Choppa mechanic is not improving the damage of [Hurtin' Time] but it is reducing the mitigation of Armor to [Hurtin' Time] damage.

Example (see screenshot) 
Your Hurtin' Time hits target for 117 damage
Your Hurtin' Time hits you for 43 damage (16 mitigated)

While enraged,
Your Hurtin' Time hits target for 117 damage
Your Hurtin' Time hits you for 51 damage (8 mitigated)

**Steps to reproduce the problem:**
attack anything 

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/61355379/85174828-c4a23200-b23b-11ea-9ce9-58bf2be48319.png)

**Comment by SilverWF** [comment]
It's because you are losing half of armor in the Berserker state

**Comment by Killamanjaro** [comment]
Correct. The mechanic is negatively affecting Hurtin' Time but not gaining the positive effects (+25%/+50% damage increase). It is therefore a bug to ignore half the mechanic.

**Comment by Ysaran** [comment]
memory may be playing me, but i think that they implemented the Rage damage scaling on Hurtin' Time a couple of years ago, but then they reverted the change cuz Rage was scaling also with gear's procs and that was not intended to happen.
