### ISSUE TITLE
Medallions don't drop by Renown Rank

### ISSUE THREAD

**Issue by magter3001** [WarEmu/WarBugs#1718]
On Live, medallions would drop by the renown rank of the player. If you killed a renown rank 30-39 player, you would get a soldier medallion. If you killed a renown rank 40+ player, you would get officer medallions or a conqueror crest (which would break down to 5 Officer Medallions). This was used to reward players who tried to kill those higher RR players (and make them a bigger target). Right now only Scout Medallions drop even if the player you killed was RR40. This also helped people get gear quicker and through kills very viable.

Also need a confirmation if medallions drop in scenarios or not. TY ;)

**Comment by Evildoor** [comment]
From my experience, medallions do not drop in SCs, only emblems.

**Comment by edocatini** [comment]
http://www.zam.com/wiki/Medallion_(WAR)   The only problem to fix is the very rare drop of medallions in rvr ( the drop of a medallion was common in the old WAR)

**Comment by Evildoor** [comment]
Now medallions drop in scenarios, but still only Soldier (in T3) ones.

**Comment by Evildoor** [comment]
Medallions no longer drop in scenarios (by decision) and drop by renown rank.
