### ISSUE TITLE
Keep/Fortress Lords purge dots/effects after several seconds

### ISSUE THREAD

**Issue by Elares123** [WarEmu/WarBugs#17182]
**Expected behavior and actual behavior:**
expected:dots should last the full time when attacking keeplords.

actual:dot and debuff effects lasting longer than a few seconds often vanish all at same time while fighting the keeplord.
seems like there is a global "purge" timer that gets all effects off the lord from time to time (every 30sec?)

**Steps to reproduce the problem:**
attack a keeplord with dots that preferable last 21sec. most of the time they just vanish after a few seconds.

**Comment by Xicoz** [comment]
Pretty sure this is just a lord mechanic, he cleanses himself after shouting a message

**Comment by dalen** [comment]
Yes, they say "Begone" each time they cleanse debuffs
