### ISSUE TITLE
Enchanted Arrows - Flame Arrow does not bypass resistances

### ISSUE THREAD

**Issue by Evilmariel** [WarEmu/WarBugs#17184]
**Expected behavior and actual behavior:**

Expected Flame Arrow to have some damage difference when swapping between tactic on/off but damage was the same.

![image](https://user-images.githubusercontent.com/46075524/85142766-d8876d00-b216-11ea-9cf1-f803fd615138.png)

Tested on a KOTBS in the new dueling area Garden of Qu'aph

Actual:
Enchanted Arrows Tactic ON:
![image](https://user-images.githubusercontent.com/46075524/85142739-cf969b80-b216-11ea-957a-23e8a7beff98.png)

Enchanted Arrows Tactic OFF:
![image](https://user-images.githubusercontent.com/46075524/85142948-14bacd80-b217-11ea-8d82-45728349b0ea.png)

Also tested with Smoldering Arrows which did work on increasing the DoT damage:
![image](https://user-images.githubusercontent.com/46075524/85143072-47fd5c80-b217-11ea-9882-f1c547ea6f3a.png)

![image](https://user-images.githubusercontent.com/46075524/85143124-5c415980-b217-11ea-8141-1e14e396c2d2.png)

Tested with Masterful Aim, Powerful Draw, Enchanted Arrows (Swapped to Centuries of Training for OFF), and Replenishing Strikes on R40/54 Shadow Warrior

*Steps to reproduce the problem:**

Equip Enchanted Arrows on a Shadow Warrior

**Comment by Farlopa** [comment]
Patch Notes 10/06/2020 - Happy Birthday
Updated - Enchanted Arrows no longer affects Flame Arrow

**Comment by Evilmariel** [comment]
Well dang did not see that; thanks for pointing it out! Closing the issue
