### ISSUE TITLE
Archmage mastery skills bugged with numbers. 

### ISSUE THREAD

**Issue by foilchin** [WarEmu/WarBugs#17181]
> 
![image](https://user-images.githubusercontent.com/67131618/85088024-e5af4800-b193-11ea-83b9-3e21172a5bc2.jpg)

**Expected behavior and actual behavior:**
Skills should be able to activate and be used, cannot use them in combat. 

**Steps to reproduce the problem:
I simply respected at the mastery trainer and after receiving skills they are filled with numbers. 

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Garrthax** [comment]
happens sometimes, just restart or /rel

**Comment by SilverWF** [comment]
This is not "numbers" this is cooldown
