### ISSUE TITLE
Garden of Qu'aph: environment doesn't cast any shadows

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#17180]
**Expected behavior and actual behavior:**

The environment doesn't cast any shadows on the new map. The character models of the players are all casting shadows fine, but no a single piece of work geometry is casting a shadow. This is making  the map appear "flat" and slightly more washed out than it should otherwise be.

The lighting correctly changeds based on the time of day, it's just that no shadows are cast to darken the areas that the sun can't see. This is very noticable in the arena itself which should have some sharp shadows in it, as well as all of the statues around the upper deck.

I don't know if there's a client setting you've missed to set the direction of world/environment shadows or what. All of the standard Mythic levels have environment shadows. Hopefully it's not something that needs to be precomputed as that will make it a lot tougher...

**Steps to reproduce the problem:**

Go the Gardens and see the lack of shadows being cast.

**Testing Screenshots/Videos/Evidences (always needed):**

What it looks like.

![Zomega_435](https://user-images.githubusercontent.com/60266177/85084683-75bdb380-b1cd-11ea-8fea-78de98e8ba44.jpg)

Terrible example of where shadows should be:

![Zomega_435a](https://user-images.githubusercontent.com/60266177/85085060-87538b00-b1ce-11ea-8f10-b10db2c4b00c.jpg)

**Comment by Kaelang** [comment]
The entire area was custom-built by Yali, at this time I think adding shadows to custom elements is pretty tricky. And as opposed to being 'bugged' or forgotten, it's simply a nod to the limitations we have at the minute when it comes to custom content.

Going to close this up as we're aware there's no shadows, but at this time there's no additional options to put in place that can easily fix something like this.
