### ISSUE TITLE
[ENGI] Autoattack range not working as intended

### ISSUE THREAD

**Issue by Dundara** [WarEmu/WarBugs#17188]
Notes: Autoattack default range is 100ft, **turrets should be affecting AA range of engi**
- Autoattack range is not being increased by gun turret -125ft
- Autoattack range is not being decreased by flame turret - 60ft
- Autoattack range stays the same with bombard - 100ft (normal)

**The problem:**
Currently AA range is not affected by turret mechanics

**Steps to reproduce**
Test however you like with any turret, AA range will always be 100ft

**Comment by lilimx** [comment]
Hey,

this issue looks resolved. I've tested it and the dmg increase works as intended.
Btw. the base AA range is 90

**Comment by Dundara** [comment]
It's good that it's doing the damage it is supposed to mate but I'm talking about the range, fix the RANGE when using GUN TURRET
