### ISSUE TITLE
White Lion: Pounce

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#17183]
If a white lion pounces on you from far away while youre going the other direction on a mount :

**What Happens**
He lands 50 feet behind you but it still dismounts you and hits you somehow.

**What should happen**
He tracks to you while in air, or he doesn't hit and gets an out of range message instead.

**Comment by Kaelang** [comment]
Related to the visual element: https://github.com/WarEmu/WarBugs/issues/16666
