### ISSUE TITLE
Chosen Auras buffing enemies instead of debuffing them

### ISSUE THREAD

**Issue by Chawsz** [WarEmu/WarBugs#17191]
Character name: Malgrex
Order assistant: Toshutkidsup

As in the title, chosen auras are providing buffs to enemies instead of debuffing them.

I found my damage a little off so I went to the garden of qu'aph to ask an order player to help me out and stood next to him with and without auras and confirmed that the auras were buffing him and not debuffing him. It is working as intended in duels but not in ORvR. This bug is also present for KotBS.

video link for outside of duel: https://youtu.be/4Rg-2o6g14M
video for in duel: https://youtub.be/neu4sthPyU4

Hope this helps and you can get this sorted soon.

**Comment by Kaelang** [comment]
Does this happen in oRVR, or only within the garden? 

Also your second YouTube link - doesn't take me to YouTube.

**Comment by Kaelang** [comment]
Duplicate report just posted shows auras impacting oRvR too. Going to merge into the one for now: https://github.com/WarEmu/WarBugs/issues/17190
