### ISSUE TITLE
Twisting Tower 1v1 bugged instance 

### ISSUE THREAD

**Issue by nnnnNATHANnnnn** [WarEmu/WarBugs#17193]
Twisting tower is starting instances with 2 players. I just had one as a WL vs a single sorc. wasn't very fair. 
![WAR-64 2020-06-20 19-20-37](https://user-images.githubusercontent.com/56577119/85215328-e7137880-b32b-11ea-82b7-966d908fbd6e.png)

**Comment by MaxHayman** [comment]
The minimum players for this SC is 6. It may have been a bug with something at the time. If it is still an issues please reopen.
