### ISSUE TITLE
Herald of Madness quest part 4 is not marked as completed in ToK

### ISSUE THREAD

**Issue by Firetribe31** [WarEmu/WarBugs#17198]
I cant get the last reward from the event cause the quest tracker in ToK is bugged some how.
![Ror1](https://user-images.githubusercontent.com/30737562/85229248-4dae9a00-b3f1-11ea-8b3b-110b9e7a5143.PNG)
![ror2](https://user-images.githubusercontent.com/30737562/85229249-5010f400-b3f1-11ea-8137-f570e535b91f.PNG)

**Comment by Kaelang** [comment]
What is the quest objective?

**Comment by Firetribe31** [comment]
> What is the quest objective?

Quest is in Norsca. Need to speak with Arglic The Fisher of Men.
That should trigger the part 4 as completed. Just did it with my alt and got it done ToK is 1/1 on my alt.

**Comment by Kaelang** [comment]
As this event has ended - I will close this report.
