### ISSUE TITLE
[WP / DoK] Vanquisher's career resource regen proc is too weak

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#17196]
Vanquisher's career resource proc gives 15 res over 3 sec (or 5 res every sec)
It makes this set very weak compared to 2 other similar ones: Onslaught and Sovereign, which gives 45 res over 3 sec (or 15 every sec)
Other proc params are the same: all three have 10% chance to proc on direct heals.
Maybe Vanq should give 45/3 sec too? Or proc more often? Or proc not on direct heals only? I don't know, please check.

**Expected behavior and actual behavior:**
Exp: having better proc on gear set with 58 iLvl
Act: it's not

**Steps to reproduce the problem:**
Buy Vanq set and wear it

**Testing Screenshots/Videos/Evidences (always needed):**
![2020 06 21-12 34](https://user-images.githubusercontent.com/16439840/85221472-b2033680-b3bc-11ea-92c4-1157fa820494.jpg)

**Comment by Rydiak** [comment]
This doesn't seem like a bug, but a balance request.

**Comment by Kaelang** [comment]
This is feedback.
