### ISSUE TITLE
Chosen aura benefiting enemies

### ISSUE THREAD

**Issue by Sixmoons48** [WarEmu/WarBugs#17190]
**Expected behavior and actual behavior:**
Chosen toughness aura "Positively" effects enemies, giving them toughness rather than taking it away

**Steps to reproduce the problem:**
Use tough aura and slap an enemy, then remove it and hit them again, can see small but visible change

**Testing Screenshots/Videos/Evidences (always needed):**

In the video i cleave the warrior priest for 0 dmg (but 129 mitigated), once i take my toughness aura off (meaning priest should have more toughness now and mitigate more) i hit for 0 dmg still but only 124 is mitigated. At top you can see when i switch off aura, and left where my damage chat window is.  If more substantial evidence is required i can try and get a friend on order side to test more

![Better evidence](https://user-images.githubusercontent.com/21229715/85202375-966c3300-b2cb-11ea-9fc1-05967156a14c.gif)
![image](https://user-images.githubusercontent.com/21229715/85202382-9b30e700-b2cb-11ea-9f49-91decfd21ae6.png)

**Comment by Chawsz** [comment]
Can also confirm the issue exists for KotBS where destro in ORvR benefits from their auras. I'll try and get some proof.

**Comment by Kaelang** [comment]
This has been fixed as of the hotfix. Please re-open if the issue persists.
