### ISSUE TITLE
[Black Orc] T3 Scenario Weapon not BoP

### ISSUE THREAD

**Issue by Krumlok** [WarEmu/WarBugs#1719]
![bug](https://cloud.githubusercontent.com/assets/14275335/10701069/0e79352a-79c2-11e5-95e7-be9d7a093df6.png)

It should be BoP. Now it can't be used for appearance anymore and it can be sold on AH

**Comment by Evildoor** [comment]
Whoever from the DB team takes this - since we had #1696, and now have this, can you take a look at all SC weapons in case more of them have this problem?

**Comment by Krumlok** [comment]
I will ask the members of my Tribe and my friends from various classes to see if their SC weapons have the same problem, Evildoor. Will update this issue with the answer.

**Comment by Meralors** [comment]
I fixed all of them now and they'll be updated/fixed with next patch.
