### ISSUE TITLE
Armor and Willpower potion - potion stat value change

### ISSUE THREAD

**Issue by palky** [WarEmu/WarBugs#17197]
Hi guys, i found issue about potions stat value change. It happens if you use potion in scenario and when you return from scenario into the city, pve, ... . **It start happens this week.**

How to reproduce issue:

1. 
I'm using in scenario (twisting tower, reikland factory) two potions --> Potent Lasting Stanchion Unguent ( +825 armor) and Potent Lasting Potion of discipline (+100 willpower). During scenario all potion stat values are good.

2. When I finish scenario and return back to"world" then all stat on mentioned potions drop down on next lower potion tier = i have +660 armor and +80 willpower. Potion names change too.

3. Check the pictures in attachment and you will see in left upper corner.

![Lapky_024](https://user-images.githubusercontent.com/18732650/85229041-c7418a80-b3e7-11ea-84f7-68cc0969b916.jpg)

![Lapky_022](https://user-images.githubusercontent.com/18732650/85229044-c872b780-b3e7-11ea-8ee4-66cf93f34aa2.jpg)

I hope this helps you find a bug. :-)

**Comment by Kaelang** [comment]
Duplicate https://github.com/WarEmu/WarBugs/issues/17129.
