### ISSUE TITLE
[DESTRUCTION QUEST] Defilers of the Castle

### ISSUE THREAD

**Issue by Enigmaxou** [WarEmu/WarBugs#172]
Quest doesn't work when you complete NW scenario. I'm aware that SC is not fully functionable. 

NPC : Raven Warmonger

![myyah_003](https://cloud.githubusercontent.com/assets/8019588/3430261/d305f456-005f-11e4-8505-3d000ed2aeeb.jpg)

**Comment by Evildoor** [comment]
Quest was removed, IIRC.
