### ISSUE TITLE
[Slayer] Distracting Roar is not remove your rage with Power Through tactic

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#17208]
Distracting Roar is Slayer's detaunt skill
When you use it, it should remove your rage.
And it does, but not when you have Power Through* tactic equipped.
_*Power Through - exhaustive blows does not remove your rage._

 Exhaustive blow - is special skill type. Distracting Roar is NOT exhaustive blow.

**Expected behavior and actual behavior:**
Expected: Distracting Roar should always remove your rage
Actual: it's not

**Steps to reproduce the problem:**
Equip Power Through tactic
Gather some rage
Use your detaunt
See you rage at the same level

**Testing Screenshots/Videos/Evidences (always needed):**
https://www.youtube.com/watch?v=HsP8gnHF_WY

**Comment by SilverWF** [comment]
The same situation at Choppa:
Their detaunt Outta My Face! does not remove your rage with Wot Rules tactic equipped.

**Comment by Killamanjaro** [comment]
Choppa's like the way it works as it was a balance for those who didn't want detaunt to drop rage.

**Comment by kalmatar** [comment]
there was a long balance discussion in 2018 behind this change, and this was deemed as the most optimal outcome
1) you are using a tactic that prevent exhaust drop from ability use
2) wasting 15-20sec of mechanic build up to do something as basic as detaunt would gimp the class vs normal class detaunts
3) you can always run without the tactic if you want your exhaust dropping abilities to drop exhaust
4) your expected argument is wrong and this is not first time you create false info bug reports when you want to change balance of class you playing

**Comment by SilverWF** [comment]
1. Exhaustive blow - is special skill type. Distracting Roar is NOT exhaustive blow.
2. Any wb slayer would be happy to lose it to save himself, BUT this is NOT discussion thread
3. See point. 2
4. This is bugtracker, not forum, where (it seems) you get used to throw personal attacks left or right. I didn't created false info bug reports yet.

**Comment by grunbag** [comment]
Working as intended , DR is dropping rage as a QoL change when rage can be removed. It’s havent been reworked to bypass a tactic counterpart.
