### ISSUE TITLE
Account is frozen.

### ISSUE THREAD

**Issue by punakone** [WarEmu/WarBugs#1720]
My old account doesn't work anymore even after changing password it says "invalid password/username" I created a new account wich works perfectly but I'm afraid I'll never get back to my old characters!

**Comment by Evildoor** [comment]
Password change takes hours, sometimes days, to affect game account. Do not abandon your hope yet.

**Comment by punakone** [comment]
thanks I appreciate it and hope it will update soon so that I could get back in there.. In the meantime I think I'll play with a new char from other account. Btw is multiboxing denied on your server?

**Comment by Evildoor** [comment]
Multiboxing is not allowed.

**Comment by punakone** [comment]
Good to know

**Comment by punakone** [comment]
Now I made this account my "order" side account and I'm going to play for a while and see if it works, thanks again :)
