### ISSUE TITLE
Dok lifetap not matching (maybe the same with wp)

### ISSUE THREAD

**Issue by Dekoupwar** [WarEmu/WarBugs#17202]
Hi,
On my dok, I am testing tactics which increase heals from lifetap. 
- My tactics are Empowered transfer (+25% heals on lifetap) 
- Murderous intent ( +10%crit +10% parry -20% on casted heals)
- Transfer focus (+20% heal on defensive target)
- Khaine blessing (on crit, 10% to have +50% AA haste)

On my test : 
https://zupimages.net/up/20/26/boc4.jpg

I wait for the proc of transfer focus and I hit a target
consume essence does 408dmg 
so 408 + (408 * 25% + 408 * 20%) = 591.6 but I am healed for 510

And on the Rend Soul : 
https://zupimages.net/up/20/26/otiu.jpg

Reminder ; Rend Soul = heal you for 360% of the damage done
my Rend Soul hit for 303
so 303 + (303 * 360 / 100) = 1393.8 but i am healed for 1324

So it's less than it should, and I neither count the Transfer focus which was up on me and neither the Empowered transfer

**Comment by Rydiak** [comment]
Numbers are correct, but your math isn't.  Transfer Focus only works for casted heals, not lifetaps.

**Comment by Dekoupwar** [comment]
Yeah you're right, it matchs, but it says : "Any time you critically hit an enemy, your defensive target will become 20% more receptive to direct healing effects during 10 sec"

I thougth it was all healings except hot, because when you look to Divine fury or Murderous intent, they speak of "casted healing"

So I don't get it, that mean that you have to melee crit any enemy to get your defensive target more healable but not by you ?

And about the Rend Soul ? I did the math without counting any tactics and it stills not match 😋

**Comment by Rydiak** [comment]
Lifetaps are not direct heals.  Changes were made to many tooltips to help clear up some of this confusion, but perhaps Transferred Focus should be changed to say "casted heals" to help further.

Rend Soul heals for 437.5% of damage done when equipped with Empowered Transfer (25% multiplicative bonus).  Again, check your math. 😋

**Comment by Dekoupwar** [comment]
You're right, my bad i said shit
thank you for enlightening me :D
