### ISSUE TITLE
Invisible Marauders

### ISSUE THREAD

**Issue by Templergun** [WarEmu/WarBugs#17204]
Hi,

i am having an issue where Marauders appear completely invisible for me, they do not have any hitbox. I can only see their Nameplate and also only if they attack me.

**Comment by Templergun** [comment]
Some more info:
- I am an IB
- I sometimes also see empty Chaos horses standing around in RvR. If that has to do with the Missing Marauders the problem existed since i created this character and all zones T1-T4 are affected
- I stopped playing around mid April and started again on 19.06.2020 (i had to download a lot of patches and stuff, so maybe something could have gone wrong there?)

**Comment by Garrthax** [comment]
> Hi,
> 
> i am having an issue where Marauders appear completely invisible for me, they do not have any hitbox. I can only see their Nameplate and also only if they attack me.

solution is simple -
![image](https://user-images.githubusercontent.com/49390790/85285979-1e039e80-b492-11ea-9c36-b8680f4fbe29.png)

**Comment by Kaelang** [comment]
This is one for the forums.

**Comment by Templergun** [comment]
The "simple solution" was not helpful at all.
The problem continues to exist.
