### ISSUE TITLE
PvP map dragons bane bug

### ISSUE THREAD

**Issue by Slapinn** [WarEmu/WarBugs#17203]
The objective of dragons bane is to take the summon orb to one of the enemy control points and summon your teams dragon. while holding the orb your slowed down and unable to regenerate AP. If you die with the orb the orb's effect doesn't go away after spawn so your stuck not being able to regain your AP and still slowed down till you die once again. Playing a tank on this map is the worst because your always having to pick up the orb so most of the match you're stuck with no AP and slowed.

Resubmitting this because I didn't submit the bug report correctly last time which I apologise for.

**Comment by Kaelang** [comment]
This has been fixed in todays patch.
