### ISSUE TITLE
Apothecary broken - craft failures

### ISSUE THREAD

**Issue by Fuamatu** [WarEmu/WarBugs#17219]
**Expected behavior and actual behavior:**
Expected: Add the appropriate ingredients and have a successful craft
Actual: Add the appropriate ingredients and 100% fail

**Steps to reproduce the problem:**
See above

**Testing Screenshots/Videos/Evidences (always needed):**

https://streamable.com/4dcw1t

**Comment by Kaelang** [comment]
Thank you for this report.

**Comment by Kaelang** [comment]
Fixed in hotfix.
