### ISSUE TITLE
 Backpacks are bugged

### ISSUE THREAD

**Issue by Whentballistic** [WarEmu/WarBugs#17218]
The backpacks seam to be bugged after the patch today.  Compartments are not fully open with items missing on both my Order and Destruction Characters.  My son is having the same issues.

**Comment by Kaelang** [comment]
Reload your launcher. And try deleting your cache.

Also ticking and unticking List View should work.

If this doesn't work, please use Support on the Forums.

**Comment by Whentballistic** [comment]
It worked, thank you !!!
