### ISSUE TITLE
Proc of Demonred (and maybe Djinn too) bugged

### ISSUE THREAD

**Issue by lemalestfait** [WarEmu/WarBugs#17215]
Hi guys, 

After consultation with magus and sorc too (who have kind of same proc), we found the Preservation buff is capped for 80 HP and not 110HP. Is it a tooltip bug or a buff bug? 

https://nsa40.casimages.com/img/2020/06/24/200624034128819498.jpg

https://nsa40.casimages.com/img/2020/06/24/200624034128441574.jpg

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/14920 Duplicate.
