### ISSUE TITLE
Bloodlord Painblade (mainhand only)

### ISSUE THREAD

**Issue by Stophy22** [WarEmu/WarBugs#17210]
Bloodlord painblade is a mainhand only weapon and this is incorrect due to the nature of the other bloodlord weapons in the game.

-Bloodlord Xiphos and Edge are both mainhand **and offhand** 
-Fortress painblade and edge are mainhand **and offhand**
-Countless other "_painblade_" classified weapons are both mainhand **and offhand**
-Other classes with difference classifications of weapons and duel wield (like marauder/WE/Choppa/Slayer) have all 3 weapons as mainhand **and offhand** pictures below.

The issue with this include:
1. Very few items can change the appearance of a mainhand only item, since it has to have the same weapon classification.
2. Other classes only need their 1st inf reward to get BL weapons in an offhand slot if they wanted, while DoK needs 2nd inf rewards to get the option
3. Dok has to choose shield as 1st inf reward if he ever wants the option at offhand bloodlord. (refer to reason 2 why this is a problem.
4. In the future when bloodlord weapons become non-bis people will want them as offhands. 

Biggest issue for me is the cosmetic side of things but that's fixed by 2nd reward. Just thought I'd be thorough since things like this usually turn up as "working as intended" when it clearly seems to be a bug. (no other class does this and its replicated no where in city weapons or invader weapons).

![Bloodlord Painblade](https://user-images.githubusercontent.com/23489906/85476098-b70ae600-b574-11ea-9c73-c7858040f653.PNG)
![Bloodlord mainhandoffhand](https://user-images.githubusercontent.com/23489906/85476102-ba05d680-b574-11ea-8c67-ceac95655ef0.PNG)

If this is working as intended would like a detailed reason for such, as all signs just point to an oversight, thank you!

**Comment by Kaelang** [comment]
Not necessarily convinced this is a bug - however will leave this open until someone can confirm.

**Comment by Stophy22** [comment]
Why would only one bloodlord weapon in the game be mainhand only when all other dual wield classes have mainhand and offhand?

**Comment by Kaelang** [comment]
Kept this open for that exact reason, it doesn't make sense. But I'm not all fingers point to this being incorrect. There's a tonne of items that have specific requirements, i.e. MH v OH. That being said, with this being the only BL weapon that has it - does sound odd.

**Comment by Stophy22** [comment]
It would make sense if it had healing stats for mainhand only since chalice would be equipped. I think this is where the problem occurred since bloodlord weapons are dps orient by nature.

**Comment by Kaelang** [comment]
Thought it could be something to do with the pre-BL weapons being MH(?), and to stop a powerspike earlier than necessary  having the first unlock require MH so that the pre-BL weapon would need to be replaced as opposed to dual wield earlier than intended. Just double checked however and a few of the pre-weapons are indeed MH&OH.

But considering the comparison to other weapons - I doubt this would be the case. 

@wargrimnir should know.

**Comment by Stophy22** [comment]
If that were the case other classes with their first inf reward as dual wield (Mara, we, choppa, slayer) would have the same mainhand only quota that this appears to have. 

But I see the reasoning, I hope mine is seen as well.

**Comment by Killamanjaro** [comment]
Could be solved by a Bloodlord trade in option similar to Sentinal? 

Anyway, I think this is a legacy result of Blackguard/Dok sharing wep types. As Blackguards don't have the 'duel wield' skill, changing this to 'Main Hand and Off Hand' shouldn't be an issue.

**Comment by Stophy22** [comment]
Any response from @wargrimnir @Kaelang if this is incorrect?

**Comment by SilverWF** [comment]
I think this item was simply copied from BG

**Comment by Stophy22** [comment]
> I think this item was simply copied from BG

yes which is why I made a bug report since DoK weapons are mainhand and offhand and BG weapons are mainhand only.

**Comment by Vancerus** [comment]
Anything new on this? Half the servers DoK probably waiting on a solution for this issue.

The problem is mainly, you are limited to only 2 weapons/shield instead of 3 if you got the first influence weapon (when shield was not a thing yet), which is mainhand only. This was changed for the scenario weapons already to be mainhand and offhand as well.

Please consider adjusting these to be offhand as well soon.

Cheers,
Vance/Leechkhing
