### ISSUE TITLE
[SW] Glass Arrow AP cost

### ISSUE THREAD

**Issue by Bejkon** [WarEmu/WarBugs#17221]
Glass Arrow TT:
![GA200624](https://user-images.githubusercontent.com/35146895/85608392-4d163d80-b655-11ea-9e4b-c75ac0c61ed2.JPG)

In reality the proc drains 15AP instead of suggested 5AP.

How to:

Activate GA.
Use any scout ability.
Keep an eye on AP bar.

To clarify, its the AP cost on proc thats not matching TT, the cost(30AP) for activating the ability is matching TT.

Side note:
The damage still doesnt match TT, actual dmg is 65 lower than TT. This has however been brought up elsewhere.

/Bejk

**Comment by Kaelang** [comment]
Glass Arrow no longer procs on auto attacks, and it will consume 15 action points each time it procs (tooltip update will come later with client patch).
