### ISSUE TITLE
Absolution Skill Witch Hunter

### ISSUE THREAD

**Issue by mistmore** [WarEmu/WarBugs#17222]
The problem is that the skill doesn't work well.
When we are lvling Perfect absolution, after we get lvl 40 to make it work. I have some friends with this problem

**Comment by Kaelang** [comment]
Appreciate the report, but 'skill doesn't work well' doesn't help identify any problems with the skill.

Please re-open this if you can provide additional information / videos to identify the issue.

Thanks.
