### ISSUE TITLE
Reikland Hills SC, 19 players in Destro side.

### ISSUE THREAD

**Issue by Firetribe31** [WarEmu/WarBugs#17223]
Just joined 1st sc after restart. Joined in middle of the scenario and i noticed that im alone in 4th party.
My name was wrong in raid frames and even sometimes my name and class icon in party frames changes to Despe that got prolly got dc and wasnt in scenario at all. But even i got Despe's spot in scenario we had 1 extrra player in.
![BUG (2)_LI](https://user-images.githubusercontent.com/30737562/85618315-4396d080-b669-11ea-83f1-cad0929dba14.jpg)
![bug2 (2)_LI](https://user-images.githubusercontent.com/30737562/85618319-4691c100-b669-11ea-9628-9f45851e58e8.jpg)

**Comment by Kaelang** [comment]
This issue relates to an ongoing problem with scenario queue systems that is already known. For ease of management of these reports, I am going to close this, as this also relates to cities - of which there is already an active report.
