### ISSUE TITLE
overlay issue when joining scenarios and leaving scenarios

### ISSUE THREAD

**Issue by archmagebugreport** [WarEmu/WarBugs#17225]
I have all Addons disabled in these videos. 

**Expected behavior and actual behavior:**

 When joining a scenario, the overlay windows don't work properly. 
Cannot open the scenario party member without there being an issue.  sometimes scenario parties from past scenarios will still be in the scenario party windows.  also, upon entering or exiting a scenario there is a bugged scenario dps/heal chart.

**Steps to reproduce the problem:**

Join a scenario.

**Testing Screenshots/Videos/Evidences (always needed):**

https://www.dropbox.com/s/g39ca131dd5bmua/overlay%202%206.24.20.mp4?dl=0

https://www.dropbox.com/s/vnr91rc0omt1n8i/overlay%206.24.20.mp4?dl=0

**Comment by Awoosome** [comment]
i had the similar issue that you are having but on my part i am not able to release (/reload fix it)
party/wbframes not showing

![BTsc](https://user-images.githubusercontent.com/67471008/85864620-5808d380-b7f7-11ea-80ac-8b79d9d8dbf6.png)

**Comment by archmagebugreport** [comment]
**update** a fresh install fixed this problem for me.   please follow wargrimm's instructions on this post here

https://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=31241
