### ISSUE TITLE
Living snot spawn

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#17227]
Living snot still spawning in CW?
![Xico_002](https://user-images.githubusercontent.com/44329952/85796579-ca968800-b6ff-11ea-9293-7f364377501b.jpg)

**Comment by SilverWF** [comment]
Yes. Not sure if it's intended, but now it acts as just PQ. Gold bags has dogs, other - tentacle pies
Killing this doesn't give progress to the past event, but probably would give for the quest - it's still available also.

**Comment by Kaelang** [comment]
Will be fixed on next DB push.
