### ISSUE TITLE
backpack won't display properly

### ISSUE THREAD

**Issue by rainlily-ssoul** [WarEmu/WarBugs#17224]
my backpack won't load properly after last patch on all the toons. you can check the issue in attached files.

filename 1. when logged in
filename 2. default backpack after tick and untick listview
filename 3. currency 
filename 4. crafting
filename 5. quest
 
what I tried:
relog
rerun launcher
deleted cache
tick and untick list view like 100 times
repair launcher and reinstall patch 

and still issue keeps up, hope this would be fixed soon.

![1](https://user-images.githubusercontent.com/52802431/85630326-64354980-b6ae-11ea-96fe-131abd6b76a6.png)
![2](https://user-images.githubusercontent.com/52802431/85630334-67c8d080-b6ae-11ea-8612-1e19725b70d2.png)
![3](https://user-images.githubusercontent.com/52802431/85630347-6b5c5780-b6ae-11ea-9f98-89737214b4ce.png)
![4](https://user-images.githubusercontent.com/52802431/85630363-71eacf00-b6ae-11ea-9f89-9f7d66f36a55.png)
![5](https://user-images.githubusercontent.com/52802431/85630380-77481980-b6ae-11ea-81cc-0458c421de8d.png)

**Comment by Kaelang** [comment]
The fix for this is on your end - this is not a game / server related issue.

Please utilise the support networks on our forums and discord.
