### ISSUE TITLE
Reinforce war engine bug

### ISSUE THREAD

**Issue by ihqt** [WarEmu/WarBugs#17228]
**Expected behavior and actual behavior:**
Expecting to heal / cleanse ram with cleanse war engine & reinforce war engine. Instead getting has no implementation message. At least reinforce war engine should be usable to ram as stated on tooltip.

**Steps to reproduce the problem:**
Cast either of the spells mentioned to ram should result in error.

**Testing Screenshots/Videos/Evidences (always needed):**

![reinforce_war_engine_bug](https://user-images.githubusercontent.com/66976051/85864123-c5533f00-b7cc-11ea-8e34-6770b94d5b30.jpg)
1. Both skills toss error when trying to cast on ram

**Comment by Garrthax** [comment]
siege weapons heal/buff/debuff is not implemented

**Comment by ihqt** [comment]
> siege weapons heal/buff/debuff is not implemented

My bad then, feel free to remove this issue then if it isn't relevant as a bug.
