### ISSUE TITLE
Unable to turn in Training Course and Urgent Orders. Empire Ch. 1, Nordland.

### ISSUE THREAD

**Issue by Zephonim** [WarEmu/WarBugs#1722]
I am unable to turn in these two quests with my Warrior Priest. I was able to turn them in just fine with my Witch Hunter. I did notice that with my WH there were rewards(boots, exp, and currency), while with my WP there was only exp rewards. I have tried abandoning the quest and picking them up again just to make sure but no luck.

**Comment by Evildoor** [comment]
#1608
#1610

**Comment by Zephonim** [comment]
Both characters went through this 10/23, and I just checked 10/24 and my Warrior Priest is still unable to complete.

**Comment by Meralors** [comment]
Fixed Urgent Order, working on other one
