### ISSUE TITLE
Healer's Tome of Dominion

### ISSUE THREAD

**Issue by LokenGarviel** [WarEmu/WarBugs#17233]
This item does not give 4 righteous fury points every second.
Tried relogging ./rel buying another one and still not working.

Buy book from vender an get in combat to see it not regen.

![Book sigmar](https://user-images.githubusercontent.com/67485240/85911053-715a5180-b7f0-11ea-9193-2abc8408b27d.png)

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
You'll need to unequip and requip the item.
