### ISSUE TITLE
Inevitable City: Progression bar

### ISSUE THREAD

**Issue by Xicoz** [WarEmu/WarBugs#17230]
this was a problem in the past and was fixed, but after 20minutes of searching couldn't find my old post on this to reopen/post on.
The red bar at top right of screen is shooting way off to the left again.
![Xico_004](https://user-images.githubusercontent.com/44329952/85875400-bdc67280-b799-11ea-81f7-902714a43159.jpg)

**Comment by Kaelang** [comment]
There is already a live report of this.
