### ISSUE TITLE
[Guild Coins Quests]

### ISSUE THREAD

**Issue by Denteron** [WarEmu/WarBugs#17238]
I'm sorry for make that topic cause i know many players make same before.

Guild Coins Quests - 3 Quests and only 1 work correctly.
### 3 - UNITY AGAINST DESTRUCTION -RVR guild quest with Guild Coin reward (that quest almost broken, we make it once and that was like a bug. Our guild mate be in RVR while other group going to dungeon, when RVR zone was locked we done that Quest, that was a luck not testing time. I hope that litle help with fix it/

//_Expected behavior and actual behavior_//
--JOINT GUILDFORCES- Done condition is WIN SC(Scenario) with guild group- When we win SC (with all 6man group(guild mates)) nothing happening - done condition is dont work or looks like that (that was about 6month ago or looks like that sorry when im mistake and that problem was fixed)
--UNITY AGAINST DESTRUCTION- Done condition is LOCK RvR zone with guild group - That quest have same issue with Done condition after lock zone/ We make it only 1 time and that was a bug cause we triggered dungeon location. I dont know, maybe "dungeon trigger" can forse SC Quest to done condition too, i have no people to test it, sorry. But maybe "dungeon trigger" can be key to fix it.

**Comment by Kaelang** [comment]
Opening multiple tickets for the same report causes confusion.

There is already one open here: https://github.com/WarEmu/WarBugs/issues/15591
