### ISSUE TITLE
Possible x realm abuse with double accounts

### ISSUE THREAD

**Issue by ihqt** [WarEmu/WarBugs#17236]
_Faction lock seems to work fine even with multiple accounts. However, I managed to find a way to dodge the faction lock if you are playing on multiple accounts._

**Expected behavior and actual behavior:**

Expected behavior: get faction locked after capturing keep in destro.
Actual Behavior: Was able to login just fine to order.

**Steps to reproduce the problem:**

1. Do whatever atrocities you need to do to get locked and exit game.
2. Shut down RoR launcher ( This might not be needed ).
3. Restart your router ( I'm running mobile internet so this might differ ). Toying around with ipconfig might also be enough to do the trick.
4. Start launcher and Login to your opposite faction account and you are able to play.
------------------------------------------------------------------------------------------
5. Exit game and log to your destro character. ( don't boot router ).
6. Now it displays faction lock that you should have got from part 1.
7. Faction lock now carries to order account but its timer is from part 1.

**Testing Screenshots/Videos/Evidences (always needed):**
Can duplicate the problem and get some screenshots if needed, Kinda hard to prove my point with just pictures and rather not share some of the screenshots publicly if possible.

**Comment by Kaelang** [comment]
Thanks - this isn't necessarily a bug, it's just a limitation of the system.
