### ISSUE TITLE
[Slayer] [No Escape]

### ISSUE THREAD

**Issue by papsbug** [WarEmu/WarBugs#1723]
Do not exhaust rage.

**Comment by Evildoor** [comment]
Checked, indeed it does not, while description says it should. Strange, since we have #1601. Combat log also says "Your Escape hits ...", while should be "Your No Escape hits ...", dunno how it was on live.

**Comment by papsbug** [comment]
...didnt see it was reported, gess i was blind :P

**Comment by noisestorm** [comment]
+
