### ISSUE TITLE
Tome of Knowledge bugs

### ISSUE THREAD

**Issue by Maginistor** [WarEmu/WarBugs#17244]
Greetings.

I have been struggling with weird bug. My Tome of Knowledge is not working. This bug exists on every character.  None of the buttons aren't clickable. 
I'm using VinyUI addon pack & I thought that could be the reason. So I did remove my addons & bug is still there.
Any Ideas how to fix this? Would be nice to abandon some quests.

Thanks for your time and assist.

![rorbugg](https://user-images.githubusercontent.com/67546594/85948542-1f353f80-b95a-11ea-9bbf-c3eb5f76b3c8.jpg)

**Comment by Kaelang** [comment]
This is one for Support on the forums - however a Repair might help.
