### ISSUE TITLE
Ironbreaker Shield Sweep ability

### ISSUE THREAD

**Issue by TDNB-TaG** [WarEmu/WarBugs#17247]
Shield Sweep Ability for the Ironbreaker:

**Expected behavior and actual behavior:**
Expected behavior: Tooltip states that it will hit up to 3 targets and restore 10 grudge for each target hit.

Actual behavior: Two Issues:
1. I've tested it hitting 4 targets for full damage
2. Restores only 10 grudge regardless of number of targets hit. (Seems to only restore the grudge for hitting targeted enemy)
Hard to confirm that it restores any grudge due to being hit afterwards generating additional grudge.

**Steps to reproduce the problem:**
Use the ability in combat with enemies.

**Testing Screenshots/Videos/Evidences (always needed):**

![Hitting 4 targets](https://user-images.githubusercontent.com/65163253/85967259-64fb1200-ba05-11ea-8f3d-a1d1bac0b9d9.png)

![Grudge restore](https://user-images.githubusercontent.com/65163253/85967134-10f02d80-ba05-11ea-866e-1d5c6d5b8847.png)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/15634

Duplicate, see above.
