### ISSUE TITLE
2 rewards for tier 1 crypt influence

### ISSUE THREAD

**Issue by Ultimaterorrior** [WarEmu/WarBugs#17241]
I chose fate of tolya for my tier 1 reward in Altdorf. I then traded it for Nightless and when I went back to the influence reward giver I was able to choose another reward. The screenshot below shows that I have both weapons with only enough influence for 1.

![Screenshot (26)](https://user-images.githubusercontent.com/67522321/85932240-4e837800-b898-11ea-9856-f3ac8a7ebc6a.png)

**Comment by Rydiak** [comment]
There are two separate NPCs that provide influence rewards for the city dungeons.  You can get a total of 4 city weapons (2 from each of the 2 tiers).

**Comment by Ultimaterorrior** [comment]
Ohhhh, cool thanks. I wanted to use Tolya skin on Nightless but didn't want
to get in trouble for it.

**Comment by Lheana** [comment]
I guess this is not an issue then, so I close it.
