### ISSUE TITLE
Despair's Preservation Proc - Sorc Weapon 

### ISSUE THREAD

**Issue by iceydealer** [WarEmu/WarBugs#17248]
**Expected behavior and actual behavior:**
Expected: When hit and the weapon procs, gain 110 wounds.

Actual: When hit and the weapon procs, only 80 wounds is gained.

**Steps to reproduce the problem:**
Get hit while the weapon is equipped

**Testing Screenshots/Videos/Evidences (always needed):**

![weapon](https://user-images.githubusercontent.com/67574141/85976928-96de8b00-b9a9-11ea-9358-6389ae414343.png)
![buff](https://user-images.githubusercontent.com/67574141/85976933-98a84e80-b9a9-11ea-8518-f19e9a744f7e.png)

**Comment by Kaelang** [comment]
Issue with proc - see https://github.com/WarEmu/WarBugs/issues/14920.
