### ISSUE TITLE
Revoltin' Gobbos PQ

### ISSUE THREAD

**Issue by jwinzeler** [WarEmu/WarBugs#17243]
During stage 1 of the Revoltin' Gobbos PQ you are to kill 125 Moonfang Goblins.

There are a lot of Goblins in the area (both "Moonfang Stickpointa" and "Moonfang Headhitta") that will, on kill, pop up a +influence text, but not count towards the PQ or actually give any influence. Most of the area back towards Mount Gunbad does not seem to count towards the PQ, but also a fair amount of packs in the middle of the zone, among others that do count.

**Comment by Kaelang** [comment]
This is still working for me - not all the Goblins do count - but not all of them need to count. The ones required are tracking correctly and have been updated in recent patches to ease completion.
