### ISSUE TITLE
White Lion 4 piece Vanq bonus not working correctly

### ISSUE THREAD

**Issue by Thoraxel** [WarEmu/WarBugs#17240]
I was playing on my White Lion Thiandrilite and was testing out my damage on the targets in altdorf when i came accross this issue. My weapon skill should be getting increased by 110 when it triggers from my 4 piece Vanq armor set but it is only being increased by 80. There are screenshots below showing this. I also believe it isnt decreasing the opponents toughness by 110 and only decreasing by 80. The buff on the target said reduced by 80 ( forgot to screenshot) but i cant see what they actual stats of the target are so i dont know. Its only a few stats but it is wrong and could make a small difference in fights.

White Lion Vanq armor:
![image](https://user-images.githubusercontent.com/67516894/85928456-0a4aa480-b8a5-11ea-8d57-5efb465c5d2e.png)

Weapon skill before the bonus:
![image](https://user-images.githubusercontent.com/67516894/85928479-2fd7ae00-b8a5-11ea-8ea4-e04ce27c2a1c.png)

Weapon skill after the bonus:
![image](https://user-images.githubusercontent.com/67516894/85928470-23535580-b8a5-11ea-961d-60cfc604ac96.png)

The buff it shows I am getting:
![image](https://user-images.githubusercontent.com/67516894/85928496-40882400-b8a5-11ea-973d-782d64f04db6.png)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17064
