### ISSUE TITLE
City crashes causing Quitter. 

### ISSUE THREAD

**Issue by tect1** [WarEmu/WarBugs#17257]
Last night i crashed at start of IC city defense and when I reloged I tried to get back into the instance and pressed join.   I received quitter debuff and couldn't join till after debuff.
Today I solo queed for altdorf and clicked join when prompted and I wasn't able to join and received quitter debuff.

Talked to a gm and was told to post on bugtracker.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by barfyman92** [comment]
something similar happened to me today. 
I joined a city, all is well for the first stage up until it's finished, then I immediately crashed out of the game. I logged back in to a green screen with a city pop on the right side of my screen like normal. I clicked enter, nothing happened for a  short while, screen goes back to normal and a few moments later I get 10 min quitter debuff.

Using "/script BroadcastEvent( SystemData.Events.SCENARIO_INSTANCE_JOIN_NOW )" didnt work while i had quitter, though it might have if i entered the script during the 1-2 min window before i got the debuff. Once I had it, it said there was no que pending.

The guys i was in city with finished stage 2, my quitter expired and I got a new pop. I got back in, finished stage 3 and got crashed out of the game yet again. 

I'm not sure what causes it, this stuff only ever happened to me once. I suggest you remove quitter debuff from city for now. 
(would really advice you to remove it from everything in general but thats another story)

**Comment by Syzako** [comment]
The script is applied even during combat and applies to the normal scenario.

**Comment by termofor** [comment]
We had 2 people that DCd and were not able to move back to City Instance. Loading screen looked like picture below and after a while moved that person out of instance and quitter debuff added.

![image](https://user-images.githubusercontent.com/80748880/150982690-fd8ffa4a-537a-45e9-affc-a6393430dd36.png)

**Comment by lilimx** [comment]
Fixed around the Patch from 28/1/2022
