### ISSUE TITLE
[Auction House] My items don't appear on the auction house?

### ISSUE THREAD

**Issue by Sciberr** [WarEmu/WarBugs#17258]
An introduction:

I'm selling armor pots on the AH and they don't appear on the list.

Details:

Even though they are the cheapest on the list they aren't there.

Evidence:

https://youtu.be/Q_M8RHy8D7w

Additional Information:

N/A

How to reproduce the bug:

Put something on the AH

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/14566
