### ISSUE TITLE
[BW] Wildfire not working with Flame Breathe

### ISSUE THREAD

**Issue by detrap** [WarEmu/WarBugs#17250]
![Screenshot 2020-06-29 22 04 05](https://user-images.githubusercontent.com/64330047/86003243-df9f4e00-ba54-11ea-8b24-92127ab6bf3c.png)

25% chance to proc with any ability from in the conflagration tree:

![wildfirebug2](https://user-images.githubusercontent.com/64330047/86003329-f47be180-ba54-11ea-95cb-516e6aeee742.png)

Does not proc at all with flame breathe

**Comment by Kaelang** [comment]
Flame Breath is a dot, not damaging + DoT.
