### ISSUE TITLE
Cannot submit the quest due to non-existing inventory overflow

### ISSUE THREAD

**Issue by raig100** [WarEmu/WarBugs#17259]
Hi there! Finished the quest, but cannot submit it to the quest-giver, the game tells me Inventory overflow, cannot salvage, open ur backpack etc.. In fact i dont have overflow
![image](https://user-images.githubusercontent.com/65672202/86279584-ecea4300-bbe2-11ea-9c2a-f10a42bcbbb5.png)

**Comment by Lheana** [comment]
Maybe your currency inventory?

**Comment by raig100** [comment]
> Maybe your currency inventory?

No, the reward is the jewerly item(
And have 8 slots in both general and currency inv((

**Comment by raig100** [comment]
![image](https://user-images.githubusercontent.com/65672202/86287367-bc110a80-bbf0-11ea-995f-8ae18f3c9d87.png)

**Comment by Lheana** [comment]
Have you set item preference in your inventory?

**Comment by raig100** [comment]
No, does this help?

**Comment by Lheana** [comment]
I don't know, I thought it could be the reason of the issue. Note nevertheless that I tested this quest and it worked fine for me.

**Comment by raig100** [comment]
I had overflow during the boss raid, but i cleaned the inventory straight after that. I will try to set the preference, see if it can help

**Comment by Lheana** [comment]
Had you logged out and in back after the raid where you had overflow?

**Comment by raig100** [comment]
Yes, had done full log out and log in

**Comment by raig100** [comment]
Tried relog, as well as creating overflow and cleaning it didnt help

**Comment by colintgallagher** [comment]
Might be weird but whenever I have inventory bugs I close all the bags by clicking on the icons then re-opening them.

**Comment by raig100** [comment]
Solved by re-doing the quest. Might be painful, double-check such thing IFI.
