### ISSUE TITLE
Getting to areas that are not ment to be gotten to

### ISSUE THREAD

**Issue by Carcharadon** [WarEmu/WarBugs#17254]
players on top of a area ( tower) on a BO in saphray 

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

in the image i attached you can see the player behind his pet i have highlighted 
![WAR-64 2020-06-29 17-43-28](https://user-images.githubusercontent.com/55959616/86063619-e320de00-ba30-11ea-9730-9bcd55533932.png)
![WAR-64 2020-06-29 17-43-28](https://user-images.githubusercontent.com/55959616/86063804-4c085600-ba31-11ea-89cc-ec0cd938d90e.jpg)
![ss](https://user-images.githubusercontent.com/55959616/86063818-5296cd80-ba31-11ea-95f2-474739ab30a1.png)

**Comment by Rockalypse** [comment]
Spot is easily reachable and is presented in most elven rvr zones, fix not needed.
