### ISSUE TITLE
Suspiciously high crit dmg multiplier

### ISSUE THREAD

**Issue by Thoraxel** [WarEmu/WarBugs#17261]
Was playing on my slayer today after the new patch when I noticed some messages coming up in my chat. They were appearing when I was dead and my dots we hurting an enemy after I had died. I asked a GM that was on at the time if I should be worried about it and they said no but to submit this report to get it fixed. 

I’m not sure exactly how to recreate what happens because I’m just playing like I normally do when it happens but I think it is from my dot inevitable doom.

![14438103-BC48-462F-8798-4D1A47DCFDC6](https://user-images.githubusercontent.com/67516894/86306755-f7213700-bc0c-11ea-9a26-055036525f32.jpeg)

**Comment by SilverWF** [comment]
This error here was since a long ago. #15925
Just slot Fierce Might tactic (seems you have it in 4th slot) and try to hit someone while on low HP - your chat would be filled with that errors

**Comment by Thoraxel** [comment]
Ok that makes sense, forgot that I had just changed my build earlier that morning and was running that tactic
