### ISSUE TITLE
[WL] Cleave Limb AP cost

### ISSUE THREAD

**Issue by shaggy996** [WarEmu/WarBugs#17262]
The WL cleave limb snare ability was recently changed to homogenize it with the other MDPS snares in game. The reuse time was doubled and the duration was halved, but the AP cost was left higher than all other snare abilities at 30 AP. 

AP cost of all other snares is 25, cleave limb should be reduced to 25 to match.

**Steps to reproduce the problem:**

![cleave limb](https://user-images.githubusercontent.com/67753767/86388876-57829980-bc4a-11ea-8126-5568699c5813.jpg)

**Comment by Kaelang** [comment]
This is feedback - use the forums please.
