### ISSUE TITLE
Oppressor Taen & Vanquisher Taen not showing on character when equipped

### ISSUE THREAD

**Issue by detrap** [WarEmu/WarBugs#17276]
Oppressor Taen & Vanquisher Taen not showing on character when equipped.

How it should look like since the changes made on this post: https://www.returnofreckoning.com/forum/viewtopic.php?f=11&t=37911

![U6nuAe0](https://user-images.githubusercontent.com/64330047/86595520-31f3e800-bfdc-11ea-97e0-803ef295ca57.jpg)

What shows in-game:

![Desktop Screenshot 2020 07 06 - 22 54 09 19](https://user-images.githubusercontent.com/64330047/86595417-0a9d1b00-bfdc-11ea-9a22-b43b0002448b.png)
![Desktop Screenshot 2020 07 06 - 22 53 45 06](https://user-images.githubusercontent.com/64330047/86595420-0b35b180-bfdc-11ea-8a99-bc70f8ec9e4b.png)

**Comment by Kaelang** [comment]
This is a known and listed report.

**Comment by detrap** [comment]
Sorry I bought the Opp Taen to confirm it also was having the same issue as the Vanq one
