### ISSUE TITLE
Death while alive bug from leaving SC's

### ISSUE THREAD

**Issue by FungleBunch** [WarEmu/WarBugs#17270]
**Summary**
I was in a PQ zone with a friend queued for SC's, loaded into Mourkain Temple (not sure if that sc specifically or maybe all?), as the match ended i left immediately because i was low hp (made it before death), once I loaded back into the PQ zone I was dead on the ground with an option to respawn. CLicking respawn removed the respawn box and nothing else, i was a corpse on the ground unable to move or cast or anything. On my friends discord stream he saw me just standing up with nothing abnormal. Eventually a enemy npc ran up and slowly killed me while still (dead) in place (shown in gyazo gif below). Once my healthbar depleted fully I got another respawn box that functioned correctly this time.

   **Expected behavior and actual behavior:**
Should've loaded back into PQ zone alive after completing SC
Once leaving the loading screen from a SC into a PQ zone, I had a respawn button that disappeared when clicked and did nothing. Had no control whatsoever over my character until a npc killed me while stuck to the floor "dead" and the second respawn button functioned correctly.

   **Steps to reproduce the problem:**
I believe I died to dots during the loading screen and may have forced the game to think I was both alive (in pve) yet dead (in pvp) at the same time. So leaving a finished SC with low hp and dots so you die in loading may reproduce the bug.

   **Testing Screenshots/Videos/Evidences (always needed):**
https://i.gyazo.com/d22d7dee9e3720c7412cd4a21c81953d.mp4
(Couldn't upload it as a mp4 so here's the gyazo link for the gif)

If the gyazo link isn't sufficient I'll get something to convert it to your preferred file type since mp4 didn't work. Thank you for your time and if there's any questions I can answer i'm more than willing to help out. Thanks for reviving this game, missed the live version and really really enjoying the private server!!

**Comment by Kaelang** [comment]
Known issue and already reported.
