### ISSUE TITLE
[Scenario] window for queueing does not open on click

### ISSUE THREAD

**Issue by Koriace** [WarEmu/WarBugs#17277]
On click, the window for single queueing scenarios doesn't open.
If in a party, the leader (not me) can register the full party. Didn't tested in a warband.
When scenario pop. The pop-up is not visible and I can't join. After the timeout I receive "properly" the coward debuff.
With a script ". script (...)" in chat, I was able to join a scenario.

I tried to repair game, restart, reload, but nothing fixed the problem. 

video .MP4 in .zip file attached.
[ROR_SC.zip](https://github.com/WarEmu/WarBugs/files/4881298/ROR_SC.zip)

**Comment by Kaelang** [comment]
This is a known issue - there is a script widely available to use if this happens.
