### ISSUE TITLE
KotBS Sovereign chest Offset item icon bug

### ISSUE THREAD

**Issue by silodin** [WarEmu/WarBugs#17271]
**Expected behavior and actual behavior:**
Should be just the sov chest icon. displays as boots.

**Steps to reproduce the problem:**
equip the knight sovereign dps set chest and check your character window

**Testing Screenshots/Videos/Evidences (always needed):**

https://gyazo.com/ad953c43c7bc94a4d5ea63998e6dde35

**Comment by Kaelang** [comment]
Known and reported issue.
