### ISSUE TITLE
Chalice of the Subjugator

### ISSUE THREAD

**Issue by Vendatha** [WarEmu/WarBugs#17275]
I have started using a Chalice of the Subjugator level 56 and i have notice that it doesn't recover the 8 soul essence per second until after combat finishes, if i use my Apostle's chalice of vehemence 46 it recovers the 8 soul essence just fine.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
You need to requip the chalice.

**Comment by Vendatha** [comment]
Hello.

I have tried the chalice over three days in the RVR lakes and in SCs and
each time combat is joined the chalice does not generate soul essence.
I have re-equiped it as you asked and tried in the RVR lake and it still
does not work.
As soon as the combat ends it begins returning soul essence.
