### ISSUE TITLE
T4 Epic Quest Completion

### ISSUE THREAD

**Issue by Thoraxel** [WarEmu/WarBugs#17284]
A guild member of mine came to me with this issue and asked if I could do a bug report on it. Their character name is ‘Araldon’

They have finish all the quests within the T4 Epic quest “” but when they go to hand in the final quest to get the weapon reward it won’t let them. They can select the weapon they want to receive but when they click complete nothing happens. 

![D9B85FC7-E3D0-499B-8917-4462D4A04F1D](https://user-images.githubusercontent.com/67516894/86906851-10921980-c10c-11ea-86a3-c3662a4a7092.jpeg)

**Comment by Kaelang** [comment]
Relogging / Clearing cache etc should work. If not - please re-open after seeking support on the forums / Discord.

**Comment by Kaelang** [comment]
Re-opening as seems to be related to the maximum amount of items cap on quests.

**Comment by Kaelang** [comment]
Fixed in todays patch.
