### ISSUE TITLE
The map pairings all just reset incorrectly.

### ISSUE THREAD

**Issue by velenne** [WarEmu/WarBugs#17283]
**Expected behavior and actual behavior:**
Earlier today was a 5star altdorf.  When the 2nd fort fell, a 3rd fort in Reikwald was engaged but failed, causing the empire/chaos pairing to reset to Praag WHILE the city was engaged.  When the city completed, the pairing never reset to Ostland/Troll Country; it stayed as Praag.

The day continued until just now with the pairing falling at the Maw.  Suddenly the entire T4 RvR reset and we lost progress in the elf and dwarf pairings.

**Testing Screenshots/Videos/Evidences (always needed):**

During City:
![image](https://user-images.githubusercontent.com/65675974/86863126-2bbf4380-c090-11ea-9088-e52d8e175afc.png)
After City:
![image](https://user-images.githubusercontent.com/65675974/86863149-38dc3280-c090-11ea-8311-74a6f29983ba.png)
Now:
![image](https://user-images.githubusercontent.com/65675974/86863167-45608b00-c090-11ea-90f4-f21988b2fa9c.png)

IGN: Taqindra

**Comment by dalen** [comment]
This should be fixed with todays patch. Required kind of rare circumstances to trigger though
