### ISSUE TITLE
my tome of knowledge is buged

### ISSUE THREAD

**Issue by solutoironlord** [WarEmu/WarBugs#17287]
![2020-07-09](https://user-images.githubusercontent.com/63125324/87204706-18e48300-c2cb-11ea-955b-10b08d043e5a.png)

i have put up with it for a week now and it happens ever time i log in all of the pages are in one and no matter what i do it just stays the same
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**
not sure it just happened

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
Screenshots and more details please.

**Comment by ProphetROR** [comment]
I have the same problem ; i can not really give any more details, all i can say is that, when I open the book, that is what i can see ; even if I try to go to the armory or the information part for example
![Bug book of knowledge](https://user-images.githubusercontent.com/68502855/87876380-1d4e2180-c9d8-11ea-9b7d-4af721f6f40d.jpg)

**Comment by Kaelang** [comment]
This is a client issue, not a game issue. Repairing / reinstalling should fix.
