### ISSUE TITLE
Festering arrow can be cast while no stance is active

### ISSUE THREAD

**Issue by DanskuL** [WarEmu/WarBugs#1728]
As you log in the SW doesn't have a stance activated, while not having a stance active you can still cast festering arrow, haven't tried with other spells that are in the "Mastery" trees but if you can cast all of your mastery specced abilities when in "No stance" that might be a major bug (currently it's trivial since festering arrow does less damage in this stance but if others spells are affected by this as well it might be an issue).

The core abilities do not seem to be affected by this (I.E eye shot or rapid fire f.ex. can not be used while in this "stance").

Issue may be related to stances and mastery abilities I've only tried with SW career, but there might be other careers that are affected.

**Comment by Evildoor** [comment]
Festering Arrow has "Requires Scout Stance" stated in its tooltip, right? (I'm asking since i can't access the game or warbuilder now)

**Comment by DanskuL** [comment]
yes it's supposed to require Scout Stance
