### ISSUE TITLE
Oil Spawn Misplaced in Covenant of Flame Keep

### ISSUE THREAD

**Issue by detrap** [WarEmu/WarBugs#17285]
Dragonwake Keep: Covenant of Flame (Outer Wall)

When oil is spawned, it is placed below, inside of the main doors. It is still accessible and can damage the enemies as well as receive damage as well, might be a visual bug for one realm of players (in this case order), as the oil was still able to be hit from enemy players outside of the keep.

Video:

https://streamable.com/yru026

Screenshot of oil room above main doors on outer wall, order players trying to spawn oil, not knowing it did below them.

![Desktop Screenshot 2020 07 08 - 21 04 07 91](https://user-images.githubusercontent.com/64330047/86911816-46142280-c15f-11ea-908e-1a1d4e081df9.png)

**Comment by Kaelang** [comment]
This is a known issue - however replication is difficult.
