### ISSUE TITLE
[Gunbad][Quest][Mourkain Crystal/Squig Faced]

### ISSUE THREAD

**Issue by Aluviya** [WarEmu/WarBugs#17280]
**Expected behavior and actual behavior:**

1. The lootitem "Mourkain Crystal" generates, if used, a questitem for destro which is only useable for order? (seems not intended)
2. the questitems for both quests "Mourkain Crystal" and "Squig Faced" are not consumed after handing the quest in and persist in the inventory (with no further use)
<img width="547" alt="Unbenannt" src="https://user-images.githubusercontent.com/17249318/86776574-9a80aa80-c058-11ea-942b-58ab8bba87c6.png">

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kabucoror** [comment]
fixed with next patch
