### ISSUE TITLE
Critical Hit Rate is Multiplicative? 

### ISSUE THREAD

**Issue by BurnSetting** [WarEmu/WarBugs#17293]
**I asked on discord first and checked forums. No one has any good answers as far as I can tell. Foofmonger sent me here**

**Expected behavior and actual behavior:**  I've been told that Critical Hit Rating is supposed to apply to all Critical Hit types (Melee, Magic, and Healing) - and it does!!  But the "+2% Critical Hit Rating" on the King's Bounty Sigmarite Kit Helm and Fists do not add a flat 2%. The result seems to be multiplicative and not additive.

**Steps to reproduce the problem:**
Equip the set pieces and you will see - Your critical hit percentage goes up 2% of what it was prior to equipping the item. ie- if you had 25% Melee Critical Hit Bonus then you go up .5% in your Melee Critical Hit Bonus. 20% = .4%, 10% = .2%, etc.
---- Please note that the 2% multiplicative effect DOES work with all your crit chances at the same time. They all go up a small percentage. ------

**Testing Screenshots/Videos/Evidences (always needed):**

![fist stats](https://user-images.githubusercontent.com/68092549/87185012-06f8e500-c2b7-11ea-8110-e6a02fa8fa7b.jpg)
![Helm stats](https://user-images.githubusercontent.com/68092549/87185020-0a8c6c00-c2b7-11ea-96aa-92525ffd3a79.jpg)
![Chance to crit without](https://user-images.githubusercontent.com/68092549/87185026-0c562f80-c2b7-11ea-84ab-8fccd980c2d4.jpg)
![Chance to crit with just fists](https://user-images.githubusercontent.com/68092549/87185030-0e1ff300-c2b7-11ea-8fdc-a023031ceced.jpg)
![Chance to crit with both](https://user-images.githubusercontent.com/68092549/87185035-0fe9b680-c2b7-11ea-9ed6-27185258ee29.jpg)

I just want to get 4% extra crit chance! Thanks and I hope I learn if this is working as intended or if it needs fixing.

**Comment by Rydiak** [comment]
https://github.com/WarEmu/WarBugs/issues/17148
