### ISSUE TITLE
[Sovereign] 7-pieces IB bonus doesnt work as intended

### ISSUE THREAD

**Issue by tquere** [WarEmu/WarBugs#17295]
Hello,
The 7-pieces defensive sovereign IB bonus doesnt work as intended.
The game indicates: "On Being Attacked: 10% chance to increase Parry, Block, Disrupt and Doge by 10% for 10 seconds".

Well, it doesnt work like that and it is totally useless as it is.

Without the proc on, those are my defensive stats:
![7PiecesOFF](https://user-images.githubusercontent.com/32341239/87219420-382af100-c35b-11ea-8c4f-48600edeeb4f.png)

With the proc, what they become
![7PiecesON](https://user-images.githubusercontent.com/32341239/87219424-44af4980-c35b-11ea-9864-1640a016af93.png)

As you can see, it is not a flat +10% ... it is just a x 1.1 multiplier ... 
Meaning that the bonus only gave me:
+3 block, +1 parry, +0 dodge and +0 disrupt.

It cannot be normal. 
And, anyway, if it is normal, you should precise it in the bonus tooltip. I mean, lots of things give flat bonuses, how are we supposed to know that this one gives ridiculous multiplier bonus.

Thanx

**Comment by Kaelang** [comment]
This should have been fixed with today's patch.
