### ISSUE TITLE
Wrong Icon for Pummelers of the Ravener

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#17298]
This is a minor issue.
Earlier I had a Pummelers of the Ravener drop. This is a set of gloves that has a boot icon currently (I checked this on a zealot, chosen, and marauder). This should instead have a gloves icon.
![Yttria_028](https://user-images.githubusercontent.com/13975292/87239521-ae6c3980-c3d5-11ea-9fee-494e1569a610.jpg)

**Comment by Kaelang** [comment]
Fixed in todays patch.
