### ISSUE TITLE
City Stage 2 NPC Lord Flag Capture "Pacing"

### ISSUE THREAD

**Issue by Rainygamer** [WarEmu/WarBugs#17291]
Hello,
Please find the link to the attached spliced video here: https://youtu.be/iwSxuViLkSE
The videos are from two different cities which happened inside this last week... thus the splice.

You can clearly see in the first section that the Order lord arrives at the flag, 10-15 seconds go by, the game text informs us that he has arrived, he kneels down, and proceeds to capture which takes... a while.

In the second part of the clip you can see the Destro lord arrive, pause for a frame and then proceed to keep running. However, he does not visually capture the flag.

I would expect that Lords are intended to stop at BOs and capture them over a set time period with then the capture then registering.

Thanks.

**Comment by Kaelang** [comment]
Already reported - but thank you for letting us know.
