### ISSUE TITLE
gained 6k gold

### ISSUE THREAD

**Issue by warhunter69** [WarEmu/WarBugs#17294]
when i was killing the lord in shinning way i almost crashed and i go massages saying i received 6k gold and another 3 saying i got 100k gold but i only got the 6k in my bag how ever after leaving for and going to altdorf city queuing area my gold returned to normal 
![b1](https://user-images.githubusercontent.com/34657198/87194120-71cb1000-c2f9-11ea-9a50-48876cef34a5.jpeg)
![b2](https://user-images.githubusercontent.com/34657198/87194141-74c60080-c2f9-11ea-9d00-8908fb04657e.jpeg)

**Comment by Kaelang** [comment]
Packet issue with lag / DCs. The gold was never there.
