### ISSUE TITLE
Dots been applied on keep door

### ISSUE THREAD

**Issue by Aktheon** [WarEmu/WarBugs#17303]
**Expected behavior and actual behavior:**
Expected:
been impossible to apply dots on keep doors
Actual:
Engineer's "Acid bomb", "Fragmentation grenade" and "napalm grenade" dots been applied on keep doors
People say RP's dots also apply on keep doors (could'nt get those screenshots yet, will attach asap)

**Steps to reproduce the problem:**
unknown, might require abuse of game mechanics to apply dots. Attempts to apply dots using Magus have failed.

**Testing Screenshots/Videos/Evidences (always needed):**
![Akteon_000](https://user-images.githubusercontent.com/10299106/87268154-60892b80-c4d2-11ea-806a-97e4c2b752f1.jpg)
![Akteon_001](https://user-images.githubusercontent.com/10299106/87268156-641cb280-c4d2-11ea-92ad-d6d7bc9bda13.jpg)

**Comment by Kaelang** [comment]
This is known. I’m going to close this so it isn’t replicated on live.
