### ISSUE TITLE
Nordland/Ostland - Merchant - Mule duplicate

### ISSUE THREAD

**Issue by OskarSniper** [WarEmu/WarBugs#17305]
**Expected behavior and actual behavior:**
Expected:
Only one Mule is listed

Actual:
Two mule's are listed and available for sale

**Steps to reproduce the problem:**
1. Go to Nordland
2. Go to Merchant
3. Trade with him

**Testing Screenshots/Videos/Evidences (always needed):**
![nordland-mule-duplicate](https://user-images.githubusercontent.com/6827409/87282535-a951dc00-c4f4-11ea-925e-d9435c375118.png)

**Comment by OskarSniper** [comment]
Same in Authun's Host (57672, 18030)

**Comment by OskarSniper** [comment]
Same in Ostland, Ferlangen (9102, 28151)

**Comment by Kaelang** [comment]
Fixed in todays patch.
