### ISSUE TITLE
Braewold not spawning for Norsca quest "The Dark One"

### ISSUE THREAD

**Issue by anatole1173** [WarEmu/WarBugs#17301]
**Expected behavior and actual behavior:**
The NPC you have to kill for the Norsca quest "The Dark One" named "Braewold" is not spawning inside of his cave, 'Tomb of Ravenborne'. I confirmed his spawn location with other players but he is not there, and has not spawned after about a half hour. Have seen other players come and go looking for him, but he's just not there. 

![image](https://user-images.githubusercontent.com/68197960/87252698-2de42200-c443-11ea-8236-5cd6cd60ad3c.png)

**Comment by Lheana** [comment]
Someone must have pulled him and he was above the cave. He is now back again.
