### ISSUE TITLE
T4 influence chalice is missing stats.

### ISSUE THREAD

**Issue by Zxul** [WarEmu/WarBugs#17300]
**Expected behavior and actual behavior:**
T4 influence chalice had 36 toughness/wounds and +100 elemental/corporeal resistances, now it has 32 toughness/34 wounds and no resistances.

**Testing Screenshots/Videos/Evidences (always needed):**

https://img.techpowerup.org/200712/1111111111111.png

**Comment by wargrimnir** [comment]
This looks like an intentional change, no other purple T4 RvR influence items have resists. The R31 variants do, which is probably fine as people are unlikely to choose them anyway.
