### ISSUE TITLE
I didnt reserve verification email.

### ISSUE THREAD

**Issue by RunAwaySkill** [WarEmu/WarBugs#1730]
I created account 1 day ago and still didnt reserve verification email,but when i try registrate again it says that email already used.
My email runawayskill@gmail.com
Best regards Runa

**Comment by Evildoor** [comment]
This is the bugtracker, place for game bugs. Issues like this belong to "Technical support" section of the forum, not here. Also, FYI - currently the forums experience some problems, which have to be resolved before services, including verification emails, could work properly.
