### ISSUE TITLE
PQ and bag bugged

### ISSUE THREAD

**Issue by kudplomb** [WarEmu/WarBugs#17306]
-->
 hello i ve a real big bug on all my characters , i can't see PQ reward on rally master on each chapter, can't see nothing on my war diary too, no chapter selection, nothing, just an empty  page, so i can't end zone PQ and choose a reward.At rally master i ve only grades names and nothing else,  no icons, no selection avaibles, no description only .... white. In Rvr  no bag drop and no bag increase roll. always roll 1..... please can you fix that ?

**Comment by Lheana** [comment]
It is not a game issue, just an issue on your side. Try the "Repair" function on the launcher, something must not have been correctly updated for you.

**Comment by kudplomb** [comment]
trying repair, problem stay same, no PQ, no bag roll, no view on rally master.
