### ISSUE TITLE
Draining Swipe Cooldown wrong?

### ISSUE THREAD

**Issue by Stompah** [WarEmu/WarBugs#17302]
The ability reads as a 20 second cooldown. It starts at 20 sec and instantly drops down to 10 sec (the opposite of what Thunderous Blow does).
![Cleganes_001](https://user-images.githubusercontent.com/68201609/87260288-ad3f1900-c476-11ea-8265-4830efde88ea.jpg)

**Comment by Kaelang** [comment]
This is a tooltip issue afaik.

**Comment by Foofmonger** [comment]
This is a tooltip issue. Draining Swipes was changed on this server to have a 10 second cooldown and 5 second duration (intentional change, old patch notes), but the tooltip wasn't updated. 20 second cooldown/10 sec duration is how the ability functioned on live.
