### ISSUE TITLE
Cannot log out

### ISSUE THREAD

**Issue by Bugz123** [WarEmu/WarBugs#1731]
If I press either log out or exit game, the timer goes down to 5 seconds, and then nothing happens. 
The surroundings disappear, but I am still logged in. 
I have to end task the game to log out.

**Comment by milosxe** [comment]
This happens to me as well, and more people reported it.

**Comment by ozarmidrashim** [comment]
I changed the disposal mechanics recently. A side effect is that Dispose() can't be called from within an event. I thought I'd changed all the instances, but logout for non-GM characters is the last remaining one.
