### ISSUE TITLE
[Altdorf] Stuck in boxes

### ISSUE THREAD

**Issue by Aluviya** [WarEmu/WarBugs#17311]
In the siege of AD at 20k 50k there are some boxes on the floor on which you can stuck without beeing able to free yourself without forcing a game crash. These should be removed as you can fall into these boxes from the upper floor or get punted into it.

<img width="285" alt="Unbenannt" src="https://user-images.githubusercontent.com/17249318/87403525-424c2a00-c5bd-11ea-95e5-edaf021cfb52.png">

**Comment by dalen** [comment]
semi fixed in todays patch by allowing /stuck command in scenarios and city sieges

**Comment by MaxHayman** [comment]
Going to close this as we have a fix for stuck issues in scenarios.
