### ISSUE TITLE
Stuck in the water after being bumped-city docks-

### ISSUE THREAD

**Issue by kish4n** [WarEmu/WarBugs#17320]
All is in the title, nothing have been added to climb and come back in the city when u are bumped in the water(east altdorf).

**Comment by Kaelang** [comment]
I'd need images / locations.

**Comment by MaxHayman** [comment]
We could flag the water for insta death?

**Comment by wargrimnir** [comment]
Dangerous Water was a thing on live when you got too deep. It started ticking something like 1000 damage per second. Well geared healers could heal through it to explore the edges of the map. Eventually they just ported you out of DT zones because people were finding things.

**Comment by MaxHayman** [comment]
Going to say the solution is the new /stuck logic.
