### ISSUE TITLE
City not rewarding invader meds for stages // game performance issues after patch. // invite bug // tell bug 

### ISSUE THREAD

**Issue by nnnnNATHANnnnn** [WarEmu/WarBugs#17321]
**Expected behavior and actual behavior:**
I expected to get invader medallions for winning stages in city. I didn't get any. Bags are working as intended.

**Steps to reproduce the problem:**
win a stage in city **without** having the invader TOK so that you can get royals. 

**Testing Screenshots/Videos/Evidences (always needed):** 
https://www.youtube.com/watch?v=yOFI1uqeheA

Apologies for semi long video, during the end you can see I show my currency bag and how many invaders I have and you see when the stage is over I don't get any meds. I know this can't be helped just reporting to fix the issue for the future. 

you will notice in the video the game is running extremely poorly, this is due to some issue with the patch that was just rolled out before this. Before my games performance completely broke I had just finished the fort(where my game was running beautifully even with the large numbers in fort), I re logged after it, and once I got back the games performance went down the drain. The reasoning as far as I can tell is the game was trying to install a patch while running. Relog after city caused the game to do a manifest / patch which fixed tooltips on abilities and potion bar addon but the games performance is still completely gone. I have yet as of writing to log back in and see if it patches again to fix it. 

P.S Before city happened for some reason people who relogged were not able to receive invites from others into warbands, the issue seemed to only happen to anyone who relogged after fort while people who didn't relog were fine and could be invited. The workaround was to open the warband, join quickly, and close it again. The people who couldn't get invites also couldn't receive tells from others, but were able to send tells to others.

**Comment by Kaelang** [comment]
There was an issue shortly after this city that was patched and fixed which likely caused this issue. Please re-open if issue persists. Additionally, the other notes are more for Technical Support on the forums.
