### ISSUE TITLE
Rare Craftsmanship quest in Avelorn

### ISSUE THREAD

**Issue by kidjo** [WarEmu/WarBugs#17325]
Hello!
I dont know if this is a bug or if it is intended but the "Rare Craftsmanship quest" cannot be turned in, it isn't even shown in the npc's ( Syth Orealian's) dialogue options, also it rewards only xp while i remember that it used to reward dark navy blue dye aswell (it was a repeatable quest from which you could farm the aforementioned dye)!

![Ancalanthir_000](https://user-images.githubusercontent.com/13076382/87651557-52960d80-c753-11ea-9293-1d29e114390f.jpg)

**Comment by Lheana** [comment]
Nothing wrong here. Follow the instructions of the quest.
