### ISSUE TITLE
Skill: Sigmar's Vision (&I assume the DoK Equivalent) does not increase Block. 

### ISSUE THREAD

**Issue by 13eara** [WarEmu/WarBugs#17328]
Sigmar's Vision does not increase block as it should(10%+). The tooltip is also incorrect, "block chance will be increase by 0% for 0 seconds."

I tried to upload a video of it, but it's too big. I contacted Gambero to test out the DoK version for me. He said it's not working on DoKs either. 

If you need proof, contact me on discord and I can send you the file. I am 13eara on the RoR Discord. 

Thanks for your time.

**Comment by Kaelang** [comment]
"If you need proof, contact me on discord and I can send you the file. I am 13eara on the RoR Discord."

With respect - this is what the bugtracker is for.

Please upload the supporting evidence.

**Comment by Olari-Prop** [comment]
Same here,
Video on: https://youtu.be/zJiILbstsmc

hope this will help

**Comment by dalen** [comment]
This was fixed in patch
