### ISSUE TITLE
Alternate appearance does not work properly for "pauldrons of the mercenary" on conqueror shoulders on my blackguard

### ISSUE THREAD

**Issue by kidjo** [WarEmu/WarBugs#17326]
Hello!
Putting in the "Pauldrons of the Mercenary" in my shoulder armor appearance tab does not change the appearance of my conqueror shoulder armor it only changes the dye color!! I don't know if this is a widespread issue or just an issue for blackguard players.

![Ancalanthir_002](https://user-images.githubusercontent.com/13076382/87652370-6aba5c80-c754-11ea-9470-4d44789097ab.jpg)

It also only seems to affect the Pauldrons of the Mercenary, it works for other shoulders (for example the Pauldrons of Upset Ithilmar as shown in the image below).

![Ancalanthir_004](https://user-images.githubusercontent.com/13076382/87652603-b8cf6000-c754-11ea-81f8-0f8b981f318a.jpg)

**Comment by Rockalypse** [comment]
From what I see on your first screenshot - mercenary appearence IS actually applied.
![image](https://user-images.githubusercontent.com/42712833/93849697-572bf480-fcb5-11ea-8686-815220159012.png)
Check related topic https://www.returnofreckoning.com/forum/viewtopic.php?t=37911.
