### ISSUE TITLE
acces problem to guarden of qu'aph

### ISSUE THREAD

**Issue by zedebenetleilax** [WarEmu/WarBugs#17327]
hello, i didn't find anything on the forum that talks about my problem.
I cannot go to the guarden of quaph, I remain systematically blocked on the loadingscreen.
I cleaned the cache several times, I used the launcher "repair" function twice ...
nothing changes, I have to make a / stuck / stuck to get out of the loadingscreen ...
Do you have an idea of the problem ?

**Comment by Kaelang** [comment]
The bugtracker is for game related issues. This sounds like a fault with your client as other people are accessing the Garden fine.
