### ISSUE TITLE
[Fortress][Shining Way] Pillar of Hope

### ISSUE THREAD

**Issue by Aluviya** [WarEmu/WarBugs#17324]
Have seen now several times people, especially rdps bugging onto the tower on the Pillar of Hope objective in Shining Way and attacking from a point where you can't directly reach them. Also abusing it to claim the BO over and over after warbands leave as you can hide behind the tower.
Found a way to reproduce the bug check the gif. Also in several fights, I punted people down from the corner in the picture below  (no videos made unfortunately) - they managed to "crawl" into the texture so it looked like they were punted but were still standing on the same point on that tower. The tower is - as you can see at the end of the video not reachable from the side people normally see enemy.

**Testing Screenshots/Videos/Evidences (always needed):**

Spot on the tower
![Tiyuvi_021](https://user-images.githubusercontent.com/17249318/87588801-8be36480-c6e4-11ea-92d1-c668085ba4f1.jpg)
Entrace to get onto the tower at 16k 39,5 k
![Tiyuvi_020](https://user-images.githubusercontent.com/17249318/87588464-02339700-c6e4-11ea-81c2-ba47f3f41cb3.jpg)
Gif picture to show how you get onto the tower
![ezgif-1-490f953973b5](https://user-images.githubusercontent.com/17249318/87588341-c567a000-c6e3-11ea-8572-e6dc4a9847ed.gif)

**Comment by Rockalypse** [comment]
Spot is easily reachable and is presented in most elven rvr zones, fix not needed.
