### ISSUE TITLE
T3 epic quest reward

### ISSUE THREAD

**Issue by Drajika** [WarEmu/WarBugs#17334]
Elf T3 Epic quest has one handed axe reward for engineer. 

Engineer cant even equip the axe to use.

**Comment by Lheana** [comment]
Can you give the name of the item?

**Comment by Drajika** [comment]
Items Name is : Disconcordant axe

**Comment by Kaelang** [comment]
Fixed in todays patch.

**Comment by Drajika** [comment]
Ur Welcome :D and thanks for fixing! guess im a cool dwarf engineer now with that axe in inventory :D! @Kaelang

**Comment by Kaelang** [comment]
Dwarfs are never cool.
