### ISSUE TITLE
DoK's Warding strike gives +0% block with shield

### ISSUE THREAD

**Issue by KSNiki** [WarEmu/WarBugs#17332]
If i remember correctly Warding strike should give 10% block with shield. The tooltip also says 0% now. When i use it, i don't get the buff from it.
![image](https://user-images.githubusercontent.com/53081960/87781523-7f245500-c839-11ea-806b-357d4f65a23c.png)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17328
