### ISSUE TITLE
[Quest] Leading the way, Destruction @The Blighted Isle

### ISSUE THREAD

**Issue by dfumagalli** [WarEmu/WarBugs#1733]
Hello,
I have farmed the whole area (I can 1 shot the NPCs) for 15 minutes, but the Narthain Gem does not drop. I have tried both archers and Sword Novices. Instead of it, (only) the archers, drop "Shinies", a white bag that is the quest item for the other quest in an overlapping area. Shinies correctly dropped for the other quest, but even after I have turned it in, they keep dropping from the archers despite they should drop the Narthain Gem. I have now several stacks of it.

**Comment by Evildoor** [comment]
Strange, since #1352 and #1550 are closed.

**Comment by dfumagalli** [comment]
No problem, if you want I can make a video.

**Comment by Meralors** [comment]
Quest fixed, can close ;)
