### ISSUE TITLE
Squigs not being summoned

### ISSUE THREAD

**Issue by gruntface** [WarEmu/WarBugs#17336]
I am unable to summon a squig (any type and in both rSH and mSH mode).

The timer and animation both run but after the explosion there is no squig. I have restarted the game and changed locations but no success.

<img width="986" alt="ROR2" src="https://user-images.githubusercontent.com/68444940/87827113-04563c80-c82f-11ea-843d-c54a672fa75a.png">

**Comment by Sivine** [comment]
I think you might have Territorial Aggression tactic.
It lets you cast pets, does the animation but do not let it spawn, just tested it on my SH in gobbo form.

**Comment by Kaelang** [comment]
Please confirm ^

**Comment by gruntface** [comment]
Thanks Sivine, this was the issue. I tried again on different tactics and in gobbo/armor mode and was able to replicate. In reading the tactic, this was not evident but appreciate the quick comment. The fact it was animating rather than simply not starting coupled with the description of the tactic was confusing me.

Cheers.
