### ISSUE TITLE
(SM) T4 Epic Quest Reward 'Ninth Peak' displaying incorrect proc

### ISSUE THREAD

**Issue by detrap** [WarEmu/WarBugs#17335]
(SM) T4 Epic Quest Reward 'Ninth Peak' displaying incorrect proc

From Dwarf Epic Quest line. Says 88 wounds increase but only increases actual wounds by 80

![InkedDesktop Screenshot 2020 07 18 - 01 16 52 80_LI](https://user-images.githubusercontent.com/64330047/87802597-ca1f8600-c894-11ea-860e-e1922d73424a.jpg)

**Comment by Lheana** [comment]
Are you sure you don't reach the cap?

**Comment by detrap** [comment]
My wounds go from 933 to 1013 which is only an 80 stat difference.

![wounds change ninth peak](https://user-images.githubusercontent.com/64330047/87816803-3dcc8d80-c8ab-11ea-9b9a-050f19cb9768.png)

**Comment by Kaelang** [comment]
This is a Preservation related problem - see https://github.com/WarEmu/WarBugs/issues/14920
