### ISSUE TITLE
Quest ; The Dark Heart of Avelorn CH. 11 Grimwater

### ISSUE THREAD

**Issue by depood** [WarEmu/WarBugs#17342]
On Questlog: use the dark heart to spawn Blackheart and kill him.
On current version: Blackheart spawns without using the item, so you cant complete the Quest the way the log says.

Workaround: kill him multible times, one kill finishes the "spawn" and the next will finish the quest.

He spawned without quest, or questitem:
![Depood_001](https://user-images.githubusercontent.com/157977/87851552-25d02a80-c8fa-11ea-9770-70d98dbab9d6.jpg)

killed him:
![Depood_003](https://user-images.githubusercontent.com/157977/87851568-48624380-c8fa-11ea-9721-5b964b1d405b.jpg)

he respawned after his corpse despawned
![Depood_004](https://user-images.githubusercontent.com/157977/87851583-70ea3d80-c8fa-11ea-9365-1be17257c80a.jpg)

**Comment by Lheana** [comment]
Nothing wrong here that prevents you from completing the quest. You need to use the item in a perimeter to lure out the NPC, then you can kill him.
