### ISSUE TITLE
SHAMAN Fury of da green fails to heal all targets when defensive target is caster

### ISSUE THREAD

**Issue by Grumug** [WarEmu/WarBugs#17359]
**Expected behavior and actual behavior:**
![Skarzig_003](https://user-images.githubusercontent.com/64093828/88208399-71b00600-cc51-11ea-8bac-f12d297c6c79.jpg)

As stated in the title the ability Fury of da green dont heal allies if the defensive target is the caster (shaman).

**Steps to reproduce the problem:**
Select an enemy target ,select yourself as friendly target,have allies in range and cast the spell.

**Testing Screenshots/Videos/Evidences (always needed):**

![Skarzig_004](https://user-images.githubusercontent.com/64093828/88208320-53e2a100-cc51-11ea-8fd9-027f23db766c.jpg)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/14857

**Comment by Undrsiege** [comment]
This is a revolving thread
