### ISSUE TITLE
Dragons Bane - no AP regeneration after summoning the dragon

### ISSUE THREAD

**Issue by depood** [WarEmu/WarBugs#17355]
Same as: Dragons bane no AP and slowed bug #17195

After summoning the dragon with the orb - my AP got drained and didnt recover till I died.

![Depood_005](https://user-images.githubusercontent.com/157977/88035890-11cb3980-cb43-11ea-8290-fbb912d55316.jpg)
![Depood_006](https://user-images.githubusercontent.com/157977/88035902-14c62a00-cb43-11ea-966c-9bfb3a82ef32.jpg)

(you see the empty AP bar and greyed out skills)

Reproduction can be though bc it happens not all the time - I asked a BW who played it and he still got his AP.
There was no AP drain on me, just placing the orb set my AP to 0.

**Comment by vayzard123** [comment]
character name: Soleria
I'm a KOTBS and i experience the exact same thing in this scenario, every time i drop the orb in the flag all my skills are greyed out and AP generation does not happen, it is only fixed on death or the scenario is over. It happens every single time i drop the orb on the flag.

**Comment by Kaelang** [comment]
Fixed in todays patch.
