### ISSUE TITLE
Throatbite not firing

### ISSUE THREAD

**Issue by adamversed** [WarEmu/WarBugs#17350]
**Expected behavior and actual behavior:**
Throatbite should deal additional damage and silence on next attack of Pet

**Steps to reproduce the problem:**
1. Have lion attack target
2. Trigger throatbite

**Testing Screenshots/Videos/Evidences (always needed):**
https://www.youtube.com/watch?v=u87tq7Ymnz4

I have shown pet attacking dummies without stance so you only get auto attacks listed in the combat  log (theres no stance restriction on throatbite, but if you want to try with any stance you will get same issue).

I have  shown first what happens when you select brutal pounce, which will correctly add damage and effect on next attack
I then show the same for throatbite, with nothing reported.

**Comment by wargrimnir** [comment]
Target dummies are immune to silence so the damage is not applied.

**Comment by adamversed** [comment]
I would still expect to see the damage component, same as brutal pounce (where dummies are immune to kd) - here is another video on a mob showing it not firing:

https://youtu.be/Ya7S_Z30V4Y

**Comment by admaska2** [comment]
Its normal it was a nerf, its worked as intended.

It was nerfed when they did the Big patch " Pet damage reworked " a long time ago.

**Comment by grunbag** [comment]
It’s working just tested
