### ISSUE TITLE
Khaine's Imbuement

### ISSUE THREAD

**Issue by panodill** [WarEmu/WarBugs#17352]
**Expected behavior and actual behavior:**
Discipline of Khaine Tactic Khaines's Imbuement
Expect it to not refresh it self or to do damage when applied, but it refresh it self so fast that the damage tick after 3s dont even come most of the time

**Steps to reproduce the problem:**
Equip tactic, its core. Hit dummy and check combat log/UI

**Testing Screenshots/Videos/Evidences (always needed):**

https://youtu.be/nBJ2jmf1pRI

**Comment by panodill** [comment]
Btw, was same with Guilty Soul dot on WP a few years ago. Lock at that fix

**Comment by wargrimnir** [comment]
This will no longer refresh itself.

**Comment by Kaelang** [comment]
This should have been fixed with today's patch.
