### ISSUE TITLE
Fortress Items : No gold cost on tooltip

### ISSUE THREAD

**Issue by Stompah** [WarEmu/WarBugs#17354]
I'm sure many have upgraded to the Fortress items and have been victim to the rogue cost of 50g attached to this upgrade. No where is it stated that this upgrade costs 50g, seems a simple fix could be implemented to make this more common knowledge
![InkedStompah_006_LI](https://user-images.githubusercontent.com/68201609/87994943-d0d81400-cab3-11ea-9b9f-7f8cd46e139b.jpg)
![InkedStompah_007_LI](https://user-images.githubusercontent.com/68201609/87994949-d33a6e00-cab3-11ea-92f0-0bd51561763d.jpg)
![InkedStompah_010_LI](https://user-images.githubusercontent.com/68201609/87994951-d5043180-cab3-11ea-9c0f-aba16da33fe9.jpg)

**Comment by Kaelang** [comment]
This is a limitation of the client at the moment and is a known issue.
