### ISSUE TITLE
[Quest] Hated Kin, Destruction @The Blighted Isle

### ISSUE THREAD

**Issue by dfumagalli** [WarEmu/WarBugs#1735]
Hello,

I have gone to the designated area and killed a quite impressive amount of every kind of the resident NPCs in that zone, including the elite.
The quest item, Syrth Extract won't drop. I get plenty of grey and craft stuff but no quest item.
I got a lot of "Leafy Back Biter", which are grey items but they are going in the "Quest items" section of the bag. I suspect they are the culprit.
Also, at the center there would be a chest, but it's invisible. Sparks are there to show where it should be, I suppose it's the PQ's chest.

**Comment by Evildoor** [comment]
Strange, #1351 is closed.

**Comment by dfumagalli** [comment]
Well, I don't know if the fact I am level 11 could affect the loot drop or something. If you want I can make a video so you see if I am doing anything wrong.

**Comment by Evildoor** [comment]
Level - i doubt it. Video - no need, i informed @Reggaewaldo and he'll take a look at this problem (and other ones too).

**Comment by dfumagalli** [comment]
Thank you!
If you need additional details or anything don't exitate to tell me. I have been WAR beta tester and am a developer in real life so if you need specific tests I can do them.

**Comment by Meralors** [comment]
Quest fixed, can be closed.
