### ISSUE TITLE
The Ebon Flame Epic Quest

### ISSUE THREAD

**Issue by Kelioum** [WarEmu/WarBugs#17351]
RIannmar Jadeheart is not spawning for the last part ofthe chain for completion

**Comment by Kelioum** [comment]
![image](https://user-images.githubusercontent.com/68522900/87890722-9d3eb080-ca05-11ea-80d0-76b86e7290f0.png)
He is outside the exit door and not in the tower where is supposed to be!

**Comment by Lheana** [comment]
Closing it as that was a temporary issue that got fixed with a server restart.
