### ISSUE TITLE
[Scenario] Quitter debuff not applied when leaving scenario via portal

### ISSUE THREAD

**Issue by Sciberr** [WarEmu/WarBugs#17358]
An introduction:

Leaving a Scenario does not give the quitter debuff that it is supposed to. 

Details:

I was able to leave and immediately rejoin scenarios.

Evidence:

https://youtu.be/ehdLykXma0k

Additional Information:

N/A

How to reproduce the bug:

Join a scenario then proceed to leave it, you will notice that you have no quitter debuff.

**Comment by Kaelang** [comment]
This should have been fixed with today's patch.
