### ISSUE TITLE
Vanquisher 4 pieses proc bug

### ISSUE THREAD

**Issue by randommpa** [WarEmu/WarBugs#17360]
buff from 4 pieses now give +80 weaponmastery and -80 toughness instead  +110 -110.
![Cagucmka_095](https://user-images.githubusercontent.com/21138966/88223556-543e6480-cc70-11ea-9655-d5b70b755410.jpg)
![Cagucmka_094](https://user-images.githubusercontent.com/21138966/88223558-56082800-cc70-11ea-99ee-655bf2e7a9ff.jpg)

**Comment by Kaelang** [comment]
This proc has been reported previously.
