### ISSUE TITLE
[Quest] Nymosar's fall, Destruction @The Blighted Isle

### ISSUE THREAD

**Issue by dfumagalli** [WarEmu/WarBugs#1736]
Repeater bolt throwsers should be ballistas planted on the ground. In the original game they were. Instead they actively follow you around! :)
Also, there's a number of dead looking corpses in that area that attack you when you get close to them.

**Comment by Evildoor** [comment]
Mobs looking as corpses is a general problem unrelated to this quest.

**Comment by DanaBloodkiss** [comment]
The fake dead NPC are fixed and the siege weapons are a general problem. Closed.
