### ISSUE TITLE
SM - Crashing Wave - Incorrect Damage

### ISSUE THREAD

**Issue by Morphann** [WarEmu/WarBugs#17361]
**Expected behavior and actual behavior:**
The tooltip for Crashing Wave with my current equipment states 650 Damage. When using Crashing Wave, the damage is considerably lower, dealing 402 (201x2)

"Your Crashing Wave hits Target Dummy for 201 damage.
Your Crashing Wave hits Target Dummy for 201 damage."

**Steps to reproduce the problem:**
As a Swordmaster, Specialise in Path of Hoeth, 9 Points in and take Crashing Wave.
Check tooltip and attack dummy/enemy/NPC with Crashing Wave.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/68667389/88234346-b1d2b100-cc70-11ea-9bc3-677e58113644.png)
![image](https://user-images.githubusercontent.com/68667389/88234506-ef373e80-cc70-11ea-84e1-1e4544cc4c06.png)

**Comment by wargrimnir** [comment]
You might notice that we don't have tooltips matching in-game damage. Please don't report every single ability you find. We don't understand the formula. They're approximations.

**Comment by Morphann** [comment]
This was one of the stronger abilities on live and it seems inconsistent with the behaviour of most other SM abilities, in particular perfect balance/spirit damage abilities. In particular the damage output is much lower than expected.
Is your initial assessment that this ability is working as intended?

**Comment by wargrimnir** [comment]
This class has been tweaked extensively over the years. My assumption is any significant deviations from live values were intentionally made.

**Comment by Morphann** [comment]
If these are intentional balancing changes, could we get the tooltips amended?
From a UX perspective, an SM might otherwise be using a non-optimal ability rotation for damage.

**Comment by grunbag** [comment]
Fixed with next patch
