### ISSUE TITLE
Tome of the Subjugator

### ISSUE THREAD

**Issue by Ajjaxx** [WarEmu/WarBugs#17365]
The tome of the subjugator does not supply the 8 righteous fury per second. Noted it when i changed tomes.

**Comment by Garrthax** [comment]
> The tome of the subjugator does not supply the 8 righteous fury per second. Noted it when i changed tomes.

reequip it multiple times, worked for me

**Comment by Wachlarz** [comment]
Common Bug U need to restart the game.Bug when U change one book to other book.
