### ISSUE TITLE
Oil

### ISSUE THREAD

**Issue by pobratim** [WarEmu/WarBugs#17368]
![Tarelka_001](https://user-images.githubusercontent.com/42023389/88450861-e904b600-ce5a-11ea-8fb1-6e9cd0939378.jpg)
Thos oil is undefendable.And i can use it as regular one.Dont know how.But sometimes you can fall under texture with it and use it as regular one.I think it only Empire Chaos bugs.A lot of texture drops are in Talabec-Praag and CW keeps.
But for a first time i see this with oil.
Ive made a 10 kills with it staying this place.

**Comment by Kaelang** [comment]
This happens every now and again, it's listed on the BT but replication is difficult.
