### ISSUE TITLE
Sov granted ability barely triggering until gear reequiped

### ISSUE THREAD

**Issue by evilest-ror** [WarEmu/WarBugs#17364]
On my snb chosen I recently purchased the chest as the 7th piece. Equipped it, removed it, put toughness talisman on it, put it back on. I quit and later relogged in. The 7th piece equipped grants an ability that has a 10% chance to activate on being attacked but it was not working properly.

After a good number of scenarios I could not see it working more than once or maybe twice, no more. So I decided to find someone to test with. No respecs, potions, or anything other than map changes. I tried with a number of mobs, would not trigger. Tried in a duel, similarly it would not trigger. Tried vs someone giving me a hand in order in case it was a duel issue, nothing. Only after removing and re-equiping the chest (only piece I tried tho), the ability immediately started working as it should.

What's odd is that it definitely activated once (or twice) before removing the piece. Reminded me of the chalice bug, not giving essence.

**Comment by Kaelang** [comment]
There's issues with Sov granted abilities that are already live on the BT - they will need a re-review.
