### ISSUE TITLE
KobS M2 morale Emperor's Champion 

### ISSUE THREAD

**Issue by Nicetomeatcha** [WarEmu/WarBugs#17370]
The tooltip says it lasts for 30 seconds, it lasts for half that. i dont know how to do a video so all i can do is this, please dont hate me for posting all these pictures.
![Danneberg_009](https://user-images.githubusercontent.com/66981327/88456535-14c87180-ce44-11ea-81b2-538fdc225fdf.jpg)
![Danneberg_010](https://user-images.githubusercontent.com/66981327/88456536-15610800-ce44-11ea-88de-8934424bb65f.jpg)
![Danneberg_011](https://user-images.githubusercontent.com/66981327/88456537-15f99e80-ce44-11ea-82fe-5891037d84f9.jpg)
![Danneberg_012](https://user-images.githubusercontent.com/66981327/88456538-15f99e80-ce44-11ea-9651-8d41ced53dcd.jpg)
![Danneberg_013](https://user-images.githubusercontent.com/66981327/88456539-16923500-ce44-11ea-9d4d-195909bf9365.jpg)
![Danneberg_014](https://user-images.githubusercontent.com/66981327/88456540-16923500-ce44-11ea-9498-564249b4cf91.jpg)
![Danneberg_015](https://user-images.githubusercontent.com/66981327/88456542-172acb80-ce44-11ea-860b-0ee9060323da.jpg)
![Danneberg_016](https://user-images.githubusercontent.com/66981327/88456543-172acb80-ce44-11ea-9fcb-dc061308f194.jpg)
![Danneberg_017](https://user-images.githubusercontent.com/66981327/88456544-17c36200-ce44-11ea-844a-33ba85dc1c35.jpg)
![Danneberg_018](https://user-images.githubusercontent.com/66981327/88456545-17c36200-ce44-11ea-8dbc-97717d42180e.jpg)
![Danneberg_019](https://user-images.githubusercontent.com/66981327/88456546-185bf880-ce44-11ea-8515-579b1d6fc271.jpg)
![Danneberg_020](https://user-images.githubusercontent.com/66981327/88456547-185bf880-ce44-11ea-8d16-604280aaed3c.jpg)
![Danneberg_000](https://user-images.githubusercontent.com/66981327/88456548-18f48f00-ce44-11ea-96b0-edf86200e847.jpg)
![Danneberg_001](https://user-images.githubusercontent.com/66981327/88456550-198d2580-ce44-11ea-8207-1e4317511fcc.jpg)
![Danneberg_002](https://user-images.githubusercontent.com/66981327/88456551-198d2580-ce44-11ea-928f-7f7b5eca84c5.jpg)
![Danneberg_003](https://user-images.githubusercontent.com/66981327/88456552-1a25bc00-ce44-11ea-8153-4c13de97365f.jpg)
![Danneberg_004](https://user-images.githubusercontent.com/66981327/88456553-1a25bc00-ce44-11ea-8c8c-23fed2c9b372.jpg)
![Danneberg_005](https://user-images.githubusercontent.com/66981327/88456554-1abe5280-ce44-11ea-850e-80cf08dac922.jpg)
![Danneberg_006](https://user-images.githubusercontent.com/66981327/88456555-1abe5280-ce44-11ea-86eb-caaee2c8d844.jpg)
![Danneberg_007](https://user-images.githubusercontent.com/66981327/88456557-1b56e900-ce44-11ea-884e-58451faf2aff.jpg)
![Danneberg_008](https://user-images.githubusercontent.com/66981327/88456558-1b56e900-ce44-11ea-80d8-23fd2687aace.jpg)

**Comment by jucawar** [comment]
hi .. this issue as another report open: #13665
