### ISSUE TITLE
KobS - warlord - 4 piece bonus - 6% armor penetration not working 

### ISSUE THREAD

**Issue by jucawar** [WarEmu/WarBugs#17378]
Hi 

I changed the solv boots for worlord boots, but the 4 piece bonus didn´t work. 
the 6% additional armor penetration not working or not appear. 
please, take a look in the file attached. 

![image](https://user-images.githubusercontent.com/64388070/88550540-23578a00-cff8-11ea-813f-ee034c286b44.png)

BR

Kobs
[KobS - armor penetration  - warlord.docx](https://github.com/WarEmu/WarBugs/files/4982377/KobS.-.armor.penetration.-.warlord.docx)

**Comment by Garrthax** [comment]
use .getstats

**Comment by jucawar** [comment]
hi... ok tks (I think its there)

![image](https://user-images.githubusercontent.com/64388070/88559966-e09baf00-d003-11ea-8c2a-714e444658b4.png)

**Comment by Garrthax** [comment]
yeah it is there, so its working properly

**Comment by Kaelang** [comment]
Always use .getstats to test things like this as the statdoll can play games.
