### ISSUE TITLE
Soft cap not being applied to main stats?

### ISSUE THREAD

**Issue by detrap** [WarEmu/WarBugs#17371]
![InkedScreenshot 2020-07-26 09 29 57_LI](https://user-images.githubusercontent.com/64330047/88468215-8c210280-cf23-11ea-9e87-d8565a0a46bc.jpg)

When exceeding the softcap of 1050, the stats on the player window (left circle) show the softcap of wounds being applied, however in statdoll and on the hp bar, its showing no signs of a soft cap being applied.

The same applies for toughness when I tested it:

![Screenshot 2020-07-26 09 06 46](https://user-images.githubusercontent.com/64330047/88468308-d656b380-cf24-11ea-8c74-0bcd0e517586.png)

Are the soft caps in the character window supposed to be ignored? Is there any information on what the actual soft caps are for each stat?

**Comment by kalmatar** [comment]
character window is known for being buggy and failing to show real information, use .getstat for more correct actual statline. 
Also wounds is not a "main stat" per se, it doesn't get a softcap at (careerrank*25)+50 like the other stats that buff outgoing abilities.

**Comment by detrap** [comment]
> character window is known for being buggy and failing to show real information, use .getstat for more correct actual statline.
> Also wounds is not a "main stat" per se, it doesn't get a softcap at (careerrank*25)+50 like the other stats that buff outgoing abilities.

From using getstats, it looks like there is no 1050 soft cap on any main stat's. Strength also has been confirmed not to have a soft cap. Maybe there is a hidden one in game but it's hard to know what it may be.

**Comment by Garrthax** [comment]
yeah confirming that

**Comment by CornerbackAC** [comment]
Can confirm this. Character window on my IB says 1065 wounds but I've got 11400 hitpoints.

**Comment by Kaelang** [comment]
This has been fixed in the hotfix.
