### ISSUE TITLE
Visual effect of dyed item is not showing off

### ISSUE THREAD

**Issue by Romanuzo** [WarEmu/WarBugs#17375]
Hey!
Sovereign Shouldaplate of da Painboss does not represent any dye - doesn't matter if you set them as appearance of another dyed shoulders or paint themselves - they just still showing base dye.

![Core_021](https://user-images.githubusercontent.com/42448411/88482702-b7c7db00-cf6b-11ea-90f3-cbbd29e229ed.jpg)

**Comment by Romanuzo** [comment]
just found out even this
![123](https://user-images.githubusercontent.com/42448411/89129832-51156500-d509-11ea-922b-17192e367de4.jpg)

**Comment by MaxHayman** [comment]
Its possible that the armor is undyable, as in the client doesnt have data on how to dye it. It looks like since it has been marked as undyable.
