### ISSUE TITLE
Eternal Yellow Honeythorn seed making Red Serrisa

### ISSUE THREAD

**Issue by Uchoo** [WarEmu/WarBugs#17372]
https://cdn.discordapp.com/attachments/722151550767857727/736742577939939338/unknown.png

The seed grows the wrong material. :(

Thanks,

Uchoo

**Comment by Kaelang** [comment]
What does it make vs what should it make?

**Comment by Uchoo** [comment]
It makes Red Serrisa (Wounds + Ranged Crit) when it should make Yellow Honeythorn.

Do you need screenshot confirmation?

**Comment by Kaelang** [comment]
Hey Uchoo, the Yellow Honeythorn shouldn't actually be in the DB. It'll be switching over to a different seed next time DB gets refreshed, so you won't lose your seed, but you also won't keep the Yellow Honeythorn. :)
