### ISSUE TITLE
[Quest] Prize of War, Destruction @The Blighted Isle

### ISSUE THREAD

**Issue by dfumagalli** [WarEmu/WarBugs#1737]
Hello,

I have killed both Keeper Nalsurith and most other NPCs except the two elites in a corner. None of them drops the Keeper Nalsuriths Key quest item. I am level 10 in case there are level based "filters".

**Comment by Evildoor** [comment]
Strange, #1354 is closed.

**Comment by dfumagalli** [comment]
It's very strange, you seem to have fixed several of the quests I am signalling but I get them broken. Could it because of level, class or similar?
I mean, if Keeper Nalsurith has got the key with his name, shouldn't I actually either get a key in my quest items inventory or a quest completion message (since I have the other required quest item)?

**Comment by Meralors** [comment]
Ok this is weird. I tested on dev server and its working. I tryed on live and killing Keeper Nalsurith isnt giving the quest update. It could be temporary bug and will be fixed with next patch/update.

**Comment by Reggaewaldo** [comment]
It will be fixed with next update that should happen rather soon. The issue is that the quest DB has not been updated.
