### ISSUE TITLE
Sovereign Squigplate Undyeable

### ISSUE THREAD

**Issue by Folgrimma** [WarEmu/WarBugs#17381]
The Squigplate is undyeable, hindering dyeing the item even if the appearance is changed.

**Comment by Kaelang** [comment]
"dyeing the item even if the appearance is changed"

So it does dye? Or doesn't?

Need more information please.

**Comment by Folgrimma** [comment]
The item "cannot be dyed." So you're unable to dye the item at all with any dyes outside of the vendor.

**Comment by Kaelang** [comment]
Not all items can be dyed.
