### ISSUE TITLE
Word of Pain/Vision of Torment being disrupted AFTER being APPLIED to target

### ISSUE THREAD

**Issue by Sixmoons48** [WarEmu/WarBugs#17388]
![evidence](https://user-images.githubusercontent.com/21229715/88873591-9c1a3a00-d1e2-11ea-9562-0bce874ca861.gif)

pretty self explanatory, after applying wop/vot it will tick down and they can still disrupt second portion, unless im mistaken this was changed way back after the dot disrupt dark ages, this will disrupt 100% of the time vs WHs the use relic

edit after testing more: upon testing with witch elf in duel arena (had disrupt cauldron) i found out that both wop and vot will disrupt after already being applied, what more is that wop completely disappears, it doesnt show up in wsct (scrolling combat text) nor does it show up in combat log, BUT VoT DOES, every single time, VoT will show disrupt, WoP on other hand will not, the witch elf was seeing same problem, they'd see it disrupt/disappear, but nothing in combat log (can post this evidence as well if necessary)

**Expected behavior and actual behavior:**

expected behaviour is once applied, the damage will always connect unless cleansed

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Sixmoons48** [comment]
Now im unsure if this is some wider-spread issue or not, attached only to disrupts, all dots, or maybe just WH relic/WE cauldron, however, upon playing my shaman and putting dots on a witch hunter, that witch hunter took ZERO damage from the dots during the duration of his cauldron, not only that, but there was no disrupt notification in combat log, this was with all 3 main shaman dots on him.  This bug feels recent but its heavily reminding me of dot/disrupt time period, almost like something was reverted on accident. Currently working trimming proof for shaman part

**Comment by dalen** [comment]
These abilities are meant to remove all magic spell damage while they are up, even dots already applied. They were changed to behave that way in a patch around one and a half year ago.

**Comment by Sixmoons48** [comment]
Thats a crazy change ive only just heard of, must have missed that patch and never seen them disrupt like this.  The tooltip is a bit misleading then, and is there any reason why it doesnt show up in combat log? Is it counted as an absorb? Even every single player i talked to had no idea this was how the ability was supposed to act and thought it was a bug.
