### ISSUE TITLE
Royal Set 8 Piece Bonuses Not Implemented Properly

### ISSUE THREAD

**Issue by Haojun-Phalanx** [WarEmu/WarBugs#17386]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=37733#p408147

With 22/04/2020 Patch, all 8 Piece Bonuses for Royal Sets are unified.

Problem:
Majority of royal sets still have the old bonuses; for example WE-Sov Main should be;

*Melee DPS Archetype
• Desolation - Up to 3 nearby enemies within 10' immediately lose 1800 Morale

but atm it's a long range punt. Also Majority of Off Sove-Warlord-Set 8 piece abilities for tanks not implemented properly. (I don't have sets, this info comes from people i know)

![sove2](https://user-images.githubusercontent.com/23129933/88811472-46806600-d1bf-11ea-8751-258709e8748c.png)
![sove](https://user-images.githubusercontent.com/23129933/88811494-4c764700-d1bf-11ea-8bea-7977a9319ac7.jpg)

**Comment by wargrimnir** [comment]
There are three different GIAB's between warlord/sov/off-sov, that post lists the two New ones that were added. The third one in the screenshot was the original WAR GIAB that was moved to whichever set it fit best. That post is a mess, non-english speaker things I guess. All three are intended, we didn't throw out the old ones.
