### ISSUE TITLE
Career Tactics are not showing their names

### ISSUE THREAD

**Issue by nainggolann** [WarEmu/WarBugs#17396]
When viewing my different tactics, the names no longer appear. They are all labeled as "career tactics"

**Expected behavior and actual behavior:**

The names are usually all there of each tactic, but now it just says "career tactic" for all of my tactics

**Steps to reproduce the problem:**

open up abilities and hover the mouse over career tactics to view them.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/69022189/88988983-82dbc100-d2a8-11ea-99c9-172ca4da0ca8.png)

**Comment by Rydiak** [comment]
Relog

**Comment by Kaelang** [comment]
This isn't a game bug, it's an issue with your client downloading the patch files.

Restart your launcher / run a repair.
