### ISSUE TITLE
[Quest] Must Have, Destruction @The Blighted Isle

### ISSUE THREAD

**Issue by dfumagalli** [WarEmu/WarBugs#1739]
The quest text implies many if not all the unicorns around drop the quest item, "Pure Hearts".
However, "Unicorns" show a tooltip with the quest item (0/4 etc) but do **not** drop it.
Lower level "Majestic Unicorns" instead, don't show a quest item counter tooltip but **do** drop it.

I think either the unicorn names or their loot table have been swapped.

**Comment by Ryanfawkez** [comment]
Pure Heart quest item added to Unicorn drop table, fixed in next patch.
