### ISSUE TITLE
Warn On Buy - doesnt warn always

### ISSUE THREAD

**Issue by depood** [WarEmu/WarBugs#17397]
Expecting to block accidental buys.
Bought on rightclick an item without warning.

**Steps to reproduce the problem:**
I wont reproduce it (too expensive).
On the NPC "Strezhyrr" i was checking Item stats for a guildmate - using most of the time left+right mouseclick to move around.
Looks like my mouse was over the Sov back and it bought it (no warning, no popup - nice waste of royals)

This seems only to happens on Strezhyrr - on Thul the warning pops up.
![Ercha_027](https://user-images.githubusercontent.com/157977/89000660-33bd7c80-d2f8-11ea-909b-68d3965015e5.jpg)

**Testing Screenshots/Videos/Evidences (always needed):**
![Ercha_025](https://user-images.githubusercontent.com/157977/89000530-e3461f00-d2f7-11ea-99c6-61db93a2291f.jpg)
![Ercha_026](https://user-images.githubusercontent.com/157977/89000538-e4774c00-d2f7-11ea-9d89-396cdc9f1ded.jpg)

On a Sidenode: not sure if GM can remove the Backpiece and refund some royals - would appreciate it.

**Comment by Kaelang** [comment]
We don't refund royals, and if it's working across characters - it's a setting that needs looking at from your side.
