### ISSUE TITLE
RR85 Collectors Edition Cosmetic not applying correctly for Witch Hunters

### ISSUE THREAD

**Issue by krubs-oss** [WarEmu/WarBugs#17393]
**Expected behavior and actual behavior:**
The RR85 Collectors Edition Cosmetic item for Witch Hunter ("[True Believers](https://www.returnofreckoning.com/armory/item/206053)") does not appear to work. Instead of providing a "Skull Mask" as shown in the Armory, it only changes the face appearance of the character model to one of the default face models (Eye Patch 4) and does not consume the item in the process.
It appears this only happens for Witch Hunters, as other Empire classes using the same item have the correct appearance (I.e BW, WP) 

**Steps to reproduce the problem:**
1. Purchase Item "True Believers" from Special Dye Merchant
2. Slot it into the Reward Item Slot in the Dye Menu
3. Accept Changes and Relog
4. The item is not consumed and remains in inventory, while character model has its face changed to "Eye Patch 4")

**Testing Screenshots/Videos/Evidences (always needed):**

Item preview in vendor
![image](https://user-images.githubusercontent.com/66293425/88956058-c9122f80-d26a-11ea-876b-fb0836de36fa.png)

Appearance after relog
![image](https://user-images.githubusercontent.com/66293425/88955513-0629f200-d26a-11ea-8939-579576f8c88c.png)

**Comment by Kaelang** [comment]
This should now be fixed. Please re-open if issue persists.
