### ISSUE TITLE
Destruction Quests - Greenskin Ch12 - Crushin' Dem All cannot handing quest

### ISSUE THREAD

**Issue by Hadzi-user** [WarEmu/WarBugs#17395]
I found the same problem, like in closed bug report [#16878 ](https://github.com/WarEmu/WarBugs/issues/16878)

**Expected behavior and actual behavior:**
Expected: Handing quest to questgiver Grimzag Uruh who has the orange quest completed icon above his head. When talking he shows the quest with the orange icon to the left. Push "Complete" button and take rewards. That quest is finished.

Actual: Handing quest to questgiver Grimzag Uruh. When clicking the complete button nothing happens. I do notice that only the XP reward is visible. I cannot select an item reward. And there is nothing in chat window.

**Steps to reproduce the problem:**
Take the quest Crushin' Dem All at Greenskin Ch12 from Grimzag Uruh.
Kill 4 Rootin' Squigs and 1 Rootin' Troll.
Return to Grimzag Uruh in Greenskin Ch12.
Try to handing quest.

I tried to do myself to fix it:
/reloadui
logoff/on
change UI language for 1 and 10
disable all addons and use clear UI

**Testing Screenshots/Videos/Evidences (always needed):**
![war-64 exe_2020 07 30_-_23 09 23 02](https://user-images.githubusercontent.com/69014772/88970462-22a24a80-d2bb-11ea-93ea-1443444299f6.gif)
![war-64 exe Screenshot 2020 07 30 - 22 28 44 16](https://user-images.githubusercontent.com/69014772/88968803-8ecf7f00-d2b8-11ea-9ec6-06aab1bc9bd9.png)

**Comment by Hadzi-user** [comment]
I thought that maybe the problem is with the choppa and decided to check. I made this quest with my zealot and it worked correct.
So It seems like there is no rewards setup for choppa.
![war-64 exe Screenshot 2020 08 01 - 10 22 46 06](https://user-images.githubusercontent.com/69014772/89096813-1369ec80-d3e2-11ea-8baa-ff92c34a7c53.png)

**Comment by DamnMiri** [comment]
I can confirm this bug on my choppa.
I think there is a similar bug on the quest "Show'em how to waaagh!"
