### ISSUE TITLE
Bright Wizard Rain of Fire cast range bug

### ISSUE THREAD

**Issue by Uncausedryan** [WarEmu/WarBugs#17398]
Casting Rain of Fire outside Maximum cast range now begins casting animation, locking the cast bar and putting the spell on cooldown
-->

**Expected behavior and actual behavior:**
The expected Behavior of casting rain of fire outside of range is to receive the out of range error and not put the spell on cooldown or animation lock your character

**Steps to reproduce the problem:**
cast rain of fire outside of Max Range

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Uncausedryan** [comment]
https://imgur.com/a/vLbTIFG
gif if uploading didnt work

**Comment by Tesq** [comment]
it's not a problem of bw alone it happening on magus firestorm (and once if not mistake on dissolving mist too). It must be an all ground targetting ability

**Comment by Sandrasfanat** [comment]
Bug is still there here a video on my google disk https://drive.google.com/file/d/1gpt0DeTyhYKD-WMx3bQga_kMV7C-K9E_/view?usp=sharing

**Comment by dalen** [comment]
For me it starts the cast where the circle is, at the maximum range of the ability. I don't really see the bug here.
