### ISSUE TITLE
[DESTRUCTION QUEST] Defend Festenplatz

### ISSUE THREAD

**Issue by Enigmaxou** [WarEmu/WarBugs#174]
Quest bugged, related to RVR Objectives in T1 :

![schlagz_003](https://cloud.githubusercontent.com/assets/8019588/3430410/5db42c0c-0061-11e4-9844-d35331c68764.jpg)

**Comment by wargrimnir** [comment]
Fixed months ago.

**Comment by JeFawk** [comment]
Interesting how I still get notifications on these.....

**Comment by JeFawk** [comment]
@wargrimnir  you just replied to something that was updated last time in dec 2015. Got any notion of time?

**Comment by wargrimnir** [comment]
Sometimes I go through old tickets that have been fixed to close them?

**Comment by JeFawk** [comment]
can just close them without a comment lol....2015
