### ISSUE TITLE
Twitch Drop - Website Issue

### ISSUE THREAD

**Issue by depood** [WarEmu/WarBugs#17405]
First: not sure if it belongs to github - if not just delete the Issue.

If you click "unclaimed" it should forward to the character selection.
Right now - this drop cant be claimed because the Url Link is wrong written.

![url issue](https://user-images.githubusercontent.com/157977/89099735-b8d88c80-d3f1-11ea-94db-92e8c8171a1a.png)

Cant try to reproduce it, waiting for the next drop.

Little Update: the next Twitch drops works - but didnt fix the drop before

Edit nr.2: the next drop bugs out too, it generates following URL: https://www.returnofreckoning.com/account/social/twitch/twitch_reward/twitch_reward/twitch_reward/twitch_reward/twitch_reward/6594

Edit nr.3: as you see in that screenshot - i could claim some rewards - some not.
![twitch drop bug ](https://user-images.githubusercontent.com/157977/89196820-09471a00-d5ab-11ea-9d06-0e3170a3a5cd.png)

**Comment by MaxHayman** [comment]
Try https://www.returnofreckoning.com/account/social/twitch_reward/6594
