### ISSUE TITLE
BW rain of fire issue

### ISSUE THREAD

**Issue by GimmiMoar** [WarEmu/WarBugs#17406]
BW rain of fire is not  casting as intended. It didn't cast numeoruns times on me last night, and it shows the action casting. 

I have a video but it wont let me attach it here- where can I send it?

**Comment by GimmiMoar** [comment]
FYI - this happened to me numerous times yesterday in ORVR

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17398
