### ISSUE TITLE
Can't queue city while having "Quitter" debuff from cancelling scenario pop.

### ISSUE THREAD

**Issue by losvtranse** [WarEmu/WarBugs#17400]
**Expected behavior and actual behavior:**
You should be able to queue city while having "Quitter" debuff because city isn't a scenario.

**Steps to reproduce the problem:**
1) Get Quitter debuff by cancelling scenario pop
2) Try to queue city.

**Testing Screenshots/Videos/Evidences (always needed):**
![изображение](https://user-images.githubusercontent.com/16538643/89037779-d2bd9500-d347-11ea-97ab-3b3b5b568e6d.png)

**Comment by dalen** [comment]
The city sieges work as a scenario. Allowing players to enter and leave scenarios while waiting for a city pop would cause a bunch of other issues. So this is working as intended.
