### ISSUE TITLE
Writ of the Realm (twitch drop quest): incorrect particulars text and missing a tier of rewards

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#17403]
**Expected behavior and actual behavior:**

The "Particulars" section says I need to do the Caledor Woods Scenario and then turn the quest in to an NPC in Altdorf. Unfortunately this scenario is not active and I play destruction. The "Requirements" section just says win any scenario which works fine, so the Particular's section just needs amending.

In addition, the reward list is missing T2 emblems.

**Steps to reproduce the problem:**

Open the "Writ of the Realm" quest in the Tome of Knowledge.

**Testing Screenshots/Videos/Evidences (always needed):**

![writ](https://user-images.githubusercontent.com/60266177/89095957-5324da00-d3ca-11ea-8592-e766ca8043c7.PNG)

**Comment by MaxHayman** [comment]
Text fixed already, reward will be added on next patch
