### ISSUE TITLE
Squig Herder  Path of Bouncin 13 pt. Mastery ability "Tastes Like Stuntie" animation freeze

### ISSUE THREAD

**Issue by Rildetarma** [WarEmu/WarBugs#17408]
As per the title, the Squig Herber, Path of Bouncin 13 point Mastery ability "Tastes Like Stuntine" has animation freezes.  The ability will fire, and record the healing and damage,  but the squig in the armor will freeze.  It will often stay in a frozen state for a few minutes (perhaps as long as five minutes) before returning to normal.  During the course of this freeze, other actions can be taken, for example additional attacks, but they only show in the damage table.  Nothing will be animated.  If one attempts to move.  The frozen squig can change locations, but no movement animations will show.  

  Below are some screen shots. 

![Warts_006](https://user-images.githubusercontent.com/15988204/89102606-e4db1a00-d3bf-11ea-840a-976a9188d7ca.jpg)
![Warts_007](https://user-images.githubusercontent.com/15988204/89102607-e573b080-d3bf-11ea-9c2d-634422af40dd.jpg)
![Warts_008](https://user-images.githubusercontent.com/15988204/89102608-e573b080-d3bf-11ea-8584-867306cc5e44.jpg)

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Rildetarma** [comment]
Any update on this?  The animation freeze persists for several minutes after using the ability.   I think this has been the case ever since the class rework.

**Comment by Zydna** [comment]
This is still bugged. Any info?

**Comment by grunbag** [comment]
Fixed already
