### ISSUE TITLE
Melee Squig - Pet ability damage not scaling with "He's A Biggun" tactic #13898

### ISSUE THREAD

**Issue by Rildetarma** [WarEmu/WarBugs#17409]
(apologies if I am doing this incorrectly)

#13893 records the Squig Herder tactic "He's A Biggun" is not scaling for damage.  The original complaint noted "You should be able to slot this tactic for 160 more pet strength and increase ability damage and tactic damage as it increases the pets base strength by 160.  When you slot tactic. Pet AA increases but pet ability damage remains the same."

 This was confirmed by the investigating Dev. Kaelang on May 16th in the original complaint.   It does not show any further result.

Screen shots were provided in the original complaint #13893.  I can provide further screens if needed.

Thank you

**Comment by grunbag** [comment]
Fixed with next patch , tooltip still incorrect btw
