### ISSUE TITLE
[PETS WL SH] pets can not be sneered

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#1740]

**Comment by ozarmidrashim** [comment]
If this is "snared", they can be snared, same as other NPCs. They're just faster than players are.

**Comment by Nfkillz** [comment]
well made a test. Yes you are right. But why pets have 125 speed instead 100?

**Comment by ozarmidrashim** [comment]
To compensate for pathing issues.

**Comment by Evildoor** [comment]
Closing as not a bug.
