### ISSUE TITLE
Gunbad Garrolath the Poxbearer broken

### ISSUE THREAD

**Issue by JoveTone** [WarEmu/WarBugs#17402]
**Expected behavior and actual behavior:**

Killed Poxbearer and once dead his corpse began spazing out, his healing minions did not die. got a lockout for him but the last boss was still gated. Tried reforming group on an alt with no lockouts to reset but kept joining the same broken instance when switching back to my main. 

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by snaky68** [comment]
Did this boss 16h ago and 1h ago... exactly the same issues...

**Comment by Sivine** [comment]
Same problem on my end, we tried yesterday evening

**Comment by Sivine** [comment]
Here is video proof : 
https://imgur.com/a/muYiR5a
