### ISSUE TITLE
Banner Skills Cool Down

### ISSUE THREAD

**Issue by Emerosa** [WarEmu/WarBugs#17413]
I usually only pull my banner out for keep takes/zone flips and plant it. When I picked it up the last few times it had a crazy cool down timer of 25000 minutes for plant/slam/blessing (When used). I took screenshots yesterday but weren't saved in the folder for some reason, I can try and replicate it again and see if I can get screenshots. So my game is not taking screenshots for some reason so here is some very poor quality phone pictures.

**Expected behavior and actual behavior:**
Plant - No Cool down
Blessing - 2 minute Cool down
Slam - 2 minute Cool down
Rally - 3 minute Cool down

**Steps to reproduce the problem:**
I've tried in the warcamp (not flagged then flagged myself) but the only thing that seems to replicate it is planting anywhere in the rvr lake.

**Testing Screenshots/Videos/Evidences (always needed):**

![Lindara 012](https://user-images.githubusercontent.com/28827833/89116957-b0bb3400-d467-11ea-8fde-c9beaa04f34e.jpeg)
![Lindara 013](https://user-images.githubusercontent.com/28827833/89116952-a0a35480-d467-11ea-8082-4526b03fd2f6.jpeg)

**Comment by Kaelang** [comment]
This is a known issue with multiple cooldowns, doesn't necessarily relate directly to this item. There is already a live report for this.
