### ISSUE TITLE
Respecing Bug

### ISSUE THREAD

**Issue by Symbelmyne** [WarEmu/WarBugs#17415]
**Expected behavior and actual behavior:**
After a respec skills bought from a tree shows up as a icon with 5 digit numbers instead of casual icon skills.
Those bought skills cant be used, nothing happens as they are sloted in skill bar.

Respecing again, cleaning cache and /rel, changing zone, dead, nothing fix it, only solution I found is to restart game including launcher.

**Steps to reproduce the problem:**
Not sure why it bugs out, but happened to me three times already once on Sorcereer, twice on Marauder. So its not uncommon thing i guess. To get the effect you need to respec. Dunno other conditions.

**Testing Screenshots/Videos/Evidences (always needed):**
![Skill bug](https://user-images.githubusercontent.com/16525371/89122541-2fe05480-d4c8-11ea-9343-9c7f406079a9.png)

**Comment by Kaelang** [comment]
Had no issues with respeccing - try reinstalling / repairing your client.
