### ISSUE TITLE
Salzenmund PQ first stage bug

### ISSUE THREAD

**Issue by Cheermazon** [WarEmu/WarBugs#17411]
**Expected behavior and actual behavior:**

First stage of PQ requires collection of supplies, you're able to click on the same supply 25 times to quickly complete

**Steps to reproduce the problem:**

Have performed PQ twice, and able to reproduce this bug

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/14893
