### ISSUE TITLE
T4 Epic quest Time to waaagh

### ISSUE THREAD

**Issue by zenthar77** [WarEmu/WarBugs#17417]
Was doing the T4 epic quest time to waaagh was half way through , went into highpass cemetery sc when i came out the quest was gone , gone from journal from the NPC quest starter and there was nothing from the npc i had to talk to witch was the next step.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
Everytime this kind of report has been opened, the players were not remembering well where they stopped. So talk to every quest giver of this epic quest.

**Comment by zenthar77** [comment]
Hi Lheana  I remember i had to go to IC and speak with Tchar'zanek witch is step 3 right before the SC popped, when i did that after SC no update i have tried it again and went back to the previous steps still nothing happens and the quest is no longer in my quest journal. I went back to the quest starter and he doesnt show the quest either. hope this can help .

**Comment by Lheana** [comment]
Give you char name

**Comment by zenthar77** [comment]
Skarzk

**Comment by zenthar77** [comment]
Skarzk

**Comment by Lheana** [comment]
Like I said, you don't remember well where you stopped, there is no issue here.
You need to talk to Grumlok.

**Comment by zenthar77** [comment]
the whole quest its self is missing from my quest journal thats the issue , doesnt matter who i speak to nothing happens the quest is gone

**Comment by Lheana** [comment]
Then show a screenshot of you talking to Grumlok.
