### ISSUE TITLE
Glitch spot, you can get inside a keep wall in Kardiv Valley

### ISSUE THREAD

**Issue by darkt1981** [WarEmu/WarBugs#17410]
**Expected behavior and actual behavior:**

You can shoot outside from it and kill stuff and they can't hit you.

**Steps to reproduce the problem:**
![Bug](https://user-images.githubusercontent.com/24462956/89105411-35369400-d421-11ea-9823-e6b40bd267bd.png)

See Screen shot

**Testing Screenshots/Videos/Evidences (always needed):**

https://postimg.cc/bdTCDz8j or see attachment.

**Comment by Lheana** [comment]
This has been addressed with last patch.
