### ISSUE TITLE
NEW BAG Invader Staff!

### ISSUE THREAD

**Issue by Agnus94** [WarEmu/WarBugs#17419]
![staff](https://user-images.githubusercontent.com/68962938/89128629-9df43e00-d4ff-11ea-9d8d-330e5db92c89.png)
Good day! Noticed a new bug with the staff for invaders. Now it is not bought at all! Having all components in the form of 1 staff Sabjugator and 122 Invader Medallion..when I try to buy it by checking the box, it is not bought, although I have all the items in the right quantity. Tried to re-enter, update the patch..nothing helped. Look at this error.

**Comment by Kaelang** [comment]
You need 100 gold.
