### ISSUE TITLE
Elixir of Shadows Buff Cancellation 

### ISSUE THREAD

**Issue by Echo-Warhammer** [WarEmu/WarBugs#17412]
**Expected behavior and actual behavior:**
During the duration of the EoS ability/buff, using Fleet Footed and Feinted Positioning will break it. After speaking with a few folks, we agreed it wasn't intended to be this way and is relatively detrimental to the class on certain occasions (this also applies to WH). For example, the engage with EoS to then catch someone with full duration of Fleet Footed and Feinted Positioning is affected.

After some discussion, it seems other classes have speed buffs removed when activating other skills - I don't know if that's true or not. But, in this case, stealth should still remain for the full 2 seconds even if the speed is lost.

**Steps to reproduce the problem:**
1. Use EoS
2. Use either Fleet Footed or Feinted Positioning
3. The buff will break (both stealth and run speed)

**Testing Screenshots/Videos/Evidences (always needed):**

I don't think it's needed for this one but I can provide a video if needed, more info on forum post: https://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=40072

**Comment by Kaelang** [comment]
This was reported earlier this year and was noted as working as intended by our ability dev.
