### ISSUE TITLE
6th piece bonus description on Invader set for tanks incorrect 

### ISSUE THREAD

**Issue by detrap** [WarEmu/WarBugs#17416]
Proc description:

![Mending wounds ability](https://user-images.githubusercontent.com/64330047/89127521-62726780-d531-11ea-8b2a-a41e2d01d509.png)

Heals for 665hp instead of 500hp:

![mending wounds combat log](https://user-images.githubusercontent.com/64330047/89127522-643c2b00-d531-11ea-9c33-305cea05f1dd.png)

This is tested on my IB and also occurs my Knight, this is with or without healing bonus e.g. tactics.

**Comment by Kaelang** [comment]
Tooltips are often classed as guidelines - the heal has been reviewed by the ability dev and such issue with the ability in itself hasn't been raised.
