### ISSUE TITLE
scenario unable to click any skills etc

### ISSUE THREAD

**Issue by chalfont** [WarEmu/WarBugs#17425]
<when i enter any scenario, i cannot click any ability, skill, open menu anything, i have to quit the game , i have no mod ( i have removed every one). i have deleted cache too, but still cannot click anything, game was fine up until last thurs after an update..
Issues should be unique. Check if someone else reported
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
This isn't a globalised issue - please look at alternative options such as a fresh install.
