### ISSUE TITLE
Getting thrown back to character screen.

### ISSUE THREAD

**Issue by Fuineir** [WarEmu/WarBugs#1742]
As in the title, and it happens to others a lot too. 
When porting to different zones, or, connecting to SCs, I'd say 75% of times I'm getting pushed back to character screen. In that state, connecting back to the game isn't possible while clicking play button. It's required to quit the game and run it again.
The issue has begun like 5days-week ago.

**Comment by Evildoor** [comment]
Closing per rules of the bugtracker.
