### ISSUE TITLE
bugged backpack

### ISSUE THREAD

**Issue by billybobjoesam** [WarEmu/WarBugs#17426]
Whenever I open my back pack, list mode is broken but the non list mode is not. The problem then becomes the bar at the bottom in non-list mode that doesn't go away as far as I know and is covering my quest items. I looked at the code and didn't want to mess with anything unless I had a developer or someone else to help me. 
![Billybobjoesam_000](https://user-images.githubusercontent.com/69168762/89221116-58378400-d598-11ea-8fb2-3fa08bbdb59a.jpg)
![Billybobjoesam_001](https://user-images.githubusercontent.com/69168762/89221118-5a014780-d598-11ea-97fb-aea341b9d44e.jpg)
![Billybobjoesam_002](https://user-images.githubusercontent.com/69168762/89221121-5bcb0b00-d598-11ea-89bd-b5573d19f266.jpg)

This is the only real bug I've run into so far but it is really frustrating cause i can't use quest items.

**Comment by Kaelang** [comment]
Repair your launcher / look at addons. Alternatively, for these isolated issues please use the forum support.
