### ISSUE TITLE
Mail deleted itself (error message inside)

### ISSUE THREAD

**Issue by pkfsa** [WarEmu/WarBugs#17427]
I didn't realize my backpack was full when trying to take the gold bag I received from my mail and it just poofed. I didn't click delete and there was no confirmation, just poof. This is bullshit.

![Capture3](https://user-images.githubusercontent.com/51827887/89240481-2f2fe700-d5ca-11ea-93c6-295b32dc4eab.PNG)

**Comment by Kaelang** [comment]
Trying to take mail with a full bag pack gives the correct error prompt. I've tried replicating this with multiple items both player sent and server generated - neither of them immediately deleted the mail.

Will keep this open to investigate the error message provided.

**Comment by pkfsa** [comment]
With something in your overflow bag too.

**Comment by MaxHayman** [comment]
This is what happens when the Report Mail button is clicked. I have added something which prevents mail being deleted if there are still gold or items attached.

**Comment by Kaelang** [comment]
This should now be fixed. Please re-open if issue persists.
