### ISSUE TITLE
Squig problems

### ISSUE THREAD

**Issue by Squigmon** [WarEmu/WarBugs#17428]
When I summon a squig in one zone then leave, i retain the squig buffs in the next but can summon another new squig to stack buffs

just leave a zone wit a squig of one kind, and when it dissapears summon a new kind to stack the buffs

![2020-08-03](https://user-images.githubusercontent.com/69180758/89248256-e598c980-d5d4-11ea-9d73-b13e160902c6.png)

**Comment by grunbag** [comment]
Fixed already
