### ISSUE TITLE
Fortress reservation acting up

### ISSUE THREAD

**Issue by encadi** [WarEmu/WarBugs#17424]
1/ Fight in Chaos wastes for a while
2/ Get Fortress Reservation
3/ Switch Warbands
4/ Try to get into fortress 1-2 mins after reservation
5/ get pushed back

**Comment by encadi** [comment]
https://i.imgur.com/QiKuEeT.png

**Comment by Kaelang** [comment]
Did the timer run out?

**Comment by encadi** [comment]
YUp for sure i entered the fortress  as i was switchign warbands.

**Comment by Hulkenngi** [comment]
Same thing happened to me a few minutes ago. I had reservation in Shining Way, I was there few minutes before the 5m reservation were supposed to end. 
Joined a warband on the way and it wouldnt allow me to enter, it just put me in queue.

**Comment by Kaelang** [comment]
> YUp for sure i entered the fortress as i was switchign warbands.

If the timer runs out you will lose your reservation.

**Comment by encadi** [comment]
Timer hadnt run out...
