### ISSUE TITLE
BW - Invader Flamestone cannot be purchased

### ISSUE THREAD

**Issue by x-eagleeye-x** [WarEmu/WarBugs#17422]
I tried purchasing the Invader Flamestone from the Invader Medallion Quartermaster in Altdorf. I have satisfied all requirements:

- Minimum 63 RR (I'm 64 at the time of writing)
- 43 Invader Medallions (I had 83 left)

I was able to purchase 2 Invader pieces with no problem, and I think I will be able to purchase the rest, expect the Invader Flamestone (Jewelry). Normally, when you do not satisfy the requirements, a message will appear in the chat window indicating the reason it cannot be obtained. No such message appeared.

**Expected behavior and actual behavior:**
Be able to purchase the Invader jewel piece without problem since I satisfy all requirements.

**Steps to reproduce the problem:**
Talk to Invader medallion NPC in Altdorf, ensuring you satisfy all minimum RR and currency requirements for the said piece. Try to right-click it to purchase. Also attempted to click on the piece and drag it to my bags. Same result (or lack thereof).

**Testing Screenshots/Videos/Evidences (always needed):**

![war-64 exe Screenshot 2020 08 03 - 12 36 30 60](https://user-images.githubusercontent.com/69109330/89152573-fb3ace80-d595-11ea-9ddc-68339c1956be.png)
![war-64 exe Screenshot 2020 08 03 - 12 36 55 26](https://user-images.githubusercontent.com/69109330/89152591-055ccd00-d596-11ea-8358-cba1c793f621.png)
![war-64 exe Screenshot 2020 08 03 - 12 37 04 71](https://user-images.githubusercontent.com/69109330/89152596-068dfa00-d596-11ea-9164-85e4f67b6133.png)

**Comment by depood** [comment]
"Requires the Invader TOK unlock to purchase"
You need to equip full invader before you can buy it.

**Comment by x-eagleeye-x** [comment]
Doh! Can't believe I missed that. Thanks very much.
