### ISSUE TITLE
Guild Bank window behavior issue

### ISSUE THREAD

**Issue by WalkerNash** [WarEmu/WarBugs#17434]
**Expected behavior and actual behavior:**
Expected: Guild Bank window closes when commanded.
Experienced: Guild Bank window was open when character was transported to Reikwald for City Attack. Upon spawning, Guild Bank window was still open and accessible (although my character didn't have any permissions other than view Tab 1). Logged out of Character. Logged back into character several hours later. Booked to Altdorf, and began experiencing Guild Bank Window opening spontaneously while I was in the market area, and I could see items being moved about within it. Every time someone moved something in the Guild Vault, the window would open if it was closed, and I would lose priority of whatever I was doing (typing)

**Steps to reproduce the problem:**

No idea. Start with being at bank with guild bank window open when Altdorf switches to prepping for City Seige

**Testing Screenshots/Videos/Evidences (always needed):**

https://drive.google.com/file/d/1P58UFkyEsVJui54f3HyiEy02vdsg3eF0/view?usp=sharing

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/11954
