### ISSUE TITLE
WP Divine Assault

### ISSUE THREAD

**Issue by siflisk** [WarEmu/WarBugs#17439]
Divine Assault is not scaling properly with Divine fury.  It is only getting ~2/3 of the 25% increase.

With 918 Strength and 36 attack power Divine Assault Paper damage is listed as 340 per hit.  With 25% increase this should be 425 per hit.(+85 Damage)  The ability actually hits for 400 per hit. (+60 Damage)

![image](https://user-images.githubusercontent.com/69251767/89424226-22f87680-d6fd-11ea-93ad-e3d654a02f38.png

**Comment by Rydiak** [comment]
Damage isn't calculated as easily as that.  There are coefficients that come into play, and the tooltips don't include damage enhancers like Melee Power.  Use my damage calculator (https://docs.google.com/spreadsheets/d/1cnBUj2mfZnFast84L3DmvF4tZVhdk90eAGlUMmU5wM4/edit?usp=sharing), input your stats in the Attacker Stats row, set the "Target Dummy" to "yes",  and you will see that Divine Assault works properly with Divine Fury.

**Comment by Rydiak** [comment]
Also just tested this in-game.  I have a flat-hit of 356 on a Target Dummy with Divine Assault and without Divine Fury, and a flat-hit of 445 on a Target Dummy with Divine Assault and with Divine Fury.  445 / 356 = 125%

**Comment by siflisk** [comment]
Tested without Divine Fury and you are right, tooltip damage is incorrect.
