### ISSUE TITLE
WP - Book of Faith = No Righteous Fury regen

### ISSUE THREAD

**Issue by GreatHarlequin** [WarEmu/WarBugs#17435]
Just completed FAITH IS MADNESS epic quest and selected the off-hand charm, BOOK OF FAITH. This book does provide a single bit of Righteous Fury when in combat. I can drain the 250 points and it will not refill with this book equipped. It's supposed to provide 8 points a second.

**Comment by Kaelang** [comment]
It's a bit fiddley - you need to unequip / requip it a few times - same things happens with the chalice.
