### ISSUE TITLE
Supply Boxes Respawn too Fast 

### ISSUE THREAD

**Issue by Toshutkidup** [WarEmu/WarBugs#17443]
**Expected behavior and actual behavior:**
Boxes should repopulate when 2 or more BO's are held and respawn every 3 min. 
Clip of issue can be found here. https://clips.twitch.tv/TolerantKawaiiLegBudBlast

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
This is an intentional change in line with the new flight mechanic - I believe this *was* missed off the notes, so should be on tomorrows set.
