### ISSUE TITLE
Fiery reserves 

### ISSUE THREAD

**Issue by anazarelle** [WarEmu/WarBugs#17448]
The tactic Fiery reserves don't work after patch of this day 6 august, normaly 10 sc cd on rain fire and now i have 20 sc , the tactic is broken.
Thx. 
https://image.noelshack.com/fichiers/2020/32/4/1596717192-personongrata-011.jpg

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17446
