### ISSUE TITLE
Combat log showing negative damaged received

### ISSUE THREAD

**Issue by detrap** [WarEmu/WarBugs#17447]
Combat log showing negative damaged received

![Screenshot 2020-08-06 22 08 25](https://user-images.githubusercontent.com/64330047/89531892-440fb300-d834-11ea-9cde-bccfca0c8ccc.png)

**Comment by Kaelang** [comment]
Was this fixed with the hotfix?

**Comment by detrap** [comment]
Haven't noticed any issues since the fix, will close and open if it arises again, thank you.
