### ISSUE TITLE
Shadow Warrior Steady Aim tooltip issue.

### ISSUE THREAD

**Issue by panodill** [WarEmu/WarBugs#17441]
**Expected behavior and actual behavior:**
Tooltip on abiity say one thing and the buff say something else.
Buff is critdamage and not critrate

**Steps to reproduce the problem:**
Buff your self and hover over buff.

**Testing Screenshots/Videos/Evidences (always needed):**

https://i.imgur.com/kz2imGP.jpg
https://i.imgur.com/scXo0hg.jpg

**Comment by grunbag** [comment]
Fixed with next patch
