### ISSUE TITLE
where is step 3 and step 5?

### ISSUE THREAD

**Issue by anonymoustype** [WarEmu/WarBugs#17445]
**Expected behavior and actual behavior:**
expected: sequential set of steps for download page, starting at 1 and going to 5
actual: sequential set of steps for download page, starting at 0 and going 6, skipping steps 3 and 5.

**Steps to reproduce the problem:**
navigate to the project's download page
https://www.returnofreckoning.com/join.php#download

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/11154591/89514461-3dc00d80-d819-11ea-807f-2361a7c9fd56.png)

Please close this bug if website 
https://www.returnofreckoning.com

Is not within scope of this project.

**Comment by Kaelang** [comment]
Should probably be on the forums - the installation guide was changed and likely just haven't updated the digital order.

**Comment by anonymoustype** [comment]
cheers will do
