### ISSUE TITLE
Duplicate NPCs in the Viper Pit (IC)

### ISSUE THREAD

**Issue by VisualVirus** [WarEmu/WarBugs#17444]
After the latest patch there are duplicate NPCs in the Viper Pit, specifically the Flight Master and the Quartermaster. Screenshots attached. This was confirmed by Kaelang in-game on 05/08/20.
![Screenshot (28)](https://user-images.githubusercontent.com/21160879/89501523-c2803c80-d7c3-11ea-83ec-b935cf67f6c2.jpg). 
![Screenshot (26)](https://user-images.githubusercontent.com/21160879/89501508-be541f00-d7c3-11ea-90d4-0b037ab56444.jpg)

**Comment by Kaelang** [comment]
Additional NPC's in the Viper Pit are also duplicated and will need looking at. Reikwald (during Altdorf siege) also has duplicate Mailbox's.

**Comment by Kaelang** [comment]
This should now be fixed. Please re-open if issue persists.
