### ISSUE TITLE
CDR Tactics aren't working.

### ISSUE THREAD

**Issue by Agnus94** [WarEmu/WarBugs#17446]
Good day! I found after restarting the server that the tactics of the fire mage spontaneous Combustion does not work! It doesn't roll back for 10 seconds. and as if it doesn't exist, I tried to re-enter the game and update the client. This tactic just stopped working.
![так](https://user-images.githubusercontent.com/68962938/89529670-c927a780-d7f5-11ea-8b30-636516794813.png)

**Comment by Qilila** [comment]
Same problem here.
Restart or Repair the game, delete profil,.. nothing works.
the spell indicates: no recovery time  but tactic does not work!

**Comment by Qilila** [comment]
It's good now! BIG Thanks ! :)
