### ISSUE TITLE
Confusing Movements Moral 1 Choppa

### ISSUE THREAD

**Issue by Tenaciousbufhel** [WarEmu/WarBugs#17459]
Choppa Moral 1 Confusing Movements (Concentrating on your perceived movements, you will be able to parry and dodge all attacks against you for 7 sec)  seams to not work today. From a day play and about 40 uses it worked about twice. Not parrying or dodging any of the attacks. Worked fine yesterday. Screen shot shows one of the examples with a combat log which was about 1 to 2 second after the use of the moral. 

![image](https://user-images.githubusercontent.com/65429915/89612540-04ee5b80-d84e-11ea-8bb7-87fd502ff87c.png)

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Are you still experiencing issues? I've had no problems with Confusing Movements.

**Comment by Tenaciousbufhel** [comment]
it is better but only lasts for about 1.5 second   attaching sequence of screen shots from one 
![Lemondropp_016](https://user-images.githubusercontent.com/65429915/89720387-95888100-d99f-11ea-8f5d-3215923d10ff.jpg)
![Lemondropp_011](https://user-images.githubusercontent.com/65429915/89720389-991c0800-d99f-11ea-8d2d-d43d4685b565.jpg)
![Lemondropp_014](https://user-images.githubusercontent.com/65429915/89720393-9d482580-d99f-11ea-8dbb-cf2c81c20352.jpg)
![Lemondropp_015](https://user-images.githubusercontent.com/65429915/89720395-a0dbac80-d99f-11ea-9bd4-8c6181abba3b.jpg)



attack

**Comment by Kaelang** [comment]
Discussed with Tenacious on discord - reopen if issue persists.
