### ISSUE TITLE
[Morale] Squig Goo rank 2 Squig Herder Moral is not applying its dmg component

### ISSUE THREAD

**Issue by encadi** [WarEmu/WarBugs#17451]
The Squig Goo Moral is jsut doign ths slowing down components not the damage component after the newest patch.

**Comment by encadi** [comment]
https://i.imgur.com/bqV5Xvr.png

debuff applied but no damage numbers (neither in the combat log)

**Comment by Kaelang** [comment]
Should be fixed now.
