### ISSUE TITLE
KotBS: Vigilance and Guard ability icons are the same

### ISSUE THREAD

**Issue by detrap** [WarEmu/WarBugs#17450]
Looks like classes are getting their duplicate icons changed to help with confusion.

Here's both the duplicate icon abilities on the knight:
![Screenshot 2020-08-06 22 46 10](https://user-images.githubusercontent.com/64330047/89533873-72db5880-d837-11ea-8442-305386aa49c6.png)
![Screenshot 2020-08-06 22 46 01](https://user-images.githubusercontent.com/64330047/89533880-74a51c00-d837-11ea-9329-3b6c685009c4.png)

**Comment by grunbag** [comment]
Fixed already
