### ISSUE TITLE
[Black Orc] Ya Missed Me

### ISSUE THREAD

**Issue by Killham** [WarEmu/WarBugs#17456]
Doesnt reducing physical damage. Not even affect your target in any way. Tooltip has only ability name and duration. Does not working in pvp nor pve. Have no screenshots with .getstat from someone who affected by Ya Missed Me, but believe me if you cheked it, you have the same result - ability does not working.
![Smorcher_001](https://user-images.githubusercontent.com/18173840/89566763-533d3380-d829-11ea-9817-482b03deba85.jpg)

**Comment by Kaelang** [comment]
"it works, but you are testing on mob AA. auto attack doesn't damage type, and ya missed me works only on physical damage"

Taken from our ability dev from an older report. Please re-open with additional evidence to support this ability is not working.
