### ISSUE TITLE
[Quest] Deathbringer, Destruction @The Blighted Isle

### ISSUE THREAD

**Issue by dfumagalli** [WarEmu/WarBugs#1745]
In this quest I am supposed to kill a guy called Galdreth Lonetree, who is meant to "guard a Midnight Crystal". Well, I have killed the dude several times but he just drops vendorable or craft stuff. Around him I only see pikes and no crystal. Is it me who am blind or is the NPC meant to drop it?

Edit: since I am finding so many related issues (all about quest items not dropping) I have completely re-downloaded and reinstalled the game from scratch with no customization.

I still don't get the quest items to drop >_<

**Comment by Meralors** [comment]
FIxed, should have been closed some time ago ;)
