### ISSUE TITLE
Incorrect model for Malinora

### ISSUE THREAD

**Issue by valkeera** [WarEmu/WarBugs#17466]
At the southern edge of Ellyrion, there is a creature named Malinora which uses model of a Swordmaster.
Killing her will make her subject to Butchering skill and she yields components normally dropped by manticores.

![Cirthanir_000](https://user-images.githubusercontent.com/58527250/89674060-c6a57a80-d8e7-11ea-8380-c60605b0d2f4.jpg)

![Cirthanir_001](https://user-images.githubusercontent.com/58527250/89674084-d2913c80-d8e7-11ea-8917-27ae4f5033f4.jpg)

![Cirthanir_002](https://user-images.githubusercontent.com/58527250/89674125-e89efd00-d8e7-11ea-9bb3-566d8fbe959c.jpg)

**Comment by Lheana** [comment]
Thanks for the report, will be fixed with next patch.

**Comment by Kaelang** [comment]
This should now be fixed. Please re-open if issue persists.
