### ISSUE TITLE
Bag or texsture in Eataine

### ISSUE THREAD

**Issue by Agnus94** [WarEmu/WarBugs#17462]
Good day! Please pay attention to an interesting bug in the Eatan textures. Once there, you have no chance to get out of there in any way other than using a book or scroll. It's like you're falling into oblivion and there's no way out.
![эатан](https://user-images.githubusercontent.com/68962938/89629263-3135c680-d8a6-11ea-9b68-7a28b2ed35cf.png)

**Comment by Rockalypse** [comment]
Walked all over this spot - it requires 1 jump to get out of this spot, closing for now.
