### ISSUE TITLE
NullReferenceException was thrown from WriteWeaponDeathSpamInfo. This object will be destroyed.

### ISSUE THREAD

**Issue by b00nation** [WarEmu/WarBugs#17464]
What happened: A NullReferenceException occured in Chat window.

**Steps to reproduce the problem:**
Happened randomly, i think a magus is involved on that. But it appeared during keep fights

**Testing Screenshots/Videos/Evidences (always needed):**
![bugror](https://user-images.githubusercontent.com/25694121/89653472-70c0da80-d8c7-11ea-902a-ab44a8e8a552.PNG)

+ today
[Drastiq's Pink Horror] says: NullReferenceException was thrown from WriteWeaponDeathSpamInfo. This object will be destroyed.

**Comment by MaxHayman** [comment]
@dalen could probably do with a proper fix, but the exception wont happen

**Comment by Kaelang** [comment]
This should now be fixed. Please re-open if issue persists.

**Comment by b00nation** [comment]
1. Ok, will test it Kaelang. 

2. It happened today before the patch.
