### ISSUE TITLE
[IB] Told Ya So! not granting AP for group mates

### ISSUE THREAD

**Issue by CornerbackAC** [WarEmu/WarBugs#17469]
**Expected behavior and actual behavior:**
Expected: using grudge grants AP to all groupmates equal to the amount of grudge spent
Actual: using grudge only grants those AP to myself, but not to groupmembers

**Steps to reproduce the problem:**
Stand next to a groupmate. Groupmate uses flee. use skills that cost grudge. Groupmember gets no AP.

**Comment by Kaelang** [comment]
Flee has a secondary effect that stops the recovery of AP - I believe this extends to buffs and abilities. If you can record a video showing this without taking Flee into effect, please re-open this issue with evidence highlighting.

Thanks.

**Comment by CornerbackAC** [comment]
@Kaelang your assumption is wrong here. Flee only stops your natural AP regen. AP reg from buffs and pots is still possible (see Refreshing Radiance or AP pots for example). Also, it works on myself when I use flee and then spend grudge. I will get AP as intended. My groupmates won't get any AP when they use flee and I spend grudge.

I will try to record a video.

**Comment by Kaelang** [comment]
@CornerbackAC possibly correct with that - try to get a video and I'll take a look.

**Comment by CornerbackAC** [comment]
Two vids for you:
One showing how I get AP from the WPs Refreshing Radiance after using flee.
Second one shows a) how the WP gets AP from my Watch An' Learn after using flee and b) how only I am getting AP when we both use flee and I then spam Oathbound with Told Ya So slotted.

https://youtu.be/IiqERMmTcbk

https://youtu.be/DraAbUQODDw

**Comment by CornerbackAC** [comment]
Update: Told Ya So also does not grant AP, when the other person does not use flee.
To reproduce: Grab a tank. Make him Oathfriend. Then make him spam Hold The Line. Use flee on your own
If you burn grudge, his AP should rise or at least stop going down. Plot twist: they dont. See the video. My AP go up, his dont.

https://youtu.be/pdnWKoHOD1I

**Comment by Kaelang** [comment]
This should now be fixed. Please re-open if issue persists.
