### ISSUE TITLE
Reikwald - re-entering location after crash sometimes wrong

### ISSUE THREAD

**Issue by CornerbackAC** [WarEmu/WarBugs#17465]
There is some random issue with the re-entering location in Reikwald after game crashes as a defender

**Expected behavior and actual behavior:**
Expected: After crashing as defender in Reikwald (which itself seems like an issue to me), you re-enter the fort at the spot where you crashed
Actual: sometimes, you re-enter at the Altdorf postern door where order enters Altdorf when it is under siege. Then you have to walk all the way back into the fort, which is impossible most of the time when the lord room is under attack.

**Steps to reproduce the problem:**
Fight in Reikwald. Wait for a crash. Re-enter. Sometimes you will re-enter in your old spot. Sometimes at Altdorf's postern door.

**Testing Screenshots/Videos/Evidences (always needed):**
Don't have any atm

**Comment by Kaelang** [comment]
Crashes aren't realistically bugs - appreciate the report however we can't identify game related issues when server instability is taken into effect. If you notice issues without crashes being involved, please re-open such ticket.

**Comment by CornerbackAC** [comment]
Its not about the crash. Its about the issue, that there seems to be a respawn point at Altdorfs postern door that is randomly used when the fort is still being sieged. Anything you can do about this?
