### ISSUE TITLE
[Quest] Lionsbane banner, Destruction @The Blighted Isle

### ISSUE THREAD

**Issue by dfumagalli** [WarEmu/WarBugs#1746]
Hello,

I kill the Gaethin Whitemane NPC but he won't drop his shield (quest item).

**Comment by Meralors** [comment]
Same as #1747 and #1737 , I'm trying to figure out why its happening

**Comment by Reggaewaldo** [comment]
It will be fixed with next update that should happen rather soon. The issue is that the quest DB has not been updated.
