### ISSUE TITLE
[Quest] Due Recognition, Destruction @The Blighted Isle

### ISSUE THREAD

**Issue by dfumagalli** [WarEmu/WarBugs#1747]
Hello,
I am meant to kill Councilman Taralion and take his head.
Sadly, he won't drop me his head, even farming him.

**Comment by Meralors** [comment]
Ok this is same issue as #1737 , its working on dev but not on live. Wait for next patch to see if it fix it.

**Comment by Reggaewaldo** [comment]
It will be fixed with next update that should happen rather soon.
