### ISSUE TITLE
[Gunbad] Boss not dead, no loot, cant progress.

### ISSUE THREAD

**Issue by XmatXergon** [WarEmu/WarBugs#17478]
We were fighting one of the gunbad bosses on left wing, Garrolath the Poxbeare, we killed him, but apparently game decided he cannot be killed, and hes dead body was following us.

No chest, no loot and no PQ contribution which means we cannot go through barrier to last boss on left wing.

Video below:
https://youtu.be/2ke_ISIGXO8

**Comment by Kaelang** [comment]
This should now be fixed. Please re-open if issue persists.

**Comment by Kaelang** [comment]
This boss is still bugged.

**Comment by dalen** [comment]
This should be fixed now
