### ISSUE TITLE
Potential Road to Madness

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#17472]
I am able to capture the points and get credit (although credit for the glyphs of madness and fury are reversed), what I discovered was that I could get credit for taking the warpstone talisman after the scenario had ended and everyone else had left. I am not sure if this working as intended or is a bug.

I forgot to take a screenshot when it occurred and have completed credits so I cannot replicate it

**Comment by Kaelang** [comment]
#17471
