### ISSUE TITLE
Glyph of Madness credit

### ISSUE THREAD

**Issue by btbw2020** [WarEmu/WarBugs#17471]
Cannot complete Capture Glyph of Madness step in scenario event.
30 times played, many wins, sometimes take it by myself and still no credit!
https://i.imgur.com/AK0l8pG.jpg

**Comment by nutspanther** [comment]
I have the same issue

**Comment by btbw2020** [comment]
Correction - now all glyphes is bugged and dont give credits. Only warpstone talisman working.
Please fix it ASAP!

**Comment by Sivine** [comment]
Objectives are missnammed, try another stone, it wroked for me.

**Comment by Kaelang** [comment]
Managed to complete this fine - additional information please.

**Comment by btbw2020** [comment]
Sure thing - we have ALL glyphs and talisman. Still no credit!
https://imgur.com/a/aLbzSTL

**Comment by Lheana** [comment]
You must take it yourself for it to count.

**Comment by btbw2020** [comment]
No, you dont! Im dont do it on 2 chars and got credits. Even if you true then it wrong way to claim credit! 
And read first post - im taken all these glyphs and talisman and dont get credit for it!!!

**Comment by Kaelang** [comment]
The task itself is working, as I've completed it, and others have. Are there potential issues with tracking? Sure. I'll see if someone can take a look.

**Comment by btbw2020** [comment]
Im told - this work strange. Im done it with 2 chars even without touch stones. And 2 others cannot complete with wear it and win.

**Comment by Rydiak** [comment]
On Order, quest credit for Glyph of Fury is gained by capping Glyph of Madness, and quest credit for Glyph of Madness is gained by capping Glyph of Fury (they are reversed).

**Comment by Kaelang** [comment]
This should now be fixed.
