### ISSUE TITLE
SM Vanquisher helm bug

### ISSUE THREAD

**Issue by kirraha** [WarEmu/WarBugs#17474]
I saw an old thread on the matter but it was closed, though issue was not fixed. 

The Vanq helmet for SM is not dyable and does not show on char. 
No, ''show item'' is not off, the helmet does not show. I have tried several things as swapping gear etc, but it does not work. 
![Fahrain_001](https://user-images.githubusercontent.com/61003952/89710412-1c7b3080-d983-11ea-83f7-862ad5af0ef0.jpg)

**Comment by Kaelang** [comment]
Not all items can be dyed - can you find proof to suggest this item should be dyeable?

**Comment by kirraha** [comment]
I dont rly care about the dye option, but I would guess it says not dyable cause the item does not show at all. I added it as a detail to the bugreport. 

The helmet is not visible.

**Comment by wargrimnir** [comment]
Fixed and confirmed this time. It was also causing the Oppressor helmet to not show, but I guess that one isn't used as much.
