### ISSUE TITLE
Killing Shadowblade doesn't register as the last step of Unmasking the Enemy questline.

### ISSUE THREAD

**Issue by baroke** [WarEmu/WarBugs#17479]
Killing Shadowblade doesn't register as the last step of Unmasking the Enemy questline.

**Expected behavior and actual behavior:**
Killing Shadowblade should complete the quest; it doesn't.

**Steps to reproduce the problem:**
Try to do the last step of this Epic.

As shown in the screenshot, my quest is still 0/1 while at the same time on the chat log you can see that i have killed ShadowBlade.
![image](https://user-images.githubusercontent.com/20115114/89719392-6dfddc80-d9d0-11ea-9518-f529fba99d9d.png)

**Comment by Lheana** [comment]
That's because the quest is not asking you to kill Shadowblade here, but Masked Shade.
