### ISSUE TITLE
Potion being removed after death

### ISSUE THREAD

**Issue by Latnemurtsni** [WarEmu/WarBugs#17481]
About 2 hours of gameplay and have wasted 5 Ballistic potions because everytime I die it goes away from my buffs, not sure if that is something that has been reported. Thanks in advance edit- just found it it is being removed when I switch stances as a Shadow Warrior. I had a full refreshed pot, switched stances and now its gone.

**Comment by Kaelang** [comment]
Use .getstats to see if the effect is being removed, of it is visual please. And follow the format - I need screenshots / video.

**Comment by Haojun-Phalanx** [comment]
it's a visual bug. pretty annoying tho.

**Comment by Latnemurtsni** [comment]
I’ll pull up my vod and clip it. That way you can see. - Feven

**Comment by Latnemurtsni** [comment]
So yeah I used .getstats and the potion was still applied but the visual stance does go away.

Here is the clip on my stream so you can see it.  

https://clips.twitch.tv/MoralPowerfulBatRlyTho

**Comment by dalen** [comment]
I've made some fixes for today's patch to avoid issues with stance dropping randomly. Not sure it will fix it all, but lets see.

When I try it solo on dev server it usually doesn't happen, even before those fixes.
