### ISSUE TITLE
no goldbag in city

### ISSUE THREAD

**Issue by grimstuck** [WarEmu/WarBugs#17485]
hello this morning i do a city 3 stars ( IC )  and at every round we never have gold bag

i have only 2 screenchoot i forgot to take screenshoot of the first round 

My caracter name is Azgedo

sorry for my english i'm french

SECOND ROUND
![Azgedo_043](https://user-images.githubusercontent.com/63030421/89732456-5fa2d580-da4f-11ea-89c3-c96a35b233e8.jpg)

THIRD ROUND
![Azgedo_044](https://user-images.githubusercontent.com/63030421/89732457-616c9900-da4f-11ea-823b-18cfd1be3b96.jpg)

**Comment by Rydiak** [comment]
You had less than 24 players on your side, which after the last patch currently clips the top-tier bags (scaling with the number of people you have under 24) from the loot pool.  I _believe_ that next patch it will clip from the bottom-tier bags first before clipping from the top-tier.

**Comment by grimstuck** [comment]
no my guild in an other 12 man have gold bags

**Comment by Kaelang** [comment]
This should now be fixed. Please re-open if issue persists.
