### ISSUE TITLE
Sacrificial Stab doesn't apply the Auto Attack damage increase

### ISSUE THREAD

**Issue by Jazz405** [WarEmu/WarBugs#17489]
Sacrificial Stab isn't applying the X% autoattack damage buff.
 
I removed all tactics, logged out to remove all buffs. 
Attack Damage numbers: MH - 105, OH - 87
The heal for Sacrificial Stab is ocurring and the buff is showing on my character, but the damage numbers aren't effected. 

**Expected behavior and actual behavior:**
Expected Behavior 
    5 Blood lust -> Auto Attack Damage: MH - 157, OH -130
    This should represent a 50% auto attack damage increase
Actual Behavior
    The Sacrificial Stab Blessing  displays and the heal occurs, but there is no change to AA Damage

**Steps to reproduce the problem:**
1 - Removed Tactics
2 - Went to Target dummy, built up Blood lust while recording AA strikes
3 - Used Sacrificial Stab
4 - Check AA Numbers

**Testing Screenshots/Videos/Evidences (always needed):**
Sacrificial Stab Text:
    ![image](https://user-images.githubusercontent.com/5931808/89792477-9978e800-daf2-11ea-9596-9a689fa933a1.png)

My Log
![image](https://user-images.githubusercontent.com/5931808/89794129-a1d22280-daf4-11ea-8ab2-033b35ae7bb4.png)

**Comment by Bobbiom** [comment]
This holds true to the invader set piece bonus aswell, the autoattack damage proc buff for melee dps.
You get the buff icon on you but the damage does not increase.

**Comment by Kaelang** [comment]
This should now be fixed. Please re-open if issue persists.
