### ISSUE TITLE
Problems or Rain Fire ability BW

### ISSUE THREAD

**Issue by Agnus94** [WarEmu/WarBugs#17484]
![дж](https://user-images.githubusercontent.com/68962938/89730025-ad194580-da43-11ea-8d2f-7b257615a1b5.png)
Good day! There is another bug, after updates with the range of the Rain Fire  ability. When using it, if the enemy is at a distance but within range of the radius, an error occurs in which the animation freezes and writes that there is not enough range to hit the target. Please fix this error, I think many magicians noticed this problem.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17398
