### ISSUE TITLE
so viele Atacken in "nur 5 sec"??????

### ISSUE THREAD

**Issue by tquirl745** [WarEmu/WarBugs#17487]
hallo, habe gerade das event scenario gespielt und da ist mir der cobat log eines weißen löwen aufgefallen.
![Tantras_002](https://user-images.githubusercontent.com/69433208/89739198-f76be800-da7e-11ea-9216-9d2585a6f6cd.jpg)

ich finde es ein wenig viele atacken. bitte einmal nachschauen und gegebenenfalls gegen diesen spieler vorgehen.
danke

mfg tantras (ingame name)

**Comment by junkjunk4** [comment]
![Ducktator_019](https://user-images.githubusercontent.com/52129228/89913687-4e46fe00-dbf4-11ea-9a0f-cc3352c7d4ca.jpg)
easier to see, happened to me aswell. FO and Blindside at :48

**Comment by junkjunk4** [comment]
![Ducktator_016](https://user-images.githubusercontent.com/52129228/89914569-7aaf4a00-dbf5-11ea-942e-e10d68b49e79.jpg)

at :06 Brutal assault, crosscut

**Comment by tquirl745** [comment]
hiho
passiert hier auch mal was?

**Comment by tlitschye** [comment]
is doch normal...wenn du sogar 5 sec überlebt hast passt doch.
Gegen einen best equipten WL passt das. Du hast 2 dots bekommen blindside und shattering blow dann armordebuff und coordinated strike.

**Comment by grunbag** [comment]
write in english please
