### ISSUE TITLE
Falling through a crack in city at stage 1 at Sun Dragon and getting stuck

### ISSUE THREAD

**Issue by Throlla** [WarEmu/WarBugs#17486]
I seen several ppl falling through and getting stuck. Now I tried it for myself in two cities in a row, so I just wanted to make a notice about it. When in a city I would not recomment you to use "stuck command. But you cant get away until end of stage 1 where you can use army recall.

// Cheers

![IMG_5828](https://user-images.githubusercontent.com/66037149/89737605-7575c200-da72-11ea-8680-afcea34c38a1.jpg)
![IMG_5827](https://user-images.githubusercontent.com/66037149/89737606-760e5880-da72-11ea-8f7f-5fd364d3621f.jpg)
![IMG_5826](https://user-images.githubusercontent.com/66037149/89737607-760e5880-da72-11ea-9761-a07ceb07cf21.jpg)

**Comment by Kaelang** [comment]
"When in a city I would not recomment you to use "stuck command. "

This is actually our recommendation. We changed the stuck command recently to bring you to spawn, not to your book location.
