### ISSUE TITLE
Maw of Madness

### ISSUE THREAD

**Issue by Tinkaballa** [WarEmu/WarBugs#17483]
The Maw of Madness weekend event has 3 objectives in the Tome of Knowledge to Capture the Glyph of Madness, the Glyph of Fury and the Warpstone Talisman as part of the 7 tasks to complete.

No matter how many times I pick up the Glyph of Fury I dont get credit for it in the Tome, the other 2 (Madness & Warpstone) I had no problem with I got credit for them first pickup.

I have tried this on a White Lion level 8 a level 22 Engineer, the only character who I have had any luck with is a level 14 Ironbreaker.

**Comment by detrap** [comment]
Madness orb is not given credit atm even after picking it up twice in one sc

**Comment by Tinkaballa** [comment]
I'll also add that the Ironbreaker did it all on Friday evening, the Engineer and the White Lion both tried to complete it on Saturday.

**Comment by dalen** [comment]
This should be fixed now.
