### ISSUE TITLE
Challenger Boots Talisman 

### ISSUE THREAD

**Issue by Barrett27** [WarEmu/WarBugs#17482]
Cannot equip talisman on the choppa challenger boots

**Comment by Kaelang** [comment]
Screenshots please, talisman and item.

**Comment by Barrett27** [comment]
![Battleclaw_004](https://user-images.githubusercontent.com/69409122/89738674-7eea3480-da48-11ea-83d6-869f56bdd922.jpg)
![Battleclaw_002](https://user-images.githubusercontent.com/69409122/89738708-ab05b580-da48-11ea-893e-db18f26ace8c.jpg)
Item / Talisman ss's

**Comment by Kaelang** [comment]
Talisman level 16
Item level 15.
