### ISSUE TITLE
black crag wall climb glitch

### ISSUE THREAD

**Issue by squirel1210** [WarEmu/WarBugs#17480]
<!-while attacking in black crag i saw a group of order run to the side of a cliff wall and teleport up the wall ontop of the mountain to make for a faster run to the other side doesnt seem right to me even if i am order  coordinates for this bug area are 34690, 10792 
Issues should be unique. Check if someone else reported
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.
-->

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Screenshot please.

**Comment by squirel1210** [comment]
unfortunately i cant recreate the glitch it was during a siege so could
have been lag, i will keep an eye out the next time we are fighting in
black crag however i didnt think at the time to take a screen when it was
happening
