### ISSUE TITLE
CoD mail bug ? / Lost 400x Gobsworth due to receipient not being able to pay and sent the mail back. Items are lost in the process

### ISSUE THREAD

**Issue by Althesian** [WarEmu/WarBugs#17496]
Hi, this isn't the first time it happened, also happened a few months back - but it was a small item. now it's kind of a big amount. and i do wanna make a bug report about it / I sent a few CoD's to Babybullet ( Flowers for apothecary ) in one of those cods were 400x taut gobswort - he couldn't afford them appareantly so sent the CoD back. but alas, the flowers were gone. i got stream footage of it 
https://www.twitch.tv/videos/706953797  timestamp 00:10:30 minutes into the VOD u'l see me logging my Swordmaster and heading to the mailbox to collect my mail.

Hopefully il get my flowers back :/ literal 5+ hours of cultivating lost in one mail

**Comment by Kaelang** [comment]
I can confirm you won't get your flowers back if the system has broken somehow. We don't get involved with item requests. However I will test this and see if I can replicate so it doesn't happen again.

**Comment by Althesian** [comment]
:)

**Comment by Kaelang** [comment]
A side-fix was pushed in the last patch.
