### ISSUE TITLE
City Siege Rewards Not Calculated Properly

### ISSUE THREAD

**Issue by Haojun-Phalanx** [WarEmu/WarBugs#17497]
Have 24v24 instance, having only 1 gold bag. 12/08/2020 Instance 12
![Haojun_002](https://user-images.githubusercontent.com/23129933/89957707-c63b1580-dc40-11ea-8a9d-daffd61dc9fd.jpg)

**Comment by Niall86** [comment]
If just one is DC'ed or quitted and there are only 23 left in the mirror - you getting 23
I don't think it's fair tho, I'd expect 2 golden bags for 19-24 men instances , while lowering to 1 gold bag only for 18 and less

**Comment by Kaelang** [comment]
@dalen Is this one for tomorrow?

**Comment by dalen** [comment]
yeah, it is in patch for tomorrow

**Comment by Kaelang** [comment]
This should now be fixed. Please re-open if issue persists.
