### ISSUE TITLE
Bladeshield doing 2k damage per tick

### ISSUE THREAD

**Issue by trubikal** [WarEmu/WarBugs#17490]
**Expected behavior and actual behavior:**

Today when I used the Swordmaster moral 3 Bladeshield I noticed it doing 2000-2300 damage per tick
instead of 600. This was on several players at the same time. 
I also noticed that my normal attacks did alot more damage then normal for a short moment as seen in the 
added video.

**Steps to reproduce the problem:**
I tried to reproduce it in a duel and in orvr, once each with no luck.
 Both times against a DoK.

**Testing Screenshots/Videos/Evidences (always needed):**

![Warhammer Online - Return Of Reckoning Screenshot 2020 08 10 - 08 00 53 04](https://user-images.githubusercontent.com/69470031/89797893-cac1da00-db2b-11ea-9950-51025ae5be98.png)
![Warhammer Online - Return Of Reckoning Screenshot 2020 08 10 - 08 00 49 99](https://user-images.githubusercontent.com/69470031/89797934-d7dec900-db2b-11ea-99b9-176ff65a72bf.png)

https://giant.gfycat.com/GrandioseFelineBats.webm

**Comment by Kaelang** [comment]
![image](https://user-images.githubusercontent.com/60117106/89800498-cba43d00-db26-11ea-8b0f-252433cb6bfc.png)

Will look to test on a player.

**Comment by Kaelang** [comment]
![image](https://user-images.githubusercontent.com/60117106/89802593-9baa6900-db29-11ea-804e-9f960519cb9d.png)

Tested on player and looks to be working as intended. If you can replicate the strange occurance please re-open the ticket with additional information and steps.

**Comment by Lheana** [comment]
As a note, the reason of your damages is because you are close to your warcamp. There is an invisible buff/debuff near the warcamps to prevent players from camping the warcamps that increases the damages when you are close to your warcamp.
