### ISSUE TITLE
Insta killed by player.

### ISSUE THREAD

**Issue by Druffz** [WarEmu/WarBugs#17495]
Got instakilled by enemy player.  It wasn't fight between warbands. Pretty much empty Praag, was passing by order warcamp, and suddenly died. WH shouldn't be able to kill doing 7k+ damage in less than a second.  I tought warcamp guard killed me, but it wasn't the issue. Seemed like a bug or a hack.

![Druffzz_000](https://user-images.githubusercontent.com/69489572/89844044-ae00c300-db7a-11ea-87a8-242363006008.jpg)

**Comment by Kaelang** [comment]
You was too close to the camp. Players get buffed.
