### ISSUE TITLE
[The Ebon Flame] T4 Dark Elf Epic Quest: Keeper of the Way spawned inside building texture

### ISSUE THREAD

**Issue by Algenubi** [WarEmu/WarBugs#17494]
During T4 Dark Elf Epic Quest 'The Ebon Flame' there is a step to kill Keeper of the Way (Eataine 57k 63k). When I reached its spot, where glowing orb placed, there was no Keeper on his usual place. But using 'Tab' button I found Keeper alive, but he was placed inside elven building, about 20 ft to the east of his usual place. With help of GM Ravenmaster I get credit of Keeper murder, and next time Keeper respawn near orb, on correct spot. However, there is a chance (?) to Keeper to respawn inside the texture, where usual player cannot reach him.

**Comment by Lheana** [comment]
He did not spawn inside the building, someone has pulled him but did not kill him and he was stuck inside. I close the ticket as there is already a ticket for this kind of issues.
