### ISSUE TITLE
Bugging oil fall on the ground after use.

### ISSUE THREAD

**Issue by Killham** [WarEmu/WarBugs#17507]
Oil dropped on the ground behind the 1st keep door. Aoe from oil hitting those who stayed on the ram, but noone can hit oil.
Its happened like now on reikland order keep. Cant present screenshots cause somehow none of them aint save exactly in this case.

**Comment by Kaelang** [comment]
This is a legacy issue, unable to replicate - believe it's lag related in circumstances. Regardless, it's known and I'm confident there is already a issue listed for this.
