### ISSUE TITLE
Daemonic Armor for Magus visual buff bug

### ISSUE THREAD

**Issue by Tradwarden** [WarEmu/WarBugs#17508]
**Expected behavior and actual behavior:** 

**Expected** - Daemonic armor is a 60 minute buff and will show in your buffs bar the entire time.
**Actual behavior** - If you get on your disc mount, the buff visually disappears from your buff bar, will sometimes reappear after some time, only to disappear again.  (From my testing, the armor is still buffed, only the buff will not show)
This is troublesome as it might lead you to believe the buff has been disenchanted and will try to recast it, which will look like it doesn't work, until it reappears. 

**Steps to reproduce the problem:**

1. Apply Daemonic Armor
2. Get on your mount
3. Buff should almost always disappear

**Testing Screenshots/Videos/Evidences (always needed):**

https://clips.twitch.tv/SneakyCourageousJuiceMoreCowbell (couldn't upload mp4 directly)

**Comment by Kaelang** [comment]
This should've been addressed in a previous patch - please re-open if issue persists.
