### ISSUE TITLE
Bleed em Out can be abused to received 1 additional tick

### ISSUE THREAD

**Issue by Zunig** [WarEmu/WarBugs#17506]
After today patch that affects how dots work, it is possible to reapply Bleed em out just after its first dot tick to cause 1 additional tick with escalating dmg buff. 
End result in the screenshot. Previously, tick before new final one would be the last one if dot run full 10s duration.

![WAAAGH](https://user-images.githubusercontent.com/60852506/90025974-05a44900-dcb7-11ea-8caa-5879659ce03e.jpg)

**Comment by dalen** [comment]
right, should probably exempt ramping dots from this mechanic. It is only Bleed Em out that is a ramping damage one.

**Comment by Grey-Rogue** [comment]
Will that be fixed for Inevitable Doom and all the other ramping damage abilities game wide?

**Comment by Kaelang** [comment]
Fixed in hotfix.
