### ISSUE TITLE
Squig Herder: pets no longer applying buffs to player as of 12/8/20 patch.

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#17504]
**Expected behavior and actual behavior:**

Gas Squig: not granting +10% ability range
Horned Squig: not granting bonus armour
Spiked Squig: not granting bonus ranged crit

Unable to test basic squig.

**Steps to reproduce the problem:**

Summon each squig and check character sheet. No stats change and the squig-specific buff doesn't appear in your buff list.

**.getstats has been tested and the values didn't change there either**

**Testing Screenshots/Videos/Evidences (always needed):**

Gas Squig (look at ability range - still 100ft)

![Fotm_040](https://user-images.githubusercontent.com/60266177/90013461-37a8b180-dc9d-11ea-8380-c9aac2e2456e.jpg)

Horned Squig (no squig and with squig - look at armour)

![Fotm_041](https://user-images.githubusercontent.com/60266177/90013494-455e3700-dc9d-11ea-8633-a3607fb35fc8.jpg)
![Fotm_042](https://user-images.githubusercontent.com/60266177/90013521-53ac5300-dc9d-11ea-92a7-c8524a59ea70.jpg)

Spiked Squig (no squig and with squig - look at ranged crit)

![Fotm_043](https://user-images.githubusercontent.com/60266177/90013569-6cb50400-dc9d-11ea-9ecc-4b580927fe46.jpg)
![Fotm_044](https://user-images.githubusercontent.com/60266177/90013589-78a0c600-dc9d-11ea-9b26-c286378e4773.jpg)

**Comment by Kaelang** [comment]
Will be interesting to see if Engineer / Magus pets have the same issue - thanks for the report.

**Comment by Sivine** [comment]
Video proof : https://imgur.com/a/HMimQik
It does not changes stats, it's most definitively linked to the fact that the pet does not provide any buff.
On top of that squigs does not have any ability as you could see on the video.

**Comment by Kaelang** [comment]
This should be fixed now.
