### ISSUE TITLE
Launcher Crash Issue

### ISSUE THREAD

**Issue by Machiara** [WarEmu/WarBugs#17509]
Hi all,

My son is having a problem launching the game.  His computer updated (I'm not sure if it was from a game patch or a Windows update) and when he hits "connect" from the launcher he gets the attached text.  We restarted his computer and even reloaded the game (twice) but still get the same message.  My game and his older brother's game is fine.  Any ideas what is going on here?  He's really disappointed that he can't play.

-Todd
![Launcher Issue](https://user-images.githubusercontent.com/69600855/90054738-1a6de600-dc91-11ea-8dbe-38200cb06b7b.jpg)

**Comment by Kaelang** [comment]
Please use Technical Support - this is a tracker for ingame bugs and broken features, not a support system.
