### ISSUE TITLE
Quest issue: [Control] 

### ISSUE THREAD

**Issue by NimeriaEverstar** [WarEmu/WarBugs#17502]
**Expected behavior and actual behavior:**

     I started the [Control] quest a long time ago, probably an old version of the epic quest. Upon revisiting the starter NPC for 
     [Control] , the NPC asks to complete a step that isn't available on my map( Investigate the Uthorin woodcutters camp in the 
     Eldhrel's lament...). The quest isn't even in my tome eventhough the 
     NPC recognizes that I had the old quest version of control. 

**Steps to reproduce the problem:**
     Visit Ch 10 Avelorn
     Click on Gethlan Stormwood
     Click on [Control]
 
     *See screen clips

**Testing Screenshots/Videos/Evidences (always needed):**
  

![Screenshot from 2020-08-11 21-13-31](https://user-images.githubusercontent.com/69556440/89964316-d4287080-dc17-11ea-8835-8a02b07095d0.png)
![Screenshot from 2020-08-11 21-13-56](https://user-images.githubusercontent.com/69556440/89964319-d5f23400-dc17-11ea-9d08-fdd079b72ee1.png)

**Comment by Lheana** [comment]
Screenshot of your quests in your ToK please.

**Comment by NimeriaEverstar** [comment]
![Screenshot from 2020-08-12 23-09-42](https://user-images.githubusercontent.com/69556440/90099860-6a888f00-dd09-11ea-977a-0618e3b2ea89.png)
![Screenshot from 2020-08-13 02-03-29](https://user-images.githubusercontent.com/69556440/90099865-6bb9bc00-dd09-11ea-8792-dda7841d3abe.png)
![Screenshot from 2020-08-13 02-03-43](https://user-images.githubusercontent.com/69556440/90099868-6c525280-dd09-11ea-95a6-e8af1e7e1624.png)

**Comment by NimeriaEverstar** [comment]
Thank you. I will check back to see if it's been resolved.

**Comment by Lheana** [comment]
I don't know why you can see it, but you have done the whole epic quest.

**Comment by NimeriaEverstar** [comment]
I'm looking for the staff that Amidala use to use as her staff skin. The one with the heart gem in the center. Do you recall which staff that is? i thought it was T3 Epic.

**Comment by Lheana** [comment]
The Bugtracker is made for **bugs**, it is not made to find the appearance you are seeking. Use the forum to do so.
