### ISSUE TITLE
Area over a choke point only order can get too

### ISSUE THREAD

**Issue by Carcharadon** [WarEmu/WarBugs#17515]
in side BV next to the tunnel on way to the keep is that small choke point with a over hang from a cave on Order side 

**Expected behavior and actual behavior:**

Move cave entrance or block it off / move order NPC guards to not block the way too it 

**Steps to reproduce the problem:**
I highlighted the engie up there with a WP that is untouchable for heals you can see where i cam on the mini map 

![WAR-64 2020-08-12 21-38-10](https://user-images.githubusercontent.com/55959616/90088447-95142100-dce4-11ea-8252-6d53bb79097f.png)

**Comment by colintgallagher** [comment]
You can get to it from the side you're on, it's just tricky.
