### ISSUE TITLE
Foul Works: P3

### ISSUE THREAD

**Issue by Behemoth1997** [WarEmu/WarBugs#17517]
Cannot complete the quest due to Cluster of stench item not appearing in my quest items tab?
I've made sure that someone has not reported this bug already and it seems I'm the only one having this issue. 
![Foul Works](https://user-images.githubusercontent.com/69627046/90119367-17213b80-dd1f-11ea-925b-7526164d5994.jpg)

**Comment by Lheana** [comment]
Abandon the quest and take it again.
