### ISSUE TITLE
RAMPING DAMAGE DOTS and channels Broken

### ISSUE THREAD

**Issue by Carcharadon** [WarEmu/WarBugs#17510]
DOTs and channel skills seem to be hitting 2x as much and some like the Slayer/CHoppa 2h bleeds for WAY too much damage 

**Expected behavior and actual behavior:**
slow tic/ reduce damage or something went wrong with the toughness fix 

**Steps to reproduce the problem:**
more testing 

Drag and drop an image file here to include it directly in the bug report,
     no need to upload it to another site 

check time stamps on screens , had banner up but it is crazy in game with dot based attacks at the moment
![1](https://user-images.githubusercontent.com/55959616/90055424-eef3f700-dca2-11ea-8095-5486353f9e8b.png)
![2](https://user-images.githubusercontent.com/55959616/90055432-f1565100-dca2-11ea-9243-eb3f320912df.png)
![3](https://user-images.githubusercontent.com/55959616/90055437-f3201480-dca2-11ea-94f2-ad093280d94d.png)
![4](https://user-images.githubusercontent.com/55959616/90055444-f4e9d800-dca2-11ea-81b7-43acda21e620.png)
![5](https://user-images.githubusercontent.com/55959616/90055449-f74c3200-dca2-11ea-989a-ff058ada8216.png)
![6](https://user-images.githubusercontent.com/55959616/90055457-f9ae8c00-dca2-11ea-95a7-2756cfa90b55.png)
![7](https://user-images.githubusercontent.com/55959616/90055463-fc10e600-dca2-11ea-82e5-7bb69236842a.png)
![8](https://user-images.githubusercontent.com/55959616/90055467-fddaa980-dca2-11ea-9e7f-db3ff4082452.png)
![9](https://user-images.githubusercontent.com/55959616/90055471-ffa46d00-dca2-11ea-93ca-6cc2da33f033.png)
![91](https://user-images.githubusercontent.com/55959616/90055484-0206c700-dca3-11ea-8ed2-b80dc131399a.png)
![93](https://user-images.githubusercontent.com/55959616/90055491-03d08a80-dca3-11ea-9cd0-7816a5f64350.png)
![94](https://user-images.githubusercontent.com/55959616/90055495-059a4e00-dca3-11ea-9899-df4c49f602b1.png)

**Comment by Rydiak** [comment]
It looks like you were being attacked by over a warband's worth of players. Do you have any screenshots of your combat log? If you do, I can parse the damage and mitigation and see if the damage formula is working correctly.

**Comment by Grey-Rogue** [comment]
These are my screen shots. Couldn't post until I got of work so Carcharadon posted them for me. 

I did in fact have an entire warband on me. I had the banner blessing on so that's why I was only taking 1 damage. 
Dots from individual players seemed to be ticking more than once every two seconds. 

I wont pretend to know what all these abilities hitting me do, but Inevitable Doom from Arwwhin hit once per second for 3 seconds in a row. Flame of Rhuin from Sellz hit twice in one second.  Relentless Strike from Xantho hit three times in three seconds.

**Comment by Tesq** [comment]
same thing in  ranked sc once today a  slayer was  hitting under ID for shittons of dmg, 

like 5/6 ppl  guarded etc dropped by 1/4 of life in 1 gcd with after an id tick, i duno if this a bug with the new dot thing or is the change to dmg formula but some dmgs are off.

**Comment by Carcharadon** [comment]
it wasn't the damage  per-say we were highlighting Rydiak it was the time stamp on the highlighted name , multiple hits pet GCD and  extra ticks of skills / look into that  something is definitely broken

**Comment by Carcharadon** [comment]
RAMPING damaging all skills that do this are broken! choppa and slayer maybe engie

**Comment by Rydiak** [comment]
https://github.com/WarEmu/WarBugs/issues/17506

Presumably related/same bug?

**Comment by Carcharadon** [comment]
im guessing all ramping

**Comment by dalen** [comment]
> im guessing all ramping

there's only one ramping dot, Bleed Em out and that's fixed now.

**Comment by Carcharadon** [comment]
well then it must be just DOTs then in general

**Comment by Kaelang** [comment]
This was addressed in the hotfix.
