### ISSUE TITLE
Squigbeast and Squig Frenzy doesnt buff pet

### ISSUE THREAD

**Issue by Rokrag** [WarEmu/WarBugs#17512]
**Expected behavior and actual behavior:**
Squigbeast m3 for sh is supposed to triple the pets damage but it does not.
Squig Frenzy is supposed to increase pets auto damage by 50% but it does not.

**Testing Screenshots/Videos/Evidences (always needed):**

no buffs
![petdamagewithoutbuffs](https://user-images.githubusercontent.com/39213178/90069678-a0555580-dcc0-11ea-942b-9522f6dfb1c8.jpg)

squig frenzy buff up
![squigfrenzydamage](https://user-images.githubusercontent.com/39213178/90069646-959ac080-dcc0-11ea-9a51-f8dd501a5931.jpg)

squig beast buff up
![squigbeastdamage](https://user-images.githubusercontent.com/39213178/90069601-8582e100-dcc0-11ea-97e8-91e4fa63af8a.jpg)

**Comment by grunbag** [comment]
Both work fine now
