### ISSUE TITLE
Endless pandemonium allows double stacks since DOT Changes

### ISSUE THREAD

**Issue by iantheace** [WarEmu/WarBugs#17518]
Since the changes to DOT application, if you equip the endless pandemonium tactic, you can stack pandemonium multiple times. Note i used this once just to demonstrate it works on players, but i cant not use it by accident as its AOE.

Please see video at

http://rgupdates.co.uk/PandemoniumBug.mp4

**Comment by dalen** [comment]
This isn't actually related to the dot changes, was like this before as well. But created a fix for it now.

**Comment by Rydiak** [comment]
From a post on the forums. The defender appears to have 2 separate Pandemonium stacks on him, which tick 1 second apart from each other at 3 second intervals.

**Comment by iantheace** [comment]
This no longer seems to occur so assume its fixed

**Comment by Zomega-WAR** [comment]
According to Discord today, this is still bugged:

![image](https://user-images.githubusercontent.com/60266177/147579566-106f81c9-73a9-46a7-9d74-28124eeeab78.png)
