### ISSUE TITLE
RVR Green Bag Royal Crest

### ISSUE THREAD

**Issue by Thoraxel** [WarEmu/WarBugs#17511]
From the patch notes today it was my understanding that we would get royals from green bags but I got a green bag from reikland at just after 5pm UK time so after the patch and the bag didn't have any royals or invaders inside of it. I have full invader set and full vanq set so it should have the option for 1 royal or invader for me to choose from. 

My TOK armory showing full invader: 
![image](https://user-images.githubusercontent.com/67516894/90064945-677aa800-dce3-11ea-85d0-488ed8244a38.png)

Contents of the bag:
![Green bag 1](https://user-images.githubusercontent.com/67516894/90063010-96dbe580-dce0-11ea-9db3-444a460807e6.PNG)

Where and when i got the bag:
![Green bag 2](https://user-images.githubusercontent.com/67516894/90063011-97747c00-dce0-11ea-8409-8d3a206a427d.PNG)

**Comment by Niall86** [comment]
Still the same
![image](https://user-images.githubusercontent.com/1152711/90066058-e11b9180-dcf5-11ea-8d6a-c352482cf872.png)

**Comment by JackHollowPoint** [comment]
Same behavior. No Invader medals in rvr bags after patch. 
![Yncarne_005](https://user-images.githubusercontent.com/25168701/90123092-f2e94d00-dd66-11ea-9fd4-be84fe6e7f45.jpg)

**Comment by CornerbackAC** [comment]
Confirmed. Neither Invader nor Royal in green for my full Invader IB.

**Comment by Kaelang** [comment]
Fixed in hotfix.
