### ISSUE TITLE
Hitting ram and players true doors with autoattacks...

### ISSUE THREAD

**Issue by licenje** [WarEmu/WarBugs#17522]
as title says ram geting hit with auto attacks and you can hit players to...
![Nasilje_000](https://user-images.githubusercontent.com/33517449/90154118-09ed6680-dd8a-11ea-91f6-64c792f46f81.jpg)
![Nasilje_001](https://user-images.githubusercontent.com/33517449/90154148-11147480-dd8a-11ea-8565-dd8faec9af5f.jpg)

**Expected behavior and actual behavior:**
![Nasilje_002](https://user-images.githubusercontent.com/33517449/90154300-3dc88c00-dd8a-11ea-9d13-ea9afcb8b20e.jpg)

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
This is already a live issue.
