### ISSUE TITLE
Was able to grab a second rank 1 influence item with my IB from CT.

### ISSUE THREAD

**Issue by ChicagoJoe999** [WarEmu/WarBugs#17528]
Had chosen and had used Earthshatter when able to get first influence item. 

Got second level of influence and chose shield Liberty.

Was accessing the rally master again at 40,000 influence and saw that I was able to choose from first influence stage again as I chose Bloodlust as a test today.

I now have 2 tier 1 influence awards and 1 tier 2 awards.  I can share screenshots but I don't think they will help.

My IB's name is Earthshatter if that makes any difference, same as the first influence item he uses.

I don't want or need Bloodlust or Liberty but really hope you don't remove Earthshatter as that is my current BIS and namesake.

**Comment by Rydiak** [comment]
This isn't a bug.  There are two different rally masters, for a total of 4 city weapons (2 basic, 2 advanced).
