### ISSUE TITLE
IB Knockdown

### ISSUE THREAD

**Issue by MagiclyDelisious** [WarEmu/WarBugs#17525]
https://www.metacafe.com/watch/12108078/ib-knockdown-bug/
**Expected behavior and actual behavior:**after getting knocked down your character stays in that position until you do an action or move then you are knocked down position again

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by MagiclyDelisious** [comment]
https://vimeo.com/447580523

**Comment by MagiclyDelisious** [comment]
this one works

**Comment by Kaelang** [comment]
This can sometimes happen, it's nothing malicious. It's been here since the start of time.
