### ISSUE TITLE
[Quest] Heroes' End, Destruction @Ellyrion

### ISSUE THREAD

**Issue by magter3001** [WarEmu/WarBugs#1752]
Collected the head of Ainalar Proudfury (got credit for it), but cannot put his head on a spike. His head doesn't show up in the inventory

**Comment by magter3001** [comment]
EDIT: There are two spikes in the area, Pike (which is the obvious big one) and the display pike (which is really small :/) that does give credit, even if you don't have the head.

**Comment by Meralors** [comment]
You are right the big spike is of no use and quest credit is awarded when you click on the small one. I removed the big spike so no more confusion :)
