### ISSUE TITLE
DOT stacking/tick rate issues

### ISSUE THREAD

**Issue by lokiusus** [WarEmu/WarBugs#17529]
**Expected behavior and actual behavior:**
Prior to the patch DOTs had a tickrate ranging from 1s-2s, mostly 2s, but ultimately varied depending on skill. But since the patch it's possible to "stack" DOTs for quicker/more ticks. 

It seems like this may not be true for all DOTs and I don't know what the distinguishing issue might be. I haven't had a chance to test more than slayer + choppa, but I've heard from others that Rend (credit Aabcd) and Dissolving Mist (credit Trisma) were performing similarly with stacked 1s ticks. I would imagine this behavior is mirrored between similar destro/order DOT skills, I just haven't had the time or access to toons to widely test it yet. 

**Steps to reproduce the problem:**

Know issue this shows up on a slayer. Grab a slayer, spec for CIT and ID. Spam CIT on a friendly target dummy/regen tank and check to see how many dot procs you can stack in one second. ID is harder to stack but possible with a 6s/8s timer, 

**Example screenies provided below.** 

In this screenie you can see CIT hit 3 times in the same 46' timestamp, once at 47', twice at 48', once at 49; twice at 50', and again at 51'. 

![](https://cdn.discordapp.com/attachments/613362389114552332/743649170350538863/CIT.PNG)

In this screenie you can see ID goes off twice at 23', once at 24', once at 25, once at 27, and once at 28. He couldn't have been spamming/reproccing ID that much alone by hitting me because ID itself has a 5s internal cooldown. And ID was definitely a 2s proc prior to this patch.

![](https://cdn.discordapp.com/attachments/613362389114552332/743651869267853362/ID4.PNG)

**Comment by Kaelang** [comment]
Fixed in hotfix.
