### ISSUE TITLE
Proc damage is affected by class mechanics

### ISSUE THREAD

**Issue by iantheace** [WarEmu/WarBugs#17535]
Proc damage since the patch appears to be affected by class mechanics. What i mean by this is, on a slayer if you have for example 75% dmg bonus, your proc would benefit from it, which is clearly incorrect.

Expected behaviour: Proc does its base damage.
Actual Behaviour: Proc does modified damage.

**Comment by Niall86** [comment]
@iantheace not that I was against nerfing slayers, however, why slayer's damage bonus should not apply in case it's a slayer's proc (not a proc granted from your party member or weapon proc)?

**Comment by iantheace** [comment]
It applies to all procs, not just your own, and it shouldn't apply to any proc, for any class, it doesn't seem to work on procs for magus and engineer with their pet dmg buff.

**Comment by Kaelang** [comment]
Fixed in hotfix.
