### ISSUE TITLE
Tracker set for WL visually bugged

### ISSUE THREAD

**Issue by valkeera** [WarEmu/WarBugs#17536]
Boots and gloves for the Tracker armor set for White Lion have incorrect icons, and the models are missing when you put them on.

![Cirthanir_003](https://user-images.githubusercontent.com/58527250/90313484-3e3d6000-df0d-11ea-96c4-48703adbfb0b.jpg)

![Cirthanir_004](https://user-images.githubusercontent.com/58527250/90313489-43021400-df0d-11ea-901b-2bb1f958026b.jpg)

**Comment by Kaelang** [comment]
This has been addressed in todays patch.
