### ISSUE TITLE
EXTREME DOT HITTING FOR 1K / TICK 

### ISSUE THREAD

**Issue by NimeriaEverstar** [WarEmu/WarBugs#17530]
**Expected behavior and actual behavior:**
My AM is specc'd as a healer and I hit this shaman for 1K / 1Second with "Transfer Force" , and Law of Conductivity 

**Steps to reproduce the problem:**
I was in Troll Country and my dot hit this gobo for a crap ton of dmg on one second. 

**Testing Screenshots/Videos/Evidences (always needed):**

![Screenshot from 2020-08-13 23-22-19](https://user-images.githubusercontent.com/69556440/90210602-64071f80-ddbc-11ea-940a-852e3127d444.png)

**Comment by colintgallagher** [comment]
Were you or the shaman close to the Order warcamp? Looks like the warcamp buff kicked in.

**Comment by NimeriaEverstar** [comment]
Yeah. I was near the WC, but I was like wow!! I didn't think I could hit him that hard with only ~200 intel.

**Comment by NimeriaEverstar** [comment]
Yes! But that seems so high damage for 1 tick.

**Comment by Kaelang** [comment]
You got the WC buff.
