### ISSUE TITLE
Slayer Inevitable Doom Procs all effects

### ISSUE THREAD

**Issue by iantheace** [WarEmu/WarBugs#17534]
Slayer inevitable doom is triggering way too much additional proc DPS.

Exepected behaviour:
Inevitable doom would not trigger active player procs.
Actual behaviour:
It triggers EVERYTHING.

**Comment by Zumos** [comment]
ID, much like Gloom of Night from the Sorc does not function as a DoT and it shouldn't (and therefore it can proc stuff). You could see it like Fireball barage, only it isn't a channel, but you only have to apply it with 1 gcd (or a cast time in the case of GoN).

**Comment by iantheace** [comment]
IF this is intended, it needs to be looked at as a balance issue, as whole zergs die purely to ID procs once you stack slayers. It should be looked at for gloom of night as well. I know you are saying it is not a DOT, but it is a DOT!

**Comment by Haojun-Phalanx** [comment]
ID can trigger procs, it was like this since 2008.

**Comment by dalen** [comment]
It works similarly to Dissipating Energies or Rune of Battle

**Comment by Niall86** [comment]
@Zumos does Gloom of Night also procs everything?

**Comment by Zumos** [comment]
It did last time I tested it.

**Comment by iantheace** [comment]
The problem is ID can be on Zero cooldown with swordmaster and stacked on every closest enemy. No other similar abilities can as far as i know.

**Comment by Zumos** [comment]
Which has nothing to do with bugs, so it doesn't belong here.

**Comment by Kaelang** [comment]
working as intended by the sounds of things, balance suggestions to forums.
