### ISSUE TITLE
Crafting ingredients above white rarity

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#1753]
I have noticed that quite a lot of Uncommon and higher level ingredients, for both talisman making and cultivating, do not have a "required skill" rating, and simply do not work.

**Comment by ropuch** [comment]
If you use CraftValueTip addon, you can invoke /craftvaluetip digest while hoovering over the fragment in question - this will provide  uniqueID & same info of the item which I believe will provide good start for devs [;

**Comment by nalgol** [comment]
most carting items in the lootlists are broken and are not suppose to work only stuff you get via gathering professions work

**Comment by Luth-RoR** [comment]
As per nalgol not every item is supposed to be salvaged.
Cultivation items that can't be actually used atm are also working as intended. They shouldn't drop though and many of them have been fixed/removed from player inventories in the past.
