### ISSUE TITLE
Choppa able to hit attacking ram from behind door

### ISSUE THREAD

**Issue by Tradwarden** [WarEmu/WarBugs#17532]
**Expected behavior and actual behavior:**
**Expected>** You must exit outside a door to be able to attack a ram, you must be on the same side the ram is on.
**Actual behavior>**A choppa was able to drop about 25% of an order ram's HP by attacking it from behind the door

**Steps to reproduce the problem:** Unknown, he seemed to be doing single target attacks, not AoE.

**Testing Screenshots/Videos/Evidences (always needed):**

![Annotation 2020-08-14 015451](https://user-images.githubusercontent.com/69600315/90222182-2f519300-ddd1-11ea-8b94-e8b18d6dbdd0.png)
![Annotation 2020-08-14 015446](https://user-images.githubusercontent.com/69600315/90222194-37113780-ddd1-11ea-8e85-9c80888774d9.png)

**Comment by Kaelang** [comment]
Do you know what Choppa skill this was?

**Comment by TenhiYT** [comment]
Will need to test it but iirc all Auto Attacks go through Doors atm. Dont think Abilities work through it tho.

**Comment by XmatXergon** [comment]
hope this will help aswell:

https://youtu.be/FWljHPkSkDQ

**Comment by Tradwarden** [comment]
> Will need to test it but iirc all Auto Attacks go through Doors atm. Dont think Abilities work through it tho.

This seems about right. It was all white (autoattack) damage, didn't actually see him use any abilities.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/10242
