### ISSUE TITLE
PLAGUEWOOD THICKET quest.

### ISSUE THREAD

**Issue by esariobug** [WarEmu/WarBugs#17547]
Hi,
the PLAQUEWOOD THICKET's quest (chap 8 - chaos) has maybe a little bug.
First you must kill 75 trolls, second un must kill a Hero "Biletongue", third un may kill 5 champions and for the finish u must kill the hero "biletongue" again.
2 times a hero in difficult quest is really difficult :)
Thanks for reading and thanks for gorgeous job, all.

**Comment by Kaelang** [comment]
Not all PQs are soloable.
