### ISSUE TITLE
Forts are letting in too many attackers 

### ISSUE THREAD

**Issue by Carcharadon** [WarEmu/WarBugs#17546]
100 + attackers at some points in fights the numbers seem to flux but average about 100  . way more then the allowed %

**Expected behavior and actual behavior:**

capping attackers vs def at correct %   - actually letting in x2 to x3 the allowed number 

**Steps to reproduce the problem:**

fort
2 separate pop counts  attached  
![WAR-64 2020-08-16 02-20-35](https://user-images.githubusercontent.com/55959616/90329137-aa4cb200-df67-11ea-8ff3-103be8885f2c.png)
![WAR-64 2020-08-16 02-20-16](https://user-images.githubusercontent.com/55959616/90329142-b20c5680-df67-11ea-8f36-4d852dca635b.png)

**Comment by Carcharadon** [comment]
people didn't leave this was pop the whole time.

**Comment by Kaelang** [comment]
Please can you support this theory with additional screenshots from other forts in the next few weeks? I’ll keep an eye too. Thanks.

**Comment by colintgallagher** [comment]
I was under the impression fort pops are capped by attackers, not defenders.

**Comment by Carcharadon** [comment]
> I was under the impression fort pops are capped by attackers, not defenders.

that would defeat the purpose of the cap to keep it from being just a zerg fest.

**Comment by colintgallagher** [comment]
> > I was under the impression fort pops are capped by attackers, not defenders.
> 
> that would defeat the purpose of the cap to keep it from being just a zerg fest.

Or to keep 200 people pushing a fort, 1 defender showing up and keeping out 195 attackers who can't get in. And now the 5 who did have to try to kill a fort lord.
