### ISSUE TITLE
T3 BFP keep minion bug

### ISSUE THREAD

**Issue by Grey-Rogue** [WarEmu/WarBugs#17544]
**Expected behavior and actual behavior:**

Dwarf keep minion spawning in Gnol Baraz while Greenskin owns keep. Dwarf cant be attacked with single target but can be AOEd and pets can agro. 

**Steps to reproduce the problem:**

Not sure if this is a one off issue or reocurring. Just saw it in passing and took a screenie

**Testing Screenshots/Videos/Evidences (always needed):**

![keep](https://user-images.githubusercontent.com/69607536/90327804-078f3600-df5d-11ea-8c0e-87fc80282411.PNG)

**Comment by Lheana** [comment]
There is no error in DB, so I guess it could have happened when there was some lag.
Thus I close the ticket, but comment here if it happens again.
