### ISSUE TITLE
[Warrior Priest] Auras turn off when swapping!?

### ISSUE THREAD

**Issue by Sciberr** [WarEmu/WarBugs#17543]
**An introduction:**

When switching auras it will automatically turn off.

**Details:**

For example if I start off with heal aura the next aura I swap to will automatically turn off after a moment making me have to wait 10 seconds to re-enable it.

**Evidence:**

https://youtu.be/o3icbW09fZ8

**Additional Information:**

I don't remember having to keep turning my aura on so much... must've been something in one of the recent patches. 

**How to reproduce the bug:**

Log onto your WP and start swapping between auras to find that your auras will automatically turn off for no reason.

**Comment by Rydiak** [comment]
Can confirm.  Changing from one aura to another, or merely "refreshing" an aura (such as when re-activating Prayer of Devotion when applying Leading the Prayer tactic), will turn the aura off.

**Comment by Kaelang** [comment]
This has been address in todays patch.
