### ISSUE TITLE
Small typo for Living Armor Tome entry

### ISSUE THREAD

**Issue by Grey-Rogue** [WarEmu/WarBugs#17545]
**Expected behavior and actual behavior:**

"Only in the most astonishingly powerful locations could such **_an_** object last longer"

remove the D from AND

**Steps to reproduce the problem:**

Unlock and read Tome entry for Living Armor

**Testing Screenshots/Videos/Evidences (always needed):**

![typo](https://user-images.githubusercontent.com/69607536/90327918-c64b5600-df5d-11ea-9ca0-8d8f996fd57a.PNG)

**Comment by Kaelang** [comment]
This has been address in todays patch.
