### ISSUE TITLE
[BW] Invader 5 set +10 range not working correctly for Morale abilities

### ISSUE THREAD

**Issue by Uncausedryan** [WarEmu/WarBugs#17549]
Expected: In-game tooltip shows the adjusted cast range for Morale abilities from 100 feet to 110 feet. White asterisk shows ability to cast Morale. Morale should initiate.

Actual: In-game tooltip and white asterisk showing cast range and ability show Morale can be used. But the ability is still only castable from 100 or less range. Occassionally when casting a morale ability from beyond 100 feet, the ability will go on full cooldown, do no damage "give the out of range error" and not spend Morale points. I was unable to capture said cooldown bug on video

**Steps to reproduce the problem:**
Equip BW invader 5 set, attempt to cast a targeted 100 base range morale ability, boosted to 110 from the 5 set bonus on target within said 110 foot range. 

**Testing Screenshots/Videos/Evidences (always needed):**
https://youtu.be/ADBHkrwfAs8
unlisted short video displaying issue

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17173
