### ISSUE TITLE
[SM] Sentry' Masterblade of Devotion - 1 Talisman slot only

### ISSUE THREAD

**Issue by CrimsonFenris** [WarEmu/WarBugs#17542]
The Swordmaster blade from sc (rank 20) Sentry' Masterblade of Devotion got only one talisman slot, despite being 2-handed.

The other version of this 2H blade got the correct 2 slots (see screenshot).

![MasterbladesBug](https://user-images.githubusercontent.com/40425011/90324111-d0278600-df6a-11ea-84ed-d3d5b8f749e1.jpg)

**Comment by Kaelang** [comment]
This has been addressed in todays patch.
