### ISSUE TITLE
WL stance drops after pet summon.

### ISSUE THREAD

**Issue by RasmusRB** [WarEmu/WarBugs#17555]
**Expected behavior and actual behavior:**

The stances: Trained to Hunt and Trained to Kill drops after pet summon, which it obviously should not. For some reason, Trained to Threaten does not drop. 
Video linked further down.

**Steps to reproduce the problem:**

Toggle stance, summon pet -> stance will drop shortly after.

**Testing Screenshots/Videos/Evidences (always needed):**

https://youtu.be/yeVquWGLChM

**Comment by Kaelang** [comment]
This has been address in todays patch.
