### ISSUE TITLE
Senario Que button not working at all

### ISSUE THREAD

**Issue by Coniption11** [WarEmu/WarBugs#17559]
**Expected behavior and actual behavior:**
It has been about a month where the scenario que button does not work at all. The window will not pop up to que. I have tried /reload, .unlock and there is no deserter debuff on any character on the account. I have also tried repairing the client and redownloading the game. I have even tried a new account to see if that worked and it did not.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Please use Technical Support, not the bugtracker.
