### ISSUE TITLE
Chaotic attunement intermittently not working (tactic doesnt work)

### ISSUE THREAD

**Issue by iantheace** [WarEmu/WarBugs#17557]
**Expected behavior and actual behavior:**

Magus 'chaotic attunement' tactic intermittently fails to work. It stops insta summoning the pet, and taking normal cast times.

Expected: should always insta summon your pet

**Steps to reproduce the problem:**

Not sure, this can actually fail mid combat, and not even fix itself when you relog..... then randomly start working again in combar. Making playing magus really frustrating at the moment. In video i even change the tactic off and on and it does not fix.

I run tactics:

Endless knowledge 
Chaotic attunement 
Daemonic reach
Endless Pandemonium

**Testing Screenshots/Videos/Evidences (always needed):**

http://rgupdates.co.uk/ChaoticAttunment.mp4

Dont worry about gryphon, i've given up on one of these :)

**Comment by iantheace** [comment]
Confirmed relogging DOES temporarily fix this bug whenever it occurs. Obviously this isnt really an option during cities/scenarious/Orvr fights etc

**Comment by Kheriel** [comment]
i have made a thread about similar problem called Tactics dropping, guess it must be same kind of bug :(

**Comment by iantheace** [comment]
Yeah it is the same bug, you are correct. All tactics just keep intermittently dropping, out of interested are you below level 40? I think it may be bolster related.

**Comment by Kheriel** [comment]
it happened in SC before lvl 40 indeed !!

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17538
