### ISSUE TITLE
Tomb of the Subjugator not generating Righteous Fury

### ISSUE THREAD

**Issue by Leonellion** [WarEmu/WarBugs#17556]
A regen effect of 8 per second to Rightous Fury is missing from the item even though it is supposed to. In both the item description and the nature of Purple grade Books for the Warrior Priest.

![Capture](https://user-images.githubusercontent.com/69814077/90428096-623ea400-e0bb-11ea-96c9-3215f6436944.PNG)

I got the item from a Purple Loot bag from a Keep Siege.

I have Video footage, but a 10MB limit on Gifs prevents me from uploading it.

**Comment by Leonellion** [comment]
The item still Spikes for 360 damage however.

**Comment by Kaelang** [comment]
Re-equip  the item.

**Comment by Leonellion** [comment]
I equip it and un-equip it multiple times on the video I made, but it still doesn't work. Unless you have now fixed it ? ( Will update in 7 hours )
