### ISSUE TITLE
Duplicate name

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#17550]
Since yesterday at loginscreen my main character (Nicebeaver) is getting a message that it has a duplicate name and I should rename. I've been using that name for quite some time now so it's odd that it has a duplicate. Sometimes relogging changing to an alt and relogging again fixes the problem. 

![Clipboard01](https://user-images.githubusercontent.com/11788060/90337064-4914f500-dfe0-11ea-8e90-4f0b768670f3.jpg)

**Comment by Kaelang** [comment]
You've been given a rename from staff by the looks of it.
