### ISSUE TITLE
[WE] shadow prowler detection ....some thing wrong with it

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#1756]
If you walk in front of enemy 100% you will be detected.

**Comment by Nfkillz** [comment]
chance of detection should be less then 100%. on live it depens from your initiative and enemy`s initiative

**Comment by ozarmidrashim** [comment]
Original formula is unknown. RoR formula uses opposed Initiative check with modifiers for distance from enemy. If you walk in front of someone's face you /should/ be detected.

I don't intend to change it.

**Comment by ozarmidrashim** [comment]
private void CheckStealth()
        {
            ushort myInitiative = (ushort)StsInterface.GetTotalStat((ushort)Stats.STATS_INITIATIVE);

            foreach (Player Plr in PlayersInRange)
            {
                if (_stealthLevel == 2)
                {
                    if (_spotters.Contains(Plr))
                        continue;
                    if (Plr.GmLevel > 0)
                    {
                        _spotters.Add(Plr);
                        SendMeTo(Plr);
                    }
                    continue;
                }

                if (Plr.Realm == Realm)
                    continue;

                int dist = GetDistanceBetweenObjects(Plr);
                float flankMod = Plr.IsObjectInFront(this, 90) ? 1f : 0.35f;

                if (_spotters.Contains(Plr))
                {
                    if (dist >= STEALTH_DETECT_RANGE_MAX * flankMod)
                    {
                        //Plr.Say("Lost track of " + _Info.Name, SystemData.ChatLogFilters.CHATLOGFILTERS_SAY);
                        _spotters.Remove(Plr);
                        SendRemove(Plr);
                    }
                }

                else if (dist < STEALTH_DETECT_RANGE_MAX * flankMod)
                {
                    float detectionBonusFactor = (float)Plr.StsInterface.GetTotalStat((ushort)Stats.STATS_INITIATIVE) / myInitiative;

                    int checkDifficulty = (int)((5 + (STEALTH_DETECT_RANGE_MAX - dist)) * detectionBonusFactor * flankMod);
                    int checkRoll = StaticRandom.Instance.Next(100);
                    //Plr.Say("Detection: dist:"+dist+", check difficulty " + checkDifficulty + "%, rolled " + checkRoll + ".", SystemData.ChatLogFilters.CHATLOGFILTERS_SAY);
                    if (checkRoll < checkDifficulty)
                    {
                        //Plr.Say("Detected " + _Info.Name +".", SystemData.ChatLogFilters.CHATLOGFILTERS_SAY);
                        _spotters.Add(Plr);
                        SendMeTo(Plr);
                    }
                }
            }
        }

**Comment by Nfkillz** [comment]
ok ty
