### ISSUE TITLE
Character class changed and reduced to level 1

### ISSUE THREAD

**Issue by Tinkaballa** [WarEmu/WarBugs#17567]
My level 12cr/15rr Witch Hunter is now a level 1 Warrior Priest at the starting zone.

I tried restarting the game, relaunching the launcher, even logged into the character but no change.

All gear, gold and items gone.

**Comment by Rydiak** [comment]
Are you sure you have logged into the right account, and have you checked the Destruction character page?

**Comment by Tinkaballa** [comment]
I only have 1 account, no destro, the character looks exactly the same, name, hair etc but level and class have changed.

**Comment by Tinkaballa** [comment]
Decided to delete the level 1 and start over since it'll only take a few hours to get back to level 12.
