### ISSUE TITLE
Login into game through the launcher

### ISSUE THREAD

**Issue by Bodezalpha** [WarEmu/WarBugs#17568]
So I changed my password to the Return of Reckoning website, and logged into the homepage trying to find an answer to my problem. When I go to login to Warhammer return of reckoning the launcher keeps telling me invalid or incorrect username or password. Cant seem to reset it or change the password. I have looked on the forums and tried resetting the password but that only resets the homepage login. Please help I want to get into my game and I am totally at a loss on what to do now.

**Comment by Kaelang** [comment]
This isn't an ingame bug. Please use the forums.
