### ISSUE TITLE
Temporary buff in city siege decreases crit chance instead of increasing it

### ISSUE THREAD

**Issue by enshoe** [WarEmu/WarBugs#17564]
**Expected behavior and actual behavior:**
Buff should increase crit chance, not reduce it.

**Steps to reproduce the problem:**
Set a box ablaze during city siege and gain the temporary buff.

**Testing Screenshots/Videos/Evidences (always needed):**
![Buff_ON](https://user-images.githubusercontent.com/27415969/90606934-d0d94a00-e200-11ea-819d-bcd8a6e661d3.JPG)
![Buff_OFF](https://user-images.githubusercontent.com/27415969/90606938-d20a7700-e200-11ea-88c9-ece0f2aa69dd.JPG)

**Comment by Rydiak** [comment]
Can you verify this with .getstats? The character window is incredibly buggy.

**Comment by Kaelang** [comment]
No additional information provided.
