### ISSUE TITLE
When someone declines the Ranked scenario pop, the requeue does not work

### ISSUE THREAD

**Issue by pkfsa** [WarEmu/WarBugs#17560]
I just had a scenario pop and someone declined during the ready up check. I got the message saying I'm returned to the front of the queue but I notice that a bunch of people are missing on the SoloQ addon. I cancelled the queue and the number of DPS in the queue did not decrease and when I requeued the number went up.

**Comment by Kaelang** [comment]
Likely the MMR system picked another set of players to form a game, some of which were out of the requeue, and some are from within.
