### ISSUE TITLE
RvR tier 1

### ISSUE THREAD

**Issue by vaselin88** [WarEmu/WarBugs#17575]
Hello Rvr in Tier 1 is totally broken:
When destruction turn in supplies its counts for destruction
When order turn in supplies its counts for destruction
So in this case destruvtion always have 100% and order always have 0 %
And order lose no matter what they do 
Please do something
With best regards Nataska

**Comment by obsidimal** [comment]
Seconding this - seems to effect all 3 regions.

Also noticed that the 3 pocket items in T1 orvr no longer spawn the item (though the tome unlock happens).  Tested this on both sides, and all three definitely worked yesterday.  Might also be tied to the zones being busted?

**Comment by Kaelang** [comment]
Fixed.
