### ISSUE TITLE
2 rams spawning when keep hits 2 stars

### ISSUE THREAD

**Issue by GimmiMoar** [WarEmu/WarBugs#17573]
Hi all, There seems to be a bug with 2 rams spawning once a keep reaches 2 stars! :(

**Comment by Opeteh** [comment]
Dude, literary 2 posts below...
![image](https://user-images.githubusercontent.com/69940910/90700337-e2186a00-e285-11ea-8a05-9d8ec6c77d53.png)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17570
