### ISSUE TITLE
Surging Pain

### ISSUE THREAD

**Issue by Caduceus42** [WarEmu/WarBugs#17571]
Hello,

The spell 'Surging Pain' says in its tooltip that it has a chance to cause Backlash. This is in fact not the case, as shown by the screenshot that I added.

With any other spell one may consider this a positive thing, however with Surging Pain it is desirable to receive Backlash so it can synergize with the tactic 'Piercing Shadows' (which causes AoE damage upon Backlash). 

![Surging Pain Pic](https://user-images.githubusercontent.com/69918329/90676597-8eddf180-e25c-11ea-9203-34f0756164e1.png)

Regards,

Caduceus

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/11494
