### ISSUE TITLE
Character Missing.

### ISSUE THREAD

**Issue by Tinkaballa** [WarEmu/WarBugs#17576]
Ok I opened a ticket yesterday as my level 12cr/14rr Witch hunter was reduced to level 1 and class changed to Warrior Priest.

I closed the ticked, deleted the level 1 and started again getting a new witch hunter to level 12cr/12rr

Today I log in and the character is gone from my character screen. Not even a replacement level 1 WP as before.

My other characters are there 33 Eng, 25 WL etc but NO 12 WH

I have no destro only order and only 1 account.

Armory shows my character as a level 1 WL

https://www.returnofreckoning.com/armory/character/1662181

**Comment by Kaelang** [comment]
This is for ingame issues, please use the forums.

**Comment by Tinkaballa** [comment]
The posts I read said to open a ticket asking for a character restoration.

How do i get my Witch Hunter back.

Character Name: Qwiksilver

**Comment by Kaelang** [comment]
Open a ticket ingame.
