### ISSUE TITLE
WL: no damage from throat bite

### ISSUE THREAD

**Issue by tlitschye** [WarEmu/WarBugs#17574]
According to tooltip "Throat bite" should do xyz damage.
No damage is inflicted but silence debuff is applied.

The other way around the video also shows using the same mechanic with Brutal pounce that shows the damage done.

Steps to reproduce, send lion to target dummy with silence command active.
[WL_Throatbite.zip](https://github.com/WarEmu/WarBugs/files/5102158/WL_Throatbite.zip)

**Comment by enshoe** [comment]
I think this could be tied in to Squig Herder's ability "Drop That!!"
The skill is intended to disarm the target and deal damage, no damage is dealt.

**Comment by Rydiak** [comment]
Do you have screenshots or a video you can link to this report? Not sure many people want to be opening .zip files.

**Comment by tlitschye** [comment]
its a mp4

**Comment by tlitschye** [comment]
PUSH

**Comment by grunbag** [comment]
Fixed with next patch
