### ISSUE TITLE
[ORDER][QUEST] The Doctor's Orders

### ISSUE THREAD

**Issue by akahige93** [WarEmu/WarBugs#1757]
"Search for Doctor Heino's escaped patient in Hangman's Wood., Return to Doctor Heino near Breuer's Regiment when you're done."

<a href='http://postimg.org/image/6x16w02gf/' target='_blank'><img src='http://s19.postimg.org/6x16w02gf/Akahige_000.jpg' border='0' alt="Akahige 000" /></a>

I can not complete the quest.

**Comment by Meralors** [comment]
FIxed on dev, wait for next patch for live update ;)
