### ISSUE TITLE
Divine Lord can be healed

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#17572]
Divine strike is healing the lords in city stage 2, I assume the DoK equivilent is as well but I havnt tested, and I dont have a clue what that ground target thing is...
![heal](https://user-images.githubusercontent.com/16922842/90691890-08c9a700-e26c-11ea-82f7-4ef60961c495.png)

**Comment by lilimx** [comment]
This issue is obsolete now, due to the latest changes.
