### ISSUE TITLE
Action house

### ISSUE THREAD

**Issue by Dalkii** [WarEmu/WarBugs#1758]
Dropped an item on sell, dont have money or any message from this, but not on my items on sold and not in the AH (greensheep order).

**Comment by Evildoor** [comment]
#854. Problem is known, but nothing can be done about it for now.

**Comment by Dalkii** [comment]
Just to know, did the item diseapear or did it come back later?

**Comment by Evildoor** [comment]
Sorry, no idea. Maybe someone with access to DB can tell you more, but i doubt it.

**Comment by Dalkii** [comment]
Thx mate for the answer

**Comment by Dalkii** [comment]
Just to telling you guys, i got the message and the gold after patching.
