### ISSUE TITLE
PQ on Destro side are counting for Order characters

### ISSUE THREAD

**Issue by valkeera** [WarEmu/WarBugs#17580]
While traveling through Destro pve zone in Ostland, I crossed the Silkens PQ, got bitten by a spider, and after a while received 1st place and blue bag for "participating" in it. Chaos storyline got unlocked in my ToK afterwards.

![Caiquenil_000](https://user-images.githubusercontent.com/58527250/90822625-0aab6d00-e335-11ea-8b93-0983a428ebef.jpg)

![Caiquenil_002](https://user-images.githubusercontent.com/58527250/90822687-1b5be300-e335-11ea-91d9-5ea3b8a6c874.jpg)

**Comment by Kaelang** [comment]
Please update your already live report.
