### ISSUE TITLE
Split arrow tactic falling off

### ISSUE THREAD

**Issue by Carcharadon** [WarEmu/WarBugs#17586]
the Split arrow tactic falls off and  no matter what you do you can not get it to reapply it self with out a full log out and log back in , if its zone change or death  or even a stance switch that makes it not work  do not  know for sure but its greatly affecting damage and pressure out put of the SW 
**Expected behavior and actual behavior:**

split arrow stays on as long is the tactic is on 

**Steps to reproduce the problem:**
play a SW for a little wile die a few times swap zones 

i attached 3 images with me high lighting the tactic and the skills , you see SFA says 100f not 65 and then a caste BHA that you can see with buff head only is on a single target in the group i shot at
![WAR-64 2020-08-21 17-43-38](https://user-images.githubusercontent.com/55959616/90941171-ffa91900-e3d6-11ea-828a-2ba25a3e0add.png)
![WAR-64 2020-08-21 17-43-50](https://user-images.githubusercontent.com/55959616/90941176-033ca000-e3d7-11ea-94e0-07c2c899a354.png)
![WAR-64 2020-08-21 17-44-03](https://user-images.githubusercontent.com/55959616/90941187-059efa00-e3d7-11ea-98d4-e5d7fd8f5e95.png)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17538
