### ISSUE TITLE
Varentane's Tower BO in Talabecland Spawning more than 4 resources

### ISSUE THREAD

**Issue by detrap** [WarEmu/WarBugs#17582]
Varentane's Tower Battlefield Objective in Talabecland Spawning more than 4 resources. Trying to capture the BO after it was held by destro during our siege on their keep nearby, all of these resources belonging to them.

![resources](https://user-images.githubusercontent.com/64330047/90831837-eaf16480-e387-11ea-94de-1fd1c823360b.png)

**Comment by timneill** [comment]
i've seen this at multiple other BOs so i think it's a general problem
