### ISSUE TITLE
Cannot see influence rewards from Crypts and Tunnels npc

### ISSUE THREAD

**Issue by Saddarak** [WarEmu/WarBugs#17583]
![Myrina_002](https://user-images.githubusercontent.com/58730536/90859798-8b985200-e391-11ea-8c39-a11dd3f61a4f.jpg)

tried reloging, updating game and patcher, no change. It happens in all 3 npc

**Comment by Vancerus** [comment]
That is the wrong NPC. Go downstairs and left for the one where you can see the rewards.

**Comment by Lheana** [comment]
As this is not issue but just a problem with how RoR got installed/updated, I am closing this ticket.
Please use our forum if you need support.
