### ISSUE TITLE
GameData.Auction.DEPOSIT_MULTIPLIER not returning the proper value based on city rating

### ISSUE THREAD

**Issue by aaearon** [WarEmu/WarBugs#17590]
**Expected behavior and actual behavior:**

GameData.Auction.DEPOSIT_MULTIPLIER should return the correct auction deposit fee value based on city rating however seems to only ever return .20, which would reflect how it was on live and previously on RoR. The values based on city rating are explained in the patch notes from 10/06/2020: https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=39021

**Steps to reproduce the problem:**

1. Look at the city rating.
1. Type ```/script EA_ChatWindow.Print(towstring(GameData.Auction.DEPOSIT_MULTIPLIER))``` in the client.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/812640/90950644-dda1ac00-e453-11ea-9b35-2f2cc941e50f.png)

(Sorry for bad screenshot but this is fairly easy to reproduce, I think)

**Comment by MaxHayman** [comment]
What are you using this for? We no longer use that constant.

This is how the price is calculated now.

`function AuctionWindowSellControls.CalculateDeposit()

	-- Get the city for the current pairing the player is in
	-- 1* 10%, 2* 8%, 3* 6%, 4* 4%, 5* 2%
	local pairingCityRating = GetCityRatingForCityId(RoR_CitySiege.GetCityFromPairing())
    local depositPrice = math.floor( (AuctionWindowSellControls.buyOutPrice / 100) * (12 - 2 * pairingCityRating) )
    
    if depositPrice < 1
    then
		depositPrice = 1
    end
	
	d("New Deposit Price: "..depositPrice)
	
	MoneyFrame.FormatMoney( SELL_CONTROLS_NAME.."DepositPrice", depositPrice, MoneyFrame.HIDE_EMPTY_WINDOWS )
end`

**Comment by aaearon** [comment]
It is being used by the AH addon Shinies to estimate the deposit when posting an item to the AH.

**Comment by MaxHayman** [comment]
Well the addon developer would need to update it. ``GameData.Auction.DEPOSIT_MULTIPLIER`` was never lined up with the fee we took in RoR before the change.

**Comment by aaearon** [comment]
No problem, thanks for giving the function on how the price is calculated. The addon can easily be updated with this then.
