### ISSUE TITLE
City queue breaks, if scenario list updates during active city 

### ISSUE THREAD

**Issue by rakels** [WarEmu/WarBugs#17608]
Today many encountered the problem. When the scenario lists updates while a city queue is active it looks like it throws everyone out of the queue and makes it impossible to requeue with the following error message (same for solo/group/wb queue):

![image](https://user-images.githubusercontent.com/9309339/91021192-b4b81d00-e5f3-11ea-89c6-9e56fa2cfa3d.png)

**Comment by Carcharadon** [comment]
i too was dropped and could not requeue
