### ISSUE TITLE
Split Arrow Tactic no longer seems to work.

### ISSUE THREAD

**Issue by Leonellion** [WarEmu/WarBugs#17604]
I logged into my Shadow Warrior ( level 19 ) with split arrow tactic which now says level 21 ... i am now level 22 but the tactic still does not work.

**No reduced range but no longer spreads to multiple targets**

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/69814077/90984947-644bab80-e570-11ea-9654-294327185122.png)

**Comment by Haojun-Phalanx** [comment]
dummies dont have mitigation. you need to test it with player/npc.

**Comment by Haojun-Phalanx** [comment]
![Nihaojin_000](https://user-images.githubusercontent.com/23129933/91027936-6a3f9c00-e605-11ea-993a-9598222f50ee.jpg)

it's working.

**Comment by Kheriel** [comment]
must be the same problem as me on my report about tactics dropping

**Comment by Leonellion** [comment]
I think I read your post, after relogging it worked for a bit... But broke after another hour of play.

**Comment by Kheriel** [comment]
yes, so it's the same thing
