### ISSUE TITLE
Hulking brute tactic 

### ISSUE THREAD

**Issue by Carcharadon** [WarEmu/WarBugs#17617]
the tactic is not working at all , log in and out /reload  unequip reequip nothing 

**Expected behavior and actual behavior:**
 should add toughness and Initiative  it adds nothing 

**Steps to reproduce the problem:**
log into a mara and equip it

![WAR-64 2020-08-25 18-18-08](https://user-images.githubusercontent.com/55959616/91237132-73149880-e6ff-11ea-92c9-635bd228609c.png)
![WAR-64 2020-08-25 18-17-38](https://user-images.githubusercontent.com/55959616/91237170-84f63b80-e6ff-11ea-8dee-1563f9fea5b3.png)
![WAR-64 2020-08-25 18-16-26](https://user-images.githubusercontent.com/55959616/91237191-90496700-e6ff-11ea-90e8-3e57ce65555b.png)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17538
