### ISSUE TITLE
Solo Ranked Queue does not return you to queue with priority

### ISSUE THREAD

**Issue by enshoe** [WarEmu/WarBugs#17613]
Expected:
When you get a solo ranked pop, but not everyone accepts and everyone is returned to queue. I would expect to be returned to the queue with priority for the next instance.

Actual:
When you accept a solo ranked scenario where all participants does not accept the invite, you are not returned to the queue with priority for the next match.

**Steps to reproduce the problem:**
Join solo ranked which does not reach 12/12 participants, while there is more people in queue for a match with your specific tag (DPS/TANK/HEAL).

**Comment by Sivine** [comment]
You need to keep in mind that other things goes into the char selection for ranked like MMR or archetype (Ranged/Melee) Maybe you didn't fit into one of those variable.

**Comment by dalen** [comment]
You get returned first in the queue, but there are other factors like MMR that goes into selecting the players for next match so sometimes there will be another pop in between.

**Comment by Opeteh** [comment]
I support this one with further explenation: When not all player accepted the match, system is telling you that you were returned in front of the queue. You can then type .ranked and see who what archetypes are queued.
Although you are often told you were moved in front of the queue and your Scenario icon is active but you can see i.e. as a queued healer that there is no healer waiting for ranked on your side and you have to leave Ranked queue and sign again.
