### ISSUE TITLE
SW tactics are dropping

### ISSUE THREAD

**Issue by natmou** [WarEmu/WarBugs#17612]
**Expected behavior and actual behavior:**
I saw some post about split arrow tactic dropping on SW, but actually this all tactics that are sometimes dropping even if you remove/change them etc... Here is a screenshot of my stats without any tactic and one with Instinctive Aim and Masterful aim.
Also split arrow is dropping as expected. The only thing that helps is to relog otherwise you are trapped with wrong or no tactic.
Interesting enough, it seems to happen only on my SW and quite frequently since last patch and makes it hell to play in RvR.

**Testing Screenshots/Videos/Evidences (always needed):**
With no tactic:
![notactic](https://user-images.githubusercontent.com/28901974/91040120-9bb86780-e605-11ea-825c-385a3431cb5c.png)

With tactic activated but not working (bug):
![withtactic](https://user-images.githubusercontent.com/28901974/91040133-a246df00-e605-11ea-824b-c89b867ac669.png)
You can see the stats have not changed.

Thank you for your work !

**Comment by natmou** [comment]
Additional information, I noticed that the tactic drop when I change zone and go through a loading screen

**Comment by Kheriel** [comment]
problem already reported in Tactics dropping tread, it's doing this on all classes above lvl 40

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17538
