### ISSUE TITLE
Casting Rune of Adamant when cursor starts out of range ends up with the Rune not being placed and the ability being on cooldown.

### ISSUE THREAD

**Issue by aaearon** [WarEmu/WarBugs#17611]
**Expected behavior and actual behavior:**

When the Rune is attempted to be placed outside of the 80 ft range, a message regarding target position out of range should be shown but the ability should not go on cooldown. What happens is that the target position out of range message is shown AND the ability is put on cooldown.

**Steps to reproduce the problem:**

Attempt to cast the Rune outside of the 80 ft range when your cursor is already outside of range. You will get the message that the target position is out of range AND the ability will be on cooldown.

**Testing Screenshots/Videos/Evidences (always needed):**

Attempt to place the Rune outside of the 80 ft range with your cursor being out of range from the beginning. 

(If it is within the 80 ft range, you may experience an issue like described in #17610 )
![image](https://user-images.githubusercontent.com/812640/91039552-0e791100-e60d-11ea-879b-97bad45975a9.png)

Receive the error message regarding target position and also see the ability on cooldown

![image](https://user-images.githubusercontent.com/812640/91039715-59932400-e60d-11ea-8fd2-0de362899993.png)

When running to where the cursor was, you can see that it was not actually placed there (note as I do not have the rune of adamant buff). Looking around the area, I cannot even find where the Rune has been placed (via running around looking for visual indicator and looking at my effects) so I do not think it actually ever gets placed.

![image](https://user-images.githubusercontent.com/812640/91039806-847d7800-e60d-11ea-8137-2af2c8fb9cf8.png)

**Comment by aaearon** [comment]
I was able to reproduce this on my Zealot with Ritual of Lunacy.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17610#issuecomment-679074492

**Comment by aaearon** [comment]
@Kaelang I think this should be reopened. It is similar to #17610 but different.
