### ISSUE TITLE
Melee Squig Herder-"Git Em!" ability pet damage

### ISSUE THREAD

**Issue by GK111** [WarEmu/WarBugs#17629]
Git em ! now doing ~50-60% less damage from pet than it was before.

i checked patches notes for last few months and didn't find anything related to squig pets nerf, so i assume this a bug
![Git Em](https://user-images.githubusercontent.com/24727277/91339355-08d32500-e7df-11ea-9800-567a0c32c2f8.png)

**Comment by pkfsa** [comment]
they nerfed the stats pets inherit to nerf engi and this was an unintended side effect

**Comment by Kaelang** [comment]
Pets inherit less base stats.
