### ISSUE TITLE
Keep door damage

### ISSUE THREAD

**Issue by Dintilion** [WarEmu/WarBugs#17628]
**Expected behavior and actual behavior:**

Dont know how to check what it is. But something is dealing a large amount of damage to keep doors, without there being any canons or rams on the door. We just had the door in KV loose 15% hp without there being any siege weapons on it.

**Steps to reproduce the problem:**

People are saying its something with BW morale 2 or some BW tactic. Cannot confirm its only what ive heard. 
Do not have a BW myself to test it out

**Testing Screenshots/Videos/Evidences (always needed):**

Dont have a video or screenshot of it. I know this is a shit report, but felt like atleast reporting something and maybe someone knows something more in detail or can confirm that they saw it aswell

**Comment by Kaelang** [comment]
Please re-open the report if you can provide additional information as nobody came to provide SS / videos etc.

**Comment by b00nation** [comment]
10th February of 2021 ~11:49pm, order nuked 14% of Barak Var Keep door via aoe spells: see the following
![image](https://user-images.githubusercontent.com/25694121/107441939-71685100-6b36-11eb-9bfa-d23fd5a944c9.png)
