### ISSUE TITLE
(Not sure if it's a bug but) Triumphant set is missing from Armory in ToK.

### ISSUE THREAD

**Issue by Opeteh** [WarEmu/WarBugs#17620]
from Zealot perspective. I bought 2 pieces, wore them and it didn't show in Armory.

**Comment by dalen** [comment]
coming next patch

![image](https://user-images.githubusercontent.com/7400/100794725-44a10a80-341e-11eb-8908-6cf75a247b30.png)

**Comment by Opeteh** [comment]
No way!!! :D


wt., 1 gru 2020 o 21:44 Erik Dalén <notifications@github.com> napisał(a):

**Comment by Opeteh** [comment]
Awesome, thanks!

czw., 3 gru 2020 o 18:13 Kaelang <notifications@github.com> napisał(a):
