### ISSUE TITLE
Heavy mounts

### ISSUE THREAD

**Issue by Ungrin** [WarEmu/WarBugs#1762]
Heavy mounts in altdorf are able to be bought for 20g and sold for 60g. I found this out when I thought the 60% mounts are able to be used (they aren't.)

They can also be stacked for 20x per stack. I don't know if this is possible on destro as well.

**Comment by Meralors** [comment]
Fixed on dev, this should be pulled live asap and double checked by GM/Dev as it is important fixe

**Comment by Elthendeath** [comment]
and actually they cannot be used.

**Comment by Tesq** [comment]
last time i looked at them  they cost the correct ammount of 140 gold on destru side
