### ISSUE TITLE
Boiled blood 8.5k crit, is this allright?

### ISSUE THREAD

**Issue by Romanuzo** [WarEmu/WarBugs#17621]
Hello!
Got hitted by BB for 8369 from 28lvl BW.
![image](https://user-images.githubusercontent.com/42448411/91290233-0d2a1e80-e79c-11ea-9e77-8eeb210a56ac.png)
40 lvl black guard, full conquerror equipped.

**Comment by Kaelang** [comment]
Probably too close to the warcamp.
