### ISSUE TITLE
Auction house not displaying all your listed items

### ISSUE THREAD

**Issue by Thurgg** [WarEmu/WarBugs#17624]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/70280558/91325628-0cd45800-e789-11ea-9db5-403874183323.png)
![Aution house bug](https://user-images.githubusercontent.com/70280558/91326299-ca5f4b00-e789-11ea-8d3a-2905a7237bc6.png)

**Comment by Kaelang** [comment]
This is a known and already live issue.
