### ISSUE TITLE
Marauder Feeding on Fear adds permanent self crit chance if you crit a target

### ISSUE THREAD

**Issue by Noronn** [WarEmu/WarBugs#17627]
**Expected behavior and actual behavior:**
FoF increases your crit chance by 20% if you crit a target while also increasing your chance to be critically hit by 10%

Right now FoF permanently increases your chance to be critically hit if you critically hit a target. This effect stacks and will result in you being at 100% ctbc.
**Steps to reproduce the problem:**
Equip FoF tactic, attack target, crit target check .getstats critratereduction going into high negative values.

**Testing Screenshots/Videos/Evidences (always needed):**

![Usells_007](https://user-images.githubusercontent.com/29786661/91330592-f26e9e80-e7c9-11ea-89a6-066493393cf9.jpg)

**Comment by Haojun-Phalanx** [comment]
https://gyazo.com/fa1d9b60761e233e2da8b2e73e564250

**Comment by dalen** [comment]
Fixed in hotfix 2
