### ISSUE TITLE
Character missing from character select.

### ISSUE THREAD

**Issue by Tinkaballa** [WarEmu/WarBugs#17633]
This is the 3rd time my character has gone missing, the 1st 2 times at level 12, now this time at level 25.

I was told open a ticket ingame, which i did and was basically told nothing you can do as the only record is of a level 1 WL.

Yes my original character of the name was a WL name holder, then I rerolled a WH but now i have lost the name also as it says taken when trying  to create a character.

Now this time I used the name on a level 11 Shaman I played back in 2016 that I deleted and rolled a WL to level 25, wasnt happy with it so deleted and rolled a WH which I got to level 25 and today that character has gone from my character select screen.

I have video footage on Twitch of me playing said WH last night.

How do i get my character back as this is becoming a bad joke.

**Comment by Rydiak** [comment]
Have you tried changing the password on your account?  Seems like someone is playing a bad trick on you.

**Comment by Tinkaballa** [comment]
Why this character and not my 36cr/44rr Eng with all my gold etc.

**Comment by emailkook** [comment]
Sounds like you weren’t meant to play a WH

**Comment by Tinkaballa** [comment]
I know right, I'm afraid to start another one, mada a BW instead.

**Comment by Kaelang** [comment]
Open a ticket in game if you need Character Restoration - the bugtracker isn't the place for it.

**Comment by Tinkaballa** [comment]
I opened a ticket ingame and was told open one here.
