### ISSUE TITLE
Dark Protector remains after Scenario with a Black Guard.

### ISSUE THREAD

**Issue by b00nation** [WarEmu/WarBugs#17632]
**Expected behavior and actual behavior:**
I got "Dark Protector" Ability assigned from black guard during scenario, i left the scenario and went back to rvr. I still have the Dark Protector buff on me.

**Steps to reproduce the problem:**
Probably get into scenario and get "Dark Protector" from a black guard and leave the scenario

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/25694121/91357830-25c52380-e7f2-11ea-8ecb-7ffa11bac3c1.png)

**Comment by Kaelang** [comment]
Do you noticed reduced damage? Or is it a visual?

**Comment by b00nation** [comment]
Hello Kaelang, sorry for the late reply. No i did not notice anything. But the ability is giving rage to the black guard not reducing any dmg. So actually the black guard could get more rage somehow.

**Comment by Rockalypse** [comment]
Dark protector is out of group ability that you can put on any ally (same with oath friend), if someone would put it on you before you join SC it will stay on you until BG puts it on someone else. Abilities like this have inbuilt range and as far as I understand and does not give BG/IB anything if they are not close enough.
![image](https://user-images.githubusercontent.com/42712833/93850988-f225ce00-fcb7-11ea-8123-4ed4544d5ee2.png)
