### ISSUE TITLE
Message diseapeared

### ISSUE THREAD

**Issue by Dalkii** [WarEmu/WarBugs#1763]
I just send gold on mail to a reroll before patching, but dont got the message and dont have the money.

**Comment by magter3001** [comment]
Don't trade, buy, or send things while there is a patch coming. Kinda the golden rule.

**Comment by Dalkii** [comment]
ps: message send from Greensheep to Dalkii (yeah thx for the advice)

**Comment by Evildoor** [comment]
Mail being unreliable is a known problem. @magter3001 advice is the best thing we have, for now.

**Comment by Dalkii** [comment]
Just to know, is my gold totaly lost or is it a chance to get it back?

**Comment by Evildoor** [comment]
No idea.
