### ISSUE TITLE
Slayer blocked door during Fort fight. Was not attackable nor killable

### ISSUE THREAD

**Issue by b00nation** [WarEmu/WarBugs#17635]
**Actual behavior:**
During Fort Fight Reikland 27/08/2020 two slayer have been staying around the inner keep, blocking the entrance, no one could kill them.

**Expected behaviorr:**
They should be killable.

**Steps to reproduce the problem:**
Don't know how t hey did it, maybe the name of that player is helpful. So u could ask him.

**Testing Screenshots/Videos/Evidences (always needed):**
![Unbenannt](https://user-images.githubusercontent.com/25694121/91408092-8e88bc00-e843-11ea-9774-986fb118f05d.PNG)

**Comment by b00nation** [comment]
and 10minutes later again, white lion "Laces":
![image](https://user-images.githubusercontent.com/25694121/91408498-4322dd80-e844-11ea-8753-6e1b56882e85.png)

**Comment by Kaelang** [comment]
This is a known issue which is being investigated.
