### ISSUE TITLE
Respawn in The Maw after releasing corpse in Fort several times

### ISSUE THREAD

**Issue by Rumpel13** [WarEmu/WarBugs#17637]
Recently fighting in Chaos Fort i got "kicked" from Fort when releasing from corpse then respawning at The Maw and lost my reservation. This happened three times and at the end no reward was given because conribution was not high enough. I also got a AFK message but i wasn't. Was walking around all the time. Long before i left Scenario because of afk.

See the chat messages:
https://imgur.com/53naaWS
https://imgur.com/l6BlfBi

**Comment by b00nation** [comment]
Something similar happened to me aswell in the maw today. I was killed and got auto released, although I got a revival. I was moved to the upper spawn point and was skipped from contribution and crests.

**Comment by dalen** [comment]
fixed in hotfix

**Comment by Rumpel13** [comment]
Wie hat was quick. Thanks.
