### ISSUE TITLE
fort mass dc, mass skill table fail

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#17634]
fort at 01:02 am (27 / 08)  server time after a bit of start of step 2 both realm got mass dc, and mass ppl where unable to use skills.
 
i personally got dc tried to log back, then got stuck in download, re crashed again to end it, then got locked out of fortress as if i had left the fort willingly.

**Comment by Vicgrim** [comment]
its not only about disconect) i die and be resed in fort and i cant use my skills and cant die)
![Vikgrim_005](https://user-images.githubusercontent.com/51807854/91365966-1d2d1700-e80b-11ea-9f74-3a0307a78f6c.jpg)

**Comment by dalen** [comment]
fixed in hotfix
