### ISSUE TITLE
[IB] Deadly critical damage to Ironbreaker

### ISSUE THREAD

**Issue by AlvaroSmorras** [WarEmu/WarBugs#17638]
Ironbreaker receiving 65000 damage from random atacks since the last patch. The damage is always labeled as critical strike and comes both from NPC and players. It happened to me in Bastion Stairs, City and in rvr (our my keep), but in the discord, more people reported the same.

In this thread of the forums (https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=40628) someone managed to reproduce this event and record it in a clip.

![Screenshot from 2020-08-26 20-25-18](https://user-images.githubusercontent.com/35376500/91434789-a113ed00-e865-11ea-9b8a-7e4ba9b2e3b8.png)
![Screenshot from 2020-08-26 23-27-48](https://user-images.githubusercontent.com/35376500/91434810-a83afb00-e865-11ea-876e-c1578a7807e1.png)

**Comment by theHalta** [comment]
For the devs, this is 99% caused while wearing a specific tactic, not sure which one to be precise.

**Comment by AlvaroSmorras** [comment]
It might be, Wargrimmir said it was most likely an underflow bug, so a damage reduction tactic might be the causing it.

**Comment by dalen** [comment]
Tried to look into this, have a suspicion about it. Did you all happen to run the "Seen It All Before" tactic?

Made a change I think will fix it anyway.

**Comment by AlvaroSmorras** [comment]
Yes Dalen, I was runnin that tactic. I'll keep using it to see if the bug disappears, but i think it was already gone. Thanks =)

**Comment by dalen** [comment]
Fixed in hotfix 2
