### ISSUE TITLE
No gold bag in City

### ISSUE THREAD

**Issue by Vicgrim** [WarEmu/WarBugs#17647]
No gold bag in City after stage 1 in 4 stars Altdorf
![Vikgrim_007](https://user-images.githubusercontent.com/51807854/91518145-3364d100-e8f8-11ea-8139-285f1d453a2b.jpg)
and after stage 2
![Vikgrim_010](https://user-images.githubusercontent.com/51807854/91518794-ad498a00-e8f9-11ea-86c0-b54e36650f39.jpg)
and after stage 3
![Vikgrim_012](https://user-images.githubusercontent.com/51807854/91519386-24cbe900-e8fb-11ea-94bb-57ad528fd909.jpg)
its a 13 vs 13 city but i think this is abnormal there one reward don't get to people. )

**Comment by Rydiak** [comment]
Low population cities have reduced rewards. This change was put in place a couple patches ago.

**Comment by emailkook** [comment]
Low population cities will do that as of recent patch.

**Comment by Vicgrim** [comment]
i dont think so
because when you play 24 vs 24 your wb get 2 gold 2 purple 2 blue and 2 white.
when you play 12 vs 12 you wb have get 1 gold 1 purple 1 blue 1 green and 1 white.
may be i wrong but i think extra blue and white bags on 13 vs 13 without gold bag - scale system bug
