### ISSUE TITLE
Engineer Armor Broken in City

### ISSUE THREAD

**Issue by Portense** [WarEmu/WarBugs#17649]
I joined a group for altdorf defense on my rr74 engineer, Giivenchy. I am full oppressor with full armor talis (+137) and Winds Impervious jewels. I sit at 4220 armor with pot and ancestral inheritance. Right before city Q, everything was working. When I joined and died, I noticed my armor went to 3700. When I died again, it went to 1300, then 800. If i removed pieces of armor to below 0. It reset to 6k with 1440% damage mitigation. I tried new potion, reusing armor buff, unequiping and reequiping, and resetting tactics. Even when the window said "6k armor" .getstats only showed 1250 armor.
Nothing worked. 
(sorry pictures are not cropped)

![1 - Copy (2) - Copy](https://user-images.githubusercontent.com/53801109/91520200-b5d29e00-e8c2-11ea-98b0-c5580ec0c9b3.png)
![2 - Copy (2) - Copy](https://user-images.githubusercontent.com/53801109/91520208-b834f800-e8c2-11ea-8ca6-56e15725d1e9.png)
![3 - Copy (2) - Copy](https://user-images.githubusercontent.com/53801109/91520210-bb2fe880-e8c2-11ea-883b-fccde5f172c3.png)
![4 - Copy (2) - Copy](https://user-images.githubusercontent.com/53801109/91520217-bec36f80-e8c2-11ea-9b6c-7615d1564b10.png)
![5 - Copy (2) - Copy](https://user-images.githubusercontent.com/53801109/91520226-c125c980-e8c2-11ea-98bb-d789436e391c.png)
![6 - Copy (2) - Copy](https://user-images.githubusercontent.com/53801109/91520227-c2ef8d00-e8c2-11ea-88b4-f36a9f6f7224.png)

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by dalen** [comment]
Check if this still happens after hotfix 2, it fixed various issues with stats
