### ISSUE TITLE
Incoming critical rate

### ISSUE THREAD

**Issue by lethewyvern** [WarEmu/WarBugs#17644]
**Expected behavior and actual behavior:**

Enormous critical rate of incoming attacks

**Steps to reproduce the problem:**

Dunno, just watch screen of .getstats command

**Testing Screenshots/Videos/Evidences (always needed):**

![crit](https://user-images.githubusercontent.com/57109035/91490695-4b266000-e8cc-11ea-86df-162858538982.JPG)

**Comment by indal-andal** [comment]
Feeding on Fear (marauder tactic) is bugged, dont slot it until they fix it (whenever it procs it increases your chance to be crit up to 100%, so even rank1 rats will crit you permanently)

**Comment by dalen** [comment]
Fixed in hotfix 2
