### ISSUE TITLE
Distracting below reduced enemy damage taking instead inflicted

### ISSUE THREAD

**Issue by coltylul** [WarEmu/WarBugs#17640]
Have this on my BG. Tested in pvp and pve.

**Comment by DanskuL** [comment]
Please provide proof of this, screenshots/videos whatever.

**Comment by coltylul** [comment]
![m2](https://user-images.githubusercontent.com/70328694/91452801-4e472f00-e87f-11ea-9101-71742eb4ec86.jpg)

**Comment by dalen** [comment]
that seems bad, I'll try to take a look at this soon

**Comment by dalen** [comment]
Fixed in hotfix 2
