### ISSUE TITLE
Deathblows in Scenarios/Cities are only going to players that did highest damage, not who got the deathblow

### ISSUE THREAD

**Issue by emailkook** [WarEmu/WarBugs#17641]
**Expected behavior and actual behavior:**
Player who got the last hit, "Deathblow", should be awarded the Deathblow on the Scoreboard. 
Actual behavior is credit for the Deathblow is only going to the player that did the highest damage, not who got the "Deathblow" how it's always been.
Last scenario done 8/27/2020 in Nordenwatch, I got multiple deathblows as Enemy makes a sound and writes it in the window. When the scenario ended, showed I had 0 deathblows.

This explains cities after patch where Choppa/Slayers/BW, etc are getting most of the Deathblows while the mediocre AOE classes are getting MUCH lower amounts after the recent patch.

I believe this is due to the new Quest contribution system that gives the credit to the player/group that did the most damage. It's actually applying it to the Deathblow counter on scoreboard.

Since scenarios now give rewards to the top of each category, it's important for the deathblow to be accurate. It's not always about who does the most damage. As in this case, a target can survive and get away, then someone Pounces or stealths in to finish them off but get zero credit for it and just gave it to someone else.

**Steps to reproduce the problem:**
During a scenario, let a player do most of the damage and have him stop, then do the last hit or two for the Deathblow. On the scoreboard, player that initially was doing the damage got the 'Deathblow" stat on scoreboard.

**Testing Screenshots/Videos/Evidences (always needed):**

![capture](https://user-images.githubusercontent.com/50253609/91469758-6dcb6100-e859-11ea-93e0-20e7304ed3d7.png)

**Comment by dalen** [comment]
Fixed in hotfix 2
