### ISSUE TITLE
Warrior Priest - Hammer of Sigmar is ignoring tooltip

### ISSUE THREAD

**Issue by warrencsteven** [WarEmu/WarBugs#17646]
While WP Wrath is my full time spec and I get stomped most of the time, in the spirit of the game and kudos to those who give their spare time to having a public server to play on.

Warrior Priest - Hammer of Sigmar is was permanently at 5s cooldown [Cannot replicate now] (should be 10s and 5s only when Sigmars Wrath buff is up - recent change to buff) and can be used at any % of health (bugged - pretty much spammable on 5s cooldown). Likely bugged if you have two hander with Sigmar Wrath on bars (did not check this, but will when I log back in).

How to reproduce - nothing special, just hit any mob with it first time and check the cooldown timer.

Let me know if you need any more info.

**Comment by Rydiak** [comment]
I could not reproduce this. Do you have any more info?

**Comment by warrencsteven** [comment]
Hey Rydiak. Currently playing and Hammer of Sigmar is currently on my character allowing to hit on any percentage health. On the 5s cooldown, when I logged and came back it reset back and was behaving as intended, but I was on keep lord a few minutes ago and somehow now it is locked to 5s cooldown again.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17655
