### ISSUE TITLE
City siege destruction entered order starting point

### ISSUE THREAD

**Issue by Estigia59** [WarEmu/WarBugs#17648]
Hello,
**Expected behavior and actual behavior:**
Destro are not supposed to trespass barriers and enter into order starting point, however, today in City 2, some of them were able to enter into the starting point and kill order. Maybe engi pulled, but we got no answer and thought it might be a bug.

**Testing Screenshots/Videos/Evidences (always needed):**

![Maenieth_033](https://user-images.githubusercontent.com/29825413/91519487-ac5d2c00-e8ea-11ea-91b8-7fe51ab92e92.jpg)

![Maenieth_034](https://user-images.githubusercontent.com/29825413/91519497-b3843a00-e8ea-11ea-8699-59354bfd3387.jpg)

Thank you very much for your time and support.
Kind Regards.

**Comment by Kaelang** [comment]
This happens when people get pulled in.
