### ISSUE TITLE
Warrior Priest Offhand Regeneration inconsistency 

### ISSUE THREAD

**Issue by Hroney** [WarEmu/WarBugs#17650]
I have noticed an issue between WP Tomes and their passive regeneration. 
For example; Tome of Repose (Which has +8 RF regen per second) and Apostle's Tome of Solemnity (Which has +8 RF regen per second) Regenerate RF passively at different rates, despite sharing the same increase per second. 
The latter regenerates a steady 20 RF passively per second out of combat while the former is +18 every half second interval and +12 on every full second interval. I have noticed this over Many different tomes and want to wear certain tomes for certain stat distributions, but notice a very different rate in RF regeneration which changes my play-style quite dramatically. Can this be looked at perhaps?

**Comment by Hroney** [comment]
Upon further investigation, some Offhands do not regenerate RF even in combat.

**Comment by Kaelang** [comment]
Some tomes take a requip a few times to activate, legacy issue that is always solved by reequiping the tome.
