### ISSUE TITLE
Non working fort tomb and fort hammer

### ISSUE THREAD

**Issue by Ladylissa** [WarEmu/WarBugs#17656]
I noticed today that on my WP (Ladysmoke) both of my fort weapons are not working.I checked my character select screen and my fort tomb and fort hammer are there just not registering the stats for them. If you mouse over them it shows them as being there but on my action bar my melee abilities are grayed out and do not work . Any time I try to do damage it says I must have a melee weapon in my right hand. I have been playing my other characters lately and just didn't notice.  I have played this toon a long time and put in a lot of  healing time on her for them to just not work. I would really like to have them working as they are designed to. I am not sure of the exact date they started not registering though. I  have pictures of Ladysmoke showing the weapons when moused over her hands and the action bars abilities grayed out. 
![Ladysmoke 1](https://user-images.githubusercontent.com/33042601/91621252-79557f80-e960-11ea-961d-16a7e5ccb9a9.jpeg)
 
![Ladysmoke3](https://user-images.githubusercontent.com/33042601/91621311-aace4b00-e960-11ea-977b-26971748c419.jpeg)

 Thank you in advance for the help in getting them working.

**Comment by Kaelang** [comment]
Looks like a client issue, try repairing your client.

**Comment by Ladylissa** [comment]
I have tried everything I know to fix it. I ended up just deleting the whole game and am now in the process of the launcher downloading stuff. I am now on day 4 of the launcher downloading things. I hope this works to get my weapons to work as they were designed to do.
