### ISSUE TITLE
Dok's Execute has 5 sec CD, instead of 10 sec

### ISSUE THREAD

**Issue by Zxul** [WarEmu/WarBugs#17655]
**Expected behavior and actual behavior:**
Dok's Execute should have a 10 sec CD without Drowning in Blood, but currently its 5 sec- when you use the skill it shows the 10 sec timer for a moment, then instantly goes down to 5 sec, and you can actually use it after 5 sec.

**Steps to reproduce the problem:**

Attack something, wait for it to get to 50% hp, use Execute, wait 5 sec and use it again.

**Comment by Rydiak** [comment]
So if you use Execute on a target below 50% HP, and never cast Drowning In Blood, it will make the cooldown 5 seconds?

**Comment by Zxul** [comment]
Yes exactly. Testing with Drowning In Blood btw, same 5 sec CD- so a time you got 5 sec Execute without needing Drowning In Blood being off CD.

**Comment by dalen** [comment]
I think I found the issue that could cause this
