### ISSUE TITLE
Blind Faith: Quest not Working Warhammer Return of Reckoning

### ISSUE THREAD

**Issue by Xennian** [WarEmu/WarBugs#17657]
The quest Blind faith from Chaos (chapter 17) in West Praag does not work. Its divided into two parts where you have to enter a cave and click on 3 ironbeard cannons which works fine. The second part where you have to kill Baragrom Blackbeard does not. The target is not anywhere inside the cave nor outside it, he does not spawn after clearing every mob and pressing every clickable item. I do believe he is meant to be standing at the end like a boss. Perhaps he is stuck inside a wall, or not implemented?

I tried googling forum but found nothing mentioned of him in either age of reckoning or return of reckoning. Quest cannot be progressed in West praag. I dont think i can contribute any picture or screenshot that would help as he is simply not to be found.

Yours sincerely,

Xen

**Comment by Lheana** [comment]
No issue here, just checked and Baragrom Blackbeard is where he is meant to be.

**Comment by Xennian** [comment]
@Lheana Are you sure you didnt see Yorrik Ironbeard or the engineer? Neither of them count for the quest when killed or looted..? Am I misunderstanding the placement of Baragrom Blackbeard, as i cannot find him anywhere inside the cave even when  i clear every mob...

**Comment by Lheana** [comment]
I am sure, Baragrom Blackbeard is inside the cave.

**Comment by Xennian** [comment]
I went to check again and i finally saw him spawn on the bottom floor, my bad @Lheana. thank so you so much though
