### ISSUE TITLE
[WL] Sentinel weapon proc grants 80 wounds instead of 110

### ISSUE THREAD

**Issue by JackHollowPoint** [WarEmu/WarBugs#17653]
*Expected behavior and actual behavior: 
In weapon description it is stated "On Being Hit: 10% chance to increase Wounds by 110 for 20 seconds", while in reality it grants only 80 wounds (like weaker epic quest weapon) 

**Steps to reproduce the problem:
Equip weapon and get attacked.

***Testing Screenshots/Videos/Evidences (always needed):
 hp without weapon proc:
![Kimba_008](https://user-images.githubusercontent.com/25168701/91581240-df3d0980-e956-11ea-96d8-1d7b681e4697.jpg)
weapon proc
![Kimba_010](https://user-images.githubusercontent.com/25168701/91580981-8ec5ac00-e956-11ea-859d-d479662d6cab.jpg)
weapon
![Kimba_011](https://user-images.githubusercontent.com/25168701/91580950-840b1700-e956-11ea-859e-56ae1fa61b50.jpg)

**Comment by Kaelang** [comment]
This is a known and listed issue.
