### ISSUE TITLE
Alternate appearance disappearing upon mailing item

### ISSUE THREAD

**Issue by Ryanfawkez** [WarEmu/WarBugs#1765]
Upon using a tradable item with alternate appearance enabled, and sending it through the mail to another character, causes the applied appearance to be lost in the process.

**Comment by magter3001** [comment]
I think that is how it's supposed to perform. I don't think that's a bug.

**Comment by Evildoor** [comment]
I agree with @magter3001. Maybe it can be changed, but it's not a bug. Closing, unless someone proves otherwise.
