### ISSUE TITLE
Beastlord Tokens missing after server restart.

### ISSUE THREAD

**Issue by Frecard** [WarEmu/WarBugs#17652]
**Expected behavior and actual behavior:**
Completed and handed in all five oRvR quests to recieve Beastlord Tokens.
Recieved all 5 tokens.
After server restarts today (28.08), im left with 2 tokens (And i did not delete or buy something with the missing 3 tokens)

- The quests are not obtainable anymore, since i completed them all, and i can't obtain the 3 missing tokens by other means.

**Steps to reproduce the problem:**
Not sure.

**Testing Screenshots/Videos/Evidences (always needed):**

![bestialtokens](https://user-images.githubusercontent.com/70372795/91549021-94a39900-e926-11ea-8e59-041af022e2dc.png)
![bestialtokens2](https://user-images.githubusercontent.com/70372795/91549027-9705f300-e926-11ea-908f-f300a88d9fc5.png)

**Comment by Kaelang** [comment]
This is a known issue that happens with some restarts - there currently isn't any way for us to return items lost due to restarts.
