### ISSUE TITLE
Discordant Turbulence (Chosen) and Windblock (Zealot) are stacking

### ISSUE THREAD

**Issue by emailkook** [WarEmu/WarBugs#17662]
**Expected behavior and actual behavior:**
Expected: Windblock should overwrite Chosen aura for a total of 50% heal debuff per M4 morale.

Actual: Zealot Morale 4 Windblock 50% heal debuff for 10 seconds has been stacking with Chosen 25% heal debuff aura for a total of 75% heal debuff for 10 seconds while Windblock active.  This has been spoken of by many organized warbands during City instances and current practice going on with Zealot self pump Morale quick to M4 then dropping it on the Chosen causing majority of players on vicinity to die due to it being a 75% total heal debuff, nearly nothing for 10 seconds.

**Steps to reproduce the problem:**

Heal an Order player
Have a Chosen stand on him to see the 25% heal debuff.
Have Zealot heal Chosen to build Morale 4 quick using their self pump heal crit tactic. 
Drop the M4 Windblock on top of the Chosen/Order player and observe the incoming heals.

Will edit post to add screenshot when can get a test in or next city to log, but has been common knowledge for past month on the ability to stack.

**Comment by pkfsa** [comment]
morales stack with normal abilities

**Comment by iantheace** [comment]
All morale abilities, stack with normal abilities, if this is incorrect, then all of these need correcting.

**Comment by acidicrain** [comment]
The stacking rules as I remember them were ability tactic and moral stacked, has this rule been changed ?

**Comment by emailkook** [comment]
I don’t think 75% heal debuff was intended even if some normal abilities and morale would stack. A fix for it might even be leaving it stacking but lowering the value to match the 50% total intended.  Anyone have memories of live because I don’t remember a 75% stack and I played Zealot. Let alone every zealot can equip self morale pump. If there is a fix pending, it can be many things but at this stage it’s just as powerful as pre-morale nerf which they tuned down for a reason.

**Comment by acidicrain** [comment]
This sounds like a change suggestion not a bug, what is strange is fix pending on something not a bug.

**Comment by emailkook** [comment]
If fix is pending, it’s agreed on not being intended internally and not
their vision.

**Comment by pkfsa** [comment]
> 
> 
> I don’t think 75% heal debuff was intended even if some normal abilities and morale would stack. A fix for it might even be leaving it stacking but lowering the value to match the 50% total intended. Anyone have memories of live because I don’t remember a 75% stack and I played Zealot. Let alone every zealot can equip self morale pump. If there is a fix pending, it can be many things but at this stage it’s just as powerful as pre-morale nerf which they tuned down for a reason.

I didn't play live but afaik heal ritual didn't proc morale pump on live so there you go
