### ISSUE TITLE
Can't get crafting skill on character 

### ISSUE THREAD

**Issue by MarioKrmpota** [WarEmu/WarBugs#17665]
On my magus (Mememaster) I can't get any crafting skill from any npc, anywhere, anytime. 
I've tried multiple times, over the past 2 weeks, but the result is always the same. I get the window asking me if I want to learn the skill, then nothing happens no matter what choice I pick.

**Comment by Kaelang** [comment]
The crafting system is working - it's likely you already have two skills and haven't unlearned one.
