### ISSUE TITLE
(SM) Nature's Blade

### ISSUE THREAD

**Issue by SickSalmon** [WarEmu/WarBugs#17667]
The SM skill Nature's Blade only provides a fraction of the supposed stat points when proccing.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
More information please.

**Comment by CrimsonFenris** [comment]
Check if it's not overlapping other main stats buffs, like potions, liniments and runepriest buffs ; Nature's blade buffs don't stack with any of those, you'll only see the best buff applying (most likely your stats stealing, 120 pts with maxed tree).
