### ISSUE TITLE
Cannot queue for SC'S

### ISSUE THREAD

**Issue by Tallanvor1** [WarEmu/WarBugs#17663]
<!--Cannot queue for scenarios, talked to multiple GMs, Wrathchild and one on destro side, they could not help me.  When I click the icon, simply nothing happens.  I am not running any addons, I created new characters to test, did /rel and /reloadui many many times, as well as completely exiting launcher and game multiple times.  I searched on the forums and also on advice chat, and still, cannot run scenarios.  Scenarios are a huge part of why I play the game.  On any character in any tier at any time of day I have this problem, simply put it is like the button does not exist, no flash etc. it is there, but does nothing. Thank you.

**Comment by Kaelang** [comment]
The scenario manager is working. You may want to look on the forums for some support.

**Comment by Tallanvor1** [comment]
Have not been able to find anything on the forums relevant 
-------- Original message --------From: Kaelang <notifications@github.com> Date: 8/30/20  4:42 AM  (GMT-08:00) To: WarEmu/WarBugs <WarBugs@noreply.github.com> Cc: Tallanvor1 <Chandler.hermansen@gmail.com>, Author <author@noreply.github.com> Subject: Re: [WarEmu/WarBugs] Cannot queue for SC'S (#17663) 
The scenario manager is working. You may want to look on the forums for some support.
