### ISSUE TITLE
Black Dragon in Cinder Fall

### ISSUE THREAD

**Issue by Ralinnanth** [WarEmu/WarBugs#17678]
There is a dragon in cinder fall that appears to be unkillable at some points and killable some other points. I am not sure if it is a major glitch or not but I am trying to farm. It walks down the mountain and if I am lucky can taunt him and he will come and I can kill him. Other times it wont allow me to taunt or kill.
![BD Glitch](https://user-images.githubusercontent.com/70601552/91892521-cbe4b380-ec60-11ea-9739-73baecbfabcb.jpg)

**Comment by Kaelang** [comment]
Not bugged.

**Comment by Ralinnanth** [comment]
Oh oki, wasn't sure. Thank you for the info!
