### ISSUE TITLE
KOTBS - "Banish darkness" tactic doesn't work 

### ISSUE THREAD

**Issue by starness88** [WarEmu/WarBugs#17670]
Expected behavior and actual behavior: 
When "Banish Darkness" tactic is sloted the ability "Repel Darkness" should throw further. 

Steps to reproduce the problem: 
I don't know, other people don't seem to have the same bug 

Testing Screen

shots/Videos/Evidences (always needed): I tried with a sword and shield and with a two handed weapon
2H : https://imgur.com/a/Bm9t0Pv
Sword and Shield : https://imgur.com/a/1BCLDSq

**Comment by iantheace** [comment]
This ability works fine, however there is a major bug where peoples tactics randomly stop working at present, particularly as they go in SC's. I would imagine you are affected by this.

**Comment by Kaelang** [comment]
Already reported.
