### ISSUE TITLE
Chosen Auras

### ISSUE THREAD

**Issue by Hawkehearteater** [WarEmu/WarBugs#1767]
Not sure if this has been addressed, but I am able to have two chaotic auras active at the same time. And not just for the temporary 12 seconds, it seems indefinite.
![gingio_000](https://cloud.githubusercontent.com/assets/15389914/10836886/c103e180-7e78-11e5-8efc-b3d351f26ef8.jpg)

**Comment by Ungrin** [comment]
This is working as intended.

**Comment by Evildoor** [comment]
Not a bug, it was intentional change. Everyone was running Twister anyway, which pretty much granted the same functionality (3 auras always on).
