### ISSUE TITLE
Pouce/Wings Of Heaven into keep

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#17674]
Today at Praag keeps defense a SM got inside the inner keep (Southern Garrison) by using Wings of Heaven. I always thought Pounce/Wings of Heaven was not possible to get inside keeps? I enclosed a picture of the spot where you can use Wings of Heaven to get inside. 

![Alastrelle_006](https://user-images.githubusercontent.com/11788060/91849126-d5b7e800-ec5b-11ea-973f-c8611652518f.jpg)

**Comment by depood** [comment]
There are multiple spots over all tiers where SM (m2) and mSH can bounce in. If you want i can provide all location i know and tested.

**Comment by wargrimnir** [comment]
More reasons to nerf the range on WOH and Pounce type abilities

**Comment by dalen** [comment]
This is fixed by the general blocking of pounce-like abilities to inner keep areas in the 2020-09-09 patch.
