### ISSUE TITLE
IC Rewards not Calculated Properly (City Siege 12v12)

### ISSUE THREAD

**Issue by Haojun-Phalanx** [WarEmu/WarBugs#17675]
01/09/2020 IC Siege, 12v12 Instance 
Stage 1 / Stage 2 / No gold bag.
Stage 3, however there is gold bag.

stage1: https://gyazo.com/2501e6e84a7aa6ae3d9f8a05e1b650ec
stage3: https://gyazo.com/acf5fcb7096317318eb2fd4e702b65d9

stage3: https://gyazo.com/b22401bc3ce6beeb93e45079744f7734

**Comment by dalen** [comment]
Likely there were 13 participants in some of the stages, so same as https://github.com/WarEmu/WarBugs/issues/17647

But it is fixed in this weeks patch.
