### ISSUE TITLE
Vulgar Display of Power - PQ 

### ISSUE THREAD

**Issue by Vicgrim** [WarEmu/WarBugs#17689]
Vulgar Display of Power - PQ  in Reikland destro chapter 21.
PQ can't be finished.  Because on stage 3 Captain Becker`s Head cant be piked.
 
**Expected behavior and actual behavior:**
Captain Becker`s Head must be piked  and stage 4 should be start.

**Steps to reproduce the problem:**
On stage 3 you need to kill Captain Becker and his guards, after kill you need put his head on pike but his head cannot be "piked"

3:50- 4: 50 Captain Becker
0:34 - 2:12 pikes on stage  1

https://youtu.be/LVeXOjOfPcI

**Comment by Lheana** [comment]
That's because these are not the right pikes you need to set the head atop.

**Comment by kyraith** [comment]
I tried every pike in the PQ zone. None of them worked
