### ISSUE TITLE
Halfing pie not working

### ISSUE THREAD

**Issue by redman012** [WarEmu/WarBugs#17680]
**Expected behavior and actual behavior:** Halfing pie should be able to be thrown at friendly targets, order can use on order and destro can use on destro. It turns out there is bottomless custard and that does currently work, but halfing pie does not. Can those be changed from halfing pie to bottomless custard or can we fix it halfing pie.

**Steps to reproduce the problem:** Buy halfing pie from vendor and add to your hotbar. Click on skill and it show throw pie on friendly target. But it does not.

**Testing Screenshots/Videos/Evidences (always needed):**
Halfing pie  (does not work)
![image](https://user-images.githubusercontent.com/65742872/91919556-5692d600-ec94-11ea-8667-2e666d1ca044.png)

Bottomless custard   ( works)
![image](https://user-images.githubusercontent.com/65742872/91919600-74f8d180-ec94-11ea-9d0e-987ab4781c7f.png)

**Comment by Kaelang** [comment]
Already reported.
