### ISSUE TITLE
Braewold the Depraved

### ISSUE THREAD

**Issue by Hawkehearteater** [WarEmu/WarBugs#1768]
Gets attacked by his rapturous cultists immediately upon spawning.
![gingio_001](https://cloud.githubusercontent.com/assets/15389914/10837291/509029ae-7e7d-11e5-97eb-30c2826d5ff2.jpg)

**Comment by Meralors** [comment]
He should no longer be killed by npc.
Will be pulled to live next update, can close issue :)
