### ISSUE TITLE
Tier 1 Bolster turning off on BO

### ISSUE THREAD

**Issue by HumblePeasnt** [WarEmu/WarBugs#17687]
in one spot in Festenplatz it turns off bolster, screen shot attached. 

does seem to re bolster when outside of the BO.

**Expected behavior and actual behavior:**

Bolster should not turn off within RVR area

**Steps to reproduce the problem:**

took 2 characters there and the same thing happened multiple times.

**Testing Screenshots/Videos/Evidences (always needed):**

![Screenshot (6)](https://user-images.githubusercontent.com/70657117/92016069-b4cdc080-ed49-11ea-820c-0af4aa56223a.png)

**Comment by HumblePeasnt** [comment]
also happened on harvest shrine and any supplies from harvest shrine disappeared when getting close to the flag

**Comment by MaxHayman** [comment]
We have a fix and it will be pushed asap.
