### ISSUE TITLE
Auction house window not opening anymore. Unable to interact with AH NPCs

### ISSUE THREAD

**Issue by PandaOrc** [WarEmu/WarBugs#17686]
Hi,

I am unable to interact with AH NPCs. Every time I click on them nothing happens. They just refuse to bring the auction house window up. This issue started yesterday.

Regards,
Gladius

**Comment by MaxHayman** [comment]
Seems to work fine. Did you try closing the game and repatching?

**Comment by Psychoxell** [comment]
i had the same. I just closed the game und started the updater again. After that it works fine

**Comment by MaxHayman** [comment]
Confirmed reports of fixed with repatch. Closing.
