### ISSUE TITLE
Invader in bags with full Invader already geared?

### ISSUE THREAD

**Issue by Romanuzo** [WarEmu/WarBugs#17694]
Hello!
Got 3 bags from City, and they all were filled with invader crests, while for a stage i've got royals.
On yesterday's city everything were working properly.
![image](https://user-images.githubusercontent.com/42448411/92045227-b10d5e80-ed88-11ea-95a8-53aa693d729a.png)

**Comment by Kaelang** [comment]
Please can you show your ToK?

**Comment by Romanuzo** [comment]
Sure thing!
![image](https://user-images.githubusercontent.com/42448411/92045381-0c3f5100-ed89-11ea-96ec-05815bd5e215.png)

**Comment by Kaelang** [comment]
What's your RR?

**Comment by Romanuzo** [comment]
64.
![image](https://user-images.githubusercontent.com/42448411/92045509-604a3580-ed89-11ea-9467-ee234bbcb11b.png)

but ive got royal crests from bags on yesterdays city

**Comment by Kaelang** [comment]
RR 70 is the minimum for crests - so unsure what happened yesterday but please re-open post 70 if it happens again.
