### ISSUE TITLE
City Siege: Scenario UI completely blank

### ISSUE THREAD

**Issue by 5119ror** [WarEmu/WarBugs#17693]
**Expected behavior and actual behavior:**
Expected behavior: scenario party, scenario map, and scenario scoreboard are usable in city
Actual behavior: scenario party, scenario map, and scenario scoreboard are completely blank

![image](https://user-images.githubusercontent.com/69434505/92044889-0e2af500-ed34-11ea-8028-ad6baaebc9c8.png)
![image](https://user-images.githubusercontent.com/69434505/92044908-18e58a00-ed34-11ea-98bd-eb99e11ed346.png)
![image](https://user-images.githubusercontent.com/69434505/92044928-23078880-ed34-11ea-92e5-9510731499de.png)

**Comment by Kaelang** [comment]
Hi we are aware of this issue - thank you for the report.

**Comment by MaxHayman** [comment]
Fix pending. Will push shortly.
