### ISSUE TITLE
PQ Destruction of the Weak and other PQ's not properly being tracked.

### ISSUE THREAD

**Issue by Xruptor** [WarEmu/WarBugs#17695]
Example, Destruction of the Weak PQ does not display any Public Quest Tracker information because the PQ itself and the surrounding area (zone) is never unlocked via the TOK.  This is the second PQ from the Chaos starter area I'm talking about.  The first one works just fine.  I think these issues are tied with the TOK and it needs to be unlocked before they get displayed or something.  This same issue happened in a greenskin area where the PQ tracker would not come up, even though I knew there was one in the area.

**Comment by Kaelang** [comment]
![image](https://user-images.githubusercontent.com/60117106/92047152-4eae6100-ed7c-11ea-9eb0-db303f1e1a7d.png)
Can confirm, likely related to the map changes. Will need @MaxHayman to take a look.

**Comment by MaxHayman** [comment]
Found the issue. Wulfsiege was not assigned to Chaos Chapter 2.

**Comment by MaxHayman** [comment]
Fix live.
