### ISSUE TITLE
Quest: Lob It Good! still bugged after all this time.

### ISSUE THREAD

**Issue by Xruptor** [WarEmu/WarBugs#17696]
This quest is still bugged and it confuses new players.  You are supposed to be lobbed over to the dam with the dwarves to continue this quest chain.  However, interacting with the Catapults does nothing and you cannot fling yourself there.  There is a way to climb up a tree, but that is just a work around and honestly does tend to confuse players.  I've seen folks asking about it in chat.

As a suggestion, put an NPC or an option on an NPC to just teleport you to the location.  You MAY want to put this in the description of the quest to talk to the NPC or something.

Apparently this has been attempted to be resolved in the past.  One of the tickets even states to talk to the "Lob Gitters" near the catapults to teleport you there.  However, currently interacting with ANY NPC at that location does absolutely nothing.

Previous Bug Reports.
https://github.com/WarEmu/WarBugs/issues/10072
https://github.com/WarEmu/WarBugs/issues/6745
https://github.com/WarEmu/WarBugs/issues/3905

Currently you have to do this mountain climbing trick as described here to circumvent this.  I think a simple teleporting NPC would be just fine.  Method to climb using tree is found here.
https://returnofreckoning.com/forum/viewtopic.php?f=5&t=32982

![Grubcrusher_000](https://user-images.githubusercontent.com/202515/92048449-bac99e80-ed55-11ea-97f6-f3573a2102ac.jpg)

![Grubcrusher_001](https://user-images.githubusercontent.com/202515/92048461-c026e900-ed55-11ea-9242-e4b7f0f115ec.jpg)

![Grubcrusher_002](https://user-images.githubusercontent.com/202515/92048473-c61cca00-ed55-11ea-9688-48b2a01db6b8.jpg)

As you can see interacting with anything doesn't work.

**Comment by MaxHayman** [comment]
Can you try going very very close to the middle catapult and then clicking it?

**Comment by Xruptor** [comment]
> Can you try going very very close to the middle catapult and then clicking it?

I tried that and it didn't work either.  I clicked everywhere and everything near the middle catapult.  The only thing that would work was allow me to use it to go into siege mode.  I think it's tied to how the object is being interacted.  Instead of it thinking it's an object with a teleport function, it still thinks it's a siege weapon.  

I think interacting with any of the Lobba Gitters or even putting an NPC to just teleport you there would be perfect.  However, you may want to put it in the Quest Notes itself so folks would know.

**Comment by Xruptor** [comment]
Thanks for the fix.  Did you go with the teleporting NPC or making the Catapults take you?

**Comment by MaxHayman** [comment]
It was working but must have broken recently. It catapults you.
