### ISSUE TITLE
Black Crag tunnels despawn siege objects

### ISSUE THREAD

**Issue by xanniez** [WarEmu/WarBugs#17692]
Since last patch, all siege objects (cannons, rams, etc) despawn when inside of any of the three tunels of Black Crag, so sieges are not possible.

Steps to test:
Spawn any siege object and try to bring it from 1 keep to the other.

Attaching video:
https://streamable.com/l42nl9

**Comment by MaxHayman** [comment]
Issue was caused by ram not detecting area by using fixture. We have a fix and it will be pushed asap.
