### ISSUE TITLE
RvR un-bolster

### ISSUE THREAD

**Issue by mrandregoe** [WarEmu/WarBugs#17691]
Some places in Nord near Festenplatz un-bolster and removes RVR from you

**Comment by mrandregoe** [comment]
![Screenshot (39)](https://user-images.githubusercontent.com/53059058/92036741-09a62100-edb4-11ea-906d-18ffe7821d9b.png)

**Comment by mrandregoe** [comment]
![Screenshot (40)](https://user-images.githubusercontent.com/53059058/92036864-3b1eec80-edb4-11ea-8ae5-cf5922ea24bd.png)

**Comment by MaxHayman** [comment]
We have a fix and it will be pushed asap.
