### ISSUE TITLE
No Bolster in the Blood of the Black Cairn Scenario T1-t4

### ISSUE THREAD

**Issue by stonefuzzy** [WarEmu/WarBugs#17703]
Bolsterfunction doesnt work in Blood of the Black Cairn Scenario(in T1 and T2-3). As well as randomly dropping in Nordland/Norsca T1 rvr lake. It happens since the patch from 02.09.2020

**Comment by MaxHayman** [comment]
Fix for Blood of the Black Cairn will go on next reboot. EvC T1 issue should have been fixed yesterday.
