### ISSUE TITLE
Ranked Que Quitter

### ISSUE THREAD

**Issue by Haojun-Phalanx** [WarEmu/WarBugs#17707]
Sometimes if someone declines "ready check" whole session bugs out and u get quitter while you are still on que.

https://gyazo.com/9cb138ad52e21f6a44a2fba1fa9229d5
https://gyazo.com/1664f601876e77f37522936dbd264a26

**Comment by Opeteh** [comment]
On similar bug, you are being told that you are re-queued (and your Scenario's button flash active) but then no pop for a long time so you leave the queue and see that numbers i.e. Destro healers doesn't hanged untill you re-queue yourself again.

**Comment by pkfsa** [comment]
had this happen too
