### ISSUE TITLE
Ranked SC Queue Bug - Multiple re-queue, eventual quitter

### ISSUE THREAD

**Issue by keunglh** [WarEmu/WarBugs#17705]
Happened twice today, thought the first was a fluke, but decided to report the second one. Within the span of 1-2 minutes, had multiple "re-queues" for ranked scenarios, but after the most recent one the queue window disappeared on me before I could click it. I assumed that someone left the queue, but after a minute I received a quitter debuff. 

I even tried spamming the macro to force join the scenario without luck. 

**Expected behavior and actual behavior:**
If players don't accept the queue, players should be placed back into the queue at the front until the next available ranked scenario is ready. 

**Steps to reproduce the problem:**
Have repeat ranked sc queue pops and see what happens. 

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/14348489/92137116-6c0e1a00-edd2-11ea-859c-465e7148718b.png)

**Comment by dalen** [comment]
likely fixed in hotfix
