### ISSUE TITLE
Bolster is not being applied in Black Cairn scenario, T1 Order

### ISSUE THREAD

**Issue by DracoRyx** [WarEmu/WarBugs#17709]
Playing Blood of the Black Cairn in T1 Order and bolster seems to not exist. My stats are not adjusted, my level is not adjusted, and nothing is particularly fair on either side. I haven't tested on destro T1. I'm unsure if that's intended or not, as I've never seen a scenario NOT have bolster unless you're at the top level of the tier.  Stats were not being bolstered, I was one-hitting level 5 and below players and getting 2-3 hit by level 15s.

Screenshot included of full screen to show no bolster icon, and no green bolstered levels on party. Smaller screengrab of a party member with no bolstered level as well.  As you can see in both screenshots, no bolstered level, bolster buff is not appearing.

![No + Level](https://user-images.githubusercontent.com/5627624/92148805-ec804b00-edd1-11ea-9aab-d6c0af2ab89c.png)
![No Bolster Vanilla UI](https://user-images.githubusercontent.com/5627624/92148808-ed18e180-edd1-11ea-98b3-43640ca51e8b.png)

**Comment by Kaelang** [comment]
Already reported
