### ISSUE TITLE
Cheaters!!!

### ISSUE THREAD

**Issue by BFGka** [WarEmu/WarBugs#17702]
a friend of mine told me a story about meeting with a witch hunter named Krubs. It opened out of invisibility and immediately my friend received two damage from a fall of 1200 units! Although at that moment there were no hills nearby, and then he killed him for a knock! take note of this, they found something how to do fall damage on a target to kill!

**Comment by Rydiak** [comment]
Any screenshots of the combat log, or is this just going to be a hearsay witch hunt?

**Comment by Kaelang** [comment]
The Bugtracker isn’t here to report players.

**Comment by BFGka** [comment]
Unfortunately he did not save the screen, but we will definitely
screen it next time! I swore at him too! Just guys pay attention to
this, maybe someone else will complain about this. Thank.


чт, 3 сент. 2020 г. в 20:19, Rydiak <notifications@github.com>:
