### ISSUE TITLE
Joined a Scenario with just one other person, this can't be normal.  Irregular Scenario Parties....

### ISSUE THREAD

**Issue by Xruptor** [WarEmu/WarBugs#17715]
I queued for a scenario and got a pop.  I went in and it was just one other person.  No one ever joined and it remained that way the entire match.

![Zuldak_030](https://user-images.githubusercontent.com/202515/92268412-553df500-eeb0-11ea-808c-ba85eab0f9ef.jpg)

**Comment by DmitriyMaksimovich** [comment]
The same thing happens to me very often

**Comment by Xruptor** [comment]
Yep it's been happening all day.  Lots of folks have complained about it in Advice/LFG and such.  It's like the queue system is broken or something.  Some folks claimed there was a server crash and that caused it but I doubt it.  It's been affecting T1 and T2 at least for me.  I've heard folks in T4 say the same thing.

**Comment by Xruptor** [comment]
![weird makeup](https://user-images.githubusercontent.com/202515/92601269-9bad9e00-f27a-11ea-911a-acefb0c6b0cf.png)

Here is another match where I was put in with only 3 people the entire match.

As a suggestion, scenarios should only pop when at least one group is completely full.  It doesn't have to be that every group is full.  Just maybe the first group 1.  Then trigger the pop for the scenario if you like.  Right now I'm not entirely sure what's going on.  I'd glady wait longer if the Scenario would pop with at least the first group full.
