### ISSUE TITLE
Weird city crash issue

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#17719]
Not sure whether this should be on the bugtracker or not as I have no idea whether the problem is with the game or my system, but I'm noticing that in every city siege my game crashes shortly after making first contact with the enemy in stage 1, I get about 10-15s of combat and then crash, after I relaunch the game it runs perfectly, no crashes, no lag, no graphics bugs (also worth noting that the game runs fine for me outside of cities, even in concentrated action like fort fights).

I have now confirmed that if I deliberately crash the game while waiting for stage 1 to begin and then rejoin the siege, it dosnt crash at first contact.

Also worth noting, I know that the contribution system in cities is messed up, but I notice that I always seem to be 24th contribution when I crash in stage 1, no matter how much participation I put in after rejoining.

**Comment by Kaelang** [comment]
Tech Support on Forums / Discord.
