### ISSUE TITLE
When stage finishes I get kicked out from the game

### ISSUE THREAD

**Issue by barfyman92** [WarEmu/WarBugs#17717]
**Expected behavior and actual behavior:**

When a stage finishes in city siege I get kicked, on relogg the que pops but i click accept it goes away nothing happens.. then i get quitter..

**Steps to reproduce the problem:**

NO idea, unique to one of my characters. Happens consistently

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
If this is unique to one character, this isn't a bug for the tracker.
