### ISSUE TITLE
[BG] Crimson Death - wrong duration [tooltip]

### ISSUE THREAD

**Issue by M0rw47h** [WarEmu/WarBugs#17713]
**Expected behavior and actual behavior:**
According to tooltip Crimson Death should last 5 seconds, while in reality it's 10 seconds debuff to match Overpowering Swing.
Tooltip could use an update.

![ezgif com-crop (14)](https://user-images.githubusercontent.com/35219756/92246603-49f5c400-eec6-11ea-9943-818a07c6bd3a.gif)
![Nowy projekt (25)](https://user-images.githubusercontent.com/35219756/92246006-73fab680-eec5-11ea-96cf-f2e4c7a4fcc6.png)

**Comment by JackHollowPoint** [comment]
> in reality it's 10 seconds debuff to match Overpowering Swing.
In reality they are vastly different: Overpowering Swing is a tactic for a core skill that costs 55 AP, and is a 25 ft Wounds debuff that lasts 20 seconds.
Crimson Death is a mastery ability that requires only Hate and has 40 ft range.

Cant see how are they matched apart +10 crit on target.

**Comment by Tesq** [comment]
is a tooltip issue, was changed back then when there wasn't client controll.
