### ISSUE TITLE
My click doesn't work when I'm in a scenario

### ISSUE THREAD

**Issue by mauxy42** [WarEmu/WarBugs#17716]
**Expected behavior and actual behavior:** I should be able to click on allies, ennemies, abilities or spell but it doesn't work. I can't leave the scenario. The only way I found is by leaving the game.

**Steps to reproduce the problem:**
Just join a scenario

**Testing Screenshots/Videos/Evidences (always needed):**

![Warhammer-Age-of-Reckoning-Versi (1)](https://user-images.githubusercontent.com/70358712/92269627-8e776480-eeb2-11ea-8cf8-19fae55d4e58.gif)
Note: The menu open  because I pressed escape
Note 2 : I'm clicking during the whole time

**Comment by Kaelang** [comment]
Please use the forums for tech support.
