### ISSUE TITLE
cant que ranked on my tank

### ISSUE THREAD

**Issue by barfyman92** [WarEmu/WarBugs#17718]
**Expected behavior and actual behavior:**

i try to que for all, ranked solo is not included in the que. i que exclusivly for ranked solo, nothing happens

**Steps to reproduce the problem:**

no idea unique to one character

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by pkfsa** [comment]
are you missing the tok unlock?

**Comment by barfyman92** [comment]
ill check that out thanks a lot for the tip, never occured to me because my gear is at a high level

**Comment by dalen** [comment]
You should get a message explaining it in chat.

Perhaps you have error messages filtered away.
