### ISSUE TITLE
Dyes Resetted

### ISSUE THREAD

**Issue by Haojun-Phalanx** [WarEmu/WarBugs#17724]
Couple days ago, i changed my colors on sorc. When i log in back today, it was all reseted. 

Before: 
![Haojun_020](https://user-images.githubusercontent.com/23129933/92302423-cfd04880-ef74-11ea-9960-7c76cc943d5a.jpg)

After:
![Haojun_021](https://user-images.githubusercontent.com/23129933/92302425-d65ec000-ef74-11ea-9146-c5711868b0cb.jpg)

**Comment by Kaelang** [comment]
No information.
