### ISSUE TITLE
Marauder:Touch of Rot procs evertime your enemy hit somebody

### ISSUE THREAD

**Issue by Xarox** [WarEmu/WarBugs#1772]
![unbenann1t](https://cloud.githubusercontent.com/assets/15455110/10853603/37176e3c-7f37-11e5-923a-f598116195b2.jpg)

i think it only should proc for use a meele ability...

here a screenshot from a slayer using aoe:

![unbenannt](https://cloud.githubusercontent.com/assets/15455110/10853393/148f4a2a-7f36-11e5-88a7-8ec6167fa17c.jpg)

**Comment by Evildoor** [comment]
Correct. Same should be done to other similar abilities (Burn Armor, Vehement Blades, Touch of Instability, etc), if not done already. #1199 is related.

**Comment by Xarox** [comment]
Touch of Instability work like it should for me
