### ISSUE TITLE
Shaman +crit tactics

### ISSUE THREAD

**Issue by Garrthax** [WarEmu/WarBugs#17720]
Mork is watchin tactic (+10% magic crit) doesnt work at all, it adds nothing in getstats and same by tests.

![image](https://user-images.githubusercontent.com/49390790/92280420-a45c4800-eef9-11ea-800e-5844f50cd574.png)

In other hand Extra special mushrooms tactic (+10% healing crit) once equipped provides bonus even when unequipped.

![image](https://user-images.githubusercontent.com/49390790/92280566-eeddc480-eef9-11ea-8822-19c58a2241fc.png)
![image](https://user-images.githubusercontent.com/49390790/92280583-f8672c80-eef9-11ea-9c91-7788c5dadb24.png)

**Comment by pkfsa** [comment]
can confirm happens to my shaman too

**Comment by Garrthax** [comment]
Mork is watchin (+10% magic crit) works now after restart, Extra special mushrooms still same

![image](https://user-images.githubusercontent.com/49390790/92310373-f199f180-efad-11ea-9486-c024616c39ef.png)

**Comment by pkfsa** [comment]
mork is watchin doesnt show any magic crit on my .getstats

**Comment by Povel** [comment]
Tactic is broken and does nothing - Needs fixing.

Confirmed on my shaman aswell.

**Comment by Garrthax** [comment]
> mork is watchin doesnt show any magic crit on my .getstats

works for me now
![image](https://user-images.githubusercontent.com/49390790/92475413-a5cd8f00-f1dd-11ea-9513-fda0f93f11dc.png)
