### ISSUE TITLE
Issue with quest: Grip of Darkness

### ISSUE THREAD

**Issue by DarkFaenix** [WarEmu/WarBugs#17726]
Hi,

On my zealot 40/38, I don't know how, but I got the quest "grip of darkness", which seems to be an Order quest!

**Expected behavior and actual behavior:**
Should only be for Order, right?

**Steps to reproduce the problem:**
I don't know, simply playing the game! :)

**Testing Screenshots/Videos/Evidences (always needed):**

Here's a snippet of CW map with the quest and its marker:
![image](https://user-images.githubusercontent.com/70721662/92307362-dc987080-ef63-11ea-948b-a9b1d40e505f.png)

And the full client window with the quest description open:
![image](https://user-images.githubusercontent.com/70721662/92307716-56315e00-ef66-11ea-8e1e-b54bab3c6c86.png)

And another one showing Hewitt, who doesn't look friendly/chatty at all:
![image](https://user-images.githubusercontent.com/70721662/92307698-313ceb00-ef66-11ea-9263-84296e94a190.png)

Thanks and regards,
DarkFaenix

**Comment by DarkFaenix** [comment]
Hmm, looks like it was legit and that I only had to kill him... Sorry guys!

**Comment by DarkFaenix** [comment]
I spoke too quickly! The quest progressed a bit, but it gets stuck there:
![image](https://user-images.githubusercontent.com/70721662/92308064-fee0bd00-ef68-11ea-843b-3cad2da40f42.png)

Hewitt respawned in the same state as in my previous screenshots.

**Comment by Lheana** [comment]
It is an order quest that starts from a GO. Destro is not meant to be able to complete it.

**Comment by DarkFaenix** [comment]
Thanks @Lheana! Just reported it, in case there's an easy fix to prevent a destro to get it in the future.

**Comment by Lheana** [comment]
I will see if we can do something like that to prevent confusion.
