### ISSUE TITLE
[Quest - Digger's Duds] (Order - Dwarven start area)

### ISSUE THREAD

**Issue by McConn75** [WarEmu/WarBugs#1773]
Hello

it is right now not possible to get a trophy from the lower row. The quest won't be considered completed while choosing them, only the upper row works.
Dwarf who wanted to choose the anvil instead of the red tape... ^^

Regards
Connarius

![grimnirson](https://cloud.githubusercontent.com/assets/10255765/10855509/51a7bdf0-7f42-11e5-82aa-3ec36d498c61.JPG)

**Comment by Evildoor** [comment]
#1704
