### ISSUE TITLE
Chapt 7 Dwarf (Barak Var) PQ objectives are Faction- Reversed

### ISSUE THREAD

**Issue by Lnternsmite** [WarEmu/WarBugs#17730]
Am I to kill my own KIN???!!!!...preposterous!!!
![Storik_025](https://user-images.githubusercontent.com/53047875/92331029-83067380-f041-11ea-9e52-113170b8e037.jpg)

**Comment by Lnternsmite** [comment]
Why did you close this? The objectives are reversed im getting destro objectives cant see order progress

**Comment by Lheana** [comment]
Because this is already reported here #17313
