### ISSUE TITLE
Create dyes is blocked

### ISSUE THREAD

**Issue by esariobug** [WarEmu/WarBugs#17731]
hi,
from game invite 
When i was making dyes, something went wrong. I created 20 dyes by clicking very quicly, after that i choose another extract, when i created 6 another dyes (quick clicks), i couldn't empty the alum root. The capacity was blocked and the game invite me to explain this. i was obliged to exit the game to continue my items.
![Izzyrd_018](https://user-images.githubusercontent.com/24323596/92335170-eff72900-f094-11ea-95f6-1cde1c65f228.jpg)

**Comment by Kaelang** [comment]
Don't click too fast, can happen.
