### ISSUE TITLE
Cannot validate quest "The Silence of the Dams" (Ranked solo quest)

### ISSUE THREAD

**Issue by Sivine** [WarEmu/WarBugs#17738]
**Expected behavior and actual behavior:**
You should be able to validate the quest to the usual NPC in Altdorf, I cannot

**Steps to reproduce the problem:**
Validate the quest and try to give it to the NPC 
I disconnected between the validation of the quest and my try to validate it, do not know if this can have an influence on the problem

**Testing Screenshots/Videos/Evidences (always needed):**
https://i.imgur.com/CJ3bQ8A.mp4

**Comment by Sivine** [comment]
Quest can ba validated @ the quest giver

**Comment by gittoaster** [comment]
Same thing with me.  What is it 1/6 chance to get the same ranked scenario?  Could be hard to get it again.
thanks

**Comment by Kaelang** [comment]
Not sure why I closed this - reopened.
