### ISSUE TITLE
Problem with craft

### ISSUE THREAD

**Issue by JIopDHekpoH** [WarEmu/WarBugs#17737]
I have bug problem. I cant learn any craft specialisations. Craft masters only have dialog "see you" and i havent button "learn skills" and i havent craft skills in window for crafting skills (v - general - crafting skills)

![9bW76-635bQ](https://user-images.githubusercontent.com/70909435/92409554-d7eddb00-f162-11ea-88be-2c3b6b7d7f5c.jpg)
![YxF4G2O8kNI](https://user-images.githubusercontent.com/70909435/92409563-dde3bc00-f162-11ea-96b0-56a29ef39900.jpg)

**Comment by Kaelang** [comment]
Visit City crafters.
