### ISSUE TITLE
Weapon Sacrifice Not Working (Invader Upgrade)

### ISSUE THREAD

**Issue by Twitchygitt** [WarEmu/WarBugs#17734]
**Expected behavior and actual behavior:**
Exchange Twanga of the Subjagator for Fortress Shoota after meeting necessary criteria.  Renown Rank 66, Twanga unequipped and in bag, at least 60 invader medallions in bag and gold in bag (been told that's required)

**Steps to reproduce the problem:**

Go to Invader Medallion Quartermaster in IC and try to trade in Twanga of the Subjagator for Fortress Shoota
![Shoota](https://user-images.githubusercontent.com/70866674/92338806-b7e5eb00-f080-11ea-9234-700e2339173d.png)

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
120 crests for a 2h.
