### ISSUE TITLE
[Rune priests] shield bug

### ISSUE THREAD

**Issue by Morksezstop** [WarEmu/WarBugs#1774]
I got 2 major issues that occure only while in combat.

Firstly rune shielding \rp's shield\ make check for cone on fire when trying to cast it on friendly target standing at my back

Second bug occure randomly like once on 3-4 non instant spells. When trying to cast heal sometimes the cast stop right away \on 0,1 sec\ and i need to recast the spell. It is very annoying and dont have any connection with different cast disrupt skills. It happen randomly but quite often and kinda ruin my healing

**Comment by Evildoor** [comment]
Second issue is known and reported elsewhere. Also, next time - please, make one report per problem.

**Comment by ozarmidrashim** [comment]
Fixed in next.

**Comment by Morksezstop** [comment]
so about the second issue is there any way to prevent it or should wait for fix?
