### ISSUE TITLE
Bright Wizard Fiery Reserves Tactic

### ISSUE THREAD

**Issue by PingasPowah** [WarEmu/WarBugs#17749]
Bright wizard Fiery Reserves Tactic is completely not working, I've tried taking and putting the tactic on and It Is still giving flame breath a cooldown I also have a GiF of It so you can see.

GiF:
https://gyazo.com/8f5554710fa3dc05465c73f0212cac08

**Comment by emailkook** [comment]
Loos like a similar issue that I just posted for the Power Through Slayer tactic. You have to swap tactic slots and swap back when you zone. Something in last patch messed up some tactics working properly and have to swap bars.

**Comment by Kaelang** [comment]
There's an ongoing issue with tactics resetting.
