### ISSUE TITLE
Unable to unequip or swap items of gear without restarting the game

### ISSUE THREAD

**Issue by detrap** [WarEmu/WarBugs#17746]
Unable to unequip or swap items of gear without exiting and restarting the game

This includes armour, trophies, pocket items and jewelry.

![Screenshot 2020-09-10 01 07 17](https://user-images.githubusercontent.com/64330047/92617428-9dbb3f80-f302-11ea-84c7-4a58504328f1.png)

**Comment by Vayra** [comment]
Were you queued for ranked SCs?

**Comment by Kaelang** [comment]
You can't change gear whilst queued for Ranked.
