### ISSUE TITLE
City Bag

### ISSUE THREAD

**Issue by Gstarhk** [WarEmu/WarBugs#17743]
![Organixx_004](https://user-images.githubusercontent.com/30270344/92602729-d29da700-f2ae-11ea-824b-235d0d667d2d.jpg)
![Organixx_005](https://user-images.githubusercontent.com/30270344/92602743-d6c9c480-f2ae-11ea-8474-024820afce89.jpg)

Hello,
Got a problem,
I got the full invader set but i still have some invader token in my city bag.
Thing is, i do have royal token in the bag zone and in the city phase.

**Comment by Kaelang** [comment]
What is your RR?

**Comment by Gstarhk** [comment]
oh, do we need to be +70 ? I'm 69
