### ISSUE TITLE
Engineer - bug tatics 

### ISSUE THREAD

**Issue by jucawar** [WarEmu/WarBugs#17745]
when you move to another area, the tatics stop working. 

not working the tatics: 
![ENg  tatics not working](https://user-images.githubusercontent.com/64388070/92616181-4e3e2a80-f294-11ea-9c68-9c1030b6100f.png)
so, after logout and login: (it start working again) 
![ENg  tatics working](https://user-images.githubusercontent.com/64388070/92616148-467e8600-f294-11ea-99e9-bc7cc1406b53.png)
I tried  /reload or change the tatics etc.. nothing worked. 
below an example: I was in duel area and move to aldorf. 

![eng  tatics - example](https://user-images.githubusercontent.com/64388070/92616899-28fdec00-f295-11ea-9ea2-90853898bc8c.png)

**Comment by CrimsonFenris** [comment]
See https://github.com/WarEmu/WarBugs/issues/17538

Only fix is to relog (preferably restart the game first), and only workaround atm is to switch to any empty tactic set prior changing/tp to another zone.

Looks like only happening to sub-40 characters, probably an issue with bolster.
