### ISSUE TITLE
supplies are not spawning after patch

### ISSUE THREAD

**Issue by Xruptor** [WarEmu/WarBugs#17747]
I'm relocating a bug that was posted on the forums by zij83.  You can find it here:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=40907&p=436239

"Destro currently has 3/4 BOs in Ellyrion/Shadowlands but supplies are not spawning. I am near the BO and seeing this message in the chat log.

https://imgur.com/a/vGlyimC"

![image](https://user-images.githubusercontent.com/202515/92617676-8a21c180-f28d-11ea-9a53-c506b51ec44f.png)

**Comment by MaxHayman** [comment]
Fixed in hotfix
