### ISSUE TITLE
Tower Camp door cannot be interacted with/opened. "No News..." uncompletable

### ISSUE THREAD

**Issue by ddemarco5** [WarEmu/WarBugs#17742]
Tower is located in West Praag, 61549, 50670

**Expected behavior and actual behavior:**
The quest "No News..." requires you to enter an abandoned tower and kill the NPC Olaf Bloodrunner.
Upon arrival, you can use the "target nearest" hotkey to target Olaf inside, but the door to enter is not intractable and will not open, rendering the quest unable to be completed.

**Steps to reproduce the problem:**
Accept the "No News..." quest, travel to 61549, 50670 in West Praag, and attempt to enter the tower located there.

**Testing Screenshots/Videos/Evidences (always needed):**

![Nicklefingers_000](https://user-images.githubusercontent.com/1832038/92554009-35dcfa00-f219-11ea-8d3f-1b5fd80fab2b.jpg)

**Comment by Lheana** [comment]
Works fine.
![Lheana_226](https://user-images.githubusercontent.com/11537611/92631895-2f5e8900-f2d2-11ea-864d-5286fe5a1a6f.jpg)
