### ISSUE TITLE
Irebough Mossroot Bestial

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#17757]
https://wiki.returnofreckoning.com/index.php/Timber!

Killed Irebough Mossroot but friendly griffons are too close and attacked him too once we pulled.
Couldn't loot so didn't get the Bestial.

**Comment by Lheana** [comment]
What prevents you from killing him again?

**Comment by Razielhell** [comment]
Nothing. Super Long respawn times and need to pull him down the hill. Will try again pulling him downside and see if friendly griffons agro on him.
