### ISSUE TITLE
Empowered Transfer - broken by 9/10 patch

### ISSUE THREAD

**Issue by Testgroupf** [WarEmu/WarBugs#17753]
Subject:  Empowered Transfer (DoK Tactic)

Issue:  Since the most recent patch, the secondary effect is no longer functioning.  Consume Essence no longer hits the extra +2 targets when used.

Resolution:  Please re-enable Empowered Transfer to allow Consume Essence to hit a net total of (3) targets (as described by the tactic's text).

**Comment by dalen** [comment]
this works for me when testing
![image](https://user-images.githubusercontent.com/7400/92696251-e3e7c180-f349-11ea-8f86-3b0d2a5df7bc.png)
