### ISSUE TITLE
Slayer Tactic (Power Through) stops working each time going into Scenario

### ISSUE THREAD

**Issue by emailkook** [WarEmu/WarBugs#17758]
**Expected behavior and actual behavior:**

When you put on Power Through tactic so Exhaustive Blows don't drop you're rage, you're supposed to stay in the red.
Actual Behavior: When I go to scenario, all Exhaustive Blow abilities (ie. Precarious Assault) is dropping my rage back to Green.
Appears another person just posted on Fiery Reserves giving them a cooldown w/ that tactic on, so several tactics must be affected by this bug from last patch and also an Engineer one on the tracker.

**Steps to reproduce the problem:**

My character is level 29, don't know if it affects higher levels yet.
Join a scenario with Power Through tactic on and try to spam Precarious Assault when you're in the yellow/red. It will drop back down to green. When you rotate tactics to a different bar and switch it back, it fixes the problem.

So every scenario/zoning, I have to switch the tactic bar and switch back for Power Through to work. Possible might be affecting other Slayer tactics as well

**Testing Screenshots/Videos/Evidences (always needed):**
https://www.youtube.com/watch?v=jQqXjLrfFmE

I have a video that shows this happening but this the description is self explanatory. I'll edit to add if it's required.

**Comment by emailkook** [comment]
It appears to be random, so I just have to swap tactics every scenario to make sure it works.

**Comment by Kaelang** [comment]
There's an ongoing issue with tactics resetting.
