### ISSUE TITLE
AoE on lord stays Endlessly and killed the whole fortress

### ISSUE THREAD

**Issue by Hardy4win** [WarEmu/WarBugs#17756]
**Expected behavior and actual behavior:** 
AoE dmg around lord shouldnt stay endlessly and kill everyone even through other floors

**Steps to reproduce the problem:**
hard to tell couldnt see in the log what caused it, the lord attacked someone and resetted after that he stood in the room not attack at all but causing in the whole fortress AoE dmg 

**Testing Screenshots/Videos/Evidences (always needed):**

https://clips.twitch.tv/HotArborealLettuceRalpherZ

**Comment by Rydiak** [comment]
Looks like someone threw a Skaven potion into the room.
