### ISSUE TITLE
"A Call for Aid" Battlefield Orders Not Clickable

### ISSUE THREAD

**Issue by cormeister** [WarEmu/WarBugs#17759]
There is a quest step in the "A Call for Aid" quest in High Elf Chapter 7 that asks you to read the Battlefield orders. I located the orders just inside the north entrance of the camp, but when I clicked them, it didn't registered that I had done that and that quest step did not complete. 

**Steps to reproduce the problem:**
Walk up to orders, click them, nothing happens. 

**Testing Screenshots/Videos/Evidences (always needed):**

![2020-09-10 13_12_35-Warhammer_ Age of Reckoning, Version 1 4 8, Copyright 2001-2012 Electronic Arts,](https://user-images.githubusercontent.com/24590251/92799077-5cf61180-f368-11ea-99f9-5cad06098d9a.png)
![2020-09-10 13_11_22-Warhammer_ Age of Reckoning, Version 1 4 8, Copyright 2001-2012 Electronic Arts,](https://user-images.githubusercontent.com/24590251/92799085-5f586b80-f368-11ea-810d-2aae7e4e34fa.png)

**Comment by Lheana** [comment]
Because you need to complete the other steps before.
