### ISSUE TITLE
[shaman] detaunt + shield bugs

### ISSUE THREAD

**Issue by Morksezstop** [WarEmu/WarBugs#1775]
2 minor bugs that are at shamans advance, so yea....

shaman ST detaunt \look over there\ dont check for cone of fire and can be casted with back toward your enemy which wasnt the case on live for sure

shaman shield /dont feel nuthin/ can be casted on everyone no matter if the target is grouped with you or not. At live you could cast it only at grp or wb members. That at my opinion was injustice since the shiled is quite weak and that limitation were totaly unneeded but if we need to be precise that should be the case. Although i dont support such change, the current way is more balanced but whatever

**Comment by Evildoor** [comment]
I agree about shield, that limitation always looked uncalled for.

**Comment by ozarmidrashim** [comment]
Cone of fire fixed. Client shows shield as castable via lit-up icon against members out of party - hence, I won't fix this even if it contradicts the tooltip for QoL reasons.
