### ISSUE TITLE
Parry Tactic not applying 10% white lion char

### ISSUE THREAD

**Issue by checkm8boom** [WarEmu/WarBugs#17768]
Flashing Claws Tactic is not applying 10% parry

Expected is 10% parry Actual is 1point of parry 

steps to reproduce results: 
create a white lion - flashing claws is a tactic under general career

screenshot 1 without tactic in parry @ 34.3 
screenshot with tactic in = parry increased by 1 to 35.3 
1% application 

![whitelion - flashing claws not applying correctly 1](https://user-images.githubusercontent.com/71177875/92995353-c86fe880-f4fa-11ea-85a1-e34ae96d68c0.jpg)
![whitelion - flashing claws not applying correctly 2](https://user-images.githubusercontent.com/71177875/92995354-c9a11580-f4fa-11ea-882f-ecb66ff4203d.jpg)

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by checkm8boom** [comment]
also get stats is showing only 28 parry 

![whitelion - flashing claws not applying correctly 3](https://user-images.githubusercontent.com/71177875/92995532-62846080-f4fc-11ea-81c3-e5eb2b04f6aa.jpg)

**Comment by GK111** [comment]
> also get stats is showing only 28 parry
> 
> ![whitelion - flashing claws not applying correctly 3](https://user-images.githubusercontent.com/71177875/92995532-62846080-f4fc-11ea-81c3-e5eb2b04f6aa.jpg)

18+10

nice try

**Comment by dalen** [comment]
the character sheet displays contribution from weapon skill, .getstats doesn't.
The +10 in 18+10 is from the tactic, it works as it should.

**Comment by checkm8boom** [comment]
putting the +10 aside which still shows even (when i am not using the tactic btw)?? i was not trying to trick anyone i have a genuine issue... if i dont have the tactic slotted i have 343.3 parry if i slot the tactic i have 35.3? how is that applying 10% parry?

**Comment by checkm8boom** [comment]
also i just checked my char the 18 is from the reflexes IV renown I have. the further 10% is from my weapon skill... the tactic is not applying

**Comment by checkm8boom** [comment]
can i please refer you back to screenshot 1 and 2 and have this ticket re-opened i assure you i am being honest we can jump on discord and i will share my screen with you and you can watch me slot the tactic and see the parry go up 1% then i will take it off and it will drop 1%

**Comment by checkm8boom** [comment]
i can do a video and show you my char if you prefer

**Comment by checkm8boom** [comment]
just to confirm its PVP thats the issue - sorry it took so much messing around to confirm so it when being bolstered in pvp it drops the stat when the lion disappears - you then have to remove the tactic and reslot it in pvp for it to re-apply or it messes it up and doesnt reapplu unless you respec renown or reapply tactic in flagged pvp 

![pvp parry applied after tactic reslot 1](https://user-images.githubusercontent.com/71177875/93000595-552d9d00-f521-11ea-8890-7483c77530fb.jpg)


the .getstats dont show the plus 10 when bolster applies 
![pvp no parry tactic](https://user-images.githubusercontent.com/71177875/93000528-fbc56e00-f520-11ea-9558-87b0a409f52f.jpg)
