### ISSUE TITLE
Scenario Turn-in NPCs missing from Reikland and The Maw areas

### ISSUE THREAD

**Issue by Xruptor** [WarEmu/WarBugs#17761]
NPC's to turn in Scenario quests that are completed are missing from the Reikland and The Maw areas when a city is under sieged.  So players have to literally wait the entire time the city is under sieged to turn them in.  Meanwhile they can still be queued up for them and are unable to acquire new quests.

Suggestion, add an NPC to both areas so that new players can turn in their quests while the cities are under sieged.

**Comment by Kaelang** [comment]
This isn't a bug.
