### ISSUE TITLE
[Choppa and Slayer] Reckless Gamble,Hurtin Time

### ISSUE THREAD

**Issue by geezereur** [WarEmu/WarBugs#1776]
Choppas and Slayers abilities Hurtin Time and Reckless Gamble should only damage you once even if you do aoe attacks now for exemple you aoe 3 mobs or players it damage you 3 times instead of one time, It should be  if you do damage to 3 or more mobs or players it Reckless Gamble and Hurtin Time should damage all of them and it should damage you only once.

**Comment by Evildoor** [comment]
#1199
