### ISSUE TITLE
Players drop off from SC top score (thus, not getting Emblem)

### ISSUE THREAD

**Issue by Opeteh** [WarEmu/WarBugs#17765]
![image](https://user-images.githubusercontent.com/69940910/92984487-bebe9480-f4aa-11ea-8c87-6394b538e3f5.png)
He was also top in Protection instead of Dalli

**Comment by dalen** [comment]
if a player leaves the SC or crashes before it ends they are excluded from the medal rewards even if they were top player in a category.
