### ISSUE TITLE
[Broken pull mechanics] Got pulled from the entrance of lord room in Stonewatch outside the inner wall

### ISSUE THREAD

**Issue by Brestir** [WarEmu/WarBugs#17760]
OUT freaking SIDE the inner freaking fortress wall. If it's not a broken pull mechanics and there is no destro bias, give same pull to slayer and fix WL's pull as well. Otherwise just fix that s**t pretty please.

How to reproduce: play as destro during any fortress siege and enjoy the broken pull mechanics that's how (but your petty gamer's soul shall be damned for that for sure).

**Comment by Kaelang** [comment]
Needs more information.
