### ISSUE TITLE
Weapon Sacrifice STILL Not Working (Invader Upgrade)

### ISSUE THREAD

**Issue by Twitchygitt** [WarEmu/WarBugs#17766]
**Expected behavior and actual behavior:**
Last bug report (#17734) on this topic I was told it requires 120 invader medallions.  I have 122 and it's still not working.  I have all the necessary material.  I try to sacrifice my Twanga of the Subjugator to get the Fortress Shoota and ... nothing happens.

**Steps to reproduce the problem:**
Try to trade a Twanga of the Subjugator OR a Stabba of the Subjugator for the Fortress Shoota or Fortress Jabbystick.
![Shoota II](https://user-images.githubusercontent.com/70866674/92992985-9b9ce080-f4bc-11ea-8a46-2756adb5b353.png)

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by dalen** [comment]
do you have the invader tome unlock?

**Comment by Twitchygitt** [comment]
No I do not.  I guess I need full invader armor first to get the weapons.

David M.

**Comment by dalen** [comment]
yes, it says in the description for the item. But for next patch I added an error message in chat if you try to buy it without having the necessary tome unlocks.

**Comment by WaltKey** [comment]
![Skullhead_137](https://user-images.githubusercontent.com/14899765/100243030-1ca53900-2f3e-11eb-91c9-6b2260856dd1.jpg)
![Skullhead_138](https://user-images.githubusercontent.com/14899765/100243083-2f1f7280-2f3e-11eb-8304-0d0479dc2c57.jpg)


Ello! The bug still there ? I can't buy, the window just closes and nothing happens.

**Comment by Lheana** [comment]
What weapon are you trying to buy?

**Comment by WaltKey** [comment]
[Fortress Orcsplitter] ofc
