### ISSUE TITLE
Unable to attack opponents in garden of quaph duels

### ISSUE THREAD

**Issue by dredfury** [WarEmu/WarBugs#17772]
**Expected behavior and actual behavior:**
You are supposed to be able to attack enemies but you are not.

**Steps to reproduce the problem:**
1Teleport to garden of quaph
2Duel a player
3Wait for the duel to start
4Unable to attack a opponent

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Video / Screenshots please.
