### ISSUE TITLE
Apostle's tome of Solemnity

### ISSUE THREAD

**Issue by benitoben20** [WarEmu/WarBugs#17779]
Hi,

The T4 willpower tome that can be acquired with Officier's emblem doesnt work. The description says its supposed to regenerate 8 fury per second, but tried it multiple time and it doesn't regen your fury.

Greetings,

**Comment by Rydiak** [comment]
Unequip and re-equip.

**Comment by benitoben20** [comment]
Did and doesn't work. Even tried log out and log back in.

**Comment by Kaelang** [comment]
They do work, play around with it a few times.
