### ISSUE TITLE
bugusers! our oil at enemy keep!

### ISSUE THREAD

**Issue by BFGka** [WarEmu/WarBugs#17775]
came to attack the castle of the enemy, and one of ours blocked their oil with our oil! please fix this possibility. thank!
![Scolopendro_000](https://user-images.githubusercontent.com/45288988/93089365-a28e4380-f6b4-11ea-984e-ebfcec07e1d4.jpg)

**Comment by Kaelang** [comment]
Probably spawned before flip.
