### ISSUE TITLE
The protective barrier in cities is not protective.

### ISSUE THREAD

**Issue by dredfury** [WarEmu/WarBugs#17777]
**Expected behavior and actual behavior:**

At the end of a stage if a team is losing too badly it gets pushed over the protective barrier. If the team goes near the protective barrier from inside the spawn enemy players can deal damage to the team that's behind the barrier or even pull them with aoe pulls like the one choppas have called Git to de Choppa or the magnet pull from the engineers. Expected behavior should be the protective barrier not allowing dmg to go through or player being pulled to the other side. 

**Steps to reproduce the problem:**
Get close to the protective barrier and cast aoe spells or pulls. Aoe spells only though

**Testing Screenshots/Videos/Evidences (always needed):**
[https://www.youtube.com/watch?v=A0_OLGbfWkY&feature=youtu.be](url)

**Comment by Kaelang** [comment]
Players will die if they kill people in spawns.
