### ISSUE TITLE
The garden of qu'aph is bugged 

### ISSUE THREAD

**Issue by dredfury** [WarEmu/WarBugs#17786]
**Expected behavior and actual behavior:**
Being able to duel our opponents and doing damage to them actual behavior we cant use any spells. 

**Steps to reproduce the problem:**
Duel any player and try to cast spells. 

**Testing Screenshots/Videos/Evidences (always needed):**
[https://www.youtube.com/watch?v=N3HGhW9IPn0&feature=youtu.be](url)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17784
