### ISSUE TITLE
Addon AnywhereTrainer allow to train skills... well, anywhere :)

### ISSUE THREAD

**Issue by lleri** [WarEmu/WarBugs#17785]
Addon AnywhereTrainer allow to train skills... well, anywhere.

**Expected behavior and actual behavior:**
Expected: Only trainers suppose to allow spec your skills. 
Actual: Addon allow you to train your skills trees anywhere. However you can't reset skills with it.

**Steps to reproduce the problem:**
1. Install addon AnywhereTrainer (my version is 1.3).
2. Reset skills on any trainer
3. Go to any place far away enough from trainer and spec necessary skills

**Testing Screenshots/Videos/Evidences (always needed):**
I can't imagine which image I should add, sorry.

**Comment by Rydiak** [comment]
As far as I am aware, AnywhereTrainer will give you the appearance of respeccing, but it doesn't actually change anything on your character.

**Comment by Kaelang** [comment]
They shouldn't spec your skills.

**Comment by lleri** [comment]
> As far as I am aware, AnywhereTrainer will give you the appearance of respeccing, but it doesn't actually change anything on your character.

The problem that it's allows you spec your skill, I spec tactic via it. Can make a video if it's necessary.

**Comment by Kaelang** [comment]
Please

**Comment by lleri** [comment]
Sorry for delay, creating video not my strong side :D Check this, please: https://youtu.be/JWa93dxTF1E

**Comment by Rydiak** [comment]
Video is private.

**Comment by lleri** [comment]
Sorry for delay and first unsuccessful attempt, new link: https://youtu.be/xjtC1rTjye8
