### ISSUE TITLE
[Quest] [Order] Bandit's Bane - can't complete

### ISSUE THREAD

**Issue by len666** [WarEmu/WarBugs#1778]
Hi, couldn't find that one in the bugtracker so I thought I would report it. 
The quest "Bandit's Bane" in Nordland (Empire chapter 3) can't be completed: I completed the requirements, I can see the orange icon over the head of the quest ending mob (Erich Maller), but when I click him then the "Complete" button in the dialog window, it doesn't trigger the status change so I can't get the reward or have the quest marked as done. The button doesn't do anything. 
I abandoned it and did it all over again, same problem.

Thanks!

**Comment by Meralors** [comment]
Fixed on dev, next quest db pull up and you should be able to complete it :)
