### ISSUE TITLE
RVR supplies are not spawning in Avelorn/Saphery (possibly elsewhere)

### ISSUE THREAD

**Issue by 5119ror** [WarEmu/WarBugs#17788]
**Expected behavior and actual behavior:**
Expected behavior: when controlling 2+ BOs for a zero-star keep, supply boxes should spawn
Actual behavior: we are controlling 2 BOs in Avelorn/Saphery, our keep has zero stars, but no boxes are spawning

**Comment by 5119ror** [comment]
Even after the hotfix/restart, supplies are still not spawning in Avelorn/Saphery.

![image](https://user-images.githubusercontent.com/69434505/93365506-b9d94800-f7fe-11ea-8512-ba3198b9934d.png)

**Comment by 5119ror** [comment]
Latest hotfix worked, supplies are spawning now.

**Comment by Kaelang** [comment]
Fixed.
