### ISSUE TITLE
Garden of Qu'aph: Not able to attack dueling opponent

### ISSUE THREAD

**Issue by Caduceus42** [WarEmu/WarBugs#17784]
Hey,

Today I was trying to duel a friend on the opposite faction, but we were unable to attack each other.

Upon entering the ring, the duel seemed to start after a couple of seconds, though only my opponent seemed to get the message that the duel had started, I never did. We were then unable to attack each other, even though spells seemed to indicate that I was casting on a valid target. 

Thanks,

**Comment by MaxHayman** [comment]
Fixed
