### ISSUE TITLE
Melee SWs qing ranked as rdps

### ISSUE THREAD

**Issue by Ridaleth** [WarEmu/WarBugs#17783]
Hello Dear,
Somehow some SWs find a way to abuse the ranked q. They q as it seems to be rdps but the end up touching people in melee range. I had like 4 matches like that when it was double melee vs 1 rdps 1 melee.
Please check this up.
P.S Ban sorcs from ranked.

**Comment by dalen** [comment]
was probably some sort of hybrid spec, where they just switched stance. But can make it a bit stricter I think.
