### ISSUE TITLE
Greenskin Chapter 1 PQ Ugrog's Rage does not have a tracker and never unlocks

### ISSUE THREAD

**Issue by Xruptor** [WarEmu/WarBugs#17782]
There is something wrong as the PQ Ugrog's Rage in Chapter 1.  It does not unlock the progress bar for the chapter on the UI.  This is similar to what happened with a previous bug in the Chaos area.  It could be that the map doesn't completely unlock in the TOK.

Please see previous bug with similar problem.  https://github.com/WarEmu/WarBugs/issues/17695

![Snotzer_000](https://user-images.githubusercontent.com/202515/93150627-b55e4380-f6c7-11ea-8339-4da45005cbc2.jpg)
![Snotzer_001](https://user-images.githubusercontent.com/202515/93150632-b7280700-f6c7-11ea-8ce7-e610f8ceb563.jpg)

**Comment by Lheana** [comment]
It works fine for me. I guess it may be due to your launcher that did not update well.
