### ISSUE TITLE
Vanquisher mdps proc giving wrong weaponskill value

### ISSUE THREAD

**Issue by Noronn** [WarEmu/WarBugs#17796]
**Expected behavior and actual behavior:**
The weaponskill vanquisher proc for melee dps only gives 80 stat points instead of 110. Checked it with .getstats, so this probably is NOT a visual bug like in #17064 reported

**Steps to reproduce the problem:**
Proc the vanquisher proc for melee dps and check values before and after

**Testing Screenshots/Videos/Evidences (always needed):**

![Prinnce_004](https://user-images.githubusercontent.com/29786661/93561960-65140980-f985-11ea-9d9a-3803e51eacdd.jpg)
![Prinnce_005](https://user-images.githubusercontent.com/29786661/93561978-6b09ea80-f985-11ea-9f66-080f8820e6b3.jpg)

**Comment by Kaelang** [comment]
Already listed issue with the proc.
