### ISSUE TITLE
No change to bagroll

### ISSUE THREAD

**Issue by Wyvernmoon** [WarEmu/WarBugs#17793]
Bagroll not increasing after keep events.
Remains same after the following:
Defended Praag
Capped Praag
Defended Caledor

No changes to numbers.

![Image2](https://user-images.githubusercontent.com/41122586/93523954-cc887580-f901-11ea-92ab-3a276d79d2ad.jpg)

**Comment by Kaelang** [comment]
Fixed in hotfix.
