### ISSUE TITLE
Quest Servitude

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#17795]
The quest Servitude (Talabecland, destro) can not be finished. After you have killed the peasants no horror appears and you can't get the Shifting Essence.
![servitudequest](https://user-images.githubusercontent.com/16590792/93536293-f618bf80-f948-11ea-8589-0277e0f8b9c4.jpg)

**Comment by Lheana** [comment]
Keep killing the Hazelhof Peasants.
