### ISSUE TITLE
Bloodlord weapon

### ISSUE THREAD

**Issue by Loupsolitiar** [WarEmu/WarBugs#17800]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**
-step 1: place the blood lord weapon on the character at this time the substats in green are activated

-step 2: place the 2nd blood lord weapon and nothing happens, it's normal because the 2 blood lord weapons do not accumulate

-step 3: withdraw the 2nd blood lord weapon that you previously placed on your character and the green substats disappear completely as if you did not have a blood lord weapon on you while if you still carry one

**Testing Screenshots/Videos/Evidences (always needed):**
https://www.youtube.com/watch?v=5sfTYsH2jzY&feature=youtu.be&ab_channel=Darnakar

**Comment by Kaelang** [comment]
This is already listed.
