### ISSUE TITLE
Turning into a Chicken after Scenario because I'm questing in lower tiers.

### ISSUE THREAD

**Issue by Xruptor** [WarEmu/WarBugs#17803]
There is this annoying bug that I get turned into a chicken sometimes when completing a T2 Scenario and returning to a T1 area.  I'm not in an RvR area so it shouldn't turn me into a chicken unless I enter the RVR area.  I understand that it flags me as RVR because I went into a scenario, but it shouldn't turn me into a chicken unless I ever the RVR lakes.

This occurred because I've gone back to the T1 questing area, just do the quest lines casually (also farm low level gear to level up magic salvage for talis) as I wait for scenario pops.  Yes they are lower leveled quests but it doesn't bother me. I'd rather just complete them and move on to the next tier.  Reading the story as I go.  But it seems I cannot do that properly because the moment I return from a Scenario I get turned into a chicken.

I can't undo the chicken btw.  The only way to remove it is by logging out and back in.

![Gearbolt_029](https://user-images.githubusercontent.com/202515/93668362-ca392f00-fa59-11ea-9126-babdd8a1b1b3.jpg)

**Comment by Xruptor** [comment]
BTW this has been mentioned before but it still happens.

https://github.com/WarEmu/WarBugs/issues/7701

I want to point out it's not all the time this happens, but once in awhile.  I'm no where near the RVR lakes and this will occur.  Just randomly questing in lower tiers that's all.

**Comment by Xruptor** [comment]
Another example, I was doing the CP2 Dwarf PQ  "Durak's Gate" as a lvl 19 Engineer (because I want to scratch it off the TOK).  I got a scenario pop for T2 Reikland.  We lost that one and when I released and went back to the T1 PQ (which was still active), I got turned into a chicken.  Forcing me to have to logout and login again.

![Gearbolt_030](https://user-images.githubusercontent.com/202515/93670075-65d09c80-fa66-11ea-9b72-d3ba9d14259a.jpg)

**Comment by Xruptor** [comment]
Yep this happens on other toons as well.  It seems to be a bug with the detection system after you exit the Scenario and zone into an area.  Instead of checking if you're RVR in a lake it just checks the tier and assumes you are in the wrong place so it makes you a chicken when you flag.

**Comment by Xruptor** [comment]
Another way to reproduce this issue.  Grab a high leveled character beyond T1.  Then make SURE you aren't flagged RVR.  Go to one of the T1 Quest hubs, any of them.  Then logout.  Login again and once you are immediately logged in, type /rvr.   Boom you turn instantly in a chicken and you aren't in a lake or anything.

**Comment by wargrimnir** [comment]
This is not bug. Any time you are in T1 and flagged for RvR you will become a chicken.

**Comment by Xruptor** [comment]
Odd so basically you cannot do scenarios while questing in lower areas.
