### ISSUE TITLE
  Shaman Fury of Da Green deals no critical damage

### ISSUE THREAD

**Issue by Wraxin** [WarEmu/WarBugs#17808]
The Fury of da green ability does not deal critical damage. Tested on magic crit and heal crit. I don't know if it's supposed to work like that.

**Comment by Sixmoons48** [comment]
the damage portion of it never crit, however the heal portion of it used to crit, i checked past few months patch notes and there is no notice of this being changed. was about to open a bug about it. this nerfs shaman's ability to heal when they already struggled to compete with zeal and dok

**Comment by CrimsonFenris** [comment]
If this is a mirror of the AM's Energy of Vaul, damage portion never crit yes (although it's not specified in the tooltip).

If this is going to be fixed, please fix it for the AM too, thanks ;)

**Comment by yuaa2** [comment]
this spell also do not AOE heal if target self, old bug
