### ISSUE TITLE
Enemy Ram hits taking down Enemy Door

### ISSUE THREAD

**Issue by GimmiMoar** [WarEmu/WarBugs#17809]
While in the RvR lakes yesterday, desto had spawned a ram to counter order. The Destro ram was half inside and half outside the keep door. While order were killing the destro ram, (as order were attacking the destro keep), every time order would hit the ram, the damage would count towards the door and would drop the keep door percentage while no order ram or cannons were around(destro killed them all!)

**Comment by Kaelang** [comment]
This is already listed.
