### ISSUE TITLE
Slayer mechanics dont work city defence

### ISSUE THREAD

**Issue by DUSKANGEL** [WarEmu/WarBugs#17802]
Good 18/09/2020 i was in Aldorf on my slayer (city defence stage 2) Our group was trying to kill enemy champion NPC, and i notice that my slayer dont get any rage at all while attacking it. I add a screenshot of the situation.
![Jailed_000](https://user-images.githubusercontent.com/12202629/93660522-8a257c80-fa58-11ea-8b4b-df8e49c21b56.jpg)

**Comment by CrimsonFenris** [comment]
NPC combat doesnt provide morale nor combat building mechanics -basically you are not counted as entering combat from just hitting NPC). From earlier patch this year.

**Comment by Kaelang** [comment]
This is already listed.
