### ISSUE TITLE
The End is Nigh Public Quest

### ISSUE THREAD

**Issue by TaterSalads** [WarEmu/WarBugs#17804]
The End is Nigh Public Quest, in Chapter 19 of Praag the first stage of the quest gets stuck at 12/20 Fearless Fanatics. It is supposed to complete the objective with each subsequent kill of a Fanatic but stayed at 12 no matter how many Fanatics I killed.

**Comment by Lheana** [comment]
I tested it, it worked fine, I could complete the PQ.
