### ISSUE TITLE
Missing caracter Dellano

### ISSUE THREAD

**Issue by Gagaddon** [WarEmu/WarBugs#17819]
![Return_of_Reckoning_-_Armory](https://user-images.githubusercontent.com/52387005/94046080-925a2080-fda6-11ea-8749-ac1d671848b3.jpg)
-->

**Expected behavior and actual behavior:**
 Last night im have internet issues and could not log, all attemps crash back to log screen, after several times i decide to wait till next morning. Today im log again and log off, but notice that may main caracter Dellano was erase , but i didnt delete him , after all hes a sov gear. Hes was also a leader of the guild so dunno if have anything to do it , 

**Steps to reproduce the problem:**

Log in and back  if  a bad connection several times ,

**Comment by Kaelang** [comment]
Open a ticket ingame and see if a GM is able to restore the character if it is indeed lost.
