### ISSUE TITLE
Chaos waste keeps bugged

### ISSUE THREAD

**Issue by TaterSalads** [WarEmu/WarBugs#17815]
We flipped to Chaos Waste from Praag. It shows on the in game interface that destruction owns both keeps. Where as it should have the correct Order and Destruction keeps. 
![Tatersalads_014](https://user-images.githubusercontent.com/71567411/93726461-387a1080-fb84-11ea-9c43-93a9e43b949a.jpg)
![Tatersalads_013](https://user-images.githubusercontent.com/71567411/93726463-3a43d400-fb84-11ea-8ac1-41ff9da0a258.jpg)
![Tatersalads_015](https://user-images.githubusercontent.com/71567411/93726466-3b750100-fb84-11ea-8c74-aa4e57ad8905.jpg)

**Comment by MaxHayman** [comment]
Most likely fixed if not please reopen
