### ISSUE TITLE
Bolster not working in Scenarios

### ISSUE THREAD

**Issue by Ryanfawkez** [WarEmu/WarBugs#1782]
I've heard various reports on the forum that the bolster buff does not apply after the introduction of Highpass Cemetary, apparently lowbies are being one-shot by high levels.

**Comment by Evildoor** [comment]
Just played 2 scs, there was bolster on first (GoE), but not on the second (RF).

**Comment by ozarmidrashim** [comment]
Bolster is hardcoded to be disabled in Tier 3 and 4. Fixing.
