### ISSUE TITLE
Box of Soldier's Medallion not available in IC

### ISSUE THREAD

**Issue by gobo-WarWizKing** [WarEmu/WarBugs#17828]
![Screenshot from 2020-09-24 02-20-48](https://user-images.githubusercontent.com/41939212/94126534-94ef6100-fe0c-11ea-841e-e7af0499d179.png)

**Expected behavior and actual behavior:**
This is for destruction vendors in IC. Most vendors offer a choice of Satchel containing 5 medallions to convert down, or a box of 25. There is no option for a Box of Soldier's Medallion.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
No longer relevant due to Currency rework.
