### ISSUE TITLE
Tactics not working after city invasion.

### ISSUE THREAD

**Issue by Wraxin** [WarEmu/WarBugs#17826]
All tactics stop working after exiting the city invasion. I always have to relog.
Probably a lot of people play without tactics after leaving the city.

**Comment by Rydiak** [comment]
I have encountered this bug twice myself (as have members of my Alliance) but not after every city. Still trying to see if I can pinpoint what is causing it.

**Comment by Kaelang** [comment]
This is already a listed issue.
