### ISSUE TITLE
Sentinel's Conjuring Talisman is not stacking

### ISSUE THREAD

**Issue by tomato6171** [WarEmu/WarBugs#17825]
Due to Patch Note, Sentinel Talisman can be stacking, I have two type Talisman Magic Power and Crit
Magic power talisman can be stacked well, but Magic crit talisman(Conjuring) is not work.
Fix this make us happy :D

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Managirl_024](https://user-images.githubusercontent.com/71809509/94105355-0adae300-fe74-11ea-9917-359938a0d995.jpg)

**Comment by Rockalypse** [comment]
Yup, all 4 crit talismans were missed due to different name format, wait for next wendesday.
