### ISSUE TITLE
No warning anymore before buying City Dungeon's accesory Talisman [Destro Side, need confirmation for Order]

### ISSUE THREAD

**Issue by Sivine** [WarEmu/WarBugs#17838]
**Expected behavior and actual behavior:**
Before buying a talisman you should have a warning that makes you select the soulstone and validate the purchace
I bought a (wrong) talisman directly wihout any warning.

**Steps to reproduce the problem:**
Buy a talisman from the Talisman Merchant with a soulstone
I did buy the heal crit tali, do not know if that's only bugged on this one.

**Testing Screenshots/Videos/Evidences (always needed):**
Sadly, I did not recorded the process and I do not have another soulstone.

**Comment by Kaelang** [comment]
You turn the setting on and off in your own client settings. Please re-open if you're able to record, whilst highlighting your current settings.

**Comment by Sivine** [comment]
Video proof : 
https://imgur.com/2rUy00i
