### ISSUE TITLE
not flagged for pvp in rvr area

### ISSUE THREAD

**Issue by M0rf** [WarEmu/WarBugs#1783]
If you afk in the wc and get unflagged for rvr you can then enter the rvr lake and wont be flagged untill u attack, this even allows you to not be chickened in t1.
Crashing the game while dead in the rvr area allows you to log in unflagged on the spot u died. This could become an issue if say a wb all done this after a failed keep seige. possible if login in the rvr area to auto put you in the closest wc ?

**Comment by Evildoor** [comment]
Second problem is already reported.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
