### ISSUE TITLE
Dying in rvr areas in KV spawns you in pve camps. 

### ISSUE THREAD

**Issue by Zxul** [WarEmu/WarBugs#17833]
**Expected behavior and actual behavior:**

Dying in rvr areas in KV spawns you in pve camps, instead of warcamp/keep. For example, died at Karaz Drengi outer, spawned at ch22 greenskin pve camp.

**Steps to reproduce the problem:**

Die in KV, see where do you spawn.

**Comment by Kaelang** [comment]
This is already a listed wider issue with respawn camps in RvR.
