### ISSUE TITLE
Badland PQ Revoltin' Gobbos (Destro) cannot go to phase II

### ISSUE THREAD

**Issue by Sivine** [WarEmu/WarBugs#17832]
**Expected behavior and actual behavior:**
The phase I is set to kill 125 Moonfang gobbos, the counter goes up to 124, then it stops incrementing but kills somehow still give influence

**Steps to reproduce the problem:**
Try to finish phase I of the PQ

**Testing Screenshots/Videos/Evidences (always needed):**
https://imgur.com/trvoZED

**Comment by Lheana** [comment]
That's because as destro, you are meant to kill Moonfang Headhitta. On the video, you only kill Stickpointa.
