### ISSUE TITLE
Missing Item RR61 Bow after recent patch

### ISSUE THREAD

**Issue by Mexlicious** [WarEmu/WarBugs#17831]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by wiscel** [comment]
I think you have same problem as I have.

https://github.com/WarEmu/WarBugs/issues/17821

**Comment by Mexlicious** [comment]
Yea its a visual bug
