### ISSUE TITLE
[SM] Invader 7 piece bonus: Shield of piety is not working

### ISSUE THREAD

**Issue by shaggy996** [WarEmu/WarBugs#17837]
Grouped with a RP we tested this for about 30 minutes.
With the RP healing him self and watching for any buffs or change in base heal values, I hit level 40 mobs for about 20 minutes with no change to the base heal values and no buff ever appearing. 

The effect is supposed to be a 5% incoming heal increase for group members excluding the SM. This has a 25% chance to trigger when the SM uses an improved  balance or perfect balance attack.

**Comment by detrap** [comment]
Just tested it now, hitting targets and mobs for 10 minutes, no proc on my healer and no increased incoming heals for them also.

**Comment by shaggy996** [comment]
The team got right on this. lol

**Comment by Haojun-Phalanx** [comment]
It's still not working.

**Comment by shaggy996** [comment]
in patch notes 28/5/2021
