### ISSUE TITLE
Morale 1 cooldown doesn't occur

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#17836]
I couldn't reproduce bug though faced it many times.

1. use m2 or m3 right after it become enable. spam morale key at 99%
2. sometimes m1 is not on 1m cooldown.
3. you can use m1 again when other morales on CD.

both had it myself and faced it from enemy.
saw WE started with m2 aoe and used m1 parry when i got m1.
i saw this happen to me few times with using m2, 
but after seeing bug happen with m3 i have to report without screenshot.

i'm using moralecircle addon.
screenshot would be simply m1 is not on CD while other 3 on CD

**Comment by Sivine** [comment]
It happens to me too (rather rarely though).

**Comment by Vancerus** [comment]
Same shortly before you loose M2. Was able to hit M1 right after. Should have a video as well somewhere.

**Comment by Kaelang** [comment]
This is a listed issue however we believe it's lag related.
