### ISSUE TITLE
Cannot form Alliance 

### ISSUE THREAD

**Issue by Squapin** [WarEmu/WarBugs#17848]
**Expected behavior and actual behavior:**

Expected: to make ally type ally name and name of leader into the form ally screen then click form alliance. This send a invite to other guild leader who can then confirm the invite.
Actual: when the invite is send and confirmed the alliance is not created. 
Experimented with relogging and been trying consistently on patch day for the last few patches.

**Steps to reproduce the problem:**
To reproduce need two guild leaders to try and form ally

**Testing Screenshots/Videos/Evidences (always needed):**

![Squapit_006](https://user-images.githubusercontent.com/52298730/94372073-cdd05400-00f2-11eb-998b-93c6491087dd.jpg)
![Squapit_007](https://user-images.githubusercontent.com/52298730/94372074-cf9a1780-00f2-11eb-82c4-1b8c97a29239.jpg)
![Squapit_008](https://user-images.githubusercontent.com/52298730/94372075-d163db00-00f2-11eb-8b0d-5905819255da.jpg)

Will update with screen shots next time I try.

**Comment by Squapin** [comment]
Expected: to make ally type ally name and name of leader into the form ally screen then click form alliance. This send a invite to other guild leader who can then confirm the invite.
Actual: when the invite is send and confirmed the alliance is not created. 
Experimented with relogging and been trying consistently on patch day for the last few patches.

To reproduce need two guild leaders to try and form ally

Will update with screen shots next time I try.

**Comment by Senthoi** [comment]
We had this happen too, someone said a workaround was to keep trying. It worked after 19 attempts.

**Comment by Squapin** [comment]
Thanks will try

**Comment by wiscel** [comment]
Just keep trying, it took us over 25 times before it finally worked.

**Comment by Squapin** [comment]
Worked on the 40th attempt.

**Comment by Kaelang** [comment]
Already listed.
