### ISSUE TITLE
Ranked Solo "The Talabec Dam" Quest Unable to turn in.  

### ISSUE THREAD

**Issue by reelzed** [WarEmu/WarBugs#17840]
**Expected behavior and actual behavior:**
Expected: Turn in quest "The Talabec Damn" 

Actual: NPC (Riccekac Warshard) does not have the option to turn in quest. 

**Steps to reproduce the problem:**

Have ranked solo version of "The Talabec Dam" quest and win a ranked solo game in The Talabec Dam.  Then attempt to turn in the quest to Riccekac Warshard in IC. 

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/70560415/94282652-aec89b00-ff15-11ea-84b0-c048c2a12dc5.png)

![image](https://user-images.githubusercontent.com/70560415/94282749-cc960000-ff15-11ea-90ab-65741a317879.png)

![image](https://user-images.githubusercontent.com/70560415/94282821-e5061a80-ff15-11ea-843c-b58a63d843ff.png)

**Comment by Sivine** [comment]
Same ticket I made
#17738
