### ISSUE TITLE
Dwarf servants (Goldmead)

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#1784]
In Goldmead (Destro 18-19 lvl camp in Ellyrion) Dwarf servants are constantly killed by Dark Elf NPCs, was not like that on live. Wrong NPC faction, i guess.

**Comment by Meralors** [comment]
I fixed 4 of them, couldnt find more so I guess I got all of them. Feel free to let us know if you find more :)
Will be pulled live on next patch, can close issue!
