### ISSUE TITLE
Grim Tidings in Grimwater can not complete

### ISSUE THREAD

**Issue by winimaister** [WarEmu/WarBugs#17845]
I have complete every points from the quest and I need only complete the quest but if I clicked in the PNJ nothing happens. The fail is in the pnj to report the quest finish

**Comment by Lheana** [comment]
Screeenshot please.

**Comment by DurinThornaxe** [comment]
I can confirm clicking on the NPC doesn't end the quest. 
![Untitled5](https://user-images.githubusercontent.com/86794706/142389999-b850ff27-7334-4950-8120-1daf7c2365f7.jpg)
Thank you for your work devs!
Love, Durinsson <3

**Comment by lilimx** [comment]
Hey,

this ticket is already closed. Please open a new one. 
Additional, you can add this ticket as reference on your fresh ticket with  the tag #17845

**Comment by Lheana** [comment]
Read the quest, and you should understand to which NPC exactly you need to turn in the quest. So no need to reopen a ticket, it's not bugged.
