### ISSUE TITLE
Keeper of the way not spawning. DE epic quest

### ISSUE THREAD

**Issue by Freemind0** [WarEmu/WarBugs#17844]
![WAR-64 2020-09-26 14-38-42](https://user-images.githubusercontent.com/56369938/94341243-119a5f00-0008-11eb-8c89-dc002d3508a0.png)

This is where Keeper of the way for Dark elfs epic quest should spawn. 
RoR wiki guide states: "Kill Keeper of the Way at 57.6k/63.4k, he is protecting the Glowing Orb behind the citadel. He will drop item Flameshrine Key. Examine it to complete the quest and turn it in."

I've been here for well over 30 minutes incase he had a long spawn time, but hes not shown up. 
I also checked his old spawn area infront of the keep by the door, not there either. 

I also tried going into the orb, to which i got teleported far up, no one there, another orb took me into a room with the next guy Riannmar. But no Keeper.

**Comment by Freemind0** [comment]
So ima add that, Keeper is now spawning, but Riannmar isnt, who spawned before when Keeper didn't spawn. Feels like their spawns are messing with eachother, or they're just bugging out.

**Comment by Lheana** [comment]
Checked just now, they are both there. It may be a problem when players pull them as one is near a building and the other in a building inside the mountain, so they stay stuck.
