### ISSUE TITLE
- Guild Heraldry Emblem Change bug

### ISSUE THREAD

**Issue by Muurloen** [WarEmu/WarBugs#17857]
**Expected behavior and actual behavior:**

Tried to change the guild emblem and colors. (Apologies I didnt screenshot the before colors and emblem).
The colors of the flag, the border pattern and the pattern colors changed, but the emblem did not.

It did still cost me 100 gold for the change.

![Muurlat_018](https://user-images.githubusercontent.com/50267777/94685855-a0042e80-02ef-11eb-85e6-713521ef3585.jpg)
![Muurlat_020](https://user-images.githubusercontent.com/50267777/94685866-a4304c00-02ef-11eb-8237-2cfb0802272e.jpg)

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
You need a higher level guild for this to take effect, the settings are saved, but not yet shown.
