### ISSUE TITLE
Wrong war report destination Eataine

### ISSUE THREAD

**Issue by Sulorie** [WarEmu/WarBugs#17859]
The war report is supposed to bring you to the closes warcamp. 

If using war report to Ulthorin Siege Camp it brings you to ch20, which is basically at the opposite end of Eataine map. 
The correct destination would be ch22.

**Comment by Kaelang** [comment]
Already listed.

**Comment by Sulorie** [comment]
Hello, "already listed" means what? :) In my simple mind it is "just a change" of teleport coordinates.
