### ISSUE TITLE
Oath Rune of Iron Not Casting on Group Member

### ISSUE THREAD

**Issue by Candy-WH** [WarEmu/WarBugs#1785]
Oath Rune of Iron Not Casting on Group Member/RoR Emulator/Version 1.4.8 build 573

Level 12 Dwarf Runepriest

Oath Rune of Iron isn't casting on group member, but rather the Runepriest.

When casting Oath Rune of Iron on group member, instead of it casting on him, it cast on me (Runepriest).  Unfortunately,  didn't take a screenshot, but will and add it to this report (apologies).

How To Reproduce the Bug:
1.  Log on a Runepriest.
2.  Have the runepriest be in a group and cast Oath Rune of Iron on a group member.
3.  Notice it casts on the Runepriest, not group member the RP targeted.

**Comment by Qrazy** [comment]
Works as it should for me on my level 21 RP. Tested in warband and each member I selected was given the appropriate buff and mine remained the same.

**Comment by Candy-WH** [comment]
I tried it again on group member and now working.  Perhaps the other day when I tried it, it was a lag (I apologize).  Feel free to close the ticket.

**Comment by Evildoor** [comment]
FYI next time - you can close your own tickets.
