### ISSUE TITLE
Players respawning in keep infinitely when they shouldn't be. 

### ISSUE THREAD

**Issue by nnnnNATHANnnnn** [WarEmu/WarBugs#17855]
sorry for unedited video. People are continuously respawning in the keep after inner is tagged, and they shouldn't be. Getting farmed for it as well. https://www.youtube.com/watch?v=YUCibxeEX9g

**Comment by dalen** [comment]
Until the gate is down you respawn in the keep if you die in the inner keep. The Lord is supposed to protect the spawn.

**Comment by dalen** [comment]
![image](https://user-images.githubusercontent.com/7400/94658016-8cae8e80-0302-11eb-898f-695a909084cc.png)
