### ISSUE TITLE
Marauder Hulking Brute Tactic Wrong Skill Increase

### ISSUE THREAD

**Issue by Meltheacin** [WarEmu/WarBugs#17868]
**Expected behavior and actual behavior:**
Hulking Brute should increase Toughness and Initiative by 160 in Monstrosity mode. Currently, its increasing Toughness but not Initiative. However, its increasing my Dodge chance by 6.1%.

**Testing Screenshots:**
![Rananickas_086](https://user-images.githubusercontent.com/72279229/94966169-69cad880-04c2-11eb-97d1-9e3e8e851743.jpg)
![Rananickas_087](https://user-images.githubusercontent.com/72279229/94966171-6a636f00-04c2-11eb-978b-1ebfc869040c.jpg)
![Rananickas_088](https://user-images.githubusercontent.com/72279229/94966173-6afc0580-04c2-11eb-96c2-4c93e076e8cd.jpg)

**Comment by Kaelang** [comment]
Please re-upload using .getstats.
