### ISSUE TITLE
[Shadow Warrior/Tactic] Powerful Draw tactic do not apply to abilities

### ISSUE THREAD

**Issue by XmatXergon** [WarEmu/WarBugs#17863]
**Expected behavior and actual behavior:**
Using tactic Powerful Draw (25% Armor Penetration to Skirmish Abilities) should make difference in damage value on all Skirmish abilities against target with armor, but its not being applied to abilities Broadhead Arrow and Flame Arrow.
Probably issue appeared because BHA and FA were originally Scout abilities, after changes made to SW and moving them to Skirmish abilities, seems like they are not correctly recognized as Skirmish Abilities.

This also probably making issue with Invader set last bonus which is increasing 10% Critical Chance on Skirmish abilities, most likely BHA and FA also not getting that bonus.

**Steps to reproduce the problem:**
Use abilities BHA and FA with Powerful Draw tactic then remove tactic and use them again on same target.

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/37849311/94875830-289cdf00-0456-11eb-99c3-6f15c0bdc068.png)

for comparison how PD works on LA and Barrage:
![image](https://user-images.githubusercontent.com/37849311/94875843-33f00a80-0456-11eb-9b18-ee1fc13835b4.png)

If needed i can make record but pretty sure combat log is self explanatory.

**Comment by XmatXergon** [comment]
Also Eye Shot ability (which previously was in Skirmish Tree now in Scout Tree) is getting affected by PD
![image](https://user-images.githubusercontent.com/37849311/94878821-d3190000-045e-11eb-9f5c-20f6dae3d045.png)

**Comment by XmatXergon** [comment]
Correction, Flame Arrow does Elemental Damage so its properly not working with Powerful Draw tactic.

**Comment by CrimsonFenris** [comment]
Looks like barrage and Shadow Sting also dont got the bonus, accordingly to your first screen.

There is a bug with tactics stopping to work after teleporting from pvp area to another, affecting especially players under rank 40.
Can you double check this, even if you're 40, by switching +stats tactics to see if they apply correctly ?

**Comment by Bejkon** [comment]
This is the issue:

https://github.com/WarEmu/WarBugs/issues/17226

BHA was skirm even before the change. FA isnt physical. SS is also affected.

The problem is that that the tactic doesnt apply to dot damage at all, but does instead give FA pen on the DD part even tho its got nothing to do with armor.

This tactic, along with Guerilla Training has never fully worked as intended since the rework. This might be the reason further tuning of the class/changes has been put on hold, awaiting fixes.
