### ISSUE TITLE
Scenario issue- wont allow respawn

### ISSUE THREAD

**Issue by GimmiMoar** [WarEmu/WarBugs#17865]
While in Battle for Pragg this morning, It would not give us the respawn option, if we died in SC. The respawn symbol wouldnt pop up.

**Comment by Freemind0** [comment]
![WAR-64 2020-10-02 15-31-48](https://user-images.githubusercontent.com/56369938/94930492-c6c88d80-04c6-11eb-8cb2-2073e6bfcfb8.png)

Heres a screenshot from my scenario. 
Zarbix stream, destru in his scenario couldn't either.
Seems to be a WH related issue.

**Comment by GimmiMoar** [comment]
Yep I was in the same SC. 

![respawnissue](https://user-images.githubusercontent.com/69077570/94931574-e98e7e00-0495-11eb-8163-3900d92b074e.jpg)

**Comment by Kaelang** [comment]
Should be sorted now.
