### ISSUE TITLE
AM Balanced Mending tactic no longer working.

### ISSUE THREAD

**Issue by TooGraphic** [WarEmu/WarBugs#1786]
Shows green in ability rework thread but tested in Altdorf/Scenarios and heals for base amount regardless of targeting self or other players.

**Comment by Evildoor** [comment]
Since this was reported already, and then closed - can you post some screens with/without tactic?

**Comment by TooGraphic** [comment]
Sorry I'm an idiot I thought it was referring to healing in general not just the skill "healing energy". Tested with that skill and it works fine.
