### ISSUE TITLE
Purple seed disappeared after game crash

### ISSUE THREAD

**Issue by JackHollowPoint** [WarEmu/WarBugs#17860]
30.09 got purple seed (int+mag crit) in gunbad. 
01.10 seed vanished after game crash during keep siege (was planted and growing)

**Expected behavior and actual behavior:**
It was fixed long ago that seeds should return to inventory in case of crash or relog, especially purple ones.

**Steps to reproduce the problem:**
Probably related to char being dead, with lots of people around.
Tried crashing game manually - seeds(normal) were returned to inventory

**Testing Screenshots/Videos/Evidences (always needed):**
Seed from gunbad
![Ivanushka_004](https://user-images.githubusercontent.com/25168701/94825541-fb790e00-040e-11eb-91fd-b681d0d2ce12.jpg)
Seed vanished (not in inventory either)
![Ivanushka_005](https://user-images.githubusercontent.com/25168701/94827107-b8b83580-0410-11eb-8d9e-8457e852b730.jpg)

**Comment by Kaelang** [comment]
Known issue, unable to replicate - weird system crash issue.
