### ISSUE TITLE
Tome of Knowledge Bragging Rights

### ISSUE THREAD

**Issue by Caduceus42** [WarEmu/WarBugs#17866]
Hello,

The bragging rights from the Tome of Knowledge are currently not working correctly.

When testing with a friend we concluded that only the entry that is last added to the Bragging Rights list is visible to players upon inspection.

Going by what the interface tells the player, it should be possible to make up to 10 different Tome of Knowledg entries visible to other players upon inspection. 

I think bragging rights and the Tome of Knowledge in general is a very nice but often overlooked part of the game and I would love to see it receive some love in the future. 

Thanks in advance,

- Caduceus

**Comment by Lheana** [comment]
Screenshots please.

**Comment by Caduceus42** [comment]
![Bragging Rights](https://user-images.githubusercontent.com/69918329/94988979-912cae80-0571-11eb-9def-b414ea5aabf4.png)

**Picture 1: This is what my Bragging Rights page should ook like.**


![Bragging Rights 2](https://user-images.githubusercontent.com/69918329/94988984-9be74380-0571-11eb-8243-2f74da87d601.png)

**Picture 2: This is what my friend sees upon inspecting me.**


![Bragging Rights 3](https://user-images.githubusercontent.com/69918329/94989000-ab668c80-0571-11eb-9cdb-389be5158972.png)

Picture 3: Perhaps related to this issue, the bragging rights page seems to reset after logging out, and upon logging back in only the entry that was last added is still visible. This last picture was taken of my own bragging rights page immediately after relogging.

**Comment by Lheana** [comment]
Do you know how to set your Bragging Rights?

**Comment by Caduceus42** [comment]
> 
> 
> Do you know how to set your Bragging Rights?

Yes, of course.

That's why my list is filled up in the first picture. 

Unless I am missing something?

**Comment by Lheana** [comment]
It was hard for me to figure out what was issue you were reporting. It is clear now, I will see to test it and confirm the issue.

**Comment by MaxHayman** [comment]
Fixed, will go live next patch

**Comment by Caduceus42** [comment]
You guys do a fantastic job! ^^
