### ISSUE TITLE
slayer

### ISSUE THREAD

**Issue by vithoria** [WarEmu/WarBugs#1787]
when i use rampage, marauders and choppas can still use there m1 parry, and that is not ment to be like that...

**Comment by Evildoor** [comment]
Was like that on live. M1 gives 100 parry, Rampage allows to bypass 100 parry, so they cancel each other and your opponent uses his standard parry value.

**Comment by vithoria** [comment]
when i use rampage  see parry, parry parry parry only while they on m1

**Comment by Evildoor** [comment]
Well, then maybe RoR has different implementation. @ozarmidrashim , can you clarify this point?
Side note - my comment above about live server is based on my (possibly wrong) memories about 1 vs 1 fights on live. However, if we ignore that and try to follow the tooltips then we don't get any "+100" or "-100". Tooltips state "parry all attacks" and "attacks cannot be parried", which is contradictory, and it seems logical to me that Morale ability gets priority over simple one in this case.
