### ISSUE TITLE
Maintance fees are still going on

### ISSUE THREAD

**Issue by shaleen22** [WarEmu/WarBugs#17872]
Hello, I'll attach two screenshots that were made by my brother (he's not with english which is why I do the reporting for him). 
In those screenshots, you'll see in the chat that the maintance fees for Reikwatch(?) is still going on even though the area was already locked/over for the guild "Todesengel". 

![Korbban_007](https://user-images.githubusercontent.com/70099622/94993739-68b5ac00-0593-11eb-82d5-45c0cf979491.jpg)
![Korbban_008](https://user-images.githubusercontent.com/70099622/94993740-6b180600-0593-11eb-9303-6b626889660c.jpg)

**Comment by Grandma-Gary** [comment]
After a zone locks you can use a /command to unclaim a keep in the mean time.

https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=41193

To unclaim a keep please use /guildreleasekeep [keep number]

Keep Ids:

1 Dok Karaz
2 Fangbreaka Swamp
3 Gnol Baraz
4 Thickmuck Pit
5 Karaz Drengi
6 Kazad Dammaz
7 Bloodfist Rock
8 Karak Karag
9 Ironskin Skar
10 Badmoon Hole
11 Mandred's Hold
12 Stonetroll Keep
13 Passwatch Castle
14 Stoneclaw Castle
15 Wilhelm's Fist
16 Morr's Repose
17 Southern Garrison
18 Garrison of Skulls
19 Zimmeron's Hold
20 Charon's Keep
21 Cascades of Thunder
22 Spite's Reach
23 The Well of Qhaysh
24 Ghrond's Sacristy
25 Arbor of Light
26 Pillars of Remembrance
27 Covenant of Flame
28 Drakebreaker's Scourge
29 Hatred's Way
30 Wrath's Resolve
