### ISSUE TITLE
Typo in Swift Strikes SW Ability

### ISSUE THREAD

**Issue by Nelkorith** [WarEmu/WarBugs#17878]
**Expected behavior and actual behavior:**

Text should say "If you are Vengeful, then duration is increased to 5 seconds." but it currently says "If you are Vengeful, then duration is increased to 5 seconds."

**Steps to reproduce the problem:**

Mouse over the ability

**Testing Screenshots/Videos/Evidences (always needed):**

https://user-images.githubusercontent.com/72359797/95026666-d4f1e780-0647-11eb-8f63-5f1ee8b12e18.png

**Comment by Kaelang** [comment]
You typed the same thing twice?
