### ISSUE TITLE
Violent Contest; Quest target Location

### ISSUE THREAD

**Issue by eyecourt** [WarEmu/WarBugs#17874]
For the Quest "Violent Contest", Captain Sveidenheim is no where to be found. Tab-targetting helped me find him but in no way am I able to attack him, beleiving him to be stuck inside one of the buildings in the Public Quest zone "Southern Breach", more specifically, by the building near the three quest targets for "Ascension"

**Comment by Lheana** [comment]
This may happen sometimes when someone pulled the NPC but did not kill him. He is back to his correct location.
