### ISSUE TITLE
Twitch Drops

### ISSUE THREAD

**Issue by Akrites34** [WarEmu/WarBugs#17873]
Hello!
I got this Otherwordly Favour crate from Twtich Drops and I just can't open it to claim my reward. Is there any hidden level requirements? I am level 32.

![Otherwordly Favour](https://user-images.githubusercontent.com/72313478/94996944-762d5f00-05b0-11eb-9609-e8e900ed1baa.png)

**Comment by Kaelang** [comment]
Likely a patcher problem, repair your client.
