### ISSUE TITLE
Mount Carrier

### ISSUE THREAD

**Issue by Meoh87** [WarEmu/WarBugs#17875]
I could not open the Mount Carrier Box on my SH 
Now the Box decayed.
Any chance to get another one?

![SHMC](https://user-images.githubusercontent.com/72341114/95014288-2bf6bd00-0646-11eb-971a-5d40bdaadd6a.PNG)

![MC](https://user-images.githubusercontent.com/72341114/95014210-b25ecf00-0645-11eb-9986-09b91381181a.PNG)

**Comment by Kaelang** [comment]
We don't replace items.
