### ISSUE TITLE
Otherworldly Favour box from twitch event - Unable to open

### ISSUE THREAD

**Issue by Actionpigeon** [WarEmu/WarBugs#17885]
**Expected behavior and actual behavior:**
Expected - I should be able to right click or shift-right click to open the box to obtain the item
Actual - Right clicking or shift-right clicking does nothing

**Steps to reproduce the problem:**
I obtained the drop from ZappyTapp, I claimed to my character "Actionpigeon" then taking from the mailbox and attempting to open was not sucessful.

**Testing Screenshots/Videos/Evidences (always needed):**

![Capture](https://user-images.githubusercontent.com/72375061/95047209-973f9e00-06dd-11eb-8b6a-364f6019da1f.PNG)

**Comment by Actionpigeon** [comment]
The box has since decayed so I can't provide any screenshots in game where I can't interact with the item .

**Comment by cormeister** [comment]
I'm experiencing the same issue, except that the box's tool tip states that control-right clicking should open the box. However, this also does not open the box for me. I've tried restarting the client and that doesn't seem to help either. Here's a screenshot of the box tooltip. Thanks!

![2020-10-05 14_10_06-Warhammer_ Age of Reckoning, Version 1 4 8, Copyright 2001-2012 Electronic Arts,](https://user-images.githubusercontent.com/24590251/95132387-8bbb9980-0714-11eb-90e3-e7550df80eb6.png)
