### ISSUE TITLE
Fort RR/Bag roll

### ISSUE THREAD

**Issue by Vylor** [WarEmu/WarBugs#17881]
Received no bag roll and 0 rr for a successful defense when participating in the defense of Stonewatch on 10/4. I was in the fort and active for most of the defense and only missed a few minutes at the start. The below screenshot is the message I was presented with when the fort finished. I was also teleported outside of the fort. 

![Vylor_036](https://user-images.githubusercontent.com/13787995/95031498-e48b2380-067b-11eb-9036-0b116be53408.jpg)

**Comment by Brestir** [comment]
I got the same issue today during the siege of Stonewatch. I was staying in jail waiting for renown and roll but instead, at the moment when lord's hp had dropped to 0%, I got ported to Altdorf (I am bind to Dorf's rally master) without any tick of renown and no bag's roll results shown.

**Comment by kyraith** [comment]
Seems like too different issues. The first one sounds like an old issue with War Reporting into a fort. The second one is an issue with fort bag rolls not showing for people in the jail when the jail get teleported out at the end.
