### ISSUE TITLE
Fortrees access without reservation

### ISSUE THREAD

**Issue by Gagaddon** [WarEmu/WarBugs#17888]
**Expected behavior and actual behavior:**

Hello , not sure if its a bug or working as intended, but when you try enter fortress without reservation, most of time teleports you back behind in the spam outside . But if you are mounted after sometime triyng to enter eventually it will let you access the fortress for some feets , near the shrubs;trees before teleports you back outside. That happended in shining way fortress , not sure if will happen in the others one.

**Steps to reproduce the problem:**

mount up and try access the fortress without reservation a couple of times.

**Comment by Kaelang** [comment]
Happens from time to time.
