### ISSUE TITLE
Massive renown kill

### ISSUE THREAD

**Issue by robswalker68** [WarEmu/WarBugs#17883]
Hi,

Last night (4/10/2020) my character Tabelrel, delivered the final killing blow on a player.  This gave me a 291,000 renown kill tick.  Order had AAO at the time as well.

I'm not sure of the exact timing but it was about 45-60 minutes before the server crash last night so not sure if that had anything to do with it.  Reported to the online GM (BoneGnasher) at the time so he would have a log showing the near enough timing of the event.

This wasn't a tooltip bug as i went from 80/90% Lvl 75 to 60% Lvl76 from one kill

Thanks

**Comment by Kaelang** [comment]
This was likely a packet issue, can you confirm the renown has stuck?
