### ISSUE TITLE
Pick On Yer Own Size

### ISSUE THREAD

**Issue by tquirl745** [WarEmu/WarBugs#17897]
The Takctic from my squig herder Pick On Yer Own Size is no longer counted. no matter what I set and try.
please restore as soon as possible

![Tquirl_021](https://user-images.githubusercontent.com/69433208/95395928-0f85a980-0900-11eb-88e4-ae30e2e8ee23.jpg)
![Tquirl_020](https://user-images.githubusercontent.com/69433208/95395930-101e4000-0900-11eb-9d69-48dd41aab263.jpg)
![Tquirl_019](https://user-images.githubusercontent.com/69433208/95395931-10b6d680-0900-11eb-990b-b35d4507d43f.jpg)
![Tquirl_018](https://user-images.githubusercontent.com/69433208/95395933-10b6d680-0900-11eb-8c31-ff1fd568cd6b.jpg)

**Comment by cimator** [comment]
![POYOS](https://user-images.githubusercontent.com/17130290/95520819-d406e000-09d0-11eb-86f1-fc735cb09ca2.jpg)

Works perfectly fine for me, make sure to use .getstats for accurate results, statdoll is sometimes bugging. Or maybe your tactics got bugged, happens sometimes, relog fixes it.

**Comment by grunbag** [comment]
Working fine
