### ISSUE TITLE
altdorf basement

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#17896]
I didnt see exactly how I got down there, but I think I fell through the stairs when a choppa pulled me

however it happened it was extremely unfair since I could still "see" the people above me, providing me with virtual-invincibility but still able to use line-of-sight heals
![bug](https://user-images.githubusercontent.com/16922842/95385224-9416fe80-08e5-11eb-81c7-f50c6dd4d29c.png)

**Comment by Kaelang** [comment]
Would need to know where it happened, please re-upload if you can locate.
