### ISSUE TITLE
Brutal assult is always active

### ISSUE THREAD

**Issue by jusva321** [WarEmu/WarBugs#17899]
Brutal assult is active Even when i am not behind my target and will force a autoattack can you make the abillity active only when it can be used 

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

When you are not behind your taget the abillity is aktive an will just make you autoattack can you fix this so it is only aktive when it can be used

**Comment by Kaelang** [comment]
Please can you record a video, and include the skill tooltip.
