### ISSUE TITLE
Cannons one-shotting in T1 Ekrund

### ISSUE THREAD

**Issue by dkoerner85** [WarEmu/WarBugs#17893]
**Expected behavior and actual behavior:**
* cannons doing a reasonable amount of damage

**Steps to reproduce the problem:**
* walk into T1 Ekrund and get hit by a cannon

**Testing Screenshots/Videos/Evidences (always needed):**
This is my combat log:

Mrandre's Organ Gun hits you for 193 damage. (44 mitigated) (166 absorbed)
Mrandre's Organ Gun hits you for 327 damage. (76 mitigated)
Mrandre's Organ Gun hits you for 327 damage. (76 mitigated)
Dotbeforeshot's Spiral-Fletched Arrow hits you for 131 damage. (50 mitigated)
Dotbeforeshot's attack critically hits you for 84 damage. (44 mitigated)
Dotbeforeshot's Takedown hits you for 168 damage. (53 mitigated)
Dotbeforeshot's Centuries of Training hits you for 46 damage. (15 mitigated)
Dotbeforeshot's Spiral-Fletched Arrow hits you for 16 damage. (39 mitigated) (166 absorbed)
Dotbeforeshot's attack hits you for 61 damage. (35 mitigated)
Dotbeforeshot's Spiral-Fletched Arrow hits you for 168 damage. (53 mitigated)
Dotbeforeshot's Centuries of Training hits you for 46 damage. (15 mitigated)
Dotbeforeshot's Spiral-Fletched Arrow critically hits you for 256 damage. (75 mitigated)
**Damenfahrrad's Cannon hits you for 2016 damage. (304 mitigated)**
Dotbeforeshot's Centuries of Training hits you for 37 damage. (24 mitigated)
**Damenfahrrad's Cannon hits you for 2016 damage. (333 mitigated)**
Tristess killed Gotsa in The Gates of Ekrund
Tristess killed Bonkbo in The Gates of Ekrund
**Damenfahrrad's Cannon hits you for 1855 damage. (232 mitigated)**
**Damenfahrrad's Cannon hits you for 1312 damage. (164 mitigated)**
You fall for 550 damage.
Viglundur's Eagle Eye hits you for 233 damage. (72 mitigated)
**Damenfahrrad's Cannon hits you for 2102 damage. (315 mitigated)**

This amount of damage can one-shot my lvl13 zealot, which makes for a rather poor experience.

**Comment by Kaelang** [comment]
Cannons are meant to hit hard, they defend the warcamps.
