### ISSUE TITLE
SW Whirling pin bug

### ISSUE THREAD

**Issue by TaterSalads** [WarEmu/WarBugs#17894]
I havent been able to capture footage of the bug happening but currently when going against a Shadow Warrior and they use Whirling pin, I follow their body and where it flew to and then suddenly they are teleported in a completely different direction then where they went flying.

Will update if I can get footage though I have multiple accounts of this happening with other players.

**Comment by Kaelang** [comment]
Likely packet loss / rubber banding / lag. Please re-upload if you can provide evidence otherwise.
