### ISSUE TITLE
[IB] Cave-In DoT duration doesn't match TT.

### ISSUE THREAD

**Issue by Bejkon** [WarEmu/WarBugs#17898]
Hej,

Expected:

![Cave-In TT](https://user-images.githubusercontent.com/35146895/95400956-49f54380-090c-11eb-8326-c0770b2a25e0.JPG)

Currently however, the DoT duration is 3s.

To reproduce, simply use cave-in while above 25grudge and pay attention.

**Comment by grunbag** [comment]
Need more details than pay attention

**Comment by grunbag** [comment]
fixed with next patch
