### ISSUE TITLE
Typos in the Tome of Knowledge

### ISSUE THREAD

**Issue by Caduceus42** [WarEmu/WarBugs#17891]
Hello,

While playing Return of Reckoning I have noticed a number of typos in the Tome of Knowledge.

To help you keep track of them, perhaps it would be useful to use this thread as a collection point of all typos that are found.

So far I have found these:

- The title 'Nature girl' is spelled with 'girl' being uncapitalized.

- The title 'Canon Fodder' is spelled with one 'n' instead of two. 

- 'The title 'Master Cockatrie Slayer' has misspelled 'Cockatrice'. 

- The title 'Master of revels' is spelled with 'revels' being uncapitalized. In the ToK there also seems to be several spaces infront of the title

![Title Typo](https://user-images.githubusercontent.com/69918329/95165284-f7047a80-07ab-11eb-88ed-656274e1aa4b.png)

Thanks,

Caduceus

**Comment by Caduceus42** [comment]
PS: I wasn't sure whether it was necessary to include a screenshot of every typo, but I can provide this is required.

**Comment by MaxHayman** [comment]
We have fixed the ones highlighted so far and they will go live in a future client patch. Thank you.
