### ISSUE TITLE
Did not receive my twitch drop Aviator Goggles

### ISSUE THREAD

**Issue by deadlinger** [WarEmu/WarBugs#17890]
never got the mail 

![2020-10-06 (1)](https://user-images.githubusercontent.com/72432095/95165031-75145180-07ab-11eb-97dc-c93ed310d16f.png)
![2020-10-06 (2)](https://user-images.githubusercontent.com/72432095/95165217-d89e7f00-07ab-11eb-8626-b64db1d2c28f.png)

**Comment by Kaelang** [comment]
We don't return lost items.
