### ISSUE TITLE
The Phoenix Eye PQ Stage 1 Bug

### ISSUE THREAD

**Issue by Caduceus42** [WarEmu/WarBugs#17892]
Hey,

On the first stage of The Phoenix Eye PQ in Eataine it is possible to click the objective flags multiple times, making it possible to speed through the PQ at a very quick pace. 

I uploaded this video to YT to showcase how the bug works:

https://www.youtube.com/watch?v=dguFrKfQ2I0

Thanks,

- Caduceus

**Comment by Kaelang** [comment]
This is a known issue.
