### ISSUE TITLE
back armor/cape not removing

### ISSUE THREAD

**Issue by roflst** [WarEmu/WarBugs#17900]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

I select to remove my cape/back armor from my character. it does it but AS soon as i zone to a different area it comes back i have asked around and ppl dont understand the bug but its annoying and i would like it fixed plz!! character name Roflstomp choppa

**Comment by Kaelang** [comment]
Need a lot more information, follow the format.
