### ISSUE TITLE
Battlebrew Backpack unavailable in appearance tab.

### ISSUE THREAD

**Issue by beskern** [WarEmu/WarBugs#17903]
Ive searched on here and found an issue tagged as resolved that older event items do not allow for alternate appearance. I have an older battlebrew backpack and when I try to slot it in the back slot for the appearance tab it says that Battlebrew backpack is not available for appearance. Ive tried multiple back pieces to see if it would take but It does not. 

Is this intended or a bug?

**Comment by Kaelang** [comment]
You answered your own question - if it's been resolved and the comment was it's not usable, then it's not usable.

**Comment by beskern** [comment]
> You answered your own question - if it's been resolved and the comment was it's not usable, then it's not usable.

The reply was that it was resolved and then the post was locked. However it appears to not be resolved because mine does not work. My comment was that there is a duplicate issue on here marked as resolved for the problem, it does not state anything else. It is from years ago so I was wondering if maybe something more recently has broken it.
