### ISSUE TITLE
bug when entering sigmars hammer or flying from there

### ISSUE THREAD

**Issue by maceinface** [WarEmu/WarBugs#17901]
![Anagtia_000](https://user-images.githubusercontent.com/72568062/95484712-7b682080-0999-11eb-9257-cc77a3dfa787.jpg)

im getting this message after entering sigmars hammer either from altdorf,using guild scrolls or even after flying from there.
game works perfectly fine and does not seem to affect anything

**Comment by MaxHayman** [comment]
Seems fixed. If this is not the case please reopen.
