### ISSUE TITLE
No Protection Value from cleansing on DOK

### ISSUE THREAD

**Issue by Povel** [WarEmu/WarBugs#17908]
As described in the title; Disciple of Khaines cleanse does not add neither healing OR protection value at all in scenarios, I assume the same probably applies to Warrior Priests cleanse.

Out of testing purposes I intentionaly only ran group cleanse tactic on my DOK with no covenant; in one scenario and I did absolutely nothing but cleanse people, no healing - The only healing that shows in the scenario summary at the end is because Mercenary armor set gives me 60HP every 4 seconds.

Here is the video: https://youtu.be/-yiu-27A1Hw

**Comment by bloodmasked** [comment]
I found a random AM to put his 24 second dot on me in RVR, I cleansed it and received 2302 protection score.

**Comment by lilimx** [comment]
Hey,

this should be fixed with patch 07/04/2021 (https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=44628)
If your the opinion it's still bugged, please open a new ticket
