### ISSUE TITLE
Garden of Qu'aph bug

### ISSUE THREAD

**Issue by TaterSalads** [WarEmu/WarBugs#17904]
Currently while dueling a shaman Fuglymane in the Garden the match would end immediately following my successful cast of Terrible Embrace on him and ending the duel with him forfeiting. I believe what is happening is him being in the air its count him as no longer being in the arena and ending it. Where as it should allow me to grip without forfeit.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. I will add it to a related issue.

**Comment by lilimx** [comment]
dublicate/related to #17172
