### ISSUE TITLE
Auctioneer still will not open up to use.

### ISSUE THREAD

**Issue by josewales** [WarEmu/WarBugs#17913]
I reported this bug last week and was closed without solution.  All my account characters can not open up auctioneer to use.  I can target auctioneer.  No other npc has this issue.  Please fix.  I am running low on pots:P

Cheers.

Char name: Catsup

**Comment by MaxHayman** [comment]
This appears to be working so I assume it is a client issue.

Is your game installed in ``C:\Program Files (x86)\`` ?

If it is please move it to ``C:\Games\``
