### ISSUE TITLE
Gunbad

### ISSUE THREAD

**Issue by Lolleromo** [WarEmu/WarBugs#17916]
Hey!

I have one huge thing about gunbad and thats the boss Wight Lord Solithex Yesterday at around 4am we were killing the Solithex for the last but when we got to the point of 20% and killed the barrier, the boss bugged so it spawned those pillars again and got big again!  It started doing the aoe spell as big and did all the normal rotation stuff as big. Then our dps went kill the barrier again, and thats not something you need to do twice. I dont know what happened but i got 5 other people that can prove it bugged hard. There was one hardcore veteran with us and said he hasnt seen anything like it. So wanted to bring it up. It was late tho i was too stupid not to take screenshot. Hope this text helps out.  Cheers!

**Comment by Kaelang** [comment]
Let me know if it happens again.
