### ISSUE TITLE
White lion pet skills do not update with increase in respective career paths

### ISSUE THREAD

**Issue by Sundowner1** [WarEmu/WarBugs#17911]
Some of the pet skills do not show actual damage/armor debuff which is applied to the enemy, in skill tooltip base (with 0 career point spent or 1st level damage/debuff amounts are disclosed.

**Comment by Kaelang** [comment]
You mean in the chatlog? Tooltip? Figures?

**Comment by Sundowner1** [comment]
Hello, kael, sorry for not providing detailed info/screens with original post. Yes, tooltip is messed. skill actually reduces armor by about 800 points
![121586994_3491816767527879_4984725400162492986_n](https://user-images.githubusercontent.com/72624493/96155822-6bb08500-0f21-11eb-93fb-25072ca31a8f.png)

**Comment by grunbag** [comment]
Fixed already
