### ISSUE TITLE
EXP, INF, and maybe REKNOWN as well gain display bug

### ISSUE THREAD

**Issue by Hauclir** [WarEmu/WarBugs#1791]
This occurs only during when the server lags really bad and lags me out and I re-enter the game. Any 1st mob I kill will say I gain a ridiculous amount of exp and if its a PQ mob a ridiculous amount of inf as well, but I am actually gaining the normal amount it suppose to give.
![hauclir_092](https://cloud.githubusercontent.com/assets/7598530/10895793/edf9d77c-816a-11e5-8119-d8564011826e.jpg)
![hauclir_094](https://cloud.githubusercontent.com/assets/7598530/10895796/efea7442-816a-11e5-9809-7b5083954445.jpg)

**Comment by Morksezstop** [comment]
sometimes when you crash you lose all inf, exp and renown, so every first point of the 3 sources give you full amount that you had before the crash and bring you to the normal level. So nothing to worry about, it is quite strange but it is how it is suppose to be

**Comment by Luth-RoR** [comment]
Should be fixed.
