### ISSUE TITLE
Error message when teleporting through Scaven tunnel

### ISSUE THREAD

**Issue by baroke** [WarEmu/WarBugs#17922]
I got this message multiple times when teleporting through Scaven tunnels, the one from Shadowlands to Ellyrion (as Destro) and some other, i think it was in T2 Orc.
![image](https://user-images.githubusercontent.com/20115114/95667249-ee28f580-0b6b-11eb-9ed2-f9292659cbd3.png)

**Comment by MaxHayman** [comment]
Thank you for the submission

**Comment by Naelar** [comment]
I got the same thing as well.  Is it because the return tunnel is missing?  Because I got a similar message today when using the skaven tunnel on the Destruction side in Kadrin Valley, except the number after 'GO:' was 1353623.
