### ISSUE TITLE
Sacellum Dungeon constant text spam

### ISSUE THREAD

**Issue by Impmon75** [WarEmu/WarBugs#17925]
When I try to run Sacellum Dungeon I get a constant stream of spam in text related to NPC's aggro on group members followed by a series of numbers and coordinates.   Theres no method of turning it off & when I ask group mates they don't have the same issue.

Thanks !

**Comment by Rydiak** [comment]
Turn off channel 9

**Comment by Impmon75** [comment]
Yea people in group said /filter channel 9

I typed that & it still happens.

**Comment by Kaelang** [comment]
Try repairing your client / doing a reinstall.
