### ISSUE TITLE
[IB] snb combat damage too high

### ISSUE THREAD

**Issue by gobo-WarWizKing** [WarEmu/WarBugs#17938]
**Expected behavior and actual behavior:**
This was after T3 empire flipped and I had ~100 AAO, vs a 57 IB, I am rr86. I have 66.3 base armor penetration from WS and +10% from 4pc SovBerserker bonus, three stacks of Slasha! for a 108 Toughness debuff. I hit a tank and I expect to do a little damage, and I expect him to do a little damage back to me. 

I jumped him semi afk at his WC and got him to 50% before he started to fight back. You can see in the combat log his hits were hitting way too hard.

21:13:35 my attack hits for 127 (102 mitigated); after a Bleed Em Out tick my next attack is Sit Down!, so this damage was done while Berserk. Assuming he Challenge! me early on, I easily hit him x3 times to cancel this, yet my damage is continuously this low throughout the fight.
21:13:44 his Binding Grudge hits me 739 (1452 mitigated). I can not be Berserk (-50% armor) as I used Sit Down! at :35 and it takes 15s to go from empty rage to berserk.
21:13:51 he hits me with M1 Demolishing Strike, so I expect to take more damage from here on out.
21:13:55 Heavy Blow hits me for 2506 (1236 mitigated). At rr80+, if he was BIS gear, had all 24 Strength talisman, all rr into strength, had +15% damage tactic and Taunted me I would barely expect this.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Screenshot from 2020-10-13 21-44-52](https://user-images.githubusercontent.com/41939212/95945864-3e889900-0da0-11eb-96f7-d3ff0cac9fd5.png)
![Screenshot from 2020-10-13 21-18-07](https://user-images.githubusercontent.com/41939212/95943653-43971980-0d9b-11eb-94c7-47cdfa7611e6.png)

**Comment by Kaloell** [comment]
He dealt more damage because he was in/ near the order WC. That is an intended mechanic to discourage people from pushing one side back into their WC.

**Comment by Kaelang** [comment]
This ^
