### ISSUE TITLE
Kill Quests

### ISSUE THREAD

**Issue by Tenaciousbufhel** [WarEmu/WarBugs#17934]
Kills are not being registered in the kill quests (open RvR.) Spend many hours in the lakes past 4 days on my newly leveled sham as solo and in the WB. Many zone flips and good fights. I have yet to complete one kill quests from open RvR. The only kills that are adding to the kill quests are those that a tied to the scenarios, oil drops and very occasional in RvR fights. I am getting RR for assisting in kills but they are not counting towards kill quests including death blows. This affects players who prefer to just RvR and not farm to obtain gold for flight masters and players who are trying to get XP from open RvR. 

**Kills should be counted in the kill quests if you or your group mate dealt x amount of damage to a kill :**

**Review changes regarding contribution for kills and see if there is a bug:**

**Testing Screenshots/Videos/Evidences (always needed):**
Added screen shots from kill quests for Praag and DW post multiple zone flips which included multiple fights my group was past of in the last 4 days. 

![image](https://user-images.githubusercontent.com/65429915/95875310-e6ba4580-0d3f-11eb-88d6-5633e0c8fa12.png)
![image](https://user-images.githubusercontent.com/65429915/95875341-ee79ea00-0d3f-11eb-9722-b9b91d98cfc0.png)

**Comment by Kaelang** [comment]
Cleaned up the report.

**Comment by dalen** [comment]
You get credit if you or your group did the most damage to the target. It is not killing blows that count.
