### ISSUE TITLE
Scout Quests only trigger at first time visit

### ISSUE THREAD

**Issue by ChrisRBe** [WarEmu/WarBugs#17936]
**Expected behavior and actual behavior:**
Taking the quest in Black Crag should update when you enter the BO range.
Quest does not update when coming into BO range

**Steps to reproduce the problem:**
- take quest in BC warcamp
- move to Rottenpike Ravine
- Quest should correctly update

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/31167512/95891192-0758be80-0d85-11eb-8cfd-d8152dc71cf6.png)

**Comment by Kabucoror** [comment]
Scout quests currently work only if you never discovred the BO before.

Ticket renamed for prober identification.
