### ISSUE TITLE
Book of Binding ports wrong (sometimes)

### ISSUE THREAD

**Issue by Tobomon** [WarEmu/WarBugs#1793]
sometimes that book ports me to a strange place im MoM. 
![xerreg_007](https://cloud.githubusercontent.com/assets/15638775/10922383/17db10ae-827b-11e5-832c-c0109bc7f8c9.jpg)

and just today another funny thing happend then
after relog i ended up here

![xerreg_008](https://cloud.githubusercontent.com/assets/15638775/10922392/24b74216-827b-11e5-9982-b6c6fe2a02e2.jpg)

then i used the book again and it brought me back to my binding point in ostland

**Comment by Luth-RoR** [comment]
Shouldn't happen anymore.
