### ISSUE TITLE
Weird writing. Sigmar's whispering in my ears ?!

### ISSUE THREAD

**Issue by Mescalbrahul** [WarEmu/WarBugs#17939]
I was walking normally into the Emperor's Palace, and between the two first armor traders. 

Just walking into the palace, you may see it while walking in the main corridor with the traders.

![BUG_LOGVAAR](https://user-images.githubusercontent.com/72875507/96003960-cb673d00-0e08-11eb-8821-2ed98396eb4e.png)

It's not something important, but a little bug that i wanted to report.

**Comment by Kaelang** [comment]
This is likely packet related and can happen from time to time.
