### ISSUE TITLE
Napalm Grenade and Phosphorous Shells problem 

### ISSUE THREAD

**Issue by nailinthehead** [WarEmu/WarBugs#17933]
**Expected behavior and actual behavior:**

All ranged abilities don't launch, when target is out of range. When it comes to Napal and Shells, whenever the chosen area is out of range they go on cooldown as if they have been used.

**Steps to reproduce the problem:**

Drop Napalm or Shells anyplace out of range.

This really breaks the game especially during keeps defence/attack as a slight misestimating the distance causes that you can't apply pressure in the key moment of action.

**Comment by yuaa2** [comment]
aoe slow shaman and AM bugged too

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17920
