### ISSUE TITLE
Daemonic Withering stacks incorrectly

### ISSUE THREAD

**Issue by patrick-petersen** [WarEmu/WarBugs#17935]
**Expected behavior and actual behavior:**

Daemonic Withering should increase the incoming damage from all sources by 15%. Thus an attacker with 40% bonus damage should do 1.4 * 1.15 = 1.61 times the base damage.
What actually happens is that the outgoing damage of the attacker is increased by 15%, this results in 1.4 + 0.15 = 1.55 times the damage.
 
 
**Steps to reproduce the problem:**
1) Summon your magus pet, wait for the +40% damage buff
2) hit anything, with an ability/ autohit record the non crit total damage
3) Use Withered Soul (with the tactic Daemonic Withering) on the same target and attack again, also record that damage.
 
First hit * 1.15 = expected damage
First hit / 1.4 * 1.55 = actual damage
 
 
**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/4784982/95879573-cd80bb80-0d76-11eb-99ca-6cbb8f3aa6ea.png)

357 + 52 = 409 Damage with 40% damage buff
395 + 58 = 453 With 40% and 15%
The 2nd damage number should be about 470.35 .
If it stacks additively the expected damage is: 452.8214286, which is pretty close to what the test shows.

**Comment by dalen** [comment]
This is how all damage multipliers in the game stacks. And it was like this back on live as well.

**Comment by patrick-petersen** [comment]
Does this also apply to -50% damage buffs from KotBS/Zealot/RP and detaunts? Those say they reduce the damage by 50%.
Basically: Is +40% dmg -50% damage intended to do 70% or 90% damage? Or should I create a separate bug report for those?

**Comment by dalen** [comment]
Positive multipliers and negative multipliers stack differently. Two -50% multipliers will give -75%, while two +50% multipliers will give +100%.

**Comment by patrick-petersen** [comment]
Thanks for the answer. I'll keep that in mind when testing other damage multipliers.

**Comment by dalen** [comment]
and damage multipliers don't increase the damage of procs.

also outgoing damage multipliers will increase the toughness mitigation of the target.

That is how it behaved on the live servers AFAIK.
