### ISSUE TITLE
Quests not Completing

### ISSUE THREAD

**Issue by TomoeOnikiriyaku** [WarEmu/WarBugs#17948]
Have been unable to complete Choke Point Detail and Navigating the Maze quests as Rottenpike scout part does not complete even when jumping up and down by flag.

**Comment by Kaelang** [comment]
More information please.

**Comment by TomoeOnikiriyaku** [comment]
I have both quests on my WP Asagiri and when I go near the other 3 BOs in Black Crag they come up on the screen as completed. When I go near the Rottenpike BO area the same thing does not happen and even when I am jumping up and down on the flag it does not complete.

**Comment by TomoeOnikiriyaku** [comment]
Ah, just received the response and hour ago while asleep, have sent more information about the quest and it is closed? I see nothing that shows a response on why it does not complete. Do I need to drop the quests and complete them one at a time, do I need to do one before the other?

**Comment by Kaelang** [comment]
Can you use the format please, I don't know which quests, what objectives, what locations, anything really.

**Comment by TomoeOnikiriyaku** [comment]
On my Character Asagiri, I am trying to do the Quests Choke Point Detail and Scout Rottenpike in Black Crag RvR zone. Both are Battlefield Objectives in that zone. When I approach the other BOs from that series of quests they automatically update. When I approach Rottenpike BO nothing happens with the quests, i.e. they do not update and complete, even when I am ontop of the flags jumping up and down. I have abandoned them and tryed to do each of them singling and still no results. I am unable to complete these two quests because of the BO rottenpike being part of both of them. I am on Order Side.

Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by Lheana** [comment]
As a note, the quest Choke-Point Guard Detail is already reported here #17936
