### ISSUE TITLE
Gunbad Loot Bags missing Liniments and Gold option

### ISSUE THREAD

**Issue by MysticSwords** [WarEmu/WarBugs#17942]
**Expected behavior and actual behavior:**
Expected Behavior: 
- When opening Gold Loot Bags from Gunbad, options for Liniments and Money will display as potential rewards
- When opening Purple Loot Bags from Gunbad, options for Liniments and Money will display as potential rewards
- When opening Blue Loot Bags from Gunbad, options for Liniments and Money will display as potential rewards

**Steps to reproduce the problem:**
- When opening Gold Loot Bags from Gunbad, options for Liniments and Money DO NOT display as potential rewards
- When opening Purple Loot Bags from Gunbad, options for Liniments and Money DO NOT display as potential rewards
- When opening Blue Loot Bags from Gunbad, options for Liniments and Money DO NOT display as potential rewards

Steps to Reproduce:
- Obtain a Gold Bag from Gunbad Loot Rolls
- Loot the Gold Bag from the Treasure Box
- Right Click the Gold Back in inventory
Verify that options for Liniments and Money are absent from potential rewards.

Discussed this with my group members and all 6 of us were showing the same issue. According to some group members, issue was not occurring two days prior when they had run Gunbad on another character.

**Testing Screenshots/Videos/Evidences (always needed):**

![BlueBag](https://user-images.githubusercontent.com/71606761/96076298-03a76380-0e7b-11eb-8d87-b0d8aab57c04.JPG)
![GoldBag](https://user-images.githubusercontent.com/71606761/96076299-03a76380-0e7b-11eb-9e2b-4729679e46b3.JPG)
![PurpleBag](https://user-images.githubusercontent.com/71606761/96076300-03a76380-0e7b-11eb-911b-6fbe40bcee4c.JPG)

**Comment by Hadzi-user** [comment]
I confirm. I have the same.
