### ISSUE TITLE
Hurtin' Time not proccing on AA

### ISSUE THREAD

**Issue by Ysaran** [WarEmu/WarBugs#17945]
**Expected behavior and actual behavior:**
Hurtin' Time state: "while this ability is active, you will deal an additional X damage whenever you strike a target with a melee attack, but you will also suffer Y damage every times this effect occurs. ". Since AA happens only in melee range it is a melee attack and thus Hurtin' TIme should proc on AA as per ability description.

**Steps to reproduce the problem:**
Just activate Hurtin' Time and try to use AA on enemies

**Testing Screenshots/Videos/Evidences (always needed):**
![hurtin time2](https://user-images.githubusercontent.com/47554048/96132655-f16d0a00-0efa-11eb-9d02-4c2fca628a6d.jpg)
![Hurtin time1](https://user-images.githubusercontent.com/47554048/96132661-f29e3700-0efa-11eb-88f9-2562c59330fa.jpg)

**Comment by grunbag** [comment]
It’s correct , attack usually means abilties for mythic .
