### ISSUE TITLE
Auction house window is not opening .

### ISSUE THREAD

**Issue by Enryle** [WarEmu/WarBugs#17940]
Hi ,

nothing happen when I click on Auction House Npc , the window is not showing up.
I tried to run the updater but nothing happen
I tried the fix option in the launcher but nothing happen

**Comment by Kaelang** [comment]
Have you updated / sorted your addons?

**Comment by Enryle** [comment]
addons are updated
I also tried to desactivate them all
I tried a to open AH without any addon an the game basic UI but the window still don't pop up

**Comment by MaxHayman** [comment]
This is caused by the folder permissions. Try moving the game to "C:\Games\Return of Reckoning" and starting and closing the launcher a couple of times.

**Comment by Enryle** [comment]
Thank you it worked  ;)
