### ISSUE TITLE
Magus Weapon 'Spirit of the Djinn'

### ISSUE THREAD

**Issue by Tyrean1** [WarEmu/WarBugs#17958]
Magus Weapon 'Spirit of the Djinn' only gives 800 hp increase (80 wounds) and not 1100 hp (110 wounds) as displayed on the tooltip.

**Expected behavior and actual behavior:**
Expected behaviour: Should increase wounds by 110. Actual behaviour: only increases wounds by 80.

**Steps to reproduce the problem:**
Tested multiple times on receiving damage to gain proc.

**Testing Screenshots/Videos/Evidences (always needed):**
![djinn 1](https://user-images.githubusercontent.com/64007669/96367589-b65f1680-1146-11eb-9d5b-886f8ce085c8.jpg)
![djinn 2](https://user-images.githubusercontent.com/64007669/96367590-b828da00-1146-11eb-94db-51f3dd03399a.jpg)

**Comment by cimator** [comment]
Preservation proc itself is currently bugged on every weapon, https://github.com/WarEmu/WarBugs/issues/14920

**Comment by Kaelang** [comment]
Already listed.
