### ISSUE TITLE
Preserved Heavy Bat Wing

### ISSUE THREAD

**Issue by spelzion** [WarEmu/WarBugs#17953]
**Expected behavior and actual behavior:**
Expected Behavior:  Heavy Preserved Bat Wing Should be able to be used as a main crafting ingredient for force shield potions
Actual Behavior:  Heavy Preserved Bat Wing cannot be inserted into the main ingredient slot of the apothecary screen

**Steps to reproduce the problem:**
Purchase a Heavy Preserved Bat Wing
Attempt to create a potion using Heavy Preserved Bat Wing as the main ingredient

![2020-10-16 (8)](https://user-images.githubusercontent.com/22056270/96300127-49b31300-0fb2-11eb-905c-c0bcf7c0d530.png)
![2020-10-16 (9)](https://user-images.githubusercontent.com/22056270/96300150-52a3e480-0fb2-11eb-9b5d-021787b3dbfe.png)
![2020-10-16 (10)](https://user-images.githubusercontent.com/22056270/96300183-5d5e7980-0fb2-11eb-8d14-54123ef1dc79.png)
![2020-10-16 (11)](https://user-images.githubusercontent.com/22056270/96300209-68b1a500-0fb2-11eb-8704-02b303e8f919.png)
![2020-10-16 (13)](https://user-images.githubusercontent.com/22056270/96300251-76672a80-0fb2-11eb-9c14-d26a195e567d.png)
![2020-10-16 (14)](https://user-images.githubusercontent.com/22056270/96300287-83841980-0fb2-11eb-8442-13bab335f71a.png)

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
What potion should this make?
