### ISSUE TITLE
ranked solo scenario debuff "quitter"

### ISSUE THREAD

**Issue by barfyman92** [WarEmu/WarBugs#17959]
i clicked join with about 17 seconds left, window dissapeared
lagged a few moments, but could see people move around etc so wasnt completely out
sc pop expires
get 10 min quitter debuff
disconnected by server
relog
20 minutes quitter

working as intended ? if so system is flawed. i thought i would get in or a repop when you crash from scenarios. maybe if there wasnt a quitter debuff applied instantly for lagging out the duration of the pop ?

**Comment by Kaelang** [comment]
You said you lagged - likely didn't trigger accepting the queue.
