### ISSUE TITLE
Invisible item in Overflow bag

### ISSUE THREAD

**Issue by wewso** [WarEmu/WarBugs#17951]
After logging in from a long time of inactivity (4 months or so) I noticed that my bags had the overflow item on the bottom. The item / items have no icon and cannot be moved or destroyed in any way (right-clicking / dragging).
This happens on all of my characters and I don't think I had any overflow items before.

There have been similar issues in the past but the problem here is that the item is invisible and cannot the dragged to any slot in the inventory or the banks.

What is even weirder is that the interface has some strange behavior when inspected in the UI debugging tool.
I did several tests to show how the UI responds:

Here is a screenshot of how the interface looks when I first open my bags after logging in. (After every log-in)

![Bug 5](https://user-images.githubusercontent.com/72975483/96252202-43289980-0fba-11eb-97a5-cd2383de224d.png)

After clicking on the list view checkbox on the right, my bags are reverted to normal view, but the item is still invisible.

![Bug 4](https://user-images.githubusercontent.com/72975483/96252717-12952f80-0fbb-11eb-8208-d6b00c7d3835.png)

Hovering the empty slot with the UI tool open gives some weird string about Salvaging which I don't even have on this character

![Bug 1](https://user-images.githubusercontent.com/72975483/96252883-5720cb00-0fbb-11eb-9d2a-517104973d2b.png)

Right-clicking the slot also produces some weird strings:

![Bug 2](https://user-images.githubusercontent.com/72975483/96253102-ac5cdc80-0fbb-11eb-87e2-6e2a2f6424b4.png)

I am currently keeping my bags as empty as possible as the interface hides the bottom roll of my inventory and I cant use any items placed there. 

I can provide more details if someone needs it to fix this bug.

**Comment by Kaelang** [comment]
Looks like an addon / client issue. Repair your client / try running without addons.
