### ISSUE TITLE
Witch Hunters cooldown of 1st skills from mastery trees

### ISSUE THREAD

**Issue by Arh13** [WarEmu/WarBugs#17967]
<!--
When activating Sanctified Oil or Seal of Destruction skills, cooldown (60 sec) of Seal of Destruction or Sanctified Oil (both skills are 1st skill from mastery trees) starts and have the same cooldown.

![image](https://user-images.githubusercontent.com/67049861/96618235-bc572200-1315-11eb-9700-541fa714f6e5.png)

![image](https://user-images.githubusercontent.com/67049861/96618258-c5e08a00-1315-11eb-8fee-6d733d31b666.png)

**Comment by Arh13** [comment]
When activating Seal of Destruction of Sanctified Oil, cooldown from the second one starts and have the same timer (60 sec). It happens all time when activating this skills. 
I cant attach screens because they looks like black flat, may be client bug or something also.

**Comment by stonetradex** [comment]
Unfortunately thats how supposed to be.. You can only use one of those per 1 minute. They share the same cooldown.

**Comment by dalen** [comment]
They are intended to work that way
