### ISSUE TITLE
An unintended glitch

### ISSUE THREAD

**Issue by Ralinnanth** [WarEmu/WarBugs#17961]
So earlier today, I was in Dragon Wake and I happened to crash. So I logged back in and I almost clicked on playing on my order character, but It didn't register to log me in so I clicked character selection taking me to the menu. However when I went to play my dark elf character something odd and interesting happened. It logged me into my order character but I was dread seer, it brought over the animation for the dark elf and well the photo should help with the rest. 
![What!](https://user-images.githubusercontent.com/70601552/96398150-26968800-1199-11eb-8757-33bbbc60ea28.jpg)

**Comment by Kaelang** [comment]
Happens from time to time -- nothing really can be done.
