### ISSUE TITLE
Fort pop more than max

### ISSUE THREAD

**Issue by Orokane** [WarEmu/WarBugs#17968]
**Expected behavior and actual behavior:**
Those entering fort after pop has been maxed out should be placed in queue outside of fort

Currently if joining fort after stage 1 without previously being in fort you will be able to go in without reservation. If you die and release in fort you will be placed outside of fort

**Steps to reproduce the problem:**
1) Wait until fort is in Stage 2/3
2) Enter fort without reservation
3) Die and release to spawn outside of fort

**Testing Screenshots/Videos/Evidences (always needed):**
This has only been tested so for playing as Destro in The Maw. Will test more forts as they come and give updates

**Comment by Kaelang** [comment]
Known issue with how fort contribution checks are working. Will likely be fixed when they're revamped and revisited.
