### ISSUE TITLE
Bloodlord Zealot Set not showing 7 Bonus

### ISSUE THREAD

**Issue by Onigokko0101** [WarEmu/WarBugs#17965]
**Expected behavior and actual behavior:**
When hovering gear for the Zealot Bloodlord set the 7 piece bonus should be shown

**Steps to reproduce the problem:**
Hover any Zealot piece from the Bloodlord Set

**Testing Screenshots/Videos/Evidences (always needed):**
![zblood](https://user-images.githubusercontent.com/69435864/96560479-3387aa00-1273-11eb-9c89-c72f3f8c5e61.png)

**Comment by barfyman92** [comment]
this looks like the same bonus as archmage, then it used to be chance to hit an additional target within 15 ft of your target on any direct dmg ability. 

It's gone on AM gear aswell, so not completely sure. possibly removed because it was deemed too strong ?

**Comment by Onigokko0101** [comment]
> 
> 
> this looks like the same bonus as archmage, then it used to be chance to hit an additional target within 15 ft of your target on any direct dmg ability.
> 
> It's gone on AM gear aswell, so not completely sure. possibly removed because it was deemed too strong ?

It could be, I have no idea what the 7 bonus is supposed to be. Im sure it still exists, this seems mostly like just a tooltip issue.

**Comment by lilimx** [comment]
![unknown](https://user-images.githubusercontent.com/23266079/96883918-35bf5380-1481-11eb-8a2b-9f00e4e1fda2.png)

hey,
this is the 7th piece boni proc.

**Comment by Kaelang** [comment]
There's a few sets where this is missing, it's already listed.
