### ISSUE TITLE
Acid Bomb hitting through keep main gate

### ISSUE THREAD

**Issue by b00nation** [WarEmu/WarBugs#17962]
Engineers ability "Acid Bomb" was able to hit me through the the main gate of the outer defense in caledor keep 

**Expected behavior and actual behavior:**
An "Acid Bomb" should not be able to be applied to people behind a closed gate + walls.

**Steps to reproduce the problem:**
I would try to throw an acid bomb in front of the gate and let someone stand behind it

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/25694121/96410435-3046dc80-11e7-11eb-9533-7b760172d6bf.png)

**Comment by Kaelang** [comment]
Already listed.
