### ISSUE TITLE
Ostland Empire chapter 8 Rally Master Demona Gaertner is bugged

### ISSUE THREAD

**Issue by criznik** [WarEmu/WarBugs#17974]
**Expected behavior and actual behavior:**
Should be able to select influence reward.
Not able to select influence reward.

**Steps to reproduce the problem:**
Complete Empire Ch8 Influence reward and speak to Demona Gaertner

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by criznik** [comment]
![Roenik_000](https://user-images.githubusercontent.com/73318318/96939687-c1de7480-149b-11eb-931c-0ca5a4ce9125.jpg)

**Comment by Lheana** [comment]
Well it works fine for me, so it must be something that is not correctly updated on your side. Restart the launcher, and try the Repair button of the launcher.
![Lheana_227](https://user-images.githubusercontent.com/11537611/97080214-0bdd6c80-15fa-11eb-9811-f09185833424.jpg)

**Comment by criznik** [comment]
Will give it another try.  Thanks.
