### ISSUE TITLE
Character titles bug

### ISSUE THREAD

**Issue by Weltsu79** [WarEmu/WarBugs#17979]
I have a bug that my character titles show only Title #816, or some other number, and that is for all my characters in both Destruction and Order in my account.

I don't know how to reproduce this bug but it happened after latest patch in 23/10/2020.
![Mordrix_001](https://user-images.githubusercontent.com/73388375/97080603-400a5a80-1605-11eb-8da1-741842cde432.jpg)

**Comment by Lheana** [comment]
The issues you are reporting are due to something that has not been correctly updated with your launcher. Restart your launcher or try the Repair button on your launcher. If it does not fix it, use our forum or discord for technical advice.
