### ISSUE TITLE
Security app (Norton) issue

### ISSUE THREAD

**Issue by Oldneko** [WarEmu/WarBugs#17972]
I got crush on Lord at CW and Security app send a message as below.
activity: Data protector blocked suspicious processing by War-64.exe
"Suspicious process attempted to change the attributes of a file protected by data protection"

something wrong with War-64.exe or my app configurations?
![data protection](https://user-images.githubusercontent.com/43213086/96935810-d0f70e00-14ff-11eb-927a-4278ed4d6e06.png)

**Comment by Kaelang** [comment]
This is explained in the installation guide.
