### ISSUE TITLE
Slayer's abilities hit harder than Choppa's ones

### ISSUE THREAD

**Issue by Hornakkan** [WarEmu/WarBugs#17978]
At equivalent Damage Bonus Slayers abilities have more damage than Choppas.

In this case : 
Runzaway's "_Lotsa Choppin_" with **194 dmg bonus** hits for **377 to 435** where Nyin's "_Flurry_" with **192 dmg bonus** hits for **413 to 485**.

![Runzaway_432](https://user-images.githubusercontent.com/65107497/96968711-a6ae4c00-1511-11eb-9762-7a2e07ef1a51.jpg)
![Nyin_105](https://user-images.githubusercontent.com/65107497/96968716-a910a600-1511-11eb-9748-f9425d490742.jpg)

**Comment by Kaelang** [comment]
One for forums.

**Comment by Hornakkan** [comment]
> 
> 
> One for forums.

Why closed where a bug is obviously demonstrated ?

**Comment by Kaelang** [comment]
Classes are not mirrored to the exact figure. They are not the exact same class for both sides. Tooltips are not 100% reflective. If you have evidence to suggest that these abilities did the exact same figure, I will reopen. Otherwise, use the forums for feedback.
