### ISSUE TITLE
Skill tooltips bug

### ISSUE THREAD

**Issue by Weltsu79** [WarEmu/WarBugs#17980]
My tooltips for skills, tactics and morales show only name, AP cost and range, no description at all.

I don't know how to reproduce this bug, but it happened after the latest patch in 23/10/2020.
![Mordrix_002](https://user-images.githubusercontent.com/73388375/97080657-b27b3a80-1605-11eb-86c2-67df05de37d4.jpg)

**Comment by Lheana** [comment]
The issues you are reporting are due to something that has not been correctly updated with your launcher. Restart your launcher or try the Repair button on your launcher. If it does not fix it, use our forum or discord for technical advice.
