### ISSUE TITLE
The Glory of Ulthuan -Ellyrion

### ISSUE THREAD

**Issue by Lnternsmite** [WarEmu/WarBugs#17982]
Hi

 Quest called " The Glory of Ulthuan" has problem in one of the stages.
![Kohrien_005](https://user-images.githubusercontent.com/53047875/97094669-d7cb7100-1624-11eb-92d6-8e3eff9497e1.jpg)

This stage requires recollection of materials for a blessing. The altar does not work, I right click it and nothing happens. I proceeded to right clicking every item separately having the altar targeted. After that didnt work I kept trying at different distances just to have the same result...

**Comment by Lheana** [comment]
Well I ignore what's wrong but that's not the quest as I tested it and it works fine.
![Lheana_228](https://user-images.githubusercontent.com/11537611/97107551-7fe64600-16c8-11eb-8b8f-b567537ebcdb.jpg)

**Comment by Lnternsmite** [comment]
I went back and it worked lol... not sure what was wrong i was right click-ing it before and didnt work. thanks
