### ISSUE TITLE
KotBS Invader Helm visual bug

### ISSUE THREAD

**Issue by Angerblaze-RoR** [WarEmu/WarBugs#17981]
There is a black area around the top of my Invader Casque. Other players also see it in the game so it's not just my client. The bug showed up as soon as I purchased and equipped the helm a couple of days ago. 

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Angerblaze-RoR** [comment]
![Warhammer-Online---Return-Of-Reckoning-Screenshot-2020 10 22---19 38 49](https://user-images.githubusercontent.com/73407486/97094443-2b55b300-1655-11eb-97ad-c007d174c6cc.jpg)

**Comment by cimator** [comment]
do you have any visual items in the pocket slot? For ex, equipping aviator googles on pocket, and enable helmet appearance causes this

**Comment by Angerblaze-RoR** [comment]
Fucking aviator's... Hahahaha, yup, that was it. Thank you for assistance, I will close the ticket now :)

**Comment by Angerblaze-RoR** [comment]
Aviator googles were the cause of this bug, closing the ticket now.
