### ISSUE TITLE
White lion pet buffs do not affect pet DPS

### ISSUE THREAD

**Issue by iantheace** [WarEmu/WarBugs#17988]
**Expected behaviour and actual behaviour:**

Using the self buff 'trained to kill' will add 200dps to the pets abilities as per my stat doll.

Actual behaviour - it does <nothing> for pet DPS.

**Steps to reproduce the problem:**

Attack a dummy with the pet, then use your 'train to kill' pet buff (should add my 700 str from items). Let it attack, then swap back to another buff like 'Trained to threaten' which adds no stats to the pets. The DPS remains the same.

**Testing Screenshots/Videos/Evidences (always needed):**

http://rgupdates.co.uk/ROR/BuffDoesntHelpPet.mp4

**Comment by CrimsonFenris** [comment]
Actually the pet cast a taunt on target with Trained to Threaten, wich increase all its dmg by 30% during 5s (castable every 10s, wo it's +15% average dps).

I dont get your "add 200 dps" with trained to kill : every skill is scaled differently from your offensive stat contribution, and pretty much every stat bonus doesnt add to your pet's damage, like tactics (notable exception being the DoT skills of the pet).

But yes, the added STR from your items should add to Hunt and Kill trainings, and after testing it's not clear about that (I didnt try to remove an item).

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17986
