### ISSUE TITLE
Destruction PQ Objective in Kron Komar Gap 

### ISSUE THREAD

**Issue by Reknarok** [WarEmu/WarBugs#17984]
The Phase 1 objective for Kron Komar Gap is showing Order objectives rather than Destruction. I am a Black Orc.
![kronkomargapqp](https://user-images.githubusercontent.com/39253672/97107269-c795bd80-171a-11eb-85df-bbb3ded1a503.png)

**Comment by Lheana** [comment]
Duplicate of #17313
