### ISSUE TITLE
White lion pet reduces based on range from target

### ISSUE THREAD

**Issue by iantheace** [WarEmu/WarBugs#17989]
**Expected behavior and actual behavior:**

Pet damage is consistent regardless of range. Actual behavior - it isnt.

**Steps to reproduce the problem:**

Have pet attack a dummy, move closer and it does more dmg, move further away and it does less damage, incrementally.

**Testing Screenshots/Videos/Evidences (always needed):**

http://rgupdates.co.uk/ROR/PetDmgReducesAwayFromTarget.mp4

**Comment by cimator** [comment]
Patch notes from 02/10/2020
- The pet damage reduction based on range from owner now only applies to melee pets.

**Comment by iantheace** [comment]
> Patch notes from 02/10/2020
> 
> * The pet damage reduction based on range from owner now only applies to melee pets.

Hmm I wonder if this is part of what is causing all the other bugs. I think there is some kind of issue where the server isn’t tracking the distances properly (you seem to suffer this problem when you are adjacent to your pet half the time). 

You can see in other pics for bugs I reported where coordinated strike (requires you and pet to both be in cc range of target) does 0 dmg.

Seeing as the pet despawns at 150ft or whatever, I’m not really sure what the point in of this mechanic is, and it seems bugged to hell in RVR is main issue so I guess if the range tracking can’t be fixed, remove this mechanic? If the pet is killed you have 15 sec before you can respawn it too, so it’s not like you could kite kill with the pet?

Food for thought.

**Comment by cimator** [comment]
Yeah, pets are really bugging out all the time, positioning wise. This change makes it worse since you cant properly track where your pet actually is. But just saying it was intended, not a bug.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17986
