### ISSUE TITLE
The White lion pet refuses to attack with attack commands.

### ISSUE THREAD

**Issue by iantheace** [WarEmu/WarBugs#17987]
**Expected behavior and actual behavior:**

The white lion pet basically refuses to attack anything, even at point blank range in rvr. It seems to work ok on target dummies. 

This is the same whether you key bind, or press the attack button.

**Steps to reproduce the problem:**

Try to attack someone in RVR with the pet.

**Testing Screenshots/Videos/Evidences (always needed):**

A video is available here

http://rgupdates.co.uk/ROR/PetWontAttack.mp4

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17986
