### ISSUE TITLE
Champion's drop issues - Ellyrion

### ISSUE THREAD

**Issue by Krosmite** [WarEmu/WarBugs#1799]
Hello,
I noticed that the champions named "Bloodscale Knight" don't drop anything, whereas the "Uthorin Assassin" do. Is that possible to make the drop working on them ? Or to change the Bloodscale Knight into Uthorin Assassin so we can take items from them ? 

Location is 5000 - 47000 - Ellyrion

Thanks for everything you're doing.

Krosmite.

**Comment by Krosmite** [comment]
![krosmite_004](https://github-cloud.s3.amazonaws.com/assets%2F15662896%2F10957482%2F0b249020-8365-11e5-8cfd-75a7cf66e5d0.jpg)

**Comment by Krosmite** [comment]
Hello, could you tell me when the issue will be fix please ? (a week, a month..)

Thank you,

Krosmite

**Comment by Meralors** [comment]
They are now droping stuff according to their level range. Will be pulled live with next patch.
