### ISSUE TITLE
rugged not working for me?

### ISSUE THREAD

**Issue by luislui1221** [WarEmu/WarBugs#17997]
i was at 570ish toughness just earlier and found out reduced to 380, seems rugged suddenly not working? or a bug?

this is i use .getstats with no tactic
![2](https://user-images.githubusercontent.com/73587072/97424480-bc75a400-194b-11eb-9bbe-7dfaefec531d.png)

this is only rugged slotted still got the same 380 toughness
![1](https://user-images.githubusercontent.com/73587072/97424471-baabe080-194b-11eb-83d7-4fe5f152ebfc.png)

**Comment by gke96** [comment]
"Rugged" is definetely fine. This is a common bug which causes all tactics to not work, might be related to changing "tactic sets". Happens time to time to my friends who use multiple tactic sets.

**Comment by yuaa2** [comment]
delete all tactics, relog, set them again
