### ISSUE TITLE
Quest Bug: Da Stick's da Fing

### ISSUE THREAD

**Issue by Reknarok** [WarEmu/WarBugs#17994]
**Expected behavior and actual behavior:**
I am unable to loot Goldfist's Sarcophagus during the quest "Da Stick's da Fing" in Ekrund. Blocks progress of the quest.

**Steps to reproduce the problem:**
Literally just do the quest.

**Testing Screenshots/Videos/Evidences (always needed):**

https://drive.google.com/drive/folders/1nGUOGy-kSBua_Iyf9oQRspxwgVQ8qKf7?usp=sharing

**Comment by cwsmitty11** [comment]
I too am having the exact same issue.  I am able to loot Snorrison's bones, but not Goldfist's.

**Comment by Lheana** [comment]
Well it works fine for me.
![Anaehll_212](https://user-images.githubusercontent.com/11537611/97780758-dcdd7280-1b86-11eb-9b1e-c4eac49a5a5d.jpg)
