### ISSUE TITLE
Sov Hammermaster 7 Piece bonus not working on AoE (vulnerability proc) 

### ISSUE THREAD

**Issue by Pharm400** [WarEmu/WarBugs#17993]
The 7 piece RP sov on hit bonus doesn't proc on AoE like rune of battle and rune of might

**It should proc off of Rune of Battle and Rune of Might:**

**Stood next to target dummies spamming rune of battle and rune of might and it didn't proc vulnerability**

![proccing](https://user-images.githubusercontent.com/72531526/97253431-3cbbce00-17c1-11eb-8808-a4436346a7ec.PNG)
The rune of battle/might is proccing my 5% chance on hit agony (sentinel weapon 450 damage proc) but the 10% sov bonus won't prov vulnerability unless I'm using a single target ability.

**Comment by Haojun-Phalanx** [comment]
https://github.com/WarEmu/WarBugs/issues/15891

Only ST abilities able to proc it, it's intended.

**Comment by lilimx** [comment]
Hey,

like Hao wrote it's intended. 
- closed
