### ISSUE TITLE
Slow Boil and Vision of Torment damage

### ISSUE THREAD

**Issue by mayh12** [WarEmu/WarBugs#17992]
Slow boil is currently doing significantly less damage than Vision of Torment. In my tests, with 100 bonus damage on both characters, vision of torment was hitting non-crit for 364 damage, compared to 193 damage for slow boil. I've attached the screenshots below.
![sorc100_Vision](https://user-images.githubusercontent.com/73502673/97234156-5b0ee180-1834-11eb-8438-074960577ff9.JPG)
![bw100_SlowBoil](https://user-images.githubusercontent.com/73502673/97234173-5fd39580-1834-11eb-8366-ebb5881be21b.JPG)

**Comment by yuaa2** [comment]
skill level same? move u mouse above skills and look at skill level

**Comment by BillenkoekHeer** [comment]
I've reported this bug back in February, see issue #15799. 
I am quite suprised this hasn't been fixed yet and the fact that I haven't heard any other BW complain about it considering it's a pretty serious bug due to the fact it deals significant less damage than it should do.

**Comment by emailkook** [comment]
![sorcdmg](https://user-images.githubusercontent.com/50253609/97797889-8ef85700-1be6-11eb-8492-d0cb93ceb5bf.gif)
 Sorc overall is doing more damage. My BW is in BiS gear and I never hit for 5000 with doing solo spec using Boiling Blood. Test Word of Pain and Boiling Blood, WoP hits much harder. Something is broken.

**Comment by mayh12** [comment]
> ![sorcdmg](https://user-images.githubusercontent.com/50253609/97797889-8ef85700-1be6-11eb-8492-d0cb93ceb5bf.gif)
> Sorc overall is doing more damage. My BW is in BiS gear and I never hit for 5000 with doing solo spec using Boiling Blood. Test Word of Pain and Boiling Blood, WoP hits much harder. Something is broken.

This looks like you were near a warcamp, 1011 chillwind crits and 2x nearly 5k crits indicated either high pass cemetery or you were near their warcamp.

**Comment by emailkook** [comment]
Nah, we were actually at our war camp when the scenario ended. I didn't think it should be doing that at your own warcamp.

**Comment by Kaelang** [comment]
Reported earlier.
