### ISSUE TITLE
Flame Breath doing instant damage but Ice Spikes does not

### ISSUE THREAD

**Issue by Pharm400** [WarEmu/WarBugs#18001]
**Expected behavior and actual behavior:**
Flame Breath and Ice Spikes have the same tooltip, but ice spikes does not do damage on cast, but flame breath does

**Steps to reproduce the problem:**
Casted scorched earth then flame breath on target dummies and there is an instant tick of damage. Casted Surging Pain then Ice Spikes and there is a 3 second delay before the first instance of damage. 
![Bug 2](https://user-images.githubusercontent.com/72531526/97507258-a5c25380-1931-11eb-8b52-90d1d03376a1.PNG)
![Sorc bug 2](https://user-images.githubusercontent.com/72531526/97507455-18333380-1932-11eb-9cc4-9db8942afb07.PNG)

**Comment by Haojun-Phalanx** [comment]
They are not mirror abilities; it's like this from the beginning. Original designers made FB like direct hit + dot (originally first tick should be able to proc procs) on the other hand sorc has Ice Spikes ( aoe dot) + Infernal Wave (direct hit).
