### ISSUE TITLE
Witch elf Ruthless Assault ability broken

### ISSUE THREAD

**Issue by Esclade** [WarEmu/WarBugs#18007]
doesnt consume stacks, deals no dmg, full cast duration and  goes on cd  

https://gyazo.com/aa5486df5c2d7e7b83c09951ce8964e2

**Comment by stonetradex** [comment]
![image](https://user-images.githubusercontent.com/72578743/97744275-b60b3780-1ac5-11eb-993b-6bd937e09bcc.png)
Pic from log also

**Comment by stonetradex** [comment]
Did some testing and it seems to be broken when Mark of Morathi and Bleeding edge tactics is sloted. RA Worked without using those 2 tactics. Anyway is pointless to use RA without BE

**Comment by reverieharlequin** [comment]
RA is now working with MoM after the hotfix. Still bugged when Bleeding Edge is slotted.

**Comment by dalen** [comment]
This was fixed
