### ISSUE TITLE
Unequipping 2nd bloodlord weapon disables the other bloodlord weapons bonus

### ISSUE THREAD

**Issue by Kaloell** [WarEmu/WarBugs#18002]
**Expected behavior and actual behavior:**
While having a bloodlord weapon (with the +5% damage bonus equipped) this bonus should count but it does not if you unequip a bloddlord weapon in the other hand.

**Steps to reproduce the problem:**
I had no Bloodlord weapons equipped, ran .getstats and got no damage modifier back.
I equipped Bloodlord BloodWard in my off-hand, and got a damage modifier of 1.05
I then equipped Bloodlord Painblade in my main hand. I still have a damage modifier of 1.05 (as it should be since these bonuses should not stack iirc)
I then unequipped Bloodlord Painblade and got a damage modifier of 0.99999994 (a rounding error or miscalculation probably, from 1).
This leaves me with the Bloodlord BloodWard equipped, without the damage bonus, or the armor reduction btw.

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/29151272/97582291-d9ff4800-19f5-11eb-9c2e-e52cd41ee340.png)
![image](https://user-images.githubusercontent.com/29151272/97582325-e4b9dd00-19f5-11eb-87d7-5fa2a90ad11e.png)
![image](https://user-images.githubusercontent.com/29151272/97582471-1337b800-19f6-11eb-8062-3f277355744c.png)

**Comment by Kaelang** [comment]
Already reported.
