### ISSUE TITLE
Constantly being attacked behind cover from Squig Herder pets. Literally LOS means nothing.

### ISSUE THREAD

**Issue by Twicckk** [WarEmu/WarBugs#18004]
Title. Easily replicated. Super annoying when you have like 4 squig pets on you killing you from behind cover.

Please help.

**Comment by CrimsonFenris** [comment]
Dont bother, pets were, are and will be always buggy going through walls and such. Same for WL pet wich can totally go through obstacles (but not able to hit from afar, yes).

Be glad last patch lowered damage from pet accordingly to it's owner's distance (dmg is much lower when the player is far from its pet).

**Comment by Kaelang** [comment]
This is a legacy and known issue.
