### ISSUE TITLE
Halloween patch:  Big error/bug for Witch Elf ability Ruthless Assault

### ISSUE THREAD

**Issue by mijalwe** [WarEmu/WarBugs#18009]
Since the patch today for the Halloween Event, the ability "Ruthless Assault" for my Witch Elf does not work.  There is an error that comes up when trying to use the ability in the system chat channel:

9399 Ruthless Assault threw an unhandled ArgumentOutOfRangeException from VoidThrowArgumentOutofRange_IndexException().

(See attached picture) (Link to video recording of the bug also included below)

*** I am attaching a link to a video I took of this happening in Inevitable City while attacking practice targets.  It includes audio of me explaining and showing what is happening the best I can. ***  

When ability is activated, the animation still shows, but no damage is done.  Under the combat chat tab, it also does not show the ability doing any damage.  The career resources also do not reset to 0 when using this ability as they should.  

I am very tired right now and cannot explain much more tonight, but am available to answer more questions or to provide clarification tomorrow.  

https://youtu.be/6FFfW_mWzJI

![Warhammer Online - Return Of Reckoning Screenshot 2020 10 31 - 03 20 36 38](https://user-images.githubusercontent.com/63208541/97773899-0d42f380-1b2a-11eb-9d9a-46b376c2bc29.png)

**Comment by dalen** [comment]
This was fixed
