### ISSUE TITLE
Immunity CC Buff Bug 

### ISSUE THREAD

**Issue by Ralinnanth** [WarEmu/WarBugs#18000]
Hey, so for the past 48 hours, while I was in RvR I've noticed that when I have immunity from knock back, knocked down, stunned ect there seems to be an issue. Ive counted that while I have the CC Buff on I am still being knocked backed, knocked down, stunned ect. Plus I am not the only one who's been expierencing this. However, and I am not saying it is a bias issue, when I try to knock back someone on order Ironbreaker, Swordmaster ect. Their immunity seems to be working as intended. I was wondering if this can be fixed. Many thanks.

**Comment by iantheace** [comment]
a billion people have reported this, it needs to be with evidence mate, devs here dont beleive anyone about it.

**Comment by Kaelang** [comment]
This has been reported.
