### ISSUE TITLE
[WL] Coordinated strike Damage issue

### ISSUE THREAD

**Issue by CrimsonFenris** [WarEmu/WarBugs#18006]
**Expected behavior and actual behavior:**
Damage should be consistent and remotely accurate from tooltip.

> Damage from Coordinated strike is correct from our character, **but hits from our pet are only hitting for half (or less) expected damage.**
Damage is oddly superior against a training Construct (about 30% dmg more), but accurate against a training target (see screenshots).
Here are respectively 161 dmg from our pet (instead of 345), and 124. THe pet is near our character (so distance from pet should not affect damage).

**Steps to reproduce the problem:**
Use coordinated strike with your pet near you, striking training target

**Testing Screenshots/Videos/Evidences (always needed):**
![CoordStrike01](https://user-images.githubusercontent.com/40425011/97738859-3b4f1600-1adf-11eb-8e5c-783088d08be5.jpg)
![CoordStrike02](https://user-images.githubusercontent.com/40425011/97738866-3d18d980-1adf-11eb-8bf7-47b4e797e37a.jpg)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/17986
