### ISSUE TITLE
Sovereign bonus : +2 mastery points bugged

### ISSUE THREAD

**Issue by badoglio170389** [WarEmu/WarBugs#18018]
i was switching randomly my helm and noticed that the sover bonus gives me only +1 mastery instead of 2

[https://i.imgur.com/QhLgNZF.png](url)

**Comment by yuaa2** [comment]
you can have more then 15 points in any tree, 15 base + 2 Sovereign = 17 points and this don`t show at mastery window

**Comment by badoglio170389** [comment]
incorrect , if u have spare points on a tree with sovereign bonus they are usually show on the right side (1 mastery point) so u can place it for exemple in the morale 4 , atleast it was like that some days before

**Comment by Kaelang** [comment]
Screenshot helm on and off please. (So I can see the item)

**Comment by yuaa2** [comment]
u cannot spare this points, its automacicaly adds to tree, if u already have 14 points in tree it becomes 16, and in mastery window u see only 15

**Comment by badoglio170389** [comment]
https://i.imgur.com/KX0MeDG.png

https://i.imgur.com/e95aiWB.png
