### ISSUE TITLE
Daemonball Rally

### ISSUE THREAD

**Issue by Insenios** [WarEmu/WarBugs#18014]
Hello I have the problem that I can not enter the new sz error message scenario # 2158
![Dalver_002](https://user-images.githubusercontent.com/73778975/97801293-e83ea580-1c3b-11eb-8f2b-dd888425ae67.jpg)
![Dalver_003](https://user-images.githubusercontent.com/73778975/97801294-e8d73c00-1c3b-11eb-8bc7-49c3c6079bd6.jpg)

**Comment by Kaelang** [comment]
Relog.
