### ISSUE TITLE
Nordland Quest: Doctor Heino, Lena Scherer and Erich Malker

### ISSUE THREAD

**Issue by Drilon01** [WarEmu/WarBugs#1801]
Nordland Quest: Doctor Heino, Lena Scherer and Erich Malker when i press complete! nothing happens so i cant complete them

**Comment by Evildoor** [comment]
Quest names?

**Comment by Drilon01** [comment]
NPC: Doctor Heino Quest: The Doctor's Orders
NPC: Lena Scherer Quest: A Sticky Situation
NPC: Erich Malker Quest: Bandit's Bane

**Comment by Evildoor** [comment]
All 3 of these were reported already.
#305
#1757 
#1778
