### ISSUE TITLE
High Elf Chapter 7 Basic Influence Reward's

### ISSUE THREAD

**Issue by cwsmitty11** [WarEmu/WarBugs#18026]
**Expected behavior and actual behavior:**
Basic influence rewards shown be visible.
The entire row of basic rewards is invisible.
**Steps to reproduce the problem:**
Gain influence to be able to choose basic reward for High elf chapter 7 from Liradean Swiftarm.

**Testing Screenshots/Videos/Evidences (always needed):**

Not able to load screen/video because that happens is game says "taking a screenshot" but doesnt actually take the screen shot.

**Comment by Kaelang** [comment]
Print Screen, paint.

**Comment by Lheana** [comment]
Duplicate of #14553
