### ISSUE TITLE
World Map

### ISSUE THREAD

**Issue by Oldneko** [WarEmu/WarBugs#18025]
world map looks bad.
it looks overlapped realm map one by one in full screen mode.
but it cant take SC as i can see ( SC looks usual maps)
![Nikuq_032](https://user-images.githubusercontent.com/43213086/97818781-ce5a9c80-1ce7-11eb-8b4e-cec258db710c.jpg)

I took screen shot in window mode showm like below
![map](https://user-images.githubusercontent.com/43213086/97818732-7ae84e80-1ce7-11eb-920b-cf916be5b0c2.png)

picture by cellphone shows bellow
![20201102_084949368](https://user-images.githubusercontent.com/43213086/97818957-ec74cc80-1ce8-11eb-8fda-5ac4e6d17c4d.jpg)

Im very sorry not good at English

**Comment by Kaelang** [comment]
Client issue, repair / reinstall.
