### ISSUE TITLE
Bright Wizzard - Rain of Fire - cooldown malfunction

### ISSUE THREAD

**Issue by ranzinus** [WarEmu/WarBugs#18035]
Problem: If you cast rain of fire outside it's range, its cool down function gets activated. 

Solution: instead of getting cool down, it should be cancelled and set back without cool down, as you didn't cast the spell. 

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by cimator** [comment]
#17398 , can confirm the same problem on all ground abilities I tried so far. Does nothing, still goes on cd

**Comment by Lithenir** [comment]
Experienced the same yesterday with Mistress of the Marsh on my AM

**Comment by Haojun-Phalanx** [comment]
it's not only the range; you are able to bug it if you place ground abilities on air/obstacles aswell.

**Comment by Kaelang** [comment]
Already reported.
