### ISSUE TITLE
BAstion Stair DOK Painblade Still Main Hand

### ISSUE THREAD

**Issue by Elizerain** [WarEmu/WarBugs#18039]
Hello, just to notice you, Dok painblade from bastion who were supposed to change since halloween patch still exclusive to main hand. Thank you
![Elizerain_001](https://user-images.githubusercontent.com/64614746/98278029-4ea72900-1f98-11eb-8d1d-8845157bbe79.jpg)

**Comment by Elizerain** [comment]
Last post just closed 7 hours ago

**Comment by wargrimnir** [comment]
This appears to be set to either hand now.
