### ISSUE TITLE
Can't use gems

### ISSUE THREAD

**Issue by Necrarian** [WarEmu/WarBugs#18037]
The gems seem to be bugged. They can't be used in any piece of gear and a few i bought off the auction some time ago are stacked and that prompted me to make a post.

**Comment by Rydiak** [comment]
Talismans have an item level requirement for the gear piece they are being slotted in. Likely you are using talismans that are too high level for the gear piece you are using.

**Comment by Necrarian** [comment]
I imagined that might be the problem but im trying low level talisman on rank lvl 40 and it doesnt work either.

**Comment by Kaelang** [comment]
Screenshots please.

**Comment by Necrarian** [comment]
https://imgur.com/tuhyxWc
https://imgur.com/F8umPJw

The screenshot doesnt show my cursor but the firt one i tried with an inferior talisman of the vitality and the second one with a talisman of the smith.

**Comment by Lheana** [comment]
Please show a screenshot of the talisman you are trying to put.

**Comment by Necrarian** [comment]
![image](https://user-images.githubusercontent.com/43074663/98468880-c9608600-21dc-11eb-9352-32459dba5945.png)

**Comment by Necrarian** [comment]
![image](https://user-images.githubusercontent.com/43074663/98468908-da10fc00-21dc-11eb-9f42-bc64cc093015.png)

**Comment by Lheana** [comment]
I suppose you know how to add talismans to items?

**Comment by Necrarian** [comment]
I was told to just drag them to the icon of the item with a socket.
