### ISSUE TITLE
Unable to release after death in cemetary sc

### ISSUE THREAD

**Issue by Malvaine** [WarEmu/WarBugs#18032]
**After being killed in sc, normally the window to release appears. This time it didn't, I had to wait for end of sc to leave:**

**Happened only once, but another member of our group got no window to accept a ressurection from one of our healers in the same sc**

![Malvajne_013](https://user-images.githubusercontent.com/57098865/98040767-23e69480-1e21-11eb-8291-7eb8f269faa4.jpg)

**Comment by Kaelang** [comment]
This is typically fixed with a reload.
