### ISSUE TITLE
Magus "Resummon" ability triggers a global error that it "Requires 35 Righteous Fury"

### ISSUE THREAD

**Issue by witc0m** [WarEmu/WarBugs#18038]
**Expected behavior and actual behavior:**
Pretty straightforward. Triggers the wrong error message when you're unable to use Resummon for whatever reason (it's grayed out). 
![Wumbology_000](https://user-images.githubusercontent.com/66286733/98274287-38ca4180-1f61-11eb-88dd-5a9609e737a4.jpg)

**Comment by grunbag** [comment]
Still happening ?
