### ISSUE TITLE
Level 15-20 Mobs in Chaos Starter area making quest completion impossible

### ISSUE THREAD

**Issue by Sorkhatani** [WarEmu/WarBugs#18034]
In the Chaos starter area, just outside the tower to kill Capt Wilke for the quest "The True Test," there is a level 15 and a level 20 guard blocking entrance to the tower. This makes completion of the quest impossible for its level range.

**Expected behavior and actual behavior:**
Mobs should be level appropriate, all other mobs are level 2. Level 15 and level 20 are obviously too tough for this spot.

**Steps to reproduce the problem:**
remove the level 15 and level 20 mobs, or reduce their level to 2.

**Testing Screenshots/Videos/Evidences (always needed):**
![Genghisjohn_001](https://user-images.githubusercontent.com/46400285/98072872-77d49600-1e80-11eb-93d4-297a11ee10f1.jpg)
![Genghisjohn_000](https://user-images.githubusercontent.com/46400285/98072878-799e5980-1e80-11eb-8775-4d400b63c2c0.jpg)

**Comment by xpander69** [comment]
![ss_11112020_22 36 20](https://user-images.githubusercontent.com/1345116/98863224-be258880-2470-11eb-9f54-e270045ebd1e.png)
confirming :P
