### ISSUE TITLE
BW belt trophies

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#18047]
BW can't show trophies around belt.
first, belt trophies had red x mark on them.
after i move them around they only appeared on the shoulder.

**Comment by Kaelang** [comment]
Need screenshots / more information.

**Comment by anarchypark** [comment]
![Tenthousand_001](https://user-images.githubusercontent.com/19988772/100769502-7aa2b680-343f-11eb-86d6-686389a7820c.jpg)

trophies are not appearing on BW belt.
it was possible before. now it's moving around only on shoulders.
like you didn't equip belt.
tested many trophies on various belts. 

belt have 4 trophy slots.
BW belt have 0 atm.

**Comment by anarchypark** [comment]
ty it's fixed.
