### ISSUE TITLE
quest working again and again

### ISSUE THREAD

**Issue by hustlewl** [WarEmu/WarBugs#1804]
![hustle_044](https://cloud.githubusercontent.com/assets/15678833/10982338/b8f5e736-841d-11e5-90e8-a1a94a2f8a6c.jpg)
![hustle_045](https://cloud.githubusercontent.com/assets/15678833/10982339/b8fb072a-841d-11e5-9888-32e9ac002a75.jpg)
I doubt that the way it should be.

**Comment by Evildoor** [comment]
#1645
