### ISSUE TITLE
[RP] Rune of burning tool tip scales with weapon dps

### ISSUE THREAD

**Issue by glasshands** [WarEmu/WarBugs#18041]
This is with rune of breaking off. The tool tip damage increases with weapon dps but the ability damage dose not. I tested 3 different setups, no weapon, starter weapon and t4 epic quest weapon.

No Weapon
![InkedShreddies_005_LI](https://user-images.githubusercontent.com/14142017/98334144-7958a800-1fbf-11eb-833b-f4c032332bc7.jpg)

Starter Weapon
![Shreddies_002](https://user-images.githubusercontent.com/14142017/98334176-89708780-1fbf-11eb-86bf-c1b0d8fd186b.jpg)
![InkedInkedShreddies_001_LI](https://user-images.githubusercontent.com/14142017/98334182-8b3a4b00-1fbf-11eb-8326-8ebf1a3f8934.jpg)

T4 Epic Weapon
![Shreddies_004](https://user-images.githubusercontent.com/14142017/98334251-b45adb80-1fbf-11eb-9739-50a5ba4fc4dd.jpg)
![InkedShreddies_003_LI](https://user-images.githubusercontent.com/14142017/98334286-c89ed880-1fbf-11eb-8acd-1ce58888ca4a.jpg)

        The T4 epic quest staff only gives 36 int but it adds over 500 damage to the tool tip. No other RP spell tool tip scales with weapon dps. I have all classes 40 except sorc and i can't think of any caster spell scaling with weapon dps. This happens with storm of ravens to and i think that's why you get so many bug reports saying the damage is off.

        I have no idea if it did this on live and i may be dumb and missing something obvious.

**Comment by glasshands** [comment]
I have no idea why the text came out like that.

**Comment by grunbag** [comment]
fixed with next patch
