### ISSUE TITLE
Inventory has been broken

### ISSUE THREAD

**Issue by Oldneko** [WarEmu/WarBugs#18042]
Inventory is not displayed correctly, like this situation.
https://github.com/WarEmu/WarBugs/issues/17951
I could see inventory correctly before the Event has begun.

It was useless even if the client was reinserted and the MOD was removed.
(I tried twice, downloading client via torrent or direct from link page "https://launcher.returnofreckoning.com/RoRInstaller.exe"
What should I do?

**Comment by Kaelang** [comment]
Move the folder to a different section / check forums for additional support.
