### ISSUE TITLE
RvR kill quests not getting credit for kills

### ISSUE THREAD

**Issue by AttilaTheHam** [WarEmu/WarBugs#18040]
I've just come back to the game after a few months and feel like I now almost never get credit for the kill quests in RvR. I get the experience/renown/influence reward for my kills but very rarely does it update the kill quests - normally for about every 30 or so kills I get, only 1 will track on the quest. I never encountered this when I played before, every kill that I was awarded experience/renown/influence for would give me credit towards the quests regardless of whether it was a solo kill where I did all the damage, a kill by my group that I didn't tag, or a kill where I only did a tiny bit of damage to an enemy while not part of a group.

**Comment by Kaelang** [comment]
This was changed however it is still working, I believe it's based on group input and not warband.
