### ISSUE TITLE
Wingmantle of Violent Rituals wrong apperance

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#18052]
**Expected behavior and actual behavior:**

When equipping this Wingmantle (shoulder armor) it gives the witch elf appearance rather than the zealot. The icon that is displayed is also a WE rather than a zealot)
To duplicate this visual bug complete the quest Crushing Stone (Chapter 21 Chaos in Reikland) and take the item

![Yttria_036](https://user-images.githubusercontent.com/13975292/98456448-5b1bb500-2143-11eb-81e3-6f18014d3dff.jpg)
![Yttria_037](https://user-images.githubusercontent.com/13975292/98456449-5c4ce200-2143-11eb-8f45-9d6437096224.jpg)

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaelang** [comment]
Fix was added on February 23rd patch. Please re-open if issue remains.
