### ISSUE TITLE
Raven Seer Waiststrap wrong appearance

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#18050]
This belt appearance is for a witch elf rather than a zealot. And because of that it misaligns the geometries. (It also has a WE belt icon rather than the zealot).

Complete the quest "The Inevitable Eye" (Chaos Chapter 21, in Reikland) and take the reward.
![Yttria_035](https://user-images.githubusercontent.com/13975292/98455908-353ee200-213c-11eb-8fc5-0cb0cfee2108.jpg)

![Yttria_034](https://user-images.githubusercontent.com/13975292/98455881-f1e47380-213b-11eb-8436-2a0044b82481.jpg)

**Comment by Kaelang** [comment]
Fix was added on February 23rd patch. Please re-open if issue remains.
