### ISSUE TITLE
[Ability] Slow Boil is broken. Zero co-efficient

### ISSUE THREAD

**Issue by Mezirah** [WarEmu/WarBugs#18051]
Visiton of Torment for sorcs is multiplying at .95 co-efficient. Slow boil is a big zero. Tool tip doesn't change no matter how much you change damgae bonus or intel. 

This was reported in February, a Fix came in March, but the fix didnt work or something else happened. Currently a major part of BW damage is missing as pure tooltip damage is hitting like a wet noodle. Is not class breaking but, its pretty big guys, please fix. On my BW toon, I can't even waste AP on it. My sorc is ripping like 1400 crits with their counterpart VoT.

Thanks for your help!

**Comment by ranzinus** [comment]
Same for me please fix this :(

**Comment by Mezirah** [comment]
Fixt
