### ISSUE TITLE
Ram cannot make contact with inner keep door inIronskin Skar in BC

### ISSUE THREAD

**Issue by detrap** [WarEmu/WarBugs#18055]
Ram cannot make contact with inner keep door inIronskin Skar in BC, tried 10 times multiple angles

![WAR-64 2020-11-09 12-36-56](https://user-images.githubusercontent.com/64330047/98491382-bc996c00-2288-11eb-858e-7f61e12eff55.png)

**Comment by Kaelang** [comment]
RvR has progressed since report went live.
