### ISSUE TITLE
Cannot Read Tome of Knowledge for Specific Classes

### ISSUE THREAD

**Issue by Pharm400** [WarEmu/WarBugs#18053]
**Expected behavior and actual behavior:**
Cannot read Tome of Knowledge for different classes under the racial tab

**Steps to reproduce the problem:**
Open tome of knowledge

**Testing Screenshots/Videos/Evidences (always needed):**
![ToK](https://user-images.githubusercontent.com/72531526/98458898-ba78c580-2141-11eb-9f6a-f31a428c0cdb.PNG)
I even picked up the hidden scroll in BV, still don't see runepriest etc.

**Comment by Lheana** [comment]
Seems like your client is not correctly updated. Try to use the "Repair" button on the launcher, or use our forum or Discord for support.
