### ISSUE TITLE
Casting Rain of Fire outside Maximum cast range now begins casting animation, locking the cast bar and putting the spell on cooldown (Bug still here

### ISSUE THREAD

**Issue by Sandrasfanat** [WarEmu/WarBugs#18054]
Casting Rain of Fire outside Maximum cast range now begins casting animation, locking the cast bar and putting the spell on cooldown
-->

Expected behavior and actual behavior:
The expected Behavior of casting rain of fire outside of range is to receive the out of range error and **not put the spell on cooldown or animation lock your character**

Steps to reproduce the problem:
cast rain of fire outside of Max Range

Bug is still there here a video on my google disk https://drive.google.com/file/d/1gpt0DeTyhYKD-WMx3bQga_kMV7C-K9E_/view?usp=sharing

dalen commented 2 hours ago
For me it starts the cast where the circle is, at the maximum range of the ability. I don't really see the bug here.

Please read carefuly- when you **use ability outside range** and there is no target circle- **ability coes on cooldown** and character animation locks- even escape key or jump key doesnt help to cansel it. Before this bug, when you use rain of fire out of the range - **u have a error message and ability doesnt go on cooldown**, you just use it immidiatly again. Now even when you slitly out of range - ability goes on cooldown, please check my video.  This is a bug, wich appear after some summer patches.

**Comment by dalen** [comment]
This is the behavior I get https://youtu.be/LFpM9vcYBLE

**Comment by Sandrasfanat** [comment]
Another video https://drive.google.com/file/d/1Py18GE7zQd2xbx87xR6_lr3SdRTP9MUx/view?usp=sharing
at 00:08 - bug behavior, at 00:22 - doing like you with sircle all ok, 0:40 and next an 2 examples of bug, and you dont even need wall for it.

**Comment by Sandrasfanat** [comment]
press move forvard, stop  then rain of fire and you will see it

**Comment by dalen** [comment]
It send a center screen message that it was out of range, but still stayed stuck in the animation.

I made a fix now so it sends the correct ability result out of range packet instead.
