### ISSUE TITLE
Bugged toughness at squig armor skill

### ISSUE THREAD

**Issue by Gessian** [WarEmu/WarBugs#1806]
hey hey, if i use on my SH " Squig Armor" at rvr zone,its give me 13k toughness...and im unkillable
if use it at pve,no bug, have 200tougness like normal 
![yezza_005](https://cloud.githubusercontent.com/assets/15679327/10983571/72cf953e-8424-11e5-97aa-fbfef979d156.jpg)
![yezza_006](https://cloud.githubusercontent.com/assets/15679327/10983573/7661bac4-8424-11e5-9a5c-b0a18b2da0f4.jpg)
![yezza_008](https://cloud.githubusercontent.com/assets/15679327/10983575/832b30f0-8424-11e5-8df6-be11e0ea3914.jpg)
you see how changes toughness at rvr if use squig armor skill(

sorry for bad english,not my lang

**Comment by Gessian** [comment]
now i tested this skill with other SH at ostland rvr zone, he hasnt recived this awesome toughness bonus(
maybe, because i have +toughness tali

**Comment by ozarmidrashim** [comment]
Corrected handling generally (+3-120 to Strength, Toughness and Wounds depending on level.)
