### ISSUE TITLE
Frequent crashes upon using Flightmaster

### ISSUE THREAD

**Issue by Caduceus42** [WarEmu/WarBugs#18067]
Hello,

Since a week or two I have been getting crashes frequently when using the flightmaster.

Instead of bringing me to the loading screen, the game crashes and puts me back to my desktop. The launcher does not crash. When I log back in, my character is in the zone I tried to fly to.

This issue seems to resolve itself sometimes, and I'm able to use the flightmaster no problem. However, when I start a new session the bug often returns.

When I asked in public chat channels, many players seemed to have the same issue. 

Here's a link to a video with the bug occuring: 
https://youtu.be/BiMbdgfzpuw

If any more information is needed I'd be glad to provide it.

Cheers,

- Caduceus

**Comment by Kaelang** [comment]
I'd suggest checking the forums as this looks to be client related (your end).
