### ISSUE TITLE
DETAUNT _ (all classes)

### ISSUE THREAD

**Issue by stonetradex** [WarEmu/WarBugs#18062]
After I pop detaunt and atack my target. I hit for -50 % less dmg. 
Just the first hits, Skills + AA

Proof: https://www.youtube.com/watch?v=U21J82mPqYA
)
Hey.. I want a Manticore!!!!

just kiding, I already have one :)

Regards,

Krima

**Comment by XmatXergon** [comment]
fixed link: https://www.youtube.com/watch?v=U21J82mPqYA

**Comment by cimator** [comment]
iirc it was intended that dots deal half damage if your target is detaunted. The first hit breaking the detaunt also getting halved seems like a side effect of that. 
Should check the patch notes from couple years ago or maybe a dev can confirm it

**Comment by stonetradex** [comment]
Slice its not a dot.
