### ISSUE TITLE
Dwarf T4 epic quest - Battle For Remembrance bug

### ISSUE THREAD

**Issue by jatosemja** [WarEmu/WarBugs#18063]
The dwarf T4 epic quest "Battle For Remembrance" seems to be bugged.
The issue is with the first quest, specifically with "Muck Pen Location" (old dwarf statue), coordinates 32K/25.4K (taken from wiki).
As the picture shows I cant click the statue, same issue happens when I complete the other 3 objectives first.
From what I asked, it should have been working few weeks ago.

![Screenshot 2020-11-10 19 41 39](https://user-images.githubusercontent.com/74264170/98717214-15522d00-238d-11eb-959c-34351672665a.png)

**Comment by odoc7625** [comment]
wrong statue
![Rainia_057 (2)](https://user-images.githubusercontent.com/66634766/98840340-87615b00-23fb-11eb-87b8-6d0dc1632eff.jpg)
here the cords
![Rainia_059 (2)](https://user-images.githubusercontent.com/66634766/98840370-921bf000-23fb-11eb-8ffc-b1a46a471691.jpg)

**Comment by odoc7625** [comment]
look at ur mini map,ur not in red blob

**Comment by jatosemja** [comment]
Thanks for the info, my bad.
I checked it now and the statue was there...not sure if I am completely
blind, or it really wasnt there yesterday.
As for the red circle (area of the quest), I figured it wasnt reliable
given the locations of "Burnmaw Tower" and "Infested Tower" are outside of
it (attached pictures).
Also when I clicked on the location of "Burnmaw Tower" the red circle on
map disappeared all together.

**Comment by Lheana** [comment]
About the quest marker issue, it's already reported here #14097 so I'll close this ticket.

**Comment by Kaizoo-fi** [comment]
Hello @Lheana ! 
This issue still seems to be valid, I've been trying to do the dwarf statue part for a good 5h today, clearing the whole PQ from start to finish, yet the old dwarf statue does not spawn per screenshots. 

I've been scouting the zone and yet to see any sign of it being misplaced to somewhere else, I feel like it just doesn't want to spawn :D

**Comment by AlexeyBlokhin** [comment]
@Lheana 
Can also confirm, statue does not appear anywhere in the area.
