### ISSUE TITLE
No debuff

### ISSUE THREAD

**Issue by xipcod** [WarEmu/WarBugs#18077]
**Expected behavior and actual behavior:**
Debuff should be added, but nothing happens

**Steps to reproduce the problem:**
It is necessary at the time of teleportation to press the button so that 2 teleportations occur simultaneously: to the city and to the scenario
Using this, you can bypass the scenario blocking when an buguser needs it.

**Testing Screenshots/Videos/Evidences (always needed):**
https://youtu.be/xyo4jXLpsiY

**Comment by xipcod** [comment]
Solution to the problem:
https://youtu.be/uz-CAqfmsQg

Just use the same teleportation system as when you use the command /stuck (x2)

**Comment by Kaelang** [comment]
Already listed.
