### ISSUE TITLE
Seed restoration didn't work when server crashed

### ISSUE THREAD

**Issue by Elenori-brings-bugs** [WarEmu/WarBugs#18070]
**Expected behavior and actual behavior:**
_Expected:_ 
Usually when the server is shut down or I exit or log out, the plants currently in the process of cultivation are saved and returned to inventory in the form of seeds and after the next login a message is included in chat confirming that seeds have been restored.
_Actual:_ 
Today (12 Nov 2020) at about 1:00 Altdorf time the server was experiencing a great slowdown ending in a crash (or perhaps it was shut down). It was impossible to cancel cultivation because of lag. After I returned later today, I found that no message was sent and no seed restoration took place, which destroyed a very rare Eternal Black Hellebore seed. Please change the restoration mechanic to work in cases like this as well.

**Steps to reproduce the problem:**
Start cultivating a seed. Experience a server crash? It should be easier to look on your end at what happened to the server during that time.

**Testing Screenshots/Videos/Evidences (always needed):**
Since there was no message and all the seeds were lost, what kind of screenshot is needed? I can provide one of the Eternal seed to show that I had one previously.

![seed](https://user-images.githubusercontent.com/74368755/98966179-03eb5b00-251c-11eb-86cf-f7836fb6d806.jpg)

**Comment by Kaelang** [comment]
We're aware this can sometimes happen with epic seeds. There's already a live report but I'll remind the devs.
