### ISSUE TITLE
Marauder off sov 4th (6% Armor penetration Proc) doesn't work

### ISSUE THREAD

**Issue by wildwindblows** [WarEmu/WarBugs#18074]
Hello Bug Tracker Team,
As it is mentioned in the title, Marauder off sov 4th (6% Armor penetration Proc) doesn't work. You can find my evidance below.
Thanks.
Armor penet. with 5x off sov piece: 16%
Armor penet. with 3x off sov piece: 14%

![resim](https://user-images.githubusercontent.com/45720515/99065801-0223a500-25b9-11eb-8410-1323c1f73b68.png)

**Comment by stonetradex** [comment]
It seems to be working.. bottom of the getstats widow It says Armor Penetration: 6 
Did you test on the new mob in IC?

**Comment by wildwindblows** [comment]
How can i test on the new mob? That test depends on so many variable and because of this there is huge variation on each test.

**Comment by wildwindblows** [comment]
I see you point. I will check from getstats window.

**Comment by wildwindblows** [comment]
Yes you are right. getstats obviously indicate 6% more armor penetration so this topic can be closed. Stats misslead me sorry.
