### ISSUE TITLE
Detaunt does not apply damage debuff when being guarded

### ISSUE THREAD

**Issue by detrap** [WarEmu/WarBugs#18079]
Detaunt does not apply damage debuff when being guarded?

When WP detaunts the zealot, the WP receives the same amount of damage however the tank no longer takes any damage from guard.

https://streamable.com/a05cok

From the video above:

Combat log is of the SM
@ 15 seconds detaunt is applied by the WP (buffhead on zealot)
Bottom of screen shows the WP still taking damage (which can confirm is the exact same amount before the detaunt)
The SM's combat log shows no damage being taking during the 15 second detaunt duration.

This is also happening with PvE mobs.

**Comment by dalen** [comment]
That is exactly how detaunt+guard is supposed to work.

**Comment by detrap** [comment]
Thanks. Had conflicting reports on forum posts.
