### ISSUE TITLE
SHAMAN DAMAGE SHIELD

### ISSUE THREAD

**Issue by Zoombi** [WarEmu/WarBugs#1807]
shaman build waaagh via dots to 5
 shaman use damage shield
SHAMAN GET DAMAGE SHIELD OF 4K
SHAMAN NO LOSE WAAGH POINTS = am does
shaman kite and do samage shield again. all chasing die
ALSO, damage shield 600 with 5 stacks protects for 3k damage
5 stacks at 5% BONUS TO INSTA each result in iNcrease from 600 to 3000
hmm u r need calculator

**Comment by Zoombi** [comment]
FUCK THIS SITE SUCKS
WHEN SHAMAN USE DPS SHIELD W 5 STACKS OF WAAAAGH THEY DO NOT LOSE ANY WAAAAGH. WHEN AM DO SAME THEY LOSE ALL BUILD UP STACKS

**Comment by ozarmidrashim** [comment]
If you can't make a civil and comprehensible report, don't bother.
