### ISSUE TITLE
T4 Dark Elf Epic Quest Step 6 (The Ebon Flame) Iriorl and Indhrian Wolfmoon NPCs not spawning

### ISSUE THREAD

**Issue by frontlinemei** [WarEmu/WarBugs#18089]
**Expected behavior and actual behavior:**
The quest said to kill enemy NPCs Iriorl and Indrhrian Wolfmoon in the tower at 35.7k/62.7k south of the PQ The Spirit of Eataine
,however I when I went inside and ran laps around the tower I never found them. I killed all the NPCs I could find to make sure I wasn't missing anything

**Steps to reproduce the problem:**
I have gone to the tower several times yesterday and today and killed all NPCs in the tower again and again but with no luck

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/74557395/99283540-0f48ca00-282d-11eb-80c2-07f4ad6ecb15.png)

**Comment by Lheana** [comment]
They are correctly inside the tower, just verified.
