### ISSUE TITLE
Intellince potions not apliening correctly

### ISSUE THREAD

**Issue by Txarlyman** [WarEmu/WarBugs#18087]
I Reallized that the Intelligence Potions and liniments are not aplieng the correct stat upgrade, its missing about 24 points from the total amount the potion / liniment gives.

I've only checked it on my magus so im not sure if it's only me or affects other players.

My stats without potions:
![Tzulagh_009](https://user-images.githubusercontent.com/59922493/99240956-7ea6c580-27fd-11eb-97b6-b1994efe2e60.jpg)

My stats with Liniment 60 intelligence 5% magic crit:
![Tzulagh_011](https://user-images.githubusercontent.com/59922493/99240723-2b347780-27fd-11eb-97f0-424ac289eadb.jpg)

My stats with a 80 intelligence buff:
![Tzulagh_012](https://user-images.githubusercontent.com/59922493/99240773-430bfb80-27fd-11eb-99e5-7ed294879ce5.jpg)

Thanks for you're atention. Have a nice day.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaloell** [comment]
"The stats in the character window are not always accurate. To be sure use .getstats" -every dev on here

This might only be a visual bug in the client character window. To make sure the stats don't get applied type ".getstats" into the chat and look at the result instead.

**Comment by Txarlyman** [comment]
I did use the command and showed the same number that the stats, sorry but I didn’t screen shot it, can do it later if you want and show the result

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Kaloell <notifications@github.com>
Enviado: Monday, November 16, 2020 2:03:27 PM
Para: WarEmu/WarBugs <WarBugs@noreply.github.com>
Cc: Txarlyman <a530004@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [WarEmu/WarBugs] Intellince potions not apliening correctly (#18087)


"The stats in the character window are not always accurate. To be sure use .getstats" -every dev on here

This might only be a visual bug in the client character window. To make sure the stats don't get applied type ".getstats" into the chat and look at the result instead.
