### ISSUE TITLE
White lion Animation bug (lions running animation). 

### ISSUE THREAD

**Issue by nnnnNATHANnnnn** [WarEmu/WarBugs#18080]
**Expected behavior and actual behavior:**
I expected the lion to run normally. There's a sorta silly animation  bug. I relogged to check if that would fix it before recording / posting.

**Steps to reproduce the problem:**
Summon WL pet and run around.

**Testing Screenshots/Videos/Evidences (always needed):**
https://www.youtube.com/watch?v=4fuxCSxImM4

**Comment by nnnnNATHANnnnn** [comment]
Reopened because it kinda (kinda key word) stopped happening and then started up again. Maybe it has something to do with being PVE flagged?

**Comment by Kaelang** [comment]
Already listed.
