### ISSUE TITLE
Squig Herder chest armor disappearing

### ISSUE THREAD

**Issue by jduvall648** [WarEmu/WarBugs#1808]
My L26 Squig Herder is missing his chest armor every time my account is logged off for  24 hours.

**Comment by Evildoor** [comment]
This problem still persists?

**Comment by jduvall648** [comment]
I am not sure, tbh I havent logged into the game in quite some time. thanks
for the reply though.

**Comment by Evildoor** [comment]
Can you check it? Or you are not playing the game any more? If latter - it's ok, just say so.

**Comment by Evildoor** [comment]
No response, closing.
