### ISSUE TITLE
Heaven's Fury Incorrect Tooltip

### ISSUE THREAD

**Issue by DefVont** [WarEmu/WarBugs#18082]
Duration is incorrect. Should be 3 seconds instead of 5 seconds, or is it supposed to be the other way around? :D

![hf incorrect tooltip](https://user-images.githubusercontent.com/64330047/99184764-5f764c80-2799-11eb-9bcd-bc9a3e3352b3.png)

**Comment by lilimx** [comment]
was fixed with patch 29/01/2021
