### ISSUE TITLE
Daemonic Resistance/liniment cancelling each other out

### ISSUE THREAD

**Issue by Tyrean1** [WarEmu/WarBugs#18085]
Since the last patch the Daemonic Resistance buff for Magus and a liniment are cancelling each other out. If I use a liniment and then cast Daemonic resistance I lose the liniment effect. This works the other way also where applying a liniment cancels the Daemonic Resistance buff.

****Expected behavior:** Both should be applied to character. **Actual behavior:** They cancel each other out**

Steps to reproduce the problem: Tested multiple times.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
Please check the kind of bug.
Is it a visible bug or does the potion really get lost.
do tests like /rel and .getstats

**Comment by lilimx** [comment]
Hey,

im going to close this ticket now due to no feedback.
