### ISSUE TITLE
Bathing in blood [BG](tactic)

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#18098]
Reported this long ago, it has been closed some week ago telling that it was fix , it is not....
https://github.com/WarEmu/WarBugs/issues/7955

Step to replicate: agro 2 mob, bring both near death, kill 1, let 1 gcd pass kill the second. You will have the tactic re-fresh the effect when it should NOT.

The effec proc and so refresh on every kill making the heal effect impossible to use since the heal tick happen every 3 sec unless you attack one mob at time or 1 player at time.....

(tick intervall after 3 sec from kill)
![Sintoras_063](https://user-images.githubusercontent.com/7527415/99676326-a190de00-2a78-11eb-9b5c-67f9bfad653b.jpg)

It need to NOT refresh/ re-proc on a new kill  ""  I F  "" the effect is alredy on;  the same way it was done for a lot of tactics  which had the same problem and were considerated a bug long ago, or be changed to have the first  tick on zero seconds,,8,9) so that the tick interval or the refresh/re-proc dosent matter anymore

**Comment by dalen** [comment]
with the new hot/dot refresh mechanics this is not a problem. Even if the dot refreshes the tick timer doesn't.

**Comment by Tesq** [comment]
no, it dosent work that way, the new dot meccanic add duration..... still there is no tick at 0 sec so the tactic dont work, i tested this...... it still take 3 sec interval from proc to recive heal; it need tick at 0 sec or be changed to not refresh.

**Comment by Tesq** [comment]
What dalen said is in right ( in part ) as show in the screen bellow if you kill 2 mob each gcd, the tactic refresh with no tick the best fix with new dot/hot meccanic is make the tick interval 0,3,6,9 instead 3,6,9.

**Comment by Tesq** [comment]
i tested this with lv 1 mobs with multiple kills dalen right the effect kick in was confused due first gcd get add
