### ISSUE TITLE
Naked NPCs in IC

### ISSUE THREAD

**Issue by Hadzi-user** [WarEmu/WarBugs#18095]
**Expected behavior and actual behavior:**
Expected behavior and actual behavior:
The NPCs in IC must have armor or some dresses.
Actual behavior:
The guards are naked, some of questgiver are naked. Many naked NPCs in IC. =) It started after the last patch 18/11/20.

**Steps to reproduce the problem:**
Go to Inevitable City and look around. You will see many naked NPCs. For Ex. Dread Sentry or Queue quest takener.

**Testing Screenshots/Videos/Evidences (always needed):**
![Hadzi_027](https://user-images.githubusercontent.com/69014772/99578925-9002f400-29ee-11eb-8fc6-78be499be253.jpg)
![Hadzi_028](https://user-images.githubusercontent.com/69014772/99578927-91342100-29ee-11eb-970d-695479b317bb.jpg)
![Hadzi_026](https://user-images.githubusercontent.com/69014772/99578929-91ccb780-29ee-11eb-809f-7416c7765c32.jpg)

**Comment by MaxHayman** [comment]
Fixed in upcoming patch/hotfix. This might also fix some weird issues around too!
