### ISSUE TITLE
Quest:  By Torchlight

### ISSUE THREAD

**Issue by Jonzac** [WarEmu/WarBugs#18093]
**Expected behavior and actual behavior:**
Expected:  Torches to interact with to destroy the tower
Actual:  no torches available, you can kill the orcs near them with is also a quest requirement

**Steps to reproduce the problem:**
Start quest "by Torchlight"

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
fixed with patch 21/07/2022
