### ISSUE TITLE
Absorb potion

### ISSUE THREAD

**Issue by zuzrat** [WarEmu/WarBugs#18094]
Level 40 absorb potion can't be used and don't have a desctiption.

![qwqwq](https://user-images.githubusercontent.com/16220885/99577201-719ff700-29f4-11eb-8197-0527af2a3d1d.png)

Not sure if it helps but on armory there are two types of "Potent Fleeting Warding potion"
https://www.returnofreckoning.com/armory/item/3003105
https://www.returnofreckoning.com/armory/item/197353

one of them have description, the other doesn't.

**Comment by zuzrat** [comment]
Not sure if it helps but on armory there is two types of "Potent Fleeting Warding potion"
https://www.returnofreckoning.com/armory/item/3003105
https://www.returnofreckoning.com/armory/item/197353

one of them have description, the other doesn't.

**Comment by zuzrat** [comment]
Also level 40 lasting AP pot absorb less then level 38 aborb pot, which doesn't make sense.
And item level is 55, not 40.
![qwqwqw](https://user-images.githubusercontent.com/16220885/101378976-2b400880-38cd-11eb-86ad-493bf53570b6.png)

**Comment by Lheana** [comment]
This has been fixed with the patch of 08/05/2021.
