### ISSUE TITLE
[Sound] Constant ambient background sound

### ISSUE THREAD

**Issue by CrimsonFenris** [WarEmu/WarBugs#18091]
Got this issue for weeks/months now :

After playing for minutes/hours, there is now a constant ambient sound in the game background ; it's like wind blowing through  cave underground or pipe, or the ambient sound of Chaos Wastes.

A constant Whooooooooo, not very loud but clearly audible in the background, and it's quickly getting on nerves after a while since it's now stuck and playing ininterrupted for the whole session.

Only a relog fixes the issue, and it's not for long (reappears after a short time playing).

_And no, i checked it's not my computer fans, since I can deactivate the sound with audio settings (along with all other sounds effects, wich is not very practical indeed)._

Issue sounds similar to database error when ambient sounds were triggering without reason (train whistles, bosses talking, etc).

My peace of mind will thank you finding a fix for this one... ;)

**Comment by lilimx** [comment]
Hey,

I guess it's a broken audio.myp or something similar.
If the issue still persists, please feel free to join the RoR discord and asked in #technical-advice.
