### ISSUE TITLE
bar not picking up keybind clicks

### ISSUE THREAD

**Issue by Parallels66** [WarEmu/WarBugs#18090]
im not sure if this will be much help as there isnt really anything fancy to it but just logging in the usual way, 2nd time now ive logged in and the game doesnt register my keybind clicks on my 3rd bar, for me specifically its bar 3, bar 1 and 2 will register fine but bar 3 just ignores the keybind clicks until i relog the entire game. 

a few guildies have had this issue aswell lately (not sure if specifically 3rd bar like mine), so far a full relog of the game is only fix we have found for it and doesnt seem to be anything we can noticeably see causing it as it happens rarely when you log in, in last 3~ weeks ive had it happen twice now.

**Comment by Parallels66** [comment]
happened again today when logging in, same thing again, 3rd bar keybinds no registering

**Comment by lilimx** [comment]
Hey, has it happened it again? Are you using any addons (Vinyui?)
