### ISSUE TITLE
[Engineer] Turret redeploy not transporting correctly to summoned location

### ISSUE THREAD

**Issue by IxanderousI** [WarEmu/WarBugs#18103]
When using redeploy after summoning a turret it won't correctly change to the new location, the improvised upgrades will still apply to the new location but the turret itself will stay on same previous spot, meaning it won't be able to hit anyone in your characters range. Standing away at much further distance from turret will redeploy correctly, seems to be an issue when its closer to original location.

Turret spawned
![turret 1](https://user-images.githubusercontent.com/25346641/99777154-cf723300-2b09-11eb-87e7-bff7eecaf657.jpg)

Turret redeployed
![turret 2](https://user-images.githubusercontent.com/25346641/99777132-c8e3bb80-2b09-11eb-8e2f-c10ad3c74e7f.jpg)

**Steps to reproduce the problem:**

Step 1: spawn a turret
step2: use redeploy at location roughly within 20ft of turret

**Comment by johnsmith534** [comment]
same thing is occurring for the magus

**Comment by CornerbackAC** [comment]
It seems that only the model of the turret is not moved. If you look at the stacks you get from the turret or addons like TurretRange, the turret is actually being teleported to your location, but the location of the visible model is not refreshed.

**Comment by grunbag** [comment]
Fixed already
