### ISSUE TITLE
Lag due to packet corruption

### ISSUE THREAD

**Issue by Banstro** [WarEmu/WarBugs#1810]
I was in a scenario and suddenly i received over 10k gold. After that happened I couldn't fight or attack anyone. When the scenario ended the gold was gone. Ended up getting a bit confused and decided to relog.

**Comment by ozarmidrashim** [comment]
Packet corruption.

**Comment by Evildoor** [comment]
From my experience this happens as following: player is affected by severe lag, which can last pretty long, up to several minutes. All other characters disappear. After some time player may gain ridiculous amounts of something, like gold, or influence, or stats (only visually). Then other characters reappear and function properly. For some time player-related issues may persist - for example, he/she is unable to attack or some buffs/debuffs which should have been gone are still shown on their character.
