### ISSUE TITLE
The action house stop showing new postings 

### ISSUE THREAD

**Issue by jusva321** [WarEmu/WarBugs#18101]
i can post a superior talisman of the protector but i dont show up when you search for it even tho i am the lowest price i have to look up my name to finde it this is on ordor toons name is jusva 

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kaloell** [comment]
The reason for this is (probably) that only the oldest X results will be shown for any query.
This means, that if you search for something that has 10000 results only the oldest X will be shown (and sorted).
Searching for something with less than X results will return all results. This is why you got a result if you looked up your name.

**Comment by MaxHayman** [comment]
I have put in a fix for this, which will come live in the next hotfix/patch. Before when there was more than 100 matching auctions it would sort results as we would have liked and would only sort on the first 100.

Now we take all the results and then sort them by Item Name, then by price per unit, then by auction start time.

So here is an example.

```            items.Add(new Item() { Name = "AlphabetSoup", SellPrice = 10, Count = 2, StartTime = 1});
            items.Add(new Item() { Name = "AlphabetSoup", SellPrice = 1, Count = 10, StartTime = 10});
            items.Add(new Item() { Name = "AlphabetSoup", SellPrice = 5, Count = 1, StartTime = 25});
            items.Add(new Item() { Name = "AlphabetSoup", SellPrice = 15, Count = 2, StartTime = 40});
            items.Add(new Item() { Name = "AlphabetSoup", SellPrice = 100, Count = 2, StartTime = 30});
            items.Add(new Item() { Name = "AlphabetSoup", SellPrice = 1, Count = 10, StartTime = 50});
            items.Add(new Item() { Name = "Banana AlphabetSoup", SellPrice = 3, Count = 10, StartTime = 20});
```

Here we have the auction house with the fictitious item "AlphabetSoup" with different sell prices and quantities and posted at different times (larger is later in time).

When searching for "AlphabetSoup" the Auction House will return the following results.

```
AlphabetSoup Price: 1 (0,1/each) Count: 10 Started: 50
AlphabetSoup Price: 1 (0,1/each) Count: 10 Started: 10
AlphabetSoup Price: 5 (5/each) Count: 1 Started: 25
AlphabetSoup Price: 10 (5/each) Count: 2 Started: 1
AlphabetSoup Price: 15 (7,5/each) Count: 2 Started: 40
AlphabetSoup Price: 100 (50/each) Count: 2 Started: 30
Banana AlphabetSoup Price: 3 (0,3/each) Count: 10 Started: 20
```

As you can see Its first ordered by Name, so "AlphabetSoup" comes before "Banana AlphabetSoup".
Then its sorted by price per quantity, so 0.1 per quantity is the cheapest so it is put at the top.
Then it is sorted by post time, meaning if you posted your item last you appear at the top. This is designed so if you wanted to appear at the top you don't need to constantly undercut the going price for your item.

**Comment by jusva321** [comment]
Thx

søn. 29. nov. 2020 11.39 skrev Max Hayman <notifications@github.com>:
