### ISSUE TITLE
Gunbad mid Arathemia not counting as killed

### ISSUE THREAD

**Issue by SchwarzCodes** [WarEmu/WarBugs#18104]
Arathemia does not count as dead if killed, making progressing the dungeon impossible. I assume this has something to do with the changes to her adds in the last patch.

**Comment by karrik1978** [comment]
Good afternoon!
Today our group faced the same problem. The boss is bugged, self-destructed at 40% health. Further passage of the dungeon is impossible.
https://youtu.be/GoF1pHoAacY

**Comment by Kabucoror** [comment]
a fix is already pending

**Comment by SchwarzCodes** [comment]
Is fixed :)
