### ISSUE TITLE
Dwarf Quest giver contently in falling animation 

### ISSUE THREAD

**Issue by BerserkersFury** [WarEmu/WarBugs#18119]
The quest giver NPC called Thronki  Grimgirsson inside of the  Durak's mine in Ekrand of "Oathbearers way" next to the tomb is in a consent falling animation when you arrive to him I took a screen shot for the reference since i immediately saw it. i hope this gets fix when the team has time to see to it
my forum name on ROR site is  BerserkersFury if anyone on the team needs to direct message me for the Screenshot

**Comment by Lheana** [comment]
You can directly post your screenshot here ;)

**Comment by BerserkersFury** [comment]
![Dwalan_000](https://user-images.githubusercontent.com/74995080/100481746-05f11480-30ed-11eb-9da9-12e565755974.jpg)
This is the Screenshot i took from it
