### ISSUE TITLE
Legendary Talismans

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#18118]
The legendary talismans for the Sentinel ring, it seems the timer is bugged. The talisman says they last 7 days. But they only seem to last 5 days.

**Comment by wiscel** [comment]
Checked to be sure, yesterday I had 4 days left on my +4 range crit. I log in today, now it says 1 day left :-/

**Comment by Kaelang** [comment]
All talismans with expiration are set to 7 days. Please re-open with the name of the item if you think it's still wrong.
