### ISSUE TITLE
Keep vendors are wrong level

### ISSUE THREAD

**Issue by huntergregg2** [WarEmu/WarBugs#1811]
The Empire keep vendors on the 3rd floor are level 15ish, whereas when Order attempts to take STK or another Chaos keep those same vendors are level 40. This gives Chaos the ability to retreat to the 3rd floor of a keep and fight with lvl 40 NPCs assisting them, but Order does not have that ability as our vendors are only lvl 15.

**Comment by huntergregg2** [comment]
Any update on this issue? It's quite an imbalance when Chaos NPCs are level 50+ and they can just run to the top of the keep and Order can't chase them due to getting slaughtered by the NPC's. But in Order keeps the NPCs are lvl 15-20, so Chaos just runs up to the 3rd floor and Order has no built-in protection as Chaos does. A 6-person group of Chaos could hold off an entire warband of Order from the third floor, until the keep lord is dropped, anyway. But Order has no such safety as the NPCs are lvl 15.

**Comment by Abolition** [comment]
It stops those scrubby White Lions from pouncing through walls up to the roof!

**Comment by huntergregg2** [comment]
Perhaps, but it doesn't prevent Chaos from logging in previously logged out characters on the third floor, killing the NPCs, then adding to the defending force or just running straight to the third floor and defending from there with the help of lvl 53+ NPCs. Nor does it prevent squigs from climbing walls or appearing in the keep randomly. Regardless of pet behavior, the NPC level is imbalanced.

**Comment by genisaurus** [comment]
Fixed on next patch
