### ISSUE TITLE
Party Leader Disconnections

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#18110]
**Expected behavior and actual behavior:**

For members to be able to join a party or warband and remain in game. Since Thursday 19th November, we have found that frequently the party leader will get disconnected back to the character screen. Leadership of the group then passes to the next party member in the group as expected... but shortly after they DC too. This happens to everyone who takes party leadership, but at times two party members will DC at once together, then other members DC shortly after. This has been ongoing daily since Thursday, particularly in PVE areas.

**Steps to reproduce the problem:**

I do not know.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/22262165/99887512-ec5b5300-2c3c-11eb-8f32-d027c2db88ac.png)

**Comment by Senthoi** [comment]
We've also tested this by disbanding our parties and just using /guild to communicate. The random single player disconnections still occur.

**Comment by dalen** [comment]
If the bug is just that sometimes some people crash there's not really much we can do here. Needs something more specific.

**Comment by Senthoi** [comment]
Thanks, and I appreciate it's like finding a needle in a haystack! I've asked our Alliance for feedback to see if more specifics or a pattern besides party leader crashing first can be seen. I'll get back to you when they've responded.

**Comment by Senthoi** [comment]
So it does seem to only be occurring in PVE areas. They've described how it seems the game thinks you're AFK - I'm going to time it next to see if it syncs with the standard AFK timer - although I've found it does seem to DC you quicker than this.
![126946722_3145884725516588_1180265352278839570_n](https://user-images.githubusercontent.com/22262165/99911321-72ce6e00-2ceb-11eb-8d5f-085f9856cf00.jpg)
![126938050_713863692861510_2143844256207081810_n](https://user-images.githubusercontent.com/22262165/99911326-782bb880-2ceb-11eb-80b3-d0e17bfec36b.jpg)

**Comment by Senthoi** [comment]
We tested this today with a small party of 4. We flagged for RVR in a PVE area to see if it would make any difference, as these DCs don't seem to occur if you are in a party queuing for scenarios, or if you are in an RVR lake. At first, it seemed that the party leader would DC when the RVR flag timed out after 10 minutes. A party member DC'd after 3 minutes, then 12 minutes, then 14 minutes - each time this was the party leader. Flagging for RVR made no difference.

**Comment by Senthoi** [comment]
I'm wondering if this fix has had anything to do with it?
![image](https://user-images.githubusercontent.com/22262165/100153515-27a78d00-2e9c-11eb-8a9a-d57f830c2078.png)
When RPing, people are generally not moving their characters. Which should just flag to show as AFK after a while as you know. It seems almost as if the game is reading that the party/WB leader is AFK and is logging them out to the character screen without a logout timer or AFK warning.

**Comment by Senthoi** [comment]
We've noticed since yesterday, the random disconnects seem to have stopped! Thanks for doing whatever it was to fix this. I'll close this report.
