### ISSUE TITLE
Wolf Is Da Best is Bugged 

### ISSUE THREAD

**Issue by Cybergamma** [WarEmu/WarBugs#18117]
![Screenshot (1)](https://user-images.githubusercontent.com/74887462/99925792-41a66b80-2cf4-11eb-87a5-36be937d7841.png)
![Screenshot (2)](https://user-images.githubusercontent.com/74887462/99925802-4b2fd380-2cf4-11eb-9ae0-7c09aeb2d548.png)

Hi there, I was doing this quest called Wolf Is Da Best for the orcs, I killed the 3 boars that I need to feed the wolf, when I checked inside my quest inventory I noticed that the quest item isn't there, I figured re-launching the game would solve the problem but it didn't. Then I decided to abandon the quest and start it again to see if that worked but it didn't, at this point I have no idea what the issue is with the quest, so I figured I let you guys know about it.

**Comment by Lheana** [comment]
It's a drop chance, it means you won't get the item automatically. Keep killing them and the item will drop.
