### ISSUE TITLE
Gunbad - Mid Wind - Final boss, Ard ta Feed

### ISSUE THREAD

**Issue by martialiss** [WarEmu/WarBugs#18129]
**Expected behavior and actual behavior:**
Final boss, Ard ta Feed:
Rage Phase, to dispell the Rage, the buttons do not appear.

**Steps to reproduce the problem:**
Fight until boss enrage.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Yasmyr** [comment]
The buttons did appear for us, but did not work.
The bubbles that spawn small squigs however were not visible (and attack able) for different members of the party. Sometimes some people could see them, and others not.

**Comment by ranzinus** [comment]
Samere here today 22:00, 27.11.2020

Problem: Bubbles are not shown anymore.  Buttons aint working , even if the obelisk is activated.

**Comment by MaxHayman** [comment]
Should be fixed. Please reopen if you have further issues.
