### ISSUE TITLE
[Engineer] machinegun turret missing armor pen and rapid fire ability after recent patch

### ISSUE THREAD

**Issue by IxanderousI** [WarEmu/WarBugs#18128]
Spawn turret, no abilities showing on UI and not performing them in combat

![turret](https://user-images.githubusercontent.com/25346641/100452627-70845f00-30b1-11eb-96b1-6ac838835919.png)

**Comment by CornerbackAC** [comment]
I can confirm this.

**Comment by Zeel0t** [comment]
Same on my engi.
