### ISSUE TITLE
Gunbad - Right Wing

### ISSUE THREAD

**Issue by Darknodx** [WarEmu/WarBugs#18126]
Masta Mixa, the final boss in the right wing completely disappears if your group wipes. It did not reset upon trying to create a new instance with a character that had no lockouts, despite the fact that all of the lesser bosses reset. We attempted this again last night once lockouts were up, and the same bug occurred.

**Comment by TheOctagon322** [comment]
Still bugged

**Comment by IxanderousI** [comment]
just happened again today

**Comment by MaxHayman** [comment]
Reproduced issue, found problem and implemented fix. Will be in next hotfix.

Will close and reference here #18186
