### ISSUE TITLE
Unable to login after a disconnection inside Warpblade Tunnels

### ISSUE THREAD

**Issue by Treadwin** [WarEmu/WarBugs#18123]
**Expected behavior and actual behavior:**

The expected behavior: After a disconnect I should be able to log in again. And finish the dungeon with my group. 

It is the second time I've encountered this problem. I'm inside Warpblade Tunnels and then suddenly getting disconnected and being unable to login again. Not even other characters. Last time this happened I went away from the computer, for like an hour or so, and when I came back, I could enter the world again. 

**Steps to reproduce the problem:**

I couldn't tell.

**Testing Screenshots/Videos/Evidences (always needed):**

![warpblade](https://user-images.githubusercontent.com/75035679/100257582-5d08b500-2f46-11eb-8c51-82ada47f18ef.jpg)

Here's a picture of an odd loading screen. It's the same as last time I encountered this.

**Comment by yamyam318** [comment]
try to enter /stuck 2-3 times during loading screen, sometimes it helps. if not your toon is bugged in dungeon and you must ask gm to help you. same issue when you log out in dungeon.
