### ISSUE TITLE
[PQ]The Norse are Coming! Can't burn Norse tents

### ISSUE THREAD

**Issue by xpander69** [WarEmu/WarBugs#18125]
**Expected behavior:**
I think you should be able burn the tents either by clicking on them or getting torches from boxes/barrels near tents

**Current behavior:**
Stage 1 stuck
Norse tents burned 0/4  - doesnt work.
Clicking on the boxes or tents doesn't give any items like torches or similar and doesn't do anything. PQ is stuck on stage 1

**Steps to reproduce the problem:**
Go to the PQ. Do all the other tasks and try to click the Tents and boxes

**Testing Screenshots/Videos/Evidences (always needed):**
![](https://cdn.discordapp.com/attachments/243681954329919488/781232051063095326/ss-20201125-TAH4B.png)
![ss-20201125-Tpen0](https://user-images.githubusercontent.com/1345116/100272280-8126bf00-2f63-11eb-894e-5cb6d8b61e20.png)

**Comment by Lheana** [comment]
Have you tried attacking it?

**Comment by xpander69** [comment]
![ss_25112020_21 45 50](https://user-images.githubusercontent.com/1345116/100274738-a289aa00-2f67-11eb-8c59-3025137bf2bc.png)
not attackable by abilities, nor autoattack
