### ISSUE TITLE
Ch. 22 bug's

### ISSUE THREAD

**Issue by GimmiMoar** [WarEmu/WarBugs#18135]
Hi All, 

We just did a chapter 22 run. We were unable to complete the one for Caledor. The orbs would not spawn in the final phase for us to click on. 

The portal in the Chaos Waste Ch. 22 did not spawn correctly, some could see it, and some could not. 

Thanks!

**Comment by MaxHayman** [comment]
Should be fixed. Please reopen if you have further issues.
