### ISSUE TITLE
Squig Herder Tastes like Chicken 

### ISSUE THREAD

**Issue by NSKaneda** [WarEmu/WarBugs#18130]
Reworked Tastes like Chicken skill on 100% health applies wounds buff (wounds increase) but not heals - one has to wait for out of combat regeneration to cover 160 wounds increase. 
If the player HP value is below 100% (99% -) the healing is instant and compliments wounds buff.

Tested in orvr and pve, in and out of combat.

**Comment by grunbag** [comment]
Fixed already
