### ISSUE TITLE
Excessive Experience gained when completing a PQ

### ISSUE THREAD

**Issue by tog89** [WarEmu/WarBugs#18133]
**Expected behavior and actual behavior:**

Multiple levels were given when in excess of 8 million xp was given with the successful completion of the Alter of Madness PQ in Empire Chapter 22

**Steps to reproduce the problem:**

Was in a party of three.  Level 40, Level 31, Level 36.  .  We completed all three stages of the PQ.  When the final stage was completed over 8 million xp was awarded so that the level 30’s became level 40 with multiple instances of the level up animation playing in succession.

Event occurred after latest patch at 16:46 CST (GMT-6)

**Testing Screenshots/Videos/Evidences (always needed):**

![Tag_000](https://user-images.githubusercontent.com/38359697/100488138-0334f600-30d2-11eb-96d3-68af6d2ad973.jpg)

**Comment by kyraith** [comment]
This appears to be the result of clicking on any clickable object within the area of the PQ during the restart window

**Comment by tog89** [comment]
Tried again with a guild mate.  Have to be level 30+ as you need to get PQ credit.  After stage 4 and before it resets, right clicking an object award 44, 000 xp per click until PQ resets.

**Comment by aloghides** [comment]
This just happened to me in a PQ in Troll Country each time you click the one of the objects in the quest.

**Comment by carmine3161** [comment]
Can confirm, had the same issue being in a party and one of the members clicking on an object in the restart downtime of the PQ, instantly got a bunch of levels.

**Comment by Calaminth** [comment]
Same thing happened in Empire Chapter 12 PQ The Grisly Herd. I was NOT in a party and I'm not sure there's an object to click either, unless it counts clicking one of the destroyed totems in stage 2. In any case I didn't click anything after the PQ ended and still got tons of XP.

**Comment by Rexdale** [comment]
I've also experienced this in Nordland - Pillage and Plunder PQ
It would appear you do not need to be in a party, anyone at the PQ can trigger this for everyone in the area.

This particular PQ seems to stop providing XP (as described above) at level 15.

**Comment by dalen** [comment]
fixed
