### ISSUE TITLE
(Squig herder) New "scrablin' Quick-like" tactic  is decreasing pet speed instead of increasing.

### ISSUE THREAD

**Issue by Torete-war** [WarEmu/WarBugs#18137]
New Squig herder "scrablin' Quick-like"isn't working as intended, instead of increase the pet speed, is decreasing the pet speed by 50%.

Tooltip says:
"increase your pet movement speed by 50%"

Log in any squig herder, equip tactic and sent to attack a target... the pet moves even slower than it moves withouth tactic.

Just log in your squig herder and test it.

**Comment by grunbag** [comment]
Fixed
