### ISSUE TITLE
Engineer's Gun Turret does not have ability bar.

### ISSUE THREAD

**Issue by SudoKaname** [WarEmu/WarBugs#18134]
I tried 3 different turret and only Gun Turret does not have ability bar. Also after use gun turret I got 1630HP buff. Is this new buff or bug?  3 png check different please.
![1](https://user-images.githubusercontent.com/62230756/100488461-63c93080-30dc-11eb-9b2b-66f1da0a95e1.png)
![2](https://user-images.githubusercontent.com/62230756/100488469-6cba0200-30dc-11eb-8365-1c1b646c10f8.png)
![3](https://user-images.githubusercontent.com/62230756/100488472-6f1c5c00-30dc-11eb-9df7-1dcf5a2adbf8.png)

**Comment by Killham** [comment]
Yep only gunturret gives it stats that it has from items to the engineer itself and have no ability on abilitybar.
