### ISSUE TITLE
(Squig herder) new tactic "Shootin Quicka" is making pet attack slower instead of faster

### ISSUE THREAD

**Issue by Torete-war** [WarEmu/WarBugs#18149]
The new "Shootin' Quicka" tactic that can be obtained 3 steps into the Path of Quick Shootin' it is slowering attack speed a 50% instead of increasing attack speed

Tooltip says:
"It will increase the Autoattack speed by 50% for both you and your pet as long as you have an active pet"

My squig herder pet is doing autoattack each 3 seconds with tactic equip and each 2 seconds withouth equip the tactic, tested in city dummies withouth any alteration of line of sigh,distance,etc

Screenshoots with tactic equiped (autoattacks each 3 seconds)
https://ibb.co/nQqSJpQ
https://ibb.co/zPkzqqK

Withouth equip tactic (autoattacks each 2 seconds)
https://ibb.co/J3yCXPB
https://ibb.co/TcXgPcF
https://ibb.co/qySvxS9

For pet's isn't buffing autoattacks speed, it is debuffing attack speed instead

**Comment by grunbag** [comment]
Fixed
