### ISSUE TITLE
(Squig Herder) Gas pet stoped working after patch, one of the abilities is not dealing damage in target

### ISSUE THREAD

**Issue by Torete-war** [WarEmu/WarBugs#18150]
The squig herder Gas pet stoped working as inteded, one of the abilities "spore cloud" instead of causing damage produces a negative heal number with overheal amount

Spore cloud should be dealing 440 damage in area 30 feet around target
https://ibb.co/SR7hWMT

Instead of dealing damage is producing some weird heal effect in combat log, with heal+overheal mensage
https://ibb.co/TMzmRpt
https://ibb.co/6Whq3hM

This is happening with or withouth new squig frenzy ability activates, isn't squig frenzy related... the pet simply isn't working as it should

**Comment by grunbag** [comment]
Fixed with next patch
