### ISSUE TITLE
[Squig Herder] Squig armor triggers GCD

### ISSUE THREAD

**Issue by Brutinho** [WarEmu/WarBugs#18155]
Confirmed by Grunbag that SA should not trigger GCD. It does not when going out but it does trigger GCS  when going in
![Gittens_196](https://user-images.githubusercontent.com/36603560/100529880-a7de3300-31b9-11eb-9082-cd5e6c160fbc.jpg)
![Screenshot_20201128-085922_Chrome](https://user-images.githubusercontent.com/36603560/100529882-b0cf0480-31b9-11eb-8db9-b9dfeec422b9.jpg)

.

**Comment by grunbag** [comment]
It’s not affected by GCD server side , seeing a GCD is a visual issue , I’ll try to fix it

**Comment by admaska2** [comment]
![sh2](https://user-images.githubusercontent.com/43276959/102221933-11ad4b00-3ee3-11eb-887c-054021bd589a.png)

Squig armor stance stil triggers the GCD.
The Gcd is invisible you canot cast a skill instantly after remove or cast the Squig armor.

Its not smooth like a mara stance swap

**Comment by grunbag** [comment]
Fixed with next patch
