### ISSUE TITLE
(Squig herder) Horned pet unable to be summoned on movement while in Squig armor

### ISSUE THREAD

**Issue by Torete-war** [WarEmu/WarBugs#18157]
The Horned Squig herder pet (melee one) was changed to be one sec casting time and could be casted while in movement during Squig armor form.

Since the patch, you need to stop 2 seconds and be static casting horned squig herder pet, even if you are in Squig armor

The correct value is 1 sec casting time and able to be summoned in movement while you are using melee Squig armor form.

**Comment by grunbag** [comment]
Fixed with next patch
