### ISSUE TITLE
(Squig Herder) Sneaky Git tactic doesn't work

### ISSUE THREAD

**Issue by jennahazee** [WarEmu/WarBugs#18159]
Sneaky Git tactic "While you're in squig armor, your defences are increased by 10%" doesn't work.
Additional parry/dodge/disrupt doesn't show in stats. Confirmed by many squigs.
![1](https://user-images.githubusercontent.com/75200130/100537459-f03d3580-3239-11eb-9b0e-88f870e481af.jpg)

**Comment by grunbag** [comment]
You don’t seems to be in Squig armor

**Comment by jennahazee** [comment]
> You don’t seems to be in Squig armor

Updated a screen.
![1](https://user-images.githubusercontent.com/75200130/100552579-3970a200-3299-11eb-890a-c575c0114ebe.jpg)

**Comment by grunbag** [comment]
Type .get stats

**Comment by jennahazee** [comment]
> Type .get stats

I've tried it several times already with different results.
1st screen, no tactics (is it supposed to show 0 on everything, when it is clearly not 0?):
![1](https://user-images.githubusercontent.com/75200130/100654069-5ae59280-335a-11eb-8075-aea19a97e6e4.jpg)

After speccing and equiping Sneaky Git I still have no result, ever tried zoning to different zone with it (and yes, i've typed .getstats each time again
![2](https://user-images.githubusercontent.com/75200130/100654332-ac8e1d00-335a-11eb-9a60-01b41efa956f.jpg)
)

However, after relogging with tactic equipped i see a 10% total here. Does it mean it works only after relog?
![3](https://user-images.githubusercontent.com/75200130/100654472-e6f7ba00-335a-11eb-9c85-208408f8e724.jpg)

And i'm getting the same 10% from .getstats with no tactic equipped and no squig armor until i'll relog again.

**Comment by grunbag** [comment]
Fixed with next patch
