### ISSUE TITLE
(Squig herder) Gas pet ability "Good shootin" dealing less damage that tooltip shows

### ISSUE THREAD

**Issue by Torete-war** [WarEmu/WarBugs#18151]
Gop shootin, Gas squig herder pet ability is dealing lower amount than tooltip says,

The ability should be doing 391 base damage
https://ibb.co/6nW9gXc

The ability is doing lower damage than intended in city dummies with 0 armor-mitigation (337damage)
https://ibb.co/4mv4FXL

This issue happening without tactics equiped for avoid problems in tooltip description aka the stats tactics were not causing the issue... there is some bug with stats not taking into account on target hits.
https://ibb.co/dtCTk7J

**Comment by grunbag** [comment]
Tooltip are scaling with player stats instead of pet stats that’s why t show highest value , but it’s wrong value . We can’t fix this client side yet
