### ISSUE TITLE
(Squig herder) the new "Da waaagh iz Strong" tactic isn't causing any damage.

### ISSUE THREAD

**Issue by Torete-war** [WarEmu/WarBugs#18153]
The new tactic effect "Da waaagh iz strong" that deals damage in the person that you dotted with Rotten arrer heal debuff when anyone heal him, is not doing anything in my combat log

The new tactic should proc damage when someone heals the target that you doted with rotten arrer heal debuff, but yesterday in 5 hours of gameplay i didn't seen a single damage hit in my combat log.
https://ibb.co/WsmP8kH

i don't know where is the problem with this tactic, but it is not appearing in combat log in a space of 5 gameplay hours betwen scenarios and rvr.

**Comment by grunbag** [comment]
It works for me .

**Comment by Torete-war** [comment]
> It works for me .

In what combat log, attacker or only defender? i have everything turn on in combat log, even when someone heals my target with a rotten arrer going on him, there isn't any tactic damage proc on him.

The damage is only appearing in the order character suffering the damage? or should appear in destruction combat log from the person that casted the rotten arrer + da waaagh iz strong.

Because right  now it is not appearing in destruction combat log, i tested today other time today.
