### ISSUE TITLE
(Squig herder) Spiked pet ability doing half damage than tooltip says

### ISSUE THREAD

**Issue by Torete-war** [WarEmu/WarBugs#18152]
The Squig herder pet ability poisoned spine is doing half of the damage that tooltip says it should be doing

This is the tooltip and the damage it should be doing, withouth stats tactics to avoid causing any conflict in the ability damage description. (1065 damage over time in a space of time of 5 ticks in 5 seconds)
https://ibb.co/RGnqrGp

The reality is that the ability is doing  495 damage over time in a space of time of 5 ticks, 99 base damage per tick with no amor and zero mitigatión in city dummies.
https://ibb.co/wLmMRyx

The damage diference is more than half the damage that ability should be doing...

This test has been done withouth any tactics or squig frenzy ability going on, for avoud causing issues with the tooltip descriptión.
https://ibb.co/WvTzfYt

**Comment by grunbag** [comment]
Same as goop shootin
