### ISSUE TITLE
(Squig herder) Squig herder autoattack

### ISSUE THREAD

**Issue by Torete-war** [WarEmu/WarBugs#18158]
The Squig herder range autoattack is set to 90 feets range, one of the benefits of using Gas squig is a 10% bonus range.

But autoattacks isn't affected by that Gas squig 10% range bonus, when you summon Gas pet, the autattacks range remains at 90 feet.

Autoattack range withouth Gas squig:
https://ibb.co/sH4bztC

Gas squig bonus:
https://ibb.co/vv6mrzS

Autoattack with Gas squig up:
https://ibb.co/Q6ftBTj

This same issue happend too with shadow warrior and the instance that grant them 10% more.

**Comment by grunbag** [comment]
Gas squig increase Abilties range , not Auto attack range
