### ISSUE TITLE
(Squig Herder) Exploding Arrer dosent works / Tactic Aimin'Quickly disables all the times.

### ISSUE THREAD

**Issue by Snowiy** [WarEmu/WarBugs#18165]
Path of Big Shootin’
- Explodin’ Arrer :  Explosin Arrer dosent works! :( 0 DMG Level 1 Mob  Also got a 20s Timer and not a 10s Timer :/

Path of Big Shootin’
- Tactic Aimin'Quickly also dosent works prober... the buff always disappears when i join Scenarios or RVR... Only switch Tactics can reset the timer correctly.

**Comment by Snowiy** [comment]
Ok, the Exlodin'Arrer Bug  generating a message:
_Ability Modifier Error: Eplodin'Arrer
(1833) modifier Entry; 2743, Affecting: 1833, Id: 1, Command: (100,0): Missing DamageInfo_

**Comment by grunbag** [comment]
Explodin Arrer fixed with next patch
