### ISSUE TITLE
WL- Trained to threaten toolkit not displaying correct info

### ISSUE THREAD

**Issue by Sundowner1** [WarEmu/WarBugs#18178]
Trained to threaten skill toolkit says 5% increase in crit chance if you are at enemy's side or back, but skill icon as buff displays it as just increase in crit, same with the info shown in character panel, in melee crit chance 5% is added to the crit chance

![image](https://user-images.githubusercontent.com/72624493/101079579-1c054600-35c1-11eb-9b6f-f55d2bdcef3b.png)
![image](https://user-images.githubusercontent.com/72624493/101079600-20c9fa00-35c1-11eb-8f3b-a7e6aed9add8.png)

**Comment by grunbag** [comment]
What is the issue ?

**Comment by grunbag** [comment]
Added as long as you’re at your target side of back to buffline
