### ISSUE TITLE
Career Trainer in Bastion Stairs was hostile (red)

### ISSUE THREAD

**Issue by emailkook** [WarEmu/WarBugs#18170]
**Expected behavior and actual behavior:**

Career Trainer supposed to be be useable and not hostile/aggressive in Bastion Stairs entrance..

**Steps to reproduce the problem:**

We zoned in and he was red to everyone and started attacking when we got close. We were able to kill it and didn't respawn.

Happened on 8:30pm CST 11/30/20

**Comment by tog89** [comment]
Happened last night on order to our group.  Also did not respawn during full run.

**Comment by kyraith** [comment]
Did not see a career trainer on my run, just the renown trainer. Maybe my group already killed him?
