### ISSUE TITLE
Archmage - Magical Infusion

### ISSUE THREAD

**Issue by Joiec** [WarEmu/WarBugs#1817]
Archmage Skill "Magical Infusion" have 2 second animation, I may be wrong, but from what i remember it was not like that on live. The Shaman equivalent "Shrug It Off" have only 1 second animation, while Shaman can use any Ability right away after the GCD, the Archmage is stuck in further animation and is not able to use any Ability for another 0.5 Seconds. Been stuck in a 2 second animation after using an "instant" Ability is ridiculous.

**Comment by magter3001** [comment]
It's suppose to be instant cast for both abilities...

**Comment by Joiec** [comment]
Maybe i described it not good enough, my english is by far not perfect.
Both Skills "Magical Infusion" and the Shaman equivalent "Shrug It Off" are wroking as intended and are "instant" aka do apply the buff shortly (like 0.5s) after using the Skill. The only difference is that AM "Magical Infusion" uses wrong animation (duration is too long) which prevents AM from been able to use next Ability after the global cooldown ends, instead AM have to wait another 0.5s till the animation finishes. Shaman do not suffer from this, as their animation duration is just 1 second long.

**Comment by Evildoor** [comment]
Tested on dev server, found nothing besides a visual problem. Animation can be annoying, but you can ignore it and press next skill right after GCD. This may screw up animation of that next skill, but mechanically everything works, as far as i've tested.
It is true that animation makes no sense, however, i don't know if it was the same on live or not. Anyone has video?

**Comment by noisestorm** [comment]
IIRC the animation was the same that the HoT spell from AM is using. told aza some time ago, but thats really absolutely low prio

**Comment by Joiec** [comment]
Just retested, yea mybad the visual just tricked me, mechanically everything works fine. I found an old video with an AM using it, on the video it has the "ressurecting" (Gift of Life) animation. https://www.youtube.com/watch?v=hKqXFDPHrQU
1:30-1:31 start of the ability 1:32 ability buff applies exactly when gcd finishes (this is even worse than ror, on ror the buff applies shortly after using the ability which is much much better)

**Comment by Evildoor** [comment]
Hmmm, res animation does not makes much sense either, since both it and current animation are long and are mostly used for spells when you stand and cast. I do believe it should be changed to HoT animation or something like that. But yeah, low priority anyway.

**Comment by ozarmidrashim** [comment]
Animation cannot be changed.
