### ISSUE TITLE
[T4 Epic Quest The Ebon Flame]  ULTRA ANNOYING BUG!!!!!

### ISSUE THREAD

**Issue by Devilot77** [WarEmu/WarBugs#18177]
**Expected behavior and actual behavior:**

Did the entire quest, killed the keepr of the ways, inspected his key, teleported through one orb, then another orb and killed the final high elf of the Jadeheart bloodline. That's the last bit of the epic length quested!
https://wiki.returnofreckoning.com/index.php/Dark_Elves_T4_Epic_Quest_The_Ebon_Flame

**Expected behavior**

At this point the orb of power is meant to appear in your quest items. Yuo click it and quest is done (after speaking to a dark elf in ch 22 wc etaine). 

**Actual behavior**
No orb appeared in the quest items. Quest vanished from my tome and cannot even be reselected. 

**Steps to reproduce the problem:**

Killed those NPC's over and over (last Jadeheart and Keeper of the ways but orb of souls never appeared). Tried to start quest again but no longer selectable in DW ch 18 Dark Elf warcamp where it begins

**Testing Screenshots/Videos/Evidences (always needed):**

N/A as there is no quest anymore to ss :/

If fixable can I ask to not have to repeat all those steps again please...

Many thanks.

**Comment by Lheana** [comment]
What is the name of your character?

**Comment by Devilot77** [comment]
Devilot, Sorceror

Ty for your help x

**Comment by Lheana** [comment]
In these cases **you need to talk to the last NPC that gave you one step of the quest line**. In your case, this is Telior Windseer at the Dark Elf Chapter 22.

**Comment by Devilot77** [comment]
Many thanks
