### ISSUE TITLE
Item Keeper's cowl Broken Texture for female Zealot

### ISSUE THREAD

**Issue by Hadzi-user** [WarEmu/WarBugs#18176]
**Expected behavior and actual behavior:**
Expected behavior: The hairstyle should be hidden when you put the hood "Keeper's cowl" on a female Zealot character.
Actual behavior: The hairstyle does not hide and it breaks through the texture of the hood of the female Zealot character

**Steps to reproduce the problem:**
Put the "Keeper's cowl" on a female Zealot character.
Notice: I can't check how is it work with male character, so I report only about female character. 

**Testing Screenshots/Videos/Evidences (always needed):**
![Hetely_039](https://user-images.githubusercontent.com/69014772/100918630-c9a52600-34e9-11eb-82d9-52e79c6aae26.jpg)

**Comment by Kaelang** [comment]
Unfortunately this can happen with some items, it's not necessarily something that's easily fixed on a case by case basis but I'll keep this up incase.
