### ISSUE TITLE
Squig Herder Shootin Quicka tactic doesnt increase pet AA

### ISSUE THREAD

**Issue by Noronn** [WarEmu/WarBugs#18182]
**Expected behavior and actual behavior:**
Shootin Quicka should reduce your AA speed and pet AA speed by 50%. It only works on the player right now, but not on the pet.

**Testing Screenshots/Videos/Evidences (always needed):**

![Squig AA](https://user-images.githubusercontent.com/29786661/101261053-85599600-3734-11eb-83f8-83678a5b18e7.png)

red line is when tactic got switched in

**Comment by emailkook** [comment]
SH “pets” are doing 3-4000 damage alone in one second right now with m1 and you wanna to buff them more. Yup wait for this fix buddy. 
![32CC8697-447D-45FA-8C61-EADECE67E494](https://user-images.githubusercontent.com/50253609/101309874-00917980-3813-11eb-8d8b-67a17bb41996.jpeg)

**Comment by emailkook** [comment]
Let the devs nerf the overtuning that was done before saying your class killing players in 2-3 seconds is too slow.

**Comment by Noronn** [comment]
I swear you people even come to the bugtracker and whine. Can you please take your whine to the forum and make suggestions as you see fit? Its a bug so a report on the bugtracker is what is supposed to happen "buddy". Maybe people on the forum are willing to give you tips how to not get oneshot by a pet. GL.

**Comment by emailkook** [comment]
It’s not a bug what’s reported. Just on the tactic giving 25% armor pen is
working on all pet attacks. Supposed to be on the user only just like the
tactic.

**Comment by emailkook** [comment]
> I swear you people even come to the bugtracker and whine. Can you please take your whine to the forum and make suggestions as you see fit? Its a bug so a report on the bugtracker is what is supposed to happen "buddy". Maybe people on the forum are willing to give you tips how to not get oneshot by a pet. GL.

Adjustments on the morale 1/removal and bug with Armor pen tactic working for the pet is already coming after discussion, this is just someone thinking it’s not working when the pet is already double hitting and every second. Would want 0.5 second hits with 50% AA? Lol

**Comment by Noronn** [comment]
Good for you. What exactly does it have to do with the reported bug though? Can you just fuck off to the forums and stop derailing a perfectly fine bug report for a tactic that doesn’t work as the tooltip reads? If it’s too strong it will get changed, if not at least they have the chance to fix it.

Keep the whine to the forum and only contribute here if you have an actual contribution to the bug itself or how it works.

**Comment by emailkook** [comment]
And my screenshot literally showed auto attack is working fine and wasn’t a
troll picture. Spined fling and other attacks hitting every second instead
of every 2 seconds. Try swapping tactic bars and back. Working fine for
others. So it’s part to counter your report.

**Comment by Noronn** [comment]
There is literally not a SINGLE auto attack in your screenshot xD can you stop trolling please?
If you think spine fling tick interval is off make your own bug report? (It isn’t by the way, you just got hit by spine fling while frenzy was up on the pet so it’s 3 hits in 1.5 secs instead of 3 secs)
Also poisoned spine has always ticked every second instead of every 3sec on ROR so this part of the screenshot is working right as well.
If you actually bothered to read tooltips and do some simple maths you wouldn’t need to post this bullshit here.

But I guess that’s too much to ask if you can just whine. Just stop commenting, every comment you add shows that you a) don’t bother testing b) don’t know how the skills actually work and c) have no idea what my bug report is actually about. Thank you.

**Comment by Kaelang** [comment]
> SH “pets” are doing 3-4000 damage alone in one second right now with m1 and you want to buff them more. Yup wait for this fix buddy.
> ![32CC8697-447D-45FA-8C61-EADECE67E494](https://user-images.githubusercontent.com/50253609/101309874-00917980-3813-11eb-8d8b-67a17bb41996.jpeg)

Don't bring balance concerns onto the bugtracker.

**Comment by grunbag** [comment]
It’s fixed
