### ISSUE TITLE
Eternal Black Serissa Seed disappears

### ISSUE THREAD

**Issue by yamyam318** [WarEmu/WarBugs#18188]
**Expected behavior**
Eternal Black Serissa Seed should stay in bag.

**Actual behavior:**
Eternal Black Serissa Seed disappears randomly after some days.

**Steps to reproduce the problem:**
Get Eternal Black Serissa Seed. 
Let some days pass and wait till it disappears.

**Testing Screenshots**
![Udut_093](https://user-images.githubusercontent.com/61079266/101289318-ff088700-37fb-11eb-8786-dcec744c619a.jpg)
![Udut_094](https://user-images.githubusercontent.com/61079266/101289351-27908100-37fc-11eb-9ba4-8d7df658ec1d.jpg)

**Comment by Kaelang** [comment]
Already listed issue.
