### ISSUE TITLE
Warrior priest Str pot and sigmars fist dont stack 

### ISSUE THREAD

**Issue by jusva321** [WarEmu/WarBugs#18185]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by jusva321** [comment]
you shoud steal 120 str from using sigmars fist on a enemy but if you have a str pot up value 80 you only get 40 more 

put a pot up hit a target with sigmars fist

**Comment by jusva321** [comment]
![1](https://user-images.githubusercontent.com/72552430/101399493-d782ee80-38cf-11eb-917e-735f8c810fdc.PNG)
![2](https://user-images.githubusercontent.com/72552430/101399506-dd78cf80-38cf-11eb-8cb2-027366300b9a.PNG)
![3](https://user-images.githubusercontent.com/72552430/101399513-dfdb2980-38cf-11eb-8a24-24ba2256ef1d.PNG)
![4](https://user-images.githubusercontent.com/72552430/101399530-e4074700-38cf-11eb-8b47-4962dadd1376.PNG)

**Comment by jusva321** [comment]
1 no pot base str 
2 pot + 80 str 
3 sigmarsfist + pot 80 str 
4 what sigmars fist shoud do 
so i am missing 80 str from it

**Comment by yuaa2** [comment]
its not a bug, all stats cannot stack in this game
