### ISSUE TITLE
Runepriest - Tactic "Ancestor's Echo" not working [sorry, is working actually]

### ISSUE THREAD

**Issue by Fluffmonster** [WarEmu/WarBugs#1818]
Hello,

this tactic from the rp (mastery slot 11) is still not working. I was speaking to Aza once and he said that this stuff "should" work. But apparently it still does not.

I would really like to test this tactic / use it and in upcoming t3 it might be a useful alternative.

![324234234324234](https://cloud.githubusercontent.com/assets/15823173/11130239/3f549b90-8984-11e5-960e-473c134155a0.jpg)

Greetings,

Fluffmonster

**Comment by ozarmidrashim** [comment]
Tried it and it does work - it just doesn't seem to proc as often as it should

**Comment by Fluffmonster** [comment]
Hum, I did not get a proc the times I tried it.

**Comment by Fluffmonster** [comment]
Okay, sorry guys, it's working indeed. I don't know if it does proc correctly but maybe I can test it later.

**Comment by Fluffmonster** [comment]
Okay, just had the time to test the proc chances (on a small scale):

26 out of 100 trys. So all seems to be working perfectly. My bad, delete this topic, who can. :)
