### ISSUE TITLE
[Public Quest] Thanalord Forest - High Elf Ch2

### ISSUE THREAD

**Issue by Renanpg** [WarEmu/WarBugs#18180]
Bug in Public Quest "Thanalord Forest" in High Elf Chapter 2
Stage 2 can't be completed cause the dryads can't be rescued.

It asks to "Free the crippled dryads" yet we can't interact nor do anything with said Dryads NPCs, making it impossible to get this Public Quest past Stage 2. 

I believe we should be able to interact with these npcs and free them somehow. There is no other object like chains or cages to interact, just the NPCs. Killing every single enemy around them also does nothing. Tryed multiple times.

I've got to this PQs Stage 2 multiple times, with multiples high elf characters, but i didn't know how to report a bug until now. That made me think it's not a new or eventual bug, it's been here for at least 2 weeks, when I started playing.
 
Here is a screeshot of me trying to interact with the dryads to no success. 

![Screenshot_1](https://user-images.githubusercontent.com/53094919/101210551-6be11d00-3654-11eb-91f6-dcdce834ca12.png)

Thank you!

**Comment by kyraith** [comment]
You do not interact with the dryads to get past this stage. There is a chain manacle around their feet that is connected to a stake in the ground between them. That is what you interact with.

**Comment by Renanpg** [comment]
Oh, I see. Thank you. I really thought I has tried everything. Sorry for bothering you guys. Thx again.

________________________________
