### ISSUE TITLE
Gunbad right Masta Mixa disappeared

### ISSUE THREAD

**Issue by Lerilla** [WarEmu/WarBugs#18186]
Hello,

when you die in Gunbad right by Masta Mixa and run into his champer, he disappeared.
Make the grp new, leave Gunbad doesnt fix it
![Aelafynn_062](https://user-images.githubusercontent.com/16804997/101282077-239c3900-37d3-11eb-9de1-2075b13db9f7.jpg)
![Aelafynn_061](https://user-images.githubusercontent.com/16804997/101282080-2ac34700-37d3-11eb-930a-6ce0a3b6c1c4.jpg)

**Comment by MaxHayman** [comment]
Reproduced issue, found problem and implemented fix. Will be in next hotfix.
