### ISSUE TITLE
[SH] Squig Frenzy doesn't enhance pet abilities anymore

### ISSUE THREAD

**Issue by Noronn** [WarEmu/WarBugs#18194]
**Expected behavior and actual behavior:**
As of the patch on 09/12/2020 the squig frenzy ability doesn't enhance the specific squig pet abilities anymore. (It only increases dmg by 25%).

**Testing Screenshots/Videos/Evidences (always needed):**

![Slesu_018](https://user-images.githubusercontent.com/29786661/101697011-54040180-3a77-11eb-88b9-3b93067d30c6.jpg)
On spiked squig for example the tick interval is not being increased by 50% while under the frenzy buff.
Other pet abilities (Horned squig, Gas Squig, Regular Squig) are also not being enhanced but I didn't take screenshots. Can add if you want.

**Comment by jennahazee** [comment]
Can confirm.

**Comment by grunbag** [comment]
Fixed with next patch
