### ISSUE TITLE
WP 2h parry strikethrough 10 bug

### ISSUE THREAD

**Issue by yoluigi** [WarEmu/WarBugs#18198]
When i equip a 2h i get a 10 seconds buff for a 10% block/parry strikethrough but only last 10 seconds instead of alwas been on.

**Comment by dalen** [comment]
This was set wrong on the hammer "Faith", was that the one you tested with?

**Comment by yoluigi** [comment]
On all weapons here an example when  equip my weapon.
![Yoluigi_018](https://user-images.githubusercontent.com/75797970/102248026-b5d8c700-3ece-11eb-94f6-713b272e7921.jpg)

a 10 seconds buff when you equip when it should be a passive.
after the 10 seconds you can see on chat i miss that 10% parry/block strikethrou...
![Yoluigi_019](https://user-images.githubusercontent.com/75797970/102248136-d4d75900-3ece-11eb-8f22-9ef83c30f4f0.jpg)

**Comment by yoluigi** [comment]
i meant on all 2h weapons fortress, sledge, the t4 epic quest ones.

**Comment by yoluigi** [comment]
Is it possible to open this again the problem is still the same missing 10% strikethrought or this one (same problem) https://github.com/WarEmu/WarBugs/issues/17020
