### ISSUE TITLE
Lost item

### ISSUE THREAD

**Issue by Apoztel** [WarEmu/WarBugs#1819]
I have lost my Shoulders of the weird on my Blackguard the same time as the Scenario weapons/shields got abit bugged and switched from Career: Blackguard to Ironbreaker. Should I contact a GM about it?

BG name: Apozter

**Comment by Evildoor** [comment]
Item loss is a known bug which has no solution so far. Dev policy is "no refunds" for now, so the only thing you can do is hope that with server restart items will return. If they don't - tough luck, but that's how it stands.
