### ISSUE TITLE
Purgatory Causes Client Freezes and Crashes

### ISSUE THREAD

**Issue by iantheace** [WarEmu/WarBugs#18193]
**Expected behavior and actual behavior:**

Expect yo use purgatory anti Rez on witch hunter and WE without crashing/lagging the client.

**Steps to reproduce the problem:**

Use purgatory.

I have provided evidence on a 16 core 5.1ghzx ryzen 5950x with an RTX 3090 on water/liquid metal so it is not an issue with my spec. You will notice everyone in disc moaning now and then when they cant detaunt  when the WH uses it without calling :).

**Testing Screenshots/Videos/Evidences (always needed):**

Theres about 20 examples in this video, but ive picked out 3 to make it easier at the times below:

9:07
7:13
24:43

you will hear in chat 'Using Purgatory' and then see it freeze, we coordinate morales with it, as they will be unable to do anything as they freeze. Note my client only freezes for 1-2 seconds but my team mates and enemies are freezing for 5 seconds or so quite often.

See the youtube video here

https://youtu.be/DbUXdfhnI-o

Note that game critical and game breaking bugs may award a manticore/griffon (realm specific) at the leads discretion however, asking for one instantly disqualifies you from this reward.
-->

**Comment by johnsmith534** [comment]
Having played against it yesterday can confirm it freezes for about 5 seconds.

**Comment by dalen** [comment]
Replacing the object for next patch with a different non-animated one, hopefully that fixes it.

**Comment by grunbag** [comment]
Does it get fixed with new models ?

**Comment by grunbag** [comment]
seems fixed
