### ISSUE TITLE
[Engineer] Turret buff not applying on character after deploying it a second time

### ISSUE THREAD

**Issue by IxanderousI** [WarEmu/WarBugs#18191]
When you use redeploy then spawn the same turret again, you lose the buff icon, meaning certain things that are dependant on active turret will not function such as tracer rounds.

As you can see, machine gun turret is not showing as active on character but stacks still are
![turret](https://user-images.githubusercontent.com/25346641/101605576-3e9cc200-39fa-11eb-976c-b0aadb1045eb.jpg)

Update
Seems to also happen when you just spawn the same turret again, buff goes but stacks remain.

**Comment by IxanderousI** [comment]
As you can see the machinegun buff is not on character, so tactics like tracer rounds won't be active as a result

**Comment by grunbag** [comment]
Is it fixed ?

**Comment by IxanderousI** [comment]
> Is it fixed ?

no it still does not apply the buff, example being bombardment turret will show then if you spawn it again because your redeploy is on cooldown, it will spawn the turret without bombardment turret buff on your character but you still gain stacks.

**Comment by grunbag** [comment]
I see buff stack on your screenshot , what buff is missing exactly ?

**Comment by grunbag** [comment]
The turret ?

**Comment by IxanderousI** [comment]
> The turret ?

yes i stated already that it is not the stacks the turret buff, so if you don't have that as active tactics like tracer rounds which require an active turret does not appear to show as active as well because i guess the game thinks you don't have an active turret, i posted the screenshot you can see it shows the stacks but not the machinegun turret icon on my character.

**Comment by grunbag** [comment]
Fixed with next patch
