### ISSUE TITLE
[ToK] History, Questing and Whacky unlocks not working / implemented ?

### ISSUE THREAD

**Issue by CrimsonFenris** [WarEmu/WarBugs#18197]
Some unlocks are currently missing/not awarded in the ToK :

**- Questing > Completed [25-5000] Quests** (noted as "not implemented" in wiki).

**- Career > Whacky > Used an Ability [100-10,000] times While unarmored**
**- Career > Whacky > Dealt [500-50,000] damage over career while unarmored**

Some "History & Lore" items for unlock cannot be found (Order side), so far : 

**- Ekrund : Oathbearers, Ancestor Worship, Durak Bitterstone.**
<details><summary>Clic for picture</summary>

![Ekrund_ToK](https://user-images.githubusercontent.com/40425011/101809408-d04e2180-3b17-11eb-8aae-f6d6793f4aa0.jpg)

</details>

Those 3 unlocks look non functional. According to another wiki, unlocks are :

**- Oathbearers : Speak to an Oathbearer (or Two) in the Pick&Goggles > currently not working (tried speaking to all of Oathbearers in the zone).**

**- Durak Bitterstone (44k, 20k): Top of the stairs at the base of the Big Doors.**
<details><summary>Clic for picture</summary>

![Ekrund_Durak_Bitterstone_44k-20k_NOT_WORKING](https://user-images.githubusercontent.com/40425011/101809614-0d1a1880-3b18-11eb-9253-9dc48a449b61.jpg)

</details>

**- Ancestor Worship (36k, 34k) : Approach the giant stone head right outside the Dwarf Chapter 1 Public Quest. The statue head is ringed by a short wooden palisade (like waist high).**
<details><summary>Clic for picture</summary>

![Ekrund_Ancestor_Worship_36k-34k_NOT_WORKING](https://user-images.githubusercontent.com/40425011/101809670-1d31f800-3b18-11eb-9ed7-9d4573627749.jpg)

</details>

**Comment by Lheana** [comment]
First of all, as noted when you create a ticket: **only one issue per ticket**.
Secondly, also as noted when you create a ticket, **you must verify the issues aren't reported yet**. Most of these issues are already reported, and if it's noted on RoR Wiki that it is not implemented yet, it means we know it is not working yet.
