### ISSUE TITLE
Squig Armor bug: melee abilities 

### ISSUE THREAD

**Issue by Rildetarma** [WarEmu/WarBugs#18196]
The new patch has introduced a bug for squig armor. I haven't figured out the trigger completely, but it seems while in squig armor, if/when switching tactics, one will have the range abilities suddenly activate, instead of the melee abilities (albeit one is still in squig armor). The fix is to jump out of squig armor, wait the cooldown, and jump back in, then the action bar becomes melee again.

**Comment by Rildetarma** [comment]
![Warts_009](https://user-images.githubusercontent.com/15988204/101887109-4458eb80-3b51-11eb-8d82-f83a60fb87c4.jpg)
Here is a screen shot.  You can see I am in squig armor, but only range options are showing as options, no melee, except Git Em.

**Comment by Rildetarma** [comment]
This can happen when first jumping into squig armor, or switching tactics while in squig armor, it seems.

**Comment by grunbag** [comment]
All tactic or specific one ?

**Comment by Rildetarma** [comment]
It seems to happen on a tactic switch.  Not any specific tactic, that I have noticed.   As noted above, it will also happen when one first goes into squig armor.

**Comment by grunbag** [comment]
Can’t reproduce on dev server , in both situation described it works fine . Wait for next patch maybe

**Comment by Rildetarma** [comment]
This bug happens at random, or when going into SA or changing tactics.  I'm not sure it's consistent though.  I suggest jumping in and out of SA a few times or changing tactics while in SA for a few minutes.  I get hit with this bug every time I am on.  If I stick with one tactic set, then things are fine.

**Comment by grunbag** [comment]
fixed with next patch
