### ISSUE TITLE
Massive FPS drop on only one character

### ISSUE THREAD

**Issue by Ysaran** [WarEmu/WarBugs#18204]
**Expected behavior and actual behavior:**
When I play with my shaman my FPS drops under 10, while playing every other character FPS are always over 25. In RvR/SC I have solid 2 or 3 FPS. The game is unplayable. I'm totally desperate. I use the very same set of addons, Buffhead list and Enemy set up. I tryied disabling all the addons and the FPS drop still happen. I tryied playing using differt internet connection and/or different PC and the problem still.

**Steps to reproduce the problem:**
Play with my shaman

**Testing Screenshots/Videos/Evidences (always needed):**
I've made a video to compare how FSP are while playing shaman and choppa in IC. You can only imagine how low FPS are when I join RvR or SC
https://youtu.be/deRt7nUdnBY

**Comment by Kaelang** [comment]
Steady FPS is 9 times out of 10 on your side.

If the FPS drops are caused by specific ability usage, we'd need to know which ones.
