### ISSUE TITLE
Bug to teleport with GUNBAD SCROLL

### ISSUE THREAD

**Issue by petocask** [WarEmu/WarBugs#18202]
Hello,

I have a big bug, yesterday and today, i will go to gunbad with a gunbad scroll but when charging map badlands i return at a screen of choice caractere.

After i test with a new caractere and is bloqued too... what is solution please

My Caractere is : Petokkaskk and petoccask (other player guild have a problem too)

**Comment by Kaelang** [comment]
Sometimes during load screens players can mini-crash. A restart usually fixes these issues.
