### ISSUE TITLE
SH the tactic He's A Biggun' doesn't work

### ISSUE THREAD

**Issue by admaska2** [WarEmu/WarBugs#18209]
Test done on Msh Vs the dummy 

A fresh pet was summon on evry test done.

The +160 str or the +160 Bs dont increase the pet damage.
I have no clue if the +160 wounds work to.

![Sh issue](https://user-images.githubusercontent.com/43276959/102159260-7769ea80-3e83-11eb-9274-c68d4d9558c1.png)

**Comment by grunbag** [comment]
Fixed with next patch
