### ISSUE TITLE
Word of Pain Critting For Over 6K (probably bugged)

### ISSUE THREAD

**Issue by Caduceus42** [WarEmu/WarBugs#18207]
Hello,

While I was roaming tonight I suddenly got a ludacris Word of Pain crit of 6606 damage. 

Not sure how this happened, but I'm assuming this is a bug. 

![Word of Pain Crit](https://user-images.githubusercontent.com/69918329/102024737-1ca59580-3d94-11eb-8e01-d3f5526e2a7f.png)

I was also recording, so if it is necessary I can share the footage. 

I wasn't able to replicate this bug on a target dummy. My highest crits were around 2.3k.

Thanks,

- Caduceus

**Comment by Haojun-Phalanx** [comment]
were you close to warcamp ? it might be warcamp buff.

**Comment by Caduceus42** [comment]
> 
> 
> were you close to warcamp ? it might be warcamp buff.

I was indeed quite close to a warcamp. I estimate about a 100ft from the nearest npc.

That could very well explain it.

**Comment by Lheana** [comment]
Indeed it is likely due to you being close to the warcamp, so I close it.
