### ISSUE TITLE
Leaving SC bug

### ISSUE THREAD

**Issue by fornicator** [WarEmu/WarBugs#1820]
had a group full of bots join a To Anroc scenario I was in.  After going from 100 point winning advantage to 12 losing, I decided it was a waste of my time and booked out.  Upon zoning into WC I was struck by lava until I died.  Everytime I res, I'm struck down again by lava damage.  

Edit: after scenario ended I stopped being killed by lava,

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
