### ISSUE TITLE
[Engineer] Turret will not deploy at characters location

### ISSUE THREAD

**Issue by IxanderousI** [WarEmu/WarBugs#18217]
Simply put, you spawn a turret and it appears at a fixed location and won't ever move from it unless you move very far away then the same happens at a new location.

As you can see in video, turret will not budge
https://www.youtube.com/watch?v=CEGlz2x-pVc&feature=youtu.be

**Comment by eTz-v-reDiahL** [comment]
also happening to magus pets

**Comment by Evilmariel** [comment]
seconded also happening with my magus pets as well

**Comment by geezereur** [comment]
Can confirm magus and engineer pets dont deploy at char locations or at all.

**Comment by Kaelang** [comment]
Does resummon work?

**Comment by IxanderousI** [comment]
> Does resummon work?

The last hotfix, actually fixed this issue, turrets are now working as intended, the only bug that i am aware that remains for turrets is this one.
https://github.com/WarEmu/WarBugs/issues/18191
