### ISSUE TITLE
The cloak with "Guild Heraldry" activated is incorrectly displayed for other players.

### ISSUE THREAD

**Issue by Syzako** [WarEmu/WarBugs#18213]
**Expected behavior and actual behavior:**

What I see:
![image](https://user-images.githubusercontent.com/39750677/102481337-b2536480-40b5-11eb-8228-be497db1bd0e.png)

What other players see:
![image](https://user-images.githubusercontent.com/39750677/102481744-40c7e600-40b6-11eb-988a-ef0b9e4b0393.png)

If the checkbox is switched to the OFF and returns to the ON, then the error is eliminated and other players see the cloak correctly.
![image](https://user-images.githubusercontent.com/39750677/102482007-acaa4e80-40b6-11eb-9c65-8faba5fc8af1.png)
![image](https://user-images.githubusercontent.com/39750677/102482589-905ae180-40b7-11eb-82d1-03916fed2c82.png)
![image](https://user-images.githubusercontent.com/39750677/102482007-acaa4e80-40b6-11eb-9c65-8faba5fc8af1.png)

BUT the error is returned after changing the zone.

**Steps to reproduce the problem:**

1) Create a character and start the game. 
2) View from the side by another character.

Career: Sorcerer

Back: Beastlord Cloak of the Skaven
Alternate appearance applied: "Show Guild Heraldry" checkbox
Dye: empty

**Comment by Denteron** [comment]
Hello/ You was trying reproduce it with other capes ?

**Comment by Syzako** [comment]
> Hello/ You was trying reproduce it with other capes ?

Hello, nope.

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/16348
