### ISSUE TITLE
Magus pet Resummon ability is not working.

### ISSUE THREAD

**Issue by Kymix21** [WarEmu/WarBugs#18210]
Like after previous patches, Magus pet ability Resummon is not working - pet doesn't move from location.

See two images below, one before and one immediately after using Resummon ability (it's on cooldown in bottom right corner), pet did not move.

![image](https://user-images.githubusercontent.com/60149182/102417077-ffa5d800-3fc8-11eb-9eb5-d18884ed99b4.png)

![image](https://user-images.githubusercontent.com/60149182/102417114-16e4c580-3fc9-11eb-9012-0043fc32c419.png)

**Comment by Kaelang** [comment]
Was this done prior to starting a logout?

**Comment by Kymix21** [comment]
I was logging out because of the bug and stopped just to grab screens of the issue real quick. However, the issue seems the be fixed since the hotfix that was a day or two after this.
