### ISSUE TITLE
AM Aoe detaunt

### ISSUE THREAD

**Issue by Vinfrid** [WarEmu/WarBugs#18216]
AM aoe detaunt (walk between worlds) doesn't work
![Xilophone_007](https://user-images.githubusercontent.com/76210368/102612610-191e5f80-4142-11eb-9be4-70188ef04ca0.jpg)

**Comment by Vinfrid** [comment]
Archimage aoe detaunt walk betwen worlds dont work properly. Enemy atack hit with full strengt  but imunnity setback work.

**Comment by Kaelang** [comment]
Can you highlight this outside the Arena? RvR or Scenarios etc.

**Comment by Denteron** [comment]
I tested it on oRvR and that true/ AOE dtaunt dont work/ I can use it on my enamy(s) but damage dont be redused/that 100%/

**Comment by emailkook** [comment]
Confirmed it doesn't work and tested it. Would add clip but file too big.
