### ISSUE TITLE
[Chosen] Warping embrace M4 damage not matching tooltip

### ISSUE THREAD

**Issue by The-DTT** [WarEmu/WarBugs#18211]
So I was fooling around with build and specced into the M4 of the Dread tree on Chosen.
Although generally the damage of this morale is way too low, the actual damage done does not match the damage the tooltip of the ability states.
I first saw it in open rvr and tested it again in pve, still with the same result. Damage stated in the tooltip is 461, the real damage done is 369. Since it's morale damage, there should not be any mitigation on the damage here.

![Panzerkasper_006](https://user-images.githubusercontent.com/47793577/102469817-7c7d9400-4053-11eb-8356-fdf95512ba0c.jpg)
![Panzerkasper_007](https://user-images.githubusercontent.com/47793577/102469828-81424800-4053-11eb-85ba-b83c29c613d8.jpg)

**Comment by Kaelang** [comment]
Tooltips aren't 100% accurate, more of a guideline - likely a tooltip issue.

**Comment by grunbag** [comment]
Fixed with next patch
