### ISSUE TITLE
The character selection menu displays the wrong character appearance.

### ISSUE THREAD

**Issue by Syzako** [WarEmu/WarBugs#18212]
**Expected behavior and actual behavior:**

The character selection menu displays the wrong character appearance.

The appearance of the character in selection menu:
![image](https://user-images.githubusercontent.com/39750677/102475439-f8a4c580-40ad-11eb-9021-0df24188f677.png)

The appearance of the character in the game, as I see it:
![image](https://user-images.githubusercontent.com/39750677/102475628-343f8f80-40ae-11eb-839e-a30799ee4a59.png)

**Steps to reproduce the problem:**

Create a character and start the game.

Career: Sorcerer

Body: Vanquisher Gown
Alternate appearance applied: Gateclaimer's Gown

Back: Beastlord Cloak of the Skaven
Alternate appearance applied: "Show Guild Heraldry" checkbox

Dye: empty

![image](https://user-images.githubusercontent.com/39750677/102477249-386cac80-40b0-11eb-8c76-3c6d7012c143.png)

**Comment by Denteron** [comment]
Sometimes that happens, that old bug but not critical. Game have alot of bugs and problem for fixing, and RoR devs team not so big for make it all. Better focusing on actual problem, u may check BT posts to see that.

**Comment by Kaelang** [comment]
This has been listed on another occasion.
