### ISSUE TITLE
Morale addon bugs default morale bar

### ISSUE THREAD

**Issue by Keptpet** [WarEmu/WarBugs#18222]
Hi i added the morale addon that lets you move morale icons individually, i since un-installed that addon but now my default morale bar is not showing & i cant place any morales in the default bar or even see it

**Comment by Keptpet** [comment]
i did click hide on the default morale bar while the addon was installed so i dont know if its just stuck on hidden i have  since un hidden the default morale tool bar but that didnt fix it

**Comment by Denteron** [comment]
Hello/ May u rty make somthing with ur other characters UI?
I mean u can share some UI from other(un bugget) characters or make new char. and share NEW fresh UI to main(char), and after customized for urself.

**Comment by Keptpet** [comment]
ill give that a try
