### ISSUE TITLE
Fort population numbers not correlating correctly

### ISSUE THREAD

**Issue by Malvaine** [WarEmu/WarBugs#18228]
Expected behavior: If there are only 92 defenders in a fort, a maximum of around 120 attackers are able to enter.
Actual behavior: Reikwald, ca. 9 pm (CET), 19.12.20 - from the beginning, 92 defenders facing 168 attackers.

![Aideana_002](https://user-images.githubusercontent.com/57098865/102700153-4f93d180-424b-11eb-868f-a82576e0e313.jpg)

**Comment by Haojun-Phalanx** [comment]
calculation is opposite,  there is only one limit for attackers which is 168. on the other hand, maximum defender numbers scales with attacker numbers.
