### ISSUE TITLE
Battle Brew Backpack: BOP on Destro & BOE on Order

### ISSUE THREAD

**Issue by DeadNerve** [WarEmu/WarBugs#18226]
**Expected behavior and actual behavior:**
Battle Brew Backpack should be the same for either side.

Currently on Destruction the Battle Brew Backpack is bind on pickup. While on Order side it's bind on equip. Because of this you'll see the backpack on the auction house for Order side but not on Destro side.

**Steps to reproduce the problem:**
Log to one side and loot the item from event giants.

**Testing Screenshots/Videos/Evidences (always needed):**
Destruction side:
![battlebrewbackpack-destroBOP](https://user-images.githubusercontent.com/76260478/102695536-04030880-41f6-11eb-929e-63a157892bb4.jpg)
![battlebrewbackpack-destroAH](https://user-images.githubusercontent.com/76260478/102695537-06fdf900-41f6-11eb-9d21-2fb27410a506.jpg)

Order side:
![battlebrewbakcpack-orderBOE](https://user-images.githubusercontent.com/76260478/102695549-10876100-41f6-11eb-9665-768616163da4.jpg)
![battlebrewbakcpack-orderBOUND](https://user-images.githubusercontent.com/76260478/102695552-11b88e00-41f6-11eb-8edd-2e63eed7cc01.jpg)
![battlebrewbackpack-orderAH](https://user-images.githubusercontent.com/76260478/102695555-141ae800-41f6-11eb-8785-5d84eac0f9cf.jpg)

**Comment by ka3vas** [comment]
Can confirm

**Comment by Lheana** [comment]
This has been fixed with today's patch.
