### ISSUE TITLE
Shaman Bloodlord 6th bonus

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#18224]
In description 4% more dmg but its only about 3.1%

buff off - 471 / buff on - 486 
![4](https://user-images.githubusercontent.com/13823154/102693171-f1e69180-4218-11eb-937b-ac841a82f40c.jpg)

**Comment by cimator** [comment]
Do you have any other damage buff active like divine fury? if so, that would explain it as damage buffs stack additively.
Lets say with divine fury %125 damage, and u would increase it to %129 with bloodlord bonus, which is roughly a %3.2 damage increase compared to having only divine fury. You should test it out with no damage modifiers.

**Comment by MKorin** [comment]
Ahh ok then its about 3.8% pretty close
