### ISSUE TITLE
[SH] Yer Bleedin'! has no cooldown

### ISSUE THREAD

**Issue by cimator** [WarEmu/WarBugs#18220]
As the title says, supposed to have 5s cd with the rework changes. Here is a vid(unlisted); https://youtu.be/R6atJukGZCc

**Comment by Kaelang** [comment]
Not influenced by any tactics?

**Comment by cimator** [comment]
SH doesnt have a tactic that reduces its CD

**Comment by grunbag** [comment]
Fixed with next patch
