### ISSUE TITLE
Get'n Smarter

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#18235]
Shaman 3th dot increase intel only by 22 not by 102
![1](https://user-images.githubusercontent.com/13823154/102806932-07e18700-43be-11eb-87df-69acc12f03e2.jpg)
![2](https://user-images.githubusercontent.com/13823154/102806937-0a43e100-43be-11eb-9db7-49c997e6e71c.jpg)

**Comment by Sixmoons48** [comment]
Looks like you got a int pot on which is most likely 80 int, which doesn't stack with ability, the ability overrides it to give you that extra 22

**Comment by MKorin** [comment]
Yea, thx
