### ISSUE TITLE
[Quest] 'Stairway to Oblivion' doesn't count the objectives

### ISSUE THREAD

**Issue by Andrey-Bulatov** [WarEmu/WarBugs#18231]
Order quest 'Stairway to Oblivion' in Bastion Stairs has 2 objectives: kill Feltharg Flesheater and speak with Einarr Storrason nearby. I killed Feltharg few times in different modes: solo, in full group with people without quest, in partial group with people who all have this quest. Killing doesn't count at all.

**Comment by Kabucoror** [comment]
fixed with next patch
