### ISSUE TITLE
Guild inviting 

### ISSUE THREAD

**Issue by Areanda** [WarEmu/WarBugs#1823]
Anyone in a guild can invite people..even if they are set that it shudnt be possible.

**Comment by Styrkarr** [comment]
Up.

Everyone in a guild can invite with the command /guildinvite <name>. Even if they don't have the right to invite.

Example:
I'm a simple member in my guild, i can't invite people (only officer and guild leader can).I don't have the button "Invite" in the guild panel, and i don't have the "invite in the guild" option when i right-click on the name of someone.
BUT i can invite him if i write in /s the command "/guildinvite <name>".

**Comment by Luth-RoR** [comment]
That was a workaround from ages ago, when no guild permissions worked at all. I think it's safe to deactivate it now.

**Comment by Neutrinoo** [comment]
This is still a problem.  Can the ability be shut off now for only those people that have authority to invite people to guild?

**Comment by sioding** [comment]
fixed with patch from 24.02.2018
