### ISSUE TITLE
Character (SW) Unable To Equip RvR Currency Main Hand Weapons (Swords).

### ISSUE THREAD

**Issue by Xarlo** [WarEmu/WarBugs#18245]
**Expected behavior and actual behavior:**

Well as the title states my character is a level 31 Shadow Warrior and is unable to equip the RvR currency weapons akin to the Main Hand "Sword" slot, I can use the Bows, just not the swords.
Even if I search the RvR currency vendors, the Swords won't naturally pop up in the vendor list as usable equipment I have to filter for unusable equipment to even find them and purchase them; even though I won't be able to use them.
I can however use the swords purchased with gold from the renown gear merchants, but those are the only ones.

The only reason it states that I can't use the weapons is because it is a sword..?

Something that may / may not help identify the issue is I don't know the exact date when my character was made, but it was some time after the Assault SW changes, but before the Ranged changes. 
I leveled the SW to a 16 and even had the level 10 RvR Recruit emblem weapon equip. (fast forward quite a while since I took a break) (Year or so break) I logged back into the character after the Ranged SW buffs were implemented, and the recruit weapon was in my inventory unable to be equip due to the red "Sword" name. So sometime in between those patches I'm guessing one of them broke my character..? Which is weird because it has only happened to me... That I know of.
 

**Steps to reproduce the problem:**

I believe it to be an isolated condition and my character is just bugged as I'm the only one this is issue is affecting... (That I know of)
If I examine other SW players they have the same weapons equip that I try to buy and use, but my character cannot.

**Testing Screenshots/Videos/Evidences (always needed):**

![Mysha_010](https://user-images.githubusercontent.com/76572377/103108069-4a9b9d00-4612-11eb-8148-0aaf7dd16a1a.jpg)
![Mysha_013](https://user-images.githubusercontent.com/76572377/103111108-6c4b5300-4617-11eb-8798-2d5d39c231ad.jpg)
![Mysha_012](https://user-images.githubusercontent.com/76572377/103111130-94d34d00-4617-11eb-99d8-ab9e7e41e50a.jpg)
![Mysha_009](https://user-images.githubusercontent.com/76572377/103111140-aa487700-4617-11eb-9ec0-4d5bd9223b69.jpg)
![Mysha_011](https://user-images.githubusercontent.com/76572377/103111145-bc2a1a00-4617-11eb-82e8-aaa87d906f2a.jpg)

**Comment by Lheana** [comment]
Do you have the same thing General Abilities?
![Lheasw_012](https://user-images.githubusercontent.com/11537611/103288449-2dd1e180-49e5-11eb-9726-c2b5beb0b0ee.jpg)

**Comment by Xarlo** [comment]
Ahhh. That would be it... I'm apparently a shield spec SW lol..

![Mysha_007](https://user-images.githubusercontent.com/76572377/103393137-36aeda00-4aef-11eb-8d40-02bf571cba6b.jpg)

**Comment by Lheana** [comment]
That is sad to announce, but the only way to fix it would be to create a new sw...

**Comment by Xarlo** [comment]
/Sigh I had a feeling that was going to end up being the result of this bug report, before I even filed it. Thank you though.
Since I have no character slots remaining, I'll have to delete this character in order to remake it. How long after deletion would I have to wait in order to reclaim the name back? Or is it instant?

**Comment by Lheana** [comment]
You'll need to wait for a patch, after the patches the names of the deleted chars are reset, so you should be able to use it after one.
