### ISSUE TITLE
The pass option for Trash in the loot auto roll menu does not work.

### ISSUE THREAD

**Issue by Neutrinoo** [WarEmu/WarBugs#18244]
**Expected behavior and actual behavior:**
You can select "pass" for trash in the auto loot menu and no trash will be added to your loot bag.

**Steps to reproduce the problem:**
Configure auto loot for "trash" to "pass".
Kill mobs that drop trash and you'll see it end up in your bag.

**Comment by lilimx** [comment]
Hey,

It's not a auto loot menu, it's a setup menu for your auto roll options when you're in a grp.
So I'll close this ticket now.

If your still the opinion this is a bug, please feel free and open a new tickt with your issue.
