### ISSUE TITLE
[Squig Herder] Range knockdown ability not benefiting from gas squig extra range

### ISSUE THREAD

**Issue by IxanderousI** [WarEmu/WarBugs#18242]
When using the gas the new ranged knockdown ability is not benefiting from extra 15ft, tooltip will show 80ft but when at 80ft from target it will simply start the cast but will not complete and result in ability cancelling itself.

**Comment by grunbag** [comment]
as you can see in combat log, i stand at 80 ft from my target.

without gas squig : 
![image](https://user-images.githubusercontent.com/24207191/103264107-03aefe00-49aa-11eb-8d40-c73f08c5d79a.png)

with gas squig 
![image](https://user-images.githubusercontent.com/24207191/103264124-132e4700-49aa-11eb-8aab-32ed07f173f7.png)
