### ISSUE TITLE
Squig armor stance bug

### ISSUE THREAD

**Issue by Akilinus** [WarEmu/WarBugs#18247]
**Expected behavior and actual behavior:**
You should be able to leave squig armor by pressing the stance again.

**Steps to reproduce the problem:**

https://youtu.be/zKEZsdsPv6w

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Sorkhatani** [comment]
Yep, and it is worse for sub 40's without Kaboom!. We have to actually log out to leave squig armor, as there is no other way to turn it off. Had to do that twice yesterday, then I just stopped using the ability..

**Comment by grunbag** [comment]
fixed already
