### ISSUE TITLE
Game is trying to log me back into scenario and keeps kicking me out :( 

### ISSUE THREAD

**Issue by fiven1n3** [WarEmu/WarBugs#18240]
Help im lost in the void. 

player name          **fivenine**

 

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by MaxHayman** [comment]
what were you doing before you were originally teleported to Winds of Chaos?

**Comment by fiven1n3** [comment]
Playing in a scenario mate. Then we lost. So hit the off switch on pc (one
touch powers it down).

Not a great time of year for me.

Gromrill crossing. When I tried to log back in it kept trying to put me
into the scenario.

A global mod was excellent and very kindly moved the char to a safe space.
Which did work. Sadly the same issue was there.

The char fivenine would log in. Handshake etc and load the IC loading map
and the kick me back out.

I've tried the /stuck to no avail.


If you could help that would be massively appreciated. :) And thankyou very
much for the reply. And apologies for the trouble. Especially this time of
year.

Thanks.

Fivenine


Dan.

**Comment by Kaelang** [comment]
Have you tried typing /stuck twice on load screen? (Even if you can't see the chat console).

**Comment by fiven1n3** [comment]
Yes quite a few times. Sadly nothing. I've reinstalled the game. And
cleared cashe etc.

Only on that character for some reason.


Thankyou for the message.


Is it recoverable?.


Thanks again.


Fivenine. - Dan.

**Comment by fiven1n3** [comment]
https://www.youtube.com/watch?v=03bWY5Q2I54&ab_channel=DE

this is whats happening.

**Comment by fiven1n3** [comment]
any news? or info? just before i head off to re level thats all. thanks.

**Comment by MaxHayman** [comment]
This should have been fixed.

**Comment by fiven1n3** [comment]
do you have a charity in mind. i know we cant fund the game, but ill
happily donate something somewhere. ;)
