### ISSUE TITLE
[Witch Hunter] Razer Strike Animation Changed

### ISSUE THREAD

**Issue by AKA-Jtpe** [WarEmu/WarBugs#18246]
**Expected behavior and actual behavior:**

'Razer Strike' ability used to have a horizontal sword slash as an animation. Currently, after patch, it shares an animation with 'Burn Armor'.

**Steps to reproduce the problem:**
1) Use 'Razer Strike'
2) Observe animation

**Comment by grunbag** [comment]
fixed
