### ISSUE TITLE
Item Bug!

### ISSUE THREAD

**Issue by olderfist93** [WarEmu/WarBugs#18258]
Hi, i'm Nazkal ingame and i have a issue with Item Bug!

I bought the item Sovereign Darkboots of the Dreadshield and i got Sovereign Darkboots of the 
Dreadsword instead. 
I really appreciate if you can help me get back my right Item!.

![bug](https://user-images.githubusercontent.com/76708212/103245206-b3ab4980-495f-11eb-8ce8-2b1721dfc21e.png)

**Comment by Lheana** [comment]
There are no information about this possible bug, or how to replicate it. Moreover we don't give out items.
Thus I close it.
