### ISSUE TITLE
Imperial Black horse

### ISSUE THREAD

**Issue by Naos7** [WarEmu/WarBugs#1825]
After looking on every quartermasters and light mount vendors, the "imperial black horse" is not available in the list. Vendors have 5 Empire mounts available and there is a "black stallion" but when I bought it it is the "Grey empire horse". I first supposed that the black empire horse was a special guild mount but after checking, all other races have 6 mounts available at vendor. I also checked with several empire character and the problem is the same with all. So this is not a bug for only one of my characters. I also asked to a friend to check it with an empire character and he have same issue.

**Comment by Evildoor** [comment]
According to Luth:
The item ID of the black stallion mount that is actually light grey: 186823
The tiem ID of the black stallion mount that is really black: 186824

**Comment by Torquemadra** [comment]
Fixed next patch
