### ISSUE TITLE
Twitch Event Quest From Presents is Shareable to party

### ISSUE THREAD

**Issue by Portense** [WarEmu/WarBugs#18259]
I was on my Bright Wizard, Chimney, and bought the twitch quest that gives the keg runner pet. After buying the quest, I partied with a guildmate, and we went to T1 area. I was able to share the quest by going into the tome, selecting the quest, and clicking share. We completed the quest together at the same time in the same area where both of our quests were marked complete. We returned to Altdorf, but during the loading screen I was kicked to character screen. I logged back in and we both were able to complete the quest even though he did not spend the presents to buy the quest.

**Comment by Kabucoror** [comment]
fixed with next patch
