### ISSUE TITLE
bug with twitch event present

### ISSUE THREAD

**Issue by starror** [WarEmu/WarBugs#18251]
I have claimed 4 kegs end present 7 hours ago on my character who's name is starbuckk but there is no present in my mail box 
thank you for your respons please

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Sorkhatani** [comment]
Confirmed. I am having the same issue. 
I get the mail in the mail box, but it is empty. I tried with 2 different characters just to see if it was somehow only affecting 1, but neither can see any items. I can "Take items" but receive nothing. The letter then shows as the usual icon in mailbox of an empty letter.
This also happened with the Keg End Elite reward: no cloak, no item. Although the game says I claimed it. Didn't really care as it was only an appearance item, but the twitch items I actually want.

**Comment by starror** [comment]
its not the same bug because i don't receive the 4 mails. The present were noticed claimed but dont received the mail

**Comment by Brackso** [comment]
I got 2 Twitch drops bugs. Yester day on the 26th (Award for The Second Day of Christmas), I claimed it but it never came to my mail on my Squigie "Bracksop". To day there are only 3 claims showing up on my account, even when I watched ToShutKidUp, FixxerTV and Zarbix streams for at least 10 hrs to day (See print screen attached to this where you can see I only goten 11 drops over the 3 days, when there should be 12 drops).

Any way. If you fix my drops or not, I wish you guys of RoR still a Happy Christmas. :)

![Twitchdrops](https://user-images.githubusercontent.com/76665169/103180095-ec312180-4892-11eb-8569-01484a80c3ca.jpg)

**Comment by Brackso** [comment]
I got 2 Twitch drops bugs. Yester day on the 26th (Award for The Second Day of Christmas), I claimed it but it never came to my mail on my Squigie "Bracksop". To day there are only 3 claims showing up on my account, even when I watched ToShutKidUp, FixxerTV and Zarbix streams for at least 10 hrs to day (See print screen attached to this where you can see I only goten 11 drops over the 3 days, when there should be 12 drops).

Any way. If you fix my drops or not, I wish you guys of RoR still a Happy Christmas. :)

![Twitchdrops](https://user-images.githubusercontent.com/76665169/103180241-441c5800-4894-11eb-9b6f-e0d1cbcf1122.jpg)

**Comment by Kaelang** [comment]
I believe this was hotfixed.
