### ISSUE TITLE
Unable to form Alliance

### ISSUE THREAD

**Issue by abigoni1** [WarEmu/WarBugs#18256]
Hi, I'm Kazzim in game, and I'm trying to form an alliance with another guild (both rank > 6) and it is not working...can you help me?

Thank you

![2020-12-28](https://user-images.githubusercontent.com/76699184/103230007-91e89d00-4934-11eb-950d-f22aa834861a.png)

**Comment by Kaelang** [comment]
Already listed.

**Comment by abigoni1** [comment]
is it solved?
