### ISSUE TITLE
Stuck in Squig Armor?

### ISSUE THREAD

**Issue by SubsaurusRex** [WarEmu/WarBugs#18252]
i have found a bug that when you go into squig armor you can not leave it when you click on the icon again it does the animation 2 times and keeps you in the armor maybe recently happened due to new update

**Comment by Snottbudz** [comment]
Same, i have to log out and back log back in before i can leave squigy. Right-click does not end it, mounting wolf does not end it.

**Comment by Hadzi-user** [comment]
I can confirm. I have the same problem.

**Comment by grunbag** [comment]
Fixed with next patch
