### ISSUE TITLE
[Zealot] Empowered Alteration tactic

### ISSUE THREAD

**Issue by cimator** [WarEmu/WarBugs#18267]
For info, this is the tactic;
![empalt](https://user-images.githubusercontent.com/17130290/103407464-d613b180-4b6f-11eb-913f-e785ff7a8be8.jpg)

and the abilitiy it affects;
![leapalt](https://user-images.githubusercontent.com/17130290/103407488-e9bf1800-4b6f-11eb-826d-08afe18b7a22.jpg)

Leaping Alteration has 3 ticks, tactic adds each tick 12 ap atm, and doesnt give ap on initial cast, so the tactic gives a total of 36 ap, instead of 48. 

Here is the vid; https://youtu.be/3JY5R4QIQn0 . You can see my ap bar in numbers

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by cimator** [comment]
Tested it again today, looks like its restoring 24 ap total now instead of 48. 12 ap on the first and second tick, last tick and the initial apply doesnt give ap now.
