### ISSUE TITLE
Triumphant Emblem Quartmaster Bug

### ISSUE THREAD

**Issue by wildwindblows** [WarEmu/WarBugs#18262]
Hello,
Although i have enough Triumphant emblem, i couldn't buy Triumphant Tramplers on the npc. I didn't observed any error. I don't know the reason of this. When I asked to gm about this, it was adviced to closed the client and relog but nothing is changed after this process. Therefore, I decided to report this as a bug.

Thanks.

**Comment by Rydiak** [comment]
Have you played any ranked SC games since the new season started?

**Comment by Kaelang** [comment]
See above question.

**Comment by Lheana** [comment]
No answer, closing this ticket.
