### ISSUE TITLE
SW Swift Strikes missing animation

### ISSUE THREAD

**Issue by kyraith** [WarEmu/WarBugs#18260]
**Expected behavior and actual behavior:**
Swift Strikes is not playing an animation on my SW

(this may also be an issue with barrage, but only heard from another SW, do not have the ability)

**Steps to reproduce the problem:**
Use Swift Strikes in combat, notice that the character model just stands there and floats around when you move (my SW is 27)

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by grunbag** [comment]
fixed with next patch
