### ISSUE TITLE
Issue placing talismans

### ISSUE THREAD

**Issue by DraqO404** [WarEmu/WarBugs#18266]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

When attempting to place a talisman, via shift-right click, into an item in my inventory the talisman will not move into the box. I have tried just clicking on the talisman and moving it over and nothing happens. Any assistance is greatly appreciated.

https://user-images.githubusercontent.com/76802011/103395305-a62ac680-4afb-11eb-9749-1019ce7e6278.mp4

**Comment by Garrthax** [comment]
You cant put lvl 24 talisman into lvl 17 gear. Talisman lvl must be similar or lower.

**Comment by Kabucoror** [comment]
A talisman must have the same or a lower rank than the gear you want to put it in.

**Comment by DraqO404** [comment]
Thank you. Hadn't considered that aspect.
