### ISSUE TITLE
Saving Keg End quest

### ISSUE THREAD

**Issue by NSKaneda** [WarEmu/WarBugs#18271]
On destruction side barrels only spawn Captive Dwarf instead of goblin. Both Nordland and Norsca locations

-
-

![Mordoszczel_013](https://user-images.githubusercontent.com/22037960/103441646-ab992580-4c4f-11eb-90cb-cf29207b917c.jpg)

**Comment by Kabucoror** [comment]
did it on destro 2h ago everything works fine.

**Comment by NSKaneda** [comment]
I've done it in 5 locations, 4 of them bugged and only the one near Gausser's Wilding worked (5 hours of grinding but that's irrelevant). 

On order side it worked at the first try.
