### ISSUE TITLE
SH: Typo in Yer Bleedin'!

### ISSUE THREAD

**Issue by Zydna** [WarEmu/WarBugs#18272]
Says it reduces initiative by 2 ? A typo or a real big nerf that I don't know about.

![image](https://user-images.githubusercontent.com/75143494/103443300-033e8d80-4c5e-11eb-8a48-c441db3cc87e.png)

**Comment by grunbag** [comment]
Typo

**Comment by grunbag** [comment]
Fixed with next patch
