### ISSUE TITLE
Fort contribution broken for WE

### ISSUE THREAD

**Issue by Keptpet** [WarEmu/WarBugs#18284]
Im playing a 40 Witch Elf & nearly every losing Fort (as attacker) i cant earn enough contribution to get my invader meds, im not afk im trying to cap bos / ninja them & defending points but if we lose while attacking a fort i seem to not earn enough contribution as a WE to get any rewards 40min of fort for zero rewards seems broken

**Comment by Keptpet** [comment]
just did Stonewatch 5th losing fort(attacking) in a row now & no contri , i capped a bo i defended said bo i went with my WB & zerg order at other bos & took them, i was fighting all the stages but still no rewards this contri system seems very broken for WE

**Comment by Keptpet** [comment]
other WEs have msg me saying they are not getting rewards either

**Comment by Kabucoror** [comment]
I tested it on my WE and recieved my rewards.
![Kynai_016](https://user-images.githubusercontent.com/45296624/103520289-3740cb00-4e77-11eb-879f-7c3d49e75f1b.jpg)

**Comment by Haojun-Phalanx** [comment]
if you are solo WE, you most likely gonna end up with bottom line of contribution pyramid.

**Comment by Keptpet** [comment]
> if you are solo WE, you most likely gonna end up with bottom line of contribution pyramid.

not soloing

**Comment by Keptpet** [comment]
> I tested it on my WE and recieved my rewards.
> ![Kynai_016](https://user-images.githubusercontent.com/45296624/103520289-3740cb00-4e77-11eb-879f-7c3d49e75f1b.jpg)

then you are lucky odd are i wont get any rewards if we are attacking & lose

**Comment by tlitschye** [comment]
hmm, cant confirm that. Almost every fort with WE i got my medals and even bags, so i sound like a git gud issue ;D

**Comment by Kaelang** [comment]
Not convinved this is a game issue - there's plenty of players who are getting rewards, WE's included.
