### ISSUE TITLE
Swordmaster eye glitch

### ISSUE THREAD

**Issue by Jiawnally** [WarEmu/WarBugs#18286]
A very odd issue i've noticed for any male high elf models holding shields. The issue is purely cosmetic but I felt it should get at least a small spotlight on it. Any male high elf model holding a shield has their left eye squinting considerably, and their right eye bulging at a disturbing degree.
![image_2021-01-02_230620](https://user-images.githubusercontent.com/48191709/103471488-209f5480-4d4f-11eb-8f73-aad80f3711a1.png)

**Comment by theStormrider** [comment]
Female SMs have the same issue, maybe worse.
![eyes sm](https://user-images.githubusercontent.com/66573497/104041978-21663980-51da-11eb-8c4b-685815173c3f.jpg)

**Comment by Kaelang** [comment]
https://github.com/WarEmu/WarBugs/issues/15976
