### ISSUE TITLE
Unable to pick up kill quests

### ISSUE THREAD

**Issue by Grzegorz75** [WarEmu/WarBugs#1828]
Quote from other person (I have this problem too):
"Yesterday there were a couple of server restarts. After the first restart, but before the second restart, I turned in almost all of my completed kill quests (did the round-the-world trip). However, I could not start the quests again. 

I figured this was an issue that would be resolved after a restart, however this is not the case. I simply cannot see icons above the heads of the NPCs and right clicking on them does nothing.

However, there were a couple of kill quests that I had not started at the time. I am able to start, complete and restart these with no problems. Only the quests that I turned in during the "buggy phase" are still not able to be picked up.

As far as I can tell - this is isolated to my Bright Wizard only. My other characters are able to complete kill quests as normal." 

Thread: http://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=7706

**Comment by Evildoor** [comment]
#1589
