### ISSUE TITLE
Auction House bugged for the account (impossible to sell objects) - please help me

### ISSUE THREAD

**Issue by Rottengul** [WarEmu/WarBugs#18280]
I've encountered a problem with my account. On any character i already have or i create from lvl 1, i'm unable to sell items in the auction house. I can buy from it tho. I drag the item into the "sell" window and set the price, but the create button remain grey and unclickable. Even more, the item in the inventory becomes bugged and not movable until relog. I don't have any addon installed and i just reinstalled the game but the bug persist. I don't know what else i could do, since some months ago i could sell stuff with no problem. Any suggestion? I didn't find any topic  for the same bug. 
![Senza titolo-1](https://user-images.githubusercontent.com/76864137/103454461-bd78d800-4ce4-11eb-8ea9-e126b4001025.jpg)
![Senza titolo-11](https://user-images.githubusercontent.com/76864137/103454464-c1a4f580-4ce4-11eb-83c5-ecaa0f491afe.jpg)

**Comment by Kaelang** [comment]
Looks like a client issue, try repairing your client / removing addons etc.
