### ISSUE TITLE
mSH - Sneaky Git tactic

### ISSUE THREAD

**Issue by Zydna** [WarEmu/WarBugs#18287]
Tooltip says "While in your Squig Armor, your defenses are increased by 10%". But it only increases parry, nothing else.

Either tooltip is wrong or the tactic bugged.

With Sneaky Git
![image](https://user-images.githubusercontent.com/75143494/103488130-8bfa2c80-4e0a-11eb-9c50-362d3fb6faac.png)

Without
![image](https://user-images.githubusercontent.com/75143494/103488142-9caaa280-4e0a-11eb-8b10-0cfbaad3f207.png)

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by Zydna** [comment]
There is actually no parry increase either. The parry increase/decrease is from tactic Pick on yer own size. So nuthing from Sneaky Git.

**Comment by Zydna** [comment]
Ok so now after patch it increases parry, dodge and disrupt, but not armor or resistances. Is this intentional or a still a bug? Because tooltip says "it increases all defenses by 10%". If it is not a bug, the tooltip should be changed.

**Comment by grunbag** [comment]
Defenses are dodge parry disrupt , not armor / resist
