### ISSUE TITLE
[Squig herder] Sneaky git still works when tactic is removed

### ISSUE THREAD

**Issue by IxanderousI** [WarEmu/WarBugs#18289]
With tactic
![MSH1](https://user-images.githubusercontent.com/25346641/103508966-f6868900-4e59-11eb-9a9c-91b8723c41ff.png)

Without tactic
![MSH2](https://user-images.githubusercontent.com/25346641/103509034-203fb000-4e5a-11eb-9023-192a7310232a.png)

Buff from sneaky git remains and as a result you can use other tactics in its stead and still keep the 10% to defence.

**Comment by Zydna** [comment]
This is really weird. Because on my mSH there is absolutely no increase at all on my defenses. I've checked with statdoll and .getstats.

**Comment by IxanderousI** [comment]
> This is really weird. Because on my mSH there is absolutely no increase at all on my defenses. I've checked with statdoll and .getstats.

Me and another player have confirmed that it is happening, not sure why its not for you, only way you lose it if you leave squig armor.

**Comment by grunbag** [comment]
Fixed with today patch
