### ISSUE TITLE
1 Accusation Absolution doing uncharacteristically low damage

### ISSUE THREAD

**Issue by CeeJay89** [WarEmu/WarBugs#18288]
1pt Absolution is doing far worse damage than its tooltip. It doesn't scale appropriately like 2 ~ 5pt does.

![Absolution scaling](https://user-images.githubusercontent.com/25260106/103488375-f47ce580-4dd9-11eb-831d-9cf7a757b864.JPG)

That is the tooltip damage that Absolution shows, however, the 1pt mechanic does approximately 65% of the 2pt mechanic (Or to put in other terms, by getting just one more Accusation, Absolution will do nearly 50% more damage), whereas the rest are scaling up appropriately. Here are some images

1 Accusation
![1pt](https://user-images.githubusercontent.com/25260106/103488440-8ab10b80-4dda-11eb-9d5c-98c04bbacd8f.JPG)

2 Accusations
![2pt](https://user-images.githubusercontent.com/25260106/103488445-8f75bf80-4dda-11eb-869e-9aa731551132.JPG)

3 Accusations
![3pt](https://user-images.githubusercontent.com/25260106/103488449-93094680-4dda-11eb-8232-e6a3825966ae.JPG)

4 Accusations
![4pt](https://user-images.githubusercontent.com/25260106/103488456-97356400-4dda-11eb-8983-0e4617bf0077.JPG)

5 Accusations
![5pt](https://user-images.githubusercontent.com/25260106/103488457-9c92ae80-4dda-11eb-8374-099ac612f149.JPG)

So every point of Accusation increases the damage by approximately 80 damage in the tooltip. However, if we take 5pt as the baseline...

5 Accusations - 838 dmg - 100% - 0 damage loss from 5pt
4 Accusations - 771 dmg - ~92% of 5pt - 67 damage loss from 5pt
3 Accusations -  703 dmg - ~83% of 5pt - 135 damage loss from 5pt; 68 damage loss from 4pt
2 Accusations - 634 dmg - ~76% of 5pt - 204 damage loss from 5pt; 69 damage loss from 3pt
1 Accusation - 426 dmg - ~ 51% of 5pt - 412 damage loss from 5pt;  208 damage loss from 2pt

So there's roughly a 7~ 9% damage loss for every Accusation from 5 down to 2 until you reach 1 Accusations, where you lose 25% of the total, despite the tooltip suggesting it should just be another 7 ~ 9%.

I tested these numbers with non-crits for consistency. Should be easy to replicate. All the screenshots were taken on the same test dummy in the same combat sequence. Nothing was changed between shots.

1 Accusation Absolution needs to reflect the proper damage. It greatly impacts the effectiveness of certain builds that utilize Flowing Accusation.

**Comment by grunbag** [comment]
fixed with next patch
