### ISSUE TITLE
Unable to turn in Keg's End quest Dead Soldiers

### ISSUE THREAD

**Issue by dkoerner85** [WarEmu/WarBugs#18293]
**Expected behavior**
Being able to turn in the quest "Dead Soldiers" by visiting a Bugman's Brewmen in any dwarf warcamp.

**Actual behavior:**
There seem to be no Bugman's Brewmen in the T2, T3 or T4 dwarf warcamps.

**Steps to reproduce the problem:**
Try to find a Bugman's Brewmen.

**Comment by Lheana** [comment]
The event has ended.
