### ISSUE TITLE
SH ability Indigestion tooltip typo

### ISSUE THREAD

**Issue by Zydna** [WarEmu/WarBugs#18295]
![image](https://user-images.githubusercontent.com/75143494/103790810-f8ab3c00-5041-11eb-8137-542efb7d37d0.png)

**Comment by Zydna** [comment]
says "increasing the cooldowns of affected enemies by 1 second for each enemy you hit, to a maximum of 3 seconds" twice.

**Comment by grunbag** [comment]
fixed with next patch
