### ISSUE TITLE
Sentinel Talisman locked to Ironbreaker role

### ISSUE THREAD

**Issue by Acerexx** [WarEmu/WarBugs#18296]
**Expected behavior and actual behavior:**
Sent Talis are usually not class specific. the only ones available no matter what class you check with are locked to Ironbreaker

**Steps to reproduce the problem:**
open talis merchant 

**Testing Screenshots/Videos/Evidences (always needed):**
![Axem_034](https://user-images.githubusercontent.com/77069069/103798058-38106300-5017-11eb-9d94-dec2da287efe.jpg)

**Comment by Acerexx** [comment]
and I just got my sent ring last night :'(

Thx for all your hard work btw!

**Comment by Sixmoons48** [comment]
same thing on destro side, ironbreaker is only purchasable talisman

**Comment by Sixmoons48** [comment]
it actually transformed the sentinel jewel i already had in my marauder's inventory, into an ironbreaker one
![image](https://user-images.githubusercontent.com/21229715/103843117-db379b80-505c-11eb-9f51-4bd3292a6950.png)

**Comment by Vancerus** [comment]
All of mine on DoK are now for Ironbreaker as well and also the new ones from the merchant. Although I can slot it nonetheless, so it seems to be just a visual bug.

**Comment by Acerexx** [comment]
Can confirm, was able to purchase - slot - reequip ring - and bonus is applied. Just a visual bug. It does still give you the warning that you will NEVER be able to use though when purchasing.
