### ISSUE TITLE
KOTBS multiple bugs

### ISSUE THREAD

**Issue by MaraIsTooNerfed** [WarEmu/WarBugs#18294]
Aura: "Now's Our Chance" - tooltip says it lasts for 12 seconds after cancelling the aura but it does not last not even 1 second once it's cancelled. Can be replicated easily.

Skill: "Challenging shout" - tooltip says it lasts for 15 seconds. It lasts more like 10. Can be replicated easily.

Skill: "Heaven's Fury" - tooltip says it lasts for 5 seconds. It lasts for 2-3 seconds. Can be replicated easily.

Aura: "On your Guard!" - Tested this vs a fresh 40 WH and a vanq+ SM. WH was able to mitigate more damage than the SM which makes no sense whatsoever. Can be replicated easily.

Stay tuned, I will bring more.

**Comment by grunbag** [comment]
one ticket per bug please, also make sure you checked english tooltips
