### ISSUE TITLE
Da Stunty Mystery quest bugged

### ISSUE THREAD

**Issue by valkeera** [WarEmu/WarBugs#18298]
The quest Da Stunty Mystery disappeared from the questbook after the last patch, individual steps are not visible.
It's still possible to unlock the steps by clicking on the flasks and complete the quest, but you can't talk to the questgiver in IC.

![Zeraton_000](https://user-images.githubusercontent.com/58527250/103810574-c7d80080-505b-11eb-8c5b-cd1c7dd5dee9.jpg)

![Zeraton_001](https://user-images.githubusercontent.com/58527250/103810585-cc9cb480-505b-11eb-9a15-b0b8f56644bb.jpg)

**Comment by Lheana** [comment]
Has this been fixed with the hotfix?
