### ISSUE TITLE
Unable to pick up repeatable kill quests on selected characters

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#1829]
Hi all,

Yesterday there were a couple of server restarts. After the first restart, but before the second restart, I turned in almost all of my completed kill quests (did the round-the-world trip). However, I could not start the quests again. 

I figured this was an issue that would be resolved after a restart, however this is not the case. I simply cannot see icons above the heads of the NPCs and right clicking on them does nothing.

However, there is one kill quest that I had not started at the time (keep lord in Barak Varr). I am able to start, complete and restart this one with no problems. Only the quests that I turned in during the "buggy phase" are still not able to be picked up, which is every other kill quest.

As far as I can tell - this is isolated to my Bright Wizard only, as this was the only character I was playing during this server restart period. My other characters are able to complete kill quests as normal.

It appears I am not the only one - I made a thread in the Game Support forums and a couple other people reported the same issue. I have also spoken to numerous people in game with the same problem.

Feel free to contact me in game.

BW: AboMeltsYou

Destro: Abolition, Abogroupheals

**Comment by Evildoor** [comment]
#1589
