### ISSUE TITLE
Witch Hunter - Sword of the Subjugator missing in the bags?

### ISSUE THREAD

**Issue by fagio1989** [WarEmu/WarBugs#18290]
Hello there,

It seems that the "Sword of the Subjugator" (Def Weapon) is missing in the bags for WHs.
I'm an active player farming bags T4 since september with my WH but never found the Sword, only Rapiers, so I guess something probably missing and prevents us to buy the fortress weapon as well =)

Screens of the weapon and its requirement:
https://ibb.co/HzBfjFK
https://ibb.co/L57zRcS

Have a nice day!

**Comment by wargrimnir** [comment]
This appears to be fixed already. The rapier/sword were intended for each class, not mixed. The fortress sword is only showing Kotbs allowed now.
