### ISSUE TITLE
[General] [Order/Destro] [Renown] - Renown Point are not awarded

### ISSUE THREAD

**Issue by Mirkul29** [WarEmu/WarBugs#183]
Description:
No Renown Point are currently awarded when reaching any Renown Rank. This prevent the player to purchase any Renown Advancement.

Reproduction Rate: 100%

Step to repro:
1- Proceed to gameplay as a any character
2- Notice the lack of functionality for the Renown Point system

Labels: Item, World Object

Note: Well aware that currently no Mechanic are working but still posting this bug as a reference point.

**Comment by milosxe** [comment]
Renown Points and Skills are (partially) implemented. Closing.
