### ISSUE TITLE
Chosen: Bottomless Stein Trophy uses Order model

### ISSUE THREAD

**Issue by JockeJoestar** [WarEmu/WarBugs#18302]
This is the Order version/model, not Destro.
![Bjarki_013](https://user-images.githubusercontent.com/53709160/103833367-22d01e80-5081-11eb-99c2-d9c285ed8258.jpg)

Black Orc (as well as most other classes) has the correct Destro version/model:
![Bjarki_014](https://user-images.githubusercontent.com/53709160/103833411-46936480-5081-11eb-8ca6-385dce4fb286.jpg)

**Comment by grunbag** [comment]
fixed

**Comment by JockeJoestar** [comment]
> fixed

![Bjarki_031](https://user-images.githubusercontent.com/53709160/106324985-62ea8180-627a-11eb-87c1-c4bde696d1fc.jpg)

Once again it is showing the Order version.
