### ISSUE TITLE
Destruction Sentinel Talisman Vendor: Only offering Ironbreaker Talismans

### ISSUE THREAD

**Issue by JockeJoestar** [WarEmu/WarBugs#18305]
When sorting by useable items, he seemingly sells nothing...
![Bjarki_015](https://user-images.githubusercontent.com/53709160/103883449-84be7180-50dd-11eb-9479-315736edd918.jpg)

... but when showing all, he only sells Ironbreaker versions.
![Bjarki_016](https://user-images.githubusercontent.com/53709160/103883524-9c95f580-50dd-11eb-939b-536f53805fc3.jpg)

**Comment by Lithenir** [comment]
Same for the Order vendor

**Comment by Acerexx** [comment]
yep, bug for both sides, reported yesterday on here

**Comment by Lheana** [comment]
Duplicate of #18296
