### ISSUE TITLE
Corset of Warboss will

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#18307]
**Expected behavior and actual behavior:**

Should be chest piece, not 2h great light armor

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/7400/103899716-15557b80-50f7-11eb-8bc7-8e2338a5cf89.png)

**Comment by Kabucoror** [comment]
fixed with next patch
