### ISSUE TITLE
item bugged

### ISSUE THREAD

**Issue by fornicator** [WarEmu/WarBugs#1830]
r2 chaos item "wrought crusher" cannot be equiped by my chosen.  Number at bottom right is 400629.  Character name "thugnasty".

**Comment by Evildoor** [comment]
Is this wrong? "Crusher" items are marauder weapons, sometimes they have type "axe" (and can be used by chosen) and sometimes "hammer" (and cannot be used by chosen). Models can differ with type sometimes, but this does not changes the fact that Wrought Crusher is labeled "hammer", so it is logical that you can't use it. If it was "axe" on live then we need a proof.

**Comment by ozarmidrashim** [comment]
Crushers should be hammer-type weapons and thus unusable by Chosen, which should accept both Axe and Sword.

**Comment by fornicator** [comment]
ok, but the game doesn't say that I can't equip it, so I wasted money on the AH to get it.  It has an axe icon, so I wasn't sure.

**Comment by Evildoor** [comment]
What? The item has "hammer" label, which should be shown in red for Chosen, which means you cannot use it.

**Comment by fornicator** [comment]
no hammer label

**Comment by fornicator** [comment]
I saw no hammer label, and it definitely wasn't red to indicate I couldn't use it. I don't even know what weapons chosen could use at that time.

**Comment by Evildoor** [comment]
![chosen_000](https://cloud.githubusercontent.com/assets/11015074/11186410/9bcec966-8c92-11e5-87c2-0153a515956c.jpg)
Weapons usable by class are listed in Abilities - General.

**Comment by fornicator** [comment]
wow, I'm reaterded nevermind
