### ISSUE TITLE
Cant queue in Scenarios at Warcamp

### ISSUE THREAD

**Issue by Brumaires** [WarEmu/WarBugs#18311]
On some of my characters I can not queue for scenarios in Warcamp, I need to exit it to be able to queue. What happens is that at Warcamp I click on the scenario icon on the minimap to queue up, but nothing happens, like the button doesn't respond to my click. As soon as I exit warcamp the button becomes responsive again.

It happens on 3 of my high elves and on my Black Orc only

**Comment by Lheana** [comment]
I ignore what causes this issue on your char, but one thing is sure, this is not an issue other players have. Try the Repair button on the launcher, or use our technical support on forum or Discord.
