### ISSUE TITLE
Focused Mind not working as intended

### ISSUE THREAD

**Issue by Aeriell** [WarEmu/WarBugs#18315]
Focused Mind doesn't work as intended. 50% of the time when you pop it it disappears right away and it doesn't reduce cast times at all.
Tested in PvE and RvR with Sorc and DoK.

**Comment by Zumos** [comment]
There are some boss fights where they disabled Focused Mind. You found FM to also not work in any PvP forms?

**Comment by Aeriell** [comment]
Yes, for example in last fort I was in. I Casted FM 4 times during the siege to test it out and it worked only 2 times.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. This is an old and ongoing issue. I will add it to the related post.

**Comment by lilimx** [comment]
dublicate/related to #2204
