### ISSUE TITLE
Shatter Limbs from Slayer's debuff tooltip incorrect 

### ISSUE THREAD

**Issue by DefVont** [WarEmu/WarBugs#18316]
Showing 5 seconds instead of 3 seconds

![Shatter Limbs incorrect tooltip](https://user-images.githubusercontent.com/64330047/104023653-129d7800-5216-11eb-9fff-f8372ee1eedd.png)

**Comment by tlitschye** [comment]
wasnt there an adjustment to shatter limbs that i depended on how many people you hit with it?

**Comment by DefVont** [comment]
> wasnt there an adjustment to shatter limbs that i depended on how many people you hit with it?

Yes so it should state 'up to 3 seconds' at the very least?

**Comment by grunbag** [comment]
Fixed with next patch
