### ISSUE TITLE
DESTRO SUBVERSION(SECRET ACHIEVEMENT & A BOSS MOB)

### ISSUE THREAD

**Issue by Hauclir** [WarEmu/WarBugs#1831]
https://www.youtube.com/watch?v=fxzQtIUdy-U

I don't really care about the achievement part I just want to be able to get to him and kill him for drops I can get to the tower manually but cant get inside. Doors wont open nor is there a lever.

**Comment by DanaBloodkiss** [comment]
Thanks for reporting but this is to hard to implement :)

**Comment by Sapphiratelaemara** [comment]
Adding information: Approaching the Wizards Tower at 
![image](https://cloud.githubusercontent.com/assets/23622177/20469770/a9f368f6-afa2-11e6-8cf9-139ea42cbde9.png) should award the achivement 'Subversion'.

In the blue tent at 
![image](https://cloud.githubusercontent.com/assets/23622177/20469887/bc30ca3a-afa3-11e6-98e4-7dd0612e41d2.png) mobs 'Luthor Vogt' and 'Dirk Eisenhauer' would have a conversation, after which killing Eisenhauer would drop a gray item 'Wizard's Key' for Destro characters which would teleport you inside and allow you to get the 'Brotherhood of Nuln' ToK unlock.
