### ISSUE TITLE
Sneaky Git only increases defenses with 0.9%

### ISSUE THREAD

**Issue by Zydna** [WarEmu/WarBugs#18326]
The tooltip says 10%

without
![image](https://user-images.githubusercontent.com/75143494/104102905-9f404880-529f-11eb-94a6-158b1391fc67.png)

with
![image](https://user-images.githubusercontent.com/75143494/104102912-b0895500-529f-11eb-8b72-d52506c7f4d1.png)

**Comment by grunbag** [comment]
fixed with next patch
