### ISSUE TITLE
all character  lost.

### ISSUE THREAD

**Issue by dadlyj** [WarEmu/WarBugs#1832]
hello here asia. pm :11:00~ 12:00

yesterday i;m played sc..clan membes 

suddenly server down... i'm sleep.

today login  my accunt.

my oders camp  character is all lost.

clan member;s say

"yesterday we have about bug"
"better now"

why me?

my accunt name: yg1008

return the incarnation's of me

**Comment by wargrimnir** [comment]
These characters appear to exist in the database, account is not banned. Likely a temporary bug.

**Comment by Evildoor** [comment]
This problem still persists?

**Comment by Evildoor** [comment]
No answer, closing.
