### ISSUE TITLE
[SH] Squig Armor stance buff doesn't stack anymore

### ISSUE THREAD

**Issue by cimator** [WarEmu/WarBugs#18325]
The stat conversion part seems to be fine,(melee crit, armor pots work fine atm) but the flat 120 str/tough/wounds buff of Squig Armor doesn't stack with pots/abilities anymore. 
As far as I can tell, it started happening after the 01/01/2021 patch. 

This is a SS of before and after strength pot;
![MSHbug](https://user-images.githubusercontent.com/17130290/104095166-635cb180-52a6-11eb-8b90-b4d16c001385.jpg)

**Comment by grunbag** [comment]
fixed with next patch
