### ISSUE TITLE
Quest NPC Saphery Windweaver for Double-Edged Quest in Chrace should be dead

### ISSUE THREAD

**Issue by dalen** [WarEmu/WarBugs#18329]
**Expected behavior and actual behavior:**

This NPC should be dead, but is alive instead. At least it should be lying down and immovable.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/7400/104121740-de72a600-5340-11eb-8a10-fb554594405e.png)

**Comment by Lheana** [comment]
I close this ticket as the Saphery Windweaver is not meant to be permanently dead, and we are already aware that a script is needed for this NPC.
