### ISSUE TITLE
Wounds on "Your status window" does not scale with lini

### ISSUE THREAD

**Issue by Zydna** [WarEmu/WarBugs#18327]
Wounds unbuffed 762
Liniment with +60 wounds
Your Status windows shows 762 (7620)
Char Panel 822 (8220)

Liniment of War: Hunger, it's the same with Liniment of Boundless Sight. Other stats from pots/lini seems to stack though. But im not 100% sure.

![image](https://user-images.githubusercontent.com/75143494/104103025-3c9b7c80-52a0-11eb-8374-53999aff8350.png)

![image](https://user-images.githubusercontent.com/75143494/104103183-07435e80-52a1-11eb-8e6b-154c1bcf8bb7.png)

**Comment by cimator** [comment]
Its a bug with squig armor. Str wounds and toughness pots/linis/buffs doesnt work with squig armor atm for some reason. reported here; #18325

**Comment by grunbag** [comment]
Fixed with next patch
