### ISSUE TITLE
Cloak of Bugman's Resolve appearance

### ISSUE THREAD

**Issue by MaraIsTooNerfed** [WarEmu/WarBugs#18324]
When trying to apply the appearance of Cloak of Bugman's Resolve (reward from event) my cloak just becomes invisible. Even when un-checking guild heraldry (although I am not in a guild).
Is this working as intended?

**Comment by Tyrannicus** [comment]
I'd like to add that when I do the same with the level 5 Battlebrew backpack I looted from a giant, the backpack cannot be used as an appearance item for any of my cloaks. "Battlebrew backpack cannot be used as apperance item" is the message I receive.

**Comment by MaraIsTooNerfed** [comment]
This was fixed after I re-installed the client via Torrents and I got it visible now.
