### ISSUE TITLE
"Battlebrew backpack cannot be used as an appearance item" 

### ISSUE THREAD

**Issue by Tyrannicus** [WarEmu/WarBugs#18323]
<
Just as the title says. I looted the pack off of a giant last week during kegs end on my new Engineer. 

I did not mail myself this pack from another character.   I did not purchase this pack from the AH prior to the patch that changed it to bop.  I looted the pack off the giant on my level 3 Engi.   I looted and equipped the pack last week. I equipped a normal. green,  vendor purchased cape today and when I tried to apply Battlebrew appearance I received the message. 

Pack is level 5. My character is lvl 19. Cape i'm trying to change appearance is a green level 17 cape.  I should be able to use lower slevel appearance item for higher level equippped item. 
-->

I tried logging off and back on. Unequip, reequipping.  I tried checking and unchecking guild heraldry and other common troubleshooting steps. All to no avail.

**Comment by Acerexx** [comment]
Same issue for me with the high level version. Had it equipped on appearance, after removing it was unable to reapply.

**Comment by Tyrannicus** [comment]
So i dont dare ever remove the backpack appearance on the characters that already have it because most likely wont be able to reapply the appearance? Surely this is a bug? 

I can apply level 1 gloves appearance to my level 22 gloves. Why can't i apply lvl 5 battlebrew appearance to a level 17-23 capes?

**Comment by lilimx** [comment]
Hey, 

thank you for your ticket. I will add this report to a related issue.

**Comment by lilimx** [comment]
related to #12491
