### ISSUE TITLE
[WH] Flanking tactic does not increase Blessed Bullets damage

### ISSUE THREAD

**Issue by CrimsonFenris** [WarEmu/WarBugs#18338]
**Expected behavior and actual behavior:**
Flanking tactic on WH doesnt seem to increase Blessed bullets damage, Either Blessed Bullets of Purity, Cleansing of Confession.

Tried on static dummies and constructs, hitting behind deal same amount of damage from bullets (see screenshots).

According to this post https://github.com/WarEmu/WarBugs/issues/14103, Flanking should increase all outgoing damage.

Since damage from bullets is increased by Engineer tactic "Coordinated Fire" (+15% increased dmg on target), I see little to no reason why flanking would not work as well ?

![Flanking_Bullets_Not_Working_Front](https://user-images.githubusercontent.com/40425011/104366702-0f5a0300-551a-11eb-9929-3b2ecc64993e.jpg)
![Flanking_Bullets_Not_Working_Back](https://user-images.githubusercontent.com/40425011/104366711-12ed8a00-551a-11eb-85a5-b83be43b8b83.jpg)

Didnt check for WE but worth a check if anyone can confirm/infirm Flanking working with kisses damage ?

**Comment by stonetradex** [comment]
[https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=40621&hilit=flanking+procs](url)

[Abilities]

- Flanking no longer increases proc damage by 15%, just like other damage bonuses don't affect proc damage.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
The Patchnotes are right and still state of the art for this tactic.
-closed
