### ISSUE TITLE
CC Immunity is not working

### ISSUE THREAD

**Issue by StirlingScott** [WarEmu/WarBugs#18333]
**Expected behavior and actual behavior:**
Immunity timer should trigger once a Crowd Control ability is applied to the player

Immunity timer triggers however the player is still able to have CC applied to their character

**Steps to reproduce the problem:**

Apply CC to an opposing player and apply another CC ability while the immunity timer is applied and the player will fall under the effects of the CC when it should not apply

**Comment by grunbag** [comment]
different immune for different CC
