### ISSUE TITLE
attack costs 10k action points

### ISSUE THREAD

**Issue by zakattak167** [WarEmu/WarBugs#18339]
I noticed when logging onto my level 39 Ironbreaker the other day that two of my attacks showed over 10k action points to use. I've tried with and without addons. I've played for several days with this happening so its not a one off thing. Grudging Blow and heavy blow

**Comment by lilimx** [comment]
Hey,

do you have any picture or videos of this issue? Does it still persists even with lvl 40? Was it propably patched?
