### ISSUE TITLE
Swimming to isle of the dead via dragonwake puts player into respawn stasis, spawning at the place you died to be killed by "the gods"

### ISSUE THREAD

**Issue by redwolf777x** [WarEmu/WarBugs#18332]
Swimming to isle of the dead via dragonwake puts player into respawn stasis, spawning at the place you died to be killed by "the gods" before you can scroll out (war report should work).

https://youtu.be/aprxP_v3RNg     (unlisted video of it)

Would it be possible to change respawn point to a warcamp instead of the spot you died to avoid player issues? Currently if you chose to keep respawning you can carry on untill you're out of the map

**Comment by lilimx** [comment]
Hey,

It looks like the problem has now been resolved. You'll get ported back to your capital city if you leave the map and die.
If your the opinion the issue still persists, please open a new ticket.
