### ISSUE TITLE
Leaping Alteration Missing Heal Tick [Zealot]

### ISSUE THREAD

**Issue by Evilmariel** [WarEmu/WarBugs#18331]
Spell Leaping Alteration: 
![image](https://user-images.githubusercontent.com/46075524/104124520-5203bb80-531f-11eb-8ab3-58da1926df02.png)

Is only ticking twice if no one else receives the HoT from the bounce. See Image (Flash of Chaos used as starting/end)
![Leaping2](https://user-images.githubusercontent.com/46075524/104124551-7bbce280-531f-11eb-8202-1fbbaefd08fe.PNG)

Heal ticks 3 times on initial target; 2 times on others if it does bounce (Flash of Chaos used as starting/end)
![Leaping1](https://user-images.githubusercontent.com/46075524/104124584-a313af80-531f-11eb-85e0-9108409ab8e7.PNG)

Comparatively; the Runepriest's Rune of Serenity is getting 4 ticks on initial target and 3 times on all others.
![RP_Serenity3](https://user-images.githubusercontent.com/46075524/104124634-e837e180-531f-11eb-8891-15f992153651.PNG)

Also; the rune of serenity ticks 3 times on self if no bounce.
![RP_Serenity1](https://user-images.githubusercontent.com/46075524/104124671-11587200-5320-11eb-9faf-5f8773369939.PNG)

**Comment by Evilmariel** [comment]
Also it seems in the first image the HoT healed for less (222) on other target and myself for normal (281). Not sure why but it was fixed after relogging (maybe visual bug only?)

**Comment by grunbag** [comment]
fixed with next patch
