### ISSUE TITLE
Shaman (and Archmage) Fury of Da Green (and Energy of Vaul) do not AoE heal when you are the defensive target

### ISSUE THREAD

**Issue by Zumos** [WarEmu/WarBugs#18336]
Fury of Da Green and the Archmage equivalent (Energy of Vaul) are supposed to heal every within 20 feet of your defensive target. However, if you yourself are the defensive target, it no longer does an AoE heal. It instead only heals yourself.

Video proof (look at the combat log):  https://youtu.be/g7NAvttwiyQ

**Comment by Undrsiege** [comment]
This issue still exists...

**Comment by lilimx** [comment]
Hey,

hank you for your ticket. I will add this ticket to the related issue.

**Comment by lilimx** [comment]
related to #16309

**Comment by lilimx** [comment]
related to  #14857
