### ISSUE TITLE
Chosen: Bloodlord 7-piece bonus (Reactionary) doesn't trigger/work.

### ISSUE THREAD

**Issue by JockeJoestar** [WarEmu/WarBugs#18337]
![Bjarki_018](https://user-images.githubusercontent.com/53709160/104255734-031e6900-547a-11eb-9f4f-e7eb503ecdac.jpg)

Spent the longest time just defending against these mobs and Reactionary didn't activate once.

![Bjarki_019](https://user-images.githubusercontent.com/53709160/104256410-7ffe1280-547b-11eb-9ca7-729cf83535f2.jpg)

Tested against higher level mobs just in case the no-damage dealing of the lower level mobs somehow messed it up. No Reactionary proc after several minutes of taking a beating.

![Bjarki_020](https://user-images.githubusercontent.com/53709160/104256567-c18ebd80-547b-11eb-9ab1-91d5807ce8cb.jpg)

Finally, unequipping the cloak to just get the 6-piece bonus while also equipping Hand of Malal (which has Reactionary proc as well) you can clearly see it triggering off of the weapon itself.

**Comment by Zumos** [comment]
![Bloodlord Reactionairy Chosen](https://user-images.githubusercontent.com/19267650/104300091-53231d00-54c6-11eb-800a-ca96e051210f.png)
I just tested the Bloodlord Reactionairy proc on Chosen and it works fine for me.

**Comment by JockeJoestar** [comment]
Same. Login in today it suddenly started working fine again. I suspect there might be some issues with the proc if you equip both full Bloodlord and Hand of Malal or something, because it truly was disabled for me last night. So it might be worth looking into that, but as for now it seems that it was a rare oddity that happened for whatever reason.

**Comment by Zumos** [comment]
It definitely sounds plausible that there might be a bug if you equip 2 reactionairy procs.
