### ISSUE TITLE
Public quest GREENSKIN CH15

### ISSUE THREAD

**Issue by Hawkrin** [WarEmu/WarBugs#18345]
**Expected behavior and actual behavior:**
Hey the PQ "Valley of the Rangers - Stage 1(Hard)" have bugged for me twice on separate occasions. It counts Redmane Dwarfs up until 8/100 but then it stops. I don't know if it's just a visual bug or if it actually stops counting.
![WAR-64_I1ZNJdiTZl](https://user-images.githubusercontent.com/71021972/104734210-2f6b0b80-5740-11eb-9ac2-3d0b4f2799d5.png)

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
I tested and it works fine for me. Comment here with more details about how to replicate it if it still occurs.
