### ISSUE TITLE
Inventory / Loot Roll Issues

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#1834]
I've been having some inventory issues, which have been happening since the latest server restart about an hour ago (the one that was to fix the RVR quest bug).

Nothing in my bag has a tooltip. I can however, click and drag items around. i cannot right click on anything to sell to the vendor.
My abilities DO have tooltips.

I cannot see any items at the vendor. All I see is numerous boxes that would contain pictures of items that I cannot see.

When someone links something and I click it a box with lots of numbers shows up.

I am unable to roll on loot. Even my auto-rolls "time out" and Pass.

Unsure if anyone else is having this issue. Hopefully the next server restart will fix it.

**Comment by Evildoor** [comment]
This problem still persists?

**Comment by Abolition** [comment]
Nah I think it was just related to that server restart. You can close.
