### ISSUE TITLE
BG Warlord 4th set bonus bugged

### ISSUE THREAD

**Issue by Lalethrin** [WarEmu/WarBugs#18347]
BG Warlord gear 4th set bonus does not display the 6% armor penetration and it also do not ad up to the total armor penetration-

**Comment by wargrimnir** [comment]
Gonna need a screenshot of this. Both the itemset and the chat command .getstats result. It appears functional to me.

**Comment by Lalethrin** [comment]
It works for me now
----- Oorspronkelijk bericht -----
Van: wargrimnir ***@***.***>
Aan: WarEmu/WarBugs ***@***.***>
Cc: Lalethrin ***@***.***>, Author ***@***.***>
Verzonden: Wed, 23 Jun 2021 18:59:22 +0200 (CEST)
Onderwerp: Re: [WarEmu/WarBugs] BG Warlord 4th set bonus bugged (#18347)

Gonna need a screenshot of this. Both the itemset and the chat command .getstats result. It appears functional to me.
