### ISSUE TITLE
Crash respawn in Reikwald in bad spot

### ISSUE THREAD

**Issue by mforeman15** [WarEmu/WarBugs#18349]
Playing destro today, I crashed in Reikwald. When I logged back in I was respawned at 38k, 29k and couldn't run back to fort. I ran down hill to try to reach the portal, and was blocked by barriers, but I also couldn't leave either. I booked to IC, fly to Reik, but lost all contribution to fort by the time I got back.  There were at least 6 others similarly stuck.
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. I will add your report to a related issue.

**Comment by lilimx** [comment]
related to #19132
