### ISSUE TITLE
Social Search: rate limit kicks in after only a few searches

### ISSUE THREAD

**Issue by s1xp0und3r** [WarEmu/WarBugs#18354]
**Expected behavior and actual behavior:**
expected behavior: it is possible to make several search requests for the guild field.
actual behavior: after a few searches for guilds in the social window  the error message (user error)
"Social Searches are rate limited, try again later." is displayed.

**Steps to reproduce the problem:**
1. open social window search
2. enter name of a guild as searchterm in guild field
3. click search 
4. repeat step (2 and) 3 a couple of times

**Testing Screenshots/Videos/Evidences:**
![search_rate_limit](https://user-images.githubusercontent.com/69598022/104820116-1abb7000-5833-11eb-8622-ebd2b0dcd89b.jpg)

**Comment by lilimx** [comment]
Hey,

this is intended to not to overload the server with requests
