### ISSUE TITLE
Engineer-ability-Hip Shot

### ISSUE THREAD

**Issue by Thorekx** [WarEmu/WarBugs#18359]
Good day

The hip shot ability was intended to use the stopping power tactic to kick opposing melee fighters back at a distance.
The distance for the ability was between 20 or 25 feet on the live server. It is currently 100 feet here.
The name from the tactik skilltree is Path of The Rifelman

<a href="https://ibb.co/vcFkmKc"><img src="https://i.ibb.co/vcFkmKc/Bum-005.jpg" alt="Bum-005" border="0"></a>

<a href="https://ibb.co/zsxVpt3"><img src="https://i.ibb.co/zsxVpt3/Bum-006.jpg" alt="Bum-006" border="0"></a>
greetings Thorek93

**Comment by grunbag** [comment]
fixed with next patch
