### ISSUE TITLE
Shaman Career Resource Display

### ISSUE THREAD

**Issue by grindbox** [WarEmu/WarBugs#18355]
Seems to be only for me, but the display with the two red and yellow faces is not working for me. no matter what spells i cast, the display is not moving.

i already tried repairing the launcher, setting it to 32 bit and using this command:

/script WindowSetShowing(*EA_WCareerResourceWindow*, true)

nothing works to get the resources work.

**Comment by lilimx** [comment]
Hey,

maybe you've already fixed it... but you have to open the layout editor, press "restore defaults" and don't save.
If you have further questions, just join the RoR discord.
