### ISSUE TITLE
Shaman spell "Sticky Feet"

### ISSUE THREAD

**Issue by Fruk0st** [WarEmu/WarBugs#18352]
Hi. I just levels up my Shaman to level 24 and i finally got my "sticky feet" spell. I cant use it in PvP zones or senarios tho but it works in PvE places for some reason.
Video below! 
-> https://www.youtube.com/watch?v=YIVeUpAem8c&feature=youtu.be&ab_channel=KristofferKarlsson

I got so exited when i leveld up so i went to the Keep in Alverorn for the spell.
I have tryed to respec in IC and tryed to loog off and in agen and nothing seams to work. can you guys help me you think?
thx! <3

**Comment by gablorquet** [comment]
My guess is that you have a set bonus granting you a +1 in the path where Sticky Feet is and you used that point to get it. I had the same problem on my AM with MoM and once I levelled, I had to go back to my trainer and respec, then took off my set and buy MoM "normally". After that point, it worked as intended.

**Comment by Fruk0st** [comment]
ye sure maby, but it works now when i leveld up, i did not buy a new point
or anything. just leveld up and it workt. and why is it that it did work in
PvE land but not in RvR. enyway. all good now tho so Yeej!

Den mån 18 jan. 2021 kl 06:14 skrev gablorquet <notifications@github.com>:

**Comment by grunbag** [comment]
Sticky feetz min level is 25 isnt it ?

**Comment by Fruk0st** [comment]
O damn. Never lookt at that, that is prob tru, Got to comfuse by it working
in PvE. Really sorry for that mate! 🙈

Den mån 18 jan. 2021 13:43grunbag <notifications@github.com> skrev:
