### ISSUE TITLE
guild bank money missing

### ISSUE THREAD

**Issue by 816384138** [WarEmu/WarBugs#18358]
guild bank on order reportedly (i wasn't keeping track as I was playing destro) had over 4k gold. of course I'm thinking that one of the a person withdrew the gold but I'm hoping there was an alternative explanation

is there an audit function to review withdraw/deposit allocations and dates? could this be a bug with the gold disappearing? 

Guild is Ruin on order if that helps

**Comment by Zumos** [comment]
Someone probably stole your gold and you make a bugreport of it. If you want to ask a question the forums or discord would be a better place.

**Comment by 816384138** [comment]
I already posted on discord too without any suggestions for the questions I asked

there is a possibility this was a bug which is why I posted here. if a dev can find out it was withdrawn then I'll withdraw my bugreport, otherwise I'm exploring other options

**Comment by lilimx** [comment]
Hey,

sorry for your loss! If you want to write a head-up for this option, please use the Suggestion & Feedback forum: https://www.returnofreckoning.com/forum/viewforum.php?f=15
(I think there were already 1 or 2 threads about this idea.)
