### ISSUE TITLE
DESTRO CH22 KADRIN VALLEY - mobs reset

### ISSUE THREAD

**Issue by badoglio170389** [WarEmu/WarBugs#18365]
the mobs into portals don't reset if boss is resetted , so people can actually go into portal phase and reset boss without worry about surviving in 12 into the lordroom with aoe and adds (the only difficulty of the whole chapter), people into portals clears adds and teleport out by the portals when finished. then all 24 can do boss from 100% to 0% together again without entering the portals again

**Comment by lilimx** [comment]
Talked with the OT,
looks like it is fixed.
