### ISSUE TITLE
Bottomless Stein not showing when equipped

### ISSUE THREAD

**Issue by DefVont** [WarEmu/WarBugs#18363]
Bottomless Stein trophy not showing when equipped, even when re-equipping the item.

**Comment by b00nation** [comment]
Yes can confirm this, since keg event end the item disappeared from displaying.

**Comment by Tyrannicus** [comment]
Same here. Stein does not render when equipped since last weekend's patches(15-16 January patch).

**Comment by grunbag** [comment]
fixed with next patch
