### ISSUE TITLE
Died in Fell Landing, respawned in Caledor, still had reservation

### ISSUE THREAD

**Issue by varinx** [WarEmu/WarBugs#18362]
Hi there,

I am currently/have participated in the Fell Landing fortress on the 18/01/2020. During this fort I was killed around about 46k 26k and ended up respawning in Caledor WC however I retained my reservation.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
With which character did happen this? I need a bit more information.

**Comment by lilimx** [comment]
Hey,

im going to close this ticket now due to no feedback.
