### ISSUE TITLE
Trollhaugen Shopkeep

### ISSUE THREAD

**Issue by Yzhydul** [WarEmu/WarBugs#18375]
Trollhaugen Shopkeep in Trollhaugen, Troll country does not open shop when clicked upon
![Yzhydul_000](https://user-images.githubusercontent.com/77712221/105126048-77bd5d00-5aa3-11eb-8c0e-053d81b7938f.jpg)

**Comment by Lheana** [comment]
Fixed with the patch of 26/03/2021.
