### ISSUE TITLE
Chosen: Bottomless Stein Trophy Not Displaying After Given Correct Appearance

### ISSUE THREAD

**Issue by JockeJoestar** [WarEmu/WarBugs#18374]
![Bjarki_025](https://user-images.githubusercontent.com/53709160/105112227-e1992f00-5ac2-11eb-9cff-6c26313b73ee.jpg)

Previously it showed the Order version. Now (based on the icon) it **should** show the Destruction version but it won't load on the character regardless of which trophy location you pick.

**Comment by grunbag** [comment]
fixed with next patch

**Comment by JockeJoestar** [comment]
![Bjarki_031](https://user-images.githubusercontent.com/53709160/106324520-937deb80-6279-11eb-80b3-896bdd34917f.jpg)

It is broken again: showing the Order version for Chosen once more...
