### ISSUE TITLE
Kills and deathblows are incorrectly reported ingame

### ISSUE THREAD

**Issue by CrimsonFenris** [WarEmu/WarBugs#18379]
**Expected behavior and actual behavior:**
I noticed from one or two weeks ago now (may be recent patches), that killblows are not reported the same way ingame, ie. you take renown for a kill (reported correctly in chat log), but you dont always get the middle screen message saying you made a deathblow (basic game feature).

See screeshot below, I made 2 killing blows according to renown log : They are correctly reported on enemy kdr addon (wich read rr log I presume), but I didnt get the onscreen message for one of the two deathblows, meaning the Dammaz Kron addon incorrectly report one deathblow instead of two.

Deaths are however correctly counted by both addons (One dead being counted by enemy but PvE, and not counted by DK).

I thing there could be an dissonnance between client and server API. That issue never happened before, and I never changed the addon used (wich seem to rely on two different inputs), and all was working fine until recently.

**Steps to reproduce the problem:**
Do killblows on multiple players, see log counting more kills than number of onscreen deathblow messages.

**Testing Screenshots/Videos/Evidences (always needed):**
![Deathblows_API_Bug](https://user-images.githubusercontent.com/40425011/105194351-c87f9500-5b39-11eb-8cd1-702325043423.jpg)

**Comment by dalen** [comment]
Session stats are not implemented at all on the server at the moment. So those must be purely in that addon.

The middle screen message for a killing blow is an addon feature.

**Comment by CrimsonFenris** [comment]
Thanks Dalen for the info, it is indeed an issue with DK not counting deathblows all the time.

It happens mostly with kills made with Dragon Gun on my WH (only few kills are counted by DK, while all are with Enemy kdr).

I suspect the "new" formula that was introduced couple of months ago (only counting "credit kill" for quests to party with most dmg on target) to mess up with this addon, but since it's not updated in a long time there is little hope to make it work perfectly again... :/

If anyone have knowledge about Dammaz Kron addon and the called functions used to "read" combat log for correct kill counting, let me know and get in touch with me please. ;)
