### ISSUE TITLE
Bug Boss Gunbad Left

### ISSUE THREAD

**Issue by abigoni1** [WarEmu/WarBugs#18371]
Hey there,

Yesterday night we were doing Gunbad Left on order and, on the last boss of the wing, he disappeared when he was 80%HP. He didn't give us the lockout, as can you see from the screenshot.
![Bug Gunbad](https://user-images.githubusercontent.com/76699184/105033006-d52bbc80-5a57-11eb-87bc-7f98d5f0f957.png)

**Comment by dalen** [comment]
Should be fixed with the patch today.
