### ISSUE TITLE
On Your Guard aura reflect dmg

### ISSUE THREAD

**Issue by MaraIsTooNerfed** [WarEmu/WarBugs#18386]
On Your Guard aura reflect damage seems to be bugged. When testing vs a WH and vs a SM, the SM took more damage than the WH per hit. I am speculating the damage received is influenced by Toughness, however, the WH did not have more Toughness than the SM.
Also, shouldn't this reflected damage not be influenced by anything and just be a flat reflect damage? If it's so easy to deny the aura, what's the point of it in the end?

**Comment by grunbag** [comment]
Proc damage doesn’t scale with stats , so they are only influenced by mastery and levels

**Comment by MaraIsTooNerfed** [comment]
It's not about my damage, it's about the received damage. If it doesn't scale with stats, then should it take defenses into consideration?

**Comment by grunbag** [comment]
If they don’t scale with stat , then they don’t check for toughness

**Comment by MaraIsTooNerfed** [comment]
Then please check it because I dueled a SM and a WH and I had different reflect damage.
My base dmg is 215.
SM was getting hit for 184.
WH was getting hit for 140.
Something triggers the "mitigation".

**Comment by SecretsOTheP** [comment]
This should be a flat physical damage amount. It's currently set to elemental damage.

Grunbag is going to change it in the DB to be physical as the tooltip states - meaning it will be mitigated by armor/reduced armor penetration and penetrated by armor penetration on gear/weaponskill. This ability scales with mastery too, so factor that in to any tests.

**Comment by grunbag** [comment]
fixed
