### ISSUE TITLE
Now's Our Chance aura tooltip

### ISSUE THREAD

**Issue by MaraIsTooNerfed** [WarEmu/WarBugs#18385]
Now's Our Chance aura tooltip says it lasts 12 seconds after being cancelled. In reality it doesn't last, not even for 1 second once the aura is changed.

English tooltip, as I was asked to mention it.

**Comment by grunbag** [comment]
Tooltip doesn’t says it last 12 seconds after being cancelled

**Comment by grunbag** [comment]
“You order your group to ready their defenses, causing 150 damage back against any attacker who strikes a groupmate within 100 feet with a melee attack. Targets can only be damaged once every two seconds.
The Battle Command will last until its toggled off. You can have up to 3 Battle Commands active at the same time.”

**Comment by MaraIsTooNerfed** [comment]
![image](https://user-images.githubusercontent.com/66925719/105362844-abab9600-5bfb-11eb-8490-4b49a93b32d8.png)

**Comment by grunbag** [comment]
Ok sorry i wasn’t looking at the right aura

**Comment by MaraIsTooNerfed** [comment]
no worries <33

**Comment by grunbag** [comment]
where did you got that tooltip from?

**Comment by grunbag** [comment]
![now's our chance](https://user-images.githubusercontent.com/24207191/105364475-7d2eba80-5bfd-11eb-944c-080e067a4516.png)

**Comment by MaraIsTooNerfed** [comment]
Hmmm, from my game of course :) And this confuses me even more now. I'll reinstall from scratch I guess?

**Comment by MaraIsTooNerfed** [comment]
Other ppl don't have it. I'll reinstall. You can close this ticket.
Thanks!
