### ISSUE TITLE
Challenge duration

### ISSUE THREAD

**Issue by MaraIsTooNerfed** [WarEmu/WarBugs#18384]
Challenge duration tooltip says it lasts for 15 seconds but in reality it lasts like 10 seconds.

English tooltip, cuz i was asked to mention the language apparently.

**Comment by grunbag** [comment]
You mean challenge ?

**Comment by MaraIsTooNerfed** [comment]
Yes, sry, Challenge. I'll edit. Since my guy screams at the ppl and I played warrior in wow a lot, I mistook the name :D

**Comment by grunbag** [comment]
Challenge is set to 15 seconds , where did you saw 10 seconds ?

**Comment by MaraIsTooNerfed** [comment]
I used it in a duel and I counted as well as asked the target to count. Both of us had lower than 15 seconds result. Tested it multiple times as well as the target didn't hit me back - so there's no confusion

**Comment by grunbag** [comment]
What buffline displayed as duration under players names ?

**Comment by MaraIsTooNerfed** [comment]
Yes, that. I also noticed it doesn't get updated properly, so if u hit escape after selecting the target and select the target again, it refreshes properly.
I spammed that in order to reach this conclusion, that it lasts for less than 15 seconds.
Also, my target mentioned at some point the debuff shown on his character buffline went from 13 seconds to 10.
Maybe it's a server desync issue, although the duration was lower than 12-10 seconds everytime.

**Comment by SecretsOTheP** [comment]
Are you using default unit frames? If so, can you provide a screenshot?

I'm adding @dalen to this ticket, may be related to the dot tick refreshing code if it has an interval set.

**Comment by MaraIsTooNerfed** [comment]
Yes, default unit frames, not buffhead.
I cannot provide u a screenshot atm as I'm reinstalling the client, but will do once I'm up.

**Comment by MaraIsTooNerfed** [comment]
After testing again in a duel, only sometimes the debuff lasts 2-3 seconds less. I would upload a video but it's 50MB+.
Most of the time seems it's working as intended. Tested vs an AM now.
So it might be a wild goose chase. I can confirm the default unit frames buff bar doesn't get updated with the debuff unless I re-select the target.

**Comment by MaraIsTooNerfed** [comment]
closing this till i have some evidence. I just got the new client so I'm going to try again
