### ISSUE TITLE
Heaven's Fury duration

### ISSUE THREAD

**Issue by MaraIsTooNerfed** [WarEmu/WarBugs#18387]
Heaven's Fury spell (KOTBS Path Of Glory tree) tooltip says it lasts for 5 seconds.
I understood it was nerfed to 3 seconds because it was deemed too strong.
However, the tooltip says 5 seconds at the moment.
Can we get it back to 5 seconds - to be a proper skill since it's sharing the DR with other cc - or can we get the tooltip changed to show 3 seconds for better information?
![image](https://user-images.githubusercontent.com/66925719/105364117-11e4e880-5bfd-11eb-831d-087de2486ef2.png)

**Comment by MaraIsTooNerfed** [comment]
If this is fixed in the newer client, please close the ticket. Apparently I was running a 2013 client somehow.

**Comment by grunbag** [comment]
fixed
