### ISSUE TITLE
Reikland PQ " The enemy within " not working properly.

### ISSUE THREAD

**Issue by Leysia** [WarEmu/WarBugs#18381]
The chapter 16 Empire Public Quest in Reikland, " The Enemy Within", is only spawning a third of the mobs it shoulder in all three stages. Due to respawn times, this poses little issue in the first two stages but for the third stage it becomes impossible to complete. August Semur and one of the Knights do not spawn, only one knight does, making it impossible to complete the Public quest.

EDIT: It appears other public quests may also be suffering from this, at least in Reikland. I entered the area of the Castle Grauenburg PQ and it is also visibly short of enemies by at least two thirds. May wish to investigate PQs in general.

**Comment by Garrthax** [comment]
yeah all pq i saw were broken, with mobs spawning just few or not at all

**Comment by Garrthax** [comment]
![image](https://user-images.githubusercontent.com/49390790/105246727-f4b80780-5b73-11eb-8304-3dadd6ba4371.png)

**Comment by Leysia** [comment]
After the hotfix, this PQ worked without a hitch for one run. After that, when running it again, the proper amount of mobs spawned for the first stage, but there were no respawns, leaving it impossible to complete.

**Comment by Wyvernmoon** [comment]
Confirmed... Doing PQ in MoM for Epic quest and mobs are not respawning.

**Comment by dalen** [comment]
Found a second issue and fixed. So they should be working again after next hotfix.
