### ISSUE TITLE
[Item] Canine Tooth

### ISSUE THREAD

**Issue by moondoggcavalier** [WarEmu/WarBugs#1839]
Both "Shattered Canine Tooth" and "Curious Canine Tooth" do not have Icons set. If I had to guess, the other canine teeth do not have icons as well. 

![evanovitch_000](https://cloud.githubusercontent.com/assets/15387904/11245119/22a7a014-8ddf-11e5-9faa-2cb51820685b.jpg)
![evanovitch_001](https://cloud.githubusercontent.com/assets/15387904/11245120/22a91da4-8ddf-11e5-8c8b-c2149fbcbb72.jpg)

**Comment by Meralors** [comment]
Fixed all of those items, they should now display correct icon.
Will be live with next item db pull ;)
