### ISSUE TITLE
Keep It Goin' does not update tooltip of ability, or increase damage

### ISSUE THREAD

**Issue by Azrienov** [WarEmu/WarBugs#18392]
**Expected behavior and actual behavior:**
Increases damage to "X"

No effect.

**Steps to reproduce the problem:**
Equip it.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by grunbag** [comment]
some screenshot would be welcome

**Comment by lilimx** [comment]
Hey,

well as Grunbag already mentioned, it would be nice if you can provide some screenshots or a video.

**Comment by Azrienov** [comment]
Sorry, I haven't been on in a while.

**Comment by Aedros** [comment]
Hi I am experiencing this issue on my lvl 24 Black Orc Bonesplitta as well. The Keep It Goin tactic when equipped has a tooltip value of 333 while the ability on my toolbar has a tooltip of 237. I have tried various combinations of equipping one then the other on my ability/tactic bar, but nothing has resolved it so far. In scenarios with bolster, both values increase but remain different with the ability tooltip being consistently lower.

**Comment by lilimx** [comment]
Hey,

this ticket is closed.
Please open a new one with your information and a testing screenshot or video.
We will link your ticket to this one.

**Comment by Aedros** [comment]
Will do. Thanks for looking into it.
