### ISSUE TITLE
[terrain] JUMP keep black firepass Gnol BARAZ

### ISSUE THREAD

**Issue by kakless** [WarEmu/WarBugs#18397]
PLAYER JUMPS INTO THE KEEP ON MOUNT.
SOUTH POTERNS Gnol BARAZ
![bug_Lekahless_016](https://user-images.githubusercontent.com/63593553/105611423-8cf0ff00-5db5-11eb-8628-79d145ac6924.jpg)
Tank

**Comment by Kabucoror** [comment]
could not reproduce the jump
