### ISSUE TITLE
Mobs PQ Chaos Wastes doesn't respawn

### ISSUE THREAD

**Issue by Misteria** [WarEmu/WarBugs#18396]
Hello,
It seems mobs in PQ in CW doesn't respawn.
I wanted to start T4 epic quest near Chapter 20 (empire), and mobs in PQ "Razing an Army" doesn't respawn (their deads corps stay on the ground).
Then I wanted to grind a little bit in CW and I realized every mobs in PQ in this area couldn't respawn.

**Comment by Enryle** [comment]
The PQ is called "razing an army" at Chap 20 empire Chaos Waste and it is still bugged . "Braineaters" Mobs count stuck at 28/30 , can't complete the PQ and can't do the epic quest neither

**Comment by Lheana** [comment]
This should have been fixed few patches ago.
