### ISSUE TITLE
MSH TACTIC [Sneaky Bouncin']

### ISSUE THREAD

**Issue by barfyman92** [WarEmu/WarBugs#18390]
This tactic does not work, there is no difference in melee range damage when the tactic is slotted or not.

![image](https://user-images.githubusercontent.com/28030187/105484321-6fd00980-5cab-11eb-9291-d6b58aac625a.png)

damage is with and without the tactic slotted so there is no difference

**Comment by grunbag** [comment]
Try something else than auto attack

**Comment by Zydna** [comment]
It works on abilities.

**Comment by admaska2** [comment]
![Sneaky B](https://user-images.githubusercontent.com/43276959/105644980-175e5f00-5e99-11eb-9d78-c18579b44025.png)

The TACTIC [Sneaky Bouncin'] dont work for auto attacks

**Comment by grunbag** [comment]
yes that's what i said, it works on abilities, not on AA.

**Comment by Zydna** [comment]
Tbh the tooltip should reflect this. Because as it is now, it says just damage. When it says damage, you think it is both AA and Abilities. And if it would, we would all save time and not report it as a bug.
