### ISSUE TITLE
Guild Heraldry Not Submitting - Finally submits and uses the default emblem and wastes my gold

### ISSUE THREAD

**Issue by Seshn1** [WarEmu/WarBugs#18395]
I tried to submit my guild heraldry quite a few times and each time nothing happened. I fully relogged and tried again and it used my colour and pattern but it gave me the default emblem despite using the exact same design. It used up my 10 gold and now I can't try to change it again because I don't have the 100 gold needed after it is set.

![Heraldry](https://user-images.githubusercontent.com/77875032/105571813-f9152980-5d07-11eb-8ba6-f3c4c8ac655a.png)
![Heraldry 2](https://user-images.githubusercontent.com/77875032/105571827-0b8f6300-5d08-11eb-9e27-b07f9e8fad75.png)

Character name: Theirtanks
Discord: Sesh#2222

**Comment by lilimx** [comment]
Hey,

sorry for the late respond. but what lvl was your guild at this time?

**Comment by lilimx** [comment]
Hey,

I'll close this ticket now, because no information has been submitted for further processing.
