### ISSUE TITLE
Crystal Grove Scout Animation Broken

### ISSUE THREAD

**Issue by VonEpic** [WarEmu/WarBugs#18399]
In the PQ Tower of the Elves, Luminous Vale, High Pass, the Crystal Grove Scouts do not have an attack animation. They have a proper movement and death animation, but stand still while attacking.

**Comment by lilimx** [comment]
Hey,

can't confirm this issue. Checked their animition at their tower and it looks fine.

**Comment by Zomega-WAR** [comment]
I did the PQ yesterday and went back again today and can confirm that the Scouts do not have an attack animation. They will follow you about if you move, stop about 20ft away and do damage, but they just remain crouched at all times even when "attacking" and doing damage.

@lilimx please could you re-open the ticket?
