### ISSUE TITLE
DoK Soverign Gear Not Registering Critical Hit Rate

### ISSUE THREAD

**Issue by ESC-Ramo** [WarEmu/WarBugs#18394]
**Expected behavior and actual behavior:**
When Equipping Sovereign DPS Gear on my DoK, I am not seeing any changes to my Melee Crit or Heal Crit or Magic Crit under the paperdoll. I was informed that Critical Hit Rate is supposed to give both Crit chance to Heal, Melee, Magic, Etc.

**Steps to reproduce the problem:**
Equip on and off Str Soverign DPS Cloak or Helm and look at stats in paperdoll

**Testing Screenshots/Videos/Evidences (always needed):**

Created a quick video showing what I mean, youtube link below.

https://youtu.be/KMxJG0Nakj4

**Comment by grunbag** [comment]
Check for critical hit rate in the paper doll

**Comment by ESC-Ramo** [comment]
Nothing in Paperdoll that is called Critical Hit Rate under any of the dropdowns

**Comment by Kabucoror** [comment]
If you want to check flat stats please use .getstats. The paper doll is buggy with some stats.

**Comment by grunbag** [comment]
It shouldnt be buggy

**Comment by ESC-Ramo** [comment]
Ok, will use .getstats from now on
