### ISSUE TITLE
Fort Trainers were changed to wear Invader - Spawns nude instead.

### ISSUE THREAD

**Issue by JockeJoestar** [WarEmu/WarBugs#18406]
![Bjarki_028](https://user-images.githubusercontent.com/53709160/105846433-77115300-5fdc-11eb-9f4a-dbbd93405d6a.jpg)

Or, at least they appear nude in Fell Landing. Haven't checked other forts.

**Comment by b00nation** [comment]
can confirm, stonewatch, reikwald and shining way is the same.

**Comment by Lheana** [comment]
It has been fixed.
