### ISSUE TITLE
Riding Wyver at the fort are hostile

### ISSUE THREAD

**Issue by Niall86** [WarEmu/WarBugs#18402]
Riding Wyver at the fort are hostile

**Expected behavior and actual behavior:**

You should be able to ride Riding Wyver at the fort 
Instead, you are suggested to attack them

**Steps to reproduce the problem:**
Come at the fort respawn

**Testing Screenshots/Videos/Evidences (always needed):**

![Blondva_135](https://user-images.githubusercontent.com/1152711/105750849-48509980-5f56-11eb-915e-6783133eff3f.jpg)

**Comment by Lheana** [comment]
Fixed with the Patch of 29/01/2021.
