### ISSUE TITLE
Mailbox Issue... broken

### ISSUE THREAD

**Issue by defleshed2** [WarEmu/WarBugs#1840]
Hello guys,

My character "Defleshed" has an issue with his Auction House tab in the mail. My character cannot access any of his mail through the auction house tab. In the chat log I can see serveral unread messages as this has not been working for 3 days. All of my other characters are working fine. I do not have any mail addons intalled so I know it is a bug with the game itself. I tried to reload a default profile and its still broken.

Thanks in Advance,
Defleshed

**Comment by Evildoor** [comment]
Seems somewhat similar to #557.

**Comment by defleshed2** [comment]
actually after reading Zealote's problem its different. mine is showing NO mail at all. not even a mail when i buy items in AH like zealot.  on my log its showing the correct unread AH mail but when I go to the mailbox its actually saying "0 messages"

**Comment by defleshed2** [comment]
Hello is someone looking at this?

**Comment by Tesq** [comment]
i had a similar problem before, i sent en email from tesq to vlodar and my dok didn't recive nothing

**Comment by defleshed2** [comment]
It's not quiet the same but this is a AH mailbox bug 

Sent from my android device.

-----Original Message-----

**Comment by Evildoor** [comment]
Closing per rules of the bugtracker.
