### ISSUE TITLE
WL Flashing Claws tactic

### ISSUE THREAD

**Issue by Zydna** [WarEmu/WarBugs#18403]
Only increases parry with 3% not 10%.

Without tactic
![image](https://user-images.githubusercontent.com/75143494/105764168-eb091800-5f56-11eb-8b84-ab9d5181ea06.png)

With tactic
![image](https://user-images.githubusercontent.com/75143494/105764212-f65c4380-5f56-11eb-9ba2-1ed8e1b1353e.png)

**Comment by grunbag** [comment]
Thanks I’ll fix that

**Comment by Zydna** [comment]
Could be some other issue, because .getstats show 4% without tactic and 14% with tactic.

**Comment by grunbag** [comment]
Yes it’s paperdoll bug

**Comment by grunbag** [comment]
fixed with next patch
