### ISSUE TITLE
Battle Brew Backpack Appearance Change Bug

### ISSUE THREAD

**Issue by Sixmoons48** [WarEmu/WarBugs#18401]
Battle Brew Backpack cant be used as appearance on some characters, some of my characters can use it while my zealot cannot change appearances 
![image](https://user-images.githubusercontent.com/21229715/105647869-0b10dc80-5e6e-11eb-8b9e-23d2eb9f0a2a.png)

**Comment by grunbag** [comment]
for some reason BoP doesn't display on live, causing this issue.

**Comment by Lheana** [comment]
Duplicate of #12491
