### ISSUE TITLE
[Gunbad] Died when going out of instance while mounted

### ISSUE THREAD

**Issue by CrimsonFenris** [WarEmu/WarBugs#18408]
**Expected behavior and actual behavior:**
Using exit portal of gunbad while mounted leads to instant dead. Character is dead, nothing happens when releaseing, and other players dont see us as dead.

Only fix is to relog atm.

**Steps to reproduce the problem:**
Exit gunbad entrance portal while on mount.

**Comment by lilimx** [comment]
Hey,

due to the lack of information, I'll close this ticket now.
