### ISSUE TITLE
Order Attacking Forts, Problem.

### ISSUE THREAD

**Issue by Ruin-84** [WarEmu/WarBugs#18416]
**Expected behavior and actual behavior:**
Fort: Fell Landing - Beeing able to Fly to enemy Keep. Eages are orange and unable to be used this bug apreared on 26.01.2021

Fort The Maw: Disconected in Fort on last (3rd) stage attacking the Lord Room, when i reconnected to the game i was respawned in 43k, 33k.

**Steps to reproduce the problem:**
FL- tried multiple times tu use the flyer - used /rel command to and it didin't helped 
TM - no wy to test :(

**Testing Screenshots/Videos/Evidences (always needed):**

![Bronimir_ FL](https://user-images.githubusercontent.com/78111239/106051704-1ae82500-60e9-11eb-858c-a69b16be7cf9.jpg)
![Hufrad_TM1](https://user-images.githubusercontent.com/78111239/106051714-1d4a7f00-60e9-11eb-896b-fe4fc1f47072.jpg)
![Hufrad_TM2](https://user-images.githubusercontent.com/78111239/106051716-1de31580-60e9-11eb-9ce1-1d85e6ed621e.jpg)
![Hufrad_TM3](https://user-images.githubusercontent.com/78111239/106051719-1e7bac00-60e9-11eb-8814-c600efe6da25.jpg)

**Comment by Lheana** [comment]
Fixed with the Patch of 29/01/2021.
