### ISSUE TITLE
 [Gunbad] Left Boss hit for deadly and unusually high damage

### ISSUE THREAD

**Issue by CrimsonFenris** [WarEmu/WarBugs#18410]
**Expected behavior and actual behavior:**
Gunbad left boss (Glomp da Squig Masta) doing insane damage, hitting 4x per 2s instead of 1 tick each second, when in Red form (after 30% hp lef).

See screenshot for evidence.

Nothing can be done to prevent this, tanks and healers are oneshot (8k dmg on my 4k armor full invader WP in 2s timeframe).

**Testing Screenshots/Videos/Evidences (always needed):**
![Crimsonfenris_000](https://user-images.githubusercontent.com/40425011/105917184-4cea8000-6032-11eb-8fc6-2d9cabe709c4.jpg)

**Comment by lilimx** [comment]
related to #19047
