### ISSUE TITLE
Redundancy in Altdorf string for stage transitioning

### ISSUE THREAD

**Issue by CprWAR** [WarEmu/WarBugs#18419]
The word "the" appears incorrectly twice in the strings for the transition in Altdorf City Siege to stage 2. Please note that this occurs for several variants depending on the time remaining.

Repro steps:
1. Enter the siege of Altdorf on an Order character.
2. Proceed until Stage 1 has ended and observe the issue with the system message while transitioning.

Current Result (example):
Two minutes until Stage 2 of the the battle for Altdorf begins!

Expected Result (Example):
Two minutes until Stage 2 of the battle for Altdorf begins!

Please see attached screenshot for reference.

![Typo_AltdorfTransition](https://user-images.githubusercontent.com/64031906/106202429-35d69a00-61ba-11eb-955d-d4810d6d87d0.jpg)

**Comment by MaxHayman** [comment]
Suprised no one picked this up before
