### ISSUE TITLE
Guild Vault bugs until /reload

### ISSUE THREAD

**Issue by MaraIsTooNerfed** [WarEmu/WarBugs#18418]
If subject A drops or withdraws an item from the guild vault and then leaves and subject B comes and uses the guild vault, subject A gets the guild vault opening on his screen along with his inventory although he is not in range.

This is a recurring issue happening each time someone uses the vault unless subject A and B use /reload.

Please fix it as it's kind of annoying to get your screen blocked by the Vault window in the middle of whatever fight is going on.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. I will add this report to a related issue.

**Comment by lilimx** [comment]
dublicate / related to #14808
