### ISSUE TITLE
Chaos PQ CH2 Destruction of the weak stucked at stage 1

### ISSUE THREAD

**Issue by Mogrim72** [WarEmu/WarBugs#18412]
Chaos PQ CH2 Destruction of the weak stucked at stage 1, 35/40, new mobs do not respawn, unaible to proceed

![CH2](https://user-images.githubusercontent.com/78102418/106032083-1586dc80-60e1-11eb-8c13-50564c1c675c.jpg)

**Comment by Lheana** [comment]
This should have been fixed few patches ago.
