### ISSUE TITLE
Invader's Medallion Quatermaster fail to sell

### ISSUE THREAD

**Issue by Dazud** [WarEmu/WarBugs#18414]
Invader's Medallion Quatermaster in Emperor's Palace tells me "not enough money to buy that" when attempting to purchase Fortress Warbow.  My character Dazu has 61 invader medallions and subjagator warbow to trade which is the listed price for the Fortress Warbow.    

(https://user-images.githubusercontent.com/78103234/106034991-3297bd00-6099-11eb-9aaa-59b20df99275.png)

![2021-01-27](https://user-images.githubusercontent.com/78103234/106035177-6bd02d00-6099-11eb-9fef-aac805c3c3f1.png)

Thanks for all you guys do keeping this game going and improving.

**Comment by Gyurza83** [comment]
Same problem - character Gabbi.

**Comment by Undrsiege** [comment]
You might need 100 gold

**Comment by Dazud** [comment]
same character - Khorndog   One of Dazu's alts

**Comment by Lheana** [comment]
You need 50 gold to buy it, that's the reason why you get the message that you don't have enough money to purchase this item.
