### ISSUE TITLE
Salvage issue

### ISSUE THREAD

**Issue by Troc40** [WarEmu/WarBugs#18415]
When I attempt to break down an item the select screen is blank I have attempted a reloadui and logging in and out but nothing seems to work

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
Screenshot(s) please.

**Comment by Lheana** [comment]
No answer, I close the ticket.
