### ISSUE TITLE
Squig pet cannot be knocked down using a knockback?

### ISSUE THREAD

**Issue by DefVont** [WarEmu/WarBugs#18422]
M1 Squig pet can be rooted but not knocked down or punted from banish darkness ability from the knight.

![squig pet no knockdown](https://user-images.githubusercontent.com/64330047/106283092-971f6b80-6295-11eb-9f16-2ff8de558b9d.png)

Image shows banish darkness landing on the pet and causing damage, with no unstoppable immunity because it wasn't affected by the knight's ability.

**Comment by lilimx** [comment]
Hey,

so we did some test and everything works as intended.
the Squig pet can be knocked down with M1 and other SH abilities active.
