### ISSUE TITLE
[Crafting] Apothecary Passive Bonus

### ISSUE THREAD

**Issue by moondoggcavalier** [WarEmu/WarBugs#1842]
I just hit 200 apothecary and I noticed that the passive bonus is broken or at least I believe it is. 

Before I hit 200, the bonuses were:
Power +2
Stability +2

After I hit 200, the bonuses are:
Power +3
Stability +1

Now I have seen contradicting ideas of what the Level 200 bonuses should be. I believe on live the bonuses were:
Power +2
Stability +2

**Comment by genisaurus** [comment]
After testing and hunting down several ancient resources, it was confirmed that as of 1.4.8, the passive bonuses at 200 were:
Power +3
Stability +1
This is working as intended, and is not a bug.
