### ISSUE TITLE
tactics, skills, potions reporting 0 damag in tooltip

### ISSUE THREAD

**Issue by engharat** [WarEmu/WarBugs#18426]
**Expected behavior and actual behavior:**
Abilities and tactics and potions which has a numerical value (eg. rugged tactic, potion of power, etc) now show 0 (zero) as value. However the effect is correct, it is only a visual bug I think.

**Steps to reproduce the problem:**
Check tactics / abilities

**Testing Screenshots/Videos/Evidences (always needed):**

![WAR-64 2021-01-29 23-02-59](https://user-images.githubusercontent.com/16682919/106332030-3f2d3880-6286-11eb-89aa-bc32a4c189ae.png)

**Comment by Lheana** [comment]
Close your launcher and restart it, this should fix it.
