### ISSUE TITLE
Tactics, Pots, Linaments, etc not loading...

### ISSUE THREAD

**Issue by Frytan** [WarEmu/WarBugs#18425]
![](https://cdn.discordapp.com/attachments/734336606290575440/804834092473384990/unknown.png)

![](https://cdn.discordapp.com/attachments/734336606290575440/804834092473384990/unknown.png)

![](https://cdn.discordapp.com/attachments/734336606290575440/804835523981213706/unknown.png)

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
Close your launcher and restart it, this should fix it.
