### ISSUE TITLE
[WL] Master Ability's Points Forced Opportunity dont work

### ISSUE THREAD

**Issue by knickk** [WarEmu/WarBugs#18432]
**Expected behavior and actual behavior:**
White Lion Master Abilitys - Forced Opportunity and other debuffs

I´m aware of actual patch notes "NOTE: Some of these may show the wrong mastery path, or incorrect tooltips until another client hotfix."
But its not just a displaying error. Its actual not working in total for all WL´s i talked to.  

No matter how many points you spend in Master tree, FO ability dosent change in damage or debuff. Lion Pet Armor debuff (Shred) ability show correct debuff in tooltip but debuff to few.

Abilitys should grow in damage and debuff with every point you spend.

**Testing Screenshots/Videos/Evidences (always needed):**
FO
[no points spend]
![image](https://i.imgur.com/w6rLpQt.jpg)
[all points spend]
![image](https://i.imgur.com/T4yA9ts.jpg)

[test on targets]
![image](https://i.imgur.com/DRUIWbr.jpg)

[armor without debuff]
![image](https://i.imgur.com/D9TC36a.png)
[armor with debuff]
![image](https://i.imgur.com/vMmHVhf.png)
->Just 1080 debuff
Normal it should be around 1400 if you spend 9 points and 1600 if you spend all.

Lion Shred
[Tooltip]
![image](https://i.imgur.com/SfysdV0.jpg)

[on enemy]   
![image](https://i.imgur.com/Z3reNg1.jpg)

**Comment by lilimx** [comment]
Hey,

It looks like the problem has now been fixed. If your the opinion it's still up, please open an new ticket.
