### ISSUE TITLE
Queue for SC, SC starts, no option to join, and then Quitter

### ISSUE THREAD

**Issue by Rydiak** [WarEmu/WarBugs#18431]
My 6-man just had a situation where we group queued for Stonetroll Crossing (the weekend event), and no queue was shown visible on the player UI.  Then QQueuer said that a queue popped, but no option to join was presented by the UI.  Attempts to requeue/try to join were unsuccessful, and then a 10-minute Quitter debuff was given.  Affected all 6 members of my party.
![Rydiak_371](https://user-images.githubusercontent.com/15963532/106350666-655dd300-629c-11eb-95d7-a9a8859afdf2.jpg)
![Rydiak_372](https://user-images.githubusercontent.com/15963532/106350668-668f0000-629c-11eb-87f9-2a8950ac5f16.jpg)
![Rydiak_373](https://user-images.githubusercontent.com/15963532/106350669-67279680-629c-11eb-9ecd-08a7645d490f.jpg)

**Comment by DefVont** [comment]
Happening for city also, half the warband got quitter debuff with no pop

**Comment by Rydiak** [comment]
Happened again queuing for SCs as a duo.  QQueuer notifies me of a scenario pop, but no UI option to join for me or my queue partner.

**Comment by MaxHayman** [comment]
This should be fixed. If it is still an issue please reopen.
