### ISSUE TITLE
Quest: Due Recognition

### ISSUE THREAD

**Issue by abalduj** [WarEmu/WarBugs#18435]
**Expected behavior and actual behavior:**

Go to quest location and find "Lording Kylar"

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/34485420/106399789-1a1dfe80-641b-11eb-82ca-3dad78618c40.png)

"Lording Kylar" doesn't exist, while "Kylar" does.

![image](https://user-images.githubusercontent.com/34485420/106399896-adefca80-641b-11eb-8cfb-edc740b61cb1.png)

**Comment by Lheana** [comment]
Does this NPC complete the quest?

**Comment by abalduj** [comment]
After killing Kylar, it's not counted in quest as completed.

**Comment by Lheana** [comment]
If you read the quest, it does not seem like the NPC you are searching is meant to be a High Elf.
This quest works fine, I close the ticket.

**Comment by Kyeld** [comment]
Shouldn't the Kylar NPC be removed? Its still confusing for players to have two NPCs with similiar names when Kylar shouldn't even exist.
