### ISSUE TITLE
Deathstone Quarry Stage 3

### ISSUE THREAD

**Issue by Hiftem** [WarEmu/WarBugs#18443]
Stage 3 Does not allow you to destroy the Chaos Rifts.  Can't complete that stage.  Rift Furies and Flamers work as intended

**Expected behavior and actual behavior:**
Should be able to destroy Chaos Rifts, but you can't do anything with them

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
I think you meant Stage 1. And this has been fixed with the last patch.
