### ISSUE TITLE
Purchasing bug

### ISSUE THREAD

**Issue by Cesi-123** [WarEmu/WarBugs#18440]
![image](https://user-images.githubusercontent.com/55823353/106519988-b985d480-64a1-11eb-9e0b-ff7faed071fe.png)
While on my Witch Elf I was attempting to purchase a low level piece of gear, the Fighter's Embracers of Vengeance.  The game took the money, nine silver, but never gave me the items.  I got an error message saying that the item could not be moved.  It did this twice and took my money both times but gave me no items.  See the attached screenshot.

**Comment by lilimx** [comment]
Hey,

thanks for you for report. I will add it to a related issue.

**Comment by lilimx** [comment]
dublicate / related to #18896
