### ISSUE TITLE
Shadow Warrior Tactics

### ISSUE THREAD

**Issue by Xerene85** [WarEmu/WarBugs#18449]
No Quarter Tactics and Guerrilla Training tactic doesen't run correctly. I've tried to change slot of tactics like suggested in an other report answer but it was useless. 
I'm Xerene, Shadow Warrior in game. 

GG

**Comment by lilimx** [comment]
Hey,

thanks for your ticket. Please next time make sure you open separate tickets for individual issues.

**Comment by lilimx** [comment]
#17220

**Comment by lilimx** [comment]
#17950
