### ISSUE TITLE
guild vault issue

### ISSUE THREAD

**Issue by turki79** [WarEmu/WarBugs#18448]
the guild name is For Funziez and on the first of february i did buy all the taps of vault 1 to 4 only and then there was a server reboot for a hot fix maybe anyway when the server came back the vaults are back locked as if i did't pay to open and the gold is gone so the ironbank took a hit :)
![image](https://user-images.githubusercontent.com/45051573/106758850-110f7600-6643-11eb-97b5-4cd267e7150d.png)

**Comment by turki79** [comment]
update

**Comment by lilimx** [comment]
dublicate / related to  #11170
