### ISSUE TITLE
Sholdaspike of thunder and Stompas of thunder, Items appareance Bug.

### ISSUE THREAD

**Issue by chaostod** [WarEmu/WarBugs#1844]
I have bought yesterday and epic lvl 18 tier 2 item and today another lvl 18 epic tier 2 item ( Sholdaspike of thunder and Stompas of thunder) I have them equip on me but I cant see them, when I reequipe them I can see my stat changing but I cant see them on my character apparence. can someone help me please?

**Comment by Evildoor** [comment]
#1035
