### ISSUE TITLE
Can't open loot-bags

### ISSUE THREAD

**Issue by Benniausdervoss** [WarEmu/WarBugs#18447]
![Unbenannt](https://user-images.githubusercontent.com/78474606/106728362-a7747500-660c-11eb-9071-bc080734d7ed.PNG)

**Expected behavior and actual behavior:**

bags should open but they dont

**Steps to reproduce the problem:**

tried to restart and repair launcher didnt help

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Vizio101** [comment]
I just did a chapter 20 easy PQ in Elf land and can confirm this also, I am unable to open the loot bag.

**Comment by Benniausdervoss** [comment]
so let's hope, that a member of staff reads this and helps us... :-(

**Comment by Lheana** [comment]
I received several loot bags these days, and I had no issue opening them. So would need more information.

**Comment by Benniausdervoss** [comment]
Seems that it is something with the EA_Backpack_folder, i have to clean it
then i can open the bags (one time) after that i have to reclean the
folder, to open other loot.
have also problems with looting items from PQ's. There it wont help to
delete the files in the EA_Loot_Folder. Some items i can grab, some i can't

Am Sa., 6. Feb. 2021 um 16:56 Uhr schrieb Lheana <notifications@github.com>:

**Comment by Lheana** [comment]
I suggest you to use our technical support on forum or discord, because this is not a general issue, and must be related to your installation/updates.
