### ISSUE TITLE
City pop not show for all in warband.

### ISSUE THREAD

**Issue by Wraxin** [WarEmu/WarBugs#18446]
Situation from today, we que 24man, pop show only for maybe 10ppl or less, i was fast enough and use script to join.
But rest ppl nope, from 24man only 11 entered city.
Order side, never have same problem on destro.

**Comment by Hadzi-user** [comment]
We saw the same pop-problem with scenes on Destro last week.

**Comment by MaxHayman** [comment]
This should have been resolved. Please reopen if not.
