### ISSUE TITLE
Wyrmbreaker's bladestoppa - item/538784

### ISSUE THREAD

**Issue by NSKaneda** [WarEmu/WarBugs#18458]
An obvious data base bug - the item [https://www.returnofreckoning.com/armory/item/538784](url) appears in the game as "Great shield 2H) preventing it's use as alternative appearance for other shields:

![Mordoszczel_021](https://user-images.githubusercontent.com/22037960/107072970-05f54b00-67e7-11eb-9cfd-279aa7f8bf6f.png)

It's a reward for Dark Elf chapter 18 epic quest line Wyrmbreaker:

![Mordoszczel_quest](https://user-images.githubusercontent.com/22037960/107073112-3806ad00-67e7-11eb-96ae-7705cf6d251c.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch
