### ISSUE TITLE
Rally Masters Not Responding for High Elf Chapter 8 and Chapter 9 

### ISSUE THREAD

**Issue by JaqiC** [WarEmu/WarBugs#18454]
After completing my influence for Chapter 8 PQ's in Ellyrion, I went to the Rally Master at that Chapter location.  The Rally Master would not allow access to take my chapter rewards.  I moved on to Chapter 9, finished the first tier, and the Rally Master for Chapter 9 is not responding either.  I don't know if this is an isolated issue, but I definitely cannot get the rewards in Ellyrion for completing the Chapter PQ's.

Thank you!
Jackie

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
I tested it, and I could claim the rewards of the High Elf Chapters 8 & 9.
