### ISSUE TITLE
Game Settings menu is bugged on login screen 

### ISSUE THREAD

**Issue by Murthor** [WarEmu/WarBugs#18453]
**Expected behavior and actual behavior:**  
The Game settings menu should close when you click okay or the exit button, instead it stays stuck on the screen unless you exit the game entirely.

**Steps to reproduce the problem:**
Just open the Game settings menu and then try to close it while on the login menu

**Testing Screenshots/Videos/Evidences (always needed):**
![screenshot_000](https://user-images.githubusercontent.com/52479032/106893858-2c6a9780-66bc-11eb-8280-f60b6f67f53e.jpg)

**Comment by slotrun** [comment]
This bug causes the game settings to be unchangeable, and a reload of the game will display the default values. Running most recent version of windows 10, lenovo laptop.

**Comment by Tesq** [comment]
it happen also on win 7, press esc allow to close the tab tought

**Comment by MaxHayman** [comment]
Fixed
