### ISSUE TITLE
Cant make nickname / lastname if including "Hao"

### ISSUE THREAD

**Issue by Haojun-Phalanx** [WarEmu/WarBugs#18463]
![screenshot_002](https://user-images.githubusercontent.com/23129933/107125369-a49eac00-68ba-11eb-9c28-2bcb1ff81e8a.jpg)

https://gyazo.com/88b96580b245ba1e935eea873b869e23
there is no toon named "Haoju" on armory

also when you try to make a lastname including "hao" nothing happens; but you still lose the gold.

cheers.

**Comment by cimator** [comment]
Tried the lastname thing, it really doesnt let you use "hao" as lastname :D weird bug

**Comment by MaxHayman** [comment]
Phrase was banned not a bug. If it is still an issue open a ticket in game.
