### ISSUE TITLE
Items disapeared each time i zoning

### ISSUE THREAD

**Issue by moblot72** [WarEmu/WarBugs#1846]
Hello, got a bug since few days, each time i buy something with my chosen robinait (or take influ reward), and travel to another zone/disconnect, all stuff acquired disapeared. 

So i can't buy nothing or take no reward cause they ll disapear when disconnect or changing zone.

Thank you

**Comment by Evildoor** [comment]
Seems similar to #1808.

**Comment by moblot72** [comment]
the problem is every item in inventory fade when zoning.
If a buy a bottle of water for example, it disapears if i zone 1 min later.

**Comment by moblot72** [comment]
Server restart and i lost more items.

**Comment by Evildoor** [comment]
This problem still persists?

**Comment by Evildoor** [comment]
No response, closing.
