### ISSUE TITLE
"Primal Mighty Debris" cannot be used to make a talisman

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#18460]
**Expected behavior and actual behavior:**

I should be able to put this crafting material in the crafting window, but it doesn't

**Steps to reproduce the problem:**

Get a "Primal Mighty Debris" (epic quality strength lvl 75 material), and try to add to the talisman crafting window

**Comment by lilimx** [comment]
Hey,

it work as intended.
![grafik](https://user-images.githubusercontent.com/23266079/123763048-b1e92100-d8c3-11eb-9299-4d8a94e45b89.png)

![grafik](https://user-images.githubusercontent.com/23266079/123762958-97af4300-d8c3-11eb-9833-eb73b635762b.png)
