### ISSUE TITLE
BW Offensive Sov 7pc bonus is wrong (Focused Affliction)

### ISSUE THREAD

**Issue by emailkook** [WarEmu/WarBugs#18465]
**Expected behavior and actual behavior:**

7pc bonus for Bright Wizard offensive Sov set should increase damage by 5% when it procs.
Actually it is only doing 4% per the tooltip of the actual proc when it goes off (Focused Affliction)

**Steps to reproduce the problem:**

Put on the 7pc offensive sov set and hit the dummy until it procs and you can hover the mouse over their debuff.

**Testing Screenshots/Videos/Evidences (always needed):**

![bw-sov-1](https://user-images.githubusercontent.com/50253609/107132196-8dec5b00-68a2-11eb-8ba9-a4ac17754124.gif)
![bw-sov-2](https://user-images.githubusercontent.com/50253609/107132200-9349a580-68a2-11eb-8268-bf8a8ca26ef9.gif)

**Comment by lilimx** [comment]
hey,

this is the same like in this ticket for Sorc  #18876

**Comment by emailkook** [comment]
Why are both tickets closed when the issue still isn’t fixed? Still does 4%
damage by both sorc and bw when should be 5% from the set bonus.
