### ISSUE TITLE
Warrior Priest Great Weapon Abilities Icons are Grey

### ISSUE THREAD

**Issue by Brumaires** [WarEmu/WarBugs#18469]
![Schelling_019](https://user-images.githubusercontent.com/77127959/107242971-da63a200-6a2c-11eb-95d9-0457bb3ec0f2.jpg)
Hello,

As you can see on the picture, I am using a great weapon, yet abilities on my hotbar requiring that sort of weapon, such as Sigmar's Wrath, Unstoppable Wrath and Soulfire, have their icons displayed in grey. I can use the abilities, they work, but whenever I do so I have an error message in the middle of the screen telling me "Requires Great Weapon".

**Comment by Rydiak** [comment]
Usually this is the result of an outdated client.  Exit the game and use the Repair function to verify your files.

**Comment by Brumaires** [comment]
Thank you for your answer. I have repaired the game, twice, unfortunately the issue is still there

**Comment by Brumaires** [comment]
Update : I've changed of 2 hander just right now, I used to have one from RvR Loot Bags, now its a scenario weapon that I am using, and that bug is gone, icons aren't grey anymore and no error messages

**Comment by Lheana** [comment]
Then I close the ticket.
