### ISSUE TITLE
Lion pet and stealth We

### ISSUE THREAD

**Issue by Bignusty** [WarEmu/WarBugs#18461]
Hi all !

I noticed a thing whit my pet , when you see a WE around stealthed i cant command my pet to attack her im the only one who r able to attack her

Thx

**Comment by lilimx** [comment]
Hey,

Thank you for your ticken.
We need a few pictures or even better a short clip.

**Comment by lilimx** [comment]
Hey,

im going to close this ticket now due to no feedback.
