### ISSUE TITLE
dwarf rvr influence reward

### ISSUE THREAD

**Issue by Kouba85** [WarEmu/WarBugs#1847]
Hi i have take my influence reward from dwarven rvr and the helmet is shown in the middle of the body not on the head. Helemets name is Karak casque.
![screenshot_000](https://cloud.githubusercontent.com/assets/15944509/11303188/dca36962-8fa1-11e5-939e-65b60ef32edb.jpg)

**Comment by DanaBloodkiss** [comment]
Fixed in next.
