### ISSUE TITLE
Post-Feb 11 patch my main hand weapon doesn't show up and the game thinks I'm not wielding it

### ISSUE THREAD

**Issue by Delegator2** [WarEmu/WarBugs#18485]
**Expected behavior and actual behavior:**

I am wielding a Mititempered Hammer, which was just fine last night. However, upon logging in after the patch, the game thinks I'm not wielding it. In the screenshot you can see:

1. My cursor is hovering over my main hand slot, and the weapon pop-up is there but the slot looks empty
2. The abilities in my ability bar that require a melee weapon are disabled (greyed out)

**Steps to reproduce the problem:**

No idea. This just happened. I tried a /rel to reload my UI. I also exited the game and used the Repair in the launcher to repatch and clean up. None of that helped. I have not yet had the opportunity to try wielding a different weapon and determine whether this is a problem with the item or the character.

**Testing Screenshots/Videos/Evidences (always needed):**

![Screen Shot 2021-02-11 at 6 25 48 PM](https://user-images.githubusercontent.com/77587188/107712127-d9ce4400-6c96-11eb-9c61-842b041cad86.png)

**Comment by Delegator2** [comment]
I obtained a different weapon, and the second weapon works while the first is still bugged. It seems to be an issue with the Mititempered Hammer.

**Comment by Kabucoror** [comment]
fixed with next patch
