### ISSUE TITLE
Chaos T4 epic quest 'Annihilation'

### ISSUE THREAD

**Issue by Naelar** [WarEmu/WarBugs#18486]
**Expected behavior and actual behavior:**
As you can see from the screenshots below, the npc does not show the quest on my Magus, but does show it on my Zealot.  My magus did an earlier version of the T4 epic when it was called 'Voices From Within'.  Could this be causing the issue?

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**
For Magus, npc does not show the quest, and it isn't in the quest log:
![2021-02-11 (1)](https://user-images.githubusercontent.com/61371494/107734696-a5bd4800-6cc3-11eb-97a1-424ea9e6383b.png)

For Zealot, quest is available:
![2021-02-11 (2)](https://user-images.githubusercontent.com/61371494/107734722-b1a90a00-6cc3-11eb-8b56-63f5b21284f8.png)

**Comment by Kabucoror** [comment]
Have you tried to speak to every questgiver in the quest chain? Maybe you can pick it up at some point.

**Comment by Naelar** [comment]
That worked!  I was able to pick it up in Step 4 (Talk to Jaust).  Thanks!
