### ISSUE TITLE
Cannot group queue for scenarios.

### ISSUE THREAD

**Issue by TVBrowntown** [WarEmu/WarBugs#18481]
Unable to group queue after new patch using addon QueueQueuer and Default Queue System. Nothing occurs when attempting to queue as a group. Cannot queue for any scenarios in a party.

_Steps to reproduce the problem:_

Form party, queue for scenarios using join all feature and/or individual maps.

_Testing Screenshots/Videos/Evidences (always needed):_
![alt text](https://i.ibb.co/1qNfxr5/WAR-64-2021-02-11-21-45-32.png)

In above image I tried blacklisting Caledor Woods and queuing for all using QQer, I also tried queuing just for Logrin's using default system in party. Changed leader to friend who could not queue. Broke party and disabled QQer, tried to queue using default Join All and didn't work. reactivated QQer. Still not working. Before starting the game I had also cleared the cache folder.

**Comment by lilimx** [comment]
Hey,

is this still an issue?

**Comment by TVBrowntown** [comment]
Has been fixed
