### ISSUE TITLE
Ridicules amount of rp, exp and inf from orvr

### ISSUE THREAD

**Issue by Morksezstop** [WarEmu/WarBugs#1848]
It seems like ppl could get really ridicules amounts of exp, inf and rp after keep take. 
<a href='http://postimage.org/' target='_blank'><img src='http://s3.postimg.org/hzhou9ahv/orvr.jpg' border='0' alt="orvr" /></a><br /><a target='_blank' href='http://postimage.org/'>image upload</a><br /><br />

that i took for barely 3-5 min healing on 1st floor into the keep. And such numbers are not some rare occurrence. These kind of numbers are easy reachable on almost every keep take when your realm got certain amount of kills
That kind of orvr encourage zerging, blobing, pveing and xrealming for renown. While we got such high rewards for doing nothing more than just to presence at the keep you will see the ugliest side of WAR

IMO this is bug that need to be fixed

**Comment by Tesq** [comment]
i was log for the most keep take today and never saw such rewards, was that from order def tonight? maybe it have to do wich contribution to lock from kills?

**Comment by Morksezstop** [comment]
it was on destro and i got it like 2-3 times at the only 2-3 times i ever went at orvr. Since t3 It could be fixes, no idea didnt step at orvr....

**Comment by Luth-RoR** [comment]
RvR mechanics have been changed and reworked.
