### ISSUE TITLE
[BO]Fortress vendor listing

### ISSUE THREAD

**Issue by Pvpve** [WarEmu/WarBugs#18490]
**Expected behavior and actual behavior:**
The listing is showing two times the exact same offensive 2 hander weapon named "Fortress Bigchoppa" instead of the expect offensive and defensive version as is shown with the one-hander.

**Steps to reproduce the problem:**
Go to the Fortress weapon vendor as a bo and open the item listing with a right click on the npc.

**Testing Screenshots/Videos/Evidences (always needed):**
![screenshot_Pvpve](https://user-images.githubusercontent.com/78989366/107835622-7dece380-6d9a-11eb-8f27-07d6d82ca198.jpg)

**Comment by Kabucoror** [comment]
This is correct as you see both buy options from BO and Choppa for the 2h weapon. A defensive 2h fortress weapon doesn't exist.
