### ISSUE TITLE
Fake toggled auras 

### ISSUE THREAD

**Issue by baest96** [WarEmu/WarBugs#18498]
Hi
I found something i assume is a bug. When i respecialize my mastery, it show my auras as being toggled on in the actionbar, but as you can see in the picture, they are toggled off at portrait. I just went through a dungeon assuming they were on, and dont know if it can be fixed, but atleast you are now aware. 

- Baest

![image](https://user-images.githubusercontent.com/79054256/107883092-11362e00-6eed-11eb-988f-77830726d4a9.png)

**Comment by lilimx** [comment]
Hey,

could you check if this issue still persists? please check if the aura really affects your stats (use .getstats) and do some screenshots.

Thank you!
