### ISSUE TITLE
Guild Heraldry - Saving Guild Heraldry Creation 

### ISSUE THREAD

**Issue by Tneebs** [WarEmu/WarBugs#18494]
**Expected behavior and actual behavior:**

- Guild rank level 10 gives access to creating Guild Heraldry. 

- Attempted to create Guild Heraldry at guild rank 10, 15, and 20. 
- Heraldry does not save. 
- Does not show on Cloaks or Standards 
- Does not show on guild profile page 

**Steps to reproduce the problem:**

I have attempted to create and save our Guild Heraldry 3 different times. Once at each guild rank 10, 15, and 20. Every time I have tried to save the creation, it says NOTE: This will cost 0 1722.

- I have deposited 20+ gold in the guild bank thinking that could help, but it did not work. The creation at save says the same as above.

- I am the guild leader as well

* My assumption is that it has something to do with the guild tax. Assuming most people would put a tax on their guild and some sort of gold was coming in, would be used to create the heraldry.

* Screenshots below show me attempting to create and save the Guild Heraldry. They show the warning notice before creating that it will cost 0 1722. The last screen shot is of the guild profile page, as well as my character showing the guild heraldry on the cloak, to show that the guild heraldry did not save.

**Testing Screenshots/Videos/Evidences (always needed):**

![ROR_GH_ERR1](https://user-images.githubusercontent.com/64165421/107872829-bfe95880-6e72-11eb-9af7-5769a0a8fcfa.png)

![ROR_GH_ERR2](https://user-images.githubusercontent.com/64165421/107872833-c37cdf80-6e72-11eb-8fa2-049cbb59d281.png)

![ROR_GH_ERR3](https://user-images.githubusercontent.com/64165421/107872834-c677d000-6e72-11eb-848e-60f1b6eaf5e1.png)

**Comment by lilimx** [comment]
Hey,

thank you for your detailed description. I will add it to a related issue

**Comment by lilimx** [comment]
related to #9791
