### ISSUE TITLE
WB SC "Grp not supported" = DC of entire WB. 

### ISSUE THREAD

**Issue by Waaughhammer** [WarEmu/WarBugs#1849]
Tried to join my WB to Nordenwatch Scenario ("Join as Group"); apparently that was a bad idea.  Got a msg that more or less said that joining entire warbands to Scenarios is not presently supported and then, a second later, the entire WB seems to have DCd, including me, ofc.  I believe it left a shell of itself (abt 6 ppl) showing in Open WB finder, but me trying to join that at relog re-caused me to DC.  

CAVEAT:  I had already used "Join All" on myself before trying to join the whole grp up, then tried to back out of that by joining the WB to Nordenwatch specifically, thinking Norden was needed in particular for T1 lock.  Maybe I caused a conflict?

My apologies if this is just me being n00b as frak as a WB ldr, but I was thinking maybe this is one reason why so many WBs DC.

**Comment by Luth-RoR** [comment]
Joining scenarios while being a member of a warband is deactivated on purpose afaik.
