### ISSUE TITLE
[Dark Elf][Chap 14] NPC appears as Merchant but is not

### ISSUE THREAD

**Issue by gamerlenny** [WarEmu/WarBugs#18499]
At Dark Elf chapter 14 camp, NPC quest giver "Trelan Blightblade" has the appearance of a merchant but he's not actually one - he has the title, overhead icon and buttons of a merchant but clicking on "Browse wares" in his bubble does not do anything, he can only be interacted with to get or complete quests, and there already is a real, funcional merchant NPC nearby in the camp. 

**Expected behavior and actual behavior:**
Trelan Blightblade should be a regular quest giver NPC, he should not have the merchant title and icons

**Testing Screenshots/Videos/Evidences (always needed):**
![Gaernith_002](https://user-images.githubusercontent.com/2891053/107988889-3b611c00-6fd1-11eb-92a4-f5b2aeb01361.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch
