### ISSUE TITLE
Force Opportunity not getting contribution from HunterTree [WL]

### ISSUE THREAD

**Issue by Haojun-Phalanx** [WarEmu/WarBugs#18496]
Hunter 15 points / Axeman 0 points = 1000 armor debuff (it's not a tooltip bug, tested on a guildie bo via .getstats)

![Choppapullop_022](https://user-images.githubusercontent.com/23129933/107880164-26f82300-6eee-11eb-82a2-267dac6d82a7.jpg)

Hunter 9 points / Axeman 15 points = 1600 armor debuff
![Choppapullop_023](https://user-images.githubusercontent.com/23129933/107880191-4d1dc300-6eee-11eb-97d9-60296a7061bd.jpg)

![wlarmordebuff](https://user-images.githubusercontent.com/23129933/107880413-9cb0be80-6eef-11eb-8253-57a45814f0af.png)

**Comment by lilimx** [comment]
Hey,

It looks like the problem has now been fixed. If your the opinion it's still up, please open an new ticket.
