### ISSUE TITLE
After restart lost my inflence gear.

### ISSUE THREAD

**Issue by Mazadun** [WarEmu/WarBugs#1850]
I was on T2 , leveld unflence to max with ostland(3 pieces) and with orcs (2 pieces) , bought gear. I left in bags.( in was yeaster day 11.20.2015) Today 11.21.2015 i log in and coulnd find it.
Character - Spelleater

**Comment by Evildoor** [comment]
Item loss is a known bug which has no solution so far. Dev policy is "no refunds" for now, so the only thing you can do is hope that when server restarts items will return. If they don't - tough luck, but that's how it stands.
