### ISSUE TITLE
Ignore issues.

### ISSUE THREAD

**Issue by Stahn456** [WarEmu/WarBugs#18500]
**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

The /ignore command isn't blocking messages from players you have on that list but join warbands you are in. I'm having issues with grieving jerks who join every open warband i join just to harass me. Its annoying. This function should cover ALL sources of the ignored player. It currently is not and should be addressed so that it does. The spamming is getting tiresome, as is the lack of response in punishing those doing it.

**Comment by MaxHayman** [comment]
This is intended. Guilds/Parties/Warbands can be self controlled. Although this seems to be a bit out of the norm, I would contact a game master with as much "evidence" as you can.
