### ISSUE TITLE
Engineer Main Hand "Hammer of the Decayed" can't be used as an appearance item

### ISSUE THREAD

**Issue by Tyrannicus** [WarEmu/WarBugs#18507]
"The Main Hand slot may never have it's appearance customized" is the message I receive when I try to use this Engineer weapon as an appearance item. 

Equip any Engineer melee weapon. Try to apply appearance using Hammer of the decayed and I receive the message shown above.  I've equipped the weapon and it is bound to my character. 

This is one of the coolest looking Engineer appearance items! This item should by all means be able to be used as an appearance item. The artwork on this weapon is amazing and perfectly embodies the Engineer class.

**Comment by Kabucoror** [comment]
fixed with next patch
