### ISSUE TITLE
Making arena actually usable 

### ISSUE THREAD

**Issue by Aesur1** [WarEmu/WarBugs#18503]
Hello i am writing here as suggested from discord, making one long post for everything i want to say.

First the aerna is a great idea but it works actually for 1v1, the momento you start having 2v2 till 6v6 buff, aura from kobs and chosen, group healing and other stuffs wont work, aswell the morale gains. 

As I said is a pity cause i think is a really cool feature cause allow to people from the same realm to fight eachother and in some guilds or alliance thsi tool could be used to improve people. I dunno if arena is already working for 24 vs 24 so wb versus 2wb, but could be again an incredible add to this feature, cause recently small scale group and guild start looking for equal fights that could be ruined by some randoms, that usually hangs around and also help people with chars in one faction only to do some fights against their friends. 

If you need details or screen i can provide them with time and with different situation but they require times, atm i am posting my and others feedback and tests in arena.

I know is not a primary problem here but arena is cool, maybe can help to boost fights and content with people that can see what is happening, just dont forget about your ideas cause they can be used very well!

Best Wishes

Aesur

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
I'll close this ticket now, because it doesn't contain any bug report.
If you want to write a suggestion please use the forums: https://www.returnofreckoning.com/forum/viewforum.php?f=15
