### ISSUE TITLE
Night of murder cape vanished after i toggled heraldry on my normal cape

### ISSUE THREAD

**Issue by Houngar** [WarEmu/WarBugs#18501]
I dont have any screenshots or video but after completing night of murder event i got the cape however after i toggled show guild heraldry on my normal cape (im a new player and was exploring features) my event cape was gone. 

It was in my appearance tab however upon toggling back i could not get the event cape to show and upon inspection it was gone from the appearance tab. 
![Houngar_020](https://user-images.githubusercontent.com/79128951/108021210-0f9f5f80-6fec-11eb-930e-2d9733b2f886.jpg)

**Comment by Houngar** [comment]
Sorry if this is not proper, 1st time on github and hope you have a wonderful day!

**Comment by Kabucoror** [comment]
Did you slot another cape? Because the alternative appearance sticks to the item.

**Comment by Houngar** [comment]
> 
> 
> Did you slot another cape? Because the alternative appearance sticks to the item.

thanks, that solved it! closing :)
