### ISSUE TITLE
Walking into BS teleports you to your binding location [Destro]

### ISSUE THREAD

**Issue by Stophy22** [WarEmu/WarBugs#18518]
**Expected behavior and actual behavior:**
Trying to walk into BS right now seems to teleport you to your binding location from the destro side of map
Expected behavior is creating a group and being teleported into the instance. 

**Steps to reproduce the problem:**
Walk into BS with a full party of 6 from destro side teleports you to book of binding location. Walking into BS from the order side of Chaos wastes teleports you into the instance. Destro portal is bugged.

**Testing Screenshots/Videos/Evidences (always needed):**
I could give you loading screens here but I think its self explanatory

Just tested, Order portal seems to work. (the portal that is in Chaos wastes that has the bridge right behind it.)

**Comment by tog89** [comment]
Order group experiencing the same behavior.

**Comment by MaxHayman** [comment]
Will be patched next hotfix. Use the portal on CW side for now.
