### ISSUE TITLE
Tzeetch Cordial getting applied at 14,16,17 seconds

### ISSUE THREAD

**Issue by Stophy22** [WarEmu/WarBugs#18513]
**Expected behavior and actual behavior:**
Zealot hot gets put on targets for 14-17seconds rather than getting put on the target for 15 seconds. The initial application gets put on for 15 seconds but after that it seems to apply at anywhere from 14-17 seconds. Not sure if tooltip is wrong but it does say it'll get applied for 15 seconds. 

**Steps to reproduce the problem:**
Make zealot, cast cordial, cast cordial again, keep casting cordial. Watch as the buff applies at different seconds ranging from 14-17. I am unable to test the ticks to see if it like ghost tickets for 2 seconds but its a weird visual bug or a strange buff to have ur hot apply for 2 extra seconds. 

**Testing Screenshots/Videos/Evidences (always needed):**
![Guywhoheals_001](https://user-images.githubusercontent.com/23489906/108337468-60e95380-7192-11eb-89d8-9ab0aba83e8d.jpg)
![Guywhoheals_002](https://user-images.githubusercontent.com/23489906/108337471-6181ea00-7192-11eb-9778-6d920939b890.jpg)
![Guywhoheals_000](https://user-images.githubusercontent.com/23489906/108337472-621a8080-7192-11eb-94ac-71f2448c7d4e.jpg)

**Comment by cimator** [comment]
Its because of the new hot/dot mechanic. Works for all "over time" abilities in the game. Lets say there is 2 seconds left for the next tick, when you refresh it, it will wait for the tick, and add the 15 seconds after it, where you'll see the 17sec hot.

**Comment by Stophy22** [comment]
ah thanks didnt know always thought it was odd
