### ISSUE TITLE
[AM] Storm of Cronos unaffected by Tranquility

### ISSUE THREAD

**Issue by Bjynt** [WarEmu/WarBugs#18511]
[

**Expected behavior:**
Increased damage by 25% or reduced cooldown

**and actual behavior:**
Tranquility has No impact

**Steps to reproduce the problem:**
use SoC without stacks, then add Tranquility stacks and use SoC

**Testing Screenshots/Videos/Evidences (always needed):**

![Shaheena_002](https://user-images.githubusercontent.com/22177300/108288873-46f54400-7185-11eb-8777-6038ecd22dd2.jpg)

**Comment by lilimx** [comment]
Hey,

as you wrote, Tranquility has no impact, because there is no intended cd decreaser or dmg increaser.
![grafik](https://user-images.githubusercontent.com/23266079/123763966-9f231c00-d8c4-11eb-8967-c09717514c3a.png)
