### ISSUE TITLE
[SW] Shadowstep swapped with Swift strikes in mastery tree

### ISSUE THREAD

**Issue by HerkRoR** [WarEmu/WarBugs#18519]
**Expected behavior and actual behavior:**
Looking at the patch notes, Shadowstep should now be available at 5 points in the Assault tree, and Swift strikes should now be a core ability in the same tree. I have it the other way around: Shadowstep as a core ability, Swift strikes at 5 points in the mastery tree. I'm actually able to use Shadowstep as it is available to me as a core ability, while Swift strikes isn't, and thus of course I can't use it.

**Steps to reproduce the problem:**
No idea, as I didn't do anything special and notice the problem recently, so I don't know when it occurred. Some 15 days ago I respecced and chose Shadowstep in the mastery tree, then respecced back to no points in Assault tree some few hours later.

**Testing Screenshots/Videos/Evidences:**
![Bug shadowstep](https://user-images.githubusercontent.com/26221439/108369379-d2a9b780-71fb-11eb-8db6-b773d241c5ee.jpg)

**Edit: Closing the issue because while it does not appear in the patch notes, having Shadowstep in core abilities is intended.**

**Comment by Garrthax** [comment]
Are you able to read? Read the fckin patch notes!

**Comment by Garrthax** [comment]
> **Expected behavior and actual behavior:**
> Looking at the patch notes, Shadowstep should now be available at 5 points in the Assault tree, and Swift strikes should now be a core ability in the same tree. I have it the other way around: Shadowstep as a core ability, Swift strikes at 5 points in the mastery tree.
> 
> **Steps to reproduce the problem:**
> No idea, as I didn't do anything special and notice the problem recently, so I don't know when it occurred. Some 15 days ago I respecced and chose Shadowstep in the mastery tree, then respecced back to no points in Assault tree some few hours later.

Are you able to read? Read the fckin patch notes!

**Comment by HerkRoR** [comment]
@Garrthax Should I've been wrong, this is not an excuse replying harshly like you did. In that case, one can just point to the mistake with respect. But nothing new under the sun, "haters gonna hate".
It seems although I'm correct, all the same. So, gloves off, you can shove yourself up the following screenshot where the sun doesn't shine.
![Patch notes 25 12 2020](https://user-images.githubusercontent.com/26221439/108402397-bd458500-721d-11eb-8f32-19c3e83fc2d3.jpg)

**Comment by Garrthax** [comment]
@HerkRoR all jumps on all classes were moved to core

**Comment by HerkRoR** [comment]
"respect must be earned" -> You haven't earned mine ;)
I don't think I'm the one "having a problem", nonetheless and as it appears there are fundamental discrepancies in our respective philosophies, there's no point to discuss further on that subject here.
