### ISSUE TITLE
BB/BE autopassing loot due to a lockout that none of us have

### ISSUE THREAD

**Issue by redwolf777x** [WarEmu/WarBugs#18514]
https://gyazo.com/3463a571ea57d7cbe2ee96d48a97fad8

**Comment by MaxHayman** [comment]
Can you show the "instance id" maybe the .lockouts output if you can

**Comment by redwolf777x** [comment]
> Can you show the "instance id" maybe the .lockouts output if you can

https://gyazo.com/f3b224500762d3ac87743d73c621a2e6

how can i get instance id?

**Comment by MaxHayman** [comment]
It should pop up when you first went into the region e.g. "49898ff2-edfb-4df7-be36-1f4b5c4494f7"

**Comment by redwolf777x** [comment]
> It should pop up when you first went into the region e.g. "49898ff2-edfb-4df7-be36-1f4b5c4494f7"

https://media.discordapp.net/attachments/575457165096124458/811935862010544128/unknown.png

**Comment by redwolf777x** [comment]
confirming BE aswell 

chat lockout screenshot: 
https://gyazo.com/f5121613a532b905034ddb02c3234b42

instance ID: https://media.discordapp.net/attachments/282256627522863105/811940612596957184/e21e788b6cb1bc862e5f1ffee586d3e1.png

**Comment by MaraIsTooNerfed** [comment]
![image](https://user-images.githubusercontent.com/66925719/108359221-067ee000-71f0-11eb-8066-1d574ab45dc5.png)

Happened in CnT as well.

Don't have the instance id.

**Comment by badoglio170389** [comment]
i can add mine too, we had the same problem
![lockouts](https://user-images.githubusercontent.com/72200276/108366789-0a633000-71f9-11eb-9b7f-34c68b8425ba.png)

**Comment by MaxHayman** [comment]
Should have been fixed after hotfix earlier today.
