### ISSUE TITLE
extra damage with res illness

### ISSUE THREAD

**Issue by Niblolkik** [WarEmu/WarBugs#1851]
on slayer when i get res (level 9) im doing massive damage

**Comment by Niblolkik** [comment]
using aoe

**Comment by Uchoo** [comment]
I have also seen this bug before. Sometimes, a person with Resurrection Sickness has a very strange value to a stat with .getstats. I have seen a White Lion with -32,xxx Strength and doing ridiculous damage, but we haven't seen this bug in a couple of weeks.

**Comment by Luth-RoR** [comment]
Should be fixed.
