### ISSUE TITLE
Righteous Fury or Soul Essence sometimes not given by Book or Chalice item for DOK or WP

### ISSUE THREAD

**Issue by bloodmasked** [WarEmu/WarBugs#18512]
Expected behavior and actual behavior:
When I have a chalice my soul essence should climb by 8 every second including while in combat. Instead it just stays the same.

Steps to reproduce the problem:

I enter combat and try to heal, my essence does not rise. To fix this problem, I have to exit combat and unequip and re-equip my chalice.

Testing Screenshots/Videos/Evidences (always needed):

I look at my soul essence and it does not climb by 8 essence every second, it remains at same value in combat.

**Comment by Rydiak** [comment]
https://github.com/WarEmu/WarBugs/issues/17435

Well documented, but sadly a recurring problem. As noted, unequip and requip to fix.

**Comment by Lheana** [comment]
This has been fixed with the patch of 08/05/2021.
