### ISSUE TITLE
[Visual] [Abilities?]

### ISSUE THREAD

**Issue by Syzako** [WarEmu/WarBugs#18517]
**Expected behavior and actual behavior:**

Kein as witch elf:

![image](https://user-images.githubusercontent.com/39750677/108366395-6dca7d80-724c-11eb-91d5-8c64d30074b3.png)

![image](https://user-images.githubusercontent.com/39750677/108366834-e9c4c580-724c-11eb-93ff-1e41632b0b6e.png)

Having as witch elf:
1) animation of skills
2) motion animation
3) weapon appearance

Inspect inventory is disabled.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. I guess this is some sort of visual glitch that happens from time to time.
