### ISSUE TITLE
[Night of Murder] Archivement not counted for Live Event 

### ISSUE THREAD

**Issue by waerter** [WarEmu/WarBugs#18510]
**Expected behavior and actual behavior:**
Hi 
I've Killed a guild Leader in open RVR for the "Night of Murder"-Event. My Archivement Tab shows the Archivement but it is not counted against my influence.

**Steps to reproduce the problem:**
I cant reproduce it because I already have the archivement. 

![Rindarel_000](https://user-images.githubusercontent.com/62266826/108261493-020ce580-7164-11eb-9e5a-8d9b8c8e1f30.jpg)
![Rindarel_001](https://user-images.githubusercontent.com/62266826/108261503-05a06c80-7164-11eb-80a2-61be1f7ec0d6.jpg)

**Comment by waerter** [comment]
I did finish the last task, but could not get the cloak.

![Rindarel_002](https://user-images.githubusercontent.com/62266826/108271009-7d749400-7170-11eb-9fe9-55ecd58b181c.jpg)

**Comment by Lheana** [comment]
I close the ticket as the event is no longer active. Moreover I did it myself, and I remember it worked.
