### ISSUE TITLE
Bastion Stair [General Issues] Kaarn Fight Infinite Respawn/Auto-Pass

### ISSUE THREAD

**Issue by Stophy22** [WarEmu/WarBugs#18520]
**Expected behavior and actual behavior:**
So tested BS after the most recent patch and a few bugs happened. You can infinite respawn in BS dungeon during Kaarn fight. ( I suspected it was any instance boss but was unable to test. And the Bosses (all bosses) auto pass on loot saying you have lockouts. Someone reported the autopassing on loot bug already but it was only for BB/BE.https://github.com/WarEmu/WarBugs/issues/18514

 Now the issues has spread to BS, so I wanted to inform the team.

**Steps to reproduce the problem:**
Enter BS, kill a boss, watch as loot auto passes.

Enter Kaarn the Vanq fight and if you die, respawn and you will stand back up exactly like the old bug for Left wing Gunbad Squig herder instance boss. Can also confirm this happens on every boss, not just kaarn.

**Testing Screenshots/Videos/Evidences (always needed):**

Instance number of Kaarn Fight captured in bottom picture. Top picture has the Auto pass loot issue in chat.
![Archea_002](https://user-images.githubusercontent.com/23489906/108372726-56dc4a80-71bc-11eb-9efd-9b069b770b98.jpg)
![Archea_000](https://user-images.githubusercontent.com/23489906/108372784-65c2fd00-71bc-11eb-9a5e-e598875c2573.jpg)

**Comment by lilimx** [comment]
Hey,

im going to close this ticket now. According to your BB/BE reference (#18514) it was fix a day after your thread. Additional I was already in BS and this issue no longer occurred. 
If you're the opinion the issue still exists, please open a new ticket and refere to this one (just add, #number)
