### ISSUE TITLE
Quest - Bred, Fed, and Led - Chaos Ch11

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#1852]
Thordis Valdar gives all three stages of the quest at the same time.

**Comment by wargrimnir** [comment]
Same with Serpents Fang Negotiator, who is part of the quest chain.

**Comment by genisaurus** [comment]
Fixed in next patch

**Comment by M0rf** [comment]
To add to this the tower where it requires you to collect the item, the doors are closed so you cant progress the quest

**Comment by M0rf** [comment]
Serpents fang negotiator is unkillable, should turn from friendly to hostile after u turn the quest in, possible like fixes to other similar quests to just require a click of the npc instead of kill ?
