### ISSUE TITLE
Guild Banner buggy

### ISSUE THREAD

**Issue by bleifuss22** [WarEmu/WarBugs#18521]
Today I lost 2 guild banners. It is not possible to put back/restore a banner after using it.
You only can expand the banner, but cannot restore to bag. I lost 4Gold about to buy new guild banner...  "Snipeleon"

**Comment by Caduceus42** [comment]
Having the same issue here. 

I can deploy the standard, but when I try to stow it nothing happens. The cast bar also says "Deploy standard" (instead of stow).

**Comment by Misteria** [comment]
Same issue here, not possible to remove the banner when it's in your hands.

**Comment by anthiquery** [comment]
same here

**Comment by DarkFaenix** [comment]
same here, it was working fine a couple of patches ago. You either need someone to pick up your planted banner or to book/scroll/fly out of zone to get it back.

**Comment by dalen** [comment]
Fixed in the 2021-03-18 patch
