### ISSUE TITLE
Missing barber in Altdorf

### ISSUE THREAD

**Issue by pattonb** [WarEmu/WarBugs#18528]
The Barber is missing in Altdorf city, for a few days now - since the end of the recent Khaine event. It's no longer in it's current place within Altdorf.

![Untitled](https://user-images.githubusercontent.com/16368149/108610074-fe5da680-738f-11eb-9d71-53dd40c785b9.png)

**Comment by Zydna** [comment]
Hmm, I can see the barber surgeon. Maybe he was on a stroll when you looked for him :-)

**Comment by bloodmasked** [comment]
type /reload should show missing NPCs

**Comment by lilimx** [comment]
Hey,

I guess the problem has been resolved.
