### ISSUE TITLE
Ard ta Feed and Solithex despawning during fight.

### ISSUE THREAD

**Issue by lovemachine-ror** [WarEmu/WarBugs#18522]
Today in a Gunbad run, Ard ta Feed despawned entirely along with all his adds and floor-hazards before even reaching 80% (the first trigger for buttons to appear). Solithex also despawned entirely, but much later in the encounter after 2 waves of adds and 5-7 self-heals, at about 40% health. When we left the bossroom and attempted to re-enter, we got the "Cannot zone in, encounter still in progress" message. 

We had completed 2 full runs of Left and Right, with all scripts working perfectly and no weird boss behaviours. None of the bosses prior to Solithex and Ard ta Feed in Mid did anything weird either. This occurred on Destro at approximately 15:30 UK time. One original member of the group was replaced before beginning Mid.

**Comment by dalen** [comment]
This should be fixed now
