### ISSUE TITLE
Attackable doors which shouldn't be

### ISSUE THREAD

**Issue by Jinxypie** [WarEmu/WarBugs#18524]
**Expected behavior and actual behavior:**

Not sure if the door to queue portal was always attackable, but you can definitely kill them now. Which is not a problem if they are open, but if they die closed, they remain closed till respawn and ppl cant get to queue.

**Steps to reproduce the problem:**

kill city door when closed

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by MaxHayman** [comment]
Altdorf or IC?

**Comment by Jinxypie** [comment]
IC. heres a screen [https://i.ibb.co/f91C384/Gangstagit-024.jpg](url)

**Comment by saschaki** [comment]
Related to this. It is not just city doors. I am currently at Schwenderhalle Manor in Reikland and some people hunker down inside and keep their morales high while attacking the door.

**Comment by Sivine** [comment]
Here is video proof : 
https://imgur.com/a/1TjBDS7
This also happens on the gates that rises in Alt during city, and I saw that also happened on doors in IC that let's you in the palace in regular IC

**Comment by Sivine** [comment]
Another example : https://imgur.com/1fZ39tt

**Comment by MaxHayman** [comment]
Fixed these examples, leaving this open for any more.

**Comment by Sivine** [comment]
Another example : https://imgur.com/Xx5SYPv

**Comment by Lheana** [comment]
Changed all the spawns of the most popular entry for Doors as not attackable, so I close this ticket. If there are still doors that are attackable while it should not be, please comment here.
