### ISSUE TITLE
Furds Bottomless Mug - Bug?

### ISSUE THREAD

**Issue by Awoelkchen** [WarEmu/WarBugs#18526]
The mug dropped in Ekrund, from a git, on my runepriest. 

I have seen people report the Mug before, but couldnt find any solution to it, whatsoever.

So I am here to "repost" it. Cant use it, equip it or pull it anywhere on my character.

Any idea what thats about?

![unknown](https://user-images.githubusercontent.com/79367411/108598555-89d63800-738e-11eb-898c-1e782b7811da.png)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. The Mug has no function yet...so that's the reason for the weird code stuff.

**Comment by lilimx** [comment]
related to #15001
