### ISSUE TITLE
Magus - Chaotic Attunement Tactic stops working when entering scenario

### ISSUE THREAD

**Issue by xdieselx666** [WarEmu/WarBugs#18527]
**Expected behavior and actual behavior:**
Expected behavior is that after equipping the tactic, the demon summon becomes "instant cast" which works after you equip it.

If you enter a scenario, you will notice that the demon summon is now 2s cast time even if the chaotic attunement tactic is equipped.
If you right click on the chaotic attunement tactic to remove it and apply it again from your tactics abilities, the demon summon becomes instant cast again.
However, when you exit the scenario (after a loss or a victory), the chaotic attunement tactic doesnt work anymore and demon summon shows 2s cast time again. You have to un-equip the tactic each time and re-equip it. 

I was able to reproduce this issue in 5-6 scenarios in a row. I also followed the advice of a GM to try to reproduce it after restarting the game and the launcher and it kept happening every time.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. Your discription is good, but could you add some screenshots as well....if the issue still persists.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. I'll add your ticket to a related issue.

**Comment by lilimx** [comment]
related to #17538
