### ISSUE TITLE
wall collision missing in elf t2

### ISSUE THREAD

**Issue by NuzzleWuzzle** [WarEmu/WarBugs#18523]
**Expected behavior and actual behavior:**
Expected to walk at the wall and not go inside it. 
Actual behavior allows you to walk inside the wall and hide there.

**Steps to reproduce the problem:**
Go to the gate between Shadow Lands and Ellyrion
Walk over to wall shown in video
Walk into wall

**Testing Screenshots/Videos/Evidences (always needed):**
https://youtu.be/C0kL4QANWUs

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by Lheana** [comment]
Fixed with the patch of 26/03/2021.
