### ISSUE TITLE
Isolyr Swiftbow (merchant Elf Chapter 15) Bugged

### ISSUE THREAD

**Issue by Delegator2** [WarEmu/WarBugs#18529]
**Expected behavior and actual behavior:**

There is a craft supply merchant at High Elf Chapter 15, Isolyr Swiftbow, that is bugged in two ways. First, he won't bring up a window to sell/buy. Second, he sometimes simply disappears when you click on him.

**Steps to reproduce the problem:**

Try to use the merchant.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
Well he works perfectly for me, so I close the ticket. Comment with more details about how to reproduce it if the issue still occurs.
