### ISSUE TITLE
Ch22 in Caledor is broken. [Order]

### ISSUE THREAD

**Issue by Klod91** [WarEmu/WarBugs#18531]
We just tried doing Ch22 in Caledor, and the orbs are broken.
We used the first orb and ran to the next altar, but the orbs didn't spawn.
I had other people tell me they had the same issue.

**Comment by atlasshoved** [comment]
CH22 In Eatine on destro has a similar problem for the final boss,  Only the center fountian orb spawns.  It works and the cooldown works, but neither of the other orbs spawn.

**Comment by MaxHayman** [comment]
Should be fixed now
