### ISSUE TITLE
Empowered Alteration only restoring 24 AP over HOT duration

### ISSUE THREAD

**Issue by johnsmith534** [WarEmu/WarBugs#18537]
With the tactic, Leaping Alteration is supposed to restore 48 AP over its duration but currently it is only giving AP twice over the entire 9 seconds.

**Comment by albert461** [comment]
haven't been able to run my build on zealot since january because of this :(

**Comment by lilimx** [comment]
Hey, 

thank you for your ticket.
I will add it to a related issue.

**Comment by lilimx** [comment]
dublicate / related to #18353
