### ISSUE TITLE
Non Alternate Appearance Avaliable for maces on Maras

### ISSUE THREAD

**Issue by TheInfamousmara** [WarEmu/WarBugs#18536]
Hey, im having a problem i spoke to a gm about, maces on marauders don't have an alternate appearance, The lvl 16 Blue mace from influence  ALcadizaar's Crusher, nor most others, including any of the Sentinel weapons. none of them can be used as alternate appearance.  (Infamous)

**Comment by wargrimnir** [comment]
Most of these should have been fixed in a recent pass. Please update with screenshots of examples if they're still not working.
