### ISSUE TITLE
Phoenix gate scenario, flags not equal distance from bridge hand in, destro big advantage

### ISSUE THREAD

**Issue by Meliannia** [WarEmu/WarBugs#18530]
Others have noticed this as well, particularly during event scen weekend, Phoenix Gate,
Im unsure why this has never been fixed as it's a glaring error and give destro a huge bias in every single Phoenix gate scenario every single time flags are taken which happens 1 to 5 times almost every single scenario
Now you'd think the distance to the bridge from the flags would be equal for both teams as you get 50 points for dropping flag off,
but it isnt
it is not even remotely close
the time it takes for Order from when destro flag is picked up and get to the bridge is 30 seconds, about 476m distance
the time it takes destro from order flag pick up to get to bridge is 19 seconds, about 388m distance

thats 11 seconds difference
if order pick up flag first, before destro , destro get it to the bridge first for 50 points
if order get flag before destro and use Flee!, destro still get it back first for 50points
a white lion can get flag first use Charge! and also Flee! x2 speed boosts and still destro will run it back first.
This is nonsense and should not be allowed to happen.

now i recall destro spotting that Gromgrill Crossing scenario, Order got to centre first by 3 seconds, as Order base was 5m closer to bridge at start of game giving destro a 3 seconds disadvantage. Now the Gms  emergency fixed this to stop Order having 3 seconds advantage by moving the Order start base back a few metres
so im wondering why phoenix gate with destro 11 second advantage has never been fixed,

there are 3 ways to do this , option 3 is probably the best choice
1. move order flag further away from bridge by 88m (this would mean elongating the map)
2. move the bridge 44m away from order flag, and 44m closer to destro flag (this would mean re arranging middle of map, river, and land)
3. move destro flag 88m closer to the bridge (easy to do no other changes needed)

there is no way a lumbering black orc should be able to pick up the flag AFTER a white lion, the white lion to use x2 speed boosts and pounces and the black orc still beat the WL to the 50 point hand in.

i hope the devs/gms rectify this as they did gromgrill crossing when order had a 3 second advantage,

here's hoping.

**Comment by GamesBondd** [comment]
We're looking into several options to adjust the flag's placement. No ETA though.
