### ISSUE TITLE
AM mechanic-tactics bugs

### ISSUE THREAD

**Issue by Zholtar** [WarEmu/WarBugs#18535]
These bugs have been weighing on the Archemages game for months:

The mechanic buff applied to "Cleasing Light" only applies to other players, not AM.

The AoE heal hit from "Energy of Vaul" only applies if the defensive target is another player, not the Archemage (heals only AM itself).

The "Isha's Encouragement" tactic does not heal the entire party when applied in conjunction with "Aphoteosis".

**Comment by lilimx** [comment]
Hey,

please make sure you open separate tickets for individual issues.
