### ISSUE TITLE
All Out Assault! damage mitigation not affected by toughness debuff

### ISSUE THREAD

**Issue by Maarkie** [WarEmu/WarBugs#18546]
**Expected behavior and actual behavior:**
Toughness is supposed to mitigate all kinds of damage. However damage of All Out Assault! aura does not change when toughness debuff is applied. Same thing is about On Your Guard! aura and Shield of the Sun ability.

**Steps to reproduce the problem:**
Tested damage of All Out Assault! aura on Training Construct with and without toughness aura on. Damage of aura was the same. Also checked if toughness debuff affects damage of other abilities and it does.

**Testing Screenshots/Videos/Evidences (always needed):**

![Hitmebabe_005](https://user-images.githubusercontent.com/79662830/109203710-cb0e8380-77a4-11eb-9060-6ed498480a6f.jpg)
![Hitmebabe_006](https://user-images.githubusercontent.com/79662830/109203722-ccd84700-77a4-11eb-9747-efae147af6b1.jpg)
Reflect damage (upper without toughness debuff, latter with debuff):
![1](https://user-images.githubusercontent.com/79662830/109208503-ab7a5980-77aa-11eb-906f-0b591fdf5e21.PNG)

**Comment by cimator** [comment]
If an ability damage doesnt increase with any stat, like these auras or procs of WP/Dok etc, they also dont get affected by toughness

**Comment by lilimx** [comment]
Hey,

it's like Cimator said...so it's no bug.
