### ISSUE TITLE
White Lion Pet Ability "Bite" bugged damage and cooldown

### ISSUE THREAD

**Issue by emailkook** [WarEmu/WarBugs#18541]
**Expected behavior and actual behavior:**

Bite pet ability says 5s cooldown, but actually is 10s when you activate it.
Bite damage also says 516 delve, but test on a mob does 186 (100 mitigated) for 286 total

**Steps to reproduce the problem:**

Attack a dummy with the pet and when Bite goes off, starts counting down from 10 seconds. 
Look at the Bite damage and it is 50% lower than the delve.

The bug report for the cooldown has been around since 2016, so thought I'd make a new report.
https://github.com/WarEmu/WarBugs/issues/7876

**Testing Screenshots/Videos/Evidences (always needed):**

![bitebug](https://user-images.githubusercontent.com/50253609/109073922-a9d26800-76bc-11eb-982b-9b1b2c2a30c0.gif)
![bitedamage](https://user-images.githubusercontent.com/50253609/109073973-b787ed80-76bc-11eb-9326-d2e87885fec1.gif)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
But as you mentioned, there is already a ticket, so it's a dublicate.
