### ISSUE TITLE
GB and BS instances not working properly after /partyresetinstance command 

### ISSUE THREAD

**Issue by engharat** [WarEmu/WarBugs#18540]
Actual behaviour:
we(my group) had a lot of troubles resetting the instance. getting outside the dungeon and let everyone use /partyresetinstance did not reset the instance. We then managed to reset it by having one new player solo entering the dungeon, and then he invited us and we managed to enter a new instance. But then all the mid bosses along the path does not give credit/loot/influence because the whole party is flagged as locked out! While in reality no one had lockout. The last boss still works. This happens both on Gunbad and in Bastion Stairs as well.

**Comment by MaxHayman** [comment]
What was the out put of .lockouts ? Doing /partyresetinstance won't help if the leader is still locked to an instance as his instance will be resumed when you go in.
