### ISSUE TITLE
Wildfire BrightWizard Tactic

### ISSUE THREAD

**Issue by Balathan5** [WarEmu/WarBugs#18545]
**Expected behavior and actual behavior:**
Wildfire: When an enemy is hit by any path of conflagration ability there is a 25% chance for them to be dotted. However this does not proc on Flame Breath which is located in the path of conflagration tree in the ability training tab and on its own tool tip. I was also unable to proc it with Backdraft.

**Steps to reproduce the problem:**
Spam Flame Breath/Backdraft on Altdorf Dummies

**Testing Screenshots/Videos/Evidences (always needed):**

![Capture](https://user-images.githubusercontent.com/79648809/109167363-4e978880-7743-11eb-810b-2741e6d43015.PNG)
![Capture2](https://user-images.githubusercontent.com/79648809/109167807-c36ac280-7743-11eb-9756-f809e88f9006.PNG)

**Comment by barfyman92** [comment]
thing is it only proccs on direct damage

**Comment by lilimx** [comment]
Hey,

Patch Notes 16/11/2019
Bright Wizard

    Wildfire tactic has been fixed. It should now deal 3 ticks of damage and will apply on AOE or Direct damage, but not dot damage. Added a 3s cooldown for the proc.

dublicate: #17250

-closed
