### ISSUE TITLE
[QUEST] "Crushing stone"

### ISSUE THREAD

**Issue by Syzako** [WarEmu/WarBugs#18557]
**Expected behavior and actual behavior:**

Impossible to complete the task.

**Steps to reproduce the problem:**

![1](https://user-images.githubusercontent.com/39750677/109392339-9d296a80-796f-11eb-967a-883d18236b0e.png)
![2](https://user-images.githubusercontent.com/39750677/109392318-8aaf3100-796f-11eb-9af6-7ebf4700baac.png)
![3](https://user-images.githubusercontent.com/39750677/109392321-8be05e00-796f-11eb-834b-1e73478353f8.png)
![4](https://user-images.githubusercontent.com/39750677/109392325-8daa2180-796f-11eb-8998-90332feb9684.png)
![5](https://user-images.githubusercontent.com/39750677/109392327-8edb4e80-796f-11eb-9c2e-d2878fb3786b.png)

**Comment by Lheana** [comment]
"[...] and mount his head on a pike **at the top of the castle steps** [...]"
