### ISSUE TITLE
Pity Zone Flip

### ISSUE THREAD

**Issue by Nikademon** [WarEmu/WarBugs#18550]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Nikademon** [comment]
![Nicademix_009](https://user-images.githubusercontent.com/79680175/109254098-2c832200-77a6-11eb-8f79-d23010e2c0f6.jpg)


here is a photo of the amount that was not added

**Comment by dalen** [comment]
What is the bug?

**Comment by Nikademon** [comment]
On pity flip you get Zero influence for the zone locking

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
