### ISSUE TITLE
No cooldown timer animation for some abilities

### ISSUE THREAD

**Issue by abezverkhiy** [WarEmu/WarBugs#18551]
**Expected behavior and actual behavior:**
When activating Feinted Positioning, Shroud of Magnus and Seal of Destruction all 3 of them experience the same bug (other WH abilities are OK) - if you hit ability ONCE then it is working as intended. But if you spam it then cooldown timer disappears from the ability icon. See screenshot - I have buffs from Feinted Positioning but there is no cooldown on the ability icon.

**Steps to reproduce the problem:**
Just spam any of 3 abilities and watch behaviour of cooldown animation

**Testing Screenshots/Videos/Evidences (always needed):**

![Johanruth_000](https://user-images.githubusercontent.com/79711232/109322350-1e1a3080-78a2-11eb-96e2-c2a1e8f26991.jpg)

**Comment by abezverkhiy** [comment]
I circled ability buff and ability icon - the icon should display cooldown timer.

**Comment by MaxHayman** [comment]
Is this a new issue?

**Comment by abezverkhiy** [comment]
Hi Max. A similar issue was reported here and couldn't be resolved due to client limitations. Sorry for bothering

https://github.com/WarEmu/WarBugs/issues/14073
