### ISSUE TITLE
Guild -->Roster  problem

### ISSUE THREAD

**Issue by anthiquery** [WarEmu/WarBugs#18554]
**I cant see members online in roster and if i uncheck the box hide offline  i cant see members from the guild too . I have an addon "warboard " there is a little module too see number of alliance mates online and guild friends online i can see the number of guildmates online and who is it but not by the classic guild interface roster.*

**Steps to reproduce the problem:**
just press G  to make guild interface appear , i had try a repair from the launcher since /reloadui do nothing  it s the same .

**Testing Screenshots/Videos/Evidences (always needed):**
https://ibb.co/c6ZznDr
https://ibb.co/bNG8brg

**Comment by anthiquery** [comment]
![guiild_roster_2](https://user-images.githubusercontent.com/44681599/109387207-4d5f8a80-7900-11eb-8d35-08f387de83b7.png)
![Uploading guild_roster_1.png…]()

**Comment by anthiquery** [comment]
![guild_roster_1](https://user-images.githubusercontent.com/44681599/109387229-6ff1a380-7900-11eb-9f57-215673077a95.png)

**Comment by anthiquery** [comment]
So i cannot  manage the roster as well due to this trouble  like i couldnt (promote demote  and so ...))

**Comment by anthiquery** [comment]
ah by graphical way i probably can by command lines

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. please try /rel.
I will close and add this ticket to a related issue.

**Comment by lilimx** [comment]
related to #18780
