### ISSUE TITLE
The purple seed ((

### ISSUE THREAD

**Issue by Uvolen1** [WarEmu/WarBugs#18559]
Sorry for bad english, I am writing via google translator. 02/27/2021 guild group held bb / be. 21-00 / 22-00 Moscow time. My character's name is Uvolen. An endless seed dropped in the BB dungeon (Azurethread Seed). I was very happy and immediately began to grow a seed and stocks of blue seeds, too, why save them now if my endless seed has grown, I thought. After completing two dungeons, we gathered for a scenario for a guild coin. In the Dungeon, the task "to capture a zone in a group" was counted. 
I suddenly noticed that through the add-on "MGR" seeds stopped collecting. I clicked into the "agriculture" itself and did not work there either. 
/ rel did not help and I completely restarted the game, unfortunately the seed disappeared (((... I was very disappointed. we won the "graveyard" and I left the game upset. In less than half an hour I was able to use the seed ((((

**Comment by Uvolen1** [comment]
> Sorry for bad english, I am writing via google translator. 02/27/2021 guild group held bb / be. 21-00 / 22-00 Moscow time. My character's name is Uvolen. An endless seed dropped in the BB dungeon (Azurethread Seed). I was very happy and immediately began to grow a seed and stocks of blue seeds, too, why save them now if my endless seed has grown, I thought. After completing two dungeons, we gathered for a scenario for a guild coin. In the Dungeon, the task "to capture a zone in a group" was counted.
> I suddenly noticed that through the add-on "MGR" seeds stopped collecting. I clicked into the "agriculture" itself and did not work there either.
> / rel did not help and I completely restarted the game, unfortunately the seed disappeared (((... I was very disappointed. we won the "graveyard" and I left the game upset. In less than half an hour I was able to use the seed ((((

**Comment by Uvolen1** [comment]
> Sorry for bad english, I am writing via google translator. 02/27/2021 guild group held bb / be. 21-00 / 22-00 Moscow time. My character's name is Uvolen. An endless seed dropped in the BB dungeon (Azurethread Seed). I was very happy and immediately began to grow a seed and stocks of blue seeds, too, why save them now if my endless seed has grown, I thought. After completing two dungeons, we gathered for a scenario for a guild coin. In the Dungeon, the task "to capture a zone in a group" was counted.
> I suddenly noticed that through the add-on "MGR" seeds stopped collecting. I clicked into the "agriculture" itself and did not work there either.
> / rel did not help and I completely restarted the game, unfortunately the seed disappeared (((... I was very disappointed. we won the "graveyard" and I left the game upset. In less than half an hour I was able to use the seed ((((

**Comment by lilimx** [comment]
Hey,

Thank you for your ticket.
sorry for your loss, but unfortunately we don't replace items if these disappear.
