### ISSUE TITLE
Phoenix gate flag take even after death

### ISSUE THREAD

**Issue by Andaryan** [WarEmu/WarBugs#18558]
I just played Phoenix Gate scenario in which I tried to take the flag, while I got very close to taking the flag I was eventually killed. Just as I died though, I got the message that my character had taken the destruction flag and the flag disappeared, as if taken. After respawning I noticed that on my minimap I had the objective symbol on my character despite having just respawned. I went to the flag capture point just for laughs, only to realise that the objective had actually stayed on me through death and respawn and caused my side to win the scenario.

To reiterate; Got very close to taking the flag a couple times, got swarmed and killed. Upon death, got the message that flag was taken by my character, held flag through death/respawn and managed to capture the flag.

I never record my gameplay and thus dont have any proof other than a screenshot taken after the scenario. But as bugs go, it is a gamebreaking one as it completely changed the outcome of the scenario.
![bugss](https://user-images.githubusercontent.com/79766529/109398714-18c2f180-7947-11eb-9065-79e02b356dd6.png)

**Comment by Lheana** [comment]
This should have been fixed.
