### ISSUE TITLE
[Visual] Cloak appearance

### ISSUE THREAD

**Issue by Syzako** [WarEmu/WarBugs#18556]
**Expected behavior and actual behavior:**

What I see:

![WAR-64 2021-02-28 01-57-02](https://user-images.githubusercontent.com/39750677/109391598-fee7d580-796b-11eb-9904-e8878f553518.png)

What see others:

![WAR-64 2021-02-28 01-57-15](https://user-images.githubusercontent.com/39750677/109391614-1921b380-796c-11eb-90ab-a9f2e86af7f8.png)

**Steps to reproduce the problem:**

Career: 
Sorcerer

Item equip:
"Sovereign Charmcloak of the Voidlord"

Aalternate appearance applied:
"Raider's Wrap"

**Comment by MaxHayman** [comment]
Who is "others"? Enemies? Allies?

**Comment by Syzako** [comment]
> Who is "others"? Enemies? Allies?

Allies

**Comment by Syzako** [comment]
> Who is "others"? Enemies? Allies?

And Enemies

From me:
![1](https://user-images.githubusercontent.com/39750677/109630631-443d1a80-7b99-11eb-8101-d852e51cbfb2.png)

From enemy (Appearance enabled):
![2](https://user-images.githubusercontent.com/39750677/109630813-73538c00-7b99-11eb-9d15-ad1c900feec2.png)

From enemy (Appearance disabled):
![3](https://user-images.githubusercontent.com/39750677/109630850-7e0e2100-7b99-11eb-9cbe-33eb8d0ddaea.png)

**Comment by Yasmyr** [comment]
I can confirm that no cloak appearance at all works, regardless of career or cloak used. Guild Heraldry on cloaks works now though.

**Comment by Tazo83** [comment]
i can confirm this as i came here to report the same thing for my slayer using the [Beastlord Mantle of the Stag] while having all these on  [Isha's Lament]    [Cloak of Bugman's Resolve]    [Arachnophile's Embrace]  on my appearance  but all my friend on discord told me they can only see the [Beastlord Mantle of the Stag]  without any appearance appearing to them its only showing on my screen

**Comment by BomblingTV** [comment]
Came here to report the same.
Had Mantle of the fireborn cloak selected to be shown, but on a stream with a realm-ally i noticed it was showning my sovereign cloack that i had equipped but not selected as my apperience. The streamer confirmed with me that he did have the option to see other player's apperanced turn on and not off.

So Cloacks does indeed seem to not be showing their correct apperances atm.
Not related to realm, and not related to appereance showing on/off option.

**Comment by BomblingTV** [comment]
This is still bugged:
https://imgur.com/a/fPAYd5F

And no the settings of "show Enemy apperance" is not the issue on user error.

**Comment by LorneTorne** [comment]
Came here to post this bug.
Choppa sovereign cloak cannot have the appearance altered either. Tried all sorts of things. No matter what I do allies always see the sov cloak apperance.
Would very much like to be able to customize my cloak in my BiS gear.

**Comment by lilimx** [comment]
Fixed with patch 18/09/2021
