### ISSUE TITLE
Feets in da Snow - Scout Icehearth Crossing not working

### ISSUE THREAD

**Issue by Rayyl812** [WarEmu/WarBugs#18567]
**Expected behavior and actual behavior:**
When getting inside the range of Icehearth Crossing, the "scout" task should autocomplete.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

thank you for your report. I will add this ticket to a related issue.

**Comment by lilimx** [comment]
dublicate #18591
