### ISSUE TITLE
T3 - Keep lords are invincible and bugged.

### ISSUE THREAD

**Issue by Gobtar** [WarEmu/WarBugs#1856]
The Tier 3 keep lords will not take damage, they may be attacked, and it registers that they are receiving damage, and sometimes will register going to 96%, however they will not take further damage or they will heal up. Related, the keep lord rarely attacks surrounding players. This makes it impossible to take keeps in tier 3.

**Comment by ozarmidrashim** [comment]
Door ordering issue. Outer is Sanctum and Sanctum is Outer. When last door goes down, keep is in Outer Door Under Attack state, and keep lord is programmed to be invulnerable to prevent login abuse.
