### ISSUE TITLE
[Keep] Oil blocks physic range attacks

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#18561]
![Gangan_018](https://user-images.githubusercontent.com/40274248/109418684-105fca80-79ca-11eb-806f-17acfb46e39b.jpg)

physical range attacks are blocked by oil in keeps, making it difficult to kill the oil, if no or only a few caster are around.

I tried different keeps and skills, always with the same result.

**Comment by lilimx** [comment]
hey,

that's intended.
#6783
#7775
