### ISSUE TITLE
Missing seed after forced relog

### ISSUE THREAD

**Issue by skattefar89** [WarEmu/WarBugs#18568]
I just had a bug inside gunbad mid wing. while i was cultivating with 2 purple seeds and 2 green i got kiled by mobs then i get resed but i was "disablet" i couldet do anyting so i relog and when i got back in one of the purple seeds from my inventory was gone and i dont know why. Is there any way that i can get that seed back some how?
It was the Eternal Black Hellevore seed

**Comment by thorbolt80** [comment]
Same eternal golden serrisa purple seed with thorbolt. I ask same but it's impossible

**Comment by Syzako** [comment]
I am lost some usual seed when use button "GO" in window "War Report" during growing new seed.

**Comment by edweray** [comment]
i lost 3 eternal seeds because of dc's and relogs, and every time my miracle grow was still working.Fix it if possible
