### ISSUE TITLE
A Sticky Situation Nordland Imperium quest chapter 3

### ISSUE THREAD

**Issue by Firetotem133** [WarEmu/WarBugs#18560]
You can't finish the quest (a sticky situation) because Gavin Scherer doesn't follow you out of the cave. The quest can be found in Nordland 3rd Empire Chapter. 

I hope the information is sufficient.

best regards
Firetotem

**Comment by Lheana** [comment]
Need more details, and screenshots.

**Comment by Firetotem133** [comment]
Sorry this is my first report about buggs. Unfortunately, I don't have a screenshot because I didn't think this was necessary. Next time I'll be sure to take a screenshot.

**Comment by Lheana** [comment]
You just have to wait for Gavin Scherer to despawn and click on the cocoon again.
