### ISSUE TITLE
Scenario pop in a scenario

### ISSUE THREAD

**Issue by gke96** [WarEmu/WarBugs#18577]
Scenario popped while I was already in one. Of course I didnt queue again after joining highpass cemetary.

![scbug](https://user-images.githubusercontent.com/11146551/109854826-8f722e80-7c68-11eb-86e6-25044daf4b16.png)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. I will add this ticket to a related issue.

**Comment by lilimx** [comment]
dublicate / related to  #15711
