### ISSUE TITLE
Repeateable DYE quest Goblins in T4 - keep dying as of today

### ISSUE THREAD

**Issue by Demoriel** [WarEmu/WarBugs#18572]
Repeatable DYE quests Goblins for the T4 PVE (the Gobbos who walk entire pairing roads) quest never used to aggro surrounding mobs and take damage till today. When they die, which is fast, the quest cannot be turned in and they respawn on a total different map, so you never know where they are.

I'm not sure about Order NPCS as i dont play Order much

**Comment by Lheana** [comment]
This should have been fixed few patches ago. Comment if it still occurs.
