### ISSUE TITLE
Bastion Stair bosses vanishing upon defeat

### ISSUE THREAD

**Issue by atlasshoved** [WarEmu/WarBugs#18575]
**Expected behavior and actual behavior:**
When downed the boss body gave an error message
![bastion bug](https://user-images.githubusercontent.com/78624394/109707136-a886bc80-7b4e-11eb-8672-ebaa6a4878fd.png)

 and did not spawn
 
 The whole center wing was cleared without issue, so we continued in the left wing until the same happened
 
 ![bastion bug2](https://user-images.githubusercontent.com/78624394/109706284-99ebd580-7b4d-11eb-9941-1c1a2f79c8d8.png)

According to .lockouts nobody was locked out to either of these, although we did shuffle some of the characters present in the instance to avoid exactly that.  We did not continue further.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by MaxHayman** [comment]
Will be fixed in next patch
