### ISSUE TITLE
[Quest][Dark Elf Chap 19] Wyrmbreaker: NPC unreachable / spawns in lava

### ISSUE THREAD

**Issue by gamerlenny** [WarEmu/WarBugs#18570]
In one part of the quest chain "Wyrmbreaker" that takes place at Dark Elf Chapter 19, you have to kill an NPC named Fandalas Stormlock near Caladain's Furnace PQ in Dragonwake. Problem is, that NPC exists but is unreachable / unattackable because he spawns in the middle of the lava around 35000, 58500 (along with a couple other mobs) and is too far from the land or bridges to be attacked from a distance.

**Expected behavior and actual behavior:**
All NPCs around Caladain's Furnace PQ should walk on the ground, paths and bridges, and not be able to walk on lava, let alone swim in it (obviously!). Since Fandalas Stormlock must be killed for a quest, he should be easy to reach. Given the quest description, he is actually supposed to appear right behind you after you click one of the chests in the PQ.

**Testing Screenshots/Videos/Evidences (always needed):**
![Gaernith_012](https://user-images.githubusercontent.com/2891053/109553880-d7138180-7ad3-11eb-9335-ffac2fc3bb3a.jpg)

In the following screenshot I target Fandalas Stormlock, but he is too far away to be attacked with my only ranged attack (Throwing dagger) and barely visible in the lava...
![Gaernith_011](https://user-images.githubusercontent.com/2891053/109554062-0e822e00-7ad4-11eb-883f-7ebcb0fd22db.jpg)

**Comment by gamerlenny** [comment]
Update: after going back to Caladain's Furnace the next day, I found Fandalas Stormlock in two other places: once in a different spot, still in the lava and too far from the ground to be attacked, and later on, after he was somehow killed by a ranged DPS player, he finally repoped at a more normal location (in the area indicated by the quest marker on the map, which I assume is where he should be). So I'm not sure what happened before and how he ended up standing in the lava, but it seems that he either randomly respawns in the wrong location, or he aggros someone and runs to the lava and stays there instead of going back to his spot. 
In any case there's something wrong with his behavior, he should not be able to wander off to a place where he can't be reached.

**Comment by Lheana** [comment]
Related to #16938
