### ISSUE TITLE
More bugs in gunbad

### ISSUE THREAD

**Issue by skattefar89** [WarEmu/WarBugs#18580]
You can still respawn inside the boss champers in all 3 wings
The last boss on the mid wing have a bug with the black cloud, it no longer do any dmg even if you stand inside it
The last boss on the left wing does not make the green puddels anymore
The goblin boss on the left wing 2 hits full invader tank

**Comment by Lheana** [comment]
The first issue reported has been fixed, for the others, verify it has not been reported yet, and **open one ticket per issue**.
