### ISSUE TITLE
Unholy quest/Order Praag

### ISSUE THREAD

**Issue by odoc7625** [WarEmu/WarBugs#18585]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by odoc7625** [comment]
![Dainia_005 (2)](https://user-images.githubusercontent.com/66634766/110065944-387e5f00-7d25-11eb-9c6a-7097c444248f.jpg)
![Dainia_004 (2)](https://user-images.githubusercontent.com/66634766/110065949-3c11e600-7d25-11eb-9907-7e7f12accd3f.jpg)
![Dainia_002](https://user-images.githubusercontent.com/66634766/110065957-3e744000-7d25-11eb-9edb-7df55dedc0ec.jpg)

**Comment by odoc7625** [comment]
idk what im doing,tryn to help

**Comment by Lheana** [comment]
Have you tried attacking the rifts?

**Comment by odoc7625** [comment]
Pink arrows are skulls i need to kill,but they have no hp.Green arrow skulls on ground with no hp,thing they are broken,shouldnt be there.The red arrow rift has hp,when i kill it nothing happens.I didnt try redo part of quest step, abandon and repickup

**Comment by Lheana** [comment]
And have you tried clicking on it?

**Comment by Lheana** [comment]
No answer, I close the ticket.

**Comment by DurinThornaxe** [comment]
I did all the things said in the thread before plus clicking on the Rift and it doesn't do anything. Can't destroy it anyway unfortunately.

**Comment by lilimx** [comment]
Hey,

the ticket is already closed. Please open a new one with your evidecnes.
It would be nice if you can add a note to this closed ticket here with #1858
