### ISSUE TITLE
DoK tactic : Empowered Transfer non existent

### ISSUE THREAD

**Issue by adeie** [WarEmu/WarBugs#1858]
Tried slotting the tactic Empowered Transfer, each time getting the same error message: 

Nonexistent tactic: 9600 Empowered Transfer
![screenshot_23](https://cloud.githubusercontent.com/assets/15959651/11320032/3db29c26-9085-11e5-8b08-d766b4cc2f93.jpg)

**Comment by ozarmidrashim** [comment]
Also fixed for WP
