### ISSUE TITLE
issues setting guild heraldry

### ISSUE THREAD

**Issue by frankystein65** [WarEmu/WarBugs#18587]

**Comment by frankystein65** [comment]
it looks as if my comments and screen shot are no longer listed.  set guild heraldry at level 10 expecting to be able to see shape and color.  generic shape and color are what we get.  
![pms](https://user-images.githubusercontent.com/30161158/111609449-aceae080-87b0-11eb-8307-9181b89d69ea.JPG)

**Comment by frankystein65** [comment]
as of 02/18/2021
![Femlyn_004](https://user-images.githubusercontent.com/30161158/111617581-ae6cd680-87b9-11eb-999e-95685855ddaa.jpg)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. I will add this report to a related issue.

**Comment by lilimx** [comment]
related to #9791
