### ISSUE TITLE
Respawn PVE from lord room PVP Karza Dammaz Keep

### ISSUE THREAD

**Issue by Bignusty** [WarEmu/WarBugs#18581]
Wrong respawn we died on lord room at karaz dammaz keep and respawned on pve warcamp instead of pvp warcamp

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
With which character did happen this? I need a bit more information.

**Comment by lilimx** [comment]
Hey,

im going to close this ticket now due to no feedback.
