### ISSUE TITLE
unable to stow guild banner, relogging losses banner

### ISSUE THREAD

**Issue by frankystein65** [WarEmu/WarBugs#18588]
clicking banner, as done to use banner, should stow banner away.

when done using banner, clicked banner in abilities hot bar.  character appears to start stowing.  banner does not stow away. character 1. Owicked  2. Femlyn
![Owicked_000](https://user-images.githubusercontent.com/30161158/110167147-57333300-7dc3-11eb-980a-fd0ddb83accf.jpg)
![Femlyn_003](https://user-images.githubusercontent.com/30161158/110167150-5a2e2380-7dc3-11eb-9ecc-699e4e07a496.jpg)

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by dalen** [comment]
Fixed in the 2021-03-18 patch
