### ISSUE TITLE
game crashed in BS now i cant log back in

### ISSUE THREAD

**Issue by bloodtyrant** [WarEmu/WarBugs#18592]
cant log back in after dungon crashed in BS it keeps trying to enter the fray then times out I did the file repair and its the same

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by MaxHayman** [comment]
What is your username?

**Comment by bloodtyrant** [comment]
It fixed its self and my char name is bloodtyrant
