### ISSUE TITLE
Pulverizer of Karl franz 

### ISSUE THREAD

**Issue by Zhentarim** [WarEmu/WarBugs#18593]
Its a reward for the epic quest "On the brink of Chaos" in Reikland chapter 15.
It allows Slayers to use a twohander with twohander dps in one hand as early as lvl 28.
![bugvapen](https://user-images.githubusercontent.com/16043550/110208154-bf4b4d00-7e87-11eb-91ea-d9bf59d0256d.png)
https://imgur.com/a/H00VLy5
Should be fixed asap

**Comment by wargrimnir** [comment]
This was fixed in a recent item pass, but I did go ahead and update the model to use a proper hammer.
