### ISSUE TITLE
Cannot use the Trainers

### ISSUE THREAD

**Issue by Razooly700** [WarEmu/WarBugs#18594]
None of my characcters can use the Trainers. For example I can right click the Renown trainer but when I select the "Buy Renown Abilities" button on the dialog window nothing happens. I can select this button as many times as I want and nothing happens. When I select "Goodbye" the dialog window closes. 

- I have tryed repair from the launcher.
- I have reset my interface.
- I have no addons
- I have not found any info on this issue
- I  have not played Return of Recoking for several years and started playing again last week. My old characters were still avialable.

**_Installed game on my laptop and was able to access the Trainers. Issue is probably the old game install since the new install works fine. If anyone else has this issue and has an old install try a reinstall (repair did not work for this)._**

**Comment by Lheana** [comment]
Apparently it was related to the installation, so I close the ticket.
