### ISSUE TITLE
Objects for ToK unlocks on cooldown

### ISSUE THREAD

**Issue by valkeera** [WarEmu/WarBugs#18596]
Since 2-3 patches back, the objects that you need to click to get a ToK unlock (either History&Lore, Bestiary or Achievement) appear to be now on 1 minute cooldown - which means that other people cannot click on it to get the same unlock for that amount of time, until the cooldown passes and the object "resets". This applies to all unlocks that are not of kill/talk to type or proximity unlocks; easter egg quests are affected as well.

Reason why I'm submitting this is that our guild is running tour-events for discovering these unlocks, and it is quite time-consuming if you have a party of 6 and need to wait more than 5 minutes for everyone to get one unlock.

If you need specific examples of objects which are affected by this, please let me know, but it appears to be every one of them.

**Comment by lilimx** [comment]
Hey,

want to add, the issue still persists. it's 1min CD.

**Comment by lilimx** [comment]
Hey,

sorry for the late delay, but this is inteded. Because some Game Objects can be set to 0 or only few seconds for the CD, but some others need a CD (due to animation resets and so on).
