### ISSUE TITLE
Portal between High Pass and Ostland

### ISSUE THREAD

**Issue by JaqiC** [WarEmu/WarBugs#18595]
I was taking the road from High Pass to Ostland and the portal on the road does not appear to be working.  I logged out and back in twice but it is still broken.

**Comment by lilimx** [comment]
When you try to enter Ostland from High Pass it says
"Region currently not available. Please try again later."

![Toffi_002](https://user-images.githubusercontent.com/23266079/119825537-56f49080-bef7-11eb-851a-39310385c56e.jpg)
