### ISSUE TITLE
Greenskin Chapter 10 

### ISSUE THREAD

**Issue by DaHiff** [WarEmu/WarBugs#18599]
Not able to select the 1st reward from the chapter had the same issue with chapter 8 and maybe 9 too not 100% on 9 tho 
![Hiff_000](https://user-images.githubusercontent.com/80197936/110236506-160b6200-7f2e-11eb-87d8-bfb2adebc66a.jpg)

**Comment by DaHiff** [comment]
chapter 13 and 14 too seems alot of the greeenskins need a look at

**Comment by Lheana** [comment]
Duplicate of #7687
Also one issue per report please.
