### ISSUE TITLE
Twisting Tower Scenario is bugged.

### ISSUE THREAD

**Issue by Korize1** [WarEmu/WarBugs#18604]
The portals in the scenario map Twisting towers are not working, both teams are stuck in their starting zones.

**Expected behavior and actual behavior:** Well the expected stuff is that the portals should work I guess.

**Steps to reproduce the problem:** Just rejoin the SC and its bugged.

**Testing Screenshots/Videos/Evidences (always needed):**
https://i.gyazo.com/596bab8b9a06f17e61730515572f20c1.jpg

**Comment by FrostKota** [comment]
https://user-images.githubusercontent.com/74566183/110349162-6e129900-8000-11eb-84ce-7a3b053d142d.mp4

to add a small clip showing that the portals aren't working and that there is no other way across as jumping off doesn't get you that close to it in the first place but just teleports you back to spawn

**Comment by geezereur** [comment]
After patch the Twisting Scenarios explosions dont stop after activated.

**Comment by Lheana** [comment]
This should be fixed.
