### ISSUE TITLE
Oath Rune of Sanctuary 

### ISSUE THREAD

**Issue by Gizbyt** [WarEmu/WarBugs#18606]
**Expected behavior and actual behavior:**
Oath rune of Sanctuary should disappear when you die, whether you use it or not. It resets to 10 minutes if you just click respawn, without clicking the yes or no button.

**Steps to reproduce the problem:**
When you have it on you, just respawn with the yes/no window still up and it will reset to 10 minutes on the buff every time.

**Testing Screenshots/Videos/Evidences (always needed):**

![Ymmeln_000](https://user-images.githubusercontent.com/80352239/110514366-23c41180-80ff-11eb-805a-457478fa6721.jpg)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. I will add this issue to a related report.

**Comment by lilimx** [comment]
dublicate / related to #18606
