### ISSUE TITLE
While in party, when exiting the guild hall in Altdorf, party members fall from the front door to their death.

### ISSUE THREAD

**Issue by FeralGirl** [WarEmu/WarBugs#18609]
**Expected behavior:** All players in a party should be able to click on the exit/entrance door to leave the Altdorf guild hall and appear in the city of Altdorf.
**Actual behavior:** While in a party, the first person to exit the Altdorf guild hall will teleport out as intended. This triggers an animation of the door opening for the other party members, who then walk out of the hall and fall to their death instead of teleporting back to Altdorf outside of the hall.

**Steps to reproduce the problem:** Form a party in Altdorf. Enter the guild hall and maybe speak to an NPC or two. Then attempt to exit the guild hall, one person clicking on the exit door and the other party members walking through the door behind the leader.

**Testing Screenshots/Videos/Evidences (always needed):** 36 sec clip uploaded to YouTube by bf, proving the issue to him after i fell to my death behind him the first time.
https://www.youtube.com/watch?v=Fua3vOsywfQ

**Comment by dalen** [comment]
Fixed in the 2021-03-18 patch
