### ISSUE TITLE
[Knight] Alt-Sov Chest icon showing as boots

### ISSUE THREAD

**Issue by DefVont** [WarEmu/WarBugs#18608]
![alt sov knight chest](https://user-images.githubusercontent.com/64330047/110591087-bda5c000-81cc-11eb-92fe-7249c474f8ab.png)

Body piece on the Knight's alt-Sov is showing as legs icon. Somewhat confusing at times.

**Comment by lilimx** [comment]
Hey,

![grafik](https://user-images.githubusercontent.com/23266079/123550242-f910ce00-d76c-11eb-8777-f185a82da4df.png)
these are both knight sov chest icon.

Guess it was fixed.
