### ISSUE TITLE
Sentinel jewel that gives 6% reduced armor penetration is not showing stat in character screen

### ISSUE THREAD

**Issue by madregit** [WarEmu/WarBugs#18601]
Sentinel jewel 6% reduced armor penetration not showing in character screen, so idk if its working or not.
Sov same stat shows in character screen.
![1](https://user-images.githubusercontent.com/80213167/110247090-2846c980-7f49-11eb-87fd-c2dd956d3c96.png)
![2](https://user-images.githubusercontent.com/80213167/110247091-2a108d00-7f49-11eb-8757-dcf9961fcf53.png)
![3](https://user-images.githubusercontent.com/80213167/110247095-2da41400-7f49-11eb-828d-3b2a855dca6b.png)
![4](https://user-images.githubusercontent.com/80213167/110247110-444a6b00-7f49-11eb-883f-845ad2b72318.png)

**Comment by bloodmasked** [comment]
Reduced armor pen does not show in the character statdoll. It does show in .getstats however. This is because of how armor pen is calculated.

**Comment by madregit** [comment]
thanks for explaining
