### ISSUE TITLE
Hard PQ in Barak Var Named: Bar Dawazbak dosn't work.

### ISSUE THREAD

**Issue by EvilBehavior** [WarEmu/WarBugs#18619]
Here u can see the PQ dosn't Work. No Orc's, Katapult's, or Timer.

![Baramosh_021](https://user-images.githubusercontent.com/80459616/110781548-563c4e80-8266-11eb-8c75-17df46f9d1f2.jpg)

![Baramosh_022](https://user-images.githubusercontent.com/80459616/110781842-aca98d00-8266-11eb-9395-d11649e26eaa.jpg)

**Comment by Richky** [comment]
This happens on a number of PQs. No Hammerstriker dwarfs in Marshes of Madness, no Moonfang Stickpointas in Badlands

**Comment by Lheana** [comment]
Works fine for Bar Dawazbak.
![Lheana_233](https://user-images.githubusercontent.com/11537611/111873291-df066900-898f-11eb-9b9e-36dbab1c9cc5.jpg)
