### ISSUE TITLE
Against All Odds PQ seems broken

### ISSUE THREAD

**Issue by Delegator2** [WarEmu/WarBugs#18616]
Tried to work the Against All Odds quest in Saphery (Easy 28-29) both yesterday and tonight, and both times it has been not just spawned, but the quest itself doesn't show up in the UI (e.g. nothing about what stage it is in). Is this PQ completely broken?

**Comment by Delegator2** [comment]
Poisonwing Canyon also seems broken. A pair of us did it, and in stage 1 the PQ kill count advanced but we got no influence, then in stage 2 the MOBs didn't spawn.

**Comment by dalen** [comment]
Fixed in the 2021-03-18 patch
