### ISSUE TITLE
Skills get swapped in hotbar 

### ISSUE THREAD

**Issue by Skibbas** [WarEmu/WarBugs#18613]
When joining/exiting sc's, some skills gets swapped/replaced in the hotbar.
Tried it a few times and it is always the same skills on my wp, although I have not tried it on other classes.

Made a clip showing exactly what happens: https://youtu.be/vQgvVt_68RE

Edit: seems to only be for some classes. The game overwrites your skillbar with the skills you started the game with I think.

**Comment by Firetotem133** [comment]
Yes, I've noticed that a few times now. 
Conclusion have the same problem. 
My skills change when I go to the SC or when I leave again.
