### ISSUE TITLE
Skill Bar bug

### ISSUE THREAD

**Issue by obius89** [WarEmu/WarBugs#18618]
Picture 1
![image](https://user-images.githubusercontent.com/31844986/110779786-df01bd00-825b-11eb-9c2b-2f9886782461.png)

Hi devs, I Have just discovered a bug. where whenever I travel or I join scenarios the skills on the one and two buttons of my skill bar will revert back to the clobber and the lob Choppa skill.   My actual skill bar setup can be seen in picture 1, but when I traveled to ic, my skills bar had reverted to what is seen in picture 2.   My username on the game is tobius89 and my char name is Basamu pm me if you need more info

Picture 2
![image](https://user-images.githubusercontent.com/31844986/110780412-926ab180-825c-11eb-8608-5d808d271bcb.png)

**Comment by Skibbas** [comment]
This bug is already reported, lets hope we get a fix soon :)

**Comment by dalen** [comment]
Fixed in the 2021-03-18 patch
