### ISSUE TITLE
RVR-related Items keep disappearing

### ISSUE THREAD

**Issue by szputnyik89** [WarEmu/WarBugs#1861]
My character "Szputnyik" has following issue: In scenarios and ORVR I get emblems and medaillons, but they keep disappearing after zoning or logout. This doesnt only include any Scout Emblems and Medaillons, but also RVR-Equip I bought and dont immediately equip.

This leads to the problem, that I cant farm any scenario weapons. The RVR-equip I buy with gold isnt really an issue because I now only buy what I can wear. But I already spent 30 emblems for a Sentry-lvl Weapon and lost the weapon with the relog. Emblems were also gone.

So I guess, I am missing at least 60-70 emblems right now. It would be really great if You could fix this. It is at this point impossible for me to get scenario weapons or set-armor.

Thank You very much

Account: Szputnyik Character: Szputnyik

**Comment by Evildoor** [comment]
This issue is already reported.
#1808 
#1846
