### ISSUE TITLE
Twisted Tower

### ISSUE THREAD

**Issue by Volaous** [WarEmu/WarBugs#18611]
So unsure how to recreate this bug but the twisting tower map's explosion effect seems to repeat and never end. We just had a match where destro capped both points and the explosion happened and we had to stand in spawn for 3 minutes until someone made a surrender vote. I didn't get to capture the event sadly and i don't know what triggers the explosion but hope this helps someone in the future.

**Comment by Lheana** [comment]
This should be fixed with the hotfix of 12/03/2021.
