### ISSUE TITLE
Chairsit Emote Broke

### ISSUE THREAD

**Issue by FrostKota** [WarEmu/WarBugs#18625]
***Issue***
Using the emote "/chairsit" gets you stuck in the chairsit animation using actions like fighting or summoning a mount doesn't fix it. In addition to not being able to get out of the animation if you try and summon a mount it will not summon it and you'll still be on the floor

***Expected Behavior***
Using the chairsit emote should put you into the animation however taking any action should take you out of animation

**Steps to reproduce the problem:**
use the emote /chairsit

**Testing Screenshots/Videos/Evidences (always needed):**

https://user-images.githubusercontent.com/74566183/110890885-dc847f00-82be-11eb-88d5-a15df99cb679.mp4

https://user-images.githubusercontent.com/74566183/110890934-f2923f80-82be-11eb-8259-212af4968935.mp4

https://user-images.githubusercontent.com/74566183/110890971-02118880-82bf-11eb-8b33-bba156b6f38b.mp4

**Comment by FrostKota** [comment]
I will continue to test further if teleporting to places fixes it, if getting stunned, knocked down, or killed fixes it.

**Comment by FrostKota** [comment]
So update on the issue, teleporting with either War Report or book of binding or Scenario join will not fix it, relogging will fix it and sometimes if relog but use it again it's like a 50/50 on whether or not you can use your mount

**Comment by lilimx** [comment]
The /chairsit emote has been removed.
