### ISSUE TITLE
Event Scenario "The Ironclad" Destro Camp is not protected by champions.

### ISSUE THREAD

**Issue by Syzako** [WarEmu/WarBugs#18629]
The champions of "Choppa Pirat" stand still when the enemy is inside the destro war camp.

![1](https://user-images.githubusercontent.com/39750677/110954219-5a6a8800-839c-11eb-90ab-1343e43f4f7c.png)

**Comment by dalen** [comment]
this was fixed with hotfix on saturday. Before that they did ~6k auto attacks to anyone that got close, but not the 30k terminate ability
