### ISSUE TITLE
Squig Herder Sneaky Bouncin tactic not working

### ISSUE THREAD

**Issue by Tohrgrimm** [WarEmu/WarBugs#18628]
**Expected behavior and actual behavior:**

Expected: 15% increased damage when you are in a range of 45 feet of your target.
Actual: Nothing happens. There is no increase.

**Steps to reproduce the problem:**

Equip the tactic and test on the dummies with the skill Big Bouncin.
Unequip the tactic and do the same again. No Change in damage.

**Testing Screenshots/Videos/Evidences (always needed):**
Equipped tactic, look at the combat log

![Sneaky Bouncin 1](https://user-images.githubusercontent.com/61800361/110951195-11d3b000-8345-11eb-9f82-dd055a052e06.jpg)

Unequipped tactic, look at the combat log

![Sneaky Bouncin 2](https://user-images.githubusercontent.com/61800361/110951296-3465c900-8345-11eb-98d7-7b73511e5fb5.jpg)

**Comment by zulnam** [comment]
Can't seem to reproduce on target dummy. Damage increases accordingly.

Can find more details on my test here: https://www.returnofreckoning.com/forum/viewtopic.php?f=71&t=43958#p476448

**Comment by Tohrgrimm** [comment]
Tested it again. 
This time I started with 0 tactics:
Big Bouncin Tick 549

Then with the tactic Sneaky Bouncin:
BigBoucin Tick 549
Tested it 4 times with reenable tactic and switching the tactic presets (but just with the one tactic) and I got once ticks of 631.

Guys something is absolutely not working with this tactic.

Other test: Tactic All by Myself
Ticks of 686
Now in combination with Sneaky Bouncin:
Ticks of 686
Tested it with 5 times with switching the same two tactics around like before and the dmg never got higher than 686.

Conclusion: All by Myself and Sneaky Bouncin dont work together and Sneaky Bouncin alone worked one time in four tests.

**Comment by lilimx** [comment]
Hey,

Im a bit confused about your ticket. 
It's actually about the tactic "Sneaky Bouncin" and Big Bouncing.
Like Zulnam, I did some tests aswell and the dmg increase works as intended.

If you are the opinion that there are more issues with Sneaky Bouncin or another tactic, please write for each issue a separate ticket.
