### ISSUE TITLE
Gnoblar Huntin npc's missing

### ISSUE THREAD

**Issue by Murthor** [WarEmu/WarBugs#18627]
**Expected behavior and actual behavior:**  
There should be npc's for this quest, there are none.

**Steps to reproduce the problem:**
simpy go to the areas where they should be and see that they are missing

**Testing Screenshots/Videos/Evidences (always needed):**
![Murthor_000](https://user-images.githubusercontent.com/52479032/110942931-889e8800-8308-11eb-918e-4baaed80980c.jpg)

**Comment by Lheana** [comment]
As they belong to a Destruction PQ, apparently when you tried, no destro player came to this place since the last patch to trigger the PQ. But the PQ works fine, so I close the ticket.
