### ISSUE TITLE
Lifting Spirits Quest

### ISSUE THREAD

**Issue by ArdzofPT** [WarEmu/WarBugs#1862]
Seems the quest "Lifting Spirits" in the High Pass warcamp is not working.

**Comment by Meralors** [comment]
2nd part of this quest was actualy broken. It is now fixed and you can complete it normaly.

**Comment by Soulwhisper** [comment]
If someone could re-open this.Looks as completed on NPC but its actually not.

**Comment by Yellowpillow** [comment]
Quest can be completed. On 2nd stage NPC's icon glowing as if you done it already before it actually done. That is the only bug, but this issue have global scale, a lots of NPSs have this icon problem, with quests and influence rewards. 
![tranquillity_032](https://cloud.githubusercontent.com/assets/18102127/19017662/9be447a6-8853-11e6-8308-9eab746c5619.jpg)
