### ISSUE TITLE
Liniment of inspirational winds not giving healing power

### ISSUE THREAD

**Issue by reyaloran** [WarEmu/WarBugs#18621]
**Expected behavior and actual behavior:**
The liniment is intended to give 60 willpower and 50 healing power.
The liniment is only giving the 60 willpower.

**Steps to reproduce the problem:**
Use the liniment of inspirational winds and check your stats. Issue was found on a Zealot and tested on Dok and Shaman with the same results.  

**Testing Screenshots/Videos/Evidences (always needed):**
Before buff (res liniment used to push off the inspirational winds buff)

![image](https://user-images.githubusercontent.com/80372173/110800080-d6a08680-8249-11eb-9008-851c755c86cb.png)

After buff
![image](https://user-images.githubusercontent.com/80372173/110799798-8b867380-8249-11eb-87ce-819e108fcde9.png)

**Comment by Wraxin** [comment]
https://media.discordapp.net/attachments/730367357503012904/819610780038201344/unknown.png
He adds. Before 36 after 86, take a look at this screenshot.

**Comment by yuaa2** [comment]
146 is HPS, not healing power

**Comment by CrimsonFenris** [comment]
> 
> 
> 146 is HPS, not healing power

You are not looking at the healing power... HP is the little number on the right, so it adds (before 36, after 86).
Please close your thread after checking it's not a bug ;)

**Comment by lilimx** [comment]
it works as intended 👍
