### ISSUE TITLE
Weekend Scenario Reknown BONUS Buff  Aint working

### ISSUE THREAD

**Issue by ranzinus** [WarEmu/WarBugs#18638]
**Problem:**

The WeekendEventReknownBuff  should increase the received reknown points by 50%  (for wining and loseing a match) -  instead  of addinng points, the max Scenario Reknown reward has ben limited by 1.650 reknown output  as a MAXIMUM reward. 

Bug has been tested in 4 Matches with  different kills and fraction points. Results were repeatable the same.

 Screenshots attached

**Expected behavior and actual behavior:**

Reknown should be way higher and has different numbers, due to different kills and objectives.

**Steps to reproduce the problem:**

check reknown calculation and double check if reknown buff is realy active, at the moment it only appears to be visible active without any function. 

**Testing Screenshots/Videos/Evidences (always needed):**
![Ranzinus_761_reknown_bug](https://user-images.githubusercontent.com/73936724/111024057-e69c9f80-83dc-11eb-86ed-132add2199ea.jpg)

![Ranzinus_761_reknown_bug_3](https://user-images.githubusercontent.com/73936724/111024059-eac8bd00-83dc-11eb-851f-2fec9d254760.jpg)
![Ranzinus_761_reknown_bug_4](https://user-images.githubusercontent.com/73936724/111024060-ebf9ea00-83dc-11eb-80cc-9ede82d80bfe.jpg)

![Ranzinus_761_reknown_bug_2](https://user-images.githubusercontent.com/73936724/111024058-e8666300-83dc-11eb-9be5-8cb1cd7ccf9e.jpg)

**Comment by Symbelmyne** [comment]
I had same bug yesterday on destro side, but Wargrimmir said there was fix pending for this - apprently every tier sc was flag as t1 therefore the RP gain cap. I played last night destro again and it was fixed, I did 5k RP for won sc mid tier. Yet, today order side, mid tier scenario - same bug, max RP for won sc was 1.7k. Looks like said fix excluded order side.

**Comment by dalen** [comment]
This was fixed early Saturday. It was still flagged as tier 1 in one place and had the renown gain cap from that.
