### ISSUE TITLE
[Dungeons] Pop / depop entities issues

### ISSUE THREAD

**Issue by CrimsonFenris** [WarEmu/WarBugs#18630]
Multiple issues affecting now Gunbad, C&T and Bastion bosses, after last 2 patches invovling repopping bosses. Since they appears to be linked I'll regroup them here : 

**Gunbad :** 
- Lord Solithex : Ziggurats wont depop on dead (leaving entity with 0 HP), plus adds popping way too fast, leading to impossible to finish now (too much dmg from adds).
- Ard Ta Feet : Green bubbles wont depop on kill (leaving entity with 0 HP) ; visual bug only, it doesnt seem to affect the fight at all.
- Glomp da Squig Masta : Boss won't spawn his green puddles on ground, leading to be far more easy to kill.

**Crypts & Tunnels :** 
- Necromancer Malcidious : Spirits adds are popping too fast (like one every 10s instead of the usual 20-30s timer), and seems to hit more than usual, with 2+ spirits at a time, leading to boss impossible to do even with 3 good dps (spirits are hitting for 4k+ each, no need to explain what happens when 2+ are on same player).
- Master Quot'lik : Boss won't spawn his puddles on ground, leading to be far more easy to kill.

**Bastion Stairs :** 
- Tar'Ignan : Boss sometimes push 2 players at same time to feed his dogs (leading to inevitable death and inability to complete left wing).
- Kaarn the Vanquisher : Boss will not pop his red puddles on ground (easy to kill), and destroying the artifact on upper stairs doesnt like to have any effect and/or will not spawn at all.
- Lord Slaurith : Colored ground zones (blue/orange/purple) will not spawn, leading to much increased time to complete (since dmg output from players is reduced).

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
It would be really helpfull if you could split up your tickets into the different topics for Gunbad / Crypts & Tunnels / Bastion Stairs
