### ISSUE TITLE
White Lion armor debuff scales with Axeman mastery instead of Hunter

### ISSUE THREAD

**Issue by Edenwolf5** [WarEmu/WarBugs#18633]
Since the patch of 03/03/2021, WL armor debuff is not scaling in my Guardian/Hunter build and remains at lvl 25 values. This particular build has 9 points into hunter and 13 into Guardian. I tried to troubleshoot the problem and have since discovered why. 

Steps to reproduce:

As it turns out, the WL armor debuff is now governed under the path of the Axeman. First I start with resetting all mastery to 0, then put 9 points into the Hunter to pick up the armor debuff, at this point the debuff remains at level 25. I then put 3-5 mastery points into the Axeman which increases the armor debuff level to 28. Afterwords, I spec 13 mastery points into the Axeman which raises the armor debuff level to 38.

**Comment by TheOctagon322** [comment]
I can confirm
Armor debuff at hunter tree, scales with middle axeman tree.

**Comment by admaska2** [comment]
Yes its Bug if you put point in Axeman, the Armor debuff will scale with Axeman mastery

**Comment by admaska2** [comment]
https://github.com/WarEmu/WarBugs/issues/18496

**Comment by lilimx** [comment]
Hey,

It looks like the problem has now been fixed. If your the opinion it's still up, please open an new ticket.
