### ISSUE TITLE
Sergeant Westwood is clipping

### ISSUE THREAD

**Issue by lomeros** [WarEmu/WarBugs#18634]
Nothing game breaking. A bit of precise mouse work allows you to click anyway. But the poor sergeant has been touched by Tzeentch it seems...
![Ludwica_001](https://user-images.githubusercontent.com/80553746/111010060-af56d000-8395-11eb-9ae2-56544e653337.jpg)

**Comment by Lheana** [comment]
I could not reproduce because the original place of Sergeant Westwood is not there, he is meant to be on the other side of the windmill. So I close the ticket.
