### ISSUE TITLE
Newly created characters repeatedly add their spells to the default positions.

### ISSUE THREAD

**Issue by BattleBoots** [WarEmu/WarBugs#18632]
Hey,

Ever since the patch on the 10th March 2021 newly created characters have a reoccuring issue where after entering/exiting an area that requires a loadscreen (i.e. not on /reload, but zone transition such as Joining / Leaving Scenarios, walking out of the gate of IC / Altdorf, Flight Masters), the game is automatically adding the default spells you start with at level 1 back into their original hotbar positions, and removing any spells you had in those slots. 

Example 1:
Before logout
![1](https://user-images.githubusercontent.com/80541404/110981503-258c1000-835f-11eb-8f3e-55cd40c68c4c.png)

After relog
![2](https://user-images.githubusercontent.com/80541404/110981574-39377680-835f-11eb-9b73-0208967e1d6c.png)

Example 2:
(from \@Lillut\# 2863 on Discord)
![3](https://user-images.githubusercontent.com/80541404/110981786-93383c00-835f-11eb-90fa-53cb9aa8d0a1.png)

Example 3:
[YouTube Video (prior to fresh game reinstall recorded 11th March 2021)](https://www.youtube.com/watch?v=8cea8ztwBXE)

Example 4:
[YouTube Video (after fresh game reinstall & creating brand new character to remove any possibility of it being mod related, recorded 12th March 2021)](https://youtu.be/SxjEpoTvTec)

You can even see the spells being replaced on the action bar before the fade to black happens on the loadscreen in above video (gif below)
![4](https://user-images.githubusercontent.com/80541404/110982191-28d3cb80-8360-11eb-9c56-265e59ba840a.gif)

Steps to reproduce the issue:

1. Create any new character, can be any class. (note: characters made PRIOR to these patch(es) are NOT affected, at least from what I've been able to gather from others and myself.)

2. Move/replace default spells 

3. Complete any hard zone transition (i.e. not a reload or warcamp helicopter) such as Flight Master, War report (to another zone), walking out of Altdorf/IC or just relog.

4. Your default spells will have returned on Action Bar 1, replacing any spells you've placed in those slots.

I'm \@Boots\# 0231 if you've any further queries, though most of the discussion/mention of this issue has taken place on the Discords #Technical-advice channel and they said to post this here. 

Thanks for your hard work as always guys.

______
edits; fixed some formatting and minor spelling mistakes.

edit2: For any other users experiencing this issue and stumbled upon this post, a temporary work around is to use the addon [NerfedButtons](https://tools.idrinth.de/addons/nerfedbuttons/) to assign the spells you would like to the default spots. 

To do this simply go to the link provided, download NerfedButtons (I use v.3.3.2) extract the zip file and navigate to your Return of Reckoning install directory's Interface --> Addons folder and paste the contents of the zip file here.

Then when in game type "/nb ui" to bring up the interface, for the addon drop down select NerfedButtons & for the sequence right mouse click the spell slot you wish to use (you might need to place a spell in it, if the sequence doesn't change to a numeric value, and right click that) and then drag the spell you want to place there and press save & create. This will force that spell to appear in that spot even if you drag it off manually (or when the game automatically replaces it) meaning you'll need to simply create a new nerfedbutton sequence if you wish to move it around. You can place your spells as normal in the action bar spots that are not affected by the bug. [Here's a short video demonstrating what to do in game (albeit, slowly because I'm super new to the addon myself.)](https://www.youtube.com/watch?v=Lv1LDDh4FTI)

**Comment by Naesti** [comment]
I hope this will be solved soon, running out of <40lvl chars :(

**Comment by Qorth** [comment]
Confirmed issue
