### ISSUE TITLE
Destruction T4 Epic Quest Boss not spawned

### ISSUE THREAD

**Issue by Vizio101** [WarEmu/WarBugs#18637]
The destruction T4 Epic Quest Annihilation cannot be completed.  At the stage of quest line where cannons and guard need to be killed the last part is to kill a lvl 40 champ called Duke Wickham.  He is not where he is suppose to be and double checked map coordinates from Wiki and no champ.  After asking about this issue in advice chat two other people responded that within the past two days they both attempted to complete the quest and was unable because Duke Wickham does not spawn.

**Comment by Lheana** [comment]
Related to #16938
