### ISSUE TITLE
is Coordinated Strikes bugged? or just in combat logs

### ISSUE THREAD

**Issue by TheOctagon322** [WarEmu/WarBugs#18631]
**Expected behavior and actual behavior:**
Expected behaviour: 4 strikes 2 from me + 2 from pet.

Actual behaviour: only 2 from me.

On keep lords im 100% sure its bugged not only on combat logs, but against other players not sure.
As you can see combat logs don't even show normal auto pet attacks, ( it is turned on, on the filters ).

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**
![Hungrylion_030](https://user-images.githubusercontent.com/64733933/110976327-6f79f380-8369-11eb-91b2-54ba4c1a36ee.jpg)
![Hungrylion_035](https://user-images.githubusercontent.com/64733933/110976544-ae0fae00-8369-11eb-845f-584bfb340e1c.jpg)

**Comment by Edenwolf5** [comment]
I noticed this a while back in large fights, the pet will do no damage in general, at least untrackable damage via the combat log and scrolling text.

**Comment by admaska2** [comment]
I think its because of this Bug https://github.com/WarEmu/WarBugs/issues/18264, to many people on the lord, so the pet stop dealing damage.
