### ISSUE TITLE
Wild Healing - Archmage Isha Tree tactic not proccing on HoT crit.

### ISSUE THREAD

**Issue by lokigfx** [WarEmu/WarBugs#1863]
Wild Healing from Isha Tree is not proccing when HoT is a critt (e.g. Lambent Aura is not triggering this tactic even when it is critting). On live server this tactic was always proccing when any heal was a crit.

**Comment by Morksezstop** [comment]
i am almost sure it is not suppose to proc from hots same as resto burst is not procing from hots which imo is huge injustice to AM and shamans but that was on live...

**Comment by ozarmidrashim** [comment]
Events that listen for damage listen only for DIRECT damage unless specified in tooltip.

**Comment by lokigfx** [comment]
Well, I was playing archmage a lot on live server and definitely lambent aura was giving proc. Here is a link to a forum post that was relating to a live server and clearly a person describes that this tactic procs from HoTs.

https://forums.freddyshouse.com/threads/tactics-wild-healing-and-restorative-burst.230137/

**Comment by Joiec** [comment]
Played AM as main from release on till end of 2010 (never twinked), and i do believe it DID proc on hot crit ticks, atleast at the time i played. Dunno if you guys remember it, but there was a "big" buff (class tree change + new abilities) to AM/Shaman ( altho eek got nerfed :p ), maybe they set the hot as a bonus to be able to proc it with that change.
