### ISSUE TITLE
[Event][Scurvy Dogs] Kills from all Scenarios add to the kill count task

### ISSUE THREAD

**Issue by zulnam** [WarEmu/WarBugs#18636]
Prerequisites:
A character that has done none of the Scurvy Dogs event tasks.

STR:
1. Queue up for any scenario EXCEPT Ironclad.
2. Wait.
3. Once in, kill members of opposite faction.
4. Inspect Live event.

EXP: No kills should be recorded in the 'Kill 100 enemies' task.

ACT: Kills are recorded from all scenarios.

Before
![Cuza_016](https://user-images.githubusercontent.com/19802847/111015037-234da400-83a7-11eb-8198-f80572bfd9e9.jpg)

After
![Cuza_018](https://user-images.githubusercontent.com/19802847/111015042-2c3e7580-83a7-11eb-87b8-c609195b0ffc.jpg)

**Comment by dalen** [comment]
this was fixed with the hotfix on saturday
