### ISSUE TITLE
[SC][Ironclad] Kills within scenario not rewarding Renown Points

### ISSUE THREAD

**Issue by zulnam** [WarEmu/WarBugs#18635]
Environment:
Order
T2/3

STR:
1. Queue up for Ironclad.
2. Wait.
3. Once inside, kill a member of the opposing faction.
4. Observe scroll text and/or any log window (combat log or custom).

EXP:
Kills reward XP and Renown Points.

ACT:
Kills only reward XP.

Screenshots:

Log
![Rhag_004](https://user-images.githubusercontent.com/19802847/111014408-ca304100-83a3-11eb-9bb5-f64620cc0d06.jpg)

During Combat
![Rhag_015](https://user-images.githubusercontent.com/19802847/111014431-dddba780-83a3-11eb-9df6-6c27be0425c7.jpg)

Example SS of intended functionality. Same char, same day, Gates of Ekrund scenario
![Rhag_009](https://user-images.githubusercontent.com/19802847/111014451-f8158580-83a3-11eb-8a3e-5cb694a26d0d.jpg)

**Comment by dalen** [comment]
this was fixed with the hotfix on saturday
