### ISSUE TITLE
Event sc map Bugg 

### ISSUE THREAD

**Issue by lilisara** [WarEmu/WarBugs#18646]
Huhu you love, I just fell through the map in Event Sc today. It took me minutes to get out of there because at the stool I got no damage until in the water. Lg Lili #
![Lilisara_283](https://user-images.githubusercontent.com/53000111/111053720-7d616e80-8466-11eb-8072-7692ee611f5d.jpg)
![Lilisara_284](https://user-images.githubusercontent.com/53000111/111053721-7e929b80-8466-11eb-9871-e75c77fce257.jpg)

**Comment by waerter** [comment]
Same issue as #18644

**Comment by MaxHayman** [comment]
Should be fixed refer to #18644
