### ISSUE TITLE
[Scenario] [The Ironclad] I can't get into Destro Camp from the water

### ISSUE THREAD

**Issue by Syzako** [WarEmu/WarBugs#18640]
I can't get into Destro Camp from the water on **both sides**, but other players **can**.

First side:

![3](https://user-images.githubusercontent.com/39750677/111025277-22fce980-8437-11eb-9a18-47f98fd8f46e.png)
![1](https://user-images.githubusercontent.com/39750677/111025275-209a8f80-8437-11eb-8e91-b72f89819e73.png)
![2](https://user-images.githubusercontent.com/39750677/111025276-21cbbc80-8437-11eb-8cd8-852e8357c156.png)

Second side:

![5](https://user-images.githubusercontent.com/39750677/111025279-25f7da00-8437-11eb-829e-ed25188c0ede.png)
![4](https://user-images.githubusercontent.com/39750677/111025278-24c6ad00-8437-11eb-9532-675e494bdf47.png)

**Comment by dalen** [comment]
use one of the sea mines to get back on  the ship.
