### ISSUE TITLE
Chapter 22 PQ "All the King's Men" in Reikland Is Not Spawning Mobs or Showing Objectives

### ISSUE THREAD

**Issue by Topologic** [WarEmu/WarBugs#18647]
**Expected behavior and actual behavior:**
The PQ should show its status on the UI in terms of objectives to complete, and it should be spawning appropriate mobs to kill to advance those objectives.  Currently it is doing neither.  Attached screenshots are to show that the PQ is completely empty and that the UI is not even acknowledging there is a PQ there in the first place.

**Steps to reproduce the problem:**
Merely go to the PQ in question and observe that it is not working.  As for how this happened, I am unfortunately not able to help with that.

**Testing Screenshots/Videos/Evidences (always needed):**

![Topocurse_122](https://user-images.githubusercontent.com/13059408/111054904-5000ca80-843e-11eb-80f1-20b18b14633b.jpg)
![Topocurse_123](https://user-images.githubusercontent.com/13059408/111054913-6dce2f80-843e-11eb-8573-5c479d1cca86.jpg)
![Topocurse_124](https://user-images.githubusercontent.com/13059408/111054914-6e66c600-843e-11eb-90d2-133f996e73df.jpg)
![Topocurse_125](https://user-images.githubusercontent.com/13059408/111054915-6e66c600-843e-11eb-93ac-0114b78c62d6.jpg)

**Comment by dalen** [comment]
Fixed in the 2021-03-18 patch
