### ISSUE TITLE
DoK Khaine's Refreshment only healing group and warband members

### ISSUE THREAD

**Issue by demodw** [WarEmu/WarBugs#1864]
As title says. On live this used to affect everyone in a 30 feet range.

**Comment by ozarmidrashim** [comment]
Target type is not Group in DB, it's All Allies

**Comment by Novgoroth** [comment]
I can confirm it only targets people in party/wb/sc party.
Other people don't receive the heals, so there's a problem with this skill, yes :/

**Comment by ozarmidrashim** [comment]
Bug in target handler
