### ISSUE TITLE
Falling through the Floor/Terrain

### ISSUE THREAD

**Issue by waerter** [WarEmu/WarBugs#18644]
**Expected behavior and actual behavior:**
I joined the Sc but everytime i was moving I fell through the ground and died after ca 20 Sec. Apparently there was at least one other Player with the same problem. 
**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**
![Randahle_000](https://user-images.githubusercontent.com/62266826/111039611-32783480-842f-11eb-98aa-1ce33ac08fe4.jpg)

Look here for the chat message from the other player: 

![Randahle_008](https://user-images.githubusercontent.com/62266826/111039648-6b180e00-842f-11eb-8119-6587af68a4a2.jpg)

**Comment by Wraxin** [comment]
https://cdn.discordapp.com/attachments/730367357503012904/821502071148511232/unknown.png
This need to be fixed asap...

**Comment by Symbelmyne** [comment]
This is kind of new bug, i had it twice in a week, very annoying, fall phase keeps you in combat so cannot log out duirng fall, and fall begins within few seconds  just after press release. And more and more ppl experience it. Everytime it happens after a change/reload map, like release to warcamp, fly to other zone port to scenario in/out.

**Comment by waerter** [comment]
Had the same Issue today again in Altdorf City Defense. 
After killing the Client and deleting Cache it worked. 
Others said they had the same Issue and managed also with Client Kill and deleting Cache to fix it temporary.

**Comment by MaxHayman** [comment]
Hello,

We have been investigating this issue and due to the inconsistent nature of the issue its hard to reproduce. However we have theorised the cause of the issue and have applied a fix in todays (08/04/2021) hot fix. Please let us know if you experience it again.

Max

**Comment by MaxHayman** [comment]
Assume fixed
