### ISSUE TITLE
Garden of Qu'aph duels, buffs/debuffs show incorrect duration

### ISSUE THREAD

**Issue by bloodmasked** [WarEmu/WarBugs#18653]
When dueling somebody of the same faction (did not test versus other) buffs/debuffs such as immunities, dots, etc, would not show their correct duration on both players.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
But I need more imput, your report is too general.

**Comment by lilimx** [comment]
Hey,

im going to close this ticket now due to no feedback.
