### ISSUE TITLE
[Quest] Land of Shadows - Dark Elf 5 - Endhrios Silentfall has indeed fallen into the mountain making them untargetable, so cannot complete quest.

### ISSUE THREAD

**Issue by Backlash50** [WarEmu/WarBugs#18650]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Backlash50** [comment]
Endhrios Silentfall has indeed fallen into the mountain making them untargetable, so cannot complete quest.

**Comment by Lheana** [comment]
Related to #16938
