### ISSUE TITLE
High Elf Chapter 3 - PQ Shattered Beach

### ISSUE THREAD

**Issue by andytomlins** [WarEmu/WarBugs#18652]
The area classed as the High Elf Chapter 3 PQ Shattered Beach is to the south of where the actual PQ is located.

PQ area
![WAR-64 2021-03-14 19-56-10](https://user-images.githubusercontent.com/6351625/111082296-6589f900-84ff-11eb-9940-fa43603a9473.png)

Where the area classed as the PQ starts.
![WAR-64 2021-03-14 19-56-32](https://user-images.githubusercontent.com/6351625/111082328-99fdb500-84ff-11eb-8916-8f1129ef56bf.png)

**Comment by dalen** [comment]
Fixed in the 2021-03-18 patch
