### ISSUE TITLE
Caul the Soulless gone hiking in Chaos Waste- NPC Teleport- Now unreachable 

### ISSUE THREAD

**Issue by NogginGnome** [WarEmu/WarBugs#18657]
Caul the Soulless has teleported from the Seven Shades Creep warcamp in Chaos Wastes to the peak of a nearby mountain, this prevents players from picking up and handing in their RvR quests. I relogged twice to see if anything changd and it didnt. 
![Screenshot (1)](https://user-images.githubusercontent.com/80725054/111235163-ffc56c00-85e7-11eb-8c08-61c1db63128c.png)
![Screenshot (2)](https://user-images.githubusercontent.com/80725054/111235166-02c05c80-85e8-11eb-83f8-c140e7d7b4c4.png)

**Comment by Lheana** [comment]
Related to #16938
