### ISSUE TITLE
WL Pet Echoing Roar Damage bug

### ISSUE THREAD

**Issue by admaska2** [WarEmu/WarBugs#18651]
Hello, since the new patch the WL spell Echoing Roar bug for the pet.

Currently Echoing Roar pet damage doesnt Exist, the dot is apply but deal 0 damage .

![Echoing bug](https://user-images.githubusercontent.com/43276959/111069506-a406c000-84cd-11eb-8b77-83c227363ef1.png)

**Comment by admaska2** [comment]
I test in pvp, the spell work work in PVP, bug only in PVE

**Comment by Azeyune** [comment]
Since the new patch, pet  Echoing Roar stop working in pvp to now

**Comment by lilimx** [comment]
Hey,

it works for me in PVE without any issue.

![grafik](https://user-images.githubusercontent.com/23266079/123513414-69e0b900-d68d-11eb-832f-ce7aaa6c2e61.png)

Maybe someone can confirm this (+ for RvR)

**Comment by lilimx** [comment]
Hey,

im going to close this ticket now due to no feedback.
If you are the opinion this issue still persists, please open a new ticket and use the "#XXXXX" number of your former ticket to link it.
