### ISSUE TITLE
High Elf Chapter 4 - PQ Blackwood Hill Garrison

### ISSUE THREAD

**Issue by andytomlins** [WarEmu/WarBugs#18654]
The area of the PQ Blackwood Hill Garrison get the PQ progress tracker from the wrong PQ.

![WAR-64 2021-03-15 11-24-30](https://user-images.githubusercontent.com/6351625/111146433-55b2f900-8581-11eb-8c6e-8cd51150cfac.png)

**Comment by dalen** [comment]
Fixed in the 2021-03-18 patch
