### ISSUE TITLE
Drop That!! is uncleanseable

### ISSUE THREAD

**Issue by Teefz** [WarEmu/WarBugs#18659]
**Expected behavior** 

"Drop That!!" (disarm from pet) should be an Ailment, so it is cleanseable. Currently it is not.

**Actual behavior:**

"Drop That!!" is classified as a Cripple, making it uncleanseable.

**Steps to reproduce the problem:**

Read tooltip / press the button and watch the debuff

**Testing Screenshots/Videos/Evidences (always needed):**
![dropthat](https://user-images.githubusercontent.com/18510648/111261323-9747b080-8622-11eb-904e-cf2bcf002a14.jpg)
![dropthattip](https://user-images.githubusercontent.com/18510648/111261432-c52cf500-8622-11eb-9c42-65e9573ca507.jpg)

**Comment by Lheana** [comment]
This should have been fixed.
