### ISSUE TITLE
AM "Funnel Essence"

### ISSUE THREAD

**Issue by Joiec** [WarEmu/WarBugs#1866]
Sometimes only initial tick is healing and the other 3 ticks are missing, altho channel is casted to the end. Sometimes it is working and i see 4 ticks in combat log + on ppls health, could not reproduce the situation where only initial tick is healing. Might be lag might be something else dunno.

edit: grinded mobs with a grp for some time, even without lag its rarely working, most of the time it only heals with the initial and misses 3 more heal ticks

**Comment by ozarmidrashim** [comment]
Apparently linked to high stacks of mechanic
