### ISSUE TITLE
Da Stunty Mystery Quest

### ISSUE THREAD

**Issue by Dottina** [WarEmu/WarBugs#18662]
You can't get up there. Always stuck

![Senjina_001](https://user-images.githubusercontent.com/33136435/111303385-bfe89e00-8654-11eb-9a09-af6546b7ccc8.jpg)
![Senjina_002](https://user-images.githubusercontent.com/33136435/111303418-c840d900-8654-11eb-8696-f46d321c161a.jpg)

**Comment by TVBrowntown** [comment]
Not true, completed this last week - jump towards the right side. Might help using a mount as well for extra speed
