### ISSUE TITLE
Gas Squig's ability debuffs needs to be swapped

### ISSUE THREAD

**Issue by Teefz** [WarEmu/WarBugs#18661]
**Expected behavior:**

Gas Squig's "Spore Cloud" should be a "Damaging" debuff.

Gas Squig's "Goop Shooting"'s debuff should be an "Ailment".

**Actual behavior:**

Spore Cloud = Ailment

Goop Shooting = Damaging

**Steps to reproduce the problem:**

Summon Gas Squig, read the tooltips and pop squig frenzy before testing on hostile.

**Testing Screenshots/Videos/Evidences (always needed):**
![Goop](https://user-images.githubusercontent.com/18510648/111262877-3f5e7900-8625-11eb-9eb5-20a22c123856.jpg)
![spore](https://user-images.githubusercontent.com/18510648/111262883-42596980-8625-11eb-8a12-93779696674f.jpg)

**Comment by Lheana** [comment]
This should have been fixed.
