### ISSUE TITLE
Engineer turrets bugs

### ISSUE THREAD

**Issue by Asciuga** [WarEmu/WarBugs#18669]
Hello, after the most recent server reboot a bug appeared .. my turret disappears when i try to pull a mob or a character. Sometimes the turret seems to work but it doesn't. the proximity buff does not work and the turret does not fire.
I don't know if it's just my problem or if it's a problem for all players.
can you fix the problem?

**Comment by Asciuga** [comment]
https://youtu.be/JitmoSSFnr0 

Look.. This is my problem!

**Comment by Asciuga** [comment]
https://youtu.be/RLv8e-Wnw0U

Look! This is my problem!

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. 
I will add this ticket to a related issue.

**Comment by lilimx** [comment]
related / dublicate #18872
