### ISSUE TITLE
magus skill bug.

### ISSUE THREAD

**Issue by dadly18** [WarEmu/WarBugs#18665]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

magus summun demon and take buff.
and demon is atteck 
and Sometimes I don't get summoned.

summun demon dont atteck. and. cant magus ability

**Comment by dadly18** [comment]
https://youtu.be/dmme1i7QPiY

https://youtu.be/fcj1lipiuxQ

magus core ability resummon after work. but next new summun demon is not work

**Comment by lilimx** [comment]
Hey,

I've tried to reproduce your issues, but it works fine for me. I'll close this ticket now.
If you are the opinion the issue still persists, please open a new ticket and we will take a look into your issue again.
