### ISSUE TITLE
Losing Ground

### ISSUE THREAD

**Issue by Kheanor** [WarEmu/WarBugs#18663]
High elf chapter 14 Losing Ground quest has the task to kill 7 Yukha Grunts. They aren't spawned in the greenskin village where they supposed to.

**Comment by Lheana** [comment]
Well they are on my side
![Lheana_232](https://user-images.githubusercontent.com/11537611/111872982-681ca080-898e-11eb-82be-b98223308569.jpg)

**Comment by Lheana** [comment]
That's because the PQ was broken before the last patch: #18616
It has been fixed with the last patch.

**Comment by Kheanor** [comment]
Thank you very much!
