### ISSUE TITLE
missing character

### ISSUE THREAD

**Issue by Gokudou** [WarEmu/WarBugs#18664]
after today's server reboot, the character disappeared (marauder 8 lvl)
instead, magus 2 lvl appeared (previously created but deleted/changed to a marauder)

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by MaxHayman** [comment]
What were the character names?

**Comment by Gokudou** [comment]
Character name Gokudou, played for about 4-5 hours (8 or 9 LVL)

**Comment by Gokudou** [comment]
do not restore the previous character, created a new one. I hope there will be no more such bug...

**Comment by MaxHayman** [comment]
I've managed to find the root cause of the issue so this shouldn't happen to anyone in the future.

**Comment by Lheana** [comment]
This has been fixed with the patch of 31/03/2021.
