### ISSUE TITLE
Horned Squig's abilities flagged as wrong debuff type.

### ISSUE THREAD

**Issue by Teefz** [WarEmu/WarBugs#18660]
**Expected behavior:**

Horned Squig's abilities+their debuff to the target should be classified as Ailments. 

**Actual behavior:**

Currently they are flagged as "Damaging" and "Cripple". Making them uncleanseable. 

**Steps to reproduce the problem:**

Summon Horned Squig / test abilities on hostile.

**Testing Screenshots/Videos/Evidences (always needed):**
![headbutt](https://user-images.githubusercontent.com/18510648/111261997-b2ff8680-8623-11eb-8dec-0ab426da43de.jpg)
![gore](https://user-images.githubusercontent.com/18510648/111262004-b6930d80-8623-11eb-8cda-57f54460eb21.jpg)

**Comment by Lheana** [comment]
This should have been fixed.
