### ISSUE TITLE
T3 Epic quest Will of the Warboss mobs not spawning

### ISSUE THREAD

**Issue by Zdalker3000** [WarEmu/WarBugs#18666]
PQ Revoltin' Gobbos does not have Moonfang Stickpointa mobs. Not on any stage. Saw same bugs at 2017 reports here, then GM's spawned mobs near area. Not present atm. So quest is roadblocked.

**Steps to reproduce the problem:** Take T3 epic q on orc side.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/80794273/111389721-83538b80-86c2-11eb-95f0-4cfcb3379567.png)

**Comment by Lheana** [comment]
Fixed with the patch of 26/03/2021.
