### ISSUE TITLE
The city siege queue system randomly kick some groups on instance creation.

### ISSUE THREAD

**Issue by engharat** [WarEmu/WarBugs#18671]
The problem happened twice to me, but it happened to other people too. I don't have any way to demonstrate it as it would require a streaming video. Anyway, I noticed that the city queue system sometime removes from the queue a warband (today we were 6man, but happened on a duo too) when an instance is created. Today it was particularly evident because my 6man group got kicked from queue at instance 11 creation, then we requeued, then kicked out again at 12 and at 13 instance. No one were in a fort or forbidden zone - we were sitting on reikwald portal and in IC. No quitter debuff is given.

**Comment by GamesBondd** [comment]
Since city queue has been worked on again, I believe the issue is not occurring anymore since we did not get any new reports in the  last 3 months.
