### ISSUE TITLE
Talismanmaking broken

### ISSUE THREAD

**Issue by Mepiff** [WarEmu/WarBugs#18673]
When i try to add ANY fragment into the talisman making box the game prints
"Bad seed data. Since the seed couldn't be generated, it has been lost."
![unknown](https://user-images.githubusercontent.com/80894705/111619666-23ee9c00-87e6-11eb-9bae-686eb0ca0411.png)

**Comment by gustavhunter** [comment]
Same issue.

**Comment by Ninjagon** [comment]
I can confirm this bug.  I have tested few different fragments, and the results is always error message: "Bad seed data. Since the seed couldn't be generated, it has been lost."
![Carnow_033](https://user-images.githubusercontent.com/80913476/111665589-2b786a00-8813-11eb-9600-b44be6c2b6c8.jpg)

**Comment by MaxHayman** [comment]
Fixed issue. Also added an error message when you try to add a fragment before a container.

**Comment by dalen** [comment]
fixed in 2021-03-19 hotfix
