### ISSUE TITLE
New Scoreboard features do not show in City sieges

### ISSUE THREAD

**Issue by bloodmasked** [WarEmu/WarBugs#18676]
When hovering over scoreboard, there is suppose to be extra info such as 
![image](https://user-images.githubusercontent.com/6406832/111743136-1cb2b580-88ee-11eb-92bc-ec1f860943ba.png)

However in my city siege today, I couldn't see any of this. But in a scenario I just did (screenshot) I could see it as intended.

**Comment by Lheana** [comment]
This should have been fixed.
