### ISSUE TITLE
[Quest] 'Bringing Down the Squig-Maker' does not work

### ISSUE THREAD

**Issue by Andrey-Bulatov** [WarEmu/WarBugs#18672]
Order quest 'Bringing Down the Squig-Maker' requires to obtain quest item 'Squig Proddin' Hand' from Kurga da Squig-Maker, hero at the Gunbad left wing. Killing Kurga in different manner does not drop quest item.

Repair the quest please!

**Comment by Kabucoror** [comment]
Works fine for me. Can you provide more info?

**Comment by Andrey-Bulatov** [comment]
Worked fine for me last time. So i count this issue as random error, where 2 tries gave no quest loot. If you need not further investigation, you may close this issue. Or I can inform you of new Gunbad runs - is drop always works or not.
