### ISSUE TITLE
Grievous Harm M3 parried

### ISSUE THREAD

**Issue by stanley-1986** [WarEmu/WarBugs#18684]
Im pretty sure Slayer M3 shouldn't be parried but it can be

**Comment by lethewyvern** [comment]
> Im pretty sure Slayer M3 shouldn't be parried but it can be

any evidences of this m being parried?

**Comment by stanley-1986** [comment]
Its ok ive gone thru my stream there was two parrys either side of the m3, and the visual of the m3 is way after the actual damage

**Comment by lilimx** [comment]
Hey,

so is this still an issue? And if yes, could you post this video or some screenshots?

**Comment by lilimx** [comment]
Hey,

im going to close this ticket now, because no evidence was brought.
If you're the opinion the issue still persists, please open a new report.
