### ISSUE TITLE
Falling through the map in The Eternal citadel scenario.

### ISSUE THREAD

**Issue by dredfury** [WarEmu/WarBugs#18688]
**Expected behavior and actual behavior:**
I should be able to play the actual map of the scenario but i guess i discovered a new dimension.

**Steps to reproduce the problem:**
I really have no clue. I just joined a scenario and fell.

**Testing Screenshots/Videos/Evidences (always needed):**
The url for the video is: https://www.youtube.com/watch?v=0nA4RND8yCs

**Comment by waerter** [comment]
Same issue as #18644

**Comment by MaxHayman** [comment]
Should be fixed refer to #18644
