### ISSUE TITLE
Ambush Pass PQ broken at 9/30 crates stage 1

### ISSUE THREAD

**Issue by Delegator2** [WarEmu/WarBugs#18685]
**Expected behavior and actual behavior:**
The Ambush Pass PQ in Dwarf chapter 15 stops counting crates at 9/30 gathered. Kills of greenskins progress normally to 60/60.

**Steps to reproduce the problem:**

Gather 9 crates. After that, crates that look active still don't give credit.

**Testing Screenshots/Videos/Evidences (always needed):**

Don't have a video and the screenshot wouldn't prove anything. But the quest is stuck at 9/30 right now.

**Comment by Lheana** [comment]
I tested it on my own, and did not notice any issue, I can collect the crates without problem. Try to leave the PQ area and come back if it happens again, or provide more details about how to reproduce it.

**Comment by Lheana** [comment]
Did more tests and I think I could reproduce the bug, so I reopen the ticket.

**Comment by Lheana** [comment]
This should have been fixed with the patch of 26/03/2021.
