### ISSUE TITLE
Plague Mist Vale PQ Broken

### ISSUE THREAD

**Issue by Delegator2** [WarEmu/WarBugs#18686]
**Expected behavior and actual behavior:**

Plague Mist Vale PQ is not spawned at all and doesn't show up on the HUD. Completely broken.

**Steps to reproduce the problem:**

Go to the PQ. It ain't there.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
Fixed with the patch of 26/03/2021.
