### ISSUE TITLE
Event scenario map bugged

### ISSUE THREAD

**Issue by Ninjagon** [WarEmu/WarBugs#18681]
Isha event scenario map is bugged - few steps from order spawn point and you will drop from the map into the nowhere. It happen my whole premade group of 6. It happened over and over again.
Screenshots there:
![Ninjagon_244](https://user-images.githubusercontent.com/80913476/111802812-b5d1d400-88ce-11eb-9fe1-c7a35296f71b.jpg)
![Ninjagon_243](https://user-images.githubusercontent.com/80913476/111802818-b7030100-88ce-11eb-9237-377b093accf8.jpg)

**Comment by geezereur** [comment]
Same with my DoK on destro side.

**Comment by waerter** [comment]
Same Issue as #18644

**Comment by MaxHayman** [comment]
Should be fixed refer to #18644
