### ISSUE TITLE
Guns of Nordenwatch Scenario Not Available

### ISSUE THREAD

**Issue by JaqiC** [WarEmu/WarBugs#18680]
As I was cycling through the scenarios to find one to join earlier today, I noticed that the Guns of Nordenwatch scenario is no longer in the cycle of available scenarios.  I relogged to see if there was possibly a glitch when I started up the game, but this was still not available.  Is this being left out intentionally or was this an inadvertent omission? 

Thank you

**Comment by dalen** [comment]
The list of available scenarios are rotated every week. It is still in the game and will become available again for queueing in the future.
