### ISSUE TITLE
Backpack does not show stack sizes until stack is moved or acted on

### ISSUE THREAD

**Issue by Delegator2** [WarEmu/WarBugs#18694]
**Expected behavior and actual behavior:**
In the inventory (backpack), if you have a stack of items: potions, crafting components, etc., the stack size is not displayed until you somehow act on the stack: move it, attempt to split it, use a potion, etc. 

**Steps to reproduce the problem:**

See the attached screenshots. 

1. Crafting backpack no stack size: shows that none of the components display a stack size
2. Crafting Backpack Moved one stack of magical essence: I have moved the magical essence on the far right, and its stack size now magically appears
3. Main backpack, similar showing what happens with the stack size of potions, first not there, then when I shift-right-click to split the stack the number shows in that window, and then even though I didn't split the stack the number now displays on the stack of 11 potions.
![Main backpack stack size now shows for that item](https://user-images.githubusercontent.com/77587188/111914274-bd68b880-8a47-11eb-924a-7850a0814257.png)
![Main backpack attempt stack split shows size](https://user-images.githubusercontent.com/77587188/111914276-be014f00-8a47-11eb-97ab-819a5bafda6f.png)
![Main backpack no stack sizes](https://user-images.githubusercontent.com/77587188/111914277-be99e580-8a47-11eb-920c-d6d7fec08cfe.png)
![Crafting Backpack Moved one stack of magical essence](https://user-images.githubusercontent.com/77587188/111914279-be99e580-8a47-11eb-814a-64d56a84a65f.png)
![Crafting Backpack No Stack Size](https://user-images.githubusercontent.com/77587188/111914280-bf327c00-8a47-11eb-8e61-bcf6959e537e.png)

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
I don't have this issue. This must be related to your installation. Please use our forum or Discord for support.
