### ISSUE TITLE
Squig Herder pet damage [intermittently]  not reported in combat tab or scrolling combat text/damage.  Sometimes pet won't even attack pve target when commanded, when master has not engaged yet.

### ISSUE THREAD

**Issue by xoonerbig** [WarEmu/WarBugs#18695]
This just started after the last patch.

About 1/2 the time when I attack a new pvp target my pet's damage will not be reported in the combat tab/log or appear in the scrolling combat text.  I can /reload or summon and new pet and it may fix the problem temporarily.  The problem appears to be intermittent.  

Also, intermittently in pve if I command my squig pet to attack the pve target it doesn't attack the pve target, the pet just sits there, even if I press the pet attack button many times.   If the master attacks the pve monster the pet will then join in.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket,
But these are two issues in one ticket.
Please open two new tickets, for each issue a separate one.
