### ISSUE TITLE
Abilities keep re-adding themselves to hotbar

### ISSUE THREAD

**Issue by nuitaran** [WarEmu/WarBugs#1869]
Every time I gain a level, all my abilities re-add themselves to my hotbar in the default locations.

**Comment by Evildoor** [comment]
Seems familiar... Are you sure this is not #1488?

**Comment by nuitaran** [comment]
I guess it's possible, but in this case it's using all my abilities every time I level and even going so far as to overwrite other abilities. :-/

**Comment by Evildoor** [comment]
Overwriting other abilities happens in #1488. Affecting all abilities, and on level up, is a new thing though...

**Comment by nuitaran** [comment]
I'll try and do some vetting and further testing so far but as of the last occurrence it wasn't limited to the starting abilities.

**Comment by nuitaran** [comment]
So, I've finally gotten around to doing some testing on this and here's what I've discovered.  You are correct, it is the same issue.  It doesn't actually happen WHEN I level, but it almost always happens if I zone or log immediately following a level.

**Comment by Evildoor** [comment]
Ok, then it's #1488, so i'm closing this.
