### ISSUE TITLE
T1 Greenskin Rally Master Not Visible

### ISSUE THREAD

**Issue by Teraka01** [WarEmu/WarBugs#18699]
**Expected behavior and actual behavior:**
No Rally Master Visible To Claim T1 Greenskin Influence Rewards

**Steps to reproduce the problem:**
Tried /reload without success
Tried relogging/reloading game many times without success
Asked for confirmation from other players and received confirmation that they could also not see NPC

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
![Anaehll_462](https://user-images.githubusercontent.com/11537611/112046266-191c6a00-8b4c-11eb-96e5-789de880f20b.jpg)
He is exactly where he is supposed to be.

**Comment by Teraka01** [comment]
That's the chapter 1 rally master NOT the T1 Rally Master. i.e. the PVP Rally Master.

**Comment by Teraka01** [comment]
Yay he's back. Thanks.

**Comment by Lheana** [comment]
Then I close it.
