### ISSUE TITLE
NPCs Missing to complete quest

### ISSUE THREAD

**Issue by Ghatisgob** [WarEmu/WarBugs#18698]
**Expected behavior and actual behavior:**
NPCs Moonfang Stickpointa are missing to complete Destro Epic Quest, Will of the Warboss.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Thags_002](https://user-images.githubusercontent.com/25305100/112033082-588f8a00-8b3d-11eb-845c-fc9dc89496c7.jpg)
![Thags_003](https://user-images.githubusercontent.com/25305100/112033092-5c231100-8b3d-11eb-81fd-146a0a3b8b61.jpg)

**Comment by Lheana** [comment]
Duplicate of #18666
