### ISSUE TITLE
I managed to get 64k armor.

### ISSUE THREAD

**Issue by dredfury** [WarEmu/WarBugs#18697]
**Expected behavior and actual behavior:**
So it seems when a enemy is reducing your armor and then either you or someone from your party uses a dmg mitigation spell like immutable defiance or distracting bellow or challenge the game bugs and gives you 64k armor.

**Steps to reproduce the problem:**
Not 100% sure that this is how it happens but it happened to me twice this way. Have a enemy use armor reduction on you and then either you or a party mate cast a damage mitigation spell like immutable defiance or distracting bellow or challenge.

**Testing Screenshots/Videos/Evidences (always needed):**

![arm](https://user-images.githubusercontent.com/71196700/111979614-f4090680-8b0d-11eb-9a28-41a2ed0717e9.png) Here is 2nd link incase the other one doesnt work
https://cdn.discordapp.com/attachments/217234129782177792/823510576549986324/arm.png

**Comment by Lheana** [comment]
Fixed with the patch of 26/03/2021.
