### ISSUE TITLE
Warhammer - Loading scenrios

### ISSUE THREAD

**Issue by Galladriall** [WarEmu/WarBugs#18690]
Every time I load into a scenario, doesn't seem to matter which one, I get booted to desktop.

I have followed all steps on Warhammer forums in case it was a framerate issue, emptied cache and all suggestions I could find, no good.

I have re-run start many times to repatch and have repaired files twice.

Still no good.

**Comment by lilimx** [comment]
Hey,

I'll close this thread. I recommend to join the RoR discord and ask in #technical-advice.
