### ISSUE TITLE
Getting "Too many quests" error when there are not too many in questbook

### ISSUE THREAD

**Issue by valkeera** [WarEmu/WarBugs#18692]
On one of my characters (Blackguard) I'm currently having a problem that I cannot take any more quests, even though the list of active quests takes up only one and a half page in the questbook. On a different character (Dok) I'm not having this problem and I can take up 2,5 pages of quests easily.

Below is a screenshot of active quests for my BG, in case there are some that might be causing this blockage.

![Zeraton_053](https://user-images.githubusercontent.com/58527250/111900549-89839800-8a33-11eb-9d17-52d02f14c14b.jpg)

![Zeraton_054](https://user-images.githubusercontent.com/58527250/111900557-91433c80-8a33-11eb-8814-1cc0d3f7259c.jpg)

**Comment by barbanera86** [comment]
i have the same problem,you have resolve it?

**Comment by valkeera** [comment]
Nope, still not fixed, it got even worse as now I'm not able to take more that 1 page of quests...
It's still happening only to one of my chars though, all other are fine.
I'm posting new screenshots with the up-to-date list of quests, in case it helps to identify the breaker...

![Zeraton_000](https://user-images.githubusercontent.com/58527250/121800749-ed34f000-cc33-11eb-931b-6277f195c2a5.jpg)

![Zeraton_062](https://user-images.githubusercontent.com/58527250/121800759-fa51df00-cc33-11eb-9acc-f50ddefccf83.jpg)

**Comment by Lheana** [comment]
@valkeera Can you contact me on Discord asap?

**Comment by Lheana** [comment]
@barbanera86 Do you roam in PvE, like doing quests, PQs on your bugged char?

**Comment by lilimx** [comment]
Fixed with Patch 11/2/2022
