### ISSUE TITLE
'The Emperor's Mandate' (part 4) unable to be completed

### ISSUE THREAD

**Issue by Irrel** [WarEmu/WarBugs#187]
The objective is to talk to 4 of the Grey Lady Patrons and then talk to Innkeeper Svetla, none of this is currently functional.

**Comment by Evildoor** [comment]
Stage 4 works properly. Minor problems with this quest:
1) You can talk to Innkeeper Svetla before interrogating the patrons.
2) At stage 5 Corrupter Bathshida spawns near another hostile NPC, Markus the Betrayer, and they attack each other, which can prevent you from killing her.
3) At stages before stage 5 NPCs (Wilhem, for example) are not always marked on map.
4) When you go to Aldric Ohrsten, he gives you a choice of reward. Then he gives you the next stage of the quest, after which he gives you exactly the same set of rewards. Not sure if this is correct or not.
https://github.com/WarEmu/WarBugs/issues/1034 indicates the same problem.
5) Aldric sends you to kill 10 Plagued Forsaken and investigate 10 Cesspools. This is incorrect according to
http://www.warbits.com/gold-quests-1916-The-Emperors-Mandate.html
http://www.warbits.com/gold-quests-1917-The-Emperors-Mandate.html
6) In the stage with neutralizing the Cesspools you can do so without finding Holy Salt.
7) Quest reward Fleeting Potion of Pith is not working.
8) There is more than one Ritualist Navr in the Spindekraken.

**Comment by Soulwhisper** [comment]
Works now. @Luth-RoR
