### ISSUE TITLE
Sacrifices Rewarded Not Working

### ISSUE THREAD

**Issue by WJamesLord** [WarEmu/WarBugs#18704]
The racial Dark Elf tactic, Sacrifices Rewarded, does not work.

**Expected behavior and actual behavior:**
Every time you are crit, an 600 point absorb should proc with a 3 second cool down.  An absorb never procs.

**Steps to reproduce the problem:**
Simply get crit by an enemy.  No absorb procs.

**Testing Screenshots/Videos/Evidences (always needed):**

Screenshot really not needed.

**Comment by wargrimnir** [comment]
Seems to be working
https://www.returnofreckoning.com/forum/viewtopic.php?f=73&t=45046
