### ISSUE TITLE
Bloodwrought Enclave: Dead Healer

### ISSUE THREAD

**Issue by Idrinth** [WarEmu/WarBugs#18701]
**Expected behavior and actual behavior:** The healer of the beginning of BE should be alive, but is dead

**Steps to reproduce the problem:** Run BE

**Testing Screenshots/Videos/Evidences (always needed):**
![Idrynth_010](https://user-images.githubusercontent.com/7874631/112068370-0dd83700-8b6a-11eb-81f0-55b204c88f52.jpg)

**Comment by lilimx** [comment]
Hey,

was she dead from the start?

**Comment by lilimx** [comment]
Hey,

im going to close this ticket now due to no feedback.

Note: I've run into BE and she was alive...
If you're the opinion this issue still persists, please open an new ticket and add the #XXXXX number to your new ticket.
