### ISSUE TITLE
Marauder: Ferocious Assault gives incorrect Strength/Toughness amount when using Potion

### ISSUE THREAD

**Issue by BulletTea** [WarEmu/WarBugs#18708]
Expected behavior and actual behavior:
Ferocious Assault tooltip says it gives 190 Str and 190 Toughness, yet with a 80 Str pot it gives 110 Strength and 190 Toughness.
With a +50 Toughness potion it gives 140 Thoughness.

Steps to reproduce the problem:
Use a STR/Toughness Potion and then use Ferocious Assault ability on a Marauder.
I had 13 points into Path of Monstrosity when testing this.

Testing Screenshots/Videos/Evidences (always needed):

![grafik](https://user-images.githubusercontent.com/81259223/112201199-4c283180-8c10-11eb-93a6-9f8739bd8b45.png)
![grafik](https://user-images.githubusercontent.com/81259223/112201242-54806c80-8c10-11eb-865d-0147a6aed848.png)

**Comment by Wraxin** [comment]
Potion buff and skill buffs not stack, so everything is fine.
