### ISSUE TITLE
Wilhem's fist Outer Oil Bugged.

### ISSUE THREAD

**Issue by Tsunade92** [WarEmu/WarBugs#18707]
Hi Everyone!

There is a bug with Outer oil on Wilhem's Fist Keep in Reikland.
No one can Damage the oil EXCEPT from Extra range Engies. Playing as a BW i usually can damage outer oil with fireball 100ft) but not this one. There is no "space" for ranged dps to damage this outer oil except for Engies with their 2dots and extra range :).

If you may take a look at this bug.

Regards.

**Comment by lilimx** [comment]
Hey,

thank you for your report. I will add your ticket to a related issue.

**Comment by lilimx** [comment]
dublicate / related to #15675
