### ISSUE TITLE
i keep getting rvr loot bags

### ISSUE THREAD

**Issue by rpvd** [WarEmu/WarBugs#18706]
Hi,

I notice that i keep getting loot bags even if i did not play rvr since yesterday (6pm server time). I left my toon in reikland wc before i logoff. I feel like cheating for always getting this loots for free every time i login. 

Hope you can check this issue.

Regards and more power.

**Comment by Gagaddon** [comment]
Hello , today im back form work and havent play during this all day. but im receive bags and rr/xp for a participation in battle that im not participate. 

![converted-WAR-64 2021-03-29 18-10-05-71](https://user-images.githubusercontent.com/52387005/112902555-aca9e980-90bc-11eb-8d61-617fa73f3843.jpg)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. I will add this report to a related issue.

**Comment by lilimx** [comment]
related to #16649
