### ISSUE TITLE
Scenario Manager is overfilling SCs.

### ISSUE THREAD

**Issue by kekkers119** [WarEmu/WarBugs#18717]
Expected behavior:
The SC manager should create scenarios and give out equal numbers of queue pops for that Scenario

Actual behavior:
The SC manager is overpopulating one faction in scenarios causing imbalance and sometimes they just get hard shut down. Worse they carry on and you get smashed due to being down 4+ players.

![moarimbalance](https://user-images.githubusercontent.com/42598271/112735843-bdbff280-8f24-11eb-9072-dada993961b8.png)
![moarimbalancedscs](https://user-images.githubusercontent.com/42598271/112735846-bef11f80-8f24-11eb-8606-e4dbe3f45ffc.png)

![sowhenwillweacknowledgeitsborked](https://user-images.githubusercontent.com/42598271/112735880-f233ae80-8f24-11eb-89f2-b3ebffb6abbc.png)
![becauseitsclearlyborked](https://user-images.githubusercontent.com/42598271/112735852-c87a8780-8f24-11eb-9e70-50c408d3af00.png)

![SCManagerisbroken1](https://user-images.githubusercontent.com/42598271/112735865-da5c2a80-8f24-11eb-9a84-9b5f6ffc8822.png)

![moarborkedSCs](https://user-images.githubusercontent.com/42598271/112735906-2a3af180-8f25-11eb-8eae-6e38c7ae0433.png)
![againimbalanced](https://user-images.githubusercontent.com/42598271/112735907-2b6c1e80-8f25-11eb-9865-025030e4c35d.png)

Steps to replicate:
I queued for SCs with my partner for a couple of hours. Granted, this is not every imbalanced SC I have been in but these are just a few. about 3 of these were all in a row.

**Comment by kekkers119** [comment]
Adding more
![SCManagerisbroken3](https://user-images.githubusercontent.com/42598271/112744921-297c7c80-8f72-11eb-8a3f-74015e2a0a24.png)
![SCManagerisbroken4](https://user-images.githubusercontent.com/42598271/112744922-2bded680-8f72-11eb-848d-976291bdd0f1.png)

So this Scenario we were a 4 man that joined with 12 minutes left. This proves the SC manager is broken and is overfilling the SCs.

**Comment by kekkers119** [comment]
![SCManagerisbroken5](https://user-images.githubusercontent.com/42598271/112744960-adceff80-8f72-11eb-9d7e-01bc327a5a33.png)
![SCManagerisbroken6](https://user-images.githubusercontent.com/42598271/112744962-af98c300-8f72-11eb-9fee-dd50b67f2ce8.png)

The scenario right after. Joined late and overfilled.

**Comment by kekkers119** [comment]
![SCManagerisbroken7](https://user-images.githubusercontent.com/42598271/112795539-a8d38400-9036-11eb-8099-1f9c535f6837.png)
![SCManagerisbroken8](https://user-images.githubusercontent.com/42598271/112795543-aa04b100-9036-11eb-9928-b3104420ae21.png)
We joined late and ovefilled this scenario.

**Comment by kekkers119** [comment]
![SCManagerisbroken9](https://user-images.githubusercontent.com/42598271/112799249-1c2bc480-903c-11eb-91d3-49d2a38bab9f.png)
![SCManagerisbroken10](https://user-images.githubusercontent.com/42598271/112799258-1d5cf180-903c-11eb-940c-d21fa7825373.png)
moar

**Comment by dalen** [comment]
When you get a SC pop you get a chat log notification at the start saying stuff like "Nordenwatch 10 vs 10".

If there's only 6 order & 10 destro in the actual scenario, that means that 4 order players declined the pop, and there were no players in queue to fill those spots with.

But for next patch we have tweaked it to try to keep more players in reserve to be able to fill the spots from quitters, but that might mean slower pops.

**Comment by kekkers119** [comment]
And to be fair sometimes maybe no pop at all would be better than losing because you're literally outnumbered... some may look at this as a challenge however I'm not sure what looks worse to a new player?

A lack of queue pops or constantly imbalanced scenarios? 

This is always my main concern regarding bugs such as this.

**Comment by geezereur** [comment]
Strange I cant even get a sc pop and I played for 4-6 hours in T4 destro.

**Comment by kekkers119** [comment]
Update-
The scenario manager is still overfilling/underfilling SCs.
![SCManagerisbroken11pop](https://user-images.githubusercontent.com/42598271/113593995-1702e280-9605-11eb-93ea-24c2092c373f.png)

![SCManagerisbroken11](https://user-images.githubusercontent.com/42598271/113593812-dc00af00-9604-11eb-8671-1b4648e07ffa.png)

![SCManagerisbroken12](https://user-images.githubusercontent.com/42598271/113593820-de630900-9604-11eb-91b6-c82e225405ae.png)

**Comment by kekkers119** [comment]
![image](https://user-images.githubusercontent.com/42598271/113594836-32bab880-9606-11eb-81b7-7b37853914bd.png)
This SC was semi imbalanced. We still won though.
![image](https://user-images.githubusercontent.com/42598271/113595596-33a01a00-9607-11eb-9bbb-3552d8810dd1.png)
![image](https://user-images.githubusercontent.com/42598271/113595670-516d7f00-9607-11eb-9c78-c09f35a37e61.png)

**Comment by kekkers119** [comment]
![image](https://user-images.githubusercontent.com/42598271/113597357-94c8ed00-9609-11eb-91ce-43d3ab983ea5.png)
![image](https://user-images.githubusercontent.com/42598271/113597396-a4483600-9609-11eb-8eae-63ecb2df5936.png)
This time I did not get an "8vs8" message.

**Comment by kekkers119** [comment]
![image](https://user-images.githubusercontent.com/42598271/113598066-9646e500-960a-11eb-87c9-6c9234bfe4eb.png)
I forgot to SS but the other side had equal numbers- this was a balanced SC.

**Comment by kekkers119** [comment]
This SC was not a balanced.
![image](https://user-images.githubusercontent.com/42598271/113610239-d44c0500-961a-11eb-9eb4-7baebf6fe6c7.png)
![image](https://user-images.githubusercontent.com/42598271/113610326-f2b20080-961a-11eb-923f-375aeccb30aa.png)

**Comment by kekkers119** [comment]
![image](https://user-images.githubusercontent.com/42598271/113611177-293c4b00-961c-11eb-8993-d2858e269dc0.png)
![image](https://user-images.githubusercontent.com/42598271/113611251-44a75600-961c-11eb-87ff-814247f6d22e.png)

Swapped to t2/t3 .... extremely imbalanced SC

**Comment by kekkers119** [comment]
![image](https://user-images.githubusercontent.com/42598271/113613896-d4023880-961f-11eb-9615-104b520427ab.png)
![image](https://user-images.githubusercontent.com/42598271/113613953-dd8ba080-961f-11eb-9931-677b55bf6d4c.png)

**Comment by kekkers119** [comment]
![image](https://user-images.githubusercontent.com/42598271/113614156-1deb1e80-9620-11eb-9db3-35b7f335a9e3.png)
![image](https://user-images.githubusercontent.com/42598271/113614447-84703c80-9620-11eb-9906-21f6336108da.png)
![image](https://user-images.githubusercontent.com/42598271/113614481-8fc36800-9620-11eb-9df4-0600b1beec9b.png)


Okay, this one is absolutely outrageous and IMO proves that I'm right. The scenario manager is not making balanced SCs. It is overfilling one side CLEARLY.

**Comment by kekkers119** [comment]
![image](https://user-images.githubusercontent.com/42598271/113615623-162c7980-9622-11eb-99c9-4503bb7de3c6.png)
![image](https://user-images.githubusercontent.com/42598271/113615692-293f4980-9622-11eb-9cb4-2c612bb2c8e8.png)

**Comment by kekkers119** [comment]
![image](https://user-images.githubusercontent.com/42598271/113619674-488ca580-9627-11eb-9211-742ae1e9f1bf.png)
![image](https://user-images.githubusercontent.com/42598271/113619710-54786780-9627-11eb-86f8-301a87b50100.png)

**Comment by kekkers119** [comment]
New updates after most recent patch 04/07/2021
![image](https://user-images.githubusercontent.com/42598271/113901040-747d6780-979c-11eb-91a3-716ff9565967.png)
![image](https://user-images.githubusercontent.com/42598271/113902087-86133f00-979d-11eb-857f-b78282c3f742.png)
![image](https://user-images.githubusercontent.com/42598271/113902151-97f4e200-979d-11eb-9e8a-a84f8490acd1.png)
Balanced so far.

**Comment by kekkers119** [comment]
![image](https://user-images.githubusercontent.com/42598271/113902327-bfe44580-979d-11eb-930f-6af1a985c707.png)
![image](https://user-images.githubusercontent.com/42598271/113903331-db9c1b80-979e-11eb-849e-1c43b4b14d20.png)
![image](https://user-images.githubusercontent.com/42598271/113903373-e8207400-979e-11eb-9f71-ef7e66b08362.png)
Slightly imbalanced SC

**Comment by albert461** [comment]
the bug is when someone gets a pop, accepts, and nothing happens. it will let someone else into the scenario while the first person can still rejoin usually by relogging

**Comment by lilimx** [comment]
Hey,

is this issue still a thing? According to the patch notes from 07/04/2021:
_- The previous changes to keep players in reserve have been disabled and scenarios will now be filled up with any archetypes available in the queue. So the pops should be faster, but the archetype composition might not be balanced._
