### ISSUE TITLE
/Chairsit clips you thru the floor

### ISSUE THREAD

**Issue by SubsaurusRex** [WarEmu/WarBugs#18710]
when you use /chairsit your character will clip thru the floor and you can move while clipping for most races it will show waist up for small races like dwarf or goblin it will show only show  shoulder to head you can cast or use abilities while clipping thru the floor and for you to not be clipping thru the floor you must log out to character screen to undo the / command.
![image0](https://user-images.githubusercontent.com/76639136/112393814-a76a2a80-8cc9-11eb-8deb-d8b2d6658d24.jpeg)
![image1](https://user-images.githubusercontent.com/76639136/112393835-afc26580-8cc9-11eb-8e25-f3ee23e5e2d3.jpeg)

**Comment by SubsaurusRex** [comment]
my account name is gruzzum

**Comment by MaxHayman** [comment]
This has been removed
