### ISSUE TITLE
Cloak appearance: Magus Sovereign cloak

### ISSUE THREAD

**Issue by Hadzi-user** [WarEmu/WarBugs#18719]
**Expected behavior:**
The owner of magus toon dyed the Sovereign cloak.
So owner and allies must see painted cloak the same.

**Actual behavior:**
The owner of magus toon dyed the Sovereign cloak.
He see dyed cloak, but his allies see default colored cloak.

**Steps to reproduce the problem:**
_You will need rich (33 royal crests) and old (75rr) magus toon to reproduce it._
Paint your Sovereign cloak on your magus and ask an ally friend to guess what color it is.

**Testing Screenshots/Videos/Evidences (always needed):**
Magus owner see this (cool cloak):
![image](https://user-images.githubusercontent.com/69014772/112747668-76d30b00-8fbf-11eb-9e52-2bc562306ba7.png)
I (hes ally) see this :
![image](https://user-images.githubusercontent.com/69014772/112747660-67ec5880-8fbf-11eb-822f-bfb82049fa72.png)

**Comment by lilimx** [comment]
Hey,

thanks for your report. I will add your ticket to a related issue.
#18556
