### ISSUE TITLE
T3 Influence items (Shaman)

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#1871]
T3, Elf, 2ed reward, Ghrond's Greatcloak -  Reduced chance to be PARRIED
T3, Greenskin, 1st reward, both rings - WS
ALL: lack of pure DPS gear, e.g.  T3, Emp, 1st reward, Qhaysh Bitskeepa there's magic crit but more WP then intel, we are no Zealots! :)

**Comment by Evildoor** [comment]
http://www.arsenalofwar.com/armor/Destruction/Ghrond's%20Greatcloak
Does not seems like a shaman item at all...

**Comment by MKorin** [comment]
T3, Emp, 2ed reward, heal crit on both purple helmets

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/5494

**Comment by wargrimnir** [comment]
Greatcloak is a BG item and was fixed. WS was removed from all casters some time ago.
