### ISSUE TITLE
Buffhead broken in RvR. Shows guard on enemy over 1000 feet away

### ISSUE THREAD

**Issue by Mezirah** [WarEmu/WarBugs#18715]
If I tab target enemy players and buffhead shows they are giving or receiving guard they will continue to have the guard icon over their head long past clip range after we part, and I can see what direction the enemy players run in etc, even 100's and 100's of feet away from me. 1000-2000 feet probably.

This is an unfair advantage. One that I've enjoyed, but it should be stopped.

**Comment by bloodmasked** [comment]
My enemy marks work past 100 feet view distance. I also heard target ring addon does it too.

**Comment by lilimx** [comment]
Hey,

thanks for your ticket, but this is no bug. If you want to discuss this, pleas use the Suggestion & Feedback Forum: https://www.returnofreckoning.com/forum/viewforum.php?f=15
