### ISSUE TITLE
[T4 Dragon's Blessing] Bones disappear when right clicked

### ISSUE THREAD

**Issue by karatak** [WarEmu/WarBugs#18711]
Hello,

There is a bug on T4 Dwarves QP Dragon's Blessing. At step 1 in this QP, you're supposed to destroy dragon bones. You can left click and attack them as you should do but if you right click on them, they simply disappear and doesn't count for the QP ! The QP works however. It's just a bit annoying to wait for them to respawn when you misclick.

Thank you guys, you're awesome.

**Comment by Lheana** [comment]
This has been fixed with the patch of 31/03/2021.
