### ISSUE TITLE
[SH] Summoning pet while in Squig Armor cancels Squig Armor

### ISSUE THREAD

**Issue by zulnam** [WarEmu/WarBugs#18720]
STR:
1. While playing a Squig Herder, activate Squig Armor (SA from here on).
2. Summon any of the available pets.

EXP:
Pet is summoned while in SA without breaking SA.

ACT:
Summoning pet cancels SA, with 5 second cooldown.

**Comment by Tohrgrimm** [comment]
Problem exists way too long. Look at ticket #18439

**Comment by lilimx** [comment]
Hey,

as Toghrimm wrote, it's already reportet. Thank you for your ticket.
- closed
