### ISSUE TITLE
Gryphons Lash affected by block rating?

### ISSUE THREAD

**Issue by YourDarling** [WarEmu/WarBugs#18725]
![image](https://user-images.githubusercontent.com/76393369/112864049-8427ec80-90c8-11eb-804d-67fd79c24cee.png)
gryphons lash after bypassing enemies block chance and parry(as intended) seems to be affected by block rate. Black Ork channel's "cant hit me" while i used that skill or "hold the line" they looks similar.
![image](https://user-images.githubusercontent.com/76393369/112864552-f4cf0900-90c8-11eb-985c-9ef731d119ee.png)

**Comment by bloodmasked** [comment]
"blocked your attack" is an auto-attack being blocked, not the ability.

**Comment by YourDarling** [comment]
![image](https://user-images.githubusercontent.com/76393369/112950185-107af380-914b-11eb-9c54-8cb4f9be97c0.png)
its not a block rate. its amount of blocked dmg. instead of dealing normal amount of dmg that skill deals 2-5 dmg after go trough the parry\block.

**Comment by bloodmasked** [comment]
parry and block does not affect dmg

**Comment by YourDarling** [comment]
> ![image](https://user-images.githubusercontent.com/76393369/112950185-107af380-914b-11eb-9c54-8cb4f9be97c0.png)
> its not a block rate. its amount of blocked dmg. instead of dealing normal amount of dmg that skill deals 2-5 dmg after go trough the parry\block.

what does it have to do with parry block? my problem is that skill deals 2-5 dmg while enemy using shield block skill

**Comment by YourDarling** [comment]
> parry and block does not affect dmg

what does it have to do with parry block? my problem is that skill deals 2-5 dmg while enemy using shield block skill

**Comment by bloodmasked** [comment]
its working as intended

**Comment by YourDarling** [comment]
> its working as intended

explain pls and give pr
