### ISSUE TITLE
Mobs not respawning.

### ISSUE THREAD

**Issue by Klod91** [WarEmu/WarBugs#18728]
Mobs don't respawn after the patch. Not just in this particular place. In general.

![Dwoff_046](https://user-images.githubusercontent.com/77681824/113145525-cff4a600-922e-11eb-83c3-a9d5f2a140d0.jpg)

**Comment by PieterDemey** [comment]
Can confirm, same issue here.

![Talabecland_servitudeQuest](https://user-images.githubusercontent.com/40518003/113147957-9c674b00-9231-11eb-9f11-6166e47a29ea.png)

**Comment by Klod91** [comment]
After more testing it seems that mobs in PQs do respawn. But not in the open world.

**Comment by MaxHayman** [comment]
Fixed

**Comment by Klod91** [comment]
Bats haven't respawned since I killed them right after the patch (before any hotfixes).

![Klodrek_000](https://user-images.githubusercontent.com/77681824/113216502-c09c4980-927c-11eb-9c4d-11b9d54d9956.jpg)
