### ISSUE TITLE
Welcome Back: Sacrifice NPC stuck below the earth

### ISSUE THREAD

**Issue by Viglundur** [WarEmu/WarBugs#18724]
N.B. As I am new to this forum as well as the reporting of bugs, this post might represent n issue already dealt with/ the devs have already been made aware of. While I scoured the site for this specific problem and couldn't find it, this does naturally not mean that it is not already known. So, in case of this issue being already known, consider this report void.

**Expected behavior and actual behavior:**
The NPC Korselbaen Purelight, found in Elf Order WC Tier 1 for the quest Welcome Back: Sacrifice is not at his place. Rather he stands some 50m away from his location indicated on the map. There, he is below the earth and inaccessible to me. Only the quest marker can be seen above the ground.

**Steps to reproduce the problem:**
As I am not aware of what actually caused this to happen I cannot even fathom steps to reproduce this. Maybe this all can be fixed with a server restart?

**Testing Screenshots/Videos/Evidences (always needed):**

![Viglundur_001](https://user-images.githubusercontent.com/81573487/112849819-f385e800-9098-11eb-84a9-01aa1b6dd281.jpg)
![Viglundur_002](https://user-images.githubusercontent.com/81573487/112849821-f41e7e80-9098-11eb-851d-1baa48fc38a0.jpg)
![Viglundur_003](https://user-images.githubusercontent.com/81573487/112849822-f41e7e80-9098-11eb-8a19-9add423d34c2.jpg)

**Comment by MaxHayman** [comment]
![image](https://user-images.githubusercontent.com/1018809/114069337-caced100-9896-11eb-942d-2cb4cabf32e9.png)
Seems at least fixed with a restart. Might be something to do with pathing so ive labelled the ticket for future reference
