### ISSUE TITLE
Slayer's Demise Wounded Slayers attack friendly targets

### ISSUE THREAD

**Issue by gablorquet** [WarEmu/WarBugs#18723]
**Expected behavior and actual behavior:**
When using PBAOE (like Scorched Earth) on top of the trio of Wounded Slayers, the NPC attack you despite staying friendly. 

**Steps to reproduce the problem:**
Go to Troll Country's Slayer's Demise PQ
Using a PBAOE like scorched earth or fire cage seem to do it

**Testing Screenshots/Videos/Evidences (always needed):**
![WAR-64 2021-03-28 20-00-16](https://user-images.githubusercontent.com/7695457/112772697-419add00-9000-11eb-9940-c7b96a112fe0.png)

**Comment by lilimx** [comment]
Hey,

I've did some tests. Looks like it is fixed now.
