### ISSUE TITLE
[Highpass Cementary] Lids to capture BOs missing

### ISSUE THREAD

**Issue by Idrinth** [WarEmu/WarBugs#18733]
**Expected behavior and actual behavior:** The graves should be closed with an interactable lid, that allows capping the BOs. This is currently missing.

**Steps to reproduce the problem:** Play the Highpass Cementary and walk to either BO.

**Testing Screenshots/Videos/Evidences (always needed):**
![Idrynth_014](https://user-images.githubusercontent.com/7874631/113206264-88423e80-926f-11eb-8f56-aefd3817c258.jpg)

**Comment by MaxHayman** [comment]
Fixed in hotfix
