### ISSUE TITLE
Rampage bypasses Morale 1 Confusing Movements

### ISSUE THREAD

**Issue by Undrsiege** [WarEmu/WarBugs#18730]
Slayer Skill "Rampage" bypasses morale 1 "Confusing Movements"...

A morale is stronger than a common ability and the Morale 1 should be stronger....

**Comment by bloodmasked** [comment]
Its not a bug because parry is calculated after the attacker's strikethrough is considered. If you have 100% parry and the attacker ignores 100% of your parry, you have 0% parry.

**Comment by Undrsiege** [comment]
> Its not a bug because parry is calculated after the attacker's strikethrough is considered. If you have 100% parry and the attacker ignores 100% of your parry, you have 0% parry.


I understand your point but the fact is confusing movements % of bonus parry is set incorrectly..  For instance Blackguards "Elite Training" gives 800% parry so as to eliminate this issue....

![Screenshot_101](https://user-images.githubusercontent.com/422949/113226807-b10a0a00-9256-11eb-8d2e-6c8d5e035e0c.jpg)

**Comment by colintgallagher** [comment]
Confusing Movements add 500% parry and dodge. But it doesn't matter because any ability that is Undefendable will bypass it all. Rampage makes the slayer's attacks Undefendable.

**Comment by bloodmasked** [comment]
Are you saying that elite training defends from rampage?

**Comment by saschaki** [comment]
There was already a ticket about this and it got closed.
You may like it or not but it is working as intended.
[https://github.com/WarEmu/WarBugs/issues/8603](url)

**Comment by lilimx** [comment]
Hey,

please add a proof that rampage bypasses M1 (that wasn't confirmed in #8603 )
