### ISSUE TITLE
Critical: Battle Objectives on Forts cannot be capped.

### ISSUE THREAD

**Issue by termofor** [WarEmu/WarBugs#18738]
You cannot capture Objectives on Fort Siege.

**Expected behavior and actual behavior:**

You can cap BO while engaged in Fort Siege

**Steps to reproduce the problem:**

Try to capture BO.

**Testing Screenshots/Videos/Evidences (always needed):**
<
![Grimnirson_011](https://user-images.githubusercontent.com/80748880/113260646-cfabe780-92ce-11eb-8106-6b409ab7e15f.jpg)
>

**Comment by MaxHayman** [comment]
Should be fixed with hotfix please reopen if any further issues
