### ISSUE TITLE
Where's Da Whatnot? Quest NPC not spawning

### ISSUE THREAD

**Issue by Aedros** [WarEmu/WarBugs#18737]
**Expected behavior and actual behavior:**

Expected behavior is that the quest NPC spawn and be kill able. The NPC is not available is the actual behavior.

**Steps to reproduce the problem:**
1. Accept the quest
2. Journey to the marked area on the map
3. Look for Fiznik Fizzlefang NPC

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
This should have been fixed with the hotfix. Comment if it still happens.
