### ISSUE TITLE
Raider's Haven PQ Stage One Tent's Bugged

### ISSUE THREAD

**Issue by Aedros** [WarEmu/WarBugs#18736]
**Expected behavior and actual behavior:**

Expected behavior is that after clicking on each of the oil lamps, the Destroy Outpost Tents counter will advance; currently it does not.

**Steps to reproduce the problem:**
1. Approach raider tent in PQ area while stage one is active
2. Click on Oil Lamp object in front of tent

**Testing Screenshots/Videos/Evidences (always needed):**

![Bonesplitta_000](https://user-images.githubusercontent.com/81740142/113258299-a3697a00-9280-11eb-8289-8d39e27498a3.jpg)

**Comment by Lheana** [comment]
You need to destroy them i.e. attacking them.
