### ISSUE TITLE
Some mobs that died after the last patch haven't respawned.

### ISSUE THREAD

**Issue by Klod91** [WarEmu/WarBugs#18739]
While the issue with mobs not respawning seems to have been fixed, it looks like some are still not respawning.
I killed the Bats in this spot right when the original patch came out, before any hotfixes. They still haven't respawned.
It's possible that they respawned after the hotfix and then someone killed them again, but at this moment they are dead.

![Klodrek_000](https://user-images.githubusercontent.com/77681824/113273788-494ad200-92dd-11eb-8bf7-b0c8359d9389.jpg)

**Comment by ShanellRoR** [comment]
![Baliff_010](https://user-images.githubusercontent.com/17355822/113276486-8b2d4580-92e8-11eb-9053-cca2db92aa72.jpg)
Same for this cave in The Blighted Isle 36k 20k

**Comment by Klod91** [comment]
As well as dummies in Altdorf and Bats in Caledor (as you can see from chat).

![Dwoff_047](https://user-images.githubusercontent.com/77681824/113276672-5b7a3f80-92e0-11eb-93a9-4e6683b513ac.jpg)

**Comment by ShanellRoR** [comment]
![Baliff_011](https://user-images.githubusercontent.com/17355822/113277675-a6e51b80-92e9-11eb-932a-d49e2aedb0d9.jpg)
Cold ones in the Blighted Isle  48k 18k

**Comment by MaxHayman** [comment]
Should be fixed in this restart please reopen if not
