### ISSUE TITLE
Sorc mechanic stacking - 200%+ critical damage

### ISSUE THREAD

**Issue by Frozenover1** [WarEmu/WarBugs#18744]
A few days ago when I was solo roaming on my sorc I suddenly noticed my damage to significantly increase after I died at one point. I did the .getstats command, and found my critical damage and critical hit chance to be 80% and 25% higher, respectively, than expected. This corresponds to the bonuses obtained from having 71-90 Dark Magic. However, relogging solved this issue, and my base critical damage went back to normalcy (15% from 4-piece sov-set).

As I was roaming Praag on my sorc earlier today I again noticed that I suddenly dealt a significantly increased amount of damage after I died. My Word of Pain critically hit for 3600 and I don't think I've seen anything like this before. See attached screenshot. As I do the .getstats command, I indeed find my critical damage to be 115 at 0 dark magic, as well as having a critical hit chance bonus of 35%. This stacks with building up to 100 Dark Magic to a critical damage bonus of 215% and critical hit chance bonus of 70%. I did not take a screenshot of this, but the 3600 WoP hit serves as enough evidence for this I hope. Edit: not warcamp-buffed as it happened in the location I'm standing at in Praag and same numbers on several different targets. 

I am not too sure how this issue is triggered, but as I have pointed out, it seems to be related to something happening when I die/respawn. I have thought of it possibly being related to another bug, which I wish to report in this same post, although the bug in question only seemed to break the mechanic for me once and has not reoccured with further in-game testing. This is therefore unlikely to be the core of the issue. However, when Hand of Ruin is cast as the final ability before dying to a backlash as the ability is cast, the effect of HoR continues from the dead sorc for the full 6-second duration. I have tried other things in-game to see what may trigger the issue, such as war-reporting at 100 dark magic, etc., but I have not found out the exact cause of the problem. 

However, when this effect triggers, this can be game-breaking, and may not always be easily spotted for when "only" 20% extra critical damage is stacked together with the corresponding critical hit chance bonus. However, the backlash mechanic does not seem to break, and still works correctly while the crit chance and damage bonuses are broken. Despite not being able to point to what exactly is breaking the mechanic yet, I wish to bring attention to the issue due to the severity of the bug. 

I am again not too sure how this may be resolved as I am not a programmer but it might hopefully be helpful to know that relogging works to reset these bonuses. Until fixed, a bandaid solution might be suggested, such as if the sorc critical damage bonus ever exceeds 127 (max from onslaught 4-piece + 4-piece sov at 100 DM), this should force the sorc to relog. 

<img width="1440" alt="Sorc mechanic ev1" src="https://user-images.githubusercontent.com/81784258/113367025-3d9df080-935b-11eb-87c2-9164024d6188.png">
<img width="1440" alt="Sorc mechanic ev2" src="https://user-images.githubusercontent.com/81784258/113367052-4d1d3980-935b-11eb-846b-0e5e12fe6895.png">

**Comment by Frozenover1** [comment]
As also reported in #19239 , this can occur on the BW too. On doing the .getstats command I find my BW to have 200% CriticalDamage and a bonus 70% CriticalHitRate at full mechanic when the bug has been triggered. Similar to Sorc.

I also believe I now know what triggers the bug. When a sorc/bw die at the very same time as they backlash, their mechanic is "saved" from the state when they died. So If I backlash at 80 Dark Magic, 80% CriticalDamage is saved, stacking with a further 100% when building up the mechanic anew. This also explains why I have noticed 100% or 80% CriticalDamage stacking more often than 20% CriticalDamage, because backlash is much less common at lower Dark Magic. 

This is very difficult to test out to figure out if this is the actual reason. But this happens to me way more when I am solo roaming, am in a fight at 100 Dark Magic, and I get zerged. Being peppered down as I suffer a backlash. It has also happened after dying in city. Relogging still solves solves this issue, but if you're in a city it can be hard to notice if it stacks at a "lower level". Relogging in a city is also not very convenient. To test, or possibly solve this issue, maybe implement that Sorc/BW should no longer be able to kill themselves from backlash, only letting backlash trigger if they have 750+ hp?

**Comment by lilimx** [comment]
Fixed around the Patch from 9/03/2022
