### ISSUE TITLE
Eastern eggs not clickable even after killing Matriarch

### ISSUE THREAD

**Issue by Issard** [WarEmu/WarBugs#18749]
after killing the Eastern Wyvern Matriarch the eggs are not clickable (next to March of Madness Fangbreaka keep)

(killed him 3 times, the barier does not disappear either )
![Issardx_043](https://user-images.githubusercontent.com/5678860/113424568-a8d5da00-93d0-11eb-826d-0dc463b4ee3e.jpg)
![Issardx_042](https://user-images.githubusercontent.com/5678860/113424569-aa070700-93d0-11eb-813f-4233c559477b.jpg)

**Comment by Senthoi** [comment]
I'm finding that I can't interact with any eggs at all right now. There's no Matriarch anywhere nearby. I've run the length of the zone and haven't seen one. This is in Kadrin Valley.
![image](https://user-images.githubusercontent.com/22262165/113475527-2c91d400-946e-11eb-8ff1-5766fae485fe.png)
![WAR-64 2021-04-03 11-17-41](https://user-images.githubusercontent.com/22262165/113475536-3ddae080-946e-11eb-9fbf-c98355d5dd59.png)

**Comment by GamesBondd** [comment]
Fixed
