### ISSUE TITLE
Guild banner aka standard cannot be picked up after its placed on ground

### ISSUE THREAD

**Issue by bloodmasked** [WarEmu/WarBugs#18745]
It gives an error saying the owner is too far away to pick it up, even though I am the owner of the banner/standard.

**Comment by Syzako** [comment]
Confirm. I, as the owner, cannot take the standard.
![image](https://user-images.githubusercontent.com/39750677/113403525-85bc2200-93f2-11eb-8b62-327dca1d457c.png)
![image](https://user-images.githubusercontent.com/39750677/113403539-89e83f80-93f2-11eb-8b61-36fd8ff4638e.png)

**Comment by DarkFaenix** [comment]
Confirmed too.

This morning, I planted my banner in a keep and couldn't take it back.

This evening, I tested it in the Viper's Pit. I couldn't take it back again and asked someone to pick it up; same error. Once I left the Viper's Pit, he's been able to return my banner with success.
