### ISSUE TITLE
WH: Sigil of Sigmar removes Sanctified Oil buff

### ISSUE THREAD

**Issue by Kythas01** [WarEmu/WarBugs#18743]
**Expected behavior and actual behavior:**
Witch Hunter Ability Issue:
- Sanctified Oil gives a 50% speed buff for 7 seconds.
- Sigil of Sigmar removes all roots and snares.

Bug: If you use Sigil of Sigmar after using Sanctified Oil, it will remove the 50% speed buff

**Steps to reproduce the problem:**
Use Sanctified Oil. Use Sigil of Sigmar as soon as you come out of Invis (2 secs). Note that the speed buff with 5s remaining is removed.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by stonetradex** [comment]
It also happen with Witch Elf Elix of shadows / flee-footed.

**Comment by mistmore** [comment]
This is a old problem.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
According to Grunbag #15606 it works as intended.
