### ISSUE TITLE
Return Fire quest bug

### ISSUE THREAD

**Issue by Hefcom** [WarEmu/WarBugs#18748]
So there is a problem about this quest - after you destroy chaos cannons nothing happens. You can't complete a quest, it still shows you that you need to destroy two cannons.

**Comment by Lheana** [comment]
It works for me
![Lheana_235](https://user-images.githubusercontent.com/11537611/113475927-75e72100-9478-11eb-8bd9-6c19dfa8ea7d.jpg)

**Comment by Rodulv** [comment]
The Return FIre quest is still bugged

**Comment by Lheana** [comment]
There is another ticket opened for this issue.
