### ISSUE TITLE
NPCs in city

### ISSUE THREAD

**Issue by Quathan** [WarEmu/WarBugs#18740]
Cannoneers in IC is attackable by Order faction usually they are friendly
Also lord was only attackable by dots after defeating all destro champs.

![image](https://user-images.githubusercontent.com/81371632/113275922-9465e480-92df-11eb-8b72-8e218e8e5b08.png)

**Comment by madregit** [comment]
happening in destro as well

**Comment by MaxHayman** [comment]
Fixed in todays hotfix.
