### ISSUE TITLE
All attacks blocked by Keep Lord

### ISSUE THREAD

**Issue by Greigals** [WarEmu/WarBugs#18750]
While attacking the enemy Keep lord with my Black Ork, all of my attacks are always blocked. 

![Untitled](https://user-images.githubusercontent.com/81819699/113439061-b2b40900-93e1-11eb-9685-65595676b5c8.png)

**Comment by Naelar** [comment]
This happened to me last night, as well.  Some were saying it was because of the toon's lvl (22).

**Comment by Lheana** [comment]
This should have been fixed with the hotfix.
