### ISSUE TITLE
Quest in Marshes Of Madness

### ISSUE THREAD

**Issue by NoTutorialneeded** [WarEmu/WarBugs#18756]
I tried doing the quest Dead Rock in Marshes of Madness and when it completed it subtracted almost a whole level worth of exp from me.
-->

**Expected behavior and actual behavior:**
I expected to gain exp, not lose it.

**Steps to reproduce the problem:**
no clue, do the quest i guess?
![Olgana_000](https://user-images.githubusercontent.com/80071793/113442714-dcc0f780-93f0-11eb-8908-0f9c8d9b118d.jpg)
![Olgana_001](https://user-images.githubusercontent.com/80071793/113442715-ddf22480-93f0-11eb-89a1-5504783a1f77.jpg)

**Comment by Lheana** [comment]
Did you really lose it or was it just the message?

**Comment by NoTutorialneeded** [comment]
Hello there, I did indead lose the experience.... It put me down from 95% of a level down to 6% without actually leveling me up.... Hope this helps.
________________________________
Fra: Lheana ***@***.***>
Sendt: lørdag 3. april 2021 12:15
Til: WarEmu/WarBugs ***@***.***>
Kopi: NoTutorialneeded ***@***.***>; Author ***@***.***>
Emne: Re: [WarEmu/WarBugs] Quest in Marshes Of Madness (#18756)


Did you really lose it or was it just the message?

**Comment by Rubyeclipse-war** [comment]
Hi there @NoTutorialneeded - I've tried to recreate this but the quests seem to be granting EXP just fine now. 

I believe this quest chain works properly, so for now I'll put back on the 2-week window in case there's anything else to add from your side. If not, we should be good! (And if anyone else comes across a similar issue with this quest chain someday, please let us know.)

**Comment by lilimx** [comment]
Hey,

So I guess it's fixed for now.
