### ISSUE TITLE
[PQ] 'Ritual of the Heavens' is bugged

### ISSUE THREAD

**Issue by Andrey-Bulatov** [WarEmu/WarBugs#18759]
Order PQ 'Rutial of the Heavens' (Isle of the Dead) is bugged. Celestial Corrupters on stage III are not attackable and ignore player as well. That's why stage III cannot be completed. Dragomas (another goal of the stage) is good.

**Comment by Lheana** [comment]
This has been fixed with the patch of 07/04/2021.
