### ISSUE TITLE
Buff of Lasting Potion of Power goes away when summoning White Lion pet

### ISSUE THREAD

**Issue by Numerrex** [WarEmu/WarBugs#18755]
https://user-images.githubusercontent.com/81825444/113442341-2826d600-93f0-11eb-8c6a-442ecee2c345.mp4

Posted by UltimateLoL

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
Please check the kind of bug.
Is it a visible bug or does the potion really get lost.
do test like /rel and .getstats

**Comment by lilimx** [comment]
Hey,

im going to close this ticket now due to no feedback.
