### ISSUE TITLE
WL-Buff Pack Hunting goes away when summoning pet

### ISSUE THREAD

**Issue by Numerrex** [WarEmu/WarBugs#18757]
https://user-images.githubusercontent.com/81825444/113443115-9d46db00-93f1-11eb-9776-192ad71a6b67.mp4

Posted by UltimateLoL

**Comment by Farlopa** [comment]
if u click back on the buff u still getting the 50%atack speed even if u dont see the icon

**Comment by Azeyune** [comment]
nope https://github.com/WarEmu/WarBugs/issues/18729

**Comment by lilimx** [comment]
duplicate.
