### ISSUE TITLE
Buffs Stacking From Runepriest

### ISSUE THREAD

**Issue by Candy-WH** [WarEmu/WarBugs#1875]
Server version 1.4.8, Build 573, playing on a Runepriest, I cast Oath Rune of Iron, and another rune priest in the scenario cast Oath Rune of Warding.  As seen in the screenshot below, they stacked, which I don't believe they did during live if not mistaken?  A friend I was grouped with (on an Ironbreaker), experienced the same findings.

http://i377.photobucket.com/albums/oo214/candey1/668b9519-2ab0-4ef4-b613-9a9060976e5c_zpsdnsu0byo.png

**Comment by Morksezstop** [comment]
if you got 3 rune priest at your group you could get all the 3 different buffs from them. Only same buffs casted on you didnt stack. That was on live and that is how is suppose to be

**Comment by Evildoor** [comment]
@Morksezstop is correct. And so is tooltip for Oath Rune of Iron.
