### ISSUE TITLE
Epic Quest Control- Stuck step 10

### ISSUE THREAD

**Issue by Alfinnete** [WarEmu/WarBugs#18764]
After completing step 9. 
- Click on the Tear of Isha inside the Cave of Whispers (entrance at 63k/36k) to loot an item of the same name. Accept the follow up.

Start in step 10.
- Kill Falathin Soulbreaker who spawns.

**- Then speak to Aerylia Windstrider at the Chapter 12 to the west.**
Talk to Aerylia dont work

![image](https://user-images.githubusercontent.com/19777804/113479958-3284b680-9468-11eb-95c1-27f5d94116e1.png)

**Comment by Lheana** [comment]
Interact with the Tear of Isha, that's the quest finisher.

**Comment by Alfinnete** [comment]
No, its not work! =)

https://user-images.githubusercontent.com/19777804/113487982-996a9580-9491-11eb-8498-ba6f379b4378.mp4

**Comment by Alfinnete** [comment]
> Interact with the Tear of Isha, that's the quest finisher.


https://user-images.githubusercontent.com/19777804/113488016-c6b74380-9491-11eb-8020-f2b2d7e32560.mp4

No, its not work =)

**Comment by Lheana** [comment]
I mean the object, not the item in your inventory.

**Comment by Alfinnete** [comment]
> I mean the object, not the item in your inventory.

I did the whole process as it should be done, including the quest is as a prontra missing only talking to the NPC, but it does not activate the dialogue to continue the quest.

I clicked on the object when it was needed, it give me the shard and there is no other interaction after that, just talk to the NPC that is broken.

**Comment by Alfinnete** [comment]
I had to redo the quest 2 times to complete...

**Comment by Alfinnete** [comment]
And now this new problem:

Step 13
Travel to Saphery.

Use the item 'Tear of Isha' on NPCs:

- Gorgluk Foulbreath at 56k/8.2k

**- Ulvarr Scorchspell at 55.5k/33.2k <- Dont work**

https://user-images.githubusercontent.com/19777804/113494480-ed3fa380-94be-11eb-8a9a-46bf04b4f0ab.mp4

**Comment by Alfinnete** [comment]
And now this new problem:

Step 13
Travel to Saphery.

Use the item 'Tear of Isha' on NPCs:

Gorgluk Foulbreath at 56k/8.2k
And now this new problem:

Step 13
Travel to Saphery.

Use the item 'Tear of Isha' on NPCs:

Gorgluk Foulbreath at 56k/8.2k
**- Ulvarr Scorchspell at 55.5k/33.2k <- Dont work**


https://user-images.githubusercontent.com/19777804/113494496-2546e680-94bf-11eb-981a-8e64a99006a3.mp4

**Comment by Lheana** [comment]
Just tested on live, everything seems fine with this NPC now.
