### ISSUE TITLE
city King blocks and other bugs from 31/03/2021 patch

### ISSUE THREAD

**Issue by BomblingTV** [WarEmu/WarBugs#18760]
Quite a few broken things since last patch, some are minor, some quite big.

Citysiege
1) King's in stage3 are only able to be damaged by Damage Over Time(DoT) classified abilities. Such as 15sec dots and Granted ability dots from Zealot/runie party buff/ability. Morale damage is blocked, DD is blocked 100%. Abilities such as Rampage and other strikethrough boosting abilities/tactics is not working on Kings during stage3.
1.1) Some lowerlevel players in orvr are reporting that same bug happends to them and they cant damage keep-lords when they are sub 40. Unsure about any more details.
1.2) Gobba gits for destro in altdorf stage1 were attackable by destro-players, when they were supposed to be friendly.
Some whitelion pets have had orange (neutral) names to Order players.

scenario
2) Scenario wait time is insanely long atm. Players are reporting spending up to 2 hours in queue without seeing a pop (reported mostly from damagedealers soloQing)

event
3) Egg event in orvr can get a bit spammy, maybe this is a result of some of the eggs bugging out and you cant click them but get a message like "you cant hatch this egg as long as the matriarch is still alive" but no hero mob is nearby. So the message in center of your screen and in chatbox can get quite spammy from these bugged eggs.
3.1) The matriarchs are spawning at a chance when hatching the eggs in orvr/pve correctly, but when killed they instantly despawn and dont grant any item drops.

cosmetic
4) Cloak apperence is still bugged and other players cant see your chosen cloak-apperence. Despite having turn the option on ingame under Server settings. This is a month old report and theres already a topic, but since we have two clock skins from april events i figured id mention it here aswel.

**Comment by Lheana** [comment]
One issue per report please. I close the ticket, open one ticket per issue after verifying it has not been reported yet.
