### ISSUE TITLE
[Quest] 'The Final Assault' with hidden NPC

### ISSUE THREAD

**Issue by Andrey-Bulatov** [WarEmu/WarBugs#18768]
Order quest 'The Final Assault' (Elf Ch 22) requires to speak with 3 shadow warriors in ch 22, according to quest description. One of them, Fileron, was found inside tower 12k, 54k approx. Player cannot reach him - look at screenshot.

![Ainudallire_006](https://user-images.githubusercontent.com/20935691/113493741-ddd64f80-94ea-11eb-89b2-9df07fe340f2.jpg)

**Comment by Lheana** [comment]
He is back to his original place.
I close the ticket as it is related to a more general issue already reported.
