### ISSUE TITLE
[Citysiege] Lobbagits neutral and attackable

### ISSUE THREAD

**Issue by BomblingTV** [WarEmu/WarBugs#18778]
Lobbagits spawning in Citysiges in both Altdorf and IC (seen it from both destro and order pov) during stage1 running from Outcrop Battleobjective towards the gate, and in altdorf from North docks to the gate.

They are neutral with orange colored nametags and attackers who are supposed to be friendly with the gits can attack them, cc them, snare them and kill them. 

This leads to a big advantage for the defending realm who can stack up on top of the gits, cleave them down while the attackers cant cleave or aoe, as it will hurt the lobba gits.

This issue was seen since last patchday, and still persist after the hotfix from easter weekend.

**Comment by MaxHayman** [comment]
Fixed in todays hotfix.
