### ISSUE TITLE
URGENT Dragon Gun WH /On Your Knees WE  NOT WORKING

### ISSUE THREAD

**Issue by mistmore** [WarEmu/WarBugs#18776]
I play with Witch Elf and Witch Hunter Dragon Gun and On Your Knees not removing moral of enemys.
Tested. Angelica

**Comment by stonetradex** [comment]
Confirmed!!! 
[https://www.twitch.tv/videos/973893356?t=02h06m41s](url)

On that match been using OYK the whole time on zarbix. Not removing any morale!! 
Tested also with both my WE and WH with opponents form opposite faction and tested in arena. 

Tested.. Krima

**Comment by CrimsonFenris** [comment]
That explains a lot indeed, why I couldnt see any difference when using Dragon Gun... 
Morale pump part is nonetheless working (at least on the DG).

**Comment by dalen** [comment]
Fixed in hotfix today.

It was actually draining enemy morale on the AoE part, but not from the main target. Now it will drain from main target as well.
