### ISSUE TITLE
[Black Crag Keep] Players randomly falling through the ground

### ISSUE THREAD

**Issue by CornerbackAC** [WarEmu/WarBugs#18773]
**Expected behavior and actual behavior:**
Expected: you can normally play Black Crag Keep
Actual: sometimes one or more players keep falling through the ground, even after respawn.

**Steps to reproduce the problem:**
No idea tbh. Seems to be random. If it happens to you, it keeps happening for the duration of the SC

**Testing Screenshots/Videos/Evidences (always needed):**
![Snobbi_031](https://user-images.githubusercontent.com/11341460/113524899-0b3a0080-95b2-11eb-8279-d8fa8e31e162.jpg)

**Comment by MaxHayman** [comment]
Should be fixed refer to #18644
