### ISSUE TITLE
Renown Gear Merchant offers an Axe to Magus Characters

### ISSUE THREAD

**Issue by Delegator2** [WarEmu/WarBugs#18771]
**Expected behavior and actual behavior:**

Playing a Magus, if I go to the lowest level renown gear merchant, he offers me a Chaos Axe (2 varieties) in addition to two types of staff. While the item doesn't show a restriction in this window, it cannot actually be equipped by this class. So, there is something wrong with the item list, and potentially with the actual Chaos Axe items.

**Steps to reproduce the problem:**

Go to renown gear merchant in the Inevitable City or any T1 Warcap for Destro
![Screen Shot 2021-04-04 at 10 06 42 AM](https://user-images.githubusercontent.com/77587188/113511401-9329f700-952d-11eb-8f3a-a53bcc5dafbf.png)

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

I've checked it and it looks like it was fixed.
