### ISSUE TITLE
Possible bug with wyvern eggs

### ISSUE THREAD

**Issue by Naelar** [WarEmu/WarBugs#18770]
I have noticed that a number of the eggs are not able to be opened because of the Matriarch being near.  Quite a few of these are close to a warcamp.  Is it possible that the Flight Master and/or Keep FM are registering as Matriarchs, and preventing these eggs from being opened?

Edit: tested this on my WH in the same spot. He could not open it, either.  Do not have SS of this.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**
See screenshots below.  Saw this in Marshes of Madness and in Thunder Mountain.  Got a pair of SS for MoM.  One showing the egg could not be opened, the other showing where I was on the map.

**Testing Screenshots/Videos/Evidences (always needed):**
![2021-04-04](https://user-images.githubusercontent.com/61371494/113506418-6ca69480-950a-11eb-9aad-3cf49dfc2264.png)
![2021-04-04 (1)](https://user-images.githubusercontent.com/61371494/113506423-729c7580-950a-11eb-86a3-d74c4f98fa53.png)

**Comment by lilimx** [comment]
Hey,

it's fixed now. Will add it to the related ticket.

**Comment by lilimx** [comment]
related/dublicate #18749
