### ISSUE TITLE
Altdorf - Quest "Spotting Trouble" Unable to progress quest by right-clicking Floating Corpse

### ISSUE THREAD

**Issue by CWNichols01** [WarEmu/WarBugs#18784]
In the Altdorf quest "Spotting Trouble", the objective is to "Search the floating corpse at the edge of the docks." The floating corpse is there, but right clicking on it does not progress the quest.

**Comment by Pixelated-Dom** [comment]
Can confirm this one, was trying to figure out what I was doing wrong with this last night, nothing seems to trigger the correct interaction

**Comment by Pille91** [comment]
Can confirm it's still bugged. Tried for 30 minutes, same with an experienced player.

**Comment by valkeera** [comment]
Have the same problem, I'm trying to get as close as I can but the next step of the quest doesn't unlock... this used to work with my previous characters without issue.

![Ainuril_001](https://user-images.githubusercontent.com/58527250/121800833-5b79b280-cc34-11eb-91db-b6b05e79f59c.jpg)

**Comment by alfaldr** [comment]
_"Spotting Trouble" quest is still bugged. After about 30 minutes of trying, I gave up._

**Comment by Forzare** [comment]
Still bugged as of today, too. Nothing happens when you click on the corpse in the water.

**Comment by illutian** [comment]
Not sure if it's possible...but until a permanent fix can be made. Why not just change where the server spawns the body.

((At least, I assume that much is possible; changing spawn coordinates. Not sure how much is locked behind unmodifiable client code.))

**Comment by illutian** [comment]
Fixed as of 7/21/2022

Corpse has been moved to be 'with in reach' when on the ramp going down the dock near the Risen Traders (hostile mobs)

**Comment by Svarty1** [comment]
I have the quest and I completed the step but I have no idea where to hand it in. There is no map marker or hint indicating what to do after completing the step. It's as if it's half-completing, i.e. ticking the tome entry but not the progression in the game.
![image](https://user-images.githubusercontent.com/113995896/227749059-483f2555-0224-4f10-ae55-646b6d88a31e.png)

**Comment by Rubyeclipse-war** [comment]
Just tested - this quest completes while you are within range of the corpse. Please try clicking on the corpse again, and if that doesn't work, abandon and re-take the quest, and it should give you a finishing window when you interact with the corpse.

**Comment by lilimx** [comment]
What do you confirm? Did you all the step that Rubi said?

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
