### ISSUE TITLE
Alliance Formation Bugged

### ISSUE THREAD

**Issue by Cesi-123** [WarEmu/WarBugs#18783]
I have made several attempts on Order to create an alliance with another guild.  Both guilds are level six and both guild leaders are on.  For some reason we are unable to create a alliance.  There is no error prompt, nothing showing why we cannot, just nothing.  Both he and I have tried it and neither one of us seems to be able to make the alliance happen.  We tried this prior to the most recent patch and have done so again today, 4/5/21, with the same results.  I have attached screenshots of us making the attempts today.

             If there is any other clarifications I can give, please let me know.  This was all done on my Warrior Priest, Aiya.

![Aiya_013](https://user-images.githubusercontent.com/55823353/113627611-63f8b000-9629-11eb-906e-ea0faca55e70.jpg)
![Aiya_014](https://user-images.githubusercontent.com/55823353/113627613-64914680-9629-11eb-8af4-c78d247407d3.jpg)
![Aiya_015](https://user-images.githubusercontent.com/55823353/113627614-6529dd00-9629-11eb-91f5-ca651a6876b4.jpg)
![Aiya_016](https://user-images.githubusercontent.com/55823353/113627615-6529dd00-9629-11eb-81df-4320eac5d032.jpg)

**Comment by lilimx** [comment]
Hey, 

thank you for your ticket. This issue is already known, so I will add it to the related ticket.
If you want to form an alliance your have to start create an alliance very often! And by very often I mean 30-50+

**Comment by lilimx** [comment]
dublicate / related to #15871
