### ISSUE TITLE
Sudden Crash PvP Zones (mssmp3.asi related)

### ISSUE THREAD

**Issue by Iagdtod** [WarEmu/WarBugs#18792]
Repeated crashes to desktop in PvP zones. 

Expected behaviour: Stay in game playing normally.

Actual behaviour: Crash to desktop. Crash occurs repeatedly in similar area if char relogs back into pvp zone at same spot. Static/noise on audio at time of crash. Happens in many places, examples are: KV 37356, 47958; Praag 34807, 59172; Praag 310093, 34923. Doesn't happen in pve zones.

Workaround is to start the launcher. When the connect button lights up, go into the 'miles' folder in warhammer install and delete 'mssmp3.asi' and then click connect. Can play for hours no problem with this workaround. Have to repeat for each new session though can change characters without restarting client. Workaround was seen from staff member on forum but cannot find it again with search.

Can reproduce problem by entering PvP and moving around.

**Comment by MaxHayman** [comment]
Sounds like an issue with your audio.myp

Have you tried this https://returnofreckoning.com/forum/viewtopic.php?t=36898

**Comment by Iagdtod** [comment]
Thanks, replaced audio.myp with the one that was linked by MaxHayman and no more crashes.
