### ISSUE TITLE
Bug caracter contribution 

### ISSUE THREAD

**Issue by Gagaddon** [WarEmu/WarBugs#18790]
Hello today im just log in game with Azummi and was walking in pve and in ic and receive contribuition in battle that im participate, not sure whats is causing the problem, looks like bug in contribuiton system, that add me even im not there. 

![2021-04-06 13-12-43-11](https://user-images.githubusercontent.com/52387005/113812658-da3e0500-9744-11eb-9762-ec69142dc792.jpg)

**Comment by MaxHayman** [comment]
Possibly linked to  the same issue which caused #18644

If so it should be fixed as of todays hotfix. Please reopen if this is not the case.
