### ISSUE TITLE
Stout and Bitter orcs invulnerable

### ISSUE THREAD

**Issue by AndyZawa** [WarEmu/WarBugs#18795]
**Expected behavior and actual behavior:**
Quest 'Stout and Bitter' seems bugged - black orcs you're suppose to kill with Organ gun are invulnerable. You can't deal damage to them either with the organ gun and normally. Organ gun works for sure, as if you aim for the other enemies that are around (goblins) you deal damage to them properly. 

**Steps to reproduce the problem:**
1. Go to the Mount Bloodhorn
2. Pick up the quest Stout and Bitter
3. Mount Organ Gun
4. Start shooting at the orcs

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
I need more information about what NPCs exactly. Please provide a screenshot.

**Comment by Kaelang** [comment]
Tested and the Organ Gun now kills the Black Orcs.

![image](https://user-images.githubusercontent.com/60117106/175754474-c7759bdd-1f7d-4b25-a789-ad0c67f0d7f9.png)
