### ISSUE TITLE
Bastion stairs, destro, last boss left wing

### ISSUE THREAD

**Issue by engharat** [WarEmu/WarBugs#18803]
Talking about the boss which randomly punt players, disabling them while spawning 2 dog which must be killed to free the player.
Expected behaviour: the dogs have some health and must be killed in order to free the player.
Actual behaviour: the two dogs die after 1 hit with a NULL EXCEPTION weird error, the player can move but cannot use skills anymore. Even getting out of the instance does not solve the problem, a relog is needed to fix the character skills.

**Comment by lilimx** [comment]
hey,

thank you for your ticket.
Do you have a screenshot of the error?
Has this error occurred again?

**Comment by lilimx** [comment]
Hey,

im going to close this ticket now due to no feedback.
If you're the opinion the issue still persists, please open a new ticket.
