### ISSUE TITLE
Chasing Oathgold - Dwarfs Step 11

### ISSUE THREAD

**Issue by Raznuts** [WarEmu/WarBugs#18800]
Expected behavior and actual behavior: You should come to place where the NPC is and kill it. Could not attack the NPC.

Steps to reproduce the problem: came to cords  60k, 7k. Tried to kill the npc. Could not attack it.

![2021-04-09 (2)](https://user-images.githubusercontent.com/19312741/114119432-ebc11180-98ea-11eb-95d7-8d7f30169c7c.png)

**Comment by Lheana** [comment]
This has been fixed with the patch of 20/04/2021.
