### ISSUE TITLE
Pummelers of Devouring (Gloves) Appearance Bug

### ISSUE THREAD

**Issue by wildwindblows** [WarEmu/WarBugs#18804]
Hello RoR  Bugtracker Team,

Appearance of Pummelers of Devouring (Gloves) is bugged. When I apply this item as an appearance, gloves and bots both change. Also, although this item is gloves, icon is bots. I think there is a bug so I want to report it. You can see the related picture below.

Thanks.

![image](https://user-images.githubusercontent.com/45720515/114263746-016c2f00-99f0-11eb-8c63-ba556b934cd3.png)

**Comment by wargrimnir** [comment]
These have the same model ID as several other Marauder gloves which is what controls the icon.

Can you test with Enduring Pummlers? R35 Green PvE drops, they should be fairly easy to get a hold of.

**Comment by wildwindblows** [comment]
Hello, sorry for the late response. I tried Enduring Pummlers as you wish. It looks like same bug as i reported above.
![resim](https://user-images.githubusercontent.com/45720515/125701559-a657ed0e-e29c-4cc2-87d3-8b66249c734e.png)

**Comment by wildwindblows** [comment]
Glove appearance is overwriting on bot appearance so i though this is a bug but if you say there is no issue thats okay.

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by wildwindblows** [comment]
Okay. Thank you.

**Comment by lilimx** [comment]
Hey,

please don't close tickets that we haven't pushed on live yet :D

**Comment by lilimx** [comment]
Fixed with Patch 22/07/2021
