### ISSUE TITLE
CnT Necromancer Malcidious Despawning @30% health

### ISSUE THREAD

**Issue by DefVont** [WarEmu/WarBugs#18801]
https://streamable.com/dbe8og

Despawns @ 4 seconds, tried twice, happened the same each time.

**Comment by lilimx** [comment]
Hey,

I can't recognize anything in this video. 
Please provide a proper video or screenshots about the issue.

**Comment by lilimx** [comment]
Hey,

im going to close this ticket now due to no feedback.
Additional the video-link seems outdated now.
If you're the opinion the issue still persists, please open a new ticket.
