### ISSUE TITLE
White Lion Desummon/Death Strips pots

### ISSUE THREAD

**Issue by KySaber** [WarEmu/WarBugs#18807]
As shown, upon despawn, the lion disappearing removes my strength pot, but this effect happens for liniments also.

https://youtu.be/5ah_uh_FnQU

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
Please check the kind of bug.
Is it a visible bug or does the potion really get lost.
do test like /rel and .getstats

**Comment by lilimx** [comment]
Hey,

im going to close this ticket now due to no feedback.
