### ISSUE TITLE
Butchering/Scavenging mobs not disappearing

### ISSUE THREAD

**Issue by kekkers119** [WarEmu/WarBugs#18810]
Not sure why but butchered mobs are not disappearing.

**Expected behavior and actual behavior:**
When you butcher a mob- the body disappears. This is no longer the case.

**Steps to reproduce the problem:**
I've been butchering for an hour. none disappear anymore.

**Testing Screenshots/Videos/Evidences (always needed):**
I have a video but unfortunately it's too big- I'll try and find a way to compress it.

**Comment by kekkers119** [comment]
![image](https://user-images.githubusercontent.com/42598271/114314798-30ef6a00-9aca-11eb-91e0-b1b3c135c9e1.png)
Well okay this is what I have for evidence- an SS of the loot I got from butchering these mobs and the bodies are still here.

**Comment by topdudes** [comment]
Confirmed. The same is happening to me and a friend. About half creatures you can't even butcher and all bodies stay around. Seems like it's slowing respawn time too.

**Comment by kekkers119** [comment]
If it's slowing respawn it's almost not even noticeable, at least to me.

**Comment by CrimsonFenris** [comment]
Respawn looks like not affected but remaining corpses are an issue since "loot nearest" key is most of the time not butchering corpses, only loot them.

Probably liked to other issues affecting spawning/despawning entities (in dungeons mostly)...

**Comment by kekkers119** [comment]
Or not even being able to loot mobs period sometimes.

**Comment by topdudes** [comment]
I've killed 4 bears in Riekland now and couldn't click on any of them. Not to get Sable cloak or to butcher.

**Comment by topdudes** [comment]
Today I was killing bats in Caledor for over an hour and, while I didn't keep count, I know that less than 1/2 killed were able to be butchered. Farming is now virtually pointless as it takes FAR too much time.

**Comment by MaxHayman** [comment]
This initial issue will is fixed pending release, if you still experience other issues after please reopen its own issue.

**Comment by kekkers119** [comment]
Thank you Max
