### ISSUE TITLE
our guild leaders are banned and it has been almost 2 and a half months from Evil Sunz no one has been allowed to take over the guild got Evilviking as a officer in the guild

### ISSUE THREAD

**Issue by Ecilchosen** [WarEmu/WarBugs#18827]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kilrathi01** [comment]
![es](https://user-images.githubusercontent.com/62448354/114616626-160d2900-9c75-11eb-9a47-fa3f6e4e040d.jpg)
![es2](https://user-images.githubusercontent.com/62448354/114616654-1e656400-9c75-11eb-81a1-0ed6829b8ba0.jpg)

**Comment by Ecilchosen** [comment]
If we get now leader we can change everything


Den tis 13 apr. 2021 kl 22:27 skrev Kilrathi01 ***@***.***>:

**Comment by Ecilchosen** [comment]
Sorry new leader


Den tis 13 apr. 2021 kl 22:33 skrev Kari Ylivirta ***@***.***>:

**Comment by Ecilchosen** [comment]
Yes killchoppa is band


Den tis 13 apr. 2021 kl 22:36 skrev Kari Ylivirta ***@***.***>:

**Comment by Ecilchosen** [comment]
sorry again all kill big boss and warboss is killschoppa count ho is band

Den tis 13 apr. 2021 kl 22:39 skrev Kari Ylivirta ***@***.***>:
