### ISSUE TITLE
Dwarf Quest Bug - Stout and Bitter -

### ISSUE THREAD

**Issue by CanadianZombie** [WarEmu/WarBugs#18830]
**Expected behavior and actual behavior:**
Supposed to use the Organ gun to shoot the black orcs on the bridge but nothing happens to them, neither does trying to melee them work.

**Testing Screenshots/Videos/Evidences (always needed):**
![Untitled](https://user-images.githubusercontent.com/82544173/114777995-b1bc9900-9d4a-11eb-97d8-60f0187e3b6a.jpg)
![Untitled2](https://user-images.githubusercontent.com/82544173/114777997-b2552f80-9d4a-11eb-8bf5-24a1fa6dc508.jpg)

**Comment by Lheana** [comment]
Duplicate of #18795
