### ISSUE TITLE
Dwarf Quest Bug - Casing Oathgold -

### ISSUE THREAD

**Issue by CanadianZombie** [WarEmu/WarBugs#18835]
**Expected behavior and actual behavior:**
Kill the only unique Ungor there to gain oathgold, killed over 5 times with no drop

**Testing Screenshots/Videos/Evidences (always needed):**
![Untitled5](https://user-images.githubusercontent.com/82544173/114805536-93ba5d00-9d79-11eb-9a93-cd64ba0d1940.jpg)
![Untitled4](https://user-images.githubusercontent.com/82544173/114805502-869d6e00-9d79-11eb-9842-0bb484e68787.jpg)

**Comment by Lheana** [comment]
The quest says to kill Korgoth Raiders to loot the Pick.
