### ISSUE TITLE
Dwarf Quest Bug - By Torchlight -

### ISSUE THREAD

**Issue by CanadianZombie** [WarEmu/WarBugs#18831]
**Expected behavior and actual behavior:**
Action to blow up these towers or any other tower but none other than this one are seen and they are not interact-able.

**Testing Screenshots/Videos/Evidences (always needed):**
![Untitled3](https://user-images.githubusercontent.com/82544173/114793784-898c6480-9d61-11eb-948a-3e0b452a0733.jpg)

**Comment by CanadianZombie** [comment]
**UPDATE:** Quest completed, should of checked the description (not mentioned in the the particulars) of the quest that mentions using  "their torches" to destroy the towers. Changing the Particular to mention this could help for those who don't read the descriptions but it's not bugged and a minor subjective issue. Animation from destroy the towers is rather odd truth be told.

**(Leaving thread up to the discretion of the admins to help anyone who makes the same oversight that I had.)** 

**IMAGE:**
![Untitled8](https://user-images.githubusercontent.com/82544173/114954489-14886000-9e31-11eb-8764-1761c78356ba.jpg)

**Comment by Lheana** [comment]
Then I close the ticket as the quest is completable. Maybe some changes will be made to the Particulars when the quest will be looked at.
