### ISSUE TITLE
Group buffs are not auto-removed on caster disconnection

### ISSUE THREAD

**Issue by CeridianX** [WarEmu/WarBugs#1883]
Sometimes I can't refresh my own Prismatic Shield (AM class) on another player. I think it usually happens when party was disbanded and recreated again. The only solution is to ask this player to right click on my version of the Prismatic Skill and discard it. Then I can again refresh the timer to 60min. Is it possible to fix it?

**Comment by Morksezstop** [comment]
Also you cant override it if other am put on someone the lower lvl of Prismatic Shield. It just stay the first Prismatic Shield that was casted. The issue is the same with mork buffer - shaman's version

**Comment by ozarmidrashim** [comment]
Prismatic Shield will only refuse to refresh if you cast it, disconnect, and relog. The player instance is different and so the original buff does not recognise you as its caster. If this is the case, I would have appreciated that you mention this in the original report.

**Comment by CeridianX** [comment]
Well, that's where I wasn't sure about when exactly it happens. As I mentioned in a first post I thought that it happens when party is disbanded but it seems you have found a true cause :)
