### ISSUE TITLE
Dwarf Quest Bug - The Tree of Beards -

### ISSUE THREAD

**Issue by CanadianZombie** [WarEmu/WarBugs#18836]
**Expected behavior and actual behavior:**
Kill goblins in the area, none of them are counting towards the quest.

**Testing Screenshots/Videos/Evidences (always needed):**
![Untitled7](https://user-images.githubusercontent.com/82544173/114811332-58715b80-9d84-11eb-821f-5b56b7da3465.jpg)

**Comment by CanadianZombie** [comment]
**UPDATE:** Did a public quest in this spot with a random party group and got 3 kills counted towards the quest yet when trying to do it alone it wasn't counting. 

**IMAGE:**
![Untitled8](https://user-images.githubusercontent.com/82544173/114949787-1e599580-9e28-11eb-8d26-478327ea0606.jpg)

**Comment by Lheana** [comment]
Well it works fine for me
![Lheanaa_043](https://user-images.githubusercontent.com/11537611/115116655-05252600-9f9b-11eb-93c8-249661a73c5e.jpg)
