### ISSUE TITLE
Dark Elf Quest Bug - Slipping the Skin

### ISSUE THREAD

**Issue by TotalRampage** [WarEmu/WarBugs#18832]
Expected behavior and actual behavior: The quest entails killing the local White Lions in the area in order to claim their pelts. However, despite the other mobs being attackable, only the White Lions remain unattackable in the respected area.

Testing Screenshots/Videos/Evidences (always needed):
![Screenshot (379)](https://user-images.githubusercontent.com/82555320/114803662-de35dc80-9d6d-11eb-8663-4cef03ecf93d.png)
![Screenshot (380)](https://user-images.githubusercontent.com/82555320/114803680-e5f58100-9d6d-11eb-97f6-12ab71af1343.png)

**Comment by Lheana** [comment]
This has been fixed with the patch of 20/04/2021.
