### ISSUE TITLE
Dark Elf Quest Bug - Nimosar's Fall

### ISSUE THREAD

**Issue by TotalRampage** [WarEmu/WarBugs#18834]
Expected behavior and actual behavior: Quest requires to venture into the Public Quest area Nimosar to destroy the Repeater Bolt Thrower. Though killing the mob does not give credit to the quest itself. 

Testing Screenshots/Videos/Evidences (always needed):
![Screenshot (381)](https://user-images.githubusercontent.com/82555320/114804442-4802b600-9d6f-11eb-8472-090bfa9232be.png)
![Screenshot (382)](https://user-images.githubusercontent.com/82555320/114804467-518c1e00-9d6f-11eb-8ff8-27307cbf6b57.png)
![Screenshot (383)](https://user-images.githubusercontent.com/82555320/114804505-610b6700-9d6f-11eb-9239-7e010cad9e60.png)
![Screenshot (384)](https://user-images.githubusercontent.com/82555320/114804520-65d01b00-9d6f-11eb-9fa8-41eac385f890.png)

**Comment by bucej** [comment]
I have the same problem. I tried to abandon the quest and take it again but nothing changed.

**Comment by Lheana** [comment]
This has been fixed with a recent patch.
