### ISSUE TITLE
Squig Beast+Squig Frenzy giving 275% increased damage instead of intended 175%

### ISSUE THREAD

**Issue by Wraythbw** [WarEmu/WarBugs#18837]
Presently, Squigbeast is currently giving 250% increased damage instead of the presented 150% damage.  I tested with a Squiggy today and verified that with Squigbeast and Squig Frenzy a squigs damage output spikes by 275% damage. Squigbeast giving 250% and Squig Frenzy giving 25% damage increase. We wanted to confirm that there was, in fact, an issue with damage output for Squig pets at present.

![Squigs Squigbeast](https://user-images.githubusercontent.com/54164763/114827406-7f785f00-9d7d-11eb-90dc-412c8dea63c3.PNG)

**Comment by Jonees123** [comment]
Morale says that it increases dmg by 150%, 100%+150%=250%

**Comment by CrimsonFenris** [comment]
440 base damage x 2 is still far more than similar WL pet skill but it's another matter.

Yet I'm afraid than it's currently working as intended, as 440 * 2.75 = 1210 (1212 in log because rounding somewhere).

**Comment by Wraythbw** [comment]
Thanks. I knew I was too tired to math. LOL I asked everyone and no one
could see a problem. I just overlooked inclusion of base damage
