### ISSUE TITLE
[Quest] Get Dat Stunty Tunnel! - Destruction - Kadrin Valley

### ISSUE THREAD

**Issue by AnnihilateImplicitly** [WarEmu/WarBugs#18842]
**Expected behavior and actual behavior:**

Requirement to scout Ice Hearth Crossing does not trigger when in range.

**Steps to reproduce the problem:**

Take the quest from Krung Da Mada in Kadrin Valley war camp. Go to Ice Hearth Crossing in direct range of BO flag and try so to trigger next quest step.

**Testing Screenshots/Videos/Evidences (always needed):**
![WAR-64 2021-04-15 17-07-39](https://user-images.githubusercontent.com/80687333/114892576-3112a100-9e0d-11eb-97ed-8fc8f3abb293.png)

**Comment by Lheana** [comment]
Same issue as #18591
