### ISSUE TITLE
Scenario Summary Window Keybind

### ISSUE THREAD

**Issue by Symbelmyne** [WarEmu/WarBugs#18847]
Scenario Summary Window Keybind doesnt open window during a scenario anymore.
Still works as intended for 2+ members group anywhere outside scenario maps.

**Expected behavior and actual behavior:**
Keybind Scenario Summary Window and press said key to open window - doesnt open anything while in scenario.

**Steps to reproduce the problem:**
Keybind Scenario Summary Window and press said key to open window - doesnt open anything while in scenario.

No needed screens cause nothing happens :)

**Comment by MaxHayman** [comment]
Hmmm this works for me. Does this happen on all of your characters?

**Comment by Symbelmyne** [comment]
At least the 4 i play. I got 2 separated UI for order and destro, both not working, changing key to different one also does nothing.

**Comment by Symbelmyne** [comment]
I finally found that CMap addon was causing this. It overwrites scenario summary window and some of Cmap versions got that feature disabled. Closing.
