### ISSUE TITLE
Crafting Trainers not working.

### ISSUE THREAD

**Issue by Klod91** [WarEmu/WarBugs#18844]
Can't learn from crafting trainers.

![Reppanse_010](https://user-images.githubusercontent.com/77681824/114915416-d173c000-9e23-11eb-8257-b6bd85485161.jpg)
![Reppanse_011](https://user-images.githubusercontent.com/77681824/114915409-cfa9fc80-9e23-11eb-8846-be358d2382a4.jpg)
![Reppanse_009](https://user-images.githubusercontent.com/77681824/114915401-cb7ddf00-9e23-11eb-8db4-101cee9d2827.jpg)
![Reppanse_012](https://user-images.githubusercontent.com/77681824/114915406-cde03900-9e23-11eb-897d-235d6fa770e1.jpg)

**Comment by JockeJoestar** [comment]
Can confirm that the same issue happens on Destro's side as well.

**Comment by Crewcop** [comment]
Cannot change or initially select trade skills on either side, tried in both cities and in Norsca.

**Comment by valkeera** [comment]
I have same problem with my AM lvl 7, tradeskill trainers in Hi Elf ch2 are not training anything either.
