### ISSUE TITLE
[QUEST] T2 Dark Elf Epic Questline "A Lord's Game" Step 12 Broken

### ISSUE THREAD

**Issue by Kwatchi** [WarEmu/WarBugs#18846]
Step 12 of the Tier 2 "A Lord's Game" Questline requires killing ten (10) Griffin Guards and ten (10) Griffin Defenders.  These are found in the Dark Elf Chapter 7 PQ "The Griffin Gate" stage 1.

PROBLEM:

Griffin Guards are name flagged red but bring up error message "Target is Not Attackable" and cannot be engaged.  Without the ability to complete the kill count, the stage of the questline becomes a road block to completion.

![Vorrg_000](https://user-images.githubusercontent.com/59769287/114959906-fec86a00-9e33-11eb-83a7-3414551c673e.jpg)

SOLUTION ATTEMPT:

Moved PQ into next stage, but unattackable status does not change on PQ reset.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
This has been fixed with the patch of 20/04/2021.
