### ISSUE TITLE
Those Who Serve - DElf Saphery quest

### ISSUE THREAD

**Issue by Wesleth** [WarEmu/WarBugs#18845]
[

**Expected behavior and actual behavior:**
Expected - Horn found in marked area
Actual - Searched over every inch of the area, both destro and order side, up on the cliffs, etc etc, no item on landmass and none in inventory

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
![Anaehll_227](https://user-images.githubusercontent.com/11537611/115117259-f2f8b700-9f9d-11eb-98ae-be66bfec227a.jpg)
