### ISSUE TITLE
Cannot turn in any quests...

### ISSUE THREAD

**Issue by kekkers119** [WarEmu/WarBugs#18849]
**Expected behavior and actual behavior:**
Well, you're supposed to be able to turn quests in, right? :) Unfortunately.. that is not the case, at least for myself....

**Steps to reproduce the problem:**
I've relogged/restarted client. Maybe I should clear cache and try...

**Testing Screenshots/Videos/Evidences (always needed):**

https://clips.twitch.tv/EncouragingFriendlySangBrainSlug-XtSfKQJLwaISo9kv

**Comment by kekkers119** [comment]
Nvm... it works again. Not sure why. But maybe others are having a similar issue.

**Comment by Lheana** [comment]
I close this ticket.
