### ISSUE TITLE
[Bastion Stairs] Left wing Galvoth Darkrage impossible to do

### ISSUE THREAD

**Issue by CrimsonFenris** [WarEmu/WarBugs#18841]
**Expected behavior and actual behavior:**
When fighting  Miniboss **Galvoth Darkrage** in Bastion Stair left wing, the Khorne Hound add is level 1 champions instead of 40+.

The add can be oneshotted on first hit, and since it is very low life by being level 1, it also adds a lot of damage to the boss from start (boss and thunder puddles hitting for 7k and more, for instance).

This boss is currently impossible to do even with end-geared party.

Same issue as other lv 1 adds, for instance in Gunbad - https://github.com/WarEmu/WarBugs/issues/18840

**Comment by martialiss** [comment]
Yes, dog add is level 1 and get killed in milli seconds.
But killed Galvoth anyway without trouble and only a Conqueror tank. That was 12 hours ago.

**Comment by dalen** [comment]
fixed 
![image](https://user-images.githubusercontent.com/7400/174071507-7f34bb4d-91c4-41bc-aedf-da0f126d1768.png)
