### ISSUE TITLE
T2 Keep Lords

### ISSUE THREAD

**Issue by Internetbaron** [WarEmu/WarBugs#1885]
I made a froum post about this already.

There is the whole story.
http://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=8445

It seems t2 Keep lords are bugged, they are too strong. They crush a whole Warband alone. We cant kill any t2 keep lord and there is not a single defending player around.

They one shot tanks with 4,5k Dmg per hit.

In the Thread is a sceen of my combatlog, i am Warrior Priest and hot hit for 10k in t2.

One of my fellows in the Warband said maybe they have t3 strength and it got messed up.

**Comment by DanaBloodkiss** [comment]
Improved.
