### ISSUE TITLE
blades of SM

### ISSUE THREAD

**Issue by borgute** [WarEmu/WarBugs#18858]
Blades of sword master doesn't works like it's said in tooltbar skills : 

Phantom's blade give a buff wounds insteak to make an absorb damage
Heaven's blade make a buff armor insteak a spirit debuff (cumulate to Wrath of hoeth)

Tactic potent enchantments doesn't works.

thanks.

**Comment by CrimsonFenris** [comment]
They work as described, you'll have to see the english tooltips that are accurate (I assume ou are playing in other language that contains outdated tooltips).

Potent enchantment works perfectly, it procs with Nature's Blade skill stealing and with AoE skills as well (very good tactic).
