### ISSUE TITLE
Turret dissapear when you use them to attack in Thunder Mountain

### ISSUE THREAD

**Issue by EssentialOrder** [WarEmu/WarBugs#18852]
I don't know if this only happens to my character ,
for some weeks now the turrets in TM dissapear when i use it 

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kruge1976** [comment]
i can confirm the same - only really tried outside the WC (where the spiders are in PVE side), but summoned turrets just vanish

**Comment by topdudes** [comment]
It's been this way for over a month now. What I've found is that turrets seem to work fine in the RvR lake but not PVE. In PVE, if I put my turret on a rock and not the ground it seems to stay.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. I will add it to a related issue.
