### ISSUE TITLE
bilerot burrow bile lord bugged

### ISSUE THREAD

**Issue by Sixmoons48** [WarEmu/WarBugs#18856]
After getting ported at 20% inside of the boss to kill his heart or whatever, it despawned nearly immediately, trapping us inside, not taking damage but unable to finish encounter 
![image](https://user-images.githubusercontent.com/21229715/115131774-40861b80-9fc0-11eb-896e-bb6f45f6f9f5.png)

**Comment by Sixmoons48** [comment]
able to walk back in after booking to finish off boss, no barriers in way

**Comment by madregit** [comment]
theres more bugs, like port after stomach and he insta dies, count influence but not have his corpse or count quest kill.

**Comment by Lheana** [comment]
This has been fixed with the patch of 20/04/2021.
