### ISSUE TITLE
Kreuznach is missing craft supply vendor

### ISSUE THREAD

**Issue by Thaodan** [WarEmu/WarBugs#18855]
**Expected behavior and actual behavior:**

Craft supply vendor is missing

**Steps to reproduce the problem:**

1. Look at the in game map of Krezunach
2. Look for the vendor.

**Testing Screenshots/Videos/Evidences (always needed):**

![Screenshot_20210418_030605](https://user-images.githubusercontent.com/1747359/115129900-0a15c400-9ff3-11eb-9f79-509dce305d92.png)

**Comment by Lheana** [comment]
There is one.
![Lheana_236](https://user-images.githubusercontent.com/11537611/115146433-cf457780-a056-11eb-80f3-b0f7c2cbdcfc.jpg)

**Comment by Thaodan** [comment]
Oh thanks.
