### ISSUE TITLE
Offensive Sovereign (MDPS) Armor Penetration stat/tool tip bug

### ISSUE THREAD

**Issue by wildwindblows** [WarEmu/WarBugs#18857]
Hello RoR Bugtracker Team,

Armor penetration bonus of offensive sov. helm and 4th piece bonus of related set are missing.  Although ".getstats" indicate 9% armor penetration (3% from off sov. helm+6% from 4th proc.), total armor penetration doesn't show them. For my scenario, total armor penetration should be 30.2% but stats indicates 21.2% so it can be said that 9% is missing which comes from offensive sovereign and 4th piece bonus. It might be a visual bug too here im not sure but this is seem weird so i decided to report this as a bug.

Thanks for take care of all bugs and keep RoR alive :)

![image](https://user-images.githubusercontent.com/45720515/115140098-3d317500-a03e-11eb-8b1c-77cfc4443351.png)

**Comment by CrimsonFenris** [comment]
No bug here, armor penetration is only calculated with your weapon skill Arpen, wich is not told by getstat, + your items/tactics/procs bonuses wich are shown in getstat but not in paperdoll.

Add both and you have your total arpen (wich is multiplicative iirc, resulting in a bit less than 30% in your case). 

The cumulative total will not be shown with base game tools, you'll need addons like statdoll or something like that.

**Comment by wildwindblows** [comment]
Is there any way to observe total stats instead of calculate by one by for each stats?
