### ISSUE TITLE
Dawnbreak hunter npcs are not attackable (Dar Elf T7 chapter)

### ISSUE THREAD

**Issue by Valashitel** [WarEmu/WarBugs#18851]
Dawnbreak hunter npcs in Dark elf T7 chapter (Quest Becoming the unseen) are not attackable.

**Expected behavior and actual behavior:**
One should be able to attack and kill them to get the quest done, but they are not attackable and thus also not killable.

**Steps to reproduce the problem:**
Go there and try to attack them

**Testing Screenshots/Videos/Evidences (always needed):**

![bandicam 2021-04-17 19-26-34-082](https://user-images.githubusercontent.com/82724243/115121513-740e7900-9fb3-11eb-9277-162412bbf7de.jpg)

Note that game critical and game breaking bugs may award a manticore/griffon (realm specific) at the leads discretion however, asking for one instantly disqualifies you from this reward.
-->Thnaks for looking into the issue

**Comment by Lheana** [comment]
This has been fixed with the patch of 20/04/2021.
