### ISSUE TITLE
Gutslime stuck in wall, unattackable.

### ISSUE THREAD

**Issue by SnyypaVoltron** [WarEmu/WarBugs#18863]
Gutslime is bugged into an unattackable position. Even challenge doesn't grab him.

**Expected behavior and actual behavior:**
You would expect him to be in his little cave chateau. 

**Steps to reproduce the problem:**
Go to his lair and tab target to find him in the wall outside. 

**Testing Screenshots/Videos/Evidences (always needed):**

![gutslimestuck](https://user-images.githubusercontent.com/82342282/115300655-1134f300-a115-11eb-8052-d24094323db9.PNG)

**Comment by avalus** [comment]
Seems to be an issue related to the pathfinding of mobs while they walk around.
The same situation happened to me the other day while trying to do a quest at the docks where a Risen had wandered away into the closest building and was targetable but not attackable, exactly as your screenshot illustrates.
