### ISSUE TITLE
Chosen crit damage stats 

### ISSUE THREAD

**Issue by oroxor** [WarEmu/WarBugs#18861]
Hi, 

On my chosen i have 5 piece of sov dreadsword and 3 warlord.
The 5 pieces of sov gives in crit damage 15% of crit ,and the tactic oppressing blows guives 15 too and i dont hjave 30 % in getstats.
![Tartouille_001](https://user-images.githubusercontent.com/38176487/115278305-96d09700-a145-11eb-9ada-d433fad0340c.jpg)
)

**Comment by yuaa2** [comment]
crit chance and crit damage diferent stats......
