### ISSUE TITLE
Dark Elf chapter 8 Quest a lord´s game is broken

### ISSUE THREAD

**Issue by Valashitel** [WarEmu/WarBugs#18862]
The War trumpet in the inventory cannot be used and so the NPC cannot be summoned

**Expected behavior and actual behavior:**
The war trumpet in the inventory should summon the NPC that needs to be killed to complete the quest, but the trumpet cannot be used inside the marked zone

**Steps to reproduce the problem:**
Try using the war trumpet

**Testing Screenshots/Videos/Evidences (always needed):**
![bandicam 2021-04-19 19-34-53-136](https://user-images.githubusercontent.com/82724243/115278927-5aea0180-a146-11eb-8026-78d9c7823055.jpg)

Thanks for looking into the issue

**Comment by Lheana** [comment]
The NPC is permanently spawned
![Anaehll_470](https://user-images.githubusercontent.com/11537611/115434793-63efd700-a209-11eb-8fa4-847affa657e0.jpg)
