### ISSUE TITLE
Ranked Q bug

### ISSUE THREAD

**Issue by Aeriell** [WarEmu/WarBugs#18868]
Joined Ranked Q, system told me I am a quitter (not possible because it was the first scenario i Q of the day) and took away 25 mmr points for no reason.

Is it a bug or some mechanic i don't understand? 

Thanks, the car is Pizzashield btw.

**Comment by lilimx** [comment]
Hey,

are you still not able to join a ranked match?

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now,  due to insufficient information.
