### ISSUE TITLE
My cast bar interface doesnt show my cast time. And I tried going into setting and reloading the UI but its still not working. Please fix, Thanks!

### ISSUE THREAD

**Issue by oneinchwarrior** [WarEmu/WarBugs#18869]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
As it's not a general issue, it must be something related to your installation or something that was not updated correctly. Try the Repair button on the launcher, if the issue persists, please use our forum or discord for technical advice.
