### ISSUE TITLE
Single character move speed lower than other toons

### ISSUE THREAD

**Issue by briantheLEDguy** [WarEmu/WarBugs#18867]
When I first logged in on my RP, it felt like I was running a lot slower than usual.  We did a few quick tests to confirm this before writing this ticket, but yes we found there was some sort of issue with my move speed. 

**The Test:** 

1 - Ran mounted race against a Knight (friend helping find bug) - Runeloc lost by a lot
2 - Had friend person log on RP to see if it was related to class/copter - Runeloc still lost the race by a lot
3 - I relogged my Slayer to see if it was all my toons - My Slayer was just as fast as my race buddy
4 - Finally logged back on Runeloc and did a foot race - Runeloc was much slower on foot as well 

This appears to be something lingering on this single toon. Several relogs/restarts have not fixed it. 

My .getstats reads back my unmounted move speed at 100 and mounted at 159.  So this appears to be reading back correctly. 

**Expected behavior and actual behavior:**

Expected - Equal speed as other players
Actual - running way slower than other players

**Steps to reproduce the problem:**

Log on Runeloc and run forward. 

**Testing Screenshots/Videos/Evidences (always needed):**

The race was down the docks in a straight line using autorun to the quest giver seen below.  When the other player arrived at the quest giver, I was roughly this far behind.  

![image](https://user-images.githubusercontent.com/45979606/115431546-49dad800-a1ba-11eb-9b69-ca62feefe0e4.png)

**Comment by CrimsonFenris** [comment]
You may have accidentaly hit the "walk" key wich slow you down until pressed again. I strongly advise to get back to run mode and unset this keybind for the future.

Otherwise try to do a repair (with launcher options), maybe master files are corrupted, but for one char only it is most probably the accidental key... ;)

**Comment by briantheLEDguy** [comment]
My Toggle Walk key binding was already not set but I set it real quick to toggle it on then off again.  I also did a repair from the launcher.  Neither of these approaches worked.  

Wonder what it is!

**Comment by lilimx** [comment]
Hey,

thanks for you tickt. I will add it to a related issue.

**Comment by lilimx** [comment]
related/dublicate: #19002
