### ISSUE TITLE
BS - Skull Lord Var'Ithrok - Spawning Hounds

### ISSUE THREAD

**Issue by Zumos** [WarEmu/WarBugs#18866]
Boss starts spawning hounds after the first punt. See video.

https://youtu.be/UaEGkF_j6L8

**Comment by CrimsonFenris** [comment]
Hounds are level 28 (so clearly a bug), and spawn like 30 at a time. Biggest issue is they drain AP with each hit, basically totally disabling targeted players.
And 60 dmg per hit * 30 each second is not doing much good to even a well-geared tank either, not to mention the other damaging from boss alone.

**Comment by lilimx** [comment]
fixed 2021-04-21
