### ISSUE TITLE
[WH] Dragon gun KD doesnt work when using Openers

### ISSUE THREAD

**Issue by CrimsonFenris** [WarEmu/WarBugs#18879]
**Expected behavior and actual behavior:**
Dragon Gun should Knockdown the main target on hit.
Currently when using any opener (from regular Incognito or Sanctified Oil), the Knockdown will not trigger.
You have to build accusations from "normal" skills to have DG work ; as soon any opener is used DG kd will not work.

**Steps to reproduce the problem:**
- Enter Stealth by any mean
- use opener to build 2 accusations
- try to use Dragon Gun on target (number of accusations won't matter)
- Target will not be kd nor getting immune from DG hit

Tested with a fellow WH in duel arena, no video recording available.
Didnt test for the WE however, could be same issue.

**Comment by komar9220** [comment]
Ability Error: Dragon gun (8110) component 0,2 (InvokeBuff): Can't find info for buff 5990

**Comment by Duukar** [comment]
The KD isnt working for me regardless of using an opener or not. There is just NO KD at all with dragon gun atm.

When I test it on the practice dummies it is giving them a 45 second resurrection sickness debuff instead of the KD..

**Comment by Duukar** [comment]
It is also not consistently proccing whichever bullet you have selected on the initial target. It IS working on all other targets

**Comment by sharju11** [comment]
Confirming the findings that Dragon Gun is not knocking down. I just tested it multiple times out int he lakes. Got about 1 knock down randomly out of 10 destro I hit. Also getting the error "Ability Error: Dragon Gun (8110) component 0,2 (InvokeBuff): Can't find info for buff 8985"

And as Duukar found, I can back up confirm that Dragon Gun isn't proccing bullets on the main target hit by Dragon Gun

**Comment by Sharmoulinho** [comment]
The dragon gun is not Knocking down anyone nor spreading its bullets debuffs following an opening and it rarely KD the target with regular accusation too
This major bug is running for almost a week now
Ability Error: Dragon gun (8110) component 0,2 (InvokeBuff): Can't find info for buff xxxx

**Comment by Lheana** [comment]
This has been fixed with a previous patch.
