### ISSUE TITLE
[Ability] Sorcerer sovereign set bonus

### ISSUE THREAD

**Issue by Syzako** [WarEmu/WarBugs#18876]
--------------------
1) Wrong Damage
--------------------

![1](https://user-images.githubusercontent.com/39750677/115510883-fd7fbd00-a2cb-11eb-9fba-d2b399268b34.png)
![2](https://user-images.githubusercontent.com/39750677/115510898-007aad80-a2cc-11eb-8e05-f24db3164e87.png)
![3](https://user-images.githubusercontent.com/39750677/115510909-02447100-a2cc-11eb-9fc9-3454e7365548.png)

--------------------
2) "On Hit" worked only for "Path of agony" abilities.
--------------------

![4](https://user-images.githubusercontent.com/39750677/115510919-03759e00-a2cc-11eb-80c2-d3ee4997d862.png)

**Comment by wargrimnir** [comment]
This event check is set to IsSingleTargetDamage, not a specific mastery tree. This is intended.
