### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by Ciaphasus** [WarEmu/WarBugs#1887]
When logging in, after inserting password and login, the game is loading, I can see buttons like properties, video etc, text box, but nothing happens. After that I get Critical error: Authentication failed -- application will now terminate

**Comment by Calarian** [comment]
Where are you loading into at?

**Comment by Ciaphasus** [comment]
Sorry, I do not get your question. Where am I situated? Moscow region, Russia. Or what do you mean?

**Comment by Evildoor** [comment]
Not an emulator bug. Such things belong to forums.
