### ISSUE TITLE
Zonelock requirements

### ISSUE THREAD

**Issue by BomblingTV** [WarEmu/WarBugs#18874]
**Expected behavior and actual behavior:**
When a Realm have captured the enemy keep and control 3/4 Battleobjectives plus the ruin+ own keep a zone is locking if these conditions are met when the zonelock-checktimer reaches zero (this can be checked by hovering the mouse over the old Victory point bar to see exact timer of the chek)

**Steps to reproduce the problem:**
In "some" zones this is not the case atm.
Instead the zones will flip instantly, or in same cases when just one Battleobjective is under control for the attacking dominating realm.

List of zonelocks ive collected data for when I realized the patern of not all zones misbehave:
- Kadrin Valley T4 locking for destro into Stonewatch fortress. This was a bugged lock that instantly locked the zone with not 3 BOs controled.
- Kadrin valley T4 locked for Order 5hours later, first lock-check timer reached 0seconds and it didnt lock the zone despite 3 fully blue BOs. next minut order had all 4 BOs and the zone locked as the timer reached 0 on the VP bar.
- Caledor T4 locked just fine normally for destro. The lock was respecting both timer and 3/4 requirement on the BOs.
- Caledor T4 locked 6 hours later, this time Order pushed and opened the Fell Landing zone with just one BO at the time the zone locked right after the keep lord had died.
- Chaos Waste T4 locking just fine normally for destro. The lock had 3/4 BOs and the lock was at the correct check-timer from the VP bar method.
- Chaos Waste T4 Order locking and opening The Maw fort. Holding 1/4 BOs and zone locked.
- Chaos Waste T4 Order locked after 1/4 BOs at the exact timer for when the checktimer ticked.
- Thunder Mountain T4 Destro locked the zone, and not a single BO was red but the zone flipped and locked anyways for destro.
- Dragonwake locking for order, was a correct lock and the timer + bo requirements were true.
- Praag T4 order locked it without a single BO controled or contesting, and instant locked after keeplord was dead.
Extra data opservations,
- MoM T2 Worked normally and required all 3 BOs for destro to lock.
- Talabecland T3 worked normally and required all 3 BOs for destro to lock.
- T3 Badlands worked nornally and order locked after capping 4 BOs and correct ticktimer.
This issue was first (based on memory) mentioned and talked about about a week ago if this helps dig up whatever code seemed to break based on timeline.

Will update on this as I get more data on which zones are working and which are not.

Screenshot of how to check the lock-check timer ingame, place mousecurser over the Green-yellow VP bar and look at the seconds shown. this doesnt automatically update unless you remove the curser and check again a second later. A trust worthy method that has worked all my years on RoR to know zonelock-checktimer
https://imgur.com/a/gMpVY9i

**Comment by MaxHayman** [comment]
Thanks for the report @BomblingTV. I've got a fix so will be deployed with the next patch/hotfix.
