### ISSUE TITLE
Skarlok

### ISSUE THREAD

**Issue by Oathaxes** [WarEmu/WarBugs#18873]
Hello ! , skarlok beastlord boss is currently bugged out up the mountain of his cave ! , thanks in advance

**Comment by Xicoz** [comment]
too add more info we had pulled the boss, it got out of range, and when it went to reset it dissapeared and spawned in this location 
![Stuntydwarfboi_005](https://user-images.githubusercontent.com/44329952/115473796-942f7980-a1f9-11eb-8a0e-c6b51d7b1c04.jpg)

**Comment by Xicoz** [comment]
same thing has happened to me with basically every lair boss throughout the years ive been playing

**Comment by lilimx** [comment]
Hey,

thanks for the report. I will add to a similar one and close this ticket.
NPCs not standing at the right place/stuck somewhere #16938
