### ISSUE TITLE
Altdorf glitch in time and space.

### ISSUE THREAD

**Issue by NoTutorialneeded** [WarEmu/WarBugs#18885]
So this is the second time in a month where i randomly get teleported into an altdorf where there is no one, i cannot use any portals, army recalls, teleports or war reports...... it says i am in combat and the doors to the keep says "Your realm cannot use this".... i have no clue what is causing this... but it has ruined two Altdorfs for me now......

And both times people have accused me of leeching city, not contributing to the fight. Even tho i tell them i am stuck in a bug and cannot to anything....

**Comment by MaxHayman** [comment]
Do you haev any screenshots of this?

**Comment by NoTutorialneeded** [comment]
sadly my keyboard's print screen button is ripped off.... i did stream it on Discord for my guild... but unfortunetly Discord does not save livestreams...
________________________________
Fra: Max Hayman ***@***.***>
Sendt: fredag 23. april 2021 00:12
Til: WarEmu/WarBugs ***@***.***>
Kopi: NoTutorialneeded ***@***.***>; Author ***@***.***>
Emne: Re: [WarEmu/WarBugs] Altdorf glitch in time and space. (#18885)


Do you haev any screenshots of this?
