### ISSUE TITLE
PNJ Franz Reichert of public quest Reichert's Raiders is not attackable

### ISSUE THREAD

**Issue by MatthieuMuschinowski** [WarEmu/WarBugs#18884]
Hello, 

Farming some public quests and stumbled upon this one...

**Expected behavior and actual behavior:**
Boss should be killable and isn't attackable on 3rd stage.

**Steps to reproduce the problem:**
See pic below : 

**Testing Screenshots/Videos/Evidences (always needed):**

![Screenshot from 2021-04-22 14-46-44](https://user-images.githubusercontent.com/7795766/115717054-1ba3f680-a37a-11eb-8780-c402b9620e82.png)

**Comment by Lheana** [comment]
This has been fixed with the patch of 20/04/2021.
