### ISSUE TITLE
Taking quests from opposite faction keep lord

### ISSUE THREAD

**Issue by jgale3303** [WarEmu/WarBugs#18882]
if you spam right click the lord you can get the quest for the opposite factions keep lord. here is an example 
![image](https://user-images.githubusercontent.com/78208440/115673341-7b54ce80-a387-11eb-9326-b1dee2efad81.png)

**Comment by jgale3303** [comment]
awesome glad i could help

**Comment by b00nation** [comment]
this has been a duplicate of https://github.com/WarEmu/WarBugs/issues/17503
