### ISSUE TITLE
Bolster not working in oRVR

### ISSUE THREAD

**Issue by Tallerz** [WarEmu/WarBugs#18880]
Entering Orvr in a character less than 40 does not proc bolster. I tried this with multiple sub-40 characters, attached from my squig herder at 5:20pm today.
![image0](https://user-images.githubusercontent.com/81527658/115589018-47b26f80-a2c7-11eb-889e-a912c39a294e.jpeg)

**Comment by lilimx** [comment]
Hey,

thanks for your ticket. I will add it to a related issue.

**Comment by lilimx** [comment]
dublicate / related to  #18988
