### ISSUE TITLE
[City siege Altdorf] Unclickable summoning stage1

### ISSUE THREAD

**Issue by BomblingTV** [WarEmu/WarBugs#18887]
When Altdorf is under siege and instances are formed. In case of the Defenders loosing the first 3 BOs Altdorf Libery BO becomes attackable. After the canons have been destroyed at his BO it opens up for the summoning-clickable object inside the building. When 6players have clicked on this and stand still till the ritual have been finished the Lord of Change will be summoned to fly to the gate and attack it.

However, right now and for the past 1-2 weeks this clickable ritual object have not been interactable for destro players after taking the BO. Some reported they could click it and start the channel but got instantly interrupted others like myself simply couldnt click on it despite boss not being already summoned fully, or no other players were trying to click so it should allow me to click on the objective.

Tested this in IC citysiege and the mechanic worked just fine normally (6players clicking at the same time worked instead of one by one, just like the change to turning in supply boxes in orvr keeps worked this way after a patch 3 weeks ago or so) However IC object is working fine. So only the Altdorf one is broken atm.

**Comment by Symbelmyne** [comment]
Still bugged Destro attacking Altdorf St1. Cant summon Chicken.

**Comment by MaxHayman** [comment]
![image](https://user-images.githubusercontent.com/1018809/120065665-5defe000-c06a-11eb-8f91-99f23ea5a35c.png)
![image](https://user-images.githubusercontent.com/1018809/120065668-634d2a80-c06a-11eb-963d-1a6f341b8cd3.png)
![image](https://user-images.githubusercontent.com/1018809/120065673-68aa7500-c06a-11eb-86a7-d9257150b7b2.png)

Seems to work fine. Do you have a video of the issue?

**Comment by MaxHayman** [comment]
Think i found the issue. There is a 60s cooldown between interactions.
