### ISSUE TITLE
Ranked Queue not working requiring relog

### ISSUE THREAD

**Issue by bloodmasked** [WarEmu/WarBugs#18890]
![image](https://user-images.githubusercontent.com/6406832/115865858-ffdd4500-a48c-11eb-8c90-1fcde61f16c2.png)

I am destro healer but it says 0 healers on destro.

It doesn't register that I am in the queue. When the scenario pops I don't get it in even though I would be first place in the queue. I wait 30+ min and still no pop.

I try to exit queue and re-enter, did not fix. So I logout and in.

Relogging fixed the issue.

**Comment by lilimx** [comment]
Hey,

I guess this ticket is obsolet now?

**Comment by lilimx** [comment]
Hey,

due to the lack of information, I'll close this ticket now.
