### ISSUE TITLE
Savage Porcine Bile Apothecary item not Working

### ISSUE THREAD

**Issue by Malvonim** [WarEmu/WarBugs#18892]
**Expected behavior and actual behavior:**

The item should be able to go into the Apothecary window for creating a potion, but instead the item doesn't go in or even give the "item add" sound that you get when putting it in the recipe.

**Steps to reproduce the problem:**

I have relogged and tried multiple times throughout a week to try to put the Savage Porcine Bile into the Apothecary window, but it has not worked at all.

**Testing Screenshots/Videos/Evidences (always needed):**

![Malvonim_057](https://user-images.githubusercontent.com/77261034/115946080-14fda800-a47c-11eb-89a4-18385ee24a83.jpg)
I do have a video if you need it, but I'm not exactly sure how to share it.

**Comment by bloodmasked** [comment]
It been broken for years #7740

**Comment by lilimx** [comment]
Hey,

thanks for your ticket. 
Like bloodmasked mentioned it's a known issue in #7740 so I will close this report now.
