### ISSUE TITLE
NPCs selling wrong EQ

### ISSUE THREAD

**Issue by Bajlk** [WarEmu/WarBugs#18894]
There are two NPCs which selling the EQ that should normally sell the other.

SC-NPCs
![SCNPCs](https://user-images.githubusercontent.com/58007137/115955400-7bbfa780-a4f6-11eb-864f-2c0bfaca4b2a.jpg)

RvR-NPCs
![RvRNPCs](https://user-images.githubusercontent.com/58007137/115955410-84b07900-a4f6-11eb-9f93-d4a3933f5800.jpg)

**Comment by Lheana** [comment]
I don't see any problem. Annihilator is RvR set and Mercenary is Scenario set.

**Comment by Bajlk** [comment]
> I don't see any problem. Annihilator is RvR set and Mercenary is Scenario set.

Scenario NPCs selling DEF-EQ for DDs while RvR-NPCs selling DD-EQ for DDs.

**Comment by Bajlk** [comment]
Closed?
It is really timewaste reporting Bugs here...
