### ISSUE TITLE
White lion 1rst Tree Skill Force Opportunity gains skill level from 2nd Tree Level up

### ISSUE THREAD

**Issue by Godhead9** [WarEmu/WarBugs#18893]
Force Opportunity should gain levels if you put points in 1rst tree Hunter not 2nd tree Axeman.

![Force Opportunity1](https://user-images.githubusercontent.com/46496255/115950560-aa348700-a4e4-11eb-94c0-02ff64eb70d9.png)
![Force Opportunity2](https://user-images.githubusercontent.com/46496255/115950565-af91d180-a4e4-11eb-83a7-68d345e3ed41.png)
![Force Opportunity3](https://user-images.githubusercontent.com/46496255/115950566-b15b9500-a4e4-11eb-94e1-be96728d4e39.png)

Thanks for your time.

**Comment by lilimx** [comment]
Hey,

It looks like the problem has now been fixed. If your the opinion it's still up, please open an new ticket.
