### ISSUE TITLE
Choppa T3 Empire Influence RVR Gear: Missing Talisman Slot

### ISSUE THREAD

**Issue by mursie** [WarEmu/WarBugs#1889]
Middle reward is a helmet named Thickmuck Skully.  In addition to being labeled after the T3 badlands keep (minor issue) the big issue is that both purple helmets have no talisman slot which is definitely not in-line with all other class rewards for same level of influence in this rvr area.  Can you please fix this.

**Comment by Meralors** [comment]
Fixed Thickmuck SKully ( also added a skin to it because it had none :p )
While I was working on it I found out Ghrond's Stompas and Qhaysh Stompas had no skin too, so they are fixed too.

**Comment by mursie** [comment]
so - if you already have item are you just SOL?  because my helm is not fixed

**Comment by Evildoor** [comment]
It is more likely that fix was not pulled live yet.

**Comment by mursie** [comment]
oh - ok - and WOW fast response!

**Comment by mursie** [comment]
just for clarification - are bugs like this usually retro'd to all players that have the gear item already?

**Comment by Evildoor** [comment]
Usually - yes. Your item should be fixed as well as new ones.

**Comment by Meralors** [comment]
Fixes are madeon dev server. Live isnt patched for every single fix we make, or we would have to bring it down every 2minutes ;)
All the fixes we make will be pulled live with next patch, dont worry, it may take a day or two
