### ISSUE TITLE
Free ability from saved build who need +2 to path X

### ISSUE THREAD

**Issue by Collision666** [WarEmu/WarBugs#18906]
**Expected behavior**

Bug done with a chosen
loading a build saved with +2 to path from souv gear.
edit : normally i have 3 points back to buy the skill.

**actual behavior**
Loading the build without 3 abilities point used for the skill (the loaded build use all the abilities points).
Edit : Not free but load with 5p souv --> Having a free ability without buying it from trainer.
The skill can be use and work.
Edit : The build is load without the need of the 6p bonus.

**Steps to reproduce the problem:**
Save a build who use 6p souv +2 to path bonus.
Start with a build who have the skill already taken.
load a build that need a +2 to path from souv gear without the +2 bonus set wear.
You still have the skill and can be use.

![bug report](https://user-images.githubusercontent.com/83250691/116157755-d111d980-a6ed-11eb-83f3-e1596c118586.jpg)

I hope my report is understandable, if not, I'm available when online for more information or stream the way to do the bug with discord.

Collision.

Edit : sorry for all the edit, first report done...

**Comment by dalen** [comment]
were you actually able to use it on enemies though? Test it out on a dummy or so.

**Comment by dalen** [comment]
Thanks for report. Fixed in the 2021-02-21 patch
