### ISSUE TITLE
My charater is slower on mount and without mount than others. 

### ISSUE THREAD

**Issue by Rndmprst** [WarEmu/WarBugs#18909]
hey, i noticed that my character is moving slower then others, and it has been like this since lvl 1, i tried on all diffrent mounts and the test i did is with my roomate, and we are on the same internet with about 19-20MS so there is no lag towards the server, i have no clue what is doing this, but its rly bugging my gameplay since i cant never outrun anyone and on slows it seem to be even stronger reduction, im estemating that this is about 7-10% slower than others but its very hard to tell. I hope this can see a Solution and it will help u find the reason for this 
**Expected behavior and actual behavior:**
Expet to move as fast as others :) 

**Steps to reproduce the problem:**
i have no clue here 

**Testing Screenshots/Videos/Evidences (always needed):**

https://www.youtube.com/watch?v=VYlqQzMVqQo

https://www.youtube.com/watch?v=mHk2EQ5ajjM

i hope u will see this and if u want to do an ingame test im willing to help with that aswell ! good evening

**Comment by Rndmprst** [comment]
bump?

**Comment by lilimx** [comment]
Hey,

this sounds like this issue  #19002 , so I will merge it.
