### ISSUE TITLE
Sentry / Echelon Choppa Great Axes (2hander)

### ISSUE THREAD

**Issue by mursie** [WarEmu/WarBugs#1890]
DPS value for these weapons is less than the DPS value for one handers.  Somehow these weapon values are way off.  In addition, there appear to be echelon and martial one handers that are available at renown levels lower than all other of that gear line (i.e. there is an echelon one hander for choppas at r25 when all others are r29.  Martial one hander available at r31 when all others are r34)

Biggest issue is the very out of wack DPS values for the 2h aces.

**Comment by Evildoor** [comment]
Orc Big Choppas DPS: #1424.
"Additional" onehanders: #1494.
