### ISSUE TITLE
Using Shattered shadows makes the game crash (using Linux + AMD GPU)

### ISSUE THREAD

**Issue by ttdm** [WarEmu/WarBugs#18905]
**Expected behavior and actual behavior:**
When Shattered shadows is casted, the game crash and wine report 
`wine: Unhandled page fault on read access to 000000B4 at address F7833EA7 (thread 0174), starting debugger...`

**Steps to reproduce the problem:**
On my side, I simply created a sorceress, leveled to the 8 and casted the spell. Each time the cast concludes itself, it crashes. 
This topic has been brought on the linux installation thread on the forum :https://returnofreckoning.com/forum/viewtopic.php?f=4&t=35023&p=477332#p477332
It has been suggested there that using an AMD GPU may be the cause. 
It probably also happen when others use the spells (crashes in scenarios with the same error message). I can group ingame with a sorceress to check if needed. 

**Testing Screenshots/Videos/Evidences (always needed):**
I'm not the only one who has reported this bug but if needed I can create a video evidence. 

I will have a bit of time during the following days to try some alternative actions if you have reasons to believe that the error is caused by my setup.

**Comment by xpander69** [comment]
Can't reproduce this with nvidia.
GTX 1080Ti 465.24.02 drivers
DXVK 1.8.1 
wine-staging 6.3 - 6.5

probably a GPU driver issue then. Ofc more people need to test this.

**Comment by fuzunspm** [comment]
same problem for me
amd 2600
5700xt
libva-mesa-driver 21.0.3-2 
lutris-5.7.11
dxvk v1.7.3L-03f11ba

I'm a returning player and this wasn't the case a year ago

**Comment by MaxHayman** [comment]
@fuzunspm The client hasn't changed since 2012 so if it was working fine a year ago its most likely a driver issue which broke it. I advise someone tries to find which driver version started causing this issue.

**Comment by fuzunspm** [comment]
@ttdm please add a comment or follow the issue from below link:

https://gitlab.freedesktop.org/mesa/mesa/-/issues/4725

**Comment by Natherul** [comment]
as per comment in the mesa thread, a new dxvk version seems to have it solved. After building it on my own system I do not crash anymore with shattered shadows on ooh shiny

**Comment by xpander69** [comment]
So, people who have this issue can you try

`WINPEREFIX=/home/yourname/Games/warhammer-online-return-of-reckoning winetricks dxvk`
should pull the latest 1.9 release

**Comment by xpander69** [comment]
I think this can be closed.
An regression in mesa drivers or dxvk most likely, not anything to do with RoR
