### ISSUE TITLE
New chars unable to gain renown after namechange wave-patch

### ISSUE THREAD

**Issue by BomblingTV** [WarEmu/WarBugs#18915]
**Expected behavior and actual behavior:**
When correctly pvp flagged in scenarios or orvr when defeating or taking part of an enemy being slaying you gain exp/orvr inf/rp.

**Steps to reproduce the problem:**
Create a char with a name that has been freedup after todays name-wave patch (28th arpil) and try to gain renown on a T1 char. You gain exp from killing players and orvr inf in orvr. but not rp.
https://media.discordapp.net/attachments/412718019425337366/837042280174452816/unknown.png
https://media.discordapp.net/attachments/329292495336767488/837056601583779860/unknown.png?width=873&height=676

Tried relogging, restarting the client, logging onto a destro toon and back to the bugged order toons, reloadui, and log on my main in t4 and could gain rp on him.
renown gain is somehow bugged on freshly created toons from todays patch, or somehow related to old names being used on new chars.

Steps done trying to narrow down the issue:
1) tried to relog, reloadUI etc. Then tried to get rp on an older char which worked fine.
2) tried to make a fresh char with a highly unlikely reused name (facerool keyboard letters) and get rp from T1 kill. no rewards
so it seems to be patch related and not related to the names as i first assumped.
3) I have my monthly rename cooldown not avaiable, othervice i would had tried renaming an older char and see if i swapped a reused name that was freed up from todays patch over on the older char, and see if the name prevented the old char from gaining rp. But couldnt test nor confirm this. Things seem to point towards it not being name related but a fresh lvl 1 creation issue from today.

Edit: Asked on official RoR about others having same issue. Got a response from a player who played in a group were all of them created fresh new toons today, and had the same issue as this.
Gamesbond tried logging on an already exsisting toon created 2 months ago and was getting renown.
so issue seems to be from created toons on todays patch, or a mix with the names that used to be taken, and are not on other characters.

**Comment by DpCrossland** [comment]
I also have this same issues Drizzen Blackgaurd

**Comment by DpCrossland** [comment]
Looks like mine is fixed, and it looks like It gave me all the renown points it wasn't showing while bugged.

**Comment by MaxHayman** [comment]
Great to hear
