### ISSUE TITLE
Whitemoon Manor PQ Broken: 1 of 3 Champions not attackable

### ISSUE THREAD

**Issue by Delegator2** [WarEmu/WarBugs#18911]
**Expected behavior and actual behavior:**

Whitemoon Manor (Dark Elf chapter 13 Normal PQ) seems broken on stage 3. At this stage you need to kill 3 champion level opponents, but one, Alanir Whitemoon, remains unattackable. Here you see me using Rend on the three normal adepts, and it isn't affecting the champ at all. I also tried melee attacks and taunt to no avail.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Screen Shot 2021-04-27 at 7 52 22 PM](https://user-images.githubusercontent.com/77587188/116326791-4aafd300-a793-11eb-9155-83edd2118a06.png)

**Comment by Delegator2** [comment]
Going through it again, Alanir Whitemoon is there at the start of the quest with the orange name but protected by a bubble. At the point where stage 2 is finished Alanir seems to respawn, still with the orange name, but also still not attackable.

**Comment by Lheana** [comment]
This has been fixed with the patch of 08/05/2021.
