### ISSUE TITLE
tactic not working after loading screen: Magus - demonic reach. Engi - throwing arm

### ISSUE THREAD

**Issue by bug-magus** [WarEmu/WarBugs#18914]
When you put the tactic in the slot, the range of the abilities is increased. However, when you join or leave an SC, the tactic resets (or not recognized) and the range of abilities normalizes. I have to change the alternative tactics set back and forth to activate the range increase.

**Comment by lilimx** [comment]
Hey,

Were you already lvl 40 at the time?

**Comment by lilimx** [comment]
maybe related to #18945

**Comment by lilimx** [comment]
Hey,

Im closing this ticket now, because there was no feedback. I already a possible related issue.
