### ISSUE TITLE
Chosen morale pump tactic internal cooldown doesn't match the description

### ISSUE THREAD

**Issue by Warmasta** [WarEmu/WarBugs#18928]
To begin with, I want to give a description of two tactics for pumping morale, the bork and the chosen.
![borkmorale](https://user-images.githubusercontent.com/47497345/116774772-7bc82600-aa67-11eb-942a-5d00d9e142ac.png)
![Chosenmorale](https://user-images.githubusercontent.com/47497345/116774779-7ff44380-aa67-11eb-844d-cb24335c2d45.png)

Based on the fact that the bork gets 4% (144mora) in about 3 seconds, and the chosen 200 in about 3 seconds, we can conclude that the chosen will accumulate m4 faster than the bork. Yes? In reality, bork accumulates M4 much faster than a chosen one. Based on this, I decided to test the tactics and clearly show the difference.
   I have attached links to video tests:
https://youtu.be/HfEYy1zkkoY    -  Chosen test
https://youtu.be/6GGc8-yBnqw   - Bork test

**Comment by Noronn** [comment]
They changed the ICD of these tactics to 10seconds a loooooong time ago but reverted them back to 3sec ICD as far as I know.
Looks like the chosen variant is still on 10sec ICD If you reach it in exactly 90 seconds.

**Comment by Warmasta** [comment]
Thanks for the comment. This is what I want to find out. Either the description is incorrect or the internal cooldown is wrong.
