### ISSUE TITLE
[WL]

### ISSUE THREAD

**Issue by RAEjarq** [WarEmu/WarBugs#18920]
**Expected behavior and actual behavior:**
Expected: Pack Hunting attack speed boost is on as long as you have the tactic equiped and activate trained to hunt. 
Actual: if you summon or release your pet or the pet gets killed, the attack speed boost goes away.

**Steps to reproduce the problem:**
On a white lion spec and equip the tactic Pack Hunting, then cast trained to hunt and summon pet - increased speed atack effect goes away.
Alternatively, with a summoned pet and Pack hunting buff on, remove pet - increased speed atack effect goes away.

**Comment by lilimx** [comment]
dublicate #18729
