### ISSUE TITLE
Some Party issues

### ISSUE THREAD

**Issue by Heyho18** [WarEmu/WarBugs#1892]
Hi,

A buddy and me were running in a party of 2 today. The problem started as both of us got disconnected from the server. From there on we had some trouble getting into another party because the server thinks we're still in party. Relog didn't fix it.

Here a brief overview of the issues:
- Party invite isn't possible with the message : Player is already in another party.
- I can join his party ( because he's the party leader ). As soon as i join his party i see him,myself and another version of myself in the ui.He doesn't see me though. Party chat,party queue,buffs and so on aren't working.
- He can invite another toon of mine and everything works fine. He although can't be loaded into another party.
- If we go offline the game shows us as still online.

I assume a server restart will fix the issue.

EDIT: Yes server restart solved it.

**Comment by Gobtar** [comment]
I think this is a symptom of the server issue, i.e Server treats disconnected player as still logged in, and can have multiple instances of that player exist as ghosts on the server.

**Comment by Tesq** [comment]
the old mythic server check the account and not the character, maybe is related to this, a force log out when the account is trying to log coulc prevent this in future maybe.

**Comment by Luth-RoR** [comment]
Should be fixed.
