### ISSUE TITLE
Everytime I log on my character is dead

### ISSUE THREAD

**Issue by Crewcop** [WarEmu/WarBugs#18933]
I log on and my character is dead it is unable to interact with any NPC's or items, but I am able to war report.
![crewcopx1](https://user-images.githubusercontent.com/76704195/116825718-a8566d80-ab4d-11eb-9171-d08095c99f66.PNG)

After using war report I am alive again
![crewcopx2](https://user-images.githubusercontent.com/76704195/116825719-a8ef0400-ab4d-11eb-8fba-3cf6623af649.PNG)

 log out to character screen, then log in again and ... I'm dead again.
![crewcopx3](https://user-images.githubusercontent.com/76704195/116825801-071be700-ab4e-11eb-8877-b2897c81b464.PNG)
Unfortunately war report is on cooldown, but if I can find somehow to zone I can get back alive again.  

I really like the character, but was considering just rerolling him again, but thought I would ask here first if it could be fixed.

Thanks.

**Comment by Psychoxell** [comment]
You tried it without your addons?

**Comment by Crewcop** [comment]
No I have not.  However every other character works with the addons on.

**Comment by lilimx** [comment]
Hey,

maybe try it with the default ui. Does the issue still persists?

**Comment by lilimx** [comment]
Hey,

I'll close this ticket now because the ticket creator did not respond.
If this issue still persist, please open a new ticket.
