### ISSUE TITLE
Fell Landing fortress zone not fireing

### ISSUE THREAD

**Issue by BomblingTV** [WarEmu/WarBugs#18931]
**Expected behavior and actual behavior:**
After Order locks Caledor Fell landing zone should open up as next active zone.

**Steps to reproduce the problem:**
After Order locked Caledor twice on first of may, it bugged out Fell landing both times, and despite Wargrimnir GM tried to open and lock some of the Elf T4 zones Caledor -> Fell landing didnt seem to trigger as active zone.

First Fortress attempt:
Stage1 fired and rams stopped working after getting gates to 30% and the for timer ran out
So no Rams for stage1 fortress were spawning and no reservations went out. 
Second fortress attempt:
The fortress didnt even fire as active zone

State of Realm Addon didnt show Fell landing to be an active zone.

**Comment by dalen** [comment]
fixed in patch
