### ISSUE TITLE
Zealot: Harbinger of Doom (ability) multiple bugs on log-in/zone change

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#1894]
1) When you log in and/or change zone the conversion from Willpower to Intelligence (and vice-versa) isn't being applied, at least not in the character stats window. The only way to get it to update is to toggle the ability on/off.

2) In addition to bug #1, when you change zone with HoD enabled you lose the glowing hands effect (the stats are still wrong as per #1). However, the ability is still "on" so when you press the ability icon for it (thinking it will activate HoD) it actually puts it on cooldown. If you change zone with HoD enabled you need to then toggle it off, wait for the 20s CD and then toggle it back on for the stats to be calculated properly.

Might be worth checking if this issue happens on character death as well (I have not tested this).

**Comment by RoR-Zomega** [comment]
Update: I used the flightmaster to go between two different zones on the same pairing (from Badlands to Black Fire Pass) with HoD enabled and the glowing hands + stats remained on/accurate. Previous testing (and the discovery of the bug) was going to and from the IC to different zones.

**Comment by ozarmidrashim** [comment]
Fixed the second of the two issues. The first is very low priority.

**Comment by RoR-Zomega** [comment]
Update: the 2nd of the two issues (glowing hands vanishes on travelling to a new zone but ability is still considered to be toggled on) is still bugged.
