### ISSUE TITLE
All The King's Men PQ Broken

### ISSUE THREAD

**Issue by Delegator2** [WarEmu/WarBugs#18942]
**Expected behavior and actual behavior:**

The All the King's Men PQ (level 40 Chaos Hard PQ) is stuck at stage 1 with 37/40 protectors killed, but no MOBs in the entire castle or area to make it progress.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Lheana** [comment]
Duplicate of #18794
