### ISSUE TITLE
PLZ STOP DIS

### ISSUE THREAD

**Issue by BFGka** [WarEmu/WarBugs#18949]
We can not a cap BO! Magus use buggs textures!
![image](https://user-images.githubusercontent.com/45288988/117133669-fa052f00-adbd-11eb-8a55-60cf0382a4c2.png)
TYVM!

**Comment by TVBrowntown** [comment]
No issue here. Anyone can walk up there.

**Comment by dalen** [comment]
open separate tickets for separate bugs. Write a description in the title
