### ISSUE TITLE
Bugged SE-RF regeneration for DoK-WP

### ISSUE THREAD

**Issue by Korthian** [WarEmu/WarBugs#18944]
Hello,

It seems that after logging and trying to change book or chalise to wp-dok class the passice SS-RF regeneration isn't working.
The only think you have to do if you wanna use your new offhand is to equip it and restart the game.

In the video i posted you can see the bug on WP. The same applies to Dok.

P.S. It has nothing to do with the item you equip. On dok i have both rrr61 chalise from sc and fort chalise. Starting the game with any one of them it bugs reg if you switch it. And if you sitch back to the starting item it worls again.

because the video is too big to upload here i will upload it to youtube and post a link on comments bellow

Thx

**Comment by Korthian** [comment]
Here is the link

https://www.youtube.com/watch?v=kWVLY4gyomM

**Comment by Rydiak** [comment]
https://github.com/WarEmu/WarBugs/issues/18782

Reported nearly every other week

**Comment by Lheana** [comment]
This has been fixed with the patch of 08/05/2021.
