### ISSUE TITLE
Bug in salvage

### ISSUE THREAD

**Issue by psykotropz** [WarEmu/WarBugs#18950]
Hello

I can't recycle items with my salvage skill. the window does not offer me anything .... the level is at 50% or more

My account is an old and my character is at level 42 in salvage

Help me please

![Capture](https://user-images.githubusercontent.com/31420001/117191900-65acc380-ade1-11eb-8050-752b3cc9c528.PNG)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. I will add it to a related issue.
