### ISSUE TITLE
Epic Quest: Conquering the Isle in Caledor, NPC Erisina Fireheart can not be found

### ISSUE THREAD

**Issue by Valashitel** [WarEmu/WarBugs#18952]
Erisina Fireheart needs to be killed as one quest objective but even after running around the whole area of Avethir public quest in WE stealth mode multiple times, i cannot find her.

**Expected behavior and actual behavior:**
Should be there in the area.

**Steps to reproduce the problem:**
Have a look for her at Avethir public quest area.

**Testing Screenshots/Videos/Evidences (always needed):**
<Due to the nature of the issue i dont think a screenshot would help.

Thanks for looking into the issue :)

**Comment by lilimx** [comment]
Hey,

thanks for your report. I will add it to a related issue.

**Comment by lilimx** [comment]
related to #16938

**Comment by Lheana** [comment]
I close this ticket as Erisina Fireheart can now be found, she is fighting but don't die anymore.
