### ISSUE TITLE
Can obtain more than one Sentinel Ring

### ISSUE THREAD

**Issue by b00nation** [WarEmu/WarBugs#18957]
**Expected behavior and actual behavior:**
Only one Sentinel Ring, should be buyable. 

I was in front of Bilewrought Burrow with my Dicipline of Khaine, had my sentinel ring inside my pocket. Then i saw that the vendor has the 3rd option still available. So i selected the Sentinel ring and it was put into my bag. Now i have two. 

**Steps to reproduce the problem:**
I think that u shoud'nt obtain the first two "prices", this somehow allows to multiple obtain the 3rd one.

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/25694121/117439850-a7e61a00-af33-11eb-8993-e57ca0354cef.png)
![image](https://user-images.githubusercontent.com/25694121/117440031-d82db880-af33-11eb-9f0f-fb70f62c8f08.png)

**Comment by bloodmasked** [comment]
You can only equip one so it doesn't matter
