### ISSUE TITLE
WE Bloodlust Bar

### ISSUE THREAD

**Issue by AkameSins** [WarEmu/WarBugs#18955]
Lately the Bloodlust points for WEs are buggy. Sometimes you attack enemies and points wont load, other times you spend them and they never disappear and sometimes you dont have any but you can use Frenzies. Please take a look into that. 

Thanks a lot.

**Comment by lilimx** [comment]
Hey,

could you provide some screenshots or better a video?

**Comment by AkameSins** [comment]
Yes I will try to take a snap and send it.

**Comment by lilimx** [comment]
Hey,

I will close this ticket now...(2 weeks ultimatium hits now)... Please open a new ticket, if you can bring a proper description and some screenhots.
