### ISSUE TITLE
Moving teleport scroll while porting leads to item loss

### ISSUE THREAD

**Issue by Sethjc** [WarEmu/WarBugs#18961]
**Expected behavior and actual behavior:**
Moving item in inventory while using portal scroll should not lead to removed item other then the used scroll.
Scroll seems to be tied to inventory slot, replacing the scroll with another item while porting will result in item loss other then the scroll.

In my case I replaced the scroll with my 60% mount to tidy up inventory while porting, resulting in the loss of the mout.

**Steps to reproduce the problem:**
1) Use teleport scroll
2) Replace the scroll with another item in your inventory
3) wait for the teleport to finish.

**Testing Videos:**
https://user-images.githubusercontent.com/83881050/117549536-3f826000-b03b-11eb-9700-8509e4bf46fe.mp4

**Comment by Sethjc** [comment]
It seems that this got fixed with the last patch.

**Comment by lilimx** [comment]
Looks fixed.
