### ISSUE TITLE
[Pets/Urgent] Follow/Stop position set to 100ft away from owner

### ISSUE THREAD

**Issue by Brutinho** [WarEmu/WarBugs#18965]
Pet follow/stop is set 100ft behind owner (at least when using range pets) 
Following video presents different scenarios in which the bug can be noticed
Occurred after Pet changes of May 8th's Patch

From https://github.com/TheRealJurki
After letting the squig attack he "freezes" in this position. Means: He is not chasing the enemy when he loses sight because of a wall nor would he attack from his new position when i call him back and let him attack again, he just runs into the old position from where he started his first attack.

Also it seems that the squig recieves full aoe dmg.

Also (and that is really old and you guys closed that topic as solved which it isnt): The (spiked) squig disappears sometimes randomly without reason and then appearing again with a cd on the squig type: but the squig isnt giving stats which might also cause that tactics which only work with an active pet dont work.

**Video:**
https://youtu.be/RNdHED1eoB4

**Comment by Teefz** [comment]
Please note that the following from above post, also affects other pet classes (WL, engi, magus) as far as i know:

_"Also (and that is really old and you guys closed that topic as solved which it isnt): The (spiked) squig disappears sometimes randomly without reason and then appearing again with a cd on the squig type: but the squig isnt giving stats which might also cause that tactics which only work with an active pet dont work."_ 

Ty!

**Comment by lilimx** [comment]
Fixed with Patch 22/07/2021
