### ISSUE TITLE
WL pet pathing issue in Black Fire Basin SC

### ISSUE THREAD

**Issue by Hekireki** [WarEmu/WarBugs#18967]
Only in Black fire basin, my WL pet never go for my targets call, he wanders off randomly, it's a big problem for ranked sc, maybe could you remove BFB from the rotation of SC for ranked if it takes too much time to fix it otherway

**Expected behavior and actual behavior:**
Expected : My pet should attack my target
Actual : My pet just run away from me and never touch my target, big pathing issue

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

thanke you for your ticket. I will add this report to a related issue.

**Comment by lilimx** [comment]
related to #18965
