### ISSUE TITLE
the tactic doesn't work for IB, the tactic "sweet revenge.

### ISSUE THREAD

**Issue by muraloo** [WarEmu/WarBugs#18966]
I conducted tests on targets, out of thirty strikes without tactics, there were ten crits, with tactics - twelve out of thirty. The test was conducted for about an hour. Please check the performance of the "sweet revenge" tactic.

**Comment by muraloo** [comment]
Yes, thank you

**Comment by bloodmasked** [comment]
30 is probably not good sample size. easy way to test would be to remove all of ur crit chance so you have 0% then test it and you should see obvious change or not.

use the training constructs because i think they have 0% chance to be crit(?)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. Please provide some screenshots of your test.

**Comment by lilimx** [comment]
Hey,

Im going to close this ticket now, because now proper evidence was brought.
If you are the opinion the issue still persists, please open a new ticket.

**Comment by muraloo** [comment]
Hey
ty
  
>Четверг, 1 июля 2021, 10:28 +03:00 от lilimx ***@***.***>:
> 
> 
>Closed  #18966 .
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Станислав Михайленко
