### ISSUE TITLE
Squig Pet teleports away from the herder when giving the attack order

### ISSUE THREAD

**Issue by TheRealJurki** [WarEmu/WarBugs#18969]
The Squig Pet teleports to another location when the Squig Herder is giving the attack order. Sometimes so far away, that its dying.

**Comment by xoonerbig** [comment]
Having the same issue.  Please fix this issue.   SH pet teleports away every time I attack a new target.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. I will add it to a related issue.

**Comment by lilimx** [comment]
related to #18965
