### ISSUE TITLE
T4 Dark elf epic quest

### ISSUE THREAD

**Issue by Dagreenboss** [WarEmu/WarBugs#18977]
Last stage after the champ kill and touching the " white doors " the quest dissapeared from my log, cant take it again, cant talk with the quest givers, its just gone.

**Comment by Lheana** [comment]
Screenshot of your quests in your Tome of Knowledge please. Also try to talk to Telior Windseer.

**Comment by Dagreenboss** [comment]
I have no quest so no screenshot, Telior Windseer gives nothing to me.

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: ***@***.***>
Enviado: jueves, 13 de mayo de 2021 16:52
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [WarEmu/WarBugs] T4 Dark elf epic quest (#18977)


Screenshot of your quests in your Tome of Knowledge please. Also try to talk to Telior Windseer.

**Comment by Lheana** [comment]
I am sure it is not a bug, you may be lost in the steps of the quest. What is the name of your char?

**Comment by Dagreenboss** [comment]
Dagreenboss, black orc. Im not lost in the steps, i had accepted the last step, the one where you can see the rewards. Thank you for your time.

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: ***@***.***>
Enviado: viernes, 14 de mayo de 2021 13:54
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [WarEmu/WarBugs] T4 Dark elf epic quest (#18977)


I am sure it is not a bug, you may be lost in the steps of the quest. What is the name of your char?

**Comment by Lheana** [comment]
According to the DB, you haven't even started the quest line "The Ebon Flame". This means you can start the epic quest from Fenrith Thaurgyn.
