### ISSUE TITLE
WE +15% Tactics

### ISSUE THREAD

**Issue by Cruella01** [WarEmu/WarBugs#18974]
Tested all 3 tactics (Taste of Blood, Masterful Treachery and Flanking)  in the city on training construct and turrets and none of them increase witchbrew damage.

**Comment by AkameSins** [comment]
Frenzied Mayhem works tho, thats weird.

**Comment by Haojun-Phalanx** [comment]
It's intentional.

**Comment by dalen** [comment]
General damage multipliers don't apply to damage procs, and Witch Brew is classed as a proc damage.

**Comment by AkameSins** [comment]
Taste of Blood is a general multiplier as long as its running so it should be working on WB, in case it doesnt.

**Comment by Cruella01** [comment]
> Taste of Blood is a general multiplier as long as its running so it should be working on WB, in case it doesnt.

I agree, it would have been nice to get a little extra damage out of the finisher. i have both WH and WE my WE has higher gear, sov and Walord and it doesnt do half the damage of my WH. witch brew 2100 for 6 attacks and have to stay in the fight meanwhile pop BAL on a squishy and its easy 5+k ive seen as high as 9k.
