### ISSUE TITLE
SW no quarter tactic

### ISSUE THREAD

**Issue by bernisroy** [WarEmu/WarBugs#18975]
SW no quarter tactic is not working properly. I have to take it out and put it back to activate each time. If I don´t do that in each sc for example, it's as if i don't have it.

Thanks.

**Comment by Haojun-Phalanx** [comment]
it's bugging if you are below 40.

**Comment by lilimx** [comment]
Hey,

thanks for your ticket. I will add it to a related ticket.

**Comment by lilimx** [comment]
dublicate/related #17950
