### ISSUE TITLE
Magus Pet Despawning 

### ISSUE THREAD

**Issue by rethmar** [WarEmu/WarBugs#18979]
**Expected behavior and actual behavior:**

Pet should not be despawning.

Magus Pet in the Havoc line  is despawning in Thunder Mountain Zone for the past week. It seems to happen at random at certain spots in the zone. Seems to happen a lot in front of Bloodfist Rock Keep.

**Steps to reproduce the problem:**

Tested while in zone over the past few days.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

I guess you wasn't lvl 40 atm? Could you confirm this?

**Comment by lilimx** [comment]
Hey,

I close this ticket now, because there was no feedback. If you are the opinion the issue still persists and you can bring proper evidence, please open a new ticket.
