### ISSUE TITLE
A Servant's Duel

### ISSUE THREAD

**Issue by Uchoo** [WarEmu/WarBugs#1897]
This quest, obtained from Chapter 12 Dark Elf, is to kill 20 Archmages. This quest does not give us any credit as we kill Archmages.

Part of the Stalker's set quests.

**Comment by genisaurus** [comment]
Fixed in next hotfix

**Comment by Ryanfawkez** [comment]
This quest is still bugged after the hotfix. Can't gain AM killcount in any way

**Comment by Evildoor** [comment]
According to #1990, quest is still broken.

**Comment by Novgoroth** [comment]
No new problem, the fix has not been implemented yet (dunno if the fix was done anyway)

**Comment by magter3001** [comment]
Still no fix as of yet.
