### ISSUE TITLE
Visual bug Warrior Priest Smuggler Hammer

### ISSUE THREAD

**Issue by Ghatisgob** [WarEmu/WarBugs#18976]
I did /rel and some log off/log in, the smuggler hammer makes this visual bug. Even in appearance the visualbug exists.
![Greabaz_012](https://user-images.githubusercontent.com/25305100/118114320-b6c34580-b3e7-11eb-9481-8d587ad36eb5.jpg)
![Greabaz_013](https://user-images.githubusercontent.com/25305100/118114324-b75bdc00-b3e7-11eb-9215-87c7da4ac96d.jpg)

**Comment by lilimx** [comment]
Hey,

due to the lack of information, I'll close this ticket now.
