### ISSUE TITLE
Squig Pet is randomly dying on attacking

### ISSUE THREAD

**Issue by TheRealJurki** [WarEmu/WarBugs#18970]
This bug occures independently from the pathing changes. That means fixing the problems i mentioned in another report on this side, this specific bug might still endure. I also reported it a long time ago and it got closed, but its still a thing, so youre welcome. 

-->The squig is randomly dying when giving the attack order because it gets teleported onto morrslieb.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
We already added your ticket to the pet-pathing issue ticket. 
If you're the opinion there is still something missing in ticket  #18965 (the main ticket, where we gather all pet-pathing issues) please feel free to create a new ticket with your research results.
