### ISSUE TITLE
Unable to Scavenge

### ISSUE THREAD

**Issue by hartmnj1** [WarEmu/WarBugs#1898]
I have the skill level to scavenge the enemies I am killing, but I do not see the flies or the wrench.

**Comment by geezereur** [comment]
I got the same bug I am unable to use Butchering.

**Comment by mursie** [comment]
Scavenging appears to be broken at the moment - I'm a 200 scavenger and no previously scavengable mobs are able to be scavenged

**Comment by Evildoor** [comment]
Should be working.
