### ISSUE TITLE
WE tactic bug ?

### ISSUE THREAD

**Issue by AkameSins** [WarEmu/WarBugs#18985]
Taste of Blood is a general damage boost for Witch Elf but it doesnt work with Witchbrew, nor with kiss of betrayal but it works for Wracking Pains and Envenomed Blade which is weird. I should be applied in kiss and Witchbrew as well if I am not mistaken.

**Comment by Haojun-Phalanx** [comment]
intended.

**Comment by AkameSins** [comment]
Should be changed imo, ToB is not like Flanking which is a positional damage multiplier. Its a general damage boost so it should work from auto attacks to Witchbrew and Kisses.

**Comment by lilimx** [comment]
Hey,

use the Suggestion & Feedbakc forum https://www.returnofreckoning.com/forum/viewforum.php?f=15 to propse a suggestion.
