### ISSUE TITLE
Rune Priest Swift  Runes

### ISSUE THREAD

**Issue by shaggy996** [WarEmu/WarBugs#18983]
Im not sure if this is technically a bug. 

The new ability RP receives at level 15 is the Swift Runes tactic to remove the cool down on Rune of Cleansing.
RP does not have Rune of cleansing at level 15. Its a dead tactic at the level you receive it.

**Comment by lilimx** [comment]
Hey,

that's true, you'll get the cleanse with lvl 16. If you want you can start a post in the Suggestion & Feedback section (https://www.returnofreckoning.com/forum/viewforum.php?f=15) so the balance team can think about your idea.
