### ISSUE TITLE
Not 40 in RvR at level 37

### ISSUE THREAD

**Issue by Fruk0st** [WarEmu/WarBugs#18982]
![not level 40 2](https://user-images.githubusercontent.com/77535151/118280970-016abd80-b4cd-11eb-939b-7a19891a17c7.png)
![not level 40](https://user-images.githubusercontent.com/77535151/118280105-2e6aa080-b4cc-11eb-98af-5baafddf0062.png)

When im joining RvR im going to level 40, but are going back to level 37 right after. so im not geting the level 40 buff. Not sure what hapend. :/ (se screenshot)

**Comment by lilimx** [comment]
Hey,

that sounds like the current debolster bug next to BOs or Keeps. I will add this to a related issue.

**Comment by lilimx** [comment]
dublicate / related to #18988
