### ISSUE TITLE
Bolster/de-bolster happening when entering/exiting BO/keep areas

### ISSUE THREAD

**Issue by aaearon** [WarEmu/WarBugs#18988]
**Expected behavior and actual behavior:**
When entering the RvR lakes as sub-40 you are bolstered. Around the BO/keep areas, debolstering/bolstering can also happen which makes game play tough mid-fight.

**Steps to reproduce the problem:**
Enter the RvR lake then go to one of the BO/keep areas. When moving around you will be continuously bolstered/debolstered even as you are already in the lake.

**Comment by L0hki** [comment]
Same here, starting having this issue since rank 37, didn't happen before and now it's non stop.

**Comment by TheOctagon322** [comment]
Yeah this extremely screws Which hunters and witch elves as well, since you can't go out invis and use openers because of bolster/debolster.

**Comment by HokoBugTracker** [comment]
tested it with a lvl 37 Swordmaster in Troll Country, but it also happened in other zones.

https://youtu.be/jbgRRnRyvJA

https://ibb.co/9hc2GVv

**Comment by Excal90** [comment]
Seems to be joining SC's is what causes the bolster issue at the point to where you stop bolstering to 48 in the orvr lakes. Relogging fixes the issue until you join another SC and then it starts happening again.

**Comment by Sorkhatani** [comment]
Still happening.
Seem to happen most often in door/gateway type areas. 
It hit me 6-7 times running from WC to Headwall in TM yesterday.
Today, it happened 5-6 times from the WC to the Wilhem's Fist keep in reikland.
[
![Sorkhatani_002](https://user-images.githubusercontent.com/46400285/121010339-5a650300-c7a6-11eb-9089-5e236b11c03c.jpg)
](url)
[
![Sorkhatani_003](https://user-images.githubusercontent.com/46400285/121010354-5fc24d80-c7a6-11eb-9b46-905533831b0b.jpg)
](url)
[
![Sorkhatani_004](https://user-images.githubusercontent.com/46400285/121010376-651f9800-c7a6-11eb-9927-89dda0584ce4.jpg)

](url)

**Comment by xpander69** [comment]
yeah confirming.. this only happens after ypu played 1 scenario, relog works around it

![ss_10062021_21 04 47](https://user-images.githubusercontent.com/1345116/121586760-b052d880-ca3c-11eb-849b-f712d94c5018.png)
switches on and off near the BO's, causing framespikes and all the weird issues

**Comment by Rydiak** [comment]
Happening at rank 36 on my SM.  Bolster is actually not applying either. It immediately drops me from rank 40 to rank 36.

**Comment by Kaelang** [comment]
@MaxHayman this is separate to the issue we looked at on Discord (and was subsequently fixed). This occurs after a T2 player completes a scenario.
