### ISSUE TITLE
Marauder Tactic broken

### ISSUE THREAD

**Issue by Nikademon** [WarEmu/WarBugs#18989]
Hulking Brute tactic not working

Edit: This is is the origin message....hidden in stuff to comment out text parts.

**Comment by bloodmasked** [comment]
you didnt write anything

**Comment by Nikademon** [comment]
Hulking brute tactic was not working

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Getku** [comment]
Hulking Brute doesn't give the initiative.  Do you need video evidence also? I have attached 2 photos
![HulkingBrute_With_Brutality](https://user-images.githubusercontent.com/51135236/119690030-024b0a00-be52-11eb-98e5-33a0c7bf3988.jpg)
![HulkingBrute_With_Monstrosity](https://user-images.githubusercontent.com/51135236/119690051-070fbe00-be52-11eb-8a76-f30cf4f3b7af.jpg)

**Comment by xpander69** [comment]
does .getstats show the change?

**Comment by Getku** [comment]
I confirmed it. It is visual bug = .getstats shows that it gives the initiative!

xpander69 thank you for your help.

**Comment by Civek** [comment]
Problem still exists. It still shows no bonus from initiative.

**Comment by lilimx** [comment]
Hey,

as Getku wrote, it's just visual, the stats are correct.
![grafik](https://user-images.githubusercontent.com/23266079/128297023-ac2d1c3c-ccaf-4c00-a0cf-19f1d7304fdf.png)

Please use .getstats and don't write in tickets to remember devs to check on issues.
