### ISSUE TITLE
Kadrin Valley. The Sealed Tower PQ - Stage 3 (Easy)

### ISSUE THREAD

**Issue by Vizio101** [WarEmu/WarBugs#18995]
To be able to complete Stage 3 of PQ.  On stage 3 there are two champions to kill.  First one works but the second champion "Raider Lobethys" cannot be attacked.

I tried logging out and in, closing client, using aoe hoping to get aggro, nothing worked.  Repeated the PQ after it reset with same results.

**Testing Screenshots/Videos/Evidences (always needed):**
![Tanithil_001](https://user-images.githubusercontent.com/66458029/118387209-f3529500-b5d1-11eb-9fff-736fbde1f4b2.jpg)

**Comment by xpander69** [comment]
should be fixed with the patch from 20/05/2021

feel free to comment if its still an issue
