### ISSUE TITLE
T1 Elf Epic Quest Among the Shadows

### ISSUE THREAD

**Issue by Ramessu** [WarEmu/WarBugs#18999]
According to the Wiki here: https://wiki.returnofreckoning.com/index.php/High_Elf_T1_Epic_Quest_Among_the_Shadows
I completed Step 7, but cannot advance. I completed Steps 8, 9 and 10 in game and nothing happens. The Quest Tracker remains at Step 7 complete and I can't turn it in after completing the next steps. Thank you in advance for any help with this issue.

**Comment by Lheana** [comment]
Have you tried interacting with the 'Ley Line Map' again?

**Comment by Ramessu** [comment]
Thank you for your help. As I noted in my other issue, "Golden History" I needed to wait for the item to reset before I could click it again and complete the quest. Sometimes you have to click the item in the quest item tab of you backpack and sometimes you have to click the actual item itself after it resets to complete. Again, thank you very much for your help. This will be very helpful to me in completing future quests where the completion isn't as simple as returning to the quest giver.
