### ISSUE TITLE
Range Squig not reliable, totally bugged and recieves full aoe dmg

### ISSUE THREAD

**Issue by TheRealJurki** [WarEmu/WarBugs#18990]
After letting the squig attack he "freezes" in this position. Means: He is not chasing the enemy when he loses sight because of a wall nor would he attack from his new position when i call him back and let him attack again, he just runs into the old position from where he started his first attack. 

Also it seems that the squig recieves full aoe dmg.

Also (and that is really old and you guys closed that topic as solved which it isnt): The (spiked) squig disappears sometimes randomly without reason and then appearing again with a cd on the squig type: but the squig isnt giving stats which might also cause that tactics which only work with an active pet dont work.

**Comment by xpander69** [comment]
video from other bugreport:
https://www.youtube.com/watch?v=RNdHED1eoB4
https://github.com/WarEmu/WarBugs/issues/18965

**Comment by GamesBondd** [comment]
#18965
