### ISSUE TITLE
Shaman ability 'Ere We Go! proc is stacking with other Shamans using the same ability.

### ISSUE THREAD

**Issue by Brizhul** [WarEmu/WarBugs#18994]
I ran into a party of shamans, and they were stacking their 'Ere We Go! ability to get a total of 6 procs of the ability per shaman (without including the tactic, Ere We Goes Again, to proc extra times) whilst using their instant channeled damage ability Bunch o' Waaagh (just doing some quick math, if one 'Ere We Go! proc is doing about 200 damage, that's about 1200 damage per damage tick, per shaman.. 7200 instant damage in total. That's just an example, this issue could potentially do more than that).

**Expected behavior and actual behavior:**
I would expect that the ability 'Ere We Go! does not stack with other shaman's using the same ability. Instead, it does stack with other shaman's using the same ability, causing an insane amount of damage instantly.. Could potentially one shot a player (Like it nearly did to myself).

**Steps to reproduce the problem:**
1: Make a party of shamans.
2: Have all shamans use 'Ere We Go!.
3: Have any shaman in the party use a damage ability on an enemy player (Bunch o' Waaagh, for example).

**Testing Screenshots/Videos/Evidences (always needed):**

![](https://cdn.discordapp.com/attachments/839077184748257311/843326816969555978/unknown.png)

![](https://cdn.discordapp.com/attachments/839077184748257311/843326949966479401/unknown.png)

![](https://cdn.discordapp.com/attachments/839077184748257311/843327122289590303/unknown.png)

**Comment by Brizhul** [comment]
These particular shaman are knowingly abusing this issue btw.

**Comment by bloodmasked** [comment]
Being attacked by the same ability 4 times is not a bug

**Comment by Brizhul** [comment]
Whether or not it's a bug, it doesn't matter.. I doubt it's meant to be working in this manner.. It's like if WP/DoK auras were 100% chance to proc instead of their usual chance to proc... I'm just surprised that the majority of the community doesn't see an issue with this.

But whatever.. After a year of trying to help make the game fair for everyone, I honestly give up.

**Comment by Brizhul** [comment]
Also, just curious.. Why are you defending something with no facts to back it up? I'd expect someone from the ror team to be commenting, not someone who's credentials consist solely of a bias, destro pov.
