### ISSUE TITLE
No guards for Mourkain Temple Spawn

### ISSUE THREAD

**Issue by vikingofmars** [WarEmu/WarBugs#18993]
Mourkain Temple destro spawn is lacking guards or they're malfunctioning or something because this WL was doing ballet on our spawnpoint
![white lion dancing in our spawn](https://user-images.githubusercontent.com/37393516/118382079-9d74f180-b5bf-11eb-8544-2e4568a63710.jpg)

**Comment by Lheana** [comment]
Is it ranked sc?

**Comment by vikingofmars** [comment]
No it was weekend event sc
