### ISSUE TITLE
Shaman's 'Ey Quit Bleeding doesnt increased Gork mechanic when used on youself

### ISSUE THREAD

**Issue by maxonian** [WarEmu/WarBugs#19009]
Expected result: Casting Ey Quit Bleeding increases shamans Gork mechanic when used on yourself

Actual result: Casting Ey Quit Bleeding does NOT increase shamans Gork mechanic when used on yourself

https://user-images.githubusercontent.com/74731579/119023063-02f32480-b9aa-11eb-86dd-07e67d2a90f1.mp4

**Comment by NabaroNya** [comment]
I confirm. Also Ey' Quit Bleedin' does not applies to two additional allies if the target is you

**Comment by Schett** [comment]
Can confirm this is also the case on AM, even hotting allies don't change your High Magic 80% of the casts
