### ISSUE TITLE
WL: pet get dismissed when pouncing

### ISSUE THREAD

**Issue by tomaslumba** [WarEmu/WarBugs#19004]
**Expected behavior and actual behavior:**
On WL when pouncing to and enemy and there is even a small high difference pet get dismissed (get the to far away messege) this occurs even when pouncing over a gap and the pet go below for a second - like in shadowlands on the path east of the SS BO.

**Steps to reproduce the problem:**
Pounce in geography with heigt difference.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by tomaslumba** [comment]
Any input for this issue?

**Comment by lilimx** [comment]
Hey,

could provide a video?

**Comment by lilimx** [comment]
Hey,

I will close this ticket now (2 weeks ultimatium hits now). Please open a new Bug Tracker ticket if you can provide a proper description and some screenhots.
