### ISSUE TITLE
Appearence Bug on Chosen cloaks

### ISSUE THREAD

**Issue by Nekkbraka** [WarEmu/WarBugs#19006]
All sov , warlord , triumphant , victorious cloaks are bugged and dont change appearence when i put another model.  Happening on other players too:
![Sevverus_105](https://user-images.githubusercontent.com/47920948/118828836-fed4e300-b893-11eb-89e2-ab1fb129dc9f.jpg)

And the right triumphant/Victorious model just to clarify the bug:
![Sevverus_107](https://user-images.githubusercontent.com/47920948/118829357-70149600-b894-11eb-9ded-abdeee4e4c56.jpg)

Only i can see my model appearence:
![Sevverus_106](https://user-images.githubusercontent.com/47920948/118829009-24fa8300-b894-11eb-8f87-191b0d5af23c.jpg)

A quick interview whit another player about it:
![bug 1 cloak](https://user-images.githubusercontent.com/47920948/118829502-8de1fb00-b894-11eb-963b-486995337b51.jpg)

**Comment by lilimx** [comment]
Hey,

thanks for your ticket. I will add it to a related issue.
#18556
