### ISSUE TITLE
Witchhunter/Witchelf Stealth Cooldown

### ISSUE THREAD

**Issue by waerter** [WarEmu/WarBugs#19013]
The Cooldown of the Wichhunter ability Incognito is only 5 Seconds. Should be 30.

**Steps to reproduce the problem:**
Enable and disable Incognito on any Witchhunter

![Randro_001](https://user-images.githubusercontent.com/62266826/119037540-641ef600-b9b2-11eb-9deb-49a6ac23cc62.jpg)

**Comment by waerter** [comment]
Same for the Witchelf Ability Shadow Prowler
![Rindarel_003](https://user-images.githubusercontent.com/62266826/119047762-9f272680-b9be-11eb-9818-b70ede0c10df.jpg)

**Comment by waerter** [comment]
It appeares to be fixed.

**Comment by xpander69** [comment]
seems to be fixed, closing
