### ISSUE TITLE
texture abuse

### ISSUE THREAD

**Issue by BFGka** [WarEmu/WarBugs#19019]
![image](https://user-images.githubusercontent.com/45288988/119093781-90c22480-ba29-11eb-95d9-5f6b15a9549a.png)

This man sit under stairs and spam dragon gun! Nice player!

**Comment by Lheana** [comment]
If you want to report a player, please make a report to the GMs. Bugtracker is for bugs, and except if you give information about how to be under the stairs, there is nothing we can fix here.
