### ISSUE TITLE
No guilds shown in the recruiting panel

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#19029]
**Expected behavior and actual behavior:**

When you bring up the Guild window when not in a guild, the game brings up the "Not in a Guild" window. This window is supposed to show a list of recruiting guilds but currently that list is empty for both Order and Destro. I haven't played for a year so there is a slim chance that somehow nobody is recruiting anywhere but I think this might be a bug.

**Steps to reproduce the problem:**

1) Log in to a character not in a guild
2) Bring up the Guild window (default keybind is "G").

**Testing Screenshots/Videos/Evidences (always needed):**

Order (guildless rank 14 char):

![image](https://user-images.githubusercontent.com/60266177/119201826-89316880-ba87-11eb-962b-9889213364fe.png)

Destro (guildless rank 40 char):

![image](https://user-images.githubusercontent.com/60266177/119201938-bb42ca80-ba87-11eb-9ba7-3f03033be1ec.png)

**Comment by xpander69** [comment]
Is this still an issue? I checked today and it seemed to work fine for me. Both destro and order. Destro side rank 40 char and order side rank 23 was checked.

**Comment by xpander69** [comment]
ok yeah its still an issue... the previous report was with chars that i left my current guild. then it showed up nicely but with chars that don't have guild to begin with or after relog, the guild search is empty indeed.

![ss_30052021_13 01 33](https://user-images.githubusercontent.com/1345116/120100044-594d2980-c147-11eb-8451-ab59eb97bfcd.png)

**Comment by FrostKota** [comment]
Forgot if this feature was exclusively cause I had addons loaded or what not, but using the / command "/reload" fixed this issue for me whenever I came across this. Don't recall if the command "/reload" was from an addon cause I recently picked up ROR again. but it's worth a shot to try and fix this issue for players who are really trying to join guilds.

**Comment by zulnam** [comment]
Can confirm this is still an issue. As long as the character you are checking on is not in a guild.

STR:
1. Connect to the server using guildless char.
2. Press the shortcut for the guild tab (default G).

Note: doing a /rel with the tab open (not sure if required) does indeed fix the issue for that session.

**Comment by lilimx** [comment]
fixed with patch [10/09/2022]
