### ISSUE TITLE
Black Orc Tactic - Loudmouth bugged

### ISSUE THREAD

**Issue by Narancse** [WarEmu/WarBugs#19025]
Hi,

After the recent patch on my Black Orc the loudmouth tactic is being invisibly equipped, Like having a 5th tactic slot, I was not able to replicate the same issue with other tactics.

Expected behavior and actual behavior: 
1 Equip Loudhmouth tactic, 
2. Remove Loudmouth tactic from the active tactics.
3. Loumouth will still do dmg.

Steps to reproduce the problem:
1. Step 1 Equip loudmouth.
2. Remove Loudmouth tactic from the active tactics.
3. Equip any other tactic.
4. Both combat log and Ui shows that loudmouth is still doing dmg. (see screenshots below)

Testing Screenshots/Videos/Evidences (always needed):
![Chuckz_088](https://user-images.githubusercontent.com/25580920/119128008-5d859280-ba35-11eb-8fb9-c1a5fa50626d.jpg)
![Chuckz_089](https://user-images.githubusercontent.com/25580920/119128021-62e2dd00-ba35-11eb-96b3-d9189b289aa4.jpg)
![Chuckz_090](https://user-images.githubusercontent.com/25580920/119128061-6d9d7200-ba35-11eb-8aa3-e90d4408ad88.jpg)
![Chuckz_091](https://user-images.githubusercontent.com/25580920/119128082-75f5ad00-ba35-11eb-986b-6bb08807484f.jpg)

**Comment by radchu** [comment]
@lilimx this is fixed with patch 17/11/2022 just like https://github.com/WarEmu/WarBugs/issues/20072
