### ISSUE TITLE
WH bug

### ISSUE THREAD

**Issue by Naelar** [WarEmu/WarBugs#19020]
**Expected behavior and actual behavior:**
Supposed to be a 30s cooldown, but was only a 5s cooldown

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![2021-05-21](https://user-images.githubusercontent.com/61371494/119094984-52037e80-b9d7-11eb-9127-fe41937184c7.png)

as you can see, i haven't dropped out of stealth yet, have clicked it off, and it has a 5s cooldown.  I tried a couple times, but was unable to capture the 30s cooldown / transition to 5s.

**Comment by waerter** [comment]
Duplicate to #19013

**Comment by xpander69** [comment]
seems to be fixed, closing'
feel free to comment if its still an issue
