### ISSUE TITLE
[Witch Elf] - Bugs/Fixes/Changes

### ISSUE THREAD

**Issue by AkameSins** [WarEmu/WarBugs#19037]
~ The default bloodlust counter seems to be broken ? Sometimes I have bloodlust but they dont appear, other times u spend all bloodlust but they are still there, no idea whats the cause of it.

~ If you have 5 bloodlust and you use the Shadow of Elixir to stealth and use an opener which adds 2 bloodlust, ur bloodlust resets to 0, idk if its intentional but it makes no sense :o It should just stay on 5 and not get reset.

~ The disappearance of the cooldown on abilities without a global cooldown, such as elixir of shadows or feinted position needs to be fixed as well.

**Comment by lilimx** [comment]
Hey,

please one issue per ticket and proivde some pictures or videos. 
If you want to discuss about some changes, please use the Suggestion & Feedback forum: https://www.returnofreckoning.com/forum/viewforum.php?f=15
