### ISSUE TITLE
DoK starter skills wrong.

### ISSUE THREAD

**Issue by 10pennynail** [WarEmu/WarBugs#19033]
I created a DoK this morning and the only melee skill was consume essence. I restarted client to check and same issue.

**Comment by Rydiak** [comment]
Not a bug.

- Cleave Soul Add scaling armor ignore up to 660 at R40 from behind. **Raise minimum level to 6 and swap Consume essence to R1.**

This is a relatively small buff that will primarily be used with DPS specs at higher tiers of play. With the limited range of abilities, we felt it was safe to move this out of the R1 basic spammable to give DPS spec an additional tool that rewards good positioning. The armor scaling is less than WL Sundering Chop, but similar in concept. Moving the basic lifetap to R1 represents the class best, but also makes it a bit clunky to maintain SE during combat during very early levels. In our this has not been unsustainable though, and you quickly get more abilities to generate SE.

**Comment by 10pennynail** [comment]
My mistake. I didn’t realize how early “early” was. Sorry to bother!
