### ISSUE TITLE
Golden History, (Travel Quest)

### ISSUE THREAD

**Issue by Ramessu** [WarEmu/WarBugs#19030]
Hello, I am not able to turn in the quest, Golden History. It states to turn in to Thesoryn Shadowseer in the Chapter 5 Elf Camp in the Shadowlands. There is no marker to locate the quest turn-in and clicking on the quest giver does nothing. Please see the attached image. Thank you.
![Untitled](https://user-images.githubusercontent.com/84376715/119204454-76a53800-ba63-11eb-94d2-74f15ac0d080.png)

**Comment by Lheana** [comment]
The quest finisher is the GameObject Histories of Aenarion, so click on it.
I have a fix for next patch because the completion of the quest is not proposed when clicking on it to loot the item.

**Comment by Ramessu** [comment]
Thank you. I noticed that after you click it to obtain the item, you have to wait for it to reset before you can click it again and complete the quest. I've noticed that some other quests require the same process. So, this has been very helpful to me. Thank you very much.
