### ISSUE TITLE
WL tactic Baited Trap

### ISSUE THREAD

**Issue by Pearlpetalbee** [WarEmu/WarBugs#19031]
White Lion The mastery abilities, Guardian, a tactic called baited trap, 
Problem: without any description, no sure what it is?

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Zomega-WAR** [comment]
![image](https://user-images.githubusercontent.com/60266177/134787051-29fb8e4e-4e84-481f-b5f6-16cefe44403d.png)

Secrets has tested and it just seems to be a tooltip issue. The tactic is working.

**Comment by zulnam** [comment]
Can confirm tactic description is still missing.

STR:
1. Log WL.
2. Go to a career trainer.
3. Mouseover Baited Trap tactic in Guardian Mastery.

ACT: Tooltip is missing everything except title and "Buff" status in top-right.

**Comment by SecretsOTheP** [comment]
Fixed for next client patch.
