### ISSUE TITLE
The Price of Survival, in Ellyrion

### ISSUE THREAD

**Issue by Ramessu** [WarEmu/WarBugs#19032]
Quest Waypoint: Kill Karthrian Sedt.

This NPC is not located on the map in this area. I searched for a long time and couldn't find the kill target.

**Comment by Lheana** [comment]
Duplicate of #16938
Karthrian Sedt was a bit far from his normal location. I killed him and he is back - for now - to his place.

**Comment by Ramessu** [comment]
Thank you. I was able to complete the quest with your help.
