### ISSUE TITLE
Quest Like Clockwork in IC - Questmob spawning behind wall

### ISSUE THREAD

**Issue by IIxGH0STxII** [WarEmu/WarBugs#19043]
The Chaos Creature in IC for the quest "Like Clockwork" spawns behind the wall leading down to Prophetess Zera instead of inside the courtyard and is not reachable / attackable. 

![Krexos_003](https://user-images.githubusercontent.com/25819236/119489844-a7c78600-bd4b-11eb-85f5-67354578e917.jpg)
![Krexos_004](https://user-images.githubusercontent.com/25819236/119489851-a9914980-bd4b-11eb-9682-b9db2d107cee.jpg)
![Krexos_005](https://user-images.githubusercontent.com/25819236/119490315-3a682500-bd4c-11eb-8b7e-dc95e133044d.jpg)

**Comment by Lheana** [comment]
Duplicate of #16938
