### ISSUE TITLE
SW tactic No Quarters

### ISSUE THREAD

**Issue by lolka4144** [WarEmu/WarBugs#19044]
Hi!
Shadow Warrior tactic "No quarter" stops working randomly, even during fights. 
To make it work again, you have to remove it, than choose again.

**Comment by lolka4144** [comment]
Figured out it happens after every zone "loading", when u cross certain points on map

**Comment by lilimx** [comment]
Hey,

thanks for your ticket. I will add it to a related ticket.

**Comment by lilimx** [comment]
dublicate/related #17950
