### ISSUE TITLE
Contributing lag source? Opposing faction appearance now visible

### ISSUE THREAD

**Issue by Mizrim** [WarEmu/WarBugs#1904]
Since t3 went live it seems to me that we can now see the opposing factions appearance customisation which if correct (my eyes may of been deceiving me but I'm pretty sure I have seen plenty of BQ helms for example on Destro toons) is bound to cause problems. I'm sure this wasnt itentional but hopefully this observation may help :))

**Comment by Evildoor** [comment]
1) It was this way before T3.
2) I'm pretty sure this was intentional. Many players wanted their appearance to be visible to everyone.
3) I don't see how this "is bound to cause problems".
