### ISSUE TITLE
Player is unable to queue for Ranked Solo Scenario

### ISSUE THREAD

**Issue by krag123** [WarEmu/WarBugs#19041]
**Expected behavior and actual behavior:**
Player is unable to queue for Ranked Solo Scenario. Getting message: You have been blocked for queueing Ranked Solo Scenario. This problem impact all characters on my Account. Kragironfist and Snorrisonn
Player should be able to queue for Ranked Solo Scenario if requirements are met.
Issue has been reported to multiple GMs ingame, and i was asked to create a bug for it us they can't see nothing in my logs.

**Steps to reproduce the problem:**
1)Log on charracter meeting requirements for Ranked Solo Scenario
2)Try to sign up for Ranked Solo Scenario
3)Observe the effect

**Testing Screenshots/Videos/Evidences (always needed):**

![Zrzut ekranu (1174)](https://user-images.githubusercontent.com/84721765/119354879-df2f2780-bca4-11eb-88cf-5456c8f549a7.png)

**Comment by xpander69** [comment]
Still an issue for your accounts?

**Comment by krag123** [comment]
Yes. I have just checked. 
![image](https://user-images.githubusercontent.com/84721765/119816849-7f778d00-beed-11eb-884c-823c35c20414.png)

**Comment by GamesBondd** [comment]
Hello, I will look into this and get back to you as it might have been manually triggered by mistake.

**Comment by Edoamar** [comment]
I have the same issue

**Comment by krag123** [comment]
Will be gratefull.

**Comment by GamesBondd** [comment]
> Will be gratefull.

After looking into it, it wasn't really a bug. You were intentionally blocked from queueing for Ranked for a month (minus 3 days) due to intentionally trolling and grief.

Since this isn't a bug, I'll close it. Feel free to contact me on Discord if you want to.

**Comment by krag123** [comment]
Thanks for info.

**Comment by krag123** [comment]
What is your discord details if i may ask?
