### ISSUE TITLE
The doors are not opening

### ISSUE THREAD

**Issue by KingEliphas** [WarEmu/WarBugs#19059]
Hello, The reason of this latter is that I can't open the tavern door in Talabecland ( chaos chapter 10 ) in order to talk with the person who is inside the building to claim my rewards for my mission. Also I have same issue in Talabecland  with the door, to get close with the "Mourning Bell" so I can ring it and complete the mission. 

Please help me. 

Best Regards,  Otar

![Emzar_005](https://user-images.githubusercontent.com/85014828/120065520-c1860780-c082-11eb-94cc-92553881150a.jpg)
![Emzar_004](https://user-images.githubusercontent.com/85014828/120065524-c5198e80-c082-11eb-96a9-5a1431c8e59f.jpg)
![Emzar_000](https://user-images.githubusercontent.com/85014828/120065529-ca76d900-c082-11eb-8dba-94ce549a6a97.jpg)

**Comment by lilimx** [comment]
Hey,

thx for your ticket, A fix is already pending.

**Comment by lilimx** [comment]
related to #19055
