### ISSUE TITLE
Report of spot where it's easy to get stuck at.

### ISSUE THREAD

**Issue by Lanzapalillos** [WarEmu/WarBugs#19050]
**Expected behavior and actual behavior:**
When being thrown off or sliding off the wall at Reikwald fortress, one gets stuck behind a tent that is badly placed, it should be moved so one can get out of there otherwise the only solution is getting unstuck via command and losing the fort entrance ticket.

**Steps to reproduce the problem:**
Head to reikwald fortress wall, at 24030/9728 and slide down the wall so one falls behind this tent. 
(or be pushed down here by any of the knockback abilities in the game)

Easy solution would be to move the tent a bit so one can walk out of that spot.

**Testing Screenshots/Videos/Evidences (always needed):**

![stuck](https://user-images.githubusercontent.com/84939342/119899560-88934900-bf43-11eb-8878-5007b6161c47.jpg)

**Comment by GamesBondd** [comment]
These spots aren't bugs and we would need to modify the terrain or add invisible walls to make sure that you don't get stuck. Alternatively, you will have to get used to avoid such locations by not allowing enemies to punt you there.
