### ISSUE TITLE
Login difficulties

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#1905]
One of my characters (sorc Xheevah) has troubles logging in for last 2 weeks. I have 5 characters on Destro, the other 4 always have instant login, but when I try to log my sorc I get the loading screen from the zone where I played last, and then Im thrown back to character selection. Any hints/tips?

EDIT: I just logged in my DoK, I check guildroster, and I see my Sorc is online :-S

**Comment by Evildoor** [comment]
Closing since #1911 has slightly more information about the issue.
