### ISSUE TITLE
Influence gain for city dungeons on order correct?

### ISSUE THREAD

**Issue by Rogots** [WarEmu/WarBugs#19066]
Hi all,

yesterday and today I went to C&T with my RP (Rogi) and my WH (Rogio). As far as I know, one run of city dungeons is worth 7k influence while the first run is 8k (might be wrong). However, I received significantly less influence (5k on WH) for my runs now.

Is my information about influence gain wrong and if so, what is the correct influence gain? Or is there something wrong in game?

Thank you in advance for any information.

Rogi

**Comment by xpander69** [comment]
This is not really a bugreport but more a question it looks like? can you remember if you used stealth in there a lot? maybe that can trigger the issue? the other people on the group got normal amounts? and you were in distance all the time?
