### ISSUE TITLE
My WP gets spawned next to a healer NPC when I log in

### ISSUE THREAD

**Issue by wewso** [WarEmu/WarBugs#19068]
**Expected behavior and actual behavior:**

One of my characters a WP get respawned next to a healer NPC every time I log in. 

I get teleported even if I was in the other side of the zone.

**Steps to reproduce the problem:**

Log off > log In > I get teleported to a healer NPC.

**Comment by lilimx** [comment]
Hey,

could you add a bit more information. Where? When? Why? a few screenshots would help a lot :D

**Comment by wewso** [comment]
Hi, I recently discovered that it doesn't always teleport me.
I will try to recreate the problem and I get back to you.

**Comment by lilimx** [comment]
Hey,

I close this report now. When you find evidence to reproduce this issue, just create a new ticket.
