### ISSUE TITLE
NPC not attackable in DE ch3 PQ Gon Seraph

### ISSUE THREAD

**Issue by Skibbas** [WarEmu/WarBugs#19063]
The lions in "gon Seraph" stage 2  are not attackable, and as the other npc's during this stage doesnt respawn the quest cannot progress.

The lions do not aggro and are not in any way attackable.

Video: https://youtu.be/-SvrFlzg4pE

**Comment by lilimx** [comment]
Hey,

could you provide some screenshots or a short video?

**Comment by Skibbas** [comment]
Will do, can fix that later tonight :)

**Comment by Skibbas** [comment]
Video up in the main post! :)

**Comment by GamesBondd** [comment]
> Video up in the main post! :)

Thanks 👍
