### ISSUE TITLE
Improved Flee not always lasting 15 seconds

### ISSUE THREAD

**Issue by bloodmasked** [WarEmu/WarBugs#19060]
Improved Flee 1 makes flee last 15 seconds instead of 10.

Sometimes flee lasts 15 seconds and other times only 10, with the renown specced.

It should always last 15 seconds when specced.

**Comment by xpander69** [comment]
is that "sometimes" totally random?, like when you are using them in one zone with succession it just comes with 10 and 15 sec randomly? or is it after switching zone or near BOs or something when it fails to be 15 sec?

**Comment by bloodmasked** [comment]
I think when it stops working, it stops working forever until you respec.

Even if I relog, it still is only 10 second and not 15.

I tested what you said about switching zones: Respecced at IC, tested flee and it worked for 15 second, then flew to dragonwake and now it only lasts 10 seconds.

**Comment by xpander69** [comment]
thank you for the information!

**Comment by xpander69** [comment]
sorry for not noticing before, but this has been reported long time ago already and not fixed yet. closing this
https://github.com/WarEmu/WarBugs/issues/18241
