### ISSUE TITLE
Epic Quest "Unmasking the Enemy" not solvable

### ISSUE THREAD

**Issue by waerter** [WarEmu/WarBugs#19067]
**Expected behavior and actual behavior:**
"Unmasking the Enemy" is not solvable because the Shadowflame Shades in Step 1 did not spawn in there usual room. Therefore cant be killed to loot the Vellum.   
(I did the quest multiple Times, so I know the room. ive searched whole drakes rest in case they did appear in other positions but they dont.) 

![Randro_003](https://user-images.githubusercontent.com/62266826/120227075-ceecee80-c248-11eb-9141-2871e84451ff.jpg)

**Comment by lilimx** [comment]
related to the closed issue: #18825

**Comment by Lheana** [comment]
Related to #16938
