### ISSUE TITLE
Deci Boots + Tali

### ISSUE THREAD

**Issue by sunspearhonor** [WarEmu/WarBugs#19061]
Issues with adding r8 tali into Deci boots (r11) for Choppa. No issues adding same tali to chest (r11).

**Comment by lilimx** [comment]
Hey,

could you provide screenhots from the item and your talisman?

**Comment by bloodmasked** [comment]
the boots are probably level 7

**Comment by Rogots** [comment]
> the boots are probably level 7

Guess so too, the talisman level requirement is refering to the level requirement of the armor/weapon piece and not to its item level (talisman level requirement needs to be equal or less than the level requirement of the equipment piece).

**Comment by lilimx** [comment]
hey,

yes, Decimator Boots are lvl 7. To slot a talisman, the required career lvl is important not the item lvl.
