### ISSUE TITLE
An error in the game when using the NerfedButtons addon 

### ISSUE THREAD

**Issue by Gokudou** [WarEmu/WarBugs#19062]
Two days ago, I got a bug, characters who use the addon have a GCD for ALL spells (3 seconds). Disable the addon, the problem disappears. NB version 3.3.2 
![Gokudou_007](https://user-images.githubusercontent.com/26198706/120107505-ef924700-c169-11eb-9b20-22ba95b1b043.jpg)

**Comment by acidicrain** [comment]
This is not a bug. Patch notes specifically say they have deliberately stopped nerfedbuttons from working

**Comment by Lheana** [comment]
There is a GCD on all spells, and it has always been the case. Please read patch notes for more information.
