### ISSUE TITLE
Plan B not rotating ability bars

### ISSUE THREAD

**Issue by lokiusus** [WarEmu/WarBugs#19071]
**Expected behavior and actual behavior:**
Plan B should rotate from ability bar 1, 2, then 3 on SM and BO.

**Steps to reproduce the problem:**
It seems to happen especially when in combat. When not in combat it sometimes rotates correctly - but not always. 

Reinstalling Plan B didn't fix. Turning off all other addons didn't fix. 

**Testing Screenshots/Videos/Evidences (always needed):**
https://youtu.be/q6LXjpCoJ_E

Showing that no matter what I do, every time I press a button it fires Ensorcelled Blow/whatever the ability bar 1 is, not the skill on the rotated to bar. Buttons not on the bar that rotates still work fine. Also showing that combat changes it.

**Comment by Rydiak** [comment]
You might want to reach out to the creator of Plan B instead of the RoR team, which doesn't maintain nor guarantee third party add-ons.

**Comment by lilimx** [comment]
hey,

yes, that's an Addon issue.

**Comment by lokiusus** [comment]
I get that it's an add on, but this issue was not happening before the last patch, and you literally said that the Plan B addon would continue to operate in the last patch notes. 

I've messaged Idrinth, because I have no idea who made this addon a decade ago, but I think just waiving off this issue is just a bit disingenuous.
