### ISSUE TITLE
Ey, Quit Bleedin' - AOE HoT doesn't apply on self

### ISSUE THREAD

**Issue by utaLz** [WarEmu/WarBugs#19078]
Hello,

The rework of the HoT "Ey, Quit Bleedin'" is pretty nice, but there is a small issue where the HoT doesn't apply on AOE when on selftarget.

Video :
https://www.youtube.com/watch?v=KO7LluzqvLA

Thanks :)

**Comment by Kaeldrick** [comment]
Yeah I confirm that, looks like it's bugged just like Fury of da Green when you target yourself or no friendly target.

**Comment by xpander69** [comment]
Already reported here for AM https://github.com/WarEmu/WarBugs/issues/19065
But i will leave thisone open for now as its same issue but cannot be searched easily for shaman.

**Comment by dalen** [comment]
This is a BuffHead addon bug. In the default effect tracker you can see the buff apply on the ally as well.

**Comment by Kaeldrick** [comment]
Not it's not a visual bug. I've checked combat log many times and no healing done to allies when using this ability on self whereas it's working perfectly when target is another friendly one.
Please, re-open this ticket :)

**Comment by dalen** [comment]
when I tested I could see the hot applying to a nearby ally when targetting myself. It only showed up in regular buff tracker, didn't show up in buffhead.

**Comment by dalen** [comment]
but can test again I suppose

**Comment by dalen** [comment]
ok, found the issue, fix pending

**Comment by lilimx** [comment]
Fixed with Patch 22/07/2021
