### ISSUE TITLE
Squig Herder: Behind Ya

### ISSUE THREAD

**Issue by Stinkyweed** [WarEmu/WarBugs#1907]
Tactic on live gave crit % increase based on the targets hit points, lower the hpts higher the crit%.  The tool tip does not reflect this, not sure if it's in the coding.

**Comment by Stinkyweed** [comment]
Flanking Shot on SW has the description in the tool tip on how both Behind Ya! and Flanking Shot are supposed to function.

**Comment by grunbag** [comment]
Fixed already
