### ISSUE TITLE
Lag-Spike and CTD on entering keep

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#19074]
Experienced a strange lag-spike on entering "Thickmud Pit". Everytime I went through the outer postern doors the game froze for couple of seconds, before cathing up again. 
After a few tries of hopping in and out, my tactic slots went missing, parts of my skills got red, some cryptic text was spammed into chat and my stats went crazy...a few moments later I crashed to desktop.
![strange](https://user-images.githubusercontent.com/40274248/120557078-af4af700-c3fd-11eb-9096-245211eac710.jpg)

After the relog, nothing of this happend again, eventhough I was still in the same area.

**Comment by lilimx** [comment]
Hey,

thanks for your ticket. The lag is the so-called "bolster-lag" which isn't a bug. There is currently an issue with bolster and debolster inside RVR zones. Will add this ticket to a related one.

**Comment by lilimx** [comment]
related to #18988

**Comment by Scophis** [comment]
I know that bolstering causes lags, but this happen while entering a keep. Thickmud Pit's postern is close the "non-rvr"-area, but this also accured on the west-postern after I spend some time in the rvr-lake.
