### ISSUE TITLE
[KotbS] "Biting blade's" duration increases on reaply

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#19073]
Noticed several times that "Biting blade's" duration increases on reaply over the 10sec stated in tooltip.
![BB-tactic](https://user-images.githubusercontent.com/40274248/120556358-aefe2c00-c3fc-11eb-99a3-48dfae20d21f.jpg)
(PS: managed to stack it up to 12 sec but didn't get a screenshot)

**Comment by Rydiak** [comment]
Not a bug.  All DoTs that can be refreshed add a second or two onto a refreshed duration when refreshing that DoT before it expires.
