### ISSUE TITLE
New SetHotbarPage hook has Mara stances mixed up

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#19087]
**Expected behavior and actual behavior:**

Part of the fixes to prevent NB have including limiting which action pages can be set to which action bars. The checks for the Marauder also ensure that you are currently in the correct stance/gift for the page you are trying to set. However it seems the wrong pages are being used for the checks.

The code is (according to the comments) trying to do:

Page 1 = Monstro
Page 7 = Brutality
Page 8 = Savagery

But the actual mapping should be (from stanceswaps.lua)

[GIFT_OF_SAVAGERY]      = { 1 },
[GIFT_OF_BRUTALITY]     = { 7 },
[GIFT_OF_MONSTROSITY]   = { 8 },

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Zomega-WAR** [comment]
@dalen

**Comment by lilimx** [comment]
according to Zomega, the fix is live.
