### ISSUE TITLE
[Quest][High Elf Chap 9] Price of Peace - NPC missing

### ISSUE THREAD

**Issue by gamerlenny** [WarEmu/WarBugs#19080]
**Expected behavior and actual behavior:**
In quest Price of Peace given at High Elf Chap 9 in Ellyrion, there should be a killable animal NPC named Silverwind in the marked area (around the Gates of Elthrai),  it's a horse that we have to kill first before interacting with the altar in order to complete the quest.

Silverwind is nowhere to be found in the area, there are only Loathsome Warriors (which are the NPC's from the  Gates of Elthrai PQ's first stage), and lots of "Loathsome Steed" Chaos-like horses that do not trigger anything when killed. No Silverwind...

Either the NPC Silverwind is in fact at another location that is not marked on the map, which makes it pretty impossible to find, or it is not there whatsoever. I tried to search the other nearby areas but could not find it.

**Steps to reproduce the problem:**
Accept Price of Peace quest from H.E. Chapt. 9 quest giver, go to the marked area and try to find Silverwind.

**Testing Screenshots/Videos/Evidences (always needed):**
![Vallekana_000](https://user-images.githubusercontent.com/2891053/120698874-ee398500-c4af-11eb-87f2-1293c9b696ab.jpg)

**Comment by lilimx** [comment]
related to #16938

**Comment by gamerlenny** [comment]
> related to #16938

Confirmed, I just tried again today and Silverwind was there as expected, he must have aggroed someone earlier and been pulled to another location, out of reach or hidden or far away from where he was supposed to be... Thanks for the tip!

**Comment by Herdon** [comment]
Minor note.
He spawns in a very weird (kind of hidden) spot. Took me 20 mins to locate him.
![Silver](https://user-images.githubusercontent.com/2021593/164336862-1f570d4a-804d-4742-9143-4cf8b3c2c9b9.jpg)
After few minutes he makes 2-3 steps and then return back to his hidden spot.

**Comment by lilimx** [comment]
This ticket is closed, please open a new one with your issue.
