### ISSUE TITLE
Harnessing the Power - Dragonwake

### ISSUE THREAD

**Issue by Ramessu** [WarEmu/WarBugs#19082]
Hello, I'm having trouble completing this quest. I've gathered the quest item and have visited Prince Endhil at all 3 locations according to: https://github.com/WarEmu/WarBugs/issues/9691 and clicking on Prince and/or the quest item does nothing. There also aren't any markers at his locations. Is this a bug or am I missing something. Also, the map marker remains on Forgepriest Kryven, but clicking on the item and/or Forgepriest Kryven does nothing as well. Thank you for any help.
![Untitled](https://user-images.githubusercontent.com/84376715/120776532-59a44680-c4f2-11eb-8fe6-1d9c6fa58445.png)

**Comment by Lheana** [comment]
This has been fixed in the last patch.

**Comment by Ramessu** [comment]
Thank and the whole team for your work! You are very much appreciated! 🙏🙏🙏John U. Thimas Sr.aka Ramessu WP, Kheperunebra BW & Sheritamun AMSent from my Galaxy
-------- Original message --------From: Lheana ***@***.***> Date: 6/26/21  10:38 AM  (GMT-05:00) To: WarEmu/WarBugs ***@***.***> Cc: Ramessu ***@***.***>, Author ***@***.***> Subject: Re: [WarEmu/WarBugs] Harnessing the Power - Dragonwake (#19082) 
This has been fixed in the last patch.
