### ISSUE TITLE
Font color too light on light backgrounds within crafting items in backpack

### ISSUE THREAD

**Issue by Figureinthedark** [WarEmu/WarBugs#19086]
When you have dark backgound color items in your backback (orange circle item) you can clearly see the number.  However with light background items the number is washed out (red circle).

Would it be possible to make the font a different color for light background items so it is more clear?  

![backpack](https://user-images.githubusercontent.com/85411246/120901296-f0165c00-c607-11eb-9690-5a70a24c2ea4.png)

**Comment by lilimx** [comment]
Hey,

thank for your report, but this isn't a real bug. If you want to make a suggestion, please write a little suggestion here: https://www.returnofreckoning.com/forum/viewforum.php?f=15

**Comment by Figureinthedark** [comment]
Ok no problem I knew it wasn't a bug...more of an 'enhancement'.   Thanks.
