### ISSUE TITLE
Soul Essence/Rightous Fury Reg - No T3 Chalice Influence Reward for DoK - Sigmar Priest gets Epic Book

### ISSUE THREAD

**Issue by Orbok** [WarEmu/WarBugs#1908]
There is a problem with Influence Rewards; compare Disciple of Khaine and Sigmar Priest.

Highly relevant for the classes DoK and SP is the hidden stat concerning regeneration of Soul Essence (DoK) and Rightous Fury (Sigmar Priest) which is on the Chalice (DoK) respectively the Book (SP).

The Sigmar Priest has an Epic Book as 2nd Influence Reward in T3 Dwarf Zone. The DoK gets no Chalice in any of the T3 Zones.
This isn't that big of a problem if you managed get the epic chalice as Influence Reward Ostland, but if you level out of t2 without getting the influence there you would have to play endess T3 szenarios to get a szenario chalice with a char that is incapable of proper healing due to the fact that he has no proper Soul Essence regeneration.

I hope I could explain the problem.
And thank you for looking in to it in advance.

**Comment by genisaurus** [comment]
Note: Qhaysh Chalice
+ 27 Strength
+ 18 Willpower
+ 12 Weapon Skill
8 SE/s

**Comment by Tesq** [comment]
influence t3 chalice/book  boost also resistences ( same for t4 ones but they  just boost 2)

**Comment by Tesq** [comment]
http://www.arsenalofwar.com/items/Destruction/Qhaysh%20Chalice

+ 27 Strength
+ 18 Willpower
+ 12 Weapon Skill
+ 80 Spiritual Resistance
+ 80 Elemental Resistance
+ 80 Corporeal Resistance
You will gain 8 Soul Essence every second.
Barrier V - On Being Hit: 3% chance to form protective barrier that absorbs up to 200 damage over 5 seconds.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/5494

**Comment by wargrimnir** [comment]
These appear correct, aside from the Barrier proc which was intentionally removed.
