### ISSUE TITLE
Outlaw's stuff alternate appearance

### ISSUE THREAD

**Issue by Novgoroth** [WarEmu/WarBugs#1909]
It seems to be impossible to use the outlaw's stuff as alternate appearance (lvl31 stuff, low T4 appearance).
Could it be possible to fix this please ?

**Comment by Evildoor** [comment]
Is this a bug (it was possible to use it for AA on live) or a request?

**Comment by Ryanfawkez** [comment]
It's not Bind on pickup, thereby not usable for appearance (unless you use the work-around)

**Comment by Novgoroth** [comment]
Use the work around ? what do you mean ?

**Comment by Evildoor** [comment]
Read my comment to #1703.

**Comment by Novgoroth** [comment]
Okay i tried that, but it only work to give AA to a non Bind on pickup object, but it's not working to give an AA to a bind object with a non BoPU object

**Comment by Evildoor** [comment]
![shields](https://cloud.githubusercontent.com/assets/11015074/11344817/86ec414e-9224-11e5-8bf6-33ebf1fe9e33.jpg)
I think you are doing something wrong. Also - you should be able to actually wear the item in terms of level restrictions for this to work,

**Comment by Novgoroth** [comment]
Oh i just understood something in fact ...
My bad, it's definitly working ! Thanks a lot ! \o/

**Comment by Evildoor** [comment]
You are welcome.
