### ISSUE TITLE
squig armor

### ISSUE THREAD

**Issue by tquirl745** [WarEmu/WarBugs#19090]
hallo.
wenn ich im squig armor bin und einen begleiter rufe, dann fliege ich immer wieder aus meinen squig armor.
ist das normal???

bitte um hilfe

danke

charackter name: tquirl

Hello.
when i'm in the squig armor and call a companion, i keep flying out of my squig armor.
is that normal???

Please help

thanks

character name: tquirl

**Comment by xpander69** [comment]
duplicate of: https://github.com/WarEmu/WarBugs/issues/18439
