### ISSUE TITLE
Ruthel Assault from WE buggy

### ISSUE THREAD

**Issue by Pagiman** [WarEmu/WarBugs#19094]
I ask you to check the ability of Ruthel Assault with the Tactic Bleeding Edge. Actually this Tactic should only ignore 50% armor, but today I noticed again with the player (nice look) that this Tactic 100% armor in connection with Ruthel Assault bypasses. I have screenshots with my sword master and also with my archmage that prove this and no, the player did not use the Elixir from Insane Power beforehand because he had approached me with the Elixir of Shadow skill, which is known to have the same cooldown timer. It really has happened many times to other witch elves as well.

Thanks in advance
![Noobody_001](https://user-images.githubusercontent.com/83768657/120945436-3e774800-c739-11eb-8e05-eb934bfb0a1d.jpg)

**Comment by Pagiman** [comment]
Here a Pic from my Slayer

**Comment by stonetradex** [comment]
Your are wrong. No offense.  
Your SS does not prove much. 
Bleeding edge and BB still ignoring only 50%. Weapon skill from character plus many other tools help go over 50% 
1 - Weapon skill from character
2 - 4% armor pen from sov helmet
3 - Increase weapon skill from Vanquisher/Triumph 
5 - Onslaught gloves  = 5%

**Comment by Grock-r** [comment]
The tactic is not "armor ignore", it is an armorpen buff, so it stacks with weapon skill.

If you had about ~3.1k armor and the WE had around ~30% armorpen from WS then numbers check out fairly closely. 
Without the buff you'd have aroung 49% mitigation (3100 * 0.7 / 44) and under the buff you'd have around ~14% (3100 * 0.2 / 44).

Toughness can be pretty much ignored as it is a slayer with Wild Gambit slotted and debuffed by Wracking Pains so it is likely at zero or very close to it.

Check the math or test it before submitting a ticket. Ask on forums if you can't do it yourself.
