### ISSUE TITLE
Declare Anathema, stagger effect disappear instantly with no damage.

### ISSUE THREAD

**Issue by azpe** [WarEmu/WarBugs#19092]
**Expected behavior and actual behavior:**
Stagger should not fade off after 5 seconds, but it did, it faded off in less than 1 seconds. I did not do any damage to break the stagger. (Evidences: Video and combat log)

**Steps to reproduce the problem:**
1- Use Declare Anathema (It can't be parried/blocked)
2- Apply stagger on the target, sometimes it last for less than 1 seconds.

**Testing Screenshots/Videos/Evidences (always needed):**

Video: https://streamable.com/ppes5u
Combat Log: 
![Capture](https://user-images.githubusercontent.com/11298467/120935792-c0994980-c704-11eb-867b-898ff0b27702.PNG)

**Comment by lilimx** [comment]
Hey,

the stagger of Declare Anathema can be parried or blocked.
When you check your video, you can see there is a little parry when you selfpunt away.

**Comment by Bejkon** [comment]
@azpe 

does this happen when vs. any/all random classes?

in the provided example, its a choppa, which brings a possible explaination.

Could it be the case that you timed your DA just after the choppa had pressed his first ability(DGN) but before he was hit by the self damage procc of Hurtin' Time? in that case, the proc tick would break the stagger instantly as it procced. 

Its a very slim window as far as timing goes but i know similar stuff used to happen with slayers(got the same kinda procc) proccing of their ID dots ticks, making them break any stagger withing 2sec as long as they kept IDing.

**Comment by stonetradex** [comment]
It happens to slayers very often, after using Agile escape  with my WE. Thanks for the video

**Comment by azpe** [comment]
> @azpe
> 
> does this happen when vs. any/all random classes?
> 
> in the provided example, its a choppa, which brings a possible explaination.
> 
> Could it be the case that you timed your DA just after the choppa had pressed his first(or second) ability but before he was hit by the self damage procc of Hurtin' Time? in that case, the proc tick would break the stagger instantly as it procced.
> 
> Its a very slim window as far as timing goes but i know similar stuff used to happen with slayers(got the same kinda procc) proccing of their ID dots ticks, making them break any stagger withing 2sec as long as they kept IDing.

it looks like you say, Hurtin' Time damage in return could break Stagger, so it is not a bug, it's working properly.

**Comment by xpander69** [comment]
Ok closing for now. Feel free to re-open if you discover any issues with it
