### ISSUE TITLE
no clobal cd

### ISSUE THREAD

**Issue by muraloo** [WarEmu/WarBugs#19091]
Sorry for my English. A witch hunter with the name |name removed], killed several times for knok, judging by the logs, he beats bypassing the global cooldown. Thanks

[link removed]

**Comment by Rydiak** [comment]
I can't read the combat log, but were any of those DoTs that he had applied earlier in the fight?  Also, you might want to send this to a GM directly instead of the bugtracker.

**Comment by xpander69** [comment]
No namecalling on bugtracker. Report those to GMs. closing

**Comment by muraloo** [comment]
how do I write a GM?

  
>Воскресенье, 6 июня 2021, 19:35 +03:00 от Rydiak ***@***.***>:
> 
> 
>I can't read the combat log, but were any of those DoTs that he had applied earlier in the fight? Also, you might want to send this to a GM directly instead of the bugtracker.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Станислав Михайленко

**Comment by xpander69** [comment]
@muraloo either in game with typing .gm to see whos online or discord or forums:
https://www.returnofreckoning.com/forum/memberlist.php?mode=group&g=17
