### ISSUE TITLE
Cloaks alternate appearance bug

### ISSUE THREAD

**Issue by Sandskid** [WarEmu/WarBugs#19096]
Hello. Alternative appearances for the cloaks are broken now. You see an appearance you chose, however, all others just see an original skin. Checked it on several cloaks and characters.
Guild cloaks is ok.

**Comment by lilimx** [comment]
Hey,

please be more specific about your issue. We already know that there are a few cloak appearances are broken, but are you talking about a specific one?

**Comment by Sandskid** [comment]
No, any alt appearance is showed just for the owner. I've checked this with my friend on different cloaks and different skins, every time he saw the original skin of the cloak I was currently wearing. Same for me, when he did the same on his side.

**Comment by lilimx** [comment]
Hey,

you both were online on the same side or he was Order and you Destro?

**Comment by Sandskid** [comment]
Both Destro

**Comment by Sandskid** [comment]
You thought it was "Enable Enemy Appearance" but no :)

**Comment by lilimx** [comment]
Hey,

okay, I will close this. You give no direct exampel what cloak appearance is broken. We already have some tiecktes about broken cloak appreances, mostly Warlord and Souvereign. Please open a new ticket about an item with its appearances and add some evidence, thanks.
