### ISSUE TITLE
Khaine's Blood Cloak skin is broken

### ISSUE THREAD

**Issue by Sandskid** [WarEmu/WarBugs#19098]
When I set this cloak for an appearance, I saw it, but everyone else just see an original skin
https://imgur.com/a/NeKuC72

**Comment by Rydiak** [comment]
By any chance, is your equipped cloak a Warlord or Sovereign cloak? There is currently a bug where no appearances work on them (can't be seen by other people), though I suspect that many more cloaks than just Warlord/Sovereign are broken with appearances.

**Comment by Sandskid** [comment]
No, it's just Harbinger

**Comment by Sandskid** [comment]
Many more, yes. I've tried different ones, both from PvE drop and from vendor, with the same result. I don't remember which ones exactly tho

**Comment by wargrimnir** [comment]
Appearances are seen by people who opt into seeing them. It's a user setting. Otherwise they see the original appearance. This is working as intended.

![image](https://user-images.githubusercontent.com/12942408/123543448-7cee9a00-d71c-11eb-83a8-045fee5d81cd.png)

**Comment by Rydiak** [comment]
Friendlies aren't seeing cloak Appearances too, not just enemies.
