### ISSUE TITLE
T4 epic quest battle for remembrance

### ISSUE THREAD

**Issue by sonnypetersen** [WarEmu/WarBugs#19104]
Can't hand in quest to Brol Gornbrow, he is standing wrong place according to map. Place is on a mountain side where character slides past.
https://wiki.returnofreckoning.com/Dwarfs_T4_Epic_Quest_Battle_for_Remembrance
Step 9

![Snotson_008](https://user-images.githubusercontent.com/29485219/121347164-27964880-c927-11eb-8537-cac949af5779.jpg)
![Snotson_007](https://user-images.githubusercontent.com/29485219/121347206-354bce00-c927-11eb-878b-ea2f37cbb34e.jpg)
![Snotson_006](https://user-images.githubusercontent.com/29485219/121347229-3b41af00-c927-11eb-868f-99922c3d42b1.jpg)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. I will add it to a related issue.

**Comment by lilimx** [comment]
related to #16938
