### ISSUE TITLE
Can't see granted abilities bug

### ISSUE THREAD

**Issue by bloodmasked** [WarEmu/WarBugs#19109]
The granted abilities UI is not hidden but I can't see it, is there a way to fix it without having to redo my entire ui?

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. 
That's more a question for the "Technical Support" forum: https://www.returnofreckoning.com/forum/viewforum.php?f=4
Or join the RoR discord and ask in #technical-advice https://discord.gg/G9jDWgv
