### ISSUE TITLE
Slot on boot rvr

### ISSUE THREAD

**Issue by Dalkii** [WarEmu/WarBugs#1910]
The rvr wl boots dont have slot for talisman, i dont know if its normal, btw the ring either, just to know if it will be fixed

**Comment by genisaurus** [comment]
Please be more specific. What is the name of the boots missing the talisman slot?

Jewelry does not have talisman slots, save for perhaps a very few items.

**Comment by Dalkii** [comment]
The missing boots talisman are Qhaysh Shinsteels and Ghrond's shinsteels on high elfs (for white lions)

**Comment by genisaurus** [comment]
Fixed in next patch

**Comment by Dalkii** [comment]
Great thx
