### ISSUE TITLE
Squig pet despawn near keep

### ISSUE THREAD

**Issue by bloodmasked** [WarEmu/WarBugs#19103]
When near keep walls your pet despawns. Happened to 2 squigs I played with, the pet despawn. Unsure if it happens to white lion pets. Such as the outer walls of keep.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
what's your current lvl? Could you provide some screenshot?

**Comment by bloodmasked** [comment]
It was happening to a level 30 squig and a level 40 rr80+ squig in my group. I don't have screenshot.

**Comment by lilimx** [comment]
Hey,

If it happens with a lvl 30 SH, it's due to the bolster/debolster in zones, this issue is already know.
If you can bring evidence that lvl 40 SH pets also disappear, would be nice. Otherwise I have to close this ticket.

**Comment by xpander69** [comment]
Yeah would like to see confirmation about that. If thats the same issue then you can replicate this by doing 1 scenario and then going to test near a BO or Keep. The bolster-debolster issue happens after you load out from scenarios. Workaround for now is to relog after doing scenarios.

**Comment by lilimx** [comment]
Hey,

due to the lack of information, I'll close this ticket now.
