### ISSUE TITLE
speed hack

### ISSUE THREAD

**Issue by braqmar** [WarEmu/WarBugs#19110]
My characters move faster than the others players, I don't know why.
![image](https://user-images.githubusercontent.com/85703636/121578661-32d29c80-ca2b-11eb-8d42-c7c54fd50220.png)

**Comment by lilimx** [comment]
Hey,

I can't see anything in this picture about your movement speed. What happened before you got the higher movement speed? Does it still persists when you /rel or die?

**Comment by braqmar** [comment]
I've got it since 3/4 weeks, after an update my characters move a lot slower, then I leave the game, and since the day after I move 2x faster. I havent change anything in my ui or addon, But I move at the same speed than horses (a little slower in fact). Same for all my characters.

**Comment by lilimx** [comment]
Hey,

thanks for your ticket. So everything is right with your character, otherwise we would already known that. it's maybe a connection issue. Just in case, I will add it to a related issue.

**Comment by lilimx** [comment]
similar to #19002
