### ISSUE TITLE
[Zealot] Demon Spittle can only be applied once to a target regardless of the number of Zealots vomiting on it

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#19119]
**Expected behavior and actual behavior:**

Expected: Demon Spittle is a plain frontal-cone DoT and enemies hit by the ability cast by multiple Zealots should have a DoT for each Zealot applied to them.

Actual: Currently a player can only be affected by a single Demon Spittle effect. If Zealot 1 casts it on the target then the target has the hex applied. If Zealot 2 then casts it while Zealot 1's hex is still active, Zealot 2's Demon Spittle will sometimes just not apply any hex at all, and the rest of the time will *remove* Zealot 1's hex and replace it with its own hex.

This causes extra problems when a Zealot is using the Sweeping Disgorgement tactic (adds an armour and spirit debuff to Demon Spittle) as this extra debuff gets removed if the Zealot's hex is removed, or just doesn't applied at all if the Zealot's hex doesn't get applied, making the application of the DoT and debuff very difficult to manage.

If I were a betting man I would say that this could be something relating to ensuring only one copy of Sweeping Disgorgement is applied, but currently this check applies to the entire hex regardless of whether the tactic is in or not, and the DoT part should stack with the DoTs from other Zealots regardless.

**Steps to reproduce the problem:**

Have 2 Zealots spam-cast Demon Spittle on a target. Only one hex will be applied.

**Testing Screenshots/Videos/Evidences (always needed):**

Unable to provide - getting recording for this setup when I'm relying on randoms in IC to test it is almsot impossible. I tested this a year ago and I tested it again today and the issue still exists.

**Comment by lilimx** [comment]
Fixed with Patch 22/07/2021
