### ISSUE TITLE
RR Trainer Bug

### ISSUE THREAD

**Issue by buffel73** [WarEmu/WarBugs#19114]
Hi 

On My SM Itangi if i click on the rr trainer and then on the rr points nothing opens up. the mastery options does open futher
Please help

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. Is this a fresh install? You should check the RoR dicord (#technical-advice)..so we can check if it's really a bug or just install/update issue.

**Comment by xpander69** [comment]
screenshot would be helpful also. Are you using any addons that might cause this and as suggested by Lilim, might be your install is broken.

**Comment by lilimx** [comment]
Hey,

I'll close this ticket now, because no information has been submitted for further processing.
