### ISSUE TITLE
Greenskins T4 Epic Quest Time to Waaagh! cannot be completed

### ISSUE THREAD

**Issue by nastya0204** [WarEmu/WarBugs#19113]
**Expected behavior and actual behavior:**
On last step of this epic quest u need to kill Wazgit (Champion lvl 40) in Kadrin Valley at 36k/50.3k. But that npc is missing, I have done this questline 1 time, so i remember where he should be.

**Steps to reproduce the problem:**
I relogged and also closed client. I didnt find on Bugtracker the same reported issue.
I waited 20 min in case if he was killed recently but he didnt respawn.

**Testing Screenshots/Videos/Evidences (always needed):**
![Screenshot_2аиаиа](https://user-images.githubusercontent.com/85760518/121731201-477d6600-caf9-11eb-9a1a-6b31f4f34079.png)
![Screenshot_2ааааааааааааааа](https://user-images.githubusercontent.com/85760518/121731211-4ba98380-caf9-11eb-9037-ffb281471e2f.png)

**Comment by lilimx** [comment]
Hey, 

thank you for your ticket. I will add this report to the other missing NPCs report.

**Comment by lilimx** [comment]
related to #16938
