### ISSUE TITLE
Stalker quest and items

### ISSUE THREAD

**Issue by Novgoroth** [WarEmu/WarBugs#1912]
I found some bugs about the stalker stuff:
- the stalker chest has naked appearance
- the quest taken in Avelorn with the NPC Asille Nightreach where you have to kill 20 Archmages doesn't work. Killing on archmages doesn't give any point for the quest.
- the NPC who's supposed to give the quest, named Halbjorn Frent, is missing. He's supposed to be in PVE chapter 12 of talabecland

**Comment by genisaurus** [comment]
Fixed in next patch
