### ISSUE TITLE
Mastery/Abilities: Mastery level 17 / ability level 42 possible

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#19122]
**Expected behavior and actual behavior:**

Mastery is supposed to be capped at 15 points, and ability levels capped at 40 (25 base and up to 15 from mastery), and these values are used to determine base damage, buff/debuffs, etc. However, it is possible to put 17 points into a mastery tree and make those abilities/tactics/etc level 42.

**Steps to reproduce the problem:**

1) While not affected by any +mastery item bonuses, put 15 points into a mastery tree.
2) Now equip items that give +2 to that mastery tree (commonly found on Sovereign gear)

That's it. You now have 17 points in that mastery and the skills are level 42 instead of 40.

**Testing Screenshots/Videos/Evidences (always needed):**

Level 40 (15 points in Path of Alchemy):

![image](https://user-images.githubusercontent.com/60266177/121766405-77545a00-cb49-11eb-96ed-f712d5a11d55.png)

Sovereign set bonus with +2 to Alchemy now applied. Ability is now level 42

![image](https://user-images.githubusercontent.com/60266177/121766425-94892880-cb49-11eb-966d-e4d1b9eec844.png)

Not just a client display error: the granted buff shows the higher stats, as does .getstats

![image](https://user-images.githubusercontent.com/60266177/121766443-b1bdf700-cb49-11eb-9499-03b35d6366f9.png)

**Comment by dalen** [comment]
This is intentional, and a possible use for the +2 mastery on sovereign sets.
