### ISSUE TITLE
One target dummy in IC reports different damage numbers to the rest

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#19128]
**Expected behavior and actual behavior:**

Expected: all of the target dummies (the arrow boards) should be identical

Actual: one of them changes the damage slightly and is likely the cause of a bunch of off-by-one issues.

**Steps to reproduce the problem:**

With a Zealot:

1) Go to IC
2) Find the two target dummies facing towards the Khorne area
3) Cast Scourge on the one on the left. Damage matches tooltip
4) Cast Scourge on the one on the right. Damage is off by one.

No other effects on the boards, all others tested. It's just that one that is wrong.

**Testing Screenshots/Videos/Evidences (always needed):**

Expected:

![image](https://user-images.githubusercontent.com/60266177/121782157-1ad05980-cba0-11eb-92d0-3bb0291ee839.png)

One on the left (map included to show where I am) working correctly:

![image](https://user-images.githubusercontent.com/60266177/121782178-3176b080-cba0-11eb-8ba1-e8d1b7f1fce9.png)

One on the right being awkward:

![image](https://user-images.githubusercontent.com/60266177/121782185-42bfbd00-cba0-11eb-9e1a-5bc400359c4e.png)

The other 6 all reported 277 damage.

**Comment by Kaelang** [comment]
All dummy's are exactly the same - just tested and doing the same damage on all.
