### ISSUE TITLE
[Zealot] Eye of Sheerian (morale 2) resistance buff not stacking on character sheet stats

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#19138]
**Expected behavior and actual behavior:**

The armour and resistance buffs should be morale/unique and stack with others. They stack correctly in .getstats, but on the character sheet the resistance buff doesn't stack with other abilities.

**Steps to reproduce the problem:**

1) Be Zealot
2) Take armour potion or get armour buffed by someone
3) Apply Mark of the Vortex to yourself for a resistance buff
4) Get to M2 and cast 

**Testing Screenshots/Videos/Evidences (always needed):**

Buffs provided by ability:

![image](https://user-images.githubusercontent.com/60266177/121810874-562f5e80-cc5a-11eb-9443-921ffafa9ef1.png)

Initial buffs on me (660 armour potion, 252 resistance buff from the Mark of the Vortex ability)

![image](https://user-images.githubusercontent.com/60266177/121810812-21bba280-cc5a-11eb-8b53-fb9d5aad5e3a.png)

Eye of Sheerian active. Armour buff correctly stacks with potion, resistance buff incorrectly not stacking with ability on character sheet

![image](https://user-images.githubusercontent.com/60266177/121810854-49ab0600-cc5a-11eb-8d09-1c4bbc4b8a30.png)

Stacks correctly with getstats so this is a client-side issue.

![image](https://user-images.githubusercontent.com/60266177/121811091-203eaa00-cc5b-11eb-9b2f-68efd18cd3cd.png)

**Comment by Haojun-Phalanx** [comment]
paperdoll is not working properly (common visual bug), if its working on .getstats, it's fine.

**Comment by lilimx** [comment]
Fixed with Patch 22/07/2021 (pending client patch)
