### ISSUE TITLE
Nordenwatch SC:  Fortress Flag is bugged

### ISSUE THREAD

**Issue by mursie** [WarEmu/WarBugs#1913]
Fortress flag does not uncap from the initial side that takes it.  (I.e. order take the flag at beginning of SC - it can not be uncapped and taken by other team.  Bugged and stays order taken despite entire destro group standing on it alone for 2 mins).

**Comment by Evildoor** [comment]
It seems that this has some kind of condition, because i've played numerous Nordenwatchs after this report and Fortress was behaving properly.

**Comment by Evildoor** [comment]
Closing until someone provides information how to reproduce it.
