### ISSUE TITLE
[Zealot] Restorative Burst triggers on self-heal

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#19135]
**Expected behavior and actual behavior:**

Expected: the wording of the tactic says it triggers if you directly crit heal an ally.

Actual: it also triggers if you directly crit heal yourself.

**Steps to reproduce the problem:**

1) Be Zealot
2) Equip Restorative Burst
3) Crit heal yourself
4) See the buff appear

**Testing Screenshots/Videos/Evidences (always needed):**

Tactic wording:

![image](https://user-images.githubusercontent.com/60266177/121793085-98718500-cbf3-11eb-8e52-71b56fceb942.png)

Crit healed myself and got the Restorative Burst tactic effect.

![image](https://user-images.githubusercontent.com/60266177/121793070-80016a80-cbf3-11eb-9de4-37481430424a.png)

**Comment by b00nation** [comment]
i'm pretty sure yourself is also an ally. All ability which explicitly don't allow self appliance, stating this in tooltip. So Khaines Bounty and Divine Warding are actualyl doing the same behavior with a similar tooltip.

**Comment by Zomega-WAR** [comment]
You know, I've just read some of the other ability text and yes it occasionally uses the term "ally" for friendly target. This one stood out as all the other crit heal tactics don't specify ally. I'm actually going to close this one as I think I was wrong.
