### ISSUE TITLE
No mitigation damage on sorcerer skill?

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#19139]
Hello,

I got 0 mitigation on sorcerer skills. Someone can explain me?

I got 477 spirit resistance. 

May be a bug on scintillating energy?

![Thorbolt_061](https://user-images.githubusercontent.com/16274785/121811149-c1316300-cc63-11eb-8f99-2ec483e212c2.jpg)

**Comment by Zomega-WAR** [comment]
Scintillating Energy is a morale ability, and morale abilities do unmitigated damage. No bug here.

**Comment by lilimx** [comment]
Hey,

I saw the video to this timesatamps. In short you had no resistance and no armor anymore.
So you've got so much debuffed that you wasn't to able to mitigate anything.

**Comment by Zomega-WAR** [comment]
Did you get hit with a Zealot M1? Just wondering as the mitigation for Shrapnel Arrow seems low as well. The M1 will take off 1320 armour and 504 resists.
