### ISSUE TITLE
 Khaine's Imbuement proccs only on Essence Lash 

### ISSUE THREAD

**Issue by Tharros** [WarEmu/WarBugs#19142]
Khaine's Imbuement not proccing on other torture skills like CoC, Flay, Cleave Soul, Fist of Khaine etc.
only on Essence Lash and there with 35 % its seems how its should

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

I did a test as well and everything works as inteded. Fist of Khain is Path of Dark Rites btw.

**Comment by wils0nyan** [comment]
please double check the proc rate it seems to proc way below 33%
