### ISSUE TITLE
Stalker gear in Order

### ISSUE THREAD

**Issue by Majestiks** [WarEmu/WarBugs#1914]
Sorelle Darkglade rewards the Stalker's Shoulders from quest Blood on the Leaves in Well of Whispers (High Elf Ch12), in Avelorn.
The champion is there but he hasnt any quest to give

**Comment by genisaurus** [comment]
Fixed in next hotfix

**Comment by Fortwunty** [comment]
Quest doesn't count your kills. Stays at 0
