### ISSUE TITLE
[World] Portal to the Winds of Chaos in IC not working

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#19156]
**Expected behavior and actual behavior:**

At the end of the jumping puzzle in the Arena in IC there is a portal that should take the player to one of the random "Winds of Chaos" areas for a short period. That portal is not currently working.

**Steps to reproduce the problem:**

Go to 44k x 28k in the IC and try to go through the portal.

**Testing Screenshots/Videos/Evidences (always needed):**

Running forward when this was taken. I just ran on the spot instead of being teleported somewhere.

![Zomega_711](https://user-images.githubusercontent.com/60266177/121963341-e0161f00-cd61-11eb-87b4-502d7dcde2c2.jpg)

**Comment by lilimx** [comment]
Hey,

this will be open again with the next patch.

**Comment by lilimx** [comment]
fixed with patch 18/6/2021
