### ISSUE TITLE
Boogerfinger: My Alt Appreance Tab does not seem to be functioning properly for any of my chars

### ISSUE THREAD

**Issue by nefariousd** [WarEmu/WarBugs#19169]
**Expected behavior and actual behavior:**
When I click the Tab For Alt appearance (all chars), The RVR tab appears (picture attached).

**Steps to reproduce the problem:**
I went to advice and watched videos.  In all cases, the slots and new char display that are supposed to appear when the alt box is checked never appear. The RVR tab appears every time. Thanks Team.
[RoR Pictures.pptx](https://github.com/WarEmu/WarBugs/files/6677282/RoR.Pictures.pptx)
.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
hey,

thank you for your ticket.
You can just drag and dropt the picture into the text field (if it's a gif or another common format)
Is this a fresh install? If yes, I would recommend to join the RoR discord ( https://discord.gg/G9jDWgv ) maybe some is borked with your install.

**Comment by lilimx** [comment]
Hey,

Im going to close this ticket now, because the ticket creator didn't respond to my request.
