### ISSUE TITLE
WH's bullets heal

### ISSUE THREAD

**Issue by globalgame** [WarEmu/WarBugs#19163]
Sanctified Bullets tactic gives insane healing effect for WH ! Is it balance?

At 40 lvl every heal from bullets gives 471 hp and WH able to heal himself sometimes like a healer or dps WP or DoK. 
I saw numbers 9k hp

![WAR-64 2021-06-17 11-32-32-90](https://user-images.githubusercontent.com/24555848/122353653-ea4e3e00-cf58-11eb-8851-92a0ea0dd66b.png)

about 30+ seconds fight with 30 lvl WH

**Comment by globalgame** [comment]
If so why Witch elf the same tactic Kiss of Doom gives 200+ healing but WH has 471 healing at 40 levels both ?

**Comment by globalgame** [comment]
Test on training construct
Witch elf
![WAR-64 2021-06-17 13-36-09-38](https://user-images.githubusercontent.com/24555848/122373628-4f5e5f80-cf6a-11eb-9124-ce7b75a110e5.png)
WH
![WAR-64 2021-06-17 13-45-35-10](https://user-images.githubusercontent.com/24555848/122373712-5f763f00-cf6a-11eb-89e2-966b8a3df8df.png)
WH on dummy
![WAR-64 2021-06-17 13-42-50-71](https://user-images.githubusercontent.com/24555848/122373785-70bf4b80-cf6a-11eb-8c03-64a928eb0b4d.png)

**Comment by globalgame** [comment]
Dragon gun gives at once several heals if more than 1 target

**Comment by lilimx** [comment]
Hey,

Im closing this thread now. 
+ Kiss of Death and Blessed Bulltes of Purity are two fundamentally different weapon enchantements. Please read the tooltips.
+ You started your thread with "At 40 lvl every heal from bullets gives 471 hp and WH able to heal himself sometimes like a healer or dps WP or DoK. I saw numbers 9k hp" and added a screenshot from a bolstered lvl 30 WH, that doesn't confirm your statement.
+ I still not seeing any dmg on your screenshots.
+ You can start a new ticket anytime....but please keep the structure of a proper report.

**Comment by globalgame** [comment]
i just filtered damage from healing
