### ISSUE TITLE
Level 1 abuse game breaking bug ?!

### ISSUE THREAD

**Issue by AkameSins** [WarEmu/WarBugs#19166]
If you are level 40 and go to Ekrund and Mount Bloodhorn RvR area, if you flag for RvR in Ekrund "which will turn you into chicken" you can then enter the warcamp and use the tunel to move to Mount Bloodhorn, after the teleport you will still be debolstered but you can use all your skills/pots/mounts etc and you can basically one shot everyone... well they can as well since you have 80 HP but ...

**Comment by Kaelang** [comment]
I tried testing this and was re-de-bolstered.

Please can you record this in action?

**Comment by GamesBondd** [comment]
> https://youtu.be/r8-KCLzSH0I

Thanks for the report.
