### ISSUE TITLE
Ch. 10 Green Skin Warcamp:  Moogz Brawl

### ISSUE THREAD

**Issue by mursie** [WarEmu/WarBugs#1916]
The NpC rally master Moogz (along with others) are inside the tower of this camp.  However, the door to access into the tower has not available mechanic to open/port into.  As such, a warcamp quest from Black Fire Pass rvr npc's which takes you here to ch. 10 can not be completed.

**Comment by mursie** [comment]
I Found a work around but the situation is dire - if you are determined - you can go to sigmarite temple pq and weave thru mountains behind this tower..  from there - a well timed jump from a railroad tie will land you on the roof of tower.  Unfortunately - this entire wc is in an  unscalable bunker cul de sac that is exited by a wall door with npcs guarding it.  so basically - once you come to this warcamp - the only way you are leaving is via book of binding.

**Comment by mursie** [comment]
or i guess you could use the flight master standing on the street. lol

**Comment by DanaBloodkiss** [comment]
Fixed in next.
