### ISSUE TITLE
[Hunter's Vale] Fallen Runepriest is actually upright and quite alive

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#19177]
**Expected behavior and actual behavior:**

The Fallen Runepriest NPC in Hunter's Vale at approx 26k x 40k on the map should be dead. She is not.

As a Zealot this offends me greatly.

**Testing Screenshots/Videos/Evidences (always needed):**

![Zomega_020](https://user-images.githubusercontent.com/60266177/122612535-36919f00-d07b-11eb-87f7-50a7a1ab9a19.jpg)

![Zomega_022](https://user-images.githubusercontent.com/60266177/122612663-6c368800-d07b-11eb-9953-13abf21bb7da.jpg)

**Comment by xpander69** [comment]
![ss_18062021_23 48 24](https://user-images.githubusercontent.com/1345116/122614759-ee30ac00-d08f-11eb-8999-c89355cbb5a3.png)
was on the same instance :D  so i think its the animation bug of WAR-64.exe
i run WAR.exe

**Comment by lilimx** [comment]
:D
