### ISSUE TITLE
Mount Wrong Level Requirement

### ISSUE THREAD

**Issue by wlfbck** [WarEmu/WarBugs#1917]
Item simply does nothing on use, i'm fullfilling the levelrequirement and am a dwarf. Tried relogging, dying and all that. Tried it just now after server crash again.

edit: Just wasted another 10g on the Bronze Contraption, also doesn't work.

**Comment by wlfbck** [comment]
Doing a bit of googling it seems the original requirement was level 20. The tooltip on RoR says 12. So i guess either the tooltip or the database entry is wrong.

**Comment by Evildoor** [comment]
It seems that the tooltip was changed from level 20 to level 12 on all mounts, but actual level check was not.

**Comment by Evildoor** [comment]
Uh, @ozarmidrashim , why was this closed? It's still not working.

**Comment by ozarmidrashim** [comment]
Because I was told that the level requirement was adjusted back to 20.

**Comment by Evildoor** [comment]
Understood. Well, the mounts still show "12" as level requirement, so i'll ask @DanaBloodkiss to take a look.

**Comment by DanaBloodkiss** [comment]
Already fixed. Will be live in next Hotfix.
