### ISSUE TITLE
Wild Hunt Task Updates

### ISSUE THREAD

**Issue by JaqiC** [WarEmu/WarBugs#19179]
The Wild Hunt Live Event is not giving credit for all tasks completed, i.e. after completing 2 of the tasks, the last entry indicates that only 1 of the 7 have been completed.

![Jaqqi_004](https://user-images.githubusercontent.com/75152388/122623834-4604ee00-d063-11eb-996c-fb506e8787e5.jpg)

**Comment by Tesq** [comment]
it's a visual bug only for "huntsman page"

**Comment by Lnternsmite** [comment]
I have a similar issue, 6/7 everything completed and its not  " actually" completed.
![Kerrak_000](https://user-images.githubusercontent.com/53047875/122691229-6e742000-d1fc-11eb-8da7-ded942b46aa8.jpg)

**Comment by CrimsonFenris** [comment]
Same bug here, cannot get the last reward :/

![Hunter_Vale_event](https://user-images.githubusercontent.com/40425011/122696242-f5e48200-d242-11eb-8be2-cf7ccf3b1349.jpg)

**Comment by Lnternsmite** [comment]
Its fixed 
![Kerrak_001](https://user-images.githubusercontent.com/53047875/122777980-8ee2bf80-d27a-11eb-9db4-c6ece685236b.jpg)

**Comment by Lnternsmite** [comment]
thank you
