### ISSUE TITLE
Mount speed issues?

### ISSUE THREAD

**Issue by Parallell86** [WarEmu/WarBugs#19171]
**Expected behavior and actual behavior:**
Should be able to keep up with players who got equal mount speed.

I noticed that alot of players with same mount type as me (r38 with 60% speed run away from me)
My guild leader and I ran through tunnels in KV RVR lake, by the end he was lets say 70-100 feet infront of me.
Ofc its not only this one situation. Its several people and frequent. Ran straight behind a SW with r16 mount and 50% speed in CW. Couldnt catch up with him/her even a bit.

EDIT: Didnt quite understand what to do with the buffhead cache feature.

**Steps to reproduce the problem:**
Im using a White Huntin' Boar. Dunno what else to say.

**Testing Screenshots/Videos/Evidences (always needed):**
![Beegmike_002](https://user-images.githubusercontent.com/44731969/122588684-aabe4980-d05f-11eb-877b-4f557e364e91.jpg)

My guild leader had to same speed stats so frankly I got no clue. My connection is perfectly stabile.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. 
There are a few people with a similar issue so I add your ticket to a related report.

**Comment by lilimx** [comment]
related to  #19002
