### ISSUE TITLE
Wl pet can make unusual high damage and oneshot people

### ISSUE THREAD

**Issue by knickk** [WarEmu/WarBugs#19173]
**Expected behavior and actual behavior:**
Wl pet can hit people for 1000-2500 dmg per crit hit and oneshot people in a single rotation

**Steps to reproduce the problem:**
pet get enrage! buff in or around Hunter's Vale and dont lose it

![](https://i.imgur.com/W9LVdS2.png)

style is Train to kill 
zone all
tactic Brute force, Pack synergy, speed training, flanking

**Testing Screenshots/Videos/Evidences (always needed):**

![](https://i.imgur.com/kMtrMry.jpg)

![](https://i.imgur.com/QebNgpY.jpg)

![](https://i.imgur.com/tsR5Gfm.jpg)

![](https://i.imgur.com/UjaXAff.jpg)

**Comment by lilimx** [comment]
+ Leonine Frenzy buff on the lion-pet (Rage!) persists even after the ability ran out.
+ If the WL player is active in the "Train to Kill"-stance, the aa of the lion-pet deals huge dmg.

**Comment by lilimx** [comment]
Reproduction:

+ Switch to "Train to Kill"-stance
+ attack an target with "Leonine Frenzy"
+ (the dmg continues on other targets aswell)

**Comment by lilimx** [comment]
hotfix 19/06/2021
 (no hotfix entry in 18/06/2021)
