### ISSUE TITLE
Hunter's Vale Boss won't come out of his portal -- Broken

### ISSUE THREAD

**Issue by Althesian** [WarEmu/WarBugs#19189]
Hi, Fleman here - I've done hunter's vale now 3times. and everytime this has happened.
https://medal.tv/clips/55812367/d1337xs26XxX

The last  boss suddenly stops exiting his portal and we have to all die in order to reset it. ( however, it's time based )
so the dungeon is failed & has to reset.

I dont know how to reproduce this issue.

All i know is i've already wasted too much time on this dungeon.

I'm going to try a 4th time now and hope for the best.

**Comment by Tesq** [comment]
i alredy reported this here with description with  N.B 
https://github.com/WarEmu/WarBugs/issues/19187

**Comment by Bricksone** [comment]
Happened to us today as well at 59% and about 10 or 11 minutes left in the pq. Not sure how you could recreate it. The screenshot was taken when we gave up and the WH had already ported back to Altdorf.
[https://www.directupload.net/file/d/6220/feo5gkzl_jpg.htm](url)

**Comment by lilimx** [comment]
Note:

Rydiak wrote that they had an almost similar issue in stage 2 
So please note ticket #19238 it could be a dublicate!
