### ISSUE TITLE
Lostgit Squigs +Lostgit Squig'un fighting one another.

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#19188]
I noticed these npcs were attacking one another, in Ellyrion.  Elyr Caverns 38k,53k.
Lostgit Squigs,
Lostgit Squig'un

![cave](https://user-images.githubusercontent.com/7898608/122647674-3eccf700-d0da-11eb-8901-d4fb574e9b6d.png)
I didn't expect them to be fighting, they should be friendly.

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by lilimx** [comment]
Fixed with Patch 22/07/2021
