### ISSUE TITLE
Chaper 15 greenskin Overtop Outpost stage 2 bugged

### ISSUE THREAD

**Issue by johnsmith534** [WarEmu/WarBugs#19182]
You have to reactivate  Trained to Hunt every time you resummon the pet to get the Pack Hunting tactic buff.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. 
But what is this ticket about? About Chapter 15? Or About a WL issue?
Please provide full description + screenshots.

**Comment by lilimx** [comment]
Hey,

Im closing this ticket now, because the ticket creator did not respond to my request.
