### ISSUE TITLE
[Hunter's Vale] vines separing each boss

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#19184]
They can only be used once, if you die at boss and rel they wont open again ( all dungeon second part after you cross over the tree-bridge).

**Comment by lilimx** [comment]
Hey Tesq,

does this issue perists, even after the hotfix?

**Comment by Tesq** [comment]
depend when the hotfix was.... i did that run yesterday night at 23:00 (gmt+1 /cet+0)

**Comment by lilimx** [comment]
Hey,

there was hotfix aroun 9 am Altdorf time

**Comment by Tesq** [comment]
then i will try again the dungeon and confirm it or close this

**Comment by lilimx** [comment]
Merci :D

**Comment by Tesq** [comment]
seems fixed closing this
