### ISSUE TITLE
[Hunter's Vale] boss wont reset / stunk on stage swap

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#19187]
step to reproduce: some of the party (1 or 2) die and rel, rest of party wipe and rel aswell after one or two people rel.

N.B: if boss dont reset correctly the party will be hit by atk of boss and debuff even trought all of the dungeon
N.B.B: if boss dont reset correctly and all party member wipe, then the entrance will be open but the ongoing fight still on and finish the step will reset the boss and the fight (potentialy making you wasting time). Also if boss enter in a portal while you kill the portal life bar the boss vanish inside the portal and the fight stuck (needed reset instance to fix it).

EDIT:  someone today told me it could be related to KD the boss before it enter the gate

**Comment by Tesq** [comment]
https://github.com/WarEmu/WarBugs/issues/19187

**Comment by Althesian** [comment]
added video evidence in my post

**Comment by Tesq** [comment]
as i edited in #19189 they seems two different issues in the end so both should be check individualy

**Comment by Tesq** [comment]
didnt see happen from as lot closing this
