### ISSUE TITLE
Tactic bugged after respec.

### ISSUE THREAD

**Issue by charlthuan** [WarEmu/WarBugs#19186]
Howdy!!
My character Charlthuan (SW) recently re-specialized his mastery, and my new tactic, No Quarter, is bugging. I have to reload the tactic into my tactics bar each time I die, or change zones. If I don't do this, the buildup times for Eagle Eye and Festering Arrow remain at their default. Help!!

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. I will add your report to a related issue.

**Comment by lilimx** [comment]
dublicate / related to  #17950
