### ISSUE TITLE
[Hunter's Vale] quest line incorrect progression

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#19183]
took quest , killed first 2 bosses and recived the reward (boots) but then no more quest from any npc (the run arrived pre last boss)

edit 1: the run in which happened was yest night from 23:00 (gmt+1 / cet+0)

edit 2 : the quest line seems to proceed after defiting the last boss of the dungeon instead (it give you the pvp kill part)
complete the pvp kill part give you the quest to recive the gloves ("kill sprite").

so it seems it continue on the wrong boss, it should be given after complete the "2-heros-tree boss" and after complete the pvp part it should ask you to kill the next boss that is the sprite. 

edit 3: the "kill the sprite part seems to work, but it also strange it probably should be kill the boss of those sprite and not a normal mob

edit 4: after the sprite kill complete i had to reach again the final boss of the dungeon for get the next quest, after killing it i was able to take another 10 kill quest

////////////////////////////////////////////////////////////////////////////

N:B at this point is clear the quest line atm work this way:

-take quest on one npc 
-kill "x" in dungeon
-kill last boss in dungeon to unlock next quest
-take quest from npc on boss location only
-kill 10 player outside of dungeon
-repeat for each pieces.

idk if it suppose to work in this way but it feel a lot of work for something inferior to invader and vanqisher ( it would be one run of the dungeon for each piece of gear, compared to beastlord  1 boss each pieace of gear); in case is intended this way i close this; lemme know.

//////////////////////////////////////////////////////////////////////////

2 cent suggestion (posting here since im alredy writing):  normal progression that follow beastlord tradition would be -> npc quest, kill boss, give quest, need exit and kill player to get the piece of equip, get back and continue with otur each for every piece the last boss (compared to bl where , 1 piece = 1 boss kill, here you need whole bosses on dungeon killed with each pieces).
While leaving timer thing still going on for more higer level player (and so reduces the timer of about 5 minutes) thus making the thing closer to BL fight while also increase longevity
Additionaly the instance could be invaded by orders and viceversa similar to tovl which would serve both as introduction to the invading meccanic and as bring back the tradition of BL.

**Comment by Tesq** [comment]
N.B: to avoid same problem that happend with beastlord at time the quest line should be made repeatable (in case of some itiem los for various reasons).

**Comment by MaxHayman** [comment]
Did your lockouts expire? You can only complete quest objectives when your lockout for a boss has expired.

**Comment by Tesq** [comment]
regardin the sprite killing part i should had been with out lockouts since i made 2-3 run in diff days and in one i was with out the lockouts but i can recheck again tomorrow with another fast run.

**Comment by Tesq** [comment]
updated main post
