### ISSUE TITLE
Hunter's vale finished the event and no cloak

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#19198]
Hello,

I finish the event and get no cloak? bug? 
-->
![Thorbolt_076](https://user-images.githubusercontent.com/16274785/122672663-13770480-d1cd-11eb-844b-4bf4f14f2d1d.jpg)

**Comment by Scutarius91** [comment]
Yeah same here, is it a hidden task perhaps?

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. This issue is already known, for some reason the task won't update correctly.
I'll add it to the related report.

**Comment by lilimx** [comment]
dublicate / related to  #19179
