### ISSUE TITLE
[Hunter's Vale] Missing title for Achievement

### ISSUE THREAD

**Issue by Caduceus42** [WarEmu/WarBugs#19197]
Greetings,

I received an achievement for killing the Spirit of Kurnous 5 times. The Tome of Knowledge entry and the RoR wiki suggest I should have received a title also ("Blessed of Kurnous"), however this has not happened. 

![Blessed of Kurnous Bug](https://user-images.githubusercontent.com/69918329/122669716-eae80e00-d1be-11eb-8c07-3d329b256865.png)

![Blessed of Kurnous Bug 2](https://user-images.githubusercontent.com/69918329/122669751-1a971600-d1bf-11eb-9458-7d38c6e88f23.png)

I hope this can be fixed at some point. 

Thank you for your time,

-Caduceus

**Comment by Lheana** [comment]
This should have been fixed several patches ago.
