### ISSUE TITLE
[Hunter's vale] quest giver interaction

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#19191]
EDIT: quest giver "Spirit of the Vale"  can atk and be atk and get kill by enemy mobs ; it should be friendly to all.

(it is placed in various part of the dungeon all of em have this problem altough mobs dont go near em but in a boss fight some are close and it may happen that they atk and also get dmg ). They need the same fix done in gunbad for healers NPC.

![Sintoras_078](https://user-images.githubusercontent.com/7527415/122657808-08898900-d167-11eb-97d2-afb43a88d544.jpg)

**Comment by lilimx** [comment]
Hey,

could you please give us some screenshots :D so we know who and why

**Comment by Tesq** [comment]
done
