### ISSUE TITLE
Sold mount back-buyed it from the list and after relog gone

### ISSUE THREAD

**Issue by donsastre** [WarEmu/WarBugs#1919]
^this happens to every item ... is there anyway to get it back it was the t3 mount :3

greetz

**Comment by ozarmidrashim** [comment]
Possibly the source of the save failures spamming the logs on character_items.

**Comment by bandshark** [comment]
I lost my Iron breaker weird helmet the same way. I figured it was just another random lost item to return after the server restart, but it didn't. I never associated it with selling and buying back before logging out. Glad someone caught it.

**Comment by Mizrim** [comment]
Crap just realised I did exactly this before my Devastator shoulders disappeared #1959

**Comment by Turrin66** [comment]
I've notice this has happened with any item I've sold and bought back from vendor, is there any fix for this?

**Comment by Evildoor** [comment]
Not yet. Just avoid doing that.

**Comment by Evildoor** [comment]
Fixed in 18.12.2015 patch.
