### ISSUE TITLE
Wild Hunt live event progress doesn't count towards completion

### ISSUE THREAD

**Issue by Bst007** [WarEmu/WarBugs#19196]
Good day! I faced the following problem:
I completed all 7 tasks of the Live Event: Wild Hunt. All 7 are marked completed. But on the final line “Complete all Wild Hunt tasks” writes only 6/7, and impossible get final award "Blessed Hide of Kurnouse".
It seems to me that “Masters Huntsman page” is not considered, but that’s full completed 16/16. My other four characters have a similar problem, this task “Masters Huntsman page” is complete, marked completed, but not counted as completed.
![001](https://user-images.githubusercontent.com/86181079/122664756-a5d7d200-d1e6-11eb-9bac-b1c0e0d747a1.jpg)
![002](https://user-images.githubusercontent.com/86181079/122664757-a83a2c00-d1e6-11eb-857e-85828c55530d.jpg)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. I'll add this report to a related issue.

**Comment by lilimx** [comment]
dublicate / related to  #19183

**Comment by Bst007** [comment]
> dublicate / related to #19183

Thank you for your attention to my problem.
I looked at the issue of other people, my problem exactly coincides with [#19179](https://github.com/WarEmu/WarBugs/issues/19179)
