### ISSUE TITLE
Task completion bugged Elf Scenario not posting completed

### ISSUE THREAD

**Issue by zarrathos** [WarEmu/WarBugs#19199]
![image](https://user-images.githubusercontent.com/57928588/122676217-19f48480-d1ab-11eb-8eb9-8835aafd7800.png)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. This issue is already known, for some reason the task won't update correctly.
I'll add it to the related report.

**Comment by lilimx** [comment]
dublicate / related to #19179
