### ISSUE TITLE
Hunter's Vale Final Boss - Nature Gates are healing itself

### ISSUE THREAD

**Issue by SireGoodman** [WarEmu/WarBugs#19190]
Hi,

My group and I were stuck on the last boss fight of HV.

For some reason, the nature gates kept getting their health back after we were hitting them, when their health was around 90% or 30%, turning the actual fight into an unending one.

The boss itself was around 50-60% if I remember well. Because the gates could not be destroyed, we could not attack him.

Unfortunately I do not know how to reproduce the bug as we all left the dungeon after finally wiping since we had been fighting for 20 or 30 minutes and were all dejected. 

I hope this is fixable!

Thank you very much in advance.

Kind regards,

Frieder

N.B: I believe another player had the same issue, with luck that player can upload image or video evidence that would help. I did not think to take any of that (I do not have a capture software on my pc) Apologies.

**Comment by Tesq** [comment]
it happened similary the same but on boss instead while klilling the gates on a failed run of mine. But last one got no problem so duno how replicate. IN that run we happened to wipe and have some ankward respawn bug as i reported in  https://github.com/WarEmu/WarBugs/issues/19187

**Comment by geezereur** [comment]
I had the same happen to my order group we all missed the loot because of it happen twice........
