### ISSUE TITLE
Herald of Nurgle at talabecland glitched

### ISSUE THREAD

**Issue by Lanzapalillos** [WarEmu/WarBugs#19194]
**Expected behavior and actual behavior:**

NPC "Herald of Nurgle" is moved down a bit down a hill and one can't interact with him.  located next to Talabecland destro warcamp.

**Steps to reproduce the problem:**

walk up to him at 22137, 7835 to meet him

**Testing Screenshots/Videos/Evidences (always needed):**

![bugged](https://user-images.githubusercontent.com/84939342/122658429-7769e080-d16d-11eb-9513-f40d40706a9b.jpg)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
I will add your report to our "NPCs not standing at the right place/stuck somewhere"-compilation.

**Comment by lilimx** [comment]
related to  #16938
