### ISSUE TITLE
DESTRO QUEST "Von Rhine's Express"

### ISSUE THREAD

**Issue by Hauclir** [WarEmu/WarBugs#192]
![hauclir_002](https://cloud.githubusercontent.com/assets/7598530/3487856/3250918c-04ac-11e4-93da-8f249a07fd13.jpg)
![hauclir_004](https://cloud.githubusercontent.com/assets/7598530/3487857/67bf4e30-04ac-11e4-8ee7-fff03dbdc15b.jpg)
NPC QUEST GIVER: Konrad Schulman
After killing 8 Salzenmund Tracker's and finally getting 8 Von Rhine's Orders from them(they don't always drop it) the quest did not register any of the Von Rhine's Order I picked up still shows 0/8.

**Comment by milosxe** [comment]
Objectives for this quest have been changed to:

Salzenmund Trackers 0/8
Kill Salzenmund Trackers 0/8

I guess it's a workaround until the quest items are usable.

**Comment by Reggaewaldo** [comment]
Closing since we cannot fix the item use yet.
