### ISSUE TITLE
NPCs missing voice lines

### ISSUE THREAD

**Issue by Eckenfeld** [WarEmu/WarBugs#19203]
None of the NPCs seem to ever use voice lines whether clicked or or talked to, this issue seems to affect several players since the last update, after asking ingame. I've done a clean reinstall, and switched between 64 and 32 bit, as well as done the repair a few times, to no avail.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. But this looks more like an issue on your side.
So I can't see your files now... but replace these three:

video.myp [https://mega.nz/file/QLoh1ApL#Y1n3QZp5Pr0r4ggyFHVUsRnvbEy80uu9GNSjeu5YK98]
audio.myp [https://mega.nz/file/wa412QyA#MbwQ7X8M_bgUTkG5YLBRyziDVNgXHCXZM0nyrVbAmuU]
vo_english.myp [https://mega.nz/file/5XoSgQZB#cvqwDT1lI2iWd8FQLmcV2yYx_dESOuu2mPAN3rD17LI]

**Comment by Eckenfeld** [comment]
Replacing those worked! I think the installer just failed to install them correctly, somehow.
