### ISSUE TITLE
Pet Summoning Issue

### ISSUE THREAD

**Issue by denixius** [WarEmu/WarBugs#19201]
I would like to send an inquiry about the pet summoning situation. I searched the forum, but I can't find anything about this, so this may only happen in my game. Still, I want to report it to this forum, too. I have created a High Elven White Lion character, sometimes (not all the time), when I summon my War Lion, the icon of this skill glowing, but my War Lion won't appear. I have to use deactivate the skill and activate it again to summon the War Lion. This issue is happening when I call my mount, sometimes my War Lion is with me, sometimes not. After unmounting from the mount, my War Lion skill glowing, but my pet won't show up.

I hope I can find a solution to this? Is there something wrong with my game, or a known bug? Also, my pet sometimes disappearing or resetting the skill. Sometimes the pet is disappearing by itself, and summoning again.

All the best,
Deniz

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
Could you post a little video or some screenshots, where we can see your bars and your missing lion?

**Comment by denixius** [comment]
Hi,

I will record a video about it and send it here as soon as possible!

Cheers,
Deniz

**Comment by denixius** [comment]
Hi,

Here is the video, and in this video, my pet disappearing when I got the quests. This is happening from time to time with different situations, like just wandering around, in a fight, in a city, or etc. 

https://www.youtube.com/watch?v=HyxQ6Z2DqYM

All the best,
Deniz,

**Comment by lilimx** [comment]
Hey,

this isn't a bug :D 
This happens everytime when you level up. The mount disappears due to the new calcualtion of its stats. 
The same happens when you enter a RVR area.

**Comment by denixius** [comment]
So, it is actually a normal thing when I experience this pet disappear from time to time. That's weird. I don't remember a thing about this back in time. :D
