### ISSUE TITLE
Hunters Vale - Kurnous multiple mirror phase

### ISSUE THREAD

**Issue by Celianazaniah** [WarEmu/WarBugs#19206]
hello, we encountered a bug today on the last boss of HV, when the boss is to transform into a wolf, he once again made the mirror phase and once the add phase + mirror so that we have put 26 minutes on the end boss
[https://www.twitch.tv/videos/1063169898](url)

**Comment by lilimx** [comment]
Hey,

I've saved the VOD with the fight as a back up. It's too big for Github, 
So poke me and I will upload it.

**Comment by lilimx** [comment]
A player reported a similar issue on the discords (22/6/2021). Waiting for the report.

**Comment by Megadwa** [comment]
im this player here is the full Kurnous run (about 25 min before we gave up)

https://www.twitch.tv/videos/1066064235
