### ISSUE TITLE
[Hunter's Vale] ToK Completion Issue

### ISSUE THREAD

**Issue by Zahaqiel** [WarEmu/WarBugs#19205]
It appears there are circumstances under which it is possible to get all seven ToK achievements for the Wild Hunt event, but not be credited as having achieved them:

![HV ToK](https://user-images.githubusercontent.com/2038205/122755761-d1d38000-d2d8-11eb-9f95-9c5d8da1a7db.jpg)

Unfortunately I cannot confirm the exact order I completed them in, but the Fallen Hunters was the last one I managed to complete.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
This issue is already known and a fix is pending. Please wait for the upcoming hotfix.

**Comment by lilimx** [comment]
dublicate  #19179
