### ISSUE TITLE
Quest : All Wrapped Up - unlootable quest item

### ISSUE THREAD

**Issue by Varnosh** [WarEmu/WarBugs#19204]
Hello,

Quest : All Wrapped Up
Zone : Wulfsiege
Trouble : Quest item should be lootable from Writhing Victim in the area. These Writhing victims cannot be looted. Cursor hover shows the lootable hand, but clicks do nothing, no matter how close you stand from the target.

![TEMP](https://user-images.githubusercontent.com/33899047/122755265-0b829780-d295-11eb-84a3-d121a2db167e.png)

**Comment by Lheana** [comment]
The quest explicitly says that you need to find Gunther, not Writhing Victim.
