### ISSUE TITLE
Khaine's Altar Voidcloak appearance NOT changeable, description text incorrect.

### ISSUE THREAD

**Issue by Goatfish01** [WarEmu/WarBugs#19208]
Khaine's Altar Voidcloak is unable to be altered appearance wise even though it says it can be. Also item text is off, describing it as a "both hands" and "Great Accessory". WTF does this even mean? I just want to change the appearance, its happening on 2 of my Characters, both pretty new.
![Malice_000](https://user-images.githubusercontent.com/86266344/122827932-a3d74700-d2aa-11eb-81d3-05223c7fe2ad.jpg)

**Comment by lilimx** [comment]
Hey,

could you please rewrite this ticket and put some information into you're ticket, not just only in the titel :D

**Comment by lilimx** [comment]
Hey,

okay, found your post hidden in the code!
