### ISSUE TITLE
Magus specable abbility Disolving Mists from changing tree doesnt work

### ISSUE THREAD

**Issue by Vdovics** [WarEmu/WarBugs#1920]
Animation of casting missing same as sklil effect. Tried respec several times, relog, but doesnt help.

**Comment by Renork** [comment]
Yep :>

**Comment by ozarmidrashim** [comment]
DM works fine on dev. Please confirm that this is not the GTAoE cursor out of range bug.

**Comment by Renork** [comment]
You're right Aza, it's the range bug. DM is working, just tested it a few times.
