### ISSUE TITLE
Ch22 in Caledor (Order) Orbs are broken.

### ISSUE THREAD

**Issue by Klod91** [WarEmu/WarBugs#19202]
Ch22 in Caledor (Order) is broken again. Can't click on the orbs. 
**Sometimes** you can click on **some** of them, but for the most part it is broken and not possible to beat.

The orbs have 0% HP and you don't get the "hand" animation when mousing over them, if that helps determine the problem.

**Comment by lilimx** [comment]
related to the closed report  #18531

**Comment by Tesq** [comment]
i saw something like that in destru aswell

**Comment by madregit** [comment]
same for destro eataine, did one today and cant click the orbs. reikland ch22 is missing one mob, cant start stage 2

**Comment by lilimx** [comment]
Fixed with patch 18/09/2021
