### ISSUE TITLE
Wild Hunt - Fallen Hunters not changing class

### ISSUE THREAD

**Issue by Hiftem** [WarEmu/WarBugs#19209]
In the Wild Hunt, the Fallen Hunters aren't changing classes when you re-enter a HV instance as they did previously (earlier today and yesterday).  Instead, the same class of hunters are remain in the same locations.  Was this intentionally changed in the latest patch, or was it accidently affected by other changes?

Thanks!

**Expected behavior and actual behavior:**  Expect the corpses to change to different classes when you re-enter a HV instance

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by wargrimnir** [comment]
Did you actually clear the dungeon?

**Comment by Hiftem** [comment]
We cleared the dungeon, but we didn't complete it within the PQ time limit.

**Comment by Tesq** [comment]
if you kill last boss dungeon cant reset so body wont change i think its intended, wait 18 h

**Comment by lilimx** [comment]
Hey,

as Tesq suggestion, could you please confirm if they stay the same after the 18h lockout?

**Comment by Hiftem** [comment]
I went back into HV today, and the bodies are now changing as I would expect.
