### ISSUE TITLE
Bloodlord belt for whs is not working for ToK unlock and set completion

### ISSUE THREAD

**Issue by bisbalien** [WarEmu/WarBugs#19219]
Equiping Bloodlord lash for wh i do not get the armory / tok unlock
![Sinbearer_005](https://user-images.githubusercontent.com/86349663/123070563-8b873980-d41c-11eb-8caf-388444244159.jpg)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
I will add your report to a related issue.

**Comment by lilimx** [comment]
dublicate  #15597
