### ISSUE TITLE
[Bastions stair] infinite patience (quest)

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#19211]
you need click the itiem near the altar, but it does not work
![Sintoras_091](https://user-images.githubusercontent.com/7527415/122893551-b7d08680-d346-11eb-9966-efb22bd0d261.jpg)

**Comment by Kabucoror** [comment]
It worked fine for me. From the SS it seems you have an offensive target too, that may cause the issue as you need the altar as only active target.

**Comment by Tesq** [comment]
i had it target to make the screenshot.....

**Comment by Lheana** [comment]
But what Kabuco explains you is that you apparently also had the Pike targeted that counts as an offensive target. Be sure to only have the Altar targeted

**Comment by Kabucoror** [comment]
You have two targets active. As an example if you have an offensive and a defensive target and do an emote it always chooses the offensive one. Same applies for your issue here.

**Comment by Tesq** [comment]
re tryed with tareget today and it work, so duno what was but it werent the target; anyway closing this
