### ISSUE TITLE
[SW] Whirling Pin sometimes doesn't knockback when moving.

### ISSUE THREAD

**Issue by Kaelang** [WarEmu/WarBugs#19210]
**Expected behavior and actual behavior:**

Whirling Pin should act similar to a Disengage from WoW. It should identify your characters starting point and throw you back X yards. Unfortunately sometimes when casting the ability (typically if moving) only the slow effect goes off and not the knockback. Sometimes this can happen when stationary. 

**Steps to reproduce the problem:**

Cast Whirling Pin whilst moving forward. Attempt to do a backspin Whirling Pin. 

https://www.youtube.com/watch?v=v8qJSbxAXvo
https://www.youtube.com/watch?v=cm_RYQZkdmY

**Comment by Kaelang** [comment]
I'm dumb.

**Comment by wargrimnir** [comment]
hide the evidence!
