### ISSUE TITLE
Destruction Ch22 Eataine, Reikland is not working

### ISSUE THREAD

**Issue by madregit** [WarEmu/WarBugs#19216]
Eataine ch22 cant click last boss orbs and reikland ch22 is missing 1 mob, cant start stage 2.

**Comment by madregit** [comment]
> Eataine ch22 cant click last boss orbs and Reikland ch22 is missing 1 mob, cant start stage 2.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
Please only one issue per ticket and we need more information. Where, when, 1-2-3 screenshots.
So I'll close this ticket, please open a new one and follow the template structure for reports.
Here a little link how to: https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37703
