### ISSUE TITLE
Outdated text in Battle of Remembrance dwarf t4 epic quest 

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#19215]
**Expected behavior and actual behavior:**
The Treasure pile is actually located (was moved to?) near the wyvern nests below Dammaz Skarr but the quest text still sends the player to a hut above Skarr.

**Steps to reproduce the problem:**

complete step 4 of the dwarf t4 epic quest and start step 5

**Testing Screenshots/Videos/Evidences (always needed):**

![](https://cdn.discordapp.com/attachments/329292495336767488/857009254635798549/unknown.png)

**Comment by Rubyeclipse-war** [comment]
@onemantankwall This is over a year old, but just wanted to say thank you for flagging this. 

I've re-written the text for this quest and updated it to more accurately reflect where the player should go. This will go live with the next patch. Here's what you should see going forward:

![image](https://user-images.githubusercontent.com/60584990/189547643-ed0c793e-8f97-435f-91fd-a13935a1a520.png)

**Comment by lilimx** [comment]
Fixed with patch [14/09/2022]
