### ISSUE TITLE
"Horn of the vale wolf" pet itiem type inconsistnetly (itiem)

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#19212]
since " warlord fell hound" ( EDIT: and "red fart squig"), another pet /companion itiem, is not pocket then the vale woulf should not be aswell; since companion in live didnt took pocket slot ( real no reason for it) and dont require cast time to summon (cuz there is no reason for it, it's not a mount which is probably why it was assigned as error).
Also since pet is limited to one only at time by 1-2 years or so and not only hide /auto vanish if hit in combat but they ger removed again no reason to take place of other pocket itiems messing your equip (beastlord book or whatever in future we gona have with lotd or we have right now such whistle or new craftable "animal horn" from HV).

**change suggested ->** _remove in database the pocket type and cast time, moreover fix the description as the warlor's fell hound and show the appropriate icon for the companion in the buff/debuff bar ( the icon is simply the itiem icon in backpack)._

**edit:** i also added "red fart squig" it have same description of "fell hound" and not pocket , while also show icon but it seems to suffer the same cast time label; so even that should be removed; all 3 should be:
- not pocket
- istant cast 
- not consumable (of course)
- show backpack icon in buff/debuff
-  have appropriate description.

![Sintoras_094](https://user-images.githubusercontent.com/7527415/122907879-da1cd100-d353-11eb-9f83-6d60d52b7ef9.jpg)
![Tesq_155](https://user-images.githubusercontent.com/7527415/122908726-befe9100-d354-11eb-86fa-46a53d42983d.jpg)
![Tesq_157](https://user-images.githubusercontent.com/7527415/122911611-c4110f80-d357-11eb-9411-45e9158d67bd.jpg)

**Comment by lilimx** [comment]
Hey Tesq,

thank you for your ticket. 
But it's intended that the horn is a pocket item and you need to equip it to summon the wolf.
So it's not a bug.

- closed
