### ISSUE TITLE
The Greater of Two Evils - step 12

### ISSUE THREAD

**Issue by Ginpachi95** [WarEmu/WarBugs#19220]
The step 12 of the quest which require to interact with  Doctor Wirt's Clothes doesn't work, I cannot interact with it, tryied to give up and take quest again as disconnect and reconnect and /reloadui didn't fix it.
https://cdn.discordapp.com/attachments/857269352461631491/857269372246425640/unknown.png

**Comment by Lheana** [comment]
This will be fixed with next patch. You'll have to abandon the quest and retake it.
