### ISSUE TITLE
Satchel and Boxes don't convert its currency

### ISSUE THREAD

**Issue by Ecilchosen** [WarEmu/WarBugs#19229]
Hey,

so I'll rewrite this ticket now, because no one wrote something inside the text box and the reports are low on information.
- All Satchel's and Boxen can't currently open by any control
- The Auction House works (not related for this ticket)

_(Edited by Lilim)_

**Comment by Ecilchosen** [comment]
![image](https://user-images.githubusercontent.com/82473452/123299449-d5097e80-d519-11eb-886a-486d32c12928.png)

**Comment by Samsonacer** [comment]
I also can't click on the satchels or Auction house

**Comment by Ecilchosen** [comment]
ill tryt all over praag to and restart the game and rapir it and dont work

Den tors 24 juni 2021 kl 19:00 skrev Samsonacer ***@***.***>:

**Comment by Moratil** [comment]
![Karmaril_000](https://user-images.githubusercontent.com/22457639/123313519-e3f82d00-d529-11eb-9009-2206d2df7072.jpg)

Same for me: can't open the Dominator boxes I bought to get the relevant Emblems

**Comment by Ecilchosen** [comment]
Ill hope its fixts now


Den tors 24 juni 2021 kl 20:23 skrev Moratil ***@***.***>:

**Comment by lilimx** [comment]
fixed with hotfix 24/06/2021
