### ISSUE TITLE
Bug Report quest

### ISSUE THREAD

**Issue by Pippochelagga** [WarEmu/WarBugs#19222]
I think it's a bug of this quest, it won't let you go on.
![Dastir_000](https://user-images.githubusercontent.com/86386482/123180293-4c440180-d48b-11eb-8cd9-379490a04a64.jpg)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
This issue is already known so I'll add it to the related issue.

**Comment by lilimx** [comment]
dublicate #19220
