### ISSUE TITLE
Hovering over items no information appears

### ISSUE THREAD

**Issue by bisbalien** [WarEmu/WarBugs#19227]
Just logged in aftrer the restart and this issue appears to be happening on my account.

**Comment by bisbalien** [comment]
![Abattoir_000](https://user-images.githubusercontent.com/86349663/123289981-9247a680-d519-11eb-9b13-3363c2caad02.jpg)
![Abattoir_001](https://user-images.githubusercontent.com/86349663/123289988-94116a00-d519-11eb-81c1-edb134a27c82.jpg)

**Comment by lilimx** [comment]
Hey,

it's not a bug. You have to restart the game completely.
So close game and launcher, restarte the launcher....count to 5 and start the game.
