### ISSUE TITLE
[Inevitable City mapping] The Monolith is "the Sacellum"

### ISSUE THREAD

**Issue by Zahaqiel** [WarEmu/WarBugs#19228]
It appears that the region making for the IC is incorrect.

When approaching the Monolith, the title over the mini-map says "The Sacellum" instead of "The Monolith", as does the mid-screen popup text when entering the area.

Obviously the Monolith is next to _the Lyceum_, but the Sacellum is on the opposite side of the map.

Relatedly, the Sacellum is similarly incorrectly marked as "The Undercroft", and the Undercroft is just "The Inevitable City".

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
This issue is already known, I will add it to a related issue.

**Comment by lilimx** [comment]
dublicate / realted to #18475
