### ISSUE TITLE
Destro re-captured Chaos Waste keep from Order but the zone locked anyway 10-15 seconds later

### ISSUE THREAD

**Issue by bloodmasked** [WarEmu/WarBugs#19223]
My 4 man entered the CW keep after it was captured, we killed everyone inside and stood on the flag to retake the keep. The keep turned red meaning we took it. But then 10-15 seconds later the zone locked.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
Did you make some screenshot? Can you add a bit more information like the timestamp or so?

**Comment by bloodmasked** [comment]
It was very close like I said 10-15 seconds after we had the keep taken

**Comment by lilimx** [comment]
Hey,

I meant the the date and and a time, so the devs can check the logs

**Comment by bloodmasked** [comment]
I wrote this bug report a couple minutes after the zone locked so maybe can find the time this was made.

**Comment by lilimx** [comment]
Hey,

im going to close this ticket now due to no proper feedback, which be can use.
