### ISSUE TITLE
Not showing item info

### ISSUE THREAD

**Issue by TheFloyd85** [WarEmu/WarBugs#19237]
**Expected behavior and actual behavior:**
Expected behavior: when hovering over an item, you see the item information (in your inventory of equiped items)
Actual behavior: it does not show information, you do not see what the item is

**Steps to reproduce the problem:**
Open inventory or character screen and hover over an item
note: i have this problem with my greenskin shaman, my empire witch hunter does not have that problem

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/86433042/123317041-dc3a8780-d52d-11eb-9e80-43d3de05a367.png)
![image](https://user-images.githubusercontent.com/86433042/123317125-f07e8480-d52d-11eb-9183-9e383c867fa2.png)

**Comment by lilimx** [comment]
Hey,

I've already close a similar ticket.
Just for the files, you've closed your game and launcher completely?
Restart the launcher, wait 5 seconds and start the game again.
Does it fix your problem?

**Comment by TheFloyd85** [comment]
It is fixed.
Thanks for the solution!
