### ISSUE TITLE
Bright Wizard - Abnormal Damage Numbers - Resolved after Logging Out

### ISSUE THREAD

**Issue by Defeldar** [WarEmu/WarBugs#19239]
**Expected behavior and actual behavior:**
On 6/25 I was doing abnormally high amounts of damage on my bright wizard, Supermarine. My fireball crit one individual for approximately 3,500 (4,300 including mitigation) and this abnormally higher amount of damage was replicated consistently across abilities. The below image is an example of this. It also occurred in a Dragon's Bane scenario - Kaelang was crit by one of these fireballs for over 3,400 (as I recall). 

![Fireball before logout](https://user-images.githubusercontent.com/86453347/123366061-7fe36200-d545-11eb-9573-a4512c8cbbff.jpg)

Additionally, I tried hitting some training dummies and crit them for 4k each crit (do not have screenshot for this one).

After re-logging, I tried hitting the training dummy again and hit it for 3314 WITH the onslaught proc. Both of these tests were done with 100 combustion (I do not yet have the 15% crit from 4 piece BW sov so this should not be taken into account.) My damage bonus for both of these tests was 222 (960 intelligence and 150 magic power). Also to note, I have Bloodlord weapon with 5% modifier equipped.

![Fireball on training dummy after logout](https://user-images.githubusercontent.com/86453347/123367154-75c26300-d547-11eb-8f57-3e904f82db67.jpg)

I do not have any idea what caused the problem and cannot reproduce it. However, this is not the first time it has occurred - it happens 1-3 times a week and resolves itself once I re-log. It is instantly noticeable, but I have not seen it playing any other class than bright wizard.

**Comment by lilimx** [comment]
Hey,

next time if this happen, please do a .getstats screenshot

**Comment by bloodmasked** [comment]
Were you in a city just before and made champ?

**Comment by Defeldar** [comment]
I’ll get some better info next time it happens, including a .getstats.

Also, was not in a city on that evening.

**Comment by Kaelang** [comment]
I remember you mr bright wizard. Glad you noticed something was funky too! As Lilim mentioned, if you find yourself nuking people as hard as you was last night, try get some additional info and we can take a look. :)

**Comment by spacestarkid13** [comment]
can confirm a big damage, I was on the same sc as a dok 75 and got hit by Fiery Blast on 2300 (not on screen) and Scorched Earth on 1150.

![Warhammer Online - Age Of Reckoning Screenshot 2021 06 25 - 05 32 37 59](https://user-images.githubusercontent.com/16030337/123510272-24b78980-d683-11eb-943f-f0dbfc649921.png)

I have a sorc 84 and it's almost impossible to achieve such numbers in rvr.

**Comment by lilimx** [comment]
Hey,

thank you for confirming it. But we need to know where it come from. 
So that's the reason we need his .getstats screenshot.
We don't doubt on his dealt dmg.

**Comment by lilimx** [comment]
maybe related with #18744

**Comment by Vylor** [comment]
[](https://media.discordapp.net/attachments/732012484172578847/947699286475423754/unknown.png) 
I believe this occurred with my sorc last night and I happened to grab a screenshot of getstats.

**Comment by lilimx** [comment]
Fixed around the Patch from 9/03/2022
