### ISSUE TITLE
Spirit of Kurnous phase 2 getting stuck at portal and not progressing to add phase

### ISSUE THREAD

**Issue by Rydiak** [WarEmu/WarBugs#19238]
![Rydiak_516](https://user-images.githubusercontent.com/15963532/123361672-1a877500-d535-11eb-8f4f-332c33564ecc.jpg)

Spirit of Kurnous is getting stuck while trying to enter his portal to start phase 2 (the add phase), and the boss fight is not progressing.  The PQ timer keeps ticking down of course, making the dungeon unfinishable.

**Comment by lilimx** [comment]
Note:

Rydiak said it happen in stage 2 but it's similar to issue #19189
it could be a dublicate!

**Comment by Rydiak** [comment]
Bug is still happening
![Rydiak_533](https://user-images.githubusercontent.com/15963532/147303763-70b909f0-0e49-4ec4-87fb-5794b9608551.jpg)

**Comment by Rydiak** [comment]
Appears to happen when the boss was knocked down in phase 1 and has the Immovable buff on him.
