### ISSUE TITLE
HV Award not working after patch from 24 june

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#19234]
After done a succesful HV run on my SW Phenicia I selected the Purple Horn award which summons a pet. In Altdorf I rightclicked the horn and nothing happened. No pet or anything. 
Already relogged a few times, changed to alts but that didnt help

**Comment by lilimx** [comment]
Hey,

so you sloted the Horn and put it in your action bar and casted it again?

**Comment by wiscel** [comment]
I should have written: I rightclicked the item, and it disappeared from my inventory, its not in the other inventory pouches, just gone completely

**Comment by lilimx** [comment]
Hey,

maybe you've slotted it?

![grafik](https://user-images.githubusercontent.com/23266079/123318524-954d9180-d52f-11eb-9942-ded637069da1.png)

**Comment by wiscel** [comment]
Silly me, its indeed in the pocket slot, thanks. You can close the topic.
