### ISSUE TITLE
Lootbag not working after patch 24 June

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#19235]
Today I got a white bag from Praag, I opened the bag, selected the Invader medallions, and nothing was added in my bag.

Already relogged a few times, changed to alts but that didnt help

**Comment by lilimx** [comment]
Hey,

is it fixed after the patch?

**Comment by wiscel** [comment]
Just had a purple bag from Shadowlands, the Invaders were added to my inventory. Thanks

**Comment by lilimx** [comment]
Hey,

thanks for the confirmation. 
- closed
