### ISSUE TITLE
Bags and Quests not working since patch 24 June

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#19233]
After done a succesful HV run on my SW Phenicia I selected the Purple Horn award which summons a pet. In Altdorf I rightclicked the horn and nothing happened. No pet or anything. Later I got a white bag from Praag, I opened the bag, selected the Invader medallions, and again nothing added in my bag.

Another strange thing also happened The Hunters Vale kill quest (and other killquests) don't update after killing other players. 

Already relogged a few times, changed to alts but that didnt help

**Comment by lilimx** [comment]
Hey,

thank you for your ticket,
But there are too many issues in one ticket. Please open a new ticket for each of your issues.
