### ISSUE TITLE
Magus tactic: Daemonic Pack not working

### ISSUE THREAD

**Issue by Rildetarma** [WarEmu/WarBugs#1923]
The career tactic located in the Magus Daemonology Tree: "Daemonic Pack" is not working. This tactic should increase the magus' toughness while a daemon is present. Instead of increasing toughness by 120-ish, it will only add 1 point. This is a bug.

**Comment by ozarmidrashim** [comment]
![shadar_005](https://cloud.githubusercontent.com/assets/6764164/11456974/3930d7a8-9693-11e5-8da0-3e7cba6e9d18.jpg)

**Comment by ozarmidrashim** [comment]
Oh, it's a character screen display issue. Fixed.
