### ISSUE TITLE
Hunters Vale respawning sprites at the summon circle

### ISSUE THREAD

**Issue by lilimx** [WarEmu/WarBugs#19231]
Hey,

these sprites are spawning at the circle and even respawn really fast after we kill them. They are still there after we did the summon, but they haven't followed us to the boss.
![Toffi_025](https://user-images.githubusercontent.com/23266079/123302506-0e8fb900-d51d-11eb-8bf7-b43c8ee4c233.jpg)

Instance ID:
![id](https://user-images.githubusercontent.com/23266079/123302584-25361000-d51d-11eb-810f-4b8d3c7b7225.png)

**Comment by MaxHayman** [comment]
Did you skip any bosses? :)

**Comment by lilimx** [comment]
Haha, yes.... the Sprite one. 
So this is an intended punishment?

**Comment by MaxHayman** [comment]
In the words of Kurnous, "You will suffer for your impudence"

**Comment by lilimx** [comment]
But Daaaad!

Okay, I will close the ticket
