### ISSUE TITLE
Kill Quests not working after patch 24 June

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#19236]
After doing a 3rd succesful HV run on my SW Phenicia I took the Hunters Vale kill quest from the questgiver after you kill last boss. 
I went to RvR to kill players but, when I opened the Quest description it , the description was of the keepdefense quest in Caledor. 

I relogged, the quest information then was back to normal but whenever I kill someone in Rvr the kills dont add up in the Hunters Vale quest (also my other killquests don't add up) 

Already relogged a few times, changed to alts but that didnt help

**Comment by lilimx** [comment]
Hey,

is it still bugged after the hotfix?

**Comment by wiscel** [comment]
The killquests are all working again, thanks

**Comment by lilimx** [comment]
Hey,

you're sure you've get enough kill contribution?

**Comment by wiscel** [comment]
Yes, sometimes it was solokills. I will check again tomorrow after I've done my HV run.

**Comment by wiscel** [comment]
Done HV again. The kills are adding up in killquests.

**Comment by lilimx** [comment]
Hey,

so it's fixed. 
If you're the opinion it's not fixed, please open a new ticket and we will investigate again.
