### ISSUE TITLE
Ranked games duration incorrect

### ISSUE THREAD

**Issue by bloodmasked** [WarEmu/WarBugs#19246]
The game tied with 1 minute remaining and the scoreboard said the game was 2 minutes long when it was more like 14 minutes long

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
Please always provide some proper screenshots or a video, but atleast a detailed description of the issue.
We can't check your issue if we only have 1-2 short sentences.

**Comment by lilimx** [comment]
Hey,

im going to close this ticket now due to no feedback.
