### ISSUE TITLE
Layout editor bug - exit button doesn't work

### ISSUE THREAD

**Issue by bloodmasked** [WarEmu/WarBugs#19241]
You get stuck in the editor and have to restart game

**Comment by bloodmasked** [comment]
![image](https://user-images.githubusercontent.com/6406832/123371306-9df8a300-d5d5-11eb-9c13-60928f94841c.png)
And then when you are back in the game, it puts alot of your interface at the top right corner of the screen (minimap, enemy hud, state of the realm, etc).
Someone else mentioned this happening to them and same has happened to me.

**Comment by bloodmasked** [comment]
Don't try to replicate before u made a backup because it totally break ur interface

**Comment by lilimx** [comment]
Hey,

I can't reproduce your issue.
Could you write a step by step guide what you did?

**Comment by lilimx** [comment]
Hey,

okay, now it happened to me.
Did you open the Layout Editor really early after you login into your character?

**Comment by lilimx** [comment]
How to reproduce:

![grafik](https://user-images.githubusercontent.com/23266079/124379720-f22c1300-dcb8-11eb-86f6-4be70e31ab6b.png)

- so this is what a borked version looks like (almost all addons are in the left upper corner)

- When you click "exit" and won' save your settings ("no"), you can't leave the Layout Editor. (One thing that I noticed is that, when you click "yes" or "no") the big ranked leaderboard disappears.)

- Only when you click "cancel" and try it again with "yes", you can leave the Layout Editor.

**Comment by gittoaster** [comment]
This has trashed a couple of my characters layouts already.  You have to force a crash to exit and then when you log in your layout is trashed, and you still can't use the editor..
