### ISSUE TITLE
The Eidolon in chaos starting zone unable to award third staff option to magus

### ISSUE THREAD

**Issue by Khagan102** [WarEmu/WarBugs#19240]
I was able to "choose it" but then it said i was unable to move it in grey text.  I don't have a full inventory my influence was enough... really odd stuff here.

**Comment by Khagan102** [comment]
Upon relogging was able to recieve said staves upon log in
such an odd issue

**Comment by lilimx** [comment]
Hey,

thank you for you're ticket.
I'll close this issue. I guess it's a leftover from the bag/box from yesterday.
