### ISSUE TITLE
Invisible Crafting Supplies

### ISSUE THREAD

**Issue by Bosc6969** [WarEmu/WarBugs#19251]
**Expected behavior and actual behavior:**
Expected: When purchasing crafting materials, I should see those materials show up in the crafting bag. 
Actual: When purchasing materials the materials are invisible.

**Steps to reproduce the problem:**
When purchasing crafting materials, you see that the money is being spent and the materials are invisible in the crafting bag. You get an error "You could not move (crafting material)." But when you click on the empty slot where the item should be you can pick up said item and then drop it and it will show up. If you click the list view, you can see all of the items in the bag.

**Testing Screenshots/Videos/Evidences (always needed):**

https://user-images.githubusercontent.com/86559348/123547900-9bf72700-d730-11eb-94bd-6e198fa20512.mp4

https://user-images.githubusercontent.com/86559348/123547923-b9c48c00-d730-11eb-84a1-e09713f926f6.mp4

**Comment by Bosc6969** [comment]
I hope those videos make sense.

**Comment by lilimx** [comment]
Hey,

I've tried to reproduce it, but no chance, it's working for me.
If you have time, jump on the RoR discord, so we can check your game:
https://discord.gg/G9jDWgv

**Comment by lilimx** [comment]
A reinstall fixed the issue.

-closed
