### ISSUE TITLE
Fightin' Infightin' Rorg Bug

### ISSUE THREAD

**Issue by Cammykins7** [WarEmu/WarBugs#19256]
I'm trying to fight Rorg 'Eadbutta in Sparkstone Ridge(Death Peak) yet he has an orange name and is not attackable.

**Comment by lilimx** [comment]
Hey,

is he important for any kind of quest?
If yes, I need the quest and a picture from the quest + his current location

**Comment by Lheana** [comment]
I noticed it yesterday as I was working on the Epic Quest "Fightin' Infightin'", so it's already fixed on dev.

**Comment by Cammykins7** [comment]
He's part of an epic Quest for Thunder Mountain and possibly before. I've come back to the area and now the quest turn-in and Rorg are gone.

**Comment by Cammykins7** [comment]
@lilimx It's part of an Epic Quest chain relating to Thunder Mountain. 
![image](https://user-images.githubusercontent.com/86422828/123827631-ca126d80-d8ce-11eb-8b9f-cc985a20bf36.png)
