### ISSUE TITLE
[Zealot/RP] Trinket attributes are not swapped based the class heal/dps mechanism

### ISSUE THREAD

**Issue by mdrntms** [WarEmu/WarBugs#19252]
**Expected behavior and actual behavior:**

When equipping an event trinket, the stats should be swapped based on the zealot/rp harbinger/rune of breaking stance. The intel points should be swapped to willpower and vice versa.

**Steps to reproduce the problem:**

Equip a trinket and swap between heal and dps stances, to see that the attributes are not updated.

**Comment by Zomega-WAR** [comment]
With the current Hunter's Vale event item (+21 willpower):

![image](https://user-images.githubusercontent.com/60266177/123559457-055c5180-d794-11eb-8bd8-4db392e82dcc.png)

Harbinger turned OFF (heal mode)

![image](https://user-images.githubusercontent.com/60266177/123559447-f8d7f900-d793-11eb-8449-5609ec0f23fe.png)

Harbinger turned ON (damage mode)

![image](https://user-images.githubusercontent.com/60266177/123559484-2ae95b00-d794-11eb-8fd1-2c1690984274.png)


I can't confirm the other stats, but Willpower on an event item seems to convert fine.

**Comment by Zomega-WAR** [comment]
Also, there are various issues with Harbinger not updating things properly when unequipping and re-equipping gear (https://github.com/WarEmu/WarBugs/issues/15181 is the master bug), but it doesn't seem that there is an extra specific bug with the event item slot, at least for Willpower.

@mdrntms what event item were you trying it with?

**Comment by mdrntms** [comment]
@Zomega-WAR

Hi,

yes i came to that conclusion by equipping and re-equipping a the trinket.

Trinket on, heal mode on:
![trinket_on_healmode_on](https://user-images.githubusercontent.com/55538767/123589761-facca700-d7e9-11eb-967e-bc56b5069a99.jpg)

Trinket off, heal mode on: (works, willpower is lower)
![trinket_off_healmode_on](https://user-images.githubusercontent.com/55538767/123589803-0a4bf000-d7ea-11eb-9ec1-810608b03d06.jpg)

Trinket on, dps mode on:
![trinket_on_healmode_off](https://user-images.githubusercontent.com/55538767/123589849-251e6480-d7ea-11eb-97ca-a98cf56f4c31.jpg)

Trinket off, dps mode on: (the stats are not lowered, maybe it is a display error or the stats are not taken into account)
![trinket_off_healmode_off](https://user-images.githubusercontent.com/55538767/123589894-35ceda80-d7ea-11eb-91d0-06e94303f1bb.jpg)

**Comment by lilimx** [comment]
Hey,

like your discussion. So I guess Zomegas link to Issue #15181 is a good idea.
So I will close this ticket, because it's a good addition to the "master bug"
