### ISSUE TITLE
IC Party bug and more

### ISSUE THREAD

**Issue by dylan6666666** [WarEmu/WarBugs#19267]
Was in a warband as a tank waiting to queue for Inevitable City. While waiting I guarded my assigned party member and my guard was functional, it worked. When we queued for the city, and I clicked the join button, my client crashed as I was on the Inevitable City loading screen. I restarted my game and loaded back in inside of the Inevitable City, but was party bugged in some way that resulted in me only being able to join party 2, and when joining party 2 showed up in party 5. No matter who joined party 5 with my, my guard ability did not work and said it could only be used on people in my group. On top of this, my game was stuttering severely when I normally run at a more than playable framerate. Twice in the city my client hard froze, requiring the process to be terminated in the task manager once, and once froze my entire OS and required a full hard reset of my computer and OS. Also, the first time my game hard froze in the City, it was on a frame that showed me as having just received 94,000+ renown and reaching renown rank 198. After the Inevitable City invasion was finally over, my client works fine and I'm having no issue grouping with anyone or using guard on someone in my group, or crashing, or stuttering.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket,
There is a related issue with crashing in IC and broken grps so I will add your ticket to this report.

**Comment by lilimx** [comment]
related to #18614
