### ISSUE TITLE
Stucking in scneario Phoenix Gate

### ISSUE THREAD

**Issue by Morrstein** [WarEmu/WarBugs#19260]
Hello in Phoenix gate scenario, if you play from order side on location under the bridge (some over 31783/37364) if you ride down from order spawn point u will stuck in rock.U cannot release even relog wont help so it will propably loose ranked sc for your team.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by GamesBondd** [comment]
This is the actual terrain, not really a bug. There are plenty of spots that you can get stuck into, in every SC or RvR map.
