### ISSUE TITLE
Solo ranked MMr stucked at 0

### ISSUE THREAD

**Issue by knickk** [WarEmu/WarBugs#19261]
**Expected behavior and actual behavior:**
after a few matches on day 1 my solo ranked MMR is stucked at 0
i had 12 games 2w-8l-2d
next game was a win so 3w-8l-2d but my MMR is still at 0 so now 13 games in total
so i did for the next match screenshot bevor and after
now its at 4w-8l-2d 14 games still at 0MMR

its now 1hr+ without change in MMr

**Steps to reproduce the problem:**
unknown

**Testing Screenshots/Videos/Evidences (always needed):**
bevor match 14
![Knick_111](https://user-images.githubusercontent.com/25160644/123696749-60f21200-d85c-11eb-8dc4-6b7375b94222.jpg)
win of match 14
![Knick_222](https://user-images.githubusercontent.com/25160644/123696744-5fc0e500-d85c-11eb-9c9d-12130e84694a.jpg)
still no MMR
![Knick_333](https://user-images.githubusercontent.com/25160644/123696748-60f21200-d85c-11eb-91df-162b4d565163.jpg)

**Comment by dalen** [comment]
You need to get a bit better win rate to get your MMR above 0
