### ISSUE TITLE
Lost a few abilities from hotbars after respec then flying

### ISSUE THREAD

**Issue by bloodmasked** [WarEmu/WarBugs#19269]
I used respec at nordland renown trainer, that changes my renown and spec to shield from dps dok. Then I went to flightmaster to go to talabecland. When I loaded in I was missing one of my assist macros and an ability from my hotbar.

Also other bug is that when you respec with new respec option, it doesn't update your renown trainer window. (But you can check your stat doll or .getstats to see that it did work). *note i used advanced renown trainer addon not regular one interface.

**Comment by lilimx** [comment]
Hey,

please one issue per report.
