### ISSUE TITLE
Server Status on Launcher

### ISSUE THREAD

**Issue by denixius** [WarEmu/WarBugs#19264]
Hi,

I'm not sure if it is bugged, but I want to send it anyway. I attached a screenshot that shows the launcher of the game. The server is currently offline, but the Web Server and Login Server seems online, I mean yellow, not red. If this indicates the current status of the server, it's bugged. If not, well, I don't know what it is. :D

Bests,
![Server Status](https://user-images.githubusercontent.com/52817043/123805836-183b6700-d8f7-11eb-9755-c78784b3812a.jpg)

**Comment by lilimx** [comment]
Hey,

the Web Server was online, like the login server, but the server where to play was not available at this point, so the access was blocked.
