### ISSUE TITLE
Standing Up on Horseback

### ISSUE THREAD

**Issue by denixius** [WarEmu/WarBugs#19265]
Hi,

This is a strange one; when I summon my horse, sometimes, I'm standing up on horseback. I attached a screenshot. When I move/ride my horse the action gets back to the riding position.

![Denixius_001](https://user-images.githubusercontent.com/52817043/123811531-00b2ad00-d8fc-11eb-9c84-68b41deeddb4.jpg)

Bests,

**Comment by lilimx** [comment]
Hey,

that's not a bug. switch on the launcher to the 32bit thingy.
