### ISSUE TITLE
Hidden Depths - Mount Gunbad, (Middle Wing)

### ISSUE THREAD

**Issue by Ramessu** [WarEmu/WarBugs#19277]
Nothing happens when clicking on the Mourkain Henge as instructed. Can not complete the quest.

![Hidden Depths - Mount Gunbad, Middle](https://user-images.githubusercontent.com/84376715/124326002-b1ff5000-db53-11eb-863d-d1e1fc85531d.png)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by lilimx** [comment]
Fixed with Patch 22/07/2021
