### ISSUE TITLE
Chosen pile of pelts bug

### ISSUE THREAD

**Issue by Cammykins7** [WarEmu/WarBugs#19279]
I'm doing the Epic Quest chain called Chosen and am in the part that relates to Ostland. I can't turn in the quest part that starts with a Mob's eye and ends/continues with the interaction with a pile of pelts. The Pile of pelts can't be interacted with. 
![image](https://user-images.githubusercontent.com/86422828/124362872-d7e52d00-dc05-11eb-9c37-a1c48ef63c77.png)

**Comment by lilimx** [comment]
Hey,

did the mob "Krul'Tor" spawn after you've clicked on the pile of pelts?

**Comment by Cammykins7** [comment]
@lilimx  I'm not able to click on the Pile to trigger his spawn.

**Comment by Lheana** [comment]
This will be fixed with next patch. You will have to abandon the quest and retake it after the patch.

**Comment by lilimx** [comment]
Fixed with Patch 22/07/2021
