### ISSUE TITLE
Quest pickup doesn't generate item in inventory: The Shadow of Azorgaron

### ISSUE THREAD

**Issue by DurinThornaxe** [WarEmu/WarBugs#19273]
I've tried abandoning and also relogging on the quest. I suspect the problem might be related to the fact you can pick the quest up from the NPC with the same name that is found in dwarf chapter 19. 

So after multiple tries I still don't receive Talisman of Cleansing Flame in my inventory, without which the final npc in Cinderfall is impossible to kill. 

Thank you for your work! Hope it gets solved :)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. This issue is already known.
So I'll add your ticket to the related report.

**Comment by lilimx** [comment]
dublicate / related to  #6403
