### ISSUE TITLE
Engineer Turret Disappears

### ISSUE THREAD

**Issue by JaqiC** [WarEmu/WarBugs#19271]
I have experienced my turret disappearing in Thunder Mountain right after I pull a mob.  It will drop fine, then promptly disappears when I pull anything.  This did not happen in any other area.  This happens when I drop my long range, medium range, and short range turret.  Here are some screen shots.

![Jaq_000](https://user-images.githubusercontent.com/75152388/124144933-03271b00-da52-11eb-83a8-2472eb4bc5f1.jpg)
![Jaq_001](https://user-images.githubusercontent.com/75152388/124144959-08846580-da52-11eb-99f2-1fb317490bbb.jpg)
![Jaq_005](https://user-images.githubusercontent.com/75152388/124144991-0de1b000-da52-11eb-9d44-7ef370f80613.jpg)

**Comment by lilimx** [comment]
Hey,

yeah, TM is a magical place. + on certain spots the turret doesn't give stacks.
This issue already known, so I'll add it to a related issue.

**Comment by lilimx** [comment]
relaated / dublicate to #18852

**Comment by lilimx** [comment]
similar to #19271
