### ISSUE TITLE
Bugged Quest: Nobility Quest in Troll Country, Felde Castle

### ISSUE THREAD

**Issue by denixius** [WarEmu/WarBugs#19272]
Hi,

In Troll Country, Felde Castle, I got a quest from Priestess Serilde, named Nobility. I killed 10 Blighted Believer, and it continues like that I should equip their robe and search the area. However, I can't equip Blighted Robe, because Priestess Serilde won't give me the robe as she told me in the quest description.

I think it's bugged.

Bests,

![Denixius_000](https://user-images.githubusercontent.com/52817043/124151935-bb2ce600-da9b-11eb-84ab-84c180bf184d.jpg)
![Denixius_001](https://user-images.githubusercontent.com/52817043/124151940-bc5e1300-da9b-11eb-82f9-26133df033bb.jpg)
![Denixius_002](https://user-images.githubusercontent.com/52817043/124151945-bcf6a980-da9b-11eb-9a47-0cd54a138634.jpg)
![Denixius_003](https://user-images.githubusercontent.com/52817043/124151965-c1bb5d80-da9b-11eb-9c00-b13b57617e55.jpg)

**Comment by lilimx** [comment]
Hey,

I guess you have to kill those people to get the robe.

**Comment by denixius** [comment]
Hİ,

I did. But never got a chance to find any robe. I killed like all of the Blighted Believer over the field. No chance.

Bests,
