### ISSUE TITLE
The Hunter's Vale timed quest bug - some bosses doesn't count.

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#19270]
I tried to do this quest day before, was failed with time.
Ok, I wasn't entered the dungeon for 18 hours, my lockouts was gone (checked with .lockouts command)
Joined new (for me, at least) party, none has lockouts there either, but only 1 guy who joined our party last
Just 1 out of 6. So 5 members (incl. leader) was without lockouts!
We entered inside, party engaged the fight with twins, then I took quest (where u need to kill all bosses in 45 min)
I joined my party, bosses (both) was above 80% HP still.
We killed them, proceed to the next, then next etc
Then I decided to check quest and noticed, that twins wasn't counted for me!
We finished dungeon, did it with 15 min left still, but quest wasn't complete for me.

**Expected behavior and actual behavior:**
Exp: Bosses should count for me if my party killed them and I don't have lockouts.
Act: it's not!

**Steps to reproduce the problem:**
No idea.

**Testing Screenshots/Videos/Evidences (always needed):**
As u can see, there is final chest, 15 min left still and twins are not complete
Also, there is strange string in the chat: "bound to the old instance... " and I've seen it after every boss killed - no idea what it is about.
![unknown_2021 06 30-18 50](https://user-images.githubusercontent.com/16439840/123994482-14cadd00-d9d6-11eb-960b-b174a900ce55.png)

Since I've clearly completed this quest and it's not finished only because of weird bug, could some GM make it completed for me, please?
It's really hard to gather competent party for HV nowadays - lack of playerbase.

**Comment by lilimx** [comment]
Hey,

how about the other dudes in your party, did someone the same quest?

**Comment by SilverWF** [comment]
> 
> 
> Hey,
> 
> how about the other dudes in your party, did someone the same quest?

I don't know exactly, probably not.
This is the last (I think) quest in the chain, so not many even get to this stage.

**Comment by SilverWF** [comment]
But yesterday and the day before it all bosses counted for me correctly - our team just hasn't enough time to complete it.

**Comment by wiscel** [comment]
This keeps happening to my Shadows Warrior Phenicia too the last 3 runs. I wait until my timer on lockout has run out. I make a new party, make sure no one has lockout. Sometime the early bosses in HV are not added in the Killquest. It's getting really frustrating now. I added screenshot so you can see we killed the early bosses but they are not added to the killquest.
![Phenicia_016](https://user-images.githubusercontent.com/11788060/124119484-df280180-da72-11eb-8319-62507ed2ca30.jpg)

**Comment by SilverWF** [comment]
> 
> 
> This keeps happening to my Shadows Warrior Phenicia too the last 3 runs. I wait until my timer on lockout has run out. I make a new party, make sure no one has lockout. Sometime the early bosses in HV are not added in the Killquest. It's getting really frustrating now. I added screenshot so you can see we killed the early bosses but they are not added to the killquest.
> 
> Edit: the killquest only worked 1 time, but then the last Lord got bugged, portals just kept spamming endless mobs, and we could not hit the portals.
> 
> ![Phenicia_016](https://user-images.githubusercontent.com/11788060/124119484-df280180-da72-11eb-8319-62507ed2ca30.jpg)

Oh, you have that message too: Still bound to old instance as it progressed further

**Comment by SilverWF** [comment]
I did it today.
1st I took the quest, then abandoned it manually, then took again.
All bosses counted correctly.

**Comment by wiscel** [comment]
Ok, I did HV today again. Just took the quest, all kills counted correctly this time. Too bad our healer forgot to cleanse at last boss.............
