### ISSUE TITLE
Mislabeled Item

### ISSUE THREAD

**Issue by Folgrimma** [WarEmu/WarBugs#19288]
Item Mugwump Hardmantle should be listed as Heavy Armor for Blackguard. It is currently listed as Medium Armor

![WAR-64 2021-07-05 21-35-57](https://user-images.githubusercontent.com/40577289/124538606-28f94a80-ddd9-11eb-8420-ed703996b82a.png)

**Comment by lilimx** [comment]
Fixed with Patch 22/07/2021
