### ISSUE TITLE
Auction don't working!!!

### ISSUE THREAD

**Issue by OVshnik** [WarEmu/WarBugs#19283]
Hi. The auction has stopped working. when I right-click on an NPC, nothing happens

![image](https://user-images.githubusercontent.com/86915531/124384714-4516c200-dcdb-11eb-9bdd-567a5e976d20.png)

https://user-images.githubusercontent.com/86915531/124384789-97f07980-dcdb-11eb-837f-49c25365cc24.mp4

****

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
I have no issues with the auction house.
Please try /rel or a relog completely.
Check your addons.
Try the repair function.

**Comment by OVshnik** [comment]
I tried these options, it does not help, it works on another computer

**Comment by lilimx** [comment]
Hey,

maybe try a fresh install on your "broken" pc version. Maybe it will fix it.

**Comment by lilimx** [comment]
Hey,

Im going to close this ticket now. Im pretty sure it's an individual game issue due to a broken patch/install.
