### ISSUE TITLE
Magus daemonic reach tactic bug

### ISSUE THREAD

**Issue by jacopodac** [WarEmu/WarBugs#19280]
**Expected behavior and actual behavior:**
my tactic daemonic reach doesn't work properly everytime. As you can see from attached screenshot with the help of dissolving mist skill tooltip s
![Piadinella_000](https://user-images.githubusercontent.com/86896998/124368997-6b9b1580-dc67-11eb-9738-9f8fcbb340ec.jpg)
ometimes i lost the benefit from the tactic ( range extender...) and i must exit from combat and switch it with another tactic and then replace another time daemonic reach to get the benefit of the tactic. 

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

Thank you for your ticket.
I see on your picture your not lvl 40 yet. 
This issue is already known, so I'll put on the related report.

**Comment by lilimx** [comment]
dublicate/related to #18945
