### ISSUE TITLE
Influence items (T3, DoK)

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#1928]
T3, Greenskin, Basic, in both blue and both purple rings same stats
T3, Dark Elf, Basic, no talis slot
T3, Dark Elf, Advanced, purple, only 1 stats difference

**Comment by taccr** [comment]
DoK T3, Greenskin, Elite: Thickmuck Breastscale looks like it's missing +30 wounds.
The order version (Thickmuck Cassock) has this missing stat.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/5494
