### ISSUE TITLE
Career Trainers in Group Ranked map

### ISSUE THREAD

**Issue by Klod91** [WarEmu/WarBugs#19289]
As far as I know, Group Ranked matches are not supposed to have Career Trainers. 
This particular map does though. (othar maps, as far as I could tell, don't)

![Reppanse_032](https://user-images.githubusercontent.com/77681824/124672258-076e9080-deb7-11eb-908b-c533f4fe7f5a.jpg)

**Comment by lilimx** [comment]
Hey,

this is no bug, it's intended since Patch 29/04/2020 (https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=37910)
