### ISSUE TITLE
Fire Forge's Camp Greenskin CH11 PQ Supply Crates

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#19287]
**Expected behavior and actual behavior:**
Expected: to click the supply crate and progress the public quest and collect credit for Gotta Nosh! quest.

Actual: interacting with the supply crates does absolutely nothing

**Steps to reproduce the problem:**
Take the Gotta Nosh! quest then go to Fire Forge's camp and interact with the supply crates.

**Testing Screenshots/Videos/Evidences (always needed):**

https://imgur.com/9iWlQ4t

**Comment by Lheana** [comment]
This is a dual PQ, which means it's for both Order and Destruction. The objective of the PQ, just like the objective of the quest "Gotta Nosh!" is to destroy the crates recovered by the dwarfs. So the quest works fine, like intended.
