### ISSUE TITLE
Magus'pet bug

### ISSUE THREAD

**Issue by globalgame** [WarEmu/WarBugs#19298]
Magus'pet disappears when you summon it in some locations where the hills or the mountains and uneven relief also it happend in Black Fire Basin scenario on the frozen lake, most probably Engi's pet has the same bug but i did not tested.
For example Thunder Mountains i tried to summon many times but pet always disappeared not everywhere of course, 
in DW and in Reikland it seems i did not see such bug

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
This issue is already known and has different ticket.
I will add this report to a related one.

**Comment by lilimx** [comment]
similar/related to #18872
similar/related to #18775
