### ISSUE TITLE
Power Hungry turn-in bug

### ISSUE THREAD

**Issue by Saladmancer** [WarEmu/WarBugs#19291]
**Expected behavior and actual behavior:**

For the quest, Power Hungry, the NPC spawned when the quest was completed by interacting with the Windsong Dais. I waited too long to accept the next quest from her and now I can't interact with the item that spawned her in the first place to resummon her. 

**Steps to reproduce the problem:**

Can't attempt to reproduce without resetting the questchain somehow.

**Testing Screenshots/Videos/Evidences (always needed):**

![Vairo_056](https://user-images.githubusercontent.com/87062115/124718328-fda75600-ded3-11eb-9776-8510553f1ce1.jpg)

**Comment by lilimx** [comment]
Hey,

abandon the quest and retake it... and try it again to interact with the windsong dais.
Please give a little feedback if it works?

**Comment by Lheana** [comment]
From what I understand, he/she can not abandon the quest because he/she has finished one step but did not accept the next one before the NPC vanishes.

**Comment by lilimx** [comment]
fixed with patch 04/11/2021
