### ISSUE TITLE
Beastlord Commodities QuarterMaster Not using Beastlord Coins

### ISSUE THREAD

**Issue by Noblesseshadow** [WarEmu/WarBugs#19293]
Unable to Buy a piece of gear "Beastlord Cloak of the skaven", the vender doesn't recognize BeastLord tokens.

![image](https://user-images.githubusercontent.com/87067208/124735738-3a903e80-df0e-11eb-8980-2a8e8f4f026c.png)

**Expected behavior and actual behavior:**
doing " repeatable Quest ( kill all Beastlords = 1 beastlord token) " and collecting enough Currency To buy a piece of gear from vender.

**Comment by lilimx** [comment]
Hey,

please confirm if you get the back after you get the 50g

**Comment by lilimx** [comment]
Worked.

-close

**Comment by Noblesseshadow** [comment]
i can confirm that with 50g + 3 beastlord Coins you are able to buy.
