### ISSUE TITLE
Layout Editor destroys your UI

### ISSUE THREAD

**Issue by Bajlk** [WarEmu/WarBugs#19295]
When opening the layout editor there is a weird big window in the middle of the screen which automatically moves all your windows on the right side to the left side and also moves some others. When trying to click "Exit" nothing happens except the big window vanishes.

Only reason is to restart your game but your UI stays destroyed.

No addons installed.

1.) https://www.directupload.net/file/u/75763/6djt5gku_jpg.htm
2.) https://www.directupload.net/file/u/75763/p5gybvde_jpg.htm
3.) https://www.directupload.net/file/u/75763/oihb6ojm_jpg.htm

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. 
This issue is already know. I'll add this ticket to the related report.

**Comment by lilimx** [comment]
dublicate / related to #19241
