### ISSUE TITLE
Norsca chapter 1 - Two NPCs have the exact same position

### ISSUE THREAD

**Issue by Yuven91** [WarEmu/WarBugs#19294]
**Expected behavior and actual behavior:**
Two NPCs in Norska is clipping through each other due to having the exact same spawn point
![image](https://user-images.githubusercontent.com/22319152/124738184-f6ef0200-df18-11eb-8847-c7e940898b38.png)
![image](https://user-images.githubusercontent.com/22319152/124738213-fce4e300-df18-11eb-83fe-f872172fcc84.png)

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
related to #16938
