### ISSUE TITLE
Name is bugged.

### ISSUE THREAD

**Issue by Althesian** [WarEmu/WarBugs#19296]
Hello, I've made a character recently, - tried logging back into it 2 days later & turns out the name it had is no longer playable, and i have to forcefully rename it. i've checked the armory however, and it turns out to be my DELETED alt DoK that i no longer have on the account

-- I wanted that specific name for my chosen ( Nephilim ) but appareantly the database shit the bed and i've no clue what to do. I've contacted multiple GM's including Wargrimnir but was directed to make a bugtracker ticket :) 
https://prnt.sc/199nva3
https://prnt.sc/199nwrg
https://www.returnofreckoning.com/armory/character/517195

**Comment by MaxHayman** [comment]
Seems like a problem occured. I would do the following.

1 - Delete this character
2 - wait for a server restart, then another character should appear in that slot
3 - delete that character
4 - contact a gm/post here to undelete the original character, the name should then be avaliable.
