### ISSUE TITLE
Quest bug: "A Cold Heart"

### ISSUE THREAD

**Issue by HakiSky** [WarEmu/WarBugs#19305]
Hi,

I noticed a bug with the quest "A cold Heart" in Troll County.

You have to summon a ghost from an urn and then kill the ghost. The ghost is summoned, but is then not attackable. After a time he disappears and the urn can not be clicked again.

I have tried all the items from my quest backpag. I then cancelled the quest and started it again. I then recorded the video in the process. The ghost could not be attacked again: https://youtu.be/TBZTRTVAogo

**Comment by lilimx** [comment]
Fixed with Patch 22/07/2021
