### ISSUE TITLE
Quest: Harvest of fear. NPC don't drop quest item

### ISSUE THREAD

**Issue by HakiSky** [WarEmu/WarBugs#19300]
Hi,
Quest: Harvest of fear
location: Ostland

The quest wants me to kill Radcliff Shoerner and take his blood. I killed hime 5 times now, but he doesn't drop anything. I also checked the quest log for special actions and also checked if I have quest items.

Thanks.
Haki

**Comment by lilimx** [comment]
Hey,

and his blood isn't in your quest backbag?

**Comment by HakiSky** [comment]
Yes, my quest backbag was empty

**Comment by HakiSky** [comment]
Here is a video of me trying to do the quest
https://youtu.be/Ay5ElkOER5Q

**Comment by lilimx** [comment]
Fixed with Patch 22/07/2021
