### ISSUE TITLE
Firebeard's Slayers PQ - Stage 1 issue

### ISSUE THREAD

**Issue by pottedfrog** [WarEmu/WarBugs#19304]
Firebeard's Slayers PQ, Stage 1 requires the killing of 30 Sea Anvil Forces and the destruction of 8 Piles of Goods. There are only 7 Piles of Goods in the PQ area that can be targetted and 'killed', even though there are 10 Piles of Goods at the site. There are 3 Piles of Goods that give the error 'That taget is not attackable', therefore the PQ cannot be advanced beyond Stage 1.

This PQ is in the map Barak Varr around location  4660, 52500

**Comment by lilimx** [comment]
hey,

I found a pile here, it was lat one (I guess it was your pq), and killed it, now im in stage 2
![grafik](https://user-images.githubusercontent.com/23266079/125167572-93c3d080-e1a1-11eb-8c06-6e6ca2b9c3aa.png)

**Comment by lilimx** [comment]
PQ complete

![grafik](https://user-images.githubusercontent.com/23266079/125167664-fae18500-e1a1-11eb-94cf-de9d22cb9968.png)

**Comment by pottedfrog** [comment]
Thanks, I spent best part of an hour in the area, in andout of cave etc trying to find that. .... Old age defo getting to me

**Comment by lilimx** [comment]
hey,

don't worry....I've also tested it again. There are 8 crates...a bit hidden, but the PQ is doable :D
![grafik](https://user-images.githubusercontent.com/23266079/125167942-4cd6da80-e1a3-11eb-8cd2-4c3a73cacec7.png)
