### ISSUE TITLE
Sigmarite Temple PQ Stage III Bugged

### ISSUE THREAD

**Issue by Delegator2** [WarEmu/WarBugs#19301]
**Expected behavior and actual behavior:**

SIgmarite Temple (Greenskin Chapter 13 Hard) PQ is bugged. The 5 Champion MOBs for Stage III are not attackable.

**Steps to reproduce the problem:**

Do stages 1 and 2...try to attack the Sigmarite vanquishers. They are non-aggro and not attackable.
<img width="1675" alt="Screen Shot 2021-07-09 at 10 33 56 PM" src="https://user-images.githubusercontent.com/77587188/125149246-c91ae080-e105-11eb-98b4-c97bfcc16929.png">

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Fixed with Patch 22/07/2021
