### ISSUE TITLE
[Sorc] Shadow of Disaster stack with Chosen/Magus resist debuff (BW version doesnt)

### ISSUE THREAD

**Issue by BomblingTV** [WarEmu/WarBugs#19309]
**Expected behavior and actual behavior:**
When a Sorc spec into the resist debuff in the middle mastery tree, their Chillwind will debuff the target's resist by X.
When you have a Magus use Glean Magic (aoe spirit resist debuff) on the target these two values stack. Or useing a Chosen's Resist debuff aura will stack aswel on top of just the Sorc selfdebuff. So you get a much lower spirit resist value to mitigate the timestamp from the sorc.

Where as on Brightwizard, Ignition resist debuff middletree tactic is not stacking with Engineer's Acid Bomb aoe corp debuff nor Knight's resist debuff from Auras.

**Steps to reproduce the problem:**
Log a BW + Engineer/knight in and try on the constructs in altdorf
Log a Sorc + Magus/Chosen and test numbers on construct in IC
(these resist values might already debuff the target to a 0 so might have to test on an actual player with a resist buff on them)

The difference is very easy to spot and Sorc's tactic clearly stack with external sources, where as BW dont.
With the ranked leaderboards from Sorc and BW being so difference maybe leavint the Sorc version as it is, and changing the BW ignition to stacking is a better balancing idea than making both classes not stack with other classes.

**Comment by BomblingTV** [comment]
Following the logic of RoR = Ability + tactic + morale, is stackable maybe the correct answer to this is not to nerf the Sorc tactic stacking, but instead making the Ignition tactic on BW stack with Knight aura/ Acid bomb on engineer corp debuffs.
Unless there was a patch some time ago directly making this unstackable on BW (which i wasnt unable to find searching the patch archives)

**Comment by geezereur** [comment]
Aaaaaand its nerfed.

**Comment by lilimx** [comment]
Fixed with Patch 22/07/2021
