### ISSUE TITLE
Keep Door dead but show as closed[emulator]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#1930]
it happened that some ppl saw a killed outer clientside as closed even if had 0 wounds

-it was char related as not all saw it that way
-being killed and ress fix the problem
-happend altogheter for some ppl

it never happened on live (at least to me) so maybe the issue is serverside.

**Comment by Tesq** [comment]
p.s door was emp t3 outer

**Comment by Luth-RoR** [comment]
Doors should work now.
