### ISSUE TITLE
Heart of Chaos : can't interact with wyvern eggs

### ISSUE THREAD

**Issue by DurinThornaxe** [WarEmu/WarBugs#19319]
"Travel to Poisonwing Canyon and kill five Poisonwing Wyverns to collect their blood. You will also need to collect the ichor from three of the Wyvern Eggs, you can find these at the Wyverns' Nest. When you have all of the ingredients...." That's part of the quest description. 

I can get the Poisonwing Blood from the wyverns but I can't interact with the eggs that are supposed to give me 3 Poisonwing Eggs.

I couldn't find any issue related to this. 

Thank you for your work!
Durin

**Comment by lilimx** [comment]
fixed with patch 21/07/2022
