### ISSUE TITLE
Destro Quest Ties That Bind: cannot complete last stage

### ISSUE THREAD

**Issue by valkeera** [WarEmu/WarBugs#19312]
For the last (I think) stage of the Ties That Bind quest in Eataine, Uthorin Informant is not available and the well can't be clicked anymore.

![Zeraton_002](https://user-images.githubusercontent.com/58527250/125330773-73357b00-e347-11eb-9e55-6374b53faaed.jpg)

![Zeraton_001](https://user-images.githubusercontent.com/58527250/125330802-7c264c80-e347-11eb-8d91-8f4dd3f1c042.jpg)

**Comment by lilimx** [comment]
related to #16938

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. I will add this report to the other missing NPCs report.

**Comment by Lheana** [comment]
I doubt this is related to the issue mentioned above, so I reopen the ticket.

**Comment by Lheana** [comment]
This will be fixed with next patch. Once done, be sure to abandon the quest and retake it.

**Comment by valkeera** [comment]
I've been able to complete the quest, thanks for the fix.
The informant now spawns right at the top of the well, you might want to reposition her a little to make it look better.

![Zeraton_010](https://user-images.githubusercontent.com/58527250/126691511-5f2838dc-c47e-4aaf-a21b-91311b73c191.jpg)

**Comment by lilimx** [comment]
Fixed with Patch 22/07/2021
