### ISSUE TITLE
Morale 4 from spec trees Not working at all

### ISSUE THREAD

**Issue by bloodmasked** [WarEmu/WarBugs#19314]
Caused from npc renown/spec profiles?

Will test soon.

An old issue that was closed apparently, but has re-emerged.

You press M4 and it lights up your morale but nothing happens, you can keep pressing M4 and it will not activate ever. M1-3 still work as normal.

**Comment by lilimx** [comment]
Hey,

I close this ticket now.....there is really no content or evidence in this ticket. 
Please open a new ticket when you can bring a proper description of your issue and some screenshots or a video.

Please read these guides to write a usefull bug report:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37703
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by bloodmasked** [comment]
I'm not sure how to reproduce it. It was happening to someone else and then happened to me.
