### ISSUE TITLE
Keep Lords Not Attacking Enemies in Active Zones

### ISSUE THREAD

**Issue by dansarii** [WarEmu/WarBugs#19311]
Keep lords aren't attacking enemies in active zones. It's possible this is because the doors aren't down yet but it doesn't make sense to have a Hero inside the keep that ignores enemies.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. There are already two similar tickets with this topic, so I will add this one.

**Comment by lilimx** [comment]
dublicate / related to #17773
dublicate / related to #18369
