### ISSUE TITLE
Marshes of Madness - Chapter 6 Green Skins - Marsh Conquest PQ bugged out

### ISSUE THREAD

**Issue by Awoelkchen** [WarEmu/WarBugs#19318]
"Destroy the Rock Carriers" appears to be broken, as you cant really attack those things since they are "dead" by default.

https://user-images.githubusercontent.com/79367411/125638841-1d1942a6-8daa-47fd-bf8e-fbf9404061a7.mp4

**Comment by Kabucoror** [comment]
2 of the carriers spawn at the wrong stage. It works fine on dev server, tho. 
Please let me know if this issue persists after the next patch.

**Comment by lilimx** [comment]
I've tested it in the live server.
Kabuco was informed about the results.

**Comment by vikingofmars** [comment]
The Bar Dawazbak issue was fixed but this one still remains it seems
![image](https://user-images.githubusercontent.com/37393516/129509623-587a4898-3cb2-4673-8fc9-768f954d2e15.png)
![image](https://user-images.githubusercontent.com/37393516/129509633-86e41449-82e9-4e7a-9e3c-9749afcb2e10.png)
![image](https://user-images.githubusercontent.com/37393516/129509655-80bd84d6-da21-4c66-b780-bd6abf1a66af.png)

**Comment by vikingofmars** [comment]
seemingly you can aoe them to "die" again to progress the stage
![image](https://user-images.githubusercontent.com/37393516/129509802-c732c3e1-e95e-48fd-bf3f-4be9f71df476.png)
