### ISSUE TITLE
Database /login server crash (?)

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#19320]
You may want to investigate what happaned today 14/07 at around 22:00 / 22:20 (cet+0 / gmt+1), while order was finishying fort, all ppl crashed(all server) it happened something that felt like a databse crash or something like that; when trying to relog login server was fine but there was no response in server lobby for about 10 plus minutes; after that instead have the server down as normal, it immediatly went back but like 5 min prior the point of crash with fort lord with more life and everyone relogging in same spot.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
I will close it for now. But if we are see any matches with similar crashing events, we will reopen it.
