### ISSUE TITLE
Frenzied Mayhem lvl req. !?

### ISSUE THREAD

**Issue by fo0liner** [WarEmu/WarBugs#19323]
Hey, 
I just noticed that Frenzied Mayhem appeared in my Tactics List, tho it is labeled as "not usable at my current level".
Bolstering seems to fix it (atleast turn it green), tho it is confusing still especially for pve (unbolstered).

Below is a screenshot of me at CR 27 that shows the tactic highlighted in red.
Reloging and leveling up to 28 did not fix the Issue.
I first posted this in the gameplay-advice channel on discord and after a few helpful words of another member i came here to report it.

I have notice a similar problem when i gained my first mastery ability at lvl 20 instead of 21 by the help of the keeper set. Tho that time i related it to the boost of +1 carnage from the set. This time however it is a core ability.

Update: I just turned CR31 and it became green.

![Vinum_000](https://user-images.githubusercontent.com/87495285/125838225-27979942-997a-41d5-a70b-6495ac6e3d36.jpg)

**Comment by dalen** [comment]
Should be fixed now
