### ISSUE TITLE
Synphoned energy + general speed proc interaction [chosen][ability][emulator]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#1932]
1) it don't heal for the correct ammount:

-i got healed by 108 but tactic says 116-8

2) the speed buff seems less effective when snare than what it suppose to be:

-snare debuff and speed buff should be additive to each other so:

 -40+30= -10%---> 90/100% 

 and not 

100% +30%- 40% = -52--> 130-52= 78/100%

3)anyway i don't know if it's know but similar to other buff stuff each kind of buff/speed snare stack with a different one, for exemple synphoned energy stacked with odjira and similar itiems but not with other skills like  flee or offensive tank set bonus.

even in this case odjira + synphoned energy were additive so 30+ 60 =90%

tough it's quite a lot odjira and similar worked same way with flee. Maybe you could decide to not let odjira  stack additively with such things cuz 60% is alredy a lot and 90% is crazy) but definettly snare and buff speed should be additive. On live there were also some renow temp talismans that boost speed base movement but the max was 8% (additive with all), packed togheter with any 30% speed buff wasn't still able to bypass that 40% snare value anyway so a snare still happened anyway and it required anyway to use flee.

4) speed potion:

there was also a speed potion from lotd that stacked for crazy ammount with odjira and flee etc, ppl were litteraly flying while jumping using that. Tough this is what you would like to avoid. (crazy value like +120% speed)
You should keep snare vs speed buff additive but don't let stack speed buff since you alredy avoided snare  stack to happen.

**Comment by ozarmidrashim** [comment]
RoR implements snares as multiplicative. They should be additive now?

**Comment by Tesq** [comment]
no i mean, i know in war there was the sw snare that stack with other snares and here was changed to not do so but seems that when there are both speed buff and snare rather than  only speed buff or only snare the snares remove more speed then they should when you also have a speed buff, it also feel the same when i use flee, under a 40% snare when i use flee it fill like i gte snared still more than a 10%
