### ISSUE TITLE
Dark Elf quest "Worth of our host" (T4, Dragonwake)

### ISSUE THREAD

**Issue by lleri** [WarEmu/WarBugs#19328]
**Expected behavior and actual behavior:**
Expected: Quest (or quest step) should be complete when I speak with NPC Alinas Melisar.
Actual: When I click on Alinas Melisar nothing is happen.

**Steps to reproduce the problem:**
Just process quest till step with Alinas Melisar at ~32k/2.5k at Dragonwake (see attached screenshot also
![Alinas2](https://user-images.githubusercontent.com/19507091/126076645-67bca439-4374-4877-8d60-231589074db0.png)
)
![AlinasMelisar](https://user-images.githubusercontent.com/19507091/126076572-cd95f5ba-41dd-4fe9-b380-25545ac30aec.png)

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Fixed with Patch 30/07/2021
