### ISSUE TITLE
Tier 4 Dark Elf Epic Quest Step 12 Bug

### ISSUE THREAD

**Issue by Marchmain** [WarEmu/WarBugs#19325]
In step 12 of the Dark Elf Tier 4 Epic Quest you are supposed to kill The Keeper of the Way who is guarding an orb at the back of a citadel. Killing him will drop a key needed to complete the quest. I found the orb but he wasn't there. Thought maybe someone else had killed him so waited a bit, looked around, but he didn't reappear. I started tab targeting to see if maybe I just was in the same spot and this revealed him stuck inside the walls of the building to the left of the orb. Tried attacking him, AOE taunting etc. but get the message "You can't see your target".  This does not appear to be a true building with rooms, doors, etc. at this ground level so I think he is just in the wrong spot and stuck within the walls of this space. Without killing him the quest can not be completed. 

Thanks
Marchmain
![Gormless_009](https://user-images.githubusercontent.com/20139857/126028220-3a945446-f14f-4833-880b-b2a808e8255c.jpg)

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

Thank you for your ticket.
This issue is already known, so I will add it to the certain bug tracker tickets.

**Comment by lilimx** [comment]
dublicate / related to  #19042
dublicate / related to  #16938

**Comment by Marchmain** [comment]
Thank you. I looked but I couldn't find any other posts related to this
bug. But I am old and GitHub confuses me. :D

**Comment by lilimx** [comment]
> 
> Thank you. I looked but I couldn't find any other posts related to this bug. But I am old and GitHub confuses me. :D

Hey,

don't worry. It's nice if you can check it first, but otherwise I always try to search for dublicates, too. :D
