### ISSUE TITLE
ThickMuck Rings:  T3 Influence Gear (destruction) 

### ISSUE THREAD

**Issue by mursie** [WarEmu/WarBugs#1933]
The ThickMuck purple rings for T3 Influence Gear have duplicate stats (defensive toughness stats) for just about all mdps and tank classes.  Apparently marauder was recently changed to have one of theirs be strength.

CAn you please make this fix for the other mdps - specifically Choppa.

Preferably the Thickmuck Dark Band - since that is the one I picked and has duplicate image to the Thickmuck Rend Ring that was changed for Marauder to have strength.

Thank you.

**Comment by Tesq** [comment]
all thickmuck ring should give toughness, the other ring is incorrect as it should be a different reward

http://www.arsenalofwar.com/search?name=Thickmuck+

**Comment by Evildoor** [comment]
Dark Bands were missing class requirements (they are for Black Guard) and should no longer be offered to other classes.
