### ISSUE TITLE
Vale-Walker Dread Seal

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#19332]
I completed the quest line of vale-walker in HV while also recived all type of bags avaible completing the dungeon with the timer,  this jewelry of the new set seems nowhere to be found but it's listen in the set pieces, either a change of the plan in the gear or something missing, or maybe i missed something; im reporting this here anyway.

**Comment by lilimx** [comment]
Hey,

you need to run the dungeon atleast 7 times (for each piece). Don't know if you miss something, but there are people with all 7 pieces.

**Comment by Tesq** [comment]
well i found the quest it's not really clear  that that suppose to be another quest after finishing the quest chain but whatever closing this.
