### ISSUE TITLE
Death From Below quest: Brauk kill not counted

### ISSUE THREAD

**Issue by valkeera** [WarEmu/WarBugs#19334]
Brauk boss (who is an ad to Skrot boss) gets despawned after the main boss is killed, and is not counted as kill in the Death From Below quest.

I don't have evidence from the site, but I can provide quest logs from two different chars that were doing full run of C&T, you can see that the Brauk kill is missed by 1 for both.

![Filomenes_000](https://user-images.githubusercontent.com/58527250/126202079-52ecefdc-7d23-4c33-b7b4-07b1cc553d29.jpg)

![Chirannir_000](https://user-images.githubusercontent.com/58527250/126202101-69b6755e-881d-4656-8d75-4cb47c7642c7.jpg)

**Comment by lilimx** [comment]
Hey,

yeah, weird...it's on one of my toons, too.
![grafik](https://user-images.githubusercontent.com/23266079/126362126-a2b9a9f9-142c-4870-a635-191571c83834.png)

**Comment by Kabucoror** [comment]
This happens because Brauk despawns as soon as Skrot is being killed.

**Comment by lilimx** [comment]
Fixed with Patch 22/07/2021
