### ISSUE TITLE
[Squig Herder] Sentinel talisman not switching stat in Squig armor

### ISSUE THREAD

**Issue by CptEdward** [WarEmu/WarBugs#19335]
**Expected behavior and actual behavior:**
Expected behavior : 
Ranged critical strike from items should also count as Melee critical strike while Squig Armor is active. 

Actual behavior : 
The expected behavior is not working for the 4% critical strike chance from the Sentinel Jewelery talisman. Switching spec to have access to different content would require to switch talisman each time we respec (not possible...).

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![2](https://user-images.githubusercontent.com/59454916/126214045-d4befced-be00-4804-b8d5-86391de1aac8.PNG)
![1](https://user-images.githubusercontent.com/59454916/126214049-4a2a19e9-0f58-43b1-ac99-f85ff6f25168.PNG)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
But we need the .getstats overview ... the paperdoll ones are not reliable.

**Comment by lilimx** [comment]
Hey,

Im going to close this ticket now due to no feedback.
If your the opinion the issue still persists, please open a new ticket and add the missing information.
