### ISSUE TITLE
character bugged

### ISSUE THREAD

**Issue by toecutter1280** [WarEmu/WarBugs#19338]
so last night i walked south out of the inevitable city to get to a maw defense, i had to leave so i logged out in the maw on my shaman named shamwich, since then i can no longer use this character, i get to my character selection screen and when i hit play on shamwich it hangs for a second and on the next screen the dialog gets stuck on searching for allies and never logs me in, i tried using the /stuck command twice and it doesnt seem to work, all my other characters work fine but this one is bugged out, and it is my main character, i need to have him moved elsewhere so i can log in please

**Comment by lilimx** [comment]
Hey,

this is not a bug. 
Please join the RoR discord and ask in #technical-advice or ask a GM to move your character.
