### ISSUE TITLE
[Quest] Nobility - Troll Country

### ISSUE THREAD

**Issue by Fritomaster** [WarEmu/WarBugs#19336]
**Expected behavior and actual behavior:**
The bug report from 2018 says it should be placed in my inventory after 10/10 kills. Tried with two characters no luck.

**Steps to reproduce the problem:**
Kill 10/10 and not get anything.

![image](https://user-images.githubusercontent.com/49774175/126263159-6f6684ba-090f-43c4-9c27-90ef789c48aa.png)

**Comment by lilimx** [comment]
Hey,

keep on killing "Blighted Believer" and try solo to be sure only you can drop the item.

**Comment by Fritomaster** [comment]
> Hey,
> 
> keep on killing "Blighted Believer" and try solo to be sure only you can drop the item.

Did the whole WQ which was a ton no luck.

**Comment by lilimx** [comment]
Hey,

is this a "yes, I've got it finally" or a "nah, it's not droping"?

**Comment by Fritomaster** [comment]
> Hey,
> 
> is this a "yes, I've got it finally" or a "nah, it's not droping"?

It is a no killed a ton of them. Then came back and killed more nothing no drops.

**Comment by Fritomaster** [comment]
Also tried dropping quest and restarting no luck.

**Comment by lilimx** [comment]
Hey,

Lheana will take a look.

related/dublicate #19272

**Comment by Kabucoror** [comment]
Tested it and got the robe after the 11th kill.

**Comment by lilimx** [comment]
Fixed with Patch 30/07/2021
