### ISSUE TITLE
Debolster in T1 makes mount unusable

### ISSUE THREAD

**Issue by Delegator2** [WarEmu/WarBugs#19343]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

Go into a T1 area. Debolster knocks you down to level 15, OK -- but it also makes your mount unusable. Was this an intentional part of the debolster?

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Delegator2** [comment]
This was not addressed by the hotfix that seems to have taken care of #19344 (which is expected, since the ability to ride a mount isn't a buff). Still an issue today.

**Comment by dalen** [comment]
You can use the T1 mount. It is available for free at quartermaster in T1 warcamp.
