### ISSUE TITLE
Bolster causes loss of potions, guard, dark protector

### ISSUE THREAD

**Issue by Delegator2** [WarEmu/WarBugs#19344]
**Expected behavior and actual behavior:**

When entering a T2/3/4 area as <40 you get a bolster. But your potion effects should stay, right? Well, as of today's patch you lose your potions, and any guard or dark protector (those at the BG abilities, I assume same for others) are lost as well when the bolster activates.

That would be enough of a pain, but it also happens any time you release to the WC and then get the bolster again. That is NOT ok, because it will be very costly in terms of potions. And people will forget to reset guard and such.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kraddus** [comment]
This seems to be a general problem with clearing Auras/Buffs on bolster. I made a post a little while ago about DoK chalices not working immediately after a bolster (#19341)

**Comment by xpander69** [comment]
can anyone confirm if the issues are still here after yesterdays hotfix?
i think it should be fixed. But if something still isnt working correctly then report back

**Comment by Delegator2** [comment]
Checked with a potion and it works. Don't have a friend on to check Guard or group buffs just yet.

**Comment by Delegator2** [comment]
Tested with guard 2, and that also works, so closing this. Thanks for the quick fix.
