### ISSUE TITLE
elixir of endless stone (item)(event)

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#19349]
second reward for event it have 2 problems

-should be consumable, it isnt
-the x5 item you get should be stackable (in live they were) instead they cant be stack so each take 1 spot in inventory

**Comment by GamesBondd** [comment]
They're now stackable (fixed by Ekalime).

**The consumable issue remains pending.**

**Comment by Tesq** [comment]
i restart client etc  but those in my inventory cant still be stack ( just reporting)

**Comment by GamesBondd** [comment]
> i restart client etc but those in my inventory cant still be stack ( just reporting)

It needs a server restart, so it'll probably have to stay the way it is till there's a hotfix or a patch.

**Comment by Tesq** [comment]
it has been fixed
