### ISSUE TITLE
T3 Empire Influence reward for Choppa: Missing Talisman Slot

### ISSUE THREAD

**Issue by Nocha** [WarEmu/WarBugs#1934]
Hi. I have problem with helmet named Thickmuck Skull ( T3 Empire influence reward) of my Choppa. This helmet have not talisman slot. Plz fix this. my choppaz nickname is Atec.
I saw a similar request https://github.com/WarEmu/WarBugs/issues/1889 
you get it close

**Comment by Evildoor** [comment]
Uh, if it is the same item then that fix will affect your character as well.

**Comment by Nocha** [comment]
Sorry, but not understand your answer.
you can fix this item or not? and when?

**Comment by Evildoor** [comment]
There is an item called Thickmuck Skully in the database. It is missing a talisman slot. It was fixed on the dev server - this means that all instances of this item, including your one, will be fixed (this means that if someone reported a problem with item, you don't need to create a separate report that your item is bugged too). When - when the fixes from the dev servers will be pulled to live server. When that will happen - i don't know.
