### ISSUE TITLE
AM Talent Bug

### ISSUE THREAD

**Issue by Lnleftovers** [WarEmu/WarBugs#19350]
I've got an ongoing bug with my AM where I've selected the talent Magical Infusion however it doesnt appear on my bar or anywhere in my abilities spell book and so am unable to use it.

I am using the Keepers set to get a + 1 in the tree and have a feeling that is causing the issue.

[Doc1.pdf](https://github.com/WarEmu/WarBugs/files/6873278/Doc1.pdf)

**Comment by lilimx** [comment]
Hey,

what's inside the pdf?

**Comment by lilimx** [comment]
Fixed with Patch 30/07/2021
