### ISSUE TITLE
Missing Appearance for Obliterator Hauberk

### ISSUE THREAD

**Issue by Hauclir** [WarEmu/WarBugs#1935]
![hauclir_110](https://cloud.githubusercontent.com/assets/7598530/11361324/ad4a6d9e-9241-11e5-87a5-0a500d5341e3.jpg)
The Blackguard Armor Obliterator Hauberk is missing its appearance I am naked when worn.

**Comment by DanaBloodkiss** [comment]
Maybe some temporary bug. It's working on Dev server and I never got a Bugreport for it before.
