### ISSUE TITLE
Light Armour and Robe armour values are same or very close

### ISSUE THREAD

**Issue by pgrzybek** [WarEmu/WarBugs#19352]
Comparing zealot armour and witch elf armour it can be said that witch elf wears robes with light armour label on it.
Wiki links as proof:
https://wiki.returnofreckoning.com/Zealot_Equipments#Mercenary_Set
https://wiki.returnofreckoning.com/Witch_Elf_Equipments#Mercenary_Set 
Vale walker helms have ame armour values fo zealot and for witch elf.

**Comment by dalen** [comment]
This is intended behaviour. Has been this way since game launch.
