### ISSUE TITLE
Shining SIlverbow supposedly neutral MOB in Jade Coast (Dark Elf Chapter 12) is Aggro

### ISSUE THREAD

**Issue by Delegator2** [WarEmu/WarBugs#19356]
**Expected behavior and actual behavior:**

In the Jade Coast camp for dark elf chapter 12 there are 2 cages with Orange-named captured elves. These should not attack unless aggroed. However, the Shining Silverbow actually has an aggro range such that, if you die at a PQ and respawn at the camp, the level 39 MOB will attack you at range and chase you down if you run.

**Steps to reproduce the problem:**

Stand next to the cage with the Shining Silverbow. Owie, he hit me!

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Fixed with patch 19/12/2021
