### ISSUE TITLE
New currency bag has broken quest item inventory tab

### ISSUE THREAD

**Issue by Skullgrin** [WarEmu/WarBugs#19363]
I moved a few items to the new currency bag that was added this patch. After the initial move, several items have now become unmovable (when I try I get the message "Item move failed: attempted to move 5 of the item X while only having 1" or some variation of that) and there are multiple copies of these items in the quest item bag of my inventory. Additionally I am now unable to open my mailbox and get mail on all of my characters. I don't know if its related, but the mailbox issue started after the inventory one.

![Thargrimm_008](https://user-images.githubusercontent.com/40448982/127762565-75bdda01-57cc-488d-b97d-0cf988a1fcb1.jpg)
This first image shows the items that are in the third currency bag that cannot be moved. You can also see the error message in the chat window.
 

![Thargrimm_009](https://user-images.githubusercontent.com/40448982/127762567-6fafd77a-9ad4-4161-b9ea-f67d80b060a6.jpg)
The second image shows what the quest item bag currently looks like. At first it only had one copy of each of items from the currency bag, however now there  are multiple copies of each one.

I don't know if the mailbox issue is related, please advise if I should open up a second bug report for it. I tried using the GM appeal to see if it could be fixed by them, but I received no response over the 4 hours I was online.

**Comment by Skullgrin** [comment]
Update: the mailbox problem may be unrelated, as when I logged on this morning I found that I was able to access the mailbox and that the GM appeal I had created was closed.  I guess a GM logged in and was able to fix that on his own (Thanks!). Bag issues still persist however.

**Comment by Txarlyman** [comment]
same problem here with the new currency bag that dupes the items from the quest bag

**Comment by Txarlyman** [comment]
and after i use something like stalward soulstone it removes one from the currency bag but it doesen't remove it from the quest bag, so i dont really know if its a visual problem or it's realy dupping the items

**Comment by GamesBondd** [comment]
@Txarlyman can you please confirm if this issue is still occurring after the last patch?

**Comment by Txarlyman** [comment]
@GamesBondd yes, it still does it

**Comment by Txarlyman** [comment]
![imagen](https://user-images.githubusercontent.com/59922493/128608231-d1b067fa-e1ce-4cf9-93a6-7b449fc9ca31.png)

**Comment by Txarlyman** [comment]
and when more i play SC, RvR, changeing zones its stacks more

**Comment by Txarlyman** [comment]
![imagen](https://user-images.githubusercontent.com/59922493/128608270-62062ce2-4f92-439a-8853-babc1fa5e103.png)

**Comment by CrimsonFenris** [comment]
It probably have been noticed, and I saw Max telling a hotfix have been deployed, but I still got currencies stuck in the 3rd bag.

I previously had the quest items showing inside as well, but now only the recruit's emblem (from the stack of 5+ I tried to move in, and got stuck) is showing.

I cannot destroy it, nor move it away (the emblem appears in the quest bag as well, after other quest items).

![Currencies_bag_bug](https://user-images.githubusercontent.com/40425011/128709764-22a98f01-e7f7-4480-a200-0f4301da7510.jpg)

**Comment by yamyam318** [comment]
Still bugged. Invisible quest items in currency bag. You should check the whole bag system, this is not the first bag-related bug. Had also issues with crafting items that cannot be moved (Cultivating) and lost purple seeds.

![RoR_Bag_bug](https://user-images.githubusercontent.com/61079266/129538960-272afda3-e6f7-45f3-9463-6bcc0d59391c.jpg)
