### ISSUE TITLE
Hi ill can see my royals in medalions in my pack 

### ISSUE THREAD

**Issue by Ecilchosen** [WarEmu/WarBugs#19361]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Ecilchosen** [comment]
Hi ill can see my royals in medalions in my pack   
![Uploading image.png…]()

**Comment by lilimx** [comment]
Hey,

something went wrong with your upload or so.
Please edit your message (on the righ top "...")
