### ISSUE TITLE
Lost item

### ISSUE THREAD

**Issue by Dragothurch** [WarEmu/WarBugs#19360]
Hi all, sry for my english.
Second: any chance before apply new patch maybe testing?
Apply 3rd currency bag in game. I place here all t4 kill quest item( i dont remember the name) and now not see.
( i hope can repairing and now not type some " kind " words) gl for work in future just pls turn back from this bad way. thx

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by MaxHayman** [comment]
Hey,

On the backpack increase, we forgot to enable something on our release build so the slots are invisible. Were just creating a deployment, so a client patch will be released within the next couple of hours.

You can slot swap to get items out of the hidden slots for now. The items are not lost.

Sorry for the inconvenience!

**Comment by Dragothurch** [comment]
I try all slot drag to secodn bag from 3rd but nothing. not come back my item

**Comment by lilimx** [comment]
Fixed with Patch 06/08/2021
