### ISSUE TITLE
It Only Takes One: Trylux Terrorspawn

### ISSUE THREAD

**Issue by Aglasener** [WarEmu/WarBugs#19362]
Upon accepting the part of the quest, Trylux Terrorspawn spawns and I am instructed to slay him. While he is targetable he does not attack me and I cannot attack him. Instead he patrols back and forth between his spawn location and the sign. 

I abandoned the quest and accepted it again, each time he was spawned again and the same problem occurred, as indicated by the screenshot.

**Testing Screenshots/Videos/Evidences (always needed):**

![WAR-64 2021-07-30 18-08-03](https://user-images.githubusercontent.com/52112240/127716449-04d6b8c2-b8f2-453d-a9d4-b3cf963425e7.png)

**Comment by lilimx** [comment]
Fixed with Patch 06/08/2021
