### ISSUE TITLE
Mara/SW stance on different skill bars

### ISSUE THREAD

**Issue by Symbelmyne** [WarEmu/WarBugs#19375]
Ive noticed some time ago abilities on skill bar 1 and rest (2-5) behave differently when stance are changed.
Abilities on skill bar 1 will disappear when stance is changed letting to slot another ability. Opposite to this, abilities on skill bars 2-5 stay in same slot, get greyed out and if removed/replaced with other ability - are gone from skill bars 2-5.

**Steps to reproduce the problem:**
Swap stance on Mara (with e.g. Ferocious Assault) or SW (with e.g. Takedown) sloting said ability on all 5 skill bars. Only said ability on skill bar 1 disappear, ability on skill bars 2-5 stay in same slot and are greyed out/disabled.

**Testing Screenshots/Videos/Evidences (always needed):**
* Skill bars on images: from left to right - 2, 3, 4, 5, 1.

Mara - Ferocious Assault requires Brutality or Monstrosity (grey on Savagery) bottom right corner

![Mara skill enabled (stance req ON)](https://user-images.githubusercontent.com/16525371/128595122-b40bb236-a136-49b8-9bf4-b432ef8b387b.png)
![Mara skill disabled (stance req OFF)](https://user-images.githubusercontent.com/16525371/128595126-bd2fed39-a6ed-4222-8883-56dd29fd1e4c.png)

SW - Takedown requires Scout or Skirmish (grey on Assault) bottom right corner

![SW skill enabled (stance req ON)](https://user-images.githubusercontent.com/16525371/128595129-789b2aee-4063-4213-86f8-4bc4e80bfd86.png)
![SW skill disabled (stance req OFF)](https://user-images.githubusercontent.com/16525371/128595134-de14e230-900c-45d9-8860-7d656a7442f4.png)

**Comment by xpander69** [comment]
This works as intended. Always been like that. Same goes to WH/WE stealthing etc

**Comment by Symbelmyne** [comment]
> 
> 
> This works as intended. Always been like that. Same goes to WH/WE stealthing etc
> Its meant to be like that to be able to reuse the same hotkeys between different stances
> 
> edit: If you don't like the hotbar1 change on stance switch, then i recommend not using the first hotbar. theres plenty of hotbars to use, conf and keybind.

I made the bugtracker ticket to point out difference, didnt question why they (skill bars) work in different way. I hoped someone will double check code for skill bars behave and try to fix it, so bars 2-5 can behave same way as bar 1 do. I dont have huge problem with the way they work right now, but if there was a chance that devs could make bars 2-5 behave as bar 1 then it was worth a shot.

**Comment by xpander69** [comment]
> I made the bugtracker ticket to point out difference, didnt question why they (skill bars) work in different way. I hoped someone will double check code for skill bars behave and try to fix it, so bars 2-5 can behave same way as bar 1 do. I dont have huge problem with the way they work right now, but if there was a chance that devs could make bars 2-5 behave as bar 1 then it was worth a shot.

its not a bug, this is how it always was intended to work as many other similar MMORPGs do it also like classic WoW.
So i would advise to maybe ask around in the forums for a potential addon that can make them behave differently than intended. Maybe there even is an addon for that...
