### ISSUE TITLE
Inevitble doom ticks[slayer][emulator]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#1937]
ppl on live were able to parry the explosions both your and those coming by others...at least when slayer haven't rampage active

https://www.youtube.com/watch?v=z4hzEKZCRUY

at 0:59

4 hit happens, 2 hit, 2 get parry: 1 auto attack and 1 skill damage are show so 1 auto and 1 ID got parry. 

1x-ID
2x-auto attack
1x-skill

**Comment by noisestorm** [comment]
ID is handled differently than on live. The whole skill is afaik considered a DoT now by any means.In other words: It is also cleans-able unlike back on live. Therefore i dont see a reason for it being parryable.

**Comment by Tesq** [comment]
the fact that wasn't cleanseable is a bug, it wasn't balance issue.

ID was and is a an aliment therefore it must be parryable.

**Comment by Gobtar** [comment]
The application of ID should be parryable the tick damage shouldn't be if it's a DoT, ID was treating each tick as an attack, which is why it was so powerful with procs.

**Comment by Tesq** [comment]
normally yes, but ID was indeed parryable, and so i report it, well you can say it's unique since it's not a 9 ppl dot but it's a 9 ppl dot that can actually hit 9 additional other ppl from each  where the runes explodes...

Still ID will be undefitable with  rampage

**Comment by ozarmidrashim** [comment]
ID has a parry check, but its parry check takes the position of the Slayer who cast ID into account - if you're not facing him you won't parry it

**Comment by Tesq** [comment]
so to parry the explosion i must face the slayer? cannot be change to always hit from in front the rune is apply to you not to the slayer a little to comfortable for slayers
