### ISSUE TITLE
Target nearest Enemy

### ISSUE THREAD

**Issue by Littleneedle** [WarEmu/WarBugs#19373]
TAB targeting in this game is a nightmare, it needs fixed to target the nearest enemy that is right in front of you.

**Comment by lilimx** [comment]
Hey,

thanks for your report. However you are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide;

    Expected behaviour and actual behaviour
    Steps to reproduce the problem
    Testing Screenshots/Videos/Evidences (always needed)

**Comment by acidicrain** [comment]
Default is tab is cycle target and N is nearest 
Check your settings in targeting keys assignment
