### ISSUE TITLE
Bar Dawazbak PQ Bug progress blocked

### ISSUE THREAD

**Issue by Noblesseshadow** [WarEmu/WarBugs#19376]
one of Bar Dawazbak PQ objectives is to Kill/Destroy cannons 
which is not possible as those cannons after being destroyed : didn't respawn / regenerate .

Note: this Public Quest is part of the second Live event "A Stronghold Saga Part 2 -Blood in the Water-" 

https://user-images.githubusercontent.com/87067208/128599016-86779727-c931-4611-a1ce-c1833763d660.png

**Comment by lilimx** [comment]
- All cannons are already on 0%
- Team is informed

**Comment by lilimx** [comment]
maybe related to #19318

**Comment by Lheana** [comment]
Should be fixed with next patch/hotfix.

**Comment by lilimx** [comment]
Fixed with Patch 13/08/2021
