### ISSUE TITLE
"Tracer Rounds" tactic not working.

### ISSUE THREAD

**Issue by solidmusket** [WarEmu/WarBugs#19374]
**Expected behavior and actual behavior:**
15% increased chance to crit when within 100ft of your turret.

**Steps to reproduce the problem:**
It only worked once. Every summon of my turret I have done is not triggering the increase of crit anymore. I have tried respeccing, relogging, and even re equiping the tactic.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/32817023/128554949-89f59aa8-b5b0-474e-b7f7-dcdaad30eb7b.png)

![image](https://user-images.githubusercontent.com/32817023/128554987-7a842eb8-7987-45b1-ad99-1911f080ae28.png)

![image](https://user-images.githubusercontent.com/32817023/128555740-09028a26-168e-49cf-b2e9-4b8f1f48a642.png)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
This issue is already known so I will add this report to the related ticket.

**Comment by lilimx** [comment]
dublicate of #17008
