### ISSUE TITLE
Black Orc weapon appearance

### ISSUE THREAD

**Issue by Pin3appleror** [WarEmu/WarBugs#19372]
Alcadizaar´s Bigchoppa gives 1handed appearance.
![BL apperence](https://user-images.githubusercontent.com/62404761/128507103-889e5906-f156-45a2-bd58-e8a355c44d4c.png)

**Comment by lilimx** [comment]
maybe related to #18536

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by lilimx** [comment]
Fixed with Patch 05/09/2021
