### ISSUE TITLE
SH: Ballistic skill gain from "Masterful aim" tactic is not converted into STR when in squig armor

### ISSUE THREAD

**Issue by LeonardoFurci** [WarEmu/WarBugs#19387]
**Expected behavior and actual behavior:**

as the title says, the "Masterful aim" tactic for SH gives 160 ballistic skill. this bonus to Ballisti Skill stat however is not converted into STR when changing into squig armor. On the other hand, the 120 ballistic skill from "Pick on yer own size" tactic is properly converted into STR once into squig armor.

**Steps to reproduce the problem:**
- enter squig armor: strenght value is at X, ballistic value is at Y
- leave squig armor
- equip tactic  "Masterful aim" 
- check Ballistic skill in "charachter sheet": Ballistic skill is not at Y+160 (at level 40)
- enter Squig armor
- check Strenght: strenght still at value X, no changes
 

**Testing Screenshots/Videos/Evidences (always needed):**
video (private on youtube): https://youtu.be/cZ79S6OVel8

please lt me know if link is not working

**Comment by lilimx** [comment]
Hey,

thank you for your ticket, but your video is still on private so I can't watch it.

**Comment by LeonardoFurci** [comment]
dear lilimx

thanks for letting me know!

I have now made the video public: let me know if this link works https://youtu.be/cZ79S6OVel8 

Always struggles with private videos and their "sharable" links

**Comment by lilimx** [comment]
Hey,

please use the .getstats command to verify your statement.
The paperdoll display isn't reliabel.

**Comment by LeonardoFurci** [comment]
thanks for letting me know. I didn't know of such command. 

I tried it and the results didn't change from the paperdoll. below I attached the screenshots of the GetStats output with and without the tactic.
![MA bug +tactic](https://user-images.githubusercontent.com/73412085/129018181-01bf9546-775b-46e9-92a1-da58e15593f6.png)
![MA bug NOtactic](https://user-images.githubusercontent.com/73412085/129018193-24af71c9-8647-4bdf-8409-83fab536758d.png)

as you can see the STR value doesn't change, despite Ballistic Skill increasing by 160.

**Comment by lilimx** [comment]
Hey,

actually it works as intended. You only gain strenght through items, not through tactics. 

![grafik](https://user-images.githubusercontent.com/23266079/129025867-13c66373-59fe-4833-898a-c7afd32fe9b3.png)
