### ISSUE TITLE
Zealot: aethyr shock don't work probably

### ISSUE THREAD

**Issue by Mongognom** [WarEmu/WarBugs#1938]
had a fight with a sw and staggered him 4 times and just 2 times it worked - sw had no immu timer and didn't use his m2 to get out of it (whispered with him and get a confirm on that)

**Comment by Evildoor** [comment]
And the stagger was not disrupted?

**Comment by Mongognom** [comment]
nope not disrupted....the flares over the head were shown for a milisecond and the immu timer triggered but nothing else happened ( and of course i didn't damage or autoattacked him =) )
