### ISSUE TITLE
Even "blood in the water, part 2"

### ISSUE THREAD

**Issue by zedebenetleilax** [WarEmu/WarBugs#19385]
hi 
Even "blood in the water, part 2"
when I click on the ekrund relic nothing happens, (no clicking noise on the object) a pop message counter displays a few seconds: "1/14, 2/14" (etc. I am at 14 / 14), but it is not counted in the even part of the book (nothing written and counter to zero in "find the dwarfen valuables")
ThX
Zede / WH / RR91

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. 
I will add this report to the related issue.

**Comment by lilimx** [comment]
related to #19395
