### ISSUE TITLE
Can't create new characters, visual glitches in character creation.

### ISSUE THREAD

**Issue by Roxfall** [WarEmu/WarBugs#19390]
**Expected behavior and actual behavior:**

During character creation, only the weapons are visible. The characters are either missing or crumpled to the ground in formless (but clothing-textured) heaps.

UI is also a little messed up. It starts with all the windows opened at once. Then I was able to press the - button to get back to selecting faction -> race -> class -> details, but I got no further.

I expect to create a character when pressing done button. Nothing happens instead.

It does not appear to be possible to join this game. Both my wife and I are seeing the same problems.

**Steps to reproduce the problem:**
Make a new account.
Download a client.
Try to create a character.
Watch the fireworks.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

it's just close the game and launcher, restart the launcher and game. 
You can check about that in the install guide here: https://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=31241
If you have still issues with the install, please join the RoR discord (How to join: https://www.returnofreckoning.com/forum/viewtopic.php?f=2&t=22044) and ask in #technical-advice
