### ISSUE TITLE
Pop group ranking games allow fight 6 vs less ppl.

### ISSUE THREAD

**Issue by Wraxin** [WarEmu/WarBugs#19392]
The leader accidentally signed up for group ranked. 2 People decline the pop. The game started 6 vs 4.
Free mmr and crest for enemy team.

**Comment by dalen** [comment]
well, either you do it this way, or you allow dodging enemy teams. I think this way is the better of the two options.

Only other option I can think of really would be to just teleport players in, not give a SC pop at all.
