### ISSUE TITLE
All mobs are dead.

### ISSUE THREAD

**Issue by wiwi1990** [WarEmu/WarBugs#19396]
HI. In quest " The Chink in Their Armor" mobs don't respawn and i can't drop quest items

**Comment by Lheana** [comment]
Everything is fine
![Anaehll_485](https://user-images.githubusercontent.com/11537611/129480867-cada93e6-e320-4fa0-894a-42266ee98009.jpg)

**Comment by Lheana** [comment]
After testing the whole quest line, I understood you were talking about the NPCs in the PQ for the second step of the quest. Please give **more information** next time.

**Comment by wiwi1990** [comment]
In Caledor Darkspine Descent. I need drop 4 vault gems in quest The Chink in Thair Armor.
![Masagus_001](https://user-images.githubusercontent.com/88961482/129482548-ad8d8e7b-6e35-4334-a0ae-ffc873843a80.jpg)

**Comment by lilimx** [comment]
Fixed with Patch 20/08/2021
