### ISSUE TITLE
WH attack animation of Razor Strike changed from quick slice to slow torch

### ISSUE THREAD

**Issue by Gunlingers** [WarEmu/WarBugs#19394]
WH Skill Razor Strike animation changed from a quick left to right forehand slice with the sword hand, into the same animation like Burn, Heretic! and Burn Away Lies, a forward torch stab with the pistol hand

**Expected behavior and actual behavior:**
Razor Strike should be a fast slice with main hand weapon. Now it is a slow torch stab with offhand weapon

**Steps to reproduce the problem:**
Use of skill Razor Strike

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. This issue is already known.
So I will add this ticket to the related one.

**Comment by lilimx** [comment]
dublicate/related to  #18617
