### ISSUE TITLE
BW tactic: Wildfire.

### ISSUE THREAD

**Issue by Fuineir** [WarEmu/WarBugs#1940]
When tactic Flashfire procs, it requires you to stand still for the spell to successfuly cast. While moving it will just bug out the animation of the spell without casting it. It should work in this way, that casting while moving under the tactic effect should allow you to finish casting, as it's insta cast.

As it goes for Wildfire, it should proc (I think) on spreading flames when it hits enemies via aoe, it does not.

**Comment by Evildoor** [comment]
One report per problem, please.

**Comment by noisestorm** [comment]
Thats is a general Issue with normal casts that get modified to instant casts. Also applies to AM spells with 5 stacks of mechanic. You cannot insta cast them while moving, but once you stand the spell gets executed as it should.

**Comment by Evildoor** [comment]
Ok, so Flashfire problem is a part of general issue reported elsewhere. Anyone has info if Wildfire should or should not proc on Spreading Flames aoe?

**Comment by noisestorm** [comment]
Description states "Any time a spell is disrupted". In my world this includes also disrupts from the triggered AoE Dot. At least in terms of consitency it should apply to it and Aza is taking descriptions literally :D

**Comment by Evildoor** [comment]
@noisestorm, we are talking about Wildfire now, which is a different tactic and is not related to disrupts.

**Comment by Evildoor** [comment]
According to #2089, Wildfire should proc off every Conflagration ability. I doubt that DoTs should (see similar issues with DoTs, #1384, for example), but i'm not a BW expert and Spreading Flames is not just a simple DoT, so we need someone who can clarify this problem. @ozarmidrashim, what do you think about this?

**Comment by Vancerus** [comment]
When i recall Liveserver times, Wildfire had this 25% chance to procc, when the DoT is beeing applied on the enemy (not with every tick, that is probably what you mean)

**Comment by Fuineir** [comment]
I think it should proc upon AoE portion of spreading flames, also, I've never seen it proc upon Backdraft, which is an direct effect skill with DoT portion on it. Imo, Wildfire should have a chance to proc on Conflagration skills, even if they're DoTs, at the time of their application, not while they're doing dmg over time (with exception of spreading flames AoE).

I've even found old tooltip of the tactic: [source: http://warhammer.gamepressure.com/war_abilities_bright_wizard.asp]

Wildfire - When an enemy is hit by your Fiery Blast, Scorched Earth, or Flame Breath, there is a 25% chance that they will become surrounded by flames for X SECONDS, dealing X ELEMENTAL DAMAGE each second to all other enemies within X FEET of them.

Which indicates that it procced from Flame Breath, then it has been revamped to work with every ability of the tree. It already has 25% of proccing chance, which is quite low, for a tactic that's that high in mastery tree.

**Comment by Luth-RoR** [comment]
Fixed.

**Comment by Luth-RoR** [comment]
From https://github.com/WarEmu/WarBugs/issues/9506

>Now wildfire does not proc on Flame Breath, Spreading Flame, Backdraft.

**Comment by wargrimnir** [comment]
This will apply on AOE and Direct damage next patch, but not dot ticks. Added a 3s proc cooldown to keep it from spamming, that means you'll at best only have two instances of it ticking on separate targets at a time.

**Comment by Natherul** [comment]
fixed as of patch just now
