### ISSUE TITLE
Mara's Hulking Brute No Initiative

### ISSUE THREAD

**Issue by Souviel** [WarEmu/WarBugs#19405]
The Marauder's Path of Monstrosity tactic, Hulking Brute, only gives Toughness and not Initiative as the tactic tooltip suggests.

Expected Behavior:
While in Gift of Monstrosity stance with the Hulking Brute tactic, you gain bonus Toughness and Initiative. This should be reflected in Gift of Monstrosity's buff tooltip, as well as on the paper doll.

Actual Behavior:
The Hulking Brute tactic only gives Toughness. And further only displays Toughness in the Gift of Monstrosity buff tooltip.

Screenshots:
In Pic A you'll see my unbuffed paper doll stats, Toughness: 192, Initiative:151.
In Pic B you'll see both the Hulking Brute tactic's tooltip displaying 120 bonus Toughness and Initiative, and my character only gaining the 126 Toughness (+6 toughness modified by stone buff) and 0 Initiative.
In Pic C you'll see the Gift of Monstrosity buff tooltip displaying that Hulking Brute is only giving Toughness, no Initiative.

![Pic A](https://user-images.githubusercontent.com/89318141/130334564-a7c989cc-82c1-463e-a822-e9835e1b8fa7.jpg)
![Pic B](https://user-images.githubusercontent.com/89318141/130334568-bb623c11-0c23-40c6-8f81-7b1d3ec1f713.jpg)
![Pic C](https://user-images.githubusercontent.com/89318141/130334575-d2b5d271-71e6-4db2-9f25-8a9c95253a3a.jpg)

Related:
The Marauder's Path of Savagery tactic, Sything Talons, is incorrectly displaying Strength instead of Initiative in the Gift of Savagery buff tooltip.

Expected Behavior:
While in Gift of Savagery stance with the Scything Talons tactic, the Gift of Savagery buff tooltip should reflect the tactic bonus of added Weapon Skill and Initiative.

Actual Behavior:
With Scything Talons, the Gift of Savagery buff tooltip displays adding Strength and Weapon Skill.

Screenshots:
In Pic D you'll see Scything Talons' tactic tooltip displaying 120 bonus Weapon Skill and Initiative. 
In Pic E you'll see Gift of Savagery's buff tooltip displaying incorrectly 120 bonus Strength and Weapon Skill.

![Pic D](https://user-images.githubusercontent.com/89318141/130334873-ed9eebbd-1b19-4773-a48f-69ceb1b12b9e.jpg)
![Pic E](https://user-images.githubusercontent.com/89318141/130334875-5b02c07d-ff9f-4489-b6be-609255f10303.jpg)

Note:
Everything else is working as intented.

**Comment by lilimx** [comment]
Hey,

this is not a bug...please check your stats via .getstats the paperdoll display isn't a reliable source. 

Someone wrote a similar ticket: #18989
