### ISSUE TITLE
Kicked to Char-select and unable to log on

### ISSUE THREAD

**Issue by BomblingTV** [WarEmu/WarBugs#19406]
**Expected behavior and actual behavior:**
After selecting your already created character, some characters seem to get "stuck" unable to log in. 

**Steps to reproduce the problem:**
Clicking a character and pressing "play" after the usual loading screen and where you should load the gameworld you are suddenly kicked to char-select but nolonger showing all your toons but only the one who is bugged. None of the buttons actually work apart from "quit" and it will send you back to the launcher. Tried rebooting, closing client but char was still bugged after ten attempts.

Not sure what details made it get stuck. The toon was bugged on two occations, first in Altdorf market. And later on in Sigmars hammer. Other toons could be logged in normally. I tried typing /stuck /stuck in loading screen to force myself to nordland but didnt work. This issue occuered after either latest patch or one before it.

**Testing Screenshots/Videos/Evidences (always needed):**
https://imgur.com/a/ai2DUiJ

**Comment by Psychoxell** [comment]
I can confirm this. I even tried to delete all Addons and UI Settings (Folders) to start with a fresh ui. This sometime work after 10 tries... 

I only have this with one character (sadly my main). All other toons work fine.

**Comment by lilimx** [comment]
**Hey,

if this issue occures on your end, please leave a note on our forum post here:**
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=46249

**Comment by Zomega-WAR** [comment]
Still going on and affecting people. Today I had something new come up when trying to login (game crashed afterwards)

https://i.imgur.com/ItRcuHf.png

Zones I believe are 0-999...

**Comment by afa555** [comment]
Hello. I can't log into the game as one of my characters. his nickname is "Faketaxi". I just get thrown back to the character selection screen. The last time I was in the destruction warcamp, in Ostland. On the other characters I can log in with no problem. pressing Enter on the boot screen and chatting /stuck I already tried and it did not help. please help me with this problem

**Comment by afa555** [comment]
I temporarily solved this problem by repeatedly trying to log in to this character. Eventually I was allowed into the game. I cleaned up my inventory a bit and canceled more than half of the active quests I had taken. Perhaps the excessive amount of information the game was trying to load from the server was interfering with the login
