### ISSUE TITLE
Ch 22 Caledor - Tor Sethai - Can't interact with orbs

### ISSUE THREAD

**Issue by keunglh** [WarEmu/WarBugs#19413]
In the final phase of Tor Sethai (Ch 22 PQ) Caledor, the normal mechanic is that the boss will stun the warband and an individual will interact with an orb that spawns to prevent the boss from wiping the group. 

However, it is currently bugged where the orb will spawn visually, but it cannot be interacted. This leads to a near impossible chance to complete the final stage.

**Comment by lilimx** [comment]
Fixed with patch 18/09/2021
