### ISSUE TITLE
Dwarf Event kills not counting towards event progression

### ISSUE THREAD

**Issue by Mossesman** [WarEmu/WarBugs#19419]
I am currently making my way through the Dwarf events, and I have run into a problem where greenskin kills don't seem to be counting properly towards the kill section of the events.

**Steps to reproduce the problem:**

1. Kill Greenskins in lakes/scenarios
2. Kill count not updating

When the "Return to Ekrund" event started I didn't seem to have this problem, and I am sitting at roughly 20/50 kills for each class. I neglected the event for a few weeks and came back to it the other day, but I have noticed whilst the attack/defend objective updates with no problem, the greenskin kill count hasn't changed. Kills within the RvR lake and scenarios do not seem to be counting.

I am also have the same problem with the "Blood in the Water" event. The screenshot below shows that whilst I have completed 2/4 of the objective kills (this was done during a large fight in MoM earlier in the week), I am still sitting at 0/200 on greenskin kills.

![Screenshot 1](https://user-images.githubusercontent.com/90095668/132095748-8ea2cd73-01e5-4e13-8d0b-8569dcec10b7.PNG)

**Comment by Mossesman** [comment]
Update - I repaired my client. Kills are now starting to count towards the "Blood in the Water" event but not "Return to Ekrund"

Also, I heard that some people have been able to pick up the final event reward without having to do the kills task (whilst completing everything else). Im guessing this wasn't intentional as I am sitting at 9/10 on "Return to Ekrund" and can't pick the final reward?

**Comment by GamesBondd** [comment]
Are you sure? Cause we haven't heard of such reports other than here and we tested the kill count in both zones and it worked normally.

**Comment by Mossesman** [comment]
Apologies for the late response. After the last couple of patches (and after repairing my client), it seems to be working now.
