### ISSUE TITLE
dok vanquisher set : 4th set bonus (item)

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#19421]
per tooltip should recover 15 essence every second per 3 seconds, it regen only 5 essence
(set bonus have no name)

how reproduce: equip a shield to remove missguiding chalice regen, spam heal till something proc the effect; it will recover only 5 essence per second instead 15

edit: likely the same happening for wp vanquisher, it need to be check
edit 2: triumphant set for dok/wp also have the same vanquisher set bonuses so it requrie to be check aswell.

**Comment by SilverWF** [comment]
Not, proc says "recover 15 essence over 3 seconds"
so 5 per sec.

**Comment by Tesq** [comment]
yes but in live was per sec, yep... so duno
