### ISSUE TITLE
[High Elves] Guild Mount not available - Duplicate one

### ISSUE THREAD

**Issue by CrimsonFenris** [WarEmu/WarBugs#19427]
**Expected behavior and actual behavior:**
Found out there are a duplicate Elven Horse on guild merchant (7 days mounts for 2 guild coins).

There are 2 iterations of the "Blue Roan Elven Charger" (with different icons), but the "Strawberry Roan Elven Charger" looks like missing (it is available as one of the 6 visible mounts in the courtyard, see screenshot).

Couldnt test buying the first Blue Roan mount (white icon) to see if its only a name mishap, or if the two Blue Roan are the exact same skin.

**Testing Screenshots/Videos/Evidences (always needed):**
The listing showing 2 duplicate names :
![Fendaryon_100](https://user-images.githubusercontent.com/40425011/132597881-02920c10-5452-49bb-9305-b796751a3bc9.jpg)

The missing (apparently available) skin : 
![Fendaryon_099](https://user-images.githubusercontent.com/40425011/132598178-09ab51e7-6cb7-405d-93a8-d3f5df93d10c.jpg)

**Comment by lilimx** [comment]
Hey,

Im closing this ticket now due to patches it's a bit outdated.
But it's still related to the new issue #20037
