### ISSUE TITLE
Stunties For Da Forge (quest), TM chap 17

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#19425]
step 3 or 4 requrie kill some mobs but these are out of range from any skill both melee and aoe, so de facto not attackable 
( 1602k : 59245k; und-a-runki-blacksmith) 
![Draznicht_003](https://user-images.githubusercontent.com/7527415/132542245-a1caba3b-ae10-481e-973b-10feee19d527.jpg)

**Comment by Tesq** [comment]
it's not part of the public quest, just near it

**Comment by Lheana** [comment]
You are not meant to kill them, read the quest.
