### ISSUE TITLE
Witch Hunter - Feinted Positioning sometimes will not work/go off. The WH will do the motion and have the sound and visual effect, but no buff or ability to use positional styles in any position.

### ISSUE THREAD

**Issue by Sully013** [WarEmu/WarBugs#19426]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by xpander69** [comment]
could you possibly record a video about this?
could it be network lag related?

**Comment by lilimx** [comment]
Hey,

additional please rewrite your ticket and don't put all inside the headline

**Comment by lilimx** [comment]
Hey,

Im closing this ticket now. We haven't received enough information from the player and the 2 weeks ultimatum ran out.
