### ISSUE TITLE
Tactics and abilities from other characters available to current character.

### ISSUE THREAD

**Issue by Gobtar** [WarEmu/WarBugs#1942]
Tested. Logging off a character, any character, and then logging on another will grant you abilities of BOTH careers. This is not just a UI bug, slotting tactics from another career will indeed work for new character I.e a Marauder with Divine Fury, or an Engineer with Stab you gooder.

**Comment by ozarmidrashim** [comment]
Doesn't work for me - is this consistent?

**Comment by Ungrin** [comment]
Confirmed, logged shaman and then logged my SW. Had Divine fury tactic and was able to use all tactics + morales + abilities..

**Comment by Evildoor** [comment]
Seems to have condition of some kind. I managed to run into this on the first try, but then i told my friend about this, and it did not worked for him.

**Comment by ozarmidrashim** [comment]
Preventative measure (block usage of any skill whose career flags don't match your own).

Cause unknown.

**Comment by ozarmidrashim** [comment]
Bug occurs if logging out while subject to Bolster.
