### ISSUE TITLE
Finding Phineas quest in Gunbad

### ISSUE THREAD

**Issue by DurinThornaxe** [WarEmu/WarBugs#19428]
It might be just me, but after a 4 hour Gunbad run in which we specifically killed ALL mobs in order to make rummaging around for Phineas' remains more easier, we spent another 2.5 hours looking for them and we couldn't find them. Here is a screenshot of the quest description: 

![Untitled](https://user-images.githubusercontent.com/86794706/132808135-b39283d1-1b60-4695-8f2b-f4450a11d465.jpg)

This was my 7th run in here and still couldn't finish this quest, I hope it's just me but something worth looking in to? And obviously we first looked in the right wing of Gunbad, where the labolatory is. 

This quest had an older issue as well, but it's different this time: #11375

Thank you for your time and effort, 
Durinsson

**Comment by Lheana** [comment]
It is fine for me:
![Anash_035](https://user-images.githubusercontent.com/11537611/132952438-b49bdc61-da41-40b6-b943-782c4320f825.jpg)
