### ISSUE TITLE
Mastery Respec Not Fully Refunding Mastery Points

### ISSUE THREAD

**Issue by SwagmastaSIM** [WarEmu/WarBugs#19422]
Hi there,

When I press "Respecialize" mastery abilities at a Career Trainer it removes all mastery points, except one, which seems stuck. 
It is not able to be removed no matter what I do; I would expect it to be refunded when I press "Respecialize".
It only seems to affect my KotBS and only the first point in the "Path of Conquest" tree.

See screenshot below (I hope it attaches correctly as I can only see a link currently):
![image](https://user-images.githubusercontent.com/39796150/132200509-4f0a18d9-0c06-427f-8c18-019403a21851.png)

Thanks for your awesome server by the way! It's really really well done :)

Kind Regards,

Grateful Player

**Comment by xpander69** [comment]
does it still stay there after relog? or /rel command?

**Comment by Kabucoror** [comment]
I guess you kotbs wears the Challenger set which gives you +1 to Path of Conquest. This can not be respecialized for obvious reasons.

**Comment by SwagmastaSIM** [comment]
Ah! Yes, that would be right... 😅

I’m very sorry to have wasted your time!
Thank you very much for prompt responses; you guys are legends!

Kind Regards,

Caleb

**Comment by xpander69** [comment]
problem solved
