### ISSUE TITLE
Carrying a building with me after patch

### ISSUE THREAD

**Issue by Tykros** [WarEmu/WarBugs#19439]
**Expected behavior and actual behavior:**
After the big patch I logged on with my char Sheerargetru and several players told me I was carrying a building with me as you can see on the screenshot.
I can't see it myself on my screen, only other players seem to be able to see it. The picture is taken by a Guildy.
 I relogged and even restarted the game without effect. Also removed all items on my char (weapons, armor, pocket items, trophies, etc, all without any change. 100% naked= still the same.

 
 

**Steps to reproduce the problem:*

**Testing Screenshots/Videos/Evidences (always needed):**

![Skyrak_004](https://user-images.githubusercontent.com/25689339/133898421-88b1b8c5-4921-4f42-9b65-f7e9d24e8c9b.jpg)
z

**Comment by lilimx** [comment]
Hey,

I posted your ticket in our team chat, hope Max or someone else with a clue will take a look. 
Did you experience any other weird things after the patch?

**Comment by Tykros** [comment]
No, All else is fine. Download went smoothly without interruptions or anything. 
But I've also seen other players with stuff attached to them. I've seen an elf with a gyrocopter on him and another with a telescope. The Gyrocopter-dude could see my building but he could not see his own gyro, just like I couldn't see my building.

**Comment by acidicrain** [comment]
There were toons with the building , a helicopter, a telescope and a pice of rail visage. As if a gear item was mixed with othe game objectes

**Comment by xpander69** [comment]
yeah, saw the copter and piece of rail also, sadlly didnt take any pictures. Maybe its some of those appearance cloak changes? mixed up ID's or something

**Comment by Symbelmyne** [comment]
Ive noticed few ppl with that graphic glitch, most of them had alt. apearance some Bat cloak (i think some event cloak)

**Comment by Tykros** [comment]
I have that batcloack as an alternative appearance and removed it to check if that was the prob, but the result stays the same.

**Comment by Symbelmyne** [comment]
![WAR-64 2021-09-19 16-55-41](https://user-images.githubusercontent.com/16525371/133932147-1b7af5c3-659b-44f8-936c-8c4684ef4ddf.png)
 Thats just EPIC.

**Comment by acidicrain** [comment]
here is a video of the rail section anf gyrocopter
https://youtu.be/42oPMv6FQ28

**Comment by dalen** [comment]
this was fixed in a hotfix
