### ISSUE TITLE
PQ Greenskin Burnbeards Oath

### ISSUE THREAD

**Issue by acidicrain** [WarEmu/WarBugs#19436]
Unable to get past stage 2 of  PQ Burnbeards Oaths Greenskin chap 20
**Expected behavior and actual behavior:**
in stage 2 you need to use the rock lobbers to destroy the statue , can not get the lobbers to fire

**Steps to reproduce the problem:**
kill dwarfs, get to stage 2
in stage 2 the lobber gits prepare the lobbers
try to fire lobber, could not get lobbers to fire
could highlight click etc the lobbers bbut could not get them to fire

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by acidicrain** [comment]
pq is completable but not via lobbers,  a gobo was there and could complete it

**Comment by acidicrain** [comment]
tried this again today , could not complete for same reason. re-open

**Comment by Lheana** [comment]
You need to destroy the gyrocopter, the statue and the tents directly, by attacking them.

**Comment by acidicrain** [comment]
The items you describe were destroyed , possible I made error that it was stage 3
