### ISSUE TITLE
Graphics bug: large stone wall segment aroung player

### ISSUE THREAD

**Issue by ChimBrouer** [WarEmu/WarBugs#19443]
In the new dwarf city, there was a huge graphic object wrapped around another player. 

- It was NOT visible for the player himself
- It was visible to several other players
- It stayed regardless it he was on a mount or not
- the Player was a dwarf (when I met him, he used his "mount"/helicopter)
- We tried changing zones in the dwarf city, but the graphic object stayed
- I added two screenshots below

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![bzug1](https://user-images.githubusercontent.com/3807126/133924089-df6f5a29-8afc-4c9c-abc8-a39b4e200ccb.png)
![bug2](https://user-images.githubusercontent.com/3807126/133924093-8284651b-7ed1-4927-a63f-89530f896809.png)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
I will add your ticket to the related report.

**Comment by lilimx** [comment]
dublicate / related to  #19439
