### ISSUE TITLE
Gud Eatz! Quest items locked behind invisible wall

### ISSUE THREAD

**Issue by Icanhascookie** [WarEmu/WarBugs#19442]
**Expected behavior and actual behavior:**
For the quest Gud Eatz!, in Da Deeps' Squig nursery, is 2 food items you need to click but the test has an invisible wall inside it that makes it impossible to click them. One of the items is actually clickable with some nifty camera work bu the other one is too deep inside the wall that you cant click it.

**Steps to reproduce the problem:**
Try to walk into the tent, but there is collosion.

**Testing Screenshots/Videos/Evidences (always needed):**

![GudEatz](https://user-images.githubusercontent.com/3661117/133911068-0659c1af-cb36-4e49-9123-9d7a8672ae38.png)

**Comment by Tesq** [comment]
it really is possible to just click the barrel with since it is close outside to end barrier in one tiny spot.

Remove the barriers or mvoe the itiems outside will fix the problems

**Comment by Lheana** [comment]
A workaround has been made: The 2 GameObjects have been spawned outside of the tent until the collision issue is properly fixed. The workaround is on live server.

**Comment by GamesBondd** [comment]
As @Lheana mentioned, here's where they are:
![image](https://user-images.githubusercontent.com/62469352/133930854-e9235848-6a76-48d0-bbf6-3b5ca75d3776.png)

**Comment by Icanhascookie** [comment]
Thank you for the quick work around/fix!

**Comment by lilimx** [comment]
Fixed with Patch 24/09/2021
