### ISSUE TITLE
[Appearance] Something is off about Thoreksson's Warhammer 

### ISSUE THREAD

**Issue by CornerbackAC** [WarEmu/WarBugs#19447]
**Expected behavior and actual behavior:**
Expected: its a) a "Warhammer" and its b) 1-handed.
Actual: Its a) an Axe and b) has a 2-handed appearance

Btw... I love the skin. Which 2h Axe has this skin?

**Steps to reproduce the problem:**
Equip Thoreksson's Warhammer 

**Testing Screenshots/Videos/Evidences (always needed):*
![appearance](https://user-images.githubusercontent.com/11341460/133940704-2d0a85eb-eaeb-4117-a833-f3a0be027f53.PNG)
*

**Comment by Grock-r** [comment]
> Btw... I love the skin. Which 2h Axe has this skin?

I believe its only available for slayers as 61rr SC weapon.
I wonder how this bugged appearance would look if you equip a shield with it.

**Comment by lilimx** [comment]
Fixed with Patch 01/10/2021
