### ISSUE TITLE
Uzkular quest bugged.

### ISSUE THREAD

**Issue by dihanin** [WarEmu/WarBugs#19444]
**Expected behavior and actual behavior:**
use the mixture to call "Alcazoram the Suntouched"(lord) .and kill him. 
but if failed once(got killed) , try second time and back to where he show up.
he is gone.
and the quest item "mixture"  use one time only , and no more "mixture" quest item.
 so it's gone and can not call "Alcazoram the Suntouched"(lord) again.
quest stuck.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

where is the quest. Can you provide some screenshots?!

**Comment by dihanin** [comment]
> Hey,
> 
> where is the quest. Can you provide some screenshots?!

![image](https://user-images.githubusercontent.com/45137982/133927781-6a93dd68-61d7-4a47-85ba-0d158573e0f7.png)

**Comment by lilimx** [comment]
I meant a picture of the enemy and the name of its location (map/chapter).

**Comment by dihanin** [comment]
> I meant a picture of the enemy and the name of its location (map/chapter).

Can not Print screen . the enemy not show up anymore as I said.
![image](https://user-images.githubusercontent.com/45137982/133954268-be5fe219-cbfc-4080-89b3-985d1a3656c7.png)

**Comment by dihanin** [comment]
> > I meant a picture of the enemy and the name of its location (map/chapter).
> 
> I can not Print screen . the enemy not show up anymore as I said.
> ![image](https://user-images.githubusercontent.com/45137982/133954268-be5fe219-cbfc-4080-89b3-985d1a3656c7.png)
> This "NEW" quest from karaz-a-Karak.

![image](https://user-images.githubusercontent.com/45137982/133956857-04a9ca1a-d093-4b59-95b9-5c67b6d39687.png)

**Comment by lilimx** [comment]
Hey,

please try to abadon and retake the quest.

**Comment by dihanin** [comment]
> Hey,
> 
> please try to abadon and retake the quest.

Appreciate !!

**Comment by dihanin** [comment]
After follow you advise, abandon the quest. and retake the quest.
quest Item "corpsetallow mixture" is back.(in backpack)
but _**my**_ quest Item "corpsetallow mixture" clicking is not working. 
I can't use "corpsetallow mixture" quest item to call "Alcazoram the Suntouched"(lord) out.  
this  is  a  first  issue.
he  show up  because  my  partner  use  " corsetallow mixture"  quest  item.
the  second issue is  when  we  attack  him  to nearly  50%  ,  he  just  gone . 
no  any  reason  .   just  disappear  .

**Comment by dihanin** [comment]
> After follow you advise, abandon the quest. and retake the quest.
> quest Item "corpsetallow mixture" is back.(in backpack)
> but _**my**_ quest Item "corpsetallow mixture" clicking is not working.
> I can't use "corpsetallow mixture" quest item to call "Alcazoram the Suntouched"(lord) out.
> this is a first issue.
> he show up because my partner use " corsetallow mixture" quest item.
> the second issue is when we attack him to nearly 50% , he just gone .
> no any reason . just disappear .
![image](https://user-images.githubusercontent.com/45137982/134038907-d440b543-cb21-47e9-8e49-cbad64376e66.png)

**Comment by dihanin** [comment]
> > After follow you advise, abandon the quest. and retake the quest.
> > quest Item "corpsetallow mixture" is back.(in backpack)
> > but _**my**_ quest Item "corpsetallow mixture" clicking is not working.
> > I can't use "corpsetallow mixture" quest item to call "Alcazoram the Suntouched"(lord) out.
> > this is a first issue.
> > he show up because my partner use " corsetallow mixture" quest item.
> > the second issue is when we attack him to nearly 50% , he just gone .
> > no any reason . just disappear .
> > ![image](https://user-images.githubusercontent.com/45137982/134038907-d440b543-cb21-47e9-8e49-cbad64376e66.png)

**Comment by ekalime** [comment]
You have to click on the bone pile to both 'use' the mixture and summon Alcazoran. Game objects have cooldowns often so if one person clicks it then the other will have to wait if they are outside the party. If you are partied, then it should give both players credit. As for him despawning quickly, I'll see if we can extend his time up while summoned.

**Comment by Lheana** [comment]
Timer of the NPC will be increased to 10 minutes with next patch.

**Comment by lilimx** [comment]
Fixed with Patch 01/10/2021
