### ISSUE TITLE
Choppa Stalker's armor has no appearance

### ISSUE THREAD

**Issue by Ryanfawkez** [WarEmu/WarBugs#1944]
The Stalker Tuff Chest for Choppas has no model yet. This is how the Stalker set should look for choppas: http://vignette2.wikia.nocookie.net/warhammeronline/images/1/16/Stalker_Choppa.jpg/revision/latest?cb=20090325070122

Not sure if the gloves and shoulders have the same issue

**Comment by genisaurus** [comment]
Fixed in next hotfix
