### ISSUE TITLE
Naked Players

### ISSUE THREAD

**Issue by TilliRage** [WarEmu/WarBugs#19445]
Some random players are looking naked. Even though they are equipping armors and all.

Equipped items on player characters should be shown on character.

I don't know how to reproduce this issue. It seems random. Some players are fine and some not. 

![naked_lol](https://user-images.githubusercontent.com/66213697/133929206-3918c504-4a0b-4cc7-84d1-8f701d68d313.jpg)

![naked2](https://user-images.githubusercontent.com/66213697/133929404-0333774a-b7f9-4a65-ae80-cc4ec1c979d0.png)

**Comment by Telja79** [comment]
have the same bug

**Comment by lilimx** [comment]
maybe related to  #19439

**Comment by dalen** [comment]
this was fixed an hour later in hotfix
