### ISSUE TITLE
Quest: Anniversary to Remember

### ISSUE THREAD

**Issue by ChimBrouer** [WarEmu/WarBugs#19449]
New Karaz-a-Karak Quest: Anniversary to Remember

**Expected behavior and actual behavior:**

Expected: Obtain the LEDGER OF ARTIFACTS when clicking on GRUM DOKOR
 Actual: Nothing happens, when you click on the NPC

I looked for the ledger somewhere around the NPC, but there is none.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**
![e2](https://user-images.githubusercontent.com/3807126/134026247-cde8cac3-27ad-4698-99bb-c502e74ae315.png)
![e1](https://user-images.githubusercontent.com/3807126/134026256-2ed0a2c9-af3e-4668-aa4f-47030a00a59a.png)

**Comment by ChimBrouer** [comment]
This is my quest bag. And what the screenshot shows is, I haven't obtained the Ledger as the quest text says ("0/1") and I am clicking on the NPC.

I looked around, if maybe the book lies somewhere, but I can not see anything. And the quest text says "go to NPC and get the ledger". That sounds like I have to click on the NPC to get the ledger.

![e3](https://user-images.githubusercontent.com/3807126/134208183-38063cd2-73cc-402d-a78d-c638aaca9454.png)

**Comment by CrimsonFenris** [comment]
Its a big book on a bench, in the central area (opposite side of the NPC).

**Comment by ChimBrouer** [comment]
You may be right.

The confusing thing is, that the book is at the NPC named "Dimzad Higar" and not close to "Grum Dokor". But Grum Dokor is mentioned in the quest and is also highlighted as the NPC for the quest, when you hover over him.

My fault, my old dwarven eyes are not that sharp anymore.
