### ISSUE TITLE
Thunder Mountain - Engineer Turrets Despawn upon Attacking

### ISSUE THREAD

**Issue by Viorayne** [WarEmu/WarBugs#19441]
**Expected behavior and actual behavior:**
What should happen is when I use a Turret Ability, it spawns a turret next to my Engineer character that attacks and activates its own abilities to deal damage and assists me in its own ways. It then stays around indefinitely until Ive travelled too far away from it, I create a new turret to replace, its destroyed by an enemy or I activate a self-destruct ability.

What actually happens is when I try to spawn a turret in Thunder Mountain Zone, the turret appears but doesnt attack and remains idle. When it's supposed to attack or I manually use one of its skills, the turret despawns (claiming in chat that it's too far away) even if im standing right next to it. Other placeables (such as Bugman's Brew from the Tinkering Mastery), can be summoned and work just fine. 

**Steps to reproduce the problem:**
To repeat the issue, you simply need to be in any area at Thunder Mountain, and summon one of the 3 Turret types as the Engineer class (Gun/Flame/Grenadier). Once you have the Turret attempt to attack a target, it will despawn regardless of distance to you.

**Testing Screenshots/Videos/Evidences (always needed):**

![GH1](https://user-images.githubusercontent.com/90990500/133910880-05f650d4-661d-415d-b15d-05310fb0b8bc.PNG)

![GH2](https://user-images.githubusercontent.com/90990500/133910878-d0ac4d03-8982-4ec3-843b-26c5b33434c5.PNG)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
This issue is already known so I'll add your ticket to a report where I gathered all these tickets.

**Comment by lilimx** [comment]
dublicate/related to #18872
