### ISSUE TITLE
[K8P] "A Skull Like No Other" quest missing map markers "zone" in quest page

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#19457]
**Expected behavior and actual behavior:**

I have noticed that some (maybe all) of the "A Skull Like No Other" quest chain is missing the map markers. Map markers I have noticed that are missing are:

1) The location of the Lazy Peon in the lower map
2) The marker to return to the Occuland of Tzeentch after absorbing the soul of the Lazy Peon
3) The location of Herald Brodkov

If I spot any more on this chain I'll update the ticket.

In addition, the "Zone" of the quest has not been set. I do not know which parts of the chain are missing it.

![image](https://user-images.githubusercontent.com/60266177/134428122-7a2030d7-2bf8-4776-9f53-2fe7c65c9cc7.png)

**Comment by ekalime** [comment]
As a hidden quest, it has no maps intentionally. These quests tend to have higher pay-off rewards and therefore have a bit more effort involved.
