### ISSUE TITLE
Is 40 lvl on T1 bug or normal?

### ISSUE THREAD

**Issue by Kuhtli** [WarEmu/WarBugs#19450]
![Scr00](https://user-images.githubusercontent.com/91080280/134032643-2dbae4c2-f440-459a-8261-2fedc616fbaf.jpg)
Saw it today....
![Scr01](https://user-images.githubusercontent.com/91080280/134032750-00e85c2f-8657-48ce-82d0-4e0da6c20cc0.jpg)

**Comment by SilverWF** [comment]
Yes it is normal
and he has lvl 11 stats, not lvl 40
