### ISSUE TITLE
Items not giving credit in SC's for the quest: Find the Valuables of Kurgaz in Karak Dron.

### ISSUE THREAD

**Issue by Tinkaballa** [WarEmu/WarBugs#19451]
I am not getting quest credit for the items found in the 4 SCs Thunder Valley, Gromril Crossing, Logrins Forge & Howling Gorge for the quest: Find the Valuables of Kurgaz in Karak Dron.

I have tried logging out and doing the sc's at different times over the last 24 hours and I have interacted with the items multiple times to no avail.

Please help I would like to complete this before time runs out.

**Comment by Lheana** [comment]
Have you done the quests to see the clues?

**Comment by Tinkaballa** [comment]
Sorry what quests, I thought you just click the item and it gives credit.

**Comment by Lheana** [comment]
You need to complete quests to be able to find the Valuables/Relics/Artefacts, as mentioned in the event tasks:
![image](https://user-images.githubusercontent.com/11537611/134817393-08c1deef-a7a8-42c7-bbf4-e94e95f9301d.png)
