### ISSUE TITLE
The Badlands normal PQ ''Bloody Savages'' Choppa Mobs are 55+Champs

### ISSUE THREAD

**Issue by Gunlingers** [WarEmu/WarBugs#19460]
The normal PQ ''Bloody Savages'' in the Badlands is no longer reachable/ doable for Players, because the 
Choppa Mobs are now Lv55+Champs

**Expected behavior and actual behavior:**
The Choppa Mobs ''Bloody Sun Hacka'' are now Lv 55+ Champs. 
They should be Lv 28 normal like the ''Bloody Sun Slasher''

**Steps to reproduce the problem:**
Fly to Badlands. March towards the PQ named Bloddy Savages from out PVE Chapter Camp 14 and try to cross the Bridge that leads to the PQ. :-]

**Testing Screenshots/Videos/Evidences (always needed):**

![Gunlinger_009](https://user-images.githubusercontent.com/54162117/134688363-1366d484-10af-41ad-b36a-df4b63caed66.jpg)
![Gunlinger_010](https://user-images.githubusercontent.com/54162117/134688435-92011c4b-4215-4f7c-ab1c-98b92dbbe88c.jpg)

**Comment by lilimx** [comment]
Fixed with Patch 15/10/2021
