### ISSUE TITLE
Quest 'Reinforcements' kills not counted

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#19466]
**Expected behavior and actual behavior:**
Kills are not counted for this quest.  I was in Marsh of Madness PvP area, at a Objective.  Kill and enemy and no kills.
See Screenshot

![reinforcements](https://user-images.githubusercontent.com/7898608/134817626-4d046eb4-0f7b-4929-b46f-86e92d60c85d.jpg)

**Comment by lilimx** [comment]
Hey,

_- Player kill credit for quests, tome unlocks and live event tasks is only granted to the group and warband members of the one that did the most damage (the one that gets the loot). Previously anyone that did any damage at all got kill credit. Renown and XP work in the same way as before._

That means in your case, that you haven't dealed enough dmg to get the kill credit for this.
