### ISSUE TITLE
K8P quest reward: "Bloodhorn Bigchoppa" wrong appearance 

### ISSUE THREAD

**Issue by acidicrain** [WarEmu/WarBugs#19461]
**Expected behavior and actual behavior:**
should be a 2h weapon is a 1h weapon

**Steps to reproduce the problem:**
equip item 

**Testing Screenshots/Videos/Evidences (always needed):**

https://cdn.discordapp.com/attachments/329292495336767488/891017588363124746/Fluf_115.jpg

**Comment by lilimx** [comment]
Should be fixed with the next server boot.

**Comment by lilimx** [comment]
Fixed with Patch 01/10/2021
