### ISSUE TITLE
Anarchy 2h sword not showing anymore after last patch

### ISSUE THREAD

**Issue by SODIX** [WarEmu/WarBugs#19463]
My sword from T4 Chaos Epic Quest are not showing anymore, I tried to re-equip it, still no luck. 
It also not showing in character screen.
Screenshots:
https://ibb.co/51RWb6M

**Comment by lilimx** [comment]
Hey,

you've checked, that your game has all updates? If your game isn't fully patched, you won't see your weapon in the character screen nor ingame (same for mailboxes)

**Comment by SODIX** [comment]
> Hey,
> 
> you've checked, that your game has all updates? If your game isn't fully patched, you won't see your weapon in the character screen nor ingame (same for mailboxes)

Yes, game fully updated.

**Comment by SODIX** [comment]
Fixed. Don't know how)
