### ISSUE TITLE
Burn away the lies 

### ISSUE THREAD

**Issue by Toldavf** [WarEmu/WarBugs#1946]
The skill currently gives 2 ticks at the same time at the end. A regular tick and the big tick in the same second. 

This gives the skill more burst then it should have. :)

**Comment by Evildoor** [comment]
What about total damage? Does it correlates with the tooltip? And how it was on live?

**Comment by Toldavf** [comment]
Unsure of total damage and it wasn't this way on live.

**Comment by Tesq** [comment]
https://www.youtube.com/watch?v=6gdhaTzpg74

at 2 min (2:10) the wh fight a bo, it seems a tick every 3 sec and it would make sense cos it's a 9 sec duration dot

**Comment by Toldavf** [comment]
![thorvold_004](https://cloud.githubusercontent.com/assets/13355649/11375510/9872b740-92d3-11e5-8870-94c82a2fd279.jpg)

Recruited a wh for testing special thanks to lleu

**Comment by Evildoor** [comment]
Hmmm. It seems that in ROR all (non-finishing) ticks are 3 seconds late, should be bullets+tick, tick, tick, finisher, and we have bullets, tick, tick, tick + finisher. Ok then.

**Comment by Vdovics** [comment]
If I remember corectly, it should tick every 3 seconds with 1st tick in moment of aply, so 0 second 1st tick, 3rd second 2nd tick, 6th second 3rd tick, 9th second ending dmg tick.
