### ISSUE TITLE
Empire influence not unlocking T3

### ISSUE THREAD

**Issue by Kenzing** [WarEmu/WarBugs#1947]
Empire influence is not unlocking, when talking to rally master in war camp/entering RvR lake.
I have tried all the tips with charging order war camp, flying to chp 13 etc etc.

According to advice channel alot of other players are having this problem as well.

**Comment by Calarian** [comment]
I know in some cases you may have to ride around the warcamp see if you can do to the back side of the Order warcamp Or ride close to where the Rats are by order warcamp

**Comment by Kenzing** [comment]
Yup, I stand corrected. Just managed to unlock it at the PvE entrance to order WC.

**Comment by Kenzing** [comment]
I've tried this now, but only managed to unlock order RvR influence.

I should have specified, that it was as destruction, I'm unable to unlock EmpirevChaos RvR influence.

**Comment by Evildoor** [comment]
Chaos influence? #1918.
