### ISSUE TITLE
Hard Nut to Crack, K8P

### ISSUE THREAD

**Issue by Stahn456** [WarEmu/WarBugs#19475]
The quest Hard Nut to Crack vanished from my quest log after turning in the step of releasing the 12 stunty miners. I accepted the step to speak to the auctioneer about buying a dwarf and on my way I got into an Ironclad scenario, but upon exiting the SC, the quest is gone from my list and the npc Engit Morkfist does not have it to give out again. It simply vanished. I spoke to the auctioneer anyway to see if it would progress, it does not. It simply no longer exists for my level 23 choppa. I attempted a /reload, camping out of the game and the launcher and restarting, nothing has brought it back.

**Expected behavior and actual behavior:**
To speak to the auctioneer in K8P to progress quest. Actual, the quest is no longer given by npc, no longer in my tome on quest log, and cannot be progressed by action.

**Steps to reproduce the problem:**
Not sure, can't remove it or accept it again to repeat it.

**Testing Screenshots/Videos/Evidences (always needed):**

![Waaaaghrior_000](https://user-images.githubusercontent.com/79117022/135348359-3f1d8854-73ca-4109-b34e-5bcf8de54afe.jpg)

**Comment by ekalime** [comment]
This is not a bug; the last step of the quest is for level 24 players to indicate the passage of time. I know it may feel confusing but quests are available at different levels and as you level up more quests are available.

**Comment by Stahn456** [comment]
Then the bug was that it was offered and accepted. Either way, something happened here that shouldn't have. I saw the list of all 4 rewards for choppa before accepting it.

Sent from Yahoo Mail on Android 
 
  On Thu, Sep 30, 2021 at 11:13 AM, ***@***.***> wrote:   


This is not a bug; the last step of the quest is for level 24 players to indicate the passage of time. I know it may feel confusing but quests are available at different levels and as you level up more quests are available.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
