### ISSUE TITLE
[Quest] Nubungki error in text

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#19472]
**Expected behavior and actual behavior:**
I didn't expect the paragraph to end like this, seem cut off, no period.  (see SC)

**Steps to reproduce the problem:**
Last step in quest line (I think)

![nubunki_LI](https://user-images.githubusercontent.com/7898608/135179721-ee85d842-54f4-49c3-9b0b-114ee52f5ac5.jpg)

**Comment by ekalime** [comment]
This is not a bug; there is a character limit in the text box - you have to read it in the Tome of Knowledge to see the full text.
