### ISSUE TITLE
Burnbeard’s Oath PQ Greenskin ch 20 statue is invisible

### ISSUE THREAD

**Issue by acidicrain** [WarEmu/WarBugs#19477]
In stage 2 of the PQ you need to destroy three sets of items.
Gyrocopter, tents and a statue
The statue is invisible and as such tough to find 

**Expected behavior and actual behavior:**
The statue should be visible at all times, it is never visible

**Steps to reproduce the problem:**
To see the problem move to the pq and try and see the statue.
To complete the pq you need to face where the statue is and aoe in that direction, check for damage being taken by statue using the combat log to validate you are hitting the statue

**Testing Screenshots/Videos/Evidences (always needed):**

https://cdn.discordapp.com/attachments/740320042616619009/892890470114537472/Fluf_117.jpg

Picture shows position I needed to stand to hit statue with hit visible where damage marks the statue, confirmed with combat log

**Comment by Zomega-WAR** [comment]
This PQ is also needed as part of the K8P questline "Flyin' Dangerously". @lilimx please can you add the extra labels?
