### ISSUE TITLE
Kind of [Lasting Erupting Blast Potion] that are not removed

### ISSUE THREAD

**Issue by Rangotiko** [WarEmu/WarBugs#19488]
The [Lasting Erupting Blast Potion] were removed from the game because they were meaking to much lag, but you can actually get almost same efect with other Potion that is not removed. The Potion is [Lasting Fiery Breath Potion] and almost same happens with all other Potions of the same kind of lower levels.

When I try to use classic Potions: [Lasting Erupting Blast Potion]
![image](https://user-images.githubusercontent.com/91816151/135739691-9b9b88c4-f7bd-4333-bac8-88c7dcdc5fe8.png)
I appears that i cant use the item (because is removed and i should not be able to use it).

But when I try to use [Lasting Fiery Breath Potion]
![image](https://user-images.githubusercontent.com/91816151/135739808-84aed269-1253-4a29-a784-8b345ebe346a.png)
I can use it and not only that, the potion actually works so it creates the same lag as Classic Potions because also has the duration of 18 sec and do AOE effect.

**Comment by Zomega-WAR** [comment]
The lag was (supposedly) caused by the special effect of the blasting potions. Do the fire breath potions actually put anything on the ground or are they just apply a dot to whever was in range when the potion is used?

**Comment by Rangotiko** [comment]
> The lag was (supposedly) caused by the special effect of the blasting potions. Do the fire breath potions actually put anything on the ground or are they just apply a dot to whever was in range when the potion is used?
> 
> I don't know from the screenshot if you have effects turned off or if the potion doesn't put one on the ground.

Thanks for your contribution, but if you are right, the max level Potion of Fire Breath Should be work since dont creates any Lag.

I create a level 200 Potion of fire breath: [Lasting Pyrewind Potion] and I tried to use it same was as i used [Lasting Fiery Breath Potion] (The potion that i said should not suppose to work)
![image](https://user-images.githubusercontent.com/91816151/135761474-b290ac75-3c6a-40a3-b105-e39b56244ef9.png)
As you can see the photo, when i try to use this Potion the game says that i cant use it, thats because the Potion is also removed from the game.

I dont write this saying that you are wrong.

You post give us 2 options:
1) My first Post is right and the [Lasting Fiery Breath Potion] is a Bug and you should not be able to use them (because teorically creates lag).
2) You Post is correct, but then the [Lasting Pyrewind Potion] should not be removed.

The conclusion is: [Lasting Fiery Breath Potion] should be removed or the [Lasting Pyrewind Potion] should be able to use again.
Thanks for your contribution again, all coments help to createa more consistent argument.

**Comment by Rangotiko** [comment]
Also level 175 potion: [Lasting Ash Howl Potion] cannot be used as well, then they get in to into the same category of the [Lasting Pyrewind Potion]
![image](https://user-images.githubusercontent.com/91816151/135762109-b9014ebe-f96c-48ed-b459-114a436f7562.png)

**Comment by dalen** [comment]
Only blast pots were disabled, not fiery breath potions which is a different thing.
