### ISSUE TITLE
Sentinel Souls cannot be stacked in your inventory

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#19492]
**Expected behavior and actual behavior:**

Sentinel Souls are a currencythat can be used to trade and buy different weapons from the R40 city dungeons. The Sentinel Soul items cannot be stacked in your inventory even though they are generic, meaning each soul (maximum of 4) will take up a slot in your bags (maximum of 4).

I traded in my unused sentinel weapons for Sentinel Souls to free up bag space, but as the Sentinel Soul currency items cannot be stacked I have no more space than I did before and I'm down 120 gold.

**Steps to reproduce the problem:**

Trade in 2 named weapons from the city dungeons for Sentinel Souls. They will not stack in your inventory.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/60266177/135757998-f98a8ce9-5b74-4087-b099-b237f11eeb2a.png)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by lilimx** [comment]
Fixed with Patch 15/10/2021
