### ISSUE TITLE
Stalker's Devotee Kit (Zealot Stalker Set) cannot be salvaged

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#19491]
**Expected behavior and actual behavior:**

Expected: all 4 pieces to be salvagable.
Actual: none of the 4 pieces are salvagable.

Armoury links:

https://www.returnofreckoning.com/armory/item/434606 - Boots
https://www.returnofreckoning.com/armory/item/434642 - Chest
https://www.returnofreckoning.com/armory/item/434630 - Shoulders
https://www.returnofreckoning.com/armory/item/434618 - Gloves

**Testing Screenshots/Videos/Evidences (always needed):**

Trying each of the 4 pieces:

![image](https://user-images.githubusercontent.com/60266177/135755609-af3ab682-1f0b-47c1-b007-eb40b50ef8a7.png)

**Comment by Kabucoror** [comment]
None of the Stalker set items are salvagable. This is intended.
