### ISSUE TITLE
Sentinel Souls cost 40g when bought instead of when traded for weapons

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#19493]
**Expected behavior and actual behavior:**

Expected: Conversion from sentinel weapon to sentinel soul is free. Conversion from sentinel soul to sentinel weapon costs 40g as per the tooltip on the sentinel soul.

Actual: Conversion from weapon to soul costs 40g, conversion from soul to weapon is free. This means you have to pay the gold up front as opposed to what it says on the tooltip for the souls which says trading in the soul costs 40g.

**Steps to reproduce the problem:**

Turn named city dungeon weapon ("sentinel weapon") in for a sentinal soul. It will costs you 40g. Then buy a weapon with the soul. It won't cost you gold.

**Testing Screenshots/Videos/Evidences (always needed):**

Confirmation that the gold should be taken when you turn in the soul for a weapon:

![image](https://user-images.githubusercontent.com/60266177/135758239-b0af28c6-4656-4714-8e41-363b1ab9e16c.png)

I do not have screenshots of the 120g I lost turning 3 weapons into souls, nor the extra 40g lost testing it for this bug report.

**Comment by Kabucoror** [comment]
fixed with next patch
