### ISSUE TITLE
Keep defense timer reset with outer walls cannons being hit.

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#19499]
If one side was able to defend their keep and not allow attackers to pass further, then there is 10 min timer starts and when it's expire it's enough to drop 1 resource and keep will be "defended" : all doors will be repaired and defenders will receive their rewards. 
Attackers could reset this timer by hitting doors or lord (if all doors down) and it require to remove at least 2% of HP to reset timer.

But, atm attackers could hit static cannons at outer walls and timer will be reset.
This cannons are pretty squishy and it's literally enough to just 1 hit to remove 30% of HP (or more) so this will be enough to reset timer and prolong awaiting.

Just imagine: main attacker forces already left the zone a hour ago, 100+ players are mindlessly sitting in their keep, guarding lord and 1 single cannon and 1 (one!) WH or WE (never seen that from WEs tho) comes, making 1 (one!) hit and timer resets. Yes, he will die after that, but just ONE hit is enough to lock whole faction at place for the next 10 min again.

And this could continue eternally. 

I am absolutely sure this wasn't intended and should be fixed, this ruins whole idea of RVR and all fun from the game.

Just look at this
https://youtu.be/kf1ljx1fZjw
We have lord tagged but damage wasn't enough to reset timer.
Then 1 WH pops near cannon, 1-2 hits, cannon at 50% HP and timer resets.
This guy already resetted our timer like 7+ times in a row...

**Comment by Rebiff** [comment]
https://youtu.be/csn_o5YXe88

**Comment by Rebiff** [comment]
https://youtu.be/3W6eiZJCJzg another example

**Comment by lilimx** [comment]
Hey,

that's actually no bug. If there are still siege weapons, you have to defend them aswell.
You should write a propsal on the forum here: https://www.returnofreckoning.com/forum/viewforum.php?f=15

**Comment by aaearon** [comment]
To tie the two together: a suggested tweak to this mechanic was posted to https://www.returnofreckoning.com/forum/viewtopic.php?f=15&t=47133
