### ISSUE TITLE
T2 Empire epic quest "Greater of Two Evils" missing final step or reward?

### ISSUE THREAD

**Issue by Grock-r** [WarEmu/WarBugs#19502]
**Expected behavior:**
T2 Epic quests supposed to reward a 17 ilvl blue chestpiece during quest progress, and then unique high ilvl purple-quality piece with a proc at the final conclusion, examples:

<details> 
<summary>Elf quest "Echoes from the Past":</summary>

![blue chest elf](https://puu.sh/Iga7L/5df14e6145.jpg)
![purple piece elf](https://puu.sh/Iga7P/a11294ce70.jpg)

</details>

<details> 
<summary>Dwarf quest "Chasing Oathgold"</summary>

![blue chest dwarf](https://puu.sh/Iga7z/1725c067a7.jpg)
![purple piece dwarf](https://puu.sh/Iga7I/00cd99652a.jpg)

</details>

**And actual behavior:**
The Empire questchain only rewards the blue chestpiece, and does so on the last step, missing the big epic reward:
<details> 
<summary>Dwarf quest "Chasing Oathgold"</summary>

![blue chest empire](https://puu.sh/Iga7W/a2fadb66ba.jpg)

</details>

In the turn-in text of the last step(16th) the NPC says that you have to go to High Pass now(didn't take the screenshot), but there's no followup quest:
<details>  
<summary>No followup: </summary>

![no followup](https://puu.sh/IeEjD/a9509be278.jpg)

</details> 

I believe this is a mistake with either misplaced quest eward or missing final step.

**Comment by Lheana** [comment]
This is not an issue, just the rewards of some Epic Quests have been changed, but not all. This is more a suggestion than a bug as these rewards are the ones of official.

**Comment by Grock-r** [comment]
> This is not an issue, just the rewards of some Epic Quests have been changed, but not all. This is more a suggestion than a bug as these rewards are the ones of official.

I see. But it still looks pretty weird and inconsistent when two epic quests have proper rewards, while a third one gives what other two give as meager progress bonus. Why'd you do Empire questline, when you can do any of the other two and get the same chestpiece and a powerful purple reward at the same time?

Even if this was the case on live, it is still probably a bug, misplaced reward or missing quest stage, but nobody bothered to fix it in years because its just low lvl pve in a pvp game.

In any case i hope you do something about it eventually. Should i post it somewhere on forums?
