### ISSUE TITLE
Volgen Warcamp NPC asleep

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#1950]
The Volgen Warcamp in Talabecland destro side is a killfest for order because the npc don't react to Order. There are no L55 Champs there. And when you die you respawn in the same camp just to be killed by order again. Got prn scrn if you want them.

**Comment by Meralors** [comment]
I added several guards npc to stop the kill-spawn. WIll be pulled live with next patch.

**Comment by wiscel** [comment]
Thanks :-)
