### ISSUE TITLE
Thoreksson's War...axe?

### ISSUE THREAD

**Issue by Rheinharte** [WarEmu/WarBugs#19511]
**Expected behavior and actual behavior:**
Completed quest to get rewarded Thoreksson's Warhammer, appearance looks amazing so understandably wanted to apply skin to fortress hammer. However apparently it is treated as an axe rather than a hammer.

**Steps to reproduce the problem:**
Go to appearance of character and attempt to apply skin to fortress hammer but does not change as it is not the same type

**Testing Screenshots/Videos/Evidences (always needed):**

![Grombrindwalin_000](https://user-images.githubusercontent.com/77078943/136673425-9a046e2c-44f4-48aa-b6d1-5cb04a150c5d.jpg)

**Comment by Rheinharte** [comment]
Thanks :)

**Comment by lilimx** [comment]
Fixed with Patch 15/10/2021
