### ISSUE TITLE
The Fall of Konrad Schultz

### ISSUE THREAD

**Issue by Uchoo** [WarEmu/WarBugs#1951]
This quest, located on the bridge between Empire Chapter 12 and 13, is currently bugged. It requires you to kill Konrad upon taking the quest, but the NPC does not turn hostile.

Also, there are 2 copies of Konrad, one in the correct position in the center of the bridge, and one at the end of the bridge (I know many other NPC's are currently duplicated as well).

**Comment by ozarmidrashim** [comment]
This quest shouldn't exist. Konrad Schultz, in the original game, was a WH who appeared in every tier, offering quests along a storyline. His appearance (possessed / shaking) should be used in Tier 4, at the end, when he is killed - otherwise he appears as a normal WH in Sentinel armor.

**Comment by Uchoo** [comment]
Touche.

**Comment by Evildoor** [comment]
#910
