### ISSUE TITLE
Quest A skull Like No Other

### ISSUE THREAD

**Issue by Nagval3** [WarEmu/WarBugs#19524]
this Q maybe cant work bug my Q item backpack, and any npc cant be consumed
![Uldradh_000](https://user-images.githubusercontent.com/32022734/137579272-146bb38d-0ec2-4d6a-af7b-4c21bce6a3ee.jpg)

**Comment by lilimx** [comment]
> 
> 
> Was there a solution to this problem?

Hey,

no, the issue still persits. We just closed and pinned your ticket to an earlier ticket with the same issue that was posted.

**Comment by Kabucoror** [comment]
![skull](https://user-images.githubusercontent.com/45296624/139587577-3031dab6-2d82-4be4-82c9-ea94c9a177ec.PNG)
It works fine for me. Please check if the skull is one of your items with no icon in your quest backpack.

**Comment by DDebosh** [comment]
![image](https://user-images.githubusercontent.com/93408106/139594212-ff3a4bb8-426c-47c7-8808-f6a9be6ae324.png)
I took the quest, but I can't take the skull to complete the task, can you give me a skull?

**Comment by Lheana** [comment]
The skull is in your quest inventory, it's given when you accept the quest.
![Anaehll_244](https://user-images.githubusercontent.com/11537611/139596907-6e9f4e3d-f0d4-418a-94b4-f8edadf55e6f.jpg)

**Comment by DDebosh** [comment]
I have already gone through this quest many times in a new way, but the skull, which all my guildmates raised without difficulty, is simply not active for me, I cannot take it! I have already thrown off 2 screenshots of where the quest was taken from me and I am standing trying to pick up this quest item, I don't have it in my bag, I've already watched it even with disabled add-ons.

**Comment by Lheana** [comment]
I have done a small change, test it again after next patch.

**Comment by DDebosh** [comment]
ok

**Comment by DDebosh** [comment]
![image](https://user-images.githubusercontent.com/93408106/140380140-debfa16c-abc0-4ed0-8a17-bd2c24c8b81b.png)
thank you

**Comment by Lheana** [comment]
Then I close this ticket as it's fixed :)
