### ISSUE TITLE
Falls of Renewal PQ 2nd stage 

### ISSUE THREAD

**Issue by NSKaneda** [WarEmu/WarBugs#19525]
**Expected behavior and actual behavior:**
2nd stage of Falls of Renewal PQ should count 10 tainted stones for completion of the stage. Currently it counts obelisks but PQ can still be completed by clicking on stones.

**Steps to reproduce the problem:**
Grind to 2nd stage. 

**Testing Screenshots/Videos/Evidences (always needed):**

![Vidarr_002](https://user-images.githubusercontent.com/22037960/137604194-670395eb-87d1-48dd-8050-625d794b4e4c.jpg)

**Comment by Lheana** [comment]
Everything is explained in the description of the stage.
![Lheana_240](https://user-images.githubusercontent.com/11537611/137627921-477d9894-4459-4518-b7ff-e92cd14437db.jpg)
