### ISSUE TITLE
T3 Greenskin influence rewards not unlocking

### ISSUE THREAD

**Issue by Zabbykins** [WarEmu/WarBugs#1953]
My T3 Greenskin influence aren't unlocking, they just sit at "Need more influence" and show no picture for the items, but show that I have reached them in my Tome of Knowledge War Story.
![untitled](https://cloud.githubusercontent.com/assets/16008217/11384689/86769abc-92d7-11e5-854e-b453c16831c8.png)

**Comment by Pitre67** [comment]
Go to Badlands, Rally Master works there :-)

**Comment by Calarian** [comment]
If that doesnt work then you need to ride close enough to bother Destro War camps in Badlands and BFP i had same issue.

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
