### ISSUE TITLE
Hidden heal debuff/debolster lingering after death

### ISSUE THREAD

**Issue by tlusto** [WarEmu/WarBugs#19539]
**Expected behavior and actual behavior:**
Sometimes after dying my heals starts to be about 30% less effective, like some heal debuf would linger on the char even through dying. The only thing i found that resets it is relogging. Neither Reequiping nor resetting tactics fixes this issue. You can see the actual numbers on screenshots, one taken with this "debuf" on, the other one after just relogging. It works similarly on all other healing skills. As you can see from screenshots stat are the same, tactics and relevant buffs/debuffs are the same - at the time of screenshots being taken there was a proc of khaines bounty and imperative spirit, but those dont affect the outgoing heals. I was standing in IC, so no bolster/debolster should apply. I tested with other players that they see the same numbers as i do as incoming heals when i healed them.

**Steps to reproduce the problem:**
Unfortunately i dont know the exact steps needed to reproduce the issue, and i have no means how to test it thoroughly, would need probably some testing with gm killing my char with certain debufs on me at the time of death i suppose.

**Testing Screenshots/Videos/Evidences (always needed):**
With bug:
![Nalrothi_008](https://user-images.githubusercontent.com/93007555/138506517-c61d1273-c07a-480f-935d-15dc73b8a0a2.jpg)
After just relog:
![Nalrothi_009](https://user-images.githubusercontent.com/93007555/138506521-a27804d5-7c40-439b-b815-1de3f3da929c.jpg)

**Comment by tlusto** [comment]
Hi,
so it seems like it affects only willpower.

![Nalrothi_020](https://user-images.githubusercontent.com/93007555/139603899-ce4b37e6-c1b7-4b7a-be7a-188758a9d3e3.jpg)
er

**Comment by lilimx** [comment]
Hey,

okay....I've already added to the related post. 
I will close it, but you can add further information here ot to the main ticket #18534
