### ISSUE TITLE
Stat potion bug

### ISSUE THREAD

**Issue by zolio1236** [WarEmu/WarBugs#19549]
How is it possible to have a stat potion ( lasting potion of strenght) & ( Liniment of the Inevitable tempest) at the same time 
![Gringots_001](https://user-images.githubusercontent.com/37667147/138967831-ba9857ad-9866-4149-ba3a-7d51e6bb89c1.jpg)
?
![Gringots_000](https://user-images.githubusercontent.com/37667147/138967838-425c2008-93bd-44cd-b138-7c5e9ca9c2a3.jpg)

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persits, please open a new ticket with proper evidences.
