### ISSUE TITLE
lag caused by bolster buff

### ISSUE THREAD

**Issue by magicthighs** [WarEmu/WarBugs#1954]
Whenever I'm moving around in a warcamp and I'm getting bolstered or bolster is removed, the game  freezes for a few seconds. Same thing happens when I exit a warcamp and bolster is applied.
I think this happens too with AAO changes, but I'm not 100% sure, because there was general lag from large groups fighting when I noticed that.

**Comment by magicthighs** [comment]
I forgot to add that everyone in my guild had the same issue, and other players, both order and destro, said it affected them too.

**Comment by taccr** [comment]
Having the same issue. I first thought its related to my addons but I temporarely removed all of them and also used a fresh install.

Every time bolster gets applied or removed I'm having a long client freeze.
For some reason it freezes longer the more I'm away from max level. At level 30 I only have mini freezes.

I see other people also complaining about this especially noticeable in the t3 empire tunnel to manor (you lose your bolster inside the tunnel) or t3 dark elf wc.

**Comment by Evildoor** [comment]
Changelog 6th March 2016
Azarael:
- Fixed an issue causing lag when Bolster was applied.
