### ISSUE TITLE
Pvp trophy items are all bugged Altdorf Library

### ISSUE THREAD

**Issue by Meliannia** [WarEmu/WarBugs#19542]
NPC Trophy vendor Delwin Lehrer in Altdorf Library won't sell any of the PvP Pip trophies it just keep saying u need the TOK unlock kill 1000 DoKs, or Kill 1000 magus etc, even when you have all these tok unlocks already, game isn't recognising you have the achieves

I have seen destroy with these trophies so it's just an Order issue with this vendor

**Comment by lilimx** [comment]
Hey,

so I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persits, please open a new ticket with proper evidences.
