### ISSUE TITLE
Revelation Quest: No location for black powder.

### ISSUE THREAD

**Issue by VonEpic** [WarEmu/WarBugs#19554]
During Chapter 14 Chaos Quest "Revelation,' in last stage where you must use black powder on an elven tower wall to frame the dwarves, no such interaction seems to exist within the stated area on the map.

**Comment by Lheana** [comment]
It works fine.
![Anaehll_243](https://user-images.githubusercontent.com/11537611/139584764-1e2caa52-9177-4ffb-8b1a-c411b8554503.jpg)
