### ISSUE TITLE
After 45+ gold purp blue bags in rvr and still no Genesis Cloak if no bug still to random to not get it 

### ISSUE THREAD

**Issue by Lunkan1978** [WarEmu/WarBugs#19558]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by xpander69** [comment]
Can you please fill the bugreport normally. This is not a place to request droprate changes either.
Closing it for now. If you want to open a bugreport then fill it correctly with  steps filled on the report.
