### ISSUE TITLE
Emotes to npc's have poor grammar and refers to them as objects.

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#19559]
**Expected behavior and actual behavior:**
Emotes to NPC's have an extra "the" in the statement.  I don't remember this issue always happening.
NPC's are persons and should not be referred to as objects.

Edit - After a little more looking, it seems this only happens to RvR NPC's.  I guess with some newer NPC's which have simple names, such as 'Bodyguard', 'Swordsman', 'Pyromancer' the grammar is fine. However, the extra 'the' is still not needed and works fine without it.  Eg.  You cheer at Pyromancer as opposed to You cheer at the Pyromancer.

But, with named NPC's there is clearly no need for the extra 'the'.

**Steps to reproduce the problem:**
Emote an NPC with something like /toast or /cheer

**Testing Screenshots/Videos/Evidences (always needed):*
![toast](https://user-images.githubusercontent.com/7898608/139787376-10df3ae4-aea6-4422-8ab5-345636cdf00e.jpg)
*

**Comment by MaxHayman** [comment]
Found cause
