### ISSUE TITLE
Unable to equip Talismans or use them.

### ISSUE THREAD

**Issue by Texalos** [WarEmu/WarBugs#19556]
I play warrior priest (grace 1h) and when i try to use Talismans i get the message "this item cannot be used yet" in my chatbox, when i try to drag the talisman to my item i get the message "that item doesnt go there" i have the required rank.

**Comment by Lheana** [comment]
Please post a screenshot of the talisman and the item you are trying to put it on.

**Comment by xpander69** [comment]
most likely you are using higher level talisman than your gear item or trying to use the same type of talisman on 2 talisman slot item. but yeah screenshot and item names would be needed information

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persits, please open a new ticket with proper evidences.
