### ISSUE TITLE
Slash and Burn final hero and champion not attackable

### ISSUE THREAD

**Issue by LordYabol** [WarEmu/WarBugs#19557]
Neither pointed melee/autoattack nor aoe works. Cannot damage them, taunts don't aggro. Progressed PQ normally in a party of 2. Healer cannot dps either.  

SS:
![Yabol_007](https://user-images.githubusercontent.com/93490153/139597880-a880d8a5-1c97-4fe9-a5f2-31db8e7e3361.jpg)
![Yabol_000](https://user-images.githubusercontent.com/93490153/139597886-5aee6521-7fb5-436c-8d89-220e97d99d04.jpg)
>

**Comment by lilimx** [comment]
fixed with patch 04/11/2021
