### ISSUE TITLE
Typo in talisman fragment name

### ISSUE THREAD

**Issue by meatcomputer** [WarEmu/WarBugs#19550]
![image](https://user-images.githubusercontent.com/2209906/139165814-07df57d0-89b7-4ca7-bb8f-7837a201c192.png)

**Expected behavior and actual behavior:**

Chaotic Shielding Brand?

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by lilimx** [comment]
fixed with patch 04/11/2021
