### ISSUE TITLE
Isen Grudgeborn (Gnol Baraz keep lord) is invincible

### ISSUE THREAD

**Issue by Ryanfawkez** [WarEmu/WarBugs#1956]
As of the latest hotfix, the Dwarf keep lord in Black Fire Pass has become invincible to Destruction, making them unable to take the keep. The keep lord's natural HP regen seems to be overly excessive, as with the release of T3 on the first day.

**Comment by Fortwunty** [comment]
All keep lords are invulnerable.

**Comment by ozarmidrashim** [comment]
Fixed (DB regression)
