### ISSUE TITLE
[Dungeons] Bolster not applied anymore

### ISSUE THREAD

**Issue by CrimsonFenris** [WarEmu/WarBugs#19566]
Last month we started a Gunbad run with my group, and 2 rerolls : one 35 WL and one 39 IB.

Previously we used to be bolstered to 40 into Gunbad (likewise into Crypts and Tunnels), but looks like it's not the case anymore, resulting in unability to complete anymore...

I wondered if that was intended or not, given the fact you can take Gunbad quests starting from level 35 or 35, if I remember correctly ?

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. There is already a ticket about that issue, so I will add your report to it.

**Comment by lilimx** [comment]
dublicate // related to #16451
