### ISSUE TITLE
One and future Git - don't give reward on last step

### ISSUE THREAD

**Issue by MannyKarlavera** [WarEmu/WarBugs#19564]
When returning the quest on the last step to Aekold in K8P it's just sign of quest as completed without beeing able to pick a reward - see screenie below. NPC just offers a new quest.

**Expected behavior and actual behavior:**
Quest reward.

**Steps to reproduce the problem:**
N/A

**Testing Screenshots/Videos/Evidences (always needed):**

![Khaoskarl_007](https://user-images.githubusercontent.com/93761347/140475241-58f6c19a-9280-4ccb-b3a9-ed67c547294c.jpg)

**Comment by MannyKarlavera** [comment]
And the quests items (the mushrooms) are still in my backpack - now moved to the quest folder tho and no longer in my currency folder
![Khaoskarl_009](https://user-images.githubusercontent.com/93761347/140475827-54938cd8-a797-47a5-81d1-3bc65ea93b10.jpg)
.

**Comment by MannyKarlavera** [comment]
hmmm, super weird... when leaving the room i noticed on my map the there was new quest point - nothing i TOK tho, and when i talked to next NPC i could turn in the quest and get the reward...  so all ended well and might just have been screwed up for me - had issues on previous steps too, but that was sorted in last patch.
![Khaoskarl_011](https://user-images.githubusercontent.com/93761347/140477128-25f004d4-a3d6-47d0-bb46-9b73fb489521.jpg)

![Khaoskarl_012](https://user-images.githubusercontent.com/93761347/140477184-fbc1d336-832a-4175-8f5c-071b358f783b.jpg)
![Khaoskarl_014](https://user-images.githubusercontent.com/93761347/140477215-3ef1331c-0ab7-4e98-80e9-6ff823cc2d87.jpg)

**Comment by MannyKarlavera** [comment]
Feel free to close the issue if this was just for me :) 
Kind regards!

**Comment by xpander69** [comment]
probably the issue with the currency bag situation. will keep it open for now. I am planning on doing the  full questchains there also, so i will check if i run into similar issue then.

**Comment by Lheana** [comment]
I tested the whole quest line, found no issue so I close the ticket.
Btw for the last step, you have to talk to Aekold Helbrass to complete the objective, but he is not the quest finisher; this is Wurrzag.
