### ISSUE TITLE
Bugged objective for "Da Stiks Da Fing" quest

### ISSUE THREAD

**Issue by TussockyThree68** [WarEmu/WarBugs#19569]
**Expected behavior and actual behavior:**
During the Greenskin quest "Da Stiks Da Fing" to complete the objective in Ch. 3 titled "Bash Boris Da Basher" you are supposed to be able to open your inventory and use the previously obtained quest item called "Bashin Stik" (by right-clicking) while targeting Boris Da Basher to advance the quest. Whenever I try this I see an error in the chat box that says something along the lines of "You can't use this item yet" 

**Steps to reproduce the problem:**
1.) Pick up "Da Stiks Da Fing" quest in Ch. 2 of the Greenskin campaign. 
2.) Follow it all the way to Ch. 3 until you reach the objective "Bash Boris Da Basher"
3.) Target Boris Da Basher in Krom
4.) Attempt to complete the objective by right clicking "Bashin Stik" in the key-items section of the backpack.

**Testing Screenshots/Videos/Evidences (always needed):**

https://user-images.githubusercontent.com/93793387/140569542-36c084f6-7341-4306-a410-cd2f389134e7.mp4

**Comment by Lheana** [comment]
You need to stand closer to be able to bash Boris.
![Anaehll_253](https://user-images.githubusercontent.com/11537611/141687601-6364f6ca-b942-4c62-b4cf-6e8a79a90000.jpg)

**Comment by TussockyThree68** [comment]
Oh. ooops
 Thank you!
