### ISSUE TITLE
Once'N'Future Git - Quest vanish / vendor glitch?

### ISSUE THREAD

**Issue by Acknslash** [WarEmu/WarBugs#19560]
Once'N'Future git; vanishing quest line/vendor.

I've had this issue twice with KV chapter 22 turn in points.

Previous step was to turn it in with the dude below, for slime stone quest. After a week of looking around i found the quest was avaliable again, but from a vendorin TM (the same one who issues live event t4 search quest for TM.

I completed this step, which was to turn is at Gazbag. I completed this step, he issues a new quest for something involving a barrel and mushroom, but immediately the quest vanished.

I have checked KV 21 and 22, as well as TM and KV WC vendors but no sign of a re-issue under a new vendor and no quest line in my quest lines. Vendor photo's below as showing after taking the quests and turning in.

I've been unable to locate this on the wiki or on forums to find out if something is erroring or if there's a step i'm issing here, but the quest vendors are deeply unclear having vanished twice. 

![Acknslash_006](https://user-images.githubusercontent.com/93328787/139941458-c68ce8bf-12aa-4fe2-a092-08a7e6115374.jpg)

![Acknslash_005](https://user-images.githubusercontent.com/93328787/139941290-2b7e9fc8-2548-4c72-b25f-7fddad858e09.jpg)

**Comment by Lheana** [comment]
What is your level?

**Comment by Lheana** [comment]
I guess your issue is related to the level requirement, it increases as you advance on the quest line. So maybe you did not have the level yet to progress further.

**Comment by Acknslash** [comment]
> 
> 
> I guess your issue is related to the level requirement, it increases as you advance on the quest line. So maybe you did not have the level yet to progress further.

the issue seems to have been fixed following the drop of the last patch with the changes to Chapter 22. I was level 39 at the time

**Comment by Lheana** [comment]
Nothing has been changed related to this quest with the last patch.
You must be able to finish this quest line.

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persits, please open a new ticket with proper evidences.
