### ISSUE TITLE
Shield of Faith

### ISSUE THREAD

**Issue by molyporph** [WarEmu/WarBugs#19561]
On warrior priest, using the tactic "Shield of Faith" seems to be bugged. If u have the tactic in your tactic slots and activate warrior priest prayer the +10% to disrupt is lost. Only way to make it work seems to be to have another tactic slot set without shield of faith tactic, activate prayer and then to switch to the tactic set which has shield of faith.

https://www.youtube.com/watch?v=5D6G0Z-Vaq0

//Edited to make the YT-link available

**Comment by lilimx** [comment]
Hey,

the tactic is working. The paperdoll stats in your character sheet doesn't work accuratly.
If you're not sure if a tactic or an ability is working the right way, use the command .getstats (remove all other targets, you have to be the only target).

![grafik](https://user-images.githubusercontent.com/23266079/140033670-2b44f567-e9a5-4cfc-abf5-6506e6b0f40a.png)
