### ISSUE TITLE
[Gameplay] Target nearest enemy acting weird

### ISSUE THREAD

**Issue by CrimsonFenris** [WarEmu/WarBugs#19567]
**Expected behavior and actual behavior:**
Until now (playing for about 5 years), the "target nearest enemy" worked fine, correctly targeting the closest enemy from you.

Now since a week or two, using the same command is behaving in a very inaccurate, clunky and frustrating way : 
- Working remotely well when over 50-60ft away from any enemy
- When close to targets (melee range), the shortcut will most of the time select a random enemy around, never the closest one, if working at all. Most of the time, the shortcut will not do anything, even after deselecting targets.
- Pretty much everytime, if working the shortcut will select a random close target, and immediately switch to another one, without reason.

I'm aware that taunts and challenge from tanks have a similar effect (forcing you to target taunting tank), but after some time, it became very obvious there is a bug with targeting : I cannot believe a tank will taunt me everytime I attempt to target someone, especially while fighting on small groups only...

Pretty much all my guildies reported the same issue on their end, wich confort me about my own sanity here... :p 

It's new to me, and a very frustrating experience as a melee right now.

**Steps to reproduce the problem:**
Fight near enemy and use the "target nearest enemy" command. 
See that nearest enemy cannot be targeted this way (or very unreliably).

**Testing Screenshots/Videos/Evidences (always needed):**
I could not provide video sadly, has to be tested ingame to see what I mean.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. There is already a similar/related one, so I will add you ticket to this report.
