### ISSUE TITLE
Magus r40 mounts displayed near vendor are wrong 

### ISSUE THREAD

**Issue by valadorn5ROR** [WarEmu/WarBugs#19574]
Hello, as the title describes I found out that magus r40 mounts that are displayed near vendor are wrong. For example check in my print screen that I gor the moonlit blue one and this is quite different with the one displayed in front of me. The same applies with the other two mounts. I've asked in official discord server and the Community Management guy told me to post it here and that it should be really easy to fix.

I believe this is a critical issue as they are not low costed just to try them and choose the one you like. So especially new players may found themselves with a mount they do not actually like.

![400px-The_Inevitable_Cityy](https://user-images.githubusercontent.com/93903420/140698321-e2e31795-55c0-43b6-9c46-be3bbcb4cd72.jpg)

![Faidroth_013](https://user-images.githubusercontent.com/93903420/140697970-8b2cf51b-3bfe-4c2c-b9ef-cd556428aeaf.jpg)
>

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. There is already a report about that issue so I will close and add your ticket to the former one.

**Comment by lilimx** [comment]
dublicate of #18833
