### ISSUE TITLE
Squig Herder Pet Bugged

### ISSUE THREAD

**Issue by Candeyy** [WarEmu/WarBugs#19579]
**Expected behavior and actual behavior:**

When summoning any of the Squig Herder pets, none appear and the message in screenshot appears, regardless of location. This is occurring on a lvl 40 squig herder.

Expected: : Summon pet, it appears regardless which one or squid herder location when summoning pet.

NOTE: On a level 25 squig herder, this behavior isn’t occurring. Could that particular character be bugged?

**Steps to reproduce the problem:**

See above.

**Testing Screenshots/Videos/Evidences (always needed):**

![51E33A72-3A34-4325-9700-5C186B01DF51](https://user-images.githubusercontent.com/88755420/140871001-b22145fe-a8f0-466c-85e1-fae19527b3a1.jpeg)

**Comment by lilimx** [comment]
Hey,

what tactics are slotted? Is this "All By Meself"?

**Comment by Candeyy** [comment]
Hey, 

**Tactics** slotted are as follows:

Expert Squirmisher
All By Meself
Pick On Yer Own Size
Shootin Quicker


**Actions**:

Plink
Yer Bleedin'
What Blocka?
Run 'n Shoot
Lots o' Arrers
Not So Fast!
Shrapnel Arrer
Stick Squigz
Choling Arrer
Behind Ya!
Flee!
Huntin Wulf

Gas Squig
Horned Squig
Summon Squig
Spiked Squig
Squig Frenzy
Big Claw
Bad Gas!
Run Away!
Drop That!
Talisman Making
Tastes Like Chicken
Not So Fast!


**Morales**:

Point Blank
Squig Goo
Shoot Through Ya
Hail of Doom






> Is this "All By Meself"?<

No, if you're asking if toon name.



Thx for looking into this.

**Comment by lilimx** [comment]
Hey,

If you have slotted "All Be Meself" you can't summon a Squig. It's the equivalence to WL "Loner" tactic.
You can't summon a pet, but you deal more dmg.
