### ISSUE TITLE
Wrong unlock in ToK for Bloodlord set

### ISSUE THREAD

**Issue by Amadon82** [WarEmu/WarBugs#19578]
Continuation of #19577 
When i have equipped the belt of the Bloodlord set, the unlock for the Bloodlord Shroud (back item) unlocked instead of the belt one.
![Amadonn_076](https://user-images.githubusercontent.com/19516183/140826680-7aa42705-6fcb-4648-b34c-ac1314694dbc.jpg)

**Comment by lilimx** [comment]
Fixed with Patch 23/06/2022
