### ISSUE TITLE
A Servant's Duel still broken

### ISSUE THREAD

**Issue by Ryanfawkez** [WarEmu/WarBugs#1958]
As of the latest hotfix, the quest 'A Servant's Duel' is still not contributing Archmage player kills towards quest completion. The Bright Wizard kill quest for the Stalker's shoulders does work now, and is obtainable.

**Comment by mursie** [comment]
Would love for this quest to work - really need gloves =)_

**Comment by Evildoor** [comment]
If something was fixed, and then bugged again, no need to create a new report, use the old one.
#1897.

**Comment by Ryanfawkez** [comment]
Yeah Evildoor, I commented on #1897 before but I wasn't sure if the comment would be read, sorry for making a new issue about it if you actually do check replies to old bugs :P

**Comment by Evildoor** [comment]
Everyone responsible for this bugtracker is automatically notified of all new reports/comments (including closed tickets) unless they manually turn this feature off. Therefore, in case of any problem/disagreement/clarification/etc old tickets should be used (if they exist, of course).
