### ISSUE TITLE
Steady Aim will not stay toggled on after zone change and after death

### ISSUE THREAD

**Issue by ohmtastic** [WarEmu/WarBugs#19580]
Steady Aim is a toggle on/off ability.

Currently it will stay toggled on unless you change zones (so using flight master, war report, entering scenarios etc.) and when you die.

This never used to be the case and is quite frankly annoying. Other abilities in other classes don't seem to have this issue.

**Comment by lilimx** [comment]
Hey,

are you using any addons?

**Comment by ohmtastic** [comment]
Just a few I'll grab a list.

AceLocale-3.0
AdvancedRenownTrainer

**Comment by ohmtastic** [comment]
I think this is from the recent change to SW, as it stayed on as did glass arrow between zone changes and deaths.

**Comment by lilimx** [comment]
Hey,

we are currently investigating about your two posted tickets.

**Comment by lilimx** [comment]
It cancels whenever traveling between different maps (e.g. from Avelorn to Chaos Wastes, but not between Avlorn and Spahery), or as soon as you die.

**Comment by lilimx** [comment]
Fixed with Patch 19/12/2021
