### ISSUE TITLE
[Altdorf quest] "Ogre Bodyguards"

### ISSUE THREAD

**Issue by Paleolog77** [WarEmu/WarBugs#19589]
This quest not correctly show at map. It show only one place at docks, & right Crub, but it's wrong, Crub stay at another place. Two another ogres not show at all. I mark them at screenshot.

![2021-11-13_15-25-34](https://user-images.githubusercontent.com/23325288/141643898-737d40e1-5df4-42e8-9736-9d75bd436068.png)

Next stay of this questline show not correctly too. Speak again with ogres, & not show again. Typing on one ogre, but area on map disappeared at another place.

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by lilimx** [comment]
fixed with patch 20/11/2021
