### ISSUE TITLE
[City bug] imbalanced instances being created

### ISSUE THREAD

**Issue by Paleolog77** [WarEmu/WarBugs#19588]
Today at city was bug, dessi have more numbered, than Order players, 24-28 & 24-36, so thay have eazy win. I think this bug is result of last patch, plz fix it, if you can, & royal crests, than dessi take as result of bug, of couse must takened back.
Bless you Sigmar
![2021-11-13_07-21-00](https://user-images.githubusercontent.com/23325288/141606240-3677e050-a3b1-44cd-8949-31a4d3dd688f.png)
.

**Comment by TilliRage** [comment]
I love how people giving order what should be done on bug reports.

**Comment by xpander69** [comment]
Im pretty sure its just because some people left the city or crashed out and new ones joined in, why the list shows like there was more on other side

**Comment by Paleolog77** [comment]
> Im pretty sure its just because some people left the city or crashed out and new ones joined in, why the list shows like there was more on other side
> 
> edit: i take it back, it could be a problem. this might also be related: #19591

You wrong. The same bug was again, now at Order side.
![2021-11-14_03-02-01](https://user-images.githubusercontent.com/23325288/141663085-1a03582d-bed6-4bb3-a622-3f6483da62b9.png)
