### ISSUE TITLE
Shadow Warrior BHA Missing

### ISSUE THREAD

**Issue by rdmfool** [WarEmu/WarBugs#19582]
**Expected behavior and actual behavior:**
Hi, I play a Shadow Warrior Lvl 12 and I had the ability Broadhead Arrow in my skill bar and in regular use. Today I logged into my Character and started a Scenario and noticed the skill missing from my Castbar and the Action tab in the Ability window.

**Steps to reproduce the problem:**
I went directly to the Career Master and looked for Broadhead Arrow and if i could relearn the skill, but the Career Master offered no solution. Even switching Masteries didnt help. 
After that i consulted the /advice Chat, which recommended relogging and closing/reopening the launcher. I tried but these steps didnt bring the ability back. Between reloggin I kept checking the Ability tab and the Career Master in Altdorf.

Because my efforts went without success I tried the Repair function of the launcher and it was loading files for approximatly 5 minutes. Relogging into my Char and checking the ability tab and my Castbar still didnt offer any relief.

Advice from the /advice proposed entering a PvP Zone to get buffed to a higher level, but suprise, alas there was no change, even after Repairing the launcher a second time.

The screenshot shows my Character and the ability tab open with the skirmisher Path, where the skill Broadhead Arrow should be. But just in case you missed it, its not there.

![Shadow Warrior lvl12](https://user-images.githubusercontent.com/94071926/141166013-2d822fd9-93fe-40bc-b529-10431cc31c2f.png)

Kind regards.

**Comment by lilimx** [comment]
Hey,

actually BHA is a lvl 16 skill....so I guess it's a bolster/debolster issue.
![grafik](https://user-images.githubusercontent.com/23266079/141305816-1f409079-7898-41e3-8094-427b1dfc6e3f.png)

**Comment by rdmfool** [comment]
> 
> 
> Hey,
> 
> actually BHA is a lvl 16 skill....so I guess it's a bolster/debolster issue. ![grafik](https://user-images.githubusercontent.com/23266079/141305816-1f409079-7898-41e3-8094-427b1dfc6e3f.png)

Ahh thanks! It actually makes sense now, but is so confusing.

I remade a SW and got BHA on lvl 2 and could use it and out of Scenarios. 

Thing is aswell, I dont see the ability at the Career Trainer. Its not in my tab nor at the trainer, its like the skill just vanished from my client.

Could try lvl to 16 and maybe the ability reappears.

Cheers and thanks for the answer!

**Comment by lilimx** [comment]
Hey,

would be nice if you can give a little feedback if you reach lvl 16 :D

**Comment by dalen** [comment]
This was fixed in last patch

**Comment by lilimx** [comment]
Fixed with Patch 20/11/2021
