### ISSUE TITLE
Cross Realm Ranked Self Targeting

### ISSUE THREAD

**Issue by Lindisfarne** [WarEmu/WarBugs#19585]
In Crossrealm SC as a healer, i was having trouble targeting myself with enemy unit frames and hotkeys. Was having difficulty casting Cleanse as well. I think it was because i couldnt cast it on myself with no target.

**Comment by Lindisfarne** [comment]
Im still stuck in this weird situation where i show as a enemy when i target myself in the RvR lake after the Ranked SC ended too.

**Comment by dalen** [comment]
This has been fixed in hotfix today
