### ISSUE TITLE
Repetitive quests at Caledor's WC: "Scions of Caledor" & "Solemn Defence of Caledor".

### ISSUE THREAD

**Issue by Paleolog77** [WarEmu/WarBugs#19590]
Both quests ask me to kill 25 players and both are on the same WC, and in the same zone, but there is no repeatable keep capture quest. Thus, I complete two quests at once, instead of the planned one, and get the advantage of farming experience and gold.
![2021-11-13_15-57-56](https://user-images.githubusercontent.com/23325288/141644863-02ef1971-a9d1-4c38-968e-5099e3af356d.png)
![2021-11-13_15-57-17](https://user-images.githubusercontent.com/23325288/141644870-9e95a2df-d7b7-4f67-b06c-e44d18740885.png)

**Comment by Kabucoror** [comment]
Scions of Caledor is disabled for now because it's part of a quest chain which can't be implmented by now.
The keep capture quest is active again.

**Comment by lilimx** [comment]
fixed with patch 20/11/2021
