### ISSUE TITLE
Potential bug regarding population imbalance in instances

### ISSUE THREAD

**Issue by Xennian** [WarEmu/WarBugs#19591]
Asked on discord to add it here. Lacks screens but might be related to the earlier city bug with population imbalance. 
The eternal citadel loaded us in 8v6 in destro favour. no one disconnected or left to refill with new players. it just started us as 8v6 and game finished as such. havent been able to confirm on other maps as this is the only one i know that is meant as 6v6 or less. very few pops on this map too..
a longshot idea of the issue: when you try to accept queue when you are dead it resets the timer and pop up screen. perhaps the game take that as a decline and allows someone else in aswell as allowing you to enter after you respawn and accept the queue pop up?

sorry for the lack of information and evidence. but yes, 14 players were active at once in that scenario.

**Comment by Acknslash** [comment]
Gonna add to this, SC's popping in t1 that are 8v11 in orders favour and no notification
![Thebadtouch_001](https://user-images.githubusercontent.com/93328787/141830296-0cf2ef07-a907-42f1-a90b-141eee482d6c.jpg)

**Comment by Xennian** [comment]
This picture of ekrund seems entirely irrelevant. just a case of destro players not accepting queue pop. which is different to the issue where the player limit has been exceeded.
