### ISSUE TITLE
Altdorf City War Quarters Wall Slide

### ISSUE THREAD

**Issue by TilliRage** [WarEmu/WarBugs#19594]
If a player walks on the edge of wall, player suppose to fall down but its not the case in Altdorf War Quarters.

Walk near edge of a wall and angle your mouse slightly towards the edge. Start walking and your character will fall but instead of going down you will be rocketed to otherside.

https://streamable.com/aif4s9

https://streamable.com/esas2d

**Comment by Lheana** [comment]
This can happen on every edge of wall/ground. I don't see it as an issue, and I am sure it can not be fixed, so I close the ticket.
