### ISSUE TITLE
Cannot make Dyes r now

### ISSUE THREAD

**Issue by zarrathos** [WarEmu/WarBugs#19596]
We cannot make dyes r now using Wooden Mortar and Pestle/Alum root extract the area is just greyed in, with all 3 items in. Any timeframe on fix?
![image](https://user-images.githubusercontent.com/57928588/141820398-dcebbc29-9733-4fcf-9a5b-9434f39fe8cf.png)
Ty guys

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. This issue is already known.
For more information, please read the added ticket.
Additional I will close this one and add it to the mentioned origin ticket.

**Comment by lilimx** [comment]
dublicate // related to #19526

**Comment by zarrathos** [comment]
Can you please fix the issue so we can make dyes. Ty very much.
