### ISSUE TITLE
Devastator Gear disappeared

### ISSUE THREAD

**Issue by Mizrim** [WarEmu/WarBugs#1959]
Bought Devastator shoulders for my Engi (chr name Steelnuts) yesterday afternoon and slotted a +18 Balistic tali, just logged in this morning and it has gone :((

No other items missing, and I know I didnt sell them as they were equipped when I logged off last night.

**Comment by Evildoor** [comment]
Item loss is a known bug which has no solution so far. Dev policy is "no refunds" for now, so the only thing you can do is hope that when server restarts items will return. If they don't - tough luck, but that's how it stands.
