### ISSUE TITLE
Squig herder: All By Meself tactic problem

### ISSUE THREAD

**Issue by Iamwithstupid** [WarEmu/WarBugs#19601]
When slotting All By Meself tactic on Squig herder you can not summon squigs. This tactic actually allowed summoning squigs before the Territorial aggression and All By Mesef merge.
There is a message that refers to removed tactic Territorial aggression(look chat in SS)
![Iamwithstupid_069](https://user-images.githubusercontent.com/36380568/142623447-95502677-27cf-4f21-b9e1-c5cb6eb6a61e.jpg)

**Comment by lilimx** [comment]
Hey,

That's not a bug. If you have slotted "All Be Meself" you can't summon a Squig. It's the equivalence to WL "Loner" tactic.
You can't summon a pet, but you deal more dmg.
