### ISSUE TITLE
Marauder - Hulking brute tactic not giving initiative buff

### ISSUE THREAD

**Issue by VladimirLem** [WarEmu/WarBugs#19600]
Tooltip shows toughness and initiative being buffed by 148 (as shown on the right in the screenshot) - when slotted, it only buffs toughness - initiative remains the same.

The other two tactics (similar first tactics from other trees) - work just fine.

I have included two screenshots - one while in Monstro stance and one while in Brut stance

![Corvinous_000](https://user-images.githubusercontent.com/94664426/142561919-8c1ca72b-d99f-459a-afe3-3c7011484ce2.jpg)
![Corvinous_001](https://user-images.githubusercontent.com/94664426/142561922-a1e970ee-45c0-4fa1-89fe-9a25b928ef78.jpg)
e.

**Comment by xpander69** [comment]
check with .getstats

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persits, please open a new ticket with proper evidences.
