### ISSUE TITLE
Quest bugged: Dwarf T1, "Boom Rush"

### ISSUE THREAD

**Issue by Rubendorff** [WarEmu/WarBugs#19608]
The dwarven T1 quest "Boom Rush" does not grant you the necessary quest item to complete the objective. As states by the quest text "While standing next to the capture cannon, use the blasting powder in your inventory to place it." As can be seen on the screenshot, no blasting powder is provided, can be located in the camp of the questgiver, or found at the designated quest location. Attempted to abandon / re-acquire the quest several times, no blasting powder is received.
![Quest Bug Boom Rush](https://user-images.githubusercontent.com/94758406/142736653-f3c2f66c-e5e6-4965-bd21-35e88c09c564.png)

**Comment by Kaelang** [comment]
Added Blasting Powder to the quest - it now goes to your Quest Inventory and you can complete it now.

**Comment by lilimx** [comment]
Fixed with Patch 29/06/2022
