### ISSUE TITLE
no player ranks shown in enemy and summary scoreboards (sc) since last patch

### ISSUE THREAD

**Issue by HokoBugTracker** [WarEmu/WarBugs#19603]
the ranks are shown as 0 in enemy when not in sight of your groupmembers, then show but suddenly return back to 0. summary windows like sc scoreboard are showing 0 aswell. this happened right after the patch on 11/20.
![Bro_001](https://user-images.githubusercontent.com/60039912/142723811-640b85ea-39f1-4d50-a0e1-dcde04408b3e.jpg)
![Bro_000 (2)](https://user-images.githubusercontent.com/60039912/142723833-ae15d5aa-21b0-417e-ae02-d0648e5909a8.jpg)

**Comment by xpander69** [comment]
Just adding my report also. Enemy also doesnt pick ranks unless they are close to you and you target those players, then ranks will be shown.
![ss_02122021_21 40 53](https://user-images.githubusercontent.com/1345116/144622590-053f3b8b-63e1-4d8e-b8fd-0537b5bea603.png)

**Comment by xpander69** [comment]
should be fixed with patch 04/12/2021
