### ISSUE TITLE
Magus Tactic: Swift Flames

### ISSUE THREAD

**Issue by Rildetarma** [WarEmu/WarBugs#19605]
The Magus tactic: Swift Flames when slotted is to reduce the cooldown of Surging Violet Fire's cooldown by 7 seconds.  It has stopped working. Surging Violet Fire's cooldown stays at 10 seconds

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
maybe related to #19604

**Comment by xpander69** [comment]
Should be fixed. Can anyone else confirm?

**Comment by Rildetarma** [comment]
I can confirm this has been fixed.  It is now functioning normally.  Thank you for your work

**Comment by Rildetarma** [comment]
Agonizing Torrent however, does not appear to be castable on the move any longer.
