### ISSUE TITLE
Neverending agony tactic not working for Pit of Shades 

### ISSUE THREAD

**Issue by zarrathos** [WarEmu/WarBugs#19606]
<!Neverending agony tactic not working for Pit of Shades 

--
Issues should be unique. Check if someone else reported
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.
-->Neverending agony tactic not working for Pit of Shades 

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/57928588/142733067-e45cd68e-83b2-4360-8090-84fc923ba67e.png)

**Comment by xpander69** [comment]
Should be fixed. Can anyone else confirm?

**Comment by zarrathos** [comment]
Confirmed bud ty. Can I get one of those cool Griffon Mounts?
________________________________

**Comment by lilimx** [comment]
Fixed with hotfix 21.11.2021
