### ISSUE TITLE
[Howling Gorge] Spot on the map where you can get stuck

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#19628]
**Expected behavior and actual behavior:**

If you fall off the bridge/high ground near the objective by destruction's spawn, you can land on a torch/rock next to each other. If this happens then you become stuck and cannot move out of them. If possible the torch needs to be moved or a bigger box put around the two items so you can't land inside them.

**Testing Screenshots/Videos/Evidences (always needed):**

I've moved the UI elements in this screenshot to make it more compact. Map shows where it happened, middle shows the torch/rock combo, bottom shows the stuck messages.

![image](https://user-images.githubusercontent.com/60266177/142782282-d65ef81b-54c7-4163-a135-10f9ed48ee69.png)

**Comment by Lheana** [comment]
We can not do anything about that, if you jump on the torch you can get stuck.
