### ISSUE TITLE
Thunder Mountain - cant get in/out on outer wall or inner

### ISSUE THREAD

**Issue by Evilchosen** [WarEmu/WarBugs#19638]
Hi can get out from the keep and in
![image](https://user-images.githubusercontent.com/82473452/144301207-157bc8fe-c858-46bd-b684-1920264999ba.png)out
![image](https://user-images.githubusercontent.com/82473452/144301374-f627bbd4-a580-4526-88e4-5079ddfabb29.png) in 

is TM

**Comment by lilimx** [comment]
Hey,

we've tested your issue twice but can't find any bugs. We can enter and exit the keep doors without any issues.
So Im going to close this ticket now.

If you are still the opinion the bugs persists, please bring detailed information to reproduce it.
