### ISSUE TITLE
scoreboard bug shows wrong number

### ISSUE THREAD

**Issue by bloodmasked** [WarEmu/WarBugs#19633]
![image](https://user-images.githubusercontent.com/6406832/143662776-0b5c73dc-d1d7-4000-b050-679407a18db5.png)

it says 2 kills for Darthmaur but really he should have 23 or 24

**Comment by xpander69** [comment]
not much info on this. Are you sure Darthmaur didn't join later or maybe was dead during the time the kills were made?
Needs more info: was he also grouped with others etc

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. This issue has been already reported, so I will close and add it to the previous one.

**Comment by lilimx** [comment]
dublicate // related to #19603
