### ISSUE TITLE
Can't login 3 out of 5 of my chars

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#1963]
Hi,

I have 5 destro characters. First I always had troubles logging in to my Sorc Xheevah, it took about 6 times or more before I could log her. Now it's totally random to what character I can log. 
Yesterday I could only play my Blackguard, today I can only play my sorc and squigherder.
Any solution what I can do, and do other platers have this problem as well? Please help.

These are my characters:

Xheevah - Sorc
Mehlindy- Witchelf
Donavicenta - Blackguard
Doktator - DoK
Nasthie - Squigherder

**Comment by Pitre67** [comment]
Some say "/stuck" two times while loading, works.

**Comment by wiscel** [comment]
I tried that trick already, I see that my chars are moved to Norsca, but still cant log them.

**Comment by Evildoor** [comment]
IIRC, you posted on forum that you get an error about data.myp being used, right?

**Comment by wiscel** [comment]
Yes, but I don't get the error everytime when it happens.

**Comment by Evildoor** [comment]
1) You unchecked "Read only", right? Stupid question, but still...
2) Are you playing the game from the torrent folder?

**Comment by wiscel** [comment]
1. no tick in Read Only
2. I got the game from the 10 direct downloadlinks at the RoR site

**Comment by Evildoor** [comment]
Well, then i was wrong and problem lies somewhere else. That message about file being used hints at some other problem using the file, but nothing comes to my mind apart from torrent (some people had this problem if they used it and played in the same folder) and you said that it's not the case...

**Comment by wiscel** [comment]
Ok, thanks for looking into it :-)

**Comment by kiefer79** [comment]
Same for me and others, have a look at http://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=8633. Some chars are able to login, some chars aren't. In my case "Kiefer" and "Bowerie" are thrown back to char selection screen, all the others work. Tried the /stuck thing, deleted all plugins, deactivated my antivirus, checked "read only" .... nothing works.

**Comment by kiefer79** [comment]
Error depends in too much open quests. See http://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=8633&p=95366#p95192 for a solution!

**Comment by wiscel** [comment]
Deleting my Quest log fixed it, thanks!
