### ISSUE TITLE
Marauder Feeding In Fear -tactic bugged

### ISSUE THREAD

**Issue by Jonee90** [WarEmu/WarBugs#19639]
**Expected behavior and actual behavior:**
Expected: Any time you critically hit an enemy, your chance to critically hit will be increased by 20% for 5 seconds, but you will also become 10% more susceptible to being critically hit.
Actual: Tactic stacks multiple times negative status that "you will become 10% more susceptible to being critically hit". Tactic NOT stacking positive effect "critically hit will be increased by 20%"

**Steps to reproduce the problem:**
Hit enemys

**Testing Screenshots/Videos/Evidences (always needed):**
Initiative normaly not in combat
![Mara ini normal not in combat](https://user-images.githubusercontent.com/75245801/144428042-dc0a71f8-4238-4e91-bff5-15eeb81dc40b.JPG)
Hitted enemy one time
![Mara ini hitted enemy one time](https://user-images.githubusercontent.com/75245801/144427940-8b5bedaf-7f86-42dc-ac7a-b63da62dd047.JPG)
Hitted enemy multiple times
![Mara ini hitted enemy multiple times](https://user-images.githubusercontent.com/75245801/144428151-79022ba3-5138-44c1-8e35-f73b7a8982c5.JPG)
Hitted enemy little bit more...
![Mara ini hitted enemy multiple times 2#](https://user-images.githubusercontent.com/75245801/144428196-bdbb6d39-a6ca-4d0f-ab75-c2494e721745.JPG)

**Comment by lilimx** [comment]
Hey,

thank you for your report, but paperdoll stats are no reliable source.
Please check again your numbers with .getstats

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persits, please open a new ticket with proper evidences.
