### ISSUE TITLE
The turret always looks in the direction of the engineer unless it has a target to attack

### ISSUE THREAD

**Issue by Lemonpie1** [WarEmu/WarBugs#1964]
Morale 4 abilities are like whack a mole, once your morale is full and you can use the m4 ability they pop up and go back to not usable I pretty much had to spam my F4 key and left mouse button to activate it.

Napalm grenade and the tactic throwing arm (25% extra range on grenadier abilities) don't work together the tooltip says 81ft range but when I throw it at max range nothing happens and the ability starts the 30 second cooldown. Similar to most of the ground target abilities if you throw them out of range they do nothing and a cooldown starts. 

The turret always looks in the direction of the engineer unless it has a target to attack its probably taking me as friendly target.

The Bugmans keg is missing the animation. It seems like the keg has a max ≈12 targets never noticed that on live it may or may not be true but i think it should heal everyone. 

Sometimes the turret tooltip doesnt show its abilities.

The lightning rod should have 5 ticks and the first one should start the moment it apears on the ground on this server it only has 3 ticks the first starts 3 sec after the inital plant and the last tick gets cut off. 
https://youtu.be/2iH48vYm-8g?t=1m21s as proof.

**Comment by Evildoor** [comment]
One report per problem, please.

Turret abilities disappearing is known, no need to report that.
