### ISSUE TITLE
Map. Zone and World map does not work

### ISSUE THREAD

**Issue by susaninf** [WarEmu/WarBugs#19649]
look at the map selection icons below

![image](https://user-images.githubusercontent.com/90922392/144625373-b701b3c3-9852-45ef-8d7f-87c9b012b751.png)
![image](https://user-images.githubusercontent.com/90922392/144625547-d3d13971-84cb-43fb-8b78-b92dddf94dff.png)

**Comment by lilimx** [comment]
Hey,

this is not a bug. Please check if your files are patched (maybe join the RoR discord and and ask in #technical-advice).

You can also check further:
- check if your game folder has all directory rights (move it to C: or to another place where it has all rights)
- check if you files have been unchecked read-only
- use the repair function (launcher > wheel > repair)
