### ISSUE TITLE
Hall of the Crimson Shroud PQ Ch14 Elf. 

### ISSUE THREAD

**Issue by DurinThornaxe** [WarEmu/WarBugs#19640]
In stage 3 of the PQ the stone is destructible now but Vedric von Heilbroner is impossible to attack or forced into attacking.

![Image 1](https://user-images.githubusercontent.com/86794706/144428880-034eb9b2-5e40-4cd2-af33-5bcc179c98dc.jpg)

Thank you all for your work! 
Best wishes, Durin

**Comment by lilimx** [comment]
Fixed with patch 09/12/2021
