### ISSUE TITLE
Against all Odds PQ Ch14 Elf

### ISSUE THREAD

**Issue by DurinThornaxe** [WarEmu/WarBugs#19643]
I've read through the other bug reports on this public quest and I didn't find my issue with it. In stage 2 there are no Rock Lobbers to destroy. And the ones that are part of the scenery are not clickable and not able to damage them.

![Image 2](https://user-images.githubusercontent.com/86794706/144430294-7eeccb01-3bcb-4ee0-8c51-f2f5e2ff4227.jpg)

Have a nice day!
Best wishes, 
Durinsson

**Comment by DurinThornaxe** [comment]
My bad, I was looking for them in the wrong spot. Please excuse my incompetence and the spam :D I'll be more careful in the future.

**Comment by lilimx** [comment]
Hey,

so I close this one again? If you are the opinion the issue still perists, please write a quick message here
