### ISSUE TITLE
[Bastion Stairs]  Galvoth Darkrage (Left wing miniboss) Thunder puddles are unreliable

### ISSUE THREAD

**Issue by CrimsonFenris** [WarEmu/WarBugs#19642]
**Expected behavior and actual behavior:**
In the left wing of Bastion Stairs, the miniboss Galvoth Darkrage (the ogre-dragon with the hound and thunder puddles) is dropping puddles a bit oddly : 
- Sometimes old puddles (that appears cleared on the ground) are reactivated when you step upon them
- Sometimes new puddles looks like dropped twice on same spot (you clearly see two thunder sprites), however it does not looks like double damage, maybe a visual bug.

**Steps to reproduce the problem:**
Try do do the boss with any normal team (2/2/2), see the puddles sometimes reactivate, or unreliably vanish.

Similar issue probably related to Master Quot'lik (C&T) spawns, see https://github.com/WarEmu/WarBugs/issues/19641

**Comment by lilimx** [comment]
Fixed with Patch 23/06/2022
