### ISSUE TITLE
WC Guards in Marshes of Madness broke

### ISSUE THREAD

**Issue by onemantankwall** [WarEmu/WarBugs#19646]
**Expected behavior and actual behavior:**
The orc guards are expected to kill the enemy player within range but the guards do nothing but stare at you.

**Steps to reproduce the problem:**

Run up the ramp towards the destruction warcamp as order.

**Testing Screenshots/Videos/Evidences (always needed):**

![unknown](https://user-images.githubusercontent.com/43802105/144548359-406a5680-1a48-40b1-a6dd-72a584b631ef.png)

**Comment by lilimx** [comment]
Fixed with patch 09/12/2021
