### ISSUE TITLE
Sweating the Stones PQ Ch14 Elf

### ISSUE THREAD

**Issue by DurinThornaxe** [WarEmu/WarBugs#19644]
Read the other bug reports on this PQ and none of them fit my issue. It is the same as the hard PQ on this chapter, the mobs in stage 3 are not attackable

![Image 2](https://user-images.githubusercontent.com/86794706/144434755-49b5afb1-8269-4fad-bb55-dba3b05698a4.jpg)

Thank you for your time!
Kind regards,
Durinsson
.

**Comment by lilimx** [comment]
Fixed with patch 09/12/2021
