### ISSUE TITLE
Can't see talismans on gear in bank

### ISSUE THREAD

**Issue by bloodmasked** [WarEmu/WarBugs#19652]
It shows up as if there is no talisman. If I take the item in my backpack, I can see the talisman. But if it goes back in bank I can't see the talisman when its in the bank.

**Comment by lilimx** [comment]
Hey,

please confirm your issue with screenshots.

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persits, please open a new ticket with proper evidences.
