### ISSUE TITLE
Sigmarite Handcannon apperance is wrong

### ISSUE THREAD

**Issue by Onlyendari** [WarEmu/WarBugs#19659]
T3 epic quest reward the Sigmarite Handcannon apperance was changed to a generic T1 pistol appearance a few patches ago, this should be a unique appearance of a 3 barrel handcannon 
![Lilizath_001](https://user-images.githubusercontent.com/95725837/145127585-16ed90f6-2006-4fa0-87b1-5ab55c17c9c8.jpg)

![b7](https://user-images.githubusercontent.com/95725837/145127927-c88a8def-094f-4661-83dd-9f6b2ad90dbc.png)

// Edit (Lilim): ticket was hidden behind some code

**Comment by Lheana** [comment]
What's the source of the information for the right appearance?

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persits, please open a new ticket with proper evidences.
