### ISSUE TITLE
Warrior Priest "Divine Light"

### ISSUE THREAD

**Issue by HokoBugTracker** [WarEmu/WarBugs#19658]
i've specced into "Divine Light" with my low (lvl 20) WP and it doesn't show up in the skill list/i can't use it. 
I've also respecced all my mastery points and specced it again, it still does not show up tho.

https://user-images.githubusercontent.com/60039912/145056523-5be12031-4499-4101-85c4-3c0d75287498.mp4

**Comment by lilimx** [comment]
Hey,

are you wearing a set that gives you an additional point into the trees?
Actually when you exact lvl 20, you aren't able to skill it, because you don't have not enough points.

**Comment by bloodmasked** [comment]
try typing /reload and check abilities again or relog?

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persits, please open a new ticket with proper evidences.
