### ISSUE TITLE
Moral Rank 2 and 3 not working properly

### ISSUE THREAD

**Issue by CptEdward** [WarEmu/WarBugs#19653]
**Expected behavior and actual behavior:**

I have been told that the Moral "Distracting Bellow" is now a Rank 3 moral spell. It should be able to be binded in a Rank 3 slot. 

On my side, this spell cannot be slot in a Rank 3 moral slot but only on a Rank 2 moral slot (or I get the message "This ability must be placed in the level 2 Moral slot"). And when I want to use it from the level 2 Moral slot, I always have a message indicating that the **target is not at ranged** (whatever distance it is from me, even melee). Such "distance message issue" also pop when I try to use "Raze" which is slot in the level 3 moral slot. 

I tried to clean the Moral bar and build it from scratch but nothing is working, and I do not think it is a toon issue as it has been created few days ago (i.e. after the relevant patch). 

**Testing Screenshots/Videos/Evidences (always needed):**
![01](https://user-images.githubusercontent.com/59454916/144760009-19e7aa85-5534-435b-ac62-41a5a88f32da.PNG)

![02](https://user-images.githubusercontent.com/59454916/144760013-578ad724-f65a-4bdc-8fc3-3d27d11f2356.PNG)

![03](https://user-images.githubusercontent.com/59454916/144760017-c30f3a9c-a5cc-4607-9480-04534b309304.PNG)

**Comment by lilimx** [comment]
Hey,

so distracting bellow won't switch into the M3 slot?

The patch was 4/11/2021 and after that change, they were still left in the wrong slots, raze M3 and distracting bellow M2.
Actually when you reslot it, it should work....otherwise if you try to cast it, it will fail.

**Comment by CptEdward** [comment]
Hi ! 

I cannot slot it on level 3 Moral slot. As shown in the two first screenshots, it indicates me that this skill requires a "Level 2 moral slot". The IB character has been created this week, so after the patch and thus I just got the moral skills from leveling. 

This issue exists on all my tanks (2 characters, 1 for each side). 

KR,

**Comment by lilimx** [comment]
Hey,

quick question, are all these characters already lvl40?
Additional, could you add a picture of your RoR folder like the example. I need to see the sizes of your files:
![grafik](https://user-images.githubusercontent.com/23266079/144764766-733b933d-57ca-4915-94fd-0cf8239ac54a.png)

**Comment by CptEdward** [comment]
Hi,

The IB is lv 29 but I have the problem since I got the Moral skill. The Black Orc is  lvl 40.

Your screenshot shows all values in KB, but mine in Ko. Hope this still helps. 

![04](https://user-images.githubusercontent.com/59454916/144765975-30fa7a23-18e2-44a5-9180-ffcf55a7dc32.PNG)

**Comment by bloodmasked** [comment]
Right click distracting bellow and raze in your abilities page. It should put bellow to m3 and raze to m2.

**Comment by CptEdward** [comment]
Hi Bloodmasked,

Not really. If I right click Distracting Bellow, it is put in a level 2 moral slot. I can't test with Raze as it is my only lv 3 moral skill yet (I'm lv 31). 

KR,

**Comment by lilimx** [comment]
> 

Hey,

I see, your install is a bit older....I would recommend a fresh install to check if it's not a failed patched data somewhere.
Here the guide: https://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=31241
If your issue still persist after that, i will label the ticket.

**Comment by lilimx** [comment]
> Hi,
> 
> The IB is lv 29 but I have the problem since I got the Moral skill. The Black Orc is lvl 40.
> 

And your BO doesn't suffer of this issue??

**Comment by CptEdward** [comment]
My BO suffer the same issue and solution proposed by Bloodmasked is not working either.

**Comment by lilimx** [comment]
hm,

actually I would recommend a fresh install. Please try that.
Here is the guide: https://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=31241
If the issue still persits, I will label the ticket

**Comment by CptEdward** [comment]
OK, I'll install the game from scratch and let you know if the issue is solved or persist. 

KR,

**Comment by CptEdward** [comment]
I'm sorry but I do not understand how to install the game through "torent" via the link above. 

I don't know how to have "ReturnOfReckoning-Oct2021.torrent" even after downloading Tixati v2.86.

Is there any other way to solve the initial problem ?

**Comment by CptEdward** [comment]
The issue has been resolved by uninstalling and reinstalling the game from scratch. On both the BO and the IB. 

Thanks for your reactivity. 

Kind regards,

**Comment by lilimx** [comment]
nice!
