### ISSUE TITLE
Can't equip a weapon, get message in chat pane 'cannot equip an item that is stacked'

### ISSUE THREAD

**Issue by N3Kify** [WarEmu/WarBugs#19651]
**Expected behavior and actual behavior:**
I've previously been able to equip a Sentry Axe of Devotion to my Ironbreaker, but when logging in today it was automatically unequipped and when I tried to equip it I get the error message in the chat pane 'cannot equip an item that is stacked. Please report this to bugtracker.' I bought another one but had the same message appear.

**Steps to reproduce the problem:**
I'm not sure what caused the problem, I was able to equip it before the update today. But logging off the game and closing the launcher and restarting it did not fix the issue.

**Testing Screenshots/Videos/Evidences (always needed):**

![Degnir_000](https://user-images.githubusercontent.com/95548670/144725057-01213e65-9287-4e2c-b774-acfc1615cc9e.jpg)

**Comment by Capibaru** [comment]
Same problem with my engie. I was able to equip it yesterday
![RORbug](https://user-images.githubusercontent.com/95568219/144742989-d1ee6b15-dece-44d0-89d6-4f415a6a34a6.jpg)

**Comment by bloodmasked** [comment]
If you have equip issues sometimes try unequipping your current weapons and then equip the new ones.

**Comment by N3Kify** [comment]
Hi Blood, when I logged in the weapon was already unequipped. I tried buying a new version of the same weapon but got the same error message so I just bought a weapon from a renown quartermaster for money and could equip that one. I tried to unequip it and re-equip the SC weapon but got the same message.

**Comment by lilimx** [comment]
Hey,

a fix is pending....it will be up soon

**Comment by lilimx** [comment]
Fixed with patch 09/12/2021
