### ISSUE TITLE
Did not get kill contribution for Felix Magnus

### ISSUE THREAD

**Issue by Ryanfawkez** [WarEmu/WarBugs#1966]
The Stalker shoulder follow-up quest to kill Felix Magnus did not work for 3 out of 5 members in our group, despite all having done the 20 BW kill quest first and having the objective to kill Felix.

**Comment by genisaurus** [comment]
Are you saying it worked for 2 of them then?

**Comment by Ryanfawkez** [comment]
Yes, it did work for 2 of them. Really weird how it played out. Upon killing Felix when he respawned the last 3 of us also got the quest completed properly.

Maybe we didn't contribute enough? I don't know

**Comment by genisaurus** [comment]
Could not reproduce on Dev. Likely a contribution problem, or it could be a problem with the way quest events are handled for groups sharing the quest. We'll look into those, but I'm going to consider this closed since it didn't seem to persist.
