### ISSUE TITLE
Sweating the Stones PQ Ch14 Elf #19644

### ISSUE THREAD

**Issue by DurinThornaxe** [WarEmu/WarBugs#19667]
There are still issues with this PQ. I can attack the Channelers now but I still can't attack Mistress Valira. 

![Untitled5](https://user-images.githubusercontent.com/86794706/145560733-fdb88b79-418e-4f29-8ffc-de0252c7ea91.png)

Best wishes, Durinsson

**Comment by lilimx** [comment]
Fixed with Patch 19/12/2021
