### ISSUE TITLE
Agro meter stopped working after patch 2021-12-09

### ISSUE THREAD

**Issue by acidicrain** [WarEmu/WarBugs#19665]
**Expected behavior and actual behavior:**
Agro meter appear in lord fights 

Previously as soon as lords in keep were attacked agro meter would activate
After the patch this does not happen and no notes in patch saying anything happened.

This means that it should be working as usual as no change to the addon so leaves that something on server side changed.
Entire warband had same effect so not local to my installation.

No picture as it seemed pointless to show the display without agro meter as it’s the same display as if not having the addon.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

as you said, the Aggro Meter is an Addon and doesn't belong to the bug tracker.
If you want a fix, please contact Sullemunk.
