### ISSUE TITLE
Scenario Emblems Still Rewarded After Leaving Scenario

### ISSUE THREAD

**Issue by Caduceus42** [WarEmu/WarBugs#19668]
Expected behavior:

When you leave a scenario, you are excluded from any rewards associated with it.

Actual behavior:

When you leave a scenario, you still receive emblems when the scenario concludes.

Screenshots/Video evidence:

If necessary I can share a screenshot of myself receiving emblems while under the effects of Quitter, but I'm not sure if that counts as "proof".

I've noticed this bug several times and am sure that the Oppressor Emblems I receive are the result of the scenario concluding, even though I am no longer in it.

I am not sure whether these are the emblems every player is rewarded at the conclusion of a scenario, or if it's a reward for being top player in DBs/damage done/healing done, etc. 

Cheers,

- Caduceus

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. This issue is already know.
Im going to close your ticket now and will add it the related one.

**Comment by lilimx** [comment]
dublicate / related to #19645
