### ISSUE TITLE
"A Run for Rolf" achievement not rewarding title

### ISSUE THREAD

**Issue by Caduceus42** [WarEmu/WarBugs#19661]
Expected behavior:

Upon killing 60 'Winter Lynx' and 'Winter Great Lynx' in Praag receive achievement "A Run for Rudolf" (Great Cat section of the Bestiary) and receive title "The Clawed". 

Actual behavior:

Achievement is rewarded, but not title. (Checked entire titles section to be sure)

Screenshot:
![ToK Bug](https://user-images.githubusercontent.com/69918329/145264158-e5474f64-e9a8-4c43-b130-fbab7c7f8a39.png)

**Comment by lilimx** [comment]
Hey,

thank you for the ticket. This issue is already known.
Additonal it's mentioned in the RoR Wiki: https://wiki.returnofreckoning.com/A_Run_for_Rolf

I will close this ticket and add it to the first ticket.

**Comment by lilimx** [comment]
dublicate/related to  #9726
