### ISSUE TITLE
Shaman tactic Bug

### ISSUE THREAD

**Issue by OutofcontroI** [WarEmu/WarBugs#19662]
I have noticed that the Morks Touch tactic , from Path of Gork (shaman's middle tree) procs with auto attacks. The description of the tactic says " all offencive spells". Strange not to work with Dots and procs with auto attacks :/

**Comment by lilimx** [comment]
Hey,

Thank you for your ticket. We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format.

**Comment by lilimx** [comment]
maybe related to: #10749

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
Anyway I already added the ticket to a related issue, so maybe no more information are needed.

If you are still the opinion that the issue still persits, please open a new ticket with proper evidences.
