### ISSUE TITLE
[SW] Steady Aim buff dropping when changing zone or after tactic set switch

### ISSUE THREAD

**Issue by CrimsonFenris** [WarEmu/WarBugs#19670]
**Expected behavior and actual behavior:**
Steady Aim is a on/off skill that should persist until deactivated.

Currently that's what happens when being teleported (after a flight/tp/death), or after switching tactic set : 
- Steady Aim buff is removed, action bar shows buff as off (the skill lose the glowing outline)
- Skills are now unaffected by steady aim (AP costs return to normal, see screenshot)
- Trying to reactivate Steady aim often results in triggering the 30s cd, as if the skill was still on, without further effect.

**Steps to reproduce the problem:**
1. Activate Steady Aim buff
2. Switch tactic set or change zone by taking the flightmaster or release after death : see the buff dropping
3. Try to reactivate Steady Aim, and the skill going into cd without being enabled.

**Testing Screenshots/Videos/Evidences (always needed):**
Before changing tactic : buff ON and costs are increased : 
![Tanaryon_006](https://user-images.githubusercontent.com/40425011/145689731-f54e0ea4-0793-4f1d-91db-354f8dbec2cd.jpg)

After changing tactic set, buff dropping, AP costs reverted to normal : 
![Tanaryon_007](https://user-images.githubusercontent.com/40425011/145689739-b30b4016-852f-48e3-9393-1eb64c7b33b9.jpg)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. This issue is already known.
Im going to close this ticket now and add it to the related one.

**Comment by lilimx** [comment]
dublicate / related to #19580
