### ISSUE TITLE
Healthpoint go to 50% of maximum

### ISSUE THREAD

**Issue by graffernsl** [WarEmu/WarBugs#19679]
**Expected behavior and actual behavior:**
Expected behavior : Normal HP. 
actual behavior: 50% HP
this bug happends with all wb members untill we def keep.
hp become normal after we leave keep zone.

**Steps to reproduce the problem:**
defence in reikland keep Wilhelms Fist

**Testing Screenshots/Videos/Evidences (always needed):**

![Grafferkobs_000](https://user-images.githubusercontent.com/58138563/146242881-0ddf2ff7-0954-47e5-a487-130b5a372b88.jpg)

**Comment by lilimx** [comment]
Hey,

Im pretty sure it's the "Diminished Rations"-debuff.
It occures for each side where are too many people are on the same place.
The mechanic is there since 2017.

**Comment by graffernsl** [comment]
It was about 2 order wb and 1 destro wb. not more 100 ppl in place. It was not such debuf even when 300x300 in one keep.

**Comment by lilimx** [comment]
still more order than destro....if the population is even, there shouldn't be any debuff
