### ISSUE TITLE
[Quest] "What's down dere" - Torches useable multiple times

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#19673]
The Quest requieres you to click seven "Chasm Torches".
Instead of looking for different ones you can just click one seven times.
![Wuts down dere](https://user-images.githubusercontent.com/40274248/145708041-b8cc09f5-74fb-49e1-85e9-dc12865868e6.jpg)

**Comment by Zomega-WAR** [comment]
I believe previously these had a delay on them to prevent you from spam-clicking.

**Comment by lilimx** [comment]
fixed with patch 22/12/2021
