### ISSUE TITLE
Riding to War quest in Chapter 18 Elf T4

### ISSUE THREAD

**Issue by DurinThornaxe** [WarEmu/WarBugs#19688]
In the Riding to War quest, High Elf chapter 18 we should speak with 5 high elf prisoners but there is only 2 and you can speak with them only once.

![Untitled5](https://user-images.githubusercontent.com/86794706/146670477-17fcd3d1-0f1b-4216-b4a3-9d7fa5924239.png)

I found this issue here #18682 but it was closed so I thought about posting it again. 

Best wishes, 
Durinsson

**Comment by Lheana** [comment]
It is possible as there are 2 camps, both are marked.
![Lheana_280](https://user-images.githubusercontent.com/11537611/146996514-ad1cd676-a828-4e55-b4fd-47ff1793ad5e.jpg)
