### ISSUE TITLE
Shadow Warrior No Quarter Bug

### ISSUE THREAD

**Issue by Lonso69** [WarEmu/WarBugs#19680]
The Scout mastery tactic "No Quarter" constantly needs to be reapplied to the tactic bar to have any effect.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. This issue is already known.
So I will close your ticket and put it to the related one.

**Comment by lilimx** [comment]
dublicate / related to #17950

**Comment by Lonso69** [comment]
ah ok, a known bug from over 1 year ago that hasn't been fixed. ill spec out of it
