### ISSUE TITLE
The Ritual of Beasts PQ Ch 17 Elf T4

### ISSUE THREAD

**Issue by DurinThornaxe** [WarEmu/WarBugs#19682]
The same as some of the other PQs I've reported on here for not triggering the Tome of Knowledge achievement.

![Image 1](https://user-images.githubusercontent.com/86794706/146524550-219993a8-5cf7-40b6-bf1c-e34311d3ced0.jpg)
 
I hope this helps!

Thank you for your work, 
Durinsson

**Comment by lilimx** [comment]
related // dublicate of #15152
