### ISSUE TITLE
Squigarmor and +power seem to not reset

### ISSUE THREAD

**Issue by BomblingTV** [WarEmu/WarBugs#19681]
Hello,
Expected behavior:
When you as a SH enter Squigarmor and equip a bunch of +ranged power gear such as Vanq belt, Warlord 5piece bonus. The +power is added to your Squigarmor stats. But if you take the gear off, zoneswap or even pvp die the stats are still remembered and you can keep them to have a high bonusdmg on top of running for example a Boost 5 proc from Offensive sove while douple dipping into both a 99range power bonus from one set, and Boost 5 from an other.
With soeve gear on:
https://media.discordapp.net/attachments/915654064539303986/921231092927848478/unknown.png?width=391&height=505
With Warlord & vanq belt boots on for big ranged power boost:
https://media.discordapp.net/attachments/915654064539303986/921231259043258428/unknown.png?width=376&height=505
With sove back on, after having entered Squigarmor and not left it while its beeing boosted by the +ranged set:
https://media.discordapp.net/attachments/915654064539303986/921231741119774770/unknown.png?width=382&height=505

At first i was thinking it was related to swapping preset builds at the trainer from a Balistic build to Str build going from Ranged to Melee build. but it does seem to be replicatable entering the following steps:

1 Enter Squig armor. (questionable if needed) check bonus dmg and stats.
2 Equip all the +ranged power you can find (unsure if works with mainstats too)
3 Reenter Squig armor. Compare the stats and bonusdmg.
4 take the +power gear off and equip your other armor (used offensive main set sove for my example to get boost 5 proc)
5 compare your stats and bonus dmg without the +power gear equiped while still having the effects.

**Comment by lilimx** [comment]
Fixed with Patch 19/12/2021
