### ISSUE TITLE
Items of another faction (Order in this case) are falling on the scenario

### ISSUE THREAD

**Issue by Erisprospero** [WarEmu/WarBugs#19696]
As you see, i have order items in my inventory. I recived them on scenario. I dont think that items of anouther fraction should fall to character, which can not use them
![image](https://user-images.githubusercontent.com/31616831/147296448-e490d689-57f1-4156-ba35-a9060f04fa15.png)

![image](https://user-images.githubusercontent.com/31616831/147296480-eb7956b5-9d6a-40b4-90da-1b60452c385b.png)

**Comment by wargrimnir** [comment]
That's my fault. Gonna have to boot to fix it.
