### ISSUE TITLE
Rune Priest DoT Rune of Immolation is uncleansable

### ISSUE THREAD

**Issue by bloodmasked** [WarEmu/WarBugs#19695]
This damage over time ability's tooltip lists it as neither a hex, ailment nor curse. Only as a "damaging" ability.

It therefore cannot be cleansed. 

This makes the tactic called Immolating Grasp especially powerful (which procs from the ability) and also since Rune of Immolation has no cooldown it therefore is even more unavoidable (if you disrupt it once, they may simply cast it again and likely not be disrupted a second time).

**Comment by lilimx** [comment]
Hey,

the damage type is right. You can read everything #12734
