### ISSUE TITLE
Every Box/Bag of Emblems/Medaillons, Liniments etc. give Double Amount

### ISSUE THREAD

**Issue by Syracus84** [WarEmu/WarBugs#19697]
I bought a Box of Dominator Emblems (25) with 5 Oppressor Emblems. After Opening it gave 50 Emblems instead of 25.

**Expected behavior and actual behavior:**

Box of Dominator Emblems (25) - Opening gives 50 Dominator Emblems

**Steps to reproduce the problem:**

Buy 1 Box of Dominator Emblems (25) with 5 Oppressor Emblems. Right-Click the Box to open.

**Testing Screenshots/Videos/Evidences (always needed):**

![Sanduran_006](https://user-images.githubusercontent.com/61934085/147297498-f3b2d046-a203-4f04-9c86-fe1f24b8968b.jpg)
![Sanduran_007](https://user-images.githubusercontent.com/61934085/147297530-47156961-30b2-4d4c-810f-a4a443e75581.jpg)
![Sanduran_008](https://user-images.githubusercontent.com/61934085/147297543-eea37d86-aaec-40b5-b953-23b56b9295f2.jpg)

This works with all boxes btw, even the (5) give double the Amount.´

Update: Even Liniment Box and Keg Present give Double Amount of Stuff. Seems like all openable Boxes are like this.

**Comment by Syracus84** [comment]
Btw it works with all boxes, even the (5) ones give double Amount.

**Comment by Syracus84** [comment]
Seems like it got already fixed. Please close or delete. Thank you!

**Comment by MaxHayman** [comment]
Fixed
