### ISSUE TITLE
Armor potions and Instructor's Boon share the same cooldown

### ISSUE THREAD

**Issue by aaearon** [WarEmu/WarBugs#19691]
**Expected behavior and actual behavior:**
When you use an armor potion, the Instructor's Boon scroll goes on cooldown and vice versa.

**Steps to reproduce the problem:**
Acquire an armor potion and an Instructors Boon scroll. Use on or the other and observe they are on the same cooldown.

**Testing Screenshots/Videos/Evidences (always needed):**
![2021-12-21 10_20_02-Greenshot](https://user-images.githubusercontent.com/812640/146904575-2535781f-a139-42a2-80c5-bc3fbc4442b0.png)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. This issue is already known.
So I will close this ticket and put it to the related one.

**Comment by lilimx** [comment]
related // dublicate to #19634
