### ISSUE TITLE
Reloadui -> crash

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#1969]
Reloadui causes crash to characters window

**Comment by MKorin** [comment]
Fixed after game restart

**Comment by MKorin** [comment]
It keeps happening

**Comment by Tesq** [comment]
after last patch or the one before

**Comment by sioding** [comment]
**Thanks for the report.** Since there is no confirmation, i will close this issue now. Please make sure to follow the bugtracker rules which you can find here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)
