### ISSUE TITLE
tier 1 lair bolster

### ISSUE THREAD

**Issue by bloodmasked** [WarEmu/WarBugs#19704]
The bolster seems to just not work at all, and other areas like the video shows is bolstering you too late (when you are already dead).

The area for the bolster should be expanded so that these bosses are less awful to deal with due to the tier 1 unbolster.

https://clips.twitch.tv/ShakingLittleReindeerDAESuppy-ta1rzvGo2_w1VsyU

**Comment by Zomega-WAR** [comment]
The checks for bolster are not continuous, seems to happen every few seconds or so. The lair in the video will remove bolster and put you back to 40 just after you jump off the tree ramp, but you just have to stand there for a moment until the server does the check and updates your stats.

**Comment by lilimx** [comment]
Hey,

hm, please retry your test like Zomega wrote

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persits, please open a new ticket with proper evidences.
