### ISSUE TITLE
auction stack size bug

### ISSUE THREAD

**Issue by bloodmasked** [WarEmu/WarBugs#19705]
Placing an auction fails when there is not an exact amount in your backpack, in the video I have 40 and 4 talismans. My auction is for 5 so it fails, and repeatedly moves the two talisman stacks in my backpack even after exiting the auction window. Usually have to relog to fix.

https://clips.twitch.tv/SmoothCarelessWaffleArgieB8-L4zPCgyXvl-S1byJ

**Comment by lilimx** [comment]
Hey,

this is not the vanilla RoR addon. Please retry your issue without Shinies.

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persits, please open a new ticket with proper evidences.
