### ISSUE TITLE
Hunter's Vale: quest log is not updating correctly after killing Treekin Twins

### ISSUE THREAD

**Issue by tfargh** [WarEmu/WarBugs#19707]
**Expected behavior and actual behavior:**
Killing the Treekin Twins should update the quest log.
It did not update the quest log. Two of us had only 1 out of 2 kills in the quest log. After finishing the dungeon, we went back to their spot and they were not there anymore.
We tried it again on different characters, and my quest log did not update at all, so 0 out of 2 kills registered.
The lockout timer however did update, showing a lockout of 17 hours on the Treekin Twins

**Steps to reproduce the problem:**
We tried a second run on different characters just killing the Treekin Twins. Same result.

**Testing Screenshots/Videos/Evidences (always needed):**

![HV1](https://user-images.githubusercontent.com/29236851/147614043-6ee87299-d9b9-46a5-a555-0626ecd0627c.jpg)

![HV2](https://user-images.githubusercontent.com/29236851/147614051-064faddf-da10-45e8-869e-b2192f75df7f.jpg)

**Comment by Rydiak** [comment]
I have tested this with two characters recently and have been unable to reproduce it.  Is it still happening?  Have you tried abandoning the quest and re-acquiring it?

**Comment by MaxHayman** [comment]
Please reopen if you continue to have this issue.
