### ISSUE TITLE
Keg End Event - can't loot giant

### ISSUE THREAD

**Issue by bloodmasked** [WarEmu/WarBugs#19709]
https://clips.twitch.tv/UgliestHardFerretHassaanChop-4jy-ixbM-xIw7-8-

for some reason can't loot giant at barak var

**Comment by bloodmasked** [comment]
then we killed the caledor one and it was lootable

**Comment by lilimx** [comment]
Hey,

I can't watch your video. I guess your link isn't correct.

**Comment by lilimx** [comment]
Hey,
