### ISSUE TITLE
Influence items (T3, WE)

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#1970]
T3, Dark Elf, Advanced, Ghrond's Fright Shawl - Chance to be DODGED
T3, Greenskin, Basic, in both blue and both purple rings same stats
T3, Greenskin, Elite, Qhaysh Corset - Willpower

**Comment by Tesq** [comment]
Ghrond's Fright Shawl
+ 17 Strength
+ 9 Toughness
+ 98 Spiritual Resistance
+ 98 Elemental Resistance
+ 98 Corporeal Resistance
+ 1% Reduced Chance to be Evaded

http://www.arsenalofwar.com/armor/Destruction/Ghrond's%20Fright%20Shawl

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/5494

**Comment by NorKalli** [comment]
long ago fixed
