### ISSUE TITLE
Zealot Issues

### ISSUE THREAD

**Issue by randyhartle** [WarEmu/WarBugs#19710]
While using a self-buff "Harbinger of Doom" am unable to change equipment.  To alter any equipment, (Upgrades or even unequipping gear) HoD must be turned off, and allowed to dissipate fully before gear changes are permitted.  Right clicking or dragging gear to slots without doing this first just results in the item being returned to inventory or remaining on the mouse cursor without changing stats.

Hexxe lvl 10 Zealot

**Comment by Kruge1976** [comment]
known issue mate (theres another log that was raised) - although it is a few weeks. 
Right pain!

**Comment by Rydiak** [comment]
Duplicate #19690

**Comment by randyhartle** [comment]
Thanks Kruge1976, did not see the original.
