### ISSUE TITLE
Beastlord quest

### ISSUE THREAD

**Issue by romcoll85** [WarEmu/WarBugs#19714]
Hello, I'm on the quest for the beastlord set. I managed to take 3 quests. On the other hand, the orc NPCs don't want to give me the quests.

Gitilla da Hunter - Black Crag 12k / 14k Camp Chapitre 16
Wotgrok da Weird - Kadrin Valley 40,5k / 37,5k Camp Chapitre 21

these two nps don't want to give me the quest. how to do ? cordially

**Comment by Lheana** [comment]
Seems like the info you have are outdated, check this:
- Karrig the Despoiler - Praag Chapter 17
- Brolgr - Chaos Wastes Chapter 15
- Boldug - Thunder Mountain Chapter 19
- Vilhjamur Godbane - Reikland Chapter 22
- Wrenthian Darktide - Eataine Chapter 20

**Comment by romcoll85** [comment]
thank you very much for this information. I apparently got bad information on the internet. thank you for your speed of intervention

**Comment by Lheana** [comment]
Then I close the ticket :)
