### ISSUE TITLE
NPC incorrect behavior (ranged vs melee) Magi Seer

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#1971]
These NPC in High Pass should not attack in the manner of melee, but used ranged magic instead.
Magi Seer.  
there is likely other similar NPC in the area
Magi Orator
Mutated Magus
Summoned Horror don't respond to Mutated Magus aggro correctly
Mutated Zealot 
Gifted Sorceror
Changing Zealot
Changin Magus

**Comment by Meralors** [comment]
All fixed, they should now use ranged attack.
