### ISSUE TITLE
[SH] Squig Leap no height restriction. Can jump all walls

### ISSUE THREAD

**Issue by somesneakygit** [WarEmu/WarBugs#19713]
**Expected behavior and actual behavior:**

Squig leap should not be able to be executed when there's a too much height difference, e.g. not able to jump up walls (e.g. keep walls or fortress walls).

**Steps to reproduce the problem:**

1. Be mSH
2. Target order or enemy npc on wall edge
3. Use squig leap and jump up

I got no video for now but if it's required I can try to make one. I play mSH. Jumping up walls in elf and dwarf keeps as well fortress is currently possible (and probably all others as well).

**Comment by lilimx** [comment]
Hey,

thank you for your report. We already have a big collection about this topic, so I will add your post to the big one.

**Comment by lilimx** [comment]
dublicate / related to #19632
