### ISSUE TITLE
SL Distracting Roar is Exhausting Rage (Same for Choppa)

### ISSUE THREAD

**Issue by ojoaop** [WarEmu/WarBugs#19719]
Expected behavior and actual behavior: The skill description doesn't say that your Rage will be exhausted by using detaunt.

Expected: Don't exhaust the SL/Choppa Enrage.
Actual behavior: When you use detaunt the Enrage is Exhausted.

Steps to reproduce the problem:
1 - Gain 100% Enrage
2 - Use Detaunt
3 - See your Rage go to 0%.

link of the video: https://youtu.be/ylBMXGXb8Ic

**Comment by bloodmasked** [comment]
Issue with fixing any one of the abilities that interact with the mechanic, is it would require a larger rework because you have to keep in mind tactics like the red tactic that prevents exhaustive blows from exhausting rage.

**Comment by ojoaop** [comment]
> Issue with fixing any one of the abilities that interact with the mechanic, is it would require a larger rework because you have to keep in mind tactics like the red tactic that prevents exhaustive blows from exhausting rage.

Yeah, you're right, but this skill doesn't mentione that you'll lose your rage. It'll be better if when you're in a fight against two players, you can detaunt one and keep your rage up, it's what make sense.

**Comment by GK111** [comment]
this is intended

https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=28164

**Comment by lilimx** [comment]
> this is intended
> 
> https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=28164

Awesome! Thanks!
