### ISSUE TITLE
[Blackguard] Force of Fury not working as intended

### ISSUE THREAD

**Issue by wghtopside** [WarEmu/WarBugs#19711]
As of patch of July 22nd:
_- Force of Fury: Armor buff no longer stacks with other armor buffs. The critical hit reduction has been changed to flat reduction of 5/10/15% instead of previous values of 15/30/45%.
It was previously meant to be a percentage based reduction, but actually worked like a flat reduction. However we feel that a percentage based reduction of a percentage based stat just complicates things, and when that stat is typically 0% for most players, it didn't really make sense. So we kept it as a flat reduction, but lowered the values instead. So this is both a bug fix and balance change combined._

However, in game FoF does not behave like flat reduction, but still behaves as multiplicative, only at 5\10\15% values.
My experiment went as following:
Untrain all renown points, unequip all gear. That brought me to 21.6% additional chance to be crit.
Use FoF at 90\60\30 Hatred and check the (anti-)crit value. The results are as following:
No FoF: 21.6%
FoF (90): 18.4%
FoF (60): 19.4%
FoF (30): 20.5%
The deltas being 3.2\2.2\1.1%, each roughly corresponds to 15\10\5% share of the 21.6% value I started with.
**This indicates to me that FoF does not only not grant -5\-10\-15% flat reduction but also still behaves as a percentage based reduction of a percentage based stat.**
Evidence:
![Coocoo_001](https://user-images.githubusercontent.com/79112443/147854209-9065fbf1-e7e8-4c1e-b732-925c516152c5.jpg)
![Coocoo_002](https://user-images.githubusercontent.com/79112443/147854214-75d20b1e-70cf-4243-9453-0e
![Coocoo_003](https://user-images.githubusercontent.com/79112443/147854221-64f6a699-b1d2-4398-bb82-587831dc4917.jpg)
c2fbc25b41.jpg)
![Coocoo_004](https://user-images.githubusercontent.com/79112443/147854226-c2e7cf51-8298-4bc5-8f19-3b9a57c6d01e.jpg)

**Comment by Rydiak** [comment]
#19105

**Comment by wghtopside** [comment]
Ran it through .getstats and .getstats show a flat -15% reduction. Closing the issue
