### ISSUE TITLE
Chopa Portly speedhacker?!

### ISSUE THREAD

**Issue by muraloo** [WarEmu/WarBugs#19718]
Makes a lot of punches in a short period of time!
![Portly](https://user-images.githubusercontent.com/47424013/148118205-becb5cf1-85e5-4ac6-a26c-1a72b7c32879.jpg)

**Comment by lilimx** [comment]
Hey,

sorry, the bug tracker is just for bugs.

If you have the feeling someone is cheating, please contact a GM ingame 
or join the RoR Discord: https://www.returnofreckoning.com/forum/viewtopic.php?f=2&t=22044 
Please bring some evidence aswell, if possible.

**Comment by wargrimnir** [comment]
Three damage sources at once is not cheating. There's lots of different ways damage can apply at the same time. You'll need to learn the sources of those damages to understand. They could be procs on hit, they could be damage over time, or both, or other things. This sort of report would require more significant video evidence to take seriously.

**Comment by muraloo** [comment]
Thx very much, I understood
