### ISSUE TITLE
[SW] No Quarter (tactic)

### ISSUE THREAD

**Issue by aadt1** [WarEmu/WarBugs#19715]
**Expected behavior and actual behavior:**
Everytime I die or enter a scenario, the effect is not active anymore. 
The only solution is to unequip "no quarter" and equip it again every single time.

**Steps to reproduce the problem:**
Have "No Quarter" tactic from the Path of The Scout active and die once/enter scenario.

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/96994155/147885720-45474df1-a0e5-4aab-9203-1a1346028174.png)
![image](https://user-images.githubusercontent.com/96994155/147885725-1b0a844e-b65f-497d-8246-7ebbf3a1f572.png)

**Comment by Rydiak** [comment]
What level are you?  It could be a bolstering issue.

**Comment by aadt1** [comment]
Currently level 29

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. This issue already has an open ticket, so I will add your report to the related one.

**Comment by lilimx** [comment]
dublicate // related to #17950
