### ISSUE TITLE
Witch Elf tactic Frenzied Mayhem

### ISSUE THREAD

**Issue by warhammerWE** [WarEmu/WarBugs#1972]
Treacherous Assault currently does not work and cannot be used at all, it simply does not respond in any way.
Flanking Mayhem tactic only seems to work on one stack of Blood Lust adding 3%. However any further stacks seem to have no affect on increasing crit chance. 
Heartseeker also seems to be doing less damage than the tooltip suggests. 

Thanks in advance

**Comment by Evildoor** [comment]
One report per problem please.

**Comment by Vdovics** [comment]
When game was up, before DDos train, I was able to crit with HS for about 1k time to time. I think dmg is ok If I consider the green equip and lvl 24 weapons.

**Comment by Evildoor** [comment]
Tested on the dev server, Treacherous Assault works (at least it gives 2 Bloodlust and low AP costs, cannot test magic damage on mobs). Frenzied Mayhem seems to be not working - panel and .getstats show no crit at 0, 1 or 5 Bloodlust.

**Comment by warhammerWE** [comment]
Thank you for replying, really appreciate all the work you put in :) I'll let you know if I find anything else amiss

**Comment by ozarmidrashim** [comment]
The multiplicative and additive handlers for tactics that scale stats by resource level were mixed up.

**Comment by Gobtar** [comment]
See this was closed 25 days ago, and there was fix pending, was the Frenzied Mayhem issue resolved? The tactic does not seem to work.

**Comment by Evildoor** [comment]
Tested, .getstats correctly shows 15 crit with 5 Blood Lust.
