### ISSUE TITLE
order can enter chapter 15 dark elf in caledor from RvR lake

### ISSUE THREAD

**Issue by Txarlyman** [WarEmu/WarBugs#19724]
Order can enter the destro chapter 15 dark elf camp in caledor from RvR because there is no champion lvl 55+ protecting that area. The few lvl 55+ champs arround are on the other side of the camp, toward PvE entrance, on the other side of the walls, or protecting a portal that goes to Saphery**

position of the guards:
![imagen](https://user-images.githubusercontent.com/59922493/148639034-c7dd8398-2530-4c49-a52f-477a49f79773.png)
![imagen](https://user-images.githubusercontent.com/59922493/148639089-06233251-fb4a-407b-8bdd-924d80197723.png)

oreder toon in middle of the WC:
![imagen](https://user-images.githubusercontent.com/59922493/148639133-4ef16604-7ee3-491e-b16d-9ac376a56b04.png)

you can get into the WC just by walking over this small elevation:
![imagen](https://user-images.githubusercontent.com/59922493/148639199-aa723c25-0851-459e-9e94-a24499d690fd.png)

thanks for you're help and atention.

**Comment by lilimx** [comment]
Fixed with Patch 11/02/2022
