### ISSUE TITLE
BloodLord 2-hand weapon different auto attack speeds in order and destruction

### ISSUE THREAD

**Issue by Bubsdubs** [WarEmu/WarBugs#19725]
on the order side, the speed of a 2-hand weapon is slower than that of the destro side.
because of this, the damage from an auto-attack of weapons on the destro side is weaker than on the order side

order side
![Varmint_003 (2)](https://user-images.githubusercontent.com/40487704/148668325-e365f405-3000-4676-ba20-7b30a78cc03f.jpg)

destro side
![2022-01-08 (2)](https://user-images.githubusercontent.com/40487704/148668340-76a4799c-7c14-401d-af7e-a04a113cd212.png)

**Comment by lilimx** [comment]
Hey,

after I discussed this with the team, this is not a bug nor an issue.
Speed doesn't affect DPS in any meaningful way. They're just different.
It still affects white burstablity va proccyness. Comes down to personal pref and/or build/comp synergy.

If you think this should be changed and you have some good ideas, please write a balance proposal here: https://www.returnofreckoning.com/forum/viewforum.php?f=95

**Comment by Bubsdubs** [comment]
> Эй
> 
> после того, как я обсудил это с командой, это не ошибка и не проблема. Скорость не влияет на DPS каким-либо значимым образом. Они просто разные. Он по-прежнему влияет на белую всплесковость и прочность. Сводится к персональному префу и/или сборке/комп синергии.
> 
> Если вы считаете, что это должно быть изменено, и у вас есть хорошие идеи, пожалуйста, напишите предложение по балансу здесь: https://www.returnofreckoning.com/forum/viewforum.php?f=95

and how to explain it
maximum non-critical attack per order 778
[![Varmint_001](https://user-images.githubusercontent.com/40487704/149517928-7a86c5e5-b888-417d-b684-46ba85197060.jpg)](https://cdn.discordapp.com/attachments/832516943700426752/931468163768524870/Varmint_001.jpg)
 and for destro side  592
[![Joppa_003](https://user-images.githubusercontent.com/40487704/149518079-622a6fe5-eb5a-44cd-ac92-932631643183.jpg)](https://cdn.discordapp.com/attachments/832516943700426752/931473771712368650/Joppa_003.jpg)

the slower the weapon the stronger the damage per attack. it turns out that for the side of the order, the characters will do more damage for the burst
