### ISSUE TITLE
Hunters Vale last boss animal aspects 

### ISSUE THREAD

**Issue by JingoNZ1** [WarEmu/WarBugs#19720]
**Expected behavior and actual behavior:**

On the last boss on Hunters Vale when kurinos chooses the three aninal spirit aspects there is no wolf/hound/lion to click on in the arena. The animals just arent there to click on so everyone has to eat the aoe dmg after the 10-15 sec timer.

**Steps to reproduce the problem:**

Have seen this on the last 3 HV runs ive done thos week. I did HV about 1 week ago before this bug and the animals showed up. I asked others in my group and they also said that animals not showing up in these last 3 runs.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Rydiak** [comment]
The animals ARE there, but stealthed around the outer area of the arena.  You need to have your team spread out to find the animals, not sit idle in the middle.  Not a bug.
