### ISSUE TITLE
NPC SC weekly events

### ISSUE THREAD

**Issue by PIERCE71** [WarEmu/WarBugs#19739]
Hi there,
I complete the events but  cannot get rewards from NCP SC events.
The rewards are not selectable.
Please help me.
Thx

**Comment by lilimx** [comment]
Hey,

could you post a screenshot from your influence bar in the ToK and where do you want to pick up the rewards?

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persits, please open a new ticket with proper evidences.
