### ISSUE TITLE
Hatred UI Bug

### ISSUE THREAD

**Issue by LordVanidas** [WarEmu/WarBugs#19732]
Often times when you're in combat, your Hatred will jump around or disappear. In the video uploaded below, you can see my hate counter disappears several times, or jumps from 100 to 10, then back to 100. Hatred should remain on the screen while in combat unless it's at 0 as far as I'm aware.

Steps to reproduce:
Your Hatred will usually jump from 100 to 10 when you use Enraged Beating at 100 hate. The red number value representing your Hate will also disappear occasionally, sometimes immediately after you exit combat, other times it drops in the middle of a fight.

Video evidence:
https://youtu.be/DXP8ivM3gWk
(Github won't let me upload a video more than 10MB, will upload directly if there's a workaround)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. There is already a ticket about that issue.
I will close your ticket now but I will add it to the related one.

**Comment by lilimx** [comment]
dublicate / related to #16711
