### ISSUE TITLE
My sorc Drakaryn is Hitting Astronomically Hard with Bolster? 

### ISSUE THREAD

**Issue by OGFear** [WarEmu/WarBugs#19730]
**Expected behavior and actual behavior:**
So as far as I've Heard from fellow Guildies Hitting for anywhere of the upwards of the 3.5k Region+ is unheard of with Word of Pain from a sorc with bolster? Im doing Double the damage of all my other friends who are bolstered and around the same level that are also on Sorcs. Our levels are as follows mine is 27 and the other two are level 28 and 31. My chillwinds are ticking as crits for 1000+ My hand of ruin is ticking for 2.1k crit ticks. My doombolts hit for 2.5k+ and my Gloombursts are hitting for 1.9k to 2k crits and my Arctic blasts are hitting for 2.2k Crits. This was Occuring in Open World RvR and I was pretty much able to oneshot anyone I came across including Fully Sovereigned out Players. I will Log out now so I do not get banned for Abusing but thought it deserved Attention since my Guildies were saying that something isn't right with my damage. 

**Steps to reproduce the problem:**
Edit: It seems the same Bug Occured to Frozenover and upon looking at his report it was indeed the same bug where I apparently had died at some point with 100 dark magic and my crit rate stayed like his I see in his screen shot his WOP hit for 3.6k and mine is now hitting for 3.7k+ so I believe it is the same issue that revolves around crit modifiers not resetting on death and or due to some weird number screwup when reviving. 

**Testing Screenshots/Videos/Evidences (always needed):**

![Jesus](https://user-images.githubusercontent.com/97493609/148877919-dba0089f-5e7e-4224-a463-acc7c702b0fa.PNG)
https://cdn.discordapp.com/attachments/925891355799076875/930303423868444682/unknown.png

**Comment by OGFear** [comment]
#18744

**Comment by Talladego** [comment]
Yes, I have also seen some very weird numbers occasionally on my sorc.
Not sure why and how though.

**Comment by Talladego** [comment]
It seems to get gradually worse the longer you play.

![Talladega_005](https://user-images.githubusercontent.com/45210243/149627266-eeac719c-00c4-4f01-acc5-f98ac4d112f4.jpg)

**Comment by lilimx** [comment]
Fixed around the Patch from 9/03/2022
