### ISSUE TITLE
Gunbad "Opt-out of Gold Bag" not working

### ISSUE THREAD

**Issue by DamizanFoshizzle** [WarEmu/WarBugs#19737]
**Expected behavior and actual behavior:**

 We ran Gunbad last night and I won 3 or 4 gold bags last night and all of them were definitly gold bags. I clicked "opt-out all bags" but kept getting the golds. When I clicked "opt-out gold bags" it did seem to work, as I didn't get any gold bags. Seems when I click "opt-out gold bags" it's set to just give you gold bags. Not sure, would have to test it. In any event, the opt-out of gold bags option in Gunbad is not working

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/97672876/149337670-028c5ec3-3000-464d-84ea-802074a8bee9.png)

**Comment by lilimx** [comment]
Hey,

I saw you already posted it in the origin report. So I will close this one and linking it.

**Comment by lilimx** [comment]
related / dublicate of #13976
