### ISSUE TITLE
Tome of Knowledge showing wrong belt for my Archmage

### ISSUE THREAD

**Issue by DamizanFoshizzle** [WarEmu/WarBugs#19736]
**Expected behavior and actual behavior:**
ToK is showing that I need "Bloodlord Whipsash" in my belt spot, which is a Magus piece, but I'm an Archmage. I do have "Bloodlord Silkenwrap" but I'm not getting credit for wearing it because the Tome of Knowledge has it as the Magus belt.
Damizan - 40/52 AM

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Damizan_007](https://user-images.githubusercontent.com/97672876/149335267-d5069181-79fe-4d77-b314-3db5dfbf05c6.jpg)
![Damizan_008](https://user-images.githubusercontent.com/97672876/149335301-bfa8884e-c4aa-4605-a482-208d9ec4dadf.jpg)

**Comment by lilimx** [comment]
Fixed with Patch 23/06/2022
