### ISSUE TITLE
Furriksson's Pick stats randomized on equip and do not provide any stats

### ISSUE THREAD

**Issue by dangerdoneky** [WarEmu/WarBugs#19733]
This seems to be known amongst players but doesn't appear to be an open ticket for it.

Expected:
The stat displayed on the pocket item remains static and grants the stat on equip.

Actual:
The stat changes each time you equip it and has no impact on character stats.

**Steps to reproduce the problem:**
1. Obtain the pick.
2. Equip it

Testing Screenshots/Videos/Evidences 
Item and stats before equip:
![image](https://user-images.githubusercontent.com/97580560/149067070-7d8c1608-d2a9-4c00-830b-d36f4258f07d.png)

Item and stats after:
![image](https://user-images.githubusercontent.com/97580560/149067186-c972000c-e108-4c91-95e6-bea1dce5e6ad.png)

Note no change in stats on character

**Comment by Tesq** [comment]
it's visual bug, work liek this, move the mouse over another itiem, the interface keep track of the stats or talismans then move onto the poket it will traslate visual only that stats into the pocket.
