### ISSUE TITLE
[Shaman] Dat makes me fizzy + focused mind bug

### ISSUE THREAD

**Issue by Morksezstop** [WarEmu/WarBugs#1973]
Insta ress tactic doesnt work properly when focused mind is active. On live with FM on you bypass the 3 sec stun effect and just insta ress. On ror when cast with FM you stay stunned for 3 sec

here one sc of the bug
<a href='http://postimg.org/image/8ktwre7yz/full/' target='_blank'><img src='http://s9.postimg.org/517z1l59b/insta_ress.jpg' border='0' alt="insta ress" /></a><br /><a target='_blank' href='http://postimage.org/'>photo hosting</a><br /><br />

**Comment by Morksezstop** [comment]
being immune for stuns also bypass the auto-stun component of dat makes me fizzy. I assume that also is not working but i didnt test it, it is more tricky to do

**Comment by Evildoor** [comment]
Uh, are you sure? Focused Mind description says "... and ignore any silencing, disarming, rooting, snaring effects ..." - stuns and knockdowns are not mentioned.

**Comment by milosxe** [comment]
Yes, Focused Mind gave you immunity to stun and stagger. And I can confirm that this is how FM and insta rez tactic worked on live.

**Comment by Morksezstop** [comment]
here at 3:10 the shaman being with immune timmer didnt get stuck from insta ress. When immune to stubs no matter via the immune timer or FM you dont self stun yourself but you still need to be at one spot to cast it. It is still impossible to cast it on run hence the shaman stop cast it /you can see the animation/ and then run away right away
https://www.youtube.com/watch?v=g1W4yk5Pu1I

**Comment by ozarmidrashim** [comment]
I deliberately coded an exception for these abilities, so that the self stun would always hit and ignore immunities, reasoning that Mythic wouldn't allow the drawback of the tactic to be so easily violated.

Lesson here is, assume no rational design.
