### ISSUE TITLE
Inventory, Ability, Tok windows broken

### ISSUE THREAD

**Issue by Banakomaz** [WarEmu/WarBugs#19734]
After I re-installed my game all game got broken.

Tok got broken window

![tok](https://user-images.githubusercontent.com/97589071/149086460-6b6c9558-77ea-4ddd-9f3a-49954158b297.png)

merchant windows also
![merchant](https://user-images.githubusercontent.com/97589071/149086284-c379356f-8ab0-4ab9-8647-dc3b68f5cc16.png)

I also cant get any loot from rvr or sc loots. Even zone locks I get bags but no crests

I have done all download guied and re insatll 5 times also repaired launcher several times but no solution

Your advise will be appreicated

**Comment by lilimx** [comment]
Hey,

sorry, but this belongs to the technical support forum: https://www.returnofreckoning.com/forum/viewforum.php?f=4
Or jump on the RoR discord and ask in #technical-advice: https://www.returnofreckoning.com/forum/viewtopic.php?f=2&t=22044

**Comment by Banakomaz** [comment]
Ok thx
