### ISSUE TITLE
potion gone when mounting up

### ISSUE THREAD

**Issue by bloodmasked** [WarEmu/WarBugs#19743]
i keep losing my potion when playing my level 38 bright wizard. 

after mounting it seems to go away.

here is clip, it can be seen to go away from my buffs and also my intelligence drops from 800 to 720 https://streamable.com/ppj1iv

**Comment by bloodmasked** [comment]
im not entirely sure what causes this but im level 38 bw and i keep randomly losing my potion

**Comment by lilimx** [comment]
Hey,

I can't see that you are loosing the potion entirely.
Please confirm that with a screenshot of your .getstats display.

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persists, please open a new ticket with proper evidences.
