### ISSUE TITLE
DPS zealot DOT bug

### ISSUE THREAD

**Issue by Wotop** [WarEmu/WarBugs#19747]
**Expected behavior and actual behavior:**

Two of my DoT abilities Warp Reality and Tzeentch's Lash seemed to have crit and not sure if it was because of the crit or other reasons but the damage was done instantly it seemed.

**Steps to reproduce the problem:**

Not sure how to replicate the problem, this was 1st time happened in Reikland after order locked zone there were some farming destro on the bridge. I tried to kill a healer (Warriorpriest), and actually did and that is when I knew something was wrong.

**Testing Screenshots/Videos/Evidences (always needed):**

![Wotopheals_001](https://user-images.githubusercontent.com/97999841/150052600-009d4473-baa1-4872-924d-d2f4e2acc17c.jpg)

I am sorry if this isn't the best bug report I am knew to this just thought it was very odd.

**Comment by lilimx** [comment]
Hey,

was the fight right next to the bridge to your Warcamp?

**Comment by Wotop** [comment]
Yes it occured right on the other side of the bridge out of destroy WC

**Comment by lilimx** [comment]
Hey,

then it's not a bug. It's just the Warcamp buff in favour for your side that increased your dmg.

**Comment by Wotop** [comment]
O that's my bad I didn't realize that was a thing tbh never seen it before.
Thank you for clarifying though, but ya know it did feel nice to actually
do some dmg as a DPS zeal all I'm saying :) thank you again for quick
response

**Comment by Wotop** [comment]
Also would the wc buff make the dot apply all dmg instantly? Or am I just
not understanding the combat log but it makes it look like two dots that I
cast applied their dmg instantly along with being a crit.

**Comment by lilimx** [comment]
Hey,

after you haven't activated the timestamp option in your combat log, it's hard to say when which DoT hitted...but all dmg stuff hits like a truck when you're next to your Warcamp.

**Comment by Wotop** [comment]
Gotcha thank you again for the quick response and information about what
happened. Much love to everyone who keeps this game alive.

**Comment by lilimx** [comment]
Hey,

you can also join our RoR discord (https://www.returnofreckoning.com/forum/viewtopic.php?f=2&t=22044), when you're not sure about an issue.
