### ISSUE TITLE
[Shaman] Pass it on dont works as tooltips suggest

### ISSUE THREAD

**Issue by Morksezstop** [WarEmu/WarBugs#1974]
Pass it on is suppose to proc on heals from mork tree. It does from some but it doesnt proc from DSU and Gork''ll fix it hot ticks. Frankly doesnt know how was on live but the tooltips said "...when you heal an ally with park of mork ability..." and yet the main mork ability DSU is excluded.

Among with all that if we follow the logic with AM 12 points tactic (issue #1863) DSU and gork'll fix it hot part should proc the heal aswell as the tooltips said.

**Comment by Morksezstop** [comment]
well shamans got like 5-6 very strong tactics so very few ppl ever speced and used pass it on \not to mention how ureliable and random is the tactic\.
So even if on live wasnt working with DSU, Grok'll fix it and shrug it off that was becouse it was bugged but noone cared to report and fix that. The thing is if we need to follow the tooltips it is quite obvious how it should work and even then the tactic will be far from the strengh on these 6-7 highly important tactics for shaman class

**Comment by Squea** [comment]
I was going to post this issue.  I can't get it to proc off of DSU which is the whole point of the tactic.

**Comment by Luth-RoR** [comment]
No evidence/response -> closed.
