### ISSUE TITLE
Guild Heraldry Won't Change

### ISSUE THREAD

**Issue by LordVanidas** [WarEmu/WarBugs#19741]
My guild recently reached level 10 and when I attempted to edit my heraldry, everything changed except the symbol. I tried again and it charged me an additional 100 gold without changing anything. Symbol is still stuck on default after I attempted to switch to Emblem 15 several times. Assistance and a refund would be greatly appreciated.

Steps to reproduce:
Attempt to change guild heraldry, not sure if there are any special circumstances involved.

Video evidence:
https://youtu.be/rW7KUUp0xgo
(Note: I had 400 gold before starting this video. Can provide additional video evidence if needed.)

**Comment by lilimx** [comment]
Hey, 

your guild needs atleast lvl 20 do get the emblem stuff.

![grafik](https://user-images.githubusercontent.com/23266079/149678914-8a83cf68-8ad0-4590-92c9-7bb52d656397.png)

**Comment by LordVanidas** [comment]
Could we possibly get a better visual indicator for that? It's really confusing for first-time users, and can result in extra money being lost, which is what happened here.

**Comment by lilimx** [comment]
Hey,

hmm....I don't know if it's possible but you can write your issue and maybe a simple solution idea in our suggestions & feedback forum here: https://www.returnofreckoning.com/forum/viewforum.php?f=15

**Comment by LordVanidas** [comment]
Got it, thanks for the info.

Also, is there any chance I could get a refund on the 100 gold? No idea if you guys do that sort of thing, but it would be incredibly appreciated if at all possible.

**Comment by lilimx** [comment]
Hey,

sorry, we don't do any kinds of refunds.... :(

**Comment by LordVanidas** [comment]
Alrighty, thanks anyways!
