### ISSUE TITLE
Goldrune's pick - no gold gain increase

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#19751]
The pocket effect dosent work, it suppose to give 5% more money from kills but i killed the same named mob with and with out but it dosent give anything more. Always the same 2 silver and 80 brass

![image](https://user-images.githubusercontent.com/7527415/150528489-4a988126-955c-43ac-b826-96039d1dfa5f.png)

**Comment by lilimx** [comment]
related to #19733

**Comment by Tesq** [comment]
> related to #19733

yes, i also aded some line to that issue, same thing on destru one

**Comment by lilimx** [comment]
Fixed with Patch 23/06/2022
