### ISSUE TITLE
Tainted Claw / Deadly Clutch

### ISSUE THREAD

**Issue by Deathics** [WarEmu/WarBugs#1975]
It appears, after several rounds of testing, that Tainted Claw itself is not functioning as I believe it did on live. On live, if I am not mistaken, Tainted Claw was -not- an incoming heal debuff, but rather a heal diversion ability that would literally cause targets to resist 100% of a heal 25% of the time. The tool tip even reads this way.

On the tactic Deadly Clutch - I believe the correct functionality of the tactic was to add a 50% incoming heal debuff in addition to the 25% chance to resist heals. This effectively made the tactic worthwhile to run over the DPS alternatives. Currently, the tactic is only bumping Tainted Claw from a 25% to 50% incoming heal debuff - the heal component of the tactic does work.

**Comment by genisaurus** [comment]
Unfortunately, your memory is incorrect.
http://waronlinebuilder.org/#career=mar;
As of 1.4.8, Tainted Claw was a 25% heal debuff, and worked exactly like every other heal debuff. With Deadly Clutch, it becomes a 50% heal debuff, and the marauder absorbs 50% of the debuffed heals (25% of the original value).

This can be closed.
