### ISSUE TITLE
Jewelry has missing icon taking a slot in the backpack

### ISSUE THREAD

**Issue by Milkyn** [WarEmu/WarBugs#19753]
Due to the missing icon it is not visible that there is a slot occupied in the backpack.

**Expected behavior and actual behavior:**
That item should be visible.

**Steps to reproduce the problem:**
Item name: Shattered Band of Doomsday
Just put that item to your backpack, you'll see that there is nothing visible.

**Testing Screenshots/Videos/Evidences (always needed):**
![grafik](https://user-images.githubusercontent.com/8441622/150639551-2249f445-d7a3-486f-b234-b0f3b0d8aa68.png)

**Comment by Tesq** [comment]
missing icon is the one of in need of repair itiem ( aka broke itiem)

**Comment by Kaelang** [comment]
Temporarily fixed to stop it taking an invisible slot in the bag. Needs an artist to make a broken version of the tooltip.

**Comment by lilimx** [comment]
temporarily fixed with patch 21/07/2022
