### ISSUE TITLE
MMR rank not drop if you crash game in ongoin Ranked

### ISSUE THREAD

**Issue by Wraxin** [WarEmu/WarBugs#19758]
I have noticed it when i got internet issue. Crashed in last 20-30sec game.(it was draw with 0-0 score). People who im inside lost few point. For me it add lost not draw but not decrase my mmr points.(also have tested it on lost game, crahed in close to end sc, no mmr lost, just 20min quitter)
I have seen many people already crash game to avoid mmr lost(not sure if they crash on purpose or just internet issue)

Reported this bug already 3weeks ago, but someone deleted(idk maybe he don't want ppl see it to abuse), anyway now ranked season 3 is done so better fix it before season 4 start.

**Comment by MaxHayman** [comment]
This might be fixed, can you let us know if it happens again?

**Comment by Wraxin** [comment]
Ok i'm gonna test it on next losing ranked. Unfortunately, not enough ppl in que today.

**Comment by GamesBondd** [comment]
> Ok i'm gonna test it on next losing ranked. Unfortunately, not enough ppl in que today.

No worries, take your time. Thank you for helping.

**Comment by Wraxin** [comment]
Ok i tested it, it's fine now, 653mmr crashed game when we losing now 615 and 20min quiter

**Comment by GamesBondd** [comment]
> Ok i tested it, it's fine now, 653mmr crashed game when we losing now 615 and 20min quiter

Perfect, thanks.
