### ISSUE TITLE
Can't change nickname due to date/time issue

### ISSUE THREAD

**Issue by mistmore** [WarEmu/WarBugs#19752]
![Zaxxed_005](https://user-images.githubusercontent.com/67388653/150551974-2523c45c-0feb-4395-80d7-c918afce7525.jpg)
I cant change nickname 
Issues should be unique. Check if someone else reported
the issue first, and please don't report duplicates.
Only ONE issue in a report. Don't forget screens or a video.
-->

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

there is currently an issue with the date/time ingame, that cause this trouble.
Devs are aware of this issue, so hopefully there will be a fix soon.

**Comment by lilimx** [comment]
Fixed with Patch 28/01/2022
