### ISSUE TITLE
Launcher/patcher incorrectly handling filenames depending on system locale (mainly Turkey/Turkish)

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#19754]
**Expected behavior and actual behavior:**

A very common problem that Turkish players have when patching the game is that instead of updating "interface.myp", it instead tries to create and update "ınterface.myp", which then causes the actual game to function incorrectly as it has files missing from the real "interface.myp".

The difference between "interface.myp" and "ınterface.myp" is that the second one is using the Turkish "dot-less i". This typically happens when string conversion functions are used to manipulate filenames (for example: String.ToLower), as those functions use the system locale to determine what the lower case version of each character is. For almost every locale, the lower case version of capital I is i (dotted), but when the system language is set to Turkish the lowercase version of capital I is ı (dot-less).

While using the system locale makes sense for most text/string conversions, it should not be used in this scenario, especially as the Warhammer Online client will only look for "interface.myp" and doesn't try to localise that filename.

If you're using String.ToLower in C#/.NET for filenames, please consider replacing it with String.ToLowerInvariant instead as this does not use the system locale for the conversion and should fix this issue.

This issue is one of the top-3 issues new players ask about when having issues installing the game (along with read-only files and OneDrive), and currently the only solution is for the player to change the language of Windows when they want to play ROR.

**Steps to reproduce the problem:**

1) Change the Window's language/locale to Turkey/Turkish
2) Run the launcher, pick repair to force a check/download
3) Look for the new "ınterface.myp" that will be created.

**Comment by MaxHayman** [comment]
Thanks for the report. Fix should be coming. PM me on discord if you are able to test it. MaxHayman#8344
