### ISSUE TITLE
[Quest] Destro - "The Price of Failure" bugged

### ISSUE THREAD

**Issue by elk76** [WarEmu/WarBugs#19769]
Destro quest at Ch18 Dark elf camp

It is a step of a chain quest: I collected the heads and when I placed them upon pikes the quest is still 0/1

![Hamund_181](https://user-images.githubusercontent.com/46483570/151770781-12e00dbd-98ec-4f1a-b82f-582d74893318.jpg)

**Comment by lilimx** [comment]
Hey,

please try the solution in this ticket first:  #16098
