### ISSUE TITLE
IC City - Queue timer drops to 0

### ISSUE THREAD

**Issue by Explorerbengt** [WarEmu/WarBugs#19761]
I was gonna solo queue for IC this morning (around 10AM server time), i looked at the city timer and it was 18min left and was about to queue, then instantly the timer (on my screen) dropped to 0 and the text came that city queue now is closed. Some others in guild had it drop from 15min to 5 min in a instance. 

Would be nice to understand what happend  to the queue since I never seen this before and missed a 5* IC.

Thanks in advandce.

//Explorer

**Comment by termofor** [comment]
I wanted to confirm that.. On the beginning queue time dropped from 22 to 12 for few people. And after that i jumped to 4 minutes to everyone. And afther that 4 minutes queue closed. Only preparation time was as it should be.

**Comment by lilimx** [comment]
Fixed around the Patch from 28/1/2022
