### ISSUE TITLE
Stacking changename tokens

### ISSUE THREAD

**Issue by eerytraveler** [WarEmu/WarBugs#19766]
You can stack changename tokens it seems, but if you try to stack a 3rd you get this -- 19000 days until eligible. Not sure if it is just a visual bug or that's now the real timer.

![image](https://user-images.githubusercontent.com/98583303/151517691-1934968e-fdbb-44cb-b75e-76d73fb0034a.png)

**Comment by lilimx** [comment]
Hey,

thank you for your report. There is already an open report about this issue.
I will close your ticket and add it to the oirgin one.

**Comment by lilimx** [comment]
dublicate // related to #19752
