### ISSUE TITLE
Dok tactic murderous intent

### ISSUE THREAD

**Issue by glasshands** [WarEmu/WarBugs#1976]
I don't think murderous intent is reducing healing by 20%.
![window_001](https://cloud.githubusercontent.com/assets/14142017/11412502/09bdb374-939b-11e5-95a0-18f0b9e3ee53.jpg)
![window_002](https://cloud.githubusercontent.com/assets/14142017/11412505/0be86630-939b-11e5-8370-6da646fc816f.jpg)

**Comment by ozarmidrashim** [comment]
If you're also running Divine Fury, that is why.
