### ISSUE TITLE
Order rvr quest not showing up on my characters

### ISSUE THREAD

**Issue by rolex29** [WarEmu/WarBugs#19772]
My White lion Crazytracy and my knight of blazing sun Blazingbabe both cant get 50+ kill quest that gives gold and experience the Destro version of those quests are The pleasures of war and the truth of war the order version of those 2 quests are not showing up on either of my characters on order 
![bild_2022-02-01_220352](https://user-images.githubusercontent.com/48477695/152051108-8c4080b5-9931-4a28-8c66-63b7e1bf9b96.png)
![image](https://user-images.githubusercontent.com/48477695/152051190-0312039a-2013-4b1b-bafa-b50b7453c950.png)

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persists, please open a new ticket with proper evidences.
