### ISSUE TITLE
crafting dye not working

### ISSUE THREAD

**Issue by hashkampf** [WarEmu/WarBugs#19776]
**Expected behavior and actual behavior:**
i can't craft dye anymore, the fixer isn't taken in account in the apoticary window, tested with multiple pigment

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/26326430/152603602-098fb39b-12f3-4be9-99d9-d34bf7428439.png)

**Comment by lilimx** [comment]
Hey,

thank you for the ticket. This issue is already known.
so I'll add it to the related report.

**Comment by lilimx** [comment]
dublicate #19526

**Comment by hashkampf** [comment]
cheers
