### ISSUE TITLE
return from losing scenario a chicken..

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#1977]
what I am getting now when in lower tier than your current tier.
in Tier 2 as RP lv 28
when I take a scenario (I lost) I return as a chicken)

currently in the PvE area of Troll Country.
thx

**Comment by Pitre67** [comment]
need to unflag for RvR and wait 10 mins

**Comment by Evildoor** [comment]
#995 is somewhat similar to this problem. But it no longer occurs and instead we have this problem, right?

**Comment by RoR-Zomega** [comment]
Confirming this still happens. Seems either the RvR flag isn't cleared or it's automatically reset when you leave a scenario. If you're in a different tier at the time then insta-chicken.

**Comment by DoubleBoxGames** [comment]
I can corroborate this experience. It still occurs.
![screenshot_000](https://cloud.githubusercontent.com/assets/7363810/14410244/96ed75b8-fef8-11e5-8ad3-c9ef1d97332a.jpg)
![aethelyn_000](https://cloud.githubusercontent.com/assets/7363810/14410245/98ba2b2a-fef8-11e5-9461-b1ffbe663f9a.jpg)

**Comment by gittoaster** [comment]
Doesn't seem relevant now.
