### ISSUE TITLE
[Quest] Destro - "The most ancient of enemies"

### ISSUE THREAD

**Issue by elk76** [WarEmu/WarBugs#19770]
This is a step of Destro chain quest in Dragonwake

There is not the dragon scale near the lair (and I cannot search inside because the lair is closed)

![Hamund_183](https://user-images.githubusercontent.com/46483570/151772171-040e445e-77a5-4631-a33d-34f8b7cc9e61.jpg)

**Comment by elk76** [comment]
thank you, it works
unfortunately I was misled by the fact that the head was still placed on the pike

**Comment by lilimx** [comment]
Uhm that's the wrong ticket. You mean #19769

**Comment by elk76** [comment]
sorry xD
