### ISSUE TITLE
Hunter's Vale - missing NPC

### ISSUE THREAD

**Issue by Tahtivaeltaja** [WarEmu/WarBugs#19778]
2/5/2022 - post patch

Our group did a speed run of Hunter's Vale, for the accessory. The final NPC did not spawn. Screenshot attached
![Screenshot 2022-02-05 141906](https://user-images.githubusercontent.com/90189853/152654477-0c6620ce-4bd1-4c8f-929d-5f9b46053905.png)
.

**Comment by Kourani** [comment]
We just had the same issue, my quest for jewelry timed out and my party members will have to make another run to get the quest again. Maybe close the instance down until this is resolved, so no one else wastes time doing it when it cant be properly finished.

**Comment by Tahtivaeltaja** [comment]
2/7/2022 - still bugged if you're doing a timed run
![Screenshot 2022-02-07 215957](https://user-images.githubusercontent.com/90189853/152871087-7a5e4b2a-9406-40c0-bbb8-9daf7ddd1c94.png)
n

**Comment by Chagatron** [comment]
Same situation. We made timed run, after killing last boss npc for rvr kill quest didn't show up.

**Comment by Mexlicious** [comment]
![Notfriendly_001](https://user-images.githubusercontent.com/51244185/152896697-25cacf70-26d4-4a90-9ca0-4a830853041d.jpg)

**Comment by wils0nyan** [comment]
I can confirm it's still bugged today please fix, ran it twice now with no reward

**Comment by lilimx** [comment]
Fixed with Patch 11/02/2022
