### ISSUE TITLE
First PQ: Chaos Chapter One PQ: Ruinous Powers stuck in stage two mode

### ISSUE THREAD

**Issue by Rildetarma** [WarEmu/WarBugs#1978]
The very first PQ one encounters after character creation in Chaos, the Ruinous Powers PQ is stuck in stage two and will not allow one to proceed.

**Comment by Evildoor** [comment]
Most of the PQs are not implemented/implemented wrong/bugged/whatever. And it is known.

**Comment by Rildetarma** [comment]
What is the status of #1923: the Magus career tactic in the Daemonology tree titled Daemonic Pact that is supposed to increase a magus' toughness when a daemon is present, but does not

 


    On Thursday, November 26, 2015 12:00 AM, Evildoor <notifications@github.com> wrote:
 

 Most of the PQs are not implemented/implemented wrong/bugged/whatever. And it is known.—

**Comment by Evildoor** [comment]
I don't know. Also, questions about #1923 should be asked in #1923. Also, i doubt that questions like "Status? When it will be fixed?" will be of much use - i rarely see such questions answered.

**Comment by ozarmidrashim** [comment]
Yup. Please don't ask for status updates on the tracker - none will be given. I get to it when I get to it.
