### ISSUE TITLE
[WL] Leonine Frenzy ICD

### ISSUE THREAD

**Issue by Bejkon** [WarEmu/WarBugs#19787]
Hej,

Leonine Frenzy seem to have alot longer of a ICD than the TT suggests.

TT:
![LFTT](https://user-images.githubusercontent.com/35146895/152710261-b83d5d99-fa98-4019-991e-f429b22932b8.JPG)

This does proc from both pet AAs(obvious if testing) aswell as pet abilities, an example of the latter can be seen here:
![WL LF from Ability](https://user-images.githubusercontent.com/35146895/152710287-4f8d93b5-ebf7-4295-9bf1-c907d8bd54c7.JPG)

The pet AA speed seem to be pretty close to 2s, as seen here:
![WL pet AA](https://user-images.githubusercontent.com/35146895/152710304-9400ae8b-a36d-48c8-99bb-043e122e7f48.JPG)

So it should be easy, if you tried, to wait for an AA to proc LF then wait for a time between 0.5-2s and manually use a pet ability in order to see a second LF proc. It should be a regular occurance even if you didnt try, really. 

In reality this seems impossible. Ive tried to time it right over and over, the only way to proc it with an ability is to cast it before the pet is on the target and open with the aoe ability, or time it so that you pop LF right after an AA and then the pet uses an ability. This leads me to believe that the ICD of LF is much closer to 2s, rather than the stated 0.5s.

//Bejk

**Comment by lilimx** [comment]
👍 

Either the Tooltip is wrong or the icd.

**Comment by SecretsOTheP** [comment]
The tooltip should be correct. I've adjusted the GCD to 0.5, will be in the next update.

**Comment by lilimx** [comment]
Fixed with Patch 24/02/2022
