### ISSUE TITLE
tali slot in fortress staff for sorc, 2nd slot impossible

### ISSUE THREAD

**Issue by Ru6ez** [WarEmu/WarBugs#19782]
**Expected behavior and actual behavior:**impossible to slot the fortress staff (the 2nd slot).
ty and sorry to disturb u

**Steps to reproduce the problem:** just bought the staff

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/99128043/152683503-4def5fcf-068d-4d9e-8920-c1c08393abbb.png)

![Sorellah_000](https://user-images.githubusercontent.com/99128043/152683554-49abb55e-68bf-46ad-8a0b-5df85b0b0fe0.jpg)

**Comment by Ru6ez** [comment]
i desactivate all addons and repair the game, same issue

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. This issue is already known, so I put it to the related report.

**Comment by lilimx** [comment]
related to #19782

**Comment by Ru6ez** [comment]
ty :) im sad to be the first with this fortress issue ...:( ty by advance.
