### ISSUE TITLE
AM Sov Cloak cannot be dyed

### ISSUE THREAD

**Issue by bosli42** [WarEmu/WarBugs#19781]
The Sovereign-style cloaks for Archmage cannot be dyed. I don't care how ugly it's gonna look or if you don't assign areas at all, but at least make it accept dyes for transmogs please.

Apparently it is possible to do "dye all" at a vendor as a workaround anyway, so there is no reason to not allow it directly.

**Comment by Meliannia** [comment]
this must be a new Feature within the last 6 months
i have dyed my 2 Ams sov cloaks
one has red dye 
one has black dye

**Comment by lilimx** [comment]
Hey,

the AM "Sovereign Wrap of the Greatmage" is dyeabel....dye items and dye via vendor works.

**Comment by lilimx** [comment]
Same for the "Sovereign Wrap of the Greatsage"

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persists, please open a new ticket with proper evidences.
