### ISSUE TITLE
Can't equip an item, get message in chat pane 'cannot equip an item that is stacked

### ISSUE THREAD

**Issue by Capibaru** [WarEmu/WarBugs#19785]
Hi everybody, same problem that is in this ticket  #19651 but now its an item from mobs (special item that drops for book of knowledge). And now special items starts to stack as you can see on a screenshot. Ive drop a lot of them but still unequipable/
![ROR11](https://user-images.githubusercontent.com/95568219/152701579-6b55d8d8-18df-4585-a1f7-8abc72575a3b.jpg)
![ROR22](https://user-images.githubusercontent.com/95568219/152701592-69d6cc83-9211-4d07-a2e4-faa5a9baafc9.jpg)

**Comment by lilimx** [comment]
Hey,

for the tome unlock you have to collect them and hand in by your local library.
These loot items are no pocket or trophy items.
