### ISSUE TITLE
BG Feeding On Weakness abilty always heals for 25% of damage dealt, instead of % according to actual Hate level, as tooltip says

### ISSUE THREAD

**Issue by andrasragany** [WarEmu/WarBugs#19783]
In the attached screenshot, my Blackguard has 100 Hate, FoW tooltip says above 90 Hate it should heal 75% of the damage dealt.
Combat log values:
Damage dealt: 256
Heal received: 64

This is 25% instead of 75%.
![FeedingOnWeakness_heal](https://user-images.githubusercontent.com/39407087/152684305-fa1fe3a9-506f-4397-932b-5591cee53d3c.png)

**Comment by taccr** [comment]
Looks like this has been fixed. Healing values are now correct for all hatred levels and the error message disappeared.

**Comment by lilimx** [comment]
fixed (unknown date)
