### ISSUE TITLE
loot previlege in PvE

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#19790]
**Expected behavior and actual behavior:**
if npc mob finished killing blow on another npc mob it gets the loot previlege and kill credit.
it was contribution based before, afaik.
so if friendly npc add and score killing blow when i killing quest mob i don't get loot.
or if npcs were fighting each other and i land killing blow at last moment, i get loot.

**Steps to reproduce the problem:**
i tested on bestial token mob Goremaw near elf t3 destro WC.
there's friendly Stag attacking Goremaw.
couldn't test on beastlord kill steal or GB mid wing 3rd boss npc kill.

**Testing Screenshots/Videos/Evidences (always needed):**
![Threescars_004](https://user-images.githubusercontent.com/19988772/152801655-b85a6200-43c7-46cf-9b64-394c120f2eb5.jpg)

**Comment by lilimx** [comment]
Hey,

are these questions or a bug report?

**Comment by xpander69** [comment]
Its not a bug report. Its a feature request i guess. for that, better place would be forum i would think.
the current implementation is like that. last hit is what makes it or breaks it. If npc does that, then you get no count or are not able to loot it
