### ISSUE TITLE
The problem with talismans

### ISSUE THREAD

**Issue by Khorni** [WarEmu/WarBugs#19796]
Hello. The problem on my favorite chaos (Lomanied)(40 lvl)
I can't insert any talisman except armor if there is a talisman of strength in the 2nd slot
![Безымянный](https://user-images.githubusercontent.com/99307739/153119383-ae5336ec-6b46-4fff-aba8-3cd3cd68322f.jpg)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. This issue is already known.
I'll add your report to the related one

**Comment by lilimx** [comment]
dublicate of #19648
