### ISSUE TITLE
Can't change Tali's on 2h weapons

### ISSUE THREAD

**Issue by Onlyendari** [WarEmu/WarBugs#19802]
Trying to upgrade a Tali from a +18 to +22 and it won't give me the option to fuse, tried on all my 2h across all my order toons(currently locked to order) and it always fails.  I can replace tali's in all other gear fine, just not 2h weapons.

**Comment by SecretsOTheP** [comment]
What's the item level of the item in question?

There's restrictions based on the level of the weapon on what talismans can actually fit in - that's why lower level purple talismans are great at lower levels.

**Comment by Onlyendari** [comment]
Yup it's a 40-61 am and slotting +22 tali into a subjugator staff, so it should work fine, also does not work on a 40-50 wl into a subj axe, nor a 40-50 wp in to t4 epic quest 2h hammer, nor a 40-72 bw into any staff i have.

**Comment by SecretsOTheP** [comment]
Do you already have a talisman of the same type in there?

**Comment by Onlyendari** [comment]
Yeah, the staff is currently equipped with a +18 wounds tali and +21 int tali, so I'm just trying to upgrade the +18 to a +22 something I used to be able to do.

**Comment by Kaeldrick** [comment]
After patch this noon, I could slot the second talis in my Fortress 2H weapon. Seems ok now 👍

**Comment by Ruin-84** [comment]
Same Here Nightless is nice and full of talis.

**Comment by xpander69** [comment]
thanks for reporting back. Closing this. If any issues arise, feel free to write here or create a new issue.

**Comment by lilimx** [comment]
Fixed with Patch 11/02/2022
