### ISSUE TITLE
Lost soulstone talisman

### ISSUE THREAD

**Issue by Foxington** [WarEmu/WarBugs#19800]
closing sentinel ring window with soulstone deleted the talisman, no warning to destroy item, item is just gone.

**Comment by lilimx** [comment]
Hey,

you checked if the talisman is back in your bag when you relog?

**Comment by Kaeldrick** [comment]
Check your in your bank in main City or new new City. Some changes have been made to these (crit reduced from 6 to 4) and my guildmates had a similar issue.

**Comment by lilimx** [comment]
hey,

please check after the patch again.

**Comment by Foxington** [comment]
Its back in my bag thank you.
