### ISSUE TITLE
the bonus from the armor set does not work

### ISSUE THREAD

**Issue by vadimchik77** [WarEmu/WarBugs#19803]
the bonus from the armor set does not work

![InkedSuperbol_000_LI](https://user-images.githubusercontent.com/99360754/153277640-3b1af1a8-b023-47e2-9a33-61e7b3019169.jpg)

**Comment by vadimchik77** [comment]
rebooting helped

**Comment by lilimx** [comment]
Hey,

Paperdoll stats are no reliable source.....always use the command .getstats
