### ISSUE TITLE
Guild notes disappear 

### ISSUE THREAD

**Issue by graffernsl** [WarEmu/WarBugs#19804]
**Expected behavior and actual behavior:**
When you kick any guildmate, all other guildmembers GUILDNOTES disappear. It disappear for all guildmates, who online in time of kicking player from a guild.

**Steps to reproduce the problem:**
Only reloging fix problem. Also if player log in after buf happends, this member GUILDNOTES will be visible

**Testing Screenshots/Videos/Evidences (always needed):**

https://user-images.githubusercontent.com/58138563/153411659-32e001f0-fd14-409c-98bb-213906914345.mp4

**Comment by lilimx** [comment]
fixed with patch 13/04/2022
