### ISSUE TITLE
error in the purchase of  fortress changestaff

### ISSUE THREAD

**Issue by Kionick** [WarEmu/WarBugs#19813]
I have 125 invader medallon
i have a ninrstaff of subjugator
when i try to buy  fortress changestaff, shows thismessage "you dont have enought money ti buy that"
this is a bug?  why i cant bu, if I have what it takes.
PJ WADEMAR

**Comment by lilimx** [comment]
Hey,

no, you don't have enough money. You should need 50g? or 120g?
