### ISSUE TITLE
COD mail Bug

### ISSUE THREAD

**Issue by Majorzero2123** [WarEmu/WarBugs#19817]
I understand that items wont be replaced/gold wont be replaced, not a big issue for my end, dont have a ton of screenshots, but want to make the issue aware.
I sent one Darkband of the fleshrender to "Whitechoppa" for a COD charge of 350 gold, I was informed that the mail didn't go through, tried sending another mail push but that didn't go through, this was about 5ish days ago.
I sent one Darkband of the fleshrender to "Sylaria" for a COD charge of 200, but i was informed that didn't go through either.  Tried sending another mail to push it through, but that didn't work either, this is the only screenshot i have:
![uwu1](https://user-images.githubusercontent.com/99697728/153969419-5fd354b7-51cb-438c-be0b-1d9c52787801.PNG)
Toon name is Majorzero if you want to check item logs or whatever, appreciate whatever you can do on this.

**Comment by lilimx** [comment]
Hey,

uhm what did you send? What did your mail look like?

**Comment by Majorzero2123** [comment]
> Hey,
> 
> uhm what did you send? What did your mail look like?

Sent 2 dark bands of the fleshrender, i was informed by both players i sent them too that the mail did not recieve on their end, so i didn't recieve anything on my end.
