### ISSUE TITLE
[WH&WE] Unbreakable Stealth

### ISSUE THREAD

**Issue by Bejkon** [WarEmu/WarBugs#19811]
Hej,

Stealth is supposed to have a 15% chance of breaking upon taking damage, afaik.

This isnt the case atm.

Im not sure exactly how the 15% is supposed to work, if its in the most general sense and anything goes or if its more specific like only if spotted by the attacker or excluding aoe etc. So with this in mind we did test every possible type of damage we could think of. morale/DD/dot application on spotted target aswell as blind aoe spam while the target was still invisible.

We did test this with both WE and WH as the target class. 
A few hundred hits each way. It should be enough to rule out the possibility of us being lucky.

Just to clairfy, the "spotted"(milky-mode) state seems to work just fine, it atleast procs from time to time.
However, if spotted, its only a matter of time until the character becomes fully invisible again. 
The only two ways to break enemy stealth atm is by killing the target while still stealthed or by draining its AP to 0.

//Bejk

**Comment by Khumakhan** [comment]
Yep, got a wh from 100 to 50% over many hits and stealth wouldn't break, and he just kept walking and went full inv again. So balanced.

**Comment by Rydiak** [comment]
I tested this versus NPCs and they can break stealth, so maybe it is only players that can't?

**Comment by MKorin** [comment]
Fix your fix plz, now all aoe break stealth 100% chance?

**Comment by Vladimir73** [comment]
Congratulations! We are useless now! At all!
Any AOE reveal us with BIG chance. Thank you!

**Comment by coltylul** [comment]
I have nothing against it. But feels like first 1-2 direct hits always broke stealth, even if you have absorb, seems not 15%.

**Comment by lilimx** [comment]
Hey,

the Dev team is aware of the fragile stealth pop issue and is currently on it to find a proper solution.

**Comment by lilimx** [comment]
Fixed with Patch 24/02/2022
