### ISSUE TITLE
BG Feeding on Weakness. 

### ISSUE THREAD

**Issue by afa555** [WarEmu/WarBugs#19824]
The hate bonus benefits don't work. It's always the same as if you did it with 30 hate.
It always heals by 25% regardless of hate and it should increase by 25% each 30 hate points up to 75% (90 hate points). But i get an error message after 60 hate saying: "ability modifier error".

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. This issue is already known.
I will add your ticket to the related report.

**Comment by lilimx** [comment]
dublicate #19783
