### ISSUE TITLE
Gate of ekrund sc is missing 

### ISSUE THREAD

**Issue by Evilchosen** [WarEmu/WarBugs#19828]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Evilchosen** [comment]
Its a bugged if you win its will miss from q list 
![image](https://user-images.githubusercontent.com/82473452/154698568-196d5d37-1fcf-459f-8d7e-3e6fce44dcb3.png)

**Comment by lilimx** [comment]
Hey,

that's no issue. We haven't switched the SC list yet.
So as you can read, PUG SC and Event SC are the same.

If the issue persist after that, please open a new ticket.
