### ISSUE TITLE
Destro gankers on the tower wall near Order WC in Praag.

### ISSUE THREAD

**Issue by Vladimir73** [WarEmu/WarBugs#19835]
So, yesterday SH killed me standing on the wall near our warcamp in Praag. When I understood where he from shootig me, it was too late )).
I've wasted some time and checked it. This place in PVE side. It easy to clambing up on this wall in point on the map 21,44. Need to jump on the small tower and there is a invisible step on the texture.
Anyway, this point the ideal place for catch players which ride between order wc and the Manor BO.
I hope you'll fix it.
Thank you. 
Vladimir.
p.s. Sorry for my english.

https://user-images.githubusercontent.com/16148013/154842561-a9ee93af-c11b-49e6-b8d9-4baa65a9cb5d.mp4

![Kondrad_117](https://user-images.githubusercontent.com/16148013/154842619-c31be05b-2914-45f6-a832-be3efbc45fc2.jpg)
![Kondrad_118](https://user-images.githubusercontent.com/16148013/154842622-0b332dcd-173c-4216-91ba-ac3e689a1057.jpg)
![Kondrad_119](https://user-images.githubusercontent.com/16148013/154842624-761b1394-7dcd-47d0-b44f-7cd5ebc824c6.jpg)
![Kondrad_120](https://user-images.githubusercontent.com/16148013/154842626-030ffa64-6cef-4a4d-9ca5-c910aaac3d52.jpg)
.

**Comment by lilimx** [comment]
Fixed with Patch 24/02/2022
