### ISSUE TITLE
Transfered 1 stack(40) lv50 armor potions from bank received 65k+in backpack

### ISSUE THREAD

**Issue by WAR2014** [WarEmu/WarBugs#19834]
Transfered 40pce lv50  armor potions from bank (Order) received 65k+ in backpack
![armor pot bug](https://user-images.githubusercontent.com/17757461/154824401-29275ed8-3d8c-4fe4-b938-e75430f34588.png)
![armor pot bug +](https://user-images.githubusercontent.com/17757461/154824605-1cf022f2-eed2-43dc-bb6d-930441ca2574.png)

[no public stuff]

**Comment by xpander69** [comment]
forwarded, closing for no public visibility
