### ISSUE TITLE
lockout bugged

### ISSUE THREAD

**Issue by bloodmasked** [WarEmu/WarBugs#19838]
I have only played destro today for several hours. Did not log order for 3+ hours ive played today.

But when I tried to log order to play because it had AAO, I was met with being locked to destro for 15 minutes.

The 90 minute lockout should have expired almost 2 hours ago already but hasn't.

**Comment by lilimx** [comment]
Hey,

did you do open or SCs? The lockout timer should start, when you enter the open RvR pool and atleast killed someone.

**Comment by bloodmasked** [comment]
Yes I did city in a 24man and we got hundreds of kills. So maybe the lockout wasn't started until after that?
