### ISSUE TITLE
Can't put talismans into armor or weapons.

### ISSUE THREAD

**Issue by mjkittredge** [WarEmu/WarBugs#19830]
**Expected behavior and actual behavior:** a single level 1 talisman unstacked, armor with open talisman socket, click talisman so it's on cursor, click armor, talisman is inserted into armor and character receives bonuses.

Actual behavior - click talisman, it's on cursor, click armor with talisman socket, receive error message "cannot equip an item that is stacked, please report to the bugtracker"
talisman will not socket

**Steps to reproduce the problem:** start new character, get armor with open talisman socket, get level 1 talisman, attempt to insert, fail, receive error message

![warbug](https://user-images.githubusercontent.com/100007511/154783307-9720cab5-839f-4b69-adf1-d09394378aa8.PNG)

**Comment by Rydiak** [comment]
Can you try putting the talisman in your armor when it is unequipped (in your backpack)?

**Comment by mjkittredge** [comment]
> Can you try putting the talisman in your armor when it is unequipped (in your backpack)?

I just figured out I have to shift right click on the item when it's in the backpack. Successfully enhanced my items with talismans. Sorry for the post, I didn't know what to do.

**Comment by Rydiak** [comment]
Good to hear! You should probably close this ticket then.

**Comment by lilimx** [comment]
okay! glad to hear!
