### ISSUE TITLE
Broken Tome Tactic Unlocks (not to be confused with disabled unlocks)

### ISSUE THREAD

**Issue by Yorobashi** [WarEmu/WarBugs#19840]
Troll Droppings & Barrel of Perfume are interactables in Troll Country which should drop items to be turned into NPCs for Giant Tome Tactic Shards. I am aware that the Tome Tactics are not currently implemented, however so far in doing the tome unlocks these are the first/only tome tactics which are incompletable.

A thread on the ROR forum from 2015, covering many of the tome tactic shard unlocks seems to indicate that these were working at one point, but have since been broken. I assume since they are disabled, not many people have been testing these things in recent months, so I wanted to bring attention to them, so that when the tome tactics are (re?)implimented devs will know these particular shards will need a little extra attention. :)

I'll compile all broken tome unlocks, related to tactics, here as I'm going to try to comb through the rest of the tome tactic shard unlocks to find all the broken ones this week, and make a complete list in one convenient place for whenever dev's are ready to focus on tome tactics. :)

![Gobgnar_001](https://user-images.githubusercontent.com/100258766/155267761-abc3c3e5-855a-4dfb-be57-fdca08e48e0b.jpg)
![Gobgnar_002](https://user-images.githubusercontent.com/100258766/155267768-5f0bcc3a-8883-46ab-a36d-bc8fd844d24b.jpg)
![Gobgnar_003](https://user-images.githubusercontent.com/100258766/155267770-0f36081a-693c-4e59-ad52-c849dadd5d0c.jpg)
![Gobgnar_004](https://user-images.githubusercontent.com/100258766/155267789-bf5c3896-d432-4891-9f50-bc6a3a0c9661.jpg)

**Comment by lilimx** [comment]
Hey,

please check the RoR wiki, the tome entries were reworked.
O'de Toilet: https://wiki.returnofreckoning.com/O%27de_Toilet
Gotta Go (Not Implemented) https://wiki.returnofreckoning.com/Gotta_Go

**Comment by Yorobashi** [comment]
appreciate the response Lil, but as title says, the post isn't about the tome tactics being disabled,, but about the interactables themselves being broken. ;)
