### ISSUE TITLE
100g lost blason guild no changes

### ISSUE THREAD

**Issue by Johnny78m** [WarEmu/WarBugs#19847]
Hello, 
I wanted to change my guilde blason for 100G. It took 10G but made only colour changes. I tried one more time, it took 100G this time but no changes at all. Help me please!

**Comment by lilimx** [comment]
Hey,

what's the lvl of your guild?

**Comment by Johnny78m** [comment]
hi, it's lvl 11

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Johnny78m** [comment]
> Hey,
> 
> what's the lvl of your guild?

lvl 11

**Comment by lilimx** [comment]
Hey,

Wargrimnir already answered on your thread here: https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=47579&p=504977#p504977

**Comment by Johnny78m** [comment]
Thank you very much.
