### ISSUE TITLE
Interface bug

### ISSUE THREAD

**Issue by Draakaris** [WarEmu/WarBugs#19848]
Hi, I have a big bug with my interface.
With one of my reroll, interface is blank: I can do nothing, no buttons, no actions...
Can someone have solutions?

Thanks
![interface](https://user-images.githubusercontent.com/100473340/155843268-036b0a1d-3bcf-4ebd-8103-ffc2eec39b1e.jpg)

**Comment by lilimx** [comment]
Hey,

that's not an issue for the bug tracker. 
Please join the RoR discord (https://www.returnofreckoning.com/forum/viewtopic.php?f=2&t=22044) and put your question in the #technical-advice channel.
