### ISSUE TITLE
Salvage Painmantle of the Duelist not receiving +melee critical chance item

### ISSUE THREAD

**Issue by Sh0tcalla** [WarEmu/WarBugs#19845]
![16457684596798120794988587326227](https://user-images.githubusercontent.com/100329161/155662199-9d29dc3b-cd77-46a6-99b8-5ec2f8003dc8.jpg)

**Expected behavior and actual behavior:**

When salvaging DoK Painmantle of the Duelist, level 28 pvp shoulder armor. Get option to either receive +strength, +Initiative, +weapon skill or +melee critical chance fragment.  When choose +melee crit chance should receive melee crit chance fragment

**Steps to reproduce the problem:**

Salvage the painmantle of the duelist shoulders, choose +melee critical chance item, and receive error: INVALID PRODUCT.  Receive no fragment.

**Testing Screenshots/Videos/Evidences (always needed):**

![16457684948504311101886882791750](https://user-images.githubusercontent.com/100329161/155662262-28c2c6be-33ff-4c48-a650-e4110b194a95.jpg)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
This issue is already known, so I will add your report to the related ticket.

**Comment by lilimx** [comment]
dublicate // related to #6909
