### ISSUE TITLE
Broken PQ - Siege of Bohsenfels

### ISSUE THREAD

**Issue by topdudes** [WarEmu/WarBugs#19849]
PQ is stuck on stage 1, only one Savage Champion spawned and no others are on the PQ.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Burnski_000](https://user-images.githubusercontent.com/81526782/155868616-ca947197-a41b-4baa-8fba-3bf972fba6e8.jpg)

**Comment by Lheana** [comment]
Works fine on dev, could not reproduce.
