### ISSUE TITLE
Chaos Chapter 4 Rally Master (Authun Skandsen) is missing the Rally Master icon

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#19856]
**Expected behavior and actual behavior:**

All Rally Masters have an icon over their head, similar to how NPCs with quest markers. The Chaos Chapter 4 Rally Master is missing his icon.

**Steps to reproduce the problem:**

Go to Chaos Chapte 4 and find the Rally Master named Authun Skandsen

**Testing Screenshots/Videos/Evidences (always needed):**

![Zomega_033](https://user-images.githubusercontent.com/60266177/156470662-221bda8d-3f82-4566-8613-11b58745ef88.jpg)

**Comment by Lheana** [comment]
It works for me.
