### ISSUE TITLE
[PQ] The Storm is Coming (chaos chapter 15 hard PQ in Chaos Wastes) - very low number of "Stormherd Gor" NPCs

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#19859]
**Expected behavior and actual behavior:**

Stage 1 of the PQ requires you to kill:

Stormherd Gors: 30
Stormherd Shamans: 10
Stormherd Ungors: 40

So you would expect the there to be roughly 3 Stormherd Gors for every 4 Stormherd Ungors. However, the ratio is the opposite of this, with there being about 1 Gor for every 4 Ungors, and only about 10-ish Gors in total. This makes completing stage 1 VERY tedious as you need to wait for a number of full Gor respawns (and the Gors are scattered everywhere), meanwhile completing the Shaman and Ungor requirements are fairly easy in comparison.

Possible fixes:

1) Increase the number of Gor spawns
2) Swap some Ungors for Gors to make the PQ completion process a bit smoother
3) Reduce the number of Gors that need to be killed

**Steps to reproduce the problem:**

Go to the PQ and compare the number of Gors to Ungors. Typically Gors seem to lead a small pack of Ungors, but the PQ kill requirements do not accurately reflect the difference in the quantity of Gor spawns compared to Ungors.

**Testing Screenshots/Videos/Evidences (always needed):**

Typical progress:

![Zomega_045](https://user-images.githubusercontent.com/60266177/156473406-7dd183d2-3bd5-4f3e-9c6e-196383fd45cc.jpg)

**Comment by Lheana** [comment]
This is not an issue, as it does not prevent from completing the PQ, it's more a QoL change. So I will close the ticket.
But note that the PQs will need to be reworked in the future.
