### ISSUE TITLE
[PQ] Tearing The Portal (chaos chapter 9 hard PQ in Troll Country) Stage 2: NPCs are missing their weapons

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#19857]
**Expected behavior and actual behavior:**

The "Chosen of Sysstos" that spawn on stage 2 are missing their weapons and just punch you. This probably isn't intended.

**Steps to reproduce the problem:**

Go to this PQ in Troll Country and progress it to stage 2.

**Testing Screenshots/Videos/Evidences (always needed):**

![Zomega_034](https://user-images.githubusercontent.com/60266177/156471180-e6ab5d48-a76c-4270-bca0-42b4dd472238.jpg)

**Comment by Lheana** [comment]
These NPCs did not have weapons on official, but indeed it seems weird, so they will wear some with next patch.

**Comment by lilimx** [comment]
fixed with patch 16/03/2022
