### ISSUE TITLE
Please help me with login ingame !

### ISSUE THREAD

**Issue by youpiff** [WarEmu/WarBugs#19853]
Please help me!

I cant go in game with my witch elf but i can go in game with my the rest characters. What is wrong? my witch elf lvl is 34 and my location is thunder mountain. when i click the play with witch elf then they load but nothing. I Uninstall the game but nothing change.

Thankyou for answers !

**Comment by Rydiak** [comment]
Post here if you haven't already: https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=46249
