### ISSUE TITLE
Cannot complete Daemon's Gate Quest 

### ISSUE THREAD

**Issue by Forzare** [WarEmu/WarBugs#19851]
**Daemon's Gate quest uncompletable**

**Seal of Sigmar is supposed to be placed on monestary gate.  Nothing happens**

**I attempted both gates and the actual doors of the building. I also tried moving the quest item to my hotbar to see if that would work:**

**Testing Screenshots/Videos/Evidences (always needed):**

![155930692-f8f7a8cc-cb5c-46b1-ac13-949ceba253dd](https://user-images.githubusercontent.com/23266079/155944632-09f72bdb-8c61-4859-854f-b2ec766f3c69.png)

**Comment by Lheana** [comment]
It works fine.
![Lheana_285](https://user-images.githubusercontent.com/11537611/158026191-20c0c136-8364-4e37-8090-3084806f1361.jpg)

**Comment by Svarty1** [comment]
Can confirm this is still broken 16/05/2023
![image](https://github.com/WarEmu/WarBugs/assets/113995896/e108938b-e903-427a-b6e1-8121f94793dd)

We tried both sets of gates (the one in the screenshot and the one to the north-west of the monastery) and the door of the building.

Ashling's guide says,
[67) Head south to the monastery gates, use the Seal of Sigmar in your quest inventory then return to Hartmann
and turn in Daemon's Gate. Accept the follow up.](https://xdocs.net/documents/ashling-warhammer-online-leveling-guide-1-40cm-5c5ddfc8165b9)
