### ISSUE TITLE
[PQ] Tower of the Elves (chaos chapter 14 hard PQ in High Pass): Hellcannon can be attacked by destro

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#19858]
**Expected behavior and actual behavior:**

Expected: There is a Hellcannon within the friendly Chaos forces. I - as a Chaos player on the same side - should not be able to attack/damage it.

Actual: I can attack/damage it.

**Steps to reproduce the problem:**

Go to the PQ on a destruction character and attack the Hellcannon.

**Testing Screenshots/Videos/Evidences (always needed):**

![Zomega_042](https://user-images.githubusercontent.com/60266177/156471620-dd748333-a017-4f7b-a9c8-bbc5cf183b1f.jpg)

**Comment by lilimx** [comment]
fixed with patch 16/03/2022
