### ISSUE TITLE
Napalm Grenade and Dissolving Mist

### ISSUE THREAD

**Issue by Lemonpie1** [WarEmu/WarBugs#1985]
Napalm grenade and the tactic throwing arm (25% extra range on grenadier abilities) don't work together the tooltip says 81ft range but when I throw it at max range nothing happens and the ability starts the 30 second cooldown. Similar to most of the ground target abilities if you throw them out of range they do nothing and a cooldown starts.

**Comment by Evildoor** [comment]
Same on Magus.
