### ISSUE TITLE
"Arixxis the Scout" NPC in Saphery is missing its name over its head

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#19862]
**Expected behavior and actual behavior:**

Expected: as a regular attackable NPC, "Arixxis the Scout"'s name should appear over the NPC model. An old screenshot confirming this can be found here: https://github.com/WarEmu/WarBugs/issues/3955

Actual: the name is missing. If you target the NPC then the name shows up in the target unit frames along with any extra add-ons such as Pure's HUD window (in screenshot below), but the name won't appear in the world over the NPC. I have turned on all name settings and it still didn't show.

**Steps to reproduce the problem:**

Find Arixxis the Scout in the south-east of Saphery (it moves about a lot). You won't be able to see the NPC's name over the model.

**Testing Screenshots/Videos/Evidences (always needed):**

All name settings turned on, still no name over Arixxis.

![Zomega_014](https://user-images.githubusercontent.com/60266177/156478601-c0a2a5a9-a346-45ee-b1d4-f234cdafe96e.jpg)

UI elements can detect the name if you target the NPC, but it still won't show up normally above the NPC's head. The "Pure" addon is in the screenshot below.

![arixxis](https://user-images.githubusercontent.com/60266177/156478810-32d9bf05-5cad-4ba2-a20c-8b4890555ed9.jpg)

**Comment by lilimx** [comment]
fixed with patch [10/09/2022]
