### ISSUE TITLE
[PQ] Fall of Grimclan (chaos chapter 15 hard PQ in Chaos Wastes) - Rocky Outcroppings can be attacked early.

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#19864]
**Expected behavior and actual behavior:**

Expected: the "Rocky Outcropping" items need to be destroyed in stage 2 of this PQ. Outside of stage 2 they should either not spawn at all, or be spawned but not attackable.

Actual: the "Rocky Outcropping" items also spawn during stage 1 and can be attacked. I cannot remember if they were also attackable during stages after stage 2 and when the PQ is resetting.

**Steps to reproduce the problem:**

Go to the PQ while it is in stage 1 and attack the "Rocky Outcropping" spawns.

**Testing Screenshots/Videos/Evidences (always needed):**

Sorry, forgot to take a screenshot of this one at the time :(

**Comment by Lheana** [comment]
As it does not prevent from completing the PQ because the GOs respawn, I close the ticket; maybe it will be modified later but it's not a real issue.
