### ISSUE TITLE
"Vanity Is Its Own Reward" quest requires you to kill a R26 lord "the hard way" in a tier 3 PQ

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#19865]
**Expected behavior and actual behavior:**

The epic quest "Vanity Is Its Own Reward" eventually sends you to each hard PQ in tier 2 and tier 3 chaos and you need to kill the boss at the end of each PQ to progress the quest.

This is fine for most of the PQs as the boss is a regular killable hero. However, on the "Tempest Horn" hard PQ (chaos chapter 13 in High Pass), the boss is not a hero but is in fact a rank 26 lord by the name of "Blooddrinker". This looks like a huge spike in difficulty compared to other hard PQs, but the objective of the PQ is not to kill the lord by fighting it to 0% health but instead to climb the steps and blow the horn which will destroy the boss.

However, killing the lord by blowing the horn will not update the the "Vanity Is Its Own Reward" quest. Instead, you have to kill the R26 lord the hard way, i.e. fight it properly and get the health down to 0. This is a huge spike in difficulty for an already difficult quest (especially if not doing it when overgeared at rank 40), and then the PQs you are sent to after this have you kill heroes again. This is the only Lord that needs killing in the PQ stage of the quest.

I am unsure if this was intended or if the quest should also trigger if you use the horn to destroy Blooddrinker so I'm putting it on the tracker. Feel free to close if intended, but if it is intended then I would urge you to reconsider this step in the quest chain. The R40 Chosen who came to help (not in the best gear but still had a shield at least) took a beating from this NPC, even with heals on it.

**Steps to reproduce the problem:**

Go to the "Tempest Horn" public quest in High Pass as destro, get to stage 4 which spawns the Bloodthirster, and then use the horn to complete the PQ. The "Vanity Is Its Own Reward" quest will not update with the "death" of the Bloodthirster.

**Testing Screenshots/Videos/Evidences (always needed):**

R26 lord: Blooddrinker

![Zomega_041](https://user-images.githubusercontent.com/60266177/156483951-dac0f451-062d-429a-a9e4-7488599e1dbc.jpg)

**Comment by Lheana** [comment]
This quest and the order version have been designed to be mirrored, and order also has to kill a PQ boss who is a lord. So this is intended and thus not an issue.
