### ISSUE TITLE
"Vanity Is Its Own Reward" quest rewards Chaos Black dye of a higher rarity

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#19866]
**Expected behavior and actual behavior:**

Expected: Chaos Black dye is usually "purple" rarity.

Actual: The Chaos Black dye reward from part of the the "Vanity Is Its Own Reward" quest chain is supposedly the same colour but has a higher rarity.

I am not sure why there are two rarities of the same dye and whether the quest reward is supposed to be a different colour.

**Testing Screenshots/Videos/Evidences (always needed):**

Normal Chaos Black Dye

![image](https://user-images.githubusercontent.com/60266177/156484677-586eae81-ccb7-4901-b702-2ed02d1ab945.png)

Extra rare version of the same dye from this quest:

![image](https://user-images.githubusercontent.com/60266177/156484746-5f486cf4-ca05-45ac-bfa0-1c63cdbf20d1.png)

**Comment by saupreusse** [comment]
normal chaos black dye: 188917
this chaos black dye: 129838176
There's two different entries in the db for this, and they differ more than only in rarity. I guess whoever created it, did so for a reason that's why I would say it's actually not a bug.

**Comment by Zomega-WAR** [comment]
In which case, is the new one supposed to be called Chaos Black Dye or something else?
