### ISSUE TITLE
[PQ] Lonely Tower (chaos chapter 15 hard PQ in Chaos Wastes) - not enough "Animated Dead" NPCs for stage 2

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#19867]
**Expected behavior and actual behavior:**

Expected: as PQs on stage 2 or later have a time limit, the full number of NPCs that need to be killed should spawn at once to prevent time-outs waiting for respawns. This particular PQ requires you to kill 30 "Undead Army" NPCs, which have the name "Animated Dead". Respawns can still occur in case the player is struggling to find all of the NPCs.

Actual: I could only find 22 spawns on stage 2 so had to wait for respawns to kill the final 8. Disclaimer: if I was being dumb and there are actually 30 spawned then please close this and let us never speak of it again.

**Steps to reproduce the problem:**

Get this PQ to stage 2 and count the number of "Animated Dead" NPCs.

**Testing Screenshots/Videos/Evidences (always needed):**

I only had a screenshot showing 22/30 kills which was after what I believe to be a full purge of the PQ's NPCs. It doesn't prove that there aren't 8 hiding somewhere. It's not a very useful screenshot.

**Comment by Lheana** [comment]
There are 30 spawns, you must have missed the ones on the isle.
