### ISSUE TITLE
Thunder Mountain Turret bug

### ISSUE THREAD

**Issue by orcfox** [WarEmu/WarBugs#19873]
Tested a couple other zones no issues.

Summoning a Engineer Turret in PVE areas of Thunder mountain seems to give it a improper location and not granting the upgrades buff, also instantly despawns when engage in combat. Using the Redeploy skill will fix its location and correct the bug, but cant get the normal construct turret skill to create a non bugged turret

Video Example: https://www.youtube.com/watch?v=yee0fvzqlmw

**Comment by Zomega-WAR** [comment]
https://github.com/WarEmu/WarBugs/issues/18872
https://github.com/WarEmu/WarBugs/issues/19099

**Comment by lilimx** [comment]
Hey,

Thank you for your report, but the issue ia already known and has been posted on our tracker. Zomega already linked both open tickets to your report, so im going close yours.
