### ISSUE TITLE
wilpower dok is bugged or just me ???

### ISSUE THREAD

**Issue by Hokseth** [WarEmu/WarBugs#19877]
I louse my wilpower, that hapen more time and when i look the score i'm alwys at last position...i do .getstats to see and in effect i louse with no sense most of power !!!!!!
![Hokseth_000](https://user-images.githubusercontent.com/101063966/156937745-745e96c8-9cb2-4185-b34b-47b0f696d5c5.jpg)
![Hokseth_001](https://user-images.githubusercontent.com/101063966/156937749-24e8e69b-bddf-41ad-89f3-bcfa4d084627.jpg)

when i relog that change all ..... 

![Hokseth_002](https://user-images.githubusercontent.com/101063966/156937766-1ce95780-445d-4d0e-bf2d-85e0762b996a.jpg)
![Hokseth_003](https://user-images.githubusercontent.com/101063966/156937770-f49f85df-d340-44d2-b207-85bfe3e8b05a.jpg)

that happens only with dok.... with zealot i have don't happens... so its is bugged ? i'm the only that i had this problem all time i logg ????

**Comment by Zomega-WAR** [comment]
https://github.com/WarEmu/WarBugs/issues/18534
