### ISSUE TITLE
Currencies didn't converted inside bank vault//mail box

### ISSUE THREAD

**Issue by sherlockandwatson** [WarEmu/WarBugs#19879]
Currencies didn't converted on my bank.

**Comment by Zomega-WAR** [comment]
Can confirm, emblems in my bank are still the old currency.

**Comment by sxe** [comment]
Currency in the mail (in bags and directly as mail attachments) also did net get converted.

**Comment by lilimx** [comment]
Hey,

Dalen is aware of it and on it

**Comment by lilimx** [comment]
In the meantime...please try this workaround (feedback always welcome here)

**the workaround for bank and mail currency is to move to main inventory and relog**

**Comment by sxe** [comment]
> In the meantime...please try this workaround (feedback always welcome here)
> 
> **the workaround for bank and mail currency is to move to main inventory and relog**

That worked!

**Comment by MaxHayman** [comment]
This is the solution. Closing.
