### ISSUE TITLE
Can't log in with my main char

### ISSUE THREAD

**Issue by Rsaint013** [WarEmu/WarBugs#19876]
I can log in with all my chars on first try, but "Dezmodo" my shaman,
 i try to log in go to loading screen "book" then comes back to main screen again, sometimes need to select server again try to log in and freezes the screen saying "Locating battles... and searching for allies " and the back screen changes to purple.
![1](https://user-images.githubusercontent.com/101045883/156921440-8c23856e-e698-4ab1-99b4-9d7aebbaf6e1.jpg)

I downloaded the game again with a fresh copy with no addons nothing and i have the same problems, in order to play with "Dezmodo". i need to keep trying and sometimes i can log on char but need to try a lot of times in order to play with "Dezmodo
![2](https://user-images.githubusercontent.com/101045883/156921549-da2938cc-ca26-45a1-85b9-885fb461ed98.jpg)
" screen stay like that after i try to log in, i need to select the server to get my chars back, if i don't select the server fast comes the purple screen again. 
![3](https://user-images.githubusercontent.com/101045883/156921636-14451470-9081-4cb5-b50f-2c893b022e78.jpg)
I try a new copy, i try to repair the old copy etc... nothing works to solve this problem, others chars log in fine with no issues, but this one have issues.

![4](https://user-images.githubusercontent.com/101045883/156921964-3ee66f5b-5a89-4b2a-b6a8-ab7881346a4b.jpg)
![5](https://user-images.githubusercontent.com/101045883/156921966-033fc7dc-ee4f-42d5-a6a7-8faa3319b59c.jpg)

**Comment by lilimx** [comment]
Hey,

please write your character name and guild in here: https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=46249
