### ISSUE TITLE
Blight Ambition Quest in Troll Country Chaos Chapter 8

### ISSUE THREAD

**Issue by Rocketman176** [WarEmu/WarBugs#19878]
Killing Corvak the Maimed does not give credit to complete the quest.

**Comment by lilimx** [comment]
Hey,

you were alone or in a grp?

**Comment by Rocketman176** [comment]
I was alone, but when I went back to the quest giver, it gave me the ability to complete the quest.

Sincerely, Robert NegreteStudent ID:1090987Oracle ID:OA301226246Apex ***@***.***

-----Original Message-----

**Comment by Lheana** [comment]
It does work.
![Anaehll_266](https://user-images.githubusercontent.com/11537611/158021358-0b9a7689-cb36-4ac6-972e-b7f7dc3d655b.jpg)
