### ISSUE TITLE
Influence Rewards not available after patch 9/3/2022 // Crypts and Tunnels

### ISSUE THREAD

**Issue by Kelreg-eng** [WarEmu/WarBugs#19887]
The influence bar is filled for Crypts and Tunnels but only the first reward is available at the rally master

**Comment by Schett** [comment]
I have same problem

![image](https://user-images.githubusercontent.com/17105698/157504589-19055e39-ccf3-484d-8a24-6ab3aea785d2.png)

![image](https://user-images.githubusercontent.com/17105698/157504703-6cab450d-4922-4c4d-b8f9-149441d08bbe.png)

![image](https://user-images.githubusercontent.com/17105698/157504767-02b8f6b1-b7b1-4906-97e1-ec6e7d729013.png)

**Comment by CrimsonFenris** [comment]
Got exact same issue ; my char was 1k influence from last reward (it was like 36k on 37k), now I cannot access to second and third tier rewards.

Furthermore, I dont know if it's a bug or intended, but when selecting the ring (last reward) from Crypts, the one rewarded from tunnels is not showing anymore ; I wonder why, knowing that you can buy 2 instances of each weapon (two from crypts + 2 from tunnels), why it's not possible to do the same with the ring as well (it will have multiple use, as backup in case of missclick, or a second ring to have alternative talisman slotted if needed).

See screenshots :
![Tanaryon_026](https://user-images.githubusercontent.com/40425011/157505182-83f09583-2a07-4884-bed5-31004bf8a09b.jpg)
![Tanaryon_027](https://user-images.githubusercontent.com/40425011/157505191-53a2c6be-747d-4d6d-bb2f-9c0a571c009e.jpg)

**Comment by dalen** [comment]
It's a bug. Fix is pending deploy.

**Comment by Arendollus80** [comment]
Ok, Just made another tracker. Delete if needed https://github.com/WarEmu/WarBugs/issues/19894
