### ISSUE TITLE
Cannot purchase gear from Oppressor vendor despite meeting all requirements. 

### ISSUE THREAD

**Issue by AnjaWP** [WarEmu/WarBugs#19883]
I cannot purchase any of the oppressor gear on my toon Dokteur despite having met all the previous unlock requirements and having enough warcrests and RR to buy the gear. When I log over to a different toon I am able to buy the gear. Seems to be a specific bug with my character. I have included screenshots of my armor unlocks,RR and warcrests just to show I should have everything required. 

![DoK armor unlocks](https://user-images.githubusercontent.com/90840431/157446085-7e312025-6c26-4686-a1cd-5e211f86c6e6.jpg)
![Warcrests](https://user-images.githubusercontent.com/90840431/157446092-f04d4584-5540-429d-b810-afd5f8d5bba1.jpg)
![RR rank](https://user-images.githubusercontent.com/90840431/157446100-b884e5ae-b07a-41ef-b7e8-c9ae59fbf31f.jpg)
.

**Comment by lilimx** [comment]
Hey,

does the issue still persists? There was a hotfix (10/3/2022)
