### ISSUE TITLE
Warband player slots not released after a palyer disconnects

### ISSUE THREAD

**Issue by sxe** [WarEmu/WarBugs#19884]
When a player disconnects while in a warband, his spot in the warband does not get freed up again, so no new players can be invited an the warband is stuck at 23 players (when it had 24 players before). It's not just 23 players tho, if multiple people disconnect the warband "shrinks" with each disconnect. We were stuck at 21 people before for example.

The only solution to fix this is creating a new warband. Changing the leader or the leader restarting the game does not fix it.

Cheers

**Comment by lilimx** [comment]
Maybe related to https://github.com/WarEmu/WarBugs/issues/19881

**Comment by dalen** [comment]
fixed after hotfix.
