### ISSUE TITLE
Partys broken after patch 9/3-22

### ISSUE THREAD

**Issue by Skibbas** [WarEmu/WarBugs#19881]
Joined a party as "donkeydorf", then relogged as "hotbastard" and both me and donkeydorf was still in the party with the other player.
He could only see "donkeydorf" in his party, even though that char was offline, and as "Hotbastard" I could see their party chat and locations etc. but not write in the chat.

So to be clear, I never joined the party as "Hotbastard", I was already "kinda in it" when I logged in.

![Hotbastard_000](https://user-images.githubusercontent.com/79228534/157412438-4d157f8d-75ea-4072-a6cd-53df4ef989d6.jpg)

**Comment by dalen** [comment]
This should be working now after hotfix
