### ISSUE TITLE
Scenario quests and turn-in NPC missing

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#19888]
**Expected behavior and actual behavior:**
Since I didn't see any message about this being removed in the patch notes, I assume this is a bug issue.

expected: scenario quests to remain
actual: they seem to be missing in Nordenwatch, as well as Kaige NPC in Altdorf

thanks

**Steps to reproduce the problem:**

**Comment by lilimx** [comment]
Hey,

that's no bug that's intended. A small gold reward has been added to scenario wins.

But intention is that you are free to roam RvR or do other quests between SCs
