### ISSUE TITLE
Stalker gear quest

### ISSUE THREAD

**Issue by Poseidon-Bluestorm** [WarEmu/WarBugs#1988]
2 bugs un ordre side :

The quest. "Kill 20 DoK" is buged. Stuck at 0 kill.

In the quest "head and shoulders" The black orc hero "Frugnuk Ironfang"  don't pop in badland. Some people have already kill it but yesterday we have wait for more than 2 hours without pop. No corpse of him on the floor.

**Comment by Sabacik** [comment]
Same with AM at destro side - not counting any kills (solo, party, WB)

**Comment by Abolition** [comment]
I think the Hero for the BW kill quest isn't spawning, either.

**Comment by Zhentarim** [comment]
Yes Felix Magnus won't respawn, there's people who have waited hours for him to respawn.

**Comment by Mezirah** [comment]
For some reason my dok kills started working tonight. 17/20 just like that. I didn't abandon or anything. It just kicked in.

**Comment by Evildoor** [comment]
That's because hotfixes were applied to Stalker quest lines, as said in patchnotes.
