### ISSUE TITLE
Twitch Drops Disappearing 10/03/22

### ISSUE THREAD

**Issue by acidicrain** [WarEmu/WarBugs#19896]
**Expected behavior and actual behavior:**
The twich drops in mail box do not disapper when opening the mail box

**Steps to reproduce the problem:**
collected two twich rewards 
claimed them on acidic
logged in as acidic
opend mail box
saw three mails
one a gold bag from yesterday
and two twich drops
opend the gold bag, at that time both twich drop mails dissapered

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Jolymphz** [comment]
Twitch drops automatically gets deleted upon opening a mail.
![getting mail](https://user-images.githubusercontent.com/101357053/157728809-017c9f29-28bd-45fe-8998-9ee0e2e1675f.PNG)

**Comment by Sapblatter** [comment]
I also tried to claim 2 twitch drops after the server came back up but when i clicked on them in the mailbox screen they disappeared.

**Comment by Disturbedst** [comment]
Same issue here. Went to open my twitch drops, upon opening the first drop all of them got delete including the one I opened without getting the rewards.

**Comment by GorkaBorka** [comment]
I tried to claim my 8 boxes earned for 2 days of watching streams (they all were claimed through website and were im my mail (charname - Belengol)), opened 1 blue and other boxes just disappeared from mail. 
Though after reloging 1 green box appeared in my inventory. 
Tried to relog a couple of times after this and nothing happened.

**Comment by Helgarm** [comment]
Two boxes just deleted themselves when I tried to open the first. And another two on a different character when I tried to close the mailbox without claiming. Nothing claimed for today, no problems yesterday. Seems that the delivery date is totally off, standing at over 19000 days ago.

**Comment by jnkilus** [comment]
Got 2 drops out of 4 in the mailbox today (Alyssen). One was instantaneously deleted. Only the green box remained. I couldn't take a screenshot as i tried to relog first, and nothing changed. But i can tell chatlog said i had 2 unopened mails. I proceeded to open the mail, saw 2 boxes for a second, then one just disappeared before my eyes. A new log said i only had 1 unopened mail.

Yesterday's drops were all good though.

**Comment by nigeleva** [comment]
I have drops 1-4 on 1 character and drop 1 on another character and were in my mail box but they all deleted when I tried to open the first one

**Comment by Kaelang** [comment]
When did you guys redeem them? Was it when the server was down for maintenance?

**Comment by acidicrain** [comment]
redemed them today after the server came up around 7 i claimed em and then loged in directly after server boot

**Comment by nigeleva** [comment]
I claimed then before the server went down and logged in when server came up again to get them -they were all in my inbox then were deleted when I opened the first one

**Comment by Sapblatter** [comment]
Character: Hinyeken
 I claimed the rewards from watching twitch while server was down for maintenance but i didn't redeemed the rewards to the characters name above until the server was back up from maintenance.

**Comment by Jolymphz** [comment]
Claimed drop #1 before the maintenance and Claimed #2 and #3 after the maintenance. Upon opening the mailbox after the maintenance #2 and #3 were there but no trace of #1 one wich was siting in the mailbox during the maintenance so it was already gone. Upon opening the mail to #3, all the mail just got deleted automatically. 
![getting mail](https://user-images.githubusercontent.com/101357053/157756048-95f34fc7-f33d-42e0-9dc5-a1f662a31947.PNG)

**Comment by JLP0103** [comment]
![IMG_0130](https://user-images.githubusercontent.com/101366995/157762605-f88f129f-9edc-45e8-a89f-69509f116e6d.jpg)
![IMG_0131](https://user-images.githubusercontent.com/101366995/157762644-4255062e-c4bb-480c-9c81-5deabc8aa7da.jpg)

**Comment by Txarlyman** [comment]
i've had the same issue, yesterday i claimed 4 Twitch drops and only got in mail, and today i claimed 4 more, there were 3 and i changed mail window tab to auction 2 of the droops desapeared from mail.

**Comment by Helgarm** [comment]
Claimed after maintenance.

**Comment by Txarlyman** [comment]
> Claimed after maintenance.

for me it didin't work, still missing 5 drops. maintenence didn't fix it

**Comment by elk76** [comment]
the same here:
I claimed 4 twitch drops this morning before the server went down
I checked the mailbox and all 4 gifts were there
I did not get them due to server shoutdown announcement  
I logged in when server came up again to get them - and 2 of 4 disappeared from my mailbox

**Comment by Jzlazuk** [comment]
During the 1st day of Twitch Drops, my 3rd drop didn't arrive to my mail at all, during the 2nd my third and fourth  Twitch Drop was deleted from mail after trying to open it (first one was before server shutdown and the second after the maintenence).

Character nick: Jlazz

**Comment by Helgarm** [comment]
> > Claimed after maintenance.
> 
> for me it didin't work, still missing 5 drops. maintenence didn't fix it

Yeah, doesn't work for me either. Just responding to the question about when I 'claimed' the items. Not when I tried to receive them. Which was, obviously, also after maintenance. FWIW.

**Comment by Lotusmox** [comment]
**Day 1 & Day 3** I was able to claim and receive all 4 drops each day in the mail fine.

**Day 2** I was able to claim all 4 drops but when opening the mail I only saw drops 1,2,3 (no #4)...drop #1 had a sent of 19000 days ago, like **JLP0103** above, and when I clicked to open it it deleted the mail.

Below is my drop history/times for the three days (strange the 4th drop shows DAY 2 for days 2&3):

![twitch drops](https://user-images.githubusercontent.com/101425983/157935457-4cdfce5d-4525-4828-9b7b-7c701b94fae1.PNG)

Hope any of this helps :)
Wurm -RoR (Wurmm-RP)

**Comment by Txarlyman** [comment]
Just an update i tryed that worked for me. After claiming the drops from Twitch, claim them one by one at RoR's web page, get them one by one from the mail, it seems that way it works, at least for me

**Comment by LordMort** [comment]
As an update to my previous post:
Topday, day 4 of the drops, I was able to claim drop #'s 1 - 3 without a problem. Drop # 4 on the other hand has issues.

The problem is that I cannot open the 4th drop. I was able to take it from my mail, and it shows up in my backpack alright, but when I try to open it, nothing happens.

The decay-timer appears to be working though, meaning that it will, most likely, be gone in less then 23 hours and 56 mins from the time of posting this message.

**Comment by Txarlyman** [comment]
with the hotfix from this morning i could open my arabian steed item, but the 1st drop from day 13th when i went to click it from the mail it disapeared

**Comment by AnjaWP** [comment]
Sadly all my drops disappeared upon opening mail even after hotfix. :( Can't really provide proof sadly as I didn't take before and after screenshots.

**Comment by CprWAR** [comment]
Today I claimed day 4 drop 4 yellow gift reward, opened it in mail but after 1 second it went puff! Dissapeared :(
