### ISSUE TITLE
Devastator chestpiece "+160 hit points every 4 seconds" not functional

### ISSUE THREAD

**Issue by laattori** [WarEmu/WarBugs#1989]
Devastator chest has a bonus of "+160 hit points every 4 seconds" for more than 1 class. At least for DoK it does not seem to do anything. Tested this in IC by letting npc hit me on my back and watching health bar closely. Health bar did not go up at any point and combat log also didn't register anything from the supposed bonus.
![deva](https://cloud.githubusercontent.com/assets/15817706/11423900/2c8adde4-9451-11e5-8932-a5baaba03661.png)

**Comment by Evildoor** [comment]
HP regen is not implemented yet, we'll use #1538 as a report for that, since it's the oldest one.
