### ISSUE TITLE
[Slayer] DOT skills + Fierce Might

### ISSUE THREAD

**Issue by nohh** [WarEmu/WarBugs#19893]
**Expected behavior and actual behavior:**
Critical bonus damage increased with each next tick of DOT skill with "Fierce Might" tactic.

![slayer_fm0](https://user-images.githubusercontent.com/19315739/157609864-8ee9a771-9ae7-4492-8fac-3bd273a4e084.png)

![slayer_fm1](https://user-images.githubusercontent.com/19315739/157609889-0579b452-01e7-4914-9e10-68ba709916a9.png)

Non crit damage is:

![slayer_fm3](https://user-images.githubusercontent.com/19315739/157612129-ccf22cbc-1643-4444-993a-4426412a399b.png)

Error message in chat:
![slayer_fm2](https://user-images.githubusercontent.com/19315739/157609896-920466a0-9a4a-4c31-b35a-3109f1c339c5.png)

**Steps to reproduce the problem:**
1. Sеt Fierce Might tactic.
2. Reduce hp to 15-20% (Can use "Reckless Gamble" skill on training dummies)
3. Use "Onslaught" skill on target, damage with critical hits will increase with each next tick.

Same issue with dot component of "Relentless Strike" skill, didnt test "Cleft in Twain" skill.
GetStat command does not show anything unusual.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Talladego** [comment]
Related to these
[#15925](https://github.com/WarEmu/WarBugs/issues/15925)
[#17261](https://github.com/WarEmu/WarBugs/issues/17261)
and explained in detail by Bejkon here:
[#19759](https://github.com/WarEmu/WarBugs/issues/19759#issuecomment-1021578786)

**Comment by Undrsiege** [comment]
This is being abused heavily.

**Comment by SecretsOTheP** [comment]
This is fixed for the next patch (might go in with next hotfix)

**Comment by SecretsOTheP** [comment]
This was patched live.

**Comment by ravezaar** [comment]
Iv tested Onslaught did 1300 ticks today for me so I wonder if this is still NOT fixed. I main Slayer and tho I barely ever use this Tactic I still want it to be correct.

**Comment by lilimx** [comment]
This ticket is closed, please open a new one with your issue.
