### ISSUE TITLE
BW/Sorc Mechanic Stacking Method

### ISSUE THREAD

**Issue by Sessyoukai** [WarEmu/WarBugs#19892]
Not a "new" bug, but I'm posting this method of mechanic stacking as per request of community management to hopefully help fix the issue.

**Expected behavior and actual behavior:**

Expected behavior: Dying from explosion/backlash while increasing bw/sorc mechanic should not result in the bonus +crit and +crit damage saved on your character after you respawn/resurrect and should reset back to 0.

Actual behavior: Dying from explosion/backlash while increasing mechanic will result in bonus +crit and +crit damage saved on your character depending on your ending combustion/dark magic (ie. it scales with the ending combustion you're at when you die - dying from backlash while increasing mechanic to 100 results in +35% crit and +100% crit damage saved after you respawn/resurrect). This allows a bw/sorc to stack mechanic bonus +crit and +crit damage to get +70% crit and +200% crit damage in total.

**Steps to reproduce the problem:**

Player must die from self explosion while using a skill to increase their mechanic by at least 20 and must not already be at 100 mechanic. So if you die from self explosion damage while increasing your mechanic from 40 to 60 or 80 to 100 then the resulting mechanic level (ie. 60 or 100) will be saved on your character after you revive. Easiest way to reproduce this bug is using city training dummies.

1. Bring yourself to 80 mechanic and equal to or less than 600 hp (600 damage is taken when exploding at 71 to 90 mechanic - hp can be lower to trigger exploding death to stack mechanic at a lower level but the easiest is going from 80 to 100 because of the higher self explosion damage).

2. Use a mechanic increasing skill that increases mechanic by 20 or more and die from the explosion damage. Best skills to use are insta-cast skills, but cast-bar skills also work. I tried testing with skills that increase mechanic by less than 20, but the result is not consistent.

3. If you do not die and are at 100 mechanic, use a skill to lower your mechanic (ie. scorched earth/surging pain or burnout/reckless gathering) and repeat step 2 until you die from explosion.

4. Respawn and receive bonus +crit and +crit damage from saved mechanic while your mechanic resets to 0 and can be increased again to 100 to stack more bonus crit.

This method is from my own testing after accidentally discovering this bug while doing dps testing on dummies. By following these steps, players can trigger this bug consistently.

**Testing Screenshots/Videos/Evidences (always needed):**

Screenshots already posted by previous bug reports showing result of mechanic stacking.

**Comment by nohh** [comment]
Can confirm.
![sorc215](https://user-images.githubusercontent.com/19315739/157608391-dbfb5c70-787c-4d61-b9d2-a266554ba0ef.png)

**Comment by Talladego** [comment]
This has been reported multiple times and I can confirm that the bug exists and the above procedure to reproduce the problem.
[#18744](https://github.com/WarEmu/WarBugs/issues/18744)
[#19239](https://github.com/WarEmu/WarBugs/issues/19239)
[#19730](https://github.com/WarEmu/WarBugs/issues/19730)

**Comment by GamesBondd** [comment]
> 

Thanks

**Comment by SecretsOTheP** [comment]
Should be fixed, pushed to master

**Comment by lilimx** [comment]
Fixed around the Patch from 9/03/2022
