### ISSUE TITLE
Pyramid of Settra Load In Causes Game Crash

### ISSUE THREAD

**Issue by dangerdoneky** [WarEmu/WarBugs#19890]
**Expected behavior and actual behavior:**
As described in title. Joined a Pyramid of Settra for testing. Game crashed while trying to load in.

**Steps to reproduce the problem:**
Join a Pyramid Scenario. Running client in English and 64 bit.

**Testing Screenshots/Videos/Evidences (always needed):**
No crash message. Will try to capture video

**Comment by dangerdoneky** [comment]
Currently also locked out of logging into this character due to the bug

**Comment by Tesq** [comment]
does that happened in full screen mode? if yes re try with windowed

**Comment by dangerdoneky** [comment]
> does that happened in full screen mode? if yes re try with windowed and let us know

This only occurred during the test for me. Once officially launched this issue seemed to be resolved
