### ISSUE TITLE
I cannot blacklist the pug sc

### ISSUE THREAD

**Issue by sherlockandwatson** [WarEmu/WarBugs#19898]
I cannot blacklist the pug sc.

**Comment by Rydiak** [comment]
Blacklist via what? Are you using an add-on? Can you provide any screenshots?

**Comment by sherlockandwatson** [comment]
![IMG_20220311_083711](https://user-images.githubusercontent.com/71406266/157823312-22ab0969-57dd-4bd6-b8d5-10ddcc5b7f97.jpg)

**Comment by sherlockandwatson** [comment]
The pug SC is nordenwatch

**Comment by Rydiak** [comment]
It appears you are using QueueQueuer, which isn't updated by the RoR devs. You might want to try finding a new version of it, or the new SC could be affecting it as well (see https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=47678&start=140#p505962).

**Comment by sherlockandwatson** [comment]
After hot fix it's working. Thx
