### ISSUE TITLE
Crypts and Tunnels influence rewards dissapeared.

### ISSUE THREAD

**Issue by Arendollus80** [WarEmu/WarBugs#19894]
After the recent patch 3/10/22 on my WL my 2cd and 3rd rank influence rewards disappeared from the NPC, despite having a maxed influence. As far as I can tell, there's no way to purchase them now.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Arendollus80** [comment]
EDIT: I see this is pending a fix, no need to reply.

**Comment by lilimx** [comment]
hey,

thanks for your ticket. So it's a dublicate of https://github.com/WarEmu/WarBugs/issues/19887
