### ISSUE TITLE
Crypts and Tunnels 

### ISSUE THREAD

**Issue by Cruella01** [WarEmu/WarBugs#19908]
Not sure if this is a just me thing, i did it today and got lockout for the kills but it didnt check off a boss in the quest. Which means i missed getting the stone. 

![image](https://user-images.githubusercontent.com/48467136/158015835-5a40111e-7614-461a-9f59-01e6199a6588.png)

**Comment by lilimx** [comment]
Hey,

is it only you in your group? Did you die during the fight?

**Comment by Cruella01** [comment]
Yes I think we wiped during it first go, or I ran out when we all wiped and went back in and started ressing. Not sure it was a pug and I didn't notice straight away sorry, so wasn't able to ask them.

**Comment by lilimx** [comment]
Hey,

uhm, this case is not really clear. It could be so many things (not bug related) why you are missed the kill.
If you are experience this issue in near future again, please open a new ticket. Be sure that:

- ...other players already have log out on this content. (check the lockout tab or do .lockouts)
- ...between your death and the death of the boss enemy isn't longer than 5 minutes. (you can see a message in your chat)
- ...that the boss reseted properly between wipes (yes, that could be a bug. Do a few screenshot and write what happened).
