### ISSUE TITLE
Campaign: Pairing not opening after Fort capture

### ISSUE THREAD

**Issue by Rubyeclipse-war** [WarEmu/WarBugs#19902]
Per the new system, the capture of one pairing should open the RvR pairing that was locked. 

Destruction just captured Shining Way, but the Dwarf/Greenskin pairing did not open, leaving only Praag for people to fight in.

Additionally, Destro's capture of Shining Way last night immediately Reset the Elf Pairing, and did not open any other pairings.

**Testing Screenshots/Videos/Evidences (always needed):**

![campaign](https://user-images.githubusercontent.com/60584990/157792009-e75cbace-cc10-487f-a51f-d3e8948a8bd0.png)

**Comment by dalen** [comment]
if the campaign points are equal it keeps one pairing of each faction locked. So if there's a city siege players can move through that fort to the enemy city.

**Comment by dalen** [comment]
after destro locked empire fort both the other pairings opened. As Destro was ahead on points and only they need a pairing locked.

![image](https://user-images.githubusercontent.com/7400/158010957-a486b1c9-a02e-4cd6-94c9-f97270300e33.png)
