### ISSUE TITLE
Karaz a Karak - Flight Deck stuck - Ridge Door doesnt work

### ISSUE THREAD

**Issue by KonnokMollom** [WarEmu/WarBugs#19909]
**Expected behavior and actual behavior:**
Actual:
You can fall down on the ledge in the Flight deck, but cant leave it through the Ridge door, so you end up stuck there.

Expected:
You should be able to leave the area through the Ridge Door

**Steps to reproduce the problem:**
Drop Down the Ledge on the flightdeck onto the surrounding balcony

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/44099864/158020245-51647708-1c72-42f0-bb03-5ec029aaae28.png)
![image](https://user-images.githubusercontent.com/44099864/158020352-83b815df-fdd4-4c6e-ad84-9f8a170d2843.png)

**Comment by saupreusse** [comment]
Fixed - added SmartAI door jump to the 4 flight deck doors (only leads inside).
Not a perfect fix, because these doors are keep doors with two jumps (one that leads inside/one that leads outside).

**Comment by MaxHayman** [comment]
Fixed
