### ISSUE TITLE
RF mechanic for Warrior Priests/DOK not working

### ISSUE THREAD

**Issue by OnamiWP** [WarEmu/WarBugs#19903]
After login server went down 3/20/22 @ ~`1030 MT US, Supplication as a way to regain Righteous Fury for Warrior Priests no longer works. This is game breaking for the WP class.

**Expected behavior and actual behavior:**
Supplication should refill RF for Warrior Priests

**Steps to reproduce the problem:**
Use RF via heals on WP
Supplicate -> No RF

**Testing Screenshots/Videos/Evidences (always needed):**
 https://youtu.be/ZfdC6FmhkUU

**Comment by AnjaWP** [comment]
Can confirm I have the same issue. 

Supplication is not generating any RF. 
All passive forms of RF generation is not working. +8 from book and Fueled Fury tactic does not work either. 
Only way to generate RF currently is through melee attacks (they still seem to work).

**Comment by DmitrievAlexander** [comment]
same with dok
https://www.youtube.com/watch?v=cS1veFRxTQ0

**Comment by Petricius** [comment]
My WP Maidenofsigmar seems bugged Similar to Dok of Slayer1912 and this thread.
I can not generate Righteous Fury (RF) passively by equipment - Tome of the Subjugator (8 RF by second) and also by
Supplication (30AP to 30RF by second). Only Smite (aoe attack) is working.
I uploaded video (about 27 MB) to my Gdisk - https://drive.google.com/file/d/1WrmXNg95EqDkmyUOUtxSpbuoPoRqqoUN/view?usp=sharing
NOTE - It is better to download the video, the online playback has low quality.

**Comment by Petricius** [comment]
It seems ok for me after server restart, So thx a lot.

**Comment by lilimx** [comment]
Fixed around the Patch from 9/03/2022
