### ISSUE TITLE
DoK Bugged after crashing.

### ISSUE THREAD

**Issue by Slayer1912** [WarEmu/WarBugs#19904]
Was playing on my DoK, after crashing i tried to log back in for several time.
Finally after logging in I have noticed that my DoK is not generating Soul Essence while in combat. It is not generating Soul Essence from chalice nor from skill (Blood Offering). Only way to get some Soul is from Essence Lash.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Hokseth** [comment]
m2 some issue 
![Hokseth_003](https://user-images.githubusercontent.com/101063966/157834894-09773fee-6705-4168-8df7-7f566e7e77b9.jpg)
![Hokseth_004](https://user-images.githubusercontent.com/101063966/157834909-c3a7c4f4-315d-4a3b-a2de-da7117d1f1f4.jpg)
the recarge don't run.... and it was neare to finish.... normally it fill up the cup
![Hokseth_005](https://user-images.githubusercontent.com/101063966/157835061-dd34d57e-ea45-45b9-abf7-24394bd3e161.jpg)
![Hokseth_006](https://user-images.githubusercontent.com/101063966/157835076-bcce665a-0f25-45c3-8752-d6a43cc5c6a0.jpg)
![Hokseth_007](https://user-images.githubusercontent.com/101063966/157835086-ea978481-c62b-43bd-80fe-4f5821282791.jpg)

**Comment by Rydiak** [comment]
Duplicate #19903
