### ISSUE TITLE
Instance Bosses don't have cd on their skills

### ISSUE THREAD

**Issue by Bafilan** [WarEmu/WarBugs#19916]
I did the Gunbad and BB/BE instances with a group today and the bosses don't have a cooldown on their skills

**Comment by Sethowl** [comment]
The second Boss on the left side in BS also seems bugged like he doesnt have cooldown on his skills

**Comment by saupreusse** [comment]
Same problem? https://github.com/WarEmu/WarBugs/issues/19917

**Comment by lilimx** [comment]
Hey,

same question, is it related to #19914 ?

**Comment by Sethowl** [comment]
The problem with the BS Boss is that he can spam his puddles and that they dont seem to disappear

**Comment by Kaelang** [comment]
Fix was added on March 13th patch. Please re-open if issue remains.
