### ISSUE TITLE
Magus pet falls through the world in Thunder Mountain

### ISSUE THREAD

**Issue by mbrymer** [WarEmu/WarBugs#19912]
**Expected behavior and actual behavior:**
Summoning a Magus pet in Thunder Mountain while in combat leads to it falling through the world and being dismissed for being too far away. It happens all the time to me when fighting in RvR in a variety of locations and appears to be related to doing it in combat while also being on a slope. I finally found a way to reliably reproduce it at the giant NPC next to the eastern BO

Possibly an issue for engi turrets as well. I don't play one so I wouldn't know

**Steps to reproduce the problem:**
- Roll a Magus
- Head to eastern BO in TM. Walk a bit NE of the BO towards the lava, aggro the giant NPC Roshk and stand on the ramp leading up to the BO
- Try to summon a pet. Observe that it falls through the world instantly or shortly after walking around for a few seconds

**Testing Screenshots:**
1. Immediately after summoning pet. Skill is on cooldown for 4 more seconds, pet can be seen to be sitting on the hillside
![Lamora_006](https://user-images.githubusercontent.com/59380114/158037478-f42ccbba-3d9a-4078-9103-c2464c0079fb.jpg)

2. 3 seconds later as can be observed from pet skill cooldown. After walking around a bit pet has fallen through the world and disappeared. Message in chat says it was dismissed for being too far away
![Lamora_007](https://user-images.githubusercontent.com/59380114/158037531-eacaec61-d4c3-4531-8bbe-183bb23a2532.jpg)

3. Extra picture showing pet below the world but not yet dismissed. LoyalPet addon displays location with the pet with the heart icon
![Lamora_002](https://user-images.githubusercontent.com/59380114/158037638-5faa991a-45bd-44e7-abb3-a693af8bdac4.jpg)

**Comment by Rydiak** [comment]
#18872

**Comment by mbrymer** [comment]
Whoops, didn't know there was already one for this. At least this gives another way to reproduce it?

**Comment by lilimx** [comment]
Hey,

yeah, there is already a ticket where I collect all weird Engi/Magus TM issues :D
