### ISSUE TITLE
Bilerot Burrows - The Bile Lord boss bug

### ISSUE THREAD

**Issue by Celianazaniah** [WarEmu/WarBugs#19914]
https://clips.twitch.tv/SparklingLongVelociraptorMoreCowbell-T70QqQ17BmCAb6lf

https://clips.twitch.tv/BumblingSpotlessPlumageBCWarrior-RGvLO58wTdG3Wmn6

we stayed and tried again and we had the same bug, impossible to finish the boss

//Lilim: I edited the ticket, because the link wasn't correctly added.

**Comment by saupreusse** [comment]
same problem - different boss:  https://github.com/WarEmu/WarBugs/issues/19916
