### ISSUE TITLE
Twitch drop 4 day 4 not working

### ISSUE THREAD

**Issue by rolando0432** [WarEmu/WarBugs#19910]
So i got my twitch drop 4 day 4 reward, i claimed it, i got a mail, i took it out from the mail, and now i have it in my inventory.
I wanted to open it, but it does nothing, i cant open it, i clicked ctrl+right click, didnt worked, i clicked right click, didnt worked, i cant open my twitch drop, i dont know why, because this happens to me first time... i send a screenshot of it that i have it, And im afraid that in 24 hours, it will dissapear and i couldn't open it
![Szutykosmo_001](https://user-images.githubusercontent.com/101335275/158022472-462723f6-6076-462c-8d3c-9fad6bed129a.jpg)

**Comment by rolando0432** [comment]
And im afraid that in 24 hours, it will dissapear and i couldn't open it

**Comment by gorwin** [comment]
we have the same problem in the order side

**Comment by lannrott** [comment]
Same problem here.
Got drop and bag cant be opened. 
Tried restarting game  / relogging but nothing helps.

**Comment by Varial6969** [comment]
Same here on Destro, opened rest of the boxes on my alts just fine and when it came to the Yellow box on my main, it just wont open.

**Comment by Karnahs** [comment]
Same problem here :/

**Comment by Antaiii** [comment]
Same issue here. Other bags worked fine, only last one, drop 4 day 4 cannot be opened

**Comment by Karnahs** [comment]
I  have read the  Patchnote, at the moment we cant opened it but it's probably available on Sunday morning.

**Comment by rolando0432** [comment]
> I have read the Patchnote, at the moment we cant opened it but it's probably available on Sunday morning.
nice

**Comment by lilimx** [comment]
Hey,

I labeled it. Let's see if the issue will be fix during the day.

**Comment by Petricius** [comment]
Same with me on Maidenofsigmar (order), it will disaper in 23 hours, so I hope, you can fix it on time :)
Thx.
![Maidenofsigmar_092](https://user-images.githubusercontent.com/17072092/158055437-fe84fb65-3ac1-4f52-8524-b9c93ed822d2.jpg)
.

**Comment by Petricius** [comment]
It works for me after restart. Thx a lot. GJ

**Comment by lilimx** [comment]
okay, I'll take your post as confirmation that the twitch drops are woking again.

If the issue still persist, please write as soon as possible a new entry here.
