### ISSUE TITLE
Missing War Crests

### ISSUE THREAD

**Issue by Sethowl** [WarEmu/WarBugs#19913]
Hello,
i dont have evidence for it (Screenshot) but i lost all my War Crests about 150 after the server restart today. Did anyone else have this problem or is there any way to get them back? I already tried reloading or restarting the game.

**Comment by lilimx** [comment]
Hey,

that's meh. Uhm Can you tell us a bit more about the whole situation?
When and where did you get the Crests?
The Crests were in your currency bag?
Anything weird after the restart, beside the loss?
Where and what did you right before the restart?

**Comment by Sethowl** [comment]
I got some of the crest i had before from scs and the rest mostly from bags and zone locks in rvr. I had all the crests in the top left spot in my currency bag and I was standing in front of the fort at restart. Except the loss of my war crests nothing weird happened after the restart.

**Comment by nordicocean7** [comment]
Update on War Crests..Mine have reappeared and disappeared again?..So maybe its a visual bug?

**Comment by lilimx** [comment]
@Sethowl 

hey,
there was a server crash with a rollback (did a little research)
![image](https://user-images.githubusercontent.com/23266079/159133457-600581f4-9bd9-4e4c-a42d-724b13a8b766.png)

So we can't do a refund, sorry.
