### ISSUE TITLE
Farty Squig Doesn't A Make Next Squig Summon Instant (with workaround)

### ISSUE THREAD

**Issue by nuitaran** [WarEmu/WarBugs#1991]
As stated, using farty squig does not make the next squig summon instant, however, if you jump during the cast it will go off.

**Comment by Evildoor** [comment]
We have #1619. Or is it different?

**Comment by nuitaran** [comment]
Ah I was reading on my phone and didn't see that it had been re-opened.  Thought it was closed back in october.
