### ISSUE TITLE
Look over There! detaunt bug

### ISSUE THREAD

**Issue by HokoBugTracker** [WarEmu/WarBugs#19924]
![02477](https://user-images.githubusercontent.com/60039912/158176972-c71d7c50-2de9-4dc0-9608-db560ff269a7.png)
"Look over there!" detaunt ability should end if the shaman attacks the detaunted target, but it doesn't dissappear even when fully dotted.

https://user-images.githubusercontent.com/60039912/158177371-692f735f-8e93-4329-976e-22c10a958337.mp4

watched a stream of a witch hunter and saw that happening to him fighting shamans over and over again, then reproduced it on the dummy in IC with my shaman.

**Comment by lilimx** [comment]
Hey,

Im a bit confused. You dot him and detaunt him, are you doing anything else after that?

**Comment by HokoBugTracker** [comment]
> Hey,
> 
> Im a bit confused. You dot him and detaunt him, are you doing anything else after that?

No, but the Detaunt should disappear as soon as the detaunted targets is being hit by the dots. It looks like the detaunt doesn't recognize the dots as attacks, it only ends after direct damage attacks or if you apply the base dot after detaunting. The life leech dot "Bleed for me" gets ignored completely.

**Comment by HokoBugTracker** [comment]
> Hey,
> 
> when dots were applied on a target and you detaunt, the dots just dealing 50% of the dmg and don't break the detaunt.

That makes no sense. Since when does your own detaunt reduce your outgoing damage? The detaunt should end immediately as soon as you attack the detaunted target (first damage tick of a dot)
