### ISSUE TITLE
Emblem of Nehekharan Assasins. Cannot equip an item that is stacked. 

### ISSUE THREAD

**Issue by TheWarXL** [WarEmu/WarBugs#19922]
Can't equip Emblem of Nehekharan Assasins (LOTD jewelry, melee power set)
Message in chat: Cannot equip an item that is stacked. Please report this to the bugtracker
![Screenshot_1](https://user-images.githubusercontent.com/53687034/158147184-3375b90f-4158-412e-9bd8-3b1919da93d1.png)
.

**Comment by NSKaneda** [comment]
Same for Emblem of Nehekharan Archers:

![Burszui_208](https://user-images.githubusercontent.com/22037960/159184707-f2c8ceb2-08eb-4e8a-ab61-6d9f64db26f2.jpg)

**Comment by lilimx** [comment]
fixed with patch 01/04/2022
