### ISSUE TITLE
weekly quest bugged : bringing change to altdorf 

### ISSUE THREAD

**Issue by badoglio170389** [WarEmu/WarBugs#19929]
https://i.imgur.com/reHovHX.png

we did a 8 men wb in city and didnt get it, probably because not all in the same party, shouldnt be like this actually siince says "in warband"

**Comment by badoglio170389** [comment]
worked fine today as 6 in group from guild, but still not for people out of it

**Comment by lilimx** [comment]
fixed with patch 01/04/2022
