### ISSUE TITLE
The Emperor's Mandate Epic quest

### ISSUE THREAD

**Issue by Franhaetta** [WarEmu/WarBugs#19936]
I have just completed step 9 of the quest chain and it doesn't let me complete and start next ste
![Knellict_010](https://user-images.githubusercontent.com/48967102/158691586-c2ae2bd6-72ed-4702-b251-404eedf3ecfb.jpg)

**Comment by lilimx** [comment]
Hey,

anything in your quest bag to proceed the quest?

**Comment by Franhaetta** [comment]
![Knellict_011](https://user-images.githubusercontent.com/48967102/158889896-e9982f6b-163b-4986-a8fd-d09d76f590a9.jpg)

anything there

**Comment by Franhaetta** [comment]
Any posible solution for now??

**Comment by Lheana** [comment]
It works fine for me
![Lheana_288](https://user-images.githubusercontent.com/11537611/163711576-2ecd3cd7-124b-4a5f-90ab-e09babfe15c1.jpg)
