### ISSUE TITLE
Server time

### ISSUE THREAD

**Issue by Schett** [WarEmu/WarBugs#19931]
Don't know if it was a intended change as there was a server change. But I make a bug tracker for it since it's confusing ppl right now when you try to organize something and some ppl say Altdorf time when they mean server time which is not the case anymore

This is the time you get when you do /time in game
![image](https://user-images.githubusercontent.com/17105698/158479183-af7bca4a-93b8-45b3-9f83-e3c562accc20.png)

This is the actual Altdorf time:
![image](https://user-images.githubusercontent.com/17105698/158479189-56b3ecc8-4443-40e5-8fda-b8b6773b8810.png)

Would it be possible to get the server time back to Altdorf time? to avoid confusion?

**Comment by lilimx** [comment]
Hey,

It's known since we switched the server to linux
