### ISSUE TITLE
Items getting deleted after sockeling a talisman

### ISSUE THREAD

**Issue by fabilie** [WarEmu/WarBugs#1993]
If u want to put a talisman into a item and type in /reloadui, the item getting deleted. you cannot find it anywhere

**Comment by Evildoor** [comment]
Exiting the game completely and starting it again does not helps?

**Comment by vove-RoR** [comment]
I think he means before clicking the "Fuse" button. Similar thing is described in #1119

**Comment by Evildoor** [comment]
Tested. #1119 is correct, it deletes talisman in such case. This issue is just like i imagined - if you do /reloadui and then log out and log in, the talisman item reappears and you can confirm(or cancel) it and get your item with talisman (or get them separately).
