### ISSUE TITLE
War crest wrong conversion after currency patch

### ISSUE THREAD

**Issue by Alucardsan** [WarEmu/WarBugs#19939]
hello,
this is a screenshot of my currency bag before the currency patch

![ror currency](https://user-images.githubusercontent.com/101787849/158746403-153fe0fd-d8bc-4d8f-abb3-2ba712340a1a.png)

lets do some mathematical !
for 1536 vanquisher token
if i transform them in to conqueror token 1536x5=7680
then i transform 7680 conqueror token in to officer token 7680x5=38400
one officer boots (before currency patch) cost 34 officer token so 38400/34=1129
so before patch with my 1536 vanquisher i can get 1129 officer boots
now after patch one officer boost cost 54 war crest so 1129 boots cost : 54x1129=60988 war crest !
why when i open my currency bag after patch i get only **6000** war crest for all my old currency ??
i think there is a big problem in your conversion old currencies to new currencies no ?
what happen if i was convert all my currencies in to officer before patch ?

**Comment by lilimx** [comment]
Hey,

Uhm is this a buf report or a question?

**Comment by Alucardsan** [comment]
hey, 
both, I think I had a bad result in gaining war crests, as you can see.

**Comment by bloodmasked** [comment]
i have the same problem, its not a bug since it was intended by the developers. unsure if it was an oversight.

basically we used to purchase low level items to salvage them into talismans, now we can't because its ridiculously expensive to do so compared to before.
