### ISSUE TITLE
New gear system with tome unlock bug

### ISSUE THREAD

**Issue by SashaKarton** [WarEmu/WarBugs#19947]
I have full conq set (even reequip it to be sure) but i still cant buy my last vanq piece cause "conq tome unlock". Relog didn't help also.

**Comment by lilimx** [comment]
Hey,

could you add a pic of your tome unlock and could you also check if there are any error messages when you try to buy stuff?

**Comment by SashaKarton** [comment]
Today bug fade. Ty fer help ;)


сб, 19 марта 2022 г., 19:56 lilimx ***@***.***>:
