### ISSUE TITLE
RvR Week 

### ISSUE THREAD

**Issue by Ristom81** [WarEmu/WarBugs#19941]
![Bhari_019](https://user-images.githubusercontent.com/26597777/158879395-103392c6-54ec-4153-8809-a87fecead6f8.jpg)

In the patch notes from 16.03. it says:
- The number of tasks required to reach first and second reward has been reduced.
I finished 3 out of 4 tasks without the forts, but that's not even enough for the second reward. Is that correct that the fort task is about one bar influence?

**Comment by Kaelang** [comment]
Fix was added on March 18th patch. Please re-open if issue remains.
