### ISSUE TITLE
NPC trader bug

### ISSUE THREAD

**Issue by Limp010186** [WarEmu/WarBugs#19945]
Hello, everyone,
I haven't been able to buy or sell anything for 3 or 4 hours. the NPC traders are bugged. The buy and sell window does not open. This is the case with every dealer! Can you help me?

https://ibb.co/JqkL0Mb

Thanks

/Lilim edit: made the link available for future reference

**Comment by Rydiak** [comment]
#19944

**Comment by bleifuss22** [comment]
I have same problem (Fr 22-03-18 **and** Sa 22-03-19). 
No char, any level, can interact with the merchants. Can´t buy or sell items, including keep merchants, wc merchants, city merchants, all! But, i can use the colour option at merchants!

**Comment by lilimx** [comment]
Hey,

dublicate of the post that Rydiak added
