### ISSUE TITLE
Ironbreaker Tactic : Sweet Revenge

### ISSUE THREAD

**Issue by Mountainz** [WarEmu/WarBugs#1994]
This tactic is not giving the +15% melee crit or reflecting on the character sheet.

**Comment by Evildoor** [comment]
What about .getstats?

**Comment by Mountainz** [comment]
Getstats is not reflecting the bonus to melee critical chance either.

**Comment by ozarmidrashim** [comment]
Tested on dev, works. Sweet Revenge isn't listed as giving melee critical chance, it's listed as giving general critical chance.
