### ISSUE TITLE
Selling items (part 2)

### ISSUE THREAD

**Issue by steoptus** [WarEmu/WarBugs#19944]
I can't open the window for trade items with NPC

![image](https://user-images.githubusercontent.com/51764381/159028578-1ae61311-cdd6-405b-b608-ffbbd585df96.png)

**Comment by steoptus** [comment]
I may have the solution: I passed my game in English

I think the French traduction is bugged

**Comment by lilimx** [comment]
fixed with patch 01/04/2022
