### ISSUE TITLE
(Altdorf) Weird victory celebration 

### ISSUE THREAD

**Issue by Celianazaniah** [WarEmu/WarBugs#19940]
https://clips.twitch.tv/IronicTangentialSpaghettiDoggo-YnnOHu3TIOC_ERA9

this is what happened to us in city phase 3

//Lilim edit: edited the post to make the link available

**Comment by lilimx** [comment]
Hey,

how long was the freeze? what happened after the clip ended?

**Comment by Celianazaniah** [comment]
we couldn't use army recall or any spell we had to use the war report

**Comment by Solganis** [comment]
Happened to us too

**Comment by lilimx** [comment]
fixed with patch 01/04/2022
