### ISSUE TITLE
Could not claim twitch rewards on site

### ISSUE THREAD

**Issue by pcpbear** [WarEmu/WarBugs#19942]
**Expected behavior and actual behavior:** I could not claim my twitch drop rewards on the RoR website. I would click the unclaimed and it would take me to the characters screen and would not show my characters name despite being linked. The first 2 rewards I could claim but the last 20 I could not.

**Testing Screenshots/Videos/Evidences (always needed):** 
![Screenshot (8)](https://user-images.githubusercontent.com/101384041/158911137-06c84914-0fa7-4fab-b4a6-c3886e413fdf.png)
![Screenshot (5)](https://user-images.githubusercontent.com/101384041/158910951-88a62fe0-5dcb-4d5f-863e-422bb8e22205.png)

**Comment by GamesBondd** [comment]
Closing this ticket as the account linked doesn't have any characters and thus has been mistakenly linked instead of the client account.
