### ISSUE TITLE
I can't sell my items to NPCs 

### ISSUE THREAD

**Issue by Ladycaska** [WarEmu/WarBugs#19957]
**Expected behavior and actual behavior:**
When i click on the button fro sell my items nothing happens

**Steps to reproduce the problem:**
Click on any npc merchant, click on button for sell items. Nothing happens.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Solganis** [comment]
https://github.com/WarEmu/WarBugs/issues/19944 ? @Ladycaska

**Comment by lilimx** [comment]
Ah damn Smartphone

**Comment by lilimx** [comment]
Hey,

are you playing with a language package?

**Comment by Ladycaska** [comment]
Ty for your help guys!
I have changed the language to english and solved the problem  :)

**Comment by lilimx** [comment]
Nice 👍
