### ISSUE TITLE
Public Quest T1 , T2 & T3 Stage

### ISSUE THREAD

**Issue by Hawkhart** [WarEmu/WarBugs#1995]
Hello !
I'm a fan of public quest and i saw something all the public quest are avaible at stage 1 but after in stage 2 the next doesn't work is it normal or i'm bad ? ^^'

**Comment by Evildoor** [comment]
Public Quests are not implemented yet.

**Comment by Hawkhart** [comment]
Oh nevermind ^^ thanks for the answer , now waiting for the day when public quest are full avaible :)
