### ISSUE TITLE
Conquest of Caledor: Order Keep Lord giving old currency for quest

### ISSUE THREAD

**Issue by Rubyeclipse-war** [WarEmu/WarBugs#19955]
**Expected behavior and actual behavior:**
Order's Caledor Keep Lord in the Eastern Keep is providing the _Conquest of Caledor_ quest, but the quest still grants Conqueror Medallions. 

**Steps to reproduce the problem:**
1. Swing by the Caledor Eastern keep as Order.

**Testing Screenshots/Videos/Evidences (always needed):**
![caledor bug 1](https://user-images.githubusercontent.com/60584990/159447367-7eea6342-15ae-48bf-ba64-8e2b0a22d8c8.png)
![Caledor Bug 2](https://user-images.githubusercontent.com/60584990/159447374-bbbcfe23-fe8e-4033-ad97-6714a07619d6.png)

(Did a search and don't think this one is on the tracker yet; apologies if it's a duplicate!)

**Comment by gittoaster** [comment]
Same for the quests Conquest of the Chaos Wastes
:P

**Comment by Kaelang** [comment]
This is fixed.
