### ISSUE TITLE
have to relog to change recipes - Talisman making

### ISSUE THREAD

**Issue by slave1974** [WarEmu/WarBugs#1996]
Once one ingredient runs out, I have to relog the game to add new ingredients to craft.  Clearing doesn't work either

**Comment by Evildoor** [comment]
I've not run into this in similar situations, so it's likely that there is a condition of some kind. Tested just now - everything worked.

**Comment by slave1974** [comment]
Several others in game said the same thing, but for me, I have to relog

**Comment by ropuch** [comment]
I've noticed that it is most likely to bug when you try to click Fuse! when one of the ingredients runs out, Afair similar bug is with apothecary as well.

**Comment by Tesq** [comment]
i confirm this when you mass craft it seems to bug in this way and you need every time to re log

**Comment by Luth-RoR** [comment]
Should be fixed, as the server checks for legit mats in the crafting slots now, so that there is no difference between the client and the server slots anymore.
