### ISSUE TITLE
Minor text bug: English typo in Squig Bits

### ISSUE THREAD

**Issue by Rubyeclipse-war** [WarEmu/WarBugs#19976]
Very minor text bug in the English description for Squig Bits (butchering ingredient):

Current text reads: "... can be used to _multiplie_ potions." 

Just a quick fix in English, which should be: "... can be used to _multiply_ potions." 

This occurs in the level 200 and 175 Squig Bits, and I believe likely extends down to the lower tiers. 

**Testing Screenshots/Videos/Evidences (always needed):**

![squig text bug](https://user-images.githubusercontent.com/60584990/160545942-87d6f12c-c7d3-4e69-a91c-ce99c9a49e26.png)

This is a tiny one, but flagging it just in case it's an easy fix. Thanks!

**Comment by lilimx** [comment]
fixed with patch 30/04/2022
