### ISSUE TITLE
Bolstering Enchantment and Heaven's Blade do not work together

### ISSUE THREAD

**Issue by RealTrecia** [WarEmu/WarBugs#19972]
**Expected behavior and actual behavior:** (Expected) Bolstering Enchantment and Heaven's Blade should affect the entire party
(Actual) Only one of the effects will affect the party, whichever was applied first. (If Heaven's Blades was applied before equipping Bolstering Enchantments only Heaven's Blade will affect the group and Bolstering Enchantments will not and Vice-versa.)

Note: Bother affects will always affect the Swordmaster, so a group member is required in order to reproduce results.

**Steps to reproduce the problem:**
(1) Apply Bolstering Enchantments
(2) Apply Heaven's Blade
(3) Attack until Heaven's Blade triggers
Note : Must have a party member with you else no difference will be seen 

**Testing Screenshots/Videos/Evidences (always needed):**

How the buffs should interact when a blade triggers
![As Intended](https://user-images.githubusercontent.com/102432487/160253233-7bf6f07a-04c8-4d8f-ae9a-22a96cafc0f8.png)
How the buffs interact when Heaven's Blade is triggered (No blade buff)
![Not as Intended](https://user-images.githubusercontent.com/102432487/160253255-e958ffa4-2615-4c62-8e7a-44e4734604b1.png)

Note that game critical and game breaking bugs may award a manticore/griffon (realm specific) at the leads discretion however, asking for one instantly disqualifies you from this reward.
-->

**Comment by lilimx** [comment]
Hey,

thank you for for your ticket. It's already reported.

**Comment by lilimx** [comment]
dublicate #18811
