### ISSUE TITLE
LOTD/Twitch mount unable to dismount when carrying siegeweapon

### ISSUE THREAD

**Issue by BomblingTV** [WarEmu/WarBugs#19971]
When a player is dragging the Ram, a canon or holding a balista they can mounted walk up to the door and dismount to place a ram.

With the Twitch drop arabian donkey mount you cant dismount in this situation, same goes for holding any keep-siege weaponery.

(havnt tried with the 250 golden scarap mount but expecting it will be same there)

**Comment by MaxHayman** [comment]
Should be fixed please reopen if not
