### ISSUE TITLE
Quest "Breaking and Entering" from Oleif Mundenson doesn't 'exist'?

### ISSUE THREAD

**Issue by VonEpic** [WarEmu/WarBugs#19979]
Quest "Breaking and Entering", offered by Oleif Mundenson at Goblin's Head Coaching Inn in Talabecland, which I have had in my book for years probably, no longer shows up in quest log, nor is any part of it interactable at the Mud Flats area. Essentially, quest exists in a fugue state? Wondering how to remove it so I don't see the grey quest icon or if it can be re-instated so I can quit/complete it normally.

**Comment by lilimx** [comment]
Hey,

I don't get it. When it's in your book, you also should be able to delete it.

Otherwise post pictures as evidences.

**Comment by VonEpic** [comment]
It's not in my book, but the quest is "active" AT the NPC.

**Comment by VonEpic** [comment]
![Olef stands 1](https://user-images.githubusercontent.com/31397093/162614127-aacf30bc-b938-4b19-80df-0e3b72200dd3.png)
![Olef stands 2](https://user-images.githubusercontent.com/31397093/162614130-3fb68a90-7ef0-4148-a8ee-4aed155bac74.png)
![Olef stands 3](https://user-images.githubusercontent.com/31397093/162614133-077e29e0-be55-46ba-a663-672cb09484cb.png)

**Comment by lilimx** [comment]
Hey,

sorry for the late respond....uhm and it's even not on the second page?

**Comment by VonEpic** [comment]
Nope, I sorted alphabetically to show it's not showing up. But i've swiped pages and it's not there, at least not named correctly. I will check each entry right now.

**Comment by lilimx** [comment]
Hey,

what happend when you click on the title of the quest inside the "quest tracker"?

**Comment by VonEpic** [comment]
Checking now.

**Comment by lilimx** [comment]
Hey,

okay :D

**Comment by Kaelang** [comment]
I have reason to believe this is related to the other issues we recently had with quest books / quests not showing. The quest does work and I've just tested it. Is in quest book, there are requirements and a turn in.
