### ISSUE TITLE
Don't Bawk quest bug

### ISSUE THREAD

**Issue by Prestmark** [WarEmu/WarBugs#19970]
A quest in Avelorn called "Don't Bawk" rewards the player with just over 60K exp if the player scouts the 4 different BOs in T1 elf zone (Blighted Isle / Chrace.). Upon completion of the quest, it rewards 0 exp, with the error message:

"You somehow gained an amount of xp larger than the system allows (82240). This gain has been prevented."

Thank you.

**Comment by lilimx** [comment]
dublicate of #19918
