### ISSUE TITLE
No Invader ToK with mixed Gear !

### ISSUE THREAD

**Issue by Ceowulf** [WarEmu/WarBugs#19981]
**Expected behavior and actual behavior:**

I get Invader`s Ward but no Invader ToK with mixed Gear !
In the Picture you can see I have mixed the whole Gear what should be needed for Invader ToK !
Do I really have to buy whole Invader Armory for fortress weapon ?

Can`t buy fortress weapon without ToK but can buy  SoV.

**Steps to reproduce the problem:**

Buy and use mixed gear -> you get no Invader ToK...

**Testing Screenshots/Videos/Evidences (always needed):**

![invader2](https://user-images.githubusercontent.com/102256203/161259301-9bd835be-08c0-44c5-ae7d-ca71d6efa9c6.JPG)

![invader3](https://user-images.githubusercontent.com/102256203/161259331-abb42f28-c755-4f05-ace3-5b941d070f00.JPG)

![invader1](https://user-images.githubusercontent.com/102256203/161259758-93c238aa-7de1-4b07-9191-5d621c15f2ec.JPG)

**Comment by Zomega-WAR** [comment]
You have the Invader Ward. That ward is obtained by equipping Invader-level sets (Invader, Triumphant and Victorious) in each of the 5 main slots. You can see this by going to your TOK, then armory, then Invader Ward to see what the requirements are.

"The Invader" TOK unlock is given by getting the full set of actual Invader armor (not the ring), much like "The Vanquisher" TOK unlock requires the full set of Vanquisher armour, "The Conqueror" TOK unlock needs the full set of Conqueror armor, and so on. The TOK unlock is actually a title of that name. If you do not have access to the player title named "The Invader" then you do not have that unlock.

Fortress weapons explicitly say that they need "The Invader" TOK unlock. They do not say that they need the "Invader Ward". This is why mixing and matching sets won't get you access to Fortress weapons.

The weapons are linked to getting that specific armour set. Even in the patch notes it only references higher armour sets being unlocked with Wards, not weapons.

**Comment by geheimrat** [comment]
Same thing on Souv:

I have full 5 invader wards (some triumph and some inv) and can buy souv. But i cannot equip souv, because it says: tome entry is missing full invader unlock. It does not say u need the 5 wards.

At the moment we have the situation, that u can buy souv with 5 inv/triumph wards, but u can only equip those souv items after buying all inv pieces. Why do i have to buy the missing inv pieces (which are cheaper than triumph i already have) just to wear souv? So 2000 crests just wasted.

Is it intended or a bug?

**Comment by lilimx** [comment]
@geheimrat 

Hey,

let's see if the fix will resolve both issues....if not, please feel free to open a new ticket.

**Comment by geheimrat** [comment]
Thx alot for reply!

**Comment by sxe** [comment]
Could someone please clearly state what the actual fix is and if this is being worked on? Before the patch today I was told it's already on the dev server, so we should get a fix soon. Since it's still not fixed I would like some clarification to the question: Will it be possible to buy fortress weapons with the invader ward?

Thanks

**Comment by lilimx** [comment]
![image](https://user-images.githubusercontent.com/23266079/163246725-4b606c4e-b88c-47f2-ac27-44ecb12d94cf.png)

**Comment by Ceowulf** [comment]
I could exchange the fortress weapon for about 2 weeks, I can also buy SOV but could not equip... 

1, so fortress weapon should be work or worked
2, SOV gear you need whole invader armor set meassge, so could not wear SOV as @gehimrat written !

**Comment by lilimx** [comment]
Hey,

Dalen is currently on vacation...I will inform you guys asap

**Comment by gats69** [comment]
Hello, i have the same problem :
I unlocked the **invider ward** (2 Invader +3 Triumphant) , 
I bought a **sovereign piece**, but I can't equip it, why?
Plz help me, I spent  3500 WC and I'm blocked now :(

salutations.

**Comment by gats69** [comment]
Hi, do ou fix the invider ward for souverain for the next patch ?

**Comment by gats69** [comment]
Testing Screenshots/Videos/Evidences 

![image](https://user-images.githubusercontent.com/10851323/165939195-754d0777-7937-48d5-aab4-3cb922ea0058.png)

**Comment by GCH72** [comment]
Hi, similar problem here :
I have full Triumphant gear, Invader ward is unlocked in ToK, i buy all Sovereign/Warlord parts, but i can't equip it !
Game message is :
"You don't have required Tome of Knowledge entry to equip this item: Completed Invader's Armor Set"

Please can you fix this in the next patch.

**Comment by gats69** [comment]
FIX PENDING, means it would be fix on next patch ?

Yours faithfully.

**Comment by GCH72** [comment]
Problem was fixed for me with last patch, thanks !

**Comment by Kaelang** [comment]
Fix was added. Please re-open if issue remains.
