### ISSUE TITLE
t3 Saphery and Avelorn Influence

### ISSUE THREAD

**Issue by Munsnit** [WarEmu/WarBugs#19989]
T3 Saphery and Avelorn Influence rewards aren't showing up in the Tome of Knowledge or the Rally Master when selecting your influence rewards. It also is maxing out your influence bar, saying you have achieved all 3 ticks of the influence.

**Expected behavior:**
Normal influence gain, being able to access what the rewards are in the ToK or the Rally Master within Tier 3 Saphery and Avelorn.

**Actual behavior:**
Blank spots in the influence reward spots in ToK and the Rally Master, and a full influence bar. I also believe handing in resources doesn't give you any influence.

**Steps to reproduce the problem:**
N/A

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/61488923/161375585-70785b37-2e6d-4e2a-a868-dc7145ce5a89.png)
![image](https://user-images.githubusercontent.com/61488923/161375610-f0dc0437-2533-4b60-8e67-dfb416dd2383.png)

**Comment by saupreusse** [comment]
Fixed in next patch

**Comment by lilimx** [comment]
fixed with patch 13/04/2022
