### ISSUE TITLE
Thanquol's Stand: Ratnarok event task mismatch

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#19986]
**Expected behavior and actual behavior:**

Flavour text says you need to complete the scenario 15 times, but the actual progress tracker is out of 10.

![image](https://user-images.githubusercontent.com/60266177/161350101-3d58e655-37fe-4422-bb0d-dc6b633cdf8e.png)

**Comment by MaxHayman** [comment]
Fixed
