### ISSUE TITLE
Thanquol's Stand: Ratnarok - "IndexOutOfRangeExpection" said in chat by NPC "Stormvermin"

### ISSUE THREAD

**Issue by Solganis** [WarEmu/WarBugs#19985]
**Expected behavior:**
No Exception said in chat by NPC Stormvermin

**Actual behavior:**
Exception said in chat by NPC Stormvermin
![image](https://user-images.githubusercontent.com/44605445/161348963-c947ed63-2a43-4ab5-b438-7bdaaa3ed9d9.png)

**Steps to reproduce the problem:**
1) 1 person alive in party,
2) play SC

**Comment by SecretsOTheP** [comment]
Upcoming hotfix will fix this

**Comment by MaxHayman** [comment]
Fixed
