### ISSUE TITLE
Getting opposite faction item drops from RvR\SC\Dungeons\PQs 

### ISSUE THREAD

**Issue by Solganis** [WarEmu/WarBugs#19988]
**Expected behavior:**
Getting items only for my Faction

**Actual behavior:**
Getting opposite Faction items too

**Steps to reproduce the problem:**
1) Do any sort of content - RvR, SC, Dungeonds, PQs
2) Getting all sort of item drops - Chaos, Dwarf, Orc, etc.

Related - https://github.com/WarEmu/WarBugs/issues/19984

**Comment by MaxHayman** [comment]
Fixed
