### ISSUE TITLE
Bolster applying in Norsca/Nordland outside of RvR

### ISSUE THREAD

**Issue by TVBrowntown** [WarEmu/WarBugs#19980]
**Expected behavior and actual behavior:**

When zoning into T1 Nordland/Norsca Bolster should not be applied unless you enter the lakes. Furthermore, Bolster shouldnb't even apply to a level 40 entering Nordland/Norsca RvR anyway.

**Steps to reproduce the problem:**

Be destro
Fly to Norsca/Nordland
You will be "bolstered"

**Testing Screenshots/Videos/Evidences (always needed):**

![Squibblegut_004](https://user-images.githubusercontent.com/32625383/161179924-dd5c4514-2659-45ff-98fe-0936844aabd9.jpg)

**Comment by lilimx** [comment]
Hey,

What do you mean? That even lvl 40 get bolstered or not debolstered. And what happens to t1 low lvl players. Do you mean they are even bolstered outside the RvR pool?

**Comment by TVBrowntown** [comment]
Sorry poor wording from me. The bolster effect should immediately turn a level 40 into a chicken but instead the effect is applied without being made into a chicken. This is probably from not being flagged for RvR.

I haven't checked what a low level t1 will experience but will create a character and see what happens but this can be easily checked by creating a character and zoning into Norsca/Nordland.

Regardless, the bolster effect should not occur outside of RvR. In the screenshot my level 40 character is at a PQ far away from the RvR lake - with bolster applying throughout the entire zone.

Simply; characters are being bolstered outside of the RvR pool.

**Comment by Zomega-WAR** [comment]
T1 has had full debolster to rank 10 for a long time now. I think it started with the event to launch the new cities and has not been removed.

**Comment by lilimx** [comment]
Hey,

the debolster was left on intentionally....Only the 40s Lairs have to be adjust to lvl 40 again (some of them are working). So technically it's no bug...but I will poke Max with this ticket.

**Comment by TVBrowntown** [comment]
It's on purpose? Why should still be active? Now as a 40 I can't use my mounts and a majority of my abilities to go back and do PQs to complete the "Vanity Is It's Own Reward" quest as the PQs are too difficult solo when bolstered down.

**Comment by MaxHayman** [comment]
This was done to allow players to go back and play with friends at lower levels. Any level 40 content i.e. lairs should remove the debolster. If a lair doesn't please remove debolster when it should please open a seperate ticket.
