### ISSUE TITLE
Guild search button greyed out until /reload

### ISSUE THREAD

**Issue by Solganis** [WarEmu/WarBugs#19996]
**Expected behavior:**
Button active without /reload

**Actual behavior:**
Button active only after /reload

**Steps to reproduce the problem:**
1) Log-in,
2) Open "Guild search window"

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/44605445/161589584-9913a086-fbf0-4f4f-98ef-234dcd8853c4.png)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. This issue has been already reported.
