### ISSUE TITLE
Encroaching Darkness missing Pater Allard

### ISSUE THREAD

**Issue by WarhammerAM** [WarEmu/WarBugs#19998]
**Expected behavior and actual behavior:**
Find Pater Allard to complete the quest line

What happens:
Unable to find Pater Allard in the quest area, there is no npc in that area

**Steps to reproduce the problem:**
Do the Encroaching Darkness questline

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

found him...so no bug

**Comment by WarhammerAM** [comment]
Where is he? I check the the coast where the quest says he is, but did not see him.

**Comment by lilimx** [comment]
You've checked the ground?
