### ISSUE TITLE
Talabecland

### ISSUE THREAD

**Issue by Areanda** [WarEmu/WarBugs#2000]
For the destro side we can use the mountain to get acces inside the keep without even attacking the Door. Meaning we can attack the defenders of the keep in their backs. While they dont expect this

**Comment by Zhentarim** [comment]
Yes, there is a fence that is meant to block people from getting in behind. But you can just jump over the side of it and get in by being mounted.

**Comment by DanaBloodkiss** [comment]
Fixed in next.
