### ISSUE TITLE
Caledor - Wrath's Resolve Keep; NPC can not die

### ISSUE THREAD

**Issue by bisbalien** [WarEmu/WarBugs#20000]
![no dmg npc](https://user-images.githubusercontent.com/86349663/162229466-be0bb202-1d93-4ce9-9fbd-8e2a14ce735b.jpg)

**Comment by Kaelang** [comment]
![image](https://user-images.githubusercontent.com/60117106/175836551-e05d127c-fdd7-45d2-b212-778f624cb524.png)
NPC is killable.
