### ISSUE TITLE
Caledor - Quest "Heralds of Defeat"

### ISSUE THREAD

**Issue by VonEpic** [WarEmu/WarBugs#20001]
Captivity Crystal does not work on Tulier Firebreather. 
Rest of quest requirements can be met, but when I attempt to use quest item "Captivity Crystal" while targeting and/or near Tulier Firebreather, nothing happens.

Caledor quest "Heralds of Defeat" location is north east of Destruction PQ "Malyros' Rest."

**Comment by Lheana** [comment]
That's because you don't have to use it on Tulier Firebreather. Read well the quest.
I've tested, this quest works well.
