### ISSUE TITLE
Quest: Trouble for Perthar

### ISSUE THREAD

**Issue by VonEpic** [WarEmu/WarBugs#20009]
Picked up Star of Isha, quest suggest bringing forged letter and star to Morridan Darkrage, but no actual quest point or conversation available at Morrigan (roughly 22k, 41k in Avelorn iirc)
![Uploading Trouble for Perthar.png…]()

**Comment by lilimx** [comment]
Hey,

uhm, for some reason your pic won't upload.

**Comment by VonEpic** [comment]
![No Quest](https://user-images.githubusercontent.com/31397093/162637140-3124f739-cf70-4b2a-b480-b676b2732bc0.png)

**Comment by VonEpic** [comment]
![Trouble for Perthar](https://user-images.githubusercontent.com/31397093/162637163-e63986cd-9679-4f0b-84df-7fd941a7c7dc.png)

**Comment by MaxHayman** [comment]
Seems to work fine

https://www.youtube.com/watch?v=K-8ffosRvBk

Can you try right clicking the body. Please reopen if that is not the case.
