### ISSUE TITLE
Quest "The Ever Ancient"

### ISSUE THREAD

**Issue by VonEpic** [WarEmu/WarBugs#20008]
No requirements present, no way to track where to turn in.
![Nollarr](https://user-images.githubusercontent.com/31397093/162616935-b7de77f9-901f-4950-9de5-90041530c6f9.png)

**Comment by Rubyeclipse-war** [comment]
This has been fixed and will go live in a future patch. :)

**Comment by lilimx** [comment]
fixed with patch [10/09/2022]
