### ISSUE TITLE
Quest "A Simple Request"

### ISSUE THREAD

**Issue by VonEpic** [WarEmu/WarBugs#20012]
Chieftan Vanik apparently has two quests called "A Simple Request" one of which seems to be working, one seems to be missing (like all my recent posts.) It speaks of descending into Morr's Maze to find some wine. Quest does not show up in quest log, tracker, or on map, etc. New quest was picked up today (10 April 22)

![A Simple Request](https://user-images.githubusercontent.com/31397093/162641171-e2779529-07c5-4ef4-abd9-4a18d0f30d42.png)

**Comment by Kaelang** [comment]
Just did the quest on the dev server and it's working fine. In quest log, on the tracker and on the map.
