### ISSUE TITLE
missing quests

### ISSUE THREAD

**Issue by Tagaruk** [WarEmu/WarBugs#2001]
strange thing happend once i logged in a few days ago: all my quests were gone, the quest list was empty and i could retake the quests i've already done. i waited for the server restart, but i didnt change a thing. also, the armory says i've played over 14 years :P 
http://www.returnofreckoning.com/armory.php?character_id=72212&character_name=Taggarson
maybe its related somehow (5434 days showed the same time all my quests were gone)

**Comment by Tagaruk** [comment]
fyi it happened again - cleared all my quest log, time played by armory now up to 6762 days

**Comment by oncearound** [comment]
this just happened to me this morning when logging in. war crashed to desktop upon loading. when i restarted it worked fine. i logged into my witch elf and all quests were missing from her tome. i was able to pick them all up again no problem, I could even do quest lines that were finished and should not be able to be picked up again.

**Comment by Skutrug** [comment]
Well tonight I had the exact same issue - Dinged 35 in the RvR lakes and bing - all my quests disappeared, including all the completed Stalker quests. I also now have officially played for 233577 days, 4 hrs and 58 minutes... Shouldn't I get a reward for playing over 64 years on RoR :-)

**Comment by Luth-RoR** [comment]
From https://github.com/WarEmu/WarBugs/issues/9256

>tome of knowledge quest tab is empty, but i can't take any quest. **it says that journal is full.**

**Comment by Ghostcrowler** [comment]
same issue here since friday im without quests and with Played 5849d 7h 4m 6s

**Comment by sioding** [comment]
#10661

**Comment by Khazardor** [comment]
Same issue... lost all my quest log. Got to do all the Beastlord grinding again to get my Beast Tokens ;(
Is this issue beeing looked at? Since Nov 2015 and no solution? Many people are having the same problem constantly.

**Comment by Afterlife92** [comment]
Got all my quests reseted again on my wp this time (I didn't crash during loading screen, had some issues with my internet connection and crashed 3 times in row to character screen). My time played on armory changed from 3 days to 17875 days.

**Comment by gittoaster** [comment]
I've played 26300 days according to my Tome.

**Comment by MaxHayman** [comment]
The played time issue has been fixed for new characters.
