### ISSUE TITLE
Weekly RVR Event - Defense of Keep not registering. 

### ISSUE THREAD

**Issue by caerfinon** [WarEmu/WarBugs#20014]
Was fighting in Praag today on Order. 
We successfully defended  the southern Garrison  against a siege with both outer and inner doors down. 
We successfully sieged Garrison of Skulls and locked the zone. 

In the Weekly RVR event I only received credit for the keep capture. The Keep defense did not register. 

![image](https://user-images.githubusercontent.com/74055317/162797711-a2f85350-a08c-47df-b56c-c2eeff8aa719.png)

**Comment by SecretsOTheP** [comment]
Fixed, for next patch

**Comment by caerfinon** [comment]
thanks for  looking into it.

**Comment by lilimx** [comment]
fixed with patch 13/04/2022
