### ISSUE TITLE
Triumphant wound bonus

### ISSUE THREAD

**Issue by Falkvor** [WarEmu/WarBugs#20015]
The triumphant 3 piece bonus is not aplying. I bought the helm (got ironmantle and warclasp replica from before). When I put the helm on, I get the wounds in the character skill. But my health points drops. Looks like it is the bonus that arent aplying.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. But I really need a few pictures. You can drag and drop them here to upload them.

**Comment by exotlv** [comment]
Update: It works after client restart

**Comment by Falkvor** [comment]
It somehow got fixed. I crashed. And after that it worked as it should.
________________________________
Fra: lilimx ***@***.***>
Sendt: mandag 11. april 2022 21:48
Til: WarEmu/WarBugs ***@***.***>
Kopi: Falkvor ***@***.***>; Author ***@***.***>
Emne: Re: [WarEmu/WarBugs] Triumphant wound bonus (Issue #20015)


Hey,

thank you for your ticket. But I really need a few pictures. You can drag and drop them here to upload them.
