### ISSUE TITLE
Characters becoming sporadically unable to log in

### ISSUE THREAD

**Issue by MerrimanZajac** [WarEmu/WarBugs#20013]
One of my characters, for quite some time, has periodically been unable to log in. Usually, though not always, what happens is there is a travel transition, I get disconnected and put back to the login screen, and then I am unable to log back in. I have tried restarting the client at that point, also re-entering the Martyr's Square server, and it doesn't do anything. I also did a repair of the client via the launcher's repair function, and I deleted the character's user folder as was recommended to me in another thread here in the bugtracker. So, when this problem happens, what I'll do is play one of my other characters for an hour or so, and then usually the problem character (Beldruuin) will be able to log in again, and the problem might not resurface for another day or so. Sometimes it resurfaces a few hours later, but usually not.

My other character, Grimfor, never had this problem until today.

A clue I might have is that the problem started happening with Grimfor when I got disconnected while transitioning out of Gunbad. I was unable to log him back in, and since then Grimfor has been randomly unable to log in.

What actually occurs on screen is as follows. When the client launches, I can either select the character from my lineup, or it will be already selected. I click "play". It starts the loading process, and shows the book image which shows the name of the zone I'm loading in to. It attempts to load for a while. It then returns me back to the character screen with my character already selected. If I wait 15 or so seconds and do nothing, the background imagery of the selection screen goes to a solid color, and I no longer have options to select a server or a character, so I have to quit the client. I've attached a picture of what this looks like.

<img width="960" alt="RoR Error 1" src="https://user-images.githubusercontent.com/86537742/162797700-ab35d209-bc6c-4928-a3bb-6c7939f7067a.png">

**Comment by lilimx** [comment]
Hey,

actually I would send you to this thread: https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=46249
I guess you already wrote your name and guild in there?

**Comment by MerrimanZajac** [comment]
I hadn't done it because it looked like a slightly different problem, looked like that thread was for permanently stuck characters maybe. So I wouldn't want a GM to have to constantly unstick me. But I can post there if that seems like the right thing to do.

**Comment by lilimx** [comment]
Hey,

yeah Im a bit confused, You've written: "One of my characters, for quite some time, has periodically been unable to log in"
When are you able to login back? After a server restart?

**Comment by MerrimanZajac** [comment]
Usually when it happens I won't be able to get in even after trying several times in a row, but sometimes it will let me in after a couple of tries. So usually what I'll do is wait about an hour, or until another day, and I  can get back in. It doesn't seem to have anything to do with a server restart.

**Comment by MerrimanZajac** [comment]
I might have figured it out. I wanted to give it a few days to see if the problem recurs. So far it hasn't. Someone in the advice channel suggested I clear a lot of quests in my quest log a while back, saying they thought it was related to this problem. I did so on both characters, and it hasn't happened since on either character. They both had 3+ full book faces of quests, and come to think of it, the problem started on Grimfor after I went into Gunbad and took all the quests there, which is quite a lot, like 15+. I since trimmed down the quests on both characters to something like 1 full book face of quests.

**Comment by lilimx** [comment]
Hey,

please read these two guides:
(Viny FPS guide) https://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=19867#p218143

(Reduce Lag, Crashes, Disconects - Complete list of things you can do) https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=20075&sid=f1d9ec9fb237bc0fbf0e3dfcbe13d3f5

**Comment by sioding** [comment]
We have also (again) a problem with big (over 400 members) guilds here. I have now fixed a lot of ppl with kicking them from their guilds. They were instantly able to login again.

**Comment by MaxHayman** [comment]
Should be fixed. Please reopen if not.
