### ISSUE TITLE
Unable to enter character after barber changes

### ISSUE THREAD

**Issue by zgrzycistopa** [WarEmu/WarBugs#20029]
Cannot access one of my characters. No issue on other characters- just on single one after did barber changes.
Name: Srebrnobrody 

**Steps to reproduce the problem:**
After "Loading interface" Screen i get normal loading window (with the art background) and afterwards 3 possible things happening:
1) goes back to characters choice screen but no option to change character to others and then after i hit "Play" again i get blue background with remainign buttons I had saying "Locating battles... Searching for allies..." = and thats it, nothing else happens
2) crashes the game
3) gets stuck on "art" loading screen

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

write your character name and your guild in here: https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=46249&start=450
A handsome GM or Mr.Bond are going to unstuck your character asap
