### ISSUE TITLE
Triumphant Gem disappeared

### ISSUE THREAD

**Issue by dharissa123** [WarEmu/WarBugs#20023]
Hi,

Could you please look into this issue.  Item was purchased at full 10k crest and no refund.  Greatly appreciate the help.  Thanks

**Comment by lilimx** [comment]
Hey,

your a Magus player?

**Comment by dharissa123** [comment]
> Hey,
> 
> you're a Sorc player? And I need the name of your Character.

Yes I am.  Name is dharissa.  Thank you

**Comment by lilimx** [comment]
Hey,

okay I will note your name. Max will going to send some Mails back actually. So check your mailbox the next day.

**Comment by lilimx** [comment]
Lilim Note // 2 weeks label; so I can check after the ticket

**Comment by dharissa123** [comment]
Ok Thank you.  I will be on the look out and confirm upon receiving

**Comment by dharissa123** [comment]
Hi again,

Thank you for working this issue out for me.  So i received the refund of 999 crest, however what I made this purchase was 9999 crest.  Could you please review purchase logs made the day when patch was implemented so you can make purchase for the triumphant gem for 9999 crest.  Thanks again

![Screenshot_1](https://user-images.githubusercontent.com/74745658/163723013-8e95d8b7-8d1b-4108-af3e-01e2930a6b13.png)
t

**Comment by lilimx** [comment]
Hey,

I've poked Max about that.

**Comment by dharissa123** [comment]
Thanks agin

**Comment by dharissa123** [comment]
hi, 

I am not understand why this was closed.  This issue was never resolved.  It is truly heart breaking that an item that cost 9999 crest was taking away and not refunded.  I've dedicated many hours in my 2 and 1/2 year tenure to enjoy and gear my toons only to have this outcome.   This gives me another reason not to play anymore.

**Comment by lilimx** [comment]
Hey,

I've poked Max again. But a nice advice....instead to say "This gives me another reason not to play anymore" just wait....

**Comment by dharissa123** [comment]
Thank you Gamesbond.  Sorry I was frustrated at the moment. But overall you guys do a great job and bringing the game back to life and doing it for free.   I am truly grateful you and the dev team did.  Thank you again

**Comment by lilimx** [comment]
Hey,

So I close it now. If you have still issues regarding to your ticket, poke me on the RoR Discord.

**Comment by Sabacik** [comment]
Thank you very much!

**Comment by Sabacik** [comment]
Hi! Did you have any luck with it?

**Comment by Sabacik** [comment]
@lilimx is there any update on it? as I still have not received nor jewellery nor war crests spent :(

**Comment by lilimx** [comment]
Hey,

sorry for the late responds....I already got smashed by another player because he haven't got the refund. It's an unique issue, so I thought there was a special log, so all in all only 1 dude got his refund back....sorry, I can't do any related to your issue :(
