### ISSUE TITLE
Eastern Wyvern Event > Back reward

### ISSUE THREAD

**Issue by Dottina** [WarEmu/WarBugs#20028]
My reward, the back, isn't shown in my bag, and not when I've equipped it.

https://postimg.cc/QF7KJY5w

https://postimg.cc/SJ2nm1ZR

**Comment by Dottina** [comment]
Fix is Good :) <3

**Comment by GamesBondd** [comment]
> Fix is Good :) <3

Thanks for your report and update ^_^
