### ISSUE TITLE
[Magus] Lasting Chaos Tactic bugged "5th Tactic Slot :D"

### ISSUE THREAD

**Issue by AmakusaROR** [WarEmu/WarBugs#20027]
**Expected behavior and actual behavior:** 
You can Summon your Demon with Lasting Chaos Tactic, then swap the tactic set and still benefit from it. Its like playing with 5 Tactics.

**Steps to reproduce the problem:**
Slot the tactic to one tactic set, summon deamon and change to the other tactic set and still keep the lasting chaos tactic.

**Testing Screenshots/Videos/Evidences (always needed): Its easy to reproduce so i dont think one is needed.**

_Lilim Note: Edited the ticket, so I can read it better_

https://user-images.githubusercontent.com/61085160/163603241-fb0967aa-1e43-4f7d-8f62-1b90e8f361f7.mp4

**Comment by lilimx** [comment]
Hey,

I guess it affected other tactics aswell. 
Could you please check if the issue persist after a /rel or after switch zones?

**Comment by AmakusaROR** [comment]
Hey,

still works after a /rel or zone switch.
Solution would be to despawn the pet when you switch the tactic sets.

**Comment by lilimx** [comment]
also related #14931
