### ISSUE TITLE
[MARA/SW] Tactics: Feeding on Fear/Bullseye 

### ISSUE THREAD

**Issue by AmakusaROR** [WarEmu/WarBugs#20030]
**Expected behavior and actual behavior: 

SW gets a flat +10% chance to be critically hit.
MARA gets a 10% Value from his chance to be critically hit
The Downside of the Tactic ofc, the +20% Crit part works fine.
Visual bug?**

**Steps to reproduce the problem: Slot the tactics and hit a dummy**
![mara1](https://user-images.githubusercontent.com/61085160/163634761-59f6097f-8c92-4a3e-8eec-065d2e86e62e.png)
![mara2](https://user-images.githubusercontent.com/61085160/163634764-315390a8-784f-4374-8bbc-fd895afd3471.png)
![sw1](https://user-images.githubusercontent.com/61085160/163634765-3b1faa6b-d3a2-44a3-b03e-a6155a549425.png)
![sw2](https://user-images.githubusercontent.com/61085160/163634766-726df7f9-0b1f-4cae-9e8e-56c13f0d63cb.png)

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

uhm, firstly....please one issue per ticket. secondly, do not trust the paperdoll tooltip. 
Use `.getstats` instead.

**Comment by AmakusaROR** [comment]
How about no? I wont report anything now.
Ty for your time.

**Comment by lilimx** [comment]
kkkk thx bye
