### ISSUE TITLE
Finish 'em faster (Choppa) 

### ISSUE THREAD

**Issue by Zhentarim** [WarEmu/WarBugs#2003]
This tactic is supposed to reduce the cooldown of exhaustive blows by 25% but instead it's increasing the cooldown by 25%. I assume it's the same thing for the ability Chop fasta and the tactic Red goes faster who are also about reducing cooldowns.

**Comment by Mazadun** [comment]
https://youtu.be/ewUamr4F80w
theres is a video
0.17 without tactic
0.50 with tactic

**Comment by ozarmidrashim** [comment]
Don't assume - Chop Fasta! modifies the base cooldown stat and Red goes faster! is a linear reduction instead of a multiplicative one.
