### ISSUE TITLE
Black orc tactic No choppin me

### ISSUE THREAD

**Issue by Raznuts** [WarEmu/WarBugs#20032]
**Expected behavior and actual behavior: The buff to toughness should last 20s as per description. Reality is it buffs for 4s. The WS from Follow me lead works as intended. The problem is the tougness buff is implemented in the buff of the magic reduction in Saving me hide, which lasts only 4s.

**Steps to reproduce the problem: Tested out in warband spamming the buff, tested in group on the training constructs.

**Testing Screenshots/Videos/Evidences (always needed):**

![Test](https://user-images.githubusercontent.com/19312741/163728505-37f96ca0-f37b-4347-82ab-c18b199e6dfc.jpg)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. This issue is already known.
I'll close and add your report to the related one.

**Comment by lilimx** [comment]
dublicate #19069
