### ISSUE TITLE
Guild Mount Missing / Duplication Issues

### ISSUE THREAD

**Issue by Rubyeclipse-war** [WarEmu/WarBugs#20037]
**Expected behavior and actual behavior:**
Some of the Permanent Guild Rank 37 mounts are missing / duplicated for High Elves and Empire. List below:

**High Elves:**
- Blue Roan Elven Charger is listed twice
- Strawberry Roan Elven Charger is missing entirely

**Empire:**
- Golden Dark Bay Warhorse is listed twice

**Steps to reproduce the problem:**
- Log into any Guild Rank 37 character, check vendor in Sigmar's Hammer

**Testing Screenshots/Videos/Evidences (always needed):**
![blue roan bug](https://user-images.githubusercontent.com/60584990/164025108-853769a8-2cbc-4e16-a903-bca9f6d07bbe.png)
![empire bug](https://user-images.githubusercontent.com/60584990/164025216-b130aad3-01b8-4fec-9362-34b88ae0ba9c.png)
![strawberry roan](https://user-images.githubusercontent.com/60584990/164025392-1c0e9ee5-f29b-4152-90ec-a2ac084b979c.png)

**Comment by lilimx** [comment]
Fixed with patch 17/08/2022
