### ISSUE TITLE
Event Eastern Wyvern 40 lvl reward absent

### ISSUE THREAD

**Issue by nohh** [WarEmu/WarBugs#20031]
40 level elite reward is absent for sorcs
![sorc_no40](https://user-images.githubusercontent.com/19315739/163674971-e63c42b7-1984-41db-89b6-56af5b75566e.jpg)

**Comment by lilimx** [comment]
Hey,

what's your current level?

**Comment by nohh** [comment]
40

сб, 16 апр. 2022 г., 16:01 lilimx ***@***.***>:

**Comment by Enotikkk** [comment]
Chosen-same here. 40/80.
![Enott_078](https://user-images.githubusercontent.com/103887894/163716273-2e8ca868-bf64-4adc-99d6-56dac3207414.jpg)

**Comment by lilimx** [comment]
Oki, thx

**Comment by MaxHayman** [comment]
Fixed
