### ISSUE TITLE
Guild Heraldry emblem no. 261 dont work

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#20045]
Instead emblem no. 261 it shows no. 1

**Comment by lilimx** [comment]
hey,

what lvl is your guild?

**Comment by MKorin** [comment]
Lvl 15, name De facto

**Comment by lilimx** [comment]
Hey,

your has to be lvl 20 to show the emblem.

![image](https://user-images.githubusercontent.com/23266079/164943174-8cc4079e-f053-400d-85f1-90b1c733cfa5.png)
