### ISSUE TITLE
City Siege: Invincible lords 

### ISSUE THREAD

**Issue by Rebiff** [WarEmu/WarBugs#20044]
At the 10 minute remaining mark of the 3rd stage all 8 champs on both sides despawn and the lords are supposed to fight each other with the assistance of the players. Currently they do not fight each other and stay out of combat, this has happened to me 2 cities in a row where the lords cannot be killed because theyre stuck resetting their health even if you try to full burst. (even when the opposing side is afk in spawn you cant outdamage the lords OOC self heal) 

**Steps to reproduce the problem:**
Do a city, dont kill all champs, focus lord at 10minutes.

**Testing Screenshots/Videos/Evidences (always needed):**
Here is a link to a video i made showcasing lords not attacking / regening through all damage.

https://youtu.be/TWzP-ND4-tY

**Comment by Rebiff** [comment]
a week later, 3cities in a row now ;_; 
![unknown](https://user-images.githubusercontent.com/91923176/165827664-faea1943-88ba-4d95-8b87-53230e4e7cf9.png)

**Comment by GamesBondd** [comment]
> a week later, 3cities in a row now ;_; ![unknown](https://user-images.githubusercontent.com/91923176/165827664-faea1943-88ba-4d95-8b87-53230e4e7cf9.png)

Hey, sorry for the lack of action. We'll take care of this asap. Sorry for the inconvenience.
