### ISSUE TITLE
Khaine's Embrace Order Respawn breached by destro

### ISSUE THREAD

**Issue by Navgoroth** [WarEmu/WarBugs#20041]
During Khaine's Embrace scenario, some destros managed to breach the wall of the warcamp.

This was not due to a punt, the destro could manage to get entrance through weird movements.
A blocking mesh might be usefull to prevent destro entering respawn.

I tried to show it on my screenshot, but it's not very clear as I stepped back to hide from getting hit, but the entrance was on the right side when facing the wall

![2022-04-21_19-27-07](https://user-images.githubusercontent.com/51286910/164520840-047db411-338b-45fc-8698-02b08730c384.jpg)
.

**Comment by Navgoroth** [comment]
I investigated as destro, and found the route to access, and also found another, screenshots attached
![2022-04-21_21-25-21](https://user-images.githubusercontent.com/51286910/164538962-ff52d831-5d67-4b66-bba2-b63269db4c97.jpg)
![2022-04-21_21-30-08](https://user-images.githubusercontent.com/51286910/164538965-b264b956-6640-4fd2-9796-cf6fb901d6d0.jpg)

**Comment by Rubyeclipse-war** [comment]
Thanks for the ticket - I've added two new barriers which would prevent Destro from getting into the Order spawn. 

I was able to confirm and fix both locations you listed, so thanks for the clear and concise instructions! 

https://www.youtube.com/watch?v=QZsqB_B5vbc

**Comment by lilimx** [comment]
fixed with patch 04/11/2022
