### ISSUE TITLE
witch elf

### ISSUE THREAD

**Issue by vithoria** [WarEmu/WarBugs#2004]
Heart seeker seems like there is some sort of range bug, im behind target abillity goes White, and still i can't knock Down my target, all thow i can hit with all my other hit's

**Comment by Evildoor** [comment]
I doubt that range has anything to do with it. More like lag issue which leads to client thinking that you are behind your target while server thinks otherwise. @ozarmidrashim, your opinion on this?

**Comment by ozarmidrashim** [comment]
Likely lag issue. I don't believe the server saves a history of rotations, so while it will compensate for position, it will not compensate for rotation.

**Comment by vithoria** [comment]
im just in the belive, if server say's on abillity ú in range, then target should be hit

**Comment by vithoria** [comment]
can use other hit's jut hear seeker i need to be right inthere ass, so close it looks like ass rape

**Comment by Evildoor** [comment]
As answered here and in #2013: lag + imperfect client-server interaction, nothing can be done for now. Closing.

**Comment by velkos4ever** [comment]
Its not an lag issue it pops up an error on my chat too

**Comment by Evildoor** [comment]
Can you explain the connection to me, please? How exactly "it pops up an error on my chat too" leads to "Its not an lag issue"?

**Comment by velkos4ever** [comment]
I just respeced to check if the spell works.it works now.i have no idea there was a fix or it was just me?

**Comment by Evildoor** [comment]
No fix was implemented in these 10-20 minutes, AFAIK. Can i hear an answer to my question, please? I would like to understand the logic.

**Comment by velkos4ever** [comment]
sorry i got distracted while i was looking my post and got directed (this was my original post about what i was refering to #2683)(i feel kinda stupid today:P)
