### ISSUE TITLE
[Quest] One of a Kind - missing quest item

### ISSUE THREAD

**Issue by TheBlueCarpetsBand** [WarEmu/WarBugs#20042]
**Expected behavior and actual behavior:**
**Expected:** This is one of the random, "hidden" quests in a zone where you click on something to accept a quest and click on it again to complete the quest, or to click on a quest item in your quest backpack to complete the quest.
**Actual:** Was able to accept quest by clicking on Dwarf skeleton, but bottle is missing so I can't click on it to complete the quest. The bottle is not on the ground, nor was it in my quest backpack.

**Steps to reproduce the problem:**
Head to (22209,23418) to find on the Dark Elf side of Ellyrion in T2 to find a dead Dwarf skeleton. Click on it to accept the quest "One of a Kind", but the quest requires a bottle that is on the ground near the Dwarf skeleton or in your quest backpack to click on again to complete the quest, but it is missing. Thus, this bugged quest cannot be completed.

**Testing Screenshots/Videos/Evidences (always needed):**

![Greggrosberg_000ssdf](https://user-images.githubusercontent.com/38879353/164585246-369a360e-75c8-4628-a1c8-a41bb0b401ce.jpg)

![Greggrosberg_331](https://user-images.githubusercontent.com/38879353/164583041-d9d44e47-1bce-4823-ab18-9815a9856e4f.jpg)

![Greggrosberg_332](https://user-images.githubusercontent.com/38879353/164583049-e2002fed-a115-4d70-a663-3286c936e37b.jpg)

![Greggrosberg_000](https://user-images.githubusercontent.com/38879353/164585951-571edb99-5f98-4e1d-a25a-18be54260584.jpg)

**Comment by Kaelang** [comment]
You need to re-interact with the Dwarf Skeleton to get the flask. Then you can empty it and complete the quest.
