### ISSUE TITLE
[Quest] Reclaiming a Birthright - missing NPC mob

### ISSUE THREAD

**Issue by TheBlueCarpetsBand** [WarEmu/WarBugs#20043]
**Expected behavior and actual behavior:**
**Expected:** Kill a High Elf NPC mob called, "Alantir Guardian", then loot a quest item (Alantir Gem) that drops off of this NPC mob to fulfill quest credit and then return to ,"Harogath Darkstrider" to complete the quest.
**Actual:** "Alantir Guardian" NPC mob is missing in Tor Elyr which means no gem can be looted so the quest cannot be completed.

**Steps to reproduce the problem:**
Chain quest "Reclaiming a Birthright" begins in the Dark Elf Ch.9 camp in T2 Ellyrion from questgiver, "Menista Kalanor". Quest then requires you to go to "Harogath Darkstrider" at the ,"Elyr Gate" which is located in the middle of Ellyrion. "Harogath Darkstrider" then requires you to go to the "Whitefire Tor (Easy)" PQ/publicquest for Dark Elf Ch.9 to kill a NPC mob called, "Lasendis Blightcaller" who drops a quest item called, "Lasendis's Map". Upon clicking, "Lasendis's Map" in your quest backpack, quest then requires you to kill a NPC mob called "Alantir Guardian" in the southwestern part of Ellyrion called, "Tor Elyr" but the NPC mob is missing there completely nowhere to be found, thus this bugged quest cannot be completed.

**Testing Screenshots/Videos/Evidences (always needed):**
![Greggrosberg_000](https://user-images.githubusercontent.com/38879353/164586775-336f6b6a-7c70-4e52-b5e0-900a02987cd1.jpg)

![Greggrosberg_001](https://user-images.githubusercontent.com/38879353/164586833-4e54e8b6-4c15-4f56-8519-2871cbc18732.jpg)

![Greggrosberg_310](https://user-images.githubusercontent.com/38879353/164586851-9d03eaa1-ed20-41ae-8113-dc05cab43bd6.jpg)

![Greggrosberg_316](https://user-images.githubusercontent.com/38879353/164586900-5a3681c9-9341-4291-9c48-1b4ec6e0880b.jpg)

![Greggrosberg_317](https://user-images.githubusercontent.com/38879353/164586913-dfd144bf-e54f-46e2-b3fe-c59eaeda520a.jpg)

![Greggrosberg_324](https://user-images.githubusercontent.com/38879353/164586937-3cf59eb4-06cf-4c68-a004-32ff4620acf2.jpg)

![Greggrosberg_325](https://user-images.githubusercontent.com/38879353/164586956-cc6de63d-45e5-4aef-9c94-4b74da775261.jpg)

![Greggrosberg_002](https://user-images.githubusercontent.com/38879353/164586989-a991e403-04ea-487d-8eab-38b2d341180a.jpg)

![Greggrosberg_344](https://user-images.githubusercontent.com/38879353/164586969-66f2cc18-5661-43e8-b025-4d28b38e9a96.jpg)

**Comment by ekalime** [comment]
This quest is working correctly. You have to follow the quest text and find the object "Lasendis's Urn" and click it. As a small object it is easy to miss, but it works.
