### ISSUE TITLE
Liminent of Boundless

### ISSUE THREAD

**Issue by Lerris81** [WarEmu/WarBugs#20052]
Hello,
when I drink Liminent of Boundless, I get only Ini.
Wouunds Buff dosn´t work.
![WAR-64 2022-04-27 08-24-59](https://user-images.githubusercontent.com/104486590/165456261-51523e3b-707e-42fd-ae7c-b24b9f9ace19.png)
![WAR-64 2022-04-27 08-25-14](https://user-images.githubusercontent.com/104486590/165456267-947ada8d-8315-4886-806f-25cd87b135a1.png)

**Comment by lilimx** [comment]
Hey,

the paperdoll display is no reliable source. Please add a picture with the .getstats command

**Comment by Lerris81** [comment]
OK thx, it is only a bug in paperdoll. in .getstats it works.

**Comment by Lerris81** [comment]
Works in .getstat
