### ISSUE TITLE
Invider ward unlocked but can't equip sovereign

### ISSUE THREAD

**Issue by gats69** [WarEmu/WarBugs#20053]
**Expected behavior and actual behavior:**

**Hello, i have a big problem :
I unlocked the invider ward (2 Invader +3 Triumphant) ,
I bought a sovereign piece, but I can't equip it, why?
Plz help me, I spent 3500 WC and I'm blocked now :(**

salutations.

**Steps to reproduce the problem:**
unlocked the invider ward (2 Invader +3 Triumphant) ,
buy a sovereign piece,
equip

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/10851323/165475320-35dea5e2-ff8a-4b17-b70c-efd1d67e02a9.png)

![image](https://user-images.githubusercontent.com/10851323/165475368-fd2f3b53-e02c-4c1f-86ad-4e1183cf37da.png)

![image](https://user-images.githubusercontent.com/10851323/165475405-4f6f9ecd-c1ba-4bec-ad51-95bb9b52aabf.png)

![image](https://user-images.githubusercontent.com/10851323/165475423-39ee90ab-a687-425e-8bbe-ca8fcca0c3ae.png)

![image](https://user-images.githubusercontent.com/10851323/165475447-150aa811-2964-42bd-ab0e-43e1d5e72f21.png)

![image](https://user-images.githubusercontent.com/10851323/165475480-e2b5e988-d45f-4ab0-8168-2524ca52fce8.png)

**Comment by lilimx** [comment]
Hey,

This issue is already on the tracker.

**Comment by lilimx** [comment]
Dublicate #20053
