### ISSUE TITLE
RvR Weekly

### ISSUE THREAD

**Issue by Ristom81** [WarEmu/WarBugs#20054]
![Zhyria_003](https://user-images.githubusercontent.com/26597777/165636612-d5f92b2f-5e10-418e-bb3c-c28efa3fa1c7.jpg)

Destro locked Caledor with a 5* keep on 04/27. Unfortunately, that doesn't count for RvR Weekly. My question: Wouldn't it be possible for a zone lock per 5* keep to also count for the keep?

**Comment by lilimx** [comment]
Hey,

I asked in team chat what's intended. So stay tuned.

**Comment by GamesBondd** [comment]
Capturing a keep and locking a zone are different and it would be good to keep it out of the weekly, as it's stating a keep conquest or defense and not a zone lock.
