### ISSUE TITLE
Runepriest knockback is undefendable

### ISSUE THREAD

**Issue by vithoria** [WarEmu/WarBugs#2005]
rune priest abilltiys is magis dmg and  knock back where neither of them seems to be affectet by elixr of couldron 100% disrupt

**Comment by ozarmidrashim** [comment]
Ability names, please. I know the knockback is Rune of Sundering.

**Comment by vithoria** [comment]
100% disrupt = elixir of couldron

**Comment by Evildoor** [comment]
"Elixir of the Cauldron", to be precise. Sorry, Azarael, when i renamed this issue yesterday i had no access to the game or mastery builder, so was not sure of exact names.

**Comment by ozarmidrashim** [comment]
I mean the second Runepriest ability. "Magic damage" doesn't tell me much.

I know most ability names from their descriptions.

**Comment by vithoria** [comment]
http://waronlinebuilder.org/#career=rp; here u can see all runepriest abillitys with name
