### ISSUE TITLE
Sentrys Glaive of Ferocity, Blackguard soldier emblem spear.

### ISSUE THREAD

**Issue by AlistaireCrowley** [WarEmu/WarBugs#2006]
Sentrys Glaive of Ferocity is bugged. Say in tooltip that its Main hand. Should be 2-hand. I e can be used with shield.

**Comment by Meralors** [comment]
It is now 2handed :) pulled live with next patch.

**Comment by Evildoor** [comment]
Requirement is proper now, but price is that of 1handed weapon.

**Comment by Meralors** [comment]
Fixed price ot match other 2handed weapons
