### ISSUE TITLE
CANT LOG IN!

### ISSUE THREAD

**Issue by Jonee90** [WarEmu/WarBugs#20061]
**Expected behavior and actual behavior:**
Login to character.

**Steps to reproduce the problem:**
Cant login to my Dok Xenil. It shows in guild roster active and online. Ppl can also wisper to it. Seems like all other characters work fine.

**Testing Screenshots/Videos/Evidences (always needed):**

After pressing play next to character, screens goes to this state. Same after restart just cant login.
![image](https://user-images.githubusercontent.com/75245801/166151548-14769c40-21e2-4db6-991c-4fa5168b827f.png)

**Comment by lilimx** [comment]
Hey,

this kind of issue belongs to the tech-suipport forum here: https://www.returnofreckoning.com/forum/viewforum.php?f=4
or join the RoR - Discord for more information here: https://www.returnofreckoning.com/forum/viewtopic.php?f=2&t=22044

If only one of your characters stucks, please add your name and guild here, and a GM will pull your character out of the void and put it at a save spot: https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=46249
