### ISSUE TITLE
[Quest][Dark Elf] Chap 18 "The List" - incorrect quest text/misspelling/typo

### ISSUE THREAD

**Issue by TheBlueCarpetsBand** [WarEmu/WarBugs#20066]
"Kularis the Torturer" NPC from DE chapter 18 in Dragonwake offers a chain quest called, "The List". However in the second quest in that chain quest, I noticed a misspelled word for the following sentence, "Fetch it, and **quickl**". This quest from the original, "Warhammer Online: Age of Reckoning" game contained the word "**quickly**" for this quest in that sentence instead of the incorrect word "**quickl**".

**Expected behavior:**
Correct quest text should look like this:

_"Even with the proper chemicals, breaking a will is a matter of patience, time, and determination. I have little patience, and time is against me. Without time, how can I savor his fear and taste his anguish as if it were a fine wine?I need the most powerful of all devices at my disposal. With this ingenious artifact, I will strip his soul bare! Despite the speed with which I must break this High Elf wretch, I am determined to make the best of my task. Fetch me the Onion! What is wrong with you, [playername]? Have you lost all reason? The Onion, fool! Fetch it, and **quickly**. Retrieve the Onion from Uldark, my apprentice, and bring it to me at once!"_

 **Actual behavior:**
In the game right now the incorrect quest text is like this instead:

_"Even with the proper chemicals, breaking a will is a matter of patience, time, and determination. I have little patience, and time is against me. Without time, how can I savor his fear and taste his anguish as if it were a fine wine? I need the most powerful of all devices at my disposal. With this ingenious artifact, I will strip his soul bare! Despite the speed with which I must break this High Elf wretch, I am determined to make the best of my task. Fetch me the Onion! What is wrong with you, [playername]? Have you lost all reason? The Onion, fool! Fetch it, and **quickl**. Retrieve the Onion from Uldark, my apprentice, and bring it to me at once!"_

Notice that the incorrect word, "**quickl**" is found in this sentence:
"The Onion, fool! Fetch it, and **quickl**" when it should be "quickly".

**Steps to reproduce the problem:**
**Testing Screenshots/Videos/Evidences (always needed):**
![Greggrosberg_224](https://user-images.githubusercontent.com/38879353/166412101-6190aae9-8fb2-4383-909d-7f30eefb2c91.jpg)
![Greggrosberg_223](https://user-images.githubusercontent.com/38879353/166412107-036c5134-8684-4869-aa81-7d5dab39af5a.jpg)
![Greggrosberg_148](https://user-images.githubusercontent.com/38879353/166412109-4b3195e8-a73d-44e4-b891-db3db28fb7a5.jpg)
![Greggrosberg_150](https://user-images.githubusercontent.com/38879353/166412112-3b8a62b3-6d7d-4088-8bd9-2b84e63db180.jpg)
![Greggrosberg_221](https://user-images.githubusercontent.com/38879353/166412119-9d31a6a4-bd76-4ae4-9afb-9fa2aca0f13e.jpg)
![Greggrosberg_222](https://user-images.githubusercontent.com/38879353/166412123-2e4ce297-3d84-47da-b966-bdd090074951.jpg)
![Greggrosberg_223](https://user-images.githubusercontent.com/38879353/166412127-7ef68639-0753-4cfa-b19d-9954fda290b8.jpg)
![Greggrosberg_224](https://user-images.githubusercontent.com/38879353/166412131-92ef7b23-f0f9-46a4-9e8e-c6c841bdc250.jpg)

**Comment by lilimx** [comment]
Fixed with Patch 29/06/2022
