### ISSUE TITLE
"Scuse Me!" deal just 1/2 base damage

### ISSUE THREAD

**Issue by pontagriel** [WarEmu/WarBugs#20060]
"Scuse Me!" is one of the important offensive shamans burst ability but now it deal just 1/2 base damage. 
Damage on screenshoot without any modificators. As we can see, the ability should deal 578 damage but deal 359.
![image](https://user-images.githubusercontent.com/104679011/166103733-17c38bfa-bb9f-4808-95b8-8cade9b946a2.png)

**Comment by vasia-buhoi** [comment]
AM mirror ability "Storm of Cronos" did more dmg then write on tooltip
![Luril_011](https://user-images.githubusercontent.com/104709290/166134076-57c99f77-2287-409d-a44b-f3a621734c93.jpg)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. This issue is already known.

**Comment by lilimx** [comment]
dublicate #18586
