### ISSUE TITLE
Witchbrew and Tactic: Frenzied Mayhem

### ISSUE THREAD

**Issue by Ristom81** [WarEmu/WarBugs#20063]
![Zhyria_004](https://user-images.githubusercontent.com/26597777/166184423-0f4bd79b-b13e-4431-9d79-91cefaae6fb4.jpg)
![Zhyria_005](https://user-images.githubusercontent.com/26597777/166184432-1837f73c-7fbd-407f-804f-a16f6f6d7bfc.jpg)

I've tested Witchbrew once without and once with the tactic: Frenzied Mayhem, but Witchbrew's damage remains the same.

My question: Is that correct that Frenzied Mayhem has no effect on Witchbrew's damage?

**Comment by vasia-buhoi** [comment]
Yes, its correct. Read [Patch Notes 09/03/2022](https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=47678)
Tactic Frenzied Mayhem effect on Witchbrew's damage, but tactics Flanking, Taste of Blood and Masterful Treachery did effect on Witchbrew's damage

**Comment by Ristom81** [comment]
> Yes, its correct. Read [Patch Notes 09/03/2022](https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=47678) Tactic Frenzied Mayhem effect on Witchbrew's damage, but tactics Flanking, Taste of Blood and Masterful Treachery did effect on Witchbrew's damage

The tooltip is correct now I tested it. But still the damage would have to be increased if I play with the Tactic: Franzied Mayhem, because witchbrew is a frenzy, and it should also get 5% more damage with the Tactic, per bloodlust.
Because Frenzied Mayhem's tooltip says: Increases the damage of your Frenzies by 5% for each Bloodlust points you have.

**Comment by vasia-buhoi** [comment]
Read patch note plz
![Безымянный](https://user-images.githubusercontent.com/104709290/166215289-50ae4e7c-dff1-45dc-be8a-df525fe56c68.jpg)

**Comment by lilimx** [comment]
Hey,

I closed this ticket and sent a request to the team if it's fixed now or not. Otherwise, there is already an open ticket (that one that you mentioned)
