### ISSUE TITLE
/emote broken.

### ISSUE THREAD

**Issue by TVBrowntown** [WarEmu/WarBugs#20065]
/emote no longer works. when you type /emote <whatever> and press enter nothing will appear or be sent.

**Expected behavior and actual behavior:**

/emote should allow custom emotes.

**Steps to reproduce the problem:**

type /emote and press enter to enter /emote chat then type whatever you like and press enter, this would usually allow you to post a custom emote. Doing thing now will produce no emote.

**Testing Screenshots/Videos/Evidences (always needed):**
Do... do I need to do this in this case? There is nothing there... I will provide a video later as I'm currently not able to.

**Comment by lilimx** [comment]
Fixed with Patch 7/7/2022
