### ISSUE TITLE
[Quest][Dark Elf] Chap 19 "Brittle Forging" - incorrect quest text/missing letters/typos/bad grammar

### ISSUE THREAD

**Issue by TheBlueCarpetsBand** [WarEmu/WarBugs#20069]
"Korana Bloodmoon" NPC from DE chapter 19 in Dragonwake offers a quest called, "Brittle Forging". However the following sentence in this quest, "_The problem lies with the resource available to the kin-traitors._ " has the word "**resource**" when it should be "**resources**" The following sentence in this quest, _"No matter how many of their camps we route out and destroy the can be resupplied by Caladain’s Furnace."_ has the word "**the**" when it should be "**they**".

**Expected behavior:**
Correct quest text should look like this:

_"We outnumber our enemy and our troops are more skilled, yet we still cannot break through these accursed mountains. The problem lies **with the resources available** to the kin-traitors. No matter how many of their camps we route out and **destroy they can be resupplied** by Caladain’s Furnace. We have already tried cutting off the supply routes, but there are far too many secret and winding passages through these mountains for that to be an effective strategy. It falls to us to assault Caladain’s Furnace directly and end this nonsense once and for all. Hyethan Baneblade has been given command of the assault. Seek him out to the south."_

**Actual behavior:**
In the game right now the incorrect quest text is like this instead:

_"We outnumber our enemy and our troops are more skilled, yet we still cannot break through these accursed mountains. The problem lies **with the resource available** to the kin-traitors. No matter how many of their camps we route out and **destroy the can be resupplied** by Caladain’s Furnace. We have already tried cutting off the supply routes, but there are far too many secret and winding passages through these mountains for that to be an effective strategy. It falls to us to assault Caladain’s Furnace directly and end this nonsense once and for all. Hyethan Baneblade has been given command of the assault. Seek him out to the south."_

Steps to reproduce the problem:
**Testing Screenshots/Videos/Evidences (always needed):**
![Greggrosberg_261](https://user-images.githubusercontent.com/38879353/166420351-a686f6a6-b527-474d-acf0-e432669c6e8f.jpg)
![Greggrosberg_257](https://user-images.githubusercontent.com/38879353/166420364-e304077a-a658-4e31-8d81-4e0d93db8c85.jpg)
![Greggrosberg_260](https://user-images.githubusercontent.com/38879353/166420367-ca81bfb0-9f54-46eb-8867-843666424b2a.jpg)
![Greggrosberg_258](https://user-images.githubusercontent.com/38879353/166420373-498d0521-4201-43bf-9b63-7245728e08cf.jpg)

**Comment by lilimx** [comment]
Fixed with Patch 29/06/2022
