### ISSUE TITLE
[NPC][Dark Elf] Chap 20 "Kill Collector/Thandros Uthorin" - incomplete dialogue

### ISSUE THREAD

**Issue by TheBlueCarpetsBand** [WarEmu/WarBugs#20071]
The Kill Collector "Thandros Uthorin" from DE chapter 20 in Eataine has missing text dialogue in English when you talk to the NPC which leaves confusion about what extra lore there is about this character and what mobs this Kill Collector needs (I already know that most Kill Collectors are currently broken in the game though, but virtually all of their dialogue correctly works except for this one). His missing quote was not included in the Tome of Knowledge about this character either.

**Expected behavior:** Normally when you encounter a Kill Collector NPC in every PVE chapter quest hub in every tier, you can talk to the NPC by right-clicking on them and they will have a complete quote/message that they will show in their dialogue every time you right click on them.

**Actual behavior:**
Right-clicking this NPC resulted in just an incomplete message which was the following:
"r own remedy. We are very close to achieving victory in Ulthuan; so close, in fact, that the High Elves"

Steps to reproduce the problem:
**Testing Screenshots/Videos/Evidences (always needed):**
![Greggrosberg_128](https://user-images.githubusercontent.com/38879353/166517662-d6df46f2-33ce-4912-8ef8-7183bf094012.jpg)
![Greggrosberg_130](https://user-images.githubusercontent.com/38879353/166517674-ba2de6db-8d16-40d6-bc20-37decec0a13e.jpg)
![Greggrosberg_129](https://user-images.githubusercontent.com/38879353/166517688-14989395-28f5-413c-b079-16d1d3cc71ed.jpg)

**Comment by Rubyeclipse-war** [comment]
Thank you for letting us know! The missing text on this NPC has been fixed.

In doing so, I saw that a lot of other Kill Collectors are currently broken, along with the actual Kill Quest for this one. In the future, it's something I'd like to come back to and work to fix. Thank you again!

**Comment by lilimx** [comment]
Fixed with patch [14/09/2022]
