### ISSUE TITLE
[Quest][Dark Elf] Chap 20 "The Great Hunt" - unable to complete quest/can't kill 4 "Eataine Noble" NPC's

### ISSUE THREAD

**Issue by TheBlueCarpetsBand** [WarEmu/WarBugs#20077]
"Dirkaln Vorsept" NPC from DE chapter 20 in Eataine offers a quest called, "The Great Hunt". However the mobs in the Cold One pen/cage cannot be killed or damaged by any kind of ability/spell (such as ST or AOE abilities/spells) thus quest credit for killing 4 "Eataine Noble" cannot be achieved and the quest is currently broken/impossible to complete.

**Expected behavior:**
Should be able to damage/kill 4 "Eataine Noble" NPC's to get quest credit to complete quest.

**Actual behavior:**
Unable to damage/kill 4 "Eataine Noble" NPC's to get quest credit to complete quest, trying to use any abilities/spells against them automatically results in a "TARGET IS NOT ATTACKABLE" error.

Steps to reproduce the problem:
**Testing Screenshots/Videos/Evidences (always needed):**
![Greggrosberg_253](https://user-images.githubusercontent.com/38879353/167076505-1089e700-6e34-4aa0-9598-d4e7cae89686.jpg)
![Greggrosberg_255](https://user-images.githubusercontent.com/38879353/167076518-1e9e9358-6608-4d8d-9303-cbbb8daa19c3.jpg)
![Greggrosberg_256](https://user-images.githubusercontent.com/38879353/167076528-5e20bd75-c9a7-4e4c-a5c9-be3f6957d2f0.jpg)

**Comment by Kaelang** [comment]
Fix was added. Please re-open if issue remains.
