### ISSUE TITLE
[TACTICS] Swordmaster - Potent Enchantments & Bolstering Enchantments proc hits targets/heals the group even tho the tactics is not slotted

### ISSUE THREAD

**Issue by HokoBugTracker** [WarEmu/WarBugs#20072]
I recognized, while fighting in city, that i've killed someone with "Potent Enchantments" even tho it wasn't slotted in my tactics bar.

I tested some more tactics on a construct and realized that tactics that i've slotted before, but swapped for others or even removed all tactics, they would still trigger/proc and hit the targets.

You can switch "Potent Enchantments" with "Rugged" in your tactics bar and "Potent Enchantments" will still work and proc, but it stops proccing/working in the background after you switched your blade enchantment. Same behaviour with heals for the group with "Bolstering Enchantments".

 https://youtu.be/h2x8QlQcooA

https://youtu.be/ZQPeBxe7ZHM

"Potent Enchantments" and "Bolstering Enchantments" are the two tactics that still work if your are replacing them on your tactics bar, you can replace them with every tactic you want. Using both tactics (PE & BE) at once is kind of negating/deactivating the other one (depends on which was slotted first). 
Like mentioned above, switching your blade enchantment will reset the overwrite of the tactics back to your normal 4 tactics that are slotted. 

![Desktop Screenshot 2022 05 04 - 22 47 05 41](https://user-images.githubusercontent.com/60039912/166825400-aafa1984-5b16-4d41-879e-1d974676da92.png)

**Comment by CrimsonFenris** [comment]
Most procs tactics of the SM are bugged, either being mutually exclusive (slotting one prevent from switching to the other for instance), or appying even after tactic switch.

Related to https://github.com/WarEmu/WarBugs/issues/19474 (see inside for some other related posts).

It's becoming more and more pressing matter ; applying more than 4 tactics at a time could be kind of game breaking in some cases (in good or bad ways).

**Comment by lilimx** [comment]
Fixed with patch 17/11/2022
