### ISSUE TITLE
Mounted Carrying Scenario Objective

### ISSUE THREAD

**Issue by hammerhammerhammer** [WarEmu/WarBugs#20078]
After picking up the Warpstone Talisman in The Maw of Madness scenario, I was able to mount using the Exotic Grey Arabian Steed.  I was able to do the same thing with the Glyph of Fury.  Upon picking up the Glyph of Fury, my teammate was not able to mount using the standard Chaos mount.

It is my understanding that this is a bug, and that normal behavior would prevent the picking up of objectives while mounted or that the objective would be dropped after mounting.  It appears that the Land of the Dead mounts bypass this behavior.

I've included a screenshot of my character mounted while carrying the Warpstone Talisman.

![Guardomatic_018](https://user-images.githubusercontent.com/69740705/167230150-0b5d2e4a-f1c6-46f8-a052-e25de83f4eec.jpg)

**Comment by lilimx** [comment]
fixed with patch [10/09/2022]
