### ISSUE TITLE
4 piece triumph does not appear on pure/buffhead

### ISSUE THREAD

**Issue by bisbalien** [WarEmu/WarBugs#20079]
after spending some time damaging dummy i realised that vicious strikes 4 piece does not appear on pure/buffhead. it may be a visual bug dont really know. Edit : weaponskill is not increasing in character panel either which should since it gives a weaponskill buff, so i guess the proc does not work properly
![WAR-64 2022-05-07 18-52-48](https://user-images.githubusercontent.com/86349663/167262076-0806aba1-89c3-448e-aede-45a81f9c0846.png)

**Comment by lilimx** [comment]
Hey,

please redo you test with the command .getstats (paperdoll stats are no reliable source).

also you can check with this trick if you get a certain buff that is triggered by special moments:
https://www.youtube.com/watch?v=fp6HdV-V2TY

**Comment by bisbalien** [comment]
with .getstats command weaponskill stays the same , does not change on this window aswell. Also my enemy addon is a bit buggy and can not add the ID of that effect in order to appear on the sides (just like the video)

**Comment by bisbalien** [comment]
Just logged in and effect finally appears on pure , although i do not know how to make it appear on buffhead (since i do not have the ID) . Also weaponskill on character panel changes correctly. It should have been something visual i guess dunno

**Comment by lilimx** [comment]
Hey,

ah nice. If you need more help with pure/buffhead setups you can jump on our RoR discord:
https://www.returnofreckoning.com/forum/viewtopic.php?f=2&t=22044
Or you can also read my guide here (Addon Section): 
https://www.returnofreckoning.com/forum/viewtopic.php?f=113&t=40739
