### ISSUE TITLE
Lionhome Lodge PQ Is Bugged

### ISSUE THREAD

**Issue by Hopkin1** [WarEmu/WarBugs#20073]
**Expected behavior and actual behavior:**

The server should record killing 20 Lion Hunters to advance to the next stage, but doesn't, it stops at 5.

**Steps to reproduce the problem:**

Go to Chrace's Lionhume Lodge PQ. Kill Lion Hunters and notice the server doesn't record beyond 5. (Note in video, I've killed 25 lions).

**Testing Screenshots/Videos/Evidences (always needed):**

https://user-images.githubusercontent.com/88755420/166977742-34e328b2-63ea-480d-a26a-8e648d444432.mp4

**Comment by Lheana** [comment]
You have to kill Lion Hunters, not Lionmarch Hunters. Lion Hunters are High Elves.
