### ISSUE TITLE
[Quest][Greenskin] Epic Quest - Time to Waaagh

### ISSUE THREAD

**Issue by TVBrowntown** [WarEmu/WarBugs#20075]
**Expected behavior and actual behavior:**
Additional Quest Info: https://wiki.returnofreckoning.com/Greenskins_T4_Epic_Quest_Time_to_Waaagh!

During the section of the Epic quest where you must do 3 different tasks. Brung must be "fired" (killed) after handing in a quest to him. However, he does not transition from friendly target to hostile target making the task unfinishable. HOWEVER, if you right click Brung you will complete the task.

**Steps to reproduce the problem:**

Do the quest. Read the task, speak to him in a calm and collected manner to complete the task in pacifist mode.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://media.discordapp.net/attachments/953611622918811658/971939963111358545/WAR_2022-05-06_09-57-57.png?width=1202&height=676)

**Comment by TVBrowntown** [comment]
It's possible I've misinterpreted fire him to mean kill him... when actually it means to literally fire him from his position.  If so, feel free to close the issue. Perhaps the wording of the quest text needs a little update to prevent confusion? :|

**Comment by lilimx** [comment]
Hey,

Let's decide a database dev 😀

**Comment by Lheana** [comment]
You are right, he is meant to turn hostile and you have to fight him, however this can not be implemented that way for now, that's why the quest has been changed. As it's known and the quest is completable, I close the ticket.
