### ISSUE TITLE
[Quest][Dark Elf] Chap 20 "Keys to Nobility" - incorrect quest text/typo

### ISSUE THREAD

**Issue by TheBlueCarpetsBand** [WarEmu/WarBugs#20076]
"Geleron Morthek" NPC from DE chapter 20 in Eataine offers part of a chain quest called, "Keys to Nobility". However the following sentence in this quest, _"Ensure that **he** remains safe from harm"_ does not make sense because the quest is referring to a woman/female NPC, "_Renefir Heartbane_" not a man/male NPC as proven repeatedly from the rest of this quest text, _"**She** has sequestered herself away from our forces so that **her** magics will not be disturbed. Take to **her** the Drakestorm Seal, and ask what may be wrought from it"._

**Expected behavior:**
Correct quest text should look like this:

_"Your work deserves a true reward, don’t you think? To our east, a mere league away, is my master’s encampment. She has sequestered herself away from our forces so that her magics will not be disturbed. Ensure that **she** remains safe from harm. Take to her the Drakestorm Seal, and ask what may be wrought from it. I think you will enjoy the result. Such a fitting end to the pretensions of the kin-traitor dynasties!"_

**Actual behavior:**
In the game right now the incorrect quest text is like this instead:

_"Your work deserves a true reward, don’t you think? To our east, a mere league away, is my master’s encampment. She has sequestered herself away from our forces so that her magics will not be disturbed. Ensure that **he** remains safe from harm. Take to her the Drakestorm Seal, and ask what may be wrought from it. I think you will enjoy the result. Such a fitting end to the pretensions of the kin-traitor dynasties!"_

Steps to reproduce the problem:
**Testing Screenshots/Videos/Evidences (always needed):**
![Greggrosberg_246](https://user-images.githubusercontent.com/38879353/167075042-45128313-bf25-407d-be98-ca287a7344a1.jpg)
![Greggrosberg_261](https://user-images.githubusercontent.com/38879353/167075386-0b82c241-8a30-40ae-a917-adaa845317d4.jpg)
![Greggrosberg_249](https://user-images.githubusercontent.com/38879353/167075034-49f3c8ce-3ac6-4ec7-b373-9e9033087675.jpg)
![Greggrosberg_248](https://user-images.githubusercontent.com/38879353/167075048-29d23221-c464-4f01-a3de-24453c7fb017.jpg)
![Greggrosberg_247](https://user-images.githubusercontent.com/38879353/167075060-1c6dc6b4-6f62-4fc7-9a26-3ec1f160801d.jpg)

**Comment by Kaelang** [comment]
Fix was added. Please re-open if issue remains.
