### ISSUE TITLE
Movement visual bug

### ISSUE THREAD

**Issue by spacestarkid13** [WarEmu/WarBugs#20080]
After patch from 04.05.2022 I experiencing odd visual bug - some NPC or players moving strafe or backwards.
Got latest Nvidia drivers (512.59), Internet connection is good.

https://youtu.be/uLaRdHr9USc

**Comment by lilimx** [comment]
Hey,

I guess that not an actual bug. If your game hits more than 100 fps, people are starting to glitching around, you can do these two things.

1. Go to your RoR Launcher, press the gear wheel, and choose the 32 bit version.
2. or, stay with the 64bit version and cap your frames inside your graphic card driver settings.
