### ISSUE TITLE
Public Quest - The Caladain Steppe - Normal

### ISSUE THREAD

**Issue by Bigolcrities** [WarEmu/WarBugs#20083]
**Expected behavior and actual behavior:**

Loot chest no longer spawns

**Steps to reproduce the problem:**

Finished public quest

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
hey,

could be an issue from the crash before....please check again

**Comment by Lheana** [comment]
Tested, the chest spawns; must have been the server crash.
