### ISSUE TITLE
Unable to connect to server or website

### ISSUE THREAD

**Issue by nuitaran** [WarEmu/WarBugs#2008]
Connect button on launcher does nothing, even after restarting multiple times. Website results in a 503 error.

**Comment by Tagaruk** [comment]
login server is down (in the launcher), website seems also down

**Comment by nuitaran** [comment]
Log in server and web server are both showing as up for me in the launcher. DDoS?

**Comment by Evildoor** [comment]
DDoS, most likely. This does not belongs to bugtracker, since it's an issue with site/server availability. Closing.
