### ISSUE TITLE
Frenzied mayhem tactic not working with Witchbrew

### ISSUE THREAD

**Issue by nineserpents** [WarEmu/WarBugs#20096]
**Expected behavior and actual behavior:**
Frenzied Mayhem should increase the dmg of your frenzies by 5% for each bloodlust you have. 
Frenzied Mayhem has stopped working with Witchbrew all together.

**Steps to reproduce the problem:**
I used the training dummies in IC to test Witchbrew dmg with and without Frenzied Mayhem tactic and it no longer scales.

**Testing Screenshots/Videos/Evidences (always needed):**

With FM:
![witchbrew-with-fm](https://user-images.githubusercontent.com/43865893/168379248-eb272694-fe85-4bfd-b630-ce7d35194eb8.jpg)
Without FM:
![witchbrew-without-tactics](https://user-images.githubusercontent.com/43865893/168379286-e4f13a0e-77c8-4aa4-9b4a-38cf74fc7ab2.jpg)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. This issue is alread known.
Ticket: #19872
