### ISSUE TITLE
Anyone has same Broadhead Arrow Hit damage as mine?

### ISSUE THREAD

**Issue by GCXXZ2022** [WarEmu/WarBugs#20094]
![image](https://user-images.githubusercontent.com/105505897/168311402-166b5cc6-64aa-4901-bb3a-28b23a72a2be.png)
When I check damage deal, I saw a Broadhead Arrow Hit critically for 1625 damage. I wonder is that bug or some kind real damage?

**Comment by lilimx** [comment]
Hey,

Where (exact place) and against what class did this incedent happen?

**Comment by GCXXZ2022** [comment]
![image](https://user-images.githubusercontent.com/105505897/168404572-b4da2191-fdcb-411f-8d23-f84f15c8be2c.png)

It was in High Pass. Class is Shadow Warrior. Image shows that happen location.

**Comment by lilimx** [comment]
Hey,

Yeah could be already the triggered Warcamp buff

**Comment by GCXXZ2022** [comment]
This location is very far from Warcamp. And I never see any buff on me when I deal damage. You see the first picture. The 1625 damage shows in mid of all damage. This damage looks like full damage amount of this skill when I use it. It didn't go debuff to target. It looks like one shot skill. Deal full damage to target.

**Comment by lilimx** [comment]
Hey,

there is no visual buff for the warcamp buff

**Comment by GCXXZ2022** [comment]
You mean this damage is normal? Somehow it deal 1625 damage by one shot. This skill is DOT. If you think this is ok. I am ok too. This is some kind the fun things I never see it.

**Comment by lilimx** [comment]
Hey,

yeah, WC buffs are actually very very powerfull (almost possible to one-hit people)....If it appears again in a weird area, do a new report, please.
