### ISSUE TITLE
Stupid Dead Stunties missing from Quest Log

### ISSUE THREAD

**Issue by VonEpic** [WarEmu/WarBugs#20093]
![Stupid Dead Stunties Quest No Longer in Book](https://user-images.githubusercontent.com/31397093/168308953-bc4e6cf3-4be4-4719-ac8b-9a0f7eae3750.png)

I have the quest, probably from years ago, but it does not show up in my quest book.

**Comment by MaxHayman** [comment]
It appears that you have already completed this quest, which is why it does not show in your quest log.

Please let me know if this is unexpected.

**Comment by VonEpic** [comment]
> It appears that you have already completed this quest, which is why it does not show in your quest log.
> 
> Please let me know if this is unexpected.

If the quest is complete, why does the dialog window for an active quest pop up?
