### ISSUE TITLE
"EU early" city siege time is 7pm Altdorf time in-game, but 8pm Altdorf time on the patch notes.

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#20091]
**Expected behavior and actual behavior:**

The patch notes say that the "EU early" city time is 8pm Altdorf time, however it has actually started at 7pm Altdorf time.

**Testing Screenshots/Videos/Evidences (always needed):**

All screenshots taken within minutes of each other.

Patch notes:

![image](https://user-images.githubusercontent.com/60266177/167904092-12ee3849-806c-4d96-87d2-b02b4bda95e0.png)

Current Altdorf time:

![image](https://user-images.githubusercontent.com/60266177/167904197-0bcf08d6-eda1-4374-8637-8031a8e54644.png)

Currently in game (city about to begin):

![image](https://user-images.githubusercontent.com/60266177/167904300-235f4000-3186-4cd3-b723-c7620002a9a6.png)

Guild calendar (I'm in the UK so it's showing 6pm UK time, which is 7pm Altdorf time):

![image](https://user-images.githubusercontent.com/60266177/167904385-6c7ebe01-ee78-4830-85e5-b2290dd784df.png)

Proof of current UK time when I took these screenshots:

![image](https://user-images.githubusercontent.com/60266177/167904501-7599c698-eb87-4d99-967c-97cb09c55bc4.png)

**Comment by lilimx** [comment]
related to #19982

**Comment by Kaelang** [comment]
Fix was added. Please re-open if issue remains.
