### ISSUE TITLE
Altdorf City Door Damage Contribution

### ISSUE THREAD

**Issue by Rebiff** [WarEmu/WarBugs#20095]
**Expected behavior and actual behavior:**
You can go into a city, and attack the pve doors around the city (as destro) and get tons of damage contribution, usually the top dps
in the city is doing this, just running around not even fighting, just hitting doors, please make these doors non attackable. im constantly seeing 3-4 destro DPS running around the map randomly attacking doors instead of helping teamfights because its more worth wile for them to just hit doors.

**Steps to reproduce the problem:**
go into altdorf city instance as destro, find doors, hit them. 
![city dps](https://user-images.githubusercontent.com/91923176/168379106-e4159c96-3b03-455b-9f33-f8b6e3343c32.png)
![city dps 2](https://user-images.githubusercontent.com/91923176/168379279-d1255ff3-1e08-4ddb-b7f7-5a0775d5f39c.png)

**Comment by MaxHayman** [comment]
Hi, would you be able to send me a video of what door is attackable? The gates at the location in your screenshot are not attackable.

**Comment by Rebiff** [comment]
![image](https://user-images.githubusercontent.com/91923176/173713621-7c81d244-d229-4d20-8c05-a4b2ceb4ddf4.png)
its the doors like these during city, theyre attackable by destro.

**Comment by MaxHayman** [comment]
![Image](https://user-images.githubusercontent.com/1018809/177209121-43c98e15-16f9-4950-9701-afd97fde03cb.png)

Doesn't seem to be attackable

**Comment by lilimx** [comment]
Fixed with Patch 16/07/2022
