### ISSUE TITLE
[LOTD] Multiple stacks of "Silver Scarabs" with different cooldown timers

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#20098]
**Expected behavior and actual behavior:**

Expected: The silver scarabs you earn during LOTD should expire at the end of it.

Actual: The silver scarabs actually last for over 7 days. Each stack of Scarabs seems to have its own decay timer on it based on when I first obtained the scarabs. At the end of the LOTD on 14 May 2022 I had 3 stacks:

1) Stack 1 had 30 minutes left on it. I assume these were earned at the end of a previous LOTD and hadn't fully decayed yet.

2) Stack 2 had 7d6h28m left on them. This was the stack I earned during the current LOTD.

3) Stack 3 had 7d21h28m left on it. I think these were earned from kills that happened after the LOTD was over (another bug report going in for this)

**Steps to reproduce the problem:**

It seems the main way of getting multiple stacks is to get kills in LOTD after the event has ended (possible as you are not teleported out immediately). The different stacks can then be seen clearly in the currency items.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/60266177/168447731-e21289c6-9430-45c5-846c-5a966afd00bd.png)

![image](https://user-images.githubusercontent.com/60266177/168447741-732ac6d6-f942-4a61-9839-e7015dab4a48.png)

![image](https://user-images.githubusercontent.com/60266177/168447716-1fac40c7-215d-4fda-9914-a800f12fb92b.png)

**Comment by MaxHayman** [comment]
Items are only stackable if their decay time is the same. As stacked items are a quantity and we don't store individual quantities decay timer.

However the 3rd stack issue is mentioned in #20099 so I will close this issue.

Thank you for reporting.
