### ISSUE TITLE
[GCD] Server allows to cast channeling spells but interrupt them after the cast

### ISSUE THREAD

**Issue by Solganis** [WarEmu/WarBugs#20104]
**Actual behavior:**
Game allow you to cast channeling spells at the end of the cast but it's got interrupted after 0.1 or 0.4 sec

**Expected behavior:**
"The 1.5 second Global Cooldowns are now more strictly checked and the server will **no longer allow casting abilities** slightly before the Global Cooldown ends."

**Steps to reproduce the problem:**
Cast spell and try to cast another channel spell at the end of the cast

**Testing Screenshots/Videos/Evidences (always needed):**
https://user-images.githubusercontent.com/44605445/169010863-265173be-c090-4dba-bca0-ceab941bec51.mov

**Comment by lilimx** [comment]
Hey,

should be fixed with the hotfix 18/05/2022
