### ISSUE TITLE
Taunt and Challenge

### ISSUE THREAD

**Issue by Zhentarim** [WarEmu/WarBugs#2010]
I have had this problem on all three destruction tanks. The abilities doesn't "force" the enemy mob to attack you. Right now taunt is as effective as an axethrow pretty much.

**Comment by Morksezstop** [comment]
aggro mechanic is not implemented at all afaik. healers dont generate aggro, dps dont create aggro and so on

**Comment by Zhentarim** [comment]
Then what determines who will be attacked? Because I know that I've managed to steal aggro from another player despite him hitting the mob first for example.

**Comment by milosxe** [comment]
Aggro in the game is obviously primitive, and only has to do with dmg dealt. It's clearly stated in the latest dev diary that they have yet to understand the aggro mechanic, and eventually implement it.

**Comment by Evildoor** [comment]
Closing per explanations above - aggro mechanic is pretty much not implemented.
