### ISSUE TITLE
T'ree Hit Combo hits yourself

### ISSUE THREAD

**Issue by Zoggof** [WarEmu/WarBugs#20103]
![image](https://user-images.githubusercontent.com/23256143/169008837-e4dd29a0-137c-4691-862e-26ffd9c024bf.png)

T'ree Hit Combo for Black Orc seems to be only hitting yourself. Tested on PvE mobs and players in RvR.

Tested with other channeled abilities on other classes (BG - Enraged Beating) and it worked fine.

**Comment by lilimx** [comment]
According to Dalen, there is a fix pending.

**Comment by lilimx** [comment]
Hey,

should be fixed with the hotfix 18/05/2022
