### ISSUE TITLE
PvE aggro screwed

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#20109]
Just started a run of destro city dungeons, team consists of 5 rr40-60ish players and one rr97 choppa, the tank (me) is spamming taunt and challenge on cooldown, using nothing but the hate builder attack with menace tactic slotted and the choppa under guard - I can't hold aggro off of the other two dps in the team, both of whom are in conq gear/level range

**Comment by MightyPhred** [comment]
Update: we killed the first boss in the pit, against 2nd boss aggro mechanics seemed to work but he dropped no loot and gave no quest credit

**Comment by MightyPhred** [comment]
2nd attempt, similar team composition featuring one high level dps (rr73 WE) that should easily have generated enough aggro for the tank to hold - 1st boss couldnt hold aggro, 2nd boss killed himself so again we got no loot and no quest credit
![log](https://user-images.githubusercontent.com/16922842/169387722-a05d50c3-e391-4cb3-a4d8-b82290d9c103.png)

**Comment by lilimx** [comment]
Hey,

so this was another character?

**Comment by MightyPhred** [comment]
> Hey,
> 
> so this was another character?

for me it was the same character as i used yesterday, i think the shaman was the same guy i had yesterday and everyone else was different

**Comment by MightyPhred** [comment]
success: issue appears to be fixed
