### ISSUE TITLE
Mob killed itself by using their ability.

### ISSUE THREAD

**Issue by GCXXZ2022** [WarEmu/WarBugs#20106]
After update, I start kill some mobs it call Magma Crawler. It is at Thunder Mountain near Order WC. 

![image](https://user-images.githubusercontent.com/105505897/169010658-6506fbae-9dea-4156-8bf1-04d6dcf34dfc.png)

After I killed them. I can't loot some of them. There is only one reason I can't loot. It is the kills is not mine. I wonder who did? I just made test. And I saw this.

![image](https://user-images.githubusercontent.com/105505897/169011533-17bd746e-4114-4373-b70c-3896d1e65523.png)

Mob use this ability that should give debuff to players kill itself. This mob ability has 10 sec. If the last hit kill by this ability, there is no loot for player. Please fix this problem.

**Comment by lilimx** [comment]
Hey, 

could you re-check if the issue persists?

**Comment by GCXXZ2022** [comment]
I re-checked the issue still there.
