### ISSUE TITLE
SW "No Quarter" tactics bug

### ISSUE THREAD

**Issue by Catch022** [WarEmu/WarBugs#20119]
Good day!
When during the game I apply the "stance dance" then "No Quarter" tactic stops working. "Eagle Eye" cast time becomes 2 seconds. 
This issue only occurs in scenarios. 
Thank you!

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. This issue is already known.
(sorry for the Fix Pending confusion)

**Comment by lilimx** [comment]
dublicate #17950
