### ISSUE TITLE
re-reporting ram bug

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#20115]
previous report got closed owing to hotfix: it didnt work - keep doors are still untouchable and the rvr campaign has now been stuck in the same two zones for about 18 hours

**Comment by lilimx** [comment]
Hey,

The last ticket was about, that the ram hurts itself in its confusion. If it's a different issue, a new ticket would be nice.

**Comment by MightyPhred** [comment]
> Hey,
> 
> The last ticket was about, that the ram hurts itself in its confusion. If it's a different issue, a new ticket would be nice.

somebody else added to that after i made the ticket, my initial report just stated that rams/doors were bugged in some manner that prevented the door being knocked down and thus stalled the rvr campaign

**Comment by lilimx** [comment]
related to #20108
