### ISSUE TITLE
Japor

### ISSUE THREAD

**Issue by Japzor** [WarEmu/WarBugs#20114]
Just relog 3 times now and my gear is still missing !!!! WTF

**Comment by lilimx** [comment]
Hey,

thanks for your report. However we are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- Expected behaviour and actual behaviour
- Steps to reproduce the problem
- Testing Screenshots/Videos/Evidences (always needed)

Here are two guides that will help you:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37703
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Japzor** [comment]
What more do u need????
Screenshot of my char with out gear? REALLY !! Come on.... why cant u not just look at my account and see what is wrong ?
In log in it look like my char got the gear.... but when i log on to them they lose it all... Have lost it on My AM and SM. So no i dont what to log in with my of my char just to see them naked... I can log on my SW and do it all over agein, but for real. if i take a screen just before log in and then when iam in them game, u can just say that i delete the gear..... So dont really see what that will get you...
Look at my account at u can see what is wrong, that it.... Them u know what is going on....
So what do u really want me to do here. Can really take screenshot of it, when it dont really help right ?
Only on my AM i did have enoght to buy new gear. but now i have Willpower gems insto of my armor ....
Just log on to my account then u can see what is going on and then u also know what to do.
I know that Rams are also bug atm so wont really be playing until it is fix. just so u know that iam not online and that you wont log me out.
Hope to hear from you agein when it is fix.
Regards,
Jarl
________________________________

**Comment by lilimx** [comment]
Hey,

When happened it the first time?
You came back after a breake and played again?
Do you have the tome unlocks/wards (Screenshot of your tome)
You've checked the vault in both cities?
Any other weird stuff that happened before (nothing patch related)
We need as much information as possible.

This is the bug tracker, pleae beare in mind that we need as much informationen as possible to trace and reproduce the issue.

**Comment by Japzor** [comment]
First it happen to my AM. All have the gear on in the log in screen. all did look normal there, but when i log on to the game. i was naked. only my staff and trinket was still there, my normal gear was gone. did also see that stuff in the bags was misssing. only got one kind there now. Normal it was full or different sharde like from Sc. also all my royal crest was gone. but when i when to get the now gear i did see that we dont use them anymore. and i did have enoght of the new one to buy my gear back....
ill try to relog alot to see if that helps but no.... my guild told me that might help. Then i log on SM. in the log in she did have the gear and when i was in the game, the same happens agein.... it was also naked..... and on that char i did't have enoght sharde for new gear, but agein my sword and trinket was still there....

iam 100% sure if i log on SW/WL  it will also lose all it gear. and really dont want that evey time i log on the game to see all my char naked beside my AM.......

Ok i to a break from the game. but yesterday i log on the game for the first time in some time. so there was still some mail for my Sm in the mail box, but for sure it have be a log time i have log on my am and they other char.

And no i did't take a screenshotfrom on my AM before i did buy they new gear, just wanted to play...... But it easy to see what i spend on it.

Ok i to a break from the game. but yesterday i log on the game for the first time in some time.

Yes my gear was not in the vault in also my Am has a almost full one and there is not really anymore space there......

Did also see that there where u normal turn in your sc quest that npc was gone.... but maybe it was just move or remove, did't really look into it, just wanted to pvp, but people told me that the rams was bug. so i just join 2 other from my guild in Eateine to ror for 2h before i when to bed.

plz let me know what more i do ?

Regards,
Jarl

________________________________

**Comment by Sandrasfanat** [comment]
I have almost same bug. Fully equiped char on login screen. Naked after login, but all gear was in inventary. Try check bank in dwarf city.
