### ISSUE TITLE
Obliterator Corslet visual bug

### ISSUE THREAD

**Issue by SATANICOMODERNO** [WarEmu/WarBugs#2012]
Hi guys, I don't know if there is any post about this bug already, if yes, sorry and feel free to delete this issue.

As the topic says, the Obliterator Corslet body piece of KoTBS Obliterator's set is visual bugged. When I wear it, my char gets naked as you can see in the pic.

 Thanks!

![hielenia_002](https://cloud.githubusercontent.com/assets/14305777/11448892/6a081c14-954a-11e5-9b80-8bbbf816220e.jpg)

**Comment by Meralors** [comment]
Fixed it now, will be live with next patch ;)
