### ISSUE TITLE
Blurring Shock (swordmaster) internal cooldown bug

### ISSUE THREAD

**Issue by indal-andal** [WarEmu/WarBugs#20129]
Months ago a patch added an internal cooldown to Blurring Shock (swordmaster) and Skull Thumper (black orc) proc limiting how many times it is applied per second. This internal cooldown seems to be bugged or not working at all with Blurring Shock. I haven't had the chance to test Skull Thumper. Can't confirm if its been bugged since last patch or longer.

Screenshot testing it on Praag destro keep's lord

![Warhammer Online - Return Of Reckoning Screenshot 2022 05 23 - 19 53 10 36](https://user-images.githubusercontent.com/61051192/169895698-4c52a713-3cf7-4a20-b619-ad1dee3454b8.png)

**Comment by JackHollowPoint** [comment]
Afaik, it was set to proc no more than 6 times per second (previously was infinite).

**Comment by indal-andal** [comment]
Didn't search the patch so I guess then its working fin
![7](https://user-images.githubusercontent.com/61051192/170115448-efc42cf2-a368-4055-8ea7-05d78d643117.png)
e

**Comment by lilimx** [comment]
Hey,

you're cute...months ago was almost exactly one year ago :D 
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=45076

- Blurring Shock now has a 150ms internal cooldown.

It's 0,15 seconds.....If you can use this information...
So I guess it's working as inteded, if you think it's fishy, please write as soon as possible here, so I can reopen it.
