### ISSUE TITLE
Phoenix's Wings Bug

### ISSUE THREAD

**Issue by Turin99** [WarEmu/WarBugs#20120]
**Expected behavior and actual behavior:** Phoenix's wings used to be an ability that as long as you were in Improved Balance stance you could cast the ability, now it only works if you are within 5 foot of your target. 

**Steps to reproduce the problem:** try and cast Phoenix's Wing while firther than 5 feet from target and in improved balance. 

**Testing Screenshots/Videos/Evidences (always needed):**

![Gillgallad_002](https://user-images.githubusercontent.com/105934044/169582990-1941a668-6ac6-4fd3-ac7f-fe08bb93bb9e.jpg)

**Comment by JackHollowPoint** [comment]
Same as  https://github.com/WarEmu/WarBugs/issues/20107 
Skill is considered melee range (will not work without target) and if works, affects targets in small radius (5 ft?)

**Comment by Undrsiege** [comment]
I was under the impression that any ability that does not have the designation of "SELF" it requires a target to use ability...  If you search the Career builder you can see this pattern.

**Comment by lilimx** [comment]
fixed with patch 27/05/2022
