### ISSUE TITLE
Black Orc Big Slash 

### ISSUE THREAD

**Issue by Zoggof** [WarEmu/WarBugs#20138]
Black Orc ability Big Slash is still bugged, will only work and go off if the enemy is within 5ft, you should be able to freely cast it whenever you are in Da Gud Plan stance. 

Swordmaster had the exact same issue with their counter part ability. 
https://github.com/WarEmu/WarBugs/issues/20120

**Comment by XmatXergon** [comment]
Swordmaster ability Gusting Wind actually works properly, its only Black Orc ability that is not working.

**Comment by manasundae** [comment]
Ive tested and it doesnt work on the target you have highlighted and only hits enemies around the target

**Comment by lilimx** [comment]
Fixed with Patch 16/07/2022
