### ISSUE TITLE
Bastion Stairs left wing boss invisible puddles. 

### ISSUE THREAD

**Issue by unflaggmyaccount** [WarEmu/WarBugs#20135]
The second boss in left wing, one with the dog and lightening puddles(can't remember the name, will pay attention next time). We did wiped it 5 times with sov tank, Despite we were able to see lightening puddles, whole room especially tank was getting much more damage than expected. It looked very alike Gunbad left wing endboss invisible puddles hitting us.

**Expected behavior**
- can avoid damage from puddles

**Actual behavior**
- still receive allot of damage of unknown origin 

**Steps to reproduce the problem:**
- engage in fight with 2nd left wing BS boss, one with a dog

**Testing Screenshots/Videos/Evidences (always needed):**
I will provide screens next time i will enter BS. Was just to frustrated to do any.

Looks to be related to https://github.com/WarEmu/WarBugs/issues/20123 https://github.com/WarEmu/WarBugs/issues/19655

[Sorry for wonky descriptions, I will try add more info my next BS run. Was just to frustrated with this issue when I faced it.]

**Comment by MaxHayman** [comment]
![image](https://user-images.githubusercontent.com/1018809/173941666-f4173bba-cc1f-40ad-adac-dac610ab5e2b.png)

Gahlvoth Darkrage

**Comment by lilimx** [comment]
Fixed with patch [23/06/2022]
