### ISSUE TITLE
Altdorf: Auctioneers and players killed by invisible enemy

### ISSUE THREAD

**Issue by Rubyeclipse-war** [WarEmu/WarBugs#20130]
(Posting this at the request of the world's greatest Dwarf-lover, Kaelang.)

Altdorf Auctioneers and players were hit by random AOE attacks near the AH a few days ago. Auctioneers and even some players were killed, and the Auctioneers then respawned over near Tim the Imbuer. Screenshot of the combat log below.

The attacker is listed as "Something" and the ability used was "Crushing Blow". 

**Testing Screenshots/Videos/Evidences (always needed):**

![auction house npc bug](https://user-images.githubusercontent.com/60584990/169924787-82f15034-15d1-4f4c-89e0-48eec56a355d.png)

Hope this helps!

**Comment by lilimx** [comment]
spooky!

**Comment by lilimx** [comment]
Fixed with Patch 03/06/2022
