### ISSUE TITLE
Keep Lords have replicating blue Lion Auras

### ISSUE THREAD

**Issue by Rubyeclipse-war** [WarEmu/WarBugs#20134]
Somewhere after the latest patch, enemy Keep Lords that Order attacks now display huge blue Lion faces above them, and a bright blue aura around them. (I have not tested this on Destro yet.)

This ability appears once combat begins and continues replicating itself during a fight, stacking over and over and dropping the framerate considerably for players who may be displaying all abilities.
**Steps to reproduce the problem:**
Siege a keep as Order and engage the Keep Lord.

**Testing Screenshots/Videos/Evidences (always needed):**

![Blue Lion](https://user-images.githubusercontent.com/60584990/170415845-4acc9eac-5a47-472e-bf73-f0ab61b3c21d.png)

**Comment by lilimx** [comment]
Creepy

**Comment by Kaelang** [comment]
Effects all lords, Order & Destro.

**Comment by Ruin-84** [comment]
I do belive this is connected to The Lords abilities, usualy the first head apears when Lords usues an abiltity coneected to words "TAKE THAT", and then it does not dispaear. but the next time its used it shows again.

**Comment by lilimx** [comment]
Fixed with patch 01/10/2022
