### ISSUE TITLE
parry

### ISSUE THREAD

**Issue by vithoria** [WarEmu/WarBugs#2013]
thk there is a bug on Perry since, ppl is capable of parry attacks when u hit them from behind, abillitys like WE knock Down, and spine crusher i see so often parry on those.. and they shouldn't be able to be parried... since it's from behind

**Comment by Evildoor** [comment]
I do believe it is the same problem as with Heartseeker not working - lag.

**Comment by vithoria** [comment]
how can u even blame lag, this is abilltys only being able to be used when u are behind ergo... no parry... lag can't affect that when u hit u are behiind ergo abillity shll hit

**Comment by Evildoor** [comment]
And? If you are attacking someone from behind who stands perfectly still and does not moves or turns - sure, there is a bug indeed - but this has to be proven. Otherwise, if this is a normal combat situation, where everyone runs around each other, then it is highly possible that lag interferes. And i do remember it even on life, all those "OMG I 100% WAS BEHIND HIM AND CANNOT KNOCKDOWN HIM WTF BUGGY WARHAMMER" of my friends in Vent.

**Comment by ozarmidrashim** [comment]
Per Evildoor. You need to understand that you making an attack on an enemy when you appear to be behind them /on your client/ means absolutely nothing. It's the server's opinion that matters, and they could have a completely different rotation on the server at the time your attack is processed.

**Comment by MKorin** [comment]
For me WE's KD never was parried, nothing in log just CD on skill, it happen when target is on edge of range.

**Comment by noisestorm** [comment]
I believe u are perhaps using Feinted Positioning and get parries when the knockdown is actually being used from front/side cones :o

**Comment by vithoria** [comment]
atm i wun a bild on WE that requirer i wait to after KD with using feinted position

**Comment by Evildoor** [comment]
Main question was answered by me and confirmed by Azarael. KD going on cooldown without effect mentioned by @MKorin can happen to any skill when client thinks that skill went off, but server does not (maybe lag affects this as well). However, that issue has nothing to do with parry, and i'm not sure if we can do anything about it. Closing this.
