### ISSUE TITLE
Magus - Dissolving Mist

### ISSUE THREAD

**Issue by Rubnim** [WarEmu/WarBugs#2014]
Hey, today I recognised that the Magus that is skilled in the Path of Changing has a Little bug with the ability "Dissolving mist". 
The mist dose work, thats noch the Problem, but if you have the tactic "Deamonic Reach" (+25% range) it is shown that it's possiible to place the dissolving mist 80ft away and you will get cooldown time on that ability, BUT the dissolving mist wouldnd be there at 80ft away - if you place the dissolving mist in the range of 60ft it will work, but not at 80. 
I compared it with a friend on with his sorcerer (pit of shades). 

So I cant really detect if it is a Problem with the +25% range tactic or if it is a Problem with the dissolving mist. All the other abilities in the path of changing tree are working with the +25% range. Thats Kind of weard.

**Comment by Evildoor** [comment]
Two bugs.
1) Mist + Reach do not interact as they should, same with Engi's Napalm - #1985.
2) Ground target abilities fail and go on CD if used out of range - #1118.
I'm closing this since Mist and Napalm are pretty much the same, so we'll use #1985 as a report for this issue.
