### ISSUE TITLE
some bugs about the ward

### ISSUE THREAD

**Issue by morgansergey** [WarEmu/WarBugs#20145]
**Expected behavior and actual behavior:**
![image](https://user-images.githubusercontent.com/106448491/170858837-f5356e8c-c762-4b82-88c2-8b00e1dd4d30.png)
have Helm but the system says no
![image](https://user-images.githubusercontent.com/106448491/170859009-e6711cf2-2053-4795-bcbd-0bec9f455431.png)
not have Shoulders but the system does

![image](https://user-images.githubusercontent.com/106448491/170859147-c92fab92-3fdf-4079-ab55-e4df1523c400.png)
![image](https://user-images.githubusercontent.com/106448491/170859171-b666d463-788a-4dc0-ad5f-82de0735b474.png)
Cannot equip this item

![image](https://user-images.githubusercontent.com/106448491/170859481-4815da23-5568-4f6e-a0d6-248bad2331a9.png)
This ward is missing some options
Prevents me from buying next tier gear
![image](https://user-images.githubusercontent.com/106448491/170859641-bc3b7693-6f82-455d-a1d4-cc1eaebb38b9.png)

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Dalgri** [comment]
I can confirm, bloodlord helmet is not counting towards the invader ward.

**Comment by lilimx** [comment]
Hey,

please read the template inside the box. Only one issue per ticket.
