### ISSUE TITLE
No ability buffer in place after long cast times

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#20144]
**Expected behavior and actual behavior:**

A recent patch has implemented an ability queue system to prevent gaps between abilities. If the cast time of the ability is below the global cooldown time then the subsequent ability press will be queued up to execute the moment the GCD ends. However, if casting an ability with a long cast time (such as a Zealot's group heal) and then press another ability near the end of the cast, that next ability is ignored by the server and nothing happens after the current ability has finished casting.

This means that there will still be gaps between abilities based on framerate, lag and player timing if doing back-to-back long casts.

**Steps to reproduce the problem:**

1) Be on a Zealot
2) Cast Elixir of Dark Blessings or Dust of Pandemonium
3) As the cast is nearly over, press ability
4) The ability you pressed in step 3 will NOT activate when the cast is finished

**Semi-related bug**

Another category of abilities not functioning properly with the ability queue system: https://github.com/WarEmu/WarBugs/issues/20141

**Comment by lilimx** [comment]
Hey,

so I did a test again and It looks like it's working as inteded.
Guess the #20141 fix, fixed that too.
