### ISSUE TITLE
[Armor/Weapon Ward] Ward System changes don't affect Bloodlord weapons and Sentinel Jewel

### ISSUE THREAD

**Issue by wilesa** [WarEmu/WarBugs#20142]
**Expected behavior and actual behavior:**

Expected behavior: 
* Be able to equip bloodlord weapon with full vanquisher unlocked
* Be able to equip sentinel jewel with full conqueror unlocked

Actual behavior:
* Both still require full set of previous PvE gear

**Steps to reproduce the problem:**
Have vanquisher ward unlocked but no PvE set completed
Try to equip either bloodlord axe or sentinel jewel

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/12731177/170792238-8fd13c2c-133d-4b65-a294-34774ee9e343.png)
![image](https://user-images.githubusercontent.com/12731177/170792338-66d22a08-bad1-423c-85bb-6b119f43433b.png)
![image](https://user-images.githubusercontent.com/12731177/170792367-561e651b-99a5-4b18-a138-eb8ebdebf652.png)

**Comment by lilimx** [comment]
Hey,

so I a little research...it's actually no bug so far. Dev's are aware and should come soon.

![image](https://user-images.githubusercontent.com/23266079/170815798-8afb4f5e-05cd-49a1-be57-516499e7ddb6.png)

**Comment by dalen** [comment]
same as https://github.com/WarEmu/WarBugs/issues/20163, fix pending
