### ISSUE TITLE
[Armor Ward] Decimator Armour Requires Recruit Ward to Equip

### ISSUE THREAD

**Issue by apache140** [WarEmu/WarBugs#20143]
Expected Behavior:
Decimator Armour should be equipped to contribute to the Recruit Ward

Actual Behavior:
Decimator Armour requires the Recruit Ward to contribute to its own ward.

![image](https://user-images.githubusercontent.com/99094843/170794880-819b20db-32f6-4f47-beaf-df3f6523eddc.png)

![image](https://user-images.githubusercontent.com/99094843/170794939-f893351f-ebe8-4140-94b8-f8251baec3f0.png)

Same for the Boots

**Comment by Zomega-WAR** [comment]
Already fixed internally:

![image](https://user-images.githubusercontent.com/60266177/170797860-2b88a05f-4c3a-4eba-b065-9911a06d0208.png)

**Comment by morgansergey** [comment]
![image](https://user-images.githubusercontent.com/106448491/170838813-504c54a6-47d2-4a75-bf21-3c560633a0e4.png)
Forgot to add options here

![image](https://user-images.githubusercontent.com/106448491/170838925-f4e9c937-c468-4b8c-9f14-1e2dd7bfe392.png)
This is Pin needs to modify his ward

**Comment by lilimx** [comment]
@morgansergey ?

**Comment by morgansergey** [comment]
The picture above is that I have a whole set of PQ equipment, but there is no activation condition, only RVR and SC equipment can be activated


The picture below is "Purple Jewelry". His wearing condition has not been corrected. "Greater Ward" This should not be able to be worn.

google translate

**Comment by lilimx** [comment]
Hey,

please, open a new ticket. This one is actually solved and has nothing to do with your current issue.
