### ISSUE TITLE
[Armor Ward] Can't Equip Sentinel Rend Ring

### ISSUE THREAD

**Issue by Tzwaenson** [WarEmu/WarBugs#20153]
**Expected behavior and actual behavior:**
Can equip the Item
Can't equip the Item

**Steps to reproduce the problem:**
Try to equip the Sentinal Rend Ring, other Sentinal Items like Chest or Belt works.

**Testing Screenshots/Videos/Evidences (always needed):**

!

![2022-05-31 20_20_01-Warhammer_ Age of Reckoning, Version 1 4 8, Copyright 2001-2012 Electronic Arts,](https://user-images.githubusercontent.com/106621660/171257673-5c584b58-6686-4a30-9d5e-8dc1fd29aae7.jpg)

**Comment by lilimx** [comment]
Hey,

could you post your ToK from Redeye and Sentinel?

**Comment by Tzwaenson** [comment]
Yes, for sure i do it tomorrow its late. But i dont have any redeye pieces. I think since one of the last Updates its Not More requiered.

**Comment by Tzwaenson** [comment]
soooo here the screens from the ToK and a equipt Sentinal Piece
![wear sentinal,](https://user-images.githubusercontent.com/106621660/171347901-94ae153f-1837-4bd5-aa7f-24008ab7f3f8.jpg)
![sentinal,](https://user-images.githubusercontent.com/106621660/171347902-a323104f-242e-4477-aee5-84bcdc4f6383.jpg)
![all,](https://user-images.githubusercontent.com/106621660/171347903-9a15c6d4-4fef-49a4-a8c2-39dc5363b026.jpg)
.

**Comment by dalen** [comment]
Already fixed
