### ISSUE TITLE
Feeding on Weakness: Ability Modifier Error

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#20150]
Above 30 Hatred the skill causes an error message in the chat log:
Ability Modifier Error: Feeding On Weakness (9316) modifier Entry: 9316, Affecting: 9316, Id: 0, Command: (2,0): Command 0,1 not found in ability 9316

Likely related to the also wrong implementation of the skill. (Known issue and also mentioned in https://github.com/WarEmu/WarBugs/issues/19783)

30 Hatred: (should be 25% of damage done as healing - correct)
Your Feeding On Weakness hits Target Dummy for 447 damage.
Your Feeding On Weakness heals you for 0 points. (111 overhealed)

60 Hatred: (should be 50% of damage done as healing -> still 25%)
Your Feeding On Weakness hits Target Dummy for 447 damage.
Your Feeding On Weakness heals you for 0 points. (111 overhealed)

90 Hatred: (should be 75% of damage done as healing -> still 25%)
Your Feeding On Weakness hits Target Dummy for 447 damage.
Your Feeding On Weakness heals you for 0 points. (111 overhealed)

It's spamming my chat, please fix. :)

**Comment by lilimx** [comment]
Hey,

as you correctly mentioned it's already reported :D
