### ISSUE TITLE
Troll Country, Empire quest, Cltivating Decay

### ISSUE THREAD

**Issue by Khan-D-Man** [WarEmu/WarBugs#20167]
After progressing the quest to the point where you have to kill the 4 Rift Horrors and 4 Rift Flamers, once You kill these your then instructed to go on to find the Cart of Tainted Grain.  However when you get to the cart and attempt to interact with it nothing appears to trigger the quest completion or progression.  Attacking the cart doesn't do anything, and clicking on the Tainted grain from the quest inventory doesn't seem to do anything either.  Left and right clicking on the cart just targets the cart and I can't see any way to progress forward.

**Comment by Kaelang** [comment]
You need to leave the zone and come back so that the GameObject can be correctly updated and you can click on it. Tested a few times and works by simply leaving the area so it reloads.

This is an issue but we do have tickets open already for problems like this so I'm going to close this one.
