### ISSUE TITLE
Set bonus dont work

### ISSUE THREAD

**Issue by blackoffff** [WarEmu/WarBugs#20160]
Set bonus number 6 dont stuck with class ability for Dok (bloodlord set)
Only 1 debuff works. Its a not fair. Fix it.
![image](https://user-images.githubusercontent.com/106673263/171401671-80c6bedd-3654-4b2b-89b5-6d004a55c4e8.png)

U can change reduce tougness to reduce initiative/armor/wounds or fix stack. Or just change set bonus for +% speed run, or 5% crit, or something else. Now this bonus is useless

**Comment by Zomega-WAR** [comment]
Procs from armour sets as well as career abilities are in the same stacking group, so only the strongest one is applied. This is not a bug and applies to all procs from armour sets.

This sounds like less of a bug report and more of a complaint or request for different bonuses, in which case you should post a proposal on the forums instead (https://www.returnofreckoning.com/forum/viewforum.php?f=15)

**Comment by blackoffff** [comment]
> Procs from armour sets as well as career abilities are in the same stacking group, so only the strongest one is applied. This is not a bug and applies to all procs from armour sets.
> 
> This sounds like less of a bug report and more of a complaint or request for different bonuses, in which case you should post a proposal on the forums instead (https://www.returnofreckoning.com/forum/viewforum.php?f=15)

no its issue, because other classes have useful bonuses, only dok have useless bonus number 6

**Comment by lilimx** [comment]
Hey,

it's not a bug. If you want to discuss it, please use the forums.
