### ISSUE TITLE
Something's Disorienting Blow hits friendly targets (players and NPCs)

### ISSUE THREAD

**Issue by Talladego** [WarEmu/WarBugs#20164]
**Steps to reproduce the problem:**
1. Enter Sigmar Crypts
2. Aggro the nearest mobs
3. Run and exit the instance before entering combat.
4. You will now cause damage to friendly targets around you including friendly players.

**Testing Screenshots/Videos/Evidences (always needed):**
![Something](https://user-images.githubusercontent.com/45210243/171527532-8b258304-dce0-4c6f-80ce-1d46b2abded4.jpg)
![Something2](https://user-images.githubusercontent.com/45210243/171527981-90e241f6-86ed-4ae6-a412-0b20f9898532.jpg)
![Something3](https://user-images.githubusercontent.com/45210243/171529486-905d330b-2bbf-4eca-bb55-6201bbd79a26.jpg)

Relogging removes the damaging aura.

**Comment by lilimx** [comment]
Creepy

**Comment by Talladego** [comment]
You get no feedback that you are causing aoe damage, only the receiving end sees the damage.

**Comment by lilimx** [comment]
Fixed with Patch 03/06/2022
