### ISSUE TITLE
WL Morale 1 bug

### ISSUE THREAD

**Issue by magter3001** [WarEmu/WarBugs#2016]
WL Morale Ensnare by passes snare and root immunity. My Choppa's Shrug it Off was supposed to give me immunity for 10 seconds but a WL's Morale 1 ignored it and rooted me anyway. It should work like a Tank's Champ Challenge, where the target cannot have the punt/root immunity, any ability immunities like Shrug It Off or any Morale immunities like Focused Mine to work.

Don't know if Marauder morale does the same thing or not.

**Comment by Evildoor** [comment]
Champion's Challenge is an unique skill and Ensnare should not work in exactly similar way. Otherwise, report is correct - Ensnare should respect Shrug It Off and other immunity sources.

**Comment by Morksezstop** [comment]
but did focused mind prevent for rooting you with champion challange cos on live it did. If you have FM on you the champ challange root only the tank.

**Comment by Evildoor** [comment]
Champion's Challenge has its own issue: #1167, use it if you want to contribute something. This issue is about Ensnare.
