### ISSUE TITLE
[Armor Ward] Inconsistency in tooltip info

### ISSUE THREAD

**Issue by zulnam** [WarEmu/WarBugs#20163]
STR:
1. Have a piece of Sentinel or Bloodlord gear and a piece of Conqueror or Vanquisher gear in your inventory.
2. Inspect tooltips.

Expected:
Both tooltips should make reference to the same ward unlock requirement.

Actual:
PvE gear still makes reference to Lesser/Greater Wards

**Comment by lilimx** [comment]
Fixed with Patch 16/07/2022
