### ISSUE TITLE
Chosen Oppressing Blows Only Gives 1% Crit

### ISSUE THREAD

**Issue by blackabyss187** [WarEmu/WarBugs#20168]
The Chosen's Oppressing Blows states that it increases the melee crit rate by 15% when wielding a great weapon, however, when a great weapon is equipped it only increases it by 1%.

**Comment by blackabyss187** [comment]
Attached are screenshots.
![Blackswordsman035](https://user-images.githubusercontent.com/64327008/172094748-b12adf8e-1e12-4ac2-a1db-a58e460fd3b5.jpg)
![Blackswordsman036](https://user-images.githubusercontent.com/64327008/172094749-349717d3-eac9-440c-a8b1-3ad97ad15eb1.jpg)

**Comment by lilimx** [comment]
Hey,

paperdoll stats are no reliable source. 
Please do a new test and check your stats with the command:
.getstats

**Comment by blackabyss187** [comment]
Okay that's accurate then. it shows the correct amount.
