### ISSUE TITLE
[Armor Wards] Weapons with ward requirements still require pve set unlocks

### ISSUE THREAD

**Issue by zulnam** [WarEmu/WarBugs#20162]
STR:
1. On a character, equip full conqueror set.
2. Acquire a weapon or off-hand from CnT or BB/BE via the influence rewards.
3. Attempt to equip the weapon.

Expected:
Weapon should be equippable.

Actual:
Action fails with the following User Error:

"_You don't have required [sic] Tome of Knowledge entry to equip this item: Completed Redeye Armor Set._"

**Comment by lilimx** [comment]
Hey,

this issue is already reported.

**Comment by lilimx** [comment]
dublicate // related to #20142
