### ISSUE TITLE
Map Issue

### ISSUE THREAD

**Issue by yogurtlumucver** [WarEmu/WarBugs#20177]
have a map issue, cant see some maps and fly points like new sc's and karak peaks

i repaired ror and nothing changed
![settra loading](https://user-images.githubusercontent.com/95940041/173179133-eb0c18fb-78d7-4bc4-98dd-5fb34e63f16b.jpg)
![settra map](https://user-images.githubusercontent.com/95940041/173179138-57d5e0b8-36e1-46ac-8d03-f850e1a0e045.jpg)
![karak eight peaks](https://user-images.githubusercontent.com/95940041/173179150-9f23ce67-5517-430e-8a04-7af64d8457d4.jpg)

**Comment by lilimx** [comment]
Hey,

is this a fresh install?

**Comment by yogurtlumucver** [comment]
nope old...

should i install another driver ???

**Comment by lilimx** [comment]
Hey,

nope. It has nothing to do with your driver :D 
Maybe your game went broken after the last update...and sometimes the repair function can't fix it. So you can try a fresh install.

Jump here to the direct download: https://returnofreckoning.wetransfer.com/downloads/93f09b8507ab0a4d349741cb6204771c20220523222603/bab7bc

and here for the install guide (start at the point directory rights):
https://www.returnofreckoning.com/forum/viewtopic.php?f=113&t=45103

**Comment by yogurtlumucver** [comment]
download new ror and installed but now i have problem with "click" items and "mouseover info" they not workin with new download :( im still playin with old download and issue not solved yet :)

**Comment by lilimx** [comment]
Hey,

I would really recommend you to join the RoR discord. 
So we can check your install and can try other things on the fly

**Comment by MaxHayman** [comment]
Please join the RoR Discord for further support.

**Comment by lilimx** [comment]
Note: it was an install issue.
