### ISSUE TITLE
Tracker Set

### ISSUE THREAD

**Issue by PTWar** [WarEmu/WarBugs#2017]
Into the Flames Quest which requires you to kill 20 Black Guards doesent work. No matter how many Black Guards you kill it stays always at 0 thus making it impossible to get the Tracker Set...

**Comment by noisestorm** [comment]
General issue with Dark and Highelfs atm. Will be fixed once the Database is pushed afaik (same applies for the DoK and AM quest from the stalker gear currently)

**Comment by Ryanfawkez** [comment]
This has been fixed since the latest patch. Close please.
