### ISSUE TITLE
Cannot login to game after loading screen

### ISSUE THREAD

**Issue by wildwindblows** [WarEmu/WarBugs#20178]
Hello ROR Bugtracter Team

I cannot login to game after loading screen. This happens when i try to login with my mara and there is no such an issue with my other alts.

**Steps to reproduce the problem:**
Launcher->character selection screen->pick mara->loading screen-> back to character selection screen like below or game crash

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/45720515/173179650-7e3d3c8f-8ac7-4460-b921-2df3fe80c6a7.png)

![image](https://user-images.githubusercontent.com/45720515/173179857-d637bd9b-90e6-4dbc-8548-14b9794a01b4.png)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
We are aware of this kind of issue. When did it happen would be more interesting.

In the meantime, please add your character name and issue here: https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=46249

**Comment by wildwindblows** [comment]
I posted character name on the post. I had no such an issue yesterday. Today, i tried to login and this happened.
Thanks.

**Comment by lilimx** [comment]
Hey,

so you logged out properly?

**Comment by MaxHayman** [comment]
Can you try now

**Comment by wildwindblows** [comment]
I can log now. Thanks.

**Comment by MaxHayman** [comment]
Thanks.
