### ISSUE TITLE
Log problem

### ISSUE THREAD

**Issue by steoptus** [WarEmu/WarBugs#20176]
When I try to connect with my character, I load into the void, and this bug is no longer there when I get kicked from my guild.

Thank to Bazgob da shaman to find the source of the problem !

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
We are aware of this issue and only a guild kick resolves this issue.

Please add your character name and issue here: https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=46249
