### ISSUE TITLE
Weekend Warfront: RAIDERS OF THE LOST PYRAMİD Bugged

### ISSUE THREAD

**Issue by wildwindblows** [WarEmu/WarBugs#20175]
Hello ROR Bugtracker Team,

When I checked weekend warfront sc quests, i saw that i already finished them. I haven't started yet to do warfront sc so i think it is bugged. I'm posting related photos below. Also, I checked warfront inf. from one of my alt and i see no issue.

**Expected behavior actual behavior:**
It supposed to be no inf. when i log to game because i haven't started to do sc.

**Steps to reproduce the problem:**
Log in to game and check live events. See that you already finished.

**Testing Screenshots/Videos/Evidences (always needed):**
![Sirzero_036](https://user-images.githubusercontent.com/45720515/173105811-eb35991d-2bd7-4c03-b0c5-ff7e553783b7.jpg)

![Sirzero_037](https://user-images.githubusercontent.com/45720515/173105832-ca14ad4c-8f85-44da-ad29-c34392335a9a.jpg)

Thanks.

**Comment by Xflame9** [comment]
Same problem.

**Comment by lilimx** [comment]
Hey,

let's wait right after the patch :D

**Comment by wildwindblows** [comment]
This bug occurred after the today's patch.

**Comment by lilimx** [comment]
Devs are on it

**Comment by GamesBondd** [comment]
This shouldn't have been the weekend warfront and it was labeled as done because the "end date" was wrong.
