### ISSUE TITLE
Guild Bug

### ISSUE THREAD

**Issue by wildwindblows** [WarEmu/WarBugs#20181]
Hello ROR Bugtracker Team,
Although im in TheFatSquigs guild, game saying that im not in a guild. Meanwhile I can write from guild chat and guild members can see it. You can see related photo below and conversation with guild members below.

**Expected behavior and actual behavior:**
My guild friends can see me as a guild member so when i open guild screen i should see the guild.

**Steps to reproduce the problem:**
After hotfix today, this problem occurred. Login to game and see you are not in a guild. However, guild members can see you as a guild member and you can talk with them from guild chat.

**Testing Screenshots/Videos/Evidences (always needed):**

![Sirzero_044](https://user-images.githubusercontent.com/45720515/173188058-17f047a3-ab10-49f6-b2ca-01dabec537a5.jpg)

Thanks.

**Comment by MaxHayman** [comment]
Does this happen after a relog or a one off

**Comment by wildwindblows** [comment]
I can see guild without no issue now. It seems problem solved. FYI. Thanks

**Comment by MaxHayman** [comment]
Thanks. Let us know if it happens again.
