### ISSUE TITLE
Marauder: Face is changing with stance

### ISSUE THREAD

**Issue by wildwindblows** [WarEmu/WarBugs#20180]
Hello ROR Bugtracker Team
Marauder face is changing when i swap stance. Each stance have different face as shown below.

**Expected behavior and actual behavior:**
Face should stay same after switching stance

**Steps to reproduce the problem:**
Pick a marauder and switch stance. See your face is changing like below after each stance.

**Testing Screenshots/Videos/Evidences (always needed):**
No Stance
![Sirzero_038](https://user-images.githubusercontent.com/45720515/173187459-004bf6e8-ae19-4776-9738-328ecd6ee1cd.jpg)

Sav Stance
![Sirzero_039](https://user-images.githubusercontent.com/45720515/173187464-13192119-97ae-4594-95b0-25b746f27bd6.jpg)

Brut Stance
![Sirzero_040](https://user-images.githubusercontent.com/45720515/173187469-26df34a6-c6ea-4c65-ab96-600bdf14dd1b.jpg)

Monstro Stance
![Sirzero_041](https://user-images.githubusercontent.com/45720515/173187473-9a4a3375-ca80-4e9b-9258-974c28de5eb6.jpg)

Thanks.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
This issue was already reported a while ago.
I will add your ticket to the related one.

**Comment by wildwindblows** [comment]
I realized that "Signet of the Cursed Company" Item is needed to be use first to this visual bug happen so I'm updated "Steps to reproduce the problem" above.

**Comment by lilimx** [comment]
dublicate of #13962

**Comment by wildwindblows** [comment]
Thanks for quick feedback, in post #13962 it is not mentioned about "Signet of the Cursed Company"". This visual bug is happening after using "Signet of the Cursed Company"" item (skeleton transformation). FYI.
