### ISSUE TITLE
"Too many Quests" (Event quest "Putting death in its place")

### ISSUE THREAD

**Issue by steoptus** [WarEmu/WarBugs#20188]
I cant take this quest, the game tells me " too many quest " but I have the place for lot of quest

**Comment by lilimx** [comment]
![image](https://user-images.githubusercontent.com/23266079/173241664-75851790-e6e9-4e28-9be4-ab3e71d77999.png)
pic from disc

**Comment by lilimx** [comment]
also:
![image](https://user-images.githubusercontent.com/23266079/173241691-97d619c5-5d6c-4844-a7ea-a2ca642ca150.png)

**Comment by lilimx** [comment]
and:
![image](https://user-images.githubusercontent.com/23266079/173241718-e7e83375-99c4-4cee-8b8f-535d8ec74106.png)

**Comment by MaxHayman** [comment]
Maybe to do with kill collectors

**Comment by GrandBillKing** [comment]
Same problem, i have zero quests and ressive this massadge "TOO MANY QUESTS"
![Screenshot_4](https://user-images.githubusercontent.com/107405373/173340568-df709fe2-ba16-42b1-ab5e-47448525bc1f.png)
![Screenshot_5](https://user-images.githubusercontent.com/107405373/173340573-8d48eb2a-2e80-4ccd-ad5c-5ba475579f9b.png)

**Comment by steoptus** [comment]
in fact, it's for all quests

**Comment by lilimx** [comment]
Hey,

thanks for all the feedback. The fix is pending and it will deployed with the next server restart or patch.

**Comment by MaxHayman** [comment]
Fixed

**Comment by GamesBondd** [comment]
As tested today, invisible quests may be preventing you from taking more quests. You will have to wipe out your whole list of quests manually in order for the invisible ones to appear and then you could remove them too.

This will allow you to accept more quests again and resume questing normally.
