### ISSUE TITLE
twitch link

### ISSUE THREAD

**Issue by skonark** [WarEmu/WarBugs#20182]
Hi I am trying to link my main ROR account for the twitch rewards but when I put in my user name and password on the ROR forum to link it tells me that one of them is wrong yet I can log into game with them just fine. I managed to claim 2 rewards yesterday with my main chars for some reason it disconnected now I cant get it to work.

**Comment by lilimx** [comment]
Hey,

what's your account name?

**Comment by skonark** [comment]
fangour

**Comment by GamesBondd** [comment]
> fangour

Please unlink from your Twitch account and make sure you're logged to the right account on the forum before linking again. There's no issue with the linking as we've been doing it for a while now and that's the first report, so most likely a tech issue from your side.

**Comment by skonark** [comment]
yeh logging into the account on forum is the problem tells me the password or user name is wrong but ill keep trying it thank you for response.
