### ISSUE TITLE
Event quest - Ostland

### ISSUE THREAD

**Issue by Rebiff** [WarEmu/WarBugs#20183]
"inspect a source of necromantic power near Kinschel's stronghold" has not been spawning the past couple hours. many people have been sitting here for 30min+ waiting for it to spawn

![image](https://user-images.githubusercontent.com/91923176/173196759-8aa93f4c-2f9e-462e-bacc-a4f51d1b374e.png)

**Comment by Rebiff** [comment]
event quest fixed, ill close issue

**Comment by lilimx** [comment]
fixed with Hotfix 12/6/2022
