### ISSUE TITLE
call war lion bug

### ISSUE THREAD

**Issue by belithien** [WarEmu/WarBugs#20199]
Hi,

after I changed my mastery, I am not able to call my lion any more. the button call war lion starts to load, than suddenly stops.

please help! thanks

**Comment by lilimx** [comment]
Hey,

any errors? What have you changed? Tactics too?

**Comment by belithien** [comment]
hi,

thanks, I found the problem! I changed the tactic, that was the issue....tahnks for your help and reply!

best regards

belithien
________________________________
Von: lilimx ***@***.***>
Gesendet: Mittwoch, 15. Juni 2022 10:55
An: WarEmu/WarBugs ***@***.***>
Cc: belithien ***@***.***>; Author ***@***.***>
Betreff: Re: [WarEmu/WarBugs] call war lion bug (Issue #20199)


Hey,

any errors? What have you changed? Tactics too?
