### ISSUE TITLE
Book out of fort crash

### ISSUE THREAD

**Issue by Onlyendari** [WarEmu/WarBugs#20190]
Every time I try to book out of a fort the game just hangs on the loading screen, I am bound to Altdorf.

**Comment by lilimx** [comment]
Hey,

could be also an update issue. You've tried repair or a fresh install?

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persists, please open a new ticket with proper evidences.
