### ISSUE TITLE
Bloodlord ward SM mixed up

### ISSUE THREAD

**Issue by Ybilla030** [WarEmu/WarBugs#20191]
Bloodlord ward for SM is mixed up, belt (BO instead of SM) which leads to no ward unlock. Reequipping or relogging doesn't fix it, neither did a server restart.

![Screenshot (404)](https://user-images.githubusercontent.com/55945548/173287529-e80622e0-049c-4975-8ad7-a410873d4aa8.png)
![Screenshot (407)](https://user-images.githubusercontent.com/55945548/173287533-c7fe7dc1-26dc-454c-92d3-d50d049e5928.png)

**Comment by lilimx** [comment]
Fixed with Patch 23/06/2022
