### ISSUE TITLE
Thanks for the gold??

### ISSUE THREAD

**Issue by KalvinYetter** [WarEmu/WarBugs#20198]
Zoned out of Pragg to Kadrin's Valley, after arriving in Kadrin I noticed a message stating I received 345572 gold.  I checked my bag and noticed I had gone from 595 gold up to 34614.  Noticed another thread that received gold (6K) this way, but when they went to Altdorf the gold was gone.  I have gone to Altdorf, as well as reloaded the UI and still have the gold in my bag.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Kallvyn_000](https://user-images.githubusercontent.com/107517301/173704171-58e4a5fc-90fa-4426-b6e6-c3e2382edb15.jpg)

**Comment by KalvinYetter** [comment]
I think my starting gold was 576, not 595.

**Comment by KalvinYetter** [comment]
Gold is back to 576 in my bag now (plus whatever silver and copper I had)

**Comment by KalvinYetter** [comment]
Zoned back into Kadrin and same thing happened again. Tried to type in an amount in a trade window but it says I do not have that amount (any amount over the original 576) even though it stats I have over 34k gold on me.

**Comment by KalvinYetter** [comment]
FYI-this seems to happen every time I zone; not a big deal because the gold is not actually there so I am not able to spend/use it.  After a bit my correct amount of gold will show in my bags.

**Comment by lilimx** [comment]
Hey,

Could be also a connection issue or lag....hm ... 
Guess it's similar to the issue that people got throw back to rr1 and ding to their actual after they gained rr. Or people who dinged to rr 234 after lag :D

**Comment by geezereur** [comment]
Had the same thing on 2 char its a visual bug.

**Comment by MaxHayman** [comment]
Should be fixed
