### ISSUE TITLE
Mace of the Dead doesn't apply to Rapture as appearance

### ISSUE THREAD

**Issue by Aaasmund** [WarEmu/WarBugs#20196]
**Expected behavior and actual behavior:**
Rapture is a hammer, Mace of the Dead is a hammer too. I expect that it should apply as appearance.

**Steps to reproduce the problem:**
Put Rapture on, click Appearance, right-click on Mace of the Dead or drag and drop it to main hand slot.

**Testing Screenshots/Videos/Evidences (always needed):**
![Asmunder_124](https://user-images.githubusercontent.com/107465980/173550635-5aebebc3-c8ee-42aa-a8bd-889e59086344.jpg)

**Comment by lilimx** [comment]
Fixed with patch [29/06/2022]
