### ISSUE TITLE
DESTRO QUEST "Sacking of Nordland"

### ISSUE THREAD

**Issue by Hauclir** [WarEmu/WarBugs#202]
![hauclir_002](https://cloud.githubusercontent.com/assets/7598530/3489431/b17bab2e-052c-11e4-97c3-ca29dba1122d.jpg)
![hauclir_004](https://cloud.githubusercontent.com/assets/7598530/3489433/b5eec600-052c-11e4-8c46-a6cb330a3590.jpg)
![hauclir_001](https://cloud.githubusercontent.com/assets/7598530/3489434/ba800eea-052c-11e4-9699-228d9afc0211.jpg)
NPC QUEST GIVER: Sythlyn the Marked
Both the Kindling and Spices are not interactable to finish quest.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
