### ISSUE TITLE
Broken Quest in Altdorf "Spotting Trouble"

### ISSUE THREAD

**Issue by WickedPiston** [WarEmu/WarBugs#20205]
**Expected behavior and actual behavior:**
Should be able to interact with the "Floating Corpse," but for some reason it just does nothing. Making the quest incompletable.

**Steps to reproduce the problem:**
Accept "Spotting Trouble" Quest from Watchman Terrence at the Docks in Altdorf

**Testing Screenshots/Videos/Evidences (always needed):**

https://user-images.githubusercontent.com/107617937/174052208-1ddaeee5-7c94-4f9c-8f66-48d81737f4e1.mp4

https://user-images.githubusercontent.com/107617937/174052235-7465547f-7ede-41ab-9dcd-d19384ad1330.mp4

https://user-images.githubusercontent.com/107617937/174052256-e01451ed-9b75-4d64-a3ba-1c7e47fc6f6d.mp4

![Screenshot (212)](https://user-images.githubusercontent.com/107617937/174052317-edbe2085-9b6f-4e34-9b6d-82e2fa9a44e9.png)

![Screenshot (213)](https://user-images.githubusercontent.com/107617937/174052345-463e6e4e-4ffe-4477-bc84-bac65cb8bc1f.png)

![Screenshot (214)](https://user-images.githubusercontent.com/107617937/174052281-1713c27c-d07d-4026-afd9-43f7d0066c93.png)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. This issue is known and already on our bug tracker.
I will close this ticket and add it to the related one.

**Comment by lilimx** [comment]
dublicate/related to #18784
