### ISSUE TITLE
Blackguard Blade of Ruin

### ISSUE THREAD

**Issue by Hauclir** [WarEmu/WarBugs#2020]
I can use this skill fine on non players, but against other players once it lights up and i click to use it, it does not work.

**Comment by ozarmidrashim** [comment]
![bgg_000](https://cloud.githubusercontent.com/assets/6764164/11451448/7c709948-95be-11e5-9624-cf9bc6b8418c.jpg)

**Comment by Hauclir** [comment]
try doing it on the go/while moving if it still works for you then its probably my end...

**Comment by Hauclir** [comment]
working fine now i didn't see anything relating to this in the notes in the recent update but w/e it was it fixed it.
