### ISSUE TITLE
[Chosen] Slayer of the Dead - "The chosen appearance cannot be applied to ... because the appearance is not the same type"

### ISSUE THREAD

**Issue by eeppuJ** [WarEmu/WarBugs#20206]
**Expected behavior and actual behavior:**

The skin of **Slayer of the Dead** should be applicable for a Chosen on an axe in main hand. 
At the moment, the skin of **Slayer of the Dead** is not applicable, with the error message : "The chosen appearance cannot be applied to ... because the appearance is not the same type", but you can equip it.

**Steps to reproduce the problem:**

1. Equip an axe in main hand.
2. Check "Appearance"
3. Drag & drop the skin of **Slayer of the Dead** into the main hand slot

**Testing Screenshots/Videos/Evidences (always needed):**

**Trying to equip the appearance :**
![image](https://user-images.githubusercontent.com/9798696/174128978-f6b16e04-80fa-46b3-b9a0-05c57611df12.png)

**With the item equiped, but not as an appearance :**
![image](https://user-images.githubusercontent.com/9798696/174129085-a2c8c030-0684-45a7-a75c-15c444dcce3c.png)

**Comment by vikingofmars** [comment]
![Choppa of the dead](https://user-images.githubusercontent.com/37393516/174396433-43dba78e-c3eb-4237-a7c7-11fc0c70febf.png)
This is also the case for the orc weapons; seems like it might be because they are missing the "or off-hand" trait

**Comment by lilimx** [comment]
Fixed with patch [29/06/2022]
