### ISSUE TITLE
Random NPC in Altdorf Palace walking through walls, minor NPC bug

### ISSUE THREAD

**Issue by WickedPiston** [WarEmu/WarBugs#20204]
**Expected behavior and actual behavior:**

The NPC should not be passing through walls and walking through fountains, should have normal pathing.

**Steps to reproduce the problem:**
Page is the name of the NPC I spotted walking through walls in Altdorf Palace Stairway, not sure if it happens all the time or needs any replication.

**Testing Screenshots/Videos/Evidences (always needed):**

https://user-images.githubusercontent.com/107617937/174046128-e9a45b94-f19a-4607-8c1e-2cfe7cd07777.mp4

https://user-images.githubusercontent.com/107617937/174046160-22a7f636-2fe1-45bc-87b3-ea104c922e61.mp4

![Screenshot (199)](https://user-images.githubusercontent.com/107617937/174046472-39716d65-7fa1-4a59-86dd-0610156d24e7.png)

**Comment by lilimx** [comment]
Fixed with Patch 23/06/2022
