### ISSUE TITLE
BG Defensive Sov Set Wrong Wounds Bonus - King's Ransom Dusk Warrior's Kit

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#20211]
The 2 piece set bonus of the BG Defensive Sov Set only gives +20 instead of +80 wounds.
I also checked with getstats with the same result.

![TkRtPnr](https://user-images.githubusercontent.com/14852547/174507454-cbfb4570-537f-4ed3-96f6-e69e41e70196.png)

I don't have the full set so I can't check the other bonuses.

**Comment by taccr** [comment]
Well apparently this has been solved by itself after logging in today.
The bonuses are now correct for some reason. I didn't change anything.

I'll leave this open for visibility, maybe this is something known?

**Comment by lilimx** [comment]
Hey,

after you equip stuff and you have the feeling the bonusdoesn't work,
check first with the command .getstats
and then try /rel and check again
.....If you don't see any changes, (even after a proper relog), please come back and poke again.
