### ISSUE TITLE
Maraurder Bloodlord Belt

### ISSUE THREAD

**Issue by Megadwa** [WarEmu/WarBugs#20213]
Hi, i ve looted the Marauder Midstrap (Belt), and it unlocked me the 
Bloodlord Shroud entry (witch i dont have) and the Bloodlord Waistgird is still locked ..

i tried to relog 2 times its still bugged

it says i have to get the Shadow warrior Belt to unlock the ward ..

![image](https://user-images.githubusercontent.com/86415949/175114106-d73dd298-f342-46d0-aa4e-5f488d4e18df.png)
![Capture](https://user-images.githubusercontent.com/86415949/175114179-6cac0531-9e10-43e3-853b-b6e56cae5065.PNG)

**Comment by lilimx** [comment]
Fixed with Patch 23/06/2022
