### ISSUE TITLE
[ITEM] Butcher's Cleaver of the dead bugs out animations

### ISSUE THREAD

**Issue by HokoBugTracker** [WarEmu/WarBugs#20210]
If you are using the event item "Butcher's Cleaver of the dead" as appearence on both weapons, it will bug out your animations.
You don't see any weapon swing animations and it stops all running animations aswell.

If you are using it on your offhand weapon, it will stop only the offhand animations, running animations will work again.

https://youtu.be/qosq-D0T1yg

**Comment by gats69** [comment]
Hello, same
I buy the Butcher cleaver of the dead apparence (2 token of Morr)
i equip them on a SLAYER (on 2 axes)
and when i do flurry or other ability, i don t see any animation.

By the way, can you increase the size of the choppers which are really too small,?
 make size x2

**Comment by lilimx** [comment]
Fixed with Patch 23/06/2022
