### ISSUE TITLE
LvL 40 Monster scavenging

### ISSUE THREAD

**Issue by Joiec** [WarEmu/WarBugs#2021]
I´m not sure, but I think lvl 40 Mobs should give Flawless Dust (200 Gold Essence), it´s not the case atm. Around 2 months ago lvl 40 Mobs gave 200 Gold Essence and lvl 35-39 175 Gold Essence, now It´s lvl 35-40 175 Gold Essence. I could not find a lvl 41 Mob yet to find out if 41 give 175 too or not, but on Destro it´s possible to kill a lvl 48 Mob that gives 200 Gold Essence.

**Comment by Jojo1337** [comment]
can confirm that.
lvl39 mobs give skill: 175 curios, 175 gold dust, 175 talismans
lvl40 mobs give skill: 200 curios, 175 gold dust, 200 talismans

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
