### ISSUE TITLE
Guild roster shows invisible player

### ISSUE THREAD

**Issue by Majorzero2123** [WarEmu/WarBugs#20214]
![image](https://user-images.githubusercontent.com/99697728/175136109-de8f31da-3381-42d9-8f22-db45fc70df3e.png)
Issue persists after relog

**Comment by lilimx** [comment]
Hey,

Do you know the invisible player?
Did some get kicked/removed/left your guild?

**Comment by Majorzero2123** [comment]
Not a clue, the last time someone left was 6/17. Issue started today and I am usually the only one on.

**Comment by MaxHayman** [comment]
I think this would have been fixed with the a patch a few weeks ago. Please reopen if that is not the case.
