### ISSUE TITLE
Unable to open window to slot talisman

### ISSUE THREAD

**Issue by vikingofmars** [WarEmu/WarBugs#20217]
**Expected behavior and actual behavior:**
Unable to Shift+Right-Click to add talismans to Apostle's Blasta of Barbarity.
Chat log reads "You could not move Apostle's Blasta of Barbarity."

**Steps to reproduce the problem:**
Attempt to Shift+Right-Click to open Tali slotting window

**Testing Screenshots/Videos/Evidences (always needed):**
![ApostlesBlastaTalismanBug](https://user-images.githubusercontent.com/37393516/175617356-26e1efc5-6258-4159-8198-a4b3ca12052f.png)

**Comment by lilimx** [comment]
Hey,

we tried to reproduce the issue, but it works on our end. 
Did you tried some attemps to fix it by yourself?

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persists, please open a new ticket with proper evidences.
