### ISSUE TITLE
Guild window not visible

### ISSUE THREAD

**Issue by yamyam318** [WarEmu/WarBugs#20215]
**Expected behavior and actual behavior:**
Guild window should be visible. Player is in guild if you search for them.
Guild window is not visible.

**Steps to reproduce the problem:**
Log in. Open Guild Window. 
Search for guild members via social window.

**Testing Screenshots/Videos/Evidences (always needed):**

![Bug1](https://user-images.githubusercontent.com/61079266/175356092-a0697dcb-2d70-434b-9527-3585a76b1faf.PNG)
![Bug2](https://user-images.githubusercontent.com/61079266/175356100-4fc73530-ee46-4342-8e09-57bd8c31108c.PNG)

**Comment by Kaelang** [comment]
This is a known issue and is being investigated actively worked on.

**Comment by MaxHayman** [comment]
Fixed
