### ISSUE TITLE
[DoK] Painblade of the Dead "The chosen appearance cannot be applied to ... because the appearance is not the same type" 

### ISSUE THREAD

**Issue by JackHollowPoint** [WarEmu/WarBugs#20220]
Expected behavior and actual behavior:

The skin of Painblade of the Dead should be applicable for a DoK on swords.
At the moment, the skin of Painblade of the Dead is not applicable, with the error message : "The chosen appearance cannot be applied to ... because the appearance is not the same type", as it is main hand only (most of DoK swords are Main Hand or Off Hand).

Steps to reproduce the problem:

Try to apply appearance, get error message

Testing Screenshots/Videos/Evidences (always needed):
![image](https://user-images.githubusercontent.com/25168701/175840002-483bac08-613e-4e8a-9b18-78e48fa17c85.png)

**Comment by lilimx** [comment]
Fixed with Patch [29/06/2022]
