### ISSUE TITLE
Auction's

### ISSUE THREAD

**Issue by Reconsniper** [WarEmu/WarBugs#20229]
I  cant place anything on the Auction for sell and any of my toons. I can buy for the Auction, I cant sell anything.  when I put an Item to sell in and the price I want to sell it at the create button will not light up to allow me to sell my Item.

**Expected behavior and actual behavior:** Expected behavior, That it would create an Auction for my Items.  Actual behavior, It doesn't allow me to create a Auction for my Items  

**Steps to reproduce the problem:** I have tried everything I know of to and have even asked other players for help. 

**Testing Screenshots/Videos/Evidences (always needed):**

![Littlefoot_000](https://user-images.githubusercontent.com/47046345/176829911-db11594c-fa1e-43e7-bce9-0798e3974273.jpg)

**Comment by lilimx** [comment]
Hey,

Im pretty sure it's the same issue as I mentioned in your post here: #20230

Please feel free to join the RoR discord if you need help.
