### ISSUE TITLE
soldier ward not unlocking with mayhem set

### ISSUE THREAD

**Issue by Devilplusone** [WarEmu/WarBugs#20222]
when you equip the mayhem gear it gives all the credits and achievements BUT it doesnt unlock the soldiers ward the head piece for the mayhem set isnt counting towards it forcing people to focus entirely on thier RR to 29 to either equip the devastator or duelist head piece...this is what i would consider to be an annoyance 

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
This issue is already reported and on our tracker,

**Comment by lilimx** [comment]
dublicate #20161
