### ISSUE TITLE
BB/BE Barakus the Godslayer does not register completion.

### ISSUE THREAD

**Issue by apache140** [WarEmu/WarBugs#20236]
Barakus the Godslayer does not register completion of Burrows & Bloodwrought and The Threat From Barakus the Godslayer quests.

**Expected behavior:** 
Registers completion of both quests for Soul Stone and Helm.

**Actual behavior:**
Does not registers completion of both quests for Soul Stone and Helm.

**Steps to reproduce the problem:**
Have quest then kill Barakus the Godslayer.

![image](https://user-images.githubusercontent.com/99094843/177058412-f2ca7e36-c25c-4a7b-a57f-1449947a1a26.png)

Previous bug report stated the issue was resolved and the bug report was closed but it is not.

**Comment by lilimx** [comment]
related to #20127

**Comment by MaxHayman** [comment]
Should be fixed as of today. If not please reopen.
