### ISSUE TITLE
Ironbreaker Ability : Avenging The Debt

### ISSUE THREAD

**Issue by Mountainz** [WarEmu/WarBugs#2023]
The heal component of this ability is not working.

**Comment by ozarmidrashim** [comment]
![ironbreaker_007](https://cloud.githubusercontent.com/assets/6764164/11456910/28fc3564-9691-11e5-88b0-33b428bcb7ac.jpg)

**Comment by Mountainz** [comment]
Can you confirm that the heal triggers on pve mobs? It's not working for me.
