### ISSUE TITLE
Permament guild mount is missing (High elves)

### ISSUE THREAD

**Issue by Warmasta** [WarEmu/WarBugs#20231]
"Strawberry Roan Elven Charger" is missing and two repeating Blue Roan Elven Charger
Testing Screenshots/Videos/Evidences (always needed)
![Screenshot_7](https://user-images.githubusercontent.com/47497345/176966685-21aecf96-9bfe-400d-8eec-0a0811eb0e10.png)
:
Referring to this post: https://github.com/WarEmu/WarBugs/issues/20037

**Comment by lilimx** [comment]
Hey,

thank you for your post. 
As you already mentioned there is ticket about that issue, so I will close this one.
