### ISSUE TITLE
Live Event Mounts 

### ISSUE THREAD

**Issue by Reconsniper** [WarEmu/WarBugs#20230]
In the Pass Live Event if you finished it you got to pick form 4 mounts. I have finished this on 3 of my toons. I can not see the Mounts when I spawn them and I do not have a icon for the mounts its just a black spot,  when you put the pointer over it will show that its the mounts. Photo 1 is me spawning the mount and the 2nd photo is after I spawned the mount what I see.

**Expected behavior and actual behavior:** Expected behavior to be able to see my mounts. Actual behavior I cant see any of the LE mounts when I have spawn then

**Steps to reproduce the problem:** Asked others players for help, they can see the Mounts but I cant ??

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

this sounds like an update issue on your side.
Try to repair your client (launcher > gear wheel >repair)
if you are from turkey and playing with a non english OS, you need the latest interface.myp

**Comment by Reconsniper** [comment]
Hello IiIimx . I have tried the update with my launcher still cant see the Mount's and I'm in the USA.. Could it be that I'm running the Game on DSL ?? That's the best internet I can get out here in the county where I am.

**Comment by lilimx** [comment]
Hey, 

nah.,...would try a fresh install. Not all issues can be solved by the repair function.
Additional make sure your game has all dirctory rights.

**Comment by Reconsniper** [comment]
A Friend told me to re-download DX9 and that fixed everything in game. I can see the Mounts now I can Use the Auction  now and I no longer T pose on my standard mounts. I also see alot of other things in the game I never thought I was missing lol. So if anyone is having  the issue I was having re-download DX9 that may fix your issue. It did for me
