### ISSUE TITLE
War crest disappeared from backpack

### ISSUE THREAD

**Issue by stormy122** [WarEmu/WarBugs#20237]
Hi!

All my war crest disappeared from my backpack. I have relogged, checked IC bank as well as second bank. But they have disappeared. 
Any tips on what to do to get them back?

**Comment by lilimx** [comment]
Hey,

what happened right before they disappeared. What's the name of your character?

**Comment by stormy122** [comment]
I was tabing in and out from the game, switching between the game and web browser. Ultimately the game freezed (black screened) last time when I opened it again, and I shutted down the computer (via force). The toon name is Laurito.
