### ISSUE TITLE
Guild bank opening (for everyone) whenever a member interacts with it.

### ISSUE THREAD

**Issue by Avenhold** [WarEmu/WarBugs#20235]
**Expected behavior and actual behavior:**
When you are interacting with the guild bank, it should not force all other members/ranks to view the guild bank tab.
When you are interacting with the guild bank, it will force all other members/ranks to view the guild bank tab.

**Steps to reproduce the problem:**
Any member must simply add or subtract an item from the guild bank.

**Testing Screenshots/Videos/Evidences (always needed):**

I did not think to record a video during me and a fellow player's testing of the bug. If required I can try to put something together.

**Comment by GamesBondd** [comment]
Please provide a video.

**Comment by Avenhold** [comment]
Tothmonra gave me permission to use this clip from his video. Like I said, I unfortunately do not have my own perspective: 
https://clips.twitch.tv/PoorKathishDonutRickroll-4Z7HerBOFdHA66it

Also as an update, we attempted to try and recreate the bug again today. But were unable to. So I think you may have already caught it. We also did test it and we weren't able to take items from the popped up window during the bug. But who knows with bugs.

**Comment by Avenhold** [comment]
Thank you lilimx!

**Comment by Rubyeclipse-war** [comment]
Recorded a new video that shows this in action:

https://www.youtube.com/watch?v=rT5Isqt34_k

Steps to recreate:

1. Open the guild vault, add items, move them, or remove them.
2. Have a different guildmate open the vault.

This can sometimes trigger the vault to open for you each time an item is moved, no matter where you are in the world (including entirely different zones). Example in the video!

**Comment by MaxHayman** [comment]
Thanks @Rubyeclipse-war  @Avenhold  these videos are helpful

**Comment by lilimx** [comment]
Fixed with Patch 16/07/2022
