### ISSUE TITLE
Stalker Set quest Avelorn

### ISSUE THREAD

**Issue by Asdar2** [WarEmu/WarBugs#20244]
Sorelle Darkglade - [Avelorn](https://wiki.returnofreckoning.com/Avelorn) 44k/35k Chapter 12
Supouts to give quest "Blood on the Leaves" Kill 10 Disciples of Khaine
But ther is no quest right no
![2022-07-08_18-54-18](https://user-images.githubusercontent.com/16272439/178045024-04e414f5-d7d9-4b17-917a-30fd406ddcae.png)
w

**Comment by Asdar2** [comment]
![2022-07-08_19-27-00](https://user-images.githubusercontent.com/16272439/178049718-a5f5aa2e-4f69-424b-8714-f81005d231e3.png)
Same with Dwarf  Rorik Copperkeg - [The Badlands](https://wiki.returnofreckoning.com/The_Badlands) 33.4k/12k Chapter 13

**Comment by Scophis** [comment]
It could be due to your level. If I remember correctly the quest aren't unlocked at the same level. Maybe try checking the NPC again, after you've gained a level or two.

**Comment by lilimx** [comment]
The level required to start the Tracker's and Stalker's quests is now 2 levels below the level of the pieces they reward

Can't test it currently, due to test-server issues

**Comment by Kaelang** [comment]
This isn't a bug - you haven't met the minimum level for the next quest.
