### ISSUE TITLE
Ironbreaker Ability : Watch An' Learn

### ISSUE THREAD

**Issue by Mountainz** [WarEmu/WarBugs#2024]
Weapon skill gained from using this ability is not contributing to parry chance. Weapon skill and armor pen is reflected on char sheet and in getstats, just not Parry chance / %.

**Comment by Evildoor** [comment]
I do believe that .getstats only shows parry from duals/items/renown/etc, not from WS, so the skill has nothing to do with it.

**Comment by Mountainz** [comment]
Thanks wil keep this in mind when testing future abilities
