### ISSUE TITLE
Troll Country aao/apathy bugged

### ISSUE THREAD

**Issue by topdudes** [WarEmu/WarBugs#20240]
For over a week I've noticed that RP rewards for BO locks and resources in Troll Country have been different than before. It appears that aao is actually decreasing renown rewards and apathy is increasing them. I'm sorry but I don't have screen shots only documentation of rewards I received today while playing my Order main.

Before this issue normal RP for locking Monastary of Morr BO was 220-260
Today:
60% aao for order - BO lock 156 RP
20% aao for order - BO lock 48 RP
40% aao for order - BO lock 76 RP
80% aao for **destro - BO lock 260 RP**
20% aao for order - BO lock 52 RP

**Expected behavior and actual behavior:**
I expect that while a realm has aao that RP rewards will be more than what is given with even numbers. It appears however that when a side has aao the rewards are reduced, when they have apathy it is increased. I have not tried this on a destro toon but expect the same result.

**Steps to reproduce the problem:**
Wait until Troll Country is active (probably a long wait given the current zone mechanics) and try it yourself. Many have seen it in game and it has been discussed with a few regular players, it shouldn't be that hard to reproduce.

**Comment by Rubyeclipse-war** [comment]
Just to note, this bug is occurring in many zones, in addition to Troll Country. 

Saw it in Praag, Kadrin Valley, and other zones over the last few days. AAO of any sort appears to reduce the renown granted for objectives and supply well below the default that it should be granting. Can get pictures easily if they're helpful.

**Comment by lilimx** [comment]
fixed with patch 03/08/2022
