### ISSUE TITLE
Engineer turret not working in Thunder Mountain.

### ISSUE THREAD

**Issue by Tonych1981** [WarEmu/WarBugs#20245]
The engineer's turret does not work in Mount Thunder. She simply disappears after being summoned and attacked. Turret self-destruct does not work either. Only in this location it is impossible to play an engineer.

**Comment by Zomega-WAR** [comment]
Reported many times before. https://github.com/WarEmu/WarBugs/issues/18872 has a list of other reports.

**Comment by Tonych1981** [comment]
Thanks for the info. This error has been there for six months, and an engineer cannot be played in this zone.

**Comment by Zomega-WAR** [comment]
There are bugs from 2015 on the tracker. If it's been reported then the devs are aware of it, and opening a new ticket doesn't help solve the issue.
