### ISSUE TITLE
Not gaining ability "Draining Swipe" when I spec for it on Marauder.

### ISSUE THREAD

**Issue by Kymix21** [WarEmu/WarBugs#20241]
While leveling a marauder, I'm attempting to spec for Draining Swipe in Savagery tree. When I spec for it, I do not receive the ability. Screenshot below shows spec tree and abilities available for savagery. 

![image](https://user-images.githubusercontent.com/60149182/177895163-adac918a-7a2a-4209-8664-312ee1149c4b.png)

**Comment by Scophis** [comment]
You have to spend an additional skill-point each to unlock skills and tactics in mastery trees.
