### ISSUE TITLE
Chosen's Corrupting Wrath Aura is not working as intended

### ISSUE THREAD

**Issue by wildwindblows** [WarEmu/WarBugs#20247]
Hello RoR Bugtracker Team,
Corrupting Wrath aura is not giving the aura value which shown in buff tool tip. As shown in the pictures below, toughness value without Corrupting Wrath is 574 but it is 608 with Corrupting Wrath tactic. Corrupting Wrath tactic is supposed to additional 114 toughness. However, it gives additional 34 toughness value. You can see toughness changes with and without toughness below. Just to be sure, I checked this from character windown, .getstats and an addon which shows stats.

**Expected behavior and actual behavior:**
Expected behavior: Corrupting Wrath Aura is supposed to give toughness value in tool tip. (Ex. it gives 34 toughness instead of 114.)
Actual behavior: Corrupting Wrath Aura gives less toughness value

**Steps to reproduce the problem:**
1. Check toughness value without Corrupting Wrath Aura.
2. Check toughness value with Corrupting Wrath Aura and compare value with first step.

**Testing Screenshots/Videos/Evidences (always needed):**
1. Without Corrupting Wrath Buff
![Sirzero_060](https://user-images.githubusercontent.com/45720515/178136868-a6f58feb-d09e-4b77-a097-232511e497de.jpg)

2. With Corrupting Wrath Buff (+114 Toughness)
![Sirzero_062](https://user-images.githubusercontent.com/45720515/178136885-3992cc00-f1d2-4fba-b40e-29c689e1994e.jpg)

Bests,
Sirzero.

**Comment by lilimx** [comment]
Hey,

what kind of potions are you using?

**Comment by wildwindblows** [comment]
im using +80 toughness potion and +660 armor potion

**Comment by wildwindblows** [comment]
wow. i just realized that toughness potion and chosen toughness aura are not  stacking? Is it like this?

**Comment by lilimx** [comment]
Hey,

yes, that's why I asked about your potions :D 
auras doesn't stack with pots (for instance the WP wounds buff doesn't stack with liniments aswell)
