### ISSUE TITLE
[Items] T1 hunter boots dose not activate the Recruit's Ward achivement.

### ISSUE THREAD

**Issue by Synesh7** [WarEmu/WarBugs#20249]
The T1 RvR item Hunter boots doesn't seem to trigger the achivement necessary to complete the First Signet achivement.

![Big report hunter 1](https://user-images.githubusercontent.com/109103653/178332871-e0a79f39-eadb-4d28-adf4-112c9d1b153b.png)

**Comment by Avm07** [comment]
I would like to confirm getting any piece of Hunter set does not update Recruit's Ward Fragment Task

**Comment by Skibbas** [comment]
This has been open for quite some time, and today I saw more ppl ask in /ad about this.
Checked my WE and it does indeed still not work for any of the hunter pieces.
![Etuwitch_001](https://user-images.githubusercontent.com/79228534/212570652-ea76087a-0610-40f0-b042-c90f7554ad34.jpg)

**Comment by Rubyeclipse-war** [comment]
Hi there,

This has been fixed! Both the Hunter Boots and Chestpiece will properly grant the Tome unlocks and the Recruit Ward as of the next patch. 

Thank you for letting us know about this bug and for the patience as we got it all fixed up. 👍

**Comment by lilimx** [comment]
fixed with patch 09/02/2023
