### ISSUE TITLE
WL Helm has different stats every time !!!! 

### ISSUE THREAD

**Issue by Drstrangeone** [WarEmu/WarBugs#20242]
My WL Invader and Sov Helm do not show me the correct additional stat. It is supposed to be 3% armor pen. However not only does it NOT give me 3% armor pen, but it will change it stats based on the last item I scrolled over. If I scroll over sov shoulder then back to the helm it will show the helm giving 2% crit. Changes for each item. Doesnt give me any stats. 

I have attached pics showing the different stats the same item gives and then how the helm does not give me 3% armor pen like it should.
![Abrom_011](https://user-images.githubusercontent.com/33774346/177897725-ea024372-5f96-4385-aa54-74c799cff8d4.jpg)
![Abrom_012](https://user-images.githubusercontent.com/33774346/177897727-dd20a3a6-8303-4d7d-81d7-aca9b6829a4e.jpg)
![Abrom_013](https://user-images.githubusercontent.com/33774346/177897728-4b7ef2fd-514d-49ac-bb38-48d8c729ad7c.jpg)
![Abrom_007](https://user-images.githubusercontent.com/33774346/177897729-b4ba07b3-bcde-49d5-b7d3-1bc6dcd1cf3f.jpg)
![Abrom_008](https://user-images.githubusercontent.com/33774346/177897730-5d587c17-6414-4ae1-a682-212741cca02f.jpg)
![Abrom_009](https://user-images.githubusercontent.com/33774346/177897731-ce12797a-8c23-46c9-bb32-66ec15a947f9.jpg)
![Abrom_010](https://user-images.githubusercontent.com/33774346/177897733-2e7b7ff2-fb7e-4dfb-bb5d-ddbf6448e248.jpg)

**Comment by lilimx** [comment]
Hey,

please do what Crimson wrote, the paperdoll display is no reliable source of information.

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persists, please open a new ticket with proper evidences.
