### ISSUE TITLE
Karaz-a-karak: Auctioneer not functioning

### ISSUE THREAD

**Issue by Rubyeclipse-war** [WarEmu/WarBugs#20250]
_Update: Confirmed this seems due to Shinies add-on. Getting rid of the add-on fully makes the Auctioneer work properly. This ticket may not be necessary if this is purely an add-on issue._

The Auctioneer in Karaz-a-karak doesn't seem to be functioning currently:

Video: https://www.youtube.com/watch?v=qUmYCgghMB0

Tested on both vanilla UI and Vinyui with Shiniez add-on, and looks like the same result. Guildmates also reported the same issue.

Thanks for looking into it!

**Comment by Zomega-WAR** [comment]
Just tried KaK with the vanilla UI and it worked fine:

![image](https://user-images.githubusercontent.com/60266177/178601185-ada965c7-35fc-45dc-b9c1-5468735ca357.png)

Regarding Shinies, KaK and K8P are missing from its list of zones where the auction house can be used. If anyone knows the zone IDs for KaK and K8P then the "acutionHouseZones" table in "Shinies\Modules\API\Shinies-API.lua" needs to be updated with them. Enabling/disabling Shinies can sometimes cause the default AH UI to mess up which might explain the OP's problem.

To my knowledge, ROR is working fine and Shinies itself needs to be updated to work with the 2 new cities.

**Comment by Rubyeclipse-war** [comment]
Thanks @Zomega-WAR - just did another fresh test with Shinies fully disabled and I see it working properly as long as the add-on is totally gone. This seems to be a purely add-on related issue then.

**Comment by lilimx** [comment]
Hey,

Yeah did a test yesterday too and Ekalime said it should actually work. Im pretty sure that the ID for the auctineers or for the area is missing (similar to the ah issue while city siege)
