### ISSUE TITLE
When i login i wanna play but it doesn't shows anything.

### ISSUE THREAD

**Issue by TuttiFrutti09** [WarEmu/WarBugs#20255]
Hello i just played ror a hours ago and all was fine.Then after some hours i wanted to play again and then i loged in and i waited like 10mins but nothing was showing :/. I think its not the issue on my internet because its fine.It would be nice if i could get some help.Thank you.(sorry for my bad english)  
![image](https://user-images.githubusercontent.com/109522861/179507665-19b66cb3-e30b-48ea-b600-05f3b1bf1d97.png)
Its just like that picture the whole time,whenever i try to play i can't :( Please help :(

**Comment by Kaelang** [comment]
This isn't a bug - please utilise the support channels on the forum / discord.

**Comment by TuttiFrutti09** [comment]
Thanks.i will try,thx very much!
