### ISSUE TITLE
No Quarter cast time reduction stops working randomly

### ISSUE THREAD

**Issue by unflaggmyaccount** [WarEmu/WarBugs#20253]
Shadow Warrior. I've noticed that at some point casting of Eagle Eye and Festering Arrow with No Quarter does not get reduced casting time. Cant find out what precisely leads to that behavior. Will add more details if I'll be able to get more.

**Expected behavior:**
Cast time of Eagle Eye and Festering Arrow should be reduced by 1 second, being 1 and 2 second respectively

**Actual behavior:**
At some casting time is as if there was no 1 second reduction, being 2 and 3 seconds  respectively

**Steps to reproduce the problem:**
- stand still and hit training construct with Eagle Eye and Festering Arrow non stop using No Quarter tactics

**Notes**

- Unsloting\sloting tactics helps for a while. But that it starts all over again.
- Changing stances looks not to trigger this bug

**Testing Screenshots/Videos/Evidences (always needed):**
Sorry for wonky video - I don't have any screen recording program. At the video u could see that casting time of Eagle Eye differs from time to time. Might be issue with new GCD, not sure, I just haven't play SW since changes.

https://user-images.githubusercontent.com/106101045/179240758-91072308-223e-4644-8121-86ae5a08594c.mp4

**Comment by lilimx** [comment]
Hey,

thank you for your nice report. 
This issue is already reported.
I will add this to the other related ticket.

**Comment by lilimx** [comment]
dublicate #17950
