### ISSUE TITLE
T3 Destruction Epic Quest: Honorable Deceit not available

### ISSUE THREAD

**Issue by SecretShrub** [WarEmu/WarBugs#20269]
**Expected behavior and actual behavior:**
As per the wiki I went to this NPC to obtain the quest "Honorable Deceit" for a weapon appearance. But when clicked the NPC has nothing to give. He does not have the quest available green book icon above him either. 

**Steps to reproduce the [problem:**]
[https://wiki.returnofreckoning.com/Dark_Elves_T3_Epic_Quest_Honorable_Deceit](url)

**Testing Screenshots/Videos/Evidences (always needed):**

![warcapture](https://user-images.githubusercontent.com/109771046/180334133-3a03ff63-6024-4fdf-915e-e832232357fd.JPG)

**Comment by Kaelang** [comment]
What level are you?

**Comment by SecretShrub** [comment]
40. Are they locked to certain levels?

**Comment by Scophis** [comment]
Just checked, it's avaible for me.  Maybe you have done it before and just forgot about it?^^
![Apogemoth_003](https://user-images.githubusercontent.com/40274248/180626525-13354d2e-7042-4a95-88d5-2e41556af3b6.jpg)

**Comment by SecretShrub** [comment]
Dang looks like I got  the Big Fumper already. Thanks @Scophis. Too bad we can't redo these so we could get all the customization options.

**Comment by SecretShrub** [comment]
Sorry to waste time on this, whoops
