### ISSUE TITLE
DoK/WP Group Cleanse Problems

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#2026]
Hey there,

the implementation for group cleanse is a.) bugged b.) wrong (at least for doks).

a.) When using efficient patching tactic I'am unable to cleanse out of party. It should cleanse the out of party target and my group. Currently it does nothing.

b.) (I have not played WP on this server so my observations are DoK only)
b1.) DoKs should not be able to cleanse without having a valid cleanse target selected.
Correct implemantation is: DoKs always need a debuffed target in LoS to activate their group cleanse. WPs however are able cleanse any time even if no debuff is present.

b2.) DoKs were able to double cleanse (only themself though) by selecting themself before cleansing. This implementation is needed since DoK group cleanse weaker than WP cleanse due to b1.

I don't actually mind the current implementation (if a. gets fixed) but this is how it worked back on live.

**Comment by noisestorm** [comment]
a) wrong due to b2)
b1) wrong
and b2) =>  the double cleanse was also a bug back on live and got fixed at the very late stages iirc.
Never worked on WP so there was quite some salt back on live about that.

**Comment by taccr** [comment]
The points I stated are correct. No idea what you think you are typing.
Hopyfully theres some more knowledgeable people reading this.

**Comment by taccr** [comment]
Adding two screenshots here to proof what can be proven by screenshots. (b1)
First picture is dok with greyed out cleanse. - Unable to activate until valid cleanse targets selected.
Second picture shows WP with always active cleanse. - Even if no debuff is present.
http://imgur.com/a/uRvKQ

**Comment by noisestorm** [comment]
Thats the point. RoR will not adapt obvious bugs which you seemingly dont seem to like or understand :>

**Comment by taccr** [comment]
Classes and abilities are not mirrored. Just as aoe detaunt was different between dok and wp so is the group cleanse.
Who exactly decides if the live implementation was a bug? You? I don't think so.
This bug report is not for stating your opinion it is to clarify the correct implementation.

The way it currently works is wrong in the ways I stated. If the devs don't want to get it right, its their choice not yours.

The problem with group cleanse that is currently affecting the game play most is the inability to cleanse out of party. Be it your second party in a warband or just someone not grouped.

**Comment by noisestorm** [comment]
That the Detaunt works in different ways is clearly stated in the tooltip. The cleanse is an exact mirror on the other hand. Also the Tooltips for both gcleanse tactics state _one_ effect. And i just repeat it. the gcleanse for DoK was definitely buggy back on live and i dont give a flying fuck if you accept that or not.

**Comment by taccr** [comment]
Good thing that I don't care about your opinion anyway. You act like a child, extremely stubborn and no arguments to be seen.

As I mentioned earlier, it is not for you to decide if it's a bug or not. The cleanse was never a mirror and everyone who played WP and DoK know exactly how different they worked.

The most obvious part is the different debuff types it dispels. WP cleanse without LoS requirement was also far superior because you could cleanse your dps behind walls and inside keeps. That was not possible on a DoK.

Next time try to contribute facts or just let people decide that actually have something to say.

**Comment by noisestorm** [comment]
I know that the handling with LoS was different, but alone the fact that you double cleansed yourself or just single cleansed you depending on IF you targeted yourself or not just shows it was obviously a bug that mythic just didnt care about like so many other things. and you should be happy to get the version where you dont have to target anyone to actually be able to cleanse. the double cleanse for a fact will not come despite how much you cry, because  -i am repeating myself here - it was just a bug and nothing else. believe me

**Comment by Vigfuss** [comment]
Taccr is correct in reporting something that is not the same as live.  I know from experience that he is correct.  The implementation could be a mistake by the RoR devs.  And if it's not a mistake there should be an explanation from the devs about why they changed it.  I don't think this should be the place for a discussion about balance of the game.

**Comment by taccr** [comment]
You are actually crying like a little baby with literally no arguments. Who the fuck are you to make those statements? All you bring to this BUG REPORT is your personal opinion which does not matter.

Now go away with your feature request. If you want a new implementation different from live go talk to a dev or make a forum thread.

This is a bug tracker and I'm here to clarify if the implementation is intended or they just don't know how the spells used to work. The devs are more than capable to decide themself if something needs to be changed.

**Comment by Evildoor** [comment]
Please, gentlemen, let's keep this civil. Sometimes reports on bugtracker turn into balance talks (see champion's challenge issue, for example), but i do believe that for now both of you have given your points of view, so let's wait for Azarael's response and continue after that. Politely, if possible.

**Comment by ozarmidrashim** [comment]
This one is difficult.

I saw, while implementing these two tactics, that the DoK version appeared to keep its target requirement. The tooltip for Efficient Patching states: 

"Patch Wounds will now remove one Ailment or Hex for the entire group."

Let's discuss DoK double cleanse if targeting self. This was clearly a bug, because a) it's not mentioned in the tooltip and b) there is no reason why this effect should not occur if targeting another group member - why only on the DoK? If I am going to change the DoK version of gcleanse to behave as it did on live, I confess to having no intention of restoring this behaviour.



-

**Comment by taccr** [comment]
As I stated in my first post here, I don't mind the current implementation if the out of party cleanse is getting fixed. The double cleanse behavior is just like many other abilities not documented anywhere. However if the target requirement gets implemented again the DoK needs some other compensation to not fall even further behind. The double cleanse was very annoying crude to play with since you always had to swap between targets.

Balance wise most of the things look fairly good atm. While WPs still are still superior to DoKs it's not as bad as back on live yet.

**Comment by ozarmidrashim** [comment]
Which is considered more powerful in general, the WP or DoK implementation?

**Comment by taccr** [comment]
I don't know what the current WP implementation looks like.

Back on live the WP cleanse mechanic was better due to no LoS requirements and the ability to remove more important debuffs (e.g. curses). (DoK can't remove IB outgoing debuff or IB/KotBS aoe snare) Thats a more grand scheme discussion and shouldn't be here.

The current DoK implementation is very clunky since you need to target yourself again to cleanse beyond LoS. The skill currently cannot be used if the target is out of range or behind an obstacle forcing you to target yourself or another group member in range.

If you want to mechanicly properly mirror the abilities (apart from the dispelled spell schools) you should take the WP mechanic which feels a lot better. Cleanse should therefore always be usable and not require a valid target in range or LoS.

The only advantage the DoK cleanse on live had was that you could spam cleanse it on one target and as soon as this guy gets debuffed the cleanse goes off.

**Comment by Vigfuss** [comment]
DoK cleanse was the better cleanse, but it involved slightly more effort to use correctly.  As far as I know it was basically 1 cleanse + group cleanse.  But Taccr might be correct that it was only double cleanse on the DoK who cast it.

**Comment by Uchoo** [comment]
Which one is better is completely subjective, since you can always cleanse out of LoS as a WP, which allows for much safer positioning. I have no clue why they need to be different, some people just need to have all these random distinctions between mirrors to have a "better" game.
