### ISSUE TITLE
Riposte not working or half working

### ISSUE THREAD

**Issue by Navar2** [WarEmu/WarBugs#20263]
Procs randomly in same enemies or different enemies

<a href="https://imgur.com/OELbL3n"><img src="https://i.imgur.com/OELbL3n.jpg" title="source: imgur.com" /></a>

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persists, please open a new ticket with proper evidences.
