### ISSUE TITLE
Mastery skills

### ISSUE THREAD

**Issue by Crespirito** [WarEmu/WarBugs#20260]
**Expected behavior and actual behavior:**

I cant use my mastery skills in any character i use.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![2022-07-19](https://user-images.githubusercontent.com/109594752/179740808-c3a4c839-76e5
![2022-07-19 (1)](https://user-images.githubusercontent.com/109594752/179741057-0de6de0e-d8fb-49b6-97bc-a8aa4b85caaa.png)
-4075-9a7b-b410556e017c.png)

**Comment by lilimx** [comment]
Hey,

I need a bit more information. You are lvl 31 so you maybe don't have unlock all tactics. 
Did you already put some points into the the mastery trees?
Additonal your screenshot depics the renown tactic tab, so there are no tactics available.

**Comment by arendsessom** [comment]
This is the tactics pane opened, and under this the one for RR tactics. I think, they are not even implemented.

**Comment by lilimx** [comment]
Hey,

yes, they aren't implemented...so that's why I asked for more information

**Comment by Crespirito** [comment]
Ok thank you.

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persists, please open a new ticket with proper evidences.

**Comment by Crespirito** [comment]
Shit, sorry, i forgive it. The problem continue,  in all of my characters.
