### ISSUE TITLE
Quest bug (New Allies, New Enemies)

### ISSUE THREAD

**Issue by graffernsl** [WarEmu/WarBugs#20267]
**Expected behavior and actual behavior:**
Requirement: free 4 Captive Smiths Freed.
Only 2 of them avaliable in quest aeria. Not posible to complite quest, cause i cant speak with same NPC twice. 

**Testing Screenshots/Videos/Evidences (always needed):**
![Graffer_107](https://user-images.githubusercontent.com/58138563/180293978-9801e07e-5c2d-4124-9d0d-b211fea32ee7.jpg)
![Graffer_108](https://user-images.githubusercontent.com/58138563/180294031-48d23208-2011-434d-9755-104cc4dacc9f.jpg)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
This issue was already reported here #12423

**Comment by graffernsl** [comment]
And not fixed in 4 years? ^___^

**Comment by lilimx** [comment]
fixed with patch 03/08/2022
