### ISSUE TITLE
lazy lions

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#20278]
war lions (at least my one) are currently unable to path through keep doorways once the door is destroyed and just try to run off around the wall, and when ordered to attack a target it keeps returing to me about 5-10 seconds later even if it had actually been in combat - apparently it only stays in combat if the elf is also in combat with the same target

also the lion does not respond to the elf getting stealth-jumped by a witch elf (in defencive mode), it just sits there until either ordered to attack or until the elf recovers from knockdown and lands a hit

edit: also dosnt respond to getting stealth jumped when in aggressive stance

**Comment by lilimx** [comment]
Hey,

Thank you for your report.
Unfortunately, your ticket contains too many issues, so we can't utilize your ticket.
Additional please make sure that your report provides proper evidences (testing screenshots/video).
Please, feel free to open a new ticket anytime.

Here are two guides that will help you:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37703
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
