### ISSUE TITLE
Nothing happens when entering the main menu

### ISSUE THREAD

**Issue by OVshnik** [WarEmu/WarBugs#20271]
Hello! After the last update, nothing happens when loading the main menu, the server does not connect. How to fix this problem?
![image](https://user-images.githubusercontent.com/86915531/180518344-9ec34555-0ac5-4d4d-9a60-ef9db328484f.png)

**Comment by lilimx** [comment]
Hey,

This isn't a bug - please utilise the support channels on the forum / discord.

**Comment by OVshnik** [comment]
ok, thanks
