### ISSUE TITLE
[DoK] [Victorious armor] [Piece bonus] [Endure]

### ISSUE THREAD

**Issue by Syzako** [WarEmu/WarBugs#20279]
The piece bonus 4 "Endure" does not work.
![image](https://user-images.githubusercontent.com/39750677/181746271-3ffb9daa-86f2-439b-89d7-5d473c977671.png)

**Steps to reproduce the problem:**

"On being hit" on me or on "Training construct" in Inevitable City, the effect does not work.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/39750677/181744863-d9d7f0a6-a550-4ac1-9593-fd3a8a786e56.png)

**Comment by lilimx** [comment]
Hey,

I've tested both Endure buffs, on Oppressor and Victorious and it worked. 
Don't forget to do a proper relog after you switched your gear.

![1](https://user-images.githubusercontent.com/23266079/181824126-ec538c51-ab30-4778-9ce9-e4e26f166edd.png)
![2](https://user-images.githubusercontent.com/23266079/181824139-a59be5cf-8d19-46c9-9807-a3a01b29fb5a.png)
