### ISSUE TITLE
[OpenRVR] [Supply] [Box] AAO not properly scaling with Box delivery

### ISSUE THREAD

**Issue by b00nation** [WarEmu/WarBugs#20276]
Expected behavior:
Box drop should scale with AAO properly, 

i.e. 0% AAO 100 Renown
20% AAO 120 Renown
-20% AAO 80 Renown

Actual behavior:
The AAO of the opposite Faction is applied sometimes.

Walked into inactive Zone having ~3 Destro Players and 2 Order Players. AAO switcht from --40 to 20%

Destro Player in DragonWake:
with 20% AAO for Destro AAO You gain 65 renown.
With 0% AAO You gain 325 renown.

**Steps to reproduce the problem:**
AAO needs to Go from -20 to 20% and backforth

**Comment by b00nation** [comment]
Here a picture of a supply drop with 60% AAO
![image](https://user-images.githubusercontent.com/25694121/180948134-2cc8d5fe-38bc-4a6f-b76e-3faf5b0d6aec.png)

**Comment by b00nation** [comment]
And the next Box behaves completely different:
![image](https://user-images.githubusercontent.com/25694121/180948535-d6d686de-3677-49f3-a5de-c4c341de4d5e.png)

**Comment by b00nation** [comment]
And here where it should be -40%:
![image](https://user-images.githubusercontent.com/25694121/180949973-015b5731-333a-43e9-8186-f5bc2ad88269.png)

**Comment by lilimx** [comment]
Hey,

this is maybe related to this issue: #20240
let's wait for the patch and review it again.
