### ISSUE TITLE
Sanctified Bullets tactic for WH doesnt register correctly in combat log

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#20288]
**Expected behavior and actual behavior:**
Should register in your heals but instead shows up in damage taken as -hit.
So actually tactic works but doesn't register correctly in combat log.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![war-64 exe Screenshot 2022 08 03 - 20 19 27 58](https://user-images.githubusercontent.com/16375224/182670393-bbc84353-b48a-4ea7-a12f-66a5d838f5af.png)

![war-64 exe Screenshot 2022 08 03 - 20 20 19 95](https://user-images.githubusercontent.com/16375224/182670422-855cacfb-b6bb-4f1f-90f5-891fa6b20fae.png)
![war-64 exe Screenshot 2022 08 03 - 20 20 19 95](https://user-images.githubusercontent.com/16375224/182670416-598bd593-c6f0-4811-8329-074a6d9d2b0f.png)

**Comment by MaxHayman** [comment]
Should be fixed. Please reopen if that is not the case.
