### ISSUE TITLE
major fps issue with crafting bag

### ISSUE THREAD

**Issue by thesweetest** [WarEmu/WarBugs#2028]
a week or so ago i was having major fps issues upon starting the game, where my frames would be incredibly skippy for anywhere from 20 minutes - 1.5 hours of afking and then out of nowhere , boom my fps would be a smooth 60 again. i made a post on the technical forum about it here

http://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=7688

after many days of trying things/waiting i gave up and started to just play and afk in the warcamps for large periods of time in order to get a stable game to enjoy, however one night while trying to craft a talisman i noticed something

in my crafting bags which were almost full save for ~1 slot, there were several talisman materials all in the same slot in the bags, all rapidly changing thumbnail icons, 5-7 items all changing in like half a second, i noticed that when these were rapidly switching spots like this, my fps dropped terribly , and when i just nuked my entire crafting bag clean, the fps bug is completely gone.

**Comment by ropuch** [comment]
Out of curiosisty: do you use any backpack/crafting mod (nRarity for example)?

**Comment by nalgol** [comment]
this is some client auto sorting issue i could find the issue for yet

**Comment by nalgol** [comment]
ok i found the issue for this dont set the autosort in the main bags it causes the cleint to go nuts and try to sort the crafting bag im not sure why it does that this cannot be fixed yet
