### ISSUE TITLE
Kotbs 4 auras bug

### ISSUE THREAD

**Issue by Kubzes** [WarEmu/WarBugs#20281]
**Expected behavior and actual behavior:**

Kotbs should have limit at 3 Command at once. In matter of fact. I found the bug how to make 4 comamnds at one time.

**Steps to reproduce the problem:**

1. Make sure you have 3 auras turned ON.
2. Join in the scenario
3. Run 4th aura. It just works (getstats tested)
4. After SC, you can manipulate auras to keep 4 auras.

**Testing Screenshots/Videos/Evidences (always needed):**

Video#1 shows entering Scenario
Video#2 shows ending of scenario + manipulating after

Because of filesize - I've uploaded it on youtube.
Video1(https://www.youtube.com/watch?v=6M36tuzpfks)
Video2(https://www.youtube.com/watch?v=6vqBYekpHHw)

**Comment by lilimx** [comment]
Hey,

thank you for your report.
This issue is already known so I will close this ticket and add it to the related one.

**Comment by lilimx** [comment]
related to #19072
