### ISSUE TITLE
[Chapter 22 Reikland and Eataine] Opt-out Gold bag bugged - Destro side

### ISSUE THREAD

**Issue by alyssonpaladini** [WarEmu/WarBugs#20284]
Opting-out from gold bags at last stage.
So basically if you click "opt-out Gold bag only" the game understand as if you clicked "Opt-out all bags".

**Expected behavior and actual behavior:**
If you click the option to opt-out gold bags, the game understand you are opting-out from all bags.

**Steps to reproduce the problem:**
It happened twice on my shaman GorkMorkBoi, I chose opt-out gold bag at last stage on both Ch22 and after the boss dies, you get nothing because the game understood you opt-out from all bags, pretty weird.

Today we went again at Ch22, at last stage I tested clicking "opt-out Gold bag only", the game said I was opting out all bags again... its been like 2 weeks already Im seeing such issue.

**Comment by lilimx** [comment]
Hey,

Thank you for your report.
There is already an open one.
So im going to add this ticket to the related issue.

**Comment by lilimx** [comment]
Dublicate/related to #13976
