### ISSUE TITLE
[WE] Kiss of Doom and Sacrifical Stab doesn't heal but damage themselves

### ISSUE THREAD

**Issue by Star-dust** [WarEmu/WarBugs#20298]
**Expected behavior and actual behavior:**
Kiss of Doom and Sacrifical Stab, when proc, should heal but now it damage themselves

**Steps to reproduce the problem:**
Use it

**Testing Screenshots/Videos/Evidences (always needed):**

Kiss Of Doom
[Image 1](https://ibb.co/C7c3gfY)
[Image 2](https://ibb.co/ykQZZch)

Sacrifical Stab
[Image 1](https://ibb.co/Kj6ZFLF)

Probably it is same as https://github.com/WarEmu/WarBugs/issues/20288

**Comment by MaxHayman** [comment]
Should be fixed if not please reopen
