### ISSUE TITLE
Not receiving bags by mail

### ISSUE THREAD

**Issue by nastya0204** [WarEmu/WarBugs#20290]
After todays patch theres a problem with getting bags by mail. I got 2 letters saying "u have won bags at..", i opened them, but they were empty. I relogged few times, but it didnt help.

**Comment by Jeliel80** [comment]
Not receiving bought Talisman from AH in mail, even after multiple relogs/restarts.

**Comment by Gojbe** [comment]
i got the same problem
![Dagrunk_005](https://user-images.githubusercontent.com/110549410/182636539-49a9573d-9b9e-44f8-823c-9f36d8bf253c.jpg)

**Comment by Amadon82** [comment]
Same here, no bag attached to the mail. (It was a green one.
![fsefsefsefsef](https://user-images.githubusercontent.com/19516183/182643135-32832fae-89cf-4e90-a1a3-e31e0bbec32f.JPG)
)

**Comment by Astricky** [comment]
I have some problem too. 2 or 3 message without bags(

**Comment by unflaggmyaccount** [comment]
Same issue here. 
![image](https://user-images.githubusercontent.com/106101045/182774468-23ae97bb-06f4-4734-849d-c3d7e909aba4.png)

**Comment by Tyrgrimm** [comment]
Like Me 
Lost 3 bags yesterday (1 green / 1 Gold /1 purple)
same effect as below > I have the mail but nothing inside

**Comment by Snowiy** [comment]
Same Problem... 
Also no Chrest for zone locks etc.

**Comment by Astricky** [comment]
ok, now i have loot bag in my mail, but loot bag not open

**Comment by Syzako** [comment]
![1](https://user-images.githubusercontent.com/39750677/183014922-51f5916e-e383-401c-b5fb-a646233975fc.png)
![2](https://user-images.githubusercontent.com/39750677/183014955-494339b4-deb4-451a-baa0-a75332bea9b4.png)

**Comment by hammerhammerhammer** [comment]
I'm unsure if it's related, but now I am receiving bags, however they contain no crests nor genesis fragments

![_009](https://user-images.githubusercontent.com/69740705/183095772-7d9d93ba-b908-4daa-a8d2-d45f624d6cd4.jpg)

**Comment by Amadon82** [comment]
And may i add that we not receive any crest when a zone lock.
![loot](https://user-images.githubusercontent.com/19516183/183142779-0aa7ef99-5f9f-42a8-96ab-1a1a540243b9.JPG)

**Comment by JohnnyWayne89** [comment]
We also can't loot bags from chests now anymore when we lock a zone. Still takes our roll bonus though.

**Comment by unflaggmyaccount** [comment]
I was able to receive 2 bags via email, but no crests or genesis there.

**Comment by lilimx** [comment]
fixed with patch [11/08/2022]
