### ISSUE TITLE
Graphic Bugs annoying after last patch

### ISSUE THREAD

**Issue by ravezaar** [WarEmu/WarBugs#20292]
Graphic Bugs when channel abilitys from AM and some from RP stick long after they ended on target, its ssems to be the channel abilitys like Beam from AM and Rune of Fire from dps-RP. ITs annoying and game breaking imho. After the beam is gone a sun-orb appears on my character that light him up like a damn Xmas tree. 

![kxk9I0U](https://user-images.githubusercontent.com/23266079/182928728-f54570bb-2951-42dd-bfec-a5831b9eba4d.png)

**Comment by lilimx** [comment]
Hey,

I need a few more test pictures or a video. 
Tried to reproduce it and it works fine on my end.

**Comment by ravezaar** [comment]
https://cdn.discordapp.com/attachments/373155396275404814/1004747480858107964/Screenshot_186.jpg

**Comment by ravezaar** [comment]
there is from another player, its the Am laser beam u see it all the time since yesterday in RvR. like every sec online so how can u not see it ? AMs with like 4-5 beams still locked on targets and this sun-orb is end result. U have to fly to other Zone or relog to get it off

**Comment by lilimx** [comment]
Hey,

okay....let's try again. 
we are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report and provide:

- Steps to reproduce the problem
- Testing Screenshots/Videos/Evidences
- Please one issue per ticket.

A picture of a glowing player is nothing that can help us to reproduce the issue.

**Comment by ravezaar** [comment]
How about u step out in the RvR ?

**Comment by ravezaar** [comment]
I give up

**Comment by ravezaar** [comment]
https://clips.twitch.tv/ClearFriendlyAdminPhilosoraptor-nlIAMy2hP-M8BETN

**Comment by Majorzero2123** [comment]
![image](https://user-images.githubusercontent.com/99697728/183049391-7d762e4f-3ba9-4fa0-abdf-16b7b6212ea5.png)
Visual settings for reference 
![unknown (3)](https://user-images.githubusercontent.com/99697728/183049493-92d9199b-ae0b-4352-aad2-6fe6e70c1936.png)
After being hit with The Archmage beam channel (Searing touch i believe) Visual effect from ability persists on character after death, can only be removed if you change zones. 
Video evidence: https://www.youtube.com/watch?v=gyCkpCai8fk

**Comment by ravezaar** [comment]
can also add Order chars suffer aswell, seen Ravens circling targets so I assume some Zealot or Sorc channel skill bugs same way

**Comment by Scophis** [comment]
Got this nice lasershow going on my AM ^^
The beams stayed active even at very long ranges and disappeared as the bodies vanished.
![Loarelle_013](https://user-images.githubusercontent.com/40274248/183114631-5a160b5c-6cca-463b-81bf-1a9b37199470.jpg)^

**Comment by lilimx** [comment]
okay, did a few tests on my AM.
It mostly happens when you don't face your enemy directly and using "searing touch".

**Comment by ravezaar** [comment]
just so u dont go crazy trying to solve this, its not ONLY AMs its seems to be several channel skill from Zealot, RP aso aswell

**Comment by lilimx** [comment]
Hey,

okay, I close the conversation now, due too much stupid comments from the OP.
This is the bug tracker not the forum. Keep your comment straight to the topic witout any passiv aggressive comments.

**Comment by lilimx** [comment]
Hotfixed 08/08/2022
