### ISSUE TITLE
I Constantly Lose my Guild

### ISSUE THREAD

**Issue by RayLGunS-W-G** [WarEmu/WarBugs#20295]
Hello There

I Have the weird Problem that every 3-4 Days i Stand there without a Guild and must be reinvited

Could you Please look over my Account if there is anything wrong with it?

Account Name is Colephis

**Comment by lilimx** [comment]
Hey,

have you ever suffered from the guild-login issue or so?
Guess someone has to check your DB entry.
Is it only on one character?
Is there anything weird while you are member or a guild or right after "got kicked"?

**Comment by RayLGunS-W-G** [comment]
The weird thing is there is nothing in Guild Log

Not that i got kicked and not that i left im just out

**Comment by Quotation3277** [comment]
Hey, I and several guildmates have the same issue. We're all new to the guild.

Name of the char / account / guild : Loug / Loug / Juggernaut

**Comment by RayLGunS-W-G** [comment]
Account / Char / Guild
Colephis / Brokk / Bitterstone Thunderers

**Comment by jdh6955** [comment]
I have also had this issue on two characters.

Account/Char/Guild
jdh6955 / Sieglaf / Bitterstone Thunderers
jdh6955 / Reiklaf / Bene Tleilax

**Comment by MaxHayman** [comment]
I have found the issue. I will need to do some database fixing on the next patch for this. Sorry for any inconvenience.

**Comment by lilimx** [comment]
fixed with patch [10/09/2022]
