### ISSUE TITLE
Received wrong amount of items bought from AH

### ISSUE THREAD

**Issue by Symbelmyne** [WarEmu/WarBugs#20293]
I (Greenlion) bought hour ago 1 stack of pots  (green 1500 HP) and I went for shopping, logged back now and received 6 stacks of pots.

![WAR-64 2022-08-04 13-40-14](https://user-images.githubusercontent.com/16525371/182839573-22fd6476-4c87-4df9-bc8e-cb9c9779ca1c.png)

**Comment by MaxHayman** [comment]
Should have been fixed. Please reopen if that is not the case.
