### ISSUE TITLE
Genesis Crests // War Crests missing in bags

### ISSUE THREAD

**Issue by osfalpha** [WarEmu/WarBugs#20297]
**Expected behavior and actual behavior:**
Genesis crests are no longer in my bag - there should be some (character - Gygeth - Order)

**Steps to reproduce the problem:**

N/A

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by JohnnyWayne89** [comment]
Any crests are missing: 
![grafik](https://user-images.githubusercontent.com/104304559/183011435-392b2b36-018c-4771-85a3-bddcd7e66ed0.png)

**Comment by lilimx** [comment]
Hey,

I need a few more information. 
Is this from a PQ? open RVR?

**Comment by JohnnyWayne89** [comment]
Open RVR of course. City bags can't be opened once they are sent after you thorugh mail either.

**Comment by JohnnyWayne89** [comment]
See this one, same issue: https://github.com/WarEmu/WarBugs/issues/20290

**Comment by lilimx** [comment]
Hey,

yeah sorry....just read crests. 
But yeah I guess it's related to: #20290

**Comment by unflaggmyaccount** [comment]
Same here. 2 bags, purple and green - nothing there, nor crests neither genesis

**Comment by zolio1236** [comment]
![Alexander_024](https://user-images.githubusercontent.com/37667147/183234343-72f8ec2c-cf99-4a73-80bd-9aa856156b83.jpg)
Same issue, open bag from chaos waste zone take last night and no crests or Gen Coins.

**Comment by lilimx** [comment]
Issue still persists after the patch

**Comment by zolio1236** [comment]
![Revolver_032](https://user-images.githubusercontent.com/37667147/183269487-3e729490-6c10-4eee-bbf3-929d29162455.jpg)
Bag from Reikwald be for Lotd started. Still no crests

**Comment by Rubyeclipse-war** [comment]
Additional information on how this bug works:

1. When a bag is awarded via Zone lock / Fort / etc, if you head to the location of the "Completed PQ" that appears and **physically take a bag out of the golden chest**, you'll get a bag with War Crests / Genesis / etc, as it should be.

2. However, **if a bag is not picked up manually** and is sent through the mail system, it will take a considerable amount of time (1h+) and when opened, will only contain non-War crest rewards, like gold, cultivating dirt, apothecary boxes, etc. 

This has probably already been identified, but just wanted to clearly spell it out after testing in case it helps.

**Comment by bulgy70** [comment]
> Additional information on how this bug works:
> 
>     1. When a bag is awarded via Zone lock / Fort / etc, if you head to the location of the "Completed PQ" that appears and **physically take a bag out of the golden chest**, you'll get a bag with War Crests / Genesis / etc, as it should be.
> 
>     2. However, **if a bag is not picked up manually** and is sent through the mail system, it will take a considerable amount of time (1h+) and when opened, will only contain non-War crest rewards, like gold, cultivating dirt, apothecary boxes, etc.
> 
> 
> This has probably already been identified, but just wanted to clearly spell it out after testing in case it helps.
I should point out that physically taking a bag out of the golden chest, has also been bugging out when Destruction have taken keeps. and no one was able to pick up their bags.

**Comment by kyeo138** [comment]
> I should point out that physically taking a bag out of the golden chest, has also been bugging out when Destruction have taken keeps. and no one was able to pick up their bags.

Confirmed.  FYI just now tried to loot a bag in Saphery/Avelorn keep as Destro, and wasn't able to claim anything (lesser green bag). Others reported the same.

**Comment by tylersund72** [comment]
Along with what's stated about the bags, I noticed something with the rewards for locking a zone. I have done 3-5 T2-T3 zones since the patch a week ago, and they have all given me renown and crests for locking the zone, but I haven't had a single T4 zone give me those rewards at all yet. Thought I'd share that information since I haven't read anyone else talking about it specifically.

**Comment by topdudes** [comment]
Bag contents from DW pity flip 8/8/22 at approx. 6pm PST (GMT -7
![Squatshooter_070](https://user-images.githubusercontent.com/81526782/183770223-845d95f5-a546-4ecc-b40f-f91aa039955d.jpg)
)

**Comment by Rubyeclipse-war** [comment]
Max did a hotfix today that appears to have fixed all new bags that get mailed out - I tested and confirmed it worked fine on my side! Please let us know if anyone is still seeing missing War Crests / Genesis Shards in new bags that get mailed; they should all work now.

**Comment by lilimx** [comment]
Hotfixed 10/08/2022
