### ISSUE TITLE
DESTRO QUEST "A Subtle Wind" PART 4

### ISSUE THREAD

**Issue by Hauclir** [WarEmu/WarBugs#203]
![hauclir_003](https://cloud.githubusercontent.com/assets/7598530/3489532/e027c6a4-0533-11e4-9dd8-6f4c1d24727a.jpg)
![hauclir_002](https://cloud.githubusercontent.com/assets/7598530/3489533/e462b53a-0533-11e4-8286-54a33e6c44b3.jpg)
![hauclir_001](https://cloud.githubusercontent.com/assets/7598530/3489534/e6c933bc-0533-11e4-9393-e098b4f5dab2.jpg)
NPC QUEST GIVER: Pieter Falke
Your suppose to get a "key" from Pieter Falke shown in 2nd SS to access the Fishes Flask tavern shown in 3rd SS, inside there should be items on the counter for you to collect to complete the quest and turn into Gaert Werden.

**Comment by Meralors** [comment]
Door have been fixed, you can now complete quest.
