### ISSUE TITLE
[Auction House] Cannot post second item 

### ISSUE THREAD

**Issue by wildwindblows** [WarEmu/WarBugs#20308]
Hello RoR Team,
After I post Sentinel Aspis item, I couldnt post Harbinger Makhiara item to AH. Please see the picture below.

**Expected behavior and actual behavior:**
I supposed to post any item which is Bind on equip. However, after couldn't post an item after second post.

**Steps to reproduce the problem:**
After post and first item, try to post second one and see you cannot post it.

**Testing Screenshots/Videos/Evidences (always needed):**
![Sirzero_104](https://user-images.githubusercontent.com/45720515/183257562-a717dc53-68f4-475e-a573-07cf1a95bdda.jpg)

![Sirzero_105](https://user-images.githubusercontent.com/45720515/183257567-312cf405-b682-4d08-98e5-6c7035d61f30.jpg)

Bests,
Sirzero.

**Comment by wildwindblows** [comment]
Also i tried with different item and still couldn't post it.
![Sirzero_106](https://user-images.githubusercontent.com/45720515/183257724-258f583a-c6dd-4f02-abfc-091368688be7.jpg)

**Comment by lilimx** [comment]
Hey, 

could you try to deploy this item without shinies.

**Comment by wildwindblows** [comment]
I tried without shinies but still cannot post item. Please see the photos below.

![Sirzero_107](https://user-images.githubusercontent.com/45720515/183628610-996be63b-9b56-491e-a421-843b64b862ca.jpg)
![Sirzero_108](https://user-images.githubusercontent.com/45720515/183628625-8be06b4a-602a-4b15-ab3c-be2649c9b131.jpg)

**Comment by lilimx** [comment]
Hey,

how many things are you selling right now? there is a limitation of 33 auctions at once.

**Comment by wildwindblows** [comment]
I count 49 item in ah currently.

**Comment by lilimx** [comment]
okay, checked....more than 50 auctions could cause issues....so mabye there is a Llmitation.
