### ISSUE TITLE
Beastlord hunting guide cooldown bug.

### ISSUE THREAD

**Issue by Souloftheskies** [WarEmu/WarBugs#20300]
**Expected behavior and actual behavior:**

Use beastlord book, have a buff, have a cd on the book for ... minutes. Actually it applies the buff without having a cd.

**Steps to reproduce the problem:**

Enter BS with a group, use beastlord book.

**Testing Screenshots/Videos/Evidences (always needed):**

Can attach later

**Comment by lilimx** [comment]
fixed with patch [11/08/2022]
