### ISSUE TITLE
AM's Perma Skill Animation Bug

### ISSUE THREAD

**Issue by wildwindblows** [WarEmu/WarBugs#20304]
Hello RoR Team,
Currently, AM's giving perma animation bug as indicated below. I dont know the exact skill but it might be Searing Touch. Thanks

**Testing Screenshots/Videos/Evidences (always needed):**
![Sirzero_087](https://user-images.githubusercontent.com/45720515/183245461-4ec6b47b-d864-4b41-9619-a7ef158f39bc.jpg)

Bests,
Sirzero.

**Comment by lilimx** [comment]
Hey,

thank you for your report.
This issue is already known.
So I will add your report to the related one.

**Comment by lilimx** [comment]
dublicate of #20292
