### ISSUE TITLE
No War Crest in Bags

### ISSUE THREAD

**Issue by bulgy70** [WarEmu/WarBugs#20309]
When openning Bags there are no war crests in any of the bags.
![Bulgy_006](https://user-images.githubusercontent.com/44948480/183261866-360a18a8-37ba-40f0-9d27-a56786e01ef4.jpg)

**Comment by Amadon82** [comment]
Same, got a bag yesterday post-patch, and it don't contain war crests nor genesis crests.
![loot3](https://user-images.githubusercontent.com/19516183/183276603-12d66505-48bd-40c8-98da-1efde0ca9a04.JPG)

**Comment by bulgy70** [comment]
I should point out that, all bags i have had. has had this issue since the last patch

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
This issue has been already reported.

**Comment by lilimx** [comment]
dublicate #20297
