### ISSUE TITLE
No war crest in bag or no bag in letter

### ISSUE THREAD

**Issue by Utgardh** [WarEmu/WarBugs#20311]
Different problem : 

1. No bag in letter after the lock
![Ravhen_006](https://user-images.githubusercontent.com/110761333/183280461-f0990867-8e28-4c5e-9592-609cfc9f246a.jpg)

2. No crest or genesis in bag
![Ravhen_009](https://user-images.githubusercontent.com/110761333/183280474-2d0ed407-ab64-474e-9c41-80a4be9bb501.jpg)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
This issue has been already reported.

**Comment by lilimx** [comment]
dublicate
#20297
