### ISSUE TITLE
Divine Assault damge

### ISSUE THREAD

**Issue by Asdar2** [WarEmu/WarBugs#20319]
Divine Assault  damage instead of healing

![2022-08-09_18-11-09](https://user-images.githubusercontent.com/16272439/183717096-3a5b4d0e-f9b5-49a0-8dc8-4336fc7090eb.png)
![2022-08-09_18-11-30](https://user-images.githubusercontent.com/16272439/183717105-f20003f2-2027-402a-967c-2f6cd0988b35.png)
![2022-08-09_18-21-06](https://user-images.githubusercontent.com/16272439/183717111-9adf0644-1fe8-46a8-8189-4aaac5dabc57.png)

**Comment by lilimx** [comment]
dublicate #20289
