### ISSUE TITLE
No cooldown with Guild Recall Scroll

### ISSUE THREAD

**Issue by Amadon82** [WarEmu/WarBugs#20316]
When you use a Guild Recall Scroll, no more cooldown show on the icon of the item. And you can use it right after again, and the recall woks, teleporting you again in the War Quarters (for Order Player).

**Steps to reproduce the problem:**

 - Be out of the War Quarters, and use a Guild Recall Scroll.
 - Once done, you can see there is no cooldown on the GRS. Now, just get out of the War Quarters.
 - Repeat the first step.

**Testing Screenshots/Videos/Evidences (always needed):**

Can't do a video, it would have been easier...
First screen taken before using the scroll, 14:12:10
Second screen after the scroll was used. 14:12:43
You can see there is no more cooldown, and you can just use the scroll at will.

![bug](https://user-images.githubusercontent.com/19516183/183415310-a04a908c-b9ea-4f3d-914a-0c8e6205548f.JPG)
![bug2](https://user-images.githubusercontent.com/19516183/183415320-8a75196d-99be-4e06-9b85-e00f7c81a181.JPG)

**Comment by Issard** [comment]
beastlord pocked item as well as ror aegis also have no cooldown now.

**Comment by lilimx** [comment]
fixed with patch 12/08/2022
