### ISSUE TITLE
Chosen Quest: Dark Flame Scepter

### ISSUE THREAD

**Issue by BicycleOfDeath** [WarEmu/WarBugs#20314]
During the quest when the pelt pile is interacted with and Krul'Tor spawns (he does), he did not drop the Dark Flame Scepter and I can not get him to respawn. Location: Ragash's Last Stand (Ostland)

**Steps to reproduce the problem:**
Follow the questline up to that point.

**Testing Screenshots/Videos/Evidences (always needed):**

![darkflamescepter](https://user-images.githubusercontent.com/49738243/183299114-2a87ba0c-9811-4453-a04a-b2c2c9df3cc8.jpg)

**Comment by Lheana** [comment]
![Anaehll_267](https://user-images.githubusercontent.com/11537611/233682638-170ee788-617f-47d8-b7d3-ae170dcce7fc.jpg)
It drops for me.
