### ISSUE TITLE
[Zealot] Manipulation tactic deals 4000 damage each time it procs

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#20310]
**Expected behavior and actual behavior:**

Expected: the Zealot's Manipulation tactic has a 25% chance to deal 25% of your direct healing as (physical?) damage

Actual: since the recent patch, the Manipulation tactic now has a 25% chance to deal 4000 damage after mitigation, regardless of heal amount.

BTW Manipulation also procs from group healing (6 chances per group heal in a full group, assuming everyone is damaged) and the healing ritual (6 chances per passive healing pulse every 3 seconds, again assuming a full group that has taken damage).

**Steps to reproduce the problem:**

1) Be a Zealot
2) Spec and equip Manipulation from Path of Alchemy
3) Target a hostile
4) Heal an ally, including yourself. Overheal didn't used to work before, forgot to test it now, so heal someone who has taken damage
5) Cry at the 4k damage done to the enemy.

**Testing Screenshots/Videos/Evidences (always needed):**

My testing:

![image](https://user-images.githubusercontent.com/60266177/183267748-46d85080-d0af-406b-8484-94316b901c38.png)

![image](https://user-images.githubusercontent.com/60266177/183267749-b166ac28-6e41-46f9-91a9-48a9f7559fe2.png)

Someone else in Discord showing them being hit by Manipulation in a tier 3 scenario:

![image](https://user-images.githubusercontent.com/60266177/183267754-207911e2-d0d9-473e-9ce6-de7e06a3a317.png)

**Comment by haeborwen** [comment]
[https://www.youtube.com/watch?v=qH0gj6Vs4Zk](url) Took a very choppy recording tonight with this same zealot.

**Comment by Rubyeclipse-war** [comment]
Here's a clear video of this bug in action: https://www.youtube.com/watch?v=XwR730eDmU8

**Comment by Haojun-Phalanx** [comment]
can confirm:
 
![image](https://user-images.githubusercontent.com/23129933/183293000-cecf0ab0-1efc-498a-9fbb-9f1dd823a8bb.png)

**Comment by lilimx** [comment]
Hey,
thank you all for the comments, the fix is pending.

**Comment by lilimx** [comment]
Hotfixed 8/8/2022
