### ISSUE TITLE
Zone lock sometimes gives no Renown / War Crest payout

### ISSUE THREAD

**Issue by Rubyeclipse-war** [WarEmu/WarBugs#20323]
_(Please note, this bug is unique from the Zone lock Bags not awarding War Crests when mailed, which has been fixed.)_

Sometimes when locking a zone, players in a faction - and it appears to be the entire faction - will get 0 Renown and 0 War Crests for the Zone lock.

Video here taken moments after this happened in Praag: https://www.youtube.com/watch?v=sUlTbP3D_EI

Players on both Destruction and Order have reported this happening in Empire T4 zones, but it may be happening in many zones. I'm not sure yet what the pattern is that causes this to occur sometimes.

Additional Images from the Destro side (Thank you Brokensafety for sharing these!):
![destro zone lock bug](https://user-images.githubusercontent.com/60584990/183842054-6187ba2f-c5c0-4b98-8bb3-df4fb835ea5f.png)

![Destro Zone lock bug 2](https://user-images.githubusercontent.com/60584990/183842058-09184aca-7ac1-4e05-8ab0-73122731d7a2.png)

Thanks for looking into it! If anyone else has more info, please share here.

**Comment by MaxHayman** [comment]
When did this start?

**Comment by alyssonpaladini** [comment]
Not only empire, dorfs and elf too. Played 2 zones yesterday on my destro toons and logoff coz wasnt rewarding RR neiter crests at zone flip.

**Comment by tylersund72** [comment]
> When did this start?

Ever since last weeks initial mail patch, I've been experiencing it in most zones that I've participated in.

**Comment by alyssonpaladini** [comment]
Ok, so heres the screenshots as you asked wargrimmir
![Gorkmorkboi_000](https://user-images.githubusercontent.com/101071916/184715088-e3aa4e8a-6f27-4d6b-9f64-8fa87dd83acc.jpg)
Zone flip - Reikland  / been there over 1h+ with wb and solo too.

**Comment by alyssonpaladini** [comment]
![Gorkmorkboi_003](https://user-images.githubusercontent.com/101071916/184715331-3515b466-2357-4a11-9b13-ed8a768d0942.jpg)
KV Keep def - Been there over 2h+ nothing too

**Comment by alyssonpaladini** [comment]
Just a SS to prove I had enuff participation for both maps, before I quit the wb
![Gorkmorkboi_004](https://user-images.githubusercontent.com/101071916/184715582-d9e1fb3f-94cf-4bfa-9774-9d4fcff0f3a4.jpg)
.

**Comment by alyssonpaladini** [comment]
Zone Flip - Praag
![Gorkmorkboi_000](https://user-images.githubusercontent.com/101071916/184725183-8d3cfa27-c438-4740-add1-da5f09f5af5b.jpg)

**Comment by alyssonpaladini** [comment]
KV Zone Flip
![Gorkmorkboi_000](https://user-images.githubusercontent.com/101071916/184732024-e6c3c691-4272-4803-8962-c6444b9a84b3.jpg)
Maybe the zone flip was 201? No tokens.

**Comment by MaxHayman** [comment]
Thanks guys, great info. Fix will go live in the morning!

**Comment by lilimx** [comment]
Hotfix 16/08/2022
