### ISSUE TITLE
Siege weapons have no cooldown.

### ISSUE THREAD

**Issue by darkt1981** [WarEmu/WarBugs#20324]
When in Thunder mountain (not tested in other zones yet) 1 person can summon multiple cannons at a times, till the caps is filled.
In stead of 1 per person.

**Expected behavior and actual behavior:**

Just summon siege weapon.

**Testing Screenshots/Videos/Evidences (always needed):**
dont have but i have tested it in game.

**Comment by lilimx** [comment]
Hey,

I found your text. Please check your tickets after you sent it.
This issue is related to #20316
