### ISSUE TITLE
Book of Binding Cooldown Timer, and Horn of the Vale Wolf Items Not Working Properly

### ISSUE THREAD

**Issue by WickedPiston** [WarEmu/WarBugs#20321]
**Expected behavior and actual behavior:**
"Horn of the Vale Wolf" Item seems to be unusable, only gives a message "This item cannot be used yet." The same effect seems to have happened to my Book Of Binding, which seems to not be showing the cooldown timer properly. Also giving the same message "This item cannot be used." Until I assume the invisible timer is up. 

I'm not sure how to replicate this or if it needs any replication, I am unsure if it has something to do with me exiting the Hunters Vale instance the way I did the first time or if the item "Horn of the Vale Wolf" itself is just broken. Along with the cooldown timer for the Book of Binding being broken with it.

Logging out and logging back in, resetting the client, or using /rel does not fix this problem.

**Steps to reproduce the problem:**

Use the Book Of Binding then notice the missing timer and also Use the item "Horn of the Vale Wolf" to notice that nothing happens.

**Testing Screenshots/Videos/Evidences (always needed):**

The moment I received the item

https://user-images.githubusercontent.com/107617937/183786244-5aafc131-53e4-4a55-acde-17a8f5233328.mp4

The moment I used Book of Binding to leave the Hunters Vale instance

https://user-images.githubusercontent.com/107617937/183786257-94609925-f16d-46c8-8926-c1b990c6512e.mp4

Trying to use the item in Praag, gives message "This item cannot be used yet." Also noticeable my Book of Binding does not have a cooldown timer and I later realize it gives the same message.

https://user-images.githubusercontent.com/107617937/183786278-7f9fec74-43ae-445a-b9d1-867732645f0d.mp4

Trying to use the item in Altdorf

https://user-images.githubusercontent.com/107617937/183786295-631cbd26-b7b6-4e84-b3d8-9b7e56d12872.mp4

Trying to use the item in Troll Country to ensure I wasn't flagged for RvR

https://user-images.githubusercontent.com/107617937/183786309-d0570404-fd07-4d21-bbd3-620eb9da5db0.mp4

Realizing that my Book of Binding also doesn't work after having exited the Hunters Vale instance after a second run.

https://user-images.githubusercontent.com/107617937/183786362-834af999-8736-4a9a-bf87-2e6706dfe1b9.mp4

**Comment by WickedPiston** [comment]
My bad again Lilim I think this has already been posted under "Guild Scroll Timer Not Working"

**Comment by lilimx** [comment]
Uhm, well yes ;)
Nice videos!

Related to/dublicate #20316
