### ISSUE TITLE
[Marauder] Tainted Claw Negative Damage Value

### ISSUE THREAD

**Issue by wildwindblows** [WarEmu/WarBugs#20329]
Hello RoR Team,
Tainted Claw hits negative damage. Please see picture below. Thanks

**Testing Screenshots/Videos/Evidences (always needed):**
![Sirzero_110](https://user-images.githubusercontent.com/45720515/184425667-7fed924c-3552-406e-b3e3-a18dd5f00988.jpg)

**Comment by Onlyendari** [comment]
All lifetaps are showing as negative damage both in the log and in the combat text

**Comment by xpander69** [comment]
https://github.com/WarEmu/WarBugs/issues/20334
related

**Comment by lilimx** [comment]
related to #20289
