### ISSUE TITLE
Cannot log with one of my characters

### ISSUE THREAD

**Issue by engorin** [WarEmu/WarBugs#20325]
After finish a scenario, i got disconnected to character screen and now cannot log with that one. It only happends with one of my characters, rest are fine.
Faction: Destruction 
NameCharacter: Pullitas 
Class: Squig 
Level: 39/51

**Comment by xpander69** [comment]
Typing blindly /stuck twice during loading screen could fix it. But the server restarted this morning so your character should be able to get in again. Let us know

**Comment by engorin** [comment]
The problem has already been solved, with the reboot this morning
