### ISSUE TITLE
Shadow Prowler

### ISSUE THREAD

**Issue by gman4gov** [WarEmu/WarBugs#20320]
**Expected behavior and actual behavior:**

Shadow Prowler ability is not working correctly.  Cannot leave stealth mode correctly.  cooldown timer issue.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

https://www.youtube.com/watch?v=8KYb8HOArv

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
This issue has been already reported.

**Comment by lilimx** [comment]
dublicate #20302
