### ISSUE TITLE
Horn of the Vale Wolf Pet Item Not Working

### ISSUE THREAD

**Issue by WickedPiston** [WarEmu/WarBugs#20326]
**Expected behavior and actual behavior:**
Expected behavior would be to see a pet follower after using the item in the proper zone. Instead the item only displays a message in chat "This item cannot be used yet."

**Steps to reproduce the problem:**
Use Horn of the Vale Wolf item to notice nothing happens

**Testing Screenshots/Videos/Evidences (always needed):**

![Screenshot (340)](https://user-images.githubusercontent.com/107617937/184273657-7a3e2b60-133d-44c3-a343-f6ed61cb2a3b.png)

https://user-images.githubusercontent.com/107617937/184273615-c3d83812-f007-4df4-ad0c-323428407649.mp4

**Comment by WickedPiston** [comment]
This has been fixed in the newest patch.

**Comment by lilimx** [comment]
@WickedPiston 

Ah, nice!

**Comment by lilimx** [comment]
Fixed with patch [14/09/2022]
