### ISSUE TITLE
[WE] Kiss Of the Doom doesn't heal as  expected, also heal logs doesn't works as expected

### ISSUE THREAD

**Issue by Star-dust** [WarEmu/WarBugs#20332]
**Expected behavior and actual behavior:**
Kiss of the Doom should heal every time Kiss of the Death proc, but now sometimes Kiss of the Doom doesn't heal when Kiss of the Death proc.
Furthermore following issue still happening:
https://github.com/WarEmu/WarBugs/issues/20298

**Steps to reproduce the problem:**
Use Kiss of the doom

**Testing Screenshots/Videos/Evidences (always needed):**

[Shot](https://ibb.co/16kVmCj)
[Shot](https://i.ibb.co/rsVPwBN/Screenshot-from-2022-08-14-13-00-59.png)

**Comment by coltylul** [comment]
Problem only with combatlog. With this problem he doesnt show overheal. On your screenshots sometime you takes damage from training construct. Besides combatlog all fine.

**Comment by Scophis** [comment]
Have you tested it with lower HP? (e.g with pve-mobs)
As far as I know lifetap heals only show up in combatlog when they actaully heal.

**Comment by xpander69** [comment]
related i guess? https://github.com/WarEmu/WarBugs/issues/20329

**Comment by Zomega-WAR** [comment]
KoD showing up as "hitting you for -2 damage" is part of the general lifetap display bugs going on (linked above). However, the healing not showing up a full health is to my knowledge intended and happens with all lifetaps.

**Comment by lilimx** [comment]
also maybe related to #20289
