### ISSUE TITLE
Khaines embrace warcamp breach.

### ISSUE THREAD

**Issue by TrueDas** [WarEmu/WarBugs#20331]
Hi. 
Was farming the scenario and figuered out the possibility to get to the warcamp of the enemy. The possibility is plain and simple. The "fog wall" or how should I call the barrier has a hole in it. Was playing destro side.
![Veldt_001](https://user-images.githubusercontent.com/111179138/184479424-57263716-7c44-4a6d-93d1-5522a960f576.jpg)
![Veldt_002](https://user-images.githubusercontent.com/111179138/184479427-d721d02f-599c-4f9f-9d58-5ed8751c20f7.jpg)
![Veldt_003](https://user-images.githubusercontent.com/111179138/184479433-4d71418e-60cf-4ad4-9ae0-b008e88f5194.jpg)
![Veldt_004](https://user-images.githubusercontent.com/111179138/184479434-ba45a67d-8bbf-43d4-adf4-979b3840864e.jpg)

**Comment by lilimx** [comment]
Hey,

looks like there is already a report with the same bypass technic.
I will add your ticket to this one.

**Comment by lilimx** [comment]
related maybe a dublicate #20041
