### ISSUE TITLE
[Combatlog] Lifetaps shown as negative damage

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#20334]
Related to #20289 

After the patch 12/08/22 lifetaps still show up as negative damage.
![Loarelle_030](https://user-images.githubusercontent.com/40274248/184536486-734b3b9a-b442-4a08-81e2-8832e1d0a6ee.jpg)

**Comment by xpander69** [comment]
https://github.com/WarEmu/WarBugs/issues/20329
related closing.
