### ISSUE TITLE
Weekend SC Giving 200 renown for a win

### ISSUE THREAD

**Issue by Emissaryx** [WarEmu/WarBugs#20330]
Weekend sc is not giving the 50% increase in renown. 5 scs and am only averaging 200 to 400 for wins in the scs but my xp is averaging over 18k.
![Capture](https://user-images.githubusercontent.com/107319355/184462415-28894609-6e93-4277-b27f-127265acdde4.PNG)

**Comment by MaxHayman** [comment]
Fixed during the weekend.
