### ISSUE TITLE
Unable to turn in Supply at Resource turn-in flag

### ISSUE THREAD

**Issue by Rubyeclipse-war** [WarEmu/WarBugs#20340]
Across multiple tiers, players are unable to turn in Supply at the Resource turn-in flags. 

The character will kneel and the cast bar will appear, but the supply will not turn in and the character sticks in the kneeling animation, even when moved afterwards.

**Video of this in Tier 1:**  https://www.youtube.com/watch?v=DUS2CB067mc

Besides Tier 1, there are reports of this happening in Tier 4, so it may impact all zones. Some players say they are able to turn in a single supply, but are then bugged and cannot turn in any others.

**Comment by Amadon82** [comment]
Made some test in t4 as well, but can't have videos.
So once you take one box, you can drop one sup in keep, then one other in warcamp, and things is brocken. You have to relog if you want to be able to run supply again.
Plus i've found one destro supply (i play order), and i was unable to take this one cause "someone already interacting with this", but i was all alone.

**Comment by Amadon82** [comment]
Update : for the boxes who are unusable, it's because someone logged off the game with the box, and that made the box bug.
Just tested this. Dunno if the fix will fix that too.

**Comment by Amadon82** [comment]
Was able to carry two sups at the same flag. Things seems to work correctly again.

**Comment by Bantafutta** [comment]
T1 Still bugged

**Comment by MaxHayman** [comment]
> T1 Still bugged

Thanks we have a fix in progress

**Comment by termofor** [comment]
Boxes working correctly now BUT: Box that was dropped by another person cannot be picked anymore.

**Comment by MaxHayman** [comment]
Fix pending for that

**Comment by lilimx** [comment]
fixed with patch [10/09/2022]
