### ISSUE TITLE
T1 zone Lock 

### ISSUE THREAD

**Issue by OneTrueKing-TouchPad** [WarEmu/WarBugs#20346]
When locking down Nordland in T1 earlier today only one of the points locked. the other 2 are still able to be captured and produce supplys.  Giving people extra Renown and Exp. 

**Expected behavior and actual behavior:**
All points should lock and no longer produce supply boxes and not give Free RR and EXP

**Steps to reproduce the problem:**

See nordland Right now, one point locked the others are not 

**Testing Screenshots/Videos/Evidences (always needed):**

![Screenshot 2022-08-18 110610](https://user-images.githubusercontent.com/111500608/185369808-e52b9ce1-afed-4de9-9db7-ad462e4f551c.png)

**Comment by OneTrueKing-TouchPad** [comment]
![T1 issue](https://user-images.githubusercontent.com/111500608/185371490-c7afd26e-6253-4894-95e2-70309c2c155e.png)
![T1 issue 2](https://user-images.githubusercontent.com/111500608/185371510-25e5f784-4a56-4060-8886-00ac7fedc125.png)

**Comment by OneTrueKing-TouchPad** [comment]
there is also still the issue of, supply boxes being dropped upon death not being able to be picked back up, constantly saying another person is currently Using ( or words to that effect ). and i believe this is happening in all T1 zones

**Comment by OneTrueKing-TouchPad** [comment]
![T1 Issue 3](https://user-images.githubusercontent.com/111500608/185457175-7ff27a09-cae8-4c32-bc1a-9e2eb0975dcd.png)

**Comment by OneTrueKing-TouchPad** [comment]
Its still happening but clearly constantly switching from 2 locked to having only 1 locked. 

sorry to be a pain but thought id try and help you guys out as much as possible.

**Comment by MaxHayman** [comment]
![image](https://user-images.githubusercontent.com/1018809/185495365-43fc80a3-5873-4b39-b1df-83e481661480.png)
![image](https://user-images.githubusercontent.com/1018809/185495384-dcce0b20-b204-4e24-ae45-eba5bb5a83d3.png)

Made a small code change which should hopefully fix it. It works for me at least.

**Comment by OneTrueKing-TouchPad** [comment]
![Dwarf T1 Locked 2](https://user-images.githubusercontent.com/111500608/185494987-aff35d25-682f-4fff-a0ac-48deafdfd08b.png)

Hey guys sorry to bother you again, but same issue slightly different for Dwarf T1 as its Locked constantly. but only showing 1 locked sign on one BO. and its not  spawning any boxes

**Comment by lilimx** [comment]
fixed with patch [10/09/2022]
