### ISSUE TITLE
Jailbreak lever in Fort does nothing 

### ISSUE THREAD

**Issue by Majorzero2123** [WarEmu/WarBugs#20345]
**Expected behavior and actual behavior:**
Expected behaviour: use fort lever, let couple people out of jail
Current behaviour: Use fort lever, everything else is normal but it doesn't let anyone out of jail and goes back on cooldown.

**Testing Screenshots/Videos/Evidences (always needed):**
Will grab SS/video Later, just posting this now so it can be looked into/tested.

**Comment by Rubyeclipse-war** [comment]
To add, this happened just now at the Shining Way Fortress.

Zero told me he was able to kneel down and see the Cast Bar which indicates the lever is off cooldown, but after the cast bar finished, Order was not freed from the jail. 

As the player also goes into a kneel animation and a similar cast bar appears for jailbreaks, this may also be related to Supply issue #20340.

**Comment by lilimx** [comment]
Hey,

could someone please test it. Maybe it was fixed with the restart this morning.

**Comment by Majorzero2123** [comment]
UPDATE: Fixed with server restart. Will close ticket
