### ISSUE TITLE
Mount always more slow than any other players

### ISSUE THREAD

**Issue by bleifuss22** [WarEmu/WarBugs#20341]
**Expected behavior and actual behavior:**
At my account "MacSnipe" I do have the problem that all my chars with all my different lvl.38 (40+) mounts are slower than other players mounts.
When I start and ride side-by-side with other players, i loose position and fall back a lot. At 100yards I do loose about 10 yards to other players. Destro players can follow and capture me, because they are more fast than ALL my mounts, also. 
I tested it and can say: My mount speed is between lvl38+ mount and a char who is riding with a cannon at siege f.e.

So unfair and pathetic. Am I disadvantaged?

**Steps to reproduce the problem:**
Start f.e. char MacSnipe, take Copter or LotD-horse and ride side-by-side along with any other player on lvl38+ mount

**Testing Screenshots/Videos/Evidences (always needed):**
no picture, because it is so easy too recognize, if you play...

**Comment by lilimx** [comment]
Hey,

are you playing the 32-bit version or the 64-bit version of RoR (you can find the setup in your launcher > cog )

**Comment by bleifuss22** [comment]
it´s the 64-bit version

**Comment by lilimx** [comment]
if you can try the 32-bit one.
I guess it's related to this issue: #19002

**Comment by bleifuss22** [comment]
Well, is it save to play 32-bit client with Windows-64bit?

**Comment by lilimx** [comment]
Hey,

yeah its stupidly named in launcher...both are actually 32bit anyway and Large Address Aware patched so they can use more addressing space... just the WAR-64 has uncapped framerates...but that old engine is not meant to do that... so animations go bust. 

Just try it out, if you experience performance issues, it's better to switch back to the 64-bit. But otherwise the 32-bit one is fine.

**Comment by bleifuss22** [comment]
Well, anyway, 32-bit "named" client runs with same speed mounts. Hooray...
But let me say, 64-bit as fake is used from all dont-know-newbies and so it has disadvantage....
It has to be said at patch notices, its an unsolved "problem". Player should decide, if no performance in heavy fights or always a puppet on a string in riding slower as your enemy... Sry, it has to be sad, pro!

**Comment by bleifuss22** [comment]
Today, I played elves T2 AND AGAIN my very best Lotd-mount is slower than every other player.
And yes, I play 32-bit client. This a worse malfunction... Plz, help!
