### ISSUE TITLE
T1 Talabec Dam Powder Keg 

### ISSUE THREAD

**Issue by OneTrueKing-TouchPad** [WarEmu/WarBugs#20347]
Hey, so in TalaBec Dam SC in Tier 1 you can only pick up the powder Keg one time for either side. once that has been placed, you cant pick up another one at all.  so everyone is just left fighting in the middle for the next 10-12 min.

**Expected behavior and actual behavior:**
the Powder keg is meant to be able to be picked up multiple times through out the SC duration, regardless to someone dying with it or it being placed on location and respawns after it detonates 

**Steps to reproduce the problem:**

if you go into Talabec Dam Sc. in tier 1 it will not take you long to see what is happening

**Testing Screenshots/Videos/Evidences (always needed):**

![tala Dam ](https://user-images.githubusercontent.com/111500608/185477146-c4d8c407-3855-404c-b0c5-1f90aea26fd9.png)

**Comment by OneTrueKing-TouchPad** [comment]
![Tala Dam 2 ](https://user-images.githubusercontent.com/111500608/185477209-449a36b8-e5f0-4b55-8982-9746b6c9220d.png)
![Tala Dam 3](https://user-images.githubusercontent.com/111500608/185477274-827ffbcb-1162-4bdc-a43c-83070760a736.png)

**Comment by MaxHayman** [comment]
Thanks. I am looking into it.

**Comment by OneTrueKing-TouchPad** [comment]
You're welcome Max, Anything else you need just ask,

**Comment by lilimx** [comment]
fixed with patch [10/09/2022]
