### ISSUE TITLE
GromGil crossing- Bo's dont count towards Event

### ISSUE THREAD

**Issue by OneTrueKing-TouchPad** [WarEmu/WarBugs#20354]
Gromgil crossing Sc event isnt working when capturing Bo's 

**Expected behavior and actual behavior:**

Should be adding towards the event 

**Steps to reproduce the problem:**

Join me in Sc event 

**Testing Screenshots/Videos/Evidences (always needed):**

![GRomGil](https://user-images.githubusercontent.com/111500608/185599950-d89ceb94-3163-47f2-a4f6-faa2911bfd01.png)

**Comment by OneTrueKing-TouchPad** [comment]
Situation no change, still the exact same result. capping BO's isnt working as part of the event tracker.

**Comment by OneTrueKing-TouchPad** [comment]
![Gromgill xing 2 ](https://user-images.githubusercontent.com/111500608/185697747-f485a599-ac8b-40aa-ba18-df43b0000915.png)

**Comment by MaxHayman** [comment]
Should be fixed
