### ISSUE TITLE
Khaine's Bounty

### ISSUE THREAD

**Issue by Mortkin** [WarEmu/WarBugs#2035]
Tatic is broken, tatic is procing shield with critical HoT's. ( it should only proc with direct critical heal).

**Comment by Evildoor** [comment]
#1882 is about WP's similar tactic, and it has fix pending. I assume that @ozarmidrashim fixed DoK's tactic as well, but if i'm wrong then this ticket should be reopened after the hotfix is implemented.

**Comment by Mortkin** [comment]
Tatic still procing with HoT's.
