### ISSUE TITLE
Cant equip tactic

### ISSUE THREAD

**Issue by mrandregoe** [WarEmu/WarBugs#20351]
I am unable to equip the tactic Greave of Sigmar just say error message in chat when trying to equip it and it is RED.
have tried logging and reloading UI with no change.

![Screenshot (77)](https://user-images.githubusercontent.com/53059058/185502239-b2d152ca-93d9-48c3-862e-b6aec149db2a.png)

**Comment by xpander69** [comment]
Are you de-bolstered? this tactic requires lvl17 afaik

**Comment by Rydiak** [comment]
Xpander69 is correct.  It is a level 17 tactic, and at level 16 you cannot equip it.

**Comment by xpander69** [comment]
Closing. feel free to add comment or request re-open if you feel theres still a bug with it
