### ISSUE TITLE
Removed from guild after downtime

### ISSUE THREAD

**Issue by cinnamae** [WarEmu/WarBugs#20355]
My character (Cin) and our guild's GM (Quests) are no longer in our guild when we log in after the downtime. We are having to continually get invites back from other guild members. The GM is being passed to another member each night. Our character pages are also somewhat bugged on the killboard on the website.

**Comment by S193off** [comment]
o/
I've the same problem.
3 or 4 days in a row, it seems i've been fired by the game from guilds where I was.
I was to Juggernauts and after now i'm to GIGN and each days I need to ask an invitation ..

**Comment by MaxHayman** [comment]
Which guild?

**Comment by lanfeust21** [comment]
same ticket as https://github.com/WarEmu/WarBugs/issues/20295
still very active for lots of new players

**Comment by MaxHayman** [comment]
I have found the issue. I will need to do some database fixing on the next patch for this. Sorry for any inconvenience.

**Comment by lilimx** [comment]
fixed with patch [10/09/2022]
