### ISSUE TITLE
Mount always more slow than any other players #20341 AGAIN OPENED

### ISSUE THREAD

**Issue by bleifuss22** [WarEmu/WarBugs#20356]
**Expected behavior and actual behavior:**
Today i played T2 elves AND AGAIN my Lotd-first-class-mount and my dwarf copters are more slow than every other players mount.
And yes, I am playing as you advised, the 32-bit client.

The change of the client from 64 to 32-bit doesnt help anymore, at next day...

The very unsatisfying thing, i got killed by any following destro on mounts, because I am slower, than every other mount!
HELP!

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Zomega-WAR** [comment]
Were you slower than other order players on the same mount as you?

**Comment by bleifuss22** [comment]
Yes, the speed of copter AND mount from ".getstats" is both speed 159.

On Saturday i tested efective speed a lot in elves T4 DW and in elves T2 SL.
-At elves T4 the speed is equal to an AM mount. OK
-At elves T2 at riding through passage northbound, a dwarf copter next to me is more fast than my Lotd-mount AND my copter, too.
Other is driving an 38+ copter, too

Not knowing if speed depends on Tx areas, but its obvious, I lost speed against the other dwarf 38+ copter.
On the way of whole passage it looks like end of passage, the dwarf next to me is about 10-15 feet in front of me.

Later on saturday in Lotd-scenario my speed ist equal to other 38+ mounts of both fractions.
At least, the T2 diffference is still there.

**Comment by lilimx** [comment]
Hey,

im closing this ticket now. You have already an open ticket with the same issue.
I will add you ticket there.

**Comment by lilimx** [comment]
related to #20343
