### ISSUE TITLE
no warcrest in my 9 bag, a plan to recover ?

### ISSUE THREAD

**Issue by rich-france** [WarEmu/WarBugs#20361]
hello,
i have 9 bags (1gold + 1purple + 3 blue + 2 green + 2white) without warcrest inside.
I know the pb is resolved since a few days.
but, is there something planned for us to recover my 9bag's warcrest ?

![wc](https://user-images.githubusercontent.com/111050039/185751865-47fa863e-9161-47f7-8531-ac7ef77ee661.JPG)

Thanks all for your amazing job.

**Comment by xpander69** [comment]
the bags contents are generated at the time of recieving them.
no refunds planned
