### ISSUE TITLE
Blut Quest  bei Chaos geht nicht 

### ISSUE THREAD

**Issue by Smaugx3** [WarEmu/WarBugs#20369]
Die Quest Blut beim Chaos kann nicht Abgeschlossen werden da die 5 Speerträger die man töten soll nicht in die Quest zählen, egal wie viele man tötet !

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**
mit jeder klasse vom chaos bei der quest 

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

bitte eröffne erneut ein ticket und in Englisch.
Ein Bild zu dem Problem wäre auch net schlecht.
