### ISSUE TITLE
Giveaway mount instantly decayed

### ISSUE THREAD

**Issue by Focusthehealer** [WarEmu/WarBugs#20366]
Good evening, I tried to retrieve the giveaway mount I won by watching RealmWatch's live on twitch 3 weeks ago, but for some reason, it instantly decayed. The mail was sent 4hours prior to my attempt to redeem it.

Toon: Focusthetank
Mount: (Not Flying) Pig
![bugg](https://user-images.githubusercontent.com/109742965/185819909-5180f521-058c-4d09-b25f-94f373b22d0c.png)

**Comment by lilimx** [comment]
Hey,

I've sent Max an reminder.

**Comment by MaxHayman** [comment]
Delivery Resent

**Comment by Focusthehealer** [comment]
Good evening, a second attempt was made to send me the mount (Not Flying Pig), but it is still instantly decaying.

![pigggg](https://user-images.githubusercontent.com/109742965/187006272-a815a7bd-8d6f-45bf-a5a2-7c4e1ab7dd91.png)

**Comment by lilimx** [comment]
@Focusthehealer 

Hey,
just an update for me...did you get a third mount or so?

**Comment by Focusthehealer** [comment]
@lilimx 

Good afternoon, 
there wasn't a third attempt at sending me the giveaway mount.

**Comment by lilimx** [comment]
@Focusthehealer 

Hey, 
Thx for your response. I will poke Max.
