### ISSUE TITLE
Destruction Willpower bug

### ISSUE THREAD

**Issue by qaswed0** [WarEmu/WarBugs#20362]
**Expected behavior and actual behavior:**

My guess is that bw fuel to the fire tactic puts willpower down before logging off.

**Steps to reproduce the problem:**

In fact, if you get a willpower bug, your willpower is different on the stat window and getstats, and the amount of healing is also reduced.

**Testing Screenshots/Videos/Evidences (always needed):**

![11](https://user-images.githubusercontent.com/71438520/185779483-926a4e0c-bf7a-4feb-99cc-aa5216aa97d6.jpg)
![2222](https://user-images.githubusercontent.com/71438520/185779176-f227bc46-4c6e-4f5a-8161-d12464886d9b.jpg)
![333](https://user-images.githubusercontent.com/71438520/185779179-03f7ae75-e231-4507-bb40-532789b2a2ec.jpg)

**Comment by Zomega-WAR** [comment]
https://github.com/WarEmu/WarBugs/issues/18534

**Comment by xpander69** [comment]
Yeah duplicate of https://github.com/WarEmu/WarBugs/issues/18534
i will leave it open for now though as its been a problem for quite a while and maybe needs more attention

**Comment by lilimx** [comment]
Hey,

sorry to close this one. We have a different way to make issues popular to the devs.
