### ISSUE TITLE
furrious choppin

### ISSUE THREAD

**Issue by normanis** [WarEmu/WarBugs#20370]
hi furrious choppin hits me when i hit someone else. its shoudnt hit u .
![furious choppin](https://user-images.githubusercontent.com/23311386/186189045-029abdd8-4fa3-4a28-b678-65b02725762b.png)

**Comment by lilimx** [comment]
related to #20289

**Comment by CrimsonFenris** [comment]
Negative numbers mean it's a lifetap healing you, as it should be.
