### ISSUE TITLE
Dissolving Mist and unable to mount

### ISSUE THREAD

**Issue by epobleepo** [WarEmu/WarBugs#2037]
Seems when you have dissolving mist up, whenever you try to mount up it will instantly dismount you until the cloud expires.

**Comment by Evildoor** [comment]
The same happens with simple Magus DoTs (and maybe non-Magus DoTs too). I can't say if it depends on some of them in particular, just that a situation like "apply all your DoTs to enemies - get killed - respawn - mount - get dismounted" is very common when i play Magus.

**Comment by ozarmidrashim** [comment]
It's because the mounts are configured to break when you apply direct damage because of the auto attack. Changed this to block the auto attack when mounted instead.
