### ISSUE TITLE
Quest Bug: A Prod in the Right Direction

### ISSUE THREAD

**Issue by Kostoglod** [WarEmu/WarBugs#20371]
Good day. Death Peak zone, quest A Prod in the Right Direction. Its a questchain. The dwarf at Bristle Cavern gives this quest. Need to kill 10 trolls, location on the map is empty, no PQ, no mobs at all.

**Comment by Kostoglod** [comment]
![unknown](https://user-images.githubusercontent.com/111536343/186232299-43c8d072-7668-4da7-b79b-1d0d75200c38.png)
![unknown](https://user-images.githubusercontent.com/111536343/186232529-15d0b35b-bc96-4c96-9d76-5b274f56b4a1.png)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
This issue is already known, so I will add it to the related one.

**Comment by lilimx** [comment]
dublicate #15156
