### ISSUE TITLE
search guild problem

### ISSUE THREAD

**Issue by Zeufox** [WarEmu/WarBugs#20385]
if you don't have a guild , you can't search guild 
i test on my 3 class , all not work

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
Could you add a picture of the window with that issue?

**Comment by D4W0lf** [comment]
It's not new
![Capture d’écran_2022-09-01_22-23-53](https://user-images.githubusercontent.com/16599525/188005588-81dc3a22-c6a7-4c5b-8726-7b1786f62c78.png)

**Comment by lilimx** [comment]
Ah, thank you for your pic.
This issue was already reported here #19029
