### ISSUE TITLE
Auction house bugged (can not open auction house)

### ISSUE THREAD

**Issue by kam19080** [WarEmu/WarBugs#20381]
I cannot open an auction house after clicking the NPC...
tried /rel, relog.....

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by xpander69** [comment]
No additional information? where was the npc you interacted with?
Do you use any addons that might interfere with it, like Shinies or similar?
Does that bug happen on one char or multiple (if you have more than 1 char to try)

**Comment by kam19080** [comment]
maybe addons interfere, 
I disabled the Shinies addon and the problem has still appeared, Do you have the list of addons that may interfere with this issue?
I only tried 2 of my chars in the same account that has this same problem.

**Comment by xpander69** [comment]
Try cleaning the addon profiles first:
`~/user/settings/Martyrs Square/charactername`
Make a backup and/or remove to somewhere else and then try the game. If its still broken then probably something wrong with the game files.

**Comment by kam19080** [comment]
I tried cleaning the addon profile and disabling all addons, but the problem is still happening.
Should I del the game and reinstall the whole game?

**Comment by xpander69** [comment]
Can you post a screenshot of your RoR folder with the files and filesizes shown. Might be something is corrupted then or similar. Where did you try to access the Auction house? did you try multiple NPCs or just maybe 1 is bugged somewhere?

**Comment by xpander69** [comment]
I meant screenshot like this to see if your files are all correct size:
https://cdn.discordapp.com/attachments/329318147310223370/1009891596323520552/unknown.png

**Comment by xpander69** [comment]
Ahh, ok. Then i guess some of the files were corrupted somehow. Glad you got it working, Enjoy! Closing
