### ISSUE TITLE
Inventory window is broken and unusable

### ISSUE THREAD

**Issue by GarthMordan** [WarEmu/WarBugs#20380]
![Cinthia_000](https://user-images.githubusercontent.com/112525910/187567665-b0a46125-8a6b-4083-b729-f7259ba4c79b.jpg)

I have restarted the client and launcher, i have run the repair tool. I have cleared the cache and relaunched, and i have checked another character and his inventory works fine. Only this character is broken.

**Comment by GarthMordan** [comment]
I have also tried with listview ticked as well as unticked, And after all the restarts this is the window i now have.

![Cinthia_001](https://user-images.githubusercontent.com/112525910/187567890-88c9e1a8-fb7e-4588-8fc2-8a19f49a2d1f.jpg)

**Comment by xpander69** [comment]
Can you post a picture of the files inside the RoR folder, with the filesizes shown. It looks like interface.myp might be corrupted or similar.

**Comment by lilimx** [comment]
Fixed via Discord
