### ISSUE TITLE
Is this normal and not a bug for SM Plan B's rotation that stuck at perfect dance and can not use perfect dance skills?

### ISSUE THREAD

**Issue by kam19080** [WarEmu/WarBugs#20383]
Always stuck for Plan B at perfect dance and can not use perfect dance skills at the rotation.
Is this normal for Plan B outdated or it is a bug?

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,
thank you for your ticket.
We are not responsible for issues that are caused by addons. If you have further questions about addon issues, please join the RoR discord.
