### ISSUE TITLE
[Mail] Can't open mails

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#20387]
I have a bunch of mails in my auction-tab that can't be opened/deleted. I tried relogging several times. 
Also the "old" mails have been opened three or four days ago and should have been decayed/deleted by now. (Charname: Loarelle AM)
![Loarelle_023](https://user-images.githubusercontent.com/40274248/188156007-e2548fc1-d44d-48b0-9abe-5c40740d966b.jpg)

// Lilim edit: added the second half here: #20402

**Comment by MaxHayman** [comment]
@lilimx Can you split the second half into a different ticket please

**Comment by MaxHayman** [comment]
[Scophis](https://github.com/Scophis) can you confirm this is still happening.

You should only have 1 RvR reward mail and 3 Auction Money

**Comment by Scophis** [comment]
Just logged in. Atm it seems to work properly. i will leave some opened mails in my mailbox, to see if they decay.

**Comment by Scophis** [comment]
The false mail notification on my sham is also gone.

**Comment by lilimx** [comment]
fixed with patch [10/09/2022]
