### ISSUE TITLE
New ranked season didn't start

### ISSUE THREAD

**Issue by Aaasmund** [WarEmu/WarBugs#20384]
**Expected behavior and actual behavior:**
According to the ranked window, the new season was scheduled to begin on August 29.

**Testing Screenshots/Videos/Evidences (always needed):**
![2022-08-30_20-37-46](https://user-images.githubusercontent.com/107465980/187846960-bf1235a3-19cc-4c5f-9921-8134504836cb.png)

**Comment by Haojun-Phalanx** [comment]
:pepecross:

**Comment by lilimx** [comment]
Hey,

so I asked Dalen. And he set the date to the 29th August 2023 (that's why it is a Tuesday not a Monday like in 2022). The reason is for the upcoming changes, that's why he set date to next year.
