### ISSUE TITLE
DarkFlame Scepter

### ISSUE THREAD

**Issue by KingEliphas** [WarEmu/WarBugs#20393]
Can't find the "DarkFla
![Malxaza_000](https://user-images.githubusercontent.com/85014828/188325675-6a374fbf-88cb-468e-9fff-8ee165b24850.jpg)
me Scepter". Location: Ostland. Chaos Ch 7.  Quest name: CHOSEN.  Quest location: "Ragash's Last Stand" PQ.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
This issue was already reported here #20314
