### ISSUE TITLE
QQer addon can't blacklist "discordant skirmish" PUG SC

### ISSUE THREAD

**Issue by deadkoo** [WarEmu/WarBugs#20392]
Check

**Expected behavior and actual behavior:**

You should be able to blacklist any SC on the QQer addon. You can't Blacklist the new PUG SC Discordant Skirmish.

**Steps to reproduce the problem:**

Try to blacklist the new SC.

**Testing Screenshots/Videos/Evidences (always needed):**

![Screenshot (11)](https://user-images.githubusercontent.com/18690941/188298881-33bc8826-5d7c-439a-83f2-cfb616d8ff0a.png)

I think it's because the SC isn't tied to any of the tiers, so it's not on the actual listing. But I know nothing.

**Comment by xpander69** [comment]
You have to contact the addon dev for that or try to modify the addon yourself. External addons are not part of RoR.
