### ISSUE TITLE
Magus Flamer,Blue Horror, Pink Horror

### ISSUE THREAD

**Issue by Demoriel** [WarEmu/WarBugs#20390]
<
Summoned Flamer, Pink Horror and Blue Horror problem. Once summoned, if they take ANY damage they disappear. Never had this problem till this week. Makes using a Magus relying on pet damage and buffs impossible. 
-->

**Expected behavior and actual behavior:**
Summoned pets shouldn't die instantly from minimal damage. Not correct behavior

**Steps to reproduce the problem:**
Summon a pet near combat. if it takes any damage it dies instantly, requiring a re-summon.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Wachlarz** [comment]
Work fine right now
