### ISSUE TITLE
Fighting fire with fire quest

### ISSUE THREAD

**Issue by pthiel168** [WarEmu/WarBugs#20396]
Fighting fire with fire quest NPC Hallbjorn Frent the quest giver at Chaos Chapter 12 does not have the quest and is not clickable.

It is expected that Hallbjorn Frent gives the Fighting Fire with fire quest.

Go to Chaos Chapter 12 and attempt to click on Hallbjorn Frent to receive the quest.

![Screenshot 2022-09-06 110310](https://user-images.githubusercontent.com/8930990/188669962-36e0a8f1-5076-400f-8b9d-149f3ca613bd.png)

**Comment by Rubyeclipse-war** [comment]
I'm able to see and accept this quest from Hallbjorn Frent. 

![image](https://user-images.githubusercontent.com/60584990/189397145-f13556dd-783f-4af6-8c9b-4ba5b3697731.png)

@pthiel168 , do you mean that the quest cannot be turned in once completed? 

Additionally, what was your character level when taking this screenshot? (Is it possible your level was too low to accept it?)

**Comment by pthiel168** [comment]
I was unable to see the quest at the quest giver. No quests were available to be taken.



I did not think about the level. which is 25, because I was able to take other Stalker Quests.



Thanks













---- On Fri, 09 Sep 2022 12:26:39 -0400 Rubyeclipse-war ***@***.***> wrote ---





I'm able to see and accept this quest from Hallbjorn Frent.

https://user-images.githubusercontent.com/60584990/189397145-f13556dd-783f-4af6-8c9b-4ba5b3697731.png

https://github.com/pthiel168 , do you mean that the quest cannot be turned in once completed?

Additionally, what was your character level when taking this screenshot? (Is it possible your level was too low to accept it?)

**Comment by ekalime** [comment]
@pthiel168 minimum level is 26 :)

**Comment by pthiel168** [comment]
Thanks and sorry to waste your time











---- On Fri, 09 Sep 2022 13:34:06 -0400 ekalime ***@***.***> wrote ---





https://github.com/pthiel168 minimum level is 26 :)

**Comment by MaxHayman** [comment]
Closing this as it seems to be resolved. Please reopen if that is not the case.
