### ISSUE TITLE
Bug with Quest: Lob it Good! - CTD crash to desktop loop

### ISSUE THREAD

**Issue by SkuzBukit** [WarEmu/WarBugs#20397]
When attempting this quest in the Greenskin Starter area once you land at the stunty area, the game will crash to desktop. Logging back in that character will immediately crash back to desktop rendering that character no longer playable.

From: Dregrot 36250,50150 Name: Lob it Good! (part 2) Description: Using any one of the Rock Lobbers on Lobber Hill, lob yourself up onto Stunty Mountain, and bash in a few stunty heads. Report to Skarzag at Big 'Un's Mound when your'e done.

**Comment by MaxHayman** [comment]
https://www.youtube.com/watch?v=zJbmZErQAJ0

Seems to work fine for me. Have you tried repairing your client? Also what is your character name.

@lilimx have you seen this before?

**Comment by lilimx** [comment]
Hey,

Is this your first time in RoR or a fresh Install? It sounds like broken files to me. Would recommend to join the RoR discord so we can check that. 
The ticket will stay open until I know more.

**Comment by SkuzBukit** [comment]
I have tried a few times including with a fresh install & new characters, same thing happened every time.

**Comment by SkuzBukit** [comment]
So I think the bug is sound-related, every time the game crashed it was after a loop of some hammer hiyying something noise cycles on repeat. The game no longer crashes to dektop every time, what I changed was making the ingame resolution match my desktop's.

**Comment by lilimx** [comment]
Hey,

thank means that your audio.myp is broken.
audio.myp https://mega.nz/file/wa412QyA#MbwQ7X8M_bgUTkG5YLBRyziDVNgXHCXZM0nyrVbAmuU

Additonal it could be still an install issue.

**Comment by SkuzBukit** [comment]
Thanks for the link, will try that, already re-installed my sound card drivers to see if that helps.

**Comment by lilimx** [comment]
If it doesn't help, I really recommend to join the RoR Discord :D

**Comment by SkuzBukit** [comment]
The new Drivers didn't change the problem with sound but the new Audio.myp sems to have fixed the problem, thank you for the help.

**Comment by lilimx** [comment]
Hey,

nice! Im closing this ticket now.
