### ISSUE TITLE
Imperial Hunting Hound doesn't summon

### ISSUE THREAD

**Issue by Oxo888** [WarEmu/WarBugs#20395]
Imperial Hunting Hound doesn't summon

click in action bar or rclick in back pack to summon - get message 'this item cannot be used yet'

![hound not summon](https://user-images.githubusercontent.com/104646624/188445908-69761123-a2eb-4dc1-9598-44b5948c6db4.PNG)

**Comment by MaxHayman** [comment]
Please provide a full screenshot and details such as character name and location

**Comment by Oxo888** [comment]
full ss as requested 
![Oxxo_002](https://user-images.githubusercontent.com/104646624/188806082-acdb0560-bf24-4592-8358-38477c4e7734.jpg)

**Comment by Oxo888** [comment]
too is Oxxo , location is Altdorf main Bank, Lord's Row

**Comment by Oxo888** [comment]
seems the bug is not unique to the Hunting Hound - Horn of the vale wolf gives the same result
![Bisto_038](https://user-images.githubusercontent.com/104646624/189408007-39d11386-0e1e-4df8-a194-b1bf120bd4dd.jpg)

**Comment by Rubyeclipse-war** [comment]
This issue was figured out and Max was kind enough to get a fix in for us.

Both Order and Destruction characters should be able to summon their _very good boy_ Hounds when the next patch goes live! Thank you for flagging this, @Oxo888 .

**Comment by Oxo888** [comment]
Thankyou good people's of mystical codings :)

**Comment by lilimx** [comment]
Fixed with patch [14/09/2022]
