### ISSUE TITLE
Helm missing after todays 2 00 pm CST patch

### ISSUE THREAD

**Issue by dcephas** [WarEmu/WarBugs#2040]
Passwatch Steelhelm taken off character after the patch.  It is the empire t3 open rve influence reward

Aeendor White Lion

**Comment by Evildoor** [comment]
Item loss is a known bug which has no solution so far. Dev policy is "no refunds" for now, so the only thing you can do is hope that when server restarts items will return. If they don't - tough luck, but that's how it stands.
