### ISSUE TITLE
Snow/Pure White dye icon missing and is bind on pickup

### ISSUE THREAD

**Issue by Maelachi** [WarEmu/WarBugs#20404]
**Expected behavior and actual behavior:**
Snow White dyes (rare dyes from some event long ago) have their inventory icon missing and I assume at the same time got turned to bind on pickup. They used to be tradeable before recent patch and they are not sold by renown dye vendor so I don't think there is any reason for them to be BoP. I stored them on one character and was about to send to another once I get sovereign/triump gear that is worth spending those dyes on.

**Steps to reproduce the problem:**
Gain Snow White dyes and look at them in the inventory.

**Testing Screenshots/Videos/Evidences (always needed):**

![kuva](https://user-images.githubusercontent.com/113184963/189351695-b4f8bdd1-7b38-46e5-8d1e-5e0f57646d49.png)

**Comment by TVBrowntown** [comment]
I recently got one of these items from the Vanity Is Its Own Reward quest chain.

**Comment by Majorzero2123** [comment]
Had same issue this night 
![image](https://user-images.githubusercontent.com/99697728/189470136-7a85b3c2-a69b-43f7-b43b-b43be8c2f4d9.png)

**Comment by Rubyeclipse-war** [comment]
One of the devs has fixed this, so you should see these icons working properly in a patch very soon.

The reason this is impacting a few different dyes is because they all share the new white dye icon. Thank you for posting and sharing these examples!

**Comment by lilimx** [comment]
fixed with patch [10/09/2022]

**Comment by lilimx** [comment]
Hey,

the fix didn't work.
Snow White Dye Icon is missing.
Same for Skull White
Order of the Griffon Light Tan Dye.

![image](https://user-images.githubusercontent.com/23266079/189490792-2d7e9e33-fc88-4646-aa7d-14d31e8d06ef.png)
![image](https://user-images.githubusercontent.com/23266079/189490800-cdfe2cce-0db5-465a-a469-84a0c96a6341.png)

**Comment by Rubyeclipse-war** [comment]
Max has been brought in to help fix on this one. (Thanks Max!) Should be _properly_ fixed now in next patch. 

If there are any further issues on this, just let us know!

**Comment by lilimx** [comment]
Fixed with patch [14/09/2022]
