### ISSUE TITLE
Kotbs ALL Auras Active

### ISSUE THREAD

**Issue by DarkMalus** [WarEmu/WarBugs#20401]
**Expected behavior and actual behavior:**Knight of the Blazing Sun should have 3 Auras active at most !
                                                                     But i have ALL Auras Active!

**Steps to reproduce the problem:**Active 3 Auras join scenario and after the scenario i could activate the other auras and it stays that way!

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

Thank you for your ticket.
This issue was already reported here #19072
