### ISSUE TITLE
cannot make a party public

### ISSUE THREAD

**Issue by tenedora21** [WarEmu/WarBugs#20400]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by tenedora21** [comment]
"make your party open" should allow party to be open and populate on list. Instead the check is disappearing and the party is not public

multiple people tried

I don't have a way to record it?

**Comment by lilimx** [comment]
Hey,

Thank you for your ticket.
This issue was already reported here #20349
