### ISSUE TITLE
Can't summon "Warlord's Fell Hound"

### ISSUE THREAD

**Issue by Templergun** [WarEmu/WarBugs#20405]
Hi,

back in the day you could get "Skaven Token" with these Token you can buy different stuff at the Guild Vendor.
The "Warlord's Fell Hound" does not work. (It can be bought but can't be summoned.)
The Fell Hound definitely worked a while ago because i used it on my Chosen.
I bought it today on my SH because i had some leftover tokens and i can't summon it. Checking on my Chosen i also can't summon it anymore. (Other Pets work fine)

Additionally:
- The "Bottomless Bowl of Custard"works. (Reward from Monolith jumping puzzle in IC)
- The Skaven Cloak works. (For Skaven Tokens)

Best Regards

**Comment by Oxo888** [comment]
i see this with order Hunting Hound, and now the Vale Wolf pet. I updated my post just now with additional ss.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket,
This issue was already reported here #20395
