### ISSUE TITLE
Mail Display showing unread mails from different character

### ISSUE THREAD

**Issue by lilimx** [WarEmu/WarBugs#20402]
related to #20387 

Checked on my shaman and was able to open mail there, but my mail-display is showing the unread mails from my Archmage (Charname: Iznogoud Sham)

![image](https://user-images.githubusercontent.com/23266079/188965935-f1c85d0b-b518-4498-854b-00460b616ad5.png)

**Comment by lilimx** [comment]
arg...ticket is a dublicate of #20350

**Comment by MaxHayman** [comment]
Thank you

**Comment by lilimx** [comment]
fixed with patch [10/09/2022]
