### ISSUE TITLE
City joining at gates

### ISSUE THREAD

**Issue by Symbelmyne** [WarEmu/WarBugs#20407]
When timer for city queue is up and you enter gate to queue, nothing happens for my last 5 cities 100% of times (destro side - solo Q)
You need to relog after scenarios been updated and then you can enter queue.

**Comment by Symbelmyne** [comment]
Update:
Queue bug exists when you are being ported out of IC to maw on queue countdown start. 
There is no queue bug if you leave IC through city postal to Maw before countdown starts.

**Comment by shaggy996** [comment]
have had the same thing happen

**Comment by lilimx** [comment]
fixed with patch 19/10/2022
