### ISSUE TITLE
Problems with game Post

### ISSUE THREAD

**Issue by lynx-LuchS** [WarEmu/WarBugs#20410]
**Expected behavior and actual behavior:**
Yesterday evening i was playing with my slayer Aheron and cultivate 2+ stacks of Crimson monkshood and ~3 stacks of Majestic goldweed. Before logging off I mail them to my another character Burya. I maled the second mail with green loot gear to my another character Malusha and after that went to sleep. Today i login to Burya and do not see the yesterday mail. Aheron do not get any rr and warcrests from yesterday RvR of Avelorn. Malusha got the green loot gear. I relog to every character at my account, but i had not thouse 2+ stacks of Crimson monkshood and ~3 stacks of Majestic goldweed.

**Steps to reproduce the problem:**

i tryed to make new mail to Burya from Aheron - it works. I have no idea why system lost 1 mail and get the other.

**Testing Screenshots/Videos/Evidences (always needed):**

![Aheron_257](https://user-images.githubusercontent.com/10521042/189832710-f9e81970-b593-46f2-ab0e-f5a422f63568.jpg)
![Burya_653](https://user-images.githubusercontent.com/10521042/189832789-a482d220-db12-4041-9f7c-0c7fa784cfa0.jpg)

**Comment by MaxHayman** [comment]
I see there was mail sent on Sun Sep 11 2022 20:27:48 GMT with subject "dfgagdfg"

Which contained
Crimson Monkshood x35
Majestic Goldweed x 25

I also see mail sent Mon Sep 12 2022 19:57:56 GMT with subject "dfasdf" but sent to "Buran". It sounds like this was sent to the wrong character.

**Comment by lynx-LuchS** [comment]
> but sent to "Buran". It sounds like this was sent to the wrong character.

Oh...  I confused the account with the name of the character in the game. Sorry. That means my mistake not game bug...

**Comment by lilimx** [comment]
Oh, so I will close this ticket.
If you have further questions, please join the RoR discord or leave a message here.

**Comment by lynx-LuchS** [comment]
i have no questions. thank u
