### ISSUE TITLE
Event Quest

### ISSUE THREAD

**Issue by Trickxxx** [WarEmu/WarBugs#20417]
Hello,

i've started the event quest Death on the Steppes and decided to go the pvp route in the quest..
i am at the point were i have to pick up a map at the Nordland bo.. i can find an click the map but i cant pick it up to get the counter for the quest, tried relogging and everything...
Im on my Sorc Trickxery, if it cant be fixed is there maybe a chance to completely reset the quest for my sorc so i can choose the pve route?

Greetings Trickx

**Comment by lilimx** [comment]
Hey,

you don't pick anything up...it should give you credits that you click it.

**Comment by lilimx** [comment]
So actually you should get this:
![image](https://user-images.githubusercontent.com/23266079/190717648-c2ee75a4-1f17-4515-84cf-9102122d9ff2.png)

**Comment by lilimx** [comment]
@Trickxxx 

Hey,
Maybe you can give us a short feedback about that.

**Comment by Trickxxx** [comment]
I found it thanks to the image you send me 😊 thanks a lot

lilimx ***@***.***> schrieb am Sa., 17. Sept. 2022, 10:33:

**Comment by lilimx** [comment]
Hey,

Nice, glad to hear. :)

- Case closed

**Comment by Trickxxx** [comment]
Yes, i found it thanks to the image you send me 😊 thanks a lot

lilimx ***@***.***> schrieb am Sa., 17. Sept. 2022, 12:11:
