### ISSUE TITLE
[Guild Standard] no bufs

### ISSUE THREAD

**Issue by Syzako** [WarEmu/WarBugs#20414]
**Expected behavior:**

![image](https://user-images.githubusercontent.com/39750677/190386466-7c87983f-9b58-4d66-ba30-a75e32a6191c.png)

**Actual behavior:**

![image](https://user-images.githubusercontent.com/39750677/190386778-9ff1e2ff-d3f0-4797-96fa-1a69cd7e2d45.png)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. Could you tell us what buffs/tactics these are?

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persists, please open a new ticket with proper evidences.
