### ISSUE TITLE
Spiked Squid

### ISSUE THREAD

**Issue by darkt1981** [WarEmu/WarBugs#20415]
**Expected behavior and actual behavior:**
When the pet is out it should give you +5% ranged crit it doesnt. When i do .getstats with or without the pet i do not get the +5 additionele ranged crit.

**Steps to reproduce the problem:**
Summon/desummon Spiked Squid

**Testing Screenshots/Videos/Evidences (always needed):**

![pet](https://user-images.githubusercontent.com/24462956/190526638-ed4b49d2-56f3-4a0f-a0a9-77fdd53cdcc3.png)

**Comment by Teefz** [comment]
Spikey grants 5+ CriticalHitRate to melee/range/magic and not only range. You can actually see it in your screenshot with spikey.
