### ISSUE TITLE
Wolves is Da Best: Not getting meat quest item

### ISSUE THREAD

**Issue by PixelMasterNZ** [WarEmu/WarBugs#20419]
**Expected behavior and actual behavior:**
Expected behaviour: kill 3x Ravenous Boar, get meat quest item to feed to wolves
Actual behaviour: kill 3x Ravenous Boar, get credit for killing them but no quest item to give to wolves for second part.

**Steps to reproduce the problem:**

Accept quest. kill 3x Ravenous Boar, get credit for killing them but no quest item to give to wolves for second part.

**Comment by lilimx** [comment]
Note for Database: Hm, was already fixed a few times in the past, please check history

**Comment by Rubyeclipse-war** [comment]
Hi there @PixelMasterNZ - just to check, it sounds like this item is currently set to drop rarely from the wolves, so you might have to kill many more than 3 to get them. Are you able to try this out and let me know if that gets you the items? Thank you!

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persists, please open a new ticket with proper evidences.
