### ISSUE TITLE
[AH] Searching for guild/ally-only on auctions leads to crash

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#20411]
When selecting the option "Alliance and Guild only" on the auction house the game starts to freeze up and I got disconnected shortly after.

![Loarelle_029](https://user-images.githubusercontent.com/40274248/189987162-f7201beb-7808-4eae-a4fd-f5fe4cf20563.jpg)
It might be possible that this also causes the server to partly crash, as I saw people complaining about server trouble just as I tried to recreate the bug. (Might be bad coincident).
![Loarelle_031](https://user-images.githubusercontent.com/40274248/189987625-e6f9c3af-24fe-4003-8d73-e845d7a6b70e.jpg)
Tested it 3 times around 21:00 Altdorf time, Char Loarelle.

**Comment by lilimx** [comment]
Hey,

can't reproduce it. I can use it without any crash.

**Comment by Scophis** [comment]
Managed to catch it on video.
https://www.youtube.com/watch?v=8L8bj39Et1o
I'm not sure how much other players are affected but my game doesn't like this AH-option^^
I checked some streamers and every time I tried the reproduce the bug , some got disconnected while being in Altdorf.

**Comment by lilimx** [comment]
Hey,

so it looks like it's a network issue.
