### ISSUE TITLE
[KotBS] More then 3 auras simultanly active

### ISSUE THREAD

**Issue by waerter** [WarEmu/WarBugs#20418]
Expected behavior and actual behavior:
Expected: Only 3 Auras active at the same time
Actual: I can run up to 5 Auras simultan at my Knight

Steps to reproduce the problem:
1. Activate 2 Auras 
2. fly to nordland/norsca (get the debolster)
3. activate the other auras (sometimes it is 1 additional aura possible sometimes 2) 

Testing Screenshots/Videos/Evidences (always needed):

![4 Auras Active](https://user-images.githubusercontent.com/62266826/190828220-0c7e47b7-184b-4222-a30d-c4cc17b2aa25.jpg)
![5 Auras in Fort](https://user-images.githubusercontent.com/62266826/190828264-bcb7843c-8ea5-41b4-a4d3-6e93df9999d8.jpg)
Here the Auras on me and one Groupmate.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
This issue was already reported here: #19072
