### ISSUE TITLE
Fightin' in da Water 

### ISSUE THREAD

**Issue by Txarlyman** [WarEmu/WarBugs#20416]
I got this quest from an NPC in Barak Varr warcamp from destruction, that sends me to the Public Quest near by "Bar Dawazbak" hadr PQ chapter 7 were i ahve to kill 2 dwarf canons. I see the canons on top of the wall there that are atakeable but they are part of the PQ, i killed 2 but it doesen't cout for the quest.

![imagen](https://user-images.githubusercontent.com/59922493/190614882-c3bd4c8a-77ac-4149-beea-faf89e871221.png)

**Comment by Rubyeclipse-war** [comment]
Thanks for letting us know! Spent some time on this one today, and it's now fixed. On the next update:

- Players should be able to properly get credit for this quest.
- This quest now also has "In progress" and "completion" custom text if you talk to the quest giver. (Previously, it just repeated the original text.) 

Please abandon then re-take this quest once the next patch arrives, and it should allow you to properly complete this. Happy Questing!

**Comment by lilimx** [comment]
Fixed with patch 01/10/2022
