### ISSUE TITLE
Cant click war wagon Stonetroll country. Death on the steppes east vs west event quest

### ISSUE THREAD

**Issue by mendi92** [WarEmu/WarBugs#20421]
Expected behavior: Click on the war wagon, complete quest objective 
Actual behavior: Cant click on War wagon

Can click on troll stone but no war wagon

**Steps to reproduce the problem:**
Join stonetroll country scenario with Death on the steppes east vs west event quest and try to click war wagon.

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/92628518/190848316-b5f6193b-3343-42b6-a3ee-4d5da191613e.png)

![image](https://user-images.githubusercontent.com/92628518/190848251-5de0df3e-1c07-449e-885e-7423d55a375f.png)

**Comment by wulfgen760** [comment]
I can confirm. Bugged the exact same way with me

**Comment by lilimx** [comment]
Hey,

thx. Max will take a look at it.

**Comment by JadeCobraz** [comment]
Same issue here, cant complete events quests if its impossible.

**Comment by JadeCobraz** [comment]
Can confirm this is now fixed and working as intended today. TY

**Comment by MaxHayman** [comment]
Thank you

**Comment by lilimx** [comment]
Hotfix 18/09/2022
