### ISSUE TITLE
Event quest 'East Meets West'

### ISSUE THREAD

**Issue by romcoll85** [WarEmu/WarBugs#20427]
Have a bug in this quest.

We must destroy the Grain Wagons  in the BG 'Stonetroll Crossing'

Its impossible to destroy the wagons, they are burning all the time !

I deleted my quest and redid the BG, same result. Other players beside me couldn't destroy wagons. The cars are burning all the time. Unable to complete the event quest

Cordialy   'Gobbond'

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
This issue was already reported here: #20421
