### ISSUE TITLE
Keep Lord is ignoring the Intruders

### ISSUE THREAD

**Issue by Romanuzo** [WarEmu/WarBugs#20428]
**Expected behavior and actual behavior:**

Hello.
Today a thing happened to me - i got killed while in alt-tab. I dont care about this death, but i dont think that this thing should work like that - i stayed in the Keep Lord model and he didnt aggro on a Whitch Elf that killed me, his adds did, but he just afk'd.

**Steps to reproduce the problem:**
I believe there is how it works right now - invisible line next to a lord room (maybe just inside), once you cross it - Lord is taunted and become hostile, BUT, if you cross this line somehow undetected (Incognito, Vanish, etc) - boss just can't see you until you hit him.

**Testing Screenshots/Videos/Evidences (always needed):**

![111](https://user-images.githubusercontent.com/42448411/190908498-9ec170cc-abb9-496b-9971-b166fe969918.jpg)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
This issue was already reported here: #17773
