### ISSUE TITLE
Yako's Blood-drive quest no reward 

### ISSUE THREAD

**Issue by glukadin** [WarEmu/WarBugs#20422]
**Expected behavior and actual behavior:**
There should be a rewards for this quest, some kind of buff item, but on complete you can't choose the item and when press "Complete" button  quest just ends without reward.
Happen to Zahharius today 17.09.2022 at approx ~10.00 server time. 

**Steps to reproduce the problem:**
Take quest Death on the Steppes - Yako's Blood-Drive, complete it.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hotfix 18/09/2022
