### ISSUE TITLE
Snow White dye bind on pickup

### ISSUE THREAD

**Issue by Maelachi** [WarEmu/WarBugs#20436]
**Expected behavior and actual behavior:**
Expected behavior: Snow White dye should be unbound and tradeable. According to Wiki it's supposed to be unbound (https://wiki.returnofreckoning.com/Vainglorious_Guide_(Order)#Vainglorious_Set:_Order_Guide): "PSA: The Snow White dye is unbound, so you can trade it or sell it." Also it was unbound before recent patch. It's also not part of any renown reward unlike say Black Samndi (rr100 reward).

Actual behavior: Snow White is bind on pickup.

**Steps to reproduce the problem:**
Get some Snow White dyes.

**Testing Screenshots/Videos/Evidences (always needed):**

![kuva](https://user-images.githubusercontent.com/113184963/191216668-bdc1666c-956c-4f0b-a116-9e777fb9cac3.png)

**Comment by lilimx** [comment]
Hey,

we will investigate if it's possible to fix that. Yeah, we set them to unbound, but , it still remains bound, because once bound - always bound.

**Comment by Maelachi** [comment]
Hei, 

Great, thank you!

**Comment by Rubyeclipse-war** [comment]
I spoke to the team on this, and it looks like this bug should now be all fixed. 

If you have some of the bound dyes, we don't have a way to make them unbound again (sorry!) but all future Snow White dyes obtained from quest lines like Vainglorious should be properly tradable. 

Closing ticket as this has been fixed, but let us know if you encounter any other issues with the dyes down the road. Thank you for reporting this!
