### ISSUE TITLE
Dolgan Cheese from event all heal the same amount of AP

### ISSUE THREAD

**Issue by Veretta** [WarEmu/WarBugs#20438]
![image](https://user-images.githubusercontent.com/73980348/191595557-84aab499-30ea-4eca-84fd-27f29c4b3feb.png)
![image](https://user-images.githubusercontent.com/73980348/191595582-94b44c76-fa7c-4970-b448-5db2fc8427df.png)
![image](https://user-images.githubusercontent.com/73980348/191595599-394d17dc-0cc2-4e10-9a76-4cd8a8532e4c.png)
![image](https://user-images.githubusercontent.com/73980348/191595627-110e3e03-4cd1-4d8a-ac8a-a4464ff14cfa.png)

**Comment by Veretta** [comment]
I haven't actually tested the values healed - so possibly a tooltip issue.

**Comment by ekalime** [comment]
My oversight, I fixed it and it'll be ready next patch. 
Should be :
Fresh - 66AP
Aged-Fresh - 100AP
Soft-Rind - 125AP
Hard - 183AP

**Comment by lilimx** [comment]
Fixed with patch 01/10/2022
