### ISSUE TITLE
Talisman containers missing from craft merchants

### ISSUE THREAD

**Issue by NSKaneda** [WarEmu/WarBugs#20439]
Talisman making containers lvl 50 - 150 are missing from camp and craft merchants, apothecary containers however are still available

-

**Steps to reproduce the problem:**

Go to any camp/craft merchant

-

**Testing Screenshots/Videos/Evidences (always needed):**

Talisman containers:

![Sorkratez_092](https://user-images.githubusercontent.com/22037960/191787162-85192d06-f48a-4873-b0d7-8dfa1cf800f1.jpg)

Apothecary containers:

![Sorkratez_093](https://user-images.githubusercontent.com/22037960/191787208-6de52bee-8995-48f8-bc90-d4740b8155b9.jpg)

Maybe not game breaking but definitely making life of new player unnecessary hard and enforcing joining a guild for one crafting profession while other remains unaffected.

**Comment by Rubyeclipse-war** [comment]
Hi - thanks for letting us know about this request! 

The current design of the game limits these to the Guild Vendors to encourage players to join a guild or level theirs up, but hearing feedback on the implementation is always good. I'll discuss this a bit with the team in the future to see what the feeling is on adjusting/improving the QoL with these. 

For now, as this is intended with the current design, I'll go ahead and close the ticket. If we do make any changes down the road, you'll see it in future patch notes.

Thank you! 
- Rubius
