### ISSUE TITLE
[Warrior Priest] Character screen Wraith's mantle appearance

### ISSUE THREAD

**Issue by D4W0lf** [WarEmu/WarBugs#20448]
Hej,
Didn't find if there is a ticket yet, but I've found that on the character screen the Wraith's mantle are colored in red, but they are colored grey in game.
I use it as appearance, and never used dye on it

**Expected behavior and actual behavior:**
The Shoulders are grey in game.

The shoulders ares red in the Character screen

**Steps to reproduce the problem:**
Use Wraith's mantle as appearance ingame and logout to see that they are Red in the Character screen

**Testing Screenshots/Videos/Evidences (always needed):**
![Capture d’écran_2022-09-27_11-38-45](https://user-images.githubusercontent.com/16599525/192493996-5de6cdc6-396d-4a02-9363-c298610e9d9d.png)
![Capture d’écran_2022-09-27_11-40-20](https://user-images.githubusercontent.com/16599525/192494015-bed5eaae-aa31-4356-a074-ecb7d0c2d9f6.png)

**Comment by Zomega-WAR** [comment]
https://github.com/WarEmu/WarBugs/issues/16005

**Comment by lilimx** [comment]
So it's related and added to it.

**Comment by Matteusnoob1** [comment]
How and where did you get these Shoulders, I am trying to find them but dont know how.

**Comment by D4W0lf** [comment]
> How and where did you get these Shoulders, I am trying to find them but dont know how.

High Elf Storyline - Open RvR - Tier 3.

Elite Influence.
