### ISSUE TITLE
Dungeon Quests dont Count and No Influence

### ISSUE THREAD

**Issue by Roidstaker** [WarEmu/WarBugs#20447]
Hi, wanted to Rush Last week with my Chosen trough GB/BBBE/BS, had 3+ times same issues with quests Not counting or not getting Influence. Yesterday was worst with BS, Not a single Boss counted for Quest or Influence but got the new Lockout, still could roll for Items. Could IT be that the 18h Timer is bugged for Quests/Influence, Not 18h and its 24+? Think had it Always when ive done it a bit later when Lockout finished.

**Comment by Roidstaker** [comment]
Ahh and had it some Times that Bosses just spammed their ultimate every GCD, played Maintank and when i looked at Combat Log U Just saw one or two ultimate  between every normal Attack.

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are still the opinion that the issue still persists, please open a new ticket with proper evidences.
