### ISSUE TITLE
Engi ruin vendor offers shoulders twice, once at wrong cost

### ISSUE THREAD

**Issue by TomSeasArt** [WarEmu/WarBugs#20442]
**Expected behavior and actual behavior:**
There should be only 1 shoulder item for sale
There are two (2) shoulder items for sale, one being the right price and the duplicate being the price of the chest piece.

**Steps to reproduce the problem:**

Simply talk to the vendor as an engineer

**Testing Screenshots/Videos/Evidences (always needed):**

![WAR-64_aaQGufyuQO](https://user-images.githubusercontent.com/81263202/192057025-ba7df725-1e07-4691-82a1-eaca9b740291.png)

**Comment by Rubyeclipse-war** [comment]
Thanks for letting us know!

I've looked into this and fixed it - the duplicate shoulders which had a higher price have been removed. You should see this fix go live with the next patch. Thank you again for the heads up!

**Comment by lilimx** [comment]
Fixed with patch 01/10/2022
