### ISSUE TITLE
Not able to receive second Sentinel Ring from CnT NPC

### ISSUE THREAD

**Issue by unflaggmyaccount2** [WarEmu/WarBugs#20457]
I have finished CnT arcs on my alt and took one ring  from Crypts NPC. When I logged him again after some time to play it, I noticed it is not possible to get second ring, from Tunnel NPC though it is possible to get weapons.

**Expected behavior:**

- Can get second Sentinel Ring from another NPC

**Actual behavior:**

- Not able to get second Sentinel Ring

**Steps to reproduce the problem:**

1. Finish CnT influence arc
2. Get one ring
3. Log off
4. Log in
5. Try getting another ring from different NPC

**Comments:**
I bet it is possible to get 2 rings.
UPD. I was able to get 2 Sentinel ring on my other alt.

**Notes:**
Looks to be an old issue. Might be expected behavior as well, but this is not articulated afaik. https://github.com/WarEmu/WarBugs/issues/15876

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/114803578/193401957-7f855f47-0fc9-49f0-981a-6482cc80634b.png)
![image](https://user-images.githubusercontent.com/114803578/193401943-37b5a1bf-0289-4cc1-97fa-0bb8c6134370.png)
![image](https://user-images.githubusercontent.com/114803578/193402108-3473671c-c0e2-4aec-a633-cba6b3e124c9.png)

**Comment by unflaggmyaccount2** [comment]
UPD. I was able to get second ring on my other alt, weeks after I finished CnT and got mine first ring.
![image](https://user-images.githubusercontent.com/114803578/193444518-f5a4cf65-3b8b-414d-8faf-8c5e6653e1e0.png)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket,
yepp, as you mentioned this issues was already reported so I add it to the related one.

**Comment by unflaggmyaccount2** [comment]
@lilimx do u by chance know know it works? I mean I was still able to get 2nd ring on one of my alts, after weeks if completing CnT
