### ISSUE TITLE
engineer turrets disappears once I start combat while attacking the magma crawlers

### ISSUE THREAD

**Issue by Magnafasul** [WarEmu/WarBugs#20450]
**Expected behavior and actual behavior:**
expected behaviour: turrets stay and attacks.
Actual behaviour: it disappears.

**Steps to reproduce the problem:**
go to thundermountain at 43k 8k circa (near the PQ to kill squiggs). plant a turret (tried all 3 and same behaviour). Attack the crawlers for the glands. 

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Magnafasul** [comment]
![Magnafasul_001](https://user-images.githubusercontent.com/114529264/192630195-5b27c8f7-1c95-4ccb-992c-fe1fc67ecd22.jpg)
![Magnafasul_002](https://user-images.githubusercontent.com/114529264/192630200-a1bb6d65-1718-4e94-afc1-1d3319200221.jpg)

**Comment by lilimx** [comment]
Hey,

Yeah that's a common issue for all engis and magus player in Thunder Mountain.

Will close and add the ticket to the related issue.

**Comment by lilimx** [comment]
Related to #18872
