### ISSUE TITLE
Shadow Warrior: Vengeance / Brutal Assault Bug

### ISSUE THREAD

**Issue by DonCarlos3850** [WarEmu/WarBugs#20453]
Expected behavior and actual behavior:
The Shadow Warrior skill Vengeance of Nagarythe should allow to use the Skill Brutal Assault without positional requirements.
This sometimes work, sometimes it does not. Maybe it is working only for a shorter period of time (like 5 sec not 10 sec as expected).
On the screenshot below you can see, that the Brutal Assault is rejected with the error message: Target must be facing away from you, while the buf still shows a duration of 3sec for the Vengeance of Nagarythe Buf.

Steps to reproduce the problem:
1 - Activate Vengeance of Nagarythe 
2 - Activate Swift Strikes (channels for 8sec)
3 - Activate Brutal Assault --> error message

![Greenifer_003](https://user-images.githubusercontent.com/16256656/192755539-2e3e922f-c0c5-4d70-b902-ad69ca8c4a47.jpg)

P.S:
I'm using the sequencer addon, therefore you will see the Brutal Assault skill not in the hotbars.

**Comment by DonCarlos3850** [comment]
After further investigation, i believe it to be only a visual bug. The Brutal Assault action appears in the combat log, despite the error message.

**Comment by lilimx** [comment]
Hey,

Sorry for the late response....I think it's a dublicate of this ticket: #12349
Please check the other ticket and poke if it's not the same issue.
