### ISSUE TITLE
Chaos CH 22, Normal PQ impossible progression

### ISSUE THREAD

**Issue by Shajarra** [WarEmu/WarBugs#20458]
Chaos CH 22, Normal PQ: Reiksguard Training Grounds Phase II: Insufficient Reiksguard Cannoneers mobs spawn to complete this phase. Counted only 4 total spawning, mobs do not respawn.

**Comment by lilimx** [comment]
Hey,

I checked the PQ and found more then 20 Reiksguard Cannoneers.
Please add more evidences.

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
