### ISSUE TITLE
I cant enter game as ONLY ONE of my characters

### ISSUE THREAD

**Issue by Grundim9** [WarEmu/WarBugs#20451]
After 1 year i came bact to play on RoR, i played some on my salayer and IB. When I tried to enter game as my Engi I notticed i have to change his name so I picked a new one and tried. Loading screen took wierdly long (like 15 sec or so) and it kicked me back to characters menu but without other chars and play button. After few secounds everything except buttons got black and in box i had only "Searching for battlers Searching for allies". We tried with Wargrimnir and Lilim to redownload game, change his location first from ostland to blighted and later Sullemunk tried to change it to nordland,  change name again, check settings folder for doubled folder of Skalagrim (final engineer name), tried to copy Ibs folder and change it name to Skalagrim and change in character settings Grundim to Skalagrim and same crap. We are clueless. Every other charaters of mine those with og names and those that names were changed works. Only Skalagrim Engineer is bugged (his previous nicks were Falstand and Khalagrim) 
![image](https://user-images.githubusercontent.com/114528878/192632865-669d7c1a-3f8b-453a-9b3b-dca19cbf13b9.png)

**Comment by TVBrowntown** [comment]
rename the user folder in your warhammer online to user_backup - it will populate new user data and you should be able to login. let me know if that works. likely is corrupt savedvariable data for one of your addons.

**Comment by Grundim9** [comment]
Made it and same crap still :/

**Comment by Grundim9** [comment]
![image](https://user-images.githubusercontent.com/114528878/192747806-52cb9982-edea-4353-a5cc-249c11c707dc.png)

**Comment by Grundim9** [comment]
![image](https://user-images.githubusercontent.com/114528878/192747866-e934616a-e121-4f4c-9baa-1e5915758c9a.png)

**Comment by Grundim9** [comment]
And my interface addons folder is empty

**Comment by TVBrowntown** [comment]
might wanna try deleting cache and hitting the cog button on the login launcher, then repairing? I'm out of ideas past this. but I had the same problem. I would login, it would fail to log me into that character, then I would click SERVERS, select the server and try to load the game. I would also type /rel during the load screen to reload the interface during the load screen. It's likely an addon that is causing this.. maybe. I haven't had the problem since. But I made some changes to my dxvk as well to stop using MSAA x16. Not sure if you have that - but could be that too.

**Comment by Grundim9** [comment]
I tried /rel during loading scrn after repairing and i had for a few secs black screen and whole my interface noormal i was dead and nothing happend later i tried again /stuck and /rel and back to situation from pictures above

**Comment by Grundim9** [comment]
But after that im back to starting point

**Comment by Grundim9** [comment]
I have completley no clue what to do that is fucked up tbh. Maybe he has some wierd items that was deleted from game and it makes trouble or sth just blind shoting tbh

**Comment by Grundim9** [comment]
Should I start lvling new one? XD

**Comment by lilimx** [comment]
Naaah

**Comment by MaxHayman** [comment]
Can you add me on discord MaxHayman#8344

**Comment by Grundim9** [comment]
Sure thing Mr. ^^

**Comment by Grundim9** [comment]
Done

**Comment by Grundim9** [comment]
Is there anything i can do to help you deal with my problem?

**Comment by lilimx** [comment]
Max and you are friends now? You can poke him via PM otherwise poke me again.

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket.
