### ISSUE TITLE
Instrument of Vengence quest

### ISSUE THREAD

**Issue by Blinkey77** [WarEmu/WarBugs#20468]
The instrument of vengeance quest in avelorn says to “read delianna’s map”. When I click on the map I do not receive credit. It doesn’t work. The quest is in dark elf chapter 12 in avelorn.

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
