### ISSUE TITLE
Lack of crests for zone flip

### ISSUE THREAD

**Issue by dreadstormer** [WarEmu/WarBugs#20467]
I was in KV for 12 hours fighting back and forth yesterday. I did multiple keep attacks (5 i think) and multiple keep defences (4) I logged on today and received 2 crests in the mail for 12 hours of fighting. This can't be right, I have received more crests for less than an hour of fighting. I didn't log on any other characters during this time and when I got lunch/dinner and had a shower etc i just afked in the WC

**Comment by CrimsonFenris** [comment]
Did you succeed in defending last keep (i.e getting a bag roll after door restored) ? Because this bag roll will wipe your contribution, you have to start over again if you want crests from zone lock.
