### ISSUE TITLE
character stucked in limbs while transferring

### ISSUE THREAD

**Issue by Proficula** [WarEmu/WarBugs#20460]
hello,
i can't connect my WL (Gascogne) after have been disconnected during transfert between CW and Avelorn.
Any help possible?
Thank you

**Comment by Proficula** [comment]
I would add that my WL is still in the WB list as WB leader. That's a bit strange!

**Comment by lilimx** [comment]
Hey,

If you haven't done that, please add your stucked characters here:
https://www.returnofreckoning.com/forum/viewtopic.php?t=46249
