### ISSUE TITLE
Arcane Teachings quest

### ISSUE THREAD

**Issue by Blinkey77** [WarEmu/WarBugs#20469]
Arcane Teachings quest in avelorn doesn’t do anything or give credit when the quest item in my bag of “Saphery ward map” is clicked. I’m standing in jade stand Pq as instructed too.
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

I just tested this and it looks like this quest chain works properly.
Did you try to redo the quest?

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
