### ISSUE TITLE
(KOTBS) Aura Bug! 

### ISSUE THREAD

**Issue by Loreblue** [WarEmu/WarBugs#20466]
I'm not sure exactly what's been causing it, though it seems like after I visit and change my masteries or my renown on my Knight that I then become unable to activate my auras. I am able to activate them once, but after I deactivate one of them and try to swap to another, it flashes about half a second of the aura swapping animation and then abruptly cuts off. This leads me to where I cannot change auras until I relog back onto that character.

I can't exactly take any screenshots of the issue as the interrupted animation is too fast for me to snip it and simply showing my buff bar isn't gonna do much good as there's no indicator of the issue there besides my lack of auras. But this has been going on for about a week or so and it's been quite the nuisance. PLEASE FIX!

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
This issue was already reported here: #18870
