### ISSUE TITLE
Gunbad middle quest Threat from Ard'ta'Feed not working

### ISSUE THREAD

**Issue by eerytraveler** [WarEmu/WarBugs#20462]
![image](https://user-images.githubusercontent.com/98583303/193498286-60c0554e-7bac-46bd-9a9d-155dcfbf1862.png)

Killed him twice in the last couple days and no credit on the kill quest. Glomp and Mixa worked just fine (2/3 on those).

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
This issue was already reported here: #20389
I will close this ticket and add it to the related one.
