### ISSUE TITLE
Stone claw keep 

### ISSUE THREAD

**Issue by Toldavf** [WarEmu/WarBugs#2046]
Currently order can use the terrain on the left of the keep as you face the main door to gain entry to the keep.

**Comment by DanaBloodkiss** [comment]
Can you take some screensots or explain it more detailed?

**Comment by Toldavf** [comment]
will sort out a video

**Comment by Toldavf** [comment]
https://www.youtube.com/watch?v=WMucuVh3PHE&feature=youtu.be

**Comment by DanaBloodkiss** [comment]
Fixed in next. Thanks for report.
