### ISSUE TITLE
[New RR80 Congratulations Quest] Potions from new quest doesn't stack with standard potions

### ISSUE THREAD

**Issue by nohh** [WarEmu/WarBugs#20479]
Potions from new quest doesn't stack with standard potions.
Standard instant heal potion ID=3000264
Quest instant heal potion ID=189770

Same situation with healing over time potion and AP potion.

**Comment by ekalime** [comment]
fixed

**Comment by lilimx** [comment]
fixed with patch [19/10/2022]

**Comment by nohh** [comment]
Can you review this moment again?
Or need new issue?

https://user-images.githubusercontent.com/19315739/201511157-8b20a67f-348b-4961-b387-c030ea8ceb86.mp4

**Comment by Rubyeclipse-war** [comment]
> Can you review this moment again? Or need new issue?

Is this for the RR60/70 quests? I saw they were giving the unstacking pots earlier today and fixed that, so it should work properly soon. If this is for RR80 quest still, please let us know.

**Comment by nohh** [comment]
Potions from 60/70/80 quests are the same, checked it (completed all quests) 5 minutes ago.
Quest potions do not combine with crafted potions in the bag.

**Comment by Rubyeclipse-war** [comment]
I fixed it all up. 👍 

On next server update: 

- Players who newly complete RR 60/70 quests will get potions that stack properly. 
- Players who already have the other potions will see them "decay" in 30 seconds, and they will turn into potions which stack properly at that time. 

Thanks for letting us know!
