### ISSUE TITLE
I slotted a talisman on my shoulder piece. they disappeared.

### ISSUE THREAD

**Issue by Magnafasul** [WarEmu/WarBugs#20474]
As per title.
I bought some talisman +7 thoughnes from auction house.
Slotted in the shoulder piece.
Fuse.
the window didnt disappear.
Clicked fuse a couple of times more.
nothing happened.
pressed esc.
![Stingus_002](https://user-images.githubusercontent.com/114529264/195318056-c01b8e9b-b814-4516-a91a-7cb1febe8c82.jpg)
![Stingus_004](https://user-images.githubusercontent.com/114529264/195318060-611b48af-8a75-4af3-9394-99a59510ba1c.jpg)

Shoulders gone.
attached ss. the second one is to show that I have other shoulders but they arent the one I lost.

**Comment by lilimx** [comment]
Hey,

they are still missing after you relog?

**Comment by Magnafasul** [comment]
ok I checked. I closed and reopened and they are no more missing. sorry for the bother!
