### ISSUE TITLE
Game Crashes in Scenarios when Bright Wizard use an Ability

### ISSUE THREAD

**Issue by wildwindblows** [WarEmu/WarBugs#20473]
Hello RoR Bugtracker Team,

Game is crashing when Bright Wizard using an ability in scenarios. I'm sure the reason must be an BW ability because game dont crash when order team dont have bw. MostIy game crashes when bw's hitting to me. I couldnt go RVR recently so I dont have any idea about it. How can I solve this issue?

Thanks in advice,
Bests.

**Comment by lilimx** [comment]
Hey,

hm, maybe a video setup thing or a broken file. Are you using and reshade stuff?
But all in all it's not a bug.
Would recommend to poke in our RoR discord in #technical-advice
