### ISSUE TITLE
RR80 quest "True Oathkeeper" rewards wrong potions (2x AP / no heal)

### ISSUE THREAD

**Issue by dbddhkpuka** [WarEmu/WarBugs#20477]
**Expected behavior and actual behavior:**
Completing the quest at the High King should reward three potions stacks (instant heal, AP, HoT) and 10 Liniment crates.
It actually rewards 40 AP + 10 AP + 40 HoT and is missing the instant heal pot stack.

**Steps to reproduce the problem:**
Complete the quest and select rewards.

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/21637631/195847096-2b5e113b-51df-4321-b5c1-05f0b36fa992.png)

**Comment by dbddhkpuka** [comment]
Well ignore that, looks like you need to choose 3 out of 4 rewards and I just didn't tick the heal potions. 
I just tried the same on Empire and could only select 3 rewards.

**Comment by Rubyeclipse-war** [comment]
Yes, your Faction Lead will let you pick 3 rewards out of the 4, so you'll have to decide which you prefer most!

Totals should be 50 AP, 50 HP, 40 HP over time, or 10 Lini crates (for 40 Linis total). They may stack in 40's, so if you see only 10, you might have some more already. Let us know if you do end up getting less than the amounts listed here!

**Comment by dbddhkpuka** [comment]
> Yes, your Faction Lead will let you pick 3 rewards out of the 4, so you'll have to decide which you prefer most!
> 
> Totals should be 50 AP, 50 HP, 40 HP over time, or 10 Lini crates (for 40 Linis total). They may stack in 40's, so if you see only 10, you might have some more already. Let us know if you do end up getting less than the amounts listed here!

That is correct, I first read it like one stack (40) each and clicked all of them one by one, but obviously didn't recognize the fourth pick was too much. The amounts were correct in both cases.
