### ISSUE TITLE
Gunbad quest for Endboss seemed to be bugged

### ISSUE THREAD

**Issue by Petrulla** [WarEmu/WarBugs#20475]
Hello 
my char Petrulion WhiteLion 40/40 Guild Gimle...
did my 7th run GB and still could not make the endboss quest count.
not sure what i did wrong
8th run seem to be the lucky number on this
best regards

**Comment by lilimx** [comment]
Hey,

You mean the quest? Additional we need a lot of more information. Most important are the lockout timers. Sometimes the combat log show some information aswell, like weird behaviour of the npc.

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
