### ISSUE TITLE
Blackguard Obliterator set wrong appearance

### ISSUE THREAD

**Issue by Hauclir** [WarEmu/WarBugs#2047]
![hauclir_114](https://cloud.githubusercontent.com/assets/7598530/11464524/87445e1e-96e4-11e5-9b69-faf772ad91c3.jpg)
This is how the gear set currently looks, the chest piece is wrong and the colors are wrong for the set.

This is how it suppose to look
http://www.arsenalofwar.com/armor/Destruction/Obliterator%20Dusk%20Warrior's%20Kit
![blackguard obliterator set](https://cloud.githubusercontent.com/assets/7598530/11464434/9fe38d38-96e3-11e5-9f5a-1a337ef8b604.jpg)

**Comment by genisaurus** [comment]
Should be fixed with next hotfix.
