### ISSUE TITLE
Uzkular Questline mob Insta despawns (KaK questline)

### ISSUE THREAD

**Issue by Majorzero2123** [WarEmu/WarBugs#20471]
https://streamable.com/rrdi8h
**Expected behavior and actual behavior:**
In the video, the mob that is supposed to spawn after interacting with the object despawns. This quest is in the middle/near the end of the questline (Karaz-a-Karak Questline)
![image](https://user-images.githubusercontent.com/99697728/194732753-bcd15cc7-dab3-4c0c-8eb7-29513872d4bc.png)

**Comment by ekalime** [comment]
fixed the timer for him to stay spawned. was set to 1 millisecond. now it is set to a few tens of thousands more milliseconds.

**Comment by Majorzero2123** [comment]
Fixed as of 10/14, Thank you :)
