### ISSUE TITLE
The "Specialty Mount Wrangler" NPC doesn't have any 30-day Guild Mount for Magi

### ISSUE THREAD

**Issue by Fontaami** [WarEmu/WarBugs#20478]
**Expected behavior and actual behavior:**

After completing a short questline as 80 renown magus, you will get a 30-day chaos mount voucher and should be able to exchange it for 30-days guild disc of your choice. However, there are zero discs to choose from.

**Steps to reproduce the problem:**

Be a 80 renown magus with completed questline named "Champion of Chaos", then visit a NPC in Stables in attempt to get your guild disc.

**Testing Screenshots/Videos/Evidences (always needed):**

![waremu](https://user-images.githubusercontent.com/42380765/195872810-dab6f130-e667-46e6-8b6a-8d3e923f9e20.jpg)

**Comment by Rubyeclipse-war** [comment]
Thank you for the report! Issue confirmed, I'm fixing it now. Will update this ticket as soon as the Fix is pending on dev.

**Comment by Rubyeclipse-war** [comment]
Bug has been fixed and is now working on the dev side! 

As soon as the next patch hits, you should properly see all the Guild Mounts for Magus appearing, like this: 

![image](https://user-images.githubusercontent.com/60584990/195880290-4d568dea-7851-444b-8cc5-11fbd1d8a4f9.png)

Appreciate the well-written report and thanks for your patience on this one!

**Comment by lilimx** [comment]
fixed with patch [19/10/2022]
