### ISSUE TITLE
LOTD Backs BOE-BOP

### ISSUE THREAD

**Issue by Endtimer** [WarEmu/WarBugs#20487]
I bought the LOTD Accessory-Backs for fashion with my chosen (Endtimer) and it came to my surprise that Drape back is flagged as Binds on Equip (BOE) while all the other Accessory Backs (i.e. Shawl, Shroud, Wrap, Veil) are Bound to Player (BOP). I also checked that this is not a "visual bug" because I could indeed trade the Drape Back but could not trade any of the other backs.
If this is meant to be this way I suppose it is fine, but I thought I should report it since I did not came across it in another issue. I did not check on the other accessories for the same issue.

Endtimer

![Wrap](https://user-images.githubusercontent.com/93056457/196049579-57da42d1-7b07-4c9a-92c3-5ae5048b8cbd.jpg)
![Drape](https://user-images.githubusercontent.com/93056457/196049581-a55d3b76-3019-4d1c-b43b-198445f75ebb.jpg)
![Shawl](https://user-images.githubusercontent.com/93056457/196049582-01856167-847c-478e-b03a-ed90204a2849.jpg)
![Shroud](https://user-images.githubusercontent.com/93056457/196049584-3d4839f1-f267-4be3-bbab-7e385b172bf7.jpg)
![Veil](https://user-images.githubusercontent.com/93056457/196049585-bf6721a6-bdd8-4bb6-b207-d4f4fa9831ac.jpg)

**Comment by Rubyeclipse-war** [comment]
@Endtimer Thank you very much for letting us know. Looks like it should indeed follow the bound-to-player status of other capes.

I've dug into this one and fixed it up on the back-end. Should be properly showing as Bound as of the next patch!

**Comment by lilimx** [comment]
fixed with patch [19/10/2022]
