### ISSUE TITLE
Event-Herald in Altdorf Warquarter only showing ranked event

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#20485]
Not sure if this intended, but the weekend warfront and the RvR week event do not show up on the herald in altdorf warquarter.
![Phoenizius_031](https://user-images.githubusercontent.com/40274248/196028235-13064862-1212-462d-8fb3-aeb23c897973.jpg)

**Comment by lilimx** [comment]
Hey,

Those are two different Herolds. 
And im pretty sure it's intended because he lives next to the other ranked Bros :D
Additional I've checked on the dev server and he has only Ranked Week stuff aswell.
