### ISSUE TITLE
A sticky situation quest

### ISSUE THREAD

**Issue by dvsshan** [WarEmu/WarBugs#2048]
Either can't hand in the quest or it has been handed in in not received xp or reward. The quest icon above Lena Scherer's stays yellow

**Comment by Evildoor** [comment]
#305

**Comment by dvsshan** [comment]
How do i search on the big tracher site to see if something had already been logged?


Sent from my SAMSUNG Galaxy S6 on the Telstra Mobile network-------- Original message --------From: Evildoor <notifications@github.com> Date: 30/11/2015  10:52 pm  (GMT+10:00) To: WarEmu/WarBugs <WarBugs@noreply.github.com> Cc: dvsshan <shannon.joel@hotmail.com> Subject: Re: [WarBugs] A sticky situation quest (#2048) 
Closed #2048.

**Comment by Evildoor** [comment]
You use the search function at the top of it.
