### ISSUE TITLE
War Report to Sari' Daroir in Saphery/Avelorn caused me to be dropped into water under map.

### ISSUE THREAD

**Issue by Veretta** [WarEmu/WarBugs#20484]
Please see video for details.

https://www.youtube.com/watch?v=NbBmjjccyCI

**Comment by Veretta** [comment]
![image](https://user-images.githubusercontent.com/73980348/196018474-68b9832e-48c5-4e35-bcf8-f2a684f9c15d.png)
Map Location

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. There is an upcoming fix pending. But they should check if they havn't missed your spot.

**Comment by Rubyeclipse-war** [comment]
Thank you for the ticket! As @lilimx mentioned, this should be fixed in the next patch along with all the other War Report issues at the moment. 

If it continues after the next update, please let us know. Until then, I'll mark this as Fix Pending.

**Comment by lilimx** [comment]
fixed with patch [19/10/2022]
