### ISSUE TITLE
[Guild-UI] Members-Overview not showing players

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#20481]
After log-in the overview shows (1/1) members are on, the roster also shows just your char.
![Loarelle_040](https://user-images.githubusercontent.com/40274248/195998500-f57ca346-8411-440e-ad73-04a465698b66.jpg)
After reloding the UI the correct number of members are shown and the roster is working, too.
![Loarelle_041](https://user-images.githubusercontent.com/40274248/195998503-a72d4a15-a1dc-4bc7-8160-91eea04ec18a.jpg)
PS: /g and /a are not affected

**Comment by xpander69** [comment]
Have you tried with default UI (without addons). Clean configs?
The guild list populates usually in 10-20 sec after you get into the game world

**Comment by Scophis** [comment]
Tested again today and the UI instantly shows the proper members after log-in. 
The only difference to yesterday is that the total members dropped to 399. *shrug*

(Guess this can be closed. I'll keep an eye on it, if it reoccurs with higher members count)

**Comment by xpander69** [comment]
Could be a bug with the amount of members in the guild. Do let us know if it occurs again.
