### ISSUE TITLE
Buff and Debuff timers not updating in Pure buffbar

### ISSUE THREAD

**Issue by bosli42** [WarEmu/WarBugs#20494]
Issue started roughly about 1-2 months back, not too long after I remade my UI from scratch with all newest addon versions. I think this is a universal problem for everyone using pure and I'm not sure if it's only in the pure buffbar or also on the basic UI player-buffbar, so I guess it's worth a ticket.

Any buff or debuff will show up on the pure buffbar (attached to pure player unit frame in my UI) when you receive it and vanish when you lose it, but the remaining timer will only update if you untarget and retarget yourself.

- buffhead works perfectly fine
- enemy UI works perfectly fine

I suspect that the server should send updates about timers but doesn't (anymore) therefore breaking the pure buffbar, but the above addons count the timer internally and don't check for server updates / unit frame info apart from new, ended or cleansed/shattered ones.

If some players that are versed well enough with the addons and can either confirm or bust this problem to be only-me that would be great.

**Comment by lilimx** [comment]
Hey,

but that's really an addon issue.
