### ISSUE TITLE
Server Rollback 9 a.m. Altdorf

### ISSUE THREAD

**Issue by unflaggmyaccount2** [WarEmu/WarBugs#20499]
Server rolls back every day approximately 9 a.m. Altdorf. Got disconnected and when back, I am rollbacked for few hours. Happened to me twice 20.10.22 and 21.10.22.

**Expected behavior:**
- After DC game progress remains

**Actual behavior:**
- After DC got game progress rollback

**Steps to reproduce the problem:**
- Play game Altdorf morning time
- U will get disconnected  around 9 A.M. and roll backed. 

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by tog89** [comment]
I am also ecperiancing rollback when I log into my  character, not on DC but on log out.  Will zone into old zone and progress lost on Epic Quest Nothing In Vain, Bag and Bank contents are reset.

**Comment by lilimx** [comment]
Fixed with Hotfix 22/10/2022
