### ISSUE TITLE
Witch Hunter Sanctified Bullet keeps healing even after being "fixxed"

### ISSUE THREAD

**Issue by Zogmar** [WarEmu/WarBugs#20496]
**Expected behavior and actual behavior:**
Blessed Bullets of Purity shall heal you if Sanctified Bullets tactic is equiped. Actual behavior: Tactic keeps healing without being in tactic set

**Steps to reproduce the problem:**
Now if you get in comabat with this tactic being equiped, u need to trigger it with any accusation spending ability (e.g "Trial by Pain"), then get out of combat remove/change tactic set, and try it again without Blessed Bullets of Purity    

**Testing Screenshots/Videos/Evidences (always needed):**

![Bullet_bug_1](https://user-images.githubusercontent.com/116203361/196777577-36d2e3cf-7cad-4ecb-b873-46603ff5157a.jpg)
![Bullet_bug_2](https://user-images.githubusercontent.com/116203361/196777621-37d2bc3e-1b15-45d3-b61a-06c1dacdaaf0.jpg)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket, but the issue is still open here: #20234
