### ISSUE TITLE
Didnt get RR80 Quest voucher in mail

### ISSUE THREAD

**Issue by Blakken12** [WarEmu/WarBugs#20490]
Hey there! 
I am RR81 and I recently logged in and I didn't receive the voucher in my mail
my Character name is Blakken.

Is there a way to get this voucher rather than getting it in mail?
or maybe a vendor I can go look at with the voucher?

![Blakken_011](https://user-images.githubusercontent.com/116116346/196532312-e5d5fd48-1249-4123-8a60-a8159ae35fe8.jpg)

just a picture to show that I'm RR81 and my Mailbox is empty.

Thanks for the help in advance =)

Kind regards 
Blakken Goldenhand

**Comment by Rubyeclipse-war** [comment]
Hi there @Blakken12 - yes, unless you just recently hit both RR80 and RR81 within the span of a few days, the Mail only goes out to RR80 players who dinged 80 after the latest patch.

For all existing RR80 and above players, please head to the Lyceum in The Inevitable City and speak to the Records Keeper. They'll have an item you can purchase for 1g. In case you need it, more info here: https://www.returnofreckoning.com/forum/viewtopic.php?t=49425

Hope this helps!
