### ISSUE TITLE
Twisted Tactics - Weekend Warfront - Tome entry

### ISSUE THREAD

**Issue by lilimx** [WarEmu/WarBugs#20501]
Wrong description for this task:

![image](https://user-images.githubusercontent.com/23266079/197228780-b1d54ebc-0d00-42bc-b1c3-72256d0b1019.png)

"at 8 enemy" but the counter says 6

**Comment by Rubyeclipse-war** [comment]
All fixed up by Eka. Thanks for letting us know!

P.S. _ANGRY CAPITAL LETTERS_

**Comment by lilimx** [comment]
THANK YOU!

**Comment by lilimx** [comment]
fixed with patch 26/10/2022
