### ISSUE TITLE
Caledor War Report 

### ISSUE THREAD

**Issue by Dottina** [WarEmu/WarBugs#20514]
We have Problem in Caledor. If Order Die or use war report to Caledor we come to DW to Pve.

High Elf Chapter 17

https://bilderupload.org/bild/2c6a50834-barbossar-000

**Comment by Rubyeclipse-war** [comment]
Thanks, I've confirmed this and was able to replicate. We're looking into it now.

**Comment by MaxHayman** [comment]
Fixed
