### ISSUE TITLE
Warrior Priest - Sigmar's Vision

### ISSUE THREAD

**Issue by ThePollie** [WarEmu/WarBugs#2051]
Ability, Path of Grace - Sigmar's Vision places a Blessing on the defensive target when an enemy is struck, increasing Parry chance by 10%. At the moment, the 'buff' is marked as a Damaging effect, not a Blessing. I have noticed it randomly vanishing during large-scale combat between warbands, and I'm concerned it may actually be getting cleansed by an ally because of it's hostile classification.

**Comment by ThePollie** [comment]
![winifred_010](https://cloud.githubusercontent.com/assets/15985954/11472458/b1ebf596-97a7-11e5-8b57-666f4f1b4542.jpg)

Attached screenshot of said effect.

**Comment by Evildoor** [comment]
Aha, it was wrong even on live, IIRC, so let's fix it. FYI, "Damaging" effects cannot be cleansed by allies, so it is broken in other way - enemies cannot cleanse it from you, like Sigmar's Fist, for example.

**Comment by ozarmidrashim** [comment]
If it was wrong on live, I can't fix it. I looked for a long time for an ID for this effect with Blessing, but found none. Same problem with Debilitate. Client will always show it as Damaging.

If you're wondering how Inevitable Doom got fixed, it's because there are two IDs for it - one is Damaging and the other is in the test region and has Ailment type.

**Comment by Evildoor** [comment]
That's understandable, but can we at least make it a Blessing on the server side?

**Comment by ozarmidrashim** [comment]
It already is. If you can't Sever it, the client is blocking you.

**Comment by Evildoor** [comment]
Alright, then i'm closing this, since you've already done all what can be done.

Yeah, i just usually say "cleanse from enemy" instead of "remove" or "sever".

**Comment by ozarmidrashim** [comment]
Found the effect - it's under the name Sigmar's Grace instead of Sigmar's Vision....
