### ISSUE TITLE
Hunter Vale boss Kurnous bugged

### ISSUE THREAD

**Issue by JackHollowPoint** [WarEmu/WarBugs#20525]
Last boss Kurunos in Hunter Vale has 5 stages:
(1) Boss HP > 80% - damage his hp and he runs into portal
(2) Boss runs around using portals - destroy portals (gates)
(3) Boss HP 80%->60% - damage his hp and he runs into portal
(4) Boss runs around using portals, additional mobs start to spawn - destroy portals (gates)
(5) Lion/Wolf/Dog stage

**
Actual behavior:
At stage (4): Portals (gates) regenerate HP extremely high rate to 100%. 
This stage is cut into sections where gates disappear and boss runs out of new portal, portals hp should keep damage but it gets healed to full health instead.
(Also sometimes boss bugged is on stage (2) - gets stuck in the portal, wont move. It can be solved by suiciding to his aoe dot.)

**Steps to reproduce the problem:**
Go to last boss in HV, get stage (4) 

**Testing Screenshots/Videos/Evidences (always needed):**
Currently there are no screenshots or videos, but all the groups from both sides (Order/Destro) who tried to complete HV were unable to do so. 

The issue appeared after Demon Moon patch.

**Comment by Rydiak** [comment]
Both issues you are reporting (regenerating gates https://github.com/WarEmu/WarBugs/issues/19190 and Kurnous getting stuck in phase 2 https://github.com/WarEmu/WarBugs/issues/19238) are old bugs that were fixed last year.  Interesting that they seem to have returned.

**Comment by JackHollowPoint** [comment]
Just checked today - the gates works properly. Gates do not regenerate HP.
Thank you
