### ISSUE TITLE
missing seed of chaos skill

### ISSUE THREAD

**Issue by yobro117** [WarEmu/WarBugs#20524]
i have trained seed of chaos,with my magus,from path of changing but can't find this skill nowhere

**Comment by lilimx** [comment]
Hey,

what's your current lvl and rr?

**Comment by lilimx** [comment]
Hey,

the skill is available with lvl 21. 
If you could, hit lvl 21 and check if you can get the ability after that.

**Comment by yobro117** [comment]
Ok thank u for answer 👍🏻

Inviato da Outlook per iOS<https://aka.ms/o0ukef>
________________________________
Da: lilimx ***@***.***>
Inviato: Wednesday, November 2, 2022 8:31:31 PM
A: WarEmu/WarBugs ***@***.***>
Cc: yobro117 ***@***.***>; Author ***@***.***>
Oggetto: Re: [WarEmu/WarBugs] missing seed of chaos skill (Issue #20524)


Hey,

the skill is available with lvl 21.
If you could, hit lvl 21 and check if you can get the ability after that.
