### ISSUE TITLE
Flame Shield

### ISSUE THREAD

**Issue by Ramessu** [WarEmu/WarBugs#20522]
Flame Shield for BW is not working properly for me. After applied, the icon greys out and has a 1x on the icon. When trying to reapply or add for others in group I get message, "TARGET ALREADY HAS THAT EFFECT" message, (Doesn't matter whether or not anyone is targeted). /rel and logging doesn't fix the issue. Restarting the game works, but once I apply Flame Shield, I get the same issue again. I also tried a repair from the launcher as well with no resolution. Greyed out icon is circled in red on the image. Thank you for any help.

![WAR-64 2022-11-01 19-54-11a](https://user-images.githubusercontent.com/84376715/199364437-e2be965e-ef20-48bf-ba38-73c9dabeb4d3.jpg)

Image while in Scenario with player targeted, message above and no buff for targeted player in group.
![WAR-64 2022-11-01 20-09-05a](https://user-images.githubusercontent.com/84376715/199365196-47b4c6d8-435a-4d29-8dd5-156033eaabe6.jpg)

**Comment by Rydiak** [comment]
Are you using the addon GCDSaver?

**Comment by Ramessu** [comment]
> Are you using the addon GCDSaver?

Yes, v1-0-6

**Comment by Ramessu** [comment]
I disabled it and Flame Shield appears to be working again. Is the issue related to the version of GCDSaver? BTW, thanks for the help!

**Comment by Rydiak** [comment]
Yes, GCDSaver is trying to keep you from recasting something that you already have.  Hold Shift and Left-Click the ability and you can cycle through the stacks allowed or even disable GCDSaver for that ability totally.

**Comment by Ramessu** [comment]
Got it, thanks!
