### ISSUE TITLE
Event Quest III Omen

### ISSUE THREAD

**Issue by Gamble885** [WarEmu/WarBugs#20520]
I have accepted the quest from the Event . Killed the lord with a group. Could also deliver the quest and also got the item. But the quest is not shown as done in my overview. Unfortunately, I do not get the event mount. Warhammer restarted I have also already

**Comment by Rydiak** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=49567
Kill all the mobs again, not just the final lord, and it should work properly for you.

**Comment by Gamble885** [comment]
yes , i killed all of these mobs 3 time. now counts

**Comment by lilimx** [comment]
//maybe just take look at it
