### ISSUE TITLE
WL toughness stacks

### ISSUE THREAD

**Issue by Cruella01** [WarEmu/WarBugs#20531]
WL "trained to hunt" is stacking with toughness potions. 
Steps to preproduce, take toughness potion or liniment and toggle train to hunt. 
Steps to fix, remove it... they're OP as it is. While at it half their damage or give them light armor to bring the class in line.

**Comment by Rydiak** [comment]
Isn't Trained to Hunt a bonus to the lion pet, not the player?

Also, you should be posting balance issues on the forum for discussion, not the bug tracker.

**Comment by lilimx** [comment]
Hey,

this ticket makes no sense.... Actually it's "Trained to Kill" that gains toughness to you playable character.
Additional, if it's a personal buff or a tactic that only belongs to you and can't be shared with other players (like an aura, zealot/rp buff, WP wounds buff... etc.) then you can use an additional pot/liniment....same with the Magus/Engi armour buff.

And as Rydiak said, if you think it's a balance issue, please use the forum.
