### ISSUE TITLE
Shami GREENBEANS entered the Top of Tavern BO / Imp T3

### ISSUE THREAD

**Issue by bleifuss22** [WarEmu/WarBugs#20534]
Well, 10 minutes ago...  Wed, Nov. 08 2022, at 22:15h CET
However this player could reach the tavern roof. It has to examined why and how. And if there is a chaet with it, dont hesitate to speak a bann to cheaters...
This kind of waste kills the fairness and gameplay...

![Yeehaw_005](https://user-images.githubusercontent.com/79282928/200678670-8d066ab9-cc4e-4331-8e3b-799cab355199.jpg)

**Comment by Gladiolix** [comment]
Most likely he got punted there.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. But please don't write tickets like that.
Im going to rewrite it.
