### ISSUE TITLE
Dwarfes T4 - Cant get my T4 weapon

### ISSUE THREAD

**Issue by bleifuss22** [WarEmu/WarBugs#20532]
I have all the points, but merchant does not let me get my T4 weapon at Dwarfes T4/Kadrin

![Yeehaw_002](https://user-images.githubusercontent.com/79282928/200432704-ef5d14c1-66c2-4ca0-bbfa-4c6d93fbd5ba.jpg)

![Yeehaw_003](https://user-images.githubusercontent.com/79282928/200432753-efae6bdd-6f1d-44f4-98bd-e73297ef29f4.jpg)

![Yeehaw_004](https://user-images.githubusercontent.com/79282928/200432783-c5db15ff-ae71-46ba-bd04-f7ee90757e67.jpg)

**Comment by Rydiak** [comment]
In the first picture you linked, could you go back to that same tome page and place your cursor over the right-most blue/green dot above the list of the available items and take a screenshot of what it says?  From the looks of it, it appears you already acquired all of your rewards.

**Comment by bleifuss22** [comment]
1st Pic: Book says I have the points to get the weapon
2nd Pic: I am not able to select and pic my weapon
3rd Pic: 2nd confirmation in book/history, I reached the points to pic up waepon

I did not acquired the 3rd lane with weapons

**Comment by Rydiak** [comment]
![Rydiak_064](https://user-images.githubusercontent.com/15963532/200691718-5d81cdf3-de11-41ed-90c2-9bf913a03292.jpg)
So just to confirm, when you hover over the influence line it shows the tooltip saying "You can collect your Elite Reward!"?

**Comment by lilimx** [comment]
Hey,

Im going to close this ticket soon if I don't get a screenshot similar to Rydiaks last one.

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
