### ISSUE TITLE
Caledor (Elf) Chapter 22 PQ is bugged on the 2nd Part

### ISSUE THREAD

**Issue by KingGwar** [WarEmu/WarBugs#20533]
I normally run the "Pure Power" PQ (Chap 22) in Caledor quite frequently. The first stage works fine but when you hit stage 2 you have to kill 10 mobs and click the cage to free the elf trapped inside. When you click the cage to free the elf that instantly starts Stage 3 of the PQ. When you put your cursor on the cage, it turns into of a hand symbol to let you click the cage, but the game won't let you click the cage. Just needs a reset...

Thank You~~

**Comment by lilimx** [comment]
Hey,

I've tried to reproduce it, but it works on my end. Could you post a few screenshots maybe?

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
