### ISSUE TITLE
T4 Nordland Morra Lair Debloster doesnt go away.

### ISSUE THREAD

**Issue by DaGreenest** [WarEmu/WarBugs#20537]
T4 Lair boss Morra area debolstering doesnt go away and the lvl 40 minion wolves can kill you before deblostering goes away.

**Comment by Zomega-WAR** [comment]
Relates to this lair (has coordinates on the wiki): https://wiki.returnofreckoning.com/Morra

I have managed to get onto the terrain above the lair and bolster does not vanish there either.

**Comment by Tinkakat** [comment]
Seems to be working fine now. The debolster goes away when you enter the cave.

![Morra](https://user-images.githubusercontent.com/120656691/208270858-ad1ffe02-4452-4458-8eeb-5c65fee4b5d0.jpg)

**Comment by lilimx** [comment]
Fixed with patch 17/11/2022
