### ISSUE TITLE
Problem with knockdowns.

### ISSUE THREAD

**Issue by Narcoticx** [WarEmu/WarBugs#2053]
Most of them time you're able to change the direction your charackter faces while beeing knocked down.
That's pretty annoying for classes who rely on backstabs and I don't think it's intended that way.

**Comment by Evildoor** [comment]
Have you experienced this while being knocked down yourself? Or just seen it on others? Because, while this is quite possible (and should be fixed in such case), i remember that even on live it was pretty common that you KDed someone, and after some delay they turned, or even moved a bit - due to lag, i think.

**Comment by noisestorm** [comment]
I personally also have this _very_ often. Rightclick mouse turning while being on the ground definitely works, but i didnt knew this was actually moving the server based direction.  Just thought that may be some client visual glitch or whatever. But if it really affects positionals it definitely needs to be looked at sooner or later

**Comment by Nfkillz** [comment]
play as WE and WH and you will taste all problem of this bug

**Comment by Evildoor** [comment]
According to several reports, this is still an issue.

**Comment by ozarmidrashim** [comment]
Verified from the code that player position updates are not sent while knocked down. Anything you're reporting is either the result of delay or cannot be fixed by me.

**Comment by Evildoor** [comment]
Changelog 19th May, 2016
[General]
- Server will now use player's last facing direction before knockdown/stagger for all positional attacks and will ignore any heading updates until kd/stagger ends.
