### ISSUE TITLE
White Lion Trained To Hunt Pet Abilities 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#20549]
**Expected behavior and actual behavior:**
AoE abilities should trigger once they are within the estimated feet range.
So by the time it has reached its target these 2 AoE abilities are on Cooldown and cannot be used when they are actually needed.
Still not sure if this is intended or a bug though.

**Steps to reproduce the problem:**

As shown in video. Take your distance from a target like as far as you can so there is not a confussion on ft range.
Call Lion. Enable Train to Hunt buff and command your pet to attack your target.

**Testing Screenshots/Videos/Evidences (always needed):**

https://user-images.githubusercontent.com/16375224/202046905-330995cc-705e-4f53-bad1-10695cac0a81.mp4

**Comment by lilimx** [comment]
Hey,

I can't watch your video :(

**Comment by Razielhell** [comment]
> Hey,
> 
> I can't watch your video :(

Still can't see it?

**Comment by lilimx** [comment]
Hm on my phone it doesn't work. Will check it tonight again.

**Comment by lilimx** [comment]
hm still can't watch it...weird

**Comment by lilimx** [comment]
Hey,

im closing this thread now, because the video is still broken. Please open a new thread with a working one.
