### ISSUE TITLE
Squig Armor

### ISSUE THREAD

**Issue by Wylfred** [WarEmu/WarBugs#2054]
I get 1 damage of almost the hits when i go Squig Armor in T1

**Comment by Evildoor** [comment]
#1806

**Comment by Wylfred** [comment]
not teh same i didnt recive toughnes, its only every hit i recive is 1 famage, my thougnes is 100.

**Comment by Evildoor** [comment]
In char list? Or in .getstats too?

**Comment by Wylfred** [comment]
it seems is working now correctly.
