### ISSUE TITLE
Game is turning off

### ISSUE THREAD

**Issue by TokcMed** [WarEmu/WarBugs#20542]
Hello! I do not know if i writing my issue to the right place but i just decide to make a bug report.
My operation system is Windows 10 Pro x64. Last time i played warhammer online is aproximetly 2-3 months, but few days ago i decide to play again and face a problem. I am starting game choose a charecter and maximum time i can play is 5 minutes. After that game just turning off. I tried to change clint version on x32 and it also did not help. Maybe you know how to help me?

**Comment by Tesq** [comment]
this is likely a win 10 problem, likely disable whatever useless and stupid internal security protection win 10 have.

**Comment by lilimx** [comment]
Hey,

this tracker is actually just for bugs. If you have technical issues, please visit our 
forums (https://www.returnofreckoning.com/forum/)
or join our
RoR Discord (https://discord.gg/returnofreckoning)
