### ISSUE TITLE
Can't Que SC's

### ISSUE THREAD

**Issue by westcoastcobra** [WarEmu/WarBugs#20546]
Hello. I'm unable to join SC's. I logged in for the first time today and attempted to que for an SC, but received a message stating that i recently left a scenario or refused a scenario, which is not possible due to the fact I just logged in and tried to que for the 1st time. 

thank you.

**Comment by lilimx** [comment]
Hey,

does your issue still persist?

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
