### ISSUE TITLE
Lectors twins resetting during encounter

### ISSUE THREAD

**Issue by shaggy996** [WarEmu/WarBugs#20548]
In the past if there was one tank the twins could be set at opposite sides of the room and the tank run back and forth as the mob that could be attacked changed.  The immune twin would not move when invulnerable. 

Currently if this is attempted, the invulnerable mob still moves some times and at a random point in the encounter one of the twins will simply disappear and reset his health thus resetting the twins health also.  the only way to complete this at all reliably now is two tanks and dont move the two twins. This exuberates the difference between  the difficulty of crypts and tunnels vs BB/BE on destro.
it now not only takes much longer to complete C&T as it always has. But requires a second tank now unlike BB/BE.  

To reproduce it, simply take one boss to one side of the room and the other to the opposite side and try and do the encounter. At some point one of them will disappear and reset.

**Comment by Spelldaoc** [comment]
https://www.youtube.com/watch?v=uWzm8FkC6mM

(Take a little time for the video to be rendered to HD by YT.)

**Comment by lilimx** [comment]
Should be fixed around patch 25/11/2022
