### ISSUE TITLE
Chosen M4

### ISSUE THREAD

**Issue by Rebiff** [WarEmu/WarBugs#20543]
Chosen M4 damages players and NPCs alike, can be used to kill armor vendors in IC ( chosen m4  Warping Embrace)

**Expected behavior and actual behavior:**
damages NPCs and allies, not supposed to

**Testing Screenshots/Videos/Evidences (always needed):**
https://youtu.be/GWrubAGa9so

**Comment by Rebiff** [comment]
you right, you diserve a manticore!

**Comment by Rebiff** [comment]
Maliketh Duplicate of Malekith
![image](https://user-images.githubusercontent.com/91923176/201806722-6346d07c-14d2-4a3f-bbc6-722947bfccdc.png)

**Comment by Zomega-WAR** [comment]
No idea what that comment is for, nor the previous "you right, you diserve a manticore!" one that was emailed to me (since deleted?). I'm just linking the tickets so both can be closed once the fix goes live.

**Comment by Rebiff** [comment]
They are jokes, i figured you wouldnt understand the first one, so i replaced it with the screenshot above. saying that you "maliketh" is a duplicate of me (only in names) malekith. Sorry if these jokes hurt either your brain or your feelings, was not my intention. ill be sure to keep it 100% serious on my fix pending bug tracker tickets from now on! <3

**Comment by lilimx** [comment]
Fixed with Patch 25/11/2022
