### ISSUE TITLE
Offensive Subjugator Weapon missing for Shadow Warior from Genesis Vendor

### ISSUE THREAD

**Issue by Milkyn** [WarEmu/WarBugs#20547]
Offensive Subjugator Weapon missing for Shadow Warior from Genesis Vendor, that leads to not able to buy the offensive fortress weapon.

Nothing more to say here

**Comment by Rubyeclipse-war** [comment]
Thank you for this report - I'm looking into it now, but I actually see the defensive "Blade of the Subjugator" missing, not the Falcata, which is the offensive. Can you please share a picture of what you're seeing?

**Comment by Rubyeclipse-war** [comment]
I've adjusted this so that the Subjugator Falcabat for Shadow Warrior can either turn into the Offensive or Defensive Fortress weapon.

This way, the conversion is simple and players can decide how they want to upgrade when they get to fortress. This change will go live on the next patch!

**Comment by lilimx** [comment]
Fixed with patch 17/11/2022
