### ISSUE TITLE
NPC Missing in Altdorf

### ISSUE THREAD

**Issue by Griz70** [WarEmu/WarBugs#20556]
The NPC Rhanz Folner  for quest " The Sewers of Altdorf" is not in game, The red map icon shows but he is not standing at the podium like he normally is by the sewers. I have tried to /reload UI and restarted the game.

**Comment by Rubyeclipse-war** [comment]
Looked into this and found him. Rhanz had wondered off attempting to handle some Skaven, and was mostly fine. 

This NPC will reappear properly following the next server boot this week! Thank you very much for the ticket.

**Comment by lilimx** [comment]
Fixed with Patch 25/11/2022
