### ISSUE TITLE
Cloak / Emblem bugg

### ISSUE THREAD

**Issue by Gojbe** [WarEmu/WarBugs#20551]
![Xtra_001](https://user-images.githubusercontent.com/110549410/202381622-61cf8c4f-7b09-4dd5-9fe1-4e7003aa7bfe.jpg)
![Xtra_002](https://user-images.githubusercontent.com/110549410/202381715-6387cf24-efbb-47c6-b775-526dd3e82c13.jpg)

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

I try to make a new cloak emblem but when i press save it do not save it :/ please help me.
And i was not able to create "Imaginary Friends" did say it was taken or baned name and i dont see it so is that guild named baned?

**Comment by lilimx** [comment]
Hey,

Okay I see the issue now. Your guild need atleast lvl 20 to unlock all clock settings.
