### ISSUE TITLE
"ROR" map icons being sent to the client for all friendly NPCs in range.

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#20555]
**Expected behavior and actual behavior:**

Expected: normal NPCs (no quests, not merchants, etc) should not show on the map and mini-map
Actual: as of Patch 17/11/22 they are all showing on the map and mini-map with the ROR icon

**Testing Screenshots/Videos/Evidences (always needed):**

Dwarf Chapter 1

Minimap:

![image](https://user-images.githubusercontent.com/60266177/202467372-e3460f98-da79-4234-bbef-5f6bb7a6a154.png)

World map:

![image](https://user-images.githubusercontent.com/60266177/202467423-fc6fa1c0-a01d-4053-853b-5f84ea8d1d80.png)

**Comment by Zomega-WAR** [comment]
Posted on Discord, not my screenshot.

Altdorf:

![image](https://user-images.githubusercontent.com/60266177/202467553-68fbb114-3e95-4a12-af55-21137c302c93.png)

**Comment by Zomega-WAR** [comment]
Also applying to destro. From IC:

![image](https://user-images.githubusercontent.com/60266177/202471000-400dc36d-c774-4b26-99e6-8efc53079184.png)

**Comment by lilimx** [comment]
uhm I think it's fixed
