### ISSUE TITLE
Quest: "Fire in the Hole!" (starter quest) offers strength potions to a Rune Priest as a reward

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#20550]
**Expected behavior and actual behavior:**

Expected: to my knowledge the quests should offer stat potions relevant to the class, in this case (Rune Priest) a Willpower or Intelligence potion.

Actual: this quest has 2 rewards for a Rune Priest: a strength potion and healing potion.

Note: this is one of the starter quests so newbies will have no idea the strength potion does nothing for them.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/60266177/202347585-4e80d4d1-8a7d-4b5e-b43e-261ec5744fdf.png)

**Comment by lilimx** [comment]
Fixed with Patch 25/11/2022
