### ISSUE TITLE
The Sewers of Alforf Quest

### ISSUE THREAD

**Issue by Svarkor** [WarEmu/WarBugs#20559]
The NPC "Rhanz Folder" seems to be missing from the SE corner of Altdorf. There is one in Sigmar's Hammer, but when talking to him it doesnt complete the quest. I did this quest yesterday with my other toon with no issues. Already tried abandoning and retaking the quest. Also tried relogging/relaunching the game. It doesnt matter much but that sigmar's recall its pretty helpfull.
![Screenshot_6](https://user-images.githubusercontent.com/118511936/202651004-dacc7aa3-1013-4738-9a87-2f814a85fdf3.png)
![Screenshot_5](https://user-images.githubusercontent.com/118511936/202651094-f28ac57a-4e0b-43f6-8599-ba6d542df904.png)
![Screenshot_10](https://user-images.githubusercontent.com/118511936/202651281-a3c30640-58e3-4f0f-919c-87820d22667b.png)

**Comment by Griz70** [comment]
Ya i reported this yesterday

**Comment by Rubyeclipse-war** [comment]
Thanks for the ticket - this has been fixed! Rhanz will return to his position in Southeast Altdorf as of the next patch.

**Comment by lilimx** [comment]
Fixed with Patch 25/11/2022
