### ISSUE TITLE
Blessing of Chaos Zealot Tactic Confirmation

### ISSUE THREAD

**Issue by Vigfuss** [WarEmu/WarBugs#2056]
This tactic is only proccing from crits of direct heals, and not from heal over time abilities or ritual of lunacy.  Is this how it was on live, or should all heals be able to proc this tactic?

**Comment by Morksezstop** [comment]
yes, only from direct heals crits. Afaik heal ritual can not crit so it should not proc it at allq while hot crit will be quite powerfull cos of leaping alteration

**Comment by ozarmidrashim** [comment]
http://warhammeronline.wikia.com/wiki/Rune_of_Serenity

"Each time Rune of Serenity bounces to a new ally, it may trigger abilities dependent on direct-healing effects, such as Ancestor's Echo or Blessing of Grungni."

As BoG is the direct mirror, I believe this is working as intended.

I also believe it's working as intended because getting a 25% healbless on your target from ANY critical heal would be ludicrous.

**Comment by Morksezstop** [comment]
how is hot proc more insane than 15 ap flash or group heal spam is beyond me

**Comment by noisestorm** [comment]
>how is hot proc more insane than 15 ap flash or group heal spam is beyond me
rly? you dont see where that is far more op than it is supposed to be?

**Comment by Morksezstop** [comment]
group heal could proc all sort of procs on 6 ppl, how is hot proc more powerfull than that? Hots got pretty hard counters and can be made obsolute, making them proc valuable effects will just bring them on par with group heal, you know making backline healers more on par with dok/wp

**Comment by ozarmidrashim** [comment]
The problem is that you're assuming it will be a case of HoT procs OR group heal spam. In practice it will be both.

**Comment by Morksezstop** [comment]
yea that is true but you got it almost permanent due group heal and flash why not add some procs from hots. And that is consideringn ot only rp/zealots but other healers. when group heals could proc all make rest of the heals lesser hence dok/wp dominance

**Comment by noisestorm** [comment]
It already proccs on gheal AND the bouncing aoe Hot. that is decent enough i would say.

**Comment by Vigfuss** [comment]
It is not proccing from leaping alteration.  According to this that should be a bug.

**Comment by noisestorm** [comment]
Just the initial Application has a chance to procc it. Not the multiple ticks itself. But that still grants you an extra chance for something that actually is not considered a direct heal anyways. If it really does not procc at all, report back

**Comment by Morksezstop** [comment]
flash proc all too, which make flash and gheal superior to all kind of hots. Imo procs from hots and nothing from mindless gheal is much better balance fix but obv is only me

**Comment by noisestorm** [comment]
You should be using the armor/armorpen tactic for HoTs in the first place. This alone makes them VERY valuable to apply. Spamming flashheal is never a 'pro' feat, but rather a small straw to grab on while kiting. But thats no Gameplay talk here. Tactic is only supposed to be on direct heals and nothing else. Runepriest 'suffer' from the same drawback, but that doesnt make them bad in any way.

**Comment by Vigfuss** [comment]
With only 3 tactics for now, I guess it might not be the best tactic to build around for the time being.

**Comment by Vigfuss** [comment]
All makes sense thanks for your feedback

**Comment by Evildoor** [comment]
So, i guess this ticket served its purpose and can be closed.
