### ISSUE TITLE
[Dwarf Chapter 1] Black Power Barrel in the PQ has the wrong animations

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#20568]
**Expected behavior and actual behavior:**

Expected: this barrel is just a normal barrel

Actual: during stage 2 of the PQ you have to interact with the barrels. When you do they start animating and bouncing around like the curious barrels in the city which have surprise nurglings/skaven in.

**Steps to reproduce the problem:**

Interact with this barrels during stage 2 of the PQ. All of the barrels were affected during that stage.

![Agemoz_003](https://user-images.githubusercontent.com/60266177/203396515-d0d3772e-1794-4c5d-968d-71bbc9187c32.jpg)

**Comment by lilimx** [comment]
Fixed with Patch 18/05/2023
