### ISSUE TITLE
 [Marauder] Stance Tactic Bug is still valid after patch

### ISSUE THREAD

**Issue by wildwindblows** [WarEmu/WarBugs#20564]
Hello,
I created Marauders Tactic bug 4 month ago but this bug is still valid after 17/11/2022 patch. FYI Please.
Previous Topic:  [Marauder] Using Stance tactics as an 5th Tactic #20285: https://github.com/WarEmu/WarBugs/issues/20285

![Marauder Tactic Bug](https://user-images.githubusercontent.com/45720515/202897088-5f853fe1-4e55-4667-81b3-cd63e242ffe7.jpg)

Thanks.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. 
But this was not intended to be fixed with this patch. 
Additonal it's a dublicate.
