### ISSUE TITLE
energy of vaul not receiving healing bonus on base heal from WP.

### ISSUE THREAD

**Issue by kaspn** [WarEmu/WarBugs#20565]
base heal on energy of vaul is not being affected by willpower healing bonuses.

**Comment by lilimx** [comment]
Hey,

Yeah that's correct. Abilities that heals through dmg always uses Str or Int.

**Comment by kaspn** [comment]
no the base heal is affected by WP, the bonus heal from dmg is affected by int. the BASE heal is not receiving the bonus from will power.
