### ISSUE TITLE
Dark Ambition: Missing Body (DE Chapter 2)

### ISSUE THREAD

**Issue by LuckyRaider** [WarEmu/WarBugs#20560]
Hi there, i quested this morning in DE Chapter 2 and wanna do the Quest: "Dark Ambition" normally there is the dead body of evidance near beside the tent but today there is nothing.
The body is missing and the quest aren't be able to finish.

Ok, found the bug: the body isn't at the ground, he is still alive beside the tent and looks like a normal living npc.

**Comment by lilimx** [comment]
Hey,

uhm you were able to finished it after you found him save and sound?

**Comment by LuckyRaider** [comment]
the last sentence is only a update. at first i couldn't finish cause i was looking for the dead body as he was last time i did the q. then i tried to check all npc's around or maybe hidden marker at the ground AND after an hour of testing i finished the q by using the q-item at the living stalker beside the tent. so normaly the body was dead (dead on the ground) and now he is still alive (standing ultharion stalker).

**Comment by Rubyeclipse-war** [comment]
On the dev server, I'm seeing this: 

![image](https://user-images.githubusercontent.com/60584990/203177631-e3e8f603-0acd-45e8-96f3-ad6962e19243.png)

Sounds like it may fix itself upon next server patch. Can you show me an image of exactly what you're seeing on your side? (Guessing he's just standing up normally?)

**Comment by lilimx** [comment]
Fixed with Patch 25/11/2022
