### ISSUE TITLE
[Dwarf Chapter 1] "Ironclaw Rock Lobber" siege engines will charge at you and attack

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#20567]
**Expected behavior and actual behavior:**

Expected: these are stationary siege engines that you can destroy while they remain stationary

Actual: they function like normal NPCs so they will chase you around and attack you

**Steps to reproduce the problem:**

Go to "Frost Peak" (west of the Dwarf Chapter 1 PQ) or the Dwarf Chapter 1 PQ itself and attack the Rock Lobbers. They will fight you back.

**Testing Screenshots/Videos/Evidences (always needed):**

This one was on the end of the bridge facing away before I attacked it, then it charged at me and attacked.

![Agemoz_004](https://user-images.githubusercontent.com/60266177/203395361-1273052d-19b1-4ad0-a0d0-01ab0e85a698.jpg)

This one was in the Dwarf Chapter 1 PQ. Combat log visible showing it attacking me after running (wheeling?) over to me.

![Agemoz_002](https://user-images.githubusercontent.com/60266177/203395586-f0519127-1112-4265-b788-26350e911b41.jpg)

**Comment by Rubyeclipse-war** [comment]
Have to admit, this was so funny I almost didn't want to fix it. Gork and Mork empowered lobbas are apparently deemed too strong in T1, so these will no longer move or auto-attack you back as of the next patch. 

Please note that this fix only *contains* the murderous intent of these clearly sentient siege weapons, so when you least expect it, who knows when they may break free and go on another rampage...

**Comment by lilimx** [comment]
Fixed with Patch 20/01/2022
