### ISSUE TITLE
Missing Items

### ISSUE THREAD

**Issue by fizzlepwn** [WarEmu/WarBugs#20561]
Hey I've played for a while back in the day and my brother and I decided to log onto our mains today. When I attempted to log onto it though I crashed. I remember having an almost full inventory from last I played this character about a year or two ago. I logged back on it with my gear unequipped and some of it put into the inventory of my Black Orc, but more than half of my end game gear was missing from the inventory due to it being filled up. I don't remember all of what I had but it was a mix of warlord/offensive sovereign set for the Black Orc and it's tragic missing these key items because I had a full inventory in the past. Is there anything you can do?

**Comment by fizzlepwn** [comment]
![image](https://user-images.githubusercontent.com/84000280/202856525-df751280-5b96-4a25-be8f-564532162f74.png)

**Comment by fizzlepwn** [comment]
I've cleared space in the inventory but still ended up missing pieces of gear I've worked hard on. Any help would be greatly appreciated

**Comment by xyeppp** [comment]
Hey, did you ever sort this out? I am having a similar issue on my character.

**Comment by fizzlepwn** [comment]
after an update went out i had gear unequipped and all of a sudden i had my gear back equipped on me last time i logged onto that black orc. sorted itself out mostly
