### ISSUE TITLE
Names after break have a random extension

### ISSUE THREAD

**Issue by jspieckermann** [WarEmu/WarBugs#20562]
**Expected behavior and actual behavior:**
Installed the game again and noticed that a lot of my characters have a random name extension. When I try to login, I am forced to enter a new name. One example is my character Halvar, on armory: https://www.returnofreckoning.com/armory/character/502103

Account name: tamarlan

Would be nice if you can solve my issue as it is a no go for me to rename my main characters.

**Steps to reproduce the problem:**
Think it is obvious in this case.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by xpander69** [comment]
How long have you been away without logging in with the characters?
The names get freed up after 1 year of inactivity.

**Comment by jspieckermann** [comment]
I really do not know how long exactly. According to armory none of these names are taken by others. Can you check whether those names are taken but not in armory? Names are very important for me so thanks for your support.
