### ISSUE TITLE
No choice between M.crit chance and Reduce Crit Chance for tanks(Chosen)

### ISSUE THREAD

**Issue by Masterrar** [WarEmu/WarBugs#20577]
**Expected behavior and actual behavior:**

Expected behavior:
Chosen and other tanks **_HAVE_** choice between Event Accessory with Reduce Crit Chance AND M.CRIT CHANCE

Actual behavior:
Chosen and other tanks have only M.Crit. chance

**Steps to reproduce the problem:**
Done main quest(pve way)

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/12447382/204041617-f0c2c237-0336-47c8-9ebd-098dac2e2494.png)
31 
![image](https://user-images.githubusercontent.com/12447382/204041764-af760699-d4e8-4ec9-bfba-04f45ad47200.png)
21 
![image](https://user-images.githubusercontent.com/12447382/204041846-291f44c5-be8f-4e0a-a541-7ceb0a213bbc.png)

**Comment by lilimx** [comment]
Hey,

Eka did a thing. Let's wait for the next reboot/patch.

**Comment by lilimx** [comment]
fixed with patch 30/11/2022
