### ISSUE TITLE
[CRAFTING] [APOTHECARY] Increases brew result on per backpack item

### ISSUE THREAD

**Issue by Syzako** [WarEmu/WarBugs#20576]
Increases brew result on per backpack item.
One ingredient used to create 8 items instead of 2.

![1](https://user-images.githubusercontent.com/39750677/203975672-0c386474-552b-4850-9aad-88892c3b4ea1.png)
![2](https://user-images.githubusercontent.com/39750677/203975688-e031221b-6665-4baf-855a-7ece1cdba8a6.png)

**Comment by Syzako** [comment]
Quickly fixed after a server restart, thanks.

**Comment by lilimx** [comment]
Fixed with hotfix 25/11/2022
