### ISSUE TITLE
Fortress Trollsplitter typo

### ISSUE THREAD

**Issue by Rebiff** [WarEmu/WarBugs#20579]
Fortress Trollsplitter has an effect that reduces incoming healing, but it says it only reduces incoming heals by 25, instead of 25% which is misleading. Almost had an aneurism when I first read the ability effect. 
![image 1](https://user-images.githubusercontent.com/91923176/204060116-15b74af8-5adf-4c08-b7f3-f78d3d770464.png)

**Comment by Rubyeclipse-war** [comment]
This has been fixed. Updated description will go live in the next patch for all weapons with the "Guile" ability proc. 

![image](https://user-images.githubusercontent.com/60584990/212536436-2f111335-283e-4c96-8a69-2d33f124a449.png)

Thank you!

**Comment by lilimx** [comment]
Fixed with Patch 20/01/2023
