### ISSUE TITLE
[Sequencer] Cant save after Week Pie patch

### ISSUE THREAD

**Issue by Symbelmyne** [WarEmu/WarBugs#20575]
After patching I logged BG in lvling now, i tried make a sequence using sequencer addon, but instead having 2+ skills on one button after pressing "save" i still got 1st ability sloted.
Easy to reproduce - right click any ability on skillbar, add another one to a sequence, press save - close it, reopen - there is only 1 ability.

**Comment by Emissaryx** [comment]
Sequencer is completely broken now. If a sequence is changed at all it is broken from their on out. It gives a Invalid Ability ID when trying to save the sequence. 
![Capture](https://user-images.githubusercontent.com/107319355/204068468-cd1b17f5-ca8f-4f98-9685-2e4272fff56e.PNG)

**Comment by Proficula** [comment]
i confirm this issue. Same here.

**Comment by lilimx** [comment]
Fixed with patch 30/11/2022
