### ISSUE TITLE
event issue: kill level 40 Greased pig then nothing drop.

### ISSUE THREAD

**Issue by dihanin** [WarEmu/WarBugs#20587]
event issue: kill level 40 Greased pig then nothing drop.
<img width="551" alt="image" src="https://user-images.githubusercontent.com/45137982/204306113-5f5af114-931a-437b-b6c2-75d17df9dd8a.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/45137982/204306182-65a71e0c-bb8e-4cf9-a0c8-35a44b9dd22c.png">

time: Altdorf 15:37

**Comment by dihanin** [comment]
and I do it again. still nothing 
<img width="549" alt="image" src="https://user-images.githubusercontent.com/45137982/204319485-d84259d2-7b96-41a0-b64e-6da23b915e96.png">

**Comment by lilimx** [comment]
Hey,

What's your current lvl. Maybe it's a bolster issue, so we want to reproduce it.

**Comment by Rubyeclipse-war** [comment]
Had some guildmates kill this the other day and we also noticed sometimes it wouldn't let anyone loot the items for maybe 30-60 seconds after it died.

Eventually, either by time passing or by having every member of the party/warband keep clicking, it would work, and the mount will appear.

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
