### ISSUE TITLE
Aborted item fusing and lost talismans

### ISSUE THREAD

**Issue by MannyKarlavera** [WarEmu/WarBugs#20585]
On 26/11 at 10:40 Altdoff time I sloted my 2h sword with two talimans, but before fusing it I aborted the process and clicked the x. 
The fusion was aborted but the talis were lost... not sure if this is a know error or had something to do with the weird server behavior this weekend.

**Comment by xpander69** [comment]
do a relog and check again.
Or maybe this all happened during the server rollback time?

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
