### ISSUE TITLE
Graphic Error - KoTBS Sov Merchant "Romarich Schaper"

### ISSUE THREAD

**Issue by rormurkin** [WarEmu/WarBugs#20580]
**Expected behavior and actual behavior:**
Sov Chest is showing a graphical icon of boots

**Steps to reproduce the problem:**
- Play class KoTBS
- Talk to one of the Sov gear merchants "Romarich Schaper"
- Buy the chest
- Graphic icon shows boots instead of chest.

**Testing Screenshots/Videos/Evidences (always needed):**

https://user-images.githubusercontent.com/119102304/204079935-fe5a1f67-239d-4bac-ac0f-a57794706670.mp4

Extended video is available upon requested.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
This issue was already reported here: #16171

//maybe related to #19315
