### ISSUE TITLE
Pious Restoration not granted.

### ISSUE THREAD

**Issue by osfalpha** [WarEmu/WarBugs#20583]
**Expected behavior and actual behavior:**
Level 24 WP with full keeper set.  After training Pious Restoration in Path of Salvation tree the ability is not granted.
Tried respec'ing several times, hard and soft logging.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

Pious Restoration is actually a lvl 25 skill. 
Try to lvl up and write a little reply.

**Comment by lilimx** [comment]
Hey,

yeah that's right...you have all points...but the ability itself is available with lvl 25.

**Comment by lilimx** [comment]
Hey,

yeah I hope this will be resloved with Dalens ability fix. 
But all in all you need a certain lvl for some abilities now. Some Abilities are locked behind a lvl wall atm.
