### ISSUE TITLE
Oathstone jewelry set bonus is not working/broken

### ISSUE THREAD

**Issue by Skullgrin** [WarEmu/WarBugs#20597]
The Great Oathstones jewelry set is supposed to give a 2 piece set bonus of +15% haste. 

Here are links to the items in question in the armory, however the bonus is not listed there.
https://www.returnofreckoning.com/armory/item/640113
https://www.returnofreckoning.com/armory/item/640114

In this first screen shot I am wearing the Skullcase of the Imperator, which gives +5% haste, and that can be verified via the .getstats info in the chat window under AuotAttackSpeed.
![haste3](https://user-images.githubusercontent.com/40448982/205127875-f102fd23-179a-455a-8099-e7df5790c15a.jpg)

In the second shot I am wearing both Imperator pieces for +10% haste. Again it is properly displaying this in .getstats.
![haste2](https://user-images.githubusercontent.com/40448982/205128537-5d439b7e-129c-4b03-b153-193a20603b79.jpg)

Here I am wearing only the Oathstones set. Note that the haste bonus for the set is not being displayed in .getstats.
![haste1](https://user-images.githubusercontent.com/40448982/205128892-110dd252-1b99-4651-8626-f92825e8783c.jpg)

I initially wanted to try using this jewelry set in combination with the new Eicheschatten Pie (+10% haste) and when it did not work at first I thought that the two did not stack together. However, when I used the pie along with the Imperator set I see that the pie does indeed stack with the armor bonus, as seen in this screen shot.
![haste4](https://user-images.githubusercontent.com/40448982/205129872-72c000b4-8554-4558-b014-0c2109268a67.jpg)

I have tried various combinations with and without the pie active, along with different haste gear and the +15% haste for the Oathstones is never displayed in .getstats, which shows that the ability bonus is broken. You might want to check the other old jewelry sets to see if any of them are also somehow not working.

**Comment by lilimx** [comment]
Hey,

could you try to /rel when you switch gear?
I can't reproduce the issue, because it's working as intended on the dev server.

.getstats without any gear and with "The Great Oathstone"-bonus
![image](https://user-images.githubusercontent.com/23266079/205150012-d1bede8c-1bdc-4b4c-bb12-90ab5b3ca201.png)

Here with the Imperator shoulders + "The Great Oathstone"-bonus
![image](https://user-images.githubusercontent.com/23266079/205150335-7dc8c0da-9fa0-4918-a5fb-e3dd8d7ee0fc.png)

**Comment by Skullgrin** [comment]
Logged in to test and it seems to be working now, It wasn't for several days beforehand, so thats odd. Will send you a PM if I notice it acting up again, but for now you can probably close this.

**Comment by lilimx** [comment]
Hey,

If the issue appears again, please open a new ticket. I will add your old ticket.
