### ISSUE TITLE
Unable to craft pies in certain situations

### ISSUE THREAD

**Issue by RogertG** [WarEmu/WarBugs#20594]
**Expected behavior and actual behavior:**

Expected behaviour: Regardless if the ingredients and the oven are scattered in the main backpack or crafting items one, pie crafting should not be be affected.
Actual behaviour: Since today, some of the ingredients go to the crafting items pack. Some remained in the main backpack. Now,  IF you have the Oak Wood + Indredient 1 in main backpack, AND another needed ingredient in the crafting items slots, THAN the "You do not meet the requirements..." message pops when you try to purchase a 5xpie from the merchant.

**Steps to reproduce the problem:**

1. Have an Oak Wood oven in your main backpack
2. Have eg. "Harvest Spices" in your main backpack
3. Have eg. "Harvest Cherries" in crafting backpack.
4. Try to buy from Mildred Tumbleberry the 5x Esmeralda pie
5. You'll get an error message "You do not meet the requirements..."

**Testing Screenshots/Videos/Evidences (always needed):**

![1](https://user-images.githubusercontent.com/32964032/204920012-2f0420c7-f944-42ce-877f-7632a483a76b.jpg)
![2](https://user-images.githubusercontent.com/32964032/204920027-bcc1a4c1-5104-4164-9364-9823163d05b7.jpg)

IG char: Lanillis/AM

**Comment by RogertG** [comment]
Workaround: "Players can place items from crafting bag ---> Bank, then pull them back from Bank ---> Main bag as a temporary workaround to solve this."[1]

1. Spell on official Discord ROR channel.

**Comment by lilimx** [comment]
fixed with patch 22/12/2022
