### ISSUE TITLE
Ingedients in the crafting-bag-> no ovens

### ISSUE THREAD

**Issue by VylozV** [WarEmu/WarBugs#20592]
Dark greetings,
i am glad, that you changed the ingredients to be able to "become" crafting-items. I have put all into that bag-folder and now i have the issue that the vendor doesn´t want to sell me ovens... He doesn´t seem to see, that the ingredients are there AND its impossible (not possible without tricking around, with putting it into the vault and taking it out again) to put them back into the regular bag (so the vendor may see, what i have in my pockets;))
I hope, you can fix this!
Sa´an´ishar!
Vyloz

**Comment by VylozV** [comment]
thanks for the fast reaction! It still doesn´t work via crafting-bag, but we can put them back into our "normal" bag again and buy ovens! You guys saved the Event! *bows low*
May the dark gods bless you!!

**Comment by VylozV** [comment]
Everything works as intended now, Amazing! Thanks ;)

**Comment by lilimx** [comment]
Hot Fix 03/12/2022
