### ISSUE TITLE
Unable to open Summons from Thyrus Gormann

### ISSUE THREAD

**Issue by pthiel168** [WarEmu/WarBugs#20595]
Right Clicking the item in the Quest Items location of the Inventory produces no result, it should open a new quest.

To reproduce: Be a level 60+ Order character. Got to the Record Keeper and purchase the Summons. Right Click the Summons in inventory to attempt to open the quest.

**Testing Screenshots/Videos/Evidences (always needed):**

![Summons](https://user-images.githubusercontent.com/8930990/205058527-14d17d06-d8fb-4e26-a6df-cc7208681837.png)

**Comment by lilimx** [comment]
Hey,

I can't reproduce your issue. It works on the dev and on the live server.
Did you done any other quest before?

![image](https://user-images.githubusercontent.com/23266079/205147287-69224e88-f51a-4277-9c7c-3a3e464041e7.png)

**Comment by pthiel168** [comment]
I have not done any of the Leveling up quests on this character (I have done so with no issues on some Destro characters). I have done other quests from the quest tab of the Inventory bag but not for quite a while. Thanks

**Comment by lilimx** [comment]
Hey,

we can't find anything. I will add an special label, just in case if there are any tickets with the same issue in the near future.

**Comment by lilimx** [comment]
related to #20596
