### ISSUE TITLE
Unable to open Genesis Letter

### ISSUE THREAD

**Issue by pthiel168** [WarEmu/WarBugs#20596]
Right Clicking the item in the Quest Items location of the Inventory produces no result, it should open a new quest.

To reproduce: Be a level 36+ Order character. Got to the Record Keeper and purchase the Genesis Letter. Right Click the Letter in inventory to attempt to open the quest.

**Testing Screenshots/Videos/Evidences (always needed):**

![Summons](https://user-images.githubusercontent.com/8930990/205058527-14d17d06-d8fb-4e26-a6df-cc7208681837.png)

**Comment by lilimx** [comment]
Hey,

I can't reproduce your issue. It works on the dev and on the live server.
same question, have you done any other quest before?

![image](https://user-images.githubusercontent.com/23266079/205147636-1bf14357-3eb3-4748-a0a2-2899d7a86ef0.png)

**Comment by lilimx** [comment]
Hey,

we can't find anything. I will add an special label, just in case if there are any tickets with the same issue in the near future.

**Comment by lilimx** [comment]
related to #20595

**Comment by Rubyeclipse-war** [comment]
Can you check to make sure that you have enough room to accept a new quest? Please try abandoning some quests and then see if this helps. Thanks!

**Comment by pthiel168** [comment]
Thanks, I tried that, deleted quests until I have only a single page of them and still no luck.
