### ISSUE TITLE
Esmeralda's Hearth Pie duration changed from 60 minutes to 30 minutes

### ISSUE THREAD

**Issue by RogertG** [WarEmu/WarBugs#20591]
**Expected behavior and actual behavior:**

"Esmeralda's Hearth Pie", one of the Pie Event's item, first time when I used it had a 60 minutes duration like all the other pies. I have tested them all. However, yesterday, I observed that it's duration has changed from 50 minutes to 30 minutes. No other pie's duration is affected, all still lasts 60 minutes.

**Steps to reproduce the problem:**

1. Create Esmeralda's Hearth Pie.
2. Use the pie.
3. Check the duration: it's 30 minutes
4. Use any other available pie.
5. Duration: 60 minutes.

**Testing Screenshots/Videos/Evidences (always needed):**

![Esmeralda](https://user-images.githubusercontent.com/32964032/204748545-9bcc5dbe-cbf4-47f2-9991-d61098e2b1ab.png)

![WAR-64 2022-11-30 10-11-59](https://user-images.githubusercontent.com/32964032/204748570-8806b7cb-39f2-4b0d-8d51-ce5e9e2f19ca.png)

![WAR-64 2022-11-30 10-12-47](https://user-images.githubusercontent.com/32964032/204748608-b0b194e9-9470-4dab-ac5a-ace74463e909.png)

**Comment by ekalime** [comment]
appears to be a tooltip issue, when used the buff under the character portrait shows 60min
![Disc_011](https://user-images.githubusercontent.com/91421798/204862561-ba2aa15f-fe82-4114-86c7-59f8966190c8.jpg)

**Comment by lilimx** [comment]
Fixed with patch 22/12/2022
