### ISSUE TITLE
[Quest] Lost in Translation

### ISSUE THREAD

**Issue by moondoggcavalier** [WarEmu/WarBugs#2059]
Disciple Rageborn has two of these quests available at once. 
![moondogg_008](https://cloud.githubusercontent.com/assets/15387904/11486598/1c954c64-9788-11e5-8b08-65620506bdf5.jpg)

I would imagine that the second one is supposed to be available after the first is completed.
![moondogg_009](https://cloud.githubusercontent.com/assets/15387904/11486600/1c98a03a-9788-11e5-8a91-82ef2c7783ad.jpg)
![moondogg_010](https://cloud.githubusercontent.com/assets/15387904/11486599/1c97e064-9788-11e5-9f58-e9826441729f.jpg)

**Comment by Meralors** [comment]
Fixed :D live next patch
