### ISSUE TITLE
"Far from home" can,t interact with Dwarf Doorknocker

### ISSUE THREAD

**Issue by Anerill** [WarEmu/WarBugs#20605]
**Expected behavior and actual behavior:**
Progres quest by interacting with object demanded by quest

**Steps to reproduce the problem:**
Take "far from home" quest from dwaeven king in Altdorf. End first part by talking to NPC Svengi Grumhammer. Go to doors and try interact with obejct.

**Testing Screenshots/Videos/Evidences (always needed):**

![Aneril_046](https://user-images.githubusercontent.com/95439181/205508813-40a35c55-5644-4dca-8655-4219a7ecb9f5.jpg)

**Comment by lilimx** [comment]
Hey,

that's the wrong door knocker. Maybe check the next door.
