### ISSUE TITLE
Missing Items After Ward Changes

### ISSUE THREAD

**Issue by xyeppp** [WarEmu/WarBugs#20609]
**Expected behavior and actual behavior:**
I have logged into the game after a long hiatus, only to find my character get stripped naked & crash in the process due to the new ward system.
Upon logging back in my backpack was full, and now I am missing two Warlord pieces which I had equipped on me before (shown in the ToK section).

I have read somewhere the items should be at the Buy Back Merchant section but they are not there, nor are they in K8P & IC banks.

**Steps to reproduce the problem:**
Log-in any old character from before the ward update that has a nearly full backpack.

**Testing Screenshots/Videos/Evidences (always needed):**
![ToK unlocks](https://user-images.githubusercontent.com/12982209/206382939-0d7d40d5-6f02-4a95-87ac-9d2f85d00c98.png)

**Comment by lilimx** [comment]
Hey,

make space in your bag back and both city vaults, then wait for a proper server restart.
Unfortunately, we do not refund Items.
