### ISSUE TITLE
[Qhaysh Defender] Missing Talisman Slot

### ISSUE THREAD

**Issue by Xalak** [WarEmu/WarBugs#2060]
Ironbreaker, Dwarf, Influence Shield [Qhaysh Defender] is missing it's talisman slot.

![inf shield](https://cloud.githubusercontent.com/assets/16090807/11487944/fc18117c-977f-11e5-8506-b0f78b8e2eaf.jpg)

**Comment by Meralors** [comment]
Will now have a talisman slot with next live patch, lucky dwarf
