### ISSUE TITLE
Chaos chapter 4, PQ Fields of Woe bugged

### ISSUE THREAD

**Issue by Roakh** [WarEmu/WarBugs#20612]
**Expected behavior and actual behavior:**
Stage 1 - destroying of Weapon Wagons. All 10 Wagons are dead, but count only 9/10. Stage 1 have no reset timer and its stuck.

**Steps to reproduce the problem:**
Come to PQ Fields of Woe. See that this stuck. People in chat said its stucked for days.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/120131285/206543320-a0bd4cbd-a26f-44d6-95d3-9c4869ac1200.png)

**Comment by Roakh** [comment]
PQ have 10 wagons, sure. But all of them dead, but game think 1 alive.
![image](https://user-images.githubusercontent.com/120131285/206806693-62498fe6-429e-4c94-bef4-10929f5d7f30.png)

**Comment by Ornerie** [comment]
This PQ is still bugged and is a stopping point for Vanity is its Own Reward epic questline.

**Comment by Rubyeclipse-war** [comment]
Hello - thank you for the report! 

I've added an extra Wagon to this PQ which will now also count for stage completion credit. This way, just in case one of the wagons bugs out again, you'll have a spare wagon that can be used to progress this to Stage 2. 

This fix will go live on the next patch. Thanks for being patient and for letting us know!

**Comment by Roakh** [comment]
Thanks a lot!

**Comment by Ornerie** [comment]
YAY! I've never been so happy to wait for patch day!  LOL

**Comment by lilimx** [comment]
Fixed with Patch 22/12/2022
