### ISSUE TITLE
Нашел ошибку в игре за сквига в 2 ветке развития

### ISSUE THREAD

**Issue by Dugaros** [WarEmu/WarBugs#20618]
Приветствую я играю за пастуха сквигов в 2 ветке развития и у меня ошибка при использовании всех тактик из этой ветки сразу. находясь в броне когда я призываю сквига меня выкидывает из брони . так же если я выпил зелье на броню на 60 мин оно пропадает когда пропадает броня сквига

**Comment by Dugaros** [comment]
имя персонажа Grufalo 39 уровень

**Comment by lilimx** [comment]
Hey,

Please open a new ticket in english, thank you.

**Comment by Dugaros** [comment]
Greetings, I am playing for the shepherd of squigs in the 2nd development branch and I have a mistake when using all tactics from this branch at once. being in armor , when I summon squig , I am thrown out of armor .

**Comment by Dugaros** [comment]
when he drank the potion for 60 minutes and jumped into the squig armor and then back into his normal appearance, the effect of the potion disappears
