### ISSUE TITLE
Spell effects are not working after a while

### ISSUE THREAD

**Issue by Ulfwych** [WarEmu/WarBugs#20614]
Ive been playing on my AMD 3600 / Geforce 3070 / 32 gb PC and ive noticed after a while of playing my character spell effects for buffs or the magus "horse" spell do not work after a while. 

If i log onto another character or restart the game it will work again but after a while they wont again.

I play with all settings at the highest.

Anything i can do to solve this? 

Thx

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. 
I would recommend to ask in our tech-support forum first: https://www.returnofreckoning.com/forum/viewforum.php?f=4
If you can find evidences for a bug, please open a new ticket with a description of steps you have done.
