### ISSUE TITLE
Cant log on one of my characters

### ISSUE THREAD

**Issue by Falkvor** [WarEmu/WarBugs#20616]
Hello.

I cant log on one of my characters. When I click play on that character, nothing is hapening. All I can do after that is close the game. When I loged in on another character, I can see in the guild roster that the character is stil on. 
![Theangel_002](https://user-images.githubusercontent.com/103452666/207026637-e81b17a2-e0ca-4422-9c27-543232668f78.jpg)
 Bouth of the characters that is on is mine. The Witch Hunter is the one that I cant log on.

**Comment by lilimx** [comment]
Hey,

Pleass check out this thread: https://www.returnofreckoning.com/forum/viewtopic.php?t=46249&start=860
Add your name and guild and what happened there.
