### ISSUE TITLE
Order ram but looks like destro ram on map.

### ISSUE THREAD

**Issue by ioana95** [WarEmu/WarBugs#20627]
Hello,
Today, 12/18/2022 in rvr in TM, Order popped ram in Thunder Mountain, but on map it showed like Destro ram, therefore our warband got destroyed by order cuz we thought it was our ram. Please fix this bug, t
![image](https://user-images.githubusercontent.com/120955461/208307520-45b4da06-c13d-4678-8c0a-c4162432e650.png)

**Comment by lilimx** [comment]
Hey,

thanks for your report. However we are missing some crucial information in your report and without further evidence we cannot continue investigating. Please follow the Bug Report template when creating a Bug Report.

Who spawned the ram?
What kind of ram?
Do you have pic while the ram was at the keep?
Does it happened again? or in a different zone?

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
