### ISSUE TITLE
High pass ogrund's tavern door is permanently closed.

### ISSUE THREAD

**Issue by Nukemi** [WarEmu/WarBugs#20622]
**Expected behavior and actual behavior:**

Door should open. Only back exit is available. Assuming they tried to fix the previous bug with the door in patch today and it got worse. 

**Steps to reproduce the problem:**
Stayed in for a while killing order who came in through back exit. Could not open it for 30mins+

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/116276071/208143917-424d4d0e-ecb0-491a-8993-fb0a86fccdd0.png)

Before patch: Before when the door broke, it went to 0 hp due to aoe. Now after the patch its just permanently closed at 100% hp and cannot be opened. This can screw up empire pairing royally till its fixed.

**Comment by lilimx** [comment]
Hey,

Thank you for your ticket. This issue has been already reported here #20621
