### ISSUE TITLE
Door to Tavern In High Pass Won't Open

### ISSUE THREAD

**Issue by Emissaryx** [WarEmu/WarBugs#20621]
**Expected behavior and actual behavior:**
Doors should open when clicked on. Doors are not opening at some points it is taking 3 to 5 minutes before doors to tavern can be opened. I just assumed this bug was turned in as this has been happening every NA evening (est) for the past 3 nights. 

**Steps to reproduce the problem:**
Click on door, watch it not open

**Comment by lilimx** [comment]
Hey,

yeah, that's weird. On the dev server it works as intended. Ingame it works weird.

**Comment by Rubyeclipse-war** [comment]
Thank you for the ticket! This same issue happens in the Black Fire Pass Tavern sometimes too. 

It appears to be the door somehow taking damage even when it shouldn't be able to. 

I'm putting in a fix with the next patch that should make both doors invulnerable to damage. Just in case it somehow has any other side effects (it shouldn't), please let us know if anything strange happens. Hopefully all should be good going forward!

**Comment by lilimx** [comment]
Fixed with Patch 22/12/2022
