### ISSUE TITLE
player cheating : Ifyouseekamy (witch elf)

### ISSUE THREAD

**Issue by dihanin** [WarEmu/WarBugs#20628]
15mins ago, 3 orders kill this "we" is normal. and kill she twice.
dmg is normal. and 3 or 4 players attack her together is reasonable.
at least we saw her HP is reducing.
after 15mins. 
engineer attack zero dmg till dead.
witch hunter attack zero dmg till dead.
AM attack zero dmg till dead.
and people release in lord room
THIS "WE" CAN KILL PLAYER AND LORD NONE REACTION WHEN "WE" RUNNING AROUND WITH  LORD ?!
LORD ZERO REACTION TILL "WE" KILL PLAYER?!
WTF IS GOING ON? 
THIS TIME GONNA TELL ME AGAIN NEED MORE PROVE?!

[
<img width="236" alt="image" src="https://user-images.githubusercontent.com/45137982/208662829-3bf53c42-bd4a-4011-8f51-fd6f17e53304.png">
](https://drive.google.com/file/d/1yoWbGfSRk_Z09HO5Gfh1Dqp7Ov1wuG7y/view?usp=share_link)

**Comment by Rydiak** [comment]
Contact a GM if you believe a player is cheating. The Bug Tracker is not the place for this.
