### ISSUE TITLE
Unable to  purchase Swordmaster Fortress Blade due to missing Falcata of the Subjugator

### ISSUE THREAD

**Issue by phidelio** [WarEmu/WarBugs#20624]
Swordmaster Fortress Blade requires Falcata of the Subjugator to purchase.  This Falcata of the Subjugator is not available for purchase from the genesis vendor, however, there is a Blade of the Subjugator for purchase.

**Comment by Rubyeclipse-war** [comment]
Thank you for the ticket - I was able to confirm this.  

I've added a new option to the vendor that will allow you to trade in the Blade of the Subjugator for this. It'll go live in the next patch. 👍

**Comment by lilimx** [comment]
Fixed with Patch 22/12/2022
