### ISSUE TITLE
Marshes of Madness - Hot Spot - War Report

### ISSUE THREAD

**Issue by Rebiff** [WarEmu/WarBugs#20635]
When war reporting to marshes of madness it should put you in the War-Camp. instead it ports you to the ch6 camp at the top of the map that is completely out of the way. I used the Hot Spot option (enemy has been engaged in marshes of madness) Enemy implying RvR so no reason to send to PvE, I'd understand if this was a PQ war report option. 

![image 1](https://user-images.githubusercontent.com/91923176/209450385-5829bc16-bb49-4b60-840d-4519533d1ad8.png)

**Comment by Rubyeclipse-war** [comment]
Thank you for the ticket. We were able to confirm this and have updated it so that it should properly send you to the Destruction Warcamp instead of Chapter 6.

**Comment by lilimx** [comment]
Fixed with Patch 20/01/2023
