### ISSUE TITLE
Rend Soul and other Channel abilities

### ISSUE THREAD

**Issue by unstoppable1776** [WarEmu/WarBugs#2063]
Channel abilities are at a 85% solution. My rend soul is way more effective than what it was 6 months ago when it was unusable. However it stops channeling enough, where I cannot rely on it fully. I have done numerous test, from spamming the ability, it getting parried or blocked, and everything seems in check. However about 15% of the time or greater it discontinues. Please take a look at this ability. Its not from players interrupting, its another issue.

**Comment by Silvertusk** [comment]
yeah same goes for BOs tree hit combo sometimes it stops or worse not even start so i guess that goes for all channel abilities

**Comment by Evildoor** [comment]
This issue is known (#843, for example), and cannot be fixed yet.
