### ISSUE TITLE
Game restart after a few minute : impossible to play

### ISSUE THREAD

**Issue by Stonick46** [WarEmu/WarBugs#20636]
Hi all, 

I look for help as I am not the most advanced guy to solve bug. I have installed Age of Reckoning on my girlfriend laptop a few days ago. Her laptop is :
 
Asus Vivobook 
Intel Core i7 - 1065G7 CPU 1.30ghz 
RAM 8Go 
Windows 11 
Graphic card Intel Iris(R) Plus Graphics
Audio controler Realtek(R) Audio 

Unfortunately the game restart always after a few game time, making it impossible to play. The bug always start with some strange noise making me thinking of an audio bug. I have made all the recent update from windows, and the different driver especially realtek as I was thinking it was an audio bug, but the issue continue. I have tried to "repair" the game as well as uninstall it and reinstall it, but nothing change. 

Here are the login and debug files, hopping it will help you to help me ^^ 

[debug.log](https://github.com/WarEmu/WarBugs/files/10300557/debug.log)
[login.122522.Log](https://github.com/WarEmu/WarBugs/files/10300559/login.122522.Log)

Any idea of where the problem come from ? 

Thanks a lot for your help.

**Comment by lilimx** [comment]
Hey,

I would recommend to join the RoR Discord and ask in #technical-advice
Additional, replace the audio.myp in your RoR folder:
https://mega.nz/file/lXBVzL5Y#Fht-670v6ahaUDLb_nGpZsxuH_xD_wN3vGAmlHUGkZM
