### ISSUE TITLE
Ranger's relics won't complete

### ISSUE THREAD

**Issue by topdudes** [WarEmu/WarBugs#20639]
A guild member and I did the relic task of Kegs End event yesterday. 2 of the relics won't register for both of us and the task won't complete.

**Expected behavior and actual behavior:**
Click on a relic, get credit for event task. Worked on 11 out of 13 but when I try in BF of Badmoon hole they don't register.

**Steps to reproduce the problem:**
I've now tried 4 times at each location with the same result

![Squatheals_007](https://user-images.githubusercontent.com/81526782/209576457-0b7b5fd1-bcba-4dcf-9120-a9e15fe91015.jpg)

**Comment by topdudes** [comment]
My second screenshot wouldn't load in first post.
![Squatheals_006](https://user-images.githubusercontent.com/81526782/209576548-305090f7-98b7-4e69-9d83-e9d978b40772.jpg)

**Comment by lilimx** [comment]
Hey,

Could you post all available page entries that are related.

**Comment by topdudes** [comment]
> Hey,
> 
> Could you post all available page entries that are related.

I'm guessing you only wanted the page displayed in the badlands shot. Well I've posted every tomb page leading to the relics that won't work and screenshots of me at the relic locations.
![Angrund relics Badmoon](https://user-images.githubusercontent.com/81526782/209694430-ee7e3d6a-104f-4e37-bb34-16468c36a089.jpg)
![Gruber's Remains Badlands](https://user-images.githubusercontent.com/81526782/209694564-276617b6-571e-4bfa-a0e3-9ec8c8c3a72a.jpg)
![KE tasks 2](https://user-images.githubusercontent.com/81526782/209694644-16e1f795-c5b9-458f-9a51-7e16a929ee59.jpg)
![KE tomb](https://user-images.githubusercontent.com/81526782/209694858-f53bac96-683c-432a-a939-8b351b349c9e.jpg)

**Comment by topdudes** [comment]
One that didn't upload with my first reply.
![KE tasks](https://user-images.githubusercontent.com/81526782/209695060-6cbd4afc-7a22-4c8a-a3f4-a681b52259bb.jpg)

**Comment by ekalime** [comment]
I know this is too late, but the Angrund's Relics credit was given, and the riddle 'Defend the pass at Varn Wyr' is another relic. Likewise the Oeragor relic is another one, not the one selected in the screenshot.
