### ISSUE TITLE
Keeper Set +1 Ability Gear - Funnel Power Not Showing Even Though Selected

### ISSUE THREAD

**Issue by warrencsteven** [WarEmu/WarBugs#20637]
This is specific to Bright Wizard, and the +1 stat on the Keeper Set and Funnel Power.

_Note: I tested if the +1 ability works on the tactic below Funnel Power and it does become available but Funnel Power does not._

Expected behaviour - Funnel Power available in the abilities available when having enough mastery points + 1 from the Keeper Set.

Actual behaviour - activate funnel power with mastery point but Funnel Power is not in the available abilities for use.

Steps to reproduce:
1) Equip the Keeper Set 
2) Select Mastery Points in the Incineration Path and select Funnel Power (6 points needed [5 earned + 1 from set bonus]
3) Check abilities to drag into ability bar - Funnel Power not available

![WAR ROR Funnel Power - Missing From Abilities with +1 Ability Gear](https://user-images.githubusercontent.com/69484598/209499766-452e5423-fbbc-47f1-abc7-699e84afb6bd.jpg)

In the image you can see the Keeper Set gear, the mastery path with Funnel Path selected and the Inciniration abilities without Funnel Power.

**Comment by lilimx** [comment]
Hey,

some spells are locked behind a certain lvl.
Funnel Power is available with lvl 21.
If you want to know more about the lvl cap, check our the ability guide: https://builder.returnofreckoning.com/career/bright-wizard

This "issue" maybe will be solved with the upcoming rework of our ability system.
