### ISSUE TITLE
The Tipsy title

### ISSUE THREAD

**Issue by Blinkey77** [WarEmu/WarBugs#20634]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

For the Keg's End event I opened a present and got a pocket item for getting a title "The Tipsy" when I equip it into my pocket slot. I did that and haven't received the title. I tried reloading UI and log out and back in. I still do not receive the title when the item is equipped in pocket slot.
![12-24-2022 Tipsy Pocket Item](https://user-images.githubusercontent.com/115272027/209447421-6f659207-de1a-4d19-9e65-60e4b0fd50f9.png)

**Comment by Rebiff** [comment]
all of the event equip titles are doing this sadly, like Designated Drinker

**Comment by Rubyeclipse-war** [comment]
Thank you for the ticket - also confirmed this. 

Please hang onto these, as they will fix and should work as soon as the next patch hits.

**Comment by Blinkey77** [comment]
Okay, thank you for taking your time to resolve this issue. I will hold
onto them

**Comment by Rydiak** [comment]
This appears to be fixed now.

**Comment by Blinkey77** [comment]
Awesome, thanks!

**Comment by lilimx** [comment]
Guess was hot-fixed 01/01/2023
