### ISSUE TITLE
2 Warlord vendors in Reikwald

### ISSUE THREAD

**Issue by Majorzero2123** [WarEmu/WarBugs#20646]
When Altdorf is being sieged, a 2nd warlord vendor will spawn where you teleport if you were in Altdorf  getting sent to Reikwald.
![image (3)](https://user-images.githubusercontent.com/99697728/210931689-efacb598-3b0f-4989-a983-a68de1ee91e6.png)
![image](https://user-images.githubusercontent.com/99697728/210931694-6a579971-eb23-4cd7-8b3e-3eaf2648b34f.png)
![image4](https://user-images.githubusercontent.com/99697728/210931711-f8c54d7e-05c1-4686-8594-ce8120387908.png)
![image5](https://user-images.githubusercontent.com/99697728/210931714-f245a1a1-2ca2-401d-9edf-d7d5351d0fef.png)

**Comment by Rubyeclipse-war** [comment]
The duplicate NPC (near the spawn point) has been removed. This fix should go live on the next patch.

**Comment by lilimx** [comment]
Fixed with Patch 11/01/2023
