### ISSUE TITLE
[Squig Herder]Spiked Squig Crit

### ISSUE THREAD

**Issue by Chummi** [WarEmu/WarBugs#2064]
he does not grant the 5% crit. if you check your stats with getstats it is definitely not shown.

**Comment by nuitaran** [comment]
Confirmed.

**Comment by danissrv** [comment]
After the patch the 5% crit from spiked squig is shown in your stats but if you type ".getstats" it doesn't show.
Which is the correct one?

**Comment by mursie** [comment]
Further issue:  character sheet is showing correct crit (pet and gear).  However, .getstats is not showing correct crit and seems to be completely erroneous.  I.e.  my gear is 7% crit and pet is 5% - the .getstats is showing 8% which is neither.

**Comment by mursie** [comment]
appears to be bolster affecting the crit - when i'm out of bolster and no pet - .getstats is reading correct 7% gear crit.  as soon as bolster hits...its 8%

**Comment by mursie** [comment]
Can we please have this fixed?  That is a lot of crit to not be getting .getstats credit for when the spiked squig is out.

**Comment by Evildoor** [comment]
Tested on dev server, .getstats shows crit. Anyone can post .getstats screens with/without squig from live server?

**Comment by mursie** [comment]
![plinkie_000](https://cloud.githubusercontent.com/assets/15176111/11918907/7b3d60a6-a707-11e5-9ebe-acd1fc23ec27.jpg)

This is with spiked squig out.  Character screen shows 17% crit (12% from stalker/dev/influence belt/rvr weapons gear, 5% from spiked squig).

.getstats shows 12%.

Spiked squig is not updating .getstats

**Comment by Evildoor** [comment]
Ahem. Critical hit rate ranged = ranged crit. Critical hit rate = any crit. It adds 5 to those 12, and you also have 5 melee, magical and heal crit, even if you don't use them.

**Comment by mursie** [comment]
in that case - i'm getting the 5% base crit regardless of squig.  Actually with no squig or spike squig i'm getting that 5% crit base on .getstats at all times.

**Comment by Evildoor** [comment]
Hmmm. Tested some more - yes, it seems that 5 crit persists without Spiked Squig, when you unsummon him or whatever. @ozarmidrashim

**Comment by Evildoor** [comment]
Bug is back.

**Comment by ozarmidrashim** [comment]
Personally verified working on RoR at present time.
