### ISSUE TITLE
Gunbad respawns send you to starting area everytime

### ISSUE THREAD

**Issue by Majorzero2123** [WarEmu/WarBugs#20659]
https://www.youtube.com/watch?v=9l3WHOO-A4c
If at any point you die in Gunbad (even when bosses are cleared), it will send you to to the starting area instead of the nearest healer.

**Comment by Rubyeclipse-war** [comment]
Thanks to some help from Max today, the respawns have all been built up again and should work properly as of the next patch. Thank you for the ticket!

**Comment by lilimx** [comment]
Fixed with Patch 20/01/2023
