### ISSUE TITLE
Chosen 1 hander bugged name 

### ISSUE THREAD

**Issue by Majorzero2123** [WarEmu/WarBugs#20654]
![image (5)](https://user-images.githubusercontent.com/99697728/212036866-499332d7-2331-44f5-8bb9-21170785b058.png)
Weapon is obtainable from Hunters Vale as a drop, and it has a bugged name.

**Comment by Rubyeclipse-war** [comment]
Thank you for the ticket - this has been fixed. This name should display properly on the next patch.

**Comment by Majorzero2123** [comment]
Fixed as of 17/1/23, The name displays properly now.
