### ISSUE TITLE
Character cant log in

### ISSUE THREAD

**Issue by Gangrelsbox** [WarEmu/WarBugs#20655]
My character Puppett can no longer log into the game. It lingers forever on "looking for battles" and "searching for allies"
I have other characters that can log in.

At the ending of a battleground I was kicked out of the game, with the above result.
I have restarted everything and checked that theres no problem with my security programs.

Please help.

/Puppett

**Comment by lilimx** [comment]
Hey,

I've already seen you wrote a post in the right thread, so im closing this ticket now.
