### ISSUE TITLE
Keg Tapper Event Item

### ISSUE THREAD

**Issue by Ramessu** [WarEmu/WarBugs#20652]
Hello, I have noticed today that the Keg Tapper event items for all 3 of my characters, (Warrior Priest, Bright Wizard and Archmage) are only available with strength as the main stat and are only available to be equipped by tanks. Please see screenshots.

![WAR-64 2023-01-12 00-54-09](https://user-images.githubusercontent.com/84376715/211989905-cccfc577-ad26-4d62-b036-86709e5d7bfe.jpg)
![WAR-64 2023-01-12 00-54-32](https://user-images.githubusercontent.com/84376715/211989906-e0b891ce-cb88-4a0d-8320-2922c0ad4ce0.jpg)

**Comment by lilimx** [comment]
fixed with patch 20/01/2023

**Comment by Ramessu** [comment]
I patched the game. Even restarted and 2 times as it is suggested to restart once to complete the patch. The Keg Tapper doesn't appear to have changed for my characters. I also don't see the fix in the Patch Notes. Do we need to wait for a server reset? Thank you for your help so far.
![Untitled](https://user-images.githubusercontent.com/84376715/213836835-a38cde21-efcb-46f4-abf4-6dc6a22ef7a0.png)
