### ISSUE TITLE
Unterbaum PQ bugged

### ISSUE THREAD

**Issue by zipherus** [WarEmu/WarBugs#20658]
Unterbaum Cemetery PQ is not progressing past stage two (burn carts).

Expected behavior: Hero should spawn after 4 carts are burned and the champion mobs that spawn are killed.
Actual behavior: Infinite? (did at least a dozen) carts can be burned and the champions killed, hero never spawns.
Screenshots/Video: No screenshot can show this as it is dynamic. Any video recording is far too large to attach, even at lowest quality.

**Comment by lilimx** [comment]
Hey,

did you get a PQ display with the current status of the PQ?
btw. you can upload videos on Youtube and link them here.

**Comment by zipherus** [comment]
It doesn't even show up as a PQ on the UI. It's just on the stage for burning carts, and you can burn as many as you want no progress.

**Comment by lilimx** [comment]
Hey,

yeah, then we already found the issue. So we are going to check other PQs aswell to fix them.
Guess the fix will be up asap.

**Comment by Sralazar** [comment]
Yeah I just arrived at the "Unterbaum Cemetery" in Talabecland,
and it doesn't show up on the UI. No quest stage, nothing.

**Comment by lilimx** [comment]
Fixed with patch 20/01/2023
