### ISSUE TITLE
Well Oiled Mashine

### ISSUE THREAD

**Issue by dreisenbarth** [WarEmu/WarBugs#20656]
Hello dearest WAR Team,

after i load in a new area the Engineer tactic Well-Oiled Mashine is not working and the turret is not instant set.
I need to remove and equip the tactic to fix it.
![Well-Oiled Machine Bug](https://user-images.githubusercontent.com/50382893/212324454-fab71041-1b43-4ef1-854b-9da52fad97dd.png)

**Comment by dreisenbarth** [comment]
After Server restart the tactic works as intended again

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
Should it appear it again. 
Reslot the tactic and do a /rel or a relog. 
Should the issue appear after that, please open a new ticket.
