### ISSUE TITLE
Quest missing reward, and lacking parity between Destro and order 

### ISSUE THREAD

**Issue by Majorzero2123** [WarEmu/WarBugs#20653]
Both of these quests can be picked up at Level 1, both in tier 3 warcamps. 
![image (4)](https://user-images.githubusercontent.com/99697728/212030845-f36df739-6d8e-47de-b26c-18d5ffccb23c.png)
The first quest is on order and has you scout through the 4 T1 elf BOs, and rewards 63,262 exp and 62 silver, 50 copper.  (quest is located in Avelorn Warcamp)
![uwu](https://user-images.githubusercontent.com/99697728/212031257-fc6e77c9-4ce5-4e71-8823-42b455334374.png)
Destros version has you go through and scout t2 (even though you can pick this up at level 1) and doesn't award anything.  (Quest is located in Black Fire pass Warcamp)

**Comment by Rubyeclipse-war** [comment]
Thank you for the ticket. Judging by the quest names, it's pretty clear these were both originally intended for the player to become a Chicken and run through lower-tier RvR zones. 

I'm going to spend a little time re-working these quests, especially the Destro quest to bring this in line with the original intent of Covert Chicken Scouting Operations. Will also fix this up so the Destro side properly grants rewards, and will post an update here once complete.

**Comment by Rubyeclipse-war** [comment]
All complete. Here's what we've updated:

- The Destro version of this quest now sends players to T1 Elf, just like the Order version.
- The Destro version of this quest now properly grants EXP and rewards.
- Both faction's quests have been increased to starting Rank 16, to properly trigger the Chicken transformation.

The updated version will go live on the next patch. Thanks for letting us know on this!

**Comment by lilimx** [comment]
Fixed with Patch 20/01/2023
