### ISSUE TITLE
[quest] Fightin' in da water

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#20664]
Have to destroy two cannons on the walls but none is present, only black powder barrels that can be destroyed.
Previous bug report (#20416) spoke about a pq in the same area but no pq is available.

![Sabadone_003](https://user-images.githubusercontent.com/17765890/212674005-ecb2d32f-f60c-4782-bf66-92019975721a.jpg)

![Sabadone_004](https://user-images.githubusercontent.com/17765890/212674209-75de942f-c0af-4fca-ba27-fcd47d336432.jpg)

**Comment by Rubyeclipse-war** [comment]
This PQ (and a few others, mostly in Dwarf/GS pairing) bugged out recently. The fix is already ready on the dev server and should go live in the next patch.

**Comment by zak68** [comment]
cannons reappeared, quest completed

**Comment by lilimx** [comment]
Fixed with Patch 20/01/2023
