### ISSUE TITLE
[quest] the yolk's on you

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#20669]
in BFP, Morgob is dealing a quest that requires to visit locations inside elf T1.
![Sabadone_006](https://user-images.githubusercontent.com/17765890/213107649-ce4f76c1-e254-4cc1-9d93-c155f3ee9d4e.jpg)

**Comment by lilimx** [comment]
Hey,

hm...That's not so ideal now :D

**Comment by Rubyeclipse-war** [comment]
This is correct, and should be mentioned in upcoming patch notes. A little info on it:

- The Quest Title is a hint at what Morgob is actually asking you to do, as this quest will turn you into a Chicken. (He's a sneaky gobbo)
- Order has the same quest, which appears for them in the Avelorn T3 Warcamp
- This quest previously had no rewards at the end, and will as of the next patch

Original changes / fixes mentioned in ticket #20653

**Comment by zak68** [comment]
got few silver and around 68k of xp, quest completed

**Comment by lilimx** [comment]
Fixed with Patch 20/01/2023
