### ISSUE TITLE
New Guild's Vault: 10 slots instead of 60

### ISSUE THREAD

**Issue by bettargh** [WarEmu/WarBugs#20662]
Recently started a new guild, rasnekd it to past rank 3, but unfortunately there has been a 1o slot unlock instead of 60 in tab 1. It is also impossible to buy other slots.

I have seen issue #1170, but that one was for disapppearing slots, in my caee slots were never unlocked.

![Vault Bug](https://user-images.githubusercontent.com/106921441/212574244-2383e236-8160-4e45-8536-2159bda76cdf.png)

**Comment by Rubyeclipse-war** [comment]
Are you using Viny or any add-ons that come with it? Some of those will break the typical guild bank UI and your ability to properly purchase more vaults.

**Comment by bettargh** [comment]
Yes, I am ! 

As soon as all add-ons were disabled, I was able to purchase as many rows as I wanted!

Cheers

**Comment by bettargh** [comment]
Mind the add-ons, disable first, check and then report a "bug"...
