### ISSUE TITLE
[Magus] Horror/Flamer doesn't work correctly

### ISSUE THREAD

**Issue by Vinfrid** [WarEmu/WarBugs#20679]
When Flamer using skills they are going on cooldown but not deal damage
![tentacleplate 1](https://user-images.githubusercontent.com/76210368/213949763-da92a49c-8bfa-464e-9f4b-af3f0f96dec6.jpg)
When Pink horror using skills, only one are working normal, Demonic Consuption doesn't work
![tentacleplate 2](https://user-images.githubusercontent.com/76210368/213949943-2c469962-280b-4275-a356-9a214a3baa95.jpg)
When Blue horror using skills, as on pink horror, Coruscating Enargy doesn't work
![tentacleplate 3](https://user-images.githubusercontent.com/76210368/213950039-f8cf1ebe-67a3-4e1f-ac11-a2a5ce571052.jpg)

Before cheking, i was thinking my addons can bug it, and i was turn it off

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. This issue was already reported here: #20382
