### ISSUE TITLE
Unable to name change

### ISSUE THREAD

**Issue by Dalgri** [WarEmu/WarBugs#20671]
**Expected behavior and actual behavior:**
Name change usually works every 4 weeks.
Name change has been done more then 4 weeks ago and still isnt possible to rechange

**Steps to reproduce the problem:**
Type .CHANGENAME

**Testing Screenshots/Videos/Evidences (always needed):**

Well i dont think that would be possible.
Im only here cuz GM's dont want to help me and sended me this way

**Comment by lilimx** [comment]
Hey,

what happen when you type .changename
do you get a grey message in your chat (filter: User Errors)?

**Comment by Dalgri** [comment]
Heya thanks for reply.
No error messages.
Usually it doesnt give annything either i think?
But once you log out to char select it shows change name.
This hasnt been working annymore somehow.

**Comment by lilimx** [comment]
_Usually it doesnt give annything either i think?_^

You will always get a message with how much time left.

**Comment by Dalgri** [comment]
I dont somehow

**Comment by lilimx** [comment]
hm, when was your last name change?

**Comment by Dalgri** [comment]
Thanks for youre time and sorry for wasting it.
It says 4 days now after enabling user errors chat filter.

**Comment by lilimx** [comment]
Hey,

oki doki, if the problem still exists in 4 days, then get in touch with me.

**Comment by Dalgri** [comment]
Thank you, appreciated.

**Comment by lilimx** [comment]
Hey,

I guess the issue resolved itself. Please open a new ticket if you have more questions.
