### ISSUE TITLE
Leonine Frenzy Crowd Control Immunity is affecting the Main Character as well as the Pet

### ISSUE THREAD

**Issue by rethmar** [WarEmu/WarBugs#20672]
Leonine Frenzy Crowd Control Immunity is affecting the Main Character as well as the Pet

WL used Leonine Frenzy tried to cast crowd control, was immune to any cc, no immunity timers were shown

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
