### ISSUE TITLE
[quest] chaos might

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#20673]
Quest location is uncorrectly marked in talabecland
![Sabadone_005](https://user-images.githubusercontent.com/17765890/213691164-e2ddb02e-9bff-4a2d-9622-2d35c4900a3b.jpg)

**Comment by Lheana** [comment]
It's not, it tells you to "Travel to the Badlands" as you can see on the quest marker. The quest marker is there to indicate the closest flight master.
