### ISSUE TITLE
Fortress Chraceaxe

### ISSUE THREAD

**Issue by rycko2b** [WarEmu/WarBugs#20670]
Howdy everyone.
I'm trying to buy the fortress weapon for my white lion. Got the subjugator weapon, the crests, the gold, full vanq set unlock, but I still can't buy it, and got no error message about it (like something went wrong, you don't meet the requirement, etc). Any clue on that?

Thanks

**Comment by lilimx** [comment]
Hey,

uhm you've wrote you have the "full vanq set" but you need the full Invader set for the "Invader's Ward".

![image](https://user-images.githubusercontent.com/23266079/213288790-63ef5e1d-88ad-4a38-a807-f5f06eee793e.png)

**Comment by rycko2b** [comment]
Oh. At the  NPC, it wasn't mentionned. Maybe a bug in description. Well if it's only that, it's ok. Just plain stupid that you can't buy it w/o full Invader set

**Comment by Telther** [comment]
Just the invader ward, which could also be obtained from pve (bastion stairs)

**Comment by rycko2b** [comment]
Ok , thanks for the informations. have a nice day :)
