### ISSUE TITLE
Not able to get Soldiers Emblem from keeps

### ISSUE THREAD

**Issue by Mortkin** [WarEmu/WarBugs#2067]
although I have: capped bo's, help to kill the keep lord, i'm not able to get soldiers emblem.

**Comment by ozarmidrashim** [comment]
Keeps which display a message indicating that the keep was taken with little to no resistance will NOT drop medallions.

**Comment by Evildoor** [comment]
Since no objections were voiced, i guess that Azarael's clarification was correct. Closing.
