### ISSUE TITLE
Flashfire-Bug instant mount 

### ISSUE THREAD

**Issue by DyslexicPlayer** [WarEmu/WarBugs#20682]
https://user-images.githubusercontent.com/123300382/214438859-0018e4e0-10bd-4e30-ad19-8bdd706d0c57.mp4

**Expected behavior and actual behavior:**
Flashfire is a tactic for Bright wizards, the tactic allows you to cast a spell instantly after the enemy disrupts you, it is not supposed to work for your mount cast time and it also works for the battle standard.

Currently the tactic works for both mount and battle standard, allowing you to cast them instantly. 

**Steps to reproduce the problem:**
proc the tactic then mount or cast battle standard.

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. 
This is intended.
