### ISSUE TITLE
Keep It Goin'! Tactic not increasing damage on Da Big Un' ability

### ISSUE THREAD

**Issue by Aedros** [WarEmu/WarBugs#20689]
**Expected behavior and actual behavior:**

The expected behavior is that the tactic will increase the base damage of Da Big Un' ability to the amount stated on the tactic tooltip. Currently on my level 24 Black Orc Bonesplitta, the tactic displays a value of 333 damage  for Da Big Un', but when I mouse over the ability tooltip on my action bar, it displays the default non boosted value of 237 (see screenshots).

**Steps to reproduce the problem:**

1. Spec 4 points into Path of Da Brawler and select Keep it Goin tactic. 
2. Place tactic on active tactic list from Skillbook
3. Mouse over tactic to see boosted value
4. Mouse over Da Big Un' ability on toolbar to verify that the value is different and lower than the value displayed in the tactic mouseover

**Testing Screenshots/Videos/Evidences (always needed):**

![Bonesplitta_000](https://user-images.githubusercontent.com/81740142/215368641-1da92923-2270-49bf-b97b-46624096f5f4.jpg)

![Bonesplitta_001](https://user-images.githubusercontent.com/81740142/215368689-8c3e6194-b8fd-496b-b828-bb39f883b8d7.jpg)

**Comment by lilimx** [comment]
Hey,

it's always recommended to do a /rel if you swap tactics. 
If you can bring more evidence, please open a new ticket.

**Comment by Aedros** [comment]
Thanks for looking into it. After conducting my own testing, it would appear that there is a difference between having the tactic equipped versus baseline. Given the screenshot evidence above showing disparate values, should this be reclassified as a display bug? The ability is clearly not displaying the tactic-boosted value. I verified this again, and did /rel between applications of the tactic to see if it made a difference. It did not.
