### ISSUE TITLE
Warcrests are not registering in my inventory

### ISSUE THREAD

**Issue by Narancse** [WarEmu/WarBugs#20683]
**Expected behavior and actual behavior:**
Gain Warcrests according to reward.
Don't receive the proper amount in my inventory.

**Steps to reproduce the problem:**
Gain Warcrests.
Check how many warcests I received.

**Testing Screenshots/Videos/Evidences (always needed):**

![Dobzse_042](https://user-images.githubusercontent.com/25580920/214515016-d6eef818-2a23-4944-8483-5ea224e0ae6f.jpg)
![Dobzse_041](https://user-images.githubusercontent.com/25580920/214515020-d915faaa-d2ee-4d2f-a3ee-e4cc890f16fe.jpg)
![Dobzse_040](https://user-images.githubusercontent.com/25580920/214515023-684f64a1-8501-48e7-914c-45bd85ee393e.jpg)
![Dobzse_039](https://user-images.githubusercontent.com/25580920/214515027-9e8404a1-4a00-4ec1-b384-4cceed76cec7.jpg)
![Dobzse_038](https://user-images.githubusercontent.com/25580920/214515028-d5a7ff25-34d2-48ea-bd9a-4b2c4d85a457.jpg)
![Dobzse_037](https://user-images.githubusercontent.com/25580920/214515029-be616bc1-ae8d-4782-9b9c-71bb8b963b25.jpg)

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
