### ISSUE TITLE
A Public Quest is missing

### ISSUE THREAD

**Issue by samuelalpha86** [WarEmu/WarBugs#20688]
Hell's Fall is seemingly nowhere to be found.

**Comment by lilimx** [comment]
Hey,

We need a bit more information.
Why? Where? How?

**Comment by samuelalpha86** [comment]
Well it's the Public Quest Hell's Fall in Praag. I can't find the enemies anywhere and it doesn't appear on any map either yet the kill counter is visible at one of the warcamps.

**Comment by samuelalpha86** [comment]
I would send a screenshot but I forgot how.

**Comment by lilimx** [comment]
Hey,

I can see the PQ on the map.
PQ is active.
I killed 2 mobs and they counted towards to the PQ progress.

**Comment by samuelalpha86** [comment]
where is it?

**Comment by lilimx** [comment]
In Praag

**Comment by samuelalpha86** [comment]
I know it's in praag but where?
