### ISSUE TITLE
Potion creation error.

### ISSUE THREAD

**Issue by Dippinsauce84** [WarEmu/WarBugs#20686]
I'm not sure if this was already reported but I was trying to make a potion and received an error code which can be seen in the attached screen capture. Just figured I'd do my part and let you know.

**Steps to reproduce the problem:**

I believe it was a combination of journeyman's glass vial, 1 ferocious zoic gore, 1 mad zoic gore, and maybe a blood canine tooth (it was 1 125 main ingredients). 

![Screenshot 2023-01-27 221904](https://user-images.githubusercontent.com/123776746/215202686-959b8564-1b86-4c5e-befb-24cca9c6b1a6.png)

Hopefully this helps improve the game in some way.

**Comment by lilimx** [comment]
Hey,

what have you tried to create?

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
