### ISSUE TITLE
Killboard successive Player Search navigates to Guild Search page

### ISSUE THREAD

**Issue by ShotsOnTarget** [WarEmu/WarBugs#20691]
**Expected behavior and actual behavior:**
Expected: if I search for a player name on Killboard and then from the results page search for another player (or the same) the results page is for players and shows players.

Actual: on the second player search the results are for Guilds.

**Steps to reproduce the problem:**
1. go to Killboard
2. search for a player
3. from the results pages search for another player

**Testing Screenshots/Videos/Evidences (always needed):**
[VIDEO](https://watch.screencastify.com/v/DldEbJfmlDZxEeW9QDwo)

A proposed fix for this is to add `isPlayer={true}` to line 81 on [pages/search.tsx]
(https://github.com/dalen/killboard/blob/4697f8ce8767636e03127601463b8d043c0f4875/src/pages/Search.tsx#L81)

e.g.       `<SearchBox initialQuery={query} onSubmit={handleSubmit} isPlayer={true} />` I've tested this works, as well as Guild search works as expected.

**Comment by MaxHayman** [comment]
Fixed
