### ISSUE TITLE
Pets unsummon on zoning

### ISSUE THREAD

**Issue by nuitaran** [WarEmu/WarBugs#2069]
As stated pets do not persist when changing zones, they unsummon and trigger their cooldown.

**Comment by Evildoor** [comment]
This was already reported at least twice, but those reports that i've found are cluttered with lots of different problems, so we might as well use this one for this issue.
Small addition - when you join a scenario (dunno what happens with other forms of zoning), the cooldown on pet summon is not shown - you just cannot use the ability until CD ends.

**Comment by nuitaran** [comment]
Can confirm, at least with squids, cool down is not shown when joining SC but is with any other zone.

**Comment by grunbag** [comment]
Fixed already
