### ISSUE TITLE
Cannot salvage healing power item

### ISSUE THREAD

**Issue by Cedgewo** [WarEmu/WarBugs#20693]
Received "invalid product" error when attempting to salvage Cloak of the Mender.

**Comment by lilimx** [comment]
Hey,

we need a few more information, to reproduce and prevent this issue.
- Where do you get this item from (order/destro vendor)
- What's your Salvaging lvl
- you wrote "Cannot salvage healing power item", does it mean you cannot salvage healing power items in general?
- Could you add a screenshot from your error message?

**Comment by Cedgewo** [comment]
Hello-from dropped items. I just passed ability to salvage the armor kits you get from RVR and found that I am not able to salvage healing for any of them either, healing critical chance, or magic crit. The only items I can create are strength, intel, and other typical ones you see at the lower levels. +175 salvage but would need to log in to check again. Have to run but will get screen shot-same error for any of the attempts.

**Comment by Cedgewo** [comment]
Salvage lvl 182
![cloak2](https://user-images.githubusercontent.com/97414343/215879602-c773c34a-e416-45fb-93c0-f41dc8b3120a.jpg)
![cloak1](https://user-images.githubusercontent.com/97414343/215879607-a08c3f95-1d14-42f1-9648-a658cb5bff96.jpg)

**Comment by Cedgewo** [comment]
So items from vendors in Altdorf or from PQs. Not sure I have seen the healing and other rare powers with dropped items as I said before.

**Comment by Rydiak** [comment]
RoR does not allow the salvaging of nor creation of "Power" talismans. Thus, you are being prevented from salvaging Healing Power because RoR has specifically restricted it.
