### ISSUE TITLE
The undercorft SC dont work for "Unity against Destruction" quest

### ISSUE THREAD

**Issue by kpihuss** [WarEmu/WarBugs#20690]
**Expected behavior and actual behavior:**
We won the Undercrotft SC with a 6 man group, but we didn't complete the Quest.

**Steps to reproduce the problem:**
Play the Undercroft SC with a 6 man group

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/54821994/215597565-3809da4a-25fa-4da7-84da-4393c1408e45.png)

https://killboard.returnofreckoning.com/scenario/eb35bc01-de28-4e93-9e6f-4a2b489fcca0

**Comment by lilimx** [comment]
Hey,

this quest is an open RvR quest, not a SC quest.
