### ISSUE TITLE
orders slow is ignoring immunity restrictions

### ISSUE THREAD

**Issue by bulgy70** [WarEmu/WarBugs#20697]
order slow ability ignoring immunity restrictions. Think it is the Shadow Warrior's Takedown

See Video, you see that there is a slow on my BG, then stops for a second and then restarts, you also see others in the party suffering the same

https://www.youtube.com/watch?v=r-Zb0OzJfuU

Looks like one of orders slows is ignoring immunity restrictions

**Comment by lilimx** [comment]
Hey,

slow doesn't give any immunity.
Additional some slow debuffs can be removed/dispelled.
