### ISSUE TITLE
[NoM] Infiltration line - Hand of Khaine - Soulfire

### ISSUE THREAD

**Issue by funnytroll** [WarEmu/WarBugs#20705]
After enter college for torch cant exit cause city not under attack
https://imgur.com/QnJOJC3

**Comment by Rubyeclipse-war** [comment]
Thank you for the ticket - this will be fixed with the next server boot!

**Comment by Syzako** [comment]
Still bugged after restart
![image](https://user-images.githubusercontent.com/39750677/219322952-526747ec-8978-409f-b5a0-fe86cb39e2b2.png)

**Comment by lilimx** [comment]
That was not a boot to deploy a stuff

**Comment by lilimx** [comment]
Fixed with patch 24/02/2023
