### ISSUE TITLE
Initiative debuffs from WH bullets stack with any other such debuff

### ISSUE THREAD

**Issue by globalgame** [WarEmu/WarBugs#20706]
Initiative debuffs from WH bullets stack with any other such debuff, for example with SW Eye Shot ability 

On this screenshot 5-6 Witch Hunters attacked me and my initiative dropped to 0 from 258
![WAR-64 2023-02-10 16-14-24-35](https://user-images.githubusercontent.com/24555848/218092884-3f7d6e7d-fd19-453d-84af-25a2fe4c766e.png)
![WAR-64 2023-02-10 16-15-14-91](https://user-images.githubusercontent.com/24555848/218092937-286c37ce-7e9e-4d64-b994-ac20a76bc5a3.png)

One question how can this be how could such a serious bug be allowed to happen ?

**Comment by Zomega-WAR** [comment]
"One question how can this be how could such a serious bug be allowed to happen ?"

In terms of game bugs, this one is actually very minor.

As asked repeatedly in the forum thread you made: do you have a screenshot of .getstats showing the double debuff being applied? The character sheet view is regularly wrong.

**Comment by Kaelang** [comment]
> I could not use .getstats there and i showed you a good example, go and do the rest with your getstats yourself.
> 
> I haven't played RoR for 10 months and maybe I'll quit again in a month .... "very minor" after these words, my desire to play decreases even more

We have over 2000 live bugs, managing live events and a new ability system rework. We ask for .getstats as it's commonly known to be the most effective way to test issues. The Bugtracker is for bugs, it's not for 'this might be a bug go and test it'. 

Please provide an accurate report utilising .getstats so we can see the results.

**Comment by globalgame** [comment]
I asked the players in the chat if anyone wanted to help, but only responded, and for a full test, at least 2 players need

**Comment by Symbelmyne** [comment]
I took opportunity and tested it myself with 2 WHs taken from ingame chat. Results:
Getstat on default character before anything

![Getstats](https://user-images.githubusercontent.com/16525371/218252759-4e250167-e6f1-4923-bea8-e7d91563dcbe.png)

And Video including getstats after one debuff applied and then with both debuff applied.

https://youtu.be/NtYh5D3DmeA

Only one with highest value debuff is taken by getstats.

**Comment by globalgame** [comment]
Symbelmyne thanks
