### ISSUE TITLE
Infamy reward BB/BE

### ISSUE THREAD

**Issue by Skibbas** [WarEmu/WarBugs#20715]
**Expected behavior and actual behavior:**
Not sure if this is working as intended, but atm you can pick up double infamy rewards for BB/BE.
The rally masters seems synced to the infamy progression but not to eachother, which makes it possible to pick a reward for each tier from both (rallymaster at BB and BE) of them.

**Steps to reproduce the problem:**
Gain infamy -> pick gear at BB Rally Master -> Go pick other gear at BE Rally Master.

Pics showing several rewards from same tier.
**Testing Screenshots/Videos/Evidences (always needed):**
![Etuguard_006](https://user-images.githubusercontent.com/79228534/218285812-8892648f-5d3e-4c17-a8a2-9f2b96f538cd.jpg)
![Etuguard_007](https://user-images.githubusercontent.com/79228534/218285814-2ab6c9ea-f61f-4ae4-bca0-ff9a20df76a3.jpg)

**Comment by Rubyeclipse-war** [comment]
This is the same for Order with CnT rewards, I believe. 

Last I heard this was intentional, but let me reconvene with the team just in case. :)
