### ISSUE TITLE
[NoM] Magnus Felberg (mount quest) - ORDER - Butcher's Bill stage, timer bugged if...

### ISSUE THREAD

**Issue by RogertG** [WarEmu/WarBugs#20714]
**Expected behavior and actual behavior:**

Expected behavior: The timer of each stage of the quest, after getting to 00.00, should automatically abandon the quest.
Actual behavior: If a user gets killed, and if the Respawn button isn't used right away, and if you make it to coincide with the last second of the PQ countdown timer, upon respawning the PQ timer is stucks at 00.00. So, when this happen that specific stage - I have tested all 9 stages (3+3+3), since I don't have any 84+ toons - and this bug occurs in Butcher's Bill stage of the PQ.;

**Steps to reproduce the problem:**

Please see the video + the above description.

**Testing Screenshots/Videos/Evidences (always needed):**

https://www.youtube.com/watch?v=DOfc5kAXLmY

**Comment by lilimx** [comment]
Fixed with one of the latest patches
