### ISSUE TITLE
[NoM] Event Progress Issue - Fascination of Murder Kill Counts Not Updating

### ISSUE THREAD

**Issue by slotterheim** [WarEmu/WarBugs#20717]
**Expected behavior and actual behavior:**
![Fascination of Murder Progress](https://user-images.githubusercontent.com/125290490/218504045-72ebdda6-7491-4458-b124-8d545b2227cc.png)

**Steps to reproduce the problem:**

Subsequent kills still arent registering. 

**Testing Screenshots/Videos/Evidences (always needed):**

Buff obtained from cauldron southwest of Wilhelm's Fist keep in Reikland. 

Was solo not in party/wb.

Playername: Bornekhorne, Chosen.

**Comment by slotterheim** [comment]
Noticed buff name and tome don't match - Fascination of Murder (tome) vs Fascination with Murder (buff) could be a factor.

**Comment by lilimx** [comment]
Hey,

yeah it's a typo. 
Just a tip, join a party to do the task.

**Comment by slotterheim** [comment]
Does it have to be party? I'm in a warband in Fell Landing - had the buff killed 2 more didnt get credit.

Buff taken from shrine southwest of destro warcamp.

**Comment by slotterheim** [comment]
Problem was damage contribution sems to be a threshold before credit is given  - all good marking this closed.
