### ISSUE TITLE
withering heat [Bright wizard][emulator][require confirmation]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#2072]
There is a snare above these that stack with the others and shouldn't , i couldn't tested cos no one could log order toons but  maybe is the withering heat channeling; sy

bw - withering heat
engi snare
sw snare (should not be  the self KB)
Am pot snare.

**Comment by ozarmidrashim** [comment]
It's impossible for snares to stack on RoR. Please confirm.

**Comment by Tesq** [comment]
i will if someone want to help test which is not the case even if are a damnit alpha  seems -.-

**Comment by Fuineir** [comment]
I've never seen it stacking, It's impossible.

**Comment by Tiggonos** [comment]
i can provide bw for testing --> Martock , just wisper me.

**Comment by Tesq** [comment]
not sure if it's that it could be any snare or not at all.

Tiggo, which playtime are you online? i'm gmt +1 and i can log anytime.

**Comment by Evildoor** [comment]
Closing until someone provides a confirmation.
