### ISSUE TITLE
Wall clip in IC 

### ISSUE THREAD

**Issue by reyaloran** [WarEmu/WarBugs#20726]
**Expected behavior**

The wall should stop you from entering it.

 **actual behavior:**

Running at this wall can let you walk through it.

**Steps to reproduce the problem:**

1: Go to the eastern entrance of the Apex in the IC.
2. Run at the right side wall between the flag and the door.
3. Clip through.

**Testing Screenshots/Videos/Evidences (always needed):**

https://youtu.be/wjVpvebvd1Q
YouTube link added due to a 10mb limit on videos in GitHub.

**Comment by reyaloran** [comment]
I did some additional testing with a guild mate, you can target and cast on people outside the wall but they cannot do the same to you.

**Comment by Rubyeclipse-war** [comment]
Good find.

All fixed, and the fix will go live with the next patch. Thanks for reporting this in!

**Comment by lilimx** [comment]
Fixed with patch 24/02/2023
