### ISSUE TITLE
Karaz Eight Peaks bestial token merchant

### ISSUE THREAD

**Issue by NSKaneda** [WarEmu/WarBugs#20728]
Oh, Benevolent Queen of Bugtracker, heed my call and don't dismiss it too quickly for I have great tale of minor bug to tell you..

**Expected behavior and actual behavior:**

Bestial token merchant of K8P has order trophies to sell, like a treacherous elf that he is.

**Steps to reproduce the problem:**

Visit Elf Embassy, talk to merchant.

**Testing Screenshots/Videos/Evidences (always needed):**

![Parszywek_006](https://user-images.githubusercontent.com/22037960/219267819-a540c299-a61b-40c9-a545-a0ba8a3882ab.jpg)
_
_

![Parszywek_007](https://user-images.githubusercontent.com/22037960/219268430-ef74d583-b8b2-4aca-aaf3-3e92f2d82f21.jpg)

A minor inconvenience but it forces me to visit Inevitable City instead of remaining in Mork blessed place :)

**Comment by ekalime** [comment]
Your queen failed you. I fixed it.

**Comment by lilimx** [comment]
It's okay. He is a good Minion.

**Comment by lilimx** [comment]
Fixed with patch 24/02/2023
