### ISSUE TITLE
[Gear] Harbinger Pummelers, broken icon

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#20725]
The icon for Harbinger Pummelers (Marauder Gloves) shows a pair of boots rather than a pair of gloves. I did not check the in game appearance as I salvaged it.
![Rezalevadgib_015](https://user-images.githubusercontent.com/13975292/218868940-7166593f-e945-4a5f-82b6-d75c33b4270f.jpg)

**Comment by lilimx** [comment]
https://www.returnofreckoning.com/armory/item/419397

**Comment by Rubyeclipse-war** [comment]
Thanks for letting us know!

This item has been fixed, and both the icon and the in-game display (which was also boots) will properly show Pummelers as of the next patch. 

Should you find anything similar, just let us know and we'll get them fixed up. 👍 Thank you!

**Comment by CaptainoftheHarem** [comment]
I did a quick auction house search for pummelers and found 4 more that look to have broken icons. Would you like me to list them in a reply or make a new post?

**Comment by lilimx** [comment]
Fixed with patch 24/02/2023
