### ISSUE TITLE
PQ elf Chapter 13 - The Circle of Winds

### ISSUE THREAD

**Issue by LeFlot** [WarEmu/WarBugs#20734]
Hello !

The Circle of The Winds QP is bug stage 1

Only the first right stones works to do the quest

**Comment by lilimx** [comment]
Ah found the text

**Comment by LeFlot** [comment]
Sorry i edit with the right number is 13 elf side- order

**Comment by lilimx** [comment]
Hey,

this issue was already reported here: #14063
