### ISSUE TITLE
[Gear] Grim Pummelers, broken icon

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#20738]
The icon for Grim Pummelers (Marauder gloves) shows a pair of boots rather than a pair of gloves. I did not check the in game appearance as I only saw it on the auction house

Grim Pummelers
https://www.returnofreckoning.com/armory/item/413589

**Comment by Rubyeclipse-war** [comment]
This has also been fixed. Onto the next...

**Comment by lilimx** [comment]
fixed with patch 17/03/2023
