### ISSUE TITLE
[Gear] Bandit's Pummelers, broken icon

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#20737]
The icon for Bandit's Pummelers (Marauder gloves) shows a pair of boots rather than a pair of gloves. I did not check the in game appearance as I only saw it on the auction house
Bandit's Pummelers
https://www.returnofreckoning.com/armory/item/414381

**Comment by lilimx** [comment]
Nice! Thx!

**Comment by Rubyeclipse-war** [comment]
This has been fixed! Onto the next one...

**Comment by lilimx** [comment]
fixed with patch 17/03/2023
