### ISSUE TITLE
Wrong location of the Order Stalker's heroes after respawn

### ISSUE THREAD

**Issue by kriegersson** [WarEmu/WarBugs#2073]
Sometimes hero appears in a different location with same coordinates then players kill him on the hill/mountain. He can't be attacked after that until server restart.

Varthek Bloodblade (quest "Blood on the leaves", Avelorn ~58.9k 65k) and some his guards - respawned in Saphery, 58400 64950.

Seems like the same happens with Frugnuk Ironfang (quest "Head and Shoulders Above", The Badlands 29380 35040).

![war 2015](https://cloud.githubusercontent.com/assets/16107582/11514924/de3fd72a-989c-11e5-862d-7e28957236f7.png)

**Comment by wargrimnir** [comment]
Pretty sure this was cleared up some time ago. Moved Varthek a bit further down the hill anyway.
