### ISSUE TITLE
Bastion Stair Quest missing reward, and lacking parity between Destro and order 

### ISSUE THREAD

**Issue by Majorzero2123** [WarEmu/WarBugs#20732]
There is a Bastion Stair quest for both sides which do share similar steps, however they do not have similar rewards. 
**(ORDER)**
Portal of Rage - Find a clue (banner in midwing) - Talk to Wounded Knight - Talk to the Grandmaster, then return to Knight Zollner - Kill 10 brass bloodfiend and loot their skulls (kinda similiar to step 1 for destro) - Use a Quest item on Each step of ruin (the same thing for destro step 3) - Kill Kaarn the Vanquisher (exact for destro last step)
![Order1](https://user-images.githubusercontent.com/99697728/219543682-c8e496a8-4038-4c30-956a-29e993eea9dc.png)
![Order2](https://user-images.githubusercontent.com/99697728/219543704-10b8f9fd-3df0-40ca-a013-fa0118d05117.png)
![Order3](https://user-images.githubusercontent.com/99697728/219543723-576191fe-b00a-46ad-8e6d-aca3a2531c3c.png)
![order4](https://user-images.githubusercontent.com/99697728/219543791-49238b2b-b5fa-43c7-8dd1-dd515f04f751.png)
![order5](https://user-images.githubusercontent.com/99697728/219543826-cecb9b3d-991e-4e00-96cd-d24928d91bbc.png)
![Order6](https://user-images.githubusercontent.com/99697728/219543870-7a1f8729-58ec-4d44-ae5f-ea3439f614cd.png)
**(DESTRO)**
Infinite Patience - Kill 8 Brass Warfiends, 8 Brass Bloodfiends, 8 Brass Blood Seekers - Use quest item of altar of khorne - Use a quest item on each step of ruin - Kill Kaarn the Vanquisher.
![Destro1](https://user-images.githubusercontent.com/99697728/219543937-707c8f1b-f442-433a-9236-d8403c0e4935.png)
![Destro2](https://user-images.githubusercontent.com/99697728/219543969-40a8e1c5-efba-4aea-a096-b5c90faaab18.png)
![Destro3](https://user-images.githubusercontent.com/99697728/219544001-27136b4a-c86d-460b-8551-4e17086e241b.png)
![destro4](https://user-images.githubusercontent.com/99697728/219544046-5bb2c6a0-a958-471c-b28d-18e0e814bbf3.png)
The destro quest gives you the option of 6 jewerly (Cleansed Fleshborne), each share the same stats but a different bonus stat. 21 Tough, 10 wounds 60 resist to ele,corp,spirit. Ruby - %2 reduced chance to be blocked. Amber -2% reduced chance to be parried. Sapphire - %2 reduced chance to be dodged. Emerald - %2 reduced chance to be disrupted. Jet - 48 hp/4s. Diamond - 3 AP per second. The order version gives you nothing.

**Comment by Rubyeclipse-war** [comment]
This has been fixed, and the rewards for Destro are now obtainable by Order players. Will go live with the next patch!

**Comment by lilimx** [comment]
fixed with patch 17/03/2023
