### ISSUE TITLE
Karak Eight Peaks Da Deeps portal

### ISSUE THREAD

**Issue by cmodii** [WarEmu/WarBugs#20731]
The portal in 28k, 31k in Karak Eight Peaks that leads to the deeps isn't working and throwing the error "This portal's jump destination (64233704) does not exist." 

![image](https://user-images.githubusercontent.com/100476911/219452763-efaa8248-e1d9-4bb9-b30e-ca4e0f55e8cb.png)

**Comment by ekalime** [comment]
This portal does not lead to the deeps; the portal to da deeps is in the mines. This portal is at the moment purely decoration
