### ISSUE TITLE
[NoM] Night of murder - bugged trophy

### ISSUE THREAD

**Issue by dunaline** [WarEmu/WarBugs#20735]
The last reward, essence of Khaine, is not possible to equip. It says The item is stacked.
I tried redovisa all trophys but still The same result.

Puttning in a screenshot where it says i should report it to the bugtracker
![16766601790966404722807366021842](https://user-images.githubusercontent.com/119890771/219760628-c1a06f01-3583-4756-b238-05ea09478857.jpg)

**Comment by ekalime** [comment]
Thank you for giving me this ticket Lilim. It completes me. It has been fixed.

**Comment by lilimx** [comment]
Fixed with patch 24/02/2023

**Comment by dunaline** [comment]
Thank you! Looks awesome:)
