### ISSUE TITLE
[Gear] Pummelers of Treachery, incorrect icon

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#20739]
The icon for Pummelers of Treachery (Marauder gloves) shows a pair of boots rather than a pair of gloves. I did not check the in game appearance as I only saw it on the auction house

Pummelers of Treachery
https://www.returnofreckoning.com/armory/item/413853

**Comment by Rubyeclipse-war** [comment]
Fixed! One more to go...

**Comment by lilimx** [comment]
fixed with patch 17/03/2023
