### ISSUE TITLE
Ostland's Grim monastery door

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#2074]
the door to the Grim monastery in Ostland, appox. 59269 x 51094 is not openable.

**Comment by Kushido** [comment]
Door ID is missing, cant fix atm. Or if its part of the PQ, then it will not work for now.

**Comment by Shadowsmove** [comment]
It's not part of any PQ that I know of. It was able to be opened a few months ago, I remember being able to go inside for the quest line and also spent time inside farming level 20 mobs to get gear and gold. just letting you know :)
