### ISSUE TITLE
I can't play

### ISSUE THREAD

**Issue by TheKirigawa** [WarEmu/WarBugs#20742]
Yesterday i start Warhammer Online and i had no problem but today when i start the luncher i can't click on connect after this message
"Important Message!
Error: System.UnauthorizedAccessException: L'accès au chemin d'accès 'C:\Games\returnofreckoning_returnofreckoning-september2022_2022-09-14_1851\ReturnOfReckoning-September2022\Warhammer Online - Return of Reckoning\WAR-64.exe' est refusé.
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   à System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   à RoRLauncher.Client.PVUIJopFVE8n8Kgay9x(Object , FileMode , FileAccess )
   à RoRLauncher.Client.Handle(PacketIn packet)
   à RoRLauncher.Client.oRrHoApbJh10cs4DCtN(Object )
   à RoRLauncher.Client.OnReceive(PacketIn packet)
   à RoRLauncher.Client.LXdsPPpT11HXZDuKxFS(Object )
   à RoRLauncher.Client.h5sN8lttoU(Object  ) "

How can i resolve this problem ?

**Comment by lilimx** [comment]
Hey,

This is not a bug. Please use the forums or ask in our discord in #technical-advice
