### ISSUE TITLE
i cant use [Essence of Khaine]

### ISSUE THREAD

**Issue by Selguzest** [WarEmu/WarBugs#20741]
**Expected behavior and actual behavior:**
![Beyhude_012](https://user-images.githubusercontent.com/125736015/219856466-caf849ff-728b-4d9c-baa0-e11d84e75cb8.jpg)

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by NSKaneda** [comment]
Same issue, trophy has "equipped" state in description and cannot be used.

![Parszywek_010](https://user-images.githubusercontent.com/22037960/219878440-abd7c0de-f10c-47d2-8cbf-405e4ed3117b.jpg)

**Comment by GimmiMoar** [comment]
The same issue for me! Will not work in any trophy slot :(

**Comment by Zerginfestor** [comment]
Same as well, Essence of Khaine is bugged atm.

**Comment by ekalime** [comment]
Fixed it, same as [https://github.com/WarEmu/WarBugs/issues/20735](url)

**Comment by lilimx** [comment]
Fixed with patch 24/02/2023
