### ISSUE TITLE
Command .lockout does not respect the chat filters

### ISSUE THREAD

**Issue by 0xAB51NTH** [WarEmu/WarBugs#20746]
**Expected behavior and actual behavior:**
Expected behaviour:
After disabling System notice .lockout should not appear in your selected chatbox

Actual behaviour
Command .lockout ignores all filters

**Steps to reproduce the problem:**
1. type .lockout
2. disable all channels in filter
3. .lockout is still visible even tho it should not
4. you can type .lockout again to see it pop even tho nothing should pop there

**Testing Screenshots/Videos/Evidences (always needed):**
![image](https://user-images.githubusercontent.com/47013267/220177808-26644e24-954d-443c-89aa-c0f746f8780c.png)
![image](https://user-images.githubusercontent.com/47013267/220177840-45e5c160-14a6-479b-b1cc-7401b44f1987.png)
![image](https://user-images.githubusercontent.com/47013267/220177874-fa7a453f-2aa6-44b8-9f7f-014a24bb6acd.png)

**Comment by lilimx** [comment]
Hey,

that's not a bug. It's intended because it's the CSR channel where people get important messages.

**Comment by 0xAB51NTH** [comment]
Okay its understandable but its quite annoying that i cant have this disable on other chats, kinda annoying when i have wb chat and it gets spammed by bag rolls, people hitting 60+ and .lockout but if its the way it is I guess I will have to cope with it.
