### ISSUE TITLE
Not enough war crests

### ISSUE THREAD

**Issue by Meggana** [WarEmu/WarBugs#20744]
I got a bag for a keep take, and chose to accept 40 war crests as a reward. I noticed that once I clicked the add 40 war crests it only added 4 to the total amount of war crests I had.  Thought it was doing this before but wasn't positive till right before the ticket.

**Comment by lilimx** [comment]
Hey,

What was the colour of your bag?

**Comment by bosli42** [comment]
If you have more than 1k crests, the game often only shows you the first 3 digits (123x). You can check by trying to split the stack with shift+rmb.

**Comment by lilimx** [comment]
Hey,

we had a similar ticket the other day...so that's why I asked

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
