### ISSUE TITLE
[Gear] Pummelers of the Wisp, Incorrect Icon

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#20740]
The icon for Pummelers of the Wisp (Marauder gloves) shows a pair of boots rather than a pair of gloves. I did not check the in game appearance as I only saw it on the auction house.

Pummelers of the Wisp
https://www.returnofreckoning.com/armory/item/417549

**Comment by Rubyeclipse-war** [comment]
And fixed! Thank you for the reports on these items. Should be properly appearing as of the next patch.

**Comment by lilimx** [comment]
fixed with patch 17/03/2023
