### ISSUE TITLE
Player Exmachina used speedhack

### ISSUE THREAD

**Issue by Alex-der13** [WarEmu/WarBugs#20753]
I have video proof how Exmachina used speedhack.

https://youtu.be/j_O-wM9tfnw

**Expected behavior and actual behavior:**

I have video proof how Exmachina used speedhack.

**Steps to reproduce the problem:**

https://youtu.be/j_O-wM9tfnw

**Testing Screenshots/Videos/Evidences (always needed):**

[https://youtu.be/j_O-wM9tfnw](url)

**Comment by lilimx** [comment]
Hey,

please PM a GM on the discord if you see any weird player behaviour.
GMs are informed so I close this.
