### ISSUE TITLE
Can you correct this weapon?

### ISSUE THREAD

**Issue by globalgame** [WarEmu/WarBugs#20751]
The Chosen is spirit damage class it needs strength as well as SM but not weapon skill stat instead of strength,  
if possible please fix it and swap weapon skill for strength.

![CHOSEN](https://user-images.githubusercontent.com/24555848/221420187-02a47443-ad7f-4d15-a32a-42c74451ffb5.png)

SM's weapon
![SM](https://user-images.githubusercontent.com/24555848/221420309-e25219e1-5627-4789-a55e-009968ee136d.png)

https://www.returnofreckoning.com/forum/viewtopic.php?t=50222

**Comment by lilimx** [comment]
Hey,

this is the bug tracker. 
Please write a post on the forums here: https://www.returnofreckoning.com/forum/viewforum.php?f=15

**Comment by globalgame** [comment]
> Hey,
> 
> this is the bug tracker. Please write a post on the forums here: https://www.returnofreckoning.com/forum/viewforum.php?f=15

I did but Sloding said in pm to me that better make a bug issue here about it....

**Comment by lilimx** [comment]
Hey,

this is not a bug. Your request belongs to this forum: https://www.returnofreckoning.com/forum/viewforum.php?f=15
