### ISSUE TITLE
Warcrest wrong count backpack

### ISSUE THREAD

**Issue by Enwaaghman** [WarEmu/WarBugs#20758]
Hi i am uploading a video of my issue with Warcrest, is a couple of months that this is happening, but i never paid attention to it cause i thought i was immaginating it. but each time i opened a loot bag instead of having the full amount i always got from 1 to max 3. and this is the video that proves it. thank you in advance i hope it is solvable xD Have a good evening there :)

https://user-images.githubusercontent.com/19395457/222544994-a283b04f-028b-4927-99af-1524e86619d1.mp4

Edit Lilim: here is the actual report
Edit Lilim 2: I deleted 3 of the 4 videos....because all of them are the same videos

**Comment by Enwaaghman** [comment]
https://user-images.githubusercontent.com/19395457/222545288-739b1b35-e46c-48d7-b954-c518038eed9b.mp4


https://user-images.githubusercontent.com/19395457/222545298-4cdac3d2-d65d-4098-a9d2-917148c07f72.mp4

**Comment by lilimx** [comment]
Hey,

what's your account and character name?

**Comment by Enwaaghman** [comment]
Waaghy 
is a blue lootbag but it happens with all the lootbags of all colors 
and it happens with all the lootbags from keep defence and zone lock and forts. :S

**Comment by lilimx** [comment]
Hey,

In this case it's just visual. If you break your stack you can see you own 3940 war crests and not just 390.

**Comment by Enwaaghman** [comment]
Oh 😳 wow. Ok thank you ☺️

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Enwaaghman** [comment]
Thank you so so so much again!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
