### ISSUE TITLE
[NoM] Invading players still in the enemy city after the Night of Murder event has ended.

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#20765]
**Expected behavior and actual behavior:**

Expected: players should only be able to invade the enemy realm's city during the event.

Actual: even though the event is now over, enemy players who were already in the enemy city have remained there.

**Steps to reproduce the problem:**

Unknown, this is a second-hand report from seeing an order player in IC.

**Testing Screenshots/Videos/Evidences (always needed):**

This screenshot was taken on 4 March 2023.

![Zomega_041](https://user-images.githubusercontent.com/60266177/222987494-e29eb23c-533e-47b1-8009-d3df7e1a8c00.jpg)

**Comment by lilimx** [comment]
That's okay. They can't kill important NPCs. And they can get killed aswell.
