### ISSUE TITLE
Destruction players able to pick up the order quest "Grip of Darkness" in Chaos Wastes

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#20766]
**Expected behavior and actual behavior:**

This should be an order-only quest as the first objective is to speak to an order NPC ("Hewitt") in an order chapter camp. Obviously going there as destruction means death (unless you sneak in, but that's another bug report) and the NPC won't speak to you as it's orange.

**Steps to reproduce the problem:**

Interact with the "Worm's Fang" object at the mouth of the giant chaos worm corpse in Chaos Wastes on a destruction character. Location in the screenshots below.

**Testing Screenshots/Videos/Evidences (always needed):**

The quest which I have accepted on a Zealot

![image](https://user-images.githubusercontent.com/60266177/222987739-022bbb2a-83f4-488c-bff6-43517eaa5355.png)

The object that triggers the quest

![image](https://user-images.githubusercontent.com/60266177/222987773-cfadbf51-da94-4802-a32d-8abffc2485db.png)

Turn-in location (Empire chapter camp)

![image](https://user-images.githubusercontent.com/60266177/222987869-fba2a170-7eac-4d63-b4f1-2282f648b4a2.png)

Hewitt was not pleased that I had snuck in to try to advance the quest.

![Zomega_019](https://user-images.githubusercontent.com/60266177/222987936-6848e6cc-1441-48e1-98d2-28dfeb5a97d7.jpg)

**Comment by Rubyeclipse-war** [comment]
After many letters of complaint from Hewitt about his recent company, this has been fixed to be Order only. 

Will go live with next patch. Thank you!

**Comment by lilimx** [comment]
fixed with patch 17/03/2023
