### ISSUE TITLE
switch /afk chat message from client to server

### ISSUE THREAD

**Issue by bosli42** [WarEmu/WarBugs#20762]
Same as some other players, I regularly have the problem that I was still on /afk from leaving a scenario, join a new one and get kicked as soon as it starts. For some time I make sure that I un-/afk right after and now I realized the problem that was giving me (and groups) a headache.

The chat message you get in chat (You are now / no longer flagged as AFK) when using /afk is only client-based and doesn't handshake with the server. That means, once you /afk without it reaching the server (most importantly during a loading screen) the chat will start showing the opposite of now afk / no longer afk of what the server actually considers the player / client, which can only be fixed by doing it again in loading screen or relogging.

**Comment by lilimx** [comment]
Hey,

this issue has been already reported here: #20218
