### ISSUE TITLE
The tooltip on "Liniment of War: Mercy" has mismatched durations.

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#20763]
**Expected behavior and actual behavior:**

The normal part of the tooltip says the liniment lasts for 30 minutes. The "Use:" part of the tooltip says 60 minutes. Both should say 30 minutes.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/60266177/222918266-4379b543-daec-4a7f-9e56-345fabe53bc0.png)

**Comment by Zomega-WAR** [comment]
y u no fix yet?

**Comment by lilimx** [comment]
issue is still up!!!!!!!!!!!!!

**Comment by lilimx** [comment]
HOW HARD CAN IT BE?!

**Comment by lilimx** [comment]
IS IT SO HARD FOR THE DEVS?!

**Comment by Rubyeclipse-war** [comment]
> IS IT SO HARD FOR THE DEVS?!

_what heresy have you assigned to me?_

Looks like a few of these are bugged actually, probably related to new ability system. Seeing if we can fix them all up at once.

**Comment by Rubyeclipse-war** [comment]
All fixed up now, should correct the text for 4 liniments which all had a wounds buff. 

The issue was due to one of the Pie week buffs, so if the Esmeralda's Hearth pie has any issues down the road, let us know! (This should have fixed that one too, but mentioning here just in case.)

**Comment by lilimx** [comment]
Fixed with one of the latest patches
