### ISSUE TITLE
The Empire Chapter 21 PVE camp can be trivially infiltrated by destruction players.

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#20769]
**Expected behavior and actual behavior:**

Due to the huge amounts of LOS blocking objects (camp objects as well as big chaos spikes), it is trivial for destruction players to walk into the camp and if they felt like it, kill the NPCs. This is because there are very few 55 Champion guards, and those that are there have their line of sight blocked. The main Champion in the middle of the camp seems to have a relatively small aggro range.

I walked in from the ~~south/south-east~~ north/north-east direction.

**Testing Screenshots/Videos/Evidences (always needed):**

I'm in the camp, looking at a 55 Champ who is ignoring me as I'm just out of aggro range.

![image](https://user-images.githubusercontent.com/60266177/222988949-6c16e567-b98c-481b-89f7-0b2f94157376.png)

Worst screenshot ever as I was posting by an NPC for a different bug ticket. Just out of view is another 55 Champ (you can see the start of the name) who did not aggro me even though I was close, I'm assuming due to not having line of sight.

![image](https://user-images.githubusercontent.com/60266177/222989012-9eee9b6f-37c2-4731-9142-f7023577073d.png)

**Comment by lilimx** [comment]
fixed with patch 17/03/2023
