### ISSUE TITLE
Destruction players able to pick up the order quest "Bloom of Hope" in Chaos Wastes

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#20767]
**Expected behavior and actual behavior:**

I - a Zealot - was tending to the weeds around the Altar of Madness in the Chaos Wastes when I came across an uncorrupted flower. Disgusted by the sight of it, I went to pluck it out of the ground to feed it to some High Elf slaves when suddenly I was cursed with a commandment from Sigmar to take the wretched thing to a nearby Empire camp. I am not foolish enough to fall for this trickery, but I feel I should warn you of the depths the Empire will lower themselves to in order to capture servants of Tzeentch.

**Steps to reproduce the problem:**

Pluck out o... right click on the "Maiden's Hope" flower item near the Altar of Madness in Chaos Wastes (Empire chapter 22 hard PQ) to start the quest.

**Testing Screenshots/Videos/Evidences (always needed):**

The item and location on the minimap.

![image](https://user-images.githubusercontent.com/60266177/222988482-a8362059-77a3-44b9-a0c0-b437e60d2c0a.png)

On the main map, including the quest turn-in point (Empire Chapter 22 PVE camp)

![image](https://user-images.githubusercontent.com/60266177/222988516-66ac5470-6c59-4dc5-bc9f-2b2fb5c9f403.png)

**Comment by Rubyeclipse-war** [comment]
Sigmar's grace blesses all! Perhaps you are not as far from salvation as you thought. 

Alternatively, you are a heathen doomed for death and the gods missed this one.  The Cult of Sigmar has informed me that going forward, only pious Empire/High Elf/Dwarf players will be able to take this quest. 

(Thank you for the ticket!)

**Comment by lilimx** [comment]
Fixed with one of the latest patches
