### ISSUE TITLE
"Death on the Steppes - Bad Liutenants" quest still in tracker after the event has ended but I cannot complete it.

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#20776]
**Expected behavior and actual behavior:**

Expected: live event quests last for the duration of the live event.

Actual: the "Death on the Steppes - Bad Liutenants" remained in my quest log partially completed, but the NPC who issued the quest no longer exists as the event is over so I cannot complete it.

I would expect the uncompletable quests to be purged at the end of the event.

**Steps to reproduce the problem:**

Erm... forget to finish a live event and then try to complete a quest for it 6 months later?

**Testing Screenshots/Videos/Evidences (always needed):**

I cannot complete "Yako's Determination" (another bug ticket), and even if I could I cannot turn this quest into Dolgan (red quest patch) as the NPCs have now been removed.

![image](https://user-images.githubusercontent.com/60266177/222994412-bd887434-291f-4e6e-8a9b-1147e79fa87f.png)

![image](https://user-images.githubusercontent.com/60266177/222994479-56441646-a74d-4ad1-b0d9-e41ff3bd11be.png)

**Comment by lilimx** [comment]
Hey,

try next time to complete the quest.
