### ISSUE TITLE
getstats and def menu[emulator][high priority]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#2077]
after last restart def menu and .getstats command don't show correctly dodge and disrupt; i dont know(since .get stats dont show) if the renow skill are bug or it's just the command/menu that is.
Also if 0 point are spent on renown dodge/dirupt i get a red 100% on both my dodge/disrupt value
![tesq_283](https://cloud.githubusercontent.com/assets/7527415/11517921/7520076a-988d-11e5-85bf-5db0086b1556.jpg)

on my dok i had with getstat command a -3 in both dodge disrupt

EDIT: the 100% chance is real it auto dodge/disrupt anything

**Comment by ozarmidrashim** [comment]
It was a critical bug. Patched.

**Comment by Tesq** [comment]
ye thx you were really fast :)
