### ISSUE TITLE
Incorrect spawn location and wrong size/mob [emulator][npc]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#2078]
![vlodar_041](https://cloud.githubusercontent.com/assets/7527415/11518091/b2cfa128-988e-11e5-9314-f0db191e35c6.jpg)

some wrong spawn mobs
13k; 4k

**Comment by kriegersson** [comment]
Same 14k 51k, Saphery.

**Comment by DanaBloodkiss** [comment]
What is this mob?Can't find any information about him.

**Comment by DanaBloodkiss** [comment]
I will delete them till we have more information.
