### ISSUE TITLE
Potions from the "Champion of Chaos" RR80 quest decay after 30 seconds.

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#20784]
**Expected behavior and actual behavior:**

Expected: the stacks of potions from this quest should be permanent.
Actual: the potions (not the liniment crates) in the rewards window have a decay timer. When you complete the quest and get the potions, they have a decay timer in your inventry. Once the timer is up... yep they actually all decay and vanish.

**Steps to reproduce the problem:**

Buy the quest from the librarium in IC and complete it.

**Testing Screenshots/Videos/Evidences (always needed):**

Rewards in quest screen:

![image](https://user-images.githubusercontent.com/60266177/223874291-56064659-b0aa-4c8b-a161-185defb3a3d6.png)

Decaying in the backpack:

![image](https://user-images.githubusercontent.com/60266177/223874492-2ae83488-7861-4cfe-8386-4bf6b4168e02.png)

Did I actually take a screenshot of the backpack once they decayed? Of course not :/.

**Comment by Zomega-WAR** [comment]
Found this in the chat log:

![image](https://user-images.githubusercontent.com/60266177/223875919-715dacec-9f8f-4661-890f-efbe72dd8d95.png)

So there's a chance they "decayed" and just merged into my existing stacks. Still a weird bug but hopefully not as bad as first thought.

**Comment by Rubyeclipse-war** [comment]
They merged into your existing stacks. :) (Used this as a temp fix a while back as there were duplicates of this HP pot that wouldn't stack.)

I've also fixed up the HP pots within all of the RR80 quests, so all should instantly stack without any need to decay after the next patch. Thank you for spotting this!

**Comment by lilimx** [comment]
fixed with patch 17/03/2023
