### ISSUE TITLE
get booted out of SC

### ISSUE THREAD

**Issue by Magnafasul** [WarEmu/WarBugs#20782]
as per title. I wait for the SC to start. it ends in a tie before starting. I get booted out and I have 10 min deserter.

It happened a few times in a row.

![Lernia_000](https://user-images.githubusercontent.com/114529264/223727922-11b56ed9-9c3a-464c-98c8-44ddd21eb1e4.jpg)
![screenshot_000](https://user-images.githubusercontent.com/114529264/223727972-68ef6f3f-b5ab-4d3f-8a6e-07afd746327a.jpg)

**Comment by lilimx** [comment]
Hey,

Please type /afk if you were AFK for a while before you queue a SC.

**Comment by lilimx** [comment]
Hey,

but you've got flagged as afk. Just try it out. If you join afk flagged a SC, you'll get booted out of the SC.

**Comment by lilimx** [comment]
But to be sure, I will add your ticket to the first time reported one here: #20218
