### ISSUE TITLE
losing war crest from my inventory

### ISSUE THREAD

**Issue by deathgrowl666** [WarEmu/WarBugs#20787]
had around 400 and now i have 70 whats going on?i didnt spend them

**Comment by lilimx** [comment]
Hey,

I don't know. I need more information.

**Comment by deathgrowl666** [comment]
what do u mean how can i prove it ? didnt took a  screenshot how i was suppose 2 know dis will happen and take picture? m8 im old player in ror i ave no intention to take 300 crests....but why this happend?

**Comment by deathgrowl666** [comment]
i had 400 war crests and now i have much less my name ingame is Deathgrowl (blork)

**Comment by lilimx** [comment]
Hey,

I don't know what happen. So I need more information. Like when did it happen? Any lags or so?

**Comment by deathgrowl666** [comment]
today 1 hour ago no lags no dc

**Comment by deathgrowl666** [comment]
ty for the help lol
