### ISSUE TITLE
"Champion of Chaos" RR80 quest does not consume the "Tchar'zanek's Invitation" quest item

### ISSUE THREAD

**Issue by Zomega-WAR** [WarEmu/WarBugs#20783]
**Expected behavior and actual behavior:**

Expected: I purchased this item from the Records Keeper in IC to begin the RR80 quest, and when the quest was completed I expected the quest item to vanish. The RR60 and RR70 quest items vanished properly once the quest was done.

Actual: the quest is complete but the item is still in by inventory.

Note that it doesn't let you do the quest again so don't worry about it being usable as an infinite source of tokens/potions.

**Steps to reproduce the problem:**

Buy the item from Feran Mal'levil in IC, right click on it to start the quest, finish the quest and then check your quest inventory. The item is still there.

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/60266177/223873778-f707e07d-d25b-435a-a4b2-61cb9e5e2fbe.png)

**Comment by Rubyeclipse-war** [comment]
This one is by design, just in case those into the lore would like to keep a memento for dinging RR80.
