### ISSUE TITLE
Magical Salvage from Altdorf NPC Item

### ISSUE THREAD

**Issue by alyssonpaladini** [WarEmu/WarBugs#20795]
Altdorf - Veteran Renwon Gear Merchant
Character in game: "DozenMader - KOBS"
Buying Duelist's Pallium of Dominion per 15s as Salvageble item

**Steps to reproduce the problem:**
I was leveling my Magical Salvage with items I found from drops or something until I saw this item that could be salvaged at npc.
I spent almost 30 gold buying that and breaking it, I got lots "Sparkling Sanguine Ingot" and was close to 90-100 level.

When I log today... everything was gone.
My fragments... (all gold I spent on it) plus my magical salvage went to 31 only.
Im not sure whats going on because I used alot of items from my other toons to keep leveling the magic salvage and later bought those items from npc to help boost abit and got rollback at the state as if I only salvaged figurines...

Its either something wrong at the rollback happened on my magical salvage for no reason or the current item sold by npc is misleading people to spend their gold for nothing (it clearly stating its "salvageable", considering this char was only 37-38 that time, 30gold isn't something cheap.

![image](https://user-images.githubusercontent.com/101071916/225799767-a70d5fa6-4872-4999-b205-298836c55aa7.png)

**Comment by Rubyeclipse-war** [comment]
These items are intentionally given for each realm, but I don't think there was any rollback yesterday. Have you logged out and in of your character to see if it remembers your old salvaging level?

**Comment by alyssonpaladini** [comment]
Yes, thats why I thought it was strange.
Im already working my salvage back to 80+ with PQ items but if those itens are bugging out, its better to have people know, so they wont spend like 30g as I did for nothing and get delevel at skill.

**Comment by lilimx** [comment]
oki
