### ISSUE TITLE
Reik ch22 cant cleanse stager

### ISSUE THREAD

**Issue by reyaloran** [WarEmu/WarBugs#20797]
**Expected behavior**
Killing an add during the final phase should give you a spell to cleanse the 30 min stager.
**actual behavior:**
The cleanse is not working to remove the debuff. it is also persisting through death.

**Steps to reproduce the problem:**
Run ch22 reik and its a 50/50 shot per run if it triggers.

**Testing Screenshots/Videos/Evidences (always needed):**
video file corrupted and I logged out to clear it as part of the video.

**Comment by lilimx** [comment]
Hey,

could you see the bar with the cleanse button? Was it greyed out?

**Comment by lilimx** [comment]
Hey,
I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
