### ISSUE TITLE
Can't complete Event quest: "Complete Master Huntsman page"

### ISSUE THREAD

**Issue by Cohiizme** [WarEmu/WarBugs#20798]
**Expected behavior and actual behavior:**
I've completed the new Event quest "Master Huntsman page", but says I'm still missing 2 items (22/24).  I've taken screenshots to show the problem.  Thank you.

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

![Cohi_010](https://user-images.githubusercontent.com/128259350/226140142-9097b26f-3d45-484f-becf-d67398eea2d2.jpg)
![Cohi_011](https://user-images.githubusercontent.com/128259350/226140144-317851d7-f7e0-47f7-9bd4-6770fac7b051.jpg)
![Cohi_012](https://user-images.githubusercontent.com/128259350/226140146-298efbab-699e-4b87-a421-ed441774b528.jpg)
![Cohi_014](https://user-images.githubusercontent.com/128259350/226140153-be908a76-e697-441f-aeed-852c64776213.jpg)
![Cohi_013](https://user-images.githubusercontent.com/128259350/226140172-9666383b-41a6-426c-987d-c4fbe4a11f99.jpg)

**Comment by ekalime** [comment]
![Untitled](https://user-images.githubusercontent.com/91421798/226148844-eb9c19b9-e9dd-47e4-a3ca-8c74c321ed0b.png)

**Comment by Cohiizme** [comment]
Ah! Thank you! Looked like it was complete! Apology!
