### ISSUE TITLE
This PQ gives Bags Without Tokens.

### ISSUE THREAD

**Issue by Svarty1** [WarEmu/WarBugs#20790]
We did a PQ but the bags had no tokens in it.

It's in The Badlands Order side.
It was;
**Bloody Savages**
Normal difficulty
Ranks 28-29
Coordinates 54, 20

Here are pictures of the bags with no tokens in them ...

**Testing Screenshots/Videos/Evidences (always needed):**

![No Tokens](https://user-images.githubusercontent.com/113995896/224851304-762907ac-bc91-4b72-9ad0-40b391fb3d81.jpg)
![No Tokens Bina](https://user-images.githubusercontent.com/113995896/224851314-27c45017-49a0-4d8d-b379-6bae71ea3d28.png)

**Comment by Rubyeclipse-war** [comment]
Thank you for the report! 

Was able to confirm this and have made the following fixes:

- Bags from these PQs now drop War Tokens
- Crafting items from these bags are now upgraded to T3 status (they were previously bugged at t2)

We might be able to sneak this fix into the Wild Hunt patch tomorrow. You'll see it go live either then or in the patch after!

**Comment by lilimx** [comment]
fixed with patch 17/03/2023
