### ISSUE TITLE
[GB][RP] (Suspected) Non-End Bosses Major Bags only contains boots

### ISSUE THREAD

**Issue by Bjynt** [WarEmu/WarBugs#20794]
**Expected behavior:**
50/50% chance to get boots or gloves from Major/gold bags that are not from wing end bosses

**and actual behavior:**
100% chance of boots

**Steps to reproduce the problem:**
Go to GB as a RP, get major bags from minor boss (or check loot table)

**Testing Screenshots/Videos/Evidences (always needed):**
5 bags with only boots (3.13% chance), also others mentioned issues of only boots. (location/PQ of screen not related to issue, only circled bags/boots) 
![Walkmasta_005](https://user-images.githubusercontent.com/22177300/225682756-03e15677-950b-4998-b9ac-4b8440001b09.jpg)

**Comment by Rubyeclipse-war** [comment]
I just tested this on dev side, and on very first boss of left wing: 

![image](https://user-images.githubusercontent.com/60584990/225794484-e3b3eacd-727f-4c38-9c2b-9808b16c7e33.png)

Gloves seem to be appearing for me. Maybe just bad RNG?

**Comment by Rubyeclipse-war** [comment]
Just tested some more, was able to get a mix of both Runepriest Gloves and Boots from the minor boss gold bags. Will leave the report open for 2 weeks just in case anyone can confirm there's something that causes it to be only boots.

**Comment by lilimx** [comment]
Hey,
I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
