### ISSUE TITLE
Tome Entry The Key to Success not working

### ISSUE THREAD

**Issue by D4W0lf** [WarEmu/WarBugs#20792]
The Tome entry The Key to Sucess for Bloodletter of Khorne is not Working

Same as #14721

**Expected behavior and actual behavior:**

Got that needed Talisman Key from a Previous entry
if i click that chest it spawns a smaller Chest (as it should)
and if i click that one , nothing happens (it should give me a Bejeweled Skull)

**Steps to reproduce the problem:**

Click the smaller chest and don't receive the Bejeweled Skull

**Testing Screenshots/Videos/Evidences (always needed):**
![Capture d’écran_2023-03-14_12-20-49](https://user-images.githubusercontent.com/16599525/224989251-ce4767a1-70b2-4b4f-bac5-d002e5b6e1b0.png)
![Capture d’écran_2023-03-14_12-33-46](https://user-images.githubusercontent.com/16599525/224989261-36d9cb03-8e24-4dbd-85e6-7526c16fa3b5.png)
![Capture d’écran_2023-03-14_12-34-43](https://user-images.githubusercontent.com/16599525/224989265-f768fe42-4519-4d84-a6dc-b349965bd33d.png)
![Capture d’écran_2023-03-14_12-34-53](https://user-images.githubusercontent.com/16599525/224989269-9309b6a0-4314-4892-a5be-afaca27258ff.png)

**Comment by lilimx** [comment]
Hey,

check out this report #6102
