### ISSUE TITLE
Hunter's Vale - Vale Vines will not open

### ISSUE THREAD

**Issue by tog89** [WarEmu/WarBugs#20808]
**Expected behavior and actual behavior:**
Right clicking the Vale Vines at the entrance to the Hunter's Vale in Ellyrion should open the vines and allow access.

Selecting and right clicking the Vines will not open them and allow access to the Dungeon.

**Steps to reproduce the problem:**
Logged out and closed patcher, relaunched game issue persists.
/reload does not change issue.
Zoning out to another zone, flying back does not change state.
Live Event Quest to access is complete.

**Testing Screenshots/Videos/Evidences (always needed):**
![Tog_429](https://user-images.githubusercontent.com/38359697/227414988-d458eee1-bc8e-4ced-8444-e4293a7687d9.jpg)

**Comment by Rubyeclipse-war** [comment]
Just tested and seems to be working for me and everyone else nearby. Have you tried repairing the game via the launcher to see if that has any impact?

**Comment by tog89** [comment]
When the error was occurring I confirmed it with others in game.  Has resolved itself now.
