### ISSUE TITLE
Event Wild Hunt - Master Huntsman not updating

### ISSUE THREAD

**Issue by NSKaneda** [WarEmu/WarBugs#20800]
Oh! Benevolent Bug Tracker Queen, 

despite having all animals tracked, identified and killed overall task tracker does not update

**Steps to reproduce the problem:**

No idea... It's working on my other alt.

**Testing Screenshots/Videos/Evidences (always needed):**

![Ginnarr_069](https://user-images.githubusercontent.com/22037960/226211610-7aef0576-8f1a-4685-b5b2-421e1a632558.jpg)

![Ginnarr_070](https://user-images.githubusercontent.com/22037960/226211616-03096716-81fe-4a1c-8b62-0dd2dfc2ceeb.jpg)

![Ginnarr_071](https://user-images.githubusercontent.com/22037960/226211620-95531437-17cf-4f62-a85e-147bf531a4af.jpg)

If you could fix it it'd be great :)

**Comment by NSKaneda** [comment]
Possible reason for this bug: I've been having severe lag spikes whole day (1-3s delay), some entries might've not registered due to that.

**Comment by lilimx** [comment]
Hey,

You forgt one animal
