### ISSUE TITLE
Wrong Weapon for Blackguard T3 RVR Saphery & Avelorn

### ISSUE THREAD

**Issue by Hauclir** [WarEmu/WarBugs#2081]
Ghrond's Glaive is incorrect it should be Ghrond's Xiphos

http://www.arsenalofwar.com/items/Destruction/Ghrond's%20Xiphos

**Comment by Hauclir** [comment]
I notice Ghrond's Xiphos was given to the Disciple of Khaine class without the magic proc and I remember having Ghrond's Xiphos on my Blackguard on live. Now I'm wondering if the live version was the one that is wrong and you guys have the correct items in place.

**Comment by Evildoor** [comment]
No item procs are implemented yet.
