### ISSUE TITLE
Sneaky Git Tactic

### ISSUE THREAD

**Issue by alexbm** [WarEmu/WarBugs#20810]
**Expected behavior and actual behavior:**
When you cast a squig in "squig armor" and you have this tactic "squig armor" is removed.

**Steps to reproduce the problem:**
use this tactick while you are in squig armor and cast any squig.

**Testing Screenshots/Videos/Evidences (always needed):**

![Captura desde 2023-03-24 18-08-11](https://user-images.githubusercontent.com/2683398/227594509-a984bd45-8902-4a86-b2f1-2270e2324796.png)
![Captura desde 2023-03-24 18-08-36](https://user-images.githubusercontent.com/2683398/227594779-c8d2a2d9-0234-4a5c-8c4e-70de37b9fed3.png)
![Captura desde 2023-03-24 18-08-43](https://user-images.githubusercontent.com/2683398/227594829-7d30970e-eb3d-4cad-a4b3-bb8dcfa9514d.png)

**Comment by lilimx** [comment]
Hey,

thank you for your ticket. This isse has already been reported here: #18439
