### ISSUE TITLE
Stalkers braces talisman

### ISSUE THREAD

**Issue by Fortwunty** [WarEmu/WarBugs#2082]
Currently unable to attach any talisman except a very low level to my Stalker's braces. Not sure what the problem is.

**Comment by Meralors** [comment]
I don't think its a database problem. I was able to add talisman to this item without problem.

**Comment by Fortwunty** [comment]
Well then it must me just me because I can only add low leveled talisman to mine. I bought the Devastator now so I'm not concerned with it.

**Comment by Evildoor** [comment]
Closing since this looks like a one-time bug.
