### ISSUE TITLE
Squig Herder Pet BUG

### ISSUE THREAD

**Issue by LarkinRepositories** [WarEmu/WarBugs#20822]
After the patch 30/3/2023 pets on both SH and WL are bugged: you stuck on pet animation trying to summon the pet, AP goes to zero and character is unable to perform any actions.
Video: https://www.youtube.com/watch?v=HPQfTDe8jH0

**Comment by Zomega-WAR** [comment]
Video unavailable
This video has been removed by the uploader

**Comment by lilimx** [comment]
Jupp, video still unavailable.

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
