### ISSUE TITLE
White Lion Throat Bite - Skill Cannot be Purchased

### ISSUE THREAD

**Issue by Narancse** [WarEmu/WarBugs#20820]
**Expected behavior and actual behavior:**
Expected behavior:
step 1:Spend Mastery Points to unlock - Throat Bite skill in Path of The Guardian 
step 2:Gain Throat Bite skill
Actual Behavior:
step 1:Spend Mastery Points to unlock - Throat Bite skill in Path of The Guardian 
result: Skill does not show up in the abbilities window or on the toolbar, mastery point is spent.
**Steps to reproduce the problem:**
Spec for Throat Bite skill in Path of The Guardian 

**Testing Screenshots/Videos/Evidences (always needed):**
(https://youtu.be/tL_zXtwB0zI)

**Comment by lilimx** [comment]
Hey,

Throat Bite is locked until you get lvl 35.
check out the RoR builder here: https://builder.returnofreckoning.com/career/white-lion
