### ISSUE TITLE
White Lion summon pet does not finish.

### ISSUE THREAD

**Issue by 10pennynail** [WarEmu/WarBugs#20821]
Expected behaviour: Summoning Lion makes Lion appear.

I tried it once, others in chat confirmed. It locks up portions of UI, and drains AP. Character unplayable, and can't log out normally due to casting preventing logging.

**Comment by Paldyy** [comment]
" NullReferenceException was thrown from .ctor. " is the system message we get

**Comment by 10pennynail** [comment]
![Spring_000](https://user-images.githubusercontent.com/29387702/228854678-a5db9e81-e5b4-4c0f-b461-37f5096d6b91.jpg)
![Spring_001](https://user-images.githubusercontent.com/29387702/228854760-509773e4-d36c-431c-9154-fd6ab36e0ce9.jpg)

**Comment by lilimx** [comment]
I think this was fixed with one of the restarts on 30/3/2023
