### ISSUE TITLE
BO - Ya missed me - Not workin

### ISSUE THREAD

**Issue by funnytroll** [WarEmu/WarBugs#20826]
Ya missed dont apply damage debuff for target
Here two screenshots one with skill description another how it show on target
https://imgur.com/a/BJ4zGnb
It literally not reduce damage,in getstats no any word about damage reduce and we test it on mara skills before and after apply debuff numbers was the same.

**Comment by lilimx** [comment]
Hey,

could you add the pic of .getstats and a proper report what you did?
Btw. you can drag and drop pics here, so no need to host it somewhere else.

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
