### ISSUE TITLE
Battle for Praag - Fall through floor bug in destro spawn

### ISSUE THREAD

**Issue by X3hl** [WarEmu/WarBugs#20831]
Loaded into the Battle for Praag scenario, ran forward a few feet and stopped and then the character fell through the floor and eventually died.

Respawned back in the spawn, again ran forward a few feet and fell through the floor after mounting up. This repeated on a couple of occasions.

I haven't encountered it before so was potentially something unique with that session or maybe just unique to the area I was standing (half way between the corrupted tree and the warcamp guards). The other members of the scenario party seemed unaffected which again would suggest a session issue rather than an environmental one.

Link to the clip on twitch: https://www.twitch.tv/xehl_/clip/SuccessfulSingleFishPogChamp-t2LmqVnNU1ZPu4mQ

Link to the Vod of the stream on youtube (twitch removes videos after a while): https://youtu.be/5K-6D6YyHAM (issue can be seen at 2:03:12 until 2:06:54 when the game kicked me back to the rvr lake.

screenshots:
[Fallen through]
![image](https://user-images.githubusercontent.com/130108466/230506730-80732620-3355-4eb0-8bc3-3f2aab220d63.png)

[2nd time falling through, general area effected]
![image](https://user-images.githubusercontent.com/130108466/230506803-f30b5ee0-6b37-4cc4-94d6-e601cc85a849.png)

**Comment by MaxHayman** [comment]
Should be fixed. Please reopen if that is not the case.
