### ISSUE TITLE
Just 1 profession

### ISSUE THREAD

**Issue by Zaccar20** [WarEmu/WarBugs#2083]
After respec professions i just can learn 1 crafting skill.
I already try to respec again but i can just lern again 1 prefession!

Elvo is the Name of this Char.
Before i have Cultivating & Apothecery

**Comment by nalgol** [comment]
you can only learn 1 crafting and 1 gathering profession what are you trying to get now?

**Comment by Evildoor** [comment]
No response to nalgol's question, closing.
