### ISSUE TITLE
Missing Gear and Currency when loading in today

### ISSUE THREAD

**Issue by Evaldis** [WarEmu/WarBugs#20838]
Today when logging in, I noticed that my character was naked at the login screen. When I loaded in, the Keeper's set, the coin from the quest and all of the gear I got from running sewers the night before was gone.

**Expected behavior and actual behavior:**
I have no idea why the gear would vanish.

**Steps to reproduce the problem:**
Tried restarting and rebooting pc.

**Testing Screenshots/Videos/Evidences (always needed):**

![Screenshot (9)](https://user-images.githubusercontent.com/130312649/230792514-67966e98-e855-4d83-ba42-2b77b254d8cc.png)

**Comment by Majorzero2123** [comment]
Hey, post in this forum: https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=50661
