### ISSUE TITLE
Reikland Factory SC - Fell through map multiple times (Order side)

### ISSUE THREAD

**Issue by skael1984** [WarEmu/WarBugs#20835]
**Expected behavior and actual behavior:**

Not falling through map and dying - falling through map and dying

**Steps to reproduce the problem:**

leaving order spawn at certain points, standing still too long in order spawn. heading up order side of map towards closest flag, (i was able to leave order spawn to the far left, and head to the destro side door and actually got to the flag, at which point i fell through the map again)

**Testing Screenshots/Videos/Evidences (always needed):**

https://youtu.be/j41RdA0dMfo -- i only started recording after id fallen through the map several times

**Comment by Zomega-WAR** [comment]
For what it's worth, it looks like you're actually being teleported out of the main map area into an area where nothing exists ("Zone 0" on the minimap) rather than falling through the area you were in.

No idea what would cause it, just clarifying what's going on.

**Comment by lilimx** [comment]
related to #20831

**Comment by MaxHayman** [comment]
Should be fixed. Please reopen if that is not the case.
