### ISSUE TITLE
order getting slow immunity

### ISSUE THREAD

**Issue by bulgy70** [WarEmu/WarBugs#20842]
order getting slow immunity

The following videos show that order are getting immunity from slows, 
Video 1 shows the WP getting immunity from Crippling Anger at 27 seconds
https://www.youtube.com/watch?v=AwyoK-dKVSk

Video 2 shows the WH getting immunity from Crippling Anger at 26 seconds 
https://www.youtube.com/watch?v=sMJ8m4CFInk

The folowing bug report was closed for the reason that slow doesnt give any immunity
https://github.com/WarEmu/WarBugs/issues/20697

**Comment by Zomega-WAR** [comment]
Video 1: The Warrior Priest used the Focused Mind ability which ignores snares.
Video 2: The Witch Hunter used the Sheild of Sigmar which ignores snares.
The other ticket: you misunderstood the comment

If you are snared then you can keep being snared over and over. This is different to roots, silences, etc, where once the original effect ends you are automatically granted immunity from being rooted/silenced again for a certain period of time. Snares do not have this automatic immunity, however there are some abilities in the game which can make a player immune to snares for the duration of that ability.

The two videos you posted showed players using their snare break/snare immunity abilities.

**Comment by lilimx** [comment]
Yupp, case closed.
