### ISSUE TITLE
Missing alot of war crest

### ISSUE THREAD

**Issue by stateofwtf** [WarEmu/WarBugs#20849]
Missing hundreds of war crest altogether. Unfortunately i can not record proof of all of that because thats up too much disk space. I do have video proof of some of the lost crest. https://youtu.be/JbGmjdAoLVM 

**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
As expected....it was just a visual bug.
