### ISSUE TITLE
Wurrzag Ud Ura Zahuhu not showing Eastern Wyvern Hunt event earnings

### ISSUE THREAD

**Issue by pthiel168** [WarEmu/WarBugs#20843]
Wurrzag does not show the option to obtain the live event earnings"

![image](https://user-images.githubusercontent.com/8930990/231480411-4114385d-26a3-4ce4-a753-24c696dbbc31.png)

**Comment by Portense** [comment]
![image](https://user-images.githubusercontent.com/53801109/231491258-243d1434-5df8-4bec-8bec-f29cf08fe2c8.png)
same problem for me. only on one character and accepting the quests does not fix it

**Comment by lilimx** [comment]
That's intended. Because if you read the text, it says:
"CAUTION: THIS WILL BLOCK THE HERALD"

**Comment by ekalime** [comment]
The npc next to him 'Wurzzag's ssistant' had a quest that blocked Wurrzag's quests, and it said 'CAUTION: TAKING THIS QUEST WILL UNLOCK QUESTS THAT BLOCK THE HERALD FUNCTION' - and it appears you both took that quest and blocked the herald. You can simply take his quests and do them, they are about 4 minutes of work going down to the sublevel.

**Comment by pthiel168** [comment]
Not to argue but I do not have a quest from the assistant and have not even seen where I could have taken one. If I did I do not see it in my quest log, unless taking it on a different character would have impacted it:
















---- On Wed, 12 Apr 2023 17:05:48 -0400 ekalime ***@***.***> wrote ---





The npc next to him 'Wurzzag's ssistant' had a quest that blocked Wurrzag's quests, and it said 'CAUTION: TAKING THIS QUEST WILL UNLOCK QUESTS THAT BLOCK THE HERALD FUNCTION' - and it appears you both took that quest and blocked the herald. You can simply take his quests and do them, they are about 4 minutes of work going down to the sublevel.
