### ISSUE TITLE
[Scenario] Tor Anroc lava damage is too low.

### ISSUE THREAD

**Issue by Tidybraveguinea** [WarEmu/WarBugs#2084]
The damage is way too little. As far as I remember it was about 2k unmitigatable damage per second on live. Lava also used to slow a target (20% snare?) Right now it slows for a moment but then stops slowing.

**Comment by Evildoor** [comment]
2k in T3? Or in T4?

**Comment by Tidybraveguinea** [comment]
t4. It could be % health damage so fat tanks wouldn't walk over lava.

**Comment by Evildoor** [comment]
Well, but we are not in T4 yet, right? So isn't it logical that it is less than 2k? Health % damage is quite possible.

**Comment by Tidybraveguinea** [comment]
We're almost in t4. And the lava damage is way too low even for t3. Healers can even stay in lava while healing themselves, being protected from melee by it.

**Comment by ozarmidrashim** [comment]
Also fixed a related issue allowing some types of unmitigable damage, including lava, to be split by Guard.
