### ISSUE TITLE
Sword Master Morale Wings of Heaven

### ISSUE THREAD

**Issue by bulgy70** [WarEmu/WarBugs#20841]
Sword Master Morale Wings of Heaven

Sword Master Morale Wings of Heaven is ignoring the high level restrictions, which limits this ability.

Was reporterd and was closed without a fix
https://github.com/WarEmu/WarBugs/issues/20681

More video which shows this is still happening
https://www.youtube.com/watch?v=L_ivQ9qhUiE

**Comment by Zomega-WAR** [comment]
The ticket you linked has not been closed.

**Comment by lilimx** [comment]
Dublicate
