### ISSUE TITLE
Impossible to buy Fortress Runestaff

### ISSUE THREAD

**Issue by Boda-ror** [WarEmu/WarBugs#20851]
I have the "Hammerstaf of the Subjugator", 100 gold and 1 600 war crest but I cannot buy the "Fortress Runestaff" as you can see in the screenshots on my character called "Bodoc" a Runepriest on my account "sorfiniel".
![Fortress runestaff](https://user-images.githubusercontent.com/61795541/232207963-4bd2913d-0e8a-4a40-84c5-f39b5730abc4.png)
![Fortress runestaff_1600warcrest](https://user-images.githubusercontent.com/61795541/232207970-5cc772d4-780c-4204-b64f-ede7a7d88eb4.png)

**Comment by lilimx** [comment]
Hey,

Do get any error in your chat?

**Comment by lilimx** [comment]
Additional question, do you have the required ward?

**Comment by Boda-ror** [comment]
Correct, fortress weapon needs the "Invader tome unlocked" I did not activated error messages, so now I see this. Issue solved

**Comment by lilimx** [comment]
Nice!
