### ISSUE TITLE
Fleet Stag Mantle: No charges left

### ISSUE THREAD

**Issue by wildwindblows** [WarEmu/WarBugs#20854]
Hello,
Fleet Stag Mantle cannot transform into stag. It gives error as "No charges left".

![Hitmachine_055](https://user-images.githubusercontent.com/45720515/232337195-f3cdd844-8942-4783-9be3-cddf1b934c2f.jpg)

Bests.

**Comment by Zomega-WAR** [comment]
It only has 50 (IIRC) charges. If the number of charges is not showing up on the item then that is the bug.

**Comment by wildwindblows** [comment]
Thanks Zomega-WAR, I may use all charges and this might be a reason. Therefore I'm closing this.
