### ISSUE TITLE
Killboard does not get updated properly for all of my characters

### ISSUE THREAD

**Issue by wappla123** [WarEmu/WarBugs#20859]
The Killboard does not get updated properly. I just checked the scoreboard of the last few scenarios (Talabed Dam) and the deaths are getting counted but the death blows arent (I had 6 death blows in one scenario and none got counted). I also got this issue on another character. I just checked the numbers and they don´t add up to the counter on top of the tables.

**Comment by Zomega-WAR** [comment]
The killboard attributes the kill to the person who did the most damage, not who got the killing blow.
