### ISSUE TITLE
[Quest]: A darker Treat

### ISSUE THREAD

**Issue by Heteryk** [WarEmu/WarBugs#2085]
Something is missing
![rahgal_051](https://cloud.githubusercontent.com/assets/16116091/11528591/16658046-98e8-11e5-82c8-a2b7b1afe665.jpg)
![rahgal_052](https://cloud.githubusercontent.com/assets/16116091/11528597/1c752e8c-98e8-11e5-82cc-2aec7514a855.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
