### ISSUE TITLE
Lost items 

### ISSUE THREAD

**Issue by Daveleo6** [WarEmu/WarBugs#20852]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by Daveleo6** [comment]
I just bought 3 rings from AH witch cost me over 450 gold and there not in the mail , need help

**Comment by Esharadon** [comment]
hello, i loged today - knight-toon was"naked" on characterscreen - when i loged in i had a redeyechest in my bag but the vanquisherchest i had equiped, is gone. pls help ty

**Comment by Daveleo6** [comment]
the rings were called Dark Band of the Fleshrender

**Comment by lilimx** [comment]
@Daveleo6 and your chars are?

**Comment by Daveleo6** [comment]
Achilies , destro

**Comment by MaxHayman** [comment]
Seems there was an issue with the mail server for a few minutes. Should be resolved now. If you have any more questions feel free to pm me on discord MaxHayman#8344. Thank you.

**Comment by Daveleo6** [comment]
Still nothing in the mail

**Comment by Daveleo6** [comment]
ok thank you MaxHayman , i got them :)
