### ISSUE TITLE
Missing "Back To The Front!" quest giver NPC

### ISSUE THREAD

**Issue by LawlrusTheWalrus** [WarEmu/WarBugs#20861]
**Expected behavior and actual behavior:**
The "Back To The Front!" quest leads you to believe the quest giver NPC called "Raven's Chieftain" is in Talabecland, Hellfang Ridge War Camp, but it does not appear to be there at all. In fact, when you get there, the orange, completed quest indicator is nowhere in the camp at all.

**Steps to reproduce the problem:**
"Back To The Front!" quest

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://user-images.githubusercontent.com/13711678/233791334-988f21af-7f0d-4ca3-91ac-2dc5359a9b86.png)
![image](https://user-images.githubusercontent.com/13711678/233791340-99273631-71ea-447c-977a-dccb67f98afd.png)

**Comment by Majorzero2123** [comment]
Hey, after some further inspection on the quest, this quest was a limited time quest from Return of Reckonings 3rd anniversary, as well as the currency the quest awards you. Thank you for the ticket, and welcome back.
