### ISSUE TITLE
Tome of Knowledge "Manbane" unlock in Chrace interactable missing

### ISSUE THREAD

**Issue by Varnarok** [WarEmu/WarBugs#20869]
**Expected behavior and actual behavior:**
Expected behaviour: Go up on small hill across the river from Thanuil's Retreat, find Manbane plant to interact with and unlock Manbane ToK entry.

Actual behaviour: Upon climbing the hill, there is no interactable there. (Seems to be part of larger zone/game wide problem of interactable world objects being missing following a recent patch)

**Steps to reproduce the problem:**
N/A

**Testing Screenshots/Videos/Evidences (always needed):**

![Manbane codex unlock](https://user-images.githubusercontent.com/4006687/234012666-04e5b271-f69f-4e5e-a3ab-852d6aa48c99.png)

**Comment by lilimx** [comment]
This has been fixed with patch 29/05/2023
