### ISSUE TITLE
T1 Dark Elf Epic "Legend and Infamy" Dreadblight Sorceress corpse missing

### ISSUE THREAD

**Issue by Varnarok** [WarEmu/WarBugs#20864]
**Expected behavior and actual behavior:**
Expected behaviour: Find Dreadblight Sorceress corpse around 17k,15k in Chrace, click on it and advance quest to nearby chapter 4 camp.

Actual behaviour: No corpse to be found anywhere inside red quest marker area or nearby outside of it. Abandoning and reacquiring quest did not fix. 

**Steps to reproduce the problem:**
N/A. 

**Testing Screenshots/Videos/Evidences (always needed):**

![Legend and Infamy](https://user-images.githubusercontent.com/4006687/233859455-36a0d87a-7717-496d-9115-92c40085e354.png)

**Comment by Majorzero2123** [comment]
Hey, thanks for the ticket! A fix for this is currently on dev, and should go live with the next patch.

**Comment by Varnarok** [comment]
I've noticed that the spike in the middle of the Dark Elf chapter 4 camp, Malagurn's Charge, is also missing. This is required later on in this same questline when you have to kill and mount Haydion Whitewrath's head there.

Several other non-quest related interactable world items also seem to be missing from this zone, including the wobbling barrels containing goblins found at 20.5k, 46,7k., the dark elf magic discs (forget their name) on the altars in front of the menhir stones in the Stone of Valetear PQ, as well as the one inside the Tor Achare PQ being guarded by 4 Hoeth Magi, and several other items around the zone. Having looked at other recent issues, it seems to be part of a larger problem.

**Comment by Svarty1** [comment]
> I've noticed that the spike in the middle of the Dark Elf chapter 4 camp, Malagurn's Charge, is also missing. This is required later on in this same questline when you have to kill and mount Haydion Whitewrath's head there.
> 
> Several other non-quest related interactable world items also seem to be missing from this zone, including the wobbling barrels containing goblins found at 20.5k, 46,7k., the dark elf magic discs (forget their name) on the altars in front of the menhir stones in the Stone of Valetear PQ, as well as the one inside the Tor Achare PQ being guarded by 4 Hoeth Magi, and several other items around the zone. Having looked at other recent issues, it seems to be part of a larger problem.

Do we need to submit each of these as a separate issue?

**Comment by Ladgahr** [comment]
The issue seems to be fixed with today's patch. The sorceress' body is present.

**Comment by Svarty1** [comment]
I completed this one today! 
... also a quest to collect amulets off corpses in another location,
... and a mission to put three heads on a spike. 
All of these had interactables missing before today.

**Comment by lilimx** [comment]
This has been fixed with patch 29/05/2023
