### ISSUE TITLE
Destruction Chrace quest "Call of the Hunt" missing Sharpened Spike interactable 

### ISSUE THREAD

**Issue by Varnarok** [WarEmu/WarBugs#20868]
**Expected behavior and actual behavior:**
Expected behaviour: Enter Tor Achare right next to chapter 4 Dark Elf camp, kill Belthain Oakenshaft, loot his head as a quest item and then place his head on Sharpened Spike interactable.

Actual behaviour: Belthain Oakshaft spawns fine but after getting his head as a quest item, there are no Sharpened Spike interactables upon which to impale it for the second quest objective.

**Steps to reproduce the problem:**
N/A

**Testing Screenshots/Videos/Evidences (always needed):**

![Call of the Hunt](https://user-images.githubusercontent.com/4006687/234002144-cec9002e-5fd1-4d95-a684-e89db5ba5130.png)

**Comment by Majorzero2123** [comment]
Hey, thanks for the ticket! A fix for this is currently on dev, and should go live with the next patch.

**Comment by Ladgahr** [comment]
It seems to be fixed. The spikes are present. I was able to finish this quest.

**Comment by lilimx** [comment]
This has been fixed with patch 29/05/2023
