### ISSUE TITLE
[Epic Quest] Dark Elf T2 "A Lords' Game" Step 18 broken. Unable to progress.

### ISSUE THREAD

**Issue by Xaratheth** [WarEmu/WarBugs#20860]
Step 18 of the T2 Dark Elf Epic Quest "A Lords' Game" requires the Player to "Pike Evriels's head on the Sharpened Pike inside the camp." But the pike is nowhere to be found. Asked many other players and they "swore" it was there a few months ago.

**Expected behavior and actual behavior:**
Expected the pike to be inside the marked zone like the Quest says.
Actually, there's no pike to be found inside the zone and even beyond after searching with 6 other players.

**Steps to reproduce the problem:**
Just reach Step 18 of the Quest, tried it on other Characters, same result.

**Testing Screenshots/Videos/Evidences (always needed):**
![bug](https://user-images.githubusercontent.com/131527812/233781056-7b867cf4-62b4-4d20-9d49-652477968a6a.jpg)

Thank you for your time reading this!

**Comment by Lheana** [comment]
Thanks for your report. This will be fixed with next patch.

**Comment by NaNuKa-black** [comment]
I am also having same problem. When will this problem be resolved?

**Comment by lilimx** [comment]
Fixed with Patch 18/05/2023
