### ISSUE TITLE
MIssing War Crest

### ISSUE THREAD

**Issue by bezlikiy87** [WarEmu/WarBugs#20866]
Today, after downloading an update (event for the weekend), I logged to the character Bezlikaya and found that about 7000 war crests were missing but I can't provide any screenshots of the previous amount of crests.
Сharacter: Bezlikaya
Renown Rank: 82

**Comment by bezlikiy87** [comment]
For understanding, there will be feedback or the ticket is not considered? Thank you)

**Comment by lilimx** [comment]
Hey,

looks like you are the only one. Maybe it was a visual bug.
Please note, we have a general policy of not restoring losses that occur due to issues.
