### ISSUE TITLE
[Quest]: Thunderdust

### ISSUE THREAD

**Issue by Heteryk** [WarEmu/WarBugs#2086]
Clicking on NPC doesn't trigger quest finale.
![rahgal_053](https://cloud.githubusercontent.com/assets/16116091/11528630/46f148b2-98e8-11e5-8841-3b60ec37e431.jpg)
![rahgal_054](https://cloud.githubusercontent.com/assets/16116091/11528638/52458228-98e8-11e5-84e7-5b40826cb53f.jpg)
![rahgal_055](https://cloud.githubusercontent.com/assets/16116091/11528665/80739270-98e8-11e5-9f35-589683b0aaf5.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by wargrimnir** [comment]
Broken Items
http://war.mmodb.com/items/mane-of-grudgeborn-fury-97591.php
+24 STR
+10 TGH
+8 WND
id 40744

http://war.mmodb.com/items/maximilions-mane-109915.php
+29 WS
+12 WND
id 510222

**Comment by wargrimnir** [comment]
Fixed stats on these sets.
