### ISSUE TITLE
Destruction Chrace quest "Treachery of Kin" House Arkaneth corpses missing

### ISSUE THREAD

**Issue by Varnarok** [WarEmu/WarBugs#20867]
**Expected behavior and actual behavior:**
Expected behaviour: Enter designated quest area around 29.5k, 48.5k in Chrace, find corpses of House Arkaneth warriors, loot 5 Arkaneth Crests and then report to Hartha in Shadowlands for turnin.

Actual behaviour: No corpses to be found anywhere inside or around red designated quest area. 

**Steps to reproduce the problem:**
N/A

**Testing Screenshots/Videos/Evidences (always needed):**

![Treachery of Kin](https://user-images.githubusercontent.com/4006687/233997022-cb311b32-1320-4f78-a120-41066513b37b.png)

**Comment by Majorzero2123** [comment]
Hey, thanks for the ticket! A fix for this is currently on dev, and should go live with the next patch.

**Comment by lilimx** [comment]
This has been fixed with patch 29/05/2023
