### ISSUE TITLE
Quest issue: Echoes of the past

### ISSUE THREAD

**Issue by RhysScurlock** [WarEmu/WarBugs#20865]
**Expected behavior and actual behavior:**
The quest requires talking to four orbs in order, the "Orb of Menlui" is missing.

![Bul_001](https://user-images.githubusercontent.com/131617764/233862155-b508a84c-5de6-4001-b254-fea549674b6b.jpg)

**Comment by Majorzero2123** [comment]
Hey, thanks for the ticket! A fix for this is currently on dev, and should go live with the next patch.
