### ISSUE TITLE
Destruction Troll Country quest "Savoring Conquest" missing Order of the Griffon corpses

### ISSUE THREAD

**Issue by Varnarok** [WarEmu/WarBugs#20872]
**Expected behavior and actual behavior:**
Expected behaviour: Go to the Plague Graves at 44.7k, 48k in Troll Country, click corpses of empire soldiers, receive 12 Decaying Heart quest items, return to Sheilv Kumari in the chapter 7 Chaos camp.

Actual behaviour: No Decaying Hearts can be gathered due to no Order of the Griffon corpses can be found near Plague Graves.

**Steps to reproduce the problem:**
N/A

**Testing Screenshots/Videos/Evidences (always needed):**

![Savoring Conquest](https://user-images.githubusercontent.com/4006687/234378532-d2b0c60a-a8f9-4126-b4c5-fb6083ef5cb5.png)

**Comment by Majorzero2123** [comment]
Thank you for the ticket, a fix is currently on dev, and will be available next patch.

**Comment by lilimx** [comment]
This has been fixed with patch 29/05/2023
