### ISSUE TITLE
Destruction Troll Country quest "The Exalted One" missing chest interactable

### ISSUE THREAD

**Issue by Varnarok** [WarEmu/WarBugs#20873]
**Expected behavior and actual behavior:**
Expected behaviour: Talk to Larz the Incarnate outside the Chaos chapter 8 camp, accept quest, click chest next to Larz, finish quest.

Actual behaviour: There is no chest next to Larz to click.

**Steps to reproduce the problem:**
N/A

**Testing Screenshots/Videos/Evidences (always needed):**

![The Exalted One](https://user-images.githubusercontent.com/4006687/234394813-fd47d5c1-746e-4814-a3a0-a9a322346f38.png)

**Comment by Majorzero2123** [comment]
Thank you for the ticket, a fix is currently on dev, and will be available next patch.

**Comment by lilimx** [comment]
This has been fixed with patch 29/05/2023
