### ISSUE TITLE
Destruction Troll Country quest "Chosen" missing Acid Burned Corpse interactable

### ISSUE THREAD

**Issue by Varnarok** [WarEmu/WarBugs#20874]
**Expected behavior and actual behavior:**
Expected behaviour: After picking up the quest, head to the "Lursa's Blight" PQ, look for Acid Burned Corpse within the red marked quest area, complete quest and advance to the next.

Actual behaviour: There is no Acid Burned Corpse present within the red marked quest area, making the quest incompletable.

**Steps to reproduce the problem:**
N/A

**Testing Screenshots/Videos/Evidences (always needed):**

![Chosen](https://user-images.githubusercontent.com/4006687/234552886-e51a588d-8d53-4dc8-9398-e7dca2dd7cf5.png)

**Comment by Majorzero2123** [comment]
Thank you for the ticket, a fix is currently on dev, and will be available next patch.

**Comment by lilimx** [comment]
This has been fixed with patch 29/05/2023
