### ISSUE TITLE
Destruction Ostland quest "Temptress" missing Wayshrine world object

### ISSUE THREAD

**Issue by Varnarok** [WarEmu/WarBugs#20870]
**Expected behavior and actual behavior:**
Expected behaviour: Travel to quest area at approx. 41.5k, 15 in Ostland, destroy the Hochnar Sigmarite Wayshrine next to corpse related to previous step in questline, turn in quest with Sheilv Kumari at Chaos chapter 7 camp.

Actual behaviour: No Sigmarite Wayshrine within or near red marked quest area to complete quest objective.

**Steps to reproduce the problem:**
N/A

**Testing Screenshots/Videos/Evidences (always needed):**

![Temptress](https://user-images.githubusercontent.com/4006687/234340928-1efcb017-0878-42a9-b190-68236db8ef40.png)

**Comment by Majorzero2123** [comment]
Thank you for the ticket, a fix is currently on dev, and will be available next patch.

**Comment by lilimx** [comment]
This has been fixed with patch 29/05/2023
