### ISSUE TITLE
Destruction Ostland quest "Hand of Glory" missing Sacristy Candle chest interactable

### ISSUE THREAD

**Issue by Varnarok** [WarEmu/WarBugs#20871]
**Expected behavior and actual behavior:**
Expected behaviour: Travel to the Kinschel's Stronghold battlefield objective in the Ostland RvR lake, find and interact with a chest containing a Sacristy Candle quest item.

Actual behaviour: No chest containing quest item to be found within red marked quest area.

**Steps to reproduce the problem:**
N/A

**Testing Screenshots/Videos/Evidences (always needed):**

![Hand of Glory](https://user-images.githubusercontent.com/4006687/234342824-45fd9569-1b49-42ce-bd6d-8eb80cdff64a.png)

**Comment by Majorzero2123** [comment]
Thank you for the ticket, a fix is currently on dev, and will be available next patch.

**Comment by lilimx** [comment]
This has been fixed with patch 29/05/2023
