### ISSUE TITLE
[Quest]: The Forgotten

### ISSUE THREAD

**Issue by Heteryk** [WarEmu/WarBugs#2087]
Clicking on remains doesn't give you clan insygnia.
![rahgal_056](https://cloud.githubusercontent.com/assets/16116091/11528686/9ae2786a-98e8-11e5-9681-710d3e08ccae.jpg)

**Comment by Meralors** [comment]
Fixed, live next patch.

**Comment by wargrimnir** [comment]
Quest area is R25, rewards for the quest are a green R10 Ballistics potion and a green R35 Intelligence potion, they don't seem to be linked to class at all, so the rewards are useless for any melee class. A 25 STR/INT/WIL/BAL potion selection would be great.

**Comment by sioding** [comment]
Fixed with patch from 2.2.2018
