### ISSUE TITLE
Destruction Troll Country quest "Dangerous Assumptions" missing Stone Moss/Bitter Root interactables

### ISSUE THREAD

**Issue by Varnarok** [WarEmu/WarBugs#20875]
**Expected behavior and actual behavior:**
Expected behaviour: After picking up the quest, head to the "Plaguewood Thicket" PQ in Troll Country to acquire quest items: 5 Stone Moss, 3 Bitter Root and 1 Raven's Blood from Injured Warrior NPC. Then find the Plaguewood Oak nearby to finish the quest.

Actual behaviour: The Injured Warrior required for Raven's Blood is present but the Stone Moss and Bitter Root world objects are nowhere to be found.

**Steps to reproduce the problem:**
N/A

**Testing Screenshots/Videos/Evidences (always needed):**

![Dangerous Assumptions](https://user-images.githubusercontent.com/4006687/234557036-396f4208-6e7f-4a88-a279-259ec0cee38d.png)

**Comment by Majorzero2123** [comment]
Thank you for the ticket, a fix is currently on dev, and will be available next patch.

**Comment by Ladgahr** [comment]
After the patch stones and roots have returned. I managed to complete this quest.
