### ISSUE TITLE
Destruction Shadowlands quest "Lighting the Way" missing high elf tent interactables

### ISSUE THREAD

**Issue by Varnarok** [WarEmu/WarBugs#20881]
**Expected behavior and actual behavior:**
Expected behaviour: After reaching the designated quest area around 22.7k, 3.8k, find 3 high elf tents to hex, then use the Orb of Muculence in your quest inventory to complete the quest.

Actual behaviour: There are no tents to interact with in the red marked quest area, making the quest incompletable.

**Steps to reproduce the problem:**
N/A

**Testing Screenshots/Videos/Evidences (always needed):**

![Lighting the Way](https://user-images.githubusercontent.com/4006687/234851820-5a271f9b-db7e-4893-aaee-31f3cfa10a1c.png)

**Comment by Majorzero2123** [comment]
Could you check this quest again? the tents are in the screenshot to the left of your character. are they interactable?

**Comment by 0xAB51NTH** [comment]
Im pretty sure the green tent in the screenshot is what you are looking for, the quest display on map is a little iffy with a lot of quests.

**Comment by Varnarok** [comment]
Hey.

Those green ones were indeed the ones I was looking for. Guess I had a bad case of tunnel vision to have missed them that bad.

Quest works fine.

**Comment by 0xAB51NTH** [comment]
@lilimx The tents were on screenshot and the poster just have not noticed them, seen him zoom near them few mins ago. Here is video showing that the quest works as intended.

https://user-images.githubusercontent.com/47013267/235367765-3eaa6d50-6d2c-4b9b-b46f-3bee8f70d760.mp4
