### ISSUE TITLE
Magus pet not granting buffs in specific zone

### ISSUE THREAD

**Issue by sasba2** [WarEmu/WarBugs#20883]
Hi,

I've had multiple fights in Thunder Mountain where i've summoned flamer minion but haven't been able to cast specific skills while moving.
I noticed this a while ago but thought it was some kind of temporary issue. However today when this happened again I wanted to test it a bit.

Expected behavior: Summoning pet grants buffs and pet abilities can be used.

Actual behavior: The game doesn't recognize that pet has been summoned. No buffs are granted, cannot use pet specific abilities (KD for instance) and even though pet does understand to take my target it does not attack. It doesn't matter wheter im in the rvr lake or in WC.

I've tested this with and without Chaotic attunement. I've stripped down my whole character to see if it would've been some sort of gear piece issue.

Reproduce: Spam different pets with and without tactic in Thunder Mountain. Using resummon grants you the buff (just tested).

**Testing Screenshots/Videos/Evidences (always needed):**
[https://streamable.com/cziyol](url)

Apparently streamable has 1 day expiration date and my video is bit too big for this site. I can provide screenshots/upload the video some place else.

**Comment by lilimx** [comment]
Hey,

thank you for your ticket.
This issue has been already reported here #18775

**Comment by sasba2** [comment]
Hi,

Thanks for your quick response. I tried to search for it but wasn't able to find, hence this new ticket.
