### ISSUE TITLE
Witchbrew Duration

### ISSUE THREAD

**Issue by SirBattosai** [WarEmu/WarBugs#2088]
Hey there!
The current Duration for Witchbrew is set to 10 seconds and it has a 10 second cooldown, the duration is 1/6 ( with max BL) from what i remember it to be on live, when i stopped playing - the duration also scaled with the consumed bloodlust i think as in 1 bloodlust - 20 seconds and next two attacks and so forth.
Is this adjustable? 
when i checked the bug tracker and the forums i haven't found this adressed yet, if it was already, disregard this report please.
1 BL: 20 seconds duration or 2 attacks
2 BL: 30 seconds duration or 3 attacks
3 BL: 40 seconds duration or 4 attacks
4 BL: 50 seconds duration or 5 attacks
5 BL: 60 seconds duration or 6 attacks

**Comment by Evildoor** [comment]
I have vague memories about Witchbrew always having 60 seconds duration (or until used, ofc) regardless of bloodlust, but i'm not an experienced WE player so i may be wrong. But it is definitely not 10 seconds.

**Comment by SirBattosai** [comment]
not entirely sure either, wether it's just flatout 60 seconds or wether it scaled with the bloodlust - it's been a few years already.

**Comment by ozarmidrashim** [comment]
It doesn't really matter either way. Setting it to 60 seconds is easiest.
