### ISSUE TITLE
Can't claim rvr inf rewards

### ISSUE THREAD

**Issue by MannyKarlavera** [WarEmu/WarBugs#20891]
**Expected behavior and actual behavior:**
Expected to be able to claim rvr inf reward when inf was completed.
I see in my ToK that inf is full, but still can not claim the reward. It's "greyed out" from NPC in dialoge. 
Tried in all T4 zones and pairings.

Was told in /AD that it's been a problem for awhile but restart should fix it. Did a complete restart but the problem remains.  

**Steps to reproduce the problem:**
Just trying to claim the reward.

**Testing Screenshots/Videos/Evidences (always needed):**

![Bugreport_000](https://user-images.githubusercontent.com/93761347/235602940-ad637782-c405-4360-8734-362f720856db.jpg)

![Bugreport_001](https://user-images.githubusercontent.com/93761347/235602653-0673cf69-2972-4edd-8f54-7d392a1cea1d.jpg)

Kind regards!

**Comment by lilimx** [comment]
Hey,

we need your character name.

**Comment by MannyKarlavera** [comment]
Oh, sorry about that! Toon is "Lotty"

**Comment by MannyKarlavera** [comment]
No idea why, but no i can claim it, Perhaps something got sorted in server reboot. Thx all!
