### ISSUE TITLE
Destruction Talabecland quest "Breaking and Entering" missing Basket of Fish interactables

### ISSUE THREAD

**Issue by Varnarok** [WarEmu/WarBugs#20890]
**Expected behavior and actual behavior:**
Expected behaviour: After picking up the quest from the Chaos chapter 10 camp, head towards the Mud Flats PQ/Village and pick up 5 Barrels of Cheap Cider, 3 Baskets of Fish and 1 Bottle of Riptide Wine before returning back to turn in the quest.

Actual behaviour: After reaching the village, you are only able to pick up the barrels of cider and bottle of riptide wine. There are no baskets of fish visible within the village apart from one on the docks that you are not able to interact with (screenshot 2). I tried completing the PQ associated with the area to see if that would cause the baskets to appear but it did not.

**Steps to reproduce the problem:**
N/A

**Testing Screenshots/Videos/Evidences (always needed):**

![Breaking and Entering](https://user-images.githubusercontent.com/4006687/235461678-6a3fe85d-3290-4e97-964b-c14fb795a860.png)
![Breaking and Entering 2](https://user-images.githubusercontent.com/4006687/235461737-6b4773d6-7bd0-40fd-8d89-1ddf7c4b275a.png)

**Comment by Majorzero2123** [comment]
Hello, just to double check, can you see the fish baskets over at 13.6k, 37k? 
![image](https://github.com/WarEmu/WarBugs/assets/99697728/fc1895f7-0753-43a5-b52e-7f9d6d7f93c9)

**Comment by Varnarok** [comment]
I do not appear to be able to see those baskets. 

![Breaking and Entering 3](https://github.com/WarEmu/WarBugs/assets/4006687/32e22475-27bf-4823-9262-7c2fe62e283d)
![Breaking and Entering 4](https://github.com/WarEmu/WarBugs/assets/4006687/a8c0cf0e-0f11-46c0-b48d-33f780c11d68)

**Comment by lilimx** [comment]
This has been fixed with patch 29/05/2023
