### ISSUE TITLE
Friendly & Enemy  Target titles and guild name showing

### ISSUE THREAD

**Issue by bulgy70** [WarEmu/WarBugs#20899]
Was looking at taking some video and screen shoots of the game with the UI turned of, and did not want an names or tags. if you look at the video you see. Friendly & Enemy Target titles and guild name showing, when turned off.  Also all addons were off.  this was only happening when i click on the player or tab to target. 

Video in PVP Lake
https://www.youtube.com/watch?v=ooB4qh5egec

**Comment by Zomega-WAR** [comment]
https://github.com/WarEmu/WarBugs/issues/20847

**Comment by bulgy70** [comment]
> #20847

I try that and thank you for linking
