### ISSUE TITLE
Cant complete Hunter's Vale quest

### ISSUE THREAD

**Issue by RunaGG** [WarEmu/WarBugs#20894]
Trying to get credits for killing Durthu-Wood Treekin. Completed all dungeon for 3 times now and stil 1/2.

![image](https://user-images.githubusercontent.com/132398466/235788361-7ba9137d-ee62-4376-a817-8cc9f1e12386.png)

Should i abandon this quest and try to complete it again or its bugged?
Character name - Runaaa

**Comment by RunaGG** [comment]
tryied today to abandon it and start again, still do not count anything but Thanan Tree Lord
![image](https://user-images.githubusercontent.com/132398466/235967625-d1b07977-8c23-4b05-82ec-169b4617b03f.png)

**Comment by lilimx** [comment]
Hey,

thank you for your report.
This issue was already reported here: #20856
I will add you ticket to the other report.
