### ISSUE TITLE
Guild Herald Reserve not what we picked!

### ISSUE THREAD

**Issue by MichaelMontei** [WarEmu/WarBugs#20892]
Hello There,

Our Guild Herald Reservation we did is not matching with what we picked and what we payed 100G for. 
We are a new Guild / Players to the game and not sure if this is updated or not?
Our Guild Level = 13 
Can this be solved please?

This is the Guild Herald Reserve I did and payed 100g for: 
![herald we wanted](https://user-images.githubusercontent.com/103993166/235750243-49be22c9-ba68-4718-b718-76f1b6cb56c9.JPG)

This is what we have in game: 
![Cloak in game](https://user-images.githubusercontent.com/103993166/235750626-9f3e69b5-6dc5-4c8b-b925-e2b7ba802dbb.JPG)

Could you take a lot at this matter please?
Thanks in advance! 

Kind regards
Vxc

**Comment by lilimx** [comment]
Hey,

that's not a bug....your guild isn't high enough atm. Your guild has to be be lvl 20 to unlock all options.
