### ISSUE TITLE
[BW] Wildfire tactic doesn´t activate on all Conflagration abilities

### ISSUE THREAD

**Issue by Vancerus** [WarEmu/WarBugs#2089]
The 11p tactic "Wildfire" has a 25% chance to activate when "any" Conflagration ability hits an enemy.

Tested now on a bunch of mobs, it just activates on Direct Damage abilities like Fiery Blast, Rain of Fire, Annihilate and Scorched Earth. DoT type Spells like Flame Breath, Spreading Flames and Backdraft are beeing left out.

Pls have a look.
Cheers,
Vance

**Comment by Evildoor** [comment]
Let's use #1940 for this tactic, since it's pretty much about the same.
