### ISSUE TITLE
Slayer cooldown Reduction Tactics not calculating correctly?

### ISSUE THREAD

**Issue by Aedros** [WarEmu/WarBugs#20898]
Hi I have equipped two slayer tactics Hastened Punishment (-25% cooldown reduction for Exhaustive Blows) and Short Temper (Reduce cooldowns 5 seconds while in Berserk State but it does not appear that they are correctly combining to reduce the cooldown of exhaustive blows.

**Expected behavior and actual behavior:**
I equip Hastened Punishment and the tooltip cooldown on Deathblow is correctly reduced to 7.5 seconds from 10 (-25%)
I equip Short Temper and when I enter Berserk status, the cooldown is reduced to 3.8 seconds and not the 2.5 I expected (e.g. 7.5 - 5 seconds = 2.5). 

The 3.8 value seems like it would be generated if the 5 second Short Temper reduction was applied first off of the default 10 second cooldown value for Deathblow and then the Hastened Punishment value (-25%) is applied (e.g 10-5 = 5*.75 = 3.75 RND 3.8).

Since Hastened Punishment is a static reduction and Short Temper a conditional one, shouldn't the Short Temper reduction be off of the new base cooldown after Hastened Punishment is applied? In this case I believe the correct final cooldown value should be 2.5

**Steps to reproduce the problem:**

Equip Hastened Punishment Tactic
Equip Short Temper Tactic
Confirm default cooldown for 10 sec exhaustive blows (e.g. Deathblow) is 7.5 seconds
Attack target dummy or NPC until red Berserk state is achieved
Mouse over Deathblow tooltip and confirm that new cooldown value is listed as 3.8 seconds

**Testing Screenshots/Videos/Evidences (always needed):**

![Brego_000](https://user-images.githubusercontent.com/81740142/236742346-e41681a9-4f73-4d64-b661-8414d9d5b27a.jpg)

![Brego_001](https://user-images.githubusercontent.com/81740142/236742394-20f21ab7-91b9-40c8-ba1e-382becda35db.jpg)

![Brego_002](https://user-images.githubusercontent.com/81740142/236742406-666349d1-a820-47e7-a959-02e06ea151e1.jpg)

**Comment by CrimsonFenris** [comment]
Like many other similar effects, fixed values effects are always taking place before any percentage-based ones, like armor debuffs apply before "% ignore" effects, and so on.

You can also test it with AP reduction tactic, wich should first decrease AP cost (by 5 or 10 depending on your rage state), before using slayer warcry wich will apply a 25% further AP reduction on top of the reduced AP value.

**Comment by Aedros** [comment]
I see. Thank you for the clarification. The interaction was not intuitively obvious (at least to me). Appreciate the investigation and explanation.

**Comment by lilimx** [comment]
Additional use .getstats to check your stats
