### ISSUE TITLE
Event Relic Drops under bridge between Praag and Chaos Wastes

### ISSUE THREAD

**Issue by AndrewSquared** [WarEmu/WarBugs#20908]
**Expected behavior and actual behavior:**
Running the order event relic from Praag to Chaos Wastes does not drop

**Steps to reproduce the problem:**
Get the event relic, cross the border between Praag and Chaos Wastes in the middle, under the bridge

**Testing Screenshots/Videos/Evidences (always needed):**
![event-relic](https://github.com/WarEmu/WarBugs/assets/5799247/ddd496d9-f153-4609-9fc3-6af7651d4278)

**Comment by lilimx** [comment]
Fix in progress

**Comment by lilimx** [comment]
Should be fixed with Hotfix 19/05/2023
