### ISSUE TITLE
Destruction Chrace quest "Lionsbane Banner" missing interactable for a banner

### ISSUE THREAD

**Issue by Ladgahr** [WarEmu/WarBugs#20900]
**Quest name:** "Lionsbane Banner"

**Quest objective:** Mount banner outside Tol Achare

**Expected behavior:** There should be an interactable object on the ground or the banner itself in the bag should be usable in the correct area.

**Actual behavior:** I could not find any interactable objects in the highlighted area on the map.
A banner quest item is not usable.

**Testing Screenshots/Videos/Evidences (always needed):**

![Popasny_000](https://github.com/WarEmu/WarBugs/assets/133169396/ce9e45a9-3498-483f-a8c5-8f8792e30aff)

**Comment by Majorzero2123** [comment]
Hey, are you able to retest this quest? I was able to complete it via a quest item. try doing it right at the start of the stairway. I used the questitem at 21k 23.7k
![image](https://github.com/WarEmu/WarBugs/assets/99697728/9e722213-0fce-4f48-9cdb-01e57d8c1adb)

**Comment by Ladgahr** [comment]
Yep, quest item worked next to a pillar at the top of the stairway. 
Before I did that I tried running around inside the highlighted area while clicking on a quest item and it appeared that correct area is much narrower, but I guess the quest works.
I'm going to use this method later on, thanks.
