### ISSUE TITLE
Destruction Dragonwake quest "The Price of Failure" missing spike interactables

### ISSUE THREAD

**Issue by Varnarok** [WarEmu/WarBugs#20901]
**Expected behavior and actual behavior:**
Expected behaviour: After accepting the quest, head towards the prisoner cages inside the chapter 18 Dark Elf camp, place 3 quest heads on spikes balled Left Sharpened Spike, Middle Sharpened Spike and Right Sharpened Spike. Then turn in the quest.

Actual behaviour: There are no spikes upon which to spike the 3 heads, leaving the quest incompletable. 

**Steps to reproduce the problem:**
N/A

**Testing Screenshots/Videos/Evidences (always needed):**

![The Price of Failure](https://github.com/WarEmu/WarBugs/assets/4006687/87f2e73b-9047-4833-bf69-41c9b464de6d)

**Comment by Varnarok** [comment]
Seems the screenshot isn't loading properly. This was the url for it: https://github.com/WarEmu/WarBugs/assets/4006687/87f2e73b-9047-4833-bf69-41c9b464de6d

**Comment by Varnarok** [comment]
Also I erroneously called them spikes when they are just called pikes.

**Comment by Majorzero2123** [comment]
Thanks for the ticket! a fix for this is on dev and should be fixed within the next patch

**Comment by lilimx** [comment]
This has been fixed with patch 29/05/2023
