### ISSUE TITLE
BW tactic Flashfire

### ISSUE THREAD

**Issue by hoppolek** [WarEmu/WarBugs#2090]
I'm not sure if there are others, but at least burning iron is unaffected by flashfire. The buff disappears, but I always have my full cast time for Burning Iron.

Also channeling skills are "instant" with flashfire, with the buff disappearing. I don't know if it worked like this on live or not, but it feels like a bug.

**Comment by ozarmidrashim** [comment]
First problem is an unfixable client bug as far as I can see. The client isn't reducing the cast time of Burning Iron, no matter what values are sent in the Flashfire packet.

Second problem is fixed.

**Comment by Londo001** [comment]
Flashfire is 2 buffs. Tactic buff is abilityID:8196, on proc abilityid:3422 is applied for 10 seconds with two parameters: 0 = -100, 1 = -1

**Comment by ozarmidrashim** [comment]
Will try that, thanks.
