### ISSUE TITLE
Liniment duration ending early

### ISSUE THREAD

**Issue by Zahaqiel** [WarEmu/WarBugs#20914]
I've used two Liniments of the Inevitable Tempest in the past half hour.  Each time, although it began with a half-hour duration, it ended early for some reason as though the status had been cancelled.

It _may_ have something to do with the GuardRange mod as I experienced a null error from LibGuard around the time I first spotted it being cancelled, but I can't confirm any connection it's just a suspicion (it was in a scenario - College of Corruption - and combat was very quickly filling up my chatlog so I couldn't track it reliably, and I didn't see when the second one self-cancelled, I only noticed it later after zoning a few times).

1hr armour pot taken at the same time as the first liniment is still going fine.

**Comment by lilimx** [comment]
Hey,

please do a /rel and check with .getstats if the stats are really gone.

**Comment by Zahaqiel** [comment]
Signed out at the moment, will do next time I have the issue occur.

**Comment by Zahaqiel** [comment]
Well, I managed to get a similar, but not exactly the same, LibGuard error (_LibGuard got an error from a registered function: [string "Interface/AddOns\GuardRange\GuardRange.lua"]:90: attempt to compare nil with number_) but as yet I haven't had the liniment disappearing error again.

I'll keep on it, who knows?

**Comment by lilimx** [comment]
Hey,

If it happenes again, please start a fresh ticket.
Thx!
