### ISSUE TITLE
College of Corruption - Being pulled into destro spawn

### ISSUE THREAD

**Issue by Emissaryx** [WarEmu/WarBugs#20919]
**Expected behavior and actual behavior:**

Shield should not allow any targeting through portal

**Steps to reproduce the problem:**
Video below

**Testing Screenshots/Videos/Evidences (always needed):**

https://youtu.be/Pnr2wDjMnSY

**Comment by Rubyeclipse-war** [comment]
Thanks for the video! Added a shiny new barrier to fix this. (The Marauder pull itself is also bugged which causes this to happen, but that will get resolved once the new ability system arrives in the future.)

To be safe, I haven't added another new barrier to the Order spawn just yet as it may block some stairwells, but if anyone sees Order players doing the same sorts of pulls into their spawn, let us know and we can get it fixed up too.

This fix will go live with the next patch. Thanks!
