### ISSUE TITLE
Kill board guild dont work

### ISSUE THREAD

**Issue by kpihuss** [WarEmu/WarBugs#20915]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**
Open any guild killboard and u will get a 400 error. For example: https://killboard.returnofreckoning.com/guild/2947

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://github.com/WarEmu/WarBugs/assets/54821994/daf5040f-1999-49ad-9cd8-fd89d7eabe4e)

**Comment by dalen** [comment]
Fixed
