### ISSUE TITLE
[EVENT] Sigmartag: Quest "Flamespeaker's gaze" not counting kills 

### ISSUE THREAD

**Issue by Scophis** [WarEmu/WarBugs#20911]
Played a few rounds of CoC, got some kills and even deathblows, but no progress on the quest. Tried to restart the quest but still no progress.
Others reported the same in chat.

![Gangan_058](https://github.com/WarEmu/WarBugs/assets/40274248/fcaecd06-7f56-4b08-9d90-4d1c4b97cdb1)

**Comment by lilimx** [comment]
This issue is known and a fix is pending

**Comment by lilimx** [comment]
Should be fixed with Hotfix 19/05/2023
