### ISSUE TITLE
Hammerstone's Pendant item Bug

### ISSUE THREAD

**Issue by rbnuck** [WarEmu/WarBugs#20928]
ROR Team,
The item reward, Hammerstone's Pendant, from the Live Event SIGMARTAG incorrectly adds 56 (an addition of 560 health) 'wounds' to the total wounds value on the Character Screen.  It does, however, correctly add exactly 120 health (12 wounds) to the character icon on the game play screen.  The additional 16 Willpower and 6 Initiative added by this item are both correctly added to the 'stats'.  The 3 screenshots provided demonstrate the details above.

Thank you for your time,

Ugguh

![Ugguh_001](https://github.com/WarEmu/WarBugs/assets/134521529/a2e6495f-7a5a-4d34-ad4e-a1e4a393fd70)

<

![Ugguh_003](https://github.com/WarEmu/WarBugs/assets/134521529/15df2e11-d4cd-4892-9e48-e45a5530e487)

![Ugguh_002](https://github.com/WarEmu/WarBugs/assets/134521529/665efc96-b3ee-4e4c-8fce-049662540d47)

**Comment by rbnuck** [comment]
Hello, 
I did check the .getstats and the values are as they should be (accurate).  The item still shows an incorrect value of wounds on the character screen (stats).  Just letting you know.
Thx

Ugguh

**Comment by lilimx** [comment]
Hey,

thx for your response. 👍
