### ISSUE TITLE
Testria Farvoid

### ISSUE THREAD

**Issue by DaiKuma81** [WarEmu/WarBugs#20927]
Testria Farvoid the mount vendor in the Chaos Ch.1 HUB. Sells Order armor and the Order Pack Mule instead of the Destruction counterparts.

I've included a few Screenshots to show the items.
![image_2023-05-23_135236464](https://github.com/WarEmu/WarBugs/assets/134439482/a06f7b77-9570-47af-b108-79e16fcad3cf)
![image_2023-05-23_135341218](https://github.com/WarEmu/WarBugs/assets/134439482/1b56c5a3-a65a-42ac-a76b-8bafa5553029)
![image_2023-05-23_135409140](https://github.com/WarEmu/WarBugs/assets/134439482/34324ba9-d05c-44aa-ac0d-892a253661a7)
![image_2023-05-23_135432009](https://github.com/WarEmu/WarBugs/assets/134439482/15badbe7-de12-4ddf-bc6a-de2cfbe6e5cd)

**Comment by Majorzero2123** [comment]
Hey, this is because you have Show all on, which will show you all the items the vendor offers, including order ones.

**Comment by DaiKuma81** [comment]
I checked just in case. Only non Destruction item is the book of binding.
