### ISSUE TITLE
renown tactics malfunction

### ISSUE THREAD

**Issue by bleifuss22** [WarEmu/WarBugs#20925]
Order, Witch Hunter, lvl 40, renown lvl 63

tactics points to spend are not similiar to game messages
see picture
-->

**Testing Screenshots/Videos/Evidences (always needed):**

![Yeehaw_008a](https://github.com/WarEmu/WarBugs/assets/79282928/071454dd-78b0-4b9f-81c9-52b80274ea12)

**Comment by lilimx** [comment]
Hey,

please try to do a proper relog.

**Comment by bleifuss22** [comment]
its the problem during logged on, i get a point by level raisong, i am not able to use it immediately. If I log i loose my progress since logged on?
