### ISSUE TITLE
NPC's in caledor have multiplicated

### ISSUE THREAD

**Issue by 0xAB51NTH** [WarEmu/WarBugs#20924]
**Expected behavior and actual behavior:**
actual behaviour: TOO MANY UTHORIN FERALBLADES
expected behaviour: few uthorin feralblade are standing

**Steps to reproduce the problem:**
Go to Caledor 52k 32k
Open eyes

**Testing Screenshots/Videos/Evidences (always needed):**

![image](https://github.com/WarEmu/WarBugs/assets/47013267/b962462f-021a-4e5c-b9fa-1b745d088520)

**Comment by lilimx** [comment]
This should be fixed 23/05/2023
