### ISSUE TITLE
using "skill tactics" (Waffenkenntnis) has no function

### ISSUE THREAD

**Issue by bleifuss22** [WarEmu/WarBugs#20926]
Order, Witch Hunter, lvl 40, renown lvl 63

while I am changing "skill tactics" with "Waffenkenntnis/Kampfgeschick" this has no fuction to character values!
see pics

**Testing Screenshots/Videos/Evidences (always needed):**
not using tactics, value is 374, its OK status
![Yeehaw_010a](https://github.com/WarEmu/WarBugs/assets/79282928/9c4cbe23-d9bd-4623-97e9-a6844d687125)

but, using tactis, should raise "Kampfgeschick" +63 for renown level 63
![Yeehaw_011a](https://github.com/WarEmu/WarBugs/assets/79282928/418e6d73-008b-487c-ba0d-05d978c00a8a)

no raise of char values! value still 374, should be 374+63 = 437

**Comment by lilimx** [comment]
Hey,

please use the command .getstats to check that.
The paperdoll stats aren't reliable.

**Comment by bleifuss22** [comment]
oh, you telling me "what I see, isn't what I get"? Nice behavior to skill your char the right way. Player is not a coder...!
".getstats" entered
got none information, where to find results?

**Comment by bleifuss22** [comment]
proofed with ".getstats". 
WEAPON SKILL is NOT raised if i use tactics - big bug/issue about! sry

![Yeehaw_012](https://github.com/WarEmu/WarBugs/assets/79282928/55ede1c6-7f8b-4b3a-8e32-c6798b4454d2)

**Comment by lilimx** [comment]
There aren't any tactics with +Weaponskills for the WH.
