### ISSUE TITLE
Bug in Beastlord crests exchange

### ISSUE THREAD

**Issue by Andayris** [WarEmu/WarBugs#20930]
Hello, 

I tried to exchange my Beastlord crests (3) againts the Beastlord hunting guide and the exchange went through but infortunetly I received the wrong gear in my Inventory (Beastlord Ironmantle). That Item is for Iron Breaker and I am actually Witch Elf.

Did notinhg special to encounter the bug, just noticed a lot a server problems earlier during the day but I don't think It has sometimes to do with it.

Hope it helps ! 

Ps : If there's anything I can do to get the proper Item let me know. (Andayris, WE)
![Item bug BL](https://github.com/WarEmu/WarBugs/assets/134763814/9b9e1bd5-ab02-4eb1-ba7f-0bda22287d07)

**Comment by lilimx** [comment]
Hey,

if it was during a weird lag season....it could be really the reason for it...otherwise I can't reproduce it.

**Comment by Andayris** [comment]
There was no lags or anything, plus how come as a WE I get a IB item ? Isn't it weird  ?

**Comment by lilimx** [comment]
Hey,

it's not reproduceable and you've have written there were server issues. So we can't find out what happen.
We have a general policy of not restoring losses that occur due to issues.

**Comment by Andayris** [comment]
I'd understand If I had a IB on my account and played it wich is not the case. Just used my crests on the book and received that IB shoulders as a WE. Nevermind If I don't get my beastlords tokens back, I'm used to  gettin' same answer. Nothing we can do, last time it was about a gunbad run not counting boss kills for my quests...

So I'll farm.

Thanks for the answers
