### ISSUE TITLE
Unequippable weapon - Destruction - Black Guard

### ISSUE THREAD

**Issue by zordard** [WarEmu/WarBugs#20937]
Not usable from inventory 
![cannot](https://github.com/WarEmu/WarBugs/assets/134952814/163d184e-07f3-438f-92a4-f01eb8eb4ecc)

**Comment by zordard** [comment]
It is equipped normally if shield is removed

**Comment by lilimx** [comment]
Well, because it's a 2h weapon. 
You have to remove the shield first.
