### ISSUE TITLE
Apothecary Main Ingredient not accepted

### ISSUE THREAD

**Issue by Zedfyr** [WarEmu/WarBugs#20933]
Items purchased from Crafting Vendor do NOT work e.g.  Preserved Anorexic Bat wing Level 25 item.  My Apothecary is currently Level 63.

In Chat window:  Bad seed data.  Since the seed couldn't be generated, it has been lost.

This is not a seed, and it was not lost
![Zedzdead_004](https://github.com/WarEmu/WarBugs/assets/134523389/67f7d3f4-a835-4591-aa4e-e2701ebc0e74)

![Zedzdead_003](https://github.com/WarEmu/WarBugs/assets/134523389/89695657-af21-4e5e-9878-dd4de3365ff2)

-->

**Comment by lilimx** [comment]
Hey,

This issue has been posted here #14696
