### ISSUE TITLE
The Ebon Flame Questline failure @ Telior Windseer

### ISSUE THREAD

**Issue by NTGrem1** [WarEmu/WarBugs#20934]
**Expected behavior and actual behavior:**
Talk to the NPC Telior Windseer to continue the quest

**Steps to reproduce the problem:**
Attempt to talk to Telior Windseer, he will disappear

**Testing Screenshots/Videos/Evidences (always needed):**

None required for this action, attempt to proceed in the Questline for The Ebon Flame

Unable to advance in the Epic Quest with The Ebon Flame

**Comment by lilimx** [comment]
dublicate #20931
