### ISSUE TITLE
Cannot hit 85...

### ISSUE THREAD

**Issue by VylozV** [WarEmu/WarBugs#20936]
Dark greetings!
I know it already, this game hates me ;)...i am stuck on 1 Renown before hitting RR 85!
Please help a "poor" Druchii...
![grafik](https://github.com/WarEmu/WarBugs/assets/119527929/c2bd961d-f388-4786-bde4-ad329dcf98e5)

Much appreciated!
Sa´an´ishar!
Vyloz (Leader of "Darkness and Ruin")

**Comment by VylozV** [comment]
Uff...fixed the issue with handing in a box, this is NOT what i wanted..but helped

**Comment by lilimx** [comment]
Gratz
