### ISSUE TITLE
Missing Items since server restart

### ISSUE THREAD

**Issue by Cekura** [WarEmu/WarBugs#20945]
**Expected behavior and actual behavior:**
Expected: Everything should work fine.
Actual: Dyes that were applied to the armor same as talismans are just GONE. 
And this is not a visual bug, reinstalled the game multiple times, logged in like 50 times, the items are just GONE.

I haven't seen anyone else having this problem yet, even tho people in my guild sais this is a common issue, but I cannot find ANY informations about that, sorry if I double post.

**Steps to reproduce the problem:**
I dont know...

**Testing Screenshots/Videos/Evidences (always needed):**
![grafik](https://github.com/WarEmu/WarBugs/assets/134284254/b6baea4d-a1e2-455e-b55a-9647833497bb)

**Comment by lilimx** [comment]
Hey,

nope, that's not common. But we need your account name and the character name that lost items. Additional, could you name a few items they got lost?

**Comment by Cekura** [comment]
Ok,

I dont like to share my account informations on such a public board, neither I'm interested in a refund. 
I just like to get rid of the bug for the sake of the community!

The dyes were w/e, not important, but the talisman that disappeared (from my BOOTS and GLOVES ONLY) were +23 Strength ones (Superior Talisman of the Gladiator).

cheers

**Comment by lilimx** [comment]
Hey,

Uhm, we don't refund stuff in general. But we can try to check what happended. Maybe Max can do some magic.

**Comment by Cekura** [comment]
Ok,

the character name that happened on is Molossuss.

**Comment by Cekura** [comment]
I found out what happened. This is not a bugg at all!
Just a 2nd set I found and somehow swapped my original items... 
I'm very sorry for your time consuming >.<

**Comment by lilimx** [comment]
Haha glad to hear!
