### ISSUE TITLE
[City dungeon BB/BE] Can't redeem Elite Influence reward

### ISSUE THREAD

**Issue by Cekura** [WarEmu/WarBugs#20947]
**Expected behavior and actual behavior:**
Expected: Every influence reward should be able to be picked up. Hence 2 Rally Masters = 2 Influence rewards. As any other player.
Actual: I was only able to redeem one "Sentinel Chaos Seal" (Slot 3 Jewelery) from BE and after I got that I went over to BB (after i completed both influence in a chained run) and he didnt let me pick anything on Elite (all the others were redeemable tho!). Look at the screenshot - its just a blank field. Every other player I talked to was able to get 2 Jewelerys tho - I'm the only one who's missing out.

To be Explicit: Cleared BB (Max Influence reached) - went over to BE without redeeming - Cleared BE (Max Influence reached) - left dungeon - redeemed the ELITE reward - went back to BB - no Elite reward here. Went back to the BE Rally Master - His reward table also looks like that now (no Elite reward visible)

I tried everything, even multiple fresh installations on different drives to clarify its not caused by an addon (as I always do with such bugs)

### Theorie: After you got MAX Influence in both runs simustaneously without redeeming, the chance of the 2nd Jewelery is bugged out. Talked about that to a lot of players but no one ever seen that happen.

I also tried to contact a GM by an appeal ingame about that, but I never heard something about this back after waiting a week I feel like this must be adressed in the bugtracker now. Sorry for the inconvenience.

**Steps to reproduce the problem:**
see theorie

**Testing Screenshots/Videos/Evidences (always needed):**
![grafik](https://github.com/WarEmu/WarBugs/assets/134284254/bb7b61cb-cb76-4f0d-8da2-3b583d979bc6)

**Comment by Majorzero2123** [comment]
Hey, so basically, you are normally only supposed to claim 1 Sentinel ring per character, but as you have mentioned, there is a way to get around it and claim 2. This ticket is not a bug, however being able to claim 2 rings is.

**Comment by Cekura** [comment]
Hah okay, thats very interesting, since pretty much everyone I know has 2 of them and use an offensive/defensive setup. I felt really bad and disadvantaged for only having one tho. Thanks for clarifying!
