### ISSUE TITLE
Squig herder pet summoning in Squig form 

### ISSUE THREAD

**Issue by Iamwithstupid** [WarEmu/WarBugs#20941]
**Expected behavior and actual behavior:**
When summoning squig while being in Squig form(Squig armor) will remove you from Squig form.

**Steps to reproduce the problem:**
Use Squig armor then summon pet.

**Comment by lilimx** [comment]
Hey,

This has been reported here #18439

**Comment by Iamwithstupid** [comment]
EARLY 2021 post? It has been working for last few years tbh...
