### ISSUE TITLE
Renown Points not being awarded

### ISSUE THREAD

**Issue by pthiel168** [WarEmu/WarBugs#20942]
Current renown level hit 18 but only have 14 renown points.
![image](https://github.com/WarEmu/WarBugs/assets/8930990/60457cc7-96f6-4566-882c-11e49f5c58b0)

Thanks

**Comment by lilimx** [comment]
Hey,

please do a relog.

**Comment by pthiel168** [comment]
Thanks,



I logged out, then exited the game and rebooted my machine. Upon getting back in I am still missing the renown points.



Cheers











---- On Wed, 31 May 2023 13:34:17 -0400 Lilim ***@***.***> wrote ---





Hey,

please do a relog.

**Comment by lilimx** [comment]
Hey,

okay, haven't read the the full text. 
You are only able spent the same amount of RR as your current lvl until you hit a lvl 38 or lvl 40. 
So you I guess your current lvl is lvl 14, because you are still in T1.

**Comment by pthiel168** [comment]
Makes sense and many thanks











---- On Wed, 31 May 2023 15:45:22 -0400 Lilim ***@***.***> wrote ---





Hey,

okay, haven't read the the full text.
 You are only able spent the same amount of RR as your current lvl until you hit a lvl 38 or lvl 40.
 So you I guess your current lvl is lvl 14, because you are still in T1.
