### ISSUE TITLE
Unable to log into specific characters

### ISSUE THREAD

**Issue by Zulisity** [WarEmu/WarBugs#20946]
I posted this on the forum thread a few days ago but no reply and now I have a second character who is experiencing the same thing.

First Character: Elrie logged out in the Maw during city siege unable to log back on.
Second Character: Azzozoth was roaming rvr in Talabecland and now cant log back on.

Please help

**Comment by lilimx** [comment]
Please add your name here.
https://www.returnofreckoning.com/forum/viewtopic.php?t=46249&start=950
