### ISSUE TITLE
Pls, explain why tactics/skills has no effect to character values

### ISSUE THREAD

**Issue by bleifuss22** [WarEmu/WarBugs#20940]
Just asking for help.

I dont know if there is a bug at my char. Using "Waffenkenntnis" has no effect on char. Thanks.

**Steps to reproduce the problem:**
1. dont use skill "Waffenkenntnis" (pic1)
2. notice the value of "Kampgeschick" of char window is 384 (at my char) (pic 1)
3. type ".gestats" to proof for active value of "Waffenkenntnis" (same 384, ok) (pic 1)
now:
4. use skill "Waffenkenntnis to 4th tactics/skill place (green symbol) (pic 2)
5. using skill "Waffenkenntnis" it says, that raises your value 384 by renown lvl +63
6. new value should be 447
7. notice the value of "Kampgeschick" of char window is still 384 (at my char)
8. type ".gestats" to proof for active value of "Kampgeschick" (same 384,  seems not ok) (pic 2)

**Testing Screenshots/Videos/Evidences (always needed):**
 pic1
![Yeehaw_015](https://github.com/WarEmu/WarBugs/assets/79282928/eaf0aad6-1c76-4012-9c3a-56e043f3409b)

pic2
![Yeehaw_016](https://github.com/WarEmu/WarBugs/assets/79282928/87863cca-2f20-4e15-80a2-bb038c370caf)

Pls, be so kind to proof, what the problem is. Dont know how to play/skill a char this way, if using a tactics/skill has an effect or not.

**Comment by lilimx** [comment]
Es gibt keine Taktik mit Waffenkenntnis.
