### ISSUE TITLE
Rift doesn't disrupt

### ISSUE THREAD

**Issue by Mezirah** [WarEmu/WarBugs#2095]
I think I'm sure about this one. To test, I had an ironbreaker cast hold the line (45% disrupt chance) and he still got rifted 8x in a row. Maybe he's really unlucky, but, it's worth checking please.

Thanks

**Comment by Evildoor** [comment]
I recommend WH/WE with 100% disrupt from ability for such tests in the future. Or phys RDPS with morale.

**Comment by Tiggonos** [comment]
shoudnt there be an imunity on getting rift anyway?
