### ISSUE TITLE
State of Realm option Show Only Your Realm stopped working.

### ISSUE THREAD

**Issue by Ryzottt** [WarEmu/WarBugs#20950]
I just logged in after a long time to try it out again. I began first by rearranging the entire U.I. to make it more like a modern MMO. I noticed that the State of Realm U.I. was showing this long list of places, so I looked at the options and it had an option for Show Only Your Zone. So, I checked it and it worked; it was only showing one location. Note that I had every single other option checked.

I then began to continue where I left off questing. I am level 6. Then all of a sudden, all those other zones started showing up again. I tried unchecking and checking Show Only Your Zone, but it didn't work. I tried various combinations of checked off options. Tried resetting SoR settings. Tried logging out and back in. Tried exiting the game entirely and relaunching. Nothing worked.

Som I am reporting now that, for me, the Show Only Your Zone option for the State of Realm U.I. has stopped working after previously working for a short time.

**Comment by lilimx** [comment]
Hey,

do you have a RoR SoR version in your interface folder?

**Comment by lilimx** [comment]
Hey,

I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
