### ISSUE TITLE
Dwarf Tactic Stubbornness not showing stat increase on stat doll since Feast of Shoika Patch

### ISSUE THREAD

**Issue by brickib** [WarEmu/WarBugs#20960]
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**

**Testing Screenshots/Videos/Evidences (always needed):**

**Comment by lilimx** [comment]
Hm,

There is no text.

**Comment by lilimx** [comment]
Hey,
I am closing this ticket now as we have not received any further information regarding the problem.
If you are the opinion that the issue still persists, please open a new ticket with proper evidences.
