### ISSUE TITLE
After today's patch corporeal resistance is broken

### ISSUE THREAD

**Issue by bettargh** [WarEmu/WarBugs#20961]
After today's patch, liniment that boosts resistances does not boost the corporeal resistance.

thank you

**Comment by bettargh** [comment]
other buffs as well

**Comment by dihanin** [comment]
and kotbs aura too.

**Comment by lilimx** [comment]
Hey,

any test pics?

**Comment by bettargh** [comment]
Here are two pictures theg first one is before the aegis liniment, the second is after having the liniment consumed
![B4 liniment](https://github.com/WarEmu/WarBugs/assets/106921441/6bb30a38-f8dc-4e4e-8b5a-d9a96a046e04)

![After liniment](https://github.com/WarEmu/WarBugs/assets/106921441/07fdf2a3-8a80-4cb8-b184-27568e274d4a)

**Comment by lilimx** [comment]
Hey,

Uhm the paperdoll stats are no reliable source.
Please check your stats with the command .getstats

**Comment by bettargh** [comment]
Getstats show the correct amount of corporeal, the paperdoll does not work
