### ISSUE TITLE
Auction House Eating Gold No Mail. 

### ISSUE THREAD

**Issue by Sherifina** [WarEmu/WarBugs#20969]
I lost 60 gold trying to buy two stacks of level 38 Unengent Armor Potions. 6/27/23 - Just want the potions if possible if not the gold. Seems to be an overall problem with the mail system today, not sure if it's related. 

Order WL Sherifina

**Comment by Gareth80** [comment]
Yeah, 27/06/2023 i just lost around 800 gold. Trying to buy 5 Potent Talisman of the Mastersmith. And i just want to give back my gold if possible.

Destruction Shaman Betaboi
