### ISSUE TITLE
SH Aimin' Quickly not working properly in midtier / bolster

### ISSUE THREAD

**Issue by bosli42** [WarEmu/WarBugs#20965]
The SH tactic Aimin' Quickly from left path doesn't work reliably in midtier / bolster.
In a scenario, while in combat with nothing happening that should affect any rebolster (no gearswitch, no tactic switch, no pet death/recast) the skills sometimes have long cast times, sometimes short cast times. This can happen so randomly, that if you spam Plink, it can sometimes be fast-slow-fast-slow-fast-slow.

**Comment by lilimx** [comment]
Related to #19137
