### ISSUE TITLE
Bestial Token [Ordor : Chaos Waste]

### ISSUE THREAD

**Issue by XZL00** [WarEmu/WarBugs#20977]
I try to done a side quest for Bestial token but it could not get in my bag after i follow the guide in RoR wiki. 
1st is 'The Key to Success'
one of this seems like broken 
in term of "Click on the smaller 'Battered Strongbox' to receive a 'Bejeweled Skull'." i could not get 'Bejeweled Skull' in my bag after follow the guide, so the Cihtym champion will not spawn.
![361417763_977025110168845_3712201440006253621_n](https://github.com/WarEmu/WarBugs/assets/139710875/22ba7509-7648-4fa4-82c7-afec74d7c01f)

2nd is 'Bigger Bray to Make Your Day'
'Kill 'Kratkar', Bray Shaman level 41, who stands on a hill at 61.5k 25.4k'
I already killed him but could not get any Bestial Token, Then i relogged and killed it again but still nothing in my bag.

in Techniquely i shoud get 2 Bestial Tokens from finished this 2 quests but i got nothing.
Please help , check bug and fix. It will make more motivation for many players that is not just want to kill Destro but want more immersive with this game :) 

Thank you :D

**Comment by lilimx** [comment]
Hey,

the quest is not implemented (that is mentioned in the wiki)
#6102

**Comment by XZL00** [comment]
> Hey,
> 
> the quest is not implemented (that is mentioned in the wiki) #6102

oh crap i think wiki is just not updated. Thank you for make sure that is 'Not implemented yet'.

So I waste my time to proof these are 'Not implemented'
but I still need 2 Betail Tokens and I done every quest without kill 1,000 mobs.
Then all I have to do is just kill 1,000 mobs, right?
Are there any ways to refund Trophy back into a Bestial Token?
I have a suck trophy in my bag and i do not want to keep it in trash. How could i change them back to Bestial Token?
or Is it impossible to do that?

**Comment by lilimx** [comment]
Hey,

nah there is no refund vendor or so. But there are enough other bestial tokens to get. Next time you can use the search function here. Or join our RoR discord :)
