### ISSUE TITLE
Devestator white lion. +160 hit point regen

### ISSUE THREAD

**Issue by Astroice** [WarEmu/WarBugs#2097]
The White lion devestator chest: +160 Hit points every 4 sec does not work

**Comment by Ryanfawkez** [comment]
It's also on the Choppa chest; I'm assuming all MDPS has it. Not sure if it doesn't work, don't have the piece yet.

**Comment by Morksezstop** [comment]
hp regen stat is not implemented yet so it is quite normal to not work... Btw healers has it also on dev body

**Comment by Evildoor** [comment]
#1538
