### ISSUE TITLE
Killed all bosses in Hunters'Vale but didnt get the Credit for my Quests

### ISSUE THREAD

**Issue by Sonny126** [WarEmu/WarBugs#20975]
Hello , i killed all Bosses in Hunter's Vale Today,, got Lockout on the dungeon too but didnt get the Credit for my Quests

Hope u can help me please.

Char Name : Heilluder
Faction : Destruction

**Comment by sherlockandwatson** [comment]
Hi, i had the same problem at BS, i didnt get any influence and the quest didnt count it. (I wona shoes) and after it i had a lockout

**Comment by lilimx** [comment]
#20856
