### ISSUE TITLE
Not 2 Sentinel Jewels

### ISSUE THREAD

**Issue by steoptus** [WarEmu/WarBugs#20973]
https://www.returnofreckoning.com/forum/viewtopic.php?t=51236

![image](https://github.com/WarEmu/WarBugs/assets/51764381/4503bdc5-1abd-4835-8d25-154aa2318928)

![image](https://github.com/WarEmu/WarBugs/assets/51764381/2fbe0570-595a-4c77-85cd-68205f72875c)

![image](https://github.com/WarEmu/WarBugs/assets/51764381/ede8e33b-1c75-40a7-8282-03383f79e4ab)

So in fact, from the beginning I could have 2 Sentinel jewels ? Hahahahahaha

No ?

**Comment by eeppuJ** [comment]
Same as this one : https://github.com/WarEmu/WarBugs/issues/15876
