### ISSUE TITLE
Can't log in some characters

### ISSUE THREAD

**Issue by Harvey3453** [WarEmu/WarBugs#20989]
After updating for the current live event of Twilight's Tide, I can't log in all of my three rr80+ characters, but no problem with other toons under rr80. How can I fix this?

My bugged characters are Ligi, Umman, and Lioney.

**Comment by lilimx** [comment]
Hey,

Please follow this link and add your character here: https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=46249
