### ISSUE TITLE
Spirit resist

### ISSUE THREAD

**Issue by Fortwunty** [WarEmu/WarBugs#2098]
This doesn't always happen, but sometimes my spirit resist just will not increase. I use my buffs, pots, and even when others buff me, it will not go above 200 and change. With every buff I had on it should have around 400+. Yes I use .getstats to check.

**Comment by ozarmidrashim** [comment]
Most buffs do not stack.

**Comment by Fortwunty** [comment]
What? AM buff and a potion should be able to be used together, or else the sorcs and shammies will always have the upper hand. What's the point of buffs if they do not stack? Spirit resist is always lowest.

**Comment by ozarmidrashim** [comment]
I didn't make the rules of the live server. I'm simply telling you that this isn't a bug.
