### ISSUE TITLE
Twilight's Tide Conundrum 

### ISSUE THREAD

**Issue by Tullarus** [WarEmu/WarBugs#20984]
So, during this current event, we have been tasked to craft a rare ring from a green quality. Which over the couple of days I have finally completed. 
![Ring](https://github.com/WarEmu/WarBugs/assets/130717976/260a35ad-177d-453e-b46f-29bfb3510192)

However when I forged said ring, it did not count in the quest chain for the event. 
![Craft](https://github.com/WarEmu/WarBugs/assets/130717976/db1915c3-c26b-46c5-86ba-48afbece1772)

Is there a specific level of the ring I must forge, i.e Level 40 green to 40 blue?

**Comment by lilimx** [comment]
Dublicate #20983
