### ISSUE TITLE
Twilight Tide event: Anullus Ring and normal talisman sloted

### ISSUE THREAD

**Issue by Symbelmyne** [WarEmu/WarBugs#20985]
I'm not sure it is a bug or intentional (if yes should be mentioned in patch notes) that normal talismans (potent talisman of Aggressor)
slotted into new rings disappear after log off.

![Blacklion talisman](https://github.com/WarEmu/WarBugs/assets/16525371/5d1352f2-3cc9-4cec-92b9-91556d8fe03d)

Logged on today morning and talisman is gone.

![Black](https://github.com/WarEmu/WarBugs/assets/16525371/5b48a6bb-a0c5-4ef3-84d1-b518e5e1286f)

**Comment by MaxHayman** [comment]
Fix pending

**Comment by MaxHayman** [comment]
Should be fixed and released
