### ISSUE TITLE
temp freeze inside event vendors area [event][destru] 

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#20982]
entering inside the slaanesh quarteers is a pain atm. Idk if it's happening to me only or to others aswell but attempt to enter resutls in freeze  fo 20 sec inside tunnels section, twice in crash,then while being inside the quarters if you move after some you gona get some smaller freeze about 10 sec. It does happen on all my chars didnt test order side. 

NB: it happen only in this part pf this map in my game, i dont even lag while rvr with lots of ppl and effect on.

**Comment by bosli42** [comment]
Same for me, everyone else I asked does not have problems. Clearing cache and everything regular doesn't help.

**Comment by Tesq** [comment]
closing this , i discovered it was art.myp corruption, i had to redownload the whole thing and let launcher re patch
