### ISSUE TITLE
Twilight Tide event: Craft a Rare Ring objective doesn't unlock

### ISSUE THREAD

**Issue by valkeera** [WarEmu/WarBugs#20983]
Crafing a rare (blue) ring for the Twilight Tide live event doesn't give the Craft a Rare Ring unlock (tested on Silver Amethyst Ring lvl 11).

**Comment by Greigals** [comment]
![image](https://github.com/WarEmu/WarBugs/assets/81819699/06ff4369-7742-4bcd-89eb-5538a65ec768)

I have the same issue as above, attached is a screenshot.

**Comment by Symbelmyne** [comment]
Worth to check if sloted tali also is required for that task to be completed.

**Comment by lilimx** [comment]
Fixed and should be deployed the next few days

**Comment by MaxHayman** [comment]
Should be fixed and released
