### ISSUE TITLE
[Marauder] - Terrible embrace z-axis landing point

### ISSUE THREAD

**Issue by X3hl** [WarEmu/WarBugs#20993]
Issue: stood on the bridge in Phoenix gate and pulled a rune priest using terrible embrace. The rune priest landed under the bridge preventing him from rejoining the fight.

not sure if it is because the landing point is the same z-axis as where he is pulled from or relative to the marauder meaning that it would be within the bounds of the bridge.

Expected behaviour - pulled target would land on top of the bridge

Actual behaviour - pulled target went through the bridge and got stuck underneath.

**Steps to reproduce the problem:**
target should be at one end of the bridge, use terrible embrace to pull to the far end of the bridge, the landing point should be around the start of the arch over the river. 

Video clip (occurs around 15 sec mark) - https://clips.twitch.tv/DifferentCautiousCakeCmonBruh-GW8TTnUwJE5GBou6

**Comment by lilimx** [comment]
Related to #15576
