### ISSUE TITLE
Devour Essence DoK

### ISSUE THREAD

**Issue by Culdu** [WarEmu/WarBugs#2100]
Devour Essence only lasts 5 seconds if first hit hits a target, otherwise it is instantly removed instead of running 5 secs. 
Also compared to old warhammer range seems very low, just like melee range and not a bit more. But perhaps i'm wrong with that(seen it was too high in the begining.)

**Comment by Evildoor** [comment]
There was an issue about range, #1299, and it says that range was fixed. Duration - @ozarmidrashim said that similar skill (Rune Of Battle, RP) will require enemies near your target to work, maybe this is the case here too. Dunno why, let's see what he says.

**Comment by ozarmidrashim** [comment]
Yeah, these are all caused by the same issue - the channelling damage handler only adds effect info to the buff packet if it hits something.
