### ISSUE TITLE
Zealot: Daemonic Fortitude (ability) uses wounds rather than HP for heal amount

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2103]
Daemonic Fortitude incorrectly heals you an amount equal to the wounds increase rather than the resulting HP increase. As an example, when I use the ability gives me an extra 80 wounds which is 800 HP. However, it then only heals for 80 health rather than 800 health.

I don't have a high level Rune Priest to test whether the mirror of this skill (Protection of the Ancestors) has the same issue.

**Comment by ozarmidrashim** [comment]
Also fixed for Protection of the Ancestors
