### ISSUE TITLE
[World Object] The Viper Pit Exit

### ISSUE THREAD

**Issue by moondoggcavalier** [WarEmu/WarBugs#2104]
There is no clickable door to exit The Viper Pit. 
![moondogg_013](https://cloud.githubusercontent.com/assets/15387904/11576849/aa419048-99e7-11e5-8314-0cbd665af1b1.jpg)

**Comment by moondoggcavalier** [comment]
Also have some other things with The Viper Pit, should I make all of those as separate bugs?

**Comment by Evildoor** [comment]
Yes, you should.

**Comment by Evildoor** [comment]
Changelog 17.02.2016
[Other Changes]
- You can now leave the Guild Halls by the doors.
