### ISSUE TITLE
Blackguard Skill None Shall Pass Reverse Damage

### ISSUE THREAD

**Issue by Hauclir** [WarEmu/WarBugs#2106]
![hauclir_122](https://cloud.githubusercontent.com/assets/7598530/11580360/8566758c-99eb-11e5-8869-51839fef0693.jpg)
I had to switch to my Glaive because of this I am surprised this was never reported guess no one uses None Shall Pass....

None Shall Pass is only suppose to damage attackers when the Blackguard blocks an attack and gain hatred, but instead it damage the Blackguard majority of the time when he blocks an attack.

**Comment by Evildoor** [comment]
It was reported for similar skill (Can't Hit Me, BO). Guard damage causes you to hit yourself, which is wrong.
