### ISSUE TITLE
Yet another scenario party problem...

### ISSUE THREAD

**Issue by karvos** [WarEmu/WarBugs#2107]
Hello All,

I have a problem with joining to scenario parties. But the most important thing it happens to me only every second scenario. 1-3-5... everything is ok but 2-4-6... I can't join or my party members can't see me in their grid. 
Do you know any reason of that?

Pls advise.

**Comment by Evildoor** [comment]
There are plenty of reports about this already.
#1138 
#1437 
and maybe some more.
No solution so far. Known things which may help are turning off FixGit addon and trying to join 4-5-6 party (usually people don't join them, so there should be free space in them) before leaving them and joining the normal ones.
