### ISSUE TITLE
Stalker's Runecuffs (Runepriest gloves)

### ISSUE THREAD

**Issue by Fluffmonster** [WarEmu/WarBugs#2112]
Hello,

I recently got the Stalker's set and it came to my mind, that - apparently - the gloves are not detected correctly.

So it is - for example - impossible to gain all of the set given boni, although the set seems to be correctly detected in the tome.

![fluffmonster_033](https://cloud.githubusercontent.com/assets/15823173/11598784/35929afc-9ac4-11e5-8a43-29102904a644.jpg)

**Comment by genisaurus** [comment]
Fixed in next hotfix
