### ISSUE TITLE
[NPC] The Viper Pit Flight Master is Missing

### ISSUE THREAD

**Issue by moondoggcavalier** [WarEmu/WarBugs#2114]
The Viper Pit Flight Master is supposed to be in this location inside The Viper Pit:

![moondogg_015](https://cloud.githubusercontent.com/assets/15387904/11600517/33f86cb8-9a9b-11e5-8c71-7ea6c416f8ce.jpg)
![fm](https://cloud.githubusercontent.com/assets/15387904/11600656/2c52048c-9a9c-11e5-8e2b-ec62626f5e4d.png)

**Comment by Evildoor** [comment]
This was fixed at some point.
