### ISSUE TITLE
Quest: "New Shinies for da Pile" not completing when NPC interacted with

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2118]
The quest named "New Shinies for da Pile" requires you to speak to Sojyvk Stormwind at the Chaos Warcamp in tier 2. The NPC is there but speaking to him does not complete the quest.

**Comment by RoR-Zomega** [comment]
Update: turns out there are 2 copies of this NPC in the tier 2 Chaos Warcamp. One of them triggers the quest completion, the other does not.

**Comment by genisaurus** [comment]
Fixed in next Hotfix

**Comment by Evildoor** [comment]
Same issue as #1838. That ticket description is a bit vague so i don't know, was the second NPC supposed to be removed, or it is OK that there are two of them, or whatever. Let's see what DB team says.

**Comment by RoR-Zomega** [comment]
Just checked that ticket and I hadn't noticed the two NPCs had subtly different names. Considering Meralors has confirmed that the Marauder one (with an i rather than a j) was the correct one for that quest AND when I tried to turn in "New Shinies for da Pile" it only worked on the Marauder and not the Chosen, I would say that the Chosen version needs to be deleted.

**Comment by Malo-RoR** [comment]
Chosen "Soiyvk Stromwind" removed from warcamp.  Should be fixed in next Hotfix.
