### ISSUE TITLE
DESTRO QUEST "Insurrection" PART 3

### ISSUE THREAD

**Issue by Hauclir** [WarEmu/WarBugs#212]
![hauclir_001](https://cloud.githubusercontent.com/assets/7598530/3505411/28b097c2-065e-11e4-8e61-9939180000c3.jpg)
![hauclir_002](https://cloud.githubusercontent.com/assets/7598530/3505412/2acbc798-065e-11e4-82fd-32cb34d0998c.jpg)
NPC QUEST GIVER: Downtrodden Elder
Unable to complete quest until Mark on Map feature works. There is an area where your suppose to stand and watch the scene unfold since the map does not show you where your suppose to stand. You can't make the scene/quest happen. I tried standing next to every gate in Salzenmund and near the gate and nothing happens, possible scene is not working as well. I tried talking to Konrad Schulman afterwards that part worked and was mark completed in the quest objectives.

**Comment by wargrimnir** [comment]
This is completable by clicking on the Castle Gatehouse, at the Inner Gate.
