### ISSUE TITLE
Inevitable City - Monolith area. Portal to Lycithas the Harridan Seer not working

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2120]
Inside the base of the Monolith in the IC where the career trainers are is a portal. Using this portal by interacting with it should teleport you to Lycithas the Harridan Seer who is nearby but not accessable in any other way. There should be a portal in Lycithas's area to teleport you back (I cannot test if this is working as I can't get there to begin with).

**Comment by Gnashspike** [comment]
Seconded: Lycithas appears on my minimap as an available quest-giver, plus it's one of the coolest places to visit within IC. Additionally: if one 'accidentally' fires off a non-target AoE ability near this portal, the portal becomes agro'd and will eliminate the offending player. Seems if it has the A.I. to do that maybe the ability to port a friendly is a simple on/off switch? Good hunting.

**Comment by Kushido** [comment]
Portals now working, you can teleport to location with Lycithas by portal in Monolith. To get out you can use portal under platform with this NPC.
