### ISSUE TITLE
Chapter 13 Greenskin influence rewards not unlocking

### ISSUE THREAD

**Issue by Magicmissle** [WarEmu/WarBugs#2122]
Ch.13 Greenskin influence aren't unlocking, they just sit at "Need more influence" and show no picture for the items, but show that I have reached them in my Tome of Knowledge War Story.

**Comment by taccr** [comment]
As a workaround use the Rally Master in Badlands.That one is working for me.

**Comment by Magicmissle** [comment]
it's not about T3 Greenskin Rally master

**Comment by Magicmissle** [comment]
Can i just up it?

**Comment by Evildoor** [comment]
This is not a forum, where old threads can be bumped to draw attention.

**Comment by Magicmissle** [comment]
At least someone noticed. Create a new topic, I do not want to.

**Comment by Evildoor** [comment]
What are you talking about?

**Comment by vove-RoR** [comment]
> As a workaround use the Rally Master in Badlands.That one is working for me.

He's not talking about the rally master who gives rewards for RvR influence, he means the standard rally master who offers rewards for public quests. Isn't this related to the public quests not working at the moment? Kill collectors offer no quests, in dwarf t3 rally master also offers no rewards for participating in corresponding PQs. I guess this is simply not implemented yet.

**Comment by Torquemadra** [comment]
Fixed next patch
