### ISSUE TITLE
Missing gear including Devestator piece at log in

### ISSUE THREAD

**Issue by Gnashspike** [WarEmu/WarBugs#2127]
Missing Devestator Pumellers and Echelon Slayer, both slotted with blue talis I proc'd last night. Good hunting (filled out CSR appeal but got no response, then got CTD during RvR and couldn't log back in). Good hunting.

**Comment by Evildoor** [comment]
Do not post about lost items on bug tracker. Item loss is a known bug which has no solution so far. Dev policy is "no refunds" for now, so the only thing you can do is hope that when server restarts items will return. If they don't - tough luck, but that's how it stands.
