### ISSUE TITLE
Magnet pulling me through outer and inner Keep doors

### ISSUE THREAD

**Issue by Gnashspike** [WarEmu/WarBugs#2128]
I am frequently pulled through objective doors (including BFOs with doors) by Engineer's Magnet. Incidentally, because I tend not to respawn, remaining a corpse just inside laying under Order's feet so I can describe in detail the who, what and where of the enemy WB make up so we can AoE them with spells similar to BW RoF BUT I'm usually informed that "Dest doesn't have anything like that (RoF), yet I frequently view multiple BWs, frequently 5 or more standing 30 to 50 feet away from inner/outer door, always using available pillars/objects as protective LoS from our AoE through the door at them, and one has to wonder how BWs achieve such 'accuracy'  channeling RoF and not able to see their victims through pillars that LoS them AND Keep walls/doors, in addition to the Molitov pots that we're doused with from above.
Can we please get Magnet and RoF off the 'auto pilot' program? If the corresponding mirrors on my side have the same issues I include them in this request. Good hunting.

**Comment by Evildoor** [comment]
Already reported.
#931 - doors are transparent to AoE.
#1896 - pulls through walls dues to no LoS checks in T3.

Destro has Pits of Shades, exact mirror (with other damage type) of Rain Of Fire.
