### ISSUE TITLE
Supplication/Blood Offering

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#2130]
These abilities can be used at full RF/SE, even though client tells you that you cannot.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
