### ISSUE TITLE
Inevitable City: Jump destination 168938792 does not exist.

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2132]
Location: behind a door at 27.5k x 41.5k near the guild vault and mailbox.

I have no idea where this portal is supposed to send you - I discovered it by accident when exploring the IC.

**Comment by Kushido** [comment]
Atm this portal not usable. Closing door for now, door ID=169012456, guid 250219, GO 2

**Comment by moondoggcavalier** [comment]
I believe that portal would send you outside the city.
