### ISSUE TITLE
Inevitable City: Mushroom Hunta quest is missing an objective

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2133]
http://war.mmodb.com/quests/mushroom-hunta-602.php

RoR is missing the "Green Gooey Mushroom" objective from the "Mushroom Hunta" quest handed out in the IC. One of the mushroom can be found at 52.8k x 35.8k in the room with the "Transformed Acolyte" NPC and there's another nearby in the room with "Shargra Glutmire".

RoR correctly spawns the mushrooms, it's just missing them from the quest.

**Comment by Meralors** [comment]
Added Green Gooey Mushroom as condition to match original quest.
