### ISSUE TITLE
Inevitable City: "Klieg Marthruss" NPC has 6 empty quests

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2135]
Location: 29.5k x 32.5k (at the bottom of the ramp that leads to the Flight Master).

Talking to the NPC named "Klieg Marthruss" brings up 6 empty quests (shown in attached image). Clicking on the entries does nothing.

![klieg marthruss](https://cloud.githubusercontent.com/assets/15970235/11610877/1270fb32-9ba9-11e5-8762-9ee02e26a1fb.jpg)

**Comment by DanaBloodkiss** [comment]
The quests were deactivated for now.
