### ISSUE TITLE
Pets affected by buffs

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#2136]
![tur](https://cloud.githubusercontent.com/assets/13823154/11611315/50712e84-9bc7-11e5-9caa-7dc99bf4cd18.jpg)

**Comment by ozarmidrashim** [comment]
Pets count as group members for the purpose of group-affecting effects, of which FoR is one.

**Comment by Evildoor** [comment]
Not a bug, it was this way on life.
