### ISSUE TITLE
Engineer T3 Influence Helmet (EMPIRE) Missing stats

### ISSUE THREAD

**Issue by mursie** [WarEmu/WarBugs#2137]
Hi,

I likely think this is the case for all classes helmets - but I did research and found that the ThickMuck and Passwatch influence helmets in T3 are missing stats for engineer.

Currently both helmets in T3 have the exact same stats and tali slot.  The missing stat is as follows:
1. Thickmuck Hardhat - 2% ranged crit (please see here:  http://www.arsenalofwar.com/armor/Order/Thickmuck%20Hardhat)
2. Passwatch Hardhat - 2% defensive stat (no database currently has this item as it was basically never taken back on live)

**Comment by saupreusse** [comment]
Fixed all thickmuck helmets.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/5494
