### ISSUE TITLE
PQ DarkElf Ch9 - Tor Elyr missing influence mobs

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#2138]
Currently the only mob to give influence for this PQ is Elyr Resident

Add the following which are found nearby

Elyr Noble
Ellyrian Defender
Ellyrian Guard
Ellyrian Commander
Ellyrian Archer

**Comment by Meralors** [comment]
This is linked to PQ right now, I dont think we can fix it till we fix PQ

**Comment by wargrimnir** [comment]
Thought that would be the case, I held off on noting the other PQ's that have similar issues.

**Comment by wargrimnir** [comment]
Would it be possible to replace several of the mobs with Elyr Residents as a temporary solution until PQ's are correctly working? That could improve the quality of several PQ's if the primary mob for them was in good enough numbers to at least farm efficiently.

**Comment by Torquemadra** [comment]
"fixed" next patch
