### ISSUE TITLE
Essence Lash hit more times than supposed to

### ISSUE THREAD

**Issue by zabis** [WarEmu/WarBugs#2139]
We were in Tor Anroc scenario, this ability hit Argryn and Xtxx
http://imgur.com/0wgaxIP

**Comment by ozarmidrashim** [comment]
Exception thrown, will need to check the logs. Nice of the DoK who triggered the exception not to report it (if an ability throws an exception, the player in question receives information about it, and this happens because it would help me to know the information)

**Comment by zabis** [comment]
It was my DoK

**Comment by Abolition** [comment]
This isn't helpful at all, but I have also experienced this bug with Slayers once or twice. It's not helpful because I cannot remember the name of the Ability off the top of my head (it's been a couple of weeks since last happened). Will post if it happens again.

**Comment by Evildoor** [comment]
@Abolition - Wild Swing?

**Comment by Abolition** [comment]
Wild Swing does sound pretty familiar, but I couldn't say with 100% certainty, I'm afraid.

**Comment by Evildoor** [comment]
I'm pretty sure it is, because:
1) Both Swing and Lash are simple AoE attacks.
2) IIRC, i've seen similar screenshot with Wild Choppin destroying people, and Wild Swing is Wild Choppin' s mirror.

**Comment by Abolition** [comment]
It could have been fixed. As I said, I haven't had it happen to me in the past couple of weeks.
Sorry it's not much help. I wouldn't want the devs spending time looking into a bug that they fixed a while ago.

**Comment by ozarmidrashim** [comment]
Apologies, Zabis - I assumed the screenshot was from your perspective.
