### ISSUE TITLE
Not getting bolstered to 26 once you hit 21 in t2.

### ISSUE THREAD

**Issue by Renork** [WarEmu/WarBugs#2142]
Once you hit 21, you do not get the level 26 bump in scenarios or any of the t2 pvp zones.

**Comment by Heteryk** [comment]
shouldn't be bolster lovered to t2 max lvl anyway if it is still 26? (can't check how it is im already over that lvl) I remember I had same issue but i thought it's just visual and lvl up then i got bolstered to 31 - so maybe there is some kind of gap in boloster.

**Comment by Renork** [comment]
It should be 21, but right now it bolsters people to 26. The problem is once you hit 21 then you're fighting bolstered lv 26 people :>

**Comment by Renork** [comment]
This is now fixed, thanks to whoever took care of it so fast :)
