### ISSUE TITLE
Aura spread failure

### ISSUE THREAD

**Issue by Laurell-Silentshade** [WarEmu/WarBugs#2143]
Was dced and unable to use wp aura after relog.

**Comment by Laurell-Silentshade** [comment]
Relogging again corrected the issue, but I suppose it should still be reported that it did and can happen.

**Comment by Evildoor** [comment]
#1385. You were in WB?

**Comment by Laurell-Silentshade** [comment]
I was when the dc happened.

**Comment by Evildoor** [comment]
Then i see nothing new compared to #1385. Closing.
