### ISSUE TITLE
Effects changing armor value are not properly displayed in character sheet

### ISSUE THREAD

**Issue by 0drew0** [WarEmu/WarBugs#2146]
Assault Stance's skill is not working as it should. In describing a game written: "increases your armor amount that you receive from item". The game is no gain armor. Everything else like works. Please contact us fix this skill that he added armor on the official server. Knowledge Base - http://waronlinebuilder.org/#career=sw.

**Comment by Evildoor** [comment]
Armor from stance is applied, but does not shows in the character panel until you change your stats somehow - for example, equip a new item. Use .getstats (in Say chat, you must target yourself) to get more reliable information about stats, it shows the bonus armor properly.
