### ISSUE TITLE
"Tomes of the Raven" interactable object hovering in the air.

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2148]
Location: Norsca, 31k x 12.5k (Chaos starting area)

This world item is incorrectly hovering in the air and needs to be lowered.
![tomes of the raven](https://cloud.githubusercontent.com/assets/15970235/11614151/4d114412-9c31-11e5-8dbf-c87a2fde9fe2.jpg)

**Comment by Torquemadra** [comment]
Checked this, someone fixed it on test at least.
