### ISSUE TITLE
Raven's are "proper" NPC enemies rather than trivial one-hit-kill mobs (Chaos starting area)

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2150]
In the Chaos starting area there are a number of Raven mobs. If I remember correctly from live these are supposed to be trivial level 1 one-hit-kills (like the bunnies and other trivial NPCs) but instead they are full enemies that drop loot.

**Comment by Evildoor** [comment]
This also applies to ravens in different zones (DvG T3, for example).

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
