### ISSUE TITLE
"Kaltira the Daemoncaller" offering the "Training Course" quest too early.

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2151]
Location: Chaos starting area.

Correct action: "Kaltira the Daemoncaller" gives the player 3 quests to do ("Dark Fate", "To Conquer" and "The Heart of Battle"). Once all 3 have been completed she should hand out the "Training Course" quest which moves the player to the next area.

Bug: The "Training Course" quest is handed out when "Dark Fate" is completed even though "To Conquer" and "The Heart of Battle" have not yet been finished.

**Comment by Natherul** [comment]
@Luth-RoR currently not fixable.
