### ISSUE TITLE
"Restless Dead" mobs dropping "Bones of the Dead" when quest has been completed

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2152]
Location: Chaos starting area

Correct behaviour: These items should only be dropped when the player is currently doing the "Dark Fate" quest (and ideally should stop dropping if the player already has enough to complete the quest).

Bug: the "Restless Dead" mobs always drop "Bones of the Dead" even if the quest has been completed (did not test whether they drop them before you accept the quest).

**Comment by Evildoor** [comment]
DB team informed me that this kind of problems cannot be fixed for now.
