### ISSUE TITLE
Quest "To Conquer" doesn't update the minimap red zone when all objectives reached

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2155]
Location: Chaos starting area

Correct behaviour: once 5 "Awakened Spirit" NPCs have been slain the red zone should change from the crypt to the NPC who gave the quest ("Kaltira the Daemoncaller").

Bug: the red zone remains over the crypt.

**Comment by Heteryk** [comment]
I think most of quests don't update on minimap when objectives are reached. It is for sure in Badlands and Black Fire Pass, where i was doing quests lately. We can assume it's common.

**Comment by RoR-Zomega** [comment]
Doing chaos chapter 1 at the moment and most of them do seem to update there. Could be that those bug reports have already been submitted/fixed where-as Badlands/BFP hasn't had as much testing or reports.

I'm going to keep reporting them until told otherwise :P

**Comment by Heteryk** [comment]
Seems good for me :D

**Comment by DanaBloodkiss** [comment]
This is a general problem. I will close it for now. Please don't continue reporting it.
