### ISSUE TITLE
"Ancestral Chronicle" interactable object for "The Heart of Battle" has a 2m respawn time.

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2156]
Location: Chaos starting area, crypts

The "Ancestral Chronicle" item needs to respawn a lot quicker than it currently does. I've just timed it and it seems the respawn timer is 2 minutes, meaning if 3-4 people are trying to complete the quest at once then some players will be waiting an age to get the item.

Please lower the respawn to something more sensible such as 5-10 seconds (or better yet, instant).

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
