### ISSUE TITLE
[Item] Inf rewards Badlands

### ISSUE THREAD

**Issue by Hekireki** [WarEmu/WarBugs#2160]
Kazza, the NPC, gives us the same rings for the basic reward (T3, orc, inf) Grol Baraz Boyz' Chain is the same as Grol Baraz Dark Band (both blue, same exact stats, level, etc). And the epic ones, Tickmuch Boyz' Chain and Thickmuck Dark Band are exactly the same, it's a bug. 
Thanks

**Comment by Evildoor** [comment]
#1933
