### ISSUE TITLE
Incorrect colour of icon above quest-giving NPCs (general issue)

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2161]
Note this has been raised before (#66) but it was closed so I'm reposting. It is the same issue (and I discovered it on the same quest). I did a quick search and I couldn't find a general open issue on it (if there is then please close this report).

Quest giving NPCs generally have 3 different icons that can appear over their head. Those icons are:

Green: Quests available
Grey: Quests in progress
Orange: Turn in a completed quest here.

As only one of these icons can be displayed at once, the priority from highest to lowest is: Orange, Green, Grey. However, RoR seems to prioritise Green before Orange (I have no idea about Grey). I've attached a recent image showing that this is still an issue. "The Eidolon" should have an Orange marker above his head as the "Daemonic Strength" can be turned in but instead he has a green icon for the "Pillaging" quest.

![quest icons](https://cloud.githubusercontent.com/assets/15970235/11614413/226c4500-9c3a-11e5-8a49-75943a3b9279.jpg)

**Comment by RoR-Zomega** [comment]
Update: regarding the grey icons, they don't seem to display at all (at least not in the Chaos Chapter 1 warcamp).

Madgar the Soul Reaper: No grey icon over his head once the "The Soulreaper" and "The Heart of Battle" (part 2) quests have been started.
Grimnot 'Eadbasher: Missing grey icon once the "Destruction" quests has been started

etc, etc.

**Comment by Evildoor** [comment]
Next time - do not repost, use the existing ticket and we will reopen it. I agree that #66 was closed for no reason.

**Comment by RoR-Zomega** [comment]
Sorry, didn't know if you wanted very old tickets re-opened or not. If I find any more that have been closed I'll use the old tickets instead :).

**Comment by Evildoor** [comment]
Found out that this was reported: #1306. Closing.
