### ISSUE TITLE
"Daemonic Strength" map red zone incorrect when quest can be handed in?

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2162]
When the quest objectives have been completed (2/2 Dwarfen Gyrocopters) the red zone changes to a red circle around the chapter 1 camp (the red circles usually indicate an area where you complete the objectives, not turn in the quest). Should this instead be a red bullet/quest icon where the "The Eidolon" NPC (the one who you turn the quest in to) stands instead? AoR/RoR seems to have no real standard for this...

**Comment by DanaBloodkiss** [comment]
That's a general bug which cannot be fixed yet.
