### ISSUE TITLE
"Daemonic Strength" quest reward potions bugged/incorrect

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2163]
2 issues in 1 here:

1): The tooltips for the two potions have no effects listed.

2): The pink potion is named "Fleeting Initiate's Fleeting Elixir of Allaying". Seeing as the red one is "Initiate's Fleeting [etc]" the first "Fleeting" probably needs to be removed from the purple potion.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
