### ISSUE TITLE
"Pillaging" quest rewards bugged

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2165]
Location: Chaos chapter 1

Out of the 3 quest rewards for this quest, 2 are bugged. The bugs are:

1) Initiate's Fleeting Corporeal Screening Potion: has no stats
2) Cracked Bladebelt of the Flesh: has an item type of "both hands" but it is a belt.

Tested with Disciple of Khaine - quest rewards may vary for other careers.

**Comment by Ryanfawkez** [comment]
Fixed. Potions do not work yet, however.
