### ISSUE TITLE
"Destruction" quest - buildings are always on fire

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#2166]
Location: Chaos chapter 1.

There's already bugs open about this quest but I'm adding a new one. The buildings by the "Kindling" objects should only be set on fire once the "Kindling" object next to it is used as part of the "Destruction" quest. The fire goes out a short time afterwards. IIRC the fire going out tied in with the corresponding "Kindling" object being usable again.

Currently some of the buildings are always on fire and some are never on fire which is incorrect.

**Comment by MaxHayman** [comment]
@Lheana did this actually work on live?
