### ISSUE TITLE
"Blood" quest has wrong NPC as kill objective

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2167]
Location: Chaos chapter 1

The "Blood" quest objectives say that you need to kill 5 "Empire Spearman" NPCs. However the fluff text for the quest says you need to kill 5 "Thorshafn Citizen" NPCs. The objective needs to be changed from the spearmen to the citizens (the citizens are in the same area as the spearmen).

**Comment by Meralors** [comment]
Actually the objectives is right, description was not. Changed text to match objective
