### ISSUE TITLE
"Wizard Lord Mathus" NPC at the "Ruinous Powers" PQ should not be attackable.

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2169]
Location: Chaos chapter 1.

I know PQs are bugged in general, but this NPC should never be attackable. In the actual PQ he spawns at the start of stage 3, kills the Chaos NPCs in the summoning area and then gets one-shot by the spawn that appears.

Can the NPC be set to invincible and/or hidden until PQs are fixed?

**Comment by Natherul** [comment]
Currently not possible to script NPCs but he is now hidden until the last stage where he is supposed to spawn

**Comment by Luth-RoR** [comment]
Thanks, closing.
