### ISSUE TITLE
"Ruinous Powers" PQ has far too short of a timer on stage 3

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2170]
Location: Chaos chapter 1

The timer on stage 3 to kill the giant spawn is about 70 or 80 seconds which is far too short for anything other than a load of people. Can the timer be increased to 180 seconds? Should give small groups enough time to take it down with non-optimal career choices.

**Comment by Razielhell** [comment]
@Luth-RoR This can close i guess.
