### ISSUE TITLE
"Ruinous Powers" PQ stage 3 boss spawns in wrong location

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2171]
Location: Chaos chapter 1

Yes I know PQs are bugged in general but it seems some work has started to get this one going :).

The giant spawn that appears in stage 3 is supposed to appear in the middle of the summoning circle pit (where the "Eye of Change" interactable object is). Currently it incorrectly spawns at the outside/top of the pit around the grave stones and empire NPCs are.

**Comment by Razielhell** [comment]
@Luth-RoR This can close.
