### ISSUE TITLE
"The Soulreaper" quest doesn't update map red-zone when objectives are completed

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2172]
Location: Chaos chapter 1

When the objective is complete (kill 5 Defiant Souls) the red zone remains over the kill area instead of changing back to the quest giver/completer ("Madgr the Soulreaper" in the chapter 1 warcamp).

**Comment by DanaBloodkiss** [comment]
This is a general problem. I will close it for now. Please don't continue reporting it.
