### ISSUE TITLE
"The Heart of Battle" (part 2) quest doesn't update map red-zone when objectives are completed

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2173]
Location: Chaos chapter 1

When the objective is complete (kill 3 Thorshafn Ancestors) the red zone remains over the kill area instead of changing back to the quest giver/completer ("Madgr the Soulreaper" in the chapter 1 warcamp).

Same NPC as #2172.

**Comment by DanaBloodkiss** [comment]
This is a general problem. I will close it for now. Please don't continue reporting it.
