### ISSUE TITLE
"Promise of Power" uses incorrect NPC to complete quest

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2174]
Location: Chaos chapter 1

The fluff text says the quest needs to be turned in to "The Eidolon" (chaos chapter 1 warcamp) but the completion has been incorrectly assigned to "Madgr the Soulreaver". It needs to be changed so that the quest completion is with "The Eidolon".

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
