### ISSUE TITLE
"Promise of Power" quest rewards are bugged.

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2175]
Location: Chaos chapter 1

Out of the 3 quest rewards for this quest, 2 are bugged. The bugs are:

1) Initiate's Fleeting Corporeal Screening Potion: has no stats
2) Cracked Bladebelt of the Flesh: has an item type of "both hands" but it is a belt.

Tested with Disciple of Khaine - quest rewards may vary for other careers.

Note: exactly the same as #2165 but with a different quest.

**Comment by Ryanfawkez** [comment]
Fixed. Potion reward does not work yet, however.
