### ISSUE TITLE
"Show of Power" NPC spawns in wrong location

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2176]
Location: Chaos chapter 1, 43k x 13k

The quest text says that the "Bright Wizard Acolyte" is at the top of the tower. However, the NPC actually spawns outside of the tower. I've checked the top of the tower and there is no NPC in there.

The "Bright Wizard Acolyte" NPC outside needs to be moved into the tower.

![show of power](https://cloud.githubusercontent.com/assets/15970235/11614773/e2088af4-9c44-11e5-91d4-da84d1605cb2.jpg)

**Comment by Meralors** [comment]
Corrected target npc location to match quest description.
