### ISSUE TITLE
"Show of Power" quest doesn't update map red-zone when objectives are completed

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2177]
Location: Chaos chapter 1

When the objective is complete (kill the Bright Wizard Acolyte) the red zone remains over the kill area instead of changing back to the quest giver/completer ("Madgr the Soulreaper" in the chapter 1 warcamp).

Same NPC as #2172 and #2173

**Comment by DanaBloodkiss** [comment]
This is a general problem. I will close it for now. Please don't continue reporting it.
