### ISSUE TITLE
"None Shall Escape" quest incorrect name, description and objectives

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2178]
Location: Chaos chapter 1

http://war.mmodb.com/quests/none-shall-escape-us-167.php

Quest name: Should be "None Shall Escape Us"
Quest description: as per link above
Quest objectives: kill the empire courier (should be the only objective)
Quest completion NPC: Surtsen the Deceiver (shouldn't be listed in the quest objectives)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
