### ISSUE TITLE
"Altar of the Raven" displaying as "ToKUtilityMob" in the world

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2179]
Location: Norsca, 32.5k x 26.5k

This world object has an incorrect name hovering above it. I don't know if the name or the entire thing should be hidden (my ToK knowledge is very limited).

![tokutilitymob](https://cloud.githubusercontent.com/assets/15970235/11614913/b5d65768-9c49-11e5-8acb-c8f6a3f52c12.jpg)

**Comment by DanaBloodkiss** [comment]
Fixed in next.
