### ISSUE TITLE
Backpack overflow check not looking to see if items can be stacked

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2180]
Example: I had 2 spaces left in my back-pack and looted a mob that dropped 3 different items. However, one of the items was stackable and I already had a stack (not at max) in my backpack. The server wasn't able to correctly assess that I had space and required me to have 3 empty backpack slots even though I only needed 2.

Please can the overflow check have a look to see if looted items actually need an empty slot?

**Comment by magicthighs** [comment]
The exact same thing happened on the live servers.

**Comment by Evildoor** [comment]
If magicthighs's comment is correct then this looks like a client issue, so i'm closing this.
