### ISSUE TITLE
"The March" quest doesn't update map red-zone when objectives are completed 

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2181]
Location: Chaos chapter 2

When the objective is complete (kill 5 Seared Gouls) the red zone remains over the kill area instead of changing back to the quest completion NPC ("Haldar" the Rally Master in the chaos chapter 2 warcamp).

**Comment by DanaBloodkiss** [comment]
This is a general problem. I will close it for now. Please don't continue reporting it.
