### ISSUE TITLE
"Foul Works" quest doesn't update map red-zone when objectives are completed

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2182]
Location: Chaos chapter 2

When the objective is complete (loot 7 Charred Spores) the red zone remains over the kill area instead of changing back to the quest completion NPC ("Sursten the Deceiver" in the chaos chapter 2 camp).

**Comment by Evildoor** [comment]
I had a discussion with the DB team, and they don't know how to fix such kind of problems yet.

**Comment by RoR-Zomega** [comment]
Do you still want me to report them as I find them?

**Comment by Evildoor** [comment]
I think you can leave them be for now and focus on other things.

**Comment by DanaBloodkiss** [comment]
This is a general problem. I will close it for now. Please don't continue reporting it.
