### ISSUE TITLE
Some Chaos chapter 1 influence rewards are bugged

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2183]
Location: Chaos chapter 1, The Eidolon (Rally Master)
Career: Disciple of Khaine

Bugged items:

1) Initiate's Lasting Screening Potion: has no stats
2) Initiate's Draught of Allaying: has no stats
3) Ravenscribed Chalice: missing soul essence regen (I cannot remember what the regen is for green chalices)

**Comment by Evildoor** [comment]
Chalices/Books do not display resource regen in RoR, so you don't need to report them individually.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
