### ISSUE TITLE
"Altar of the Decay" displaying as "ToKUtilityMob" in the world

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2184]
Location: Norsca, 42.5k x 33k

This world object has an incorrect name hovering above it. I don't know if the name or the entire thing should be hidden (my ToK knowledge is very limited).

Note: same issue as #2179 but with a different object.

![tok2](https://cloud.githubusercontent.com/assets/15970235/11615095/e0f1b532-9c4e-11e5-938a-7ddb96c49c40.jpg)

**Comment by DanaBloodkiss** [comment]
Duplicated https://github.com/WarEmu/WarBugs/issues/2179 and fixed.
