### ISSUE TITLE
DoK: using "Restore Essence" on an NPC causes an animation and cast bar bug

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2185]
Replication steps:

1) Go to Chaos chapter 1 camp with a DoK
2) Cast Restore Essence on The Eidolon (Rally Master)

The character gets stuck in this animation loop (see attached image) until you cast something on a valid target (i.e. not an NPC) or attack something. In addition, the cast bar does not vanish until you somehow clear the animation.

![restore essence](https://cloud.githubusercontent.com/assets/15970235/11615116/b1fc4cb4-9c4f-11e5-850f-33fcefa7cede.jpg)

**Comment by Evildoor** [comment]
#1275
