### ISSUE TITLE
"Monolith Portal Effect" in IC is a R39 NPC that will attack you

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2186]
Location: IC, Monolith, 22.5k x 37k

Above the "Portal" interactable object is an NPC named "Monolith Portal Effect" which can be targeted (only via tabbing - it cannot be clicked on) and attacked. It will likely kill you. The NPC needs to be friendly and invisible (or just removed if not important).

Referenced in #2120 in a reply but it has absolutely no relation to the bug mentioned in #2120 so I've created a new issue.

**Comment by DanaBloodkiss** [comment]
Fixed in next Hotfix.

**Comment by RoR-Zomega** [comment]
Now that the portal is usable and takes you to Lycithas the Harridan Seer, I've discovered that the portal you use to return has the same issue. Were all of the "monolith portal effect" entries fixed or do you want me to raise a new issue for this new one?

**Comment by DanaBloodkiss** [comment]
I fixed all of them. Included in next Hotfix.
