### ISSUE TITLE
[Shadow Warrior] [VON+Seady Aim]

### ISSUE THREAD

**Issue by papsbug** [WarEmu/WarBugs#2187]
Maybe it is onli me but every time i buff my self with thos two at same time i cant switch stances till buffs go off.

**Comment by Qrazy** [comment]
Just tested using both and could change stances but there was a noticeable delay. Using steady aim on it's own seems to cause the delay.

**Comment by Evildoor** [comment]
It seems that Steady Aim affects stances, while by description it should only affect damaging abilities.

**Comment by papsbug** [comment]
Yea gess it give some hiden, cast time to stance change or something.
Tested with no lag, it is not von+sa it is just steady aim. Animation is ok it is instant, but dependent skills  are geting 1.5 sec usage delay.
