### ISSUE TITLE
T1 Lair drops items for opposing realm

### ISSUE THREAD

**Issue by Nozzqt** [WarEmu/WarBugs#2188]
Seems to be bugged, killed 9 bosses and either they drop nothing or they drop Dwarf stuff, not sure if intended or that I am just unlucky?

**Comment by Evildoor** [comment]
I don't know what's the chances of getting nothing compared to getting an item from these bosses, but Dwarf classes are 1/3 of Order classes, and 9 tries is not that much...

**Comment by Nozzqt** [comment]
Yeah, I might have been unlucky, but one of the guys I have been going with hasn't seen a helmet from the boss in Ekrund for 2 weeks and dwarf stuff kinda suck when your playing Destro.

**Comment by Evildoor** [comment]
Well, Dwarf stuff on Destro is another matter.

**Comment by Evildoor** [comment]
Oh, but that matter was already reported: #518.
