### ISSUE TITLE
[Slayer][Influence Rewards][T3 Empire]

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#2189]
The Thickmuck War Shroud and the Passwacht War Shroud have identical stats. I don't think thats intentional.

**Comment by Styrkarr** [comment]
I don't find any info about Passwacht War Shroud stats, so i can't say if it's normal or not. If someone find it, just share ! ;)

But i found a missing stat on Thickmuck War Shroud (2% melee crit is missing). It'll be fixed on the next patch.

**Comment by wargrimnir** [comment]
Added Disrupt to all Passwatch Shoulders
