### ISSUE TITLE
Random lag spikes which lead to disconnects

### ISSUE THREAD

**Issue by hartmnj1** [WarEmu/WarBugs#2190]
I keep experiencing random lag spikes that last longer than 10 seconds and they will dc me. If I log back on, it is only a matter of a few minutes before this happens again.

**Comment by roadkillrobin** [comment]
Samae here. happens when i play on a mobile connection.

**Comment by Evildoor** [comment]
Most likely this problem is on your side, especially if we consider this:

> happens when i play on a mobile connection.

Closing.
