### ISSUE TITLE
Multiple side entrances not working

### ISSUE THREAD

**Issue by Shadowgurke** [WarEmu/WarBugs#2191]
Destro side seems to be unable to use any postern doors in T3. I am not sure about Order but apparently they can use them. I believe this is a high priority bug to fix, since it makes defending already sieged keeps almost impossible

**Comment by Vigfuss** [comment]
I don't want to pressure the devs on this, but is there an eta on this one?  It would be at the top of my list for bringing ORVR back in T3.

**Comment by Petricius** [comment]
On Order side - Talabecland - both side doors seems to be "Destro" and unavailable to use.
![grombrrindal_031](https://cloud.githubusercontent.com/assets/17072092/12827510/67a5fb14-cb80-11e5-83bb-be1d3d61ef4b.jpg)

**Comment by Soulwhisper** [comment]
Pick Lock doesnt work either for WH on all doors.

**Comment by Soulwhisper** [comment]
Reporting here after 6th of March patch.Postern doors still buggy in Passwatch Castle.

**Comment by Evildoor** [comment]
Changelog from 21.03.2016 (a bit late :P ).

[Keeps]

- Fixed all postern doors.
