### ISSUE TITLE
[Quest]: An Army Marches

### ISSUE THREAD

**Issue by Heteryk** [WarEmu/WarBugs#2196]
Two quests you get from one npc has the same name (description is different). Dunno if that should be like that.

![rahgal_060](https://cloud.githubusercontent.com/assets/16116091/11624011/0579b53a-9cd1-11e5-9828-928641ec2965.jpg)
![rahgal_059](https://cloud.githubusercontent.com/assets/16116091/11624012/07c69542-9cd1-11e5-813f-7d63613f342d.jpg)

**Comment by Meralors** [comment]
Quest line should now works correctly.

**Comment by Torquemadra** [comment]
Quest line did not work properly, does next patch.
