### ISSUE TITLE
[Slayer][Stalker Armor Set Boni]

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#2198]
The 4 piece bonus on the Stalker set for slayer is currently +2 morale, which is the 4 piece bonus for tanks. I don't know if this was a balance change or bug but according to 

https://gaarawarrgabs.wordpress.com/2009/03/08/definitive-guide-to-armor-sets-in-war/

the 4 piece bonus should be on hit proc called Bewildering.

**Comment by Evildoor** [comment]
Procs are not implemented yet.
