### ISSUE TITLE
elixir of the couldron

### ISSUE THREAD

**Issue by vithoria** [WarEmu/WarBugs#2199]
either there is some default bug on the abillity or els the AM's is startin to cheat since they knoc me away while the abillity is active, and dot me up

**Comment by Talissera** [comment]
Vithoria, sometimes it happens, when the target has knock immune because of previous knock/force push/silence/...
It is really annoying when I do the same with sorc or especially squig herder, who don't stop and whom almost impossible to stop due to high damage and bad snare from shot.

**Comment by Chummi** [comment]
i already told you how it worked when you were rage whispering me. no need for being salty and those false cheat "accusations". the skill works fine. it was simply my reaction time which outplayed you in the above mentioned fight. you messed EoC up. you didn't use it within the gcd of your opener and i knocked you back a split second before you used KD + EoC. the KD ran out before you could close the gap and you got kited.

**Comment by Evildoor** [comment]
Ah, so it was like that? Sigh. Closing.
