### ISSUE TITLE
[Influence] Dwarf chapter 6 has no way to obtain influence

### ISSUE THREAD

**Issue by Ryanfawkez** [WarEmu/WarBugs#2200]
The PQs in Dwarf Chapter 6 are all broken to the point where no NPC awards influence upon kill.
Battle at the Blood Fen has no objective for killing Greenskins, yet Destruction has the Order side objective by which killing the Dwarfs also awards no influence. Marsh Conquest has no Greenskin NPCs to kill despite its objective; Destruction also has the Order objective by which killing the Dwarfs grants no influence. Assault on Coal Ridge Depot is stuck on stage 2, and the Signal Flare boxes have no use for awarding influence per objective.

**Comment by Torquemadra** [comment]
Addressed to some extent next patch
