### ISSUE TITLE
Wrong Item Icon for Dwarf Chapter 14 Influence Reward Deatherseeker's Cloak

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#2201]
The Deatherseeker's Cloak has the icon of a piece of jewerly in the tome of knowledge, and almost fooled me to pick it up after 2 hours of influence grinding :)
Edit: I forget, at least for Slayers it looks like that. I don't know for the other classes.

**Comment by Meralors** [comment]
Fixed, live next patch ;)
