### ISSUE TITLE
[Slayer][Empire Chapter 14][Influence Reward]: Bonebreaker's Armbraces missing some stats

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#2202]
I might be wrong but only +9 Strength on blue lvl 27 gloves doesn't sound right.

**Comment by Styrkarr** [comment]
I can't find any info about Bonebreaker's Armbraces stats. If someone have it, just share ! ;)

**Comment by wargrimnir** [comment]
Fixed some time ago
