### ISSUE TITLE
[quest] restoring lifes balance

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#2210]
t2 high elf chapter 6, no way to obtain the key from the bloodhags

**Comment by Meralors** [comment]
Fixed this quest so it can now be completed.
Also fixing the following one so the npc are not fighting each others

**Comment by wargrimnir** [comment]
Currently broken. Prisoners fighting, not able to interact with them.

**Comment by Thayli** [comment]
The prison bindings are a game object, you do not need to interact with the prisoners themselves. This quest can be completed.
