### ISSUE TITLE
Focus Mind doesn't provide immunity to Magus AOE pull

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#2211]
Focus Mind doesn't provide immunity to Magus AOE pull

tested on SW in scenario vs Magus aoe pull.

**Comment by taccr** [comment]
It's not supposed to provide immunity against punts and pulls.

**Comment by Evildoor** [comment]
Description does not includes pulls and knockbacks. However, it also does not includes knockdowns, and in another report people were saying that on live it granted immunity to them.

**Comment by taccr** [comment]
You were immune to everything but punts and pulls back on live.

If you consider the stun/stagger immunity a bug is up to you. It does not state the immunity in the tooltip.

However the same goes for some mara tactics that were implemented with the tooltip version and not the live version.
You have to make a decision if you consider a wrong tooltip a bug or not. I can list many more examples but you should get my point.

**Comment by Evildoor** [comment]
The dev team makes a decision in each individual case. We'll see what @ozarmidrashim says about this.

**Comment by gittoaster** [comment]
@taccr it most certainly does, including Mara/WL pulls, M4 aoe punt (eg SM).

Possibly, the ability it would not work against was undefendable root.

**Comment by taccr** [comment]
No it does not. FM is not a renamed version of RD.
Feel free to provide proof it you are so convinced.

**Comment by Morksezstop** [comment]
I confirm that FM was working vs all CC exept pulls and punts. It wasnt written on the tooltips but was that way on WAR and i presume mythic made that intendedly but no idea why they didnt fix the tooltip, prolly noone ever reported it

**Comment by milosxe** [comment]
FM gave immunity to anything that gave you unstoppable buff, and immunity to roots. As taccr said, you only didn't get immunity to knockbacks and pulls.

**Comment by ozarmidrashim** [comment]
Closing per 3-1 consensus.

**Comment by gittoaster** [comment]
just ask yourselfs who play classes with FM, don't you ever use FM vs Mara pull.  You watch that thing come at you then 1.5-ish seconds later you watch it fall off?  Same with the Magus pull.. I use it and I am the only one left NOT pulled.  
I hope someone can find evidence of that.

**Comment by gittoaster** [comment]
FM should work against Marauder pull because TE is classified as a spell, therefore covered by the disrupt component of FM.  I will gather video if possible.  thx
