### ISSUE TITLE
Passwatch Outer can be bypassed easily.

### ISSUE THREAD

**Issue by magter3001** [WarEmu/WarBugs#2212]
Made a video on where the problem is. This video is only for the devs so whoever wants to fix it can just PM me or leave a message here. Most Destro already know this as it was on Live as well for the longest time but still I rather keep it hidden for those few who want to abuse it.

https://vimeo.com/148185449

**Comment by magter3001** [comment]
Made another video of the Order Saphery keep outer walls being able to be bypassed very similar to how it was on Live servers. 

https://vimeo.com/148195109

Same password for both videos. Just waiting for the right dev to PM me :)

**Comment by DanaBloodkiss** [comment]
Hello!Can you please PM me on forum? Forumname: Dana 
Thank you very much!

**Comment by magter3001** [comment]
Sent

**Comment by DanaBloodkiss** [comment]
Thank you, Passwatch should be already fixed on Live. T3 Elf will be fixed on next Hotfix. Please confirm if it's fixed after the next patch.

**Comment by magter3001** [comment]
Both have been fixed, thanks
