### ISSUE TITLE
Missing 3rd crafting backpack with items after .respec

### ISSUE THREAD

**Issue by cervaes** [WarEmu/WarBugs#2216]
First of all sry my english is not wery good! 
Last night i respeced my gathering skill (scavanging to salvaging) , and my third crafting backpack has dissappeared. It was full with gold dust, and curio.
Other problem is i cant level up salvaging after 26, and i have salvaged a tons of items.
Thanks for your help!

**Comment by Evildoor** [comment]
First issue - isn't it how it is supposed to be? Additional backpack slots are dependent on your crafting skill, and you nullified it by respeccing.

**Comment by cervaes** [comment]
So i can say goodbye to that items?

**Comment by Evildoor** [comment]
Seems so. Maybe they'll return when you level your new skill and get the 3rd backpack tab again, but i doubt it.
