### ISSUE TITLE
[Quest]: Celestial Defender

### ISSUE THREAD

**Issue by Heteryk** [WarEmu/WarBugs#2217]
So i noticed that this quest line has one revard every quest. I have to admit it looks awesome but i already have like 5 of them - this may be some bug.
![rahgal_066](https://cloud.githubusercontent.com/assets/16116091/11654273/9b8336a4-9da4-11e5-8598-15dc4d5a68da.jpg)
![rahgal_063](https://cloud.githubusercontent.com/assets/16116091/11654283/b203088c-9da4-11e5-973f-6db38d1fdf0b.jpg)
![rahgal_065](https://cloud.githubusercontent.com/assets/16116091/11654279/a01e75ca-9da4-11e5-966a-de9e6a0e5c90.jpg)

This may or may not be the first quest of the line -wasn't paying attention when i started.
![rahgal_058](https://cloud.githubusercontent.com/assets/16116091/11654310/e6a7938c-9da4-11e5-85a0-ae36079d2266.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
