### ISSUE TITLE
[Quest]: Hallenfurt's Appeal

### ISSUE THREAD

**Issue by Heteryk** [WarEmu/WarBugs#2218]
quest is marked on wrong place on map. Should mark warcamp but shows docks.
![rahgal_067](https://cloud.githubusercontent.com/assets/16116091/11655213/29877026-9dac-11e5-930b-5bdbb5725701.jpg)
![rahgal_068](https://cloud.githubusercontent.com/assets/16116091/11655216/2c0222e2-9dac-11e5-8a2f-9c594d289d6c.jpg)

**Comment by DanaBloodkiss** [comment]
Fixed in next Hotfix.
