### ISSUE TITLE
Interrupt

### ISSUE THREAD

**Issue by Alex40k** [WarEmu/WarBugs#2219]
Pls make checking of target vision more shot. If some range start cast and you hide with wall it does not help tons of fireballs, arrow, rifts and ather just fly through wall in you. It's terrible.

**Comment by Evildoor** [comment]
Actually, you are hit only by half (or less) of tons of arrows and fireballs - those which were close to finishing the cast when you started to hide behind the wall. Rifts are separate problem reported elsewhere.

**Comment by Tesq** [comment]
i see it happen sometimes must be some server lag, or the 25% distance check whe  someone exit from the range cast in some situation make this happen.
