### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by rapper256** [WarEmu/WarBugs#222]
Tanks can wear dual wielded and cannot use auras himself. Quests waypoints is wrong zone. I mean when I take quest, the quest point to wrong zone by the red border. Res skills doesn't work. Choppa berserk doesn't work. Skills cooldown can't seen and you use any skills, when skill is finished and you try use again skill action seen again but skill doesn't work for example when you use Flee and Flee was ending, Flee seen useable and when you try use again you action seems like use Flee but you can't use Flee and you can't gain movement speed. So much for that. If I remember and realize new or I forgetted to written bugs, I will post here.

Bright Wizard's Combustion doesn't work too. All stacked abilities doesn't work. And Archmages cannot heals his mates back of himself. When Archmage heal to back of himself to mate heal skill is stucked. And can't unlock crafting skills. I wanna talismans but crafting skills is not unlockable. So other people can't sell any talismans.

Sorry for bad grammar.

**Comment by rapper256** [comment]
Why am I should read the database before posting anything? When I read that post I don't know where I can reading the database and I can't striving for finding and reading and understanding database. If all of those bugs are known issue why didn't fixed when I post that issue? You need try to think efficiency instead of blaming anyone, lol. I just post that issues for help, if those issues are well known, fix them then.

**Comment by ozarmidrashim** [comment]
Mirkul29 commented on 11 Jul 2014 
> 11 Jul 2014 
> 2014

**Comment by rapper256** [comment]
rapper256 commented 2 hours ago
