### ISSUE TITLE
Work guards in SC

### ISSUE THREAD

**Issue by Alex40k** [WarEmu/WarBugs#2220]
In many sc guards not work at all. They stay on hill and look how enemy kill their side players. It's posible to increase agr area of them or put them down on ground from hill?

**Comment by Evildoor** [comment]
From what i've heard, "on hill" guards (Mourkain, Tor Anroc, etc) work exactly that way - they are here only to kill enemies who climb onto the respawn hill somehow (Pounce, for example), not to slaughter everyone who gets close like guards on other scs (Nordenwatch) without a hill to protect the spawn.

**Comment by Tesq** [comment]
in ton anroc they are too near the end fo the roof  and slaughter all ppl, this shouldn't happen and was alredy reported.

On mourkain temple they are fine and work as they should.
