### ISSUE TITLE
Qhaysh blocka

### ISSUE THREAD

**Issue by DanaBloodkiss** [WarEmu/WarBugs#2221]
Hey m8, can I request somewhat a favour :P being the black orc t3 inf reward if u have time to add it, It should be called "Qhaysh blocka" currently they have identical jewellery rewards

np m8, if its any use its exactly the same as all other tanks shield reward for t3 rvr inf. cheers m8

**Comment by Tesq** [comment]
http://www.arsenalofwar.com/items/Destruction/Qhaysh%20Blocka'

+ 27 Strength
+ 18 Toughness
+ 12 Initiative

Barricade V - On Being Hit: 5% chance to increase armor by 500 for 6 seconds.

**Comment by DanaBloodkiss** [comment]
Thanks Tesq

**Comment by wargrimnir** [comment]
Appears to be correct.
