### ISSUE TITLE
Dwarven Chapter 12 Rally point

### ISSUE THREAD

**Issue by Kouba85** [WarEmu/WarBugs#2223]
Hallo i have set my rally point to dwarven ch12 in black fire pass and when i use by book of binding it send me to zone 0 everything black.
![snorrri_013](https://cloud.githubusercontent.com/assets/15944509/11657430/f29468b0-9dbc-11e5-9ea1-e19ca477ccdc.jpg)

**Comment by Kouba85** [comment]
after 10 restarts and after new changelog still the same:(

**Comment by Tesq** [comment]
use /stuck 2 times in row , then save tome to another location

**Comment by Evildoor** [comment]
Closing per rules of the bugtracker.

**Comment by Torquemadra** [comment]
fixed next patch
