### ISSUE TITLE
Devastator Gorgerin remove hair

### ISSUE THREAD

**Issue by Novgoroth** [WarEmu/WarBugs#2225]
My devastator gorgerin makes my hair disappear ! :((

<a href="http://www.hostingpics.net/viewer.php?id=718911Navgaroth004.jpg"><img src="http://img11.hostingpics.net/thumbs/mini_718911Navgaroth004.jpg" alt="Heberger image" /></a>

**Comment by Novgoroth** [comment]
If i may, i think that the gorgerin is, like every other helmet, removing hair slot, but it's not supposed to do that for Dok, not supposed to remove hair slot

**Comment by Evildoor** [comment]
Closing per #4333
