### ISSUE TITLE
[Slayer][Empire Chapter 12][Influence Reward][Missing Stats]: Runed Leathers

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#2226]
Same as in the others

**Comment by Meralors** [comment]
I can't find any info about Runed Leather stats, if anyone oculd help ;)

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
