### ISSUE TITLE
[Slayer][High Elf Chapter 13][Influence Reward][Missing Stats]: 2 Items this time

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#2228]
Armbraces of Graceful Blows
Chargers of Graceful Blows 
are missing stats

**Comment by Styrkarr** [comment]
I can't find any info about Armbraces of Graceful Blows and Chargers of Graceful Blows stats. If anyone find it, don't hesitate to share it ! ;)

**Comment by NorKalli** [comment]
long since fixed
