### ISSUE TITLE
XP gain too high

### ISSUE THREAD

**Issue by Halhammer** [WarEmu/WarBugs#2230]
Just logged my lvl 30 engi, I'm gettin 6,300 XP on a regular 30 mob kill...

**Comment by taccr** [comment]
This is the value I get when I'm rested. Sounds ok to me.

**Comment by Calarian** [comment]
Your engi probably has rested XP they just implemented that.

**Comment by Halhammer** [comment]
Well, if that's intended - fair enough. Strangely, I'm not gettin any further XP now after i hit 31, stuck at 0 points. Logged out and back in several times. Influence workin fine.

**Comment by Evildoor** [comment]
Xp/renown gain is disabled at cap.

**Comment by Halhammer** [comment]
Eh yea... but at 31.99 not at 31.00, or am I missin somethin?

**Comment by Evildoor** [comment]
Before patch it was at 31.99. Now it is 31.00.

**Comment by Halhammer** [comment]
Aaah, cheers for enlightening me :D
