### ISSUE TITLE
No exp since patch 08/12/2015

### ISSUE THREAD

**Issue by Rammsteinn** [WarEmu/WarBugs#2231]
Character: Shandar

No exp gained from kills, sc win, bo capture, quests.

Inf and Renown working fine.

**Comment by Rammsteinn** [comment]
Surprisingly in sc some players get exp, some don't.

**Comment by Evildoor** [comment]
Something's wrong here indeed. Sometimes kills reward nothing (yes, i've considered known issues like pet DBs), and once i've got like 5k exp from a kill in 3 vs 2 fight (scenario, so no AAO).

**Comment by Lheana** [comment]
I just up lvl 31 and stopped gained xp ... Are you lvl 31 too ?

**Comment by Morksezstop** [comment]
<a href='http://postimage.org/' target='_blank'><img src='http://s22.postimg.org/4ocpsrfz5/image.jpg' border='0' alt="sc" /></a><br /><a target='_blank' href='http://postimage.org/app.php'>capture screen</a><br /><br />
here we got one odd sc where winning side got less renown than lossing side
About the exp it seems that capped at lvl 31 character dont get visual contribution of all the unusable exp like it was on live. That is not big deal but renown contribution is quite strange. 
As u see the premade that do 90% of all kills got lower renown income while the loosing side that got 4-5 kills got some ridicules amount of renown.

**Comment by Lheana** [comment]
I think when you are lvl 31, you simply stop having xp (as I can see in your screenshot).

**Comment by ozarmidrashim** [comment]
Forgot to announce this change. Players at the XP and Renown cap will no longer gain XP and Renown, to prevent preloading of the next level before we push the cap in future.

**Comment by Morksezstop** [comment]
my shaman is at rr40 and on the scoreboard i still got 1,6 rp. So the rule is working differently for exp and renown
