### ISSUE TITLE
Quest 'Balance' Order skipping steps

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#2234]
Yet another quest which skips some steps and completes after only talking to the same quest-giver NPC.

Order-Chrace NPC Gaelnielle Whitewing, Cliffs of Ushuru

**Comment by Meralors** [comment]
Quest requesting to use an item are not working for now, this is probably why this quest have been changed to be completed just by talking to npc.
Can't fix now.

**Comment by Razielhell** [comment]
Fixed.
