### ISSUE TITLE
WB management issue

### ISSUE THREAD

**Issue by Talissera** [WarEmu/WarBugs#2235]
I had an issue, when I had WB leader position in crowd WB and in our WB some people went off, tp to the scene (while in WB, yes), there is no ability to kick them from WB or drag and drop between WB groupes.

**Comment by Calarian** [comment]
This bug has been around forever, this happens quite often and is especially annoying when using Squared.

**Comment by Tesq** [comment]
the wb rooster also sign their position, even if they leave wb they are still signed inside

**Comment by Luth-RoR** [comment]
Should be fixed.
