### ISSUE TITLE
[quest] cannot finish 'Echoes from the past'

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#2236]
this quest I cannot complete as the Ark of Saruthil which, to my understanding is the quest objective and clicking it does nothing...

The Shadowlands - Order quest at the Mirelen PQ

**Comment by Meralors** [comment]
Killing the Uthorin Loreseeker should award you with Weathered Parchement. If anyone can check that if its working on live ( I dont have order toon :p )

**Comment by gittoaster** [comment]
I found it now, there is a Banner right beside the quest giver.  The Weathered Parchement is not needed and the map location is incorrect.  Good enough I guess.
