### ISSUE TITLE
[Blackguard]Shielding Anger  disrupt rate doesnt show in character window

### ISSUE THREAD

**Issue by Kozic** [WarEmu/WarBugs#2240]
First time posting here so forgive me for any mistakes.
I notice Shielding Anger blackguard's tactic, disrupt rate doesnt show in character window.I think the tactic work because i can see i have many disrupts but it just doesnt show in character window.

**Comment by ropuch** [comment]
Use .getstats - it shows correct values for Shielding Anger / Anger Drives me

**Comment by Evildoor** [comment]
Was fixed at some point.
