### ISSUE TITLE
[Tome Unlock] Chapter 11 Dwarf can't be unlocked by me.

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#2243]
I went there directly after the T3 release.
I unlocked the Area around CH 14 of the High Elves but not CH 14 directly as for the INF Rewards.
Yesterday I run and jumped around the flight master and talked to everyone in the Camp but to no sollution.

The same for Dwarf CH 11.

**Comment by Evildoor** [comment]
High Elves: #1939.

**Comment by Evildoor** [comment]
#2298 has more info about dwarfs. Closing.
