### ISSUE TITLE
Quest - Birds of a feather - Blighted Isle

### ISSUE THREAD

**Issue by Lannicus** [WarEmu/WarBugs#2244]
Hello,

The quest birds of a feather, given by karaa ravenseer, isnt working correctly.

The quest item doesnt get deposited into ones inventory, thus rendering the player unable to do it in its intended increments, it is simply completed by clicking on her once again. Of the trophy rewards you have the option of selecting, i believe only the first 4 are available to picked.

Regards,
               Lannicus.

**Comment by Evildoor** [comment]
Trophy quests' rewards are already reported. Quests where you have to do something with items cannot be fixed yet.

**Comment by Yellowpillow** [comment]
That was great quest, item teleported you into places you can't reach normally, from there you could see fight of two dragons and just beautiful scenery.
