### ISSUE TITLE
Squg Armour Action Bar does not switch.

### ISSUE THREAD

**Issue by Gobtar** [WarEmu/WarBugs#2248]
When switching to the Squig Armour Stance, Action Bar 1 should switch similarly to the marauder and shadow warrior stance switch mechanic but it does not do this on the Squig Herder.

**Comment by Evildoor** [comment]
Still not fixed.

**Comment by ozarmidrashim** [comment]
I don't know when this report was reopened, but I've personally verified it works on live.
