### ISSUE TITLE
Devastator Helm Appearance

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#2249]
it shows the item but im missing my hair there =P

**Comment by Evildoor** [comment]
I guess this means Devastator Helm for Warrior Priest... I know that it's the only one which exactly matches the name in the title, but "Helm" can also be understood as "item which goes into Helm slot", so it can be confusing...

**Comment by Laurell-Silentshade** [comment]
This is also happening with devastator dok helm.

**Comment by Evildoor** [comment]
DoK helm was already reported.

**Comment by Torquemadra** [comment]
Fixed next patch
