### ISSUE TITLE
Burn Away Lies finisher crit

### ISSUE THREAD

**Issue by Talissera** [WarEmu/WarBugs#2250]
This evening we have tested BAL crits, no crits for finish tick.
Are we unlucky, or smth goes wrong?

**Comment by Qrazy** [comment]
Unless you have 100% chance to crit, its not guaranteed to crit. Even with 100% crit chance you would have to factor in your targets initiative. So I would say unlucky.

**Comment by Talissera** [comment]
I understand your idea, but after 20 mins of constant BALing, we have a lot of crits on ticks, but no crit for finisher. Some other WHs confirm that smth goes wrong. If needed, I can make screenshots tomorrow.

**Comment by Evildoor** [comment]
http://www.pixic.ru/i/M090b9W3o1G3U8P2.jpg
From forum topic.
Well, if you really did it for 20 minutes and 0 crits, something can be wrong indeed... Maybe patch broke something...

**Comment by Talissera** [comment]
I know, that there was a fix with grave STR bonus on BAL (0.66x), ans since that there is hard time for WH. Our natural enemies like sorcs have their crits around 2k+ on empty target..

Now friend confirmed that saw crit with last tick on random squig herder. But really it is rare. Waiting for confirm, thanks.

**Comment by ozarmidrashim** [comment]
BAL's last tick can critically hit.

**Comment by Talissera** [comment]
>>BAL's last tick can critically hit.
If you say that's all right, then thanks for your work, we will test it further.

**Comment by Evildoor** [comment]
Since we have several proofs that BAL crits and Azarael's confirmation, i'm closing this.
