### ISSUE TITLE
NPC mobs who Parry/Disrupt your opening attack aren't aggroed.

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#2252]
If you attack an idle mob and it parries/disrupts your first attack (I haven't tested dodge) it won't start attacking you. It only attacks once you have successfully managed to hit it.

I'm 87.4% sure that on AoR mobs aggroed on the first attempted attack and not the first successful one.

**Comment by magter3001** [comment]
I can confirm that this effects dodge as well. Been leveling my BO and those dodges always got me out of combat when I had M2 up :/

**Comment by Tesq** [comment]
confirm

**Comment by Evildoor** [comment]
It seems that mobs only get aggroed on taking damage/being taunted. For example, you can target a mob and spam Law of Conductivity - each usage will restart the duration, thus preventing the first tick of damage, and mob will never attack you. Or you can apply Touch of Rot/Burn Armor/Vehement Blades and the mob will not aggro either (if you prevent yourself from autoattacking somehow and mob is not in a fight with someone else).
