### ISSUE TITLE
Interface reinitialised each connection

### ISSUE THREAD

**Issue by Kiriziel** [WarEmu/WarBugs#2253]
Hello,

Each time I have to disconnect and reconnect, my icons bars are reset and all of my bindings are not recorded so I have to bind again my icons on the skills bars ... Pretty annoying :(

I have no add-ons installed and this bug is for all my characters.

Thanks you by advance

**Comment by noisestorm** [comment]
Properly log off once you have saved your settings (and i mean log out and exit the client and not taskkill r alt+f4 it!). If they do not save correctly, then you most likely have some write protection in your folder.

**Comment by Kiriziel** [comment]
Ok thanks for your help, i'll try it :)
