### ISSUE TITLE
M2 Focused Mind not responsive a lot of times

### ISSUE THREAD

**Issue by savagehippie** [WarEmu/WarBugs#2255]
When I pop the M2 Focused Mind on my sorc, I then use either of the 3 sec cast abilities depending on spec, and they still take 3 secs to cast and most of the time just freeze after animation without ever fully casting. I never had a problem with this before T3. Note: I always used it to spam the shit out of either doom bolt or shattered shadows, worked before, doesn't work now.

**Comment by Evildoor** [comment]
#2204
