### ISSUE TITLE
[Cultivation]Staghorn Fusk Spore

### ISSUE THREAD

**Issue by geezereur** [WarEmu/WarBugs#2257]
I have been trying to upgrade Staghorn Fusk Spore   lvl 175   to  lvl 200 version  it cant be done I have been trying for 3 days now with everything, its the Spore that increases the number of potions.
How do you delete this?  Just after I wrote this I made a lvl 200 one ^^  well took me 3 days.

**Comment by Evildoor** [comment]
You can close your own tickets.
