### ISSUE TITLE
stats defense contribuition[emulator]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#2258]
it seems that stats as wepskill / willpower / initiative don't add % to defense atm.

/getstats and character rooster show only the % from renow skill or charcater skill

(every  4 points should = 0.1% in the correspective defense)

N.B. it could be a visual bug for char roost/get stats cos it also happen the same for block rating, it dont get show but for what we know block rating always worked. It need to be check directly by you.

**Comment by Evildoor** [comment]
I think this is not implemented yet rather than overlooked bug.

**Comment by sullemunk** [comment]
iirc it din't show on live either so it was more of a hidden stat

**Comment by Tesq** [comment]
no on live it was showed

**Comment by Evildoor** [comment]
@Tesq is right.

**Comment by ozarmidrashim** [comment]
Adding Trivial because as most players know, the formula used for the character stat screen is not valid in the majority of situations. Because the attacking stat tends to dwarf the defending stat, you will rarely if ever get anywhere close to the full value of defense from the defending stat as calculated by the formula on HammerWiki.

**Comment by Tesq** [comment]
i dont get what you mean aza? the % from stats like wep skill usually give  a 5% to your defense and that is not reduced by anything if not strengh, well yes in some case some classes can have their def totaly bypassed but you don't invest in that stat if you dont want surpass that chance, classes like melee or tank that invest in this benefith enormusly.
Atm every melee classes dont get the paryr from wep skill and that is like a good 10-20%
It also matter vs tank as tank go low sterngth, this help healer and dps to parry their cc, this is why kobs/chosen stag are parryable.

**Comment by sullemunk** [comment]
at lvl 31 and statcap (825) the weapskill adds 39.5% to parry vs someone who has 0 in Strength at equal level
(same for willpower(disrupt) vs intelligence, and Initiative(dodge) vs Ballisticskill)

**Comment by ozarmidrashim** [comment]
Let's illustrate the principle. Assume 600 Str opposes 250 WS. The formula for the emulator is:

DefStat / OffStat * 0.075 * 100

250 / 600 * 0.075 * 100 = 3.125% parry.

The formula for the stats screen is:

 Weapon skill / [(Level * 7.5 + 50) * 13.5]
250 / ((31 * 7.5 + 50) * 13.5)

So what I'm saying is, 90% of the time, the stats screen is going to be wrong. I don't really want to resend all of the stats every time WS, Initiative or Willpower changes just so it can be wrong in a different way.

**Comment by Tesq** [comment]
Weapon skill / [(Level * 7.5 + 50) * 13.5]
250 / ((31 * 7.5 + 50) * 13.5)

what is this? i dont understand, is this refering to the penetration or the controbution to parry?

wep skill  / intelligence / willpower contribution should be

4 poins =0.1%

I have correct add-on that show this ratio client side for every itiem i have 


![tesq_291](https://cloud.githubusercontent.com/assets/7527415/11717232/6281519a-9f4f-11e5-872d-eb10dfd8aa2a.jpg)


12 wep skilla re = 0.03% how is possible you get wrong stats?

**Comment by sullemunk** [comment]
depends on level

**Comment by Tesq** [comment]
mm not sure, only armor penetration and block rating should change change via level, regards def and wep skills.

**Comment by sullemunk** [comment]
armor pen% from weaponskill formula is: (weapskill/(level*7.5+50)*0.25)*100

**Comment by sullemunk** [comment]
there is no basestat contribution for block

**Comment by Tesq** [comment]
block rating is the base stat for block in that sense

**Comment by sullemunk** [comment]
touche, BlockRating/(GameData.Player.level*7.5+50)*20 = block %

**Comment by Tesq** [comment]
anyway i fell like is important to have this fix it/make em relevant somehow do yoru best :)

**Comment by sullemunk** [comment]
I included those defensive stats % in the updated statdoll i'm working on

**Comment by ropuch** [comment]
So, to sum up the block part: does shield block rating mean anything right now? While wielding a 290 BR shiled I have 0% block rate in char window/getstats/statdoll/whatever.

**Comment by Evildoor** [comment]
This was implemented at some point.
