### ISSUE TITLE
Alternate appearance not being used on character select screen

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2262]
When viewing your characters at the character select screen the dyes are used but the alternate appearance for items are not. Example images attached.

Login screen:
![select](https://cloud.githubusercontent.com/assets/15970235/11725845/ac52363a-9f73-11e5-8458-e9f005938cd4.jpg)

Actual:
![actual](https://cloud.githubusercontent.com/assets/15970235/11725853/b3feb48a-9f73-11e5-91ee-e1e2a1cd29bb.jpg)

**Comment by Evildoor** [comment]
Should be fixed.
