### ISSUE TITLE
Gas Squig summon does not grant armor

### ISSUE THREAD

**Issue by Lambadi** [WarEmu/WarBugs#2263]
The 'Gas Squig' ability says it will grant/double my armor when summoned. This does not happen at all. However the 'Summon Squig' (the standard squig) increases the armor value. At least that is what the character screen states.

**Comment by ozarmidrashim** [comment]
False report.

![lesquig_000](https://cloud.githubusercontent.com/assets/6764164/11845651/c9c43e8c-a40c-11e5-8337-b669f201aa43.jpg)
