### ISSUE TITLE
[Quest] Like Clockwork

### ISSUE THREAD

**Issue by Meralors** [WarEmu/WarBugs#2267]
Target NPC "Ieoeariieouu" (spelling sucks!) is not in game for now.

**Comment by zibiman** [comment]
![zibiman_000](https://cloud.githubusercontent.com/assets/16434526/12471469/85ddcb1e-c006-11e5-885d-547b2cf729fd.jpg)

**Comment by DanaBloodkiss** [comment]
Quests in the capital cities got deactivated except Live Event quests.
