### ISSUE TITLE
Thickmuck direhelm, T3 influence marauder helm missing stat

### ISSUE THREAD

**Issue by Styrkarr** [WarEmu/WarBugs#2268]
The marauder helm Thickmuck direhelm (influ T3 chaos) is missing stat 2% crit melee.

http://www.arsenalofwar.com/armor/Destruction/Thickmuck%20Direhelm

**Comment by Styrkarr** [comment]
Fixed in the next patch.

**Comment by mursie** [comment]
please fix all classes helms then.  All classes are missing the 2% crit.  If you place this on marauder - please ensure all classes have this on their helm.

**Comment by Styrkarr** [comment]
Don't worry i saw that. It'll be done.
