### ISSUE TITLE
Relogging during scenario displays RR of the initial character

### ISSUE THREAD

**Issue by Tidybraveguinea** [WarEmu/WarBugs#2269]
If you log out a character while being on scene and then log in as another character while the scene still going (even of opposite faction), by the end of the scene that character will gain the same renown rank as the one that you loged out. Works both ways: renown rank can be lowered or increased.

**Comment by Evildoor** [comment]
Is this real or visual issue? I mean, these 40 renown ranks don't go away after restarting the game, you can spend them to buy renown mastery, etc? Or not? I'm asking because i've seen similar issues, for example, same thing with gold and different condition, but that gold was not real.

**Comment by Renork** [comment]
I'll test this now, logging 21 rr 20 sorc and then my 15 rr17 magus to see.

**Comment by Renork** [comment]
Visual bug. It did say I was rr20 but after relogging it went back to rr17.

**Comment by Evildoor** [comment]
Aha, thanks.

**Comment by noisestorm** [comment]
Visual Glitch also happened for SC tokens on my char/twink. T3 tokens were shown in the backpack of a lvl 12 char. Tried also speccing RR and spending Tokens, neither worked. Strangely the Tokens were on the same inventory slot (#4 in currency bag), allthough the first 3 were empty. Maybe there _could_ happen some glitch if the inventory isnt empty on that spot thou

**Comment by sioding** [comment]
Checked that on my own right now - didn´t happen anymore. Close
