### ISSUE TITLE
[Quest]: An Old Flame

### ISSUE THREAD

**Issue by Heteryk** [WarEmu/WarBugs#2270]
When you go where the map shows you find Berynn, but then i'm not sure what should happen - when random mob kill this guy no Flametorn spawns. Talking with him doesn't do anything.

![rahgal_069](https://cloud.githubusercontent.com/assets/16116091/11748412/73c7a178-a028-11e5-902c-5966bd3d21c2.jpg)

**Comment by Ryanfawkez** [comment]
Quest cannot be fixed as long as NPC kill/spawn scripts upon accepting the quest are unsupported.

**Comment by Shadowsmove** [comment]
this quest now shows this when you interact with the npc 
![skafgrim_034](https://cloud.githubusercontent.com/assets/13737673/12257804/81fd0e8c-b8d7-11e5-828b-b2820d1b66bd.jpg)

**Comment by DanaBloodkiss** [comment]
Fixed in next. Related to https://github.com/WarEmu/WarBugs/issues/3887
