### ISSUE TITLE
[Quest]: Everyone Pays

### ISSUE THREAD

**Issue by Heteryk** [WarEmu/WarBugs#2273]
Quest is not showed on map and that may be just me but I can't find Noble Osgar - he should be somewhere in Lord's Row. I'll make sure later that "not on map" isn't my fault because of to man quests tracked.

No pic this time :<

**Comment by Ryanfawkez** [comment]
NPC is right across the renown/carreer trainer palace in Altdorf;
![noble1](https://cloud.githubusercontent.com/assets/8767404/11752095/d87d98f6-a03d-11e5-9625-c6c74f761ca7.jpg)

Will add quest markers as needed.

**Comment by DanaBloodkiss** [comment]
Added 1 questmarker. Currently we can only set 1 questmarkers.
