### ISSUE TITLE
[Quests in general?]

### ISSUE THREAD

**Issue by Heteryk** [WarEmu/WarBugs#2274]
Quests in T3 - dwarf and empire (elf probably too but im still doing other quests) are not updated on map uppon progresing, but here im not sure if they shoud show you where should you go turn in the quest. Should they? If they should, is this enough or should we report every single quest here? 

This issue is present probably for most if not all quests not only in T3.

**Comment by Evildoor** [comment]
If you mean that when you fulfill the requirements the area on map does not updates - do not report it, we cannot fix it yet.

**Comment by Heteryk** [comment]
Yes, that's what I had on my mind. Ty for clarification.
