### ISSUE TITLE
Missing stats on several T3 influence helm

### ISSUE THREAD

**Issue by Styrkarr** [WarEmu/WarBugs#2275]
Thickmuck Waaaghat - missing 2% heal crit - http://www.arsenalofwar.com/armor/Destruction/Thickmuck%20Waaaghat

Thickmuck Gorget - missing 2% melee crit - http://www.arsenalofwar.com/armor/Destruction/Thickmuck%20Gorget

Thickmuck Skully - missing 2% melee crit - http://www.arsenalofwar.com/armor/Destruction/Thickmuck%20Skully

Thickmuck Steelhelm - missing 2% melee crit - http://www.arsenalofwar.com/armor/Order/Thickmuck%20Steelhelm

Thickmuck Hat - missing 2% melee crit - http://www.arsenalofwar.com/armor/Order/Thickmuck%20Hat

Thickmuck Hexveil - missing 2% melee crit - http://www.arsenalofwar.com/armor/Destruction/Thickmuck%20Hexveil

Thickmuck Hardhat - missing 2% ranged crit - http://www.arsenalofwar.com/armor/Order/Thickmuck%20Hardhat

Thickmuck Taen - missing 2% melee crit - http://www.arsenalofwar.com/armor/Order/Thickmuck%20Taen

Thickmuck Skullcase - missing 2% melee crit - http://www.arsenalofwar.com/armor/Destruction/Thickmuck%20Skullcase

Thickmuck Casque - missing 2% melee crit - http://www.arsenalofwar.com/armor/Order/Thickmuck%20Casque

Thickmuck Dreadhelm - missing 2% melee crit - http://www.arsenalofwar.com/armor/Destruction/Thickmuck%20Dreadhelm

**Comment by Styrkarr** [comment]
Fixed in the next patch.

**Comment by mursie** [comment]
this was only fixed for a few helms.. sigh.

squignoggin should have 2% ranged crit on thickmuck version.

**Comment by Styrkarr** [comment]
Please, open a new bugtrack if you think there is a missing stat on an item.
