### ISSUE TITLE
murderous intent

### ISSUE THREAD

**Issue by vithoria** [WarEmu/WarBugs#2276]
tactik on dok, that is suppost to give 10% crit and 10% parry when i slot it all my crit in charackter window disapear

**Comment by Tesq** [comment]
uhm last time i check murderous intent crit got signed correctly on /getstat in general critical hit or something like that. Anyway just to tell about it it shoudl both give 10% crit chance and 10 heal crit chance

**Comment by ozarmidrashim** [comment]
Wrong command order. Fixed.
