### ISSUE TITLE
Can't see or use granted abilities.

### ISSUE THREAD

**Issue by Sighan** [WarEmu/WarBugs#2279]
The Zealot Buffs ("Mark of Deamonic Fury", "Mark of the Vortex", "Mark of the Spelldestroyer") should grant abilities as per Tooltip. Those abilities do not show up in my "Granted Abilitys" Bar. Using the Hotkeys for "Granted Abilities" does activate them either, leading me to believe that the abilities never get applied to the character.

**Comment by Morksezstop** [comment]
they are not implemented on purpose becouse their usefullness is close to 0 while to work they need much coding

**Comment by Evildoor** [comment]
@Morksezstop is correct.
