### ISSUE TITLE
Blackguard Devastator Hauberk Wrong Appearance

### ISSUE THREAD

**Issue by Hauclir** [WarEmu/WarBugs#2280]
![hauclir_131](https://cloud.githubusercontent.com/assets/7598530/11760851/1680b336-a061-11e5-9b34-cdf31c1b0329.jpg)
This is how the current Devastator Hauberk looks which is wrong the picture below has the correct appearance and the correct color for the set.

![blackguard devastator armor set](https://cloud.githubusercontent.com/assets/7598530/11760857/5c3e7476-a061-11e5-984b-6a4f50829799.jpg)
http://www.arsenalofwar.com/armor/Destruction/Devastator%20Dusk%20Warrior's%20Kit

**Comment by Ryanfawkez** [comment]
Model has been altered to match that on the image provided. Won't change the colour as other Devastator pieces are also uncoloured by default in the wartool.
Fixed in next patch.
