### ISSUE TITLE
Character stats window: heal crit sent to client missing base crit chance

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2283]
The tootip for healing crit chance is missing whatever the base chance to critical heal is. I don't actually know this figure is, I just know it exists as you can crit heal with no crit heal gear.

Reproduction: Naked Zealot with Blessing of Chaos tactic equipped (no other tactics). Keep spamming Flash of Chaos and it will eventually crit and proc the tactic. No points in RR, no points in mastery.

Note: I don't know whether there is a base chance to critically heal or a base chance to be critically healed.

**Comment by Evildoor** [comment]
It was this way on live. There is some base chance for crit heal, but it was not shown anywhere.

**Comment by Morksezstop** [comment]
base heal crit is 10% and was never shown on live neither but it use to stack with other crit you got from gear, skills, tactics, morals, renown. So if u got 40 on paper sheet u really got 50ish

**Comment by RoR-Zomega** [comment]
Thank you :)

Is it possible for AoR to send this through along with the gear/tactic/etc bonus?
