### ISSUE TITLE
Flashfire

### ISSUE THREAD

**Issue by bloodi** [WarEmu/WarBugs#2284]
So i am not 100% certain of this because its kinda complicated to test, mostly because enemies do not tend to stand there and let themselves be casted upon but Flashfire + Fiery Blast seems to ignore the Flashfire ICD.

Most likely the disrupt from the enemies affected by the aoe is what is causing the issue, i got a few back to back procs yesterday and unless is some weird lag issue there is no way the proyectile took 3 secs to travel and granted me anothere proc respecting the ICD.

So if anyone can confirm or help me test it, it would be appreciated.

**Comment by ozarmidrashim** [comment]
Missing retrigger interval.

**Comment by gittoaster** [comment]
I can confirm that the Flashfire+Fiery Blast combo seems to be performing.. too well.
I'm exactly certain but I think the CD is part of the issue - without precisely testing, I don't think the proc interval is working as intended.
