### ISSUE TITLE
[Squig Herder] [Pet]

### ISSUE THREAD

**Issue by papsbug** [WarEmu/WarBugs#2286]
Pet can attack wile player is on mount. Not sure who it was on live but some WL players say there pet could not attack till dismount, dont have any SH to ask but need to be same...

**Comment by Tesq** [comment]
so 90% time wl run away and left the pet to snare me was a bug? maybe after they used the attack they could re-mount..

**Comment by papsbug** [comment]
Maybe that is different, dono. Just saying if SH/WL is on mount then he can kite wile pet attack, that is not how it should be. Or maybe i am wrong? Any way any skill usage need to dismount u. For me it is not good :D 

Need more confirmation, i jut talk to some random dude who sad he played WL on live.

**Comment by Evildoor** [comment]
#604
