### ISSUE TITLE
Weapon Skill on Zealot devastator gear (technically not a bug)

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2287]
Inspired by #1363.

The Devastator Footwraps for the Zealot have Weapon Skill as one of the bonus stats. Can this be changed into something more useful such as Wounds (Wounds doesn't appear on that item)? It's not a bug as the original item was like that as well (http://www.arsenalofwar.com/armor/Destruction/Devastator%20Footwraps), but more than likely would've been changed by Mythic if they had ever gotten around to reviewing the gear again.

Obviously this is about as low-priority and as trivial as issues go :)

**Comment by ozarmidrashim** [comment]
With respect, you know it's not a bug, so it doesn't belong here under any circumstance.

**Comment by RoR-Zomega** [comment]
Yes, but as per the linked issue that is still open: 

"I do believe this is one of the cases when logic should be favoured over original stats in original game. Initiative is a fine defensive stat but WS and WIL are almost worthless to magus, so they should be replaced." - Evildoor

and

"Well, i'm not asking to fix all items in the game. The priority rather depends on the item's importance, so while PVE influence is not much of a deal, crucial PVP items (from PVP vendors, for example) are completely different story. However, even not important items deserve to be reported." - Evildoor

Considering this is on what is currently end-game gear for the Zealot it seemed worthy of an issue (esp if T2 Magus item stats are).

**Comment by Evildoor** [comment]
We are working on this, but i can't tell you how long will it take, since there is a lot of work to do. Also, you can save your time and do not report such problems, we'll go through all PVP items anyway.
