### ISSUE TITLE
My character renown up bugged

### ISSUE THREAD

**Issue by Nocha** [WarEmu/WarBugs#2288]
hi support.
i am choppa with nickname Atec
I have 31 lwl rang and 40,33% renown rang. Today i dont have any renown: from lock, from scenarios, from kill of order player. Absolutly anything. I  have only 33% of 41 renown, and i must have renown till 99%, but my renown bugged. I can give aproove screens. and interesting question: how you can compensate lost renown. its really?

**Comment by Morksezstop** [comment]
not bug, devs change it so ppl cant progress more than lvl 31 and rr40. Chars with rr and lvl more than respected lvls stop at their current progression till the lvl cap is moved upwards (at your situation you stuck at rr 33% of rr 40 till the cap rise)

**Comment by Nocha** [comment]
thank you for fast answer
