### ISSUE TITLE
Scenario table still lists RR gained even when RR capped

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2289]
The scenario results table lists the XP and RR earned for each player in that scenario. When someone has reached their max rank the XP gained is correctly listed as zero. However, when someone is at their maximum possible RR the scenario doesn't set the amount of RR gained to zero and instead shows - what I assume is anyway - what they would've earned if they weren't renown capped.

Not sure if this is by design or not, but to be consistent with XP the renown column should probably be zero when you are renown capped.

**Comment by Luth-RoR** [comment]
Only the player xp/renown was/is capped, but xp/renown gain is still counted for guilds etc.
