### ISSUE TITLE
Bugged item (from vendors)

### ISSUE THREAD

**Issue by anyadhatan** [WarEmu/WarBugs#229]
I found bugged item which is from vendor,to see this item select "Show All" option. To see large picture,click on image.

1 location:
![runepriest_036](https://cloud.githubusercontent.com/assets/8081009/3564179/b0f46d2a-0a73-11e4-8330-78a195a97191.jpg)
![runepriest_037](https://cloud.githubusercontent.com/assets/8081009/3564178/b0f3ed0a-0a73-11e4-9114-218de94624c8.jpg)
![runepriest_038](https://cloud.githubusercontent.com/assets/8081009/3564180/b1098c50-0a73-11e4-9613-69d75184a3ac.jpg)

2 location:

![runepriest_039](https://cloud.githubusercontent.com/assets/8081009/3564182/f4747f5e-0a73-11e4-840f-d89b560e7acc.jpg)
![runepriest_040](https://cloud.githubusercontent.com/assets/8081009/3564183/f476dc72-0a73-11e4-8515-ca297605d38e.jpg)

**Comment by DanaBloodkiss** [comment]
Fixed.
