### ISSUE TITLE
knocking down trouble

### ISSUE THREAD

**Issue by Asdar2** [WarEmu/WarBugs#2290]
I do not think that it's okay, I'm a witch hunter is not the first time I played at Karak Norn 100rr when you use a skill Pistole Whip your enemy should not move (but here the players use the bug. And when you're opining behind them, they start spinning and not letting you use skills from the back) ...... to witch Hunter is critical. Sorry for bad english

**Comment by Asdar2** [comment]
I would also like to know when you're hiding behind the object as enemies know that you are there it is a bug or an addon that shows on the map? This destroys the idea of playing for gank class

**Comment by Ryanfawkez** [comment]
It's been reported and has a fix pending on #2053.

**Comment by Evildoor** [comment]
@Ryanfawkez is correct.
