### ISSUE TITLE
Tactic Riposte and Slayer Choppa

### ISSUE THREAD

**Issue by geezereur** [WarEmu/WarBugs#2291]
Riposte right now dont scale with rage for more damage as it did on Live servers.

**Comment by ozarmidrashim** [comment]
I am going to deliberately revert this by changing Riposte to proc damage. Proof will need to be supplied.

**Comment by Luth-RoR** [comment]
There was some evidence for it provided in https://github.com/WarEmu/WarBugs/issues/8297, but it was deleted and closed by the creator for unknown reasons (as every other report opened by him).
Additionally Hurtin' Time/Reckless Gamble https://github.com/WarEmu/WarBugs/issues/8077 damage and self damage was also increased by the class mechanic (evidence also closed/deleted by the owner).

**Comment by Luth-RoR** [comment]
From https://github.com/WarEmu/WarBugs/issues/9780
>As found in following video: https://www.youtube.com/watch?v=9hdEvb3PTA4&t=77s
taken from ~1:30-2:30
Slayer riposte dmg scales based on mechanic:
Green dmg = 310+(299 mitgated) = 609 total.
Yellow dmg = 393+(347 mitgated) = 740 total, 387+351 = 738 total
Red dmg = 360+(446 mitigated) = 805 total
Tested on RoR, no change in riposte dmg on mechanic change, consistent damage.

**Comment by grunbag** [comment]
thanks to @Luth-RoR  for the video. Fixed for next patch

**Comment by sioding** [comment]
fixed with patch from 20.04.2019

**Comment by sioding** [comment]
Fixed with patch from 27.04.2019
