### ISSUE TITLE
Apothcary lvl 200

### ISSUE THREAD

**Issue by geezereur** [WarEmu/WarBugs#2292]
I don't seem to be able when I use a lvl 125 main ingredient to use also a multiplier and a extender at the same time.
It needs 2 stabolizers to sucseed.
Wich would mean that I have to make 1 pot at a time...

Am I using a wrong combination ? Anybody who has the combination to extenders and multipliers for lvl 30 pots ?

**Comment by Squea** [comment]
With a level 75 main ingredient you can use a level 1 vial and a 200 resin.  A 100 main ingredient requires a level 150 vial and a 200 resin.  Level 30 potions are 125 main ingredient which requires two goldweed, so you might as well use a level 1 vial.  You will only get two potions, but thems the breaks; you can still make 5 heal/ap pots at a time.
