### ISSUE TITLE
High Pass: icons on minimap (player, vendor, etc) not displaying in the correct locations.

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2296]
Bit of an odd one this. The icons on the minimap when in High Pass are all too low (or too far south) compared to where the object represented by the icon actually is. Talabecland doesn't have this issue, just High Pass. Images attached to show the difference between actual location and minimap location.

Keep door: too far away on the minimap.
![high pass keep](https://cloud.githubusercontent.com/assets/15970235/11768391/99d973fe-a1c3-11e5-8129-c2f6116dee0f.jpg)

Keep walls: in/on them according to the minimap but not in the game world.
![high pass walls](https://cloud.githubusercontent.com/assets/15970235/11768394/b277bde4-a1c3-11e5-82be-915707de19a5.jpg)

Keep Foreman: outside the keep walls according to the minimap but he's on/in them in the game world.
![high pass foreman](https://cloud.githubusercontent.com/assets/15970235/11768397/d3ba14ac-a1c3-11e5-9958-f8a88e2d3175.jpg)

**Comment by Ryanfawkez** [comment]
As you can see by the keep's outer wall placement on the map, the entire minimap tracking in High Pass seems to be out of sync. The icons are calculated exactly where you are standing, yet the rest of the minimap is still a few units off.

**Comment by RoR-Zomega** [comment]
Yeah all of the icons on the map still seem to be 100% accurate in relation to the player. I didn't find any instances where LOS, NPC interactions, etc were affected by this. Just seems to be a minimap display error.

I had plans for further testing today but the game has been down for a while so I'm posting what I have.

**Comment by Luth-RoR** [comment]
The high pass map was alos a bit bugged on the mythic server (it partially changed when entering some areas of the map).
