### ISSUE TITLE
Shields (bubbles) bug

### ISSUE THREAD

**Issue by Morksezstop** [WarEmu/WarBugs#2297]
Since t3 introduction when someone got abosrb shield (from healers for example) and recieve dmg while the shiled is on him and still active he got 1 dmg tick for each hit he got instead absorbing the whole dmg
Not sure if this is made that way intendently or just bug
here is some screenshot of the event
<a href='http://postimage.org/' target='_blank'><img src='http://s10.postimg.org/lshj6q0sp/bubble_bug.jpg' border='0' alt="bubble bug" /></a><br /><a target='_blank' href='http://postimage.org/'>upload photos</a><br /><br />

**Comment by Evildoor** [comment]
IIRC, shields always worked this way in ROR, even before T3. True, on live whole amount was absorbed (however, absorbed lifetap heals healed for 1).
