### ISSUE TITLE
Unlock: Dwarf Chapter 11

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#2298]
I was unable to find the unlock spot for Dwarf chapter 11 in Badlands. It was no where around where it should be. Later I was running around the RVR lake and the unlock popped, I was at approx 44831 by 51298. I was able to confirm this location on a second character. It is just outside Muggaz's ChoppaZ War Camp right along side a rock wall, very close to a high level guard npc, thought I was going to be hit and killed any second finding it second time.

**Comment by LestiArdisson** [comment]
Thanks for the info Shadwosmove.

**Comment by Torquemadra** [comment]
Fixed next patch
