### ISSUE TITLE
NPC mobs, looking dead but still actively attacking

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#2299]
I have found several of these NPCs, here are some of the locations.
Bloody Sun Toof Raida, Badlands approx 21074 by 7574
Uthorin Seeker, The Shadowlands, Mirelen Approx 53228 by 7369 two of them. 
                                                                      Approx 51282 by 8700
                                                                      Approx 53432 by 6857
Ulthorin Deathrain, The Shadowlands Approx 58245 by 61231

**Comment by Evildoor** [comment]
#881
