### ISSUE TITLE
Bugged items,some of them makes client crash

### ISSUE THREAD

**Issue by anyadhatan** [WarEmu/WarBugs#230]
At Aldorf,(a vendor) to see all item select "All Show" optionts,you cant buy these items,but when you LINK these items in chat few white items makes client crash. (5th and 6th picture items)

![runepriest_042](https://cloud.githubusercontent.com/assets/8081009/3564203/ed742310-0a75-11e4-909c-99ee3e314489.jpg)
![runepriest_036](https://cloud.githubusercontent.com/assets/8081009/3564204/ed762a48-0a75-11e4-9191-3001ae2afdb5.jpg)
![runepriest_037](https://cloud.githubusercontent.com/assets/8081009/3564205/ed762e9e-0a75-11e4-8a30-a66a4df93a98.jpg)
![runepriest_038](https://cloud.githubusercontent.com/assets/8081009/3564206/ed77c5ba-0a75-11e4-9040-7bfe74a2358c.jpg)
![runepriest_039](https://cloud.githubusercontent.com/assets/8081009/3564207/ed7a4d26-0a75-11e4-88f0-3547b6cb6703.jpg)
![runepriest_040](https://cloud.githubusercontent.com/assets/8081009/3564208/ed7b2c1e-0a75-11e4-9935-140dc63d0183.jpg)
![runepriest_041](https://cloud.githubusercontent.com/assets/8081009/3564209/ed8a9366-0a75-11e4-8332-ea331c34778f.jpg)

**Comment by Reggaewaldo** [comment]
This guy should not sell RvR gear. Deleted all gear he sales. We will have to fix him up as a real Craft supply merchant.

**Comment by Reggaewaldo** [comment]
Closing created new issue with the loot table #1480
