### ISSUE TITLE
Quest: Redemption in High Pass

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#2301]
The gate to enter the Tomb of the Traitor in High Pass at Approx 4076 by 39215 is not able to be opened. This location is supposed to be accessible for the PQ  and for the Quest Redemption. I understand PQs are not all fixable at the moment but after finding that you need access for the Quest Redemption also I decided to post this message.

**Comment by Meralors** [comment]
Fixed crypt gate, it now open !
