### ISSUE TITLE
Quest: Chapter 3: The Trail of Bones

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#2303]
![skafgrim_019](https://cloud.githubusercontent.com/assets/13737673/11802404/60ee1256-a2be-11e5-85a7-798a012a7b67.jpg)
 
Picture should say it all.

**Comment by Meralors** [comment]
This quest is part of a long quest line and shouldn't be available right away. Also one of the previous NPC involved in this line ( Garek Hammershield ) isnt in game yet. It may take time to fix all the quest line.

**Comment by DanaBloodkiss** [comment]
Capital City quests got deactivated.
