### ISSUE TITLE
New Users can´t register

### ISSUE THREAD

**Issue by Vancerus** [WarEmu/WarBugs#2304]
Hello,
a friend of mine wanted to register and gets the error pictured below. I tried to confirm and i also get the same error when trying to register a new account.

![general error](https://cloud.githubusercontent.com/assets/14907399/11809920/8c520eb8-a32a-11e5-9525-34a16b03efab.png)

**Comment by Vancerus** [comment]
Workaround is: 
1) try to register -> get error
2) try to login using the user/pw from before -> get errormsg for account not activated yet (but you dont get an activation email until the next step)
3) click send activation email again
4) check inbox for activation mail and click the link in it -> get errormsg (the same as picture above)
5) you can now successfully login to the game

**Comment by ozarmidrashim** [comment]
This isn't an emulator bug
