### ISSUE TITLE
Cloudflare IPs flagged as spammer

### ISSUE THREAD

**Issue by magicthighs** [WarEmu/WarBugs#2305]
I can't comment on the forums anymore, I get this message:

"Your IP 141.101.105.216 or your username magicthighs or your e-mail address xxxxx@gmail.com has been blocked because it is blacklisted. For details please see http://www.stopforumspam.com/api?ip=141.101.105.216&username=magicthighs&email=debeuk@gmail.com.
An entry on the blacklist may have several reasons:
1. You are a well-known spammer.
2. Last time a well-known spammer was using the dynamic IP address which you got from your ISP (Internet Service Provider), your e-mail address or the username you have choosen.
3. Your ISP is well-known for a lot of spamming customers and is not fighting against spammers enough."

A whois on the IP in question shows that it's owned by cloudflare.

**Comment by ozarmidrashim** [comment]
This isn't an emulator bug

**Comment by magicthighs** [comment]
I know. I can't comment or PM anyone on the forum about this, that's why I posted it here.

**Comment by ozarmidrashim** [comment]
Yeah, we know about it already.
