### ISSUE TITLE
Devestator Slayer Helmet

### ISSUE THREAD

**Issue by donsastre** [WarEmu/WarBugs#2307]
it has no appearance and if you wear it, visibility enabled, your hair disappear :3 slayer looks strange xD

greetings

**Comment by Ryanfawkez** [comment]
Do you know what the Devastator helmet is supposed to look like? Please include a picture if you can.

**Comment by donsastre** [comment]
this one looks pretty like the rest of devestator set

http://www.blogcdn.com/massively.joystiq.com/media/2009/03/4236tygwarr.jpg
http://33.media.tumblr.com/tumblr_m6t7gsMYXK1qhwu0p.jpg

maybe the shoes have also the wrong apperance

greetings

**Comment by Ryanfawkez** [comment]
I'll see what I can do.

**Comment by donsastre** [comment]
thx a lot sir ... the earlier days in t2 at the day we could used only the devestator shoes they had an other skin which was nice but with t3 release it changed :3 idk what happende there

**Comment by Ryanfawkez** [comment]
All fixed. This is what it currently looks like; 
![slayer](https://cloud.githubusercontent.com/assets/8767404/11822086/1a02c44a-a36d-11e5-8748-7068382b5b97.png)

**Comment by donsastre** [comment]
wow nice the hair disapearing bug is also gone? awesome!!

**Comment by Ryanfawkez** [comment]
Well, in this particular instance, I simply changed the Devastator War Shroud's appearance to that of an item model the Slayer can actually wear. The previous model was bugged in such a way that it has no model at all for the Slayer, and thus removed his hair.

**Comment by donsastre** [comment]
well idk if u updated but there is now a new skin an other one than the one above xD and my hair are still gone :3 but the shroud is visible 

greetings

**Comment by Ryanfawkez** [comment]
Hasn't updated yet.
