### ISSUE TITLE
Slayer Rage mechanic + Flee

### ISSUE THREAD

**Issue by Gobtar** [WarEmu/WarBugs#2309]
When Flee is used the Rage meter immediately drops to 0 rather than gradually reducing your resource to 0 before starting to climb again.

**Comment by Evildoor** [comment]
@ozarmidrashim - when you'll be checking this, take a look at #1018 too. Its author has not specified the conditions, but i presume it is about rage dropping when you leave combat.

**Comment by Chummi** [comment]
worked like that on live and it shouldn't be changed! if you use any skill which drops rage you also lose all the rage instant. flee was always the onliest instant rage drop for any 2h slayer

**Comment by Evildoor** [comment]
Wrong. I've tried special spec with Power Through + Improved Flee 2, hoping to get 30 seconds in Rage (not Berserk) while fleeing and after it. However, while you Flee (Improved or not), your Rage drops twice as fast as it normally builds, so you drop into green zone from 100 Rage after 7.5 seconds instead of 15 (how i hoped), so my idea was busted. But it was drop at 10 Rage per second, not instant reduction to 0.

**Comment by ozarmidrashim** [comment]
245 Flee
You run away from the battle in a mad panic, increasing your run speed by 30 for 10 seconds.  You immediately lose all of your action points, any career mechanic points, and your Morale will begin to drop, and you will not begin to regain action points until 10 seconds have passed.

**Comment by Gobtar** [comment]
Alright I will explain it better, on live i would slot: Wot Rules? on my choppa, and Power Through on my slayer, when I used flee it would not instantly bring the career mechanic to 0, it would instead slowly start winding down, this would work regardless of whether or not I was in combat. This meant I had just much more time in both the green and yellow rage categories (0-74 resource) before I returned back to the red as the mechanic would have to go to 0 before having to start building again.

Not only would this be a life saver but it also helped with burst, since 25-74 rage is when the finisher abilities are most effective (in conjunction with AP pots). I dubbed it "the back swing"

I never tried using this with improved flee, but having flee work like a finisher (i.e dump rage immediately) is NOT how it worked on live.

**Comment by ozarmidrashim** [comment]
YouTube confirms, another *wonderful* case of wrong info on wikis and wrong tooltips.

**Comment by ropuch** [comment]
Uhm, then maybe it was broken on live, too? On BG after hitting flee Hate is dropped instantly to 0, and morale starts to go down just as tooltip says. And I'm pretty sure it is the same as it was on live (for BG). Flee is working the same for Shaman, DoK, WE and Sorc  (and their order-mirrors, I suppose) - instantly dropping career points. It does not prevent gaining them back, but all career points hit 0 after you flee.
Why Flee for Slayer/Choppa should work different? It's core skill, the same for all classes. I perfectly understand using it (with AP pots) to close the distance, but this seriously looks like a unresolved bug from live. Slayer/Choppa have their rage exhaust mechanic (which both can suppress by Wot Rules?/Power Through, at certain risk/cost) - and now you want to grant them "Oh, I'm so enraged that I feel like cooling down just a tiny little bit" at the cost of AP pot ;-). Apart of "Flee" working differently  on other classes, this is also messing with Slayer/Choppa  rage/chop/exhaust archetype ;/

**Comment by Gobtar** [comment]
The reason why Flee! was different for the choppa/slayer was the double sided sword of trying to use it as a rage exhauster. when you can't exhaust your rage from Wot Rules? you need to use Flee! to get your rage down, but because using flee doesn't immediately exhaust your rage you are in tremendous danger for a good 2-3 seconds as you are still in the red. you are also stuck in the green (>25) for twice as long hampering your ability to return to the fight. If slayers could just pop flee to get rid of rage immediately it makes the Wot Rules? / Power Through tactics much more manageable. 
Drinking an AP pot and hitting the yellow will actually happen faster the way it is implemented now... and the Slayer/Choppa is in alot less danger doing so.

**Comment by ropuch** [comment]
And what about Choppa without Wot Rules? He will just gain next Charge (better than orginal: 10s>7s) staying combat ready at the cost of AP pot.

**Comment by Chummi** [comment]
i'm pretty sure that you lost all the rage in the moment you popped flee, like it was on BG, IB, BW, Sorc, WH or WE. can i see that youtube video which confirms that i'm wrong?

**Comment by Tesq** [comment]
what is wrong with the tooltips? it's correct indeed

"any career mechanic points, and your Morale will begin to drop, and you will not begin to regain action points until 10 seconds have passed."

**Comment by ozarmidrashim** [comment]
https://youtu.be/LIFPGzkmlwE?t=166
