### ISSUE TITLE
Disarm issue

### ISSUE THREAD

**Issue by zuzrat** [WarEmu/WarBugs#2310]
WL's pet still attacking/using skills during SH disarm(i tested it a few times)

**Comment by Chummi** [comment]
was exactly how it worked on live! pet and its owner are 2 different sources of outgoing damage. single target detaunt does also affect either the pet OR the player. it's working like it should and there is no bug.

**Comment by zuzrat** [comment]
Oh my god, u think im so stupid? I used disarm ON PET, not on WL, and disarm does not work at all

**Comment by genisaurus** [comment]
Did disarm work on pets on WAR / should it on RoR? They don't use weapons. Not sure how you would disarm a lion other than.. dis-*arm*ing it.

**Comment by zuzrat** [comment]
Sure it worked on WAR.    http://www.youtube.com/watch?v=ErM4cIw4CEc
2:07
