### ISSUE TITLE
[Quest]: Morr's Bane

### ISSUE THREAD

**Issue by Heteryk** [WarEmu/WarBugs#2311]
Corpse is alive (maybe they should) clicking on them does nothing. Also quest objective seem wrong? 
![rahgal_072](https://cloud.githubusercontent.com/assets/16116091/11837958/4f7bc582-a3e4-11e5-8b94-c85b2a2eef42.jpg)
![rahgal_073](https://cloud.githubusercontent.com/assets/16116091/11837959/512aca5e-a3e4-11e5-85c6-a0712425027b.jpg)

**Comment by Styrkarr** [comment]
This quest shouldn't be available right away. It'll be unavailable in next patch.
