### ISSUE TITLE
Reduced renown gain since last DDos attack

### ISSUE THREAD

**Issue by Rammsteinn** [WarEmu/WarBugs#2312]
Hello my favourite devs ever !

Since last ddos attack, i have noticed a weird kill renown gain gap between players along with some unrewarded deathblows. And I'm not talking about healers vs dps.

For example, in that high pass cemetery, we got 31 total kills. That IB got 3500 renown with 0 db and I got 1074 renown with 8 db although our total kills were 31 both of us. That trend applied to my whole party (premade).

Moreover, some of my deathblows did not trigger any renown. When I killed someone, i had the message "you have slain XXX" in chat window, the kill counted for the kill quests, but no renown was triggered. This also happened for some db's in RvR lakes.

Just had a chat with Lay ingame, he seemed to have noticed the same. I tried to screenshot the last sc summary screen but it showed black :-(

**Comment by Rammsteinn** [comment]
Forgot to mention i'm not renown capped (rr 28).

**Comment by Ryanfawkez** [comment]
This is a common issue which has been persistent before the DDoS attacks.

**Comment by Rammsteinn** [comment]
Ok, thank you for your swift reply :-)
