### ISSUE TITLE
Chests not appearing after completing Public Quests in Starting Areas

### ISSUE THREAD

**Issue by SmallTownGriff** [WarEmu/WarBugs#2315]
Hi,

Very new to RoR so may be an ongoing trend but after completing the chapter 1 public quests for the order and destruction starting areas the reward chests do not appear following completion. 

Thanks,

STG

**Comment by Gobtar** [comment]
Chests and PQ related loot rolls are not in the game yet.

**Comment by SmallTownGriff** [comment]
Fair enough, no worries :)
