### ISSUE TITLE
Thickmuck War Shroud - Slayer

### ISSUE THREAD

**Issue by AlwaysOnCloud9** [WarEmu/WarBugs#2316]
Has no appearance and no crit chance rating which im being told it should have both. Was told to submit a ticket here and it should get fixed.

**Comment by Evildoor** [comment]
Crit part is already fixed on dev server.

**Comment by AlwaysOnCloud9** [comment]
Awesome.. Would love the visuals also but not so concerned about that

**Comment by Styrkarr** [comment]
Fixed in the next patch.
