### ISSUE TITLE
Inevitable Doom - Slayer

### ISSUE THREAD

**Issue by AlwaysOnCloud9** [WarEmu/WarBugs#2317]
This ability was partially working.. as of tonight though all the sc's ive done it is completely broke. 1st original problem: inevitable doom does not take into account any movement after it has been applied. Meaning the aoe only hits people that were around the original target when ability was first used. 2nd new issue: As of 12/17/2015 ive done 4 sc's and Inevitable doom is only effecting 1 target.. It is not doing any AoE damage at all.

**Comment by ozarmidrashim** [comment]
Personally tested and I see absolutely no evidence of this. Removing my assignment until video evidence is provided.

**Comment by AlwaysOnCloud9** [comment]
Will upload a video later tonight/tomorrow of both situations. 100% know since t3 release the 1st issue always happens. 2nd issue only happened last night during about 4 sc's. Something that might help your testing.. I am running full skavenslayer with the 3 abilities unlocked. 3 tactics would be the one that just gives strength, +15% damage when flanking and Bleed on crit. I usually run the armor tactic and havent seen the 2nd issue.. maybe something with the bleed on crit.

**Comment by AlwaysOnCloud9** [comment]
Got a bit more action into it tonight and cant noticably see it like before. IF if happens again I will be sure to record it. Thanks for everything!
