### ISSUE TITLE
Pounce working through fences in High Pass

### ISSUE THREAD

**Issue by Renork** [WarEmu/WarBugs#2320]
Morning,

I don't believe this was the case on live, but pounce bypasses the fence on highpass scenarios.

**Comment by ozarmidrashim** [comment]
So do ranged attacks, which is equally stupid.

**Comment by Renork** [comment]
I mean *technically* a projectile could fit through a fence :^)

**Comment by dcephas** [comment]
I disagree,. A pounce could/should scale a 5' ft fence, provide there is a line of sight, as you do have at the grave yard.  the WL is jumping over the fence bro.   Simple physics.

**Comment by Renork** [comment]
Well, I'm 98% sure pounce didn't allow you to jump over the fence on live. If you prefer to leave it this way, then that is fine. ^ Dcephas, I don't know who your college physics professor was, but going through a fence is not the same as jumping over it, plus physics truly does not have a lot to do with this, unless we're going to integrate calculus equations here :^)

**Comment by Luth-RoR** [comment]
The problem is here probably that the fence is only a semi-transparent texture without a model. 
I guess this can't be changed without client modification.
