### ISSUE TITLE
Butchering Materials

### ISSUE THREAD

**Issue by Squea** [WarEmu/WarBugs#2322]
The butchering ingredient: Thick Porcine Bile drops from: Iceridge Sabertusk, in High pass.  This is a swine or hog type ingredient.  Sorry I don't know how to add labels.

**Comment by Squea** [comment]
I've seen other cats drop this item.  It might not be a bug just a strange choice; perhaps cats needed another butchering item to drop.

**Comment by genisaurus** [comment]
Was fixed at some point
