### ISSUE TITLE
Butchering: High Pass mobs

### ISSUE THREAD

**Issue by Squea** [WarEmu/WarBugs#2323]
Grisly hound 24 wolves, Bloodsnout Tuskgor 24 boars, not butcherable.  Approximately 45k 45k high pass, order area.

**Comment by Squea** [comment]
Steinbruck Stag 22 Deer, 4k 20k Talabacland, not butcherable.

**Comment by nalgol** [comment]
should be a creature type error deers well what should they drop?

**Comment by Squea** [comment]
I've thought about this.  It seems that there are main apothecary components that correspond to main stats: Willpower, Intelligence, Strenth, Ballistic.  These are all covered by: Cats, Unicorns, Bears, Vultures.  There are at least two sources of damage shield potions, Griffon/Frond; and at least two sources of armor ingredients, lizards/scorpions.  Perhaps they should drop toughness main ingredient as another source of toughness pots.  Although venom from a deer is stupid so perhaps not.  There have to be some gaps in the butchering drop table.

**Comment by Squea** [comment]
Location: Norsca/Order 56k, 52k
Mob: Hrim Tuskgor/ Skakkr Tuskgor Level 9
Not able to butcher.

**Comment by Evildoor** [comment]
Spiders are fixed in next per #4338.

**Comment by genisaurus** [comment]
Was fixed at some point
