### ISSUE TITLE
[Witch Elf] Witchbrew

### ISSUE THREAD

**Issue by Chummi** [WarEmu/WarBugs#2324]
It does not scale with strength, weapon dps or get any contribution from flanking.

**Comment by Evildoor** [comment]
Uh, was it different on live? Because i've tried changing DPS and STR, and the tooltip damage stays the same. Dunno about Flanking.

**Comment by Chummi** [comment]
i'm not 100% sure how it worked on live since i never played a WE outside the pts. was just curious to see that there is literally no stat or tactic contribution. going to ask some friends of mine later and try to find a proper confirmation

**Comment by ozarmidrashim** [comment]
If the tooltip shows no stat contribution when you modify your weapon or strength stat, the damagetype is proc damage and it does not scale, making this a false report.
