### ISSUE TITLE
issues related to the missing RP+Zealot abilities

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#2326]
I have noticed some peculiar behavior from some abilites known as Runes (RP) and the Zealot as well.
There is maybe a connection to the fact that these abilities are not completely implemented including the particulars for each of those additional effects.  My thought is that these abilities are/should be handled differently then others?
Other things wrong when using the buff aspect of the Runes they are prone to double or triple applications, which is not right.  Maybe the root cause of this is because of the missing abilities?
It's curious that there may be other side-effects as well such as perhaps 'stuck in combat' as well.

sorry not a precise BR at all.

**Comment by Evildoor** [comment]
Pardon my possible stupidity, but what do you mean? What is "peculiar behavior" and what is "double or triple applications"? I've noticed nothing wrong with these abilities, they work as on live (apart from not granting abilities) - buff stats. What am i missing?

**Comment by Squea** [comment]
I believe this is a UI issue, the buffs are not doubling and tripling it just the current state of the in-game UI.  Pure target bars update well and are the best atm, imo.
