### ISSUE TITLE
Tenuous Situation

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#2331]

**Comment by gittoaster** [comment]
quest 'Tenuous Situation' completes without doing anything

Order - Saphery
Quest Giver Sonsea Stormfire

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by wargrimnir** [comment]
Quest does not have a quest blob indicating where to find these two NPCs.
http://i.imgur.com/hjVDxZX.png

**Comment by DanaBloodkiss** [comment]
Fixed in next patch.
