### ISSUE TITLE
Bladed Whispers

### ISSUE THREAD

**Issue by PTWar** [WarEmu/WarBugs#2337]
Tarond Frostrage's quest "Bladed Whispers" does not apear on npc...

**Comment by Squea** [comment]
I have it on higher toons.  The level requirement is too high for the armor to be of value.  Quest level should be reduced to 10 or 12.  Good Will, the Tracker quest for witch hunters is available at a lower level 12 or 13.

**Comment by PTWar** [comment]
Still bugged...

**Comment by Squea** [comment]
I've just now picked it up on my 32 chosen.  Still haven't completed it all the way, but you can get it.

**Comment by PTWar** [comment]
I'll Check again tomorrow then. Ty.
On Jan 8, 2016 21:52, "Squea" <notifications@github.com> wrote:
>
> I've just now picked it up on my 32 chosen. Still haven't completed it
all the way, but you can get it.

**Comment by PTWar** [comment]
Well... I cant get it with my lvl 13 Chosen... Which is strange... Because I could get the other two with the same char...

**Comment by DanaBloodkiss** [comment]
It's for Level 16.
