### ISSUE TITLE
Quest:  Bloodhorn Beckons appears to be broken

### ISSUE THREAD

**Issue by mursie** [WarEmu/WarBugs#2338]
Supposed to go to Mt. Bloodhorn and speak to Splitsnout (which it says in the quest bio) but the actual complete says talk to Forynir Amberbreak which doesn't exist.  Talking to splitsnout doesn't complete quest any longer.

**Comment by Evildoor** [comment]
Tested - everything works for me. Text says "Speak to Splitsnout", and he correctly finishes it and gives you xp / money.

**Comment by Evildoor** [comment]
No additional info provided, closing.
