### ISSUE TITLE
Spells not firing correctly after latest patch.

### ISSUE THREAD

**Issue by Renork** [WarEmu/WarBugs#2340]
It takes 2-3 times for a spell to go off. For example, if I attempt to cast pandemonium on my magus, it will begin casting then stop, so then I have to cast it again. The targets did not go out of range either. This happens to the instant dots also, they will not fire the first time, and sometimes the second time.

**Comment by magter3001** [comment]
This happens to all abilities. If you click on them, they seem to work but if you press the keybind, they will fail a lot. Really annoying when you wish to switch guard to someone and you have to stand 5 feet away from them in order for it to work or fire off. :/ Alpha :P

**Comment by Tesq** [comment]
for guard use enemy switch, via click on the party ui, it dont fail, for the other skill is well know that this can happen sometimes sadly

**Comment by ozarmidrashim** [comment]
Bug in position history manager
