### ISSUE TITLE
Land mine & demonic infestation graveyard

### ISSUE THREAD

**Issue by Renork** [WarEmu/WarBugs#2341]
These little suckers are appearing everywhere.

**Comment by Tesq** [comment]
the issue are stranges, models seems losing their patterns and became  string/lines,

It may  be related to a second bug, yesterday i was able to use for the first time more than 1 demonic  infestation but i was also able to infinite summon them, the max you can active was 3 on live, after 3 the new one make disappear the first one. Maybe the relentless spam of some dudes bug the server cos i saw work those skill in some moments and not in others.
