### ISSUE TITLE
Guild disappearance

### ISSUE THREAD

**Issue by Yaliskah** [WarEmu/WarBugs#2345]
On last connection, all guild related infos for all guild members have disappear, as if the guild hadn't exist.
Guild Name  : Vox Irae  Lvl : 7
Leader : Hasard ( Yaliskah )
Guild members : Mamain - Jinhees - Mordreed - Dasheal - Dentelle - Medusae - Marilagal....

**Comment by imneo58** [comment]
Our guild disbanded as well. 
Guild Name : Violently Folded Towels
Lvl : 10
Guildleader: Molonlabe
Guild members : Molonlabe, Yerina, Brightknight, several more I can add if needed.

**Comment by phsampaio** [comment]
Our guild disappeared as well, twice this week. We had to reform again, twice.
Guid Name: hCore
Level 4 or 6 (cannot remember exactly)
Guild Leader: Truekandur
Guild members: Tomate, Morvius, Arquimago, Adoky, Barbeiro (and others I can't recall now)

**Comment by SATANICOMODERNO** [comment]
Actually my guild isn't being deleted, but the number of the members is being reduced to 10 every server restart.
