### ISSUE TITLE
Squig Armor stats visual issues

### ISSUE THREAD

**Issue by zuzrat** [WarEmu/WarBugs#2348]
On live squig armor gave you a toughness and wounds bonuss, and there is some visual bug with CD on this skill.

**Comment by Evildoor** [comment]
Use .getstats to get reliable info about your character, not character screen. Wounds and toughness are properly changed here. Cooldown - what's the problem? Tested, it works fine.

**Comment by zuzrat** [comment]
Yea, you are right, So there is only tooltip bug. About CD, there is no  10,9,8,7 etcetc :D. You cant use squig armor for 10 sec, thats true,but again, i think its a bug coz u cant see exactly when you can use this skill again.

**Comment by Evildoor** [comment]
Uh, i just tested it and noticed no such thing. i use Squig Armor, i leave it, 10 sec cd starts ticking.

**Comment by zuzrat** [comment]
Meh, seems only i have this issues:/ Addon Cdown dont show CD for me aswell.

**Comment by Evildoor** [comment]
Hmmm. Maybe it is broken on live server, but fixed on dev server. Can't test it on live, i have no SH. Ok, i'll change the name a bit and leave this ticket open. Maybe someone will confirm my guess.

**Comment by zuzrat** [comment]
This bugs were fixed in last patch. Not sure how to close it by myself....
