### ISSUE TITLE
Ability going on CD when target dies before it hits

### ISSUE THREAD

**Issue by zuzrat** [WarEmu/WarBugs#2349]
When you use your abilities(not sure if melee have this problem tho) and your target died before your ability landed on it(and did 0 damage obviously) this skill still goes on CD.

**Comment by Evildoor** [comment]
Was it different on live?

**Comment by zuzrat** [comment]
Yes i guess, thats why i wrote it here:D

**Comment by Evildoor** [comment]
Proof?

**Comment by zuzrat** [comment]
http://www.youtube.com/watch?v=VKA05gbSTOQ    4:09
watch it on slow speed, You can see that he tried to use Finish'em off(it even goes on CD as well for 0.1 sec, obviously u can notice it only  in slow mode) but after target died and skill did not landed CD dissapeared.
