### ISSUE TITLE
Pets don't die/unsummon when out of range

### ISSUE THREAD

**Issue by M0rf** [WarEmu/WarBugs#2353]
Not sure on the correct distance but currently all pets stay until they die no mater the distance from the owner, they should disappear when out of range of the owner.

**Comment by milosxe** [comment]
Disappear or teleport back to owner's location?

**Comment by M0rf** [comment]
Disappear and go on cooldown to punish sloppy play of not paying attention to your pet, thats how it worked on live.
About the range i have a feeling but could be wrong that they should disappear when the owner is no longer in view distance, how far that is i dont know.
