### ISSUE TITLE
[quest] Celestial Defender - broken questline on tasks req

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#2356]
The quest is missing some steps functioning properly.

thx

**Comment by Ryanfawkez** [comment]
Care to elaborate on which steps cannot be completed?

**Comment by gittoaster** [comment]
gladly..  
[url=http://postimg.org/image/f4zeiig29/full/][img]http://s16.postimg.org/9gt3rmbpx/Sleeperheals_012.jpg[/img][/url]
this screenie shows the stage that 'auto-completes'.  

this is the only note I can find for that particular task..

http://www.warbits.com/gold-quests-1002-Celestial-Defender.html

From memory I think the task should be something like kill 12 Vile Fiends and 1 recover Rift Fragment.

Other than this step the rest of the quest works.

**Comment by Ryanfawkez** [comment]
Those sequences are spawn-script based by the logical consequence of the quests; which is unsupported at this time. They've been made auto-completeable as a means of work-around. This quest cannot be completely fixed to its original state, yet.

**Comment by Sortas** [comment]
![sortas_021](https://cloud.githubusercontent.com/assets/16688534/12303222/d28828ae-ba31-11e5-96bb-2ef35434d1b1.jpg)

**Comment by Evildoor** [comment]
Closing per #3868.
