### ISSUE TITLE
ToK quests 

### ISSUE THREAD

**Issue by darkha** [WarEmu/WarBugs#2357]
I've got a problem with Tome of Knowledge. 
I can take quest but as soon as I go SC or other zone the quests dissapear from ToK. I can't see them at all. I can still do them but I can't see the progres.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
