### ISSUE TITLE
Chicken after Ranking up in Scenarios

### ISSUE THREAD

**Issue by Lileldys** [WarEmu/WarBugs#2358]
I've been seeing and have seen people saying in /ad that ranking/leveling up in scenarios and being turned into chickens, even though they are still in the appropriate tier.

**Comment by Evildoor** [comment]
Strange. I've seen (before patch) that levelling up in scenario leaves you without bolster (#1646), but not this.

**Comment by Tiggonos** [comment]
i can confirm this.
