### ISSUE TITLE
Casting in mid air

### ISSUE THREAD

**Issue by CornerbackAC** [WarEmu/WarBugs#2359]
When kicked/knocked back, you get interrupted when you are kicked AND when you land on the ground again.

IIRC, the kick on live only interrupted you when being kicked, NOT when landing again.

**Comment by ozarmidrashim** [comment]
While you're in the air, you count as Moving and casts are rejected.

**Comment by tutti13** [comment]
no. i can cast while flying. but the cast is interrupted when i land on the ground, which wasnt the case on live servers.

**Comment by ozarmidrashim** [comment]
@noisestorm

**Comment by Tesq** [comment]
this explain what it happened to me too sometimes

**Comment by noisestorm** [comment]
Working as intended. Only instant casts work for kicks. If on live you ever where able to cast while flying that was a lucky case of lag most likely but not intended.

**Comment by Tesq** [comment]
No it's not you CAN cast atm while in air , and only get interrupt when you land, reoprn it

**Comment by tutti13** [comment]
Exactly. Landing shouldn't interrupt you again.

**Comment by Tesq** [comment]
On RoR was decides that KB should not allow cast and this is different from live but this is not the case cos  you can actually cast while in air like it was on live atm but you get interrupt when land

@noisestorm can you reopen it?

**Comment by ozarmidrashim** [comment]
Just a heads up - I will be fixing this in the direction of blocking casts while airborne, not in the direction of allowing casting while in the air.

**Comment by ozarmidrashim** [comment]
And after testing, it shows the correct "Moving" state while airborne. There's nothing to fix until I see a video proving that you can successfully cast anything while airborne from a KB.

**Comment by Blubberino** [comment]
https://www.youtube.com/watch?v=NprJWU_i4xw

17.58 dok starts and compleats a grp heal mid air

https://www.youtube.com/watch?v=TJYFl3F11Mg

Skip to 7.15 for several casts after kick and mid air.

**Comment by taccr** [comment]
My 2 cents here.
Pretty sure the first interrupt when you are getting punted was the same on live. Only exception was when the caster had FM up.

Second interrupt when landing I don't really remember but there is probably some videos of it. My guess is that it didnt interrupt.

First video shows the dok ST heal being cast while flying. (It's not a group heal)
Second video doesn't really show anything but you can start channels while airborne.

**Comment by Guerra-warhammer** [comment]
https://www.youtube.com/watch?v=2iH48vYm-8g

12:20 engi cast in the kick

**Comment by noisestorm** [comment]
copypaste from other topic
>https://www.youtube.com/watch?v=NprJWU_i4xw

>17.58 dok starts and compleats a grp heal mid air

a) that is a 0.5 sec single targte heal 
b) like i said you could even cast 1.0 sec casts on the move since the games movement check was shit.

>https://www.youtube.com/watch?v=2iH48vYm-8g

>12:20 engi cast in the kick

this is a channel spell, londo mentioned something about channels not being interrupted.

**Comment by Guerra-warhammer** [comment]
but you cant cast a 0,5sek cast on this server

**Comment by noisestorm** [comment]
Sadly for now i cant provide a video, but for a fact i abused casting on the move myself over the years of playing. Its not something i believe was possible, its something i did in fact abuse all the time. If you were standing still the first 0.1 sec of any cast that was lower >= 1.0 sec you could just cast the other 0.9 sec without standing still. 

Also i can just repeat myself again: movement checks on live were shit, kick itself was already proven (in another topic) to interrupt indeed as well and for consistency's sake the interrupt was carried on for the kick duration. consider it a fix for shit that mythic didnt bother to corretc themselves.

**Comment by Guerra-warhammer** [comment]
when i post you a vid with a 2sek cast or longer, then you fix the bug or not?

**Comment by noisestorm** [comment]
Judging from Azas post he will change it for now, but that doesnt mean that this could not be considered to be changed for balance sake at a later stage.

**Comment by Blubberino** [comment]
You can see that it is totally possible to do a full 3s channel I don't see why other casts shouldn't be possible then you can 0.5s casts you can see magus starting casts so stop it really this is a bugtracker prove me wrong then.
It's not like caster is super strong in a grp based setup anyway, meele is meta and not the otherway around.

 I mean look at your statement here: 
c) this is a channel spell, londo mentioned something about channels not being interrupted, allthough i personally see no reason why they shouldn't, even if he is right about it. 
It's proven there so it's NOT your decision.

**Comment by noisestorm** [comment]
Channel spells do not behave like your normal spell, so you cannot consider them to be equal

**Comment by Blubberino** [comment]
Now we have here Touch of the Divine (1s) while getting pulled. 

https://www.youtube.com/watch?v=Rf1EV0jPtkM
2.15

**Comment by sioding** [comment]
This is already fixed
