### ISSUE TITLE
Big Choppa of Dominion

### ISSUE THREAD

**Issue by Squea** [WarEmu/WarBugs#2361]
Minimun level 14, requires 9 renown.  The second talisman slot on this item can only be slotted with level 8 talismans, while the first slot allows the proper level 12 talisman.

**Comment by Evildoor** [comment]
Maybe this is a particular case of point 1 in #2480?

**Comment by Squea** [comment]
Hmm, I will buy it and try again to confirm.

**Comment by Evildoor** [comment]
No response, closing.
