### ISSUE TITLE
Blue Gear dropped from PvE mobs

### ISSUE THREAD

**Issue by Jaycub** [WarEmu/WarBugs#2364]
Assuming this isn't intended?

Dread-Woven Darkstaff off of Runebough Branchwraith (champion mobs @ 5500 7000 Saphery)

edit: got another blue drop 100% sure now that it is happening

**Comment by magter3001** [comment]
Maybe it's because of the new event? The quest items those mobs drop are rare item drops.

**Comment by milosxe** [comment]
Nope, they do drop. But with a really low chance. I got 2-3 blues maybe from champ mobs, 0 from regular.

**Comment by DanaBloodkiss** [comment]
Fixed in next patch. Thanks for the report!
