### ISSUE TITLE
Bandit's and Outlaw's salvaging bug

### ISSUE THREAD

**Issue by magter3001** [WarEmu/WarBugs#2365]
Some of the level 31 gear such as Bandit's and Outlaw's give a level 1 mat for crafting when salvaged, instead of a level 150 mat. There are numerous items so I don't know if you guys want me to find all the items that give out the level 1 mat.

P.S. for players: You can use a character with level 1 salvaging to find out which item will give out a level 1 mat and which one won't.

**Comment by Evildoor** [comment]
Same bug applies to many items, starting from Wanderer IIRC.

**Comment by laattori** [comment]
If an item does not show item level in the tooltip it is such an item.

**Comment by magter3001** [comment]
Bandit's Choppa and Bandit's Blood Drinker would give level 1 mats, both don't have an item level shown.

**Comment by Squea** [comment]
Rings for the most part salvage at level one.  Cloaks and most armor have proper levels.  Few weapons need item levels.

**Comment by Torquemadra** [comment]
without specific names nothing will get done as not searching the entire database. Get me names and will fix.

**Comment by Squea** [comment]
Many of these have been fixed; rings now have item levels, and salvage for the proper materials at this point.  This can probably be closed as a general topic in favor of specific item posts.
