### ISSUE TITLE
Event Q:As Lord TcharZanek Demands

### ISSUE THREAD

**Issue by Aelice** [WarEmu/WarBugs#2368]
After killing 25/25 enemys, Gather information from an Emire courier.

I cant get courior to trigger my quest and several others seem to have the same problem.

**Comment by Aelice** [comment]
Working again after the server restarted.

**Comment by gittoaster** [comment]
I haven't found the turn in for this for Order, yet..  Can anyone confim the turn in for me plz

thx

**Comment by Meralors** [comment]
Did you try Captain Hans Boschmar? he's the one giving quest, should be the one to return it.

**Comment by Evildoor** [comment]
Bugged again according to #3959

**Comment by DanaBloodkiss** [comment]
Should work. Talked about it with someone else.
