### ISSUE TITLE
Lagging out of sc link data

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#2370]
just lagged out of sc after that happened in an sc (screen chat). i think i tabbed to the chosen and than game stopped and client crashed.

perhaps it helps.

![martock_025](https://cloud.githubusercontent.com/assets/13809443/11918151/8cc2291a-a725-11e5-9c74-8629ca613737.jpg)

**Comment by Londo001** [comment]
Looks like packet corruption.

**Comment by Evildoor** [comment]
Closing since packet corruption is reported elsewhere.
