### ISSUE TITLE
Combat bug

### ISSUE THREAD

**Issue by zuzrat** [WarEmu/WarBugs#2371]
If i use Behind ya,finish 'em off or shrapnel arrer(or some other instaskill) just after What Blocka? i noticed in combat log that what blocka doing damage only AFTER this instaskills. Seems speed of this arrow is too slow or smth like that.

**Comment by Evildoor** [comment]
Second bug was already reported.

**Comment by zuzrat** [comment]
Oki.

**Comment by Gobtar** [comment]
Travel time of Wot Blocka is always a bit slow, this allows you to Wot Blocka, 1s Plink/RunNShoot, and one of your instants to all land around the same time stamp.

**Comment by Evildoor** [comment]
So it's not a bug then? Instant casts were always fast, while Wot Blocka was slow?

**Comment by Gobtar** [comment]
I will start looking up Youtube videos

**Comment by Gobtar** [comment]
https://www.youtube.com/watch?v=VKA05gbSTOQ
4:24 seconds

**Comment by Evildoor** [comment]
Yeah, Wot Blocka seems slower than Finish Em. Not a bug then.
