### ISSUE TITLE
Disrupt

### ISSUE THREAD

**Issue by kirrahakotta** [WarEmu/WarBugs#2376]
You can't disrupt with taunt and the taunt wont pull mobs who has already aggroed on someone.

**Comment by Evildoor** [comment]
Disrupt with taunt? What?
Aggro system is barely implemented.

**Comment by milosxe** [comment]
Maybe he means interrupt someone that is casting?

**Comment by Evildoor** [comment]
Maybe, but it would be wrong. Taunt interrupts just fine.

**Comment by kirrahakotta** [comment]
Precisely milosxe, I have tried to interrupt many times but dont notice that it works

**Comment by Tidybraveguinea** [comment]
As a def tank, I use taunt only to interrupt casts/skills and do it often. I'd probably notice if it wasn't working. Unless it somehow got broken recently, like the posterns.

**Comment by kirrahakotta** [comment]
Okey then it might been a short while it didnt work for me, or the animation for the other char did not interrupt even though the skill did :) 

I play as def tank too and use taunt a lot in pvp so if it would stop work my job would be a bit harder :")

**Comment by Tidybraveguinea** [comment]
I can pretty safely confirm that taunt correctly interrupts skills. Taunt pulls mob on you even if that mob is attacking someone else, exactly how it must be. How "strong" is this pull in terms on agro, this I don't know.

**Comment by Evildoor** [comment]
@Tidybraveguinea, are you talking about interrupts working after latest patch, or before it? I can confirm that they worked before, but don't know about after.
