### ISSUE TITLE
I have no option to play the game only cinematic, credits, setting and quit

### ISSUE THREAD

**Issue by ninjachicken2e** [WarEmu/WarBugs#2377]

**Comment by Evildoor** [comment]
I thought we had #2375. Which was answered.

**Comment by ninjachicken2e** [comment]
are the servers still down because if not then something is wrong

**Comment by Evildoor** [comment]
The bugtracker is not a place for such kind of problems. Use forums.

**Comment by ninjachicken2e** [comment]
ok
