### ISSUE TITLE
MISSING STUFF

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2379]
Many things are missing...potions from quests or buying them...still dont work.Rolling chest never shows up in public quests...can you fix these guys? These stuff are really basic/important...especially the public quest chests! Thanks ! #PUBLIC QUESTS #POTIONS 
E.g.I heard that Public Quests Chests(bags) are in scripts so you have to re-write them from the beggining or something like that.It would be awesome if you could do that...to get the full experience from PQs.

**Comment by Evildoor** [comment]
We know all this, no need to point out the obvious.
