### ISSUE TITLE
[Rune Priest][T3 Influence reward Dwarf] Tickmuck Skullcap/Passwatch Skullcap missing Stats

### ISSUE THREAD

**Issue by Dalekith** [WarEmu/WarBugs#2382]
Hi,

I likely think this is the case for all classes helmets - I didn't find the helmet for Rune Priest but a helmet for either the shaman or zealot. AM and RP helmets should obviously have the same stats

Thickmuck Cowl - 2% Heal crit (please see here: http://www.arsenalofwar.com/armor/Destruction/Thickmuck%20Cowl)

**Comment by Torquemadra** [comment]
After checking it in the database it showed the heal crit on it but was missing stats. 

Fixed next patch
