### ISSUE TITLE
Live Event RVR quest Part 3

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#2383]
I don't see anything on the bug tracker so I'm writing this up, no players have been getting credit for Keep lord kills for this quest as far as I can tell. I'm pretty sure you all know about this and are working on it but just in case here is the Bug report about it.

**Comment by Renork** [comment]
I created a thread about it, and it doesn't look like anyone has been able to complete it. Thank you for posting it on the bugtracker.

**Comment by geezereur** [comment]
Yeah it seems no one gets the credit for killing keep lords.

**Comment by DanaBloodkiss** [comment]
The quest was changed long ago so I will close this. You can now finish the quest.
