### ISSUE TITLE
Loots Roll in Sc and RVR

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#2384]
For the last two days I've noticed that when items drop in any kind of RVR only the 6 man group that (i think) got the Killing Blow are able to choose and roll for the items. I read back through the chat log and only saw members of certain six man groups in the WB or SC team choosing and rolling, others in the WB or Party did not have any choice, I was able to roll on some but not others so it's not just me being excluded on some rolls and when I was able to choose and roll only the others in my 6 man group also were able. I'm guessing this is a recent change? or bug? after the parch a couple of days ago. If it was changed on purpose,why? if it's a bug, (unintended change) that's why I am writing this :). My only thought on how this happened is maybe when the change was made to the solo players in SC there was an unintended change to all loot rolls?

**Comment by Evildoor** [comment]
This is a bug. Sometimes you get no roll, XP and renown even when you land a DB yourself.

**Comment by ozarmidrashim** [comment]
This is intentional, I assumed a warband was handled as 4 separate groups when it came to XP, Renown, Inf and drops.

**Comment by Evildoor** [comment]
Hmm, i believe we are talking about two different issues here.
1) WB consists of 2 parties. Party 1 gets deathblow - party 2 does not gets XP and other things. This is intentional.
2) But sometimes you (and other players in your party) get nothing even when YOU land a deathblow on target. This is big.
If @Shadowsmove meant only the first issue, and not the second - my apologies, i misunderstood.

**Comment by Shadowsmove** [comment]
I had meant the both :). but as far as the intended change, what happens when players outside the KB part are healers helping everyone do they get a roll? or other players are contributing in some way. You changed so solo players in SC can't steal KBs and get the rewards but there is nothing preventing a player in one part of a WB from doing the same to another part. One group is doing all the damage and then a SW or whoever from another group nabs the KB and his group get all the goodies.I know this would be hard to tell who does what in a mass battle but against small groups or solos it could easily happen. This may also encourage WB leaders to stack their own part of the WB with melee or AOE so they get more killing blows or push some types of players to one group limiting their chances of scoring a KB. I really think this might cause more problems in the future with these types of issues and then more and more warbands will be only made closed and only made up of people who trust one another, guildies and so forth, leaving many of the players that normally jump on a WB to help out in the cold. Just my opinion of how this could go. i know I sound negative about the change but honestly this is just my feedback.

**Comment by Evildoor** [comment]
Second problem seems to be fixed. First one is a balance decision, so its discussion does not belongs here. Closing.
