### ISSUE TITLE
Healing Energy

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2389]
So when you build up full FORCE to reduce cast time of healing...when your healing ability gets instant cast...you cant cast them while you are moving...you have to stand still. I dont know if you are aware of this but its pretty unrealisting...CHEERS :D

**Comment by Evildoor** [comment]
Tested. Applied 5 Law of Conductivity to a mob, cast Boon of Hysh on the move, it worked.

**Comment by Stefanosgr18** [comment]
Healing energy doesnt work...you have to stand still :-1:

**Comment by Evildoor** [comment]
Indeed.

**Comment by ozarmidrashim** [comment]
HE wasn't benefitting from the mechanic at all.

**Comment by Stefanosgr18** [comment]
@ozarmidrashim Indeed...thanks!

**Comment by Stefanosgr18** [comment]
Fixed! Thanks...cool!
