### ISSUE TITLE
Butchering: Squig

### ISSUE THREAD

**Issue by Squea** [WarEmu/WarBugs#2391]
Butchering Squigs only drop porcine bile.

**Comment by noisestorm** [comment]
Mob-archetypes (like Pig, Cat, Vulture, Scarabs) just have some general mat associated to their Types. If someone can provide a valid List of which mob should drop which exactly this can be changed, or rather filled up on mobs.

**Comment by Halhammer** [comment]
Think most of them drop correct mats already. Squigs used to drop heal pot mats iirc.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
