### ISSUE TITLE
SHIELD OF SAPHERY ARCHMAGE

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2392]
![123](https://cloud.githubusercontent.com/assets/16375224/11930281/a984a21a-a7ea-11e5-9fde-b5ef2860d492.jpg)
It says target must be in a group or a warband...but you can cast it to every ally...:/

**Comment by milosxe** [comment]
This was an intended change from live version. Closing.

**Comment by Stefanosgr18** [comment]
But you can change the text on the ability...isnt it easy? Just remove the : Target must be in group or warband

Thanks keep up the good work!
