### ISSUE TITLE
ARCHMAGE ability text

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2393]
SHIELD OF SAPHERY ARCHMAGE...doesnt show absorb text pop up when taking hit by an enemy on RVR or PVP.

**Comment by noisestorm** [comment]
Just Visual though. Effectwise the skill is working as intended

**Comment by Stefanosgr18** [comment]
@noisestorm It is fixed...you can close it. Now text shows normally...absorb absorb pops up nice :D
