### ISSUE TITLE
SCAVENGING BUG

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2394]
![123](https://cloud.githubusercontent.com/assets/16375224/11932626/7ce9b3e8-a7ff-11e5-9431-93abfc7fc9b7.jpg)
Your skill is too low to use this item(craft).
Can someone check this and explain? Thanks guys.

**Comment by Evildoor** [comment]
What's your scavenging level?

**Comment by Stefanosgr18** [comment]
it was 21 when this happened...

**Comment by Evildoor** [comment]
I'm not sure, but isn't skill requirement 5*monster level = 25 in this case?

**Comment by ozarmidrashim** [comment]
This is incorrect as compared to live.

Any target should be scavengeable at any skill level. The player's skill level should act as a restriction on the level of the acquired item.

**Comment by Stefanosgr18** [comment]
So its a bug?...i tried exiting the game and relogged again...and killed some Nurse Dogs etc...and i could scavenge them normally...

**Comment by Stefanosgr18** [comment]
@ozarmidrashim https://www.youtube.com/watch?v=YJDr9Wex7lU

**Comment by Stefanosgr18** [comment]
Oops...occured again :(
![war crafting bug](https://cloud.githubusercontent.com/assets/16375224/11967142/3a2733f4-a909-11e5-841c-852154d0db25.jpg)
I cant scavenge him...the chat spams me : Your skill is too low to use this item
After that i killed the guy in the circle and scavenged him normally without any problem.

**Comment by Stefanosgr18** [comment]
![123](https://cloud.githubusercontent.com/assets/16375224/11994987/4da8cc6e-aa51-11e5-91cc-fa89d64a5af2.jpg)
There you go again...

**Comment by nalgol** [comment]
currently scavaging is based on the lvl of the mob compared to the your skill if the mob is to high you cannot scavange it this needs a rather big rewrite of the current system

**Comment by Evildoor** [comment]
Then it's on par with PQs and other stuff, so i'm closing this.
