### ISSUE TITLE
Pets are displayed as mailboxes on the minimap

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2398]
https://www.youtube.com/watch?v=on3SxfD9xlk&feature=youtu.be

It looks like this is only a bug on White Lions...i will upload another video to prove it.

**Comment by Evildoor** [comment]
All pets currently look like mailboxes, IIRC.

**Comment by Stefanosgr18** [comment]
Oh ok :P :) I jist noticed it only in Lions...Dont know...there you go :

**Comment by Evildoor** [comment]
I'm not sure if you should bother with making videos for trivial and/or easy to reproduce things like this one. But video may indeed be helpful if it is difficult to describe a problem with words/screenshots.

**Comment by Stefanosgr18** [comment]
Alright :+1:

**Comment by Evildoor** [comment]
Was fixed at some point.
