### ISSUE TITLE
Devastator shoulders Marauder - can not dye

### ISSUE THREAD

**Issue by Paninii** [WarEmu/WarBugs#2400]
Couldn't find it in the bugtracker.  Cant seem to dye the Devastator shoulders.
This is on Marauder the case at least. (Name marauder Tinteling)

I was able to dye my DoK devastator shoulders.

**Comment by Ryanfawkez** [comment]
Despite the item already being labeled as 'dye-able' in the wartool, the item model itself is still unsupported for dye application. Only way to fix this is to change the item's model.

**Comment by Paninii** [comment]
fixed it seems
