### ISSUE TITLE
Quest Contribution with Killblows

### ISSUE THREAD

**Issue by noisestorm** [WarEmu/WarBugs#2401]
Seems like occasionally people in party do not get any contrib for Quests that need Killblows. Stalker Set Quest (Hero Kill-step) or ratogre for the Event are two examples that happened today for no apparant reason. 4 People got contrib while one random player was missed out.

**Comment by Evildoor** [comment]
Maybe this is the same problem that sometimes prevents you from getting XP/Renown/etc in PVP, even though someone from your party or even yourself landed the deathblow...

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
