### ISSUE TITLE
assist macro with lots of delay

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#2402]
assist shows to work poorly in scenarios (experienced there) especially with fast target switching it has quite some delay (1-5 seconds).

perhaps implemenation could be looked at again?

**Comment by Tiggonos** [comment]
problem seems when target is out of range, assist bugs out then even and doesnt work for some time at all. AFAIK on live you always got the assistants target no matter if it was out of range for you or not. (easier handling anyway imho).

**Comment by Evildoor** [comment]
"on live you always got the assistants target no matter if it was out of range for you or not. " 
I agree. According to my memory, /assist was simply "select enemy target of your friendly target" and had nothing to do with range of any kind (dunno, unless maybe if that enemy target was too far away from you to select).

**Comment by Tiggonos** [comment]
After last patch assist has issues again. Could you please check the latest fix perhaps got depushed or something?

**Comment by taccr** [comment]
There's still something wrong with assist.

During my tests I could always acquire the target from assist if I instantly press the assist button after the target was selected by the other player. Only a few seconds later it stops working. So something seems to clear information about the target on the server side.

I also tried the new .assist command but that either does not work at all or I'm providing the wrong arguments. I used the other players name here.

**Comment by Shadowgurke** [comment]
Why is this low priority? This is a crucial feature for every premade and it works especially bad in any group that has a mix of ranged DPS and melee DPS. We are talking about up to 5s delay to assist on a target, which is about the TTK for your average target. I would appreciate it very much if this could be looked into

**Comment by Tiggonos** [comment]
after network patch it seems to work good now, perhaps that fixed the issue.

**Comment by Evildoor** [comment]
Closing then.

**Comment by taccr** [comment]
Problem still persist. The situation has become a lot better though.
After selecting a new target assist now works for roughly 20-50 seconds. Then it stops working until you select a new (same target doesn't work) target.

Please reopen.

Tested on dev.

**Comment by sioding** [comment]
Nothing new heard of that - so close until new rumors comes up
