### ISSUE TITLE
Quest Bug  Suspicious Character

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2403]
Name	                     Suspicious Character
Discovered By	             Seodica,Bretonnia
Zone Area	             Grey Lady Coaching Inn
Found in   Zone            Nordland

There are severak  Suspicious Characters in Grey Lady Coaching Inn...and you have to discover 15 of them...but i found out that if you continuously click on any of these characters it will start counting...1/15 2/15 etc(as many clicks as you did) 
Is this intended?(which i dont think so) Check it out guys :+1:

**Comment by noisestorm** [comment]
General Bug with all clickable Item/Person quests. I believe the emulator currently cannot set some sort of 'checked-flags' for already clicked items/persons, but im not sure here. Low priority anyway, since the basic quest functionality is given

**Comment by Evildoor** [comment]
#424
