### ISSUE TITLE
[Not implemented yet] NPC Barber Bug

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2405]
https://www.youtube.com/watch?v=RJViwvVKpPM

It doesnt work...i have over 1 Gold of money...if money might be the issue.Can you confirm/check it?

**Comment by noisestorm** [comment]
Doesnt work because its not implemented yet.

**Comment by Stefanosgr18** [comment]
Ok cool...priorities first but we would like to see these things little by little working again :)

**Comment by ozarmidrashim** [comment]
Congratulations. Let me know when you're a paying subscriber.

Oh.

**Comment by Stefanosgr18** [comment]
Funny thing is that i want to help the project but you dont accept :( :-1:

**Comment by Evildoor** [comment]
Duplicate of #1403, so Azarael was right closing this.

**Comment by Stefanosgr18** [comment]
@Evildoor Thank you ! Good to know!!
