### ISSUE TITLE
t3 Empire posterns not working

### ISSUE THREAD

**Issue by Tidybraveguinea** [WarEmu/WarBugs#2408]
They were working fine, than something happened... And they stopped. There was no server restart, happened in the middle of rvr.

**Comment by Soulwhisper** [comment]
Pick Lock doesnt work either for WH on all doors.

**Comment by Soulwhisper** [comment]
Reporting here after 6th of March patch.Postern doors still buggy in Passwatch Castle.

**Comment by Evildoor** [comment]
Changelog from 21.03.2016 (a bit late :P ).

[Keeps]

- Fixed all postern doors.
