### ISSUE TITLE
I can not go to your character

### ISSUE THREAD

**Issue by Serg2015** [WarEmu/WarBugs#2409]
I can not go to your character elf witch. All the other characters from the first time I go . Elven Witch starts to boot and then throws her characters to choose from .

**Comment by Evildoor** [comment]
Have you tried to use /stuck during character loading?

**Comment by Serg2015** [comment]
Yes. Did not help.




>Понедельник, 21 декабря 2015, 23:25 -08:00 от Evildoor <notifications@github.com>:
>
>Have you tried to use /stuck during character loading?
>—
>Reply to this email directly or  view it on GitHub .


С уважением, 
Василенко Сергей.

**Comment by Evildoor** [comment]
Check #1963, maybe it will help.

**Comment by Evildoor** [comment]
Closing per rules of the bugtracker.
