### ISSUE TITLE
Lair Boss Absent, Lair of the Shambler T3 BFP

### ISSUE THREAD

**Issue by Simmox** [WarEmu/WarBugs#2410]
i dont know if you want to know about these things but

the lair of the shambler in black fire pass itsnt there
unlike the vampire lord in badlands is
so,in case you dont know about him

http://warhammeronline.wikia.com/wiki/Lair_of_the_Shambler

http://warhammeronline.wikia.com/wiki/Ulnac_the_Shambler

drops the shambling helms

merry xmas

**Comment by Evildoor** [comment]
#1999
