### ISSUE TITLE
stalker not offered

### ISSUE THREAD

**Issue by Drilon01** [WarEmu/WarBugs#2411]
All Stalker quests are not offered to me. I hit lvl 31 and now i dont have the chance to do the quests pls remove the lvl threshold if there is one.

**Comment by Evildoor** [comment]
Level threshold is not the problem here (unless it was broken by mistake in some of the recent patches). To me this seems more like a particular case of #1589.

**Comment by Meralors** [comment]
Quest level shoudl be working fine ( its a level 24 quest ).
Did you try to relog? How many quests do you have in your book?

**Comment by Drilon01** [comment]
i have maybe 9 quests in my book not much. i reloged many times but its not working. when i go to Erich Ruher in highpass there is no quest offer. the same in Avelorn. i remember i had to many quests and i abandon a lot of them and i abandoned the Erich Ruher quest by accident since then he dont offer me the quest again.

**Comment by Tesq** [comment]
some days ago (2) all my quest from my magus got wipe and i also cannot get the second part of the new rvr event quest, waiting some times to see if it fix itself with a restart or something similar but the issues may be connected to a general quest bigger  problem

**Comment by Drilon01** [comment]
okay then it isnt just me. it have to be a problem somewhere

**Comment by genisaurus** [comment]
Problem with player account, not the server. PM a GM for resolution
