### ISSUE TITLE
Nordenwatch Scenario NPC clothing bug

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2412]
![war 2015-12-22 10-47-04-33](https://cloud.githubusercontent.com/assets/16375224/11951605/ecb0796e-a89a-11e5-9e7b-a8eadd0517c5.jpg)
![war 2015-12-22 10-46-59-89](https://cloud.githubusercontent.com/assets/16375224/11951606/ece4d682-a89a-11e5-8895-2a9178ee8133.jpg)

Is this intended? For him to be naked?

**Comment by Evildoor** [comment]
particular case of #742
