### ISSUE TITLE
[quest] the exalted one, chaos c8

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#2413]
No way to hand in the quest, should be from chest but merely completes, no drop off point. Quest giver doesnt do anything.

**Comment by Evildoor** [comment]
#790? Or this is different?

**Comment by Torquemadra** [comment]
The hand in location is actually Vhorek Bloodfist in the camp, it is functional, just odd.

**Comment by Meralors** [comment]
Quest is working, I just added info in tooltip so you know where to turn in.
