### ISSUE TITLE
Missing Emblem weapon.

### ISSUE THREAD

**Issue by KOTBS** [WarEmu/WarBugs#2414]
Missing Emblem weapon.

se screenshot.
![trevlig_002](https://cloud.githubusercontent.com/assets/16400629/11954583/18501cfa-a8aa-11e5-8f29-7976fbf72bf1.jpg)

**Comment by Meralors** [comment]
Hmm I think I saw that before, this name is shared with a quest item. I'll check whats wrong

**Comment by Meralors** [comment]
Ok its fixed, the vendor will no longer sell the quest item. You can now buy a correct weapon.
Fixed next patch.
