### ISSUE TITLE
Terrain BUG

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2419]
I dont know if this can be fixed asap but you cant get past through these rocks...there is something like a WALL blocking the way...and you go on them you somehow stuck in there and fall in graphics or die after 8-10 seconds.
![warhammer return of reckoning terrain bug](https://cloud.githubusercontent.com/assets/16375224/11958321/ee3e858e-a8cf-11e5-9834-f25b011bf40f.jpg)

Check the video to see better:

https://www.youtube.com/watch?v=a4a3qZy57aI&feature=youtu.be

**Comment by Ryanfawkez** [comment]
That's to prevent Destruction from entering the Order warcamp through the PvE area. I have to admit, it's really buggy and not optimally placed at all, but you can still exit the Warcamp by following the paths.

**Comment by Stefanosgr18** [comment]
Yeah i agree with you...but its a bug...so i reported it.And yeah sometimes its confy to cut this way out...furthermore its unrealistic...too much.They should put a couple of guards above the rocks...so if an enemy or NPC enemy aproaches they will go and 1hit kill them :P Nevermind its a bug so i had to report it.
