### ISSUE TITLE
Issue with 7 players in an SC

### ISSUE THREAD

**Issue by Gobtar** [WarEmu/WarBugs#2420]
Issue when there is only 7 players on the same side, the one player gets left and is forced to be a solo player and thus does not benefit from kills.

![hekatrix_005](https://cloud.githubusercontent.com/assets/7888608/11958404/1860aaae-a89e-11e5-9473-2899204813e9.jpg)
![hekatrix](https://cloud.githubusercontent.com/assets/7888608/11958436/4b7b97b4-a89e-11e5-9d9f-9e106b2f871f.JPG)

**Comment by Stefanosgr18** [comment]
Yes i noticed that too...maybe its a random bug or something...it happened to me twice so far

**Comment by Tesq** [comment]
maybe is just a visual bug for rooster

**Comment by Torquemadra** [comment]
also had this when 7th

**Comment by Stefanosgr18** [comment]
Actually its not random...it happends in almost every scenario

**Comment by ozarmidrashim** [comment]
Is fixed on live.
