### ISSUE TITLE
potion bug -no shared CD [emulator][itiems]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#2421]
differents potions itiems (of same kind) don't share the same CD 

exemple
potion 1 heal for 1100
potion 2 heal for 900

i am able to use boht in chain as each one of theme have a separate 5 min CD.

UPDATE:

the potions which i was able to use togheter were

-Slaughterer's Draught
-Soldier's Healing Draught

**Comment by Luth-RoR** [comment]
Crafting potions and "pvp potions" always had separate cooldowns. Same with AP potions from medallion vendors and crafted ones.
