### ISSUE TITLE
kotbs morale "Emperor's Champion" healing effect is missing/the morale not spending morale resource

### ISSUE THREAD

**Issue by Tidybraveguinea** [WarEmu/WarBugs#2422]
It seems to add all stats correctly including wounds, but the healing part is missing. On live all "increase wounds" effects including bork's "da toughest!", bolster (when entering zone with bolster from pve zone) and kotbs "emperor's champion" and magus "aegis of orange fire" were acting like self-heal in addition to wounds increasing.
EDITED: It also doesn't spend morale when you use it.

**Comment by Tidybraveguinea** [comment]
still not healing

**Comment by Evildoor** [comment]
Maybe fix was not applied yet? @ozarmidrashim ?

**Comment by Stefanosgr18** [comment]
@ozarmidrashim Fixed?

**Comment by Tidybraveguinea** [comment]
Nope, still just increasing of hp pool :(

**Comment by Stefanosgr18** [comment]
..:(

**Comment by Tidybraveguinea** [comment]
all ok, healing now
