### ISSUE TITLE
Khaine's Refreshment not healing the caster

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#2423]
Should also heal the caster every tick and not just people around him.

Most likely the same issue with Martyr's Blessing.

**Comment by Landaren** [comment]
I think it was made to heal 6 people at random, meaning it may or may not heal you? That was how it was designed on live the last time I played at least.

**Comment by taccr** [comment]
Can't confirm or deny if there was a cap for the aoe heal part.
However it was definitely healing the dok himself.

Currently it does not even heal the caster if no other targets are in range.
