### ISSUE TITLE
Influence reward at main Order's WarCamp dont work.

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2426]
![war 2015-12-22 19-57-01-05](https://cloud.githubusercontent.com/assets/16375224/11962147/44f7e788-a8e6-11e5-918b-e4e926ff3c74.jpg)

It doesnt work in Grey Lady Coaching Inn too.
Sorry i dont know if this is mentioned before...but on previous Grimmenhagen Village i could take my influence rewards.

**Comment by Evildoor** [comment]
You need to unlock the ToK page related to this chapter.

**Comment by Stefanosgr18** [comment]
And how do i do that? :( Please help and close this if it is not a bug... @Evildoor

**Comment by Evildoor** [comment]
You have to visit a certain areas related to chapters, usually PQ areas (PVE) or RVR zone (PVP). These are different between chapters and we don't know how to fix them if they are wrong (#1205 still not fixed, for example).

**Comment by Stefanosgr18** [comment]
Oh i see...but my bar filled up fully and i still cant get my reward(other races told me that they can take their rewards normally)so maybe its a specific bug for Archmage...why do you close this? Its a bug...not related to the #1205...

**Comment by Evildoor** [comment]
You can get influence regardless of ToK page, but you cannot obtain items without it. I have no reason to think it was different on live. Wrong areas for unlocking these pages can be the problem and should be fixed, but we can't do this now.

**Comment by Stefanosgr18** [comment]
Oh ok than.What is ToK page?

**Comment by Evildoor** [comment]
Tome of Knowledge page.

**Comment by Stefanosgr18** [comment]
Oh...i see lol ...thanks anyway

**Comment by Stefanosgr18** [comment]
Ahh...i see whats the problem....the BAR doesnt show up correctly for each chapter...but inside the ToK you can see exactly how much Influence you have for each chapter...Am i right?!

**Comment by Evildoor** [comment]
Yes.

**Comment by Stefanosgr18** [comment]
:D Is this on any other ticket? I know that you know it but its good to write them down and put on some labels.

**Comment by Evildoor** [comment]
What "this"? I already said that "You can get influence regardless of ToK page, but you cannot obtain items without it." does not seems like a bug to me.

**Comment by Stefanosgr18** [comment]
No i mean the bar(BUG) thing....that doesnt show up correctly in which chapter you are while you move from 1 area to another(most often from one PQ to another PQ )

**Comment by Evildoor** [comment]
#1687

**Comment by Stefanosgr18** [comment]
Ok nice...i cant do that everytime...to search if someone mentioned this bug...so i post it...i hope that this is not a problem for you :/

**Comment by Evildoor** [comment]
What's the problem? I take bug reporting seriously and looked through most of the reports, 2.5k is not that much (ok, it was 1.5k when i started). And i did all this BEFORE i became a moderator here, when i was simple player. Only because i did not wanted to post duplicates.
