### ISSUE TITLE
"Item move Failed:" bug... 

### ISSUE THREAD

**Issue by wonderbloob** [WarEmu/WarBugs#2427]
recently ive been trying to lvl my scavenging and talisman making. about a week ago, the crafting section of my inventory bag began to stack many differently named crafting components onto eachother(they all stacked in one inventory square and flashed randomly). my chat window CONSTANTLY spams this error: "Item move failed: attempted to move 20 of the (item) while only having (x)" . because this error is constantly spammimg, it lags my game to almost a halt.

```
 Also (im sure these problems are connected) the talisman crafting window bugs out most of the time i try to craft. if im lucky, i can get 2 tallys done before my crafting items start stacking together and the talisman making program will bug out. 
```

let me know if theres any info i forgot to give you! thanks for all the hard work!!!
-wonderbloob

**Comment by nalgol** [comment]
this is not easy the client auto sorts some of the inventory this somebugs with the itemhandler server side

**Comment by wonderbloob** [comment]
Thanks for the response! !!
