### ISSUE TITLE
Friend List Stuck removing people BUG

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2428]
![war 2015-12-22 21-11-01-35](https://cloud.githubusercontent.com/assets/16375224/11963567/9615304e-a8f0-11e5-9509-e68fd17ccadd.jpg)
![war 2015-12-22 21-09-56-65](https://cloud.githubusercontent.com/assets/16375224/11963569/964b9012-a8f0-11e5-9971-6859ec359a49.jpg)
1st) There is no remove option with right click on a friend on friend list (I think there was an option on LIVE)
2nd)Even if you remove them with the "console" by opening (search more...)**as shown in the picture**
they still stay there on the friend list.

**Comment by Evildoor** [comment]
1) Interface shows no such option = was the same on live.
2) Was fixed at some point.
