### ISSUE TITLE
MAILBOX Bug

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#2429]
![war 2015-12-22 21-26-10-85](https://cloud.githubusercontent.com/assets/16375224/11963918/b8c49f2e-a8f2-11e5-8c2b-4eede73bfea8.jpg)
*********************_ATTENTION**_*********************
I noticed that it is happening only with my Bright Wizard!
I open the message i take the items and after that i click delete and it says that items are still attached(false) i already took them.But it may confuse a lot of people...if it is money and they dont have their backpack open while they are taking the money to watch carefully if the money transfered to their backpack.If it is an item you can easily check if the item transfered to you. I tried closing mailbox and reopen it and delete the message but keeps saying : "items are still attached"

**Comment by Stefanosgr18** [comment]
UPDATE : NOT HAPPENING ONLY WITH BW...it happens with all careers.

**Comment by Natherul** [comment]
Should have been fixed with the patch from yesterday
