### ISSUE TITLE
Event's rat cloak bugged out on female AMs

### ISSUE THREAD

**Issue by Morksezstop** [WarEmu/WarBugs#2430]
well the new event's cloack bugg out when using it on female AM

<a href='http://postimage.org/' target='_blank'><img src='http://s22.postimg.org/ee8aen09d/image.jpg' border='0' alt="1" /></a><br /><a target='_blank' href='http://postimage.org/app.php'>how to screenshot on windows 7</a><br /><br />

<a href='http://postimage.org/' target='_blank'><img src='http://s8.postimg.org/n6pxvfq51/image.jpg' border='0' alt="2" /></a><br /><a target='_blank' href='http://postimage.org/'>image free hosting</a><br /><br />

<a href='http://postimage.org/' target='_blank'><img src='http://s1.postimg.org/izvz6v7lb/image.jpg' border='0' alt="3" /></a><br /><a target='_blank' href='http://postimage.org/'>free photo hosting</a><br /><br />

on side note you could make the cloack for AMs like sov cloack much more wider. Frankly on tall and tin characters such wide cloacks looks much better. And since the rat back is signiture for RoR you could make it wider for AMs \may be WL?, BGs?, Doks?\ so even on tin female characters will look good and ppl will use it.

**Comment by Stefanosgr18** [comment]
Archmage seems to get more and more bugs.

**Comment by NorKalli** [comment]
Can we delete this? Not much we can do

**Comment by sioding** [comment]
Since we can not see any screenshots cause they aren´t hostetd anymore - close
