### ISSUE TITLE
STUCK icons BUG and NPC healer not working.

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2432]
![1322](https://cloud.githubusercontent.com/assets/16375224/11966657/c3407f14-a905-11e5-8daf-c09ff8c0d8e5.jpg)
Just some interface stuck icons.And in addition NPC healer not working(Obviously you already know that but i mentioned it because i remembered on LIVE when these stucks remained after you died in PVE you should go to a healer to remove them :)

**Comment by Torquemadra** [comment]
there is no more death debuff so npc healers are out of business afaik

**Comment by Stefanosgr18** [comment]
Yes maybe they will rework and bring back death debuffs only on PVE though. Stuck icons might confuse you though while joining Scenario or PVP - RVR battles.

**Comment by Evildoor** [comment]
Debuffs not going away - #1435 and some others. Healer NPC are not implemented, as @Torquemadra said.
