### ISSUE TITLE
WRONG stats in party info-icons STUCK BUG

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2433]
![1234](https://cloud.githubusercontent.com/assets/16375224/11966678/e0f03982-a905-11e5-9491-973b7620eb88.jpg)
Actually i have to admit...this is annoying and really bad...because it causes confusion/chaos to healers...i didnt know who to heal first...! :-1:

**Comment by Stefanosgr18** [comment]
![123](https://cloud.githubusercontent.com/assets/16375224/11967049/8c818eb6-a908-11e5-9ca3-1bfcdecff8a6.jpg)

**Comment by Stefanosgr18** [comment]
![123456](https://cloud.githubusercontent.com/assets/16375224/11967064/a5bc6d6a-a908-11e5-8fdd-3651635d5fa0.jpg)

**Comment by Morksezstop** [comment]
i am not 100% sure but i think there is some bug involved with absorb shields. It seems that the frames calculate absorbs as damage and visualy lower the character hp while in reality the character is at full hp cos all the damage is absorbed.
AM shield m1 is pretty decent for testing that but need more time to be certain about it

**Comment by Stefanosgr18** [comment]
Yes...i noticed that too...thanks for reminding it...! Check it out and report back

**Comment by Stefanosgr18** [comment]
In addition: If u late to join scenario and try to join a party...it doesnt show up on interface and sometimes you join a party and kicks you out automatically.Most important is when people join later scenario not in the beggining and they try to join a party...it doesnt show up on left screen interface...which is kinda annoying for healers trying to click on them.They can kinda "ghost" join party and get Xp and Rp in the end but we cant see them on left side.

**Comment by Evildoor** [comment]
#715
#947
And some more.
