### ISSUE TITLE
Scenario Parties are bugged.

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2436]
If u late to join scenario and try to join a party...it doesnt show up on interface and sometimes you join a party and kicks you out automatically.Most important is when people join later scenario not in the beggining and they try to join a party...it doesnt show up on left screen interface...which is kinda annoying for healers trying to click on them.They can kinda "ghost" join party and get Xp and Rp in the end but we cant see them on left side.

**Comment by Evildoor** [comment]
#1138 and #1505. And i've already linked them to you, and you looked through them.
