### ISSUE TITLE
Potent Stimulating Draught

### ISSUE THREAD

**Issue by Squea** [WarEmu/WarBugs#2437]
Level 25 Crit AP potion, like the level 30 version, is not usable.  Not sure if this applies to all critical ap pots.  Seems to be the case.  Level 32 Charging Draught is usable, level 32 Potent Charging Draught is not usable.

**Comment by magicthighs** [comment]
Been meaning to file a bug report on this but keep forgetting, none of the blue AP pots seem to be usable.

**Comment by ropuch** [comment]
Not sure if it helps, but:
32 blue AP pot: [Potent Charging Draught] {ID 3000462}
35 blue AP pot: [Potent Invigoration Draught] {ID 3000463}

**Comment by kaey** [comment]
Potent rejuvenating potion (lvl38 AP) is unusable as well.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/8719
