### ISSUE TITLE
NPC naked/clothing bug 

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2438]
This girl is naughty.
![war 2015-12-23 02-54-31-30](https://cloud.githubusercontent.com/assets/16375224/11969328/970c051a-a920-11e5-816d-3e9dd6bfc63c.jpg)

**Comment by noisestorm** [comment]
Not sure if this is entirely client sided, but this occurs pretty often. Nothing to worry about

**Comment by Evildoor** [comment]
And another particular case of #742. Do not report such things. Only report naked NPCs if they are really naked, not bugged out like in #742.
