### ISSUE TITLE
emperor's champion doesn't heal

### ISSUE THREAD

**Issue by Tidybraveguinea** [WarEmu/WarBugs#2441]
On this video you can clearly see that ec morale not only increases amount of hp overall but heals you by the same amount. 2:04
https://www.youtube.com/watch?v=dGG2-mtewoU&index=2&list=LLAKsIdslo7cm9dFMqVTDmLw

**Comment by Evildoor** [comment]
No need to create a separate ticket for this. Post it in #2422, if you believe it is needed (since @ozarmidrashim closed it, i believe it was fixed).
