### ISSUE TITLE
Choppa's ability Wot's Da Rush abuse

### ISSUE THREAD

**Issue by Nocha** [WarEmu/WarBugs#2442]
Hi support. 
I have character - this is 32lwl slayer 
Yesterday i die in one sec from choppa Scumbag when our wb atack keep
His ability Wot's Da Rush do more multipple damage in one sec + ability Hurtins Time.
I have proof, you can check link http://postimg.org/image/5ehf676wj/ 
how you can see his abilities work more times in 1 sec. It is global cooldawn hack or ability abuse.

**Comment by Evildoor** [comment]
It's a bug, which happened before to different abilities.

**Comment by ozarmidrashim** [comment]
Bug with Tantrum. Should be fixed.
