### ISSUE TITLE
PUBLIC QUEST Raven Host Vanguard

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2445]
In the final stage GIANTS body dissapears when we kill him...everytime.

**Comment by Meralors** [comment]
PQ are not implemented yet. So anything related to them can bug

**Comment by Stefanosgr18** [comment]
Yes i know i just mentioned it...so when the time comes..:) I heard the you will focus more on PVE to fix PQs and Dungeons in the future and then release T4.
