### ISSUE TITLE
Winds of insanity not interrupted by taunt

### ISSUE THREAD

**Issue by hoppolek** [WarEmu/WarBugs#2446]
I've played a few scenarios and my taunt doesn't interrupt zealot's "winds of insanity".

**Comment by ozarmidrashim** [comment]
WoS is implemented as a toggle and not a channel.

**Comment by RoR-Zomega** [comment]
FWIW I can confirm this is working as intented. Old video from AoR showing Wind of Insanity being a toggle and the player being able to cast other stuff while it was still active: https://www.youtube.com/watch?v=CLno108Cjjg
