### ISSUE TITLE
CHAPTER 2 influence low items

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2447]
![123](https://cloud.githubusercontent.com/assets/16375224/11982475/2f618676-a9b4-11e5-8df3-c45ea0119f08.jpg)

LOL is this a bug? +1 strength??  Thats too low...i remember that in LIVE the last items were stronger than +1 POWER for sure

**Comment by Stefanosgr18** [comment]
![123](https://cloud.githubusercontent.com/assets/16375224/11992376/836a224a-aa2d-11e5-9db8-e2cdf0e2ad2e.jpg)
On archmage its fine...it seems that it only happens with Slayer...dont know though.I think there is unbalance on items.

**Comment by Ryanfawkez** [comment]
If you can find the original stats for the items through search through Google for them, I'd be happy to fix any item's stats that are currently obtainable.

**Comment by Stefanosgr18** [comment]
@Ryanfawkez http://warhammeronline.wikia.com/wiki/Warrior_Priest_influence_rewards
Go to this link...it only shows for Warrior Priest but you can imagine that other careers have the same stats.Can you fix that? E.g for slayer insted of +1 strength put +4 or +5.Armor is fine i guess.Keep it balanced

**Comment by Ryanfawkez** [comment]
Could take that as a base, yeah. Easy enough for T1 chapter 1 to 4 gears, it becomes more complicated in T2 and T3.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
