### ISSUE TITLE
Apothecary Dye bug

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2448]
![1234](https://cloud.githubusercontent.com/assets/16375224/11982899/f0384922-a9b7-11e5-8147-6d7567e62320.jpg)
Cant use that to make dye...

**Comment by Stefanosgr18** [comment]
Am i doing something wrong? I cultivated a plant and extracted this ingredient.

**Comment by Meralors** [comment]
This is not a bug, you are not using the right component. To craft a dye you need a "Wooden mortar and pestle" and "alum root extract", they can be both bought to npc

**Comment by Stefanosgr18** [comment]
Oh ok so i was doing it wrong...! Thanks...close it :P

**Comment by Evildoor** [comment]
FYI - you can close your own tickets.

**Comment by Stefanosgr18** [comment]
How?

**Comment by Evildoor** [comment]
"Close issue" button near "Comment" button.

**Comment by Stefanosgr18** [comment]
ty
