### ISSUE TITLE
Unusual rewards in SCs

### ISSUE THREAD

**Issue by Gobtar** [WarEmu/WarBugs#2452]
Just played in a scenario, if I killed someone I got 0 RR/XP from them however if they killed me, I got the rewards as if I solo killed them.

![hekatrix_012](https://cloud.githubusercontent.com/assets/7888608/11986219/7d3dfae8-a9a3-11e5-8c7a-2bc9cc27e0cf.jpg)

**Comment by Tidybraveguinea** [comment]
And I got 9k renown on a sc today while all others got 1k-2k. I was alone in a group.
Probably fits into "unusual sc rewards" ticket.

**Comment by magter3001** [comment]
Our guild premades for some reason kept getting next to nothing in renown even though we were doing all the killing. Later on when I queued solo, I seemed to get the highest reward possible each scenario. 

Hope that helps. :)

**Comment by vove-RoR** [comment]
This also might be only visual. Sometimes on the scoreboard I see totally different information comparing with what other player (sitting next to me) sees.

**Comment by Luth-RoR** [comment]
Was an issue for a while; should be fixed now.
