### ISSUE TITLE
[ability][witch elf] elixier of the insane power

### ISSUE THREAD

**Issue by diablight** [WarEmu/WarBugs#2453]
Elixier of the insane power triggers a 60sec cooldown for elixier of the cauldron. Contrary the elixier of the cauldron does not trigger a cooldown for elixier of the insane power. I can not remember which one was right on live server though.

**Comment by Lileldys** [comment]
Using one elixir made all the others go on cooldown, no matter which is used.

**Comment by ozarmidrashim** [comment]
Also fixed on WH.
