### ISSUE TITLE
[quest] - Sanctify 

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#2456]
This quest Order in Highpass.  I can't complete it so far 2 toons tried.

I can't complete the second task Behorst Black Heart.  
I kill The Keeper of the Shrine and check Zumwalds supplies..  
Afaik this isn't working properly, I think killing The Keeper of the Shrine should give a Heart you then interact with the Supply chest there?

thx

**Comment by Meralors** [comment]
You actualy have to kill "Shrinekeeper Behorst" to get Behorst heart (sound fair :p ). He's a magus NPC on the way to shrine.
