### ISSUE TITLE
[Public quest] Fortress of Korhandir

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#2457]
Fortress of Korhandir public quest is not counting Vanquishers towards the total meaning the PQ never hits stage 2 and wont reset to stage 1 for inf farming untill server reset.

Stage 1 should be -
kill 70 ellyrian great riders - working
kill 35 ellyrian vindicators - working
kill 20 ellyrian vanquishers - not working

**Comment by Meralors** [comment]
We can't fix PQ yet, hopefully we will be able to soon enough :)
