### ISSUE TITLE
RR40 cap is now unfortunately broken

### ISSUE THREAD

**Issue by mursie** [WarEmu/WarBugs#2459]
I'm 6 renown away from rr40 and can't actually get rr40 because you apparently have to get exactly 6 renown for it to ding.  This was the case before, only previously, the cap was actually 41 so players would ding 40 and basically gain enough renown to be rr41 but it wouldnt ding 41.  Now - im stuck at rr39 unable to ding rr40.

![plinkie_001](https://cloud.githubusercontent.com/assets/15176111/11989155/50d5784e-a9be-11e5-8894-a2848b3757f2.jpg)

**Comment by Tidybraveguinea** [comment]
Try to relog.

**Comment by mursie** [comment]
This did fix the issue - weird, but thank you
