### ISSUE TITLE
MAP BUG

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2460]
After travelling from Altdorf to Nordland and opened map...it stuck BLACK in most areas
![123](https://cloud.githubusercontent.com/assets/16375224/11992282/84da01c8-aa2c-11e5-8091-ec99df0775c7.jpg)

**Comment by magter3001** [comment]
I remember that bug on Live... good times :P

**Comment by Stefanosgr18** [comment]
Hahhaah yeah...trye

**Comment by Evildoor** [comment]
Interface problem in client.
