### ISSUE TITLE
[quest] an inconvenient truce

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#2461]
Marker for mission in wrong location, at PQ  as opposed to Elyr gatehouse

After killing relevant mobs unable to hand in mission to Harogath Darkstrider who is in the right place but the gates (which opened on live) are not able to be targeted, clicked or opened.

**Comment by Meralors** [comment]
Fixed Zone Marker.
Also fixed doors, they now open and you can talk to npc.
