### ISSUE TITLE
Spiked Squig is not giving 5% Crit

### ISSUE THREAD

**Issue by PorkandKite** [WarEmu/WarBugs#2462]
we had a problem with this before, it was fixed but now it seems to not give the crit anymore when i use .getstats

**Comment by Evildoor** [comment]
.getstats screens with/without?

**Comment by PorkandKite** [comment]
I used .getstats with and without my spiked pet active and my crit did not change, which means it isnt giving the 5% crit

**Comment by Evildoor** [comment]
Tested, it's #2064 again.
