### ISSUE TITLE
HELM visual BUG

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2466]
![123](https://cloud.githubusercontent.com/assets/16375224/11993384/fd3c685c-aa38-11e5-9d3a-0f3e611da10b.jpg)
Helm doesnt show up visually even in withing 'P'.

**Comment by Meralors** [comment]
Item is showing on dev, are you sure to select "show item" next to the helm icon?

**Comment by Stefanosgr18** [comment]
Oh thanks you have to select show item...
