### ISSUE TITLE
Cultivating

### ISSUE THREAD

**Issue by syrka82** [WarEmu/WarBugs#2469]
If you have a critical success or special moment with lvl200 seeds, the whole cultivating bugs. Only relogging fix it.

sry, critical success or special moment don't have a affect, its bugs randomly

**Comment by Evildoor** [comment]
What exactly happens?

**Comment by syrka82** [comment]
while harvesting, it bugs the whole cultivating.
 the first harvest work, but then nothing else. i can't harvest the other plant or plant new one's. Only a relog fix it.

**Comment by Evildoor** [comment]
#1721?

**Comment by syrka82** [comment]
ok, i didn't find this one, sry for double post it.
