### ISSUE TITLE
QUEST low level item reward BUG + LOW XP reward

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2471]
![123](https://cloud.githubusercontent.com/assets/16375224/11994046/1c6353aa-aa41-11e5-9008-3e1c0e919b79.jpg)
Highi level quests low level item rewards.

**Comment by Stefanosgr18** [comment]
![123](https://cloud.githubusercontent.com/assets/16375224/11994451/3d8a7288-aa47-11e5-9c41-939c37e88312.jpg)
Here too...in many quests they give very Under Power items as reward in accordance of the item level.

**Comment by noisestorm** [comment]
https://github.com/WarEmu/WarBugs/issues/2473

**Comment by Stefanosgr18** [comment]
@noisestorm 
http://warhammeronline.wikia.com/wiki/Promise_of_Battle_V
Only Promise of Battle V gives an item on LIVE.And its a potion : http://warhammeronline.wikia.com/wiki/Lasting_Potion_of_Insight

Promise of battle quests :
Promise of Battle I : gives 2092 XP
Promise of Battle II : gives 2461 XP
Promise of Battle III : gives 2580 XP
Promise of Battle IV : gives 2063 XP
Promise of Battle V : gives  2063XP and Item: Lasting Potion of Insight or Career Equipment(potion)

if you could fix them it would be great.Please re-open this ticket.

**Comment by Stefanosgr18** [comment]
http://www.warbits.com/gold-quests-493-Promise-of-Battle.html

Check this one please...it shows thte rewards for every race! It would be awesome if you apply it exactly as it was!

**Comment by DanaBloodkiss** [comment]
Added the correct EXP amount and the correct rewards!Nice report!Thanks :)
