### ISSUE TITLE
Renown points bug/hack

### ISSUE THREAD

**Issue by magnetical** [WarEmu/WarBugs#2472]
Did a scenario, destruction lost hard nobody had more than 1k renown, suddenly at the end a healer had 7,2k having the stats in the picture.Is it a bug or is he a hacker?
![img_24122015_135806](https://cloud.githubusercontent.com/assets/14090937/11994440/22215872-aa47-11e5-83cf-52af3c77ddf2.png)

**Comment by Evildoor** [comment]
#2395
