### ISSUE TITLE
Under Power items in accordance of ITEM LEVEL 

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2473]
![1234](https://cloud.githubusercontent.com/assets/16375224/11994460/7a5a0a2a-aa47-11e5-97b1-c890ecd21b9c.jpg)

**Comment by noisestorm** [comment]
Pls do NOT post something like this. Item rarity also is essential to the stats, not just the level.

**Comment by Stefanosgr18** [comment]
![13](https://cloud.githubusercontent.com/assets/16375224/11994799/97b4e1d4-aa4d-11e5-987e-f090d8ee98bc.jpg)
