### ISSUE TITLE
Promise of Battle QUESTS

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2478]
Promise of Battle quests are giving too low Xp 900-1000...they suppose to give 2000+...is this intended?

**Comment by Evildoor** [comment]
Proof of 2000?

**Comment by Stefanosgr18** [comment]
http://warhammeronline.wikia.com/wiki/Promise_of_Battle_I
http://warhammeronline.wikia.com/wiki/Promise_of_Battle_II
http://warhammeronline.wikia.com/wiki/Promise_of_Battle_I

**Comment by Stefanosgr18** [comment]
Check rewards...and they dont even give items as rewards...only high XP

**Comment by Stefanosgr18** [comment]
Refer to : #2471
