### ISSUE TITLE
Talisman Slotting Issues

### ISSUE THREAD

**Issue by noisestorm** [WarEmu/WarBugs#2480]
2 Issues:
*1: Slotting 2 talis of the same COLOR -not rarity -  (gem being Blue for str and tougness for example)
into the same item does not work.
*2: Putting up a Tali in a slot where already an Talisman was slotted before and taking the newer one out again, completely removes the old slotted one from the item, even though you did not accept any form of item change yet.

**Comment by Stefanosgr18** [comment]
LOL i noticed that(*2) but i didnt posted because i though that it would already have been mentioned.

**Comment by Tiggonos** [comment]
https://github.com/WarEmu/WarBugs/issues/1119

**Comment by nalgol** [comment]
both issues will be fixed next patch

**Comment by Evildoor** [comment]
1st issue is back according to #4206

**Comment by nalgol** [comment]
just slotted 2 talismans into a greatweapon works just fine ???
i need the weapon name and the talisman names you tryed to add

**Comment by Evildoor** [comment]
@Kouba85

**Comment by Kouba85** [comment]
weapon is Titan´s Bigloppa of Brutality and tallismans are +8 strengh weak talisman of contender
and second weapon wich i tryed was Big choppa of conquest the same talismans.

**Comment by Kouba85** [comment]
btw i tryed to add as second talisman Lesser talisman of challenger and this doesnt work too.

**Comment by nalgol** [comment]
you cannot slot 2 talismans of the same type aka no 2 talis with strength

**Comment by Kouba85** [comment]
Oh thats bad.
