### ISSUE TITLE
[quest] no end of danger

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#2482]
This quest is not counting all the hostile creatures that it should be.

Tundratusk
Shiftpaw Wolf
Shiftclaw Wolf
Moltclaw Eagle

As per the quest wording (and memory) these animals should count towards the quest..  
If not it's not a big deal at all, just a minor issue.

**Comment by Ryanfawkez** [comment]
Original quest description is as follows; 
http://www.warbits.com/gold-quests-1525-No-End-of-Danger.html

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
