### ISSUE TITLE
Scenario Renown Calculations

### ISSUE THREAD

**Issue by Nocha** [WarEmu/WarBugs#2484]
Hi support.
Very often i see that renown on scenarios distributed wrong.
Example 1 : http://postimg.org/image/6xccrl6o5/ 
we win scenario 500 vs 0 . My party ( i am Uri slayer) do very more destros deathblow and what we watch in the end. Its lol
Example 2: http://postimg.org/image/xkvnievvz/ 
again we win scenario. My party do 58 deathblows and what we see again: only 1900 renown vs 5300 renow from destro who die 8/0?

What's the secret?

**Comment by Stefanosgr18** [comment]
Yes there is some unalance...as i can see...better they mods should explain us whats going on. :)

**Comment by noisestorm** [comment]
Stefano can you pls stop making nonsensical additions to every other post? This is a Bugtracker and not a Forum to comment on everything. I'd appreciate that as well as the Coders who have to read through the tracker. And if not i'll take the freedom to remove superfluous posts of yours in the future.

@topic there is most likely some Bug with the new Group-Size-Healrenown fix that we saw a few days back. In any case thats something for @ozarmidrashim to look at

**Comment by Nocha** [comment]
I have commentary: if u have full party u gain a little bit renown and if you join solo u gain renown normally

**Comment by Nocha** [comment]
this example illustrated renown calcalating : http://postimg.org/image/5d4qaq0bb/ 
as you see solo players gain too much renown then party ppl.  watch Slayer Nefistox - he was solo and gain too more renown then other
