### ISSUE TITLE
Tombstone UI for Respawning not popping up

### ISSUE THREAD

**Issue by Muglu** [WarEmu/WarBugs#2485]
I was playing just a minute ago and could not figure out why I was unable to respawn after dying in RvR.  I was fighting in Nordland and had no issues with it earlier in the day.  The game functions normally otherwise, there is just no pop-up to respawn.

**Comment by noisestorm** [comment]
try /reload in game and see if your release interface pops up. I am not sure if this is a Server or Client issue, hence i can just advice you to either try the reload command or call for a friendly ress or crash the client..

**Comment by Lamimolette** [comment]
Thank you for the quick answer.
At the end of the sc i deco/reco.
Now working as well, i will try if this happen again.
