### ISSUE TITLE
Bolster only raising you to lvl 31

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#2486]
As title says, it seems bolster is settling at 31 leading to some strange mitigation numbers from lvl 32s

**Comment by Ryanfawkez** [comment]
How are level 32's being down bolstered? Prior to the T3 release, when the bolster was still at level 21 and people were level 26, such an issue wasn't reported.

**Comment by Evildoor** [comment]
Should be obsolete with T4 release and 22-31/32-40 brackets.
