### ISSUE TITLE
Nature's Blade is not buffing party members

### ISSUE THREAD

**Issue by CeridianX** [WarEmu/WarBugs#2488]
Swordmaster's Nature's Blade (Blade Enchant) is not giving stolen stats from the enemy to the other party members but only to herself / himself. This skill should also buff others in a party within 100 feet.

**Comment by Evildoor** [comment]
Is this related to #2129? SM has similar tactic.

**Comment by CeridianX** [comment]
It might be related to this. However Nature's Blade is not a tactic but an actual skill - that would be a difference.

**Comment by Evildoor** [comment]
You misunderstood me. #2129 describes an issue - BO's ability Da Biggest is bugged when tactic You Got Nuffin is slotted. You describe the same issue with Nature's Blade, therefore i suspect that it's exactly the same problem. Do you have Bolstering Enchantments tactic slotted? If yes, try unslotting it and test again. If Nature's Blade works fine without tactic, then it's the same problem.

**Comment by CeridianX** [comment]
I'll try to test it next time. Thanks.

**Comment by CeridianX** [comment]
Yes, I can confirm that Nature's Blade works as long as there's no Bolstering Enchantment tactic slotted. So, it seems to be the same issue as with BO's ability.
