### ISSUE TITLE
Incorrect Scenario Xp & Rp

### ISSUE THREAD

**Issue by Stefanosgr18** [WarEmu/WarBugs#2489]
![123](https://cloud.githubusercontent.com/assets/16375224/12002320/fd3fbce8-ab03-11e5-8954-2291554dc5a6.jpg)
Not cool...unbalance.

**Comment by Evildoor** [comment]
That's enough. I appreciate your eagerness to support the project, but your attempts to do so bring way more harm than help. As a moderator of this place, i ask you to stop posting on the bugtracker.

**Comment by Stefanosgr18** [comment]
What? This is not a bug?? Seriously? Look the diferrence of shaman and me...

**Comment by Evildoor** [comment]
Cause of the difference is clear to anyone with knowledge of the game. Your knowledge is almost non-existent. Bugtracker is a place for reporting bugs, not for teaching you trivial things.

**Comment by Stefanosgr18** [comment]
Ok i dont post anymore...bye
