### ISSUE TITLE
Bugged crafting items.

### ISSUE THREAD

**Issue by Ripliel** [WarEmu/WarBugs#2493]
Some examples of bugged items for crafting
![bug1](https://cloud.githubusercontent.com/assets/16005849/12003832/3ac967a4-ab49-11e5-8c98-6c78ecce7606.JPG)
![bug2](https://cloud.githubusercontent.com/assets/16005849/12003833/3d22c68a-ab49-11e5-9b5d-fa18666b09f8.JPG)
![bug3](https://cloud.githubusercontent.com/assets/16005849/12003834/404815f4-ab49-11e5-934e-ced9aee495ac.JPG)
![bug4](https://cloud.githubusercontent.com/assets/16005849/12003835/4147e3ee-ab49-11e5-8659-d4e6d75e106f.JPG)

**Comment by Torquemadra** [comment]
They are not "bugged" per se, they are part of the older crafting system that was simplified on live and some older, unnecessary items were retired and as such grandfathered into these things. The fact that we are able to obtain these are drops is probably why we are able to get the rare drops to make chaos black as that is part of that system too.

**Comment by magter3001** [comment]
Would be possible for the devs to make these seeds into pigments then that either give chaos black dye or skull white dye?

Here's a list of some seeds I got...
Plagued-touched Dwarf Cheese Slipper Seed
Plagued-touched Searing Spikewort Seed
Plagued-touched Waxen Violet Canny Seed
Plagued-touched Sallow Argost Creep Seed
Plagued-touched Brown Old Man's Bristles Seed
Plagued-touched Probing Black Pea Seed
Plagued-touched Willowy Foolsberry Seed
Plagued-touched Blistering Dragoncap Seed
Plagued-touched Gossamer Spider Frond Seed
Plagued-touched Mottled Flea Agaric Seed
Plagued-touched Low-Cap Toody's Hat Spore
Plagued-touched Scarred Ulric's Tash Seed
Yellow-Stemmed Carmine Blusher Spore
Reach Loam
Treated Peat
