### ISSUE TITLE
[Magus] Chaos T3 RVR Inf rewards

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#2497]
At rank 2 you able to pick up helmet
But both lvl 27 purple helmets have same stats, but one of them have +2% Mag crit chance, while another one - not.
Passwatch Barbute - without mag crit
Thickmuck Barbute - with 2% mag.crit and this item has a wrong name for Chaos area, cos Thickmuck is from GS areas

All another stats are the same

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by SilverWF** [comment]
Excuse me, what will be fixed? The bug is not in lack of +magical crit - this helms must be different, but I really didn't remember what is a right stats for them :)
