### ISSUE TITLE
[Magus] Dark Elves T3 RVR Inf rewards

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#2498]
At rank 1 you able to pick boots, but all items are without talisman slots
Maiden's Daemonspurs 22lvl
Daemonspurs of Teclis 22 lvl
Grond's Daemonspurs 27lvl
Qhaysh Daemonspurs 27lvl

At rank 2 you able to pick up cloak
But there is only 1 purple lvl 27 cloak (Grond's Voidcloak) and it has pretty strange bonus: +1% reduced chance to be parried - absolutely useless stat for Magus
So totally there is 4 cloaks:
Maiden's Voidcloak 22lvl - seems OK
Maiden's Greatcloak 22lvl - seems completely as wrong item here
Maiden's Fright Shawl 22 lvl - seems completely as wrong item here
Grond's Voidcloak 27 lvl - seems ok by name, but not OK by stats
so, based on rank 1 and 3 reward names there must be something like Voidcloak of Teclis and Qhaysh Voidcloak

**Comment by Ryanfawkez** [comment]
On what class, may I ask? Item names would be appreciated too.

**Comment by SilverWF** [comment]
On Magus

**Comment by ungrninja** [comment]
http://warhammeronline.wikia.com/wiki/Magus_influence_rewards
[Maiden's Voidcloak]
[Ghrond's Voidcloak]
[Voidcloak of Teclis]
[Qhaysh Voidcloak]

Item Missing:

Qhaysh Voidcloak (http://www.arsenalofwar.com/armor/Destruction/Qhaysh%20Voidcloak)
Level:	27
Renown:	27
+ 11 Wounds
+ 9 Initiative
+ 7 Weapon Skill
+ 98 Spiritual Resistance
+ 98 Elemental Resistance
+ 98 Corporeal Resistance
+ 1% Reduction in being Critically Hit

I couldn't find info on the missing blue cloaks.

**Comment by ungrninja** [comment]
In addition to missing talisman slots on both purple boots the Qhaysh Daemonspurs are missing crit reduction.

http://www.arsenalofwar.com/armor/Destruction/Qhaysh%20Daemonspurs
Qhaysh Daemonspurs:
+ 18 Willpower
+ 22 Intelligence
+ 2% Reduction in being Critically Hit (missing stat)

**Comment by tutti13** [comment]
Still buggy

**Comment by Evildoor** [comment]
Have you seen any patchnotes claiming that this was fixed? Or maybe some comments here?

**Comment by ElMosquito** [comment]
Has not been fixed yet.

**Comment by Lheana** [comment]
@wargrimnir Can this report be closed? Is it fixed?
