### ISSUE TITLE
[Magus] Greenskin T3 RVR Inf rewards

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#2499]
At rank 1 you are able to pick up jewelry item
Grol Baraz Warp Pendant 22lvl 
Grol Baraz Dark Band 22lvl - seems wrong here, because no Magus careeer req and melee stats
Thickmuck Warp Pendant 27lvl
Thickmuck Dark Band 27lvl - seems wrong here, because no Magus careeer req and melee stats
Also, all area names must be used only once per reward level, but there is 2 times used same names. There is lack of "Brewer's ..." and "Karagaz ..." jewelry items

At rank 3 you able to pick robe, but here is something strange:
Nightrobe of Teclis 22 lvl - wrong name for GS area (Teclis is from DE area) and melee stats (STR, WS)
Qhaysh Nightrobe 27lvl - wrong name for GS area (Qhaysh is from DE area)

**Comment by ungrninja** [comment]
http://warhammeronline.wikia.com/wiki/Magus_influence_rewards
There are two purple jewelry rewards with same stats. According to the wiki the Thickmuck Dark Band doesn't belong.

Item Missing:
Qhaysh Warp Pendant
+ 11 Willpower
+ 8 Initiative
+ 17 Intelligence
+ 48 Spiritual Resistance
+ 48 Elemental Resistance
+ 48 Corporeal Resistance
+ 1 AP Per Second

**Comment by tutti13** [comment]
Still buggy

**Comment by wargrimnir** [comment]
Fixed some time ago, Dark Band are BG rings.
