### ISSUE TITLE
"New Recruits" - Nordland

### ISSUE THREAD

**Issue by loonbg** [WarEmu/WarBugs#25]
http://warhammeronline.wikia.com/wiki/New_Recruits

What i change : `Speak with Samuel Twitty 0/1` to `Speak with Samuel Twitty`

`UPDATE quests_objectives SET Entry =30361,ObjType = 1,ObjCount = 0,Description = 'Speak with Samuel Twitty',ObjID = 98325 WHERE Guid=5254;`

**Comment by Reggaewaldo** [comment]
Test ok.

Closing.
