### ISSUE TITLE
[Magus] Greenskin T2 RVR Inf rewards

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#2500]
At rank 2 you able to pick helmet.
But blue 13 lvl hemet Ironclad barbute has only 1 stat (+8 INI), while another one Alcadizaar's barbute has 2 stats (+8 WOU and +9 INI)

At rank 3 you able to pick staff
But it contains only 1 purple 18 lvl staff. Instead of 2nd there is Zealot's blue charm: Alcadizaar's Skull

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
