### ISSUE TITLE
[Magus] Chaos T1 RVR Inf rewards

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#2502]
At rank 1 you able to pick jewelry
But all items seems not for offensive mage, because do not contains INT stat
Festenplatz Marauder Warp pendant
Festenplatz Marauder Dark Band
Festenplatz Pillager Warp pendant
Festenplatz Pillager Dark Band

**Comment by wargrimnir** [comment]
Fixed some time ago, Dark Band are BG rings.
