### ISSUE TITLE
Joining another realm's party/wb

### ISSUE THREAD

**Issue by hogo2hogo** [WarEmu/WarBugs#2503]
Hi, today I was soloing rvr in empire keep attack because there were no available slots in any wb(i am a destro player) and i saw that in the say chat some guy asked for healers in his wb.
So I right clicked his name in the chat and I pressed "join group" which was the successful part. The problem is that i joined orders' wb. (!) I did not notice if i get rr, or if my group heals can heal them but still its a bug worth reporting :p

**Comment by Evildoor** [comment]
#1870
