### ISSUE TITLE
[Door] Fangbreaka Swamp Keep (T2 Destruction Marshes of madness) front door

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#2505]
The front door of this keeps leads to nowhere: you see the "Loading" message, then nothing around, then death and you are respawns in the Greenskin Ch 6 PVE camp
Backdoor works properly

**Comment by Povel** [comment]
+ 1

**Comment by SilverWF** [comment]
The same bug for Order side if they are taken this keep and trying to use front door: "Loading" message then falling down (but I wasn't dead this time so can't say where you will respawn)

**Comment by Ryanfawkez** [comment]
I have to personally apologise for this bug right here. Forgot to add a 0 in one of the spawn coordinates as I added them to each keep door and postern, by which the entire waypoint jump threw you into oblivion.

It's fixed in the next patch.
