### ISSUE TITLE
witchelf tactic  Frenzied Mayhem

### ISSUE THREAD

**Issue by boindill** [WarEmu/WarBugs#2506]
Frenzied  mayhem dont work.

**Comment by Torquemadra** [comment]
Have been informed by a friend that this is a paper doll issue, have you tried .getstats at each stage to see if crit rate changes there?

**Comment by ozarmidrashim** [comment]
This is a paperdoll issue. Use .getstats before reporting that it outright doesn't work.

Paperdoll issues related to effects which change their value depending upon resource level will be fixed generally in the next update.
