### ISSUE TITLE
Irelevant item Rewards in many quests ORDER

### ISSUE THREAD

**Issue by RoRWp** [WarEmu/WarBugs#2507]
Hello guys.Im playing with Slayer and a few quests so far gave me as a reward potions (intelligence) which is irelevant to my race.

**Comment by noisestorm** [comment]
Irrelevant Report as well. Give out questnames and steps with alternative or correct rewards and then the DB team may look at it. Posts like yours here ar enot helpful at all.

**Comment by RoRWp** [comment]
I will report soon...i have to do these quests again.As soon as i do i will report back.Cheers!

**Comment by RoRWp** [comment]
![healeras_005](https://cloud.githubusercontent.com/assets/16444872/12034078/b0ea88b2-ae34-11e5-9663-19a460beb1c0.jpg)
@noisestorm

**Comment by Evildoor** [comment]
The Emperor's Mandate rewards are overall screwed and it has it's own report: #187.
