### ISSUE TITLE
Players cannot be scavenged

### ISSUE THREAD

**Issue by Povel** [WarEmu/WarBugs#2508]
Unless you get the DB on the target, you cannot scavenge him/her/it - This applies to both PvE and PvP.

On live you could scavenge almost any corpse as long as you waited a moment even if someone else killed the target.

**Comment by noisestorm** [comment]
You can scavange other bodies, but only if they got looted. If the Killer does not loot the mob you cant scav it. Thats how it works unless it got changed recently.

**Comment by Povel** [comment]
Well that's just the thing though - Items get rolled for in PvP just like everything else and ultimately ends up in someones inventory anyway.

But the corpses still remain non-scavengeable and I think it's hell of a shame to not have it like the old system to say if for example a push happens in Tier 1 (again just an example) and a bunch of people die; a person in the back is then gonna make use of scavenging and scavenge the bodies as they're not of any use to the people who got the killing blow.

**Comment by nalgol** [comment]
player scavaging is not working cause theres no corpse system for dead players so if they respawn / rez the copse is gone aka i didnt add that feature yet cane we need those corpses first
