### ISSUE TITLE
RunePriest's master runes going on cooldown if used at long range.

### ISSUE THREAD

**Issue by Lileldys** [WarEmu/WarBugs#2509]
Using Master Runes at a long range (Longer than a heal range) will cause the skill to go on cooldown without casting. Happens with all 3 runes. I am unable to test the Zealot rituals as I don't have a high enough Zealot :P 

Video: https://www.youtube.com/watch?v=xKCfaRDylxc
Cast works as intended @ 3 seconds. The bug is shown @ 33seconds.

**Comment by ozarmidrashim** [comment]
https://github.com/WarEmu/WarBugs/issues/1118
