### ISSUE TITLE
0 XP, 0 RP's, 0 influence 

### ISSUE THREAD

**Issue by Alvanos** [WarEmu/WarBugs#2510]
I logged my KoTBS named Amsu. At 1st I was unable to get my auras activated, sicne they were self-deactivate in 5 seconds. After some reloggings I managed to get them work. But then I noticed that I was getting 0 credit from every source that would give me. Kills, keep takes gave me nothing.

**Comment by noisestorm** [comment]
Server right now is lagging quite hard, therefore your Auras may be lagging too.
At the killgains, that happens sometimes and a full Client restart normally fixes this issue. Just taskkill and report back if that helped

**Comment by Evildoor** [comment]
This problem still persists?

**Comment by Evildoor** [comment]
No response, closing.
