### ISSUE TITLE
Zealot: Mark of the Vortex has incorrect description (not sure if actual ability is affected)

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2512]
Looks like the ability text has been copied from http://waronlinebuilder.org/#career=zea;. It starts off with "Increases all your groupmember's resistances" but it should be "Increases a groupmember's resistances", i.e. the ability only affects a single target like all of the other Zealot marks.

I haven't tested the ability itself to see if it actually grants the bonus to the whole group or not.

**Comment by milosxe** [comment]
Since the tool tip is wrong, it's a client side issue and can't be patched without repercussions.
It doesn't affect everyone, only one person.

**Comment by RoR-Zomega** [comment]
Apologies, it seems I accidentally read it as groupmembers' rather than groupmember's.
