### ISSUE TITLE
Passwatch Glaive has wrong speed

### ISSUE THREAD

**Issue by ropuch** [WarEmu/WarBugs#2515]
Hi! Destro T3 Empire influnece reward (2H Passwatch Glaive)  for BG has too low speed (2.0). As much As I like it, it's clearly a DB item bug :).

**Comment by Ryanfawkez** [comment]
2.0 is actually too fast for a 2-hand weapon. The number needs to be higher for a longer delay between AA hits.

**Comment by Meralors** [comment]
Will be 3.4 now, like most other 2 handed.
Live next patch.
