### ISSUE TITLE
[Skill][White Lion] Pounce on walls

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#2516]
The ability to Pounce on walls was fixed, not so far, if I'm not wrong
But it is still possible, Isgard for example, doing this all the way.

**Comment by ropuch** [comment]
Player name is not really necessary in bug report ;-)

**Comment by SilverWF** [comment]
Maybe they'll check logs and found a source of bug. He is not only who doing this, for sure.

**Comment by Evildoor** [comment]
#1222
