### ISSUE TITLE
[Engie] Friction Burn can't be cleansed

### ISSUE THREAD

**Issue by milosxe** [WarEmu/WarBugs#2517]
Both zealots and doks can't cleanse this dot even though it's a hex.

**Comment by ozarmidrashim** [comment]
Friction Burn has the correct typing in the DB.

**Comment by milosxe** [comment]
Yes, it's weird. I can clearly see the debuff on friendly target, cleanse lights up but no matter how many times you try, you can't cleanse. Yesterday a dok reported the same thing in sc.
