### ISSUE TITLE
DoK influence reward

### ISSUE THREAD

**Issue by julanta** [WarEmu/WarBugs#2520]
Some of the DoK T3 purple influence reward is wrong

Chaos:
Thickmuck Gorget missing a talismans slot

Dark Elf:
Ghrond's Bloodwades missing a talismans slot
Qhaysh Bloodwades missing a talismans slot
Only one purple back piece, wrong stats and level req. on the one that should be purple

Greenskin:
Two identical rings, different names but same stats
Thickmuck Breastscale is missing rougly 15 of some stats compared to other rewards.

**Comment by Meralors** [comment]
Thickmuck Gorget - Added 1 talisman slot
Ghrond's Bloodwades - Added 1 talisman slot
Qhaysh Bloodwades - Added 1 talisman slot

As for the other items I need to find infos on how they were on live.

**Comment by julanta** [comment]
Found some info on DoK T3 inf. reward.

List of all the item names: http://warhammeronline.wikia.com/wiki/Disciple_of_Khaine_RvR_guide


Found some of them on: http://www.arsenalofwar.com/

http://www.arsenalofwar.com/items/Destruction/Qhaysh%20Chalice
http://www.arsenalofwar.com/items/Destruction/Passwatch%20Edge
http://www.arsenalofwar.com/armor/Destruction/Qhaysh%20Bladebelt
http://www.arsenalofwar.com/items/Destruction/Ghrond's%20Xiphos
http://www.arsenalofwar.com/items/Destruction/Stoneclaw%20Sword
http://www.arsenalofwar.com/armor/Destruction/Passwatch%20Bladebelt
http://www.arsenalofwar.com/armor/Destruction/Qhaysh%20Bloodwades
http://www.arsenalofwar.com/armor/Destruction/Ghrond's%20Torment%20Cloak
http://www.arsenalofwar.com/armor/Destruction/Qhaysh%20Torment%20Cloak
http://www.arsenalofwar.com/armor/Destruction/Thickmuck%20Gorget
http://www.arsenalofwar.com/armor/Destruction/Thickmuck%20Blood%20Chain

**Comment by Styrkarr** [comment]
Fixed Dark elf missing purple cloak.

For Greenskin, what careers has the same rings ?

**Comment by Evildoor** [comment]
Breastscale: #1928.
Identical rings: i presume that it was DoK ring and BG ring(missing class restriction) offered to DoK, this was fixed.
Cloak: fixed.
Talisman slots: fixed.
Closing.
