### ISSUE TITLE
Moving crafting resources from main inventory to crafting inventory

### ISSUE THREAD

**Issue by Prysm** [WarEmu/WarBugs#2521]
Error in chatbox.  Items that failed to move were destroyed.
![image](https://cloud.githubusercontent.com/assets/16451817/12010132/d24cc3a4-ac67-11e5-9d04-449f34ce4331.png)

**Comment by Squea** [comment]
The crafting backpack is a bit buggy, sometimes you have to click around in your main bag to access the corresponding slot in the crafting pack.  Could be an addon issue, I use Miracle Grow.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
