### ISSUE TITLE
Respawning in Warcamp when entering sc in rvr lake

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#2523]
on live you were only ported to wc when entering sc at bo or keep not everywhere.

(its weird right now: joining sc will port you to wc everywhere, but when dead and logging out and in again or crashing client you are ressurrected at the point you died no matter where, even in contested or taken keep etc, seems exactly the wrong way ^^)

**Comment by Tesq** [comment]
yea  i can confirm was that way, if you where near bo and keep only, which was to prevent ppl to capture or relog  into battle objective

**Comment by Tiggonos** [comment]
just experienced: when entering a sc in a keep, you come out at that keep. (prbly. only when not contested though).

**Comment by Tiggonos** [comment]
thx for fixing.
