### ISSUE TITLE
The Emperors Mandate

### ISSUE THREAD

**Issue by Numatic** [WarEmu/WarBugs#2524]
Curropter Bathshida does not respawn to be killed. I know a known issue with Markus attacking her, but she has not respawned and the body is laying in the same spot every time I check (for the last several hours). Not sure if a bug or glitch and she just needs to be reset.
![numatic_001](https://cloud.githubusercontent.com/assets/16452410/12010424/538296ea-ac74-11e5-93da-c7c63de3e34e.jpg)

**Comment by Evildoor** [comment]
#187 is an original issue about the quest.
I'm not closing this report because it seems to be a different problem.

**Comment by Meralors** [comment]
Just to make sure it works properly I moved the other npc a bit further so they don't fight each other anymore. There was no problem in db about her respawn rate, so she may just have bugged on live because of the fight between those 2 npc. Should no longer happen.
See how it goes next patch ;)
