### ISSUE TITLE
aura kotbs

### ISSUE THREAD

**Issue by crixus28000** [WarEmu/WarBugs#2526]
the aura for knight of the blasing sun (concentration, that heal), in true game, each defense we recovery xx life points 3 times (example : for 90 pv aura, 1 block = 30 + 30 + 30 in the same time ) and in this game it's wrong because it is 90 points life for 3 seconds then if we block 2 times in 1 seconde, it's stay 90 pv on 3 secondes and not 30 + 30 + 30 x2, i hope to helped, thanks if you can do something, cya :-)

**Comment by taccr** [comment]
Effect doesn't stack.

**Comment by Thorgatin** [comment]
That aura never worked like that; it would be totally OP...

**Comment by Torquemadra** [comment]
Never worked like that, would be a heal to full for every tank close to a knight who popped shield wall if under attack from multiple sources.
