### ISSUE TITLE
[DUELS] Party buff give bonuses to the opponent.

### ISSUE THREAD

**Issue by Tanesiris** [WarEmu/WarBugs#2528]
Duels are simply bugged, If you play kotbs the auras buff you and your opponent even if hes marked as a enemy, this really kills duels for me because my enemy gets all my bonuses while he should be decreased.

**Comment by ozarmidrashim** [comment]
Not really interested in duel bugs.

**Comment by Tanesiris** [comment]
Well some players do enjoy duels also worth mention is that Stealth is broken for WH's and everyone can see you, im here to help but that statement was not necessary. Feels like a pointless feature if some classes are going to get screwd over only because its not in your intrests to fix it.

**Comment by Torquemadra** [comment]
It wasnt even a feature on live, appreciate it for it being there in any form

**Comment by noisestorm** [comment]
Auras also should just give the bonis if you're in the same party with the Chosen/Kotbs. If youre not then the auras arent affecting your opponent anyways? Nonetheless this was a gimmicky implementation just for fun. Be happy you can at least test your dmgs and skills realm-internally.

**Comment by Tanesiris** [comment]
I Been playing since beta to clear that one up, And i do appreciate the effort but its not enjoyable "in any form" for the classes that have to deal with the handicap.

**Comment by Luth-RoR** [comment]
These kind of bugs will likely never be fixed as this is an unsupported feature that never existed on the mythic servers. Furthermore there could be client restrictions that can't be passed atm.
