### ISSUE TITLE
Warband management

### ISSUE THREAD

**Issue by Sonare** [WarEmu/WarBugs#2530]
If someone got crashed or leave he still taking slot in wb and he can't be invited again  (need to form new WB)
After this bug WB leader cant move ppl also.

**Comment by Sonare** [comment]
partially it's can be fixed by kick someone else from wb and invite again (works not in all cases)

**Comment by Sabacik** [comment]
I had the same the same problem today. People crashed and ti was impossible to remove them from the party. Also it was impossible to move warband leader between the parties.

**Comment by Tesq** [comment]
seems that crash or log in the sc it's the same as on ror differently from live your character during port is not online and this bug the wb.

**Comment by hoppolek** [comment]
It looks as you can't move players between groups. But you do in a weird way. It looks as you're still in the old group while your group buffs and heals will affect the "new" group, but not yourself.
