### ISSUE TITLE
No XP, no RR for kills during scenario

### ISSUE THREAD

**Issue by OldPlayer** [WarEmu/WarBugs#2531]
It seems that many people get no XP, no RR for kills done during scenario. Kills are counted for, final bonus for finishing scenario is granted.

Relogging does not help.
Using .unlock does not help.

**Comment by Sabacik** [comment]
Same here. Did 4 SC in the last 30 min and in all I have received 602-604 renown. Bonus for win 600 and 2-4 renown for kills in the SC regardless of the number of kills.

**Comment by Calarian** [comment]
Are you grouped or running solo? I think it is based on the party doing the killing as well.

**Comment by taccr** [comment]
Grouped. We got like 5 renown in total per player for getting around 20-30 dbs.

**Comment by OldPlayer** [comment]
Always grouped. All people in scenarios have mentioned experiencing the same problem. Lots of people in advice were discussing that as well.

**Comment by Torquemadra** [comment]
confirmed, my lvl 9 engi got top damage and kills and no one from our team got anything at all.

[img]http://i.imgur.com/17asei9.jpg[/img]

[img]http://i.imgur.com/hF7m5zR.jpg[/img]

**Comment by Evildoor** [comment]
There are plenty of reports recently (#2510, #2484, #2399, etc, etc) which indicate that something's wrong with reward system, and the problem is being worked on.
