### ISSUE TITLE
Skaventide RvR quest Relentless Siege not working correctly or as described

### ISSUE THREAD

**Issue by Hargrim** [WarEmu/WarBugs#2533]
Hello,

According to the Dana post on the forums, this quest should be changed to: 

I changed the keep lord Quest. You have to retake it and then you have to kill 3 keep lords. Please try if it is possible.

I retaked it and still have the old one, please find screen attached.

![image](https://cloud.githubusercontent.com/assets/16460565/12015966/0c5ec956-ad45-11e5-8065-30a6c0a208f8.png)

**Comment by Meralors** [comment]
Changed quest on live, its now working. Closing
