### ISSUE TITLE
[KotBs] Gilde Shield Tactic

### ISSUE THREAD

**Issue by shamallow** [WarEmu/WarBugs#2534]
The +15% disrupt attacks doesn't work.

It's not counted in the character stats.

**Comment by noisestorm** [comment]
Use the .getstats command and see if it really is not added. Then comment back

**Comment by shamallow** [comment]
ok i will try that (i didn't know this command btw)

**Comment by shamallow** [comment]
i've just used the .getstats command, and it appears that the tactic works.
i have an item with 3% disrupt, and then with the tactic, i got 18% in all.
![image](https://cloud.githubusercontent.com/assets/16374367/12020482/4ae35876-ad7d-11e5-87a4-0d4261343cc4.png)
