### ISSUE TITLE
HP/4 Stat Not Working

### ISSUE THREAD

**Issue by Chucunei** [WarEmu/WarBugs#2536]
The feature x hit points every 4 seconds on item dont work.

**Comment by Evildoor** [comment]
#1538

**Comment by Chucunei** [comment]
Thanks for your quick answer, but sorry i'm spanish and i not understand if this is fixed or not, so this hit point regen works correctly now?

**Comment by Evildoor** [comment]
No. I just pointed out that this problem was already reported.
