### ISSUE TITLE
Procs from "Warping the Spirit" and "Regenerative Shielding" tactics in the wrong stacking group

### ISSUE THREAD

**Issue by RoR-Zomega** [WarEmu/WarBugs#2537]
As per thread here: http://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=10300#p102273

Azarael:
> This looks like a bug. The way I've implemented tactics generally in RoR is that they all stack with each other in the Tactics stacking group, regardless of whether the effect is applied directly via the base tactic buff or indirectly via a procced buff. Warping the Spirit and Regenerative Shielding had their base tactic marked correctly but not the buff they create.

> For base stat bonuses, this behaviour can be verified by looking at the paperdoll. If it matches the output of .getstats, my handling is correct. The reason this doesn't work for armor is because the server is, for some reason, authoritative over the armor stat.

**Comment by taccr** [comment]
The correct behavior however is the current implementation where the warping the spirit armor buff does not stack with armor potions. Only the higher buff used to count here.

**Comment by Squea** [comment]
If working as intended it makes the tactic worthless as almost everyone is running armor pots, and many tanks have a potent self-armor buff anyway.  I agree that for example: a toughness pot shouldn't, and doesn't currently, stack with a Shaman's Do Sumfin Useful.  Tactic procs might be a different animal, although at the same time we don't want people reaching 5k armor at this stage in the game.

**Comment by taccr** [comment]
I'm just stating how it was on live. Many tactics are useless or outclasses by others. However here you still get the reduced armor pen and a higher armor buff than pots do provide.

**Comment by ozarmidrashim** [comment]
Reverting fix per taccr. While I'd normally prefer consistency, the last thing this game needs is ADDITIONAL armor stacking.
