### ISSUE TITLE
[Scenario] Renown and exp.

### ISSUE THREAD

**Issue by Ripliel** [WarEmu/WarBugs#2538]
What kind of bug or evil magic is this?
![sc](https://cloud.githubusercontent.com/assets/16005849/12025458/b03f4298-adc8-11e5-8d93-18da504710d6.JPG)
![sc2](https://cloud.githubusercontent.com/assets/16005849/12025460/b2527de8-adc8-11e5-9128-d15e9ca6215e.JPG)

**Comment by noisestorm** [comment]
Is already known. No need to report it further
