### ISSUE TITLE
Encroaching Darkness III

### ISSUE THREAD

**Issue by Armond-Hammer** [WarEmu/WarBugs#2539]
The Encroaching Darkness quest line in Nordland bugged for me at this part. The quest should complete and move on to Encroaching Darkness IV when clicking on Peter Allard however It did not do this for me.

Here is a link to the wiki of the quest.

http://warhammeronline.wikia.com/wiki/Encroaching_Darkness_III

**Comment by Hauclir** [comment]
They made it so that you have to go back to the priest where you got that quest from to move on to next part after you complete the quest. No need fixing just close it.

**Comment by noisestorm** [comment]
For future stuff like that: indeed some quests that require you to click some item/corpse to finish, will not finish itself like on live (with completion popup) - you have to go back to the questgiver.
