### ISSUE TITLE
Red Wolf: Nordland Lair

### ISSUE THREAD

**Issue by Squea** [WarEmu/WarBugs#2540]
Normal Red wolf mobs cannot be butchered.  Could be I have too low a skill, I'm at 183 butchering.

**Comment by noisestorm** [comment]
Exact mob name(s) for the DB team pls. Then i can mark it

**Comment by Squea** [comment]
Mob: Red Wolf
Level: 40
Location: Nordland 30k, 60k

I went back and only managed to kill one.  It didn't drop coin, possible that they don't drop loot at all.  Can't butcher.

**Comment by Thayli** [comment]
Works fine. All wolves in the area drop gold, items and can be butchered.
