### ISSUE TITLE
Blackguard Devastator Pauldrons Wrong Appearance

### ISSUE THREAD

**Issue by Hauclir** [WarEmu/WarBugs#2541]
![hauclir_002](https://cloud.githubusercontent.com/assets/7598530/12029464/886c60d4-ada0-11e5-909a-5b6e6ee003e1.jpg)
![hauclir_000](https://cloud.githubusercontent.com/assets/7598530/12029465/8a48f052-ada0-11e5-8f53-d14eec10d4be.jpg)
^ This is how it currently looks like, picture below is how it suppose to look. I even died it red and black like the picture below to show how clearly different it is.
![blackguard devastator armor set](https://cloud.githubusercontent.com/assets/7598530/12029466/8f92f238-ada0-11e5-9291-a335c0f73e84.jpg)

**Comment by Hauclir** [comment]
![hauclir_003](https://cloud.githubusercontent.com/assets/7598530/12060499/f9901a36-af25-11e5-87f2-d9266d9ad241.jpg)
![hauclir_000](https://cloud.githubusercontent.com/assets/7598530/12060500/fc89cbc4-af25-11e5-8a93-12e1c367eb52.jpg)
looks like someone tried to fix it, but they put wrong appearance again XD good try tho.

**Comment by Ryanfawkez** [comment]
I'll fix this definitely in the coming hour, currently working on a few item appearances for the next patch.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
