### ISSUE TITLE
Public Quest Mob influence gain is too low.

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#2542]
On live kills gained you 100 influence per stage 1 mob kill not 50.

I appreciate that this may not be anything relevant at the moment and that PQs and other PvE will be getting looked at in time but I mention this because I like to pick up the influence items because there are some unique appearances there and I like to do it at a relevant level. 

As it stands now at 50 inf a kill I end up horribly overleveled, chapter 7 influence caps out at just over 12000, which is 240 mobs which at around 700-1200 xp per mob is 200k xp.

Again, Im sorry if this is something not to be brought up at this time, I just hoped that it would be an easy fix and increasing the rewards to live levels would assist in diluting frustration its current form. I have videos available showing 100 inf per kill on stage 1 mobs if required for verification.

**Comment by Evildoor** [comment]
#1800. Seems to be a general problem, not only PVE-related.

**Comment by Torquemadra** [comment]
T2 BFOs relinquishing 100 in per cap tick

**Comment by wargrimnir** [comment]
PQ's give proper influence now.
