### ISSUE TITLE
Hrim Tuskgor are craftable with scavenging 

### ISSUE THREAD

**Issue by RoRWp** [WarEmu/WarBugs#2543]
http://warhammeronline.wikia.com/wiki/Boar
They are animals.But we can scavenge them?

**Comment by ozarmidrashim** [comment]
You were told to 'stop posting on the tracker.'

If I have to ban you from the game in order to enforce this, I will.

**Comment by RoRWp** [comment]
I asked kindly to post again important bugs as this one.
