### ISSUE TITLE
Bags bugged after setting preferences

### ISSUE THREAD

**Issue by Udonyawhyisthisnametaken** [WarEmu/WarBugs#2544]
So I set preferences for my bags to divide crafting materials from salvages from crap but after a reload (= zone switch) I can't access my bags anymore. 
reload / relog doesn't work either.
checkboxes won't work
can't set preferences back

![tsubomi_012](https://cloud.githubusercontent.com/assets/16477507/12035939/b261612c-ae41-11e5-9217-532cc3442ed4.jpg)
![tsubomi_013](https://cloud.githubusercontent.com/assets/16477507/12035951/ce80cdf2-ae41-11e5-9b3d-5b51410c6192.jpg)
![tsubomi_014](https://cloud.githubusercontent.com/assets/16477507/12035961/dff1549e-ae41-11e5-9bf3-0f562ce1ab4a.jpg)

**Comment by Kaelang** [comment]
This is no longer present in the current version of RoR - if this issue persists please re-open a new ticket.
