### ISSUE TITLE
Can't Hit Me damage does not procs War Bellows

### ISSUE THREAD

**Issue by balgax** [WarEmu/WarBugs#2546]
Block Channel doesnt proc a roar

**Comment by Evildoor** [comment]
If Can't Hit Me not proccing a War Bellow is a problem then why bring AP tactic in here?

**Comment by ozarmidrashim** [comment]
Requesting confirmation that CHM! and WoDS for SM proc effects.

**Comment by genisaurus** [comment]
Confirmed @ 2:49, Nature's Theft procs during WoDS: https://www.youtube.com/watch?v=RYCsgQbsgUc
WoDS and CHM! can proc Blade Enchantments/War Bellows.
