### ISSUE TITLE
Mixed Defenses tactic not stacking with Suppression

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#2548]
According to stacking groups it should stack, however it didn't for me the last time I tried.

No idea how it was back on live.

**Comment by ozarmidrashim** [comment]
To verify this, check whether the paperdoll mismatches with the output of .getstats.

**Comment by taccr** [comment]
Paperdoll shows 50%, .getstats 25%.
Does this mean its working properly?

**Comment by Gobtar** [comment]
They stacked on live;All i have is anecdotal evidence that I mained a chosen on live. Tactics and abilities generally did stack.

**Comment by ozarmidrashim** [comment]
taccr: It confirms that this is a bug and that they should stack. Paperdoll represents how it was on live, getstats represents what the RoR server is currently doing.
