### ISSUE TITLE
Shield Rush Buff categorized as Blessing

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#2549]
Shield Rush was not removable on Live Servers.

It was a Buff, not a Blessing. - I know the tooltip says different, but that's how it was.

**Comment by Evildoor** [comment]
I think we should not follow the live logic here and leave the type as Blessing. @ozarmidrashim ?

**Comment by ozarmidrashim** [comment]
Both 3496 Shield Rush and 8011 Shield Rush are Blessings, so Shield Rush never had a blue Buff typing on live Warhammer. If Shield Rush was a Blessing and yet could not be severed, I interpret this as a Mythic bug and I will fix it.
