### ISSUE TITLE
SH/Engi pet range

### ISSUE THREAD

**Issue by Halhammer** [WarEmu/WarBugs#2550]
Dunno if this has been brought up but can somebody look into the pet range? Especially squig pets that keep following and harassing you across the whole damn map are becoming increasingly annoying... same goes for indefinite turret redeploy range ofc. Both were leashed at 100ft on live.

**Comment by Evildoor** [comment]
Are you sure about this? #2353 is supposed to be fixed.

**Comment by ozarmidrashim** [comment]
Leash is 300ft on RoR.

**Comment by Halhammer** [comment]
Morf is right about the disappearing pet and cooldown. I'm 99% sure it was 100ft for the engi turret, maybe 150ft but I doubt that. Never played a SH but I guess it'd be the same for the pet. Anyway 300ft is way off

**Comment by Udonyawhyisthisnametaken** [comment]
Lions sometimes appear out of nowhere too

**Comment by gittoaster** [comment]
I am experiencing what may be a bug on WL.
WL does not return to combat when you mount - then seems to stay in melee range after that.

I test
Send Lion to attack
Mount Up (should make pet heel+out of combat)
Pet seems to run to me sometimes but always still actually in melee range

Also what I tested
Send Lion to attack and let it engage
Heel Lion - Lion only appears to return but actually stays in range.

**Comment by gittoaster** [comment]
[img]http://s4.postimg.org/uie11z8ml/petrange.jpg[/img]
range still in range but seen as out of range (after Heel command).

**Comment by Zealote** [comment]
Regarding the original report, if the leash were 100ft, wouldn't that mean, for example, that a SH couldn't send their basic squig in while being at their max range (also 100ft), since the squig would constantly be moving at least a few feet in and out of that range? :S Or have I just misunderstood what Halhammer meant?

**Comment by Luth-RoR** [comment]
Just a small info to pet behavior: 
Everyone can check his own pets a.i. commands/pathing by targeting the pet and type _.mindread_
Maybe this helps to narrow issues down.
