### ISSUE TITLE
[SM/KotBS][Influence reward Elf T3] Missing stats

### ISSUE THREAD

**Issue by Rodagroda** [WarEmu/WarBugs#2552]
Swordmaster:
Ghrond's Warcoat missing stats. (Should be +17 Str? see Ghrond's Grudgecoat)
Ghrond's Solerets missing talisman slot

Knight of the Blazing Sun
Ghrond's Warmantle missing stats. (Should be +17 Str? see Ghrond's Grudgecoat)

Ironbreaker item as reference:
http://www.arsenalofwar.com/armor/Order/Ghrond's%20Grudgecoat

**Comment by Meralors** [comment]
Added 1 talisman slot to Ghrond's Solerets.

As for the other items I'm looking for information about how they were on live to fix them.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/5494

**Comment by NorKalli** [comment]
long since fixed
