### ISSUE TITLE
scenario party window HP bars are not updating correctly.

### ISSUE THREAD

**Issue by sb220** [WarEmu/WarBugs#2553]
possibly an issue where one characters name is showing another characters HP bar.

As a healer Its impossible to do anything but group heal. Hp bar on party window would show me taking dmg and dying, but it wasn't actually happening. Reason I think my hp bar was linked to a different player

**Comment by noisestorm** [comment]
Only occurs if people join already full groups and bug them out. Is already known - small hint from my side: Most of the time the one above the 'attacked' target is the one actualyl getting the damage.
