### ISSUE TITLE
Keep doors buggy

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#2555]
About 50% of the time clicking on one (not a double click) will directly turn you around, leave you outside (or inside if trying to get out) facing away from the door. This seems to have cropped up in last day and a half. No problem with posterns.

**Comment by AddisonSchiller** [comment]
Lately Keep doors have been giving hte message "Too far from keep door" when you click on them to get in, even if you are close enough. Had this happen quite often today, usually when trying to get into a keep, but not go out.

**Comment by Lheana** [comment]
This must have been fixed so I close it.
