### ISSUE TITLE
Scenarios Rewards close to no XP or Renown

### ISSUE THREAD

**Issue by roadkillrobin** [WarEmu/WarBugs#2559]
My last scenario at rank 19, i got a total of 2rrp and 19xp. We won scenario with 500-45
Why is there no Scenario win bonuses anymore?

**Comment by Renork** [comment]
Bug and it has been reported.

**Comment by Evildoor** [comment]
There are plenty of reports recently (#2510, #2484, #2399, etc, etc) which indicate that something's wrong with reward system, and the problem is being worked on.
