### ISSUE TITLE
Blackguard Sentry's Glaive of Ferocity Talisman Slot Issue

### ISSUE THREAD

**Issue by Hauclir** [WarEmu/WarBugs#2560]
You can slot the 1st talisman fine to any of the 2 slot, but you can't slot a 2nd talisman to the last slot and yes I was using 2 different stat talisman that are below level of the weapon so that they can be inserted. Picture example showing me trying slot a toughness talisman(even though it does not show the cursor in ss)  to the last slot with a strength talisman already inserted in one of the 2 slots, but it does not allow me to insert the talisman in the last slot.
![hauclir_003](https://cloud.githubusercontent.com/assets/7598530/12045299/c356b96e-ae55-11e5-99e1-6e10487ed114.jpg)

**Comment by taccr** [comment]
Isn't this the same problem as https://github.com/WarEmu/WarBugs/issues/2480 ?

**Comment by Hauclir** [comment]
confirm same issue it worked when I slotted a different color.
