### ISSUE TITLE
Crashed Highland Cemetery Scenario earned rr 170

### ISSUE THREAD

**Issue by Prysm** [WarEmu/WarBugs#2561]
Title says it all.  character Prysm, time 9:15 eastern standard time.  Game lagged out but before it did it  kind of glitched I was awarded some absurd amount of rps and dinged rr 170.  Don't have a screen shot so best I can do is give a description.

**Comment by taccr** [comment]
Packet corruption. I dinged so many high renown ranks and won a lot pq bags in scs.
It's a known problem.

**Comment by Evildoor** [comment]
taccr is correct, and this was reported elsewhere.
