### ISSUE TITLE
Map gone after log out in Altdorf

### ISSUE THREAD

**Issue by hoppolek** [WarEmu/WarBugs#2562]
Whenever you log out a character in Altdorf and then log in any character, you will not be able to open your map. The way to get rid of this is to relog again.

If this is server side, maybe it has something to do with Altdorf not loading properly? My mini map reports zone 0 if I log on in Altdorf, or my last map if I travel to Altdorf.

**Comment by Cimbas** [comment]
Ahh thank you, now I know where this comes from. Reloading your interface in another zone than altdorf also solves the problem for me.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/6831
