### ISSUE TITLE
Stuck in a weird spot in SC.

### ISSUE THREAD

**Issue by KOTBS** [WarEmu/WarBugs#2566]
![trevlig_006](https://cloud.githubusercontent.com/assets/16400629/12049129/a9f2e36a-aee3-11e5-91ef-d8c151201fe7.jpg)
The picture tells you every thing.

**Comment by Evildoor** [comment]
I doubt that we can do anything with getting stuck in terrain.

**Comment by genisaurus** [comment]
Terrain issues aren't bugs
