### ISSUE TITLE
[Squig Herder] SharpToofs Tactic does not work

### ISSUE THREAD

**Issue by Gobtar** [WarEmu/WarBugs#2570]
The Squig Herder tactic Sharp Toofs does not increase the damage of Git Em! nor does it decrease the action point cost. The Action point decrease does not show up on the tooltip, I did test the damage on a player with all other aspects being the exact same (with and without tactic).

**Comment by ozarmidrashim** [comment]
This tactic presents an implementation problem, in modifying solely the damage of the pet's attack. Fortunately, both the tactic and melee Squig Herders are crap, so the tactic now modifies both the master and the pet's first attack's damage.
