### ISSUE TITLE
Focused Mending tactic active in full aura range.

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#2571]
Focused Mending should only be effective in 30f range around the KotBS. (Guard range)
Currently the buff displays +15% on all targets in aura range.
However targets outside 30f range should get the regular Stay Focused buff without the 15%.

The current version is simply too strong and not how it was on live.

**Comment by Evildoor** [comment]
It was 30 ft on live? Proof?

**Comment by taccr** [comment]
I don't have any screenshots. But I'm sure any good KotBS player can confirm :)b

**Comment by ozarmidrashim** [comment]
8060 Focused Mending
Stay Focused! will now also cause groupmates in the area to receive 15% more from all healing effects used on them.

I'm going to need confirmation for this, because if this is true, it will require modifications to the basic aura handler to force refreshes.

**Comment by Torquemadra** [comment]
This was always dependent on the aura in live not just a team wide buff

**Comment by Tiggonos** [comment]
the tooltip does not indicate anything that the tactic buff has different range then the aura.

**Comment by taccr** [comment]
It actually does. All other auras state "all groupmates within 100 feet". The tactics states "in the area".
We are trying to get confirmation how it was implemented on live.
I'm already 100% sure because I played my KotBS to RR100 and several for years.

**Comment by ozarmidrashim** [comment]
Mythic's implementation doesn't support this idea either. Focused Mending is implemented by adding another command to the basic Stay Focused! buff. If they really had separate ranges, this would be an extraordinarily bad way of designing the buffs, with the correct way being to spawn an additional 30ft aura buff when Stay Focused! is activated and kill it when SF! goes down.

**Comment by Evildoor** [comment]
Closing since no proof was provided that the tactic on live worked in such questionable way.

**Comment by Thorgatin** [comment]
I remember it like descibed by the OP too. No evidence though. I suspect a stealth nerf deployed in an unknown patch by mythic coders
