### ISSUE TITLE
'The Lighthouse' Objective not shown on map T2.

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#2574]
Usually all the Bo's are shown in the map.  This has been around for a while, I don't see a proper BR for it.
[img]http://s13.postimg.org/3s2vfrx6f/lighthouse.jpg[/img]

thx

**Comment by vove-RoR** [comment]
You have to get there to see if it is controlled by order or destro, minimap shows precisely same thing as the world map.

![untitled](https://cloud.githubusercontent.com/assets/16596013/12201679/a62121f2-b61d-11e5-8a0e-3d6844801363.jpg)

**Comment by gittoaster** [comment]
My theory is it's possibly to do with the Z axis of that Objective being higher?
