### ISSUE TITLE
Quest Icons are incorrectly used

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#2575]
The quest icons for PvP Kill quests do not show as Blue icons as the intended graphic in live game.

**Comment by noisestorm** [comment]
The whole Questicon usage currently is wrong:
Blue = repeatable Quest which was not taken yet
Green = normal Quest that can be done once and was not taken yet
Grey = Quest that you have accepted
Orange = quest is completed and can be handed in

**Comment by gittoaster** [comment]
recent changes to the system have addressed the color schemes.
