### ISSUE TITLE
Brigand's Hatchet stats

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#2578]
Should either be a 2h weapon or stats tuned down to 1h.

![Brigand's Hatchet](http://img8.uploadhouse.com/fileuploads/21901/21901588c6bfb320cc34846d50711edb2b1bfcf5.png)

**Comment by Torquemadra** [comment]
Should be a 2h but not much of a concern as WLs cant dual wield and no other elf can use an axe. There are a couple of artifact 1 hander elf axes about from when the WL was originally meant to dual wield.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by Sabacik** [comment]
Should it be a bit slower, around 3.2 - 3.4 for a 2h?
