### ISSUE TITLE
AM silence

### ISSUE THREAD

**Issue by Sizer1111** [WarEmu/WarBugs#2580]
Not sure if it happens for all classes but my sorc was able to continue casting spells during the am silence. Still got immunity for the full duration too.

**Comment by noisestorm** [comment]
Silence is basically missing an interrupt component @ozarmidrashim 
thats with all silences so far (maybe due to the 3/4 casttime grace period?)

**Comment by ozarmidrashim** [comment]
Nope. A number of spells are instead missing their typing.

**Comment by ozarmidrashim** [comment]
Fixed missing vulnerability to Silence for a number of spells.
