### ISSUE TITLE
Oath friend not respecting range

### ISSUE THREAD

**Issue by magicthighs** [WarEmu/WarBugs#2581]
Oath friend still gives grudges even if the target is in another zone.

**Comment by noisestorm** [comment]
Same for DP from BG.

**Comment by ozarmidrashim** [comment]
Correct range is?

**Comment by magicthighs** [comment]
According to http://warhammeronline.wikia.com/wiki/Oath_Friend it's 160ft.

**Comment by Torquemadra** [comment]
On live it was zone wide for generating grudge and hatred, the range is regarding the placement of oath friend and the buffs received from the IB/BG

It would toggle off when leaving a zone.

**Comment by taccr** [comment]
Buffs received have a seperate range show on the specific spell. (Usually 50f)
The range shown on the oath friend/dark protector tooltip is the range to apply the actual buff to your friendly target.
