### ISSUE TITLE
Combat start/refresh problems

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#2582]
If an ability does not do damage or is being avoided the attacker (defender too?) is not being brought in combat or his combat timer extended.

i.e. dodging an attack should bring you in combat. 
taunting a player or npc should also bring both in combat

Also when your guarded player enters combat the tank needs to be brought on combat too.
Currently I can take guard damage without being in combat.

**Comment by danissrv** [comment]
Also when you do group buffs like Git Stuck In and someone from party is in combat then you should also get in combat.

Those are all important features for generating Morale or Rage(for choppa/slayer)
