### ISSUE TITLE
Morale fading too fast

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#2583]
Morale is fading too fast after combat ends or flee is being used.
There should be a 3s ish delay.

e.g. on live I was able to use flee and still champion's challenge someone before morale drops. On RoR it instantly drops after flee is being used.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
