### ISSUE TITLE
Demonic Infestation

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#2584]
If you click to place just out of range by error the ability goes on cool down but no demon gets placed.

Demon also explodes if next to corpses, inside dissolving mist

Also doesnt seem to have a skin mesh on it as of today, its just a lattice body 

![untitled11](https://cloud.githubusercontent.com/assets/16200780/12060827/c9ff3110-af45-11e5-92d7-86d579269dbd.png)

**Comment by Evildoor** [comment]
First problem is known: #1118
