### ISSUE TITLE
Engineer/Magus = Redeploy/Resummon still not functional.

### ISSUE THREAD

**Issue by Povel** [WarEmu/WarBugs#2589]
These abilities still do not function properly and will most of the time leave your turret/horror in place where you summoned it without moving it to your location when you use the respective skill of each of the 2 classes.

**Comment by Torquemadra** [comment]
working on my engi in pve with no fails so far.

**Comment by peusnaugrim** [comment]
Its work but if you use the tactic "extra ammo" that give action point he didnt work after redeploy. sad we have to re summon another turret... can you fix it?

**Comment by Torquemadra** [comment]
Mine works pve with redeploy and with extra ammo tactic still working even when redeploying from a great distance

**Comment by Soulwhisper** [comment]
I noticed that Inside Suskarg Caves in Troll Country couldnt redeploy not even a single time! I tried redeploying over 30-35 times but non worked.

**Comment by Zegreiart** [comment]
When using Resummon to move the Pink and Blue Horror (the only two horrors I got so far) they disappear and do not reappear to the supposed relocation while out of combat.

While in RvR and in combat I could relocate the Pink Horror, didn't try to move the Blue Horror.

I can replicate the failure to move both of them while out of combat. While moving them, they disappear and the buff that builds up begins to deplete.

**Comment by ozarmidrashim** [comment]
Closing because Redeploy and Resummon were rewritten not long ago with new position code. If issues persist, make new report.
