### ISSUE TITLE
Highpass Cemetary SC

### ISSUE THREAD

**Issue by Simmox** [WarEmu/WarBugs#2590]
Noticed in T3
the crypts can no longer be capped,ie you cant interact with them any more
thus no points can be gained
makes for a long SC as combat killsare the only way to score points
first noticed this morning,and still the same about 12 hrs later

**Comment by noisestorm** [comment]
Yep, both tombstones are missing their covers hence nothing clickable there.

**Comment by Povel** [comment]
+ 1
