### ISSUE TITLE
Buffs don't scale past 11 mastery points

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#2594]
Every mastery point spend in a tree should increase your buffs by a certain value. However this stop for every buff I tested past 11 mastery points.

Here a few examples:
Chosen/KotBS Resists Aura:
11: tooltip 302, actual buff 302
12: tooltip 311, actual buff 302
13: tooltip 321, actual buff 302
14: tooltip 330, actual buff 302
15: tooltip 340, actual buff 302

Toughness Aura:
11: tooltip 96, actual buff 96
12: tooltip 99, actual buff 96
13: tooltip 102, actual buff 96
14: tooltip 105, actual buff 96
15: tooltip 108, actual buff 96

DoK Armor Covenant:
Armor Cov:
11: tooltip 528, actual buff 527
12: tooltip 544, actual buff 527
13: tooltip 561, actual buff 527
14: tooltip 577, actual buff 527
15: tooltip 594, actual buff 527

I have the feeling that all buffs are affected.

**Comment by ozarmidrashim** [comment]
It's because a buff's level can no longer exceed the target's level. 15 points in a path gives you a level 36 buff.

**Comment by ozarmidrashim** [comment]
Fixed.
