### ISSUE TITLE
Change Appearance Bug

### ISSUE THREAD

**Issue by akkzilla** [WarEmu/WarBugs#2595]
After recently acquiring Stalker's Shoulders, Boots and the Devastator Skully, even though all three pieces say they're changeable, when attempting to change them to Outlaw's Sholdaspikes, etc. it says the Outlaw's Sholdaspikes, etc. cannot be used to customize the appearance. Am I missing something or doing something wrong or is this a bug? Thanks.

**Comment by Evildoor** [comment]
Outlaw's Sholdaspikes are not bound to player and have no "Alternative appearance available" flag, right?

**Comment by akkzilla** [comment]
Correct. I recently saw another Choppa using the same Stalker's shoulders and had the Outlaw's Sholdaspikes as the alternate appearance. I tried doing the same yet it gave me that message. Could it be perhaps because the Stalker shoulders have a talisman in them?

**Comment by Torquemadra** [comment]
There is a method to go around the system and change appearances of items not flagged and to use the appearance of said items as a appearance as well. I assume known to the dev team, if not will provide details.

**Comment by ozarmidrashim** [comment]
Closing as this isn't a bug. We allow a workaround to bypass client behaviour.
