### ISSUE TITLE
Willpower stat stuck at 700

### ISSUE THREAD

**Issue by DannyWithaY** [WarEmu/WarBugs#2596]
On my level 32 zealot, I have started noticing that no matter what I do my willpower is stuck at 700. If I remove my Mark of the Spell Destroyer, my willpower decreases to 698 and when I reapply it my willpower increases back to 700 - an increase of 2, rather than the 42 that it should be - and if I pop any of my willpower potions, my willpower remains unaffected at 700. When I use the .getstat command, it lists my willpower at 700 as well. I've also noticed that as soon as I am buffed by another player my potion disappears. I have tried relogging, reloading my UI, restarting the game entirely and even restarting my machine and problem persists. 

I've definitely noticed a decrease in my overall heals so its not just a visual bug, its effectively nerfing my character into oblivion >< I can grab some screen shots if needed. Thanks!

UPDATE: after respeccing my willpower will go as high as 714 but is once again ignoring potions and my buff still isn't providing 42 willpower (16 now instead of 2).

UPDATE 2: Things are working properly on my Runepriest so this appears to be a real issue.

**Comment by Lileldys** [comment]
Seems to effect Zealots only. My Runepriest is fine. 
![runepriestwillpowertest](https://cloud.githubusercontent.com/assets/13259775/12069324/f6751fbc-b020-11e5-8cb6-ce1dca64cc51.png)

**Comment by ozarmidrashim** [comment]
Marking Dubious because you seem surprised at the idea that a Willpower potion won't stack with Mark of the Spell Destroyer.

**Comment by Torquemadra** [comment]
They stacked on live which is why my WL always took a STR buff on top of str pot in tovl, otherwise the zealot and RP buffs would be useless as no ability granted and everyone runs pots anyway

**Comment by DannyWithaY** [comment]
Yep...pretty sure they're supposed to stack. Played every heal class on live and it always stacked. Also, it stacks on my Runepriest just fine (right now) so it should be working for my zealot, no?

**Comment by ozarmidrashim** [comment]
Disinformation. I'm on live testing this right now and the paperdoll says they do not stack.

**Comment by Torquemadra** [comment]
.getstats showing stacking on rp

**Comment by DannyWithaY** [comment]
By "live" i was referring to the original game servers >< 
Also +1 Torquemadra, thanks for backing me up :)

**Comment by ozarmidrashim** [comment]
![zealot_000](https://cloud.githubusercontent.com/assets/6764164/12069518/cf14a59e-b02c-11e5-844e-69b0419d04b6.jpg)
![zealot_001](https://cloud.githubusercontent.com/assets/6764164/12069519/d14b8a94-b02c-11e5-9579-c9ba42782bcb.jpg)

Please don't press a point when you are wrong.

As I've already told you, if the client says on its paperdoll that two effects do not stack, THEY DO NOT STACK. The client uses its own rules to calculate stats, it reads the stat values from the incoming buffs and applies those rules to generate what you see in the paperdoll.

As you can clearly see, these two effects do not stack. The higher of the two is applied.

:)

**Comment by DannyWithaY** [comment]
So then why is my willpower STUCK when it should not be? Is that going to just be ignored here? Stop worrying about the potions and please help with the bigger problem :(

**Comment by ozarmidrashim** [comment]
Excuse me? First I have to waste my time providing evidence because you both decided you knew better than I did how the game works, and now you tell me to stop worrying about that and accuse me of ignoring the main problem?

**Comment by DannyWithaY** [comment]
Only because you have yet to acknowledge the main problem. Not trying to cause trouble, I just want to be able to heal properly again.

**Comment by Thorgatin** [comment]
Potions stacked NEVER on the old mythic server(s) with any buffs. There was once a (mythic) dev discussion to make an exception for engi/magus self armor buff and nothing else.

Next time better get your "facts" straight, before wasting precious dev time...two people talking wrong stuff, doesn't render it automatically true.
And the wording in this "bugreport" is absolutely inappropriate; the devs are not your bugfixbots Mr. willpower stacker...
I would simply ignore this until you learned how to express yourself in an appropriate manner to someone who fixes this game in his free time...

**Comment by Evildoor** [comment]
Problem 1: potions and buffs not stacking - not a problem, it was this way on live, we have proof via client numbers.
Problem 2: stuck willpower - tested on dev, it works fine and goes over 700, and over 714 too on lvl 32 Zealot. If this problem really exists then there are some unknown conditions.
There is also problem 3, but i'm afraid that it cannot be solved by performing some fixes on the server side, or even the client side. However, the way to deal with it was outlined pretty clearly by Aza and Thorgatin, so i can save myself the trouble.
No more problems found. Closing.
