### ISSUE TITLE
Dwarf C5 Rally Master inf rewards

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#2597]
are not select able, I have the influence but no way to select reward.

![untitled 11](https://cloud.githubusercontent.com/assets/16200780/12069530/d1890352-b003-11e5-87be-571b3cab1235.png)

**Comment by Evildoor** [comment]
General problem. You need to unlock the chapter in your ToK.

**Comment by Torquemadra** [comment]
This isnt a ToK issue though the area does have one, applied all ToK to character, all influence on test and still unable to obtain influence rewards from him.

**Comment by Soulwhisper** [comment]
Fixed @Luth-RoR
