### ISSUE TITLE
Slayer level 29 morale ability "untouchable" 

### ISSUE THREAD

**Issue by sb220** [WarEmu/WarBugs#2598]
The ability is supposed to raise your dodge, disrupt and parry to 100% for 5 seconds, but at the moment it simply multiplies your current values somehow. 
My level 29 slayer with 2% disrupt, 0% parry and 0% dodge becomes a dismal 6% disrupt, 0%parry and 0% dodge for 5 seconds in scenarios.

**Comment by Torquemadra** [comment]
Is this just showing on paperdoll or also on .getstats?

**Comment by sb220** [comment]
On paperdoll my disrupt did raise by 4%. I don't know about getstats.

What got me curious to begin with was that I took normal damage (focused) and died immediately after using the morale.

**Comment by Tiggonos** [comment]
does the tooltip read "by 100%" or "to 100%" ?

**Comment by Evildoor** [comment]
Tooltip says "by 100%", and on live that meant by flat 100%, not by 100% of yours (i'm talking about combat effect, dunno about paperdoll).

**Comment by ozarmidrashim** [comment]
![medina_000](https://cloud.githubusercontent.com/assets/6764164/12070832/a7fa876a-b083-11e5-9a6c-6694adc71bee.jpg)

**Comment by Tiggonos** [comment]
if its "by 200%" its not meant to be "at 100%". I know Mythic Devs had big problems understanding the mathematical % scheme in many ways. "By 200%" means: if it was 2% it will be 8% with the moral and gets deducted by the "ignore parry/dodge/disrupt" modifier of your attacker. Aza hits a -20lvl mob, so i think the -modifier of it is 0 and i guess he has about 20% parry on that slayer making it nearly 100% parry. In PVP you will prbly. never get 100% parry. If devs wanted 100% they called it "defends all attacks" or similiar.

**Comment by ozarmidrashim** [comment]
It's by 200% to prevent it from being reduced below 100% by "virtually undefendable" attacks.

**Comment by Toldavf** [comment]
This ability is not working as described and its not working how i remember it working from live it shoul be doubling defence chance not increasing them to 200%
