### ISSUE TITLE
"Into the fire" - Nordland

### ISSUE THREAD

**Issue by loonbg** [WarEmu/WarBugs#26]
http://warhammeronline.wikia.com/wiki/Into_the_Fire

What i change : `Speak with Lanric 0/1` to `Speak with Lanric`

`INSERT INTO quests_objectives (Entry,ObjType,ObjCount,Description,ObjID,Quests_Objectives_ID) VALUES (30362,1,0,'Speak with Lanric',113,'');`

**Comment by Reggaewaldo** [comment]
This has been changed in the DB so that the Speak to condition is now set. Change will roll over with next hotfix.

Closing.
