### ISSUE TITLE
[Engineer] Barbed Wire - not working

### ISSUE THREAD

**Issue by Bykster** [WarEmu/WarBugs#2604]
Hello,
Barbed wire is not working at all. There isn't also animation for skill.

Description: You fling coils of barbed wire all around you, rooting all enemies within 30 feet in place for 5 seconds. There is a 50% chance of the root breaking with every hit.

Best regards and good luck with it.
Bykster

**Comment by ozarmidrashim** [comment]
![engineer_001](https://cloud.githubusercontent.com/assets/6764164/12070844/8f5e77ce-b084-11e5-834a-1d44eb4e38e7.jpg)

**Comment by ozarmidrashim** [comment]
Given the number of apparently false reports I'm seeing in the last few days, I'm going to have to start demanding video evidence from people claiming core skills don't work.

**Comment by HtGeist** [comment]
It does work but launches very delayed just like sorc root,got barb wired after i killed the engi bout 2/12 secs after he did the animation,it seems you dont hit people directly in melee with you,but people behind and further away gets rooted fine...its buggy with delayed launch(aka certainly not insta and bad sync on area of effect seems not centered directly on you.

**Comment by ozarmidrashim** [comment]
There's nothing I can do about the delay of any skill under heavy server load or lag.

**Comment by Bykster** [comment]
Sorry I didn't tryed it on mobs, I tryed it during rvr and it didn't work. It's probably like HtGeist said. Thanks for feedback anyway. 
BR

**Comment by HtGeist** [comment]
goofed around high pass with a chosen and tested his cone stagger me on am and another am jumped forth and back and he would cone stagger to test bug,almost as a rule the am jumping infront full stagger immunity but no staggering and the guy behind got the full hit.we tried me infroont jumping and other guy...person in front just getting full free immunity with no stagger...i suspect the aoe root has same bug.

**Comment by Simmox** [comment]
Barb wire certainly has no animations at the moment
