### ISSUE TITLE
SC Rewards when teleporting out of scenario

### ISSUE THREAD

**Issue by Zanilos** [WarEmu/WarBugs#2607]
If you book out of SC you still get the tokens when the SC ends.

**Comment by Zanilos** [comment]
Just seen Aza forum post, I'll grab some screenies.

**Comment by Zanilos** [comment]
![screenshot_001](https://cloud.githubusercontent.com/assets/16420518/12071100/aa49c6da-b091-11e5-9006-ceec199d601c.jpg)
![zaneng_001](https://cloud.githubusercontent.com/assets/16420518/12071101/acbb4150-b091-11e5-90df-05bdff2dad72.jpg)
![zaneng_003](https://cloud.githubusercontent.com/assets/16420518/12071102/ae7202ea-b091-11e5-9638-d1c4e018518f.jpg)


The first one is me leaving, the second I have left using BoB, third is getting reward. You can see in chat window.

**Comment by Evildoor** [comment]
Not only are you getting rewards at the end of the scenario, you can also roll on dropped items.
