### ISSUE TITLE
detaunt skill not being applied but still using gcd when not facing target

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#2608]
it seems the detaunt is a "shout" when it states its a skill on your target. according tooltip facing your target is not a prerequisit of detaunt on wp. (target being in range and los is a prerequesit therefore the skill goes to red an is not usable). So either it needs to get red when you dont face your oponent (so skill cant be used) or it needs to get aplied to your target without need to face it.

this also applies at least also to runepriest detaunt.

**Comment by Tiggonos** [comment]
to ad: when you stand still, the char turns to the target to detaunt it. but you mostly run away from target when you want to detaunt it. see video.

http://vitus.wmp.media/sonstiges/vitus/wp-detaunt.mp4

**Comment by noisestorm** [comment]
Not just happening for WP, but thats an issue with all detaunts. I was talking with @ozarmidrashim about that some **long** time ago, but i didnt find proof of it for being a 360° spell back then.. So currently it is handled like a normal cone spell which has 180° and therefore you need to face your target. 
PS: Every spell that has a cone lets your char auto-face your target like in your video so thats nothing special.

**Comment by Tiggonos** [comment]
the video should just proof that the gcd is triggered despite the detaunt not being aplied. i can live with the prerequisit that you need to face the target (though i think its wrong) but then the spell shouldnt be usable when not facing your target. (just like spine breaker for example is greyed out when you not behind your target).

**Comment by noisestorm** [comment]
Yea i get what you mean.The problem with gcd on spells is on EVERY cone spell though as well and not just Detaunt. Especially visible if you try to kite with ranged dps and see that a lot of spells dont even work unless you jump midiair to turn and fire them off.

**Comment by ozarmidrashim** [comment]
Confirmed. Single-target detaunts will no longer require facing.

**Comment by Tiggonos** [comment]
Love you

**Comment by Tiggonos** [comment]
comitted as of 06.01.
