### ISSUE TITLE
Problem with one character: game often crashes, character cannot log in for 30+ minutes

### ISSUE THREAD

**Issue by OldPlayer** [WarEmu/WarBugs#2609]
I'd like to inquire what to do in a case when just one character has the following problem:
1) The game crashes (during zone change or just because it wants to)
2) Character cannot load in, using /stuck repeatedly during loading screen sends him to starting zone, but it cannot load up.
3) Character can be loaded after 30-60 minutes of repeated tries, restarts, PC restarts etc.

The same character has a strange problem with quests. Quests often become invisible after zone change, ie. Tome of Knowledge questbook is empty. Quests do work and kills are counted, but I cannot find out if quest is done or not unless I go to the quest giver.

Very rarely (once per total crash max, usually it does not appear) the following message appears at Launcher start:
Data.myp:
System.Exception: You need to stop application currently using the following file: data.myp
   v MYPHandler.MYPHandler.WriteFileToArchive(FileInArchive archFile, MemoryStream MS)
   v MYPHandler.MYPHandler.ReplaceFile(FileInArchive archFile, FileStream newFile)
   v RoRLauncher.Client.UpdateWarData()

Other characters work well, only one seems to be cursed.

Can you help me, please?

**Comment by Evildoor** [comment]
This problem is not related to a server and does not belongs here. Maybe forums can help.
