### ISSUE TITLE
Bugusing at Reikland factory sc

### ISSUE THREAD

**Issue by Doomsday82** [WarEmu/WarBugs#2612]
![keylle_001](https://cloud.githubusercontent.com/assets/13207459/12072460/a5943c74-b0f0-11e5-863a-cd2c31e01154.jpg)
Some engi using bug with Guards at destro side and goes to wc.

**Comment by dedoan** [comment]
It's me, it's very simple i see when you taunt a guard in your guard, this guard don't repop after dead and it's possible go in warcamp des for farm

**Comment by dedoan** [comment]
i thinks you create a timer for repop guard

**Comment by Evildoor** [comment]
Should be fixed (12th March patch).
