### ISSUE TITLE
G13 Invisible Buff Monster

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#2613]
Appeared at Stone of Imrathir public quest, my wife was running all out assault to get my baby Kotbs influence fast and I guess it picked up the agro of this thing as it was attacking us and gave quite a lot of xp.

![svanah_000](https://cloud.githubusercontent.com/assets/16200780/12072892/51e252da-b0ca-11e5-8756-0dfe89138ee7.jpg)

**Comment by Ryanfawkez** [comment]
Reason it gave so much experience was because it's level 27. Considering you killed it with ease with 2 (from what i can tell) low-level tanks, it has been removed for the time being. Fixed in next patch.
