### ISSUE TITLE
[Quest]: The Harvesters

### ISSUE THREAD

**Issue by Heteryk** [WarEmu/WarBugs#2617]
Acording to this page 
http://war.mmodb.com/quests/the-harvesters-2962.php
we are missing here some objectives to do.
Also it may be just me but I couldn't find Scoruis the Awakener. 
EDIT: I have to check one more place for Awakener. (quest is marking two areas on the map).
EDIT2: Awakener is one the second location but he's duplicated (at least two of them there).
![rahgal_074](https://cloud.githubusercontent.com/assets/16116091/12074346/d49bc160-b14d-11e5-8880-edacbc737794.jpg)

**Comment by Ryanfawkez** [comment]
The online database entry seems flawed to me. The quest description states only to kill the Harvesters of Decay and Scorius the Awakener, as the quest currently functions.

I've removed the duplicate spawn, and also added in two Harvesters of Decay to make the quest less of a hassle to do. Scorius remains at his original position though, as marked by the quest.
