### ISSUE TITLE
SM Guard

### ISSUE THREAD

**Issue by Zanilos** [WarEmu/WarBugs#2618]
It's been reported to me that SM guard ignores ignores GCD. 
From what i have been shown, it sure does.

**Comment by ozarmidrashim** [comment]
All versions of Guard should have the same issue.

**Comment by Zanilos** [comment]
On second look it would seem that you all tanks have this. Please wait until tomorrow for me confirm, unless you have tested.

**Comment by Tesq** [comment]
chosen too, maybe is due how buff are applied in ror, wp/dok buff also work this way

**Comment by taccr** [comment]
I see no issues with guard on my KotBS. What exactly are you guys experiencing?

**Comment by Zanilos** [comment]
On live it was 1 GCD to apply, 1 GCD to remove and so on. In RoR we can just flash guard. So if your hotkey clicking is quick enough you can remove and re apply GCD in less than 1 GCD.

As you said, it effects all guards.

**Comment by Evildoor** [comment]
IIRC it was 1 GCD to apply, but no GCD to remove (like simple buff).

**Comment by ozarmidrashim** [comment]
The hotbar corroborates Evildoor's post - Guard doesn't trigger a GCD when the client removes it. Unsure what to do.

**Comment by Zanilos** [comment]
That does sound familiar tbh. I'll check some old videos...

**Comment by Zanilos** [comment]
https://www.youtube.com/watch?v=e9IjLZ9UlhE

@5:53 there is guard swap. Like you said, no GCD to remove, but definitely 1 GCD to apply

**Comment by taccr** [comment]
The current implementation is correct. Removing guard does not use up a gcd - only applying does.
You can swap guard in one gcd.
