### ISSUE TITLE
Stalker's scorchguards - no set bonus

### ISSUE THREAD

**Issue by hoppolek** [WarEmu/WarBugs#2619]
The BW Stalker's Scorchguards does not give stalker set bonus. The set wants them named Stalker's Scorchguard without the s at the end.

**Comment by Tiggonos** [comment]
this is just a visual bug. stat bonus is applied.
![martock_029](https://cloud.githubusercontent.com/assets/13809443/12079371/a59bd884-b236-11e5-94cf-67bb2ae5f60e.jpg)
![martock_030](https://cloud.githubusercontent.com/assets/13809443/12079372/ac99a468-b236-11e5-9a11-7299231ef3bb.jpg)

**Comment by genisaurus** [comment]
Fixed in next patch.
