### ISSUE TITLE
Squigherder pets

### ISSUE THREAD

**Issue by HtGeist** [WarEmu/WarBugs#2620]
Time to take a good long hard look at squigherder pets,they way they get inside closed keeps,shoot straight thru scenary ignoring line of sight and the dmg they do is like 3 times what they did on live..needs to be toned down to a more balanced level,seems the dear spike pets forget they do physical dmg and thus armor buffs/engi flak jacket should reduce it significantly,gas squigs standing in melee range but unattackable with anything but ranged attacks etc,makes these already annoying (profanity) even more annoying,borderline powerful.

**Comment by Evildoor** [comment]
"dmg they do is like 3 times what they did on live" and other things regarding damage - proof?
Everything else - general problems with all pets and NPCs which cannot be fixed yet.

**Comment by HtGeist** [comment]
well my SH on live running around t3 with 750 bs the squig would hit an AM with armor pot  for 50-70 pr spike flung with the squigfrenzy anything remotely tankish got 30-40 dmg and toughness  tanks 10-20 which made me solely play sh for the humor part of it,but here in RoR those pesky buggers fling away 150 dmg spikes ever so happily on my engi with 42% dmg reduction from running with flak jacket buff...seems over the top compared to his own very immobile not terrain ignoring turret does 1/3 with no way to boost it.

**Comment by bloodi** [comment]
By proof he means, screenshots, links to old sources, calculations, etc.

Not just some random "i remember them doing less" and a pitiful comparision to the turret of the engi.

**Comment by HtGeist** [comment]
Ofc i want to do more dmg,i am dps and i am partially glass cannon with high main stat and abilities that debuff my dmg type,i SHOULD do more dmg,but i am not hence the bug report uhm where did my dmg go? because i figure the problem is in the scaling of grenade magic dmg with ballistic skill as stand in intelligence for magic dmg,is not properly coded and acid bomb not reducing/debuffing as should. but squig herder pets seem to have gotten a very generous scaling is what i notice time and time again,since more and more play them...guess why they have WL burst with ranged atm...

**Comment by Torquemadra** [comment]
Pet damage is "higher" than live due only to the remembrance of all the free end game armour which had such massive armour values they rendered pet damage a triviality.

**Comment by Evildoor** [comment]
No solid information provided, closing.
