### ISSUE TITLE
Possible bug: Can be punted on top of houses in Nordenwatch

### ISSUE THREAD

**Issue by foxbeep** [WarEmu/WarBugs#2621]
Just had this happen and although I don't think it's game breaking it doesn't seem fair. I had just hit Whirling pin and was flying away from a destro player when a chosen punted me on top of this house.

![laerith_031](https://cloud.githubusercontent.com/assets/15528466/12075276/9233a962-b140-11e5-9301-f65fc19c6f92.jpg)

**Comment by Evildoor** [comment]
Terrain issues aren't bugs (c) Genisaurus
