### ISSUE TITLE
Able to get in a SC tier at higher level

### ISSUE THREAD

**Issue by Yyrd** [WarEmu/WarBugs#2622]
If your in a group at correct lvl and que with this gruop.   you can level outside the groups teir and still enter the groups SC when it pops.

**Comment by Evildoor** [comment]
Seems pretty similar to #1399.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
