### ISSUE TITLE
Players not receiving XP and RP for suicide/guard/lava kills

### ISSUE THREAD

**Issue by Sonare** [WarEmu/WarBugs#2623]
Didnt get any RR when enemy suicide (KB himself from fall)34

**Comment by noisestorm** [comment]
Next time pick some adequate name for the issue, not a meaningless title like you had,

**Comment by Tesq** [comment]
it seems the case, i also recived kill by myself, no killing blow should be recived by still it should the renow/exp for the contribution.

**Comment by Evildoor** [comment]
#1673
