### ISSUE TITLE
Game Crashes while joining warband in a different location

### ISSUE THREAD

**Issue by saupreusse** [WarEmu/WarBugs#2624]
My Game crashes/closes everytime i click on the join button for a warband.

**Comment by Zanilos** [comment]
Are you in Altdorf when you join?

**Comment by saupreusse** [comment]
yes

**Comment by Zanilos** [comment]
That's the issue, there is a problem if you accept WB invites while in AD.

**Comment by Kouba85** [comment]
I have the same problem and if i turn off game via ctrl+alt+delete and task manager than log on. Everything goes and in Altdorf too. Sorry for my bad english.

**Comment by vove-RoR** [comment]
This might as well be connected with full warbands that appear as wbs with free slots in them. Crashed myself this way few times.

**Comment by Kouba85** [comment]
So another solution try first join sc and than wb and after this leave que for sc. For me is functional too.

**Comment by phsampaio** [comment]
I am having the same problem, leaving Altdorf before joining a WB is a temporary solution. Worked for me.

**Comment by SecretsOTheP** [comment]
This is not just limited to warbands. Additional information, including some client debugging info is listed below.

#10461

**Comment by SecretsOTheP** [comment]
The internal representation of the group window looks like this when a player is added to a group and the crash occurs:

> 0019575c db 57 19 00 21 00 00 00 1f 00 00 00 02 00 00 00 0c c8 a7 00 9c 57 19 00 29 0b a3 00 ff ff ff ff a8 57 19 00 56 e7 4a 00 be 06 04 e7 21 00 00 00 bd 00 00 00 04  .W..!................W..)........W..V.J.....!........
00195791 fd 19 00 01 00 00 00 21 00 00 00 ec fd 19 00 74 92 a1 00 ff ff ff ff 08 fd 19 00 88 f8 4a 00 be 06 04 e7 00 00 00 00 2b 01 00 00 d9 57 19 00 60 38 8e e6 d0 81  .......!.......t.............J.........+....W..`8....
001957c6 eb df 00 00 00 00 00 00 00 00 00 00 00 00 10 00 00 00 be 06 04 e7 34 d5 b9 2c eb 7d 00 98 dd 2a 91 85 01 00 d4 ba 2c c7 8f 01 00 c9 9b 2a c9 8f 01 00 00 00 49  ......................4..,.}...*......,......*......I
001957fb 20 64 75 6e 6e 6f 20 6c 6f 6c 8a d9 03 c6 e3 05 b2 90 01 27 25 05 40 01 02 12 01 00 64 00 98 dd 2a 0f 16 01 1d 00 03 01 00 00 01 05 00 00 00 48 72 61 6e 64 0b   dunno lol.........'%.@.....d...*..............Hrand.
00195830 00 00 00 49 20 64 75 6e 6e 6f 20 6c 6f 6c 8e 8c 06 82 cd 07 90 92 02 27 25 05 40 01 02 a0 02 01 64 64 02 d4 ba 2c 0f 2d 04 17 00 14 01 00 00 01 07 00 00 00 45  ...I dunno lol.........'%.@.....dd...,.-............E
00195865 6c 76 69 72 61 61 0b 00 00 00 49 20 64 75 6e 6e 6f 20 6c 6f 6c c0 8c 06 ac ce 07 90 92 02 27 25 05 40 01 02 c4 02 01 64 64 01 c9 9b 2a 0f 10 01 1c 00 01 01 00  lviraa....I dunno lol.........'%.@.....dd...*........
0019589a 00 01 08 00 00 00 48 72 65 74 68 67 61 72 0b 00 00 00 49 20 64 75 6e 6e 6f 20 6c 6f 6c 90 8d 06 94 ce 07 90 92 02 27 25 05 40 01 02 c4 02 01 64 64 13 0a 53 75  ......Hrethgar....I dunno lol.........'%.@.....dd..Su

**Comment by SecretsOTheP** [comment]
WAR.EXE!004c48d

This is in the packet handler for the game client, also a place where the game crashes and present in the call stack when it does. So it's definitely crashing on a type of  F_CHARACTER_INFO and doesn't like the data its being sent. It may be a good idea to start logging F_CHARACTER_INFO if the crash can be reliably reproduced in a dev environment.
