### ISSUE TITLE
Shatter/Sever always remove 1hour buffs first

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#2626]
Shatter Enchanment and Sever Blessing currently remove the 1 hour buffs first.
I'm not sure how it was on live but this looks very inconsistent.

I think it should remove a random buff.

(Tested with Shaman Resists and Zealot Marks)

**Comment by Torquemadra** [comment]
There was some system on live but I don't recall what it was, my biggest annoyance with the thunderstout debacle wasn't the large stat boost but the fact that stacking served as a shatter block.

**Comment by Evildoor** [comment]
Seems correct to me - first applied, first removed.

**Comment by ozarmidrashim** [comment]
Removal abilities are FIFO.

**Comment by danissrv** [comment]
I also remember that on live the shatters were removing a random buff. 
Imo this is better than fifo cause it's very easy to mask important buffs...

**Comment by Evildoor** [comment]
Closing since taccr's question was answered. If someone dislikes current cleanse handling - they should use forums.
