### ISSUE TITLE
Kiss of Agony/BBoP Initiative Debuff Issue

### ISSUE THREAD

**Issue by SirBattosai** [WarEmu/WarBugs#2628]
Hey there!
KoA currently removes/adds only 54 initiative instead of 72 when fully commited to the respective mastery line, when i tested it on my wich hunter with BBoP, the latter worked just fine and actually removed/added 72 initiative with 15 pts spent into the tree.

screenshots:
http://imgur.com/a/4gb5e

**Comment by taccr** [comment]
Pretty sure it got scaled down to the mobs level. Have you tried it on a higher level player or mob?

**Comment by Tiggonos** [comment]
https://github.com/WarEmu/WarBugs/issues/2594

should be fixed though?

**Comment by SirBattosai** [comment]
i tested it on same level mobs and on players r32 respectively yesterday and while the WH received and debuffed 72 initiative the WE did only receive 54 and debuff 54 - not sure if it got adressed in this hotfix.
