### ISSUE TITLE
[Quest] The Threat Revealed

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#2630]
Have to find signs of the missing high elves, found prison camp, slaughtered everything within a 2 mile radius, clicked the cages and the people within  and cant seem to find a way to complete this.

Ignore it was the shackles I had walked over 100 times, quest is working

**Comment by Torquemadra** [comment]
1) I am unaware of the nuances of this logging system or your personal preferences, tools I have used previously dictated a new ticket after a previous one was closed for tracking purposes. I am not out to make extra work for anyone and am fairly conscientious with what I log. Including revisiting after logging just in case or if futher information shows up.

2) Missions is completed, totally and utterly. Cannot find a relevant NPC to hand in said quest in High Elf Chapters 9, 10 or 11. Other people having same issue which is why I got a tell in game regarding it due to this previously logged report, then checked character and saw it was completed but I never handed in.

![svanne_008](https://cloud.githubusercontent.com/assets/16200780/12474139/9e64daa8-bfe6-11e5-92da-0f635abc8f84.jpg)

**Comment by Evildoor** [comment]
2) Now the point is valid. Reopening.
1) Without clarified 2 it was unclear that the problem is different. Also, we prefer to gather info related to one thing (quest in this case) in one report, unless the problems in question are completely different.

**Comment by Torquemadra** [comment]
Again, I was unaware how the system functions and presumed as lacked the power to reopen past tickets myself they would remain off the radar or peoples action lists.

Quest starter is Sethys Stormwalk and I believe originally ended the quest line with her as was originially a 6 part line with a shoulder reward at end. There is no functionality to handing in here.

![svanne_009](https://cloud.githubusercontent.com/assets/16200780/12474516/ccee05c2-bfe9-11e5-83c2-5e12bd9d80c2.jpg)

**Comment by DanaBloodkiss** [comment]
Will open a new ticket. https://github.com/WarEmu/WarBugs/issues/3915
