### ISSUE TITLE
Block Rating

### ISSUE THREAD

**Issue by Symbelmyne** [WarEmu/WarBugs#2632]
While playing Kotbs i`ve noticed that no matter which shield i wear my block % is not changing (besides value got from Renown Traning). I`m not sure it suppose to be like that.
![screenshot42859](https://cloud.githubusercontent.com/assets/16525371/12078616/2dca9e28-b211-11e5-8dfe-608678825a39.jpg)
![screenshot44078](https://cloud.githubusercontent.com/assets/16525371/12078617/34f68d10-b211-11e5-8107-a79820193be8.jpg)

**Comment by Evildoor** [comment]
#2258
