### ISSUE TITLE
Leveling on chickens

### ISSUE THREAD

**Issue by sharkenator** [WarEmu/WarBugs#2633]
Few days ago my friends and I noticed a leveling bug. If you have high level characters, you can easily boost opposite faction players by feeding them with chickens in empty RVR zones so they just pass T1 or even T2 if you have enough time. If you relog, renown and experience that you get from killing a chicken is reset.  All you need is just feed - relog - feed - relog...
I think it kills the spirit of WAR and should be fixed.

**Comment by Renork** [comment]
May I suggest removing this from the bugtracker so that others don't take advantage of it before it gets fixed? This is one of those bugs that you can do many things with (I Pm'ed Aza how this bug works.

**Comment by taccr** [comment]
It's not just chickens. You can abuse the relog-resurrect anywhere. Already submitted a video of 3 people RR/Medal farming this way.

**Comment by Renork** [comment]
killing a chicken takes 1 hit and is a lot faster, which is not the same as the above ^ that should be a separate report.

**Comment by Evildoor** [comment]
Fix already implemented, but not pushed yet @ Aza
So no need to remove.

**Comment by Renork** [comment]
Excellent, I'm sad for the t1 influence but hey it needed to be fix eventually :>
