### ISSUE TITLE
Respec Costs

### ISSUE THREAD

**Issue by Sabacik** [WarEmu/WarBugs#2636]
There are different respec costs in different places.

When I want to do mastery respec in IC (trainer in the Monolyth) it costs 5.80 if I do it in Chrace (in the RvR WC) it cost 3.60.

**Comment by Luth-RoR** [comment]
Are you sure you had the same amount of mastery points spent? The price is calculated per mastery point spent.

**Comment by Zealote** [comment]
You're probably right, Luth:

![respec costs 1](https://cloud.githubusercontent.com/assets/10598420/17459511/37582998-5c33-11e6-9f2f-90e76c069de4.png)

![respec costs 2](https://cloud.githubusercontent.com/assets/10598420/17459512/3963dc64-5c33-11e6-9efa-344ee107fec0.png)

**Comment by Luth-RoR** [comment]
Thanks, i close it then.
