### ISSUE TITLE
Renown/хр/emblems sc reward duplicating.

### ISSUE THREAD

**Issue by Doomsday82** [WarEmu/WarBugs#2640]
![keylle_001](https://cloud.githubusercontent.com/assets/13207459/12079158/62f12372-b240-11e5-8c8c-9acb16b953b3.jpg)
![keylle_002](https://cloud.githubusercontent.com/assets/13207459/12079161/6fda9c80-b240-11e5-929f-d278ba5e4c5c.jpg)
Same with 600rp winning rewards etc.

**Comment by Doomsday82** [comment]
More
![keylle_004](https://cloud.githubusercontent.com/assets/13207459/12092674/a088dea8-b30f-11e5-99ab-d52c73213243.jpg)

**Comment by Jojo1337** [comment]
happens quite frequently to me too. 

![jojoo_011](https://cloud.githubusercontent.com/assets/15436264/12113122/0cd70e40-b3a1-11e5-8c7a-ea8bc0318eee.jpg)

I don't know what triggers that, but the second tick comes like 1-2 minutes later. i guess when the 2 minute timer runs out which starts when the sc is over and the sc info popup is showing?
