### ISSUE TITLE
chosen missing t2 rvr inf rewards

### ISSUE THREAD

**Issue by M0rf** [WarEmu/WarBugs#2641]
Tier 2 empire/chaos - 2nd reward - currently 4 jewels of which 2 are duplicates, should be 2 shields and 2 jewels.
Tier 2 elf/dark elf - 3rd reward - missing purple 2h axe.
Tier 2 dwarf/greenskin - 3rd reward - missing purple 2h axe.

Sadly couldnt find the name, wiki doesnt show chosen inf rewards but they existed not long ago so hopefully you dont have much trouble putting them back in.

**Comment by Ryanfawkez** [comment]
I will look into these items and fix them accordingly.

**Comment by Ryanfawkez** [comment]
The 2hand axes for the Chosen are still in the database as well as in MySQL, not sure why they aren't showing up in the ToK.

**Comment by NorKalli** [comment]
Long since fixed
