### ISSUE TITLE
join warband + join sc bug

### ISSUE THREAD

**Issue by Kouba85** [WarEmu/WarBugs#2642]
Hallo,

sometimes when i join open wb it shows me party is full.
![snorrri_017](https://cloud.githubusercontent.com/assets/15944509/12079294/df27b95e-b233-11e5-94de-1dc5c028b2cf.jpg)
![snorrri_018](https://cloud.githubusercontent.com/assets/15944509/12079297/eabd8992-b233-11e5-8889-d6eab1b91e55.jpg)

so after this i try to join Scenario and chat writes to me that i am in warband so i must leave warband but i am not in. 
![snorrri_019](https://cloud.githubusercontent.com/assets/15944509/12079305/1a82809c-b234-11e5-955d-5eaac5a4f0ba.jpg)

**Comment by vove-RoR** [comment]
Being locked in a wb seems to occur when many people try to join the same warband at the same time. As a result you are not "physically" in the warband but you are in it "logically"- you can see warband's composition in party options etc. but you are not in it. You cannot leave, the only solution is to relog.

**Comment by Kouba85** [comment]
BTW i found another solution to this. I join another wb it must be t1 i don´t know why but its functional. Than leave this t1 wb and than is everything functional. So i can join wbt3 and scenarios too.

**Comment by Evildoor** [comment]
I presume that this is #2625.
