### ISSUE TITLE
Get into Gnol Baraz Keep as Destro

### ISSUE THREAD

**Issue by saupreusse** [WarEmu/WarBugs#2644]
You can easily get into Gnol Baraz Order Keep as a destro if you use this hidden path....
tis really annoying because you get a whole warband into the keep without attacking the front gate.
You can kill all order in there or just stand on the mountains and shoot at them with ranged dps.
Here is the link to the video i made:
https://www.youtube.com/watch?v=p5niSST6-xY

Greetings!
Saupreusse

**Comment by saupreusse** [comment]
Pls make this high priority its soo annoying and can be fixed easily

**Comment by DanaBloodkiss** [comment]
Should be fixed in next. Thanks!
