### ISSUE TITLE
Abnormal DoT ticks

### ISSUE THREAD

**Issue by bloodi** [WarEmu/WarBugs#2645]
This tick happened just as the scenario ended, obscuring the names because i am sure it was not intented and just a weird behaviour.

http://imgur.com/TLE1nJO

I dont think Signal Flare should be doing 3k ticks.

**Comment by Thorgatin** [comment]
In which scenario did it happen?

**Comment by bloodi** [comment]
Gates Iirc

**Comment by taccr** [comment]
Might be related
http://s017.radikal.ru/i428/1601/76/1c0dd5b02fff.jpg
from http://www.returnofreckoning.com/forum/viewtopic.php?f=16&t=10408&p=104008

**Comment by Ryanfawkez** [comment]
If I see it right, Signal Flare didn't simply tick for damage as it should every 3 seconds, it did the full ability damage, ignoring the 21 second duration it's supposed to have. Could be simply because the scenario ended. It's still rather weird behavior.

**Comment by diablight** [comment]
Referring to bug #4318: today this bug happened again. I onehitted a tank because enfeebing strike hits for all his life within the same gcd. I do not know how this can happen

**Comment by Evildoor** [comment]
Per my comment in #4742: i do believe that this issue (#2645) is different from #4318 and #4742:

- this issue (and few others, which are closed and linked here) describes instances of significant damage (but not excessive - it just seems that all remaining damage is done at once) from DoTs (apart from taccr's screen), but in one tick.
- #4318 and #4742 describe excessive damage from Enfeebling strike and in several ticks - i doubt that total damage from ES is enough to do that much.

**Comment by ozarmidrashim** [comment]
Should have been resolved a while ago - was an issue with ApplyDamageModifiers
