### ISSUE TITLE
Autoloot function stopped working

### ISSUE THREAD

**Issue by ropuch** [WarEmu/WarBugs#2646]
Hi,

I've noticed recently (yestaerday/today) that autoloot function has stoppped working properly.
Even with "Always autoloot" on, there's still standard loot window showing and one needs to click "Loot All" to get the items,

Not game-breaking ;-)

ropuch

**Comment by Aelice** [comment]
Auto loot stopped working, i have relogged and it did not fix it.
i have unboxed the option for auto loot and filled box again but nothing happens.

**Comment by Mazic92** [comment]
Same problem here!

**Comment by Evildoor** [comment]
Tested, autoloot works. Closing.
