### ISSUE TITLE
[Item] Imperial Hunting Hound and related bugs

### ISSUE THREAD

**Issue by SilverWF** [WarEmu/WarBugs#2654]
(Pretty sure, all of this will be the same for Destro and their event gift pet)
1. This hound do not have any skin and animation while summoned. It must have it. Tested in the Altdorf.
2. This pet can be targeted by allies and, probably, by enemies. It must not be able to taken as target.
3. (for pet classes: Engineer, Magus, Squig herder, White Lion). Tested on Engineer. If you summon your natural pet (turret), then call this event-pet, you will loose control on your natural pet and able to summon new pet.
Basically:
Summon turret - you can handle it (force it for attack etc.)
Summon hound - you loosing control on turret, but turret UI is on screen
Unsummon hound - your turret still here, but still not "yours"
Summon turret - previous turret stays in the World and seems active. You can handle your new turret.
Summon hound - you loosing control on turret, but turret UI is on screen
...
You can call any number of that turrets (and, maybe, demons, squigs, lions) and if you called all of them in the aggresive mode - all clones will attack nearby targets at the same time and will follow your attacks also! This has been tested on Engineer and 10 turrets at the same time.
This can be really dangerous of easy PVE-farm or even worse - in the PVP.
Please fix this bugs.

**Comment by SilverWF** [comment]
Warlord's Fell Hound can be targeted too - as hostile target, but cannot be attacked.

**Comment by Stavoz** [comment]
Skin is partial bug works in other zones than altdorf

**Comment by Tiggonos** [comment]
animation does sometimes work, sometimes doesnt.
