### ISSUE TITLE
[Talisman making] Portalstone

### ISSUE THREAD

**Issue by shamallow** [WarEmu/WarBugs#2659]
Hello,
there is a problem to make portalstone; it says " Bad seed data. Since the seed couldn't be generated, it has been lost ".

![portalstone](https://cloud.githubusercontent.com/assets/16374367/12089124/c4b4d594-b2e1-11e5-9ce6-cf4a4ffb4b3d.png)

**Comment by Tesq** [comment]
i add to make teleport stone like these, you only need the recipient on live
