### ISSUE TITLE
[NPC]"Vende the Traslator"

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#266]
Cannot interac with it
![tesq_016](https://cloud.githubusercontent.com/assets/7527415/3576072/b38115ae-0b8e-11e4-94c1-282b6a82553b.jpg)
![tesq_000](https://cloud.githubusercontent.com/assets/7527415/3576073/b4a8f884-0b8e-11e4-9d7c-100d548011ea.jpg)

**Comment by Reggaewaldo** [comment]
He is a game object. Is he part of a Quest or Tome unlock ?

**Comment by RoR-Zomega** [comment]
Update: he is part of a quest named "Lost in Translation".
![lost in translation](https://cloud.githubusercontent.com/assets/15970235/11605069/28b2a6a4-9aee-11e5-989b-00ea3c91d5d7.jpg)
