### ISSUE TITLE
Lvl 1 Marauder Torchbearer dropping lvl200 seeds

### ISSUE THREAD

**Issue by Kallahh** [WarEmu/WarBugs#2665]
I've just created a new char and the 1st mob I killed dropped me a lvl200 seed.

I doubt that this is working well so... just in case :P

**Comment by Torquemadra** [comment]
doesnt every mob have a chance of dropping a seed from 1-200? I thought that was a design choice

**Comment by genisaurus** [comment]
Not necessarily a design choice, but a problem with the loot system we're using at the moment. High level seeds are on the loot tables for almost all npcs.
