### ISSUE TITLE
[skill] White Lion Brutal Pounce

### ISSUE THREAD

**Issue by grotsaidstop** [WarEmu/WarBugs#2667]
Since few days the skill Brutal Pounce don't work all the time.
I'm not sure if it's a bug cause sometimes it works.

When i use it, i see the could down started then it reset and don't work.

I think that is a kd immune prevent the Brutal Pounce using, but is this case the pet can't have the bonus damage.
(sorry for my bad english)

_______________________

Depuis quelques jours le skill Assaut Brutal de la voie Gardien ne fonctionne pas tout le temps.
Lorsque je le lance, le cd démarre, se reset et ne marche pas.

Je pense que cela provient d'une immunité au kd de la cible mais dans ce cas le lion ne peut pas recevoir le bonus de dégât alors qu'il devrait le recevoir sans pouvoir kd.

**Comment by saupreusse** [comment]
maybe its lag... sometimes this happens on my SW when shooting arrows all over the place

**Comment by ozarmidrashim** [comment]
If the CD is reset, your pet is out of range on the server.

**Comment by grotsaidstop** [comment]
Ok, so if i understand, i see the pet near me, but in real not because of the lag, and the skill don't work.

Thanks for your answers. :)

**Comment by genisaurus** [comment]
Closed - issue/question addressed by Aza.
