### ISSUE TITLE
Switching language

### ISSUE THREAD

**Issue by welow** [WarEmu/WarBugs#2668]
After changing the language using the / laung 6 or 7 I do not remember , change the language to another is impossible.

Also, after reading the mail, it is still lit icon in radar that there is a letter .

My name in game - Regulaks =)

**Comment by Evildoor** [comment]
Second problem is already reported elsewhere. Next time - one report per problem.

**Comment by bloodi** [comment]
Just a heads up, it is possible to change the language again via the .ini file, so while annoying this is easily solvable.
