### ISSUE TITLE
Refuse Respawn

### ISSUE THREAD

**Issue by Karvoth1** [WarEmu/WarBugs#2670]
The Watchtower Defenders near the watchtower refuse to respawn, when enemies around them have respawned several times.

Alvar, certain Norse Pickets, and all Norse Marauders from 'The Dark One' quest also refuse to respawn (after checking back 10 hours later, at that), tested with several enemies around them respawning several times.

**Comment by DanaBloodkiss** [comment]
Still?

**Comment by Evildoor** [comment]
No confirmation, closing.
