### ISSUE TITLE
RVR/Problem with displaying of who killed you

### ISSUE THREAD

**Issue by Banzay123** [WarEmu/WarBugs#2672]
When I was on scenarios, enemy (witch hunter) used against me debuff (Fervor), I killed him in battle and died of that skill at the game issued, that I'm died by "nothing".
P.s. My English bad, ask questions, try to explain
![qua_000](https://cloud.githubusercontent.com/assets/16545971/12098681/91ab8f48-b2d8-11e5-9dff-2102e2b0722a.jpg)
![qua_001](https://cloud.githubusercontent.com/assets/16545971/12098682/91ae1646-b2d8-11e5-926e-1f62b2f41822.jpg)

**Comment by Evildoor** [comment]
Not a bug, it was the same on live.
