### ISSUE TITLE
Unsticking in Inevitable City

### ISSUE THREAD

**Issue by Walmsley09** [WarEmu/WarBugs#2673]
When unsticking in Inevitable City (especially if you get trapped in the viper pit) when logging back on you appear above the city, falling down, and past the course-way to the castle. Then upon landing in nothingness you survive, and the only option is to use rally teleport

**Comment by Torquemadra** [comment]
/stuck twice within 5 seconds will suffice as a workaround with no cooldown as well.

**Comment by saupreusse** [comment]
Same is happening if you do this while standing in a dangerous territory :)

**Comment by Evildoor** [comment]
#400
