### ISSUE TITLE
"Pulling" Abilities

### ISSUE THREAD

**Issue by Walmsley09** [WarEmu/WarBugs#2675]
It seems that the abilities which can pull targets or enemies in front of them towards them occasionally works through keep gates, and also always works through doors such as Tower BO doors and Tavern doors.

**Comment by saupreusse** [comment]
right! in the SC "lost temple of isha" i was pulled into the ruins and kept stuck in them until the end... not very funny because i could not attack anyone or being attacked by anyone.

**Comment by genisaurus** [comment]
Well-known issue, several reports made already.
