### ISSUE TITLE
Cant Connect to ror homepage with mobile device

### ISSUE THREAD

**Issue by saupreusse** [WarEmu/WarBugs#2676]
If i try to connect to http://www.returnofreckoning.com/ on my mobile phone (android/firefox v43.0) the site won't load up.
your DDosProtection by cloudflare is causing this issue.. it gives me a new ID every two seconds and tries to connect me to the homepage but I am just stuck in the DDosProtection window and my site refreshes all the time.

Greetings!
Saupreusse

**Comment by saupreusse** [comment]
I just try to do my job...  :D

**Comment by genisaurus** [comment]
This is not a bug with the game, and thus does not belong here. Moreover, it works fine with Chrome mobile.

**Comment by saupreusse** [comment]
At least now we know there is nothing wrong with the ddos protection.
