### ISSUE TITLE
Dying to get into Fangbreaka Swamp Keep

### ISSUE THREAD

**Issue by TheRealReginn** [WarEmu/WarBugs#2677]
Not sure if this has been reported, but the front entrance to Fangbreaka Swamp Keep is bugged.  While trying to enter from the front, I get a loading screen that ends up with me falling through the world and dying.

**Comment by genisaurus** [comment]
Could not reproduce on dev environment, may have been a problem with lag on live.

**Comment by saupreusse** [comment]
max hayman already said it was his fault... should be fixed in next patch ;)

**Comment by Evildoor** [comment]
Seems to be fixed.
