### ISSUE TITLE
Archmage : Balance Mending Tactic not working.

### ISSUE THREAD

**Issue by CalmVinsanity** [WarEmu/WarBugs#2678]
I've tested heal values with tactic equipped on myself and a target. Then without tactic equipped and saw no changes. No 35% more heals on allies or +15% heals on myself.

**Comment by genisaurus** [comment]
https://github.com/WarEmu/WarBugs/issues/1786, https://github.com/WarEmu/WarBugs/issues/1667

**Comment by ozarmidrashim** [comment]
-1 for false report

![celestica_030](https://cloud.githubusercontent.com/assets/6764164/12116479/fa9832e8-b3b1-11e5-837e-60ee2d08d98e.jpg)

1) HE on self
2) HE with tactic on self
3) HE with tactic on ally (lv12 so buff component is deleveled)
4) HE on ally (lv12 so buff component is deleveled)

**Comment by CalmVinsanity** [comment]
I apologize i miss understood the tactic as general healing not the skill. Thanks for taking the time to check.
