### ISSUE TITLE
skaven priest bugged with magus minions

### ISSUE THREAD

**Issue by velkos4ever** [WarEmu/WarBugs#2680]
after a lot of time i took shouting on advise for help for the quest since no answered i decided to try to kill the priest (boss on skaven event) with the minions by using only minions and not attack diractly.after 2-3 minutes by spaming minions to attack the boss bugged he was walking back and forward and i was attacking it by that time after that some guys came up and saw the priest bugged and they took it and they spammed ahaahah/reported for bug etc(and the irony is they wanted me to be reported while they took the boss).any ways i did took later with 5-6 people . my name on the char i had it was heidi and my name of my account is velkos4ever if you decide to do anything banning (which i would'd like :3)

**Comment by Torquemadra** [comment]
#2627

**Comment by Evildoor** [comment]
Torquemadra is correct.
