### ISSUE TITLE
Possible to get to high-ground in an SC

### ISSUE THREAD

**Issue by KOTBS** [WarEmu/WarBugs#2681]
![oviktig_000](https://cloud.githubusercontent.com/assets/16400629/12107460/c8580290-b36b-11e5-9c15-2be1cfa6df15.jpg)
Shoud not be possible?

**Comment by saupreusse** [comment]
it seems fine... there are other places where you can just walk out of the map in this sc but this one seems legit :) since everyone could easily follow you up there..

**Comment by Evildoor** [comment]
What's the problem? If you can get to high terrain with conventional methods, everyone can do the same and kill you. Or kill you with ranged attacks from below. If you got punted into high terrain which cannot be reached without punt and your enemy has no RDPS, and you play RDPS - it's your enemy's problem.
