### ISSUE TITLE
Can't leave my guild

### ISSUE THREAD

**Issue by TaeBal** [WarEmu/WarBugs#2682]
Hi im Taebaal : black orc

My guild name "BEHEMOTH"

its one man guild (1/1) im guild leader but i want leave this guild 

But i cant when i push Leave button on guild roster window 

-> pop up small window with this msg "Are you sure?" -> and i push "Yes" -> not work

just now work and got this system msg "The specified player is not a guild leader" 

Yes im guild leader its (1/1) guild 

So i think its bug :)

Thanks for read and sorry about my bad english

**Comment by Evildoor** [comment]
It was always that way, dunno if we can do something. IIRC, you can solve this by asking a friend to create a new character, transferring leadership to that character, and deleting them.
