### ISSUE TITLE
Game sound is gone?

### ISSUE THREAD

**Issue by PowerOfMamaliga** [WarEmu/WarBugs#2686]
Ok, so today my game sound is gone. No NPC or player voice heard when interacting, no music, no battle sounds when you cast a spell, when you hit something etc. The only thing I can hear is some sound effects like bird singing and others. I checked the settings and everything is ok. I tried existing the game and logging in again. Same problem.

**Comment by Evildoor** [comment]
I'm pretty sure this is a game client's problem, in which case we can do nothing.

**Comment by PowerOfMamaliga** [comment]
It's weird because yesterday it had no problem. So I need to install the game again?

**Comment by Evildoor** [comment]
I don't know. Use forums, bugtracker is for server bugs.

**Comment by PowerOfMamaliga** [comment]
Ok
