### ISSUE TITLE
Spawned under The Inevitable City

### ISSUE THREAD

**Issue by SirSweeper** [WarEmu/WarBugs#2687]
When I logged in I was under The Inevitable City, It was all grey and I could move around for a bit before character disappeared. Don't know if it can be replicated or the cause was my PC. 

Sweeper - Marauder

**Comment by Evildoor** [comment]
I don't quite get it. If it is "under Inevitable City" then it's #400.
If it is "all grey" and you can move your character around but you are not looking at them from the usual 3rd person view then it is a known bug with Zone 0.
Which one is it?

**Comment by SirSweeper** [comment]
I don't know how to explain, but if you've ever play WoW it's like the under Stormwind bug just that it's all grey.

**Comment by Evildoor** [comment]
I played WoW, but not enough to know about that bug. So it's "all grey", after all?

**Comment by SirSweeper** [comment]
Yeah it was all grey with a white grey sky box. It was some days ago and I don't know if it was because of my PC.

**Comment by Evildoor** [comment]
Ok, then it's Zone 0, most likely. Just use /stuck (or /stuck and then /stuck during loading screen, if single use does not helps).
