### ISSUE TITLE
Crash - UI/Inventory

### ISSUE THREAD

**Issue by Stavoz** [WarEmu/WarBugs#2688]
Crashing can cause loss of saved UI settings reverting back to the standard UI, having to make all setting changes again (loss of saved profiles).

Also some other players reported to have some items missing from inventory after disconnect.

**Comment by Evildoor** [comment]
Item loss problem is known. Not sure if we can do anything about saved profiles, since they are on client side.

**Comment by Evildoor** [comment]
No objections to my comment, closing.
