### ISSUE TITLE
infuence reward when afk and not in wb

### ISSUE THREAD

**Issue by Kouba85** [WarEmu/WarBugs#2689]
Hi sorry for spaming but when i was smoking a was standing somewhere in Altdorf and when i sit to pc i get 2 times influence reward.
![snorrri_026](https://cloud.githubusercontent.com/assets/15944509/12126050/4a95084c-b3ef-11e5-813c-231c583804dd.jpg)

**Comment by Landaren** [comment]
From what? This isn't a lot to go on

**Comment by Kouba85** [comment]
I don´t know i came to pc from kitchen and make move with my character and on screen was big written you´ve got received an influence reward. When i made screenshot there was just this in chat window. And after 30 sec the same.

**Comment by Kouba85** [comment]
I just want tell that there is some mistake with rewards.

**Comment by Evildoor** [comment]
My guess will be packet corruption, which is reported elsewhere. Closing unless someone proves that i'm wrong.
