### ISSUE TITLE
Shaman detaunt has LoS check while moving

### ISSUE THREAD

**Issue by Morksezstop** [WarEmu/WarBugs#2690]
AM single target detaunt (Dissipating Hatred) doesnt make LOS check, so it is possible to cast it with back toward your enemy

**Comment by Evildoor** [comment]
#2608

**Comment by Morksezstop** [comment]
yea but the linked topic is not as it is at ROR for zealot/rp/shaman

https://github.com/WarEmu/WarBugs/issues/1775
since this report shaman st detaunt need cone of fire...
i dont mind to avoid cone of fire check but make it that way for all healers...

**Comment by Evildoor** [comment]
Tested RP and Zealot, found no problems. Tested Shaman - interesting, LoS check exists, but only when you move. You can detaunt just fine while standing still.
