### ISSUE TITLE
Stalkers Armor Quest Resetting after log off/disconnect

### ISSUE THREAD

**Issue by meleriex** [WarEmu/WarBugs#2691]
I've tried to complete these quests:
http://warhammeronline.wikia.com/wiki/Stalker's_Armor

Multiple times and cannot because the counter keeps resetting after I log off or get disconnected.
Sometimes they don't reset and it will keep the amount I've killed but then If I get more kills it wont count toward the quest.

Not sure what to do about this one.  I am playing Destruction.

**Comment by Torquemadra** [comment]
have you tried abandoning and picking up the quests again?

**Comment by meleriex** [comment]
yes, it hasn't happened since i picked it back up.

**Comment by Evildoor** [comment]
I suppose that this can be closed.
