### ISSUE TITLE
Bug on scenario

### ISSUE THREAD

**Issue by Talissera** [WarEmu/WarBugs#2692]
Sometimes everything stops on scenario, people are disappeared, then after 2-3 mins scenario continues, but I'm in 0hp (practically dead) but can move, can cast abilities like Icy Spikes, but without effect. One time healer could res me, in other cases I should crash client and go out or wait till the end for emblems. 

At this moment this bug appears very often (yesterday 3 of 6 scenes, today 3 in a row). Personally had freeze with 100rr gaining, group mates had mln of gold, but after scene bugged gold was disappeared. On screenshot there are buffs and debuffs from previous scene, which still appear on the bar without effect. And strange %exp
![talissera_003](https://cloud.githubusercontent.com/assets/14876300/12127715/ce8422e0-b409-11e5-9dde-357daaaffb03.jpg)

**Comment by Evildoor** [comment]
#1810
