### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by kirrahakotta** [WarEmu/WarBugs#2693]
I have been crashing a lot lately and it does not happend when the server has lots of players. My friend can see my toon standing, jumping and running around but my screen get still except myself, I can run around, but I can't log out or do anything except running around, so I must kill the game by tabbing down and shut it down, then log in again. 

This has happend in scenarios and in rvr, both in T1 and T2.

**Comment by magter3001** [comment]
A lot of people get this. Some say that having too many quests in your ToK or having too many seeds in your backpack increases the chance of this happening. I personally noticed less of these scenarios when I removed a lot of my seeds but still get it from time to time.

**Comment by sioding** [comment]
**Thanks for the report.** Since there is no confirmation, i will close this issue now. Please make sure to follow the bugtracker rules which you can find here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)
