### ISSUE TITLE
Shadow Warrior "Steady Aim + Rapid Fire" Bug

### ISSUE THREAD

**Issue by saupreusse** [WarEmu/WarBugs#2694]
Hey there!
I Play Shadow warrior main and I found a bug concerning steady aim + rapid fire.
To reproduce this bug, follow these two steps:
Step 1: Cast steady aim (All my attacks should now take +1.5 seconds build up time)
Step 2: Cast Rapid Fire (should now take 1.5 seconds to build up and then start the channeling)

What really happens:
Step 1: I cast rapid fire but the channeling begins immediately and does dmg at the very second i begin to cast (Not 1.5 seconds later).
Step 2: the cast time of rapid fire ends 1.5 seconds earlier as it should, but has done full dmg so far.

Here is a quick video that shows exactly what i mean:
https://www.youtube.com/watch?v=FdiNKpm6yAc&feature=youtu.be

Since rapid fire is the only chaneling ability that shadow warrior has (all other abilities have build up time, wich is different), I assume that this is also the cause of this bug.
Steady Aim works fine with abilities that build up, but doesn't with abilities that have a channeling effect.

Greetings!
Saupreusse

**Comment by Ungrin** [comment]
I'm not sure if this is intentional or not since it functioned exactly the same way on LIVE.

**Comment by Evildoor** [comment]
IIRC, on live RF with SA on was getting 1.5 second cast, during which no damage was done, and then normal RF channeling followed.

**Comment by ozarmidrashim** [comment]
Can confirm, client shows this behaviour.

**Comment by Kaelang** [comment]
If this is still applicable post rework please open a new ticke
