### ISSUE TITLE
ORDER QUEST "Down by the Banks"

### ISSUE THREAD

**Issue by Hauclir** [WarEmu/WarBugs#270]
![chaosdwarf_003](https://cloud.githubusercontent.com/assets/7598530/3579226/f213ccc8-0bb9-11e4-8fb7-ab8a073776c7.jpg)
![chaosdwarf_004](https://cloud.githubusercontent.com/assets/7598530/3579237/31dffb10-0bba-11e4-8555-b8a373f875f3.jpg)
NPC QUEST GIVER: Quartermaster Nachtman
There suppose to be a monster npc named Lundr Bruor that spawns after when you click on the bucket to collect it next to a pond, but the monster does not spawn for you to kill making it impossible to complete the quest. Here a ss down below I found of a quest guide for this quest with the picture of the monster
![downbythebanks6](https://cloud.githubusercontent.com/assets/7598530/3579252/791bf04c-0bba-11e4-8226-68c00d9b88d2.JPG)

**Comment by Evildoor** [comment]
According to #4151, the quest works now.
