### ISSUE TITLE
Entering Stoneclaw without destroying the door

### ISSUE THREAD

**Issue by imneo58** [WarEmu/WarBugs#2700]
Not sure if it's a bug or just overlooked part of the original game. Also not sure who I'm supposed to send a bug report to. The Patch notes state to send a pm but not to whom.

Anyway, there is a way to access Stoneclaw Castle by using the terrain to circumvent the doors. I don't have fraps but I did take several SS's and can even demonstrate how to do said bug. It just requires going up the terrain/mountainside near Tomb of the Traitor PQ then running the highline of the range of mountains behind Stoneclaw then on down into the keep courtyard. I will submit a bugreport to the bug tracker as well. Just trying to be thorough.
![mijdaedseh_028](https://cloud.githubusercontent.com/assets/14805388/12136351/8988558c-b40c-11e5-849f-a8fcfbb10761.jpg)
![mijdaedseh_029](https://cloud.githubusercontent.com/assets/14805388/12136350/89863752-b40c-11e5-857b-bffd8177bf95.jpg)
![mijdaedseh_030](https://cloud.githubusercontent.com/assets/14805388/12136357/898ccde2-b40c-11e5-8f83-e1709bb2938c.jpg)
![mijdaedseh_031](https://cloud.githubusercontent.com/assets/14805388/12136354/898bed82-b40c-11e5-8168-940ebaa37a0f.jpg)
![mijdaedseh_032](https://cloud.githubusercontent.com/assets/14805388/12136352/8988f578-b40c-11e5-8a4f-b97ad5486c08.jpg)
![mijdaedseh_033](https://cloud.githubusercontent.com/assets/14805388/12136355/898c2e82-b40c-11e5-9d05-6526b9d897a1.jpg)
![mijdaedseh_034](https://cloud.githubusercontent.com/assets/14805388/12136353/8989f32e-b40c-11e5-84a9-4185d2b841cb.jpg)
![mijdaedseh_035](https://cloud.githubusercontent.com/assets/14805388/12136356/898c8562-b40c-11e5-9ae3-87d47a14eac5.jpg)
![mijdaedseh_036](https://cloud.githubusercontent.com/assets/14805388/12136358/89a00baa-b40c-11e5-9a55-81600ad615ea.jpg)
![mijdaedseh_037](https://cloud.githubusercontent.com/assets/14805388/12136365/89ad7c86-b40c-11e5-96d0-89102dd00c74.jpg)
![mijdaedseh_038](https://cloud.githubusercontent.com/assets/14805388/12136359/89a61c70-b40c-11e5-9e8d-bd9249dc600f.jpg)
![mijdaedseh_039](https://cloud.githubusercontent.com/assets/14805388/12136360/89a67cd8-b40c-11e5-867c-f012bc42e246.jpg)
![mijdaedseh_040](https://cloud.githubusercontent.com/assets/14805388/12136362/89a831d6-b40c-11e5-8174-574cdff388c8.jpg)
![mijdaedseh_041](https://cloud.githubusercontent.com/assets/14805388/12136363/89a9339c-b40c-11e5-82bd-d494d5267055.jpg)
![mijdaedseh_042](https://cloud.githubusercontent.com/assets/14805388/12136361/89a82952-b40c-11e5-98dc-bae458810ec6.jpg)
![mijdaedseh_043](https://cloud.githubusercontent.com/assets/14805388/12136364/89a985fe-b40c-11e5-972c-aa26753befaf.jpg)
![mijdaedseh_044](https://cloud.githubusercontent.com/assets/14805388/12136366/89bae1d2-b40c-11e5-9923-80b562d19c69.jpg)
![mijdaedseh_045](https://cloud.githubusercontent.com/assets/14805388/12136368/89c40df2-b40c-11e5-87e2-7a1d1a4cc9d4.jpg)
![mijdaedseh_046](https://cloud.githubusercontent.com/assets/14805388/12136367/89c2931e-b40c-11e5-9696-e1b98e9ca022.jpg)
![mijdaedseh_047](https://cloud.githubusercontent.com/assets/14805388/12136370/89c4c328-b40c-11e5-8b63-dfc1dea1c284.jpg)
![mijdaedseh_048](https://cloud.githubusercontent.com/assets/14805388/12136369/89c47314-b40c-11e5-853c-2f1712d81f99.jpg)
![mijdaedseh_049](https://cloud.githubusercontent.com/assets/14805388/12136371/89c64770-b40c-11e5-8d12-c8ab828407c1.jpg)
![mijdaedseh_050](https://cloud.githubusercontent.com/assets/14805388/12136372/89c84b7e-b40c-11e5-97ef-9197773dde8d.jpg)
![mijdaedseh_051](https://cloud.githubusercontent.com/assets/14805388/12136373/89ce3a02-b40c-11e5-9b2f-0b0807d776cc.jpg)
![mijdaedseh_052](https://cloud.githubusercontent.com/assets/14805388/12136374/89d439e8-b40c-11e5-8a62-977e33bf7491.jpg)
![mijdaedseh_053](https://cloud.githubusercontent.com/assets/14805388/12136375/89dc0e8e-b40c-11e5-947e-569ba64b8673.jpg)
![mijdaedseh_054](https://cloud.githubusercontent.com/assets/14805388/12136376/89e0df22-b40c-11e5-8373-42ed72937f42.jpg)
![mijdaedseh_055](https://cloud.githubusercontent.com/assets/14805388/12136377/89e35fea-b40c-11e5-82fb-c1b2277f6ef7.jpg)
![mijdaedseh_056](https://cloud.githubusercontent.com/assets/14805388/12136378/89e3f888-b40c-11e5-913f-6e9d2a5491a9.jpg)

**Comment by saupreusse** [comment]
#2662 shows a video of this :)

**Comment by Evildoor** [comment]
So it's a duplicate then. Thanks, @saupreusse.

**Comment by saupreusse** [comment]
A pleasure, as always! @Evildoor
