### ISSUE TITLE
Out of bounds leeching?

### ISSUE THREAD

**Issue by Aelice** [WarEmu/WarBugs#2704]
like most know its real easy to get Out of bounds in WAR but if you do so in Hige pass/Talabecland,
Badlands/blackfirepass to the east in all maps you can get to places that are connected with the respective rvr zone  and leech xp/inf/renown, 
![aelice_003](https://cloud.githubusercontent.com/assets/16370505/12143504/764fc3d6-b481-11e5-8d7f-3ad80ffff23d.jpg)

![aelice_002](https://cloud.githubusercontent.com/assets/16370505/12143345/21add5ee-b480-11e5-9fb2-2d7a01e68341.jpg)

**Comment by Luth-RoR** [comment]
"Dangerous territory" should be restricted to non-GMs as far as possible atm.
