### ISSUE TITLE
New Group issues

### ISSUE THREAD

**Issue by gats69** [WarEmu/WarBugs#2705]
Hello,
since the last patch, we can see a bug in the management of group : 
- unable to move a player from group 1 to group 2
- unable to change the lead
- some player seem to be bugged and must deco/reco to can be invit in a group

salutations.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
