### ISSUE TITLE
WL tactic (Pack Hunting)

### ISSUE THREAD

**Issue by MadzCatz** [WarEmu/WarBugs#2707]
This tactic does'nt work 
![xkx_000](https://cloud.githubusercontent.com/assets/16580163/12149783/f3a22f9e-b4a5-11e5-886e-ba1ff309d1ad.jpg)
![xkx_001](https://cloud.githubusercontent.com/assets/16580163/12149788/f7159fb2-b4a5-11e5-831c-98bbd0e58d96.jpg)
 when I change buff, my attack speed does'nt change .

**Comment by Evildoor** [comment]
Is it real or visual issue? Have you tested it in combat?

**Comment by MadzCatz** [comment]
I think both, visual and real, u need screen of combat logs to ?

**Comment by Evildoor** [comment]
Tested, visual only.

**Comment by MadzCatz** [comment]
ok, nice ! :)
