### ISSUE TITLE
Main setting reset on restart (re-explain)

### ISSUE THREAD

**Issue by Walmsley09** [WarEmu/WarBugs#2709]
"Every time I close the game and re-run it, it resets a lot of the settings. Most notably, setting it to windowed mode, and a low resolution for both windowed and full screen, and also resetting all of the graphical settings. Also things like hiding your name ect are reset."

I recently made this post, however it was closed quoting "#2253"

It is not what is in that ticket. He explains that his key bindings and ability slots are resetting, I am clearly saying it is actual game settings.

**Comment by Evildoor** [comment]
First of all - do not open new ticket in case you have something to say about existing one. Comment it and we will take a look at it (and reopen, if needed).
While #2253 is a bit different, the core is the same - settings such as key bindings, windowed or not, window size, graphic settings, etc, are saved on your computer and handled by client, not the server. Therefore, this response:
"Properly log off once you have saved your settings (and i mean log out and exit the client and not taskkill r alt+f4 it!). If they do not save correctly, then you most likely have some write protection in your folder."
still applies, and the bugtracker is for server bugs.

**Comment by Walmsley09** [comment]
Sorry i thought once it closed you couldnt write in it
