### ISSUE TITLE
ORDER QUEST "Catching Gnaga"

### ISSUE THREAD

**Issue by Hauclir** [WarEmu/WarBugs#271]
![chaosdwarf_005](https://cloud.githubusercontent.com/assets/7598530/3581352/5a236e60-0bea-11e4-943d-de146cff8fef.jpg)
NPC QUEST GIVER: Ludwig Eberhardt
There a beastmen npc named Gnaga missing that you need to kill for his horns(Gnaga's Horns) also he has a pet pig name Gapa that follows him around and helps him fight, the pig Gapa is spawned in an abundance in the gotland forest which is incorrect there should only be 1 Gapa. Here are some SS from a quest guide down below whichs shows which area location he walks around on the map and a picture of him and his pet pig.
![catchinggnaga2](https://cloud.githubusercontent.com/assets/7598530/3581390/080419da-0beb-11e4-89dc-788f3d554dc6.JPG)
![catchinggnaga3](https://cloud.githubusercontent.com/assets/7598530/3581392/0e0591ba-0beb-11e4-9541-8a88db3b0472.JPG)

**Comment by Evildoor** [comment]
From https://github.com/WarEmu/WarBugs/issues/587 by @goingbzrk:
"Upon killing gnaga you don't recieve the horns you need to complete this quest"

**Comment by DanaBloodkiss** [comment]
One of the best reports I saw this far. Though I spawned both NPCs and matched the quests to it but we moved their spawn to another place so it matches to the surroundings better. The questmarker show you where.

**Comment by peusnaugrim** [comment]
Gnaga and the boar gapa are not there. Anyone have the location in Norsca?
