### ISSUE TITLE
Witch elf Elixir of blades

### ISSUE THREAD

**Issue by Vdovics** [WarEmu/WarBugs#2710]
The tooltip says "anytime enemy strikes you, you will deal 100 dmg back to them". Should it work also on ranged attacks? because it doesnt says it proc only from melee attacks only like it says on Witch hunters Van Horstmann´s Speculum. 
Anyone familliar with this from live?

**Comment by ozarmidrashim** [comment]
When asking for clarification of a bug, you may use the forum.

**Comment by Chummi** [comment]
it was always melee attack only.

**Comment by Vdovics** [comment]
Ok. I never spec for that on live and tooltip didnt say it clearly. Thanks for the info.
