### ISSUE TITLE
Guild Roster

### ISSUE THREAD

**Issue by Zanilos** [WarEmu/WarBugs#2713]
Not regular roster bug.

I have recruited 3 people and every time they log in they are not in the guild. There is no info on news that they have been kicked or left...

![guild broke](https://cloud.githubusercontent.com/assets/16420518/12178935/1ff26ae8-b56c-11e5-90f4-61fa16128684.jpg)

**Comment by Zanilos** [comment]
I removed my SS as it had my guild TS on it, Ill edit and re apply :D

**Comment by Evildoor** [comment]
#948
