### ISSUE TITLE
Witchbrew Implementation

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#2714]
From http://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=7499&start=30#p104859

Current implementation: Able to proc a WB stack every attack without any sort of cooldown or proc chance.
i.e. MH + OH + 2xFinisher (=4) in one global.

Live implementation (details currently unknown): Most likely ICD based (2s ish) see video linked in the thread.

Intended behavior?
"Bugfix"? (Because the ability tooltip supports the current implementation)

Please confirm.

**Comment by Vdovics** [comment]
As far as I remember Witch brew works the same as choppa/slayer hurting time togle dmg buff. It also add XY dmg to all melee attacks. Both buffs has also no internal cooldowns. The opinion that witchbrew proc 1 per second or has some kind of internal cooldown is wrong(in my opinion). It just works the same as tooltip says.

**Comment by taccr** [comment]
Reckless Gamle and Hurtin Time are totally differently implemented:
They trigger with a 100% chance on melee abilities which automatically limits one proc per global. They do not trigger on AA or the throw attack.

We are here to figure out the behavior because there is evidence that WB does not proc on every attack.

**Comment by Vdovics** [comment]
So my bad than. 2 years are 2 years and I cant remember corectly. Sorry.

**Comment by ozarmidrashim** [comment]
I've looked at the combat log and I've seen areas where the RoR implementation and his log differ. Specifically, an area in which we see Kiss of Betrayal, then auto attack, then Witchbrew, then second auto attack. RoR would trigger two Witchbrews here - the official server triggered one.

**Comment by seraxes** [comment]
This is correct. Witchbrew should only proc once a second.

**Comment by Tiggonos** [comment]
so this is correct behaviour for witch brew proccing 3 times in a second? thats 1000 dmg in 1 second?

![martock_038](https://cloud.githubusercontent.com/assets/13809443/14065765/27825a98-f437-11e5-896e-db519f5e7d93.jpg)

**Comment by seraxes** [comment]
Why is this skill still not fixed?

**Comment by ozarmidrashim** [comment]
Dealt with, along with Wounds debuff ordering.

**Comment by Thorgatin** [comment]
https://web.archive.org/web/20100105091850/http://www.darkworlddesigns.com/BlogtheWitch.html

**Comment by Tiggonos** [comment]
what is the new mechanic then if i might ask? once every two seconds?
