### ISSUE TITLE
WL - Trained to Threaten

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#2715]
Tooltip says 5% melee crit on a positional basis, Mythic/EA couldnt get that to work so on live it was always a flat 5% melee crit 

On RoR this doesnt seem to be happening on the paperdoll (intermittant) but definitely not using .getstats

Sometimes it shows on the paperdoll, sometimes it stays all login, sometimes it vanishes and never comes back after changing stances.

At no point however does it show up in .getstats

![svanne_007](https://cloud.githubusercontent.com/assets/16200780/12153715/696758d4-b489-11e5-9a39-4191d89583db.jpg)

**Comment by ozarmidrashim** [comment]
RoR performs the positional check - you must be flanking to get the bonus. Therefore, this ability will not show in getstats, as it's implemented as a conditional.
