### ISSUE TITLE
SC parties still not working correctly

### ISSUE THREAD

**Issue by Olszewski-Slayer** [WarEmu/WarBugs#2716]
it said im in a party and i can leave it. on the chat box it said its full. u can see its not. group make on top left doesnt show me in a party but shows i can leave the party though. SC parties still bugged. i wasnt trying to move party when dead either. u can see the multiple times i tried to fix the party to make it full before being dead. very frustrating to play when u are trying to get in a group when it bugged out. 

![olszewski_006](https://cloud.githubusercontent.com/assets/16567054/12156299/2d90d1dc-b498-11e5-8cff-84f6e7a6456c.jpg)

**Comment by Evildoor** [comment]
#1138
