### ISSUE TITLE
Loot rolls when not in a group

### ISSUE THREAD

**Issue by bwdaWAR** [WarEmu/WarBugs#2718]
I've got loot roll popups shortly after logging in with my Sorc and BG, without joining or even trying to join any parties/warbands/scenarios.
I don't know if it is relevant, but before logging those characters, I was in a bugged T3 warband with a DoK. I switched after leaving WB, without shutting down the client. I started in party 1, was moved to party 2, and after a  while my group heals spread to party 1, not 2 (I think it spread to party 2 when I was moved, but I'm not sure). Maybe the game still considered characters on my account being in that warband, for the same reason it considered my DoK to be in a different party? The loot was in the T3 rank range.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
