### ISSUE TITLE
ORDER QUEST "Misled"

### ISSUE THREAD

**Issue by Hauclir** [WarEmu/WarBugs#272]
![chaosdwarf_009](https://cloud.githubusercontent.com/assets/7598530/3581684/579f07b6-0bf0-11e4-98cd-0cd25d504cb6.jpg)
NPC QUEST GIVER: Ludwig Eberhardt
After killing Gernar Kaltenbach I was unable to turn the quest into Sergeant Polk, also Sergeant Polk is a naked dwarf wielding a sword instead of a Empire Men
![chaosdwarf_010](https://cloud.githubusercontent.com/assets/7598530/3581711/c89dad82-0bf0-11e4-9dc3-8a2ace8f0716.jpg)

**Comment by Reggaewaldo** [comment]
I just checked this, the quest has been altered so that you are not supposed to talk to Polk and just report back to the quest giver.

Closing.
