### ISSUE TITLE
friendly player flaged to be attacked

### ISSUE THREAD

**Issue by Olszewski-Slayer** [WarEmu/WarBugs#2720]
logged on and i see this. lol. looks like a duel bug.

![olszewski_007](https://cloud.githubusercontent.com/assets/16567054/12158778/3028d0f8-b4ab-11e5-98b0-3932e17df68a.jpg)

**Comment by noisestorm** [comment]
Nothing relevant. He just didnt finish his duel with whoever - upon zoning or dying this should be selffixed anyways
