### ISSUE TITLE
T3 ELF RVR INF Marauder Cloak Rewards missing stat and 1 wrong choice in place. 

### ISSUE THREAD

**Issue by Hauclir** [WarEmu/WarBugs#2721]
![hauclir_004](https://cloud.githubusercontent.com/assets/7598530/12159381/9bba1af8-b496-11e5-8c8c-0f8bdd5b9a39.jpg)
Not sure if this has been reported yet can't seem to find a issue made here for it, but the Marauder class is missing 1 purple cloak choice which should be Qhaysh Shroud instead of Maiden's Greatcloak and a +17 strength stat is also missing to it's Ghrond's Shroud. As of right now the Marauder has 3 blue cloaks and 1 purple cloak to choose from instead of 2 blue and 2 purple.

http://www.arsenalofwar.com/armor/Destruction/Ghrond's%20Shroud
http://www.arsenalofwar.com/armor/Destruction/Qhaysh%20Shroud

**Comment by Styrkarr** [comment]
I fixed the stats for Ghrond's shroud.
And you are right, the second purple is Qhaysh shroud, i'm going to add it to the rewards.

**Comment by Styrkarr** [comment]
Fixed in next patch.
