### ISSUE TITLE
Renown Trainer Confused

### ISSUE THREAD

**Issue by AndrewSquared** [WarEmu/WarBugs#2722]
When coming back to the renown trainer to train skills after a log-out, any previously learned abilities are not tracked by the trainer or your abilities interface. Points show as spent, all bonuses are retained, but training an ability further is not possible.

For example, going to the renown trainer after having trained Might I and Opportunist I, I am unable to train Might II without having enough to re-buy a skill. Even then, adding new skills after a re-log is only successful sometimes.

![001_before_renown_train](https://cloud.githubusercontent.com/assets/5799247/12159957/365e5a56-b4b5-11e5-9738-a051aa9f652f.png)

![002_after_renown_train](https://cloud.githubusercontent.com/assets/5799247/12159962/3e1ed3a6-b4b5-11e5-8e22-41e8c1468a05.png)

![003_after_renown_train_paper_doll](https://cloud.githubusercontent.com/assets/5799247/12159963/413d76be-b4b5-11e5-915f-c851eebfd2d9.png)

![004_after_relog_paper_doll](https://cloud.githubusercontent.com/assets/5799247/12159965/434acea2-b4b5-11e5-93e3-98c435150d68.png)

![005_after_relog_trainer](https://cloud.githubusercontent.com/assets/5799247/12159967/44ca2b7e-b4b5-11e5-9dd2-0c7e58628c86.png)

**Comment by Evildoor** [comment]
#1486
