### ISSUE TITLE
Killing 20 DoK's Quest discontinuation

### ISSUE THREAD

**Issue by Alvanos** [WarEmu/WarBugs#2723]
After I killed 20 DoK's for my stalker gear quest, I got an update to report to Ulfmn Vogel in High Pass Warcamp. He gave me 25silver but I got no update to the quest. Also The high elf Sorelle Darkglade which gave me the kill quest does nothing and has no dialog options.

**Comment by genisaurus** [comment]
Closing, confirmed to be working. If the quests are not progressing properly for the OP, this is a character issue and he should contact a GM in game. Also, note that the kill quests do not reward Stalker gear. They lead to a second quest to kill a hero NPC, and *that* quest rewards the gear.
