### ISSUE TITLE
I dodged my own Whirling Pin!

### ISSUE THREAD

**Issue by foxbeep** [WarEmu/WarBugs#2725]
Not sure how this happened, I'm assuming I dodged the knockback effect for my own whirling pin, which in turn put my own pierce defenses debuff on myself

![laerith_037](https://cloud.githubusercontent.com/assets/15528466/12162108/97d0b5e6-b4c3-11e5-9c98-2a19b3165089.jpg)
![laerith_035](https://cloud.githubusercontent.com/assets/15528466/12162113/9e267188-b4c3-11e5-8d93-40ac5e7d4772.jpg)

**Comment by Ryanfawkez** [comment]
I've seen the self-punt failing on SWs/SHs even when they popped it during an incoming push from the enemy, and despite it snaring them with no immunities. Assuming this is the reason why.
