### ISSUE TITLE
[Runepriest] Oath Rune cannot be cast on party members

### ISSUE THREAD

**Issue by vove-RoR** [WarEmu/WarBugs#2729]
Today I faced an issue where I couldn't buff my party members from my warband with Oath Rune (none of them). They didn't have any other Oath Runes on them, I was the only runepriest in the party.

Now I do not know what exactly caused it but I am almost sure it was caused by joining a scenario while being in the warband. You cannot queue for sc when you are in a warband but you can queue a scenario and then join the warband (it doesn't remove you from the queue).

So, the situation was: I queued for scenario and as it was taking long to find a match I joined a warband meantime. We took enemy keep and sc popped up so I joined it. I could buff party members from my sc party. Once sc finished I was back in my warband but I couldn't buff the teammates who were in my party, only myself.

I didn't have the possibility to recheck if joining the sc when in wb was the thing that caused it, if I manage to reproduce it I will update the entry.

**Comment by vove-RoR** [comment]
I can confirm it is caused by joining a scenario while in a warband as I have just managed to reproduce it following above steps.

**Comment by vove-RoR** [comment]
Today I've seen this report #2603 which looks related.

**Comment by Luth-RoR** [comment]
Afaik there exists code to prevent people from joining scenarios while they are part of a warband.
Just don't join scenarios while you fight as part of a WB, as it is intended.
