### ISSUE TITLE
[Quest] "Firebrew" - Multi-part can be taken at same time.

### ISSUE THREAD

**Issue by Niobandi** [WarEmu/WarBugs#2730]
At the "Pick & Googles" tavern in Ekrund, Brewmaster Eisenbjorn and Gunnar Klaurse give you all the part of the quest "Firebrew" at the same time.

They should be given one after the other will be done.

![traron_000](https://cloud.githubusercontent.com/assets/16079024/12175626/a8f62194-b563-11e5-86e2-6c7e5518bbaf.jpg)

**Comment by Meralors** [comment]
Fixed quest line, npc should no longer offer all quest .
