### ISSUE TITLE
Bandit Queen/ Darkshroud BOP/BOE 

### ISSUE THREAD

**Issue by Zenoviazen** [WarEmu/WarBugs#2731]
Not all of my Bandit Queen and Darkshroud items are BOE. 
This seems to be a race issue???
As an elf, all elf classes are bound to me and not tradable. 
All other races (dwarf/human) are BOE and tradable. 
This was observed with items I had on me that were dropped before patch
These elf items that are bound can be sold at AH but can not be directly traded or mailed

**Comment by Evildoor** [comment]
Checked, all 4 High Elf helms of The Bandit Queen are BOE.

**Comment by BoscoTheBear** [comment]
I just got the bandit queen helmet for chosen and I was trying to trade it to one of my party members and the helmet is still BOP, so I don't know if it is a issue with all the helmets for destruction or just for some classes.

**Comment by BoscoTheBear** [comment]
![garshak_000](https://cloud.githubusercontent.com/assets/16624356/12217775/4a31be16-b6d0-11e5-83ce-b881ac6d3df3.jpg)
my guild mates were also telling me that it might not be bugged I just want confirmation to see this helm is still BOP or what the patch saying its BOE now.

**Comment by genisaurus** [comment]
Fixed with next restart, not next patch. The items were changed to BoE, but the "bound" flag was still set for all players who had previously equipped the items. That bound flag has been cleared for these helms. Closing now, because this will go into effect with the next restart instead of patch.
