### ISSUE TITLE
[Chosen] Aura spread failure - one of your auras was removed.

### ISSUE THREAD

**Issue by D4W0lf** [WarEmu/WarBugs#2733]
When I want to join a party and if this party is full, lost all my aura since today (01/07/2016 @ 21:00).
[21:26:09] The party is full.
[21:26:09] Aura spread failure - one of your auras was removed.
[21:26:09] Aura spread failure - one of your auras was removed.
[21:26:10] Aura spread failure - one of your auras was removed.

After this errors messages, I can't reactivate my auras. Disconnect / Reconnect make the auras re-work.

If I join a non-full party and try to activate my auras, it work.

Before trying to join a party, just after login, no issue with the auras.

Let me know if you need some others explaination, and sorry for my poor english :)

DaWolf

**Comment by Torquemadra** [comment]
was there another chosen with his auras on?

**Comment by D4W0lf** [comment]
Where ?
I was in the WC of Talabecland, so perhaps.
But I was not in a group so difficult to see it.

I've targeted a Chosen near me, and he had 2 auras. Resist and heal on block.

I've not looking for another Chosen.

**Comment by taccr** [comment]
https://github.com/WarEmu/WarBugs/issues/1385

**Comment by D4W0lf** [comment]
OK didn't see this ticket, sorry.
