### ISSUE TITLE
When buying "silent essence", stacks dissapear but gold is still removed from my inventory

### ISSUE THREAD

**Issue by hredthel** [WarEmu/WarBugs#2735]
> When I have the 'craft supply merchant' window open
> and my inventory window set to the 'crafting' tab, 
> selected to buy a stack of level 1 'silent essence'
> and I set my purchase amount to anything above 20 (normal stack)
>     >AND there is a PARTIAL stack of 'silent essences' in my inventory

As soon as I buy the stack of essences: lets say 50, and I have a partial stack of 10 already in my bag: Only 10 essences will transfer to my bag (being the amount needed to fill that one partial stack) and I will get charged for the full 100silver.

If I buy them in groups of 20 at a time I have no issues

tested with a partial stack of 3, 7, 10, 12, 13, 15, and 16.

**Comment by Kaelang** [comment]
Purchased a stack of 50 and changed from 10-40 and a 20 stack.

Please re-open if issue continues.
