### ISSUE TITLE
'Chosen Poorly' quest npc bug

### ISSUE THREAD

**Issue by Razz1n** [WarEmu/WarBugs#2737]
After i finihed part for killing boss i returned to NPC and he gave me Stalker's hands but then i got second same quest on boss and reward from him again.
![emberus_012](https://cloud.githubusercontent.com/assets/16601045/12185336/d0604b42-b5b3-11e5-99bb-e68ca015479a.jpg)

**Comment by Torquemadra** [comment]
its now repeatable for those who lost items in the ddos attacks, they are not salvageable though

**Comment by noisestorm** [comment]
Patchnotes yes. Quests are repeatable now.
