### ISSUE TITLE
Cultivation Breaking randomly

### ISSUE THREAD

**Issue by Vandorkholme** [WarEmu/WarBugs#2738]
I usually use the  miraclegrow remix addon, but this happens even while using the normal interface (still while miraclegrow is loaded in addons however). Randomly as I try to harvest my plants it will become completley unresponsive and I cannot harvest any plots or plant new plots. I have to relog every time and lose the plants that were in the plots.

**Comment by taccr** [comment]
Breaks frequently for me if I harvest the plants too fast.
If I do it slow it usually works with very few exceptions.

**Comment by Evildoor** [comment]
#1721
