### ISSUE TITLE
Can't join scenario because I'm still in combat but am not.

### ISSUE THREAD

**Issue by amonkeynamedfee** [WarEmu/WarBugs#2739]
I've only had this problem on the blackguard so far but sometimes once I get done with a scenario and reque and the accept pops up it says I'm in combat no matter what, relogging dosent work; I have to close the entire game AND the launcher and restart to get out of combat to accept a que pop.

**Comment by taccr** [comment]
have you tried the .unlock command in say chat?

**Comment by noisestorm** [comment]
what taccr said.

**Comment by amonkeynamedfee** [comment]
Thanks for the quick reply. I wasn't tracking about that fix. I'll try it out next time it happens.
