### ISSUE TITLE
Stacking snares

### ISSUE THREAD

**Issue by Mezirah** [WarEmu/WarBugs#2740]
Not sure if this is correct, but I when I came out of a champ challenge by a sword master, I was walking with like 5-10 % speed. A knight was on me, and possibly a SW or BW. I think the knight and SM snares were stacking though.

**Comment by noisestorm** [comment]
Most likely you were just affected by SMs wings which is a heavy heavy slow. If you encounter another 'ridiculous' slow again in the enar future, then quickly use the .getstats command and screenshot your movement value there

**Comment by genisaurus** [comment]
Wings of Heaven, as a morale-inflicted snare, could be stacking with ability-inflicted snares. Not sure if this is a bug, or working as intended.

**Comment by Chummi** [comment]
SWs Whirling Pin and AMs Mistress of the Marsh were supposed to stack on live which resulted in a root, same counts for SH + Shaman. Not sure if it's the same here or if it got already fixed, but that might be the case.

**Comment by Evildoor** [comment]
No confirmation, closing.
