### ISSUE TITLE
PvE Quest:  Beasts for the Raven God

### ISSUE THREAD

**Issue by Vandorkholme** [WarEmu/WarBugs#2741]
The quest points to a very specific type of enemy in a specific area, so specific that there is only 1 enemy of the type in the area, a hound named Steelfang and you have to kill him 10 times. And you have to wait for him to respawn 10 times. This seems like an oversight.

**Comment by Meralors** [comment]
Added some target npc and lowered a bit the amount to kill to make this quest doable in less than 30min :p
