### ISSUE TITLE
Morale skill - Champion's challenge - not working properly?

### ISSUE THREAD

**Issue by Bykster** [WarEmu/WarBugs#2742]
Hello,
You and your opponent are frozen in a place for all skill time duration. You should be able to run in a fenced off area - if I remember it well from official server.

I hope that you understood ;)

cheers.
Mario

**Comment by taccr** [comment]
No, it doesn't work like that. Both players are rooted unable to move.

**Comment by Evildoor** [comment]
Wrong.
