### ISSUE TITLE
Detaunt + Dots

### ISSUE THREAD

**Issue by Culdu** [WarEmu/WarBugs#2744]
Detaunts only affect the first tick of a Dot all following ticks do normal dmg. Also tried it with guard, the guard is not working(as intended) on a detaunted enemy, but second and following dot ticks do normal dmg instead of detaunted(50%) dmg.

**Comment by noisestorm** [comment]
Can confirm. Tested with detaunt pre dot and detaunt during dot. Only one tic gets reducded and the rest hits for the full value.
