### ISSUE TITLE
Inescapable/Casmir Pol

### ISSUE THREAD

**Issue by Fiddlehero** [WarEmu/WarBugs#2747]
Yesterday, I killed Casmir Pol and got credit for the kill. The quest was considered done in the quest log. I went to turn it in, and clicked the "complete" button. Instead of completing, it reset the quest for me. I need to kill Casmir Pol again. 

Now during the fight, he killed an engineer and myself a couple of times. Our healer managed to remain up, and rez us so that we could finish the fight. He reset a couple times, but his health did not. Could this be the reason I got completion, but not real completion for the quest?

**Comment by Torquemadra** [comment]
Are you certain you didn't get the armor? Stalkers armor is now repeatable (but not able to be salvaged

**Comment by Fiddlehero** [comment]
Yes, I’m certain, I checked my bags. I re-did the quest today and it worked fine. I got the armor the second go around.






Sent from Windows Mail





From: Torquemadra
Sent: ‎Friday‎, ‎January‎ ‎8‎, ‎2016 ‎12‎:‎51‎ ‎PM
To: WarEmu/WarBugs
Cc: Fiddlehero





Are you certain you didn't get the armor? Stalkers armor is now repeatable (but not able to be salvaged

**Comment by Luth-RoR** [comment]
Should be fixed.
