### ISSUE TITLE
[Interface] Tutorial window

### ISSUE THREAD

**Issue by Gothmakh** [WarEmu/WarBugs#275]
Every now and then, a tutorial window pops up. Until now, each of those windows did not nove any text.

![gothmakh_002](https://cloud.githubusercontent.com/assets/8167516/3584407/793104ce-0c18-11e4-921b-d01ae682bd92.jpg)

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
