### ISSUE TITLE
[Skill] Squig Herder's Expert Skirmisher tactic reduces mount summoning time

### ISSUE THREAD

**Issue by vove-RoR** [WarEmu/WarBugs#2752]
In game description of the tactic:
>Your cast times are reduced by 50% when you are within 20ft of your target.

Now this tactic as I guess should apply only to SH's skills yet it reduces the mount summoning time which is an item use. Also the summoning time is reduced permanently.

**Comment by bloodi** [comment]
Shit, i forgot this was a thing, the same happens on every tactic, at least the BW does the same and its where i noticed it, i forgot to report it since, well, i dont ever run that tactic.

**Comment by magicthighs** [comment]
Noticed this too on my BW with the flashfire tactic (0 sec cast time after disrupt).

**Comment by Evildoor** [comment]
Dunno about mount, but on live it decreased cast times of career abilities when you had no target at all (turret summon, for example).
