### ISSUE TITLE
[crash] When getting winning point at the end of a scenario

### ISSUE THREAD

**Issue by pmettraux** [WarEmu/WarBugs#2754]
If the additional point added when you win a scenario allow you to get to the next level the app crashes in different way. Sometimes you just get disconnected. It happens to me all the time when I pass a level when I win a scenario. But never happened to me when it was in PVE.

Hope it will help,
Wurz Shaman ;)

**Comment by Evildoor** [comment]
I would like to see a confirmation on this. IIRC, i've levelled on scenario end several times, and had no problems.

**Comment by Evildoor** [comment]
No confirmation, closing.
