### ISSUE TITLE
[Crafting] Cultivation: Two Possible Seed Bugs

### ISSUE THREAD

**Issue by Kaori1** [WarEmu/WarBugs#2756]
Hello! I noticed a somewhat minor issue with two of the seeds thus far in my Cultivation farming:

1. Upon growing a Rugged Thief's Seed (Ballistic) I noticed that I was rewarded with a "Rugged Thief's Nettle" upon a successful cultivation/craft. However, this lvl 200 Apothecary Main Ingredient Plant CANNOT be broken down into new Seeds and Arboreal Resins. I tested other lvl 200 seeds for Strength and Willpower and both of those seeds provided me with plants that could be broken down into Seeds/Arboreal Resins. Therefore, I am assuming that the lvl 200 Ballistic stat Rugged Thief's Nettle is bugged. 

2. I did not practice Cultivation on live so this next one may or may not be an actual bug: I have within my possession two ALMOST identical seeds; A "Shaded Shadow Fusk Spore" which is classified as a SEED and a second "Shaded Shadow Fusk Spore" that is classified as a SPORE. Both of these seeds are lvl 125, share the same item icon (a fungi/spore icon) and cannot be stacked with each other. As such, I am only assuming that the one classified as a SEED is some sort of a mistake since they both have "spore" in their name. 

I hope these findings help improve this wonderful server of yours and I'll be sure to keep an eye out for more bugs to report in the future. Thank you for your time and dedication!

**Comment by Squea** [comment]
Seeds that drop from mobs do not seem to stack with seeds that are grown.  If a seed will not stack, simply grow it and refine the plants; they will then stack.

**Comment by genisaurus** [comment]
Rugged Thief's Nettle should be reapable as of the next patch
