### ISSUE TITLE
[BO] Crit tactic issue. 

### ISSUE THREAD

**Issue by Gobtar** [WarEmu/WarBugs#2758]
The getstats show builder based crit as a seperate crit bonus, and it testing with THC either I crit consistently or I wont crit at all. I am not sure what the issue other than this.
![crittactic](https://cloud.githubusercontent.com/assets/7888608/12213886/e35d86a2-b657-11e5-8bd6-a699bbe68f84.png)

**Comment by Evildoor** [comment]
Tested this + THC, got both crits and non-crits. Separate bonus is because it gives general crit (melee, ranged, healing, magical) rather than just melee crit (Sweet Revenge, for example, works in the same manner).

**Comment by Gobtar** [comment]
I only brought it up cause I went a whole SC with minimal crit, consistent with a 9% crit then next SC it was back to normal, will do additional testing with a larger sample group.

**Comment by Evildoor** [comment]
No confirmation, closing.

**Comment by Gobtar** [comment]
Sorry, will get additional testing done, I haven't had the time to sit down and make a large sample set with various control times (i,e delays with attack) Will try to get this done this week.
