### ISSUE TITLE
[NPC] Texts <name>

### ISSUE THREAD

**Issue by Gothmakh** [WarEmu/WarBugs#276]
Some NPCs adress the player by his name... at elast that is what they are trying to do. Instead, they refer to him as *name*
it seems as if the variable <name> in those texts is not linked to the the corresponding variable in whatever player database the player nams are stored.

Here are some screenshots:
![gothmakh_003](https://cloud.githubusercontent.com/assets/8167516/3584443/37e0c832-0c19-11e4-9ab9-c122592e435d.jpg)
![gothmakh_004](https://cloud.githubusercontent.com/assets/8167516/3584445/3f6137c2-0c19-11e4-97e0-a90e864fee66.jpg)
![gothmakh_006](https://cloud.githubusercontent.com/assets/8167516/3584448/4ab5d24a-0c19-11e4-85a8-2b13e845ccb8.jpg)
![gothmakh_006](https://cloud.githubusercontent.com/assets/8167516/3584450/4f74a5b8-0c19-11e4-9cd1-b28e5b0e7204.jpg)

**Comment by genisaurus** [comment]
Fixed at some point in history
