### ISSUE TITLE
[NPC] questgiver Alan Cartwright spawned twice

### ISSUE THREAD

**Issue by vove-RoR** [WarEmu/WarBugs#2761]
In Brokenbone Pass there is a NPC called Alan Cartwright who is spawned twice.

Even though Alan and his clone look a little bit different they give exact same quests. Quests cannot be taken twice but they can be taken from one Alan and turned in to another Alan. Also 2 quests out of 3 he gives can be turned in right away without doing a thing (rewards 60 xp).
![alan1](https://cloud.githubusercontent.com/assets/16596013/12215910/05602df2-b6c8-11e5-8dce-68bc2d95cd14.jpg)
![alan2](https://cloud.githubusercontent.com/assets/16596013/12215912/0c1e5308-b6c8-11e5-94d3-b5919cef1c2e.jpg)

**Comment by genisaurus** [comment]
Not a bug. WAR had several quest-givers like this, who were scripted to spawn in one area, walk to another, and then despawn. They all gave cultivation materials as rewards. We lack the scripting to make them move or despawn, but their original spawns remain.
