### ISSUE TITLE
Tor Anroc Bauble

### ISSUE THREAD

**Issue by Walmsley09** [WarEmu/WarBugs#2763]
Recently I have realised that in the scenario Tor Anroc, it happens quite often that holding the bauble stops granting points. In my last match I held it for 2 mins and no points were generated, and the enemy team won purely through kills. It seems it may work up until the initial carrier dies, then it no longer grants points.

**Comment by Evildoor** [comment]
Were you standing near your warcamp?

**Comment by Walmsley09** [comment]
No I ran along the side passages, as their team were camping the WC. Was just me and a healer on the courseway between the WC and the centre if that makes sense?

**Comment by Walmsley09** [comment]
![20019644](https://cloud.githubusercontent.com/assets/16541810/12216611/ff4b65ea-b6df-11e5-9b01-5a407747c93c.jpg)
This should explain better where I was running about
