### ISSUE TITLE
[Slayer] Numbling strike not working

### ISSUE THREAD

**Issue by Kouba85** [WarEmu/WarBugs#2764]
I think that this abillity is not working properly i have target but this abillity is not active. Cannot use it.
![snorrri_028](https://cloud.githubusercontent.com/assets/15944509/12217436/95b47e5c-b700-11e5-96e9-17d96ad455b3.jpg)

**Comment by Evildoor** [comment]
Ahem. What does that big yellow text in the middle of the screen says?

**Comment by Kouba85** [comment]
It says that requires target to have parried or blocked but i have target - filty rat. The same in scenario or RVR when i have targeted another enemy player.

**Comment by Evildoor** [comment]
Let's try again. You have a target. The text says  "requires target _TO HAVE PARRIED OR BLOCKED_". Something sounds the bell?

**Comment by genisaurus** [comment]
I'm going to close this now. Kouba, in order for Numbing Strike to work, your target must have recently parried or blocked one of your attacks. A level 1 rat in Altdorf will almost never do that, so you will almost never be able to use Numbing Strike against the rat.
