### ISSUE TITLE
Wherever They Are Found (Roland Gotthardt)

### ISSUE THREAD

**Issue by vove-RoR** [WarEmu/WarBugs#2766]
Roland Gotthardt in Raven's End gives a quest with some error thrown as a an objective (see attached).
![untitled](https://cloud.githubusercontent.com/assets/16596013/12218068/c0a3e386-b70b-11e5-8b23-f990fe97c248.jpg)

**Comment by Ryanfawkez** [comment]
NPC to be spoken to is currently missing since Mount Gunbad isn't implemented yet.

**Comment by Lheana** [comment]
As Gunbad is now accessible, the quest works fine.
