### ISSUE TITLE
Free(k) RR, Infl. and Xp ticks

### ISSUE THREAD

**Issue by Pumatouch** [WarEmu/WarBugs#2769]
While standing around today in Dwarf T3 RvR Lake, a kill which I had not participated in rolled across my screen, giving my level 26 a grand boost of 1/4 level worth of xp, among other things. The one whom I was conversing with had the same occurence, only he reported to also receive a medallion. 
Combat log showed a kill by a 3rd player indeed, but none of them were grouped with me, neither then or ealier, and I had not participated in any (succesful) combat at the time.

On a differnt character, something similar happened, only this time after leaving a succesful keep siege and heading out to assist some folks with Stalker quests. Long story short, we waited around for an hour and suddenly a great tick like above rolled in. None of the new group members I was around at the time of this occurence had this happen.

I could provide photos, I suppose, but they would merely show the ticks in combat log, coupled with a picturesque background of mountains.

**Comment by nalgol** [comment]
wasn't a zone lock by any chance or?

**Comment by Pumatouch** [comment]
In fact no, was very clear in combat log that, don't remember names, a guy had sliced a destro guy to death, rewards and stuff.

**Comment by Pumatouch** [comment]
The second case I was far away from the zones, I am not aware if they were taken at the time.
