### ISSUE TITLE
[NPC] Texts <career>

### ISSUE THREAD

**Issue by Gothmakh** [WarEmu/WarBugs#277]
Some NPCs adress the player by his carreer... at elast that is what they are trying to do. Instead, they refer to him as *career* (in my case they would call me *Runepriest*.
It seems as if the variable <career> in those texts is not linked to the the corresponding variable in whatever player database the player careers are stored.

Here are some screenshots:
![gothmakh_005](https://cloud.githubusercontent.com/assets/8167516/3584472/a1d20396-0c19-11e4-8553-6443dd8c4016.jpg)
![gothmakh_008](https://cloud.githubusercontent.com/assets/8167516/3584474/a76a1d98-0c19-11e4-838d-a8a8b47d8184.jpg)

**Comment by genisaurus** [comment]
Fixed at some point in history
