### ISSUE TITLE
Bank Vault: 2nd page

### ISSUE THREAD

**Issue by Squea** [WarEmu/WarBugs#2772]
If you move an item into an area of the personal bank vault which you haven't purchased, (2nd or 3rd page) the item will disappear.

Item is there if you relog/buy the slots.

**Comment by nalgol** [comment]
i just tryed this but no mater what i do i cant move an item to a not buyed bank slot how you do it ?

**Comment by Squea** [comment]
It likely happened with a bat wing or some other butchering material I can't make a usable pot out of on the second vault page.  Possibly a one time thing, it doesn't happen now.

**Comment by Evildoor** [comment]
Closing then.
