### ISSUE TITLE
BW Devastator shoulders - wrong appearance

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#2774]
BW Devastator Illuminations are missing 1/2 the piece (the outer part).

**Comment by Ryanfawkez** [comment]
If you feel as if Devastator gear has the wrong appearance on this server, please do include a picture of the original Devastator set from live.

**Comment by gittoaster** [comment]
[img]http://s22.postimg.org/ohod1pmld/shoulder.jpg[/img]
I tried looking for better images but I could not find any.  Anyways I think part of the issue is that it seems like 1/2 the shoulders seems missing,  It's hard to tell even what set it is.  The way it is now is not like any other model I have seen before.  For example you should not be able to see that much of the skin on the shouder - which would be mostly covered by extra model..
