### ISSUE TITLE
[White Lion] Coordinated Strike skill doesn't require an active pet

### ISSUE THREAD

**Issue by vove-RoR** [WarEmu/WarBugs#2779]
White Lion's skill Coordinated Strike (simultaneous attack with the lion pet) doesn't require an active pet to use. Although when used without lion it does only part of the dmg.

Similar skill for Squig Herder (Git Em!) requires an active pet to use that attack, so I guess that either SH's skill shouldn't require active pet or WL's skill should require it.

**Comment by ozarmidrashim** [comment]
"I guess"

Come on, man.

**Comment by vove-RoR** [comment]
But Git Em! has and is essentially the same skill. Besides what would be the point to use it without an active pet? (not counting sinking your ap away)

**Comment by ozarmidrashim** [comment]
It doesn't matter. It has to be an actual bug, not a logical inconsistency, to be reported here.

**Comment by vove-RoR** [comment]
If you don't consider it a bug just close the ticket and it will stay in history for future reference. Isn't that why there is a bugtracker in the first place?

I was convinced it's not working as intended, there is no logic in attacking enemy together with your pet that doesn't exist. As I had no possibility to compare it I simply compared it to the mirror skill.

In the end if lack of logic isn't a bug I'm really sorry but from the other side I guess it's better to have false positives than no record at all.
