### ISSUE TITLE
Shaman ability: Nuthin' but da WAAAGH!

### ISSUE THREAD

**Issue by Meralors** [WarEmu/WarBugs#2780]
This tactic (Path of da green mastery) seems to not be working at all. It should lower the dmg dealed to the shielded target by 15% but I see no difference.

**Comment by Morksezstop** [comment]
nope, it is not supposed to do that. It suppose to increase the damage that the shielded person do while the shield last on him with 15%. Last time when i tested it /2-3 months ago/ the tactic was working

**Comment by Evildoor** [comment]
Tested, tactic works correctly, like Morksezstop said.
