### ISSUE TITLE
[Pets] Cannot send pet on an attack without LoS

### ISSUE THREAD

**Issue by vove-RoR** [WarEmu/WarBugs#2781]
There are issues with pathing of the pets.
1. First one is pets won't attack targets that are not in line of sight even if they are really close and you can target them/click them. Sending pet to attack someone behind a corner doesn't work- that person has to come out, then you can send your pet to attack and even if that person takes its previous spot behind the corner pet still chases him. There is an exception though as squig herder's spiked squig will still shoot through obstacles even if its owner cannot.
2. Second is that on some maps pets go for their target in straight line completely ignoring any obstacles (walls, fences etc.) on their way which is a significant shortcut for the pet. Haven't tested it that much but this happens in Highpass Cemetery (white lion's pet can go straight through the fence) and in the Lost Temple of Isha (squig herder's and white lion's pet can pass through walls in the middle of the map that are part of the entrance).

**Comment by noisestorm** [comment]
Comes from a general pathing issue - same happens for NPCs if you actually look at them. The LoS problem with shooting through walls is a seperate issue as well as the attacking problem you stated. normally pls open one post per problem so it can all be handled and closed as the single problems get fixed.

I'll just link https://github.com/WarEmu/WarBugs/issues/299 for now as a something similar was already reported. 

About the first problem you stated here with pets not attacking ppl that are out of LoS - can confirm and find it quite annoying myself, but i dont know if this actually is the proper behavior. If you can link a video where ppl can send their pets without LoS that may get us a chance to get it changed.

**Comment by vove-RoR** [comment]
I dig a little in patch notes using archived WAR webpages. This is what I've found in [patch notes for 1.2](https://web.archive.org/web/20120208103954/http://herald.warhammeronline.com/patchnotes/index.php?id=2009_1-2-0):
>* When instructed to attack a target on the other side of a closed door, pets will no longer run through the door. 

>* Pets will have a more accurate line of sight when trying to use abilities on their targets. 

Seems they were aware of pet issues and trying to solve it. On the other hand that's patch 1.2, so something might have changed after. If I found anything more I'll let you know.

**Comment by Zealote** [comment]
Tried this on mobs and I can send my war lion to attack when they're out of LoS of both my char and the lion.

I think this video (https://www.youtube.com/watch?v=FfilDuLX-40) shows that you should be able to -- i.e. that it's currently working correctly -- at about 12:20.
