### ISSUE TITLE
Bug defending the order keep at Ellyrion

### ISSUE THREAD

**Issue by zageen** [WarEmu/WarBugs#2785]
![Uploading Briquette_003.jpg…]()

I was defending the order keep at ellyrion when the screen turned as shown in the picture attached. I tried to log out/in several time but still the same. I can use some skills

My character is Briquette on the account of Siro60

**Comment by zageen** [comment]
![briquette_002](https://cloud.githubusercontent.com/assets/16636201/12222963/42a07b5a-b7cb-11e5-8b7a-05d152ff088f.jpg)

**Comment by noisestorm** [comment]
https://github.com/WarEmu/WarBugs/issues/2783
