### ISSUE TITLE
Constant Crashing and Disconnects

### ISSUE THREAD

**Issue by fippydarkpaw** [WarEmu/WarBugs#2786]
It seems to be happening only in Scenarios. Sometimes all players freeze and eventually the connection (or whatever is happening) will stabilize again and I can continue playing. Other times, all players freeze in place and I have to ctrl alt del out of the game and log back in. 

Not sure what's causing it.

**Comment by noisestorm** [comment]
Is already a known problem, lets hope for aza/londo to find the source of it.

**Comment by fippydarkpaw** [comment]
Thank you. Sorry I didn't see anything specifically about this when I searched.
