### ISSUE TITLE
Invalid creature

### ISSUE THREAD

**Issue by Vilberg** [WarEmu/WarBugs#2787]
It says to report, so I report. Not sure how to get this to a GM. Ignore / delete if this is not the right place to report it. 

http://i.imgur.com/qDb0cNB.jpg

"Invalid Creature,plz report to GM. QuestID 42404,Objid=12052 0 of 1"

**Comment by Meralors** [comment]
Fixed quest, you can now find and kill Aladris Garabor.
Live next patch
