### ISSUE TITLE
pack of un-attackable mobs Saphery Ch 14, dark elf

### ISSUE THREAD

**Issue by hartmnj1** [WarEmu/WarBugs#2789]
Just west of the chapter 14 in dark elf there is a pack of swordmasters that appear to be dead, but if you aoe they attack and you are unable to target them, only laying down aoe to kill them.

**Comment by Torquemadra** [comment]
You can target them by mouseclicking  and also attack them, there is a bunch of them across the world, I really should spend a day writing down the co ordinates of them

**Comment by Meralors** [comment]
Swordmaster of Hoeth won't be lying on the floor anymore.
Fixed next patch
