### ISSUE TITLE
[NPC] Wounded Griffon

### ISSUE THREAD

**Issue by Gothmakh** [WarEmu/WarBugs#279]
After helping the friendly NPC called Wounded Griffon in his fight against some maurader NPC, the Wounded Griffon switched agro to me. I could not defend myself, since the Wounded Griffon was blue to me (tagged as friendly).

![gothmakh_014](https://cloud.githubusercontent.com/assets/8167516/3584577/c245942a-0c1a-11e4-968c-9781a1401a61.jpg)
![gothmakh_012](https://cloud.githubusercontent.com/assets/8167516/3584580/c648c560-0c1a-11e4-83c9-72c5a526b851.jpg)

**Comment by DanaBloodkiss** [comment]
Fixed.
