### ISSUE TITLE
Timeworn Soul - Inevitable City

### ISSUE THREAD

**Issue by benitoben20** [WarEmu/WarBugs#2790]
Hello,

I've seen that all Timeworn Soul (Only the female one), in inevitable city, have a visual problem with their arms. It's nothing much, but it's a little bug i've find out. (See the picture)

Thank you !
![isas_007](https://cloud.githubusercontent.com/assets/16641170/12226322/2aa1b2b8-b7e8-11e5-9234-68996759d09e.jpg)

**Comment by Meralors** [comment]
Fixed, they shouldn't have arms flying away anymore :)
Live next patch
