### ISSUE TITLE
[NPC] T3 craft supply merchants without stock (e.g. Hugo Boehm and Voltz Reifsneider)

### ISSUE THREAD

**Issue by vove-RoR** [WarEmu/WarBugs#2791]
Found two supply merchants that offer nothing to sell.

1. In T3, there is crafting supplies vendor in Hergig Landing named Hugo Boehm. He sells nothing.
![image](https://cloud.githubusercontent.com/assets/16596013/12223258/fa2cd748-b7c9-11e5-8187-d9035122439c.jpg)

2. Another one is located in Raven's End (Voltz Reifsneider).
![image](https://cloud.githubusercontent.com/assets/16596013/12223302/0473ad20-b7cb-11e5-87b8-278683a641f9.jpg)

**Comment by vove-RoR** [comment]
I changed the title as it seems most of the vendors in T3 don't sell a thing (from the ones I spoke with none offered the crafting supplies).

**Comment by vove-RoR** [comment]
Closed by accident, sorry.

**Comment by DanaBloodkiss** [comment]
Fixed all Craft Supply Merchants.
