### ISSUE TITLE
Reducing chance to be critically hit 

### ISSUE THREAD

**Issue by zibiman** [WarEmu/WarBugs#2795]
The Reducing chance to be critically hit is just on 0% max and on live server it was going under 0% in minus nummbers like -10% or - 17% because the chance to be critical hit is adding to anemy critical hit chance if i have 10% chance to be critical hited and my anemy have 20% critical chance then my 10% are added to his 20% then he have 30% chance to land critical hit on me
![lalulila_000](https://cloud.githubusercontent.com/assets/16434526/12242094/b821df48-b89f-11e5-90a4-af0fa50af9cc.jpg)
![lalulila_001](https://cloud.githubusercontent.com/assets/16434526/12242095/b849a0f0-b89f-11e5-861c-24f6c7a06c75.jpg)

**Comment by Morksezstop** [comment]
i am pretty sure that on live you still got 0 from the stats view while the game was using the munus value for all the calculations

**Comment by zibiman** [comment]
0% was for pve to not get critical hit by pve montsters because they have o% criticalhit chance that why the must tanks have 0%  because of pve but u can make -% for pvp

**Comment by ozarmidrashim** [comment]
This is a client issue. Closing.
