### ISSUE TITLE
potions bugg?

### ISSUE THREAD

**Issue by Preddan** [WarEmu/WarBugs#2796]
I made some int pots and traded the half stack to a friend and they all is left on my bar.

![war 2016-01-11 19-18-53-27](https://cloud.githubusercontent.com/assets/16653361/12242509/d2aa2a92-b899-11e5-98fa-080374657945.jpg)

**Comment by Preddan** [comment]
I lost em after I relogged 2 times

**Comment by VUBITA** [comment]
And now too? Pots for 60 min. lost after 20 -25 min. After Fly, after to join sz.
