### ISSUE TITLE
Brigand axe 1h

### ISSUE THREAD

**Issue by Senss** [WarEmu/WarBugs#2798]
Hello the brigand 1h axe 
1)is only wearable on right hand when all other brigand 1h are either hand

thanks

**Comment by Evildoor** [comment]
Exact item name, please. Or screenshot.

**Comment by Senss** [comment]
"Brigand's Axe"

**Comment by Senss** [comment]
btw the "Brigand's Cleava" 1h for Choppa is   either hand + 2,5weap speed

**Comment by Styrkarr** [comment]
Fixed in next patch.
