### ISSUE TITLE
Worn Grimbraces

### ISSUE THREAD

**Issue by Marshmello2093** [WarEmu/WarBugs#2799]
just thought I'd show its not very important but there's a white lvl 2 item called Worn Grimbraces that have the icon of boots and don't seem to have an ingame model
![malkethor_000](https://cloud.githubusercontent.com/assets/16658455/12252414/b4c22cb6-b89c-11e5-8132-b668dad71722.jpg)

**Comment by Meralors** [comment]
They will be gloves now :)
Live next patch
