### ISSUE TITLE
[World object] Cannon missing

### ISSUE THREAD

**Issue by Gothmakh** [WarEmu/WarBugs#280]
During the quest *Return Fire* the player is supposed to use and fire a cannon. This cannon is not implemented yet.

![gothmakh_016](https://cloud.githubusercontent.com/assets/8167516/3584601/184ff464-0c1b-11e4-8075-157e7f04253c.jpg)

**Comment by Evildoor** [comment]
https://github.com/WarEmu/WarBugs/issues/118
