### ISSUE TITLE
Quest: Eaten Away

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#2801]
this quest does not show up on map and after looking all over the areas I cannot find the corpse cart
![skafgrim_037](https://cloud.githubusercontent.com/assets/13737673/12258172/98a8464e-b8da-11e5-93fc-e93bb7b0d748.jpg)

**Comment by Meralors** [comment]
The Festering Corpse Cart does exist. I added a questmarker to make it easyer to find it.
Live next patch.

**Comment by Shadowsmove** [comment]
I am still having trouble with this quest, I am not seeing the quest marker on my map. I think it may be because this quest for some reason does not show on the list beside the region map when you pull up the map. the quest is not listed with the others maybe that's why the quest marker is not showing on the map. Could this be causing the marker not to show?

**Comment by Gakvar** [comment]
I was trying to complete this quest and I can't find the cart anywhere either, I checked the graveyard where it's supposed to be, checked the carts around the farms and the town, none of them is the cart the quest refers to.

**Comment by EarlOfDitches** [comment]
Can't find the cart or at least quest marker anywhere.
Where it must be?

**Comment by lennip** [comment]
Update: I had the same problem, I finally found the cart and the body of Marquis Scholler (the guy we're supposed to find), they are near the entrance of the small cemetery in front of the Haunted Mill (facing Emp Chapt 14, on the other side of the river). But, neither the cart nor Scholler's body are clickable, so the quest cannot be completed. And there still is no quest marker on the map.

**Comment by Natherul** [comment]
fix coming next patch

**Comment by Soulwhisper** [comment]
Fixed @Luth-RoR .

**Comment by Coryisbored** [comment]
The body is not clickable anymore

**Comment by saupreusse** [comment]
works like a charm for me :S

**Comment by onkelll** [comment]
Quest marker shows it being in the big graveyard north of Ch 14, but apparently it's not supposed to be one of those three carts, but one with a corpse next to it by the windmill south of Ch 14. Problem is niether the corspe or cart are clickable.

**Comment by Sonnenritter1337** [comment]
![image](https://user-images.githubusercontent.com/64979746/82163530-e3e32380-9879-11ea-87c5-e6eb2130f826.png)
Neither the body nor the cart are clickable.
