### ISSUE TITLE
ToK Quest Log not tracking completed quests after relog

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#2805]
the ToK quest log does not save the status of a quest after logging out. Any time I log out and back in the mark for "quest completed" is reset to not being checked not matter how many of the quests in your list are complete. This does not affect turning the quests in or anything, you can still look at the quest page and see the objective has been finished, it's only in the full list of all quests where the mark is reset, so sorting by completed quests will not show any.

**Comment by Evildoor** [comment]
Known bug. However, i've not found any other reports for it yet.
