### ISSUE TITLE
[Item] Hardhat of Natural Rest

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#2806]
Hardhat of Natural Rest, inf reward for c9 high elf for engineers looks like it sits too low on head causing severe clipping

![ballistik_028](https://cloud.githubusercontent.com/assets/16200780/12259127/8ef341b0-b8e1-11e5-9c92-f40cf8f1acb3.jpg)
![ballistik_030](https://cloud.githubusercontent.com/assets/16200780/12259128/907698de-b8e1-11e5-9253-f2f2afc3d7f8.jpg)

**Comment by Ryanfawkez** [comment]
This issue is known to happen on some Devastator item models as well. There is no fix yet.

**Comment by Torquemadra** [comment]
Fixed next patch
