### ISSUE TITLE
Drakes Butchering / Apothecary Item Bug

### ISSUE THREAD

**Issue by dtru** [WarEmu/WarBugs#2809]
After butchering the drake type mob, there's an apothecary item in loot — displayed with no icon and it is uncollectable. 

Exact example: Deathridge Screamer (drake mob) that can be found here:
Talabecland (Rindlewood)
Coordinates: 25580, 11362

Same item appears on all mobs of such creature type.

Provided a screenshot attached.
![talabecland drake item bug](https://cloud.githubusercontent.com/assets/3666162/12271315/7049c38a-b96b-11e5-829e-3c041637eefb.jpg)

**Comment by Evildoor** [comment]
Dunno if drakes count as lizards (#1593) or not.

**Comment by dtru** [comment]
I think that's the same type, but it's not fixed then? 

BTW different lizards I've butchered — all was fine.

**Comment by nalgol** [comment]
fixed was a typo
