### ISSUE TITLE
39 and 40 lvl mobs in Lair of Silveroak cant be scavenged

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#2813]
No loot as well.

**Comment by Meralors** [comment]
Where is lair of silveroak? :p and if you have mobs names, would be even better! thx

**Comment by Torquemadra** [comment]
It's a puzzle area to get to by the destro starting area, you have to go all Mario and do jumps to access it. Leave destro start area head to water and follow the water edge to the right. Technically it's a t4 area in the t1 zone.

**Comment by Torquemadra** [comment]
In Nordland, sorry can't edit properly on phone

**Comment by MKorin** [comment]
16.5k / 25.5k Norsca.
Silver Dryad.
About a month ago scavenging works there.

**Comment by Ripliel** [comment]
Month ago Devs "fixed" it for some reason. No scavenging anymore

**Comment by Thayli** [comment]
They can be looted and scavenged.
