### ISSUE TITLE
Wrong rank of pots being produced

### ISSUE THREAD

**Issue by hartmnj1** [WarEmu/WarBugs#2814]
When making intelligence pots using a level 75 plant, 50 vial, 1 water, 50 resin, and 75 resin, I was producing intelligence pots for level 35 and higher. I should have been producing pots for the teens and end game.

**Comment by magicthighs** [comment]
https://github.com/WarEmu/WarBugs/issues/1644

**Comment by Evildoor** [comment]
Magicthighs is correct.
