### ISSUE TITLE
Keep getting ejected from my guild (not kicked)

### ISSUE THREAD

**Issue by Gobtar** [WarEmu/WarBugs#2815]
Everytime I log on my Black Orc (Gobtarsmasha) I am no longer in my guild. In the news log, I join the guild but don't leave or kicked. This might be caused by the database thinking I am in a defunct guild.
![guild](https://cloud.githubusercontent.com/assets/7888608/12286461/85e741fc-b99a-11e5-9efb-39b1ec7b2f44.png)

**Comment by Evildoor** [comment]
#948?

**Comment by Gobtar** [comment]
If it helps I should be in Magical Rainbow Ponies. I have only ever had this problem with this toon.

**Comment by Gobtar** [comment]
Similar to the issue, I this started when I attempted to join a different guild a couple of months ago, and that guild got deleted by the server or something along those lines. I have had this problem with this character ever since.

**Comment by Evildoor** [comment]
Then it's the same issue as #948, so i'm closing this.
