### ISSUE TITLE
Lost Temple of Isha and the crack of doom

### ISSUE THREAD

**Issue by vove-RoR** [WarEmu/WarBugs#2819]
There is this spot in the Lost Temple of Isha on the side of the zone with BO. You can fall there when entering from the side (not going through the main entrance). When you fall there you get stuck in flying animation (not touching ground, like permanently falling) and cannot do a thing. The other day I managed to angry jump out of it after few minutes but maybe it would be possible to add some soil in there or something.

![untitled](https://cloud.githubusercontent.com/assets/16596013/12302352/b5ef2db0-ba1c-11e5-8df6-8cbeedb19707.jpg)

**Comment by Evildoor** [comment]
While this was really annoying even on live... #2566

**Comment by vove-RoR** [comment]
Ok, it's just I've seen earlier someone was posting about getting swallowed by textures in Altdorf, thought it's doable.

If someone sees this entry be aware of the deadly crack in the Lost Temple of Isha next time you are there! :)

**Comment by Evildoor** [comment]
Ah, you mean #2783. It's not closed... Ok, i'll reopen this, since this issue occurs much more often than #2566 and seriously impedes those affected.

**Comment by Torquemadra** [comment]
Fixed next patch
