### ISSUE TITLE
[Item] Quest items still in inventory

### ISSUE THREAD

**Issue by Gothmakh** [WarEmu/WarBugs#282]
During some quests, the player has to gather some items and hand them to the quest giver. After he has done this, the items do not disappear from the players inventory. One has to destroy them manually.

**Comment by RoR-Zomega** [comment]
The "Dark Fate" quest in the Chaos starting area does not remove the "Bones of the Dead" items from the quest items back-pack slot when completed.

**Comment by RoR-Zomega** [comment]
The "Wicked Things" quest in the Chaos starting area does not remove "Vorque's Sackbag" when completed.

**Comment by RoR-Zomega** [comment]
The "The Heart of Battle" (part 1) quest does not remove the "Ancestral Chronicle" item when completed.

**Comment by RoR-Zomega** [comment]
Short-form time:

Quest: Foul Works (Chaos chapter 2)
Items: Charred Spores

**Comment by RoR-Zomega** [comment]
Quest: The March (Chaos chapter 2)
Item: Crawling Doll

**Comment by wargrimnir** [comment]
These should be removing correctly on completion now.
