### ISSUE TITLE
Order quest: Training Course

### ISSUE THREAD

**Issue by Squea** [WarEmu/WarBugs#2821]
If you talk to Elsa Schmidt and then join a scenario, you cannot turn in the final stage of the quest to Viktor Riese.

**Comment by Evildoor** [comment]
Strange. #1722 and some others should have been fixed...

**Comment by Ryanfawkez** [comment]
It was fixed, I've done it various times on newly created alts. Including the anomaly of joining a scenario before handing in the quest may mean there's a client side bug related to quest completion.

**Comment by DanaBloodkiss** [comment]
Should be possible. Closed.
