### ISSUE TITLE
Riding mount as a chicken

### ISSUE THREAD

**Issue by vove-RoR** [WarEmu/WarBugs#2822]
Normally you cannot use your mount while being a chicken. However, if you are mounted while being max level in current tier and you level up it doesn't dismount you changing you into a mounted chicken. It's not only visual, you still have the mount speed buff.

And yes, it looks hilarious.

![untitled](https://cloud.githubusercontent.com/assets/16596013/12323697/8b985d04-bab5-11e5-8849-fdbe2b64fd8b.jpg)

**Comment by vove-RoR** [comment]
Going to a lower tier on a mount and flagging yourself for RvR works correctly and dismounts you.

**Comment by Aelice** [comment]
Should maby be a feature for the next chicken apokalyps 😉
