### ISSUE TITLE
Crafting inventory bugging

### ISSUE THREAD

**Issue by nqte** [WarEmu/WarBugs#2823]
Hi RoR team,

First, I would like to thank you for your work. So here's my trouble :

The trouble : Since i was a lvl 100+ talisman maker on Snqp, i had 2 inventories allowed for the craft. But when i reseted the skill without taking the items off, i saw them back to their place on my Shnfnk character with a butcher lv 100+.As well, i cannot move them and they are unclickables.

The source : If you're using your twos (or more) crafting inventories, then you .respec without taking off the items, then the inventories seems to be bug on all chars.

Hope i didn't duplicated the post, however i'm sorry.

Regards,
Snqp

![2016-01-14_13h51_15](https://cloud.githubusercontent.com/assets/16589126/12324910/8893625a-bac6-11e5-983f-c913f26668e8.png)

**Comment by Evildoor** [comment]
#1548?

**Comment by nqte** [comment]
Nope, this is not the same thing. See on my screenshot, i've got the
talismans craft items on my *Shaman* *because* i respected my talisman
making *on* my *Squig Herder* so it just bugged the 2nd crafting inventory
on my account.

Regards,
Snqp

2016-01-14 14:34 GMT+01:00 Evildoor <notifications@github.com>:

> #1548 <https://github.com/WarEmu/WarBugs/issues/1548>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WarEmu/WarBugs/issues/2823#issuecomment-171646001>.
>



-- 
Despert Dimitri
Infographiste, webdesigner

dimitri.despert@gmail.com
+33 6 72 05 43 01
www.dimsigner.com

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
