### ISSUE TITLE
[Quest] Celestial Defender

### ISSUE THREAD

**Issue by Sortas** [WarEmu/WarBugs#2824]
http://www.warbits.com/gold-quests-1005-Celestial-Defender.html
![sortas_021](https://cloud.githubusercontent.com/assets/16688534/12325206/2d78260c-bad1-11e5-8657-7a29a5c00ab4.jpg)
next
http://www.warbits.com/gold-quests-1006-Celestial-Defender.html

**Comment by Evildoor** [comment]
This already has an issue opened - #2356, and you posted this in that report. Why duplicate it here?
