### ISSUE TITLE
Quest: Show of Power - Destruction

### ISSUE THREAD

**Issue by SATANICOMODERNO** [WarEmu/WarBugs#2825]
The quest says to kill the Bright Wizard Acolyte, but the BW acolyte isn't respawning or its taking too long. I'm waiting for 10 minutes and nada.
![shiima_000](https://cloud.githubusercontent.com/assets/14305777/12328875/952d68c8-bac4-11e5-9cde-a0a083270bea.jpg)

**Comment by Evildoor** [comment]
From some other ticket - "The quest text says that the "Bright Wizard Acolyte" is at the top of the tower."
The screen supplied does not looks like top of tower.

**Comment by SATANICOMODERNO** [comment]
I made this quest many times in the past and the acolyte always be in the site I show in the pic. Also the mark in the map leads to the same spot where i took the screenshot. Anyway, I'll take a look in the top of the tower. Thanks!

**Comment by Torquemadra** [comment]
He used to be outside the tower, he is now definitely inside.

**Comment by Evildoor** [comment]
No response, closing.
