### ISSUE TITLE
Magical salvaging

### ISSUE THREAD

**Issue by necropanda777** [WarEmu/WarBugs#2826]
hi, got something wrong with magical salvaging. if i break blue armor pieces it gives me white materials instead of blue ones. i dont have any pic to post sorry, but if u can try once u ll see it too.  i lost 6 blue armor pieces already and dont have anymore to take a pic and post it. Violet ones look like they work.
Thx for the help.

**Comment by Evildoor** [comment]
I think this is a problem of particular blue items. Do you remember their names?

**Comment by Torquemadra** [comment]
If you have a critical failure you get a fragment but its white, this event can be monitored under the "system general" filter tab. Are you certain you didnt have a failure?

**Comment by necropanda777** [comment]
y i know that, and i may had it 1 or 2 time. but with the crit failure u get only essence or a gold dust, not the white material, unless things changed after the last patch. And btw 6 failure in a row? is it possible? 
cant remember the name but they were 2 elms (1 for WE and 1 for Shammy) 1 chosen's chest, 1 off-hand weapon for zeally, arms for Dok and cant remember the last one. All blue, all 29/31 ranks.
Anyway i ll take a look the next time to see if i got crit fail.

**Comment by necropanda777** [comment]
p.s thanks for the answers.

**Comment by necropanda777** [comment]
ok so i was wrong it's not the skill bugged, it's a visual bug in the backpack, in the space where trade skill materials are.
basically i checked what i've done after yesterday and i saw that some spots looked empty but there was a material inside, other were empty even if the backpack was full (some material went to the main windows of it) and in the low left corner there was 1 single spot containing 3 diffferent material, all toughness but 1 blue 150, 4 white 150 and another 1 blue 150, all in the same square. when i click on it started to flash (like a strobe light), i mean first it was showing a blue one then the 4 white ones. i had to transfer all in main backpack windows to unbugged.
i hope i was enough clear to make u understand what happened, my english is a little rusty.
Thx again.

**Comment by necropanda777** [comment]
if u dont need/want any other info about i think we can close this one.

**Comment by nalgol** [comment]
this item flashing seams to happen if you use any auto sorting on the main bags then the client goes nuts and moves stuff around in crafting bag no clue why though

**Comment by necropanda777** [comment]
ok thx, i ll check if i got any auto sorting.

**Comment by Evildoor** [comment]
Items flashing was reported elsewhere. Problematic items should be reported individually. Closing.
