### ISSUE TITLE
Quest: Sanctified Ground

### ISSUE THREAD

**Issue by dryystn** [WarEmu/WarBugs#2829]
The Monastery gate won't open, can't kill Thomas the Champion inside and finish quest.

**Comment by Evildoor** [comment]
Where the gate is located? Zone, coords?

**Comment by dryystn** [comment]
Zone is Ostland, coords are 55, 47

**Comment by Evildoor** [comment]
#2074? Or there are 2 monasteries there?

**Comment by dryystn** [comment]
No you are right Evildoor, that seems to be the same monastery and Kushido's reply covers it.

**Comment by Torquemadra** [comment]
Tweaked quest placing Tomas the Champion in a hidden enclave outside the monastery so the chain can be completed. Will return to this when can fix door.
