### ISSUE TITLE
WE / WH No GCD after out of stealth ability

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#2831]
e.g. Enfeebling Strike

**Comment by Evildoor** [comment]
Is this wrong?

**Comment by ozarmidrashim** [comment]
-1 Doesn't know what he's talking about

**Comment by MKorin** [comment]
On live WH / WE cant KD or use other skill just after go out from stealth by skill like Enfeebling Strike, there was GCD like after any normal skill, now thers no time for reaction. On live first was animation from Enfeebling Strike and was time to cast 1 skill before you get kd now its instant.

**Comment by ozarmidrashim** [comment]
Again, wrong. The client does not show a GCD when any opener is used.
