### ISSUE TITLE
[Crafting] Stable potions have "volatile" description

### ISSUE THREAD

**Issue by vove-RoR** [WarEmu/WarBugs#2832]
I was leveling apothecary and used some materials to make an elixir. Unstability-Ometer said it will be 100% stable, yet all 4 potions I made have description "volatile" even though name of the potion doesn't say they are. Due to the rng and high cd on potions I wasn't able to determine whether this is only visual or not.

The recipe I used was: Apprentice's Glass Vial + Musty Elvish Parsley + 1 Stabilizer

![untitled](https://cloud.githubusercontent.com/assets/16596013/12362633/51f931d8-bbbc-11e5-8683-02cd994dcb34.jpg)

**Comment by vove-RoR** [comment]
This seem to affect all "fleeting elixirs" of uncommon quality. Rare ones don't have that description.

**Comment by magicthighs** [comment]
It's only visual, and yes, I noticed this too (but forgot to file a bug report, apparently).

**Comment by magicthighs** [comment]
Checked it ingame just now, it affects all potions made with elvish parsley (heal over time pots, in other words), not just the fleeting ones. If you use an extender to get the non-fleeting variety you still get a potion that says it's unstable in the description, but isn't really.

**Comment by genisaurus** [comment]
Fixed in next patch
