### ISSUE TITLE
[Quest] The Dark Heart of Avelorn 

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#2839]
Mission is not able to be completed has a unknown pre requisite 

Also Valeis Oakenstaff is lying on the floor "dead" until attacked by mobs

"Handing in" quest does nothing as unknown is still not fulfilled.

![untitled5554](https://cloud.githubusercontent.com/assets/16200780/12371818/687fa1e2-bc0e-11e5-824e-d706041c7c5b.png)

![untitled9999](https://cloud.githubusercontent.com/assets/16200780/12371819/6c6c2cb2-bc0e-11e5-9b0a-c1ab266c59dc.png)

**Comment by DanaBloodkiss** [comment]
Thank you for the report!Fixed in next.
