### ISSUE TITLE
Quest- Under A Rock

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#2847]
this quest auto completes, it is given by the NPC Alan Cartwright, he can be found in several areas.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
