### ISSUE TITLE
Quest- Healing Nature

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#2850]
the first two parts of this quest auto complete, it is found in Shadowlands at Sorrowstrand, High Elf Chapter 6.

**Comment by pixie126** [comment]
What I discovered in this quest, is that when you get to the part that wants you to heal corrupted roots, you can't.  The quest says to use the purified water on root.  Not in quest inventory, nor could I interact with any of the corrupted roots.  I could not complete this.

**Comment by NorKalli** [comment]
added scripting label; empty phial needs to be added upon quest pickup and scripted to transform into a filled phial once used near the lake.

**Comment by gimkus** [comment]
![image](https://user-images.githubusercontent.com/38866449/40009573-162af46a-57ab-11e8-97de-d06a079587e8.png)

noo bootle how fill it?

**Comment by Paleolog77** [comment]
Quest still not work. Phial not appeared, so i can't use it at lake.

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
