### ISSUE TITLE
Quest- No End To Danger

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#2851]
this quest auto completes, it is in High Pass, at Ravens End, in Empire Chapter 11

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
