### ISSUE TITLE
Quest- Houses Divided

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#2854]
this quest auto completes, it is in Avelorn, at Fernwood, High Elf Chapter 10, i think it is the last part of the chain, Report to Salanir Flamebreaker.

**Comment by Evildoor** [comment]
Maybe "divided"?

**Comment by Shadowsmove** [comment]
thanks, got it, sorry it's a little late (5:47am) for me, keyboards getting blurry ;) but I am done for now with these bugs

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
