### ISSUE TITLE
Bloodmarr camp unintended access

### ISSUE THREAD

**Issue by bwdaWAR** [WarEmu/WarBugs#2855]
There is a way to get into the Chapter 13 Chaos camp (Bloodmarr) up the hills in the back that is frequently utilised by Destruction players returning from killing the True Insanity Stalker boss. But Order can use the same way to get inside and kill the quest giver for True Insanity, and probably get further into the camp, potentially even into range for the skaven quest NPCs (didn't test that). The Stalker quest giver NPC will respawn in 2 minutes, so it's not such a big problem, but one of those rank 56 camp guards somewhere in that shrub next to the cages could still be useful.
![](http://i.imgur.com/zaoPddV.jpg)
![](http://i.imgur.com/EFriey3.jpg)

**Comment by DanaBloodkiss** [comment]
Thank you for the report!Added more Warcamp Guards!
