### ISSUE TITLE
[Quest] Welcome Back: Pacification

### ISSUE THREAD

**Issue by Gothmakh** [WarEmu/WarBugs#286]
The first step of this quest is buggy.

![gothmakh_001](https://cloud.githubusercontent.com/assets/8167516/3587383/8a164ea0-0c38-11e4-8104-cd0af81fe5fa.jpg)
![gothmakh_002](https://cloud.githubusercontent.com/assets/8167516/3587388/9923e16e-0c38-11e4-9774-c1d9069a825b.jpg)

**Comment by Reggaewaldo** [comment]
This has been fixed.

Closing.
