### ISSUE TITLE
[NPC] Palace Guard

### ISSUE THREAD

**Issue by Gothmakh** [WarEmu/WarBugs#291]
Some Palace Guards are tagged as agressive. Since they are lvl 40, they pretty much instant killed my lvl 9 toon.

Another problem: If you click on *respawn* you will respawn in the exact spot that you were killed at.... which is extremely annoying, since that is where an agressive lvl 40 guard is just waiting to kill you again.

![gothmakh_011](https://cloud.githubusercontent.com/assets/8167516/3596973/5623550e-0ccc-11e4-90ef-07096b128ba4.jpg)

**Comment by wargrimnir** [comment]
These guards are located just outside of the area with the RvR gear vendors. There are 2 of them, and they occasionally fight one of the Militiamen, so you'll frequently find at least one of them dead. Should be an easy fix.

.gps
http://i.imgur.com/ED2g6Z6.png

**Comment by Evildoor** [comment]
Second problem(respawn) was fixed. First one still persists.

**Comment by DanaBloodkiss** [comment]
Fixed.

**Comment by Evildoor** [comment]
Bug is either back, or was not fixed.

**Comment by Evildoor** [comment]
Fixed again.
