### ISSUE TITLE
[World Object] Brown

### ISSUE THREAD

**Issue by Gothmakh** [WarEmu/WarBugs#294]
There is a weird non-targetable object in Altdorf called *Brown*.

![gothmakh_019](https://cloud.githubusercontent.com/assets/8167516/3597103/c163260e-0ccd-11e4-8f15-b7de33b01cad.jpg)

**Comment by Reggaewaldo** [comment]
This should be resolved from what I can see in the DB.

I will verify later when I have access to the Dev server.

**Comment by Reggaewaldo** [comment]
Looked it up and it appears it was just a bugged cat. It is now fixed.

![kbctest_002](https://cloud.githubusercontent.com/assets/13517919/10123503/52afcf7e-653b-11e5-9c99-fb684cf9625c.jpg)
