### ISSUE TITLE
[Quests] Center of the World

### ISSUE THREAD

**Issue by Gothmakh** [WarEmu/WarBugs#297]
Although I visited all the areas, the corresponding quest steps do not get tagged as completed.

![gothmakh_025](https://cloud.githubusercontent.com/assets/8167516/3597176/728c331c-0cce-11e4-93be-809c605cd21c.jpg)

**Comment by wargrimnir** [comment]
These should be fixed, now that the appropriate map areas have been added to Altdorf.
