### ISSUE TITLE
[Quest] Seize Lost Lagoon

### ISSUE THREAD

**Issue by Gothmakh** [WarEmu/WarBugs#298]
The first step of this quest is broken.

![gothmakh_026](https://cloud.githubusercontent.com/assets/8167516/3597198/a06a8022-0cce-11e4-897c-24a56d666008.jpg)

**Comment by Evildoor** [comment]
Side note - i think this quest (as well as all quest related to the Lost Lagoon) should be removed from the game, since that's exactly what was done with the battlefield objective which you have to capture/scout.

**Comment by Reggaewaldo** [comment]
First step should include taking quest, talking to the lady again to turn it in since we don't have any way of checkin a "area flag".

**Comment by Reggaewaldo** [comment]
Closing this for now. We can come back to it later if we feel the need to alter it.
