### ISSUE TITLE
Dead elves attacking, public quests Blighted isle

### ISSUE THREAD

**Issue by jpnrd** [WarEmu/WarBugs#2983]
Some of the elves in two public quests i travelled through were looking dead but still were very fine alive :)  and following you, lying to the ground 

I tried to make a video but vlc couldn't stop crashing. so here's a few screenshots.

![ysachouine_001](https://cloud.githubusercontent.com/assets/16733126/12372685/6033122e-bc60-11e5-8d77-f978038fd825.jpg)
![ysachouine_002](https://cloud.githubusercontent.com/assets/16733126/12372683/6031e480-bc60-11e5-8844-f7d459bf841d.jpg)
![ysachouine_003](https://cloud.githubusercontent.com/assets/16733126/12372686/60339a82-bc60-11e5-9789-d7035f3ec50c.jpg)
![ysachouine_004](https://cloud.githubusercontent.com/assets/16733126/12372682/6030f4da-bc60-11e5-86c3-12d1af3bd7ea.jpg)
![ysachouine_005](https://cloud.githubusercontent.com/assets/16733126/12372684/6032710c-bc60-11e5-943b-a682555cbca7.jpg)
![ysachouine_006](https://cloud.githubusercontent.com/assets/16733126/12372687/60468322-bc60-11e5-9ac4-7384f7058f66.jpg)
![ysachouine_007](https://cloud.githubusercontent.com/assets/16733126/12372688/6049a994-bc60-11e5-9de8-c57bf1598d93.jpg)
![ysachouine_008](https://cloud.githubusercontent.com/assets/16733126/12372689/604b1798-bc60-11e5-85fd-f0c8757335df.jpg)
![ysachouine_009](https://cloud.githubusercontent.com/assets/16733126/12372690/604d02a6-bc60-11e5-9798-10cbdb5a1cd7.jpg)
![ysachouine_010](https://cloud.githubusercontent.com/assets/16733126/12372691/60543378-bc60-11e5-95a0-d6b9305c25a6.jpg)
![ysachouine_011](https://cloud.githubusercontent.com/assets/16733126/12372692/605bfe3c-bc60-11e5-8a4b-f5614f7042f0.jpg)

 I hope it helps.

I take this occason to say a HUGE THANK YOU to the devs for resurecting my favorite game ever! 

 Have a good day.

**Comment by Evildoor** [comment]
Don't bother with videos and screenshots in this case. Just provide exact names, and location.

**Comment by jpnrd** [comment]
Oh well! thank you i take a note of that ;)

**Comment by DanaBloodkiss** [comment]
Thank you for the report!Fixed in next.
