### ISSUE TITLE
[NPC] wrong pathing

### ISSUE THREAD

**Issue by Gothmakh** [WarEmu/WarBugs#299]
There are guards protecting the points players have to capture in battlefields.
In the battlefield of Nordland, there is a ship being guarded by guards. When they charge the player, they do no walk on top of the planks. Instead, they fall through those planks and attack the player from down in the water. They are even able to hit the player, although the guards should be out of melee range.

The player, on the other hand, cannot attack those guards since he cannot see the target (because line of sight is being blocked by the plank the player is standing on).

![gothmakh_027](https://cloud.githubusercontent.com/assets/8167516/3597240/6677c89c-0ccf-11e4-8003-a35bb1ddd0b7.jpg)

**Comment by Meralors** [comment]
Modified pathing seems to have solved the problem.
