### ISSUE TITLE
[Quest] Arming the Militia

### ISSUE THREAD

**Issue by Gothmakh** [WarEmu/WarBugs#302]
It is not possible to interact with the bodies of the dead marauders or militia men. Therefor it is not possible to collect their weapons and advance in this quest.

![gothmakh_006](https://cloud.githubusercontent.com/assets/8167516/3598415/6dd0ed72-0ce2-11e4-8b04-7ae534a5f85c.jpg)

**Comment by Evildoor** [comment]
https://github.com/WarEmu/WarBugs/issues/62
