### ISSUE TITLE
ORDER QUEST "A Sticky Situation" PART 1

### ISSUE THREAD

**Issue by Hauclir** [WarEmu/WarBugs#305]
![chaosdwarf_001](https://cloud.githubusercontent.com/assets/7598530/3607899/691c2618-0d53-11e4-9e3c-8d66f62f7463.jpg)
![chaosdwarf_003](https://cloud.githubusercontent.com/assets/7598530/3607932/228490d6-0d54-11e4-8d5c-46fb232438c9.jpg)
NPC QUEST GIVER: Lena Scherer
Unable to complete quest due to Gavin Scherer not being interactable to continue on to part 2 of A Sticky Situation quest.

**Comment by Reggaewaldo** [comment]
We can't fix this yet since we do not have a "interact with" quest completer. I will see if i can make a workaround.

**Comment by Evildoor** [comment]
Closing per #2658.

**Comment by SirEdrick** [comment]
Just a note: Gavin only spawns during the second phase of the public quest The Webworks. This might need to be fixed, or just add the note ingame.

**Comment by Thayli** [comment]
Seems Gavin was accidentally added to the PQ spawns. Now he should always be there, not only during stage II of the PQ.
