### ISSUE TITLE
Cannot use potions in the back pack

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#31]
User cannot use potions that are in the back pack. The character has the correct minimum rank.

![potions in backpack](https://cloud.githubusercontent.com/assets/7492543/2892822/904aa362-d541-11e3-9c2b-e2d2e735bb34.png)

**Comment by Evildoor** [comment]
If i understand correctly, overall potion functionality was implemented, and now each individual non-working potion should be reported, so i'm closing this.
