### ISSUE TITLE
[World object] chest

### ISSUE THREAD

**Issue by Gothmakh** [WarEmu/WarBugs#313]
There is an invisible chest that cannot be interacted with.

![gothmakh_001](https://cloud.githubusercontent.com/assets/8167516/3625439/97957bde-0e6b-11e4-9b9e-2f6244b9c3ae.jpg)
![gothmakh_002](https://cloud.githubusercontent.com/assets/8167516/3625440/9ba2a0e4-0e6b-11e4-906b-ec4769df6f35.jpg)

**Comment by Meralors** [comment]
This is a PQ chest reward, while fixing the PQ the "ghost" chest shouldn't be appearing anymore. For this PQ, its fixed.
