### ISSUE TITLE
[Interface] Bag Loot Preference 

### ISSUE THREAD

**Issue by Gothmakh** [WarEmu/WarBugs#315]
You can have 5 inventory bags and assign preferences to them, e. g. all weapon drops will be placed in bag 5.
You can actually check these different preferences via the user interface.

This feature does not work properly though. Every drop lands in the next available slot, no matter if you want it to be dropped into a special bag.

![gothmakh_000](https://cloud.githubusercontent.com/assets/8167516/3655380/e8f3b706-1178-11e4-9fd9-ea33207dce62.jpg)

**Comment by Evildoor** [comment]
Closing this since https://github.com/WarEmu/WarBugs/issues/573 is about the same problem but contains "additional information towards the known issue", according to Elven.
