### ISSUE TITLE
[Item] armor value calculation

### ISSUE THREAD

**Issue by Gothmakh** [WarEmu/WarBugs#316]
Although I am wearing some pieces of armor, my overall armor value is being displayed as zero. In these pictures, it actually should be 17.

![gothmakh_003](https://cloud.githubusercontent.com/assets/8167516/3655416/610a1a1e-1179-11e4-89a6-9a53786d7ed9.jpg)
![gothmakh_004](https://cloud.githubusercontent.com/assets/8167516/3655417/610ba7f8-1179-11e4-9711-7b18f74d0c23.jpg)
![gothmakh_005](https://cloud.githubusercontent.com/assets/8167516/3655418/610d3aa0-1179-11e4-8f9c-f830e5b09aa3.jpg)
![gothmakh_007](https://cloud.githubusercontent.com/assets/8167516/3655419/610f3850-1179-11e4-999a-98f7cb64a3fe.jpg)

**Comment by Reggaewaldo** [comment]
This should be solved.
