### ISSUE TITLE
[Interface] Inventory erroneously full

### ISSUE THREAD

**Issue by Gothmakh** [WarEmu/WarBugs#317]
Although I still have a slot left in my inventory, it is not possible to pick up another (last) item. Instead, the message *Cannot loot. Inventory overflowing. Open backpack to remove overflow.* appears.

![gothmakh_009](https://cloud.githubusercontent.com/assets/8167516/3655456/de4bfb00-1179-11e4-952a-19470959b601.jpg)

**Comment by Evildoor** [comment]
Fixed.
