### ISSUE TITLE
Items/gear disappear when u take them from a mailbox if your inventory is full

### ISSUE THREAD

**Issue by M34tb4lls** [WarEmu/WarBugs#342]
This afternoon (around 20:00 pm at Spain time, 19:00pm London time) I sended a mail between two characters of my account (character "Nietzsche" send that mail to character "Meatballs") with some gear I farmed before. When I log in Meatballs, I went to the mailbox to take the items, then I pushed the button "take all items" from the mail options and they disappeared at the moment, because my inventory was full. I started a post in the RoR forums asking about solutions ( http://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=825 ) and they redirect me at this site. I don't have screenshots to prove it (because I don't know that it will happen, now I know and I will provide screenshots if it happen again, but I will be careful knowing it) but I hope that someone can check it and confirm that this mail was sended and the items (all gear farmed) disappeared when I take them from the mailbox, and then try to fix it, and if it's possible try to return me the items that I have lost. 

Resuming it, the bug I report is that when u take items from a mail by "take all items" when u have the inventory full, or almost full enough that the items u take can't be on it, they disappear and there's no way to get them.

Waiting an answer for this problem. Thank you for your job.

PS: I will try to be as specific as possible and give details of this specific bug. I'm trying to make memory to remember the gear in question that I sended and lost in this bug and I'm almost 100% sure that were those items, u can check it if u have some way to see what was the content of the mail sended at 19:00 pm aprox, London time, between characters Nietzsche and Meatballs: 1x Galerunner's Knightseal, 1x Galerunner's Heater, 1x Galerunner's Faulds, 1x Galerunner's Helm, 1x Galerunner's Bookstrap, 1x Galerunner's Lash, 2x Galerunner's Matchlock, 1x Storm Courser's Matchlock, 1x Galerunner's Flamerobe, 1x Galerunner's Vambraces, 1x Galerunner's Mane, 1x Galerunner's Bulwark, 1x Galerunner's Runestaff. That's were the items I have lost in this bug.

**Comment by Evildoor** [comment]
Fixed. Now items stay in mail if your inventory is full.
