### ISSUE TITLE
My patience is eternal, friend

### ISSUE THREAD

**Issue by ozarmidrashim** [WarEmu/WarBugs#3458]
:)

**Comment by gofuckyourselfmuslimpigshit** [comment]
I dont think so you muslim cunt, you wont win this battle believe me, I am in the process of making a programme that will end this github repository.

Eat some dicks.

**Comment by gofuckyourselfmuslimpigshit** [comment]
MUSLIM PIGSHIT

**Comment by ozarmidrashim** [comment]
I can close every single spam issue you make in two clicks.

You lose!

**Comment by gofuckyourselfmuslimpigshit** [comment]
WHEN WW3 COME IM COMING TO KILL YOU

**Comment by gofuckyourselfmuslimpigshit** [comment]
I wont lose, you will sleep. and wake up with 1000000000000000000 posts

**Comment by gofuckyourselfmuslimpigshit** [comment]
ypu dirty muslim cunt

**Comment by gofuckyourselfmuslimpigshit** [comment]
Allah is a faggot peado nigger

**Comment by gofuckyourselfmuslimpigshit** [comment]
fuck your muslim religion you pigshit fucking cunt

**Comment by gofuckyourselfmuslimpigshit** [comment]
you wont win this, at all

**Comment by gofuckyourselfmuslimpigshit** [comment]
you might think you will, BUT NO
