### ISSUE TITLE
"Promise of Battle" Quest displaying unusual message

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#36]
The quest message for "Promise of Battle" from NPC Matthias Gelt, displays an unusual message in the quest missions.

![promise of battle quest](https://cloud.githubusercontent.com/assets/7492543/2894252/d4633636-d550-11e3-9bdc-431060d21802.png)

**Comment by Reggaewaldo** [comment]
Tested OK, this can be closed.
