### ISSUE TITLE
Quest Item and Rewards not showing up p2

### ISSUE THREAD

**Issue by Reorgael** [WarEmu/WarBugs#366]
So I started a Empire character and found some of the same issues.

The quest "Return Fire" requires you to destroy the Raven hosts cannons with your own, sadly there are no Empire cannons, they just aren't there.

In terms of Rewards not showing up the Quest "Supply Lines" will give you a choice of either dyes or a trophy. I picked the trophy and nothing happened, I completed the quest mind you and got everything but the item.

On perhaps a related note the first public events that you engage in, both Order and Destruction, are a little faulty. First of all it keeps coming up with Failed then might continue on, might not. Second is the end of event prize chest that you get, doesn't show. I have only confirmed the last point with the Destruction side of things, but the first point for both still stands.

**Comment by Reggaewaldo** [comment]
This is now fixed.

Closing.
