### ISSUE TITLE
[emulator] Inactive communication channels

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#367]
There are several channels in which one can communicate with others (I.E. /s for say, /advice for advice).

There are other popular channels that are none functioning, such as.

The command:

/t1:
The user can broadcast their message through the entire Tier region, within their realm (the oppsoite realm do not see) Inside that tier, including elfs and dwarfs zones.

/1:
Referring to region 1, which is similar to /t1 command. Except for one:

For example, a person in empire zone tier 1 broadcasts a message in /1 chat. It is only captured by the players in the empire zone (RvR and PvE). Dwarfs and elfs are ignored.

/2:

This channel is purely a RvR channel. Only players (of the same realm) in the RvR lake will receive this message. Anyone outside the lake or in another zone are ignored.

**Comment by Evildoor** [comment]
Many chat channels were added in recent patch, so i believe this can be closed.
