### ISSUE TITLE
Quest objective dot on the map

### ISSUE THREAD

**Issue by MaxHayman** [WarEmu/WarBugs#37]
When you're on a quest usually there are hints on the map which tell you where to go. Currently they are always set to an area around the order start area. 

Currently I've worked out some of the rest of the F_QUEST_INFO packet

```
Packet.WriteByte(1); //Objective count

Packet.WritePascalString(CQuest.Quest.Name); // quest name
Packet.WritePascalString("Return to your giver"); // objective name (blank unless your returning to a quest giver)

Packet.WriteUInt16(0x006A); //106 - Zone id
Packet.WriteUInt16(0x046D); // Type of marker (read below)
Packet.WriteUInt16(0x4D9E); // X coordinate (on the map when you push m) 
Packet.WriteUInt16(0xCB65); // Y coordinate (on the map when you push m) 
Packet.Fill(0, 18); // not sure why 18?
```
Marker Types (probably more);
0425 - Red Cave
0004 - single dot
046D - wide shape

I've been decoding one for Wolves Among the Sheep

```
00 00 01 00 03 00 00 09 4D 61 72 61 |............Mara|
|75 64 65 72 73


02 // objective count 
1C 57 6F 6C 76 65 73 20 41 6D 6F 6E 67 20 74 68 65 20 53 68 65 65 70 20 33 30 30 30 30 // quest name
00 // objective name
00 6A // zone id
04 6D // a rectangle
4D 9E // x
CB 65 // y
00 64 00 01 // some unks? perhaps indicate what objective there for?

1C 57 6F 6C 76 65 73 20 41 6D 6F 6E 67 20 74 68 65 20 53 68 65 65 70 20 33 30 30 30 30 // quest name
17 52 65 74 75 72 6E 20 74 6F 20 53 61 6D 75 65 6C 20 54 77 69 74 74 79 // return to smual twiffy
00 6A // zone id
00 04 // single dot
3B C3 // x
C6 A1 // y
00 00 04 00 // unks? (indicating when you've done objectives?)
```

**Comment by Reggaewaldo** [comment]
Verified Quest marker for the following:
A Son's sacrifice
Encroaching Darkness
Love Lost
Of Honor and Glory
Promise of Battle
Sick Feeling - Fixed the quest series.
The Emperor's Mandate
The End is Nigh - Fixed the quest conditions.
The Return of the Locket
Woebegone - Fixed the quest conditions.

**Comment by Reggaewaldo** [comment]
How should we proceed with this issue, should we tackle things as they appear or should we keep this open ?

**Comment by Evildoor** [comment]
This works for most of the quests i've come across, so i'm closing this and any other problematic quests should be reported individually.
