### ISSUE TITLE
Guild being repatedly deleted

### ISSUE THREAD

**Issue by phsampaio** [WarEmu/WarBugs#3785]
Our guild was apparently deleted, twice in this week. We had to reform it again the two times.
Guid Name: hCore
Level 4 or 6 (cannot remember exactly)
Guild Leader: Truekandur
Guild members: Tomate, Morvius, Arquimago, Adoky, Barbeiro (and others I can't recall now)

more info:
We formed ou guild the first time last week, and since then, it has disappeared twice, yesterday being the second time. The first time we had to actually gather 6 ppl again and create it again. Until this afternoon, the guild was ok. Now I logon about an 12h ago, and its not there anymore. I confirmed with other players, no one is in a guild anymore.

**Comment by Evildoor** [comment]
You already reported this in #2345, no need to create a separate report.
