### ISSUE TITLE
Ratgineer Zarkol and pet bug

### ISSUE THREAD

**Issue by Majakathi** [WarEmu/WarBugs#3789]
Found out that you can bug Zarkol for a easy kill with lion pet. Seems like if you die vs Zarkol while pet have a dot on him he will bug out where the pet was, then u can go back and kill him without him attacking you. Tested on a diffrent mob and it went back to normal when the dot was over

**Comment by Torquemadra** [comment]
https://github.com/WarEmu/WarBugs/issues/2627

**Comment by Evildoor** [comment]
Torquemadra is correct.
