### ISSUE TITLE
Recipe for Disaster Quest

### ISSUE THREAD

**Issue by qualteia** [WarEmu/WarBugs#3793]
Quest Recipe for Disaster, Order Badlands quest, is missing the dye rewards as you can see on warbits: http://www.warbits.com/gold-quests-1702-Recipe-for-Disaster.html and compare rewards to ingame ss. 
![recipe for disaster](https://cloud.githubusercontent.com/assets/16740013/12375838/72290c36-bc92-11e5-8ad9-eb2af048f186.png)

**Comment by DanaBloodkiss** [comment]
Thanks for the report!Fixed in next!
