### ISSUE TITLE
Quest:The Gift of War

### ISSUE THREAD

**Issue by Kallixenia** [WarEmu/WarBugs#3795]
when i want to turn on the quest , for the emblems , i keep getting messages

cannot salvage
inventory overflowing
open backpack to remove overflow

even if my inventory is half filled, and there is more than enough space in currency stash
i relogged fiew times and wait for lag check and still have that issue

**Comment by Evildoor** [comment]
Individual problem with unknown cause which has no solution so far, apart for server restart (see #2031).
