### ISSUE TITLE
History and Lore Unlock: Nomads

### ISSUE THREAD

**Issue by Laurell-Silentshade** [WarEmu/WarBugs#3798]
Going by old wikia notes. This I think is supposed to be unlocked by either being close to the Destro prologue portal or by interacting with screamer @ 30,10. Either method isn't producing this unlock.

**Comment by Ryanfawkez** [comment]
I'll see which Screamer I'll be able to add this to at the Norsca start point.

**Comment by Luth-RoR** [comment]
Reopening because https://github.com/WarEmu/WarBugs/issues/8416

**Comment by Lheana** [comment]
The Screamer behind the tent will trigger the unlock 'Nomads'
