### ISSUE TITLE
History and Lore Unlock: Norse Tribes

### ISSUE THREAD

**Issue by Laurell-Silentshade** [WarEmu/WarBugs#3799]
"From the Ch 1 camp, head east to the tents and approach a purple mutated tree (35k,12k)" from Wikia. Proximity unlock not working.

**Comment by Evildoor** [comment]
AFAIK, no ToK unlocks were implemented apart from chapters, noteworthy persons, NPC kills and armor sets, so everything else will not work, no need to report it.

**Comment by Ryanfawkez** [comment]
Evildoor, the Tome of Knowledge is currently under reconstruction, including these History and Lore ones. Proximity unlocks are not implemented yet, while we currently can fix the one's that require GO interaction.
