### ISSUE TITLE
Engage the Gorger[npc]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#3806]
21k/9k mob missing

http://warhammeronline.wikia.com/wiki/Engage_the_Gorger

should grant a bestial token

**Comment by Ryanfawkez** [comment]
NPC is there, look around a little more. He's right around the corner as you exit the Ogre/Gnoblar area.

**Comment by Tesq** [comment]
uhm i looked around but not anykind of that mob, it's suppose to be on the small mountain anyway on those coords but was nothing there. i will re check and close if that's the case

**Comment by Tesq** [comment]
it was in a slighter different place than live i close
