### ISSUE TITLE
[Tome of knowledge] Plumes of the eye killer

### ISSUE THREAD

**Issue by glasshands** [WarEmu/WarBugs#3807]
i cant seem to buy the cape and i did the quest
![window_015](https://cloud.githubusercontent.com/assets/14142017/12379233/3b5ca9c0-bd13-11e5-879e-e49adb4268d1.jpg)

**Comment by DanaBloodkiss** [comment]
Fixed in next.

**Comment by redcloudpl** [comment]
![thaer_001](https://cloud.githubusercontent.com/assets/16903246/12593975/163f67a0-c474-11e5-9c68-e548750dc332.jpg)
Unfortunately, this hasnt been fixed fully. I also have problem to get this cloak. This bug has also been reported via bugtracker.

**Comment by DanaBloodkiss** [comment]
Then you do something wrong. It's only a display problem in the Tome but you can go to the vendor in the capital city and buy the cloak.

**Comment by redcloudpl** [comment]
That is true Dana. I was able to buy coat, even tho that icon was missing from the TOme of knowledge. I think we can close this issue now.
