### ISSUE TITLE
Rune of Breaking

### ISSUE THREAD

**Issue by Souldinkou** [WarEmu/WarBugs#3808]
You are able to use rune of breaking to ghost stats. Normally when you activate it and turn it off it will switch your int and magic crit to will and healing crit which works like intended. However, You can equip a will/int set up use the buff than are able to switch armors and keep the willpower and heal crit from the first set.

**Comment by Evildoor** [comment]
Visual only, getstats shows proper stats.

**Comment by Souldinkou** [comment]
Yeah but the heals hitting higher, so how is that just visual?

**Comment by Evildoor** [comment]
Proof? My naked Zealot on dev server heals for the same amount with or without ghost stats.

**Comment by Souldinkou** [comment]
Guess it is just visual, not sure what I saw in the combat log last night but its fine now. Aside from the stats showing high in character stat window. Sorry, it just felt like cheating so thought id bring it up, Thanks.
