### ISSUE TITLE
visual bug - SM Stalker Boots

### ISSUE THREAD

**Issue by relic445** [WarEmu/WarBugs#3812]
After the recent patch a black line showed up circling the platecoat on SMs. here's a photo of what it looks like. 
![screenshot_003](https://cloud.githubusercontent.com/assets/16748760/12380268/b7f1486e-bd23-11e5-90d3-59628b385e4b.jpg)

**Comment by Torquemadra** [comment]
Note - thats shows only on the character selection screen and was there before todays patch

**Comment by Evildoor** [comment]
I doubt that we can do anything about this...

**Comment by Evildoor** [comment]
According to #4315, this is caused by boots (Stalker ones, for example).

**Comment by Torquemadra** [comment]
To fix this rare combination error on the boots would require the changing of 30+ items to a completely different appearance with no guarantee its not the chests at fault with another rare boot combination which would be another 30+ items. Given the infrequency of this and the ease in which it can be corrected with the appearance function I am not currently willing to spend the time on this as would likely cause further problems and restrict armor appearance options for the class.

**Comment by Torquemadra** [comment]
fixed next patch
