### ISSUE TITLE
Hat of the Duelist

### ISSUE THREAD

**Issue by Fiddlehero** [WarEmu/WarBugs#3814]
Whenever I equip the WH Hat of the Duelist, my character goes bald. As soon as I switch to any other headgear, my hair re-appears.

**Comment by Ryanfawkez** [comment]
Issues relating to hair on certain item models are known, it's a client bug that cannot be fixed yet.

**Comment by Evildoor** [comment]
Uh, how was #3800 fixed then?

**Comment by genisaurus** [comment]
By changing the appearance. Found a BW grille that looked exactly the same, or otherwise indistinguishable, more or less. That may not be an option for all classes

**Comment by Torquemadra** [comment]
Fixed next patch
