### ISSUE TITLE
Marauder weapon discrepancy 

### ISSUE THREAD

**Issue by Vandorkholme** [WarEmu/WarBugs#3815]
In Troll Country warcamp there is a quest where one of the selectable quest rewards called "Axe of the Dutiful" that gives +52 weapon skill, and only is useable in the main hand, which makes me believe it was supposed to be for a Chosen.

**Comment by Torquemadra** [comment]
or is an artifact from when maras didnt dual wield and instead had the main hand "duplicated" into their offhand

**Comment by Ryanfawkez** [comment]
http://www.warbits.com/gold-items-1970-Axe-of-the-Dutiful.html - Appears the same as on the current live server, don't think this has to be altered.
