### ISSUE TITLE
Slayer T3 ORVR Helms

### ISSUE THREAD

**Issue by Olszewski-Slayer** [WarEmu/WarBugs#3818]
i believe that these two armor pieces should read the same stats 
![olszewski_008](https://cloud.githubusercontent.com/assets/16567054/12381640/2a339296-bd5c-11e5-9e12-b8ea6932b621.jpg)
![olszewski_009](https://cloud.githubusercontent.com/assets/16567054/12381641/2cb51530-bd5c-11e5-9324-79f38f5e6298.jpg)

**Comment by wargrimnir** [comment]
Added Disrupt to these, as it was on several other pieces.
