### ISSUE TITLE
Killing mobs does not grant beastiary credit within party and proximity

### ISSUE THREAD

**Issue by jigsawed** [WarEmu/WarBugs#3820]
Issue: 
When killing enemy mobs/creatures, party members are not getting bestiary credit for kills within same party and within proximity of each other.

Background: 
A party member and myself were exploring elf-lands and killing elves and other assorted creatures of the like, and as we were attacking the enemies we quickly realized that we weren't getting bestiary credit for each others kills.  In 'live' if we were in the same party and within proximity i should be getting bestiary credit for anything my party members kill and vice versa.  

Troubleshooting:
We tried each 'tagging' the creature with damage, and this seemed to work in granting us both credit for sometime.  We were both getting credit in our bestiary for the kills.  Shortly thereafter after about 30 or so more mobs/creatures killed, we started to realize that 'tagging' the creatures was not accomplishing the goal of us each attaining credit for the creature kills within our bestiary.  Now even if I pulled the creature, my party member whom would kill it would *sometimes* get credit seemingly at random, and other times when they would pull, and I would do maybe-half-of-the-creature's-life-in-damage, and they would kill it, they would still get credit.  I would only get credit sometimes, and no amount of:
'who is pulling' 
'who is dealing the killing blow' 
'who is dealing the most damage' 
.. would determine whom was getting the credit in the bestiary for the kill.

Reason for bug report/community impact:
This is concerning because with the implementation of new PvE material and rewards that rely on the Bestiary, this bug will make it very difficult to work with other players to cumulatively obtain bestiary credit to obtain newly available rewards.  Basically it seems I am only guaranteed credit in my bestiary for creatures I pull, do the most damage to, and ultimately kill; if I work with another player in a party that also takes part in pulling/damaging/killing the creature I may or may not get credit seemingly at random, discouraging me from working with other players to obtain bestiary credit.

I am requesting someone look into this issue further to see if this is the expected and desirable behavior for the server, and if not to ensure that party members within proximity of each other when killing mobs/creatures within the warhammer world share bestiary credit within the party.  This will encourage players that desire bestiary-tied rewards to work together to obtain these rewards, and seek them out.

Replication: 
I was working on killing elves for by bestiary..

![elvesbestiary](https://cloud.githubusercontent.com/assets/16752405/12383798/3bd84a20-bd78-11e5-8372-847759b1cb19.jpg)

such as the elves found in this PQ (Tower Aspirant, Tower Acolyte, Tower Arbiter etc.) ..

![partykillbugdiscovered](https://cloud.githubusercontent.com/assets/16752405/12383756/c3061b90-bd77-11e5-9303-15c4f2ce516b.jpg)

.. when I realized that my party member was not getting credit for the kills I was making within their proximity, nor that I was getting credit for the kills they were making.

**Comment by Torquemadra** [comment]
Confirmed, there is no group credit, this is a flaw thats featured across about 50% of the missions too

**Comment by nalgol** [comment]
sorry gona fix it asap
