### ISSUE TITLE
Magus 5 piece Devastator proc

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#3824]
Is listed here http://www.returnofreckoning.com/forum/viewtopic.php?f=11&t=10645 as being an erosion proc which is lowering resistances 

Erosion - On Hit: 10% chance to lower all of target's Resistances by 150 for 10 seconds.

What we actually have is 

Corrosion - On Hit: 10% chance to lower target's Armor by 930 for 10 seconds.

Which gives nothing useful for the Magus per se but does give some hilarious mass armor debuff options with mist and all the aoes.....

Note- I dont have a full set of dev on my magus so cant test if its a tooltip error or misplaced proc.

![dev](https://cloud.githubusercontent.com/assets/16200780/12391047/e9d25078-bdb2-11e5-8b9f-6b383f1617aa.png)

**Comment by genisaurus** [comment]
Fixed in next patch.
