### ISSUE TITLE
Auction house not working after patch

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#3826]
when trying to make a new sell in ah it gets cancelled imidiatly.

**Comment by Torquemadra** [comment]
there is a 50 sale cap per person, are you hitting this?

**Comment by Tiggonos** [comment]
is that new? should be mentioned in patchnotes then. If possible also alter the cancel msg to "Auction Number limit reached" or similiar please.

**Comment by DanaBloodkiss** [comment]
This is not that new but you are right someone forgot to mention it.
