### ISSUE TITLE
Tome of knowledge Bestiary Nurgling quest : Getting it off Your Chest , not work

### ISSUE THREAD

**Issue by TaeBal** [WarEmu/WarBugs#3827]
<a href="http://imgur.com/9eHD7Bu"><img src="http://i.imgur.com/9eHD7Bu.jpg" title="source: imgur.com" /></a>

<a href="http://imgur.com/rdKaQPo"><img src="http://i.imgur.com/rdKaQPo.jpg" title="source: imgur.com" /></a>

Location : Tier 2 Dwarf "Barak Varr" (54221,50000)

When i click dead corpes -> nothing happen :)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
