### ISSUE TITLE
Eadplate of the Duelist

### ISSUE THREAD

**Issue by manningus** [WarEmu/WarBugs#3828]
This new Black Orc helmet has no changed stats - got the same like old Devastator

**Comment by genisaurus** [comment]
Not a bug. The stats on the helmets are intended to be the same. See:
https://docs.google.com/spreadsheets/d/1A6KjlKYjFz2VzFHi8z6ibqH1HzlAh_YpXKfKDIilTr0/edit#gid=2012868967

**Comment by manningus** [comment]
Ok,  sorry for your time,  missed this file:) thanks for great job,  mng


Odesláno z aplikace Outlook Mobile






On Mon, Jan 18, 2016 at 2:18 PM -0800, "genisaurus" <notifications@github.com> wrote:












Not a bug. The stats on the helmets are intended to be the same. See:

https://docs.google.com/spreadsheets/d/1A6KjlKYjFz2VzFHi8z6ibqH1HzlAh_YpXKfKDIilTr0/edit#gid=2012868967
