### ISSUE TITLE
[Item] Scroll of Altdorf triggers cooldown when not used

### ISSUE THREAD

**Issue by vove-RoR** [WarEmu/WarBugs#3831]
I got my Scroll of Altdorf today and when I wanted to use it turned out I cannot since I was in a RvR zone. That's ok but even though I haven't used the item it triggered cooldown on it and I couldn't use it for another hour.

As a side note: it's also an instant cast, shouldn't it have casting time like the Book of Binding?

**Comment by Ryanfawkez** [comment]
As a custom item, it cannot have a channeling teleport timer, so it has to be instant teleport. You can actually negate the cooldown timer's effect by relogging; item can be used despite its apparent cooldown status.
