### ISSUE TITLE
WP with shield

### ISSUE THREAD

**Issue by Olszewski-Slayer** [WarEmu/WarBugs#3832]
WP with shield lol

![olszewski_003](https://cloud.githubusercontent.com/assets/16567054/12407796/8f9e2b60-be28-11e5-9788-f91e048d7cd2.jpg)

**Comment by Torquemadra** [comment]
Ryan added that in to see how the community would react, its a book appearance item

**Comment by Olszewski-Slayer** [comment]
They can make my rofl-copter into a griffon?  I honestly hate the copter. Never used it on live. I had a Griffon. I would like to see dwarfs riding a awesome looking ram or wild looking boar!

**Comment by Landaren** [comment]
If we're going to start fixing appearance items then do it for all of them.

**Comment by Tiggonos** [comment]
altering apearence so archetypes look like different archtypes is imho a very bad idea.

**Comment by Olszewski-Slayer** [comment]
Dunno y ppl posting things like this ^ when it was a joke question just like the joke they turned the book to shield. I've been playing since warhammer online started. I fully understand they couldn't,wouldn't, change my copter to a Griffon. So let's drop the lame comments for this topic.

**Comment by genisaurus** [comment]
Intentional Change
