### ISSUE TITLE
pegasus kill count bugg 

### ISSUE THREAD

**Issue by guiltanas** [WarEmu/WarBugs#3833]
I was going for the Pegasus 1000 kill achievement put there seams so be a bug where I got 1000 kills when I had just 912 I since then killed the last 88 but there is obviously something wrong. 

![screenshot_1](https://cloud.githubusercontent.com/assets/16751630/12408741/ca1aa8fa-be63-11e5-884c-72d18d1b0d3d.png)

**Comment by TaeBal** [comment]
<a href="http://imgur.com/waUzd0i"><img src="http://i.imgur.com/waUzd0i.jpg" title="source: imgur.com" /></a>
<a href="http://imgur.com/XKVYk08"><img src="http://i.imgur.com/XKVYk08.jpg" title="source: imgur.com" /></a>
<a href="http://imgur.com/1HigCol"><img src="http://i.imgur.com/1HigCol.jpg" title="source: imgur.com" /></a>

Same here 
I was killed unicon and pegasus
But count is not work
But total count is work

**Comment by genisaurus** [comment]
A few issues at play here: 
The first is with the creatures killed having either the wrong Major type or Sub type. This is an easy fix... if we know every creature that should be classed as a pegasus. Could probably take a census, but it's low priority. There are also 150+ subtypes, so this would need to be done for almost every creature.

The second issue is that the bestiary counter might not be counting subtypes, only major types in this instance.

**Comment by Evildoor** [comment]
Should be fixed.
