### ISSUE TITLE
Healing potions (maybe) not working properly

### ISSUE THREAD

**Issue by bwdaWAR** [WarEmu/WarBugs#3834]
I'm going to start with that this is more of an impression, as I wasn't able to find anything in the combat logs, but it happened several times so I'll post it all the same in case it's actually a bug.
When I use an instant healing potion very close to death (about 5% health), I do not notice any sort of healing, and I die less than a second later. But the potion is used up, and the potion type is put on the 5 minutes cooldown.
It's possible that the healing actually happened, just the damage was too much for it to matter, but still, death happens pretty much immediately after clicking the potion, plus these potions heal 832 HP (Draught of Healing) on a 4720 HP character, that's around 17%, so it'd likely buy a second or two. Healing debuff is also a possibility, but the character is a WL, not a healer... But like I said, I wasn't able to find anything in the logs about this.
If I'm not mistaken about this, then it's possible that the potion use and the subsequent cooldown triggers immediately before death, but the healing delays afterwards for whatever reason and so it doesn't happen. Or the potion use and cooldown happens immediately after death. I'll also note that I never really have noticable lag issues, such as the melee ability range problem.

**Comment by bwdaWAR** [comment]
I did some testing and I managed to reproduce the effect. In this screenshot, you can see the healing potions on the 5 minute cooldown, but the healing doesn't appear in the log.
![](http://i.imgur.com/8BqoAz2.jpg)
And in this screenshot, you can see the healing shown in the log (same settings) earlier when I couldn't time it right:
![](http://i.imgur.com/zyL9EgR.jpg)
The important part of this is that the potion use must happen almost exactly the same time when the deathblow happens, maybe 0.1-0.5 second earlier. The potion is used up, it goes on a cooldown, but the healing itself doesn't happen.

**Comment by Evildoor** [comment]
Seems questionable to me. 0.1-0.5 seconds is too small time window which gets impacted by potion delay, lags, etc. I doubt that much can be done here apart from fixing potions being usable when dead.

**Comment by vove-RoR** [comment]
It's rather related with lag as Evildoor mentioned and not only potions are affected. Many times you gonna get your cds on skills that didn't work because you died.

Maybe it is a little bit unfair but works both ways, you can heal someone from the dead, I've seen that happen many times. Someone dies but I manage to heal him right before server "notices it" bringing him back to the land of the living without having to rez and without triggering the resurrection debuff.

**Comment by Evildoor** [comment]
Closing this since nobody provided information contradicting my statement.
