### ISSUE TITLE
Dissolving mist failing - demonic reach

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#3835]
This is similar to trying to place demonic infestation/mines just out of reach, the ability goes on cooldown but nothing gets placed. This still causes mist/infestation/mines to fail 100% of the time

However I have had dissolving mist failing an awful lot today even when placing well within the range. I can replicate this reliably.

If you are moving and place mist within 65ft, mist will be places as it should.

If you are moving with the demonic reach tactic (+25% range on changing abilities) placing the mist between 65 - 81ft fails and causes a cooldown.

Placing mist outside range always puts ability on cooldown with no mist placed.

**Comment by Tesq** [comment]
it should put it in the max distance in that direction instead.

**Comment by ozarmidrashim** [comment]
Tested and works. Any issues will be related to the previously known problem with ground-target abilities.
