### ISSUE TITLE
ToK - Not counting squigs....ish

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#3836]
Yesterday the ToK was counting my squig kills as I figured I may go for the 100k squig kills, it ticked off 25 and I went to sleep. Today I have over 200 squig kills, from the same location as yesterday but it hasnt ticked off the 100 squig kills marker

![sqi](https://cloud.githubusercontent.com/assets/16200780/12410183/3d39fe0e-be40-11e5-9f84-7700ff093f55.png)

![squig](https://cloud.githubusercontent.com/assets/16200780/12410187/401d3b04-be40-11e5-85fd-c3db453976c6.png)

**Comment by DanaBloodkiss** [comment]
This should be fixed by this patch. http://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=10941
