### ISSUE TITLE
Burning Windmill Public Quest (ORDER)

### ISSUE THREAD

**Issue by Jonzac** [WarEmu/WarBugs#3837]
The PQ "Burning Windmill" Stage 1 (Kill 50 Horrors) works perfectly.  Stage II is supposed to make the Seeker Cultists change from neutral to hostile and drop the invulnerability sphere around them.  The cultists do neither and the PQ cannot progress and always fails.

**Comment by Evildoor** [comment]
Do not report Public Quest staff, they are not implemented.

**Comment by Jonzac** [comment]
Ok sorry
