### ISSUE TITLE
Specific Potions Will Not Work

### ISSUE THREAD

**Issue by Jonzac** [WarEmu/WarBugs#3838]
The following potions do not work and do not have a "USE:" description in where the effects are noted.  All potions that do have that information work as required.
Initiate's Fleeting potion of clout
Initiate's potion of clout
Initiate's fleeting corporeal screen potion

Lasting Initiate's lasting elixir of allaying. WORKS -Nork
Initiate's warming draught WORKS -Nork

**Comment by genisaurus** [comment]
Are these particular potions crafted, or dropped from NPCs?

We have duplicate entries in the database.

**Comment by Jonzac** [comment]
They are rewards from quests. The few potions I have crafted all work. Additionally the few quest reward potions that work (almost all healing) do not show up on the potion bar add on

**Comment by NorKalli** [comment]
removed an item that does work

**Comment by aengie666** [comment]
The potions I make are not movable in my pocket (Fabricated Journeyman's Glass Vial).

Greetings aengie666 / Michael

**Comment by sioding** [comment]
fixed with patch from 01.06.2019
