### ISSUE TITLE
A Servant's Duel - missing quest.

### ISSUE THREAD

**Issue by Munds1** [WarEmu/WarBugs#3840]
I have a problem with quest in Avelorn "A Servant's Duel" with reward item Stalker's Gloves.

I finished it and received reward just before server restart and new patch 17.01.2016. After log in again reward missing and i cant take this quest again. I just want to do quest again, so I write email to gm Elven and wait for some server restarts. Till now nothing helped so I past problem here like Elven said. I think mine char will be only one bugged so maybe someone can reset that quest on mine char for me (char nick in game: Flog)?
 
![flog_000](https://cloud.githubusercontent.com/assets/16772770/12412222/61b831a2-be85-11e5-856a-0776d99880c0.jpg)

**Comment by Evildoor** [comment]
To me this looks like work for GM, since problem is clear (repeatable quest is not repeatable) but only affects one character, while bugtracker deals with server-wide issues... But since Elven send you here, we'll see what others say...

**Comment by DanaBloodkiss** [comment]
Hello,
I think it's only bugged for you cause of the server restart.Please wait for Elven to asnwer.
Greetings
