### ISSUE TITLE
Problem with quest item 

### ISSUE THREAD

**Issue by shmolik** [WarEmu/WarBugs#3843]
Quest line (An Army Marches), at the NPC Brother Lance, is in a raven's repartition, location 11-59. At the end of the line quest to kill the magician in the Temple Changes at the top of the stairs, the coordinates of 28,47 (map). At the end of the quest, return to Brother Lance and get the cloak (24 lvl) on 3 types of resistance to 60 with one or two slots for talismans.

**Comment by Evildoor** [comment]
Uh, and what's the problem?

**Comment by Ryanfawkez** [comment]
I think he's referring to the Crimson Cloak quest, which awarded a blue cape with all 3 resistances 60+, and two talsiman slots.

**Comment by shmolik** [comment]
no magician, no cloak

**Comment by shmolik** [comment]
no magician, no cloak

**Comment by shmolik** [comment]
no magician, no cloak

**Comment by Evildoor** [comment]
According to Ryanfawkez' comment above, cloak is a reward for different quest.

**Comment by Evildoor** [comment]
No proper information provided, closing.
