### ISSUE TITLE
Wrong ToK unlock, dwarf ironbreaker

### ISSUE THREAD

**Issue by Meralors** [WarEmu/WarBugs#3844]
Not sure why as I can't check db yet, but I got 100kill unlock before 25. Also only killed 5 of them, weird..
![kortex_000](https://cloud.githubusercontent.com/assets/11932648/12424170/2cc2d89a-becf-11e5-8cca-31eb2f8a2bee.jpg)

**Comment by Ryanfawkez** [comment]
Nalgol messed up the code. Was mentioned to him last night when he tried to fix total killcount bestiary tracking, we haven't heard from him since.

**Comment by Evildoor** [comment]
Should be fixed.
