### ISSUE TITLE
War is upon us quest broken. T2

### ISSUE THREAD

**Issue by Partizan-Rusi** [WarEmu/WarBugs#3846]
War is upon us quest broken. T2 quest. Just noticed you can't complete it  http://i.imgur.com/HKCod0A.jpg

**Comment by vove-RoR** [comment]
It might be visual as normally you have to slay 50 of each race for that q, not only greenskins.

**Comment by Evildoor** [comment]
You logged on a character which you've not played in a long time? This kind of things happened when quest was changed from 150 kills to 50 of each race - however, in such case i was able to turn the quest in immediately. This is different for you? If yes - maybe abandoning the quest and taking it again will solve the problem?

**Comment by Partizan-Rusi** [comment]
I was unable to finish this quest 100%. Now when I dropped quest and spoke with Warmaster npc it shows me different quest. We'll see how it goes.

**Comment by genisaurus** [comment]
Quest is working fine - this is an issue from when the quest objectives were changed. Abandoning and retaking the quest should clear the issue.
