### ISSUE TITLE
WP grave buff and bug RP

### ISSUE THREAD

**Issue by Tholkienn** [WarEmu/WarBugs#3847]
It seems that spam the LP buff will give RP, by tick of 21.

**Comment by Evildoor** [comment]
What's "LP buff"? Also, keep in mind that you get RP ticks for healing others - this can happen even in some questionable situations, like playing a scenario and then healing allies in PVE.

**Comment by Landaren** [comment]
I think he means the Sigmar's Grace buff, that adds wounds. It counts as a "heal" even if your party members are at full health.

**Comment by Tholkienn** [comment]
Yes is that!
And you of fight, you can spam it.

**Comment by Evildoor** [comment]
So, Sigmar's Grace counts as heal even at full HP and can be used to get renown ticks after participating in PVP like i mentioned above? Not a bug then.
