### ISSUE TITLE
[Crafting] Cultivating - spores marked as seeds

### ISSUE THREAD

**Issue by vove-RoR** [WarEmu/WarBugs#3848]
While leveling cultivating I noticed **sometimes** spores are considered seeds. In the cultivating ui they have the growing background of a seed.

This is only visual and in the end you still harvest the correct mushroom however it is not happening 100% of the time, sometimes same spore is a spore and sometimes it's a seed.

1. Spore considered spore when growing.
![untitled2](https://cloud.githubusercontent.com/assets/16596013/12430296/d1606cb6-bee6-11e5-93ff-dabe068d88c3.jpg)

2. Different spore considered seed (with background for a seed instead of the cave)
![untitled](https://cloud.githubusercontent.com/assets/16596013/12430330/f8b549a8-bee6-11e5-8686-19ea6644ff10.jpg)

3. Spore from point 2 but this time correctly marked as spore
![untitled3](https://cloud.githubusercontent.com/assets/16596013/12430348/0b87a29c-bee7-11e5-805e-c4f32ea6ddb2.jpg)
![untitled4](https://cloud.githubusercontent.com/assets/16596013/12430414/65836ab0-bee7-11e5-851c-46b818a5a12a.jpg)

Spore from point 2 was a loot from mob (let's call it spore A). Spore B (from point 3) is the mushroom that grew from spore A converted into the spore again. But I don't think it would matter as both items would have the same ID anyways?

**Comment by nalgol** [comment]
the old loottables contain outdated crafting materials that's why you cannot stack looted and harvested spores / seeds
