### ISSUE TITLE
TOK - Bestiary not unlocking

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#3852]
May be slightly related to this https://github.com/WarEmu/WarBugs/issues/3820

My wife killed a dragon and got the appropriate tome unlock and can go to the dragon pages within the ToK, I received credit for the kill adding to my count of dragonoids in the bestiary but I did not receive the tome unlock and I am now unable to receive the unlock at all regardless of how many I kill.

**Comment by Ryanfawkez** [comment]
There's a bug in the code related to total killcount tracking, by which killcount objectives cannot be completed as normal.

**Comment by Torquemadra** [comment]
Just to clarify, first dragon kill, my wife got unlock, I did not but it counted the kill. Consequent dragon kills not opening the ToK section and is unclickable.

![drag](https://cloud.githubusercontent.com/assets/16200780/12439617/78391718-bf00-11e5-83f0-eba24c373ae4.png)

**Comment by Evildoor** [comment]
Should be fixed.
