### ISSUE TITLE
History & Lore: The Beastmasters of Karond Kar

### ISSUE THREAD

**Issue by Laurell-Silentshade** [WarEmu/WarBugs#3855]
Manacles of Wrought Iron not interactable. Blighted Isle: 14530, 47785

**Comment by Ryanfawkez** [comment]
Has a ToK unlock on the dev server, will be fixed in next patch.

**Comment by Lheana** [comment]
The Manacles of Wrought are still not interactable, and so don't provide the H&L unlock.

**Comment by Lheana** [comment]
Fixed now !
