### ISSUE TITLE
[Greenskin chapter 13] Can't receive influence rewards from rally master

### ISSUE THREAD

**Issue by milosxe** [WarEmu/WarBugs#3857]
As the title says, can't pick rewards from rally master in greenskin ch13, Gorthug.
Was hoping to get the staff for appearance and the inf was kinda annoying to farm :p.

![xiuxiu_003](https://cloud.githubusercontent.com/assets/13332067/12441307/df2da192-bf45-11e5-90ff-b5279449b657.jpg)

**Comment by Meralors** [comment]
Did you try relogging? Sometime its a temporary bug

**Comment by milosxe** [comment]
I did. Screen was made after a relog. And I tried once again just to be sure.

**Comment by Evildoor** [comment]
#2122
