### ISSUE TITLE
Champion Manticores in Ellyrion

### ISSUE THREAD

**Issue by ArdzofPT** [WarEmu/WarBugs#3858]
Two named Champions in the south of Ellyrion near the bridge are unattackable.  They are Vamalath and Malinora.

**Comment by Ryanfawkez** [comment]
Would they be required to kill for any quest/drop, by chance?

**Comment by ArdzofPT** [comment]
Not sure about that.  I came across them on my way to do Rally Master visit
quests and was worried that I'd aggro one of them unintentionally.  Turned
out I couldn't.

**Comment by ArdzofPT** [comment]
Though champs tend to have better drop rates, so I suppose it would be nice
to be able to kill them.

**Comment by Torquemadra** [comment]
Just run of the mill champions, nothing special in loot tables but their Z axis spawn puts them high in the air out of range, just a glitch showing them on the floor. Fixed Malinoras axis from 8896 and moved Vamalath down and to the side so hes not blocking the path so completely.

Fixed next patch
