### ISSUE TITLE
barber

### ISSUE THREAD

**Issue by Kouba85** [WarEmu/WarBugs#3859]
Hi, i tryed to go to barber surgeon in Altdorf to see another look of my character. I hit the button to change look but nothing done. But after reload my character has new look.
![snorrri_027](https://cloud.githubusercontent.com/assets/15944509/12445643/c8b130da-bf65-11e5-8b35-800d2afc51b0.jpg)
![snorrri_031](https://cloud.githubusercontent.com/assets/15944509/12445644/cdbcf1f4-bf65-11e5-93cd-6f1be3e6969e.jpg)

**Comment by vove-RoR** [comment]
#1403

**Comment by xyeppp** [comment]
Barber got fixed in the last patch. This is how he works now - you click check out and relog for the change to apply. Patchnotes haven't been posted yet, but this is not a bug.

**Comment by Torquemadra** [comment]
Confirmed, its functional, awesome.

**Comment by Evildoor** [comment]
#1403
