### ISSUE TITLE
Bestiary: Tainted Grove Spite

### ISSUE THREAD

**Issue by Laurell-Silentshade** [WarEmu/WarBugs#3861]
The unlock requires a drop "Tainted Spite Essence". At the moment this hero doesn't even drop money so I'm assuming this is yet to be implemented. Just thought I'd bring that one up.

**Comment by Ryanfawkez** [comment]
ToK unlocks relating to item interaction/obtainment cannot be fixed yet.

**Comment by ArdzofPT** [comment]
Essence is dropping. It didn't drop every time on live.
