### ISSUE TITLE
Guild being deleted all the time

### ISSUE THREAD

**Issue by SATANICOMODERNO** [WarEmu/WarBugs#3862]
Hello guys. Some time ago my friends and me created a guild in RoR called hCore. And today, for the fourth time, our guild was deleted. No one did it. The leader didnt make it. The guild is being suddenly deleted. 

Guild name: hCore
Last leader name: Khandur lv 26 rr 23

**Comment by Evildoor** [comment]
You guys already reported this twice. That's enough. #2345 is a main ticket.
