### ISSUE TITLE
[ToK] Kill 25 skavens dont trigger

### ISSUE THREAD

**Issue by Averatos** [WarEmu/WarBugs#3863]
![averatos_000](https://cloud.githubusercontent.com/assets/16805605/12461493/7c8b644c-bfb9-11e5-95a6-c818aea712fd.jpg)

It triggers for100, but not 25.

**Comment by Torquemadra** [comment]
Note - achieved the 25 skaven kill today from kills in the event maze.

![ska](https://cloud.githubusercontent.com/assets/16200780/12474813/0c72525a-bfec-11e5-8196-ec613b0aae39.png)

**Comment by DanaBloodkiss** [comment]
Any confirmation that this is still not working?

**Comment by Averatos** [comment]
Im off on work untill the 29th. I confirm when I return.

**Comment by Averatos** [comment]
yes, the kill 25 triggers for me now. but my ToK have ben reset.... :( 
![averatos_001](https://cloud.githubusercontent.com/assets/16805605/12651341/80742408-c5e6-11e5-83d4-d207c8edefd2.jpg)

**Comment by DanaBloodkiss** [comment]
Great. Closed.
