### ISSUE TITLE
no GUI

### ISSUE THREAD

**Issue by Razielx** [WarEmu/WarBugs#3864]
Everything was fine. and then i enabled healgrid and i lost everything. only things i can see on my gui is healgrid box, chat, and pure unitframes. when i hit esc nothing happens. i removed all mods from addon folder and that didn't help

**Comment by vove-RoR** [comment]
This is not a bug.

You should try that on technical forum. Removing the addons only won't help you, you have to wipe clean the configuration folder for your character to restore the defaults.
