### ISSUE TITLE
[ToK] Daemon Vine unlock Bugged

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#3865]
I killed a fiendish barb in Avelorn, around the Watchtower of Aethwyn PQ and rather than unlocking Daemonvine, it unlocked Daemon Prince, and all the kills count as that

**Comment by DanaBloodkiss** [comment]
Note to myself: The SubyType and Type are correct.

**Comment by DanaBloodkiss** [comment]
Note: Found the bug. Fixed in next.
