### ISSUE TITLE
[TOK] VERMINKIN BANNER

### ISSUE THREAD

**Issue by Olszewski-Slayer** [WarEmu/WarBugs#3866]
Verminkin Banner does not give Skaven: What a Rat's Nest T3: Talabecland Tome Unlock

![olszewski_004](https://cloud.githubusercontent.com/assets/16567054/12464477/26292548-bf97-11e5-9390-d5794dd8d87a.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
