### ISSUE TITLE
Tactic slots

### ISSUE THREAD

**Issue by duskiy5** [WarEmu/WarBugs#3867]
I logged in into altdorf 2 times today and this happened , keep in mind this stayed untill going into another zone first time i got it was in High pass , 2nd time in Altdorf.

The stats were visual but the actual Tactics all functioned.

the 1st time in highpassi could literally use all the tactic slots except the last one and it would not remove itself unless logged out or when swapping zones

![duskiy_002](https://cloud.githubusercontent.com/assets/16807549/12465148/ee9b334c-bfcc-11e5-82ee-b4e0246f9378.jpg)
![duskiy_003](https://cloud.githubusercontent.com/assets/16807549/12465149/eecae97a-bfcc-11e5-98d2-c7811cbcd84d.jpg)
![duskiy_004](https://cloud.githubusercontent.com/assets/16807549/12465150/eeeb34be-bfcc-11e5-938e-3ca1aed783c5.jpg)
![duskiy_005](https://cloud.githubusercontent.com/assets/16807549/12465159/f37c3dd4-bfcc-11e5-967f-67d8f487adc8.jpg)
![duskiy_006](https://cloud.githubusercontent.com/assets/16807549/12465158/f319e1d4-bfcc-11e5-9e29-4c385e012a93.jpg)

**Comment by ozarmidrashim** [comment]
Packet corruption again.
