### ISSUE TITLE
[Quest] Celestial Defender - Incorrect mob level

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#3868]
At the part where you need to kill the Chaos Spawn Fiend which is a level 23-24 quest the mob in question spawns as a level 30. Upon killing another lvl 30 one respawns.

There are some other issues regarding this line in the tracker but are not applicable.

![torquemadra_005](https://cloud.githubusercontent.com/assets/16200780/12466012/49d77348-bf9f-11e5-9b8b-b3e5dde8feb5.jpg)

**Comment by DanaBloodkiss** [comment]
Thank you for the report!Level corrected.

**Comment by Ryanfawkez** [comment]
I fixed the Saphery Maelstrom stones, they can be interacted with as well. Quest line should be fully fixed.

**Comment by Evildoor** [comment]
Then i'm closing #2356.
