### ISSUE TITLE
[Quest] Orders from Karl Franz

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#3870]
First part, courier is broken again.

**Comment by DanaBloodkiss** [comment]
What means broken?

**Comment by vove-RoR** [comment]
I did entire chain recently and had no problems at all with it.

**Comment by Torquemadra** [comment]
Broken as in the courier is not interactable and doesnt complete the mission. Tried before and after attaining 25 kills

Gather information from a chaos courier - 0/1

Have done this many times prior.

**Comment by DanaBloodkiss** [comment]
Note to Devs: I checked everything. No bugs.

**Comment by Torquemadra** [comment]
Worked after server reset
