### ISSUE TITLE
[Quest] The Threat Revealed

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#3871]
https://github.com/WarEmu/WarBugs/issues/2630

I got asked about this quest today for where I handed it in, after checking it seems that though I had completed it I have been unable to locate a drop off npc to actually finish it.....

**Comment by Evildoor** [comment]
1) Use existing ticket.
2) Given the situation in existing ticket, i'm going to require a damn good evidience that anything is wrong here.
