### ISSUE TITLE
Initiative debuffs are not working as intended

### ISSUE THREAD

**Issue by provorot** [WarEmu/WarBugs#3872]
Char under devastator ini debuff and 34% chance to be crited suffers only from 32% crit attacks, assuming attacker has 14% crit.

**Comment by Evildoor** [comment]
What lead you to such conclusion?

**Comment by provorot** [comment]
1 SW, 1 DoK, enemy combat log parser and 200 rapid fire shots.

**Comment by ozarmidrashim** [comment]
[Emulator]

            // Basic
            int chanceToBeCrit = (int)((caster.EffectiveLevel * 7.5f + 50f) / 10f / target.StsInterface.GetTotalStat((byte)Stats.STATS_INITIATIVE) * 100f);

            // Add from stats
            chanceToBeCrit += damageInfo.CriticalHitRate + caster.StsInterface.GetTotalStat((ushort)BonusTypes.BONUSTYPES_EBONUS_CRITICAL_HIT_RATE) - target.StsInterface.GetTotalStat((ushort)BonusTypes.BONUSTYPES_EBONUS_CRITICAL_HIT_RATE_REDUCTION);

[HammerWiki]

[(Level * 7.5 + 50) / 10] / Initiative = base % to be critically hit.

**Comment by provorot** [comment]
So, can you please explain it to me? If enemy player has 30 ini and it shows 100% to be crited, but still he receiving 40% crits it is normal?

**Comment by genisaurus** [comment]
That would not be normal, but that is also not what is happening. It is very likely that the client is displaying that some initiative debuffs are stacking, when they actually do not.

1. Do .getstats with no debuffs on target. Compare to client.
2. Apply all debuffs
3. Do .getstats with all debuffs on target. Compare to client.

Is there a discrepancy? Regardless, plug the initiative value reported by .getstats into the provided equation, and see what the actual chance to be crit is. At level 32, you need about 86 Initiative to have a 34% chance to be crit. 

Additionally, you need to clarify: 
Did the target have a 34% chance to be crit *in addition to* your 14% chance to crit (total chance: 48%)? 
Or did the target have a 20% chance to be crit, + your 14% chance to crit = 34%?

If it's the latter, and you're complaining about a 2% discrepancy in only 200 trials, then you just got unlucky.

**Comment by provorot** [comment]
Just checked, it really just ui mistake, .getstats shows 90 ini while in char screen it shows 26 ini with 111%.
