### ISSUE TITLE
Appearance error - knifegun!!

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#3873]
Dwarf influence item C10 Special of the Gruff is a pistol with the appearance of a sword. While the dual wield melee animations work fine and are quite sexy and even the ranged attack animations are kind of cool the bullet noises while performing ranged attacks lets the ensemble down :(

Any chance of something sexy and unique when you fix it ;)

![pist](https://cloud.githubusercontent.com/assets/16200780/12474617/7c0038fa-bfea-11e5-8058-da0d39b16e10.png)

![knifrgun](https://cloud.githubusercontent.com/assets/16200780/12470937/cb379d9c-bfc6-11e5-8756-ef05a2f5816f.png)

**Comment by DanaBloodkiss** [comment]
Thank you for the report!Fixed in next patch.
