### ISSUE TITLE
[ToK] Bestiary Unlock

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#3874]
Related to #3852

Killing the dragon did indeed get me an unlock this time, sadly it was an unlock for a Great Eagle.....

Unusual Sun Dragon no longer adds to tally of Dragon kills, just eagles.

Dragon location 18500, 55000 Saphery

**Comment by Torquemadra** [comment]
Just noticed the patch notes say

- The "Unusual Sun Dragons" in Saphery are unusual for a reason. Their creature sub-type has been fixed.

This would certainly we unusual.....

**Comment by DanaBloodkiss** [comment]
I would quote the comment of Torquemadra. 

This is upposed to be liek this.

Closed.
