### ISSUE TITLE
Trophy Vendor

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#3879]
the trophy vendor in the library will allow you to buy all the trophies you can get without you having a bestial token to trade for them. I was able to get all the dwarf trophies with no bestial tokens on my player and only one in my vault, that was still there after I purchased the trophies.

**Comment by Torquemadra** [comment]
Confirmed. Solution will be to prevent moving of token from backpack to vault.

**Comment by DanaBloodkiss** [comment]
Please repot things like this with a PM to a GM / Database Developer.

**Comment by Evildoor** [comment]
Oh. It was reported to me, but i've not thought that this can be abused and told Shadowsmove to post it here. My apologies.

**Comment by Shadowsmove** [comment]
follow up for your information, I tried to buy the trophies on a character that had no bestial tokens or bestial unlocks and could not get any of them. Torque may be right, it might be having the token in my vault that allowed it.
