### ISSUE TITLE
Scenario bug

### ISSUE THREAD

**Issue by phsampaio** [WarEmu/WarBugs#3882]
Encountered a bug a couple of times. Apparently the game disconnects you if you try to enter scenarios that you queued solo before joining a party of higher Tier players.

Was with my RP at level 10 or so, Tier 1, when I got invited to a party of higher leveled guild mates, all in T2 (first time I encountered the bug) or T3 (the second time). Before I was invited, I was already solo-queued for SCs, and that status didn't change after I joined the party (the SC button on the top left was "on fire" as usual). As expected, the SCs popped up just for me and I entered the SC, just to be disconnected soon after. Also, the other party members were queued for SC, but it didn't pop up for them.

Hope this helps!

**Comment by RevMalthus** [comment]
this consistently happens with me as well

more troubling, everytime i try to /reload in order to fix the issue I automatically crash the game

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
