### ISSUE TITLE
not a bugg, juat a note on dragon kills.

### ISSUE THREAD

**Issue by Averatos** [WarEmu/WarBugs#3883]
This might just be me mistaking. But I se some people reporting not getting dragon kills in the ToK. 
For what I remember ther wer only 2 dragons in the game that counted for dragon kills. And they are in Cinderfall, T4. So anny dragons exept them giving a dragon kill would I say is bugged.

**Comment by Torquemadra** [comment]
This Saphery dragons were altered accordingly as per patch notes http://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=10941

**Comment by Averatos** [comment]
But in the report 3874 the response is that it is unusual and shold not give dragon kills.
