### ISSUE TITLE
Crag Great Wing

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#3885]
Killing the Crag Great Wing at approx 7762 by 41161 in the Blighted Isle shows a corpse that "glows" as if to be looted but every time I killed this mob I could not loot the corpse. This mob also is Red but acts pink/orange, completely passive unless attacked, not aggressive at all.
![skafgrim_083](https://cloud.githubusercontent.com/assets/13737673/12480348/c9bb7fb2-c00f-11e5-9faa-d63c8c722aa8.jpg)

**Comment by DanaBloodkiss** [comment]
Faction changed and respawned. Fixed in next Hotfix.
