### ISSUE TITLE
an old flame

### ISSUE THREAD

**Issue by emandil** [WarEmu/WarBugs#3887]
the queas call "an old flame" in High pass- Talabecland is bugged
the bug is: invalid creature pls report to GM, quest ID: 30301,objld=35642
is bug is reported to player called Emmerick thk

**Comment by Ryanfawkez** [comment]
Care to provide the quest giver? Makes it easier to find the right quest; there's 5 different entries.

**Comment by DanaBloodkiss** [comment]
Ryan :D look in his report :P pfffff "quest ID: 30301,objld=35642"

Fixed in next patch.
