### ISSUE TITLE
eject the Guild has each restart server

### ISSUE THREAD

**Issue by alariouch** [WarEmu/WarBugs#3888]
Hello, has whenever there is a restart of the server I eject my Guild... it lasts from the month of June and this is not normal! I turn therefore to you for maider a solve this problem... thank you ALARIEL

**Comment by Evildoor** [comment]
#948, if i understood this report correctly. No solution so far.

**Comment by kossso** [comment]
hello I too have exactly the same bug I'll be happy about my oda characters malyaa good day and thank you

**Comment by alariouch** [comment]
Yes you understand the problem... numbre there is the person who bears the name RAMPAGE which on this problem... What is the solution? delete my character and any recomencer?

**Comment by Evildoor** [comment]
Like i said above - problem is known, but we don't know what causes it and what can be done to avoid it.
