### ISSUE TITLE
Loot rolls when dead

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#3889]
I tried to find another topic about this issue but I could not find any and I don't know if it is a bug or if it is intentional (I would guess it is a bug since it is a problem in my opinion).
If you are dead and select need or greed on a loot roll that pops up you don't get to roll on the items at all.
In the chat window, where all party members' choices are shown, your need/greed/pass does not appear (while the loot window disappears) and you don't get a chance to roll on the items that dropped.
This is quite annoying because during fights I want the loot window off the screen quickly and select need on everything that drops automatically. If I died just before or after the loot window appeared and happened to select an option before I could react that I died (I also forget about this issue all too often while waiting for respawn or res) I don't even get to roll on the loot.

**Comment by imneo58** [comment]
I enable autoroll I want and set the autoroll settings. I am not sure if that includes me in the roll so will need to test for verification.

**Comment by Luth-RoR** [comment]
I guess this is solved/not a fixable (clientside) problem.
