### ISSUE TITLE
Ironclaw Camp in Mount Bloodhorn has a few bugs.

### ISSUE THREAD

**Issue by Ryanfawkez** [WarEmu/WarBugs#389]
There's a rock lobber with moving NPC properies. There's also a few level 1-3 mobs, which should be around level 4-6, I believe. Also, there's a few neutral mobs, while they should be hostile.

**Comment by Reggaewaldo** [comment]
Rock lobber is now fixed. Will check the others when i have access to the game.

**Comment by Meralors** [comment]
All npc in camp are destruction sided and the correct level
