### ISSUE TITLE
Engi :Buff elem resist staking whit other elem resist from other Engi

### ISSUE THREAD

**Issue by Tyrean** [WarEmu/WarBugs#3890]
Hi all i have found this issue 

I was on scen whit 3 engi and i have 3 same elem buff from all engi and those buff are stacking you can see it on my screens :

First one 3 elem buff for 681 elem resist 
http://www.heberger-image.fr/images/75624_Macintosh_000.jpg.html

Second 2 elem buff and just 615 elem resist 
http://www.heberger-image.fr/images/18954_Macintosh_001.jpg.html

**Comment by ozarmidrashim** [comment]
.getstats output needed.

**Comment by Tyrean** [comment]
i have out of buff 385 resist elem so there is a huge issue ...

**Comment by ozarmidrashim** [comment]
False report.
