### ISSUE TITLE
Ninja loot /destroying game

### ISSUE THREAD

**Issue by KOTBS** [WarEmu/WarBugs#3891]
If you need money/ninjaloot just join any warband and wait, where every you are you get loot.

Possible fix is no crossjoining tiers and kick after 1 minute if in wrong tier/zone/Altdorf.
![trevlig_022](https://cloud.githubusercontent.com/assets/16400629/12486548/7d052066-c063-11e5-8936-b659c8db63c5.jpg)

**Comment by noisestorm** [comment]
Zonerestriction for loot generally would be needed i'd say.

**Comment by genisaurus** [comment]
You're not wrong that this is unfair and a problem, but it's also not a bug.
