### ISSUE TITLE
Appearance of Experience or Renown gain

### ISSUE THREAD

**Issue by imneo58** [WarEmu/WarBugs#3893]
I have had this happen before but didn't get a SS of it at the time to present as evidence. I was crafting trying to raise cultivation when I experienced lag after which I got a message stating I had received X amount of renown and was now RR 151. It seems to be appearance only as I can log out and back in and everything will be back to normal. I will update this thread, if needed, with any future recurrences. 

![molonlabe_052](https://cloud.githubusercontent.com/assets/14805388/12487727/0e321142-c02e-11e5-8618-5aba041f515d.jpg)
![molonlabe_053](https://cloud.githubusercontent.com/assets/14805388/12487726/0e2b1c3e-c02e-11e5-86c5-c136ee1f8ef0.jpg)

**Comment by Evildoor** [comment]
#1810
