### ISSUE TITLE
Hit points per second not working

### ISSUE THREAD

**Issue by mammoths87** [WarEmu/WarBugs#3896]
Left a comment about this issue in #1538

Please correct me if im wrong but hp regen on items did work while in combat on live? I might be wrong

Was supposed to be fixed with recent patch but ive been trying it out and im not regenrating any hp with neither devastator chest nor shield: Sentry's herald of ferocity

**Comment by Torquemadra** [comment]
HP regen did indeed work during combat, if it does not its a useless stat.
