### ISSUE TITLE
[History & Lore] Bloody Sun Boyz

### ISSUE THREAD

**Issue by Laurell-Silentshade** [WarEmu/WarBugs#3899]
According to the Wikia the object (banner) is only active on a certain PVE quest. I've done this quest prior to the ToK being reimplemented into the game and can't check if it even works. Is it possible to make unlocks like this retroactively available? It seems silly not to make this lore independent of the quest.

**Comment by Ryanfawkez** [comment]
Did you check if flag interaction works without the quest? We probably will not reset them, and the flag should be usable despite not having the quest.

**Comment by Laurell-Silentshade** [comment]
I took a lowbie toon to test it and yes it works if I have the quest. Not usable if he doesn't.

**Comment by Ryanfawkez** [comment]
Then it is working as intended, I'm sorry you cannot get the unlock since you already did the quest on one of your mains. Perhaps we will reset some quests for unlocks like this, but we're not sure yet.

**Comment by Laurell-Silentshade** [comment]
Okay, thank you. I really appreciate the work you guys are doing and you'll at least consider it. ^_^
