### ISSUE TITLE
[Item] Silverglass Casque has model in wrong place.

### ISSUE THREAD

**Issue by Cr3nshaw** [WarEmu/WarBugs#3900]
As above, ch14 elf influence reward for KotBS - Silverglass Casque has model in wrong place.

![hurgon_163](https://cloud.githubusercontent.com/assets/10353875/12499553/cd902d62-c0ab-11e5-8601-ece06a7c9af3.jpg)

**Comment by Cr3nshaw** [comment]
EDIT: Didnt notice, it actually has model but in wrong place. 
![hurgon_162](https://cloud.githubusercontent.com/assets/10353875/12499417/ba546e44-c0aa-11e5-8b9d-152f39e2bbb9.jpg)

**Comment by genisaurus** [comment]
Should be fixed in next patch.
