### ISSUE TITLE
Auction mail

### ISSUE THREAD

**Issue by Olszewski-Slayer** [WarEmu/WarBugs#3901]
After you receive auction mail the mail notification does not go away even after zoning to diff location and re-logging. Even when it has been deleted and u re-log and rezone mail notification does not go away. The pics below will show you.

![olszewski_006](https://cloud.githubusercontent.com/assets/16567054/12499434/8cbd5b9e-c078-11e5-8c7f-1d8e28d384c1.jpg)
![olszewski_007](https://cloud.githubusercontent.com/assets/16567054/12499438/8f4f23d8-c078-11e5-809e-169f337ac24f.jpg)

**Comment by Evildoor** [comment]
#1109
