### ISSUE TITLE
Issue with renown points gained.

### ISSUE THREAD

**Issue by Nycta** [WarEmu/WarBugs#3903]
Earlier this evening I was stuck at renown rank 39. I had 49080 renown points out of 49140 for a few scenarios. Now I got to renown rank 40 but I am stuck at 0% for a while now and even after scenarios.

p.s: No hurries, I don't need you to fix it, just reporting it for any use it might have to you guys. Character name is "Play" a zealot.

**Comment by genisaurus** [comment]
Not a bug, renown gain is disabled once you hit the cap, which is currently rr40.
