### ISSUE TITLE
Auction issue: some items not mine

### ISSUE THREAD

**Issue by dcephas** [WarEmu/WarBugs#3904]
can't cancel, some items not mine, now saying limit of 50 reached

**Comment by Evildoor** [comment]
Limit of 50 is intentional, can't cancel was reported elsewhere.

**Comment by Tiggonos** [comment]
https://github.com/WarEmu/WarBugs/issues/1103

:)

**Comment by dcephas** [comment]
I understand the 50 limit but there are items in that 50 limit that are not my items.  And I cant remove them.

**Comment by ClintEastwod** [comment]
Got the same problem.
![image](https://cloud.githubusercontent.com/assets/18602535/15441848/ee7a99ca-1ee5-11e6-8e0b-4f3db2491195.png)

**Comment by Sayce78** [comment]
Also having this issue, only on my new little zealot. 12 items that are not mine appear on the Sell tab.

**Comment by JackHollowPoint** [comment]
Same problem. Haven't played that cahr couple of month.  
![kimba_006](https://cloud.githubusercontent.com/assets/25168701/22010535/e12a19e4-dc9a-11e6-831e-309a071ee24c.jpg)

**Comment by sioding** [comment]
**Thanks for the report.** Since there is no confirmation, i will close this issue now. Please make sure to follow the bugtracker rules which you can find here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)
