### ISSUE TITLE
[Quest] Lob it Good

### ISSUE THREAD

**Issue by Laurell-Silentshade** [WarEmu/WarBugs#3905]
Speaking to the Bloody Sun Lobber doesn't actually catapult you to the location, it just completes the quest.. This is a problem because two Mount Bloodhorn lore can only be obtained this way making it impossible to get them. These lobbers won't launch independent of having the quest, which is doubly frustrating for OCD completionists, i.e. me on my main.

**Comment by Evildoor** [comment]
#390
