### ISSUE TITLE
Fake dead dark elves

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#3907]
2x darkwing skylords are fake dead on the ground in front of a tower at 40800 25000 in Saphery

**Comment by DanaBloodkiss** [comment]
I will do this.

**Comment by DanaBloodkiss** [comment]
Fixed in next.

**Comment by Torquemadra** [comment]
Post patch, there is still one fake dead elf at this location 

![447](https://cloud.githubusercontent.com/assets/16200780/12633844/ccad839a-c542-11e5-85a8-ba736f4493b5.png)

**Comment by DanaBloodkiss** [comment]
Fixed in next.
