### ISSUE TITLE
[Engi & Magus]Flak Jacket & Daemonic Armor

### ISSUE THREAD

**Issue by Chummi** [WarEmu/WarBugs#3909]
regarding to original notes:

Flak Jacket: The cast time has been removed from this ability and a cooldown has been added. The value of the armor buff has been lowered and will now stack with other armor buffs. The duration of the ability remains the same, but no longer is removed after twenty hits.

Daemonic Armor: The cast time has been removed from this ability and a cooldown has been added. The value of the armor buff has been lowered and will now stack with other armor buffs. The duration of the ability remains the same, but no longer is removed after twenty hits.

correct me if i'm wrong but afaik none of them don't stack atm.
http://warhammeronline.wikia.com/wiki/Game_Update_1.4.4

**Comment by genisaurus** [comment]
I am confirming that they do stack.

Base:
![base](https://cloud.githubusercontent.com/assets/13349928/12514347/f685e0c8-c0f0-11e5-888c-de67cf52c262.PNG)

With Flack Jacket:
![base fj](https://cloud.githubusercontent.com/assets/13349928/12514356/001a4818-c0f1-11e5-8bd5-21d6acbd28a2.PNG)

With Flack Jacket and Fleeting Girding Unguent:
![base fj fgu](https://cloud.githubusercontent.com/assets/13349928/12514368/0bac96e0-c0f1-11e5-8867-4fa55012584e.PNG)
