### ISSUE TITLE
Shadows on Graphics options

### ISSUE THREAD

**Issue by Vohnnyan** [WarEmu/WarBugs#3910]
At least in my case it doesnt seem to be possible to turn shadows off, when selecting "none" on shadows.

**Comment by Evildoor** [comment]
Client issue - so i doubt that we can do anything here.

**Comment by genisaurus** [comment]
Client issues are not something we can address at this time, if ever. Your shadows are a problem between the client and your video card, not the server.

**Comment by Vohnnyan** [comment]
Thank you for the replies, I had no idea this was something you couldn't work on,
Previously I could turn shadows off, but not anymore.
Tx anyway :)
