### ISSUE TITLE
[Knight] Preseverance ability not stacking with armor pot

### ISSUE THREAD

**Issue by Antismar** [WarEmu/WarBugs#3911]
On live it was stacking.

**Comment by Evildoor** [comment]
Proof?

**Comment by Antismar** [comment]
played knight 4 years, any knight can confirm it was stacking
it was only self armor buff ability in game afaik stacking with pot

**Comment by Evildoor** [comment]
"Played knight 4 years" - not a proof. "Any knight can confirm" - not a proof either. Get a screen/video from original game which shows that they stacked, that would be a proof.
Tested in game - client charsheet shows no stacking, which means there was no stacking on live. Closing.
Only buff? What about Engi/Magus armor buffs?

**Comment by Antismar** [comment]
it was stacking with every other armor buff in game pot, lotd ones, all of them
screen attached
![knight stack](https://cloud.githubusercontent.com/assets/14290471/12516641/c3fd9536-c12e-11e5-87da-841ebf5b9a7f.jpg)

**Comment by Antismar** [comment]
engie magus armor buffs started to stack in one of last patches, knight one was stacking always

**Comment by Evildoor** [comment]
This screen does not shows armor with both buff and potion, and with them separately, so i can't draw conclusions from it.

**Comment by Antismar** [comment]
it was stacking, but since you moved it to closed i guess noone will see it and noone else will confirm. And any knight playing for few weeks even knew it was stacking.
on screen you see sov + pot + lotdx2 + ability
do the math, sov was how much armor ? ~5k ? pot for mobs i guess 660 + lotd ~800 + ~960 = 7500
1400 left = talis in gear + ability

**Comment by ozarmidrashim** [comment]
http://idrinth.de/en/stacking-buffs/

The "old" column for KotBS shows that they do not stack, which is consistent with the emulator's own stacking rules. Buff potions and ALL standard abilities except for engineer / magus armor buffs, which were changelogged are in the same stack group.

We will not change this... and I'd like to note that on a personal level I'm offended that this topic has been posted. Isn't KotBS OP enough?

**Comment by Antismar** [comment]
your decision to not make it work how it was working on live, just thought that was the idea to make it as close to live as possible + later balance things when t4

**Comment by taccr** [comment]
My information was that the client is not authoritative over the armor stat which makes in-game testing obsolete.

On topic: I'm also sure that it was stacking but I can't provide you proof aswell.

However the ability remains strong and useful even in the current state. I achieve currently achieve 4k armor with it while regenerating ap.
