### ISSUE TITLE
More Filth for Me! ToK unlock

### ISSUE THREAD

**Issue by Hoffwin** [WarEmu/WarBugs#3912]
The champ Filthmiser in Avelorn dose not unlock the ToK thing for More Filth for Me!

**Comment by DanaBloodkiss** [comment]
Working for me.

**Comment by Hoffwin** [comment]
Okay... the two champs on the hill? are you Order or Destro? im a Destro char

**Comment by DanaBloodkiss** [comment]
Only works for order.

**Comment by Hoffwin** [comment]
Roger... dont know where to get it for Destro then. but thanks.

**Comment by DanaBloodkiss** [comment]
I'm sorry this one is for both fractions. Proof: http://warhammeronline.wikia.com/wiki/More_Filth_for_Me! and fixed in next patch.
