### ISSUE TITLE
[Tome of Knowledge] Easy unlocks by suiciding yourself

### ISSUE THREAD

**Issue by vove-RoR** [WarEmu/WarBugs#3913]
When you die in Tor Anroc as a result of being thrown to lava it counts your death as a kill made by yourself and unlocks corresponding content in the ToK.

This can lead to easy unlocks by intentionally committing suicide many times in a row.

![untitled2](https://cloud.githubusercontent.com/assets/16596013/12517131/2c1f3d28-c129-11e5-8f78-697be2cc8030.jpg)

**Comment by Evildoor** [comment]
Are there any unlocks for killing players of your own faction?

**Comment by vove-RoR** [comment]
To check it I would have to kill myself 200 times to get the trophy for killing 200 dwarfs.

**Comment by Ryanfawkez** [comment]
200 Dwarves? Those trophies used to be unlocked by killing 1,000 enemy race NPCs only; did not count for class kills of the enemy faction. Also you shouldn't be able to collect them since those trophies are not available on your own Faction; what Dwarf would run around with a Dwarf Destroyer medal? Seems like absolute lore treason to me, thus isn't possible.

**Comment by vove-RoR** [comment]
I was checking that on [wiki](http://warhammeronline.wikia.com/wiki/Tome_of_Knowledge) and it says:
> The Tome of Knowledge will grant multiple types of rewards, including:
> ...
> The Tome of Knowledge will grant multiple types of rewards, including: Trophies, which you may then place on your armour to show off your achievement (such as an Ironbreaker skull for killing 200 Dwarfs).

So, killing 200 dwarf (in this case more appropriate: committing suicide 200 times) gives you nothing when you are order? I imagine for the trophy to be not obtainable as even when granted the possibility to collect it there would be no npc on the order side that gives said trophy. What with other rewards?

Even if at the moment it doesn't affect the game in any way I think it's still a good thing to keep in mind, if titles would eventually get implemented this might allow certain titles to be obtainable by a side that normally could not access it, e.g. a dwarf with title Dwarf Slayer :)

Cheers!

**Comment by bloodi** [comment]
Just adding that it seems that all group gets credit when one of your groupmates suicides, also seems to happen when a Slayer or Bw kills himself via their mechanic.

**Comment by Ryanfawkez** [comment]
Had it happen on my IB due to guard damage.

**Comment by DanaBloodkiss** [comment]
Fixed in next patch.
