### ISSUE TITLE
Renown Reset

### ISSUE THREAD

**Issue by Walmsley09** [WarEmu/WarBugs#3916]
Hello,
I just arrived in the inevitable city and it force-logged out my character, when I returned I went to the renown vendors to buy the items I intended to buy however it would not allow me stating I did not have enough renown. 
![rhad_000](https://cloud.githubusercontent.com/assets/16541810/12518780/7d628100-c132-11e5-86c0-a4c4cd067e9c.jpg)
![rhad_001](https://cloud.githubusercontent.com/assets/16541810/12518781/7d68206a-c132-11e5-9640-f1d5be700fc9.jpg)
![rhad_002](https://cloud.githubusercontent.com/assets/16541810/12518782/7d6872a4-c132-11e5-9bdd-132ebb25e304.jpg)
As you can see by these pictures I have enough medallions to prove I have fought a lot in SCs and RVR, and also one item I am wearing requires renown to wear, and yet i managed to wear it in the first place.

This seems similar to #1791 however in that he had lost his XP, where as you can see by hovering over the item in my character sheet, it still registers me as being high enough level. Also killing an enemy does not result in a massive xp hit.

It took a few full game restarts in order for it to return, so I see it having the potential to glitch and become possibly permanent in some instances.

Thank you

**Comment by DanaBloodkiss** [comment]
Hello,
wait till next server restart please.
Greetings.

**Comment by Evildoor** [comment]
I suppose this was resolved.
