### ISSUE TITLE
Cannot get my Influence Reward in T2 Dwarf (Rally Master in Barak Varr)

### ISSUE THREAD

**Issue by phsampaio** [WarEmu/WarBugs#3918]
Although I completed my basic influence reward in Dwarf T2, I cannot get it through the Rally Master in Barak Varr, as shown in the picture atached.

IGN: Sacerdote
Carrer: Runepriest
![sacerdote_003](https://cloud.githubusercontent.com/assets/16727921/12520790/afc1b3be-c12d-11e5-9eaa-bc4af060c8fe.jpg)

**Comment by noisestorm** [comment]
Go to the Rally Master in the other pairing. Inf rewards cannot (for now) be linked to 2 seperate NPCs.
