### ISSUE TITLE
Rune of Binding  (stagger-break)

### ISSUE THREAD

**Issue by Flonus** [WarEmu/WarBugs#3920]
If you use "Rune of Binding" dmg procs like "Flames of Rhuin", "Shining Blade" etc. break the stagger instantly.

**Comment by noisestorm** [comment]
I hope you did test that in a Duel or another safe enviroment without having someone else breaking it by chance?

**Comment by ozarmidrashim** [comment]
While a Rune of Binding can proc procs, and procs will break staggers, any proc from Rune of Binding itself will be processed before the stagger buff is actually applied. This is guaranteed. As such, this isn't an issue because damage procs require an attack to be issued in order to proc them.
