### ISSUE TITLE
[Quest] Chasing Shadows

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#3922]
After attaining the map I dont seem to have anywhere to progress to. Tried clicking NPCs in Chapters 13 and 14 camps.

![778](https://cloud.githubusercontent.com/assets/16200780/12523488/3b2a4172-c125-11e5-8d70-49c8d048c5b1.png)

**Comment by noisestorm** [comment]
Did you try to talk to the one that you actually got the quest from?

**Comment by Torquemadra** [comment]
Fillion Skyspear 63k 30k, located the quest giving npc and handed in and progressed. Perhaps a small tooltip rewrite, hard to memorise all ;)
