### ISSUE TITLE
Campfire outside of Order spawn in Gates of Ekrund gets players "stuck"

### ISSUE THREAD

**Issue by Talsorc** [WarEmu/WarBugs#3925]
![talsorc_007](https://cloud.githubusercontent.com/assets/16845523/12526234/513fe764-c139-11e5-869e-56bdc816a311.jpg)

**Comment by Evildoor** [comment]
I doubt that we can do anything here.

**Comment by Antismar** [comment]
Its a 'feature' from live :)

just watch when you jumping off spawn

On live while in sc typing /stuck out of combat was porting you to sc spawn, maybe this can be implemented ?
