### ISSUE TITLE
Loot roll bug when having 2x the same number

### ISSUE THREAD

**Issue by Pumatouch** [WarEmu/WarBugs#3929]
When an even roll occurs, I suspect the player named with the first letter in the alphabet gets it. Seen it happen a few times, today I took a screenshot. Doesn't prove anything on its own of course, but the second "roll" is non-existant, and Arthur gets alot of loots.

![](http://oi63.tinypic.com/24x3y2f.jpg)

**Comment by noisestorm** [comment]
Are you sure it was depending on the name? It could also depend on the slot in your group (like if you were invited before the other one for example?). Nonetheless there should be a second loot roll for draws right?

**Comment by Pumatouch** [comment]
Talsorc, who was the other one to roll 84 here, was in the group before I joined.

**Comment by Pumatouch** [comment]
Went and done proven myself wrong.

![](http://oi66.tinypic.com/erbst5.jpg)

![](http://oi68.tinypic.com/23wa7h1.jpg)

So it's not alphabet dependant after all. Still a second roll is not shown to players.

**Comment by Luth-RoR** [comment]
There is likely a second, third, etc. roll if the outcome is even. In most cases there will be only 2 players get a second roll, so the 50% chance on the second roll is pretty high and it could **seem** that one player has an advantage.
That further rolls are not shown is unfortunate, but probably a client restriction.
