### ISSUE TITLE
Shadow Warrior Helms - Stats need to be reviewed.

### ISSUE THREAD

**Issue by SATANICOMODERNO** [WarEmu/WarBugs#3930]
Item: Underwork Maskhelm - lv 23 - Shadow Warrior
Stats: 113 armor, 15 willpower, 15 wounds, 49 spiritual resist.

As you guys can see, the item comes with +15 WIllpower instead +15 ballistic skill. 

Item: Doom-Caller Maskhelm - lv 25 - Shadow Warrior
Stats: 122 armor, 9 willpower, 16 wounds, 9 iniciative, 35 spiritual resist.

Idem above. Item comes with willpower instead ballistic skill.

It's not wrong by the way. But willpower is not something useful for Shadow Warriors. I don't know if this change could be done, but it would help a lot. 

Thanks!

**Comment by Evildoor** [comment]
Problems like this are known, will be handled later and for all classes at once.

**Comment by vove-RoR** [comment]
To be honest I wouldn't bother with reworking green items. I only wonder why originally there's willpower on them, aren't they for tanky melee build or something? Although resistance gained from 15 willpower is amusing indeed.

Maybe there were some changes considered in sw mechanics that never got implemented?

**Comment by gittoaster** [comment]
All the stats have more than one purpose.  WIll - Disrupt Initiative  - chance to be crit etc.
So this gear is actual proper for the class.  
But there are items that aren't proper.  Eg str on Staff, Str on Engie.

**Comment by Torquemadra** [comment]
A lot of stats on items are a artifact from when other systems were in place, a SW will never gain enough willpower to make any semblance of an impact in disrupt without seriously gimping themselves. However in alpha willpower was I believe to be a resist mechanism hence its placement across the board on classes with no use for it.
