### ISSUE TITLE
Bestiary: unlock for Unicorn

### ISSUE THREAD

**Issue by ungrninja** [WarEmu/WarBugs#3936]
Unlock: A Little Off the Top
Rewards: The Hornsnapper (title)

Supposed to be a unicorn named Sylendoras @ 16k, 44k in Shadowlands or a wounded guy under a unicorn up on top of a plateu around 23k, 56k. 

Wandered around both areas and didn't see either.

**Comment by DanaBloodkiss** [comment]
Seems a little bit different 
http://warhammeronline.wikia.com/wiki/A_Little_Off_the_Top
I will spawn the unicorn but for now Unlocks related to Items which drop don't work.
