### ISSUE TITLE
Bestiary: unlock for Warhawk

### ISSUE THREAD

**Issue by ungrninja** [WarEmu/WarBugs#3937]
Unlock: I Just Washed This Cloak
Title: The Grounded 

The wiki shows 
-Skyherald Warhawk @24600,22200 in Shadowlands
-Crag Great Eagle @ 6k, 37k in Blighted Isle
-5 Warhawk Feathers from Skyhunter Maulers @ 20.4k, 27.1k in Shadowlands

I killed the Skyherald Warhawk and the Crag bird in Blighted Isle a few times with no luck. The Skyhunter Mauler in Shadowlands does drop the Warhawk Feathers (I assumed unlocks of this type might not be working yet?)

**Comment by Ryanfawkez** [comment]
Unlock by item is not yet implemented.

**Comment by Lheana** [comment]
Update this report. This Bestiary unlock for Warhawks should be triggered by:

- Killing 'Skyherald Warhawk' next to 'Elder Meresene' -> does not work
- Collecting 5 'Warhawk Feathers' from 'Skyhunter Maulers' -> they don't drop it
- Killing 'Crag Great Eagle' -> does not work

I think now it can be fixed.

Note: 'Skyherald Warhawk' and 'Skyhunter Maulers' don't count as Warhawk, but they should. And I think 'Crag Great Eagle' should count as Great Eagle, but he does not.

**Comment by Lheana** [comment]
Fixed for 'Skyherald Warhawk'.

**Comment by Lheana** [comment]
- [ ] Skyheral Warhawk
- [ ]

**Comment by Lheana** [comment]
Completely fixed
