### ISSUE TITLE
Bestiary: unlock for Imp

### ISSUE THREAD

**Issue by ungrninja** [WarEmu/WarBugs#3938]
Unlock: What Makes You Sparkle?

The unlock works but the "The Imp Squisher" title isn't granted. Just shows "???"

**Comment by Ryanfawkez** [comment]
Cannot be implemented since loot interaction for tok unlocks isn't enabled.

**Comment by ungrninja** [comment]
On Destro it only involves talking to the merchant Bradas Coldtouch. No loot interaction needed. I was able to get the unlock just fine, only the title wasn't working.

**Comment by Ryanfawkez** [comment]
Will fix that then, at least.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
