### ISSUE TITLE
Dread Sentry - Inevitable City

### ISSUE THREAD

**Issue by benitoben20** [WarEmu/WarBugs#3940]
Hello,

There's a Dread Sentry watching the abyss in The Inevitable City. I think he's not at the right spot :)
He's on the left side of the Monolith (big floating cube). It's kinda hard to see it on the picture, but he's at the bottom left, just a bit up from my 2nd spell. I've included a position of myself on the map.

Thank you,

![isas_000](https://cloud.githubusercontent.com/assets/16641170/12532745/61e06818-c1e9-11e5-9e9b-71f06fd88d20.jpg)
![isas_001](https://cloud.githubusercontent.com/assets/16641170/12532746/61eb81e4-c1e9-11e5-8138-d263d701cea6.jpg)

**Comment by DanaBloodkiss** [comment]
Thanks for the report!Removed this spawn.
