### ISSUE TITLE
ToK Bestiary- Daemonvine

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#3941]
All the mobs that I think should be classed as Daemonvine that I have killed so far in Avelorn are registering as Daemon Prince kills. Specifically the Fiendish Talons and Fiendish Barbs in and around the Corruption PQ in Avelorn. I have not tested mobs of this type in other areas yet but plan to. I do not think I will be able to kill a Daemon Prince for quite some time to see what they are registering as :), can't remember any common (non dungeon) area to find them.

**Comment by Evildoor** [comment]
#3865
