### ISSUE TITLE
ToK Bestiary unlock

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#3942]
in the picture you see a Cahmpion Yhetee named Coldsnap, he is found at approx 9 by 5 in Troll Country. The problem is, he is supposed to be (according to the wiki) a level 19 Champion Stone Troll named Coldsnap for the Unlock It's A Snap. If you kill him he counts as a Yhetee and there is no unlock..

![skafgrim_118](https://cloud.githubusercontent.com/assets/13737673/12533259/38975958-c1f8-11e5-89a5-02a74ae88cfd.jpg)

**Comment by DanaBloodkiss** [comment]
Added the correct Unlock for the next patch.

**Comment by Eusebeus82** [comment]
This is still broken as of April...

**Comment by Evildoor** [comment]
I suppose this is because of

> The currently active build contains a lot of regressions. Please do not report to the bugtracker any issue that was previously raised and fixed but has reappeared in the latest build. Thank you.
