### ISSUE TITLE
renown 89 bug

### ISSUE THREAD

**Issue by shamallow** [WarEmu/WarBugs#3943]
hi,
i got renown rank 89 with my lvl 25 marauder, in Inevitable City killing mobs.
this deserve the mount ? :)

![renown_89_bug](https://cloud.githubusercontent.com/assets/16374367/12533265/b0cbe33a-c22a-11e5-9b0c-cbbf546c8f98.jpg)

**Comment by Cr3nshaw** [comment]
Did you even relogged to confirm it isnt just visual bug...?

**Comment by taccr** [comment]
Packet corruption. Happens on all the time. Nothing new here :)

![RR75](http://img3.uploadhouse.com/fileuploads/22003/22003433504c29585852a9b959e2a27cd6fd7813.png)

**Comment by Evildoor** [comment]
taccr is correct. Closing.
