### ISSUE TITLE
ToK Bestiary- Loop Back

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#3944]
this unlock requires you to kill a zombie named Rupert, I found 3 of him in 3 close by places in Avelorn. Rupert one is approx at 43500 by 44233, he is attackable and does not give the unlock. Rupert two is approx 41969 by 41468, he is also attackable and also does not give an unlock. Rupert three is approx 40735 by 40649, he is not attackable and as far a I can tell is only there visually. 

pic of Rupert 1
![rupert 1](https://cloud.githubusercontent.com/assets/13737673/12533329/cc3cc3da-c1fa-11e5-8879-e09b1cf633b0.jpg)

Pic of Rupert 2
![rupert 2](https://cloud.githubusercontent.com/assets/13737673/12533331/d9d6204a-c1fa-11e5-8fb8-bc2fd4ce3bd0.jpg)

pic of Rupert 3
![rupert 3](https://cloud.githubusercontent.com/assets/13737673/12533335/e5eaf36a-c1fa-11e5-9a2e-cd1885791b01.jpg)

**Comment by DanaBloodkiss** [comment]
Removed the duplicated spawns and added the tome Unlock for next patch.
