### ISSUE TITLE
ToK Bestiary Ogres

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#3945]
I've killed a bunch of Ogres of different types and names in the last day and none are registering on my ToK entry for them. Can't see where they might be registering instead but the Ogre category is still at zero. gorgers and yhetees are registering fine.

**Comment by Shadowsmove** [comment]
a little while ago I ran across an ogre tyrant, after killing him that entry was unlocked in my Tok, but still no "plain" ogre

**Comment by Ryanfawkez** [comment]
There are no 'regular' Ogres. Only Bulls and Tyrants. There's also dragon Ogres that probably count amongst the Dragonoids.

**Comment by Shadowsmove** [comment]
Ok, to clarify. the Ogre Bull sub type is the one I am not able to unlock, (I should have been more specific in my first post) I was guessing that any ogre mob except the tyrant should count as bulls. Dragon Ogres count as Chaos Breeds I think.

**Comment by DanaBloodkiss** [comment]
I reworked the Ogre CreatureSubTypes , some were listed wrong. I hope the Unlocks are fine with the next patch.

**Comment by DanaBloodkiss** [comment]
The SubTypes look like this in the different categories and below you see the Dragon Ogres in another categorie too

subtyp.add("100,HUMANOIDS_OGRES_GORGER");
        subtyp.add("101,HUMANOIDS_OGRES_OGRE");
        subtyp.add("102,HUMANOIDS_OGRES_OGRE_BULL");
        subtyp.add("103,HUMANOIDS_OGRES_OGRE_TYRANT");
        subtyp.add("104,HUMANOIDS_OGRES_YHETEE");
        subtyp.add("105,HUMANOIDS_SKAVEN_RAT_OGRE");
        subtyp.add("106,HUMANOIDS_SKAVEN_SKAVEN");
        subtyp.add("107,MONSTERS_CHAOS_BREEDS_CENTIGOR");
        subtyp.add("108,MONSTERS_CHAOS_BREEDS_CHAOS_MUTANT");
        subtyp.add("109,MONSTERS_CHAOS_BREEDS_DRAGON_OGRE");

**Comment by Lheana** [comment]
Many Ogres Bull do not count in kill counts in High Pass => names :
- 'Bonestomper Bull'
- 'Bonestomper Bullrager'
- 'Bonestomper Bloodbutcher'
- 'Bonestomper Maneater'
- 'Bonestomper Butcher'
- 'Bonestomper Tainted'
- 'Bonestomper Magus'

I think these mobs are Ogres Bull too, but not sure (maybe they are Ogres Tyran):
- 'Bonestomper Irongut'
- 'Slaughtermaster Khag'
- 'Thargh the Butcher'
- 'Bonestomper Touch'
- 'Bonestomper Bruiser',

**Comment by Lheana** [comment]
In Badlands too, there are Ogres Bull that don't count : Bloodmaw Bull and Bloodmaw Irongut.

**Comment by Ryanfawkez** [comment]
After some research, I have to conclude that the Ogre Bull subtype has to be applied to all Ogres that are of superior ranking to their regular Ogre brothers. Ogre Bulls are tougher, specialised variants of Ogres, whereas the regular Ogre subtype is to be applied to weak/small versions.

**Comment by Ryanfawkez** [comment]
Bonestomper Tainted, Touched and Magus are bugged, I believe.

**Comment by Lheana** [comment]
I noticed some Ogres Bull in the chaos PQ in High Pass 'Guts Out' don't count : name = 'Icemaw Bruiser'.
