### ISSUE TITLE
[ToK] Pocket Items missing at Vendor

### ISSUE THREAD

**Issue by TaeBal** [WarEmu/WarBugs#3947]
http://warhammeronline.wikia.com/wiki/What_do_We_Have_Here%3F/Orc,_Black_Orc

http://warhammeronline.wikia.com/wiki/Lucky_Humie%27s_Hand

I got unlock "What do We Have Here?" in my ToK 

But "Lucky Humie" <-- this pocket item not in NPC's selling stuff list 

Im not sure its bug or not cuz im noob 

Thank you for read :)

**Comment by TaeBal** [comment]
<img src=http://www.pwnsan.com/wp-content/uploads/2008/11/62.jpg>
<img src=http://www.pwnsan.com/wp-content/uploads/2008/11/63.jpg>

And this Steamtrain Token Tome Unlock not work too :)

**Comment by noisestorm** [comment]
i believe pocket items - unlicke most trophies - arent implemented yet at all. And i actually cant even remember what they were doing. Werent those just fun items you could make some emotes/sounds or whatever with?

**Comment by Ryanfawkez** [comment]
1. most of them are implemented in the library vendor, although some unlocks related to them may not be working yet.
2. tehyw ere just fun items that either made a sound, a visual effect or parsed a chat command for fun.

**Comment by DanaBloodkiss** [comment]
Fixed in next Hotfix. Vendor List and both Unlocks.

**Comment by Styrkarr** [comment]
Fixed in next patch.
