### ISSUE TITLE
. commands not working in new chat channels

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#3948]
s.a.

**Comment by vove-RoR** [comment]
You are supposed to write them on /s, so for example if you are on /advice chat you write:
1. /s
2. .unlock

**Comment by Tiggonos** [comment]
no . commands worked in advice e.g.

**Comment by Ryanfawkez** [comment]
In my personal experience, using a . command in any other channel than /s would parse it to the channel instead of executing the command. It's a simple rule of thumb to use commands in /say chat, since it will ALWAYS work. Having this fixed so it works in all channels, however, would be great.
