### ISSUE TITLE
Lair of Elrin Helfried

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#3949]
Avelorn 58k,46k.It dropped Green Battlehammer.It should drop 1-3 level 36 rare shoulders with 20 melee power or magic power and a talisman slot according to this http://warhammeronline.wikia.com/wiki/Elrin_Helfried

**Comment by Torquemadra** [comment]
Drop tables are correct on this NPC in the database. May be an item clamp in place(?)

**Comment by Soulwhisper** [comment]
#4476
