### ISSUE TITLE
Lair of Lady Grimgyre

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#3955]
Killing 
![sapphery lair](https://cloud.githubusercontent.com/assets/16864486/12537594/57fbaa3c-c2cb-11e5-81c7-39ab9627e8de.jpg)
Does not drop Grimshimmer's Ley stone.(Only unlocks ToK achievement.)
So we cannot proceed the Lair. 
Source : http://warhammeronline.wikia.com/wiki/Lair_of_Lady_Grimgyre

**Comment by ishkurirriador** [comment]
There is a way to go straight to Lady Grimgir, without ley stone. and Lady Grimgir doesn't drop anything. this is real problem, i think.

**Comment by Soulwhisper** [comment]
ishkurirriador Which way?

**Comment by ishkurirriador** [comment]
@Soulwhisper https://s32.postimg.org/mu74hxu9x/21391604.jpg
legend for this map:
1) Arixxis
2) Tower of Lady Grimgyre
black line - way to go to the tower.

so you need to go east, climb up to the hills/textures, reach tower (there will be some npc greenskins), and then do some accuracy jumps (jump to the little place with grass).
 after this you can kill some lvl+ mobs and walk down to the lair of Lady Grimgyre.

**Comment by Soulwhisper** [comment]
Which little place with grass do you mean? Cant find a way to go there.If you could post Screenshoots please.

**Comment by ishkurirriador** [comment]
@Soulwhisper https://s32.postimg.org/qkh1fhvud/Ish_021.jpg https://s31.postimg.org/j3tbh4863/Ish_022.jpg

**Comment by Soulwhisper** [comment]
Oh my...yeah thats hard for me(Order) because i have to take down that Hero...thanks.
