### ISSUE TITLE
SW: Barrage + Powerfull Draw

### ISSUE THREAD

**Issue by sullemunk** [WarEmu/WarBugs#3958]
The Barrage ability does not bennefit from the Powerfull Draw tactic (+50% range on ALL Skirmisher abilitys)  despite beeing an Skirmisher Ability

**Comment by bloodi** [comment]
Isnt Barrage a cone in front of you?
If so, there is no range to increase, its just an area of effect in front of your character, the tactic increases the range, not the area of effect.

**Comment by noisestorm** [comment]
I am not sure, if range modifiers really should *only* work on spells that have an actual range in their spell info. Barrage states 40 feet in its tooltip, but no range for the info, but i feel like the 40feet should also be increased to 60 feet here.

But does that also mean that for example Glass Arrow does not reduce the range for groupheals?

**Comment by Evildoor** [comment]
My memory agrees with bloodi - range increase does not affects size of aoe effects, so it's not a bug. Balance issues and suggested changes belong to forums.
