### ISSUE TITLE
Can't make interaction with some stuff.

### ISSUE THREAD

**Issue by arbi89** [WarEmu/WarBugs#396]
I can't interactive with Secured Chest in mission Pillaging also have the same problem with Kindling in mission Destruction.

edit.
I just discovered on mailbox i cannot interactive with all stuff. Only with NPC.

edit.2
I have enough! 90% of starting quest for chaos (Chosen) dont work good. I cant earn many rewards bcs of bugs -.- Also respawn time fo NPC is way to fast. It's crazy. I kill one then i go to the next one, I kill him and I see that earlier guy who was dead is already respawned (3 second respawn?). Because of this I'm dead by all time.

edit.3
In missios with quest items is also bug. I dont recieve them and when i do, they dont work. Can't use it. Send me info if someone is working on it. My nick name on the page is arbi89 and i'm playing Chosen "Mortar".

**Comment by Evildoor** [comment]
Closing per @Elvenalthur .
