### ISSUE TITLE
Level 25 mobs dropping lvl 200 butchery materials.

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#3960]
In Avelorn the Fiendish talons, Euphoric Talons and Euphoric barbs (count as tok demon princes?) have the chance to drop lvl 200 Chaos-Imbued demon flesh. Its not 100%but fairly high rate of drop, I would say 50%.

Note - my butchery is only 181 as well

![652](https://cloud.githubusercontent.com/assets/16200780/12540400/70126fce-c2d6-11e5-9c9c-6361b39ac7d2.png)

![669](https://cloud.githubusercontent.com/assets/16200780/12540402/739fbbe2-c2d6-11e5-94a3-8381e1d8a81d.png)

**Comment by nalgol** [comment]
db error

**Comment by DanaBloodkiss** [comment]
Fixed in next patch.
