### ISSUE TITLE
Shambler hat BoP issue

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#3961]
Seems like a flag resetting for this as was unable to trade it manually or via mail.

I had a WH shambling hat in the AH from my Engi, I cancelled it to trade it to someone else. On pickup I couldnt trade it or mail it but could use the AH to play a game of chicken in case someone else nabbed it for the low issue price ;)

Could putting it up for sale and taking it off be reapplying old flags?

Edit, other people have shambler drops from the kills and cant trade manually 

![784](https://cloud.githubusercontent.com/assets/16200780/12543204/0ab6cb50-c2fb-11e5-8000-61f613bbafeb.png)

**Comment by wargrimnir** [comment]
These are BoE now, shouldn't be an issue.
