### ISSUE TITLE
Wrong Respawn Location

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#3969]
Died 3 times there trying to do Lair of Gorthlak.Instead of respawning to the nearest chapter(in this case Adunei) always respawned at Tor Aendris Camp.
![respawn location](https://cloud.githubusercontent.com/assets/16864486/12548970/a0b8de92-c362-11e5-9d3c-624af9e6441c.jpg)

**Comment by DanaBloodkiss** [comment]
Can you mark where you died and where the 2 camps are located?Just use Paint, takes 1 min :) thank you!

**Comment by Soulwhisper** [comment]
![1234](https://cloud.githubusercontent.com/assets/16864486/12562236/d87c4734-c3ac-11e5-98b2-e808c7dd8ec0.jpg)
Died in Black
Adunei in Green (Chapter 2 of the High Elf)
Tor Aendris Warcamp in Red

**Comment by Torquemadra** [comment]
Fixed next patch
