### ISSUE TITLE
Avelorn CH12 no way to get INF

### ISSUE THREAD

**Issue by Scrilian** [WarEmu/WarBugs#3972]
Tried to farm some chapter 12 influence for a 2h axe for slayer and I can't find any mob on any ch12 PQ to give any inf whatsoever.

**Comment by Scrilian** [comment]
Somehow I can't even get the CH14 Influence for the Empire now, but I have 100/20804, so I was able to get it and not I cant on the same PQ >_<

**Comment by Torquemadra** [comment]
C12 HE fixed next patch. If still have issues with C14 Emp please open a new ticket.
