### ISSUE TITLE
missing quests

### ISSUE THREAD

**Issue by oncearound** [WarEmu/WarBugs#3973]
I had the exact same issue as #2001. I commented on it after realizing it is closed already. Upon loading war today i crashed to desktop on first try. Second attempt was successful and normal. loaded up my witch elf and noticed all my quests were missing. i was able to pick them all up again no problem, including quests that i should not be able to pick up for a second attempt. time played on tome main page is showing 43301 days.

**Comment by Evildoor** [comment]
Uh, what?
1) It is not closed.
2) Closed tickets can be commented - read the rules of the bugtracker.
