### ISSUE TITLE
[BO] Da Greenest

### ISSUE THREAD

**Issue by Gobtar** [WarEmu/WarBugs#3975]
The proccable ability from the Greenest is a specific resistant type, yet it does not stack with *All* Resistant buffs (such as zealot mark or chosen aura). 

Specific resistance debuffs stack with General Resistance debuffs, the same should be true for buffs.

**Comment by ozarmidrashim** [comment]
False report. Confirmed using character stat screen, which shows original stacking rules, using Mork's Buffer + Da Greenest Spirit.

If you have a problem with the emu's stack handling, it is necessary to demonstrate a mismatch between the output of .getstats, which uses the server's rules, and the character stat screen, which uses the original game's rules.
