### ISSUE TITLE
Humans counting as high elves | TOK

### ISSUE THREAD

**Issue by JamGrif** [WarEmu/WarBugs#3976]
The low level human tower guards in chapter 1 chaos area count as high elves in the TOK even though they are obviously humans. 
![abc](https://cloud.githubusercontent.com/assets/16886300/12562836/1b626f5a-c39f-11e5-8b22-6e773a7a508f.png)

**Comment by JamGrif** [comment]
![abc](https://cloud.githubusercontent.com/assets/16886300/12562858/3c915f9c-c39f-11e5-9d8c-1a94d2cd4ff7.png)

**Comment by DanaBloodkiss** [comment]
Thanks!Fixed in next patch.
