### ISSUE TITLE
[Ability] IB: Vengeful Strike

### ISSUE THREAD

**Issue by Halhammer** [WarEmu/WarBugs#3977]
Seems like the toughness bonus doesn't proc, anyone confirm?

**Comment by Torquemadra** [comment]
I can confirm it works on my IB both on paperdoll, .getstats and through oathfriend

**Comment by Halhammer** [comment]
Weird. Guarded Attack and Inspiring Attack are workin fine tho.

**Comment by Torquemadra** [comment]
what context is the issue? my IB is only lvl 13 but seems functional from the toughness boost of vengeful strike, even the buff icon is showing

**Comment by Halhammer** [comment]
Ok, it just doesnt stack with pot. Only armour does it seems.
