### ISSUE TITLE
Hexxing Doll

### ISSUE THREAD

**Issue by Squea** [WarEmu/WarBugs#3980]
This average curious object is one of the bugged curios.  Same with Canopic Jar and myriad others I'm sure.  Every non-common curio I'm guessing is currently not usable.

**Comment by nalgol** [comment]
acording to http://warhammeronline.wikia.com/wiki/Talisman_Making
Curios
Uncommon, Rare, Very Rare, and skill 200+ no longer drop. 
so they where removed from the game
