### ISSUE TITLE
ToK unlocks - Beastmen

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#3982]
The Beastmen category seems to be a bit messed up, some crisscrossed entries I think. Ungors seem to be fine and I have not encountered a Doom Bull yet so i don't know about it, but I was killing all kinds of Beastmen yesterday and today and after killing 100 Gors, it unlocked that I had killed 100 Bestigors. I had at that point only killed maybe 30 Bestigors, also when I killed any Bray Shamans it counted as a Gor and did not unlock the Bray Shaman sub type. When I checked my ToK, my Gor kill count is over 150 but has no unlock for Encountering a Gor, killing 25, or killing 100. My Bestigor count is about 30 and as I said above it has the killed 100 unlocked.

**Comment by Torquemadra** [comment]
working on this atm

**Comment by DanaBloodkiss** [comment]
Next time please exact NPC names when you can remember them :)

**Comment by Evildoor** [comment]
![mara_002](https://cloud.githubusercontent.com/assets/11015074/13925196/7e5b0a02-ef98-11e5-8672-888b82bffcec.jpg)

Killed a Bloodpelt Gor in IC on dev.

**Comment by DanaBloodkiss** [comment]
Thanks. Fixed in next.

**Comment by poutpoutt** [comment]
The count between Gor and Bestigor is still messed up : I killed many Felhorn Gor in Norsca (arount 20k/41k) and the kill count goes up but I don't get Gor unlocks for kills.
On the contrary, the Bestigor kill count doesn't go up but I got the unlocks for 25 and 100 Bestigors killed.

So far, no problem when I kill Bestigors, Bray shamans or Ungor.

**Comment by Lheana** [comment]
Fixed.
Note: if you have already killed 1/25/100 etc Gors, it won't trigger the unlock. Will only trigger for the next kill count unlocks.
