### ISSUE TITLE
Incorrect RVR area: High Pass

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#3983]
I was running around north High Pass and got flagged for RvR as if I was entering the lakes. I was at approx 19231 by 18018 heading basically east when I was shown the countdown to being flagged, I continued into that area and was flagged. sorry I have no idea how large the area is. If I find other places around the area that flag me I will add them to this report.

**Comment by Tiggonos** [comment]
is it reddish on the map?

**Comment by Shadowsmove** [comment]
no, there is no red in the area I was in. I have circled the area I was in on the map in this picture.
![high pass rvr flagged area](https://cloud.githubusercontent.com/assets/13737673/12598838/be786972-c45a-11e5-8258-758cdfa35447.jpg)

**Comment by Kaelang** [comment]
Ran multiple circuits around this area and was not flagged. Please re-open if issue persists.
