### ISSUE TITLE
ToK  unlock - Ghoul

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#3984]
In the Badlands you need to kill a Ghoul named Rauklus around 17797 by 10850, there are actually 4 of him in that area, I killed all four and none gave the unlock for a Bestial Tactic Fragment. I am pretty sure that the tactic fragments are not implemented yet so I'm not worried about that, just reporting the 4 of the same mob.
http://warhammeronline.wikia.com/wiki/Foul_Amongst_the_Fowl

**Comment by Torquemadra** [comment]
Extra Rauklus NPCs removed next patch

**Comment by Lheana** [comment]
Rauklus seems to have only 1 spawn now, but still does not provide the unlock 'Foul Amongst the Fowl'. Maybe it is now fixable ?
