### ISSUE TITLE
ToK Bestiary - Warhawk unlock

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#3987]
In High Pass one of the Warhawk unlocks requires you to gather 5 Warhawk eggs the eggs are scattered in the mountains in western High Pass between the PQs Chaos Ruins and Cult of the Magus. I found several of the eggs in those mountains but none are able to be clicked so they cannot be gathered yet. I know item based unlocks are not working yet but in most cases you can still gather the items needed even if you can't use them to get the unlock but here you cannot do that.

http://warhammeronline.wikia.com/wiki/Poached,_Scrambled,_or_Fried

**Comment by Lheana** [comment]
It is now possible to interact with Warhawk eggs but they still do not give item.
