### ISSUE TITLE
ToK Bestiary - Yhetee unlock

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#3988]
One of the unlocks for the Yhetee is to find a drowned body, it is at approx 25950 by 27800, it is very hard to see, it's underwater in a small lake. I did find it but when clicked it does not give the unlock or title.

http://warhammeronline.wikia.com/wiki/Warrior,_Your_Life_Force_is_Running_Out

**Comment by CaptainoftheHarem** [comment]
I would like to say that today, I have been able to get the unlock but the title shows up as ??? on the mouse over (it should be "The Defrosted")

**Comment by Torquemadra** [comment]
Fixed next patch
