### ISSUE TITLE
ToK Bestairy -Chaos Spawn unlock

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#3989]
For this unlock in High Pass you need to find and click on a book called Sixth Book of Llian and click on it. I found the book at approx 28200 by 30300, but when I clicked on it I did not get the unlock or the title.

http://warhammeronline.wikia.com/wiki/Beyond_Definition

**Comment by Torquemadra** [comment]
fixed next patch

**Comment by Lheana** [comment]
Interacting with the book triggers the unlock but not the title 'The Serene'.
