### ISSUE TITLE
ToK Bestiary - Bloodthirster unlock

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#3990]
For this unlock in High Pass you need to find and click on an Empire Runners Corpse found at approx 38195 by 40653. I found and clicked on the corpse but did not get the unlock or the title.

http://warhammeronline.wikia.com/wiki/Dire_News_Indeed

**Comment by CaptainoftheHarem** [comment]
I just checked this (after the 1/31/2016 patch), I can get the unlock for this, but I am unable to get the title

**Comment by Torquemadra** [comment]
Fixed next patch
