### ISSUE TITLE
ToK Bestiary - River Troll unlock in Troll Country

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#3994]
For this unlock you need to find Troll Droppings that are found around 50000 by 50000 and 49000 by 43000 and then bring the Troll Droppings to someone in Felde Castle, Empire Chapter 6. I found and clicked on the Troll Droppings (then washed my hands) but didn't receive any in my back pack, so i could not attempt to bring the item to the required NPC. I know some other multi part unlocks allow you to collect the items but not deliver them, the Bat Wing item for instance, should go to this same NPC I got it but can't give it to the NPC, but most of the ones I know are for dropped items not found items so i have no idea if this should be working or not at this point in the ToK project.

http://warhammeronline.wikia.com/wiki/Gotta_Go

**Comment by thorbolt80** [comment]
you can click on troll dropping now but nothing happen

**Comment by Purgaru** [comment]
can't we still fix this?
