### ISSUE TITLE
ToK Bestiary - River Troll unlock

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#3995]
For this unlock in Troll Country you need to find and kill a Bridge Troll I was able to find two of them one at approx 47000 by 39000 and the other at approx 53000 by 37000. I killed both but neither gave me the unlock.

http://warhammeronline.wikia.com/wiki/Takes_its_Toll

**Comment by Torquemadra** [comment]
fixed next patch

**Comment by VMblast** [comment]
This issue havent being fixed. Ive just did this River Troll tome unlock but havent got token. Beastiary was unlocked tho, but havent got any token for it. Killed that troll at least 5x with no result.

**Comment by Soulwhisper** [comment]
@Luth-RoR @Torquemadra 
This one is still bugged guys.
A group killed him,got the unlock on ToK but didnt get the Token.

**Comment by Lheana** [comment]
The item reward for this unlock is not given automatically, it must be sold from vendors in Lyceum/Library.
