### ISSUE TITLE
ToK Bestiary - Slayer unlock

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#3997]
For this unlock in Barak Varr you need to find and talk to First Mate Kjaelsson aboard The Sea's Anvil found at approx 10000 by 45000. I found and clicked on him but did not get the unlock or the title. 

Another unlock in this location, talk to Captain Erginsson also does not unlock but is for a Man Tactic Fragment and i don't know if he should be working or not. I included this in this post instead of opening another since Tactics don't seem to be implemented yet, if you would like me to I can post it in it's own report.

http://warhammeronline.wikia.com/wiki/First_of_Many

http://warhammeronline.wikia.com/wiki/Off_With_His_...

**Comment by Torquemadra** [comment]
fixed next patch
