### ISSUE TITLE
ToK Bestiary Giant unlock

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#4001]
For this unlock in The Marshes of Madness you need to find and engage (not kill, just attack) Thrags, he is found at approx 55000 by 60000. I found and attacked him (then promptly died) but did not get the unlock or the title. I have no idea if killing him will give the unlock but I know in Live all you needed was to attack, didn't matter if you died, ran away or even killed him.

http://warhammeronline.wikia.com/wiki/Bare_the_Brunt

**Comment by Torquemadra** [comment]
Fixed next patch, unlocks on kill, on engage not supported atm.
