### ISSUE TITLE
ToK Bestiary - Horror of Tzeentch unlock

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#4005]
For this unlock in The Blighted Isle you need to find and kill the Lost Horror, it is found at approx 20500 by 38000. I found two of this mob, both in the same area and active at the same time. I killed both but neither gave the unlock.

http://warhammeronline.wikia.com/wiki/Where_Did_You_All_Go%3F

**Comment by Torquemadra** [comment]
Fixed next patch
