### ISSUE TITLE
ToK Bestiary - Harpy unlock

### ISSUE THREAD

**Issue by Shadowsmove** [WarEmu/WarBugs#4006]
For this unlock in The Shadowlands you need to find and click on the Harpy Roost, it is found at approx 50000 by 43000. I found and clicked on the item and got the unlock but I did not get the title, The Bold.

**Comment by DanaBloodkiss** [comment]
Hello! Can you please always link a wiki to it , like here http://warhammeronline.wikia.com/wiki/House_on_the_Hill

**Comment by DanaBloodkiss** [comment]
Related to this https://github.com/WarEmu/WarBugs/issues/4073 and fixed.
