### ISSUE TITLE
Lair of Silveroak

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4010]
![lair norsca](https://cloud.githubusercontent.com/assets/16864486/12578474/d4023146-c429-11e5-8cea-d12cdf296fb0.jpg)
We managed to kill him but he dropped wrong item : Green item : Outlaw's Grudgecoat
Confirmed Drops : 
Drops 1-3 Rank 39 Rare BOE Chest pieces per kill.

Source : http://warhammeronline.wikia.com/wiki/Silveroak

**Comment by Torquemadra** [comment]
I would assume mobs have been locked down in terms of drops. Theres a lvl 42 hero I bug test against and drops 31 gear max.

**Comment by Soulwhisper** [comment]
https://www.youtube.com/watch?v=E0I-GatqMC8
About drops i found this on youtube.

**Comment by Torquemadra** [comment]
Loot tables correct in database.

**Comment by Evildoor** [comment]
This should have been closed.
