### ISSUE TITLE
[quest] Keep to the roads

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#4011]
C14 empire quest, reads to interact with a backpack item. Clicked all NPCs in c14 camp (cant recall which one gave me quest) and cannot complete.

Though the full text mentioned the Emperors Arms which I think is in c15 and may just need to be handed in there.

![741](https://cloud.githubusercontent.com/assets/16200780/12578447/d9bdea20-c3ee-11e5-9fb5-fe3d5110e751.png)

**Comment by DanaBloodkiss** [comment]
Good report. Noticed there is a bugged Quest Finisher and the second step was bugged too. Fixed in next Hotpatch. (Though the second step is leading into T4) Questfinisher on the first Quest is the Queststarter "Emil Trachsel).
