### ISSUE TITLE
Inluence Item  RVR T3 Elves

### ISSUE THREAD

**Issue by Poseidon-Bluestorm** [WarEmu/WarBugs#4012]
Hi,

I play DoK and actually In RvR T3 Elves Rewards, we have 3 Blue Cloak and only 1Purple Cloak.
I think one of blue cloak must be replace by a purple one with:

11 PV
9 Init
5 Weapon skill
98 Spirit Resist
98 Corpo Resist
98 Elem Resist
1% Crit reduce

Like Order Size.

Thx
Have a good Day

**Comment by Evildoor** [comment]
#2520
