### ISSUE TITLE
[NPC] Raven Hellmagus drops no loot and cannot be scavanged

### ISSUE THREAD

**Issue by vove-RoR** [WarEmu/WarBugs#4013]
In the Order's starting zone there is an area with Raven Hellservants, Raven Hellfangs, Raven Hellmaguses and Raven Hellmasters. It's a little bit to the north of where you start the game in emp, two quests to do there: Silencing the cannons and Test of mettle.

All of the mobs in that area besides Raven Hellmagus are lootable and scavangeable. Raven Hellmaguses drop no loot nor can be scavanged.

**Comment by Torquemadra** [comment]
Fixed next patch
