### ISSUE TITLE
Guard working out of group

### ISSUE THREAD

**Issue by Grywwy** [WarEmu/WarBugs#4015]
I think that guard work's even if the teammate is not in your group.

For example: 
-TANK and DD are in the same grp
-TANK gives guard to DD
-DD leaves grp
-Guard is still on the DD and the dmg received will be divided by the two (of course only if the DD stays in range of the TANK)

**Comment by Ryanfawkez** [comment]
Same goes for Oathfriend, it works even when your oath friend is getting hit in another zone; still builds grudges.

**Comment by noisestorm** [comment]
Did you really test the damage mitigation? Because the same happens when you join a SC for example. You still got the guard from your Tank but the damage somehow isnt mitigated anymore. (at least i have the feeling that its most of the time not working and need to be re-applied)
