### ISSUE TITLE
Able to heal keep door & npcs with defensive target healing skills.

### ISSUE THREAD

**Issue by Lileldys** [WarEmu/WarBugs#4017]
With keep door as my friendly target, with my Archmage's lifetap skills (Transfer Force and Balance Essence) I was able to heal the keep door in Barak Varr and in Ostland. Haven't tested others.
I was also able to heal keep lords with this method.(Did not screenshot, but easily reproducible)
![screenshot31530](https://cloud.githubusercontent.com/assets/13259775/12589164/4d6366e8-c454-11e5-8d25-4a09b7e6f857.png)

**Comment by Torquemadra** [comment]
You could always heal lords afaik

**Comment by ozarmidrashim** [comment]
Fixed on live.
