### ISSUE TITLE
Wierd Speedhack bug

### ISSUE THREAD

**Issue by sn3jk** [WarEmu/WarBugs#4019]
Encountered some kind of bug today which gave me speedhack, couldn't see any players or NPCs or interact with anything. After a while my character dropped through the floor and just kept on falling, that's when I logged.

I was setting up the addon "Aura" when it happened.
Went afk with the addon settings up and when i got back i continued to setup my addon. When I was done the bug had occurred.

After the restart you did today(jan 26-2016) my Aura addon was reset, don't know if it's relevant but maybe it has something to do with that.

![bugwar1](https://cloud.githubusercontent.com/assets/16905775/12593387/179e77f6-c471-11e5-87cd-362a74b0ab9c.png)
![bugwar2](https://cloud.githubusercontent.com/assets/16905775/12593389/1c5bf8f4-c471-11e5-87e3-d31ee23b2c38.png)
![bugwar3](https://cloud.githubusercontent.com/assets/16905775/12593390/1e5c5eaa-c471-11e5-9a3c-3463b1ca8824.png)

edit:
When i logged back in i was met with a blackscreen, solved that by using my book of binding.. 

![warbug4](https://cloud.githubusercontent.com/assets/16905775/12593547/eba74636-c471-11e5-88aa-09ab4b4c4128.png)

**Comment by noisestorm** [comment]
Looks like a casual packet corruption to me - nothing to worry about. Problem is already know and shows in all different kinds and forms. I had stuff like that already: :D (http://i.imgur.com/lPupaD1.jpg)
