### ISSUE TITLE
[Tactic] Breaking Point not working for cleft in twain

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#4020]
![tiggo_009](https://cloud.githubusercontent.com/assets/13809443/12593605/38415702-c472-11e5-8a6c-412f104b9b9d.jpg)

38% crit looks very low compared to the other giant slayer abilities. can you check please?

**Comment by noisestorm** [comment]
did you test 100 hits for each ability, or where can we see the numbers of actions used?

**Comment by Tiggonos** [comment]
this is after a full scenario you can see the % of skills used and can derivate for other skills.

**Comment by noisestorm** [comment]
Not sure if this one Sc segment is enough, especially since the skill in discussion is a dot i think(?), that may throw the randomness abit around, but maybe aza can look at it once hes back

**Comment by Tiggonos** [comment]
yes its more a suspicion then a proof, but there were problems with tactics and dots before.
