### ISSUE TITLE
wp influence item elve t3: wrong stats

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#4021]
ghrond's battlecoat and qhaysh battlecoat (t3 elve influence second stage) have the wrong stats.

1% reduced chance to be parried and 1% reduced chance to be critically hit should be vice versa.

the willpower coat definitly is not a melee dps item and thus doesnt need reduced chance to be parried.

**Comment by DanaBloodkiss** [comment]
Fixed in the next patch.

**Comment by Tiggonos** [comment]
HDL

;)
