### ISSUE TITLE
IB Guarded attack with Focused Offense

### ISSUE THREAD

**Issue by zerind1991** [WarEmu/WarBugs#4023]
Hello. I Noticed something weird when i use Guarded attack with focused offense tactik.
My armor is: 2390 if i set the tactik. Guarded attack grants 519 armor whitch lose 30% i guess from  tactik (im not entirely sure btw) if it does it still increase armor by 363 so it should be about 2753.
 What happaned insted this is: After i use Guarded attack armor goes from 2390 to1949 and when the buff expire it reduce to 1601 and stay like this until i change tactik. Its pretty much debuffing me.
(I tested it without any buff on me or pots).
Well i hope i could help you guys if you dont know about it yet. You doing a great job an keep up the good work.
Best Regards.

**Comment by ozarmidrashim** [comment]
FO isn't updating the counter immediately. Visual.

**Comment by Evildoor** [comment]
#2146
