### ISSUE TITLE
[WE/WH] Destealthing

### ISSUE THREAD

**Issue by noisestorm** [WarEmu/WarBugs#4026]
Just had a disrupt the second i went into stealth. Since the spell was a targeted single cast i instantly got kicked out of it - allthough it was defended. This i would call a bug.

Similar stuff also always happens with any projectiles already in flight as well. Maybe direct hits should only unstealth when you actually passed the ini check for the stealther and not just when any on-hit gets applied. Sadly i cant really find any video where i could verify my assumption, but stealth is still lackluster on so many ends, that this would be a great QoL fix anyways. (Basically either have some form of 'grace period' on entering stealth where you cannot be unstealthed, or just bind it to the actual pass of the init-check)

**Comment by Areanda** [comment]
Just a comment but the stealth is alr better then live.. on live with an aoe attck u wud get out of stealth also if u had a dot or wotever on u u couldnt even get in stealth. .
End of conclusion that i meant was u call it a bug wich actually on live wasnt

**Comment by ozarmidrashim** [comment]
2s grace given.
