### ISSUE TITLE
Butchering

### ISSUE THREAD

**Issue by mekon1** [WarEmu/WarBugs#4029]
Hammerwiki says squigs are ment to drop restoration blood from butchering the icespike and icehorn squigs in black fire pass don't drop it

**Comment by Squea** [comment]
Currently the butchering tables for mobs is a bit squirrely.  Squigs aren't worth farming at the moment because of porcine bile's limited use.  I believe they're working on it.

**Comment by noisestorm** [comment]
exact mob names always help, when you find something not properly working.

**Comment by Evildoor** [comment]
#2391
