### ISSUE TITLE
Quests with more than 4 rewards

### ISSUE THREAD

**Issue by Kelthas** [WarEmu/WarBugs#4030]
When finishing quest cannot choose reward intelligence talismans, choosing toughness talisman works tho.

**Comment by DanaBloodkiss** [comment]
General problem because there are more then 4 rewards. Nothing database related.

**Comment by Evildoor** [comment]
This bug (inability to select 5+ reward if quest has more than 4) was around since forever but i've not found a proper report for it, so this one will be used.
