### ISSUE TITLE
[quest] buying time

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#4031]
C14 dwarf in badlands.

Cannot find Teefgrinda, have searched extensively, up and down the caves and the platforms.

I have vague recollections that Teefgrinda was a large squig that was found on the chasm floor outside the caves entrance. There are a couple of little squigs there but nothing else.

I could be wrong.

![144](https://cloud.githubusercontent.com/assets/16200780/12601270/d415606a-c46d-11e5-9c97-2427decbd3e6.png)

![665](https://cloud.githubusercontent.com/assets/16200780/12601272/d5497e76-c46d-11e5-9206-8bd338dcc8df.png)

**Comment by DanaBloodkiss** [comment]
He's an Orc location: map 2 1284790 904155 6132 and he is spawned. I checked it. Closed.

**Comment by Torquemadra** [comment]
Dammit, I spent literally a couple of hours exploring that place and after your post found him right of a junction where I went left  >:( sorry to waste your time.
