### ISSUE TITLE
Player Stuck in World Geometry

### ISSUE THREAD

**Issue by GoldenNewblett** [WarEmu/WarBugs#4032]
Used Book of Binding that was set in Komar, Mount Bloodhorn.  Stuck in Zone 0, and cannot seem to get out.  Any help would be appreciated. Skjonne, LvL 7 Ironbreaker.

**Comment by Torquemadra** [comment]
type /stuck twice within 5 seconds and get teleported back to start area.

**Comment by Evildoor** [comment]
Read the rules of the bugtracker. Then read Torquemadra's comment. Then read forums - such situation was already encountered and solved countless times.
