### ISSUE TITLE
Sc Flag cannot be taken

### ISSUE THREAD

**Issue by zerind1991** [WarEmu/WarBugs#4033]
Hello. I noticed scenario flags somtimes bugged can not be taken and the other realm who owns it still get the point. I can not test it but i have seen many times 1 people standin on flag and log out after he capped it so that way the flag cannot be taken anymore.

**Comment by Evildoor** [comment]
#3787

**Comment by zerind1991** [comment]
Closed mean fixed or you already know about that?

2016-01-27 10:01 GMT+01:00 Evildoor <notifications@github.com>:

**Comment by Evildoor** [comment]
I linked the ticket where this was already reported.

**Comment by zerind1991** [comment]
Ah okey thank you

2016-01-27 10:25 GMT+01:00 Evildoor <notifications@github.com>:
