### ISSUE TITLE
[Craft] changing profession

### ISSUE THREAD

**Issue by Eresanion** [WarEmu/WarBugs#4034]
Hi impossible to change/respec craft.

**Comment by Evildoor** [comment]
You mean ".respec" does not works?

**Comment by noisestorm** [comment]
It did work yesterday and since there was no patch til then, i think hes just not aware of having to use commands.
use 
.respec Gathering
or
.respec Crafting
for your respective job

**Comment by Eresanion** [comment]
Okay it  works sorry
