### ISSUE TITLE
KOTBS missing boots models

### ISSUE THREAD

**Issue by Asherdoom** [WarEmu/WarBugs#4035]
KOTBS got all boots so far (T2) models missing. They are equipped but character figures as naked on his feet. Relogging, cancelling cache and similr stuff is not working.

**Comment by Evildoor** [comment]
Item names, please.

**Comment by Asherdoom** [comment]
all rvr t1 & t2 boots and Shallyan Greaves.

**Comment by Evildoor** [comment]
Exact names of "all rvr t1 & t2 boots", please.

**Comment by Asherdoom** [comment]
Decimator's guardian Boots, Obliterator's Guardian Boots, Devastator's Guardian Boots

**Comment by DanaBloodkiss** [comment]
Cannot find a single one of these items in the DB, not the exact names.

**Comment by Asherdoom** [comment]
i ll post a screen here the t1 and t2 boots i sold i am equipping this atm.

![rhen_000](https://cloud.githubusercontent.com/assets/16918614/12619020/0f57d7fc-c4f5-11e5-9a20-c01926549ffd.jpg)

**Comment by DanaBloodkiss** [comment]
Thanks!

**Comment by DanaBloodkiss** [comment]
Though we can fix this item when you know more post the item names

**Comment by Asherdoom** [comment]
i agree with ya as soon as i get more boots i screen and post here be sure!
