### ISSUE TITLE
Chalice of Thunder - No Essence Regen

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#4039]
T2 Chaos Inf Chalice has no essence regen.

Can't play my dok anymore :(

**Comment by taccr** [comment]
Same goes for WP Inf Tome.
Sigmarite Tome of Thunder in Empire T2.

**Comment by genisaurus** [comment]
Can you confirm that this is not a visual bug?

**Comment by taccr** [comment]
It's not just visual. New tooltip description is also missing.

Went in combat and used flee -> No Regen.

**Comment by ozarmidrashim** [comment]
Already on it.
