### ISSUE TITLE
[Minor]Quest text don't resolve player names in the NPC chat bubbles

### ISSUE THREAD

**Issue by dfumagalli** [WarEmu/WarBugs#404]
Hello,

I am at a quest NPC, she's addressing me with her chat bubble but she's not correctly putting in my name.

In example, instead of saying "There's a path for you, Vaerah", she says: "There's a path for you, [Name]".
![vaerah_046](https://cloud.githubusercontent.com/assets/5745561/4434863/af9106c2-4728-11e4-90d6-dafa507e3e49.jpg)

**Comment by Evildoor** [comment]
General issue not tied to one quest. https://github.com/WarEmu/WarBugs/issues/276
