### ISSUE TITLE
Sham Reward T3 Inf

### ISSUE THREAD

**Issue by Sakhou** [WarEmu/WarBugs#4041]
Hello ! 

Not sure if this has been reported yet can't seem to find a issue made here for it, but the Shaman class is missing 1 purple cloak choice which should be Qhaysh Shroud instead of Maiden's Greatcloak. As of right now the Shaman has 3 blue cloaks and 1 purple cloak to choose from instead of 2 blue and 2 purple.

Sham screen cloak 
<a href="http://www.hostingpics.net/viewer.php?id=801781Ghazbag003.jpg"><img src="http://img11.hostingpics.net/thumbs/mini_801781Ghazbag003.jpg" alt="Heberger image" /></a>
AM screen cloak 
<a href="http://www.hostingpics.net/viewer.php?id=402892Nirvella000.jpg"><img src="http://img11.hostingpics.net/thumbs/mini_402892Nirvella000.jpg" alt="Heberger image" /></a>

**Comment by Styrkarr** [comment]
Fixed in next patch.
