### ISSUE TITLE
WP Devastator proc Mending not working correctly

### ISSUE THREAD

**Issue by Isgard** [WarEmu/WarBugs#4047]
For the Warrior Priest Priest the 5 Pieces Proc "Mending" only gives 55 HP, instead of 191 health(tooltip), either tooltip is wrong, or ability.

**Comment by noisestorm** [comment]
Screenshot that stuff. Not sure if healdebuff are working on it or not, but some screenshot could help

**Comment by Isgard** [comment]
![wp_mending_proc](https://cloud.githubusercontent.com/assets/16906830/12626597/b5519cb2-c539-11e5-8b84-1217aec71d7e.png)
