### ISSUE TITLE
mobs mobs mobs

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#4050]
just been followed for miles through high pass by a load of mobs that should have run back to their spawns, they dont hit me, they just wont leave me alone either

![mordraeon_000](https://cloud.githubusercontent.com/assets/16922842/12620792/9bf74b50-c515-11e5-88c0-ff0b1b6e5a88.jpg)

**Comment by Soulwhisper** [comment]
![some mobs now keep following forever-visual bug](https://cloud.githubusercontent.com/assets/16864486/12620901/cacab10e-c526-11e5-896f-8f42b38502f0.jpg)
I was ready to upload it.Looks like major bug.Only if you attack them they dissapear visually(respawning to their starting location)
