### ISSUE TITLE
KotBS invalid Devastator Casque appearance

### ISSUE THREAD

**Issue by Cr3nshaw** [WarEmu/WarBugs#4053]
Oi, I belive this is correct model for devastator casque. Im not 100% sure tho since i cant find info on lvl requirements for live dev set. I had helmet as seen below on 22 kotbs, painted in blood red, so i assume its  devastator set piece. 
![lirric_006](https://cloud.githubusercontent.com/assets/10353875/12621783/79925dae-c522-11e5-938f-6efd86d63c14.jpg)
![lirric_005](https://cloud.githubusercontent.com/assets/10353875/12621801/9086a3d0-c522-11e5-9eaa-d029cb96314b.jpg)

**Comment by Shtrober** [comment]
Devs, add this helmet in game, please! Or look at chapter 13 hign elves last influence reward. It have bugged appearance, helmet just be in center of my maw. Move it to my head, if you can. Name of this item: Casque of windsteel.
![merir_032](https://cloud.githubusercontent.com/assets/16929424/12633438/eb0d21a2-c582-11e5-843d-0ffe997c40e0.jpg)

**Comment by DanaBloodkiss** [comment]
Fixed "Casque of windsteel".

**Comment by Samotnick** [comment]
It IS correct model for devastator from live.

**Comment by DanaBloodkiss** [comment]
I still don't understand what you guys are talking about. Which item need which items appearance?

**Comment by Cr3nshaw** [comment]
Dunno why Casque of Windsteel got into tis report. My original point is that Devastator Casque has wrong model and correct one is provided on 2 screen shots in first post. Samotnick's comment was on the topic.

**Comment by DanaBloodkiss** [comment]
Do you have the name of an item with the correct model?

**Comment by Cr3nshaw** [comment]
I belive it was the only one with such a model but im not sure. If screenshots arent enough than i appology for this thread.
