### ISSUE TITLE
[Minor Bug] the DING noise on kill not working

### ISSUE THREAD

**Issue by Luranni** [WarEmu/WarBugs#4054]
I know I know, not a big deal, but I love that noise. I believe it is connected to Dammaz Kron? Anyway since today's patch it isn't working when you get a death blow.

**Comment by Evildoor** [comment]
What noise? Is this some feature of an addon?

**Comment by Luranni** [comment]
It goes DING! You killed so-and-so, worked fine before the patch. I think it is connected to Dammaz Kron, the noise is the same as quest hand-in and completion.

**Comment by Evildoor** [comment]
Dammaz Kron is not our problem.
