### ISSUE TITLE
NPC visual bug

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4057]
![npc bug](https://cloud.githubusercontent.com/assets/16864486/12627560/2ca31a68-c547-11e5-829d-953eeb8a7825.jpg)
Ellyrian Reaver.His location(51,13) : 
![location](https://cloud.githubusercontent.com/assets/16864486/12627594/5d14c548-c547-11e5-932f-d0652988065e.jpg)

**Comment by DanaBloodkiss** [comment]
Fixed in next Hotfix.
