### ISSUE TITLE
Rally Master does not exist - High Elf Chapter 4 (Chrace) 

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4061]
![no chapter 4 influence counter in tok chrace](https://cloud.githubusercontent.com/assets/16864486/12628154/7afe96ee-c54a-11e5-9df6-96b904ba96dd.jpg)

**Comment by Torquemadra** [comment]
Hes downstairs inside the tower at the camp....

**Comment by Soulwhisper** [comment]
Correct my bad.

**Comment by Soulwhisper** [comment]
Correct.My bad
