### ISSUE TITLE
Influence Rewards are not selectable.

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4065]
![pisth_128](https://cloud.githubusercontent.com/assets/16864486/12628719/2f7fa552-c54d-11e5-8355-20ec12dd95ee.jpg)
![pisth_127](https://cloud.githubusercontent.com/assets/16864486/12628720/2f82fb62-c54d-11e5-85c9-8a117617319a.jpg)
There is a rally master there but cant pick up the rewards from him.

**Comment by Evildoor** [comment]
Have you unlocked the corresponding chapter in ToK?

**Comment by Soulwhisper** [comment]
![1234](https://cloud.githubusercontent.com/assets/16864486/12643710/708c67fa-c5c6-11e5-8d14-7aad41cda5b2.jpg)
Yes

**Comment by Evildoor** [comment]
Strange. He is a rally master for High Elves chapter 1, not RVR
![archmage_000](https://cloud.githubusercontent.com/assets/11015074/12643969/a106dfb4-c5d0-11e5-85e0-6b7995ed52a5.jpg)
and he shows correct rewards to me.

**Comment by Soulwhisper** [comment]
Hm...i have unlocked all chapters of High Elves...yeah thats strange...maybe it has something to do with races? I will check and i will report back

**Comment by Soulwhisper** [comment]
![pisth_132](https://cloud.githubusercontent.com/assets/16864486/12644230/154256da-c5ca-11e5-9555-327bdb2a1281.jpg)
Dunno how this happened...
Correct RvR influence rewards located at Tor Aendris High Elf War Camp Blighted Isle
![pisth_131](https://cloud.githubusercontent.com/assets/16864486/12644250/421e9cb8-c5ca-11e5-9dde-7bc88267e49c.jpg)
