### ISSUE TITLE
Librarian in chapter 1 Blighted Isle

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4066]
![librarian chapter 1 blighted isle sells wrong items](https://cloud.githubusercontent.com/assets/16864486/12628902/12055304-c54e-11e5-9ea9-ea3740e419ab.jpg)
He sells crafting items instead of trophies etc.

**Comment by DanaBloodkiss** [comment]
Fixed in next Hotfix. (Removed the vendor list , though he's not a Trophy Vendor.)
