### ISSUE TITLE
Harpy mobs not attackable

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4067]
![pisth_129](https://cloud.githubusercontent.com/assets/16864486/12629032/9d06d2c0-c54e-11e5-9f84-13c51537a34f.jpg)
Area in Blighted Isle ![gg](https://cloud.githubusercontent.com/assets/16864486/12629042/a4dde8a8-c54e-11e5-8822-425ee33854e2.jpg)

**Comment by DanaBloodkiss** [comment]
Respawned the mob = fixed in next Hotfix.
