### ISSUE TITLE
NPC Kazgrim Thorlunson in The Badlands

### ISSUE THREAD

**Issue by Kringe** [WarEmu/WarBugs#4070]
NPC Kazgrim Thorlunson in The Badlands,  no longer offers the tier 3 rvr kill quest  (kill 20 players) at lvl 26 (Steel something I turned it in and tried to get it again, checked on several other characters and relogged)

**Comment by Karcasse** [comment]
I have exactly the same problem. My character is Cark, White Lion, lvl 28, rr 19.

**Comment by DanaBloodkiss** [comment]
Fixed in next patch. Corrected the level to 22.
