### ISSUE TITLE
Potions randomly disappearing when zoning

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#4071]
After playing for a while tonight me and my party had their potions disappear randomly while zoning between the lakes.
Someone posted about it here https://github.com/WarEmu/WarBugs/issues/2796#issuecomment-175886795
but I think it belongs into a new report.

Happening since todays patch.

**Comment by noisestorm** [comment]
Can confirm, had that happening on my WH yesterday night as well

**Comment by Evildoor** [comment]
Let's make it clear - what exactly you meant by "potions"? Items in inventory? Or buffs from drinking potions? Question to both of you.

**Comment by taccr** [comment]
Potions buffs were removed. However this hasn't happened to me since month. So it might have been fixed already.

**Comment by Evildoor** [comment]
Ok then.
