### ISSUE TITLE
Shadow Warrior Barrage

### ISSUE THREAD

**Issue by MalakarSW** [WarEmu/WarBugs#4072]
It is obvious that the Skirmisher tree had its abilities swapped and switched around. The Live version of Skirmisher looks like this: http://waronlinebuilder.org/#career=sw;

ROR's ingame tree looks like this:
![malathorn_002](https://cloud.githubusercontent.com/assets/16929056/12633647/5548be24-c541-11e5-99b0-af4e37fb80bc.jpg)

The ability in question is Barrage. Barrage was swapped as you can obviously tell from the higher end of the Tree to the lower end. Due to this, the ability will appear as if you can't use it at level 21, the earliest level you can obtain it. If you attempt to click it, it will give you this statement just like the icon says(Which is also red'ed out): 
![malathorn_000](https://cloud.githubusercontent.com/assets/16929056/12633691/a6a16c9e-c541-11e5-931a-04b43384fc12.jpg)

However, you are able to use this ability regardless. As shown here:
![malathorn_001](https://cloud.githubusercontent.com/assets/16929056/12633708/bd32f7d4-c541-11e5-8da2-ee4ef9be8eaa.jpg)

You can see the cooldown, the damage and the AP spent. The ability works even though it says it doesn't. I'm sure this might also be the case for the other Skrimisher abilities that were swapped.

Anyway, I don't know if this is something hard coded into the game and you'll just have to live with it or if perhaps someone missed switching a 0 to a 1 or clicking a box somewhere. Just wanted to bring this to the attention of the devs to try and fix it so that people leveling Shadow Warrior, specifically Skirmisher, don't get the wrong idea that their abilities don't work because the icons and such say so.

**Comment by Evildoor** [comment]
Same happens to any other abilities which were moved around. This is hardcoded into client, we can do nothing.
