### ISSUE TITLE
[ToK] The Bold and The Impure titles not unlocking

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#4073]
On my way working with unlocks I attempted to get The Bold (house on the Hill) and The Impure (Things best left unknown). I got the unlock but the title just shows up as ??? when I mouse over it. If it matters I did both with a zealot.

**Comment by DanaBloodkiss** [comment]
I think I fixed it here https://github.com/WarEmu/WarBugs/issues/4038 also it seems correct in the Database.

**Comment by DanaBloodkiss** [comment]
And the other one here https://github.com/WarEmu/WarBugs/issues/4006

**Comment by DanaBloodkiss** [comment]
Though both are working on the Dev server just tested them. So wait till next Hotfix.
