### ISSUE TITLE
NPC Bug: Dwarf Slayer BO Guard

### ISSUE THREAD

**Issue by Vandorkholme** [WarEmu/WarBugs#4075]
#Sometimes the slayer guard at battle objectives in dwarf/greenskin zones spawn without a face.(Not sure if T2 ones are affected but I have seen it multiple times in T3)
http://i.imgur.com/9qaTSWi.jpg

**Comment by DanaBloodkiss** [comment]
I removed the NPC helmet. I think Helmet and Hair cross and bug out. Should be fixed in next Hotfix.
