### ISSUE TITLE
[Item] Hammergun!!

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#4076]
Recruits Warhammer has the appearance of a pistol, interestingly before today (Changelog 27.01.2016) it had the appearance of a rifle....

C1 Dwarf Influence item.

![622](https://cloud.githubusercontent.com/assets/16200780/12639289/83195bbc-c571-11e5-9509-0b18a7a48ac2.png)

**Comment by DanaBloodkiss** [comment]
Fixed in next Hotfix.
