### ISSUE TITLE
[Craft] Apothecary makes Intellect potion of wrong level

### ISSUE THREAD

**Issue by Abagor** [WarEmu/WarBugs#4077]
I've got Apothecary skill at 200.  Usually, when I make a potion using main ingredient of **25** lvl, I get a potion with minimal lvl **10** requirement.

Issue: When I make **Intellect** potion using main ingredient of **25** lvl, I get a potion with minimal **35** lvl requirement instead of 10.

**Comment by Evildoor** [comment]
#1644
