### ISSUE TITLE
Raven Breaker Spawn Dead

### ISSUE THREAD

**Issue by saupreusse** [WarEmu/WarBugs#4083]
In Highpass 58/28 are some raven brakers which spawn lying dead on the ground.
they can attack you and you can kill them, its just the animation thats buggy.
Also few of them have the wrong lvl ( lvl 2 ). they should be lvl 30 mobs not lvl 2.
http://i.imgur.com/fBwuutp.jpg

**Comment by DanaBloodkiss** [comment]
Fixed in next Hotfix.
