### ISSUE TITLE
[Quest] Piers Of Destiny, Norsca 

### ISSUE THREAD

**Issue by Kloies** [WarEmu/WarBugs#409]
This quest is extremely odd as you should be able to finish it by going to the docks. But instead you kill a Gnashfang Winterwolf (?) and the quest is completed and you just have to turn it in.

**Comment by Evildoor** [comment]
I do believe that wolf has nothing to do with this, and you just have to speak to the NPC again - all "Scout" quests behave in that way because right now we have no means to determine if the player was in correct location (i.e. docks) or not.
