### ISSUE TITLE
[Zealot] Scourged Warping Tactic Bugged

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#4091]
Currently if Scourged Warping Procs while Scourge is being cast, it consumes the proc rather than allowing a second (instant) cast of scourge after the first finishes. On live if the tactic procced while scourge was casting, it was not consumed allowing for the second cast.

**Comment by Symbelmyne** [comment]
Confirmed, proc is consumed when proc while Scourge is being full time cast.

**Comment by spacestarkid13** [comment]
Scourged Warping keeps proc even if removed. Noticed it when switched to healing set of tactics. Harbinger of Doom wasn't enabled.
