### ISSUE TITLE
[Appearance] KOTBS - Baraz Espaliers wrong appearance

### ISSUE THREAD

**Issue by Rhombutts** [WarEmu/WarBugs#4092]
![thickmuck_esp](https://cloud.githubusercontent.com/assets/13096975/12655690/262389b2-c5c8-11e5-832c-6646a4de3779.jpg)
![baraz_esp](https://cloud.githubusercontent.com/assets/13096975/12655786/97ec4de0-c5c8-11e5-8ca6-70577198710a.jpg)
![same_reward](https://cloud.githubusercontent.com/assets/13096975/12655790/9ece8808-c5c8-11e5-8020-17c98c838f81.jpg)

Baraz Espaliers have the wrong appearance and wrong icon, they should share the same appearance with Thickmuck Espaliers but instead are cloth shoulders that are waist level.

**Comment by Styrkarr** [comment]
Fixed in next patch.
