### ISSUE TITLE
Building a second turret

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4093]
Building a second gun turret when you already have built one bugs 
Career Resources Window(opacity lowered),Pet Action Bar(opacity lowered and Penetrating Round icon disappears) + Top Left icon of gun turret <Under primary target> (opacity lowered)
![12345](https://cloud.githubusercontent.com/assets/16864486/12656093/04f979e4-c605-11e5-84d2-1e9b2e034736.jpg)
Just visual bugs.
**UPDATE** it happens when you try to build flame turret etc etc...so in conclusion you have to remove the current turret and rebuilt from the beggining to make it not to bug.

**Comment by Soulwhisper** [comment]
First gun Turret and what it should look like after building the second one.
![1234](https://cloud.githubusercontent.com/assets/16864486/12656138/4425e166-c605-11e5-84de-ab644020a396.jpg)

**Comment by ozarmidrashim** [comment]
No idea how to fix, sorry.

**Comment by Kallixenia** [comment]
could be error from addon ?

**Comment by Soulwhisper** [comment]
Probaply something wrong with UI on rebuilding...we can check on the future though.
