### ISSUE TITLE
[Appearance] Can't apply dye

### ISSUE THREAD

**Issue by Rhombutts** [WarEmu/WarBugs#4094]
![can tdye](https://cloud.githubusercontent.com/assets/13096975/12656470/77f4b000-c5cc-11e5-9d09-102659e12a8e.jpg)

I applied a new appearance over my belt (old one had no model), the new appearance however can't have dye applied to it.

**Comment by Cr3nshaw** [comment]
That belt can only by dyed by vendor option - dye all.

**Comment by noisestorm** [comment]
The item will most likely still not change its color, despite coloring it through Vendor right? There are just some items that have no area to change its color. This belt is most likely one

**Comment by Rhombutts** [comment]
No, the work around to dying it is to un equp everything then by the vendor use the dye all option.  Aside from that theres no way to apply item dye like say Chaos Black or Blood Red, it tells me that it can't be dyed.

So only vendor dye can be applied, not item dye.

**Comment by genisaurus** [comment]
This is a client problem, not a server one. Dyeable regions are defined by the client. Closing, because it's not something we can fix.
