### ISSUE TITLE
T3 Kill Quest A Pile too Far wrong level

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#4095]
I can still get this quest at level 20 (from Ulthrin Dreadmark in the Avelorn Warcamp), it should be limited to 22

![evildentalplan_001](https://cloud.githubusercontent.com/assets/13975292/12657918/76e0f2b0-c5cb-11e5-8b16-9858f478b2e1.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
