### ISSUE TITLE
[Appearance] Magus Duelist shoulders

### ISSUE THREAD

**Issue by epobleepo** [WarEmu/WarBugs#4097]
Magus duelist appearance is currently the wrong one. It was originally working upon duelist item launch but seems to have broken along the way. 

Current:

![hypnodisc_034](https://cloud.githubusercontent.com/assets/16072050/12658839/64e47202-c603-11e5-9de5-045d598a85d7.jpg)

What they should be:

![qrohsct](https://cloud.githubusercontent.com/assets/16072050/12658904/b2489a0a-c603-11e5-9048-75e7d9d3460b.png)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
