### ISSUE TITLE
[ToK] Warpblade Rat Ogre gives wrong unlock

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#4100]
At the moment when you kill a warpblade rat ogre (grovod caverns, destruction side), rather than giving a skaven related unlock, it gives the unlock of snotling. All of the kills count as snotlings rather than skaven

![evildentalplan_004](https://cloud.githubusercontent.com/assets/13975292/12660645/5aa9f56a-c5da-11e5-995e-77b95577326c.jpg)

**Comment by DanaBloodkiss** [comment]
Strange. Seems all fine in the Database.

**Comment by DanaBloodkiss** [comment]
Fixed in next Hotfix.
