### ISSUE TITLE
Rimewing Eagle (Level 30) hostile mob in Chrace

### ISSUE THREAD

**Issue by MalakarSW** [WarEmu/WarBugs#4101]
Level 30 Hostile mob named Rimewing Eagle is found 'merely pretending' to be dead in Chrace, around level 9 and 10 mobs. 

![malathorn_003](https://cloud.githubusercontent.com/assets/16929056/12660933/afd83f56-c5e4-11e5-9fa4-b840e0811845.jpg)

Merely Pretending. 
![malathorn_004](https://cloud.githubusercontent.com/assets/16929056/12660950/c8fef2e0-c5e4-11e5-9fd2-e58d66783d41.jpg)

Normally I wouldn't care but the thing is, for a new player snooping around/leveling from quests, the Rimewing Eagle is not exactly easy to spot and can be easily overlooked which will lead to a quick one-shot on a level 8 or 9. 

(Don't mind the T3 kill quests *coughs*) 

I might just rename this entire thing to "The Birds of Chrace".  There is also eagles outside of the Elisia PQ in Chrace that are in the water.
![malathorn_005](https://cloud.githubusercontent.com/assets/16929056/12661061/77c199ae-c5e5-11e5-98c8-eb3e0cdcf35e.jpg)

**Comment by DanaBloodkiss** [comment]
Fixed in next Hotfix.
