### ISSUE TITLE
Invalid NPC

### ISSUE THREAD

**Issue by steve38h** [WarEmu/WarBugs#4102]
Quest ID 779,objld=159190 of 1
Location Talabecland 44055,55312
NPC name Alchemist Brond
THX
Soned :)

**Comment by Ryanfawkez** [comment]
Cannot be fixed yet, as Mount Gunbad isn't implemented.

**Comment by erkislev** [comment]
![invalid](https://cloud.githubusercontent.com/assets/16850861/12944394/beb5286e-cff7-11e5-9ab4-28bcb3b1f186.jpg)

**Comment by Evildoor** [comment]
#2802
