### ISSUE TITLE
Bestairy: Snotling

### ISSUE THREAD

**Issue by Laurell-Silentshade** [WarEmu/WarBugs#4103]
Clicking on Loose Rock (48,48) in Blighted Isle is supposed to unlock "And I just cleaned my Boots"

**Comment by noisestorm** [comment]
Screen with location and with source of unlock if possible

**Comment by Laurell-Silentshade** [comment]
[http://warhammeronline.wikia.com/wiki/And_I_Just_Cleaned_My_Boots](url)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
