### ISSUE TITLE
Siege Weapons - Shoot from anywhere, anytime

### ISSUE THREAD

**Issue by Faleene** [WarEmu/WarBugs#4107]
When siege weapons were working, the window that allows you to mount the weapon / exit would not disappear when you moved out of range of the siege weapons.  This allowed you to be able to fire the siege weapon from anywhere in the zone, it also prevented anyone from being able to enter as long as you didn't close the window.

On a sidenote, the siege weapons breaking could be a case of someone that reserved the weapon by having the weapon logging out, which prevents anyone from being able to access them.

**Comment by Faleene** [comment]
Just confirmed that when having the siege weapon window open.  If you log out while it's opened, and log back in again, the siege weapon can no longer be used

**Comment by genisaurus** [comment]
Was fixed at some point.
