### ISSUE TITLE
Relief of Gotland description error

### ISSUE THREAD

**Issue by Ravenheart87** [WarEmu/WarBugs#4110]
The Relief of Gotland quest shows the following message in its short description: "Invalid Npc, plz report to GM. QuestID 29737,ObjId=72608"
![bug](https://cloud.githubusercontent.com/assets/16955016/12672951/f9301b66-c679-11e5-8700-fa83a6e8b446.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
