### ISSUE TITLE
Disconnects/Lag out due to paket corruption or other reason

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#4115]
im sure devs are aware, but i think a bug entry cant hurt and perhaps players can write in coments the circumstances when it happens.

what my experience is, that this bug happens especially when playing in group and in scenarios. i experience very seldom that lag out in the rvr scenario or when i pug alone and dont queue and join sc in a party.

sometimes waiting in the sc long enough the game recovers, sometimes the sc ends and you need to restart client to play again.

the issue got worse with the last few patches. there was one patch when it was introduced first, but i dont remember which one, perhaps the one you adressed latency and introduced move prediction?

i hope this helps!

**Comment by saupreusse** [comment]
I can tell that i often disconnect while fighting near one of the BO's in gates of ekrund.

**Comment by Evildoor** [comment]
"but i think a bug entry cant hurt and perhaps players can write in coments the circumstances when it happens." - sure. But we already have an entry. #1810. Use it.
