### ISSUE TITLE
[Item] Chosen T3 Inf Reward

### ISSUE THREAD

**Issue by Syddz** [WarEmu/WarBugs#4117]
Elves : missing cloak [Qhaysh Changehide](http://www.arsenalofwar.com/armor/Destruction/Qhaysh%20Changehide).

Dwarves/GS : Thickmuck Chaos Seal and Thickmuck Dark Band have the same stats, seems that the real missing item is [Qhaysh Herald](http://www.arsenalofwar.com/items/Destruction/Qhaysh%20Herald).

**Comment by Styrkarr** [comment]
Fixed in next patch.
