### ISSUE TITLE
T3 kill quests can be taken before 22

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#4121]
Majority (if not all) kill quests are affected.
Can take them at r21. Haven't checked at r20.

**Comment by vove-RoR** [comment]
I checked it and could take only 2 quests from t3 (with a character being t2) and they were not the repeatable ones. Can you write the names of the quests?

**Comment by taccr** [comment]
My rank 21 quest log with t3 only quests. (Ignore War is upon is quest - Didn't want to cancel that for the screenshot)

[R21 Quest Log](http://img2.uploadhouse.com/fileuploads/22034/22034262d58b5073fe4bc1cc57bb7f3890036307.png)

**Comment by vove-RoR** [comment]
> My rank 21 quest log

Then they must be possible to obtain on higher level or only one faction, my toon in T2 is 15 (destro) at the moment and I cannot take the ones you have. Judging by the quest names looks like you play Order.

**Comment by Ryanfawkez** [comment]
Will be fixed in the next patch.
