### ISSUE TITLE
(Regenerative Shield) RP

### ISSUE THREAD

**Issue by Landaren** [WarEmu/WarBugs#4122]
According to the rules that I read on the forums regarding tactics and abilities, Regenerative Shield should stack with armor increasing buffs. 
If tactics do indeed stack with buffs, Regenerative Shield does not increase your armor if you are using a Armor Potions, or Prayer of Absolution, or Guarded Attack.

**Comment by Landaren** [comment]
http://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=9444&hilit=Tactics+Stacking+With+buffs

This was the post Az made about tactics stacking, I may have misread or interpreted what he wrote incorrectly.

**Comment by taccr** [comment]
It should stack according to RoR stacking rules but it never did stack on live. There's a few exceptions in the game and this is one of them.

What you are looking for is in here: https://github.com/WarEmu/WarBugs/issues/2537

**Comment by Evildoor** [comment]
Closing per #2537
