### ISSUE TITLE
Riposte

### ISSUE THREAD

**Issue by Moosrose** [WarEmu/WarBugs#4123]
I think Riposte is not working as intended. Tooltip: Each time you parry an enemy's attack, you will strike them back for xxx damage which they can not prevent.
![riposte](https://cloud.githubusercontent.com/assets/16966336/12691423/f9e4d566-c6eb-11e5-9841-c3f628e8796d.jpg)

**Comment by ozarmidrashim** [comment]
And what exactly are you proving with this screenshot, in which you only show your own outgoing damage?

**Comment by Moosrose** [comment]
if they cannot prevent the dmg from riposte why the dmg from riposte is mitigated? on live the dmg mitigation from riposte was not possible. that's why I add screens where u can see that its working not correctly

**Comment by Torquemadra** [comment]
Unpreventable, not unmitigated damage

**Comment by ozarmidrashim** [comment]
Unpreventable means that they are not able to defend against the attack. This is because Riposte could loop if you strike someone with 100% parry.

**Comment by Moosrose** [comment]
ok then sry for disturbing if its like that
