### ISSUE TITLE
Marauder Item: Grim Midstrap 

### ISSUE THREAD

**Issue by Moosrose** [WarEmu/WarBugs#4124]
Maybe block is a bit fail for Marauder. 
![belt](https://cloud.githubusercontent.com/assets/16966336/12691493/9ff0c398-c6ec-11e5-9e92-7adeff604254.jpg)

**Comment by taccr** [comment]
Not really a bug. Just bad itemization.

**Comment by balgax** [comment]
Change wound to strengt would be appreciated

**Comment by Styrkarr** [comment]
"Change wounds to strength would be appreciated", no.

Change 2% Block by 2% Parry.
Fixed in next patch.
