### ISSUE TITLE
[Ability] Whirling Pin is defendable

### ISSUE THREAD

**Issue by Thorindor** [WarEmu/WarBugs#4126]
Introduction:
Whirling Pin is a Shadow Warrior ability that will self punt the player if there is an enemy in range capable of being snared.  Currently, the ability is being dodged/blocked.

Details:
The text of the ability is: All enemies within 30ft become snared, reducing movement speed by 40% for the next 10 seconds.  You are knocked back away from your enemies.

On live, whirling pin and the squig herder mirror ability did not trigger a defence check.  Neither ability does damage.  These self punts functioned the same way as the WH/WE self punts that were also non-damaging abilities and not subject to defence checks.  

See the combat log in the attached screen shot for an example of whirling pin being dodged.  I have also noted it being blocked.  
![thorondir_004](https://cloud.githubusercontent.com/assets/16969273/12693899/4d40db2a-c6d7-11e5-9c1b-70429a22f3e2.jpg)

Additional information:
Whirling pin also does not work if the enemy is immune to snares.  This is working as intended and not the bug I am reporting.  

How to reproduce bug:
Use whirling pin on enemy PVE targets or enemies.  Occasionally it will not activate and the combat log will note that it was defended against. 

 
.

**Comment by noisestorm** [comment]
This is well known and was afaik implemented on purpose. Sadly i dont really know where i should look for on the forum, im quite sure there was some talk about that

**Comment by Chummi** [comment]
got fixed on purpose and it always worked like it now does.

**Comment by Chummi** [comment]
https://github.com/WarEmu/WarBugs/issues/811

**Comment by sullemunk** [comment]
Whirling pin can be Disrupted by Youself aswell
