### ISSUE TITLE
Feathered (coin) Acolytes wrong level?

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#4127]
As per patch notes http://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=11149

It was noted that 6 feathered acolytes of level 23 would be boosted to 39-40. Well I can find 6 feathered **_coin_** acolytes in altdorf of 22-23 but no others.

![9554](https://cloud.githubusercontent.com/assets/16200780/12694018/67ce3f18-c6ec-11e5-801c-6ccf78490305.png)

**Comment by Ryanfawkez** [comment]
Yes, NPC levels were not updated with the last patch.
