### ISSUE TITLE
[Tactic] Regenerative Shielding missing -10% armorpen

### ISSUE THREAD

**Issue by Scrilian** [WarEmu/WarBugs#4130]
I don't know if its only visual bug, but somehow the buff shows only +armor and not the -10% armor pen, which shows both on the Zealot tactic.
http://i.imgur.com/HevzALf.jpg

**Comment by Scrilian** [comment]
http://i.imgur.com/I43vw0N.jpg

**Comment by noisestorm** [comment]
You could save yourself and us a bit of trouble if you next time simply use the .getstats feature and see for yourself. Because it is working.
