### ISSUE TITLE
At Least They'll Stay Cool

### ISSUE THREAD

**Issue by Averatos** [WarEmu/WarBugs#4131]
The "At Least They'll Stay Cool" ToK unlocks for Bears dosnt work 

Collect 5 Bear Pelts to unlock the entry. Got 6 now and no trigger

**Comment by Ryanfawkez** [comment]
Cannot be fixed yet as ToK unlock by item is unsupported.

**Comment by Lheana** [comment]
Maybe fixable now thanks to a workaround ? :)
