### ISSUE TITLE
Mushroom misplaced - Inevitable City

### ISSUE THREAD

**Issue by benitoben20** [WarEmu/WarBugs#4137]
Hello,

On the left side of the door to enter the Citadel in IC, there is a mushroom floating. I supposed the mushroom goes with the "mushroom addict" room in the Citadel. 

Thank you,

![isas_016](https://cloud.githubusercontent.com/assets/16641170/12696497/6dee48a4-c73a-11e5-87cd-264c7653caad.jpg)

**Comment by Torquemadra** [comment]
fixed next patch
