### ISSUE TITLE
Book of binding , bug

### ISSUE THREAD

**Issue by Magteridon** [WarEmu/WarBugs#4138]
when I use the book teleport, teleporting me this zone 0 in the air, after disconnect and reconnect AC onnect I keep appearing in zone 0
![magteridon_003](https://cloud.githubusercontent.com/assets/16975012/12696524/5377a762-c76d-11e5-8870-c4fb6e1dfae2.jpg)

**Comment by JamGrif** [comment]
just do /stuck twice

**Comment by Evildoor** [comment]
JamGrif is correct. Known bug, closing.
