### ISSUE TITLE
Riding Wyvern - Inevitable City

### ISSUE THREAD

**Issue by benitoben20** [WarEmu/WarBugs#4139]
Hello, there is a riding wyvern floating next to the expedition balloon. Not sure if he's supposed to be there...

Thank you,

![isas_015](https://cloud.githubusercontent.com/assets/16641170/12696522/f32978f4-c73a-11e5-9a73-70d9f997896f.jpg)

**Comment by DanaBloodkiss** [comment]
It's supposed to be there. Just the wrong animation but that's a general problem.
