### ISSUE TITLE
[Quest] Zone: Norsca, Quest: Pillaging

### ISSUE THREAD

**Issue by Blorke** [WarEmu/WarBugs#414]
You have to secure two chests.
Problem: you can't interact with the chest, when right-clicking on it.

**Comment by Evildoor** [comment]
Works now.

**Comment by Lordbufu** [comment]
This bug has now returned, below are the screenshot for it.
They look like there in the shade now, i think there constantly in the already used state or something along those lines.

Sadly the screenshot doesnt show the cursor, but im hovering over it to show there is not interaction option.

![Jestertheteste_000](https://user-images.githubusercontent.com/19768243/54936361-9e9bbe00-4f22-11e9-83b4-68a60751e169.jpg)
![Jestertheteste_001](https://user-images.githubusercontent.com/19768243/54936372-a2c7db80-4f22-11e9-80c0-59098afbb80f.jpg)
