### ISSUE TITLE
Brigand's Bigloppa low DPS

### ISSUE THREAD

**Issue by laattori** [WarEmu/WarBugs#4140]
It seems like other Brigand 2-handers have about 68 dps, but Bigloppa only 65.9 dps. Is this intended or an oversight?

![bigloppa](https://cloud.githubusercontent.com/assets/15817706/12696542/066a0560-c776-11e5-8616-dd00fad6bcf5.jpg)
![deathaxe](https://cloud.githubusercontent.com/assets/15817706/12696546/0d29447e-c776-11e5-90a1-6f06c8425418.jpg)
![glaive](https://cloud.githubusercontent.com/assets/15817706/12696548/10c94e12-c776-11e5-97d8-c8410ff9f708.jpg)

**Comment by Ryanfawkez** [comment]
I'll streamline all of the brigand's 2hander weapons to have 68.0 DPS and a speed of 3.6.

**Comment by laattori** [comment]
Much obliged.
