### ISSUE TITLE
Arledge Thorn - Inevitable City

### ISSUE THREAD

**Issue by benitoben20** [WarEmu/WarBugs#4141]
Hello,

I've killed Arledge Thorn in IC, but the book of binding count him as a snotling.
I've included a picture of him + book and a picture of myself on the map.

![isas_013](https://cloud.githubusercontent.com/assets/16641170/12696567/f63a52a6-c73b-11e5-908a-fe25b1f0adf8.jpg)

![isas_014](https://cloud.githubusercontent.com/assets/16641170/12696569/f8b131e4-c73b-11e5-8e44-b5a03b2e0fc3.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
