### ISSUE TITLE
Movement at mach 8

### ISSUE THREAD

**Issue by Luftwaffle12** [WarEmu/WarBugs#4144]
Moving my character around makes me go into mach 8 and fly across the screen and eventually I ended up in the basement of IC by falling through the floor. The only thing I did that was new was use my new ability "Rending Blade" or summoning my Warlord's Fell Hound. My run animation is very fast as well looks like a little gerbil running.

**Comment by Evildoor** [comment]
What is "mach 8"?

**Comment by Evildoor** [comment]
No response, closing.

**Comment by Luftwaffle12** [comment]
I meaant just like really fast like speed of sound mach 1
