### ISSUE TITLE
Duel Bugs

### ISSUE THREAD

**Issue by sullemunk** [WarEmu/WarBugs#4145]
While making my Duel addon i came across some Buggs:

While an Duel has been issued and accepted it can't be /duelsurrendered or canceld, it hold both players flagged for duel untill someone loses

An Duel that is pending can't be canceled with /duelcancel, the one challanged must accept or decline to cleare the duel state (and even if canceled the once challanged can use /duelaccept after and still get into duel state)

/duelsurrender doesn't seem to work proppely

/duel <name> always duels the Targeted Player, never the <name>, so you can type annything as <name> as long as you have someone trageted

**Comment by Luth-RoR** [comment]
These kind of bugs will likely never be fixed as this is an unsupported feature that never existed on the mythic servers. Furthermore there could be client restrictions that can't be passed atm.
