### ISSUE TITLE
wp m3 Divine Protection 

### ISSUE THREAD

**Issue by omegachief** [WarEmu/WarBugs#4150]
Warrior Priest morale 3 show buf but during 10 sec duration it dont absorb  any dmg taken by player and party.

**Comment by Torquemadra** [comment]
Working for me

![855](https://cloud.githubusercontent.com/assets/16200780/12700524/0fa6dccc-c7b5-11e5-97a4-9dd3cfad72d1.png)

**Comment by omegachief** [comment]
Can you test it in rvr environment ?  I havent test it in pve but good it works there.

**Comment by omegachief** [comment]
I think i missed small part of tooltip of this skill . Dmg that i was taking was magical, so thats why absorb didnt work  becuse it absorb only melee dmg. Thanks for repply.
