### ISSUE TITLE
[Monster] Lundr Bruor Wrong Appearance

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#4151]
Lundr Bruor has the appearance of a nurgle cultist, it should have the appearance of a dryad. It is part of the quest "Down by the Banks" which is just outside the Empire Chapter 4 camp in Norsca. The quest otherwise is functional. See Issue #270 for the correct appearance

**Comment by Styrkarr** [comment]
Fixed in next patch.
