### ISSUE TITLE
broken count on killing squigs

### ISSUE THREAD

**Issue by jpnrd** [WarEmu/WarBugs#4153]
Hi! 

As said in tittle.
![patanouk_007](https://cloud.githubusercontent.com/assets/16733126/12702186/1290f76c-c821-11e5-9cd9-c5806f6c1eb7.jpg)

2 or 3 days after the ToK re released ( which made me start the squig cloak achievment) the count of my kills were back to 0. I took a few minutes to notice, that's why I'm at 200 ..
since i've already reached the 10k squiggs I wondered if it could be possible to set the count at right numbers back? i'm not far after, like 2k.

Thank you already :)

**Comment by MKorin** [comment]
I lost ~7k :(((

**Comment by jpnrd** [comment]
A friend  kept the killing on but i stopped :p so sad hum?
He hopes the missin count is still hidden somewhere and adds to the new one but my scepticism made my stop ^^

**Comment by Ryanfawkez** [comment]
Sorry, the ToK killcount was completely reset, and you won't get previously recorded killcounts back since we cannot validate whether or not you truly had the killcount before the reset.

**Comment by Evildoor** [comment]
Closing per Ryanfawkez.

**Comment by jpnrd** [comment]
Not even 10 k? that's why i put a screenshot with :)
