### ISSUE TITLE
<RoR Launcher> Server Notice : Mail Expiry

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4154]
![123456](https://cloud.githubusercontent.com/assets/16864486/12702406/e653ddf8-c830-11e5-98cc-f5799b07d506.png)
Removed the items from my alts mailbox...but the message still here everytime i open the Launcher instead of showing Latest news/Changelog as it used to do 1 week ago.

**Comment by Evildoor** [comment]
This notice seems like current Latest News to me.

**Comment by Soulwhisper** [comment]
What is the expiry period? I told you that i removed the items from the mailbox last week but the message is still here...
