### ISSUE TITLE
Lost all Items/ I'm dead

### ISSUE THREAD

**Issue by Zaccar20** [WarEmu/WarBugs#4155]
Hello since the Server restart today i lost all my Items & the game say i'm dead (Have no Live/AP)
Also no Monster can attack me.
Just the gold & professions stay. On loadingscreen i have all my eqipment still.

![war 2016-01-31 15-28-35-594](https://cloud.githubusercontent.com/assets/12786673/12702699/f566542a-c82f-11e5-8c77-2751eb49d50e.jpg)
![war 2016-01-31 15-29-22-805](https://cloud.githubusercontent.com/assets/12786673/12702702/fae3a614-c82f-11e5-9b09-46ef00d7822c.jpg)

**Comment by Milkyn** [comment]
Same issue over here with my Character "Schattenmilch"

**Comment by ozarmidrashim** [comment]
Bug in alliance handler.

**Comment by tksci** [comment]
Similar issue, but i have my items. I can get resurrected but when I logout and back in, I'm still dead. Character "Keisra".

**Comment by tksci** [comment]
still having this issue with my character, referred to a GM about help, they said they were not able to, any suggestions?
