### ISSUE TITLE
No Quarter Tactic not always working

### ISSUE THREAD

**Issue by foxbeep** [WarEmu/WarBugs#4156]
Slotted No Quarter, Eagle eye sometimes still takes 2 seconds to cast
Screenshots provided show no quarter in bottom right, where mouse target on my tactics bar and >1s cast time remaining
No debuffs

Still costs 60 AP
![laerith_073](https://cloud.githubusercontent.com/assets/15528466/12703049/76226e00-c7fe-11e5-8fd4-cdb30f71fa7a.jpg)
![laerith_074](https://cloud.githubusercontent.com/assets/15528466/12703050/7624c6f0-c7fe-11e5-874f-a017cfa3f582.jpg)

**Comment by foxbeep** [comment]
Any news on a fix? I'm still encountering this problem regularly

**Comment by Evildoor** [comment]
Read the rules of the bugtracker.

**Comment by foxbeep** [comment]
Sorry
Updated information

This bug seems to only occur if chaining Eagle Eye
It's never happened on my first Eagle Eye but if I chain them together (Using the ability right before the previous Eagle eye fires to "queue" up the ability) it starts to occur
This may be a latency related issue too so if anyone in Europe would be able to test it might answer a question or two.

**Comment by grunbag** [comment]
can't reproduce
