### ISSUE TITLE
Engineer mobs in Ekrund are flight masters

### ISSUE THREAD

**Issue by foxbeep** [WarEmu/WarBugs#4159]
![hrandi_010](https://cloud.githubusercontent.com/assets/15528466/12703484/dc0b7c7e-c809-11e5-8f83-41a31c0a43ce.jpg)
![hrandi_011](https://cloud.githubusercontent.com/assets/15528466/12703485/dc13ce7e-c809-11e5-8ce9-9d26617ba801.jpg)

these mobs work as flight masters

**Comment by Evildoor** [comment]
#642
