### ISSUE TITLE
Ignore option does not work for Guild chat

### ISSUE THREAD

**Issue by Scrilian** [WarEmu/WarBugs#4161]
Somehow I'm still able to see the dumbass chat, even thou I ignored him this morning. I think its the same for Alliance and Warband chat too.
http://i.imgur.com/qtZ4c8P.jpg

**Comment by ozarmidrashim** [comment]
I don't agree with changing this. Party, Warband and Guild are the only chats in which Ignore is now set not to work, and this is because participation in these chats is governed by player choice in association.

**Comment by Luth-RoR** [comment]
Working as intended.
