### ISSUE TITLE
Fierceness can cause massive lag spikes

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#4165]
The Slayer Fierceness Buff can cause massive lag spikes when hitting many targets before the stacking cap is reached. This is especially noticeable when ID is being used and is hitting many targets in one timestamp. Even worse with multiple applications of ID.

WSCT looks like this:
![Fierceness](http://img9.uploadhouse.com/fileuploads/22041/2204133935006d1b39882cc2dcd063e4adaaf85d.png)
Just imagine 30 more Fierceness Buffs scrolling through the screen...

**Comment by ozarmidrashim** [comment]
ICD now 1s.
