### ISSUE TITLE
Trophy Item: Workbelt Pouch Incorrect Placement

### ISSUE THREAD

**Issue by porkstar** [WarEmu/WarBugs#4167]
The pouch attaches to shoulder instead of hip.
![hamcat_137](https://cloud.githubusercontent.com/assets/16991402/12705121/aa716e2c-c830-11e5-9374-5bd9c6eaae9d.jpg)

**Comment by Pumatouch** [comment]
Cannot confirm this. Stays on my belt.

**Comment by porkstar** [comment]
I cannot get it to place anywhere except on the edge of my shoulder. Tried all combos of trophy placement and they all go on my shoulder.

**Comment by Evildoor** [comment]
No confirmation, closing.
