### ISSUE TITLE
[Skill] Magus Dissolving Mist tics 2 times

### ISSUE THREAD

**Issue by Scrilian** [WarEmu/WarBugs#4171]
I've noticed that quite a few times Magus Mist tics two times a second.
http://i.imgur.com/JJ8QgS6.jpg
I know, I forgot to turn on the timestamp :C

**Comment by Scrilian** [comment]
Another example of it
![valtor_135](https://cloud.githubusercontent.com/assets/16498708/12891197/eb776eae-ce97-11e5-9189-dc50b9e4d39d.jpg)

**Comment by Scrilian** [comment]
Any update on the issue? I think this maybe caused by some bugs vertical movement.
![valtor_251](https://cloud.githubusercontent.com/assets/16498708/13898783/0adda3f6-edee-11e5-8847-82c739be06ec.jpg)

**Comment by grunbag** [comment]
Fixed already
