### ISSUE TITLE
[Quest] Revelation

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#4172]
In Chaos Chapter 14 quest, Revelation, there is a part where you have to steal an elven banner and plant it into a dead dwarf foreman. You are then supposed to talk with a dwarf NPC, Dunn Ironhelm. It is possible to find him, but he is neutral and you cannot talk to him to turn in the quest. I have tried killing him to see if he spawned a friendly mob, but it didn't work, also to see if I could talk to his corpse.

**Comment by Torquemadra** [comment]
Fixed next patch
