### ISSUE TITLE
Maraduer Career Tactic Deadly Clutch - 2nd Part of Passive not working

### ISSUE THREAD

**Issue by Kringe** [WarEmu/WarBugs#4174]
Deadly Clutch "Tainted Claw will now reduce ALL healing used on your target, you will receive 50% of the heals on your target while the debuff is on does not appear to be working correctly.

We are not receiving 50% of the heals (tested this on a tank with debuff on and healing him to full while at half health.

**Comment by ozarmidrashim** [comment]
![iambalanced_000](https://cloud.githubusercontent.com/assets/6764164/12719614/23f33ba0-c8ee-11e5-9d25-5f7458e88a84.jpg)

**Comment by taccr** [comment]
Can you confirm that the healing debuff is actually 50% and not 25%?
The tooltip of DC always states 25%.

**Comment by ozarmidrashim** [comment]
It's 50%. It turns out this buff's tooltip has 4 different lines, with the value hardcoded, for no good reason whatsoever.

*grumbles off to add yet another "// Thanks, Mythic"*
