### ISSUE TITLE
Wrong item display for SH

### ISSUE THREAD

**Issue by hogo2hogo** [WarEmu/WarBugs#4177]
As also seen by the picture, this item listed (and is ) as boots, has the visual of a belt.
Minor
![wrong display](https://cloud.githubusercontent.com/assets/16440840/12712679/c9681e00-c8d2-11e5-8f5a-00bc3eb3596b.jpg)
 bug but still a bug :)

**Comment by Torquemadra** [comment]
fixed next patch
