### ISSUE TITLE
Wrong stats for BG emblem weapon

### ISSUE THREAD

**Issue by hogo2hogo** [WarEmu/WarBugs#4178]
Another probably error bug that i found the other but didnt have time to check if it was fixed in recent patches. I think the healing stats are close to useless for bg. Sorry for double posting if it has already been solved.
![emblem weapon bg](https://cloud.githubusercontent.com/assets/16440840/12712723/05c9f9b8-c8d3-11e5-9074-32e01926f22c.jpg)

**Comment by Torquemadra** [comment]
Pretty good for a dok though....

**Comment by Evildoor** [comment]
Not a bug. It's a sword for a DoK, which is shown to you because it has no class restriction.
