### ISSUE TITLE
Marsh Choppa Achievement Unlock

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4179]
Interact with a choppa is in the Marshfang Spider cave in the Marshes of Madness area.
Searched the whole cave and found no Choppa body. Only thing i found is a Marsh Axe which is not interactable.
![cave](https://cloud.githubusercontent.com/assets/16864486/12718944/ae255126-c8fa-11e5-80cf-c06dd262acfb.jpg)
Source : http://warhammeronline.wikia.com/wiki/Marsh_Choppa
Need confirmation though.

**Comment by Torquemadra** [comment]
Fixed next patch
