### ISSUE TITLE
Character Selection

### ISSUE THREAD

**Issue by Blubberino** [WarEmu/WarBugs#4181]
Helmets are displayed in the character selection even though they are hidden in the real game.

Edit: Yes same goes to all appearance changes but since you only stay on character screen for 10 seconds or less it's not really something anywhere near the list of things that needs to be looked at first^^^
But still thanks for taking a look at really nice to see that you take a look at even things like this.

**Comment by Evildoor** [comment]
1) Same with cloak, i presume.
2) Items are also showing their real models, not applied ones. This overrides the next issue.
3) Item models are saved client-side - for example, if you wear an item and then it's model is changed in a patch, you'll still see the old one in character selection.
However, i doubt that we can fix this.
