### ISSUE TITLE
Skull of Ograrand

### ISSUE THREAD

**Issue by Blubberino** [WarEmu/WarBugs#4182]
In the Inevitable City (in the Library) there is a fireplace currently it is open and you can't click the skull but before it gave you an quest which gave you then this funny Skull.

http://warhammeronline.wikia.com/wiki/Skull_of_Ograrand

https://www.youtube.com/watch?v=gpNJXACxmL0 (Showes how you obtained it on live)

**Comment by Torquemadra** [comment]
lvl 40 quest, also requires significant work regarding interactables. I would suggest not fixable at this time.
