### ISSUE TITLE
Taunt and Challenge

### ISSUE THREAD

**Issue by zibiman** [WarEmu/WarBugs#4184]
Ability Challenge dont force Mobs to atk me it was working the last week

**Comment by Evildoor** [comment]
#2010?

**Comment by zibiman** [comment]
also taunt dont force mobs but like i say last week it was working that mobs atk you ,i dont mean infight i mean if i challenge 6 mobs that are not infight with ability they shold atk me that worked before now its not working

**Comment by Torquemadra** [comment]
Aggro mechanics WERE (partly) functioning before yesterdays patch, now they are not, neither taunt not challenge will force an npc to attack you where as they did before Changelog 31.01.2016.

Suggest removing BO from header, adding taunt and its effecting all tanks.

**Comment by zibiman** [comment]
i found out that there still some aggro mechanics see video

https://youtu.be/6y5phvJOeXE

**Comment by Evildoor** [comment]
Hotfix 17/09
[NPC]
- Fixed an issue preventing Taunt effects from causing initial aggro.
