### ISSUE TITLE
[Item] Hatchet of Vengeance

### ISSUE THREAD

**Issue by Mikaill** [WarEmu/WarBugs#4185]
Great Axe (two-handed weapon) with appearance and speed/DPS of one-handed.
Can be purchased from Bountyman Lipschultz in Nordland.
![war 2016-02-01 19-12-59-50](https://cloud.githubusercontent.com/assets/17011135/12726602/cffb5124-c918-11e5-9d9e-4b9269b403a9.jpg)

**Comment by Torquemadra** [comment]
fixed next patch
