### ISSUE TITLE
Daemonic Infestation

### ISSUE THREAD

**Issue by Blubberino** [WarEmu/WarBugs#4189]
There is a problem with using this skill while moving. If you use it while moving and try to cast it further away then maxrange it will cast, go on full cd and don't summon the infestation. 
However it works properly if you don't move you can cast it further away then maxrange and it will summon the infestation on maxrange. 

![di_001](https://cloud.githubusercontent.com/assets/16993024/12729700/4b146148-c928-11e5-8898-89cb7a21af72.jpg)
![di_002](https://cloud.githubusercontent.com/assets/16993024/12729701/4b14a338-c928-11e5-9df2-6ce3c5a37ca7.jpg)
![di_003](https://cloud.githubusercontent.com/assets/16993024/12729703/4b1a20ba-c928-11e5-9c40-1c439a5e507a.jpg)
![di_004](https://cloud.githubusercontent.com/assets/16993024/12729702/4b176e1a-c928-11e5-84d8-3f8c426f45c3.jpg)

**Comment by ozarmidrashim** [comment]
#1118
