### ISSUE TITLE
[NPC] "Molora the Seeker" has an attackable raven by her side.

### ISSUE THREAD

**Issue by Halobravo** [WarEmu/WarBugs#419]
Near the quest giver is a little raven companion.  You can attack it and it will run around but it doesn't take any damage.  My guess is that it should be a friendly NPC, or perhaps that it is just misplaced?

![guanyu_001](https://cloud.githubusercontent.com/assets/9036262/4527691/2484629e-4d69-11e4-932e-c718389c7354.jpg)

![guanyu_002](https://cloud.githubusercontent.com/assets/9036262/4527715/551512d2-4d69-11e4-94d2-6328a69e3d8f.jpg)

**Comment by Ryanfawkez** [comment]
These ravens aren't attackable on the dev server at this moment - considered fixed.
