### ISSUE TITLE
Tactic slots once more

### ISSUE THREAD

**Issue by duskiy5** [WarEmu/WarBugs#4190]
figured it out it works the same way as the bug that made you keep class abilities after relogging.

so i suppose the tactics from both classes stacked or something and even relogging did not fixed it this time untill i force crashed the game.

![duskiy_007](https://cloud.githubusercontent.com/assets/16807549/12731918/740b326a-c933-11e5-9153-1b5cc6b2b496.jpg)
![duskiy_008](https://cloud.githubusercontent.com/assets/16807549/12731921/761406f4-c933-11e5-98e6-560178406cd0.jpg)
![duskiy_009](https://cloud.githubusercontent.com/assets/16807549/12731926/78ad29ae-c933-11e5-9fae-843c7b4e5f3a.jpg)
![duskiy_010](https://cloud.githubusercontent.com/assets/16807549/12731932/7ccf8f0e-c933-11e5-8341-4151a10352b5.jpg)
![duskiy_011](https://cloud.githubusercontent.com/assets/16807549/12731938/800ab9dc-c933-11e5-951b-b365c7f8c25f.jpg)

**Comment by Evildoor** [comment]
Azarael already answered you in #3867 - this is packet corruption, which is known problem.
