### ISSUE TITLE
Renown Abilities

### ISSUE THREAD

**Issue by Gotrek129** [WarEmu/WarBugs#4192]
When Ill learn any renown abilities there are dissapearing. Unlearning ur somethink.

**Comment by Torquemadra** [comment]
Its a display issue only, your abilities remain but it gets messy when training new ones. WHen you want to spend points, just reset them, close the window then open it and purchase them again.

If you suspect you are actually losing stats (which you are not) target self and type .getstats

**Comment by Evildoor** [comment]
#1486
