### ISSUE TITLE
Hight Pass quest bug: Wherever They Are Found

### ISSUE THREAD

**Issue by Anethka** [WarEmu/WarBugs#4193]
![gethel_000](https://cloud.githubusercontent.com/assets/17015247/12734482/14be9d5c-c941-11e5-9b6e-fadb2286484b.jpg)

**Comment by Torquemadra** [comment]
Mount Gunbad isnt open yet

**Comment by Anethka** [comment]
i know but i did as the message says, report to a GM so sorry if it wasn't the correct choice ^^

**Comment by Evildoor** [comment]
#4169
