### ISSUE TITLE
Slow projectiles

### ISSUE THREAD

**Issue by erkislev** [WarEmu/WarBugs#4198]
[Excuse me if the issue was previously addressed — didn't find anything like that]

Some projectiles (e.g. for Bright Wizard — Fireball, Mage Bolt, Fireblast) start flying very slowly after a number of times of repeat. The damage is done to the target in proper timing, but the animation of the projectile is slow. Especially this happens on sieging the doors, as you have time to repeat the same abilities time and time again. But sometimes it happens out of nowhere — the first Fireball you send may be slowly animated already.

Screenshot provided — you can see my THREE fireballs at once.
![slow fireballs](https://cloud.githubusercontent.com/assets/16850861/12745387/0717c17e-c9aa-11e5-8b07-32cb7cdf5cc2.jpg)

**Comment by Evildoor** [comment]
View first unread post Changelog 19th May, 2016
[General]
- Fixed projectile travel times.
