### ISSUE TITLE
[Quest] "Pile it Up!"  You can "Gorkifi" the statue before you pick up the Handful o' Mud

### ISSUE THREAD

**Issue by Halobravo** [WarEmu/WarBugs#420]
For this quest the idea is to desecrate the Dwarven statues with mud.  However you can cover them with mud before the mud is picked up.  Also when you do cover them, it use to put mud textures around the statues for a short time to show that you did the task, this doesn't currently happen.

Another thing to note is that when you click on the mud and the statue it instantly completes the quest objective.  I believe in the original game there was a short "cast time" where your character knelt down and collected the mud. And for the statue I believe your character did a throwing animation at which point some mud covered the statue for a short time.

![guanyu_003](https://cloud.githubusercontent.com/assets/9036262/4527995/8f3a3e68-4d6b-11e4-90fe-81a01f71b5ce.jpg)

![guanyu_004](https://cloud.githubusercontent.com/assets/9036262/4527997/908e5d94-4d6b-11e4-8f8b-c3c12addbc3f.jpg)

**Comment by Natherul** [comment]
this is working as intended, I dont know when the fix was implemented.
