### ISSUE TITLE
Wrong Bolster in T1 - Visual Bug

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4200]
![toufekiaaaa_013](https://cloud.githubusercontent.com/assets/16864486/12746674/93b33214-c9a8-11e5-96d5-6df5c1d881b8.jpg)
![toufekiaaaa_014](https://cloud.githubusercontent.com/assets/16864486/12746675/93ddb7aa-c9a8-11e5-88b9-d0f1db14dfdd.jpg)
Not to 15 but to 11

**Comment by ozarmidrashim** [comment]
Hardcoded and cannot be fixed.
