### ISSUE TITLE
Squig herder (Squig Armor) issue with converting critical chance

### ISSUE THREAD

**Issue by murmelon** [WarEmu/WarBugs#4201]
Isn't converting critical chance
![gibbon_017](https://cloud.githubusercontent.com/assets/12655727/12746700/b1274cc2-c9a8-11e5-8ac5-ef43705d54bf.jpg)

Also visual bug. Adding armor from gas squig
![gibbon_016](https://cloud.githubusercontent.com/assets/12655727/12746739/e6a80008-c9a8-11e5-8e9c-2c0f3e87af77.jpg)

Also. When pet suffers from enemy damage, command "Heel" and "Stay" is not working correct, pet tries to attak enemy always.

**Comment by Evildoor** [comment]
Next time - one report per problem.
Armor from gas squig - known issue which applies to many effects which change armor value (#2146).
