### ISSUE TITLE
Sorc devastator 5piece bonus "Quickening" problem

### ISSUE THREAD

**Issue by TaeBal** [WarEmu/WarBugs#4203]
Sorc devastator 5 piece bonus is "Quickening" 

Quickening is :
Quickening - On Being Hit: 10% chance to reduce build times by half a second for 10 seconds.

But in game I was test that. when I get quickening buff from my 5 piece devastator set.
That buff not making my build time for half. That's "quickening" make reduce build time just 0.5 sec 

I mean 
Correct quickening work : 3 sec magic cast time -> 1.5sec magic cast time 
Wrong quickening work atm : 3 sec magic cast time -> 2.5sec magic cast time

Is this bug or am i missed something? i dont know cuz im noob thats why im just report here :)

Thanks for read and sorry for my bad english. hope you guys will understand what Im said

**Comment by Evildoor** [comment]
"10% chance to reduce build times by HALF A SECOND". Not "by HALF". Half a second = 0.5 sec.

**Comment by ozarmidrashim** [comment]
Nothing more to say about this.

**Comment by TaeBal** [comment]
Sorry my bad
