### ISSUE TITLE
the t1 order siege wepons is bug

### ISSUE THREAD

**Issue by lijebin** [WarEmu/WarBugs#4205]
i found t1 order siege wepons is bug order can't use any near enemy area only one that is can't kill enemy and destro is fine plesae fix it soon

**Comment by lijebin** [comment]
screenshot 
![tarelther_000](https://cloud.githubusercontent.com/assets/17027595/12752816/38449588-c9ff-11e5-9c1f-1214811aab6a.jpg)

**Comment by lijebin** [comment]
this is the only can work
![Uploading Tarelther_002.jpg…]()

**Comment by lijebin** [comment]
this is only fine 
![Uploading Tarelther_002.jpg…]()

**Comment by lijebin** [comment]
will it fix in next patch to

**Comment by lijebin** [comment]
i hope order and destro t1 siege wepons can be work

**Comment by Evildoor** [comment]
#4112
