### ISSUE TITLE
Greatweapon

### ISSUE THREAD

**Issue by Kouba85** [WarEmu/WarBugs#4206]
Hi second tallisman slot on greatweapon still not working.

**Comment by Evildoor** [comment]
What do you mean? Especially by "still"?

**Comment by Kouba85** [comment]
Sorry for my bad english but i saw on ror home page that this problem is fixed but i can just use one tallisman slot on greatweapon and the second one is not working.

**Comment by Evildoor** [comment]
"i saw on ror home page that this problem is fixed" - where?

**Comment by Kouba85** [comment]
![tali](https://cloud.githubusercontent.com/assets/15944509/12785083/e88126a6-ca8a-11e5-9dbe-2376a29f7957.jpg)

**Comment by Kouba85** [comment]
Changelog 17.01.2016

**Comment by Evildoor** [comment]
So, first point of #2480 is broken again?

**Comment by Kouba85** [comment]
yes

**Comment by Evildoor** [comment]
Closing then.
