### ISSUE TITLE
T3 inf WE cloak changed to BG

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#4207]
![zireael_005](https://cloud.githubusercontent.com/assets/13823154/12754107/436b1246-c9ca-11e5-9dbd-21e81712045a.jpg)

**Comment by Styrkarr** [comment]
The WE cloak is "Ghrond's Fright Shawl". "Greatcloak" is for BG. It was a bug which was fixed with the last patch.

Maybe ask a GM to change this item with the real WE one.

**Comment by MKorin** [comment]
but there is reduced chance to be dodged in Ghrond's Fright Shawl... for WE?

**Comment by Styrkarr** [comment]
I think it's an old stat (as engi/SH item with strength instead of balistic skill).

I changed it  to %parry_strikethrough.

**Comment by MKorin** [comment]
cool, thx

**Comment by Evildoor** [comment]
Not a bug, but collateral damage caused by bug fixing. Closing.

**Comment by mursie** [comment]
I notice you are closing these and saying it is collateral dmg.  CAn you elaborate on this?  Does this mean that it will not be fixed?  That if you have a ring that has now changed career you are SoL?  Just curious what your statement means

**Comment by Evildoor** [comment]
> Maybe ask a GM to change this item with the real WE one.
