### ISSUE TITLE
Squigtreiba Pet Kartenwechsel

### ISSUE THREAD

**Issue by Skellort** [WarEmu/WarBugs#4209]
Hallo Team

Beim Squigtreiba ist mir aufegfallen, dass bei den RVR Karten wo es einen Kartenwechsel gibt wie in (Averlorn/Saphery , Nordpass/Talabec) das Pet verschwindet aber nur wenn man sich im Kampf befindet. Bei normalen überqueren der Karte tritt das Problem nicht auf..
Falls das Problem schon bekannt ist sorry konnte aber nichts dazu finden.

danke im vorraus 
hoffe ihr könnt das beheben danke

mfg

**Comment by Evildoor** [comment]
Read point 9 of the bugtracker rules.
