### ISSUE TITLE
[NPC] "Skarzag" Is always mounted except for when you complete "Stunties is fer Smashin' "

### ISSUE THREAD

**Issue by Halobravo** [WarEmu/WarBugs#421]
This npc is always mounted until you finish the quest "Stunties is fer Smashin' "  Once you complete the quest and go back to him he is standing on the ground.  After you turn in he is mounted again.  Perhaps it's not a bug?  But it does look very strange.

https://www.youtube.com/watch?v=OR6DUjo7evA&feature=youtu.be

**Comment by Ryanfawkez** [comment]
This is no longer occurring on live nor dev. I assume it's fixed.
