### ISSUE TITLE
Chicken of Doom

### ISSUE THREAD

**Issue by Fiddlehero** [WarEmu/WarBugs#4211]
Hi, today, while in Nordland ORvR our warband encountered a level 19 zealot chicken. He often times absorbed damage, though I could get a point of damage into him every now and then. We eventually downed him because we focused on the chicken for a while. at one point we damaged him normally, but that window didn't last very long.
![thyrsis_000](https://cloud.githubusercontent.com/assets/16520814/12760158/eaf7ed44-c999-11e5-9c8b-3975267edcd5.jpg)
![thyrsis_002](https://cloud.githubusercontent.com/assets/16520814/12760165/f1ff0c76-c999-11e5-98f3-ba63dfecfa35.jpg)

**Comment by Renork** [comment]
When you say "Chicken of Doom", do you mean to say the chicken was one shooting you and/or doing any significant damage to you? Or are you just reporting that it took a while to kill a chickened player?

**Comment by Fiddlehero** [comment]
Someone claimed that it was hitting for 140 damage. I was taking damage too, though I'm not sure if it was from the chicken, or from a ranged DPS in their warcamp.

**Comment by Bluezeon** [comment]
*14 Damage.

**Comment by Torquemadra** [comment]
Cant see the absorb tactic accounting for the level of mitigation once it was down

**Comment by Evildoor** [comment]
Seems somewhat similar to #1574.

**Comment by Kaelang** [comment]
Haven't seen anything like this in the more recent versions of RoR - on top of this, this report doesn't provide any information to look to replicate such issue.

If the issue persists, and you notice in-game, please re-open this report.
