### ISSUE TITLE
Guild Calendar Event Sign Ups

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4214]
As a Guild Leader cant accept other members sign ups for events.
![toufekiaaaa_018](https://cloud.githubusercontent.com/assets/16864486/12762771/8278cddc-c9f9-11e5-8748-db2c297c9335.jpg)
Whichever i try to accept it only affects me.Example : Im trying to accept Paterellas but when i R-Click on him and press accept the acceptance goes on me.Same for other members.Tried deleting the event and recreating it but doesnt work.

**Comment by nalgol** [comment]
should work next patch
