### ISSUE TITLE
Attack from behind

### ISSUE THREAD

**Issue by saupreusse** [WarEmu/WarBugs#4215]
I refer to #2013 , #2004 , #2206 and #2614.
I just made a quick video to this problem wich may help fixing  it.
In the video you can see clearly that this issue is not caused by lag in this specific situation.
(lag may be a cause of it, too - but not in my video)
I was pinging the server all the time while I was recording and my ping was just fine (~ 42ms) and I didnt loose any packages.
Also, in my video the target and myself are standig still , so there is no movement which could cause this issue.
My conclusion: if it isnt lag or movement - it must be something else causing this bug.
I hope this will help fixing it, but if it doesnt help at all I am sorry for posting it (again).

https://www.youtube.com/watch?v=pS3glpVSThg&feature=youtu.be

**Comment by noisestorm** [comment]
That is something i already mentioned towards Aza. The serverside angle for skills that require "Facing away" is too small at the moment. Client csays it is something like 175~170°, serverwide it is set to 160° i believe.

**Comment by saupreusse** [comment]
Ahh okay :) maybe after this is fixed our poor WH/WE friends can play in peace again
