### ISSUE TITLE
Greenskin Tier 3 Influence 1 reward Chosen.

### ISSUE THREAD

**Issue by Lokenoth** [WarEmu/WarBugs#4216]
![lokenoth_002](https://cloud.githubusercontent.com/assets/17035321/12767579/ecab2aee-ca01-11e5-900a-526163f95a38.jpg)
The Ring I was wearing and received from the Greenskin Tier 3 Influence reward become a Blackguard specific ring. Any help?

**Comment by Styrkarr** [comment]
The Chosen ring is "Thickmuck Chaos seal". "Dark Band" is for BG. It was a bug which was fixed with the last patch.

Ask a GM to change this item with the real Chosen one.

**Comment by Evildoor** [comment]
Not a bug, but collateral damage caused by bug fixing. Closing.
