### ISSUE TITLE
Gold from nowhere ahd death when i'm alive

### ISSUE THREAD

**Issue by Recaron** [WarEmu/WarBugs#4217]
![malatiel_000](https://cloud.githubusercontent.com/assets/17049721/12789107/8b865fdc-caf0-11e5-8fb3-55543abc4ad9.jpg)
![malatiel_001](https://cloud.githubusercontent.com/assets/17049721/12789109/8d2c6c5a-caf0-11e5-876a-5b8e72938a22.jpg)
I receive gold when i create a character. I don't now why. And now i'm "dead" but i'm alive, and have 220 lvl. all info in screenshots.

**Comment by Evildoor** [comment]
#1810
