### ISSUE TITLE
Ib and BG Mastery

### ISSUE THREAD

**Issue by Weatherwaz** [WarEmu/WarBugs#4219]
ther is eather a bug in the black guard : path:  PoA taktick: Soul killer  make it as same as the IB but thet you can reaplay it 3 time Is Silli OP so both side need it or take down to just 50% 
As it is now it is 150% heal debuff . 
or a bug thet the Iron braker did not get the same: In pob ther is a taktik you can get Punishing knock
ther you dont get It can be reaplayd 3 time so you get a - 150% heal debuff

Sorry fore the bad Eng :)

**Comment by Evildoor** [comment]
If this report was made just by reading tooltips then it's wrong: Soul Killer applies 50% heal debuff regardless of number of stacks.

**Comment by Weatherwaz** [comment]
No it whas not to reading the tole tip it whas of testing. om me Wp Babb(healer) and aye did get 0 in heal can test it more if you whant

**Comment by Evildoor** [comment]
Screens with "proper healing - Mind Killer applied - 0 healing", please.

**Comment by Landaren** [comment]
Not, true. Tested it out, can provide a screenshot if needed.

**Comment by genisaurus** [comment]
Please do.

**Comment by Evildoor** [comment]
No proof, closing.
