### ISSUE TITLE
[Quest] "Two Can Play at Dat" the Bloody Sun Banner doesnt work

### ISSUE THREAD

**Issue by Halobravo** [WarEmu/WarBugs#422]
You need to click on the Blood Sun Banner to get the Tome of Knowledge entry "Bloody Sun Boyz" but you cannot interact with the flag.

![guanyu_005](https://cloud.githubusercontent.com/assets/9036262/4528948/69150dfa-4d73-11e4-85b2-2a893af8777d.jpg)

![guanyu_006](https://cloud.githubusercontent.com/assets/9036262/4528984/ba395c9a-4d73-11e4-9036-230d52a72a5e.jpg)

**Comment by Ryanfawkez** [comment]
Flag can be interacted with now on the dev server - considered fixed.
