### ISSUE TITLE
Influence rewards switched classes.

### ISSUE THREAD

**Issue by KeeperOfSecrets** [WarEmu/WarBugs#4220]
Some of the T3 Inf rewards have suddenly switched classes. Mainly these two:
http://i.imgur.com/T5P7OZK.jpg
These were both equipped on a witch elf until the patch about 3 days ago.

**Comment by Torquemadra** [comment]
This is a result of a wide reaching influence item fix, attempt to contact a GM on the forums to swap them for you.

**Comment by Evildoor** [comment]
Not a bug, but collateral damage caused by bug fixing. Closing.
