### ISSUE TITLE
Archmage high magic does not increase dot damage.

### ISSUE THREAD

**Issue by Londo001** [WarEmu/WarBugs#4221]
Damage over time abilities that indicate "Tranquility increases effectiveness." do not get benefit from "Tranquility" levels.

To reproduce: Cast lambent aura 5 times (increased tranquility to 5), then cast radiant gaze, each dot tick were not affected. On live, each dot tick damage for this dot would have been 25% higher.

![tranq](https://cloud.githubusercontent.com/assets/10520029/12797235/c3674750-ca77-11e5-9272-987287df5625.jpg)

**Comment by ozarmidrashim** [comment]
Specific to Radiant Gaze.
