### ISSUE TITLE
T3 RvR Influence Cloak Ghrond's Greatcloak

### ISSUE THREAD

**Issue by meleriex** [WarEmu/WarBugs#4223]
has had "Blackguard" affix added it to it for some reason.  I am a Witch Elf, I am unable to wear it now.

:(

character name = Cnote R32RR37 witch elf

**Comment by Styrkarr** [comment]
[#4207](https://github.com/WarEmu/WarBugs/issues/4207)

**Comment by meleriex** [comment]
so im out of a cloak or?

**Comment by Torquemadra** [comment]
pm a gm on the forums

**Comment by Evildoor** [comment]
Not a bug, but collateral damage caused by bug fixing. Closing.
