### ISSUE TITLE
Noble Bertram

### ISSUE THREAD

**Issue by MalakarSW** [WarEmu/WarBugs#4225]
I've noticed in two zones there are two of one named NPC.

First in Troll Country
![gottselig_003](https://cloud.githubusercontent.com/assets/16929056/12803997/03e6cdba-cabd-11e5-8ba1-955e3bb642d4.jpg)

Another in The Badlands (Same name but different face.)
![malathorn_009](https://cloud.githubusercontent.com/assets/16929056/12804010/166a985e-cabd-11e5-8e34-6fba62efa240.jpg)
![malathorn_010](https://cloud.githubusercontent.com/assets/16929056/12804017/26c1126e-cabd-11e5-82db-18c35d8063c8.jpg)

**Comment by Evildoor** [comment]
One report per problem.
Cartwright was already reported - #2761.

**Comment by Styrkarr** [comment]
Fixed in next patch (for Noble Bertram).
