### ISSUE TITLE
Premature hit on T4

### ISSUE THREAD

**Issue by GerrDooctor** [WarEmu/WarBugs#4227]
Excuse my bad English, I use Google translator.
After receiving the quest to Skaven dungeon I went to his execution.As a result of actions unknown to me there was no part of the walls that allowed me to go outside, and then I went to the side of the mountains are on the horizon.There I found the city walls of Altdorf and victorious NPC guarding the gates.As proof, I have attached a video that I started writing when I realized that something went wrong [https://youtu.be/0tdRXl9R4zo](url)

**Comment by Evildoor** [comment]
From rules of the bugtracker (http://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366):

9. Ensure you can use English to a respectable standard. 

Google Translate reports will be closed on sight.
