### ISSUE TITLE
BUG report

### ISSUE THREAD

**Issue by Nemrag** [WarEmu/WarBugs#4228]
Hi Github,

i play long Time closed,open Warhammer, and now im play here thx for Open this Server and the old Warhammer.

Bug Report t2 Sets
I Play 2 Chars t2 and farm me the Set from the Green Market the last Set Bonus from Black Orc and JDK DD not Work to get 1 Point in Skill Tree.
Its bad for the Farmers to get the complete Set and many Soldier Medals are useless.

The Class Balance and Skill Tree´s Suxx Order vs Destro
its not Normaly that the WL Jump with NO CD u cant Stop him no Stun, noc Slow doesnt Work.
AM rofl Class can do 3-4 vs 1 AM the Dots are too long Range and little CD .... 

Mfg Momo/Finaly/Gubbel

**Comment by ozarmidrashim** [comment]
Let's try that again, except following the format outlined here:

http://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
