### ISSUE TITLE
[Quest] "Sumfink in da Water" none of the barrels have stuntys in em

### ISSUE THREAD

**Issue by Halobravo** [WarEmu/WarBugs#423]
For this quest you need to click on the barrels to open them up and find some dirty stunties waiting for you!!  If i remember correctly a dwarf would pop out of the barrel and you would kill it.  However, none of the barrels had any stunties to kill!  :( sad day

Also the barrels wiggle around in a really creepy way... I don't like it.

https://www.youtube.com/watch?v=3lvjHhKtNis&feature=youtu.be

**Comment by Lheana** [comment]
Any info on the name of the dwarves?

**Comment by Lheana** [comment]
Dizzy Beardlings are already spawning when you click on these barrels.
I fixed the animation of the barrels.

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
