### ISSUE TITLE
Wrong Respawn Location - Troll Country

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4232]
![wrong respawn](https://cloud.githubusercontent.com/assets/16864486/12827546/ef9c50b0-cb88-11e5-93c5-fc2ef10aa42b.jpg)
Died on dots...but respawned at Suskarg instead of Felde as i should.

**Comment by Soulwhisper** [comment]
![123](https://cloud.githubusercontent.com/assets/16864486/12828931/fab261f4-cb8f-11e5-9ac1-4ab161de2627.jpg)
Here too...dying inside RvR lake...instead of Respawning to closest chapter which is Fedle...respawned at main Warcamp : Blackbramble Hollow

**Comment by Evildoor** [comment]
Dying in RVR respawns always respawns you in RVR Camp.

**Comment by Soulwhisper** [comment]
Ok so i let it open for the first one.

**Comment by Torquemadra** [comment]
fixed next patch

**Comment by Soulwhisper** [comment]
Nice
