### ISSUE TITLE
Twenty Steps Quests - Chain Rewards

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4233]
These left unbalanced in terms of rewards...
![toufekiaaaa_040](https://cloud.githubusercontent.com/assets/16864486/12828406/4d91c2fa-cb8d-11e5-9537-2e53be5a1a59.jpg)
![toufekiaaaa_041](https://cloud.githubusercontent.com/assets/16864486/12828405/4d89039a-cb8d-11e5-9581-9d8529ff5580.jpg)
I remember the 48 armor boots having +1 talisma free slot.
Rewards : 
48 Armor
+2 Toughness
+4 Initiative
OR
48 armor
+1 Free Talisma slot

**Comment by Soulwhisper** [comment]
No dilemma choosing between these 2..you choose the one with the stats obviously.

**Comment by wargrimnir** [comment]
http://war.mmodb.com/items/shallyan-shinsteels-90381.php
+11 WS
+4 STR
+2 TGH

http://war.mmodb.com/items/shinsteels-of-the-truth-seeker-91618.php
96 Armor
+16 STR
