### ISSUE TITLE
[BUG]Quests duplicaded

### ISSUE THREAD

**Issue by Scrilian** [WarEmu/WarBugs#4237]
I've just crashed at Avelorn keep siege and lost all my quests on BW. Now I'm able to take the Orders Quest the second time. Same must be for the Rats quest.
http://i.imgur.com/9rdiyin.jpg
Can see the scroll in the inventory.

**Comment by Scrilian** [comment]
And after restart the quests are back to the original.
http://i.imgur.com/lgqswmz.jpg

**Comment by Evildoor** [comment]
#2001
