### ISSUE TITLE
drops only on grp not on wb anymore sice the last patch

### ISSUE THREAD

**Issue by Bloodslicer** [WarEmu/WarBugs#4238]
hello GMs i found a critcaly bug . When in a WB kill any 1 in grp 1 an enemy the drop (soldier medallion) drops only in grp 1 so grp 2 3 and 4 can not roll on it. The same things on other grps  plz fix it  mfg Bloodslicer ur little git ;)

**Comment by Soulwhisper** [comment]
This is intended...AFAIK.On live drops were more frequent and were open to whole WB though.

**Comment by Evildoor** [comment]
Intended.
