### ISSUE TITLE
Multiple interactions with single quest object are possible

### ISSUE THREAD

**Issue by Halobravo** [WarEmu/WarBugs#424]
This isn't just for the quest "Save da Choppas" it works on every quest or public quest item that you have to interact with something multiple times.  You can just spam click whatever that item is and it instantly grants you what you need.  Many of these quest items / objects had a short cast time with kneeling animations before you got credit for it.  Another thing for this quest specifically is that the Choppa's have full HP.  Seeing as they are "Wounded" I would expect to see them at lower HP than 100%

(Speculation) you are collecting their weapons "choppas" so they can be taken back and used by other Orks, and I think the wounded guys die after you retrieve the weapons.  I am not sure if they die or not but that's what I seem to remember happening.

![guanyu_007](https://cloud.githubusercontent.com/assets/9036262/4529319/a53b665a-4d76-11e4-82ae-49c379df9b41.jpg)

**Comment by Evildoor** [comment]
Since this is the oldest and clearest open report which describes the issue (multiple clicks on same quest object are possible), i'll use it and close the other ones with similar problems.

**Comment by wargrimnir** [comment]
Fixed some time ago. GO's will only be usable once, then go on a 60s cooldown.
