### ISSUE TITLE
Quest: Mirelen's Watch High Elf Chapter 5 unable to be completed

### ISSUE THREAD

**Issue by pixie126** [WarEmu/WarBugs#4240]
Mirelen's Lost quest out of Mathrin's Watch in the Shadowlands will not complete.
It asks you to: Slay Uthorin Seeker
                       Parchment (Seeker's Parchment)
You can kill many seekers and get many parchments that go in your quest inventory, but none fulfill the quest.  Deliaren Swordsinger is the turn in NPC and he won't complete it.

**Comment by Torquemadra** [comment]
Fixed next patch

**Comment by pixie126** [comment]
Thanks
