### ISSUE TITLE
Quest: Echoes From the Past High Elf Chapter 5 unable to be completed

### ISSUE THREAD

**Issue by pixie126** [WarEmu/WarBugs#4241]
Quest Echoes From the Past out of Mathrin's Watch in the Shadowlands asks you to:
                Find the Uthorin Ensign (check the chest that is being closely guarded in the center of       Mirelen)

The Ark of Saruthil shows the clicky hand, but does not actually interact to complete portion of the quest. 
A quest leveling guide I have shows that completing this should proc another quest to accept to continue this quest line.

**Comment by Torquemadra** [comment]
Fixed next patch
