### ISSUE TITLE
Quest: Burden of the Land High Elf Chapter 6 autocompletes

### ISSUE THREAD

**Issue by pixie126** [WarEmu/WarBugs#4243]
This quest out of Sorrowstrand asks you to:
Use the Tears of Asuryan at:
     The Archway, The broken statue, the tower, and the partial wall

You do not receive the tears to use and there is no clickable areas near each target in the PQ Forgotten Future.  ( understandable if this completes this way due to the targets not being active) 

Finally, I found the NPC Ciaren Mournleaf, and talking to her out completed the whole quest.

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
