### ISSUE TITLE
Quest: A Call for Aid High Eld Chapter 7 cannot complete

### ISSUE THREAD

**Issue by pixie126** [WarEmu/WarBugs#4244]
Quest A Call for Aid out of Skyblade's Hold in the Shadowlands, asks you to
Kill Alonidar Lifedrinker
Find Battlefield Orders

Killing him gets credit, and the orders are down on a chest in the lower camp (like I remembered) and gave the clicky hand, but could not interact to complete its portion of the quest.

**Comment by Torquemadra** [comment]
Fixed next patch
