### ISSUE TITLE
Quest: The Glory of Ulthuan High Elf Chapter 9 targets in different zones

### ISSUE THREAD

**Issue by pixie126** [WarEmu/WarBugs#4245]
This quest should be completed in Ellyrion.  The quests states Starwillow root (4), Valeflower (4), and Wildbrush.  When it shows on your tracker it has Starfire Bloom instead of Valeflower.  
I couldn't complete this in Ellyrion.  All I could get there was the Wildbrush.

The Starfire Bloom is apparently in the Shadowlands near Sorrowstrand.  I clicked on the plant and it auto completed itself and the Starwillow Root to finally complete the quest.

**Comment by Torquemadra** [comment]
Fixed next patch
