### ISSUE TITLE
[Quest] "Spotling" quest has no turn in NPC

### ISSUE THREAD

**Issue by Halobravo** [WarEmu/WarBugs#425]
You can complete the quest objective by clicking the Pile of Junk, but it doesn't have a turn in point.  From my memory, a little snotling is supposed to pop out of the Pile of Junk and you talk to him to complete the quest.  I don't remember if he gave more quests or just turned in a quest.

https://www.youtube.com/watch?v=CFtFSv3qJx0&feature=youtu.be

**Comment by Meralors** [comment]
Turn in point added but no script. Quest is working that way tho
