### ISSUE TITLE
Cannot Clear Titles

### ISSUE THREAD

**Issue by Renork** [WarEmu/WarBugs#4250]
Unable to clear titles.

Note: **Switching** a title is not the same as **clearing**, FYI for those that want to chime in with their comments.

**Comment by Duendes** [comment]
I would also like to note that I cannot clear my title either and agree that while switching titles works, clearing them does not. I switched my title to Road Warden, not realizing that the Tome "clear title" is broken and now cannot go back to my default title. Is there a command for this?

**Comment by Evildoor** [comment]
Changelog from 21.03.2016 (a bit late :P ).
- Clear title works now.
