### ISSUE TITLE
Inventory bugged out

### ISSUE THREAD

**Issue by dasset** [WarEmu/WarBugs#4251]
I started Apothecary & Cultivation earlier today. I couldn't use Miracle Grow so I asked if anyone was having trouble with it. Someone told me that I had a bugged slot and that I should move items around in my inventory to find the bugged slot. Tried to dabble with it for a while but then my inventory went totally bonkers. 

![Inventory](https://cloud.githubusercontent.com/assets/17085430/12850084/a7e8b864-cc2b-11e5-85ad-bae549200214.jpg)

*update* 

Had to restore default User & Interface, must be an addon bug but which, I'm not sure. Disabling all addons didn't help. Had to use a fresh User & Interface folder.

**Comment by Evildoor** [comment]
#941?

**Comment by Evildoor** [comment]
No response, closing.
