### ISSUE TITLE
Tactic Flashing Claws doesn't add 10% parry (White Lion)

### ISSUE THREAD

**Issue by Paninii** [WarEmu/WarBugs#4252]
I have tried many situations on my White lion (ihavecats) but it always seems to add 2% parry.  With or without a pet.

The only thing i can think of is it adds 10% of the parry chance you have, instead of a flat 10% that it should add.

Plus, it adds 2% even without a pet, so thats probably a bug aswel?

The clip shows that parry status without tactic, with tactic without pet, and with tactic and with pet.

https://www.youtube.com/watch?v=yc3UROUitIU&feature=youtu.be

**Comment by Evildoor** [comment]
That's charsheet. What does ".getstats" say?

**Comment by Paninii** [comment]
ok so, getstats shows 22% with lion and tactic.
it shows 12% with tactic but without lion and 12% without tactic.

Which al seems correct, so i gues its just a display error of sorts.

**Comment by Luth-RoR** [comment]
Paperdoll issue.
