### ISSUE TITLE
Guild Tithe Rate

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4253]
You can set them but they dont work...no income from Upkeeps and Tithe/Tax doesnt work.
***UPDATE***
Tithe does work actually....it collects ammount from us(Farming/Killing etc) and donates it to the Guild...but by the time Taxes dont work and Guilt Vault NPC doesnt react...it is useless.

**Comment by nalgol** [comment]
if tithe work taxes work as well the amount isn't just listed at the tihted money section 
i uploaded both of them at the same time
guild vaults do work on dev just need some heavy testing still

**Comment by Soulwhisper** [comment]
Nono...Tithed money appears fine :) 
![guild](https://cloud.githubusercontent.com/assets/16864486/12860757/6590b016-cc67-11e5-9b57-9b833f287049.jpg)
Ok good to know...looking forward for these Warband features...!

**Comment by nalgol** [comment]
upkeep is the amount of gold needed to keep a guild claimed keep running afaik 
i didn't add the tax values to the tithe field since its called tithe ^^
so tax works in the background as soon as guild vaults are available the money should be there
just looked at the db some guilds got some money in there already

**Comment by Soulwhisper** [comment]
Oh...so we can keep Tithing...the money wont be lost when the Guild Vaults will be implemented right? It will be there...

**Comment by Soulwhisper** [comment]
![guild](https://cloud.githubusercontent.com/assets/16864486/12868492/cb81283e-cd10-11e5-8252-27a611350cc8.jpg)
VISUAL : The pop-up notification of Guild Tithe does not show correctly.Guild is correct.Tithe appears to be wrong for everyone in the guild.Just the notification.

**Comment by nalgol** [comment]
yes the money will be there its already stored in the db the guild vault will just load the values 

for tithe hmm need to take another look then ( tax is global for every player tithe can be set by each player what he wants to give to the guild)

first tax is applied to looted money after that tithe is applied so you can set tax to like 50 % and tithe to 80%

**Comment by Soulwhisper** [comment]
ah ok...just to know its only visual.Try setting Tax and Tithe to whichever values you want.First time chat shows them correct.Travel in any country after that and check chat.Its visual bug.
![visual](https://cloud.githubusercontent.com/assets/16864486/12871587/f9bc1c34-cd8a-11e5-9a62-de733aa6fb74.jpg)

**Comment by Evildoor** [comment]
Changelog 17.02.2016
[Guilds & Guilds Features]
- Tithe and taxes work now.
...
- Guild vault works now.
