### ISSUE TITLE
Wrong weapon type

### ISSUE THREAD

**Issue by JamGrif** [WarEmu/WarBugs#4255]
The weapon painbringas big choppa says it is a great axe but is held in one hand

![aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/16886300/12857135/69cbf964-cc40-11e5-833e-efc97f1f8c9d.png)

**Comment by Torquemadra** [comment]
Fixed next patch
