### ISSUE TITLE
Quest  : Slay it again, Sam (Questmarker)

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4256]
Questmarker dissapears if you first speak with the slayer Samonir.
![toufekiaaaa_059](https://cloud.githubusercontent.com/assets/16864486/12860815/ca91a7f4-cc67-11e5-811b-c16a08acf057.jpg)
![toufekiaaaa_060](https://cloud.githubusercontent.com/assets/16864486/12860816/cc59f014-cc67-11e5-9827-dad919d98480.jpg)

**Comment by DanaBloodkiss** [comment]
Actually there were 2 questmarkers. I replaced them by one so it should show up.
