### ISSUE TITLE
Dark Elf Bolt Throwers in High Elf Warcamp.

### ISSUE THREAD

**Issue by Gobtar** [WarEmu/WarBugs#4262]
Many High Elf Warcamps use the Dark Elf Bolt Throwers instead of the High Elf Model.
![pocketknight_003](https://cloud.githubusercontent.com/assets/7888608/12864907/b14ab668-cc72-11e5-970d-15fe9edfd59c.jpg)
Example:
![eagle_claw_ concept_art](https://cloud.githubusercontent.com/assets/7888608/12864914/f610edda-cc72-11e5-893a-9bcc6d88bfd3.jpg)

I will add the name of an ingame model that currently uses the HE Bolt thrower model.

**Comment by DanaBloodkiss** [comment]
That was fixed.
