### ISSUE TITLE
tome of bestairy unlock

### ISSUE THREAD

**Issue by lijebin** [WarEmu/WarBugs#4265]
i kill 25 slayer already they it told me to kill the slayer in barvak varr but i don't get kill on him to get unlock

**Comment by Evildoor** [comment]
"i don't get kill on him to get unlock" - what?

**Comment by lijebin** [comment]
the titel my magus just kill him twice didn't get title

**Comment by Evildoor** [comment]
Unlock name, monster name.

**Comment by lijebin** [comment]
ok first of many 
![arngrym_003](https://cloud.githubusercontent.com/assets/17027595/12865817/940efe80-ccf2-11e5-9073-6f0198c0e63b.jpg)

**Comment by Evildoor** [comment]
#3997

**Comment by lijebin** [comment]
then monster name is first mate kjaelsson
