### ISSUE TITLE
a sorcer level 12 in t1 norland

### ISSUE THREAD

**Issue by lijebin** [WarEmu/WarBugs#4266]
he just level 12 and didn't turn to chicken
![tarelther_005](https://cloud.githubusercontent.com/assets/17027595/12865701/d270e746-ccee-11e5-8b65-c5c4aa52947a.jpg)

**Comment by lijebin** [comment]
any gm can help

**Comment by Evildoor** [comment]
#1399
Stop asking for GM help here - if you need one, use forums/in-game chat.

**Comment by lijebin** [comment]
ok sorry
