### ISSUE TITLE
Wrong image on items

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#4267]
The rewards from the quest Marked for shaman: Average Greenbringas of Discipline and Average Greenbringas of Insight, have the image of an axe instead of gloves as it should be.

**Comment by ElMosquito** [comment]
They don't seem to have any appearance either. They are invisible when equipping them.

**Comment by Ryanfawkez** [comment]
That's because they have a weapon model assigned, which doesn't show on your character when used as an armor piece. Will be fixed in next patch.
