### ISSUE TITLE
nordland t1 order warcamp

### ISSUE THREAD

**Issue by lijebin** [WarEmu/WarBugs#4271]
is this bug or not because i can use a hill to pass harvest shine and jump on a rock to their war camp and don't attack by guards 
![arngrym_004](https://cloud.githubusercontent.com/assets/17027595/12871238/7c22da44-cdab-11e5-90d1-74fb0d3767dd.jpg)

**Comment by Evildoor** [comment]
Hmmm. Can you do something from here, like killing important NPCs or afking players? Because from the look of this screenshot it seems that you can only reach guards, and it's unlikely place for players to afk since flightmaster, vendors and other important things are far from here.

**Comment by lijebin** [comment]
yes my damon can kill some npc and i kill some player here

**Comment by lijebin** [comment]
just like this
![arngrym_005](https://cloud.githubusercontent.com/assets/17027595/12873007/e588bcaa-cded-11e5-94f7-05d646cd0cd0.jpg)
![arngrym_006](https://cloud.githubusercontent.com/assets/17027595/12873008/ea05b4ea-cded-11e5-84d9-dad03d4db1d5.jpg)

**Comment by lijebin** [comment]
so is this fix ?

**Comment by Evildoor** [comment]
Changelog 17.02.2016
- [4271] Guards: Added more Nordland T1 Warcamp Guards.
