### ISSUE TITLE
[Item] Qhaysh Boyz' Ring changed to Thickmuck  Dark Band in inventory

### ISSUE THREAD

**Issue by ropuch** [WarEmu/WarBugs#4273]
It seems Choppa Greensking T3 Inf reward Qhaysh Boyz' Ring has been somehow changed to Thickmuck  Dark Band (BG reward), so now I have unusable purple ring in my backpack.
Unfortunately I can't tell which particular update caused since I have not been playing this toon in a while. I know of at least one more chopa hit by the same ring swap 

![ringz](https://cloud.githubusercontent.com/assets/24792/12871817/c7bd38b0-cd8c-11e5-80a1-1bfc15bc9579.png)

**Comment by Evildoor** [comment]
#4207
#4220 
#4223
and some more.
