### ISSUE TITLE
In-Combat Morale Swapping

### ISSUE THREAD

**Issue by Sek92** [WarEmu/WarBugs#4274]
Hi,

I would like to report a bug which allows morales to be switched whilst IN combat.

Whilst a set morale may be chosen from whilst out of combat, if I recall on live you could not switch morales during combat.

During combat, whilst morale is charging, one can open up their abilities bar, click the morales tab and RIGHT click the morale of their choosing even if the chosen morale wasn't previously set and use the key that the morale (1/2?) is bound to, in my case F10, to initiate it.

As this is a rather fluid endeavor to capture with a screenshot - I have recording it on twitch for your attention.

http://www.twitch.tv/rubmycrit1/v/41785821

I initially begin with M1 Point-Blank, wait till my morale 1 is ready, open up the action bar/ morales page, right click M1 Concealment, and using the bound key the morale is assigned to - I am able to use a completely different morale during combat.

I believe this is an issue that may need to be addressed.

Thanks.

**Comment by Evildoor** [comment]
#1143
