### ISSUE TITLE
Invis bugged mob spawn

### ISSUE THREAD

**Issue by Theslay** [WarEmu/WarBugs#4276]
Found a bugged little mob ^^
![theslay_005](https://cloud.githubusercontent.com/assets/17109649/12872928/edc516da-cdb0-11e5-9ca3-d74f6994107e.jpg)
![theslay_004](https://cloud.githubusercontent.com/assets/17109649/12872929/f5d8e4a0-cdb0-11e5-8e03-90ece4e4d611.jpg)
![theslay_001](https://cloud.githubusercontent.com/assets/17109649/12872930/042436fe-cdb1-11e5-8980-78e975e8f197.jpg)

**Comment by DanaBloodkiss** [comment]
Fixed in next.
