### ISSUE TITLE
Parry

### ISSUE THREAD

**Issue by xA3Kx** [WarEmu/WarBugs#4277]
ive noticed using Weapon Skill is suppose to increase parry and Armor pen, but when i spec into Renown, and or Tactics parry doesn't increase at all when i check my Character sheet and .getstats command.

**Comment by Evildoor** [comment]
![huntress_000](https://cloud.githubusercontent.com/assets/11015074/12874221/9bf5a9d4-cde0-11e5-8f17-22caceaee447.jpg)

**Comment by ozarmidrashim** [comment]
Parry from WS varies with attacker's Str and will not be shown.
