### ISSUE TITLE
Dok T3 Influence reward Jewelry

### ISSUE THREAD

**Issue by gvdn78** [WarEmu/WarBugs#4279]
Hi i noticed on my Dok that my influence reward from greenskin t3 has changed and is now unusable as it says it is usable by BG now.
Also noticed the rewards u can take now have also changed and was wondering if reward selection could maybe be reset so u can choose again now that different rewards are available.

Thank you

**Comment by Evildoor** [comment]
#4207
#4220 
#4223
and some more.
