### ISSUE TITLE
ToK - Bestiary Night Goblins in badlands

### ISSUE THREAD

**Issue by GRuBshy** [WarEmu/WarBugs#4280]
Goblins in the  Badlands, are count as normal goblins, but they are night goblins.
![ungar_000](https://cloud.githubusercontent.com/assets/17109054/12876145/fdd5a748-cdfa-11e5-98ca-e488db73d404.jpg)

**Comment by DanaBloodkiss** [comment]
Fixed around 24 Night Goblin Sub Types.
