### ISSUE TITLE
No extra emblem for winning when time runs out

### ISSUE THREAD

**Issue by tutti13** [WarEmu/WarBugs#4284]
Winning with a higher score (but < 500) after the 15:00 mins run out does not give an extra emblem for winning.

(Winning with 495:210 after the time ran out only gave me 4 emblems)

**Comment by Evildoor** [comment]
IIRC, ROR's current system rewards 1 emblem per 100 points and 1 extra emblem per 500 points.

**Comment by tutti13** [comment]
May I suggest changing this, so the last Emblem is awarded for winning?

**Comment by Evildoor** [comment]
This is not a place for suggestions.
