### ISSUE TITLE
Quest: Ravage The Lords of Order

### ISSUE THREAD

**Issue by Povel** [WarEmu/WarBugs#4285]
The Order equivalent version of this quest requires only 45 kills instead of 99 kills that is required by the Destruction Version.

This is stage 3 (the part before you go visit your home city and King of the quest chain)

**Comment by Evildoor** [comment]
Maybe you logged onto a character which still has an old version of the quest? Or it's not the case and you accepted it from the NPC?

**Comment by Povel** [comment]
Pretty sure it's the latter, although I will bring a toon up into T3 tomorrow and take the quest to confirm.

TBC

**Comment by Ryanfawkez** [comment]
I remember altering one of the quests to have the actual required killcount at 99, seems I forgot to do the same for Destruction. Will be fixed in next patch.

**Comment by Povel** [comment]
Fair enough =P
