### ISSUE TITLE
Pets in rvr

### ISSUE THREAD

**Issue by cimator** [WarEmu/WarBugs#4288]
When high level players go to a lower tier rvr, they become chicken but their pets stands still and they can control it. It is ok for squigs because I can see the owner's name so that I can report him/her, but the owner's name doesnt show up on lions and a 32 rank lion kept killing me in t1 rvr. It is quite annoying please fix this. (I couldnt find how to label this sorry about that)

**Comment by Evildoor** [comment]
#4036 may be related.

**Comment by Pumatouch** [comment]
Most def related. A fix could be to remove all existing turrets and pets upon being turned into chicken. If it then keeps occuring it's most likely somebody messing with the chicken function in general.
