### ISSUE TITLE
[NPC] Spire of Teclis

### ISSUE THREAD

**Issue by Vandorkholme** [WarEmu/WarBugs#4289]
The Well of Qhaysh Brightspear (White lion-esque guard) does not need to be killed to cap the BO.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by sioding** [comment]
since there are no guards at BO´s anymore and this issue is being reported in 2016 i will close this now
