### ISSUE TITLE
Influence Reward WH

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4292]
![phantomas_000](https://cloud.githubusercontent.com/assets/16864486/12917160/710128f0-cf40-11e5-8a97-1ce00236076b.jpg)
Back on live i remember there was a +5 or +7 ballistic skill pistol as a reward on the first PQ.
I guess this +1 Initiative is not correct for WH.
Dunno though if you could do it +5/+7 ballistic or Strength because i heard that WH main stat Ballistic changed to STR now.
Regards.

**Comment by Evildoor** [comment]
Proof?

**Comment by Soulwhisper** [comment]
PQ chapter 1.
Cant find any.But im pretty sure it had Ballistic Skill bonus on live.
I will search deeper to find the rewards though.

**Comment by Ryanfawkez** [comment]
http://www.warbits.com/gold-items-14724-Recruiters-LR.html

Only Recruiter's weapon I found find on the web; has a +3 main stat, assuming this pistol thus needs +3 strength. Will be fixed in next patch.
