### ISSUE TITLE
Horrors of War - Cowering Militiaman

### ISSUE THREAD

**Issue by JeFawk** [WarEmu/WarBugs#43]
Cowering Militiamen must be killable but is friendly.

![image](https://cloud.githubusercontent.com/assets/7268697/2907729/bdb82f66-d61f-11e3-857a-84024009eeb7.png)
 
They should turn neutral when you talk to them but I think my fix will also do, they're always neutral.

Code to apply fix:
`UPDATE creature_spawns set Faction='0' WHERE (Entry='145')` 

And to be consistent:
`UPDATE creature_protos set Faction='0' WHERE (Entry='145')` 

Thanks @Fikatind

**Comment by milosxe** [comment]
This quest is working fine now. You can talk to cowering militiamen and "they will join your cause". Closing.
