### ISSUE TITLE
RvR T3 Empire - Error: Wrong Ressurection Location

### ISSUE THREAD

**Issue by erkislev** [WarEmu/WarBugs#4300]
Once been fighting in RvR T3 Empire Talabecland and clicked Ressurection. Instead of being ressurected at Passwatch Castle, I've been thrown to a wrong location — which was even out of south Talabecland, it was out of the map. See screens below.

I had a chance to move to South Talabecland though through mountain passes.
![lost 2](https://cloud.githubusercontent.com/assets/16850861/12942593/6af99516-cfed-11e5-9a97-14f3659a1b3e.jpg)
![lost](https://cloud.githubusercontent.com/assets/16850861/12942592/6af3431e-cfed-11e5-85c4-cd40a04ef42f.jpg)

**Comment by Torquemadra** [comment]
Where in RvR Talabecland?

**Comment by DanaBloodkiss** [comment]
Sure it's not a singel bug?

**Comment by erkislev** [comment]
Never heard of it and never repeated it, so yes, it's a single bug, but doesn't that mean it can occur someday to someone else?

**Comment by Vandorkholme** [comment]
I've had this randomly happen somewhere in T2. It only happened once, and it wasn't out of the map... but it definitley wasn't a warcamp. I have no idea how to reproduce it.
