### ISSUE TITLE
Incognito

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4301]
![phantomas_001](https://cloud.githubusercontent.com/assets/16864486/12944551/75de9712-cff0-11e5-8173-e72deb17d8bc.jpg)
If i remember correct back on live you should first use Burn Armor while you were Incognito before you use any other abilities. Now i can use all my abilitities while Incognito.

**Comment by Evildoor** [comment]
It was possible to use any ability while stealthed on live.

**Comment by Soulwhisper** [comment]
Hm...maybe after some patch...dunno...
