### ISSUE TITLE
Cannot go back to default title

### ISSUE THREAD

**Issue by Duendes** [WarEmu/WarBugs#4302]
This issue was posted before but fell into the yonder without a fix. The problem is if you change your title to anything other than the default, you cannot CLEAR your title so that it goes back to the default. (You can switch to another achievement based title, but that's not the issue here.) 

The tome has a "Clear Title" option, but nothing happens when you click it. I would like to go back to my default title. 1. There is no listing of default titles earned via rvr, and 2. There is no way to clear the current title. 

If this is not fixable via the tome entry, is there a command to just clear title or to put your default rvr-earned title back into place?

**Comment by Evildoor** [comment]
> This issue was posted before but fell into the yonder without a fix.
Really? Then i suggest you to go read the rules of the bugtracker.
