### ISSUE TITLE
Destro Saphery Scavenging:  Dryads now broken unscavengable.

### ISSUE THREAD

**Issue by mursie** [WarEmu/WarBugs#4303]
For order, the lvl 27-29 champs in Saphery are a densely populated popular place to both power level and scavenge for talisman fragments.  This is in the southeast part of saphery in the pve zone.

For destro, there was unfortunately only about 5 dryad champs located in the far northwest of the map (behind the chapter 12 camp) that basically gave destro the same type of scavenging access.  In addition, a new patch of dense dryads were placed right beside these 5 champs.  Unfortunately, the bug is that ALL of these mobs are now no longer scavengable.  Which means, destro doesn't have access to a good spot to farm talismans like order does.  

Can you please address these mobs and re-activate their drop tables for scavenging.

**Comment by Doomsday82** [comment]
Just wanna open same ticket. Safery champs at destro have no loot and no scanvege avalable a few weeks, like all 39-40 mobs exept new in capitals. It must be mistake then fix loot from 40lvl mobs. But on order side all works good, so bring back chap scavenging to destro, or remove it from order. Now it disbalanced.

**Comment by Torquemadra** [comment]
#4046 ? if not precise names please

**Comment by Gobtar** [comment]
I will get you the precise names tonight Torque

**Comment by Gobtar** [comment]
Runebough Branchwraith

**Comment by Evildoor** [comment]
#4046 then.
