### ISSUE TITLE
T3 Influence reward rings changing career unexpectedly.

### ISSUE THREAD

**Issue by mursie** [WarEmu/WarBugs#4304]
Our guild member plays a zealot.  His T3 influence ring (which is career bound) has +AP on it and is a very critical piece of gear for BiS at the current stage of the game.  For some reason, a few weeks back a number of players noticed that their T3 influence rings have now been altered and are no longer usable. 

Specifically, for the player named Captainhawt, his T3 influence ring was changed to a Blackguard career ring that can no longer be used (he's a zealot).  Can you please fix this?

**Comment by Evildoor** [comment]
#4207
#4220 
#4223
and some more.
