### ISSUE TITLE
Wrong stats on Bandit's Heater

### ISSUE THREAD

**Issue by NyphoX** [WarEmu/WarBugs#4307]
![odnhtxw](https://cloud.githubusercontent.com/assets/17164873/12956248/503d3f2c-d027-11e5-98aa-41056f19fba4.png)
This would pretty much make the Bandit's Heater less valuable than the Grim Heater.

**Comment by Torquemadra** [comment]
http://www.warbits.com/gold-items-4821-Bandits-Defender.html

adding +2 block to these
