### ISSUE TITLE
Starter Items

### ISSUE THREAD

**Issue by DanaBloodkiss** [WarEmu/WarBugs#4308]
Confirmation needed if these ones are actual bugs.

-All Empire classes start with the same boots: "Ragged Peasant Boots" Every other race in the game has specific class boots.

-Slayer has no boots upon spawn.
-Shaman has no boots upon spawn.
-Squig Herder has no boots upon spawn.
-Choppa has no boots upon spawn.
-Black Orc has no boots upon spawn.
-Magus has no boots upon spawn.
-Zealot has no boots upon spawn.

**Comment by DanaBloodkiss** [comment]
http://www.returnofreckoning.com/forum/viewtopic.php?f=11&t=11435

**Comment by Renork** [comment]
Magus did not have boots :^)

**Comment by Evildoor** [comment]
I suppose that this served it's purpose and can be closed.
