### ISSUE TITLE
Item level wrong when salvaging

### ISSUE THREAD

**Issue by Blubberino** [WarEmu/WarBugs#4309]
Xiphos of Agression is treated as lvl 1 Item when you salvage it. 
![valfaros_007](https://cloud.githubusercontent.com/assets/16993024/12964461/8d964c5a-d050-11e5-983d-3a518cca885a.jpg)
![valfaros_006](https://cloud.githubusercontent.com/assets/16993024/12964469/95541f44-d050-11e5-893a-4233da9c090f.jpg)

And you also get lvl 1 salvaging stuff 
![valfaros_008](https://cloud.githubusercontent.com/assets/16993024/12964482/a5e69706-d050-11e5-9182-f30f9f68935b.jpg)

**Comment by ozarmidrashim** [comment]
Any item not showing Item Level: will salvage as level 1 for some reason.

**Comment by Torquemadra** [comment]
Fixed next patch
