### ISSUE TITLE
"Flawless Gold Dust" missing

### ISSUE THREAD

**Issue by GankbusOsmium** [WarEmu/WarBugs#4310]
The NPC "Plaguesworn Denizen" drops, at lvl 40, "Forgotten Soldier's Insignia " but only "polished gold dust" which is lvl 175. It is supposed to drop "Flawless Gold Dust" lvl 200.
Maybe the chance is just very low, had 9x lvl 175 "polished gold dust".

**Comment by Scrilian** [comment]
Same true for the order side Feathered Acolytes.

**Comment by Ryanfawkez** [comment]
Do the level 40 NPCs also drop level 175 curios? To me it seems the level 39 NPCs can be scavenged for level 175 mats, while the level 40s drop the level 200 stuff. Keep in mind the NPCs alternate between level 39 AND 40, which may be the reason as to why you're getting both level 175 and 200 mats. I can't check the droprate for level 200 gold dusts, but it could be that their chance to drop is very low.

**Comment by GankbusOsmium** [comment]
As I wrote "The NPC "Plaguesworn Denizen" drops, at lvl 40, "Forgotten Soldier's Insignia " ". 
Forgotten Soldier's Insignia is a lvl 200 curio. Got only those from the lvl 40 version, no lvl 175 curio yet.

**Comment by Ryanfawkez** [comment]
Yeah, that narrows down the problem to an incomplete scavenging table for level 40 mobs.

**Comment by NorKalli** [comment]
long since added
