### ISSUE TITLE
Quest "Defend Lost Lagoon"

### ISSUE THREAD

**Issue by magicthighs** [WarEmu/WarBugs#4313]
The order quest "Defend Lost Lagoon" asks you to slay enemy players at the Lost Lagoon BO, which doesn't exist anymore (used to be in Norsca) and then hand the quest in at the BO Marshall, making it impossible to complete.

**Comment by Evildoor** [comment]
Who gives it?

**Comment by magicthighs** [comment]
Excellent question, but I have no idea, found the quest in my quest log when I was cleaning it up. If I have to guess I think it might be the Festenplatz or Harvest Shrine BO Marshall, because they're not at the BOs atm, and after dropping the quest I can't find any NPC in Nordland that gives it.

**Comment by Ryanfawkez** [comment]
Will be restricting these quests to level 40 as a way to prevent people from getting a quest that cannot be completed. I'd suggest you simply remove this uncompletable quest.
