### ISSUE TITLE
[ART] Visual bug on T2 chests of Swordmaster

### ISSUE THREAD

**Issue by CecilTOB** [WarEmu/WarBugs#4315]
It s a personal problem cause other player can wear the gear correctly without any problem. But they can see that strange bend black on my chest.

What I did, since that problem didnt exist before, was a change appearence with that skin, and now it s stucked like this.

Problem is on Issued, Regulation, Conquest and Dominion chest piece of Swordmaster.

Player Cecill

![screenshot4826](https://cloud.githubusercontent.com/assets/17180649/12983023/bb3dfb98-d0e7-11e5-8725-4461ab6dec1f.png)

**Comment by Ryanfawkez** [comment]
It's not your chestpiece, it's the boots you're using.

**Comment by CecilTOB** [comment]
Thanks so much for this. Now the Thread is, Visual bug on Stalker s boots.

**Comment by CecilTOB** [comment]
Problem solved if I skin the Stalker s with other stuff.

**Comment by Evildoor** [comment]
#3812
