### ISSUE TITLE
Open RvR T2 Dwarf Entry

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4317]
It only unlocks the influence bar only when you get really close to Foultooth's Warcamp(Destro) in Barak Varr.On other Tiers every RvR influence unlocks when you visit for first time your Warcamps.
Is this intended or what? **Spend 1 hour to find out where i had to go to unlock the entry so i could start earning influence for T2 RvR in Dwarf.**
Regards.

**Comment by Evildoor** [comment]
#1205
