### ISSUE TITLE
Landmine

### ISSUE THREAD

**Issue by Blubberino** [WarEmu/WarBugs#4321]
The Tooltip of the landmine says that it should be a 3 second stagger but the debuff showes that it lasts for at least 5 seconds.

![pania_006](https://cloud.githubusercontent.com/assets/16993024/12992491/15b768c0-d115-11e5-886a-a2b848dbe630.jpg)

After testing the Landmine the debufftimer seems to show the correct time of the stagger and in this case the tooltip gives the wrong information of how long the skill lasts.

**Comment by milosxe** [comment]
Tooltip is client side and can't be changed. 5s duration for stagger was an intentional change for landmines and infestation. 

Should prolly be updated in this thread
http://www.returnofreckoning.com/forum/viewtopic.php?f=11&t=8768

In other words, not a bug.

**Comment by Blubberino** [comment]
Ah okay sry
