### ISSUE TITLE
Sc queue bug

### ISSUE THREAD

**Issue by Rammsteinn** [WarEmu/WarBugs#4322]
Hey all !

This to report a curious bug i've experienced in the past couple of days.

I am on character A, queued for sc's. No pops. Getting bored, log out to switch to toon B.

When on toon B, I queue and get a pop. Surprisingly, that pop is for my toon which is logged out. On the "scenario team shout", I see character A's name in the list. If i click "join", nothing happens. If I requeue, it tells me I'm already queued although the sc button is not lit. Only restarting game fixes it.

Looks like the scenario queue process mixes both toons.

Anyone else having this issue?

**Comment by Torquemadra** [comment]
I see this issue too, investigating

**Comment by Rammsteinn** [comment]
Oh ok ! So even if it says i can't queue because i'm already queued, i still actually AM in the queue?

Also forgot to mention. Sometimes I get a pop on toon B and I take it. Then, DURING the sc, i get a pop for toon A. Looks like at this stage the client doesn't even realize I am in an sc and not supposed to get any pop !
