### ISSUE TITLE
teleport barrels modrins amboss [low priority]

### ISSUE THREAD

**Issue by Boebinator** [WarEmu/WarBugs#4323]
if you fall in the canyon on chapter 1 modrins amboss in ekrund it have explosive barrels that you can click for a teleport but they dont work for destro.

location: 30000:40000 there must be 2 or 3 barrels and 1 in the cave under the bridge.

**Comment by DanaBloodkiss** [comment]
We could add that as teleport but that would be lame. We will wait till we have the original effect.
