### ISSUE TITLE
Guild Managment

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4326]
![guild permsissions](https://cloud.githubusercontent.com/assets/16864486/13012059/5871304a-d1b2-11e5-9531-ea6e80ec5ab3.jpg)
Probaply none of the permissions are functionall right now(Most are not implemented yet) but i tested chat permissions and they dont work.
**Obviously you are aware.Just posting it.**

**Comment by ozarmidrashim** [comment]
The bugtracker is for bugs in existing content, not for features that we never implemented in the first place. This is said clearly in the rules for the tracker on the forum.

**Comment by Soulwhisper** [comment]
Sorry for that but didnt know that chat permissions havent been implemented yet.
By the time Roster Managment tab works fine i assumed that Cha tab will too.
Regards
