### ISSUE TITLE
IB scenario Shields:  rr 24 > rr29 shield.  bug?

### ISSUE THREAD

**Issue by mursie** [WarEmu/WarBugs#4327]
Sentry's Defender of Sanctity:  Lvl 24 rr shield  has 1% crit reduction and **80 hp** every 4 secs
Sentry's Defender of Rigor:  Lvl 29 rr shield  has 1% crit reduction and  **20hp** every 4 secs

Why is the rr24 shield better than the lvl 29 shield.  (yes i know the minor stats and block rating are better on the 29 but this can't compensate for 60hp every 4 secs that the lower shield has.

Is this intended?

**Comment by Evildoor** [comment]
http://www.arsenalofwar.com/items/Order/Sentry's%20Defender%20of%20Sanctity
http://www.arsenalofwar.com/items/Order/Sentry's%20Defender%20of%20Rigor
Should be 20. Maybe other tanks have the same problem.

**Comment by Styrkarr** [comment]
Fixed in next patch.
The other tanks shields are normal, it was the only one with 80hp/s.
