### ISSUE TITLE
Not enough guards for destro in Avelorn

### ISSUE THREAD

**Issue by Zanilos** [WarEmu/WarBugs#4334]
![echosta_069](https://cloud.githubusercontent.com/assets/16420518/13023105/75b72b8e-d1dd-11e5-920c-8936f183fb51.jpg)
![echosta_070](https://cloud.githubusercontent.com/assets/16420518/13023104/75a9f4b4-d1dd-11e5-84c5-58e561158fa0.jpg)

We did our usual WC race, except we didn't die... Got a few cheeky kills before suicide.

**Comment by Zanilos** [comment]
Just to inform you what was done...

We pushed between the guards they 1 shotted a few people, but when we got further in there are only lvl 14ish npc. You can just stand by them and res up.

**Comment by Torquemadra** [comment]
Not next patch
