### ISSUE TITLE
IB Thickmuck Greathelm: T3 Empire influence

### ISSUE THREAD

**Issue by mursie** [WarEmu/WarBugs#4335]
as with all other tank Thickmuck helms, this helm should have 2% melee crit chance.  Currently it does not.  Can you please add.

For reference pls see the thick muck Kotbs and SM below

http://www.arsenalofwar.com/armor/Order/Thickmuck%20Casque
http://www.arsenalofwar.com/armor/Order/Thickmuck%20Taen

**Comment by Torquemadra** [comment]
Thickmuck Greathelm has an additional 22 wounds that the others do not.

**Comment by Ryanfawkez** [comment]
I fixed the Ironbreaker helmets in relation to each other, not sure why there's crit on the SM/KotBS helms.
