### ISSUE TITLE
Zealot Tactic "Blessing of Chaos"

### ISSUE THREAD

**Issue by Moosrose** [WarEmu/WarBugs#4336]
If proc from "Blessing of Chaos" is up on target 25% more heal is only working with direct heal. For hots it seems not to work.

**Comment by ozarmidrashim** [comment]
RoR treats any buff as a single attack or heal, dealt over time. It calculates the damage bonus, resistance etc at the time of cast and not individually for each tick.

**Comment by Moosrose** [comment]
cant follow,) maybe an example for me would be nice

**Comment by ozarmidrashim** [comment]
If Blessing of Chaos is up when you cast your HoT, it's affected. If it's not up, it won't be affected, even if you apply BoC after the HoT is applied.

**Comment by Moosrose** [comment]
you´r sure we set the hot after the proc was up and there was no affect

**Comment by ozarmidrashim** [comment]
Hmm. I'll check it.

**Comment by ozarmidrashim** [comment]
Confirmed, fixed.

**Comment by ozarmidrashim** [comment]
Edit: Nope. It actually works as it did on live. While BoC is up, the HoT's effect is increased. There was nothing to fix.
