### ISSUE TITLE
Venomburst Spiders - no loot and cannot butcher

### ISSUE THREAD

**Issue by SharpiesOfWar** [WarEmu/WarBugs#4338]
Hello. 

The level 9 Venomburst spiders in norsca drop no loot and cannot be butchered. The Venomburst Widows next to them do however. Locations is near: 53.4k, 25.3k

**Comment by DanaBloodkiss** [comment]
Should be working.

**Comment by SharpiesOfWar** [comment]
Hi.
I just went back into that area and killed some more of them. There are two types of spiders in that spot. "venomburst spider" (smaller spider) and "venomburst Widow" (larger ones). The Widows, are butcherable but the "vemonburst spider" is not.

**Comment by Torquemadra** [comment]
Fixed next patch
