### ISSUE TITLE
Hrim Tuskgor - cannot butcher

### ISSUE THREAD

**Issue by SharpiesOfWar** [WarEmu/WarBugs#4339]
Unable to butcher these mobs near location Norsca - (56.1k, 42.6k)

**Comment by DanaBloodkiss** [comment]
We would need information what the creature should drop when it's butchered.

**Comment by SharpiesOfWar** [comment]
According to the following links: 
http://warhammeronline.wikia.com/wiki/Tuskgor 
https://gaarawarrgabs.wordpress.com/2009/11/19/beginners-guide-to-butchering/

They should be dropping the appropriate level butchering items: 
Boar Blood (Duration) - Thin Boar Blood 
Zoic Gore (Stabilizer) - primal zoic gore
Animal Humor (Restoration) - Putrid Animal Humor

**Comment by Evildoor** [comment]
#2323
