### ISSUE TITLE
[Quest] Zone: Nordland, "Raven Host Vanquard" public quest does not proceed to stage 2

### ISSUE THREAD

**Issue by arthrone** [WarEmu/WarBugs#434]
After finishing 1 stage of Raven Host Vanquard Public quest 2nd stage does not start.

**Comment by SpartanMarine88** [comment]
The escort, (a dwarf priest) spawns dead and naked by the barn area. If i remember correctly he is supposed to enter guarded by a group of civies.

**Comment by milosxe** [comment]
You can complete all 3 stages of this PQ. Closing.
