### ISSUE TITLE
Tuskgor and Bull Tuskgor - not butcherable

### ISSUE THREAD

**Issue by SharpiesOfWar** [WarEmu/WarBugs#4340]
Unable to butcher these mobs near location Ostland - (46.7k, 43.3k)

**Comment by DanaBloodkiss** [comment]
We would need information what the creature should drop when it's butchered.

**Comment by SharpiesOfWar** [comment]
According to the following links: 
http://warhammeronline.wikia.com/wiki/Tuskgor 
https://gaarawarrgabs.wordpress.com/2009/11/19/beginners-guide-to-butchering/

They should be dropping the appropriate level butchering items: 
Boar Blood (Duration) - clotted Boar Blood 
Zoic Gore (Stabilizer) - feral zoic gore
Animal Humor (Restoration) - Stale Animal Humor

Note: I have found another site: http://war.mmodb.com/ which says that tuskgor are of subtype: "chaos breed" and not "beasts" as it has recorded for boars. So many the http://warhammeronline.wikia.com/wiki/Tuskgor is wrong.

**Comment by Lheana** [comment]
They are now correctly butcherable.
