### ISSUE TITLE
Bloodsnout Tuskgor - not butcherable

### ISSUE THREAD

**Issue by SharpiesOfWar** [WarEmu/WarBugs#4341]
Unable to butcher these mobs near location High Pass - (42.5k, 50.8k)

**Comment by DanaBloodkiss** [comment]
We would need information what the creature should drop when it's butchered.

**Comment by SharpiesOfWar** [comment]
As per:  #4339 and #4340, I found the following information:
------------------------------------------------------------------------------
Note: I have found another site: http://war.mmodb.com/ which says that tuskgor are of subtype: "chaos breed" and not "beasts" as it has recorded for boars. So maybe the http://warhammeronline.wikia.com/wiki/Tuskgor is wrong. 
-----------------------------------------------------------------------------

**Comment by Shadowsmove** [comment]
Tuskgors are able to be scavenged since the update that implemented professions, I think all chaos breeds are scavenge types and not butcher type but I cannot remember if it was this way on live or not.

**Comment by Evildoor** [comment]
#2323
