### ISSUE TITLE
Quest: Different Kind Of Battle

### ISSUE THREAD

**Issue by SharpiesOfWar** [WarEmu/WarBugs#4345]
This quest seems to be bugged. It looks like it should be sending me to talk to Werner Fassbinder but in the requirements, it is telling me to talk to someone else. I have attached two screenshots. The first one is when I first picked up the quest and was not able to turn it in. The second one is what the quest says tells me after I abandoned it and picked it up again. 
![knee_000 - different kind of battle - speak to unicorn](https://cloud.githubusercontent.com/assets/16397729/13028248/7b1efb92-d21e-11e5-9bb7-56adf862adbc.jpg)
![knee_001 - different kind of battle - speak to thagor balefist](https://cloud.githubusercontent.com/assets/16397729/13028249/7ec54f12-d21e-11e5-9c61-babec2743db1.jpg)

**Comment by Torquemadra** [comment]
Checked on live and test environment, fully functional for me.

**Comment by SharpiesOfWar** [comment]
Hi. I just dropped the quest again and it came up with the correct person to speak to. We can close this.
