### ISSUE TITLE
Beastial and Giant Tactic Fragments [Tome Unlocks]

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4348]
I can get the unlocks(in ToK too) but it doesnt count them.
For example i got this Giant Tactic Unlock in ToK but it says 0/15.Same with Beastial.
![toufekiaaaa_085](https://cloud.githubusercontent.com/assets/16864486/13029105/3db61ea8-d28b-11e5-9fe4-2e3cd2eac0e7.jpg)
**They are not supported/implemented yet or...just bugged?**
Regards

**Comment by Ryanfawkez** [comment]
Tactic fragments aren't implemented yet.
