### ISSUE TITLE
[Sorc] "Swell of Gloom" tactic inflicts damage incorrectly

### ISSUE THREAD

**Issue by murmelon** [WarEmu/WarBugs#4352]
![primer](https://cloud.githubusercontent.com/assets/12655727/13030079/2d814546-d2a7-11e5-8856-48c5618fa379.jpg)

**Comment by ozarmidrashim** [comment]
So, what you're saying is that SoG adds damage directly to Gloomburst instead of being a separate, constant proc-type hit?

**Comment by murmelon** [comment]
SOG inflicted damage separately from GloomBurst, but deals to same damage like non critical GB.
So on pic, for "ROR server" must be 446 from tactic (like non critical GB) instead 260.
