### ISSUE TITLE
[ITEM] Casque of the Bandit Queen

### ISSUE THREAD

**Issue by Scrilian** [WarEmu/WarBugs#4353]
Somehow its bound on pick up and not bound on equip.
![valteri_009](https://cloud.githubusercontent.com/assets/16498708/13030177/1445d924-d2b2-11e5-83a9-19806212112f.jpg)

**Comment by Torquemadra** [comment]
#3961

you can have buddy playing auction house chicken to trade though

**Comment by Scrilian** [comment]
Huh, I can sell it and trade with auction trick. Shame I can't just trade it :c
