### ISSUE TITLE
[RvR] Tier 2 Order Keeps -Mandreds

### ISSUE THREAD

**Issue by Vandorkholme** [WarEmu/WarBugs#4354]
In Mandred's and CoT the trainers/vendor aggro radius is way too large and will aggro you in the lord's room. Its probably the same in the dwarf keep but I haven't been there since this bug started occurring.

**Comment by Torquemadra** [comment]
Fixed next. If additional problems elsewhere please log another ticket.

**Comment by Torquemadra** [comment]
#4084
