### ISSUE TITLE
Quest: One Too Many

### ISSUE THREAD

**Issue by Povel** [WarEmu/WarBugs#4356]
Unable to turn in this quest to the NPC named Fenrelis Minithain.

Might I add this was one of the NPC's that had one of the 25 kill quests that you could turn in for 5k exp.

**Comment by Torquemadra** [comment]
What does the quest say? There were other parts to this quest originally like getting a banner which have been disabled, this "should" be a kill 25 player only quest.

**Comment by Tiggonos** [comment]
that kill25 player quest war turned of with the last patch, as destro didnt have that quest. the banner quest is a pve quest on the same npc. turning in worked before the patch.

**Comment by Tiggonos** [comment]
- Two killcount quests for Order have been made unrepeatable, to balance out the amount of repeatable killquests for both realms in T3 (7 in total). These quests are 'Steeled for Slaughter' and 'One Too Many'.

**Comment by Torquemadra** [comment]
sigh.... fixing
