### ISSUE TITLE
Fehlendes Inventar und Aktionsleiste

### ISSUE THREAD

**Issue by tarsionia** [WarEmu/WarBugs#4358]
hallo,
seit gestern abend fehlen bei meinem DOK (Tantras) diverse Sachen aus dem Inventar, quest gegenstände und bezahl marken.
desweiteren werde ich mit 0 hp im spiel angezeigt und kann nicht normal ausloggen, da er immer sagt, das ich Tod sei.
es fehlen auch die Aktionen aus der aktionsleiste. wenn ich wieder welche rein setze und benutzen will, geht das nicht bzw er bricht sie einfach wieder ab.

anbei ein paar screenshots:

![warhammer online age of reckoning-02-14-2016 14-40-41](https://cloud.githubusercontent.com/assets/17233947/13034076/bcb9d7da-d32b-11e5-8a72-81e6d0f4fe42.jpg)
![warhammer online age of reckoning-02-14-2016 14-52-48](https://cloud.githubusercontent.com/assets/17233947/13034074/bcb5b876-d32b-11e5-8c07-444fe14b259c.jpg)
![warhammer online age of reckoning-02-14-2016 14-52-56](https://cloud.githubusercontent.com/assets/17233947/13034078/bcbe1d54-d32b-11e5-93f4-4b2c3256d7c2.jpg)
![warhammer online age of reckoning-02-14-2016 14-53-00](https://cloud.githubusercontent.com/assets/17233947/13034077/bcbc8818-d32b-11e5-83c2-86f46ae8ed65.jpg)
![warhammer online age of reckoning-02-14-2016 14-53-03](https://cloud.githubusercontent.com/assets/17233947/13034075/bcb8136e-d32b-11e5-8940-4bfddf376eda.jpg)

bitte um eine sehr schnelle hilfe.

vielen dank im voraus

tarsionia

**Comment by Evildoor** [comment]
Read the rules of the bugtracker.
