### ISSUE TITLE
Harbinger of Doom/Rune of Breaking

### ISSUE THREAD

**Issue by Blubberino** [WarEmu/WarBugs#4363]
Currently it is not converting Healing Power to Magic Power. Even though I tried it several times and checked stats with .getstat it didn't convert it. Since I'm not having any Item with magic power I can't test the other way around but I bet that doesn't work too.

Harbringer of Doom worked however with Crit and Int/Willpower.

Pic of .getstat with ontoggeld Harbringer of Doom

![laranaxas_000](https://cloud.githubusercontent.com/assets/16993024/13046860/8c87c33c-d3db-11e5-80af-372c57ee42b9.jpg)

**Comment by Kweedko** [comment]
so still no fix :(
