### ISSUE TITLE
Collision VS Players,Pets and NPC's

### ISSUE THREAD

**Issue by Povel** [WarEmu/WarBugs#4364]
I'm sure this has been posted many times before but the fact that Ranged classes such as SW or Engi or Squig herders are able to auto-attack trough walls and such ASWELL as their pets being able to COMPLETELY ignore any sort of obstruction and simply go right trough it and keep attacking you unless you actually get out of range of the pet's owner is just absolutely ridiculous.

This should easily go in the category of what you people call "Fundamental Game Breaking Bugs" but don't be mistaken; I could care less about getting a Griffon/Manticore - I am perfectly fine with 50 % mounts and couldn't care less as I too want nothing but the best for this game without any sort of reward other than being able to play it.

As much as I love the work that you guys put into making this game better; this issue has to be adressed sooner rather than later, and most definetly before you think about putting T4 in the game =/

**Comment by Ryanfawkez** [comment]
https://github.com/WarEmu/WarBugs/issues/2781
Closing.
