### ISSUE TITLE
The Shadowlands - Rock of Galirian (Dark elf chapter 5)

### ISSUE THREAD

**Issue by Aluviya** [WarEmu/WarBugs#4365]
Some of Galirian Watcher and Galirian Defender are fighting eachother even though they are supposed to be allied. Also it seems only a few of them are fighting, take a closer look at the Galirian Watcher on the right side of the picture.
![aluviya_002](https://cloud.githubusercontent.com/assets/17249318/13046941/fcb7d7d2-d3db-11e5-847a-3cefae4d1838.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
