### ISSUE TITLE
[QUEST] Tarred Dwarf 

### ISSUE THREAD

**Issue by Asherdoom** [WarEmu/WarBugs#4367]
Half part is doabl just clicking the tree... rope is missing totally i suggest to put it aside the tree to make quest doable.

i leave here screen of quest text and place! :)

![rhen_002](https://cloud.githubusercontent.com/assets/16918614/13055151/767d9308-d3ec-11e5-8d6d-184f3248b456.jpg)
![rhen_003](https://cloud.githubusercontent.com/assets/16918614/13055156/78db9852-d3ec-11e5-9232-efe9f372bde0.jpg)

**Comment by foxbeep** [comment]
I've completed this quest before
Not sure if the problem was caused by a patch since my last attempt but I managed to rescue him a number of weeks ago

**Comment by DanaBloodkiss** [comment]
It's behind you ... closed.
