### ISSUE TITLE
[Black Fire Pass-NPC] Weird spawn location

### ISSUE THREAD

**Issue by saupreusse** [WarEmu/WarBugs#4370]
![shirayha_168](https://cloud.githubusercontent.com/assets/16520352/13058386/3e10bfd6-d423-11e5-9708-148c4be19dc8.jpg)
![shirayha_169](https://cloud.githubusercontent.com/assets/16520352/13058391/437a3ba0-d423-11e5-86ef-f2c47101ae4e.jpg)
Looks like these 4 dwarfs are lost in the mountains.

**Comment by DanaBloodkiss** [comment]
Thanks for the report!Though there is nothing wrong with it :)
