### ISSUE TITLE
[Badlands-NPC] Wrong spawn location

### ISSUE THREAD

**Issue by saupreusse** [WarEmu/WarBugs#4371]
![shirayha_170](https://cloud.githubusercontent.com/assets/16520352/13058497/e2c8c74e-d423-11e5-9ef6-2e9ca58d9141.jpg)
![shirayha_171](https://cloud.githubusercontent.com/assets/16520352/13058498/e3af399a-d423-11e5-92ba-8dfdeda4297f.jpg)
This skeletal prospector spawns inside the warcamp and gets killed by npc guards as soon as it respawns.

**Comment by DanaBloodkiss** [comment]
I don't see the problem , where should it be spawned?

**Comment by Evildoor** [comment]
No confirmation, closing.
