### ISSUE TITLE
[influence item]thickmuck mantle wrong stat

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#4372]
![antigonos_012](https://cloud.githubusercontent.com/assets/13809443/13060326/e0306b74-d430-11e5-8942-d6cae47cb5f5.jpg)
has willpower toughness and then melee crit. should be heal crit. (for salvation wp)

**Comment by Ryanfawkez** [comment]
Thickmuck Painmantle (DoK variant) currently lacks a 1% crit of any kind. Can't find the original item's stats.

**Comment by Tiggonos** [comment]
so does painmantle also have healing stats and did now get 1% melee crit? why not fix the items alltogether?
