### ISSUE TITLE
Chosen PQ inf rewards

### ISSUE THREAD

**Issue by roadkillrobin** [WarEmu/WarBugs#4376]
Tons and tons of PQ influence rewards for Chosen class are Zealot Charms.

**Comment by Evildoor** [comment]
Item names and related chapters, please.

**Comment by roadkillrobin** [comment]
I think its all Sheilds on all PQ rewards
Den 16 feb 2016 8:09 fm skrev "Evildoor" <notifications@github.com>:

**Comment by roadkillrobin** [comment]
Dark Elf Chapter 12, Newshore Effigy
Dark Elf Chapter 14, Skull of Statecraft
Greenskin Chapter 14,  Effigy of da Plauge

These are all in t3 no shields, just Charms.

**Comment by roadkillrobin** [comment]
t1
Greenskin Chapter 1, Recroot Skull
Greenskin Chapter 4, Goldfist Effigy
Choas Chapter 1, Opportunist Skull 
Choas Chapter 2, Skull of the Passage
Choas Chapter 3, Plundered Skull
Dark Elf Chapter 1, Recrudecent Effigy 
Dark Elf Chapter 3, Skull of Trammels
Dark Elf Chapter 4, Denrazer's Effigy

**Comment by roadkillrobin** [comment]
t2
Greenskin Chapter 5, Tainted Creek Effigy
Greenskin Chapter 7, Effigy of Bar Dawazbak
Greenskin Chapter 8, Firebrew's Fightin' Effigy
Choas Chapter 6, Reaper's Effigy
Chaos Chapter 8, Plaugewood Focus
Choas Chapter 9 Blightstone Focus
Dark Elf Chapter 6, Necrolith Skull
Dark Elf Chapter 5, Senburian Effigy
Dark Elf Chapter 8, Coaxer Effigy

And thats all of em i think

**Comment by NorKalli** [comment]
All long since fixed
