### ISSUE TITLE
avelorn lv 1 hero incorrect spawn[npc]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#4384]
around 31k-47k

![tesq_316](https://cloud.githubusercontent.com/assets/7527415/13078671/cd695ef2-d4c0-11e5-931a-9a4ab7b093c0.jpg)

**Comment by Torquemadra** [comment]
mob is correctly placed.

http://warhammeronline.wikia.com/wiki/Final_Rest..._Again
