### ISSUE TITLE
fiendish talon unlock encounter a deamon price [tome]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#4385]
![tesq_315](https://cloud.githubusercontent.com/assets/7527415/13078791/53bad4e0-d4c1-11e5-9717-c83b09a394c6.jpg)

**Comment by Evildoor** [comment]
#3865 is supposed to be fixed...

**Comment by Tesq** [comment]
didn't find that post (deamon vine what it mean?) it's from some days ago it should so.

**Comment by DanaBloodkiss** [comment]
Fixed in next!Thanks for the report.
