### ISSUE TITLE
KOTBS influence rewards are the same (T2, gloves)

### ISSUE THREAD

**Issue by FearTheGriff** [WarEmu/WarBugs#4388]
In the troll country empire warcamp, the influence rewards are exactly the same for the first set of gloves for KOTBS
![tylo_000](https://cloud.githubusercontent.com/assets/16886300/13088312/a87f5cae-d4e3-11e5-947a-9d087335ba81.jpg)
![tylo_001](https://cloud.githubusercontent.com/assets/16886300/13088316/ac1d69fa-d4e3-11e5-8a73-9d500d9bf085.jpg)

**Comment by JamGrif** [comment]
.
