### ISSUE TITLE
Soldier's Healing Draught unusable at RR21

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#4390]
I'm way above the RR requirement but all I get is:
"You need to be a higher renown rank to use this item."

Looks like the requirement is set to R21 and not RR21. (or both together)

**Comment by taccr** [comment]
Same goes for Soldier's Stimulant Potion.

I just hit R21 and both potions work now. Not working for lower ranks than 21 though.

**Comment by genisaurus** [comment]
Potions should show level requirements in next patch.
