### ISSUE TITLE
Choppa rank 15 wrong new tactic

### ISSUE THREAD

**Issue by DrBullFrog** [WarEmu/WarBugs#4392]
! Just hit lvl 15 on my Choppa. According to waronlinebuilder.org I should have gotten the new tactic "Don't Hate Da Choppa". Instead I got "Don't Wanna Live Foreva" which is only useable at rank 33 or more.

![mordok_002](https://cloud.githubusercontent.com/assets/17291851/13106747/326ccaf6-d56a-11e5-84da-29e229d65a1d.jpg)

**Comment by milosxe** [comment]
http://www.returnofreckoning.com/forum/viewtopic.php?f=11&t=8768
