### ISSUE TITLE
Loot while in a party

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4393]
Cant loot MOBS while in a party anymore.Started occurring after yesterdays patch.

**Comment by Pxl555** [comment]
I would like to add from my observation , you can still get "some" loot but for some reason you cant loot trash items and more importantly you can NOT scavenge while in a party because of it , Works normally while alone

**Comment by Evildoor** [comment]
Hotfix 17/09
[Groups]
- Fixed an issue causing groups and warbands to be incapable of looting.
