### ISSUE TITLE
The Burning Windmill PQ Order

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4396]
After Changelog 17.02.2016
- [X] ~~No stage announcement.~~
- [X] ~~No kill counter.~~
- [X] ~~Cant gain influence anymore.~~
- [ ] Stage 2 does not work as it should.(Barriers dont open,so cant attack MOBs).**Unless you have special ability to pull them out.**
- [X] ~~Stage 3 does not work(Does not spawn the final MOBs).~~

**Comment by Soulwhisper** [comment]
After Changelog 25.02.2016
- [ ] Stage 3 does not work(Does not spawn the final MOBs).

**Comment by Damiel126** [comment]
The toons for the chaos sorcerer hero and flamer champions are loading as naked dwarfs.

In addition to being able to pull the champions, you can also use AOE damage to get them out of the bubble.

Stage 3 does appear to work at present.

The blue bag reward is broken - it has no item, just crafting gear.

![abigaele_005](https://cloud.githubusercontent.com/assets/10399547/13547047/6a33e39e-e315-11e5-95b9-9263b5fc21c5.jpg)
![abigaele_008](https://cloud.githubusercontent.com/assets/10399547/13547048/6a34287c-e315-11e5-9a75-8f332bd48fa3.jpg)
![abigaele_009](https://cloud.githubusercontent.com/assets/10399547/13547049/6a348146-e315-11e5-9569-09cc4625424a.jpg)

**Comment by Soulwhisper** [comment]
@Damiel126 Loot tables are not ready yet :) Thanks for updating it though.

**Comment by Soulwhisper** [comment]
**UPDATE** 
- [ ] After Stage 3 PQ starts earlier than it should
![toufekiaaaa_007](https://cloud.githubusercontent.com/assets/16864486/13610894/86a37256-e568-11e5-9c2e-5a0e0c465ff6.jpg)

**Comment by Soulwhisper** [comment]
![toufekiaaaa_012](https://cloud.githubusercontent.com/assets/16864486/14062755/76391e6c-f3b3-11e5-9dea-5699cc96bcae.jpg)
- [ ] Stage 3 MOBS stuck and cannot be killed.Can finish PQ.

**Comment by Soulwhisper** [comment]
#7144
