### ISSUE TITLE
The Webworks PQ Order

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4399]
~~After Changelog 17.02.2016~~
- [X] ~~**Stage 1** Works~~
- [x] ~~**Stage 2** Cant interact with Cocooned Citizens.~~

**Comment by Evildoor** [comment]
Was it possible before the patch?

**Comment by Soulwhisper** [comment]
No but it should after patch.

**Comment by Soulwhisper** [comment]
- [ ] Now stage 1 doesnt work at all.

**Comment by wargrimnir** [comment]
This area was updated last patch, there is a much smaller section that doesn't display the PQ. This is because the area directly above it is near a Destro PQ. They can't overlap unfortunately.

**Comment by Soulwhisper** [comment]
@wargrimnir So this cant be fixed at all?

**Comment by wargrimnir** [comment]
Well, it could, just tricky getting the maps to line up properly. At this point it would get a trivial flag if the issue stays open. The entire back end of the cave wasn't covered before, now it's just that spot.

**Comment by Soulwhisper** [comment]
Got it...lets leave it for another time!
Either way PQ is fully Working!
