### ISSUE TITLE
'Horrors of War' cannot be delivered

### ISSUE THREAD

**Issue by JeFawk** [WarEmu/WarBugs#44]
Horrors of War cannot be delivered.

![image](https://cloud.githubusercontent.com/assets/7268697/2908018/aed40350-d622-11e3-9850-b703f85dd765.png)

Thanks @Fikatind

**Comment by Reggaewaldo** [comment]
Tested on the Dev server. It is working and should carry over to live if it has not done so already.

This can be closed.
