### ISSUE TITLE
The Norse are Coming! PQ Order

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4400]
After Changelog 17.02.2016
- [X] ~~No stage announcement.~~
- [X] ~~No kill counter.~~
- [X] ~~Cant gain influence anymore.~~

**Comment by Soulwhisper** [comment]
- [ ] If you spam Defenders Corpses at Stage 1 you can gain influence.

**Comment by Evildoor** [comment]
You mean that you can click the same corpse multiple times, while you should be able to click each one only once?

**Comment by Soulwhisper** [comment]
Yes.Clicking the same corpse multiple times give you +50 influence and you can spam it for like 9-10 times then it stops giving Infl.

**Comment by Evildoor** [comment]
#424

**Comment by Soulwhisper** [comment]
Oh ok if that counts for PQs too then ok.

**Comment by Soulwhisper** [comment]
- [ ] Stage 2 and Stage 3 doesnt work.

**Comment by Soulwhisper** [comment]
- [ ] Stage 1
The Norse invaders must be stopped here! Slay the Sea Dogs, destroy their supplies and burn their tents. Leave them nothing with which to gain a foothold on Empire soil!

**-    Norse Tents Burned - 0/4
-     Norse Supplies Destroyed - 0/14
-     Norse Sea Dogs - 0/40 **

- [ ]  Stage 2
Gather torches from the campfires atop the hill and use them on the Norse Boats to set them aflame. Destroy any Norsemen who try to stand in your way.

**-    Norse Boats Burned - 0/4
-     Norse Plunderers - 0/8
-     Timed: 6:00 Minutes **
