### ISSUE TITLE
Ruins of Schloss von Rubendorff PQ Order

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4401]
After Changelog 17.02.2016
- [X] ~~No stage announcement.~~
- [X] ~~No kill counter.~~
- [X] ~~Cant gain influence. (??anymore??) **Dont know if you could before patch though**~~

**Comment by Soulwhisper** [comment]
- [ ] Stages dont work.

**Comment by Soulwhisper** [comment]
![toufekiaaaa_013](https://cloud.githubusercontent.com/assets/16864486/14062851/c9b3dd18-f3b6-11e5-8bb4-35beb9c85dd3.jpg)
Looks like timers and UI for the chest is really messed up on this PQ.

**Comment by Soulwhisper** [comment]
**_Stage 1_**
Kill the Norse Ravagers and liberate Schloss von Rubendorff!

-     **Norse Raiders - 0/15**
-     **Norse Ravagers - 0/20 **

**_Stage 2_**
Tear down the Raven Host banners and reclaim Schloss von Rubendorff for the Empire!

-     **Claim the Skulltaker Banner - 0/1**
-     **Claim the Banner of Lostsight - 0/1**
-     **Timed: 10:00 Minutes **

**Each banner is guarded by a named mob, Pergris Lostsight at the Banner of Lostsight and Faar Skulltaker at the Skulltaker Banner, and two Norse Ragelords that must be defeated before the objective can be claimed. Griffon Soldiers will spawn during this stage and attack any enemy mobs they encounter, including those protecting the two banners.**

Stage 3 
Defeat the leader of the Norse warriors and let them get a taste of failure.

-     **Fjeldrin the Savage - 0/1**
-     **Timed: 10:00 Minutes **

**Comment by Frubertlives** [comment]
Kills still not counting.

**Comment by Soulwhisper** [comment]
Yes i confirm.Kills dont count on Stage 1 so we cant proceed.

**Comment by Bakkoda24** [comment]
Attempting to do this on 6/30/16 at 8:28pm EST.

Wasn't able to get past the first stage. PQ Tracker was only indicating 0/15 for Ravagers, did not indicate tracking for killing Raiders. Based on the comments above me, this appears to be an incorrect value for the Ravagers.

Group of 2 was unable to progress past the first stage.

Apologies for not including screenies. Writing this comment after I logged off and it slipped my mind.
