### ISSUE TITLE
Suderholm PQ Destro

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4403]
After Changelog 17.02.2016
- [X] ~~No stage announcement.~~
- [X] ~~No kill counter.~~
- [ ] Cant gain influence. (??anymore??) **Dont know if you could before patch though**

**Comment by Luth-RoR** [comment]
Newer report: https://github.com/WarEmu/WarBugs/issues/7321

**Comment by Soulwhisper** [comment]
LOL...yeah that was old.Good job.
