### ISSUE TITLE
HP and Morale glitch

### ISSUE THREAD

**Issue by Shalliar** [WarEmu/WarBugs#4407]
Just after completing "Great Tribes" quest in Ostland I was returning to my base (first Chaos camp in Ostland - Ferlangen, I think) and suddenly got this:
![2016-02-17_00004](https://cloud.githubusercontent.com/assets/17254643/13119437/38d96084-d5ba-11e5-97f7-cf1ad537d86b.jpg)

1) Wounds showing incorrectly.
2) Full morale, though I wasnt in combat.
3) Tactic didnt ended.
4) I couldnt summon my mount.
Relogging solved this problem, but anyway, it was quite strange.

**Comment by Evildoor** [comment]
I'm 95% sure it's #1810.
