### ISSUE TITLE
Guild experience with max level chars

### ISSUE THREAD

**Issue by sh0tyy** [WarEmu/WarBugs#4408]
Greetings,

I recently created a new guild which has my alts in it only at the moment with members lower than six.
Now my problem is that when I play with my main char which is level 32 and has capped the experience bar. I don't know if this is intentional or not but I believe even if my char has capped its experience level doing other things such as quests,oRvR,scenarios I should be contributing experience to the guild, which is not happening. If I joined on my alt char and I kill a mob I can see the experience is being contributed immediately. 

So my question is, why isn't my main char who is level 32 not able to contribute to the guild experience leveling from quests, RvR, Scenarios etc? Is this intentional or a bug which is being looked at ?
I can't remember how things were in the live server, so here I am asking for some information.

Thank you!

**Comment by Soulwhisper** [comment]
Your 32 level character does not gain anymore Xp so cant pass it to Guild.

**Comment by sh0tyy** [comment]
It looks like it is working now.
Thanks!
