### ISSUE TITLE
Guild Banner

### ISSUE THREAD

**Issue by Chummi** [WarEmu/WarBugs#4409]
so i want to save my design, press Save and got this:
"Saving this Heraldry is permanent and will cost you 01704. Do you really want to save?"

i press Yes, nothing happens and banner stays. i relogged and tried it on guild officier and guild lead

any idea?

**Comment by nalgol** [comment]
we don't know how to send the correct price values yet you need 10 g to reserver your banner for the first time after that its 500 gold you shouldnt change your banner like your underware ^^

**Comment by Chummi** [comment]
well we made one pre patch in t2 with was given. now you implemented the full kit and i tried to set it up properly for the first time. i honestly refuse to pay 500g to "change" something we made with not even 10% of the possibilities just to see if it works back then. a reset to all banners before the implementation would have been cool.

**Comment by Soulwhisper** [comment]
**Reset Heraldry** button doesnt work.
