### ISSUE TITLE
Only receiving about 1/3rd of kill credit in SCs

### ISSUE THREAD

**Issue by Dirox-Hirox** [WarEmu/WarBugs#4410]
I have noticed that I (and others,) are now receiving almost no credit for kills after the patch on 2/17/2016.  Here is a screenshot of a Battle of Praag to show what I mean, our parties moved together, and even sometimes if I got the DB I didn't receive credit for the kill on the chart, quests, or receive the 5 points for the kill.

![hirox_007](https://cloud.githubusercontent.com/assets/7065919/13130267/d3950574-d5b0-11e5-9d9b-6590d4f470e9.jpg)

If you add up the deathblows, there are much more of them than there are kills by an extreme amount.

**Comment by Tiggonos** [comment]
fixed with latest hotfix.
