### ISSUE TITLE
PQs after latest update  2/17/16

### ISSUE THREAD

**Issue by hrothgar22** [WarEmu/WarBugs#4412]
Ok, so I have been testing this stuff for the past few hours and here is what I have found

The PQs are working correctish, from what I can tell the PQs in the not so farmed places Dwarf T1 and T2 seem to work correctly still, but after you complete the PQ and get the loot box or fail the PQ the reset timer ticks down but it does not reset, I figure this is what is causing the other PQs to look broken, They was completed once and then they went thru the reset process they freeze up or just don't reset, I did get a message from the server twice after completing the PQ successfully, something along the lines of

<PQ Name> says: missing context something, (not exactly sure what it says but I know I got the message on more than 1 PQ once the reset timer started, ill complete another one real fast and tell you exactly what the message says so hopefully it will lead to a fix)

Hope all this info helps

-Rinhart Griffonbane

**Comment by Torquemadra** [comment]
Virtually all pqs stalling on reset, live and dev, getting NullReferenceException was thrown the object will be destroyed error at end of PQs. Tried several in all pairings.

**Comment by Soulwhisper** [comment]
![pqs](https://cloud.githubusercontent.com/assets/16864486/13151553/47fc24fc-d673-11e5-880d-7b85e816080d.jpg)
Chest has visual bug.
Stages are not synced with the timer.
![paterellas_005](https://cloud.githubusercontent.com/assets/16864486/13151656/ccfe5062-d673-11e5-9227-049cb99ab6fa.jpg)
Finally PQ scoreboard does not show other players(scores) participated in the PQ.
And you cant open the chest.

**Comment by wargrimnir** [comment]
Fixed a long time ago.

**Comment by Soulwhisper** [comment]
I dont know if it was already stated somewhere else but i have to add that **if you enter a PQ while its in Finish/Reset stat**e the PQ Tracker gets stuck on Finished 0:00 and doesnt reload when PQ resets. You have to do it manually with /rel command.

**Comment by Luth-RoR** [comment]
Going to close this; Those visual UI errors are probably fixed with client access.
