### ISSUE TITLE
stealthing setback

### ISSUE THREAD

**Issue by GankbusOsmium** [WarEmu/WarBugs#4413]
http://www.twitch.tv/stenchypow/v/46763765

02:07:40

Setback on stealth is not working properly, makes you able to stealth while being focused.

**Comment by Soulwhisper** [comment]
http://www.returnofreckoning.com/forum/viewtopic.php?f=75&t=11502

**Comment by Torquemadra** [comment]
That was solid focusing in the vid and the WH did stealth (though it was hard to see anything in that UI mess), noticed it myself in scenarios now looking for it. Tested and no set back taking place.

**Comment by Chummi** [comment]
how is this UI a mess and what do i need to change that the video counts as an evidence? i always thought it is pretty clean and from my understanding you can see everything. honest question here.

**Comment by ozarmidrashim** [comment]
Incognito is set back 250ms on a 50% chance (fragile spell: normal chance is 25%). I was able to stealth on my test server successfully while under attack by 12 mobs.

Please advise of correct handling if it is different.

Also please bear in mind this report:

https://github.com/WarEmu/WarBugs/issues/1754

**Comment by ozarmidrashim** [comment]
Fixed on live.
