### ISSUE TITLE
Talisman making/salvaging inventory

### ISSUE THREAD

**Issue by TheSOcialN** [WarEmu/WarBugs#4417]
While i was doing some salvaging/talisman making last night i had a weird bug, item cliping threw each other i had to move them from craft inventory to backpack to get them but it was totally bugging (some item where loosing there icone as well) also some talisman i made dissapear in the process.

Hope it help a bit, i'll try to get some print screen next time i see that bug.

**Comment by TheSOcialN** [comment]
http://imgur.com/XYAMT5G

Here you can see that the item lost his icon

**Comment by oddmage** [comment]
I have the same problem. Moving them slots brings the icon back, doesn't need to be bag.
