### ISSUE TITLE
SW's tactic Replenishing Strikes doesnot work on running

### ISSUE THREAD

**Issue by krisolyub** [WarEmu/WarBugs#4420]
Hello! 
SW's tactic Replenishing Strikes should give AP when crit happens. But there is no AP adds when SW is running. On old game version it worked.

**Comment by ozarmidrashim** [comment]
Just to get this straight: you're telling me that while you are moving, this tactic doesn't give any AP?

**Comment by krisolyub** [comment]
Then tactic works good. I remember at old game you could make some dots on enemy and use skill "run", but get AP from dot's tics. 
But if it should proc only on direct damage, then it works propertly.
