### ISSUE TITLE
Nurglings quest mobs

### ISSUE THREAD

**Issue by kodemonkeh** [WarEmu/WarBugs#4421]
Hi there. the Order T1 Nordland Quest - Nurglings does not appear to be able to be completed.
The area highlighted for the quest completion does not have the correctly named mobs to kill.
The mobs at the location are "Nurglings" when they need to be "Bilerot nurglings".

**Comment by Ryanfawkez** [comment]
Bilerot Nurglings were removed due to a merged droptable of the T4 variant mobs that used to spawn in Bilerot Burrow, a T4 Destruction dungeon in their capital. They dropped rare dyed at a pretty quick rate, and this shouldn't have been the case for the level 9-10 variants.

**Comment by Torquemadra** [comment]
Amended quest to count the replaced nurglings, fixed next patch
