### ISSUE TITLE
Chat permissions are not working

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#4422]
- [X]  As an officer i cant unassign banners from other players in guild.
      Managment Tabs are checked to have full control but it doesnt work.

**Comment by nalgol** [comment]
gonna look into it

**Comment by Soulwhisper** [comment]
Chat permissions dont work either

**Comment by Evildoor** [comment]
Changelog 30.03.2016
[Guilds]
- Remove standard bearer works now with offline members.

**Comment by Luth-RoR** [comment]
Officer chat permissions seem to be coded for the first two guildranks, not linked to the permissions themselves.

**Comment by Natherul** [comment]
oh, this is fixed since a while back. thanks for the report
