### ISSUE TITLE
probleme de guilde 

### ISSUE THREAD

**Issue by alariouch** [WarEmu/WarBugs#4425]
bonjour , une fois de plus je me tourne vers vous signaler un très gros problème , en effet mon personnage et deguilder a chaque restart serveur. cette situation est vraiment très handicapante pour moi car je ne peut  n'y rejoindre une guilde n'y en créer une ... sil vous plait , pouvez vous essayer de régler ce problème? sinon jais une solution , jais un autre archimage qui lui na pas ce problème de deguildage permanent , donc je vous propose de transférer l’intégralité  de mon personnage buguer vers celui qui ne l'ai pas ... vous comprendrai je pense qu'avec un personnage full renommée full influence et surtout full stuff devastater/dueliste je n'ai pas envie de reprendre tout a zéro. sil vous plait aider moi.

**Comment by Evildoor** [comment]
Read the rules of the bugtracker.
