### ISSUE TITLE
butcher

### ISSUE THREAD

**Issue by hengag** [WarEmu/WarBugs#4426]
I am sorry for bad english . but the ability of the animals extracted butcher unsold NPC

**Comment by Evildoor** [comment]
Uh, what?

**Comment by Soulwhisper** [comment]
He means that you cant sell seeds that you take from buthering to NPCs .

**Comment by noisestorm** [comment]
>I am sorry for bad english . but the ability of the animals extracted butcher unsold NPC

If you are unsure in english, ask a friend to translate it or write it in your native language pls.

**Comment by Evildoor** [comment]
No explanation, closing.

> write it in your native language pls.
Uh, no. I'm closing non-english reports on sight together with Google Translate ones.
