### ISSUE TITLE
Wrong MOB Level

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4427]
These MOBS after server restart were 30lvl.I killed them once and after they respawned they were 29 LVL.Killed them several times but keep spawning 29 level.
![mobs](https://cloud.githubusercontent.com/assets/16864486/13183799/2ffee032-d741-11e5-8e8c-103ff79bc49d.jpg)

**Comment by Vandorkholme** [comment]
A lot of mob spawns have level variation, this isn't a bug.

**Comment by Soulwhisper** [comment]
Dont know.
