### ISSUE TITLE
Kots bug auras

### ISSUE THREAD

**Issue by Tholkienn** [WarEmu/WarBugs#4430]
From about 3 days, i have a bug with my auras: can't, sometime, put more than 2.

It seems to be link with the guard, because it's always when i switch grp, leave a grp, et let my guard on.
The only way is to reconnect, put  it's a little shitty when you just drink pots.

**Comment by noisestorm** [comment]
Try to group with someone and switch your guard on them when this occurs. Let him remove the guard by himself and see if you can turn on the third Aura again

**Comment by Tholkienn** [comment]
I try, but the switching guard don't work, i have to dc rc to have my auras.

**Comment by Tesq** [comment]
is not linked  to guard , it's totaly random , i can't figure it how it work, it basically happen after a lots of aura swaps while doing sc and/or after even 1 swap but i cannot find the core of the bug.

**Comment by Tholkienn** [comment]
Ok, it's link to auras

**Comment by grunbag** [comment]
Aura have changed
