### ISSUE TITLE
ToK Completed Quests

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4431]
![toufekiaaaa_089](https://cloud.githubusercontent.com/assets/16864486/13195977/97ab6c40-d7c9-11e5-9d68-b4ff92fc578b.jpg)
ToK no longer shows completed quests with "Xmark" after latest patch.They cannot be sorted as completed,too.

**Comment by Evildoor** [comment]
Are you sure this is not #2805?

**Comment by Soulwhisper** [comment]
I think thats it but before the patch it was working fine. Strange
