### ISSUE TITLE
WL pet dmg

### ISSUE THREAD

**Issue by Skellort** [WarEmu/WarBugs#4432]
Hi Team

I had a fight vs a WL Pet , the Problem is the dmg.
My Character has 4430hp, i looked at the dmg report and saw that the Pet does all together 722hp dmg on me and killed me in just 17 seconds, dmg report says he did 5 attacks but i got much more dmg in this time.
I take some pics of dmg report hope u can tell me whats wrong thank u
![wl4](https://cloud.githubusercontent.com/assets/17030555/13196094/230ea482-d7c5-11e5-9066-eb422390f323.jpg)
![wl1](https://cloud.githubusercontent.com/assets/17030555/13196095/26f8294c-d7c5-11e5-9f78-ff8e07794927.jpg)
![wl](https://cloud.githubusercontent.com/assets/17030555/13196096/2aae9db4-d7c5-11e5-9637-e97c57096b40.jpg)
![wl5](https://cloud.githubusercontent.com/assets/17030555/13196242/19052bc4-d7c9-11e5-85d3-c97b7c1e478d.jpg)

**Comment by noisestorm** [comment]
Not sure what to take from that log? There is literally not one attack of any Lionpet shown in there? Theres just an engie dot ticking but thats it. So i assume you want to tell us, that the pet dmg you received is not shown anywhere in there?

**Comment by Skellort** [comment]
K thats right engie dot ticks, but why the WL killed me. The report show that he never did any dmg.

**Comment by ozarmidrashim** [comment]
Attacks from pets are filtered as attacks from NPCs....

**Comment by Evildoor** [comment]
Closing since we failed to find anything suspicious here. Also, i can't speak for everyone, but for me this is one of the cases when logs in non-English seriously hinder my ability to comprehend them. I don't see anything resembling WL pet attacks here - is this because they are not here, or is this because i don't understand the language?
