### ISSUE TITLE
ToK unlocks. Title "The Liberator"

### ISSUE THREAD

**Issue by ShanellRoR** [WarEmu/WarBugs#4433]
![kritz_060](https://cloud.githubusercontent.com/assets/17355822/13197118/f07fad38-d7f4-11e5-9a67-a06cbc44c2e7.jpg)
"Now what appears"
Champion mob killed. He dropped a medalion - "Tarnished Medal", which I should examine. But it's not examanable, so title is not available.

**Comment by Lheana** [comment]
I think this issue is now fixable. Tarnished Medal is still lootable, but nothing happens when right-clicking on it.

**Comment by Lheana** [comment]
Equiping the 'Tarnished Medal' triggers the title, but not the unlock 'Not What It Appears'. Must kill again the orgre tyrant 'Graw Leadgut' to have the unlock.
