### ISSUE TITLE
"Chaotic attunement" tactics works not as intendent.

### ISSUE THREAD

**Issue by ShanellRoR** [WarEmu/WarBugs#4434]
It says, that summoning daemons will not cost any AP, but in game it reqires same 55AP as without that tactics.
![zechariah_112](https://cloud.githubusercontent.com/assets/17355822/13197164/7af61834-d7f6-11e5-9c62-8d48b80d0069.jpg)

**Comment by Evildoor** [comment]
> It says, that summoning daemons will not cost any AP

Wrong. This tactic does two things:
1) Reduces cast time of 3 summoning abilities from 2 seconds to 0. Their AP stays the same.
2) Reduces AP cost of "Resummon" ability from 60 AP to 0.
