### ISSUE TITLE
Lost buffs and crafting progress after relogs, crashes etc

### ISSUE THREAD

**Issue by Specialpatrol** [WarEmu/WarBugs#4435]
I guess this issue is something that you're already completely aware of...

But would it be possible to fix it so you don't loose growing seeds (in Cultivation) and long-term buffs from potions (armor, stats etc) whenever there's a crash, restart or disconnect from server - or whenever you simply log out before seeds have been harvested and buffs have expired? 

It would be greatly appreciated.

**Comment by Evildoor** [comment]
#2347
