### ISSUE TITLE
Kill Collector Quests broken after patch on 2/20/16

### ISSUE THREAD

**Issue by Bombatta** [WarEmu/WarBugs#4436]
The kill 20 and 25 players quests in High Pass at least...  They fill almost instantly instantly in T3 scenarios and the Gears of War medal quest fills much quicker than the number of kills you get ...  It went from 0 0 0 to 30 9 7 and we only had like 10 kills.  All of this in scenarios tested

**Comment by phsampaio** [comment]
I'm having the same problem. Killing quests for T2 and T3 filling up almost immediatly. Gears of WAR also filling up too quick.

**Comment by Nekkma** [comment]
It seems you get the entire groups credit for each kill. In a scenario each kill advance the quests with 6. When we tried it later outside, in a 2 man group, each kill advanced the queast by 2.

**Comment by ozarmidrashim** [comment]
Fixed.
