### ISSUE TITLE
I got 21 lvl T1 for killing boss

### ISSUE THREAD

**Issue by Ail07** [WarEmu/WarBugs#4437]
I got 21 lvl for killing bosses T1 was 4 level, after the murder of the boss in Nordland got a lot of experience, and became a chicken!

**Comment by phsampaio** [comment]
Got from 28 (half-way to 29) to 32 after killing hero from DoK kill quest. It showed I gained about 457,000 xp.
Was gaing normal rested xp a few minutes before the quest.
Char name:  Dalborga (SW)

**Comment by Ail07** [comment]
There's even a quest not want to get rags got a problem (
Character Warpop

**Comment by Ail07** [comment]
for the murder of Lord т2, prokachatsya from 20 to 32. Elf fortress. Character Dast

**Comment by ozarmidrashim** [comment]
Fixed.
