### ISSUE TITLE
[Quest(s)] T2 Elf WC Scouting Quests

### ISSUE THREAD

**Issue by Povel** [WarEmu/WarBugs#4438]
These quests are able to be immediately turned in after you take them from Katmis Shattersword in the T2 Order Elf Warcamp.

Pretty sure you gotta go to the actual BO's to complete them no? ;o

Also Destruction Warcamp have no equivalent version of these quests as far as I could see.

**Comment by Evildoor** [comment]
Quest names?

Also, there is no mechanism to determine the area for quest purposes yet, that's why we have this, and why kill quests can be done anywhere.

**Comment by Evildoor** [comment]
No response, closing.
