### ISSUE TITLE
Receiving items from Destro classes (on Order) since patch 20/02/16

### ISSUE THREAD

**Issue by phsampaio** [WarEmu/WarBugs#4440]
Since the patch of 20/02/16, I am being rewarded with items for Destro classes while playing on Order. Apparently these are all level 33, and are only after killing players (not on mobs from what I can tell). 

Until now, I got a chosen glove and a magus one.

**Comment by gruch** [comment]
I'm playing a swordmaster. In one hour of level up, I am being reward with 3 destro classes item on mobs in Saphery. Level 29 stuff (Grim punchas, frenzied focus...).

**Comment by ozarmidrashim** [comment]
Fixed.
