### ISSUE TITLE
Influence Bar

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4441]
-  By the time it is implemented the only problem is that it **does not ALWAYS** change Chapter when you enter other PQs or RvR Lakes/WCs.

**Comment by nalgol** [comment]
i know the packet acts very strange but i needed it to display publicquests right so untill we figure out why chapters donet update on the client we have to live with it

**Comment by Soulwhisper** [comment]
- [ ] After several shutdowns of the server Influence bar doesnt want to appear.
![bar](https://cloud.githubusercontent.com/assets/16864486/13245260/ace27d86-da14-11e5-9f28-dde4280c4cc9.jpg)

**Comment by Soulwhisper** [comment]
After further testing i found out that if you create new Character the Influence Bar goes buggy by it self(wont appear at all).
Like you said packet acts very strange.

**Comment by Soulwhisper** [comment]
Actually i stayed there till stage 2 resets.And guess what.UI appeared but it was stuck to : Resseting in 0:00 and it stays like that forever.

**Comment by Soulwhisper** [comment]
Yes...even more testing i found out that it doesnt show up all the times.You have to force it somehow(Go to a warcamp to force the RvR T(X) bar to show up) to make it work for chapters too.

**Comment by Soulwhisper** [comment]
Or to go to a specific area outside a PQ to trigger it.
