### ISSUE TITLE
Guild>Recruit>Search

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4446]
![phantomas_009](https://cloud.githubusercontent.com/assets/16864486/13203063/cd33f29a-d8b6-11e5-93a2-586de26c082a.jpg)
- [ ] If you hit Search button as it is without adjusting any of the settings it breaks the button and cant be pressed again unless you /rel or relog.

**Comment by Evildoor** [comment]
#1564?

**Comment by Soulwhisper** [comment]
No.Its working after yesterdays patch. #1564 should close now. Just try hitting the Search button without changing Play Style,Total Players etc etc. It will broke and cannot be pressed again

**Comment by Soulwhisper** [comment]
After the shutdowns of the server Guild search is not working anymore at all.

**Comment by Soulwhisper** [comment]
It worths looking into this.If you are in a Guild you can use the Search(If not try /rel).
If you are not you cant.

**Comment by Soulwhisper** [comment]
If u are in a Guild you cant press the Search button.You have to /reloadui first and then it works fine.
If u are not in a Guild it works fine.
Search results are not correct many times though.
