### ISSUE TITLE
Chat>Experience report

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4449]
![phantomas_010](https://cloud.githubusercontent.com/assets/16864486/13203317/1e2102ae-d8be-11e5-840a-e9d3f8328ba5.jpg)
Killing MOBs and Enemy Players reports it as capturing BOs after patch.

**Comment by Evildoor** [comment]
Similar things (if not exactly the same) happened before patch. See #1573, for example.

**Comment by Soulwhisper** [comment]
This was not happening before the patch though.
**UPDATE** _Now completing Quests reports message : You gain XXXX exp from winning the Battle of the Keep._

**Comment by ozarmidrashim** [comment]
Can personally confirm that this happened before the patch as well.

**Comment by Soulwhisper** [comment]
not to me.Maybe occured after 17.02.2016 patch.

**Comment by Soulwhisper** [comment]
After patch it only reports that you gain exp.Let it be like that :) Its better.

**Comment by notre4ror** [comment]
05/04/2016 Still happens, killing mobs on IC arena and gets "you gain xxx exp from capturing Battlefield objective"
