### ISSUE TITLE
Char bug, no stuff, no skill

### ISSUE THREAD

**Issue by Tholkienn** [WarEmu/WarBugs#4451]
When i log my BW, i have this to my screen:

http://img4.hostingpics.net/pics/646336Zhippo002.jpg

When i log it first time, i was bump to the char selection, if it can help dev'

**Comment by Tholkienn** [comment]
I find a way to debug: /stuck 2 times, off all addons. delog relog.

**Comment by Tholkienn** [comment]
M char is bug again, and i can't disconnect by the menu, the message is:
you cannot quit because you are dead.
All the first time i want to log it, i'm bump after the loading page to the selection page.

**Comment by Evildoor** [comment]
Closing per rules of the bugtracker.
