### ISSUE TITLE
Gold bug, possibly only visual?

### ISSUE THREAD

**Issue by foxbeep** [WarEmu/WarBugs#4452]
Sold a few items to a vendor in High pass and then turned back to join the fight at Ogrund's Tavern when this happened

Relogged to see what would happen and it went away.
Not sure if just visual or not but could be massively abused if replicatab
![laerith_088](https://cloud.githubusercontent.com/assets/15528466/13204000/19dc7c66-d88a-11e5-9cad-1afad319a313.jpg)
![laerith_089](https://cloud.githubusercontent.com/assets/15528466/13204001/1e14527c-d88a-11e5-83c8-f587447ce08f.jpg)

le

**Comment by Evildoor** [comment]
#1810
