### ISSUE TITLE
[Chosen]Hastened Dismissal

### ISSUE THREAD

**Issue by Chummi** [WarEmu/WarBugs#4454]
http://www.twitch.tv/stenchypow/v/48844822 - current implemtation
https://www.youtube.com/watch?v=0c-Bqs06NbY - live
https://www.youtube.com/watch?v=9TpoIo9QcHg - live

completely different. this version is useless.

**Comment by Chummi** [comment]
tested it with and without Hastened Dismissal.

without it the punt is longer:
http://www.twitch.tv/stenchypow/v/48846406

**Comment by ozarmidrashim** [comment]
Fixed
