### ISSUE TITLE
Cannons in t3 Badlands' order warcamp counted as a warhawks.

### ISSUE THREAD

**Issue by ShanellRoR** [WarEmu/WarBugs#4456]
![nahimoff_000](https://cloud.githubusercontent.com/assets/17355822/13207450/7ffd94c2-d91f-11e5-90be-0b269604b14a.jpg)
Just kiled a cannon there and got warhawks unlock in ToK

**Comment by DanaBloodkiss** [comment]
Seems fine in the database.

**Comment by Evildoor** [comment]
No further info provided, closing.
