### ISSUE TITLE
[PVP KILL QUEST] Badlands not working

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#4458]
The second pvp quest at Kazgrim Thorlunson is not working. (doesnt give quest, despite having icon over head) (im lvl33)
![antigonos_019](https://cloud.githubusercontent.com/assets/13809443/13208303/b27e8238-d917-11e5-800b-fcb1d6a441e7.jpg)

**Comment by Soulwhisper** [comment]
Also he got buffs on him???

**Comment by DanaBloodkiss** [comment]
General bugs which we know and will fix later. Thanks for the report!
