### ISSUE TITLE
Get kicked 20.000 feed away

### ISSUE THREAD

**Issue by Zaccar20** [WarEmu/WarBugs#4462]
Hey, on sc i get kicked 20.000 feet away, i think it was a squigherder.

![elvo_000](https://cloud.githubusercontent.com/assets/12786673/13213429/16bdff2c-d949-11e5-860b-5ed964f858cf.jpg)
![elvo_002](https://cloud.githubusercontent.com/assets/12786673/13213438/2145608e-d949-11e5-80dd-298af2be437a.jpg)

**Comment by Tiggonos** [comment]
its the zealot ability.
