### ISSUE TITLE
Wrong Influence Reward Chapter 1 Empire

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4463]
![phantomas_000](https://cloud.githubusercontent.com/assets/16864486/13214577/286f7510-d959-11e5-86ff-1769ad4d504e.jpg)
- [ ] Charm-Book is for priests and the stat(Intelligence) is wrong either way.
- [ ] ToK does not show it as a reward but Rally Master can give it to you.

**Comment by Torquemadra** [comment]
set book as WP only. fixed next patch

**Comment by Soulwhisper** [comment]
![pyromanths_000](https://cloud.githubusercontent.com/assets/16864486/13244913/7ea9cbf6-da12-11e5-90e0-ea26032d3a43.jpg)
Same with BW.I think most classes got this book.Dont want to open tickets so i report here.

**Comment by Evildoor** [comment]
Hmmm. I'm starting to suspect that this, #4357 and #4376 is the same problem - for some reason, Charm items are shown to classes which cannot use them.

**Comment by Soulwhisper** [comment]
Yeap it looks like same problem with Destruction classes too.
