### ISSUE TITLE
Destro Punts - Pushing people to 20,000 feet altitude

### ISSUE THREAD

**Issue by marsares666** [WarEmu/WarBugs#4465]
There are certain destroy punts that seem to be kicking people quite literally into the cloud, and leave them hanging there, thus basically putting people out of action. I've been in three scenarios within one hour where this has happened.

I haven't been able to recreate all instances as I'm reliant on destro using their punts, but so far I've witnessed the following:

(1) BlackGuard single target punt, pushing me into the clouds.
(2) Zealot AOE punt, pushing me and a WP into the clouds
(3) Zealot AOE punt pushing 5 people from a premade (not mine) into the clouds

In all instances we lost the scenario as 1-5 people were pushed out of action, thereby putting us at a numerical disadvantage. I'm not aware if this also happens with Order punts, as I don't play Destro.

**Comment by marsares666** [comment]
Changed back to game-breaking as it has happened again in another scenario, to me and so far 4 other people. Scenarios are unplayable as a result, as it's an instant loss for Order if they lose a couple of people like this.

**Comment by marsares666** [comment]
Changed back to game-breaking in the title as it has happened again in a scenario to me and three other people. Scenarios are pretty unplayable as it's an instant loss for Order if you lose a few people.

**Comment by Tiggonos** [comment]
https://github.com/WarEmu/WarBugs/issues/4462
