### ISSUE TITLE
Scenario Bolsters

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4472]
**Happened in Battle of Praag**
Some people got Bolster and some others dont.
I was with my 30 level Engi and didnt get the bolster.
But a Marauder 33 level got bolster.
Could manage to take a sceenshot because i was pushed to the skies.
Confirmation Request.

**Comment by Tiggonos** [comment]
https://github.com/WarEmu/WarBugs/issues/4470

**Comment by Soulwhisper** [comment]
Closing.Thanks...havent refreshed the page.
