### ISSUE TITLE
[Ability] Zealot WOI sends you to space

### ISSUE THREAD

**Issue by Scrilian** [WarEmu/WarBugs#4474]
Idk if its an abuse of not but WOI now sends you to space on use.
![gaziraga_093](https://cloud.githubusercontent.com/assets/16498708/13216892/c705ce70-d96f-11e5-80d8-b26a3c0c9d62.jpg)
![gaziraga_092](https://cloud.githubusercontent.com/assets/16498708/13216895/ce19808a-d96f-11e5-8fb1-2b38df2b05e9.jpg)

**Comment by Soulwhisper** [comment]
#4462

**Comment by Tiggonos** [comment]
aza fixed it right now

**Comment by marsares666** [comment]
Cant believe how quick you guys are. Thank you so much.
