### ISSUE TITLE
T3 lair boss in BFP not dropping loot

### ISSUE THREAD

**Issue by magicthighs** [WarEmu/WarBugs#4477]
Another report and confirmation, that Ravack, the lair hero in Black Fire Pass, doesn't drop loot either.

**Comment by genisaurus** [comment]
Fixed in next patch

**Comment by Tholkienn** [comment]
We drop two IB helm at 15pm this day.

**Comment by Soulwhisper** [comment]
Ravack drops 1-3 level 36 rare BOP cloaks per kill.

**Comment by Soulwhisper** [comment]
**UPDATE**
Ravack drops 1-3 level 36 rare BOP cloaks per kill.
He dropped 1 jewerly and 2 cloaks.He shouldnt drop jewe though.
