### ISSUE TITLE
Application of Rune of Regeneration can proc Regenerative Shielding tactic

### ISSUE THREAD

**Issue by Lileldys** [WarEmu/WarBugs#4478]
The tactic "Regenerative Shielding" should only trigger when it ticks healing. Currently, you can just spam "Rune of Regeneration" on a target to proc the tactic without it healing. Seems like the application of the skill is considered a tick to the tactic.

**Comment by ozarmidrashim** [comment]
Also affects other skills which apply a buff on tick.
