### ISSUE TITLE
[WL] bugged damage

### ISSUE THREAD

**Issue by Antismar** [WarEmu/WarBugs#4479]
As on screenshots. 1 particular WL is doing super high damage.

![wl_dmg](https://cloud.githubusercontent.com/assets/14290471/13223974/c566ab40-d986-11e5-9a44-7d337d8fffce.jpg)
![wl_dmg2](https://cloud.githubusercontent.com/assets/14290471/13224013/eb389d38-d986-11e5-8d18-a0cc66123893.jpg)

**Comment by Luth-RoR** [comment]
Should be fixed.
