### ISSUE TITLE
Looking like the previously logged character- mixed careers. 

### ISSUE THREAD

**Issue by Naraes** [WarEmu/WarBugs#448]
What is it?
Basically this bug, or glitch, I had found was my previously logged character, mixed with the character I originally wanted to log on to. 

How did this happen?
      I was playing my White Lion, when the Scenario ended, I wound up DC'd from server. I figured, might as well stay logged off, and relog back onto my other character; so I did. Multiple things happened after I decided this. After I had logged into my Witch Elf, the one I returned playing on, I warped to Mount Blood Horn- where my White Lion had DC'd. I was found along the mountain walls (more specifically along the mountain of Spore Rock Major Landmark).  I thought "Oh, it must have glitched my White Lion again" until I looked closer seeing that I had the body of my witch elf- with the gear, abilities, and guild of my White Lion- still containing my Witch Elf's name. The images provided show what I am describing. All of the abilities had worked, including the summoning of the war lion. Instead of the "high pitched" white horn that high elves use to summon this lion, it used the dark elf horn when summoning their "Cold One" mounts and the deeper 'trumpet' summoning sound. 

How do I know this is a glitch/bug: 
        It is proven in the pictures that my hair/face/skin color is unobtainable for high elves, also noting that Dark Elves cannot get that type of gear, let alone hold a war axe. 

Did it fix itself? 
       It did not mechanically fix itself as I observed my character, however once I had reloaded my Return of WAR launcher, both my characters had returned back to their original selves. 

Please note: I had not tried to go to a major city or warcamp as this mixed class, it did not occur to me at the time- so I do not know if I was labeled as an enemy at the time towards Destruction or Order. 

Images:
![naraes_019](https://cloud.githubusercontent.com/assets/9633262/4966617/24d659e6-67d6-11e4-9a9c-26f716c434ea.jpg)
![naraes_020](https://cloud.githubusercontent.com/assets/9633262/4966618/24d6a496-67d6-11e4-9573-16763a8d9df1.jpg)
![naraes_021](https://cloud.githubusercontent.com/assets/9633262/4966619/24dc38ca-67d6-11e4-8fd2-53d7e9326499.jpg)

**Comment by Evildoor** [comment]
This was fixed. Closing.
