### ISSUE TITLE
Medallions in scenarios.

### ISSUE THREAD

**Issue by bloodi** [WarEmu/WarBugs#4481]
According to Genisaurus in the new loot system we had this change for scs:

-Medallions will no longer drop in scenarios. Their drop rates have been slight increased, and double around keeps and BOs. Additionally, we're working on getting loot chests working on keeps, so gear should come a little quicker in the future.

They still drop in scs.

**Comment by genisaurus** [comment]
Old loot code is still hiding out somewhere.
