### ISSUE TITLE
Banners Visual Bug

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4482]
You can equip but there is visual bug.Cant see it in real world on your character.
Dunno if you disabled it to fix it.Seen no other report.

**Comment by nalgol** [comment]
should work again next patch

**Comment by Soulwhisper** [comment]
Niceee! Gj nalgol!

**Comment by Soulwhisper** [comment]
Still doesnt work.

**Comment by Soulwhisper** [comment]
Doesnt work.Why closed?

**Comment by DanaBloodkiss** [comment]
Fix pending means it's fixed with the next patch. The patch went live so I closed it. When it still does not work reopen it.

**Comment by Soulwhisper** [comment]
I know but still doesnt work.Cant see it in real world on your character(Cant hold it visually).

**Comment by Soulwhisper** [comment]
![123](https://cloud.githubusercontent.com/assets/16864486/13576599/2b071e92-e497-11e5-9ee1-adb50ae14dbf.jpg)
Clicking on the banner at hotbar doesnt show it on your character.

**Comment by nalgol** [comment]
well im just standing in game and
![banner](https://cloud.githubusercontent.com/assets/6865913/13612070/dd98bede-e565-11e5-8e53-9cd9b10dfbb2.jpg)

 have the banner out did you assignt standard bearer`?
.standard yourname

**Comment by Soulwhisper** [comment]
Yes im assignt.Tried unassigning and assigning again.Nothing worked.
![toufekiaaaa_009](https://cloud.githubusercontent.com/assets/16864486/13612471/608583c2-e570-11e5-93fe-baba79a56285.jpg)

**Comment by nalgol** [comment]
okok clearly destro based dev i forgot to add the spell ids for order banners /blush will be fixed with next db push

**Comment by Soulwhisper** [comment]
Nice! Thanks nalgol!
