### ISSUE TITLE
[Query] Witch Elf - Web of Shadows Morale 2

### ISSUE THREAD

**Issue by Luranni** [WarEmu/WarBugs#4483]
I noticed today that Web of Shadows was granted at level 33, on live it was a level 36 ability so I'm not sure if we're supposed to have it yet (it's a pretty strong m2).

**Comment by Chummi** [comment]
Pretty sure that this was a bug on live.
Class specific morale 2 were always granted at lvl 32 on any other class.
The exact equal counterparts for Web of Shadows (Flying Axe, Reversal of Fortune and Great Fang which can be found on White Lion, Witch Hunter and Marauder) are available at rank 32.

Class specific Morale 3 is always granted at rank 36.

I don't see how this morale is by any means stronger than a *50% crit *buff for your group. DR's damage is usually used for morale dumping and its damage is equal to SN.

Besides granting the WE the possibility to have a defensive morale 1 (Confusing Movements) and a damage morale 2 for its group play it has no impact. 50% crit on the other hand is insanely strong in both ways offensive and defensive.

**Comment by ozarmidrashim** [comment]
Closed per response to issue #4505.
