### ISSUE TITLE
Bug Wb/grp

### ISSUE THREAD

**Issue by Tholkienn** [WarEmu/WarBugs#4484]
Still the server in on, we can't grow up grp to wb.

**Comment by Soulwhisper** [comment]
Cant see Dots on map too.

**Comment by gats69** [comment]
yes WB bugged

**Comment by Soulwhisper** [comment]
I think todays patch fixed it. Can someone confirm it?

**Comment by Tholkienn** [comment]
It's patching!

**Comment by Evildoor** [comment]
I suppose that this was fixed and can be closed.
