### ISSUE TITLE
[Item] The Boundless Axe

### ISSUE THREAD

**Issue by Scrilian** [WarEmu/WarBugs#4485]
Was it supposed to be 40STR 40Wounds instead of 40STR 40Toughness?
![valtor_205](https://cloud.githubusercontent.com/assets/16498708/13233377/8061a3a4-d9c4-11e5-9d19-d7e18a3546f3.jpg)
![valtor_206](https://cloud.githubusercontent.com/assets/16498708/13233385/8777c97a-d9c4-11e5-897c-2a99872d5607.jpg)

**Comment by genisaurus** [comment]
No, it wasn't.
