### ISSUE TITLE
[Item] The Boundless 2handers

### ISSUE THREAD

**Issue by Scrilian** [WarEmu/WarBugs#4486]
Some 2handers have very low stats for 2handers and some have are high. Any bugs with it?
![otis_054](https://cloud.githubusercontent.com/assets/16498708/13233451/bda1fe44-d9c4-11e5-9bbc-f41589278a66.jpg)
![valtor_198](https://cloud.githubusercontent.com/assets/16498708/13233466/d097f40e-d9c4-11e5-8608-cfbe99283703.jpg)
![otis_048](https://cloud.githubusercontent.com/assets/16498708/13233478/dc528494-d9c4-11e5-9749-b97e18d528b3.jpg)

**Comment by dasset** [comment]
![navras_022](https://cloud.githubusercontent.com/assets/17085430/13238580/bab6ade8-d9dc-11e5-8658-e6ee592bfd43.jpg)

Are the items bugged or are some just badly optimized? And if they are badly optimized, any change of reworking them?

**Comment by Scrilian** [comment]
Yea, some 2handers have very fast speed of 2.8, some are slow as fuck with 4.1. Barely remember any being this way on live, which were mostly 3.6-3.8 speed.

**Comment by Ryanfawkez** [comment]
https://github.com/WarEmu/WarBugs/issues/4140
will be adjusting DPS to 74.0 and speed to 3.6 on all 2hander Boundless weapons.

**Comment by bloodi** [comment]
Why wwouldd you leave the stats as it is?

Currently some have double the stats of others with the same dps.

**Comment by Ryanfawkez** [comment]
@bloodi - Double the stats of others? Compared to which item? All the Boundless 2-handers have the same stats at the moment if they have 6% disrupt. Some boundless 2-handers (SM greatsword for example) have over double the same stats but no disrupt. Reason I'm not tweaking these just yet is because there needs to be a consensus on adressing varying stats for varying weapons, while we have already agreed that DPS and speed rates should all be generalised.

**Comment by bloodi** [comment]
You can check it with things like Boundless Longstaff vs Wingstaff of the eternal.

The blue version has +34 ini +67 Int +3% disrupt, the purple has +32wp +32int +6% disrupt, lets assume for a moment that 3% disrupt = 48 stats points as Geni said, why the difference is 37 here?

There is weird stuff like that all over those items, if we go for a comparison to the previous tier, we can see that 1% = 16 stat points was not true at all before, not even close, a Bandit 2h axe has +50 str +37 Ws +3% parry and the 1h has +31 str +31 ws, there we see a difference of 25 stats points between equiping 2 1h yet we get 3% parry, which should be 48.

If you go by item level, which is imo, the best way to normalize their stats, they should be equal to the current lvl 29 sc emblems weapons, both are item level 35, a BW staff for sc has +33 wounds +44 int +2% crit +4ap per sec, while we have things like Boundless Kndlestave with +32 wp +32int + 6% disrupt, without even putting value on disrupt or +ap you can see that they are not equal, stat wise.
