### ISSUE TITLE
[Item] The Boundless Hatchet problem

### ISSUE THREAD

**Issue by Ridel1e** [WarEmu/WarBugs#4489]
The Boundless Hatchet (Great Axe on WL) behaves like one handed weapon. It has damage like one handed.
![4](https://cloud.githubusercontent.com/assets/6741162/13236082/44f17d4e-d9d3-11e5-9ff6-17893efcd12e.jpg)

**Comment by Torquemadra** [comment]
It has the damage of a 2 hander and the stats of a 2 hander, it just has the appearance of a 1 hander. Regardless, fixed next patch.
