### ISSUE TITLE
Dyes not applying correctly

### ISSUE THREAD

**Issue by Fct2** [WarEmu/WarBugs#4490]
Dear support,

offcourse i wanted to look badass and i bought 8 skull white dyes and 4 chaos blacks
Obviously i am to early buying this stuff so it costed me like 400 gold.

Somehow i still see yellow pieces on it so it actually looks pretty ugly now. 
Can u pls help me on this? Spending so much so i hope i look badass soon :)

Thx in advance

![fct_056](https://cloud.githubusercontent.com/assets/17419959/13239388/1e6701c4-d9da-11e5-9c92-c7dddc05e05d.jpg)
![fct_057](https://cloud.githubusercontent.com/assets/17419959/13239390/1e673bbc-d9da-11e5-8e8f-98348531bebf.jpg)
![fct_058](https://cloud.githubusercontent.com/assets/17419959/13239389/1e672b7c-d9da-11e5-86bb-0b541ee2cbc2.jpg)
![fct_061](https://cloud.githubusercontent.com/assets/17419959/13239418/499bf7be-d9da-11e5-9723-2b1aca0894da.jpg)

Cheers,
FCT

Keep the good job up

**Comment by Torquemadra** [comment]
Sorry thats a problem with that model skin being hard coded that way and something we are not able to amend. I would suggest finding an alternate appearance items that lends itself better to being dyed that colour.

**Comment by Fct2** [comment]
Allright any way to get some white dyes back or do i have bad luck?
