### ISSUE TITLE
[Bolster] Pets to lvl 37

### ISSUE THREAD

**Issue by Scrilian** [WarEmu/WarBugs#4494]
Seems to me that bolster buffs pets past the 35 lvl, making SH/WL damage a bit ridiculous
![otis_057](https://cloud.githubusercontent.com/assets/16498708/13244812/3895cacc-da1a-11e5-8cfd-99c94540e720.jpg)
.

**Comment by Scrilian** [comment]
37 flamers and turrets
![gaziraga_101](https://cloud.githubusercontent.com/assets/16498708/13248337/befd6ce6-da2e-11e5-9952-9bee27b9374d.jpg)

**Comment by Evildoor** [comment]
This should be obsolete with T4 patch and changed bolster system.
