### ISSUE TITLE
[Item] Martial/Vanguard rings and cloaks

### ISSUE THREAD

**Issue by Scrilian** [WarEmu/WarBugs#4495]
It seems that every tier has rings and cloaks, except the 31-39 one. Is that intended?
![valtor_208](https://cloud.githubusercontent.com/assets/16498708/13246172/faa4fbd0-da22-11e5-876c-1391fd3c1db5.jpg)
![valtor_211](https://cloud.githubusercontent.com/assets/16498708/13246178/00bea0ca-da23-11e5-9341-d297811341e6.jpg)
![valtor_212](https://cloud.githubusercontent.com/assets/16498708/13246183/0b84b8f0-da23-11e5-9f76-5636d1ad9d80.jpg)

**Comment by Styrkarr** [comment]
It is. And it's not implemented for now.

**Comment by Evildoor** [comment]
This was fixed with T4 patch.
