### ISSUE TITLE
"Sticky Squigz" ability not knocking you back from your enemies.

### ISSUE THREAD

**Issue by ShanellRoR** [WarEmu/WarBugs#4496]
Had a couple of fight in Talabec, used that skill and it did not knock me back from the enemies, but still seems to snare them.
![nahimoff_005](https://cloud.githubusercontent.com/assets/17355822/13251172/a2d0d6d2-da3f-11e5-806c-163714ea9420.jpg)

**Comment by Evildoor** [comment]
No confirmation, closing.
