### ISSUE TITLE
[Ability] Slow boil tick disrupted

### ISSUE THREAD

**Issue by Scrilian** [WarEmu/WarBugs#4497]
Today I noticed that Slow boil dot has a very high chance of being disrupted and mainly by Black Guards not only on application but tick as well. Just had a praag vs alot of them, will make screenshots with proofs when encounter this bug again.

**Comment by Torquemadra** [comment]
Shielding anger tactic among other BG tools may explain it

**Comment by Scrilian** [comment]
There were quite a few 2hander ones so I doubt that its the tactic. To me it looked that the tic checked for willpower coz a few tics were disrupted by shamans aswell.
And Slow boil doesn't agro rats in atldorf, unlike other dots like Boiling Blood.

**Comment by Scrilian** [comment]
That's a tic disrupt from fully doted SH
![gaziraga_109](https://cloud.githubusercontent.com/assets/16498708/13254022/6b0ba176-da50-11e5-9946-0b21a222c8f6.jpg)

**Comment by bloodi** [comment]
I dont feel an increased chance of disrupt, however is true that it can be disrupted on cast and then it can be disrupted when it does the damage after the 5 seconds, i dont think that is normal as every other debuff with a damage at the end doesnt suffer from the same, at least wop/bb doesnt.

**Comment by gittoaster** [comment]
There should only be one chance to disrupt (on application) same as BB.

**Comment by Tiggonos** [comment]
is this for boiling blood too? (2 chances to interrupt?).
