### ISSUE TITLE
DC in Battle For Praag - Unable to log back in! 

### ISSUE THREAD

**Issue by sandreid** [WarEmu/WarBugs#4498]
I've done two BFP today, and randomly DCed (One time I was dead, and got ressed on my BO. The other time I was dottig a Choppa on my BW). 
After I DCed, I had to crash the game. I tried to relog to my character but I get "thrown back" to character selection screen before the loading screen even showed, with an error message saying I'd DCed. So in other words, BFP makes you DC and unable to log on to the character again for an unknown time period. This also happened to a guildy of mine, so it's not just me.

I don't know what causes this in BFP. There doesn't seem to be any pattern to it. I suggest disabling BFP until this has been resolved :)

P.S. How do I add a label?

Thanks!

Razid

**Comment by Evildoor** [comment]
I'd like to see more evidence from someone that this is especially caused by BFP.
P.S. Labels can only be added by the devs.

**Comment by sandreid** [comment]
There was plenty of people reporting it in /ad, but everything seems to be okay back to normal after the restart.

**Comment by ozarmidrashim** [comment]
Issue was caused by my failure to release a spinlock.
