### ISSUE TITLE
SW's tactic Bullseye does not work propertly

### ISSUE THREAD

**Issue by krisolyub** [WarEmu/WarBugs#4499]
SW's tactic Bullseye:
1)  does not proc from dot's crits. (the tactic buff should appear on crit).
2)  does not proc 2nd time when the tactic already is active. (the tactic buff should renew on crit).

**Comment by Sizer1111** [comment]
It never procced on dots. As far as refreshing itself, i think it did on live at one point but was not supposed to, and got fixed in a later patch. Might be wrong there, but im sure it never worked on dots.

**Comment by Chummi** [comment]
tactics never procced on DoT.
about refreshing i'm not 100% sure but i doubt. will check footage later. 
if they refreshed it should be applied for all tactics not for Bullseye exclusive. WEs ToB or Mrds FoF doesn't refresh either. **Imho they shouldn't.** anyway will try to provide footage from live later.

**Comment by krisolyub** [comment]
Maybe u right.
I just read the description of the tactic. Base on it tactic should procced on every crit. 
Btw i remember chosen tactic which gives 25% parri from every block. That chosen tactic renews on every block.
