### ISSUE TITLE
[PQ] - Revoltin' Gobbos

### ISSUE THREAD

**Issue by Ryanfawkez** [WarEmu/WarBugs#4500]
This PQ is a Destruction-only flagged PQ but only Order is able to do it, awarding them influence for Chapter 11. By my estimation it is supposed to be do-able by both factions, and such be flagged accordingly with both Destro and Order's objectives.

**Comment by Ryanfawkez** [comment]
Confirmed: http://warhammer.gamepressure.com/map.asp?ID=2 - shows that this is a dual faction PQ, same as with Fireforge's Camp, which is currently only do-able by Destruction.

**Comment by Torquemadra** [comment]
All the multi faction pqs are currently assigned to one realm due to restrictions currently in place
