### ISSUE TITLE
Wrong emblem given in Scenario

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4502]
![pyromanths_000](https://cloud.githubusercontent.com/assets/16864486/13260957/91e355c6-da66-11e5-8e90-8a981d1644e8.jpg)
Got a Scout one.

**Comment by Soulwhisper** [comment]
Is this intended because rank caps changed temp? If it is close it please.

**Comment by Ryanfawkez** [comment]
Not sure if it's intended but that does explain why it happens. Won't be much of an issue since the rank caps are scaled up temporarily.

**Comment by Soulwhisper** [comment]
So its fine earning a T2(14-26) emblem while you do T1(1-13) Scenarios/RvR ?

**Comment by genisaurus** [comment]
It wasn't intended, the loot dropped by a player is based on the level of the player killed. The changed tier caps were pushed after the loot tables were. Fixed in next patch.
