### ISSUE TITLE
[Item] - The Boundless Bigloppa

### ISSUE THREAD

**Issue by Sizer1111** [WarEmu/WarBugs#4504]
This weapon has 73 dps while the other 2h 35 purples have 75 dps. Pretty minor but thought id mention it. 

![pookeys_003](https://cloud.githubusercontent.com/assets/16495179/13263511/cb822854-da37-11e5-8c06-c39d18f96919.jpg)

![pookeys_004](https://cloud.githubusercontent.com/assets/16495179/13263513/cd689f36-da37-11e5-9fa0-0d1d6b8ef110.jpg)

**Comment by Ryanfawkez** [comment]
https://github.com/WarEmu/WarBugs/issues/4486
