### ISSUE TITLE
Stealth and portals

### ISSUE THREAD

**Issue by Luranni** [WarEmu/WarBugs#4506]
On live if you were in stealth you could not interact with portals and suchlike, either nothing would happen or it would unstealth you.  At the moment I am able to use tunnels, keep doors etc while stealthed, not sure if this is intended behaviour.

**Comment by Luranni** [comment]
UPDATE (after testing): I am indeed also able to Stealth > Pick Lock > Use Postern > still stealthed to get into enemy keeps.

**Comment by grunbag** [comment]
Fixed while ago
