### ISSUE TITLE
Abilities issue

### ISSUE THREAD

**Issue by aaltom** [WarEmu/WarBugs#4507]
I do not know if this has already been reported but occasionally skills would not activate when the cooldown starts (cooldown start but the skill dont have worked). For example: I run the SW's stunt that does not work but the cooldown starts anyway.

**Comment by Evildoor** [comment]
What "stunt" exactly?

**Comment by aaltom** [comment]
its the knockdown

**Comment by Tiggonos** [comment]
what is meant with "not work" if the target is imun to knockdown, the cooldown should still trigger on the ability shouldnt it?

**Comment by aaltom** [comment]
sometimes when i kite, abillities do not engage, but the cooldown start

**Comment by aaltom** [comment]
sorry for my bad english

**Comment by Evildoor** [comment]
I do believe that comments to #1816 apply here as well.

**Comment by Evildoor** [comment]
No objections to my comment, so i'm closing this per #1816.
