### ISSUE TITLE
Bottom of IC

### ISSUE THREAD

**Issue by benitoben20** [WarEmu/WarBugs#4509]
Hello,

I jumped off the platform on IC, to find what would happen, and I hit the an "invisible floor" under IC. There's 2 things on the pictures, but i'll report it on the next ticket. 

Firstly, when I jumped and landed on the bottom floor of IC, I did not received any damage from the fall. On the bottom floor, I was able to walk around and inspect every corner of the bottom of IC. Still, I'm suprised, almost no dust... :) 

Either way, I think it would be best to kill the player once it reaches the bottom. I used my book to teleport out.

Thank you,
![isas_011](https://cloud.githubusercontent.com/assets/16641170/13270572/12d417ce-da5d-11e5-96d9-743378dfca37.jpg)
![isas_009](https://cloud.githubusercontent.com/assets/16641170/13270571/12d3b540-da5d-11e5-8c84-274ba914c7a5.jpg)

**Comment by wargrimnir** [comment]
Fall damage should certainly kill you now.
