### ISSUE TITLE
Monster at the bottom of IC

### ISSUE THREAD

**Issue by benitoben20** [WarEmu/WarBugs#4510]
Hello,

I jumped from the platform of IC, and at the bottom, there is a LOT of monster NPC roaming around. From what I saw, there's more than 15 monster down there. Wondering if they should be there...

Thank you,

PS: Made another ticket [#4509](https://github.com/WarEmu/WarBugs/issues/4509) for reaching the bottom alive

![isas_012](https://cloud.githubusercontent.com/assets/16641170/13270692/d44a0c2e-da5d-11e5-9b1f-f9b7669eace3.jpg)
![isas_017](https://cloud.githubusercontent.com/assets/16641170/13270757/30efd7f6-da5e-11e5-873d-856a8cfbc0fc.jpg)

**Comment by Ryanfawkez** [comment]
Excess NPC removed. Fixed in next patch.

**Comment by Yellowpillow** [comment]
meantime mobs are back, they like there
![arena_025](https://cloud.githubusercontent.com/assets/18102127/14771378/521e8172-0a9a-11e6-9b8b-bf46447f301b.jpg)

**Comment by DanaBloodkiss** [comment]
I think they bug through the ground. We should not remove them because then they will miss at their correct place.
