### ISSUE TITLE
Monolith

### ISSUE THREAD

**Issue by benitoben20** [WarEmu/WarBugs#4511]
Hello,

Once you are able to solve the jump puzzle and reach the top of the monolith, there's an issue with the walkable floor. Your character walks higher than what the monolith permits. Also, you can walk on the edge of the monolith without falling down.

Thank you,

PS: What a quest for a pie ! :P
![isas_004](https://cloud.githubusercontent.com/assets/16641170/13270883/0401bd76-da5f-11e5-9bac-ba626bf3068e.jpg)

**Comment by Ryanfawkez** [comment]
We'd have to alter the collision model in order for this to work as intended. This spot was never supposed to be reachable on live, so its collision model is a lot bigger than it should be as it'd also take up less game data. We have no control over hitboxes for models like this at the time.
