### ISSUE TITLE
NPC's attacking each other

### ISSUE THREAD

**Issue by benitoben20** [WarEmu/WarBugs#4512]
Hello,

In the PQ Kruegerhaus, in Tabacland, the NPC "Krueger Caller" is hostile to every other NPC around.

Thank you,
![isas_019](https://cloud.githubusercontent.com/assets/16641170/13271383/aeef17da-da62-11e5-816a-31fc2a183239.jpg)
![isas_020](https://cloud.githubusercontent.com/assets/16641170/13271384/aef02846-da62-11e5-97a3-2bd75e145d1e.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by Gobtar** [comment]
Servants will now kill neutral NPCs.( These Daemonettes cannot be controlled!)
Namely the "Heralds" and lvl 1 animals.

**Comment by Lheana** [comment]
Seems like peace is back in this castle, NPCs don't attack each other any longer.
