### ISSUE TITLE
SQ: Behind Ya!

### ISSUE THREAD

**Issue by Stinkyweed** [WarEmu/WarBugs#4515]
Posted in November without ability confirmation.

Tactic on live gave crit % increase based on the targets hit points, lower the hpts higher the crit%. The tool tip does not reflect this, not sure if it's in the coding.
Flanking Shot on SW has the description in the tool tip on how both Behind Ya! and Flanking Shot are supposed to function.

**Comment by Evildoor** [comment]
#1907
Read the rules of the bugtracker.
