### ISSUE TITLE
The Boundless Hide vs The Boundless Cloak

### ISSUE THREAD

**Issue by davidchicheung** [WarEmu/WarBugs#4516]
Exactly the same item main stat wise, besides the resistances.

Screenshots attached below. The difference are the following stats...
132 vs 93 spirit resistance
44 vs 31 elemental resistance
44 vs 31 corporeal resistance

![meepie_000](https://cloud.githubusercontent.com/assets/699806/13275839/35a47da0-da6e-11e5-946b-982002bc1a94.jpg)
![meepie_001](https://cloud.githubusercontent.com/assets/699806/13275840/35a5c5d4-da6e-11e5-8275-d9003e96b40d.jpg)

**Comment by Ryanfawkez** [comment]
Makes no sense to have reduced stats on cloaks that are identical to each other. Scaling all resistances up to 132 - 44 - 44.
