### ISSUE TITLE
0 Renown after disconnecting from SC

### ISSUE THREAD

**Issue by phsampaio** [WarEmu/WarBugs#4517]
Just after I finished a SC (Morkain Temple), I pressed "leave" but got disconnected during the load screen. Loged again on the same char, only to find out my 26 RR gone (pic below). I even lost the abilities, apparently.

Exiting the game and logging again resolved the problem, so it seems just a visual bug.

![sacerdote_000](https://cloud.githubusercontent.com/assets/16727921/13276268/5777ffa0-da9c-11e5-962a-d644cee8f911.jpg)
![sacerdote_001](https://cloud.githubusercontent.com/assets/16727921/13276269/5779bf70-da9c-11e5-8332-e2f9210dc5c4.jpg)

**Comment by Evildoor** [comment]
#1791
