### ISSUE TITLE
The Boundless Crusher stats

### ISSUE THREAD

**Issue by laattori** [WarEmu/WarBugs#4519]
The Boundless Crusher stats look a bit underwhelming compared with the other Destro weapons. Fix possible?
![crusher](https://cloud.githubusercontent.com/assets/15817706/13280477/107b3d92-dae7-11e5-9ddf-275775d4703f.jpg)
![cutta](https://cloud.githubusercontent.com/assets/15817706/13280485/14ed5a72-dae7-11e5-9d8f-ee82ab86c8e9.jpg)
![stabba](https://cloud.githubusercontent.com/assets/15817706/13280490/1cf1eb48-dae7-11e5-8ec6-4c155eafbc68.jpg)

**Comment by Torquemadra** [comment]
fixed next patch
