### ISSUE TITLE
[Guild Vault] Weird behaviour

### ISSUE THREAD

**Issue by Luranni** [WarEmu/WarBugs#4521]
Not a biggy (yet), but I've noticed sometimes if guildies access the guild vault, it also opens on my screen as well.  So:

After using the vault, I went to the crafting merchant at which point another guildy used the vault. We tested and it only popped up on my screen when they put something in or took something out (not just opened it).  I then went to other zones and we repeated the test (the guild vault did not appear on my screen in talabec or avelorn).  I then returned to IC and we tested again both with and without my having the NPC targetted... the guild vault did not appear on my screen.

Sorry but I couldn't narrow down the cause with the tests we did yet, it appears to be a little random.  I'll add to this report with screenshots of where/when it happens in future.

**Comment by Luranni** [comment]
Ok got some screenshots, still can't pin down the why of it but here we go.
![guildvault bug 1](https://cloud.githubusercontent.com/assets/16735846/13300596/3ad81c2c-db41-11e5-88db-118a6d74092d.jpg)
![guildvault bug 2](https://cloud.githubusercontent.com/assets/16735846/13300597/3adc922a-db41-11e5-8578-bc649d179b7e.jpg)
![guildvault bug 3](https://cloud.githubusercontent.com/assets/16735846/13300598/3adccf2e-db41-11e5-9dd8-95fd19c19ba2.jpg)

**Comment by nalgol** [comment]
all guild vault users are saved in an array so if somone changes something everyone will see it somehow it seams it didnt deregister you on closing the vault

**Comment by Luranni** [comment]
Aye I'm just concerned it could happen in combat, that would be a big oops.  Will add anything useful if it happens.

**Comment by Soulwhisper** [comment]
Happened to me actually in fight...bit annoying.

**Comment by Luranni** [comment]
Yep just happened to me while in Tor Anroc.  Pretty nasty actually as the cursor moves to the gvault money so your abilities stop firing and the gvault is suddenly smack in the middle of the screen - oops.

**Comment by nalgol** [comment]
if you run out of range it didn't deregister your char fixed next patch
