### ISSUE TITLE
Punted over outer fence (High Pass Cemetery) 

### ISSUE THREAD

**Issue by BananaBunn** [WarEmu/WarBugs#4523]
Punted by an Ironbreaker over the outer fence in the high pass cemetery scenario, a white lion was then able to pounce over the fence to me. I assume the wl issue is this #2320 but couldn't find anything relating to either Ironbreaker punt or being punted over the fence in high pass cemetery sc.  
![bunnzz1](https://cloud.githubusercontent.com/assets/17455732/13292779/07572aa4-db15-11e5-8e74-2316cdb96774.jpg)
![bunnzz2](https://cloud.githubusercontent.com/assets/17455732/13292782/09c8e958-db15-11e5-86c4-45c93e276058.jpg)

**Comment by Evildoor** [comment]
Changelog from 21.03.2016 (a bit late :P ).

- High Pass Cemetary has now been fenced off with Magical walls to prevent people from punting their enemies out of the scenarios.
