### ISSUE TITLE
Seaguard Blue and Goblin Green Dyes

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#4524]
There are two different kinds of Seaguard Blue dye in the game. One is craftable from cultivating and creates an item with green text while the other is dropped from mobs and has white text. Even though they have the same name, they are not the same kind of blue (shown in the picture).
Goblin Green Dye has also multiple varieties of item IDs it seems. Two with green text (drop from mobs and they do not stack with each other) and one with white text (crafted from cultivating). But at least they have the same color when applied on a piece of armor.
 ![seaguardblue](https://cloud.githubusercontent.com/assets/16590792/13293764/5bd4bfd6-db21-11e5-8e20-a57180eac05c.jpg)

**Comment by Ryanfawkez** [comment]
So, going by their icons, their colours simply need to be switched for the sake of consistency.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
