### ISSUE TITLE
Damage through absorb shields

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#4526]
Not sure if this is actually a bug. It just looks very confusing to me.

Regular hit:
Spellbreak Sentinel's attack hits you for 176 damage. (647 mitigated)

Same hit with absorb:
Spellbreak Sentinel's ability hits you for 0 damage. (120 mitigated) (703 absorbed)

I remember something about absorb damage being pre mitigation but then where does the 120 come from?
Mobs are literally eating through my shields. Please confirm that this is working as intended.

**Comment by Evildoor** [comment]
While i don't know the exact mechanism and may only hazard a guess that 120 is mitigated by toughness while armor gets bypassed, the numbers don't look wrong when compared with my memories from live.

**Comment by ozarmidrashim** [comment]
Toughness => Absorption => Armor/Resistances.

Yes, it sucks.
