### ISSUE TITLE
[Item] Wolfenburg Casque

### ISSUE THREAD

**Issue by Halhammer** [WarEmu/WarBugs#4527]
Empire Ch. 9 Influence Reward for KOTBS, Wolfenburg Casque, has no skin.
It used to be that spiky-mohawk helm back on live, if you guys are able to find it somewhere.

Would really appreciate wearin my beloved non-feathered mohawk helm again :D

**Comment by Torquemadra** [comment]
done and even added stats to it. Fixed next patch
