### ISSUE TITLE
Spilge Stinkrat

### ISSUE THREAD

**Issue by Skutrug** [WarEmu/WarBugs#4529]
Spilge Stinkrat is a champion/hero located underground (below game level) in Unterbaum (Talabecland) at 35826,46065.
It shoots the character during the quest "cleaning an empire" - Please bring him to the surface so we actually see him - also, it would be great if NPC actually checked LOS but I guess it will be for the future.

**Comment by DanaBloodkiss** [comment]
Moved his location out of the house. Fixed in next.

**Comment by gittoaster** [comment]
Also not, his level is 40 Champion.  Does not seem to be the correct level for Chapter 14 area.

**Comment by DanaBloodkiss** [comment]
Changed.
