### ISSUE TITLE
Flame Breath Worked Differently on Live

### ISSUE THREAD

**Issue by Dreamhous** [WarEmu/WarBugs#4530]
https://www.youtube.com/watch?v=h5mY7yUDapM
At 0:30, 4:15, 4:20 and numerous other times in the video it shows that Flame Breath applied damage on ability activation on live
On RoR the damage applies after 3 seconds

**Comment by ozarmidrashim** [comment]
Calling BS for two reasons:

1) http://www.returnofreckoning.com/forum/viewtopic.php?f=75&t=11193
2) You can see from the hotbar that he's able to spam it (tactic? WW?) so the combat log ticks don't mean anything.

**Comment by ozarmidrashim** [comment]
Proven with https://www.youtube.com/watch?v=Hk-UVsBESiU at 1:23.

**Comment by Scrilian** [comment]
Did it proc Funnel Power?

**Comment by Tiggonos** [comment]
good point scrilian, when it procs flames of rhuin it should proc funnelpower too. now lets find proof :)
