### ISSUE TITLE
T2 Dwarven Rally Master not showing INF rewards

### ISSUE THREAD

**Issue by Ghrevith** [WarEmu/WarBugs#4531]
The rally master in the T2 Dwarven Warcamp does not show the rewards to be selected for achieving Influence rank in that RvR zone.

**Comment by Evildoor** [comment]
Have you unlocked the page in Tome of Knowledge for Dwarf T2 RVR?

**Comment by Ryanfawkez** [comment]
What Warcamp is this? Is it in Barak Varr or Marshes of Madness? You can only pick up your influence rewards from one of them, same as in T3 where only the Badlands WC rally master can give you the influence rewards.

**Comment by Ghrevith** [comment]
This was the rally master in the Baraka Varr Warcamp. I wasn't aware that only one of the RM would offer rewards. I jump to the Marshes Warcamp and check there instead. Appreciated.

**Comment by Evildoor** [comment]
I suppose that this was resolved.
