### ISSUE TITLE
Bestiary bug

### ISSUE THREAD

**Issue by mnetkabel** [WarEmu/WarBugs#4534]
Hi. 
I just finished killing 1 000 chaos servants bestiary task. I was supposed to get item reward, but it is just an empty square in the Items section of Tome of Knowledge. I was told in Advice chat to report it as a bug, so here it is : )

![theoutlaw_000](https://cloud.githubusercontent.com/assets/17475022/13321146/e1a4126a-dbd5-11e5-912a-607fd18eaa26.jpg)
![theoutlaw_001](https://cloud.githubusercontent.com/assets/17475022/13321145/e1a42fca-dbd5-11e5-95e3-8662134d578e.jpg)
![theoutlaw_002](https://cloud.githubusercontent.com/assets/17475022/13321147/e1a5ce16-dbd5-11e5-853b-7ac9b3e15555.jpg)

**Comment by Ryanfawkez** [comment]
You don't get an item reward in your bag for completing most ToK unlocks; you simply become eligible for purchasing the related ToK from the library vendors. Talk to Delwin Lehrer in the Altdorf Library, you can buy a Chaos Cleanser, One Pip trohpy from him with this unlock.

As to why your reward doesn't show in the ToK by the unlock, I have no idea. Most items show as intended; cloaks, pocket items, jewels, ect.

**Comment by mnetkabel** [comment]
I did another one with the 1000 horrors and I got a token for trophy. Wierd
thig is i didnt get one from the Chaos servants task

**Comment by mnetkabel** [comment]
Does that mean I can buy another one?

**Comment by DanaBloodkiss** [comment]
Listen to Ryan!
"Talk to Delwin Lehrer in the Altdorf Library, you can buy a Chaos Cleanser, One Pip trohpy from him with this unlock."
You can buy yourself a reward. Just go to the vendor and right click the item "Chaos Cleanser, One Pip" then you get it into your inventory. You don't need a token for it.
