### ISSUE TITLE
[Quest] Destruction: Bred, Fed and Led

### ISSUE THREAD

**Issue by Luranni** [WarEmu/WarBugs#4535]
"Bred, Fed and Led" - grants the Crimson Cloak for Destruction.

Starts from NPC Thordis Valdar in Chaos ch11. It seems to have the same bug as the Order one had, as two are available at once.

The NPC you are supposed to kill after getting the List of Collaborators doesn't turn red, he stays friendly.. and I couldn't find the Secret Document in the tower.

**Comment by Evildoor** [comment]
#1852 is supposed to be fixed (at least the part about multiple stages at once)...

**Comment by Luranni** [comment]
Well yes and no I guess :D.  There are TWO stages of the quest you can pick up at once now, not three hehe.

**Comment by Torquemadra** [comment]
Fixed next patch

**Comment by Luranni** [comment]
Awesome, thank you.
