### ISSUE TITLE
lvl 40 keep guards in T2 

### ISSUE THREAD

**Issue by guiltanas** [WarEmu/WarBugs#4537]
4 of the guards on the first floor in T2 keeps are lvl 40 this is both in order and desto keep.

**Comment by DanaBloodkiss** [comment]
NPC names ...

**Comment by guiltanas** [comment]
Order side x4 Pyromancer lvl 40-41
Desto side x4 Idolator lvl 40-41 and x2 Defiler lvl 41

**Comment by guiltanas** [comment]
![kithkannan_000](https://cloud.githubusercontent.com/assets/16751630/13328341/62d90076-dbee-11e5-9c11-c5bb9968e473.jpg)

**Comment by Torquemadra** [comment]
fixed next patch
