### ISSUE TITLE
[NPC] Inevitable City - Missnamed flavour NPC

### ISSUE THREAD

**Issue by Luranni** [WarEmu/WarBugs#4538]
At the doorway into the Apex from the Flight Master in IC there's an NPC "Derl Iceheart (Male Only), he appears to have replaced a Dread Sentry.

![male only bu](https://cloud.githubusercontent.com/assets/16735846/13322780/5eedac18-dbd6-11e5-8d62-e96993bb7530.jpg)

**Comment by DanaBloodkiss** [comment]
Removed the "(Male Only)" for now. Not sure if he replaced a Dread Sentry.

**Comment by Ryanfawkez** [comment]
http://war.mmodb.com/bestiary/derl-iceheart-3363.php
He's supposed to be standing on the other side, that's all. He's practically still where he's supposed to be; at the entrance to the Apex.

**Comment by Evildoor** [comment]
I doubt that anyone should bother much about whether he stands on the correct side or not. Closing.
