### ISSUE TITLE
Flame Breath should proc Funnel Power

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#4540]
same as flames of ruin. same video shows Funnelpower proccing from flamebreath at 1.53/1.54.

![image](https://cloud.githubusercontent.com/assets/13809443/13323079/0a57d474-dbd8-11e5-83ae-c7a4214c179d.png)

https://www.youtube.com/watch?v=Hk-UVsBESiU

**Comment by bloodi** [comment]
No it does not, you can clearly see him using scorched earth, thats what is proccing funnel power.

Funnel power does not proc of dots, full stop.

**Comment by Tiggonos** [comment]
but funnel power is before scorched earth. he uses flame breath on 1.52.00?

**Comment by Tiggonos** [comment]
ok funnel power mentiions "directly damagin abilities" while flames of rhuin speaks of attacks.

closing here.
