### ISSUE TITLE
"Harbinger Ring of Calamitous Fervor" BoP

### ISSUE THREAD

**Issue by GankbusOsmium** [WarEmu/WarBugs#4541]
The item "Harbinger Ring of Calamitous Fervor" is bound on pickup. I am not sure whether this was intended or not.
Please check.
![11](https://cloud.githubusercontent.com/assets/16682555/13323097/3089e51a-dbd8-11e5-90da-1b4175166326.png)

**Comment by DanaBloodkiss** [comment]
http://www.warbits.com/gold-items-9185-Harbinger-Ring-of-Calamitous-Fervor.html

It's correct. Next time get sources yourself please.
