### ISSUE TITLE
Inevitable Power - Lady Krueger unkillable

### ISSUE THREAD

**Issue by fiazco** [WarEmu/WarBugs#4543]
NPC Lady Krueger needed for the "Curruptor's Crown" cant be killed.

Error Message in chat was : Formatexeption was thrown from parseuint32"

The NPC stays at 1% hp. wont despawn/respawn. 

Can't be killed by GM, as Vistyn tried to.

**Comment by Torquemadra** [comment]
looking into this

**Comment by cimator** [comment]
Tried today, both lady krueger and the honorable deceit champ doesnt respawn. They just stay without hp and cant hit.

**Comment by Torquemadra** [comment]
There was a flaw in the db causing exceptions, fixed next patch both
