### ISSUE TITLE
Pyromancer at order keep for T2

### ISSUE THREAD

**Issue by Psychotrope** [WarEmu/WarBugs#4544]
![flambibi_001](https://cloud.githubusercontent.com/assets/17417573/13328174/8d91545e-dbed-11e5-9157-795466257266.jpg)
The pyromancer, a BW npc in the order keep, is actually lvl 40 and 41, they insta kill everyone.
Some ppl say it's the same problem for destro keep.

**Comment by Evildoor** [comment]
#4537
