### ISSUE TITLE
Wrong drop Item

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4545]
Level 5 Mob dropped Level 23 item at Engine Number Nine PQ Dwarf Chapter 2
![toufekiaaaa_002](https://cloud.githubusercontent.com/assets/16864486/13328202/1ce2a90c-dbf6-11e5-80e1-f2b12cc7f81e.jpg)

**Comment by genisaurus** [comment]
Fixed in next patch
