### ISSUE TITLE
Raven War Breakers Appearance Mismatch

### ISSUE THREAD

**Issue by ArmedAssaulted8** [WarEmu/WarBugs#4549]
Raven War Breaker NPCs became really messed up after latest patch, they have their regular look swapped for that of Raven War Sappers. Not all of them look like that, but I found many in different places, camps, etc

![azalith_000](https://cloud.githubusercontent.com/assets/17481397/13330625/0f43c584-dc13-11e5-958f-7268cbb8422c.jpg)

stuff of nightmares

**Comment by DanaBloodkiss** [comment]
Fixed in next.
