### ISSUE TITLE
A Sampling of Sorrow

### ISSUE THREAD

**Issue by Cupkiller** [WarEmu/WarBugs#4550]
The quest is just not working... Completely. Trying to kill the diseased nordlanders and nothing happens. Even Plagued Wolves don't give anything.

**Comment by Evildoor** [comment]
#102 is supposed to be fixed...

**Comment by Cupkiller** [comment]
Tried to do it with my Choppa ork day before yesterday and with chaos zeolot yesterday. 

Killed about 20 of the mobs and even tried to kill wolves but nothing happens.

**Comment by Ryanfawkez** [comment]
Since the loot system was changed, quest items no longer drop from NPCs.

**Comment by genisaurus** [comment]
Fixed in next patch.
