### ISSUE TITLE
Public quest chests.

### ISSUE THREAD

**Issue by Cupkiller** [WarEmu/WarBugs#4552]
In Norsca at least. When you complete these quests, there are no chests or there are one but it is invisible but active. Anyways, you can get your reward.

**Comment by DanaBloodkiss** [comment]
Examples of PQs.

**Comment by Cupkiller** [comment]
1.Holmsteinn Revisited - no chest at all.
2. Destruction of the Weak - during all stages there was an invisible chest but I was able to click it and nothing more. When all stages were completed the chest didn't fix itself so it was still invisible and I with 3 more people weren't able open it.

Additional info about Suderholm - We weren't able to do it because of the demon level 4 and rank LORD in the middle of the village. It does enormous amount of dmg. Not sure if its a bug or not.

**Comment by nalgol** [comment]
this is all work in progress atm don't expect everything working at once i just added 360 items to the baglists by hand just for the first 4 chapters -_-

**Comment by wargrimnir** [comment]
All chest should currently spawn if the PQ can be finished. Not all are implemented fully yet.
