### ISSUE TITLE
T2 RvR and scenario bolster 

### ISSUE THREAD

**Issue by Deratarin** [WarEmu/WarBugs#4554]
Bolster in the T2 zones is broken. Characters above level 21 are not bolstering like 14-20lvl characters.

**Comment by Soulwhisper** [comment]
What do you mean?
Changelog 20/02
- Bolster will now overbolster players depending on their rank.
- The tier caps are temporarily 13, 26 and 35.

**Comment by Deratarin** [comment]
So if your character a 21 rank he will not have a bolster buff on t2 and will have to fight against bolstered to rank 26 characters with higher damage and heal?

**Comment by Tiggonos** [comment]
same in t3 (randomly) lets see if the fix will fix that too. will open ticket if it persists after push.
