### ISSUE TITLE
[SW] Broadhead Arrow damage scale issue

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#4555]
2096 dmg dot tick

![d93c9f9499715dd11894fb5587c6adffae264677ef851d41cf pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/13031465/13333413/da3d7c20-dc41-11e5-8dba-ebbef8a30cb8.jpg)

**Comment by Evildoor** [comment]
#2645
