### ISSUE TITLE
Fling Explosives Engineer Morale 4.

### ISSUE THREAD

**Issue by Rowanmantle** [WarEmu/WarBugs#4556]
Termos from the guild Porn Factory brought my attention to this, My current main is Boulder the engineer and tonight i used my m4 for the first time on the dark elf keep in avelorn during a push. Termos then pm'd me notifying me of this bug and has provided sc's the m4 seems to hit its full 4s duration in 1 sec.
![6uloddp](https://cloud.githubusercontent.com/assets/17483417/13338378/ad6c6c00-dc29-11e5-90a7-bbb03ff417d4.jpg)
![nmcb6nv](https://cloud.githubusercontent.com/assets/17483417/13338382/b57cfc98-dc29-11e5-9db4-c87a9ffe4030.jpg)

**Comment by Zanilos** [comment]
Link doesn't work, just drag the screenshot into the text box, no need to upload to image hosting sites.

**Comment by ozarmidrashim** [comment]
Fixed on live.
