### ISSUE TITLE
PQs Order - Blighted Isle 

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4557]
- [ ] The Public Quest window(UI) sometimes is not working for PQs.

**UPDATE after more testing** Relogging fixes it.Acts weird anyway.Sometimes it pops up sometimes it wont.For all PQs Elf/Dwarf T1 to T3.

**Comment by Soulwhisper** [comment]
Yeah im pretty sure its not working as it should everywhere ,except Empire T1(where it works fine)

**Comment by nalgol** [comment]
pq's dont show if you don't have the chapter influence display (witch i don't fully understand how to send it right yet  only fix currently is to run around till you get one it from somewhere it will work for all pqs then)

**Comment by Soulwhisper** [comment]
I did what you said if you mean to get the unlock that shows up on the screen. I tried moving all over Blighted Isle but for some reason when i enter PQs in Blighted Isle it only announces the mid screen message (Stage 1 etc etc) Influence bar UI doesnt appear. This doesnt happen in Empire.

**Comment by Soulwhisper** [comment]
**UPDATE**Actually i stayed there till stage 2 resets.And guess what.UI appeared but it was stuck to : Resseting in 0:00 and it stays like that forever.

**Comment by Soulwhisper** [comment]
Managed to fix it only by travelling to Chrace through Flight Master which forced the UI bar to appear (T1 RvR) and from there i travelled on foot to Blighted Isle again.

**Comment by Soulwhisper** [comment]
Closing.UI has to do with this #4441
