### ISSUE TITLE
Quest ; The Dark Heart of Avelorn CH. 11 Grimwater

### ISSUE THREAD

**Issue by pixie126** [WarEmu/WarBugs#4558]
I attempted to pick this quest up from Intelis Raincaller and got this message in the quest window:
Invalid creature, plz report to GM. Quest ID 35021, objld=33740  0 of 1

Suppose to use Dark Heart Gem to lure out Blackheart (treekin), destroy him, then return to Intelis Raincaller.

Thank you.

**Comment by Ryanfawkez** [comment]
Can't use quest items to trigger spawns at the moment, but I'll look into how I can fix this quest for now.

**Comment by Ryanfawkez** [comment]
Step fixed, NPC added, questmarker added. Fixed in next patch.
