### ISSUE TITLE
Quest line (An Army Marches)

### ISSUE THREAD

**Issue by mrSVS** [WarEmu/WarBugs#4561]
Still don't work.
At second stage do not drop quest item, which the begin 3 stage - check near cavern.
No chance for get Crimson Cloak http://www.arsenalofwar.com/armor/Order/Crimson%20Cloak 
Last check 25.02.2016

**Comment by Evildoor** [comment]
#2196 is supposed to be fixed.

**Comment by Torquemadra** [comment]
it works 100%, please read the mission and its objectives before posting

**Comment by mrSVS** [comment]
Thanks for fix!
I'm check quest at morning 25.02.2016. Patch is apply later :) 
Agree, works 100%.
