### ISSUE TITLE
Dark Elf Chapter 4, small size Camp-Guardian

### ISSUE THREAD

**Issue by Aluviya** [WarEmu/WarBugs#4562]
![neue bitmap](https://cloud.githubusercontent.com/assets/17249318/13350775/802cceca-dc82-11e5-96cd-2c22aeead4a5.jpg)

Size seems buggy.

**Comment by Torquemadra** [comment]
fixed next patch

**Comment by ElMosquito** [comment]
There is a tiny guard in chapter 2 as well.
![small](https://cloud.githubusercontent.com/assets/16590792/13363676/edb04678-dcca-11e5-986f-d75a9716e812.jpg)

**Comment by Torquemadra** [comment]
They will all be fixed, it's the same Npc spawned multiple times
