### ISSUE TITLE
Boundless Weapons - weird stats

### ISSUE THREAD

**Issue by zernichter** [WarEmu/WarBugs#4563]
hi, 

i'm wondering about the stats on the new boundless 2h & 1h weapons.

 the boundless direblade ( chaos 1h weapon - sword chosen) stats: 40 str & 40 toughness

the boundless deathaxe ( chaos 2h weapon - greataxe chosen ) stats: 32 str & 32 weapon skill & 6% disrupt

the boundless kife ( chaos 1h weapon - dagger zealot ) stats: 16 willpower & 16 int & 3 % disrupt

the boundless witchstaff ( dark elf 2h weapon - sorc staff ) stats: 79 int & 79 wounds.

so hows it come that some of the weapon stats differ that much ? i think someone should look into this and adjust them in the right way 

![zernichter_064](https://cloud.githubusercontent.com/assets/17494646/13351840/d19bab30-dc89-11e5-9451-648b332bd3e9.jpg)
![zernichter_063](https://cloud.githubusercontent.com/assets/17494646/13351854/dca80f32-dc89-11e5-8f5f-585bb5c305ac.jpg)
![zernichter_065](https://cloud.githubusercontent.com/assets/17494646/13351864/e9faa6cc-dc89-11e5-9587-e8fde3711453.jpg)

**Comment by Evildoor** [comment]
#4486
