### ISSUE TITLE
Journal unlocks

### ISSUE THREAD

**Issue by Shalliar** [WarEmu/WarBugs#4565]
Some unlocks, like "Norse Tribes" (Screamer near chaos portal in Norska) or unlocks about noteworthy persons (f.e. Eidolon and Vaulkor) arent working.

**Comment by Shalliar** [comment]
![winfrid_003](https://cloud.githubusercontent.com/assets/17254643/13352895/892a3d54-dca1-11e5-856f-db6c4dde07a1.jpg)

**Comment by Luth-RoR** [comment]
Fixing _all_ ToK unlocks is an ongoing process. The report is to unspecific.
Also: https://github.com/WarEmu/WarBugs/issues/3799
