### ISSUE TITLE
Bolster

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4566]
![paterellas_001](https://cloud.githubusercontent.com/assets/16864486/13353201/5ebe4cf0-dc9b-11e5-8f02-e20f24e6bc88.jpg)
11 level player does not get boolster. Happened with a level 2 player.

**Comment by Evildoor** [comment]
Have they lvled up on that sc?

**Comment by Soulwhisper** [comment]
No. Scenario just started.Shadow Warrior is 11 level from the beggining.

**Comment by Evildoor** [comment]
Made some tests on this after T4 patch, bolster seems to be screwed. What i've noticed:
1) Buff icon is different from chat message. Yes, i know where this possibly comes from and that it's trivial, just listing it for the record.
2) Problems happen in T1, T2 and T3.
3) RVR is affected as well as scenarios.
4) Bolster to different level: in T2, lvl 11 Sorcerer is bolstered to 23 (according to chat), lvl 19 is bolstered to 21, and lvl 21 is not bolstered.
5) Stats are bolstered too much. I've tested damage on a lvl 16 champion rat in RVR:

- lvl 11, green items of Vengeance from T1, no tactics, no mastery/renown points spent, no talismans: ~500 dmg doombolt (damage done + mitigation, of course).
- same + lvl 19: ~400 dmg doombolt.
- same + lvl 21: ~ 380 dmg doombolt. 
- same + lvl 21 + green items of Conguest: ~ 425 dmg doombolt.
- same + lvl 21 + green items of Conguest + int tactic + 20 renown points into int: ~ 515 dmg doombolt.

6)  T4 seems more or less ok, all levels are bolstered to 40 (apart from 40, ofc), and damage across the board is less different.
