### ISSUE TITLE
Bestial tokens

### ISSUE THREAD

**Issue by Kelthas** [WarEmu/WarBugs#4567]
Killed the following mobs today and did not receive bestial tokens or
the tome unlocks that comes with them.

Averlorn, Goremaw ( Dispense Justice )
High Pass, Bloodscent ( Engage the Gorger )
Troll Country, Bridge Troll ( Takes its Toll )

**Comment by Ryanfawkez** [comment]
Seems their ToK unlocks got wiped. Fixing.
