### ISSUE TITLE
Durak's Gate PQ - Ekrund

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4569]
There are duplicate MOBs Choppas 4/5 - 35/36 levels.35-36 shouldnt exist.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by Soulwhisper** [comment]
Im reopening this.
- There are still duplicate MOBs Choppas 4/5 - 35/36 levels.35-36 shouldnt exist.
- You cant interact with powder on Stage 2 so you cant progress the PQ.
- PQ area ID is not correct as it should with (8/8/2016 changelog patch). Needs redesign.
