### ISSUE TITLE
Bug on the Renown ability tab

### ISSUE THREAD

**Issue by Psychotrope** [WarEmu/WarBugs#4571]
There is a display bug on renown ability training tab, i'm RR 28 and i have 100 point to spend, i can use them all but i cant click on "train".
![flambibi_004](https://cloud.githubusercontent.com/assets/17417573/13359959/feaa2fa2-dcb6-11e5-8e96-77318b72a91c.jpg)

**Comment by Psychotrope** [comment]
Up

**Comment by Evildoor** [comment]
> Up

This is not a forum. Read the rules of the bugtracker.

**Comment by taccr** [comment]
This is not even server related.
You are using advancedrenowntrainer addon.

The renown information is not even pulled from the server (hence 100 points available) when not standing next to a trainer which is clearly the case here. You are also unable to train renown skills when not in range of a trainer.

It's the addon that doesn't work correctly here and not the server.

**Comment by Evildoor** [comment]
Oh, so it's restricted to addon? Ok then.
