### ISSUE TITLE
WE influence reward Dark Elf Ch.1

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#4573]
Dark Elf Chapter 1's third influence rewards for witch elf shows a chalice as an option when retrieving your reward from the Rally Master. In the Tome of Knowledge there is no chalice, only when speking to the Rally Master.
![chalice](https://cloud.githubusercontent.com/assets/16590792/13363164/51d40e3a-dcc8-11e5-8447-a5af48ac109d.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next.
