### ISSUE TITLE
Pillager's dark offering - lvl 35 looted in T1 RvR

### ISSUE THREAD

**Issue by shamallow** [WarEmu/WarBugs#4574]
Hi, i've just looted a marauder ring lvl 35 with my lvl 12 witch elf...
I believe devs have to know about it.
![kissmay_001](https://cloud.githubusercontent.com/assets/16374367/13364601/06191eb0-dcd0-11e5-9274-36170e2d3f53.jpg)

**Comment by shamallow** [comment]
I'm not one to ask something like that, but is it worth to have the special mount ? :)

**Comment by genisaurus** [comment]
Fixed in next patch.
