### ISSUE TITLE
Renown abillity respec bug

### ISSUE THREAD

**Issue by jaxel90** [WarEmu/WarBugs#4575]
When you respec renown abilities, it does give you your renown points back but does not reset the abillities or restet used points, until you close and reopen the window.

In this screenshot ive just respecced after having taken 2 lvls of defender but as you can see defender is not reset
![eilonna_000](https://cloud.githubusercontent.com/assets/17504132/13365748/26fa54e4-dcd7-11e5-8f16-b64b6ad32eb3.jpg)

Hope this helps you any, otherwise gj and thanks for an awesome revival of something that should never had died ;)

Best regards
Jaxel

**Comment by Evildoor** [comment]
May be related to #1486.

**Comment by sioding** [comment]
this is fixed
