### ISSUE TITLE
Visual Bugs

### ISSUE THREAD

**Issue by Lidskjalf** [WarEmu/WarBugs#4578]
Recent update with a couple visual bugs... Never seen a bug report on here with something similar to my attached screenshots.

First Screenshot is on the way to Kinschels BO in T2.
2nd/3rd in Avelorn WC.

![sykex_002](https://cloud.githubusercontent.com/assets/17505385/13368001/16c30acc-dca4-11e5-9403-d26323e6c14d.jpg)
![quex_001](https://cloud.githubusercontent.com/assets/17505385/13368000/16c273dc-dca4-11e5-91b9-b7f23147ece7.jpg)
![quex_002](https://cloud.githubusercontent.com/assets/17505385/13368002/16c457a6-dca4-11e5-829f-1bbbca6a492f.jpg)

**Comment by Evildoor** [comment]
> Never seen a bug report on here with something similar to my attached screenshots.
#4539 

Next time - one report per problem. While both bugs here are visual, one of them is related to NPCs, and other one to items.

**Comment by Lidskjalf** [comment]
First time posting for RoR, duly noted.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/4539 is fixed.

**Comment by Luth-RoR** [comment]
The other one is a client bug happening when tabbing out and back in several times after the game ran for a while. 
Can't be fixed for now (and maybe never).
