### ISSUE TITLE
Training Course (Quest)

### ISSUE THREAD

**Issue by Nelyous** [WarEmu/WarBugs#4579]
For the quest titled "Training Course" T1 Empire, when the quest is completed I am not able to turn in. Viktor Riese will not accept the final turn in. The star is orange but, will not complete.

**Comment by Torquemadra** [comment]
Did you select all rewards?

**Comment by Nelyous** [comment]
I did

**Comment by Torquemadra** [comment]
works on dev, guess wait till next patch
