### ISSUE TITLE
T2 Osland bugs 3 Hugo Von Prittes

### ISSUE THREAD

**Issue by Vandorkholme** [WarEmu/WarBugs#4580]
Stonetroll keep/Mandreds has level 40 normal guards on the bottom floor instead of whatever level champions that were there. Also there are 3 Hugo Von Prittes.
http://i.imgur.com/nIXNN5z.jpg

Edit: The guards inside also aggro people hitting the door without using AoE
Edit: Additionally there is a duplicate Heathgut troll near Mandreds

**Comment by Torquemadra** [comment]
fixed next
