### ISSUE TITLE
Questline reset. 

### ISSUE THREAD

**Issue by guiltanas** [WarEmu/WarBugs#4583]
After the restart at ca 19.00 the 26th I found that all my quests had been removen from my guest log and that ha had to pick them up again, I did not think any more of it until i came to altdorf and found that i could to all the skaven quests again... I dont know how this happend or if it was anymore than me. none of my friends had the same bugg.
the items i know i should not have are now in my bank vault since i dont know where to put them. 
![screenshot_4](https://cloud.githubusercontent.com/assets/16751630/13370293/a2f62f60-dd03-11e5-94f6-c15a0d9eaee6.png)
![kithkannan_000](https://cloud.githubusercontent.com/assets/16751630/13370299/b638b1ec-dd03-11e5-86e6-43e5619f9c67.jpg)

**Comment by Evildoor** [comment]
#2001
