### ISSUE TITLE
Cannot dye set item

### ISSUE THREAD

**Issue by Partizan-Rusi** [WarEmu/WarBugs#4585]
I cannot dye [Obliterator Vestments] RVR set item for RP. I clearly remember in original WHO you could dye any armor item so its bug.
Fix this bug, armor looks ugly green.

![ror dye](https://cloud.githubusercontent.com/assets/16727243/13370737/09240104-dd22-11e5-85ee-a6fc342113fd.jpg)

http://i.imgur.com/hjUD1Do.jpg

**Comment by Torquemadra** [comment]
fixed next patch
