### ISSUE TITLE
T2 Osland Resource Carriers

### ISSUE THREAD

**Issue by Vandorkholme** [WarEmu/WarBugs#4588]
I've seen 2 Empire and 1 Chaos thus far
Between destro wc and Mandreds http://i.imgur.com/nvi68y9.jpg
Behind Mandreds http://i.imgur.com/nzzyNVZ.jpg
and there is a Chaos one that spawns at Kinschel's Stronghold BO

**Comment by Torquemadra** [comment]
cleaned on dev, fixed next patch
