### ISSUE TITLE
Aliance ranks

### ISSUE THREAD

**Issue by Guerra-warhammer** [WarEmu/WarBugs#4589]
hi,

i find out  that the guildmember who has the **guild rank 0**, i cant upgrade in the aliance. hope for a fix and sorry for the bad english ;)

screens:
http://www.fotos-hochladen.net/view/xarloc031u46syri1vo.jpg
http://www.fotos-hochladen.net/view/xarloc0309nwy4bh5rp.jpg
http://www.fotos-hochladen.net/view/xarloc029ox5gdsznej.jpg

**Comment by nalgol** [comment]
this is intentionally in order to not have to promote every single guild member to be able to use alliance chat every guild member rank > 0 is automatically alliance rank member
rank 0 is reserved if you want guildys excluded from alliance chat
