### ISSUE TITLE
skill suppression [chosen]

### ISSUE THREAD

**Issue by Durhim** [WarEmu/WarBugs#4590]
Hello,

I can't see in the caracter tab this +25%  to my character parry when I use "Suppression"  in fight. 
I have actually 21% parry and in a fight I never see one parade comes out ? So it should work for approximatly 1/5 hit and with suppression up to 46% ?

So is it bugged ?

regards

**Comment by Evildoor** [comment]
What does .getstats say?

**Comment by taccr** [comment]
Works for me. Paperdoll and getstats match.

**Comment by Tesq** [comment]
it work, suppression can be removed by shatter ench, and do not stack (also mixed defense ) with  dev proc.

**Comment by Evildoor** [comment]
No confirmation. 2 people claiming report is false. Closing.
