### ISSUE TITLE
Orclings

### ISSUE THREAD

**Issue by Aelice** [WarEmu/WarBugs#4597]
![loena_004](https://cloud.githubusercontent.com/assets/16370505/13374741/9fd2f900-dd8d-11e5-909d-e1fd62a93cd8.jpg)
Found at Saphery 38000, 47600

**Comment by Torquemadra** [comment]
name of mob?

**Comment by Aelice** [comment]
Yukha's Boy

**Comment by Torquemadra** [comment]
fixed next patch
