### ISSUE TITLE
Items from Rats in Altdorf

### ISSUE THREAD

**Issue by Elueh** [WarEmu/WarBugs#4598]
Lvl 1 Rats in Altdorf drop lvl 25 green Worked Beastman's Horn item and green Worked Mailcoat of Volition,Worked Steadkeeps of Brawn item which has no lvl requirement at all.

**Comment by Elueh** [comment]
also, no level on item Worked Steadkeeps of Brawn

**Comment by genisaurus** [comment]
Fixed in next patch.
