### ISSUE TITLE
White Lion NPC

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#4599]
In the Blighted Isle around the Dreamshade Forest PQ (next to Dark Elf Chapter 3) there used to be white lions to kill for lion pelt quest item. They still drop the item and they sound like lions but they are not lions anymore. Instead they are looking like a living armor:
![lionbug](https://cloud.githubusercontent.com/assets/16590792/13375323/3b2a1312-dd9c-11e5-983e-bd87c75e9327.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by ElMosquito** [comment]
Even though this thread is closed and this issue were supposed to be fixed, it seems like the mutant white lions are back in the Blighted Isle and Chrace, and they are stuck on 0 hp.
![lion](https://cloud.githubusercontent.com/assets/16590792/13713879/87b71ade-e7cb-11e5-94c4-cdb1ab1da4ee.jpg)

**Comment by ElMosquito** [comment]
The white lions in Chrace also gives a message like this:
![wrong](https://cloud.githubusercontent.com/assets/16590792/13717352/2df860a0-e7e1-11e5-93b1-3f1e49685018.jpg)

**Comment by DanaBloodkiss** [comment]
Fixed on dev server.
