### ISSUE TITLE
Quest NPC killed by nearby mobs

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#4600]
In the quest Innocence Challenged you are supposed to speak to Goldenwing Eyas (The Blighted Isle at the Golden Tor PQ). The problem is that the NPC is killed by the nearby birds. It spawns at multiple spots but all are being killed over and over again and you have to wait for one to respawn and save it in order to proceed with the quest.
![deadquest](https://cloud.githubusercontent.com/assets/16590792/13375387/23ced2a0-dd9e-11e5-9901-f08faabf3709.jpg)

**Comment by Ryanfawkez** [comment]
Cannot fix this yet as NPC relations can't have exceptions to them; to prevent them from attacking each other they'd all have to be neutral to each other, by which you cannot hand in the quest to them.
