### ISSUE TITLE
Quest: Due Recognition

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#4602]
In the description of the quest Due Recognition you are supposed to find Lordling Kylar in the Blighted Isle. Lordling Kylar is lying dead in the Dreamshade Forest but when interacting with the body nothing happens. Instead, to proceed with the quest, there is a high elf on a horse named Kylar in the same area, which you have to kill.
Maybe this is already a known issue, and it is not really a problem, but when reading about the quest in the tome of knowledge you are told to find a missing Lordling Kylar. Interacting with the dead body seems to be the right thing to do to proceed the quest, not to kill a mounted high elf named Kylar.
![kylar](https://cloud.githubusercontent.com/assets/16590792/13376155/30d8128a-ddb3-11e5-9bb9-6048a3351687.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
