### ISSUE TITLE
[Faction] Duel/Target Bug 

### ISSUE THREAD

**Issue by Lidskjalf** [WarEmu/WarBugs#4607]
As posted, a targeting/nameplate bug after a duel with another member of the same faction. 

![quex_008](https://cloud.githubusercontent.com/assets/17505385/13377228/3c47f9ce-dd8f-11e5-94ff-2d0d5065f114.jpg)
![quex_009](https://cloud.githubusercontent.com/assets/17505385/13377229/3c48b53a-dd8f-11e5-8baf-e339ff47f325.jpg)

**Comment by noisestorm** [comment]
Only happens if you not cleanly 'kill' someone during a duel. Also you can just re-challenge this person, kill him(or get killed) and the problem should be resolved as well.

**Comment by Luth-RoR** [comment]
These kind of bugs will likely never be fixed as this is an unsupported feature that never existed on the mythic servers. Furthermore there could be client restrictions that can't be passed atm.
