### ISSUE TITLE
Ironbreaker oathfriend bug

### ISSUE THREAD

**Issue by AlistaireCrowley** [WarEmu/WarBugs#4613]
Oathfriend giving grudges even when you are not in the same area.

**Comment by Evildoor** [comment]
#2581 is supposed to be fixed...

**Comment by Ryanfawkez** [comment]
I play an Ironbreaker myself and I can confirm that this bug has persisted since Jan 1st, up to this day.

**Comment by ozarmidrashim** [comment]
This is a nitpick on #2581. The check on OF and DP blocks them from in different regions and not in different zones, because having an OF just over a region border and not getting grudges from it would be pretty bloody stupid.

Changed to 300ft range.
