### ISSUE TITLE
Pets not disengaging when stealthing

### ISSUE THREAD

**Issue by Gorgust** [WarEmu/WarBugs#4615]
I have noticed that when a pet gets send after you. Either from a WL or SH it will stay on you after you have entered stealth. Rendering escape impossible and kind of unfair since it requires little to no effort finding a stealthed target you could not find otherwise.

I dont know if this is intentional or just a oversight in the programming of the AI.

**Comment by ozarmidrashim** [comment]
Nope. The pet will stay on you if it was within 30 ft when you cloaked. This is not a bug.
