### ISSUE TITLE
NPC don't give quest

### ISSUE THREAD

**Issue by Alouqua** [WarEmu/WarBugs#4616]
Hi, I searched for a gun warhammer of skin, and the only one who gives he's the NPC Celestial wizard Vladesaul in High pass, with the quest "Celestial Défender' but i find the NPC, but he's does'nt give the quest.

**Comment by Ryanfawkez** [comment]
The quest is given by Ernst Kastner, in Chapter 12 Empire.

**Comment by Evildoor** [comment]
No response, closing.
