### ISSUE TITLE
Scavenge instead of butcher

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#4618]
I have noticed that the low level mobs hare, deer and stag, that are scattered around the world, can not be butchered like other animal mobs. Instead they can be scavenged for talisman stuff, which doesn't seem right since they are animals.

**Comment by genisaurus** [comment]
Please note the specific animals that have this problem.

**Comment by ElMosquito** [comment]
Rank 1 and rank 2 hare, deer and stag:
![hare](https://cloud.githubusercontent.com/assets/16590792/13381085/802daaf8-de52-11e5-9b4e-7dfa0dae0619.jpg)
![deer](https://cloud.githubusercontent.com/assets/16590792/13381090/8f6366fc-de52-11e5-80bb-42eec4ef17c5.jpg)
![stag](https://cloud.githubusercontent.com/assets/16590792/13381091/945c2e28-de52-11e5-99a1-c1faa3aabb22.jpg)

**Comment by genisaurus** [comment]
Thanks, fixed in next patch.

**Comment by ElMosquito** [comment]
I also found out that rank 2 rabbit and lizard can be scavenged instead of butchered:
![rabbit](https://cloud.githubusercontent.com/assets/16590792/13381580/d9abfbcc-de5f-11e5-830a-06b4518279f8.jpg)
![lizard](https://cloud.githubusercontent.com/assets/16590792/13381582/dd9b2a0a-de5f-11e5-8b1b-08d3f6922db7.jpg)
