### ISSUE TITLE
ToK : Item name "Troll's Dinner" not work

### ISSUE THREAD

**Issue by TaeBal** [WarEmu/WarBugs#4619]
<img src=http://i.imgur.com/hgtuwpj.jpg>

http://www.pwnsan.com/?p=783

Not work atm same like this
"Broken Wight Blades"
http://warhammeronline.wikia.com/wiki/Broken_Men,_Broken_Blades

**Comment by Lheana** [comment]
I think this issue is now fixable. 'Troll's Diner' correctly drops on Mudbelly Trolls, but right-clicking on it does not provide the unlock 'Who Is Up for Seconds'.
