### ISSUE TITLE
Arnholdt's Company NPC's do not render until you walk to the middle of the camp.

### ISSUE THREAD

**Issue by Kelanos** [WarEmu/WarBugs#462]
When dying in certain parts of Nordland, upon respawning at Arnholdt's Camp, the North side NPC's (Renown Gear Merchant, etc) do not appear until you walk to the centre of the camp (by the great cannon). 
![barbad_004](https://cloud.githubusercontent.com/assets/9700848/5055534/bdb5e2b4-6c5c-11e4-8860-d1717d8f8fce.jpg)
![barbad_008](https://cloud.githubusercontent.com/assets/9700848/5055536/c02ba254-6c5c-11e4-895f-48fa34c70b05.jpg)

**Comment by Evildoor** [comment]
IIRC, this is a general issue which can happen in many places and which was present on live WAR servers, so we can't do much about it. Closing unless someone states otherwise.
