### ISSUE TITLE
Unable to equip reward from first Empire PQ

### ISSUE THREAD

**Issue by Gideon404** [WarEmu/WarBugs#4620]
PQ reward Templar's Cracked Cassock.  Requires minimum rank 2 and career warrior priest.

None of the criteria are red.  Unable to equip on rank 12 warrior priest.  If it is relevant, female toon.

**Comment by Ni7ek** [comment]
just noticed the same problem

**Comment by Ryanfawkez** [comment]
Was set to medium armor instead of medium robe; WPs can only wear the latter. Fixed in next patch.
