### ISSUE TITLE
[Shield] of the Eternal - Missing Stat

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#4621]
The blue level 35 shields are missing an additional stat. While they have 42 thoughness they are lacking the 2% block which e.g. the Bandit shields had.

As comparsion one could also look at other Eternal offhands...

Dwarfen shield: Defender of the Eternal
High Elf shield: Pavise of the Eternal

I don't know the name of the Empire shield though...

**Comment by Torquemadra** [comment]
http://www.warbits.com/gold-items-8335-Defender-of-the-Eternal.html

adding stats for next patch
