### ISSUE TITLE
ToK: From Mouth to Neck

### ISSUE THREAD

**Issue by bughunterror** [WarEmu/WarBugs#4622]
The tome unlock From Mouth to Neck is not unlocking. Talking with Golgrund Stonefist does not give you the Amulet of Fangs, but you can still kill the chaos hounds for the Chaos Hound Fangs. Collecting 10 fangs and talking with Golgrund does not unlock From Mouth to Neck.

http://warhammeronline.wikia.com/wiki/From_Mouth_to_Neck

**Comment by Ryanfawkez** [comment]
Item interaction/hand-in is unsupported in general at the present time.

**Comment by Yellowpillow** [comment]
reward is Jewelry set item. If you going to fix ToK unlocks - please start from accessories, they more important than titles.
