### ISSUE TITLE
Bugged mobs at PQ

### ISSUE THREAD

**Issue by Doomsday82** [WarEmu/WarBugs#4625]
Some mobs at PQ cant die. They have 0 hp, but stayin and not die and not check for quest. For example:
![krohus_033](https://cloud.githubusercontent.com/assets/13207459/13381030/3a456570-de62-11e5-9a9f-c4892febcba8.jpg)
eagle claw stayin after damage with 0 hp, and still 0/10 for quest.
Same problem with champions in tower at Temple of Heimkel PQ in High Pass.

**Comment by Torquemadra** [comment]
need precise names

**Comment by Doomsday82** [comment]
cant check name of what champs, because u add hero mob into tower door.

**Comment by Lheana** [comment]
All NPCs in PQ Temple of Heimkel are ok.

**Comment by sioding** [comment]
No reaction from the report creator - close that after Lheana checked that.
