### ISSUE TITLE
[Scenarios] Highpass Cemetary Bug

### ISSUE THREAD

**Issue by Vandorkholme** [WarEmu/WarBugs#4629]
http://i.imgur.com/ufqsVbs.jpg

Both Crypt and Stag have a tombstone in place of where the cover of the coffin should be.

**Comment by Torquemadra** [comment]
should be fixed next patch

**Comment by Torquemadra** [comment]
#4832

**Comment by Torquemadra** [comment]
Trying again, hopefully fixed
