### ISSUE TITLE
Slaughterer's War Shroud missing appearance

### ISSUE THREAD

**Issue by rameden** [WarEmu/WarBugs#4631]
The item [Slaughterer's War Shroud ] for the slayer is missing it's in game appearance. Right now it doesn't show anything at all.

**Comment by rameden** [comment]
Item ID: 408525
Item Model: 2017

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by rameden** [comment]
Thanks Ryan.

PS: Nice Rabbit!
