### ISSUE TITLE
Dark Elf Warcamp Siege Weapons

### ISSUE THREAD

**Issue by Vandorkholme** [WarEmu/WarBugs#4633]
In most Dark Elf warcamps the DE repeaters seem to have been replaced with the skin for HE repeaters.

**Comment by Vandorkholme** [comment]
http://i.imgur.com/2yXphua.jpg

**Comment by Gideon404** [comment]
Related? #4262

**Comment by Gobtar** [comment]
The bolt throwers in #4262 are dark elf Bolt throwers, and is what the Dark Elf single target siege weapon should look like.

**Comment by Gobtar** [comment]
![de_bolt thower](https://cloud.githubusercontent.com/assets/7888608/13720406/35258ac2-e7de-11e5-8e57-1988fda3680e.jpg)

**Comment by Evildoor** [comment]
Checked Avelorn and The Blighted Isle warcamps (screens posted are from there), siege weapons are correct. Closing.
