### ISSUE TITLE
report bug influence reward t3 empire

### ISSUE THREAD

**Issue by lucryss** [WarEmu/WarBugs#4634]
hello, dya ago i completed all influence t3 empire(high pass), when i go give my reward, not give me nothyng in my bag, so i try relog, and when i was online, all my influence rest from 0.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
