### ISSUE TITLE
Ghrond's Hide appearance

### ISSUE THREAD

**Issue by Morohtar** [WarEmu/WarBugs#4635]
"Ghrond's Hide" (cloak, item level 27, violet) appearance cannot be changed anymore with others like the "Birtday Mantle" or "Pelt of the Dark Young". It was possible to do so until 29/02/2016 when I noticed it stopped to work. It still asks "if you are sure to change appearance to that item" when you try to do so, you click "ok" but nothing happens.

Thanks.

**Comment by Evildoor** [comment]
I presume it's the same problem as #4572, so will be fixed next patch.
