### ISSUE TITLE
Random Character Disappearance

### ISSUE THREAD

**Issue by ArielRoR** [WarEmu/WarBugs#4636]
I've had all of my Order characters disappear from the character selection screen. (Bar the one I created after to message a GM). I logged out after character hoping, swapping items around between my partners and my account to delete two of my Destruction characters. After doing so, I swapped over to the Order page to make myself two new characters to see that all of them were gone.

I relaunched to see if that might bring something back to life (later suggested by the GM as well). Relaunched again, just in case. Apparently they're all there on the account but for what ever reason, I am unable to see them. 

The GM (I believe) was Vistyn.

Thanks for any help possible, Ariel.

**Comment by rameden** [comment]
Is it possible that you have two pages of order characters?

http://imgur.com/bSFeZDx

If this is not the case I am sure someone will be in touch shortly to get this solved.

**Comment by ArielRoR** [comment]
That would indeed be the case. I'll admit it, I'm retarded :P Thanks for the response!

**Comment by rameden** [comment]
Not a problem at all. Glad it was an easy fix! I am an Altaholic as well.
