### ISSUE TITLE
[Public Quest] Empire Chapter 2 Stage II's not working

### ISSUE THREAD

**Issue by Ni7ek** [WarEmu/WarBugs#4637]
The windmill PQ doesn't let you kill the cultists in the bubbles, and the Ruins PQ doesn't let you interact with the banner. Both Stage II objectives.

Edit: tried the Longship quest too, another bug on Stage II, this time I noticed the mouseover flavor text doesn't match the displayed objective. It says to gather torches (which are nowhere to be found) and burn ships, but the objective says to kill 8 plunderers (who are also nowhere to be found)

**Comment by Ni7ek** [comment]
Also it's now eternally stuck on Resetting in 0:00.

**Comment by Evildoor** [comment]
1)#4401
2)#4637
3) One report per problem.
4) Exact names of PQs.

**Comment by Ni7ek** [comment]
I thought every stage 2 of every PQ in one chapter counted as one big problem. Exact names of PQs? Ruins of Schloss Von Rubendorff, The Burning Windmill, and The Norse Are Coming!

**Comment by Soulwhisper** [comment]
#4396
#4400
#4401

**Comment by Evildoor** [comment]
> I thought every stage 2 of every PQ in one chapter counted as one big problem.

If the problem was the same - yes. But cultists in bubbles and killing plunderers instead of gathering torches are not the same problem.
