### ISSUE TITLE
Inevitable power epic quest no longer soloable

### ISSUE THREAD

**Issue by kmelesh** [WarEmu/WarBugs#4639]
This is my thread 

http://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=11919

where i list the issue that a level 25 hero mob prevents the completion of this quest chain, when i first did this quest on another toon after epic quests were implemented i faced no complications as the stated mob was either passive or was a champion mob not a hero

i was advised by the community to post this on the tracker as epic quests are ment to be soloable and order epic quests require no group

**Comment by Torquemadra** [comment]
fixed next

**Comment by kmelesh** [comment]
hey torq i dont know if you worked on it or not but now the floor below the one that has bruenhilde has 3 or so Elizabeth kruger champ mobs

**Comment by Torquemadra** [comment]
Been through whole tower, unless the PQ is operational and going through its appropriate stages it should be much, much clearer.
