### ISSUE TITLE
[WL] Pounce through keep doors

### ISSUE THREAD

**Issue by Hixipixi** [WarEmu/WarBugs#4641]
Its possible to pounce through all doors in T3 elves keep
Skill is grey but it will be performed and you jump inside the door/wall and kann go through.

**Comment by genisaurus** [comment]
Reported months ago https://github.com/WarEmu/WarBugs/issues/1642

**Comment by Hixipixi** [comment]
sorry i didnt find with the serach option, only with other players involed passing the door.
