### ISSUE TITLE
[NPC] Level 39 manticore stuck in permadeath

### ISSUE THREAD

**Issue by Ryanfawkez** [WarEmu/WarBugs#4642]
![untitled](https://cloud.githubusercontent.com/assets/8767404/13403514/a4036814-df15-11e5-92e1-f2c8abcce727.png)

Right at Dark Elf chapter 1, there's a fantastically high leveled Manticore that's stuck in permadeath.

**Comment by Torquemadra** [comment]
had a null string, fixed next patch
