### ISSUE TITLE
Guard[skill] bugged in orvr/pve

### ISSUE THREAD

**Issue by sn3jk** [WarEmu/WarBugs#4646]
Save da runts is bugged for me in orvr/pve, it's not lighting up on my bar(it does so when it's working correctly in SCs).

The problem/bug is that it does not apply guard instant, say that I'm guarding player 1 and decide to swap to player 2, I cannot double tap my guard bind to swap guard instantly(this works flawlessly in SCs).

The addons im running that i can think of could interfere with the skill are:
Enemy(tried with both guard option on and off, no difference. Havn't tried disabling this addon)
Every Body Guard(no difference with it disabled or not)
Textured buttons(havn't tried disabling this)

Will test more tomorrow and get back with more info.

Update 1:
I have tried with a chosen tank and it's the same problem.
Tried with all addons disabled and still no luck. 
Seems like there is some hidden GCD on guard removal since the first apply(when i have none guarded) is instant.

**Comment by ozarmidrashim** [comment]
Cannot fix. Spent some time looking at group packets - they work correctly in warbands but not in groups for some infernal reason I'll never bloody understand.

**Comment by Evildoor** [comment]
#4044 will be used for this.
