### ISSUE TITLE
Scenario: Battle For Praag

### ISSUE THREAD

**Issue by Povel** [WarEmu/WarBugs#4647]
... Will not pop anymore.

Problem lies with other SC's getting favored before BFP because they're 12v12 and not 18v18 like Battle For Praag is.

Presumably this issue presented itself with the most recent patch where one attempted to fix the problem with scenarios not filling up quick enough (?)

**Comment by magter3001** [comment]
Have had the same issue. 

http://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=11826#p125246

Happened after this patch.

**Comment by Torquemadra** [comment]
Made changes in the DB should be fixed next patch
