### ISSUE TITLE
Char- empty, skills gone, items lost, .....

### ISSUE THREAD

**Issue by Spielteufel** [WarEmu/WarBugs#4650]
Sorry my English is not good and i make it with help from friends and google translater.

After logged in on my Char "Alator", my Charaktewr was Dead (in the Unit Window the Picture was the Skull and my Life empty. All my Items/Tokens are gone/lost, the skills was gone too, i wasn't able to chat with anybody, ...
After talking to  GM Verdammt (about a Friend in the Game and Teamspeak) he "brought me back to Life". My Skills was back but the Rest was still gone/lost/buggy .
After logging in/out, restarting PC two times,... i still have this problems and i'm "Dead" again. Also i'm not able to Log Out... 'cause i'm Dead 
My second Char is working fine.
Hope you can help me soon =)  Sincerly Alator 
Thanks for help

**Comment by Spielteufel** [comment]
Please Help

**Comment by Evildoor** [comment]
Closing per rules of the bugtracker.
