### ISSUE TITLE
Unable to do PQs if full influence

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#4651]
When I was doing the first PQ in chaos chapter 1, I noticed that when you have full influence, nothing you do counts towards the progress of the PQ. Killing the mobs does not count and you are unable to interact with the Perished Soul tomb stones.

**Comment by ElMosquito** [comment]
Update: It seems like the problem is not full influence. The PQ stops "responding" to your actions after some time and you need to leave the area of the PQ and enter it again to reset your progress in the PQ.

**Comment by wargrimnir** [comment]
Should be fixed.
