### ISSUE TITLE
[NPC]Bloody Sun Challenger

### ISSUE THREAD

**Issue by Vandorkholme** [WarEmu/WarBugs#4652]
In DE T1 WC http://i.imgur.com/r2XHWLH.jpg

**Comment by Evildoor** [comment]
Checked both live and dev, he looks like a normal gobbo.

**Comment by Torquemadra** [comment]
I wasnt sure what was being referenced but after evils comment I checked the database and that NPCs alternate model was an orc not a gobbo which caused the problems. Fixed next patch.
