### ISSUE TITLE
Fuergan Firebeard mob wrong loot table

### ISSUE THREAD

**Issue by foxbeep** [WarEmu/WarBugs#4653]
Mob Fuegan Firebeard in BV at shipwrecked slayer's camp is level 10 champ dropping 21 greens
![mugkrakka_001](https://cloud.githubusercontent.com/assets/15528466/13416212/92b72792-df26-11e5-955b-a858f9541412.jpg)

**Comment by genisaurus** [comment]
Fixed in next patch - wrong items in loot group
