### ISSUE TITLE
Plague on the Wind - PQ (Troll Country)

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4654]
It is messed up.Kill counter counts wrong the kills.Resets without any reason on Stage 1.
I killed 20/20 Farmer and 7/10 Harv and out of nowhere it reversed the kills on the counter back to 0.
Stage 2 doesnt work ofc.

**Comment by Soulwhisper** [comment]
Looks like it is fixed and working as it should

**Comment by wargrimnir** [comment]
Re-open this, no mobs are spawning here currently.

**Comment by StaH84** [comment]
Public Quest +/- works but in Blue bags there are no weapons/armor to choose from.

**Comment by Soulwhisper** [comment]
This is #5377 major issue.
Database team needs to add the items manually to each bag.

**Comment by Soulwhisper** [comment]
Closing this.It works fine.
