### ISSUE TITLE
Emperor's Ward Tactic

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4655]
![paterellas_002](https://cloud.githubusercontent.com/assets/16864486/13421449/122788a8-df97-11e5-9039-9a0a6ff93996.jpg)
Normally it should absorb 166 instead of 158.Dunno if its a visual bug only.

**Comment by Evildoor** [comment]
Combat log? Tactic tooltip (on the tactic panel)?

**Comment by Soulwhisper** [comment]
Absorb is correct at combat log.Just a visual bug.Which is hardcoded i suppose and cannot be fixed yet...right?
