### ISSUE TITLE
Endemius The Blister...

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4656]
This champion in Troll Country at 2k/31k never drops greens.Killed him over 20 times in a row.

**Comment by genisaurus** [comment]
Champions at the moment do not have a higher chance of dropping any loot than normal mobs. With only 20 repetitions, there is a ~65% chance of not getting a single green, so this cannot be proven to not just be bad luck. Moreover, there's nothing that would prevent this particular mob from rolling on a universal loot group that works for every other mob.

Champions and heroes will get a higher chance to drop certain classifications of items in the near future, but in the meantime, this cannot be proven to be a bug.

**Comment by Soulwhisper** [comment]
Sorry Geni.my bad
