### ISSUE TITLE
Beacon of Firengrom PQ (T3) 

### ISSUE THREAD

**Issue by Waaghaa** [WarEmu/WarBugs#4658]
See: http://warhammer.gamepressure.com/warhammer_public_quest.asp?ID=144

I have not done this PQ before, 

But I do feel that something is wrong with it anyhow as the last stage requires you to kill Fargus Headswallower not once, but twice ? (meaning you, have to wait for him to spawn again ) 

Also the white loot bag I recieved by post, cannot be opened.

**Comment by rameden** [comment]
PQ's are currently being worked on. While some may work on the live server most will not. These issues will be flushed in the coming patches.

**Comment by wargrimnir** [comment]
Only one kill required currently
