### ISSUE TITLE
Vengering resist values

### ISSUE THREAD

**Issue by laattori** [WarEmu/WarBugs#4659]
Seems like Vengering resists are too low considering their item levels.

![weird1](https://cloud.githubusercontent.com/assets/15817706/13427496/198d16e6-dfbd-11e5-8c71-47c8975953c4.png)
![weird2](https://cloud.githubusercontent.com/assets/15817706/13427501/1f02de80-dfbd-11e5-8583-efd726256c27.png)
![sanctuary1](https://cloud.githubusercontent.com/assets/15817706/13427503/246742da-dfbd-11e5-9d9a-e756dc85ea96.png)
![sanctuary2](https://cloud.githubusercontent.com/assets/15817706/13427506/2a86e8f0-dfbd-11e5-9d6c-c3823dd8c2eb.png)

**Comment by rameden** [comment]
Fixed in next patch.
