### ISSUE TITLE
Character appears naked to everyone but me

### ISSUE THREAD

**Issue by ConkerDaRed** [WarEmu/WarBugs#4661]
Hello, for the past couple of Weeks my Character "Conker" has appeared "Naked" to everyone else. This is not the Case on my Screen. I am in Full Gear, yet everyone else says I'm Naked.

I also have plenty of Appearance Items Active on my Character as well. Maybe this is the Source?

I had read on the Forums that.. "You most likely have an item in your backpack that is bugged, preventing the server from loading your character.

Raise this on the bug tracker with your character name and account name."

**My Character Name is: Conker
My Account Name is: C0NK3R**
-note- My account name has a (Zero), and a (Three) in it.

Any Help would be much Appreciated! Thanks!

**Comment by Ryanfawkez** [comment]
Take off your guild standard item.

**Comment by ConkerDaRed** [comment]
Thank you Sir!
