### ISSUE TITLE
White Lion pet bug when using skaventunnels in T2 dwarf.

### ISSUE THREAD

**Issue by AlistaireCrowley** [WarEmu/WarBugs#4665]
When you use skaven tunnel with pet up it gets lost. Pet have not died but its not with you. Ie you have to resummon pet on other side of tunnel. 

This is prolly an issue in T3 dwarf also.

Best regards

**Comment by Evildoor** [comment]
#2069?

**Comment by AlistaireCrowley** [comment]
Bott yes and no. It doesnt die and trigger respawn timer when you use the tunnel. Actionbar disapear but Pet is still Up and peticon in qbar is still highlighted. And you have to manually release pet  to be able to summon it again.

But yea, similar issues as you posted.

**Comment by Londo001** [comment]
This can be fixed once server side los is added. Server currently does not know tunnel geometry, so pet spawns  above ground over the tunnel.

**Comment by AlistaireCrowley** [comment]
Ok. Cheers for the quick answer. 

Best regards.
