### ISSUE TITLE
Grave Diggers PQ - Order

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4668]
- [X] ~~Stage 3 doesnt work (**Rhizha doesnt spawn**).~~

**Comment by rameden** [comment]
This is fixed in next patch.

**Comment by Soulwhisper** [comment]
Closing for now than.

**Comment by Soulwhisper** [comment]
Doesnt spawn the chest after finishing 3rd Stage.

**Comment by Soulwhisper** [comment]
Same here...Stage 1 zombies shouldnt spawn During Stage 2 and Stage 3.

**Comment by rameden** [comment]
I believe it was this way on live.

**Comment by Soulwhisper** [comment]
Alright then.Closing.Only problem is chest (which doesnt spawn in any of PQs in Troll Country)

**Comment by Soulwhisper** [comment]
Green bag does not have an Item and it has 1 slot to choose which is empty and says : No icon set

**Comment by Soulwhisper** [comment]
Blue bag too...looks like all bags are bugged.

**Comment by Soulwhisper** [comment]
Except bags now with the latest changelog : 
Nalgol:
- Changed the Way PQ Areas work now we have custom sizes for PQ areas
The area of this PQ is wrong.You have to go from the sides to trigger the UI.Entering straight to the PQ area doesnt show PQ UI and you cant make a progress in it.
