### ISSUE TITLE
The Blighted Farm PQ - Order

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4669]
- [X] ~~Stage 3 doesnt work (**Valgar the Leper doesnt spawn**)~~

**Comment by rameden** [comment]
This is fixed in next patch.

**Comment by Soulwhisper** [comment]
Closing for now then.

**Comment by Soulwhisper** [comment]
Here too...doesnt spawn chest.

**Comment by Soulwhisper** [comment]
+ If turret/pet kills Hero in the last Stage he doesnt respawn and cant complete the PQ so...you have to wait for a restart.

**Comment by rameden** [comment]
No fix for that as of now.

**Comment by Soulwhisper** [comment]
Purple bag does not have an Item and it has 1 slot to choose which is empty and says : No icon set

**Comment by Evildoor** [comment]
I suppose this was closed by mistake, since another problem was reported after "Fix Pending", which should have been removed.

**Comment by Soulwhisper** [comment]
![paterellas_034](https://cloud.githubusercontent.com/assets/16864486/14764245/aedbf02a-09b9-11e6-903e-9a0b26773655.jpg)
This specific Believer keeps spawning on stage 1 while he shouldnt.
