### ISSUE TITLE
Shield of Aqshy Defense bonus in stats window

### ISSUE THREAD

**Issue by nub5** [WarEmu/WarBugs#467]
When you the user cast "Shield of Aqshy" they do not see the armor increase in the character stat window.  Starting armor value of 9, cast spell and it is still 9.  Re-test with starting armor value of 0, cast, armor value still 0.  According to the spell description armor value should increase by 74 for duration of spell.

This could be a larger issue that the shield is not providing the stated armor bonus to the player.

**Comment by akanieski** [comment]
@ozarmidrashim: What handler is used to ability handler stat buffs?
