### ISSUE TITLE
Lashing Power, Marauder's M4 bug

### ISSUE THREAD

**Issue by Thaligon** [WarEmu/WarBugs#4670]
It is suppose to have chance to hit back and heal you, atm it hits back and hits you too..

Pic from my test run combat log

<a href="http://imgur.com/W8oFTdR"><img src="http://i.imgur.com/W8oFTdR.jpg" title="source: imgur.com" /></a>

**Comment by Evildoor** [comment]
It actually deals damage? Because on this pic i see minus before numbers, which hints that it's just a visual bug. (There was tiem when lifesteal and some other things, like Prayer Of Devotion, worked in the same manner)

**Comment by Thaligon** [comment]
Well i almost died on lvl 20 mobs from it

**Comment by ozarmidrashim** [comment]
Negative damage is a heal, so if you almost died, it wasn't a result of this, which is a display issue only :)
