### ISSUE TITLE
Inevitable Power quest in High Pass (blood tome - bug)

### ISSUE THREAD

**Issue by venohard333** [WarEmu/WarBugs#4672]
This quest requires to be found the Blood Tome in the Keep of Asavar Kul (coordinates - 36846, 22107) in High Pass. Also I think this is the 2nd quest in the chain, not 100% sure tho. I found the book, but when I try to interact with it nothing happens and therefore I cant complete the quest witch offers pretty neat rewards. This is a screenshot I made to show the book location. I hope this quest gets fixed. Thank you!

![blood tome](https://cloud.githubusercontent.com/assets/17593818/13462090/3a85169c-e08e-11e5-94cf-d32ef7120ba1.jpg)

**Comment by Torquemadra** [comment]
can you confirm this is still an issue after a server reset

**Comment by venohard333** [comment]
yes I can do that just let me know when - my ingame name is Furitus

**Comment by Torquemadra** [comment]
I amended the quest as wasnt happy with it ending with just picking up a book, now theres a librarian to defeat.

**Comment by venohard333** [comment]
Alright, thank you for your time I really appreciate it ! Keep up the good work.

**Comment by Waffulz3178** [comment]
I made a post regarding the turn in of this quest which now seems to be bugged. [https://github.com/WarEmu/WarBugs/issues/4680](url).
