### ISSUE TITLE
Bestial ToK Mob: Bloodscent 29 Champion

### ISSUE THREAD

**Issue by Povel** [WarEmu/WarBugs#4673]
Pretty sure this guy isn't supposed to have a doppler

http://i.imgur.com/ef8bB7K.png

**Comment by Povel** [comment]
Also Evildoor if you're reading this; Sorry about the Hugo Von Pritte double post.

My memory isn't the best sometimes :P

**Comment by Evildoor** [comment]
I suggest you to read the rules of the bugtracker - no offence here, just a friendly advice based on your actions.

Note to self - delete these two comments in a few days.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
