### ISSUE TITLE
Engineer Moral 4 Fling Explosives hitting more often than intended

### ISSUE THREAD

**Issue by aglarang** [WarEmu/WarBugs#4676]
Recently an engineer with the Morale 4 ability Flings explosives used it during a keep seige.  It seemed to hit for much longer (or hit for more tics per second) than the tool tip suggests.  The tool tip states it hits each enemy in a 30 feet radius for 400 damage once per second for 4 seconds.   The attached screen shot shows the ability hitting my character 10 times (for 560 damage each).  I died, so I do not know how many more times I would have been hit.  This ability did the same for all others in this particular defense.   This obviously killed the majority of defenders and allowed Order to take the keep. 
This is obviously game breaking, especially in keep seige situations.   See the attached screenshot.
![arnald_000](https://cloud.githubusercontent.com/assets/17597798/13467039/854b5354-e06a-11e5-97eb-ea350b28c632.jpg)

**Comment by Evildoor** [comment]
#4556
