### ISSUE TITLE
White lion moral ensnare need fix

### ISSUE THREAD

**Issue by Torete-war** [WarEmu/WarBugs#4678]
## The white lion moral 1 Ensare, it is a root ability with cast range 65 feets, which added to the pounce jump, it is just a death sentence to ranged clases in this server,no matter what they do.

In live server the moral roots had high chances to break when you were taking damage hits.
This was introdouced when KOTBS moral 2 area 10 sec non breakable root was changed to a breakable one, and they left the only non breakable moral roots into the tanks moral 1 one, which force both the target and the tank, to stay rooted in a place for all the time, even if the target dies

The white lions are already overpowered enough against range damage dealers, with spaming pounce ability.... giving them a non breakable root morale, when it was breakable one in live server, it is another backstab for the already overpowered developers realm.

**Comment by Evildoor** [comment]
This is a place for bugs, not for a balance discussions.

**Comment by Torete-war** [comment]
dude read the fucking mensage, it is a bug.... it should be a BREAKABLE ROOT, which it is not right now!!!

**Comment by Evildoor** [comment]
It was breakable? Proof then.

**Comment by Torete-war** [comment]
Open the request another time, and you maybe learn something about game.... instead of beign a nazi accusing people about game balance request, when it is obiusly a game bug....

**Comment by Torete-war** [comment]
The moral roots were changed, when kotbs one found too overpowered.... the 10 seconds moral 2 one, i know right, was the higher renow lvl kotbs in europe in first 3 moths after the kotbs class release.


The only none breakable one, it is the tanks moral 1, and it is because leave you stuck at the place, even if the target dies.

**Comment by Evildoor** [comment]
Read my comment. You say it was breakable on live. Bring me proof. And i mean solid proof like videos from live.

**Comment by Torete-war** [comment]
Can you give me your real name in warhammer return of reckoning server? so i can link you to white lions players from live?

**Comment by Evildoor** [comment]
Read the rules of the bugtracker - proof must be solid, video from live where it can be clearly seen that Ensnare gets broken by damage. Not words from players about their memories. Even honest and competent players who played WL for 5 years.

**Comment by Torete-war** [comment]
If you want fix something, maybe you may leave it open, instead of close it 1 min after post it, triying to erase evidence, your main it is a white lion, isn't it?

**Comment by Torete-war** [comment]
Dont worry, will search for the evidence, see you

**Comment by Thorgatin** [comment]
This never worked like stated by the OP. The root could be broken by abilities which remove roots, not by damage. 
Roots that could be broken had it stated in their tooltip.

I would be careful with abusing the bugtracker.

**Comment by Torete-war** [comment]
Minute 3:09, black orc rooted, and broken by damage....

[https://www.youtube.com/watch?v=ooM9gSl-mXY](url)

**Comment by Torete-war** [comment]
The root was broken by damage, after kotbs moral 2 one was nerfed...

**Comment by Evildoor** [comment]
Right, rooted and broken by damage. But it's SM root, not WL root.

Erasing the evidence? Read the rules - closed issues get checked as well as open ones.

**Comment by Torete-war** [comment]
Are you serious? the root was not swordmaster one....read coment in youtube video, says the ability used by white lion, and it was a ensnare one!!

**Comment by Evildoor** [comment]
![root](https://cloud.githubusercontent.com/assets/11015074/13474244/2b2ac76a-e0ce-11e5-85d0-4c352c6e93bd.png)

That's Aethyric Grasp icon in his effects. But no Ensnare one.

**Comment by Torete-war** [comment]
Sigh...i will keep searching, but even if you wanna deny it, it was like that.

**Comment by Torete-war** [comment]
Cool, and now i am banned? Seriusly guys, would be funnier for everyone if developers help both sides equally, and not only order one...
The server idea was great, but order developers fanatism...is quite dangerous, people will end playing everyone in order against npc in pve fest, if not balance slayer áreas, archimage dps, godly WP, and zero change in range dps supervivance because white lions pounce spam and tricks like this one.

**Comment by ozarmidrashim** [comment]
Hello there. This is Azarael.

You've been abusive on the tracker, even descending to compare one of our staff to Nazis (which we consider a grave issue) and have splurged your Destruction partisanship all over multiple topics by failing to bring up that FLAMES OF FATE (the Marauder skill) is a DIRECT COPY of Ensnare and works in exactly the same way.

I've checked the patch notes and there is absolutely nothing logged regarding this effect.

Additionally, you are no longer welcome here.

**Comment by Torete-war** [comment]
Even if marauder has a clone moral, you know perfectly marauder don't have
pounce for instant travel to the rooted spot...
Guys, do whatever you want, but you may check all scenarios ending 500 -
0.... Sometimes 4 or 5 times straight, if you want a healthy game, even if
i am not wellcome, make it funny for both parts, or you will end facing a
PVE boring shit, with all playera using theyr order overpowered toon.

**Comment by Torete-war** [comment]
Even if marauder has a clone moral, you know perfectly marauder don't have pounce for instant travel to the rooted spot...
Guys, do whatever you want, but you may check all scenarios ending 500 - 0.... Sometimes 4 or 5 times straight, if you want a healthy game, even if i am not wellcome, make it funny for both parts, or you will end facing a PVE boring shit, with all players sing theyr order overpowered toon.

Oh, and i call him Nazi, when he said the bug track was a balance discusión, when it was a legit bug report.
He accused me first

**Comment by taccr** [comment]
For further visual verification (aka retard check):

![Root](http://img2.uploadhouse.com/fileuploads/22177/221773325fc372a12f1a7d5b20995327e611c4df.png)

**Comment by Torete-war** [comment]
Whatever, the game is balanced and 5 scenarios straight 500 - 0, will always build a strong a players database.
With balanced numbers of class played equally, withouth only kotbs,slayers,wp and 1 or 2 archimage killing people in just 2 dots.

**Comment by Torete-war** [comment]
And dont forget the white lion, killing range clases withouth kite posibilty and destruction not saving any counter mirror pounce spamer ability for theyr range dps clases
