### ISSUE TITLE
White lion ensnare moral root, not working as intended... in live the root was breaking with damage hits, which it is doing it here

### ISSUE THREAD

**Issue by Torete-war** [WarEmu/WarBugs#4679]
The white lion moral 1 Ensare, it is a root ability with cast range 65 feets, which added to the pounce jump, it is just a death sentence to ranged clases in this server,no matter what they do.

In live server the moral roots had high chances to break when you were taking damage hits.
This was introdouced when KOTBS moral 2 area 10 sec non breakable root was changed to a breakable one, and they left the only non breakable moral roots into the tanks moral 1 one, which force both the target and the tank, to stay rooted in a place for all the time, even if the target dies

The white lions are already overpowered enough against range damage dealers, with spaming pounce ability.... giving them a non breakable root morale, when it was breakable one in live server, it is another backstab for the already overpowered developers realm.

**Comment by Evildoor** [comment]
Read the rules of the bugtracker. Duplicate issues will be closed on sight.
