### ISSUE TITLE
Shadow Grey Dye - shows tool tip of "dye remover"

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#468]
Shadow Grey Dye I have the wrong tooltip and behavior for this item.

description says "This item will remove dye from a piece of armor.  To bleach this item..."

Also - No sell price.  Afaik this should be able to be sold.

Can't use it to dye.

**Comment by milosxe** [comment]
Dyes are fixed. They are properly dyeing armor and not bleaching as they used to. Closing.
