### ISSUE TITLE
Inevitable Power quest in High Pass reward selection bugged

### ISSUE THREAD

**Issue by Waffulz3178** [WarEmu/WarBugs#4680]
-This could just be for Chosen I am not sure-

After clicking on the blood tome and then returning to the Whispering Voice to turn in the quest, it will not allow you properly complete the quest. Upon selecting your reward, I selected the shield, and clicking the complete the quest dialog between the character and the Whispering Voice will disappear but will not register as completed and will not give you your reward. <blockquote class="imgur-embed-pub" lang="en" data-id="0AuQhnw"><a href="//imgur.com/0AuQhnw">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by Torquemadra** [comment]
can you hover over every empty square in your backpack and tell me if one shows up with information on an invisible item?

**Comment by Waffulz3178** [comment]
nothing showed up

**Comment by Torquemadra** [comment]
fixed next patch
