### ISSUE TITLE
Bestial ToK Mob Reward: Sheen Gloomleaf

### ISSUE THREAD

**Issue by NoiDAx** [WarEmu/WarBugs#4681]
Hello!

I Killed the Sheen Gloom Leaf in Ostland to get the item Shawl of Spring (Cape) as reward, and I came to get the cape in Altdorf with Mandred Vogt but cant "buy"

Sorry about my english.

A Video from past doing this unlock.
https://www.youtube.com/watch?v=EfdOqZwbpIw

**Comment by Torquemadra** [comment]
mob was missing ToK, fixed next patch, will require killing again
