### ISSUE TITLE
Inevitable Power: Crypt Entrance

### ISSUE THREAD

**Issue by Shadowgurke** [WarEmu/WarBugs#4682]
The first step of this quest requires you to Kill some stuff and find the Crypt Entrance. Clicking the Crypt entrance however does not grant credit.

Note: I was able to complete the quest before but it seems bugged now. Other people confirmed that they are also stuck there

**Comment by Torquemadra** [comment]
Working on dev server, please try on server restart

**Comment by Shadowgurke** [comment]
working now
