### ISSUE TITLE
[Crafting] Cultivation issue - Ballistic Skill Seeds

### ISSUE THREAD

**Issue by Zorbibroz** [WarEmu/WarBugs#4685]
Hi, 

I make a lot of Ruffled Thief's Nettle Seed (Ballistic Skill Seed cultivating level 150) and sometimes i make some critical but that don't up the level of my current seed, i can't up this one to make a better cultivating level seed. I'm blocked only on this seed to lvl 150.
I hope that you can fix this soon, because we're lvl 35 now, and i can only make pot lvl 32 :/.

**Comment by magicthighs** [comment]
You don't level up with a crit, crits give you extra plants. To level up you need a "special moment".

**Comment by genisaurus** [comment]
Closed, since this does not appear to be a bug. I was able to get Thief Nettle seeds up to 200 through special moments on live.
