### ISSUE TITLE
[Chosen] Dire Shielding tactic not working properly

### ISSUE THREAD

**Issue by Waffulz3178** [WarEmu/WarBugs#4686]
The Chosen Dire Shielding is described as making the ability Bane Shield affecting allies within 30 feet of covered in a Bane Shield as well and last an additional 7 seconds.

Bane Shield lasts, initially, for 10 seconds; with Dire Shielding the ability and its effects on myself and allies should last for 17 seconds. However, it does not nor did it appear to affect my allies.

**Comment by Evildoor** [comment]
#4532
