### ISSUE TITLE
war-torn helmet deciple og khaine

### ISSUE THREAD

**Issue by vithoria** [WarEmu/WarBugs#4689]
war-torn helmet medium armour deciple of khain have no apperence anymore

**Comment by Ryanfawkez** [comment]
Seems fine to me in the wartool, you sure you simply didn't hide your helmet by accident?

**Comment by Evildoor** [comment]
I tested on dev, it's really invisible, with or without hiding.

**Comment by Ryanfawkez** [comment]
Yeah, DE_Helm_DK_01 has no appearance for some reason, changed it to DE_Helm_DK_02. Fixed in next patch.
