### ISSUE TITLE
[Quest] Order - Sieze Lost Lagoon, Nordland - Error in Description

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#469]
Seize Lost Lagoon quest, the dialog to accept the quest shows a error in the required task.

http://postimg.org/image/klqibygc3/

Says "Invalid Go,plz report to GM.  QuestID 33007,Objld=9293 0 of 1"

**Comment by Evildoor** [comment]
https://github.com/WarEmu/WarBugs/issues/298
Yeah, i know that linked issue has a rather interesting name, but this one is misspelled too, so i'm closing this one as newest.
