### ISSUE TITLE
Tactical Divination Reward

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4693]
Reward for this quest for WP should have the same value of stats.
One glove has +16 tough the other has +6 willpower(**it should have +16Willpower**).

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by wargrimnir** [comment]
White Lion rewards are wrong too, both missing the +6 stats. Probably other classes.

http://war.mmodb.com/items/bohsenfels-wristguards-96815.php
http://war.mmodb.com/items/criers-wristguards-101137.php
