### ISSUE TITLE
Character Cloak Appearance

### ISSUE THREAD

**Issue by akkzilla** [WarEmu/WarBugs#4694]
Have always used the Back Accessory alternate appearance, yet today tried changing it to something else and the game gives the prompt "Are you sure you want to apply this item's appearance? The current appearance will be lost." but once accepting 'Yes' nothing happens. Not sure if this is a recent bug or not but thought it was really weird. All other item slots in the alternate appearance still work however.

**Comment by Ryanfawkez** [comment]
Can you tell me if the cloaks you're using are both flagged as "cape" and "accessory"? There's a few bugged cloaks which are wrongly tagged as two handers, by which they become a "great accessory" in the "both hands" slot.

**Comment by Torquemadra** [comment]
and precise names of cloaks please

**Comment by akkzilla** [comment]
That's gotta be it! Ghrond's Cuvva is titled 'Both Hands' as a great accessory. The three cloaks which I tried alting its appearance are Skaven Cloak, Hide of Killing Frost, and Pelt of the Dark Young which are all tagged correctly as Back Accessory.

**Comment by Torquemadra** [comment]
removed 2 hander tag, fixed next patch
