### ISSUE TITLE
Death in Green and Brown, Ostland

### ISSUE THREAD

**Issue by QuinnHarlech** [WarEmu/WarBugs#4695]
Couldn't achieve the Cloak Shawl of Spring. The Mob Sheen Gloomleaf (Ferlangen Forest) stands ther two times, but non of them is a champ. The achievement is not granted by killing both of them.
![thronrik_009](https://cloud.githubusercontent.com/assets/17616529/13495292/22ce9bce-e14a-11e5-8f18-cf7f351399cf.jpg)

**Comment by Evildoor** [comment]
#4681
