### ISSUE TITLE
[Squig Herder] Pets cooldown.

### ISSUE THREAD

**Issue by roadkillrobin** [WarEmu/WarBugs#4698]
If you zone your pet dies but sometimes the CD gets increased aswell. Everytime i pop into a scenario or out of one there's about 15sec left on the pet CD; However, after those 15 seconds the "pet button" looks normal and you try to click it but nothing happens for about another 15 sec. If i pop into a scenrio thats allready started I have to wait another 30 seconds just to get the pet up.

**Comment by Evildoor** [comment]
#2069

**Comment by roadkillrobin** [comment]
It's not the same problem tho.

**Comment by Evildoor** [comment]
How a situation described in #2069 is different from your one?
