### ISSUE TITLE
[Engineer] Landmine stagger bypasses defenses.

### ISSUE THREAD

**Issue by Gobtar** [WarEmu/WarBugs#4699]
I am not 100% sure if this is a bug or working as designed, but the land mine causes a target to be staggered even if said target defended against the attack, i.e Block.

**Comment by Evildoor** [comment]
#1661 is supposed to be fixed.

**Comment by ozarmidrashim** [comment]
It was. This is unrelated (recent change to command execution for AoE handlers that trigger on damage)
