### ISSUE TITLE
"The end is nigh" - can't interact with quest object

### ISSUE THREAD

**Issue by Fikatind** [WarEmu/WarBugs#47]
you need to find Sergeant Arnoldt but its only his corpse so you cant interact with, and you cant complite the quest.

![fikatind_019](https://cloud.githubusercontent.com/assets/7502763/2908223/4a24f088-d625-11e3-98a9-9d7732085f8d.jpg)

**Comment by Reggaewaldo** [comment]
Tested OK.

Closing.
