### ISSUE TITLE
[Witch Hunter] Incognito issue

### ISSUE THREAD

**Issue by shamallow** [WarEmu/WarBugs#4700]
When i cast successfully this ability, I lose the buff after 1 or 2 seconds if an enemy launched me dots.
(and my AP is fine atm)

so so annoying...

**Comment by ozarmidrashim** [comment]
As no evidence has been supplied for this bug, I have added a check to the next patch which will fire when Incognito or Shadow Prowler is broken through a damage handler, informing you of who broke your stealth and with which ability it was. I will be marking this report as Fix Pending and closing it when I patch. If you spot an ability that is not a direct damage ST ability breaking Incognito, create another report then with the name of the ability which broke the stealth.

**Comment by Silentguard** [comment]
It's ok that this ability can be used under damage with no setback effect? Because WHs now going stealth right in melee combat whenever they want.

**Comment by Renork** [comment]
^ this happens frequently where a wh will just stealth in combat. I don't remember seeing much of this on live.

**Comment by Evildoor** [comment]
Stealthing under focus is a different issue: #4413
