### ISSUE TITLE
Missing tactic Zealot

### ISSUE THREAD

**Issue by heyheybugs** [WarEmu/WarBugs#4701]
There is a tactic called Drink Deeply a level 32 core tactic, its missing :)

![zealotmissingtactic](https://cloud.githubusercontent.com/assets/17622568/13505606/bdaafa08-e171-11e5-8fa8-70888965d377.jpg)

**Comment by Evildoor** [comment]
32?
http://waronlinebuilder.org/#career=zea;
Maybe 37?

**Comment by genisaurus** [comment]
This is not the place to report bugs with AddOns.

**Comment by heyheybugs** [comment]
Ok good to know, I didn't actually think to check the warbuilder just saw the level within the addon and thought wtf, so sorry for the mistake.
