### ISSUE TITLE
Event quest Abandon

### ISSUE THREAD

**Issue by NoiDAx** [WarEmu/WarBugs#4702]
Hello!

I droped the the quest **_Main Event: Eternal Bond - The Missing Maiden_** and I tryed to accept her again talking with NPC **Boris Saewert** in Altdorf near Flight Master, but they dont give me the quest, I Dont know if is a bug, or suppose to work this way when you drop a quest.

Thx!

Sorry About my bad english!

Event Quest link
http://www.returnofreckoning.com/forum/viewtopic.php?f=19&t=3945

**Comment by Ryanfawkez** [comment]
It should be given by the quest giver that gave you the part of the quest you abandoned. It does not reset the entire chain back to the first quest giver.

**Comment by NoiDAx** [comment]
U alright!

Thx for help!
