### ISSUE TITLE
In-fight status

### ISSUE THREAD

**Issue by Luth-RoR** [WarEmu/WarBugs#4703]
-deleted former post, cause crap-

1. I think on the original server it worked like this:
If a player died, the infight status persisted through his death (i remember getting instantly rage again after being ressed, out of enemy range and without being hit).

2. It took often a very long time for group members to get out of fight; i guess because every single member had to get out of fight for loosing the in-fight status.

Hard to get find any video though, maybe someone can confirm/deny.

**Comment by Thorgatin** [comment]
Actually not true; videos show group members in fight but without the recording player getting infight.

**Comment by Thorgatin** [comment]
https://www.youtube.com/watch?v=R6MpQsqUQds&feature=player_detailpage#t=37

**Comment by ozarmidrashim** [comment]
Dying will no longer cause leaving of combat in next build.

**Comment by Luth-RoR** [comment]
Report is wrong, sorry for the inconvenience. :flushed: Base morale gain seems to be too low though. https://github.com/WarEmu/WarBugs/issues/7084
