### ISSUE TITLE
Sentry - IC

### ISSUE THREAD

**Issue by benitoben20** [WarEmu/WarBugs#4706]
Hello,

There is 2 sentries that are one on another.
As we say, pictures tell more than words.

Thanks,
![isas_021](https://cloud.githubusercontent.com/assets/16641170/13516235/4def86b0-e186-11e5-9b7c-8c00e7aedbcf.jpg)
![isas_022](https://cloud.githubusercontent.com/assets/16641170/13516234/4dedb8f8-e186-11e5-8628-8aac084420e6.jpg)

**Comment by Torquemadra** [comment]
Fixed next patch
