### ISSUE TITLE
[Magus] Resummon & Horrors

### ISSUE THREAD

**Issue by Zegreiart** [WarEmu/WarBugs#4707]
When using Resummon to move the Pink and Blue Horror (the only two horrors I got so far) they disappear and do not reappear to the supposed relocation while out of combat.

While in RvR and in combat I could relocate the Pink Horror, didn't try to move the Blue Horror.

I can replicate the failure to move both of them while out of combat. While moving them, they disappear and the buff that builds up begins to deplete.

**Comment by Evildoor** [comment]
Please, post this as a comment in #2589
