### ISSUE TITLE
backpack talisman crafting (all times in the first slot of the crafting bag)

### ISSUE THREAD

**Issue by ultimatetitane** [WarEmu/WarBugs#4708]
All the item in the first 2 crafting bags are set in the first slot of the first bag. Its flickering all the icons items add random in the first slot. i need to click and drag to find (almost) all my items here.

**Comment by Evildoor** [comment]
#1548?

**Comment by ultimatetitane** [comment]
i i've seen that one. the flickering is simular. but my items are all in the first slot.

**Comment by Evildoor** [comment]
I'm pretty sure it's the same problem, which is covered by #1548. Closing until someone proves otherwise.
