### ISSUE TITLE
(ITEM) Boars not dropping extenders (Droplist)

### ISSUE THREAD

**Issue by Pamz123** [WarEmu/WarBugs#4709]
Boars are not giving out their respective levels of Extenders (Apothecary), upon butchering. 

Namely the item **Boar Blood**.

Theres also a wrong willpower placed ingredient dropping.

Heres the reference (at the bottom of the page):
http://warhammeronline.wikia.com/wiki/Boar

**Comment by Torquemadra** [comment]
we need a specific mob name to start, if we just pick a random board to start and that one actually works where do we go from there?

**Comment by Evildoor** [comment]
#4340 and some others may be related.

**Comment by Pamz123** [comment]
@Torquemadra 
None of the "Boar", which is animal type, Sub-Type-Beast drop the item mentioned above.
So names of monsters are _Boars or Tuskgor_
 For named boars, heres the full list:
   `
  Ebertusk R3 (Normal) - Nordland
    Slaytusk the Ravager R8 (Normal) - Nordland
    Bonesnapper R9 (Champion) - Nordland
    Gorger R9 (Champion) - Chrace
    Thornmaw R9 (Hero) - Chrace
    Brokentusk R17 (Champion) - Ellyrion
    Bloodgore R18 (Champion) - Shining Meadow Ellyrion
    Rumblehoof R19 (Champion) - Ellyrion
    Clotsnout R23 (Champion) - Army of Faith Talabecland
    Oaktusk R23 (Champion) - Avelorn
    Dirtfur R29 (Champion) - The Badlands
    Bladetusk R31 (Champion) - Black Crag
    Tyrangor R36 (Champion) - Dragonwake
    Cragtusk R38 (Champion) - Black Crag
    Kraggorn R40 (Champion) - Black Crag 
`

**Comment by Torquemadra** [comment]
While I appreciate the effort I really need just ONE name of a mob that is confirmed not functioning properly so I can see what is actually the issue given that some in the DB are missing types and sub types but some are not.
