### ISSUE TITLE
The Boundless Boyz' Ring stats

### ISSUE THREAD

**Issue by laattori** [WarEmu/WarBugs#4710]
Seems like The Boundless Boyz' Ring resists are too low compared with the other variants of similar item levels.

![boundless3](https://cloud.githubusercontent.com/assets/15817706/13527960/ad905082-e21b-11e5-8c60-717eebb113e9.png)
![boundless2](https://cloud.githubusercontent.com/assets/15817706/13527964/b2fa30f6-e21b-11e5-8586-a68a877d7d5e.png)
![boundless1](https://cloud.githubusercontent.com/assets/15817706/13527966/b8dfdb42-e21b-11e5-89cd-7d2b876334d3.png)

**Comment by Torquemadra** [comment]
made uniform next patch
