### ISSUE TITLE
Different stats on same Boundless wearpons order/destro

### ISSUE THREAD

**Issue by Doomsday82** [WarEmu/WarBugs#4711]
![fardigun_003](https://cloud.githubusercontent.com/assets/13207459/13528175/60666b48-e225-11e5-8ccf-63f6d66403db.jpg)
![krohus_032](https://cloud.githubusercontent.com/assets/13207459/13528181/6e99248a-e225-11e5-979c-8198318af8cb.jpg)
Most of 1h with 3% disrupt have 16+16 stats, but what engi rifle have it too much. 
Also i never seen on destro 2h with 80str+64ws+2AP, like WL and slayers have. At least it must be for choppa.

**Comment by heyheybugs** [comment]
Lol, funny that order got the higher stats by 'accident'; really ;D

**Comment by Doomsday82** [comment]
btw, then ill bye that rifle 2-3weeks ago it was 16+16+3disrupt) But when i log on engi today i was really surprised. Must be some "fix"

**Comment by Torquemadra** [comment]
rifle made uniform next patch
