### ISSUE TITLE
Marauder Healdebufftactic works not corectly

### ISSUE THREAD

**Issue by Janollas** [WarEmu/WarBugs#4712]
Hi, i think it give a problem with the tactic "deadly clutch". It works mostly without a problem but i know from the live server the Dmg Sigmarpriestskill "devine assault" will give my Marauder 25% from the Heal. Today i have a fight with an Dmg Siggi and it doesnt work. So i tested with an Guildmembers SP and it shows me normal Heal skills give me 25% Heal on my Marauder. But "devine assault" heals the SP and nothing Heal cames to me. I have make 2 screenshots to show you what i mean.
![janollas_000](https://cloud.githubusercontent.com/assets/16622909/13530823/9a341386-e223-11e5-9413-4a9507b5b834.jpg)
![janollas_001](https://cloud.githubusercontent.com/assets/16622909/13530833/a3d27126-e223-11e5-9162-175f570a3c39.jpg)

Ps. please forgive me for my bad english :]

**Comment by Evildoor** [comment]
Intentional change from live. See #4174
