### ISSUE TITLE
Lizards in south Ostland

### ISSUE THREAD

**Issue by Dirkdaring** [WarEmu/WarBugs#4715]
Was killing the lvl 14-16 Slimetongue  Lizards in South Ostland , today, and whenever one would get to zero HP, it was say  FormatException was thrown,  or  can`t parseunit32  and either destroy the mob
, or  make it unattackable 

![hanoveer_002](https://cloud.githubusercontent.com/assets/17651165/13535460/f25a66b0-e1ff-11e5-8b28-6df34afec069.jpg)
![hanoveer_003](https://cloud.githubusercontent.com/assets/17651165/13535463/f4e80518-e1ff-11e5-9c48-47de113f432e.jpg)

**Comment by Torquemadra** [comment]
#4632
