### ISSUE TITLE
Lesser Daemon of Tzeentch

### ISSUE THREAD

**Issue by benitoben20** [WarEmu/WarBugs#4716]
Hello,

While you do the Maiden's quest, you stumble upon Lesser Daemon of Tzeentch. I killed one and the ToK counted him as a snotling. 

Thanks,

![rasila_001](https://cloud.githubusercontent.com/assets/16641170/13541591/3a5a8a0a-e22b-11e5-8f62-2b75ae0ab3c2.jpg)
![rasila_000](https://cloud.githubusercontent.com/assets/16641170/13541592/3a5bf4e4-e22b-11e5-84f1-8d5e0e38ec04.jpg)

**Comment by Styrkarr** [comment]
Fixed in next patch.
