### ISSUE TITLE
Temple of Sigmar - Altdorf

### ISSUE THREAD

**Issue by benitoben20** [WarEmu/WarBugs#4717]
Hello,

There is a table floating in the Temple of Sigmar. Never knew Warpriest of Sigmar could do that :)

Thank you,
![rasila_003](https://cloud.githubusercontent.com/assets/16641170/13541688/cedc5b54-e22b-11e5-972d-8dda6aac557b.jpg)

![rasila_002](https://cloud.githubusercontent.com/assets/16641170/13541670/b9c6585a-e22b-11e5-9558-a08020734bb4.jpg)

**Comment by Ryanfawkez** [comment]
Gameobjects 'float' in general due to a client-sided issue. It tends to happen upon completing/picking up quests.
