### ISSUE TITLE
Reaper bolt throwers broken

### ISSUE THREAD

**Issue by Damiel126** [WarEmu/WarBugs#4720]
In House Arkaneth PQ in Elf chapter 1 the bolt throwers don't behave properly.

1. They follow you and attack like a mob. They should be static and not attack.
2. When they die, they appear to be alive and aggro'ed, but when you click on them they are dead.
3. When they die, they don't switch to the destroyed animation
4. They don't disappear, and they don't respawn

There used to be a quest where you have to destroy 3 reaper bolt throwers, but haven't checked lately to see if it's still offered. If so, it's not currently able to be completed once each of the bolt throwers has been destroyed after a server reset.
![abigaele_001](https://cloud.githubusercontent.com/assets/10399547/13547005/ccdcadca-e313-11e5-86c1-f80510ca44b5.jpg)

**Comment by Damiel126** [comment]
Found similar behaviour with an order toon in the destro zone. These shades are just decoration, spying on the high elves, and as a destro player you can only talk to them. Attacking with an order toon however kills them in the same way as the bolt throwers above, so maybe something to investigate settings wise in the database.
![abigaele_021](https://cloud.githubusercontent.com/assets/10399547/13547374/5eb3368c-e324-11e5-842c-28503526b667.jpg)
![abigaele_022](https://cloud.githubusercontent.com/assets/10399547/13547375/5eb65d1c-e324-11e5-9dd6-c3af504c4377.jpg)

**Comment by Damiel126** [comment]
More investigation. The ones in Chrace behave the same way. When the NPCs attack them though they seem to die normally instead. The one on the left is one I killed. The one on the right was killed by the nearest white lion.
![abigaele_030](https://cloud.githubusercontent.com/assets/10399547/13547449/b7285eca-e327-11e5-807a-52d90bd645ea.jpg)

**Comment by Damiel126** [comment]
This is mostly resolved. There's only one minor bug remaining.

Now when you kill a bolt thrower, it has the sparkling effect indicating loot but it's not lootable.

**Comment by Luth-RoR** [comment]
They have a wrong flag in the DB. Could be easily fixed with the wartool.

**Comment by Ryanfawkez** [comment]
Removed loottables. Bolt Throwers should act like all other siege now.
