### ISSUE TITLE
Elf Chapter 1 PQ not working

### ISSUE THREAD

**Issue by Damiel126** [WarEmu/WarBugs#4721]
After killing the shades in stage 1 of the House Arkaneth PQ in Elf chapter 1, nothing happens. There should be a spawn of witch elves, sorcerors and black guard, each with a leader for stage 2, and a hydra champion with beastmaster for stage 3.

The active zone for the PQ is also smaller than it is supposed to be, as it should extend around to the right where the reaper battery is.

The PQ information and influence also don't show in the interface.

**Comment by ellionkeman** [comment]
House Arkaneth is not working at all. Area message appears when you enter PQ zone but no PQ influence panel appears and no kill count there.

**Comment by Damiel126** [comment]
Influence panel now appears with the fixed zones, but no influence is being awarded to any of the chapter 1 or 2 elf PQs I've tested.

**Comment by wargrimnir** [comment]
PQ is now active, although all the scripting for multiple waves is not.

**Comment by ErikWPotter** [comment]
The NPCs for phase 1 don't exist. I fought them on another character maybe 5 days ago (Jan-21-2018). One or two days ago I was back with a different character and now the PQ is stuck in phase 1 and there are no spawned NPC that you must kill to progress the quest.
