### ISSUE TITLE
Quest Destro: Honorable Deciet

### ISSUE THREAD

**Issue by Nekkma** [WarEmu/WarBugs#4722]
The quest mob "Mirithas Iirenor" spawns on top of hostile mobs and get killed in a few seconds after spawn.
![zatakk_002](https://cloud.githubusercontent.com/assets/17377105/13547019/88249038-e2c0-11e5-8829-dd000f08402b.jpg)

**Comment by Nekkma** [comment]
Not sure if this is a bug or not as there are duplicates of two of the mobs (in a tent next to the final mob). The one above, however, matches the location in the quest description.

**Comment by Torquemadra** [comment]
removing duplicates, fixed next patch
