### ISSUE TITLE
Incorrect influence reward Order Empire Chapter 2 BW

### ISSUE THREAD

**Issue by Damiel126** [WarEmu/WarBugs#4723]
There's a warrior priest charm in the influence rewards options for bright wizards in Empire. Should be an alternate spec staff.
![abigaele_010](https://cloud.githubusercontent.com/assets/10399547/13547058/ea7ac680-e315-11e5-8f69-b81fc72ed7cc.jpg)

**Comment by Torquemadra** [comment]
fixed next patch
