### ISSUE TITLE
Beastmaster mob wrong animation

### ISSUE THREAD

**Issue by Damiel126** [WarEmu/WarBugs#4724]
The beastmasters in the Swale or Miralei (Elf chapter 2 PQ) are spawning as chaos marauders instead of dark elves.
![abigaele_012](https://cloud.githubusercontent.com/assets/10399547/13547096/d439fd94-e317-11e5-8fad-160e90f5e01e.jpg)

**Comment by Torquemadra** [comment]
fixed next patch
