### ISSUE TITLE
Elf Chapter 2 PQ Swale of Miralei not working

### ISSUE THREAD

**Issue by Damiel126** [WarEmu/WarBugs#4725]
No influence bar. No PQ notification. No influence from mob kills.
![abigaele_013](https://cloud.githubusercontent.com/assets/10399547/13547110/3535c286-e318-11e5-86fa-afd3a19a62e2.jpg)

**Comment by Soulwhisper** [comment]
Yes this is related to this one #4557 
You have to run around the map to trigger the bar somehow...looks like Influence bar UI is acting weird atm.

**Comment by Damiel126** [comment]
Update :( Its worse. If you go up to the land bridge to the left, you get the PQ notice, but it says destruction. I'll grab a screenshot in a sec.

**Comment by Damiel126** [comment]
![abigaele_016](https://cloud.githubusercontent.com/assets/10399547/13547143/d82525d0-e319-11e5-9107-be3787f6c514.jpg)

**Comment by Soulwhisper** [comment]
Destruction means you have to kill.All PQs refer Destruction at stages.

**Comment by Damiel126** [comment]
Influence panel now appears with the fixed zones, but no influence is being awarded to any of the chapter 1 or 2 elf PQs I've tested.

**Comment by wargrimnir** [comment]
Fixed in next patch.
