### ISSUE TITLE
Cliffrender Hunter Mob spawning in wrong zone

### ISSUE THREAD

**Issue by Damiel126** [WarEmu/WarBugs#4726]
It's spawning in the Swale of Miralei PQ area and is untargetable.

It would normally be flying above the cliff in the foreground, on the land bridge between 
![abigaele_014](https://cloud.githubusercontent.com/assets/10399547/13547152/f88b97be-e319-11e5-95e8-1b5ccad59666.jpg)

**Comment by Damiel126** [comment]
* on the land bridge above it, here.
![abigaele_016](https://cloud.githubusercontent.com/assets/10399547/13547156/1214a536-e31a-11e5-95f0-ab356cd659a2.jpg)

**Comment by Lheana** [comment]
Has been fixed several patches ago.
