### ISSUE TITLE
Elf Chapter 2 PQ The Forlorn Isle not rewarding influence

### ISSUE THREAD

**Issue by Damiel126** [WarEmu/WarBugs#4727]
Same issues as Swale of Miralei:
1. the area for the PQ is much further up than it should be
2. it shows as being Destruction not Order
3. it shows as chapter 1 not chapter 2

Killing a dryad will show influence being rewarded both on the interface and in the chat, but the influence is not actually awarded to the influence bar - that total remains the same. It's probably mapped to Dark Elf Chapter 1.
![abigaele_018](https://cloud.githubusercontent.com/assets/10399547/13547207/d778f8a2-e31c-11e5-9f48-e9eccf9b235a.jpg)

**Comment by Soulwhisper** [comment]
3. and below is also related to this #4557

**Comment by ellionkeman** [comment]
Looks like it is not working at all.
![kemie_017](https://cloud.githubusercontent.com/assets/18136746/14585968/5f8ec952-0491-11e6-9bd9-b8193e901a09.jpg)

**Comment by Soulwhisper** [comment]
This problem has to do with custom sizes :
**Changelog for April 8th, 2016
Nalgol:
- Changed the Way PQ Areas work now we have custom sizes for PQ areas**
It needs sometime.Report for any other PQ you find.

**Comment by Damiel126** [comment]
Influence panel now appears with the fixed zones, but no influence is being awarded to any of the chapter 1 or 2 elf PQs I've tested.

**Comment by wargrimnir** [comment]
These are fixed in next patch.
