### ISSUE TITLE
A Cure for What Ails Quest Reward

### ISSUE THREAD

**Issue by foxbeep** [WarEmu/WarBugs#4730]
The quest A Cure for What Ails given by Burlok Greysteel at 13k, 3k in Marshes of Madness has a reward option for Ironbreakers that is a pair of boots with no stats but armor.
I couldn't find what these stats were supposed to be (Caravaneer Steadkeeps) but the other reward option for the same quest does have stat bonuses.
![dickings_005](https://cloud.githubusercontent.com/assets/15528466/13547630/eeb9124a-e29f-11e5-9791-680d25f016f8.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
