### ISSUE TITLE
Thanalorn Forest PQ zone displaced

### ISSUE THREAD

**Issue by Damiel126** [WarEmu/WarBugs#4731]
Looks like all the Elf PQ lakes are displaced. Doesn't seem to be that the influence tracker isn't working, it's just that the areas on the map that define when you're in a PQ area seem to be offset with the PQ itself.
![abigaele_034](https://cloud.githubusercontent.com/assets/10399547/13547731/75c8ede6-e331-11e5-8007-e3690971b3d8.jpg)

**Comment by wargrimnir** [comment]
This was corrected some time ago.
