### ISSUE TITLE
Broken item BW Elf Chapter 1 influence reward

### ISSUE THREAD

**Issue by Damiel126** [WarEmu/WarBugs#4732]
'Brave Baston' is broken. When equipped, it looks like there is no weapon equipped. The appearance cannot be applied over the top of other equipment, and the icon is 'no icon set'. In the tome the entry also appears blank.
![abigaele_039](https://cloud.githubusercontent.com/assets/10399547/13547829/3342f88c-e335-11e5-8052-5400bba93367.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
