### ISSUE TITLE
moral 4 Fling explosives is bugged ?

### ISSUE THREAD

**Issue by Alouqua** [WarEmu/WarBugs#4734]
I used moral 4 in RvR, def keep, i waited to build it up, and as i play with my team we launch all our moral together to do a max of damage, when i done it yesterday, the destro got lots of lost and then yelled and said they will report bug because i used my moral 4. I'm now stuck in the "winds of chaos" aera bevause of this bug report.

So i want to know why i can't use this moral as i spend my spec points to have it ?
If this moral is bugged why don't wan the player or simply block it from buying it ?

Thanks for the help

**Comment by Evildoor** [comment]
Morale is bugged: #4556
Fix was implemented, but not pushed to live yet.
I'm closing this because morale bug was already reported and bugtracker is a wrong place for discussing bans and other penalties.
