### ISSUE TITLE
[Tactic] Long-held Grudge

### ISSUE THREAD

**Issue by Skutrug** [WarEmu/WarBugs#4735]
Equipping the Ironbreaker tactic "long-held grudge" produces the error message "Nonexistent tactic: 1393 Long-Held Grudge"
I have not verified if the tactic still works, it is accepted on the tactic bar despite the message.
Yesterday this message was not produced when I equiped it to tank one stalker hero

**Comment by Evildoor** [comment]
I do believe that the tactic is not implemented because overall aggro system is pretty much nonexistent.

**Comment by thorbolt80** [comment]
As aggro is working may be this tactic can be implemented now?
