### ISSUE TITLE
T3 Lair Bosses Dropping 2 of Same Loot

### ISSUE THREAD

**Issue by Dreamhous** [WarEmu/WarBugs#4737]
I've killed the T3 BFP Boss and Badlands boss, BFP Boss 3 times and Badlands Boss Once, every time it drops two of the same loot, so If an IB Helm drops it drops twice, never two unique items.

**Comment by genisaurus** [comment]
Not a bug. There is no requirement that the items be unique, just that they be usable by at least one member of the party.
