### ISSUE TITLE
Rank 20 and no chicken in t1

### ISSUE THREAD

**Issue by 13jack13** [WarEmu/WarBugs#4740]
As title says, I'm currently in Nordland, with my Witch Hunter **Strigo**, rank 20 rr 19, and flagged for rvr,The character is able to roam, attack etc. and is not transformed in chicken. I try to walk the whole rvr lake.

**Comment by 13jack13** [comment]
Edit. It will unflag automatically once stepping out the rvr lake.

**Comment by Tiggonos** [comment]
always provide screenshots...

**Comment by 13jack13** [comment]
I also contacted a GM Saturday at 9 pm Amsterdam time about it. I don't need to prove it. They just need to know that the problem is there and look after it. On a screen you don't see nothing more than I said.

**Comment by ozarmidrashim** [comment]
Must have been long-dealt with
