### ISSUE TITLE
The Grisly Herd PQ - Order

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4743]
High Pass PQ. Cant get more kills than these.**(Check Image below)**.Looks like stuck to Stage 1 forever.
![pq](https://cloud.githubusercontent.com/assets/16864486/13550561/78f79e8e-e329-11e5-89f7-e760c9dbb121.jpg)

**Comment by ChronoVarience** [comment]
This one can be closed; I got a bag this morning US MT time. 
Video here:  http://plays.tv/video/574c6da5035f05eb21/grisley-herd-pq

**Comment by Soulwhisper** [comment]
Someone re-open this.Over-counts bestigors in Stage 1.
![maxeras_016](https://cloud.githubusercontent.com/assets/16864486/16267688/ca1836d8-3893-11e6-85a5-e3a2a264d06b.jpg)
