### ISSUE TITLE
Strange hands of shaman player.

### ISSUE THREAD

**Issue by Cupkiller** [WarEmu/WarBugs#4746]
Took these screenshots of this new shaman type which came straight from the warp of chaos.
![thegloriusone_004](https://cloud.githubusercontent.com/assets/17481515/13551415/9154659e-e341-11e5-8465-3990dc5f27c6.jpg)
![thegloriusone_002](https://cloud.githubusercontent.com/assets/17481515/13551424/d60dd864-e341-11e5-96e2-2ac1a380b665.jpg)

**Comment by Evildoor** [comment]
Same bug sometimes happened on life, i doubt that we can do anything here. Closing unless someone proves that this is a different problem which can be solved by us (for example, if it's some item with weird model).
