### ISSUE TITLE
[Charge] + Jump

### ISSUE THREAD

**Issue by roadkillrobin** [WarEmu/WarBugs#4750]
Seem to break the anti bunny jump penalty.
Had a Slayer press Charge + Jump every time he got low on HP and it literally teleported him away.

**Comment by Evildoor** [comment]
Not sure if it really breaks... I mean, penalty starts at a pretty low value of 5%, while charge gives 50%...

**Comment by Evildoor** [comment]
Since nobody provided a clarification, i'm closing this.
