### ISSUE TITLE
[Item] Brave Waraxe

### ISSUE THREAD

**Issue by Arvetaith** [WarEmu/WarBugs#4752]
There is a slayer/ironbreaker 2h axe awarded by Elf chapter 1 inf that currently has no damage or attack speed stats, so it just constantly deals a stream of 1 damage hits, but each of those hits can cause procs such as Flame of Rhuin or Prayer of Devotion
![arvetait_000](https://cloud.githubusercontent.com/assets/17685252/13553843/a5412a5e-e38e-11e5-9c89-c70fd29f99d9.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
