### ISSUE TITLE
Pounce through keep door in Marshes of Madness

### ISSUE THREAD

**Issue by Elabas** [WarEmu/WarBugs#4754]
It is posible to get inside a keep via pounce.

Whene you pounce a keep door you are stuck inside the door wich alows you to look through the door an select a guard on wich you can pounce wich gets you inside. I discoverd this on the Keep in Marshes of Madness. Dont know if it is possible on other doors.

**Comment by Evildoor** [comment]
Hmmm. This is a bit different from #1642...

**Comment by ozarmidrashim** [comment]
According to the hotbar, Pounce should not work on inorganic targets. Changed.
