### ISSUE TITLE
[Crafting] Aphotecary breaks with low level ingredient & lvl 200 extenders

### ISSUE THREAD

**Issue by notre4ror** [WarEmu/WarBugs#4755]
Using a lvl 75 Wispy Dandedragon ingredient with two extenders of lvl 200 and one resin lvl 200 ( I try with container lvl 1 and 150 with the same result) i get an system error message "An error on the crafting system has occurred" and breaks the apo, relog fix the problem, but you can't make this kind of potions.

**Comment by genisaurus** [comment]
Using more than one level 200 extender provides no benefit. Do the system probably doesn't account for the possibility.

**Comment by acidicrain** [comment]
https://youtu.be/1cnKhcbxUA8
similar occarance video of bug

**Comment by Natherul** [comment]
should be fixed as of today
