### ISSUE TITLE
[SW\SH] Whirling Pin can be used while rooted

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#4758]

**Comment by Nfkillz** [comment]
sticky squigz too

**Comment by Evildoor** [comment]
Is this wrong?

**Comment by taccr** [comment]
Used to be exactly like this on live.
It was pretty annoying since it also worked with morale roots.

You could in theory consider this as a bug. Up to you.

**Comment by Torquemadra** [comment]
WH/WE self punting out of champions challenge got fixed on live, I would consider this a bug

**Comment by Evildoor** [comment]
I agree that jumping while being affected by Champion's Challenge is wrong, but not sure if we talk about simple roots.

**Comment by Silentguard** [comment]
You using self punt which should not break control, but anyway you self punt out of place where you been rooted, fly away with roots on your legs and keep standing for a whole duration of effect. So where the logic?

Even if we consider it as a balance issue i see no point in granting two most protected rdps classes in game by root avoid with 30 sec cd.

**Comment by ozarmidrashim** [comment]
If Whirling Pin and Sticky Squigz do not grey out when the client is subjected to a root, I will not change their serverside handling.

**Comment by ozarmidrashim** [comment]
The snare component will fire when rooted. The self-knockback component will not.
