### ISSUE TITLE
Quest completed icon showing when one step in quest is not yet complete

### ISSUE THREAD

**Issue by magicthighs** [WarEmu/WarBugs#4759]
For the skaven event quest "Raising the Empire Banner" the quest NPC showed an orange quest completed icon above his head, even though I hadn't fulfilled one step of the quest (talking to the BO Marshall) yet.
![verdammt_015](https://cloud.githubusercontent.com/assets/6838946/13555221/0b69be32-e3bb-11e5-84a2-a5d283bc7f01.jpg)

**Comment by Yellowpillow** [comment]
may be related to #8000

**Comment by Luth-RoR** [comment]
Using https://github.com/WarEmu/WarBugs/issues/8000 for this, as it is a general issue with many quests.
