### ISSUE TITLE
Deathstone Quarry PQ - Order

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4764]
- Some furries fall out of the PQ area.Killing them doesnt count nor give influence.

**Comment by Soulwhisper** [comment]
![toufekiaaaa_012](https://cloud.githubusercontent.com/assets/16864486/14764293/4a4588b8-09bb-11e6-9a67-70f66be74148.jpg)
Look at the counter...:P

**Comment by Soulwhisper** [comment]
On Stage 1 Killing Rift Horrors counts them as Rift Furries.

**Comment by Soulwhisper** [comment]
#6935

**Comment by Soulwhisper** [comment]
Some furies fall out of the PQ even if they are inside...

**Comment by saupreusse** [comment]
Furries...
