### ISSUE TITLE
Welcome to Troll Country PQ - Order

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4768]
Hill Crushers shouldnt spawn at Stage 2 and 3 in the farm area.
Actually they shouldnt spawn at all at 2 and 3 Stages.

**Comment by Soulwhisper** [comment]
![paterellas_010](https://cloud.githubusercontent.com/assets/16864486/13567070/b45e56d2-e461-11e5-9429-8d5de271061f.jpg)
2 pigs spawn at the same location...they must spawn at square formation to prevent killing Mobs at Stage of PQ.

**Comment by rameden** [comment]
Hill Crushers will now only spawn in stage 1
Pigs will now only spawn if PQ is in stage 1
