### ISSUE TITLE
inevitable power quest step the whispering voice

### ISSUE THREAD

**Issue by Dirkdaring** [WarEmu/WarBugs#4772]
I completed the step to retrieve the book from the Blooded Librarian  but when i go to complete turn in, the quest does not complete and  advance.

![vangrief_000](https://cloud.githubusercontent.com/assets/17651165/13555891/f0d4365c-e391-11e5-93af-ca29762505c2.jpg)

**Comment by Torquemadra** [comment]
Weird one, fixed next patch, sorry for inconvenience

**Comment by Dirkdaring** [comment]
Ok did the quest on another character last night, worked fine. Tried it again on this character, it still doesn't give me an option to select a reward.  Dropped the quest and killed the librarian 3 more times dropping that step in quest and accepted it again each time I go for completion turn in. It doesn't give him a reward to select and complete the quest. Odd may need to drop a few previous steps and try again.

**Comment by Torquemadra** [comment]
Dont, its an issue with the marauder weapon selection, its fixed next patch
