### ISSUE TITLE
GCD bug

### ISSUE THREAD

**Issue by aaltom** [WarEmu/WarBugs#4773]
HI,
sometimes (not all time) GCD is starting when abilities cant be used.
i try to use an ability which, for some reason can not work at this moment, but GCD is starting for nothing. So its painfull, is it normal?

**Comment by Evildoor** [comment]
More info needed.

**Comment by aaltom** [comment]
exemple : i try to use an abilitie when i kite, but cant use the abilitie (cause i m not in a good position), and sometimes the GCD is starting however the abilitie was not used. sorry for my english.

**Comment by taccr** [comment]
I think what he is saying is that abilities that require facing will still try to cast and trigger a gcd even if not facing the target.
If it's a channeled ability then it will do the full channel and interrupt in the end even if you were not facing properly at the beginning of the cast.

**Comment by Evildoor** [comment]
I do believe that comments to #1816 apply here as well.

**Comment by Evildoor** [comment]
No objections to my comment, so closing per #1816.
