### ISSUE TITLE
Oaktalon Screecher animal mob can be scavenged

### ISSUE THREAD

**Issue by ropuch** [WarEmu/WarBugs#4774]
Oaktalon Screecher birds can be scavenged (Avelorn 9,8K 27k)

**Comment by Torquemadra** [comment]
applied appropriate type and subtype, fixed next patch

**Comment by Squea** [comment]
Cannot Butcher Oaktalon Screecher.

**Comment by Luth-RoR** [comment]
Next time screenshots please.

**Comment by Lheana** [comment]
They can be correctly butchered.
