### ISSUE TITLE
[tactic] focused offense not working

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#4775]
error in formula 0 x 1.15 is 0 ^^

![mago_033](https://cloud.githubusercontent.com/assets/13809443/13556726/3cefce80-e3e1-11e5-9472-eb19e75b1ddb.jpg)

**Comment by taccr** [comment]
Damage is scaled properly for me. Just showing wrong in the getstats formula.

**Comment by Tiggonos** [comment]
i dont see any increase in the skill tooltips. you? or is it calculated on the fly when hitting?

**Comment by taccr** [comment]
Correct - Currently now showing on tooltip values.
Not sure if that was ever the case.

**Comment by taccr** [comment]
Same display issue on incoming damage modifiers.

**Comment by ozarmidrashim** [comment]
You need to know how to read the stats.

[x + y] * z just means (value of base stat bonus) + (value of total linear stat modifier) * (value of percentage stat modifier).

This formatting is just an aid to understanding stats for which a linear stat modifier or a base stat bonus has a regular meaning. Incoming and outgoing damage as well as build time modifications are examples of where reading it like this is meaningless.
