### ISSUE TITLE
Sorcerer Vision of Domination utility (Vision of Torment addition)

### ISSUE THREAD

**Issue by Paninii** [WarEmu/WarBugs#4779]
I was looking up some sorcerer clips on youtube and noticed something i hadn't before.
One of the movies showed the tooltip of the tactic Vision of Domination.
This was a movie by a RR64 Sorcerer so the numbers will be according to that.

**When Vision of Torment ends, you will  regain 80 action points**.  Word of Pain's Willpower debuff is increased to 351 and will deal 1119 Spirit damage at the end of the debuff duration.

Now the numbers in this tooltip aren't important.  What is important is that there is a part for Vision of Torment which isn't there on RoR.
This could ofcourse have something to do with our current patch level and this not being in then, but i thought i'd put in bugtracker anyway.

Link to the video, you'll want to check around 1:12 to 1:16 for the tooltip.
https://www.youtube.com/watch?v=6xR0dVK2Rfk

**Comment by Torquemadra** [comment]
Things change I would surmise, originally the only thing that tactic added was +50AP when vision of torment ended.

**Comment by taccr** [comment]
False report. Video is from 2011. Tactic was modified in [1.3.5](http://warhammeronline.wikia.com/wiki/Game_Update_1.3.5/Combat_and_Careers)

`Vision of Domination: This tactic will now increase the value of Word of Pain's Willpower debuff, increase the amount of damage, and cause the effect to expire and deal its damage more quickly. The ability "Vision of Torment" is no longer affected by this tactic.`

**Comment by ozarmidrashim** [comment]
Closed per taccr.
