### ISSUE TITLE
ToK unlock kill 1000 Empire rewards The History of the Empire

### ISSUE THREAD

**Issue by adeie** [WarEmu/WarBugs#4782]
Killing 1000 empire awarded the ToK unlock The History of the Empire, the unlock also awards a title which is currently not working : The Anarchist

![empire tok unlock bug](https://cloud.githubusercontent.com/assets/15959651/13557552/8d18f2e8-e3ea-11e5-9bbe-f16d782bcfc2.jpg)

**Comment by Torquemadra** [comment]
fixed next patch
