### ISSUE TITLE
Item: [Faded Scroll] does not give unlock

### ISSUE THREAD

**Issue by Reggaewaldo** [WarEmu/WarBugs#4785]
Item does not give unlock as it should.
![skarmklipp](https://cloud.githubusercontent.com/assets/13517919/13557877/0495ce24-e3f8-11e5-9037-80d018a56687.PNG)

Item name: Faded Scroll
Source: http://warhammeronline.wikia.com/wiki/When_There%27s_a_Will

**Comment by Torquemadra** [comment]
tok unlocks from clickies are currently not supported

**Comment by Sapphiratelaemara** [comment]
Adding location
![image](https://cloud.githubusercontent.com/assets/23622177/20468441/1f555958-af97-11e6-86c8-1711dcd14e87.png)
