### ISSUE TITLE
Agro issue - NPCs healing to full

### ISSUE THREAD

**Issue by kmelesh** [WarEmu/WarBugs#4789]
Him i am not 100% certain of this issue however checking this boss lair multiple times a day and examining corpse position i belive that the t1 lair boss in dwarf is bugged and does not respawn after death, it only reappears after restart 

furthermore there is a secondary bug with lair bosses the second it kills any member of your party its health resets to 100%

**Comment by kmelesh** [comment]
am wrong about dwarf respawn but secondary bug is there for sure

**Comment by Torquemadra** [comment]
With recent changes it seems if a NPC kills the primary (only?) agro holder they reset and heal up regardless of other players having been attacking it and the NPC in question having dots and effects still upon it from combat.

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=13939
