### ISSUE TITLE
Bestial Token reward bug

### ISSUE THREAD

**Issue by Rhombutts** [WarEmu/WarBugs#4790]
![slagnarf_554](https://cloud.githubusercontent.com/assets/13096975/13561018/5400c688-e3f5-11e5-8863-50595c49359d.jpg)

One of the newest rewards for a bestial token is 2h axe for orcs. I accidently bought one, it doesn't equip as a trophy, it does equip as a weapon.

Refund pls :)

**Comment by Ryanfawkez** [comment]
You're not getting a refund. Item will be changed back to what it was in the next patch., by which you'll have a usable trophy.
