### ISSUE TITLE
[Appearance] Rappin of the Eternal

### ISSUE THREAD

**Issue by Rhombutts** [WarEmu/WarBugs#4791]
The cloak "Rappin of the Eternal" which gives +30 strength +20 wounds can not have its appearance altered with the switch trick.
![slagnarf_555](https://cloud.githubusercontent.com/assets/13096975/13561220/629e0ef0-e3f8-11e5-9b13-57a180507289.jpg)

**Comment by Vandorkholme** [comment]
This isn't a bug.

**Comment by Ryanfawkez** [comment]
@Vandorkholme - Yes it is. Cloak was flagged as a two-hander, which disallows applying the 'one hander' appearance cloaks to it. Whether or not it's BoP shouldn't matter; the work-around is intended.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
