### ISSUE TITLE
Martyr's Blessing

### ISSUE THREAD

**Issue by Fabreese** [WarEmu/WarBugs#4795]
This warrior Priest ability doesn't work as described. You just heal your party member within 30ft, Not alla allies in 30ft.

**Comment by Evildoor** [comment]
#1864 is supposed to be fixed.

**Comment by ozarmidrashim** [comment]
False report. Please don't waste my time.

We need to start closing any and all ability reports made without evidence on sight.

![solaris_029](https://cloud.githubusercontent.com/assets/6764164/13568957/fae52126-e45c-11e5-90db-e5dd9fdf3457.jpg)

**Comment by Soulwhisper** [comment]
https://www.youtube.com/watch?v=ic50gZ3HUIo

**Comment by Evildoor** [comment]
Not enough evidence for my liking. That BW's hp bar could have been bugged.

**Comment by Soulwhisper** [comment]
Yeah i know...if i found any evidence ill post it here.

**Comment by Soulwhisper** [comment]
https://www.youtube.com/watch?v=ypsPmjyYPPg
Feel free to pause and check Combat log.
I give you 2 names.Scyte and Penelopa Lost.

**Comment by Soulwhisper** [comment]
https://www.youtube.com/watch?v=reMYXw9HrOM
One more.Elricka,Cosmopavone,Elizabetka.

**Comment by Soulwhisper** [comment]
https://www.youtube.com/watch?v=0vqSZz13fzU
Last one.Musticus.
It behaves strange in battles when there is a lot of people...it doesnt catch everyone but i dont know whats the source of the problem.
If you want more footage and better video evidence tell me.

**Comment by Soulwhisper** [comment]
Hmm...this one i really akward.None of the names in Combat Log are on my screen in front of me.
Illef(SLAYER),Warhawkrichard(WP),Norely(BW) and Spiling(ENGI) should be mentioned in combat log but they didnt.Also check WP and BW dont get healed.
https://www.youtube.com/watch?v=UCYgBdcIHzA

**Comment by Soulwhisper** [comment]
This is definitely buggy when there are a lot of allies around you(On big fights).
please re-open it.

**Comment by ozarmidrashim** [comment]
Nope. What is actually happening here is that the target selection code is iterating the first 9 allies to be found, even if they have maximum HP.
