### ISSUE TITLE
Zealot Creation Hairs and Beards

### ISSUE THREAD

**Issue by boddole** [WarEmu/WarBugs#4796]
Did a search for "zealot hair" and didn't find anything:

-Hairs 3 and 4 are coming 'out of the character's face'
![hair clipping](https://cloud.githubusercontent.com/assets/17700413/13566022/4e08d9a6-e408-11e5-8637-3ab17994b3bf.png)

-Beards 3,6,7,8 seem to be made from taffy and stretch up and down as the character moves (some down to the character's waist).
![beard streatching](https://cloud.githubusercontent.com/assets/17700413/13565969/19cc4786-e408-11e5-8e38-898ee485cf30.png)

**Comment by Evildoor** [comment]
I'm pretty sure it's client issue, therefore I doubt that we can do anything here.

**Comment by boddole** [comment]
Anything I can do about it from my end?

**Comment by Evildoor** [comment]
I don't think so. Closing since nobody added anything to my conjecture.
