### ISSUE TITLE
Several quest NPCs with double spawns

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#4797]
I have seen many quest NPCs that spawn twice in the same area. Most of them I have seen are located in T1 areas (since I've only been doing low level quests so far) but I suppose there are some duplicated NPCs at higher levels as well, as it seems like a common bug. I will add to this list when I find more and if some are fixed I will remove them from the list.
All kinds of mobs are affected by this double spawn bug; friendly mobs, enemy mobs, quest npcs etc.
For example, there are a lot of enemy double spawns in the area of Salzenmund PQ (Nordland) that are not mentioned in the list below.
1. Calgn Putrich in Norsca. (Seems to be fixed)
2. Bethraldar Redlash in The Blighted Isle.
3. Telathor Darkthorn in The Blighted Isle.
4. Rykoth Ebonglaive in Chrace.
5. Ullaris Virdett in The Blighted Isle.
6. Volruc Kinslayer in The Blighted Isle.
7. Pieter Falke in Nordland at Salzenmund PQ. (Seems to be fixed)
8. Rat Catcher Thomas in Nordland (at Salzenmund PQ).
9. Downtrodden Elder in Nordland (at Salzenmund PQ). His clone is repeatedly killed by nearby enemies due to the location of the second spawn point.
10. Emile Ahlstrom in Nordland (at Salzenmund PQ).
11. Watch Captain Ferumund in Nordland (at Salzenmund PQ).
12. Dirk Eisenhauer in Nordland (at Salzenmund PQ). He spawns 3 times.
13. Elector's Watch double spawns. Just an example from the area around Salzenmund PQ in Nordland where there are a lot of enemy double spawns.
14. Fritz Meinrich in Mount Bloodhorn.
15. Chompa in Mount Bloodhorn.
16. Kargil the Grim in Mount Bloodhorn.
17. Haladis Valewarden in Ellyrion.
18. Alvar in Norsca. He spawns 3 times.
19. Simon Hirtzel in Ostland. Spawns 3 times.
20. Bilemaw in Troll Country.
21. Halmund Pfeiffer in Troll Country.
22. Aethlys Dreamsong in Chrace.
23. Ghourna'r in Troll Country.
24. Hans Dobel in Troll Country.
25. Otto von Buergh in Troll Country.
26. Malivus the Tumored in Marshes of Madness.
27. Gerevus Lionmane in Chrace.

**Comment by ElMosquito** [comment]
There is this gobbo called Nobwart Noggins that also appears on many places with the same quests everywhere. I don't know if it is supposed to be like that because he can be found in many maps as well (two times in Talabecland near chapter 10 and I found him in Troll Country as well).

**Comment by Evildoor** [comment]
Nobwart is a special case: #1183

**Comment by ElMosquito** [comment]
Update with more double spawns.

Pieter Falke at Salzenmund PQ (Nordland).
![pieter](https://cloud.githubusercontent.com/assets/16590792/13685172/755d3a92-e70f-11e5-9e71-ec948ee22ab5.jpg)

Rat Catcher Thomas in Salzenmund PQ (Nordland). He is not a quest NPC but he still has a clone of himself in the same area.
![ratcatcher](https://cloud.githubusercontent.com/assets/16590792/13685349/4d31e300-e710-11e5-9721-e1aa052e1a1c.jpg)

Downtrodden Elder in Salzenmund PQ (Nordland), where the new addition of the quest NPC is killed by nearby mobs.
![elder](https://cloud.githubusercontent.com/assets/16590792/13685437/c7f53a74-e710-11e5-9d7e-c2d7e6b4aaf4.jpg)

Emile Ahlstrom in Salzenmund PQ (Nordland).
![emile](https://cloud.githubusercontent.com/assets/16590792/13686225/2a00fb46-e715-11e5-9d86-85d4c812a742.jpg)


There are a lot of double spawn of enemy mobs in the area of Salzenmund PQ as well. When I did some quests in the area just now there were a lot more enemies around than last time I did the quests (1-2 months ago). For example, the enemy mob Watch Captain Ferumund spawns twice.
![watch](https://cloud.githubusercontent.com/assets/16590792/13685900/3cdac672-e713-11e5-8bdc-efe4041acd11.jpg)

Dirk Eisenhauer even spawns three times.
![dirk](https://cloud.githubusercontent.com/assets/16590792/13686087/48193b6c-e714-11e5-8030-faa4995bbb32.jpg)

Here you can see some Elector's Watch that are lined up in pairs (double spawns but with coordinates slightly different from each other).
![linedup](https://cloud.githubusercontent.com/assets/16590792/13686195/f9ad4634-e714-11e5-8f60-feec1954a65e.jpg)
