### ISSUE TITLE
Icons/Names over head Rally Masters

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4798]
When you get enough influence to pick first-second or third reward rally masters dont get the sky blue icon over head which indicates that you can pick your reward.
## List of names : 
**There is still an issue that the icon wont turn Blue over the NPCs head nor on the Minimap.It just stays grayed out(Incomplete)**
- [x] Krasa Falkenheim
- [x] Caelas Whitewave
- [x] Emil Traschsel
- [x] General Breuer
- [x] Werner Fassbinder
- [x] Konrad Riese
- [x] Captain Victor Krauss
- [x] Greta Machholt
- [x] Siegmund Kraemer
- [x] Eldred Krebs
- [x] Captain Kleinke
- [x] Aelthyan Brightblade
- [x] Menuthil Fargaze
- [x] Saelir Haelir
- [x] Valdred Kaltenbach
- [x] Captain Oswin Breitenbach
- [x] Sergant Kraussner
- [x] Grizela Hirtzel
- [x] Aen Cinderblood

**Comment by Soulwhisper** [comment]
![paterellas_009](https://cloud.githubusercontent.com/assets/16864486/13567795/14531010-e466-11e5-8fdb-7b99fa1771de.jpg)
Proof.Rally master should have the blue icon with skull over his head.

**Comment by Soulwhisper** [comment]
![123](https://cloud.githubusercontent.com/assets/16864486/13947997/4c028434-f026-11e5-8d15-c0f8593eb98f.jpg)
Now text is missing also over this rally master head in Chapter 1 Empire.

**Comment by Soulwhisper** [comment]
![paterellas_034](https://cloud.githubusercontent.com/assets/16864486/14062693/1adff25e-f3b1-11e5-81ff-21b07b3bfc40.jpg)
This is what it should look like.

**Comment by Soulwhisper** [comment]
General Breuer Rally Master is missing icon above head

**Comment by Soulwhisper** [comment]
Werner Fassbinder too.

**Comment by Soulwhisper** [comment]
Konrad Riese too.

**Comment by Soulwhisper** [comment]
Captain Victor Krauss too.

**Comment by Soulwhisper** [comment]
Greta Machholt

**Comment by Soulwhisper** [comment]
Thoren Hammerwall(Although this guy doesnt work at all yet)

**Comment by Soulwhisper** [comment]
Emil Traschsel

**Comment by Soulwhisper** [comment]
Menuthil Fargaze

**Comment by Soulwhisper** [comment]
Caelas Whitewave

**Comment by Soulwhisper** [comment]
Krasa Falkenheim

**Comment by StaH84** [comment]
Eldred Krebs

**Comment by StaH84** [comment]
Captain Kleinke

**Comment by StaH84** [comment]
Sigmund Kraemer

**Comment by Soulwhisper** [comment]
- Thoren Hammerwall(Although this guy doesnt work at all yet)
- Krasa Falkenheim
- Caelas Whitewave
- Menuthil Fargaze
- Emil Traschsel
- General Breuer
- Werner Fassbinder
- Konrad Riese
- Captain Victor Krauss
- Greta Machholt

**Comment by Soulwhisper** [comment]
@StaH84 Just Delete your comments when you see them added on the top list. Keep reporting though. Thanks

**Comment by StaH84** [comment]
Will do!

**Comment by Soulwhisper** [comment]
TY

**Comment by Soulwhisper** [comment]
**Patch 20/09/2016
- Fixed the state information of many NPCs. This will correct their icon display on the map and minimap.**

**Closing this because it was major issue and its fixed by Aza!
If you find any specific Rally Master NPC that misses icon/name over his head create an individual ticket please.**
