### ISSUE TITLE
No getting XP for the Guild

### ISSUE THREAD

**Issue by Sharzar** [WarEmu/WarBugs#4800]
Hello Guys,

I gain no XP for my Guild with all my Chars, they are all on MAX LVL.

The Question is, how was it on Live, do i have to play a lots of alts to reach/get xp for the guild or is it only me that i have the issues that i dont get any xp for the guild, with any Char at lvl 35/40.

Renown Points still working i get Renown Points for the Guild but no XP

Greetings

Sharzar
Guild = "Hasserfüllt"
Destruction

**Comment by Evildoor** [comment]
#4408
