### ISSUE TITLE
T3 Advanced Reward Magus

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#4802]
One of the cloaks for magus in elf T3 influence rewards seem to have wrong stats with reduced chance to be parried instead of disrupted. This issue has been mentioned before but was not fixed: https://github.com/WarEmu/WarBugs/issues/2498

![maguscloak](https://cloud.githubusercontent.com/assets/16590792/13574124/0ca5e0aa-e483-11e5-9fc3-6ce221908cf2.jpg)

**Comment by Evildoor** [comment]
Read the rules of the bugtracker.

**Comment by ElMosquito** [comment]
Where can I even read the rules? I can not find any rules anywhere around this page.
