### ISSUE TITLE
Wrong influence rewards (Magus, Zealot)

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#4803]
I have been checking all the influence rewards for several classes in the game and I have found some common patterns about the influence rewards for each class and race. I will list wrong influence rewards for the chaos classes here.

Note: These rewards do not appear in the tome of knowledge (except for the rings) and can only be seen/selected at the rally master of each chapter.

If nothing is said about the classes in the following list, it means their influence rewards for that specific chapter is correct already.

Chaos Chapter 1
    - Elite reward: Opportunist Skull (zealot charm)
    *Affected classes: Magus

Dark Elf Chapter 1
    - Elite reward: Recrudescent Effigy (zealot charm)
    *Affected classes: Magus

Greenskin Chapter 1
    - Elite reward: Recroot Skull (zealot charm)
    *Affected classes: Magus

Chaos Chapter 2
    - Elite reward: Skull of the Passage (zealot charm)
    *Affected classes: Magus

Chaos Chapter 3
    - Elite reward: Plundered Skull (zealot charm)
    *Affected classes: Magus

Dark Elf Chapter 3
    - Elite reward: Skull of Trammels (zealot charm)
    *Affected classes: Magus

Dark Elf Chapter 4
    - Advanced reward: Denrazer's Effigy (zealot charm)
    *Affected classes: Magus

Greenskin Chapter 4
    - Elite reward: Goldfist Effigy (zealot charm)
    *Affected classes: Magus

Dark Elf Chapter 5
    - Advanced reward: Senburian Effigy (zealot charm)
    *Affected classes: Magus

Greenskin Chapter 5
    - Advanced reward: Tainted Creek Effigy (zealot charm)
    *Affected classes: Magus

Chaos Chapter 6
    - Elite reward: Reaper's Effigy (zealot charm)
    *Affected classes: Magus

Dark Elf Chapter 6
    - Advanced reward: Necrolith Skull (zealot charm)
    *Affected classes: Magus

Dark Elf Chapter 7
    - Basic reward: No basic rewards
    *Affected classes: Magus, Zealot

Greenskin Chapter 7
    - Elite reward: Effigy of Bar Dawazbak (zealot charm)
    *Affected classes: Magus

Dark Elf Tier 2 RvR
    - Elite Reward: Reaver Skull (zealot charm)
    *Affected classes: Magus

Greenskin Tier 2 RvR
    - Elite reward: Fangbreaker Skull (zealot charm)
    *Affected classes: Magus

Chaos Chapter 8
    - Basic reward: No basic rewards
    *Affected classes: Magus, Zealot
    - Elite reward: Plaguewood Focus (zealot charm)
    *Affected classes: Magus

Dark Elf Chapter 8
    - Advanced reward: Coaxer Effigy (zealot charm)
    *Affected classes: Magus

Greenskin Chapter 8
    - Basic reward: No basic rewards
    *Affected classes: Magus, Zealot
    - Elite reward: Firebrew's Fightin' Effigy (zealot charm)
    *Affected classes: Magus

Chaos Chapter 9
    - Elite reward: Blightstone Focus (zealot charm)
    *Affected classes: Magus

Greenskin Chapter 9
    - Elite reward: Sea Stunty Obscura Ring (ring with toughness and wounds should be for only blackguard)
    *Affected classes: Magus, Zealot

Chaos Chapter 10
    - Basic reward: No basic rewards
    *Affected classes: Magus, Zealot

Greenskin Chapter 10
    - Basic reward: No basic rewards
    *Affected classes: Magus, Zealot

Dark Elf Chapter 11
    - Basic reward: No basic rewards
    *Affected classes: Magus, Zealot
    - Elite reward: Effigy of Icy Blood (zealot charm)
    *Affected classes: Magus

Chaos Chapter 12
    - Elite reward: Focus of Insanity (zealot charm)
    *Affected classes: Magus

Dark Elf Chapter 12
    - Advanced reward: Newshore Effigy (zealot charm)
    *Affected classes: Magus

Chaos Chapter 14
    - Basic reward: No basic rewards
    *Affected classes: Magus, Zealot

Greenskin Chapter 14
    - Basic reward: No basic rewards
    *Affected classes: Magus, Zealot
    - Elite reward: Obscura Ring of da Plague (strength and toughness should be for only blackguard)
    *Affected classes: Magus, Zealot

**Comment by sioding** [comment]
fixed with patch from 09.03.2018
