### ISSUE TITLE
[Ironbreaker Tactic] 'Seen it all Before' increases crit damage taken instead of reducing it

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#4805]
Tested it on a few mobs and it looks like the crit damage taken is increasing instead of decreasing.

**Comment by taccr** [comment]
Provide a .getstats output to make this easier.

**Comment by Cimbas** [comment]
Okay here 2 screenshots 
![cimbam_004](https://cloud.githubusercontent.com/assets/16117730/13579414/c091ce20-e49d-11e5-823a-dbb8f5b168d0.jpg)

First one is without 'Seen it all before'. Base damage of the salamander is 68 damage afaik max crit damage without modifiers is 1.6 times base --> 108,8 damage.

![cimbam_005](https://cloud.githubusercontent.com/assets/16117730/13579484/19fff8c4-e49e-11e5-8929-85fdb4ac1f76.jpg)

Second one with 'Seen it all before' one would expect the crit damage to go down but instead the mob crits me for consistently higher values. And crit spike with 114 and 110 damage are above afaik what should be possible.

Interestingly enough the .getstat show -15 critical damage taken... so maybe it's not the tactic itself but the implementation of -critical damage.

**Comment by Thorgatin** [comment]
For a while i tested it with the "enemy" combat log statistics and without the tactic the average crit damage vs the same NPC type (and level) is lowered over the time; with the tactic slotted it is raised again.

**Comment by Luth-RoR** [comment]
Reopening this as the bug is back.


with tactic: 
```
Feathered Coin Acolyte's attack critically hits you for 148 damage. (586 mitigated)
Feathered Coin Acolyte's attack critically hits you for 157 damage. (618 mitigated)
```
without tactic:
```
Feathered Coin Acolyte's attack critically hits you for 133 damage. (525 mitigated)
Feathered Coin Acolyte's attack critically hits you for 144 damage. (565 mitigated)
```
though getstats still says 
```
BONUSTYPES_EBONUS_CRITICAL_DAMAGE_TAKEN -15 [(0 + -15) x 1]
```

**Comment by Luth-RoR** [comment]
Fixed.
