### ISSUE TITLE
Grub Broke-nose in Barak Varr  don't allow to complete the task

### ISSUE THREAD

**Issue by marcoc5417** [WarEmu/WarBugs#4806]
Grub Broke-nose in orc camp "Foultooth's" in Barak Varr  don't allow to complete the task "Fixin' da boyz"

**Comment by ElMosquito** [comment]
Have you checked what the requirements are for completing the quest? Maybe read what it says or look up on google to make sure the requirements are right. I have noticed several quests that somehow get wrong requirements. E.g. I am supposed to talk to a certain NPC on destro side, according to the description, but the requirements says something completely different like talking to some NPC on order side or kill x amount of some random mob.
Abandon the quest and pick it up again solves the problem and you can finish the quest when the right requirements are displayed in the tome of knowledge.
I will write a bug report about this problem if/when I have figured out what is triggering this kind of problem (I have not been able to recreate the bug under controlled circumstances, even though I have had this bug on a few T1 quests on more than one character).

**Comment by sioding** [comment]
checked - works fine for me. close
