### ISSUE TITLE
Inevitable Power Quest - Librarian's Blood Tome bug?

### ISSUE THREAD

**Issue by Bassror** [WarEmu/WarBugs#4808]
I killed the champion Librarian, went and talked to The Whispering Voice NPC, but nothing happens when i click 'complete' in order to finish this part of the Inevitable Power quest.

**Comment by Torquemadra** [comment]
Marauder? A weapon bugged out, its fixed next patch and you have a wider selection.

**Comment by Bassror** [comment]
Yes, Marauder. But it's not the weapon bug, i cannot even complete this part of the quest, Librarian Blood Tome to continue the Inevitable Power chain. The NPC 'The Voice Whisperer' does not complete the quest, it simply does nothing. After clicking the complete button, the quest screen closes and nothing happens, and the NPC still have the yellow quest marker above the head.

**Comment by Torquemadra** [comment]
Its the weapon bugging out thats preventing the selection because its not showing anything, you are at the reward stage but a weapon bugged the hell out and messed it all up.

Its fixed next patch

**Comment by Torquemadra** [comment]
#4772

**Comment by Bassror** [comment]
Got it now Torq, thanks!
