### ISSUE TITLE
Wrong icon on witch elf shoulders

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#4809]
The RvR influence rewards for witch elf in Dark elf T2 (Shadow Spire Throatlatch, Spite's Throatlatch and Reaver throatlatch) have the icon of a helm instead of shoulders.
![shoulders](https://cloud.githubusercontent.com/assets/16590792/13585688/7fb75792-e4bd-11e5-9b4b-50c043a442bd.jpg)

**Comment by Torquemadra** [comment]
fixed next patch
