### ISSUE TITLE
[Shamman] Instant rez bug teleports to another map

### ISSUE THREAD

**Issue by notre4ror** [WarEmu/WarBugs#4810]
Jumping during the instant rez (using instant rez tactic) causes a bug wich teleport the target to the same coordinates but on the diferent map.
For example I try this on High pass on tavern and the target gets teleported to the same coordinates but on Talabecland.

**Comment by Evildoor** [comment]
Maybe it's #1627, and not the jump?

**Comment by notre4ror** [comment]
Maybe, but only happens to me when i jumped before using rez, it's true it's at the bottom of the map but i try several times on tavern and only happens after jumping.
