### ISSUE TITLE
Keep PQ rolls

### ISSUE THREAD

**Issue by roadkillrobin** [WarEmu/WarBugs#4814]
Only seem to take damage done into consideration.
Dps always have the highest contributing factor and if you're dedicated healer you don't even get to roll sometimes.

**Comment by Soulwhisper** [comment]
Noticed that too...healers almost never on the list...only DPS.Shouldnt be like that though.Contribution comes from healing too.

**Comment by taccr** [comment]
There's currently no contribution or anything implemented.
It's totally random atm and when you are in the rvr zone you will get contribution anywhere.

**Comment by Vandorkholme** [comment]
Its definitely by damage, through multiple keep takes sorcs got gold loot bags every time.

**Comment by genisaurus** [comment]
Take it from a dev - there is _**no**_ contribution system in place yet. The "contribution" rating is entirely random for now, until a suitable algorithm can be implemented. As such, this is not a bug, and can be closed.
