### ISSUE TITLE
Morale "Misdirection" works against any damage.

### ISSUE THREAD

**Issue by Lileldys** [WarEmu/WarBugs#4819]
This skill is only meant to work against magic damage, but currently works against any damage recieved, as shown in the screenshots

![heyguys_003](https://cloud.githubusercontent.com/assets/13259775/13603315/451a5432-e534-11e5-8955-ccef31d38e76.jpg)
![heyguys_004](https://cloud.githubusercontent.com/assets/13259775/13603316/45e8015c-e534-11e5-90bf-f83deb384440.jpg)

**Comment by Evildoor** [comment]
Tooltip disagrees. "A strong counter aura will reduce by half any incoming Magic damage and redirect half of ANY DIRECT DAMAGE back to the caster."

**Comment by Lileldys** [comment]
![heyguys_005](https://cloud.githubusercontent.com/assets/13259775/13603551/fa66619a-e535-11e5-855f-473df8a6aa41.jpg)
