### ISSUE TITLE
Wrong influence rewards (Witch Elf, Blackguard, Sorc)

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#4820]
As I did a list of wrong influence rewards for magus earlier, this is a list of wrong influence rewards for the dark elf classes.

Chaos Chapter 1
    - Elite reward: Ravenscribed Chalice (dok chalice)
    *Affected classes: Witch Elf, Blackguard, Sorc

Greenskin Chapter 1
    - Elite reward: Recroot Symbol (dok chalice)
    *Affected classes: Witch Elf, Blackguard, Sorc

Chaos Chapter 2
    - Elite reward: Symbol of the Passage (dok chalice)
    *Affected classes: Witch Elf, Blackguard, Sorc
Chaos Chapter 3
    - Elite reward: Plundered Symbol (dok chalice)
    *Affected classes: Witch Elf, Blackguard, Sorc
Dark Elf Chapter 3
    - Elite reward: Phial of Trammels (dok chalice)
    *Affected classes: Witch Elf, Blackguard, Sorc

Dark Elf Chapter 4
    - Advanced reward: Denrazer's Phial (dok chalice)
    *Affected classes: Witch Elf, Blackguard, Sorc

Chaos Chapter 5
    - Elite reward: Only one item where other classes have two
    *Affected classes: Sorc

Dark Elf Chapter 6
    - Advanced reward: Necrolith Phial (dok chalice)
    *Affected classes: Witch Elf, Blackguard, Sorc

Dark Elf Chapter 7
    - Basic reward: No basic rewards
    *Affected classes: Witch Elf, Blackguard, Sorc

Chaos Chapter 8
    - Basic reward: No basic rewards
    *Affected classes: Witch Elf, Blackguard, Sorc

Dark Elf Chapter 8
    - Advanced reward: Coaxer Symbol (dok chalice)
    *Affected classes: Witch Elf, Blackguard, Sorc

Greenskin Chapter 8
    - Basic reward: No basic rewards
    *Affected classes: Witch Elf, Blackguard, Sorc

Chaos Chapter 9
    - Elite reward: Blightstone Chalice (dok chalice)
    *Affected classes: Witch Elf, Blackguard, Sorc

Greenskin Chapter 9
    - Elite reward: Sea Stunty Symbol (dok chalice)
    *Affected classes: Witch Elf
    - Elite reward: Sea Stunty Obscura Ring (ring with toughness and wounds should be only for blackguard)
    *Affected classes: Witch Elf, Sorc

Chaos Chapter 10
    - Basic reward: No basic rewards
    *Affected classes: Witch Elf, Blackguard, Sorc

Greenskin Chapter 10
    - Basic reward: No basic rewards
    *Affected classes: Witch Elf, Blackguard, Sorc
    - Elite reward: Symbol of da Miner (dok chalice)
    *Affected classes: Witch Elf, Blackguard, Sorc

Dark Elf Chapter 11
    - Basic reward: No basic rewards
    *Affected classes: Witch Elf, Blackguard, Sorc

Greenskin Chapter 11
    - Elite reward: Mutant Exile Symbol (dok chalice)
    *Affected classes: Witch Elf, Blackguard, Sorc

Chaos Chapter 12
    - Elite reward: Calyx of Insanity (dok chalice)
    *Affected classes: Witch Elf, Blackguard, Sorc

Greenskin Chapter 12
    - Elite reward: Goblin Rebel Symbol (dok chalice)
    *Affected classes: Witch Elf, Blackguard, Sorc

Greenskin Chapter 13
    - Elite reward: Priesterstadt Phial (dok chalice)
    *Affected classes: Witch Elf, Blackguard, Sorc

Chaos Chapter 14
    - Basic reward: No basic rewards
    *Affected classes: Witch Elf, Blackguard, Sorc

Dark Elf Chapter 14
    - Elite reward: Phial of Statecraft (dok chalice)
    *Affected classes: Witch Elf, Blackguard, Sorc

Greenskin Chapter 14
    - Basic reward: No basic rewards
    *Affected classes: Witch Elf, Blackguard, Sorc
    - Elite reward: Phial of da Plague (dok chalice)
    *Affected classes: Witch Elf, Blackguard, Sorc
    - Elite reward: Obscura Ring of da Plague (strength and toughness ring should be only for blackguard)
    *Affected classes: Witch Elf, Sorc

Dark Elf RvR T3
    - Advanced reward: Has only 3 options for cloaks where most other classes have 4.
    *Affected classes: Blackguard

**Comment by Ryanfawkez** [comment]
Fixed the chalices and rings. Rest of the missing items will be added eventually.

**Comment by NorKalli** [comment]
All of these have been fixed a long time ago
