### ISSUE TITLE
Wrong influence rewards (Shaman, Squig Herder)

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#4821]
This list is not as long as the former ones about magus and witch elf rewards but there are some missing influence rewards for shaman.

Chaos Chapter 3
    - Elite reward: Only one item where other classes have two
    *Affected classes: Squig Herder

Dark Elf Chapter 5
    - Elite reward: Only one item where other classes have two
    *Affected classes: Shaman

Dark Elf Chapter 7
    - Basic reward: Has no basic rewards
    *Affected classes: Shaman, Squig Herder

Chaos Chapter 8
    - Basic reward: No basic rewards
    *Affected classes: Shaman, Squig Herder

Greenskin Chapter 8
    - Basic reward: No basic rewards
    *Affected classes: Shaman, Squig Herder

Greenskin Chapter 9
    - Elite reward: Sea Stunty Obscura Ring (toughness and wounds ring that should only be for blackguard)
    *Affected classes: Shaman, Squig Herder

Chaos Chapter 10
    - Basic reward: No basic rewards
    *Affected classes: Shaman, Squig Herder

Greenskin Chapter 10
    - Basic reward: No basic rewards
    *Affected classes: Shaman, Squig Herder

Dark Elf Chapter 11
    - Basic reward: No basic rewards
    *Affected classes: Shaman, Squig Herder

Chaos Chapter 14
    - Basic reward: No basic rewards
    *Affected classes: Shaman, Squig Herder

Greenskin Chapter 14
    - Basic reward: No basic rewards
    *Affected classes: Shaman, Squig Herder
    - Elite reward: Obscura Ring of da Plague (strength and toughness ring that should be only for blackguard)
    *Affected classes: Shaman, Squig Herder

Dark Elf RvR T3
    - Advanced reward: Has only 3 options for cloaks where other classes I have looked at have 4 options.
    *Affected classes: Shaman

**Comment by Ryanfawkez** [comment]
Fixed the reward items at least, assigned class to the mentioned rings for Greenskin chapter 9 and 14. Implementing extra rewards is a tougher challenge, as is adding in missing items.
