### ISSUE TITLE
Jewe cannot equiped

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#4822]
I got this from PQ in Troll Country through white bag.Cannot equip**(red Accessory)**.
![toufekiaaaa_008](https://cloud.githubusercontent.com/assets/16864486/13611351/ce9cecb6-e56a-11e5-8ea8-9b3065ad1da6.jpg)

**Comment by DanaBloodkiss** [comment]
What should be the correct amount?
