### ISSUE TITLE
Zealot buffs freezes frame

### ISSUE THREAD

**Issue by Blubberino** [WarEmu/WarBugs#4824]
Since the last patch you cause the allie to have a quick freeze frame if you buff them with a zealot buff. This bug occured on live also but got removed once.

**Comment by ozarmidrashim** [comment]
The packet we send for this appears in the logs. Nothing I can do.

**Comment by Blubberino** [comment]
Since this bug only occures when you are buffed with it the first time couldn't it be possible to fix this issue with a permanent placeholder (something just like the zealot buff just without an effect)
