### ISSUE TITLE
the game change my team

### ISSUE THREAD

**Issue by pelhan** [WarEmu/WarBugs#4826]
Changelog after 6th March 2016, entering the black guard the shield achieved in the epic mission of empire changed me to the same but the Chosen, that if the player XD linked, so appearance only serves me.
I appreciate what it repaired
thanks

**Comment by Torquemadra** [comment]
the appearance changed?

**Comment by pelhan** [comment]
yes,appearance Chosen shield stayed, but did not have any shield equipped when logs in

**Comment by Torquemadra** [comment]
can you give me precise name of shield

**Comment by pelhan** [comment]
The black guard not because it aims, but "appeared" the Chosen is shield of change.
I imagine that the same call

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format. 

You can help us by following these bugreport rules: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
