### ISSUE TITLE
[TOK] BO guards in T3 counting towards PvP kills.

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#4828]
I just noticed I was getting kills for "Disciple of Khaine" from T3 elf BO guards, doesn't seem correct.

**Comment by Torquemadra** [comment]
which mission was counting the kills?

**Comment by gittoaster** [comment]
I am referring to the ToK Beastiary section..
For example "Ghrond's Sacristy Death Mistress" count towards DoK here..
I think it is deathblows only...
[img]http://s27.postimg.org/4xhvk9olr/tok.jpg[/img]

**Comment by gittoaster** [comment]
There is also the similar related unlocks such as being killed by x(class type) for each individual classes.  I didn't find any other related bug reports yet but i thought i remember seeing some..
http://postimg.org/image/7c4m7zxd3/

**Comment by gittoaster** [comment]
I noticed that this was fixed for T4 so I am assuming it's fixed for all tiers, closing.

**Comment by gittoaster** [comment]
T3 for Order still not correct.  "Ghronds Sacristy Beastgaurd" is counting as DoK kill.  Should be category "Dark Elf"
T4 - Objective Guards in used in Praag are counting to Zealot kills, should be "Chaos" insead.

**Comment by wargrimnir** [comment]
Guards no longer count as any sort of kills.
