### ISSUE TITLE
Banning a guild leader makes the guild defunct

### ISSUE THREAD

**Issue by magicthighs** [WarEmu/WarBugs#4830]
Right now, when a guild leader is banned, it can render their guild defunct. Unless specific permissions have been set, nobody can invite guild members, promote people, or join an alliance.

I propose that guild leadership is passed after a certain amount of time if the guild leader hasn't logged on. On retail servers, guild ownership would pass to the first person to log on after a certain amount of time. I know this for certain, because I had three guilds all to myself near the end of the game, all gained through this mechanism.

**Comment by MaxHayman** [comment]
This should happen already.

**Comment by sioding** [comment]
Thats fine - no need to look at it. Close.
