### ISSUE TITLE
[Scenarios] Highpass Cemetary capture points

### ISSUE THREAD

**Issue by Vandorkholme** [WarEmu/WarBugs#4832]
Was supposed to have been fixed #4629 
http://i.imgur.com/ZXai3UW.jpg

**Comment by Torquemadra** [comment]
lets try again.... 

fixed next patch

**Comment by Evildoor** [comment]
If the problem is exactly the same, why not comment the existing ticket instead of creating new one?

**Comment by Vandorkholme** [comment]
Didn't think you guys looked at closed tickets

**Comment by Evildoor** [comment]
Rules of the bugtracker...
