### ISSUE TITLE
Problem at "glory of Ulthuan" quest (High Elves, T2, Ellyrion)

### ISSUE THREAD

**Issue by Milord9** [WarEmu/WarBugs#4833]
At the camp of Reaverspring (south of Ellyrion), the NOC Melaina Blesswing gives us the quest "glory of Ulthuan" : we have to collect flowers. If there are no problem to get wildbrushes and Valeflower, it looks like there is a bug with the starwillow root, we can't right-click on it.
However I've been able to complete the quest by right-clicking on another flower in the same area (I don't remember the name, star... something) and it has validated my quest.

![arenia_002](https://cloud.githubusercontent.com/assets/17692456/13624945/ee65ccc8-e5b2-11e5-92e5-3903f132c325.jpg)

**Comment by Evildoor** [comment]
#4245

**Comment by sioding** [comment]
referenced report shows more problems with that quest.

**Comment by sioding** [comment]
Fixed with patch from 2.2.2018
