### ISSUE TITLE
White lion (the pet and the warrior)

### ISSUE THREAD

**Issue by Milord9** [WarEmu/WarBugs#4834]
I've found this in the shattered beach (North of Chrace, High Elves, T2). This bugs appears in all the Yenlui area : this is supposed to be a mob wild white lion (the animal) but instead we have a white lion (the guy). When dead, he doesn't disappear but just stay there, inactive and a message appears in the chat.
![saphery_001](https://cloud.githubusercontent.com/assets/17692456/13625020/c9c6f1e8-e5b3-11e5-9901-4f77665fc355.jpg)

**Comment by Torquemadra** [comment]
fixed next
