### ISSUE TITLE
Rank 9 jewelry Flameguard's Feeble Mark has 82 armor

### ISSUE THREAD

**Issue by magicthighs** [WarEmu/WarBugs#4837]
Got it from a PQ bag in Troll Country, either from Slayer's Demise or Plague Trolls.

![verdammt_018](https://cloud.githubusercontent.com/assets/6838946/13636180/c28ed696-e600-11e5-96c3-d0c0a1cb4734.jpg)

**Comment by Evildoor** [comment]
Same item as in #4822, but the problem is different, so not closing this.

**Comment by wargrimnir** [comment]
Removed armor and Skill requirement.
