### ISSUE TITLE
Dark Xiphos of Change

### ISSUE THREAD

**Issue by balgax** [WarEmu/WarBugs#4838]
Item is not usable. It is the third weapon choice of the quest chain in chaos

![xiphos](https://cloud.githubusercontent.com/assets/16364042/13636493/868ef85e-e602-11e5-847c-c30d39a9894a.jpg)

Error Message in Chat:
![error](https://cloud.githubusercontent.com/assets/16364042/13636495/891de59e-e602-11e5-84ba-2708d2c0e89b.jpg)

**Comment by Evildoor** [comment]
#4788
