### ISSUE TITLE
Fighter's Sledge of Conquest for WP have Destro banner appearance...

### ISSUE THREAD

**Issue by secikesa** [WarEmu/WarBugs#4839]
Fighter's Sledge of Conquest for WP have Destro banner appearance.... Found him slotted in my Trophy slot on character window, and since then have proportions of gigantic Destro banner with cow skull on it :)

**Comment by DanaBloodkiss** [comment]
Seems correct in the database.

**Comment by Evildoor** [comment]
No response, closing.
