### ISSUE TITLE
Bound items are not flagged boundToPlayer

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#4842]
Items that are bound to the player do not have the boundToPlayer=true flag. This is breaking some addons (e.g. ClosetGoblin). I already modified the addons but it would be better to have a proper implementation server side so everyone can use them again.

Currently all items are flagged boundToPlayer=false.

**Comment by Lheana** [comment]
Is this still an issue @taccr ?

**Comment by Kaelang** [comment]
Closed - no further information.
