### ISSUE TITLE
Bugs on quest rewards : some items can't be chosen (Ulthuan)

### ISSUE THREAD

**Issue by Milord9** [WarEmu/WarBugs#4844]
Accross the high elves territories, everytime that we can choose a talisman as reward of a quest, the second line cannot be selected, it just send me back to the previous dialog/quest description page. Only the first line (beside "choose 1") can be selected. 
![saphery_002](https://cloud.githubusercontent.com/assets/17692456/13648307/3c8d2ad8-e638-11e5-8355-1e1c9cd4c33b.jpg)

**Comment by Evildoor** [comment]
Again, this bug was there since forever (rewards after the first 4 cannot be chosen) and is not limited to elven quests.

**Comment by Evildoor** [comment]
#4030 will be used as a report for this problem.
