### ISSUE TITLE
bugged NPC "Aethyr assistant" (Shadowland, high elves T2, Skyblade's hold)

### ISSUE THREAD

**Issue by Milord9** [WarEmu/WarBugs#4845]
I know this is war time and the order is looking for cheap workforce, but common : the invisible man as an assistant.... :)
He is in Liradean Swiftarm tent. We can only see the hammer moving.
![saphery_003](https://cloud.githubusercontent.com/assets/17692456/13648461/fe7a2a4c-e638-11e5-8943-cec881719563.jpg)

**Comment by Torquemadra** [comment]
Aethyr assistant is a spiritual assistant as indicated by the word "Aethyr". This is how it should be.
