### ISSUE TITLE
Quest "abandonned" even if it is completed (Ulthuan)

### ISSUE THREAD

**Issue by Milord9** [WarEmu/WarBugs#4846]
Recurent bug with reknown quests that I've found in Ulthuan : when it is complete and we talk to the NPC to finish it, I first receive the message "[name of the quest] abandoned" and then "You have received an influence reward".
It should be just a text problem, as the quest disappear from our quest agenda and we do receive the reward

**Comment by Milord9** [comment]
Sorry, I forgot the picture
![saphery_005](https://cloud.githubusercontent.com/assets/17692456/13648618/e0cdef82-e639-11e5-9770-231b2f8557e8.jpg)

**Comment by Evildoor** [comment]
Happens since T1 and has nothing to do with Ulthuan. #1573 is related.

**Comment by Lheana** [comment]
This has been fixed.
