### ISSUE TITLE
Shadow Warrior auto attack.

### ISSUE THREAD

**Issue by Mc-ribs** [WarEmu/WarBugs#485]
Whenever I select a target with left click, my toon will start firing her autoattack, stopping me from prepping up/firing my starting move.

**Comment by Siegureboy** [comment]
Yes, I have this issue as well. I don't mind having to hit the button on my hotbar for AA to be on/off, but I do not see any difference in the AA icon on the hotbar; therefore I have a harder time determining if it is on or off. Maybe just fade it/tint it? It used to be shiny-ish (hard to explain) when AA was on.
