### ISSUE TITLE
zealot Daemon Spittle 

### ISSUE THREAD

**Issue by Kweedko** [WarEmu/WarBugs#4852]
Daemon Spittle don't hits on landing like on off server or like a Flame Breath on BW

**Comment by ozarmidrashim** [comment]
Proof.

**Comment by Kweedko** [comment]
this 
![leapingtoad_001](https://cloud.githubusercontent.com/assets/13465031/13675487/b4adeb94-e703-11e5-93c1-a894ee9a3ed1.jpg)

or what you mean proof?

**Comment by ozarmidrashim** [comment]
I want proof that Demon Spittle hit on application on the live server.

**Comment by Kweedko** [comment]
what you want me to ask EA to reanimate WAR? or what? ok just look 
http://www.youtube.com/watch?v=cmVj7Ps1j_s 1:34 zeal using it and it hits on application

**Comment by Kweedko** [comment]
so that was proof you asked why still  
https://github.com/WarEmu/WarBugs/labels/Confirmation%20Request

**Comment by ozarmidrashim** [comment]
Patience. Thanks.

**Comment by Kweedko** [comment]
thank you
