### ISSUE TITLE
destro quest: destruction of the weak

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#4853]
quest is stuck at phase 1: champion Tonas Jorgen lies dead but the system seems not aware of it.

**Comment by joneswaronline** [comment]
This problem still continues

**Comment by Damiel126** [comment]
Here's Tonas Jorgen killed by Raven Thralls.
![okshunz_006](https://cloud.githubusercontent.com/assets/10399547/16007726/8af7fd40-31b7-11e6-98cf-196385370deb.jpg)

**Comment by joneswaronline** [comment]
Great pic, thanks for adding that. This issue is also mentioned in #6253 and #4862 and #4909

**Comment by wargrimnir** [comment]
Should be fixed.
