### ISSUE TITLE
Can't turn in T3 quests "Gears of WAR" or "Defend Passwatch Castle"

### ISSUE THREAD

**Issue by tomaslumba** [WarEmu/WarBugs#4855]
Hiya, since last night I can't turn in the quests "Gears of WAR" or "Defend Passwatch Castle". The NPC shows the yellow badge but nothing happens when  press "Complete" except for the dialoge ending.

I can turn in other kill quests.

Toon in lvl 27

Kind regards

**Comment by Torquemadra** [comment]
did you read the actual requirements within your quest log and verified that you had completed them?

**Comment by tomaslumba** [comment]
Yes, the quests are completed in ToK and the NPCs badge is yellow and they they don't ingore me like NPCs do when you havent completed the quest yet.

**Comment by tomaslumba** [comment]
Hiya, not sure if you did anything but today I could turn in the quests. Kind regards!

**Comment by Torquemadra** [comment]
Theres a display issue with some quests showing a orange circle when requirements ahve not been completed. It could have been this.

**Comment by tomaslumba** [comment]
Nope wasn't that. I didn't do any more rvr/pve on that toon, simply logged out and tried again the following day - and two days later it worked. 

Thx for your time mates 😊
