### ISSUE TITLE
Sent alot of purple fragments by mailbox, but receiver didn't received mail!

### ISSUE THREAD

**Issue by Darki77** [WarEmu/WarBugs#4856]
So, either my other toon just didnt received the mailbox for some reason... Or i spelled Joeic instead of Joiec..... What i really doubt, but it could be. Still, i sent really alot of fragments, purple ones, that i farmed for hours and hours. there's any way to help me getting my mail back???????? Or anything you can do to resolve this strange case?

**Comment by Evildoor** [comment]
Read the rules of the bugtracker.
