### ISSUE TITLE
bad cages for bad prisoners 

### ISSUE THREAD

**Issue by Milord9** [WarEmu/WarBugs#4857]
As far as I was able to see, everytime there is an area with prisoners, it is a mess : prisoners go out of their cage to attack enemies. After the fight they try to go back to their jail and finish above it.

I guess this issue already exist in the bug tracker, but I've been unable to find it ("prisoners" and "cage" give no result with the search tool).

![lothern_001](https://cloud.githubusercontent.com/assets/17692456/13692535/95ab6eda-e742-11e5-9773-b11da54f26d6.jpg)

**Comment by Lheana** [comment]
They are now correctly inside their cages.
