### ISSUE TITLE
Two bugged dark elves guards in Ellyrion

### ISSUE THREAD

**Issue by Milord9** [WarEmu/WarBugs#4858]
South of the Shady tower (Ellyrion, High elves), there is an Ellyrian prisoner obviously guarded by two dark elves. Those two guys can be selected, but we can't attack them, as well as they dont attack you if you're around.

![lothern_003](https://cloud.githubusercontent.com/assets/17692456/13692701/1161ed00-e744-11e5-8ecd-b13747a6ff30.jpg)

**Comment by Milord9** [comment]
Apologies, I've dowload the wrong screenshot !

Here is the right one : 

![lothern_002](https://cloud.githubusercontent.com/assets/17692456/13692726/4d29448c-e744-11e5-8d19-73e728aec1b1.jpg)

**Comment by DanaBloodkiss** [comment]
Coordinates please. There are 200 spawns of them and I can't find the correct location.

**Comment by Milord9** [comment]
51180-58978

![lothern_030](https://cloud.githubusercontent.com/assets/17692456/14936665/b0d8cff4-0ef2-11e6-8cda-4a6afa77defb.jpg)

**Comment by DanaBloodkiss** [comment]
Thank you fixed in next patch.
