### ISSUE TITLE
Double kill in "Control" quest (Avelorn, High elves)

### ISSUE THREAD

**Issue by Milord9** [WarEmu/WarBugs#4859]
For this quest, we have to kill i guess 10 bloody sun treechopa orc, but the quest instead tell us to kill one then nine of them. Actually, when we kill the first orc, it is added for the first line (1/1) and the second line (1/9), no problem for the rest of the quest.

![lothern_004](https://cloud.githubusercontent.com/assets/17692456/13692886/1c589fbe-e745-11e5-91fa-dfdfa7cf961f.jpg)

**Comment by sioding** [comment]
Works fine. No double kill order in quest.
