### ISSUE TITLE
mount speed bug

### ISSUE THREAD

**Issue by grsapoun** [WarEmu/WarBugs#4860]
Hello,
I' ve notice that when you fell in water while you are mounted and you dimount, you still have the speed as if you are mounted when u get out of water.

**Comment by Soulwhisper** [comment]
I think its intented...not a bug.

**Comment by grsapoun** [comment]
running on feet the same speed as mounted?

**Comment by Soulwhisper** [comment]
Yes.Its intented to not get dismounted while you are in water.**Not sure though.**

**Comment by Evildoor** [comment]
#798
