### ISSUE TITLE
Squig Squeal Ability is not working

### ISSUE THREAD

**Issue by ManBearSquig** [WarEmu/WarBugs#4861]
The Taunt ability for the Squig Herders Basic Squig Squig Squeal does not taunt the enemy, I am unsure if the taunted target takes extra damage from the squigs attacks.

**Comment by Evildoor** [comment]
If by "taunt" you mean "force monsters to attack" then #2770.

> I am unsure if the taunted target takes extra damage from the squigs attacks

Test it then.

**Comment by Evildoor** [comment]
No response, closing.
