### ISSUE TITLE
ToK unlock kill 1000 Dark Elves rewards: The History of the Dark Elfs

### ISSUE THREAD

**Issue by Reggaewaldo** [WarEmu/WarBugs#4863]
Killing 1000 Dark elfs rewards incorrect ToK unlock, see screenshot.

![image](https://cloud.githubusercontent.com/assets/13517919/13705348/b453687a-e7a0-11e5-9f4d-e32edafce670.png)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
