### ISSUE TITLE
Vulture Bolt Throwers

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#4865]
The Repeater Bolt Throwers in The Blighted Isle near Dark Elf chapter 2, that are also part of a quest where you have to destroy/kill them, are apparantly counted as vultures. I got a tome unlock that said I had encountered a vulture when destroying the first bolt thrower.
While the bolt throwers are seen as vultures in the game, the Carrion Seeker Vultures just east of Chaos chapter 2 do not count as vultures for some reason.

**Comment by DanaBloodkiss** [comment]
Fixed in next patch.
