### ISSUE TITLE
Order T3 WC is accesible by Destro

### ISSUE THREAD

**Issue by Ghostweed** [WarEmu/WarBugs#4866]
I can get into the Order T3 Empire WC find a sweetspot and kill stunties and NPCs. There was a guard for 1 day after i farmed several ppl who probably complained about it to GM, but next day the guard was gone. If Devs or GMs are interested I can show u how to get in and where is the sweetspot.

**Comment by Torquemadra** [comment]
can you pm me with it on forums please
