### ISSUE TITLE
r34 bloody sun choppas in dwarf chapter 2

### ISSUE THREAD

**Issue by magicthighs** [WarEmu/WarBugs#4867]
R34 Choppas spawning right on top of identically named R4 ones.

SpawnId=935256,Entry=635,Name=Bloody Sun Choppa,Level=34,Rank=0,Max Health=3570,Faction=129,Emote=0AI:STANDING,Position :(OffX = 191, OffY = 212,Heading = 3925, Oid = 19789, Name= Bloody Sun Choppa)(46096, 25935, 7100)

SpawnId=340627,Entry=635,Name=Bloody Sun Choppa,Level=4,Rank=0,Max Health=420,Faction=129,Emote=7AI:STANDING,Position :(OffX = 191, OffY = 212,Heading = 3925, Oid = 19775, Name= Bloody Sun Choppa)(46096, 25935, 7100)

**Comment by Soulwhisper** [comment]
#4569 It should be fixed.Can someone confirm?

**Comment by Torquemadra** [comment]
these are not fixed on dev, seem tied to PQ spawn cycle
