### ISSUE TITLE
[Quest] Dangerous Assumptions

### ISSUE THREAD

**Issue by Gakvar** [WarEmu/WarBugs#4871]
This quest starts in Trovolek, asks that you kill and collect something around the Plaguewood Thicket public quest and then bring the stuff you collected to an object called Plagueood Oak found in the same PQ area. After completing this stage there is nowhere to turn it, no NPCs in Trovolek or Trollhaugen and the quest text suggests it should continue from the tree itself. but it's impossible to continue. In other similar quests that continue from objects, I've noticed they instead continue from the original NPC quest giver, not in this case though.

**Comment by DanaBloodkiss** [comment]
Should work in next. Display of the starter and finisher in 3 steps. 

1. Vhorek Bloodfist -> Rorrim Rotscale
2. Rorrim Rotscale -> Rorrim Rotscale
3. Rorrim Rotscale -> Vhorek Bloodfist

**Comment by poutpoutt** [comment]
For the second part of the quest, the description and the objectives do not match : in the text, it says you have to get bitter root, moss from the "moss covered stone", blood from the injured warrior and then oint the oak but in the quest objectives, you do not have the moss part.

Also, the injured warrior is getting killed buy the surrounding trolls.
