### ISSUE TITLE
Leather Mask of the Gobbo

### ISSUE THREAD

**Issue by alxxqp** [WarEmu/WarBugs#4874]
http://i.imgur.com/nlAbQQi.jpg

Stopped working as an alternate appearance item, even though it says it can be used as such. It still works when you just put it on.

**Comment by DanaBloodkiss** [comment]
The item should not exist ingame. Where you got it from?

**Comment by alxxqp** [comment]
Someone sold it on the auction for 300g

2016-03-12 12:36 GMT+02:00 DanaBloodkiss <notifications@github.com>:

**Comment by Ryanfawkez** [comment]
Came from a bugged droptable before the new loot system was introduced. Reason it cannot be used for appearance is because it has no armor type assigned.

**Comment by alxxqp** [comment]
Thats not true, I used it as appearance for ~3 months. But thanks for not
letting me have it and loosing my gold again, though.

2016-03-12 15:42 GMT+02:00 Ryan Fawkez <notifications@github.com>:

**Comment by Ryanfawkez** [comment]
Yeah, it was changed so that you personally wouldn't be able to use an overpriced, bugged item. No problem.
