### ISSUE TITLE
Steeled for Slaughter

### ISSUE THREAD

**Issue by Yvislar** [WarEmu/WarBugs#4875]
the quest Steel for Slaughter in BFP this quest is repeatable on my WH but not my IB I don't even recall being able to pick up the quest i've looked around for the pick up quest to talk to Kaz but i'm unable to find it or possibly my quest log was full when this happened and is now lock in neverland.

**Comment by DanaBloodkiss** [comment]
Cannot find this questname in the DB.

**Comment by Evildoor** [comment]
I guess it's 'Steeled for Slaughter'.

**Comment by Yvislar** [comment]
Yes I'll apologize the quest giver is Kazgrim Thorlunson in the badlands and I met Steeled for Slaughter.

**Comment by Ryanfawkez** [comment]
Needs every character in the database to have his quest flag as "completed" removed, since this quest has been made repeatable again. Those who handed in the quest when it became unrepeatable, cannot get it again until then.

**Comment by Yvislar** [comment]
Is this ticket still being worked on?
