### ISSUE TITLE
Stoutness of Stone Tactic seems to effect all CC

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#4877]
It should only affect stuns and kd's but our tank snares last 5s on some IBs(Dwarfs - it's a racial tactic). Pretty sure it's this tactic what's causing it.

**Comment by taccr** [comment]
Nvm. Tactic is seen it all before. Just so rarely used that I forgot about it.

**Comment by gittoaster** [comment]
It appears it is happening vs Dispel.
