### ISSUE TITLE
ToK: Trinkets for Treasure 

### ISSUE THREAD

**Issue by Reggaewaldo** [WarEmu/WarBugs#4879]
When selling the item to vendor it does not give you the unlock.

http://warhammeronline.wikia.com/wiki/Trinkets_for_Treasure

Also drop chance seems way to high.

![image](https://cloud.githubusercontent.com/assets/13517919/13721464/8728f044-e828-11e5-96a0-b40bda7062fb.png)

**Comment by DanaBloodkiss** [comment]
No option for unlocks like this now.

**Comment by Lheana** [comment]
Fixable now ?

**Comment by Ryanfawkez** [comment]
Nein.
