### ISSUE TITLE
Goblin/orc Bloody Sun Boys

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#4882]
Several Bloody Sun Boy orcs are bugged near the Greenskin starter area in Mount Bloodhorn. Only the orcs are bugged, not the goblins with the same name.
![gobboorc](https://cloud.githubusercontent.com/assets/16590792/13722451/9f23b166-e846-11e5-8049-35d50a85135b.jpg)

**Comment by DanaBloodkiss** [comment]
I removed the orc model and replaced it with the goblin one for now.
