### ISSUE TITLE
devastator item only tradeable via Auction House

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#4883]
not sure if intended, but devastator gloves and shoes (and prbly duelist) cant be mailed or traded directly.

**Comment by Evildoor** [comment]
#4763

**Comment by Tiggonos** [comment]
im confused so its intended it isnt tradeable via mail/direct ??

**Comment by Evildoor** [comment]
Note to self - delete these two comments since question was answered in #4763.
