### ISSUE TITLE
Cannon Smasha quest

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#4884]
The cannons on top of the dam in Greenskin starter area (Mount Bloodhorn) can not be destroyed for the quest Cannon Smasha. This is the area where you are supposed to "fly" to when interacting with one of the Bloody Sun Lobber in the quest Lob it Good. Though this feature is not working, it is still possible to run to the area where this quest is handed out (and several other quests that seem to work just fine, despite their location).
![quest](https://cloud.githubusercontent.com/assets/16590792/13722600/6443c928-e84b-11e5-80a2-51629f662ecf.jpg)

**Comment by Ryanfawkez** [comment]
Issue is related to these cannons being gameobjects, would have to convert them to NPCs to make them killable AND count towards the quest.

**Comment by Meralors** [comment]
Changed Ironmane Cannon to NPC, They can now be killed and complete quest step.
