### ISSUE TITLE
Memorial Plaque = Kill 1000 Dragons

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#4885]
While I was exploring on top of the dam near det Greenskin starter area I found this Memorial Plaque on one of the walls. When interacting with it I got the "Kill 1,000 Dragons" tome unlock.
![plaque](https://cloud.githubusercontent.com/assets/16590792/13722684/1317bf3e-e84e-11e5-843c-90c797bafb15.jpg)
![dragon](https://cloud.githubusercontent.com/assets/16590792/13722688/29ff6cb0-e84e-11e5-8097-f2258bb175fa.jpg)

**Comment by Ryanfawkez** [comment]
Already fixed in the next patch.
