### ISSUE TITLE
Dok bug appearance

### ISSUE THREAD

**Issue by Mortkin** [WarEmu/WarBugs#4887]
Dok's are using this armor to use the same look as sorc's

http://i.imgur.com/uEdqZuB.jpg

**Comment by Styrkarr** [comment]
Fixed in next patch.

**Comment by Mortkin** [comment]
you guys already fix it?

**Comment by Evildoor** [comment]
Main ROR page clearly says:

Changelog from 21.03.2016 (a bit late :P ).

[Addressed Tickets]

- [4887] Item: Fixed appearance for "Thick Quilted Vestments".
