### ISSUE TITLE
Unique scenario weapons

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#4888]
The following weapons have "unique" label, which means that you cannot equip two of them, which does not makes any sense since they are intended for dual wielding classes:
Sentry's Stikka of Brutality
Sentry's Chaosaxe of Brutality (this is Main Hand only, which is also wrong)
Sentry's Stiletto Of Brutality
Titan's Trollsmasher of Devotion
Sentry's Axe of Devotion (also Main Hand only)
The following weapons are also "unique", however, this does not affects gameplay much since they either cannot be dual-wielded or it's unlikely that someone will want to do so (for example, 2 healing swords on DoK). Still, i'm listing them because most of the scenario weapons are not "unique".
Sentry's Stabba of Brutality
Sentry's Sword of Brutality
Sentry's Painblade of Brutality
Apostle's Xiphos of Brutality
Sentry's Bigloppa of Brutality
Sentry's Deathaxe of Brutality
Sentry's Ninestaff of Brutality
Sentry's Glaive of Brutality
Sentry's Witchstaff of Brutality
Sentry's Blocka of Brutality
Sentry's Shoota of Brutality
Sentry's Herald of Brutality
Nihilist's Focus of Brutality
Sentry's Aspis of Brutality
Apostle's Chalice of Brutality
Sentry's Blocka of Cruelty
Sniper's Longbow of Merit
Sentry's Pavise of Merit
Sentry's Longbow of Merit
All order T2 weapons named "something's something of Devotion" (apart from 1 greatsword, 1 gun, and 2 slayer weapons mentioned above)

**Comment by Torquemadra** [comment]
fixing

**Comment by lilsabin** [comment]
where can i read the rules ?

**Comment by Evildoor** [comment]
http://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
