### ISSUE TITLE
Two quests are the same

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#4889]
I found two quests that are the same except for different names and different NPCs to return to. Brekin' Teef and Da Stick's Da Fing.
![breakin](https://cloud.githubusercontent.com/assets/16590792/13724128/6528a392-e87b-11e5-95ec-26146000c796.jpg)

![dastick](https://cloud.githubusercontent.com/assets/16590792/13724130/69e9cac8-e87b-11e5-8887-9afcfd9b4569.jpg)

**Comment by ElMosquito** [comment]
I also found out that, after going through all the stages of the quest lines, Da Stick's Da Fing has at least one more stage that can not be completed since it says you have to kill Krulloz da Kwik, which is a friendly mob. On the live server you got an item in your i nventory to use on him and thus making him attackable, but such items do not work here so perhaps changing him from ally to enemy or just interact with him to be able to finish the quest.

**Comment by Ryanfawkez** [comment]
Can't recover quest info for Breakin' Teef, will have to disable that quest. Meanwhile Da Stick's Da Fing's final stage will be fixed.

**Comment by Ryanfawkez** [comment]
Krulloz da Kwik will be neutral to both realms in the next patch.
