### ISSUE TITLE
goblin green dye can't stack

### ISSUE THREAD

**Issue by fizzibliz** [WarEmu/WarBugs#4890]
can stack goblin green dye with a green rarity,

Thanks for the good work keep it up!

Fizzi

**Comment by Ryanfawkez** [comment]
Two different IDs, would have to purge one of them from the item database.

**Comment by DanaBloodkiss** [comment]
Fixed in next patch.

**Comment by Ottogrim** [comment]
Problem is still here, i have three different stacks

**Comment by NorKalli** [comment]
fixed ages ago
