### ISSUE TITLE
Main stat not increasing past 200, when debolstered in T1 

### ISSUE THREAD

**Issue by kmelesh** [WarEmu/WarBugs#4899]
Going back to t1 to test debolstering and experince t1 again i noticed that my strength was not increasing past 200, which is unusual since my other normal t1 toons have strength values easily over 200.

 For example My character had a strength of 195, after slotting  +12 str ring it once again only rose to 200

**Comment by ozarmidrashim** [comment]
Paperdoll issue. The paperdoll will not be anywhere near reliable for debolstering.
