### ISSUE TITLE
"Ulfred" should have 2 PvE quests to accept

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#49]
The NPC Ulfred (who can be found next to the Raven Host Vanguard PQ), should have 2 Quests you can accept.

1. The quest called "Murder Wood" - Collect Beastmen Horns 0/10.

2. Participate in the PQ ( I can't find the name of that quest. It was a latter add on from the original).

Neither of these quests are available to accept.

![ulfred](https://cloud.githubusercontent.com/assets/7492543/2908443/cb07f7fc-d627-11e3-9462-12117cf6c2cc.png)

**Comment by milosxe** [comment]
I didn't find any other quest besides Murder Wood on the online resources concerning this NPC. And Murder Wood works fine. Closing.
