### ISSUE TITLE
minor Apothecary bug

### ISSUE THREAD

**Issue by fizzibliz** [WarEmu/WarBugs#4901]
I was farming my potions today and my apothecary got stuck a few times, vials were locked in but i couldn't add/remove any items nor create potions from my apothecary window, a relog solved it. This is not a big bug I guess (most old warhammer biugs were worse xD). I use motion to do my crafting.

Thank you for the hard work,

Fizzi

**Comment by Evildoor** [comment]
#1996?

**Comment by fizzibliz** [comment]
I ll do more potions and keep you posted if its the same bug

**Comment by fizzibliz** [comment]
yes same problem sorry
