### ISSUE TITLE
npc/pets killing enemies affecting public quests/causing them to be uncompletable

### ISSUE THREAD

**Issue by ragnarian** [WarEmu/WarBugs#4909]
i have noticed that if a pet/npc attacks an enemy (namely, bosses) the enemy wont count towards the quest completion, normally this isnt too troublesome since most enemies respawn, but for bosses, it does, tonas jorgen doesnt respawn, so if a pet attacks him, the public quest becomes uncompletable

**Comment by joneswaronline** [comment]
This problem is also mentioned in #6253 and #4862 and #4853 
Jorgen is dead next to an NPC that killed him and he won't re-spawn so the public quest is stuck.

**Comment by Lheana** [comment]
Works fine now afaik.
