### ISSUE TITLE
Item bug

### ISSUE THREAD

**Issue by Ktaan** [WarEmu/WarBugs#4910]
Echelon Horn of Brawn still can be equipped even though its Unique - Equipped item type

**Comment by Evildoor** [comment]
Have you got several of them equipped before the patch?

**Comment by taccr** [comment]
Some unique-equipped items are indeed still equippable.
Echolon Knot of Volition for example still allowed multiple equipped instances.

**Comment by Ktaan** [comment]
Evildoor, yes i got 3 of them equipped before patch (in jewerly slots 2,3,4) on my IB Ktaan

**Comment by Evildoor** [comment]
Unequip them all and try again.

**Comment by Ktaan** [comment]
Just checked- now i cant equip 2 of them at the same time. But right after the patch i was able to unequip and equip 2 of them. Guess its fixed. TY!
