### ISSUE TITLE
ch12 PQ inf bug

### ISSUE THREAD

**Issue by Gazzargh** [WarEmu/WarBugs#4911]
Hi, not sure if this was just me or is an issue, seems the ch12 PQs "areas" are out of whack, i wasn't getting any INF apart from standing between the 2 PQs together and shrine is being classified as ch11.  the only INF i could get was off the odd champ mob but even then they were sparse.

**Comment by wargrimnir** [comment]
Reports like this need to be more specific. Zones and PQ names. Will close this and work off other tickets as they're likely already resolved.
