### ISSUE TITLE
[Engineer] wrong weapons type

### ISSUE THREAD

**Issue by Morksezstop** [WarEmu/WarBugs#4913]
Some hammers for engi are with wrong descriptions. They are marked for main hand **or offhand**. Atm i see that with t1 sc hammers. you still can use them but need to manuially put them at the right slot

**Comment by Luth-RoR** [comment]
Dwarf hammers can be generally worn by all dwarf melee classes (even if it makes no sense stat-wise), which includes the slayer (dualwield).
