### ISSUE TITLE
AH sell tab 

### ISSUE THREAD

**Issue by AsleIB** [WarEmu/WarBugs#4914]
When i press the "sell" tab in the auctionhouse frame - it lists a huge list of active auctions (of which is not mine) and the option to press "cancel" is highlighted. So .. i have not tried of course - but i'm affraid the option for other people to cancel eachothers auctions is available?

![asle_001](https://cloud.githubusercontent.com/assets/17806005/13726624/19636fe0-e8d1-11e5-8af6-35fdb78be9c5.jpg)

Reggards 
Asle

**Comment by Evildoor** [comment]
#3904
