### ISSUE TITLE
Not getting T1 and T2 influence when de-bolstered

### ISSUE THREAD

**Issue by davidchicheung** [WarEmu/WarBugs#4915]
Not getting any T1 zones (possibly T2 as well) influence after being de-bolstered as a rank 35 character. Screenshots attached.
![meepie_003](https://cloud.githubusercontent.com/assets/699806/13727389/b05f1d5e-e8a4-11e5-861e-a8f52aa89a26.jpg)
![meepie_004](https://cloud.githubusercontent.com/assets/699806/13727388/b0596d50-e8a4-11e5-8e4a-38b1bb316abd.jpg)

**Comment by davidchicheung** [comment]
T2 not working as well.

**Comment by Luth-RoR** [comment]
Needs clarification if it only happens on BOs (working as intended) or generally (bug).
