### ISSUE TITLE
Quest: "Ignoble weapons" bugged (The Blighted Isle)

### ISSUE THREAD

**Issue by adreamtokill** [WarEmu/WarBugs#4916]
The reaper bolt throwers that you're suppose to destroy are unattackable. the sword icon shows when you point your mouse at them but when clicked they dont seem to have any health and any attack will be interuppted.

**Comment by Evildoor** [comment]
Maybe the same problem as #4884.

**Comment by Meralors** [comment]
Fixed siege weapon, you can now destroy them and complete quest.
Live next patch

**Comment by Kaliselia** [comment]
Okay I am having the same problem as the Return Fire quest for Empire in that you do not get credit for destroying the Reaper Bolt Thrower plus they are showing up as being level 10 and for a starting area that is quite high since it takes quite a while to destroy them.
