### ISSUE TITLE
Nordenwatch

### ISSUE THREAD

**Issue by Morksezstop** [WarEmu/WarBugs#4917]
This is not exacly bug but there is one spot where if u stuck there is no way to go out. So is it possible to remove this pole for the best? It is quite annoying since the only way to get out is the end of sc or just dying

<a href='http://postimg.org/image/xfpzwpasd/' target='_blank'><img src='http://s14.postimg.org/xfpzwpasd/nordenwatch.jpg' border='0' alt="nordenwatch" /></a>

**Comment by ozarmidrashim** [comment]
Nope. We can't.
