### ISSUE TITLE
dead when leaving SC

### ISSUE THREAD

**Issue by Natherul** [WarEmu/WarBugs#4922]
I died as I pressed leave SC and upon entering the "normal" world I was dead but with full HP unable to do anything, a /stuck got me back but but..... .P 
![phurnag_000](https://cloud.githubusercontent.com/assets/3688166/13730090/f899a9bc-e945-11e5-8479-e3dfaf4f5c2c.jpg)

**Comment by sioding** [comment]
**Thanks for the report.** Since there is no confirmation, i will close this issue now. Please make sure to follow the bugtracker rules which you can find here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)
