### ISSUE TITLE
Can't turn in T3 epic emp quest "Cleansing an empire"

### ISSUE THREAD

**Issue by tomaslumba** [WarEmu/WarBugs#4925]
Hiya, have same issue when it comes to turning in this quest as I had with two rvr quests the other day (reported them too - and they solved them selfs after two days) - can't turn it in the quest "Cleansing an empire". I have completed all the steps and killed the last boss. In ToK it says that quest is completed. When i talk to the NPC (who has the yellow badge over his head) I can choose my reward but then nothing happens... 

Can a server restart be the solotion? - ofc not saying you should restart on accound of this :) but i'll keep it in mind.

What to do?

Kind regards!

**Comment by Ryanfawkez** [comment]
Are you trying to select the 5th reward, on the second row? Those items cannot be chosen. Also, if so, what class are you trying to obtain your reward on?

**Comment by Torquemadra** [comment]
Are there 5 options? What class are you? Have you actually killed Eustasius Lang and it shows that objective crossed off in your questlog?

**Comment by tomaslumba** [comment]
Heya, i'm a WP and trying to claim the 1st reward, the 2h hammer. There are three options to choose from.
Yes, I've killed Eustasius Lang and it shows that objective is crossed off in my questlog.

**Comment by tomaslumba** [comment]
So I did the dwarf epic T3 quest now - Anciet Horrors - and guess waht - I did it and I can't claim the reward for that one either...
All completet i ToK...

Help :)

**Comment by tomaslumba** [comment]
![karlbartos_007](https://cloud.githubusercontent.com/assets/17112647/13755570/2edf5040-ea1c-11e5-8707-ac79860c8d16.jpg)

**Comment by Torquemadra** [comment]
Can you try after a server boot, we havent done one today

**Comment by tomaslumba** [comment]
Kk, will do, when do you think next reboot will be?
Killed the final boss one more time today, but didnt change anything.

**Comment by tomaslumba** [comment]
Got a new clue... seems like I can't turn in quest where I get to pick the reward... did the elf chap 10 quest "a cockatice nuisanse" and the reward is a dye or a talis- but i can't choose either. Same problem as with the other quests above.

**Comment by Torquemadra** [comment]
booted now.

**Comment by tomaslumba** [comment]
The server reboot solved the issue. I was able to turn in all quests and get the rewards :)

Thx mates - keep up the good work!
