### ISSUE TITLE
Set of Carnage

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#4934]
Now when some public quests work och give out gold loot bags it should be possible to get PvE armor sets, just like on the live server. I have checked one gold loot bag in t1 and it gave me the option to pick one piece of armor from the Set of Carnage. The problem is that the armor has no set bonus and is just a normal purple item but it still gave me a tome unlock for the Set of Carnage.
![carnage](https://cloud.githubusercontent.com/assets/16590792/13751138/0150a9a2-ea09-11e5-9170-92c4416bbc11.jpg)
![tokcarnage](https://cloud.githubusercontent.com/assets/16590792/13751141/060c054a-ea09-11e5-8a1a-6cbfa65e65bc.jpg)

**Comment by wargrimnir** [comment]
This appears to be correct.
