### ISSUE TITLE
Ghrond's Xiphos

### ISSUE THREAD

**Issue by Blubberino** [WarEmu/WarBugs#4935]
Looks like it's not salvagable but it should

![xyp](https://cloud.githubusercontent.com/assets/16993024/13753207/54d3ed9c-ea12-11e5-9700-112db36be626.PNG)

**Comment by Styrkarr** [comment]
Fixed in next patch.

**Comment by Blubberino** [comment]
Well nice, just tried to salvage that item you guys fixed but it happens to give a lvl 1 fragment instead an (150 fragment i think) higher one. Can you please fix that and revert my item because that fragment (well the major talisman of the aggressor) is about 100g worth which is quite annoying to loose because of an bug.
![valfaros_013](https://cloud.githubusercontent.com/assets/16993024/14031731/8bda4a26-f20e-11e5-93f0-d322df2bf834.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
