### ISSUE TITLE
Healing Bonus stacking in tactics group

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#4936]
Blessing of Grungni(1.25) is currently stacking with Focused Mending(1.15) resulting in a 1.4 bonus.

**Comment by Evildoor** [comment]
Is this wrong?

**Comment by Silentguard** [comment]
Both of this is tactic effect which never stacks on live and i hardly believe should never stack.

**Comment by Evildoor** [comment]
Closing since no clarification was provided. This stacking is correct according to @ozarmidrashim's comment to #1671, and if this was different on live then i'd like to see something more solid than "it never stacked on live" response from a single person.
