### ISSUE TITLE
[DOK] Rend Soul wrong DMG on Gun Turret's

### ISSUE THREAD

**Issue by Blubberino** [WarEmu/WarBugs#4937]
Rend Soul is only doing a fraction of it's dmg on turret's (I guess WL pets too but not tested) which is a serious problem. In fight gun turret's were always save targets to heal you up because they normally don't have ton of resistence and you can keep your aoe detaunt up while doing so.

![valfaros_009](https://cloud.githubusercontent.com/assets/16993024/13786309/4c2555bc-ead7-11e5-91b7-0ff8560eb1da.jpg)

Here in this case it did 70(+46)=116 while it should do 3x more than that.

**Comment by Blubberino** [comment]
Also since you will take a look a Rend Soul can you please check if there is a mistake which resistence effects this skill. Because even though it does the same kind of dmg (Spirit DMG) as Covenant of Vitality/Celerity it always is effected by migations way stronger.
![valfaros_010](https://cloud.githubusercontent.com/assets/16993024/13762506/b2fe7644-ea3f-11e5-91f9-0b02a5c323b2.jpg)

Here in this case 96% of the dmg from the pact hits the target while only 62% of Rend Soul arrives at the target which indicates that there are 2 different defensives who effect the skills which should not happen because both are spirit dmg or not?

**Comment by Silentguard** [comment]
Difference in mitigation based on str-tou absorbtion, in case with rend soul, ability has dmg scale stat but covenants dont. So cov of vitality mitigates only by resists while RS by tou and resists both.

**Comment by Evildoor** [comment]
Second question was answered by Silentguard.
First question - why are you talking about 70 + 46 (it's Covenant damage), Rend Soul is 130 + 106 = 236. Still not 303 (and should be more, since DPS DoKs with a bit of common sense use Divine Fury), but not so much difference. And in what situation this occured (for example, i see Challenge stuck on your effects panel)? Should be tested in clean conditions (1 vs 1, no tactics slotted, etc) before anything will be done here.

**Comment by Blubberino** [comment]
Yes sorry looks like I slipped there...happens if you try to report something late night^^

However I did check the skill again because the numbers still seemed to be off I started not on gun turret only normal npc's in IC without divine fury and discovered that the numbers actually are off. (Exept i did another mistake...)
![valfaros_011](https://cloud.githubusercontent.com/assets/16993024/13786406/b09373bc-ead7-11e5-82cb-3beda0605fce.jpg)

So as you can see the Dmg is at 234(+23)=257 and it actually should do 290 here.

**Comment by ozarmidrashim** [comment]
Skill was missing offhand contribution. Please try it again.

**Comment by Evildoor** [comment]
No response, i suppose this works fine now.

**Comment by Blubberino** [comment]
Sorry had a lot of things to do and didn't check bugtracker lately. Yes works perfectly fine now stats are correct with divine fury and without it. Thanks you guys.
