### ISSUE TITLE
[Sorc] HoR 

### ISSUE THREAD

**Issue by Artricks** [WarEmu/WarBugs#4939]
Hand of Ruin continues to channel after death, if u cast it right before ur hp gone.

**Comment by Evildoor** [comment]
Deals damage? Or just a visual effect? Screenshots of combat log, please.

**Comment by milosxe** [comment]
It was the case on live too. Same thing with Withering Heat

**Comment by bloodi** [comment]
Its tricky to pull off but it does happen, saw it once or twice on my BW

**Comment by Artricks** [comment]
Yes, it deals damage after death.
