### ISSUE TITLE
Crafting Ceiling

### ISSUE THREAD

**Issue by LittlefishSail** [WarEmu/WarBugs#4940]
I realize there is now a cap on gathering ingredients, but I can't find anywhere in the patch notes about a cap on crafting ability (if I missed it, I apologize for wasting your time.)  If I didn't miss anything, and there isn't a cap on crafting, I can't make it past level 199 for Talisman making right now.  I've done this on Destro, but the Order character I've been trying this most recently with has used 37 level 175 fragments at skill level 199, and has failed to advance to 200.  I can chalk up 10 to 15 of those as bad die rolls (did this many times before on many servers on Live), but 37 indicates some kind of cap or error.  Thanks very much for the help.  (Tried this on character Driften on Order at approx. 12:15AM EST)

**Comment by Luth-RoR** [comment]
It's confirmed that lvl 200 talisman crafting can take much more than 37 lvl 175 mats depending on your luck. Also: the chances to levelup could differ from the mythic server, as the original chances are unknown afaik.
