### ISSUE TITLE
Engi: (and possibly others) Corp. Resist

### ISSUE THREAD

**Issue by Pumatouch** [WarEmu/WarBugs#4941]
I went and did some testing the other day on Acid Bomb and the reduced resistances it gives.
It turns out one _MUST_ begin with Acid Bomb (Corp. Resist Reduction) before applying any other dots, in order to receive the damage boost from the reduced resists. If one, on the other hand, begins combat with, say, Incendiary Rounds and *then* throw Acid Bomb on the target afterwards, Incendiary Rounds's dot damage will not receive the damage boost. One will then need to reapply IR, now that the target's resists have actually been lowered.
The difference in damage is 167 to 220 on IR dot ticks. 
Furthermore, if Acid Bomb debuff runs out and dots are still lingering, those dots will do full damage, as if the target was still debuffed.
I suspect these rules apply to all other classes who employ resist reduction.

**Comment by Pumatouch** [comment]
Here's a screen with Incendiary Rounds _before_ Acid Bomb, baseline damage.

![](http://i.imgur.com/YCNpghS.jpg)

And here's a screen with Incendiary Rounds _after_ Acid Bomb, notice the damage boost being applied to IR.

![](http://i.imgur.com/ZTKyaln.jpg)

**Comment by Evildoor** [comment]
#1444
