### ISSUE TITLE
Destro flight master in Talabecland can be killed

### ISSUE THREAD

**Issue by rybiz** [WarEmu/WarBugs#4942]
Engineer Doily can lure flight master from destro warcamp and kill him, He isnt available than for destro for as long as he can be butchered and than respawn.
![kharald_000](https://cloud.githubusercontent.com/assets/17850026/13776474/a11b5576-eaaa-11e5-8371-5d4547620811.jpg)

**Comment by DanaBloodkiss** [comment]
That's fixed in next patch.
