### ISSUE TITLE
Crafting inventory bug

### ISSUE THREAD

**Issue by gabor128** [WarEmu/WarBugs#4944]
Hello,

There bug which appears sometimes on inventory crafting tab. I have cultivating skill and sometimes there is a slot where the items are changing. There are more free slots, but the system sense something, maybe that there are no more space, and tries to put several different ingridient to the same slot. It cannot do it and therefore begins to change the ingridients on the same slot. I cannot pick it up or do anything with it. The only thing I can do is I change to main inventory tab and click back to crafting. Than the chaning stops. I click on the slot and pick the item and put it to a free slot. After this another ingridient appears at the "changing" slot. I put it similarly elsewhere. Sometimes there are 2 or more items stucked to one slot. The bug appears again even after I used up the materials, or put them elsewhere, or I relogged. The bugged slot is random every time on craftin tab, but surely there is an item in it. After relog in several cases many items on crafting tab dismiss (their icons), but when I move the mouse over it marks as an ingridient. I have to pick it up and put it elsewhere and the icon changes back to normal.

This problem appeared a few weeks ago. I don't know what caused/causes it. Maybe when I was in T3 elf geathering ingridients  and I went to destro side and I found special ingridients which are still not work (absorb, and so on) and maybe my inventory was full when I opened the mail from my other character. -> I throw or sold away these ingridients, but the "workin" ingridients are became bugged. I cant make a picture. I would need a video or something for the changing inridients in a slot.

I also like to mention a difficulty. It's maybe not a bug, but a bad change. It connects to cultivating. I always use an addon to make it easier. This week I noticed that when I begin a sheed growing I cannot put the necessary additional ingridients to the seed at the beginning of the process. I can put them in only when the growing process reaches the proper state!! This is a big problem I think, because I have small time periods to add the proper ingridients. If I miss the ingridient insertion, then the result will be crap. So I loose the price of the ingridients and crafting time for zero good result. I cannot use Cultivation skill and this way Aphotcary sikll too. 
It's the same without addon. Please check it!!

**Comment by Evildoor** [comment]
Items changing in one slot: #1548
Next time - one report per problem.

**Comment by calsidar** [comment]
i am having the same problem + i can't mail some items , 
and when i drag them they apear double
