### ISSUE TITLE
[Quest] "Ancient Horror" bug

### ISSUE THREAD

**Issue by Morohtar** [WarEmu/WarBugs#4946]
The Epic quest "Ancient Horror" (order, dwarf, chapter 10) presents a bug when in Badlands it is asked to click on a pillar down a gorge. 

The pillar cannot be clicked by some players while others can. Some can visualise the hand-icon cursor passing over it while others cannot. 

Even relogging and leaving-retaking the quest can solve the issue.

Thanks.

**Comment by Torquemadra** [comment]
confirm this is still the case please

**Comment by Morohtar** [comment]
It is still the case. It requires to "Observe the Stone plinth" but personally I cannot click on it and I know of other people with the same issue. Other players who were in my party group could click on it and finish the quest. The plint is in Badlands (59k, 16k).

Thanks.
