### ISSUE TITLE
lost items from inventory

### ISSUE THREAD

**Issue by Liczersky** [WarEmu/WarBugs#4947]
After suturday/sunday's hotfix I have lost almost all of mine staff. Items except mount (include book of binding), some blue items for my char, but also crafting bag is almost empty (only bottle's i have) and my private bank vault is totaly empty. I have lost potions, and seeds. I had seeds of every lvl for leveling cultivating for my guild mates, and 175 and 200 lvl seeds of all kind. It took me over 1 month to get it all and now i have only 7pcs of Majestic Gold Weed and nothing else. 
I have wrote 3 in-game CSR Appeals, but nothing has changed till now. I would be very greatfull for resolve of this issue.

**Comment by Evildoor** [comment]
Wrong place. Recently there was an issue which caused players to lose all the items and those items then appeared in vendor's buyback - if this is the case, PM a GM. If not, and this is another case of item disappearance without known reason - nothing we can do.

**Comment by Liczersky** [comment]
Thanks, that is the resolve, except one little thing. I do not have enough money to get it all back. I have spend over 35 gp, and still some staff left to rebay back. Before hotfix i had 37 gp.
And my chat over and over again send me a message that there is no GM online, when i ask if there is any GM, that can help.

**Comment by Evildoor** [comment]
Again, wrong place. Read
http://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=12202
or some other threads on forums.
