### ISSUE TITLE
The patch client was unable to update the file

### ISSUE THREAD

**Issue by acid1324** [WarEmu/WarBugs#4948]
Hello.
I've just downloaded the game through torrent, pasted launcher into to main folder and everytime i try to launch warpatch.exe such error appears.
![bug](https://cloud.githubusercontent.com/assets/17861038/13793293/8535c9da-eaf6-11e5-99e0-329824632d22.jpg)
I have 100+GB space on disc so i have no idea why i can't just run it without any problems. I have win7

**Comment by ozarmidrashim** [comment]
Please read the technical support sticky on the forum. This is not an emulator bug.
