### ISSUE TITLE
[Emulator] When player issues a name that already exists in DB, client refuses any other name

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#495]
When giving a name for a new character, which has already been taken. The server pushes to the client that the name has already been taken, but it refuses to accepted any name.

How to reproduce:

Create new character.

Type in a name that already exists. E.g Elvengreen and click Done.

Client is prompt with a message to say name is a duplicate as we already know.

If you type a different name, e.g "ruifggdfsfhjdb". It will still refuse  it.

One user claimed deleting the directory located "C:\Users\username\AppData\Local\BANANA\Return...\3.9.0.8\" temporarily resolves it.

**Comment by akanieski** [comment]
I noticed when I got the 'latest' source from WarEmu/WarEmu on git.. it doesn't seem to have the fix for the message box:
```
[Misc]
-When creating a character, if the name is taken or too short, a message will appear instead of a blank box.
```

Where is the most up-to-date source stored?

**Comment by MaxHayman** [comment]
PacketOut Out = new PacketOut((byte)Opcodes.F_SEND_CHARACTER_ERROR);
                 Out.FillString(cclient._Account.Username, 24);
                 Out.WriteStringBytes("You have entered a duplicate or invalid name. Please enter a new name.");
                 cclient.SendPacket(Out);

Its caused by this. Which is the correct packet structure. 

Its weird, the client wont send the character create packet again, UNLESS you run the packet logged in which it works fine. (Observer effect xD)

**Comment by MaxHayman** [comment]
hmm seems like F_CHECK_NAME is wrong and causingit

**Comment by MaxHayman** [comment]
Fixed.
