### ISSUE TITLE
[BO] Savin' Me hide 

### ISSUE THREAD

**Issue by Gobtar** [WarEmu/WarBugs#4950]
I am a little confused about this Magic reduction from the ability. 
This is what Get Stats reports. 
![smh](https://cloud.githubusercontent.com/assets/7888608/13802416/514db294-eb1a-11e5-9c71-271a6bcaed56.png)

I am not sure if this a bug or a quirk of the reporting, but it looks like incoming magic damage is reduced by 0.

**Comment by ozarmidrashim** [comment]
Please don't make reports for percentage stats based on .getstats alone. The formatting is for my personal interpretation and should only ever be used to support a discrepancy that you've actually noticed from gameplay or the combat log.
