### ISSUE TITLE
Order can enter dark elf chapter 6 warcamp

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#4952]
While I was checking the many wrong influence rewards for sorc (to add to another bug report that I am still working on) I met a KotBS inside the Dark Elf Chapter 6 warcamp, killing the rally master and kill collector.
I guess it isn't that big of a problem since rvr usually stay in the orvr lakes. But if it is that easy for order to enter the warcamp, it would be possible to camp rvr flagged players as they respawn if they would die in the pve area.
![elfch6](https://cloud.githubusercontent.com/assets/16590792/13816500/e4535412-eb8e-11e5-898c-03d198312d3e.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
