### ISSUE TITLE
Bad items from T2 time

### ISSUE THREAD

**Issue by Partizan-Rusi** [WarEmu/WarBugs#4954]
Bad T2 items that dropped in PvE. Mostly in Troll country long time ago.
http://i.imgur.com/QiCn0aO.jpg
![bad items cut war](https://cloud.githubusercontent.com/assets/16727243/13825031/c26aab56-ebc1-11e5-98bb-6aa5d5a83f23.jpg) 

Doomsayer Cassock , Skullbacked Mantle, Spatterguards of the Truthseeker.

Solerets of the Depraved , Spatterguards of the Depraved , Irongaunts of the Depraved .

**Comment by Torquemadra** [comment]
Seems there are multiple instances of the same item in the DB, one correct, the other... unfinished.

**Comment by Partizan-Rusi** [comment]
...a very long time ago, these items was left in the bank and forgotten :]

**Comment by genisaurus** [comment]
Removed several "%of the Depraved" items from the loot tables that were missing stats.
