### ISSUE TITLE
Certain Classes aren't able to complete Training Course (Order)

### ISSUE THREAD

**Issue by reapoh** [WarEmu/WarBugs#4955]
In the Empire Tier, as soon as you start the quests, Training Course. The quest has you talk to the career trainer, Elsa Schmidt.

Rune Priest is the only class affected by this bug.

I've also noticed that the only reward for the quest completion for the class is just Experience, while all the other classes get some boots.

Considering that this is a starter quest, I'd consider it low priority. But its a bug none the less.

**Comment by Torquemadra** [comment]
NPC was missing RP reward for completion, added now, fixed next patch.

**Comment by Soulwhisper** [comment]
![masterheal_000](https://cloud.githubusercontent.com/assets/16864486/13947386/e969d014-f022-11e5-924b-6678525ac189.jpg)
Archmage cant complete this quest too.Clicking on complete button doesnt do anything.
