### ISSUE TITLE
[White Lion] War Lion pet bugs

### ISSUE THREAD

**Issue by Rhine13** [WarEmu/WarBugs#4957]
There are a few bugs pertaining to the White Lion pet that I thought I should address, as the War Lion is pretty critical to the White Lion's damage output and class mechanic. 

1.) **The pet doesn't follow commands.** Often in rvr, I'll find myself having to flee from a fight and call my pet back, but doing so is difficult now. Simply switching the pets stance from aggressive or  defensive to passive doesn't work; the pet will continue to attack its target when switched to passive, even though the stance says that the pet should stop attacking its target and return (pic 1).
![catpleasecomehome](https://cloud.githubusercontent.com/assets/17893160/13835159/a5163962-ebcb-11e5-9ae5-dabb6e18b908.png)
Pressing Heel doesn't work either; the pet will turn towards me and then instantly return to attacking as soon as it receives damage. What I usually have to do is switch the pet to passive and spam click the Heel ability until it reaches me. This method is frustrating because I then have to manually press Attack for my pet to stop 'Heeling' and attack my target, even when switched back to a defensive or aggressive stance.

2.) **Switching between trainings doesn't work.** Trainings such as "Trained to Threaten" and "Trained to Kill" change the abilities of the war lion, which offer a lot of utility for the White Lion. Switching between these grants the player buff, but doesn't change the pet's abilities unless it is resummoned, which is about ~20 seconds of downtime (pic 2).
![trainedtohwat](https://cloud.githubusercontent.com/assets/17893160/13835323/2f5c49ee-ebcd-11e5-9ac8-01dc7a4af9d8.png)
Also, when the war lion dies and is resummoned, even if the player still has the Training buff on, the pet will be resummoned without any of its abilities. The pet then has to be desummoned, the Training used again (on top of the already persistent buff), and the pet resummoned. This may just be a graphical error that simply isn't showing the pet's abilities when changed

3.) **The pet doesn't use it's abilities in aggressive stance.** For some reason I see the pet only autoattack when in aggressive stance, which is also the default stance, which may be confusing to new players (pic 1 shows this as well). Also, the silver linings which rotate around the abilities used to be able to be right-clicked on and off during Live, which dictated whether a pet would automatically use its abilities.

4.) **The pet doesn't defend when in defensive or aggressive stance.** If I am struck by an enemy without actually attacking it, the pet will not defend me, even in defensive stance. The pet will only attack if I attack, if I command it to attack, or if it, itself, is attacked (pic 3).
![helpme](https://cloud.githubusercontent.com/assets/17893160/13835702/ec4a0e1c-ebd0-11e5-891d-2372a869c05f.png)
It's like he _doesn't even care about me._

5.) **Names don't stay.** This is probably the most trivial of the errors, but I noticed that using /petname name will rename the pet upon resummoning, but the pet will lose its name and revert back to 'War Lion' when it dies. Although maybe this is intended, and my character is really just constantly ordering new lions each time he loses one.

I've only gotten to level 12 but these are about all the bugs I've found so far pertaining to White Lion. It was my favorite class during Live and I'm glad the game is back up in this form; you all have done a really great job.
- Rhine

**Comment by Evildoor** [comment]
2 is visual
3 is reported already: #4951

**Comment by Nfkillz** [comment]
6) pets move faster than players)

**Comment by Evildoor** [comment]
It seems that you forgot about #1740.

**Comment by Zealote** [comment]
Hope noone minds if I update this report and try and make it a bit clearer? Using the OP's numbering:

1) **Bugged**. Switching to Passive or Defensive doesn't trigger the respective "stop attacking completely" and "start attacking when attacked". Switching to Aggressive, however, _does_ make pet start attacking. The lion repeatedly runs back after pressing heel when it's in Aggressive/Defensive because you're still being attacked (even if only by DoTs) - isn't that how it was on AoR?

2) **Visual**, as Evildoor said. Lion does _not_ (at least anymore) need to be resummoned to get new stance abilities (neither generally, nor after it dies).

3) a) **FIXED**. Lion does use stance abilities while in Aggressive stance.
......b) **Duplicate** of #6718 

4) **Bugged**. Lion doesn't defend when you're attacked (without you first attacking, and when it's out of aggro range in Aggr), while it's in Def/Aggr stance.

5) **Bugged**. /petname command only affects lions summoned after it's used.

**Comment by Luth-RoR** [comment]
Thanks for the update/clarification.
Also a good example why we have the "one report per bug" rule. :smirk:

**Comment by Zealote** [comment]
Yeah I was going to ask if you thought it'd be better to close this and remake separate reports (or I'm happy to), but I didn't wanna seem like I was interfering :stuck_out_tongue:

**Comment by Luth-RoR** [comment]
No it's ok, but thanks. Aza is aware of most of the stuff posted in this report iirc; it just can't be fixed atm afaik. 
Takes a while and/or needs more understanding of the server-client packet structure.

**Comment by sioding** [comment]
Will close this issue cause  the WL Pet had a complete overview.
