### ISSUE TITLE
Shadow Warrior Barrage display error

### ISSUE THREAD

**Issue by luci1981** [WarEmu/WarBugs#4964]
![firicel_001](https://cloud.githubusercontent.com/assets/17927514/13877714/47b1e956-ed15-11e5-9a0c-20c4bc2557bb.jpg)

At first usable level it display the error "Your current level is to low to use this ability". The ability is usable and it works.

**Comment by ozarmidrashim** [comment]
This is because Barrage's position was switched compared to live. We can't update the client yet.
