### ISSUE TITLE
Highpass Cementary T2 Bug 

### ISSUE THREAD

**Issue by boompoto786** [WarEmu/WarBugs#4965]
As I entered the scenario, I found myself in an area where I couldn't move or see any team mates yet I was registered in the Scenario Summary. The pictures attached shed some light in the description. Thanks
![kendalljenner_000](https://cloud.githubusercontent.com/assets/17931790/13884199/fb99385e-ecfa-11e5-9a8e-853b3e8f2736.jpg)
![kendalljenner_003](https://cloud.githubusercontent.com/assets/17931790/13884207/03e3f18e-ecfb-11e5-9cc2-1627f99398d1.jpg)

**Comment by Thorgatin** [comment]
With the "door to the clouds" in the background this looks exactly like the "zone 0" we had often at the start of the emu.

**Comment by Evildoor** [comment]
Yes, looks like zone 0, so nothing new here.
