### ISSUE TITLE
/cannel

### ISSUE THREAD

**Issue by Averatos** [WarEmu/WarBugs#4966]
Non of the in game /channel commands are working.

If doing "/channeljoin" I get "Usage: /channeljoin {channel name}"
If doing "/channeljoin (any channel)" I get nothing.

The same with every /channel-command, i.e "Usage: (etc.)" or nothing.

**Comment by ozarmidrashim** [comment]
This is deliberate. These channels exist only to power addons.

**Comment by taccr** [comment]
I already rewrote some addons to use party/guild chat or whispers.
It's a little spammy (since you usually don't hide those) but it works.
