### ISSUE TITLE
[White Lion] [Squig Herder] Pet behavior bug

### ISSUE THREAD

**Issue by Reyanabeth** [WarEmu/WarBugs#4967]
WL are able to command pet to attack while mounted.
Pet must return to its owner and be forced to "Heel" after mount summoning is complete.
But at current state WL can prevent any other player to escape/pursue him by mount, while he can.
It is not such a big thing for group pvp, but it makes huge impact on soloroam mechanic.

I suggest to check SH pets as well. Squig Herder pets must return to owner after mount summoning is complete too. 

Here you can see my pet attacking a mob, while I still sit on my mount.
![reyanabeth_005](https://cloud.githubusercontent.com/assets/17819287/13890143/24679c0c-ed74-11e5-8614-86935ea61d49.jpg)

PS I'm sorry for my poor grammar.

**Comment by Evildoor** [comment]
#604
