### ISSUE TITLE
Set of Havoc

### ISSUE THREAD

**Issue by ElMosquito** [WarEmu/WarBugs#4969]
I got this in a massive loot bag from a T2 PQ and when equipping them I got a ToK unlock for the set of Havoc. The armor piece is not giving any set bonuses though.
![shamhavoc](https://cloud.githubusercontent.com/assets/16590792/13892687/5647de0a-ed59-11e5-976a-2eb2a9e6c2fb.jpg)

I know that the set of Havoc is not completely broken since I got these on my zealot:
![zealhavoc](https://cloud.githubusercontent.com/assets/16590792/13892697/73d7dd94-ed59-11e5-8b59-2a7f24cf6704.jpg)

The only difference is that on my zealot I got the Havoc gloves from a keep siege loot bag, and on my shaman from a PQ.

**Comment by MerryGitmas** [comment]
Piece for Ironbreaker. No bonus. They are also green in quality.
![screen shot 2016-05-19 at 20 26 18](https://cloud.githubusercontent.com/assets/18053736/15406874/2ca03930-1e00-11e6-959c-fef1deb758f0.png)
![screen shot 2016-05-19 at 20 26 28](https://cloud.githubusercontent.com/assets/18053736/15406875/2eabdc7a-1e00-11e6-830f-d0f7206f9371.png)
![screen shot 2016-05-19 at 20 26 36](https://cloud.githubusercontent.com/assets/18053736/15406876/2fdcc154-1e00-11e6-8f56-f48daeaa0fa9.png)
