### ISSUE TITLE
Account Has Been Banned Just Because Asked For Support A Game Master

### ISSUE THREAD

**Issue by rapper256** [WarEmu/WarBugs#4970]
Are your Game Masters is a joke? I have been permanently banned from forum just because opened a thread as "That Game Has Main Bugs" then fans were flaming me and then I were countering them. And then I got permanently banned. Then I asked for help to the Game Master. Because I have been created characters which I want retake the names but unfortunately I couldn't entering into my account because of my account is seems not activated. Then I asked for a support from a Game Master and that jerk was permanently banned me for ban evading. He is idiot that can't comprehend that was forum ban rather in-game ban. SON OF A BITCH!

**Comment by ozarmidrashim** [comment]
Whine.
