### ISSUE TITLE
Set Piece career mistaken

### ISSUE THREAD

**Issue by 13jack13** [WarEmu/WarBugs#4971]
I just bought the gloves with my choppa from renown vendor, and received a marauder one.
![rollah_000](https://cloud.githubusercontent.com/assets/13911366/13897673/7f88cf44-edb9-11e5-9acb-59c179c31174.jpg)

**Comment by Evildoor** [comment]
Are you sure that you've not just clicked the wrong item by mistake?

**Comment by 13jack13** [comment]
100%. Bought it with medallions and have option "useful now or later" always on.

**Comment by taccr** [comment]
You cannot buy duelist gear with medallions.

**Comment by 13jack13** [comment]
Emblems dude. Pardon me. Stays the fact that is a wrong career. As you can see are bound to player. You can't trade them

**Comment by Evildoor** [comment]
Tested on dev, correctly received Punchas of the Challenger.

**Comment by 13jack13** [comment]
My question still stands. How comes they are bound to player? I couldn't wear it for sure!

**Comment by taccr** [comment]
If you would pay attention then you would have noticed that all duelist gear is bound to player - even the tradeable ones.
Anyway, tested it myself and received gloves for choppa.

**Comment by Torquemadra** [comment]
You can trade on the AH I believe

**Comment by 13jack13** [comment]
Nope

**Comment by 13jack13** [comment]
Ok i figured it out with another piece. If you open the socketing window and close it, even without socketing they become untraceable. We can close this.
