### ISSUE TITLE
[Quest] "Will of the Warboss" bug

### ISSUE THREAD

**Issue by zuzrat** [WarEmu/WarBugs#4972]
The epic quest "Will of the Warboss" (destro,greenskin,ch10).
There is no ''Ironguard Riksson'' at  Black Fire Pass (≈54k,≈34k ) i have to kill.

**Comment by 13jack13** [comment]
There is. Just before the fortress gates on the right, under the trees.

**Comment by zuzrat** [comment]
ye, you are right,thx browski!

**Comment by 13jack13** [comment]
No prob mate :D enjoy your helm
