### ISSUE TITLE
Prayer of righteousness does "morale" damage

### ISSUE THREAD

**Issue by Thorgatin** [WarEmu/WarBugs#4973]
The prayer does unmitigated damage according to the combatlog. Though the tooltip says "spirit damage".
https://i.imgur.com/TE0Mw8c.jpg

**Comment by Evildoor** [comment]
Needs to be tested on players.

**Comment by taccr** [comment]
Same target, both spirit damage attacks:
Your Judgement critically hits Spellbreak Novice for 136 damage. (66 mitigated)
Your Prayer of Righteousness hits Spellbreak Novice for 135 damage.

**Comment by Thorgatin** [comment]
Against a player target:
![u0-neu-d3-c48d925162c56c6f8bea7d379f65d4b8 pimgpsh_fullsize_distr_crop](https://cloud.githubusercontent.com/assets/8567481/13899324/b98f04ce-edeb-11e5-9b35-1ee931876cb5.jpg)
