### ISSUE TITLE
Abusing Highpass Sementry

### ISSUE THREAD

**Issue by Sosaqa** [WarEmu/WarBugs#4975]
Hello i dont know english well. Did not find place where i can report such things. I hope i am at right place. 
2 chosens Sweatpantz and Chinab knocking out through wall. After, u cant even die. So they disable 2 players from start to whole match. 
It was not accident, they knew what they do, abusing bugs.They tried do it more after.

**Comment by Evildoor** [comment]
1) This was already reported. #4523.
2) Bugtracker is a place for reporting bugs, not players. Therefore, players names are irrelevant and should not be posted. If you want to report a player for something, PM a GM.
