### ISSUE TITLE
Qhaysh Grudgecoat does not allow for appearance item

### ISSUE THREAD

**Issue by kingofvrock** [WarEmu/WarBugs#4976]
I noticed this a few weeks ago....

I have several accessory cloaks. If I equip an accessory cloak, I have no problem applying another accessory cloak's appearance over the "base" accessory cloak. However, who wants to roll with a base accessory cloak?

I have a Qhaysh Grudgecoat that I do wear, but I would like to apply the appearance of any number of the accessory cloaks that I have. Unfortunately this item does not allow me to do so.

When I try to drag/drop the accessory cloak into the back appearance slot while my Qhaysh Grudgecoat is equipped, the accessory cloak is not slotted.

**Comment by Ryanfawkez** [comment]
Fixed in next patch. I also fixed every other 2 hand flagged cloak.

**Comment by kingofvrock** [comment]
Nice! Thank you for the quick turnaround on this mundane thing.

I appreciate all you and the other devs do.

**Comment by kingofvrock** [comment]
Confirmed fix as of this posting. Thanks again.
