### ISSUE TITLE
Squig Herders bugs and Quest bugs 

### ISSUE THREAD

**Issue by nipplewizard** [WarEmu/WarBugs#498]
The skill "Get im!" does not work due to it saying no pet is active when one is.

Skills will lock up and will not be able to use even when in the middle of a fight.

When summoning squig it will sometimes never spawn and say you are still casting and you will not be able to use another skill.

Squigs will sometimes just stop moving and eventually disappear .

The Quest none shall escape you cannot talk to the person for quest.

The quest item of power the item found cannot be used.

**Comment by milosxe** [comment]
Everything in this ticket has been resolved. Closing.
