### ISSUE TITLE
Ironbreaker bouncing like rubber off elevated terrain instead of climbing/walking on it.

### ISSUE THREAD

**Issue by Letsaros** [WarEmu/WarBugs#4980]
After i got unstuck from a weird position my toon was stucked in, for some minutes later after the relog my ironbreaker couldn't climb elevated terrain in Norsca. He would instead bounce off of it like it was an invisible rubber wall.

More details. I was riding my gyrocopter on the spines of the mountains that split Norsca's center. At some point i fell down from them and got stuck in a hole on the ground. My toon was also stuck in a non stationary animation and couldn't use ./stuck nor book of binding or any channeling ability. So i just relogged.

When i loaded the game again my toon was not stuck in the whole. Instead he was, to my relief, back in Empire chapter 4. I summon my mount and proceed to take the same route and climb the rocks again to reach my initial destination (Lair of Silveroak). 

That was when i found out that for about 2 minutes i was bouncing back when i was trying to climb any elevated piece of terrain. No matter how small or easy to climb it might be. I couldn;t climb for any reason. After some minutes passed I suddenly found out i could climb/walk/ride normally again.

**Comment by Luth-RoR** [comment]
No evidence/verification/can't be replicated -> closed.
