### ISSUE TITLE
log in issues

### ISSUE THREAD

**Issue by Passionbabe63** [WarEmu/WarBugs#4982]
Hi, not sure how to word this but will do my best, I am having some serious logging in issues on random characters, by that I mean that i can log them in one day but not the next, or get logged off with party invite and not get back on, I have tried the /stuck stuck command, yesterday I tried to log on one character but the game logged me on a different character in a different zone, I have spoken to some gms online and they suggested I post on here, this has been happening for several weeks, I have tried clearing my profiles to see if that works, but no joy, it happens on order and chaos characters, I hope you may be able to offer any suggestion for fixing this. I know I am not the only one with this issue.thanks

**Comment by Passionbabe63** [comment]
any joy with fixing this please

**Comment by Evildoor** [comment]
Read the rules of the bugtracker.

**Comment by Evildoor** [comment]
Closing per rules of the bugtracker. Inability to get into the game is not solved here.
