### ISSUE TITLE
Champion's Challenge

### ISSUE THREAD

**Issue by Keleis** [WarEmu/WarBugs#4983]
Tanks can't move after casting Champion's Challenge if he uses Resolute Defense before(On live he can).
Proof: https://www.youtube.com/watch?v=0tWPOeyPifk (10:15 SM cast CC on WE)

**Comment by Torquemadra** [comment]
Quite sure this is a "fix" but dont take my word for it.

**Comment by ozarmidrashim** [comment]
Will not change this. If you use C'C, you are GRAPPLING with your opponent, unable to move, and this effect cannot be dispelled or broken. I consider this abuse.
