### ISSUE TITLE
Sigmar's Fist strength buff + potion

### ISSUE THREAD

**Issue by Gazzargh** [WarEmu/WarBugs#4984]
if you have a strength potion equipped, the +111 strength from sigmar's fist doesnt stack on top but from your unbuffed strength, only gaming +21 strength when using +90 strength potion rendering them useless.

**Comment by taccr** [comment]
Not supposed to stack.

**Comment by Gazzargh** [comment]
so the strength buff from sigmar's fist only gives +21 strength, even if you buff a group member it gives only +21 if they have a potion. without the tactic for SF to buff toughness the ability is useless effectively.

**Comment by taccr** [comment]
This is not a bug. Many classes "suffer" from this problem. You can always use another type of potion or wait for the implementation of liniments.

**Comment by Evildoor** [comment]
taccr is correct. Also, read the rules of the bugtracker.
