### ISSUE TITLE
A specialization bug with Squig Herder "Path of the Big Shootin' " (With images)

### ISSUE THREAD

**Issue by DavidWAAAGH** [WarEmu/WarBugs#4986]
Hello, when I put some mastery points to the specialization of Path of the big Shootin' the first Tactic spec its not working, its not even in my Tactics tab.

I dont know what causes this bug or if mastery trees are still bugged, but I'm just going to upload some images here.

This tactic makes that Plink casts 1 second faster but at costs 20 action points more.

I'm afraid that if I'm spending this mastery points for unlocking that mastery tree, some of the next abilities couldnt work properly.

Also, 

![bigs1](https://cloud.githubusercontent.com/assets/17970607/13908098/3d78e28a-eeca-11e5-8104-c48e93d299d3.png)
![bigs2](https://cloud.githubusercontent.com/assets/17970607/13908132/a4573272-eeca-11e5-9158-74deb99e11df.png)

Thanks.

**Comment by DavidWAAAGH** [comment]
Also, I spent 10 renown points on marksman but I'm not getting the bonus for Ballistic Skill by 4

I need to re-spec the renown points in order to put them again in marksman but, again, they restart to 0 and it shows:

Available: 0 Spent:10

Its not in the general tab, not moral tab, not tactics tab, etc...

Thanks.

![renown](https://cloud.githubusercontent.com/assets/17970607/13908164/4948e802-eecb-11e5-8d08-9a892edfba71.png)

**Comment by Evildoor** [comment]
1) You don't get the tactic just by spending 3 points in the tree, you have to put ADDITIONAL point into the tactic itself.
2) One report per problem.
3) General tab does not works properly. Use character sheet and .getstats. Marksman works, like any other such things.
