### ISSUE TITLE
Helm of the Duelist  Warrior Priest

### ISSUE THREAD

**Issue by Aelice** [WarEmu/WarBugs#4987]
![aelic_000](https://cloud.githubusercontent.com/assets/16370505/13908288/ecd8efce-eeff-11e5-8bea-849fbaf19a59.jpg)
![aelic_001](https://cloud.githubusercontent.com/assets/16370505/13908289/ed98eb30-eeff-11e5-9dc9-1a0c715b23bc.jpg)
My char turns bald when putting on the dualist healmet

**Comment by Torquemadra** [comment]
Membership to the hair club for men now attached to this helm and for the sake of political correctness they do not discriminate against women.
