### ISSUE TITLE
Thickmuck Circlet (t3 Emp. AM helm)

### ISSUE THREAD

**Issue by Landaren** [WarEmu/WarBugs#4988]
Item is missing a talisman slot.
Item is also missing some stat points possibly, although I cannot confirm that. Just loosely basing it off of items from other characters.

I.E. WP/dok helm has 
22 str
8 will
14 toughness
2% crit
Tali slot.

Sorc
22 int 
14 toughness
8 initiative 
2 crit
tali slot

**Comment by genisaurus** [comment]
Fixed in next patch.
