### ISSUE TITLE
White Lion | "primal fury"

### ISSUE THREAD

**Issue by Luth-RoR** [WarEmu/WarBugs#4989]
The ability does not increase the damage output of the WL (in the sides or back of the target).
Tested on lvl 1 rats in altdorf.

**Comment by Thorgatin** [comment]
It seems that attacks/tactics with a positional benefit work generally very unreliable:
I just tested flanking and could get the 15% damage increase only maybe 1 out of 10 times, despite being completely in the targets back all the time (the rats don't move etc.)

**Comment by Evildoor** [comment]
Hmmm. Then #4215 may be related.

**Comment by Thorgatin** [comment]
I stood completely behind the target and it was looking straight away from me/in the same direction as i did, so that there was no angle at all. I think though testing on player targets is needed here.

**Comment by Thorgatin** [comment]
I just tested it with pounce and flanking (before it was "hack"):
The same damage when pouncing from the front or completely from the back.

**Comment by Thorgatin** [comment]
Ok, seems to be only pve related; still strange though.

**Comment by genisaurus** [comment]
Note - perhaps related to the "Icone" DB column? Is that used to determine where the "frontal arc" of a creature is, or just sight radius?

**Comment by taccr** [comment]
Pretty sure the mob is just facing you before the damage is being calculated. Can you try it with someone else tanking the mob?

**Comment by Thorgatin** [comment]
Gonna try as soon as i found some victim.

**Comment by ozarmidrashim** [comment]
Confirmed working.
