### ISSUE TITLE
Zone0, Dead, no items and no guild

### ISSUE THREAD

**Issue by Zaccar20** [WarEmu/WarBugs#4993]
Hey since the patch i stuck at Zone0 with my WE.
If i use /stuck i came to Norsca but i'm death, have no items,
no guild or anything else.
And every time i Login back i'm again at Zone0.

![aeedys_002](https://cloud.githubusercontent.com/assets/12786673/13923811/51cb4562-ef82-11e5-87f3-57b4e304504c.jpg)
![aeedys_003](https://cloud.githubusercontent.com/assets/12786673/13923810/51c42bec-ef82-11e5-8a45-136121921966.jpg)
![aeedys_005](https://cloud.githubusercontent.com/assets/12786673/13923812/51cdc422-ef82-11e5-8819-f7626e8565e6.jpg)

**Comment by Nycta** [comment]
I got the same, logged my SH first, was in zone 0 dead, ability bar messed up, items missing from the backpack, didn't check the gear, he was dressed in the main menu. Then I logged the marauder, again to zone 0, backpack empty, completely naked, ability bar messed up(most abilities missing).

**Comment by Zaccar20** [comment]
ty u guys ist fixed.
You guys are awesome :)
