### ISSUE TITLE
Aethyric Shock

### ISSUE THREAD

**Issue by Mezirah** [WarEmu/WarBugs#4994]
I think the damage portion of my zealot's stagger broke the stagger itself upon application. Can you help me determine what happened here in this video? [](https://youtu.be/xnDdG3flaJg?t=52m58s)

**Comment by Mezirah** [comment]
https://youtu.be/xnDdG3flaJg?t=52m58s

**Comment by Evildoor** [comment]
I think nearby flamer hit the BW, because half a minute or so before that moment you staggered an AM and stagger worked properly there.

**Comment by Mezirah** [comment]
at 53:00 even it appears the flamer is attacking away from the BW at the slayer or knight in the frey

**Comment by ozarmidrashim** [comment]
It's not possible for this to happen.
