### ISSUE TITLE
Rhya´s Fertile Loam not working

### ISSUE THREAD

**Issue by lawfol** [WarEmu/WarBugs#4995]
I got a blue "soil" named "Rhya´s Fertile Loam" from a keep loot bag.
It cant be added to the cultivation window,neither the normal one or the miracle grow addon.

Additional thought: for that kind of loot bag it seems a pretty bad reward. It is worse than the better half of the vendor soil statwise. But this is not a real bug,just an idea.

**Comment by nalgol** [comment]
fixed next update these loams are better then soil they have a 20% chance to create a special moment aka upgrading your seeds to the next lvl no other than these loams have this stat
