### ISSUE TITLE
Connection 

### ISSUE THREAD

**Issue by jrs4286** [WarEmu/WarBugs#4998]
When the game starts the first screen comes up and says "Login Complete," then there is a pause and a black screen comes up that says "Locating battles...: and then "Searching for allies..." and gets stuck on this screen. I logged in successfully the first time I started the game, but this has happened ever since.

**Comment by Noergl** [comment]
Same problem. Played just fine (12 hours ago). Game hung up when i created a new character and tried to name it. When i relogged got the same screens as described above. I can login with my sons account on the same PC, so it doesnt seem to be the game files themselves. There are other peoples in the forum having the same difficulties. LogIn server?

**Comment by 38602** [comment]
Same issue - tried to create a new character, unsuccessfully, button DONE was not working. Then reloaded application and now stuck on black screen with "Searching for allies..."

**Comment by totadu54** [comment]
same problem, i play the game for the first time yesterday, and now, i can't connect anymore. i have this error message : 
Could not connect to Login server
System.Net.Sockets.SocketException (0x80004005): Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu 178.32.58.46:8000
   à System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
   à System.Net.Sockets.Socket.Connect(String host, Int32 port)
   à RoRLauncher.Client.Connect()

(sorry for the word in french, but i'm french, so...)

**Comment by Evildoor** [comment]
Closing per rules of the bugtracker. Inability to get into the game is not solved here.
