### ISSUE TITLE
T3 epic quest Cleansing an empire - Zumwald is gone

### ISSUE THREAD

**Issue by tomaslumba** [WarEmu/WarBugs#5002]
Hiya, in the questchain "Cleansing an empire" has Doctor Zumwald gone AWOL. His is not at the PQ and the mutant version of him is also gone. No body, just no spawn.

Kind regards

**Comment by Tholkienn** [comment]
Same for me and 2 mates.

**Comment by Torquemadra** [comment]
we know..... 

Someone on team was so awestruck by the amazing Dr Zumwald they incorporated him into the PQ he used to roam around and made him a hero.

Fixed next patch.

**Comment by tomaslumba** [comment]
Hehe, this is why we love WAR/ROR 😀
