### ISSUE TITLE
[Weapon] Calamitus Longrifle

### ISSUE THREAD

**Issue by Karast** [WarEmu/WarBugs#5003]
This is a very strange item.

This is a rank 33 rifle that has 2h melee weapon stats, and goes in the melee weapon spot instead of the ranged weapon spot. It is also classified as a "Great Gun", rather than the usual rifle, or pistol.

It looks awesome though, so it might be a fun future appearance item!

**Comment by Ryanfawkez** [comment]
Seems like a bugged entry. Fixed it to be appropriate alongside the rest of the Calamitous items, it's now a Handgun instead of a rifle, with fixed stats.

**Comment by Karast** [comment]
Great!

But should you ever feel like it please feel free to actually add in great guns. mmmm 2h rifle stats!
