### ISSUE TITLE
T3 Empire PQs 1

### ISSUE THREAD

**Issue by Partizan-Rusi** [WarEmu/WarBugs#5005]
Unterbaum Cemetery - only works in stage 1. stage 2 doesnt have objectives.

**Comment by Styrkarr** [comment]
The PQ is working on the dev server. Stage 2 is "Burn the Festering Corpse Carts".
Maybe you just have a bug with the objectives display (which happen frequently).

**Comment by Pamz123** [comment]
Pq doesnt work for me either
[http://shrani.si/f/20/sZ/13ZCzn07/arhi011.jpg](url)

**Comment by Partizan-Rusi** [comment]
I checked every object. Title says some "carts", there is no objects that can be activated at all. So I presume its bug.

**Comment by grunbag** [comment]
fixed in next patch

**Comment by Razielhell** [comment]
@Luth-RoR Close this one Luth.
