### ISSUE TITLE
[AM] Gift of Life occasionally doesn't rez

### ISSUE THREAD

**Issue by tutti13** [WarEmu/WarBugs#5006]
A guildmate has an issue, where his Gift of Life sometimes just won't rez. He has to cast it 2-3 times to rez someone, even if no enemies are around anymore.

**Comment by ozarmidrashim** [comment]
Proof?

**Comment by tutti13** [comment]
Quite hard to proof, as there is no success/error callback for healer A when rezzing player B :/

**Comment by Tiggonos** [comment]
Nvidia Shadowplay has a "record last x minutes" function, could be handy to have a video of those unsuccesful reses.

**Comment by Thorgatin** [comment]
_The other key "Video prerecord" is what it makes Afterburner for gameplay recording so awesome. You can set it to write a temporal file to your HDD or your RAM with this last option being totally awesome as it doesn't bother your HDD with useless load.
You have 2 checkers, manual and auto, with the first starting/stopping the prerecording with the hotkey and the second starting the prerecording everytime you start a 3D application. Then 3 self-explanatory options, prerecord duration or size limits and whether HDD or RAM for temporal storage._

http://l2citadel.com/forums/topic/1026-gameplay-recording-with-msi-afterburner-and-x264-encoding-on-the-fly/

**Comment by tutti13** [comment]
K, I'll pass this info on and see if we can get any footage of this.

**Comment by Tesq** [comment]
happened too on my AM sometimes it seems to not have any criteria for when it happen.

**Comment by Luth-RoR** [comment]
No evidence/response -> closed.
