### ISSUE TITLE
Quest "The Eagle's Claw"

### ISSUE THREAD

**Issue by ROR84119** [WarEmu/WarBugs#5007]
Tier One: The Blighted Isle
Quest: The Eagle's Claw
Kill Harpies 0/6

You are unable to interact with the Elven Bolt Thrower to shoot down the harpies. A shame as this is a fun little intro quest into siege weapons right after character creation

**Comment by ellionkeman** [comment]
Yet there is no harpies in the air and the bolt thrower kill those two appearing right near it by itself.
![ulallas_001](https://cloud.githubusercontent.com/assets/18136746/14304896/b6bc9356-fbbf-11e5-8a2d-bf48c8162593.jpg)

**Comment by saupreusse** [comment]
you are supposed to shot them from the sky. right now thats not possible to fix.

**Comment by Lheana** [comment]
You can now shoot harpies thanks to the Elven Bolt Thrower.
