### ISSUE TITLE
Item: Gladiator's Mediocre Sabatons

### ISSUE THREAD

**Issue by ROR84119** [WarEmu/WarBugs#5010]
Gladiator's Mediocre Sabatons
Boots (Chosen)

The boots are not seen when equipped, the character is shown barefoot

**Comment by ROR84119** [comment]
![ygarak_000](https://cloud.githubusercontent.com/assets/18016232/13972863/ac835952-f06a-11e5-9e18-6a5ee9c536a2.jpg)

**Comment by Torquemadra** [comment]
I forgot to ask... where did you get them, I already fixed btw, next patch

**Comment by ROR84119** [comment]
Chaos Chapter 1 PQ reward, green loot bag
