### ISSUE TITLE
PQ chests gone

### ISSUE THREAD

**Issue by AlistaireCrowley** [WarEmu/WarBugs#5015]
When finishing 2 PQ:s in emp T3 twice no chest appeared. Nullfill exception thrown. Item destroyed message in chat box. Same with loot chest from keep takes. And reward was not mailed after timer went out. 

Best regards

**Comment by szejoza** [comment]
Tried another 2 PQ's in Talabecland - same thing happened as the with the OP

**Comment by wargrimnir** [comment]
This is working properly now.
