### ISSUE TITLE
Scenarios crash the game (Magus)

### ISSUE THREAD

**Issue by Clawfinger84** [WarEmu/WarBugs#5016]
Several different kinds of gamebreaking crashes happen

*1 Game freezes, but I can still move around. Similar to the lagspikes, but it crashes instead of fixing itself.

*2 Entire screen shows sky texture, UI gone, and I have to manually shut the game down.

*3 Similar to *1 I can move around and everyone else is running in place, but i get two dialogueboxes stating my name and nothing else with a set of Yes/no buttons

**Comment by Evildoor** [comment]
Does the second issue says that your location is "Zone 0"?
Third looks like packet corruption.

**Comment by Clawfinger84** [comment]
UI and everything disappears, there's nothing to look at

**Comment by Clawfinger84** [comment]
And it seems to only affect my magus, WE, BG and BO are fine in SC

**Comment by Luth-RoR** [comment]
Could it be that you have some addons activated exclusively on your magus that cause the issues?
