### ISSUE TITLE
Renown per kill given bug

### ISSUE THREAD

**Issue by Dobrodushny** [WarEmu/WarBugs#5018]
Cant say if I can reproduce it, but at the keep assault I've killed enemy player (it was solo kill) and got 12500 rp and 2500 influence points like it was 400% AAO buff on me (it was not).
![image](https://cloud.githubusercontent.com/assets/12887046/13998193/ffb68a5e-f146-11e5-81e5-3d443076bf9e.png)

**Comment by Evildoor** [comment]
T2? Or T3?

**Comment by Dobrodushny** [comment]
T3

**Comment by Daniellita** [comment]
Did you actually get that renown/inf? Sometimes you get bugged information in the chat window but you don't actually receive the amounts stated (visual bug).

**Comment by Dobrodushny** [comment]
As far as I remember, I've gotten it.
