### ISSUE TITLE
Firebrew achievement

### ISSUE THREAD

**Issue by Troelsnap** [WarEmu/WarBugs#5019]
![healsnapsen_000](https://cloud.githubusercontent.com/assets/18040365/14003602/21bbcd00-f154-11e5-8b62-3813246943ab.jpg)
![healsnapsen_001](https://cloud.githubusercontent.com/assets/18040365/14003601/21bae7e6-f154-11e5-99e2-7ae8262d0618.jpg)

An achievement there that used to give a barrel with "firebrew" a granted ability. I got the achievement, but I did not get the barrel item it originally gave. a 5 charge barrel item where you would get a breath of fire for 60 mins.

**Comment by Troelsnap** [comment]
That would obviously do dmg.

**Comment by Morksezstop** [comment]
hah firebrew, so much memories about it... They better not reintroduce it
