### ISSUE TITLE
Shadow Warrior Animation Bugs/Errors

### ISSUE THREAD

**Issue by Jestus** [WarEmu/WarBugs#5020]
I've noticed on the Shadow Warrior the following strange things/possible bugs:

- No bowstrings on any of the bows
- Often times no visible arrows fire, but damage is still done
- Sometimes when arrows fire, they move extremely slow toward the target and disappear before arriving (but still do damage)

Since the effect these have is largely aesthetic, I realize it's low priority. However, I figured I'd post it anyway just to have the info.

**Comment by Ryanfawkez** [comment]
Thanks for the report, sadly we cannot tackle any of these issues yet as long as we do not have full client control that'll allow us to add such a visual effects/tackle existing ones.
