### ISSUE TITLE
[Zealot] Windblock 1shots

### ISSUE THREAD

**Issue by Scrilian** [WarEmu/WarBugs#5024]
1760 three times per second of moral damage
![gaziraga_191](https://cloud.githubusercontent.com/assets/16498708/14029266/240f4906-f212-11e5-8feb-e706f4f61ae5.jpg)

**Comment by Torquemadra** [comment]
this is hitting only once per character on dev server

**Comment by Scrilian** [comment]
The guy could be hacking, single handedly stopped the push.

**Comment by Torquemadra** [comment]
I wasnt disputing, merely tested on dev and advised to assist Azarael.
