### ISSUE TITLE
Knight of the Blazing Sun Emp Chapter 5 Influence Rewards

### ISSUE THREAD

**Issue by Dhaegon** [WarEmu/WarBugs#5026]
The influence rewards for the Knight of the Blazing Sun in Empire  chapter 5 Elite include the Warrior Priest Charm "Defient Book". The item of course can't be used by a KotBS thus is a useless reward. As I remember that should have been a shield, but I am unable to find any information on this. 
![tamius_000](https://cloud.githubusercontent.com/assets/18058170/14029987/4c9ad1ae-f1d3-11e5-939d-e15a9cfe9960.jpg)

**Comment by Ryanfawkez** [comment]
Ironically enough, it isn't a Warrior Priest's book, as it misses that class restriction. It's also the sole reason this reward is able to show up for the KotBS and any other Empire class.

Fixed in next patch.
