### ISSUE TITLE
Glowing Eyes (Visual Bug)

### ISSUE THREAD

**Issue by Blubberino** [WarEmu/WarBugs#5028]
People who operate the auctioneer seem to get glowing eyes well atleast nearly everyone there gets it.

![valfaros_014](https://cloud.githubusercontent.com/assets/16993024/14031860/42f36968-f20f-11e5-9743-b1c76b21d275.jpg)

Probabbly something similar to that super growth an hour before???

**Comment by ozarmidrashim** [comment]
Should be fixed.

**Comment by Blubberino** [comment]
Yep didn't seen anything like this morning
