### ISSUE TITLE
[Item] Boundless Trollsplitter missing dps

### ISSUE THREAD

**Issue by Scrilian** [WarEmu/WarBugs#5029]
2.3 dps less, 1 str and 1ws missing
![valtor_263](https://cloud.githubusercontent.com/assets/16498708/14031991/e0649e0e-f220-11e5-9a79-cdcebf07c908.jpg)

**Comment by Scrilian** [comment]
Come to think of it, hatchet speed is weird too.

**Comment by Ryanfawkez** [comment]
DPS and speeds are fine. On what basis do you assume these stats are wrong? Their Destruction counterparts, or..?

**Comment by Scrilian** [comment]
Sorry if I got it wrong somewhere from the forums, weren't the 2handers supposed to get equal speeds and dps at some point? 
Like every 35lvl purple 2hander 52x1,45=75.4 dps. 
Could be wrong about the stats though.

**Comment by Ryanfawkez** [comment]
Equal speed and DPS was applied by me 1 patch after the Boundless items were in. Genisaurus reverted this change a few patches later, when he fixed all the stats.

**Comment by genisaurus** [comment]
Sorry for the confusion, and for having to revert Ryan's change.

No bugs here, everything working as intended.
