### ISSUE TITLE
Epic Quest "Ancient Horror" Epic Bug

### ISSUE THREAD

**Issue by mattyrichards** [WarEmu/WarBugs#5030]
Just completed the Epic Dwarf Quest "Ancient Horror". Interacted with the plinth, went back to Elgrim Stoutgirth, completed quest. Reward was a blue helm. 

Helm isn't in inventory. 

Gutted. Just took me about 2 hours to complete! :D

**Comment by Shadowsmove** [comment]
I just finished the quest line and the last part had me going to the Dwarf Highking in Altdorf, maybe you still have one part left?

**Comment by Torquemadra** [comment]
hand in is dwarf king in altdorf

**Comment by mattyrichards** [comment]
You're totally right. What an idiot I am! Thanks guys.
