### ISSUE TITLE
flashfire - instant cast cant be casted while running

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#5031]
as the other bug report got derailed and i didnt find another one for this specific problem, i though it might be wise someone looks into it.

cast time casts which are modified to instant should be castable while running.

**Comment by Thorgatin** [comment]
Used to work like this on the mythic server too (player had to stop for half a second to cast).

**Comment by Tiggonos** [comment]
yes but mythic didnt have the coding god azarael!
