### ISSUE TITLE
Norsca PQ1 Ruinous Power

### ISSUE THREAD

**Issue by Japieja** [WarEmu/WarBugs#5033]
The PQ is still bugged.
When not in a group, as soon as someone else kills a target in the PQ I don't get credit for killing militiamen anymore. Can't click on the tombstones, and killing the final 'boss' doesn't finish the PQ.

EDIT: tested this multiple times over a fast amount of time.

**Comment by ellionkeman** [comment]
Confirmed
If someone is clicking on the tombstones others can't do so. 
the final boss must be killed several times for the stage to be considered completed

**Comment by wargrimnir** [comment]
This should be working properly now. Needs confirmation.

**Comment by Razielhell** [comment]
- [ ] The PQ works fine. Although purple(major) bags dont contain anything @wargrimnir

**Comment by 13jack13** [comment]
Raziel it's not true. they contain everything beside the purple item as i wrote on the forum :D

**Comment by wargrimnir** [comment]
Added items to blue and purple bags in next.
