### ISSUE TITLE
NPC's and knockdown: Kip the f*** up

### ISSUE THREAD

**Issue by Pumatouch** [WarEmu/WarBugs#5034]
It seems NPC's are phasing around and changing locations upon getting back up from a knockdown. 
An NPC was knocked down on my position, and when he got up he was in the wall, coming back out at me. Dots finished him off inside said wall, unable to reach him for loot. 
The knockdown in question was Engi tactic Stopping Power.

**Comment by Gobtar** [comment]
It is not limited to the Engi, I have had this problem using a Black Orc, Shaman, and Knight..

**Comment by taccr** [comment]
Oh exactly this happened to me y'day.
I was testing something with spiteful slam and suddenly the npc was out of range running back to me from about 100f distance.

**Comment by Luth-RoR** [comment]
There was a fix for that, shouldn't happen anymore.
