### ISSUE TITLE
Black Orc Morale 2 Walk it off!

### ISSUE THREAD

**Issue by Razzorc** [WarEmu/WarBugs#5036]
I tried it a few times now and saw, that there is no 140 toughness buff for my groupmembers within 100 feet, but only for me.

**Comment by Evildoor** [comment]
No confirmation. Also, i was on sc and BO applied this morale to me.

**Comment by Evildoor** [comment]
Aha. So it seems that there is problem here, which is similar to #4044 - morale works just fine in scenarios, but i've witnessed it only affecting BO himself while in party in PVE. Dunno about RVR. Not reopening since this looks like a general issue and #4044 will be used for it.
