### ISSUE TITLE
Huge player models like lvl 100 buff on live 

### ISSUE THREAD

**Issue by wizclone** [WarEmu/WarBugs#5038]
saw some really huge model the other night 
happened after the patch/restart of the server yesterday
![gunvan_001](https://cloud.githubusercontent.com/assets/18071457/14045509/323d92f6-f29b-11e5-850b-ef1d1d8f154a.jpg)
![gunvan_002](https://cloud.githubusercontent.com/assets/18071457/14045512/3241d71c-f29b-11e5-99d7-091658ee2704.jpg)
![gunvan_003](https://cloud.githubusercontent.com/assets/18071457/14045510/32405d56-f29b-11e5-913f-a55f74bb685e.jpg)
![gunvan_004](https://cloud.githubusercontent.com/assets/18071457/14045508/323951d2-f29b-11e5-9d12-dbf96a6b0780.jpg)
![gunvan_005](https://cloud.githubusercontent.com/assets/18071457/14045511/324167a0-f29b-11e5-90da-3317ae6b646e.jpg)

**Comment by Evildoor** [comment]
#5023
