### ISSUE TITLE
Pets | when the pet gets the killblow, the npc can't be looted

### ISSUE THREAD

**Issue by Luth-RoR** [WarEmu/WarBugs#5039]
Seems like this bug is back.
Tested with lion pet in pve.

**Comment by Thorgatin** [comment]
Seems unreliable: i had 5 cases in a row where i couldn't loot and after this i could loot regularly other mobs killed by the pet. Seems not realted to kills with pet AA or pet abilities.

**Comment by Evildoor** [comment]
Hmmm, so #1229 consists of several separate problems. Interesting.

**Comment by Yellowpillow** [comment]
same problem, some visual:
![loot](https://cloud.githubusercontent.com/assets/18102127/14712623/f5459cb8-07ee-11e6-8701-732c2d5a60b2.jpg)

**Comment by Lheana** [comment]
This has been fixed a while ago.
