### ISSUE TITLE
[Loot] WarBand Loot Drop Bug

### ISSUE THREAD

**Issue by Lidskjalf** [WarEmu/WarBugs#5041]
Happens quite frequently, text & loot rolls show player winning (1st, 2nd, 3rd, etc.) but does not reward player properly to the actual roll.

![asdgsgs](https://cloud.githubusercontent.com/assets/17505385/14051171/87ba698a-f286-11e5-8f2a-0539a3515dba.jpg)

**Comment by taccr** [comment]
If your name is not within the top 25 then the client currently thinks you are rank 1.
Common bug since the introduction of the keep bags.

In your screenshot you simply did not make it into top 25 and therefore did not win anything.
Warband or not does not matter.

**Comment by Evildoor** [comment]
This was mentioned in comments to #4804, but i'll leave this ticket open as a separate problem (and with more information).

**Comment by nalgol** [comment]
i changed it so players who are out of the 24 limit are shown as place 24 hope that works dont have enaugh ppl on my testserver to test it :-P

**Comment by Soulwhisper** [comment]
@nalgol This hasnt been fixed.Bug still persists.Those who arent in the list get the "You have placed 1st and won"...message.

**Comment by Soulwhisper** [comment]
**Changelog 05/09/2016**
Azarael
- Fixed an issue causing players to appear as first on the gold chest scoreboard if they were not in the top 24.
