### ISSUE TITLE
Keep capture reward / can't see and loot the reward Chest

### ISSUE THREAD

**Issue by waukenn** [WarEmu/WarBugs#5042]
hi 

the 23 / 03 / 2016 , i participate to the Well of Qhaysh keep capture . 

After the reward roll i should be able to get a Violet bag. Unfortunatly , i wasn't able to see the chest in the keep so i can't take my bag. 
I look in the mail box , i didn't receve the bag . 

Character : Waukyne  lvl 33 sorcerer
Keep : Well of Qhaysh in Saphey 

The 23 / 03 / 2016 //  hour : 18H15 

My thank to your great job 
Waukenn

**Comment by Evildoor** [comment]
#4804
