### ISSUE TITLE
Mount in Water

### ISSUE THREAD

**Issue by Blubberino** [WarEmu/WarBugs#5045]
It is possible to use your mount when you are in water which grants you additional movement speed.

![laranaxas_021](https://cloud.githubusercontent.com/assets/16993024/14053258/37b8732e-f2d0-11e5-975d-d52affce7410.jpg)

Should be unusable but is kinda funny and makes it easier to get through water don't know if you even should fix it.

**Comment by Evildoor** [comment]
Pretty much #798
