### ISSUE TITLE
Rank 4 morale bug

### ISSUE THREAD

**Issue by Partizan-Rusi** [WarEmu/WarBugs#5046]
Magus' rank 4 morale Daemonic Scream hits multiple times for 6700+hp. Can be critical bug

http://i.imgur.com/iFg9iuC.jpg

I was hit through the keep door. All my groupmates who was within range died instantly with full hp.
![scream morale war 2016-03-25 22-51-06-933](https://cloud.githubusercontent.com/assets/16727243/14053273/19ff388e-f2e1-11e5-9005-97bf50e813cf.jpg)

**Comment by Scrilian** [comment]
Can be related? https://github.com/WarEmu/WarBugs/issues/5024
I think there is some area in the elf keep doors, where this happens and multiplies the instances of moral damage tics.
