### ISSUE TITLE
Paths' Tactics Are Not Working

### ISSUE THREAD

**Issue by BrokenDiamond** [WarEmu/WarBugs#5048]
I just Trained until get Path of Conflagration's tactic but I unfortunately I can't see that tactic.

**Comment by Evildoor** [comment]
Screenshot of your mastery path.

**Comment by BrokenDiamond** [comment]
I don't get why do ya need screenshot of my Mastery Path but so be it. [http://i66.tinypic.com/2retjxj.jpg](url)

**Comment by taccr** [comment]
Because you are obviously new to this game and didn't spend a point to train the tactic. Those are not for free.

Not a bug.

**Comment by BrokenDiamond** [comment]
What the hell are ya talking about? I'm not new to this game, I were at on live and as you can see I spent point to train the tactic. And I didn't said those are free but yes those are free, when you spent your points if you reach them you get them.

And yes, it is bug.

**Comment by Elratie** [comment]
no it´s not a bug you didn´t spend a point into the tactic itself

**Comment by BrokenDiamond** [comment]
I gonna check.

**Comment by Evildoor** [comment]
Yes, my suspicions were correct, just like posters above.
