### ISSUE TITLE
[Ability] Zealot - Mirror of Madness not work

### ISSUE THREAD

**Issue by notre4ror** [WarEmu/WarBugs#5049]
I try this hability with npc, and players and doesn't work, the char makes the animation, the cooldown is wasted but no curse is app in btoh cases.

**Comment by Torquemadra** [comment]
I have experienced this as well. It behaves strangely on the cast like it's thinking about what to do at the end of the cast then doing nothing.  Not extensively tested

**Comment by TaeBal** [comment]
I have same problem 
When i use "Mirror of Madness" my zealot doing cast motion 
But not shooting and just got cooldown
