### ISSUE TITLE
Black Orc Root uncleansable

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#5052]
BO Root is currently uncleansable.
All other tank roots are considered hexes and cleansable.

Also:
All tank roots and a couple other abilities currently do not show up as hex. (Missing isHex=true flag for example. Also effects curse and ailment abilities.)
Is this a client thing or are you able to modify all abilities to show the correct spell school flag on the clients side?
The missing flag causes the cleanse ability not to lighten up even if the ability can be cleansed.

**Comment by ozarmidrashim** [comment]
What the client says is law. If it shows as Hex, Debuff, Curse, Ailment or whatever on the client, that's the type it had on live.

**Comment by taccr** [comment]
If all tank roots are marked as debuff (which the tooltip states).
How comes that the black orc root is the only root that is not a hex and uncleansable?

**Comment by ozarmidrashim** [comment]
I don't know where you're getting your source for any of them being hexes. I determine the effect type by what the client shows when a packet to init that buff is sent. In the case of all of these roots, it shows Debuff - which is also what the client checks to determine cleanse status.

**Comment by taccr** [comment]
This is the current ability root status when it comes to cleanses:
Roots Destro:
BO: -AM/RP/WP		-> Uncleansable!
CH: -RP		+AM/WP	-> Hex
BG: -RP		+AM/WP	-> Hex

SO:	-AM		+RP/WP	-> Curse
MA:	-RP		+AM/WP	-> Hex

Uncleanse = -
Cleanseable = +

Roots Order:
IB:	-SHA	+ZE/DoK	-> Hex
KN: -SHA	+ZE/DoK	-> Hex
SM: -SHA	+ZE/DoK -> Hex

BW:	-SHA	+ZE/DoK -> Hex
ENG:-SHA	+ZE/DoK -> Hex

**Comment by ozarmidrashim** [comment]
My point is that it does not matter what's in the tooltip. If the buff icon that results from sending F_INIT_EFFECTS to the client with that ID shows something different to what is in the tooltip, it takes precedence. All of them except Fire Cage (as far as I remember) show Debuff and thus do not kick the Cleanse icon.

**Comment by taccr** [comment]
Sorc, Magus, BW, Eng root show as hex/curse iirc. Only tank roots don't show up as cleansable.
My point here is:
All tank roots but the black orc one are cleansable and currently considered hexes. They cleanse skill does not lighten up but it works.

So my question here is:
Should tank roots which are considered debuff cleansable at all?
If yes, why is black orc missing?
If no, why are all the other tank roots cleansable atm?

**Comment by ozarmidrashim** [comment]
No effect marked as Debuff should be cleansable.

**Comment by taccr** [comment]
Well then the BO root is the only tank root the currently works properly being uncleansable. Please adjust the other tank roots.

Theres also a couple other abilities like SM Wrath of Hoeth which is a damaging debuff but cleansable as a hex.

**Comment by ozarmidrashim** [comment]
Yeah, there are a few that are off.
