### ISSUE TITLE
Potent Enchantments does spirit damage

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#5053]
The tactic potent enchantments currently does spirit damage.

Tooltip does not state this. (unlike Ensorcelled Agony tactic)

**Comment by Evildoor** [comment]
How it was on live?

**Comment by taccr** [comment]
I don't know. However when comparing tooltips you get the following:
Ensorcelled Agony: Mentions spirit damage and does spirit damage
Quick Incision: Does not mention spirit damage and does normal damage
Potent Enchantments: Does not mention spirit damage and does spirit damage

Not really consistent.

**Comment by Evildoor** [comment]
I don't know either. I do have memories that on live people were saying that Deep Incision does physical damage, therefore it is crappy (since SM is a magical tank), but no such thing about Potent Enchantments. I may be wrong, though. Anyone can clarify this point?

**Comment by ozarmidrashim** [comment]
Deals spirit damage because a SM blog says it does.
