### ISSUE TITLE
Blade Enchantments triggered by tactics

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#5054]
I'm not sure about this one however I could not find anyone confirming or denying this.

Currently the tactics Ensorcelled Agony and Deep Incision are triggering Blade Enchantments.
However Potent Enchantments Tactic does not. (Reason for this could be a tactic loop)

Please confirm or deny.

**Comment by ozarmidrashim** [comment]
Impossible because DOT handler is not listened for.

**Comment by taccr** [comment]
Can you explain what you mean by "should be impossible"?
The blade enchantments triggered by those 2 tactics?

**Comment by ozarmidrashim** [comment]
They're DoT tactics. Blade Enchantments listen for direct damage from melee.

**Comment by taccr** [comment]
Well that's exactly what I'm reporting. Those two tactics currently trigger blade enchantments.

**Comment by taccr** [comment]
[![SM](http://img.youtube.com/vi/2bMlCAQGkXE/0.jpg)](http://www.youtube.com/watch?v=2bMlCAQGkXE)

**Comment by ozarmidrashim** [comment]
Yeah checked it and it's the wrong listener. Dealt with.
