### ISSUE TITLE
Buffs with bolster on character

### ISSUE THREAD

**Issue by Syddz** [WarEmu/WarBugs#5058]
With the new bolster system, a lvl 22-26 in T3 orvr lake gets bolster to 38 and self buffs are up according to this lvl if casted in those areas, but if the toon goes back in T2 or joins a T2 scenario, the buff value remains the same as in T3 orvr. E.g. armor buff value on my magus with T3 bolster is up to ~530, it remains the same if I join a T2 scenario if I don't recast the spell in there, instead of being lowered to ~330. This issue may also happen on other bolster-sensitive buffs.

**Comment by taccr** [comment]
It's exactly the same with tactics and was always like that.
That stuff doesn't scale dynamically. You have to slot your tactic with the bolster or you won't get the bolstered effect.

**Comment by ozarmidrashim** [comment]
Special case affecting buffs which stack with everything. Handled.
