### ISSUE TITLE
rain of fire freaking out

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#5059]
very often when casting rain of fire out of range (arrows grey) it doesnt react anymore instead of cancelling the spell. (castbar stays in 10second mode) you cant recast it either then but need to do another cast before it works again.
(behavior when it not freaks out but you try to cast it out of range: rain of fire is casted at the foremost possible range).

**Comment by Evildoor** [comment]
Looks like particular case of #1118 to me.

**Comment by Tiggonos** [comment]
its a bit different as its not a going on cd issue but it could be the same unfixable reason :(

**Comment by Evildoor** [comment]
Seems inconsistent. I logged onto dev server and RoF behaved like you said (concerning the movement). Then i tested some other stuff on different char, logged BW again, and now RoF refused to go on CD when cast out of range, regardless of movement.

**Comment by ozarmidrashim** [comment]
Fixed a while back when casting GTAoEs out of range was fixed
