### ISSUE TITLE
Game crashes upon login

### ISSUE THREAD

**Issue by Larolen** [WarEmu/WarBugs#5061]
I log into my destruction account and click connect. It gets to as far as the screen just before the character choosing screen then crashes the game everytime. Only happens on my destro account

**Comment by BrokenDiamond** [comment]
The launcher crashing happened to me until couple of days ago. When I click "Connect" button the laucher turns into don't respond mode. Then when I open 2nd times that launcher, then I could entering into game without problem but there isn't same issue exist anymore. I hope your problem will be fixed too. :)

**Comment by Larolen** [comment]
Hopefully i love playing my DoK and it has been 2 weeks i couldn't play.

**Comment by Evildoor** [comment]
Closing per rules of the bugtracker. Inability to get into the game is not solved here.

**Comment by Larolen** [comment]
Lol i was told to make a bug tracker post by a gm.....

**Comment by Evildoor** [comment]
Then they were wrong. Problems like this (or when you log into the game dead and have no items and cannot log out) should be solved individually, so they belong to the forum's tech support and GMs.
