### ISSUE TITLE
[Swordmaster] Wrath of Hoeth and Gusting Wind

### ISSUE THREAD

**Issue by Xvim22** [WarEmu/WarBugs#5062]
Both Wrath of Hoeth and Gusting Wind are being Disrupted. 

The tooltips show both as still gaining damage through Strength, but Wrath of Hoeth does not show any damage contribution from Weapon Damage.

**Comment by Evildoor** [comment]
Disrupt is only visual - Azarael said somewhere that it works as melee attack but shows "Disrupt" instead of "Parry".
We cannot alter the tooltips, therefore Wrath of Hoeth had no weapon damage contribution on live. 
Closing.
