### ISSUE TITLE
Renown Abilities Are Resetting After Exit From Game

### ISSUE THREAD

**Issue by BrokenDiamond** [WarEmu/WarBugs#5063]
I don't know whether if it's visual bug or not but I can Train abilities while I have less points than required and also it's annoying bug. So please developers, fix that bug.

**Comment by Evildoor** [comment]
#1486.

**Comment by BrokenDiamond** [comment]
Thank you for link. I didn't know there was same thread has been created before. But it's bug anyway and have to be fixed. ;) And if I can't remember my renown abilities that will ruin my game experience but fortunately I'm training only 1 type of renown ability.
