### ISSUE TITLE
Item that is invisible when it's equipped

### ISSUE THREAD

**Issue by SmitiB** [WarEmu/WarBugs#5065]
[Defender's Depraved Chestplate]

**Comment by MerryGitmas** [comment]
The reward for the quest "To Duty Recalled" in High Pass (Order) are swapped. The gloves replace shoes and vice-versa. One of the items is Ghostly Irongaunts
As a consequence, when equipped the item is invisible.

**Comment by Evildoor** [comment]
Create a separate report, please.
