### ISSUE TITLE
Being Kicked Out From Group After Relog

### ISSUE THREAD

**Issue by BrokenDiamond** [WarEmu/WarBugs#5068]
At on live when you relog or after you got disconnection and entering into game again you have being still in your group.

**Comment by ozarmidrashim** [comment]
Won't be addressed any time soon.

**Comment by BrokenDiamond** [comment]
I know why here is for but I just prefer to kindly ask for fix them to developers. ;)

**Comment by ozarmidrashim** [comment]
I am a developer.

**Comment by BrokenDiamond** [comment]
So then my words for ya! ;)

**Comment by Ryanfawkez** [comment]
I honestly doubt if this were ever the case on live; I know this system is used in Guild Wars 2, but I do not remember ever retaining my party after logging back in on Warhammer Online.

**Comment by Evildoor** [comment]
Closing per 2 comments above.
