### ISSUE TITLE
Can't See Group Members At Map

### ISSUE THREAD

**Issue by BrokenDiamond** [WarEmu/WarBugs#5069]
When you open map you can't see your group members as green pointed.

**Comment by ozarmidrashim** [comment]
This account belongs to banned user rapper256

**Comment by BrokenDiamond** [comment]
rapper256 is not related with my account. This account is belongs to my friend. And you are jerks who perma banned my friend's current account for just asked for support to GM. And I asked for support to GM again for my friend's account then they banned my account. WTF is wrong with you?!
