### ISSUE TITLE
Engineer [Visua;], [Trivial]

### ISSUE THREAD

**Issue by Morksezstop** [WarEmu/WarBugs#5070]
Female engineer hairstyle is changing when using helm
from
<a href='http://postimage.org/' target='_blank'><img src='http://s15.postimg.org/qcj4v0fej/image.jpg' border='0' alt="1" /></a><br /><a target='_blank' href='http://postimage.org/'>photo hosting sites</a><br /><br />

to
<a href='http://postimage.org/' target='_blank'><img src='http://s16.postimg.org/tno12ftn9/image.jpg' border='0' alt="2" /></a><br /><a target='_blank' href='http://postimage.org/app.php'>free screen capture</a><br /><br />

it change from hairstyle 9 to hairstyle 8. Probably that is the case for all female dwarves not only engineers

**Comment by ozarmidrashim** [comment]
Is this even a bug? If the hairstyle would clip, it changes.

**Comment by Morksezstop** [comment]
ah interesting observation, but i dont see reason to change it since it could be 2 tails even with helm.
But yea, i see your point and that may be the right direction
