### ISSUE TITLE
Knock down warping

### ISSUE THREAD

**Issue by adeie** [WarEmu/WarBugs#5072]
The chosen kd downfall is acting strange, when used it doesnt seem to register the kd location and makes the target act as if it were out of range, then when the kd duration is over they tend to warp to another location

**Comment by Hyronen** [comment]
Yup had the same visual issue when knocking people down they don't seem to stay in one place rather moving in the ground like kind of a lag or something strange 
asked many people and they have the same issue.

**Comment by Evildoor** [comment]
Was the same on live.

**Comment by Chummi** [comment]
it is not related to the chosen exclusive there is a problem with the netcode since it happens to every knockdown. the people just warp away

**Comment by Chummi** [comment]
"was the same on live."
bullshit, sorry. the kick and KD behavior was way different i played WH from day one to the end and the people moved at best a bit infront when the lag was real. 

https://www.youtube.com/watch?v=yOoIo1hnYi4

1:05 is the first and you can keep watching.

**Comment by Lileldys** [comment]
Warping has been happening since the netcode was updated earlier this week

**Comment by Evildoor** [comment]
> "was the same on live."
> bullshit, sorry. the kick and KD behavior was way different i played WH from day one to the end and the people moved at best a bit infront when the lag was real.
> 
> https://www.youtube.com/watch?v=yOoIo1hnYi4
> 
> 1:05 is the first and you can keep watching.

It seems that we are talking about different things, since your video does not shows behavior which i had in mind. Can someone make a video of this current knockdown warping?

**Comment by adeie** [comment]
Was testing it last night a long with making this report, here are some clips I have, as you can see when the target is kd they continue to either move in one direction or they warp to another.

https://vimeo.com/160614371

**Comment by Evildoor** [comment]
Ahem. Yes, this is exactly what i had in mind. According to Lileldys's comment, this only started happening after certain patch, so maybe we can do something. But this (at least some issue with KDs which caused the same visual effects) did happened on live.

**Comment by Halhammer** [comment]
Can confirm this only emerged after last patch. If you KD a target, and KB after it'll get punted into a completely random direction. I don't recall that bein the case back on live.

**Comment by taccr** [comment]
Pretty sure this is the same problem as https://github.com/WarEmu/WarBugs/issues/5034#issuecomment-202110937

**Comment by Chummi** [comment]
https://www.twitch.tv/stenchypow/v/57232204

1:15:40 - if you wanna see more feel free to skip to the re-broadcast.

in the video i linked above you can see how cc worked on live. it was almost every time on point. sometimes ppl warped away like 1 step infront of you and i never had similiar issues to the one here or the one you described Evildoor, so i am not sure under which circumstances you where playing but the information that this is similiar to live is simply false.

also the abilities are known as crowd CONTROL, i doubt that it is control to SAFE ppl by give them one or multiple free warps across the whole map so i dont even get why we are arguing here and dont simply fix it.

**Comment by Evildoor** [comment]
> i dont even get why we are arguing here and dont simply fix it.

I already assigned Aza to this as soon as i've heard that the KDs were fine before certain patch, so this will be fixed. What i don't get is why you keep insisting so much that this never happened on live. Do you understand that by the laws of logic you have to provide videos of 100% game process of the whole WAR to prove your point, which is obviously impossible? Replace "bullshit" and "simply false" with "this never happened to me personally or everyone i've played with" and your point will be valid.

**Comment by Tesq** [comment]
there are other case of warping when ppl is up on wall they ghost up and down on the walls.

**Comment by Luth-RoR** [comment]
There was a fix for that, shouldn't happen anymore.
