### ISSUE TITLE
XP stuck

### ISSUE THREAD

**Issue by kabbolt** [WarEmu/WarBugs#5075]
Hello, my problem is simple. I do not gain XP in PvE but i gain some in battlegroup and those for 2 weeks.

XP now work with my lvlup 27 in battlegroup, after to have to create another character who he, can disconnect it by the interface while my wizard cannot. COMPUTING WTF !

PS: Sabacik you are serious man !? xD

**Comment by Sabacik** [comment]
If you are killing mobs which are trivial (grey) you will not get XP

**Comment by Evildoor** [comment]
This problem still persists?

**Comment by Evildoor** [comment]
No response, closing.
