### ISSUE TITLE
Chaos Magus Infused Disc Ridin' Shirt Can't Be Used for Alternate Appearance

### ISSUE THREAD

**Issue by beddiecrokka** [WarEmu/WarBugs#5076]
Attempting to use Chaos Magus' Starter Gear Chest piece "Infused Disc Ridin' Shirt" (Item ID 187622) as Alternate Appearance for another chest piece which is labeled as Alternate Appearance Available (e.g., "Militia Nightrobe", ID 702103), results in the alternate appearance not being applied even though the game properly asks for confirmation.

The intended outcome is that the "Militia Nightrobe" would now have the appearance of the "Infused Disc Ridin' Shirt".

To reproduce the problem, obtain a "Militia Nightrobe" from the Renown Gear Merchant in T1 Nordland (Pillager Nigel at Blessed Gathering Warcamp) and equip it by hitting P to open your Character Portrait, then drag/drop it in your Chestpiece slot. Click the Alternate Appearance checkbox and then drag/drop the "Infused Disc Ridin' Shirt" on the Chestpiece slot. Click Yes to the confirmation window that appears and you will see the alternate appearance is not applied.

[YouTube Video of Problem](https://youtu.be/9WSxCTdU1Sk)

**Comment by Ryanfawkez** [comment]
Already fixed in next patch.
