### ISSUE TITLE
Guild without leader

### ISSUE THREAD

**Issue by Simtexx** [WarEmu/WarBugs#5079]
Guild "Legion of Boom" is stuck in some limbo because i was somehow kicked from guild when i held lead and no one else got promoted. Since then my BW "Simtex" gets kicked when joining any new guild after some hours.

**Comment by Evildoor** [comment]
Second issue is known: #948.

**Comment by nalgol** [comment]
i made some changes to the code if guild leader is missing the nexr officr will set to guild leader hope this will sort out some of the issues

**Comment by Luth-RoR** [comment]
Should work now. The other guild+leader problems atm happen due to general DB problems. Second issue was already reported as stated.
