### ISSUE TITLE
DARK ELVES DESTRUCTION QUEST "For Amusement's Sake"

### ISSUE THREAD

**Issue by Hauclir** [WarEmu/WarBugs#508]
![hauclir_006](https://cloud.githubusercontent.com/assets/7598530/5555021/aa528f3e-8c40-11e4-94ab-c9d6ab4ae63a.jpg)
![hauclir_005](https://cloud.githubusercontent.com/assets/7598530/5555022/b32a7fc2-8c40-11e4-9c60-ac408eff1866.jpg)
![hauclir_004](https://cloud.githubusercontent.com/assets/7598530/5555025/bf91f6b4-8c40-11e4-90af-76a696cdecfb.jpg)
Location: The Blighted Isle
NPC QUEST GIVER: Overseer Rathus
Issue: You do not get the "Phaos Gem" when you first accept the quest like your suppose. You then use that gem on a Narthain-Bladewalker npc which will follow you afterwards(being mesmerized) you then bring that npc back to Overseer Rathus to complete the quest and collect your reward. There is also 2 wrong npc guards they are high elves instead of dark elves.

**Comment by Reggaewaldo** [comment]
Fixed the NPC so that they are replaced with Dark Elfes. We can not fix the item now though so I will flag this as can't fix and close for now.
