### ISSUE TITLE
[NPC] "jumping" between front arc and back arc.

### ISSUE THREAD

**Issue by Gobtar** [WarEmu/WarBugs#5080]
Mobs twitch between front arc and back arc, this isn't a major issue for mob pulling because of back peddaling but this has implications for heroes and dungeons.

**Comment by Evildoor** [comment]
#4215?

**Comment by Gobtar** [comment]
No, what I am talking about is Mobs will actively maneuver moving behind the player and then back into their front arc, as if they don't know where to stand when stationary...normally a mob will not actively maneuver once the player is at rest but continue to attack it's last position.

**Comment by notre4ror** [comment]
Yes i can confirm that.
I see that leveling my DoK since few days a go, the npc "seems" to look for your backwards all the time, happened to me on IC arena, on the ramp.

**Comment by Lheana** [comment]
I think this has been fixed.
