### ISSUE TITLE
Faction NPCs do not repopulate captured keeps

### ISSUE THREAD

**Issue by Jestus** [WarEmu/WarBugs#5081]
I'm not sure if this is a bug or working as intended with the new keep system, but I'll report it anyway:

On live, when an enemy keep was captured, friendly faction NPCs would take over the keep and the vendors, etc, would spawn on the top level. Currently this does not happen and the keep remains empty.

**Comment by Torquemadra** [comment]
Currently the other side never takes possession of the keep in real terms. You will notice many, many different things from live regarding orvr at them moment.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
