### ISSUE TITLE
Bleakwing Matriarch dont drop loot.

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5083]
Me and my friends are manage to reach Bleakwing Matriarch (hero 39lvl in Talabecland) and kill her, but no gain any loot. Please fix her. A little portal to the hill would be nice too.
![euthanizer_070](https://cloud.githubusercontent.com/assets/18102127/14083848/bf2793b2-f528-11e5-9a58-92c27496e1f6.jpg)

**Comment by genisaurus** [comment]
For my notes:
7 Bleakwing items are missing from the DB, and no items are assigned to this lair boss.
http://warhammeronline.wikia.com/wiki/Bleakwing_Matriarch

**Comment by Yellowpillow** [comment]
Here example what he supposed to drop. with fullscreen proofs below.
Please contact me if you need examples of any missing loot from 39lvl heroes, i have a lot screenshots that may help. Ingame character Arena (destro), or "Arena" account on forum.
![123](https://cloud.githubusercontent.com/assets/18102127/14123998/47f3645a-f614-11e5-90ad-eb23f993ed0d.png)
http://imgur.com/a/wuZli

**Comment by magicthighs** [comment]
The matriarch isn't supposed to drop loot. After you kill her, you're supposed to destroy the egg behind her. Then the Bleakwing Patriarch comes down, and that's the actual lair boss.

Note that none of this is working at the moment.

**Comment by Yellowpillow** [comment]
still doesn't work - no loot.
