### ISSUE TITLE
Oozing Tramplers and Pummelers of the Reaver have strange stats (lvl39 heroes drop)

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5084]
Oozing Tramplers and Pummelers of the Reaver supposet to be wearing by maradeur, anyways they have 2% block in stats, whitch make them useless because mara cant take shield. Also there may be another strange stats in anoter items from 39lvl hero-bosses.
![default](https://cloud.githubusercontent.com/assets/18102127/14084686/048fec70-f52d-11e5-92f4-3ce475559316.png)
![2](https://cloud.githubusercontent.com/assets/18102127/14084687/0491e160-f52d-11e5-9bc2-f52f9a73ec56.png)

**Comment by Ryanfawkez** [comment]
A lot of R39 lair items have outdated stats, not sure when we'll get around to fixing them to be considered useful items.

**Comment by Yellowpillow** [comment]
I think those items is good as is, but maradeur items seems to have wrong stat with block instead of something alse like parry. 
I prefer all of those items to be as they was on live, but did they really contain block? :).

**Comment by genisaurus** [comment]
Fixed in next patch.
