### ISSUE TITLE
Autoattack combat animation not activating in combat

### ISSUE THREAD

**Issue by Jestus** [WarEmu/WarBugs#5085]
It appears that many times, when beginning combat soon after dismounting or interacting with a mount, the character will stay in an idle animation, rather than the "combat stance" animation.

It doesn't happen every time, but it does happen frequently and seems to be related to mounts in some way.

Let me know if you need images!

**Comment by Evildoor** [comment]
Most likely client-sided issue, if yes then we can't do anything about it.

**Comment by ozarmidrashim** [comment]
Confirm cannot fix.
