### ISSUE TITLE
Crimson Cloak not boe

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#5089]
The cloak is currently tradeable even after equipping it once.
Shoulbe be boe.

[Video](https://www.youtube.com/watch?v=6AnSOGI5jNs#t=1m28s)

**Comment by genisaurus** [comment]
Fixed in next patch.

**Comment by Torquemadra** [comment]
Unfixed, it never was

**Comment by taccr** [comment]
What is your source?
I provided video proof of it being boe. Can't really be more clear.
