### ISSUE TITLE
Same Same but Different 

### ISSUE THREAD

**Issue by Averatos** [WarEmu/WarBugs#5091]
Some of the Boundless cloaks are the same (stat vise) but have different names. 

I don`t know if it is intentional ore something that just happen when the stats was fixed.
416180, 416186, 416313 and 416317 are the same.  

416312, 416176 are the same.

And I`m guessing that is not all that are sharing stats but not name.

**Comment by Ryanfawkez** [comment]
Item suffixes for cloaks are based on racial class allegiance.

Greatcloak = Blackguard
Fright Shawl = Witch Elf
Charmcloak = Sorceress
Torment Cloak = Disciple of Khaine
Cuvva = Black Orc
Rappin' = Choppa
Backcuvva = Squig Herder
Greencloak = Shaman
Warmantle = Knight of the Blazing Sun
Huntscloak = Witch Hunter
Keymantle = Bright Wizard
Battlecoat = Warrior Priest
Warcoat = Swordmaster
Hide = White Lion
Forest Wrap = Shadow Warrior
Wrap = Archmage
Grudgecoat = Ironbreaker
Cloak = Slayer
Cape = Engineer
Veil = Runepriest
Changehide = Chosen
Shroud = Marauder
Voidcloak = Magus
Guise = Zealot

You can check this for yourself by checking the racial restriction on Gale-Runner's cloaks, and seeing which stat other than wounds is on there. STR/WS for MDPS, BS/INT for RDPS, willpower for healers and STR/TOUGH for tanks. Cloaks from high level lairbosses have Block ratings on the tank cloaks, while they also give disrupt and less chance to be disrupted on healer cloaks.
