### ISSUE TITLE
[Public Quest] Dark Elves Tier 1 - Spires of Narthain

### ISSUE THREAD

**Issue by DiamondExplosion** [WarEmu/WarBugs#5092]
Hi,
It is possible to complete the stages 1 and 2 but not the third. The dragon (Sunlathir) we have to kill is located above the city and never go down. I also tried to taunt her or throw daggers but there was text saying : "You can't see the target".
Hope this will help,
DiamondExplosion.

**Comment by wargrimnir** [comment]
Fixed in next.
