### ISSUE TITLE
"The Grounded" - Title tome unlock - not working

### ISSUE THREAD

**Issue by Nycta** [WarEmu/WarBugs#5094]
**Bird, Warhawk (Crag Great Wing) - I Just Washed This Cloak
"The Grounded"
(D) BLIGHTED ISLE @ 7, 37 or 8, 47. Kill the warhawk by Volruc Kinslayer to collect Warhawk Feathers. WARNING: This entry is specifically buggy. Confirmed unlocks by killing the bird ONLY.
(O) See entry in SHADOWLANDS, THE below.**

Checked it on Destruction side, can't find the birds on the second location. Collected a few feathers, killed the npc many times, clicked on the feathers in the backpack. No unlock.

**Comment by Evildoor** [comment]
#3937
