### ISSUE TITLE
Lost Horror - Pocket item tome unlock - not working

### ISSUE THREAD

**Issue by Nycta** [WarEmu/WarBugs#5095]
**Horror (Lost Horror) - Where Did You All Go? x
POCKET ITEM
(D) & (O)
BLIGHTED ISLES @ 20.5, 38. In the hills W of Lacorith, there is a lone L4 champ Pink Horror. Kill him.
NOTE: For (D), climb the mt @ 24, 43. Jump on the rocks near the DE PQ "Golden Tor" to get onto the mt cliffs. Then run along the top and you should see the horror after about 10-15 seconds. Kill it.**

Tried it on Destruction. Killed the npc many times. No unlock. I have no idea what the reward (pocket item) is either.

**Comment by Ryanfawkez** [comment]
https://github.com/WarEmu/WarBugs/issues/5400
