### ISSUE TITLE
"The Howler" - Title tome unlock - not working

### ISSUE THREAD

**Issue by Nycta** [WarEmu/WarBugs#5096]
**Wolf - A View With a Howl 
"The Howler"
BLIGHTED ISLE @ 5, 49. NW of Dreamshade. While hunting wolf matrons, approach the edge of the cliff to hear "wolves howling down below". This unlocked after killing him. NOTE: Between the PQ's 'Dreamshade' & 'The Watchtower', walk along the cliffside until you get a message "Looking out over the cliffs to the dark waters below, you hear the echo of the wolfs call" and you will get the unlock.**

Tried it on Destruction. Wandered the area (the wider area as well) for quite some time, tried multiple directions, even went down the cliff approximately at the coordinates given. No unlock.

**Comment by Averatos** [comment]
For what I can tell, non of the unlocks that require you to explore/enter/walk near something are working.
