### ISSUE TITLE
"The Liberator" - Title tome unlock - not working

### ISSUE THREAD

**Issue by Nycta** [WarEmu/WarBugs#5097]
**Ogre Tyrant (Graw Leadgut) - Not What it Appears
"The Liberator"
(D) & (O)
BADLANDS @ 63, 36 or 60, 27. Enter the cave. Kill this L29 Champ and inspect the medal he drops. NOTE: If you kill him in a group, he only drops 1 medal, so you'll have to kill him several times.**

Tried it on Destruction side, with two different toons. Killed the npc, got the medal every time, clicked it in the backpack, even tried sending it to other toons in the account. No unlock.

**Comment by Evildoor** [comment]
#4433
