### ISSUE TITLE
Issue About Map's Textures Turns Into Black

### ISSUE THREAD

**Issue by letumexordo** [WarEmu/WarBugs#5098]
The issue about "explored areas" of map. I noticed that when I explored unexplored area once it has turned into black. Here is screenshot about this issue.
![letumexordo_000](https://cloud.githubusercontent.com/assets/18152938/14125069/e9422ccc-f611-11e5-94f2-6e7e34e5ae18.jpg)

**Comment by genisaurus** [comment]
This is an issue with the client, not the server. It's likely that a MYP file is marked as read-only, or was corrupted during download. Solution is to make sure all MYP files are not read-only, and if that doesn't work, re-download the game. Closing this here, since it's not fixable by staff.

**Comment by BrokenDiamond** [comment]
For being "read only" I should change them by myself because they weren't ticked as "read only." And also before I double clicked one of the .myp files but I don't think that would affect it. And I never seen that bug exist at on live, but I'm not sure quiet, though.

**Comment by Evildoor** [comment]
> And while you can code everything how wouldn't you fix that bug and other client-side issues too?

No, we cannot "code everything". And i already told you that in another ticket.

**Comment by BrokenDiamond** [comment]
Why not? Aren't you have authority for that as developers of this game? No, you didn't told me that in another ticket. lol.
