### ISSUE TITLE
blessing of isha dont work correct

### ISSUE THREAD

**Issue by hrihor88** [WarEmu/WarBugs#5099]
Why in action bar there is write 1237 but the effective heal amount is 1190? shouldnt be more than 1237? thanks a lot
![kiry_027](https://cloud.githubusercontent.com/assets/18153044/14125206/39047934-f60a-11e5-9582-65d97fa10ad5.jpg)

**Comment by Evildoor** [comment]
Why - #1624
Shouldn't be more - no, tooltips indicate the state how it was on live.

**Comment by hrihor88** [comment]
because the other healing group ( for example the WP ) heal more than the write in action bar... thats why lol

**Comment by Evildoor** [comment]
I don't know the exact mechanism, but it's quite possible that something in it causes the difference. Maybe @ozarmidrashim can clarify this point.

**Comment by ozarmidrashim** [comment]
RoR uses linear interpolation between value at rank 1 and value at rank 40. Mythic used irregular steps. This affects every skill in the game and is a very very very low priority to fix.

**Comment by hrihor88** [comment]
well okey ill wait when you have time for that thing... thanks !
