### ISSUE TITLE
"The Dark One" cannot interract with object

### ISSUE THREAD

**Issue by DizzyUA** [WarEmu/WarBugs#51]
Bloody pike not usable, so you cant place head on it
![dizzy_003](https://cloud.githubusercontent.com/assets/7514926/2908579/58007f70-d629-11e3-9427-8a608630d59c.jpg)

**Comment by Lumberjackscoot** [comment]
Is there an update on this quest being fixed?

**Comment by Lumberjackscoot** [comment]
Nvm. Once you get the head. Right click the post then go back to the quest giver and it should be complete. Sorry for the update post.

**Comment by Reggaewaldo** [comment]
Confirmed implementation as reported by Lumberjackscoot. Tried to alter the completion status but a script will most likely be needed.

Quest chain ID's are : 40029 - 40031

**Comment by Reggaewaldo** [comment]
Updated the description to include returning to the quest giver to Brandr the Grey.

Closing.
