### ISSUE TITLE
Squig Herder Squigs Issues

### ISSUE THREAD

**Issue by Jestus** [WarEmu/WarBugs#5100]
I've noticed two things happening constantly with SH Squigs that are really obnoxious to defend against:

1. Squigs teleport up on walls to attack you in keep defense. This becomes annoying because while they are easy to kill, they just keep doing it.

2. The ranged squig constantly shoots through walls and from long range. Often times it just keeps shooting through keep walls to kill you when you should be safe.

Unless these are working as intended, it would go a long way to help sieges by getting them fixed!

**Comment by Evildoor** [comment]
1) #2781
2) #1683
