### ISSUE TITLE
Cloak customization bug

### ISSUE THREAD

**Issue by DavidWAAAGH** [WarEmu/WarBugs#5101]
Hello, when I try to put a pelt from the library, a custom cloak, it doesnt work it says that my cloak cannot have a customization, its a normal cloak, not epic or something like that.

**Comment by Evildoor** [comment]
Exact item name.

**Comment by DavidWAAAGH** [comment]
Grim cloak, all renown armor vendor (cloaks), green, blue... its not working even with just normal cloaks that can be customized.

**Comment by DavidWAAAGH** [comment]
I tried all of them, and its not working, it says that "that cloak cannot be customized" but I've asked to other players and they can customize theirs.

**Comment by Ryanfawkez** [comment]
All cloaks were fixed from being 2 handed to having no 2 handed flag. Would like another post-patch confirmation request.

**Comment by Evildoor** [comment]
No response, closing.
