### ISSUE TITLE
Pots disappear after logging

### ISSUE THREAD

**Issue by JosephGarcia** [WarEmu/WarBugs#5102]
Every time I log off or get logged out (via crash, freeze, etc) and I relog instantly all my buffs are gone but more importantly the potions that I just took that still had 45+ min left on them are gone as well. Im sure you guys have probably bumped into this for a while but it gets quite annoying (thankfully willpower pots are cheap :p ) but for the others that have to waste 10g+ on pots I feel bad for. T4 is around the corner and pots are really important heading into that Tier. Thank you so much for bring back Warhammer. Glad too join you guys.

**Comment by Evildoor** [comment]
#2347
