### ISSUE TITLE
Guild Vault isnt grow

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5103]
After my guild grow up to 11 lvl, guild vault not grow with it, it supposed to add 60 spots in 2nd vault, but it doesnt. it may happened because i already byued 20 spots in 2nd vault. On live it would grows automaticly for another missing 40 spots. Please fix it if possible.

**Comment by nalgol** [comment]
ahh wouldn't that be like cheating i buy the cheap rows before unlock and get the expensive one for free?

**Comment by Aruis100** [comment]
Its unfair to force guilds to pay all that gold to unlock 10 slots at a time for those who bought it early, when it does come as an unlock for getting to rank 11. Think of that money spent as a temporary early access fee, but it shouldn't lock you into paying loads more for whats given for free anyways.

**Comment by Luth-RoR** [comment]
Report needs clarification if it stays as it is or will be fixed.
