### ISSUE TITLE
Guild joining

### ISSUE THREAD

**Issue by ishkurirriador** [WarEmu/WarBugs#5104]
The client of that player, that joins a guild goes to desynchronization. every npc, mobs etc dissapears and only killing the process and reloading both launcher and game helps. checked in Crimson Sunz guild. dunno about other guilds.

**Comment by Evildoor** [comment]
Each time? For any player who joins?

**Comment by ishkurirriador** [comment]
Yes, and I test it on my twinks and twinks of our guildmates. so it happens everytime. want to hear about other guild, is it same or not?

**Comment by Evildoor** [comment]
No, that's enough for now.

**Comment by munchykin** [comment]
Just formed a new guild and it Desyc'd the whole party when guild was formed, and has Desycn'd the next 3 players that joined.  same as above.  everything was normal after client closed and game relaunched

**Comment by Titoos** [comment]
I had the same issue, but In addition there is another scenario with exact same symptoms:
1) join guild 
2) leave guild 
3) press G to open guild window -> all players begin to disapear, then mobs, client desynchronizes with the server, but it wont disconnect you
4) shutdown client and reload
5) repeat 3), you'll get same issue
It continues to desynchronize until you rejoin guild.

**Comment by ishkurirriador** [comment]
Today our guildmate Esteri joined our guild, and do not have the same issue. her game was fine after joining guild. (she is playing at macbook using bootcamp, if this info can help)

**Comment by ishkurirriador** [comment]
checked both with my and my wife's new toons this night. Seems ok now. no more decyncs. If you did something with this problem - looks like it's that what was need! thanks!

**Comment by ishkurirriador** [comment]
New People joined our guild without problem. So, you'd fixed it! Thanks! Many years of happy living! I think this issue ticket can be closed now.
