### ISSUE TITLE
Rgearding the mass DCs in warbands (notice)

### ISSUE THREAD

**Issue by DanaBloodkiss** [WarEmu/WarBugs#5105]
quoting Yomo/WH.

"Hey,
I recognised something which may help to fix the wb mass dc ...

while you are in loading screen and your wb has this so called "mass dc" you wont crash to desktop... hope it helps

pls tell me if it was usefull :)

greetings

Yomo/WH"

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/4898#issuecomment-205963239
