### ISSUE TITLE
To Duty Recalled - Quest - Rewards are swapped and Invisible

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#5106]
The rewards for the quest "To Duty Recalled" in High Pass (Order) are swapped. The gloves replace shoes and vice-versa. One of the items is Ghostly Irongaunts
As a consequence, when equipped the item is invisible.
The NPC granting the quest is called Recalled Silver Helm
![bug report](https://cloud.githubusercontent.com/assets/18053736/14141141/2470c552-f675-11e5-81e3-56ccd49b9447.jpg)

**Comment by Torquemadra** [comment]
95% of all quest rewards for all classes was messed up, fixed next patch
