### ISSUE TITLE
WL Pounce

### ISSUE THREAD

**Issue by Braumoasta** [WarEmu/WarBugs#5107]
Seems like:

After beeing staggered, pounce keybutton is free to push, target in range, on my keybutton i see the global cooldown....but.......WL dont jump. After Death (in SC) or sometimes after 2-3mins or after zonechange (open RVR) pounce will work normally.

I might say sometimes this also happens without beeing staggered before.

**Comment by Evildoor** [comment]
A bit unclear... Can you make a video of this problem?

**Comment by Braumoasta** [comment]
ok ill try my very best^^

**Comment by Skutrug** [comment]
Yes Evil, I can confirm that I have experienced it several times. It is more frequent in Badlands and the server answers "invalid target" even though the pounce was activated and fired (see the start of the animation). It might have to do with the xyz settings of the target, but it happens to me even with NPCs.
When it starts, zoning out, relogging or (sometimes) /reloadui clear the problem.

**Comment by Tiggonos** [comment]
video:
http://tiggo.wmp.media/sonstiges/vitus/pounceput.mp4

**Comment by Tiggonos** [comment]
entering sc does fix the problem

**Comment by ozarmidrashim** [comment]
Can't reproduce
