### ISSUE TITLE
Turret's Damage doesn't attribute to an Engineer in warfront statistics.

### ISSUE THREAD

**Issue by Aliram** [WarEmu/WarBugs#5108]
Nothing more to add here. I tested it many times, deployed a turret, it killed a guy. Checked statistics still 0 damage 0 kill blows.

**Comment by genisaurus** [comment]
Engineer version of this bug https://github.com/WarEmu/WarBugs/issues/4957
Closing this as a dupllicate.

**Comment by Evildoor** [comment]
I'd rather say it's covered by #1229. Still a duplicate, though.
