### ISSUE TITLE
Two Engineer bugs.

### ISSUE THREAD

**Issue by Aliram** [WarEmu/WarBugs#5109]
About half of the times you deploy your turret, its skill icons just doesn't appear. It's a random bug, you can kill your turret and re-summon it, icons might appear this time and might not. And it's pretty annoying since you can't monitor abilities cd, let alone using it manually. At first I thought this bug has something to do with bolster, you know like your hp bar disappears sometimes when you get stats boost. But no, now I'm level 35 and it still happening. I can provide screenshots or even video if needed.

And the second one. Trench Fighting tactics doesn't increase Lightning Rod's damage. Not sure it intended or bug, it seems logical from one side, since it's a gadget and so the damage coming not from engineer himself. But I bet it worked on live servers. And it's pretty major, since Lightning Rod is a main source of tinker engi's damage.. Can you please check this one.

**Comment by genisaurus** [comment]
The first one is a known issue, and is mostly visual - the turret will still use its abilities. The latter one I don't believe was known.

**Comment by Evildoor** [comment]
Next time - one report per problem.
