### ISSUE TITLE
Block/Parry/Dodge/Disrupt from block rate shield/ws/ini/wp not added in getstats.(only for paperdoll)

### ISSUE THREAD

**Issue by Killham** [WarEmu/WarBugs#5110]
![11111](https://cloud.githubusercontent.com/assets/18173840/14152738/5a0467ee-f6bd-11e5-8eb3-65e7f10b4b2c.jpg)

**Comment by genisaurus** [comment]
Correct. This is not a bug - .getStats shows _bonus_ block/parry/dodge/disrupt, not base.
