### ISSUE TITLE
Engineer Bug

### ISSUE THREAD

**Issue by kingstewart** [WarEmu/WarBugs#5112]
So I noticed an engineer equipping 2 melle hammers + having his rifle. I know this is a bug and you cannot have 2 melle weapons as a engi. They are benefitting from another bomus item stats and that is broken. I have included pictures to show what i mean. I really want that Bug Report Token Also for my Griffon!! My name is Jimz and I am an Engineer!
![jimz_001](https://cloud.githubusercontent.com/assets/18175660/14154997/a756afb4-f68d-11e5-8aaf-e6c8812bde09.jpg)
![jimz_002](https://cloud.githubusercontent.com/assets/18175660/14154999/aa335426-f68d-11e5-9d1d-5c0486459565.jpg)
![jimz_003](https://cloud.githubusercontent.com/assets/18175660/14155001/ac76f5f8-f68d-11e5-90f6-0d474e17e95a.jpg)

**Comment by ozarmidrashim** [comment]
You should have read the topic on how to report bugs on the tracker before asking for a token, because you've just ensured that you'll never get one.

**Comment by kingstewart** [comment]
Never fails for the trolls to come out and comment like they are important. This post wasn't to you, you give yourself too much credit like your opinion matters. Try Hard, Cry Hard GG!

**Comment by Thorgatin** [comment]
The kek is epic.
