### ISSUE TITLE
[Zones] T3 reset issues.

### ISSUE THREAD

**Issue by Lidskjalf** [WarEmu/WarBugs#5114]
T3 Zones have not been resetting properly in every zone for the past 3 hours (maybe more).  Other tiers seem to be resetting properly, as seen via screenshots.  March 30/2016

![quex_030](https://cloud.githubusercontent.com/assets/17505385/14157812/05bb45aa-f68a-11e5-90d1-a4a6fefad03f.jpg)
![quex_031](https://cloud.githubusercontent.com/assets/17505385/14157814/087b72f6-f68a-11e5-83b9-7fccbe4242b8.jpg)
![quex_032](https://cloud.githubusercontent.com/assets/17505385/14157817/0b445c82-f68a-11e5-848f-aa9e41de4a18.jpg)

**Comment by Evildoor** [comment]
#5113
