### ISSUE TITLE
Possible loot bug after a patch

### ISSUE THREAD

**Issue by nefarit** [WarEmu/WarBugs#5117]
![ror2](https://cloud.githubusercontent.com/assets/14332802/14162723/e4ca59b6-f6ee-11e5-97b9-a6f39e25702a.png)

Some level 35 items (picture shows an example) are now grey after what I'm guessing was the patch on the 29th or 30th of March. Seen multiple other items having the same problem, most of them have dropped from IC arena but some were also from T3 rats, so I'm guessing it's a lvl 35 specific bug. Sadly I don't currently have more greys to show but I know I saw a weapon among others so hopefully you can see it on the loot table.

**Comment by Torquemadra** [comment]
Its a trash loot item, they are supposed to be grey, they come in all shapes and sizes, cloaks, weapons, food, body parts, they are just there for flavour.
