### ISSUE TITLE
Dwarf Ch 5 Influence Items Not Available

### ISSUE THREAD

**Issue by davidchicheung** [WarEmu/WarBugs#5118]
Dwarf Ch 5 Influence Items are not available. Screenshots attached.

![meepie_006](https://cloud.githubusercontent.com/assets/699806/14164008/37602712-f6b0-11e5-88eb-06966f2a8428.jpg)
![meepie_007](https://cloud.githubusercontent.com/assets/699806/14164007/375b782a-f6b0-11e5-9b39-29e550f6c7e5.jpg)

**Comment by Evildoor** [comment]
#2597
