### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by D4RKJ3D1** [WarEmu/WarBugs#5121]
Hello, I was excited to find this game!
I just finished downloading and tried logging in with the credentials i registered with but it told me invalid login/password. I'd REALLY like to play, any way to resolve this? Username: D4RKJ3D1

**Comment by elwafel** [comment]
Use the forums for this.

This topic should be helpful - http://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=2889

**Comment by D4RKJ3D1** [comment]
Oh sorry i just went to contact us and it led me here, my apologies.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-2115-v2-a>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-2115-v2-a>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
