### ISSUE TITLE
Da All Powerful quest

### ISSUE THREAD

**Issue by ellionkeman** [WarEmu/WarBugs#5123]
![latriel_024](https://cloud.githubusercontent.com/assets/18136746/14182404/b998aed4-f773-11e5-8c30-b1fd6534fda2.jpg)
64.5k 43.1k Stunty bone boxes can't be hit and destroyed but are count to be destroyed when you kill Irontoe Anccestor - the second quest objective

**Comment by Ryanfawkez** [comment]
GOs cannot be attacked and killed as on live yet. The shared objective is meant as a work-around for quest completion.
