### ISSUE TITLE
Nordland t1 wc chaos 2

### ISSUE THREAD

**Issue by ellionkeman** [WarEmu/WarBugs#5126]
![roobaka_007](https://cloud.githubusercontent.com/assets/18136746/14184222/d4789a62-f77c-11e5-96f9-c0c1ada4e154.jpg)
This point can be attacked by order from the hill above. Dunno if it is a bug. Never had such experience on live.

**Comment by Evildoor** [comment]
Is this i problem? I don't see any vital NPCs or points of interest here.

**Comment by ellionkeman** [comment]
When you use the cannon you can be killed. Guards don't react from that distance.

**Comment by ellionkeman** [comment]
![tookka_025](https://cloud.githubusercontent.com/assets/18136746/14185329/031d3e0e-f782-11e5-808b-07fb7cf359b8.jpg)
There they are

**Comment by ellionkeman** [comment]
![tookka_027](https://cloud.githubusercontent.com/assets/18136746/14185432/706b43e8-f782-11e5-9b6f-6c4a14b5fe43.jpg)

**Comment by Renork** [comment]
Was always like this on live.

**Comment by Evildoor** [comment]
There were similar situations which were fixed despite the situation on live, but i'm not sure if there is a problem here. If enemy realm can snipe some valuable NPCs, or players logging into the game / afking near vendors / whatever - it should be fixed. But there is nothing here (so far) but a single cannon, and if you are manning a cannon - doesn't that makes you a PVP participant, in which case you should be vulnerable?

**Comment by Renork** [comment]
@Evildoor Yes you are correct. Order has a cannon that makes you vulnerable as well (the one that's down the road). Both sides have a cannon that allows you to snipe targets down the beach, but they both still allow players to attack you, which is fine as you said (you ARE pvp'ing after all).

**Comment by ellionkeman** [comment]
thanks

**Comment by Evildoor** [comment]
Closing as not a bug then.
