### ISSUE TITLE
Swordmaster Eternal Shield bugged.

### ISSUE THREAD

**Issue by Melekh** [WarEmu/WarBugs#5129]
The level 35 shield Pavise of the Eternal currently has no stats apart from 2% Block. Correct me if i'm wrong, but I believe it should have +42 toughness on it aswell.

![edeltraudt_000](https://cloud.githubusercontent.com/assets/18197965/14190151/8b137c56-f791-11e5-95dc-b2eaa4c05230.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
