### ISSUE TITLE
No kill contribution

### ISSUE THREAD

**Issue by Morksezstop** [WarEmu/WarBugs#5130]
If your enemy die from your dots after you are death you dont get any recognition for the kill. No renown or exp, inf, db and so on

That is very unsatisfying when playing engineer...

**Comment by ozarmidrashim** [comment]
![medina_001](https://cloud.githubusercontent.com/assets/6764164/16521026/f6adeb26-3f8b-11e6-8d6e-f97827f821f7.jpg)
