### ISSUE TITLE
Wrong appearance for sigmarite bonebreaker

### ISSUE THREAD

**Issue by Theslay** [WarEmu/WarBugs#5135]
Well inverything in the tittle , and i also point the fact that i can't apply any appearance on it
![theslay_008](https://cloud.githubusercontent.com/assets/17109649/14215931/6644156a-f846-11e5-87c7-2f7457484ac6.jpg)
![theslay_009](https://cloud.githubusercontent.com/assets/17109649/14215950/7654f532-f846-11e5-9566-51d8b83561fb.jpg)

**Comment by Evildoor** [comment]
Uh, pardon my possible stupidity, but what's exactly wrong with its appearance? Looks like a hammer, no?
Tested, appearance changed without problem:
![slayer_002](https://cloud.githubusercontent.com/assets/11015074/14227075/e1c233d2-f8fc-11e5-8792-bfa98fbb364c.jpg)

**Comment by Theslay** [comment]
well on my dawie , i can't change the appearance and i don't have the right base appearance but i may be a bug only on my char . You can see on my screen that the hammer has the outlaw hammer skin despict the fact that i haven't applied any appearance and it's not the right base appearance

**Comment by Theslay** [comment]
Sorry for bad english btw :)

**Comment by Evildoor** [comment]
> right base appearance

What does this means?

**Comment by Theslay** [comment]
well it used to be this appearance and well it still is in the lobby
![screenshot_002](https://cloud.githubusercontent.com/assets/17109649/14264860/82e03420-fac0-11e5-90eb-3be792a65a2f.jpg)

**Comment by Evildoor** [comment]
Should have started with this. Seems that it was changed. DB team?

**Comment by Styrkarr** [comment]
We need a proof that this is tha right appearance. The icon of the item is one thing, the appearance is another thing. Having the outlaw icon doesn't mean it should have the outlaw appearance.

**Comment by Theslay** [comment]
well i don't know what to do more , the strange thing is that the appearance in the lobby is not the same as in game . I also point the fact that this hammer is the reward of the epic empire weapon quest so it should have a special appearance

**Comment by Torquemadra** [comment]
That will happen when things change, which happens for several reasons, sometimes items will have their appearance upgrade, sometimes they will have special appearances that they shouldnt, sometimes they will have entirely the wrong model assigned to them. In this case a rarer t3 appearance was replaced by a common t4 one, I dont know why but I have now reassigned the previous appearance as indicated in your lobby picture.

Fixed next patch

**Comment by Theslay** [comment]
Thanks you all ! I really appreciate that people take time to respond ! You're all da best !
