### ISSUE TITLE
Ancestor's Echo trigger

### ISSUE THREAD

**Issue by elwafel** [WarEmu/WarBugs#5136]
Ancestor's Echo can be triggered by Blessing of Valaya despite of it being aoe spell.

**Comment by Morksezstop** [comment]
um that is how it is suppose to be and was on live
personally i dont like the advantages that group heals got from procs over ST heals and esp hots but hey thats how the things are

**Comment by ozarmidrashim** [comment]
As Morksezstop states, this is not a bug, as much as I wish that it were.
