### ISSUE TITLE
Carrion and Vultures in Talabecland

### ISSUE THREAD

**Issue by Dirkdaring** [WarEmu/WarBugs#5137]
Tried to butcher the lvl 30 and 31 Blightbeak Carrion and Vultures in South west Talabecland, couldn`t bring up butcher ablity to butcher them and I normaly have no issue butchering them . 
![hanoveer_000](https://cloud.githubusercontent.com/assets/17651165/14221531/0d31fe4c-f82d-11e5-9887-04cb54bc6cc3.jpg)

**Comment by Lheana** [comment]
Moreover, Blightbeak Carrions should drop 'Blightbeak Beak', which, once given to healer in chap 14 Empire/healer in chap 11 Chaos, provides the unlock 'Diseased Pecking Order'.

**Comment by Lheana** [comment]
Blightbeak Carrions and Vultures still don't count as Vultures. Blightbeak Carrion still don't seem to drop the item 'Blightbeak Beak' needed for the ToK unlock.

**Comment by Ryanfawkez** [comment]
Dropchance is very rare.

**Comment by Lheana** [comment]
Plaguefeather, a vulture champion for ToK unlock 'More Than Just a Foul Feather', located in Talabecland at 5.4k 43k, does not count as Vulture (does not count at all). He nevertheless correctly provides his unlock.

**Comment by Lheana** [comment]
Fixed.
