### ISSUE TITLE
EXP Bar Went Smaller

### ISSUE THREAD

**Issue by letumexordo** [WarEmu/WarBugs#5139]
![letumexordo_001](https://cloud.githubusercontent.com/assets/18152938/14223515/64f65956-f888-11e5-9316-2ac3e014dfc2.jpg)

**Comment by Evildoor** [comment]
And what's wrong with this image?

**Comment by noisestorm** [comment]
The visual of your XP bar is simply a setting in your UI..

**Comment by Ryanfawkez** [comment]
This happened to as well, but you can fix it by just adjusting either the scale of your UI or by making the bar bigger again by dragging it out in your interface editor.
