### ISSUE TITLE
Freezing Issue

### ISSUE THREAD

**Issue by letumexordo** [WarEmu/WarBugs#5140]
Sometimes my game froze and I keep hearing a stucked sound(same sound before frozen).

**Comment by Evildoor** [comment]
Game freezing completely sounds like a problem with a client or your PC, in which case we can't do anything.

**Comment by genisaurus** [comment]
Closing - this wouldn't be an issue with the server. At best, it would be a bad packet sent causing a crash, but there's nothing here to indicate what packet that might have been.
