### ISSUE TITLE
Magus Mastery Bug

### ISSUE THREAD

**Issue by wennis1** [WarEmu/WarBugs#5141]
Magus Mastery ability " Fiery Winds ", from the Havoc path, that makes the spell " Red flickering flame " hit 2 targets instead of 1 does not work. 
I spent 3 points in the Havoc path and my " Red flickering flame  still only hits 1 target.
************************************************************************************************************

I'm sure you will fix all the bugs soon, I really appreciate all the hard work you guys do.

From one Warhammer fan to another: Thanks for this server! WAAAGH!

**Comment by Evildoor** [comment]
Not a bug. 3 points are not enough. You have to put the fourth point in the tactic itself and equip it.

**Comment by wennis1** [comment]
Yes it is working now after I respecced 4 times, I did the exact same
things 4 times....I have no idea why it didn't work the first 3 times, oh
well.

Thank you so much for the response, all your hard work and for this
fantastic experience to finally play WAR again :)

WAAAGH
