### ISSUE TITLE
Bug Dark Elves Quests Chapter 2

### ISSUE THREAD

**Issue by DiamondExplosion** [WarEmu/WarBugs#5142]
Hi,
There are two dark elves that are supposed to give quests (Ullaris Virdett and Telathor Darkthon) but when you click on them you can't receive the quest. Although when you die and reborn at the camp the icon above their head turn grey like you have the quest (but you haven't) and if you die again it'll be an orange icon like rewarding (but when you click no pop-up reward). Die a third time and the icon disappear.
Good luck with that bug,
DiamondExplosion.

**Comment by sioding** [comment]
checked - can not reproduce
