### ISSUE TITLE
Blackguard skill "Pitiless Strike" not appearing on action bar

### ISSUE THREAD

**Issue by Dortharn** [WarEmu/WarBugs#5143]
![pitistrike_bug](https://cloud.githubusercontent.com/assets/18230114/14226440/7d2153c8-f8e2-11e5-9bbb-a3465c282e62.png)
![pitistrike_bug2](https://cloud.githubusercontent.com/assets/18230114/14226452/e7cbe5da-f8e2-11e5-9c2e-52580a116114.png)
![pitistrike_bug3](https://cloud.githubusercontent.com/assets/18230114/14226472/87c1c69a-f8e3-11e5-9027-a00058ea4a6f.png)

As you can see, the icon only appears when we have enough Hate to use the skill. It is just a graphical bug though.

**Comment by Evildoor** [comment]
Seems like you have problems with your monitor or something. I can clearly see icon in grey colors when <20 Hate. And it was always that way on live. And many similar abilities grey out when they cannot be used - for example, Driven By Hate on these screens (button 8).
