### ISSUE TITLE
High Elf Female mount animation issues

### ISSUE THREAD

**Issue by Illiyara** [WarEmu/WarBugs#5145]
High Elf females have a few animation issues while mounted. First, their faces get frozen into this weird squinty grimace.
My AM normally:
![illiyara_106](https://cloud.githubusercontent.com/assets/14138704/14226989/ffbe9698-f8fa-11e5-929f-d387a238969e.jpg)
And while mounted:
![illiyara_107](https://cloud.githubusercontent.com/assets/14138704/14226992/0c6e969a-f8fb-11e5-801c-b306bdf9d4f3.jpg)

While mounted, there is no animation; she sits stiffly with that expression. My laptop isn't powerful enough to fraps, but here's how it should be: https://youtu.be/Sa6zafw0x8c?t=1m55s

When turning in place, this happens to her cloak.
![illiyara_108](https://cloud.githubusercontent.com/assets/14138704/14227020/85ac8594-f8fb-11e5-94da-3540a48cdfc8.jpg)

**Comment by Evildoor** [comment]
Faces - was like this on live and is client-related, we can't do anything.
Cloak - #5050

**Comment by Illiyara** [comment]
Ah ok thanks
