### ISSUE TITLE
[Bolster] White Lion not bolstered in RvR lakes

### ISSUE THREAD

**Issue by Skutrug** [WarEmu/WarBugs#5147]
Today the bolster is not affecting my Lion - the interface shows me as level 27 (22+5 of bolster) in T2, but my Lion is only shown as level 22 - A few days ago my lion was bolstered to 28 when I was.
It is either an error of the bolster or an error of the display.
Cheers,
Frizzie (and Fuzzy)

**Comment by noisestorm** [comment]
Try resummoning the Pet while you are inside the lake (bolstered yourself)

**Comment by Torquemadra** [comment]
The problem summons inherit the stats of the caster the time of the summoning, if you level up while having a summon out then it will remain as it was until you dismiss and resummon, the same is true in the lakes. Summon before getting bolster and its your old level, summon after and it will inherit your bolstered level. This is unlikely to be something we can fix at this time.

**Comment by Skutrug** [comment]
Yes, it appears to be fixed by resummoning the pet - not an issue, just annoyance.
Cheers
