### ISSUE TITLE
influence for wrong side

### ISSUE THREAD

**Issue by lucyferr** [WarEmu/WarBugs#5148]
well windowlicker gm with cool armor told me to post it here so i do it as asked: i tried ch12 with my blackorc and it seems that only karaz work properly at first stage(i know that pqs work fully only in tier 1 but thats not my point). apparantly killing goblins in cave dont count at all (moonfang remnant- dont get any inf and dont see even objective window nor any counts after killing)and at grimbeared station pq  killing dwarfs counts in inf for dwarf ch12 not for orcs so as orc i got few times more influence for order ch12 then for destruction side

order inf

![attilla_004](https://cloud.githubusercontent.com/assets/18238718/14230378/32aea440-f954-11e5-8a8f-f0a46a2ef619.jpg)
![attilla_005](https://cloud.githubusercontent.com/assets/18238718/14230379/32d0462c-f954-11e5-8ba2-249e4a319833.jpg)

destruction inf

![attilla_003](https://cloud.githubusercontent.com/assets/18238718/14230380/3304ef4e-f954-11e5-9396-c5e704b0b877.jpg)

**Comment by Torquemadra** [comment]
The problem is the cross faction pq functionality, they are currently set for one side only and have been allocated as such to enable influence farming evenly across the realms.

**Comment by lucyferr** [comment]
ok is there anyway to move my inf to destruction?

**Comment by lucyferr** [comment]
and what about moonfang remnanant
