### ISSUE TITLE
Wild Healing bug

### ISSUE THREAD

**Issue by Torpedovegas** [WarEmu/WarBugs#5151]
Lambent Aura for an AM costs 30 AP

When Wild Healing procs, the cost is still registering on the tooltip and actually casting for its full amount of 30 AP instead of 15 AP

Every other ability seems to register correctly except for LAmbent Aura (the 15 sec HoT)

**Comment by Evildoor** [comment]
>  the cost is still registering on the tooltip

This means that it was the same on live. I know that this looks weird when compared with WH's tooltip, but we have Mythic to thank for that. So it's not a bug, unless you have video from live where LA actually removes 15 AP while affected by WH.

> Every other ability seems to register correctly

Funnel Essence has the same problem. #2002.

**Comment by ozarmidrashim** [comment]
The only abilities that register with Wild Healing are:

- Blessing of Isha
- Boon of Hysh
- Healing Energy
