### ISSUE TITLE
[AM] Dissipating Energies ticks remove detaunts

### ISSUE THREAD

**Issue by Illiyara** [WarEmu/WarBugs#5152]
Dissipating Energies (13 pt Asuyran Mastery) is a buff placed on an ally which periodically does damage to enemies around him. 

On RoR, if you detaunt someone and he is damaged by your dissipating energies, it breaks the detaunt. This is true even if you cast it on someone else, then detaunt.
I can't find any info on how it's supposed to interact with detaunts (or if anyone even cares since it sucks so much), but the current implementation doesn't seem right.

**Comment by ozarmidrashim** [comment]
Dissipating Energies inflicts direct damage and will break detaunts.
