### ISSUE TITLE
Refreshing Draught

### ISSUE THREAD

**Issue by ShanellRoR** [WarEmu/WarBugs#5155]
On use it restores 82 AP instead of 32, as intendent. Also, if my memory does not tricks me - same problem with Recruit's warming potion.
![todd_042](https://cloud.githubusercontent.com/assets/17355822/14231699/66dad680-f995-11e5-9493-25fe075171f1.jpg)
![todd_043](https://cloud.githubusercontent.com/assets/17355822/14231700/6b10fd4c-f995-11e5-9343-bf80ef52b561.jpg)

**Comment by Luth-RoR** [comment]
82 AP would be a bit too much for level 5 i guess.
I could only find this atm:
http://warhammeronline.wikia.com/wiki/Refreshing_Draught
http://warhammeronline.wikia.com/wiki/Quickening_Draught
