### ISSUE TITLE
Influence Bars Can't Showed Up On The Screen At Tier 2 Zones

### ISSUE THREAD

**Issue by letumexordo** [WarEmu/WarBugs#5159]
![letumexordo_000](https://cloud.githubusercontent.com/assets/18152938/14232308/dd7fd582-f9af-11e5-9250-adb7e9cf4f3f.jpg)

**Comment by ellionkeman** [comment]
it isn't shown randomly sometimes even if you get inf making PQ or orvring

**Comment by letumexordo** [comment]
I don't know. I never noticed that showed up.

**Comment by Evildoor** [comment]
#4441
