### ISSUE TITLE
Salutary greaves

### ISSUE THREAD

**Issue by ellionkeman** [WarEmu/WarBugs#5160]
when you use these boots the char looks like he doesn't wear any. 
![kemahn_023](https://cloud.githubusercontent.com/assets/18136746/14232325/c3aebece-f9b0-11e5-90e2-a641a414b93e.jpg)

![kemahn_024](https://cloud.githubusercontent.com/assets/18136746/14232326/cf15fa48-f9b0-11e5-92b4-92f1cc16630a.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
