### ISSUE TITLE
No roll if player is dead.

### ISSUE THREAD

**Issue by vegfar23** [WarEmu/WarBugs#5163]
This issue has bugged me a lot of times now, so i figured I'd report it. If a player either 'needs' or 'greeds' while dead, the roll sometimes gets cancelled. I doubt this bug triggers every time, because then it would probably have been removed by now, considering how critical this bug is. It's a true killjoy for any player to 'need' for an item you've long wanted, then just watching the roll getting cancelled.

Submitted by Vegfar23

**Comment by Evildoor** [comment]
#3889
