### ISSUE TITLE
Chaos mobs dropping greenskin trash

### ISSUE THREAD

**Issue by Thorgrumm** [WarEmu/WarBugs#5164]
Exceptionally minor database anomaly added for tidy-up purposes, the Bane Knights/Champions in the Unterbaum Castle PQ also drop greenskin trash (squigskin cloak, throwin' rock) as well as three versions of same trash called 'chaos mark' with different icons. Please let them keep their 'Manly Beards' trash though :)

**Comment by NorKalli** [comment]
long since fixed
