### ISSUE TITLE
Unterbaum Castle PQ

### ISSUE THREAD

**Issue by Thorgrumm** [WarEmu/WarBugs#5165]
Noticed some anomalies with this PQ. 

First time I ran through it, the 1st stage information was shown as normal (kill x amount of Bane Knights x amount of Bane Champions), when i got to the required amount of kills on one of the mob types the PQ text to show that the goal was reached turned blue (as it should) however killing more of that type of mob continued to increment the counter.

Moving to Stage 2, killing the third champion triggers stage 3, however the champion does not remain for looting. End of stage 3, killing the champion drops the chest and completes the PQ but he doesnt remain for looting.

Also, when I now run through the PQ (completed it about 15ish times), the PQ information text (default top right of the screen) is not visible for any stage now (how many Bane Knights/Champions to kill, plus the timers for killing the champions in stages 2 and 3). Ive tried relogging and re-zoning and coming back to it but the PQ info for me does not show. I get the central screen message to tell me that i have entered the PQ, and when the next stages start, but not the stage progress info.

**Comment by Evildoor** [comment]
The last part about PQ information text applies to all PQs and was reported elsewhere.

**Comment by Thorgrumm** [comment]
Ok, good stuff. You guys are feckin' awesome btw.

**Comment by DonCarlos3850** [comment]
Tried the PQ today. First stage was okay. But the champions for the second stage did not appear. We searched the area and the castle but to no avail.

**Comment by grunbag** [comment]
already fixed it seems you can close it
