### ISSUE TITLE
Dwarven Gyrocopter in Norsca starting area

### ISSUE THREAD

**Issue by Zadur** [WarEmu/WarBugs#5167]
As title says theres a Dwarven Gyrocopter in the Norsca starting area right after the restless dead area. It is untargetable and is just sitting there before the gate

**Comment by Zadur** [comment]
![tcharz_001](https://cloud.githubusercontent.com/assets/18254681/14238017/2ced379e-fa6f-11e5-9cb4-cf2d947faad3.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by Thrileon** [comment]
those gyrocopters supose to fly. and you have to use some canons (or something like that) in the area to kill them.   
So those gyrocopters they supose to FLY on the air.  the bug is not that you cant hit them but they dont realy flying
