### ISSUE TITLE
Chaos Black Cannot Sell To NPC

### ISSUE THREAD

**Issue by davidchicheung** [WarEmu/WarBugs#5168]
As title suggests, says you can NPC for 4g on the AH but you cannot NPC it anymore.

**Comment by davidchicheung** [comment]
Screenshots attached.
![meepie_011](https://cloud.githubusercontent.com/assets/699806/14240526/5dc6e646-f9fa-11e5-91b3-45b6ab9f2b0d.jpg)
![meepie_012](https://cloud.githubusercontent.com/assets/699806/14240527/5dc8cb8c-f9fa-11e5-8dc9-313f4b5aef30.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
