### ISSUE TITLE
Quest Names Gone On Screen

### ISSUE THREAD

**Issue by letumexordo** [WarEmu/WarBugs#5169]
Sometimes quest names gone one screen, that was went back though but that was gone again. And that arrow doesn't work.
![letumexordo_001](https://cloud.githubusercontent.com/assets/18152938/14244110/1098d02e-fa62-11e5-964f-76259c0c3b5a.jpg)

**Comment by Evildoor** [comment]
This bug was here for a year or more, i've not found a report for it though. 
To be more precise - ToK forgets which quests you want to track, that's why that arrow does not works - you have to open quest log in ToK and enable tracking for each quest again.

**Comment by letumexordo** [comment]
Well I found why are they gone from screen. Because they were deleted automatically, all of them! WTF?!

**Comment by Evildoor** [comment]
Oh, it's another case then. #2001.

**Comment by Evildoor** [comment]
Closing since both problems here were already reported.
