### ISSUE TITLE
[Game Access] Login Failure at "Loading <location>" step

### ISSUE THREAD

**Issue by Skutrug** [WarEmu/WarBugs#5170]
In the last 3-4 day I am experiencing issues with login into the game at the stage of loading the location. I log into the authentication server, reach the stage of "login completed", access the character selection screen, select the character and press <play> then the game tells me it is loading the location (Altdorf... location does not matter as it affects all characters) I see the book page with the quote and the client then fail to connect with the server and I crash back to character selection screen.
In the past I experience this with heavy server use during prime European time (I am US-based) but now I have it even in low population times.
If I try long enough - maybe 20 retry, it eventually connects and then I can play.
Cheers

**Comment by Evildoor** [comment]
#2052
