### ISSUE TITLE
Buttons Stucking Issue

### ISSUE THREAD

**Issue by letumexordo** [WarEmu/WarBugs#5172]
Sometimes buttons are stucking and when you tryin to hit another button stucked button counts. For example you assign CTRL+X button as hotkey, when you hit X button then you  see at CTRL+X assigned hotkey will hitted. And it cause game turns into smaller windowed from fullscreen mode because of "Alt" button's stuck.

**Comment by Evildoor** [comment]
Most likely a problem with your PC, not the game. I have such problem.

**Comment by ozarmidrashim** [comment]
100% not an emulator issue.

**Comment by letumexordo** [comment]
I don't think so it's about my PC. Otherwise that issue should be happen on another games. It seems game's bug.

**Comment by Evildoor** [comment]
Because in my case it does happens with other games, or even out of games (in browser, for example). Maybe we have a slightly different problems, but still this does not looks as something we can fix by changing code in emulator.
