### ISSUE TITLE
jug of corn whiskey 

### ISSUE THREAD

**Issue by ellionkeman** [WarEmu/WarBugs#5174]
this item as far as i remember was giving some unlock in ToK on live. Now using it has no effect.

![latriel_079](https://cloud.githubusercontent.com/assets/18136746/14258208/0b3c35d8-faaa-11e5-89a3-bc1c4a08418e.jpg)

**Comment by Ryanfawkez** [comment]
Can't find any documentation on this item. It could be part of a quest.

**Comment by Evildoor** [comment]
No information provided, closing.
