### ISSUE TITLE
Sacred ground PQ

### ISSUE THREAD

**Issue by ellionkeman** [WarEmu/WarBugs#5177]
2 stage of PQ - Ulric's reborn look like wolves but can be scavanged upon death.
![latriel_082](https://cloud.githubusercontent.com/assets/18136746/14259277/e04672a8-faae-11e5-828f-e81ff449c5e7.jpg)

**Comment by wargrimnir** [comment]
Creature type appears to be correct. Needs confirmation.

**Comment by Lheana** [comment]
Creature type and subtype are correct

**Comment by Lheana** [comment]
These wolves can correctly be butchered.
