### ISSUE TITLE
[Killing Frenzy] quest.

### ISSUE THREAD

**Issue by Thrileon** [WarEmu/WarBugs#5178]
[Killing Frenzy]  
kill 12 Blighted Animals  - Not Working, The monsters is there but kills dont count.
Kill 6 Blighted Trolls  - Working Fine

![thrileon_001](https://cloud.githubusercontent.com/assets/18271436/14262220/01027588-fabd-11e5-9846-4f658db35514.jpg)

**Comment by Torquemadra** [comment]
Requires blighted wolves to complete, changed mission text. Fixed next patch

**Comment by Thrileon** [comment]
there is also Blighted Boars or something like that.

**Comment by Torquemadra** [comment]
That there may be but unless you want a 3rd requirement to the quest they wont count due to technical limitations

**Comment by Thrileon** [comment]
i understent. but if you can change the Blight Animals to -> Blighted Wolfs. So you avoid people keep reporting this quest ;p

**Comment by Torquemadra** [comment]
I did ;)
