### ISSUE TITLE
[Dangerous Assumptions] quest

### ISSUE THREAD

**Issue by Thrileon** [WarEmu/WarBugs#5181]
[Dangerous Assumptions]
Kill Blighted Plaguebearer   - NOT working. The monster is there but kill dont count.
Find Lursas Monolith   - Working Fine

![thrileon_002](https://cloud.githubusercontent.com/assets/18271436/14263041/2195a6ae-fac1-11e5-9d8f-bf0be16cf2d4.jpg)

**Comment by Torquemadra** [comment]
The blightED plaguebearers are further up but I can see the confusion with the BLIGHT plaguebearers. Added the correct mob close to the monolith to prevent confusion.
