### ISSUE TITLE
Client Closes After Accept Warband Invitation

### ISSUE THREAD

**Issue by letumexordo** [WarEmu/WarBugs#5184]
What the hell is this wrong with this game? I was at the Tier 2 area while I got invitation from a member who was at Tier 3 zone. Maybe that cause force-client closing bug? lol.

Edit: I don't get force-client closing when I went to Tier 3 zone. Hmm. Weird bug.

**Comment by donsastre** [comment]
the wb was bugged if that happens you need to close or the leader needs to close the bugged one and open a new one.. same for groups

greetings

**Comment by letumexordo** [comment]
Oh. Can't you fix it yet? And also thank you for make it straight. :)

**Comment by Evildoor** [comment]
#2624
