### ISSUE TITLE
Please help my dwarf escape the void

### ISSUE THREAD

**Issue by Nedrud** [WarEmu/WarBugs#5186]
My ironbreaker is lost in the void.

It started when I wanted to teleport back from Altdorf to Mount Bloodhorn. After the loading screen I only saw a pink and purple background on my monitor. My GUI worked though. I just logged out and thought I will be ok when the next day I'll log in. But it was the same, so tried to do something. Opened the map and checked minimap and they say Im in Norsca... not Mount Bloodhorn. When I moved  the minimap moved too, so something was happened but still the "game area" was pink-purple. Tried to use teleport again, but still the same colors all i saw.

Tried to join a scenario which worked, we lost becasue my team was incompetent :) But when I left the scenario still got the same void only with different colors and my minimap said I'm at "Area 0" or "Map 0" something like that.

Other characters works fine.

**Comment by Evildoor** [comment]
Read the rules of the bugtracker and use search.
