### ISSUE TITLE
[Morale 1] Point black doesn't work on NPC's

### ISSUE THREAD

**Issue by notre4ror** [WarEmu/WarBugs#5188]
Using this morale on npc only shows the animation, but the mob still coming and still attacking from the floor.

**Comment by Evildoor** [comment]
Tested several times, mob got properly knocked down.

**Comment by notre4ror** [comment]
Yes, knocked down, but continues walking and attacking (depending on the distance), that not suppose to happen after knocked down, at least for the next seconds.

**Comment by Evildoor** [comment]
Not in my case. When i said "properly knocked down", i meant that mob stopped attacking me or moving. If there is a problem then we are missing some kind of additional conditions for it to manifest.

**Comment by notre4ror** [comment]
I don't know, because i only cast morale and see the mob knocked but moving in my direction or attacking me if is close to me, i use first the blocking debuff, but not always.
I try (no party buff, no potions): 
- blocking debuff then morale -> mob keep coming with knockdown active (the npc is on the ground)
- Alot o' arrers then morale -> same result
- Blocking debuff + Alot o' arrers then morale -> same result
if i try to cast morale (getting morale killing another mob) on a close range the mobs still attacking from the floor, i can see the knockdown animation, but i recieve damage from him on the floor on the nect second he remains on the floor.
I try this with several mobs on diferents places, like IC arena, Averlon, Talabecland and Sapheri. two days testing this and two days getting the same result, mob knocked but still moving or mob knocked and still attacking.
I don't do anything special, only use the morale when is avaliable.

**Comment by notre4ror** [comment]
Ok, here a little video of what i'm talking:
https://youtu.be/2ShuyKDJa4I

**Comment by Evildoor** [comment]
@ozarmidrashim, what do you think about this?

**Comment by notre4ror** [comment]
Yesterday, on my Magus using Warping blast has a first attack, has the same results, the npc gets the debuff knockdown, but still moving, soo, maybe this issue is related to something else and not only the morale 1.

**Comment by Abolition** [comment]
I can confirm that I have experienced this on my Magus, with the abovementioned situation to notre4ror.

**Comment by notre4ror** [comment]
Seems to be a general issue with knockbacks. 
If a chosen uses KB on a mob, that mob warps to a random location and start coming.

**Comment by Evildoor** [comment]
Mobs warping after knockdown were already reported: #5034.

**Comment by Luth-RoR** [comment]
There was a fix for that, shouldn't happen anymore.
