### ISSUE TITLE
[Black Orc] "Mor' Hardcore" tactic - Incorrect distance of knock back? 

### ISSUE THREAD

**Issue by murmelon** [WarEmu/WarBugs#5190]
short=medium knoch back
![warp blast](https://cloud.githubusercontent.com/assets/12655727/14281041/54314eaa-fb3f-11e5-91ba-ad9f6941bc20.jpg)
https://www.youtube.com/watch?v=i6EbJj_VYcY
![mhardcore](https://cloud.githubusercontent.com/assets/12655727/14281086/9c9615ae-fb3f-11e5-908c-c43d8241dd10.jpg)
https://www.youtube.com/watch?v=v4buSvNtAd0&feature=youtu.be

**Comment by ozarmidrashim** [comment]
Warping Blast is power 600 angle 50. This corresponds to medium knockback on other abilities such as tank punts.
