### ISSUE TITLE
9 spells at the same time?

### ISSUE THREAD

**Issue by Ritzlas** [WarEmu/WarBugs#5192]
It's not the first time but now full life and oneshot istakill i think something is wrong,nine spell hit me at the same time from the same BW,it's a "bug"???
![xanxicar](https://cloud.githubusercontent.com/assets/18288217/14284897/bd85c7b4-fb49-11e5-9d40-8dd8fa52e586.jpg)

**Comment by ozarmidrashim** [comment]
Log is legit. Backloaded Pyroclastic Surge into Sear into Nova. GCD is 1.1s here, so it is perfectly possible to have these spells hit simultaneously.
