### ISSUE TITLE
[Vendor Issue] - Craftsman Merchant has no goods

### ISSUE THREAD

**Issue by nerdherder90** [WarEmu/WarBugs#5193]
Olbin Furrow in Oathhold at Marches of Madness has actually no goods to sell.
![war 2016-04-05 18-09-12-31](https://cloud.githubusercontent.com/assets/18290469/14289207/1464c962-fb5a-11e5-9674-c250a5e966f0.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
