### ISSUE TITLE
Turquoise Tome Unlock

### ISSUE THREAD

**Issue by cimator** [WarEmu/WarBugs#5194]
As I remember on live, there is a trophy named Turquoise Tome, one gem which should have unlocked after reaching 777 tome unlocks, just got 794 unlocks and tried taking it from library but couldnt.

**Comment by Ryanfawkez** [comment]
There's no code that supports specific types of tome unlocks. The only ones we can enable at this time are kill count objectives, special NPC kills and Gameobject interaction. Item collection/hand-in/interaction as well as everything that requires a certain count other than kills cannot be fixed yet.
