### ISSUE TITLE
Rank 12-14 Mobs Chaos Ch6 Area Dropping Rank 9 Purples

### ISSUE THREAD

**Issue by davidchicheung** [WarEmu/WarBugs#5198]
As titles suggests rank 12-14 mobs are dropping rank 9 purples. Screenshot attached.
![meepster_000](https://cloud.githubusercontent.com/assets/699806/14302638/19c821a8-fb58-11e5-99e7-c9531063ef71.jpg)
![meepster_002](https://cloud.githubusercontent.com/assets/699806/14302639/19cd14f6-fb58-11e5-8b1a-a4e163c45f87.jpg)

**Comment by genisaurus** [comment]
Fixed at some point
