### ISSUE TITLE
High Pass Cemetary Targeting Issue

### ISSUE THREAD

**Issue by Faemar650** [WarEmu/WarBugs#5199]
During the High Pass Cemetary scenario, if you open a gate to leave the starting area or click on one of the battlefield objectives, 'Target Nearest Enemy' will no work.  If you try and use this option, you target will remain the gate or BO objective.  You have to manually click on a target to choose one and then you can cycle through using Target Nearest Enemy... even then, sometimes the gate or objective will reset your target to nothing.

**Comment by Evildoor** [comment]
#5060
