### ISSUE TITLE
Witch Elf - Sever Limb

### ISSUE THREAD

**Issue by Faemar650** [WarEmu/WarBugs#5200]
This skill is supposed to disarm an opponent for 4 seconds making them unable to use a melee weapon or ranged weapon... However, opponents can still use weapons during the 4 second duration the skill is supposed to be active.   They are able to use melee/ranged skills,I couldn't tell if this effects auto-attack only, but the description doesn't say.

**Comment by Evildoor** [comment]
Proof?

**Comment by Chummi** [comment]
playing a witch elf as my destru main and yet i can't confirm. sever limbs works fine, maybe you overlooked the KD immunity which grants a immunity to disarm too?

**Comment by Faemar650** [comment]
What would like as proof?  If you hit a mob in PvE, the disarm works fine and the mob will not attack for 4 seconds.  If you hit someone in PVP, they can still continue to attack through the 4 seconds.

**Comment by Evildoor** [comment]
Video where someone gets affected by Sever Limb and still can attack. Or screens to begin with.

**Comment by Evildoor** [comment]
No proof, 1 voice against. Closing.
