### ISSUE TITLE
Tactic: Flanking

### ISSUE THREAD

**Issue by seraxes** [WarEmu/WarBugs#5201]
Front hits do 313 dmg, side and back hits do 345 with Flanking slotted.
Test has been done with Choppa with flanking hitting a Warrior Priest.
That seems to be 10% instead of 15%.

**Comment by ozarmidrashim** [comment]
Furious +25%
Berzerk +50%
Flanking +15%

140 / 125 = 1.12 (Furious)
165 / 150 = 1.1 (Berzerk)
345 / 313 = 1.10

**Comment by Tiggonos** [comment]
but these values look wrong?

25% of 125 is 31 so Furious damage should be 156
50% of 150 is 75 so Berzerk damage should be 225
15% of 313 is 47 so flanking damage should be 360

or am i missing something?

**Comment by seraxes** [comment]
So Critical damage and flanking are damage bonuses, these are calculated from the base damage.
Enrage and Berserk are both damage bonuses, same as the two above and damage bonuses are additive?

**Comment by ozarmidrashim** [comment]
Damage bonuses are additive. Damage reductions are multiplicative.

**Comment by Chummi** [comment]
Tiggo, i think you don't understand what Azarael typed and how calculation works.
Small example with less complicated numbers:
1000 base damage
50% damage from enrage
15% from flanking

1000+(1000*0,5)+(1000*0,15)=1650 (+65% damage (50+15=65)) = RIGHT
1000*1,5*1,15=1725 (+72,5% damage (50+15=65)) = WRONG

**Comment by Tiggonos** [comment]
easier to leave out berzerk and enrage.

when skill does 100 dmg from front, it should do 115dm from behind shouldnt it? (as in op example if 313 from front it should do 360 from back, shouldnt it?)

**Comment by Chummi** [comment]
not sure if srs or troll you will get the 15% on base tooltip but obviously he was enraged azarael calculated 1:1 for your with the exact numbers i just pointed out how it works for a better understanding

**Comment by Chummi** [comment]
209 was his base ttp
+31 Flanking
+105 Enrage
= 345

-31
=314

due to the difference in terms of rounding you have this ~1 difference.

only if you think the buffs stack multiplicative, you will end up with your outcome but then again you wouldn't have a 65% modifier but a 72,5% which is wrong if you just add 50+15.

should be 100% clear now, right?

**Comment by Tiggonos** [comment]
original post doesnt say anything about being berserk, that confused me prbly.

**Comment by seraxes** [comment]
Exactly, I did not think the Enrage, Berserk mechanism counted as damage bonus - I though that It simply "changed" the base damage - I don't know why, but this is how I remembered from live.
