### ISSUE TITLE
Block % contribution

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#5204]
it may be visual but from when (it seems at least) defense contribution from stats got fixed i recive a lower value from shield than what i suppose to get in paper dool menu.
it's a value around 5% ( i mean shield give me 5%), it also happen on my chosen.
The .get stats command do not show any block increase and from warratingbuster add on i have all variable stat contribution and usually near your level shield give you between 19/21% block chance.
In fact i should recive something like that. warrating booster was correct in live.

Dont know maybe is visual or not implemented yet just reporting anyway.

![ulthuan_006](https://cloud.githubusercontent.com/assets/7527415/14310807/2c1ad454-fbe4-11e5-9c9b-2bc40ba05423.jpg)
![ulthuan_007](https://cloud.githubusercontent.com/assets/7527415/14310809/2e9230ce-fbe4-11e5-8424-07c67d01bdbf.jpg)

p.s the add on was not active at this time but it happen the same on my chosen and in these screen instead it's show the ammount the add-on assign to the shield clientside.

![tesq_009](https://cloud.githubusercontent.com/assets/7527415/14311064/b836d310-fbe5-11e5-82ff-645fb8ca04ce.jpg)
![tesq_008](https://cloud.githubusercontent.com/assets/7527415/14311067/ba758950-fbe5-11e5-8f68-576fff792142.jpg)
![tesq_007](https://cloud.githubusercontent.com/assets/7527415/14311127/0ef8f0d4-fbe6-11e5-826e-0363853f6535.jpg)

p.p.s  seems like is assigned a  fix value 5% instead a variable one that scale with level

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/6196

**Comment by Luth-RoR** [comment]
The block values from shields is calculated directly against the attackers DPS stat, so that they never show with .getstats.
The paperdoll values are high likely incorrect for the same reason (see the linked report).
