### ISSUE TITLE
General Issue with Absorb

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#5207]
i dig some old screenshoot of mine and it seems absorb worked post mitigation and not pre, it's pretty clear in a case of 3x absorb on 3x different skills which it would be not possible if absorb  worked pre mitigation. i should had absorbed all the value of the absorb in 1 skill which didn't happen  and then give at least 1+ damage ( as is happening now in ror)

the result of mitigation and abosrb is 0 damage as show in screenshot from live ( you have not always 375 absorb like in ror but variable number left after mitigation: 70, 200 etc)
-is impossible get 0 with % but only with absorb
-if mitigation is show for point 1 then absorb must had work post mitigation

so absorb work exatly as a temp wounds pool, i also want to share that more absorb were cumulative regadless the source.
And absorb prevented set back which i'm not sure is happening now

![tesq_191 3](https://cloud.githubusercontent.com/assets/7527415/14311888/05799c58-fbea-11e5-8d0c-ba2f745cae6a.jpg)

**Comment by Evildoor** [comment]
Absorb mechanic was discussed #4526. Do you disagree with it?

> i also want to share that more absorb were cumulative regadless the source.
> And absorb prevented set back which i'm not sure is happening now

Need to be verified that these two point are not happening in RoR.

**Comment by Tesq** [comment]
had no point at that time after testing absorb in ror and sow how behaviour vs enemy skill

warped flesh last vs 1 skill only cos it absorb pre mitigation
on live worked vs more skill cos worked post mitigation.

no proof for the other 2 point so far need more time.

**Comment by ozarmidrashim** [comment]
Talk to Annaise about this.

**Comment by Tesq** [comment]
i dont get if it's irony or is a proposal to go further into the matter

warped flesh absorb 375 damage at rr 80

if absorbed value is  less and damage is 0 ---> then mitigation happened before and not after.

there is no way that what happened in the next screenshoot had absorb happen before, cos the BASE value of a skill for a white lion in t4 is at lest 350:  i've done multiple absorb 

![tesq_196](https://cloud.githubusercontent.com/assets/7527415/14320275/c23b40e2-fc14-11e5-84f8-0c73ad3df8b4.jpg)

**Comment by Morksezstop** [comment]
On live only mitigation that count while you got proc/skill that absorb damage was toughness.
Everything else count after the bubble is gone. That was made on purpose to balance the game when someone got multiply absorbs at large scale fights.

Sadly abosrb effects doesnt scale at all while the damage do and when everyone reach end game most absorbs become quite obsolete

**Comment by Tesq** [comment]
never said they "scale" they stack.... 

when 1 finished the other not, and it totaly make sense as when 1 snare end other dont stop to work. their eff take the place of the other

the first absorb pool get used then the second and third if you have 4 absorb provided they have the duration to be consumed they all working as when 1 is consumed the next one get, so they do nto stack in the strich sense of the term but they done.

**Comment by Morksezstop** [comment]
yes, absorb effects stack on top of eachone BUT on WAR you calculate fist the toughness reduction then the rest you negate from absorb and after the absorb is gone you got all ressists and armor + tougness calculated for the rest of the damage done

**Comment by Tesq** [comment]
yes and tell how is possible i mitigated 311 damage with tough+ fortitude only and of course is possible regared other scree where there is not this mitigation and of course is ni possible get 0 by  divede physic damages by 75% or 40%.

**Comment by Morksezstop** [comment]
hidden ranks + thoughness + may be Hardy Concessions
the mitigation before absorb comes only from toughness
only way to reduce the damange before mitigation are using Hardy Concessions, detaunts and all dmg decrese skills and tactics afaik
armor and resists doesnt count when you recieve dmg while you got active absorb effect on you.

If they changed something that should be written at some change logs, otherwise you are wrong

**Comment by Tesq** [comment]
there is nothing wrote cos by argument never was that way.

here in t3, i have more tough now that what i had in t4 at rr 100 cos warped flash worked a lot better than those point in tough. adn i never see once warped flesh absorb more than 1 hit NEVER it absorbed always 2 medium it in live (300-400 x hit).

Then again is not possible get 0 by division (hidden ranks/hardly concession/ taunt) wich is write cleary on the log

**Comment by ozarmidrashim** [comment]
As I said. Talk to Annaise about this. He will know about how absorption worked on the live server, and the bugtracker is not for speculation.

**Comment by ozarmidrashim** [comment]
Confirmed from forum that absorb works as intended.
