### ISSUE TITLE
[The Orb and the Tome] quest

### ISSUE THREAD

**Issue by Thrileon** [WarEmu/WarBugs#5208]
[The Orb and the Tome]  (i think this is the 3rd part of the quest)

1) Quest not working. The grave dont gives the quest item. (image 1)
2) The Grave location not showing on the map.   (image 2. my location)
3) There are 2 same NPCs who gives the quest.  (image 3)

*sorry for bad english

![thrileon_005](https://cloud.githubusercontent.com/assets/18271436/14314709/94158c30-fc01-11e5-80df-7fb3b4495bee.jpg)
![thrileon_003](https://cloud.githubusercontent.com/assets/18271436/14314715/9886c982-fc01-11e5-8d3f-8b0926db7def.jpg)
![thrileon_004](https://cloud.githubusercontent.com/assets/18271436/14314790/1c5a5044-fc02-11e5-8c35-b43825be70b8.jpg)

**Comment by Ryanfawkez** [comment]
1. Can't add item interaction for quest start yet, will have to re-write the quest to only require GO interaction.
2. Questmarker has been added.
3. Will remove the invalid spawn.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
