### ISSUE TITLE
[Cold Hard Steel] quest

### ISSUE THREAD

**Issue by Thrileon** [WarEmu/WarBugs#5209]
Cold Hard Steel    quest (working but not correctly)

This quest says  Kill Griffon soldiers for their arms and armor.. Find knight  Bidden and recover his mighty lance.
Crafted steel sword 0/4 
Biddens Mighty Lance 0/1
-  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
It looks like  ( soldiers = sword  /  Bidden = lance)
But only bidden drops Both lance and swords. (swords not correctly)
Its not big deal but Bidden is only one mob (correctly)  and you have to wait to kill him again and again. with result if 2-3 or more people trying to do the quest will be ..you know.

If you like you can make the Steel Swords to Drops from Griffon Swordsman (mob in the area, and looks more realistic to quest requirments). 
Or maybe there is mob with name Griffon Soldier? that is guarding the Bidden? Just they dont added it there? 
I dont know.i am just reporting it.  whatever you want.

*sorry for my bad english

![thrileon_007](https://cloud.githubusercontent.com/assets/18271436/14316577/7481863e-fc0c-11e5-84fa-f81bc9440fb9.jpg)

**Comment by Torquemadra** [comment]
Fixed next patch, thanks.
