### ISSUE TITLE
Guild roster display bug

### ISSUE THREAD

**Issue by Keucher** [WarEmu/WarBugs#5213]
![friendo_001](https://cloud.githubusercontent.com/assets/18269594/14325848/7a9745c6-fc2b-11e5-8bf9-9099417b43f7.jpg)
By using the search tool I noticed this bug occured in 2015 before, but there seemed to be no up to date thread about it. We're a guild with around 30 people and every member suffers from this bug, not just me. Relog does not fix it. It started yesterday.

**Comment by Evildoor** [comment]
#1438

> but there seemed to be no up to date thread about it

Read the rules of the bugtracker.
