### ISSUE TITLE
[Servitude] quest

### ISSUE THREAD

**Issue by Thrileon** [WarEmu/WarBugs#5215]
Servitude Quest wants you to find Rusted Strongbox. 

1)There is more than one box. And those more boxes dont working. Only the real box works. the 3rd box i found works for me. maybe more up floor are more boxes.

2) Becouse the mobs can see you through walls and moving to another flour without using normal way likestairs its REALY tricky to be able do this quest. When you go near gate 3-4 mobs attacking you from inside. and when you move in Tower  3 mobs attacking you from another floor. And before you you kill them  respowns already starts. (i was 3-4 lvl higher that quest lvl and it was so tricky to able go up). So if you can move them in locations that not pullet all together or remove some of them.

*i think in the 2nd image the box i targeting is that works for me, but am not 100% sure becouse i click them to fast the 2 boxes there.

![thrileon_008](https://cloud.githubusercontent.com/assets/18271436/14329141/b88e935e-fc42-11e5-9348-b95e04161e16.jpg)

![thrileon_009](https://cloud.githubusercontent.com/assets/18271436/14329158/c95efa8e-fc42-11e5-8805-7427d32c6f33.jpg)

**Comment by Torquemadra** [comment]
They are actually different boxes even though they look the same, one is called rusted LOCKbox, the other rusted STRONGbox. I cant do anything at this point as will need to verify the other boxes use on other quests.
