### ISSUE TITLE
[Spirits for the Raven God] Quest

### ISSUE THREAD

**Issue by Thrileon** [WarEmu/WarBugs#5217]
Questmarker showing wrong location. (i mean the area on the map that showing where is the mobs).
OR the mobs spown in wrong location. (for me looks like questmarker bug)

On image 2 you can see the questmarker. But the mobs are in my location. (little more to south).

Also guys if you want to focus on *Major Bugs*  (like quests actualy not working). And not *Minor Bugs*    ( like wrong-miss Questsmarkers,  but quest working). Who can be fixed during beta or just later. And i bothering you now, let me know. 
Or you can make another button like (Minor - beta bugs (for later fix)) so i post those minor bugs there.

*Major and Minor bugs is how i call them. its not develop team call or how they think or work.
*sorry for my bad enlgish

![thrileon_011](https://cloud.githubusercontent.com/assets/18271436/14336003/7fea7358-fc68-11e5-828c-4f69cb76e61c.jpg)
![thrileon_010](https://cloud.githubusercontent.com/assets/18271436/14336005/832c109e-fc68-11e5-9b81-8bb3dae09fe9.jpg)

**Comment by Torquemadra** [comment]
All bugs are important if they are trivial they will be marked as such, if a quick fix we will get on it, just make a search to verify you are not logging an issue that has been logged before ;)
