### ISSUE TITLE
Scenario Desynching

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#5218]
Having reports of people being unable to interact with doors, unable to see other people in team, though others on the team can use the doors as normal.

Had this happen to myself just now, its almost like a soft desynch with the server.

This was occuring both before and after a server restart

**Comment by Morksezstop** [comment]
did reloadui works for that matter? Cos it was helping at certain degree for desynching before.

**Comment by Torquemadra** [comment]
not really.

Kill a guy, he respawns, comes back invisible

I pile into opposition in a reikland factory, mash them all up and no one can see me apparantly.

Only seen this today, other people complaining of it. Im clueless.

**Comment by Evildoor** [comment]
> Kill a guy, he respawns, comes back invisible

#5087

**Comment by Tesq** [comment]
this happened to my guild leader as well i was invisible for him and other ppl, regard thedoor it happened several times with talabecland outer (never the inner).
This type of things seems increasing by the last partch, it also happen seems when ressing someone and from that the bug report about AM ressing not working i think wich i also experienced

all these stuff being reported must  be linked to the same source of the problem

**Comment by ozarmidrashim** [comment]
It is important to know:

When everything disappears and doors become uninteractable, can you still use chats?

**Comment by Heyho18** [comment]
Had this happen today as well.
You can still use chat and recieve tells as well.
You even get the buffs from invisible groupmembers like chosen/kotbs auras
You can see squiq pets, but not the Squiqherder himself.
You can sometimes see some skills. For example I could see the root from the sorc, but not the sorc herself.

Hopefully it can help you track down the problem.

**Comment by ozarmidrashim** [comment]
Right. It's not a soft disconnection then, it's a problem with the ranging system.

**Comment by Heyho18** [comment]
Just played a couple of more scenarios.
Sometimes you don't see groupmembers from the beginning sometimes you do.

The key thing is that everything changes as soon people start dying and release or get ressed.

For example: On one scenario today our 2 parties got wiped except a choppa and myself. From there on i could only see him and myself.

Another time i couldn't see 3 members ( 1 Dok/2Tanks)  of my party from the very beginning of the sc. The DoK died and got ressurected by another healer. From there on i was able to see him . At some point one of the invisible tanks died, released, came back and was visible as well.

**Comment by Tesq** [comment]
happening the same of what were used for wh/we before, they get remove from the server from some ppl maybe?

**Comment by Tiggonos** [comment]
I was invisible for my groupmates after being ressed i could still tap the flags (here: Battle for Prag)

**Comment by Darishel** [comment]
This happened to multiple people in my scenario group yesterday, including me.  The marauder and me could only see two out of a larger group of enemy players.  Other times I couldn't see other friendly players in a scenario.  When someone would be rezzed, either in a scenario or in PVE, they would become invisible to their groupmates.  Reloadui didn't fix it, but dying or relogging did.

**Comment by Tiggonos** [comment]
enemies get invisible too. Pets do see them and atrack them though! perhaps helps.

**Comment by Tiggonos** [comment]
NPC in inevitable city are invisible too. (not all of them only those that also give renown i think) seems they have a similar profile then players? hope it helps to find the bug.

Video:
http://tiggo.wmp.media/sonstiges/vitus/invisiblecity.mp4

**Comment by Tiggonos** [comment]
i played solo this morning and didnt experience any invisible players own or enemy side. either bug was fixed tonight, or it has something to do with groups?

**Comment by Tiggonos** [comment]
also with group queueing bug seems gone!
