### ISSUE TITLE
[Scenario] Loss of Bolster on scenario death

### ISSUE THREAD

**Issue by ozarmidrashim** [WarEmu/WarBugs#522]
Being killed in a Scenario purges all your buffs, including Bolster and other buffs which should persist through death.

**Comment by akanieski** [comment]
This one looks important! :+1: 

I'm trying to poke around looking for the logic that handles death. I found basic logic that sets health to zero and respawns you.. but nothing that looks like logic that would persist buff status.

I'll keep looking.
