### ISSUE TITLE
Highpass Cemetery Doors unclickable

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#5220]
Was in a HP Cemetery right now where more than half the destruction team was unable to click on the doors to open them. Even if someone else clicked on it the door remained closed for the affected players.

/reloadui solved the issue for me, but others reported that it didn't fix it for them.

This issue obviously causes a big problem with this scenario if one team has the majority of their players or key roles like healers stuck inside spawn. 

Until the issue is isolated and resolved I would suggest temporarily removing the gates from the spawn area or disabling the scenario.

**Comment by Evildoor** [comment]
#5218
