### ISSUE TITLE
[Revelation] 2 Quests

### ISSUE THREAD

**Issue by Thrileon** [WarEmu/WarBugs#5221]
If you open the map in the bottom right you can see the local area quest, but those 2 quests is not visible there. With result dont showing questmarker also ( i guess). 
i am not sure what part of chain are those 2 quests,  but is one after other.(like 2&3 or 3&4).

*First Quest and Map
![thrileon_014](https://cloud.githubusercontent.com/assets/18271436/14355142/9d9b8e02-fce8-11e5-95bb-959b5d944334.jpg)
![thrileon_013](https://cloud.githubusercontent.com/assets/18271436/14355038/4ded7e56-fce8-11e5-8b1d-161b6101be86.jpg)

*Second Quest and Map
![thrileon_015](https://cloud.githubusercontent.com/assets/18271436/14357311/e32624f2-fcf0-11e5-82eb-dc2b840777f4.jpg)
![thrileon_016](https://cloud.githubusercontent.com/assets/18271436/14357371/14a9f18e-fcf1-11e5-8ef0-74c02d4af6cf.jpg)

**Comment by Ryanfawkez** [comment]
Are you sure those quest markers aren't used by a different quest? Both of those steps lack an actual quest marker, so I highly doubt they're the ones showing up near Ogrund's Tavern.

Will add quest markers for the quests.

**Comment by Ryanfawkez** [comment]
Fixed the questmarkers, also the quest rewards.

**Comment by Thrileon** [comment]
am not talking about "As Lord Tchar'zanek Demands."
The problem is for the 2 quests Revelation (both same name becouse is a chain.)
there are 2 problems.
1) they dont show questmarkers (you fix it as you say).
2) The problem is not about what you CAN see, the problem is about what you CANT see. You cant see the Quests revelation (while i have them) on the Bottom Right of the map Window (where is the quest list) . Normaly the Quest Revelation SHOULD be there like the "As Lord Tchar'zanek Demands." becouse this is the MAP for the quest.

I upload an image to explain what i mean becouse my english is terrible and realy sorry about that.

![thrileon_016](https://cloud.githubusercontent.com/assets/18271436/14362443/369282ae-fd08-11e5-806f-1b87181e2db9.jpg)
