### ISSUE TITLE
Durak's Gate PQ

### ISSUE THREAD

**Issue by ellionkeman** [WarEmu/WarBugs#5222]
Ekrund. When you are on stage 2 you can't interact with barrels of powder. And it is written - destruction - stage II.
![turngolf_099](https://cloud.githubusercontent.com/assets/18136746/14358772/27f9b2be-fcf7-11e5-99ba-46afc9644a6c.jpg)
![turngolf_100](https://cloud.githubusercontent.com/assets/18136746/14358773/27fa5c82-fcf7-11e5-92c4-489207f18f2e.jpg)

**Comment by Runescryer** [comment]
`I've also noticed that with Durak's Gate, the 'border' where Choppa kills count towards Stage 1 progression doesn't extend much past the catapult near where the Loot Box is supposed to spawn

**Comment by Soulwhisper** [comment]
Fixed PQ-Area for the following Quest.

**Comment by Kaelang** [comment]
Unsure why this was closed - I'm going to re-open in response to https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=38511.

Tested on dev and unable to interact with the Barrels of Powder.
![image](https://user-images.githubusercontent.com/60117106/82553042-357dfd80-9b5b-11ea-9f86-5825d52dc0c4.png)

**Comment by Lheana** [comment]
For information, you need to destroy directly the Lobbers by attacking them.
