### ISSUE TITLE
[NPC] Multiple named spawns in Avelorn

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#5223]
I have found multiple simultaneous spawns of several named NPC's around Avelorn:

Karineth Bloodtear: at least 3 spawns around the Arkaneth camp at 22k, 42k.
Lashtail (champ lizard): at least 2 spawns by the river north of Ch12, 5k,  42k
Sarrion Blessedbow and Mellina Warbreaker: at least 2 spawns each at Handmaidens Enclave, 13k, 23k.

I assume there is only supposed to be one of each of them alive at a time.

**Comment by Ryanfawkez** [comment]
Yes, reason for double spawns could either be related to quest objective or waypoint movement.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
