### ISSUE TITLE
Volkryth Flamecaller

### ISSUE THREAD

**Issue by gaymer77** [WarEmu/WarBugs#5225]
One thing I've noticed about the T1 PQ stages where there is a hero instead of champion is that they only take 1 dmg every time they are hit. Needless to say this makes completing the PQ impossible.  Please fix this.

**Comment by gaymer77** [comment]
Add Hralgar the Kraken to the list of only takes 1 dmg per attack

**Comment by Tyramissoux** [comment]
![dralafi_001](https://cloud.githubusercontent.com/assets/13544944/23285831/cca472ce-fa33-11e6-94fc-61049205834c.jpg)
There's definitely something wrong with that hero.

**Comment by wargrimnir** [comment]
T1 PQ Heroes are now Champions. They'll be retouched in the future to make sure they're bolstered, but there's no reason for Hero con bosses in T1.
