### ISSUE TITLE
Debolstering Stats Decreased

### ISSUE THREAD

**Issue by davidchicheung** [WarEmu/WarBugs#5226]
After hitting 14 on my Swordmaster and Marauder both lost a bunch of stat points when they were debolstered to rank 13. Most noticeable is the main attributes of that class TOUGHNESS / STRENGTH, defensive stats that were increased by items (in green) were also decreased (resistances).

Screenshots attached.
![how_000](https://cloud.githubusercontent.com/assets/699806/14370281/a20dcf6a-fce1-11e5-9023-188b2a6bb901.jpg)
![how_001](https://cloud.githubusercontent.com/assets/699806/14370284/a211680a-fce1-11e5-8f47-ea75bd52133e.jpg)
![where_000](https://cloud.githubusercontent.com/assets/699806/14370282/a211527a-fce1-11e5-886b-e4f7d39d1b85.jpg)
![where_001](https://cloud.githubusercontent.com/assets/699806/14370285/a211d498-fce1-11e5-8972-419f695028ac.jpg)
![where_002](https://cloud.githubusercontent.com/assets/699806/14370283/a2115702-fce1-11e5-8087-4cdbb7308360.jpg)
![where_003](https://cloud.githubusercontent.com/assets/699806/14370286/a213271c-fce1-11e5-8e1a-1b56b03bdd7b.jpg)

**Comment by Luth-RoR** [comment]
Working as intended; better gear/talis closer to your new level and/or with better rarity should help.
