### ISSUE TITLE
Can't Sending A Whisper Issue

### ISSUE THREAD

**Issue by letumexordo** [WarEmu/WarBugs#5227]
So, sometimes while you whispering with someone even if they are online game says "That player could not be found!" So imagine how annoying that trying to send a message over and over by writing. I just when I can't send message then I copy my whole writings even "/r" then trying to enter and send and hope it can delivering.

**Comment by Evildoor** [comment]
Possibly connected with players loading between zones (for example, going to scenarios).

**Comment by letumexordo** [comment]
But that happens so often. I think it is a bug and needs a fix. But I don't know and that issue wasn't exist on live.

**Comment by Luth-RoR** [comment]
If you couldn't send the message just try to send it again with hold shift while pressing up-arrow after 3 seconds.
