### ISSUE TITLE
Oathfriend uses global cooldown

### ISSUE THREAD

**Issue by Mezirah** [WarEmu/WarBugs#5229]
Posting for someone else. They said it currently uses a GCB when it did not on live.

**Comment by Ryanfawkez** [comment]
The ability itself shows a cooldown once applied, I'm unable to pop any other ability during this singular visual cooldown. Cannot confirm whether or not it should be this way; didn't play an Ironbreaker on live.

Another addition to this ability; it says it has a 1.5 second cooldown, but you can switch it near instantly to another target regardless. Basically the cooldown is ignored each time you re-apply the ability, be it to another friendly target or not.

**Comment by bughunterror** [comment]
https://youtu.be/tQbhRCdt7us?t=61

I found a video from live if it helps. Around 1:03 the IB uses Oathfriend, and then another ability. Looks like it has it's own separate cooldown.

**Comment by ozarmidrashim** [comment]
Also corrected for BG
