### ISSUE TITLE
[None Shall Escape Us] Quest

### ISSUE THREAD

**Issue by Thrileon** [WarEmu/WarBugs#5235]
Dont show Questmarker.

![bloodsign_000](https://cloud.githubusercontent.com/assets/18271436/14383949/e9c9e4dc-fda0-11e5-9e28-350bc84bc43a.jpg)
![bloodsign_001](https://cloud.githubusercontent.com/assets/18271436/14383951/eb8b56e8-fda0-11e5-9fb7-168c643bba03.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
