### ISSUE TITLE
Can You Provides Quite Debolstering?

### ISSUE THREAD

**Issue by letumexordo** [WarEmu/WarBugs#5238]
I meant even if we have overranked gears, talisman inside, over renown and mastery points than required you can't provide it they are debolstering too? In that way we won't get trouble with being chickened. Thanks.

**Comment by Ryanfawkez** [comment]
This is not something for the bugtracker, post it in the feedback and suggestions section on the forums. Closing.

**Comment by letumexordo** [comment]
Sorry. My bad.
