### ISSUE TITLE
[Fields of Woe] Public quest

### ISSUE THREAD

**Issue by Thrileon** [WarEmu/WarBugs#5239]
(Fields of Woe) Public quest  
stage 2 - Nordland Sergeant 0/10   

Cant Find any of them in the zone of the public quest. I kill evrything around.
i found some units on mount who maybe is those but they are out of the zone of the PQ.

![thrileon_019](https://cloud.githubusercontent.com/assets/18271436/14392691/59b54b54-fdcb-11e5-874a-bf888d460f96.jpg)

**Comment by wargrimnir** [comment]
Fully implemented next patch.
