### ISSUE TITLE
[Quest] Traditions of war pulls Gorthlack

### ISSUE THREAD

**Issue by Damiel126** [WarEmu/WarBugs#524]
The Traditions of War quest requires you to get 3 glowing crystals. These are in a cave located in the Thanalorn Forest public quest.

The quest itself is fine. The problem is when you go through the tunnel past the first pit, your presence invariably pulls the undead orc and gobbo from the endgame lair in that area - Gorthlack and Gorthlack's Buddy.
![talistan_007](https://cloud.githubusercontent.com/assets/10399547/5628287/19222cc8-95f9-11e4-872c-ff216eba0929.jpg)

**Comment by Thayli** [comment]
I moved the spawns a little so they don't interfere as much, since this is not properly fixable without NPC pathing implemented. It's still possible to aggro Gorthlack, but at least now you need to actively be hugging the wall to do so.
