### ISSUE TITLE
Chosen Glitched?

### ISSUE THREAD

**Issue by KingKaiser** [WarEmu/WarBugs#5247]
My chosen that I created today was working fine earlier.  After logging out and logging back in, whenever I throw my axe, it totally freezes up the spell at 0.0s.  In addition, when attacking specific units such as the Thorshafn Militia, and the other npcs associated with the public quest in Sturmvall.  I currently have no way of finding a fix for this, as it continues to happen with each relog.  I would also like to add that when entering the public quest area, my auras also do not work.

**Comment by ellionkeman** [comment]
Same with my AM. skills are freezing on 0,0s 
![alirtinn_007](https://cloud.githubusercontent.com/assets/18136746/14402371/703ac1da-fe3c-11e5-9628-3c4f11f9a511.jpg)

**Comment by ellionkeman** [comment]
But this happened with me only in one PQ - Norscan Longships

**Comment by Ryanfawkez** [comment]
Fixed.
