### ISSUE TITLE
Unknown window

### ISSUE THREAD

**Issue by ellionkeman** [WarEmu/WarBugs#5248]
This appeared after alt+tabbing to desktop. No idea what it is... 
![alirtinn_008](https://cloud.githubusercontent.com/assets/18136746/14402410/ad0255e6-fe3d-11e5-85f8-fdbce630d45d.jpg)
![alirtinn_009](https://cloud.githubusercontent.com/assets/18136746/14402411/ad043f0a-fe3d-11e5-980e-b5be43c8f758.jpg)

**Comment by Ryanfawkez** [comment]
Account entitlement tab. This is a packet corruption.

**Comment by Evildoor** [comment]
#1810
