### ISSUE TITLE
Multiple mob spawns

### ISSUE THREAD

**Issue by Nekkma** [WarEmu/WarBugs#5250]
While trying to do the epic quest chain "Inevitable power" we noticed that multiple mobs spawned as one in PQs. We noticed it in all PQs that you pass in the quest chain. Example below:
![nekkkma_001](https://cloud.githubusercontent.com/assets/17377105/14402571/5a8e48c2-fe3a-11e5-84ea-d5f44bf46ae4.jpg)

**Comment by Ramgarr** [comment]
Same issue in the temple of change for the Empire epic quest chain (Cleansing an Empire).
It makes the quest impossible to do

**Comment by Sayce78** [comment]
Some of the Norse Sea Dog spawn points in the PQ The Norse are Coming (Empire, Ch 2) have multiples. Not all are multiple spawns and those that are seem to be only 2. Interestingly, it looks like only the shirtless males are spawning in duos.
