### ISSUE TITLE
ic - merchants not showing on minimap

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#5252]
see screenshot

![smooshi_003](https://cloud.githubusercontent.com/assets/13809443/14403054/b949a844-fe48-11e5-8c7a-6c8af8672006.jpg)

**Comment by Kaelang** [comment]
![image](https://user-images.githubusercontent.com/60117106/82226471-70dfb880-991e-11ea-90bd-c6e1035a237d.png)
This has since been fixed.
