### ISSUE TITLE
Stacking NPCs in PQs

### ISSUE THREAD

**Issue by LittlefishSail** [WarEmu/WarBugs#5253]
Sounds a lot like the bug detailed in 5250 a couple of hours ago, but on Order side.  Trying to complete the Epic Quest Control of an Empire, final stage is at the Unterbaum PQ.  Can't even get through the front gates, as there are 6/7/8? mobs stacked in the same spawn location just inside the gates, who happily annihilate you almost immediately.  Tried the same sequence using a RR40 character who'd already soloed this, and was annihilated again almost as rapidly.  Thanks for the help :)

**Comment by Thorgrumm** [comment]
Just to add info to this, each time you kill an npc in stage 1 of the PQ at Unterbaum Castle he respawns as two stacked npc's, kill these and he returns as four stacked and so on. If you complete stage one, the second and third stages play out fine with no npc stacking. When the PQ resets after completion, all npc's are single, kill one and he respawns as two and so on.

**Comment by wargrimnir** [comment]
Please include the chapter and faction in future tickets regarding PQ's. This is Empire Ch14, for example.

Also, it appears the duplicate spawns were removed at some point. Needs confirmation.
