### ISSUE TITLE
The boundless "mirroring"

### ISSUE THREAD

**Issue by popolacarotte** [WarEmu/WarBugs#5256]
Well, I opened the Auction Hall to buy an Axe for my Slayer Reroll.

And what a surprise.

Just take a look at what I found

**Dwarf 2H**
http://www.hostingpics.net/viewer.php?id=185411Dwarf2H2.jpg

Take a look at this beauty, badass hu ?

I also found this one, 
http://www.hostingpics.net/viewer.php?id=526169Dwarf2H1.jpg

But we already know this one right ?

**Orc 2H**

http://www.hostingpics.net/viewer.php?id=501004Orcs2H.jpg

Not really the same since the Dps is shittier.

Can somebody explain why such difference ? Or why I NEVER found the "TrollSplitter" mirror ?
Or fix this joke ? I don't know.

**Bonus - For shit and giggles
White Lion 2H**

http://www.hostingpics.net/viewer.php?id=500057WL2H.jpg

Outclassing the Trollsplitter in many way, for some reasons...
2.9 Speed. The same as a 1h axe. Wow.

No wonder why they shit on every one.

**Comment by Ryanfawkez** [comment]
Again, this is not a bug. I'd advise you to stop copy pasting your forum thread replies to the bugtracker.
