### ISSUE TITLE
Deathwing vulture mob listed as being a Giant Bat instead of a vulture - Still drops Bat items.. Screenshots in comment section.

### ISSUE THREAD

**Issue by jaxci12** [WarEmu/WarBugs#5259]
Its nothing major, I'd just like to mention that a mob called Deathwing has the appearance of a vulture, but if you kill it, it will count as a Giant Bat. It's around the coordinates (28k, 38k) in Norsca. The surrounding vultures might have the same bug, as they aren't giving you the bestiary unlock for killing a vulture.
![1e5f327799587c123aa1445d9cb6e6bf](https://cloud.githubusercontent.com/assets/18364473/14403564/3e620e78-fe5c-11e5-81fc-1b26afd38147.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch. Thanks for the report.

**Comment by jaxci12** [comment]
Just glad I could help :)

**Comment by jaxci12** [comment]
Back with more Deathwing action.. I tried just killing it once more and then some "Bat Guano" dropped, pretty sure that's not how it's meant to be :) 
![bat guano](https://cloud.githubusercontent.com/assets/18364473/14403594/755499d0-fe5e-11e5-965b-11862d9f9fa5.jpg)

**Comment by jaxci12** [comment]
![moreguano](https://cloud.githubusercontent.com/assets/18364473/14403615/91df7d9e-fe5f-11e5-949d-58186cd683bf.jpg)

**Comment by Ryanfawkez** [comment]
item drops are dependent on subtype, as long as the mob remains a bat by the database info it'll drop bat-related items. Since it's now changed to a vulture for the next patch it'll drop vulture-related items.

**Comment by jaxci12** [comment]
This picture was taken after the patch which was just made

**Comment by Evildoor** [comment]
> Fixed in next patch.

does not means that the patch was deployed immediately.

**Comment by jaxci12** [comment]
Yea, I figured. Sorry about that.
