### ISSUE TITLE
dead players still clickable and stand

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#5260]
looks like killed players still stand and are clickable dispite being dead. (assumption: untill they hit release).

**Comment by Tiggonos** [comment]
here is a video of it:

http://tiggo.wmp.media/sonstiges/vitus/deadmanstanding.mp4

**Comment by Tiggonos** [comment]
same with mobs

**Comment by Ryanfawkez** [comment]
Reminds me of that old bug that showed a ghost player at the Land of the Dead Colossus. Sometimes it was only one, sometimes there were two to three more.

**Comment by sioding** [comment]
**Thanks for the report.** Since there is no confirmation, i will close this issue now. Please make sure to follow the bugtracker rules which you can find here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)
