### ISSUE TITLE
Multiple mobs spawn on same location

### ISSUE THREAD

**Issue by Clawfinger84** [WarEmu/WarBugs#5262]
Knightly riders PQ in Hazelhof ch11 Chaos.

The more i pull, the more mobs replace the mob i killed. there are now like 20 knights standing in the same location. Bodypull and you're dead

**Comment by Clawfinger84** [comment]
[URL=http://s122.photobucket.com/user/Clawfinger_photos/media/Klotpelle_009.jpg.html][IMG]http://i122.photobucket.com/albums/o253/Clawfinger_photos/Klotpelle_009.jpg[/IMG][/URL]

**Comment by Evildoor** [comment]
#5250
