### ISSUE TITLE
Grimmenhagen Barrows

### ISSUE THREAD

**Issue by ellionkeman** [WarEmu/WarBugs#5266]
there's a sarcophagus inside it. when you put cursor on it it looks like a hand to interact but nothing happens upon clicking on it. I don't know what should happen. On early live war there was a champion. I don't remember what happened on late live sorry 

![vatnica_000](https://cloud.githubusercontent.com/assets/18136746/14404361/23d26b8c-fe7c-11e5-945f-82b386437234.jpg)

**Comment by NorKalli** [comment]
Added Eoldred Nightbane mob, however not scripted to come out of coffin yet.

**Comment by Sinrman** [comment]
Killing Eoldred Nightbane gave me "Encounter a Snotling" Tome unlock.

**Comment by Lheana** [comment]
The Coffin will be corrected with next patch. Eoldred Nightbane will spawn when clicking on the coffin, and he will correctly count as a Wraith.

**Comment by Natherul** [comment]
should be fixed as of today
