### ISSUE TITLE
North Chrace Dark Elf

### ISSUE THREAD

**Issue by DiamondExplosion** [WarEmu/WarBugs#5267]
Hi,
When you kill a white lion near Gon'Seraph an exception is throw : FormatException was thrown from ParseUInt32.
DiamondExplosion

**Comment by Evildoor** [comment]
Exact mob name. "White Lion"?

**Comment by DiamondExplosion** [comment]
Yes see here : 
![war 2016-04-10 08-25-48-88](https://cloud.githubusercontent.com/assets/18140308/14408455/0aca1714-fef6-11e5-9c9a-487075e75f4a.png)

But there is also a problem with the others near Dreamshade Forest (maybe the same in database) :
![war 2016-04-10 08-29-05-74](https://cloud.githubusercontent.com/assets/18140308/14408472/8db9eafa-fef6-11e5-87b2-3fd066ab206e.png)
