### ISSUE TITLE
Officer's phial of adrenaline

### ISSUE THREAD

**Issue by ShanellRoR** [WarEmu/WarBugs#5270]
![todd_050](https://cloud.githubusercontent.com/assets/17355822/14407091/35f7c804-fec5-11e5-9d23-c10166976c1d.jpg)
It is said, that it restores 112 Ap, but in fact it's only 82.

**Comment by taccr** [comment]
This looks like a more general problem with AP potions.
They all seem to give 82, no matter what you use.
I just tried it with r10 Lesser Potion of Invigoration and r1 Recruit's Warming Potion - Always 82.

**Comment by NorKalli** [comment]
long ago fixed
