### ISSUE TITLE
bugg

### ISSUE THREAD

**Issue by Mortuum** [WarEmu/WarBugs#5272]
the quest invisible power is bugged it stand each other countless mobs and there are 2 who I only a kille

**Comment by Evildoor** [comment]
Description not clear.

**Comment by Nekkma** [comment]
I assume it is the same bug I posted about in #5250 

The last stage was very difficult to do as the stack of mobs instagibbed you. I ran with shieldwall and aaggroed everything while my healer friend ran behind and ressed me when he got passed them.

**Comment by Evildoor** [comment]
No clarification, closing.
