### ISSUE TITLE
Always Critically Hitting Rats!

### ISSUE THREAD

**Issue by letumexordo** [WarEmu/WarBugs#5273]
I don't know if it's bug but someone told me Tier 3 Rats are bugged because they always hitting critical damage! And they kill me with 2 hits even if I'm Rank 31 Witch Hunter. I can't do solo any!

**Comment by ozarmidrashim** [comment]
Closed:

1) "I don't know if it's bug". You must know, and provide proof.
2) Yes, champ rats of level 39 should be killing a 31 Witch Hunter in two hits. You're not meant to be soloing them.

**Comment by letumexordo** [comment]
1. Are you kidding me? If I don't know if it isn't bug then I shouldn't report this bug? What kind of joke is your community? And no, proving anything is not my job, it's your job finding out bugs and fix it. I'm supporting you by reporting bugs and you're saying I should prove it? You're so funny. I think you should going to comedy show and being comedian. lololol.

2. You might be right. Because they are Champion and 8 rank above.
