### ISSUE TITLE
[Guild] Can't search for guild

### ISSUE THREAD

**Issue by Scrilian** [WarEmu/WarBugs#5275]
Most likely a QoL thing. 
You should be able to search for guilds while you are in one - easy to find possible alliances, new members of dying guilds, etc.
![gaziraga_236](https://cloud.githubusercontent.com/assets/16498708/14409009/03523b02-ff13-11e5-8709-9defd3312513.jpg)

**Comment by xyeppp** [comment]
This used to work many months ago, got broken with some random update.

**Comment by Evildoor** [comment]
#4446?

**Comment by Scrilian** [comment]
Seems like it with Search button being not even click-able.

**Comment by Lileldys** [comment]
Can search fine when out of a guild, but when in a guild it doesn't work.
