### ISSUE TITLE
Multiple slavering fronds

### ISSUE THREAD

**Issue by DyneLarsen** [WarEmu/WarBugs#5276]
In the High Pass PQ Foetid Plains, there are multiple slavering fronds in a single spot.
![war 2016-04-10 11-34-57](https://cloud.githubusercontent.com/assets/11929822/14409357/edcdd9f0-ff10-11e5-9599-d9f2c8fc5442.png)

![war 2016-04-10 11-35-02](https://cloud.githubusercontent.com/assets/11929822/14409358/f715b5be-ff10-11e5-8477-ae02af5714a0.png)

**Comment by Ryanfawkez** [comment]
#5250
