### ISSUE TITLE
Honorable Deceit  Bug  cannot complete.

### ISSUE THREAD

**Issue by VoxMortis** [WarEmu/WarBugs#5279]
Me and my friend were PVE-ing for an hour and a half  once we had to go to shaphary  the quest dissapeared for me  then i went back to check if i dint get the quest , but it told me i had to do it all over again wtf dudes  I wont sit for 1 and half hour again  thought  this. Can i start from the point that the quest bugged somehow ??? if not gg this game

**Comment by Evildoor** [comment]
This problem (quests getting reset) is known and has no solution so far. Also, the bugtracker is not a place where you can ask for personal help, it's a place for reporting bugs so that they can be fixed.
