### ISSUE TITLE
Chaos chapter 4 influence/quest problem (PQ related)

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5280]
Chaos chapter 4 influence cannot be obtained because non of the PQs is working and not a single mob is giving influense after being killed. This also spawn another problem - quest which is must be opened since player gain 2/3 influence in chapter (the one with +1 lvl up scroll in reward) cannot be open and completed. I realy miss that lvl-up scroll as nostalgic relic from the past :'(

**Comment by Ryanfawkez** [comment]
The insta-level scroll quest isn't available, no matter how much influence you may have in Chaos chapter 4. Also, we cannot tie quest obtainability to reaching a certain amount of influence yet.

**Comment by wargrimnir** [comment]
All Ch4 PQ's are working.
