### ISSUE TITLE
Nurgling Mesh Idle

### ISSUE THREAD

**Issue by DoubleBoxGames** [WarEmu/WarBugs#5281]
I found this little guy in a PvP zone (queued). Just thought I should show it. Not sure why it was there, but I could not click on it, or interact with it.
![azroghast_000](https://cloud.githubusercontent.com/assets/7363810/14410871/a3929fdc-ff07-11e5-8e5b-dac3e095b21f.jpg)

**Comment by Evildoor** [comment]
#4325
