### ISSUE TITLE
guilg join and kick from guild doesnt alert with message for all members

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5282]
When somebody join guild and when i kick somebody from guild there should be message in chat that "character name" join guild or kick out from guild. That message should be seen by all guild members.

**Comment by Evildoor** [comment]
May be related to #577

**Comment by MaxHayman** [comment]
@sioding this should work

**Comment by sioding** [comment]
tested on my own - works fine
