### ISSUE TITLE
guild vendor's goods doesnt work (Chitin Shard,Viper's pit,Alchemy)

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5286]
Any of 25lvl potion ingridients buyed from guild vendor in Viper's pit doesnt work, instead after i try to set them into craft window it bugs out and none of crafting materials doesnt work until reloading.
  Those are tested:
Preserved Brittle Chitin Shard (25 lvl ingridient for armor potions) 
Preserved Anorexic Bat Wing (25 lvl ingr for absorb potions)
Preserved Carious Chimerical Claw (25 lvl thorns pot. ingr.)
Bottled Runny Rat Spittle (25 lvl glue bomb pot. ingr.)
  As i understand absorb,thorns and glue bomb pots are'nt implemented in the game yet, but at least armor pots should working.

**Comment by stortzm** [comment]
Preserved Bat Wings are also not working (apo lvl 175 shield pot main )

**Comment by valkeera** [comment]
Neither does lvl 75 Preserved Fractured Chimerical Claw.
