### ISSUE TITLE
High Pass Magi Mob Pile-up

### ISSUE THREAD

**Issue by Tuidog** [WarEmu/WarBugs#5289]
I've found multiple of the same mob which spawn on top of each other. They are standing next to a campfire, one stack being two **Magi Seers**, and the other being five **Magi Destroyers**. All are close to the map coordinates 14400,51100. Interestingly this bug did not exist a week or so ago when I last came to this area of the map.

![bug report](https://cloud.githubusercontent.com/assets/2540606/14415156/fd8ae910-ff69-11e5-982a-cd3fd881022b.jpg)

**Comment by Ryanfawkez** [comment]
#5250
