### ISSUE TITLE
Bolster Re-Application Upon Level Up

### ISSUE THREAD

**Issue by Topologic** [WarEmu/WarBugs#5290]
Bolster is either not reapplying itself, or in some cases is reapplying a DIFFERENT Bolster.

In my experience earlier, I've had Bolster fall off and stay off on my IB as I leveled from 2 to 3, but on my Zealot, when I leveled from 10 to 11 in a scenario, the level 26 Bolster was misapplied to me.

I am certain that these are not mere UI bugs, as my durability changed markedly in each case.

**Comment by Evildoor** [comment]
#1646
