### ISSUE TITLE
Can't Entering Into Game!

### ISSUE THREAD

**Issue by letumexordo** [WarEmu/WarBugs#5291]
When I click "PLAY" button the map loading but after than that I went into character selection again. And after than that I can't even click once again that "PLAY" button. What the hell is wrong with your servers?!

P.S. After bunch of tries, I be able to entering into the game. But I think the game need strong fix!

**Comment by Evildoor** [comment]
Read the rules of the bugtracker.

**Comment by letumexordo** [comment]
Isn't it a bug? Even if it isn't, it is an issue!

**Comment by Evildoor** [comment]
http://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

> Isn't it a bug? Even if it isn't, it is an issue!

Yes, this problem is not a bug. And this place is called _BUG_tracker for a reason.

**Comment by letumexordo** [comment]
No, it is a bug. So I can't entering into the game even if my account's status is okay. Then it is a bug. And thus here is proper place for report this bug.
