### ISSUE TITLE
Standard (guild banner) doesnt work

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5292]
Any of standard bonuses, additional abilities, buff icons doesnt work. 
I set up to one standard bonuses for: 15% strength, 15% armor, 15% reknown
Using command .getstats and with or without standard my stats are identical.
When i carry standard there are should be buff icons below my character's lifebar
When i carry standard there are should appear additional abilities, like set standard to the ground, or aoe knock back which is granted on 12 lvl of the guild.
![2](https://cloud.githubusercontent.com/assets/18102127/14426062/1a06b2ac-fffd-11e5-8d2e-fdffb1390d15.png)
![3](https://cloud.githubusercontent.com/assets/18102127/14426063/1a075612-fffd-11e5-8bcc-2d9657e39eed.png)
![4](https://cloud.githubusercontent.com/assets/18102127/14426065/1a0bc8e6-fffd-11e5-8384-2d4532c521dd.png)
![5](https://cloud.githubusercontent.com/assets/18102127/14426064/1a09032c-fffd-11e5-83d6-353a337b2390.png)
![6](https://cloud.githubusercontent.com/assets/18102127/14426061/1a0651e0-fffd-11e5-96de-8358073128fd.png)

**Comment by ozarmidrashim** [comment]
Bugtracker is not for unimplemented features
