### ISSUE TITLE
Cleansing an Empire is bug

### ISSUE THREAD

**Issue by Tecet** [WarEmu/WarBugs#5293]
Hi,

Epic quest Cleansing an Empire is buged. 

At 3th step in chain in Temple of Change, Zealots at entrance have multiple spawn, killed like 50 and dosnt looks like path can be clear there should be just 2 on each side of door.

Chain cannot be complete as require enter to temple and Im getting instant killed if going anywhere close. 

Fix please

**Comment by Evildoor** [comment]
#5250
