### ISSUE TITLE
proc on influence reward

### ISSUE THREAD

**Issue by jonyjones** [WarEmu/WarBugs#5295]
Some t2 weapon inf reward should have proc. Some with only damage others with movement speed slow like this :
http://warhammeronline.wikia.com/wiki/Fangbreaker_Edge DOK
http://warhammeronline.wikia.com/wiki/Fangbreaker_Skull zealot
http://warhammeronline.wikia.com/wiki/Karaz_Skinflayer zealot
http://warhammeronline.wikia.com/wiki/Skull_of_Thunder zealot
http://warhammeronline.wikia.com/wiki/Spite%27s_Skinflayer zealot

**Comment by Torquemadra** [comment]
We know. Not currently implemented.
