### ISSUE TITLE
RvR Quests not giving Influence bonus points.

### ISSUE THREAD

**Issue by DavidWAAAGH** [WarEmu/WarBugs#5298]
Hello:

I just realized that RvR quests dont give you Influence when you finish them.

As you turn them in, a logo in the screens shows " You've obtained an influence bonus" but there is not bonus, I turn them in while I have my Tome open, and it just showed the same amount of Influence points that I have.

**Comment by Evildoor** [comment]
Visual bug, they should not give influence, but this text is displayed for some reason. #1573
