### ISSUE TITLE
sh moral 1 ap reduce to much

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#5302]
squiq herder morale mushroom wrap should reduce ap costs by 50%. it reduces (at least) plink from 38 to 9 AP though. (looks like its a combination of the 35% reduce ap tactic). without any tactic it correctly reduced ap from 40 to 20 ap.

**Comment by Tiggonos** [comment]
ok it ads up 50% and 35% and reduces by 85%. dont know if thats correct but for me it should be

60 ap for 35% = 39
39 ap for 50% = 19,5

**Comment by ozarmidrashim** [comment]
What you see on the client is law.

**Comment by Tiggonos** [comment]
i understand. (not the mythic logic, adding up % is just a no go ^^).
