### ISSUE TITLE
Morale sometimes becomes unavailable in big fights

### ISSUE THREAD

**Issue by kaey** [WarEmu/WarBugs#5308]
Video: https://www.twitch.tv/koolker/v/59491009
At 1:10 you can see that first morale is not available and you can't use it by pressing hotkey.
It unbugs when you use any other morale or wait out of combat until morale level falls below the bugged one.
Never seen it happen in small fights (like scenarios).

**Comment by kaey** [comment]
Don't know if related, but morale abilities can also fail start a cooldown after being used. In the screenshot, only the first morale I used went on cooldown.

![rammaq_000](https://cloud.githubusercontent.com/assets/3503165/14476720/2fa19562-0112-11e6-9b42-242d7827987a.jpg)

**Comment by ozarmidrashim** [comment]
These are both client issues.
