### ISSUE TITLE
Slideshow like lags in big fights

### ISSUE THREAD

**Issue by kaey** [WarEmu/WarBugs#5309]
Same video: https://www.twitch.tv/koolker/v/59491009
When big fight starts (in video it's around 1 min) game starts slideshow.
It begun after some patch, maybe 2 month ago, I don't really remember, it was all fine before that.
It's not a PC/windows/OBS/twitch issue, everyone else in my warband experiences the same.

**Comment by Luth-RoR** [comment]
Is this still a problem?
