### ISSUE TITLE
Respec is possible with any NPC

### ISSUE THREAD

**Issue by kaey** [WarEmu/WarBugs#5311]
1. Install addon Anywhere Trainer
2. Talk to any NPC (by right clicking)
3. Open anywhere trainer
4. Respec
5. ...
6. No profit

**Comment by Landaren** [comment]
This is true, but does it really need to be fixed?

This is more of an upgrade to the quality of life for the player base leaving it as is.

**Comment by sioding** [comment]
Fixed with patch from 28.03.2018
