### ISSUE TITLE
Chosen crashes a few seconds after logging in.

### ISSUE THREAD

**Issue by Theyseememaruading** [WarEmu/WarBugs#5313]
I was wanting to level my chosen a bit more, but for some reason my client kept crashing after a few seconds. Sometimes i didn't get to move, sometimes i did. I logged on to a different toon and didn't have the problem anymore. My chosen is rank 4, rr0, and at the Chaos Chapter 2 PQ. Any help would be great. EDIT: I logged to another toon and that seems to have fixed the problem. Still unsure of what caused it before i switched toons.

**Comment by Evildoor** [comment]
Individual problem with character, use forums (support section).
