### ISSUE TITLE
Gale Runner Dreadaxe

### ISSUE THREAD

**Issue by shibirian** [WarEmu/WarBugs#5315]
I assume this item is randomly generated...right?
![anthyr_010](https://cloud.githubusercontent.com/assets/17605387/14474394/2388eb6e-00fd-11e6-8eab-94c542b186d1.jpg)

**Comment by genisaurus** [comment]
No. What is actually being reported here? The stats are in-line with records we have of other Gale-Runner weapons we have from live. http://www.arsenalofwar.com/items/Destruction/Gale-Runner's%20Choppa

**Comment by shibirian** [comment]
It's a Chaos drop for Order.

That shouldn't happen, right?

**Comment by genisaurus** [comment]
Ah, yes, that would be a bug.

**Comment by wargrimnir** [comment]
Added career req, although I don't think this would still be an issue anyway.
