### ISSUE TITLE
Ignite hitting for 83k dmg

### ISSUE THREAD

**Issue by Kallahh** [WarEmu/WarBugs#5319]
Just a few minutes ago, in Stoneclaw Castle a 33 BW hitted my Shaman for that amount of dmg in the 1st tick of ignite.

Proof: 
![ignite](https://cloud.githubusercontent.com/assets/16372162/14476379/b44a53ea-0107-11e6-89ef-acd78a13dc8a.png)

**Comment by ozarmidrashim** [comment]
This is a variant of the DoT unusual crit damage problem, which has an open report.
