### ISSUE TITLE
[Shadow Warrior] VoN

### ISSUE THREAD

**Issue by Siegureboy** [WarEmu/WarBugs#532]
VoN drains TONS of AP when used. I do not know how much exactly, though it seems like it drains the amount of AP the hotbar tooltip states, then it just continues to drain it AP/second for a second. Want to say its ~150-200 AP that it drains.

**Comment by Thorgatin** [comment]
According to WSCT it drains exactly 35 AP for me. There was an issue like the one you describe, before the last patch.
