### ISSUE TITLE
Lost Locket

### ISSUE THREAD

**Issue by Calehdir** [WarEmu/WarBugs#5320]
The Item Lost Locket which you get from Wart Trolls for the tome entry [Gone But Not Forgotten](http://warhammeronline.wikia.com/wiki/Gone_But_Not_Forgotten) is not working.

You should right click the item to get the entry + a title, The Undaunted.

**Comment by Lheana** [comment]
The "Lost Locket" item now provides the title "The Undaunted", but not the unlock "Gone But Not Forgotten".

**Comment by Ryanfawkez** [comment]
Added 'Gone But Not Forgotten' on the Wart Trolls. Had 'Battered But Not Forgotten' before, which is a Bloodletter unlock.
