### ISSUE TITLE
Witch Hunter finishers bug

### ISSUE THREAD

**Issue by Ktaan** [WarEmu/WarBugs#5321]
Currently you can both parry and dodge finishers of the Witch Hunter (since they range ability).
But you cant dodge Whitch Elf's finishires (but they are all range too).
 This screenshot shows this (its on russian though)
https://i.yapx.ru/BCgJ.jpg

**Comment by Lileldys** [comment]
It show a dodge (because they used to be a ranged attack, using ballistics), but its a parry check.

**Comment by Evildoor** [comment]
Lileldys is correct, it's just visual and intended.
