### ISSUE TITLE
Rapid Fire bugged

### ISSUE THREAD

**Issue by shibirian** [WarEmu/WarBugs#5322]
1) Skirmisher Stance - Rapid Fire cannot be used while moving (it is immediately cancelled)

2) At Keep Door - if used with "Unshakable Focus", "Vengeance of Nargayth", and "Steady Aim"  Rapid Fire is either:
a) not activating at all - takes three or four tries before it activates
b) cancelled early one after half the time or so.

The effects are reproducable and at least 2SW had it so far.

**Comment by Evildoor** [comment]
Uh, what? Rapid Fire was always a stationary skill.

**Comment by Tiggonos** [comment]
as on 2) its a problem with all channeled abilities, i encountered it on my bw (withering heat) and on my squiq (lotsa arrers). sometimes it works sometimes not or only after some time.

**Comment by shibirian** [comment]
Evildoor, according to Skirmisher stance description it should be mobile? I never played skirmisher on live but it should? (You're practically playing Legolas, though....)

**Comment by Evildoor** [comment]
> according to Skirmisher stance description it should be mobile

What? The only thing about shooting on the move that i can see in Skirmisher Stance's description is "You gain the ability to autoattack while moving while in this stance".

**Comment by Thorgatin** [comment]
This ability never worked on the move.
Clarification for the OP: autoattack damage is the white damage in the combatlog; it happens automaticaly in the background. Ability damage is something else.

**Comment by Evildoor** [comment]
No response, closing.
