### ISSUE TITLE
Keep Doors bugged (or LOS)

### ISSUE THREAD

**Issue by shibirian** [WarEmu/WarBugs#5323]
Magical damage is going through Keep and Postern doors - not physical.

This includes AOE.

Magical non-aoe dmg needs to be cast first. For example a ray continues through a Postern door if the target moved through it.

Effect is reproducable.

**Comment by ozarmidrashim** [comment]
If you're referring to, for example, finishing your cast of Radiant Lance when the player is outside of the keep door and the bolt still travelling to hit them when they enter the keep, it's not a bug.

**Comment by Morksezstop** [comment]
I think he refer to AM searing touch that keep the channel effect even when your target go tru doors

**Comment by shibirian** [comment]
Searing touch: That is one effect I witnessed today to happen in Badlands. So that's regular. Good to know.

The other: AOE went through keep doors today. As a destro BG to my question confirmed it wasn't physical dmg but magical.

Mobs were pulled through keep doors, too, today.

**Comment by Vayra** [comment]
> Mobs were pulled through keep doors, too, today.

Mobs are still ignoring all LoS. The patch only addressed player abilities.

**Comment by shibirian** [comment]
Ok, so the mobs are the one thing. The AOE happened anyway...

**Comment by Kaelang** [comment]
PbAoE / AoE spreads work from the person / ground they target, regardless of LoS.

Please re-open if you still believe this to be a bug on more updated versions of RoR.
