### ISSUE TITLE
[Sense of Style] Quest

### ISSUE THREAD

**Issue by Thrileon** [WarEmu/WarBugs#5326]
I cant find any clickable Harp. There is a Harp in the mindle of the village but is not clickable.

![bloodsign_002](https://cloud.githubusercontent.com/assets/18271436/14479870/c6e06b92-012b-11e6-90f3-e4c24011862a.jpg)

**Comment by Ryanfawkez** [comment]
You need to find Elohir Dawnbreak's Harp and interact with it to progress the quest. It works as intended.

**Comment by Thrileon** [comment]
my bad. realy sorry
