### ISSUE TITLE
Mob archer Spown inside tree.

### ISSUE THREAD

**Issue by Thrileon** [WarEmu/WarBugs#5327]
In this Location Mob Archer Spwn inside a tree and hiting you from there.
Location: The Blighted Isle
Cords: 9737, 29556 

In following images you can see the Target Ring where is the archer inside the tree. And the location.
![bloodsign_004](https://cloud.githubusercontent.com/assets/18271436/14480136/95638dbc-012e-11e6-8789-d9586ed0baf1.jpg)
![bloodsign_005](https://cloud.githubusercontent.com/assets/18271436/14480137/96ff4a9e-012e-11e6-8c0b-c1f2cb30f067.jpg)

I Touching the Tree on this image. 
![bloodsign_006](https://cloud.githubusercontent.com/assets/18271436/14480139/99744a40-012e-11e6-9654-db12322c78c2.jpg)

And a distance image to locate the tree easier.
![bloodsign_007](https://cloud.githubusercontent.com/assets/18271436/14480304/41113a6e-0130-11e6-8d80-47d6096984fe.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
