### ISSUE TITLE
[NPC] Volruc Kinslayer - Double spawn

### ISSUE THREAD

**Issue by Thrileon** [WarEmu/WarBugs#5328]
![bloodsign_008](https://cloud.githubusercontent.com/assets/18271436/14492849/af113ff0-018a-11e6-8d04-9852c56c9e37.jpg)

on my location
![bloodsign_009](https://cloud.githubusercontent.com/assets/18271436/14492893/efecbf40-018a-11e6-921c-8c5d50cc4776.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
