### ISSUE TITLE
Plaguewood Troll Teleportation

### ISSUE THREAD

**Issue by DoubleBoxGames** [WarEmu/WarBugs#5329]
A small bug. 
Whenever I knock down a Plaguewood Troll with the Chosen's "Repel" Ability, there is a good chance that the Troll teleports randomly away from me, but typically behind.

**Comment by DoubleBoxGames** [comment]
On closer examination, it occurs when the Troll attempts to move behind me, and the teleportation can be predicted as the same direction it was moving.

**Comment by Evildoor** [comment]
#5034
