### ISSUE TITLE
Orb of Cadaith not working - The Blighted Isle

### ISSUE THREAD

**Issue by Damiel126** [WarEmu/WarBugs#533]
The Orb of Cadaith in the Shining Guard outpost in the Swale of Miralei (The Blighted Isle, 39.5k,37k) is supposed to teleport you to its counterpart in Lacorith (The Blighted Isle, 35k,36k).

It is supposed to work by right clicking the orb, which was I think a 3 second cast, and then you teleport to the other one. It avoids having to run all the way around Adunei to get down to the swale and vice versa.

Low impact right now as falling does no damage so you can just jump down.
![aelthys_001](https://cloud.githubusercontent.com/assets/10399547/5679966/9165d2a8-985a-11e4-9314-a360de4f79ea.jpg)
![aelthys_002](https://cloud.githubusercontent.com/assets/10399547/5679967/916b15ec-985a-11e4-99a6-7c4faa31e74f.jpg)

**Comment by Elvenalthur** [comment]
This is still an issue on live. Can comfirm.

**Comment by Lheana** [comment]
The Orb of Cadaith in Lacorith will now teleport players to the other Orb of Cadaith next to the Order PQ 'Swale of Miralei', and vice versa.

**Comment by sioding** [comment]
Fixed with patch from 1.12.2017
