### ISSUE TITLE
(Telathor Darkthorn) NPC 2 Spowns.

### ISSUE THREAD

**Issue by Thrileon** [WarEmu/WarBugs#5330]
Telathor Darkthorn npc Questgiver 2 spowns. In Akranas Storm.

![bloodsign_012](https://cloud.githubusercontent.com/assets/18271436/14493867/8d5b4c56-0190-11e6-91ec-234cbd57eac2.jpg)
![bloodsign_011](https://cloud.githubusercontent.com/assets/18271436/14493869/8e9c0e52-0190-11e6-8632-2565d6c7a1ed.jpg)

**Comment by Evildoor** [comment]
#4797

**Comment by Thrileon** [comment]
ah ok. and i was ready to post more dublicated npcs ;)
