### ISSUE TITLE
PQ: The Norse are Coming!

### ISSUE THREAD

**Issue by shibirian** [WarEmu/WarBugs#5333]
1) Defender Corpses do not count for Quest
2) PQ is shown as Destruction (it is for Order)
3) Single Coprses can be clicked multiple times for Quest (so one corpse can be clicked five times and it counts)

**Comment by Evildoor** [comment]
3 is a general issue reported elsewhere.

**Comment by Soulwhisper** [comment]
4)Interacting with Slain Defenders in Stage 1 counts them as Norse Sea Dogs.

**Comment by StaH84** [comment]
Issue:
- [ ] Not sure If it's a bug but I was hitting Last Stage Hero for 1dmg with every hit.

**Comment by Soulwhisper** [comment]
Interacting with Slain Defenders in Stage 1 counts them as Norse Sea Dogs and breaks the counter!
