### ISSUE TITLE
Nordland - Water bucket unlock

### ISSUE THREAD

**Issue by shibirian** [WarEmu/WarBugs#5336]
1) Does not work
2) Water bucket is floating the air.

**Comment by Ryanfawkez** [comment]
This item is part of a quest, there is no ToK unlock associated to it according to Google.

**Comment by Eusebeus82** [comment]
If we're thinking of the same thing, this used to be an unlock as part of the Missions of Mercy pursuits (?) section of the tome. You had to collect the water and deliver it back to a soldier on the road, who made comments about being thirsty. Its the sort of multipart unlock that isn't in the scope of fixing without a work around, I think.

**Comment by Luth-RoR** [comment]
http://warhammeronline.wikia.com/wiki/Waterbearer
