### ISSUE TITLE
KotsBs - Stand Strong

### ISSUE THREAD

**Issue by shibirian** [WarEmu/WarBugs#5339]
Does only activate after multiple tries over time; actually it activates after showing 4s countdown then a couple of times.

With Press Attack it only works if activated first and then PA next.

Tested with lvl5 knight.

**Comment by taccr** [comment]
Works perfectly fine on my kotbs. Are you sure you are not having latency issues?

**Comment by shibirian** [comment]
That could be!

**Comment by Evildoor** [comment]
So it seems that it was latency. Closing.
