### ISSUE TITLE
[Emulator] [Abilities] [AM] Using Reinforce War Engine ability causes client to lag out severly

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#534]
If the character Arch mage uses the ability Reinforce War engine on another player, it causes his/her client to lag out to the point that he/she must kill the game and reload.

To reproduce: 

Log an AM with RR10 (who will have Reinforce war engine ability).

Cast it upon another player, and you are stuck in mid case. Players and models begin to disappear around you. The only way to recover is to kill the process and load the game again.

**Comment by ozarmidrashim** [comment]
Is this public? This has serious trolling potential and will likely be abused if it remains up here.
