### ISSUE TITLE
The Burning Windmill

### ISSUE THREAD

**Issue by shibirian** [WarEmu/WarBugs#5340]
1) If not killed Seeker Flamer does not reset with PQ but stays spawned - killing the Flamer results in: You encountered a Snotling.

**Comment by Ryanfawkez** [comment]
Fixed the subtype.

**Comment by Soulwhisper** [comment]
![masterheal_000](https://cloud.githubusercontent.com/assets/16864486/14827572/b5ac3192-0beb-11e6-918e-de6093b998d0.jpg)
Still spawns in Stage 1 of the PQ.

**Comment by StaH84** [comment]
Issue:
[ ] Some Champions from the bubbles in Stage 1 aggro with Seeker Horrors as a group, they shouldn't
