### ISSUE TITLE
Tor Anroc lava / SC guards

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#5341]
If you get knocked into the lava and die the enemy team does not get any points from the kill. Same thing if you get killed by the guards around spawn (in any SC). 

This is different from live where dying to lava/guards/the pit in EC all gave points like any other kill.

**Comment by Evildoor** [comment]
#1673 is supposed to be fixed...

**Comment by Vayra** [comment]
I'm not sure about the guard kills off the top of my head, but dying to lava does give you exp, renown and credit for quests, just not points in the scenario.

**Comment by ozarmidrashim** [comment]
Kill credit and scenario credit are distinct. I don't really care about fixing this, to be honest.
