### ISSUE TITLE
Guild Alliances

### ISSUE THREAD

**Issue by Aruis100** [WarEmu/WarBugs#5342]
I was told to post this here by a GM saying that the issue is unresolved, as the glitch only seems to affect some guilds and because my last report was taken down and linked to the resolved category.

Our guild is unable to ally with other guilds. Daily we try with one of the 5 guilds who want to ally with us, and it does not work. We have tried everything from multiple alliance names, being close and in a party, using the / command instead of the guild menu, as well as everyday we try again and again to get our alliance together. I landed a perfect 360 on my horse while sending the alliance request and it still didn't work.

**Comment by Evildoor** [comment]
> my last report was taken down and linked to the resolved category

Wrong. I closed your report and linked #4528, which is not resolved and which describes your problem. Use it if you have information to add.
