### ISSUE TITLE
Oathbearer marksman

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#5345]
barak varr: entering from ekrund gets you ported to a wrong location and fatal fall occurring.
![untitled](https://cloud.githubusercontent.com/assets/17765890/14516641/68ad6bf8-0205-11e6-96f4-27538f3bf052.png)
barak varr: "oathbearer marksman" are unattackable.

**Comment by Evildoor** [comment]
One report per problem, please. Also, coordinates for the second problem.

**Comment by Evildoor** [comment]
#5987 will be used as a report for the first problem.

**Comment by Evildoor** [comment]
No response, closing.
