### ISSUE TITLE
Armor talismans

### ISSUE THREAD

**Issue by igsky** [WarEmu/WarBugs#5346]
If you take any tank class and put armor talismans in every slot availabe you can make physical damage reduction go over 100%, for BO with full green/blue quality armor talismans physical damage reduction to 104-110%. If you abuse this with healer class, you can not be killed via physical damage, pretty much. This is a big issue, IMO, because there are more physical DD(+tanks) then magical DD classes .
This works for T1 for sure, never ever tried it out in T2-T4 though. This fact makes armor talismans much stronger then any other talisman at T1.

**Comment by Evildoor** [comment]
Armor cannot reduce damage by 100%, there is a cap (even if paperdoll states 100% or more reduction). Was the same on live. This is a balance issue, not a bug.
