### ISSUE TITLE
Guild Recall Scrolls

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#5349]
Guild vendor (at guild rank 17) has guild recall scroll for sale, however they do not actually work.
Additionally, would it be possible to get these to stack in groups of more than 5?

**Comment by Tesq** [comment]
in live stack was 20

**Comment by Abolition** [comment]
In Live stack was 5.
Unless it got changed after I stopped playing with the Scaven update.

**Comment by Tesq** [comment]
http://www.gotz.org/forum/showthread.php?t=12823

is outdated but you must have right

**Comment by Zealote** [comment]
Is this still a bug? I just tried using one and it worked (from High Pass to Sigmar's Hammer). That's with guild rank 20 though.

Also, stack limit is currently 20.

**Comment by Luth-RoR** [comment]
Thanks, closed then.
