### ISSUE TITLE
Things I wonder

### ISSUE THREAD

**Issue by bender072** [WarEmu/WarBugs#535]
Will you ever get the crafting systems up? It would be nice to make talismans for armor that has slots. 
Potions and instant need. npcs seem to have unnatural strength and potions would be nice
Npcs, and spell casters need to be nerfed? It seems to be very unbalanced with the npc damage ratio and the spellcaster damage base.
Orc quest lines fixed? Some orc quests either don't work, or are missing it's coding, or missing in general.
Some npcs have the wrong models, or missing textures? Some of the undead in norsca have ghoul models, or aren't wearing clothing, along with most tower guards being elves when they are suppose to be human, and some characters are missing clothing, or load clothing then the clothing disappears later on again.
RVR combat is a problem? Besides the balancing being unbalanced, you have level 13+ npcs near the flags when you can only level to 10, and I wonder when the Bolster death bug will be fixed.
pets, and summonable pets along with spells bugged? When playing a marauder I noticed some spells will bug and I have to switch mutations with the same spell in order to use it, or switch back to use the spells. Pets have problems following you down mountains or across water. They stand still when you cross water, or go down mountains and you have to resummons them. they also have an issue where the command bar for your pet disappears, and they are stuck in aggressive mode and attack everything till they die which makes pets useless. Summonable pets are just only aggressive making them useless when needed, and the summon ability is kind of glitched where it doesn't work at certain lengths.

**Comment by ozarmidrashim** [comment]
This is the bugtracker, not a request list. Make one report per post and check that it hasn't already been reported.
