### ISSUE TITLE
PvE: Invalid NPC in Quest "Wherever They Are Found".

### ISSUE THREAD

**Issue by EmeryDuBois** [WarEmu/WarBugs#5350]
At the Raven's End, Empire Chapter 11 in High Pass, NPC Roland Gotthardt is giving a quest called "Wherever They Are Found".
As soon as you click on the Quest button, in Objectives shows up a line with text:
"Invalid Npc,plz report to GM. QuestID 775.ObiId=15919"

**Comment by Evildoor** [comment]
#4169
