### ISSUE TITLE
BW stalker shoulders have weapon skill

### ISSUE THREAD

**Issue by kaey** [WarEmu/WarBugs#5351]
Weapon skill is a totally useless stat for Bright Wizard.
I think it shouldn't be there.
![sestica_000_cr](https://cloud.githubusercontent.com/assets/3503165/14533977/f11e6414-026f-11e6-951e-6227b7fa4ea3.jpg)

**Comment by Evildoor** [comment]
Not a bug. Useless stats on items are a problem, but it will be dealt with later. (it was already solved for PVP sets)
