### ISSUE TITLE
Can't log into one character

### ISSUE THREAD

**Issue by Tuidog** [WarEmu/WarBugs#5352]
I was playing as my character "Elviolas" in Altdorf and the game crashed. I tried logging in many times and it did not work, rather it would show the loading screen then send me back to the main menu (server select character select "menu"). I tried logging in and typing /stuck twice before the login and the only thing that changed is that it now displays the Nordland loading screen instead of the Altdorf one and in the character selection menu the character is said to be in Nordland. Based on what I saw in the forums I believe this is a bug.

**Comment by Tuidog** [comment]
resolved with the server restart

**Comment by Tuidog** [comment]
Only could log into the character once now it is back to not working

**Comment by Evildoor** [comment]
Individual problem with character, use forums (support section).
