### ISSUE TITLE
4 auras on kotbs

### ISSUE THREAD

**Issue by luci1981** [WarEmu/WarBugs#5353]
Bug or upgrade? :)

![jachk_002](https://cloud.githubusercontent.com/assets/17927514/14540233/ae9bf30a-028c-11e6-88d8-ecc1bc4c4c49.jpg)
![jachk_003](https://cloud.githubusercontent.com/assets/17927514/14540235/b1e83712-028c-11e6-877a-69f14bfe649e.jpg)

**Comment by Tesq** [comment]
should be a icon bug from the last big patches sometiemes icons in the buff menu screw a little

**Comment by Tiggonos** [comment]
buff icons dont tell anyhting they still totally bugged.

**Comment by luci1981** [comment]
Look at the icons in the cast bar - 4 are active.

**Comment by ozarmidrashim** [comment]
Icons in the cast bar light up in response to the presence of the buff, so Tiggo's statement is not invalidated.

**Comment by Tiggonos** [comment]
easiest proof would be if you could provide screens from getstats and damagelog for the dmg and heal aura where you get healed when defending an attack. On my kotbs i yet didnt recognice 4 auras on.

**Comment by Kaloell** [comment]
How to reproduce:

1. Train Focused Mending in the Path of Glory.
2. Have a tactic set with Focused Mending active but not Stay Focused! up.
2. Swapp tactic sets to one without Focused Mending. **This activates the "normal" version of Stay Focused!.**
3. Active any 3 auras (e.g.  Gather your Resolve!, Press the Attack! and Stand Strong!). After this you should have 4 auras running at the same time. Stay Focused! is proccing and healing, see screenshot.

![Aninus_014](https://user-images.githubusercontent.com/29151272/58171315-09a11100-7c96-11e9-920d-09a73778367e.jpg)

The bug persisted even when switching zones or auras, as long as Stay Focused! was not deactivated, and the tactic Focused Mending was not swapped in.

**Comment by grunbag** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 17.08.2019
