### ISSUE TITLE
Mourkain Temple Out of Bounds

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#5355]
Forgot to take a screenshot, but it's possible to leave the map of the Mourkain Temple SC in the SW corner, saw an order group take the bauble there to try and hide. You end up outside the visible map.

**Comment by Evildoor** [comment]
Well, screenshots are needed.

**Comment by Vayra** [comment]
I'll get some next time I play the map

**Comment by Tesq** [comment]
always was like that, but they get no point, they are too far from temple so is useless do that and the relic anyway reset after some seconds if the keeper die.

**Comment by Vayra** [comment]
Here's a few screenshots:
![kalyth_000](https://cloud.githubusercontent.com/assets/1183293/14563953/a77ff830-0324-11e6-9e2c-5fdda57fc930.jpg)
![kalyth_001](https://cloud.githubusercontent.com/assets/1183293/14563954/a796ff62-0324-11e6-8c00-d09e5d0400f9.jpg)
![kalyth_002](https://cloud.githubusercontent.com/assets/1183293/14563955/a7a7d076-0324-11e6-8bea-248c728c7d6a.jpg)
