### ISSUE TITLE
Quest icons are wrong on some quests

### ISSUE THREAD

**Issue by shibirian** [WarEmu/WarBugs#5356]
The quest can be finished but does not reset; in the sense of it still stays active for handing it in (yellow sign and complete button remain).

**Comment by Ryanfawkez** [comment]
Are you sure you're handing it in at the right NPC? The quest giver is also the hand-in NPC; not the Passwatch Marshal.

**Comment by shibirian** [comment]
Yes. I'll make screens later and attach them here. :)

**Comment by shibirian** [comment]
As can be seen - this can be done multiple times: Nothing happens.

![cyriana_079](https://cloud.githubusercontent.com/assets/17605387/14577912/6f023a3e-037b-11e6-9e76-7e01855fea1c.jpg)
![cyriana_080](https://cloud.githubusercontent.com/assets/17605387/14577913/6f069af2-037b-11e6-8b85-9b5ecdb255af.jpg)

**Comment by Torquemadra** [comment]
You need to talk to a pass watch Marshall, you haven't finished objectives. The Orange icon over head is a bug

**Comment by Luth-RoR** [comment]
Happens only with custom quest that are not done by mythic/not included in the 1.4.8 version.

**Comment by Lheana** [comment]
#8000
