### ISSUE TITLE
[Emulator] Scenario Point system increases too quickly

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#536]
The current point incremental system for captured BOs are fast,

If a realm claims more and 1 BO (max 3 in Nordenwatch) the point increments are each second. They should be every 3 seconds (like a heal over time/damage over time buff).

**Comment by MaxHayman** [comment]
It should be every 2 seconds currently. No one told my the exact Intervals, but I will get it changed. Also it was 5 points for kills?

**Comment by Elvenalthur** [comment]
Thanks Max. Yeah, it was 5 points per kill.

**Comment by gittoaster** [comment]
I would suggest that you consider not adding points for kills in capture the flag sc's as it can distract from the flags mechanics.  

I think only some scenario are kills only but we have seen a lot of different varieties before.

cheers
