### ISSUE TITLE
no reward in warcamp after dieing and respawning

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#5360]
right now when you die in rvr and respawn in warcamp and the zone locks, you dont get any reward.

this quote by carry gouskous implies it worked differently on live:

"While players who have died recently and are respawning in the warcamp will still acquire zone capture rewards"

http://www.returnofreckoning.com/forum/viewtopic.php?f=15&t=12868&p=140885#p140883

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
