### ISSUE TITLE
BW | "withering heat" can be used in 360° angle while moving

### ISSUE THREAD

**Issue by Thorgatin** [WarEmu/WarBugs#5361]
The ability has a 360° angle, not 180° as it should. BW dot abilities work normally (180°).

Maybe related to https://github.com/WarEmu/WarBugs/issues/2608 and does affect more abilties.

**Comment by Tiggonos** [comment]
withering heat cant be used while moving it breaks instantly. just tested on rat. therefore its not 360 degree either.

**Comment by Thorgatin** [comment]
Where did i wrote that the whole channel can be used while moving?

It could be used on the move on the mythic server and it can be used on the move here; only the first damage tick hits and a 3 second snare is applied (also like on the old server).
Most people use it to get another instant hit without cast time while kiting (the snare is also helpful).
