### ISSUE TITLE
Keep loot rolls

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#5365]
Regardless of how many people are present at a keep capture or defence, only 23 people are selected and able to roll for loot. These 23 names show up on the loot table.

If you do not happen to win the lottery of getting to roll:
1. You do not receive a single medallion
2. The loot table will say "you have placed first and won a gold bag", even though the table clearly shows it is someone else's name (one of the lucky 23 to roll).

**Comment by Evildoor** [comment]
2nd point was already reported, but remaining info is new, IIRC.

**Comment by Abolition** [comment]
Additionally, if you one of the lucky 23 to get to roll and do not roll high enough to win a bag, you do not receive any medallions.

**Comment by Abolition** [comment]
It is possible that the "lucky 23" could be related to who gets to the Keep "PQ" latest.

For example, yesterday our 6-man ran into a heavily populated keep fight as the Lord was under attack. We literally died to champion mobs at the gate and stayed dead. The Lord died, and we all rolled for loot bags as part of the "lucky 23".

Perhaps the last 23 people to enter the PQ area are the ones that get to roll?

No evidence to back it up; just throwing it out there.

**Comment by Soulwhisper** [comment]
@Luth-RoR This works fine now.
