### ISSUE TITLE
lair whit hero  no drop nothing

### ISSUE THREAD

**Issue by Magteridon** [WarEmu/WarBugs#5366]
access is difficult and also when you kill does not let anything attached photos of how to access the lair and the boss is
![magteridon_008](https://cloud.githubusercontent.com/assets/16975012/14580340/c34064e6-03ca-11e6-94cb-72a536dc23f3.jpg)
![magteridon_009](https://cloud.githubusercontent.com/assets/16975012/14580342/c34341d4-03ca-11e6-9073-d6b82063c1b6.jpg)
![magteridon_010](https://cloud.githubusercontent.com/assets/16975012/14580341/c342c61e-03ca-11e6-80e6-e599dcd21619.jpg)
![magteridon_011](https://cloud.githubusercontent.com/assets/16975012/14580344/c3449c00-03ca-11e6-8226-d35db51eb717.jpg)
![magteridon_012](https://cloud.githubusercontent.com/assets/16975012/14580343/c3442cf2-03ca-11e6-86b2-af83122be73f.jpg)
![magteridon_013](https://cloud.githubusercontent.com/assets/16975012/14580345/c3453e8a-03ca-11e6-8e93-91d2c8e1c8a1.jpg)
![magteridon_014](https://cloud.githubusercontent.com/assets/16975012/14580346/c3550a54-03ca-11e6-972c-e916984331a0.jpg)
![magteridon_015](https://cloud.githubusercontent.com/assets/16975012/14580347/c357fc32-03ca-11e6-9701-5115030d9f3d.jpg)
![magteridon_016](https://cloud.githubusercontent.com/assets/16975012/14580348/c3595654-03ca-11e6-9678-ae99ab62bb3e.jpg)

**Comment by Evildoor** [comment]
#5083
