### ISSUE TITLE
Scenario flags

### ISSUE THREAD

**Issue by arthur3k** [WarEmu/WarBugs#5371]
Making players untargetable by ranged if they run around them, should be removed.

Noticed this in Reikland factory scenario.

**Comment by Vayra** [comment]
Yes, I'm fairly sure they did not break LoS on live, and it's a big issue for Sorcs/BWs with long cast times when fighting around flags.

**Comment by arthur3k** [comment]
Yeah, Im sure that didnt happen on live and when playing range it feels stupid that the skills goes red all the time. :P
