### ISSUE TITLE
wrong spawn point in Inevitable City

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5372]
After being killed/died i should spawn in another place in Inevitable City.
Here i point it on screenshots:
1 is where i spawned now
2 is where i should spawn if i died inside IC
![1 spawn](https://cloud.githubusercontent.com/assets/18102127/14582278/bc23a8de-0411-11e6-9976-cf09ef38d1b5.png)
![2spawn](https://cloud.githubusercontent.com/assets/18102127/14582277/bc239af6-0411-11e6-9ca9-3e22a3208b3d.png)

**Comment by Ryanfawkez** [comment]
Respawn point is based on the zone's entry point from the flight master at the moment. Not sure if this can be fixed.

**Comment by Yellowpillow** [comment]
was fixed, not perfectly correct place, but it's close enough.
