### ISSUE TITLE
Shaman in Talabekland named Cunnin' Shaman dont provide quest

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5374]
this little fella should give quest, for the completion of which you have to find tome behind Tavern BO (in RvR zone). Reward for completion should be 60,000 exp and few gold coins.
That quest have chain after that, requires to fly into BFP and touch 5-6 piles of bones in RvR zone there, which is also give gold and 60k exp in reward. 
Cant remember 3rd part of it, and as i remembere there is 3 part in total.
![default](https://cloud.githubusercontent.com/assets/18102127/14582467/c273f1d0-0416-11e6-8efe-3e1dbcda37ba.jpg)

**Comment by Torquemadra** [comment]
Not planned at this time
