### ISSUE TITLE
ToK Incorrect Unlock

### ISSUE THREAD

**Issue by Thorgrumm** [WarEmu/WarBugs#5376]
ToK incorrect unlock for killing 100 Snotlings when killing Chaos mobs (was doing stage 2 of PQ in Unterbaum Castle). Similar to closed issue #3869:
![100 snotlings](https://cloud.githubusercontent.com/assets/18247674/14582920/4297d5fa-040a-11e6-8981-cb6469f22000.jpg)

**Comment by Ryanfawkez** [comment]
We need some exact NPC names to fix their subtype. Please include 'em ;)

**Comment by Thorgrumm** [comment]
Killing the level lvl29/30 champion 'Biilos the Rotting' in stage 2 of the PQ gave the unlock, prior to this I had been farming 'Bane Knights' and 'Bane Champions' in stage 1. I dont think that the Bane Knights/Champions would have contributed to the unlock as I have done this PQ around 30ish times so I would have got it long ago. This leads me to think that it is just the three lvl29/30 champions in stage 2 that contribute to the snotling unlock, possibly also the stage 3 champion. I'll grab the rest of the champions names next time I run through the PQ.

**Comment by Thorgrumm** [comment]
Definately goes towards the unlock:
- Biilos the Rotting (lvl 29/30 Champ PQ stage 2) got the unlock when i killed him

Possibly goes towards the unlock:
- Gruelox Festersword (lvl 28 Champ outside Unterbaum Castle gates throughout PQ)
- Siklous (lvl 29/30 Champ PQ stage 2)
- Kanscere the Grotesque (lvl 29/30 Champ PQ stage 2)
- Nagrech the Festering (lvl 31 Champ PQ stage 3)
