### ISSUE TITLE
Loot bags do'nt contain all the items that should be into them

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5377]
First of all: they dont contain proper stuff. In purple bags should be found purple armor or accessories, in green bags - green items, in blue - blue items. Now there no armor or accessories at all, only medalions, money and crafting materials.

Second: White bags always contained white gear. But all other bags contained white gear + gear which has to be in that particular bag. For example green bag should contain 1 white item and 1 green item. There always was 1 white item to choose.

Third: there was a little bit Experience points into bags as an option.

4: there should be crafting vessels (for talisman making and alchemy optionally) to choose.

may be partly reference to #4906 and #4864

**Comment by Razielhell** [comment]
Known. Waiting for appropriate tools to create mass items.
