### ISSUE TITLE
Trivial clipping/stretching [Bright Wizard]

### ISSUE THREAD

**Issue by Mourdechai** [WarEmu/WarBugs#5379]
![screenshot_000](https://cloud.githubusercontent.com/assets/18507551/14584407/551169e0-0413-11e6-94db-55ae1b6b0e05.jpg)

Pretty self explanatory. The mesh clips/stretches during certain animations(not just on the select screen) on the Flamerobe of the Braggart. It looks like the mesh is kind of awkwardly attached to the legs and then folded back over(so this may not be fixable or even worth anyone's time). Resolution is 4k, downsampled to 1080(not with DSR).

**Comment by NorKalli** [comment]
Can we close this?
