### ISSUE TITLE
Debuffs are slightly broken

### ISSUE THREAD

**Issue by bender072** [WarEmu/WarBugs#538]
When you cast an ability that causes a damage over time or debuff, and click on another target the debuff disappears and you either have to recast the debuff and keep attacking the same target or risk losing the debuff to attack another target

**Comment by Thorgatin** [comment]
If you look in the combat log, you see that the damage from dots still tick. Only the debuff icon is removed, not the actual debuff itself.

**Comment by bender072** [comment]
For some reason I don't see the damage meter going up on the enemy as it disappears. I don't know it seems weird, but I'll keep picking at it.
