### ISSUE TITLE
Knight Auras Bolstered Incorrectly

### ISSUE THREAD

**Issue by Ramasee** [WarEmu/WarBugs#5380]
Knight of the Blazing Sun Auras "Press the Attack!", "Stand Strong!", and "Gather Your Resolve" give far too many stats for what they are supposed to. This bug is caused by casting the auras while you are bolstered inside of a scenario. Submitted screenshots.

![ramasa_000](https://cloud.githubusercontent.com/assets/18507595/14584441/67f58676-0414-11e6-92cc-c2df56b56265.jpg)
![ramasa_001](https://cloud.githubusercontent.com/assets/18507595/14584443/6802a806-0414-11e6-8468-6faec7e6e7c1.jpg)
![ramasa_002](https://cloud.githubusercontent.com/assets/18507595/14584444/68040cbe-0414-11e6-90cb-b886b58822af.jpg)
![ramasa_003](https://cloud.githubusercontent.com/assets/18507595/14584445/68089202-0414-11e6-80eb-e81dd13a3c44.jpg)
![ramasa_004](https://cloud.githubusercontent.com/assets/18507595/14584447/680a9fd4-0414-11e6-941a-f98b333fbdf7.jpg)
![ramasa_005](https://cloud.githubusercontent.com/assets/18507595/14584446/6809494a-0414-11e6-8fbb-a4d57b28a895.jpg)
![ramasa_006](https://cloud.githubusercontent.com/assets/18507595/14584442/6800d544-0414-11e6-83cd-0dfc28738d6c.jpg)
![ramasa_007](https://cloud.githubusercontent.com/assets/18507595/14584448/680b28f0-0414-11e6-83e8-90c108d14d79.jpg)
![ramasa_008](https://cloud.githubusercontent.com/assets/18507595/14584449/680d92ac-0414-11e6-8f9a-bdd26814ec61.jpg)
![ramasa_009](https://cloud.githubusercontent.com/assets/18507595/14584450/68105c44-0414-11e6-9ff6-b89c4893744a.jpg)

**Comment by taccr** [comment]
Screenshots are taken without bolster so the ability tooltip is obviously lower.

The only "bug" here is buffs not dynamically scaling with the bolster buff. Also affects tactics etc.
Been exactly like this on live though.

**Comment by Ramasee** [comment]
The screenshots were meant to show that the abilities were providing more than they should after you were no longer bolstered. For instance, you can go out in T3, get bolstered, cast your auras, and they will stay at the value they were when you cast them, even after you leave.

They did not do this on live, at least not when I played. Granted I wasn't playing at the time of server close, so it may have changed. Or maybe it did, but you couldn't notice it because of how KotBS auras worked on live versus here.

There may be no way to fix it currently; I just didn't see it posted anywhere. Also it works for every KotBS aura at all different bolsters.

**Comment by taccr** [comment]
I can only repeat myself since everything was mentioned in my earlier post already.
There is no dynamic scaling. Neither for buffs or for tactics.

A lot of bolstered players enter RvR and don't reequip their tactics to get the bolstered stats. Same goes for abilities that were activated outside RvR.
Not a bug.

**Comment by Evildoor** [comment]
#5058
