### ISSUE TITLE
Light Armor of Power

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#5381]
http://i.imgur.com/e384Gun.png

Weird item. I've never heard of it before. Something new?

**Comment by Ryanfawkez** [comment]
Any hints on how you obtained this item? Would love to know its origins.

**Comment by wargrimnir** [comment]
Random drop, was grinding salvaging at the time on R10ish mobs.

**Comment by genisaurus** [comment]
Fixed in next patch.
