### ISSUE TITLE
Porting to start of T1 on disconnect from Scenarios

### ISSUE THREAD

**Issue by GreySovereign** [WarEmu/WarBugs#5382]
There's what seems to be a bug in relation to disconnecting from Scenarios and loading screens. Every time I disconnect from a scenario or loading screens (due to Internet issues), I am ALWAYS ported to the very start of T1 for whatever race I am playing. It also automatically resets my book of binding to that location also. I wasn't sure if this was a bug or was carried over from Live because I never had this issue. PLEASE FIX / CHANGE THIS .

**Comment by Kaelang** [comment]
This is no longer happening in the current version of RoR. Please re-open this issue if you are still experiencing this.
