### ISSUE TITLE
Pulling Over Fences in High Pass Cemetery

### ISSUE THREAD

**Issue by Topologic** [WarEmu/WarBugs#5383]
It's currently possible for players to be pulled over the fences surrounding the capture points in High Pass Cemetery.  

The offending pull was Git to Da Choppa; I don't know if any other pulls work, though I'd wager they do.

**Comment by ozarmidrashim** [comment]
Nothing to do with me.

**Comment by Luth-RoR** [comment]
Was fixed.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/2320

**Comment by Luth-RoR** [comment]
Moved to client modification milestone for the same reason as in the linked report.
