### ISSUE TITLE
Various SQ bugs (pre-T4).

### ISSUE THREAD

**Issue by Teefz** [WarEmu/WarBugs#5384]
Hello! I have been back for a couple of weeks and figure I’d list a few of the bugs I’ve encountered. Some of the bugs is already on the bugtracker.

1. Squigs despawn zoneing.
Note: Squig Herder loses his pet (his ‘stance’) every time when zoning. (F.x. zoning through the skaven tunnels, loading a scenario etc.) Fun fact: I think they start running all the way from either BFP or Badlands depending on which zone and then just ultimately bugs out.
2. Pet stance bar
Note: Squig Herder’s pet action bar has some issue with the opacity. This bug was on live as well and as far as I know, it happens upon zoning and/or simply spawn of pets. No idea what causes it. Another thing is that, the different pet abilities will sometimes appear on difference pets. (Not that it rly matters for the overall performance of the pet, but it’s the principle!)
3. Drop That!! Ability bugged or ‘working as intended’? 
Note: The Squig Herder’s disarm (Drop That!!) is not instant anymore. Meaning you hit the disarm, but the time in which it actually hits the target, anywhere between 1-5 seconds pass by. Ultimately making the fight especially against WL’s slightly more tricky. I believe Github’s theory that the disarm actually only procs of the squig auto attack and not any of the pets abilities might be interesting to look at. 
4. Where is my armor Gas Squig?!
Note: Squig’s do not recieve armor bonus from gas squig. At all. Not even 1 armor. Ultimately making the gas squig completely useless and the possibility of going melee out of the question. 
5. Why does Horned Squig stack with str?! 
Note: “This pet receives bonuses to str equal to ur bonus from items… etc.” But this pet is “leveled” up through the BIG SHOOTING tree. I get the idea that the squig is melee and it thereby needing str, but then you might as well just swap it with Gas Squig?! 
6. Pet abilities can’t be trained at the ability training
Note: This does not affect the actually squigs, but it’s more of a visual issue. 
7. Pet’s kills on quest mobs doesn’t give the the group the reward of the kill. 
Note: F.x. You and your 6man kill Felix Magnus for the Stalker Quest. Pet get’s the killing blow. Squig gets quest done. Rest have to wait for respawn. Therefore squigs has to kill pet/call it off target(and thereby lowering dps significantly). 

That’s the ones from the top of my head.. I’ll be back with more if I encounter some.

**Comment by Evildoor** [comment]
Please, use search before posting. Also, 1 report per problem next time.
1) #2069
2) #811 point 1
3) According to Azarael in #1554, disarm procs off everything. Maybe enemy dodges attacks of the pet, or something else.
4) #2146
5) Not a bug.
6) Players don't need to train abilities either. Not a bug but decision (at least for now).
7) #1229 and #5039
