### ISSUE TITLE
Keep loot bag

### ISSUE THREAD

**Issue by arthur3k** [WarEmu/WarBugs#5386]
So, today when I got my first bag from a keep take I got a massive loot bag as a reward but when i opened the bag to collect the gear the loot disapered. 

Sad day for a greenie!

**Comment by Evildoor** [comment]
Just to clarify:

> when i opened the bag to collect the gear the loot disapered

This means that you clicked on the bag in your inventory and it disappeared without showing a window with its contents? Or you clicked on the PQ chest on the ground in the keep, and it disappeared without giving you anything?

**Comment by Evildoor** [comment]
No response, closing.
