### ISSUE TITLE
Problem queuing for scenario as group

### ISSUE THREAD

**Issue by KiroyWolf** [WarEmu/WarBugs#5387]
Intro:

When trying to queue for a Scenario as a party when in a party, it will not allow it until the party is restarted.

Details:

My partner and I always group together when we log into the game. However, when either of us tries to queue for Scenarios as a party, the option is not clickable and when hovered over, it gives the tool tip that you "must be in a party or be a party leader in order to select this option" or something to that affect (no matter whether my partner or I am the party leader). So, in order to get it to work, we have to disband the party and reinvite each other and then the option to queue as a party becomes selectable. It wouldn't be so bad, but once a Scenario ends, the option to queue for a Scenario as a party becomes unselectable again and we must disband the party and form a party all over again in order for it to be able to be selected.

Additional information:

This seems to have happened to us just after the patch to fix the keeps that was sent out last week. We have also not tried this with three or more people in the party to see if it is an issue at that point, just with us two.

How to reproduce the bug:

First, log into a character and party up with someone else. Then, the party leader goes to queue the party up for Scenarios, but the ability to select the option is not there. After that, disband the party and reform the party. The party leader will then be able to queue the party up for Scenarios. The process repeats itself once a Scenario is completed.

**Comment by ropuch** [comment]
I had the same problem. but somehow using QueueQueuer solved the problem.

**Comment by Thayli** [comment]
Reloading UI seems to be a workaround.

**Comment by Kaberu** [comment]
I've found if you keep the queue window up when you disband your group the "group queue button" will then be available.  It would seem it flags once you disband vs forming the group.  Reform the group and you can queue up.  So same issue here for my wife and I.

**Comment by Soulwhisper** [comment]
As Thayli said /rel works fine.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
