### ISSUE TITLE
Unable to loot/Mobs will no longer spawn

### ISSUE THREAD

**Issue by Joulipous** [WarEmu/WarBugs#539]
I wanted to farm a bit at the Broketoof camp today on my choppa Krakka. None of the mobs I killed dropped anything, I couldn't loot, the bodies stayed where they were, except for a champion I killed and the dead mobs didn't respawn as if my touch were cursed.

**Comment by Thorgatin** [comment]
Maybe it's this issue: http://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=1936
