### ISSUE TITLE
Kotbs T3 orvr influence reward shoulder bug

### ISSUE THREAD

**Issue by Brezirk** [WarEmu/WarBugs#5390]
In Badlands t3 on the RoR server, I purchased the Brewer's ESpaliers. Equipped this item to find out that shoulders appear to be at my waist level instead of being on my shoulders. Plz let me knw if it is suppose to be this way or what lol. if not looks kinda cool :) my kotbs name is Breztank. thx

**Comment by Ryanfawkez** [comment]
They have a model for Shaman shoulders. Changing it to Knight of the Blazing Sun shoulders.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
