### ISSUE TITLE
Rebought Loot Bag

### ISSUE THREAD

**Issue by GloomySam** [WarEmu/WarBugs#5392]
I won a major loot bag at a keep. Then sold it to a vendor by accident. Bought it back and now can't open it. That sucks :(

**Comment by CptnMiller** [comment]
Can confirm - same happened to me, accidentially sold it, bought it back, cant open it.

**Comment by blakokami** [comment]
Any news on this? Is it able to be fixed?

**Comment by Luth-RoR** [comment]
Closing this as the referenced issue has info from DB dev. https://github.com/WarEmu/WarBugs/issues/6840#issuecomment-238053075
