### ISSUE TITLE
tab targets bugmans finest and lightning rod

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#5395]
both not even attackble. shouldnt target these.

**Comment by Evildoor** [comment]
Not attackable? #1466 was ninja fixed?

**Comment by Tiggonos** [comment]
interesting. i will recheck but they both were orange and not attackable im quite sure

**Comment by Torquemadra** [comment]
Not attackable but they are a target block

**Comment by Evildoor** [comment]
#1466 includes:

> Both should be unattackable and would be nice if they were unable to be targeted

Ok, first problem was fixed but second remains and, according to Azarael's comment, he has no means to fix it for now. Therefore, i'm closing this report since #1466 already describes this problem.
