### ISSUE TITLE
ToK Bestiary Unlock: Iceshard Blade

### ISSUE THREAD

**Issue by Thorgrumm** [WarEmu/WarBugs#5396]
Troll Country 37500,900, inside the cave 'Shiver Hollow' with Yhetees. At the back there is a 'Shard of Ice' which should be clickable and you receive the 'Iceshard Blade'. It is currently not clickable.
![shard of ice](https://cloud.githubusercontent.com/assets/18247674/14590203/1e1db044-04ed-11e6-9934-b104fac6a401.jpg)
http://warhammeronline.wikia.com/wiki/Achievements_%28Bestiary:_Iceshard_Blade%29

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
