### ISSUE TITLE
Darl Elf T1 PQs

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#5398]
Hello!

Please reduce the amount of mobs around the PQs and increse their respawn timer. Even if the PQs doesn't work, some quests have objectives in the PQ areas and very often reaching the quest object is very hard or nearly impossible.

Regards,
StaH.

**Comment by Evildoor** [comment]
Is this about #5250?

**Comment by StaH84** [comment]
No. It's not about multiple mobs in one spawning point. Just there's way tooo many of them in PQ locations and they are respawning really fast. With time needed to heal between fights it's really hard to navigate through them.

**Comment by Lheana** [comment]
PQs of this chapter have all been reworked, I think it has fixed in a certain way this.
