### ISSUE TITLE
"Foul Works" - wrong objective, not usable item

### ISSUE THREAD

**Issue by DizzyUA** [WarEmu/WarBugs#54]
currently it has objectives like in screenshot.
![dizzy_005](https://cloud.githubusercontent.com/assets/7514926/2909256/bb5f5b3e-d630-11e3-9b41-7d23a0c7ed65.jpg)
in quest you should use Cluster of Stench near watchtower of Selthis Lysk, and kill after that 5 mobs "watchtower defender", so objectives should be: 
1) use Cluster of Stench near watchtower of Selthis Lysk
2) kill watchtower defenders 0/5
Currently npcs not count as right kills. and no item provided for quest

**Comment by Reggaewaldo** [comment]
Tested today. The quest can currently be completed as a regular kill quest. The item is not given and thus can't be used.
