### ISSUE TITLE
Items lost in mail.

### ISSUE THREAD

**Issue by Joulipous** [WarEmu/WarBugs#540]
I send a number of gale-runner items from my choppa Krakka to my black orc Brakka, including two Black Orc chests and also some silver. Had my blackguard Valinar send BO Shoulders to Brakka. He recieved the silver and all gale-runner items (I think, don't know how many items I send exactly) except for the Black orc chests and shoulders, which both magically disappeared, can't be a coincidence right!?

**Comment by Joulipous** [comment]
Add to that the disappearance of certain quest rewards on completion, just lost a belt and a trophy on the same character(Brakka).

**Comment by Evildoor** [comment]
Mail fails sometimes, nothing we can do here. If a quest gives you no reward, it should reported independently, with quest and reward names.
