### ISSUE TITLE
Blighted Isle Tome Unlocks

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#5400]
I've done a run through Blighted Isle to hunt some unlocks and a number of them are not working:
I made it into one report so as to not clutter up the tracker, but if you'd prefer individual reports for each issue let me know and I'll edit the post into one for each.

# Bestiary:
**Horror - Where Did You All Go?**
Killed the Lost Horror at 20, 38, did not get unlock.

**Scorpion, Giant - Beach Bum**
3, 63. Title unlocks when the champ is killed, but the bestiary entry does not show as completed. 

**Wolf - A View With a Howl**
Should unlock as you move along the edge of the cliff at 5, 46-49, as well as post a message about hearing wolves howling below. Does not work.

# History and Lore:
**The Beastmasters of Karond Kar**
![therealvayra_000](https://cloud.githubusercontent.com/assets/1183293/14604907/402ed648-0576-11e6-835b-dc75a435d258.jpg)
Clicking on the Manacles of Wrought Iron at 14,47 should give the unlock, this does not currently work.

**The Black Arks of Naggaroth**
Should be unlocked by moving along the cliffs running up to Dark Elf Ch1. Does not work.

# Exploration:
**Cold One Hunters:**
Should be unlocked by approaching the Cold One Corral for Destruction at 12,20. Does not unlock.

**The Mysterious M.B. (Precious Flask):**
Clickable item Precious Flask in Order start area (39, 2), should grant an item that can be clicked to give the achievement
![therealvayra_002](https://cloud.githubusercontent.com/assets/1183293/14606192/558a32e8-057c-11e6-8560-d2f34bd60a0e.jpg)

**Comment by Ryanfawkez** [comment]
Fixed all the ones not related to proximity unlocks; Cold One Hunters and The Black Arks of Naggaroth.. Those are unable to be fixed at this time.
