### ISSUE TITLE
Guild roster displays only one member (me)

### ISSUE THREAD

**Issue by Darishel** [WarEmu/WarBugs#5401]
None of the offline members are showing up in the guild roster.  All three of my characters in the guild are displaying this way.  Fully exiting the game didn't fix it.  I don't know if another person was online in the guild if they would show up in the roster.

![image](https://cloud.githubusercontent.com/assets/18334944/14607251/a23cdda8-0535-11e6-85cb-15c763ec5a4d.png)

![image](https://cloud.githubusercontent.com/assets/18334944/14607364/159f38e0-0536-11e6-8932-443f8dcc6fcc.png)

**Comment by Evildoor** [comment]
#1438
