### ISSUE TITLE
Felde castle door

### ISSUE THREAD

**Issue by ellionkeman** [WarEmu/WarBugs#5403]
Troll country. Fwkde castle. Cant open the castle door. On live it could be opened. But I don't remember maybe this feature was aremoved in late patches. 
![broliy_021](https://cloud.githubusercontent.com/assets/18136746/14614863/b6262d6c-05ab-11e6-8ed4-2b984d08b1a4.jpg)

**Comment by Thayli** [comment]
Fixed all 4 doors.
