### ISSUE TITLE
Dark Elf ch6 - Ruins of Nagarythe - Stage 3

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#5404]
No spawns for the final bosses. Checked all over the area for them.

http://i.imgur.com/HQD6lwb.png

**Comment by Soulwhisper** [comment]
**25/08/2016**
- Scanned the area again.This is correct.Stage 3 mobs dont spawn.

**Comment by Razielhell** [comment]
You fixed this :P @Luth-RoR
