### ISSUE TITLE
Ch.7 Dark Elfs - The Griffon Gate

### ISSUE THREAD

**Issue by Forgjordr** [WarEmu/WarBugs#5405]
Stage 1 - Uthorin Stormer kill Eagle Claw and complete Stage 1 without player.
Window with PQ information and results broken if player walk around PQ zone.
All High Elves which i kill in this PQ in Tome Knowledge identify as Empire Human.

**Comment by Soulwhisper** [comment]
@Luth-RoR This is fixed!
