### ISSUE TITLE
Slayer | "devastate"

### ISSUE THREAD

**Issue by Luth-RoR** [WarEmu/WarBugs#5407]
The slayer wounds debuff is spammed on the target until it's dead:

![20160419163239_1](https://cloud.githubusercontent.com/assets/8567481/14642904/9b546570-064c-11e6-8cd3-0bd5161b3e29.jpg)

**Comment by Scrilian** [comment]
I'd say there is an issue with the abilities in general.
![x](https://cloud.githubusercontent.com/assets/16498708/14647258/91fe759c-0665-11e6-96c8-e440e5c08ce6.jpg)
Related to https://github.com/WarEmu/WarBugs/issues/4171

**Comment by Scrilian** [comment]
And another one with M4
![x2](https://cloud.githubusercontent.com/assets/16498708/14647340/fc053da4-0665-11e6-9329-48c8f2c59154.jpg)

**Comment by ozarmidrashim** [comment]
Initial report was fixed. Second report is a variant of repeater M4 problem which has multiple open reports.
