### ISSUE TITLE
Gaining Destruction Influence from PvE PQs as Order, Not Gaining on Order PQs

### ISSUE THREAD

**Issue by Bombatta** [WarEmu/WarBugs#5411]
I am playing as a 35 Warrior Priest and I am gaining Destruction Influence from a PQ at the approximate location of 32000 26000 in High Pass.  I cannot see anything telling me I am in a PQ, I just get the little +50 INF whenever I kill skeleton archers.  It shows in my ToK as Chaos Chapter 13, the influence that has accrued.

On the other hand, I no longer gain influence from PvE PQs for Order, nor can I advance the kill counts in the PQs.  I have tried PQs in all three pairings, ones that I have not inf capped yet, nothing.  My RvR influence is unaffected. 

This affects another of my characters but not all.  Thanks.

**Comment by Evildoor** [comment]
1st issue is known: #5148

**Comment by wargrimnir** [comment]
Needs confirmation.

**Comment by Blaqwar** [comment]
Can't comment on the second part of the issue but I was gaining influence at that specific PQ, with Chaos CH13 as well.

![hathol_035](https://cloud.githubusercontent.com/assets/5108812/21486049/6a0fc578-cbad-11e6-9739-32976f8e2f26.jpg)
![hathol_037](https://cloud.githubusercontent.com/assets/5108812/21486051/72c220a8-cbad-11e6-8560-05669ef39fa4.jpg)
