### ISSUE TITLE
Reikland Factory - Mages Horror ticks BO flag

### ISSUE THREAD

**Issue by shibirian** [WarEmu/WarBugs#5412]
Reikland Factory - A Mage leaves his Pink Horror behind at Middle Flag - BO flag ticks down and flips over to Destro. No other destro there - no WE in SC too (see screens).

I was so busy killing the horror before the flag ticks over (which was uselelss to do anyway) that I missed taking a screen of it.

Question: Is that legit? I mean I cannot remember that that happened on live.

See screens for list of toons in SC; no WE.
![anthyr_117](https://cloud.githubusercontent.com/assets/17605387/14659710/90b925e0-069e-11e6-8a69-f332fd46e996.jpg)
![anthyr_118](https://cloud.githubusercontent.com/assets/17605387/14659711/90be39b8-069e-11e6-8fa8-ff39ef9a7710.jpg)

**Comment by Kaelang** [comment]
No longer happens. Closing.
