### ISSUE TITLE
Keep Defence INF tick

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#5413]
Not sure if isolated to just Fangbreaka Keep in T2, but it appears that was the defence tick happens, you gain XP and RP, but there is no INF tick. Unsure if intended, or a bug?

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
