### ISSUE TITLE
NPCs in Ch10 Chaos

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#5414]
Raven War Breaker NPCs in the CH10 Chaos camp are named "wRaven War Breaker".

Update: Also the wRaven War Breakers in Scenarios, so maybe all Raven War Breakers have this.

**Comment by Evildoor** [comment]
#5251 is supposed to be fixed...

**Comment by Vayra** [comment]
But no new patch since then. Last patch was the day before that ticket posted.

**Comment by Evildoor** [comment]
The ticket was closed by @Ryanfawkez who fixed it, so he either closed it by mistake or the changes were pushed without a patch announcement - my comment above is based on assumption of latter, since several other tickets were closed together with #5251. Ryan?

**Comment by Ryanfawkez** [comment]
Closed it by mistake. This update is not live yet.
