### ISSUE TITLE
Armor buffs (and i bevieve other stat buffs) do'nt stuck correctly

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5415]
I tested it on armor buffs, but i sure this is works the same for other buffs.
Buffs of same stat do not stuck, this is how it supposed to be. 
What i talk about is redundant amount of overbuff is still takes part in total math.
Here's the deal.
How it was on live: lets say you have 2000 basic armor. You have buffed for 600 armor by pot. After that you have buffed for 400 armor by ability. In total you should receive 600 armor, because it strongest buff. But (here magic begins) while you have 2 those buffs, if you have been debuffed for, let's say 800 armor, you will have in total 2200 armor left. 2000 + 600 + (400 which is not count without debuff) - 800 = 2200.
that overflow 400 is count, but only when debuffs appears.
3 of same stat not count. Only 2. For example 2000 basic armor + 600 buff + 400 buff and + another 300 buff - 1000 debuff = 2000 armor left (3rd baff is weakest and doesnt count at all)
Same should work for strength, willpower, and any other stat buff.

**Comment by Evildoor** [comment]
Is this based on paperdoll or getstats?

**Comment by Yellowpillow** [comment]
I tasted it with .getstats
of course i dont have screenshots of that mechanic from live, never thought it would be necessary

**Comment by ozarmidrashim** [comment]
Confirmed false report. Tested with:

- Inspiring Attack +120 Str
- Sigmar's Fist +120 Str
- Big Swing -120 Str

Client displays my base Str value of 312 with all 3 active.

Please remember that you are required to post evidence before you make a massively contradictory report like this to avoid wasting my time.

**Comment by Yellowpillow** [comment]
You misunderstood me. Sorry for not posting those at first place:
![arena_024](https://cloud.githubusercontent.com/assets/18102127/14675448/15a57f3a-071a-11e6-9993-6ac0c4935fda.jpg)
![arena_026](https://cloud.githubusercontent.com/assets/18102127/14675447/15a535de-071a-11e6-9937-19885d3c9a5f.jpg)
1st is without debuff, 2nd is with debuff. Armor pot gives +495 armor. Covenant of tenacity + 363 armor. 
without debuff it should be 2108 armor (covenant not counts)
with debuff it should'nt be 788, it should be 2108 + 363 - 1320 = 1151 (covenant fills debuff partly). That how it works on live. 
Formula is: basic armor + strongest buff - (debuff - one strongest of overbuffs) 
It should works only with debuff, and without them everything is correct now and same buffs should'nt stuck.

**Comment by ozarmidrashim** [comment]
There is nothing to discuss, sorry. The client knows how it worked on live and it says you're wrong. I will not act on this report.

**Comment by Yellowpillow** [comment]
I swear to god it was like this on live, at least on 1.3 patch when we tested it last time. I even can gather some people who can confirm this.
Anyway it's your server and you decide how to make it. I just try to fill all holes i see, helpfull or, eventually, not.

**Comment by ozarmidrashim** [comment]
It's written in the rules for using the bugtracker that we don't really care about what you think you remember from live. The client disproves you, and whatever the client says is law. No arguments.

Understand that people have attempted to manipulate us in the past by offering false recollections about the live server. We CANNOT trust you simply because you claim it was that way on live.

**Comment by Yellowpillow** [comment]
I understand. Im apologize. I did not mean to offend and did not try to manipulate, just sharing memories.
