### ISSUE TITLE
[Pet] Magus pet doesn't attack Well of Qhaysh (T3 elven keep) doors

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5417]
I push his attack button but he dont do anything. By manually push horror's abilities i makes him attack doors one time, but after that he stand steel and not makes attempt to attack it again by himself or use autoattack.
![deadlysilence_005](https://cloud.githubusercontent.com/assets/18102127/14676511/cc1fa0a2-071e-11e6-99c9-88d1f1590708.jpg)
![deadlysilence_007](https://cloud.githubusercontent.com/assets/18102127/14676512/cc8dcac8-071e-11e6-9fff-7383937c1f6e.jpg)
![default](https://cloud.githubusercontent.com/assets/18102127/14676523/da695162-071e-11e6-9a1b-26dd8c36a3eb.jpg)
may be related to #2781

**Comment by Ryanfawkez** [comment]
As far as I know, it relates to pets being able to attack gameobjects in general.

This bug isn't specific to just the Flamer; Squigs, White Lions and Gun turrets have the same issue.

**Comment by Yellowpillow** [comment]
But all horrors perfectly attacks empire keep's outer doors
![default](https://cloud.githubusercontent.com/assets/18102127/14678500/f4715a3e-0726-11e6-8866-3a6a11d37ee7.jpg)
I assume this is somehow related to position of door itself.

**Comment by Yellowpillow** [comment]
Some more tests: pet can attack both inner and outer dwarfen doors, so my guess is there something wrong with elven keep itself.
![default](https://cloud.githubusercontent.com/assets/18102127/14712725/5b28ecec-07ef-11e6-8850-d64e95b6f98a.jpg)

**Comment by ozarmidrashim** [comment]
No longer an issue
