### ISSUE TITLE
Order Guild "Sylvan" have 2 guild leaders.

### ISSUE THREAD

**Issue by Kali14** [WarEmu/WarBugs#5419]
Hi, Im Nikolaj, leader of guild Sylvan. I creat this guild 14.04.2016. Few hours after that was restarting server. After this restart to guild joined also some destro players with their leader. Some destro players has creat an destro guild this same day. Of course I kicked them when I sawthem in my guild.  Next day, this is 15.04.2016, to guild Sylvan joined next 3 destro players, and I kicked them too. After this time they stop joined to Order guild Sylvan. But in my guild is still their leader, Choosen 10 lvl, but he is afk from 4 days and him, can't just kick off because he is leader same like me. Sylvan have today (20.04.2016) 6-7 lvl and Im just afraid what this choosen can do in future with my order guild.

**Comment by Kali14** [comment]
I try put screenshoot of guild roster but don't know how.

**Comment by Mourdechai** [comment]
drag the screenshot itself into the comment box and it will be attached.

**Comment by Kali14** [comment]
[ file:///C:/Documents%20and%20Settings/Administrator/Moje%20dokumenty/Moje%20obrazy/sylvan%20leader.bmp ](url)

**Comment by Kali14** [comment]
![mmmm](https://cloud.githubusercontent.com/assets/18577119/14685233/10d0fb46-0734-11e6-8665-89821caa5b39.JPG)

**Comment by Kali14** [comment]
There isnow a next Bug with guild roster. Show only 1 person who is online.

![kkkkl](https://cloud.githubusercontent.com/assets/18577119/14699001/50b32a1c-0794-11e6-978b-c68e4aea7c9c.JPG)

**Comment by Evildoor** [comment]
#1438
