### ISSUE TITLE
intermittent driver crash

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#542]
Hi... I have been experiencing this issue from time to time for most of the time I've been playing RoR (at least the past 3 months)...

Hard to describe but occasionally I get a total system freeze which usually lasts for 5-10 seconds, in which time I cannot do anything then I the system return to normal but with a message that my driver crashed (graphics driver).

This only happen with RoR

Also present on my last Windows 8.1 install 64 bits
AMD 7750 HD graphics card.

I don't know what else is causing this but nobody else seems to be having this kind of issues??

**Comment by gittoaster** [comment]
more speculations...

I usually get this sort of thing during scenario or after a scenario... once when respawning..

**Comment by Damiel126** [comment]
Hmm. I got this exact issue with the same setup - 8.1, 7750. Then my 7750 blew out completely, I switched to my onboard graphics, and no problems since. Also I didn't have the same issues on my laptop or my other PC.

**Comment by Elvenalthur** [comment]
I've heard in recent times that some of the later AMD drivers cause kernal crashes, and killed some cards ;)

Mmmm, try downloading an older version of their drivers and see if it still happens?

FYI, this would of been better posted on forum, as it's not related to in game bugs.

**Comment by gittoaster** [comment]
[quote] I've heard in recent times that some of the later AMD drivers cause kernal crashes, and killed some cards ;)[/quote] do you mean in Warhammer or just in general??

**Comment by Evildoor** [comment]
Since this is related to hardware and the game in general, not RoR, this problem (if it still exists) belongs to the Technical Support forum section. Closing.
