### ISSUE TITLE
.unlock not working for my account

### ISSUE THREAD

**Issue by Narcoticx** [WarEmu/WarBugs#5420]
Don't know if others have this problem aswell, but if I type .unlock in say chat my char actually says .unlock. It also doesn't do the little "jump".
Can't join scenarios now when getting the "in combat" bug.

**Comment by Tiggonos** [comment]
can you provide a screenshot?

**Comment by kaey** [comment]
Dot commands are not implemented in custom channels, like /t1 or /8.
Try typing: 
/s .unlock

**Comment by Chummi** [comment]
Tiggo & Kaey, whether Narcoticx or the guild he plays in lacks game experience. We tried everything to free him including macros. Yet he can't get rid of the bug. How should a screenshot help? He types the command and nothing happens. What do you want to see? 

PS: We tried close to everything including the old /s &jump and other things. 

So please try to provide a solution if you post, thanks :)

**Comment by Tiggonos** [comment]
well. then good luck.

lol
