### ISSUE TITLE
Destro epic weapon quest in Chaos - reward for Squig Herders

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#5422]
Spear reward "Impala' of Entropy' from INEVITABLE POWER is a great spear, requiring both hands to use. Obviously, Squig Herders use one handed spears with the Offhand or Mainhand property. 
Unfortunately I didn't realise this until after I'd selected the reward.

**Comment by Ryanfawkez** [comment]
https://github.com/WarEmu/WarBugs/issues/4926

General fix was applied which made the majority of Squig Herder spears one-handed in the main hand slot only. Will be live with the next patch.
