### ISSUE TITLE
Gnol Baraz (Order dwarfen keep in t3) have wrong scope

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5423]
As it can be seen on screenshots there is half of Gnol Baraz keep's scope is not defined as related to it. I cant tell if this was on live like this or not, but it seems not right anyways.
![default](https://cloud.githubusercontent.com/assets/18102127/14713476/550b6f26-07f2-11e6-8602-395777fa3799.jpg)

**Comment by sioding** [comment]
**Thanks for the report.** Since there is no confirmation, i will close this issue now. Please make sure to follow the bugtracker rules which you can find here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)
