### ISSUE TITLE
Cultivating: Special Moment on 175 seeds yields a lvl 1 plant

### ISSUE THREAD

**Issue by aglarang** [WarEmu/WarBugs#5424]
Recently while leveling up Marshroot seeds, I had a special moment harvesting a lvl 175 seed/plant.  Instead of yielding a lvl 200 Marshroot plant, it gave me a lvl 1 Smoking Pyre Ivy plant.   I got the other results correctly (pigment and normal lvl plants.)  I am assuming this is a bug or a consequence of some of the lvl capping done for trade skills.
I will try this again and capture a screen grab.  At the time I did it, I did not think to screen cap it.

**Comment by Evildoor** [comment]
#5402 may be related.

**Comment by aglarang** [comment]
Evildoor,  That is exactly the same issue.  My searches did not yield that defect, so I created a new one.  If someone can merge these, or close mine and continue with the earlier one.  Thanks.
