### ISSUE TITLE
Well of Qhaysh doors (other t3 keep's doors) strange positioning

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5425]
I test it with choppa's ability "Go for da soft spot" which is working only if target facing away.
Results: 
1. Well of Qhaysh inner and outer door can't be hit by that ability 
2. Any of the doors of the other 2 order's keeps can be hit by that ability.
My guess is the problem with position of keep doors.
Also this is may be related to problem with pets: #5417 
![1](https://cloud.githubusercontent.com/assets/18102127/14714562/86390744-07f6-11e6-8261-680e060e0672.jpg)
![2](https://cloud.githubusercontent.com/assets/18102127/14714563/86393bd8-07f6-11e6-8852-4ff9f6a0425d.jpg)
![3](https://cloud.githubusercontent.com/assets/18102127/14714564/8639640a-07f6-11e6-8dc6-7cf9415bfdda.jpg)
![4](https://cloud.githubusercontent.com/assets/18102127/14714566/863b036e-07f6-11e6-9c7a-527673620a2f.jpg)
![5](https://cloud.githubusercontent.com/assets/18102127/14714565/863ab62a-07f6-11e6-96d7-56a551bbff80.jpg)
![6](https://cloud.githubusercontent.com/assets/18102127/14714567/863d623a-07f6-11e6-8c4d-722aaa301030.jpg)

**Comment by Lheana** [comment]
Has this been fixed?

**Comment by raptrr** [comment]
No further information, closing this issue.
