### ISSUE TITLE
Bugged TOK Unlock - Where Did You All go?

### ISSUE THREAD

**Issue by Eusebeus82** [WarEmu/WarBugs#5427]
Hi

We've encountered a bugged TOK unlock that I think you should be in a position to fix. The unlock "Where did you all go?" should simply involve killing the Champion; Lost Horror in Blighted Isle. I have killed this mob solo, and again as shown in the screenshots below, but no unlock has been recieved.

Can you look into this? Thanks

![eusebeus_006](https://cloud.githubusercontent.com/assets/18599533/14716716/2a22ef02-07e6-11e6-97ed-2582421cfaeb.jpg)
![eusebeus_005](https://cloud.githubusercontent.com/assets/18599533/14716720/2cb562a4-07e6-11e6-80d1-68be62792d92.jpg)

Eusebeus

**Comment by Vayra** [comment]
Should be fixed in next patch according to #5400
