### ISSUE TITLE
Bugged TOK visual - Beach Bum

### ISSUE THREAD

**Issue by Eusebeus82** [WarEmu/WarBugs#5428]
Hi

The TOK bestiary unlock Scorpion: Beach Bum is bugged in a minor way. When killing the champion Baneclaw in SW Blighted Isle, the unlock flashes on screen and grants XP and the title; Scorpion Squisher (as intended). The unlock remains un-ticked in the TOK however. Can you look into tidying this up - realise this is low priority, but it is annoying :)

![eusebeus_008](https://cloud.githubusercontent.com/assets/18599533/14717032/819b0a5c-07e7-11e6-8601-9125d18d7d92.jpg)
![eusebeus_007](https://cloud.githubusercontent.com/assets/18599533/14717031/819a4162-07e7-11e6-884c-e394ed80068c.jpg)

Thanks

Eusebeus

**Comment by Vayra** [comment]
Should be fixed in next patch according to #5400
