### ISSUE TITLE
Nekkid toons - spawning with no inventory

### ISSUE THREAD

**Issue by Damiel126** [WarEmu/WarBugs#543]
Created some toons tonight and they had no gear on the character selection screen.

When I logged in they had nothing equipped and nothing (not even the book of binding) in inventory.

Looks like it might have happened to the guy behind me too.

Recreated the toon and the same issue. Made a new toon of the same class and same issue. Others in chat had same issue. Hopefully will be resolved with reboot.

![untitled](https://cloud.githubusercontent.com/assets/10399547/5702474/dae05c54-9aae-11e4-97f4-41162c2b7b3b.png)
![viruindaw_002](https://cloud.githubusercontent.com/assets/10399547/5702506/401af8cc-9aaf-11e4-8a2b-b0d76d187b59.jpg)

**Comment by ozarmidrashim** [comment]
Probably related to an issue with the database running out of space. Likely to be fixed.

**Comment by MaxHayman** [comment]
If you recreate the character now, it should be fine.
