### ISSUE TITLE
Ghoul (Rauklus) - Foul Amongst the Fowl

### ISSUE THREAD

**Issue by WARchosen** [WarEmu/WarBugs#5430]
Ghoul (Rauklus) - Foul Amongst the Fowl
BESTIAL TOME TACTIC
BADLANDS @ 19, 10. killing npc name Rauklus i do not get bestial tom tactic

**Comment by Evildoor** [comment]
Tome tactics are not implemented yet, so no need to report them.

**Comment by WARchosen** [comment]
Horror of Tzeentch (Golmir) - Pack of Three
DAEMONIC TOME TACTIC
(D) & (O)
AVELORN @ 62, 14. He's in a slight depression in the far E wall of the mt and is a L23 champ, also two non-champ L23 spiders come along for the fun.

this tome tactis work

**Comment by Evildoor** [comment]
I asked the DB team, they said that tome tactics shouldn't be working. Well, maybe one or two got implemented.
