### ISSUE TITLE
Ogre Tyrant (Graw Leadgut) - Not What it Appears

### ISSUE THREAD

**Issue by WARchosen** [WarEmu/WarBugs#5431]
Ogre Tyrant (Graw Leadgut) - Not What it Appears
"The Liberator"
BADLANDS @ 63, 36 . Enter the cave. Kill this L29 Champ and inspect the medal he drops. NOTE: If you kill him in a group, he only drops 1 medal, so you'll have to kill him several times.

when i loot the maedal and inspect him i do not get a title "The Liberator"

**Comment by Evildoor** [comment]
#4433
