### ISSUE TITLE
Troll (Mudbelly Troll) - Who Is Up for Seconds

### ISSUE THREAD

**Issue by WARchosen** [WarEmu/WarBugs#5433]
Troll (Mudbelly Troll) - Who Is Up for Seconds
POCKET ITEM
BADLANDS @ 35.5, 33.5 and along the road S of the C11 Dwarf camp. These trolls drop Troll's Dinner. Examine the item to get an unlock for the pocket item: A Troll's Pet Kitty. Drop rate has been nerfed, so get ready for a lot of farming.

when you loot the Troll's Dinner nothing happen when you inspect this item

**Comment by Evildoor** [comment]
#4619
Please, use search.
