### ISSUE TITLE
Vulture (Vulture Feeder Parts) - Feeding Time...

### ISSUE THREAD

**Issue by WARchosen** [WarEmu/WarBugs#5434]
Vulture (Vulture Feeder Parts) - Feeding Time...
"The Main Course"
 BADLANDS @ 35, 27.5. WARNING: buggy. Examine the Vulture Feeding Parts. NOTE: Try destroying the "Feeding Post" stand to make it work. If that doesn't do it, it may be possible that we need to speak with someone first, or locate a different item prior to activating the feeder.

there is no such thing as Vulture Feeding Parts and "Feeding Post"

**Comment by Ryanfawkez** [comment]
Indeed there are no Vutlure Feeding Parts or Feeding Post, there are however a Vulture Feeder Post and a Vulture Feeder about at the correct coords.

**Comment by Ottogrim** [comment]
Working fine, got the unlock on 2 PC

**Comment by Evildoor** [comment]
Closing as false report.
