### ISSUE TITLE
Shaman's Ability: Yer A Weaklin'

### ISSUE THREAD

**Issue by Catholicism198** [WarEmu/WarBugs#5436]
Yer A Weaklin' gets the visual effect from Gork's Waaagh! even though it does not benefit from it. Visual bug?

**Comment by Evildoor** [comment]
Visual effect? You mean icon on the panel lights up?

**Comment by Catholicism198** [comment]
Yes, that is correct. It's nothing major. It doesn't reset Gork's Waaagh! It's just a minor bug worth pointing out.

**Comment by Evildoor** [comment]
Uh, then i'm pretty sure that it's a client issue - we can't do anything in such case.

**Comment by ozarmidrashim** [comment]
Can't do anything about it.
