### ISSUE TITLE
Magus' Daemonic Reach tactic - Dissolving mist

### ISSUE THREAD

**Issue by Catholicism198** [WarEmu/WarBugs#5437]
Daemonic Reach does not effect Dissolving Mist ability- it changes the range of the reticle? and tool tip information- the ability does not activate past it's initial 65ft

**Comment by Evildoor** [comment]
Tested, tactic properly increases range.

**Comment by Catholicism198** [comment]
It works sometimes...when you first equip get/equip the tactic- but after you log it stops working. I try uploading a video.

**Comment by Torquemadra** [comment]
#3835

this is actually a problem thats still persisting in various forms. If cast after 65ft but before 81ft while moving it will often fail and go onto cooldown. This doesnt seem to be happening with napalm grenade.

if you try to play mist/napalm while mounted it will almost invariably fail.

**Comment by Evildoor** [comment]
Tested after relogging and after dying, everything works. So yes, video, please.

**Comment by Evildoor** [comment]
No proof, closing.
