### ISSUE TITLE
Some greenskin quests lack coding

### ISSUE THREAD

**Issue by bender072** [WarEmu/WarBugs#544]
![garinold_000](https://cloud.githubusercontent.com/assets/10451423/5714126/045c482e-9a8a-11e4-8032-511c5b61b2c3.jpg)
![garinold_001](https://cloud.githubusercontent.com/assets/10451423/5714127/07b83ffa-9a8a-11e4-84af-b8f7827afd49.jpg)
![garinold_002](https://cloud.githubusercontent.com/assets/10451423/5714130/0a2f1fba-9a8a-11e4-8fd5-cb481a503ba7.jpg)

The requirements for the quests show up as missing coding

**Comment by Evildoor** [comment]
Quests shown here have proper text now.
