### ISSUE TITLE
Magic resistance

### ISSUE THREAD

**Issue by ClintEastwod** [WarEmu/WarBugs#5440]
I got 900+ corporeal resistance on my sorc (with chosen aura). It should be about 50% dmg reduction. In fact the corporeal dmg reduction is about 20%. So what wrong with it? I believe there was no KOTBS nearby and I might be debuffed only by BW for 300 or so. Or this is special mode for BW only? Becouse my spirit spell resisted very well by order. You may see both examples on the screenshot attached.
And why BW may cast Sear (1 sec cast) and Pyroclastic Surge (2 sec cast) just during 1 second??
![warlog](https://cloud.githubusercontent.com/assets/18602535/14722515/8d98d410-0814-11e6-8fe2-0e3941b5815e.jpg)

**Comment by Pxl555** [comment]
When you say you "believe" that there wasn't a knight nearby and that you have 900+ corp resistance it would be nice showing the full ui with the stats screen at least so we can actually see what is happening around you.

**Comment by ClintEastwod** [comment]
You are right, my bad. But I don`t have such screen, I made the combat log screen after I left the fight. I ll try to catch the issue and screen it.


>Пятница, 22 апреля 2016, 3:10 +03:00 от Pxl555 <notifications@github.com>:
>
>When you say you "believe" that there wasn't a knight nearby and that you have 900+ corp resistance it would be nice showing the full ui with the stats screen at least so we can actually see what is happening around you. 
>—
>You are receiving this because you authored the thread.
>Reply to this email directly or  view it on GitHub


С уважением,
Орлов Михаил

**Comment by Evildoor** [comment]
> And why BW may cast Sear (1 sec cast) and Pyroclastic Surge (2 sec cast) just during 1 second??

Was always possible (and even more, see #5192, for example). Sorcerer can do the same.

Resists and other stuff - proof, please.

**Comment by ClintEastwod** [comment]
Thanks for your answer!
Could you explain me plz how it works?

" Backloaded Pyroclastic Surge into Sear into Nova. GCD is 1.1s here "

If I got 2 spells? one is 1 sec cast and second spell is 2 sec cast, how I may burst them in 1 moment?

>Пятница, 22 апреля 2016, 10:00 +03:00 от Evildoor <notifications@github.com>:
>
>>And why BW may cast Sear (1 sec cast) and Pyroclastic Surge (2 sec cast) just during 1 second??
>Was always possible (and even more, see  #5192 , for example). Sorcerer can do the same.
>Resists and other stuff - proof, please.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly or  view it on GitHub


С уважением,
Орлов Михаил

**Comment by Evildoor** [comment]
Sorry, i'm not a BW/Sorc specialist, so you should ask one in game / on forums.

**Comment by Pxl555** [comment]
The way Pyroclastic Surge work is that when you cast it actually has a travel time before it lands , where as Sear and Nova hit almost the instant you fire them off, resulting in you landing all 3 spells at the same time.  If you add boiling blood and slow boil into the mix you can make all 5 spells ,given proper timing , land at the same time.

**Comment by ClintEastwod** [comment]
Got it, Thanks.


>Пятница, 22 апреля 2016, 12:19 +03:00 от Pxl555 <notifications@github.com>:
>
>The way Pyroclastic Surge work is that when you cast it actually has a travel time before it lands , where as Sear and Nova hit almost the instant you fire them off, resulting in you landing all 3 spells at the same time.  If you add boiling blood and slow boil into the mix you can make all 5 spells ,given proper timing , land at the same time.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly or  view it on GitHub


С уважением,
Орлов Михаил

**Comment by Evildoor** [comment]
No confirmation provided, closing.
