### ISSUE TITLE
Spider, Giant - Tacky Decor

### ISSUE THREAD

**Issue by WARchosen** [WarEmu/WarBugs#5441]
Spider, Giant - Tacky Decor
"Spider-Slayer"
BARAK VARR @ 5, 28. Go to the cave N of the zone entrance. BONUS: Lore unlock by examining the statue nearby.

when you enter the cave nothing happens

**Comment by Sapphiratelaemara** [comment]
Should also trigger when entering cave in Troll Country:
![image](https://cloud.githubusercontent.com/assets/23622177/20518942/47bf58b6-b0a1-11e6-98ae-496842b9c932.png)

and Norsca:
![image](https://cloud.githubusercontent.com/assets/23622177/20518970/641cd010-b0a1-11e6-8eb8-e78160ad996b.png)
