### ISSUE TITLE
More amount of Renown, Experience and Influence should be gained near BO

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5443]
Usually near any Battlefield Object buff for 150% was given, which granted additional 50% of Renown, Experience and Influence as long as enemy character been killed inside BO zone by player whose character also was inside that BO's zone. Now it not work and there is no buff near BO.
That buff stimulated people to take war actions near battlefield objects.
![default](https://cloud.githubusercontent.com/assets/18102127/14728611/5be4d094-0847-11e6-950d-8d94e9723e2b.png)

**Comment by RichardCRoR** [comment]
yes this is accurate. it happened to me as well..

**Comment by Evildoor** [comment]
RVR system is being reworked, so this is obsolete.
