### ISSUE TITLE
No reward for defending Battlefield Objective

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5444]
On live there was rewards for defending BO, more precisely for killing enemy players inside BO which is controlled by your realm or being rechecked by your realm.
Formula was rediculously easy: all of renown gained from death enemy players inside BO's scope (renown gained by healing does'nt count) was summed up and saved in pull, and after i believe 5 minutes or so all renown in pull was shared between all players who will be inside BO's scope at that moment. 
For example: inside bo was killed 5 people, each of them give 500 renown, 2500 renown in pull. In 5 min on BO was 2 people, each of them gain 1250 renown.
That feature greatly increase enthusiasm of players to defend BOs and make attempts to take back BOs which was attacked.
Now defending BO and kill somebody near it dont give anything.
![default](https://cloud.githubusercontent.com/assets/18102127/14729018/05fe0c5a-084b-11e6-92a9-7be352403a46.jpg)

**Comment by Evildoor** [comment]
RVR system is being reworked, so this is obsolete.
