### ISSUE TITLE
[Item] Sigmarite Graceblade Off Hand flag

### ISSUE THREAD

**Issue by grabalek** [WarEmu/WarBugs#5445]
Small issue but annoying. Witch Hunter's **Sigmarite Graceblade**, a reward from empire epic quest, has both Main Hand and Off Hand flag enabled. This makes it impossible to change it's appearance with any sword without Off Hand flag on, as the item types don't match. I belive the same might be true for the other sword from elf epic quest.

**Comment by Ryanfawkez** [comment]
There should be NO either hand Empire swords, thank you for reporting this. A blanket fix to make all Empire swords main hand only is pending.
