### ISSUE TITLE
PQ Grave Diggers - Quest Corruption of Desire [Public Quest] [Quest]

### ISSUE THREAD

**Issue by Frather** [WarEmu/WarBugs#5447]
![frather_009](https://cloud.githubusercontent.com/assets/18612335/14737913/f577de36-087e-11e6-854c-55d27827e880.jpg)
![frather_010](https://cloud.githubusercontent.com/assets/18612335/14738020/80bde166-087f-11e6-8fd3-93ae125ded2e.jpg)
There will be no mob in the area of PQ-Gravediggers and are required to complete the quest Corruption of Desire. Lost the whole chain of quests.

**Comment by Evildoor** [comment]
#5416
