### ISSUE TITLE
item bag issues / potions disapearing

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#5449]
there are other bug reports about it from january, but this is new to me.

besides i get those msgs in chat about it:

![melquardt_001](https://cloud.githubusercontent.com/assets/13809443/14746500/392b5514-08b0-11e6-9cfa-6b583df4b255.jpg)

**Comment by Tiggonos** [comment]
they back again after i bought the third bag!

hope it helps ;)
![melquardt_002](https://cloud.githubusercontent.com/assets/13809443/14746528/5d80affe-08b0-11e6-82a7-e729a2061de5.jpg)

**Comment by Tiggonos** [comment]
when using them, they change position and another error msg appears.
![melquardt_003](https://cloud.githubusercontent.com/assets/13809443/14746638/d42c103a-08b0-11e6-85ca-99d223717e3c.jpg)

**Comment by xyeppp** [comment]
Have you got item filtering turned on in bags? Click those < next to each bag, and check.

**Comment by Tiggonos** [comment]
good hint! on the fourth back item sorting was on by default. So it tried to move the potions to that bag although i didnt bought it yet and made it dissapear.
