### ISSUE TITLE
High Elf guards spawning in Narthain Dark Elf camp

### ISSUE THREAD

**Issue by Damiel126** [WarEmu/WarBugs#545]
Swordmasters spawning as guards near Overseer Rathus in Narthain, Blighted Isle (8.5k,13.5k).
![viruindaw_010](https://cloud.githubusercontent.com/assets/10399547/5740075/51abc5de-9c54-11e4-882f-d388e1bed95a.jpg)

**Comment by Styrkarr** [comment]
I didn't find any Swordmasters as this place. All seems to be ok.

![styrkbg_000](https://cloud.githubusercontent.com/assets/15971981/11766662/7edca642-a192-11e5-9b91-842a6f641299.jpg)

**Comment by Meralors** [comment]
Must have been fixed. closing
