### ISSUE TITLE
Parry and Weapon Skill + .getstats not work together

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5450]
.getstats command dont see parry gained from weapon skill stat
character window instead see parry from WS, but don't see parry from onehanded weapons, which is not have problem in .getstats
![1](https://cloud.githubusercontent.com/assets/18102127/14747439/2c7da8de-08c5-11e6-864e-1710051fadef.jpg)
![2](https://cloud.githubusercontent.com/assets/18102127/14747438/2c7cedc2-08c5-11e6-85f4-390d0cf66cab.jpg)
![3](https://cloud.githubusercontent.com/assets/18102127/14747437/2c7ce02a-08c5-11e6-87c7-e4165ddbfc31.jpg)
I can test othed secondary stats if you want.

**Comment by ozarmidrashim** [comment]
getstats will not report stats which are not purely linear or multiplicative. Parry from weaponskill depends on the enemy's attacking stat. Please don't report this as it will never be changed.
