### ISSUE TITLE
Unable to take out the guild standard

### ISSUE THREAD

**Issue by Natherul** [WarEmu/WarBugs#5452]
I managed to set the standards for the guild with the .standard playername but I cant use the standard, no errors or anything it just wont actually be used.

**Comment by Natherul** [comment]
not sure if this report would benefit from it but heres a log when I try and use a standard
[sniff_h08m20.txt](https://github.com/WarEmu/WarBugs/files/232821/sniff_h08m20.txt)

it would seem the command to use item is sent but then no response is given from the server for it?

**Comment by Kepli** [comment]
I also have this problem a fix would be great
