### ISSUE TITLE
High Elf Foreman - Pulled by Pet or AOE

### ISSUE THREAD

**Issue by shibirian** [WarEmu/WarBugs#5453]
We've defended the Order keep in Saphery today.

Suddenly, on the roof over the keep door, there was AOE (this pink purple circle thing - forgot the name) and a squiggy jumping around - then, suddenly, the Foreman came through the roof and went into attacking stance and then kept standing there.

Rest see screens.

![cyriana_095](https://cloud.githubusercontent.com/assets/17605387/14757132/a543ecf8-08f0-11e6-8144-d27f76240d9b.jpg)

**Comment by sioding** [comment]
Could not reproduce.
