### ISSUE TITLE
Dark Elf RVR T3 Influence NPC Varil Shadowsage Missing

### ISSUE THREAD

**Issue by HunterBlackstone** [WarEmu/WarBugs#5456]
I and others cannot locate the Rally Master Varil Shadowsage for the Dark Elf Teir 3 Rewards. Believe he is missing.

**Comment by HunterBlackstone** [comment]
Player Doubletap finally found this NPC next to Thasan WIndwatcher. However, he does not have a Name Plate. He also has no icon above his head, and is not on the map at all.

**Comment by Evildoor** [comment]
#4798
