### ISSUE TITLE
kill message in chat

### ISSUE THREAD

**Issue by ellionkeman** [WarEmu/WarBugs#5457]
I was killed by Invalidname19.

![kemahn_030](https://cloud.githubusercontent.com/assets/18136746/14759827/55b93956-0939-11e6-820a-99f49a106608.jpg)

**Comment by xyeppp** [comment]
That is, literally, somebody's name that was changed a long, long time ago. To close.

**Comment by Evildoor** [comment]
Closing per xyeppp.
