### ISSUE TITLE
Choppaz Wood Camp Flag - T3 Elf RvR

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#5459]
The Battlefield Objective flag at the Choppaz Wood Camp has two flag models, which are on top of the other. However, when capturing the flag, only one of these is clickable and you have to have your cursor in the "sweet spot" to click the cappable flag.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
