### ISSUE TITLE
Bag glich

### ISSUE THREAD

**Issue by Gromf1988** [WarEmu/WarBugs#5460]
Faulty display shows the bags and items in it
all the cherecters

**Comment by Evildoor** [comment]
Description not clear. Screenshot?

**Comment by Gromf1988** [comment]
![kventel_000](https://cloud.githubusercontent.com/assets/18628267/14765001/93edceec-09d6-11e6-8110-2faf016be6e6.jpg)
![kventel_001](https://cloud.githubusercontent.com/assets/18628267/14765002/93efc27e-09d6-11e6-9e39-3147d68e5c13.jpg)

**Comment by Gromf1988** [comment]
helped reinstall the client

**Comment by Gromf1988** [comment]
the problem is somewhere in the folder "user"

**Comment by Evildoor** [comment]
Ok then.
