### ISSUE TITLE
Both Ghrond's Choppa and Karaz Choppa isn't salvageable

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5461]
Both Ghrond's Choppa and Karaz Choppa (influence rewards for Choppa, dark elves t3, greenskin t2) isn't salvageable
![default](https://cloud.githubusercontent.com/assets/18102127/14760814/87883e4e-095e-11e6-969b-33701bd19c51.jpg)

**Comment by Abolition** [comment]
Evildoor, you could probably tie it in with the ticket I opened regarding the DOK weapons, which was for Karaz and Spite's Xiphos.

**Comment by Evildoor** [comment]
I don't see any point in that.

**Comment by Abolition** [comment]
I worded that badly. I guess I meant to say that there appears to be multiple RvR INF rewards that aren't salvagable.
Jewel pieces are also not salvagable.

**Comment by Evildoor** [comment]
Oh, that's quite possible. Exact names should be reported.

**Comment by Yellowpillow** [comment]
I dont think that jewelry for infl. was salvajeable on life.

**Comment by NorKalli** [comment]
fixed these two items

**Comment by sioding** [comment]
fixed with patch from 05.05.2018
