### ISSUE TITLE
bound to player item can be given to another player

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5462]
Rune-Scribed Squigkickas. It's clearly say Bound to player. 
However i receive it from mail, paying for it. After that i can't send it to another person, game say i can't because it bounded.
After that i put this item into guild vault and manage to take it by another character. Same as Devastator/duelist gloves/boots.
I can't tell is that bug with this item itself or there is boundage global bug.
![default](https://cloud.githubusercontent.com/assets/18102127/14761042/766b7124-0965-11e6-816e-ec988c7f2042.jpg)

**Comment by Ryanfawkez** [comment]
Just a visual bug. It won't be actually bound to you until you wear it, which means it can still be sold on the Auction House and put in the Guild Vault. You could also mail it with a work-around.

**Comment by Yellowpillow** [comment]
Work-around not work eventually
![default](https://cloud.githubusercontent.com/assets/18102127/14761262/f5b35d38-096b-11e6-937f-9cd18ba3e77f.jpg)

**Comment by Ryanfawkez** [comment]
Work-around does work if you know how to use it. Take an item you can trade, drag the 'BoP' item to it and instantly right click as they swap while in the mail window.. Should work if you time it correctly.

**Comment by Yellowpillow** [comment]
Sounds like using bugs, which i strongly against of. But i think i have no choice. Anyway i just want to make report, friendly reminder for future. I guess in ten years little bug reports like this may be helpful to make you occupied, if you run out of ideas what to fix =D

**Comment by Lheana** [comment]
BoP items can no longer be moved into the guild vault.
