### ISSUE TITLE
Bugged TOK - Killing 1000 goblins

### ISSUE THREAD

**Issue by Eusebeus82** [WarEmu/WarBugs#5464]
Hi

Killing 1000 goblins does not correctly award the "Kill 1000 Goblins" unlock. It instead awarded me the "The History of the Goblins" unlock instead.

![eusebeus_011](https://cloud.githubusercontent.com/assets/18599533/14761187/a8e69c4c-0950-11e6-9557-3c7adce10430.jpg)
Can you look into this thanks
Eusebeus

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by Eusebeus82** [comment]
Also, I can confirm the Orc and Empire ones have the same error. How I've got 1000 Empire kills as Order is sad... :(
