### ISSUE TITLE
Big Choppa of Conquest does not count as a great weapon for Da Big Un' 

### ISSUE THREAD

**Issue by MagnusLindstrom88** [WarEmu/WarBugs#5465]
When you try to do Da Big Un' equipped with a "Big Choppa of Conquest" You get the message "Requires a Great Weapon", even though the weapon is a two-handed Great Axe.

**Comment by Evildoor** [comment]
Tested, works fine on my BO (and on Choppa too, Weaklin Killa).

**Comment by Torquemadra** [comment]
theres 2 named the same in the DB because.... well I dont know....

Fixed next patch

**Comment by CptDavis** [comment]
Level 8 BO using Survivalist's Bigchoppa of Vengeance. This is a great axe but I am not able to use it with the Dabig Un' skill. Says I require a great weapon.

**Comment by Evildoor** [comment]
Make a separate report for this, please. Same problem, but items are different. And this issue should have been closed.
