### ISSUE TITLE
What Do We Have Here? (Zealot) - ToK

### ISSUE THREAD

**Issue by MagnusLindstrom88** [WarEmu/WarBugs#5466]
What Do We Have Here? (Zealot)
NORSCA: X42-Y:63

"Work your way south along the edge of the RVR lake, on top of the ridge. You will find the scroll behind a burned out farmhouse at this location, Grants the Smoking Skull Pocket Item"

Does not currently grant the Smoking Skull Pocket Item when you loot the scroll.

**Comment by Ryanfawkez** [comment]
Pocket items are not instantly rewarded upon gaining ToK unlocks. You need to buy them at the capital city library once you've gained the unlock.
