### ISSUE TITLE
Free bank glitch?

### ISSUE THREAD

**Issue by Clawfinger84** [WarEmu/WarBugs#5467]
My bank has been completely unlocked, free of charge. 
both additional tabs are unlocked and working. 
Is this intended or is my Magus (max rank, rr & culti) glitched?

**Comment by Ryanfawkez** [comment]
There was a time back when bank tabs did not have to be purchased. If you've made your character back then, you won't have to purchase new bank slots. If you had to prior buy these slots on the same character that now has them all unlocked for free; that's not intended.

**Comment by Clawfinger84** [comment]
Oh, alright, yeah it is a very early character
