### ISSUE TITLE
Incorrect RVR area: Nordland

### ISSUE THREAD

**Issue by Hellconbrood** [WarEmu/WarBugs#5468]
I found out that northland is complete a RVR-Lake. I run on the road from norsca to northland and when i entered northland the RvR-countdown started and when i run back to norsca it stopped. This issue comes with the last update.

greetings
Squighoppa

(sry for my bad english -.-)

**Comment by Yellowpillow** [comment]
a little bit visual here
![5ex4d_2cijs](https://cloud.githubusercontent.com/assets/18102127/14889555/55a33224-0d70-11e6-9543-cc536765c885.jpg)

**Comment by saupreusse** [comment]
Its only "ravenraid" that is marked as an RVR lake.

**Comment by saupreusse** [comment]
Fixed...
