### ISSUE TITLE
Human, Bandit (Fay Val) - Treaty for Treasure

### ISSUE THREAD

**Issue by WARchosen** [WarEmu/WarBugs#5470]
Human, Bandit (Fay Val) - Treaty for Treasure
POCKET ITEM
(D) CHRACE @ 48, 8. The 3 NPCs are up a ramp from the water right under the bridge connecting to the RvR area, W of Yenlui. The other mobs are L10 Amalyn Weber with her dog L20 Canine. Unlocks: Semi-lucky Charm.

killing those 3 npc nothing happens

**Comment by thorbolt80** [comment]
You musk kill Amalyn Weber L10 to have the pocket item.
