### ISSUE TITLE
hurtin' time under T1 debolster

### ISSUE THREAD

**Issue by GloomySam** [WarEmu/WarBugs#5477]
You are supposed to be unable to use skills and tactics above lvl 13 when you debolster to T1.
However, choppas (and slayers too, I assume, although I haven't checked that on slayer) can go to T1 PvE, turn on Hurtin' Time, then go out in T1 RvR and thus deliver more damage than they're supposed to.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
