### ISSUE TITLE
Empire: Warrior Priest: "Torn Holy Shirt" Has Wrong Armor Type of "Robe" Instead of "Medium Robe"

### ISSUE THREAD

**Issue by beddiecrokka** [WarEmu/WarBugs#5478]
Problem began when I took my Torn Holy Shirt off (Item ID 187608) and then couldn't put it back on. I could not use it as alternate appearance either. I then noticed in the item tooltip that it's listed as "Robe" instead of "Medium Robe" and Warrior Priest can not use "Robe" items.

Item should be re-classified as "Medium Robe" armor type.

Screenshot shows the item listed as "Robe" armor type.

![warrior_priest_body_armor_torn_holy_shirt_187608](https://cloud.githubusercontent.com/assets/18107644/14766764/baa733ae-09ca-11e6-9b91-c64c53d3dc93.jpg)

**Comment by Ryanfawkez** [comment]
Crap... my bad. Fixed in next patch.
