### ISSUE TITLE
[Nordland/Norsca] Flames of Change

### ISSUE THREAD

**Issue by wlfbck** [WarEmu/WarBugs#548]
One is supposed to scout "Lost Lagoon" (http://warhammer.gamepressure.com/warhammer_public_quest.asp?ID=379 marks the spot) but you do not get credit when reaching that spot.

**Comment by Evildoor** [comment]
Lost Lagoon RVR objective was removed from the game long ago, so this quest is pointless and should be removed (if not removed already), IMO.
Also, we have no way to check the correct area for scout/kill/whatever quests.
