### ISSUE TITLE
PQ's are brocken

### ISSUE THREAD

**Issue by Hellconbrood** [WarEmu/WarBugs#5480]
I tried Ekrund,Bloodhorn,MoM,Northland and Norsca. Only the first PQ in Norsca is working all others dont work. Most of the PQ's work in background but the PQ Stage Text did not refresh and did not show you the right stage. You can earn influence for the stage if you kill the right NPC but you cant read which NPC you must kill. When you relog you see the right stage with the killed and to be NPC`s. But if you kill some of that NPC on text it doesnt count.

I hope you understand what i mean.

greetings
Squighoppa

Sry for my bad english

**Comment by Evildoor** [comment]
Each PQ should be reported separately with description of its problems. Many of them were already reported, so use search before posting.
