### ISSUE TITLE
A Charmed Life

### ISSUE THREAD

**Issue by Averatos** [WarEmu/WarBugs#5487]
![averatos_012](https://cloud.githubusercontent.com/assets/16805605/14770321/2822ded4-0a6f-11e6-8fe9-24822790be23.jpg)

For what I recon there should be the icon on a cloak there and not the Bestial Token one.

Also there is ??? instead the cloak name there  after the unlock is completed.

**Comment by Lheana** [comment]
The only way to see it for now, is to talk to merchant who sells this cloak in Lyceum/Library, or to have the cloak in your inventory.
