### ISSUE TITLE
Lair Bosses Not Respawning

### ISSUE THREAD

**Issue by davidchicheung** [WarEmu/WarBugs#5489]
Seems like Lair Bosses are not respawning in T1 and T3 lair bosses.

T1 lair bosses are not respawning after 2:50 min respawn timer (checked after 3 hours)
T3 lair bosses are not respawning after 30-45 min respawn timer (waited full hour)

**Comment by Yellowpillow** [comment]
didn't theyre respawn timer is random?

**Comment by davidchicheung** [comment]
Seems like T1 lair bosses are between 2-4 hours? Randomly decided after death I assume. But in previous patch notes it was states that the T3 ones should be on a ~30 minute time if I am not mistaken?

**Comment by Luth-RoR** [comment]
Lair boss timers have a fixed + a random component. 30 minute timers seem to be _a little low_ for T3 and afaik they are the same for every lair.
Can be re-opened when with any evidence.
