### ISSUE TITLE
[Low priority] More duel bugs

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5490]
1. While duel your opponent can be healed by aoe heals if he in one party with you. Like DoK's ability Transfer Essence - you hit him to heal yourself and he heals as well. You can be healed by his own aura. Anything work in party.
![arena_020](https://cloud.githubusercontent.com/assets/18102127/14771274/e36b0fe6-0a96-11e6-87c6-d8f7cf215918.jpg)
![arena_021](https://cloud.githubusercontent.com/assets/18102127/14771275/e36b11d0-0a96-11e6-81ad-bfaccae557e9.jpg)
![arena_023](https://cloud.githubusercontent.com/assets/18102127/14771273/e36b06ea-0a96-11e6-97eb-cee37860b935.jpg)

2. if player 1 dueling with player 2 and near player 3 dueling with player 4 - they can hit each other, all four of them without any restriction. It's kinda fun tho, but not right in general.
![arena_017](https://cloud.githubusercontent.com/assets/18102127/14771291/d58e7092-0a97-11e6-8f37-9141781e035d.jpg)

3. If oponent invisible - you still can see him. 
![default](https://cloud.githubusercontent.com/assets/18102127/14771317/6da2dddc-0a98-11e6-8dad-2a8a896b0409.jpg)

probably related to #4765 and #2528

**Comment by Luth-RoR** [comment]
These kind of bugs will likely never be fixed as this is an unsupported feature that never existed on the mythic servers. Furthermore there could be client restrictions that can't be passed atm.
