### ISSUE TITLE
Promise of Battle Quest

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#5493]
The one you have to speak to cowering citizens.
It shows as completed on the NPC but its not.

**Comment by StaH84** [comment]
Issue:
- [ ] Again KotBS is recieving Intelligence (Lasting Potion of Insight) potion as a reward.

**Comment by Soulwhisper** [comment]
Major(probaply) issue here too for all classes.Needs to be changed to main stat for each class.

**Comment by Soulwhisper** [comment]
Re-opening this.Still looks as completed on the NPC but its not.

**Comment by NorKalli** [comment]
entire quest works
