### ISSUE TITLE
Warrior Priest Itemization

### ISSUE THREAD

**Issue by mrSVS** [WarEmu/WarBugs#5494]
Please fix some issues with influence items:

Open Rvr - Tier 2:
Mandred's Fists: 13Str, 13 WS, +1% Healing Critical
Stontroll Fists: 13 Willpower, 13 Wound, +1 Meele Critical
Need logical swap of critical chance: 
Mandred's Fists: 13Str, 13 WS, +1% Meele Critical
Stontroll Fists: 13 Willpower, 13 Wound, +1% Healing Critical

Open Rvr - Tier 3:
Wartrior Priest dont have helm with healing critical like other healers class:
Passwatch Helm: 22 Str, 8 Willpower, 14WS
Thickmuck Helm: 22 Str, 8 Willpower, 14 Tougness, +2% Melee Critical

Logical correction:
Passwatch Helm: 22 Willpower, 8 Wounds, 14 Tougness, +2% Healing Critical
Thickmuck Helm: 22 Str, 8 Wounds, 14 Weapon Skill, +2% Melee Critical

This changes is true ROR-style, like Devastator/Duelist itemization.

**Comment by Evildoor** [comment]
This kind of problems is known and will be handled later, no need to report them.
