### ISSUE TITLE
Flagged for rvr all over the Nordland and receive coward's reward

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5496]
anywhere i try to get into Nordland i receive a coward's reward. After relog game put me into warcamp and get me flagged for rvr again. There is nowhere to hide. 
![5ex4d_2cijs](https://cloud.githubusercontent.com/assets/18102127/14785180/80b1c3c6-0b0a-11e6-8d72-b7a0fea828a3.jpg)
i think i saw report alike mine, but can't find it...

**Comment by Evildoor** [comment]
#5468

**Comment by Yellowpillow** [comment]
Yes, that it. Can't find him because dude make mistake in "Nordland"
