### ISSUE TITLE
Incorrect RVR area: Blighted Isle

### ISSUE THREAD

**Issue by Eusebeus82** [WarEmu/WarBugs#5497]
Hi

The area in Blighted Isle, Fire Crystal Caverns is incorrectly flagged as the RVR lake once you get slightly inside (it's not even close to it).

![eusebeus_023](https://cloud.githubusercontent.com/assets/18599533/14789279/b6023710-0b03-11e6-841f-5c9a0edcb3b6.jpg)
![eusebeus_024](https://cloud.githubusercontent.com/assets/18599533/14789296/cae455b4-0b03-11e6-8265-f38292379291.jpg)

Thanks
Eusebeus

**Comment by saupreusse** [comment]
should be fixed.
