### ISSUE TITLE
Bloodletters in High Pass not flagged as Bloodletters

### ISSUE THREAD

**Issue by Eusebeus82** [WarEmu/WarBugs#5498]
Hi

We stumbled upon these (Destro PQ i think) Bloodletters in High Pass and killed them. Sadly, they're not flagged as bloodlettters.
Location was c.12000.6000
![eusebeus_022](https://cloud.githubusercontent.com/assets/18599533/14789441/6a0bf606-0b04-11e6-9eb5-ec70b47357a0.jpg)
Thanks
Eusebeus

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
