### ISSUE TITLE
Aspects of Winds of Magic not flagged correctly

### ISSUE THREAD

**Issue by Eusebeus82** [WarEmu/WarBugs#5499]
At 31500,35500 in Blighted Isle there is a ritual circle with Banshee looking mobs representing the winds of magic. They're all flagged as Snotlings... can you correct this please.
![eusebeus_026](https://cloud.githubusercontent.com/assets/18599533/14789564/0e645a0e-0b05-11e6-83a7-83740b7770b8.jpg)
![eusebeus_027](https://cloud.githubusercontent.com/assets/18599533/14789569/12c4b350-0b05-11e6-93fe-1a769a779641.jpg)
Thanks
Eusebeus

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
