### ISSUE TITLE
"Holy Warriors" - unusual objective 

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#55]
"Holy Warriors" Quest has an unusual ID in the objective list.

I believe an .info is required on this? I will locate the person you have to speak to in the quest and tell you where. 

It's in Troll country, so when I fly there, I might disappear like a certain plane....

![holy warriors](https://cloud.githubusercontent.com/assets/7492543/2910103/e9c3029e-d63c-11e3-9c28-8d4f32c32dfa.png)

**Comment by Reggaewaldo** [comment]
Confirmed this as working as of today.

This can be closed.
