### ISSUE TITLE
[NPC Farming] Filthy Rat

### ISSUE THREAD

**Issue by lakeyours** [WarEmu/WarBugs#5500]
NPC: Filthy Rat (Level 1)
Faction: Order.
Location: Altdorf. (And somewhere else I assume)
Bug Reporter: Gentleman (Account Lakeyours)
Error: 
People around Altdorf is farming the Filthy Rats. The Filthy Rats drops dyes and which can be sold for gold to other players. This is very easy, TOO easy, and this causes a value unbalance in Gold and/or in dyes.
I think this is not the intent of the developers 
Solution: 
Change the drop from NPC Filthy Rat (Level 1) to not drop dyes or make it more rare for a dye-drop.

**Comment by sioding** [comment]
No Dye to drop anymore.
