### ISSUE TITLE
Bat, Giant (Neborhest Bat) - For Once It Isn't Guano

### ISSUE THREAD

**Issue by WARchosen** [WarEmu/WarBugs#5501]
Bat, Giant (Neborhest Bat) - For Once It Isn't Guano
"Echo Hunter"
MARSHES OF MADNESS @ 41, 48. Perform killing blow on this regular L19 mob just S of Dwarf Ch9.

killing bat dont give a unlock

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
