### ISSUE TITLE
Dark Elven public quest list

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5504]
Thought it might be helpful.
Elves:
Tier 1:
1. Spires of Narthain – 1st stage counter is broken. After killing 30 of Narthein Towerwatch – nothing happened, can't be completed.
2. The Watchtower – 1st stage cannot be complete, counter of kills is not working.
3. Mistwood Grove – 1st stage can't be complete, counter of killing Venomblade Spites is not working.
4. Nimosar - 1st stage cannot be complete, counter of killing Nimosar Guardians is not working.
5. Dreamshade Forest - 1st stage cannot be complete, counter of killing Dreamshade Ambusher is not working.
6. Golden Tor – PQ don't show counter, instead there is counter from Dreamshade Forest PQ.
7. Gon'Seraph - 1st stage cannot be completed, counter of killing Gon'Seraph Guards is not working.
8. Tor Achare - 1st stage can't be completed, counter of killing Hunter Guards is not working.
9. Lionhome Lodge - 1st stage cannot be completed, counter of killing Lion Hunters is not working.
10. Stone of valetear - 1st stage cannot be completed, counter of killing Shining Guard Knights is not working.
Tier 2:
11. Ruins of Anlec – on 2nd stage Ruined chest cannot be used, PQ cannot be completed. Also there only one chest but counter say 0 of 3, so there must be 3 different chests. 
~~12. Out of the Shadows – no problems.~~
~~13. Rock of Galirian – no problems.~~
14. Jagged Coast – Eagle claw (ballista) runing around (wrong type/subtype).
15. Ruins of Nagarythe – ~~on 1st stage you can click at 1 Ancient tablet to achieve all of them~~; on 3rd stage cant find Imlia Shadowprance of Vael Shadowprance, they just not inside PQ's scope, so PQ can't be finished.
~~16. The Gloomridge Copce – on 1st stage you can click at 1 Dirt Patch to achieve all of them; same on 2nd stage.~~
17. Dawn's Early Fight – Wreckage survivors should be saved, not killed.
18. Stone of Ecelsion – on 2nd stage Tether Stones can not be destroyed, so PQ can't be finished.
19. The Griffon Gate - Eagle claw (ballista) runing around (wrong type/subtype).
~~20. Town of Berhessa – no problems.~~
~~21. Reservation of Honor – no problems.~~
~~22. Monument of Narialle - no problems.~~
23. Reaver's end – at 3rd stage counter not achieve killing Lord Itharion Thunderblade and Chosen of Chorhandir, PQ can't be finished.
~~24. Tor Elyr - no problems.~~
25. Whitefire Tor – Arkaneth bolt thrower runing around (wrong type/subtype).
Tier 3:
~~26. Spirited Resistance -  on 2nd stage you can click at 1 Root to achieve all of them.~~
27. Quyl-Isha Temple – starts at 2nd stage without countdown timer.
28. Wavesinger – ~~on 2nd stage you can click at 1 Repeater Bolt Chest to achieve all of them;~~ Lothern Crest Blades disappear after completing 1st stage and don't come back in 3rd, making PQ unable to accomplish.
30. Dartian Forest - 1st stage can not be completed, counter of killing Avelorn Protectors, Spearfighters and Swiftblades is not working; Avelorn Swiftblades being killed by Uthorin Warriors and Fallen Fighters. 
31. Sea Guard Beachhead – 1st stage cannot be completed, counter of killing Veteran Seablades is not working.
32. The Pool of Elthrai - 1st stage cannot be completed, counter of killing Calmseekers, Halcyon Keepers and Halcyon Wards is not working.
33. Everspring – 1st stage cannot be completed, counter of killing Everguard Bowdancers is not working.
34. Watchtower of Aethwyn – 1st stage cannot be completed, counter of gathering Glass Shards is not working.
35. The jade Stand – 1st stage cannot be completed, counter of killing Jade Adamant and Stalwart Theurgist is not working.
~~36. Whitemoon Manor - 1st stage cannot be completed, counter of killing Whitemoon Scholar, Apprentice and Master is not working.~~
37. Recompense - starts at 3rd stage without countdown timer; can't be complete because there is no Arkaneth Deathcrafter in PQ scope.
38. Trial by Fire - 1st stage cannot be completed, counter of killing Impetuous Graduate and Scorchgaze Salamander is not working.
39. Ghyran's Embrace – can't be complete because there is no entrance to PQ zone, doors is closed.
40. The White tower of Hoeth – can't be complete because there is no Tyrinil Starwatcher to kill; Loremaster of Hoeth and Spellmine could be have wrong size. 
41. House of Cards – 1st stage can't be completed, counter of killing Arkaneth Havocbow is not working.
Tier 4:
~~42. The battle of Avethir – no problem~~
43. The vault of dragon princes – entrance into PQ area is blocked by magic barier, PQ can't be finished
44. Kelysian's landing - no objective counter at all, PQ can't be finished
45. Loryndaal - on 2nd stage one dragon orb can be clicked to achieve all 3, otherwise no problem
46. Malyros' rest - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
47. The fortress of Kaledor - in 1st stage counter don't counts kiling in objective, PQ can't be finished, also doors leading into PQ's area don't opens.
48. Dragonwatch falls - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
49. Keeper's vigil - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
50. Galiron's mouth - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
51. The Caladain steppe - in 1st stage counter don't counts kiling in objective, PQ can't be finished, also there is 1 mob to kill in counter.
52. The Caladain gate - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
~~53. Caladain's furnace – no problem~~
54. The phoenix eye – Shining Banner don't interactable, PQ can't be finished (also in same spot stay both shining banner and uthorin banner, I suppose after interaction with shining banner it must transform intto uthorin banner)
55. Woodsong manor - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
56. The senthoi pool - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
~~57. Blind Justice – no problem~~
58. The Spirit of Eataine - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
Dawnbreak manor - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
59. Last Stand - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
60. Follow the light - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
61. Glittering citadel - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
62. Ritual of light – located in Isle of the dead, portal to jump in there say: the portal's jump destination (215180136) does not exist
63. Ritual of metal - located in Isle of the dead, portal to jump in there say: the portal's jump destination (215180136) does not exist
64. Ritual of shadow - located in Isle of the dead, portal to jump in there say: the portal's jump destination (215180136) does not exist
65. Ritual of fire - located in Isle of the dead, portal to jump in there say: the portal's jump destination (215180136) does not exist

**Comment by Evildoor** [comment]
Edited, marked things already reported.

**Comment by Soulwhisper** [comment]
8/8/2016
- Nimosar PQ in The Blighted Isle is now working.

**Comment by Yellowpillow** [comment]
checked and added t4 PQ's in list
