### ISSUE TITLE
Crafting Skills unremovable

### ISSUE THREAD

**Issue by almondillo** [WarEmu/WarBugs#5505]
After clicking on the trades kill vendors in the second chapter of the empire starting area, I was automatically taught scavenging and apothecary. I then attempted to remove the trades kills and none of the apprentice trainers can be interacted with about trade skills and none of the teachers do anything, but repeat the same stuff they do every time. I am now stuck with 2 accidental trade skills and wasn't even given a pop-up to accept them in the first place.

**Comment by ellionkeman** [comment]
to remove skills type  .respec gathering and  .respec crafting

**Comment by Evildoor** [comment]
Closing per ellionkeman.
