### ISSUE TITLE
Guild Heraldry

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#5508]
At guild level 20, guild heraldry is unlocked. In my experience, it works fantastic on my own character model. However, other guild members running around with the appearance selected on their characters do not show up on my screen. Instead, they show up with whatever the appearance of their backpiece would be, prior to the guild heraldry being applied.

**Comment by Lileldys** [comment]
Unequipping and Re-equipping the item(cloak) seems to allow others to view your heraldry.

**Comment by Vancerus** [comment]
Unequipping and Re-epuipping does NOT solve the problem.

Each time you or the others run out of CLIPPING RANGE the cloak is set back to whatever is under the guild emblem.

![vancetra_003](https://cloud.githubusercontent.com/assets/14907399/15076619/e487dcfc-13aa-11e6-8f32-ff905e1b3337.jpg)

**Comment by MaxHayman** [comment]
Should be fixed in next patch

**Comment by sioding** [comment]
fixed with patch from 08.12.2018
