### ISSUE TITLE
Mitigation system

### ISSUE THREAD

**Issue by Parwun** [WarEmu/WarBugs#551]
Have tested how mitigation works atm.
Every possible damage reduction is calculated as mitigation.
Resist/armor (as it should)
WRONG -Toughness (should be calculated before mitigation)
WRONG - Guard (should be calculated before mitigation)

**Comment by MaxHayman** [comment]
@nalgol

**Comment by ozarmidrashim** [comment]
[Patch Notes for 1.3]

Damage mitigated by resistances and armor will still be shown in the combat log and not the tooltip. Additionally, the "mitigated" value displayed in the combat log will now also include damage reduction from the enemy's Toughness.

Toughness is working correctly. Guard is not.
