### ISSUE TITLE
Gathering Intelligence (order) Quest bugged?

### ISSUE THREAD

**Issue by Eusebeus82** [WarEmu/WarBugs#5513]
This quest requires you to kill a Raven Courier somewhere between Empire Ch11 and the High Pass Warcamp. I have searched and there is no such mob. I can't locate a corpse either with the same name to click. There are no map markers.
Can you fix this, or the map indicators?
Thanks
Eusebeus

**Comment by Razielhell** [comment]
Fixed in next.
