### ISSUE TITLE
[Guild] After the last patch my guild has 141 liders

### ISSUE THREAD

**Issue by notre4ror** [WarEmu/WarBugs#5514]
Like the topic says... and i can't demote liders.....

Edit:
Using another char( called 1) you can select any of the 141 chars to set lider, later the char ( called 1) demotes automatically to one range less. Any of the 140 liders can do this, all have full permisions on the guild.

**Comment by Luth-RoR** [comment]
Should be fixed now; if not please post the problems here: https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=15164&start=90#p170428

**Comment by Luth-RoR** [comment]
Preferably with a guild name.
