### ISSUE TITLE
[ToK] Dwarf,Slayer

### ISSUE THREAD

**Issue by Arvetaith** [WarEmu/WarBugs#5515]
It seems that currently the Bestiary unlock for killing 1000 slayers is currently only awarding a bestial token, despite the wiki saying that each class grants a title upon reaching 1000 kills. Im not sure if this is the case for any other class currently but I imagine that it likely is.

**Comment by seduch** [comment]
i think titles were granted on the killing of players (playing the class slayer) not mob.

**Comment by Evildoor** [comment]
So, what's the situation here? Killing 1000 mobs should award bestial token, killing 1000 players which play Slayer should award title. Is this not the case?

**Comment by Luth-RoR** [comment]
Afaik slayer mobs should also count for the title.
