### ISSUE TITLE
PQ (public quests) achievement counter's interface bug

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5516]
I pretty sure it isn't PQ itself bugged, instead I think it's 
Interface bug: If you step into PQ's scope once it's achievement counter can stuck to you and shows up when you into another PQ scope or just about everywhere.
For example I was into Macabre Fervor PQ, and after that counter from it pop up when I was in Ruinous Powers PQ.
Pillage and Plunder's PQ's counter follow me throu all Nordland and shows up in next PQs: The Wilds of War, Fields of  Foe, Sacred Ground, Salzenmund.
More on screenshots:
![1](https://cloud.githubusercontent.com/assets/18102127/14835790/ce896e9c-0c1c-11e6-8268-e69d10801d26.jpg)
![2](https://cloud.githubusercontent.com/assets/18102127/14835791/cea2e674-0c1c-11e6-92fd-dde4e9113ec9.jpg)
![3](https://cloud.githubusercontent.com/assets/18102127/14835792/ceb3d8e4-0c1c-11e6-92eb-45c964c5dd73.jpg)
![4](https://cloud.githubusercontent.com/assets/18102127/14835793/ceb3e0a0-0c1c-11e6-87f4-4a9bb0e44e6f.jpg)

**Comment by Soulwhisper** [comment]
I believe this has something to do with PQ IDareas.

**Comment by Yellowpillow** [comment]
Possible, but not very probable, you can't drug PQ's counter with you before you step in that PQ's scope.

**Comment by Soulwhisper** [comment]
PQ consistent...known and there is another ticket open too older then that.
Packet related! @Luth-RoR @Ryanfawkez  
**This can close.**

**Comment by Luth-RoR** [comment]
I only find 2 newer ones and an older one; they seem to be related to each other, but i don't think to this one here. https://github.com/WarEmu/WarBugs/issues/6883 https://github.com/WarEmu/WarBugs/issues/6935 https://github.com/WarEmu/WarBugs/issues/5517
Maybe i have overlooked it.

**Comment by Soulwhisper** [comment]
#6935 and #5517 is a different problem.
#6883 is the one we are looking for.
You need separate reports for which PQs it happens and which area it triggers or its a major packet issue?
To be honest at some PQ areas it doesnt happen at all.

**Comment by Luth-RoR** [comment]
>You need separate reports for which PQs and which area it triggers or its a major packet issue?

I don't know what's causing it, but atm no separate reports are needed. Maybe because of different area maps overlaping each other and need to be fine tuned (just guessing).
