### ISSUE TITLE
The achievement counter of PQ counts in the wrong line

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5517]
After 1 line of counter is fulled, another objective's line start put achievements in wrong lines, mostly in one above them.
For example: we have 2 lines, in first we have objective to kill 10 skeletons, in second 20 vampires. If we kill 10 skeletons and 10 vampires counter says: 10 of 10 skeletons and 10 of 20 vampires. Then, because skeletons line is complete, counter start putting vampires in skeleton's line, which is above him. It's like counter delete 1st line and put 2nd line in its place, but interface still shows 2 lines, and instead count vampires – it continue counts skeletons when vampires killed (15 of 10 skeletons, 10 of 20 vampires).
It operate like this in all working public quests.
![default](https://cloud.githubusercontent.com/assets/18102127/14836211/84243d70-0c1f-11e6-8a15-12741ff3cb82.png)

**Comment by wargrimnir** [comment]
This happens because the pqspawns are assigned to the stage that initiates it. Any time you have multiple objectives, it may count one line. I believe this can be fixed, but needs more experimentation.

**Comment by Razielhell** [comment]
#6935
