### ISSUE TITLE
Chaos public quest list

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5518]
All tested today and here what's wrong with...
Chaos
Tier 1:
~~1. Ruinous Powers – you can click at 1 gravestone to achieve all of them.~~
2. Destruction of the weak – on 2nd stage counter don't show how many “refugee duelist” was killed.
~~3. Holmsteinn Revisited – st.1 - you can click at 1 holmstein supplies box to achieve all 20.~~
4. Suderholm – ~~I can click at one kindling to achieve all.~~ On 3rd stage final boss Lord is same as Hero, I suppose hero should transform into lord, but that isn't happened and they both stand together. Because of it 3rd stage complete automatically – lord kill hero, PQ counts it and finish itself.
5. Macabre Fervor – Flagellants should be hostile by default, not neutral; counter broken – sometimes it stuck at showing 1st stage [random number] of 60, sometimes after finishing PQ counter say “PQ status: finished” even if PQ is reloaded, sometimes it not shows at all; on 2nd stage 2 Flagellants should attack person who attack Prophet of Doom; after finishing PQ not give loot bags; Accused in cage should have release option by interacting with cage – after being release he run forward to fight Flagellants.
6. Pillage and Plunder – 1st stage can't be completed, counter of killing Nordland Swordarm isn't working.
7. The Wilds of War - 1st stage can't be completed, counter of killing Wilderland Trackhound and Wilds Huntsman isn't working.
8. Fields of  Foe - 1st stage can't be completed, counter of killing Militia Guard is not working.
9. Sacred Ground – 1st stage can't be completed, counter of killing Wolf of Ulric is not working.
~~10. Salzenmund - 1st stage can not be completed, Supplies aren't interactable.~~
Tier 2:
11. Krul'Gor Herd – 1st stage can't be completed, counter of killing Krul Stomper isn't working.
12. Spirits of the Shadow - 1st stage can't be completed, counter of killing Shadow Spite and interacting with Kindling is not working.
13. Bells of War – 1st stage can't be completed, counter of killing Alerted Militia and Militia Sergeant is not working.
14. Silkens – PQ can't be complete because there is no objective counter in PQ's scope.
15. Reaper's Circle – 1st stage can't be completed, counter of killing Rankhide Wolf isn't working.
16. Wayshrine of Sigmar – 1st stage can't be completed, counter of killing Felde Refugee isn't working.
17. Ragash's Last Stand - PQ can't be complete because there is no objective counter in PQ's scope.
18. Bog Hunters – Mile Huntsmans kills Mile Hound, who should be friendly to them; 1st stage can't be completed, counter of killing Mile Huntsman isn't working; there is only one Obscure Meeting Stone in PQ's scope, but objective is to interact with 15 of them (0 of 15 it says).
19. Griffon Outpost – 1st stage can't be completed, counter of killing Order Handgunner isn't working.
20. Lursa's Blight – 1st stage can't be completed, counter of killing Rot Priest isn't working.
21. Plaguewood Thicket - 1st stage can't be completed, counter of killing Plaguewood Troll is not working.
22. Trovolek - 1st stage can't be completed, counter of killing Trovolek Defender and Trovolek Seer is not working.
23. The Blightstone Trolls - 1st stage can't be completed, counter of killing Blighted Boar is not working.
24. Tearing the Portal - 1st stage can't be completed, counter of killing Infected Warrior and Infected Champion is not working.
25. Plague Altar - 1st stage can't be completed, counter of killing Nurgling is not working.
Tier 3:
26. Mud Flats - PQ can't be complete because there is no objective counter in PQ's scope.
27. Steinbruck Manor - 1st stage can't be completed, counter of killing Steinbruck Watch and Steinbruck Farmhand is not working; Steinbruck Farmhand's counter says 1661 of 500.
28. Suderheim – upper Cemetery Gate isn't interactable.
29. Army of Faith - can't be completed because there is no enter into building where PQ's contained, doors is closed; Peasant's kills counts in counter correctly, but Peasants themselves are outside PQ's scope; on 2nd stage only 2 Temple Guards of 4 required pop up outside building, have to wait another 2 to spawn; on 3rd stage there is no Arch Lector Ansel outside the building to kill.
30. Serpent's Fang Bandits – NPC Hazelhof Wench run around and Bandits run after her to kill.
31. Knightly Riders – on 2nd stage objective is to do something with Food Stores, also there spawn champions who protect buckets with food, but I can't interact with buckets, so PQ can't be completed.
~~32. Village Vermin – no problems.~~
33. Kruegerhause – Kruegerhause Servant should transform into daemonette after being hit enough times; PQ can't be complete because there is no objective counter in PQ's scope.
~~34. Bitterspring – no problems.~~
35. Tempest Horn – 1st stage can't be completed, counter of killing Savage Bloodseeker isn't working.
~~36. Guts Out – no problems.~~
37. Keep of Asavar Kul - PQ can't be complete because there is no objective counter in PQ's scope.
38. Temple of Heimkel - PQ can't be complete because there is no objective counter in PQ's scope; also with counter NPCs "...Champion" disappeared frome PQ's scope after server reloading.
~~39. Beacon of Firengrom – no problems.~~
40. Tower of the Elves – on 2nd stage destroying Repeater Bolt Throwers isn't count in counter, so PQ can't be completed.
Tier 4:
41. The Storm is Coming - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
42. Lonely Tower – on 2nd stage Animated Death have no animation, otherwise no problem
43. Reaping Pain - in 1st stage counter don't counts kiling in objective, using wanton shard also don't counts, PQ can't be finished.
44. Sands of Time - no objective counter at all, PQ can't be finished
~~45. The Tower of Awakening – no problem~~
46. Fall of Grimclan - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
47. Gates of Praag - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
~~48. Tomb of Deathsword – no problem~~
49. Eastern Breach - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
~~50. Cinderash enclave – no problem~~
51. Southern Breach – in 1st stage counter don't counts kiling in objective, PQ can't be finished.
52. The end is nigh – one chaos beacon can be clicked to gain all 5 required to complete stage, otherwise no problem
53. The wings of the griffon – no objective counter at all, PQ can't be finished
54. Dark Retribution - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
55. Ambush at Garrisonburg - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
56. Rain of fire - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
57. Stoneclan's demise -  Rapidfire Turret after being hit enough times not die, became immortal (can't be hit, but run around and shoot at me), because of that 1st stage can't be completed. 
58. Vulgar display of power – in 1st stage one Pike can be used to gain all required to complete stage (Pikes should be used after each kill of empire soldiers and after using one pike there is a head should appear on it), on 2nd stage counter don't counts kiling in objective, PQ can't be finished.
59. Hunting the hunters - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
60. Fields of Reikland - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
61. Reiksguard training grounds - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
62. At the king's men - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
63. Chasing Shadows - no objective counter at all, PQ can't be finished
64. Sundered Fortress - no objective counter at all, PQ can't be finished, doors leading into PQ's area don't open. (I believe this PQ was two-sided, for order and destr)

**Comment by Vayra** [comment]
37. Keep Of Asavar Kul works for 1st stage, but the door does not open for 2nd stage so can't get to the required mobs (or verify that they spawn). The door to the building at the back (where the champ for epic quest spawns) should open when the force-field blocking it is removed after completing stage 1.

**Comment by Evildoor** [comment]
> 1. Ruinous Powers – you can click at 1 gravestone to achieve all of them.
> 3. Holmsteinn Revisited – st.1 - you can click at 1 holmstein supplies box to achieve all 20.
> ...

#424

**Comment by Yellowpillow** [comment]
Checked all t4 PQ's, update list

**Comment by Gnashspike** [comment]
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "Luth [Masked]" <FWD-737QTYSMENAIYCQANIQDDYCDEBMCIZLAI2VUBLAC2AAQABXEECLAARQQERYIAGNAGHFDSELMVA6QMLECEJIBAOKJUY7UE7UYCWFES5JHZ5QL4IJOH2CHFCBYZMTECYSFF5SA4NJHNZSOQABFEFASAI2QE4MCIWBBHAQFQJJYQJP4AD4ABOAAL3CPNA2WA2FBAAQAAIA=@opayq.com> is being returned by server outscan-backup.junkemailfilter.com on Sun, 11 Jun 2017 09:07:23 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  sadlyknotmyself@gmail.com
    host alt2.gmail-smtp-in.l.google.com [173.194.219.27]
    SMTP error from remote mail server after RCPT TO:<sadlyknotmyself@gmail.com>:
    452-4.2.2 The email account that you tried to reach is over quota. Please direct
    452-4.2.2 the recipient to
    452 4.2.2  https://support.google.com/mail/?p=OverQuotaTemp l19si1162098ywa.103 - gsmtp:
    retry timeout exceeded
