### ISSUE TITLE
[PQ] Empire Tier 1 - Pillager's Approach - Undiscoverable

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#5520]
The PQ Pillager's Approach is currently unrecoverable and nonoperational.

**Comment by Soulwhisper** [comment]
#4394 ?

**Comment by Soulwhisper** [comment]
Yes i can confirm that now idArea is missing...and no UI(counter) appears when entering PQ area.

**Comment by Soulwhisper** [comment]
I updated #4394
