### ISSUE TITLE
[ToK] Missing Entry - "Ironmane's Lock" - Permanent "New Entry"

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#5528]
Plaque for what ought to be Ironmane's Lock entry causes permanent blank new entry.
![dungchewa_001](https://cloud.githubusercontent.com/assets/18690551/14840010/d8401630-0bfd-11e6-869b-ee6d7c7fc594.jpg)
![dungchewa_002](https://cloud.githubusercontent.com/assets/18690551/14840012/db098fea-0bfd-11e6-9903-b9b1e4fbb056.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
