### ISSUE TITLE
[PQ] Greenskins Tier 1 - Ugrog's Rage- "Keep"

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#5530]
Ugrog's Rage - PQ

Stage One: Not granting influence. No counters. Listed as "Keep"
![dungchewa_003](https://cloud.githubusercontent.com/assets/18690551/14840066/7e2b2594-0bfe-11e6-9eef-624f7266ab21.jpg)

**Comment by Frubertlives** [comment]
It seems the Squigs are also granting influence for Chapter 2 and not Chapter 1.

**Comment by Mafti** [comment]
agreed, bit annoying when i wanted to make my tome look very nice :)

**Comment by wargrimnir** [comment]
Should be fixed.
