### ISSUE TITLE
Dark Magic not building while in Stoneclaw Keep in HP

### ISSUE THREAD

**Issue by imneo58** [WarEmu/WarBugs#5531]
Just as title says. While inside the confines of Stoneclaw keep I cannot build dark magic. I can exit the keep and build without issue it seems but not inside. Also while casting Ice spikes, which is primarily what is used to build DM, no dark magic and no dismount. I have tried logging and still no solution. Well after further testing,it's not limited to the keep afterall. I can't build outside the keep sporatically. I found a sweet spot on the left side of the outer wall between the next to the last and last merlons. Which I can build dark magic fine at that spot. Also after entering or exiting through keep doors I can build 10 dm

**Comment by Evildoor** [comment]
Issue is more general: #5537
