### ISSUE TITLE
[PQ] Greenskins Tier 1 - Sharpthorn Wud - "Keep"

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#5532]
No progress on PQ possible. The PQ stays unlisted and says it is a "Keep" upon entry to the area. All champions and bosses spawned. Likely related to #5530

![dungchewa_006](https://cloud.githubusercontent.com/assets/18690551/14841041/f17e8550-0c07-11e6-9daf-62c1d22b61b4.jpg)

**Comment by wargrimnir** [comment]
Should be fixed.
