### ISSUE TITLE
[ToK] Missing Entry - "Grokk" - Da War Maker Rally Master

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#5534]
Grokk does not grant a "Noteworthy Person" entry upon speaking to him as he should. 
![dungchewa_007](https://cloud.githubusercontent.com/assets/18690551/14841072/545b8efc-0c08-11e6-9fbb-a25fdce02451.jpg)

**Comment by Lheana** [comment]
Think it's fixable :)
