### ISSUE TITLE
[ToK] Missing Entry - "Wobna Slipsquig" - Kill Collector

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#5535]
Wobna Slipsquig does not grant "Noteworthy Person" entry as he should upon speaking with him.

![dungchewa_005](https://cloud.githubusercontent.com/assets/18690551/14841106/9bf2ecc4-0c08-11e6-85d8-5adac54752d8.jpg)

**Comment by Lheana** [comment]
Think it's fixable now :)
