### ISSUE TITLE
[ToK] Missing Entry - "Good Night Goblin" - Bestiary Unlock

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#5536]
Talking to Bloody Sun War Blasta does not grant Night Goblin "Good Night Goblin" bestiary unlock as it should.

![dungchewa_004](https://cloud.githubusercontent.com/assets/18690551/14841157/f547f486-0c08-11e6-9df2-02292ab00412.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by Ryanfawkez** [comment]
The unlock was already on Uzfang, as per http://warhammeronline.wikia.com/wiki/Good_Night_Goblin states.
