### ISSUE TITLE
lvl35 blue AP-Pots not useable

### ISSUE THREAD

**Issue by Vancerus** [WarEmu/WarBugs#5538]
Potent Invigoration Draught (Instantly restores 166 AP) is the blue crit of the normal lvl35 AP potion.

Unfortunately nothing happens when i want to use them, not even a error msg.

![vancero_172](https://cloud.githubusercontent.com/assets/14907399/14849181/dbedc0c4-0c71-11e6-8d44-ad6687bcffd5.jpg)

**Comment by Yellowpillow** [comment]
#2437
