### ISSUE TITLE
[ToK] Misplaced/Missing Entry - Simple Minds - Observation Point

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#5540]
Observation Point does not grant "Simple Minds" lore entry as it should.
![dungchewa_011](https://cloud.githubusercontent.com/assets/18690551/14856675/15171a04-0c67-11e6-9767-b6cf918be837.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
