### ISSUE TITLE
[ToK] Missing Entry/Misplaced Entry - "Bloody Sun Boyz" - Bloody Sun War Banner

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#5542]
Bloody Sun War Banner grants wrong entry. It grants "Simple Minds" when it should grant "Bloody Sun Boyz".
![footstompa_000](https://cloud.githubusercontent.com/assets/18690551/14857544/a5a90368-0c6a-11e6-98dd-f5ca0dce2882.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
