### ISSUE TITLE
[PQ] Greenskins Tier 1 - Ironclaw Camp - "Keep"

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#5543]
Ironclaw Camp - PQ

Stage One: Not granting influence. No counters. Listed as "Keep"
![dungchewa_013](https://cloud.githubusercontent.com/assets/18690551/14858284/73d24acc-0c6d-11e6-99c4-ce1e4606f1a1.jpg)

**Comment by wargrimnir** [comment]
Should be fixed.
