### ISSUE TITLE
[NPC] Tracking Hound - Not Butcherable 

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#5544]
Tracking Hound cannot be butchered. 

![dungchewa_015](https://cloud.githubusercontent.com/assets/18690551/14859389/f1767f9e-0c71-11e6-8517-150f826f5a0e.jpg)

**Comment by Evildoor** [comment]
Maybe hound mob type is broken altogether in this regard(#4389).

**Comment by Lheana** [comment]
Tracking Hounds can now be butchered.
