### ISSUE TITLE
Giant (Thrags) - Bare the Brunt

### ISSUE THREAD

**Issue by WARchosen** [WarEmu/WarBugs#5546]
Giant (Thrags) - Bare the Brunt
"The Earth Shaker"
(D) & (O)
MARSHES OF MADNESS @ 55, 60. Engage and battle and get hit by this L15 Hero (you don't have to defeat him to get the unlock). The unlock is just random from getting hit by the mob.
BONUS: Hidden quest for a golden nugget when traveling up the mt toward the coords. 

when he hit me he dont give a unlock and the item golden nugget for hidden quest when i click  nothing happens

**Comment by Evildoor** [comment]
#4001
Does killing him gives the title?

**Comment by Ryanfawkez** [comment]
Currently you can only get the unlock by killing.
