### ISSUE TITLE
Greenskin Public quest list

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5547]
Greenskins:
Tier 1:
1.Ugrog's Rage - no objective counter in PQ's scope, so you have to complete it blindfold; on 2nd stage you can click at 1 Beer Barrel to achieve all of them; not give you chapter's influence except for finishing PQ. 
2. Broketoof Camp - 1st stage can't be completed, Orc Flag isn't interactable, also there is 1 Orc flaf in PQ's scope (objective counter say you need 5).
3. Raider's Haven – 1st stage can't be completed, the counter of killing Red Raider Robber isn't working.
4. Kron Komar Gap - PQ can't be completed because there is no the objective counter in PQ's scope.
5. Sacred Grove - PQ can't be completed because there is no the objective counter in PQ's scope.
6. Ironclaw Camp - 1st stage can't be completed, the counter of killing Dog Waylayer isn't working.
~~7. Sharpthorn Wud - PQ can't be completed because there is no the objective counter in PQ's scope.~~ See comment below.
8. Sharpthorn Rock Mine - PQ can't be completed because there is no the objective counter in PQ's scope.
9. Goldfist's Hole Recovery - 1st stage can't be completed, the counter of killing Irontoe Thunderer isn't working.
Tier 2:
10. The Specter of Battle - 1st stage can't be completed, the counter of killing Spectral Screamer isn't working; Fallen Rock blocking the way to PQ's zone; introductory inscription says this is Keep, not PQ.
11. Marsh Conquest - PQ can't be completed because there is no objective counter in PQ's scope; introductory inscription says this is Keep, not PQ.
12. Battle at Blood Fen -  PQ can't be completed because there is no objective counter in PQ's scope.
13. Up the Creek Without a Battle - PQ can't be complete because there is no objective counter in PQ's scope; introductory inscription says this is Keep, not PQ.
14. Firebeard's Slayer – 1st stage can't be completed, the counter of killing Sea Anvil Slayer isn't working.
15. Danurgi's Rangers – 1st stage can't be completed, the counter of killing Hammerstriker Ranger isn't working.
16. Bar Dawazbak - PQ can't be completed because there is no objective counter in PQ's scope.
17. Burn Rock Tower - 1st stage can't be completed, the counter of killing Hammerstriker Rocklayer isn't working, interacting with Burn Rock Box not counts in the counter.
18. Gudrim's Veterans – 1st stage can't be completed, the counter of killing Gudrim Shieldwall isn't working.
19. Boarding the Seahammer - 1st stage can't be completed, the counter of killing Seahammer Portguard isn't working.
20. Fall of Firebrew – PQ can't be completed because there is no Barak Varr Brewer in PQ's scope to kill, killing other NPC with “Barak Varr” prefix not counts in the counter.
21. Grundadrakk's Wharf – 1st stage can't be completed, the counter of killing Barak Varr Sea-Axe isn't working.
22. When the Ship Hits the Sand – 1st stage can't be completed, the counter of killing Grundadrakk Ranger isn't working; there is only 11 Rangers in PQ's scope, whith is too few for completing anyways, objective to kill 125 of them.
23. Ironrock Point - 1st stage can't be completed, the counter of killing Grundadrakk Grudger isn't working.
24. Long Drong and the Slayer Cove - 1st stage can't be completed, the counter of killing Slayer Pirete isn't working.
Tier 3:
25. Thardrik Smashin' - PQ can't be completed because there is no objective counter in PQ's scope; introductory inscription says this it's Keep, not PQ.
26. Statue of Inspiration - PQ can't be completed because there is no objective counter in PQ's scope; door which lead to reward chest is closed.
27. Revoltin' Gobbos -  PQ can't be completed because there is no objective counter in PQ's scope.
Fireforge's Camp – 1st stage can't be completed, the counter of killing Oathbearer Stormguard isn't working.
28. Mutant Exiles – 1st stage can't be completed, the counter of killing Exiled Farsight isn't working.
29. Gassy Mines – marked on the map area not contain PQ – there is only naked mountains, on coordinates 37k – 60k I found 4 champion squigs who might be related to PQ, but PQ itself is missing; introductory inscription says this it's Keep, not PQ.
30. Kolaz Umgal – 1st stage can't be completed, the counter of killing Kolaz Umgal Ironguard isn't working; there is only 16 Ironguards in PQ's scope, whith is too few for completing objective to kill 125 of them. 
31. Moonfang Remnant - PQ can't be completed because there is no objective counter in PQ's scope; introductory inscription says this it's Keep, not PQ.
32. Grimbeard Station - PQ can't be completed because there is no objective counter in PQ's scope; introductory inscription says this it's Keep, not PQ.
33. Altstadt - PQ can't be completed because there is no objective counter in PQ's scope; introductory inscription says this it's Keep, not PQ.
34. Kolaz Umgal Scouts - 1st stage can't be completed, the counter of killing Kolaz Umgal Steelshot and Kolaz Umgal Stoneguard isn't working.
35. Blight-Favored Cult – 1st stage can't be completed, the counter of killing Blighted Cultist and Nurgling isn't working.
36. Blighted Herd - 1st stage can't be completed, the counter of killing Blighted Gor Shaman isn't working; there is only 11 Shamans in PQ's scope, whith is too few for completing objective to kill 150 of them. 
37. Sigmarite Temple - can't be completed because there is no enter into building where PQ's contained, doors is closed; there is no objective counter near PQ's marked area outside the building.
38. Priesterstadt - PQ can't be completed because there is no objective counter in PQ's scope; introductory inscription says this it's Keep, not PQ.
Tier 4:
~~39. Valley of the Rangers – no problem~~
40. Overtop outpost - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
41. Morkfang da mad - in 1st stage counter don't counts kiling in objective, PQ can't be finished, also doors leading into PQ's area don't opens, so PQ's area unreachable.
42. Ambush canyon – on 2nd stage one Gyrocopter can be used to achieve all of required, also killing  43. Oathbierer Bomber don't counts in achievement counter, so PQ can't be finished.
44. A wyvern in the hand – PQ is working fine. Wyverns sometime bugs and cannot be attacked.
45. Skargor da traitor – in 2nd stage Chrunga Da Midboss is missing into PQ's area, 2nd stage is bugged and freeze without timer, PQ can't be finished.
46. Und-a-runki - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
~~47. Riechert's raiders – no problem~~
~~48. Gutbasher gnoblars - no problem~~
49. Ruins of Mingol Kurdak – item Bucket of Scrap Metal is missing in 1st stage, interaction with another items in PQ's area or killing mobs don't counts, PQ can't be finished.
50. Burnbeard's oath - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
51. Kazad Urbar - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
52. Baradum - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
53. Duraz Dok - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
54. Clarion tower - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
55. Battlegut ogres - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
56. Slayer keep - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
57. Duraz deb - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
~~58. Beer barrel bash - no problem~~
59. Gutbash tribe stronghold - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
60. Da drakk cult - no objective counter at all, PQ can't be finished
61. Flamerock mine - in 1st stage counter don't counts kiling in objective, don't counts interaction with banner, PQ can't be finished.
62. Fallen keep of grom rodrin - in 1st stage counter don't counts kiling in objective, PQ can't be finished, also doors leading into PQ's area don't opens.
63. Lair of the blisterclaw - in 1st stage counter don't counts kiling in objective, PQ can't be finished.
May be related to: #5543 #5533 #5532 #5530 #424 #391

**Comment by Evildoor** [comment]
#6125, different problem now.

**Comment by Yellowpillow** [comment]
checked and updated T4 PQs

**Comment by Gnashspike** [comment]
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "Luth [Masked]" <FWD-737QTYSMENAIYCQANIQDDYCDEBMCIZLAI2UBTOYB2AAQGQBZIBTACDABPABJEU73FEVBKRAA4YBFA2XIIRJF5CZZGBJMSSBAJSFQV5JWIBDUCFGJEWITJSCTOMNAMVYHBVXBZTIWUAAXASDQAEEAD3ABJQAHYACMAF6BT3SYE5MCKWBCONCTH6SNNUQSEABAAAQA====@opayq.com> is being returned by server outscan-backup.junkemailfilter.com on Sun, 11 Jun 2017 09:03:37 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  sadlyknotmyself@gmail.com
    host alt2.gmail-smtp-in.l.google.com [173.194.219.27]
    SMTP error from remote mail server after RCPT TO:<sadlyknotmyself@gmail.com>:
    452-4.2.2 The email account that you tried to reach is over quota. Please direct
    452-4.2.2 the recipient to
    452 4.2.2  https://support.google.com/mail/?p=OverQuotaTemp q72si1588232ywg.93 - gsmtp:
    retry timeout exceeded
