### ISSUE TITLE
Multiple Quests

### ISSUE THREAD

**Issue by SpartanMarine88** [WarEmu/WarBugs#555]
Any quests where you need to talk to NPC's of a certain variety, (Farmers of Hearts and Minds, Suspicious Patrons at the Grey Lady, Wounded Soldiers at the windmill to name a few.) Can all be repeatedly talked to to complete the quests.

**Comment by Evildoor** [comment]
General problem which was already reported. Here, for example: https://github.com/WarEmu/WarBugs/issues/424
