### ISSUE TITLE
[ToK] Unlock for the title "The Trollwise" not working on Destruction side.

### ISSUE THREAD

**Issue by seduch** [WarEmu/WarBugs#5551]
When you speak to Afvaldr in Troll Country, located at 61516, 29360 nothing happen.
Should give unlock for the title "The Trollwise" .

Don't know if working properly on Order side.

**Comment by cimator** [comment]
I have the title Trollwise on my squig herder so it works for destro too, maybe you spoke to wrong npc.

**Comment by cimator** [comment]
Try talking to Walbrect Veit at 26k 41k, Troll country when server is online again

**Comment by seduch** [comment]
Thank, will check it. But if i refer to the thread on the forum about unlocks it's the NPC for the order unlock (Oh My Tzeentch even the NPC are xrealming !)  
cf:
(D) TROLL COUNTRY @ 61.5, 29. Talk to Afvaldr.
(O) TROLL COUNTRY @ 26, 41. Talk to Walbrecht Veit. Out of sight, behind the rocks just to the right of the entrance to the top camp at Griffon Outpost PQ.

**Comment by poutpoutt** [comment]
Killing Walbrecht Veit works to unlock for Destruction (even if normally, it should work with talking to Afvaldr).

**Comment by Lheana** [comment]
Now talking to "Afvaldr" as Destruction will trigger the unlock and the title.
