### ISSUE TITLE
Reikland Factory's wrong spawn points

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5552]
Destruction players are unable to use exit from scenario, because spawn point is too far and below the bridge. 
Because of wrong spawn points guardians of both sides stay too far away from original spawn points. That broke many strategic ways of that scenario and ruin many opportunities for premade groups.
Please fix the best scenario in the game. (removing one flag was great idea, but guards really ruins about 1/3 of scenario)
![10](https://cloud.githubusercontent.com/assets/18102127/14885320/d90ffdf0-0d5b-11e6-88ce-12d11d4e4e0c.jpg)
![11](https://cloud.githubusercontent.com/assets/18102127/14885321/d9109a3a-0d5b-11e6-9909-bd7a8eeb2cef.jpg)

**Comment by ozarmidrashim** [comment]
Not a bug, so doesn't belong on the bugtracker.

Also, no "Please Fix".
