### ISSUE TITLE
Marauder Impale 

### ISSUE THREAD

**Issue by Nicoltepps** [WarEmu/WarBugs#5553]
I noticed that the Marauder's "Impale" ability animation is not correct. Normally, he will thrust with his sword arm, but currently he flails about. I love the original animation for impale, and would very much like to see it return. :D

**Comment by Evildoor** [comment]
Do you have a weapon equipped in off hand?

**Comment by Nicoltepps** [comment]
Im not sure. I'm assuming he does, but suppose i do and suppose i don't. Which would be the problem?

**Comment by Evildoor** [comment]
Having no offhand weapon changes Marauder's animations, even while mutated. Impale is flailing with mainhand weapon if you have no offhand.

**Comment by Nicoltepps** [comment]
That's very helpful. Now that you mention it, I remember that being a problem for me in live. Thank you very much for your help!

**Comment by Evildoor** [comment]
Closing as not a bug then.
