### ISSUE TITLE
Career tactics not training, or even available to buy

### ISSUE THREAD

**Issue by Geawiel** [WarEmu/WarBugs#5556]
(Edit: forgot char names: BO - Geawiel, Mara - Mikli)
I've tried this on both characters that are able to train the first level tactic now.  It applies to both.  The first is a lvl 19 Black Orc (the screenshots are of this character.)  The other is a lvl 15 Marauder.

The issue: both have trained the first career tactics slot in their respective training tree.  When I go to the career trainer to purchase the ability, their respective tactic does not show to purchase or even is listed.  It is not in either character's abilities>tactics tab either.  The only ability that shows to purchase for the BO isn't even anything I have trained, nor does it even allow me to purchase it.  The trainer just stands there and looks at me.

![geawiel_001](https://cloud.githubusercontent.com/assets/18731274/14907733/a1d3a62c-0d81-11e6-805d-0c82902310d8.jpg)

![geawiel_002](https://cloud.githubusercontent.com/assets/18731274/14907734/a1daf9a4-0d81-11e6-9e1a-cddaaac6b209.jpg)

**Comment by Evildoor** [comment]
You have to spend additional mastery point to get the tactic/ability itself.
