### ISSUE TITLE
Bolstering is not working

### ISSUE THREAD

**Issue by ClintEastwod** [WarEmu/WarBugs#5557]
Only wounds are increasing properly, skills are not bolstering too.

![image](https://cloud.githubusercontent.com/assets/18602535/14909930/8f456656-0df1-11e6-8f12-08b1526a9a1b.png)

**Comment by Evildoor** [comment]
What? Stats are different, skill damage is different. That's the purpose of the bolster - to give you a reasonable amount of wounds and slightly boost other parameters, not to bring you to the level of loaded lvl 15 (or whatever top level in a tier it is) characters.

**Comment by ClintEastwod** [comment]
Yes, but I remeber that you got mush more stats from bolstering. And damage from skills was bolstered in 2 times at least. Though, may be I am wrong.

**Comment by Evildoor** [comment]
if the bolster worked differently - proof. I've not created a new characters recently, but lvl 16-17 in t2 feels and plays just fine.

**Comment by ClintEastwod** [comment]
I made new toon, lvl 2 now. What I got from bolstering, plz have lool at skill damage. Its damaging lvl 19, enstead of lvl 3 damaging on screen above.
![image](https://cloud.githubusercontent.com/assets/18602535/14911894/2102b832-0e01-11e6-861c-0a02062083b6.png)

**Comment by Evildoor** [comment]
Client tooltips don't mean much. As you can see, damage in combat log is proper (higher than lvl2 one stated by client tooltip).
![kobs_000](https://cloud.githubusercontent.com/assets/11015074/14914116/2164f146-0e10-11e6-8b35-fca016b5ce69.jpg)

**Comment by ClintEastwod** [comment]
ok, ty Evildoor
