### ISSUE TITLE
Noteworthy Persons in Dwarf T1/Mount Bloodhorn

### ISSUE THREAD

**Issue by angrelion** [WarEmu/WarBugs#5558]
1. Dodrum Ironsplitter
   and 
2. Odarik Rorkisson
   
   both do not give you the entry.
   ![noteworthy_drawfs_t1](https://cloud.githubusercontent.com/assets/18734102/14911754/c6609902-0df7-11e6-8e41-6247831ba8b4.png)

**Comment by Lheana** [comment]
Odarik Rorkisson (Rally Master) and Dodrum Ironsplitter (Kill Collector) of Dwarf chap 3 (7.5k 25k) still don't provide their respective Noteworthy Persons unlocks when talking to them.
