### ISSUE TITLE
Some more marauder bugs

### ISSUE THREAD

**Issue by Starwhisper** [WarEmu/WarBugs#556]
Hello I noticed some bugs on the marauder, they seem to be here since the Str/hp stacking bug has been fixed.

1. Stance handling
 It has already been reported that you can loose your mutation upon changing zone.  I'd like to add that the cooldown of the mutations is wrong. I can't tell which is the correct way to handle them but I'm sure each mutation SHOULD NOT trigger a cooldown on every other mutation. Even gift release triggers cooldowns.

2. Game loading crash
 Every day, upon the first logging on my marauder, the game will crash and close during the loading. I need to load my marauder twice each day regardless of the zone he is in. 

3. Inventory flood
 There is a bug which will fill a marauders inventory with gift weapons when he is not logged into the game. Here is a screenshot:

<a href="http://www.hostingpics.net/viewer.php?id=172745Tamert001.jpg"><img src="http://img4.hostingpics.net/thumbs/mini_172745Tamert001.jpg" alt="Heberger image" /></a>

This bug will also occur everyday. It will fill my bags with gift weapons (gift of savagery, gift of monstrosity,etc.) as you can see in this screenshot in bags 3, 4 and 5. We cannot sell them and we cannot mass trash them so I have to delete them one by one every day. 

 Maybe this bug is related to the database problem that happened some days ago?

**Comment by ozarmidrashim** [comment]
[Stance handling]
https://www.youtube.com/watch?v=dJdAArOBkiA&feature=player_detailpage#t=105 shows cooldown triggered on all mutations. Mutations are off the GCD, so if a unified cooldown were not applied to all of them, switching between mutations without delay would be possible. Please research before reporting.

2 and 3 are related to each other. Every time the server crashes, the inventory of a Marauder is flooded with copies of his mutation gifts, and this circumstance causes the Marauder's client to crash the first time the character is logged in post-server restart or server crash.
