### ISSUE TITLE
Book of Binding to Kron Komar 

### ISSUE THREAD

**Issue by angrelion** [WarEmu/WarBugs#5560]
If using the **Book of Binding** to **Kron Komar** in **Mount Bloodhorn**, you will end stuck out of the world. 
_Only "Fix" so far: Double /Stuck command._

**Comment by NorKalli** [comment]
Book simply does not work to Komar anymore

**Comment by NorKalli** [comment]
self note: learn to set rally point

**Comment by NorKalli** [comment]
fixed

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
