### ISSUE TITLE
Keeps don't contain teleportation flags

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5561]
On live all keeps contained flags, usually located in one of the casemates (towers) on 3rd floor. Those flags allowed players to teleport into warcamp unless inner doors of keep was attacked (i believe, because after inner doors is attacked you respawn in WC anyways).
This may be useful when you was killed in RvR zone, and you don't want to be in Keep, you go from keep to WC and you getting killed over and over again, because you respawn in keep all the time.
![arena_0491](https://cloud.githubusercontent.com/assets/18102127/14915081/e8076da0-0e20-11e6-8ba7-64d397dddcaa.jpg)

**Comment by genisaurus** [comment]
They were intentionally left out, and adding them back in would be a feature request.
