### ISSUE TITLE
Lissariel's Glade PQ (T2 Ch7 Order)

### ISSUE THREAD

**Issue by Eusebeus82** [WarEmu/WarBugs#5566]
This PQ has some tracking issues - you can interact with the logs to complete the 1st stage, kill the spites for stage 2, and kill the dryads for stage 3. The hero mob "Deeproot" spawns while the PQ is requesting to kill the Dryads. When the 12 dryads die, the PQ updates to "Kill Deeproot", and promptly de-spawns him...

**Comment by Razielhell** [comment]
Fixed. @Luth-RoR
