### ISSUE TITLE
Vulture mobs in Mount Bloodhorn

### ISSUE THREAD

**Issue by Eusebeus82** [WarEmu/WarBugs#5569]
There are a large number of vultures outside the Order Flightmaster in Mount Bloodhorn. These are not flagged as Vultures for the TOK.

**Comment by Ryanfawkez** [comment]
Names please.

**Comment by Eusebeus82** [comment]
They are all called Ravenous Vulture.
![eusebeus_052](https://cloud.githubusercontent.com/assets/18599533/15093818/7c0838b2-148a-11e6-9627-3b03222c4377.jpg)
