### ISSUE TITLE
[ToK] Missing Entry - "De-spite" - Maegda

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#5573]
Kill Maegda the Spite does not grant "De-spite" ToK entry as it should. 
![dungchewa_023](https://cloud.githubusercontent.com/assets/18690551/14925770/0bad4324-0e17-11e6-9fa1-4bd9af9da6c7.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
