### ISSUE TITLE
[PQ] Greenskins Tier 1 - Sacred Grove - "Keep"

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#5575]
Sacred Grove - PQ

Stage One: Not granting influence. No counters. Listed as "Keep"

![dungchewa_022](https://cloud.githubusercontent.com/assets/18690551/14925838/6cd7aaae-0e17-11e6-8f32-42a26294aabb.jpg)

**Comment by Evildoor** [comment]
#5547
