### ISSUE TITLE
Blighted Isle: tainted crystal not granting Tome entries for "The Gateway To Ultimate Knowledge"

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#5581]
The tainted crystal located in front of Gorthlak Lair does not grant any tome entries (The Gateway To Ultimate Knowledge). Coord 36k 17k

**Comment by Milord9** [comment]
![lothern_028](https://cloud.githubusercontent.com/assets/17692456/14936459/8d285a34-0eed-11e6-8ff6-19909d3a742c.jpg)

![lothern_029](https://cloud.githubusercontent.com/assets/17692456/14936461/96dd3fae-0eed-11e6-97a6-896c3daf6f18.jpg)

**Comment by saupreusse** [comment]
fixed :)
