### ISSUE TITLE
Armoured Mounts Name/Appearance

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#5583]
I saw on the forums that the armoured mounts are being fixed next patch.
I was having a look at them in the IC and it looks like some of the mounts have incorrect labels to model.

For example: the "Red Battle Wolf" is black and the "Black Battle Wolf" is red.

Unfortunately my game doesn't let me take screenshots, or else I'd attach some.

Unsure if other mounts have similar situations, but could be worth checking out before they are introduced so the whole "My Black Horse is grey" QQ doesn't happen again, haha.

**Comment by Torquemadra** [comment]
Whats your baseline? The colours are named according to the pelt of the wolf and the ones standing around the heavy mount vendor are 75% run speed mounts not implemented.

**Comment by Abolition** [comment]
![abolition_002](https://cloud.githubusercontent.com/assets/15091486/15169317/085940fe-1779-11e6-888e-3b41ca9e40a8.jpg)

Red Battle Wolf seems to be brown.
Black Timber Battle Wolf isn't black, but I suppose a dark brown is probably "close enough" in Mythic's eyes, so that one is probably not such a problem.

I thought perhaps the Red wolf was supposed to be the one labelled "Black Timber" (due to the red harnesses etc), and that the one labelled "Red" was supposed to be the Black Timber , due to the lack harnesses etc.

I wasn't aware that these models were the "not implemented" models, so it's probably not worth a fix. I just thought it was strange that a "Red" wolf was brown.

**Comment by NorKalli** [comment]
Can we close this?
