### ISSUE TITLE
Temptress quest

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#5584]
The Wayshrine in Sigmarite camp is unclickable. There is another one next to the river near Chaos Chapter 7 but map indicator doesn't show it.

**Comment by Evildoor** [comment]
#4450, but the author closed it for some reason...

**Comment by Ryanfawkez** [comment]
"Quest marker was indicating not the right shrine, actually." - by which I assume we'd simply have to move the quest marker to the correct, working gameobject.

**Comment by StaH84** [comment]
I guess it's better to move the object rather then quest marker because the wrong object is in the right place pointed by the marker:-)

**Comment by Luth-RoR** [comment]
Using this report: https://github.com/WarEmu/WarBugs/issues/8255
