### ISSUE TITLE
[Gear] Belt - Festenplatz Pillager Bellybuckle - Invisible

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#5585]
The belt "Festenplatz Pillager Bellybuckle" is invisible for the Choppa.
![dungchewa_024](https://cloud.githubusercontent.com/assets/18690551/14936458/405b436a-0ebb-11e6-890e-cfebed987ad7.jpg)

**Comment by wargrimnir** [comment]
Appears correct
