### ISSUE TITLE
public quest "stone of Aqshy" bugged (Saphery)

### ISSUE THREAD

**Issue by Milord9** [WarEmu/WarBugs#5587]
We are supposed to -I guess- interact with the eight pillars here ("0/8 stone of Aqshy") but cliking on them do nothing.

![lothern_011](https://cloud.githubusercontent.com/assets/17692456/14936598/2548a230-0ef1-11e6-936a-9ad8a46530b9.jpg)

![lothern_012](https://cloud.githubusercontent.com/assets/17692456/14936599/2bfe3b3a-0ef1-11e6-9271-dba110c98f12.jpg)

**Comment by grunbag** [comment]
Fixed
