### ISSUE TITLE
visual bug on a 3 NPC quest

### ISSUE THREAD

**Issue by Milord9** [WarEmu/WarBugs#5588]
In Saphery we meet 3 mushrooms charged goblins who give us the same quest (to collect a mushroom). After completing the quest, the yellow icon disappear from the NPC we have talked to, but not the two others.

![lothern_013](https://cloud.githubusercontent.com/assets/17692456/14936627/c8bd951a-0ef1-11e6-93dc-0c300538d5c9.jpg)

![lothern_014](https://cloud.githubusercontent.com/assets/17692456/14936628/cf972004-0ef1-11e6-9933-66c3d28c1a29.jpg)

**Comment by NorKalli** [comment]
long ago fixed
