### ISSUE TITLE
Invalid NPC - Talabecland

### ISSUE THREAD

**Issue by aevalone** [WarEmu/WarBugs#5589]
Quest NPC in Talabecland shows Invalid NPC in quest text.  Screenshots attached.

Screenshot 'invalid npc2' shows coordinates.  Screenshot 'invalid npc1' shows quest text.

![invalid npc 2](https://cloud.githubusercontent.com/assets/18753053/14936982/f586b808-0ec7-11e6-893f-b3b6917e378e.png)
![invalid ncp 1](https://cloud.githubusercontent.com/assets/18753053/14936984/fa3fac1a-0ec7-11e6-908f-52eaee430faf.png)

**Comment by Evildoor** [comment]
#2802
