### ISSUE TITLE
Mara change apperance when change mutation

### ISSUE THREAD

**Issue by dajciekrwi** [WarEmu/WarBugs#559]
Hi , 
Dear Devs,
After change one mutation for  other  (no matter Brut, Savage or Monstro),  a Marauder change his apperance, what  piss me really off!
Is anything what i can do with this bug?
Good luck, and thx for hard work

**Comment by ozarmidrashim** [comment]
This issue occurs if a Marauder changes zones with an active Mutation (appearance). The mutation appearance is lost upon zoning, and the next mutation cast will result in the Marauder's entire appearance changing.

If the client uses the Gift of Release before zoning, the mutation bug will not occur. However, using the Gift of Release will not change the Marauder's stance, only his appearance.

**Comment by Evildoor** [comment]
IIRC, this was fixed.
