### ISSUE TITLE
Vomitous Waraxe may have wrong stats.

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#5590]
The Vomitous Warhaxe (dwarf 2h loot from Stinkfang the Vomitous, Ellyrion lair boss) has +20 hate caused.

I am not sure if this is a bug.
![screen shot 2016-04-30 at 21 46 51](https://cloud.githubusercontent.com/assets/18053736/14938489/1706d8fa-0f1d-11e6-96ca-a2a9ce4189d5.png)

**Comment by genisaurus** [comment]
Not a bug, these are the correct stats.
