### ISSUE TITLE
[Quest] A Bitter Salve

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#5591]
There are 2 issues with the quest at this point in time. First the quest area on the region map is wrong. I have attached a file showing where the quest marker should be (roughly around the wagon defense pq). Second, while selectable, clicking the blessed salve near the wagons does not complete the quest, and does not create a loot box.
![smaragdus_007a](https://cloud.githubusercontent.com/assets/13975292/14938792/a90617a2-0ef5-11e6-9978-6e5859689bc8.jpg)

**Comment by NorKalli** [comment]
i fixed it, hooray.

**Comment by sioding** [comment]
fixed with patch from 05.05.2018
