### ISSUE TITLE
[Quest] Special Mix

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#5592]
Upon finding the quest giver Alchemist Brond in Talabecland, I get the following message in the quest text: 
![smaragdus_006](https://cloud.githubusercontent.com/assets/13975292/14938813/4ccf5e48-0ef6-11e6-9aac-b00bbdd853bf.jpg)

I am aware that Mt Gunbad is not working at this point in time.

**Comment by Evildoor** [comment]
#2802
