### ISSUE TITLE
Pocket Item - Revolting Crock

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#5595]
The unlock for this item works fine, however when used, the item does not do the "poo shower".

Trivial, I know, but I want to poo on people.

**Comment by jigsawed** [comment]
Need this back in the game! It's not the same without it.

**Comment by dryack** [comment]
+1

My favorite item of any category in the game.

**Comment by jigsawed** [comment]
Woah! Can we not close the issue? This is really important to me.  We want this item back!  If oh close the issue its like saying we will never get it back!

**Comment by Luth-RoR** [comment]
>Luth-RoR modified the milestone: **Server | Issues can not be fixed yet** 13 minutes ago

The report was closed, because it can't be fixed atm; it will be reopened once it can be fixed. It was not closed because it will never be fixed.

**Comment by jigsawed** [comment]
Can you provide more details on the mechanism that is preventing it's fix (maybe an alternative bug report that this functionality relies upon), and perhaps next steps for when that mechanism is working properly to get this item fixed?

**Comment by Luth-RoR** [comment]
I'm no dev, but there are many, many more important issues at the moment and this probably needs the attention of a coder; their time is rare and filled with coding improvements for the server that affect anyone.
