### ISSUE TITLE
Avevlorn: Public quest "Rotten embrace", order: quest stuck on stage 1

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#5597]
Killing nurselings does not grant any influence nor advances the stage.

![screen shot 2016-05-01 at 09 22 30](https://cloud.githubusercontent.com/assets/18053736/14940851/5a0fabde-0f7e-11e6-8308-f566fc7e0fc7.png)

**Comment by Razielhell** [comment]
@Luth-RoR Fixed.
