### ISSUE TITLE
Avevlorn: Public quest "Ritual of Corruption", order: quest stuck on stage 1

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#5599]
Killing npc's does not grant any influence nor advances the stage.

![screen shot 2016-05-01 at 09 30 05](https://cloud.githubusercontent.com/assets/18053736/14940876/8f8c9596-0f7f-11e6-9d33-351672378730.png)

coord 29k 18k

**Comment by Razielhell** [comment]
@Luth-RoR Fixed.

**Comment by Luth-RoR** [comment]
From https://github.com/WarEmu/WarBugs/issues/9764:
>The Ritual of Corruption PQ counts every single kill for each category, e.i. you kill a sentinel and it counts for the sentinel, acolyte, and witch (See Ritual of Corruption). Furthermore, it has to be disclosed that I did not finish the Ritual of Corruption as I ran out of time and had to go.

https://cloud.githubusercontent.com/assets/29195802/26778622/58968f26-49e2-11e7-95f3-8198fd485c4a.jpg

**Comment by Luth-RoR** [comment]
DB dev tested it and it's working.
