### ISSUE TITLE
[Quest] "Saving New Emskrank" displays incorrect Objectives 

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#56]
This quest is missing 2 of the objectives and has 1 of the objective (Find Giant sea mine) which is not part of the quest.

Correct objectives:

Douse the Kindling (1)
Save the Mead (1)
Save the Spices (1)

During the latter builds of WAR. This quest was removed from the game. Either we could fix it or just better yet, remove it entirely? I'm sure it won't be missed as it was a quest that required you to enter the RvR lake.

![saving new emskrank](https://cloud.githubusercontent.com/assets/7492543/2914652/74be12ce-d69e-11e3-9b77-670ed42b8191.png)

**Comment by SeriousSham** [comment]
Interestingly enough, the Kindling objective can be completed in Norsca, 29127 / 48759.

**Comment by genisaurus** [comment]
Quest starter and finisher removed.
