### ISSUE TITLE
[Shadow Warrior] Basic Mechanics

### ISSUE THREAD

**Issue by Siegureboy** [WarEmu/WarBugs#560]
Please let me know if this is being discussed elsewhere/if this is a known issue. I have tried multiple times to cast an ability like Eagle Eye, and then before the "arrow" hits the target - click the ability VoN. Nevertheless, I fail at what I want to do. I find that the damage from my direct damage abilities are calculated before flight time, or there is no such thing as flight time. Steady Aim is commonly used after an ability has been cast, but before the arrow hits the target (in air).

**Comment by Thorgatin** [comment]
Projectile traveling time isn't implemented yet.
