### ISSUE TITLE
High Pass: Public quest "Cult of the Magus", order: 2nd stage spawns the wrong kind of npc, quest fails

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#5600]
![screen shot 2016-05-01 at 10 04 06](https://cloud.githubusercontent.com/assets/18053736/14940991/86318286-0f84-11e6-8491-b2ae25ffc507.png)

At the second stage, the quest requires:
![screen shot 2016-05-01 at 10 05 40](https://cloud.githubusercontent.com/assets/18053736/14940984/542ac680-0f84-11e6-9c4e-4c5f98e32f39.png)
Magi Orators are spawned and the quest cannot be completed.

![screen shot 2016-05-01 at 10 05 46](https://cloud.githubusercontent.com/assets/18053736/14940987/672ce826-0f84-11e6-8ece-eb24c0ef743b.png)

In general, Npc's do not grant any influence

**Comment by MerryGitmas** [comment]
The requested npc's are a bit north of the PQ area, the quest is not bugged.

**Comment by Evildoor** [comment]
So, this can be closed?

**Comment by MerryGitmas** [comment]
Yes please

**Comment by Evildoor** [comment]
FYI - you can close your own tickets.
