### ISSUE TITLE
Giant High Elf

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#5601]
Loremaster of Hoeth at approximately (15k, 47k) within the PQ area sometimes spawns as a GIANT character model.
Nothing gamebreaking, it just looks hilarious.

![aborifts_002](https://cloud.githubusercontent.com/assets/15091486/14941018/cf2c6274-0fcc-11e6-9333-2a327b99552f.jpg)
![aborifts_003](https://cloud.githubusercontent.com/assets/15091486/14941020/d33f4cb4-0fcc-11e6-9f27-fdb438ec208e.jpg)
![aborifts_004](https://cloud.githubusercontent.com/assets/15091486/14941021/d5eb4b52-0fcc-11e6-8af3-2e6989b0ff4e.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
