### ISSUE TITLE
[Black Orc] Fangbreaker's Bigchoppa having incorrect animations

### ISSUE THREAD

**Issue by Krumlok** [WarEmu/WarBugs#5602]
![sin titulo](https://cloud.githubusercontent.com/assets/14275335/14942007/6458dd86-0fb0-11e6-96e4-9989ed7b2d60.png)

![sin titulo](https://cloud.githubusercontent.com/assets/14275335/14942011/7e258278-0fb0-11e6-942f-0521ea891bfc.png)

As you can see, the animation is like a 1hand axe. Even though it prevents a blocka from being equipped, a 2h with the animations of a 1h doesn't look really well :(

**Comment by Evildoor** [comment]
#1035 is supposed to be fixed.

**Comment by Ryanfawkez** [comment]
@Evildoor - There are two Fangbreaker Bigchoppas in the database. The one that isn't obtainable has been fixed, whereas the obtainable one seen here continues to suffer from a bugged look.

**Comment by Ryanfawkez** [comment]
Fixed in next patch. Also renamed the Bigchoppa for Black Orcs to Bigloppa for the sake of the Database.

**Comment by Krumlok** [comment]
Glad to hear you fixed it! Thanks!
