### ISSUE TITLE
High Pass: empire chapter 11, Influence reward may have wrong stats

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#5604]
The elite reward chest piece (Trisanctifier's Klad) has only +3 wounds (+23 strength). The alternative reward has comparatively better stats.
The woulds should probably be +13 or more.

![screen shot 2016-05-01 at 13 47 45](https://cloud.githubusercontent.com/assets/18053736/14942029/d51108e4-0fa8-11e6-8f18-4eb4278cf3fc.png)
![screen shot 2016-05-01 at 13 47 30](https://cloud.githubusercontent.com/assets/18053736/14942030/d75b280a-0fa8-11e6-94c1-821f417bd64e.png)
![screen shot 2016-05-01 at 13 47 18](https://cloud.githubusercontent.com/assets/18053736/14942031/d901fd8c-0fa8-11e6-8fba-731d6bafef02.png)

**Comment by Ryanfawkez** [comment]
http://war.mmodb.com/items/trisanctifiers-klad-56043.php - Lacking +19 weaponskill. Fixed in next patch.

**Comment by Soulwhisper** [comment]
@Ryanfawkez And +4 Initiative on Ironmantle http://war.mmodb.com/items/trisanctifiers-ironmantle-56055.php
