### ISSUE TITLE
Level 13 mobs not dropping any rare/very rare loot.

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#5606]
Today i have killed 517 Batsmen (levels 12-14) in Ostland, 35 Ghouls (lvl 13) in Troll's Country and 281 Empire npc's (lvl 13). None of them dropped any Rare/Very rare loot apart from 1 Blue dye and 1 Purple dye.
This bug may be connected to the fact that lvl 13 mobs used to drop lvl 9 Very rare gear (Tempest-rider) and now not even that.
The correct loot should be Harrier (blue quality) and Reaver (purple quality).

This may be a bug.

**Comment by Evildoor** [comment]
IIRC, blue and purple drops were removed from monsters to encourage PVP over grinding.

**Comment by MerryGitmas** [comment]
Related to this issue
https://github.com/WarEmu/WarBugs/issues/5198

**Comment by Evildoor** [comment]
No objections to my comment, closing.
