### ISSUE TITLE
Everyone is Guild leader bug

### ISSUE THREAD

**Issue by Partizan-Rusi** [WarEmu/WarBugs#5607]
Everyone is Guild leader bug

My account was temp. banned for few days and something happened. Now when I login in game my guild have 50 Fifty Guild leaders - http://i.imgur.com/RVcmUTA.jpg WTF.
I was Guild leader and when they temp ban me, some fuck up happened
I cant demote other Guild leaders obviously. I need someone to reset ranks except for Guild leader char - Partizan. Can you fix my guild ?

**Comment by Evildoor** [comment]
#5514
