### ISSUE TITLE
Vehement Blades Not Working

### ISSUE THREAD

**Issue by sinderhella** [WarEmu/WarBugs#5608]
I can not get the witch elf ability vehement blades to work,  It does not matter if I am using shadow prowler or not.

**Comment by Evildoor** [comment]
Proof.

**Comment by sinderhella** [comment]
![sinderhella_000](https://cloud.githubusercontent.com/assets/19142979/14972358/eb717aaa-108f-11e6-8120-a8ca6554f3c1.jpg)
![sinderhella_001](https://cloud.githubusercontent.com/assets/19142979/14972356/eb6edebc-108f-11e6-9fd3-0a588e054b03.jpg)
![sinderhella_002](https://cloud.githubusercontent.com/assets/19142979/14972357/eb701d5e-108f-11e6-96ad-16a77eccc451.jpg)

**Comment by ellionkeman** [comment]
ehm. When you use shadow, you get a new skill panel and should put there needed abilities

**Comment by ellionkeman** [comment]
and that ability works only in shadow status - it is so called opener, when you start attacking with that ability

**Comment by Torquemadra** [comment]
Basically when you go into stealth you get a stealth bar which replaces your main bar, as only some abilities are useable in stealth. When in stealth add the Vehement blades ability to the first hotbar and you will be good to go.
