### ISSUE TITLE
Wrong pvp zone T1 empire.

### ISSUE THREAD

**Issue by ellionkeman** [WarEmu/WarBugs#5609]
46.4k  13.8k Nordland Empire. I got pvp flag at that position. Looks like there is no pvp zone at all but I got it.
![lunder_007](https://cloud.githubusercontent.com/assets/18136746/14948163/019ba3ea-1046-11e6-99db-162f41731324.jpg)

**Comment by ellionkeman** [comment]
Even here. After relogging I got rvr flag here
![lunder_008](https://cloud.githubusercontent.com/assets/18136746/14948272/1a249d26-1047-11e6-8b7e-b7b8a3b86875.jpg)

**Comment by Evildoor** [comment]
#5468
