### ISSUE TITLE
Lost all items

### ISSUE THREAD

**Issue by AlistaireCrowley** [WarEmu/WarBugs#561]
Today game Went into a serious lagfest. Character get stuck in casting animation and such. I had to force shut off the game. When I log back on ALL my items on character is gone. Inventory and equipped items. And also a named mob I attacked just Before lagfest is gone. Some of the items are +8 str jewel, +10 int jewel. DoK lady weap. DoK shoulders ( rare). Stormcoursers dok arms. 
![molochai_001](https://cloud.githubusercontent.com/assets/10405430/5834875/2d87ab06-a162-11e4-85df-a753622f0e2f.jpg)

**Comment by MaxHayman** [comment]
Should be fixed. Let me know if it isn't.
