### ISSUE TITLE
[Quest] 'Ead 'Unta (part 2)

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#5611]
This is the quest to get Tracker Boots. Upon attempting it with my DoK, I got to this screen
![raveria_000a](https://cloud.githubusercontent.com/assets/13975292/14949252/1602bb8a-100e-11e6-8b96-4a95832d654d.jpg). Killing the Hero does not allow the quest to complete as the skull is still missing. The Undead Human Skull is not locatable (as far as I can tell), and was not part of the original quest on live, or earlier in RoR (I completed it on a Zealot).

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
