### ISSUE TITLE
Squig Herder Ability Git em!

### ISSUE THREAD

**Issue by Culdu** [WarEmu/WarBugs#5612]
Tooltip of Ability says I will also hit pets target if pets target is within 35 feet of me and pet also hits my target if it is within 35 feet of the pet. Tried it with pet an me attacking the same target. If pet is also in melee range I hit twice and pet hits twice like tooltip says. If pet is farer away (guess these 35 feet) I only hit once, but pet still hits twice. So opposit like it should be.

**Comment by Abolition** [comment]
I think the range on the ability is only like 5 or 10ft or so, which could be a factor. Unless this is intentional, then ignore me.

**Comment by Culdu** [comment]
This might not look very important but due to pets dmg is 60 and mine is 500 with that attack it is really a nerf for melee squig. So hope it will be fixed soon. Kind regards

**Comment by jonyjones** [comment]
dev near couter the malfunctionning ability but forget the squeal of basic squig that u use alot with tis ince only 2 mele pet and ability nedd mele. So basic squig taunt 30% damage on a 650 and 350 damage attack, but pet only do 100 damage on git em so its 60 damage bonus from taunt and it shuld be 300-350.

**Comment by grunbag** [comment]
the ability deal the intended damage
