### ISSUE TITLE
Missing russian symbols.

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5613]
After every restarting of the server some of saved russian symbols in guild window transform into some unreadable mess with question marks, so i have to retype it all over again every time.
I tested all symbols and these are eraseable (case sensitive):
Б, В, Г, Д, Е, ё, Ж, З, И, Й, К, Л, М, О, П, р, т, у, ф, х, ц, ч, ш, щ, ъ, ы, ь, ю.

**Comment by Luth-RoR** [comment]
Afaik cyrillic and lots of special symbols are not supported by the database on purpose. After each server restart you probably see the symbols that are really stored in the DB.

**Comment by Yellowpillow** [comment]
Update:
![nonameness_017](https://user-images.githubusercontent.com/18102127/36147400-7daa7988-10d1-11e8-9741-f265d6a0839d.jpg)
![nonameness_018](https://user-images.githubusercontent.com/18102127/36147401-7dcad732-10d1-11e8-9142-4836b3c0c731.jpg)
