### ISSUE TITLE
Persistent renown and influence points boost.

### ISSUE THREAD

**Issue by imagifault** [WarEmu/WarBugs#5616]
Noticed on character Ghotznug at Black Fire Pass, while engaging large order party.

After the glitch (looked like massive disconnect), renown went from roughly 36.6 to 37.37 lvl, influence for greenskins - from nearly lvl 2 to nearly lvl 3.

In combat log there were separate mesages, noting renown and influence granted to character (for no reason - no kills were actually scored).

An extra renown point also appeared. All changes to renown and influence persisted after client restart.

P.S. also influence reward (thickmuck sholdaplate) was available and successfully purchased.

**Comment by Evildoor** [comment]
Seems like usual packet corruption (#1810), except for the part that these gains persisted...

**Comment by RichardCRoR** [comment]
I just wrote up a ticket on a similar issue. It may be related.

**Comment by Vayra** [comment]
If the disconnected players were from the other faction and damaged by you, should it not count as a kill?

**Comment by imagifault** [comment]
Then it was the most massive slaughter a tank ever did in WAR, I suppose O_o
Yet, no kills were noted in combat log.
