### ISSUE TITLE
Renown points cannot be spent

### ISSUE THREAD

**Issue by RichardCRoR** [WarEmu/WarBugs#5617]
I started the game with 1 RR point to spend. (never have I stepped into T1 before then.)
within a 30 minutes time frame in T1, I was able to achieve RR 6 with no effort.
When I went to spend the RR points, it said I had zero remaining even though I was RR6.

**Comment by Evildoor** [comment]
> within a 30 minutes time frame in T1, I was able to achieve RR 6 with no effort.

Does not looks wrong to me. First renown ranks are easy to get. On live, where renown gain was higher (progression pack), your renown was constantly capped in t1 if you did no pve, especially when playing healer. Even in ROR you can get a fresh character to 2R/5RR by winning 1 scenario (maybe 2, can't remember exactly). I don't know for sure, but i suppose that you can get renown even faster by fighting in RVR with AAO.

Therefore, only interesting part here is this:

> When I went to spend the RR points, it said I had zero remaining even though I was RR6.

**Comment by noisestorm** [comment]
Just hit the respecc Button at the trainer tu actually update your Renownpoints. Its just not properly updated, but everything is there.
