### ISSUE TITLE
[NPC] Scavengeable critters

### ISSUE THREAD

**Issue by ellionkeman** [WarEmu/WarBugs#5618]
Nordland, Chaos Ch4
Sparrow can be scavanged.

![keman_000](https://cloud.githubusercontent.com/assets/18136746/14973878/68598204-10f6-11e6-8cf6-cc334fb59f8b.jpg)

**Comment by ellionkeman** [comment]
![keman_001](https://cloud.githubusercontent.com/assets/18136746/14973900/decf1296-10f6-11e6-8116-3a063e15c594.jpg)

**Comment by ellionkeman** [comment]
Chicken. 40.2k 48.3k Nordland Chaos. Same thing

![keman_003](https://cloud.githubusercontent.com/assets/18136746/14974196/7ff91c4a-10fa-11e6-83e9-043a7f19537a.jpg)

**Comment by ellionkeman** [comment]
Nrodland. Blackbird level 2. Same 
![keman_006](https://cloud.githubusercontent.com/assets/18136746/14975290/d7643862-1108-11e6-8d82-4172e3b4c5bf.jpg)

**Comment by ellionkeman** [comment]
Ostland. Doe 2 level. same 

![keman_013](https://cloud.githubusercontent.com/assets/18136746/14976489/c750c15a-1114-11e6-8496-377ad5b5b93c.jpg)

**Comment by Culdu** [comment]
Quite sure that it was the same on live server. With being able to level up scavenging also on higher monsters guess it can be removed.

**Comment by ellionkeman** [comment]
Ravenous vulture lvl 9. Mount bloodhorn. Same
![turngolf_025](https://cloud.githubusercontent.com/assets/18136746/15096513/b4a07bba-1504-11e6-85bf-3010fd9852de.jpg)

**Comment by ellionkeman** [comment]
Brine vulture lvl 16, Barak Varr. Same

![turngolf_084](https://cloud.githubusercontent.com/assets/18136746/15107029/eb3d979e-15d5-11e6-9850-0bb1c2398923.jpg)

**Comment by ellionkeman** [comment]
Dustfeather vulture lvl 23  Badlands. Same.

![turngolf_113](https://cloud.githubusercontent.com/assets/18136746/15171277/f68c170c-1755-11e6-97f0-71d060d0fdd3.jpg)

**Comment by d3BugErr** [comment]
Also pigs, chics and cows at Emp ch5 
![pigscavenge](https://cloud.githubusercontent.com/assets/25364850/22927163/e448de3a-f2c0-11e6-9d92-ccf8fd755c3d.jpg)

**Comment by Lheana** [comment]
Works fine for vultures now.

**Comment by NorKalli** [comment]
@Lheana can we close this?
