### ISSUE TITLE
I lost all my gear,and items in bag

### ISSUE THREAD

**Issue by Iltiriberia** [WarEmu/WarBugs#562]
Hi, I have a problem .When Connect me ingame with my shadow warrior Maldryr, I could not get into the server and had to reconnect. When I managed to get enter in , I had lost all my objects.

![maldryr_001](https://cloud.githubusercontent.com/assets/10632625/5838157/96b5381e-a185-11e4-989b-48e08d658772.jpg)

**Comment by MaxHayman** [comment]
Should be fixed. Let me know if it isn't.

**Comment by Iltiriberia** [comment]
Thanks a lot, MaxHayman! =)
