### ISSUE TITLE
Hand of Ruin channel continues after death

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#5621]
Hand of Ruin continues to channel, and deal damage, after death. In my particular instance, I committed suicide by killing myself with Backlash as I was casting it.
It could be the case for other channel abilities, too, I suppose.

**Comment by Evildoor** [comment]
#4939 is supposed to be fixed.

**Comment by ozarmidrashim** [comment]
Please don't report bugs in the current build - it's known to be completely ruined - thank you
