### ISSUE TITLE
SH ap tactics

### ISSUE THREAD

**Issue by cimator** [WarEmu/WarBugs#5626]
![leakypants_003](https://cloud.githubusercontent.com/assets/17130290/15023992/a2ce0b30-123b-11e6-84b4-2e538924acc9.jpg)
![leakypants_004](https://cloud.githubusercontent.com/assets/17130290/15024000/ac38699a-123b-11e6-93e1-ee9324377516.jpg)

While using these two tactics plink should be 39 ap cost as it says so; 
![leakypants_005](https://cloud.githubusercontent.com/assets/17130290/15024021/c52edb64-123b-11e6-8f2b-ad459dc9bcb1.jpg)

But uses 46 ap instead not 39, it first decreases %35 then increase for 20 ap cost, it should be the opposite.

**Comment by Luth-RoR** [comment]
Was the real AP usage with the tactic tested with an addon like "warhammer scrolling combat text" or just read from the tooltip?

**Comment by sioding** [comment]
No confirmation so i close this now.
