### ISSUE TITLE
[Apperance] Ironfist Armbraces Missing Appearance

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#5627]
The Slayer Arms Ironfist Armbraces from the quest The Great Chase in Barak Varr does not have any appearance in game.
![tackyshorts_000](https://cloud.githubusercontent.com/assets/13975292/15032864/c8e70a8a-122a-11e6-8f05-05f4b1ebb2f0.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
