### ISSUE TITLE
[ToK] Missing Entry - "Dirty Dealin'" - Dog Waylayer

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#5628]
Killing the Dog Waylayer in Snotwood Forest does not grant the ToK entry "Dirty Dealin'" as it should.
![dungchewa_025](https://cloud.githubusercontent.com/assets/18690551/15033711/c5c29eda-123b-11e6-9d5b-bff5c4006c33.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
