### ISSUE TITLE
[NPC] Deep Root Spider - Counts as Servant of Chaos

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#5629]
Deep Root Spiders currently count as kills for Servants of Chaos and not Giant Spiders.
![dungchewa_026](https://cloud.githubusercontent.com/assets/18690551/15033722/fb21279a-123b-11e6-9b00-7950120c79bc.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
