### ISSUE TITLE
Choppa's Invisible Armor

### ISSUE THREAD

**Issue by Dusty1474** [WarEmu/WarBugs#563]
I've just bought some new armor pieces from the AH and when I equipped them, they just "removed" my previous ones, as the present pieces ain't appearing on my character.

http://i.cubeupload.com/f0lUzA.jpg

**Comment by Elvenalthur** [comment]
What's the name of the item/s?

**Comment by Dusty1474** [comment]
Gale-Runner's Skully
Gale-Runner's Tuff Chest
Initiate's Punchas
Initiate's Bellybuckle

**Comment by Reggaewaldo** [comment]
Tested OK, the armor shows as intended.
This can be resolved.
