### ISSUE TITLE
Can't Hit Me! Mob Despawn

### ISSUE THREAD

**Issue by Faraso** [WarEmu/WarBugs#5630]
While farming in IC arena with black ork using Can't Hit Me! Mobs said this "NullReferenceException was thrown. This object will be destroyed." After the mobs died this resulted into NOT getting xp or loot and they despawned for good.

Note: I immediately spoke to a GM (Ayrion) about this and he delivered the issue to a Developer too.

![chernabog_006](https://cloud.githubusercontent.com/assets/19200794/15037238/e9a31850-12a1-11e6-9bea-44c77b6653e9.jpg)

**Comment by Evildoor** [comment]
#4168
