### ISSUE TITLE
Precursor gear on sale

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#5631]
Today someone was selling gear with Precursor prefix. 
Based on my knowledge this gear drops from chapter 22 mobs. Is this legit?
![precursor](https://cloud.githubusercontent.com/assets/18053736/15043519/ad4b6dde-12c5-11e6-9c73-f9b6567e3090.png)

**Comment by Evildoor** [comment]
We need to know the source of these items. Or, to be more accurate, both sources (where they should be acquired according to WAR and where they currently come from in ROR).

**Comment by MerryGitmas** [comment]
Based on what is written [here](https://www.returnofreckoning.com/forum/viewtopic.php?f=11&t=2324&p=24148&hilit=precursor#p24148) They should come from chapter 22

**Comment by Ryanfawkez** [comment]
These items drop from any level 39-40 mob of which Order actually has a few around the world, mostly in lairs.

**Comment by genisaurus** [comment]
Not a bug, they are dropping off creatures of the correct level.
