### ISSUE TITLE
High Pass: Public quest "Cult of the Magus", order: 2nd stage counts the wrong kind of npc, quest fails

### ISSUE THREAD

**Issue by iljuro** [WarEmu/WarBugs#5632]
It counts some Magi Devourers as Magi Chosen.
Some Devourers seem to not be counted at all.
Some Devourers that was counted for one player may not have been counted others.

![cotm](https://cloud.githubusercontent.com/assets/18705881/15049287/e1aab954-12ed-11e6-8e98-235d5cb3c5a2.png)

**Comment by iljuro** [comment]
Well it actually do finish if you kill enough Devourers. But I don't think it can be done with less then 10.
I have a feeling the ones (of some of) on the right hand side by the cave enterance don't count correctly.

**Comment by iljuro** [comment]
Today I got unlock for Snotlings when I killed the second Chosen

**Comment by Soulwhisper** [comment]
Also in 1st Stage it counts wrong.Looks like major issue on the counter of PQs.

**Comment by Soulwhisper** [comment]
#6935 Major issue yeah.
