### ISSUE TITLE
Repeating Quest Text

### ISSUE THREAD

**Issue by Leondros** [WarEmu/WarBugs#5634]
Hey guys, it's understandably not a huge priority as it affects probably .002% of players who read quests. I don't have any screen caps since it is easily explainable, but if need be I can take some. Basically, when you turn in a quest or talk to an npc midway through the quest, it displays the same text as when you first picked it up. I'm not sure if its packet loss on my end, but I tried my roomate's character and a wired/wireless connection, still the same results. I asked around a bit and the few people the answered also have the same problem. It'll probably be fixed with t4, but I just wanted to give you guys a headsup in case no one has reported it. I'm just a lore nerd and like reading the completion text but its by no means game-breaking (obviously :p) Thank you guys for all the hard work, i've been doing nothing but playing this these past two weeks!

**Comment by Ryanfawkez** [comment]
As it stands, 99% of the quests are missing their completion text. They can be restored if there is documentation of the hand-in text.

**Comment by Lheana** [comment]
I close this as it's a too general issue that affects ~5500 quests.
