### ISSUE TITLE
TOK - Daemonvine Kill count doesn't show

### ISSUE THREAD

**Issue by Eusebeus82** [WarEmu/WarBugs#5635]
Daemonvine kills in the TOK don't count up. Unlocks for kills are granted correctly however.
![eusebeus_044](https://cloud.githubusercontent.com/assets/18599533/15062804/d960eef0-133b-11e6-93cd-c6add2396f75.jpg)

**Comment by Lheana** [comment]
I found they count in the line ???? (at the place of Daemon Prince)
![anaehll_307](https://cloud.githubusercontent.com/assets/11537611/21741908/bf1e5eb4-d4e3-11e6-9c65-df61af9be25e.jpg)

**Comment by Luth-RoR** [comment]
Great find, thanks.
