### ISSUE TITLE
TOK Beastman Gor - Kill Counts not granting unlock

### ISSUE THREAD

**Issue by Eusebeus82** [WarEmu/WarBugs#5636]
Kill counts for Beastman Gors are not granting unlocks :(
![eusebeus_013](https://cloud.githubusercontent.com/assets/18599533/15062844/60a820f4-133c-11e6-94b6-def4ea1c3038.jpg)

**Comment by Lheana** [comment]
Fixed.
Note: if you have already killed 1/25/100 etc Gors, it won't trigger the unlock. Will only trigger for the next kill count unlocks.
