### ISSUE TITLE
Quest - Chasing Shadows (order Saphery)

### ISSUE THREAD

**Issue by Eusebeus82** [WarEmu/WarBugs#5637]
This quest given has no interactable object to collect in the (massive) marked area for the quest. I have scoured the area and killed every mob in it many times. You are intended to interact with a Map of Ulthuan, but it does not exist. Nor does the quest complete on killing any of the mobs in the area, or returning to the quest giver.
![eusebeus_047](https://cloud.githubusercontent.com/assets/18599533/15064473/86b345de-134c-11e6-8dee-4d93af10c420.jpg)

**Comment by wargrimnir** [comment]
This exists, but the quest blob covers the entire area. If it could focus on this one side camp that would be a great improvement. 
http://i.imgur.com/mCBX5iX.jpg
http://i.imgur.com/gPt6sgw.png

**Comment by wargrimnir** [comment]
I'll also note, after clicking on the map and getting the quest complete, there doesn't seem to be an NPC to turn it back into. Not one of the named elves in the PQ area, nor any of the questgivers at CH13 or CH14.

**Comment by sioding** [comment]
Changed the questmarker to a smaller one. Fixed with next patch

**Comment by sioding** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=25909
