### ISSUE TITLE
TOK - Highborn (History and Lore - Saphery)

### ISSUE THREAD

**Issue by Eusebeus82** [WarEmu/WarBugs#5638]
Activating the Intricate Vase at 45500,54000 should grant the TOK History Unlock for Saphery. The jug is present, but does not grant the unlock.
![eusebeus_048](https://cloud.githubusercontent.com/assets/18599533/15065354/b86ee0ec-1356-11e6-88cf-90982b3420d4.jpg)

**Comment by Lheana** [comment]
Still not working

**Comment by thorbolt80** [comment]
Please update in Wiki : not working yet
