### ISSUE TITLE
Horror of Tzeentch (Purple Horror) - The Colors of Horror

### ISSUE THREAD

**Issue by WARchosen** [WarEmu/WarBugs#5639]
Horror of Tzeentch (Purple Horror) - The Colors of Horror
"Aethyr Guard"
(D) & (O)
OSTLAND @ 43, 52. Kill 2 Horrors at once (within 1 second of each other) to spawn 1 Purple Horror. The 2 horrors must be different colours and they must be killed within the cicular blue runed areas of the Tzeentch Bonfires.

the purple horror dont spam when a i kill the pink and blue horror  even when i farm them for 2 hours

**Comment by Eusebeus82** [comment]
There used to be a whole cycle on this where killing the Purple Horrors a few times spawned in a champion Firewyrm to fight, standing on the rock spire in the area. This unlock could be made available surely, by just permanently having the Purple Horror mob in place? (Also the Firewyrm, cos they're cool, and there are none before T4 areas afaik)
