### ISSUE TITLE
Character gone

### ISSUE THREAD

**Issue by Parwun** [WarEmu/WarBugs#564]
Hi, I used delete option on lvl 1 character i wanted to remove, nothing happens, I did delete operation again, after short while two characters are gone, the desired one and another character.
 Character I did not remove and now missing: Bright Wizard- Birdman

**Comment by MaxHayman** [comment]
What character did you mean to delete?

**Comment by Parwun** [comment]
Account name is: Lomonosov
I kept Parwun on separate acc)

**Comment by MaxHayman** [comment]
What character did you mean to delete?

**Comment by Parwun** [comment]
Putin

**Comment by MaxHayman** [comment]
Did you remake him?

**Comment by Parwun** [comment]
Yes i did

**Comment by Parwun** [comment]
Solved, many thanks! You are the best!)

**Comment by MaxHayman** [comment]
=D
