### ISSUE TITLE
[NPC] One Tusk Shaman is...visually.."imperfect".

### ISSUE THREAD

**Issue by Krumlok** [WarEmu/WarBugs#5640]
![sin titulo](https://cloud.githubusercontent.com/assets/14275335/15078858/9156710a-13b5-11e6-9137-3169d99c6468.png)

Just a strange sighting I saw on Barak Varr, on the road to Lair. Cant exactly remember the coords

I don't know if it's a client-side bug, but I tried to re-log and the NPC was the same...uh..."thing". Relog didn't fix that abherration.

Sorry for the title. I couldn't find a proper one :(

**Comment by Ryanfawkez** [comment]
Already fixed in next patch.
