### ISSUE TITLE
Renown skill points dont save

### ISSUE THREAD

**Issue by MarwinDexter** [WarEmu/WarBugs#5641]
So whenever i go to a renown vedor to increase a stat, in this case both strenght and wounds, after i used my point on desired stat, the stats dont save and when i talk to the vendor/trainer again i have all points i just speded back. Tried relogging, and tried on diffrent characters nothing saves. also tried on destro side and on Order side. The problem is still here. Anyway, just wanted to let you know, dont know if this is a bugg or it is just no implemended yet!

**Comment by Evildoor** [comment]
Screens/video.

**Comment by MarwinDexter** [comment]
It works now, everytime after the server crash?? Or did you fix it?

**Comment by Evildoor** [comment]
I did nothing, and i doubt that anyone else did. Closing then.
