### ISSUE TITLE
TOK - Bestial Token

### ISSUE THREAD

**Issue by turtoi94** [WarEmu/WarBugs#5642]
![asgarth_001](https://cloud.githubusercontent.com/assets/19229060/15082228/5262939c-13cf-11e6-8bb7-38d0cddeabaf.jpg)

Killed a mob which gives a bestial token with the tome unlock, but I didn't receive the token. Need help with this one... Thanks! :D

**Comment by Evildoor** [comment]
#4567
I think it's a build regression.
