### ISSUE TITLE
[Scenarios] Frozen at Respawn Point

### ISSUE THREAD

**Issue by Shrewdz** [WarEmu/WarBugs#5647]
After death and upon respawn player is stuck at spawn point, cannot move (except to turn around in circle), cannot mount, jump, or cast spells/auras, etc. Reloadui does not fix the bug. Have personally been stuck at spawn point with several other players who were bugged--some were in voicechat with me at the time describing the same phenomenon. After match ends you will continue to be stuck at whatever area you spawn back to. Only fix is re-log.

This bug is game-breaking for several reasons. If it happens in an SC it immediately gives the opposing force the numerical advantage as well as breaking up group synergy. If this were to happen in an open world situation--the game breaking quality of this bug is obvious.

**Comment by Evildoor** [comment]
#5451
