### ISSUE TITLE
[Scenario] Gates of Ekrund--Falling Into the Castle

### ISSUE THREAD

**Issue by Shrewdz** [WarEmu/WarBugs#5648]
Twice during different scenarios of GofE I have fell through the castle floor while taking flags. At the time I was in Curse chat and had zero lag issues. My client was downloaded via Torrent--the more stable way. What occured is that as I was taking the flag my toon literally slipped through the floor. Next thing I know I land on the ground beneath and am inside the structure. To get out I can go through the walls--they are one way.

This bug is a problem because it can ruin a game especially if the score is close.

**Comment by Evildoor** [comment]
#1677
