### ISSUE TITLE
Quest - Dwarf Starter Quest Rewards

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#5649]
In the Dwarf starter area in Ekrund, there are at least six quests that reward glove-items, while none reward boots or shield/weapon. 

The quests [Bitterstone Legacy], [Fight On], [Hit 'em Where it Hurts] and [Golden Age] all reward the same glove item (Watchguard's ...) and the quests [Outta Sight, Outta Mine] and [Ore Not] give the same item (Preserver's ...)

When you hit Ch. 2, you'll have six nearly identical glove items. A small problem, but a simple fix.

**Comment by Paleolog77** [comment]
Did not create a new topic. Quest "Ore Not" (i think) have ended, but quest items 'Bitterstone Ore" are still inside inventory, & continue to accumulate.
![8](https://cloud.githubusercontent.com/assets/23325288/21520567/4e97b490-cd06-11e6-91e2-723ecbb25cf9.jpg)

**Comment by sioding** [comment]
Checked all Quests in the starter Area - look fine no double gloves
