### ISSUE TITLE
Scenario PQ Ui popped up

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#5651]
I joined scenario while i was in PQ area(Burning windmill).So in the mid of scenario the scoreboard popped up.
![pokopikos_000](https://cloud.githubusercontent.com/assets/16864486/15091067/b4d7c436-1445-11e6-915e-64a16e7a5e7f.jpg)

**Comment by Evildoor** [comment]
Have you participated in the PQ? Or just queued a SC and stood there doing nothing?

**Comment by Soulwhisper** [comment]
I participated.It was for my quest(Killing seekers horrors and interacting with abandoned sack).But yes...it counted in the PQ too.

**Comment by Evildoor** [comment]
Then i don't see anything wrong here. You participated, then someone finished the PQ and the game informed you about your contribution and reward. Why should the game care that you've left the PQ area? And it was the same on live, IIRC.
