### ISSUE TITLE
Quest - The Eagle's Claw

### ISSUE THREAD

**Issue by Jsnen** [WarEmu/WarBugs#5652]
Firstly; the Elven Bolt Thrower does not work.
Secondly; the 'replacement' Harpies that spawn in the path leading on from the Bolt Thrower are too high level, mostly level 4-6, where the player is at most level 2 at the time.
Thirdly; the dead harpies and the dead Calumel Survivor around the bolt thrower come alive every other minute or so.

**Comment by Evildoor** [comment]
#5007

**Comment by Jsnen** [comment]
There is still the matter of two lvl 4-6 Harpies spawning on the road leading on.

**Comment by Evildoor** [comment]
Comment #5007 then.

**Comment by Jsnen** [comment]
This is what I'm talking about, which isn't mentioned in #5
![velehen_001](https://cloud.githubusercontent.com/assets/19235618/15097770/6ae8aab0-1527-11e6-861e-d9ea1b7f1053.jpg)
007 
![velehen_000](https://cloud.githubusercontent.com/assets/19235618/15097772/70d6605c-1527-11e6-98e5-cb188da0ca73.jpg)

Two harpies that spawn at too high a level for the area.

**Comment by Meralors** [comment]
Changed Harpy level to match player level at this part of game. Also moved the "chain dieing" harpy that kept spawning on npc.
