### ISSUE TITLE
Shadow Warrior - Grim Slash playing wrong animation

### ISSUE THREAD

**Issue by Jsnen** [WarEmu/WarBugs#5653]
When using the ability Grim Slash as a Shadow Warrior, the animation played looks more like a cowering or fear animation and definitely not an attacking animation.

Edit: It seems to be specific to when you're holding a bow in your hand, for instance after having used Eagle Eye - holding a sword in you hand, a proper animation plays.

**Comment by Evildoor** [comment]
1) As you said, this happens when character swaps weapons. It was always this way in WAR.
2) Even if this is wrong, i doubt that we can do anything here, since it's a character animation which comes from the game client, AFAIK.
