### ISSUE TITLE
Bug in backpack or with Seeds & spores

### ISSUE THREAD

**Issue by Sledgehammerz** [WarEmu/WarBugs#5654]
Currently i noticed that after making tauts gobsworts and try to convert them back to spores, this fails and i loose them all (lost like 50 of them before i noticed). The same happens when making majestic goldweeds and trying to convert them back again.
Additional, in the backpack all my seeds and spores are stacked in 1 field of the backpack, flickering between them, i cannot move them or separate them. 
Relogging does not work, and after exiting the game all is gone.
I get an error message while logging into the game, stating that moving the item failed.
I get the same error message when i try to move the seeds from the crafting backpack to the main backpack.

Anything to do about that? i cannot use my cultivation at the moment?

**Comment by Evildoor** [comment]
Items in one slot: #1548

**Comment by Sledgehammerz** [comment]
no not that one, i have 4 x 2 rows, happens in the 3rd section, 4th slot. But indeed that same flickering happens as shown, but now from all my seeds and spores while they are all stacked in that same slot...
I managed to move them to main back pack to quickly right clicking them, they then come 1 by 1 there, but putting them back creates the same bug and same error messages.
