### ISSUE TITLE
Cockatrice (Petrified Corpse) (Slashbeak)- A Charmed Life

### ISSUE THREAD

**Issue by WARchosen** [WarEmu/WarBugs#5656]
Cockatrice (Petrified Corpse) (Slashbeak)- A Charmed Life
CLOAK ITEM
SAPHERY @ 59, 27.5. Head E and cross the road from the Ithilmar Tower PQ. You should see a small camp of cockatrice type mobs and toward the wall there will be a corpse that's clickable. Click it to receive an item and then kill the L27 champ to receive the unlock for: Plumes of the Eye Killer.

the corpse "Petrified Corpse" dont give a item so kiling 27 champ will dont give a unlock Plumes of the Eye Killer

**Comment by Vayra** [comment]
Just click the corpse, then kill the champ. I've gotten the unlock on 2 chars that way.

**Comment by Eusebeus82** [comment]
I've received the unlock on my knight just by clicking the corpse, iirc.

**Comment by WARchosen** [comment]
me and 2 other players on destro side clik on corpse and kill the champ and nothing happens

**Comment by Blaqwar** [comment]
Simply killing Slashbeak worked for me on 3 Order characters now, a few months ago and just today.

![slashbeak](https://cloud.githubusercontent.com/assets/5108812/22113334/32384d2a-de66-11e6-88b7-d38eda769bfb.png)
