### ISSUE TITLE
Fae Dust

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#5657]
These seem to be on the same drop list as R9-11 gear, and are marked BoP. Second one I've found, so I'm guessing there's Fae Dust for each class.
http://i.imgur.com/c67g4Bt.png

**Comment by Ryanfawkez** [comment]
Quest reward item that is wrongly dropping as a PvP drop due to the 'Bloody' prefix, shared by Rank 11 gear.

**Comment by wargrimnir** [comment]
I fixed this!
