### ISSUE TITLE
Ostland PQ Empire Ch 8 Black mire bugged

### ISSUE THREAD

**Issue by iljuro** [WarEmu/WarBugs#5659]
I've got influence bar but i doesn't move

PQ-status says: 
Destruction - Stage III 0:00
Rhiliza 0/1
Destruction - Plague Trolls
Plague Trolls 0/65

I've farmed it a good while but no second stage

**Comment by Sayce78** [comment]
PQ is in stage 1 and kills do not count toward stage 1. I received no influence. 
Black Mire Gor - 0/15
Black Mire Ungor - 0/15

**Comment by Razielhell** [comment]
Works now @Luth-RoR
