### ISSUE TITLE
Items dropped by Master Moulder Vitchek are wrongly flagged as bind on pickup

### ISSUE THREAD

**Issue by Luth-RoR** [WarEmu/WarBugs#566]
The blue items dropped by "Master Moulder Vitchek" in Altdorf are wrongly flagged as BoP. On the original server they were BoE and were a common sight on the auction house.
![luthiell_003_crop](https://cloud.githubusercontent.com/assets/8567481/5889868/72d2692a-a43d-11e4-9b1d-282abdf045bc.jpg) ![thorgotan_021_crop](https://cloud.githubusercontent.com/assets/8567481/5889869/73b6421c-a43d-11e4-9ba0-1927d6cbdc0e.jpg)

This data here is outdated / wrong: http://www.warbits.com/gold-items-30288-Intruders-Horn-of-Accuracy.html . Almost every item seems to be BoP on that DB.

On the original server normally only the following items were BoP:
- armor set pieces + special weaponry dropped from instance or dungeon bosses*
- gear from public quest bags
- gear bought with any form of "token" from one of the vendors

*Master Moulder Vitchek is not one of the altdorf sewer bosses, despite the fact that he spawns in one of the instances sometimes. He is one of the special bosses that spawn in the world, when a certain prerequisite is met.

**Comment by Thorgatin** [comment]
The green "Infiltrator's" items are also wrongly BoP:
![lutece_008_crop](https://cloud.githubusercontent.com/assets/8567481/6041537/a62b6982-ac7d-11e4-9f7e-b024c6d22913.jpg)

**Comment by Thorgatin** [comment]
Also all jewelry dropped by him was flagged as "unique", so you could only equip the same item once.
