### ISSUE TITLE
NPC texture bug

### ISSUE THREAD

**Issue by ellionkeman** [WarEmu/WarBugs#5661]
44.0k 48.6k. Tor Aendris, The Blighted Isle. NPC Shinig warscout has some strange textures.

![turngolf_016](https://cloud.githubusercontent.com/assets/18136746/15096127/482def54-14f4-11e6-9938-929dc8cdf71e.jpg)

**Comment by Meralors** [comment]
Fixed.. somehow.. Dont ask, its dev magic stuff.
