### ISSUE TITLE
Critter wrong place

### ISSUE THREAD

**Issue by ellionkeman** [WarEmu/WarBugs#5665]
tracker mastiff, mount bloodhorn. This dog is always in the water and swimming. Doesn't look like it has to be so :)
![turngolf_053](https://cloud.githubusercontent.com/assets/18136746/15097733/f5770478-152d-11e6-99d9-f244e7a7edf9.jpg)

**Comment by Evildoor** [comment]
Coords.

**Comment by ellionkeman** [comment]
31.0k 14.3k

Sorry, I forgot about coords D:

**Comment by Meralors** [comment]
Moved the dog, won't be swimming anymore.
