### ISSUE TITLE
Rune of warding 

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#5666]
Rune of warding ability doesnt cast if enemy NPC is full health.
Dont know about enemy players.

**Comment by ozarmidrashim** [comment]
No bugs from the current build, thanks.

**Comment by Soulwhisper** [comment]
Can you look into this now or still not yet?

**Comment by Evildoor** [comment]
Tested on dev, cast buff on self, used RoW - it correctly applied to a NPC.

**Comment by Soulwhisper** [comment]
https://www.youtube.com/watch?v=BktWOuuR4gA

**Comment by Evildoor** [comment]
Is that 30 ft range?

**Comment by Soulwhisper** [comment]
My bad you are right.
