### ISSUE TITLE
Tactics after death...

### ISSUE THREAD

**Issue by ohmtastic** [WarEmu/WarBugs#5668]
Hello, noticed this earlier during RVR in high pass.

I have split arrows tactic on my SW and it doesn't proc after you die.

The situation is this, firing off spiral arrow, split arrows proc'ing fine, get killed while a shot is travelling, hits the target damaging it for more than normal (I guess the extra 30% that split arrows removes) and then doesn't proc to hit nearby targets within 20m.

This might also affect other tactics, being switched off when you die.

**Comment by ozarmidrashim** [comment]
I've had this tested and the testers reported that it works fine. I will need to see actual proof.

**Comment by ohmtastic** [comment]
Yep I'll try to simulate it again...

I know it definitely showed only the damage text on the target for 230 something, on a chosen of similar if not higher level which is more than normal (normally around 150). No other damage text markers appeared on other destro around the target.

It's nothing major, gamebreaking or even annoying. Just thought it was worth mentioning in case it was part of something bigger. Good to see you got back to me very quickly, loved this game when I was younger and I really appreciate you and the rest of the team putting time and effort into this [😊]
Martyn


________________________________
