### ISSUE TITLE
Problems with my click on portraits and guild options

### ISSUE THREAD

**Issue by Iltiriberia** [WarEmu/WarBugs#567]
Hi, i'm sorry, but I have a problem with my character Morkhian. When I click on portraits of another players to invite to party, the click fails and the options don't appears. In the friends list this bug also appears. It's very annoying that this bug don't let me upgrade rank another players in my guild. This bug only seems be with my character Morkhian.
![helpplease](https://cloud.githubusercontent.com/assets/10632625/5891300/ad1b93ea-a48d-11e4-92ce-a24508fed5a7.jpg)

**Comment by Thorvaldr1** [comment]
Having the same issue on all of my characters (the promoting in the guild and the inviting to a group)

**Comment by Evildoor** [comment]
The problem still persists? If yes - are your other characters (who don't have this problem) in guild?

**Comment by Evildoor** [comment]
No response, closing for now.
