### ISSUE TITLE
Talabecland portal to reikland

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#5671]
Not working atm (with the release of t4)
![sheyr_004](https://cloud.githubusercontent.com/assets/18032193/15099652/320ee1b2-155b-11e6-9a1c-69304338c2fd.jpg)

**Comment by Bonzoooo** [comment]
The portal works from Reikland to Talabecland, but not the other way.

**Comment by Razielhell** [comment]
Fixed in next patch.
