### ISSUE TITLE
orvr  objects

### ISSUE THREAD

**Issue by ellionkeman** [WarEmu/WarBugs#5676]
objects can be taken by "chicken" 
![turngolf_066](https://cloud.githubusercontent.com/assets/18136746/15099283/e4f0d8fa-1559-11e6-8c4c-5a364e7329ee.jpg)
![turngolf_067](https://cloud.githubusercontent.com/assets/18136746/15099285/e886927a-1559-11e6-8497-6eef0373ab80.jpg)

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
