### ISSUE TITLE
T4 SCs granting Soldier Emblems

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#5680]
Just finished a t4 sc on my r35 dok, was awarded 3 Soldier Emblems when I should have been awarded 3 Officer's.
![forkrul_003](https://cloud.githubusercontent.com/assets/1183293/15099362/b70a5a5c-1553-11e6-9de3-fd9db0e6de63.jpg)

**Comment by Evildoor** [comment]
Looks like the scenarios are still using old tiers. I've just been on a sc with a mix of lvl 27-28, 30 and 35 players.

**Comment by genisaurus** [comment]
Fixed during rapid patch,
