### ISSUE TITLE
Wrong class items offered by RVR vendors

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#5682]
(Martial Longsword of the Survivalist)I can buy this from renown weapon quartermaster.Its a sword but doesnt belong to WPs.

**Comment by Evildoor** [comment]
Known issue. For some reason, some items without explicit class restriction are offered to other classes.

**Comment by Soulwhisper** [comment]
Same issue with BW
![pyromanths_007](https://cloud.githubusercontent.com/assets/16864486/15139438/cca686d2-169e-11e6-9094-7801e207e887.jpg)

**Comment by Evildoor** [comment]
And DE swords, and Mara Axes, and possibly some others. Don't bother naming them.
