### ISSUE TITLE
Bright Wizard spell not working - Rain of Fire

### ISSUE THREAD

**Issue by Kulayleus** [WarEmu/WarBugs#5683]
Rain of Fire not working - 8177 Rain of Fire threw an unhandled ArgumentOutOfRangeException from the Void AddBuffCommand(Worldserver.unit.WorldSererv.BuffInfo.Common.AbilitymodifierEffect)

**Comment by Zanilos** [comment]
[http://imgur.com/hFNISSK](url)

**Comment by ozarmidrashim** [comment]
Should be fixed
