### ISSUE TITLE
An Eye for Trouble quest

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#5686]
The quest shows an Invalid Creature for the target with a note to report to GM:
![forkrul_004](https://cloud.githubusercontent.com/assets/1183293/15099563/ce202b0e-1558-11e6-8881-1a5413aa0f63.jpg)

**Comment by Evildoor** [comment]
Per #6214: there are two quests with the same name available at once on this NPC.

**Comment by sioding** [comment]
Checked - everythings fine

**Comment by Rockalypse** [comment]
@sioding just checked, looks like problem reappeared.
![12](https://user-images.githubusercontent.com/42712833/44951161-5d986b00-ae65-11e8-8e6c-2ebbe5e2905e.png)
![13](https://user-images.githubusercontent.com/42712833/44951162-5d986b00-ae65-11e8-82ae-f9514cf0f660.png)
