### ISSUE TITLE
"time to waaagh!" quest have wrong description and does not indicate on the map the location of the objective

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5689]
First: "time to waaagh!" is diplicate name quest
![default](https://cloud.githubusercontent.com/assets/18102127/15099597/b6b5363c-156a-11e6-95b1-bb0b31f83b44.png)
2nd: it cannot be completed, there is no such mob as Wazgit anywhere near Badrot's Bashin' Place, there is no any horns to use, and there is no any mark on map to point the place where is quest objective. So there is no way to finish quest.
![2](https://cloud.githubusercontent.com/assets/18102127/15099627/5991516a-156b-11e6-96b6-10f55f13bc7c.png)
Okay i figure out what was the problem. I take that quest in, lets call it " pre-t4 bugged time", so i had not 2 quests with same name, but same quest in 2 different stages. So when i finish 1st stage (of 3 i guess), one of record is disappear, not opening 2nd stage because i already have 3rd and the last one stage. After i finish it i just be able to take rewards. 
So i think there will be no problem with double-named quest. The only problem might be in not spoting on map location of Wazgit and confusing description.

**Comment by Natherul** [comment]
there is a horn, it just cant be used... the horn is on the left side of the bridge, very small

**Comment by Natherul** [comment]
there is also a third quest that can be started in that camp (badrot) which I believe is the actual quest your looking for :D

**Comment by Torquemadra** [comment]
Wazgit is at Krungs scrappin spot, text ammended next patch
