### ISSUE TITLE
Unable to set rally point to Ch18 Destruction in DW

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#5690]
The Rally Master in ch18 Destruction camp gives an error when trying to set the rally point:
Unknown Rally Point NPC (5949)
![forkrul_005](https://cloud.githubusercontent.com/assets/1183293/15099637/e8d70f06-155a-11e6-95b3-ce23aae38fb3.jpg)

**Comment by saupreusse** [comment]
Fixed in the next patch.
