### ISSUE TITLE
RvR Kill Enemy x/x Quests not working.

### ISSUE THREAD

**Issue by ArrDub** [WarEmu/WarBugs#5691]
![war 2016-05-08 11-23-34-15](https://cloud.githubusercontent.com/assets/19254092/15099644/9fce45fe-150f-11e6-9431-4088f9eb936d.jpg)

**Comment by Evildoor** [comment]
Amount of kill quests was reduced to 1 per zone. Old ones which were now unavailable can't be completed. It seems that this is one of them.
