### ISSUE TITLE
Spellblade T1 RvR gear is Medium Armor

### ISSUE THREAD

**Issue by Plompkin** [WarEmu/WarBugs#5693]
I'm sure there's others but I've found these at least.

![saedren_000](https://cloud.githubusercontent.com/assets/19254156/15099685/17aec6c4-1511-11e6-87f8-134ee0cc538f.jpg)
![saedren_001](https://cloud.githubusercontent.com/assets/19254156/15099688/1d903884-1511-11e6-9505-79e5a9d58a79.jpg)

**Comment by Evildoor** [comment]
Spellblade's boots and gloves of Vengeance are affected (Chosen too).
Belts should not be armor, #5699.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
