### ISSUE TITLE
Bugged rally point in Praag

### ISSUE THREAD

**Issue by kaey** [WarEmu/WarBugs#5694]
When using book of binding and rally point set in praag, character get's teleported to Zone 0 or something

**Comment by Evildoor** [comment]
> rally point set in praag

Which one?

**Comment by Lileldys** [comment]
Captain Reinold in Westmark Barricade causes this for order at least.

**Comment by kaey** [comment]
Yes, Captain Reinold for order side.

**Comment by saupreusse** [comment]
Should be fixed in the next patch. (fixed all of the rally masters)
