### ISSUE TITLE
Mount speed even when casting

### ISSUE THREAD

**Issue by TheSOcialN** [WarEmu/WarBugs#5697]
I have a weird bug and i'd like not to get repported for speed hacking.

Sometime after using mount when i get dismounted i keep the speed and can cast while moving like if i was on my mount dunno if its a known bug or if its new or if it has something to do with run away

character : drunkenbill (squig herder)

**Comment by Symbelmyne** [comment]
Same for me, when i start casting while mounted I dismount but still can move with speed of mount. 
class SH

**Comment by CoolJoshuah** [comment]
same here

**Comment by grunbag** [comment]
doesn't happen anymore
