### ISSUE TITLE
Current quests are not displayed on the HUD by default upon first log on

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#57]
When you log on, any quests you still have outstanding appear under the quest tracker HUD as default. 

You can choose whether or not you want certain quests displayed on the HUD, under the quest tab in the tome of knowledge. But by default, all quests that are accepted appear on the HUD quest tracker.

![quest s not appearing on hud at log on as default1](https://cloud.githubusercontent.com/assets/7492543/2914886/e7861154-d6a2-11e3-83b4-87b2584d2fc4.png)

![quest s not appearing on hud at log on as default2](https://cloud.githubusercontent.com/assets/7492543/2914891/f5beb99c-d6a2-11e3-85cd-d453d2d2f000.png)

**Comment by milosxe** [comment]
Quest tracking on HUD is working now after a relog. Closing.
