### ISSUE TITLE
Dozens of nestled NPC clones in starting location.

### ISSUE THREAD

**Issue by Dmitrijv** [WarEmu/WarBugs#570]
I just made a new character and noticed that the NPCs who greet you in the starting area (Destro at least) have been cloned multiple times. They are all standing inside of each other and it looks like there are dozens of them in there. Same thing for mobs but in lesser numbers.

**Comment by Tuidog** [comment]
I have noticed this consistently as well and tried starting on both sides with the same results. Once a quest is received one of the NPCs in the stack often still holds the green book marker indicating there is a quest to obtain yet I have already taken that quest.

**Comment by Trollmar** [comment]
Yep noticed the same probs like you guys. I had the same problem with the enemy NPCs in the starting area too. (like the marauders. They standing inside each other too)

**Comment by Evildoor** [comment]
Many instances of this problem were fixed, so i'm closing this. Any remaining ones should be reported individually, with NPC names and locations.
