### ISSUE TITLE
Expedition Resources mini map icon

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#5707]
Expedition Resources merchant in warcamps shows up with Flight Master icon on mini map.

**Comment by Kaelang** [comment]
The report does not provide enough information to identify / replicate the reported issue.

Please re-open this problem if it persists with further information. 

You can view the latest guide to reporting bugs here: https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=37703
