### ISSUE TITLE
Squig Herder ranged pets 

### ISSUE THREAD

**Issue by Daknallbomb** [WarEmu/WarBugs#5709]
Ranged pets form squig herder dont attack from range , they run into meele fight

**Comment by Evildoor** [comment]
Proof.

**Comment by CoolJoshuah** [comment]
My squig do this as well, they run right to my target instead of staying away and doing range attacks.

**Comment by Zealote** [comment]
Fixed? Or maybe more info about the issue? My Gas/Spiked Squigs are initiating their attacks from range (maybe about 50ft, hard to say though).

**Comment by Zealote** [comment]
I only looked before at whether squigs were attacking from melee --as indicated by the inital report-- or from range, but I didn't think to compare the actual range here with that on AoR, which someone has just brought up as an issue on the forum.

Obviously, from the vid above, they _are_ attacking from range, but it seems that the current distance is indeed smaller than it should be. There must loads of examples/evidence, but there are 2 fairly clear ones at ~2:39 and 3:25-3:35 in the following vid: https://www.youtube.com/watch?v=FfilDuLX-40

Ofc, that doesn't tell you what the actual distance was. The tooltips for the Spiked Squig's abilities show 150ft, which seems really high to me: I don't remember being attacked by them from that far away, outside of detaunt range, but it could be right for all I know.

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16267#p178763
