### ISSUE TITLE
[Quest] [Nordland][Bad Item] Encroachting Darkness 

### ISSUE THREAD

**Issue by Chaoslan** [WarEmu/WarBugs#571]
Hello

For this quest, we need to pick up an abandonned sack in the zone of the public quest: The burning Windmill.

When we pick up the abandinned Sack, the item Cassock <LINK data="ITEM:434979" text="[Cassock
appears in our inventory bag. So it's not the abandonned sack and not in the quest bag.

I know this is minor, but maybe this will help to resolve orthers bugs faster ;-)

**Comment by Reggaewaldo** [comment]
This should not produce a quest item as it currently stand but rather a interaction with the Abandonned Sack. I will test the function when I have access to the Dev client.

**Comment by Reggaewaldo** [comment]
Tested Ok. Will go live with next patch/uppdate.

Closing.
