### ISSUE TITLE
Epic Quest Unmasking the Enemy

### ISSUE THREAD

**Issue by kusiu666** [WarEmu/WarBugs#5711]
I made I think 3 steps from npc Masked Shade in Caledor near warcamp. I colect dager from PQ Executioner Blade and after I go to that NPC  masked shade I finish that step he did not gave me next one.
 Sorry for english. My nick in game is Morgim I will gratefull if you will fix that for me. 
Thank you

**Comment by Evildoor** [comment]
My guess is level restriction.

**Comment by Torquemadra** [comment]
already fixed. and yes it was a level restriction.
