### ISSUE TITLE
Pets disappearing/running away after T4 patch

### ISSUE THREAD

**Issue by Symbelmyne** [WarEmu/WarBugs#5714]
Hi, today in Praag and TM my squigs randomly disapear but my skill for squig is still lit up. Recall doesnt work, need to resummon squig.

**Comment by Nycta** [comment]
I have the same thing, happens everywhere, orvr/scens, squig gets lost, waiting for it while calling it works sometimes but it is overall very hard to manage, especially in open rvr where one travels a lot - lost four squigs while moving from top BO to south one in Reikland, that bad. All the above with the squig on passive.

**Comment by Symbelmyne** [comment]
Yesterday I noticed that squig stopped disapearing, its somewhere (beneath textures), when I use follow or start attack something it comes back. That something new.

**Comment by Nycta** [comment]
I confirm what Symbelmyne says, if you stop before it is actually lost, something that does happen if you travel too far, and call it repeatedly, it will reappear, same thing if you get an enemy targeted and command it to attack.

**Comment by Tiggonos** [comment]
on wl: heel is casted periodically. also heel is lighted up all the time while it should be casted manually.
![melquardt_012](https://cloud.githubusercontent.com/assets/13809443/15433255/da5d64a6-1eb1-11e6-84af-63f013ed5b91.jpg)

**Comment by Symbelmyne** [comment]
I hope todays (21.05) fixes would work but they didnt. Tested in Altdorf/Praag on WL and IC/Praag on SH. No matter addon Loyalpet turned on or off, no matter command follow used or no. Every randomly 20-30s pet disapears, pet UI gone, skill of pet lit on, skills of pet greyed out. Attack doesnt bring back squig/lion.

[https://www.youtube.com/watch?v=cyWbeyAuCqA&feature=youtu.be]

**Comment by Tiggonos** [comment]
same with lion. when mounted at some point the lion just refuses to run and stands still. then ui disappears and comes never back. need to recast lion.

**Comment by ricdur** [comment]
Hi, same here, my squigs disappear every time during 20/30 seconds.

**Comment by geezereur** [comment]
Same here really sucks when you fighting someone in rvr and the lion goes to take a nap and you lose because of that.

**Comment by cervaes** [comment]
i have figured out the pets are disappearing only in certain places, not 100%, but mostly... I found 3 places in Praag: 32:33 , 24:33 , 22:45

**Comment by cervaes** [comment]
one more in 28:29

**Comment by ozarmidrashim** [comment]
Was dealt with
