### ISSUE TITLE
Squig Herder stuck in fast motion

### ISSUE THREAD

**Issue by CoolJoshuah** [WarEmu/WarBugs#5718]
I'm not sure whats causing this but for some reason my squig herder gets stuck on his mount.
I am still able to attack order players at mount speed. The only way I can fix this is to relog with my character. I also have got stuck with the "Run Away!" ability on and i'm running around at extra movement speed all the time. I fixed it the same way by reloging.

**Comment by trivoid** [comment]
Yes, this! I recorded a video of it (Ignore the death, it was but in the name of science)

Prevents me from using most keybinds, looks like speedhacking. I don't know why but it's not consistent, it does happen often though. Like @CoolJoshuah says, relog fixes it.

[https://www.youtube.com/watch?v=vatDbWbFdOM&feature=youtu.be](url)

**Comment by Evildoor** [comment]
#5697
