### ISSUE TITLE
rank cap bug 39-40

### ISSUE THREAD

**Issue by artypeterson** [WarEmu/WarBugs#5720]
For now rank 40 announced as cap. i got 39 and gain no more exp

http://joxi.ru/L210aldf63nMvm

**Comment by CoolJoshuah** [comment]
I had the same problem and I logged out then logged back in and I was 40.

**Comment by artypeterson** [comment]
Im not talking of getting renown rank 40 which works exactly hot you described. Im talking of rank. Lvl cap.

**Comment by genisaurus** [comment]
Fixed as of a rapid patch,
