### ISSUE TITLE
ToK: Dense and Denser

### ISSUE THREAD

**Issue by bughunterror** [WarEmu/WarBugs#5721]
ToK unlock for Rhinox not working. Clicked bone pile and no unlock.

http://warhammeronline.wikia.com/wiki/Dense_and_Denser

**Comment by CaptainoftheHarem** [comment]
I just wish to confirm that this unlock is still not working as of when I type this

**Comment by Lheana** [comment]
Interacting with 'Rhinox Bonepile' in Thunder Mountain, at loc 45k 59k, triggers the unlock 'Dense and Denser' but not the associated title 'The Rhinox Rocker'.

**Comment by Lheana** [comment]
This unlock and his title should be also triggered by interacting with another 'Rhinox Bonepile' in Thunder Mountain, at 49.2k 55.7k.

**Comment by Lheana** [comment]
Fixed
