### ISSUE TITLE
Quest in Altdorf - The Halflings Plight - Texture bug

### ISSUE THREAD

**Issue by Flammendrung** [WarEmu/WarBugs#5722]
![war_2016_05_09_00_21_15_070](https://cloud.githubusercontent.com/assets/19255851/15100734/fa160986-157b-11e6-81c8-8564eae6ca4f.jpg)
![war_2016_05_09_00_21_21_392](https://cloud.githubusercontent.com/assets/19255851/15100735/fa1a726e-157b-11e6-890d-45910fbe2f31.jpg)

**Comment by Lheana** [comment]
Quest no longer available, and GOs have been removed.
