### ISSUE TITLE
Tzeentch's Reflection

### ISSUE THREAD

**Issue by unowien** [WarEmu/WarBugs#5725]
The Chosen's "Tzeentch's Reflection" ability in the Discord tree has a line of sight bug.  Roughly 60% of the time when you go to use it it will say "Target is too far away" or give you the broken LoS message.  This spell is a self buff.  How are you too far away or out of sight of yourself?  There seems to be no way around this.  At first I thought maybe it was checking LoS or distance of my current target for no reason, as the spells distance/los check.  Instead of on myself (which makes no sense for that check to take place anyway).  So I tried using it with no targets selected mid-combat.  Still get this bug a lot.  It's just sometimes it works and sometimes it doesn't.  Best thing I've found to do is just spam the button and eventually it will work.

**Comment by ozarmidrashim** [comment]
This ability is correctly configured on the server.

**Comment by Luth-RoR** [comment]
No evidence/response -> closed.
