### ISSUE TITLE
Dusk have wrong proc

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5726]
On live there wasn't proc for AP, there was proc for decreasing 600 target's armor. I don't know is it was intentional or just by mistake.
![12345](https://cloud.githubusercontent.com/assets/18102127/15101235/681998f2-159b-11e6-8398-23175ef2cdc9.png)

**Comment by genisaurus** [comment]
Intentional, the procs on the epic weapons were moved around.
