### ISSUE TITLE
Reichert's Raiders PQ can't be completed

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5728]
on 1st stage objective is to burn the tents and rais the banner. So after burning those tents the banner can not be raised. There is one suitable place for banner but interacting with it don't do anything. Also there is already one banner in PQ's scope.
![arena_072](https://cloud.githubusercontent.com/assets/18102127/15101457/e1f5c4ba-15a1-11e6-9b05-e39340f3cc74.jpg)
![arena_073](https://cloud.githubusercontent.com/assets/18102127/15101456/e1f552b4-15a1-11e6-9ac9-a42e8a23f4f1.jpg)

**Comment by Styrkarr** [comment]
Don't click on the banner, click on the ground where stand the banner.

**Comment by Styrkarr** [comment]
Don't know why it's not working on live as it is on dev server. I changed the objective, now a click on the banner will work.
Fixed in next patch.
