### ISSUE TITLE
T4 lava deals no damage

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5729]
I jump into lava near Caladains furnace PQ and not die. 
![euthanizer_010](https://cloud.githubusercontent.com/assets/18102127/15101478/6fa3706e-15a2-11e6-8c2d-8f04da4c061e.jpg)

**Comment by sandreid** [comment]
Not sure if it's the same origin of issue, but water outside of zones (between DW and Isle of the Dead aka end of the "world") also deals no dmg, despite your chars making noises, clearly being unhappy about the whole thing.

**Comment by Lheana** [comment]
I think it has been fixed, right?

**Comment by NorKalli** [comment]
long since fixed
