### ISSUE TITLE
[Backpack] Item preferences do not filter items in bags correctly.

### ISSUE THREAD

**Issue by Dmitrijv** [WarEmu/WarBugs#573]
When you open your backpack you can click on an arrow on the right to configure each bags preferences individually. I tried to set up one of my bags to only accept green items when looting stuff from mails from the auction and it turns out that bag filters do nothing atm. I tested most of the check boxes and none of those work.

**Comment by Elvenalthur** [comment]
Related to #315, but this adds additional information towards the known issue
