### ISSUE TITLE
Falling from a great height in KV don't do any damage

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5730]
I jump down from 2  high bridges and don't get any damage from it.
I can't say for sure if it related directly to Kadrin Valley zone or it depends from height of jump.
![sdrghgsdgs](https://cloud.githubusercontent.com/assets/18102127/15101674/9de0f07e-15a6-11e6-91b8-a6c1feae1905.png)
![12345](https://cloud.githubusercontent.com/assets/18102127/15101686/def02198-15a6-11e6-8750-dcc38c543ed8.png)

**Comment by Taylz** [comment]
Bridge, mountain, fall from heights in general and is (Multiple Zone) referenced #5672

**Comment by Reggaewaldo** [comment]
Can confirm.

**Comment by Luth-RoR** [comment]
Closed as https://github.com/WarEmu/WarBugs/issues/7201#issuecomment-239415510 has more info on the bug.
