### ISSUE TITLE
Epic quest's weapons alternate appearance's problems

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5733]
Some of epic quest's weapons can't be set on alternate appearance, and for different classes there are different patterns.
For example for DoK there is no way to set Alt. Appearance for one-handed swords, but no problems with chalice. Orks can set one-handed weapon for alt. Appearance but can't do it with shields. BG can set A.A. for shields but can't for one-handed swords. 
![1](https://cloud.githubusercontent.com/assets/18102127/15102046/bfbc3a5a-15ab-11e6-953c-de90fa313a53.jpg)
![2](https://cloud.githubusercontent.com/assets/18102127/15102047/bfbcde10-15ab-11e6-928b-1fa8b1365f38.jpg)
![3](https://cloud.githubusercontent.com/assets/18102127/15102048/bfbed9e0-15ab-11e6-9898-9a708ab1913b.jpg)

**Comment by Torquemadra** [comment]
This is a system issue due to them being off or main hand the "alternative appearance" option doesnt show. Simply DRAG and DROP them into the alternate appearance slot as opposed to trying to get the prompt window up.
