### ISSUE TITLE
404 : gravity not found

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#5734]
after using the special power of the skaven cloak for a laugh i turned myself back into a magus by getting on my mount and it appears to have messed with the games ability to keep my angle relative to the floor in proper coordination...
![omadon_000](https://cloud.githubusercontent.com/assets/16922842/15102600/38ee99c6-1599-11e6-97e5-c58b22615323.jpg)

**Comment by Luth-RoR** [comment]
High likely client side.
