### ISSUE TITLE
Quest: "Organ Donor"

### ISSUE THREAD

**Issue by Gakvar** [WarEmu/WarBugs#5736]
Quest from Kazad Gromar given by Heindel Hildenmayer where the player is supposed to take control of an Organ gun on the walls and kill 5 Bloody Sun Trolls right in front of the walls. 

The guns work and fire well but barelly scratch the trolls, they charge the walls and the guards kill them, not awarding the player any credit. Upon trying to face the troll with brute force, they are easy to kill but yet don't award any credit for the quest.

**Comment by Sayce78** [comment]
Unable to take control of guns for this quest today. Tried guns on walls and guns outside walls, near trolls.

**Comment by Bonzoooo** [comment]
There are no trolls to kill. Guns work fine, but no trolls.

**Comment by NorKalli** [comment]
fixed

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
