### ISSUE TITLE
Quest: "The Fall of Thag Bolgar" and "Axes of the Fallen"

### ISSUE THREAD

**Issue by Gakvar** [WarEmu/WarBugs#5738]
These two quests from Kazad Gromar, Kadrin Valley, direct the player to turn them to Acolyte Bronzebanner, who's inside the Shrine of Grimnir right next to Kazad Gromar. 

The problem is the shrine has doors that cannot be opened like most other doors. The interactivity seems to be off.

**Comment by Lheana** [comment]
The door works fine now.
