### ISSUE TITLE
Portal from High Pass to Chaos Wastes

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#5741]
gateway to t4 is not working

**Comment by Evildoor** [comment]
Zone names.

**Comment by zak68** [comment]
from high pass to chaos wastes

**Comment by zak68** [comment]
![gabri_062](https://cloud.githubusercontent.com/assets/17765890/15399322/790f2588-1de7-11e6-88f8-0df72fd05999.jpg)

**Comment by Razielhell** [comment]
Fixed in next Patch.
