### ISSUE TITLE
Chosen Questline

### ISSUE THREAD

**Issue by NeoMoonlight** [WarEmu/WarBugs#5742]
In Tier 2 Emp/Chaos, 
I had completed this quest all the way to the Troll that has the Stone. When the NPC indicated by the quest is killed, the quest item isn't dropped or marked as obtained.

**Comment by Evildoor** [comment]
Troll name.

**Comment by NeoMoonlight** [comment]
Blightgore 

    On Monday, May 9, 2016 2:07 AM, Evildoor <notifications@github.com> wrote:
 

 Troll name.—

**Comment by Evildoor** [comment]
#1597
