### ISSUE TITLE
Bolster buff doesn't work in Serpent's Passage

### ISSUE THREAD

**Issue by Thorgatin** [WarEmu/WarBugs#5744]
Low level players don't get bolstered in T4 scenarios.

**Comment by Evildoor** [comment]
On all of them?

**Comment by Thorgatin** [comment]
I played a few. Can't say for sure, sry.
I also compared it with .getstats in the scenario and outside in the PvE to make sure it's not only the buff icon that is missing. The stats were the same out- and inside the scenarios for my lvl 35 IB.

**Comment by Evildoor** [comment]
I'm asking because i've just played Serpent's Passage in T3 and it had no bolster, so maybe it's related to this scenario and not T4 (can't play in T4 yet). Clarification, anyone?

**Comment by Evildoor** [comment]
It seems that i was right. Played T4 scens, they are fine, but bolster is missing on S'P in both T3 and T4 (and T1-2 too, i suppose, but i've not tested).

**Comment by Evildoor** [comment]
Seems to be fixed.
