### ISSUE TITLE
TM - Golgin Rockbinder Quests Auto-Complete

### ISSUE THREAD

**Issue by Taylz** [WarEmu/WarBugs#5747]
All quests given from Golgin Rockbinder auto-complete after accepting them without completing any tasks.

These all appear to be scouting quests.

![runredrun_020](https://cloud.githubusercontent.com/assets/18205385/15109221/830aa2d6-1619-11e6-901a-d9996bcd0bab.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch
