### ISSUE TITLE
Title: The Insane

### ISSUE THREAD

**Issue by Natherul** [WarEmu/WarBugs#5748]
The champ mob does drop the scintillating scale but the item cannot be used and as such you can not obtain the title currently. 

Minor issue :D

**Comment by Evildoor** [comment]
Mob name.

**Comment by Natherul** [comment]
Mob name is corrupt spawn, as stated the mob drops the right item but item cannot be used :D On retail you got the item and had to use it 3 times before you got the title (giving you text on each use)

**Comment by Natherul** [comment]
as stated in the other one, now closed: the item is not usable and gives a TOK unlock but it does not give the title

**Comment by Natherul** [comment]
also apparently the scale is now a pocket item, it should be just a consumable :P

**Comment by CaptainoftheHarem** [comment]
Just confirming that this is still an issue, I can equip the scintillating scale which drops from the firewyrm but it does not grant the title "The Insane"

**Comment by Natherul** [comment]
workaround fixed.
