### ISSUE TITLE
ToK: Cloak "Cape of the Screamer" 

### ISSUE THREAD

**Issue by seduch** [WarEmu/WarBugs#5749]
I killed the champ but no unlock for the cloak

From Live "Poke'm if You Got'em
5k, 25k. Kill Vilemaw, a Lvl33 champ Screamer who roams across the water just SE of the Lonely Tower PQ.
Reward
Cloak - Cape of the Screamer."

**Comment by Natherul** [comment]
indeed, also there is 2x spawn of vilemaw, one in the water and one on land closer to the tower
