### ISSUE TITLE
quest kill the deathless

### ISSUE THREAD

**Issue by lijebin** [WarEmu/WarBugs#5750]
kill the deathless quest is bug in t4 emp chapter 20 quest 
![grimskaldter_011](https://cloud.githubusercontent.com/assets/17027595/15110541/24a46b14-1614-11e6-9a85-d9df71372557.jpg)

**Comment by szejoza** [comment]
Fully working now (done it on 2 chars already)

**Comment by sioding** [comment]
thx @szejoza
