### ISSUE TITLE
NPC Darktalon Dragon repop time is way too long

### ISSUE THREAD

**Issue by seduch** [WarEmu/WarBugs#5751]
That NPC in dragonwake (51;58) had a very small repop time in the live version (almost instantly) and was great to farm for the cloak unlock (+ he droped blue seed too).

(I would really like the repop time do be the same as on live but as usual i refer to the wisdom of the dev )

**Comment by Yellowpillow** [comment]
his resurrection time was about 5 seconds on live, making him the only option to gain that cloak and blue seeds
![arena_074](https://cloud.githubusercontent.com/assets/18102127/15117403/710a1a7c-1618-11e6-95f2-ae3194365556.jpg)
