### ISSUE TITLE
T4 scenario books/chalices

### ISSUE THREAD

**Issue by kaey** [WarEmu/WarBugs#5752]
Since they are blue, they give 6 fury per second instead of 8.
Apostle's tome of solemnity
Apostle's tome of zeal

**Comment by Evildoor** [comment]
Apostle's Tome of Zeal is correct according to:
http://www.arsenalofwar.com/items/Order/Apostle's%20Tome%20of%20Zeal
Apostle's Tome of Solemnity is blue but should give 8 RF:
http://www.arsenalofwar.com/items/Order/Apostle's%20Tome%20of%20Solemnity
Strange...

**Comment by sioding** [comment]
fixed with patch from 09.03.2018
