### ISSUE TITLE
Annihilation quest reward for sorcs

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#5755]
The sorc staffs from the Annihilation Epic Quest are missing a talisman slot, they only have 1 while most other staffs with talisman slots have 2 (for example the t3 epic quest ones).

**Comment by Meralors** [comment]
Could you please give the item name? Easyest for us to find and correct it :)

**Comment by Vayra** [comment]
don't remember all the names, but Sacrilege and Torture at least. Though I'm fairly sure Torq already fixed it since we discussed it ingame.

**Comment by Torquemadra** [comment]
its fixed
