### ISSUE TITLE
Warrior Priest Spatterguards of the Mercenary missing TM slot

### ISSUE THREAD

**Issue by Zumos** [WarEmu/WarBugs#5758]
![zumoswp_011](https://cloud.githubusercontent.com/assets/19267650/15115531/b7566832-15ff-11e6-844c-1d493601404b.jpg)
Looking at the Warrior Priest sets now in Altdorf I saw that the Mercenary boots (Full name = Spattergaurds of the Mercenary) do not have a talisman slot, which it should have of course :)

**Comment by Meralors** [comment]
Fixed, live next patch.
