### ISSUE TITLE
Timmy's Day 1 Bug Report.

### ISSUE THREAD

**Issue by TimmyTheNerd** [WarEmu/WarBugs#576]
Character's Name: Eadwoppa
Race: Greenskin
Class: Black Orc

Some/most of these bugs may have been mentioned before but I like to be thorough. I was mostly a PvEr in WAR and so I'm doing PvE content first. I hope this can be of help, thank you for having me on RoR. Sorry if I'm doing this wrong.

GENERAL:
-Characters don't start with abilities in the action bar.
-Clicking on a corpse to loot it always autoloots everything.
-Mobs and NPCs stand still instead of moving when they should have a patrol path.
-Several NPCs and a few Mobs throughout the world clone spawn ontop of eachother. Seems to be dozens in each stack.
-Sometimes dead Mobs will continue to attack after being killed. Died to this three times.
-All Scenarios are broken.
-Several items in the game show the wrong thumbnail when displayed as quest rewards. The thumbnail seems to always be that of a goblin shaman staff.
-Ignore doesn't work. Neither does the /ignore command. You will still see what the person is saying. Very annoying when people spam /Advice.

BLACK ORC:
-General-
Black Orc uses the Choppa's animation when selected on the Character Select screen.

-Abilities-
Lob Choppa - It's possible to get stuck in the Lob Choppa animation and for the casting bar to be stuck at full.

CHAOS T1:
-Mobs and NPCs-
-Kill Collecters do not work.
-Restless Dead appear to have the wrong model.
-Tower Guard appear to have the wrong model and sometimes spawn in nothing but their undies.
-Dwarven Gyrocopters spawn on the ground and do not move.
-Seared Ghouls sometimes spawn with the wrong model.
-Calgn Putrich uses a generic zombie sound file instead of his own.
-Braewold the Depraved will be attacked by the Rapturous Cultists when he is spawned.
-The horse ride offered by Velix Majere cannot be taken.

QUESTS:
-General-
-Quest giver NPCs despawn and then respawn when accepting or completing quests.
-Quest items do not show up under the Quest Items tab in your inventory.
-Almost all of the Quests in game seem to have their requirements removed.

-Chaos T1-
Prove Yourself - The turn in symbol does not appear above Skurlorg Blackhorn's head after killing the Nurglings.

Dark Fate - The first Restless Dead you kill drops 2 Bones of the Dead, not sure if bug. The bones remain in your inventory until you destroy them.

Wicked Things - Vorgue's Sack Bag floats above the ground until clicked. The turn in symbol does not appear above Vorgue's head after collecting his bag.

Daemonic Strength - Hellfire Cannons don't work. Clicking on them automatically gives credit for killing a Dwarven Gyrocopter.

The Heart of Battle - You are not given the Ancestral Bane. Thorshafn Ancestors are already spawned. Killing them counts towards both quest objectives.

Destruction - Houses are already burning. You can click the same Kindling twice to complete quest almost instantly. Grimnot 'Eadbasha shows that he has a quest still, even after completing the requirements to turn in the quest. Still possible to turn in the quest, at which point Grimnot 'Eadbasha will still show he has a quest for you.+

Pillaging - Secured Chests don't despawn when clicked. You can click the same chest to complete the quest almost instantly. Offers same rewards as Promise of Power. Selecting the Gutstrap of the Flesh wont give you the item. 

Blood - The turn in symbol does not appear above Virixa Darkwhisper's head after killing the Empire Spearmen.

Promise of Power - Offers same rewards as Pillaging. Selecting the Gutstrap of the Flesh wont give you the item. Killing one Thorshafn Militiaman counts as participating in the scenario.

Show of Power - The Bright Wizard Acolyte doesn't spawn at the top of the tower, instead spawns outside of it  off to the East Side. Selecting the Orc Trophy wont give you the item.

None Shall Escape - The Empire Courier spaws at level 38 and kills in one shot.

The March - The turn in symbol does not appear above Haldar's head after killing the Seared Ghouls.

Foul Works - Charred Spores spawn above the ground, moving to on the ground when gathered. Sometimes the reverse happens, where they spawn on the ground and then move above it when gathered. The turn in symbol does not appear above Sursten the Deciever's head after gathering the Charred Spores.

Marked - Quest cannot be completed because the Crawling Doll cannot be used.

Nowhere to Hide - Shows the thumbnail for a second Big Choppa reward but it cannot be chosen. The first Big Choppa reward (forgot to write down the item name) will not be in your inventory if chosen.

The Dark One - If you manage to kill Braewold the Depraved, he will not drop his head. This makes the quest impossible to complete.

Foul Works - The Cluster of Stench item doesn't appear in your inventory. Killing a Defender counts towards the requirement to use the Cluster of Stench on a Defender.

The Eager - Big Choppa reward (again, forgot to write down the item name) cannot be chosen and has the wrong icon displayed.

ABILITIES:
-General-
Flee - Doesn't show the cooldown after being used and can still be clicked, although no effect is gained.

ITEMS:
Potions don't seem to work and are messing their effect tool tip.

**Comment by Elvenalthur** [comment]
Thank you for taking the time to assess, and raise issues that you feel need fixing. Please write one bug per one report.

**Comment by TimmyTheNerd** [comment]
I'll keep that in mind. I basically just take notes each day I play. I'll start working on organizing them by what I feel their priority is and only report the major ones. I doubt anyone wants to see me posting 20+ bug reports everyday.

**Comment by Elvenalthur** [comment]
Any legitimate bug is always worth raising. We don't have time to "rinse and repeat" the current state in game, but when others make us aware of something that was functioning fine, but isn't now. That's something useful to know.
