### ISSUE TITLE
NullReference Exception for summoning Imperial Hunting Hound

### ISSUE THREAD

**Issue by sioding** [WarEmu/WarBugs#5760]
![image](https://cloud.githubusercontent.com/assets/18517842/15117180/b3a16488-1606-11e6-95ec-4aebfba1872c.png)

**Comment by Lheana** [comment]
The dog is correctly summoned now.

**Comment by Oxo888** [comment]
i just bought the Imperial Hunting Hound with an old token i never spent ... and it doesn't summon

i cry

**Comment by lilimx** [comment]
Hey,

please open a new ticket with that issue. This was was closed 2 years ago.
