### ISSUE TITLE
Sun Dragon can't be attacked

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5761]
Sun Dragon (in DW near ch. 18 of dark elves) can't be attacked
![arena_073](https://cloud.githubusercontent.com/assets/18102127/15117487/d38525de-1618-11e6-9029-9c139a34523d.jpg)

**Comment by Torquemadra** [comment]
Hes scenery, hes actually flying up in the air just the byte is missing to make the model do same so shows it erroneously on the floor
