### ISSUE TITLE
cannon impact bug

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5762]
there should be nothing targetable and sometimes explosions, which is knock back players. Instead there targetable thing and no explosions.
![12](https://cloud.githubusercontent.com/assets/18102127/15117877/af64b7ee-161a-11e6-845a-889eaaf7df1d.png)

**Comment by NorKalli** [comment]
NPCs have long since been removed, would like to close this

**Comment by NorKalli** [comment]
NPC's need to be placed again, scripted to cause knockback AOE on a 15s timer
