### ISSUE TITLE
[TM] loot chest wrong spawn location.

### ISSUE THREAD

**Issue by saupreusse** [WarEmu/WarBugs#5764]
After we took the destro Keep in TM, the loot chest spawned just beneath the new Keep lord, which resulted in him flying through the air after the chest despawned.

**Comment by Ryanfawkez** [comment]
Does this happen for every keep? I placed the chest spawn at the same coords as each respective keep lord, so if it happens in TM it should happen everywhere.

**Comment by saupreusse** [comment]
it happens for TM and DW, so I guess it happens for all of em.
