### ISSUE TITLE
[TM] Keep Gate does not trigger Range AutoAttacks

### ISSUE THREAD

**Issue by saupreusse** [WarEmu/WarBugs#5765]
Destructions Keep Gate in TM does not trigger the range dps autoattacks (tested on SW).
I asked the players around me to confirm, and they had the same problem.
It worked perfectly fine when i switched from range to melee, and stood right before the gate.

**Comment by saupreusse** [comment]
this applies also for DW, so i guess it applies for all of the tier 4 gates.

**Comment by kamikaiser** [comment]
Seems this is still an issue. Currently unable to auto-attack or use Spiral-Fletched Arrow on keep doors (confirmed all T3 destro doors). Auto-attack just never happens, and spiral-fletched shows the cast bar and animation but then it just gets stuck at the end of the cast and nothing happens until you use a different skill.

**Comment by szejoza** [comment]
shouldn't be an issue anymore, we have rams for keep doors now
@sioding

**Comment by sioding** [comment]
thx @szejoza
