### ISSUE TITLE
Archmage Annihilator Highmantle (Shoulders) - missing stat

### ISSUE THREAD

**Issue by Pxl555** [WarEmu/WarBugs#5767]
**Annihilator Highmantle is missing +3% Reduction in being Critically Hit**

![screenshot1](https://cloud.githubusercontent.com/assets/17297910/15118642/6e7cc774-160d-11e6-903c-87b0cc93d52f.jpg)

**Mirror(Shaman) Shoulders:**

![screenshot2](https://cloud.githubusercontent.com/assets/17297910/15118653/7ad594b0-160d-11e6-89de-ac3740abf452.jpg)

**Other 2 Order Healers:**

![screenshot3](https://cloud.githubusercontent.com/assets/17297910/15118660/85d8ad84-160d-11e6-848b-2afbf8473e0d.png)
![screenshot4](https://cloud.githubusercontent.com/assets/17297910/15118662/872bab1e-160d-11e6-9f8c-9151e7df2921.png)

I checked the whole set just in case that it was allocated on another item. I can provide those screenshots if needed.

**Comment by genisaurus** [comment]
Fixed on next restart
