### ISSUE TITLE
PQ bags cannot be opened after server restart

### ISSUE THREAD

**Issue by Sersaypygan** [WarEmu/WarBugs#5768]
After a number of PQs, 5 PQ bags picked up via the mailbox will not open. Nothing at all happens when right clicking the bags in the inventory.

**Comment by Evildoor** [comment]
PQ names.

**Comment by Sersaypygan** [comment]
The pq was the Elven one in Dragon wake, Dark Elf side. Celdorian's (Spelling?) furnace.

**Comment by taccr** [comment]
Pretty sure this is some time based problem. Seems only to affect bags that have been in the mail for a certain time. Freshly mailed bags are not affected.
Maybe the loot gets removed by some garbage collection.

**Comment by Sersaypygan** [comment]
I did indeed wait overnight before getting some of them, but at least two of the bags where recent with my picking them up, within a few hours.

**Comment by genisaurus** [comment]
If you waited overnight, it is likely that the server was rebooted between the time when the bags were sent and when you opened them. PQ bag contents are not saved to the database, so if the server was rebooted, the bags would revert to standard items.

**Comment by Ziggesmuts** [comment]
Got a white bag in mail from Tomb of the deathsword in Praag didnt open after 20 min after pq was finnished

**Comment by roadkillrobin** [comment]
Having the same problem. 7 bags from Dragonwake PQ wont open.
