### ISSUE TITLE
Guild news don't show leveling (rr/rank)

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#577]
Under Guilds and Guild News, no report of it's members ranking rank or rr are shown as per what I remember..

**Comment by Yellowpillow** [comment]
indeed, in news should shows every 10rr after 40ff reached and also 40 lvl i think. I May be 
inaccurate on this.

**Comment by MaxHayman** [comment]
Wasn't a bug, just wasn't implemented. However I have added it in.

**Comment by sioding** [comment]
fixed with patch from 17.11.2018
