### ISSUE TITLE
The Winds Impervious set have wrong set bonuses

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#5770]
set bonuses now is x2= +25 ini, x3= +210 armor. 
![2](https://cloud.githubusercontent.com/assets/18102127/15120836/9bf7ad48-1628-11e6-9d24-a046e3eaecf5.png)
On live there was: 
x2 = 
On hit: 10% chance to decrease enemy's all type resistances for 185 points for 10 sec.
x3 =
On being hit: 25% chance to decreace enemy's morale for 50 points.
Proofs:
![default](https://cloud.githubusercontent.com/assets/18102127/15120775/5d9e93b8-1628-11e6-8259-b35e00f446b3.png)
sorry it is on russian, you can check the acuracy, i type russian text so you can use translater:
Эрозия: при ударе возникает 10% вероятность снизить сопротивление цели всем видам урона на 185 ед. (единиц) на 10 сек. (секунд)
Сомнение: при получении удара возникает 25% вероятность снизить боевой дух атакующего на 50 ед. (единиц)

**Comment by Evildoor** [comment]
> On live there was: 
> x2 = 
> On hit: 10% chance to decrease enemy's all type resistances for 185 points for 10 sec.
> x3 =
> On being hit: 25% chance to decreace enemy's morale for 50 points.
> Эрозия: при ударе возникает 10% вероятность снизить сопротивление цели всем видам урона на 185 ед. (единиц) на 10 сек. (секунд)
> Сомнение: при получении удара возникает 25% вероятность снизить боевой дух атакующего на 50 ед. (единиц)

I confirm this, and it was this way on live. However i don't know, maybe these bonuses were altered intentionally, like with epic weapons.

**Comment by Yellowpillow** [comment]
i hope not, because this is the only ToK acc. set usefull on live. I hope just by mistake those set bonuses was added on another set, and from that another set bonuses was added for this one.

**Comment by genisaurus** [comment]
This was an intentional change.
