### ISSUE TITLE
Sigmar's Hammer is now a T1 rvr zone

### ISSUE THREAD

**Issue by player1137** [WarEmu/WarBugs#5771]
After buying some Journeyman Relic Boxes in the tavern I hoped into a scenario, after coming back from it I got turned into a chicken. Minor bug.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
