### ISSUE TITLE
Tier 1 Nordland Warcamp - One less merchant for Destruction

### ISSUE THREAD

**Issue by YUKO1** [WarEmu/WarBugs#5772]
Hello! 

I am not sure if this is meant to be, but it makes me wonder. Before T4 was released there were four merchants on each side of Nordland Warcamps in Tier 1. It appears that Destruction has now one less merchant that doesn't sell recruiters medallion/items like Order Warcamp offers.

I was unable to find any information regarding this in the forums and I think it could have been missed.

![urzuranol_000](https://cloud.githubusercontent.com/assets/17162613/15123372/bea70898-1623-11e6-8030-69993e807bfb.jpg)

Kind regards,
YUKO

**Comment by Evildoor** [comment]
Report is correct (Order has 4 vendors), except that you are indicating the wrong place. Vendors were moved around a bit, and the spot you indicated was occupied by a zealot lady who sells weapons, and she is present (even on this screen). Missing one is Pillager Fasir.

**Comment by wargrimnir** [comment]
The missing vendor is the one that sells medallion set pieces. You can find him in the back of IC, but should also be at the warcamp as there's no Keep in the tier to buy from. Not sure if it's the same for Order side.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
