### ISSUE TITLE
Mordekhain report

### ISSUE THREAD

**Issue by Mordekhain** [WarEmu/WarBugs#578]
-1-
![mornekhain_031](https://cloud.githubusercontent.com/assets/10746714/5988268/984415a2-a972-11e4-9d24-5872395dd741.jpg)
Some problems with NPC wearing.
-2-
![mornekhain_029](https://cloud.githubusercontent.com/assets/10746714/5988273/e40a4ef2-a972-11e4-8fa8-835b886bfaa0.jpg)
NPC cant done this quest. He cant be a free.
-3-
![mornekhain_028](https://cloud.githubusercontent.com/assets/10746714/5988371/7fa389a2-a976-11e4-834f-a14e77164e40.jpg)
Renown points doesnt work.
-4-
![mornekhain_018](https://cloud.githubusercontent.com/assets/10746714/5988291/db619cf0-a973-11e4-93f4-ec3b5f8bcd71.jpg)
Sometimes Quest NPC fade out for several seconds.
-5-
![mornekhain_008](https://cloud.githubusercontent.com/assets/10746714/5988301/30b6a984-a974-11e4-9e9b-8e4eaf42e27a.jpg)
![mornekhain_007](https://cloud.githubusercontent.com/assets/10746714/5988302/3f3bb68e-a974-11e4-8d1f-8735b2f9d0c8.jpg)
Quest NPC start to attack "red" mobs and die in battle. Also quest is working nice.
-6-
![mornekhain_006](https://cloud.githubusercontent.com/assets/10746714/5988319/bbf954a6-a974-11e4-87d0-52f68c8da98a.jpg)
![mordekhain_001](https://cloud.githubusercontent.com/assets/10746714/5988330/57d3e76a-a975-11e4-9201-6399e20d079b.jpg)
After respawn in IC i always fly down. Often I stay under textures after SC.
-7-
![mornekhain_034](https://cloud.githubusercontent.com/assets/10746714/5988331/66cca82e-a975-11e4-85e6-bedff1f4f61e.jpg)
I can use Dark Protector (hatred working nice) but I dont see buff. Cant use Guard on my party players.
-8-
![mordekhain_008](https://cloud.githubusercontent.com/assets/10746714/5988374/adf826d2-a976-11e4-8217-b4c1bcbf825c.jpg)
The Covenant of Vitality heal me when my friend kick mobs and do not heal him.
-9- Same bug with "Rend soul". Sometimes this ability dont heal but deal damage.
-10-
![mordekhain_007](https://cloud.githubusercontent.com/assets/10746714/5988384/2d168a08-a977-11e4-9852-b791f9142fb9.jpg)
Soul essence bar fade out after using "Rend Soul".
-11-
![mornekhain_015](https://cloud.githubusercontent.com/assets/10746714/5988394/d0b687bc-a977-11e4-9b1e-a8aa5b83da69.jpg)
Often text on Hatred bar fade out.

I hope I help you!

P.S. Forgive me for my bad bad english! xD

**Comment by Evildoor** [comment]
Please, create a separate report for each problem next time.
Most of these problems are known or were already solved, so i'm closing this.
