### ISSUE TITLE
KABOOM!

### ISSUE THREAD

**Issue by Teefz** [WarEmu/WarBugs#5783]
1. KABOOM works, u get shot up in the air, but you do not leave the Squig Armor.
2. You do not get CD on KABOOM or Squig Armor since you don't leave Squig armor.
3. KABOOM can only be used once. After that you need to zone / relog.

**Comment by noisestorm** [comment]
to add: You can still disable or re-enable squigarmor, but all attacks are completely blocked.

**Comment by ricdur** [comment]
Hi, yes KABOOM is bugged, we can use it one time and after that that bug all the other abilities.
Castbar stop for all at 5% and abilities not works, need to disconnect and reload.
Thank you.

**Comment by Teefz** [comment]
Bump. This is still broken by the way.

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16267#p178763
