### ISSUE TITLE
Battle For Remembrance BUG

### ISSUE THREAD

**Issue by MarwinDexter** [WarEmu/WarBugs#5784]
I was doing this quest with a grp of people, we come to the " Pile " part, and after that was done, we killed ourself to respawn at a camp, and then my quest disapeared. I could run to Dwarf Ch21 and complete the quest, but not take the next part :O 
Now the Dwarf NPC " Burli Durinsson " woh i completed the quest at isnt giving me the next part of the chain quest.. Talked to all the Dwarfs at this camp and no one gives me the quest again :'( 
Please Help!! 
I am also lvl 33 Witch Hunter named " Marw "

**Comment by MarwinDexter** [comment]
Also relogged and restarted the client

**Comment by Evildoor** [comment]
My guess is level requirement. Get a level up (or several) and try again.

**Comment by MarwinDexter** [comment]
But if that is the case, why could i complete both Elf and Empire chain quests?

**Comment by Evildoor** [comment]
Maybe level restriction was removed from Elf and Empire quests, but not the dwarf one.

**Comment by MarwinDexter** [comment]
The thing is i almost completed the chain, but after the " Auto delete part " everything stopped working. It stopped tracking it, i was gone in the tome of knowledge quest section and i could complete it, but the quest isnt even at the npc anymore. If it was lvl restriction on it, i would not be able to pick it up in the first place right?

**Comment by Evildoor** [comment]
I don't get it. This part of your report:

> I could run to Dwarf Ch21 and complete the quest, but not take the next part

suggests that you completed a part of the quest, and then the NPC refused to give you the next part - this is normal behavior if this next part has level requirement, that's why i suggested it.

You are the only one with this problem? Your party members were able to continue normally? What levels they had?

**Comment by MarwinDexter** [comment]
The next part isnt even showing. The quest got removed from the quest log,
so i couldnt find it. But sure, will will lvl up and see if it solves it.
Thanks anyway

2016-05-10 17:26 GMT+02:00 Evildoor <notifications@github.com>:

**Comment by Evildoor** [comment]
> The next part isnt even showing.

And? World Of Warcraft has "i have quests but you are too low lvl" icon over NPC heads, but WAR has none. If NPC has quest with lvl restriction, you'll never know about it until you get the needed level. Or am i missing something?

**Comment by MarwinDexter** [comment]
No, you are right on that part. I just think it is strange that i almost
completed the quest chain, but i will do as you suggested and keep lvl up
the char, so i can give a more accurate answer if something is wrong

2016-05-10 18:02 GMT+02:00 Evildoor <notifications@github.com>:

**Comment by Evildoor** [comment]
No response in 2 weeks, closing.
