### ISSUE TITLE
Squig pets!

### ISSUE THREAD

**Issue by Teefz** [WarEmu/WarBugs#5785]
I'm sure you guys are aware of the White Lion pets and Squig Herder pets that are basicly teleporting all over the place. This post is just to ensure that all the bugs with the pets are known:

1. Pets teleport.
2. Pets despawn or just run off in one direction. (Even with Heel spam.)
3. Zoning and zoning while mounted will sometimes cause pets to gain INSANE movemeet speed issue.

**Comment by Evildoor** [comment]
#5753 
#5732 
#5785
#5709
