### ISSUE TITLE
Black Crag same npc on two places

### ISSUE THREAD

**Issue by MarwinDexter** [WarEmu/WarBugs#5786]
In Dwarf-Ch21 there is 2 of the same npc there " Burli Durinsson ". 
He gives you the same quests. 

![marw_074](https://cloud.githubusercontent.com/assets/19227687/15131576/7a1263e8-1651-11e6-8d16-a821a0db397e.jpg)
![marw_075](https://cloud.githubusercontent.com/assets/19227687/15131577/7a13c346-1651-11e6-8e41-769aff6f56e4.jpg)

**Comment by Lheana** [comment]
Has been fixed.
