### ISSUE TITLE
Invalid - Report to GM - Quest New Allies, New Enemies Empire Chapter 17

### ISSUE THREAD

**Issue by Zaxx0nd** [WarEmu/WarBugs#5787]
When speaking to Yalgon Sparktamer about quest New Allies, New Enemies in Empire, Chapter 17 an objective is invalid.

Invalid message: Invalid Go,plz report to GM, QuestID 10287,Objld=0 0 of 3

![image](https://cloud.githubusercontent.com/assets/19254707/15132203/da3b6b34-160b-11e6-9713-65fd9457824a.png)

**Comment by NorKalli** [comment]
long since fixed
