### ISSUE TITLE
Ability: KABOOM!

### ISSUE THREAD

**Issue by trivoid** [WarEmu/WarBugs#5788]
Video below showing the bug.

Basically, after using the ability KABOOM!, I can no longer use any abilities. Also, I never played on live, but from the description I guess I'm supposed to exit Squig Armor when using KABOOM!, which obviously doesn't happen in the video. 
Relogging fixes it.

Gorgeous ability, would love a quick fix, cheers!

https://www.youtube.com/watch?v=9Nypxs5HYug&feature=youtu.be

**Comment by Evildoor** [comment]
#5783
