### ISSUE TITLE
T4 Bound Book of Binding Zone 0

### ISSUE THREAD

**Issue by Taylz** [WarEmu/WarBugs#5789]
Currently bound to Praag WC. When using BoB to return, loads into Zone 0.
Used BoB from CW. When re-logging spawn into CW RvR Lake.
![runredrun_026](https://cloud.githubusercontent.com/assets/18205385/15135564/d3114f4e-16b6-11e6-892d-2967e1ec82e7.jpg)

**Comment by kaey** [comment]
This will be fixed with next patch.
#5694
