### ISSUE TITLE
Cinderfall

### ISSUE THREAD

**Issue by destruch** [WarEmu/WarBugs#5794]
When i step in cinderfall i automaticly teleported to badlands.

**Comment by Vayra** [comment]
This applies to all the smaller side-zones in T4, West Praag, Death's Peak and (possibly) Isle of the Dead. You get ported back to your rally point.

**Comment by Thorgatin** [comment]
Probably the custom fix to prevent people from exploring "dangerous territory".

**Comment by Evildoor** [comment]
Changelog 19th May, 2016
[Other changes]
- Opened West Praag, Cinderfall and Death Peak areas. Please report any bugs you find in these areas while doing your tome unlocks.
