### ISSUE TITLE
Quest Chaos chp 18 "Seize the Glory"

### ISSUE THREAD

**Issue by Ziggesmuts** [WarEmu/WarBugs#5795]
No count on Griffon Footman

**Comment by Mazadun** [comment]
+1 
![war 10-05-2016 20-55-32-120](https://cloud.githubusercontent.com/assets/15877842/15156857/a5c5e17c-16f1-11e6-999e-a8409e97eec2.png)

**Comment by NorKalli** [comment]
long since fixed
