### ISSUE TITLE
AAO

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#5797]
Half Warband had AAO and the other half didnt.
![paterellas_036](https://cloud.githubusercontent.com/assets/16864486/15142871/af55febc-16af-11e6-892a-55a70a17fd39.jpg)

**Comment by noisestorm** [comment]
Can confirm myself that the AAO buff is not consitently applied at all. Back in T3 this issue mostly just occured when the AAO was at very low values (20 and 40%) and pingponged around, but i even saw it with values of over 160% at T4.

**Comment by Tesq** [comment]
i add that aao apply in all pairing isntead the single zone

**Comment by Troelsnap** [comment]
The issue could sometimes be solved by going to a PVE area and come back into the rvr lake - just added info for the devs.

**Comment by taccr** [comment]
It looks like AAO is currently not distributed between all people of one faction in the zone.

Not sure if this is related but sometimes you get to keep your aao and get huge amounts of renown while almost everyone else has no aao.

Probably not being recalculated and refreshing properly when someone enters or leaves the zone.
