### ISSUE TITLE
Auction House wont allow cancellation of sales

### ISSUE THREAD

**Issue by s0undie** [WarEmu/WarBugs#5800]
keep getting an error that states "an unkown error was encountered with the auction house" while trying to cancel auctions.
![rofl_003](https://cloud.githubusercontent.com/assets/14369390/15142958/a4113146-16a7-11e6-9eb8-569e062334f3.jpg)

**Comment by noisestorm** [comment]
Tried it with a potion and a piece of gear right now. Works for me without any issues though. Are you sure those items were not sold before while you are still in this window? The mail icon at your Minimap makes me suspicious

**Comment by Evildoor** [comment]
#1103
