### ISSUE TITLE
[Quest] Defend Bloodfist Rock

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#5802]
Unsure if keep defence quests are supposed to have lower coin reward than the normal T4 "base" of 1.59g, but this quest gives 74.88 silver.

**Comment by Evildoor** [comment]
Kill quests give 74.88s in the central zone, 37.44s in the zone closest to your fortress, and 1.59g in the zone closest to the enemy fortress (c) Genisaurus
