### ISSUE TITLE
Oil on elf keep

### ISSUE THREAD

**Issue by pikara** [WarEmu/WarBugs#5804]
I buy today 2 siege oil (15g one) for def an elf keep on T4. On iner door, it dont do anything, cant even take it. On outer... after drop it, it rush to enemies like it was a pet, on start, to the guy i have selected then to the guy who attacked it... fun to see, not fun for my pocket bag.

Sorry, i have no time take pics (it die fast) and no gold to reproduce it.

**Comment by Partizan-Rusi** [comment]
I presume all siege engines work that way, thats why nobody use them.

![oil t4 war 2016-05-13 05-42-19-149](https://cloud.githubusercontent.com/assets/16727243/15236644/6b8f945a-18cf-11e6-8865-002a18c0c819.jpg)

**Comment by Soulwhisper** [comment]
Eataine keep doesnt even drop.

**Comment by szejoza** [comment]
Pretty much 100% sure Oils are working now everywhere
@sioding

**Comment by sioding** [comment]
thx @szejoza
