### ISSUE TITLE
Deaf Ears - Empire CH18 Quest Bug

### ISSUE THREAD

**Issue by player1137** [WarEmu/WarBugs#5806]
Slain Plaguetail Prophets are not being registered, the kill-count is not progressing.

**Comment by pixie126** [comment]
Can confirm, killing the prophets does not count for the quest.

![xramoth_014](https://cloud.githubusercontent.com/assets/15041016/15989706/adc9f37e-3044-11e6-8a0c-b6128d4ea0c1.jpg)

**Comment by NorKalli** [comment]
changed mob required for completion

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
