### ISSUE TITLE
nonexistant tactic frozen fury: 9517

### ISSUE THREAD

**Issue by stillwaterww** [WarEmu/WarBugs#5807]
when i slot this tactic this is the message i get. 
nonexistant tactic frozen fury: 9517
![iobel_002](https://cloud.githubusercontent.com/assets/19287032/15147878/2901a230-16c3-11e6-83ea-38f1b67c88d7.jpg)

**Comment by stillwaterww** [comment]
Also this I just discovered, if I have frozen fury slotted and I relog my entire tactics bar is empty. This does not happen with any other tactics.

**Comment by Pxl555** [comment]
Just saw someone write that the tactic is bugged , just want to point out that it constitutes a very sizable party damage increase while the other side has full access to it and it directly impacts performance of other tactics such as "tapping the dark" ( path of agony 7p tactic) making those much worse.
