### ISSUE TITLE
[Black Orc] Da Greenest Bellow

### ISSUE THREAD

**Issue by Grywwy** [WarEmu/WarBugs#5808]
![grywwy_035_bugtracker](https://cloud.githubusercontent.com/assets/13614929/15147889/357d0446-16c3-11e6-8c2b-944cbd519214.jpg)

Buffs from the "Da Greenest" Warbellow dont seem to work for the group

**Comment by ozarmidrashim** [comment]
Is Loudmouth slotted?

**Comment by Grywwy** [comment]
I'll test this on thursday again and reply back to you.

**Comment by Grywwy** [comment]
I just saw that you get Loudmouth at lvl 37 and my Guildmate BO was lvl 35, so can't be.

**Comment by Grywwy** [comment]
He just told me that "You Got Nuffin" was slotted

**Comment by Diskete** [comment]
da biggest , and da toughness have same problem too, dont work for the group in my case with rugged, good wif shield and im da biggest tactics slotted.

**Comment by grunbag** [comment]
Fixed already
