### ISSUE TITLE
magus lv 38 mount doesn't correspond to their colors

### ISSUE THREAD

**Issue by ursvamp** [WarEmu/WarBugs#5809]
the magus mounts does not correspond to their respective colors

**Comment by Evildoor** [comment]
#5583

**Comment by Torquemadra** [comment]
According to what? Which colours? Wheres your benchmark?

**Comment by ursvamp** [comment]
![1](https://cloud.githubusercontent.com/assets/16873706/15154905/6a18c508-16b6-11e6-81b8-3facf6e2a5d2.png)


How I post my benchmark sir?

**Comment by Torquemadra** [comment]
those are heavy 75% mounts and colour different

**Comment by ursvamp** [comment]
somehow we can see the preview of he 60% colours?

**Comment by Torquemadra** [comment]
I will look into placing the 60% ones when I can, sorry for inconvenience.
