### ISSUE TITLE
Battle for Praag - Scenario

### ISSUE THREAD

**Issue by player1137** [WarEmu/WarBugs#5811]
Central Praag BO can't be tapped/taken over.

**Comment by player1137** [comment]
![obobo_000](https://cloud.githubusercontent.com/assets/4945074/15149431/cee736fa-16c9-11e6-921f-b2ffc9bc84c8.jpg)
Some visual confirmation.

**Comment by Luth-RoR** [comment]
From https://github.com/WarEmu/WarBugs/issues/9393

>once last flag is opened to capture,
after that point you can capture it anytime, no matter flag sequence.
so it's possible that 2 different flags are on timer by each realm.
for example, in Gromril Crossing
Pilo O' Warstuff flag is on timer by Destruction
Order capture Da Base Camp flag ( it was opened before )
after both timers up one flag disappear with
[] says: IndexOutOfRangeException was thrown from GivePoint. This object will be destroyed.

**Comment by Natherul** [comment]
should be fixed as of today
