### ISSUE TITLE
Tomb of Deathsword bug

### ISSUE THREAD

**Issue by ursvamp** [WarEmu/WarBugs#5812]
mobs in Tomb of Deathsword PQ in praag isnt respawning

and loot bags cant be opened. I dont know if are they all but the ones that came in mail cant be open.

**Comment by Lheana** [comment]
NPCs now respawn.
Concerning bags in mail, I don't think it is completely fixed. So I advice to take the bag directly from the golden chest, or take it from mail asap to be sure you can open it and have several choices inside it.
