### ISSUE TITLE
Karak Karag guards bug

### ISSUE THREAD

**Issue by Vandorkholme** [WarEmu/WarBugs#5819]
Upon killing the guards inside they say: Nullreference exception was thrown. This object will be destroyed.

http://i.imgur.com/m3FyLUJ.jpg

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
