### ISSUE TITLE
Moving turrets

### ISSUE THREAD

**Issue by ellionkeman** [WarEmu/WarBugs#5821]
When my turret is up it's moving along with me wherever I go. 

![broliya_042](https://cloud.githubusercontent.com/assets/18136746/15153532/3d8fda7c-16e2-11e6-9f00-7cec2dafc971.jpg)
![broliya_043](https://cloud.githubusercontent.com/assets/18136746/15153534/3d91b86a-16e2-11e6-8fc1-c44aeb6c2def.jpg)
![broliya_044](https://cloud.githubusercontent.com/assets/18136746/15153535/3d933e1a-16e2-11e6-8985-a5c41e99ad28.jpg)
![broliya_045](https://cloud.githubusercontent.com/assets/18136746/15153533/3d9022e8-16e2-11e6-9411-7cf94643f719.jpg)

**Comment by Evildoor** [comment]
#5463
