### ISSUE TITLE
[Quest] Like Clockwork: invalid creature

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#5824]
This quest in IC has an invalid creature as the target, with a note saying to report it.
![forkrul_006](https://cloud.githubusercontent.com/assets/1183293/15155014/e48b12ee-16e0-11e6-9634-8b14d47b6fc7.jpg)

**Comment by Evildoor** [comment]
Hmmm, it should have been deactivated, #2267.

**Comment by Ryanfawkez** [comment]
All, if not most rank 40 flagged quests are currently obtainable.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
