### ISSUE TITLE
Quest Chaos chp 20 "Glories Past And Present"

### ISSUE THREAD

**Issue by Ziggesmuts** [WarEmu/WarBugs#5825]
Quest Says: Kill Caretaker Fildon but he is blue and cant be killed

**Comment by Mazadun** [comment]
![war 10-05-2016 20-55-32-120](https://cloud.githubusercontent.com/assets/15877842/15164163/b57350a4-1715-11e6-91e5-fc29509850a1.png)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
