### ISSUE TITLE
Elves distorted faces

### ISSUE THREAD

**Issue by Shangri-lah** [WarEmu/WarBugs#5826]
Hello, some high elves (and maybe dark elves) faces are distorted in game, and look very very ugly and non esthetical.

![soliness_002](https://cloud.githubusercontent.com/assets/19257358/15155723/190b8fb4-16e4-11e6-8181-b05db817819f.jpg)

![soliness_001](https://cloud.githubusercontent.com/assets/19257358/15155736/234197b2-16e4-11e6-857f-8eefbbe75893.jpg)

**Comment by Evildoor** [comment]
Client related issue, we can't do anything.
