### ISSUE TITLE
New t4 sc Tome/Chalice regen

### ISSUE THREAD

**Issue by Mortkin** [WarEmu/WarBugs#5827]
The new t4 sc Tome/Chalice is only +6 RF/SE.

http://i.imgur.com/2XYvm6U.png

**Comment by Morksezstop** [comment]
it is suppose to be that way. RF/SE regen depends of rarity of the weapon not from the level
blue + 6, purple +8, orange + 10, no matter if the orange item level is 1 or +50

**Comment by Evildoor** [comment]
#5752 will be used for resolving this issue, since WP and DoK have the same problems.
