### ISSUE TITLE
Influence rewards ( dwarf t2) problem

### ISSUE THREAD

**Issue by Furrikson** [WarEmu/WarBugs#5829]
Cant take rewards from Rally master. Got 4401 inf atm. but there is info that i need get more influence to take first reward

**Comment by NorKalli** [comment]
Guessing this is long since fixed, however I need to know command to manually add influence so I can test

**Comment by Quincent87** [comment]
I believe the problem still persists. See the screenshot below that I took just now:

![geraldan_000](https://user-images.githubusercontent.com/41511871/43035765-66209cde-8cf5-11e8-858e-ff1077e5db22.jpg)

I have full influence for the zone as you can see, but the Rally Master's rewards are blank.

**Comment by wargrimnir** [comment]
This is a similar issue to T4 zones. There's only one valid Rallymaster to receive rewards from per influence bar . In split zones like BV/MM and Badlands/BFP there's a rallymaster at each warcamp. Only one of the two will give rewards. We've provided a workaround for this in Emp/Chaos in T4 by copying the working rallymaster to each camp, and sort of hiding the non-working Rallymaster in a tent out of the way.

**Comment by Lheana** [comment]
#10992

**Comment by Quincent87** [comment]
That certainly makes a lot of sense. I used the correct Rallymaster to pick up the rewards, so it all works.

**Comment by sioding** [comment]
Fixed with patch from 30.03.2019
