### ISSUE TITLE
Terrible Embrace

### ISSUE THREAD

**Issue by Chummi** [WarEmu/WarBugs#5832]
ehm it always breaks when moving and it feels like a 30f pull it got totally gimped with the latest change while it worked before...

**Comment by taccr** [comment]
Looks like last patch made this ability not being able to cast on the move. Definitely a bug.

**Comment by Troelsnap** [comment]
created another bug report with an actual vid of how it worked on live. 
#5835

**Comment by Evildoor** [comment]
Next time use the same report to post video.
