### ISSUE TITLE
[Shaman] Aint done yet tactic

### ISSUE THREAD

**Issue by Grywwy** [WarEmu/WarBugs#5833]
![grywwy_042](https://cloud.githubusercontent.com/assets/13614929/15161617/286f04de-16ff-11e6-80c9-5dfbb264e309.jpg)

ALL healing abilities get buffed by 40% even if the targed is at full health!
Tactics slotted while testing this: Extra Special Mushroomz, RUN AWAY!, Restorative Burst

Gamebreaking bug? :P

**Comment by Morksezstop** [comment]
sounds like balance change even if unintended :P

**Comment by Grywwy** [comment]
Thats fine with me haha :P
