### ISSUE TITLE
Marauder pull interrupted by moving

### ISSUE THREAD

**Issue by Troelsnap** [WarEmu/WarBugs#5835]
This ability were working yesterday the 09.05.2015 whilst running and pulling - which it did on live:

https://www.youtube.com/watch?v=adZUlCMLpNE

40 secs in the video or so, you see it was like that on live.

**Comment by Chummi** [comment]
it worked perfect until today

**Comment by Kallahh** [comment]
Just the first 5 seconds

[https://www.youtube.com/watch?v=jINtZ9XLpew](url)

**Comment by Troelsnap** [comment]
it's broken again.

**Comment by Evildoor** [comment]
Should be fixed.
