### ISSUE TITLE
Serpent's Passage salvage while mounted.

### ISSUE THREAD

**Issue by Lileldys** [WarEmu/WarBugs#5839]
Able to take the part while mounted, and move with it while mounted. On live it forced you unable to use your mount with the part.

**Comment by Evildoor** [comment]
Changelog 19th May, 2016
[Scenarios]
Serpent's Passage
- Salvage drop will now award 75 points.
- Salvage carrier can no longer be mounted or stealthed.

**Comment by gittoaster** [comment]
You can still run with the part, you don't appear mounted, but gain the speed buff.

**Comment by Evildoor** [comment]
#6229
