### ISSUE TITLE
[Keeps] Null Reference Exceptions

### ISSUE THREAD

**Issue by Halhammer** [WarEmu/WarBugs#5841]
Seen some null reference exceptions bein thrown when attackin keep doors or keep lord, effectively buggin them out. Mainly in Emp/Chaos pairings. Pretty much like back in T2.

**Comment by Evildoor** [comment]
#5819 may be related.

**Comment by Luross** [comment]
Same thing happened this morning with Covenant of Flame outter door in Dragonwake when the door was about 20% life. The door said "Nullreference exception was thrown. This object will be destroyed." and then becam untargetable until the keep defense reset happened. Prevented us from getting a sweet Seal of Domination tho :'(.

**Comment by Blubberino** [comment]
Happens also in praag today at 60% or so

**Comment by ChronoVarience** [comment]
Don't know if this should be on another ticket or not; let me know. This same thing happened this evening when a ram was damaged at Drakebreakers Keep.

Video link:  http://plays.tv/video/5743ebf9562b63e27d/drakebreakers-siege-ram-throws-null-reference

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by ChronoVarience** [comment]
As far as I know, this has been fixed(is why video was pulled); I for one have not encountered this for some time now.

**Comment by sioding** [comment]
Thanks for the quick answer. Will close this now.
