### ISSUE TITLE
Repeating interaction over a single quest item

### ISSUE THREAD

**Issue by Milord9** [WarEmu/WarBugs#5843]
Everytime we have a quest asking to interact with several different items/NPC (to collect flowers, to free prisoners, etc...) it is possible to just find a single of it and to repeateadly right-click to complete the quest. I don't know if it's the staff will but in doubt I report it.

![arenia_001](https://cloud.githubusercontent.com/assets/17692456/15167867/a51ea980-172c-11e6-8ccd-a562592752ce.jpg)

**Comment by Evildoor** [comment]
#424
