### ISSUE TITLE
the very slow Shadow Warrior poisoned arrow

### ISSUE THREAD

**Issue by Milord9** [WarEmu/WarBugs#5844]
Sometimes when using the Shadow warrior poisoned arrow, the shot starts, then the arrow just stops in the air and very slowly moves to the target. If the target dies before the arrow aims it (wich often happens) the shot will continue to stay still in the air.

![arenia_003](https://cloud.githubusercontent.com/assets/17692456/15167961/57545622-172d-11e6-9715-b555c44d382d.jpg)

**Comment by Evildoor** [comment]
#4198
