### ISSUE TITLE
Undefined and broken portal in Nordland 

### ISSUE THREAD

**Issue by Milord9** [WarEmu/WarBugs#5845]
North-East of the Order warcamp in Nordland, at the crossing of Order's and Destruction's roads to Norsca, there is a portal graphically up but unusable.

![arhalian_004](https://cloud.githubusercontent.com/assets/17692456/15168036/f2de2adc-172d-11e6-9b97-b6bf6b7cf188.jpg)

![arhalian_005](https://cloud.githubusercontent.com/assets/17692456/15168040/f9ef3636-172d-11e6-92de-043c14673f6f.jpg)

**Comment by Morksezstop** [comment]
hunters vale afaik
