### ISSUE TITLE
Impossible to use the portal from Saphery to Eataine

### ISSUE THREAD

**Issue by Milord9** [WarEmu/WarBugs#5846]
Even if the re is no problem to travel to Eataine by dwarf transports, the portal from T3 Saphery to T4 Eataine seems to be bugged.

![lothern_002](https://cloud.githubusercontent.com/assets/17692456/15168074/5ec8b5d2-172e-11e6-8716-3174d5337fae.jpg)

![lothern_004](https://cloud.githubusercontent.com/assets/17692456/15168077/6215ada8-172e-11e6-8807-43bca0470a7f.jpg)

**Comment by saupreusse** [comment]
#5861 same problem here, but I still cant replicate it. It works for me...

**Comment by Razielhell** [comment]
Fixed in next.
