### ISSUE TITLE
Goblin's warmachines are alive, alive !

### ISSUE THREAD

**Issue by Milord9** [WarEmu/WarBugs#5847]
In Saphery, at the city besieged by goblins there are some warmachines having the same bug than the elven ones : they assault us if attacked ; When they come to 0hp, they stop attacking and remain still before disappearing.

![lothern_025](https://cloud.githubusercontent.com/assets/17692456/15168130/e426e532-172e-11e6-99e0-68975bd60a88.jpg)

**Comment by Ryanfawkez** [comment]
NPCs cannot be made permanently invincible yet.
