### ISSUE TITLE
Impossible to accept a scenario after being out of combat

### ISSUE THREAD

**Issue by Milord9** [WarEmu/WarBugs#5848]
Of course we can't accept a scenario while we are in combat, but sometimes (I don't know what circumstances change it) even after a combat, I mean after having regen all the HP and being really out of taunt and danger, the "yes I'm ready now" buton remains grey ; If I try to delay it ("yes give me a minute") the new "accept" button will be grey as well.

![lothern_026](https://cloud.githubusercontent.com/assets/17692456/15168197/7bc11ebc-172f-11e6-9c52-137acf35afcf.jpg)

**Comment by Vancerus** [comment]
write ".unlock" or ".u" in chat

**Comment by Evildoor** [comment]
Vancerus is correct.
