### ISSUE TITLE
Lots of guildleaders in guild :)

### ISSUE THREAD

**Issue by tomaslumba** [WarEmu/WarBugs#5852]
This morning when i log in we had lots of guildleaders in guild. This is prolly because of the new "change inactive guildleader feature". Our ordinary leader hasn't been on i a while - i'm all for democracy but this is to much :)

Kind regards!
![kharlbartos_004](https://cloud.githubusercontent.com/assets/17112647/15171921/8a2f94e2-1752-11e6-8a99-122486aa8a2b.jpg)

**Comment by Evildoor** [comment]
#5514
