### ISSUE TITLE
tome: wight unlock

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#5853]
killing a "bleakwind wight" or "brimdall yggdreidar", both in chaos wastes loc 7k,2k , does not unlock the related bestiary entry

**Comment by Meralors** [comment]
They count as  Undead>Skeleton  kill. What unlock should they be?

**Comment by zak68** [comment]
bestiary->undead->wight
assuming that following link reports the truth
http://warhammeronline.wikia.com/wiki/Wight

**Comment by Meralors** [comment]
Sound just right. Changed them to Wright sub-category, should be live next patch.

(you can check http://war.mmodb.com/ )

**Comment by zak68** [comment]
thank you
