### ISSUE TITLE
lvl38 blue Str Pots give wrong buff

### ISSUE THREAD

**Issue by Vancerus** [WarEmu/WarBugs#5855]
If we use the "Potent Lasting Potion of Power" which should give 100 Str a wrong potbuff is applied.

Here you see the pot i used: 
![vancero_188](https://cloud.githubusercontent.com/assets/14907399/15177226/4dcff89e-176f-11e6-9c2d-ab7181ac96a0.jpg)

and here the low lvl35 80 Str buff is applied:
![vancero_189](https://cloud.githubusercontent.com/assets/14907399/15177238/59bc80dc-176f-11e6-971a-b4afc0006b26.jpg)

the same problem occurs with the blue crit of the lvl 35 which should give 90 Str.

**Comment by Evildoor** [comment]
#5782
