### ISSUE TITLE
Soldier medallions

### ISSUE THREAD

**Issue by Siro60** [WarEmu/WarBugs#5856]
I tried to transform my officers medallion into soldier medallions to complete my devastator gear.
Lost a 8 officers medallion but got no soldier medaillon.

Could you please correct this and reward me back the 8 lost officer medallions.

**Comment by Evildoor** [comment]
Stupid question: have you checked both currency and normal bags?

**Comment by Siro60** [comment]
yes, after a second check , the boxes were in. Maybe a lag or whatever. Thanks for care.
