### ISSUE TITLE
Game DCing to char select and quests completely wiped

### ISSUE THREAD

**Issue by Sersaypygan** [WarEmu/WarBugs#5857]
This has started happening alot in the past day for me, where I will be in a party queing for scenarios, and a scenario pops. I hit accept. The screen freezes, the screen goes white, with (Not responding) on the window border, and sometimes (About every other time so far) I get booted to character select.

I also noticed between this that my quests where completely wiped, and quests i KNOW i completed where able to be done again. Later on I attempt more scenario group ques, get a pop, crash again, and notice the 3 quests i'd picked up had been wiped when i get back on.

So apparintly, not only am I crashing constantly on scenario group ques, its wiping my quests every time it dose, too.

**Comment by Evildoor** [comment]
Please, post this in #2001.
