### ISSUE TITLE
Incorrect RVR area: Black Fire Pass and Badlands

### ISSUE THREAD

**Issue by bwdaWAR** [WarEmu/WarBugs#5859]
It seems some areas of the world that were previously not part of the lakes are now. These include: Chaos chapter 3 and 4 and the Destruction warcamp in Nordland (including the whole border between Nordland and Norsca), Greenskin chapter 11 and 12 in BFP and Badlands. There are probably more areas that'll count as part of the lake, but that's what I found so far. I was in the Greenskin chapter 11 camp a few days before the T4 patch and I didn't get flagged then like I do now, so this most likely came with the T4 patch.

**Comment by Evildoor** [comment]
Nordland: #5458

**Comment by bwdaWAR** [comment]
You mean this? https://github.com/WarEmu/WarBugs/issues/5468

**Comment by Evildoor** [comment]
Yes. Sorry, typo.

**Comment by saupreusse** [comment]
ye. grimbeard station and da hills were marked as RVR lakes. Fixed now.
