### ISSUE TITLE
npc: de chapter 16

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#5860]
"rally" is listed but npc's not present

**Comment by Evildoor** [comment]
Are there any NPCs without name and title?

**Comment by zak68** [comment]
yes: quest giver velathor lashstrider hasn't its name displayed

**Comment by Evildoor** [comment]
Only one, and he's not the rally master? Ok then...

**Comment by Shadowgurke** [comment]
![lyrai_010](https://cloud.githubusercontent.com/assets/1018113/15180849/33bf2834-1784-11e6-9bae-246f07bcd107.jpg)

works fine for me

**Comment by Evildoor** [comment]
So he is the rally master after all? #4798 then.
