### ISSUE TITLE
world: portal from saphery to caledor

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#5861]
not functioning,it says "region currently not available. please try again later"

**Comment by saupreusse** [comment]
can not replicate, works fine for me.

**Comment by saupreusse** [comment]
seems like its only working for staff members... someone will have a look at it.

**Comment by zak68** [comment]
![gabri_040](https://cloud.githubusercontent.com/assets/17765890/15185563/11ba3d76-179a-11e6-8107-29d849ad1de0.jpg)

**Comment by Razielhell** [comment]
Fixed in next Patch.
