### ISSUE TITLE
Quest "Wherever They Are Found", invalid NPC

### ISSUE THREAD

**Issue by doomy330** [WarEmu/WarBugs#5864]
Quest in High Pass, Order Chapter 11, Roland Gotthardt.
Invalid NPC quest ID 775, ObjId=15919
![13214697_1276041145757215_1224092785_o](https://cloud.githubusercontent.com/assets/19310032/15187752/0cdf8e9e-17ab-11e6-90fc-fa764676427e.jpg)

**Comment by Evildoor** [comment]
#4169
