### ISSUE TITLE
I cant gain any Renown Ranks anymore.

### ISSUE THREAD

**Issue by geezereur** [WarEmu/WarBugs#5865]
My Rank 14  RR 14  Witch Elf  Nimbul    is stuck att 100%,  I cant gain any more Renown.
I have been killing people in RVR and Also  Joining Scenarios + Keep takeover nothing works.

**Comment by Evildoor** [comment]
Changes to Leveling:
- Renown Rank is now capped to your current Career Rank. You will no longer gain renown if your renown rank is greater than your career rank, until you reach level 40.
