### ISSUE TITLE
quest scarlet tide 

### ISSUE THREAD

**Issue by ellionkeman** [WarEmu/WarBugs#5867]
before t4 update I got scarlet tide quest. Now the npc who gave me the quest hasn't got on though i finished it and I can't finish it
![ulallas_002](https://cloud.githubusercontent.com/assets/18136746/15191232/720a8e84-17bc-11e6-84d3-981bf6ee4338.jpg)

**Comment by Evildoor** [comment]
Can you actually read the T4 patchnotes, please?
- The number of kill quests in each pairing has been reduced to 1. The overall kill quest rewards have been increased, and will now be restricted to the pairing in which they are assigned.
