### ISSUE TITLE
[Quest Reward][Faith in Madness][Slayer] 2H Red Carnage has speed of 1H

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#5868]
At least I think 2.7 is too fast for 2H.

![red_carnage](https://cloud.githubusercontent.com/assets/16117730/15191417/e6ea17e0-17b4-11e6-957c-0ac4b0b373ee.png)

**Comment by Torquemadra** [comment]
Slayer specific clone of a historical 2 hander (Carnage, dwarf) and has historical values. Not a bug but an opinion.
