### ISSUE TITLE
helicopter, teleport in zones and animation bug

### ISSUE THREAD

**Issue by Wagrash** [WarEmu/WarBugs#5872]
Today my helicopter bugged - it always active, even I use skills or something else. It was unbugged only after Im crashed.

**Comment by Wagrash** [comment]
+ I was teleported to times into high pass when trying to travel into death peak

**Comment by Wagrash** [comment]
![farin_000](https://cloud.githubusercontent.com/assets/16164209/15193948/fe3cd586-17c8-11e6-8ddb-736f2936c4ba.jpg)
![farin_001](https://cloud.githubusercontent.com/assets/16164209/15193947/fe396e46-17c8-11e6-980d-fb8e752188ca.jpg)
![farin_002](https://cloud.githubusercontent.com/assets/16164209/15193949/fe3d10c8-17c8-11e6-8c14-13432cdf2860.jpg)
And my turret always "rides" with me

**Comment by Evildoor** [comment]
1) One report per problem.
2) Turret: #5463.
3) Were you actually able to attack and kill someone with skills while remaining on the mount? Or you used some aoe at empty space and 5 seconds later your game crashed?

**Comment by Wagrash** [comment]
after one of deaths near order warcamp I sit up on my mount and while remaining on the mount I used my aoe skills, trowed some grenades, deploy my turret. While I get dmg from destro side I never droped from mount. While I fly to another zone my mount was bugged. So I fly to my group members - on map they was on death peak. While I trying to move in that zone my client crashed and after relogging I was be in high pass without bug of my mount. But after that I try to fly into death peak one more time and game not crashed just teleported into high pass.
Sorry for my bad english.
