### ISSUE TITLE
Jagged Edge tactic does not trigger when dot deals critical hit

### ISSUE THREAD

**Issue by DaWAAAGH** [WarEmu/WarBugs#5874]
![grufrip_004](https://cloud.githubusercontent.com/assets/16031857/15195337/157d507a-17d0-11e6-825c-3b14e4c7a36d.jpg)

Tested this with "Yer all bleedin' now" and it didn't crit first but few seconds later it did but jagged edge didn't trigger. Tactic clearly says "Any time you critically hit an enemy they will begin to bleed..."

**Comment by ozarmidrashim** [comment]
Any ability that triggers on damage or critical hit is configured to trigger on direct damage only, and this will not be changed without supplied proof.

**Comment by Evildoor** [comment]
Closing per Aza's explanation.
