### ISSUE TITLE
New Keep/PQ loot contribution system

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#5878]
Looks like it completely broke now.
![paterellas_037](https://cloud.githubusercontent.com/assets/16864486/15199166/db985098-17e4-11e6-9193-d667d5cd3029.jpg)
![paterellas_038](https://cloud.githubusercontent.com/assets/16864486/15199167/dbc51402-17e4-11e6-8aeb-0e5775f585b9.jpg)

**Comment by Torquemadra** [comment]
its a display issue, people are able to get the bags rvr and pq

**Comment by Soulwhisper** [comment]
If fixed with latest server restart then we can close it?

**Comment by Soulwhisper** [comment]
Not fixed with today's patch. Still 0000.

**Comment by Soulwhisper** [comment]
Still bugged after the patch.

**Comment by genisaurus** [comment]
Should have been fixed since

**Comment by Soulwhisper** [comment]
This works fine on T3.

**Comment by Soulwhisper** [comment]
Covenant of Flame Keep is bugged.
![paterellas_042](https://cloud.githubusercontent.com/assets/16864486/15819150/265b0e0e-2bea-11e6-982f-56ec2ee384b5.jpg)

**Comment by Soulwhisper** [comment]
Cascades of Thunder
![pokopikos_000](https://cloud.githubusercontent.com/assets/16864486/15820733/f3af4038-2bf3-11e6-8761-846b06a27e78.jpg)

**Comment by Soulwhisper** [comment]
Anyone can test this one and close it if it works?
