### ISSUE TITLE
Gold Bags from keeps disappers from Bank vaults

### ISSUE THREAD

**Issue by nohh** [WarEmu/WarBugs#5879]
I have store 2 bags in bank vault and now i have noticed that they disappears.

**Comment by Evildoor** [comment]
Probably collateral damage of Ruin wipe. BTW, they would have been bugged anyway (per explanation in #5768), so i recommend opening bags ASAP.

**Comment by nohh** [comment]
Ok, looks like keeps bags was wiped with ruins set pq bags.
Should i close this bug by myself?
