### ISSUE TITLE
You Really Got Nothin [Shaman tactic} da Green spec

### ISSUE THREAD

**Issue by footpatrol2** [WarEmu/WarBugs#5882]
I Spec'd into this and the tactic isn't working in reducing the cooldown on Don' Feel nuthin absorb.

**Comment by Evildoor** [comment]
Where exactly this tactic says anything about absorb? The tooltip states that it should reduce the cooldown of "You Got Nuthin", which is silence.

**Comment by footpatrol2** [comment]
I am wrong. So so so so sorry. Please delete this or ignore.
