### ISSUE TITLE
Crushing The Reavers Quest Broken

### ISSUE THREAD

**Issue by sinderhella** [WarEmu/WarBugs#5883]
I have killed multiple watchers of tor elyr and they are not counting towards the kill count.  All riders of tor elyr have counted fine and I am killing the mobs in the same area.

**Comment by sinderhella** [comment]
![sinderhella_004](https://cloud.githubusercontent.com/assets/19142979/15202174/d01f730a-17ac-11e6-88c5-fbc65518fea5.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
