### ISSUE TITLE
Renown gear - can't be equipped

### ISSUE THREAD

**Issue by ellionkeman** [WarEmu/WarBugs#5885]
T1 renown gear bought from renown quartermaster can't be equipped. I press on it, try to drag and drop to a correct slot - nothing happens. No messages in chat as well
![ulallas_004](https://cloud.githubusercontent.com/assets/18136746/15204132/d51de380-1812-11e6-8062-354357fd5a05.jpg)
![ulallas_005](https://cloud.githubusercontent.com/assets/18136746/15204133/d5210d12-1812-11e6-872b-9612b6aa477b.jpg)
![ulallas_006](https://cloud.githubusercontent.com/assets/18136746/15204131/d51bc1a4-1812-11e6-8b31-8aa475791471.jpg)

**Comment by ellionkeman** [comment]
the gear that has +tough + wound attributes is ok and can be equipped

**Comment by Evildoor** [comment]
#5693
