### ISSUE TITLE
Chain quest annihilation in reikland broken.

### ISSUE THREAD

**Issue by Mordrahar** [WarEmu/WarBugs#5886]
I have the end of the quest completed, and everytime i try to pick up the weapon, it says cannot salvage, backpack overflowing, and that i need to reorganize my backpack. However my backpack is open, there is room, I even removed items from my crafting/salvage slot.
![theages_001](https://cloud.githubusercontent.com/assets/19319691/15204706/f1e7b730-17d5-11e6-8695-807061b2ae2f.jpg) 
![theages_000](https://cloud.githubusercontent.com/assets/19319691/15204710/f8a28032-17d5-11e6-8339-2bfa9bea212b.jpg)

**Comment by Evildoor** [comment]
Individual problem with unknown cause which has no solution so far, apart from server restart (see #2031).

**Comment by Mordrahar** [comment]
any idea when the next server restart might happen?

**Comment by Evildoor** [comment]
No.
