### ISSUE TITLE
Empire chapter 19 influence reward

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#5890]
Rewards shown in ToK looks fine for Kotbs but while at rally master there's an additional reward (book) for wp to chose from
![sheyr_007](https://cloud.githubusercontent.com/assets/18032193/15205735/2984a812-181a-11e6-8c68-19aeba11f8a8.jpg)
![sheyr_008](https://cloud.githubusercontent.com/assets/18032193/15205734/2982d5d2-181a-11e6-9580-d0ab315d1cc7.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
