### ISSUE TITLE
Guild roster reset and random guild leader assignment.

### ISSUE THREAD

**Issue by Partizan-Rusi** [WarEmu/WarBugs#5895]
I have problem with guild roster. It was reset(to fix previous bug) and guild leader was given to random dude, who is newbie 15 lvl joined few weeks ago -  http://i.imgur.com/Fgk7vXy.jpg
Obviously I need guild leadership restored to my character - Partizan, who was original founder of the guild and g.l. all this time - http://i.imgur.com/Q2IYdT7.jpg

**Comment by Evildoor** [comment]
Wrong place. Ask a GM or support forums.

**Comment by Partizan-Rusi** [comment]
GM send me here.

**Comment by Evildoor** [comment]
Ok then, i'll have a talk with the team and we'll see who should be dealing with such kind of problems.
Note to self - bawl responsible GMs out for sending people with individual problems to bugtracker.

**Comment by Partizan-Rusi** [comment]
Well GM told me they can't deal with this kind of problems yet.

**Comment by Evildoor** [comment]
I was right. Problems like this belong to the Game Support forum section.
