### ISSUE TITLE
world: roadside memorial

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#5897]
in eataine loc26k,49k clicking on the "roadside memorial" makes you informed about the "repeater crossbow" lore.
![gabri_047](https://cloud.githubusercontent.com/assets/17765890/15209797/7466ec1e-1833-11e6-9aeb-e79830c534c3.jpg)

**Comment by Evildoor** [comment]
Is this wrong?

**Comment by zak68** [comment]
http://warhammeronline.wikia.com/wiki/Eataine/History_%26_Lore
no, sorry.
