### ISSUE TITLE
High elf chapter 22 quests bugged 

### ISSUE THREAD

**Issue by Hyronen** [WarEmu/WarBugs#5898]
![mcdonaldz_008](https://cloud.githubusercontent.com/assets/16591485/15209986/c017303e-183c-11e6-8e0f-232177eee7b9.jpg)
![mcdonaldz_009](https://cloud.githubusercontent.com/assets/16591485/15209989/c01be93a-183c-11e6-934a-f89aad4d291c.jpg)
![mcdonaldz_010](https://cloud.githubusercontent.com/assets/16591485/15209987/c017bc84-183c-11e6-9cb7-54ba9059baea.jpg)
![mcdonaldz_011](https://cloud.githubusercontent.com/assets/16591485/15209988/c017e718-183c-11e6-8a67-d8714abd0cf7.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
