### ISSUE TITLE
White Lion AI

### ISSUE THREAD

**Issue by Theseus2** [WarEmu/WarBugs#5899]
The Pet suddenly and most randomly runs off into nowwhere when you move around on the map and has to be summoned aggain, after the cooldown of 15 sec. 
And after a fight it often says at the scene of the last fight and has to be summend with heel to your new position.

**Comment by Evildoor** [comment]
#5714?

**Comment by Theseus2** [comment]
It is similar, but my petskills also vanish.

**Comment by Evildoor** [comment]
Only skills? Or the whole panel (including "Heel", "Attack", etc) vanishes and "Summon War Lion" skill goes on cd, as if the pet was killed?

**Comment by Theseus2** [comment]
The whole panel.

**Comment by Evildoor** [comment]
I see. Since it's still more or less the same problem (pets disappearing and wasting your time and cd to summon them) i'll rename #5714 and you can add your information to it if you want.
