### ISSUE TITLE
Mordekhain's report 2

### ISSUE THREAD

**Issue by Mordekhain** [WarEmu/WarBugs#590]
-1-
If you stay under or above player on SC in melee range you can attack him from behind textures.
-2-
If you stay close to enemy flag you can capture him from behind textures or brake his capture.
-3- 
Sometimes "Rend soul" animation get bugged. Ability go to countdown but she dont deal damage and heal.
-4-
When I cross the border of some location I get strike on me (no damage). That automatically dismount me. Sometimes I need use my mount twice to get mounted. Icon of mount fade out from bar after relogin .

**Comment by Evildoor** [comment]
Closing since all these issues were fixed. (Except for other form of 3 which sometimes occurs, but that's a different problem and it is not only RS-related)
