### ISSUE TITLE
Mara: Terrible Embrace 

### ISSUE THREAD

**Issue by Gidroplanchik** [WarEmu/WarBugs#5905]
All hi, today I have come into game, and have seen that Terrible Embrace works not correctly!
I can't attract on the run!
I have come on Youtube to be convinced how was on off WHO, and have found video with the proof of how has to work Embrace.
https://www.youtube.com/watch?v=atU27Sv5P_4
At 0:59 it is accurately visible how Mara attracts on the run!

**Comment by Evildoor** [comment]
#5835
