### ISSUE TITLE
Can`t use annihilator set, after restart server

### ISSUE THREAD

**Issue by ttorun** [WarEmu/WarBugs#5907]
Hi,sorry for may language!

After restart server, when bags with Ruin Gear were wiped, I cant find gold bag from keep`s lock.
Moreover, I cant equip my annihilator Tramplers.

May nickname in game, Yankay

**Comment by Evildoor** [comment]
1) One report per problem.
2) All bags were wiped. Even if they weren't wiped they would have been bugged.
3) Tested on dev, set my marauder to 40/37 like your one, equipped tramplers normally.

**Comment by ttorun** [comment]
Ok, my problem is... I cant equip my annihilator Tramplers.
Before restart, I could.

**Comment by Evildoor** [comment]
No clarification on this point, so i'm closing this. If this problem still persists then it's most likely individual problem which belongs to game support forums. Dunno, maybe these particular Tramplers got bugged for some reason.
