### ISSUE TITLE
Tier 2 - Light Empire Hellblaster, Light Empire Cannon not working

### ISSUE THREAD

**Issue by MrHurricane89** [WarEmu/WarBugs#5909]
The Light Empire Hellblaster, Light Empire Cannon siege defenses are not working properly.
Steps to reproduce:
1. Buy the items from your keep def vendor for 2g/piece.
2. Try to place them in your keep, on the ranged pad to the right of the main gate, on the bastion.
3. The siege is placed, but is unusable, one time it went down and attacked some Destro on its own, behaving like a regular mob.

**Comment by Evildoor** [comment]
#5715
