### ISSUE TITLE
Door of Praag Destro keep is bugged

### ISSUE THREAD

**Issue by Theseus2** [WarEmu/WarBugs#5911]
If we want to attack the keep door of the northern Garrison of Praag, we get: target is out of range. So we cant conquer it.

**Comment by noisestorm** [comment]
to add to this: Outergate is clickable where it is supposed to be, but its effective position is the one of the Inner gate. Meaning you target the outer gate, go into range of the inner gate(per lockpick for example) and then can attack it. Nonetheless its basically impossbile for order atm to flip Praag.

**Comment by Ryanfawkez** [comment]
Not my fault the fixes aren't being pushed in my absence! :palm_tree:
