### ISSUE TITLE
[Sorc] Ice Spikes issue

### ISSUE THREAD

**Issue by stillwaterww** [WarEmu/WarBugs#5912]
I've tested this a couple times but ice spikes dot effect is not applied to any t4 keep doors.
![iobel_003](https://cloud.githubusercontent.com/assets/19287032/15220110/a2864936-1866-11e6-8b65-9e2c27eb2602.jpg)
![iobel_004](https://cloud.githubusercontent.com/assets/19287032/15220120/a6476a64-1866-11e6-981f-94981d5461f0.jpg)
![iobel_005](https://cloud.githubusercontent.com/assets/19287032/15220127/aa55bf16-1866-11e6-8955-eea3cc6ae175.jpg)

**Comment by Evildoor** [comment]
I see lots of people attacking the door here. Need to be tested with just a few (i suspect it's #1469).

**Comment by stillwaterww** [comment]
Ill try testing this some more, also the screenshots is with me spamming ice spikes

**Comment by Evildoor** [comment]
No confirmation, closing.
