### ISSUE TITLE
All guild ranks reset -set to default rank- after Patch

### ISSUE THREAD

**Issue by Krumlok** [WarEmu/WarBugs#5917]
![guildbug](https://cloud.githubusercontent.com/assets/14275335/15223653/d830893e-1875-11e6-81a2-d9a2e5cc72e0.png)

As you can see, everyone is set to the default Rank (Rekroot) after the hotfix was applied. Yesterday I had Deathskul Boyz, Gudlistnas, etc, but today, it's all reset.

**Comment by Evildoor** [comment]
Wrong place. Forums, game support.
