### ISSUE TITLE
Backpack Items / Macros dropping from Action Bar

### ISSUE THREAD

**Issue by ShotsOnTarget** [WarEmu/WarBugs#592]
I've been specifically putting my Mount on action bar. Upon starting game, relogging, joining Sc, leaving Sc, or flying between zones the mount is no longer on my hotbar.

Same thing happens when trying to place a macro icon on the action bar (dragged from Macro menu).

Only tried this on Action Bars 1 & 2. Possibly same thing will happen with other backpack items (e.g. potions)

**Comment by Symex** [comment]
I can affirm this is still occuring. Have the Same Thing with Mount, Book of Binding and also sometimes with my Abilities, which often switch to Places they where in a older Setup of mine.

Often occurs when going through a Loading Screen such as joining a Scenario or using the Flight Master.

**Comment by Evildoor** [comment]
Items no longer disappear from action bars. Closing.
