### ISSUE TITLE
Serpent's Passage - Salvage awarding too little points

### ISSUE THREAD

**Issue by Pxl555** [WarEmu/WarBugs#5920]
In RoR the salvage rewards 35 points at this point. On live it used to be 75.

https://www.youtube.com/watch?v=Md2IB7lEkR8#t=09m02s

The video shows the cap in the middle announcement and you can see how much the points move.
I am not sure if this is an intentional change or not but as it is right now some games that are one-sided can feel very dragged out.

**Comment by Zealote** [comment]
Must've changed/been fixed since this report: it's now awarding 75 points.

**Comment by Luth-RoR** [comment]
Thx.
