### ISSUE TITLE
Jumping disrupts Marauder Pull

### ISSUE THREAD

**Issue by Vancerus** [WarEmu/WarBugs#5921]
Tested thoroughly now in SCs, Open and Duels.

If the enemy jumps EVERY Terrible Embrace (Marauder Pull) gets disrupted.

**Comment by Chummi** [comment]
same bug as the day before. breaks on movement .... :(

**Comment by Vancerus** [comment]
there is also an open thread about that Chummi, but this one is another issue.

**Comment by jonyjones** [comment]
lol Fix?
