### ISSUE TITLE
Shaman Ruin Hat

### ISSUE THREAD

**Issue by Grywwy** [WarEmu/WarBugs#5926]
The Shaman Hat from the Ruin PQ set has +11 Weapon Skill on it.
Was that put on there on purpose?

**Comment by Torquemadra** [comment]
Im sure it was at one point, changed it now

**Comment by stillwaterww** [comment]
Not only shaman gear has this, I've found that sorc/magus shoulders also have weaponskill and zealot headpiece has it aswell.

**Comment by Grywwy** [comment]
This can be closed (as far as the shaman hat goes)
Thx for the fix!

**Comment by Evildoor** [comment]
FYI - you can close your own tickets.
