### ISSUE TITLE
Potions - Shown value and their real value

### ISSUE THREAD

**Issue by myhra** [WarEmu/WarBugs#5927]
I noticed that the shown values on some buff and armor potions are higher than buffed value. 

The buffs for stats seems to be maxed at 80 points, even if you take the blue ones on level 35 and 38, which should buff 90 and 100 stat points.

Similar thing with the armor potions. The "potent lasting securing unguent", which shoul add 742 armor only adds 660.

**Comment by Ktaan** [comment]
Just wanted to add that lvl 38 blue armor pot which supposed to give 842 armor, gives 660 armor too

**Comment by NorKalli** [comment]
long ago fixed
