### ISSUE TITLE
T4 Lair Bosses

### ISSUE THREAD

**Issue by Kuroiwashi** [WarEmu/WarBugs#5929]
I went with my guild to try check out the new lair bosses, we tried Kaladrin Vally and Black Crag, in BC the door to Malachia Lair is targetable, so as the potion you need to use to open it, but they arent clickable.

The one in Kadrin Valley, Lair of the Fallen Slayer, there is a door, that cant be open.

I know T4 just came out, but are the Lair Bosses suppose to be bugged or not available till later?

**Comment by NorKalli** [comment]
lonnngggggg since fixed
