### ISSUE TITLE
Not aggro'ing mobs when mounted

### ISSUE THREAD

**Issue by ShotsOnTarget** [WarEmu/WarBugs#593]
Rode through large numbers of mobs (20+) whilst mounted. This was in Mnt. Bloodhorn. Squigs, Spiders, etc. Only aggro'd 1 Squig, who seemed bugged out and I couldn't fight and wouldn't follow me. This is repeatable.

Seen similar thing when using an ability to dismount (via AutoDismount addon) within melee range of a mob - the mob bugs out, Runs around a little sporadically but I cannot fight it (except for an occasional auto-attack), nor is it interested in fighting to me.

**Comment by Mordekhain** [comment]
Also cant speack with NPC when mounted.
