### ISSUE TITLE
Nordenwatch fortress flag bug (SC)

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#5930]
First side to cap doesn't have to care about fortress as it's not possible to cap it again by other side until the end
![sheyr_010](https://cloud.githubusercontent.com/assets/18032193/15232522/367bd40e-18a2-11e6-9fd1-a4034c17ed45.jpg)
![sheyr_011](https://cloud.githubusercontent.com/assets/18032193/15232523/367f1b50-18a2-11e6-8158-6216f931ecd0.jpg)

**Comment by fiazco** [comment]
More of a bug than abuse. I was in that SC, didnt even know about that.

**Comment by szejoza** [comment]
fixed ;p

2016-05-13 0:56 GMT+02:00 fiazco <notifications@github.com>:

**Comment by Vayra** [comment]
It happens intermittently, I've seen it happen on central flag in Reik Factory as well.

**Comment by Evildoor** [comment]
#3787
