### ISSUE TITLE
WP bugged items (Tome of Repose, Annihilator Spatterguards)

### ISSUE THREAD

**Issue by Buschfrau1** [WarEmu/WarBugs#5932]
Tome of Repose:
atm: 36 wounds; 36 toug;: 106 corp resis; 106 ele resis
should be: 36 wounds; 36 tough; 106 corp resis; 106 ele resis + 106 spirit resis and armor procc ~900 i think.

Annihilator Spatterguards:
atm: 25 str; 13 wp; 10 tough; 2% dodge
should be: 25 wp; 10 tough; 13 ini; 2% dodge
(they got the stats of old annihilator forgot to give them the new stats)

Greetings Buschfrau

**Comment by Ryanfawkez** [comment]
http://www.arsenalofwar.com/items/Order/Tome%20of%20Repose - wrong on the extra resist. The armor proc counts for 700 over 6 seconds. Spatterguards fixed in next patch.

**Comment by Buschfrau1** [comment]
why is the blue one http://www.arsenalofwar.com/items/Order/Reikwatch%20Tome 3 resis then :/ ?

**Comment by Torquemadra** [comment]
Procs are not being allocated to influence weapons at this time.
