### ISSUE TITLE
Zaki Thunderbrow in Black Crag Quest Issue

### ISSUE THREAD

**Issue by Geizty** [WarEmu/WarBugs#5933]
It appears the entire questline The Grudges of Karak Drazh is available from Zaki Thunderbrow when talking to him.  There are 7 The Grudges of Karak Drazh available.

This is Dwarf Chapter 21.

Screenshot attached.

![image](https://cloud.githubusercontent.com/assets/19244064/15235711/c6a38d04-188b-11e6-96eb-29687c6f70ef.png)

**Comment by NorKalli** [comment]
long since fixed
