### ISSUE TITLE
Potent Lasting Potion of Force

### ISSUE THREAD

**Issue by mursie** [WarEmu/WarBugs#5934]
Potion is a blue crit of the green version.  Tooltip on the potion reads that it adds 90 strength for 60 minutes.  Pot is actually only giving 80 strength and the buff on your portrait says only 80 strength.

ETA - its all pots with values above 80... they are being capped at 80

**Comment by milosxe** [comment]
Looks like the stat pots are capped at 80 for some reason. Didn't matter to me if I used 90 or 100 int pot, cause I got only 80 out of it.

**Comment by Evildoor** [comment]
#5927
