### ISSUE TITLE
Swordmaster gear in the first warcamp

### ISSUE THREAD

**Issue by Carebucket** [WarEmu/WarBugs#5939]
Some of the swordmaster gear in the first warcamp is medium armor, but you can only use heavy so it makes it useless.
![vaelor_004](https://cloud.githubusercontent.com/assets/19345079/15246363/f7f48b40-1914-11e6-8e3d-f038194b4db3.jpg)
![vaelor_000](https://cloud.githubusercontent.com/assets/19345079/15246368/021d0f52-1915-11e6-989d-676415fd2e69.jpg)

**Comment by Evildoor** [comment]
#5693
