### ISSUE TITLE
[Ability][White Lion] Coordinated Strike damage is not properly calculated.

### ISSUE THREAD

**Issue by sebid** [WarEmu/WarBugs#594]
**Ability Name:** Coordinated Strike
**Link:** http://warhammeronline.wikia.com/wiki/Coordinated_Strike

I have no idea what formula is used for the damage. Some websites use a damage ratio of 1:2 for the pet, others use 1:1, others 3:1. The only part that I've seen is that they all state 25 yards in the tooltips, while on RoR, the tooltip states 35 yards. Hotfix? Who knows. 

One target:
**- If the pet is not summoned at all** *{1}*
Expected Behaviour: Skill should do one "piece" of damage, the initial " You strike your target for X damage"
Observed Behaviour: Skill hits 5 times with the same damage.

**- If the pet is summoned and out of range**  *{2}*
Expected Behaviour: Skill should do one "piece" of damage, the initial " You strike your target for X damage". Pet is outside 35 yards, cannot hit its target. Pet does not have a target and you are not in the range, you don't hit again. Pet is not in range to your taget, it doesn't hit again.
Observed Behaviour: Skill hits 2 times with the same damage.

**- If the pet is summoned and in range, fighting the same target**
Expected Behaviour: You strike the target for X damage. Pet strikes the target for Y damage. You are in range with your pet's target, You strike again for X damage. Pet is in range with your target, it strikes again for Y damage.
Observed Behaviour: Sometimes it works, sometimes not.
- If opening combat by using a Coordinated Strike, the pet will not do it's damage portion, only the player will hit twice.  *{3}*
- If used during combat, the skill will properly work, the player hitting twice and the player's pet hitting twice.
- If the summoned pet is dead, and outside of range, the player hits twice. It should only hit once, as the pet is outside the range of the player.  *{4}*

Two targets: 
**- If the pet is summoned and in range, fighting a different target**
Expected Behaviour: You hit your target for X damage. Pet hits its target for Y damage. You hit your pet's target for X damage. Pet hits your target for Y damage.
Observed Behaviour: Works properly. Your target gets hit once by you once by your pet. Your pet's target gets hit by you and once by your pet.

**- If the pet is summoned and outside of range, fighting a different target**
Expected Behaviour: You hit your target for X damage. Pet hits its target for Y damage. 
Observed Behaviour: Works properly. Your target gets hit for X damage. Pet's target gets hit for Y damage. No secondary damage due to being outside of range.

A different issue altogether is probably behind the bug when the skill is used but does not do any damage at all/showing in the log.
Video:
1 - http://youtu.be/zleCdbN1pf8
2 - http://youtu.be/Fz1w8VQiF3Q
3 - http://youtu.be/LCdWUawlVHk
4 - http://youtu.be/ebRQevoHtsY

**Comment by andytomlins** [comment]
The issue is down to the death state of the pet not being set properly. The devs know of the issue. Also the range was upped to 35ft in live a few years back.

**Comment by sebid** [comment]
Might be, it's related to issue {4}. There is still {1},{2},{3} to be solved.
