### ISSUE TITLE
T4 Influence rewards in ToK

### ISSUE THREAD

**Issue by stillwaterww** [WarEmu/WarBugs#5941]
After picking my inf reward the item chose has dissappeared from the ToK entry.
![iobel_006](https://cloud.githubusercontent.com/assets/19287032/15247235/181f4c18-1913-11e6-9f19-92d4ac669c36.jpg)
![iobel_007](https://cloud.githubusercontent.com/assets/19287032/15247240/1c215f04-1913-11e6-8a5a-9db0e459c4cf.jpg)

**Comment by Luth-RoR** [comment]
According to the DB-team a client side issue. Can't be fixed atm.
