### ISSUE TITLE
Morale 3 Penance and Universal Confusion doesnt working

### ISSUE THREAD

**Issue by Ktaan** [WarEmu/WarBugs#5947]
This ability fires off really wierdly. It doesnt work for sure when you have your defensive target selected.  Sometimes it goes in cooldown without dealing damage or stun, you preserve all your morale points and you can use them (except M3). And generally when you press it-  it goes through half of animation but nothing happens.

**Comment by taccr** [comment]
The ability goes off when theres an enemy target in range(which is ok) but it doesn't seem to do anything.
No stagger, no damage, no combat log entry or anything.

**Comment by Soulwhisper** [comment]
It doesnt work at all...i click on it and it triggers back off.Its like denying the clicks im doing.

**Comment by georgehabadasher** [comment]
After some testing, it won't go off unless you have a hostile target.  It will hit every target in the AoE except your target.
