### ISSUE TITLE
M2 Focused Mind doesnt work like intended

### ISSUE THREAD

**Issue by Ktaan** [WarEmu/WarBugs#5948]
1) Terrible Embrace pulling through M2 Focused mind. And it wasnt like this on live for sure.

2) You still got tank punted with Focused Mind activated (not sure it it was like this on live)

**Comment by Evildoor** [comment]
#2211

**Comment by Garrulillo** [comment]
Focused Mind only works half way. Remove and ignore de negative conditions, as intended, but the cast time reduction not works at all.

**Comment by gittoaster** [comment]
Pretty much any class can use a non-morale ability to effectively shut down a focused mind used in a defensive or offensive situation.  It's kind of sad, and it is currently not working as it expected currently.
From what I remember only morale ability is able to do anything related to CC.  Right now there interrupts seem to still work, anytthing that will stop you from casting will work.. 
I would suggest that no non-morale abilties can stop a caster while FM is active.
