### ISSUE TITLE
[PQ] Loot bag rewards

### ISSUE THREAD

**Issue by Grywwy** [WarEmu/WarBugs#5949]
Green and white loot bags only have some cultivating stuff and money to choose from.

![grywwy_038bug](https://cloud.githubusercontent.com/assets/13614929/15252576/dda7e010-192e-11e6-962f-95e75aab108f.jpg)

![grywwy_039bug](https://cloud.githubusercontent.com/assets/13614929/15252585/e885b2be-192e-11e6-8a52-de44177776bb.jpg)

The green bag was from Tomb of Deathsword
The white bag was from Reicharts raiders

**Comment by Evildoor** [comment]
#5377 #5837
