### ISSUE TITLE
[Ability][White Lion]Blindside DoT component is not properly applied.

### ISSUE THREAD

**Issue by sebid** [WarEmu/WarBugs#595]
**Ability Name:** Blindside
**Link:** http://warhammeronline.wikia.com/wiki/Blindside

Expected Behaviour: Skill should do an initial damage and apply a Damage over Time element on the target.
Observed Behaviour:
- When opening combat with the skill it will do the damage and sometimes it will apply the DoT component.
- During combat when circling the target, it will do the damage component but will rarely apply the DoT component.

May be related to positional checks server side on DoT component as well? 
Video: http://youtu.be/POBfs29hjOs

**Comment by sebid** [comment]
Not going to open another bug report for the issue, but sometimes after being dragged on the Hotbar, the Blindside skill gets replaced at random with other skills after a specific event which I don't know yet. Happened to me two times after relogging.

**Comment by ozarmidrashim** [comment]
If the server crashes, the server will reslot the skills a character gained when first created into their default slots.
