### ISSUE TITLE
Reickland burning - missing npc?

### ISSUE THREAD

**Issue by gasskull** [WarEmu/WarBugs#5950]
i been trying to find elohir silverhawk, supposed he should be inside the tents , but he isnt there, aswell roamed  the whole  area trying to find him with no avail. any word if the npc is missing?

**Comment by Evildoor** [comment]
Who is he?

**Comment by gasskull** [comment]
elohir silverhawk

**Comment by Evildoor** [comment]
Khm. Ok, i'll be more precise. What kind of NPC is he? Rally master? Target of a quest? Part of ToK unlock?

**Comment by gasskull** [comment]
he is a npc to kill for the quest reickland burning. i apologize for my english

**Comment by saupreusse** [comment]
he was there all the time. he stands between the two tends...
