### ISSUE TITLE
T4 Elf WH belt - " Wraith's Lash "

### ISSUE THREAD

**Issue by noisestorm** [WarEmu/WarBugs#5953]
Belt has 7 willpower on it, but no STR or WS instead.

**Comment by Ryanfawkez** [comment]
http://www.arsenalofwar.com/armor/Order/Wraith's%20Keysash
http://www.arsenalofwar.com/armor/Order/Wraith's%20Tool%20Belt
http://www.arsenalofwar.com/armor/Order/Wraith's%20Silkenwrap

Seems all belts have willpower on 'em. I suggest changing every willpower stat on all but the healer belts to their core dmg stat.

**Comment by wargrimnir** [comment]
Willpower was removed/replaced from all classes that had no use for it a few weeks ago.
