### ISSUE TITLE
T4 Dwarf WH Boots - Drengi Shankboots & Badmoon Shankboots

### ISSUE THREAD

**Issue by noisestorm** [WarEmu/WarBugs#5954]
![boots](https://cloud.githubusercontent.com/assets/13032588/15256005/96543d06-193f-11e6-97d0-aff3904c93ef.JPG)

Judging from this info (as well as Magus boots having +2% crit on them) and seeing that the WH boots for example are both only with 28stat + 18stat , maybe a lot more boots need their +15power or +2crit

**Comment by Ryanfawkez** [comment]
Agreed. 2% crit on the Drengi boots and +15 power on the Badmoon boots?

**Comment by Ryanfawkez** [comment]
Added +15 of a certain power dependent on archetype to all the Badmoon boots. All the Drengi boots have a 2% crit value based on archetype (tanks get 2% block).
