### ISSUE TITLE
T4 Dwarf WH torsos - Ironskin Longcoat & Badmoon Longcoat

### ISSUE THREAD

**Issue by noisestorm** [WarEmu/WarBugs#5956]
Both items have 30stat+6stat (other one has actually 30+8). Stats should most likely all across the board be 30+25+6, as well as all torsos missing most likely some sort of defensive procc. Only one available on arsenal as referance though:  
![torso](https://cloud.githubusercontent.com/assets/13032588/15256589/77831980-1942-11e6-87b1-7b7275c49dd8.JPG)

**Comment by Ryanfawkez** [comment]
Good call. This requires some well thought out planning beforehand though.

**Comment by Ryanfawkez** [comment]
Gave all items three stats, adjusted values accordingly.
