### ISSUE TITLE
T4 BO Kadrin Valley

### ISSUE THREAD

**Issue by stillwaterww** [WarEmu/WarBugs#5957]
When standing at Icehearth Crossing bo during a zone lock, no rewards are given.

**Comment by noisestorm** [comment]
Can confirm: Whole area does not count towards the RvR area. Means also no AAO there.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
