### ISSUE TITLE
T4 Empire WH - Hat of the Fist & Hat of Repose

### ISSUE THREAD

**Issue by noisestorm** [WarEmu/WarBugs#5958]
http://www.arsenalofwar.com/armor/Order/Hat%20of%20the%20Fist
http://www.arsenalofwar.com/armor/Order/Circlet%20of%20Repose

Helms are both missing 2% melee crit.

**Comment by Ryanfawkez** [comment]
I assume it's the same for a lot of other items in the DB. Should assign somebody to check them all ;)

**Comment by Ryanfawkez** [comment]
Fixed.
