### ISSUE TITLE
T4 Elf WH Shoulders - Bandolier of Hatred & Wraith's Bandolier

### ISSUE THREAD

**Issue by noisestorm** [WarEmu/WarBugs#5959]
(for referance)
http://www.arsenalofwar.com/armor/Order/Wraith's%20Runemantle
http://www.arsenalofwar.com/armor/Destruction/Wraith's%20Shoulderguards

Both items most likely missing 2% crit on them.

**Comment by Ryanfawkez** [comment]
I assume it's the same for a lot of other items in the DB. Should assign somebody to check them all, as with the helmets.

**Comment by wargrimnir** [comment]
Added missing crit values
