### ISSUE TITLE
[Ability][White Lion]Sundering Chop armor ignore partially works.

### ISSUE THREAD

**Issue by sebid** [WarEmu/WarBugs#596]
**Ability Name:** Sundering Chop
**Link:** http://warhammeronline.wikia.com/wiki/Sundering_Chop

First of all, on various websites, I see the skill ignores 50% armor. On RoR for my WL, it says a static 247. It's not 50% of owner armor either, as my armor was at 402. Might be an issue with a magic number?

Expected Behaviour: Skill should do the initial damage. If the character is behind the target, it should do more damage, ignoring 50% of its armor.
Observed Behaviour:
- On player characters, skill does X damage in front or sideways and when being behind it does X+more damage, ignoring *some* armor.
- On NPCs, skill does X damage from the front or behind, not applying the armor ignore component. Either NPCs have 0 armor or the mechanic for NPC armor ignore is not working?

Video: 
http://youtu.be/TjXAMX7wusw
http://youtu.be/Ja3VaaiIdgA

**Comment by ozarmidrashim** [comment]
Client tooltips are God, and overrule any and all other sources.

http://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=1189 is where ability issues are handled.
