### ISSUE TITLE
T4 ToK Jewelry 

### ISSUE THREAD

**Issue by KonradCurze** [WarEmu/WarBugs#5960]
The Oathstones set bonus is funky and, of course unobtainable, since illegal areas.

Now: 2 Pieces +15 Auto attack haste

Actually: 2 Pieces : On Hit 10% Debuff targets armor by 1200 for 10s.

and then much later nerfed to 3% proc chance for 3-400 armor reduction

**Comment by KonradCurze** [comment]
Well a GM told me to do so, anyways one cant help to be interested, wondering if its a intended RoR flavour. Whatever maybe I shouldnt use this thing, all the buttons already giving me a headache

**Comment by cimator** [comment]
That label tho:D

**Comment by KonradCurze** [comment]
I'm just a misunderstood chosen who wants ArPen pls halp

**Comment by Torquemadra** [comment]
Its intended, changes were made to procs and passive abilities for balance purposes, primarily we dont want aoe debuffs going out via aoe heavy classes. Resistence debuffs are gone too. All procs in game are set.
