### ISSUE TITLE
SH Annihilator Armor Set

### ISSUE THREAD

**Issue by cimator** [WarEmu/WarBugs#5961]
Annihilator set for SH gives %5 Dodge with 4 piece bonus, it should be %5 ranged crit chance as its here; https://docs.google.com/spreadsheets/d/13C0SbnhRDmmD_6DaxgoeBuDhM8yLy2igWktFQ6DkdKo/edit#gid=1833526864 , checked all other stats and they are same with this link except that one

**Comment by Torquemadra** [comment]
fixed next patch
