### ISSUE TITLE
Double Spawn

### ISSUE THREAD

**Issue by cimator** [WarEmu/WarBugs#5963]
![leakypants_008](https://cloud.githubusercontent.com/assets/17130290/15262815/765e3fd2-196d-11e6-8f53-46d616bc03fd.jpg)
 Double Spawn of a mob " Graelba " , checked also if it should be unique;
![leakypants_007](https://cloud.githubusercontent.com/assets/17130290/15262824/90d7a2f4-196d-11e6-994c-831d5ed8ad54.jpg)
Got a tome unlock, so yep.

Coords; 24k, 49k TM

**Comment by Ryanfawkez** [comment]
It has three spawns, removing 2 of 'em.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
