### ISSUE TITLE
T4 CH Darkboots of the Mercenary

### ISSUE THREAD

**Issue by KonradCurze** [WarEmu/WarBugs#5964]
Chosen boots for Officer's Emblem , have no armor on them

Edit Screenshot: https://i.gyazo.com/9f2c9677011b203fb1a48312cb333f7f.png

**Comment by Torquemadra** [comment]
screenshots please, shows 565 in db

**Comment by Shadowgurke** [comment]
![armor](https://cloud.githubusercontent.com/assets/1018113/15264534/63f6360e-1974-11e6-8da0-d80680e8c426.JPG)

**Comment by Torquemadra** [comment]
well its right on dev and db, not sure what to say but wait for next patch
