### ISSUE TITLE
[PQ] Tower of Awakening Too Many Mobs

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#5967]
The Tower of Awakening PQ in the Chaos Wastes has a lot of mobs spawning, it seems a bit excessive. Also there are 2 spawns of Bloodletter K'Thar  (that I found).

![yttria_018](https://cloud.githubusercontent.com/assets/13975292/15265235/fdca7392-1944-11e6-8aa1-665c02d42a6b.jpg)
![yttria_019](https://cloud.githubusercontent.com/assets/13975292/15265257/765589a0-1945-11e6-8ff0-c1e4c4361843.jpg)

**Comment by Evildoor** [comment]
Is this wrong? I remember some PQs in CW having lots of mobs on live.

**Comment by CaptainoftheHarem** [comment]
Here is how it looked on live (it is facing the bottom picture in my first post)
![yttria_086](https://cloud.githubusercontent.com/assets/13975292/15345495/393e4f24-1c75-11e6-9ad7-bcc5aa8101dc.jpg)

**Comment by Soulwhisper** [comment]
Functionality added to the following tier 4 PQ !
