### ISSUE TITLE
fighting monsters, they often get frozen and stop

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#5968]
I've seen this consistently in T4 where fighting a monster (as AM ) where monsters seemingly get stuck in range and just stay there, unresponsive.

**Comment by Tholkienn** [comment]
Same in farming with kotbs, mobs stop, don't reset.

**Comment by gittoaster** [comment]
I haven't seen this in a while so I'm assuming is not occurring any longer.
