### ISSUE TITLE
The Praag Prison

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#5971]
Located directly north of Martyrs Square:

![abolition_003](https://cloud.githubusercontent.com/assets/15091486/15266469/ff7cd8a6-19e4-11e6-908f-c75e795eef61.jpg)
![abolition_004](https://cloud.githubusercontent.com/assets/15091486/15266470/01244a18-19e5-11e6-81f9-4627efcc20be.jpg)

Knight punt and Magus Rift were two examples used here, but I guess any displacement that gets people over/through the fence would work.

Maybe removal of the fence?

**Comment by noisestorm** [comment]
The fences here are statics on the map. You cannot remove them without modifying the client. The only thing they could do would be placing some random rubble above it to prevent people from falling into it.

**Comment by Luth-RoR** [comment]
Client side issue. Delayed until fa fix is possible.
