### ISSUE TITLE
The Weed Whacker

### ISSUE THREAD

**Issue by Averatos** [WarEmu/WarBugs#5975]
![averatos_008](https://cloud.githubusercontent.com/assets/16805605/15267194/322be2e4-19bb-11e6-84e0-f2c421da188e.jpg)
The given titel should be "The Weed Whacker"

**Comment by Ryanfawkez** [comment]
Include details for the original unlock next time please. Just the NPC name is fine, makes for easier bugfixing.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
