### ISSUE TITLE
Tome unlock - Insane in the Membrane

### ISSUE THREAD

**Issue by Sersaypygan** [WarEmu/WarBugs#5979]
Champ required for kill drops the scintillating scale, but the item does nothing hen right clicked. According to tome unlock guides, this item is ment to duplicate itself several times in the players inventory upon multiple clicks, before the title "The Insane" is unlocked.

**Comment by Ryanfawkez** [comment]
Item interaction isn't supported yet. Will apply pocket item work-around.

**Comment by Ryanfawkez** [comment]
Hmm, seems I can't add titles alongside with tome unlocks to items. Going to declare this as 'cannot fix yet'

**Comment by Sersaypygan** [comment]
Well, I can listen to Cypress hill in the meantime. Here's hoping you guys will figure something out sometime. :)

**Comment by Natherul** [comment]
same as: https://github.com/WarEmu/WarBugs/issues/5748

also now the tok unlock works but it does not give you the title :D
