### ISSUE TITLE
Quest - The Pleasure of Pain

### ISSUE THREAD

**Issue by Sersaypygan** [WarEmu/WarBugs#5980]
Quest potentially impossible to complete. Quest requires the player to find and kill Varthon Bloodblade, and question the body upon defeat for turn in and progression. No quest progression possible due to no possible interaction after NPC's death.

Perhaps he was ment to turn friendly upon a certin health %.

**Comment by noisestorm** [comment]
Did you try talking to the NPC you got the quest from? Thats normally how it works here for the time being

**Comment by Sersaypygan** [comment]
Yes, that was not the turn in each which led me to the assumption of the other method I listed. I cant say for sure though, as it's been quite a few years since i'v done this quest before.

**Comment by Gakvar** [comment]
Confirmed, after killing Varthon Bloodblade, there is nowhere to turn this quest and continue the chain.

**Comment by Nekronsieben** [comment]
still can't return the quest.

**Comment by Lheana** [comment]
You will be able to turn in the quest to Varthon with next patch.

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
