### ISSUE TITLE
ORVR T4 Dwarf rewards, Body: wrong stats

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#5981]
The purple rewards have same stats apart from 1 point of difference:

![screen shot 2016-05-14 at 10 32 21](https://cloud.githubusercontent.com/assets/18053736/15267662/a082cb3c-19bf-11e6-8f30-f9f704df626a.png)
![screen shot 2016-05-14 at 10 33 52](https://cloud.githubusercontent.com/assets/18053736/15267663/a1d4c6ca-19bf-11e6-8c8e-afd553f8640e.png)

The blue rewards have a bigger gap

![screen shot 2016-05-14 at 10 33 37](https://cloud.githubusercontent.com/assets/18053736/15267666/aba6f268-19bf-11e6-947d-f83670948c36.png)
![screen shot 2016-05-14 at 10 33 45](https://cloud.githubusercontent.com/assets/18053736/15267667/acb93148-19bf-11e6-8434-c486f9619273.png)

**Comment by NorKalli** [comment]
long ago fixed
