### ISSUE TITLE
ORVR T4  Elf: rewards, Shoulders: wrong stats

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#5983]
The stats differ significantly.
Blue rewards:

![screen shot 2016-05-14 at 10 43 47](https://cloud.githubusercontent.com/assets/18053736/15267716/390651e8-19c1-11e6-8e3c-ed4ca5644e0d.png)
![screen shot 2016-05-14 at 10 43 35](https://cloud.githubusercontent.com/assets/18053736/15267722/5694e904-19c1-11e6-8aa7-63512de9a10f.png)

Purple rewards:
one piece is made redundant by the obviously better second.

![screen shot 2016-05-14 at 10 43 55](https://cloud.githubusercontent.com/assets/18053736/15267728/70f99826-19c1-11e6-885b-a71f6e49e47f.png)
![screen shot 2016-05-14 at 10 44 04](https://cloud.githubusercontent.com/assets/18053736/15267729/72308aa6-19c1-11e6-8fb5-c8f883493744.png)

**Comment by NorKalli** [comment]
@wargrimnir purple items are now balanced, however blue choices still are clearly in favor of the first one. Is this good to go, or need a tweak?
