### ISSUE TITLE
Pillars of Remembrence AreaID

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#5985]
The areaID for the Keep is wrong.Its not covering the whole area.For example if you go in the front door/stairs the UI doesnt show up so you are not participating...At the sides inside the Keep too UI is missing.

**Comment by saupreusse** [comment]
seems fine. maybe someone else fixed it already.

**Comment by Soulwhisper** [comment]
Correct.Fixed.
