### ISSUE TITLE
SET OF THE RUIN (KOTBS) ((CLOSED))

### ISSUE THREAD

**Issue by Antalor** [WarEmu/WarBugs#5988]
Hello. I just got 3 pieces of Ruin and seems like 1st bonus from this set doesn't work.
It's +630 armor,
Greetings.
PS. Please for fast fix it!

**Comment by Evildoor** [comment]
Proof.

**Comment by Antalor** [comment]
Okay, give me some minutes.

**Comment by Antalor** [comment]
Sorry, I was wrong. When I got second piece of Ruin I instantly equipped it. After relog, bonuses work fine it seems.
Sorry for problem, topic for close.
Greetings.

**Comment by Evildoor** [comment]
FYI - in cases like this you can close your own tickets, no need to rename them.
