### ISSUE TITLE
[White Lion] Baited Trap tactic

### ISSUE THREAD

**Issue by Reyanabeth** [WarEmu/WarBugs#5990]
Granted ability doesn't work properly.
Armor bonus is significantly worse.
![reyanabeth_027](https://cloud.githubusercontent.com/assets/17819287/15269972/7a2caecc-1a31-11e6-9aad-181a41a4fb5e.jpg)
![reyanabeth_025](https://cloud.githubusercontent.com/assets/17819287/15269973/8121d9dc-1a31-11e6-907a-9fd1ceebf6ec.jpg)

**Comment by Evildoor** [comment]
Were you affected by any other armor buffs? Like potion?

**Comment by Reyanabeth** [comment]
Yes. I had used unguent with 660 armor buff.

**Comment by Evildoor** [comment]
#5937
