### ISSUE TITLE
Baraz Keep AreaID

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#5991]
The AreaID for RvR Defending/Attacking the Baraz Keep is currently inside the Black circle.It should be increased to Green because while we were defending some people were standing inside the Black circle(They can see the PQ scoreboard popping up) but many people were standing outside of the black circle[In front doors of Keep] and they couldnt participate to get the loot from chest.
![123](https://cloud.githubusercontent.com/assets/16864486/15270004/88014502-1a19-11e6-8f42-80135899b5d1.jpg)

**Comment by saupreusse** [comment]
it is much bigger than the green circle, maybe someone else fixed it already. can be closed.

**Comment by Soulwhisper** [comment]
Correct.Fixed.
