### ISSUE TITLE
[Item] Goblin Green Dye

### ISSUE THREAD

**Issue by Reyanabeth** [WarEmu/WarBugs#5992]
There is an issue with this particular dye bottles.
It seems there are 3 different types of green quality bottles, which cannot be stacked.

![reyanabeth_015](https://cloud.githubusercontent.com/assets/17819287/15270016/219fe22c-1a33-11e6-90df-9e92159b9f99.jpg)
![reyanabeth_016](https://cloud.githubusercontent.com/assets/17819287/15270018/27c26d0a-1a33-11e6-8b5b-6cf2398f01b4.jpg)
![reyanabeth_017](https://cloud.githubusercontent.com/assets/17819287/15270019/2bc3d5e2-1a33-11e6-968e-f82a5280a692.jpg)

**Comment by Torquemadra** [comment]
Shouldnt occur in future but current ones you have will remain this way until used.

**Comment by Tholkienn** [comment]
Same for me.
