### ISSUE TITLE
Quest: Metal Hide

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#5995]
Salamander Eggs are spam-clickable.

Talisman rewards are garbage, pls update to something relevant for R10.

**Comment by Evildoor** [comment]
> Salamander Eggs are spam-clickable.

#424

**Comment by sioding** [comment]
Quest checked - Eggs aren´t spam-clickable anymore. Removed the weak talisman - there are inferior available.

**Comment by sioding** [comment]
Fixed with patch from 26.01.2018
