### ISSUE TITLE
Title : Lion Guard

### ISSUE THREAD

**Issue by Celefindel** [WarEmu/WarBugs#5998]
Greetings . I went to fetch the hidden scroll in Eataine, 30k, 36k, that unlocks the dark elf TOK "The history of the Dark Elves" and grants the title "Lion Guard". The TOK unlocks all right but the title doesn't appear in the title list, and appears as ??? in the reward icon of the unlock in the Bestiary.
I searched the bugtracker first before posting, to see if there was a report of these kind of title bugs, but couldn't find anything. Thank you :)

**Comment by Ryanfawkez** [comment]
Already fixed in next patch.
