### ISSUE TITLE
Tok : Picking up the pieces and the Master Hunter's pelt cloak

### ISSUE THREAD

**Issue by Celefindel** [WarEmu/WarBugs#5999]
Greetings. The TOK "Picking up the pieces" in the wolf section in the bestiary, which also grants the "Master hunter's Pelt" cloak doesn't seems to work. It is required to kill 60 winter wolves and winter howlers in Praag (around 18k, 4k) for the Order side. I killed at least 80, and the tok is still locked, and the cloak still can't be bought in the Altdorf library. Thank you for all you hard work on the game !

**Comment by Ryanfawkez** [comment]
PvE kill quests remain unsupported at the time.
