### ISSUE TITLE
Groups and player positions

### ISSUE THREAD

**Issue by JeFawk** [WarEmu/WarBugs#6]
* Ported issue
* Created by MaxHayman

Players proper positions are not sent.
This needs to be decoded:
Group.cs
// X/Y ....
`byte[] data =`
`{`
`0x84,0x7A,0x90,0x95,0x03,0xE2,0x36,0x50,0xE2,0x50,`
`0x40,0x01,0x02,0xD4,0x01,0x01,`
`};`

Some work has been done on this in https://github.com/WarEmu/WarEmu/commit/5c3f1cc03ba2bf43af6fd2b3b8017ef6bb9fef14

**Comment by MaxHayman** [comment]
This was fixed.
