### ISSUE TITLE
Chaos Wastes   Title unlock  The Anarchist 

### ISSUE THREAD

**Issue by Dirkdaring** [WarEmu/WarBugs#6000]
Went to pick up the title last night,  which I had also done back on live  the hidden scroll was behind the North east pillar, just like its supposed to be , however when i clicked on the scroll it said I received a Beasitry unlock, and no title unlock, 

  Here is the location and description for the unlock.  At the Mastiff BO . 

   X: 23000 - Y: 10000	The Anarchist
Unlock: Empire: The History of the Empire Goal: Click on the scroll located behind the NE stone pillar by the flag.

**Comment by Ryanfawkez** [comment]
Already fixed in next patch.

**Comment by Ryanfawkez** [comment]
https://github.com/WarEmu/WarBugs/issues/5998
