### ISSUE TITLE
T4 Rams

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#6002]
Ram doesnt work at Praag Destro Keep.

**Comment by Soulwhisper** [comment]
Ram doesnt work at Drakebraker's Scourge Keep at DW.

**Comment by Soulwhisper** [comment]
Ram doesnt work at Bloodfist Rock Keep.

**Comment by Tholkienn** [comment]
Message : Says too far form door.

**Comment by Morrdread** [comment]
too far from door, and here is a ss
![morrdread_038](https://cloud.githubusercontent.com/assets/18380142/15274663/002ec470-1a86-11e6-99ea-cca42fd7c59c.jpg)

**Comment by Soulwhisper** [comment]
Yes its not deployable at outer doors.

**Comment by genisaurus** [comment]
Should be fixed in next patch

**Comment by Soulwhisper** [comment]
No damage on doors.Tried a couple of Keeps.No combat log.
