### ISSUE TITLE
Empire Foreman NPC at Passwatch Castle Keep

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#6003]
The NPC that sells siege weapons died somehow and doesnt respawn.

**Comment by Soulwhisper** [comment]
**UPDATE** Found out that he is being pulled out with AOE probaply from Destro attacking the front Keep Door...so he goes down fights and dies...

**Comment by Evildoor** [comment]
#5453 may be related

**Comment by Soulwhisper** [comment]
Probaply...but not exactly the same.This NPC goes out and defends at door.He died but his corpse found at his spawn position.
