### ISSUE TITLE
T3 Ram

### ISSUE THREAD

**Issue by Gribby** [WarEmu/WarBugs#6006]
No damage on door, at Passwatch Castle Keep (2nd door). Couldn't deploy on first door.

**Comment by Evildoor** [comment]
#6002 may be related

**Comment by Soulwhisper** [comment]
I changed the title to T4 rams in my ticket.I reported only Rams for T4.

**Comment by Soulwhisper** [comment]
Confirm that on 2nd door it doesnt do any damage.And adding that trying to deploy 2nd ram after the first one is destroyed it gives a message : Door is blocked by another ram

**Comment by genisaurus** [comment]
Should be fixed in next patch

**Comment by Soulwhisper** [comment]
No damage on doors.Tried a couple of Keeps.No combat log.

**Comment by Evildoor** [comment]
Not reopening since i presume that this and #6002 are the same problem.
