### ISSUE TITLE
Runic Blessings Slayer talent bug

### ISSUE THREAD

**Issue by Earthpacu** [WarEmu/WarBugs#6007]
The Runic Blessings Slayer talent currently revives you with the resurrection stat debuff.

As far as I remember on live this was never the case and it spawned you with no state debuff like regular resurrections do.

Haven't attached any pictures as it's incredibly easy to replicate, just slot Runic Blessings and die until it procs.

**Comment by ozarmidrashim** [comment]
Proof_required.jpg

**Comment by Evildoor** [comment]
No proof, closing.
