### ISSUE TITLE
[World] Death's Peak illegal area

### ISSUE THREAD

**Issue by twyxxy** [WarEmu/WarBugs#6008]
[Dead Weight](http://warhammeronline.wikia.com/wiki/Dead_Weight) should have two options for unlock, Death Peak and Chaos Wastes.
Death Peak location ports player back to Book of Binding location due to "illegal area".

![](http://i.imgur.com/FbwA8J2.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
