### ISSUE TITLE
[Quest] Killing Time

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#6009]
I'm pretty confident this quest counts kill contribution across all zones. I have it completed and am yet to fight in Chaos Wastes.

**Comment by Evildoor** [comment]
> The overall kill quest rewards have been increased, and will now be restricted to the pairing in which they are assigned.

Maybe it's counting all kills in Empire - Chaos zones? Or in other zones / scenarios too?

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
