### ISSUE TITLE
[Ability][Morale]Pet healing increases the morale meter.

### ISSUE THREAD

**Issue by sebid** [WarEmu/WarBugs#601]
Mechanic: Morale blue bar
Ability required to reproduce: http://warhammeronline.wikia.com/wiki/Nature%27s_Bond 

Expected Behaviour: I believe the Morale meter should rise up only if the character is in combat. Also, through offensive means like attacking, and being grouped up.
Observed Behaviour: The Morale meter can be charged by casting Nature's Bond for a White Lion for example, which heals the pet, and is a spammable skill. Whenever the player casts the heal, he enters combat, and probably a side effect is the increase of the Morale bar. Afterwards on each tick of the healing spell, the Morale bar will continue charging up, unless the player exits combat by not casting anymore.

I have no idea if it's the same for Squigs/Mag/Engi as I don't have one to test if they have healing spells.

Video: http://youtu.be/3ef_l1ETKvo

**Comment by Thorgatin** [comment]
A sidenote:
The player doesn't enter combat when casting (no "in-combat" status, tactics can be changed etc.), only the Moral bar raises.

**Comment by Evildoor** [comment]
AFAIK, healing no longer puts you in combat(unless your target is in combat). Closing.
