### ISSUE TITLE
DoK Tier 4 RvR Gear 

### ISSUE THREAD

**Issue by freshour** [WarEmu/WarBugs#6010]
RVR Tier 4 - Greenskin - Bloodfist Xiphos - needs the willpower to be changed the strength as it has parry and 3% melee crit. 

The cloack from chaos zone, tier 4 Torment Cloak of Repose - needs heal crit changed to melee crit

**Comment by Abolition** [comment]
Itemisation across the board for DOK INF gear is pretty bad, but that has been standard since T1, and it was like this on Live. Hopefully it gets changed, however.

**Comment by wargrimnir** [comment]
Neither of these appear to be an issue currently.
