### ISSUE TITLE
Problem with any Pet related careers

### ISSUE THREAD

**Issue by soulcoffin** [WarEmu/WarBugs#6011]
Hello,

This just started yesterday. All of my pet based characters have instability issues with their pets. For example every one of them have lost their pet stance bars. They exist in formatting the interface ui but, do not appear once you save. Also the pet status bar and icon flash off and on. My Magus today has her Horror following her around where ever she goes, like a WL or SH pet. 

I do not know at all what this could be. So this is why I am contacting you.

Please help, thanks!

**Comment by soulcoffin** [comment]
FYI I fixed it myself. It had to do with the add on Loyal Pet. Thanks

**Comment by Evildoor** [comment]
All of this (ui problems, daemon following their Magus around) was already reported elsewhere. Please, use search.

**Comment by soulcoffin** [comment]
OK. My bad. This is the first time I have used this reporting domain. So how does it work from here. Do I attach this to another ticket or what? #5463

**Comment by Evildoor** [comment]
If you found that your problem was already reported, you should comment existing ticket if you have something to add.
