### ISSUE TITLE
quest : Sanctified ground (again)

### ISSUE THREAD

**Issue by Milord9** [WarEmu/WarBugs#6012]
For the Quest "Sanctified ground" (Ostland, 59-47) :Thomas the champion cannot be found and killed in order to achieve the quest. I'm aware of the past problems with it (#2829) but even if Thomas is supposed to be in an enclave outside the monastery with the tweaked quest, I've been unable to find him. Or there's no NPC, or I'm bad.

**Comment by Torquemadra** [comment]
look harder

![torquemadra_098](https://cloud.githubusercontent.com/assets/16200780/15275010/87ce5a1e-1a8e-11e6-94da-c987b73ad6a6.jpg)
