### ISSUE TITLE
Timeless wisdom quest

### ISSUE THREAD

**Issue by svenimir** [WarEmu/WarBugs#6013]
Completed on Runepriest is Praag.   from Ch 18 camp.  Feel rewards should be more level appropriate.   Gave me option of 2 level 31 helms for completing quest.   Both 149 armor, 15 willpower.  one with 26 wounds, other with 10 wounds.

**Comment by Evildoor** [comment]
How it was on live?

**Comment by svenimir** [comment]
Sorry, I could not find much on the quest. On war.mmodb.com<http://war.mmodb.com/> it just shows experience and nothing else.  May not have been updated properly though.   Obviously not a big issue, just came across it while questing.

[http://war.mmodb.com/images/776x106xlogo.jpg.pagespeed.ic.nNrdDXykux.jpg]<http://war.mmodb.com/>

Warhammer Online : Age of Reckoning Database - MMO DB<http://war.mmodb.com/>
war.mmodb.com
The Collector As a reminder, the easiest way to submit information to our web site is to download our Automated Collector and run it in the background while you are ...




________________________________

**Comment by Evildoor** [comment]
Unfortunately, in such case we can't do much. We can fix items when info from live is available, but if it's not then these items have to wait until we get to reworking PVE rewards, which is very low on our to-do list.
