### ISSUE TITLE
Reintroduction of orange mob bug?

### ISSUE THREAD

**Issue by s0undie** [WarEmu/WarBugs#6016]
Noticed while scavenging orange champ mob that disabling my turret after pulling them with it, bugged them out. They will not find a new target that does damage to them. 

Basically i can pull anything that's an orange mob and render them useless, taking my time killing them.

I noticed this way back, but unsure if it was ever fixed? I think it was but that bug is back again in that case.

**Comment by Evildoor** [comment]
#2627
