### ISSUE TITLE
Critical on tali making

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#6017]
So tonight, I crit on two purple fragments for talisman making and was super excited.

Except, they made blue talismans.

Mats used:
lv 50 container
lv 175 puple fragment (armour and willpower)
lv 200 gold dust
lv 200 curio
lv 175 magic essence

A normal tali output would be a level 28 purple talisman.
A normal crit in this instance would be a level 32 purple talisman.

The critical made a level 36 blue talisman, which is LOWER overall output.

Sad panda :(

![rekt](https://cloud.githubusercontent.com/assets/15091486/15272433/7d7a628c-1ab7-11e6-8a74-561fd0accb12.png)

**Comment by Evildoor** [comment]
#4501
