### ISSUE TITLE
Epic jewelry healing not ticking

### ISSUE THREAD

**Issue by The-Real-Vyta** [WarEmu/WarBugs#6019]
I got the epic jewelry pieces [Gorkamork][Hapless Ha'penny][Wind of Change][Fullbelly's Lucky Foot] today specifically for a full set bonus of 52 hp every 4 secs but i've been watching and tracking it for a few hours but it is not ticking so it's not healing at all. I'm also curious if the other set bonuses of ap and moral are ticking as well. I have them all on as well. I am on a knight.

**Comment by Torquemadra** [comment]
works perfectly, tested just now in IC on live
