### ISSUE TITLE
255 Mastery Points bug - Ruin, Anni, Merc

### ISSUE THREAD

**Issue by Blubberino** [WarEmu/WarBugs#6020]
Somehow it is possible to bug out the mastery points. It shows you then an wrong number of points which you actually can distribute. After you distributed them it only takes the last selected line and skills so it doesn't take more than you normaly have. Not sure how the bug occured but it occured ofter equiping ruin set. 
Each equipment item which you change will also cause a small lag the bug could have occured because of several appearance changes.

![laranaxas_028](https://cloud.githubusercontent.com/assets/16993024/15273109/b6d896a2-1a8f-11e6-891a-8b49250eca93.jpg)

I keep testing and let you know if I find out how it occurs.

**Comment by Blubberino** [comment]
Okay found it. Ruin set and then flying to prag caused it again

**Comment by Torquemadra** [comment]
Its mostly visual and tied to the +1 ability function of the set armour bonus that obliterator, tracker, annihilator, ruin, mercenary and bloodlord now have in place. If you try to spend all the points you will get a random build. Removing and replacing an armour piece resolves but will throw out a full respec

**Comment by Blubberino** [comment]
Yep but still gives you +2 instead of +1

**Comment by Zegreiart** [comment]
![arkenhest_000](https://cloud.githubusercontent.com/assets/17631607/15285357/3ed783d8-1b1c-11e6-9b40-ea218bca8ab4.jpg)

I found the same thing as Torq described, but I am able to keep and use ID, even though I am too low to have that ability/have it specced into.

I don't know if this is worth repeating, but I took a SS of me using ID and with the tree open. So, take that for what it's worth, hope this helps.

**Comment by Blubberino** [comment]
Not sure what you did but it isn't possible anymore to use the talent point at all

**Comment by Evildoor** [comment]
Point taken from pool was reported separately: #6379.

**Comment by taccr** [comment]
This is by no means a "just visual" bug. It is literally game breaking (refer to https://github.com/WarEmu/WarBugs/issues/6406).
Please handle with higher priority.

**Comment by Tesq** [comment]
a guildmates of mine reported that ruin5th bonus instead sometimes make his mastery reset , i post it here cos it's a common issue linked to th e+1 bonus in one path

**Comment by taccr** [comment]
The 255 comes from the set giving -1 mastery point when you equip the 5pc.
Causing an unsigned char underflow from 0 to 255 if you had all your talent points spent.

The client then thinks it has enough points to respec sending all the mastery training data to the server which causes a simple respec when you spend more mastery points than you have available. however (almost) any selected ability you trained during that point is still being bought causing impossible specs.

I recommend fixing the set to not modify the mastery points available and resetting everyones talent trees.

**Comment by Blubberino** [comment]
Seems to be fixed now does not occur anymore. The other bug seems to be fixed too.

**Comment by genisaurus** [comment]
Closing, fixed in recent patch.
