### ISSUE TITLE
The hornsnapper [Title]

### ISSUE THREAD

**Issue by silodin** [WarEmu/WarBugs#6021]
The correct npc does drop the correct item but it is not right-clickable thus can not grant the achievement/title which are both "The Hornsnapper"

**Comment by Evildoor** [comment]
NPC name, unlock name, NPC type.

**Comment by Ryanfawkez** [comment]
Here: http://warhammeronline.wikia.com/wiki/A_Little_Off_the_Top

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
