### ISSUE TITLE
Passwatch Castle Ram and Cannon

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#6022]
![pyromanths_008](https://cloud.githubusercontent.com/assets/16864486/15273281/3a07d25c-1a9c-11e6-90e6-bcefb8f1ddda.jpg)
They arent suppose to spawn up there.Especially RAM.They arent placed by players.

**Comment by Ryanfawkez** [comment]
Indeed it isn't. It's a game spawned cannon which persists from the 'new' RvR system back on the old live server, only problem is is that these siege weapons are also usable as regular weapons, rather than decorative pieces for siege weapon pick-up.

**Comment by genisaurus** [comment]
Should have been fixed in a recent patch

**Comment by Soulwhisper** [comment]
They are still there.

**Comment by genisaurus** [comment]
Sorry, was confusing with another keep. Will be fixed in next patch,

**Comment by Soulwhisper** [comment]
They are still there.Please re-open this.
And if someone could move the Cannon one floor up so it can face at the inner front door(Or remove it completely) and just remove the RAM.

**Comment by Soulwhisper** [comment]
Someone removed them.
