### ISSUE TITLE
Rank 1 morale: Misdirection

### ISSUE THREAD

**Issue by Sonare** [WarEmu/WarBugs#6026]
Don't affect by DoT.
In description it's about all incoming magic damage but DoTs didnt redirect.

**Comment by Evildoor** [comment]
"... and redirect half of any DIRECT damage ..."

**Comment by Sonare** [comment]
damage dont reduce also

**Comment by ozarmidrashim** [comment]
no_proof.jpg

What actually happens, like on every other damage modification skill on RoR, is that for DoTs, the effect of armor / resistance / damagetype modifiers is applied when the DoT is cast, not when the DoT is ticking.

Won't be looking at this unless proof is demonstrated that a Misdirection cast before a DoT is applied does not reduce the damage.

**Comment by Evildoor** [comment]
No proof, closing.
