### ISSUE TITLE
Bolster in t4

### ISSUE THREAD

**Issue by Sonare** [WarEmu/WarBugs#6027]
I meet guy who was bolstered to 40 lvl but he is "gray" for me (im 39). So when I killed him i didn't recieve any exp or inf points.  But if he kill me he will got huge amount of exp, rr and inf. 

what i'm asking - to do all of "bolstered" ppl not "gray" to max lvl (40) or make minimum lvl for t4 abit higher.

**Comment by Luth-RoR** [comment]
Needs confirmation if actually like described or caused by code to prevent repeated character/renown farming (intended).
