### ISSUE TITLE
WP and DoK T1 Fighter items

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#6031]
Fighter armor and belts of Vengeance are bugged for these classes: they are present on vendors but cannot be used. Some of them are "medium armor" instead of "medium robe", other are even more weird:
![pop_000](https://cloud.githubusercontent.com/assets/11015074/15273479/3a0a5a3e-1aa3-11e6-8079-cb1458c699c1.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
