### ISSUE TITLE
Quest: Crushing Stone

### ISSUE THREAD

**Issue by traveyb** [WarEmu/WarBugs#6035]
Chaos Chapter 21, Crushing Stone
On the map it refers to killing 2 types of mob, Stoneclan Bombarder and Stoneclan Ironhelm however in the ToK it says Stoneclan Bombarders and Stoneclan Alehelm (in which these don't exist but Ironhelms do).

**Comment by Ryanfawkez** [comment]
Stoneclan Bombarders, in the sense of an amount higher than 1. One Bombarder is 1 kill, you need 15.
Stoneclan Alehelms do exist; there is 7 of them compared to the 2 Ironhelms, unrelated to the quest. They are, however, noth of the quest marker. I will thus increase the quest marker's side for ease of nagivation.
