### ISSUE TITLE
[Slayer] Mercenary shoulders have 2% crit reduction instead of 3%

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#6036]
According to https://docs.google.com/spreadsheets/d/13C0SbnhRDmmD_6DaxgoeBuDhM8yLy2igWktFQ6DkdKo/edit?pref=2&pli=1#gid=1441773204

they should have 3%.
![cimbo_008](https://cloud.githubusercontent.com/assets/16117730/15273714/5a187442-1aa2-11e6-88e1-bb26638b46b6.jpg)

**Comment by Torquemadra** [comment]
fixed next
