### ISSUE TITLE
Tome unlocks - Lairs

### ISSUE THREAD

**Issue by Sersaypygan** [WarEmu/WarBugs#6037]
I somewhat remember (And others have also recalled when asked) that Lairs on live granted a tome unlock upon discovering them. I have played for awhile now, and done plenty of lairs, without getting any sort of tome unlock related to them. I do not know which section these unlocks where in, or their exact titles (I assume they'd be the same name as the boss in the lair). Just recalling best as I can from memory and others recalling the same.

**Comment by Ryanfawkez** [comment]
Cannot fix yet, as proximity unlocks are unsupported.
