### ISSUE TITLE
[Pets]Pets are not set to passive/inactive after mounting.

### ISSUE THREAD

**Issue by sebid** [WarEmu/WarBugs#604]
I have no idea if it's the same with Engi/Squig/Magus. Tested on my WL
**Expected Behaviour:** When using a mount, pets enter the Passive state, and their abilities are greyed out until dismounting, when they assume their previous state with the abilities becoming available again.
**Observed Behaviour:** The player can still command the pet to attack/follow/use abilities and the pet still reacts aggresively to the environment.

Video exemplifying the issue: http://youtu.be/rUsjhmmJF-w

Video with the correct behaviour: https://www.youtube.com/watch?v=sJ3O1PIt5aU#t=40 - 0:40 - Pet goes on passive and greyed out when player is mounted

**Comment by Zealote** [comment]
Update: War Lions (and presumably pets in general) can't be commanded while mounted now.

But they're still not set to passive, and the abilities aren't greyed out, meaning it's still possible to make the lion attack if you get close enough to an enemy while mounted.
