### ISSUE TITLE
Tome unlocks - Chaos god alters in Norsca

### ISSUE THREAD

**Issue by Sersaypygan** [WarEmu/WarBugs#6047]
This is a set of 4 lore or achievement unlocks that I unlocked several times on live. My memory on ALL the details for these are fuzzy, so bear with me.

There where a set of stone alters that would spawn, 1 at a time on a long timer, in random set spots in the area. (The khorne one is called Alter of Bloodshed.) To unlock their tome unlocks, one had to draw a nearby mob onto the alter and slay it. Once this was done, the unlock for that specific god was gained, and a moment later the alter would despawn, then start the time again for one of the 4 to spawn again later.
I do not have coordinates for all the possible spawn points, nor have i found all 4 of them as of yet, but they simply do not work. They can be right clicked, but nothing happens. They are also named "ToKUtilityMob" when standing next to them.

I did my best to track them down though. The alters are.
Khorne - Alter of Bloodshed.
Slaanesh - Alter of the Shameless (Found this up in 2 different locations.)
Tzeentch - Alter of the Raven
Nurgle - Alter of Decay

These spawn on both order and destro side.

**Comment by Ryanfawkez** [comment]
Awesome, some backstory to the seemingly random-ass altars we use in jumping puzzles and event quests now! :dancer: 
Sadly this cannot be fixed yet.

**Comment by Sersaypygan** [comment]
I figured it wouldint be fixable just yet. Still, I try to remember what i can. And if I recall, those unlocks had some pretty nifty lore insight too. Now you know though.

**Comment by Sapphiratelaemara** [comment]
Now provides tome unlocks when clicked but does not have the "kill mob at" functionality.
