### ISSUE TITLE
Murgluk's gits

### ISSUE THREAD

**Issue by lilsabin** [WarEmu/WarBugs#6050]
so , i am questing in dwarf and i have noticed that the pq s are bugged in chapter 2 (thats where i am at ) 
the first one is the one were you have to kill the bloody sun guys , when you kill them it doesnt count .
The second one is the one in the mine , when you interact with the pile of coal or the dust bag , nothing happen 

IT IS DWARF TIER 1 PQ CHAPTER 2

**Comment by Evildoor** [comment]
Exact PQ names.

**Comment by lilsabin** [comment]
dwarf tier 1 in ekrund : -duraks gate -murgluks gits , then i just tried to do other one in mountbloodhorn (dwarfs) : -kron komar gap and -the siege of komar .  As i said before , when u kill the units u suppose to , nothing happen

**Comment by Evildoor** [comment]
This report will be used for the second PQ, changing the name. First one is already reported, #5222. Other ones should be reported separately.

**Comment by Soulwhisper** [comment]
8/8/2016 Patch
- Murgluk's Gits in Ekrund is now working.
