### ISSUE TITLE
Expedition Quartermaster - Tannebach's Doom camp Chaos Wastes

### ISSUE THREAD

**Issue by Thorgrumm** [WarEmu/WarBugs#6052]
Clicking on this NPC 'Dwarf Engineer' brings up the flightmaster map:
![expedition quartermaster](https://cloud.githubusercontent.com/assets/18247674/15275306/c8c3ec60-1abf-11e6-829f-64b0be51aadc.jpg)
.

**Comment by Evildoor** [comment]
Currently all Expedition NPCs act as flightmasters. Not sure if this is wrong (until LOTD gets implemented, ofc).

**Comment by Thorgrumm** [comment]
On live the expedition quartermasters only function was to be there for players to hand in LotD resources to assist in unlocking the zone. Actually getting to LotD was only ever done via the regular flightmasters, but as this is RoR it's totally up to you guys :)

**Comment by Evildoor** [comment]
No objections to my comment, so i'm closing this. When LOTD will be implemented and their function will be available, they would be fixed. I don't see any reason why anybody should bother now, since this issue is trivial.
