### ISSUE TITLE
RvR

### ISSUE THREAD

**Issue by kostn** [WarEmu/WarBugs#6054]
after the destruction of the first gate of the castle in Saphery . The second gate is not inactive , does not come from the target

**Comment by Evildoor** [comment]
> The second gate is not inactive , does not come from the target

What?

**Comment by kostn** [comment]
The second gate of the castle is not possible to take the target
sorry for my English. thanks to Google translator=))

**Comment by Evildoor** [comment]
> Google translator

Read the rules of the bugtracker. No google translator reports. If your English is not good enough then you don't report things.
