### ISSUE TITLE
Crafting Critical Bug

### ISSUE THREAD

**Issue by LittlefishSail** [WarEmu/WarBugs#6056]
Level 200 green fragments are producing white talismans on critical, so instead of a critical bonus, you get a critical penalty.  I've produced this bug using both Ballistic and Strength fragments, using materials that on a regular roll make a green +14 talisman, but on crit produce a white +12 talisman.   (Specific combination is level 1 box, level 200 green fragment, level 175 gold, essence, and curio.)

**Comment by Evildoor** [comment]
Possibly similar bug to #4501.

**Comment by Grywwy** [comment]
The same thing happend to me while using a blue 175 armor fragment, 175 essence and 200 curio and gold.

It created a green +101 tali usable at lvl 36...
