### ISSUE TITLE
Inevitable Power - Griffon Swoardsmen

### ISSUE THREAD

**Issue by sinderhella** [WarEmu/WarBugs#6062]
The step in inevitable power to kill the griffon swordsmen there are now swordsmen at the pq where it shows they are supposed to be on the map.
![sinderhella_007](https://cloud.githubusercontent.com/assets/19142979/15276096/a0ff5afc-1a92-11e6-8a8a-25bfad25dca2.jpg)

**Comment by Torquemadra** [comment]
Its fine on dev, should be ok after a server reboot

**Comment by sinderhella** [comment]
Seems to be working now, the screenshot from above was from the PQ area where the mobs were supposed to be.
