### ISSUE TITLE
rvr: taking damage beyond closed doors

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#6063]
opening this because i recall that aoe spell damage has been prevented to pass through obstacles.
praag, keep defense, inside keep, doors up so no los. if i get close to the door i start taking damage. looking in the combat log i see "reckless gamble" among the other hits.
wanted to take a screenshot but whole wb got a mass dc and on relog order was blockading the keep, so blame them if i'm not able to post any graphical evidence ;)

**Comment by Morksezstop** [comment]
afaik this is fixed for t3 but not for t4. Prolly soon fix will come

**Comment by Mazadun** [comment]
I have video of such thing happening to me as well at keep in BC.

https://youtu.be/tCiJTT8oNyQ
