### ISSUE TITLE
1st Order chapter in reikland - unfriendly peasants

### ISSUE THREAD

**Issue by Eusebeus82** [WarEmu/WarBugs#6065]
In the 1st chapter in Reikland there are a number of peasants which I don't think should be attack able by order. (not all the revolting ones, the ones in the camp)

![eusebeus_068](https://cloud.githubusercontent.com/assets/18599533/15277298/f5d822d8-1af7-11e6-99e7-46c3db727c50.jpg)
Thanks
Eusebeus

**Comment by Evildoor** [comment]
How it was on live?

**Comment by Eusebeus82** [comment]
These mobs in the pve camp were friendly to order on live. The content of this chapter is related to rebellion - so there are quite a lot of hostile to order Member of Empire type mobs in the chapter, but the ones in the camp were loyal and friendly.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
