### ISSUE TITLE
TOK - Leader of the Lost

### ISSUE THREAD

**Issue by Eusebeus82** [WarEmu/WarBugs#6066]
Chaos Mutant Calvin Lankdorf in Praag should grant the tome unlock, Leader of the Lost when killed and does not.

![eusebeus_064](https://cloud.githubusercontent.com/assets/18599533/15277327/aaed2966-1af8-11e6-963c-177dd3aceb39.jpg)

Thanks
Eusebeus

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
