### ISSUE TITLE
Quest: Due Recognition 

### ISSUE THREAD

**Issue by sinderhella** [WarEmu/WarBugs#6069]
The step for killing Lordling Kylar does not complete.

![daemonreaper_005](https://cloud.githubusercontent.com/assets/19142979/15277906/f2a33266-1ac4-11e6-8c08-f66c8b3086e9.jpg)

**Comment by Evildoor** [comment]
#4602?

**Comment by Ryanfawkez** [comment]
Not everything's about mindless slaughter. Read the quest description and you'll find you only have to find him.. "Search Dreamshade Forest west of Poisonblade Heath for Lordling Kylar."

**Comment by Damiel126** [comment]
Interacting with the dead Lordling Kylar does indeed finish the quest, but 'Kylar' the mounted high elf is still something that shouldn't be there. It seems like a no longer necessary workaround for an earlier issue with interacting with the Lordling Kylar body. The 'Kylar' high elf spawn should be removed.
