### ISSUE TITLE
The Vessel of Azorgaran

### ISSUE THREAD

**Issue by Zuyanna** [WarEmu/WarBugs#6070]
Quest is given by Pherix the Magus in the Citadel, objective is to use quest item Pherix's Orb on the npc Attendant Zeola Bayshadows then kill her.  Orb is not given, npc(22kx55kish) is not attackable, quest is not auto completed at quest giver.

**Comment by sioding** [comment]
Questobject is fine and attackable. The orb to weaken the Hero isnt implemented yet.
