### ISSUE TITLE
tok: basilisk

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#6072]
according to http://warhammeronline.wikia.com/wiki/Basilisk
killing npc "stinky" should unlock bestiary -> beasts -> basilisk entry.
in "black crag" , lair "sulfur caves" at 5k,8k is full of mobs named like "%basilisk" ("sulforous basilisk", "blasted basilisk" ) that probably are treated as "giant lizards" instead.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by zak68** [comment]
sorry, but seems there's something unaligned or misplaced.
on killing  a "sulforous basilisk" i got the message "you have encountered a basilisk" ,clicking on it showed the correct animal; but the bestiary does not report such discovery and killing more basilisk mobs affects the "lizard, giant" kill count.
![gabri_065](https://cloud.githubusercontent.com/assets/17765890/15418341/c1ec74b4-1e5e-11e6-9370-adefc86ec08b.jpg)
