### ISSUE TITLE
[KotBS] Strength Aura buggin out

### ISSUE THREAD

**Issue by Halhammer** [WarEmu/WarBugs#6073]
KotBS strength aura bugs out a lot recently, not applying to group mates. Switchin it off and on again makes it work. Kinda odd, only seems to be that one aura.

**Comment by Evildoor** [comment]
Does this happens with/without tactics affecting this aura?

**Comment by Halhammer** [comment]
Now that you mention it, I'm pretty sure it's happening with EA on.

**Comment by Marffff** [comment]
Same bug for "Stay Focused!" aura with "Focused Mending" tactic

**Comment by Kaelang** [comment]
Tested with and without tactic slotted, the aura still applies to group members. Could likely be a secondary kotbs aura as two don't stack.

Please re-open if issue persists on live environment.
