### ISSUE TITLE
Quest "The Fallen of War"

### ISSUE THREAD

**Issue by nohh** [WarEmu/WarBugs#6076]
1. "class" in desc.
2. Warcamp not specified.
![fallenwar](https://cloud.githubusercontent.com/assets/19315739/15280887/61b997ac-1b3e-11e6-8e72-a1e2d16ac8ba.png)

**Comment by Evildoor** [comment]
Class was already reported elsewhere. Warcamp? You mean, where to return with this quest?

**Comment by nohh** [comment]
Yes, where to return with this quest.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by fixfax86** [comment]
It does not reward Seal of the Exemplar as it used too, or was it Seal of the Paragon! is that on Purpose or is it a bug?
