### ISSUE TITLE
Savin' me hide [Black Orc]

### ISSUE THREAD

**Issue by footpatrol2** [WarEmu/WarBugs#6078]
Savin' me hide used to have a green wave animation identical to the ironbreaker's Vengeful Strike blue wave but it was green.

**Comment by footpatrol2** [comment]
Oh the green wave would apply to the entire group

**Comment by Evildoor** [comment]
Well, now i'll ask you - how it was on live, with proof? Similar wave is logical for toughness buffs, but not logical for toughness buff and magical resistance buff.

**Comment by footpatrol2** [comment]
Sorry looking SOOO many dps Black orc video's gah and they don't use the ability.

**Comment by Evildoor** [comment]
Video quality seriously hinders my ability to understand what's going on in this video.

However, i can safely say that effect should be playing on BO himself:
https://www.youtube.com/watch?v=1k4TCkVxt0E
4:45

Dunno about the group.
