### ISSUE TITLE
[Command][Pets][White Lion] /petname does not currently work.

### ISSUE THREAD

**Issue by sebid** [WarEmu/WarBugs#608]
Command: /petname xyz

Expected behaviour: By typing the command, a player can change the name of his/her pet.
Observed behaviour: Currently, the system is not implemented or not functioning properly, the command returning no feedback at all.

**Comment by Zaccar20** [comment]
Hey, just for information:
with /pet <name> you can chance the Name of the lion
but it just works after resummon and u have to do it after every login again!

**Comment by xyeppp** [comment]
The squigs do not work in the same way, even after resummoning them the name stays the same.
