### ISSUE TITLE
Rally master teleports to Zone 0

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#6080]
Binding the Book of binding to High elf chapter 19 rally master and using it teleports you to zone 0, a layer under Altdorf. Nothing can be done from there other than teleporting somewhere else with another book or using /Stuck
![screen shot 2016-05-16 at 08 59 41](https://cloud.githubusercontent.com/assets/18053736/15283819/35b7b1b4-1b45-11e6-88d8-aa6cf66a3433.png)

**Comment by saupreusse** [comment]
fixed.
