### ISSUE TITLE
War Shroud of the Mercenary missing 2% disrupt

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#6081]
According to https://docs.google.com/spreadsheets/d/13C0SbnhRDmmD_6DaxgoeBuDhM8yLy2igWktFQ6DkdKo/edit?pref=2&pli=1#gid=1441773204
they should have 2% disrupt 
![cimbo_009](https://cloud.githubusercontent.com/assets/16117730/15283963/a2dab102-1b4e-11e6-815d-bca9ac2cb18c.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
