### ISSUE TITLE
[Slayer] Annihilator Leathers Missing 11 Wounds

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#6082]
According to https://docs.google.com/spreadsheets/d/13C0SbnhRDmmD_6DaxgoeBuDhM8yLy2igWktFQ6DkdKo/edit?pref=2&pli=1#gid=1441773204
the Annihilator leathers should have 23 Wounds.

![cimbo_010](https://cloud.githubusercontent.com/assets/16117730/15284080/6cfe9714-1b4f-11e6-9995-2372e8c03f1f.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
