### ISSUE TITLE
T3: Heavy Hellfire Blaster - not deployable

### ISSUE THREAD

**Issue by Luicetarro** [WarEmu/WarBugs#6083]
Tried to place them at different pads in T3 - Dwarf and T3 - Empire.
Mid was working just fine.

No error-message, it just does refuse to work.

No screens, since there is nothing to see. It's me standing still, in front of a pad.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
