### ISSUE TITLE
Greenskin CH 19 PQ influence gain

### ISSUE THREAD

**Issue by Mudelncjasn** [WarEmu/WarBugs#6086]
If any dev can spare the time to fix "Ruins of Mingol Kurdak" PQ so we can gain influence from it would be much appreciated. Doesn't even have to be fully fixed... as long as you can gain influence for ch19 greenskin at some point. Thank you.

_This is the only PQ that is reachable for ch19 since Death Peak is inaccessible._

**Comment by Ryanfawkez** [comment]
Death Peak will be accessible in the next patch.

**Comment by Mudelncjasn** [comment]
That is great news! My next question is: will the PQ for ch19 work there?

**Comment by wargrimnir** [comment]
This PQ is working now.
