### ISSUE TITLE
Stealth being improperly broken

### ISSUE THREAD

**Issue by noisestorm** [WarEmu/WarBugs#6087]
![st](https://cloud.githubusercontent.com/assets/13032588/15286022/0ffa5c40-1b5b-11e6-96d7-af371fd4b995.JPG)

Just a random aoe Debuff that destealthed me. 
Same for a Throwing Dagger that i even dodged in stealth!

![dag](https://cloud.githubusercontent.com/assets/13032588/15286126/6c7c946a-1b5b-11e6-8f01-fd3388131c12.JPG)

**Comment by Evildoor** [comment]
#5166 may be related.

**Comment by grunbag** [comment]
Fixed already
