### ISSUE TITLE
Tome Unlock - It's in the bag

### ISSUE THREAD

**Issue by Sersaypygan** [WarEmu/WarBugs#6090]
According to a guide, this tome unlock would trigger after killing 6 young basalisks just outside the chp 16 greenskin camp, then talking to a goblin outside the fenced area (Name: Gubs). This does not work.

**Comment by Lheana** [comment]
In real 'Young Basilisks' should drop 'Lisk Meat'. Destro need to collect 6 of them, then talk to Gubs.
Btw 'Young Basilisks' count as Giant Lizard instead of Basilisks.

**Comment by Ryanfawkez** [comment]
Work-around made at the Library/Disciple's Assisant.

**Comment by Blaqwar** [comment]
'Lisk Meat erroneously drops off players after today's patch (I experienced it in T3, dunno bout other tiers).

**Comment by Lheana** [comment]
And 'Young Basilisks' don't drop the item 'Lisk Meat' required to provide this bestiary unlock.

**Comment by Luth-RoR** [comment]
Known issue, there was a mistake with PvE drops and it will be fixed soon.

**Comment by Lheana** [comment]
Young Basilisks still seem not to drop the 'Lisk Meat'.

**Comment by Lheana** [comment]
Meant to be fixed ?

**Comment by Luth-RoR** [comment]
I got the info that it should be fixed on the next DB push; does it still not work?

**Comment by Lheana** [comment]
Seems like yes, I killed some 'Young Basilisks' and did not have any 'Lisk Meat'. Same for https://github.com/WarEmu/WarBugs/issues/8738
