### ISSUE TITLE
High lvl potions dont give the right amount of bonus

### ISSUE THREAD

**Issue by Grywwy** [WarEmu/WarBugs#6091]
These 2 potions dont give the right amount of bonus.

![grywwy_039_russitrank](https://cloud.githubusercontent.com/assets/13614929/15289342/e3a04580-1b71-11e6-87e9-66aace89dd82.jpg)

![grywwy_044_widerstand](https://cloud.githubusercontent.com/assets/13614929/15289348/ec7315b6-1b71-11e6-8531-35b63def0d29.jpg)

I've tested it with the .getstats command before and after using them.

Before:
![grywwy_045_stats_davor](https://cloud.githubusercontent.com/assets/13614929/15289381/1eb3a5e0-1b72-11e6-901f-1c2f50079b3c.jpg)

After:
![grywwy_041_stats_danach](https://cloud.githubusercontent.com/assets/13614929/15289392/27c23214-1b72-11e6-9e0b-3cec30661f43.jpg)

I should have 617 toughness and 1649 armor according to the tooltip of the potions.

**Comment by Evildoor** [comment]
#5927
