### ISSUE TITLE
PQ  Slash and Burn Elf (Ch10) does not advance while killing stage mobs

### ISSUE THREAD

**Issue by helvalius** [WarEmu/WarBugs#6097]
In the PQ Slash and Burn, Elf Ch10, one needs to kill "Uthorin Ebonblades 0/150". Killing those mobs does not advance the PQ.

**Comment by Razielhell** [comment]
@Luth-RoR Fixed.

**Comment by Razielhell** [comment]
@Luth-RoR This is not fixed. Stage 1 doesnt count mobs.

**Comment by Paleolog77** [comment]
At stage 3 bosses not available to fight :(
![2021-11-01_16-42-04](https://user-images.githubusercontent.com/23325288/139681992-fed80776-9638-4b4e-a735-4889ee535117.png)

**Comment by lilimx** [comment]
Hey, 

thank you for your ticket. There is already an open ticket about the issue, so I will add this one.

**Comment by lilimx** [comment]
mentioned in: #19557
