### ISSUE TITLE
Bestial Token tome unlock - For the promise of power - not working

### ISSUE THREAD

**Issue by Nycta** [WarEmu/WarBugs#6099]
_Liche (Mound of Dirt/Scepter of Maggots) - For the Promise of Power

"CALEDOR @ 32, 22. E of the (D) Warcamp against a hill between two waterfalls is a Mound of Dirt. Click on it to get the Scepter of Maggots, then click on the scepter in your inventory. Finally, click the mound again for the unlock. NOTE: For (O) you'll need to come from the RvR lake, hug the hill to avoid the hero packs and drop down."_

Clicked on the mound, nothing happens.

**Comment by Ryanfawkez** [comment]
Added tome unlock to the Mound of Dirt. Item scripting is unsupported at this time.
