### ISSUE TITLE
"Report to General Breuer" displaying unusual text objective

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#61]
Another PvE quest where it is displaying the strange text in the objectives.

![report to general breuer](https://cloud.githubusercontent.com/assets/7492543/2916824/6b53f412-d6bf-11e3-84e4-701a612ea216.png)

**Comment by Reggaewaldo** [comment]
I confirmed this currently working as intended.

We can close the ticket.
