### ISSUE TITLE
Bestial Token tome unlock - Bigger Bray to Make Your Day - not working

### ISSUE THREAD

**Issue by Nycta** [WarEmu/WarBugs#6100]
_Beastmen, Bray Shaman (Kratkar/Dreadhorn Shaman) - Bigger Bray to Make Your Day
BEAST TOKEN
(D) & (O)
CHAOS WASTES @ 56, 25 or 61, 25 or 54, 15. Kill this L40-41 non-champ. He's a few feet off the W side of the road. If he's not up, there may be a Dreadhorn Shaman L40 non-champ there instead. I got the unlock for killing Kratkor, a friend got the unlock for killing the shaman later that day. NOTE: Five minute respawn. FURTHER: Mob also pops up on the side of the cliff E of the road, so look all around the Gor areas, not just the W side of the road.
NOTE: (D) MUST kill Kratkor. The beastmen are friendly._

Killed him three times as destro, an engineer also killed him and confirmed that you don't get the unlock on either side. There is a destro-friendly npc spawning next to Kratkar and is hostile to him. The aforementioned engineer pulled the npc and I was able to kill Kratkar with no intervenience but still got no unlock.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
