### ISSUE TITLE
Bestial Token tome unlock - Timber! - not working

### ISSUE THREAD

**Issue by Nycta** [WarEmu/WarBugs#6101]
_Treekin (Irebough Mossroot) - Timber!
BEAST TOKEN
(D) & (O)
EATAINE @ 49, 63 to 50, 48. Vanquish this L40 Hero that patrols S of Lilithorn Estate._

Killed him two times on my (lovely and cute) SH, got no unlock.

**Comment by Ryanfawkez** [comment]
Working fine on dev server. Assuming it's fixed in the next patch.
