### ISSUE TITLE
Choppa Ruin shoulders

### ISSUE THREAD

**Issue by M0rf** [WarEmu/WarBugs#6103]
Currently has 2% reduce armor pen, listed here https://docs.google.com/spreadsheets/d/13C0SbnhRDmmD_6DaxgoeBuDhM8yLy2igWktFQ6DkdKo/edit?pref=2&pli=1#gid=1535980708 as having 3% melee crit.

**Comment by Torquemadra** [comment]
Thats a mistake. Ruin was not altered from live with the exception of the correcting a few useless stats (ie WP on melee)

https://docs.google.com/spreadsheets/d/14yRcqyjWswYa7s1x2w90JBLcMyR2CMrblkof8AUXj3U/edit#gid=1535980708

**Comment by Torquemadra** [comment]
precise name next time please
