### ISSUE TITLE
PQ  Putrid Tar Pits, Dwarf (Ch 13) unable to pickup Despoiled Revenants to advance

### ISSUE THREAD

**Issue by helvalius** [WarEmu/WarBugs#6105]
In Stage 1 of  the PQ  Putrid Tar Pits, Dwarf (Ch 13) one is unable to pickup Despoiled Revenants to advance the stage to the next.

**Comment by Soulwhisper** [comment]
**@Luth-RoR Will not create a new ticket.**
- [ ] PQ implemented but in Stage 1 it needs 100 Revenants.There are only 10-15 in the area...need more of them.

**Comment by grunbag** [comment]
Fixed in next patch

**Comment by Razielhell** [comment]
This can close too.
