### ISSUE TITLE
Can't take elv rvr reward inluence

### ISSUE THREAD

**Issue by Tholkienn** [WarEmu/WarBugs#6107]
In DW, T4 emp, Renth Goldleaf, don't give rewards.
http://img11.hostingpics.net/pics/899502Aniomed073.jpg

**Comment by Evildoor** [comment]
Have you unlocked the relevant chapter in your ToK?

**Comment by nohh** [comment]
Have same issue
![goldleaf](https://cloud.githubusercontent.com/assets/19315739/15306534/00ad8f22-1bd4-11e6-9c13-996813bb1e9a.png)

**Comment by Tholkienn** [comment]
Yes evil
