### ISSUE TITLE
Heart of Strength quest Reikland chap 21 

### ISSUE THREAD

**Issue by Enwaaghman** [WarEmu/WarBugs#6110]
At the last stage of the quest,you should relise the 3 npc from their cages and then kill them but the WC champs kills the 3 enemies npc instead to leave them alive to be killed by player .

**Comment by Ryanfawkez** [comment]
Gotta make 'em neutral for other NPCs to stop attacking them.

**Comment by Enwaaghman** [comment]
thank you so much :)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by Enwaaghman** [comment]
:D
