### ISSUE TITLE
Quest - Sweets for the Souleater

### ISSUE THREAD

**Issue by Sersaypygan** [WarEmu/WarBugs#6112]
The quest requires you to kill Grimclan dwarves around chaos chp 16. No dwarves in the region grant credit towards the quest however.

**Comment by Ryanfawkez** [comment]
Quest says you need to kill the Veterans.

**Comment by saupreusse** [comment]
Quest works just fine. fixed a typos in the quest description though. can be closed

**Comment by StaH84** [comment]
Quest tooltip need correction to match the ToK description in stage where You need to kill deamonettes and gather Grimclan souls.
![Bjoorn_020](https://user-images.githubusercontent.com/18528095/54087057-97d05100-434f-11e9-9f63-e58bfd150add.jpg)
![Bjoorn_025](https://user-images.githubusercontent.com/18528095/54087059-97d05100-434f-11e9-9b75-dfeee54620be.jpg)
