### ISSUE TITLE
Black orc tactic You got nuffin' and swordmaster tactic bolstering enchantments - wrong scaling

### ISSUE THREAD

**Issue by roadkillrobin** [WarEmu/WarBugs#6113]
Healing scales depedning on how many mastery points you got on your active Warbellow
Dunno if this is deliberate.
.

**Comment by roadkillrobin** [comment]
![blokka_011](https://cloud.githubusercontent.com/assets/16356956/15304969/ad8c6c04-1bc0-11e6-81eb-c882afcefc31.jpg)
![blokka_012](https://cloud.githubusercontent.com/assets/16356956/15304970/adb4dc7a-1bc0-11e6-83f8-e6ef6ad8cbba.jpg)
![blokka_013](https://cloud.githubusercontent.com/assets/16356956/15304971/adbec2ee-1bc0-11e6-8d36-8185a8c23c49.jpg)

**Comment by Aleteh** [comment]
Healing skills do increase with mastery points, but have you tried putting on willpower jewelry/gear to see if it scales with that as well?

**Comment by Evildoor** [comment]
Tested, confirmed. I presume it's a bug, since the You Got Nuffin tooltip does not changes when you are putting points into other trees to level up their bellows (for example, Can Youz Hear Me Now? tooltip scales with Da Boss tree, even though it's a core tactic).
> Healing skills do increase with mastery points, but have you tried putting on willpower jewelry/gear to see if it scales with that as well?

No, it does not.

**Comment by roadkillrobin** [comment]
It does indeed scale withh willpower. 75 willpower increased healing from 64 to 67 per tick.

**Comment by Evildoor** [comment]
> It does indeed scale withh willpower. 75 willpower increased healing from 64 to 67 per tick.

Sure about that?
![bork_001](https://cloud.githubusercontent.com/assets/11015074/15335091/8018e9b4-1c79-11e6-803e-f9d1a5624fd3.jpg)
![bork_002](https://cloud.githubusercontent.com/assets/11015074/15335098/85c2a684-1c79-11e6-9b27-b1732c3508a2.jpg)

**Comment by roadkillrobin** [comment]
The 64 one might be due to overhealing...forgot to check.

**Comment by Luth-RoR** [comment]
From https://github.com/WarEmu/WarBugs/issues/9732
>[Swordmaster] Tactic - Bolstering Enchantments heal scales off blade enchantment level not mastery level

>I'm not sure if this is intentional but Ive found the tactic is weaker when using lower level blade enchantments. In order to get the ,max healing you have to use the blade enchantment with the most mastery points invested in.
