### ISSUE TITLE
[Stalkers quest] Head and Shoulder Above : no follow up quest

### ISSUE THREAD

**Issue by Fitonio** [WarEmu/WarBugs#6115]
After killing 20 Black Orc, i return to Rorik Copperkeg. But no follow up quest so I can't finish [Head and shoulders above] on Candead.

Regards.

C.

**Comment by Evildoor** [comment]
Would like a confirmation on this, since i've seen people doing this quest without problems.

**Comment by Fitonio** [comment]
Maybe it's just a bug on my toon.

Would you like a screen or some complement of information on the toon ?

**Comment by Evildoor** [comment]
By confirmation i meant "how it is with other characters?". Can you do it with your other characters? Can other players do this quest line normally?

**Comment by Fitonio** [comment]
The second part of the quest can just be available at lvl 25.
Escuse my question.

Really Sorry.

Regards.

C.
