### ISSUE TITLE
[ToK] Missing Entry - "Xobz Madgut" - Noteworthy Person

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#6116]
Xobz Madgut does not grant a Tomb of Unlock as he should.
![dungchewa_029](https://cloud.githubusercontent.com/assets/18690551/15308937/391f6746-1bb0-11e6-8c26-70c4fb4f2570.jpg)

**Comment by Lheana** [comment]
Still not working, but fixable I think :)
