### ISSUE TITLE
[ToK] Missing Entry - "Gorgor" - Noteworthy Person

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#6117]
Talking with Gorgor does not grant a Tomb of Knowledge unlock as it should.
![dungchewa_027](https://cloud.githubusercontent.com/assets/18690551/15308954/6e51b4e6-1bb0-11e6-873e-dd66a39cb367.jpg)

**Comment by Lheana** [comment]
Update this issue, still not working :)
