### ISSUE TITLE
[ToK] Missing Entry - "Gorsh Smashmouf" - Noteworthy Person

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#6118]
Talking to Gorsh Smashmouf does not grant a Noteworthy Person entry as it should.
![dungchewa_028](https://cloud.githubusercontent.com/assets/18690551/15308976/9d278476-1bb0-11e6-8cdb-63f9c3414acd.jpg)

**Comment by Ryanfawkez** [comment]
How is this a noteworthy person? he is not a rally master nor a kill collector.

**Comment by Frubertlives** [comment]
Don't know _why_ he is noteworthy, but he is listed as a noteworthy person in the ToK and is meant to trigger an unlock. http://warhammeronline.wikia.com/wiki/Ekrund/Noteworthy_Persons

**Comment by Frubertlives** [comment]
![dungchewa_040](https://cloud.githubusercontent.com/assets/18690551/15324916/7cf7905e-1c16-11e6-9712-7b76fc8a67a5.jpg)

**Comment by Lheana** [comment]
Most of the Noteworthy Persons are kill collector or rally master, but there are some that are neither of the two. Gorsh Smashmouf is one, and think it is fixable now :)
