### ISSUE TITLE
[ToK] Missing Entry - "A Tale by the Fire" - Destruction - Bestiary Unlock

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#6120]
Talking to the Forsaken Acolyte does not grant the "A Tale by the Fire" unlock as it should.
![dungchewa_030](https://cloud.githubusercontent.com/assets/18690551/15309096/99301c42-1bb1-11e6-813e-9125c6bddc87.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
