### ISSUE TITLE
[Quest] A Weapon of Doom

### ISSUE THREAD

**Issue by moondoggcavalier** [WarEmu/WarBugs#6121]
![moondogg_026](https://cloud.githubusercontent.com/assets/15387904/15309099/aab7271c-1bb1-11e6-88ae-6bf0702828af.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by moondoggcavalier** [comment]
The Escaped Engineer is now present but he is only level 1
![moondogg_034](https://cloud.githubusercontent.com/assets/15387904/15416814/5a611ed0-1e1d-11e6-8ee8-1866c627fe8c.jpg)

**Comment by saupreusse** [comment]
hes now lvl 30

**Comment by NorKalli** [comment]
long since fixed
