### ISSUE TITLE
[PQ] Greenskin Tier 1 - "Goldfist's Hole Recovery" Stage 1 Broken

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#6122]
Kill counter for Irontoe Thunderer is not working in "Goldfist's Hole Recovery PQ"
![dungchewa_031](https://cloud.githubusercontent.com/assets/18690551/15309130/f38cb9a2-1bb1-11e6-9570-42c78ce5fe24.jpg)

**Comment by Evildoor** [comment]
#5547
