### ISSUE TITLE
[PQ] Greenskin Tier 1 - "Broketoof Camp" Stage 1 Broken

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#6123]
Interacting with the Orc Flag does not cause the PQ "Broketoof Camp" to progress.
![dungchewa_032](https://cloud.githubusercontent.com/assets/18690551/15309160/3b0f148c-1bb2-11e6-8542-8905ca5113ed.jpg)

**Comment by Evildoor** [comment]
#5547
