### ISSUE TITLE
[PQ] Greenskin Tier 1 - "Raider's Haven" Stage 1 Broken

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#6124]
Kill counter for Red Raider Robber is not working in "Raider's Haven" PQ.
![dungchewa_033](https://cloud.githubusercontent.com/assets/18690551/15309179/6ca9f228-1bb2-11e6-95e1-86e33be066c8.jpg)

**Comment by Evildoor** [comment]
#5547
