### ISSUE TITLE
[PQ] Greenskin Tier 1 - "Sharpthorn Wud" Stage 2 Broken

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#6125]
Kill counters for "Tenacious Spite" and "Vengeful Dryad" are broken for the "Sharpthorn Wud" PQ
![dungchewa_037](https://cloud.githubusercontent.com/assets/18690551/15309201/bb7049c0-1bb2-11e6-8bae-dd7c4d22b30d.jpg)

**Comment by wargrimnir** [comment]
Should be fixed.
