### ISSUE TITLE
Loading screens kick to main menu.

### ISSUE THREAD

**Issue by Aruis100** [WarEmu/WarBugs#6126]
This glitch happens every time i try to fly anywhere. It loads like normal but then it boots me to main menu. It loads nearly all the way through, and normally right when i would load in, the icon stops moving and i get put right back to the main menu, and this persists even when i then try to log in normally as well.  The only workaround i have found is typing /stuck a ton while first trying to log in, and sometimes i get sent to Norsca and that loads in for me. A couple GMs tried porting me around, and that works sometimes, but i end up back at the main menu half the time after the same load and icon freeze. I did have the chance to find out that T1 players will follow a rank 40 chicken into certain death if i call a charge over /say with enough capitals and exclamation marks thrown in.

**Comment by Aruis100** [comment]
Update: I tried different graphic settings and a new character but they didn't work either. Typing /reload and /stuck, while /reload will make the load pause, then start again, it has no affect on getting logged in or zoned properly.

**Comment by KonradCurze** [comment]
I'm having the same issue on my Marauder..

**Comment by Aruis100** [comment]
Keep trying commands, idk if it was chance but .unlock followed by /stuck seemed to have worked even though it didn't earlier.

**Comment by KonradCurze** [comment]
.unlock followed by double /stuck allowed one loadscreen to go through and i got to starting zone, after that I headed to nearest flight and tryed to fly and loadscreen,charscreen again.

**Comment by Evildoor** [comment]
Wrong place. Read the rules of the bugtracker.
