### ISSUE TITLE
tok: wolf

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#6130]
according to 
http://warhammeronline.wikia.com/wiki/Alpha_in_Bits
killng the wolf Sorenna in Talabecland, located around 46k, 8k, should unlock bestiary->beasts->wolf ; it doesn't work and Sorenna spawns twice, lvl 26 and lvl 25.

**Comment by Ryanfawkez** [comment]
Type ans subtype are fine, the unlock itself cannot be fixed yet as Beastial tactic fragments cannot be unlocked yet. Removed the double spawn.

**Comment by Lheana** [comment]
This unlock is still not working : killing Sorenna does not provide the unlock "Alpha in Bits". But I think it can now be fixed.

**Comment by Luth-RoR** [comment]
Don't know if the ToK is bound to the tactic fragment.

**Comment by Lheana** [comment]
However killing Lishka in High Pass provides the unlock for destro.

**Comment by Lheana** [comment]
I don't know why but killing Lishka as order does not provide the unlock.

**Comment by Lheana** [comment]
Killing Lishka still does not provide the unlock 'Alpha in Bits', order and destruction side. Sorenna still provides it.

**Comment by Lheana** [comment]
Fixed
