### ISSUE TITLE
npc: lishka

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#6131]
there are two wolfs named "lishka" in high pass @ 47k,51k, lvl 25 (wrong) and lvl 26 ; however this mob grants the "wolf" bestiary entry, as described in http://warhammeronline.wikia.com/wiki/Alpha_in_Bits

**Comment by Ryanfawkez** [comment]
https://github.com/WarEmu/WarBugs/issues/6130

**Comment by avenflar** [comment]
Not sure if the fix has been applied or not, but the wolf is still spawned twice

**Comment by saupreusse** [comment]
fixed.
