### ISSUE TITLE
Dwarf Chapter 22 Rally point

### ISSUE THREAD

**Issue by mrSVS** [WarEmu/WarBugs#6135]
NPC Rally Master Gav Hallmundr: "Set Rally Point" function don't work.
Display error:
"ERROR: Unknown Rally point NPC (6990)"

P.S.: No flymaster at most PVE chapters

**Comment by Evildoor** [comment]
One issue per problem. Lack of flightmasters is not a bug.

**Comment by saupreusse** [comment]
rally point is fixed in the next patch
