### ISSUE TITLE
Dread-Woven Grudgecoat

### ISSUE THREAD

**Issue by Thorgrumm** [WarEmu/WarBugs#6137]
'Dread-Woven Grudgecoat' is a BoP item level 30, although other back accessories in the 'Dread-Woven' range are not BoP and are item level 25:

![dread-woven back](https://cloud.githubusercontent.com/assets/18247674/15319049/da2b99f0-1c20-11e6-9feb-a91ccae9f2a3.jpg)

**Comment by Evildoor** [comment]
How it was on live?

**Comment by saupreusse** [comment]
fixed in next patch
