### ISSUE TITLE
[Quest] Misplaced Rivalries

### ISSUE THREAD

**Issue by moondoggcavalier** [WarEmu/WarBugs#6138]
It shows that the quest is complete before finishing the quest. However clicking complete does not reward anything. 
![moondogg_030](https://cloud.githubusercontent.com/assets/15387904/15319991/0890e004-1bfc-11e6-9c2d-8bcc58469d1e.jpg)

**Comment by noisestorm** [comment]
It does for a quite a few quests. But as your ToK shows you you have no step completed yet.. Just a visual that randomly occurs afaik and im not even sure that can be fixed?
@Torquemadra ?

**Comment by Luth-RoR** [comment]
Is this a custom quest (made by the RoR staff)?

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/5356

**Comment by NorKalli** [comment]
set correct completion requirement to kill Dragon Shadows

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
