### ISSUE TITLE
PvP Area Zone - Elf (Chrace [T1]) 

### ISSUE THREAD

**Issue by AndmeA** [WarEmu/WarBugs#6139]
Hello,

In the QP Gon'Seraph (Chp 3 - Elf) which not work like alls QPs in this area (thats not the point) we're going to be in RvR statut when we reach the "center" of the camp (15300 - 6300 +/-) so we turn into chicken and die sadly ... ^^ 

Its not really near the RvR area, that's why i report it as a "bug" :) 

Edit : it happens too in Tor Achare PQ (24k - 20k +/-) ^^ That's rude for my DK :p

**Comment by saupreusse** [comment]
fixed soon...
