### ISSUE TITLE
Trading Destroyed Item

### ISSUE THREAD

**Issue by Coppercross** [WarEmu/WarBugs#614]
In an attempted trade with the destruction player "Death" we initiated a trade of one event cloak for another with different stats.  I received her cloak and my cloak left my inventory.  However, she claims that it never made it into her inventory.  I would suggest holding off on any trades until this issue is fixed.

**Comment by Elvenalthur** [comment]
I've had no issues with any peer to peer trades. Worked every time.

**Comment by Coppercross** [comment]
I'm glad you haven't had any issues and I hadn't either until this one instance.  However, there is still a sorceress running around, missing a cloak! :)

**Comment by Evildoor** [comment]
Have not heard about such problems apart from this report, so i suppose it was a one-time bug and this can be closed.
