### ISSUE TITLE
ToK bugged entry

### ISSUE THREAD

**Issue by Morkhill** [WarEmu/WarBugs#6140]
In Bestiary/Animals/Beasts, regarding the wolves achievements, it seems that the "picking up the pieces" is broken and does not deliver the proper achievement with Kill Collector "Tosha Schreiber" in Chaos Ch.7 warcamp in Ostland. Killed about 200 "Bloodfang Wolves" for a required amount which is around 70.

**Comment by Evildoor** [comment]
#5999
