### ISSUE TITLE
Dark Elf chapter 19 BG influence rewards

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#6142]
It seems that this chapter has the same problem as T3 RVR had - BG items have no restriction to BG and are offered to other classes (for example, Grimbraces of Upset Ithilmar, Pauldrons of Upset Ithilmar, Gateclaimer's Greaves and Gateclaimer's Hauberk are offered to my BO), which can possibly prevent you from selecting some items for your class.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
