### ISSUE TITLE
[NPC] High Elf bodyguards sleeping on the job

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#6143]
Some of the champion-level mobs on the bridge leading into the HARD PQ in Ch 22 Dark Elf.

One NPC appears to be lying down, while another stands at a 45 degree angle.

![abogroupheals_002](https://cloud.githubusercontent.com/assets/15091486/15325517/d04db652-1c89-11e6-8168-9e932337c20b.jpg)

**Comment by Meralors** [comment]
Fixed, back on duty. Live next patch.
