### ISSUE TITLE
Auction not showing cheapest>most expensive

### ISSUE THREAD

**Issue by Clawfinger84** [WarEmu/WarBugs#6144]
Instead of having auctioneer showing cheapest to highest, the cheapest items get hidden in nothingness

Im for instance selling arboreal resin for 5s cheaper than what's listed as cheapest, but my sell post does not show up at all, because window favors to show the things that cost the highest instead, and search query get's limited prior to getting to show those items listed the lowest. no matter the settings i use, it's the same item anyhow!

**Comment by Evildoor** [comment]
This is caused by #1821.
