### ISSUE TITLE
[Quest] The Sport of Princes

### ISSUE THREAD

**Issue by moondoggcavalier** [WarEmu/WarBugs#6146]
![moondogg_032](https://cloud.githubusercontent.com/assets/15387904/15330615/a8da5d22-1c2b-11e6-9d6d-cedd587378fb.jpg)

**Comment by Ryanfawkez** [comment]
NPC missing from the database. Recreating him.

**Comment by moondoggcavalier** [comment]
Abandoned the quest and picked it up again, still an invalid object.
![moondogg_039](https://cloud.githubusercontent.com/assets/15387904/15438093/8be566ac-1e98-11e6-881c-14bcba3de89d.jpg)

**Comment by NorKalli** [comment]
long ago fixed
