### ISSUE TITLE
Keep loosing log book quests

### ISSUE THREAD

**Issue by mignon29** [WarEmu/WarBugs#6148]
Hi, since few days, i lost my quests in the log book, the quests are still in progress but no show in the book and in the map, when i try to do the objectifs, nothing happened. I waited for the next server restart (i think 3 times), and still nothing.

**Comment by Evildoor** [comment]
#2001?
#2357?

**Comment by mignon29** [comment]
looks like " Game DCing to char select and quests completely wiped #5857" or #2001 but without the time past in game (3 days, sounds normal)

**Comment by Evildoor** [comment]
Then it's already reported. Closing.
