### ISSUE TITLE
Uneven numbers in Scenarios

### ISSUE THREAD

**Issue by Shadowgurke** [WarEmu/WarBugs#6152]
In Scenarios we fought a weird number of people today. Happened both in Isha and in Tor Anroc. We (Destro) were two groups. Order was 17 people both times. The cap for these Scenarios is two groups as far as I am aware.

**Comment by Luth-RoR** [comment]
Shouldn't be possible due to matchmaking code afaik. 
17 people in actual numbers or in the scenario screenshot?

**Comment by Zealote** [comment]
I thought it was well-known that SCs are sometimes imbalanced numbers-wise. I guess it's to do with people delaying joining and/or leaving the queue entirely, as you do usually get more people later on, but by that point it's often too late/nearly finished.

(On a side note, it's prob already known but on AoR it used to end SCs that had X degree of unevenness, after warning on-screen that it'd finish after some given time if more didn't join.)

**Comment by Luth-RoR** [comment]
Afaik if you hit join and the scenario is already "full", nothing happens. But needs confirmation.

**Comment by Kaelang** [comment]
This is working as intended on live versions of RoR.
