### ISSUE TITLE
Castbar

### ISSUE THREAD

**Issue by Kuroiwashi** [WarEmu/WarBugs#6153]
The castbar for BO flag capping, the same for SC flag capping is broken, the effect works but you dont get teh 10 sec cast bar, so people who dont know what is happening arent capping due to this UI error

**Comment by Evildoor** [comment]
#5918?

**Comment by Kuroiwashi** [comment]
It's not only Scenarios flag or ball (Morkain Temple/Tor Anroc), but in oRvR the flag also has the same UI/visual bug, I put it as castbar, since that's the thing it's missing, is not that the object is not able to be interacted with, is the UI portion of the interaction that's not working properly

**Comment by Evildoor** [comment]
So yeah, it's #5918.
