### ISSUE TITLE
[Strength In Numbas]

### ISSUE THREAD

**Issue by roadkillrobin** [WarEmu/WarBugs#6154]
Doesn't generate morale of your Squig.

**Comment by ozarmidrashim** [comment]
Require proof that the pet was considered a groupmate for the purpose of this tactic.

**Comment by roadkillrobin** [comment]
Well it's considered a "groupmate" when it comes to other abillties like groupheals, covenants, chosen auras, tooth of tzeentch etz.

**Comment by roadkillrobin** [comment]
I'm not sure how I can add a confirmation on this, but i'm 90% sure it's how it worked on live.

**Comment by Evildoor** [comment]
Find a video from live where this tactic procs off squig.

**Comment by Evildoor** [comment]
No confirmation, closing.
