### ISSUE TITLE
TOK - Song and Dance unlock/Breaking Point quest (no mob)

### ISSUE THREAD

**Issue by Eusebeus82** [WarEmu/WarBugs#6156]
As detailed below in the Tome Titan section, the quest Breaking Point should spawn the mob Bloodsong, for the unlock. Can the mob Bloodsong be simply placed nearby so that the quest and the unlock can be completed.

![eusebeus_072](https://cloud.githubusercontent.com/assets/18599533/15339020/4e929e16-1c7a-11e6-9c35-b3b5c3dd7f0f.jpg)

thanks

Phil

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
