### ISSUE TITLE
Demonsoul

### ISSUE THREAD

**Issue by Puzur** [WarEmu/WarBugs#6157]
Can the staff Demonsoul please get alternate appearance? The other T4 weapons have alternate appearance.
![nizzo_001](https://cloud.githubusercontent.com/assets/19417243/15339216/2f2f1366-1c38-11e6-98e8-1d460d473954.jpg)

**Comment by NorKalli** [comment]
@Torquemadra was this ever addressed/fixed?

**Comment by sioding** [comment]
checked on dev - alternate appearance is available and works like a charm - close
