### ISSUE TITLE
"Dominion" gear has wrong level requirement

### ISSUE THREAD

**Issue by Thorgatin** [WarEmu/WarBugs#616]
Some of the "Dominion" weapons that are purchasable at the vendors in the altdorf war quarter, have a wrong level requirement:

Level 14 / RR 9 correct:
![runhilde_009_crop](https://cloud.githubusercontent.com/assets/8567481/6212005/96e7001e-b5e0-11e4-8d4d-f7ed7565e1ad.jpg)

Level 9 / RR 9 wrong:

![runhilde_008_crop](https://cloud.githubusercontent.com/assets/8567481/6212020/d42cdd2c-b5e0-11e4-9897-73ebfdc27618.jpg)

I don't know if it's the same for destro.

**Comment by andytomlins** [comment]
The higher level dominion gear is correct from live when t1 was lvl15. I think it was reduced to use with the lvl12 cap.

**Comment by ozarmidrashim** [comment]
The two Dominion versions of an item were identical in the DB (with stats expected of Rank 14 gear), except that the rank requirement for the pieces earlier on in the DB matched the renown rank requirement of 9. I assumed this to be a mistake and have adjusted the requirement for the lower-level copies, and removed them from the vendor. Equipped copies of the adjusted items should be unequipped automatically from players.

**Comment by Thorgatin** [comment]
For a knight, the low level dominion gear seems to be completely missing (except one sabre). No swords, no shield. 
For the IB and SM only the low level shield + 2hander are missing (dunno if there should be any).

**Comment by Thorgatin** [comment]
Last patch fixed Dominion weapons for the order side, but not for destruction.

**Comment by ozarmidrashim** [comment]
Whoops. Fixed for next.
