### ISSUE TITLE
Quest: Bearing A Grudge

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#6162]
Quest rewards need fix, usually other class items are broken too.
Also a R5 heal pot, woo.

http://i.imgur.com/tXpk2qn.png
Metal Plated Mane
should have +21 WND
http://war.mmodb.com/items/metal-plated-mane-115661.php

**Comment by Ryanfawkez** [comment]
Gave all rewards +21 wounds. Made the rank 5 potion a level 10 potion.
