### ISSUE TITLE
Massive loot bags not opening

### ISSUE THREAD

**Issue by Oplats** [WarEmu/WarBugs#6164]
Got a massive loot bag from destro DW PQ for ruin set couple of days ago (not mailed, I won the bag and went and got it directly from the chest), forgot to open it. I accidentally sold it to a vendor and bought it back straight away but then I was unable to open it. I click it but it remains unresponsive. I can move it around my inventory but can't open the loot bag anymore. Tried selling it again and buying the bag back but that did not worked either.

**Comment by Evildoor** [comment]
#5392
