### ISSUE TITLE
Quest: A Matter of Scale

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#6165]
60xp, something is wrong here. That's not a short trip to complete for the quest.

http://i.imgur.com/hrTXkqd.png

**Comment by Ryanfawkez** [comment]
This is a cultivation quest. It's supposed to award a specific type of seed as I recall from live.

**Comment by wargrimnir** [comment]
http://war.mmodb.com/quests/a-matter-of-scale-1263.php

Guess it's the same as live then.

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 15.06.2019
