### ISSUE TITLE
[Icon] Precursors Pummelers wrong icon

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#6166]
The icon for precursors pummelers shows a pair of boots, but the description and name are for the marauder gloves. I am unsure if the appearance is correct (not high enough level at this point).
![rezalevadgib_004](https://cloud.githubusercontent.com/assets/13975292/15345291/5365836a-1c73-11e6-9cf9-e787bb0573be.jpg)

**Comment by Meralors** [comment]
Fixed item icon.
