### ISSUE TITLE
Quest: Missions

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#6169]
http://i.imgur.com/EvExTRt.png Bad stats on both items
Skullbacked Mailcoat
20 STR
5 WND

http://i.imgur.com/SQgmP8Y.png
Mailcoat of the Purifier
19 STR
6 WS

http://war.mmodb.com/items/skullbacked-mailcoat-108887.php
http://war.mmodb.com/items/mailcoat-of-the-purifier-101136.php

**Comment by Meralors** [comment]
Fixed.
