### ISSUE TITLE
3 more epic quest T4 

### ISSUE THREAD

**Issue by Areanda** [WarEmu/WarBugs#6171]
gave ya a link so u can see the other 3 epic quest neither of em work tried em all.
http://stuntystomper.blogspot.nl/2008/11/epic-quests-for-fun-gear.html

**Comment by Torquemadra** [comment]
will get to at some point, thanks

**Comment by Lheana** [comment]
I close this as some of these epic quests are already available, and the others will be implemented one by one in the next months
