### ISSUE TITLE
Tuff Hide Greaves missing model [Mt. Bloodhorn Quest reward]

### ISSUE THREAD

**Issue by Krumlok** [WarEmu/WarBugs#6174]
It's a quest reward from Timber!, a quest in da War Maka, T1 Mt. Bloodhorn. 
Look.
![sin titulo](https://cloud.githubusercontent.com/assets/14275335/15353315/bca61b44-1ce8-11e6-9083-3e667eb0bb1b.png)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
