### ISSUE TITLE
T1 Chalice

### ISSUE THREAD

**Issue by Ghostwarrior1** [WarEmu/WarBugs#6177]
hello there i just saw that t1 chalice dont give any Soul essence cuz it should right ? just asking
![ss 2016-05-18 at 01 15 03](https://cloud.githubusercontent.com/assets/15137357/15356746/f37f1564-1cfa-11e6-9194-0005d446c4db.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by Ghostwarrior1** [comment]
ohh okey ty  looking forward to the patch notes :D
