### ISSUE TITLE
Sigmars Grace Buff awards RP/XP

### ISSUE THREAD

**Issue by Maddox911** [WarEmu/WarBugs#6180]
Found this issue to be reproted already and closed as intentional but this doesnt happen only after RVR combat. It happens literaly all the time you are in group, at start of scenarios before any pvp happens etc. You keep getting XP/RP ticks for just casting it, that cant be intentional.

**Comment by Evildoor** [comment]
> Found this issue to be reproted already and closed as intentional

Go and read the rules of the bugtracker.

After that, if you still think that something is wrong - make a video where you enter the game, join a group which had not participated in any PVP, use Grace and get XP/RP, and post it in existing ticket.
