### ISSUE TITLE
[Marauder] Mutating Release ability 

### ISSUE THREAD

**Issue by Larhis** [WarEmu/WarBugs#6184]
Im used Mutating Release and it remove my existing snare debuff, but immiunity didint work, got snare debuff even was buffed wifh Mutating Release.

**Comment by Evildoor** [comment]
You got snared by what?

**Comment by Larhis** [comment]
Dont know. Prob. from wep. ability proc.

**Comment by Evildoor** [comment]
No confirmation, closing.
