### ISSUE TITLE
Quest: Wolfbane

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#6187]
This quest giver is located in Ostland, ~18-19 area, gives a quest to kill 25 Forest Gnawer wolves in Nordland/Norsca.

There are R19 wolves in the area named Forest Prowler that would be far more appropriate if this could be tweaked slightly. Otherwise it really doesn't make any sense.

**Comment by LadyCereus** [comment]
Agreed the Wolfbane quest seems odd.  The other quest the same NPC gives asks you to kill spiders for silk, but none of the spiders in the area drop any.  Quest name is Spidersilk, quest giver is Roderic Grace.

**Comment by thorbolt80** [comment]
There is one forest gnawer in Nordland at 36.18 So weird that the quest is given in Ostland at 49.41.

**Comment by Lheana** [comment]
In fact there are 3 spawns of Roderic Grace:
- One in Nordland who is meant to give quest Wolfbane
- One in Ostland who is meant to give quest Spidersilk
- One in Talabecland who is meant to give quest Testing the Waters
I set the quests that way.
Also more precisely about Wolfbane, the quest is meant to include any wolf in Nordland and Norsca, which explains de high count. Nevertheless we can not set the quest that way, thus only Forest Stalker will count toward the quest and reduced the count needed.

**Comment by sioding** [comment]
fixed with patch from 05.11.2018
