### ISSUE TITLE
Quest: Sanctified Ground

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#6189]
More broken items
http://i.imgur.com/V5LXmjj.png
http://i.imgur.com/0Q7QMnJ.png
Retriever's Mane
+27 STR (probably)
Lawman's Mane
+27 WND

http://war.mmodb.com/items/lawmans-mane-98181.php

Retriever's gear is not listed at all in mmodb, the next level higher is R18 with slightly more armor and +29 STR flat, I would hazard a guess based on the itemization patterns Retriever's would be the primary class archtype stat (STR/BAL/INT/WIL) at a +27 bonus.
http://war.mmodb.com/items/stonefast-mane-103716.php

**Comment by wargrimnir** [comment]
Door to the temple needs to be openable as well.
coords 107 1074309 936837 6836

**Comment by Evildoor** [comment]
Have you checked closed reports about these quests? People already tried to report the closed door.

**Comment by wargrimnir** [comment]
There's the cemetery gates, which were fixed. Then there's the Monastery door at the top of the hill which the coords are for. If the door ID is missing (Kushido's note on it), we could still get some levers to TP back and forth in order to finish the quest. Also, I believe their method for finding ID's via the geom files had improved since Kushido was working on it, but maybe I'm getting things mixed up.

I am aware that Torque hid a copy of the mob nearby, but there's still a handful inside. Figured I would just make a note about since the quest rewards were broken if anyone wanted to take another try at fixing it. Has been a couple months.

**Comment by G33z3r** [comment]
The temple door opens and Tomas is inside.  A friend and I killed him last night.  The quest now shows as complete but there is no place to turn it in.  We were unable to click on the glowing pieces of the statue to restore it.  When you mouse over it the hand appears but clicking on it does nothing.  My friend also tried /pray since the quest text mentions praying to restore it but that didn't work either.

**Comment by Luth-RoR** [comment]
Additional info from https://github.com/WarEmu/WarBugs/issues/9174:

>After you kill "Thomas the Champion" in the Grim Monastery in Ostland (59k/50k) you're supposed to "restore the desecrated statue of Sigmar through fervent prayer". Although the item that you're supposed to use (a big flame symbol at the bottom of the Sigmar statue labelled "Desecrated Monastery") is there, you can't actually use it and therefore can't turn in the quest. 
This is the object that's supposed to finish the quest:

![alathorn_005](https://cloud.githubusercontent.com/assets/25819236/23091939/146c3870-f5c1-11e6-9908-29703c60d49d.jpg)
