### ISSUE TITLE
[Crafting] Bugged talisman result ?

### ISSUE THREAD

**Issue by cONfUSiOUz** [WarEmu/WarBugs#6190]
Using **200** dust/curio, 175 magic essence and Strand of Azure Gloom (175 blue WP fragment) critical success resulted in: Potent Talisman of the Resolve (r36 green +16 WP).

Using **175** dust/curio, 175 magic essence and Strand of Azure Gloom (175 blue WP fragment) critical success resulted in: Superior Talisman of Purpose (r32 blue +19 WP).

Is this a bug or how it is supposed to work for now.
![deviante_003](https://cloud.githubusercontent.com/assets/19440625/15379717/4ac7f564-1d70-11e6-9cb5-dd307986de8f.jpg)
![deviante_006](https://cloud.githubusercontent.com/assets/19440625/15379723/5730a792-1d70-11e6-84ac-2e5b793f6ae4.jpg)

**Comment by Evildoor** [comment]
#4501 
#6056
