### ISSUE TITLE
t2:rvr zone

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#6191]
chickened on arrival from t4, "walked" all the way to chap6 wc, relogged and got chickened again; but why, since in t1 it works?

**Comment by Evildoor** [comment]
Because t2 is screwed somewhere. Zone name, chapter name, map screenshot.

**Comment by zak68** [comment]
marshes of madness
![gabri_061](https://cloud.githubusercontent.com/assets/17765890/15387120/91cadf9a-1dab-11e6-8428-f74e18ca8eb5.jpg)

**Comment by Evildoor** [comment]
#5780
