### ISSUE TITLE
[Quest] Heart of strength

### ISSUE THREAD

**Issue by Ktaan** [WarEmu/WarBugs#6197]
Destruction, Ch.21, Reikland

You should kill NPCs in cages but friendly for your realm NPCs insta kill them and you can't progress further in quest.

![6c13a8ff4f8b86f13a94df2e9005e759346d3fb4a3bc7f275a pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/17799901/15396448/dafcdfcc-1de4-11e6-9c59-c3015bc165e8.jpg)

**Comment by Evildoor** [comment]
#6110
