### ISSUE TITLE
Nordland : Hard PQ: pillager's approach, Not working and Flagging for PVP

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#6198]
Entering the area for this quest flags you for PVP. The quest is also stuck and doesn't show the requirements. No influence is granted on kills.

![urmig_000](https://cloud.githubusercontent.com/assets/18053736/15397528/70db30aa-1dd8-11e6-8c1f-856bb017387a.jpg)

**Comment by Evildoor** [comment]
#4394
#6048
Also, one report per problem.
Also, i don't know what this map is supposed to show, apart from the fact that it's in Nordland.
