### ISSUE TITLE
"Arming the Militia" Cannot interact with bodies

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#62]
Cannot interact with the bodies to claim the needed weapons to complete the quest.

This quest is done at the PQ "The norse are coming!" in Nordland (Order side).

![arming the militia](https://cloud.githubusercontent.com/assets/7492543/2916996/2d299320-d6c1-11e3-8b1c-7453258c7eee.png)

**Comment by Evildoor** [comment]
This quest works now.
