### ISSUE TITLE
Shadowlands: PQ: Mirelen, cannot be completed

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#6200]
The quest does not show any requirement and is stuck
Killing ulthorin seekeers does not grant any influence.

![urmig_005](https://cloud.githubusercontent.com/assets/18053736/15400218/a1d8b81c-1de2-11e6-8d2c-a14c067a8a85.jpg)
http://warhammeronline.wikia.com/wiki/Mirelen

**Comment by wargrimnir** [comment]
Fixed in next.
