### ISSUE TITLE
Incorrect RVR Area: Barak Varr

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#6201]
The area between Dwarf Ch 7 and Bar Dawazbak PQ (south) flags you for RvR

**Comment by Evildoor** [comment]
Map screenshot, please.

**Comment by MerryGitmas** [comment]
![screen shot 2016-05-21 at 13 47 30](https://cloud.githubusercontent.com/assets/18053736/15448470/995795ae-1f5a-11e6-89f7-9216937d5eb6.png)

![screen shot 2016-05-21 at 13 47 54](https://cloud.githubusercontent.com/assets/18053736/15448474/a9dabce4-1f5a-11e6-92b4-d0af89d81b64.png)

**Comment by saupreusse** [comment]
fixed in next patch
