### ISSUE TITLE
Barak Varr: Dawazbak PQ (order side) cannot be completed

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#6202]
The quest is stuck and shows no requirements. Coordinates on the image
![urmig_006](https://cloud.githubusercontent.com/assets/18053736/15401046/bd1be8d0-1de5-11e6-99e5-905c90aba0d6.jpg)

**Comment by Evildoor** [comment]
It's mentioned in #5547 as a greenskin one, but i presume that you mean its dwarven part.

**Comment by MerryGitmas** [comment]
Yes i am on Order.

**Comment by wargrimnir** [comment]
This PQ is working now.
