### ISSUE TITLE
WP | Tactic "Intimidating Repent" bugs all other active tactics

### ISSUE THREAD

**Issue by Sosaqa** [WarEmu/WarBugs#6203]
First of all i want say, that my english skills not good but i will try.

It starts after i was DCed. I farm scales for armor pots. Then i relog to game back, after few mins i noticed that my tactics not properly working, they dont work anymore. I had conversation with GM Ayrion, he tried help me, we disabled all add-ons, did few relogs and etc. Nothing what help me.
I notice 2 strange things:
1. I see this error each time after relog and then i try to change my tactic panel 
   screen - http://puu.sh/oXLpb/9894d7b499.jpg
After this error all tactics not working at all.

2. After each relog my default tactic panel is 4. And its totally empty. Looks like game somehow forced lock at this panel(assumption). And after i try change panel and i see new panel, but its stil on forced 4 (assumption). So no one tactic cant be activated. sry for my english. Ayrion can explain, i hope.

Update:
I fix my problem tactic called "Intimidating Repent" was broke ALL tactics. After i remove it - all fine.
Thx for helping Ayrion.

 -Hehechpok

**Comment by Luth-RoR** [comment]
Couldn't reproduce on the dev server. Probably related to unclean disconnect from the DB.
