### ISSUE TITLE
Throat Bite does not enough dmg

### ISSUE THREAD

**Issue by Tiggonos** [WarEmu/WarBugs#6204]
should do 351 only does 100.
![melquardt_008](https://cloud.githubusercontent.com/assets/13809443/15406629/8e341a3e-1e07-11e6-8078-d32cf6944532.jpg)

**Comment by Tiggonos** [comment]
couldnt see if silence even works.

**Comment by Paninii** [comment]
confirming the damage part, doing 64 dmg (26 mitigated) at level 35 on a level 39 mob

**Comment by Danszilver** [comment]
I know this has been a long time ago, but throat bite seems to have stopped adding the damage entirely. I have tried several times to get the ability to work, but failed every time.

The ability seems to be able to put the silence debuff on the target, but fails to put on any damage.
![Danszilverr_000](https://user-images.githubusercontent.com/50529499/57574251-d3fa5d80-7435-11e9-9aef-20d03268eef3.jpg)
![Danszilverr_001](https://user-images.githubusercontent.com/50529499/57574252-d65cb780-7435-11e9-99bd-afdb8dfea4bc.jpg)

If more information is needed, feel free to ask.

**Comment by Kaelang** [comment]
If this is still applicable post rework please open a new ticket.
