### ISSUE TITLE
Warrior Priest Vendors

### ISSUE THREAD

**Issue by Vandorkholme** [WarEmu/WarBugs#6206]
From T1 Renown Gear Merchant:
2handers that don't give AoE detaunt:
Survivalist Sledge of Vengeance

Books giving no RF regen:
Healer's Tome of Vengeance
Survivalist's Tome of Vengeance

From T2 Veteran Renown Gear Merchant:
2handers that don't give AoE detaunt:
Fighter's Sledge of Dominion
Fighter's Sledge of Conquest
Survivalist's Sledge of Dominion
Survivalist's Battlehammer of Conquest
Survivalist's Sledge of Conquest

From T3 Advanced Renown Gear Merchant:
2handers that don't give AoE detaunt:
Sentry Sledge of the Fighter
Echelon Sledge of the Fighter
Sentry Battlehammer of the Healer
Echelon Battlehammer of the Healer
Sentry Battlehammer of the Survivalist
Sentry Sledge of the Survivalist
Echelon Battlehammer of the Survivalist
Echelon Sledge of the Survivalist

**Comment by Ryanfawkez** [comment]
T1 tomes and sledges fixed in next patch.

**Comment by Ryanfawkez** [comment]
Fixing the T2 and T3 ones as well. FYI; Battlehammers are one-handed.
