### ISSUE TITLE
Game crashing to character select screen.

### ISSUE THREAD

**Issue by CustardSlice** [WarEmu/WarBugs#6207]
Hi,

I seem to be having a reoccurring issues where, if I need to load a new area e.g. Scenario has popped or I move into a new area. The game goes happily to the loading screen then all sound cuts off and I am then are the character select page with no "play" button. I have to restart the game every time unless I head the music come back on?.

**Comment by Evildoor** [comment]
Wrong place. Read the rules of the bugtracker.

**Comment by CustardSlice** [comment]
Great load of help this site is then for "bugs"
