### ISSUE TITLE
Personal Notes (Member Notes) Roster Management

### ISSUE THREAD

**Issue by swbf2fan2510** [WarEmu/WarBugs#6208]
Members can't change member notes unless i give them permission to change eachothers.

**Comment by MaxHayman** [comment]
Seems fine for me. Not sure what you are referring too.

![image](https://user-images.githubusercontent.com/1018809/47967654-aa601400-e057-11e8-8a3b-6eec3e9953d7.png)

**Comment by MaxHayman** [comment]
@sioding Can we close this? I am not sure what there original issue specifically is talking about.

**Comment by sioding** [comment]
Nope sorry @MaxHayman. 
This is still a problem. If the rught "Edit Membernote" is being set you are able to edit ALL membernotes which seems correct. Cause this right should be set for ppl who are in a guild lead or organisations role. 
The right "Edit Personal Note" is not working. With that you should be able to only edit your own Membernote - not others. Even when its being set you are not able to edit your own Membernote.

**Comment by MaxHayman** [comment]
Working as of 12/07/2019
