### ISSUE TITLE
Quest: At Peace

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#6210]
This one seems to have the wrong mob. Objective is to kill 3 wolf riders that are killing horses, but there's no horses nearby, and these mobs are R17 Champions.
http://i.imgur.com/IX4Luts.png
info for the wrong mob http://i.imgur.com/vta06iQ.png?1

Over here however, we have some greenskins beating dead horses, and the same mob, but not a champion. This appears to be the correct location as it matches up with the quest description. The quest blob should be moved as well.
http://i.imgur.com/JTB8Uke.png
http://i.imgur.com/5CYtXIH.png
info for the correct mob http://i.imgur.com/yD6o0hm.png

**Comment by Natherul** [comment]
Should be fixed as of todays patch (14/07/2017)
