### ISSUE TITLE
Quest: Gnoblar Huntin'

### ISSUE THREAD

**Issue by freshour** [WarEmu/WarBugs#6212]
I have all three items, for the 3rd time. I made sure I had none of them when I accepted the quest after having all of them once and abandoning it. Tried it now 3x. I have all 3 items, only the trapper parts give me credit, the other two don't. I think it has something to do with the quest thinking they are all in cinderfall when they aren't. 

1 is in badlands the other is in black crag. Neither of which give credit. When this is fixed, please allow us to just take the quest with all three and turn them in. I'm not sure I can get all these items for a forth time. THANKS!

**Comment by Vayra** [comment]
There's 4 items. 2 in Cinderfall, 1 in Badlands, 1 in BC. Need to kill Gutbash Tooth Gnoblars as well in Cinderfall.

**Comment by freshour** [comment]
Did all of this and it doesn't work.

**Comment by Ryanfawkez** [comment]
You are completely right. Thought all three gnoblar types were in Cinderfall, so I restricted them to that zone, as there's also Bloodmaw Gnoblars in High Pass. Will have to alter quest descriptions for both sides and include Black Crag and the Badlands.

**Comment by balgax** [comment]
i have the 4 piece i guess and cant use noone of them as i should for the tome unlock

![image](https://cloud.githubusercontent.com/assets/16364042/15426787/1ebb962a-1e91-11e6-9fcc-1b3c9a502316.png)

![image](https://cloud.githubusercontent.com/assets/16364042/15426799/3929b776-1e91-11e6-9152-9220c21f3c6b.png)
![image](https://cloud.githubusercontent.com/assets/16364042/15426814/4bfcef08-1e91-11e6-9db3-5f0c79c268b6.png)
![image](https://cloud.githubusercontent.com/assets/16364042/15426824/5a055838-1e91-11e6-9f0e-9024088caaa0.png)

**Comment by freshour** [comment]
Curious - how often do those happen hehe? I literally cannot wait to try this out. I really loved the idea of set piece jewelry so its super fun that us melee guys have one set! Thank you for such a fast reply on this one!

**Comment by Torquemadra** [comment]
removed area restrictions, mobs can be killed anywhere, items required for quest and ToK now only drop when actually on the quests themselves

**Comment by freshour** [comment]
Okay, I know we just had a crash and not a restart, but killed and got the nose and the quest was not updated and is still 0/1. Do I have to drop the old quest and get the new one? Or should I just wait for a proper restart?

**Comment by Torquemadra** [comment]
it needs a db push, so next patch

**Comment by freshour** [comment]
Okay thanks!! Any shot of one today or is there no real way to get an ETA on it?

**Comment by freshour** [comment]
Server just patched - still didn't get credit for looting the nose.

**Comment by freshour** [comment]
Going to abandon the quest again and try again

**Comment by freshour** [comment]
Confirmed - restrictions aren't removed even on dropping the items and retaking the quest.
