### ISSUE TITLE
[Quest] An Eye for Trouble

### ISSUE THREAD

**Issue by moondoggcavalier** [WarEmu/WarBugs#6214]
Duplicate of the same quest, one of which has an invalid object.

![moondogg_036](https://cloud.githubusercontent.com/assets/15387904/15417266/d3b11124-1e21-11e6-97d3-8cc5284351a9.jpg)
![moondogg_037](https://cloud.githubusercontent.com/assets/15387904/15417265/d3aeac4a-1e21-11e6-9eb7-8d10e72b1c95.jpg)

**Comment by Evildoor** [comment]
#5686

**Comment by stickas** [comment]
This quest still shows up as 
"Invalid Creature - QuestID
44621, ObjId=1722 - 0/8"
