### ISSUE TITLE
Time to waaagh

### ISSUE THREAD

**Issue by Areanda** [WarEmu/WarBugs#6216]
if u do 2 steps in the quest to the point u need to talk to Tzaarchanek,
u can then go to left room pick the quest up again but then ur immediatly on the last stage meaning u get ur weapon after 2 quests instead of 16.

**Comment by Zegreiart** [comment]
![doktabeatbox_044](https://cloud.githubusercontent.com/assets/17631607/15419538/3b0b9358-1e2c-11e6-9bfc-f5a9934c5ff0.jpg)
Confirming, also was able to do this. I was unable to actually follow the quest chain, but was just given the last two quests themselves from Grumlok.

**Comment by NorKalli** [comment]
long since fixed
