### ISSUE TITLE
Quest: The Threat Revealed

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#6217]
Broken items! :D

http://i.imgur.com/aRGwLen.png
http://i.imgur.com/5ENn0gm.png
Mane of Repatriators
+12 WS
+10 WND
+6 TGH

Chivalrous Mane
+18 STR
+10 TGH

http://war.mmodb.com/items/chivalrous-mane-101175.php
http://war.mmodb.com/items/mane-of-repatriators-101015.php

**Comment by wargrimnir** [comment]
Ah, also the last step of the quest should be killing an NPC name Istavahn Bonecrafter, but you only need to click on a book as the NPC itself seems to be missing from the area.

**Comment by sioding** [comment]
fixed next patch

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
