### ISSUE TITLE
Incorrect RVR area: Dragonwake warcamp

### ISSUE THREAD

**Issue by Vasiliuss** [WarEmu/WarBugs#6222]
Flagged for RVR on arrival to Dragonwake warcamp "Drakewarden Keep".

[http://i.imgur.com/MlpS9FT.jpg](http://i.imgur.com/MlpS9FT.jpg)
[http://i.imgur.com/HyEqhjW.jpg](http://i.imgur.com/HyEqhjW.jpg)
[http://i.imgur.com/GnLA2Mx.jpg](http://i.imgur.com/GnLA2Mx.jpg)

**Comment by saupreusse** [comment]
should be fixed soon. maybe not in the next patch, but soon....
..soon....
