### ISSUE TITLE
BW Fireball damage on keep doors

### ISSUE THREAD

**Issue by KingDuppy** [WarEmu/WarBugs#6225]
When using Fireball on keep doors it seems to be doing damage to the door but taking around 30 seconds for the damage numbers to show up so i can see i have done damage.

**Comment by Evildoor** [comment]
What about other abilities, both instahitting and with fly time like Fireball? Other classes abilities, like Eagle Eye?

**Comment by KingDuppy** [comment]
All BW instant hitting abilities seem to be working fine showing the damage when they hit the door

**Comment by Abolition** [comment]
This is the same with Sorc's Doombolt.

**Comment by Luth-RoR** [comment]
Maybe related to projectile travelling time.

**Comment by ozarmidrashim** [comment]
No longer relevant
