### ISSUE TITLE
[PQ] Contribution in new Eatain Order PQ Da Orcwerks does not work for healers

### ISSUE THREAD

**Issue by Scrilian** [WarEmu/WarBugs#6226]
![gaziraga_320](https://cloud.githubusercontent.com/assets/16498708/15425559/b80a4182-1e91-11e6-8557-6a3535f8b32b.jpg)

**Comment by Soulwhisper** [comment]
There is no reset timer here.

**Comment by Soulwhisper** [comment]
Now after 21st Changelog Counter is broken Visually on 1st Stage.
