### ISSUE TITLE
Guilds: Two guilds have merged with each other

### ISSUE THREAD

**Issue by YUKO1** [WarEmu/WarBugs#6227]
Hello!

We made a brand new guild this morning. 

I relogged just now and saw under the guild panel of whom last joined/left there is another guild created named "Death Watch". It is, as if both our guilds have merged with each other, our titles, settings, information regarding the guilds etc, our renown contribution seemed to reach a explosion too. I managed to see their bank vault but no access to it. 
(We haven't unlocked our vault yet, we're still rank 1)

![khazhakar_001](https://cloud.githubusercontent.com/assets/17162613/15425537/32ee7c82-1e89-11e6-9939-d4ab60b04472.jpg)

![khazhakar_002](https://cloud.githubusercontent.com/assets/17162613/15425538/32f41dd6-1e89-11e6-9f39-f6ef6b1a2a85.jpg)

Has anyone else experinced this?

Kind regards,
YUKO1

**Comment by Luth-RoR** [comment]
Happened due to temp server/DB problems.
