### ISSUE TITLE
Can still mount in Serpents Passage sc

### ISSUE THREAD

**Issue by Gonzio** [WarEmu/WarBugs#6229]
Speed buff is still obtained after mounting, with the salvage, however there is no horse animation.

http://imgur.com/HsGhqMX

**Comment by munchykin** [comment]
I noticed this today,,,someone moving at mount speed with no mount animation, running at same speed as mounted escort.

**Comment by Thorgatin** [comment]
Happens when the player is mounted and takes the part as it seems. The player is dismounted but still has the mount buff, just like when you walk through water.

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=18653
