### ISSUE TITLE
Tome Trinket: Oathstone of Karak Eight Peaks

### ISSUE THREAD

**Issue by balgax** [WarEmu/WarBugs#6230]
I have the 4 "items" of the Gnoblars. I should use 1 of the 4 items to get the tome unlock but dont get it.
Screens are available if needed

**Comment by Ryanfawkez** [comment]
https://github.com/WarEmu/WarBugs/issues/6212

**Comment by Evildoor** [comment]
So it was #6212 after all... Quest and tome unlock require the same things? Sigh...
