### ISSUE TITLE
20/05/2016 - KABOOM!

### ISSUE THREAD

**Issue by Teefz** [WarEmu/WarBugs#6231]
KABOOM still doesn't work correctly and still causes the squig herder to not being able to use ANY - I repeat - ANY abilities besides mounting up. Loading a new zone doesn't not fix the issue anymore. Only way to fix it, is a relog.

My guess on why it doesn't work is because the Squig Armor around the Squig Herder doesn't actually explode. The animation is there, but you remain in the squig armor. Therefore something f's up :)

**Comment by Evildoor** [comment]
Add new info to #5783
