### ISSUE TITLE
20/05/2016 - NullreferenceException ( Pets! )

### ISSUE THREAD

**Issue by Teefz** [WarEmu/WarBugs#6232]
![ss](https://cloud.githubusercontent.com/assets/18510648/15427305/6fd02302-1e94-11e6-80a9-6aa6df2736df.jpg)

Linked a SS. This causes the pet's to f' up. And I've just been told that this effect Magus pets. Weather or not it effect's Engineer turrets or WL pet, I cannot say.

**Comment by Evildoor** [comment]
#6211
