### ISSUE TITLE
Death Peak: area out of the map

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#6234]
In Death Peak, you can border the valley in the center and fall inside being unable to get out.
Falling causes no damage so you need to use a book.
If you keep going southward  you end into Dangerous territory.
You can fall down pretty much everywhere along the border.
![urmig_009](https://cloud.githubusercontent.com/assets/18053736/15428927/1d63b6a4-1e96-11e6-960e-84a49f314840.jpg)

**Comment by Ryanfawkez** [comment]
People now get terminated when they fall here.
