### ISSUE TITLE
Death Peak Champion of the Lost Forge: Snizzort, double spawn

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#6236]
The Ratogre Hero Snizzort located at 8k 30k is doubled.
This boss is necessary for a quest called Champion of the Lost Forge, mentioned [here](http://warhammeronline.wikia.com/wiki/Game_Update_1.2.0/Quests_and_Public_Quests
![urmig_017](https://cloud.githubusercontent.com/assets/18053736/15429194/c08444ec-1e97-11e6-9d73-224e54ef5e25.jpg)
)

**Comment by saupreusse** [comment]
fixed in next patch.
