### ISSUE TITLE
Death Peak: PQ Peak's Edge: stuck at stage 3

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#6237]
The boss Borgut Facebeater does not spawn, there is no timer to restart the quest.
![urmig_018](https://cloud.githubusercontent.com/assets/18053736/15429542/527d11a2-1e99-11e6-93b4-9e0c50e9f2c1.jpg)

**Comment by Razielhell** [comment]
There is a WIP in these PQs.
