### ISSUE TITLE
Dwarf CH 19 Elite rewards have wrong stats

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#6239]
These 2 elite rewards have similar stats but one is better.
Either they need to have different stats entirely or same stats for esthetic reasons

![wh1](https://cloud.githubusercontent.com/assets/18053736/15430160/02b486fc-1e9c-11e6-8654-3da7790fc411.png)

**Comment by Evildoor** [comment]
I suppose that second one is missing "Slayer" restriction as well as these 3 stat points.

**Comment by wargrimnir** [comment]
Corrected stats.
