### ISSUE TITLE
[Quest] Striking Fear in Praag

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#6240]
Does not offer the "T4 standard" of 1.59g for completion. See screenshot.

![abolition_007](https://cloud.githubusercontent.com/assets/15091486/15430462/9c7d5a0a-1ee4-11e6-8814-da802732e451.jpg)

**Comment by Evildoor** [comment]
Kill quests give 74.88s in the central zone, 37.44s in the zone closest to your fortress, and 1.59g in the zone closest to the enemy fortress (c) Genisaurus
