### ISSUE TITLE
[Quest] Defend Garrison of Skulls

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#6241]
Does not offer the "T4 standard" of 1.59g for completion. See screenshot.

![abolition_008](https://cloud.githubusercontent.com/assets/15091486/15430487/bd7960f0-1ee4-11e6-983f-06fc52f9fabf.jpg)

**Comment by Evildoor** [comment]
Kill quests give 74.88s in the central zone, 37.44s in the zone closest to your fortress, and 1.59g in the zone closest to the enemy fortress (c) Genisaurus
