### ISSUE TITLE
[Quest] Stompin' Stunties in Thunder Mountain

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#6242]
Does not offer the "T4 standard" of 1.59g for completion. See screenshot.

![abolition_009](https://cloud.githubusercontent.com/assets/15091486/15430502/cee39fa4-1ee4-11e6-8c87-9c7d159b4eb0.jpg)

**Comment by Evildoor** [comment]
Kill quests give 74.88s in the central zone, 37.44s in the zone closest to your fortress, and 1.59g in the zone closest to the enemy fortress (c) Genisaurus
