### ISSUE TITLE
[Quest] Striking Fear in the Chaos Wastes PLUS an additional note

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#6243]
Does not offer the "T4 standard" of 1.59g for completion. See screenshot.

![abolition_010](https://cloud.githubusercontent.com/assets/15091486/15430546/ea9ca2a4-1ee4-11e6-9c53-bb1f37ea770d.jpg)

I have a sneaky feeling there may be two kill quests for this zone, which may be an error? See below.

![abolition_011](https://cloud.githubusercontent.com/assets/15091486/15430566/ffb7a954-1ee4-11e6-8b69-512ac8dcb6b2.jpg)

**Comment by Evildoor** [comment]
Kill quests give 74.88s in the central zone, 37.44s in the zone closest to your fortress, and 1.59g in the zone closest to the enemy fortress (c) Genisaurus

Second quest may be a problem though.

**Comment by Abolition** [comment]
Regarding Killing Time - I turned it in today and was unable to pick it up again, so it appears it is a one off quest.

**Comment by Evildoor** [comment]
Closing then.
