### ISSUE TITLE
Martikhoras

### ISSUE THREAD

**Issue by Uchoo** [WarEmu/WarBugs#6249]
This mob in Caledor is currently stuck inside of a mountain and cannot be aggroed unless you jump off of the above cliff. Part of a bestial token unlock. On live it had a roaming path that it flew.
![galrauch_000](https://cloud.githubusercontent.com/assets/15972308/15434916/019af20a-1e7f-11e6-90fb-383eabc900fd.jpg)

**Comment by saupreusse** [comment]
fixed. he now spawns down the hill on the other side.
