### ISSUE TITLE
Mount/water interaction

### ISSUE THREAD

**Issue by nrvi** [WarEmu/WarBugs#6250]
Upon entering a deep water that would dismount you, it removes the mount visually but the mount buff on character&the movespeed doesn't get removed. You end up running around +%50ms without a mount.
![mount](https://cloud.githubusercontent.com/assets/19493545/15435106/1a29c5b4-1ec3-11e6-8a19-ed89b48c8ee4.jpg)

**Comment by Evildoor** [comment]
#798
