### ISSUE TITLE
Serpent Pass Scenario  

### ISSUE THREAD

**Issue by albensambo** [WarEmu/WarBugs#6252]
serpent pass  order spawn in destro spawn near end of game, and if you try to mount with salvage part, it wont let mount anymore even with out had to relog just to mount after the scenario was over.

**Comment by Evildoor** [comment]
> serpent pass order spawn in destro spawn near end of game

What?

> if you try to mount with salvage part, it wont let mount anymore even with out had to relog just to mount after the scenario was over.

Should be posted in #6229.

**Comment by Evildoor** [comment]
No clarification, closing.
