### ISSUE TITLE
broadhead arrow

### ISSUE THREAD

**Issue by truewage** [WarEmu/WarBugs#6254]
time since the skill is released until it hits 2sec

**Comment by Evildoor** [comment]
Even when point blank?

**Comment by truewage** [comment]
yes

**Comment by truewage** [comment]
edit: all abilities hit 2sec after being released

**Comment by ozarmidrashim** [comment]
I see absolutely nothing wrong with it.

Projectile speeds were normalized. At 100ft, SW shots require 1.35s to connect. This is in line with information received regarding the speeds of "most" projectiles in the game.

**Comment by truewage** [comment]
https://youtu.be/si2CI-YDEeA

**Comment by geezereur** [comment]
Squig Herders Yer Bleedin dot hit faster than Shadow Warriors Broadhead Arrow,
 you have to have to wait before applying the healing debuff dot on SW travel time of broadhead arrow is to long.
