### ISSUE TITLE
[Sorc] Annihilator Castbracer appearance

### ISSUE THREAD

**Issue by stillwaterww** [WarEmu/WarBugs#6258]
Not sure if this is intended or not.
These seem to share a model with chaos ch18 influence reward.
Expurgatorial Castbracers.
![iobel_009](https://cloud.githubusercontent.com/assets/19287032/15435909/4e01af5e-1ebf-11e6-9949-7561aa9a18ae.jpg)

**Comment by Torquemadra** [comment]
There are very few unique items in the game, this is not uncommon
