### ISSUE TITLE
Door regen too fast

### ISSUE THREAD

**Issue by Swipz** [WarEmu/WarBugs#6264]
Ok we will try to take Dragonwake keep and see some issues trying taking it : 

On outerdoor : 
- Ram doesn't work
- Door regen way too fast, we destroy oil in around 45sec, and door regen around 30% in this time with the 4 Battle objectives taken. 

After GM help (Natharax) in Inner door : 

- Ram works but only do 1956 dmg
- Door regen still be too fast

On both doors : 

- Autoattack on door doesn't work, don't know if it's because of Ram on door. but only be able to hit the door with skills

**Comment by Natherul** [comment]
I was there, had to kill the first door as the regen (with no BOs for desto) was waay too high. second door did not behave the same but regen was still way too high (when destro managed to get 2 BOs the door regen was around 3% per sec or something like that)

**Comment by Evildoor** [comment]
Rams not working and autoattack on doors were already reported.
