### ISSUE TITLE
|QUEST| Can't be completed

### ISSUE THREAD

**Issue by Azmah00** [WarEmu/WarBugs#6266]
Hi,

For destruction, these quests can't be completed (they're well done and all is done right)

Greenskins chapter 12 : 

- Crushin' Dem All
- Gobbos in da Trees

Thanks to do something to their NPC who're bugged..

Also, there's 3 Sun Dragons on T3, before the T4 patch i was farming them for the Book Unlocks, but now, they're no longer count on the book, is it normal?

**Comment by Evildoor** [comment]
One report per problem.
#4125 is supposed to be fixed.
Sun Dragons are not dragons IIRC.

**Comment by saupreusse** [comment]
They are all fixed and it can be closed.
