### ISSUE TITLE
Squig Herder pet passive mode

### ISSUE THREAD

**Issue by Gooboo1** [WarEmu/WarBugs#6267]
Before the update on 19th May, 2016 the passive mode for squigs would continuously attack when told to once. After the update it now just hits the target once then runs back to you. I looked in the update for that day and didn't see a change for it. I don't know if this is just a change made but unlisted or a bug. I also don't know if this happens for other pets or just squigs because I have not played another class involving a pet.

**Comment by Tiggonos** [comment]
wl pet is the same problem.
