### ISSUE TITLE
Serpent's Passage salvage

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#6270]
Currently the salvage respawns instantly after being captured. On live there was a 15-20 second delay so that both sides had a chance to get back to the salvage before it respawned. Right now you either end up with 1 side running them back to back by having 2 people there, or each side taking turns grabbing the next one after one side caps.

**Comment by sioding** [comment]
Can we please have some evidence from live? A video would be great.

**Comment by Vayra** [comment]
Here's a video from 2009 showing a 20s reset time of the part:

9:02 the part is captured,
9:22 the part is reset
11:06 part is capture
11:26 part is reset.

https://www.youtube.com/watch?v=Md2IB7lEkR8
