### ISSUE TITLE
T4 Lair: Malachia's Lair

### ISSUE THREAD

**Issue by OcecoOtto** [WarEmu/WarBugs#6273]
I was looking to see what T4 Lair bosses were open and I noticed that the creepvine was blocking the path to Malachia's lair. I believe that the item to clear the path was already reported to not be clickable. However there is still a way to get into the lair and kill the boss. Not far from the legitimate entrance there is a set of rocks up the mountain that can be climbed with relative ease and allow you to traverse out of the map boundaries. From that point you can make your way over to the lair entrance and bypass the creepvine dropping down to the cave entrance. The npcs inside are mostly level 40 champions and respawn relatively quickly, this might make it easy to farm them for higher level scavenging parts. I thought this was strange since most out of bound zones seemed to port you back to the capital or Norsca if you strayed to far. Here are the screenshots showing the path from the rocks you can climb to get out of the map boundaries.
![sevastyan_006](https://cloud.githubusercontent.com/assets/19501260/15446817/9520546e-1ef9-11e6-8562-b60c07088bdd.jpg)
![sevastyan_007](https://cloud.githubusercontent.com/assets/19501260/15446821/be73dfd4-1ef9-11e6-9cb5-c1c752caa70a.jpg)
![sevastyan_008](https://cloud.githubusercontent.com/assets/19501260/15446823/c146b402-1ef9-11e6-82f9-1450a07d2c9e.jpg)
![sevastyan_009](https://cloud.githubusercontent.com/assets/19501260/15446824/c3b480d4-1ef9-11e6-9324-448e8ea2ab17.jpg)
![sevastyan_010](https://cloud.githubusercontent.com/assets/19501260/15446826/c635bdf0-1ef9-11e6-8d0c-951775e48986.jpg)
![sevastyan_011](https://cloud.githubusercontent.com/assets/19501260/15446827/c7fce5f0-1ef9-11e6-9cde-94c21fb708bd.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
