### ISSUE TITLE
Quest: Questionable Judgement

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#6275]
No items here, but, I'm pretty certain the wrong mobs are listed.

http://i.imgur.com/LeinYUK.png

There are no Magi Destroyers in the area. The cave at the top of the hill here has a handful of Magi Devourers. Those are probably the correct mob, unless I'm missing something or this PQ stage needs to advance. It's broken currently.

http://i.imgur.com/gDWcvEo.png

**Comment by Ryanfawkez** [comment]
Spawned about 10 Magi Destroyers in the area. Fixed in next patch.
