### ISSUE TITLE
War lion | NullReferenceException

### ISSUE THREAD

**Issue by Thorgatin** [WarEmu/WarBugs#6278]
The lion drew aggro from an NPC and the NPC followed it. 
Right in the moment as he came into attack range, an exception was thrown and the lion disappeared, leaving the NPC rooted on it's place instead of resetting it.
The lion wasn't completely gone as it seems, as the 50% increased crit damage tactic still worked. The lion could be called again like normally, but it happened again on other NPC types.
Sometimes it doesn't happen at all, sometimes after a few seconds and sometimes right before the first hit.
My wild ass guess: pet abilities.

![20160521110031_1](https://cloud.githubusercontent.com/assets/8567481/15447492/61b26d88-1f44-11e6-9e95-010870d1557c.jpg)
![20160521110031_1_crop](https://cloud.githubusercontent.com/assets/8567481/15447496/779a97a6-1f44-11e6-8e3e-8ce64be4d2eb.jpg)

**Comment by Thorgatin** [comment]
If that happens, the "call white lion" ability must be used 2x again; after the first use, nothing happens (no GCD either); after the second use, the lion is called with the ability going on cooldown.

**Comment by Evildoor** [comment]
#6211
