### ISSUE TITLE
siege weapons rapair from death/hide status

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#6280]
saw emp cannon being repaired by a dead which hunter or it could had been another  hide one.
When you click something you should de-hide and from death you shoudl not being able to interact with anyting

**Comment by Ryanfawkez** [comment]
Checked what happens on death on siege weapon. Seems you lose the control over it. Will try stealth repairing.

**Comment by Ryanfawkez** [comment]
Yep, seems you can repair and fire siege weapons from stealth.
