### ISSUE TITLE
Full Tank got one shotted by Sorc

### ISSUE THREAD

**Issue by PigletInoshishi** [WarEmu/WarBugs#6282]
Hey, 

i just got one shotted in a sc by a sorc (i played a full tank IB) by a 90k crit. Just got 82 damage before that shot. A GM said i should upload the combat log here so here we go.
(i censored all names) 

![oneshotsorc](https://cloud.githubusercontent.com/assets/19503683/15447904/1fd8eb32-1f51-11e6-812f-862872b8a694.jpg)

**Comment by grunbag** [comment]
Fixed already
