### ISSUE TITLE
Sorc Insane Dmg

### ISSUE THREAD

**Issue by Anirith** [WarEmu/WarBugs#6283]
https://gyazo.com/50099c15e70582e5b881449fc036ea57
https://gyazo.com/55002e7b11fdf0a4ea2d2649fda046eb
 I dont know how, but sometimes my dots will do this amount of damage, some bugged with the critical multipler i guess.

**Comment by PigletInoshishi** [comment]
Just opened the same thread lol ^^

**Comment by Evildoor** [comment]
#6282
