### ISSUE TITLE
[NPC] Sun Dragon incorrect spawn

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#6284]
almost invisible 2x neutral pixer sun dragon  that shoud be removed at 45k 53k
![tesq_065](https://cloud.githubusercontent.com/assets/7527415/15447951/6a1faffe-1f52-11e6-8652-03b571b908b9.jpg)

**Comment by Ryanfawkez** [comment]
Revmoed the Sun Dragon Anchors. Fixed in next patch.

**Comment by Tesq** [comment]
there is even behind him a normal sun dragon
