### ISSUE TITLE
[Quest] Unmasking the enemy

### ISSUE THREAD

**Issue by Luicetarro** [WarEmu/WarBugs#6285]
Quest istn't obtainable anymore, since the reduction of the starting-lvl.
Even with a lvl above the old starting-lvl the quest won't get displayed.

Black Crag Chapter 21.
Rorki Thunderbreaker at 33.2K 19.4K

Others are posting the same issue in the forums, so it istn't me alone.

**Comment by Torquemadra** [comment]
unmasking the enemy starts in dragonwake

Battle for remembrance starts in BC,both work on dev

wait for a reboot.
