### ISSUE TITLE
Order Nordland Chapter 3 PQ Faewulf's Rest and The Webworks Broken

### ISSUE THREAD

**Issue by MatteV2** [WarEmu/WarBugs#6286]
At the Faewulf's Rest Normal PQ I was unable to interact with the stage 1 items, the Ancient Stones, and in The Webworks Easy PQ the kills on the spider in Stage 1 did not register on the tracker (unsure if the PQ still advances once requirements are met, regardless of registering on the tracker or not)

**Comment by Evildoor** [comment]
#4398
#4399
Next time - one report per problem.

**Comment by MatteV2** [comment]
Oh, I searched for them but couldnt find them. Sorry, will keep in mind next time.
