### ISSUE TITLE
Nordland, PQ: The norse are coming, cannot be completed

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#6289]
On stage 2, some NPC's called Norse Plunderer are supposed to spawn but they do not.
![screen shot 2016-05-21 at 13 29 32](https://cloud.githubusercontent.com/assets/18053736/15448363/12b70f5e-1f58-11e6-8de3-08c09ba3f555.png)

Coordinates are 13k 11k
![screen shot 2016-05-21 at 13 27 34](https://cloud.githubusercontent.com/assets/18053736/15448357/e38af830-1f57-11e6-8404-b787c3159990.png)

**Comment by Evildoor** [comment]
#4400
