### ISSUE TITLE
Show Helm On/Off bug

### ISSUE THREAD

**Issue by Habsi** [WarEmu/WarBugs#6290]
Only on my IB "Jaegeroo" i got this bug. Helm randomly show on/off. Addons turn off/ Reinstall game, nothing help.

**Comment by Evildoor** [comment]
I doubt that this problem has anything to do with the server.

**Comment by Tesq** [comment]
try disable chance no disk see if it work

**Comment by Evildoor** [comment]
No comments disproving my statement. Either it's a problem on your side or, dunno, you have a helm without model, then we need a helm name. Closing.
