### ISSUE TITLE
Pass it on tactict and Sticky Feets -- Shaman

### ISSUE THREAD

**Issue by kkprfx** [WarEmu/WarBugs#6292]
Hello,so lets begin with Pass it on tactict.
tactict tooltip says : "Any time you heal an ally with a Path of Mork ability,there is a 25 % chance that another ally within 30 feet of them  will also gain 306 health as well"
but it only works with direct heals and not with  hot ticks like DSU or EQB.
i dont know if this is intentional, if it is then its cool just update tooltip :p 
ok to Sticky feetz now, ability works just fine but when u cast it out of range ability obviously not working but u still get cd for it
thank u for u time :)

**Comment by Evildoor** [comment]
1) One report per problem.
2) We cannot update tooltips and it's unlikely to change in the nearby future. Such kind of basic knowledge is mandatory before reporting things.
3) Use search: #1118, #1974.
