### ISSUE TITLE
[RvR] Tier 2 Elf - Destro Door Invincible

### ISSUE THREAD

**Issue by Frubertlives** [WarEmu/WarBugs#6294]
Door "broke" but it remained as an impenetrable barrier for players of any faction. Postern door was also impossible to enter. 
![dungchewa_042](https://cloud.githubusercontent.com/assets/18690551/15448782/57a4bdd8-1f39-11e6-8567-afc3d01659f0.jpg)

**Comment by Tesq** [comment]
it's client side as happened to me in talabecland lot of timeswith the outer

**Comment by Frubertlives** [comment]
Happened in Fangbreaka keep again just a moment ago.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
