### ISSUE TITLE
Squig Herder Ability KABOOM!

### ISSUE THREAD

**Issue by Culdu** [WarEmu/WarBugs#6295]
If you use KABOOM! in Squig armor, u optically keep Squig armor and the Squig armor Quick bar, but truly you are not in squig armor ( buffs, can't use special abilities) and you can't rejoin squig armor. To remove that bug u have to leave the optical squig armor with the normal ability squig armor and use kaboom as normal squig again(which is greyed out but working) After that everything is working "normal" again

**Comment by ozarmidrashim** [comment]
#5783 dupe.

Please read the rules of using the bugtracker.
