### ISSUE TITLE
[NPC] missing champ 55 allow enter inside emp chap 15

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#6296]
9k, 36k chap 15

![tesq_076](https://cloud.githubusercontent.com/assets/7527415/15448906/22d0b5ea-1f6f-11e6-84a3-3a287cf9a22c.jpg)
![tesq_078](https://cloud.githubusercontent.com/assets/7527415/15448918/4562182e-1f6f-11e6-863e-3fd241778ae7.jpg)

it need to be placed in front of me in the first image in 30 feet

also here you need one
![tesq_079](https://cloud.githubusercontent.com/assets/7527415/15448931/977b27d6-1f6f-11e6-9fdc-3ea272fd26cc.jpg)

**Comment by saupreusse** [comment]
fixed
