### ISSUE TITLE
Praag south keep no ram deployable

### ISSUE THREAD

**Issue by Amalafein** [WarEmu/WarBugs#6304]
Ram was not deployable. Last ram was not long enough down. 

In this time 4 oils was deployed and destroyed, so it should be a bug

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
