### ISSUE TITLE
Praag South Keep Oil not attackable

### ISSUE THREAD

**Issue by Dichnich** [WarEmu/WarBugs#6305]
Just a few minutes ago we tried to attack Praag South Keep with defenders and Oil. The Oil wasn't attackable with range on a normal way. Only by jumping at random positions and using instant abilities any damage could be dealt.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
