### ISSUE TITLE
War Lion / Quest Kill Credits

### ISSUE THREAD

**Issue by nrvi** [WarEmu/WarBugs#6307]
Observed quest: Inescapable (Kill Casimir Por)

If the killing blow is done by a war lion pet, only the White Lion will get the kill credit and not the rest of the party.

Couldn't test this yet on a different quest, or tried to replicate it on the same one. Will try to and update when servers come back up.

**Comment by Evildoor** [comment]
I'm pretty sure it's #1229 or #2401, or both of them.
