### ISSUE TITLE
[Quest] "New Allies, New Enemies"

### ISSUE THREAD

**Issue by Gakvar** [WarEmu/WarBugs#6308]
This step of this long quest starts with Grunmir Sourhelm in Dwarf chapter 17, Lorkinson's Excavation, Thunder Mountain.

It's objective is to find a Bandit's Courier in camp full of bandits and supposedly talk to him. Problem is he's aggressive and can only be killed. The quest completes but there is none to turn the quest to (supposedly it was to turn it to him).

**Comment by Meralors** [comment]
Fixed Bandit Courier faction, he's now Order Neutral. I couldn't check the complete quest line so it could be a bit buggy.

**Comment by Gakvar** [comment]
It's fixed, thanks.
