### ISSUE TITLE
[Quest] "The Lance of Lothern"

### ISSUE THREAD

**Issue by Gakvar** [WarEmu/WarBugs#6309]
This quest starts in Dwarf chapter 17, Lorkinson's Excavation, Thunder Mountain. It sends the player to  search Dragon's Blessing for clues about an elf Silver Helm who went there searching for Aleanda.

On site the player can find a book on the ground called Aleanda's Account. Nothing happens by interacting the book but the quest seems to complete only by entering the area. There is none to turn this quest to for further steps.

**Comment by Meralors** [comment]
Interacting with Aleanda's account will now complete quest.

**Comment by Gakvar** [comment]
The quest was already completing, However, there isn't yet a place or person to turn it to, or a second quest that starts at the object
