### ISSUE TITLE
[Quest] t4 dwarf ch 17 "Warding the Past"

### ISSUE THREAD

**Issue by Gakvar** [WarEmu/WarBugs#6310]
This quest sends the player to inspect a Ward Stone located by the road side nearby and then return to Darent Urjyr.

The tracked objective reads like "Invalid Go,plz report to GM. QuestID 10624, Objid=2150". 

The ward stone can be found but nothing happens when interacted with.

**Comment by Meralors** [comment]
Fixed game object. You can complete this quest by interacting with Ward Stone. Also added a quest marker.

**Comment by Gakvar** [comment]
working properly. Thanks.
