### ISSUE TITLE
DC invite

### ISSUE THREAD

**Issue by Blubberino** [WarEmu/WarBugs#6311]
Sometimes when you are in IC and you get a group invite the game closes. Not sure what the reason for it is.

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format. 

You can help us by following these bugreport rules: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
