### ISSUE TITLE
[Quest] t4 dwarf ch 17 "Uncovering Undgrin Ankor"

### ISSUE THREAD

**Issue by Gakvar** [WarEmu/WarBugs#6312]
This quest starts with Durkin Kanstone and it requires the player to enter a series of tunnels nearby, investigate a few places and kill 10 Burrowing Fiends skaven.

The inspection objecties are completed from the start, but killing the Burrowing Fiends, which the cave is infested with, gives no credit for the quest's completion.

**Comment by Meralors** [comment]
Killing Burrowing Fiends should now update quest.

**Comment by Ziggesmuts** [comment]
Still dont working

**Comment by Evildoor** [comment]
"Fix pending" usually means "fixed next patch", not "fixed immediately".

**Comment by Gakvar** [comment]
It's fixed, thanks.

**Comment by wargrimnir** [comment]
Reopening, the Surveyed objectives are not automatically completed. Quest describes using an item near locations to advance.

https://i.imgur.com/U1o1azs.png

**Comment by wargrimnir** [comment]
Well apparently you can turn it in without them being completed. Still, I believe we have the ability to update this quest properly when we get around to it.

Also, the mob rates inside this cave are insane. Maybe clean that up a bit.

**Comment by sioding** [comment]
fixed with patch from 01.06.2019
