### ISSUE TITLE
[Quest] "Hand of Glory"

### ISSUE THREAD

**Issue by DSaunders91** [WarEmu/WarBugs#6313]
Destruction Tier 2 Ch 6 Ostland there is a quest called Hand of Glory; it requires you to do two things, Kill Faethel the Ragged and collect some Sacristy Candles. According to the quest description you should then have two items in your inventory; Sacristy Candles and Faethels Hand, then simply use Kumari's Ritual in your inventory to finish the quest however you don't have Kumari's Ritual and hence cannot finish the quest.

**Comment by Ryanfawkez** [comment]
Item script interaction is unsupported at this time.
