### ISSUE TITLE
Doors bugged by pets

### ISSUE THREAD

**Issue by Amalafein** [WarEmu/WarBugs#6314]
After hitting door in Praag and Thunder Mountain to ~60% with def and oil, the door said NullReferenceExeption was thrown. This Object will be destroyed. At the same time (both Praag and TM) a spiked Squig just said the same.

After this, doors were not targetable (is this a word?) for both sides

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
