### ISSUE TITLE
[Ability] Zealot - Aethyric Shock

### ISSUE THREAD

**Issue by Dmitrijv** [WarEmu/WarBugs#6315]
Point 13 Path of Alchemy ability that is supposed to deal ~400 dmg to target and stagger it for 6 seconds or until it's damaged.

Currently ability damage is applied after the stagger thus breaking the stagger immediately.

**Comment by Evildoor** [comment]
Proof.

**Comment by ozarmidrashim** [comment]
Falsely reported before: https://github.com/WarEmu/WarBugs/issues/4994

Closing.

**Comment by Dmitrijv** [comment]
Explain to me this then:
http://i.imgur.com/zLkMqYB.gifv

Maybe the ability damage is not what causes the stagger to break but w/e the cause may be it just doesn't the 6 seconds.

**Comment by Evildoor** [comment]
Mobs are not a good indicator for this, CC used on them is somewhat screwed.
