### ISSUE TITLE
"Welcome back : brotherhood" quest

### ISSUE THREAD

**Issue by Milord9** [WarEmu/WarBugs#6317]
We are supposed to collect cannonballs at the gates of Eckrund. The only map indication is an arrow asking to move east from the Eckrund RvR area to Mount Bloodhorn. At the gates themselves the only clickeable cannonballs are these ones but they are unusable.

![arhalian_026](https://cloud.githubusercontent.com/assets/17692456/15450626/de49ae22-1fa0-11e6-8daa-d995c2b0fc8c.jpg)

**Comment by Ryanfawkez** [comment]
As Order you're supposed to collect a crate on the Order side.
