### ISSUE TITLE
NPC: graphic issue, Kag Malosson has no head

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#6318]
The Npc for the quest The Shame of War, Kag Malosson, has no head.
![screen shot 2016-05-21 at 21 18 29](https://cloud.githubusercontent.com/assets/18053736/15450661/97bb9940-1f99-11e6-9f08-3027b0918838.png)

**Comment by Soulwhisper** [comment]
Fine.This can close. @Luth-RoR 
![warhammer online age of reckoning 11 06 2016 - 16 23 26 02](https://cloud.githubusercontent.com/assets/16864486/20038482/6564ae18-a43d-11e6-9f46-8e14451a1c6a.png)

**Comment by Soulwhisper** [comment]
@Luth-RoR Suffering again.Hmm? Each picture shows a diferrent model of the NPC.
![warhammer online age of reckoning 12 21 2016 - 11 16 02 02](https://cloud.githubusercontent.com/assets/16864486/21383574/1f005ad0-c76f-11e6-9213-14ea113231de.png)
