### ISSUE TITLE
Problems with unlocking chapters in ToK

### ISSUE THREAD

**Issue by AndmeA** [WarEmu/WarBugs#6320]
Hello,

I'm in T3 since 2 days, and today i went to Ork and Elves area's to do some PvP (which happened) to earn some INF pts. 

But the problem is that my bar doesn't appear on my screen. But it's not only the bar which is missing, but even in my ToK, the RvR - T3 area's for elves and orks doesn't appear at all. 

When i go to the PNJ for the rewards, i don't even see any item (only the 3 levels of rewards)

Btw, it's the first time it happend to me, i've unlock all T1/2 RvR area's without any problems ... And T3 Chaos is unlocked too.

And while fighting, i got INF pts as usual ... 

So here is the bug i encouter.

Ps : sorry for my poor english skill, hope someone will understand this :) ^^

**Comment by Vayra** [comment]
I've had the same issue in T2 with my Zealot over the past 2 days. Not unlocking the ToK pages for chapters or t2 rvr. 
I gain inf as usual, but cannot see the progress bars. Standard UI shows no progress, while Warboard shows full inf.
Talking to Rally Masters does not show any rewards when I ask to see them.
Charname: Cruzealot
Affected zones: T2 dark elf / chaos rvr, ch6-7 dark elf (that I have tested)

**Comment by Nyxxounnet** [comment]
I have the same problem with one of my chars. I cant see or get any influence rewards from all Tier, except T1 and i already get them.
I removed all my addons, relog, etc.. nothing changed.
Every thing is fine with all of my other chars, only for the last one >  Biffator - Destruction Choppa.
Here is a screenshot of my ToK and a rally master.

![biffator_000](https://cloud.githubusercontent.com/assets/19513120/15452524/100b02d4-1ff2-11e6-8aae-d1d1d259f2cd.jpg)

Nyxxo

**Comment by Bers2k** [comment]
create usable object at each rvr chapter, use this object - open ToK record

**Comment by AndmeA** [comment]
Did u have some example of an "usable object" ? I'm talisman maker, so can't do potions by myself ^^

**Comment by Bers2k** [comment]
many such examples, there are NPC, left-click on them opens some records in ToK
sorry for my "english"

**Comment by Evildoor** [comment]
Gentlemen, would you kindly wait for a dev response before discussing what makeshift changes can be made to solve this problem?

**Comment by nibblers** [comment]
Just my findings hopefully can be helpful:- (sorry for wall of text inc)

rolled an engineer (waiting for the oil/keeps to be re-worked).
did the usual quest lines down to grey lady, in there picked scavenge and talis making, did the kill 5 spiders and inspect dodgy customers quests in the tavern. ran a sc mourkin temple (we won) hit rank 5.
headed up road to wc usual route (on the road got the map pin for the windmill PQ) going by the medical tent and into che chapter camp next to the wc, talking to the kill collector and rally master doing that quest travel line. then straight up into wc, went direct to rally master and set rally point. did not check rewards (as no inf), then went round and picked up all the kill quests, sold junk and checked out gear, bought gun and spanner (wrench) then headed straight into rvr lake.
Solo. in middle of the zerg, and sniped off and aoe kills resulting in getting full inf (recieved the ding and saw T1 inf was full) and then a rank soon after. From overextending and a sorc burst ended up back in wc.
now the rally master has lost his icon from over his head. on opening the select influence rewards, theres the usual blurb, but it has no icons, no boxes just three black works basic medium advanced and Select is disabled.
TRied reloadui and nothing, so i logged out (did not exit) and back in straight away, the rally master now has his icon back, but its grey.
on entering it shows boxes, no icons or info. hovering over any it says do not have enough influence.
inspecting the war story, the only page I can get up is Empire story. in this, the prolouge is ???. Chapter one shows a 3rd way into basic, and chapter 2 is empty. then from here all empire is shown as ???
I had then re-entered the lake in nordland to see if the influence would reshow, the top right information panel bar is missing.
So flew to ekrund, got the map pin discovered ekrund, ran into lake, on the gun, the seargent had quest to defend the stonetower, i picked that up, went to tower and got the map pin on discovering stone tower bo.returned to wc. checked tome. nothing shows up in war story, the 'home' page is just the Empire story. Flew to elf and same, get the discovery, but not showing up in tok. 
Quit exited the game and relogged back in. Has now reverted back to the blank page just showing black basic advanced elite. no grey icon.
ran up to chapter 3 spoke to rally master, same blank page (but he does have grey icon over his head).
The ToK still is stuck showing only empire and chapters 1 and 2, but the infor looks correct for those two, rewards and pq' etc.

**Comment by AndmeA** [comment]
Looks like we're somes who have the same problems ...

Hope a dev will make a response ... I don't know if it's worth to keep getting inf in the area's concerned or not ? Would be sad to get back to 0 =(

**Comment by brinnande** [comment]
I had this same problem with t3 dwarf/orc. No influence bar/bugged, and nothing to select at rally master. I had only been on offence in badlands (playing order). I took at trip to black fire basin (defensive war camp), and t3 dwarf immidiatly unlocked, and my previously earned influance was there so nothing was lost, and items could be selected at rally master.

**Comment by Luth-RoR** [comment]
Yes, it shouls be only an UI issue. The server should still track your earned influence.

**Comment by Blaqwar** [comment]
The previous solution of running into the defensive side (Blackfire Basin) of Dwarven T3 pairing solved the bug for me. It unlocked the Dwarven T3 influence unlock in the ToK.

**Comment by Lheana** [comment]
I close this as it is old, and may be fixed by the changes I did about Greenskin Warcamp unlocks.
