### ISSUE TITLE
TM Order war camp

### ISSUE THREAD

**Issue by chakzo** [WarEmu/WarBugs#6324]
TM (Thunder Mountain) Order war camp accesable by destro range attacks

can provoke nice fights, 

issued to report

**Comment by Evildoor** [comment]
Screens/video.

**Comment by chakzo** [comment]
![chakzo_003](https://cloud.githubusercontent.com/assets/19510845/15479331/f562e1ca-211f-11e6-9249-a9ee72e26a53.jpg)
![chakzo_004](https://cloud.githubusercontent.com/assets/19510845/15479330/f5614036-211f-11e6-9101-397da3165c07.jpg)
![chakzo_005](https://cloud.githubusercontent.com/assets/19510845/15479332/f564ccce-211f-11e6-94e9-a6b54fb0a81d.jpg)

**Comment by saupreusse** [comment]
fixed in next patch.
