### ISSUE TITLE
quest: What's Inside is What Counts

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#6325]
acted according to 
http://warhammeronline.wikia.com/wiki/What's_Inside_is_What_Counts
but "Kraglorn the Maker" seems rather uninterested about the matter and does not interact.

**Comment by Lheana** [comment]
Little update : the item 'Mote of Zzangal'Nes Nalanel' correctly drops from the giant in Praag 'Geral The Dim', but interacting with Kraglorn the Maker does not provide the unlock
(Reward :Title = The Unflinching)

**Comment by Lheana** [comment]
Equiping 'Mote of Zzangal'Nes Nalanel' triggers the title but not the unlock 'What's Inside is What Counts'. Killed again 'Geral The Dim' but did not provide the unlock.

**Comment by Lheana** [comment]
I talked to 'Kraglorn the Maker' (West Praag), and it provided the unlock 'What's Inside is What Counts'.

**Comment by Ryanfawkez** [comment]
Yeah, slapped it onto Geral The Dim now as he's the NPC required to get the item.
