### ISSUE TITLE
Chapter 6 PQ bug?

### ISSUE THREAD

**Issue by Lioneyes** [WarEmu/WarBugs#6326]
Hello.  I have been trying for more than an hour to complete the PQ in Chapter 6 and it seems it is bugged.  I have been killing the Felde Refugees needed but the kills dont seem to count (stuck at 0/50).  I contacted a GM (Ayrion) and he advised me to log out and relog again.  It did not work.  I also used the command .reloadui and .unstuck in case they would help.  Nothing changed.  Please, advise.  Thanks in advance.

**Comment by Evildoor** [comment]
PQ name.

**Comment by Lioneyes** [comment]
Wayshrine of Sigmar, Stage 1


[image: photo] Giannis Sp Papagiannopoulos
Philosophy of Mind, Ph.D.

Email: extremio.music@gmail.com
Website: https://www.facebook.com/extremio
<https://www.facebook.com/extremio.page/?fref=ts>
<https://twitter.com/GiannisExtremio>
<https://www.youtube.com/user/JohnPapas74>
Get a signature like this: Click here!
<http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=&u=236980081917747>

On Sun, May 22, 2016 at 10:43 AM, Evildoor <notifications@github.com> wrote:

> PQ name.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/WarEmu/WarBugs/issues/6326#issuecomment-220819072>
>



-- 
*EXTREMIO*

**Comment by Evildoor** [comment]
#5518
