### ISSUE TITLE
Keep doors may be bugging due to pets

### ISSUE THREAD

**Issue by Dirox-Hirox** [WarEmu/WarBugs#6327]
![possiblekeepbug](https://cloud.githubusercontent.com/assets/7065919/15452051/5199a258-1fae-11e6-9bc4-fe4922498510.png)

When I arrived at a keep attack, the first thing I was going to do is summon my Magus pet, the second I did this, the keep door and my pet both said the error message in chat.  There may be a possible connection.

**Comment by Evildoor** [comment]
#6314
