### ISSUE TITLE
Keep door bugged

### ISSUE THREAD

**Issue by qualteia** [WarEmu/WarBugs#6328]
Eataine keep Arbor of Light door bugged at 40%, became untargetable, and in chat log said "[Keep Door] says: NullReferenceException was thrown. This object will be destroyed"
![hotnurse_000](https://cloud.githubusercontent.com/assets/16740013/15452084/7502cf04-1f9e-11e6-8d85-2d5a8fcccb69.jpg)

**Comment by Evildoor** [comment]
#6314
