### ISSUE TITLE
Ground target AoE abilities throwing exceptions

### ISSUE THREAD

**Issue by TatianaLinae** [WarEmu/WarBugs#6331]
I have a bug where when I go to cast Rain of Fire, I get the 10 second time bar, but absolutely nothing happens. 

I get this message: 

8177 Rain of Fire threw an unhanded NullReferenceException from Boolean object within Radius Feet ( WOrldServerObject.Int 32) . 

Thanks.

**Comment by TatianaLinae** [comment]
![tatyana_008](https://cloud.githubusercontent.com/assets/19512915/15452954/05d29554-1fbe-11e6-957f-c3e06fc8e150.jpg)

**Comment by spacestarkid13** [comment]
For me Pit of Shades works when I remove Close Quarters tactic.
![antifreeze_005](https://cloud.githubusercontent.com/assets/16030337/15497434/6b546934-21a3-11e6-9f0b-0d6aa7c66b96.jpg)
![antifreeze_006](https://cloud.githubusercontent.com/assets/16030337/15497444/755126de-21a3-11e6-87a6-a73de3465b45.jpg)

**Comment by Evildoor** [comment]
Possibly linked to Close Quarters - got several reports that exceptions appear when it's slotted.

**Comment by nibblers** [comment]
magus:
Using Close Quarters. all target abilities give exceptions

**Comment by Evildoor** [comment]
Adding "Fix Pending" per #6602.
