### ISSUE TITLE
Cart in Serpent's Passage

### ISSUE THREAD

**Issue by gomboni** [WarEmu/WarBugs#6332]
Engineers and magi can pull people inside environment objects like the little cart in front of Destro spawn. I am reporting this because once inside that cart you can't leave it by no mean but death.

**Comment by Evildoor** [comment]
This looks like general issue, similar reports:
#4369
#5971 
Not sure what to do. While it's possible to fix it for particular map spots, this requires placing walls or something to prevent people from getting to the object and is not an option in some cases.

**Comment by Luth-RoR** [comment]
Client issue.
