### ISSUE TITLE
Quest: Mouth of Miasma

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#6333]
The quest step to Find Mushroomed Ale should resolved by clicking on a barrel near a group of Orcs in the quest blob. Instead the Rotweed plants from the previous objective are showing up as the quest marker when you hover over them. I haven't been able to find any barrel that resolves this so far.

Shame too, the items appear to be correct.

**Comment by saupreusse** [comment]
seems to be fixed.
