### ISSUE TITLE
Bugged influence T2 Dwarf

### ISSUE THREAD

**Issue by Bers2k** [WarEmu/WarBugs#6334]
![sela_001](https://cloud.githubusercontent.com/assets/19250381/15452766/7a9e38fc-2013-11e6-99df-5ae1f7a8b6b0.jpg)
participated in the capture of the fortress 8 times I think has accumulated enough influence, but the book does not display progressive, curator also says not progressive, I can not get a reward....

**Comment by Bers2k** [comment]
I created another FM, brought him to the dwarf T2, book just did not register that I "discovered" this chapter. curator of the same issues buggy list of awards.

**Comment by Bers2k** [comment]
![abdula_000](https://cloud.githubusercontent.com/assets/19250381/15452941/9766555e-2019-11e6-8397-6cdae1dbbcae.jpg)

**Comment by Evildoor** [comment]
Tested on two characters, they successfully got page unlocked upon flying to Barak Varr.

**Comment by Bers2k** [comment]
Honestly, I can not understand how you could not reproduce it.i have download English client, created BW, arrived to the elves, took a neutral point... but in the book chapter does not open...
whats wrong with me?
![abdula_003](https://cloud.githubusercontent.com/assets/19250381/15453244/e95f4d30-2027-11e6-9422-de925669110a.jpg)

**Comment by Evildoor** [comment]
Oh, this falls into #6320 category, btw.
