### ISSUE TITLE
quest: Picked Clean

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#6335]
i was trying to tok unlock the "Keeper of Secrets" entry but nothing happens if i click on then "discarded bones" in t4 aetaine @ 47k,2k approx
source:
http://warhammeronline.wikia.com/wiki/Picked_Clean

**Comment by Lheana** [comment]
Still not working.

**Comment by Lheana** [comment]
Now interacting with 'Discarded Bones' correctly provides the unlock but not the associated title 'Herald of Temperance'.

**Comment by Lheana** [comment]
Fixed
