### ISSUE TITLE
Mines and Napalm not working (Exception msg)

### ISSUE THREAD

**Issue by Pumatouch** [WarEmu/WarBugs#6338]
It's quite hard to set any Mines or any Napalm as of right now. Getting Exception messages all over. Seen a few engis get away with doing it, but they are not aware of how to work around the issue themselves; pure luck.

![](http://i.imgur.com/sg05Vdf.jpg)

Taken to a different specc as of now, but being without Mines is a serious gimp. At least it seems as if Magus have same problem.

**Comment by Evildoor** [comment]
I presume it's #6331.
