### ISSUE TITLE
Engineer skill: Sticky Bomb applying to 6 enemies

### ISSUE THREAD

**Issue by Mcgotrek** [WarEmu/WarBugs#6339]
Yesterday, I was in a scenario. I used the skill "Sticky Bomb" and saw 5-6 bombs being applied to enemies instantly. I checked the combat log and they were in fact applied to several enemies. 
As stated, it's a single target skill (though it can detonate and damage several enemies), but the initial mechanic got to several enemies, so I thought you would know it.

Regards

**Comment by ozarmidrashim** [comment]
I see no probable cause for this, so as it's an edge case I won't investigate it further without proof.

**Comment by Luth-RoR** [comment]
Maybe the target was killed right after the debuff was applied; in this case: working as intended.
