### ISSUE TITLE
Pistols and Ballistic Skill

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#634]
There are some pistols (for WH of course, not for Engi) which have ballistic skill on them instead of strength, notable examples are Vengeance and Dominion ones. I know that this is not exactly a ROR bug, they are remnants of ancient WAR times, when WH needed ballistics, but still - can we fix what Mythic failed to fix?

**Comment by ozarmidrashim** [comment]
Done.

**Comment by Evildoor** [comment]
Thanks!

**Comment by Evildoor** [comment]
Strange. I clearly remember that this was fixed and i used Matchlock of Vengeance on my WH, with STR, but now it gives 13 BAL again. What happened? A mistake, i hope? Matchlock of Dominion is fine.

**Comment by Reggaewaldo** [comment]
This is an issue with the DB and the information that we currently have available.

I will have a look into this and see if we can make some standard rule or procedure to handle these types of issues in a painless way.

**Comment by Reggaewaldo** [comment]
Gameupdate 1.3 should have resolved this issue, but it seems like the online databases do not mirror this fix. 

Source: http://warhammeronline.wikia.com/wiki/Game_Update_1.3/Items

**Comment by Evildoor** [comment]
Fixed Matchlock of Vengeance.
