### ISSUE TITLE
[NPC] Bursar Whitefire. Quartermaster

### ISSUE THREAD

**Issue by ellionkeman** [WarEmu/WarBugs#6340]
T1 High elves war camp. Bursar Whitefire is an emblem quartermaster but sells only simple gear for money.

![alirtin_029](https://cloud.githubusercontent.com/assets/18136746/15453146/751cdce0-2012-11e6-89ef-3ed29acf89f7.jpg)

**Comment by saupreusse** [comment]
fixed in next patch.
