### ISSUE TITLE
Blue lines in lava

### ISSUE THREAD

**Issue by silodin** [WarEmu/WarBugs#6342]
visual bug with lava in cinderfall, seems to stretch across the map and only pop up over lava. lava also does no damage.
![silomun_008](https://cloud.githubusercontent.com/assets/18403822/15453275/07e5b928-2010-11e6-8452-03968ea3f9b3.jpg)

**Comment by Evildoor** [comment]
Lava damage was already reported. IIRC, blue lines were on live, so we cannot fix them.
