### ISSUE TITLE
Quest : Time to Waaagh

### ISSUE THREAD

**Issue by kkprfx** [WarEmu/WarBugs#6344]
hello, i did this q on my shaman and everything was normal.
today i tried to do on my marauder and it got bugged.
i was able to pick last step when i was 3-4 steps in or even earlier didnt notice.SS for proof. check quest log. i will still do the other steps so i'd appreciate if u dont remove my weap :)

![gavlistos_001](https://cloud.githubusercontent.com/assets/19504946/15453407/61d08a46-201d-11e6-9697-ea9864fdb06e.jpg)

**Comment by Evildoor** [comment]
#6216
