### ISSUE TITLE
Butchering, Extenders, Apothecary

### ISSUE THREAD

**Issue by swbf2fan2510** [WarEmu/WarBugs#6345]
Boars and Tusgors doesn't drop extenders. 

To be specific as far as i have checked the boars in Black Crag named - Cragback Tusker - doesn't drop extenders.

And in Apothecary the butchered stimulants you get from Boars and Tusgors Apothecary level 175 - 200 can't be put in ingredients when crafting. #apothecary #butchering

**Comment by Evildoor** [comment]
#4709 may be related.

**Comment by wargrimnir** [comment]
There's a bunch of things listed on the wiki that would be helpful to check if they're dropping properly. http://warhammeronline.wikia.com/wiki/Apothecary/Modifiers/Duration

**Comment by Kaelang** [comment]
As this is a legacy issue, and lots has changed, please re-open if this issue persists as it should be fixed.
