### ISSUE TITLE
Chaos Wastes Screamer Cape

### ISSUE THREAD

**Issue by Dichnich** [WarEmu/WarBugs#6347]
The champion at Chaos Wastes 6K 25K doesn't complete the quest to get the screamer cape.

**Comment by Evildoor** [comment]
Quest name.

**Comment by Ryanfawkez** [comment]
"Cape of the Screamer", comes from killing the level 33 champion Vilemaw in Chaos Wastes.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
