### ISSUE TITLE
Thunder Mountain Titel "The Rhino Rocker"

### ISSUE THREAD

**Issue by Dichnich** [WarEmu/WarBugs#6349]
Clicking the Rhinox Bonepile at the edge of a Lava Lake gives Exp but no titel.

**Comment by Evildoor** [comment]
Unlock name.

**Comment by Dichnich** [comment]
Location for the Titel is shown here. 
http://warhammeronline.wikia.com/wiki/The_Rhinox_Rocker
Got exp and the message that I learned something about rhinos. Would be a nice to have, but no priority.

**Comment by Evildoor** [comment]
#5721
