### ISSUE TITLE
quest: Grab the Bull By the Horn

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#6350]
trying to unlock tok->bestiary->beastmen->doombull
following
http://warhammeronline.wikia.com/wiki/Grab_the_Bull_By_the_Horn
but clicking on  "Pile of Bones"  in t4, Dragonwake @ 64k,29k approx nothing happened.

**Comment by thorbolt80** [comment]
It's works now.

**Comment by Algenubi** [comment]
Unlock doesn't work. Clicking on pile of bones gives nothing.
