### ISSUE TITLE
[T3 BFP Rally Master] Gark da Kroosha not giving out inflooenz rewards.

### ISSUE THREAD

**Issue by Krumlok** [WarEmu/WarBugs#6352]
![sin titulo](https://cloud.githubusercontent.com/assets/14275335/15454413/5ed4a686-2038-11e6-990a-e9a34508be93.png)

Doesn't let me select anything, so it's not a visual bug. It's also not fixed by relogging.

**Comment by lilimx** [comment]
fixed
