### ISSUE TITLE
Expert Skirmisher and Land Mine

### ISSUE THREAD

**Issue by HappyCultist** [WarEmu/WarBugs#6354]
I get the following error message when using land mine with expert skirmisher slotted.
1524 Land Mine threw an unhandled NullReferenceException from BooleanObjectWithinRadiusFeet(WorldServer.Object, Int32).

![kepler_001](https://cloud.githubusercontent.com/assets/19478623/15454557/690eaa44-203c-11e6-83a6-c1c01e70932e.jpg)

**Comment by Evildoor** [comment]
Post this in #6331.
