### ISSUE TITLE
Dark Elf T4 - Xiphos of Remembrance

### ISSUE THREAD

**Issue by freshour** [WarEmu/WarBugs#6355]
Has strength, INITIATIVE, WILLPOWER - if its a healing wep str needs swapped to wounds maybe, but it seems more of a melee wep, so maybe Str - reduced chance to be parry would make it a unique one to compete with dwarf rvr wep.

**Comment by wargrimnir** [comment]
Bugtracker should not be used for balance. This can be closed.
