### ISSUE TITLE
Quest - And Thus With Traitors

### ISSUE THREAD

**Issue by sinderhella** [WarEmu/WarBugs#6356]
I am unable to attack the Arkaneth Turncoat during this portion of the quest.
![sinderhella_011](https://cloud.githubusercontent.com/assets/19142979/15455223/3975311a-2003-11e6-9b69-e0a9b8682d0b.jpg)
![sinderhella_013](https://cloud.githubusercontent.com/assets/19142979/15455224/3d7243de-2003-11e6-9332-6a160a5798f5.jpg)

**Comment by Evildoor** [comment]
#2042
