### ISSUE TITLE
TOK - The Hornsnapper

### ISSUE THREAD

**Issue by sinderhella** [WarEmu/WarBugs#6357]
I have completed the entry A Little Off The Top to get the title The Hornsnapper but it does not show properly in the TOK.  It shows credit for the pegasus unlock Do You Know the Way which is supposed to give the title The Hornblower.

![sinderhella_008](https://cloud.githubusercontent.com/assets/19142979/15455237/7b225750-2003-11e6-84b0-b60750a8ad23.jpg)
![sinderhella_009](https://cloud.githubusercontent.com/assets/19142979/15455238/7b3852d0-2003-11e6-8157-5ece9b354165.jpg)
![sinderhella_010](https://cloud.githubusercontent.com/assets/19142979/15455239/7b44e608-2003-11e6-9d90-3e47b6574f35.jpg)

**Comment by Ryanfawkez** [comment]
http://warhammeronline.wikia.com/wiki/Do_You_Know_the_Way - fully working as intended.

http://warhammeronline.wikia.com/wiki/A_Little_Off_the_Top - unlock comes from killing Sylendoras, title is unlocked by right clicking the horn he drops.

**Comment by sinderhella** [comment]
Not working as intended I did the quest for A Little Off the Top for the Hornsnapper title, which the game gave me but the TOK shows credit under the Pegasus for Do You Know The Way and not A Little Off the Top.
