### ISSUE TITLE
Quest - Breaking the balance

### ISSUE THREAD

**Issue by sinderhella** [WarEmu/WarBugs#6358]
The quest is to kill Soliraen Goldthorn and claim any information that he might have that concerns other mages.  The mob does not drop anything to complete the Read the Edict of the White Tower portion of the quest.  The mob is in three places in the identified map area and none of them drop the needed item.  There are no books or chests in the nearby tents either that are clickable to give you the information either.

**Comment by wargrimnir** [comment]
Drop a scroll on the ground to click at 9940,39360, that should suffice for the quest. There's also a double spawn of this NPC nearby.
