### ISSUE TITLE
mobs sometimes not following

### ISSUE THREAD

**Issue by Natherul** [WarEmu/WarBugs#6362]
sometimes when attacking mobs (especially noticeable when pulling a large amount of mobs) they will just stand there and look at you.

They can be attacked fine and they will attack you if you move up to them but they will remain stationary.

**Comment by Kaelang** [comment]
Appreciate this is a dated report - however this does not provide enough information to identify the issue and/or replicate the problem. Please re-open this issue if this persists in the latest version of RoR.
