### ISSUE TITLE
Quest: Cleansing an Empire. Rewards for Runepriest

### ISSUE THREAD

**Issue by khazadson** [WarEmu/WarBugs#6365]
When you complete last quest of the chain you can choose one of three rewards: two staffs and **one-handed axe**. 
See screenshots attached.  

![ce1](https://cloud.githubusercontent.com/assets/19366027/15455982/ab6af0ee-206b-11e6-8202-ec01b3552698.jpg)
![ce2](https://cloud.githubusercontent.com/assets/19366027/15455985/b82b736c-206b-11e6-8b0e-7525cabf4dd4.jpg)

**Comment by Torquemadra** [comment]
item skill missing, added
