### ISSUE TITLE
RvR Influence rewards not showing

### ISSUE THREAD

**Issue by Carebucket** [WarEmu/WarBugs#6366]
Happened to me in T1 but other people saying it also happens in other tiers. You come into the zone even tho you haven't been there at all and your influence is already maxed out and you can't even see the rewards on rally master.
![neiglen_000](https://cloud.githubusercontent.com/assets/19345079/15456013/4bb5892e-206c-11e6-94f4-505d794fc2db.jpg)

**Comment by LittlefishSail** [comment]
Confirmed, at least for T2.  Had several kills and one zone flip in T2 Dark Elf, and the Rally Master and Tome don't even recognize that I've been to the zone, much less contributed or won influence.  (As of 5/22/16)

**Comment by Evildoor** [comment]
#6320
