### ISSUE TITLE
Non-pack relative monsters linked together when being attacked.

### ISSUE THREAD

**Issue by Ellipsis9** [WarEmu/WarBugs#6367]
When pulling Hill Crushers for part 1 of the "Welcome to Troll County" public quest in Empire chapter 5, pigs will also occasionally be pulled with them and attack you.

**Comment by noisestorm** [comment]
as a lot of different stuff is too - mob linking is in alpha and was just newly added. i'll be so free and edit your title a bit since this is generally the case

**Comment by Lheana** [comment]
I guess this is fixed.
