### ISSUE TITLE
Cleave Limb

### ISSUE THREAD

**Issue by Keitter** [WarEmu/WarBugs#637]
Does the White Lion ability Cleave Limb work correctly? 
A sundering blow which deals damage and inflicts your victim with an Ailment which reduces their autoattack speed by 20% for 10 seconds.
OR after White Lion update patch 1.05 it became
Cleave Limb: This ability now snares the target for 10 seconds. The ability no longer reduces auto attack speed.

Just a request for you to review this ability really as I noticed it is not mentioned on the excellent and comprehensive forum post Current State of Classes and Abilities.

**Comment by ozarmidrashim** [comment]
Apologies for not having updated that thread. Cleave Limb works as advertised.
