### ISSUE TITLE
Quest: Betrayal from Within

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#6370]
http://i.imgur.com/Fe2r2Vj.png

Neat, but I don't recall any Bastion Stair scenario. Londo should totally get on this.

Really it should be changed to state instance instead of scenario.

Same issue with the quest Overwhelming Odds, but for Mount Gunbad scenario.

**Comment by Ryanfawkez** [comment]
These are simple dungeon quests, changed the descriptions to speak to respectively mentioned quest NPCs.
