### ISSUE TITLE
Quest: A Cold One Nuisance

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#6371]
http://i.imgur.com/3gr3R0v.png

Darkscale Cold Blood creatures do not advance the quest, they make up a majority of mobs in the area. There are a few Darkscale Cold One mobs in the area, so it's completeable. If possible, add the first mob to the quest requirements, they're in the quest description as a target, and hovering over them does show them as an objective.

**Comment by Meralors** [comment]
Halved the number needed of Cold one and added  5 Cold Blood to the quest objectives.
