### ISSUE TITLE
Lowbies getting bags in T4 PQ's 

### ISSUE THREAD

**Issue by Unknown** [WarEmu/WarBugs#6373]
I have seen lowbies (lvl 6-12ish) at the DW Furnace PQ getting rolls multiple times since the last patch.  Today I witnessed a lvl 8 Sorc get a White bag, and a lvl 9 SH get a green bag.  Haven't seen any lowbies get a gold yet, but they are stealing rolls/bags from people that actually belong there.  Please fix.

**Comment by Unknown** [comment]
On another note, it seems you can still AFK in PQ's and get bags thanks to the persistence roll buff. Witnessed a Mara afk on bridge for about 2-3 cycles of the PQ and he won a bag.  Please don't remove the persistence buff, but please rework the contribution system so that 1) you can't get a roll unless you are eligible for T4 bolster; and 2) make it so you not only get zero contribution bonus, but zero roll just for being in the PQ area without actually contributing.

Thank you.

**Comment by wargrimnir** [comment]
Patch notes today should address some of this issue.

**Comment by Evildoor** [comment]
Fixed in today's patch.
