### ISSUE TITLE
Pit of Shades - Not Work.

### ISSUE THREAD

**Issue by Malacabada** [WarEmu/WarBugs#6375]
Hello, my name is Marco, my nickname is Malacabada (Sorceress).

I have a problem when using the skill Pit of Shades, it does not work.
She comes to inform the cooldown, but which indicate the site for damage, does not report the damage the screen and does not cancel when I walk.

And I can not use it because it does not work, it does animation but does not work simply.

Grateful.
Marco Soares.

**Comment by Evildoor** [comment]
Screenshot.

**Comment by Enoelxx** [comment]
hallo,

ich habe hier das selbe problem, diese fehlermeldung kommt dann

![enoelxx_017](https://cloud.githubusercontent.com/assets/19532295/15471210/1abe7f40-20f5-11e6-9094-9ecec7fd79c4.jpg)

ich hoffe das hilft euch weiter

**Comment by Abolition** [comment]
It could be an issue with the terrain where it is being casted. Sometimes I cast it in an area within range and I think it probably tries to place it on the bottom of the world?

**Comment by Evildoor** [comment]
If Enoelxx's screen is correct, then it's #6331. @Malacabada ?

**Comment by Malacabada** [comment]
Maybe.

Screen in sequence:
1º
![malacabada_001](https://cloud.githubusercontent.com/assets/19522596/15480322/59b401b0-20fb-11e6-9db9-a522d31a91ed.jpg)

2º
![malacabada_002](https://cloud.githubusercontent.com/assets/19522596/15480333/65f9a59c-20fb-11e6-9659-474b3af759de.jpg)

3º
![malacabada_003](https://cloud.githubusercontent.com/assets/19522596/15480347/78ae3b08-20fb-11e6-8838-726047fda961.jpg)

4º
![malacabada_004](https://cloud.githubusercontent.com/assets/19522596/15480353/806078de-20fb-11e6-8ab7-b02afeb2fa39.jpg)

5º
![malacabada_005](https://cloud.githubusercontent.com/assets/19522596/15480358/88fe29aa-20fb-11e6-8521-be8e09c944e0.jpg)

**Comment by Evildoor** [comment]
Check the other chat tabs please. Are there any exceptions thrown?

**Comment by Malacabada** [comment]
![malacabada_006](https://cloud.githubusercontent.com/assets/19522596/15486721/1d160460-211e-11e6-963e-ad068de1e631.jpg)

**Comment by Evildoor** [comment]
Yes, it's #6331.
