### ISSUE TITLE
Ebon Flame Quest Wrong Step

### ISSUE THREAD

**Issue by Shadowgurke** [WarEmu/WarBugs#6376]
The Ebon Flame Quest is bugged after the last patch. It seems that the ending quest NPC is wrong in the database. The quest is supposed to direct you to Telethir Bloodbrow (as stated in the questlog and shown on the map). However, as shown on the screenshot, it requires you to talk to Mathlas Nightwyrm instead. This NPC is not in the encampment nor can I find him on google.
This video from Mazadun shows how the quest used to work 
https://youtu.be/0tySKwkiD0c?t=122

![image](https://cloud.githubusercontent.com/assets/1018113/15458212/61f924ae-2097-11e6-9252-9c0783538ba7.png)

**Comment by Torquemadra** [comment]
fine in the database, that requirement is not in the mission, can only suggest trying again after a server boot

**Comment by Shadowgurke** [comment]
Reboot changed the original quest. Bugged quest remains but on abandoning + reaccepting the quest, it is updated.
