### ISSUE TITLE
Standard duplication

### ISSUE THREAD

**Issue by JohnLandi** [WarEmu/WarBugs#6377]
### Steps to reproduce:
1. Have a standard out.
2. Die while holding the standard
3. Pick up the standard
### Expected results:

You will not have a standard in your inventory, as it should be on the ground.
### Actual results:

You will still have the standard in your inventory and you can pick up the one off of the ground as well. This results in being able to duplicate standards.

**Comment by MaxHayman** [comment]
Assume this is fixed as it was before the standard rewrite.
