### ISSUE TITLE
5pc Mercenary bonus mastery point bug

### ISSUE THREAD

**Issue by Mountainz** [WarEmu/WarBugs#6379]
When you equip 5pc merc gear its actually taking a mastery point away from your total available points. It still drops the point in to the appropriate tree though
![mountain_028](https://cloud.githubusercontent.com/assets/16036733/15458751/f304c4d4-206b-11e6-9cd2-05c7179b393a.jpg)
![mountain_029](https://cloud.githubusercontent.com/assets/16036733/15458753/f83bbe80-206b-11e6-8547-7123c8deb8fd.jpg)

**Comment by Uchoo** [comment]
Can confirm, I only have 25 points available at RR40.

**Comment by dalgrimar** [comment]
Same here

**Comment by Styrkarr** [comment]
Same for all the 5pc bonus.

**Comment by Mercenery** [comment]
can confirm too (WH-set)

**Comment by Torquemadra** [comment]
may or may not have been resolved, can you repost if still an issue

**Comment by Blubberino** [comment]
Tested it with ruins from zealot and works now.

**Comment by taccr** [comment]
This was hotfixed together with https://github.com/WarEmu/WarBugs/issues/6020 2 days ago.

**Comment by genisaurus** [comment]
Closing, fixed in recent patch.
