### ISSUE TITLE
Mastery points bug

### ISSUE THREAD

**Issue by Farheim** [WarEmu/WarBugs#6382]
Having this since the last patch (just woke up and saw that). And they actually work, i can take new skills, tactics and all. 
http://imgur.com/a/JICt0

UPD: it's about obliterator 3p bonus, when i equip all pieces i'm gettin dem points.
http://i.imgur.com/McnAJBb.jpg

**Comment by Farheim** [comment]
Also not fading after restarting game and reloading ui.

**Comment by Evildoor** [comment]
#6020
