### ISSUE TITLE
Power From the Gods

### ISSUE THREAD

**Issue by Uchoo** [WarEmu/WarBugs#6384]
On live, this tactic gave a flat AP return per second, rather than adding to AP regeneration. For example, you could use Flee and regain AP or use Hold the Line and maintain AP.

**Comment by Evildoor** [comment]
Oh really? But this thread:
https://www.returnofreckoning.com/forum/viewtopic.php?f=11&t=8768
allows me to say "Screw how it was on live!". I suggest everyone reporting abilities to read it before posting.

**Comment by Uchoo** [comment]
I was simply attempting to point out a known difference from live but thank you..
