### ISSUE TITLE
Ram crashed after hit with oil

### ISSUE THREAD

**Issue by kaey** [WarEmu/WarBugs#6388]
After today's patch, we attacked keep drakebreaker's scourge in dragonwake.
As soon as ram got hit with oil at inner doors, it crashed.
![1](https://cloud.githubusercontent.com/assets/3503165/15465767/f5706142-20de-11e6-96b3-a4b103fb48ff.jpg)

**Comment by kaey** [comment]
Then we tried attacking Wrath resolve in caledor, both oil and ram stopped taking damage at 27% hp
and door was always at 100%

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by kaey** [comment]
It was fixed a few weeks after.
