### ISSUE TITLE
Mercenary 5 piece bug 

### ISSUE THREAD

**Issue by Daknallbomb** [WarEmu/WarBugs#6389]
The magus mercenary 5 piece bug dont works correkt . 
The Bonus mastery point isnt given and u cant skill like http://waronlinebuilder.org/#career=mag;9;13;0;9:;7:9:11:13:;;;0:0:0:0:

miss one mastery point ;( 

u got 26 mastery points , and if u wear 5 piece set u got just 25 (and one is skilled in havoc)

**Comment by Evildoor** [comment]
#6379
