### ISSUE TITLE
Flightmaster deviations

### ISSUE THREAD

**Issue by Skilorian** [WarEmu/WarBugs#639]
Quite a few times while using the flightmaster I "land" away from the flightmaster.  I am either in the water behind the large boat in blighted Isle. I've ended up almost in the Grey Lady Coaching Inn while flying to Nordland. When traveling to Altdorf I have just been given a light blue screen and can't move, though I have been able to use my book of binding.  I haven't traveled much to Ekrund, but every time I've ended up where I'm supposed to be.

**Comment by Evildoor** [comment]
This problem still persists for anyone? I remember this problem, and how it got even worse when additional T2 zones were opened, but then some fixes were implemented, and after that i've got no troubles with flying. Light blue screen (Zone 0) is a different problem.

**Comment by Reggaewaldo** [comment]
No this should not be present anymore.

**Comment by Evildoor** [comment]
Ok, let's leave this as is for now, and after few days i'll close this if nobody else responds.
