### ISSUE TITLE
[RVR] convent of flame dw keep oil bug/ edit: all sieges weapons bug

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#6390]
keep switch between full healt and low hp on my screen, it also get damages but healt bar dosen't get reduced

edit: all sieges weaposn are currently bug this also include oil and not ram, they all can't get destroyed after reached a 25-30% life for some reason even if they nomaly drop until that %.
All these sieges weapon had the first 2 lines behaviour.

**Comment by Dirkdaring** [comment]
Yep didn`t try any other keeps but Dest keep in Dragonwake, last night after the patch, we had 4 cannons all hitting the outer oil on the keep, the oil was already at 25 % when we started and it never went any lower after 10 min of us hitting it with 4 cannons and no one on the oil it still wouldn`t go below 25 % hp.

**Comment by Tesq** [comment]
fixed
