### ISSUE TITLE
Chaos Wastes: empire Ch 20: duplicate NPC: Cuthbert Lawry

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#6392]
This NPC has a clone in the same camp and the quests are doubled.
![urmig_000](https://cloud.githubusercontent.com/assets/18053736/15468798/1e2bc8a2-20de-11e6-820e-645ea3075bf0.jpg)
![urmig_001](https://cloud.githubusercontent.com/assets/18053736/15468807/224a10a6-20de-11e6-8ee2-a6d2df6283d1.jpg)

Apparently the model is different.

**Comment by Ryanfawkez** [comment]
There's another spawn of his in Praag, right outside Empire Chapter 17.

**Comment by Ryanfawkez** [comment]
Removing his two double spawns. They may be required for a certain quest, but since I can't tell it's safe to assume they're invalid.
