### ISSUE TITLE
Keep siege rolls are not showing (T4)

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#6394]
After defending the Keep from a siege the scoreboard shows all zeros.

![wh1](https://cloud.githubusercontent.com/assets/18053736/15471302/2eae613a-20ed-11e6-972b-cf63a71c65de.png)

**Comment by Soulwhisper** [comment]
#5878 Dont know whats happening.Geni said that it should have been fixed and he closed it.

**Comment by Soulwhisper** [comment]
Its not PQs issue.Only happens in Keeps Loot Rolls.
PQs show correctly the score.

**Comment by MerryGitmas** [comment]
By the way, i was not first so the visual bug about contribution persists

**Comment by Soulwhisper** [comment]
Its works fine on T3
