### ISSUE TITLE
Gatestones

### ISSUE THREAD

**Issue by Blubberino** [WarEmu/WarBugs#6396]
Building a gatestone is currently only giving a error message.

![valfaros_016](https://cloud.githubusercontent.com/assets/16993024/15473441/61d09cbe-2100-11e6-98a0-17df9156093e.jpg)

**Comment by Soulwhisper** [comment]
Probaply its not implemented yet.

**Comment by Evildoor** [comment]
Similar to #2659.

**Comment by Blubberino** [comment]
Yep did not know what the order equivalent is
