### ISSUE TITLE
RR bug (?)

### ISSUE THREAD

**Issue by Morrdread** [WarEmu/WarBugs#6399]
I have reached rr40 but the counter will not flip to 40 and allow me use of the final rr point. After an entire morning I am stuck at rr39, even though the counter reads 0rr left to gain.
![ladydread_022](https://cloud.githubusercontent.com/assets/18380142/15474731/1abcc766-20d4-11e6-9742-bff93b8c5b6c.jpg)

**Comment by Morrdread** [comment]
yes i logged out and back and re started the game

**Comment by Evildoor** [comment]
I presume that you were 35/39 before T4 patch and only logged on now. Currently your renown rank cannot be higher than your level.

**Comment by Evildoor** [comment]
No objections to my comment, closing.
