### ISSUE TITLE
"Enroaching Darkness" Unsual text in quest objective

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#64]
Displaying the strange text in objectives as seen in case #55 

It can be located at the "Traitor's crossing" just south of the Order WC.

![enroaching darkness](https://cloud.githubusercontent.com/assets/7492543/2917221/4c1bcddc-d6c3-11e3-853c-6388482b06c9.png)

**Comment by Reggaewaldo** [comment]
Confirmed this working.

This can be closed.
