### ISSUE TITLE
world issues

### ISSUE THREAD

**Issue by Skilorian** [WarEmu/WarBugs#640]
getting kicked to character screen between zones.  Logged back into this...
![skilor_006](https://cloud.githubusercontent.com/assets/11249555/6428470/f8289306-bf68-11e4-8dcf-375ac25a49bc.jpg)

**Comment by Thorgatin** [comment]
Known. Try the "book of binding" or /stuck.

**Comment by Evildoor** [comment]
Known zone 0 bug.
