### ISSUE TITLE
[Quest] t4 dwarf ch 18 "Leave None Behind!"

### ISSUE THREAD

**Issue by Gakvar** [WarEmu/WarBugs#6401]
This quest has 3 objectives:

Kill Ogshak
Rouse Dwarfs
Kill Ogshak's Greenskins

Problem is there are only Ogshaks and Og's Finishers in the area, no greenskins that award credit for the quest completion. The other 2 objectives are fine.

**Comment by Ryanfawkez** [comment]
Og's Finishers will contribute towards completion now.

**Comment by wargrimnir** [comment]
There's a bunch of duplicate spawns for Ogshak around as well.

**Comment by Lheana** [comment]
Quest works fine, and there is only one spawn of Ogshak left.
