### ISSUE TITLE
[Quest] t4 dwarf "What We Came For"

### ISSUE THREAD

**Issue by Gakvar** [WarEmu/WarBugs#6402]
This quest starts with Morgrin Goldbeard and requires the player to kill Bloody Sun Greenskins and blow up trash piles by the huts in front of Emberlight Mine nearby.

Instead of tracking the trash piles blown up the tracker says: "Invalid Go,plz report to GM. QuestID 18002,ObjId=907"
No Greenskins in the area award credit for the completion  either.

**Comment by saupreusse** [comment]
fixed.

**Comment by Gakvar** [comment]
will it be fixed only in the next patch or should it be fixed right now?

**Comment by Evildoor** [comment]
> Fix pending = fixed next patch. Also, ticket is still open.
