### ISSUE TITLE
[Quest] Unholy - Praag

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#6408]
Hi this quest appears to have errors in the tasks and as well autocompletes.

**Comment by iljuro** [comment]
I'm pretty sure the "Dark Flame" of the task "Find Dark Flame" is on top of the stone tower at 62,50 in West Praag. Unfortunatly the door is not active.

**Comment by Ezella** [comment]
The tower at 62,50 in West Praag and the Dark Flame inside are now accessible.

![1 unholy](https://cloud.githubusercontent.com/assets/18719012/18799959/d923ef24-81da-11e6-94e6-23bd386e1ce9.jpg)

![2 unholy](https://cloud.githubusercontent.com/assets/18719012/18799975/e0627968-81da-11e6-831f-a908d32cc90a.jpg)

**Comment by Ezella** [comment]
Quest marker for target area on the map is still missing (62,50 in West Praag).
