### ISSUE TITLE
5/5 Mercenary Bug - Mastery Points

### ISSUE THREAD

**Issue by Hamere** [WarEmu/WarBugs#6409]
I have found that when one gets 5/5 Mercenary (+1 to a skill tree) and talk to the Mastery trainer, they are offers 255 Mastery Points.
![hamere_114](https://cloud.githubusercontent.com/assets/19538674/15481689/c14cc796-20f9-11e6-87f2-5a4f26cc56c5.jpg)
 This seems like a fairly major issue. When one tries to spend these points, their tree is reset, though the last ability they got will be available.
![hamere_116](https://cloud.githubusercontent.com/assets/19538674/15481757/248d4bc8-20fa-11e6-8f6b-a4ebaf4e6d21.jpg)
Hopefully this issue can be fixed. I hope this has helped.

**Comment by Blubberino** [comment]
#6020
