### ISSUE TITLE
Summon mount possible in water/lava

### ISSUE THREAD

**Issue by redcloudpl** [WarEmu/WarBugs#6411]
Wondering through Cindefall i realise that it is possible to go through lava (doesnt kill you) and also I can summon my mount and travel quicker. I checked this also in water in Dragon Wake and you can mount. You have to try twice or three times before you mount your horse (if u click once-no effect).

![thaer_013](https://cloud.githubusercontent.com/assets/16903246/15485883/42d3332a-2142-11e6-9363-4915f202ef00.jpg)
![thaer_014](https://cloud.githubusercontent.com/assets/16903246/15485882/42d19844-2142-11e6-8fe0-e66eea2f9766.jpg)

**Comment by Evildoor** [comment]
Combination of #798 and #5729.
