### ISSUE TITLE
Vultures in lava

### ISSUE THREAD

**Issue by redcloudpl** [WarEmu/WarBugs#6412]
I've noticed them in Cinderfall.

Also there are some vultures sitting in "deadly" lava?

![thaer_011](https://cloud.githubusercontent.com/assets/16903246/15485975/c6a5b63c-2142-11e6-8eab-8c8cc0929797.jpg)
![thaer_012](https://cloud.githubusercontent.com/assets/16903246/15485976/c6a8c85e-2142-11e6-92ab-e39e339ce723.jpg)
![thaer_013](https://cloud.githubusercontent.com/assets/16903246/15485977/c6a945ea-2142-11e6-95d4-b83bc3f51c81.jpg)

**Comment by Evildoor** [comment]
As i already said elsewhere, lines in lava were on live and we cannot fix them.

**Comment by Ryanfawkez** [comment]
The lines aren't the issue here, @Evildoor. The Vultures casually sitting in the lava are.

**Comment by Evildoor** [comment]
And? That's exactly the reason why i renamed the issue to "vultures in lava" instead of simply closing it.

**Comment by Ryanfawkez** [comment]
@Evildoor - I see the change now. I'll just remove the vultures and close this.
