### ISSUE TITLE
Quest: Cleaning up Saphery

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#6413]
Unable to find the Gleaming Shard indicated in the quest description that allows you to create the concoction and finish the quest.

Should be around 208 1472253 1517517 9097

**Comment by wargrimnir** [comment]
Found it in the Southern Stonewind Cavern. http://i.imgur.com/S9VmCXi.png

Still, could we get a second quest blob for the area?

**Comment by Ryanfawkez** [comment]
Nope. Can only have one quest marker per quest at the moment.
