### ISSUE TITLE
HE Ch 14 PQ: Against All Odds

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#6414]
Rock Lobbers are sentient creatures! They're set to passive, but can be attacked, can't be killed, and proceed to attack you despite being at 0 hp.

http://i.imgur.com/P4hLykF.png

**Comment by Meralors** [comment]
Finaly fixed ( took me forever.. ). Rock lobber will now act as normal siege weapon.

**Comment by wargrimnir** [comment]
Great! Now you just need to do all of the other siege weapons in the game that act the same way ;)
