### ISSUE TITLE
PVE: Threat

### ISSUE THREAD

**Issue by Gooboo1** [WarEmu/WarBugs#6416]
Threat is really buggy in this game. A chosen with a tactic to increase threat by 100% and a magus with a 50% less threat tactic shouldn't be able to pull off of the chosen after waiting 10s to let him build threat shouldn't pull using two abilities. And after the chosen uses his aoe taunt it does not agro them sometimes.

**Comment by Evildoor** [comment]
PVE threat mechanics is pretty much not implemented, no need to report such things.
