### ISSUE TITLE
[Quest] t4 dwarf ch19 "Tapping the Vein"

### ISSUE THREAD

**Issue by Gakvar** [WarEmu/WarBugs#6417]
This quest directs the player to go into Karkarag Mine in Death Peak and gather Ore Samples. There is no indication on the map where Karkarag MInes is or any quest specific marks indicating the location.

Upon entering a cave called Webspun Hollow, I found some objects on the ground named Ore Samples that I can target, but they award no credit for the completion of the quest. At no point the world is telling me I'm entering the Karkarag Mines.

**Comment by saupreusse** [comment]
fixed the ore samples. couldnt fix the questmarker yet.

**Comment by Gakvar** [comment]
can't interact with them yet. is the fix online?

**Comment by Evildoor** [comment]
Fix pending = fixed next patch. Also, ticket is still open.

**Comment by Ryanfawkez** [comment]
Questmarker added now.
