### ISSUE TITLE
[Quest] t4 dwarf ch19 "A Prod in the Right Direction"

### ISSUE THREAD

**Issue by Gakvar** [WarEmu/WarBugs#6418]
This quest directs the player to find a lost regiment of dwarfs inside Blisterclaw tunnels in Death Peak. There is no indication on the map of where that place might be.

Upon exploring a cave called Bristle Cavern, that has lots of Blisterclaw skaven fighting greenskins outside, in Death Peak, I found a number of injured dwarves hiding in there, one of them named Grundnir Stonebearer with an incompleted quest on his head, but my quest doesn't complete when I interact with him.

**Comment by Ryanfawkez** [comment]
Grudnir Stonebearer is the hand-in NPC, I will also mark him as the quest objective to make it completable.
