### ISSUE TITLE
Order T1 RvR Rally Master Broken

### ISSUE THREAD

**Issue by TwistyRainbow** [WarEmu/WarBugs#6420]
The Rally Master for Order t1 RVR does not show any available influence rewards, even though my character is up to full influence.

**Comment by Evildoor** [comment]
And the page in ToK fails to unlock?

**Comment by TwistyRainbow** [comment]
The page in ToK did not unlock, but the influence bar shows up when I'm in
an open RVR area, as shown in this screenshot.

On Tue, May 24, 2016 at 12:30 AM, Evildoor <notifications@github.com> wrote:

> And the page in ToK fails to unlock?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/WarEmu/WarBugs/issues/6420#issuecomment-221163796>
>



-- 
Brenndan L. Crumley

**Comment by Evildoor** [comment]
#6320
