### ISSUE TITLE
npc:gorger

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#6421]
in t3 , badland @ around35k,25k this vulture is spawned as lvl 28 and  27 champs.

**Comment by zak68** [comment]
sometimes i wonder how your database schema is structured...

**Comment by Lheana** [comment]
Double spawn problem ?

**Comment by sioding** [comment]
**Thanks for the report.** Since there is no confirmation, i will close this issue now. Please make sure to follow the bugtracker rules which you can find here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)
