### ISSUE TITLE
[UI] Guild and Alliance member names

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#6424]
On Live, I believe that members of the guild and alliance had their names, or possibly the guild under their name a different colour (as the name itself changes colour with RvR flagging).

Guild: Light Blue
Alliance: Dark blue/green

**Comment by Yellowpillow** [comment]
![_198](https://cloud.githubusercontent.com/assets/18102127/18934301/f7348aec-85e9-11e6-9618-33d225e17536.jpg)
