### ISSUE TITLE
[Skill] Pit of Skill

### ISSUE THREAD

**Issue by Abolition** [WarEmu/WarBugs#6427]
After the little server reset / DC about half an hour ago, trying to cast Pit of Skill results in a NullReferenceException error. Ability goes on cooldown and get stuck in cast animation.

Unsure if BWs are having the same issue Rain of Rofl.

![abolition_019](https://cloud.githubusercontent.com/assets/15091486/15505154/55b6fd36-2201-11e6-9cfa-41971d8711fd.jpg)

**Comment by Evildoor** [comment]
#6331
