### ISSUE TITLE
[Quest] Welcome Back: On the Battlefield

### ISSUE THREAD

**Issue by TaeBal** [WarEmu/WarBugs#6428]
Its T1 empire nordland quest for trophy reward 
Empire courier dead body disappeared since last patch 
Was tested about any other ppl can see or find that 
They said "Can't see and find too" 
My marauder have complete this quest before patch 
But my black orc and witch hunter cant see body at quest location 
Thank you for read :)

**Comment by Ryanfawkez** [comment]
Think I already fixed that in the same way I did https://github.com/WarEmu/WarBugs/issues/6429 - respawned the GO so that its database coordinates match that of the actual location.

**Comment by TaeBal** [comment]
Sorry my english so bad i still didnt understand...
So uh... what can i do now? need wait for next server reboot or go some where?

**Comment by Evildoor** [comment]
I suppose that this was fixed with reboot.
