### ISSUE TITLE
[ToK] Jewely unlock bug  "One Tusk"

### ISSUE THREAD

**Issue by TaeBal** [WarEmu/WarBugs#6429]
One Tusk: (13.3k, 2.5k – Exact Coordinates) Travel to Praag and make your way far North to the coordinates given. Approach and enter from the East side of the town. Upon entering, you should locate an NPC by the name of Sasha Michailov (attackable). There is no need to attack, as you just need to simply walk up to this NPC, facing him, and then turn to the left and walk behind one of the first town buildings. You should find an interactive object on the ground called “Third Journal of Lliean” (a book or tome of some sort). Simply click on it and you will be granted the tome unlock, “Empirical Proof”, allowing you to claim One Tusk.

A book disappeared since last patch 
I think many of ground clickable quest object are disappeard since last patch i think

**Comment by Torquemadra** [comment]
try after a server reboot please

**Comment by TaeBal** [comment]
Ok i will :) thank you for answer

**Comment by Ryanfawkez** [comment]
Did notice GOs have a tendency to disappear for no apparent reason. Their location coordinates are usually invalid, yet they teleport you to the actual location they are supposed to be at.

**Comment by Ryanfawkez** [comment]
Respawned the GO on dev server, it now has proper location coordinates and shouldn't despawn.
