### ISSUE TITLE
Targeting

### ISSUE THREAD

**Issue by stonefuzzy** [WarEmu/WarBugs#6430]
when select urself as secondary target its not possible to change to a friendly unit through the bound button, only through leftclicking

happens on WP

**Comment by Evildoor** [comment]
Which button exactly?

**Comment by stonefuzzy** [comment]
doesnt matter to whitch button i bind my "target self" or "target nearest friendly" (currently target self on shift+m4 and friendly on shift+m5). The issue always occurs.

**Comment by Elvenalthur** [comment]
Tested this by ensuring I selected myself, then targeted an enemy player in RvR. Then proceeded to shift+tab (change friendly target). Worked as expected

Targeted an enemy player in RvR. Targeted myself, then proceeded to shift+tab (change friendly target). Worked as expected

Tested in Praag RvR zone.

**Comment by Evildoor** [comment]
Agreed with Elven. Everything works fine for me, so it looks like a problem on your side.

**Comment by gittoaster** [comment]
@elven's comment
he's not talking about shift-tab cycle, he's saying the target nearest commands aren't working properly.
So, since yourself will always be the nearest target, acquiring a target besides yourself should be the proper usage of the command.

**Comment by Evildoor** [comment]
Oh, it's target _nearest_ friendly. Sorry, my bad. However, 95% of targeting is handled on the client side, so we cannot change that.
