### ISSUE TITLE
[Dye Quest] "Devoted" not repeatable

### ISSUE THREAD

**Issue by tutti13** [WarEmu/WarBugs#6432]
The dye-quest "Devoted" by "Caravella Betz" in empire chapter 7 is not repeatable.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by tutti13** [comment]
I already completed this quest once before i opened this ticket. Cannot accept it again now...

**Comment by Evildoor** [comment]
Use support forums.
