### ISSUE TITLE
WL's chest with SW look

### ISSUE THREAD

**Issue by Antalor** [WarEmu/WarBugs#6433]
Hello. I wanted to report bugged appearance for WL's chest. It looks like SW chest.
I don't remember the name of this item, but it's from quest in Empire Ch7 for sure.
Greetings.

**Comment by Ryanfawkez** [comment]
"Skullbacked Mailcoat" - already fixed. I know the current SW chest for WLs comes from T3, but I don't know the item name nor quest it comes from.

**Comment by Antalor** [comment]
When I'll know the name of it, I write it here.

**Comment by Elvenalthur** [comment]
The item is called Mailcoat of the purifier. From the Quest "Missions" claimed from Hogar Putnam at Empire chapter 7 Ostland.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by Antalor** [comment]
I found one more called Desperate Mailcoat
