### ISSUE TITLE
t3 passwatch castle oil and door guards bugged

### ISSUE THREAD

**Issue by Nasharan** [WarEmu/WarBugs#6434]
- the outer door oil can be replaced instantly after the one before was killed, thus giving order a perma oil spam.
- the keep's guards on the ground floor aggro and attack any melee through the closed main gate.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
