### ISSUE TITLE
Trasfered to nowhere after scenario ends

### ISSUE THREAD

**Issue by nohh** [WarEmu/WarBugs#6436]
Trasfered to nowhere after scenario ends
It was Nordenwatch, don't know if it matters but before the scene ended I was pulled by a maradeur.
![nohh_009](https://cloud.githubusercontent.com/assets/19315739/15515797/83ad3970-21f8-11e6-85bc-9e6a312af15c.jpg)
![nohh_008](https://cloud.githubusercontent.com/assets/19315739/15515801/86a7845a-21f8-11e6-9dcb-a8870a4c86aa.jpg)

**Comment by Evildoor** [comment]
Zone 0, nothing to see here. "/stuck" twice.
