### ISSUE TITLE
Relentless Siege Quest kill count not working

### ISSUE THREAD

**Issue by maze1001** [WarEmu/WarBugs#6438]
didnt get any credit for kills in sc/orvr (t3) for the quest "Relentless Siege".

**Comment by Ryanfawkez** [comment]
It's been disabled in scenarios as it is an oRvR quest. It should work in Talabecland, High Pass, Black Fire Pass, The Badlands, Avelorn and Saphery just fine.

**Comment by maze1001** [comment]
not working for me on high pass / talabec

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
