### ISSUE TITLE
[T3 DWARF] Influence not working 

### ISSUE THREAD

**Issue by Orbisfabri** [WarEmu/WarBugs#6439]
![albins_000](https://cloud.githubusercontent.com/assets/19559009/15517705/8cb03634-21f9-11e6-95f9-d6b4c70cc168.jpg)
![albins_001](https://cloud.githubusercontent.com/assets/19559009/15517708/8f372f2a-21f9-11e6-83b1-28e2b0a73259.jpg)

**Comment by Evildoor** [comment]
#6320
