### ISSUE TITLE
respawn and scenarios

### ISSUE THREAD

**Issue by Harnag** [WarEmu/WarBugs#644]
1)  sometimes when you die in a scenario, the "respawn" button does not appear.  This leaves you with no choice but to exit the scenario using /stuck or to exit the game.  Not good for scenario participation

2)  often times you cannot join a scenario when it pops, because you are considered "in combat" perpetually, even when you are not in combat.  I suggest eliminating this restriction entirely so you can join a scenario even if "in combat."  This seems simpler and better than trouble shooting the bug.  Scenario participation will be improved significantly.

**Comment by Evildoor** [comment]
1) You can use /reloadui and the button will reappear.

**Comment by ozarmidrashim** [comment]
I believe issue 2) occurs if you zone out of a scenario while you're "in combat" within that scenario. If anyone can confirm that it would be grand.

**Comment by Thorgatin** [comment]
Confirmed

**Comment by Harnag** [comment]
/reloadui reloads the ui, but the respawn button still does not appear.  Does this work for anyone else?  still seems like a significant bug that needs to be fixed.

**Comment by Evildoor** [comment]
Strange. Usually /reloadui helped me, today it failed for the first time.

**Comment by Harnag** [comment]
Further to issue 1):  It looks like this happens whenever it says "PLAYER has died" instead of "PLAYER has been killed by PLAYER2".  Similarly, it seems like NPCs are not lootable whenever you see "Enraged soul has died" instead of "has been killed by...".   Maybe this will help troubleshoot.
