### ISSUE TITLE
Fighter's Andsplate of Vengeance shows wrong icon

### ISSUE THREAD

**Issue by rakels** [WarEmu/WarBugs#6440]
The item shows the icon of boots instead of gloves:

![unbenannt](https://cloud.githubusercontent.com/assets/9309339/15519182/7ee27f2e-2200-11e6-9b5a-7b6c04f8dc1f.PNG)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by ellionkeman** [comment]
And they are invisible when you put them on
![yozhik_002](https://cloud.githubusercontent.com/assets/18136746/15613086/5fcb8f90-243a-11e6-9136-174f9e5f0a16.jpg)
