### ISSUE TITLE
Lost dye after server reset

### ISSUE THREAD

**Issue by Kourani** [WarEmu/WarBugs#6443]
Hi,

After the reset when people got stuck in Thunder Mountain, i noticed that my ruin chest that i had dyed earlier today with a chaos black dye was now undyed. The dye was not found in my bag neither. tried relogging and still nothing. Not a huge loss, just thought it was worth bringing to light, if its something that can be prevented in the future.

**Comment by wargrimnir** [comment]
This happens when the server goes down unexpectedly. Without doing a rollback, it can't be prevented.

**Comment by Evildoor** [comment]
I agree with grimnir. Not everything is saved in case of server going down unexpectedly, so nothing can be done here.
