### ISSUE TITLE
[Character] Tesq stuck to loagind screen

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#6444]
all other character can be log appart my chosen, when i click play it lost connection and return to handshacking screen.
Furthermore clicking charecter to select a different character to play with dosen't work, i need to close the client and re open it.
Got it after i deliberately crash after a soft disconnection / disconnection.

edit: seems fixed , maybe you reload the server, close it if the description it's of no help

**Comment by wargrimnir** [comment]
You can close your own tickets. FYI

**Comment by Evildoor** [comment]
Point 3 of the rules...
