### ISSUE TITLE
Quest: Head of the Viper

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#6447]
It seems only the Black Orc models named Blacktoof Crusha are contributing to this quest. Screenshot is for the one that needs to be added. Or rather, the one in the screenshot appears to be an objective when you hover over it, but the quest does specify Blacktoof Smasha.

http://i.imgur.com/qEUYnKv.png

Also, the cages in the area can't be clicked through or destroyed, so you have to wait for the neutral mob to clip through them and attack nearby enemies to click on them for their aspect of the quest.

**Comment by Torquemadra** [comment]
read the staff patch notes : P

**Comment by wargrimnir** [comment]
Oh just barely one step ahead of me. I see how it is.
