### ISSUE TITLE
No quests anywhere

### ISSUE THREAD

**Issue by sandreid** [WarEmu/WarBugs#645]
Quests have vanished from the face of the earth. 

On old chars, you can't hand the quests you had in your log and now have completed, in. And you can't see or get new ones. 
On new chars you can't get new quests, either. Even the very first quest is unaccessible for a brand new chars (Both Order and Destro). I've tried on multiple chars, from both factions, both old and new, and it's all the same. It's like all quests have been removed from the game, but they somehow remain in the questlogs.

Everything was working just fine yesterday (4th of March 2015)

Kind regards,

Razid

**Comment by sandreid** [comment]
Is fixed now.

Thanks!

**Comment by sandreid** [comment]
The bug is back after the server went offline earlier today.

**Comment by dragosvv** [comment]
The bug is back
