### ISSUE TITLE
Ebonmane Lion not butcherable

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#6450]
elven got it, i'm a derp

**Comment by Ryanfawkez** [comment]
Seems you included an image that's linked to https://github.com/WarEmu/WarBugs/issues/6447 - might wanna update this ^^

**Comment by Elvenalthur** [comment]
A few a spawned outside the entrance to order WC in Eataine: SpawnId=545161,Entry=1592,Name=Ebonmane Lion,Level=29,Rank=0,Max Health=3010,Faction=1,Emote=0AI:STANDING,Position :(OffX = 257, OffY = 397,Heading = 3574, Oid = 54296, Name= Ebonmane Lion, Active= True)(37272, 22805, 6019)

**Comment by Lheana** [comment]
Works fine now.
