### ISSUE TITLE
Gateclaimers body for sorc; Infl, ch19 DE

### ISSUE THREAD

**Issue by ishkurirriador** [WarEmu/WarBugs#6452]
This armor was always looks like AMs body armor on live. now it looks like usual Sorc dress. I was always roleplay an AM that switched side of conflict when Malekith arrives. as it was on live - alt appearence can't been show by other faction players - so no proplebs in identifying enemy or missidentifying it with other class.

**Comment by Ryanfawkez** [comment]
Yeah, things are a bit different here. The enemy realm CAN see your alt appearance. We've been fixing every item with bugged appearance from live exactly to counter the fact that people can be misled by certain bugged appearances.

**Comment by ishkurirriador** [comment]
Maybe implementing veiw-real-gear of enemy players will help? At least, then, players will always see real gear of enemies? and people, who like to wear something alternate will be happy? :) in my opinion, fixes should be applied only to gear, that looks buggy (like Orcish gear for dwarfes, etc)

**Comment by Ryanfawkez** [comment]
The ability to view your enemy's custom-made looks in its entirety by use of the good looking armors and weapons we already have in the game is not something we're going to revert for the sake of keeping bugged items in the realm. As fun as it is to support xrealming centered looks, we are fixing all of them for a reason. No exceptions.

Also, considering the amount of alternate gear options is massive in this game (once we're able to add icon models to these), there is no need to continue on wearing bugged armors.

**Comment by Evildoor** [comment]
Closing per Ryan's explanations.
