### ISSUE TITLE
SM tactic--"Impeccable Reactions" unwork

### ISSUE THREAD

**Issue by kam19080** [WarEmu/WarBugs#6453]
The next "parry" was not happen, when i got a "parry" 

Thank you,

**Comment by Evildoor** [comment]
Confirm. Aza, maybe this'll help:
![ir](https://cloud.githubusercontent.com/assets/11015074/15551152/51ba8e16-22bd-11e6-88f7-97ccb5f80c9f.jpg)

**Comment by kam19080** [comment]
Thx a lot, Cheer!
