### ISSUE TITLE
Public Quests do not work for me.

### ISSUE THREAD

**Issue by Alexrule44** [WarEmu/WarBugs#6455]
I made my witch hunter 2 days ago and noticed that none of the Public Quests would update (top right objective list) whenever I would do anything for the objective. I still get the influence for killing things but in the end I won't recieve any rewords. 

If I go to a public quests where there has been some progression like it will say 13/40 rift horrors left it will never show me that its progessing; It will just stay at 13/40, even if it completes it still shows that.

Any help would be awesome!

Witch Hunter : Connar

**Comment by genisaurus** [comment]
Fixed in next patch,

**Comment by Alexrule44** [comment]
Thanks!
