### ISSUE TITLE
same loot from lair boss t4 each time

### ISSUE THREAD

**Issue by Blorckever** [WarEmu/WarBugs#6456]
Hi all !!

I found a bug for loot from Lair boss t4 i run whit guildies firends on lair boss today and all boss dropped 2 same loot ( 2 choppa shoulders / 2 mara boots / 2 Magus chest /and again 2 feet BO / 2 shoulders BO and 2 chest BO 2 zealot chest) 

Thanks for your job !

**Comment by NorKalli** [comment]
long ago fixed
