### ISSUE TITLE
DOK Influence Rewards

### ISSUE THREAD

**Issue by Blubberino** [WarEmu/WarBugs#6457]
Some itemstats seem to be mixed up and I think for dok it should be always 1 item for meele and 1 for healer to make things fair. So therefore I post the items with the mixed up stats which need some tweaking.

![valfaros_031](https://cloud.githubusercontent.com/assets/16993024/15556765/e9c2bbf4-22cf-11e6-973d-9c3c4a8437de.jpg)![valfaros_030](https://cloud.githubusercontent.com/assets/16993024/15556769/edbb2f8e-22cf-11e6-9203-66c3a76fac70.jpg)

![valfaros_029](https://cloud.githubusercontent.com/assets/16993024/15556775/f20dad50-22cf-11e6-96a1-847cb5e439e3.jpg)![valfaros_028](https://cloud.githubusercontent.com/assets/16993024/15556778/f476e962-22cf-11e6-8a1e-0b74c2ca9d39.jpg)

![valfaros_027](https://cloud.githubusercontent.com/assets/16993024/15556781/f894684e-22cf-11e6-9164-4eeb4325f327.jpg)![valfaros_026](https://cloud.githubusercontent.com/assets/16993024/15556783/fa1ebc8c-22cf-11e6-90b6-b518cfd80b49.jpg)

![valfaros_025](https://cloud.githubusercontent.com/assets/16993024/15556785/fbf57adc-22cf-11e6-9e14-cad6df8072c9.jpg)![valfaros_024](https://cloud.githubusercontent.com/assets/16993024/15556792/fd77b7bc-22cf-11e6-8179-d2c1443c064b.jpg)

![valfaros_023](https://cloud.githubusercontent.com/assets/16993024/15556796/ffb5fcfa-22cf-11e6-8f40-15cb64255026.jpg)![valfaros_022](https://cloud.githubusercontent.com/assets/16993024/15556798/00c397b0-22d0-11e6-9d3d-300d06dcb0eb.jpg)

![valfaros_021](https://cloud.githubusercontent.com/assets/16993024/15556800/02f6c4da-22d0-11e6-9760-7efc7551f3d7.jpg)![valfaros_020](https://cloud.githubusercontent.com/assets/16993024/15556805/047313fe-22d0-11e6-89d5-6e645ef763b7.jpg)

So I think Items with for meele dok shouldn't have heal crit or willpower so mostly offensive or wounds while on the other hand items for heal dok shouldn't have offensive stats but therefore willpower and defensive stats.

**Comment by Blubberino** [comment]
Recommended Swaps/Changes
1. Weapon skill with toughness
2. Initative with Weaponskill
3. Strength with Willpower and Initiative + resis are different so add/remove additional resis
4. Strength with Wounds
5. Willpower with wounds
6. Healing Crit with Meele power

**Comment by Luth-RoR** [comment]
Original item stats for some classes (mostly healers) were mixed and pretty crappy.
No bug. Feature request -> please use the forum.
