### ISSUE TITLE
Wrong detaunt types

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#646]
Slayer, Choppa and White Lion have wrong effect types (Ailment, Curse and Curse respectively) on their detaunts - type should be Debuff, like all other detaunts in the game, otherwise they can be disrupted or cleansed.
P.S. WL's detaunt also places an effect on WL, its type is also wrong, should be Buff, otherwise Order healers can cleanse it from WL.

**Comment by ozarmidrashim** [comment]
Are you basing this on the visual appearance on the client? That's hardcoded. The server has its own storage for the type of a buff or debuff.

**Comment by Evildoor** [comment]
So, you fixed this? Server side the type is Debuff, and they can't be disrupted/blocked/cleansed?

**Comment by ozarmidrashim** [comment]
Yes.

**Comment by Evildoor** [comment]
Ow, glad to hear that. Nice job! Sorry for bothering you then.
