### ISSUE TITLE
[Quest] t4 dwarf ch19 "Keystone Quandary"

### ISSUE THREAD

**Issue by Gakvar** [WarEmu/WarBugs#6460]
This quest requires the player to locate runestones laying on the ground over a large area. The text directions don't help that much and there are no map indications. I was able to locate three of the stones by thorougly looking around guided by the quest text, but the Rune of Earth is nowhere to be found and I have no idea where else to look for it.

**Comment by Elvenalthur** [comment]
located all the positions of the runes:

rune of air (map locator works)

.t m 27 1436653 931819 8724 (Deaths peak)

SpawnId=253594,Entry=99214,Name=Rune of Air,Level=1,Faction=0,Position :(OffX = 350, OffY = 227,Heading = 3549, Oid = 27907, Name= Rune of Air, Active= True)(3053, 38891, 8724) Dist =1


Rune of fire (no map locator) 

.t m 27 1448326 929053 8688 (Deaths peak)


SpawnId=254482,Entry=99828,Name=Rune of Fire,Level=1,Faction=0,Position :(OffX = 353, OffY = 226,Heading = 2093, Oid = 35590, Name= Rune of Fire, Active= True)(14726, 36125, 8688) Dist =1


Rune of earth (no map locator) 

.t m 5 1423446 929129 9440 (Thunder mountain)

SpawnId=253657,Entry=99223,Name=Rune of Earth,Level=1,Faction=0,Position :(OffX = 347, OffY = 226,Heading = 1206, Oid = 32167, Name= Rune of Earth, Active= True)(55382, 36201, 9440) Dist =2

Rune of water (no map locator)

.t m 5 1432690 937377 9068 (Thunder mountain)

SpawnId=253521,Entry=99203,Name=Rune of Water,Level=1,Faction=0,Position :(OffX = 349, OffY = 228,Heading = 1718, Oid = 26280, Name= Rune of Water, Active= True)(64626, 44449, 9068) Dist=0

**Comment by Gakvar** [comment]
are those coordinates?

**Comment by Elvenalthur** [comment]
They will make sense to who will fix it.

**Comment by Ryanfawkez** [comment]
Problem with Death Peak, Cinderfall and West Praag quests is that they have no map info in the wartool. We cannot accurately place quest markers in these regions until we get a visual map. Could add a marker to Thunder Mountina, however.

**Comment by Gakvar** [comment]
Nice. Maybe a banner or something to be easier to see in the world? Or something discrete.

**Comment by Ryanfawkez** [comment]
We can fix quest markers in these zones now. However, they can only be placed in one location.

**Comment by Razielhell** [comment]
Fixed in next Patch.
