### ISSUE TITLE
BO Tactic Big Brawlin'

### ISSUE THREAD

**Issue by Topologic** [WarEmu/WarBugs#6462]
This tactic is currently applying its snare/disorient as a Debuff instead of an Ailment, and so it can't be cleansed by healers.

Prior to an earlier update, this snare was removable by RP/AM cleanses, and I've been unsuccessful in finding any patch notes which describe this change as intentional.

**Comment by Evildoor** [comment]
Tested, client shows Big Brawlin as debuff (tooltip when applied to enemy), which means that it was debuff on live.

**Comment by ozarmidrashim** [comment]
Confirm per Evildoor. False report.
