### ISSUE TITLE
Siege weapons respawning in keeps

### ISSUE THREAD

**Issue by pikara** [WarEmu/WarBugs#6463]
Keep Bloodfist Rock.
OIL and RAM respawn all time. Even 2 oil at same time. It drop coin if u control it (1s 64c) and drop loot (i get 1 remove dye) and u can scav it.
It also become soo weak.

Oil video
https://youtu.be/Lc97uUMjr94
RAM video
https://youtu.be/0HSaY2e_fQk

Thanks to Pulumna for help on report and spend 5g on a canon for video report and other destro for not attack he.

~~EDIT: Also there was no siegue merchant in that keep.~~ Edited by Evildoor: #6499 will be used for this

**Comment by pikara** [comment]
Looks like all weapons respawn and give XP like it was mobs. I have meet even 3 of that weak oils in same keep.

https://youtu.be/VkRu79QBdXY

**Comment by Lheana** [comment]
This must have been fixed a while ago, so I close it. If not fixed, please comment here.
