### ISSUE TITLE
Pit of Shades "unhandled NullReferenceException"

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#6466]
Charname: TherealVayra
Ability: Pit of Shades

Error message: 9485 Pit of Shades threw an unhandled NullReferenceException from Boolean ObjectWithinRadiusFeet(WorldServer.Object, Int32)

This happens each and every time I cast Pit of Shades. Issue persists through death, relog and restarting client. Other sorc in my group could cast PoS fine (joined shortly after the SS was taken).
Ability goes on cooldown as if it was cast, but cast bar is stuck at 10.0s without progressing. 
![therealvayra_003](https://cloud.githubusercontent.com/assets/1183293/15573350/b2229440-2346-11e6-920e-c3f644dda13b.jpg)

**Comment by Vayra** [comment]
Did some more testing and isolated the issue down to the tactic Close Quarters. 
With the tactic equipped the above error message appears 100% of the time.
Without the tactic equipped ability works fine.

**Comment by Evildoor** [comment]
#6331
