### ISSUE TITLE
Nordland ORvR access from behind the shrine

### ISSUE THREAD

**Issue by Rahvins** [WarEmu/WarBugs#6467]
Hello, I've found a path leading to the Nordland ORvR zone that makes possible to reach the shrine from behind climbing the hills. I suppose this should not be allowed as I remember from live. Screenshot with the path starting location attached.

Thanks

![rahvin_004](https://cloud.githubusercontent.com/assets/19590330/15574074/82cefd1e-234b-11e6-9779-cb490959f454.jpg) 
![rahvin_000](https://cloud.githubusercontent.com/assets/19590330/15573978/1217b89a-234b-11e6-8d8e-737ed52f9489.jpg)
![rahvin_001](https://cloud.githubusercontent.com/assets/19590330/15573979/121ca59e-234b-11e6-8088-803f113a1315.jpg)
![rahvin_002](https://cloud.githubusercontent.com/assets/19590330/15573980/121f46fa-234b-11e6-9f77-478acd514b0b.jpg)
![rahvin_003](https://cloud.githubusercontent.com/assets/19590330/15573981/122169a8-234b-11e6-941a-955eaeb16e44.jpg)

**Comment by Evildoor** [comment]
1) Is this wrong? You can enter RVR zone near point through the hills, and? Defenders will most likely be on the point, not down the road. And if they abandon point for some reason and leave it undefended - shouldn't they be punished for this?
2) It was different on live? How exactly?

**Comment by saupreusse** [comment]
yeah i know this place.... will fix it with the next patch

**Comment by redzus** [comment]
There are couple more entry points and i had long ago posted something about it 
 example

![quickgit_002](https://cloud.githubusercontent.com/assets/19255613/15627941/34f1b1ea-24f4-11e6-92ff-689e8306fa1b.jpg)

**Comment by saupreusse** [comment]
these are annoying since you are not supposed to be up there (trees are flying a bit, you can jump on roofs and inside the house objects. i did my best. if you still find a way to get up there after the next patch - make another bugreport :)
