### ISSUE TITLE
(fighting chance) engineer tactic

### ISSUE THREAD

**Issue by peusnaugrim** [WarEmu/WarBugs#6469]
the  engineer tactic (fighting chance) provide +120 strenght + 120 weapon skill + 120 ballistic skill.
BUT when you equip this tactic they **don't raise your parry chance** as he should do ( +120 weapon skill)

**Comment by ozarmidrashim** [comment]
Visual, and effective dupe of #6196 . I won't fix it for the same reason I gave in that report. Parry chance increases on the server.

**Comment by Evildoor** [comment]
Duplicate, closing.
