### ISSUE TITLE
(Sw)projectile travel times

### ISSUE THREAD

**Issue by truewage** [WarEmu/WarBugs#6471]
travel time of the projectile should depend on the type of skill that Use .
not for all abilities the same time the projectile .

sorry google translator if he could explain the problem in Spanish would do it much better.

I leave a video with different classes pulling abilities :

https://www.youtube.com/watch?v=si2CI-YDEeA

**Comment by Evildoor** [comment]
#6254. Now go and read the rules of the bugtracker about what can be done in your situation. And don't forget about point 9.
