### ISSUE TITLE
ITEM: Greathelm of the mercenary: can only colour the primary layer.

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#6473]
Greathelm of the mercenary: can only be colored on the main layer. No secondary option is available, even when changing the skin.

**Comment by Evildoor** [comment]
Maybe workaround in #3845 will help you.

**Comment by MerryGitmas** [comment]
Nope, it does not work

![col](https://cloud.githubusercontent.com/assets/18053736/15581485/70a08874-2364-11e6-870e-3028730c0fa7.png)

**Comment by Torquemadra** [comment]
Hardcoded that way, nothing can be done, not a restriction.
