### ISSUE TITLE
Unable to buy career abilities

### ISSUE THREAD

**Issue by Heyhoneynut** [WarEmu/WarBugs#6475]
Hello I'm unable to get any abilities from Elsa Schmidt in the Grimmerhagen Village. "New player area"
I'm a dwarf engineer level 5 trying to buy a "Penetrating Round" ability- Rank 3- Path of The Rifleman.

Thank you!

**Comment by Evildoor** [comment]
You don't need to buy abilities in RoR, they are unlocked automatically. Ignore Penetrating Round and other pet abilities - they are available to your pet, just a visual bug causes them to be shown in trainer's window.
