### ISSUE TITLE
Squig Armor breaks abilities

### ISSUE THREAD

**Issue by HunterBlackstone** [WarEmu/WarBugs#6476]
After using Squig Armor, numerous times I have had my abilities break and become unusable. While you can use an ability and it's animation will fire (arrow, etc) there is no damage and the ability does not get a cooldown. Relogging fixes. Rezoning doesn't typically.

**Comment by Evildoor** [comment]
After entering and exiting Armor? Was KABOOM used?

**Comment by d3cimus** [comment]
I have had this happen regularly.  Kaboom seems to be the most common reason that abilities break, but I seem to occasionally be able to reproduce it by using the self-knockback, or from Ironbreaker knockbacks.  I have not noticed it from other sources of knockback.

I experience the exact same thing as HunterBlackstone in that the animation will fire and the global cooldown animation will start, but the ability will not actually fire or do damage.  For cast time abilities, it usually gets about half a second into the cast before failing.

**Comment by roadkillrobin** [comment]
Happens here aswell.....

**Comment by ozarmidrashim** [comment]
Was fixed some time ago
