### ISSUE TITLE
Unable to collect area influence rewards (empire chapter 1)

### ISSUE THREAD

**Issue by Heyhoneynut** [WarEmu/WarBugs#6477]
Empire Chapter 1- War Comes Home To Grimmerhagen "Raven Host Vanguard Public Quest".
I have 3060/3060 influence to collect the basic, advance and elite rewards but cant click on them to receive them.
Thank you!

**Comment by Evildoor** [comment]
Do you have page unlocked in the ToK?

**Comment by Heyhoneynut** [comment]
I'm not sure how could I check if it is?

**Comment by Evildoor** [comment]
Open your tome of knowledge and check if you have chapter 1 unlocked in Empire storyline.

**Comment by Heyhoneynut** [comment]
Yea chapter one has a cross marked next to it to say I completed it but above it where it says Prologue it has ??? and doesn't have a cross marked

**Comment by Evildoor** [comment]
Screenshot, please.

**Comment by Heyhoneynut** [comment]
<img width="721" alt="war1" src="https://cloud.githubusercontent.com/assets/19594204/15581734/87db2390-2365-11e6-9285-a4013b6fcf0d.PNG">

**Comment by Heyhoneynut** [comment]
<img width="683" alt="war2" src="https://cloud.githubusercontent.com/assets/19594204/15581763/b1450d90-2365-11e6-9949-ef80072c524e.PNG">

**Comment by Evildoor** [comment]
Ok, so it's not #6320...

**Comment by Heyhoneynut** [comment]
Not sure hopefully high level ones work but I also cannot purchase this
<img width="585" alt="war3" src="https://cloud.githubusercontent.com/assets/19594204/15581865/1d896ae6-2366-11e6-8129-3fb130fac1f5.PNG">

**Comment by Heyhoneynut** [comment]
cancel that last post it automatically gives it to me

**Comment by Heyhoneynut** [comment]
okay so should I just leave it and hope it doesn't happen at higher level ones?

**Comment by Evildoor** [comment]
Yes.

**Comment by Heyhoneynut** [comment]
awesome thanks!

**Comment by Heyhoneynut** [comment]
Found a solution, speak to the rally master and he gives you the rewards

**Comment by Evildoor** [comment]
Uh... Excuse me, but how were you trying to get them before?

**Comment by Heyhoneynut** [comment]
via the book, you used to be able to click on the items in the book and receive the items. before the game got shut down

**Comment by Evildoor** [comment]
It never worked like that, so this is not a bug.
