### ISSUE TITLE
Snares not renewing

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#648]
Currently dots and debuffs have their duration renewed if you apply them again before they end, but snares are bugged and timer is not renewed. This means that you can't snare someone 1-2 second before they are free, you have to wait until snare wears off, which is sometimes enough for them to escape.
P.S. This is for single snaring person, i have not tested how this works for two players of same class.
P.P.S. I have not tested this for each and every snare currently in game, but i'm pretty sure that it's true for BO, Chosen, IB, Engi and Magus.

**Comment by ozarmidrashim** [comment]
Known and on the agenda to fix, though I'm not sure if fixing it will actually improve the gameplay.
