### ISSUE TITLE
Chosen Greenskin Weapon Rewards

### ISSUE THREAD

**Issue by th3gatekeeper** [WarEmu/WarBugs#6480]
The main weapon in question here is:
![greenskin 2h_zps4f913zny](https://cloud.githubusercontent.com/assets/19579983/15585040/4593b3f4-2332-11e6-94b9-332b3558efc2.jpg)

A majority of Chosen damage is spirit damage and therefore weaponskill is not something most chosen will stack - especially on a 2H. With things like Ravage/rending Blade both being main sources of damage and both spirit, as well as touch of palsy or tooth of tzeentch also dealing DoT spirit damage... Weapon skill falls FAR behind other stats.

For instance, compare that influence weapon with the SC weapon OR even the 1H from the same area:
(1H)
![greenskin 1h_zpsep348e2a](https://cloud.githubusercontent.com/assets/19579983/15585146/c6b65ec8-2332-11e6-9580-5feb62653b8c.jpg)

The 1H offers some GREAT stats... Parry, crit and toughness - all things a 2H chosen needs. Arguably STR>Toughness but both those are superb.

(SC)
![pvp 2h sword_zps5c1absu3](https://cloud.githubusercontent.com/assets/19579983/15585150/cf92e0c0-2332-11e6-8d0a-c9bdec2aa72e.jpg)

This is really a dream weapon with all the key stats, Strength, Wounds, AP/Sec AND 4% crit is amazing. CRUSHES the influence weapon hands down.

What I suggest is using a stat allocation more like the Greenskin 1H - but a 2H version on the 2H weapon. This would actually make the 2H appealing. If it kept toughness/parry/crit but at 2H allocation amounts it would be a great option but offer a much different approach compared to the SC weapon. I dont know how the allocation works... but something LIKE:

+51 Toughness, +37 Strength, +2% parry, +4% Crit

Makes it about "par" with the SC weapon offering different stats and a true pros vs cons. Right now I cant see any Chosen actually using EITHER influence 2H as it offers nothing that is that great....

**Comment by Luth-RoR** [comment]
This is more like a feature request, no bug. 
There are also a lot of non-spirit damage abilities for the chosen as well as autoattacks (which are a major part of the DPS of every melee class).
