### ISSUE TITLE
Can't Open Purple Bag (From T4 Keep)

### ISSUE THREAD

**Issue by blakokami** [WarEmu/WarBugs#6482]
Title. Many people can't open purple bags from keeps at the moment it seems. This issue was not resolved once a server restart happened.

**Comment by Evildoor** [comment]
Fresh bags just from keep? Which were not occasionally sold to vendor and which have not lasted through the server restart?

**Comment by blakokami** [comment]
In my case I accidentally did sell it to a vendor and bought it back. In other cases, this happens when the bag wasn't opened before a server restart.

**Comment by Evildoor** [comment]
#5392
#5768
