### ISSUE TITLE
Level 175 ballistic seed giving level1 molotov seed 

### ISSUE THREAD

**Issue by Enarion** [WarEmu/WarBugs#6483]
![lauria_000](https://cloud.githubusercontent.com/assets/19255238/15591345/d46f947a-239c-11e6-9f17-b600c839513d.jpg)
Hello ,
Two time already on special moment my level 175 seed for ballistic ( game down so i haven't the name ) give me level one seed for molotov potion instead of level 200 ballistic seed.
Best regards

**Comment by Enarion** [comment]
level 175 are scrubby thief's nettle seed giving smoking pyre ivy ( level 1 for molotov potion )

**Comment by Evildoor** [comment]
#5402
