### ISSUE TITLE
NPC: Eternal watcher construct cannot be killed.

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#6485]
The NPC Eternal Watcher in the Ebon keep cannot be killed but keeps attacking even at 0% health.
![screen shot 2016-05-26 at 23 05 09](https://cloud.githubusercontent.com/assets/18053736/15591713/922fef0c-2396-11e6-8230-eff6a21665bb.png)

**Comment by Ryanfawkez** [comment]
I think this issue applies to all NPCs that have a model that is primarily used as structures.

**Comment by Ryanfawkez** [comment]
Hmm, seems to be dependent on subtype more than anything.
