### ISSUE TITLE
NPC: wrong location: Viktor Riese

### ISSUE THREAD

**Issue by MerryGitmas** [WarEmu/WarBugs#6487]
This NPC is supposed to be only in Grimmenhagen, Empire starting area, but can be found also in the Ebon Keep of Chaos Wastes, offering the same quests for lvl 1 

![screen shot 2016-05-26 at 23 12 05](https://cloud.githubusercontent.com/assets/18053736/15591827/4b9da876-2397-11e6-80ef-44d1fced119b.png)

**Comment by Ryanfawkez** [comment]
Not true. This NPC and others like it are supposed to be here, as they're a part of the Ebon Keep PQ. Only problem is, they have the same functionality as the NPCs in their respective chapters, while they shouldn't. Only way to fix this is to create unique copies without functionality.

**Comment by Ryanfawkez** [comment]
Fixed all of these NPCs for the next patch. They are now unique entries for the PQ.
