### ISSUE TITLE
Mara Terrible Embrace 2nd Range Check

### ISSUE THREAD

**Issue by Shadowgurke** [WarEmu/WarBugs#6488]
Today Marauder Pull was changed to have a second Range check to determine if the target is still in range. If the target moves an inch out of range, the cast fails. Below I linked several videos from live that show a Marauder pulling his target despite it being out of range (watch action bar symbol)

https://youtu.be/NWkTWzRfNZg?t=175

https://youtu.be/O9fVROGGR58?t=728

https://youtu.be/fObp2EB0hNI?t=459

**Comment by Vayra** [comment]
On live the 2nd range checks had a good bit of leeway, somewhere between 20-50% of the skill range (possibly affected by cast time). Basically if target is in range when you start the cast it would be almost impossible for it to get out of range by the end of the cast unless it got punted real hard, was already on the fast mounts or was out of combat and teleported somewhere (Book, sc, guild scroll, etc).

**Comment by Evildoor** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=78&t=14212
Balance issue, not a bug.
