### ISSUE TITLE
Quest NPC mislocated

### ISSUE THREAD

**Issue by pixie126** [WarEmu/WarBugs#6489]
The NPC for the quest The Pride of Caledor, Drakeseer,
 is stuck in the terrain and cannot be interacted with.

![xramoth_007](https://cloud.githubusercontent.com/assets/15041016/15593137/350ec630-236f-11e6-8979-5438708313dc.jpg)

**Comment by Torquemadra** [comment]
actually the npc was set at scale 1 so was too small to click, fixed next patch
