### ISSUE TITLE
Norsca Destro Tower Guard npc

### ISSUE THREAD

**Issue by Ghazkhull** [WarEmu/WarBugs#649]
I was in the tower where Captain Von Wilke (in Norsca) is and there are Tower Guard NPCs on the stairs leading up to the left and to the right of the room. The Tower Guard on the left staircase was laying down as though he was dead, with same grey/white target ring when you select him as a dead guy. He is very much alive and attacks you. When you try tp attack back, you get an error message on screen that your target is dead. If you run, he chases, still attacking, but invisible. Then, *POOF* his dead model shows up at your feet again.

**Comment by Reggaewaldo** [comment]
Could not reproduce the error reported but I'm aware that this was an error before.

This can be closed.
