### ISSUE TITLE
Apothecary/Alchemical Compound bug window

### ISSUE THREAD

**Issue by ChronoVarience** [WarEmu/WarBugs#6490]
This Apothecary window bug occurs randomly anyway, but it will always occur when attempting to use the Alchemical compound.

Video:  http://plays.tv/video/5747e16b8b46714642/alchemical-compound-apothecary-window-bug-26-may-2016

**Comment by Evildoor** [comment]
Are you sure this is compound-related? Looks more like #1457 to me (vove-RoR's comment), since you cannot even insert Grumpleaf into window, which happened before using the compound.

**Comment by ChronoVarience** [comment]
The Grumpleaf thing is different I think; the stack of Beardweed I had been working ran out. When that happens the secondary ingredients stay in their slots but you cant replace the main; however, that little irritation is easily overcome by clearing out the bottle which empties all the ingredients and then re-slotting anther bottle.(a bug for another ticket, perhaps?) The compound, on the other hand, won't slot period and completely bugs out the UI. You can't slot a different ingredient. You can't un-slot the bottle. You can't slot secondary ingredients. If you shut down the UI and bring it back up, you can't slot a new bottle. To continue making potions you have to relog.

Video: http://plays.tv/video/57490b3aa5162cf28e/apothecary-compound

**Comment by LordMort** [comment]
Hi there!

I have the same problem with all of the compounds (alchemical, aggregate, elemental, as well as terrestrial) I tried.

Upon trying to put the compound into the main ingredient slot the apothecary skill becomes unusable until I log out and log back in again.

**Comment by Luth-RoR** [comment]
High likely addon related (ezcraftx afaik).
