### ISSUE TITLE
Thrown to character menu after loading screen

### ISSUE THREAD

**Issue by rakels** [WarEmu/WarBugs#6491]
Most often i get directly kicked to character menu after an loading screen, for example when i want to join a scenario or when i use the flight master. It started to happen more frequently since i got to t2, but this could also be a coincidence. If it happens i need to close the game client completely and log back in. If you need any additional information just let me know

**Comment by Elvenalthur** [comment]
These kind of issues are best asked on the forum. It's more tech support than game bugs.

That said, are you in a guild that has more than 500 members? Try leaving the guild and see if that fixes it.

**Comment by rakels** [comment]
Thanks for the feedback and you're right i'm currently in a guild with 500+ members. I will leave that one
