### ISSUE TITLE
[Sorc] Pit of Shades

### ISSUE THREAD

**Issue by stillwaterww** [WarEmu/WarBugs#6492]
Since logging in today pit of shades no longer functions for me.
Its also giving a null reference error.
Here are some screenshots:
![iobel_011](https://cloud.githubusercontent.com/assets/19287032/15607850/241e04a6-2416-11e6-9fad-bf4c8b426bea.jpg)
![iobel_012](https://cloud.githubusercontent.com/assets/19287032/15607854/269a36b4-2416-11e6-9eac-08d6f82dcefa.jpg)

**Comment by Evildoor** [comment]
#6331
