### ISSUE TITLE
Big Brawlin'

### ISSUE THREAD

**Issue by Uchoo** [WarEmu/WarBugs#6493]
The Slayer ability "Break Loose" does not provide immunity to this tactic. I am unsure if it dispels it upon activation or if other such abilities (Juggernaut, other MDPS root breaks) interact with it in a similar fashion.

**Comment by Ryanfawkez** [comment]
All MPDS have a specific snare/root break that also makes them immune to all CC for 10 seconds, including snares. Juggernaut is for tanks only, and only breaks snares/roots, not granting immunity for them.

**Comment by Uchoo** [comment]
That is true. So when I use "Break Loose", I shouldn't be getting snared again by the black orc tactic, correct? I'll try to get someone to confirm this for me.

**Comment by Ryanfawkez** [comment]
Could be the issue. Tactics tend to act different from direct abilities at times.

**Comment by grunbag** [comment]
it's already fixed, closing
