### ISSUE TITLE
[Object] Ram+Oil don't reset in TM

### ISSUE THREAD

**Issue by Scrilian** [WarEmu/WarBugs#6494]
Maybe it was a recent change, but they don't reset or ress for like 20+ minutes
![otis_088](https://cloud.githubusercontent.com/assets/16498708/15613000/eb997a10-2439-11e6-8aa9-4a698155e384.jpg)

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
