### ISSUE TITLE
[Zealot] Veil of chaos

### ISSUE THREAD

**Issue by Blubberino** [WarEmu/WarBugs#6495]
The healing is too low and should be higher
![laranaxas_044](https://cloud.githubusercontent.com/assets/16993024/15615659/e5a37cc2-243f-11e6-8e0c-4d088de55aa2.jpg)

Tested without any healing reducing tactics and out of combat

Healing done 281, Healing in tooltip 395

Sry pic. isn't that good.

**Comment by Zealote** [comment]
No issue on my lvl 26 zeal, with no tactics equipped:

![voc 1](https://cloud.githubusercontent.com/assets/10598420/17458886/091e60aa-5c1b-11e6-93b5-4011422108ee.png)

Strangely though, when I returned to IC after an SC, the tooltip value had changed but the heal value was (pretty much) the same as it should be:

![voc 2](https://cloud.githubusercontent.com/assets/10598420/17458894/ac3ddcb6-5c1b-11e6-8b11-e28adae44dee.png)

One other odd thing (still to do with VoC's heal value) is that when I cast VoC on some low lvl players (levels 8, 10, 11), the heal value was not only different from the tooltip (154), but it decreased as the other player's level increased. The heal values were 113, 121, 125. The 125 heal value was the same on another level 11 player. Could this be in any way related to the original report, or, if not, maybe there's some other known reason for it?

**Comment by ozarmidrashim** [comment]
Caused by pulldown of maximum level of buff when applied to lower level character
