### ISSUE TITLE
Close quaters tactic on magus

### ISSUE THREAD

**Issue by Flickofthewirst** [WarEmu/WarBugs#6496]
While having the tactic on, 2 of the abilities doesn't show up on a screen and doesn't do anything at all "Daemonic Infestation" doesn't show up, or do damage or stagger anyone, and "Tzeentch's Firestorm" doesn't do any damage and also doesn't show up on the screen.
Without the tactic, both abilities works as it should.

**Comment by Nantroxss** [comment]
Same for engineer's Expert Skirmisher tactic and the Land Mine

**Comment by Evildoor** [comment]
#6331
