### ISSUE TITLE
Wrong influence rewards 

### ISSUE THREAD

**Issue by szejoza** [WarEmu/WarBugs#6497]
Ch1 and Ch2 in Chaos. Got zealot items to chose for marauder
![sheyrd_000](https://cloud.githubusercontent.com/assets/18032193/15623058/e769a8b2-246f-11e6-8109-d413c565aecd.jpg)
![sheyrd_001](https://cloud.githubusercontent.com/assets/18032193/15623057/e7666102-246f-11e6-9421-b4c494a12aba.jpg)

**Comment by Torquemadra** [comment]
added class requirement
