### ISSUE TITLE
Thunder Mountain ~ Bloodfist Rock Keep (T4) Missing Siege Vendor (!)

### ISSUE THREAD

**Issue by Sovox** [WarEmu/WarBugs#6499]
This keep is missing a **Siege Weapon Vendor** (!)
![lestrange_004](https://cloud.githubusercontent.com/assets/19616566/15623251/83b6a282-2426-11e6-9924-59183353b921.jpg)
^--Middle section inside the outer wall's Gatehouse {Where I've seen all the other vendors}--^

![lestrange_005](https://cloud.githubusercontent.com/assets/19616566/15623256/88ad9f70-2426-11e6-927b-ac6dee346076.jpg)
![lestrange_006](https://cloud.githubusercontent.com/assets/19616566/15623262/8b629d9c-2426-11e6-95fa-226f4b741001.jpg)
^--These two are just showing that the NPC isn't misplaced inside the Keep itself--^

---

![lestrange_009](https://cloud.githubusercontent.com/assets/19616566/15624362/fe4abc36-243a-11e6-9a33-9c1c3c89a47d.jpg)
^--Left Section of the outer wall's Gatehouse {Leading up to Oil}--^

![lestrange_011](https://cloud.githubusercontent.com/assets/19616566/15624367/1b63501c-243b-11e6-8783-bc2871d3c370.jpg)
^--Clearer Screenshot of the Middle Section of the outer wall's Gate House--^

![lestrange_012](https://cloud.githubusercontent.com/assets/19616566/15624376/3e49095a-243b-11e6-9aee-f7753518274f.jpg)
^--Right Section of the outer wall's Gatehouse {Leading Up to Oil}--^

![lestrange_014](https://cloud.githubusercontent.com/assets/19616566/15624384/62684620-243b-11e6-931d-714a22fd7a88.jpg)
^--Top of the outer wall's Gatehouse--^

![lestrange_015](https://cloud.githubusercontent.com/assets/19616566/15624396/d44d4df8-243b-11e6-91d2-d91db28280ff.jpg)
^--View from inside the Keep looking at the outer wall--^

---

![lestrange_016](https://cloud.githubusercontent.com/assets/19616566/15624469/4edaffce-243d-11e6-9d75-cf250ac7702d.jpg)
![lestrange_019](https://cloud.githubusercontent.com/assets/19616566/15624470/5177abba-243d-11e6-86f7-149c8b2a3624.jpg)
^--Outer wall from the right--^

---

![lestrange_017](https://cloud.githubusercontent.com/assets/19616566/15624476/6c2695fc-243d-11e6-887b-51d7b3e59a5b.jpg)
![lestrange_018](https://cloud.githubusercontent.com/assets/19616566/15624477/6f4c72d8-243d-11e6-9a6e-676d57d7e1c1.jpg)
^--Outer wall from the left--^

Still, I see no **NPC** (?) =/

---

_(Note: I have also mentioned this to the **GM: Selth (?)** in-game, before the servers went offline yesterday about this issue.)_

---

**--->UPDATE 06/06/2016 | 06/11/2016<---**
_Still missing a Siege Vendor._

**Comment by Elvenalthur** [comment]
Siege weapons are bought from the keep foreman at outer now.

**Comment by Sovox** [comment]
First Screenshot is inside the Outerwall/Gatehouse, the NPC is missing. Also no where to be found, I searched the entire Keep "property". =|

**Comment by Evildoor** [comment]
This was mentioned in comment to #6463 but we'll use this ticket.

**Comment by Sovox** [comment]
@Evildoor glad to see this got some prior notice. I am concerned more on the side of the missing NPC though, versus the Oil/Ram respawn time that is mainly covered in #6463. But, if we could keep the focus on the **missing NPC** for this thread, I would greatly appreciate it~ 
=)

**Comment by Sovox** [comment]
Order gets to have their vendor, why can't destro have one? Makes keep def in TM really annoying.

**Comment by Ryanfawkez** [comment]
Orc Foreman is included in the Thunder Mountain keep NPCs listing.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
