### ISSUE TITLE
The Son`s Sacrifice

### ISSUE THREAD

**Issue by Zbiten** [WarEmu/WarBugs#650]
Quest isnt worked. Requirements complete, but target NPC dont complete the quest 
![kjarvald_000](https://cloud.githubusercontent.com/assets/6445006/6543528/4eedb606-c538-11e4-9d59-ef57f173a58d.jpg)

**Comment by DanaBloodkiss** [comment]
This isn't Jakob's Son. Look in the red area on map. Jabokb's son is near Jakob.

**Comment by Zbiten** [comment]
Read better and see on screen on red circle...right circle. Ill already speak with Jacob`s Son)
