### ISSUE TITLE
Quest: Curing Dissent

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#6501]
This is gonna be difficult if we've lost the last wardb-ish site
http://i.imgur.com/JjWynAs.png

Missing stats
http://i.imgur.com/04OYSHB.png
Enforcer's Mane
+28 STR
+28 WS

id 504270

Special Issue Mane currently has +28 TGH, should have a second +28 stat, can't find the original
id 504258

**Comment by saupreusse** [comment]
i rebuilt these two item sets (enforcer and Special Issue)  with a 28/18 base. (as provided in the screenshot). live in the next patch

**Comment by wargrimnir** [comment]
Damn, that's what Dana was talking about. Not sure why I put +28 there. Apologies, must have done one too many of these in the past week or so.

**Comment by saupreusse** [comment]
:)
