### ISSUE TITLE
Retribution

### ISSUE THREAD

**Issue by Uchoo** [WarEmu/WarBugs#6502]
This Slayer skill is not reflecting damage past the 5ft range as far as I can tell, though it may be something different. All I know is that I cannot use it on someone hitting me from a range, which is different than live.

**Comment by Evildoor** [comment]
> All I know is that I cannot use it on someone hitting me from a range, which is different than live.

Wrong, it was changed. Yes, i remember 3-4 slayers jumping into Pit of Shades and kiling a sorc. But then it was patched.
http://warhammeronline.wikia.com/wiki/Game_Update_1.3.5/Hot_Fixes

**Comment by Uchoo** [comment]
I stand corrected.
