### ISSUE TITLE
Auction House Posting and Purchasing

### ISSUE THREAD

**Issue by TagTimeGaming** [WarEmu/WarBugs#6503]
The Auction House is not working properly.  

While attempting to purchase and sell Chaos Black dye, I purchased two dyes for 6g and 7g.  As I purchased these, more auctions showed up for 7g and 7g, 98s.  I assumed someone else was selling at the same time.  However, when I went to sell my dyes, they do not show when I search for Chaos Black Dye.  They show on my Sell tab, though.  I am worried this issue is making my dyes unseeable by possible purchasers.

**Comment by Evildoor** [comment]
#1821
