### ISSUE TITLE
NPC Squabrik the Honcho is spawn three times in 54k, 8k

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#6507]

**Comment by avenflar** [comment]
Just adding that it's supposed to give : 

Gnoblar (Honcho Bogwash) - Tiny Tyrant
GREENSKIN TOME TACTIC
(O) & (D)
MARSHES OF MADNESS @ 35, 60. Kill the L20 mob. Doing this unlock plus "Cull the Weak" will completely unlock the first Greenskin Tactic called "Fungal Fetish".
By Unpeftable, Kellithe & Wilken
20081022

... and it doesn't.

**Comment by DanaBloodkiss** [comment]
Fixed in next patch.
