### ISSUE TITLE
 Not correct work skills in the black orc , it is important !

### ISSUE THREAD

**Issue by Greedndefender** [WarEmu/WarBugs#6509]
1) When using the rack " Balshuschy " lists for additional articles get not only uses this stance , but also the enemy of which articles should go.
2)
When using the rack " greening " of the Resistance as well , are using this rack and enemy armor buff appears , but in fact your not given .

**Comment by Evildoor** [comment]
Description not clear.

**Comment by Greedndefender** [comment]
Black Ork
1) In duel, bonus stats of War Bellow "Da Biggest!" do not decrease opponents stat's, but increas stats instead.(hope it works fine for opposit realm)
2)The same thing for War Bellow "Da Greenest"(was hard to check war bellow "Da Toughest!"maybe it's wrong aswell)

**Comment by ozarmidrashim** [comment]
Duel-only issue.

**Comment by Evildoor** [comment]
#2528 will be used for this.
