### ISSUE TITLE
The Son`s Sacrifice

### ISSUE THREAD

**Issue by Zbiten** [WarEmu/WarBugs#651]
Quest isnt worked. Requirements complete, but target NPC dont complete the quest. Please, read better, or take glasses, and see on my screens. Ill abandoned that quest and do it at 8 times) Not affect)
![kjarvald_001](https://cloud.githubusercontent.com/assets/6445006/6543607/b26da44a-c53b-11e4-8af3-6f48306338f0.jpg)
![kjarvald_002](https://cloud.githubusercontent.com/assets/6445006/6543608/c6ad32ae-c53b-11e4-92ed-8185de1be9af.jpg)
![kjarvald_000](https://cloud.githubusercontent.com/assets/6445006/6543609/c9ce3d34-c53b-11e4-9333-ab42e8bfdd82.jpg)

**Comment by Elvenalthur** [comment]
It does work. Once you talk to Jakob's son, talk to his father. Then the next quest is to return to Scrivener.

**Comment by Evildoor** [comment]
Wording now says that you should return to Scrivener. Closing.
