### ISSUE TITLE
Gnoblar - Cull of the Weak

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#6511]
The ears don't stack and don't give the tactic

GREENSKIN TOME TACTIC
(D) & (O)
MARSHES OF MADNESS @ 56, 7. Fight Boglars and loot their Boglar Ears. Collect 5, once you have 5 then it auto-completes and you receive the unlock.
By OneWingedAngelo1, Dormammu, Risingashes, Ibeefus, Rhumble, Icebird & Yvarma
20081209

**Comment by DanaBloodkiss** [comment]
They will stack up to 5 now. 
The tactics aren't working yet. This feature will come later.

**Comment by Lheana** [comment]
Now we can collect it, and ears are stacking but nothing happens when having the 5 required.

**Comment by Lheana** [comment]
Workaround possible ?

**Comment by Ryanfawkez** [comment]
Collection of Ears item now obtainable at the additional library vendor.
