### ISSUE TITLE
 Not correct work skills in the black orc.

### ISSUE THREAD

**Issue by Greedndefender** [WarEmu/WarBugs#6512]
Black Ork
1) In duel, bonus stats of War Bellow "Da Biggest!" do not decrease opponents stat's, but increas stats instead.(hope it works fine for opposit realm)
2)The same thing for War Bellow "Da Greenest"(was hard to check war bellow "Da Toughest!"maybe it's wrong aswell)

**Comment by Evildoor** [comment]
#6509
