### ISSUE TITLE
Piercing Bite not working

### ISSUE THREAD

**Issue by Freki123** [WarEmu/WarBugs#6513]
Wether i equip the tactic or not i see no damage difference. I used the brutality claw with only the pve shield proc for better testing and the ap on crit tactic. I only used the Level 40 Iron Breaker Npc in Reikwald and attacked them with "Convulsive Slashing" i saw no difference in damage or mitigation.
Shoudnt i get a higher dmag number with less mitigation? (I dont count the crits)

![pic1](https://cloud.githubusercontent.com/assets/19626877/15629415/c13eefcc-2518-11e6-8eab-aeca744c1342.jpg)
![pic2](https://cloud.githubusercontent.com/assets/19626877/15629416/c154bdde-2518-11e6-86d1-4c2951b3c81b.jpg)

**Comment by taccr** [comment]
Just did a few tests and I can confirm that at least the following abilities do not profit from PB:
- Covulsive Slashing (Brut)
- Mouth of Tzeentch (Sav/Monstro)
- Rend (Sav/Brut)

**Comment by Evildoor** [comment]
I think this should be tested on players, not mobs.

**Comment by Freki123** [comment]
Thanks to the the friendly help from Gavlistos here the screens:
Same dmg and mitigation with and without tactic.

![with_piercing](https://cloud.githubusercontent.com/assets/19626877/15632430/3618f5f4-2591-11e6-9e7c-ced803d93901.jpg)
![without_piercing](https://cloud.githubusercontent.com/assets/19626877/15632431/3619a21a-2591-11e6-9fa1-0eea731f4c82.jpg)

**Comment by ozarmidrashim** [comment]
MoT works. Rest did not.

**Comment by taccr** [comment]
Wrecking Ball (Monstro) does not profit from PB.

Everything else looks good now.
