### ISSUE TITLE
Issue siege weapons

### ISSUE THREAD

**Issue by Blorckever** [WarEmu/WarBugs#6514]
Hi all !!

There an annoying issue for siege weapon when we put 2 siege for outher door impossible to put others siege when we want to kill oil and door on inner area said "maximum siege weapons ...."

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
