### ISSUE TITLE
Quest: A Line in the Sand

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#6515]
Items missing stats

Quickener's Mane
http://i.imgur.com/WraYh30.png
http://i.imgur.com/BFst4AM.png
Missing +13 WS
id 74175

Invoker's Mane
http://i.imgur.com/ys5Mlfu.png
missing +13 INI
from war.mmodb.com cache
 Invoker's Mane
28		Medium Armor	High Elf	White Lion	Armor:270 Wounds:+15 Tough:+15 Init:+13
id 517410

**Comment by Torquemadra** [comment]
looks right in db, guess someone got there already
