### ISSUE TITLE
Questionable Fashion

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#6516]
Kill Gorgers around Iceflow Maw at 7k,7k in Troll Country for a Gorger Bone Decoration. Once collected, right click the item in the backpack to trigger the unlock. 

Clicking the item doesn't do anything

**Comment by poutpoutt** [comment]
Clicking on the item makes it disappear but doesn't give the unlock.

**Comment by Lheana** [comment]
This issue is still not fixable ? There are several unlocks which consist clicking on a dropped item, that are working now.

**Comment by Luth-RoR** [comment]
I guess it can be fixed now.

**Comment by Lheana** [comment]
Equiping the 'Gorger Bone Decoration' triggers the title, but not the unlock 'Questionable Fashion'. Must kill 'Bonegash Gorgers' to have the unlock.

**Comment by Ryanfawkez** [comment]
Only way to enable the unlock for now is by killing Bonegash Gorgers. Cannot add both tome unlock and title unlock on an item.
