### ISSUE TITLE
Afvaldr, NPC lvl 2 Destro lost in Troll Country in 61k 29k

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#6518]

**Comment by Evildoor** [comment]
Description not clear.

**Comment by avenflar** [comment]
There is a lvl 2 pnj spawned randomly against a mountain flank in troll country. i'm not sure he's supposed to be there

**Comment by Evildoor** [comment]
If you are not sure - don't report. I see nothing wrong with lvl 2 npc in T2 - maybe he's a part of quest or unlock or something.

**Comment by Evildoor** [comment]
Nobody provided information that this NPC shouldn't be here, so i'm closing this.
