### ISSUE TITLE
O'de Toilet

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#6519]
Troll, River (Brackmaw) - O'de Toilet
GIANT TOME TACTIC
(D) & (O)
TROLL COUNTRY @ 56, 47. First, near the Troll hunting goblin camp pick up a Barrel of Perfume. Then kill the mob @ 56, 44k.

Impossible to pick the barrel, and killing the mob doesn't do anything

**Comment by Ryanfawkez** [comment]
Killing the mob grants the unlock in the next patch.
