### ISSUE TITLE
Molotov seeds not working

### ISSUE THREAD

**Issue by mantiyeah** [WarEmu/WarBugs#6522]
I tried the molotov and napalm seeds from levels 1-125 and they don't create any potions

Probably they don't work neither for higher levels.

Maybe it is better to take them out of the game while the potions are not created for not making people waste money in the ah or time cultivating them.

Thanks for keeping the game alive, see you

**Comment by Evildoor** [comment]
#1526

**Comment by relg** [comment]
Same here, I just cultivated the seeds for days now until 150 level. (Crimson-Tipped Pyre Ivy) and brewed 20 portions. No potions came out of it.  So problem continues still. Just to inform you about it.  I don't know if that gave any skill-ups (none showed) but no molotow-cocktail did appear in my inventory.
