### ISSUE TITLE
Quest: Dark Tidings

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#6524]
Broken items

Harbinger Steelhelm
http://i.imgur.com/8yDPWLs.png
http://i.imgur.com/W32KAfT.png
Missing +11 WS
id 517722

Spirit Steelhelm
http://i.imgur.com/Y1hl5Zn.png
http://i.imgur.com/yofkIZl.png
Missing +15 WS
id 517734

**Comment by Torquemadra** [comment]
fixed
