### ISSUE TITLE
problem with dots disrupt and multiple-disrupt disrupt

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#6525]
I noticed one issue with some dot abilities right now such as Rune of Immolation and Ignite which if you apply to two different targets, if one disrupts then both dots are disrupted.

**Comment by Evildoor** [comment]
Proof.

**Comment by gittoaster** [comment]
this one i definitely have the ability to test, but if it happens again I'll surely save the info.  Should be easy to test in the defensive target stacks disrupt.
I think that another possibility might be that something is just wrong with the way the disrupt check is handling and possibly is effecting all similar DoT's.
thx
