### ISSUE TITLE
Dots that have disrupt check on each tick

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#6526]
I have noticed that more at least two slow dots have disrupt check on each tick, which are Rune of Immolation and Ignite (probably more).
Sorry if there is already a thread for this, I've searched for a bit already..

**Comment by Evildoor** [comment]
Proof.

**Comment by ozarmidrashim** [comment]
public static void InflictPrecalculatedDamage(AbilityDamageInfo damageInfo, Unit caster, Unit target, float multiplier, bool bFinalize)
        {
            damageInfo.Damage = damageInfo.PrecalcDamage * multiplier;
            damageInfo.Mitigation = damageInfo.PrecalcMitigation * multiplier;
            damageInfo.Absorption = 0;
            damageInfo.TransferFactor = 1;

            if (damageInfo.DamageType != DamageTypes.RawDamage)
            {
                target.BuffInterface.NotifyCombatEvent((byte) BuffCombatEvents.BCE_ShieldPass, damageInfo, caster);

                #region Dealing/Receiving Event
                caster.BuffInterface.NotifyCombatEvent((byte)BuffCombatEvents.BCE_DealingDamage, damageInfo, target);
                target.BuffInterface.NotifyCombatEvent((byte)BuffCombatEvents.BCE_ReceivingDamage, damageInfo, caster);
                #endregion

                CheckCriticalHit(caster, target, damageInfo);

                caster.BuffInterface.NotifyCombatEvent((byte)BuffCombatEvents.BCE_DealtDamage, damageInfo, target);
                target.BuffInterface.NotifyCombatEvent((byte) BuffCombatEvents.BCE_ReceivedDamage, damageInfo, caster);

                #region General Multipliers

                damageInfo.DamageBonus += 
                    caster.StsInterface.GetStatBonusModifier((byte) BonusTypes.BONUSTYPES_EBONUS_OUT_DAMAGE_PERCENT) 
                    + target.StsInterface.GetStatBonusModifier((byte) BonusTypes.BONUSTYPES_EBONUS_INC_DAMAGE_PERCENT);
                damageInfo.DamageReduction *=
                    target.StsInterface.GetStatReductionModifier((byte) BonusTypes.BONUSTYPES_EBONUS_INC_DAMAGE_PERCENT) 
                    * caster.StsInterface.GetStatReductionModifier((byte) BonusTypes.BONUSTYPES_EBONUS_OUT_DAMAGE_PERCENT);

                #endregion

                // Guard is separate because it needs to come after shielding
                target.BuffInterface.CheckGuard(damageInfo, caster);

                damageInfo.ApplyDamageModifiers();
            }

            #region Application

            PacketOut outl = new PacketOut((byte)Opcodes.F_CAST_PLAYER_EFFECT, 24);

            outl.WriteUInt16(caster.Oid);
            outl.WriteUInt16(target.Oid);
            outl.WriteUInt16(damageInfo.DisplayEntry); // 00 00 07 D D

            outl.WriteByte(damageInfo.CastPlayerSubID);
            outl.WriteByte(damageInfo.DamageEvent); // DAMAGE EVENT
            if (multiplier == 1.0f)
                outl.WriteByte(0x07);
            else if (!bFinalize)
                outl.WriteByte(0x0B);
            else
                outl.WriteByte(0x0F);

            outl.WriteZigZag(-(int)damageInfo.Damage);
            if (damageInfo.Mitigation > 0)
                outl.WriteZigZag((ushort)damageInfo.Mitigation);
            if (damageInfo.Absorption > 0)
                outl.WriteZigZag((ushort)damageInfo.Absorption);
            outl.WriteByte(0);

            target.DispatchPacketUnreliable(outl, true, caster);

            if (target.ReceiveDamage(caster, (uint)damageInfo.Damage))
            {
                caster.BuffInterface.NotifyCombatEvent((byte)BuffCombatEvents.BCE_OnKill, damageInfo, target);

                damageInfo.WasLethalDamage = true;

                Player plrCaster = caster as Player;
                if (plrCaster != null)
                {
                    Player plrTarget = target as Player;

                    if (plrTarget != null)
                        SendDeathSpam(damageInfo, plrCaster, plrTarget);
                }
            }

            #endregion
        }

Please show me where there's a defense check in this code.
