### ISSUE TITLE
Auction House Issues are not being addressed.

### ISSUE THREAD

**Issue by TagTimeGaming** [WarEmu/WarBugs#6527]
Hello Devs.  I apologize if this is annoying because this is my second post about this; my first one was closed.  I know this issue is #1821.

The Auction House posts items based on when they were posted once they reach the Auction Limit.  Is this really intended?  This seems like a very serious economic issue, and #1821 doesn't even mention exactly what is wrong, nonetheless whether or not it is being paid attention to.  That post is from November of 2015 and the Auction House is still broken.  This can be easily manipulated to give people immense amounts of gold as well as ruin the auctioning experience for new players that do not understand.  I really think this should be given some attention and see if this can be fixed or adjusted.  Thank you for your time, and once again, I apologize for double-posting.

**Comment by Evildoor** [comment]
Go and read the rules of the bugtracker. Thoroughly, you've broken several of them.

> Is this really intended?

No.

> This seems like a very serious economic issue, and #1821 doesn't even mention exactly what is wrong, nonetheless whether or not it is being paid attention to.
> This can be easily manipulated to give people immense amounts of gold as well as ruin the auctioning experience for new players that do not understand.

Then this should be posted in #1821.
