### ISSUE TITLE
Greenskin oRvR ToK locked

### ISSUE THREAD

**Issue by Camoue** [WarEmu/WarBugs#6528]
Hello,
Yesterday i have entered "BFP" did't notice it in right moment, going for keep, keep taken.
When i was trying to see my gathered "Inf" i have seen in ToK that i didn' even get T3 Greenskin oRvR unlocked...
Today i have login, start some SC's and i get this in my chat for killing enemyes. (ToK still locked)

http://i.imgur.com/VImLd4y.jpg?1

What shall i do, may u fix me please, i mean im soon t4 so its not that big prob but this s*** in chat.

Thank you,
Cheers.

(I have asked GM ingame about this and he told me to write ticket on bugtracker)

**Comment by Evildoor** [comment]
#6320. Messages in chat have nothing to do with it, they are your exp gains for kills in scenario which are wrongly labeled as rewards for keep (see #4449, for example).

**Comment by Camoue** [comment]
I get them for killing normal NPC's too.

**Comment by Evildoor** [comment]
This is mentioned in #4449.

**Comment by Camoue** [comment]
Sorry
