### ISSUE TITLE
Zealot Chaotic Agitation 

### ISSUE THREAD

**Issue by Kweedko** [WarEmu/WarBugs#6529]
On official server this ability continue chaneling even target is out of line of sight, and out of range.

On live it stops immediately.

**Comment by Evildoor** [comment]
If this is true then all channels should work in the same manner, which sounds questionable to me. @ozarmidrashim , what do you think?

**Comment by Kweedko** [comment]
yep most of them worked that way, like abilities with cast time which not ended if it casted half way and target run out of range

**Comment by Kweedko** [comment]
find one https://www.youtube.com/watch?v=F4Iwvt9NWxA 0:36 zeal chaneling storm of ravens and slayer run away but channel still going.

**Comment by Kweedko** [comment]
and here https://www.youtube.com/watch?v=CLno108Cjjg  4:28 zeal got punted away and  used the Chaotic Agitation on slayer at most the same time, slayer gone out of line of sight but channel still going, i know that only couple of seconnds in this vid but skills worked that way on off server.

**Comment by Kweedko** [comment]
it's like BW and sorcr no need to see the spot directly when they channel Rain of Fire and pit of shades

**Comment by ozarmidrashim** [comment]
What I think is that it's ridiculous and that I'm not going to do anything about it.

People picking at the slightest issues with range and LOS/cancellation mechanics is doing my head in. RoR's channels tick once every second to determine range/LOS. If you're out of range, or you're out of LOS, your cast should break. That's counterplay. That RoR is slightly more aggressive than live in determining LOS/range violations is not an issue worthy of attention.

**Comment by Kweedko** [comment]
too bad
