### ISSUE TITLE
Taunt and Challenge doesnt work on BO

### ISSUE THREAD

**Issue by Yadizz** [WarEmu/WarBugs#6530]
Taunt and challenge doesnt work on black orc, since last patch.

**Comment by Evildoor** [comment]
Tested on mobs, damage is properly increased with taunt.

**Comment by Liczersky** [comment]
tested on mobs in DW on ruin PQ just about 1 min ago, doesn't work properly. I play marauder and my wife on BO, i get agro on mobs by damaging then 1 time aoe and she couldn't take them by tounting or chalanging, i didn't damage them anymore just to find out.

**Comment by Evildoor** [comment]
Agro system is barely implemented, so no need to report problems with it.

**Comment by Liczersky** [comment]
ok, so no chance for manti for my wife, just kiddins. But before last pach everything was fine with this and now it doesn't work. BO is useless as a tank now

**Comment by Evildoor** [comment]
So, Yaddiz is your wife's account?

**Comment by Liczersky** [comment]
yes it is

**Comment by Liczersky** [comment]
we checked this together

**Comment by Yadizz** [comment]
Doesnt work with tactic for 100% hate too.

**Comment by Evildoor** [comment]
Closing per my second comment.
