### ISSUE TITLE
Cannot open my loot bag from PQ

### ISSUE THREAD

**Issue by Yadizz** [WarEmu/WarBugs#6531]
Vgot my loot bag via email in game, and I cannot open it. Loot bags are not active for me.

**Comment by Evildoor** [comment]
How long it was in mail?

**Comment by Liczersky** [comment]
same with me. for 2 days in email and can't open my green lootbag, previous i had no problem with loot bags coming via email

**Comment by Yadizz** [comment]
Yesterday it was about one hour-same problem, today is about 12 hours.

**Comment by Evildoor** [comment]
Loot bags cannot be opened after server restart, so 12 hours and 2 days are most likely bugged because of this. One hour one - there were no restarts during that hour?

**Comment by Liczersky** [comment]
yes there was 1

**Comment by Evildoor** [comment]
#5768 then.
Side note - next time, please, don't answer the questions addressed to one account from another. Even if i'll remember that you play together, other people reading bug reports may be confused.
