### ISSUE TITLE
Harpies cancels Throw axe

### ISSUE THREAD

**Issue by iljuro** [WarEmu/WarBugs#6533]
First it was some of the harpies in Eataine, on the hill east of The Siege of Anyerrial PQ
Now it's the Bloodrend Shredders by the Dragon Corpse, at 9, 30 in Dragonwake.

I get a glimpse of the Throw Axe progress bar and then nothing, no text on screen, in either chat or combat logs. It doesn't use any action points and I can repress the button as fast as I'm able.

I've tried it on two different computers, one at work two days ago and now at home.

**Comment by Evildoor** [comment]
I'm pretty sure that this has nothing to do with you, and these harpies are supposed to be flying in the air, but are displayed on the ground.

**Comment by iljuro** [comment]
That would explain why I now have the same problem with the manticores next to them. But I strongly remember being able to throw axe at flying things in live to get them down for a whooping. But I can't hit them either, not even with Flurry so...

**Comment by ozarmidrashim** [comment]
Z-axis is wrong.

**Comment by Torquemadra** [comment]
They are essentially aerial decorations, we are just missing a byte which has them flying in the air.

**Comment by Lheana** [comment]
NPCs that are meant to fly are now flying. So this must have been fixed.
