### ISSUE TITLE
Witch Elf T4 Greenskin Epic Quest Rewards

### ISSUE THREAD

**Issue by SirBattosai** [WarEmu/WarBugs#6534]
Hey there!
Both of the greenskin epic quest rewards the Seeping Blade and Merciless have lower dps stats than their elven or chaos counterparts - not sure if it is intended.
 Regards

Edit: http://imgur.com/a/SaTrI screenshots of the weapons for easier comparison.

**Comment by SirBattosai** [comment]
There's also some inconsistency with the proccs going on - when I am not using any Kiss, the procc Judgement IX from Seeping Blade proccs just fine, if I use one though it does not procc at all.
I compared it with the procc Agony IX from Frenzy which seems to be unaffected in its functionality wether the kiss is enabled or not, thus working in both cases.

**Comment by Torquemadra** [comment]
weapon stats are historical, be happy you dont have a 4 second offhand like WHs ;)

**Comment by SirBattosai** [comment]
I guess I'll make another topic for my second comment then, thanks for the clarification though. ( slow offhands are good though, as they're moar bursty :>)
