### ISSUE TITLE
Equipment bug

### ISSUE THREAD

**Issue by sausobat** [WarEmu/WarBugs#6535]
This items cannot be equipped: 

[Fighter's Bloodwades of Vengeance] and [Fighter's Breastscale of Vengeance] (both DoK renown vendor equipment).

**Comment by magicthighs** [comment]
Confirmed on my DoK, rr9/r9, can't equip them.

**Comment by Evildoor** [comment]
Fighter's Armscales of Vengeance have the same problem. On WP: Fighter's Fists of Vengeance and Fighter's Spatterguards of Vengeance.

**Comment by Torquemadra** [comment]
marked as medium armour not medium robe, should be good next patch
