### ISSUE TITLE
Wash your hands!

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#6537]
Kill the plague victim Plague Feaster, a rank 19 Champion, in Ostland, located at 48k,32k.

```
If he doesnt come--click on basket of fish nearby* 
```

He's not there and clicking the basket doesn't do anything

**Comment by Meralors** [comment]
This is a scripted spawn and I'm afraid we can't fix that yet.

**Comment by Lheana** [comment]
Created NPC 'Plague Feaster', kill him for the unlock.
