### ISSUE TITLE
Aethyr Guard

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#6538]
Title Unlock: Aethyr Guard
Notes: Unlock: Colors of Horror Goal: This one's a bit unusual. Head into the broken up courtyard at this location. Try to pull a Pink and a Blue horror and kill them at the same time. Do this correctly, and a Purple Horror will spawn nearby. Kill it for the title unlock. Repeat a few times for a fun surprise!

Killing the horrors don't do anything.

**Comment by Evildoor** [comment]
#5639
