### ISSUE TITLE
Pillager's Greaves - no stats

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#6540]
![pillagergreaves](https://cloud.githubusercontent.com/assets/11015074/15634467/18083688-25cd-11e6-88cb-29b575d80a0c.jpg)

**Comment by saupreusse** [comment]
these are the quest rewards for the quest "blighted ambition". They are fixed in the next patch - same with #1187

**Comment by Evildoor** [comment]
> these are the quest rewards for the quest "blighted ambition"

Uh, not sure if i follow. Isn't "Pillager" stuff supposed to be lvl 15 generic green drop from mobs and PVP?

**Comment by saupreusse** [comment]
hmm let me check :)

**Comment by saupreusse** [comment]
yeap those are all fixed in the next patch. they drop from the quest AND in pvp. :)
