### ISSUE TITLE
Kisses interaction with Weapon Proccs

### ISSUE THREAD

**Issue by SirBattosai** [WarEmu/WarBugs#6541]
Hey there!
When I tested the WE t4 epic quest reward weapon seeping blade with the judgement IX procc it worked fine when I was not using an active Kiss. 
When activating a kiss though, the procc effect ceased to function, I tried different kisses, swapping the weapon from mainhand to offhand and re-equipping it, but to no avail.
On the other hand the other epic quest reward weapon I have, frenzy with the procc Agony IX still proccs with kisses active and without.
regards!

**Comment by Torquemadra** [comment]
Confirmed on dev, seems the case with WE direct damage procs and kisses

**Comment by SirBattosai** [comment]
Thanks for the hard work!
