### ISSUE TITLE
Pull/Fetch teleport

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#6542]
The current implementation of pull/fetch is a teleport to the player instead of a smooth flight like the animation would suggest. The moment the cast is successful the victim is being teleported to the pulling player.

It's obvious that both sides can easily abuse this behavior.
- The pulling player and people around him get hits in before the victim even realized that he was pulled. On my tank I can literally spam knockdown next to someone pulling and the moment he succeeds the cast the victim is kd'd.
- Classes with escapes can easily get away. Especially SWs/SHs.

**Comment by ozarmidrashim** [comment]
????

This is implemented by sending F_CATAPULT and processing player state. The server isn't doing any kind of position change, it just sends F_CATAPULT.

**Comment by taccr** [comment]
Well Torquemadra just removed the video where I show that it works for both sides...

**Comment by Torquemadra** [comment]
you mean the video in a place where you shouldnt be making them

**Comment by ozarmidrashim** [comment]
I saw the video, which has been linked privately. The point I'm making is that we send F_CATAPULT and wait for the client to update us. I don't think there's anything I can actually do about this.

**Comment by taccr** [comment]
I don't know how they did it on live but I was never able to instantly kd people the moment they were pulled. I also never saw someone instantly self punting away. Maybe you can figure this one out in the future.

Regarding the location:
- I already recorded many videos there, publicly available on this very tracker.
- Nobody actually sees where I am and has any gain from what he sees.
- Many people have access to the dev server.
- Security through obscurity is something you don't do.

**Comment by ozarmidrashim** [comment]
There's an issue with the packetlogger which causes the last byte of any packet to be 0, so it is possible that F_CATAPULT has some data we're not aware of. I'll log it later to see what the client's sending for position while in catapult.

**Comment by DanaBloodkiss** [comment]
@ Taccr 

"Regarding the location:
- I already recorded many videos there, publicly available on this very tracker.
- Nobody actually sees where I am and has any gain from what he sees.
- Many people have access to the dev server.
- Security through obscurity is something you don't do."

Don't record videos in VIP locations in future which you will share to the public. Thanks for removing the link.

**Comment by Thorgatin** [comment]
I'm pretty sure on the mythic server the attacker and others around him in melee range could damage the victim during the flight as well as the victim of a pull could damage the attacker (and probably people around him too), as if they were already in melee range of each other.
I guess we couldn't see this very often though, as most people probably had their GCDs running during the pull. But sometimes, against very coordinated assist groups, you got pulled and while in the air, got focus damage by the marauder and his groupmates to land dead.
This is why i always tried to use AOE detaunt and CC-immunity during the flight.

This strange behaviour added further to the shabbiness of pulls.

**Comment by redzus** [comment]
Alright i want to add my 50 cents too on that.  I see always people  on every, Pounce, self punt, pull my magus, engi, mara or WL  and even a kick, fly perfectly as its intented.
From experience, it behaves as it did on live, When i get pulled, i do not get damage, while in flight but at the moment when i can start walking again. unless i am hit in midair by range attacks, or by meele users i pass while flight. which are close enough to reach. I  do not really see  the issue some people present in here.

**Comment by Thorgatin** [comment]
1. That people don't do it doesn't mean that it can't be done; they probably just didn't notice yet and it depends if the players are aware of the situation and the game mechanic behaviour. E.g. you won't see this happening in 99.9% of all pug scs.
2. There was a video, which was removed, showing the behavior (couln't see it though)
