### ISSUE TITLE
Get stuck animation mounting when you mount and move forward at the same time.

### ISSUE THREAD

**Issue by Neutrinoo** [WarEmu/WarBugs#6543]
Reproducible.   On Magus - click mount and move forward at the same time.  Magus character get's stuck in crouched position.  Only way to break out of it is to cast another ability.

**Comment by Evildoor** [comment]
Happens to all classes, not only magus.

**Comment by Neutrinoo** [comment]
Still a problem - animation should cancel or mount animation should finish.

**Comment by Kaelang** [comment]
As this is a legacy issue, and lots has changed, please re-open if this issue persists as it should be fixed.
