### ISSUE TITLE
On my account I need to logon several times just on my magus to get into server.

### ISSUE THREAD

**Issue by Neutrinoo** [WarEmu/WarBugs#6544]
On my account I need to logon several times just on my magus to get into server.  Character name Neutrino - then sometimes I end up under IC in an area off the map.  I use my book and I have spawned behind the order warcamp in High Pass.  Lately is mostly just been logon issues.  Other toons on my account do not have this problem.

**Comment by Evildoor** [comment]
Read the rules of the bugtracker. Bugtracker is not dealing with inability to get into the game.
