### ISSUE TITLE
Dying of magus armor is terrible.  Not really new but limited armor in ROR is really bad.

### ISSUE THREAD

**Issue by Neutrinoo** [WarEmu/WarBugs#6545]
Dying of magus armor is terrible.  Not really new but limited armor in ROR is really bad.  The best dying armor in the real game was tyrant.

**Comment by Evildoor** [comment]
Uh, what? Are you telling me that you don't like the colors of magus armor sets in RoR?

**Comment by saupreusse** [comment]
Well what do you expect us to do? rework all the mage armors so they can be dyed in different locations? redesign them? the high level armor will make it into the game as we progress rebuilding the server and cleaning up the database. until then you have to work with what is already there. I dont think the dyeable parts of these armors were changed at all compared to live.

**Comment by ozarmidrashim** [comment]
Not a bug.
