### ISSUE TITLE
Oil on Outer AFTER door is down

### ISSUE THREAD

**Issue by deadkoo** [WarEmu/WarBugs#6547]
In TM right now, replaced oil above outer to kill order entering while we where attacking inner door. They actually had oil up on both inner and outer.

Searched and didn't see this specific oil bug yet.

**Comment by Torquemadra** [comment]
Not entirely sure why you consider this to be a bug, the outer oil never despawned with the main door down, indeed its part of the arsenal available to keep the other side from pushing through the open doorway. If you are attacking the inner secure the outer oil tower.

**Comment by deadkoo** [comment]
" You can no longer place a ram at an inner keep door before the outer door is destroyed
- Breaking an outer door will cause The outer ram to be destroyed"

Sorry, I misread/understood that. Via reading the last patch notes, my brain read those parts as Oil/ram wouldn't pop on outer once outer door was down. My mistake!
