### ISSUE TITLE
[Item] Slimed Big Choppa

### ISSUE THREAD

**Issue by ellionkeman** [WarEmu/WarBugs#6548]
The item seems to be wrong. It is written both hands but it is one manded weapon.

![yargahak_003](https://cloud.githubusercontent.com/assets/18136746/15648257/f0eddfb2-2671-11e6-90d5-59bb173109c8.jpg)

**Comment by Ryanfawkez** [comment]
It's supposed to be two-handed. Altered the model to a 2handed axe in the next patch.
