### ISSUE TITLE
Lair of Fesitt

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#6550]
Festitt is a rank 40 Rat Ogre Hero.

- [x] He should be Rat Ogre.Now he is something like Lizard named Deathscale.
- [x] He shouldnt be 46 Level but 40.

Source : http://warhammeronline.wikia.com/wiki/Lair_of_Fesitt

**Comment by Torquemadra** [comment]
Festitt isnt in game, lair bosses need reworking overall to reapply their abilities and innate armour penetration values

**Comment by Soulwhisper** [comment]
Alright.Didnt know that :+1:

**Comment by Torquemadra** [comment]
yeah its something Im working on at the moment so hopefully soon ;)

**Comment by Soulwhisper** [comment]
Thanks @Torquemadra
