### ISSUE TITLE
Lair of Morra

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#6552]
Dropped 2 Steeltoes of the Dire Wolf.
Morra drops 1-3 Rank 39 Rare BOE Boots per kill.
We cant put it on Auction House or Trade them because it says it is bound to player but it shouldnt.![123](https://cloud.githubusercontent.com/assets/16864486/15651071/d8843386-2685-11e6-863a-3f416d2f5731.jpg)
Source : http://warhammeronline.wikia.com/wiki/Morra

**Comment by Vayra** [comment]
Lair items were changed to be BoP on this server a while ago, IIRC.

**Comment by Evildoor** [comment]
You had at least one engi in the group?

**Comment by Soulwhisper** [comment]
Only 1.

**Comment by Evildoor** [comment]
#6456 then
