### ISSUE TITLE
Lair of Silveroak

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#6553]
Dropped 2 Bulwark of the silvered Oak for engi class too like #6552
We cant put it on Auction House or Trade them because it says it is bound to player but it shouldnt.It should be Bound on Equip.
Source : http://warhammeronline.wikia.com/wiki/Silveroak
![123](https://cloud.githubusercontent.com/assets/16864486/15651830/9882b6a4-268a-11e6-9af0-dddc37976acd.jpg)

**Comment by Evildoor** [comment]
Closing for the same reason as #6552.
