### ISSUE TITLE
Sometimes Trial By Pain Interrupting When You Move

### ISSUE THREAD

**Issue by ThunderMjolnir** [WarEmu/WarBugs#6554]
Those combo skills are bugged since on live. The Marauders' combo skill from Gift of Brutality was interrupted too when you move.

**Comment by Evildoor** [comment]
Video, please. There indeed were bugs in RoR which caused channels to interrupt for no reason, but they were fixed, and now channels are pretty reliable.

**Comment by Torquemadra** [comment]
note they do interrupt if you jump, I dont actually know if they are supposed to or not.

**Comment by Evildoor** [comment]
Yes, jumps should interrupt channels, IIRC.

**Comment by noisestorm** [comment]
also remember that every taunt you receive will also interrupt you. just in case.

**Comment by Evildoor** [comment]
No proof, closing.
