### ISSUE TITLE
[PQ] Ruinous Powers loot bags bug

### ISSUE THREAD

**Issue by ellionkeman** [WarEmu/WarBugs#6555]
Today I got 1st place making this PQ and received violet bag. But there was no gear. Only crafting ingrs.

![balphus_000](https://cloud.githubusercontent.com/assets/18136746/15652846/c5c1d8be-2691-11e6-91fc-347856c1e65d.jpg)
![balphus_001](https://cloud.githubusercontent.com/assets/18136746/15652847/c5c32b74-2691-11e6-90e3-0a97f6089acf.jpg)
![balphus_002](https://cloud.githubusercontent.com/assets/18136746/15652849/c5c4abde-2691-11e6-8b05-6501132de9bc.jpg)
![balphus_003](https://cloud.githubusercontent.com/assets/18136746/15652848/c5c46b7e-2691-11e6-9983-b255d8d8059f.jpg)

**Comment by Evildoor** [comment]
#5377
