### ISSUE TITLE
Rend Soul channel disappears

### ISSUE THREAD

**Issue by Blubberino** [WarEmu/WarBugs#6556]
Since the latest patch the channel of rend soul disappears right after using it causing some trouble to tell if you actually got interrupted or not.

maybe related to #843?

Maybe appears if you use weapons with procs like carnage and dusk or more than one enemy

**Comment by Evildoor** [comment]
Would like a confirmation on this. Logged on DoK, RS worked properly.

**Comment by ozarmidrashim** [comment]
Also playing DoK, RS working fine.

**Comment by Blubberino** [comment]
Don't know if it was just temporal but just occured today as seen in the video and I'm not sure what the cause for it is will test it again if server is back up. 

Also it's only visual ability still does it's job but the channel disapperars

**Comment by Evildoor** [comment]
Had this (or similar) problem today, but on Zealot - cast bar sometimes disappeared when i was casting something and received damage during cast. However, this looks like a client problem, and i'm not sure that it was not same on live, so not reopening.

**Comment by ozarmidrashim** [comment]
Rend Soul cannot be set back, so it's not that.
