### ISSUE TITLE
NPC Ironclaw 'Eadbusta are lvl 1 naked dwarves instead of Orks (Ekrund, 1rst PQ)

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#6559]

**Comment by saupreusse** [comment]
there are 0 spawns for Ironclaw Headbasha in the database, could you please provide a screenshot? Thanks!

**Comment by avenflar** [comment]
http://imgur.com/SzvFDni

Here you go

**Comment by saupreusse** [comment]
seems like someone else fixed it already. can be closed.
