### ISSUE TITLE
AM - Transfer Force

### ISSUE THREAD

**Issue by Lileldys** [WarEmu/WarBugs#6563]
If the killing blow on a mob/player is from a tick of "Transfer Force", it ticks the heal aspect of the skill twice. 
![wutwut_021](https://cloud.githubusercontent.com/assets/13259775/15659686/df14b2c0-26c6-11e6-9a90-32b5fe7cf5af.jpg)

**Comment by Kaelang** [comment]
As this is a legacy issue, and lots has changed, please re-open if this issue persists as it should be fixed.
