### ISSUE TITLE
Quest: Misinformation

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#6564]
No mob in the RvR area to turn this in. Should be a Fellwhisper Scout.

That or the quest blob is in the wrong location. I didn't see anything there resembling an "abandoned cairn"

**Comment by Ryanfawkez** [comment]
Fellwhisper Scout spawn missing.

**Comment by Lheana** [comment]
Works fine now. The NPC is in Caledor, east border next to DW.
