### ISSUE TITLE
[Witch Elf] lair boots

### ISSUE THREAD

**Issue by stillwaterww** [WarEmu/WarBugs#6566]
these have got bs on em sure it had its uses once, but probaly not anymore
![sorrowstrike_006](https://cloud.githubusercontent.com/assets/19287032/15661766/15a7c54c-26eb-11e6-8263-ab458e39e4dd.jpg)

**Comment by Evildoor** [comment]
Is this wrong? Weren't lairs changed to drop BoP items, but guarantee that at least one of the group members would be able to use them?

**Comment by Vayra** [comment]
The drop is the correct class, Evil, just it's a Witch Elf item with Ballistic Skill on it. Ie it has a useless stat.

**Comment by Evildoor** [comment]
Oh, sorry, my bad. Too much reports about BoP from lairs.

**Comment by saupreusse** [comment]
I am going to rework all these boots... they have a lot of wrong and missing stats. will take some time.

**Comment by saupreusse** [comment]
Aaaand they are fixed.

**Comment by stillwaterww** [comment]
Awesome news :)
