### ISSUE TITLE
Missing Mercenary Gear From Bag

### ISSUE THREAD

**Issue by Strongnoff** [WarEmu/WarBugs#6567]
Saturday 28/05/2016 after putting together all the money a had and asking some from my friends, i finally managed to by from the auction house a pair of boots and a pair of gloves from the Mercenary set. I paid 120 gold for each for a total of 240 gold expended. Today is the 31th of may and i just logged to play a few scenarios and my Mercenary equipment is gone, i still have the helm i got from emblems, but the gloves and boots are gone,
I ask of you kindly to plz return to me this itens if possible, and if not at least the money. Iam not a hard core player so for me it was a really big effort to get this far and i was really exited for finally having my choopa well geard.
The Character name is Strongnoff, a lvl 39/39 choppa.
Please help me out, i love the game and the work you guys are doind, so plz dont let it end in a bad way for me.
Thank you.

**Comment by Evildoor** [comment]
Sorry, nothing doing. Point 3 of the rules.

**Comment by Strongnoff** [comment]
Really? is that all?
it must not be so hard for you guys to verify that im not lying and to give me simple gold coins.
this kind of thing is the kind that really takes away all the point in playing and getting your gear and stuff. if your hara earned fruits get taken away from you.

**Comment by Evildoor** [comment]
1) It was said 1000 times already - this is alpha and you are tester, not player. Resurrecting WAR is first and foremost, the fact that you can play your favorite game is just a bonus. Expect wipes, bugs, item losses and other problems.
2) No, we cannot verify what was lost, check the rules, it's said there.
