### ISSUE TITLE
Destro Quest "The Last Full Measure" - quest item not attackable

### ISSUE THREAD

**Issue by appdevman** [WarEmu/WarBugs#6568]
In the IC Lyceum, you can select the display case that houses the chalice, but it is not attackable.  (you need to break the case and take the chalice).

Thanks for all your hard work devs!    : )

**Comment by saupreusse** [comment]
we can not give players the ability to break the case yet, so i made a workaround: you have to loot the case by rightclicking! Also added a missing quest marker on the map.^^
