### ISSUE TITLE
Quest: New Allies, New Enemies

### ISSUE THREAD

**Issue by pixie126** [WarEmu/WarBugs#6569]
Kill Outcast Dark Elf
Cannot kill the Outcast Dark Elf.  He is way too friendly even after prodding him  a few times.
![xramoth_008](https://cloud.githubusercontent.com/assets/15041016/15664221/9d4ec438-26c7-11e6-8f39-a324801d47e5.jpg)

**Comment by pixie126** [comment]
Sorry, this is a Dwarf Chapter 15 Quest.

**Comment by Evildoor** [comment]
#5739
