### ISSUE TITLE
[Quest] Scouting the Gates - Order, Ekrund

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#657]
This quest auto-completes itself without doing any scouting of the gates.

There a several other quests with similar issues like this at each Warcamp.
Ekrund
Scouting the Gates
Evicting the Squatters 
Ironmane's Defense

**Comment by Reggaewaldo** [comment]
This is a know issue that we can't emulate the "scout" objective properly so a handler needs to be created for that.

**Comment by Reggaewaldo** [comment]
Closing and will reopen when we can fix.
