### ISSUE TITLE
Siege weapons of the enemy to convert from PVE to RVR status. 

### ISSUE THREAD

**Issue by Pushkarbeavers** [WarEmu/WarBugs#6570]
If you shoot from siege weapons a character in the RVR status on the character in PVE status, the character in PVE the status will automatically change the status to RVR.
This can use the gunker by killing players running PVE status.
Around Barkanov and PVE siege weapons a lot, that gives space for gank

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Pushkarbeavers** [comment]
since I stopped playing in the project, and only sometimes I go to look at the changes. So I don't care any more relevant bug.
