### ISSUE TITLE
Choking Arrer

### ISSUE THREAD

**Issue by Symbelmyne** [WarEmu/WarBugs#6573]
Yesterday ive noticed SH silence skill stopped working, or didnt work most of times. After fight with one BW in MTemple I payed higher attention to how Choking Arrer works. I fought said BW 3 times in a row, I used 3 times silence, 1st didnt work, granted no immune, got CD on skill and no effect - was casted with many BW dots, 2nd time I casted silence and it didnt fire, 3rd time same as 1st one. After that I watched my targets buffhead immunes for CC and when i used silence, it didnt stop targets to cast, skill went on CD. It happened 3 times in a row, fighting 2 WPs and 1 AM in Praag scenario. All that stuff happened after I respeced to Finishem Off and used full Mercenary SH set for extra skill point.

**Comment by Kaelang** [comment]
I'm going to close this as a legacy issue however this should have since been fixed.
