### ISSUE TITLE
War Priest standing up on mount when jumping.

### ISSUE THREAD

**Issue by Rilos** [WarEmu/WarBugs#6575]
When riding on a mount, he auto stands when jumping.

**Comment by Soulwhisper** [comment]
It was like that on live too.It has something to do with the gear.While you level up and change gear he stops doing that.

**Comment by Evildoor** [comment]
> It was like that on live too.

I agree with this.

**Comment by Evildoor** [comment]
No objections to comments, therefore i'm closing this as client problem which cannot be fixed by us.
