### ISSUE TITLE
Magus - Dissolving Mist & Daemonic Infestation don't work with Close Quarters tactic

### ISSUE THREAD

**Issue by Lilisai** [WarEmu/WarBugs#6576]
**Dissolving Mist**
Error: 8494 Dissolving Mist threw an unhandled NullReferenceException from Boolean ObjectWithinRadiusFeet(World.Server Object, Int 32).

**Daemonic Infestation**
Error: 8541 Daemonic Infestation threw an unhandled NullReferenceException from Boolean ObjectWithinRadiusFeet(World.Server Object, Int 32).

Edit: I didn't place them out of range.

**Comment by Vayra** [comment]
#6331 

It's due to the Close Quarters tactic, remove it and it will work
