### ISSUE TITLE
Apothacary problem

### ISSUE THREAD

**Issue by Bomburin** [WarEmu/WarBugs#6578]
If you get Ingredients in from viper pit (most likely same in sigmars hammer.) and you get: preserved Aneroxic bat wing, preserved chemarical claw, and brittled chitin shard etc. and use them it will not put it in the crafting window. and you cannot take anything out or put anything in, it still doesn't work if you close the window. the only way to stop it from not working is to relog. but don't use those ingredients they will still stop your crafting.

**Comment by Evildoor** [comment]
#5286
