### ISSUE TITLE
[Ability] Taunt and Challenge don't cause aggro

### ISSUE THREAD

**Issue by Ryanfawkez** [WarEmu/WarBugs#6579]
Since yesterday, the tank abilities Taunt and Challenge have stopped working as aggro pullers. Whenever these abilities are used, the caster enters a combat state, but the NPC is virtually unaffected by the aggro pull effect.

**Comment by Evildoor** [comment]
Tested on dev, it worked.

**Comment by taccr** [comment]
Taunt/Challenge pulls the npc when it is out of combat. No effect when someone else is has aggro.

**Comment by Vayra** [comment]
Can confirm, I was xp farming with my zealot last night and the tank was unable to pull mobs off myself or the sorc with taunt / challenge. They only worked to pull the mobs at the start of combat.

**Comment by Evildoor** [comment]
It's the same as #6530 then. According to my knowledge, aggro system is pretty much nonexistent for now, so i don't see any reason to report problems with it, even if something changes.

**Comment by Ryanfawkez** [comment]
@Evildoor, aggro pulls while NPCs were in combat with another target used to work just fine until recently. This sudden change is quite a concern, in my humble opinion. Not having an aggro system has nothing to do with the fact this ability is now broken, as it worked as intended before.

**Comment by Evildoor** [comment]
All right.
