### ISSUE TITLE
Charge! and its removal

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#658]
Charge! should end immediately when you use any ability (not sure about some things like Marauder's mutation swap). From my observations, currently it is removed when you deal damage. This leads to following things:
1) Autoattack removes charge. Since for now you have to be very careful with your abilities (no ability queue implemented yet, press button too early and you waste AP/cooldown/GCD without any effect), it is pretty easy to waste your charge because your character autoattacks your target before you can use snare or something else. To avoid this you can clear your targets, charge, catch up with an enemy, then quickly target and hit them, but its clunky.
2) Detaunt does not interrupts charge, neither do aoe abilities if you hit no one with them.
3) Axe/choppa/whatever throw interrupts charge when it hits, not when you start throwing.

**Comment by ozarmidrashim** [comment]
Just a note: I'm rewriting a lot of the ability, buff and damage handling. It's not really worth reporting bugs based on the old code for that reason.

**Comment by Evildoor** [comment]
Fixed in 21.05.2015 patch. Closing.
