### ISSUE TITLE
[Gear] Enervating Pummelers, broken icon and appearance

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#6582]
As the title suggests the appearance is missing from the marauder item Enervating Pummlers and the icon shows a pair of boots.
![rezalevadgib_005](https://cloud.githubusercontent.com/assets/13975292/15695360/0935b73e-276c-11e6-808c-f770d11d39e5.jpg)

**Comment by saupreusse** [comment]
fixed in next patch
