### ISSUE TITLE
[NPC] Inner Keep Champ NPCs leaching and destroying Ram

### ISSUE THREAD

**Issue by Krazis** [WarEmu/WarBugs#6585]
Hey there 

At a recent siege in Pragg, we experienced the inner keep NPCs of the Garrison of Skulls leaching through the inner door and targeting the ram. These NPCs did considerable damage to the ram, to the point where the ram would go down in about 20 seconds. 

I assume the NPCs are not meant to leach through the inner door to target the ram, but that was the case. 

Thanks, let me know if you need more clarification.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
