### ISSUE TITLE
Oil Bug - Abilitys useabel while using oil

### ISSUE THREAD

**Issue by Farkitin** [WarEmu/WarBugs#6586]
Hey there,

I´ve just noticed, that you can use your greyed out Abilitys while you are using the oil.
There is also a pop up, that you cannot use Abilitys while operating a siege weapon.  
I believe that should not be.

https://youtu.be/eQcvr6kgQ5M

Best regards

Farkitin

**Comment by sioding** [comment]
fixed with patch from 08.12.2018
