### ISSUE TITLE
Destro IC Quest "Book Return" - can't interact with any book stack in Lyceum

### ISSUE THREAD

**Issue by appdevman** [WarEmu/WarBugs#6588]
If you enter the general area advised by the quest instructions, there are three different stacks of books on the floor that appear to allow interaction (place mouse cursor on top until icon changes to a hand);  however right-click does not perform interaction (on any book stack).  Quest can not be completed at this time.

Thanks for all your hard work devs  : p

**Comment by saupreusse** [comment]
the right pile of books was missing. i added one in the northernmost place in the lyceum. fixed!
