### ISSUE TITLE
[item] Gale-Runner's War Shroud

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#659]
This item is classified as a Helm atm, but it should be a Back Piece.

**Comment by ozarmidrashim** [comment]
War Shroud is the generic name for a Slayer helm  (see also: War Shroud of the Bandit Queen). It has the wrong model.

**Comment by Reggaewaldo** [comment]
Checked the item and it is properly displayed as a Helm.

Closing.
