### ISSUE TITLE
bug into house of praag

### ISSUE THREAD

**Issue by Magteridon** [WarEmu/WarBugs#6590]
you can attack  other faction into of house
![magteridon_013](https://cloud.githubusercontent.com/assets/16975012/15712595/402ee844-2813-11e6-8bb7-3e5851a9f53f.jpg)
![magteridon_014](https://cloud.githubusercontent.com/assets/16975012/15712596/40336180-2813-11e6-97de-088ca2af69bb.jpg)
![magteridon_016](https://cloud.githubusercontent.com/assets/16975012/15712941/9e8cc126-2814-11e6-9c17-2ee49c41fd6d.jpg)

**Comment by saupreusse** [comment]
fixed :)
