### ISSUE TITLE
Mount not showing

### ISSUE THREAD

**Issue by akalukz** [WarEmu/WarBugs#6591]
So on my son's account, for a couple of days now, periodically when mounting his mount doesn't show up, but he can move at it's speed.  At first I thought it was just visual on his client, but then we were in RvR together and it looked like he was just running that fast on my screen as well.  Would really hate to see someone banned over this.   Let me know if I need to provide more details or screenshots etc.

**Comment by Torquemadra** [comment]
Are you certain its not happening when going through water? This happens more to dwarves/goblins

**Comment by Renork** [comment]
This happened to me on 5/31 and 6/1 also. I did not go over any lakes/water.

**Comment by akalukz** [comment]
Torquemadra, this happened 2-3 times.  Once in Gates of Ekrund, once in Talabacland RvR, and once in Highland PVE area around the stalker quest hub.   I will get screenshots if happens again.

**Comment by d3BugErr** [comment]
Don't know about how it looks from another player but it is totally repeatable by just going in water while on mount - it just disappears save for the speed buff. Going out of water still keeps the buff and no horse, at least for me.
Bonus: mounts are allowed to be summoned in water resulting in quirky animation.

![waterhorse1](https://cloud.githubusercontent.com/assets/25364850/22929754/44c5e0ca-f2ce-11e6-860c-05e305799093.jpg)
![waterhorse2](https://cloud.githubusercontent.com/assets/25364850/22929756/44ca76ee-f2ce-11e6-9275-7c8d4b1c3ab1.jpg)
![waterhorse3](https://cloud.githubusercontent.com/assets/25364850/22929753/44c3ec3e-f2ce-11e6-9658-2151c24b583f.jpg)
![waterhorse4](https://cloud.githubusercontent.com/assets/25364850/22929755/44c76350-f2ce-11e6-8e05-5c8de001d993.jpg)

**Comment by grunbag** [comment]
Fixed while ago
