### ISSUE TITLE
Quest: New Allies, New Enemies Ch. 17 Praag

### ISSUE THREAD

**Issue by pixie126** [WarEmu/WarBugs#6593]
This quest is unable to be completed due to an invalid go.  Can do the other 3 parts , but not the last.
NPC that gives quest is Yalgon Sparktamer.

![xramoth_010](https://cloud.githubusercontent.com/assets/15041016/15713699/0ebfcdd6-27dd-11e6-9e8e-83f3978a7c22.jpg)
![xramoth_011](https://cloud.githubusercontent.com/assets/15041016/15713706/1189e966-27dd-11e6-936c-77336a1424eb.jpg)

It's chests of Stolen Gromril that are the 3rd part of this quest. 

Thank you.

**Comment by Evildoor** [comment]
#5787
