### ISSUE TITLE
Quest: Daemon's Gate Ch. 16 Reikland

### ISSUE THREAD

**Issue by pixie126** [WarEmu/WarBugs#6594]
Sorry, this is in Reikland not Praag.  I was confused.  :)
Quest given by NPC Hartmann Gottschalk has an invalid creature.

Invalid Creature, plz report to GM. Quest ID 30512, Objld=57857  0 of 1

Thank you.

**Comment by Evildoor** [comment]
FYI - you can change the name of your tickets.
