### ISSUE TITLE
Kotbs/Chosen T4 Epic Quest Twohander Stats

### ISSUE THREAD

**Issue by fiazco** [WarEmu/WarBugs#6598]
I don't know if the Stat gaps are intended, but 20Stats difference on High Sun -> Doom's Edge seems a bit off since both Swords got the same Stats (STR / WOU / INI). Posted my Weaps with Talis but should be no problem right ?

![warsong](https://cloud.githubusercontent.com/assets/17479149/15719289/93e94aee-282f-11e6-87fc-bfd621646a46.jpg)![torment](https://cloud.githubusercontent.com/assets/17479149/15719310/a3dcea00-282f-11e6-90c8-e468b8a021ee.jpg)
120 Stats  -> 133 Stats

![high sun](https://cloud.githubusercontent.com/assets/17479149/15719292/991ddf34-282f-11e6-82ef-cdab4894a333.jpg)![dooms](https://cloud.githubusercontent.com/assets/17479149/15719305/a198f6a8-282f-11e6-8a22-192e86cbe8d9.jpg)
136 Stats  -> 116 Stats

![dawn](https://cloud.githubusercontent.com/assets/17479149/15719299/9e68d480-282f-11e6-920e-f94e36f826ad.jpg)![anarchy](https://cloud.githubusercontent.com/assets/17479149/15719302/a03eb0d6-282f-11e6-8672-d6a41b39d401.jpg)
136 Stats  -> 124 Stats

**Comment by Evildoor** [comment]
I do believe that @Torquemadra 's comment to #6534 applies here.

**Comment by fiazco** [comment]
Just 18 Stat points off... sry cant math today

**Comment by fiazco** [comment]
Ah ok @Evildoor thanks
