### ISSUE TITLE
Altdorf gate

### ISSUE THREAD

**Issue by Luth-RoR** [WarEmu/WarBugs#660]
There is one gate in Altdorf, that doesn't work yet:

![luthiell_008](https://cloud.githubusercontent.com/assets/8567481/6638040/f8a83c82-c981-11e4-9198-82e413f7646f.jpg)

![luthiell_009_crop](https://cloud.githubusercontent.com/assets/8567481/6638037/eefe5216-c981-11e4-9af6-98dfd00a0fdb.jpg)

**Comment by MaxHayman** [comment]
Must have missed one! Is it clickable at all?

**Comment by Thorgatin** [comment]
No, it's just the gate in the front. The gate behind this one works.

**Comment by Reggaewaldo** [comment]
Confirmed, Still the same issue here.

**Comment by Kushido** [comment]
Fixed the right gate. Front gate still need fix, trying to find door id.

**Comment by Ryanfawkez** [comment]
https://i.gyazo.com/c2ca308520b4d904793d1f934ff1601a.jpg

**Comment by Luth-RoR** [comment]
![](https://media.giphy.com/media/3o7TKJhBfNCiispgDm/giphy.gif)
