### ISSUE TITLE
bug map in rvr kadrin valley 

### ISSUE THREAD

**Issue by Magteridon** [WarEmu/WarBugs#6600]
can acces to 2 camp , destru and castle order
![magteridon_031](https://cloud.githubusercontent.com/assets/16975012/15720842/6fd40764-2836-11e6-83fe-922375ff5930.jpg)
![magteridon_032](https://cloud.githubusercontent.com/assets/16975012/15720841/6fd3e284-2836-11e6-9e1e-15ea9396edb2.jpg)
![magteridon_034](https://cloud.githubusercontent.com/assets/16975012/15721193/29fe57a6-2838-11e6-83ca-5cf4d85e0e3f.jpg)

**Comment by saupreusse** [comment]
fixed it.. i think :) you can try to do it but i placed some warcamp guards that will kill you if you get to close^^

**Comment by Magteridon** [comment]
Tomorrow check again

**Comment by Magteridon** [comment]
i try again today  and no see changes..
![magteridon_035](https://cloud.githubusercontent.com/assets/16975012/15740793/e1e20344-28b6-11e6-80e5-b21fca530971.jpg)

**Comment by Evildoor** [comment]
Fix pending = fixed in next patch, not already fixed.
