### ISSUE TITLE
[Ability] Rain of fire null reference exception

### ISSUE THREAD

**Issue by equite** [WarEmu/WarBugs#6601]
Rain of fire bugged. Chanelling bar doesnt move, but it starts CD after using. Ability doesnt generate heat and cause no damage, throwing null reference error in chat
![whiterun_000](https://cloud.githubusercontent.com/assets/19678040/15725113/b8155e24-2863-11e6-9ea2-d4cae8b0cdd6.jpg)

**Comment by Torquemadra** [comment]
close quarters tactic?

**Comment by equite** [comment]
Yes, didnt know that tactic is the bug reason

**Comment by Torquemadra** [comment]
#6602 ?

**Comment by Evildoor** [comment]
#6331
