### ISSUE TITLE
PQ Loot Bag offering an Officer's Medallion

### ISSUE THREAD

**Issue by Sovox** [WarEmu/WarBugs#6603]
My **Minor Loot Bag** I received in the mail from the **PQ ->Caladain's Furnace<-** offered me an **[Officer's Medallion]** as a reward choice option **(?)**. 

____________________________________________________________________________
![lestrange_021](https://cloud.githubusercontent.com/assets/19616566/15732111/31b17428-282f-11e6-96cd-825b6c811e14.jpg)
![lestrange_022](https://cloud.githubusercontent.com/assets/19616566/15732113/33c4ff0a-282f-11e6-97bd-6d4897394291.jpg)

____________________________________________________________________________

{ _**Note**: This was the only PQ I took part in today, so I am absolutely positive it is from there. Also, I have not accepted a reward from this said loot bag as of yet; just in case._ }

**Comment by Torquemadra** [comment]
Everythings ok from the database on the dev server, will have to look into it further

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by Sovox** [comment]
@Ryanfawkez Woo-hoo~ Thank you very much! { Does this mean I'm eligible for a Manticore Mount now, lol? :P }
