### ISSUE TITLE
[Quest] t4 dwarf ch20 "Mending Grimlina"

### ISSUE THREAD

**Issue by Gakvar** [WarEmu/WarBugs#6605]
I'm supposed to speak to Darrin Garrikson inside a tower in Black Crag, but the door is non-interactible, although it seems he's inside.

**Comment by Evildoor** [comment]
Door coords.

**Comment by Gakvar** [comment]
The place is called Infested Tower in Black Crag. 42000, 18000

**Comment by Lheana** [comment]
Fixed the door, so you can know complete the quest.

**Comment by sioding** [comment]
Fixed with patch from 13.1.2018
