### ISSUE TITLE
Renown abillity's dissapear after relog

### ISSUE THREAD

**Issue by carmine3161** [WarEmu/WarBugs#6608]
Overall the renown ability upgrade mechanic seems to be in trouble, the UI for available points and spent points are never really truthful until you re spec you entire renown tree. I log in spend my renown points and i get the stat upgrades but when i log of and then on the UI from the merchant shows me Ive spent all remaining points but have no effect to any of my stats, I have to re spec my entire renown tree in order to get any benefits every time i log in this is annoying and i feel this isn't intended. however im grateful for your work so far and I am willing to deal with this but hopefully it will be fixed in the near future, thank you.

**Comment by Evildoor** [comment]
#1486
