### ISSUE TITLE
Phys RDPS mainhand weapons

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#661]
Since WH's pistols were fixed, lets fix RDPS' weapons too. Currently there are no Vengeance and Dominion mainhand weapons with ballistics, so i suggest:
1) Replace 13 STR with 13 BAL on Spanner of Vengeance. It's available only to Engis, who have no use for STR (except melee AA).
2) Same with Spanner of Dominion - 14 STR and 8WS only for Engi, change to 14 BAL 8WS.
3) I guess High Elves' sword for SW is Falcata of Vengeance with 13 STR. There is a problem that it can be used by SM (if they want 13 STR over 9 STR 4 TOU from Blade of Vengeance), who may disagree with changing it to 13 BAL, so i guess it's better to create new sword with 13 BAL strictly for SW.
4) High Elves' Dominion weapons: Falcata gives 14 STR 8 INI, Blade gives 21 STR. Same solution as 3, i guess?
5) I'm not an experienced SH player (and SH has different melee attacks with spear and with Battle Squig, with BAL=>STR conversion only in Battle Squig), so i don't know, do they need changes on their spears or not. Some input from SH players on this point will be useful.

**Comment by ozarmidrashim** [comment]
On point 5): SH melee in general needs fixing, and the real way to do that is to give them a means of converting Ballistic Skill to Strength that ISN'T dependent on using the ridiculous and self-limiting Squig Armor.

**Comment by Reggaewaldo** [comment]
@ozarmidrashim How about to give SH something like the RP / Zealot stat convert buff ? Balance issue ofc.

**Comment by Evildoor** [comment]
Fixed weapons from PVP vendors to have stats useful to phys RDPS. List of affected items:
Engineer: Spanner of Vengeance, Spanner of Dominion, Spanner of Conguest, Echelon Spanner, Martial Spanner.
Shadow Warrior: Falcata of Vengeance, Falcata of Dominion, Falcata of Conguest (added to vendor in Altdorf), Sentry Falcata, Echelon Falcata, Martial Falcata.
NOTE: SW swords can be used by Swordmasters, so those of them who used Falcatas will have to change their weapons.
Squig Herder: Stabba of Vengeance, Stabba of Dominion, Stabba of Conguest, Sentry Stabba, Echelon Stabba, Martial Stabba.
