### ISSUE TITLE
Issue with stun immunity from WH

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#6612]
There is either an issue with Declare Anathema NOT granting immunity, or Pistol Whip ignoring immunity.

I just got stunned by both within 8 seconds of each other by the same WH
As you can see in the screenshots below, I was disabled by Declare Anathema at 16:21:21, then I was hit by Pistol Whip at 16:21:28 and again disabled when I tried to use abilities at 16:21:29. There should have been an immunity running when I was hit by Pistol Whip, I did not get a screenshot of my UI at the time so I can't tell if I did have an immunity and Pistol Whip ignored it or if DA did not grant immunity at all. 
![forkrul_013](https://cloud.githubusercontent.com/assets/1183293/15748556/a93a43de-28df-11e6-9dfe-bdec066d6ef8.jpg)
![forkrul_014](https://cloud.githubusercontent.com/assets/1183293/15748560/ab7f826c-28df-11e6-8f59-88923025c0ce.jpg)

**Comment by Torquemadra** [comment]
DA gives a smaller immunity, i think 10 seconds which puts it pretty close

#5914

**Comment by Vayra** [comment]
10s immunity for a 5(?)s stagger? That sounds extremely low, but if that's the case the immunity might just have run out.

**Comment by Renork** [comment]
The 10s immunity is correct on DA.

**Comment by Blubberino** [comment]
It's a 6 second stagger. Yep is extreamly low warhammer online career builder says it should be 3s stagger. However in the video tesq posted in the other thread you can clearly see the 6s stagger + 10s immunity.

**Comment by Luth-RoR** [comment]
On patch 1.4.7 mythic unified knockdowns/staggers/roots on all classes:
https://web.archive.org/web/20131227093334/http://www.warhammeronline.com/article/Game-Update-147-1018
The only exceptions were CC abilities with a duration that is linked to a career resource (e.g. black guard KD).

These changes were pushed live without adjusting immunities for some staggers; that means:
The WH/WE had their low pre-1.4.7 immunities on their buffed single target staggers (3 -> 6 seconds) and the knight/chosen had their high pre-1.4.7 immunities on their nerfed AOE staggers (9 -> 3 seconds.
This was _obviously_ a bug, as special immunities on certain abilities make no sense when someone broadly changes the hard-CC in the game to unify it and no one mentioned this exception in the patchnotes. Furthermore the immunities on the abilities were _exactly_ the same as before the patch, which is another hint for a bug.

Please keep in mind that 1.4.8 WAR was **not** bug-free.

**Comment by grunbag** [comment]
fixed with next patch
