### ISSUE TITLE
Mark of remaking

### ISSUE THREAD

**Issue by Torquemadra** [WarEmu/WarBugs#6613]
Currently when this activates it gives a 10 minute window of opportunity to accept the resurrection, on live this was 60 seconds to prevent dying, waiting for a strategic area to clear out then taking the rez and picking up a potentially large amount of corpses behind enemy lines and within defenses.

**Comment by noisestorm** [comment]
In case aza mixed something up: The rezz-component of this buff was timed 10 min (but thats stated in the tooltip iirc) so you couldnt stack multiple rezzbuffs from one healer alone. After the 10 minutes the buff remains as a normal toughness boost without any other effects.

**Comment by Blubberino** [comment]
Wasn't 10 minutes but also not 60s video would be helpful here to clear things up before it get's fixed.

**Comment by Luth-RoR** [comment]
Closing this, as https://github.com/WarEmu/WarBugs/issues/8138 has more details.
