### ISSUE TITLE
Abilities bugged.

### ISSUE THREAD

**Issue by Brigamartis** [WarEmu/WarBugs#6614]
I have a Bright Wizard(Jesin) and an Engineer(Jerryrig). In both cases certain abilities have stopped working. On the BW the rain of fire just keeps sending me nullobject references and has done for three days now. On my engineer, the land mine has started doing the exactley same thing. Theres no gfx, apart from on rain of fire the cast bar gets stuck on full, no dmg dealt. On engineer absolutely nothing except for CD on landmine is active, again no dmg to enemies or action or GFX. I am going to try and reinstall and see if that fixes it, but relogging and closing client down isnt fixing it. Thankyou for your time.

**Comment by Evildoor** [comment]
#6331
