### ISSUE TITLE
Elvish epic weapon for Shadow Warrior

### ISSUE THREAD

**Issue by myhra** [WarEmu/WarBugs#6615]
The proc from the elven epic quest sword "Wyvern's Talon" doesn't seem to work.

After testing it with several attack skills including both, range and meele, and a decent amount of repetitions still no proc.

**Comment by Evildoor** [comment]
Proc name.

**Comment by myhra** [comment]
The proc name is "Judgement IX".

**Comment by Torquemadra** [comment]
Proc works 100%

However seems to be some sort of stacking or sequence issue that is preventing DD proc from working when having another proc weapon when its in the main hand

Will require investigating, thanks for the report.

**Comment by myhra** [comment]
I tested it with only one proc weapon, my bow was one which you can buy with scenario tokens. However, I had Bullseye tactic equipped. But after testing without other procs, still no damage proc on meele and range skills. Strange.

**Comment by Torquemadra** [comment]
![torquesw_011](https://cloud.githubusercontent.com/assets/16200780/15758668/a2793862-28d9-11e6-9d6c-23c0b9c645df.jpg)

Yep, requires investigation

**Comment by myhra** [comment]
![myhra_000](https://cloud.githubusercontent.com/assets/19335341/15759321/891ba1b8-290e-11e6-82c7-b7a021782636.jpg)

Half an hour keep fight. No proc :/

**Comment by Torquemadra** [comment]
But you would have had your bow on for that which seems to be "blocking" it so to speak

**Comment by HappyCultist** [comment]
Hi again!
The procs DO work if i'm stanceless, but as soon as i enter assault/scout/skirmish, the weapons won't proc anymore. Even with only one weapon equipped.
It looks like you were not using any stance in your screenshot, but maybe i'm misunderstanding something here.

**Comment by Kaelang** [comment]
I'm going to close this as a legacy issue however this should have since been fixed.
