### ISSUE TITLE
[NPC] Crot Headstomper - missing item list

### ISSUE THREAD

**Issue by Elueh** [WarEmu/WarBugs#6617]
Craft Supply Merchant item list is empty. 
Greenskin Chapter 18
SpawnId=543193,Entry=7492,Name=Crot Headstomper,Level=36
Greenskin chapter 17
SpawnId=538503,Entry=6640,Name=Gurgrok,Level= 35
Greenskin chapter 15
SpawnId=533415,Entry=1702,Name=Suggskull,Level=30

**Comment by Torquemadra** [comment]
fixed next patch, thanks
