### ISSUE TITLE
Chosen: mercenary set not the same stat in game & according to excel sheet

### ISSUE THREAD

**Issue by Roildr** [WarEmu/WarBugs#6619]
Hello,
the mercenary set (and maybe ruin/annihil) for chosen have not the same stats in game and according to the https://docs.google.com/spreadsheets/d/13C0SbnhRDmmD_6DaxgoeBuDhM8yLy2igWktFQ6DkdKo/edit#gid=1535980708
Github told me the sheet should be the template for the in game stat. So I reckon there is a problem

**Comment by Torquemadra** [comment]
Specifically where? one piece? all?

If you are claiming an error you need to show us exactly where it is, thank you.

**Comment by Roildr** [comment]
All pieces of mercenary.
For example: looking at the vendor, shoulder in game stats = 12 toughness 28 wounds 18 initiative 3% reduce chance to be parried. On the sheet = 26 strenght, 11 toughness, 13 initiative , 3% melee crit

**Comment by Torquemadra** [comment]
fixed next patch, specifics help to a huge degree

Thanks again.

**Comment by Roildr** [comment]
So what is correct, the in game stat or the sheet stat?
Thanks for considering Torquemadra, cheers :)

**Comment by Roildr** [comment]
Also, it is the same for the ruin set. I am wearing the ruin set and the bonuses are different from the sheet.
Example: helm ruin (sheet) = 28 str 11 willpower 12 wounds 14 init
helm ruin (in game) = 28 toughness 12 wounds 11 initiative 14 weapon skill

**Comment by Torquemadra** [comment]
sheet is the correct values though mistakes can happen, mercenary and ruin should be correct now.
