### ISSUE TITLE
Sent myself 8 gold, found empty mail.

### ISSUE THREAD

**Issue by Rilos** [WarEmu/WarBugs#6620]
This just happened today.  I sent my main from Tier 4 to Tier 1, but the gold wasn't in the mail.

**Comment by taccr** [comment]
Happens when you send the mail before logging in the new character at least once.

**Comment by Evildoor** [comment]
Yes, i would like to hear if that's the case.

**Comment by Rilos** [comment]
The character was already level 7.

**Comment by Luth-RoR** [comment]
Maybe related: https://github.com/WarEmu/WarBugs/issues/4780 ?
