### ISSUE TITLE
Blue 38 potions

### ISSUE THREAD

**Issue by roadkillrobin** [WarEmu/WarBugs#6623]
The blue potions doesn't seem to give out the right stats.

100 willpower one only gives 80 and 
825 armor only gives 660
They are even displayed as the 80 and 660 in the bufftracker.

![narfzon_021](https://cloud.githubusercontent.com/assets/16356956/15772027/06967392-296f-11e6-9284-47044edf4ad7.jpg)
![narfzon_022](https://cloud.githubusercontent.com/assets/16356956/15772028/069d518a-296f-11e6-8336-92f63697a137.jpg)
![narfzon_023](https://cloud.githubusercontent.com/assets/16356956/15772029/069f7a0a-296f-11e6-9d26-5bce4e46f008.jpg)

**Comment by Evildoor** [comment]
#5927
