### ISSUE TITLE
No commands are working.

### ISSUE THREAD

**Issue by Tuffelhunden** [WarEmu/WarBugs#6627]
I tried to respec my gathering skill using ".respec gathering" however it seemed to do nothing. I then tried to get the list of Game Masters by using ".gm" this also did not do anything. I did both of these commands as well as ".respec crafting" in both lower and upper case multiple times in the /say chat and nothing happened.

Most likely user error however I would love some help about this.

**Comment by Evildoor** [comment]
Individual problem => use support forums.
