### ISSUE TITLE
lair in t4 no work doors  but can enter for other zone

### ISSUE THREAD

**Issue by Magteridon** [WarEmu/WarBugs#6629]
![magteridon_060](https://cloud.githubusercontent.com/assets/16975012/15787580/73fac9d4-29c3-11e6-81bf-c72203eb5aab.jpg)
![magteridon_061](https://cloud.githubusercontent.com/assets/16975012/15787577/73f9c80e-29c3-11e6-8411-7f412642bcba.jpg)
![magteridon_062](https://cloud.githubusercontent.com/assets/16975012/15787579/73faaa26-29c3-11e6-841c-b5891156dada.jpg)
![magteridon_063](https://cloud.githubusercontent.com/assets/16975012/15787578/73faaff8-29c3-11e6-83cf-6d193db80322.jpg)
for enter other zone  and  not used normal entrance
![magteridon_058](https://cloud.githubusercontent.com/assets/16975012/15787594/86806898-29c3-11e6-9226-1d4a0ec02927.jpg)
![magteridon_059](https://cloud.githubusercontent.com/assets/16975012/15787593/867d0126-29c3-11e6-893c-8906a2ec674b.jpg)

**Comment by Magteridon** [comment]
fixed any parts of mountain but can  enter again . 
example
![normak_088](https://cloud.githubusercontent.com/assets/16975012/16018011/dfaff8fc-31a2-11e6-906b-366ccd513366.jpg)
![normak_089](https://cloud.githubusercontent.com/assets/16975012/16018012/dfb4e434-31a2-11e6-9b03-c9727f85f4a7.jpg)
![normak_090](https://cloud.githubusercontent.com/assets/16975012/16018016/dfc8b5b8-31a2-11e6-87c7-952d3f266f1c.jpg)
![normak_091](https://cloud.githubusercontent.com/assets/16975012/16018014/dfbd55f6-31a2-11e6-94f9-91e69ae20760.jpg)
![normak_092](https://cloud.githubusercontent.com/assets/16975012/16018015/dfc4679c-31a2-11e6-8e18-f2e7e83e4d60.jpg)
![normak_093](https://cloud.githubusercontent.com/assets/16975012/16018013/dfb769e8-31a2-11e6-8829-83cd73753175.jpg)

**Comment by Magteridon** [comment]
now no have  hero , its removed of lair

**Comment by Lheana** [comment]
Doors of the lair are now fixed. But you'll have to wait for its bosses.

**Comment by sioding** [comment]
Fixed with patch from 13.1.2018
