### ISSUE TITLE
West Praag destruction respawn point is set in a PQ area

### ISSUE THREAD

**Issue by Magteridon** [WarEmu/WarBugs#6630]
when die in this area you respawn here and there mobs only of public quest
![magteridon_064](https://cloud.githubusercontent.com/assets/16975012/15788733/3ba5940a-29c9-11e6-9429-eccb704a8dd8.jpg)
![magteridon_065](https://cloud.githubusercontent.com/assets/16975012/15788732/3ba4b918-29c9-11e6-8c47-b828616159e2.jpg)

**Comment by Kaelang** [comment]
There are now friendly NPC's surrounding this respawn location.

There is no alternative WC etc for a spawn to be set in Praag, so looks like NPC's here were implemented.

Closed.

**Comment by Lheana** [comment]
As a note, that's how it was on official, the respawn and "camp" in West Praag was there.
