### ISSUE TITLE
My guild that I created the Guild Leader has shifted to a person who has been offline for a very long time

### ISSUE THREAD

**Issue by Richardwarhawk** [WarEmu/WarBugs#6632]
Looking to get guild lead of my guild back on order called the Savvy, My toons name is Warhawkrichard a warrior preist.  Any way you can help me with that again? I just got my account back after around 5 to 6 months.

**Comment by Evildoor** [comment]
Uh, so you are telling me that your problem is:
1) You was offline for a long period of time.
2) Someone else logged in, leadership was transferred to them.
3) Now you are back, but this someone else is offline, so you want your leadership back?
is that correct?

**Comment by Richardwarhawk** [comment]
Yes, that is correct.  Sorry was very late when I made that report

**Comment by Evildoor** [comment]
1) Bugtracker does not deals with individual problems.
2) I don't see any problem here. That someone is offline, wait some time and leadership will be changed to someone else who is online. If that does not happens after current leader being offline for a time interval which triggers the change (a month, IIRC) then you should ask help on support forums.

**Comment by Elvenalthur** [comment]
As Evildoor has already stated, it's an individual problem and doesn't belong on the bugtracker (nor is it a bug).

However, if you contact myself (Elven) or another GM with details of the guild (with proof) and who should be the leader of the guild, we can pass leadership to that character.
