### ISSUE TITLE
White Lion- Your Pet Cannot See That Target

### ISSUE THREAD

**Issue by Liandel** [WarEmu/WarBugs#6634]
Recently, the War Lion for the WL class has been having an issue where if the target is LOS to the pet, or you are LOS to the pet, it randomly says "Your pet cannot see that target" in the chatbox, and the pet is completely unresponsive. This happens especially in caves and tight corridors such as gates of Ekrund.

**Comment by ozarmidrashim** [comment]
Check removed pro tem.
