### ISSUE TITLE
lost  order city in t4 in death peak

### ISSUE THREAD

**Issue by Magteridon** [WarEmu/WarBugs#6635]
no have mobs and have  cave great
![magteridon_067](https://cloud.githubusercontent.com/assets/16975012/15800073/48606e34-2a70-11e6-9bf4-a37dbaabcb09.jpg)
![magteridon_068](https://cloud.githubusercontent.com/assets/16975012/15800072/48600ff2-2a70-11e6-85ba-805bef692964.jpg)
![magteridon_069](https://cloud.githubusercontent.com/assets/16975012/15800075/48620e42-2a70-11e6-9c4a-419617729000.jpg)
![magteridon_070](https://cloud.githubusercontent.com/assets/16975012/15800076/48628282-2a70-11e6-89f3-957b82c30a28.jpg)
![magteridon_071](https://cloud.githubusercontent.com/assets/16975012/15800074/48622bc0-2a70-11e6-9570-1171840124b8.jpg)

**Comment by Torquemadra** [comment]
unused area, shouldnt be accesable
