### ISSUE TITLE
destru lost city in death peak too

### ISSUE THREAD

**Issue by Magteridon** [WarEmu/WarBugs#6636]
![magteridon_074](https://cloud.githubusercontent.com/assets/16975012/15800158/8229d798-2a72-11e6-8e66-c4f2e874d17b.jpg)
![magteridon_075](https://cloud.githubusercontent.com/assets/16975012/15800159/822b5dd4-2a72-11e6-9933-41e11db49c03.jpg)
![magteridon_076](https://cloud.githubusercontent.com/assets/16975012/15800161/822eb060-2a72-11e6-8692-dfccf3fef208.jpg)
![magteridon_077](https://cloud.githubusercontent.com/assets/16975012/15800160/822be47a-2a72-11e6-905b-8935a108cebc.jpg)
no have mobs or npc`s no have nothing this map

**Comment by Torquemadra** [comment]
Because its an used area that shouldnt be accessable now
