### ISSUE TITLE
Scenario queue not cancelled by relog

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#6638]
You can queue for a scenario, get bored, relog to a different character, queue again and receive pop for your old character (even in different tier) which you cannot accept.

**Comment by Tyramissoux** [comment]
Still a thing. 
Was queued on order toon,waiting time for SC was too long and logged out, ofc without leaving the queue. 
Logged into destro char and queued (button didn't show any active queueing). Got a pop after a few minutes, pressed join and nothing happened. Tried to requeue and it told me that I'm already queued for all SCs (except Stonetroll Crossing - left q for that one on both toons).
Could only queue for Stonetroll Crossing. After the minute, I got a quitter on destro-side. 

Please check this as it might also cause the population imbalance problems.

**Comment by Kaelang** [comment]
Looks like the check has changed to remove queue on log-off. Just tested and seems to be working now. Please re-open if issue persists.
