### ISSUE TITLE
Oil still usable after keep lock

### ISSUE THREAD

**Issue by Blubberino** [WarEmu/WarBugs#6639]
It is possible to use the oil after a keep got locked. So basially you can gank the keep owners from their own keep with the oil. We tested it with deploying the oil right before keep switch but probabbly you can deploy it also after the claim.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
