### ISSUE TITLE
Quest: Empire Ch 19: Daemon Hunter 

### ISSUE THREAD

**Issue by iljuro** [WarEmu/WarBugs#6641]
Battle Wizard Krishtof gives out two Daemon Hunter Quests and one of them is bugged

![war-krishtof](https://cloud.githubusercontent.com/assets/18705881/15801360/9889e332-2a92-11e6-920f-c26378bf48a1.jpg)

**Comment by sioding** [comment]
fixed with patch from 05.11.2018
