### ISSUE TITLE
Eagle Claw Crewman : NPC High Elf Chapter 1 + The Eagle's Claw quest

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#6643]
He keeps getting chain-killed by a lvl 6 Harpy next to him, could the mob be removed or the NPC moved a few metres?

By the way, we're supposed to use the Eagle Claw siege weapon to kill the lvl 6 harpy, would it be possible to debug it or at least place a regular siege weapon as a fix?

**Comment by Evildoor** [comment]
Eagle's Claw has its own report: #5007.

**Comment by saupreusse** [comment]
as long as the siege weapons cant be used on npc there is no way to fix it...at least the eagle claw crewman isnt instakilled anymore.
