### ISSUE TITLE
Rockbridge stuck

### ISSUE THREAD

**Issue by Blubberino** [WarEmu/WarBugs#6644]
Can you guys (when you have some spare time) add an extra rock to prevent getting stuck here?

![laranaxas_044](https://cloud.githubusercontent.com/assets/16993024/15801535/689ba5ce-2a98-11e6-905f-511c0333aeee.jpg)

18200,31500

**Comment by saupreusse** [comment]
If it is not an urgent thing (like getting into a keep) i would rather leave it as it is until we can place Nifs AkA client control.

**Comment by Luth-RoR** [comment]
K, closed then until client modification is possible.
