### ISSUE TITLE
Weird lvl 40 Hero mobs at PQ.

### ISSUE THREAD

**Issue by tutti13** [WarEmu/WarBugs#6645]
In caledor, at the PQ "The Might of Ulthuan", there is a bunch of bodyless lvl 39 and 40 hero mobs with orange aggro level (one "Encounter Manager" and several "Encounter Slave")
Like 6 or 7 of them. 
Is this intentional?
![dwaini_028](https://cloud.githubusercontent.com/assets/11341460/15801608/f3599908-2a9a-11e6-9c3e-8cca888f49de.jpg)

**Comment by grunbag** [comment]
Fixed in next patch
