### ISSUE TITLE
(Trivial) NPC Hoarfrost

### ISSUE THREAD

**Issue by Topologic** [WarEmu/WarBugs#6649]
The NPC Hoarfrost (level 40 champion located near 51k, 6k in Kadrin Valley) is considered by the game to be a Yhetee, despite having the appearance of some type of bird.

At the very least, I received the ToK unlock for having encountered a Yhetee upon killing it.

**Comment by saupreusse** [comment]
Hoarfrost is supposed to be one of the Sacellum Heros. removed the spawn and corrected his Model ID and made him a hero.
