### ISSUE TITLE
Unsual crit damage with BW

### ISSUE THREAD

**Issue by Mizhas** [WarEmu/WarBugs#6651]
Hi, i want to report an issue with crit damage multipliers. This morning i logged on my BW and did some ruin PQ farming when i started to get some messages about crit damage multipliers. When i looked the damage i saw that i was doing 52k crit hits with any skill. 

![staqarde_002](https://cloud.githubusercontent.com/assets/19757491/15804015/b9c50ce0-2af9-11e6-83fe-d3fb14439167.jpg)
![staqarde_003](https://cloud.githubusercontent.com/assets/19757491/15804016/bfc4b744-2af9-11e6-97fe-841df8456b51.jpg)
![staqarde_004](https://cloud.githubusercontent.com/assets/19757491/15804017/bfeabcb4-2af9-11e6-879b-a429893d3c2a.jpg)

**Comment by Evildoor** [comment]
#5319 may be related.

**Comment by ozarmidrashim** [comment]
Was fixed.
