### ISSUE TITLE
Chaos Wastes: NPC: Gambit Controller

### ISSUE THREAD

**Issue by iljuro** [WarEmu/WarBugs#6653]
I'm not sure, but I think this guy is involved in the Desperate Gambit Quest.
Unfortunatly he's in the ground. Only his name shows.

He's in the inner east corner of the Lost Artifacts castle at abt 29, 55
Brave lv1 chap though, he did help me fight a lv39 skeleton.

![war-gambit](https://cloud.githubusercontent.com/assets/18705881/15804748/bcfe5096-2b13-11e6-98c1-0fcce4d41d00.jpg)

**Comment by saupreusse** [comment]
No idea what these controller mobs are good for. kicked him out for now, but will ask around if anybody knows.

**Comment by Luth-RoR** [comment]
Iirc this type of "NPCs/worldobjects" have been created by DB scripts automatically based on data from the mythic server.
Maybe they were used on the WAR server as part of a scripted event when a certain condition is met.
