### ISSUE TITLE
gutslimes bitz

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#6654]
the gutslime weapons have the wrong stats, they used to have 3/6% crit chance depending on 1h or 2h
http://postimg.org/image/suy62rxdn/

**Comment by Evildoor** [comment]
Proof.

**Comment by Lileldys** [comment]
They got nerfed due to them being too easy to obtain, and BiS for all casters

**Comment by Vayra** [comment]
Proof should be in patch notes from a few months back when it was nerfed due to how easy it was to farm since lair bosses don't have their proper abilities yet.

**Comment by Evildoor** [comment]
"they'll stay nerfed until gutslime is fixed to do an appropriate amount of dmg and has a range of abilities that'll make it fair to get a 3-6% crit weapon for" (c) DB team

**Comment by Soulwhisper** [comment]
@Luth-RoR This one fixed today.
Torquemadra

Lair of Nerx Gutslime rebuilt +3/6 critical weapons in place as drops.

**Comment by Luth-RoR** [comment]
Thanks, i only searched for "nerx".
