### ISSUE TITLE
Badmoon Hole Keep at Black Crag is not inside RVR area

### ISSUE THREAD

**Issue by zibiman** [WarEmu/WarBugs#6657]
i dont get rvr flagged at the keep because its outside RVR area
![lalulila_001](https://cloud.githubusercontent.com/assets/16434526/15805317/93d7d97c-2b26-11e6-9361-7e434768d9aa.jpg)

**Comment by saupreusse** [comment]
I made a bandaid for this - but since the keep is inside a cave its not really adequate because now the pve areas that lie above it will flag people for rvr. But i guess its more important that the keep lies within the lakes until we can find a better solution.
