### ISSUE TITLE
Black orc wrong starter sheild

### ISSUE THREAD

**Issue by JamGrif** [WarEmu/WarBugs#6658]
The black orc starter shield has the wrong appearance from live. There are alot of videos on youtube which show a different shield then the one we have. ![qeqeqeqeq](https://cloud.githubusercontent.com/assets/16886300/15805349/540d103e-2b1f-11e6-8a42-c35787751ba1.JPG)
th a spike

**Comment by Evildoor** [comment]
Yes, i remember that shield. However, it was changed later.

**Comment by JamGrif** [comment]
why?

**Comment by Evildoor** [comment]
No idea.

**Comment by JamGrif** [comment]
Why cant it be changed back? The old appearance is no where in the game now and the current starter shield has the same appearance as t2 influence rewards? :/

**Comment by Evildoor** [comment]
Bugtracker deals with bugs, not with requests and feature suggestions. There is a thread or several on forums about desired appearance items, use them.
