### ISSUE TITLE
Flying out of the Sc Zone 

### ISSUE THREAD

**Issue by Sullfrax** [WarEmu/WarBugs#666]
I encountered a bug when some Career uses a push ability I felt trough the map and landed behind a the barricade with no way in. I didn't pay attention what Career use the ability on me, so I cant say what abilitiy causes the bug.
![92bf771af6d6be5b313b6f158358b98a](https://cloud.githubusercontent.com/assets/11579455/6762302/c9c9d7ea-cf5d-11e4-922a-1ca240d3d28e.jpg)

**Comment by ozarmidrashim** [comment]
To update you on this:

Found out that a few of the values in the knockback packet are wrong, resulting in super punts. Hopefully fixing that issue will also solve the teleportation issue.

**Comment by ozarmidrashim** [comment]
Need to calculate pin coordinates and convert them to world to solve this one, I think

**Comment by ozarmidrashim** [comment]
Let's see whether this works next patch.

**Comment by ozarmidrashim** [comment]
Fixed in next patch.
