### ISSUE TITLE
[Magus] [Tactic] Wild Changing

### ISSUE THREAD

**Issue by andytomlins** [WarEmu/WarBugs#6661]
Magus tactic Wild Changing that increases the critical chance of all path of changing abilities doesn't seem to increase it for all. Only Rend Winds.
![galataya_008](https://cloud.githubusercontent.com/assets/6351625/15805939/b8ec1486-2b2f-11e6-81d1-53eea0211f83.jpg)
![galataya_009](https://cloud.githubusercontent.com/assets/6351625/15805940/b8f25742-2b2f-11e6-85a9-5d1100377dcd.jpg)

**Comment by andytomlins** [comment]
After some more testing it seems to be dots and channel that are using the crit tactic
![galataya_015](https://cloud.githubusercontent.com/assets/6351625/15806459/b4ddd198-2b3b-11e6-8778-85f877e6d55b.jpg)

**Comment by ozarmidrashim** [comment]
Was fixed in recent patch
