### ISSUE TITLE
Bright Wizard : some spells amount of damage is bugged

### ISSUE THREAD

**Issue by shamallow** [WarEmu/WarBugs#6665]
i'm not sure about the english name of these abilities (one is annihilate i guess)

![meijix1](https://cloud.githubusercontent.com/assets/16374367/15806129/12d89188-2b3d-11e6-8bbd-b3c5b086003d.jpg)
![meijix2](https://cloud.githubusercontent.com/assets/16374367/15806128/12d29a80-2b3d-11e6-8018-a063748b2329.jpg)

**Comment by Evildoor** [comment]
#6651
