### ISSUE TITLE
Quest HE Chapter 3 : Among the Shadows

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#6667]
There are no 'Uthorin Chest' to find, but there is a clickable 'Ley Line Map' on a chest though. Clicking it doesn't do anything, and can only be done once as it then becomes un-clickable.

Relogging didn't change that.

**Comment by Ryanfawkez** [comment]
Objective is the Ley Line Map: GO interaction triggers a quest item loot which you'll have to get to complete the quest now.
