### ISSUE TITLE
Empire prologue and ch 1

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#6668]
This is a group of small issues, I didn't want to create every Issue for each problem.

GRIFFON RECRUITER quest:
- quest text says {career} in the beginning,
- no orange indicator over Samuel Twitty - guy we need to talk to,
- weird reward - Initiate's Warming Drought - does nothing.

INTO THE FIRE quest:
- quest person (priest) should have orange indicator

TRAINING COURSE quest:
- Elsa Schmidt should have orange indicator, not Victor Riese
- weird reward, boots 25 armor and KotBS class boots 12 armor.

NO indicators on any of the Rally Masters in the world.

WOEBEGONE quest:
- Orgni Stouthammer should have orange quest indicator

OF HONOR AND GLORY quest:
- Stephan Bossy doesn't have orange quest indicator

SILENCING THE CANNONS quest:
- put 2-3 more cannons to kill

SILENCING THE CANNONS quest:
- quest has the same name but requires to kill hellmagus', hellfangs and hellservants and has same rewards. Please put mobs closer to the cannons, From cannon point of view they are too far away.

CHAPTER 1 Influence bar error - not shown.

Regards,
StaH84

**Comment by Evildoor** [comment]
> I didn't want to create every Issue for each problem

That's too bad, because that's exactly what i'll ask you to do. Also, use search before posting, some of these were already reported.

**Comment by StaH84** [comment]
Ok no problem, I thought it will make Your work easier this way. I will search and not copy the existing reports then. You may delete this one.
