### ISSUE TITLE
[Magus] [Tactic] Chaos Unleashed

### ISSUE THREAD

**Issue by andytomlins** [WarEmu/WarBugs#6669]
Tactic Chaos Unleashed is meant to increase crit chance of all path of havoc abilities. Only affects direct damage abilities.
![galataya_016](https://cloud.githubusercontent.com/assets/6351625/15807035/4720b698-2b4a-11e6-9762-db96fbd34452.jpg)

**Comment by ozarmidrashim** [comment]
Was fixed in recent patch
