### ISSUE TITLE
GRIFFON RECRUITER quest:

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#6670]
Issues
- quest text says {career} in the beginning,
- ~~no orange indicator over Samuel Twitty - guy we need to talk to,~~
- weird reward - Initiate's Warming Drought - does nothing.

Edited by Evildoor: second issue is not a bug per comments below.

**Comment by Evildoor** [comment]
> no orange indicator over Samuel Twitty - guy we need to talk to,

I'm not sure if this is wrong. One thing is completing the quest and then handling it to a NPC - indicator should be shown. But this is another category of quests which require you to talk to a NPC first.

**Comment by StaH84** [comment]
If in quests, that point You to talk to NPC first, NPCs don't need indicator over their head, just to find them, I won't report this anymore as a bug.

**Comment by Evildoor** [comment]
Yes, i believe that it's not a bug.

@DB team - what should we do about {career} and other stuff like that? We have a separate report for that, i'll fetch it if needed, but the question is - is this a general issue, or should that ticket be closed and each individual case reported separately, like here?

**Comment by Ryanfawkez** [comment]
@evildoor, <career> and <name> should have no issue working in the general quest description. If it's in { } though, it won't work as it's supposed to be done by using < >.

Fixed the quest reward, it's now a healing potion.

**Comment by Ryanfawkez** [comment]
Also fixed the entire starting quest chain for Nordland now.
