### ISSUE TITLE
WOEBEGONE quest

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#6674]
Issues:
- Orgni Stouthammer should have orange quest indicator in first phase
- no map indicator where to retuen
- not working potion as a reward

**Comment by Evildoor** [comment]
Potion name.

**Comment by StaH84** [comment]
Will take some time, I have to do quest again. Or is it possible to check it the other way?

**Comment by Evildoor** [comment]
I don't see any.

**Comment by Ryanfawkez** [comment]
Quest markers are all fine, orange quest marker pops up as soon as you speak to Orgni, reward Initiate's Potion of Clout has no database reference for ability so cannot be fixed.

I suggest reading the quest description and backpedaling accordingly if you're having issues finding the correct hand-in NPC.

**Comment by StaH84** [comment]
I've done this quest several times. I always read description and find correct NPC - good not click and go leveling. Just pointing this out because some other quests i.e. Emperor's Mandate mark the NPC on map to turn in the quest after i.e. killing Bashida the corrupter.
