### ISSUE TITLE
Error /device/Hdd2/DR2 not exist

### ISSUE THREAD

**Issue by notre4ror** [WarEmu/WarBugs#6677]
I have this error login-out o closing the game since lasts patches, never got before.
If not this message, i got the Runtime c++ error. 

The point is, since two/three last patches the client crashes with one of these errors and i never have this problems before.

**Comment by wargrimnir** [comment]
Your hard drive is dying, that's not us. Kindly close this ticket please.

**Comment by noisestorm** [comment]
Ask google on what the exact problem is. Nothing to do with the game/launcher.
