### ISSUE TITLE
EMPIRE Chapter 1 Influence rewards

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#6678]
Issue:
- First stage influence reward - only healing potion works, rest do not.

**Comment by Evildoor** [comment]
Other potions names.

**Comment by StaH84** [comment]
Working potion:
- Initiate's Draught of Allaying
Not working:
- Initiate's Lasting Screening Potion
- Initiate's Warming Draught
- Lasting Initiate's Lasting Elixir of Allaying

**Comment by NorKalli** [comment]
all items work
