### ISSUE TITLE
Knight - Ruin Boots

### ISSUE THREAD

**Issue by mursie** [WarEmu/WarBugs#6679]
Could you please review this armor piece for stats.  It currently has willpower on it.

Could this please be reviewed and changed to a core stat the knight typically has on all other gear:  wounds/initiative/toughness/strength/weaponskill

**Comment by Evildoor** [comment]
AFAIK, Ruin set was not touched at all, so it's not only knight boots which have to be reviewed.

**Comment by wargrimnir** [comment]
Fixed recently.
