### ISSUE TITLE
Problem with Tier 4 Public Quests.

### ISSUE THREAD

**Issue by Rilos** [WarEmu/WarBugs#6680]
I started grinding public quests in Tier 4 level 31-33 in Eataine, but it never fills up my influence bar.  

I was also not being included in the roll at the completion, which I thought it was my level (being level 31) but at 32 I wasn't even receiving the roll UI or the ability to pick up a bag at the end. 

This did not change after logging out and logging back in.  My character is a level 32 Warrior Priest and the chests were rolled for in a warband. The influence was tested solo and in a warband.

**Comment by Evildoor** [comment]
And other lvl 31-32 characters have no such problems?

**Comment by Rilos** [comment]
I logged in after this post and the influence bar started to move finally.  I haven't checked PQ chest rolls, but I'll be doing that today.

**Comment by Rilos** [comment]
The chest rolls work, but the influence UI seems to show no Influence gained at all.

**Comment by Rilos** [comment]
Logged in on another computer that doesn't have addons.  Dawerks Cleva shows no moving influence bar.

**Comment by Evildoor** [comment]
I doubt that computer has anything to do with this. It's more of interest if this is or is not restricted to your WP.

**Comment by Noergl** [comment]
I recognised similar issues. At level 31 i didnt see any loot tables and couldnt click the loot box either. Meanwhile at level 32 i still dont see anything, but today ( 9th of June) the PQ doesnt seem to work at all. Been there three times, Endboss hero doesnt show up, everyone left. I didnt have those issues with other higher level chars a few days before.

**Comment by Aehnur** [comment]
I have the same problem with my lvl 31 BW. Actually, i don't even see the whole pq ui. However i sometimes do see the countdown before its restart. I tried disabling all add-ons and reloading the base ui, but it did not change a thing. It worked fine on my lvl 40 SM while runing add-ons.
