### ISSUE TITLE
Glitched name wireframe dog in Altdorf.

### ISSUE THREAD

**Issue by deeldoze** [WarEmu/WarBugs#6683]
Not really a high priority, but a wireframe dog with a completely glitched out name just spawned in Altdorf at 25.8k, 34.4k. The blue text above is in fact the nameplate.
![bootus_007](https://cloud.githubusercontent.com/assets/19521607/15815896/772f9264-2b95-11e6-98bb-1113614cfeb6.jpg)

**Comment by MaxHayman** [comment]
I assume this was fixes as I haven't seen this.
