### ISSUE TITLE
High Elf Chapter 1 quests

### ISSUE THREAD

**Issue by Zomgmeister** [WarEmu/WarBugs#6684]
Just a report, nothing really important, some polishing issues.

The Eagle's Claw: Kill Harpies. Two harpies spawn near quest giver, one of lvl 2, which is appropriate, while another is of lvl 6, which is unsoloable. Sure, can be done with the help of npc guards, but meh. Also this nice harpy tend to kill quest giver from time to time.
There are other harpies of good level further south, who are named Arkaneth Harpies, but their killing does not fulfill quest requirement - and there is a quest later to kill these anyway. No other harpies seem to be in vicinity of the quest.

Prince Eldrionn is not marked as a quest finisher or as a quest giver later. Still works anyway.

Shadow Vantage quest seems to be completed (orange marker) right after taking. Still need to be completed really to be turned.

Reluctant Hand: Find Azure-rock. It is possible to pick one instance of the rock six times in a row, it does not despawns after picking, just moves z-higher.

Everything else seems to be working as intended (including that keg, heh), thank you!

**Comment by Ryanfawkez** [comment]
Harpy levels fixed to 2.

Fixed Prince Eldrion's quest line.

Can't fix this orange marker, it's a UI packet issue.

Azure-rock made get item on interaction with GO. Should require multiple GO lootings now.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by Evildoor** [comment]
Ryan already fixed these, but next time, like i said in other report - one report per problem and use search before posting.

**Comment by avenflar** [comment]
Just pointing out that the Harpies are lvl 6 because you are supposed to kill them with the Eagle Claw.

**Comment by Zomgmeister** [comment]
> Harpies are lvl 6 because you are supposed to kill them with the Eagle Claw

Yeah, but there are two harpies right at the questgiver and the eagle claw, one lvl 2 and another is lvl 6. Which kills the questgiver and other npc nearby. Probably its' placement is wrong, shouldn't be up there, belongs down at the target practice.
