### ISSUE TITLE
ToK: Chaos Lands: The Inevitable City

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#6685]
The tome entry on the ToK Introduction page for the Inevitable City does not go away after clicking it. The entry itself seems bugged too.

![01](https://cloud.githubusercontent.com/assets/11018815/15819442/739889aa-2be3-11e6-8ab3-db7056f84eaa.png)
![02](https://cloud.githubusercontent.com/assets/11018815/15819445/758cff0c-2be3-11e6-86ac-5181ac917393.png)

**Comment by Evildoor** [comment]
Same with Altdorf. However, IIRC, it was the same on live and looks client related, so i'm not sure if we can do anything about this...

**Comment by Lheana** [comment]
#5525

**Comment by Lheana** [comment]
Fixed

**Comment by Coldgrin** [comment]
This issues is back, same exact problem 8/31/18
