### ISSUE TITLE
Empire Chapter 1 quests

### ISSUE THREAD

**Issue by Zomgmeister** [WarEmu/WarBugs#6687]
New Recruits: Samuel Twitty isn't marked as a quest target in game. Not a problem in this instance, but can be bothersome for similar quest where it is required to find someone not standing in three steps away.

Grimmenhagen Burning: One door may be clicked three times to complete three supposedly different door clicking.

Horrors of War: same as above, one cowering militiaman is enough.

Don't know about other classes, but lots of quest reward Bright Wizard with crappy belts and only belts, at least two of them even share name.

Everything else works, including public quest, which is really great.

**Comment by Evildoor** [comment]
1) One report per problem.
2) Please, use search.
3) Samuel Twitty: #6670.
4) Doors: #424.
5) Militiamen: same.
6) Belts just being crappy are not the problem. If two different quests reward the same belt, then we need their names and belt name.

**Comment by Ryanfawkez** [comment]
It has been requested before if we could change certain start rewards to be more than just belts, gloves and boots. We'd rather not do this at the present time as the priority lies with fixing the quests and rewards to how they were on live, before we decide to make any alterations.

**Comment by Luth-RoR** [comment]
No bugs/feature requests -> closed.
