### ISSUE TITLE
Troll Country Quest Don't Appear

### ISSUE THREAD

**Issue by Alfinnete** [WarEmu/WarBugs#6688]
Hello.

I'm playng with my Iron Breaker and I'm at level 25 and the quest 60+k xp not appear to start in Troll Cou-ntry.

**Comment by Evildoor** [comment]
60k xp quests were not implemented, and i doubt if they ever will.

**Comment by Alfinnete** [comment]
I've done some parts with mI've done some parts with my WP and my friends are also doing.y WP and my friends are also doing.

**Comment by Alfinnete** [comment]
I've done some parts with my WP and my friends are also doing.

**Comment by Evildoor** [comment]
Screenshot of the quest page in the ToK, please.

**Comment by Evildoor** [comment]
No response, closing.
