### ISSUE TITLE
Tome of Knowledge Wrong bestiary unlock

### ISSUE THREAD

**Issue by TehSpike** [WarEmu/WarBugs#6689]
I've unlocked bestiary lock for snotlings by killing dwarf guard (slayer) of BO in Tier 1 Dwarf vs Greenskin zone.
![rubakha_000](https://cloud.githubusercontent.com/assets/19779640/15825211/a537dc7c-2c24-11e6-86fe-aa517231324e.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
