### ISSUE TITLE
NPC name: Ecgalf the Crusader. Duplicated Named quest mobs in Chaos Ch 21

### ISSUE THREAD

**Issue by TehSpike** [WarEmu/WarBugs#6690]
I've detected 2 totally same named NPCs (for the one quest) in one place in Chaos Ch 21 (sigh... don't save quest name).
![tremma_031](https://cloud.githubusercontent.com/assets/19779640/15825383/4ec94da2-2c25-11e6-96aa-978b4f63cda2.jpg)
![tremma_032](https://cloud.githubusercontent.com/assets/19779640/15825392/5b5049f4-2c25-11e6-8224-6b8cef524946.jpg)

**Comment by Evildoor** [comment]
NPC name: Ecgalf the Crusader.
Important details, such as this, should be written in the report name or body. Human can look at screenshots, but search engine can't.

**Comment by saupreusse** [comment]
fixed in next patch.
