### ISSUE TITLE
Missed Acc Unlock of Tome of Knowledge

### ISSUE THREAD

**Issue by TehSpike** [WarEmu/WarBugs#6691]
There is Accessory Unlock of Tome of Knowledge "From Mouth to Neck" in Saphery.
Beastmaster Mezellian shouldgive pkayer a necklace. And when player has 10 Chaos Hound fangs and necklace in inventory and are talking with Mezellian, he (player) get unlock.
But the problem is Mezellian don't give necklace to player, even if he has those 10 fangs.
![tremma_035](https://cloud.githubusercontent.com/assets/19779640/15825567/14a3460e-2c26-11e6-9040-84cd33a6367e.jpg)

**Comment by Evildoor** [comment]
#4622
