### ISSUE TITLE
Missed Acc Unlock of Tome of Knowledge 2

### ISSUE THREAD

**Issue by TehSpike** [WarEmu/WarBugs#6692]
There is accessory unlock of Tome of Knowledge "Sacking for Sacs" in Thunderous Mountains.
Player need 5 Arachnid Poison Sacs to get it.
But there is no unlock even if player has those sacs.
![tremma_036](https://cloud.githubusercontent.com/assets/19779640/15825646/6ff5baa0-2c26-11e6-8f07-d24b1334bead.jpg)

**Comment by Evildoor** [comment]
#5781
Please, use search before posting.
