### ISSUE TITLE
Missed Quest Update Greenskin Ch 16

### ISSUE THREAD

**Issue by TehSpike** [WarEmu/WarBugs#6693]
There is quest "Squig Shakes" in Greenskin's Ch 16.
Player need  to kill squig and put it into empty barrel. The first step is going well, but last step seems to be undoable: there are enough empty barrels but I coudn't get that up. And there is no barrel item in my inventory.

![tremma_037](https://cloud.githubusercontent.com/assets/19779640/15825773/df0ecba2-2c26-11e6-85b3-46db03b01e84.jpg)

![tremma_041](https://cloud.githubusercontent.com/assets/19779640/15825823/09b0c3b0-2c27-11e6-919e-cc4d4e0cb39f.jpg)

![tremma_042](https://cloud.githubusercontent.com/assets/19779640/15825803/fa286fe2-2c26-11e6-9367-eadd05af468e.jpg)

**Comment by saupreusse** [comment]
fixed in next patch. you can now loot the empty barrels and they will drop a barrel item. the quest step will be completed once the item is in your inventory.
