### ISSUE TITLE
Hate generation is freezing for BlackGuard

### ISSUE THREAD

**Issue by Qwack** [WarEmu/WarBugs#6695]
We have tested this across several players.  Hate generation freezes up and will not move upward under any circumstance.  This happens both in RvR lakes and in simple PvE.  There is no specific number it freezes on.  I can't determine a pattern or trigger event for it yet.  It is extremely deabilitating to have Hate freeze on a low number.  It is not merely the number display itself freezing in the resource window, but the actual effect too.  /Reload does fix it but its not wise to keep hitting /reload in a fight.  It will unfreeze once the timer kicks in on reducing Hate.

**Comment by Evildoor** [comment]
#966
