### ISSUE TITLE
[Item] Missing stats on Order T4 RvR Influence Helm

### ISSUE THREAD

**Issue by Styrkarr** [WarEmu/WarBugs#6697]
Missing a lot of % crit on the Order RvR T4 Influence Helm "of the fist".

**Comment by Evildoor** [comment]
Uh, #6681?

**Comment by Styrkarr** [comment]
@Evildoor seems Ryan already fixed the destro one so i'm going to edit that bugtrack for the order helms.

**Comment by Ryanfawkez** [comment]
I fixed it for Order too.

**Comment by Evildoor** [comment]
Ok, then i can close this.
