### ISSUE TITLE
"Eye of Change" world object cannot interact with

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#67]
The big eye in the middle of chap1 pq  cannot be interact, ti should grante something in tome of knowledge
![eye of change nienet interazione](https://cloud.githubusercontent.com/assets/7527415/2920931/e6213b6e-d6ec-11e3-8432-5e764827c2b3.jpg)

**Comment by Nlghtbringer** [comment]
Any feedback on this?
Since it looks like a problem.

**Comment by Milkyn** [comment]
By clicking this object you will receive xp and and entry in your quest book.
