### ISSUE TITLE
Missing Stats on T2 Dwarf pvp reward Wh hunter

### ISSUE THREAD

**Issue by Internetbaron** [WarEmu/WarBugs#6700]
Hello,
there is a missing stats on the T2 Dwarf pvp reward Wh hunter hat.
The Epic one, its the second quest reward.

One of the epic hat has only 2 stats
Strengeth 8
Weapon Skill 9

the other has 3
Weapon Skill 8
Strengeth 11
Initiative 8

**Comment by Evildoor** [comment]
Hat names.

**Comment by Internetbaron** [comment]
Fangbreaker Hat
Strengeth 8
Weapon Skill 9

**Comment by saupreusse** [comment]
Corrected stats for Fangbreaker Hat and Alcadizaar's Hat.
