### ISSUE TITLE
Missing Talismanslot Elf t2 PvP reward WH shoulders

### ISSUE THREAD

**Issue by Internetbaron** [WarEmu/WarBugs#6701]
hey,

topic says it. Its about the Epic Shoulders.

One Shoulder with 27 Wounds and Talisman slot

the other with
Strengeth 13 and Weapon Skill  15
no talisman slot

**Comment by Evildoor** [comment]
Shoulder names.

**Comment by Internetbaron** [comment]
Item Level 18       "Bandolier of Thunder"
Strengeth 13 and Weapon Skill 15
no talisman slot


the correct ones name is "Spite's Bandolier"     Item Level 18
27 Wounds and Talisman slot

**Comment by saupreusse** [comment]
added missing talisman slot to bandolier of thunder
