### ISSUE TITLE
Mid-cast range check on stationary casts.

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#6703]
As of last patch if target moves even 1 foot out of range before the mid-cast range checks all stationary cast abilities will fail due to out of range. The grace distance appears to have been completely removed. This is different from how it was implemented just last week, how it was on live, and how it should be according to Aza in [this post](https://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=14164&start=30#p155018).

**Comment by ozarmidrashim** [comment]
You misunderstood. RoR performs two checks:

- Start cast
- Mid-cast (60%)

There is no end-cast range check. That's the grace. Both the start cast and mid cast checks are strict.

**Comment by Vayra** [comment]
Really? Cause I've noticed a massive increase in abilities being stopped by Out of Range since the June 4th patch. Before that patch I can't even remember seeing Gloomburst (1s cast) ever being interrupted by range, since then I've had it happen about a dozen times when fighting at the same range I normally do. My 3s casts as well are getting Out of Range waaay more than before that patch. So I'm pretty sure something changed in the way those checks are handled for stationary casts.

**Comment by Luth-RoR** [comment]
Confirmed to work as intended by developer. Please post any evidence for the issue (short video).
