### ISSUE TITLE
Key bindings/Hot keys stop working

### ISSUE THREAD

**Issue by grumbagz** [WarEmu/WarBugs#6704]
Randomly Ill log in and no special hotkeys will work. Anything bound to 1 through = or on the numpad always works but any binding such as a letter or mouse button such as mouse 4 will not. I'm using a logitech g510 keyboard and logitech g600 mouse so maybe the logitech software is whats messing up? Let me know if you need more information.

Thanks,
Grumbagz

**Comment by Evildoor** [comment]
This is a problem on your side, bug tracker deals with server problems.
