### ISSUE TITLE
"Bloodhorn Beckons" Quest Objective Text Issue

### ISSUE THREAD

**Issue by Topologic** [WarEmu/WarBugs#6705]
See the attached screenshot; the text next to the checkbox for the quest objective makes no sense.

![yomiel_004](https://cloud.githubusercontent.com/assets/13059408/15846255/44c391e0-2c49-11e6-9203-2750cd4d6b07.jpg)

**Comment by saupreusse** [comment]
seems to be already fixed. should be live next patch.
