### ISSUE TITLE
Issue To Load Addons

### ISSUE THREAD

**Issue by ThunderMjolnir** [WarEmu/WarBugs#6715]
I can't loading those addons including Buff Head (Failed), Crusher (Loaded(!)), PotionBar (Failed), Pure (Failed), Pure Templates (Failed), TargetRing (Failed). It happened after I deleted YakUI while game was opened as far as I remembering. But I re-download game but still I have this problem.

**Comment by taccr** [comment]
Not an emulator bug. Consult the forums.

**Comment by Evildoor** [comment]
#6706

**Comment by ThunderMjolnir** [comment]
Oh I thought it belongs to here because here is bug relevant place.
