### ISSUE TITLE
[Engineer] Work Gloves of Ruin - No dodge

### ISSUE THREAD

**Issue by hoppolek** [WarEmu/WarBugs#6716]
The description of the gloves says "+2 Dodge skill" instead of just +2% Dodge. According to .getstat it doesn't seem to give the evasion bonus.
![pippi_005](https://cloud.githubusercontent.com/assets/14668194/15870757/a57fe65c-2cf1-11e6-98fe-101d7c732a1f.jpg)
![pippi_006](https://cloud.githubusercontent.com/assets/14668194/15870756/a53b65cc-2cf1-11e6-8220-0b606623ecc2.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
