### ISSUE TITLE
Crafting Bag icon overlay

### ISSUE THREAD

**Issue by Hoppinz** [WarEmu/WarBugs#6722]
My Characters name is Hoppinst. This is the character I had this issue on. In my crafting bag I had 11 items stacked on 1 bag slot. The icons of these material would fluxuate between each image and number of materials. If i sold and rebought the items on this one slot. It would clear 10 slots in my inventory like the items where not actually on that 1 slot, When purchasing the items back they would all stack on that 1 bag slot and i would actually have 10 other bag slots open. The reason i'm reporting this. When those 10 items stacked up I was lagging super hardcore and could not figure out why. Once I sold these items my lag vanished immediately. This has happened multiple times and I know how it happens. I don't know how to completely avoid it though. If I right click the crafting material in my normal bag too fast and my craft bag has lets say 5 open slots and i move 7 materials from inventory bags this starts the overlay in the exact same bag slot. If i need to clearify more please contact me as this issue really messes up my game and possibly others if they dont realize what can make them lag as badly as I was if this incident occurs to them

**Comment by Evildoor** [comment]
#1548
