### ISSUE TITLE
Some Epic Quest rewards have wrong level requirement

### ISSUE THREAD

**Issue by Vayra** [WarEmu/WarBugs#6725]
Some of the Epic quest rewards have the wrong level requirement. This seems mostly limited to the rewards from Time To Waaagh!
Some item names:
Carnage, Northern Chill, Scourge for DoK
Corruption, Torture for Sorc

This issue means that the weapons at least have lower weapon dps than it should, and depending on how you determine stats possible lower stats than intended.

**Comment by Evildoor** [comment]
Is this wrong? Two epic quests give rewards for lvl 36, third one (Time To Waaagh) gives slightly worse rewards for lvl 35. Or there are both lvl 35 and lvl 36 weapons awarded for it?

**Comment by Vayra** [comment]
That's correct, Time to Waaagh gives only lvl 35 items while the other two gives lvl 36.

**Comment by Torquemadra** [comment]
The weapons are historical for better or worse, their time in the sun is also short lived so do not have the desire to generically match everything in there

**Comment by Vayra** [comment]
Fair enough.
