### ISSUE TITLE
low lv guards in eatine wc?

### ISSUE THREAD

**Issue by Diskete** [WarEmu/WarBugs#6726]
![apisonadora_009](https://cloud.githubusercontent.com/assets/19426036/15899420/ee50b136-2d9b-11e6-8a3a-ea5a5af38fe2.jpg)
![apisonadora_010](https://cloud.githubusercontent.com/assets/19426036/15899421/ee7ab724-2d9b-11e6-9d3f-92c01c096b9c.jpg)
![apisonadora_011](https://cloud.githubusercontent.com/assets/19426036/15899422/ee7e80b6-2d9b-11e6-80ac-cb8cba7b31e1.jpg)

i think guards lv in the eatine wc are too low, lv 14 and lv 39 npc are easy killeable for any lv 40 and the wc can be easy invade.

**Comment by saupreusse** [comment]
i replaced some of them with 55 champs. live next patch.
