### ISSUE TITLE
wrong inf items in chapter 19 elf.

### ISSUE THREAD

**Issue by Diskete** [WarEmu/WarBugs#6727]
rewards in this chapter are bugged, the third point of inf give you any gloves and shoulder of am and  ib for black ork, dunno if other class have that problem.
![apisonadora_005](https://cloud.githubusercontent.com/assets/19426036/15899716/f69652be-2d9c-11e6-8865-42a04260c430.jpg)
![apisonadora_006](https://cloud.githubusercontent.com/assets/19426036/15899718/f69a9680-2d9c-11e6-9652-56e17f24a0d4.jpg)
![apisonadora_007](https://cloud.githubusercontent.com/assets/19426036/15899717/f698c4ea-2d9c-11e6-8d53-3ae0a950ab05.jpg)

**Comment by Evildoor** [comment]
It's not AM, it's SM items which are supposed for BG: #6142.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
