### ISSUE TITLE
Book of binding issue

### ISSUE THREAD

**Issue by Amadon82** [WarEmu/WarBugs#6728]
When you bind your book in the t3 destro warcamp (Hellfang Ridge - Talabecland) and use it, you're teleport in High Pass, near the RvR zone.

**Comment by Evildoor** [comment]
I used it many times, and got properly teleported into warcamp in Talabecland. Tested just now - worked fine.

**Comment by Amadon82** [comment]
Well, can't test it anymore, i've changed the binding location a few days ago ... Good to know it's not happen to any other ppl.
