### ISSUE TITLE
Rogue mastery point appearing

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#6731]
When respecializing and removing all mastery points, I noticed that upon relogging after a server reboot I suddenly had an extra point in the right mastery tree that was not my own doing. I say extra because I already have one from Ruin gear, as can be seen in the screenshot. To get the point back, I need to respecialize a second time.

I was able to reproduce this issue multiple times by just respecializing, not assigning any points and relogging. I feel it might be related to the Ruin gear set in some way, since it dumps the point in the tree that already has one.

![screenshot from 2016-06-08 23-41-38](https://cloud.githubusercontent.com/assets/11018815/15912112/dd867778-2dd2-11e6-9ba2-68d29081f05d.png)

**Comment by Natherul** [comment]
indeed, same here I did however not realise it was from merc gear and if using that point after a relog the game would remove one random ability that I purchased with mastery as I did not have enough points. caused me to respec multiple times -.-
