### ISSUE TITLE
[Shaman] Gork's Barbs' career mechanic integration

### ISSUE THREAD

**Issue by Thayli** [WarEmu/WarBugs#6733]
The Shaman skill Gork's Barbs integrates with the career mechanic in such a way that Gork's Waaagh! reduces cast time, while it is an instant cast skill. I'm not entirely sure whether this should be regarded as a balance issue or if this is actually a bug or mistake.

![screenshot from 2016-06-09 00-32-23](https://cloud.githubusercontent.com/assets/11018815/15913444/58bc66e4-2dda-11e6-97c4-334bbd6acb8e.png)

**Comment by Evildoor** [comment]
I don't see what we can do here, since it's impossible to change tooltips yet and it's already changed not to consume your Waaagh.
