### ISSUE TITLE
T2 Epic quest chain Elf 'Echoes from the Past' and Empire 'Greater of Two Evils' cannot be finished

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#6734]
Once you completed the second quest from 'Echoes from the Past' or the first from 'Greater of Two Evils', you cannot progress as no NPC seems to give a follow up quest. I tried to look for guides and wiki on the Internet, but they all seem to be extremely incomplete on the matter. 

Didn't try Dwarf as I couldn't even find the name of the Epic quest.

**Comment by Evildoor** [comment]
Since we have #4241, i suggest you to gain a few levels and try again, maybe it's the level restriction.

**Comment by avenflar** [comment]
My character is lvl 16 and the starting quests of the chains are for lvl 10-12. I do not believe it is a matter of level.

The quest in #4241 works properly, it's the following quest that seems to be missing.

**Comment by Lheana** [comment]
For sure epic quest Echoes from the Past can be continued without problem.
