### ISSUE TITLE
Oathstone Jewelry Set 2 Piece Bonus not working correctly

### ISSUE THREAD

**Issue by Turrin66** [WarEmu/WarBugs#6736]
Looking at my Attack Speed stat it's base value is 4.2, when I use my Git Stuck In ability it increases my attack speed 30% making it 3.1. However, when I equip my Oathstone jewelry set the 2 piece bonus which is 15 Auto attack haste decreases my attack speed to 19.2 instead of increasing it by the supposed 15% which should make it somewhere in the 3.6 range without using Git Stuck In.

**Comment by Evildoor** [comment]
#6380
