### ISSUE TITLE
Quest: Song of Sorrow Ch. 22 Caledor

### ISSUE THREAD

**Issue by pixie126** [WarEmu/WarBugs#6737]
This quest is given by Lyrien. It says to kill 6 Wrathwind Hexblades.  This is do able.  It then says to seek out the captive Galdhain Starlance to turn the quest in.  I found him. He is impossible to talk to as he is either dead or running straight out into a group of npc's including a champion and dies quickly.  There is no way to interact with him unless he can be made to stay and respawn in his cage. 2 npc's will attack him there and they can be handled, 6 and a champion, no.   

![xramoth_012](https://cloud.githubusercontent.com/assets/15041016/15919668/08be8a4c-2dd9-11e6-957c-4caa4bebc4e1.jpg)

![xramoth_013](https://cloud.githubusercontent.com/assets/15041016/15919673/0c7fb12e-2dd9-11e6-907d-03a7a98455d9.jpg)

**Comment by saupreusse** [comment]
fixed in next patch.
