### ISSUE TITLE
Quest: The Hope of Ulthuan Ch. 22 Caledor

### ISSUE THREAD

**Issue by pixie126** [WarEmu/WarBugs#6739]
Quest given by Brathen Truesight.  Asks you to defend yourself after freeing captives.  Freed the captives for another quests and this is the one the NPC there attempted to have me do.

![xramoth_013](https://cloud.githubusercontent.com/assets/15041016/15923487/1130ab0a-2df3-11e6-953f-3814cf018a79.jpg)

**Comment by Lheana** [comment]
The quest has been fixed with patch from 08.10.2018
