### ISSUE TITLE
Quest: A Portent of Triumph Ch. 22 Caledor

### ISSUE THREAD

**Issue by pixie126** [WarEmu/WarBugs#6740]
Npc Wounded Unicorn attempts to give this quest. I would love to help as I am obsessed by unicorns and unicorn oppression is a no no.  :)  

![xramoth_012](https://cloud.githubusercontent.com/assets/15041016/15923584/9d361ab8-2df3-11e6-8eb4-67bd0702d000.jpg)

**Comment by sioding** [comment]
fixed with patch from 08.10.2018
