### ISSUE TITLE
Dwarf CH15 PQ inf Rewards

### ISSUE THREAD

**Issue by Camoue** [WarEmu/WarBugs#6741]
I don't exacly know is this is correct, but [Big Lad's Bonesplit] shows as an Axe item and picture of an items looks like an oh/2hSword. 
Can u make it to 2h sword if that is an 2h sword it's needed for Appearance. I just don't wanna lose that sword look...

http://i.imgur.com/HpfKC37.jpg?1

Thanks

**Comment by Razielhell** [comment]
Fixed in next Patch.

**Comment by sioding** [comment]
fixed with patch 21.10.2017
