### ISSUE TITLE
mobs out of zone 

### ISSUE THREAD

**Issue by Magteridon** [WarEmu/WarBugs#6742]
in death peak mountains, in all zone  have this mobs  up of mountain
![normak_047](https://cloud.githubusercontent.com/assets/16975012/15927257/ab59c7f0-2e40-11e6-80b8-2c404f401dfe.jpg)
![normak_046](https://cloud.githubusercontent.com/assets/16975012/15927270/bba0aa48-2e40-11e6-93d6-6ccb7da798c7.jpg)

**Comment by Magteridon** [comment]
and too is acces to toher zones  and can exit of map of here .

**Comment by NorKalli** [comment]
long since fixed
