### ISSUE TITLE
[Quest] Lob It Good!

### ISSUE THREAD

**Issue by SardonicWrath9** [WarEmu/WarBugs#6745]
The Bloody Sun Lobba interaction doesn't work, it's suppose to lob you up to Stunty Mountain not sure if this has been mentioned before I believe the race Trophy quest is up there and as someone that likes to go through the quest line and read quests it would be nice if there could be a possible fix for this, thanks for reading.

**Comment by Ryanfawkez** [comment]
There is a work around for this; you can climb up along the ridge behind the level 1 Dwarfs, over the fallen tree and past the dwarf observation point to reach Ironmane's Lock.

**Comment by Evildoor** [comment]
#390

**Comment by Xruptor** [comment]
This issue still hasn't been fixed.  As a suggestion, possibly put an NPC to just teleport the player to the correct location.
