### ISSUE TITLE
Castbar dissapear

### ISSUE THREAD

**Issue by roadkillrobin** [WarEmu/WarBugs#6746]
When taking dmg.
Spells who also gets setback to negative vallues stops casting

**Comment by Evildoor** [comment]
I confirm the disappearance, though it does not happens all the time, only sometimes. Not sure about this part:

> Spells who also gets setback to negative vallues stops casting

This only started happening a few weeks ago. And it seems that #6556 was about this.

**Comment by ozarmidrashim** [comment]
Evidence and steps to reproduce.
