### ISSUE TITLE
Engineer Magnet and Magus Rift, able to pull defenders off of keep with no regards to LOS.

### ISSUE THREAD

**Issue by Smilingdeath** [WarEmu/WarBugs#6747]
I was at a Keep siege in DW today.  While laying dead in front of the inner door, I watched an Engineer run up and pull people from the top of the inner walls all the way out and into the horde of order.  

As you cannot spawn in the keep if the outer door is down, this is a tactic that can easily deprive a keep of any defenders when an Engineer/Magus simply pulls all the healers off the top of the wall (I could barely see the top of the healers head, while the engineer would not have had ANY LOS as they were further to the left side of the door which the healer was located on that side as well.) and down to where they can easily be killed.

(Wall+healer on top of wall)____Eng____me_Door as a description of the relative description of the parties involved.  As I could barely see the healer, and the engineer would not have been able to from its position closer to the wall.

**Comment by Torquemadra** [comment]
tested on live with my engi and a GM, respects los, will not pull if i cant have a direct line of sight, can you provide more evidence with screenshots please

**Comment by Smilingdeath** [comment]
I will if the server lets me online tonight.

**Comment by Luth-RoR** [comment]
No evidence/response -> closed.
