### ISSUE TITLE
[Swordmaster] [Tactic] Ensorcelled Agony

### ISSUE THREAD

**Issue by danissrv** [WarEmu/WarBugs#6748]
Ensorcelled Agony damage seems to be reduced by toughness. 
I'm pretty sure it didn't  work like that on live. The damage is really low and doesn't worth  to spec it atm!

**Comment by Evildoor** [comment]
Proof, please.

**Comment by GankbusOsmium** [comment]
Ensorcelled Agony scales with strength so it is supposed to be reduced by toughness.

"The damage is really low and doesn't worth to spec it atm!"
It is a core tactic and you cant spec it. 
The dmg is fine though.

**Comment by danissrv** [comment]
It's very difficult to find a proof, but I will search...However  I'm pretty sure it was only mitigated by resistances.
Do you have a proof that it should be mitigated by toughness? 
Loudmouth or Potent enchantments are not mitigated by toughness, no?

**Comment by Evildoor** [comment]
> Ensorcelled Agony scales with strength so it is supposed to be reduced by toughness.

Oh, i forgot about this. Damn 4 DoTs tactic on SM. Not a bug then.

**Comment by Evildoor** [comment]
In this case by proof i meant screens / video from RoR with different damage on target with different toughness. But GankbusOsmium's comment made that unnecessary. Ensorcelled Agony scales from strength and gets mitigated by toughness. Potent Enchantments do not scale and do not get mitigated.
