### ISSUE TITLE
[RvR] Tier 3 - Can enter keeps full group through picklock

### ISSUE THREAD

**Issue by YUKO1** [WarEmu/WarBugs#6751]
Hello!

This will be my third contribution to bugs and issues of the development of ROR.

Me and my friends yesterday roamed around in Tier 3 through a private group. One of our buddies have the pick lock function that allows you (only) to enter the keep. But this time we had four mdps who shared the same ability (3 WL & 1 WH). Once activated, entire group was able to get inside - despite no icon under character bar of being able to enter doors - we killed all the guards on the bottom floor - provoked the guards on second floor - keep lord was not attackable, simply walked by to 3rd floor - top merchants on 3rd floor slain. Then the server restart came.

Clumsy me didn't screenshot it, always try to, there were no GM online at that time. Maybe some of my friends have atleast a image taken. Will update this issue later if found.

I hope someone sincerely can check this up and fix it somehow, it is quite crucial.

Kind regards,
YUKO

**Comment by Evildoor** [comment]
Post this in #6633.
