### ISSUE TITLE
Fireguard spire was captured while the hero was still alive

### ISSUE THREAD

**Issue by iRolland** [WarEmu/WarBugs#6752]
The champs and hero spawn out of their usual location which allows you to go up to banner and capture it.  All I had to do was kill the champs and the capture the bo. Didn't need to hassle with the hero.

**Comment by iRolland** [comment]
![irolland_003](https://cloud.githubusercontent.com/assets/19490541/15975210/56af9ac2-2f44-11e6-9f5c-0f3438159a48.jpg)

**Comment by iRolland** [comment]
Also you don't need to kill all the champs I only killed the front two

**Comment by Ryanfawkez** [comment]
Fixed the flag's positioning. Testing to see now if the BO can still be captured without killing the required guards.

**Comment by Ryanfawkez** [comment]
EDIT: Fully fixed now.
