### ISSUE TITLE
Dwarf Tier 2 RvR Influence Rewards

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#6753]
Issue:
- Cannot recieve influence reward from Rally Master Borgrim Runecaller. Influence area of the T2 Dwarf RvR does not include Goldpeak's Warcamp. When I enter warcamp Influence bar disappears and Influence rewards cannot be obtained (empty squares in place of rewards while talking to Rally Master)

**Comment by avenflar** [comment]
I suffer the same issue, but only on one of my characters

**Comment by Evildoor** [comment]
What about other rally master? There are two of them, in Barak Varr and Marshes of Madness?

**Comment by avenflar** [comment]
Same thing for both areas and both masters.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/7215

**Comment by Luth-RoR** [comment]
Did you try to walk to the barak varr destro warcamp from the RvR side to get the area discovery? Iirc this was a method to get the influence bar working in dwarf T2 a few months ago.
