### ISSUE TITLE
T3 Elf Order Keep: Well of Qhaysh has r41 guards.

### ISSUE THREAD

**Issue by Lileldys** [WarEmu/WarBugs#6756]
Instead of the usual r30ish champs, the keep has r41 normal mobs.
Main culprit is called "Warden", but i haven't seen the others to confirm if it's all.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
