### ISSUE TITLE
Avelorn : Dryad Oldback doesn't give the 'Chip Off the Old...' ToK unlock

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#6758]

**Comment by Evildoor** [comment]
#5429

**Comment by Lheana** [comment]
I think the unlock is now fixable : just need to kill the dryad named 'Oldbark' in Avelorn. Btw, this dryad has double spawn.

**Comment by thorbolt80** [comment]
Done today. The unlock work finally !
