### ISSUE TITLE
Scroll of the Inevitable City worked in an RvR area.

### ISSUE THREAD

**Issue by Nycta** [WarEmu/WarBugs#6759]
Two of us just used it in Drakebreaker's Scourge in Dragonwake.

**Comment by Evildoor** [comment]
Is this wrong?

**Comment by Yellowpillow** [comment]
Scrolls are worked in RvR areas on live.

**Comment by milosxe** [comment]
He doesn't mean the Guild Recall Scroll, but as the name states "Scroll of the Inevitable City". It used to work only in PvE zone, but since the patch you can use it in RvR. And I don't think that it's on purpose since it ports you instantly.

**Comment by Thayli** [comment]
It works in scenarios too. You get ported to the IC but you remain in the scenario party and the game acts as if you're still in the game, giving you status updates about the scenario.
