### ISSUE TITLE
Tome of Knowledge repetitive wipe

### ISSUE THREAD

**Issue by NorKalli** [WarEmu/WarBugs#6761]
My character Nokalli,level 40 Mara, cannot hold quests in his ToK. Daily all my quests are wiped. I can't see the ones I've picked up, nor can I turn anything.

An hour ago I picked up the anniversary quest. Thirty minutes later it's gone, and I can't progress, abandon, nor start it again.

Is there any way to completely reset my characters quest history?

**Comment by Evildoor** [comment]
#2001 and #2357 may be related.

**Comment by NorKalli** [comment]
I played nearly every day since I submitted this, it hasn't been addressed and I am incapable of receiving the anniversary rewards.
