### ISSUE TITLE
Tier 2 - Keep Lord - Shadowlands keep

### ISSUE THREAD

**Issue by Sayce78** [WarEmu/WarBugs#6762]
Warband attacked T2 Shadowlands keep with defenders. Reached Keep Lord and attacked lord. Keep Lord reset a few times then despawned at 80% and did not respawn. Other champions on lord's level respawned at least twice, but Keep Lord did not. 

This happened 6/10/16 around 10PM Pacific time.

**Comment by Evildoor** [comment]
#5841?

**Comment by Sayce78** [comment]
I saw #5841 and wasn't sure if this was the same. It might be; there could have been an error pop up that I missed. However, #5841 sounded like things were still visible but could not be targeted and, in this case, the target disappeared completely.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
