### ISSUE TITLE
The passage in the forbidden region Stonewatch,The Maw and Fell Landing.

### ISSUE THREAD

**Issue by Runnistik** [WarEmu/WarBugs#6764]
To get into Stonewatch need to specify the Assembly point Kadrin Valley. at the "you're entering a restricted area" you have to crash the client to reconnect , then you will remain in this area. For other areas you just have to change the # Assembly point on Chaos Wastes and Caledor, respectively.

**Comment by Ryanfawkez** [comment]
Assembly point = Rally point? I'm not sure what you're referring to with Assembly point.

**Comment by Runnistik** [comment]
Yes.from the curator of the camp
