### ISSUE TITLE
[Quest] Trade Waaagh!

### ISSUE THREAD

**Issue by TaeBal** [WarEmu/WarBugs#6765]
<a href="http://imgur.com/xSqlXlo"><img src="http://i.imgur.com/xSqlXlo.jpg" title="source: imgur.com" /></a>

This quest from T1 nordland War camp 
I found steal trade goods -5/5 at exactly area quest tracker pointed
But Kill enemy scouts - 0/10 is not work i think 
I killed some players in T1 with debolster 
And I killed some players in T4 
both are not work
I have count still 0/10 
Am i missed something? or is this bug?

Thank you for read and sorry for my bad english
Have good day :)

**Comment by Ryanfawkez** [comment]
Only counts in Nordland and Norsca.

**Comment by TaeBal** [comment]
I was killed some enemy player in nordland RvR area with debolster but cant get counts... something i missed?

**Comment by Ryanfawkez** [comment]
Hmm, seems debolster doesn't allow for quests to be tracked. Will have to make these quests not zone-specfic.

**Comment by Ryanfawkez** [comment]
Upped killcount to 30, made kills attainable in every zone.

**Comment by TaeBal** [comment]
Sounds good :D Thank you so much

**Comment by TaeBal** [comment]
Thanks for patch!!
Good news : Now all Anniversary dye quest count every kill.
Sad news : We have new problem
Trade waaagh!(T1 Anniversary dye quest) is not repeatable 
<a href="http://imgur.com/iV7U6AL"><img src="http://i.imgur.com/iV7U6AL.jpg" title="source: imgur.com" /></a>

I didnt check yet about T2 and T3 quest have same problem. Let me check that now and if they had problem too  -> i will report here wait for me :)
