### ISSUE TITLE
 Praag Rally Master 

### ISSUE THREAD

**Issue by Enwaaghman** [WarEmu/WarBugs#6766]
![bug](https://cloud.githubusercontent.com/assets/19395457/15985143/6f0d1482-2fe4-11e6-920c-ef7e2536beb4.jpg)

Couldnt select reward before and after some server restart and I have the Influence to take the basic reward.

**Comment by Evildoor** [comment]
Have you unlocked the Praag RVR in your ToK? Are rally masters in other Empire / Chaos zones working?

**Comment by Enwaaghman** [comment]
I have been in pve and did some unlocks in Empire just went now to Reikland wc
![bug 2](https://cloud.githubusercontent.com/assets/19395457/15985445/5c63ff54-2fed-11e6-89c0-e416a887d0df.jpg)

only one who works is the Rally Master in Chaos Wastes.
