### ISSUE TITLE
[Pocket Item] Kossar's Helm

### ISSUE THREAD

**Issue by TaeBal** [WarEmu/WarBugs#6769]
<a href="http://imgur.com/asK2Lt1"><img src="http://i.imgur.com/asK2Lt1.jpg" title="source: imgur.com" /></a>

This pocket item said : Form corrupted bear in 5min , This effect will removed immedietly when you getting hit 

But this pocket item not work atm 
Its from Birthday token vendor

**Comment by Torquemadra** [comment]
spellID 15175, working on dev server, needs pushing to live.

**Comment by TaeBal** [comment]
Oh ok thanks for answer :)

**Comment by Torquemadra** [comment]
working now on live
