### ISSUE TITLE
Trial by pain, bugged ability? 

### ISSUE THREAD

**Issue by jpnrd** [WarEmu/WarBugs#6770]
Hi! 

I never use it but i've just figured out that trial by pain doesn't stop / can be triggered when you turn your back to the target, even when walking/running. 

Here's a sreenshot
![sbradaradjan_044](https://cloud.githubusercontent.com/assets/16733126/15985612/92f6839c-2ff3-11e6-81a2-8bc4418687a6.jpg)

I don't know if it's inteded or bugged so i report, sorry if useless post :/ 

Have a good day :)

Ps: the screenshot shows the target (to see the damage) but it works when running with no sight of it like 10 feet behind.

Pps: as usual, HUGE thanks to all the team for RoR! ;)

**Comment by ozarmidrashim** [comment]
Intentional
