### ISSUE TITLE
"sticky Squig"

### ISSUE THREAD

**Issue by ricdur** [WarEmu/WarBugs#6774]
Hi guys, the abiliti "sticky squig" look broken when i use it on a WHunter just after it pop and KD me.
The abiliti work find every time exept for ALL WHunter after a pop and KD, the abiliti not work and don't pull me away their sword, I stay near them and they kill me... without run...

Thank you.

**Comment by Daknallbomb** [comment]
Dat whs using seal of sigmar , they are immun to the slow there . and if ist like that u cant jump away .

**Comment by Evildoor** [comment]
Yes, most likely it's a smart WH who uses snare immunity, and you have to snare at least one opponent to jump back. Not a bug.

**Comment by ricdur** [comment]
Thanks to reply, i will test the abilitie more attentively, it seems if an enemie parry that have the same effect than an ummuninty and don't throw me back.
