### ISSUE TITLE
Raiders 'o Da Lost WAAAGH! Quest ~ {Part IV} Bugged ~

### ISSUE THREAD

**Issue by Sovox** [WarEmu/WarBugs#6776]
When you reach this stage that asks you to **investigate the Dig Site**, the intractable 'site' _does not give the player anything_, and thus cannot continue further on this Anniversary Quest.

**We tried logging in and out as well as restarting the quest.**

_______________________________________________________________________________
![lestrange_055](https://cloud.githubusercontent.com/assets/19616566/15987789/dfda81c6-2fea-11e6-9805-5dc1181ed493.jpg)

_____________________________________________________________________________
![lestrange_056](https://cloud.githubusercontent.com/assets/19616566/15987799/a65acbc6-2feb-11e6-981d-08cd25b1a2fe.jpg)

_{ ^~ Also located here for some reason is another set of **Long Forgotten Tools**, which is needed for a previous part of this quest line. ~^ }_

**Comment by Sovox** [comment]
#6773 Also mentions this in their post as well =)

**Comment by Ryanfawkez** [comment]
Works fine on the dev server.

**Comment by Sovox** [comment]
@Ryanfawkez I will test this out today to triple check. From what I've heard a lot of others are still encountering this issue, though.

Will report back.
