### ISSUE TITLE
Guild Recall Scroll spending before perform purpose

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#6780]
When i activate Guild Recall Scroll there is animation with channeling started, it is for 10 sec long. If i move while animation is perform channeling is stops, but animation (blue aura) stays. And more important - scroll itself spended in a moment of klick on it, while it should spend after 10sec channeling complete and it perfopm telepotration action.

**Comment by dalen** [comment]
This has been fixed since
