### ISSUE TITLE
Kills double counted occasionally for Raiders o' da lost Waaagh

### ISSUE THREAD

**Issue by Zuyanna** [WarEmu/WarBugs#6782]
One Dragon Ogre kill counted as two towards quest completion.  This doesn't happen all the time or with the same mobs, but i've heard of it happening on this quest specifically enough to want to take a screenshot.  I'm sorry if this has been previously reported, my searches didn't indicate it was.  
![zafara_002](https://cloud.githubusercontent.com/assets/19364515/15991996/b936de66-308f-11e6-8fd5-0dfad3c8e869.jpg)

**Comment by Evildoor** [comment]
#6782
