### ISSUE TITLE
Ram's can block

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#6783]
Here, a ram is shown blocking a attack.

http://jun.imghost.us/C7kO.jpg

**Comment by Lileldys** [comment]
Is blocking all Direct Damage it seems. DoTs tick just fine.

**Comment by Soulwhisper** [comment]
![maxeras_003](https://cloud.githubusercontent.com/assets/16864486/16041500/6036f16a-323e-11e6-8148-1c5292c4c0ad.jpg)
Confirmed.It blocked all melee attacks.

**Comment by stillwaterww** [comment]
I can confirm this is the same for oil, only attack I managed to land was the dot debuff.
![sorrowstrike_030](https://cloud.githubusercontent.com/assets/19287032/16081806/6ca40178-330f-11e6-8c10-e76734e32bb0.jpg)

**Comment by Soulwhisper** [comment]
Its the same for all siege weapons.Change title to Siege Weapons can block.

**Comment by ozarmidrashim** [comment]
Intentional.
