### ISSUE TITLE
High Elf Ch 1 - Prince Eldrion

### ISSUE THREAD

**Issue by Sayce78** [WarEmu/WarBugs#6784]
Prince Eldrion does not have a green indicator that he has a quest to give. (He doesn't have the orange one to indicate a turn in either, but it looks like that was reported elsewhere and is a UI issue.) 

First, you are given a quest to talk to him - no orange indicator, but that's okay since there's a quest to direct you there. Then he gives you a quest to kill Arkaneth Harpies; no orange indicator for turn in, but that's okay. Then - nothing. No quests. Of course, if you talk to him again he will give you the quest to kill Arkaneth Witch Elves ("The Brides of Kaine"), but for a minute there you're left wondering where the next quest is!

**Comment by NorKalli** [comment]
replaced NPC, questline now works properly

**Comment by sioding** [comment]
fixed with patch from 26.05.2018

**Comment by avenflar** [comment]
I created a new character in T1 Emp 2days ago and noticed that every NPC was like OP's description (mission quest markers) but it fixed partially itself over the course of a couple of hours. 

So it may not be an issue with the individual NPCs themselves ?
