### ISSUE TITLE
High Elf Ch 1 - "Tears of Lileath" quest - invisible mobs

### ISSUE THREAD

**Issue by Sayce78** [WarEmu/WarBugs#6785]
In the tower where you find the scrolls for the "Tears of Lileath" some mobs (the Corsairs) are unable to be seen or targeted, even when they attack.

Details:
The first time, I was in the small room with the Scroll of Fortune. I first killed the mob by the scroll, then was attacked by another mob that I could not see. I spun around, moved up and down the room, cleared my target (the dead mob) to see if it would populate what was attacking me, but I could not target the mob and I died. 

The second time, I killed the mob I saw in the room, grabbed the scroll, began to be attacked by an invisible mob, and ran up the ramp toward one of the upper scrolls. I attacked the mob by the upper scroll (above Scroll of Fortune), turned around and now saw three mobs (the invisible one from below, an invisible one from above, and the one I saw and attacked that was by the scroll). 

I'm not sure how consistent this is. I stayed in the scroll area trying to get the tears of Lileath to appear and the mobs were almost always visible. Moving around when attacked by an invisible mob (maybe changing levels?) seemed to make them appear. Pathing there was a little messed up and might be a factor. For example, before the scroll area, when I was on a ramp shooting at a mob below, it would not run up the ramp (which curved along the wall of the tower) to get to me - it took a straight line which caused it to disappear from below and reappear in front of me. I could not get the tears to appear (might be because I was too slow, not sure if that is an issue), so I eventually moved on.

**Comment by Lheana** [comment]
NPCs are fine now.
