### ISSUE TITLE
Scenario/game glitch 

### ISSUE THREAD

**Issue by Daorkyorks** [WarEmu/WarBugs#6790]
so i was playing a scenario and someone needed help with a T1 lair (im level 17) so they invited me to the party. i accepted. when i left the scenario the game logged me off my character so i went back on/ when i came back on i was left at the inevitable city. the game thought i was level 40. and my renown bar was gone. so i went to ostland then the level fixed but my renown bar was still gone. my character is a black guard. the black guards name is Shorlishlina. Can you please fix this?

**Comment by Evildoor** [comment]
This is visual only and will fix itself over time. #1791
