### ISSUE TITLE
Quest Bait & Switch Ch. 18 Praag, also Broken Ground PQ (not working I know)

### ISSUE THREAD

**Issue by pixie126** [WarEmu/WarBugs#6793]
There are no Gloomglade Scouts to kill to complete this quest.  They are part of stage 1 of Broken Gound, but there are none in that area.

![xramoth_014](https://cloud.githubusercontent.com/assets/15041016/15995183/52c993f6-30dc-11e6-9d92-594b68879de1.jpg)

**Comment by saupreusse** [comment]
Fixed the quest. Public quest is not fixed yet ofc.

**Comment by Sprak2686** [comment]
Having trouble with another part of this quest chain. 

Bait & Switch seems to be bugged at "Kill Doomblade Vraslyn" due to being unable to attain his helm.

PQ in area doesn't seem to be working properly either.

**Comment by Luth-RoR** [comment]
>PQ in area doesn't seem to be working properly either.

title: 
>also Broken Ground PQ (not working I know) 

and 
https://github.com/WarEmu/WarBugs/issues/6793#issuecomment-225877719
