### ISSUE TITLE
[Orvr] Order keeps

### ISSUE THREAD

**Issue by stillwaterww** [WarEmu/WarBugs#6794]
When taking an order keep as destro and put an oil down there it spawns order oil, quite a moneywaster and makes defending a bit more challenging. I've seen this happen in Eataine and in Kadrin Valley.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
