### ISSUE TITLE
[Birthday Event] Bear hat

### ISSUE THREAD

**Issue by stillwaterww** [WarEmu/WarBugs#6795]
When choosing the hat reward that turns you into a bear you can drag and drop the item to your castbar and activate the transform buff while not having the item equipped in your pocket slot.

**Comment by Ryanfawkez** [comment]
The Skaven Cloak does the same thing. As I recall from live, you didn't have to actually wear the item for the buff clicky to be usable.

**Comment by Torquemadra** [comment]
Always able to activate from backpack without being equipped.
