### ISSUE TITLE
The Siege Merchant, that never spawned.

### ISSUE THREAD

**Issue by Dethik** [WarEmu/WarBugs#6796]
I was told by the GM I spoke to on top of the TM keep to post these SS's here and tell my story... Well it began with... Oh he meant the Destro Siege Merchant that NEVER spawned in Bloodfist Rock Keep in Thunder Mountain... Not once... Never... At all... So yeah, that's a thing.
![dethik_011](https://cloud.githubusercontent.com/assets/8033617/15996452/5600e2fe-30dc-11e6-8f53-e97d820dcd0e.jpg)
![dethik_012](https://cloud.githubusercontent.com/assets/8033617/15996459/60282530-30dc-11e6-97da-5e69b19ed3dc.jpg)
![dethik_014](https://cloud.githubusercontent.com/assets/8033617/15996460/6374a92a-30dc-11e6-92ed-cc4d709d9ad2.jpg)

**Comment by Dethik** [comment]
No body, Never spawned(even after keep flip), and not a trace in the natural spawn location of this Merchant.

**Comment by stillwaterww** [comment]
I'm told the merchant is on extended holiday ;)

**Comment by Evildoor** [comment]
#6499
