### ISSUE TITLE
empty zone keep ticking

### ISSUE THREAD

**Issue by koza2205** [WarEmu/WarBugs#6798]
yesterday at eataine there was a huge rvr and destro got 1  keep ..Order atacking without managing to do anything and we get the tick rewards.sudenly every ordo goes to pragg and 4-5 ppl stay at eataine keep with every bo on ordo side the keep in around 1 h tick around 4-5 times without action in the zone  
and i think thats probably a bug couse it needs around 24++ kills so it can ticks

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
