### ISSUE TITLE
Defensive BG T4 2h weapons have wrong price and type

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#6800]
Sentry's Glaive of Vehemence. 440 instead of 880.
It is also classified as a "Spear" and not "Great Spear" which means it is currently usable as a 74dps 1h weapon.

Same goes for Sentry's Glaive of Barbarity which has the correct price but is also considered a Spear with 65.3dps 1h.

**Comment by Ryanfawkez** [comment]
Thank you for the report. The fact this spear was flagged as a one-hander caused the issue in which i falsely gave it the same amount of Emblems required as for a regular 1 handed weapons.

Both spears are two-handed now and have their price fixed.
