### ISSUE TITLE
Fighter's Armbraces of Vengeance

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#6801]
Cannot equip this item.Bought it from Bountyman Cohen.The Toughness/Initiative one CAN be equipped.
![maxeras_000](https://cloud.githubusercontent.com/assets/16864486/16005059/e23c91f0-316d-11e6-8acf-ae6ffc2a679a.jpg)

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
