### ISSUE TITLE
[ITEM] Tradeable magus mount

### ISSUE THREAD

**Issue by ellionkeman** [WarEmu/WarBugs#6805]
Basic magus mount can be sold. Looks like slow but easy way for money duping.

![awwakuua_000](https://cloud.githubusercontent.com/assets/18136746/16018775/a43cea08-31ae-11e6-81dc-965307fc3dbd.jpg)
![awwakuua_001](https://cloud.githubusercontent.com/assets/18136746/16018774/a439402e-31ae-11e6-84fc-71a81e9e3908.jpg)
![gandalfine_001](https://cloud.githubusercontent.com/assets/18136746/16018779/a45460fc-31ae-11e6-9e74-96dbef4553c9.jpg)
![gandalfine_002](https://cloud.githubusercontent.com/assets/18136746/16018776/a444aca2-31ae-11e6-90bd-b38a7c21124e.jpg)
![gandalfine_003](https://cloud.githubusercontent.com/assets/18136746/16018777/a4459392-31ae-11e6-8481-9793060b660f.jpg)

**Comment by Torquemadra** [comment]
fixed next patch
