### ISSUE TITLE
freeze

### ISSUE THREAD

**Issue by lftr** [WarEmu/WarBugs#6808]
hello,

Since the last patch (rr80) wednesday i have always a freeze during 2 or 3 seconds everytime when i join a sc at the first contact with ennemy party 
After the freeze i can play the whole sc without nothing

**Comment by Evildoor** [comment]
#4824?

**Comment by lftr** [comment]
hello,
i have this problem too with rp/zealot buff but no it's another one.

**Comment by lftr** [comment]
hello
i have no freeze since 2 days thanks for you fix.
