### ISSUE TITLE
Bug Abuse ! Teleport

### ISSUE THREAD

**Issue by Jubok21** [WarEmu/WarBugs#6809]
Hey i make a PQ with 4 Guildmates and at the end one player teleport to us(Abuse) with Name : Varzan

and Know the  timer when we finish the quest and teleport to us...

**Comment by sullemunk** [comment]
Might be a GM checking if you where boting? Or it might have been a player that just came out of an SC or just logged in

**Comment by Evildoor** [comment]
1) I agree with sullemunk. Not all players appearing near the end of PQ are abusers and cheaters. Get some proof first.
2) Bugtracker is for bugs, not for reports. Read
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=3524
