### ISSUE TITLE
Caretaker Proc heals too much

### ISSUE THREAD

**Issue by tutti13** [WarEmu/WarBugs#6812]
For a melee-DoK, the 5pc. Duelist proc (Caretaker) heals 382 instead of the 180 mentioned in the tooltip.

![caretaker](https://cloud.githubusercontent.com/assets/11341460/16039372/bb247cce-3229-11e6-859c-320e1f103948.PNG)

**Comment by taccr** [comment]
The issue here is that it's scaling with str.

**Comment by ozarmidrashim** [comment]
Intentional.

**Comment by tutti13** [comment]
Awesome. Nevermind then.
