### ISSUE TITLE
THE EMPEROR'S MANDATE quest

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#6815]
Issues:
*Intelligence potion (Lasting Potion of Insight) as a reward for KotBS. I think strenght would be better.
*Map indicator, in Chapter 3 camp, where to turn-in the quest is lightened up before You kill Empire Turcoats
*Empire Turncoats don't have attack animations.
*From chapter 4 quest is giving 5 times the same reward (same items) over and over again
*Quest chain in Norsca is weird. First we have to investigate 10 cesspools and kill 10 Plague Forsakens then Investigate 1 cesspool and find sunken buidling (clicking on cesspool do the trick also for the building) and finally Cleanse 1st 2nd 3rd and 4th cesspool and again clicking on any cesspool once finishes all four.

(Small moderator Edit: pls do NOT use the " - [ ] " function to create a list..)
(I won't anymore)

**Comment by Soulwhisper** [comment]
Looks as completed on NPC but its not.

**Comment by peusnaugrim** [comment]
Same problem as *From chapter 4 quest is giving 5 times the same reward (same items) over and over again. Canno't finish the quest. Sergent Polk 58.30 don't validate the last part of the quest. Can't take items

**Comment by Lheana** [comment]
The Epic Quest has been reworked few weeks ago. Everything is fine now.
