### ISSUE TITLE
THE DOCTOR'S ORDERS quest

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#6816]
Issue:
Intelligance potion (Lasting Potion of Insight) as a reward for KotBS. Strenght, Armor or Toughness would be better.

**Comment by Soulwhisper** [comment]
This is a major issue.I think its linked as Intelligence potion for all classes.

**Comment by Meralors** [comment]
Added a str potion to the possible rewards. Not 100% sure this is a MAJOR issue tho ;)
Live next patch
