### ISSUE TITLE
[ToK] unlock "Kill 1000 member of the empire" not work

### ISSUE THREAD

**Issue by TaeBal** [WarEmu/WarBugs#6818]
<a href="http://imgur.com/HCMH89s"><img src="http://i.imgur.com/HCMH89s.jpg" title="source: imgur.com" /></a>

I have 1000 kill dwarf and elf already and i bought dwaf and elf 1000 kill reward trophy
But empire is not work atm 
Kill 1000 empire already but not unlock and cant buy 1000kill trophy 

Thanks for read :)

**Comment by Camoue** [comment]
Its allready reported.

**Comment by TaeBal** [comment]
Oh i didnt found was searched : 1000 kill , empire / can you link for me? if that true -> i will delete this thread

**Comment by Evildoor** [comment]
#6454
