### ISSUE TITLE
A STICKY SITUATION quest

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#6819]
Issue:
Quest consists two parts. First part is to kill 5 Venomfangs and free Gavin Scherer. And second part tells us to free Gavin Scherer again

**Comment by Soulwhisper** [comment]
Oh boy.Now Gavin Scherer is gone from the cave :( @Luth-RoR Canf find him.

**Comment by Razielhell** [comment]
@Luth-RoR @Thayli fixed it.
