### ISSUE TITLE
T4 event quest - only 1 reward

### ISSUE THREAD

**Issue by tutti13** [WarEmu/WarBugs#6821]
The last step for the t4 order event Q only rewarded me with the 2 years anniversary cloak. No token.

**Comment by Nastylicious** [comment]
it says you may choose between 1 of the following item that means you can only choose the cloak or the token your choice really

**Comment by tutti13** [comment]
Correct. This is exactly how it is NOT supposed to be. You are supposed to get both.

**Comment by Nastylicious** [comment]
soo thats mean all thoes who have done the quest will never get the second item from that quest hmm sad

**Comment by tutti13** [comment]
True.

I already opened a post on the forums regarding this issue and PMed magicthighs about this. Maybe there is a solution -.- I need those goggles.

**Comment by Blubberino** [comment]
Well I got both and since you have to pick cloak and the currency item I most certainly think you too you just spent that token on the item you want...

**Comment by Ryanfawkez** [comment]
@blubberino - certainly the case for people on Destruction, on Order this quest was saved invalidly after its much-needed fix due to how the new choice count is enabled.

**Comment by tutti13** [comment]
Will the fix also be applied for people who already completed it and only got one reward?
