### ISSUE TITLE
bug talisman equipment

### ISSUE THREAD

**Issue by Lasorar** [WarEmu/WarBugs#6823]
I can not equip talismans on my objects , they refuse to crimp it .
The object window appears Bugge.
![lasorar_008](https://cloud.githubusercontent.com/assets/19935617/16053517/7a9458d8-3269-11e6-9762-aec86d224aa2.jpg)
![lasorar_009](https://cloud.githubusercontent.com/assets/19935617/16053525/80f9578c-3269-11e6-97e5-12ab60aee2d3.jpg)
As you can see there is a drop-down menu on the side , maybe this is the has the annihilator because I have never had such problems before.
Yours

**Comment by taccr** [comment]
What talisman are you using?

**Comment by Lasorar** [comment]
Willpower +24 potent talisman of tenacity id (907360),
nothing anormal with it. level36 anni helm 40 so, tali is not the problem i think.

**Comment by taccr** [comment]
helm is 35, talis 36. working as intended.

**Comment by Lasorar** [comment]
helm 40 for the second twice.
![lasorar_010](https://cloud.githubusercontent.com/assets/19935617/16055972/b134463c-3273-11e6-8faa-249e70c22afc.jpg)

**Comment by taccr** [comment]
No. Only the rank requirement matters for slotting talismans - It's clearly 35.

**Comment by Lasorar** [comment]
(O_O) oki, thanks for your answer.
