### ISSUE TITLE
Earthshatter - rarely not dealing its AoE damage

### ISSUE THREAD

**Issue by hoppolek** [WarEmu/WarBugs#6824]
Ironbreaker's Earthshatter rarely does AoE damage (it does happen rarely). It mostly only hits one target for damage (my enemy target afaik), while the snare is still AoE.
![bubbis_008](https://cloud.githubusercontent.com/assets/14668194/16056418/b83968d4-3275-11e6-83bb-d753d1be7d12.jpg)
![bubbis_009](https://cloud.githubusercontent.com/assets/14668194/16056422/ba70449c-3275-11e6-967e-edc974122457.jpg)

**Comment by Shadowgurke** [comment]
If you read the tooltip of the ability, the damage only starts once you have 25 Grudge. Below that only the Snare gets applied. Your target most likely dies from your autoattack afterwards

**Comment by hoppolek** [comment]
My grudge is shown as purple in my UI showing 100 grudge. You can also see my combat log in the lower right showing how the monster died from my earthshatter. 

After playing around with it a bit more in RvR. I don't find any pattern of when it doesn't deal AoE damage, and when it sometimes does.
