### ISSUE TITLE
T1 sm 2h weapon 

### ISSUE THREAD

**Issue by koza2205** [WarEmu/WarBugs#6826]
![kopelia_000](https://cloud.githubusercontent.com/assets/16072249/16061981/22ae0bd4-3299-11e6-89df-04236130fb43.jpg)
it doesnt have talisman slot

**Comment by koza2205** [comment]
![kopelia_000](https://cloud.githubusercontent.com/assets/16072249/16062002/4026bd6e-3299-11e6-8153-0aae7617e1e4.jpg)
same goes for 2h

**Comment by koza2205** [comment]
![kopelia_001](https://cloud.githubusercontent.com/assets/16072249/16062019/4b47da98-3299-11e6-8eef-26692f60d98c.jpg)
same goes for 2h

**Comment by noisestorm** [comment]
afaik no t1 inf weapon has any tali slots?

**Comment by Ryanfawkez** [comment]
@noisestorm - Half of them did, half of them didn't. Added talisman slots to all Nordland RvR rewards, for the sake of consistency. Also fixed their levels.
