### ISSUE TITLE
Hekara Ravenblood double spawn + quest 'Ascension' broken

### ISSUE THREAD

**Issue by Mebrind** [WarEmu/WarBugs#6828]
Approx co-ords: Praag, 50668,24162

Double spawn of the NPC Hekara Ravenblood.

Is also the questgiver for the quest 'Ascension'. The goal of the quest is to kill the NPC, but the NPC stays friendly when the quest is accepted, not possible to kill the NPC to finish the quest.

**Comment by noisestorm** [comment]
Since we dont have the technology to trigger a hostility change i assume the double spawn was intended to have one killable, while the other functions for the quest. So one should probably have its faction changed?

**Comment by Mebrind** [comment]
Both version of the NPC can give the quest. When the quest is accepted (I've abandoned and tried to accept from both versions) both stay friendly and cannot be interacted with any further. I tried talking to the npc after the quest assuming that a dialogue would trigger the hostility change, but nothing happened.

**Comment by noisestorm** [comment]
Which uhm.. is exactly what i posted?

**Comment by Mebrind** [comment]
I misunderstood your last sentence as how it was currently working, rather than a suggestion to fix the issue.

**Comment by Nekronsieben** [comment]
there are still double NPC's http://i.imgur.com/JG8jayo.jpg

**Comment by l3liss** [comment]
Can confirm; Still broken; Cannot kill friendly NPC

**Comment by sioding** [comment]
No double spawn - checked. Quest works fine
