### ISSUE TITLE
T4 DOK/WP influence items

### ISSUE THREAD

**Issue by Nyuszika** [WarEmu/WarBugs#6829]
Please fix the stats on DOK t4 influence items, like to have a healing chest in greenskin as a WP have, and to have same shoulders as the the WP have from the elf zone. DOK t4 inf shoulders have not heal crit or parry on it.

And also fix some mixed items, that having str and willpower, or str and healing power  etc., cos atm belts, and backs, and alos most of weapons (willpower with weapon skill) are mixed, but it shoud be one meele and one heal at least.

TU very much!

**Comment by Tholkienn** [comment]
Yes, some melee stat and crit heal...

**Comment by Meralors** [comment]
Is it a difference in stats between live and RoR version or something you would like to change?

**Comment by Nyuszika** [comment]
Well i just want usefull heal and dps armor as a reward. Example in t4 greenskin have 2 chest with 30 str as main stat, no healing one.  And in elf zone shoulder DOK have missing stat (2% parry, 3% heal crit - WP inf items have) and also both have dps stat on it.
I want balance between DOK and WP influence items , and to change stupid items like willpower and meele power together.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/6457
