### ISSUE TITLE
[public quest] destruction of the weak Tonas Jorgen bug (norsca)

### ISSUE THREAD

**Issue by ithridell** [WarEmu/WarBugs#6830]
the npc boss of the stage one is dead but the pq don t start phase 2

**Comment by Meralors** [comment]
I couldn't reproduce this on dev. If anyone have this bug on live please link to this report.

**Comment by Meralors** [comment]
Checked live, I think its a tempory bug on live, hopefully a reboot will fix it.

**Comment by Luth-RoR** [comment]
No response -> closed.
