### ISSUE TITLE
Zone 0

### ISSUE THREAD

**Issue by iRolland** [WarEmu/WarBugs#6831]
Not sure if this is client side problem or a bug .... But went through open door in sigmars hammer. Landed here ...
![irolland_027](https://cloud.githubusercontent.com/assets/19490541/16089063/747f107e-3321-11e6-9b20-189faccafc1b.jpg)
Then went towards the light
![irolland_028](https://cloud.githubusercontent.com/assets/19490541/16089081/86bddf68-3321-11e6-9652-1cb13ab6cc86.jpg)
and landed in zone 0

Easily fixed by using book of binding to return to proper location.

**Comment by MaxHayman** [comment]
Assume this is fixed next patch

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
