### ISSUE TITLE
SM Discerning Offense & Poised Attacks consistency issue

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#6832]
Discerning Offense gives:
	- 10% block strikethrough
	- 10% parry strikethrough
	- 10% evade strikethrough
	- 10% disrupt strikethrough
	
Poised attacks in imp/perf stance gives:
	- 10% block strikethrough
	- 10% parry strikethrough

So either Discerning Offense should not give evade/disrupt strikethrough or it's missing from Poised Attacks.

**Comment by Zealote** [comment]
Discerning Offense is racial so needs to affect all avoidance, whereas you should only be able to parry/block an SM's melee attacks, meaning the other two aren't needed. So I don't see that this is a bug.

The only possible issue is when it says you've disrupted Gusting Wind. I thought the internal server calculations were still using the correct stats (WS and parry), but if it's not it would obv be a slight disadvantage that GW isn't affected by PA.

**Comment by Luth-RoR** [comment]
True.
