### ISSUE TITLE
ITEM Annihilator boots for MARA

### ISSUE THREAD

**Issue by Zanilos** [WarEmu/WarBugs#6833]
[(http://imgur.com/hk6Ear8)]

I can only presume this item is missing stats. 
Genis preview google doc states that they should have 25 Tough, not 10. 
[(https://docs.google.com/spreadsheets/d/13C0SbnhRDmmD_6DaxgoeBuDhM8yLy2igWktFQ6DkdKo/edit#gid=1222955442)]) Link for reference.

**Comment by Meralors** [comment]
Matching Geni file I changed annihilator boots thoughness to 25 ( and corrected the title ).
Live next patch.

**Comment by Zanilos** [comment]
Wrong title was uhhh... intentional. Obviously.

Thanks for fix.
