### ISSUE TITLE
Procs triggered by oil

### ISSUE THREAD

**Issue by hoppolek** [WarEmu/WarBugs#6834]
As the oil is physical damage it is now triggering procs (detected by Jagged Edge). I also noticed some oils dealing very high crit damage and figured that tactics that affects crits (like fierce might) also affects the oil damage. Oil is hard camped and hard to make any real tests.

**Comment by Luth-RoR** [comment]
Is this still an issue?

**Comment by Vancerus** [comment]
Did throw some oil today and is still proccing everything as Convenants, Mara Mutations, Tactic Heal Debuffs and so on. I don´t think that is intended.

![vancero_231](https://cloud.githubusercontent.com/assets/14907399/19412941/e62f3f00-9320-11e6-873a-d3a847196c78.jpg)
