### ISSUE TITLE
t1 lair bugged

### ISSUE THREAD

**Issue by koza2205** [WarEmu/WarBugs#6835]
http://plays.tv/video/576187447aefe96189/probably-bug-abuse in this video you can see how they bugged t1 lairs with taunt i think it happens in the other lairs too and in every tier couse Taunt doesnt work as it used to be

**Comment by Kaelang** [comment]
Appreciate this is a dated report - however this does not provide enough information to identify the issue and/or replicate the problem. Please re-open this issue if this persists in the latest version of RoR.

The video link is no longer live.
