### ISSUE TITLE
TM warcamp PvE route no LoS on fences and r39 normal guards.

### ISSUE THREAD

**Issue by adeie** [WarEmu/WarBugs#6837]
The PvE exit to the TM warcamp (27K,54K) has normal r39 Bloody Sun Stompa npcs and the fence does not break LoS allowing order to be pulled in.

![screenshot_129](https://cloud.githubusercontent.com/assets/15959651/16094822/e2c152be-3339-11e6-9436-c7211fc8bcb0.png)
![screenshot_128](https://cloud.githubusercontent.com/assets/15959651/16094840/f111b872-3339-11e6-901e-f2c811250fd2.png)

**Comment by Meralors** [comment]
I add some 55+ guards so order can't get inside camp. But for the fence I have no idea what kind of fix can be done, but with those new guards, any order close enough to be pulled will be killed before the pull is done .
