### ISSUE TITLE
MISLED quest

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#6838]
Issues:
- Cage Prisoners attack and kill Norse Invaders
- No ambush during questline (maybe because it requires scripting)

**Comment by Meralors** [comment]
I'm not sure what you want to report with this? :) Quest can be completed correctly, you have to click on the cage, not the prisoner. 
And anything scripted isnt working yet, but again its not stoping the quest to be completed :)

**Comment by StaH84** [comment]
Of course it can be completed. I know about the cages. Just reporting faulty parts of the quest so it can be perfect as the Warhammer Online is:-)
