### ISSUE TITLE
parry in knockdown

### ISSUE THREAD

**Issue by Lemonpie1** [WarEmu/WarBugs#6839]
titel says it my attacks are getting parried in knockdown mostly by choppas

**Comment by Ryanfawkez** [comment]
How was this on live? Were attacks undefendable during knockdown there?

**Comment by Lemonpie1** [comment]
They shouldn't be able to block or parry but i don't know if you can dodge or disrupt while knocked down

**Comment by Luth-RoR** [comment]
Controversial topic; some people say it was possible to defend attacks during knockdown, some say it was not possible (in my **oppinion** was not possible).

**Comment by Zealote** [comment]
What's the status on this, does there need to be a forum thread?

I know logic probably won't be the primary determining factor, but it would seem to suggest that you shouldn't be able to parry/block while knocked down (though I guess you could argue you might be facing up an so still able to...).

Regardless, unless someone can provide a vid of someone defending during a kd, it seems reasonable to assume you couldn't.

**Comment by Zealote** [comment]
Looks like the SM blocks while knocked down in this video (https://www.youtube.com/watch?v=0tWPOeyPifk) at ~3:16.

**Comment by Luth-RoR** [comment]
No, looks like he blocked during KD.

**Comment by MKorin** [comment]
but on live you cant turn around while knocked down

**Comment by Zealote** [comment]
> but on live you cant turn around while knocked down

Wait for Luth or someone else to confirm, but afaik it's just a visual thing when the player turns while knocked down - they still face in the same direction as they were when you first used kd.

**Comment by Luth-RoR** [comment]
Does KD turning still work?
Iirc there was a problem in the past with KDs: 
There either had to be the "KD+target movement lag" bug or the "KD+turning" bug; both could not be fixed in the past; but afaik devs found a fix for both a few months ago.

**Comment by Zealote** [comment]
I just tried it with WE's kd and yeah people can still turn. Don't know whether it's just visual though.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
