### ISSUE TITLE
Greenskins Chap. 15

### ISSUE THREAD

**Issue by Zaccar20** [WarEmu/WarBugs#6841]
Hey i found some Bugs/ or give you just info about some not working PQs.

**Public Quests**

~~Overtop Outpost (easy PQ)
don't work now (just a info)~~ **_Has been fixed_**

~~Morfang da Med (normal PQ)
don't work yet (just onemore info :))
and i don't now maybe ist a bug, the south entrance to the PQ (the door) don't work!~~ **_Has been fixed_**

**Quests**

Pile On (quest)
Boozraz Waaagzzug is next to the Bat Hollow after a long looking for him i found him.
Maybe a 2nd mark on the map would help to  find him much easier. Not everyone will look around so long like i do ;)

The rest of the Chap. work well just on the hard PQ the Counter don't work right  sometimes.

I will soon show my impressions of the next chapter!
Grettings Zaccar :)

**Comment by Ryanfawkez** [comment]
One problem per report in future, please.

**Comment by Zaccar20** [comment]
ok

**Comment by Lheana** [comment]
Fixed with patch from 21.10.2018
