### ISSUE TITLE
T4 accessory tome unlock bug

### ISSUE THREAD

**Issue by Antiguanec** [WarEmu/WarBugs#6842]
Dear programmers, thank you for your hard work. I want to tell you about the bug in a design of book of knowledges. For slaying 100 Chaos Spawns not unlocked "Broken Bones" and NPC "Disciple Venomstung" trade for this wrong 2nd item "One Tusk" not "Broke Toof" from a set "Da Waaagh! Teef". My charaster name Bison, you can check it. Very tnx if you fix it.

**Comment by Vayra** [comment]
Broke Toof is unlocked by killing 100 Bloodbeasts of Khorne, not Chaos Spawns.

**Comment by Antiguanec** [comment]
Where they spawned?

**Comment by Thayli** [comment]
There's 2-3 in Chaos Wastes, at the PQ The Tower of Awakening. The guide on the forums regarding these tome unlocks does indicate Chaos Spawns, but it is indeed Bloodbeasts of Khorne. I made the same mistake a few days ago.

**Comment by Antiguanec** [comment]
Thanks for you guys
