### ISSUE TITLE
Gamecrashing on attempting enter a group

### ISSUE THREAD

**Issue by Glaurung80** [WarEmu/WarBugs#6843]
It was more than for three times in one game session. I was in Emp T2 and was trying to join the RvR-party. Every attempt caused game crash.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
