### ISSUE TITLE
tier pvp war camp siege weapons

### ISSUE THREAD

**Issue by SEINFELD11** [WarEmu/WarBugs#6844]
hellfire cannons do not cause any damage. no sound or recoil either.

thank you.

**Comment by SEINFELD11** [comment]
forgot to add on - its the single target cannons that do not work.

thank you.

**Comment by SEINFELD11** [comment]
Hello,

Tier 1 Warcamp for Chaos, Nordland. Attempting to shoot at empire players.
They are in range and the targeting arrow goes red. I can click to fire,
and it does show reload animation. But no damage to players, no firing
sound or recoil animation.

Thank you.

**Comment by Ryanfawkez** [comment]
Perhaps they run out of range. The no sound issue is known, happens when you attempt to fire multiple times in a row.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
