### ISSUE TITLE
[Tank Morale] Demolishing Strike 

### ISSUE THREAD

**Issue by Chummi** [WarEmu/WarBugs#6845]
Apparently this morale stacks with any ability armor debuff. 

On live not a single armor debuff stacked. Whether morale with ability, morale with proc nor proc with ability. The "active" armor debuff was always the highest one. 

It's quite broken since that stacking allows you to debuff ~2500 armor.

**Comment by sullemunk** [comment]
to compensate the morale + tactic +ability armor buff stacks as well iirc

**Comment by Pxl555** [comment]
What sullemunk said is for most cases wrong in RoR, most if not all armor buff morals do not stack ( ex. Mountain Spirit, Eye of sheerian ,1k1 Blessings ,Gift of Life) and some tactics  like zealot warping the spirit and RP Regenerative Shielding do not stack either. The few exeptions to this rule in RoR are Engi/Magus armor buff and Dwarf racial tactic. How the non-morales interacted i can not recall but i do know that morale buffs were nerfed not to stack and it would seem feasible that the debuffs wouldn't stack either but i can not provide confirmation for that.

**Comment by Luth-RoR** [comment]
Buffs/debuffs shouldn't stack at all atm. Tactics stack though.
Report needs evidence (.getstats output).

**Comment by Zealote** [comment]
I thought the principle was that buffs from separate groups (that is, ability/tactic/morale/?) should stack? E.g. Blorc's Walk It Off! M2 (tough buff) *does* currently stack with Savin' Me Hide... I don't know whether that's how it's sposed to be though. 

I'm pretty sure, however, that almost no armour buffs/debuffs should stack, regardless of how other stat (and other things like +% avoidance) buffs worked: dwarf racial tac and the engi/magus 60min buff were two of the only ones (maybe the only two) that stacked iirc.

Anyway, I tried testing it on a mob with my IB and my ability damage with both Stone Breaker (SB) and DS applied was higher than with SB alone. **But** my AA dmg seems to have remained the same (???):

-Normal non-debuffed Grudging Blow dmg = 221
-GB dmg with 1088 debuff from SB = 275
-GB dmg with SB's debuff + 1056 debuff from DS = 286
-AA with just SB debuff *and* with SB/DS debuffs = 362

![ds arm stack](https://cloud.githubusercontent.com/assets/10598420/17459160/3b23b140-5c25-11e6-9800-cce0909cb5b6.png)
