### ISSUE TITLE
queue scenario bug

### ISSUE THREAD

**Issue by ithridell** [WarEmu/WarBugs#6848]
sometimes sc queue bug if you were in combat recently. it appear you are always in combat even 10 mn after. same if you cap a neutral bo. if the queue proc you can t go in.

i ve got a picture but i don t know how to put it in sorry :/

**Comment by taccr** [comment]
Did you use unlock?

**Comment by Soulwhisper** [comment]
Just drag it from your computer inside the text.

**Comment by ithridell** [comment]
![alshara_000](https://cloud.githubusercontent.com/assets/19818901/16129942/548a3db6-3407-11e6-84d2-d46c93e2df5d.jpg)
no i didn t use unlock because i don t even know wha do you refer ^^

**Comment by Soulwhisper** [comment]
Type in chat : .unlock

**Comment by Ryanfawkez** [comment]
https://github.com/WarEmu/WarBugs/issues/1015
