### ISSUE TITLE
[NPC] Chemor the Pungent 

### ISSUE THREAD

**Issue by ellionkeman** [WarEmu/WarBugs#6849]
Troll country 48.5k 7.4k. There're 2 copies of this npc.

![balphus_017](https://cloud.githubusercontent.com/assets/18136746/16131470/f8e15912-3416-11e6-864b-a8b429d62b50.jpg)
![balphus_018](https://cloud.githubusercontent.com/assets/18136746/16131471/f8e3dba6-3416-11e6-8489-6d408c2d31cf.jpg)

**Comment by Styrkarr** [comment]
Fixed in next patch.
