### ISSUE TITLE
[QUEST] Wyrmbreaker quest - Dark Elf Ch.18

### ISSUE THREAD

**Issue by Morkhill** [WarEmu/WarBugs#6852]
The Quest line "Wyrmbreaker" is available in Ch. 18 [DE] with the NPC Tanulos Spitespear, you can complete the first 5 parts but not the last one which is supposed to grant you the choice between a few equipable items. Is it possible to fix this so that you can access these reward items ?

**Comment by sioding** [comment]
fixed with patch from 17.11.2018
