### ISSUE TITLE
quest not completing with full backpack message

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#6854]
![onesword_backpack](https://cloud.githubusercontent.com/assets/19988772/16142033/bdba8a80-349c-11e6-9c86-bc922f5f272e.jpg)
my backpack was full at first attemp to complete quest
then i played orvr with full backpack
after that i made empty spaces but it still says these messages
relog, restart didn't work. other quests are fine 
character name is 'onesword'

**Comment by Ryanfawkez** [comment]
Empty your crafting bag a bit as well, that should resolve your issue.

**Comment by anarchypark** [comment]
also not working
should i just abadon and do it again?
if it's not a general bug and only in this character's case i don't mind

**Comment by Luth-RoR** [comment]
Requires also a server restart afaik.

**Comment by Spelldaoc** [comment]
Bags now allow overflow. Should correct issues.
