### ISSUE TITLE
Tier 4 Black Cragg Badmoon Keep outer door 

### ISSUE THREAD

**Issue by Krazis** [WarEmu/WarBugs#6855]
The outer door and inner door seem to reset themselves. There seems to be a possible link to holding 3 BOs. Once we capped 4 BOs the door became invulnerable. 
Contact GM Aryion he was present during the siege for more detailed information.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
