### ISSUE TITLE
Incorrect Bolstering in lower tiers

### ISSUE THREAD

**Issue by Renork** [WarEmu/WarBugs#6856]
I haven't seen this on the bugtracker yet. The bolster for t1/t2 is incorrect. Players are getting bolstered to level 13, but if you're level 11 (cap) you do not get bolstered. The same thing applies to t2, at level 21 (cap) you do not get bolstered, but everyone between 12-20 gets bolstered to 22 and 23.

**Comment by Lileldys** [comment]
You get overbolstered when at a lower rank in each tier. To make up for less gear/skills/masteries

**Comment by noisestorm** [comment]
overbolstering is indeed no bug.
