### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#6860]
Its corporeal not coporeal :)
![maxeras_003](https://cloud.githubusercontent.com/assets/16864486/16157977/a7132aae-34c3-11e6-98d1-c4f20c97e64f.jpg)

**Comment by 56SillyStrings** [comment]
If you lock under the "block" information there is also a word misspelt.

**Comment by Soulwhisper** [comment]
attacks and not atacks yeah
![maxeras_004](https://cloud.githubusercontent.com/assets/16864486/16161093/5e9a68e4-34d4-11e6-945e-6e9eeb2f8462.jpg)

**Comment by ozarmidrashim** [comment]
Clientside.
