### ISSUE TITLE
Magical/heal power

### ISSUE THREAD

**Issue by NihilAbalham** [WarEmu/WarBugs#6861]
Hi, 
The figures of heal power and magic power do not seem vouchers. At present they bring a ratio of 1 for 5, to little meadows, as for the willness or the intelligence. On the official server the power of care and the magic power were, it seems to me, of a ratio of one for one even two but no more. Objects containing these statistics just became useless. Is it wanted ?

Thank you for all that you make !

**Comment by Vayra** [comment]
Magic / Heal power always was 5:1 just like Int/willpower. The purpose of Magic / Heal power was to bypass the soft / hard cap on the main stats.

**Comment by ozarmidrashim** [comment]
False report. Do not post a bug report based on simple contradiction from live, especially when you are not sure.

Closed with extreme prejudice.
