### ISSUE TITLE
[NPC] Eataine white lions

### ISSUE THREAD

**Issue by stillwaterww** [WarEmu/WarBugs#6862]
These white lion npc's are killing off their pets.
![sorrowstrike_031](https://cloud.githubusercontent.com/assets/19287032/16161444/d118c39a-34cd-11e6-9a62-f5a79b43ba5b.jpg)

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16037
