### ISSUE TITLE
Twenty Steps Quest

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#6866]
First Part.
Looks as completed but its not.

**Comment by krillep** [comment]
Still not fixed.

**Comment by sioding** [comment]
Do not bump.
The bugtracker is not a forum in which old threads get buried by the new ones – we regularly look through all reports, both old and new. Creating a duplicate report because the existing one "is too old" is pointless and so is "bumping" old reports with meaningless comments.

**Comment by krillep** [comment]
That it hasn't been fixed for over a year, is also pretty meaningless.

**Comment by sioding** [comment]
Checked the Quest on dev and it works fine. All three steps are OK.
