### ISSUE TITLE
Chap 4 Dwarf Quests 'Dog Fight' and 'Stout and Bitter' are identical in content, and I don't think that correct.

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#6867]

**Comment by Hargrim** [comment]
Changed reward from Stout and Bitter to shoulders.

Fixed in next patch.

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16037#p177201
