### ISSUE TITLE
Bug?!

### ISSUE THREAD

**Issue by Furrianer** [WarEmu/WarBugs#6874]
Hi
I have found a bug at the chosen ability-display. The shown number of armor is about 1900  that must be wrong because all of my equipment should be at 2900 armor. The question is is the calculation of armor and resistances even wrong? For clearity i have taken a screenshot about this figures in case you want it you can have it.

**Comment by Lileldys** [comment]
Have you slotted the tactic "Focused Offense"?

**Comment by Luth-RoR** [comment]
No evidence(.getstats output)/response -> closed.
