### ISSUE TITLE
WELCOME TO TROLL COUNTRY Public Quest

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#6878]
Issue:
- Multispawn (2 or 3 mobs in one place).

**Comment by Sayce78** [comment]
Issue #2: stages/counters do not show, but PQ progresses. No loot roll/loot at completion of PQ, even though chest appears.

Tonight, for some reason, the PQ was stuck at 4/50 Hill Crushes, Stage 1, but we were able to kill the champions in stage 2 when they spawned (even though it didn't say stage 2) and the hero in stage 3 when it spawned (even though it didn't say stage 3). Chest appeared after hero died, but no loot roll, no bags. No timer for reset either. 

We did earn influence throughout.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/7104
