### ISSUE TITLE
Empire/Elf T4 influence rewards: DoK

### ISSUE THREAD

**Issue by bobselektor** [WarEmu/WarBugs#6880]
the stats of these items should be swapped in order to have melee power bonus with the other dps bonuses instead of tank/healer stats. ex: torment cloak of repose with melee power and the charon's cloak with healing crit.

![eltsin_011](https://cloud.githubusercontent.com/assets/20017460/16173024/8cc03e08-3595-11e6-8f8c-35afb9b08989.jpg)
![eltsin_012](https://cloud.githubusercontent.com/assets/20017460/16173025/8cc61a08-3595-11e6-863f-2b0f0557b38c.jpg)

**Comment by Torquemadra** [comment]
Opinionative and not a bug, it all fits with much of the t4 items which were hybridized. Not willing to change these items at this stage as multiple attribute dependency for Doks and WP are a much larger issue and people may alreay have taken the items for a purpose.
