### ISSUE TITLE
White Lion: Guardian Spec 'Brutal Pounce'

### ISSUE THREAD

**Issue by DragonTank** [WarEmu/WarBugs#6881]
When this ability knocks them on the ground the can spin around on the floor so its hard to get a side or back strike on them, dunno if this is supposed to be working like this but surly if their knocked down they shouldn't be able to spin around on the ground?

**Comment by Lileldys** [comment]
Happens with all knockdowns

**Comment by noisestorm** [comment]
The direction of back/side gets saved on the server the moment the target gets his knockdown. even if they turn visibly around their position will not get updated. visual issue is hard to fix but will be adressed in the later future. for now the only thing i can tell you is: if you knockdown someone as wH for example where you require their back, then you can stand right there after the knockdown to still receive the flanking bonus
