### ISSUE TITLE
Tactics not properly updating with Bolster

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#6882]
![maxeras_009](https://cloud.githubusercontent.com/assets/16864486/16174260/0b888ff6-35c3-11e6-89a6-aa32f28c01da.jpg)
It should restore 140 and not 128 in Berserk and in Furious 80 instead of 73.

**Comment by noisestorm** [comment]
Are you sure its not because of tooltip<->bolster inconsistency?

**Comment by Soulwhisper** [comment]
Outside of RvR lakes its 73/128 on tooltip.By the time i entered RvR and i got bolstered it went up to 80/140.I will further test it and report back.Closing for now

**Comment by Soulwhisper** [comment]
Still the same.I tried removing the tactic and putting it back in...and then it correctly scaled up to 80/140.So it is buggy...it doesnt give you the correct amount of health when you get bolstered.
![maxeras_010](https://cloud.githubusercontent.com/assets/16864486/16177448/424d5eae-3636-11e6-8d76-e843d50517e3.jpg)

**Comment by Soulwhisper** [comment]
Yes...ok here is the issue:
I tried removing the tactic and putting it back in...and then it correctly scaled up to 80/140.It doesnt give you the correct amount of health when you get bolstered.You have to remove it from your tactics bar and put it back in to update it.

**Comment by Soulwhisper** [comment]
Same issue with other tactics too.You have to remove and put back in to get them updated.

**Comment by Soulwhisper** [comment]
Here is the video clearly showing the bug.
https://www.youtube.com/watch?v=QQe3vwt9OMs

**Comment by Soulwhisper** [comment]
AFAI Understand they dont update automatically the first time you get bostelered.If you get bolstered and replace them manually they update correctly and after that they correctly downscale-upscale when you debolster-bolster.

**Comment by Soulwhisper** [comment]
Any news on this one? Looks like gamebreaking.Many people dont know that and get stuck with previous stats which makes them weaker and also battles become un-stable.

**Comment by Soulwhisper** [comment]
FIXED
