### ISSUE TITLE
Wrong PQ Ui/tracker persistence

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#6883]
![maxeras_007](https://cloud.githubusercontent.com/assets/16864486/16174283/279b8116-35c4-11e6-8f69-67902bad217a.jpg)
This one with Afflicted Zombie pops up randomly and gets stuck many times,when entering the area i draw on the map below.
![maxeras_008](https://cloud.githubusercontent.com/assets/16864486/16174286/644a9e8a-35c4-11e6-928f-2b8e0babd574.jpg)

**Comment by Soulwhisper** [comment]
Maybe an Addon nasty Glitch though.

**Comment by Soulwhisper** [comment]
Happened again with all Addons disabled.

**Comment by Reggaewaldo** [comment]
I can confirm that this happens for not only this but other public quests as well.

**Comment by noisestorm** [comment]
Quest trackers for pretty much all PQs are somewhat buggy. be it the location of where they are being visible or the update rate/progression. Not sure if there was another report yet about this, so ill mark it for now

**Comment by Luth-RoR** [comment]
I was told that PQs sometimes bug too, if you have already full influence from the area. 
I tested this though with the "ruinous power" PQ and it did work fine for me with full influence.

**Comment by dbsimon88** [comment]
Yeah I guess I'm one of the only people reporting that this happens to every public quest I try (11). I haven't been able to complete any PQ!

**Comment by Soulwhisper** [comment]
**Current state with latest Hotfix 15/08/16.**
This happens more often now.PQ Ui persists when you enter a PQ and you leave the area.Its completely random.

**Comment by wargrimnir** [comment]
This was fixed in general. Code was looking for two different indicators for the PQ, it now checks only the map files.
