### ISSUE TITLE
Sigmars Grace

### ISSUE THREAD

**Issue by Richardwarhawk** [WarEmu/WarBugs#6884]
The Warrior priest Mastery Ability Gives the wounds buff for an hour but also Heals everyone in your group for 800 health.. Ita not supose to heal people for 800. either that or it adds 800 Health but its suppose to add 80 if im correct, I might be wrong.

**Comment by noisestorm** [comment]
80 wounds equates to 800 hitpoints. And it was knowlingly implemented the way that it heals the full amount of HP that it buffs.
