### ISSUE TITLE
Bright Wizard T4 Influence Rewards: Empire

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#6886]
Hello everyone,
I think quite a lot of the BW Influence rewards have shitty stats and because I think that shouldn't be the case I would like to report them/have them changed.

Lets start with the helm (second empire reward)
![bw_empire_helm](https://cloud.githubusercontent.com/assets/16117730/16176493/2add4c80-3612-11e6-9794-099eb87a3e22.jpg)

The Grille of the Fist is fine even though a change from Initiative to Wounds would be welcome.  On the Grille of Repose a change from willpower to intelligence would be welcome. If you say "No, thats a defensive item" than change it please to disrupt... that would be more usefull than willpower

Now the back (third empire reward)
![bw_empire_back](https://cloud.githubusercontent.com/assets/16117730/16176624/3dfda1f6-3613-11e6-841d-26b23eb85297.jpg)
Imo both are currently inferior to the level 39 green drop back with 30 int/20 wounds. To fix that both would ideally have to change to int/wounds stats. If you dont want to do that please put some int on both of them.

**Comment by Torquemadra** [comment]
Please dont request main stat replacement on items just because of your personal preferences, this is not a bug. While you can make a small case for the willpower being a wasted stat you cannot say the same about initiative. WP changed for universal stats.
