### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by TheJinxer** [WarEmu/WarBugs#6887]
I've been trying to register but keep getting this error message after I submit my information. 
-----------------------------------------------------------------------------------------------------------------------
General Error
SQL ERROR [ mysqli ]

MySQL server has gone away [2006]

An SQL error occurred while fetching this page. Please contact the Board Administrator if this problem persists.
------------------------------------------------------------------------------------------------------------------------
I'd love to know if anyone knows how to fix this.

**Comment by noisestorm** [comment]
Sorry but thats no bug for the ingame platform/client. Use the search on the forum and if you cant find anything make a post there.

(To me it looks like the cloudflare bug in which you just have to try again a fw times, or wait a bit and try again tomorrow or so)
