### ISSUE TITLE
Quest - Flatten 'Em!

### ISSUE THREAD

**Issue by Jsnen** [WarEmu/WarBugs#6888]
When using the cannons in the quest Flatten 'Em!, the greenskins dodge all artillery attacks and instead fly across the divide and engage in melee.

**Comment by noisestorm** [comment]
not sure if that can be fixed currently so lets ask our good guy @Ryanfawkez about it

**Comment by avenflar** [comment]
Same things is happening with the Empire quest at the starting zone. If you fire at the Hellcannon, it touches the NPC in front of it instead who aggroe

**Comment by Ryanfawkez** [comment]
Would have to re-enable the ability to fire at enemy NPCs, which can only be done if we find a way to prevent XP to be gained from killing NPCs with siege weaponry.
