### ISSUE TITLE
Bright Wizard T4 Influence Rewards: High Elf

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#6889]
Hello,
the BW T4 high elf influence rewards are a real mess right now.

Belt (1st reward)
![bw_high_elf_belt](https://cloud.githubusercontent.com/assets/16117730/16176778/ed5e9642-3617-11e6-9f57-2638c9fe5707.jpg)
Keysash of Hatred: Please change Initiative to Wounds. It would fitter better into the defensive setting of the item and makes more sense if you consider the class mechanic.
Wraith's Keysash: Please Change Willpower and Initiative to Intelligence because currently that Item doesn't make much sense.

Shoulders (2nd reward)
![bw_high_elf_shoulders](https://cloud.githubusercontent.com/assets/16117730/16176835/5dea481e-361a-11e6-8b39-0b867806698a.jpg)
If you add up the stats and compare them to the mercenary you will notice that they are about even. So they are missing a % based boni. I couldn't find the item on arsenalofwar.com but maybe you have other sources.
If you could then also change the willpower to wound or intelligence the items might even be usefull.

Staff (3rd reward)
![bw_high_elf_staff](https://cloud.githubusercontent.com/assets/16117730/16176872/8246cf60-361b-11e6-92aa-9ac0f6dd9474.jpg)
Alright... these staff are both so bad compared to the dwarf reward (Bloodfist Greatstafft, on the right) or the SC staff it isn't even funny anymore. I don't know how you feel about introducing lager amounts of magic power but I think that could be a way to make them viable compared to the crit staffs. In any case please get rid of Willpower, Thoughness and Initiative.

**Comment by Torquemadra** [comment]
Again, you dont get to propose changes on the bugtracker, this is for bugs not opinions, if an item has something worthless to a class, like weaponskill on a staff thats something to be considered. Willpower changed, nothing else.

**Comment by Cimbas** [comment]
Thanks for your reply. Since you didn't adress the shoulders I ask again. I don't have the stats for the Bright Wizard but according to arsenalofwar.com (http://www.arsenalofwar.com/search?name=wraith) the healing classes get an additional 2% crit.
