### ISSUE TITLE
[Chosen] Aura still bolstered after leaving PVP zone

### ISSUE THREAD

**Issue by Ruffenuff** [WarEmu/WarBugs#689]
I did the following steps with my lvl 4 chosen:
- Go to an open world PVP zone (e.g. in Nordland) where you get the "bolstered" effect and your lvl is raised to 15
- Use an aura (e.g. "Dreadful Fear") => your strength gets increased by +36
- Leave the PVP zone and lose the "bolstered" effect
- This is the Bug: Now the aura is still at value +36. (at lvl 4, it should be +12)
- In Addition: after switching to another aura like e.g. "Corrupting Wrath", waiting until the timer of "Dreadful Fear" runs out and activating "Dreadful Fear" again, it is now back at +12

**Comment by Thorgatin** [comment]
Did you test if it isn't just visual? The character window doesn't always show correct values, even when they work correctly on the server.

**Comment by Ruffenuff** [comment]
I just tested it using the ability "enraged blow" on a lvl 1 pox rat, with my lvl 4 chosen and an axe with dps 9.0 / speed 2.7. Here are the results:
- +0 str: 49 dmg (+38)
- +12 str: 50 dmg (+38)
- +36 str: 57 dmg (+45)
