### ISSUE TITLE
Bright Wizard T4 Influence Rewards: Dwarf

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#6890]
Hello again,
I would like to propose a few changes to the bright wizard influence rewards.

Boots (1st reward)
![bw_dwarf_boots](https://cloud.githubusercontent.com/assets/16117730/16176965/fba873ba-361e-11e6-8c11-1d10d8be3394.jpg)
While the Drengi Ashboots are currently a viable option because it's the only pair of boots with crit on them a change from Initiatve and Toughness respectively to Wounds would be most welcome.

Body (2nd reward)
![bw_dwarf_body](https://cloud.githubusercontent.com/assets/16117730/16176984/aaf02f70-361f-11e6-8c0e-60c1f052502f.jpg)
Like the High Elf shoulders, if you add up the stats and compare them to Mercenary its about even. But they are missing the 3 AP per sec.
Also it would be welcome if the Initative, Thoghness and Willpower could be converted to Intelligence or Wounds.

Staff (3rd reward)
![bw_dwarf_staff](https://cloud.githubusercontent.com/assets/16117730/16177018/4c714216-3621-11e6-91ec-6e47ca7be883.jpg)

Badmoon Emberstaff: Currently you can buy a better staff than that at the altdorf vendors (Vanguard Emberstaff of the Caster, on the right). Depending on how you feel about power creep it might be done with changing Initiative to wounds.
Bloodfist Greatstaff: Great Item. High Int, High Crit and I dont mind the morale gain on it because it makes it unique among the top tier staffs.

**Comment by Torquemadra** [comment]
Again, you dont get to propose changes on the bugtracker, if an item has something worthless to a class, like weaponskill on a staff thats something to be considered.
