### ISSUE TITLE
Stealth breaks when you dodge/parry

### ISSUE THREAD

**Issue by Lemonpie1** [WarEmu/WarBugs#6894]
Now I don't know if this is a bug or not but it seemed kinda odd to me that when someone hits you with an ability while in incognito and you dodge/parry that ability it breaks stealth.

**Comment by noisestorm** [comment]
There are still a bunch of strange things happening with stealth yes. Since i had reported something similar back then, but it got marked as 'fixed' and closed ill keep this one as open for now
