### ISSUE TITLE
distance check

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#6895]
t2, stonetroll keep, trying to go back inside; i don't think i was that distant.
![attilio_005](https://cloud.githubusercontent.com/assets/17765890/16178822/0837963a-3654-11e6-9f30-222369ca3f99.jpg)
ps: i was not pounced,disabled,mezzed or whatever

**Comment by noisestorm** [comment]
Are you perhaps playing from the US(or just with a bad ping) and were perhaps spamming it from quite some distance before and simply died in front of it?
