### ISSUE TITLE
"Perfect Defenses" tactic for Swordmaster keeps resetting

### ISSUE THREAD

**Issue by Tyalath** [WarEmu/WarBugs#6904]
Yesterday I used a specialization point to get the tactic called "Perfect Defenses" for the swordmaster, first tactic in Path of Vaul, but after about 10-20 minutes of playing I get a message "You have gained a specialization point" and then the tactic is gone. I went to spec for it again after a few minutes received the same message again and tactic is gone. I asked in advice chat but no one seems to be having the same problem, all their tactics and abilities are working. It was just before the server restarted.

**Comment by Lileldys** [comment]
Are you using one of the 5pc set bonuses for an extra mastery point? I sometimes loose my selected skill with this, but I am currently unable to figure out the cause.

**Comment by Torquemadra** [comment]
changing an item, any item including weapons, jewellery and even trophies causes the reset on the +1 system at the moment requiring the point to be respent.

**Comment by Tyalath** [comment]
Hmmm did not even think about it because I had enough points without needing the bonus point from the armour set. I removed the armour set, re specialised the points and then equip the armour set and it worked. Thank you.
