### ISSUE TITLE
[Ironbreaker] Seen It All Before tactic seems to increase crit dmg

### ISSUE THREAD

**Issue by Zealote** [WarEmu/WarBugs#6905]
Tested on a lvl 19 mob:

  Without tac: Normal hit = 34 , crits = 48, 49, 49, 50, 50, 50, 51, 51, 51, 51, 52, 52, 53, 54
  With tac     : Normal hit = 34 , crits = 52, 52, 52, 52, 52, 53, 54, 54, 54, 55, 57, 58, 58, 59
(I've ordered the crits)

Strangely, getstats correctly shows -15 to bonus crit dmg so I've re-checked and tried to make sure I'm not making any stupid mistakes (like getting the results the wrong way round :P). Might be worth someone else double checking though if poss.

**Comment by taccr** [comment]
https://github.com/WarEmu/WarBugs/issues/4805

**Comment by Zealote** [comment]
The one time I forget to search first -.- Closing.
