### ISSUE TITLE
ToK Unlock 'Not So Great Anymore' - Reikland , Grinya, killing it doesn't give the unlock :(

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#6907]

**Comment by Meralors** [comment]
Not so Great Anymore is unlocked by killing Bloodmane (http://warhammeronline.wikia.com/wiki/Not_So_Great_Anymore) . Do you have info saying Grinya should unlock something too?

**Comment by avenflar** [comment]
https://returnofreckoning.com/forum/viewtopic.php?f=8&t=1837

CTRL + F Not so great anymore

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16037
