### ISSUE TITLE
Slayer/Warrior Priest/Engineer - Empire T3 Inlfuence Rewards

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#6910]
Can you adjust the stats?
Stoneclaw and Karagaz War Shroud are exactly the same.
Whats the dilemma between Passwatch War Shroud and Thickmuck War Shroud? Ofc you go for the Thickmuck.
So now we got 2 rewards to choose instead of 4.
Same for Warrior Priest and Engineer rewards.
![influence rewards](https://cloud.githubusercontent.com/assets/16864486/16212796/e975479c-3752-11e6-87ce-f3c498708aba.jpg)

**Comment by Meralors** [comment]
We try to set stats as close as possible from live WAR. DO you have a link to those items?

**Comment by Soulwhisper** [comment]
Unfortunately i cant find any source.I doubt that there is an open source out there for specific oRvR influence items for Slayer.If you could balance them temporarily though it would be great.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/5494
