### ISSUE TITLE
GRAVY TRAIN quest

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#6911]
Issues:
- maybe a trivial one but quest discription says to get bat meat but bats don't drop any and "meat" is counted as kills
- same reward as Situation Abnormal (or Last Stand - can't remember) quest.

**Comment by Hargrim** [comment]
Changed description to Kill Leatherwing Bat.

Changed reward of quest Gravy Train to Cadger's Gloves from Cadger's Shoulders.

Fixed in next patch.

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16037#p177201
