### ISSUE TITLE
Chapter 15/16 High Elf Eataine PQ UI and Chapter Bars

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#6918]
PQ UI(There is no Progress info.) and Chapter Bar are missing.

**Comment by DragonTank** [comment]
i got mine working randomly all ive done is run around the whole map to unlock the zone map and its randomly appeared.

**Comment by Soulwhisper** [comment]
It shouldnt be randomly though...The bar must appear when you enter a Chapter.We can have custom size PQ areas.The PQ UI should appear when you enter the PQ area...

**Comment by Soulwhisper** [comment]
Ok here is the bug: If you dont visit Chapter 16 area and unlock it PQ UI(in all 3 PQs) and Chapter Bar dont show in Chapter 15.If you visit/enter Chapter 16 and unlock the area you can then see all PQ UI and both Chapters in whole Eataine **BUT** if you enter Chapter 15 it shows Chapter 16 bar and if you enter Chapter 16 it shows Chapter 15. **Eataine needs customization for PQ UI and Chapters** Regards :D 
And thanks to DragonTank.

**Comment by Soulwhisper** [comment]
Torquemadra

- Corrected mixed up PieceID for High Elf Chapters 15 and 16 returning the appropriate influence bars to the correct areas
