### ISSUE TITLE
White Lion ability bugged

### ISSUE THREAD

**Issue by Hekireki** [WarEmu/WarBugs#692]
Hello,

My ability Blindside is supposed to inflict an Ailment to my opponent, the spell requires to be on the back/flank of the opponent. The spells is casted (and can be casted ONLY if flank or back so that's not about that) but the ailment doesn't apply everytimes or almost, depending on the luck and if you are REALLY well positionned on the back of the enemy, it shouldnt be this way, the spell is grey when im not on the back/rear, when it enlight up I can cast it and it should logically apply the ailment, which it doesn't..., so basically my rotation is broken because I need this ailment to use my Lion's Fury ability (which by the way deals imo less dmg than it should, it's supposed to be 100+ spiritual dmg, it deals smth like 70 or 80 to trolls)
Another bug is the pet, always 30 feet behind, almost useless, dying in 3 hits he doesn't get bolstered (not like in the original game really...) The pet seems to have delay, he really can't follow me and that's a pain. The spell Charge! doesn't apply the movement speed on the pet, bugged.
There is also the fact that the pet dmg are not recorded in the final stats of dmg in scenarios.

Thanks for the hardwork, this career is fun but really at this point really not fun to play because of the bugs ruining the fun :)

**Comment by Thorgatin** [comment]
Known. It's like that with every damaging ability atm (particularly melee abilities). Maybe this can be fixed by adding ability queues to the server.

It's also advisable, to always create one bug report for each problem. So the devs can close them one by one after a fix.
