### ISSUE TITLE
MOB in waterfall

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#6928]
32/44 
![toufekiaaaa_001](https://cloud.githubusercontent.com/assets/16864486/16249227/1ff9e532-381d-11e6-8770-f76b2dda1bbe.jpg)

**Comment by Torquemadra** [comment]
It isnt, its actually flying in the air but we are missing information to make its character model reflect that at this point.

**Comment by Soulwhisper** [comment]
Closing for now then.
