### ISSUE TITLE
Shrine of the Dragontamer - PQ High Elf Chapter 21 

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#6929]
- If you complete final stage it tells you that you havent participated enough to get a reward and stucks like that on the screenshot below until it resets.

![toufekiaaaa_004](https://cloud.githubusercontent.com/assets/16864486/17718701/f7e40dc0-641d-11e6-883d-d6473d3eecec.jpg)

**Comment by saupreusse** [comment]
Works just fine. reset happens 3 minutes after the boss is killed. if it gets stuck, that is emu related i guess.

**Comment by Soulwhisper** [comment]
I said if it fails.

**Comment by Soulwhisper** [comment]
Look even if you complete final stage it tells you that you havent participated enough to get a reward.
![toufekiaaaa_004](https://cloud.githubusercontent.com/assets/16864486/17718701/f7e40dc0-641d-11e6-883d-d6473d3eecec.jpg)

**Comment by Soulwhisper** [comment]
**Updated Status 09/06/2016**

**Comment by Kaelang** [comment]
![image](https://user-images.githubusercontent.com/60117106/82145063-06f0e180-9840-11ea-85ac-8003e58bdab5.png)
Was able to complete this PQ without any sticking issues, and received participation rewards.

If you are aple to replicate on the newer versions of RoR, please re-open this issue.
