### ISSUE TITLE
Marauder Influence items duplicate

### ISSUE THREAD

**Issue by ShotsOnTarget** [WarEmu/WarBugs#693]
Festenzplatz Pillager Dark Ring and Festenplatz Pillager Rend Ring both have identical stats. These are the RR9 INF rewards from Nordland Warcamp for Marauder.

**Comment by Evildoor** [comment]
Was fixed at some point. Dark Ring is a BG which was missing class restriction. Now marauders have choice between Rend Ring and Dark Band.
