### ISSUE TITLE
on both of your knees!

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#6931]
screenshot taken just now during an impromptu dueling contest, why exactly is the skill "on your knees" hitting twice? (i got caught by the aoe while wash was dueling someone else and it strikes 2 hits)

http://tinypic.com/view.php?pic=505taq&s=9#.V2ndkqKd9sA

**Comment by ozarmidrashim** [comment]
because OYK! is a WE finisher and it hits twice
