### ISSUE TITLE
Raven Host Vanguard PQ

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#6933]
- [x] **Stage 1**. Most of the Raven host marauders are linked out of the PQ even if they are in the middle of the area killing them doesnt count them in progress of PQ/Dont give you any influence.
- [x] **Stage 2**. Doesnt work.MOBS still dont spawn around Sigmar.

**Comment by Soulwhisper** [comment]
**Current Status after 8/8/2016 Patch**

**Comment by Soulwhisper** [comment]
**Current Status after Changelog 23/08/16**

**Comment by Soulwhisper** [comment]
**Current Status after Changelog 28/08/16**

**Comment by Soulwhisper** [comment]
For Stage 1 problem im providing screenshots below with the marauders that fall out of the PQ.
![warhammer online age of reckoning 09 18 2016 - 12 49 17 15](https://cloud.githubusercontent.com/assets/16864486/18614914/32115a38-7da1-11e6-8b97-da26a2db3211.png)
![warhammer online age of reckoning 09 18 2016 - 12 49 41 16](https://cloud.githubusercontent.com/assets/16864486/18614915/32151df8-7da1-11e6-872c-b74083fcd23a.png)
![warhammer online age of reckoning 09 18 2016 - 12 50 02 17](https://cloud.githubusercontent.com/assets/16864486/18614916/321c19c8-7da1-11e6-957d-af2aa993a07f.png)
![Uploading Warhammer Online  Age of Reckoning 09.18.2016 - 12.51.30.18.png…]()
![Uploading Warhammer Online  Age of Reckoning 09.18.2016 - 12.58.53.19.png…]()
![Uploading Warhammer Online  Age of Reckoning 09.18.2016 - 13.09.21.21.png…]()

**Comment by wargrimnir** [comment]
Converted remaining Stage 1 spawns, added mobs to Stage 2.

**Comment by Soulwhisper** [comment]
- Ok there is an issue on Stage 2.
- [ ] The Brave peasants you added are 3 level.Father Sigvald is 4 Level. Marauders that spawn around him are 2-3 Levels.Didnt engage at all and Sigwald just couldnt die.NPCs just killed Marauders on their own.On live you should protect Sigwald and if you failed(Marauders kills him) then Peasants and Sigwald should turn hostile on you and you should kill them to advance in Stage 3.
- [ ] Also if you kill marauders in Stage 2 they have slow respawn rate and they respawn again in last 3 seconds of Stage 2.

**Comment by wargrimnir** [comment]
Yeah, none of that is happening without scripting.

**Comment by Soulwhisper** [comment]
Maybe a workaround until it can be done? Can you make Friendly NPCs dont attack us?

**Comment by wargrimnir** [comment]
This appears to be an issue with the tethering system. Probably needs to check faction before dishing out the call for help function.

**Comment by Razielhell** [comment]
Got a blue bag and its empty(No weapon/gear).
![warhammer online age of reckoning 01 28 2017 - 10 51 54 165](https://cloud.githubusercontent.com/assets/16864486/22395464/e64870f0-e547-11e6-8761-ed12fecac32c.png)

**Comment by wargrimnir** [comment]
I didn't make blue/purple gear for Ch1
