### ISSUE TITLE
PQ Counters Major Issue

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#6935]
When you have **finished** X/X quests and still have to complete Y/Y kill,when you kill one Y mob, counter brokes and goes crazy.For example it may overcount kills and reset X or Y kills randomly, it just goes crazy and numbers in counter change randomly.Only way to fix it is to get out of the PQ area and get back in so the PQ UI refreshes but again if you try to kill Y mob it breaks with the first kill.

**Comment by Vayra** [comment]
In my experience this is only a visual issue and the PQ will progress fine when the stage is complete. Ie if you have a PQ that requires killing 30 each of two types of mobs and you get 30/30 on one mob and 15/30 on the other, the PQ will complete the stage when the counter says 45/30 and 15/30 or whatever the number ends up being when you've killed 30 of each.

**Comment by Soulwhisper** [comment]
Yeah it progresses normally...but Counter behaves really weird.

**Comment by Soulwhisper** [comment]
This is major issue and is happening at ALL PQs out there. I will upload a video to show you exactly.

**Comment by Soulwhisper** [comment]
https://www.youtube.com/watch?v=8a_SA5UZ_bA

**Comment by Yellowpillow** [comment]
may be related to #5517

**Comment by Soulwhisper** [comment]
Been playing with the bug.
You might wanna check this too.

**Comment by Razielhell** [comment]
This is fixed.
