### ISSUE TITLE
[kill task]  Fast Finds

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#6936]
talked to Golen in chaos chap4 and killed tons of spider but it's not enough ; has the kill task been implemented ?

**Comment by zak68** [comment]
how can a dok obtain the following item ?
Crow Caller Chain
+4 Toughness
+12 Weapon Skill
+104 Spiritual Resistance
+89 Elemental Resistance
+178 Corporeal Resistance

Crow Caller Chain (43k, 6.5k) Travel to Thunder Mountain and make your way to the coordinates given. Slay enough Magma Crawlers until you receive Arachnid Poison Sac (x5). After you receive these items, head to Altdorf and enter the Altdorf Library – second floor. Speak to the Library Assistant just across the Tome Accessory Librarian, Mandred Vogt, and purchase the Vial of Concentrated Venom in exchange for your five Arachnid Poison Sac(s). After you receive this item, equip this item as it is a Pocket item. Equipping this item will grant you the tome unlock, “Sacking for Sacs”, allowing you to claim Crow Caller Chain.

**Comment by Cpryt** [comment]
My apologies, as I am the creator of that thread. I have updated the thread and added the Destruction description:

> Crow Caller Chain: (43k, 6.5k) Travel to Thunder Mountain and make your way to the coordinates given. Slay enough Magma Crawlers until you receive Arachnid Poison Sac (x5).
> Order: After you receive these items, head to Altdorf and enter the Altdorf Library – second floor. Speak to the Library Assistant just across the Tome Accessory Librarian, Mandred Vogt, and purchase the Vial of Concentrated Venom in exchange for your five Arachnid Poison Sac(s). After you receive this item, equip this item as it is a Pocket item. Equipping this item will grant you the tome unlock, “Sacking for Sacs”, allowing you to claim Crow Caller Chain.
> Destruction: After you receive these items, head to The Inevitable City and enter the Lyceum. Speak to the Disciple's Assistant just by the Tome Accessory Librarian, Disciple Venomstung, and purchase the Vial of Concentrated Venom in exchange for your five Arachnid Poison Sac(s). After you receive this item, equip this item as it is a Pocket item. Equipping this item will grant you the tome unlock, “Sacking for Sacs”, allowing you to claim Crow Caller Chain.

You can also visit the thread: https://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=13566

**Comment by zak68** [comment]
Disciple Venomstung does not sell "Vial of Concentrated Venom"

**Comment by zak68** [comment]
problem solved; many thanks for your efforts !

**Comment by Lheana** [comment]
Just adding some information for this report:
This Bestiary unlock for Giant Spiders should be triggered:

- For Order, by killing 60 'Warpweb Spiders' and 'Warpweb Broodling' in Chrace in a large zone around 45.5k 42.7k. Then return to the Kill Collector, Elthossar Youngstar, in the Cliffs of Ushuru to complete the Kill Quest Toxic Shock

- For Destruction, by killing 60 'Scarlet Wolf Spiders' and 'Grey Wolf Spiders', in Nordland mainly around 48k 40k, to complete the quest for the Kill Collector, Golen, in Authun's Host (Chaos Chapter 4).
