### ISSUE TITLE
Raiders 'o Da Lost Waaagh! IV - Uncompletable

### ISSUE THREAD

**Issue by Cpryt** [WarEmu/WarBugs#6937]
Raiders 'o Da Lost Waaagh! IV
Undead Guardians slain - 5/5
Dig Site investigated - 0/1

The Dig Site objective is uncompletable. Clicking will not complete the quest. Please fix soon as we only have until 6/25/16 to complete this.

**Comment by Ktaan** [comment]
Did this stage like 1h ago, everything worked
