### ISSUE TITLE
[Howling Gorge] Mounting while carrying keg

### ISSUE THREAD

**Issue by Nekkma** [WarEmu/WarBugs#6939]
I noticed several instances of people mounting up while carrying the powder keg tonight in howling gorge. As seen in the screenshot the chosen is mounted up (check his buffs, he had the visual bug that does not show mount but i rode besides him so he was definitly mounted) while carrying the keg.
![nekkma_005](https://cloud.githubusercontent.com/assets/17377105/16280753/753e53a8-38c1-11e6-80c6-876a245994a9.jpg)

From patchnotes june 21: - Players attempting to mount or stealth while carrying powder keg will cause immediate detonation of powder keg.

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=18653
