### ISSUE TITLE
Flymaster: player trying to travel from Ekrund to Nordland falls somewhere near Mount Bloodhorn.

### ISSUE THREAD

**Issue by hidmann** [WarEmu/WarBugs#694]
Found: When the player is trying to fly from Ekrund to Nordland, the flight interrupts. Character falls somewhere near Mount Bloodhorn and becomes invisible and invulnerable.

STR:
1. Launch the client and log in.
2. Connect to battle with your character.
3. Relocate to Ekrund and find the flightmaster there.
4. Fly to Nordland.

Result: Flight from Ekrund to Nordland interrupts, character falls near Mount Bloodhorn and becomes invisible and invulnerable.

Expectation: Flight from Ekrund to Nordland delivers the character to Nordland.

Reproducibility: 100% via character Yyrkoon.

**Comment by Evildoor** [comment]
Closing per #639 .
