### ISSUE TITLE
Temple of Change - Public Quest Empire Chapter 11

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#6940]
~~On Stage 2 we couldnt find Monolith Destroyed so we didnt manage to progress on Stage 3 to finish the PQ.~~

**Comment by Razielhell** [comment]
- [ ] From Stage 2, one champion is missing. There are 7.

**Comment by grunbag** [comment]
Fixed in next patch

**Comment by thorbolt80** [comment]
Just test 
1) can't click on the monolith on stage 2.
2) doesn't count the kill of :" transform ritualist" 0/8  so I killed more than twenty with the repop...
