### ISSUE TITLE
[Quest] Cold Hard Steel

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#6943]
The Quest Cold Hard Steel from Chaos Chapter 11, has dyes as a reward, but does not seem to be repeatable. Were there only certain dyes quests that qualified for being repeatable?

**Comment by Ryanfawkez** [comment]
Nope, they should all be made repeatable. This one's repeatable for the next patch.

**Comment by CaptainoftheHarem** [comment]
Quick Question, if I have already completed a repeatable quest (before it was made repeatable), how do I get it again? I went to re-complete "To the Hunt" from chaos chapter 7 on a toon who had done it a while back, and it wasn't available for me as a repeatable quest.

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16037#p177201
