### ISSUE TITLE
[Monster] Duplicate Nosebiter

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#6944]
In this screenshot there are 3 visible Nosebiter, who is a named mob in troll country
![cristoria_004](https://cloud.githubusercontent.com/assets/13975292/16295619/8329851a-38ed-11e6-897c-b34b1a1af13f.jpg)

**Comment by DanaBloodkiss** [comment]
Fixed in next patch.

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16037#p177201
