### ISSUE TITLE
NOBILITY Quest

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#6949]
Issues:
- Quest discription says to kill Blighted Believer 0/1 and 0/10
- In quest we have to kill Blighted Believers who appear in second stage of the PQ. It's wrong. It should be changed to Blighted Mutants or put some Blighted Belivers in Stage 1.

**Comment by Soulwhisper** [comment]
It should be:

- Blighted Believer 0/10
- Blighted Robe 0/1
Also for the second part you said the PQ is wrong.See more here : #6950

**Comment by StaH84** [comment]
It's really wierd that You have to kill mobs in quest for second stage of PQ not for the first one.

**Comment by Lheana** [comment]
Fixed and set the quests like they are meant to be.

**Comment by sioding** [comment]
fixed with patch from 14.10.2018

**Comment by Fritomaster** [comment]
This is currently broke again.

**Comment by Fritomaster** [comment]
![image](https://user-images.githubusercontent.com/49774175/126262870-8c6c55bd-bc75-49bd-918d-624b52f7e08c.png)
Tested on two characters its no longer dropping the robe again.
