### ISSUE TITLE
"Raiders 'o Da Lost Waaagh! V"

### ISSUE THREAD

**Issue by Dainar-ru** [WarEmu/WarBugs#6951]
I can not get rewards for quest. I select rewards and see "Inventory owerflowing", but i have free slots in my backpack.
![ranulfur_011](https://cloud.githubusercontent.com/assets/20115206/16315399/2f970b24-3993-11e6-9e9d-fc8f3628f14d.jpg)

**Comment by Ryanfawkez** [comment]
Clear your crafting bad as well.

**Comment by Dainar-ru** [comment]
I have free slots in crafting bag too
![ranulfur_012](https://cloud.githubusercontent.com/assets/20115206/16315891/226399ca-3995-11e6-8751-d591b2dbfced.jpg)

**Comment by Dainar-ru** [comment]
I can not get my revards still. It is so sadly...
GMs, can you halp me?

**Comment by Dainar-ru** [comment]
![ranulfur_013](https://cloud.githubusercontent.com/assets/20115206/16356256/ed8533ae-3ae2-11e6-8ab3-4214cdf67272.jpg)
![ranulfur_014](https://cloud.githubusercontent.com/assets/20115206/16356257/f3cd118c-3ae2-11e6-89ed-1321a8b32ad0.jpg)
![ranulfur_015](https://cloud.githubusercontent.com/assets/20115206/16356258/f765d0c2-3ae2-11e6-95a7-65ec25afa422.jpg)
![ranulfur_016](https://cloud.githubusercontent.com/assets/20115206/16356259/f943e58c-3ae2-11e6-9bc0-158840def0ba.jpg)

**Comment by Magteridon** [comment]
you need  select 2 items  when select one no work need select 2 items  and complete

**Comment by Luth-RoR** [comment]
Can someone confirm if this was fixed with the latest patch too?
