### ISSUE TITLE
Quest : Slay it again, Sam Quest

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#6952]
- Looks as completed on NPC but its not.
  ![maxeras_021](https://cloud.githubusercontent.com/assets/16864486/16316528/a91105ee-398f-11e6-8fef-ea03a271ce8f.jpg)

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/5356

**Comment by Soulwhisper** [comment]
Yeah thats very general though. There are many quests with this kind of bug.

**Comment by Lheana** [comment]
#6952
