### ISSUE TITLE
The slayer Chronicles:Ending

### ISSUE THREAD

**Issue by arbich** [WarEmu/WarBugs#6955]
After asking a GM ingame, I post my probleme here.

Can´t finish the birthday quest. After the last step, when I try to get my rewards (Birthday Mantle and Birthday Token), I get the error message:
"Cannot salvage
Inventory overflowing
Open backpack to remove overflow"

Neither my inventory, nor my quest-inventory or my crafting-inventory is full, when I try to finish the quest.

I hope the time this quest is available will be extended ;-)

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=15031
