### ISSUE TITLE
CHAPTER 7 Empire - Knight of the Blazing Sun Influence Rewards

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#6960]
Issues:
- Again Charm as a Elite Reward for KotBS
- Advanced reward - Brassarts of Faithfull - with Willpower

**Comment by Ryanfawkez** [comment]
Item name for the charm please.

**Comment by StaH84** [comment]
I would give the name but the server was down:-(

**Comment by Luth-RoR** [comment]
Ah sry, was a mistake; i closed some others with the label.

**Comment by Zealote** [comment]
"Brassarts of the Faithful" do still have +4 willpower, but I can't see any charms for Knight's Ch. 7 inf rewards in any of the zones... that's just based on what the ToK's WAR Story tab says though. 

I have got SSs but would be a a bit of a mess to crop and paste them all here, easier if StaH84 could clarify if poss :P
