### ISSUE TITLE
Torment ring

### ISSUE THREAD

**Issue by Virn-Lifia** [WarEmu/WarBugs#6961]
Hello all,

I have a problem to validate Torment ring. Indeed, I have kill the skeleton named in Ostland to validate the success on my bestiary book. After I going to Cinderfall to see the three NPC skeleton (dwarf, human and elve) I click on. The NPC is activate (a little "bump") but I haven't their skull on my bag ; so I can't finish this task to take my Torment ring :'(.

Could you help me ? I have try four time, before and after reboot server, I have clean my book quest, I haven't another ideas :s

Regards.

**Comment by Ryanfawkez** [comment]
You need to pick up the quest in the library first to make the obtaining of these skulls validated. The quest rewards you with a pocket item that gives the unlock upon equipping.

**Comment by Virn-Lifia** [comment]
Thanks man perfect with the quest :)
