### ISSUE TITLE
[Melee-Combat] LoS by ganking someone on a 60% mount

### ISSUE THREAD

**Issue by Laktosefrei** [WarEmu/WarBugs#6963]
Hi,

melee player have a problem with ganking someone on a 60% ms mount. If the Ganker succsessfully dismount someone (on a 60% ms mount) the player cant do any melee-skills exept for the ranged ones (WH finisher etc.). 

The 60% movement speed mount causes this problem

**Comment by Luth-RoR** [comment]
High likely server-client lag and/or high-ping to low-ping compensation code.
