### ISSUE TITLE
BW Buffs not functioning correctly.

### ISSUE THREAD

**Issue by ChronoVarience** [WarEmu/WarBugs#6967]
_In a party_(6man or less), the Bright Wizard buffs Flame Shield and Flames of Rhuin do not appear to be functioning correctly; the buffs will buff the caster but not the other members of the party. Although this video does not demonstrate it, this does not appear to be the case in a warband.

Video: http://plays.tv/video/576d92a1c582edb044/flame-shield-flames-ruhin-doesnt-fire-in-group-group-recieves-no-buff

**Comment by Lileldys** [comment]
Are you sure those members are RvR flagged?

No need to post a pointless video...

**Comment by Soulwhisper** [comment]
OMG...video actually shows that it works perfectly fine.

**Comment by ChronoVarience** [comment]
@Soulwhisper  Look again, pay particular attention to the buff indicators in the HUD and on the party window, they don't match up with the buff indicator in the target window; furthermore, when the KOTBS switches from the primary target window(on the right) to the secondary target window(on the left) the buffs disappear. And then there is the player in question confirming the buffs didn't take.

@Lileldys  Yes, I am sure the party members are RvR flagged; I re-logged to that location after having been DC'd. I'm the one who is not RvR flagged and my understanding is that if you are not RvR flagged and you buff a player who is RvR flagged then you are supposed to immediately flag; this did not happen either.

**Comment by Soulwhisper** [comment]
Maybe because it cant handle all the buffs in the window.I never had problems with my BW buffs.You should start thinking of visual bug because of an addon(Disable all addons and try again).

**Comment by ozarmidrashim** [comment]
Did you not consider that if there really were a problem with FoR / FS, that it would have been reported before now? I mean, it's a very obvious bug.

**Comment by ChronoVarience** [comment]
ok, thank you for your time
