### ISSUE TITLE
Battlefield Objective NPC Buggs out

### ISSUE THREAD

**Issue by ChronoVarience** [WarEmu/WarBugs#6968]
Russenschellers Graveyard NPC Garrison of Skulls Prophet, bugs out and cannot be attacked w/ melee skills(?); moreover, _when this happens_, this NPC cannot be looted upon death.

Video:  http://plays.tv/video/576d9c707fbecaf67f/npc-buggs-out

**Comment by Lheana** [comment]
Closing as there are no longer guards at BOs.
