### ISSUE TITLE
Invalid NPC outside of Talabecland

### ISSUE THREAD

**Issue by vladopunk** [WarEmu/WarBugs#6969]
"Invalid NPC,pls report to GM, Guest ID 779, ObjLd=1591 0 of 1 "

An NPC givin a quest outside the camp in Talabecland. It said report so im reporting. :)

**Comment by Elvenalthur** [comment]
Got the name of the quest?

**Comment by Hargrim** [comment]
Quest name is Special Mix, missing NPC is Drugni Deepblade (ID 15919) and he is in Gunbad, so this is probably the reason why he is currently unavaliable.

**Comment by Lheana** [comment]
Quest now works.
