### ISSUE TITLE
Attempting to Loot with a Full Bag

### ISSUE THREAD

**Issue by coup1393** [WarEmu/WarBugs#697]
When attempting to loot with a full bag the player is sent a message in the chatbox that their bag is full. 
The Loot Window remains open, and when the player opens his bag, he may even drag and drop items from his bag to the background. 
The problem arises when the player can no longer loot the object. Pressing the "loot all" button does not work nor does drag and dropping nor double clicking the object.

**Comment by Evildoor** [comment]
I'm not quiet getting what does "when player can no longer loot" mean. You can kill a mob, see a loot, get a message about full bag, empty your inventory and then loot items. The only issue coming to my mind is that you can move away from the corpse, which will prevent you from looting, but that's logical, right?

**Comment by Evildoor** [comment]
No response, closing.
