### ISSUE TITLE
The Mysterious M.B. (quest) (dust covered Flask)

### ISSUE THREAD

**Issue by peusnaugrim** [WarEmu/WarBugs#6973]
The Mysterious M.B. :
Clickable item (dust covered Flask) in Order (blackmarsh inside the tunnel),  can't be clicked anymore  to give the achievement and the flask. The "dust covered flask" in now inside the wall few inch from original location and you can't clik on it.

**Comment by Ryanfawkez** [comment]
Seems fine on live right now.

**Comment by Luth-RoR** [comment]
There seems to be an issue with the quest, but closing this now as https://github.com/WarEmu/WarBugs/issues/7428 has a screenshot.
