### ISSUE TITLE
Dying in Howling Gorge while holding the keg prevents you from using mount

### ISSUE THREAD

**Issue by Marchmain** [WarEmu/WarBugs#6975]
If you are killed while holding the keg in Howling Gorge you are unable to use your mount again. Sometimes it is fixed after your next death but I have had games where I was unable to use my mount for the entire game even after multiple deaths.

**Comment by Luth-RoR** [comment]
Stealth doesn't work too according to https://github.com/WarEmu/WarBugs/issues/9370
>When one then plays a class WH / WE you can not go to the whole scenario in stealth.

**Comment by Kaelang** [comment]
Tested - was able to mount post-death whilst holding the objective.
