### ISSUE TITLE
same issue as Equipment bug #6535 

### ISSUE THREAD

**Issue by Zuyanna** [WarEmu/WarBugs#6981]
armscales only that I saw though this time.  screenshot taken a few days ago, but issue persists

![dyami_004](https://cloud.githubusercontent.com/assets/19364515/16360026/6e6449fc-3b19-11e6-9d78-e5eebdedf28f.jpg)

**Comment by Vayra** [comment]
This issue applies to ALL the Fighter's XXX of Vengeance items for DoK.

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16037#p177201
