### ISSUE TITLE
Siege weapons cannot be reclaimed by owner

### ISSUE THREAD

**Issue by huntergregg2** [WarEmu/WarBugs#6984]
Today, 6/26/16 at 2:35AM Pacific Time, a dwarf character named Begs stole me siege during a keep defense in Eataine. I was not only unable to reclaim it, on my mount or off, but he repeatedly ran away from me unmounted and towing my siege and I was unable to claim it back. He further taunted my group mate 

I'll file a separate report against the player, but the fact is that this is the second time someone in my guild has purchased siege and had it stolen since the patch went live which allowed siege to be towed. 

This is clearly an issue as I paid for the siege and dropped the siege, and another character was able to man my siege and take off with it, thus I lost the gold to purchase it as well.

**Comment by Soulwhisper** [comment]
I doubt that he was unmounted while running away from you and towing your weapon at the same time.Probaply he was mounted(and visual bug). #6934 is this what you mean? If yes close the ticket please.
