### ISSUE TITLE
PQ Nordland 'Norses are coming!' some 'Norse Sea Dog' are spawned on each others, with 'Norse Plunderer' and 'Hralgar the Kraken' being naked chaos humans

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#6986]

**Comment by Soulwhisper** [comment]
Stage 3 is not correct.You should protect the Sea Watch...from Invaders coming(In multiple waves 4 or 5 in total)from the sea with their boats.On live you could actually see the boats coming from distance and then Invaders spawning on the coast and heading all the way up to the Sea Watch.

**Comment by Soulwhisper** [comment]
Nurse plurenders are Champions guys.You fixed models too from dwarfs to Nurse but they are 5-6 level champions.

**Comment by Soulwhisper** [comment]
This one needs to be closed.I will update in new ticket with latest patch soon.
