### ISSUE TITLE
i Want dire shield working 

### ISSUE THREAD

**Issue by jonyjones** [WarEmu/WarBugs#6989]
I m pretty sure near all important order ability is working, and this is important ability. I wait you ask for proof even if i feel most order ticket aren't asked

**Comment by taccr** [comment]
a.) read the bugtracker rules
b.) the tactic is horrible
c.) https://github.com/WarEmu/WarBugs/issues/6970

**Comment by ozarmidrashim** [comment]
It already works, you idiot.

**Comment by taccr** [comment]
Dude stop it, you a literally wasting everyones time here. Grow up and respect the rules.

**Comment by jonyjones** [comment]
I planned to stop it but i have to answer you reaction. you started by naking me having to track and make myself 2 post (in addition of the 3 others that were already existing) and search each time you reaction. I cant grow up more but i can teach you why rule are made by dominant so they can use them when they need and avoid them if not. I hope you get that i never insult without reason and it wastnt intended to you. But who live by the sword , ...

ps if you want waste more time you should ask about rule. I m very interested in that. I always laugh at ppl that remain the law, break the one of nature and turn around on theirselves like how is it happening to me.

**Comment by ozarmidrashim** [comment]
I warned you.

**Comment by jonyjones** [comment]
thanks you but for what?
