### ISSUE TITLE
Item: Crusher of Entropy

### ISSUE THREAD

**Issue by roadkillrobin** [WarEmu/WarBugs#6992]
This is a old weapon i picked up on on a character probobly around 5months ago. 
But the dps seems way out of proportion to the lvl requirement. 

![highdps](https://cloud.githubusercontent.com/assets/16356956/16364551/49f27270-3bea-11e6-8475-38eb9357cb6f.jpg)

**Comment by Ryanfawkez** [comment]
All one-handed of Entropy weapons have this DPS value.
