### ISSUE TITLE
cant turn in Repentance

### ISSUE THREAD

**Issue by runebbb** [WarEmu/WarBugs#6997]
tier 2 warcamp cant turn in quest of killing hugo von pritte destrucion in ostland to agnarr crowbane

**Comment by DanaBloodkiss** [comment]
Can't find any bug. Reloaded the quest finisher though in the database.

**Comment by Soulwhisper** [comment]
**8/22/2016**
Still buggy.Cant turn it in NPC named Agnarr Crowbane.

**Comment by Luth-RoR** [comment]
K, reopened then.

**Comment by runebbb** [comment]
it works on some talismans but on others dosent i know it dosent work on int talismans

**Comment by Soulwhisper** [comment]
Willpower Talismans work.

**Comment by Nekronsieben** [comment]
Streng Talismans work.
Intelligence Talismans dont work.
Toughness Talismans dont work.

**Comment by Thameno** [comment]
Got the Same with the Quests "Repentance" & " Desire for Corruption can't redeem by me.  Even when I choose a talisman, nothing will happen. The other Quest won't appear.

**Comment by sioding** [comment]
fixed with patch from 05.11.2018
