### ISSUE TITLE
Scenarios Don't End Due to Huge Population Imbalance

### ISSUE THREAD

**Issue by Liandel** [WarEmu/WarBugs#6998]
Scenarios don't seem to factor in the population of both sides and end due to population imbalances. I was just in a five minute scenario where order only had three PUGs versus a full premade plus additional PUGs. Not once did I get the notification that it would end due to imbalance. Not sure if intended or not. 
![liandel_007](https://cloud.githubusercontent.com/assets/19737935/16366112/bbc21c76-3bc6-11e6-9a51-baf4c5dd2a2d.jpg)

**Comment by Krazis** [comment]
I believe that function is not implemented yet. By sheer chance, the initial individuals maybe have hit, "give me a minute" then canceled, leading to the que system to try to find others and failing.

**Comment by ozarmidrashim** [comment]
Bugtracker not intended for features that are not implemented
