### ISSUE TITLE
T2 Keep Lord bug "null exception"

### ISSUE THREAD

**Issue by Sayce78** [WarEmu/WarBugs#6999]
Killed Keep Lord in Shadowlands, received "null exception" error that said something about this object being destroyed. Keep did not change from destroy to order (order killed Keep Lord); destro NPCs started respawning. Allegedly, this also happened to destro in Ellyrion keep owned by order.

Possibly related: #5841, #5819

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
