### ISSUE TITLE
cant activate my account

### ISSUE THREAD

**Issue by anabiosis23** [WarEmu/WarBugs#700]
Hi, cant activate my account ( 500 Internal Server Error )

**Comment by Bitz95** [comment]
I can't activate my account too. I got the activation link and it showed me 500 internal server error.

**Comment by AgentAgent** [comment]
Same problem here

**Comment by Decay57** [comment]
Same problem. I ran into the 500 Internal Error when I submitted my registration on the site. I received the registration email anyway and get that same 500 error when trying to use the account verification link in the email.

**Comment by MaxHayman** [comment]
It should be fixed now.

On 14 April 2015 at 16:34, Decay57 <notifications@github.com> wrote:

> Same problem. I ran into the 500 Internal Error when I submitted my
> registration on the site. I received the registration email anyway and get
> that same 500 error when trying to use the account verification link in the
> email.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WarEmu/WarBugs/issues/700#issuecomment-92912857>.
>



-- 
Thanks,

Max Hayman

**Comment by Decay57** [comment]
That it is. Was just ale to log in. Thanks!

**Comment by Bitz95** [comment]
Thank you! Link worked this morning.
