### ISSUE TITLE
Item: Disconcordant Trollsmasher

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#7002]
http://i.imgur.com/cAg3eSI.png
Retribution, the R36 epic weapon. For reference.

http://i.imgur.com/fYPiWXB.png
Disconcordant Trollsmasher, R27 rare weapon with probably too much DPS

**Comment by Torquemadra** [comment]
t3 epic weapons were introduced as such to maintain relevance when the cap was t3 but lvl 35, they will be readjusted in due course.
