### ISSUE TITLE
Altar of the Bloodbane PQ

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7004]
-  Stage One: Kills do not register in the counter.

Close #5522 please Ryan or someone.

**Comment by Ryanfawkez** [comment]
So you've knowingly made a bugtracker report for an issue already reported? I'm sorry, but recent tickets for old issues will be referred to and closed.

**Comment by Ryanfawkez** [comment]
https://github.com/WarEmu/WarBugs/issues/5522

**Comment by Soulwhisper** [comment]
Evildoor left.Thats why i created a new one.Nevermind.
