### ISSUE TITLE
Ulfenwyr PQ

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7005]
- [x] Stage 1 doesnt count kills.

**Comment by Soulwhisper** [comment]
PQ implemented and is fully working.
- [ ] Several Bilerot Scavenger double spawns in Stage 1

**Comment by Soulwhisper** [comment]
#8935

**Comment by Razielhell** [comment]
I think this is diferrent...
![warhammer online age of reckoning 01 24 2017 - 14 24 02 01](https://cloud.githubusercontent.com/assets/16864486/22247149/f1f92746-e240-11e6-8836-5b406949c3a9.png)

**Comment by Razielhell** [comment]
#8935

**Comment by Razielhell** [comment]
Also in blue bag there is a ring for WL but i doubt that it should be 1str & 10willpower.
Probably 10str & 1willpower?
![warhammer online age of reckoning 01 24 2017 - 14 59 45 04](https://cloud.githubusercontent.com/assets/16864486/22248203/25943b04-e246-11e6-84cf-5dc96b220ad9.png)

**Comment by wargrimnir** [comment]
This was changed to Wounds instead of Willpower
