### ISSUE TITLE
Pit of the Forsaken PQ - Empire Chapter 3

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7006]
~~\- Stage 1 doesnt count kills~~

**Comment by Soulwhisper** [comment]
8/8/2016
RyanMakara

Added functionality for the following PQs:
- Pit of the Forsaken (Order chapter 4 Empire hard PQ)

**Comment by Soulwhisper** [comment]
Everything works great except Stage 2 where Knights(Champions) spawn twice.

**Comment by saupreusse** [comment]
RYYYYAAAAAN - you messed up the spawns again.

**Comment by Soulwhisper** [comment]
IIRC you can finish it...! :) Just double spawns.

**Comment by avenflar** [comment]
Yeah but it's hard as hell

**Comment by Soulwhisper** [comment]
https://www.youtube.com/watch?v=ffpMF0bYL2E
2:29:25 @Ryanfawkez Hahahaha...

**Comment by wargrimnir** [comment]
Removed duplicate spawns.
