### ISSUE TITLE
Closed Warband Invite Bug

### ISSUE THREAD

**Issue by fiazco** [WarEmu/WarBugs#7013]
Hey,

seems like there is some bug after the patch/login server prob with closed Warbands. 

People who get invited and accept the invite actually dont join the WB and cant join any open wb/party afterwards.

Relog fix the bug for open wbs/closed partys but once you try to create a wb its the same bug all over again.

**Comment by Tholkienn** [comment]
Sae for us, we do some full grp... hard for view all..

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16037#p177201
