### ISSUE TITLE
Howling Gorge Mounting bug

### ISSUE THREAD

**Issue by zigzur** [WarEmu/WarBugs#7017]
Hi just played Howling Gorge and got killed by the bomb wean i was carrying it, respawn and mounted but my mount didnt show up so i was running realy fast and could not dissmount or be dissmounted. i pick up bomb and fight like i was not mounted

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/6939

**Comment by Zealote** [comment]
I think #6939 is different isn't it?

That one's just the usual bug --that affects everyone-- where you can pick up bomb (or salvage/artifact/bauble) and can then still summon your mount. Whereas this sounds like a rarer/more unique issue (hasn't happened to me at least) related to dying while holding the bomb, where the OP got stuck in mounted state (sounds like it even persisted in combat).

Looks like the exact opposite of #6975, but prob more closely related(?)

**Comment by Luth-RoR** [comment]
Both issues have probably the same root.
I'm not sure what
>fight like i was not mounted
