### ISSUE TITLE
Aspis of the Waaagh missing talisman slot

### ISSUE THREAD

**Issue by Zumos** [WarEmu/WarBugs#7018]
Aspis of the Waaagh, the black guard shield from the epic quest Time to Waaagh! misses its talisman slot.

![dispatched_004](https://cloud.githubusercontent.com/assets/19267650/16464955/d1c89ee6-3e3c-11e6-9471-a62722920229.jpg)

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16037#p177201
