### ISSUE TITLE
"/stuck" command in scenarios

### ISSUE THREAD

**Issue by t5p1ny** [WarEmu/WarBugs#702]
Just reporting what happened to me after using the "/reload" command to bring up the ressurrect window in a scenario (gates of ekrund specifically) and finally using the "/stuck" command after quitting due to the insuccess in doing so. once loaded into nordland/norsca the objective tracker was displaying this way:

![heimghaal_000](https://cloud.githubusercontent.com/assets/11949313/7145247/bf6033e2-e2e2-11e4-9217-a68288dc16b2.jpg)

**Comment by Evildoor** [comment]
Stuck was reworked. Also, you can log back into scenarios now.
