### ISSUE TITLE
House Arkaneth PQ 

### ISSUE THREAD

**Issue by twyxxy** [WarEmu/WarBugs#7020]
No mobs give influence upon killing, mobs do not count at all towards the PQ. 

![](http://i.imgur.com/JmkbdXY.jpg)

**Comment by Damiel126** [comment]
This is the case for all High Elf and Dark Elf PQs in T1 at present.

**Comment by saupreusse** [comment]
should it be aktive already?
I dont know if anyone has worked on it yet...

**Comment by Paleolog77** [comment]
confirm, elf t1 pqs still don't work

**Comment by wargrimnir** [comment]
Fixed in next
