### ISSUE TITLE
Marauder Lair Items Wrong Stats

### ISSUE THREAD

**Issue by Lindisfarne** [WarEmu/WarBugs#7022]
I found two lair items (Metoh's Direhelm and Tramplers Of The Direwolf) for marauder that have +block on them, and im pretty sure its supposed to be parry. I'm not sure if theres any other mara items that have block as well, but 2 of 3 i found did. 

![northernrage_003](https://cloud.githubusercontent.com/assets/7563181/16488456/a94f5290-3e9e-11e6-8cc4-471b6c1ee047.jpg)
![northernrage_004](https://cloud.githubusercontent.com/assets/7563181/16488457/a951775a-3e9e-11e6-8882-d6efbf47d337.jpg)

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16037#p177201
