### ISSUE TITLE
[Guilds] Toons missing 

### ISSUE THREAD

**Issue by Halhammer** [WarEmu/WarBugs#7025]
So after servers were back on earlier our guild now has 29 members instead of 75 before...
From what I can tell the missing toons are somehow connected with certain accounts, i.e. mains and alts of certain people are gone, others are still there (like mine)

**Comment by geezereur** [comment]
My guild is also gone on both Destro and Order side.

**Comment by Halhammer** [comment]
nvm just saw Elven's post on forums
