### ISSUE TITLE
Tome of Knowledge, Armory: Tier 1 Obliterator Chest Piece

### ISSUE THREAD

**Issue by joneswaronline** [WarEmu/WarBugs#7027]
In the Tome of Knowledge, Armory, under the Tier 1 Armor Sets, the game is not recognizing when I put on the Obliterator Chest Piece. It is not giving credit for it. See picture
![graved_009](https://cloud.githubusercontent.com/assets/19896303/16509170/a9dd0e8a-3ee6-11e6-976c-d92eb276b1f0.jpg)

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16037#p177201
