### ISSUE TITLE
Guild

### ISSUE THREAD

**Issue by KatsuraKo** [WarEmu/WarBugs#7028]
After yesterday crash server I disappeared my guild. Can you reestablish it? Guild name Across, lvl half past five

**Comment by Luth-RoR** [comment]
Not a bug, common issue atm.
DB server loading is to slow.

**Comment by KatsuraKo** [comment]
Thank you for answer, how much time need to fix that?

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=15127&p=164516#p164516
