### ISSUE TITLE
Sorc stuck "in combat" more frequently than other classes

### ISSUE THREAD

**Issue by Harnag** [WarEmu/WarBugs#703]
Similar to ticket #644 but not the same:  Sorcerer class gives off "damage" at times long after they have stopped fighting, and also before they begin fighting in a scenario.  Thus you sometimes see Sorcerers having done significant "damage" in a scenario before any fighting has commenced.  I also see damage numbers still floating up in my screen long after a scenario has ended and I have not engaged in any combat.  Then a scenario pops and I cannot join because the system thinks I am "in combat."  I believe it is this phantom "damage" with sorcerers that prevents them, more than other classes, from being able to enter scenarios because they are "in combat."  Fixing this phantom damage may solve the problem for Sorcerers (and possibly BW) from being stuck "in combat" so often.
- Gephank

**Comment by Gnashspike** [comment]
Hey Gephank,
I believe the Frozen Touch buff is responsible for this; the players you buffed with that spell are damaging 'something' and the Frozen Touch is proccing, but using YOU as the recipient of the proc, not the buffed player doing the damage. That seems like it would account for the "extra damage" sorcs achieve in SCs as well. Keep in mind, I'm just guessing. As Icy (my GF) plays, I watch this happen to her over and over. It's incredibly frustrating for her, and I imagine all sorcs. Only relogging (or NEVER using Frozen Touch, which is kind of ridiculous) remedies this bug.

Hope you can get the Devs to deal with this crappy bug. My heart goes out to ya mate.

Good Hunting,
Gnashspike Rhaylphist
