### ISSUE TITLE
DISCIPLE OF KHAINE Essence Lash Ability

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#7030]
Issue:
- Ability should give 45 Essence on attack + additional 15 for every enemy hit. It gives essence only upon hitting the enemies. Or was it intended change?

**Comment by Luth-RoR** [comment]
This was changed/fixed by mythic in one of the later patches. 
Career resource points are only restored when enemies are actually hit by the ability, not by using it.
