### ISSUE TITLE
"Bountyman Lipschultz" using my horse?

### ISSUE THREAD

**Issue by rolloman** [WarEmu/WarBugs#7031]
i found it hillarious and diddnt hinder me in any way but it was a visual bug non the less

![nackskott_006](https://cloud.githubusercontent.com/assets/20053193/16535492/f4fc8da8-3fe7-11e6-9d24-b263eac2fdf4.jpg)

**Comment by Luth-RoR** [comment]
DB devs can give NPCs mounts. 
#artisticfreedom
Not a bug.

**Comment by rolloman** [comment]
even my mount? because im on it aswell

**Comment by Luth-RoR** [comment]
I can only see the NPC on the mount on this picture.

**Comment by rolloman** [comment]
found a better screenshot
![nackskott_000](https://cloud.githubusercontent.com/assets/20053193/16535856/4e845c72-3feb-11e6-9365-d45e75a400a5.jpg)

if its not a bug but a prank from a GM then i gotta thank them for the good laught :P

**Comment by Luth-RoR** [comment]
I see thx, maybe related to the DB loading to slow/incomplete atm. 
There are lots of database related problems atm. Should be gone if the DB loading is fixed (few days hopefully). Please report back if the issue still persists.

**Comment by rolloman** [comment]
okay will do! ty for quick response :)
