### ISSUE TITLE
Serpent's Passage cap double credit

### ISSUE THREAD

**Issue by grant-musick** [WarEmu/WarBugs#7032]
When capping the salvage in SP, if you start the cap then move after the 1 second mark then start the cap again you get credit for two caps. I was able to reproduce this twice.

**Comment by Luth-RoR** [comment]
Closing this, as https://github.com/WarEmu/WarBugs/issues/7783 has additional info.

**Comment by Gobtar** [comment]
Someone did this in a SC up to 4 times in one go. Replicated once in SC before coming here to write a report.
