### ISSUE TITLE
NPC 'Yergwan the Brave' is spawned twice in Norsca

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#7033]

**Comment by avenflar** [comment]
Update : He's spawned thrice

**Comment by Luth-RoR** [comment]
Coordinates:
https://github.com/WarEmu/WarBugs/issues/98

**Comment by Hargrim** [comment]
Corrected, fixed in next patch.

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16037
