### ISSUE TITLE
NPC Captain Alerios is spawned twice in Chrace

### ISSUE THREAD

**Issue by Damiel126** [WarEmu/WarBugs#7034]
In the Sea Guard camp just north of Lionhome in Chrace, there's a group of champions with a hero named Captain Alerios. He actually has two spawns in this area instead of one.
![licksitbetta_030](https://cloud.githubusercontent.com/assets/10399547/16538444/f83ddd02-4067-11e6-940a-5dc6a0b7d24a.jpg)
![licksitbetta_031](https://cloud.githubusercontent.com/assets/10399547/16538445/fdd2cf5c-4067-11e6-96b9-8a639e711977.jpg)

**Comment by sioding** [comment]
fixed with patch from 24.02.2018
