### ISSUE TITLE
Disrupt Skill

### ISSUE THREAD

**Issue by WJamesLord** [WarEmu/WarBugs#7035]
Some pieces of Mercenary gear have a "Disrupt Skill" attribute.  This attribute apparently does nothing - it doesn't increase your ability to disrupt spells nor does it reduce your spell's chance to be disrupted (from what I can ascertain).  Please change the Disrupt Skill to Disrupt.

**Comment by Ryanfawkez** [comment]
Please include the specific item names so we can check and fix them on an individual basis.

**Comment by WJamesLord** [comment]
The Zealot Cowl of the Mercenary is effected by the Disrupt Skill issue, but I believe there may be a few others Mercenary items effected as well.  I recall a DoK item on the live servers had the same issue.  I have attached a screen shot to aid in tracking down this issue.  Thanks much for your help!
![cowl issue](https://cloud.githubusercontent.com/assets/2352429/16541562/5aeabf92-4054-11e6-80de-3b57e99c9a03.png)

**Comment by Luth-RoR** [comment]
I guess you closed this accidently.
