### ISSUE TITLE
DISCIPLE OF KHAINE Essence Lash Ability

### ISSUE THREAD

**Issue by StaH84** [WarEmu/WarBugs#7036]
Issue:
- Ability should build 45 essence on use and additional 15 per enemy hit. Now it gives only 15 per enemy hit.

**Comment by Zealote** [comment]
Your original one's still here: https://github.com/WarEmu/WarBugs/issues/7030

**Comment by Luth-RoR** [comment]
Yes, you can still post in closed reports. But this one is more clear now, thx.

**Comment by Luth-RoR** [comment]
As there are wrong tooltips on the client we need further confirmation if the tooltip is wrong/outdated or just the wording in the mythic patchnotes: 

_Essence Lash: This ability will now deal damage in a large radius in front of the target. For each enemy hit, you will regain 15 Soul Essence points. You will no longer receive Soul Essence upon activation alone._
https://web.archive.org/web/20131227093330/http://www.warhammeronline.com/article/Game-Update-141-0301

**Comment by StaH84** [comment]
Oh boy, sorry. I thought previous report didn't come in - disapperared real fast. Tooltip in game DOESN'T show "Builds 45 Soul Essence" so it's ok. Ignore this report too. Sorry for commotion.
