### ISSUE TITLE
Quest : By Torchlight, Order, Bloodhorn.

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#7037]
There are no way to destroy the 2 watchtowers. You are supposed to use a torch looted on an 'Ironclaw Watchas'

**Comment by sioding** [comment]
**Thanks for the report.** Since there is no confirmation, i will close this issue now. You can help us by following the bugtracker rules which you can find here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
