### ISSUE TITLE
Durak's Legacy, Quest Order Bloodhorn.

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#7038]
It's one of the lasts step of the quest chain I believe. You have to recover an oathstone from 'Traitor's Watch'. Clicking on the 'Loot Chest' doesn't complete the quest.

**Comment by avenflar** [comment]
okay, I actually found the correct chest, the 'Secured chest', lost on a beach in 38k 9k. I believe its location should be where the 'Loot Chest' is actually.

**Comment by Ryanfawkez** [comment]
Moved Loot Chest to the quest marker location. It will now give Durak's Oathstone, which will have to be right clicked to progress the quest.

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16037
