### ISSUE TITLE
Crashing to desktop upon Login

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#7040]
Whenever I try to log on my slayer (Tackyshorts, level 20, located in Altdorf) it completes the loading screen, and then it crashes to desktop. I have tested all of my other 16 characters having only one other crash, but on the second try I had it work. I was able to have the occur 3 times.

**Comment by Luth-RoR** [comment]
Type /stuck and hit enter and again /stuck and hit enter (2x) while at the loading screen.
