### ISSUE TITLE
Everyone is Guild leader bug 2

### ISSUE THREAD

**Issue by Partizan-Rusi** [WarEmu/WarBugs#7042]
Everyone is Guild leader bug again.
Older bug - https://github.com/WarEmu/WarBugs/issues/5607

I have same problem with guild roster. 
After ddos and database offline time almost everyone became guild leader - http://i.imgur.com/KADs7LO.jpg
Hopefully you can fix this nasty bug and restore my guild to previous state, before ddos.
Obviously I need guild leadership set only to my character - Partizan, who was original founder of the guild and g.l. all this time.

Also I lost almost all the people from roster who joined my guild recently.

**Comment by Luth-RoR** [comment]
Needs to be fixed by someone with DB access.

**Comment by Partizan-Rusi** [comment]
I wonder if my guild is the only one with this crap. People telling guilds was fixed and maybe something gone wrong.

**Comment by Luth-RoR** [comment]
If your order and destro guilds have been created more recently, they are high likely lost as the backup was an older one.

**Comment by geezereur** [comment]
They are old Guilds way before may 5th.
