### ISSUE TITLE
Seer Thaena in Norsca - Player Name Incorrect in Conversation

### ISSUE THREAD

**Issue by LordTercept** [WarEmu/WarBugs#7043]
http://imgur.com/shGEjJl

When you speak to the NPC you see "there is a path for you [Name]", this should be pulling the player's character name I believe.

**Comment by saupreusse** [comment]
Fixed in the next patch.

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16037

**Comment by Tuffskin** [comment]
Still bugged

![image](https://cloud.githubusercontent.com/assets/21177769/18024524/9a0fbd60-6bda-11e6-8736-fa62a7d06959.png)

**Comment by Ryanfawkez** [comment]
Fixed now with a reformed name/career/race command in creature_texts.

**Comment by sioding** [comment]
Checked - works fine
