### ISSUE TITLE
I haven't been able to complete any PQ

### ISSUE THREAD

**Issue by dbsimon88** [WarEmu/WarBugs#7044]
Every PQ I've tried to partake in hasn't shown me how many mobs have been slain and it  isn't updating the stage at all no matter how many I kill.  I've counted greater slain than the required amount to make sure. It only almost seemed to work when someone else is doing the quest and I re-enter the zone for the PQ, that seems to update the npcs slain. (Had this problem with every PQ I'm level 13 this is my first char. Frustrating haha I want loot! :/ )

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/6883

**Comment by Luth-RoR** [comment]
Watch the chatwindow for PQ progression, there is a message. Hard PQs need oftern a huge amount of NPCs.

**Comment by dbsimon88** [comment]
I am watching the chat window and there is no quest acknowledgement.

**Comment by Luth-RoR** [comment]
Ok, it was removed as it seems. The PQ window works for me though:

**Comment by dbsimon88** [comment]
So what can I do? :/ any suggestions to fix it? I've asked other new
players and they are just as clueless about it. Maybe you should reconsider
closing this bug topic.

PQ are such a big part of the game and if I'm not experiencing it likely
others are too.

Thanks,
Dave

**Comment by Luth-RoR** [comment]
It was closed because there exists another report about it yet: https://github.com/WarEmu/WarBugs/issues/6883

**Comment by dbsimon88** [comment]
The previous person reported it for a particular quest. So can still
receive a bug report tolken? The speed of my new mount will dry my tears
from not being able to participate in an PQs

Haha I'll be quiet now. I know everybody is working as hard as they can,
I'm just happy to be able to play this game again.

Be well,
David
