### ISSUE TITLE
MoM, NPC 'Black Skull Meanie' attack their 'Captured Dwarf'

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#7050]

**Comment by Torquemadra** [comment]
They dont like him, not fixable at this stage.

**Comment by avenflar** [comment]
You can't set a different flag for them?

**Comment by Ryanfawkez** [comment]
We could, but that one flag that would make them unattackable would also allow Order to attack them. Sorta breaks the immersion if both factions are able to kill a captured enemy/friendly (war crimes, ect)
