### ISSUE TITLE
Guild leader bug 

### ISSUE THREAD

**Issue by Teinhala** [WarEmu/WarBugs#7055]
Fix guild pls, half part of members become a guild leader =/
http://i.imgur.com/ULl3mYS.jpg
http://i.imgur.com/vW8AoNu.jpg

Guild name - Don't Panic
Guild leader - Teinhala

**Comment by Gintofag** [comment]
I think this made for save u guild from disappearance.

**Comment by Ryanfawkez** [comment]
https://github.com/WarEmu/WarBugs/issues/7042
