### ISSUE TITLE
Zone 0 from flight master

### ISSUE THREAD

**Issue by ylyandra** [WarEmu/WarBugs#7058]
I do not have a screen shot and it has only happened once last night. I attempted to take the flight master from riekland to TM and ended up in Zone 0 basically in mid space. Used book to get to IC from there but I thought i would let you know about it

Incident occurred on magus Ylly

**Comment by Luth-RoR** [comment]
This is a very old bug that only happens rarely nowadays.

**Comment by Sayce78** [comment]
This happened to me as well just now - going to the flight master in Altdorf but ended up in Zone 0. I was walking toward flight master and had not clicked on him yet to select a destination. I used my book to get out.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/6831
