### ISSUE TITLE
Various Objects Display Buffs They Do Not Have

### ISSUE THREAD

**Issue by LordTercept** [WarEmu/WarBugs#7059]
Come across a number of world objects that when you highlight them display all kinds of buffs they obviously don't have.  See screen shots:

http://imgur.com/q5gTabf
http://imgur.com/Lt0KYb5

Ordinance objects display this as well.  Seems to be inanimate objects mainly, although a "Cowering Citizen" in Nordland exhibited the same problem for me.

**Comment by Soulwhisper** [comment]
Its an addon issue.Try disabling first those addons which are yellow.For me problem was Deathblow.

**Comment by Luth-RoR** [comment]
Thx, closed then.

**Comment by LordTercept** [comment]
Thanks for the info, sorry I'm new to the game and don't have hardly any addons.  It was indeed Deathblow.  I'll make sure I check those things next time.
