### ISSUE TITLE
Can't log into the game.

### ISSUE THREAD

**Issue by Bistt** [WarEmu/WarBugs#7060]
Good afternoon. Play from Russia.
When I first installed it, everything worked. Evenings when you run the Launcher web server shows red and the connect button is not active. How to fix and start playing?

Добрый день. Играю из России.
Когда первый раз установил, все работало. Вечеров при запуске Launcher показывает web server  красным и кнопка connect не активна. Как исправить и начать играть?

**Comment by Luth-RoR** [comment]
Hi,
the launcher works fine. For support please use the support forum: https://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=2889
Also check if the server is really up when you can't connect.
