### ISSUE TITLE
Emp ch 7 KoTBS wrong reward

### ISSUE THREAD

**Issue by Gintofag** [WarEmu/WarBugs#7061]
![bug1](https://cloud.githubusercontent.com/assets/20201317/16552289/9ae4db4e-41e1-11e6-8f17-d956e0fee6ac.png)
Wrong reward for KoTBS in chapter 7 empire.

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16037#p177201
