### ISSUE TITLE
Item without model: Squire's Greaves

### ISSUE THREAD

**Issue by Gintofag** [WarEmu/WarBugs#7062]
![gintoki_003](https://cloud.githubusercontent.com/assets/20201317/16556285/02392b60-41fb-11e6-949e-3159482378cc.jpg)
This item has no ingame model and don't displayed on character.

**Comment by Gintofag** [comment]
Also i think another reward from this quest have some trouble.

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16037#p177201
