### ISSUE TITLE
Naked dead characters

### ISSUE THREAD

**Issue by Ziggesmuts** [WarEmu/WarBugs#7063]
When I log in chars is naked and dead all items gone and text says:KeyNotFoundException thrown from build guild

**Comment by Luth-RoR** [comment]
There is a general issue with guilds atm. I link your issue here: https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=15164

**Comment by Luth-RoR** [comment]
It would be helpful to know your character and guild name.
