### ISSUE TITLE
Quest "Trick of the trrade" uncompletable.

### ISSUE THREAD

**Issue by ShanellRoR** [WarEmu/WarBugs#7066]
![kastul_061](https://cloud.githubusercontent.com/assets/17355822/16562701/f141decc-4206-11e6-94ca-1d6670b6a3d7.jpg)
So, as far as I remeber this NPC needs to be killed to obtain head. But it's to killable, as well as other prisoners.

**Comment by Hargrim** [comment]
Looking into this.

**Comment by Hargrim** [comment]
Corrected NPC faction, fixed in next patch.

**Comment by ShanellRoR** [comment]
Thanks!

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16037
