### ISSUE TITLE
Champion of Tzeentch is being killed by two acolites of the same God.

### ISSUE THREAD

**Issue by ShanellRoR** [WarEmu/WarBugs#7068]
![kastul_062](https://cloud.githubusercontent.com/assets/17355822/16565560/c9cbf980-4216-11e6-9293-5e2ebacf2b75.jpg)
I am not sure if it is a bug, but Tzeentch acolites are killing aspiring champion os their God. Cave CW 12.7k 60k

**Comment by Hargrim** [comment]
Faction corrected, fixed in next patch.

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16037
