### ISSUE TITLE
Zealot Daemon Spittle/Sweeping Disgorgement tact and resists/mitigations bug 

### ISSUE THREAD

**Issue by Kweedko** [WarEmu/WarBugs#7069]
I can't tell about all classes hve the same problem but zealot got it i hit plaer wit 25% resists and he mits almost 50% and daemon spittle debuff on resists sweeping disgorgement don't apply on skill itself but Daemon Spittle is corpreal damage and debuff seems not aplying right cause after debuff a player hits become harder but not hard enough on with my buddy sw we tested after debuff he got 5% resists but still mits almost 35% but he got only 25% rez before the debuff, something completely broken here maybe for all classes maybe only for zeal.

and here you vidio of it for proof https://www.youtube.com/watch?v=AZ6WW-e7G50

**Comment by Zealote** [comment]
Wait for confirmation from Luth/a dev, but afaik:

1) Mitigation values in combat log refer to toughness in RoR, so there'll be no change to the value displayed after your resist/armour debuff.
2) An ability's dmg/dot is applied before debuff the debuff; combined with the fact that dots aren't affected by modifiers that're applied afterwards, Daemon Spittle's dmg won't be affected by its own debuff. The same applies to Warp Reality: you need to use it after you've applied Daemon Spittle debuff to get the increased dmg.

https://github.com/WarEmu/WarBugs/issues/1444

**Comment by Kweedko** [comment]
yeah i know about dots but he got only 200 tough and 50% of mits it's ain't never been like that on off server, softcap on rez was 40% and a bit and u can see in vidio that im used not only dots but direct too and it t4 it even more insain mits above to 90% this is ridiculous.

**Comment by Kweedko** [comment]
https://www.youtube.com/watch?v=cmVj7Ps1j_s you can see here real damage on off server ye it's 80 zeal but 80rr don't give you about 50% damage buff and he crits snb tanks 1k not 200 like now here

**Comment by Luth-RoR** [comment]
The first implementation of RR80+ meant one "hidden level" for every renown rank up to RR100 (+ 20 hidden levels = level 60). So these kind of videos are not very meaningful.
The combat log shows a mixture of all mitigation types.
Also: different abilites have different stat coefficients (how well they scale with your DPS/heal stats); this defines also how well thoughness stacking works against them. The DPS stat coefficient for most DOTs is around 50% iirc.

About RvR situations: there are to many percentage based damage modifiers flying around in the game (e.g. guard, challenge, morales, etc.).

**Comment by Zealote** [comment]
I'm a bit confused cos there seem to be a few different issues here; is it mitigation values or overall dmg or the debuff effect of Daemon Spittle (or all three) that you think is being calculated incorrectly?

Two confounding issues are the lvl difference between your chars, and more importantly bolster makes it a lot harder to judge.

If you compare the actual difference between your dd attacks at the end though:
Tzeentch's Cry: 216 (172) -> 280 (109)
Scourge          : 262 (220) -> 340 (143)

The debuff is clearly working correctly - there's a ~30% increase in dmg for each.

As for mitigation, it's not as simple as saying he's got 50% mitigation since the mitigation value isn't just resists. For example, with your Tzeentch's Cry after debuff: 109 / (280+109) * 100 ~= 28%. Almost all of that's from toughness. So I suppose the question is: is that a reasonable value?

Finally, wrt stat coefficients, I got TC's to be about 2.95; I'd be interested in any confirmation/rejection of that though.

**Comment by Kweedko** [comment]
are u mad only two lvls on 90 and 100 +20 insain if that was that 100 onshoot everybody below 80

besides this yesterday i tested with my buddy tank tact for damage from rituals works fine rituals damage corpreal with rez debuff almost none mits at all on skills looks like the damage not corpreal but in armor but all zeal must damage corpreal i played ddzeal on off up to 98 rr difference in damage betwen 80rr and 50rr was about 5-7%

**Comment by Kweedko** [comment]
we can test this right now in game wit my zeal and any of your char

**Comment by Luth-RoR** [comment]
> are u mad Luth-RoR only two lvls on 90 and 100 +20 insain if that was that 100 onshoot everybody below 80
No, i'm not mad. 
This was the **first** implementation by mythic, as i wrote. It was reduced to max. 5 additional levels on RR100 later and at the third step everyone was bolstered to level 45 in RvR to compensate somewhat for the powergap.
Btw, your posts are very hard to read/understand without any punctuation.

**Comment by Kweedko** [comment]
lets go and test in live take a tank or whatever you want and i show all i got and u see something not right

**Comment by Luth-RoR** [comment]
This is neither a chat window nor the forum. 
You already posted some numbers here; the question is if they are right or wrong. There is no need to get more of the same numbers.
You'll have to wait for a response from someone with knowledge about combat calculations (developer).

**Comment by Kweedko** [comment]
then they must check damage form rituals tact and all of skills
