### ISSUE TITLE
The Twisting Tower quest's description is broken

### ISSUE THREAD

**Issue by ShanellRoR** [WarEmu/WarBugs#7071]
So, the problem is in description of quest's objective
![kastul_070](https://cloud.githubusercontent.com/assets/17355822/16568078/92577cfa-422e-11e6-8893-3a4d00738bef.jpg)

**Comment by Ryanfawkez** [comment]
NPC is missing from the database.

**Comment by saupreusse** [comment]
yeah but id rather wait with a fix until the twisted tower is ingame. 
On live you would get a quest from Detzerg muckmush, where you would have to travel to the twisted tower.

**Comment by lilimx** [comment]
This was fixed a while ago
