### ISSUE TITLE
Serpents passage cap

### ISSUE THREAD

**Issue by bloodi** [WarEmu/WarBugs#7072]
#When you cap the "flag" on the serpents passage sc, cancelling the cast bar and using it again will grant you a double cap, saw some guy doing it, did the same and won from 370 to 500 in a single cap.

**Comment by Lileldys** [comment]
https://github.com/WarEmu/WarBugs/issues/7032

**Comment by bloodi** [comment]
Thats what i get for being illiterate and searching Serpents instead of Serpent's
