### ISSUE TITLE
Slayer Wrong appearance

### ISSUE THREAD

**Issue by Theslay** [WarEmu/WarBugs#7073]
Oi lads, 
Seems some appearances for the slayer are not the good one . I speak with Gumthorr about the appearance of the reavers armbraces , the dire wolf chargers and the helfried's torc . they all got the t3 generic appearance . I know it's a minor issue but it's kinda upseting , slayer have few apperance and it's kinda boring to always have the same , Anni appearance would be good ^^ ( finally some boots for slayer my toe are pleased)

![theslay_010](https://cloud.githubusercontent.com/assets/17109649/16569761/7ee1ee42-423a-11e6-84ae-d0ffac9c9094.jpg)
![theslay_012](https://cloud.githubusercontent.com/assets/17109649/16569765/84da8a8e-423a-11e6-98a5-3c89299a91ba.jpg)
![theslay_013](https://cloud.githubusercontent.com/assets/17109649/16569767/8785ca1e-423a-11e6-9d90-71d3a713745c.jpg)
![theslay_014](https://cloud.githubusercontent.com/assets/17109649/16569768/8b123866-423a-11e6-909a-f59af17ad6c8.jpg)

**Comment by Torquemadra** [comment]
Items changed to 05 appearances as with 99% of the other classes however please note this is not a bug but a preference and as such the bugtracker is not the best place, perhaps the suggestions on the forums would have been a more appropriate platform.
