### ISSUE TITLE
Khaine's Embrace Queue Rules.

### ISSUE THREAD

**Issue by Lileldys** [WarEmu/WarBugs#7074]
Not entirely sure what this SC is meant to be group wise. Currently, you can only queue it solo or in a group of 6. It seems to follow Caledor Woods queue requirements. The only patch notes made about this SC is:

> Londo:
> -Added Khaine's Embrace scenario handler.

Seems strange for this scenario to follow this queue rule.

**Comment by Londo001** [comment]
KE should have no queue requirements at the moment.

**Comment by Torquemadra** [comment]
KE currently (on live) seems to have the condition of being either 6 man or 1 man
