### ISSUE TITLE
Invisible players in Scenario lists

### ISSUE THREAD

**Issue by mohokios** [WarEmu/WarBugs#7076]
i experienced the problem 2 times in overall... probably a random bug or whatever, i don't know.... 

i am not able to reproduce it, i didn't have fraps or anything else to take a video from the game..

Problem:
White lions were NOT in order or shown up in any of  players list though they were playing on Scenario normally..

Problem: 
you don't know who your enemies are and how many they are...

**Comment by Evildoor** [comment]
I do believe that this is not restricted to white lions - my friend had the same problem on his AM - we queued together, but he was not present in the scenario list and he was unable to join a party.

**Comment by mohokios** [comment]
i am not sure if this has any effect also in scenario balance...ok, we all know that scenarios are totaly random in terms of who will join, roles etc... BUT
what's happening with balance between the number players ?

**Comment by Kaelang** [comment]
This has since been fixed.
