### ISSUE TITLE
Deathly engineer have no model.

### ISSUE THREAD

**Issue by ShanellRoR** [WarEmu/WarBugs#7077]
![kastul_099](https://cloud.githubusercontent.com/assets/17355822/16593347/814ba91c-42ed-11e6-9929-36d64cfcfe20.jpg)
![kastul_100](https://cloud.githubusercontent.com/assets/17355822/16593349/858eb51e-42ed-11e6-9f57-a0b0941e8668.jpg)
Located in a cave in Cinderfall coords 62k 49k. His model appears only after you kill him.

**Comment by saupreusse** [comment]
Fixed in next patch.

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16037
