### ISSUE TITLE
Login/Launch Error

### ISSUE THREAD

**Issue by enavarromo** [WarEmu/WarBugs#7083]
Hi, when I try to loggin with the launcher (placed in the same directory as the WAR.exe) it throws me this error:
Error starting: System.UnauthorizedAccessException: Acceso denegado a la ruta de acceso 'D:\Program Files (x86)\Warhammer Online - Age of Reckoning\WAR.exe'.
   en System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   en System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   en System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   en System.IO.FileStream..ctor(String path, FileMode mode)
   en RoRLauncher.Client.patchExe()
   en RoRLauncher.Client.Handle(PacketIn packet)

Thank you!
Eloy

**Comment by Luth-RoR** [comment]
Not started as admin (UAC), directory write protected, files in use by another program (e.g. torrent) etc. pp.
Please use the support forum in the future, as the bugtracker is for bugs and the launcher works fine: https://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=2889
Thanks.
