### ISSUE TITLE
Morale upon death

### ISSUE THREAD

**Issue by footpatrol2** [WarEmu/WarBugs#7084]
In live when a player died he lost all of his morale instantly. In RoR this is not the case.

**Comment by Luth-RoR** [comment]
RoR morale gain works differently iirc:

**Comment by footpatrol2** [comment]
This affects defensive morale cycles and morale bombs. If you kill a key component of the defensive morale cycle/morale bomb in live you would break the defensive morale cycle or lessen the bomb in live. 

In RoR as long as the target is killed and got rezed you can upkeep the defensive morale cycle/not lose bomb component. Do you still want me to find a video?.

**Comment by Luth-RoR** [comment]
I didn't wrote that you need to find a video. The confirmation request is for a dev with knowledge on the actual combat code.
RoR server morale gain: 
https://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=12409&p=134588#p134588

I was wrong about the linear steps; that's just until M2. The behaviour on RoR is correct for the different morale steps, though the morale per second seems to be too low.
In this video he has M1/2 ready after 10 seconds everytime, not every 36 seconds like in RoR. We don't know anything about any morale per second modifiers in this vid ofc, but there shouldn't be +26 morale per second through gear or tactics on him.

My point was that in RoR it seems to take generally a longer time to reach your morales compared to the mythic server (it's not _live_ anymore since 2013).
Thus classes with a higher risk of getting killed in mass PvP situations (melee) virtually never see any higher morales before they get killed again.
But i don't want to start a balancing discussion here, as the bugtracker is for bugs. 
At this point we just need confirmation if this behaviour is working as intended or not.

**Comment by Luth-RoR** [comment]
I forgot to post the video...
https://youtu.be/JdJgheowSiE?t=255

**Comment by Lileldys** [comment]
I believe that morale gain was increased dependant on group size. In full 6man groups, people would  get m1 in 10s, but while playing solo morale took them longer to get. My guess is more people in a group the faster you gained morale on live.

**Comment by footpatrol2** [comment]
So notice in the video that you linked, when the choppa dies he loses all of his morale. This bug tracker open post is on morale lost at death. Upon death you lose all your morale and exit combat instantly. In RoR when you die you still are in combat and gain morale.  I agree that morale gain was increased based on group size also. I agree that morale gain is slower in RoR then the mythic servers. 

I am unsure that your comments are to me or to ozarmidrashim.

In addition, because I'm that guy. There used to be a racial renown tactic that would increase your morale gain by additional 5% per same race group member. Although this is not part of the bugtracker post.

But since we are talking about morale gain also. When mythic gave up on the community running racial groups they may have provided the 5% morale boost per group member as a default setting (Mixed groups or racial) when they decided to change the renown system. Maybe that can help with your assessment on morale gain. I don't know if they did that. Just a guess.

**Comment by Luth-RoR** [comment]
It was just a reply mixed with general info. Maybe i/we could find an old video that shows some solo player with his morale bar.

**Comment by Lileldys** [comment]
https://youtu.be/yOoIo1hnYi4?t=2m57s

Starts combat at 3:02, Gains morale 1 at 3:38.

**Comment by Luth-RoR** [comment]
Nice thanks. So the base morale gain of RoR and the gain while being solo on the mythic server match (36 seconds). 
Only the faster morale gain in groups doesn't work/is not implemented. 
And that morale persists after death, but it shouldn't be (which is my fault).

**Comment by Luth-RoR** [comment]
Ok, this was discussed internally and atm it will be left as it is, as

a) "morale bombing" would be made easier atm with a way faster morale regen rate.
b) there is a general discussion going on what to do with morales (they morale gain system and morale abilities; some of them are far too lame/useless and some definitely OP).

I leave this report open until this is _really_ solved, but please _use the forum for any balance discussions_ on morales. Thanks

**Comment by footpatrol2** [comment]
Although your focus on this bug tracker report has been on the speed of which morale is obtained. That is not the purpose of this bug tracker report. 

By not completely draining the morale upon death, your making defensive morale cycle's stronger and easier to maintain. A player that dies that is part of the defensive morale cycle but does not have his morale drained can be rezed and still continue the defensive morale cycle. There is no interruption currently. While on the mythic servers there would have been. 

By not completely draining the morale upon death your making morale bombs stronger. Rez the bomb component player before he starts losing morale, continue gaining morale towards your bomb component. 

On the mythic servers, If you kill a opponent he will have zero morale while the rest of his group have higher morale gain then him. This interrupts defensive morale cycles and staggers morale bombs. 

Defensive morale cycle's are time dependent. Morale drain interrupts the timing. 
Morale bombs depend on multiple specific players reaching specific Morales at a specific time. Complete Morale drain upon death decreases the morale bomb. 

If you recognize, that by leaving it where it is currently is a conscious buff to defensive morale cycles and bombs then I have no objections. I would just like you to know that it is a indirect buff.

**Comment by Luth-RoR** [comment]
No, my focus on this report was not the speed at which morale is obtained, even if it seemed like that. I was interested in finding out how morale worked **generally** on the mythic server.
I just posted examples/my experience with the morale system we have atm and the flaws it creates for certain archetypes with a higher "risk vs reward" factor, particularly in mass PvP.

As i wrote, the whole morale mechanic was discussed internally (morale gain & drop on death, etc.) and atm it will be left as it is, until there will be a more balanced solution.
I think everyone is aware that the current mechanic is not perfect, but the mythic one was not perfect too.

Btw:_I only posted the outcome of the discussion; that doesn't necessarily mean it reflects my own oppinion on that matter._

> please use the forum for any balance discussions on morales. Thanks

**Comment by bozzax** [comment]
The old (pre 1.4) renown tactics gave increased morale gain.

Dwarves Camaraderie - You receive an additional 5% morale gain for every Dwarf in your group.
Empire Alligence - You receive an additional 5% morale gain for every Empire in your group.
High Elf Lineage- You receive an additional 5% morale gain for every High Elf in your group.
Chaotic Alligence - You receive an additional 5% morale gain for every Chaos in your group.
Dark Elf Lineage- You receive an additional 5% morale gain for every Dark Elf in your group.
Orcish Camaraderie - You receive an additional 5% morale gain for every Greenskin in your group.

**Comment by ozarmidrashim** [comment]
Morale issues were handled a few weeks ago
