### ISSUE TITLE
No rp and inf upon killing enemies

### ISSUE THREAD

**Issue by Psema** [WarEmu/WarBugs#7085]
Yesterday night i solo killed 1 AM next to the bo that is close to order warcamp in DW then as he was passing again (around 40 secs afterwards)i killed him again with my WE and he gave no rp and no inf.Same happened a few minutes afterwards with a BW first time he game rp and inf the second gave nothing.

**Comment by Luth-RoR** [comment]
Mechanic to prevent renown farming. Working as intended.
