### ISSUE TITLE
Dwarven T3 influence problem

### ISSUE THREAD

**Issue by arti005** [WarEmu/WarBugs#7089]
So I have this strange problem with RvR influence with Dwarves in T3. When I first leveled and came to Badlands T3 to do some PvP I noticed that is showed I had full influence with Dwarves. But ToK shows nothing, and also NPC with rewards shows no items, showing that I have no influence. I spend a lot of time doing RvR in Badlands and Black Fire Pass so I am sure I would get some influence by now.
The problem persists after logout, after reboot.
Btw, a reward NPC in Badlands fell underground...
I attach screens showing what I mean.

![badlands](https://cloud.githubusercontent.com/assets/20372736/16709099/2d4b6c0e-4607-11e6-9e48-a0d0a040970e.PNG)
![blackfirepass](https://cloud.githubusercontent.com/assets/20372736/16709101/311de956-4607-11e6-907e-9b8a62ed6184.PNG)
![dwarvent3rvrinfluence](https://cloud.githubusercontent.com/assets/20372736/16709102/336213b8-4607-11e6-8c20-3d7c0faa33c5.PNG)
![tok](https://cloud.githubusercontent.com/assets/20372736/16709103/34eb579e-4607-11e6-9beb-9e47bb9d0d44.PNG)

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/6320
