### ISSUE TITLE
duping items in backpack

### ISSUE THREAD

**Issue by jim6** [WarEmu/WarBugs#709]
after server restart yesterday i lost some items i had dropped and even though i had put the npc'able items all neatly stacked up to save inventory space they were all unstacked again

when i tried to stack (canteen of stale water again) the water that was supposed to disappear suddenlly became  a stack of 6553 units of stale water.

after this happened i 'destroyed' the stack. hope this helps

**Comment by jim6** [comment]
it reproduced 3 times in total :/

**Comment by Evildoor** [comment]
The stacks mechanic was reworked. Is this problem still present?

**Comment by Evildoor** [comment]
No response, closing for now.
