### ISSUE TITLE
Sets and classes 

### ISSUE THREAD

**Issue by Kweedko** [WarEmu/WarBugs#7094]
Why some classes got 3 sets for each mastery branch in t4 and others got only two?
(And speaking of Zealot "of course i speak for zeal" cause of that i can't spec couple of good specs, but othe classes deseve it too more choices more specs for everybody)
My suggestion ruin for middle(cause no crit and this is buble branch), ani for left(like now) and SC set for right(cause idk useless def set for aoe branch) 
Or ruin for right and SC for middle(like now)

**Comment by Luth-RoR** [comment]
That's a suggestion/feature request, not a bug at all. The bugtracker is only for bugs. 
Forums are that way: https://www.returnofreckoning.com/forum/viewforum.php?f=15

**Comment by Kweedko** [comment]
All those suggestion/feature request means nothing nobody reading them, only if they wrote by edgy 6vs6ers

**Comment by Luth-RoR** [comment]
1. No.
2. Feel free to join any discussion on the forum; though the staff is not responsible for any user-inability to argue against _edgy 6vs6ers_.
3. Bugtracker rules are for everyone; that includes _you_.
