### ISSUE TITLE
Sowing Sorrow Error 

### ISSUE THREAD

**Issue by Fiddlehero** [WarEmu/WarBugs#7097]
![rychter_001](https://cloud.githubusercontent.com/assets/16520814/16711444/ba445a18-4610-11e6-9809-06372603000e.jpg)
I was questing in the Chaos wastes, and came across this error in the Sowing Sorrow questline.

**Comment by saupreusse** [comment]
i think this needs scripting. should spawn a daemon after you spoke to him if i see it correctly.
