### ISSUE TITLE
Occasional client to crashes

### ISSUE THREAD

**Issue by Malgaroth** [WarEmu/WarBugs#7101]
It's really all in the title this time. Going up the T1 ORvR ramp in Empire on Destro side can occasionally cause the game to crash, whether you're playing as a destro or order toon. Tested it on my zealot, my swordmaster and my disciple of khaine. Polling chat shows that others have had similar issues.

**Comment by Luth-RoR** [comment]
I'm going to check this on the dev server.

**Comment by Luth-RoR** [comment]
Couldn't find any bug. Does that happen only during heavy PvP situations?

**Comment by Malgaroth** [comment]
I wouldn't call it heavy PvP, not even a full warband on either side, when the server comes back up I'll grab some recording software and try to catch it out.

**Comment by Luth-RoR** [comment]
Thanks.

**Comment by Luth-RoR** [comment]
Ok, there still some problems going on with the server crashing itself and different types of occasional client crashes happen from type to time.
The devs try to find the roots of the problems, but these kind of issues are not easy to solve.

**Comment by Malgaroth** [comment]
Oh yeah, I got no issue with that, problems take time, I'm not trying to rush anything along. Just trying to let it be known where problems might be and help where I can
