### ISSUE TITLE
(PQ) Maccabre farvor (destruction tier 3 PQ, can be complete with workaround

### ISSUE THREAD

**Issue by redraven313** [WarEmu/WarBugs#7102]
Not sure how much bug this is, but it is something I noticed and I couldn't find it when I looked through the bug tracker.

The destruction PQ Macabre fervor seemed bugged yesterday (9/07/16), when you were in the area the kill counter didn’t advance, though you got influence for the flagellant kills and when you advanced to stage 2 and 3 you got no credit. 

However in the PQ just besides it (Pillage and Plunder ) I noticed Macabre fervor did track the kills (macabre fervor was showing in the other PQ area),so I waited and found out that when stage 3 was complete (which was shown in the tracker) I was awarded credit for the Macabre Fervor and rolled for reward.

I have no idea if this information will help you and is interested if it can help, I will certainly look for this trick in other PQs

-Redraven313

**Comment by wargrimnir** [comment]
This area issue has been fixed. Other PQ's still need to be activated.

**Comment by redraven313** [comment]
awesome. Had forgotten I had Warhammer installed, due to me writing this damm bachlor. will probably return in Jan

________________________________

**Comment by Luth-RoR** [comment]
Better return asap: https://www.returnofreckoning.com/forum/viewtopic.php?f=2&t=18972 😃
