### ISSUE TITLE
Boss of "Welcome to troll country" PQ

### ISSUE THREAD

**Issue by chstens** [WarEmu/WarBugs#7104]
If you leave the area, most mobs return to their spot, but this guy just dies and renders the PQ uncompleteable.

**Comment by Torquemadra** [comment]
boss name?

**Comment by Luth-RoR** [comment]
PQ seems to have general issues: https://github.com/WarEmu/WarBugs/issues/6878

**Comment by Torquemadra** [comment]
works fine on dev
