### ISSUE TITLE
im at full infulence 10520 in T2 and it wont let me buy any of the infulence gear

### ISSUE THREAD

**Issue by thaddes** [WarEmu/WarBugs#7105]
Hi my character is thaddes I'm in T2 I'm at full influence and keep going to captain victor which is were it 
tells me to go and the rewards are gray I asked other people and they said to report the bug one person said they experienced the same if you can help would be greatly appreciated so I can get my gear ;D

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/6320

**Comment by Luth-RoR** [comment]
Known problem with area discovery.

**Comment by thaddes** [comment]
sorry I'm still confused so how do I fix it or will it be fixed in future and if not all good I love this game already just want to know ;D

**Comment by Luth-RoR** [comment]
There will a fix, but area discovery is not as easy to fix as some DB entry. The DB had also issues lately. Could take a bit

**Comment by thaddes** [comment]
oh ok cool hey I appreciate its f2p game so I appreciate what ever you guys do thank you so much for your response
