### ISSUE TITLE
Tunnels and trinkets quest description is broken

### ISSUE THREAD

**Issue by ShanellRoR** [WarEmu/WarBugs#7109]
![kastul_107](https://cloud.githubusercontent.com/assets/17355822/16732031/d3626ea8-4783-11e6-9b7e-aff9ddc50325.jpg)

**Comment by saupreusse** [comment]
Fixed in next patch.

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16037
