### ISSUE TITLE
Bane Shield oneshot

### ISSUE THREAD

**Issue by krisolyub** [WarEmu/WarBugs#7110]
Chosen aura "Bane Shield" doesnt work propertly. It stacks from 2 or more chosens and extends out of group. So 1 chosen can hit order's AOE dps 6+ times (i saw 9 at scene) at one sec by 120 damage. And if there is 2 chosen then from 9 destro AOE dps gets 18 hits per 1 second. So order AOE dps kills himself in 1 sec when hits wb destro. 8 chosens = 9*8*120 = 8600 damage at one sec. 
It is impossible fight this way in rvr.

**Comment by Luth-RoR** [comment]
Do you have a combat log screenshot at hand?

**Comment by krisolyub** [comment]
No i dont have screenshot. But i ll do it soon and attach here.

**Comment by Luth-RoR** [comment]
Thanks. Maybe there will be also a white system message in the chat with "Exception thrown ..." including a number. This could be usefull too.

**Comment by krisolyub** [comment]
No i didnt notice any exeption in say chat.

**Comment by ozarmidrashim** [comment]
8364 Dire Shielding
Bane Shield will now also protect any of your allies within 30 feet and last 7 seconds longer.
