### ISSUE TITLE
No items' descriptions.

### ISSUE THREAD

**Issue by theormore** [WarEmu/WarBugs#7112]
So, yeah - that is it. When I hover my mouse at itemz in my bag, there is no description. It also happens when accepting quests and picking rewards. Basically, no item icon "show" a description. Description shows from items linked in chat, though.

**Comment by Luth-RoR** [comment]
Do you have any addons installed?

**Comment by Elvenalthur** [comment]
In the in game options, do you have tooltips and advanced information check boxes enabled?
