### ISSUE TITLE
rvr rewards

### ISSUE THREAD

**Issue by lftr** [WarEmu/WarBugs#7113]
hello

all my merchants for rvr rewards are bugged in emp zone the windows appear empty in all slot
when i change zone for darfs and come back in emp the reward merchant is still bugged but this time i have the darwf's rewards

**Comment by Luth-RoR** [comment]
Probably related to https://github.com/WarEmu/WarBugs/issues/6320 but the switching rewards seems new.

**Comment by Kaelang** [comment]
As this is a legacy issue, and lots has changed, please re-open if this issue persists as it should be fixed.
