### ISSUE TITLE
ruin gear vendor gave me other class's part

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#7114]
vendor gave me BW's shoulder when my character is WP
my average ping is 280ms
there was a lag when i browsed vendor window and accidentally clicked random part
before all parts are shown
( should have used buy/sell warning system )

**Comment by Luth-RoR** [comment]
And the bug is?

**Comment by anarchypark** [comment]
when u browse vendor they show u proper class's parts only
i thought it's a bug that buying other class's part which suppose not showing in vendor
if not a bug move on

**Comment by Luth-RoR** [comment]
Not a bug. You can select an option in the window to hide gear your character can't wear.
