### ISSUE TITLE
Crafting Inventory Bug (Scavenging)

### ISSUE THREAD

**Issue by ShadowstarWD** [WarEmu/WarBugs#7116]
The items being scavenged were trying to place themselves in the same slot over and over causing a constant flicker in one inventory space. Only by clicking in the slot and dragging it to another inventory space until it was clear could you even identify just what you had looted. Not sure if the problem is with the automatic loot being picked up or not. However, once you rearrange the inventory the item was then no longer able to be used in making talismans. It was like it was not reading anything there.

Taking all crafting items out of the crafting bag was the only way that talismans could be made without having to reopen and close the skill repeatedly.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/1548 Known.
