### ISSUE TITLE
Unusual amounts of client crashing in the Inevitable City

### ISSUE THREAD

**Issue by Vinrick** [WarEmu/WarBugs#7119]
Have both personally experienced and seen other players reporting a noticeable increase in CTDs when moving around the IC; doesn't seem to be restricted to a single area in the IC, but this is based off of a small sample size (~6 people during low-pop hours).  Seems to have started in the past few days after the long bout of server downtime.

**Comment by Luth-RoR** [comment]
Seems to be a common problem atm, not only in IC: https://github.com/WarEmu/WarBugs/issues/7101
