### ISSUE TITLE
obj wall fly ..

### ISSUE THREAD

**Issue by Magteridon** [WarEmu/WarBugs#7120]
![normak_184](https://cloud.githubusercontent.com/assets/16975012/16795153/17394b70-48dc-11e6-8fd1-81ac39a7cc22.jpg)
![normak_186](https://cloud.githubusercontent.com/assets/16975012/16795159/252cfc5e-48dc-11e6-9bd0-a6a389da6031.jpg)

**Comment by Magteridon** [comment]
Elite reward !! greys
![normak_142](https://cloud.githubusercontent.com/assets/16975012/16795224/71c07370-48dc-11e6-80c5-52be16dce2f6.jpg)

**Comment by saupreusse** [comment]
fixed the flying palisade.

**Comment by Torquemadra** [comment]
the other is already fixed but one issue per report please

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16037#p177201
