### ISSUE TITLE
Missing a Character since the server issues started

### ISSUE THREAD

**Issue by Concerned101** [WarEmu/WarBugs#7122]
My level 40 Engineer (Svot) no longer appears on character select screen since the servers have been having issues.

**Comment by Concerned101** [comment]
*note all my other characters are available.

**Comment by Elvenalthur** [comment]
If you check the forum, there's plenty of responses in relation to this. It's not a bug and the character isn't missing. All technical support is handle through the forum, not the bugtracker.
