### ISSUE TITLE
this castle  no have texture, can go  to dangerous zone out map

### ISSUE THREAD

**Issue by Magteridon** [WarEmu/WarBugs#7123]
![ataulfa_006](https://cloud.githubusercontent.com/assets/16975012/16829995/76fcbd6a-499c-11e6-9a61-33bde88e629e.jpg)
![ataulfa_007](https://cloud.githubusercontent.com/assets/16975012/16829993/76fbb596-499c-11e6-92bf-3110f6240032.jpg)
![ataulfa_008](https://cloud.githubusercontent.com/assets/16975012/16829994/76fcb6d0-499c-11e6-92e2-ebddf3c65333.jpg)
![ataulfa_009](https://cloud.githubusercontent.com/assets/16975012/16829996/76fdcee4-499c-11e6-8cbe-246ac98f686c.jpg)

**Comment by Luth-RoR** [comment]
This is a client side issue; can be solved when the client can be modified.
