### ISSUE TITLE
Unmasked Heater character placement

### ISSUE THREAD

**Issue by edavoc** [WarEmu/WarBugs#7125]
![aedrik_002](https://cloud.githubusercontent.com/assets/16967436/17449115/668ef5c4-5b26-11e6-9853-05fd73eba1ce.jpg)

When equipped the item appearance for Unmasked Heater is set too high on your character's arm. I believe the proper placement of the shield should roughly be aligned with the handle texture on the back of the item.

**Comment by Luth-RoR** [comment]
Client side issue. Will be closed until the client can be modified.
