### ISSUE TITLE
Sylvan guild is gone.

### ISSUE THREAD

**Issue by Kali14** [WarEmu/WarBugs#7126]
Hello I was leader of this guild, im Skalier:) 
I didn't post on forum because have some techical problems with forum and when Azarael was put topic about missing guilds I didn't wrote this one because I didn't know that is gone because I couldn't log in before. We had 17 lvl and I was guild leader. Just please for restore guild if this is possible. Thanks:)

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=15164&p=176748#p176748
