### ISSUE TITLE
Khaine's Embrace - never ending explosions

### ISSUE THREAD

**Issue by hoppolek** [WarEmu/WarBugs#7127]
I just played a scenario just now where order had captured both flags. Just as they were awarded with the double cap, destro got both flags capped. What happened was a never ending explosion fest, the explosions simply never stopped coming. It was also impossible to end the scenario (timer didn't end it either).
![flygaresset_000](https://cloud.githubusercontent.com/assets/14668194/17453124/40b8b79e-5b77-11e6-881e-1b967b49ef77.jpg)

**Comment by saupreusse** [comment]
maybe you changed the difficulty to "hard" in your settings. ^^
