### ISSUE TITLE
Bugged Quests that I could find - Nordland (Warcamp)

### ISSUE THREAD

**Issue by MasterSausage** [WarEmu/WarBugs#713]
Spoils of War - Instant complete
Flames of Change - Instant complete
Piers of Destiny - Instant complete
Recovering Steel - Instant complete
Pillaging the City - Instant complete
Stoking the Fire - Instant complete
Defilers of the Caste - Instant complete

**Comment by Evildoor** [comment]
Quests were removed/moved to T2 and implemented properly/whatever. Closing.
