### ISSUE TITLE
impossible  unlock  ToK

### ISSUE THREAD

**Issue by jpnrd** [WarEmu/WarBugs#7130]
Shadowlands , 12.2k - 57.7k, there's a "rootwalker remains" which once clicked should unlock "rings of history" , even when killing it nothing happens

**Comment by Ryanfawkez** [comment]
Changed Rootwalker Remains from an NPC to a game object, clickable by both factions for the unlock and title.

**Comment by jpnrd** [comment]
Thanks a lot :)

**Comment by jpnrd** [comment]
Tested and unlocked ;) ty
