### ISSUE TITLE
Renown character bag

### ISSUE THREAD

**Issue by Dekata** [WarEmu/WarBugs#7132]
Hi. My character has 27 renown points, but I can spend for renown abilities only 24 - wrote in window " Available: 24". So i miss 3 points. Whether it is possible as to correct that?

**Comment by Luth-RoR** [comment]
What's your level?

**Comment by Dekata** [comment]
25 lvl 28 rr

**Comment by Luth-RoR** [comment]
Just for clarification: On your character you can spend 24 renown points on level 25?
Also: a screenshot would be helpful.

**Comment by Dekata** [comment]
![error](https://cloud.githubusercontent.com/assets/13432606/17464925/40b49a8e-5cf2-11e6-9259-f10229a5cb67.jpg)

**Comment by Luth-RoR** [comment]
This is not a bug.
There was a patch a while ago that capped the renown rank to your your level; you have to level up to level 27 to be able to spend the additional renown points.
Afaik the cap is removed at level 36 or 37.
Your character got more renown than he has level ranks before that patch.

**Comment by Dekata** [comment]
Thx a lot! :)
