### ISSUE TITLE
Pheonix Gate flag

### ISSUE THREAD

**Issue by massmurder** [WarEmu/WarBugs#7133]
Unable to turn in the flag at Pheonix gate. We had our flag still there and was still unable to cap.

Cheers,
Zattaro

**Comment by Symbelmyne** [comment]
Had the same. was carring flag, came back to our flag, there is missing small chalice in the tower gate where suppose to be cap point. scenario t2.

**Comment by Luth-RoR** [comment]
**Iirc** when both flags are hold by each team, the flag has to be carried to the bridge.
Could that be the case here?

**Comment by Symbelmyne** [comment]
I was checking, there used to be 2 flags on each side of bridge, but also were missing. Besides, carring orb i couldnt use any abilities except non targatable, like hold the line, flee ect.

**Comment by Tesq** [comment]
cannot give the flag ye, you shoudl give it to the building behind you while you have still yours but it's not working didn't test the reset at mid but qw had our and i couldn't turn it.

**Comment by Pumpgunpete** [comment]
Still the Brazier (item to drop the flag) is missing (09.08.15 - 18:00 european time). 
Without the Brazier u cannot turn in the flag. Brazier was in front of the little buildings upstairs as far as i remember.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/7269 has more info and will be fixed soon.
