### ISSUE TITLE
The Sealed Tower (Order chapter 16 Dwarf PQ)

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#7134]
- Stage 2 misses timer.
  ![maxeras_000](https://cloud.githubusercontent.com/assets/16864486/17487567/1f286c68-5d9e-11e6-995c-5b61ba5a7eb9.jpg)

**Comment by Kaelang** [comment]
Stage 2 now has a timer.

![image](https://user-images.githubusercontent.com/60117106/82145118-75ce3a80-9840-11ea-8dd7-dd7b4b7b5632.png)
