### ISSUE TITLE
Hells Fall - Order PQ, Praag

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7136]
PQ area ID is missing Saupreusse :) No UI when entering the PQ.Also no Chapter showing in the area.

**Comment by Soulwhisper** [comment]
You can force UI to show up at this location...just outside of the PQ and facing to the wall...only there :P Needs little MOB re-arrangement or just the Area ID because there are some Skullblades outside of the PQ area but killing them gives you influence and counts them in UI.
![toufekiaaaa_002](https://cloud.githubusercontent.com/assets/16864486/17604293/e183f044-601d-11e6-8e76-123f529e79c6.jpg)
![toufekiaaaa_001](https://cloud.githubusercontent.com/assets/16864486/17604294/e185d012-601d-11e6-95fa-2cf064939c31.jpg)

**Comment by saupreusse** [comment]
this one is special. The PQ lies within 3 parts of the map. the UI will only show up in two of them
(miskas commons and so on). need a goldname to find out why this is the case.

**Comment by saupreusse** [comment]
#7135 similar issue. PQ area is complete, though it wont show up.

**Comment by Razielhell** [comment]
@saupreusse /applause
