### ISSUE TITLE
Ruins of Schloss von Rubendorff - PQ Order Chapter 2

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7138]
UPDATED 20/12/2016
- [x] PQ area ID is bigger than it should.I draw the area where it should be based on where mobs of first stage required to be killed.
  ![maxeras_003](https://cloud.githubusercontent.com/assets/16864486/17496881/e5686832-5dc7-11e6-8bd4-27ba701fb2eb.jpg)

**Comment by Soulwhisper** [comment]
**_Stage 1_**
Kill the Norse Ravagers and liberate Schloss von Rubendorff!

-     **Norse Raiders - 0/15**
-     **Norse Ravagers - 0/20**

**_Stage 2_**
Tear down the Raven Host banners and reclaim Schloss von Rubendorff for the Empire!

-     **Claim the Skulltaker Banner - 0/1**
-     **Claim the Banner of Lostsight - 0/1**
-     **Timed: 10:00 Minutes**

**Each banner is guarded by a named mob, Pergris Lostsight at the Banner of Lostsight and Faar Skulltaker at the Skulltaker Banner, and two Norse Ragelords that must be defeated before the objective can be claimed. Griffon Soldiers will spawn during this stage and attack any enemy mobs they encounter, including those protecting the two banners.**

**Comment by Soulwhisper** [comment]
- Stage 1 Ravagers are all naked.

**Comment by Soulwhisper** [comment]
From here
![warhammer online age of reckoning 11 02 2016 - 23 31 52 14](https://cloud.githubusercontent.com/assets/16864486/19948330/b228a664-a154-11e6-8f1a-9ba0eef9edaf.png)
it stucks like this 
![Uploading Warhammer Online  Age of Reckoning 11.02.2016 - 23.32.54.15.png…]()

**Comment by wargrimnir** [comment]
Converted the remaining stage 1 mobs so that are inside the current PQ area.
The visual chest bug remains and should have it's own ticket with the PQ's noted where it is present. This is a coding issue.

**Comment by Soulwhisper** [comment]
@wargrimnir There is no visual chest bug.Most of Order PQs dont have this bug.
