### ISSUE TITLE
Return Fire Quest Bug 2 Hellcannons

### ISSUE THREAD

**Issue by FreedomFighter08** [WarEmu/WarBugs#7139]
It has never been like this before but today the Hellcannons are almost impossible to destroy they neglect your dmg by like 90%, they are almost impossible to solo

**Comment by Soulwhisper** [comment]
This quest must be completed by Firing Hellcanons with OUR ORDER EMPIRE CANNONS up on the hill.Doing so Dodges every single shot( **THIS IS THE BUG** ).That you do low damage is correct based on the new Azarael's system.

**Comment by Ryanfawkez** [comment]
Hellcannons were level 10, based on a general fix to set a base level for siege equipment in each tier. They have been changed to game objects for now, and require to be right clicked for quest completion.

**Comment by Soulwhisper** [comment]
Workaround?

**Comment by Soulwhisper** [comment]
Ok today **26/08/2016** i tested again firing hellcannons with Empire Cannons and it did damage.Destroying them didnt register on Quest though.

**Comment by Soulwhisper** [comment]
Checked 3 times in a row the PQ. **28/08/2016**
![pordh_000](https://cloud.githubusercontent.com/assets/16864486/18034543/6e214b1e-6d48-11e6-9742-2a1229b37951.jpg)
![pordh_001](https://cloud.githubusercontent.com/assets/16864486/18034544/6e227b56-6d48-11e6-8ecb-53d147f4a74e.jpg)
![pordh_002](https://cloud.githubusercontent.com/assets/16864486/18034545/6e23ee14-6d48-11e6-9f65-e97d68cdee3c.jpg)
![pordh_003](https://cloud.githubusercontent.com/assets/16864486/18034546/6e282cc2-6d48-11e6-9a3c-92365546bd2e.jpg)
![pordh_004](https://cloud.githubusercontent.com/assets/16864486/18034547/6e2eee0e-6d48-11e6-8cde-f83449e5292f.jpg)
