### ISSUE TITLE
problem with input different characters

### ISSUE THREAD

**Issue by Vasiliy543** [WarEmu/WarBugs#714]
Welcome on the server created five characters, but I can play only one , the choice of the rest after the loading screen throws back to the character selection screen , I can only play a warrior prist.

**Comment by Evildoor** [comment]
If this problem still persists, try typing /stuck (Enter - /stuck - Enter) during the loading screen. If the problem persists EVEN after that, create a thread here:
http://www.returnofreckoning.com/forum/viewforum.php?f=4
