### ISSUE TITLE
Vorque skaven npc Destro starting area

### ISSUE THREAD

**Issue by FreedomFighter08** [WarEmu/WarBugs#7140]
The skaven npc inside the crypts isn't giving out his quest anymore until lvl 2 where you fetch his sack, this has never happened before.

**Comment by Ryanfawkez** [comment]
Quest level fixed to 1.

**Comment by FreedomFighter08** [comment]
Can you also fix that the first npc giver give out all quests at the same time because when you get down the hill and starts questing around the first PQ you can see that there's still a quest you haven't taken yet because you leveled up and now you have to run all the way up the hill back to the first npc quest giver just to grab it, it's like quests that should be given directly are on delay because you need to level up but why would you want to run back to grab them when you want to move forward to the next questing area, and also that the npc next the renown npc gives you the quest to deal with the dwarf gyrocopters directly instead of skipping it because now you have to run back and accept it too at a later level.
