### ISSUE TITLE
Order and Destro Starting Area-Quests Gone

### ISSUE THREAD

**Issue by FreedomFighter08** [WarEmu/WarBugs#7141]
Several quests are not as they were yesterday, so MANY are just gone and some you need higher lvl for, nothing makes sense anymore

**Comment by Luth-RoR** [comment]
I have to close this as "many quests" is too unspecific and the report would stay open forever.

Also: DB devs confirmed to me that quest chains have been linked together in the last patch, e.g. 
http://warhammeronline.wikia.com/wiki/New_Recruits
You need to do the first quests before other ones will be available, like on the original server. But it's still a bit work in progress so not every follow up quest might work.
Level requirements should have been altered too, to match the mythic req.

**Comment by FreedomFighter08** [comment]
too many to count and too disorganizing, why would you want to run back because the quest comes later, doesn't make sense, starting areas are suppose to move forward from location to location not run all the way back to a starting npc because she needed u to be lvl 2 or lvl 3 etc etc etc

**Comment by Luth-RoR** [comment]
It should be balanced out if everything works well (like on the mythic servers):
At the time you arrive at the NPC to catch the quest, you should have the appropriate level (if you didn't left quests out). 
But the forum is for the discussion of changes/fixes like this one, this here is the bugtracker.

**Comment by FreedomFighter08** [comment]
That's the thing, when you arrive at the starting place as human Grimmenhagen Village there are like 5 quests that aren't there because you aren't lvl 3, there's a long way to lvl 3 because you just turned lvl 2, everything is just broken atm, you have to queue scenario if you don't wanna grind mobs, nothing works well in either starting area, I'm at grimmenhagen village right now and I have no quest to deliver or receive because I've done all available, i'm still missing 5 of them for this broken reason

**Comment by Luth-RoR** [comment]
I never wrote that it works perfectly now (_alpha phase_).
You already made a thread about that topic on the forum: https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=16046

**Comment by FreedomFighter08** [comment]
Yeah but it actually worked perfectly yesterday prior to this new change regarding quests, nothing to complain about then

**Comment by Ryanfawkez** [comment]
I'm on it.
