### ISSUE TITLE
Savin me Hide

### ISSUE THREAD

**Issue by footpatrol2** [WarEmu/WarBugs#7142]
The patch you just installed has done something to the savin me hide animations. 

Previously on august 7th 2016, savin me hide animations were working correctly, affecting the BO and his groupmates. 
. 
Now August 8th 2016 savin me hide animations do not happen at all. 

Just a friendly reminder.

**Comment by Luth-RoR** [comment]
Referring to: https://github.com/WarEmu/WarBugs/issues/6078

**Comment by footpatrol2** [comment]
fixed
