### ISSUE TITLE
Pillager's Approach - PQ Order Chapter 3

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7143]
UPDATING HERE @Luth-RoR 
- [x] Stage 1 has mob respawns issues.
- [x] Mobs are not exactly as the objectives say.For example Overseers are over 10.Raiders are less then 50.
**But that wont be a problem if respawns work.**
![warhammer online age of reckoning 12 19 2016 - 00 47 18 04](https://cloud.githubusercontent.com/assets/16864486/21297226/bb62caa8-c584-11e6-9731-eb50b81882e5.png)

**Comment by wargrimnir** [comment]
Reduced kill count at this PQ. 30 required, 36 are present.

**Comment by Soulwhisper** [comment]
- [ ] There are some Overseer duplicates on Stage 1.

**Comment by Luth-RoR** [comment]
From https://github.com/WarEmu/WarBugs/issues/8930:
_This public quest is buged. the mobs are all dead and they dont respawn its stuck at stage 1 Cruel Overseer9/10, Murderous Raider 27/30. you also cant finish the quest "Promise of Battle" because the raiders wont spawn._

**Comment by Soulwhisper** [comment]
#8935

**Comment by wargrimnir** [comment]
Such a bother, removed the norespawn flag in next. I'm guessing destro came by and killed a champ to bug it out or something.
