### ISSUE TITLE
The Burning Windmill - PQ Order Chapter 2

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7144]
- [x] The only issue is that in Stage 1 Cultists inside bubbles can be pulled with AOE(even pulling Horrors you pull Cultists too because of the link system),on live they couldnt.
  **_If this can be fixed with a workaround to put some barriers around the bubbles so they cant be pulled out in Stage 1 it would be nice unless it needs scripting._**

**Comment by Torquemadra** [comment]
they are "linked" via Azaraels tether system due to the current system of PQ phases and didnt show on dev due to just killing them, will get fixed as soon as can get to it.

**Comment by Soulwhisper** [comment]
Yeah Torque...i forgot that too...they can be pulled too because they are linked also with Horrors :+1: Could you secure them from AOE though? Also there is an annoying bat in the PQ.

**Comment by Soulwhisper** [comment]
Patched.
Now i guess it just only needs the scripting for bubbles and pathing for final stage.
