### ISSUE TITLE
Shrine of Tzeentch - PQ Order Chapter 12

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7146]
- There are no Shard of Charges on Stage 2 so you cant progress.
- Also the Lore of the PQ is not correct. It should be : 

**Stage 1: Keeper of the Shrine**

**Stage 2: Celestial Wizard Shards**

**Stage 3: Tzeentchian Artifact Defeated**

**Comment by Razielhell** [comment]
This work on Dev. Checking on Live now.
