### ISSUE TITLE
Cult of the magus - PQ Order Chapter 11

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7147]
- Mobs are out of PQ and killing them doesnt reward influence nor counts them.
  ![maxeras_004](https://cloud.githubusercontent.com/assets/16864486/17500508/c5c0c9b8-5dde-11e6-8700-35c429635e28.jpg)
  ![maxeras_005](https://cloud.githubusercontent.com/assets/16864486/17500509/c5c31b78-5dde-11e6-9f00-edd1f4f260cd.jpg)
  ![123](https://cloud.githubusercontent.com/assets/16864486/17837002/aa52fa22-67af-11e6-8ab9-ab3462800f51.jpg)
  And many other.
- There are many Devourers inside the cave for Stage 2 that are duplicate and most of them fall out of the PQ too.

**Comment by Soulwhisper** [comment]
PQ can be completed.

**Comment by Luth-RoR** [comment]
:confused: Was there a stealth fix?

**Comment by Soulwhisper** [comment]
Nope it always worked.Just a lot of mobs fall out of the PQ area as i mention above.

**Comment by Luth-RoR** [comment]
Ok, thx.

**Comment by Soulwhisper** [comment]
#8935

**Comment by grunbag** [comment]
Fixed in next patch
