### ISSUE TITLE
Empire Ch. 3 - Nordland - Quest: "Trade Wars"

### ISSUE THREAD

**Issue by Shardreg** [WarEmu/WarBugs#7149]
The "Angry Dwarf Merchant" that gives the quest Trade Wars (Kill 30 enemy players, collect 5 trade goods from the RvR area) is not there anymore.

The NPC was unstable this weekend, disappearing and reappearing, but now he seems to be gone for good.

My Dwarf "Hjaldir" has the quest open (and completed), if this helps to track it ingame.

**Comment by Ryanfawkez** [comment]
Intended.
