### ISSUE TITLE
Party view

### ISSUE THREAD

**Issue by blanchj** [WarEmu/WarBugs#715]
Some issues that we saw playing on party.

1) All time you see the others players on party like they are at a long distance and then you cant see thier life or buffs.
2) Party leader cant join BG like a party.
3) You cant share quest with party members.

I know that maybe this points are not so important but I going to post all I see and you decide.

**Comment by Evildoor** [comment]
2 was fixed. Not sure about 3. 1 was partially fixed - usually party frames work, but pretty often they are not updated, so you can see your party members as "far away" or "dead" until you click on them. According to some dev talk somewhere, the mechanism of sending packets responsible for this is not 100% clear, so it cannot be fixed yet.

**Comment by Evildoor** [comment]
Update: according to patch notes this was fixed for warbands, but not for scenario groups yet.

**Comment by nalgol** [comment]
3. i just coded a basic group share feature

**Comment by wargrimnir** [comment]
Limit for party information is 300'. Quest sharing is enabled. Full groups can join scenarios.
