### ISSUE TITLE
Quest: A Son's Sacrifice I

### ISSUE THREAD

**Issue by Yukinova** [WarEmu/WarBugs#7150]
Quest is not available.. :(

**Comment by Luth-RoR** [comment]
Was this one of the quests of from the last event?

**Comment by Yukinova** [comment]
http://warhammeronline.wikia.com/wiki/A_Son's_Sacrifice_I

**Comment by Luth-RoR** [comment]
Maybe the minimum level req. was changed last patch. Needs confirmation from DB dev if intended.

**Comment by Ryanfawkez** [comment]
Attainable at level 2 now, as it should be.

**Comment by peusnaugrim** [comment]
The quest is available now but the last reward (choose between 4 trophy isn't working) here. he don't give trophy even if I select which one I like
