### ISSUE TITLE
Chosen aura timer not working

### ISSUE THREAD

**Issue by Neothrell** [WarEmu/WarBugs#7151]
Hi fr player, i try to explain correctly this issue.

I played chosen in official game and when i activate a new aura, the last one activated had a timer to shut down (12 sec). 
Today if i activate a second aura, the first one stay activated ans i can have 2 aura activated permanently.

Sorry for my english and thanks to your attention.

**Comment by Zealote** [comment]
This was an intentional change, you can now have 3 auras up permanently. 

See this forum thread: https://www.returnofreckoning.com/forum/viewtopic.php?f=11&t=8768&hilit, under Knight/Chosen.

(PS No need to apologise for your English, it was perfectly understandable :) )
