### ISSUE TITLE
Pierce Armor WS BUFF - Witch Elf

### ISSUE THREAD

**Issue by Krimalicious** [WarEmu/WarBugs#7156]
The PA weapon skill buff is not increasing parry %, after I get the buff about 102 WS my parry rate stays the same.. 

Proof - https://www.youtube.com/watch?v=EUSOj09ALAE
Min 1,55

**Comment by Zealote** [comment]
Your link's to a github url :P

**Comment by Krimalicious** [comment]
Fixed,, TY

**Comment by Luth-RoR** [comment]
The character window is still unreliable regarding stats and especially for parry/block/etc.

**Comment by Evildoor** [comment]
#6196?

**Comment by Luth-RoR** [comment]
Thanks.
