### ISSUE TITLE
SH Pet still Dissapearing

### ISSUE THREAD

**Issue by cervaes** [WarEmu/WarBugs#7157]
Hello,

I have still problems with my pet...
My squigs randomly disapear for 10-20 secs but my skill for squig is still lit up. Recall doesnt work, need to resummon squig.

We have write to Github bugtracker too, but nothing is happening... 
Link: https://github.com/WarEmu/WarBugs/issues/5714
Video: https://www.youtube.com/watch?v=cyWbeyAuCqA&feature=youtu.be

I hope we will get some ETA or Fix for it!

THX!!!

**Comment by Luth-RoR** [comment]
> I hope we will get some ETA or Fix for it!
