### ISSUE TITLE
Bitterschaum Swamp - Order Public Quest Empire Chapter 13

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7158]
- [x] PQ area ID/UI is wrong.
With **RED** are the areas that the UI/Counter doesnt show up and with **GREEN** that shows up.
Needs to be enlarged because in **RED** areas there are MOBs of the PQ Stage 1. Actually the whole lake with **BLACK** should be the area ID of the PQ.
**_UPDATED 29/1/2017_**
![toufekiaaaa_000](https://cloud.githubusercontent.com/assets/16864486/17531186/83e64068-5e83-11e6-9b47-c96b6bdf8447.jpg)

**Comment by Soulwhisper** [comment]
The drawing is not very accurate...but in general it needs rework.

**Comment by saupreusse** [comment]
fixed in next patch
