### ISSUE TITLE
Guild disappeared

### ISSUE THREAD

**Issue by Algenubi** [WarEmu/WarBugs#7159]
Guild name: Eversong
Guild leader: Ainudallire

Guild name: Oi oi
Guild leader: Erola

Both guilds were disappeared at last day of june. I left message on forum, but it was deleted. Topic related to this trouble is closed.

Dear developers! I understand that guild disappearance is not critical problem for server being, and that you may have no time to deal this trouble. But I don't understand, why you can't post any specific message on forum with explanation of current state during more than two months!

I kept all my gold in guild vault, talis & potions. I don't know what to say to my guildmates - if we even could return our guild or not.

Please clarify the situation with my guilds at last. Thank you.

**Comment by Luth-RoR** [comment]
Unfortunately guilds that are completely lost can't be restored according to GM post:
https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=15164&sid=d49c3d2c52a47918127eb4c8db2a4a00&p=177637#p177637
