### ISSUE TITLE
Mail bugged again

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#716]
After server crash few min ago (12.30 cet), items disappear again when you try to mail them.

**Comment by Thorgatin** [comment]
It was not fixed, the red launcher message just was not readable anymore in the, because of the RvR event anouncement: http://www.returnofreckoning.com/forum/viewtopic.php?f=2&t=3505

**Comment by Evildoor** [comment]
This was fixed, and i heard nothing about problems with mail during last weeks.
