### ISSUE TITLE
253 extra points for choosing renown abilities, seen on 2 different characters on same account.

### ISSUE THREAD

**Issue by brinnande** [WarEmu/WarBugs#7161]
Noticed today when trying to upgrade new renown abilities at the trainer that I had a lot more points available for use then what should be possible (253 points higher then my renown rank, so 255 with the 2 points previously not in use). I had not played for a while so did not know if it was a known issue or change in the game. I picked abilities worth 254 renown ranks, which afik is more then one can attain normally in the game. Stats in the character window went up accordingly with the abilities. I was also adviced in chat to use the .getstats command, which I did. It showed slightly different stats then the character window, but the renown abilities seemed to still apply.
I have logged out and back in on this char and his status is unchanged (meaing he is still owerpowered).
Logged in on 2 other chars on the same account. 1 of them was as he should be with regards to renown points, but the other one had the same issue as my first character. This char also had 253 more available then his renown rank.
I was unable to get screenshots at this time, I saw some posts that it might be an ongoing issue. 
First time bugreporting, so let me know what else info you might need if needed.

**Comment by Ryanfawkez** [comment]
https://github.com/WarEmu/WarBugs/issues/6020? Should be fixed.

**Comment by Ryanfawkez** [comment]
https://github.com/WarEmu/WarBugs/issues/7075
