### ISSUE TITLE
Martyr's Optimal Relic

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7163]
I took this item from a Blue PQ bag(The norse are coming probaply).
Here is the bug.When i took it it was bound on equip.I never equipped it and the next day i logged in it turned into Bound to Player.I tried to trade it but it said that i couldnt trade this item.I could put it on Auction House normally though.Why it turned into Bound to Player without using it on me and if so why i could be able to trade it in AH if it turned in BTP?There is something wrong with the item probaply.
![martyr s optical](https://cloud.githubusercontent.com/assets/16864486/17536088/40e16ab4-5e9b-11e6-9410-8171258f5351.jpg)

**Comment by Luth-RoR** [comment]
Already known; an old bug with the BoP/BoE implementation: https://github.com/WarEmu/WarBugs/issues/4763

**Comment by Soulwhisper** [comment]
Lol thanks Luth.I even write it on that ticket too.
