### ISSUE TITLE
[scenario] dubious reward

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#7165]
![gabri_131](https://cloud.githubusercontent.com/assets/17765890/17542353/2d0de6ac-5ec8-11e6-9c3a-4a0f05e78c15.jpg)
first time i have seen a not integer number , cannot say if i got 2 or 3 emblems.

**Comment by Luth-RoR** [comment]
High likely due to the new token/item reward system in objective based scenarios (see the latest patchnotes).
Needs confirmation if the log display is intended by the dev or needs fixing.

**Comment by ozarmidrashim** [comment]
dealt with
