### ISSUE TITLE
Exp for Hero / Champ

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#7167]
There's 11,2k exp for champ on BO in t4 but only 2,8k for hero(both 40 lvl)

**Comment by Luth-RoR** [comment]
Needs confirmation if this could happen due to some hidden XP/renown buff in RvR areas when there was a fight in that area recently.

**Comment by ozarmidrashim** [comment]
Intentional, heroes calculate XP differently. XP is granted as if you had a full party attacking
