### ISSUE TITLE
War Lion "Pounce" ability disappeared

### ISSUE THREAD

**Issue by FreedomFighter08** [WarEmu/WarBugs#7168]
Im rank 20 i have obliterator set to grant me +1 for my tree, 5 points into the tree to reach it then 1 point to get the ability so 6 points in total, I got then after some time it disappeared out of my action bar and I couldn't find it in my ability page either

**Comment by Zealote** [comment]
Is it when you remove/switch any of your gear, as in https://github.com/WarEmu/WarBugs/issues/7024 (in the comments; ignore its inapt name :P)?

If so, you should've got the mastery point back and just need to re-purchase the ability.

**Comment by FreedomFighter08** [comment]
No I never switched out the gear which grant the gear bonus I have no reason to do so yet, but the other none set parts those I switch out

**Comment by Luth-RoR** [comment]
In the report linked by zealote he wrote that the bug happens on _any_ gear change.
