### ISSUE TITLE
Land dissapeared upon entering Reikland

### ISSUE THREAD

**Issue by SlaytonTheSly** [WarEmu/WarBugs#7169]
Things around me decided to dissapeare when I entered Reikland from Praag. Just as it happened, I got a message "You have entered Pilgrim's Mount".
[http://imgur.com/a/admUO](url)

**Comment by Zealote** [comment]
That link's to github, just FYI.

**Comment by SlaytonTheSly** [comment]
sec. gonna fix link. weird... worked when I clicked... O.o

**Comment by SlaytonTheSly** [comment]
http://imgur.com/gallery/admUO

**Comment by Luth-RoR** [comment]
You can just drag and drop your picture to the comment field and hit "comment".

**Comment by SlaytonTheSly** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/20950924/17559819/d0422656-5f1f-11e6-8948-33c22644ff90.jpg)

**Comment by Luth-RoR** [comment]
Ok, this is a well known, very old bug: https://github.com/WarEmu/WarBugs/issues/7058
