### ISSUE TITLE
Tactics are forgotten

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#717]
I notice that the way the game remembers the tactics is acting strangely and sometimes seem to forget when going into a scenario or reloading.

**Comment by Tioos** [comment]
This issue can be divided into two cases:
1) Tactics are not visible on their slots. This occurs after first logon, relog and reloadui.
2) Tactics are visible on theirs slot, but they dont grant specific bonuses, or the bonuses are not visible in character's stats tab. 
For example: Brute Force dont give strentgh bonus for my choppa. This happens to me every time after joining/leaving scenario or changing zone. To fix this I have to clear tactic slot(s) and set tactic (Brute Force) again. 
Like I said, im not sure if it is not Char's Stats Tab bug only.

**Comment by Thorgatin** [comment]
Point 2 is just a visual issue. Tested on healer with willpower tactic.

**Comment by Alteren** [comment]
Also having this similar issue. My tactics get reset to another tactic slot (usually a blank one) whenever zoning into scenarios or other zones.

**Comment by Evildoor** [comment]
Consolidating the empty tactic bar problem in https://github.com/WarEmu/WarBugs/issues/81.
