### ISSUE TITLE
Ram glitching with punts.

### ISSUE THREAD

**Issue by Sporc** [WarEmu/WarBugs#7175]
Been noticing this for a while now, but if a rams crew is punted away, and new members fill the ram at around the same moment the previous crew trys to get back on, it will allow more then four players on the ram. This can lead to 10% hits on the keep door. If its happening, you will see a ram swing that you can start, and afterwards it will go to the ram leader, and you'll be adding to its swing.

**Comment by Sporc** [comment]
I've done a bit of testing the past few days and have narrowed down some other issues with the Ram. Should I list separate tickets for those or roll it into this one?

**Comment by Luth-RoR** [comment]
Would be nice if you could open a report for every issue, so that they can be closed if one issue is fixed.
There also some reports about ram problems open already: https://github.com/WarEmu/WarBugs/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20ram

**Comment by Luth-RoR** [comment]
Works on jumping too according to https://github.com/WarEmu/WarBugs/issues/7260

I thought you mean completely new bugs with the ram in your earlier post, sorry.
I closed your other report, as both are high likely connected/have the same root of the problem.

**Comment by Sporc** [comment]
No problem, yeah I think they're all related to the same root issue. Like a second Ghost ram being spawned or something.
