### ISSUE TITLE
 Gutrot Mine - Public Quest Dwarf Chapter 4 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7176]
- ~~Stage 1 doesnt count kills.Cannot proceed to Stage 2-3.~~

**Comment by Razielhell** [comment]
- [ ] Implemented but PQ Tracker issues. Green area is fine. Red area has no PQ Tracker.
![warhammer online age of reckoning 01 30 2017 - 01 05 52 246](https://cloud.githubusercontent.com/assets/16864486/22408877/6291bda0-e689-11e6-97ef-acfba23f675b.png)

**Comment by saupreusse** [comment]
fix pending
