### ISSUE TITLE
Open Parties and Warbands Window

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#7178]
- This one is old and probaply its client related but there is no report so far for it so here we go.
- Hovering the mouse over Parties/Warbands sometimes doesnt display the area(Its just blank) that the group is.Mostly for PQs but sometimes for RvR groups too(Shown as PvE).
- Also on live you could make your party open even if you were alone so someone else could join in with you.Now ticking the box and even refreshing doesnt create a stand-alone "party".

![maxeras_006](https://cloud.githubusercontent.com/assets/16864486/17567105/b2f1b6ee-5f46-11e6-84a5-1de230a849e3.jpg)

**Comment by Luth-RoR** [comment]
Could be also because the party/WB packets are not yet completely decoded.

**Comment by MaxHayman** [comment]
Should be fixed
