### ISSUE TITLE
Kron Komar Gap - Public Quest Dwarf Chapter 3

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7179]
- No UI and no influence farming the mobs in the area.Doesnt work at all.

**Comment by Luth-RoR** [comment]
Iirc this was a PQ where both factions can battle each other and need to fulfill goals. Probably not yet implement due to it's special nature.

**Comment by Soulwhisper** [comment]
- [ ] This is implemented and working fine!
