### ISSUE TITLE
Marghaz Bloodtoof Ritual - Public Quest Dwarf Chapter 4

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7184]
- ~~Stage 1 doesnt count kills of Shamans and Boys.~~
- Pq area ID needs to be enlarged.There are Boys and Shamans on Stage 1 among the coast.

**Comment by Razielhell** [comment]
**Implemented**
- [ ] As said above PQ Tracker now showing among the coast where Stage 1 and Stage 2 mobs are.Drawn the area where PQ Tracker dissapears.
![warhammer online age of reckoning 01 31 2017 - 21 52 16 01](https://cloud.githubusercontent.com/assets/16864486/22482079/24d4c2aa-e800-11e6-8557-9f95c9c2d5e7.png)

**Comment by saupreusse** [comment]
fix pending
