### ISSUE TITLE
Always get a error message at end of loading game...

### ISSUE THREAD

**Issue by manowar40** [WarEmu/WarBugs#719]
i ve played till Lvl 5 and then the game is crashed in Norsca with the message "data file corrupted"
and following text :
Data.myp:
System.Exception: You need to stop application currently using the following file: data.myp
   bei MYPHandler.MYPHandler.WriteFileToArchive(FileInArchive archFile, MemoryStream MS)
   bei MYPHandler.MYPHandler.ReplaceFile(FileInArchive archFile, FileStream newFile)
   bei RoRLauncher.Client.UpdateWarData()

Any other charakter is no problem and i can play.... Only this one charakter when i log in i get the error message... character name is Darkhead and is lvl 5...

**Comment by Evildoor** [comment]
Have you removed "read-only" flag from all game files and folders, especially data.myp? If not, do so. Are you playing the game from the folder used by your torrent client? If yes, copy/move the folder somewhere and play from there.

**Comment by Evildoor** [comment]
No response, i guess the problem was fixed. Closing.
