### ISSUE TITLE
High Elf Chapter 3 - PQ Thrallseekers

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7190]
- [x] Stage 1 doesnt count kills.

**Comment by Soulwhisper** [comment]
Implemented and working fine.
This guy doesnt count when you kill him.
![warhammer online age of reckoning 12 24 2016 - 17 50 25 80](https://cloud.githubusercontent.com/assets/16864486/21467782/cf30a2cc-ca01-11e6-94c8-8d4b8d88f6ec.png)

**Comment by sioding** [comment]
Fixed with patch from 1.12.2017
