### ISSUE TITLE
Black Fire Basin - Emblems win reward

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7192]
You received 7.5 Emblem ?? Isnt that suppose to be 5+1 for Victory?
![maxeras_009](https://cloud.githubusercontent.com/assets/16864486/17570491/4be98f12-5f55-11e6-9f70-5af753988ea1.jpg)

**Comment by Zealote** [comment]
https://github.com/WarEmu/WarBugs/issues/7165

**Comment by Soulwhisper** [comment]
Ty man
