### ISSUE TITLE
High Elf Chapter 15 - Da Orcwerks

### ISSUE THREAD

**Issue by PandaOrc** [WarEmu/WarBugs#7193]
One person Noronn just got 1st contribution and he rolled 0 as 000000 which should not be happening as far as I know. 

After finishing stage one we automatically went to stage 3 once as well.

**Comment by Soulwhisper** [comment]
This happened to the Blighted Farm PQ too yesterday after Hotfix happened.Before all rolls were ok to all PQs i were doing at all Tiers.

**Comment by Soulwhisper** [comment]
Also same with this old one. #6957

**Comment by Soulwhisper** [comment]
This is fixed @Luth-RoR
