### ISSUE TITLE
Issue About Burn, Heretic! Ability Relevant With Accusation

### ISSUE THREAD

**Issue by SymbioteWolverine** [WarEmu/WarBugs#7196]
Well I used my Burn, Heretic! Ability and it was't coutned as I hit with it since my Accusations wasn't consumed and cooldown applied. Then I used Absolution.

**Comment by Kaelang** [comment]
Appreciate this is a dated report - however this does not provide enough information to identify the issue and/or replicate the problem. Please re-open this issue if this persists in the latest version of RoR.
