### ISSUE TITLE
"The True Test" NPC wrong location and door doesn't work

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#72]
Npc (Captain von wilke) should be inside tower earth floor, furthermore tower door do not work and so even another chapter1 quest cannot be done .
![the true test](https://cloud.githubusercontent.com/assets/7527415/2921301/a15e98d2-d6f1-11e3-9e4c-d1b9abc6d90a.jpg)

**Comment by Reggaewaldo** [comment]
This has now been fixed so that you can acess the tower.

This can be closed.
