### ISSUE TITLE
Fall damage won't kill

### ISSUE THREAD

**Issue by Lileldys** [WarEmu/WarBugs#7201]
If Fall Damage would kill you, you take no damage.

Tested with the bridge closest to Order WC in DW. If you walk off this bridge, you'll take 90% fall damage. If you jump, you take 0 damage.

Strangely, falling in water now causes you to take damage.

**Comment by Zealote** [comment]
Guess this is the explanation for #5672 and #5730.

**Comment by sioding** [comment]
**Thanks for the report.** Since there is no confirmation, i will close this issue now. Please make sure to follow the bugtracker rules which you can find here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)
