### ISSUE TITLE
Black Fire Basin: spawn point distance to objective

### ISSUE THREAD

**Issue by edavoc** [WarEmu/WarBugs#7202]
It seems like Destruction's spawn point in the scenario Black Fire Basin is closer to the flag objective than Orders. Every time I have done this scenario on order and rush to the flag all of destruction's players are already at the objective before I can reach them to stop the claim. This is a huge advantage to destruction in this scen as they always get the first claim of the flag no matter how quickly order can get to the point. Please look into readjusting the distance to the flag from the spawn points because of right now it seem unbalanced in the favor of destruction.

**Comment by Luth-RoR** [comment]
I think the flags are like on the mythic server, aren't they?
Also: there are mounts with different speed in the game atm.
How big is the estimated time difference and was the fasted mount used?

**Comment by edavoc** [comment]
This is t4 so both sides should have 60% mount speed. The time difference is about 5 secs or so, enough to give them time to cap the flag before we can reach it. I'll have to do some testing later tonight, but almost every time I've done this scenario destruction is at the point before order can reach it.

**Comment by Luth-RoR** [comment]
I asked because not everyone has 100 gold for the fastest mount when he hits T4. 
But 5 seconds is pretty much.

**Comment by edavoc** [comment]
Might be closer to 3-5, I'll try to get a more accurate time later, when I log on.
