### ISSUE TITLE
T1 Lair Boss x2 the same drop

### ISSUE THREAD

**Issue by FreedomFighter08** [WarEmu/WarBugs#7203]
Drops 2 of the same item for 1 class

**Comment by Soulwhisper** [comment]
Were there 2 of this class in group?

**Comment by FreedomFighter08** [comment]
No i've done it a few times and it has never been 2 of the same class in the group, it drops x2 anyway

**Comment by Soulwhisper** [comment]
Maybe #6456 ?

**Comment by FreedomFighter08** [comment]
This was T1 Ekrund Bandit queen, yeah but same thing obviously
