### ISSUE TITLE
Character Selection Screen Weapon Appearance Not Showing

### ISSUE THREAD

**Issue by FreedomFighter08** [WarEmu/WarBugs#7204]
http://imgur.com/a/5BbN0
 Okey so it's showing my alternate appearance of my helmet but not my alternate weapon, my weapon is "Spite's Greataxe" that's showing but with the alternate appearance of "Greataxe of the Lady" that's not showing on the login screen. 
http://imgur.com/a/zLMcN

**Comment by Luth-RoR** [comment]
Known https://github.com/WarEmu/WarBugs/issues/4181
