### ISSUE TITLE
Castle Grauenburg PQ - Empire Chapter 16

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#7205]
**UPDATED 28/08/2016**

Nothing to report.

**Comment by saupreusse** [comment]
The Devil Himself created this PQ.

**Comment by saupreusse** [comment]
all mobs are giving influence and are counted. the counter resets itself to a random number very often and wont update the progress correctly. (mostly if you get near the great castle). in stage two the counter will not work, but the quest will be completable nonetheless. all champions were spawned. sometimes if you are the first to enter an PQ area, the mobs wont show. relog or revisit the pq and it should be working. Nothing that i could fix right now.

**Comment by Soulwhisper** [comment]
https://www.youtube.com/watch?v=OHD7J1rdab8&feature=youtu.be

**Comment by sioding** [comment]
Fixed with patch from 6.1.2018
