### ISSUE TITLE
Fields of Ruin PQ - Empire Chapter 15

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7210]
- Stage 1 doesnt work.

**Comment by thorbolt80** [comment]
Quest is working now. But there is 2 "rebel strongarm" (mob to kill on stage 1) at 9.51. They don't count for kill when you kill mobs. (May be slighlty too much North of PQ)

**Comment by Lheana** [comment]
I think this has been fixed in previous patches.
