### ISSUE TITLE
T2 Dwarf Influence is bugged for several of my characters (and only T2 Dwarf)

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#7215]
![zyreelle_002](https://cloud.githubusercontent.com/assets/19625008/17633283/c1ee4d24-60cc-11e6-9a85-2c9974b5e301.jpg)
 
And with that, my influence bar is full while it should be empty. And it only happens with Dwarf T2. I had unlocked Dwarf T1 before so it's not a matter of needing the first one to get the second. And going to the other WC doesn't change anything. However I usually always go into Dwarf T2 through MoM (because since I play Order, we attack there), so maybe a flag or something like that in MoM is malfunctioning? 

It's seriously infuriating because when I create a character, it's the lottery to know if I'll be locked out of a third of the T2 RvR rewards. Can anything be done to fix that for my character? If not, it'd be nice if someone could look into that bug.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/6753
One report for the same issue is enough. Please use the open report you have already posted in.
