### ISSUE TITLE
The Guns of Nordenwatch Quest

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7216]
- Can be done twice by my  40 LVL Engi.

**Comment by Luth-RoR** [comment]
Iirc this is one of the scenario quests. Wasn't this one always repeatable?

**Comment by Soulwhisper** [comment]
It says to speak with the NPC you take the quest from.I took it once - speaked to him - finished it and it gave it to me again. Not the kills.

**Comment by Luth-RoR** [comment]
kk, thanks for clarification.

**Comment by Soulwhisper** [comment]
We fight tickets together Luth! You are not alone.No problem :+1:

**Comment by saupreusse** [comment]
Fixed in next patch
