### ISSUE TITLE
The Dragon Gate PQ - High Elf Chapter 7

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7217]
- [x] On stage 1 Deathrain and Deadaim mobs are 15-16 level.Siegewarriors are 28-29...need to be 15-16 or a little above then that maybe 16-17.Not higher for sure! PQ is for 14-15 ranks.
- [ ] PQ area needs to be fixed/bigger.There are mobs Northeast of the PQ and there is no UI there.

**Comment by wargrimnir** [comment]
Changed level of Siegewarriors

**Comment by Razielhell** [comment]
PQ issue only left.
