### ISSUE TITLE
Preemptive Strike PQ - High Elf Chapter 7

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7218]
- Duskblades inside the cages(move in to out) dont count nor give influence.So they fall out of PQ.
  P.s. Actually its 1 or 2 of them.
- Deathblades on Stage 2 some outside the cages dont count nor give influence.So they fall out of PQ.

**Comment by thorbolt80** [comment]
On stage 2 : 50 uthorin guard should pop. We got nothing.
