### ISSUE TITLE
Lair of the Dead PQ - High Elf Chapter 7

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7219]
- On Stage 2 Deadwoven at least Champion mobs shouldnt spawn.It makes it impossible to reach Dhar Stones to repair them.Stage should spawn only normal mobs or only Champions and **NOT BOTH**.

**Comment by Lheana** [comment]
NPCs 'Deadwoven Champion' will no longer be Champions.

**Comment by sioding** [comment]
fixed with patch from 8.12.2017
