### ISSUE TITLE
A login Issue That I am not sure about.

### ISSUE THREAD

**Issue by bender072** [WarEmu/WarBugs#722]
when I start my ROR launcher it will go to the loading screen. After it loads it proceeds to the server authentication. the very right where the black box is where it starts to tell you when you are connecting to the server it remains completely blank. After 30 seconds to a minute it crashes with a critical error saying Authentication failed -- application will now terminate. even if I create a new account, and every time it reaches the server authentication process.

**Comment by bonesoul** [comment]
@bender072 how you fixed it? having the same issue here.
