### ISSUE TITLE
Ostland Quest Desire for corruption

### ISSUE THREAD

**Issue by takopa** [WarEmu/WarBugs#7223]
chaos chap 7 (kournos campement)
the quest ask to kill a player ennnemy (validate) and to find a Rusted chest in the monastery of morr (pvp area)
I was looking around for 1 hour but i didn't find anything, It's possible that i didn't find it, but i think  the chest is simply not there.

Sorry for my english (french). Thank you, bye.

**Comment by Ryanfawkez** [comment]
The chest is there.

**Comment by DurinThornaxe** [comment]
I can't find the chest either. What am I missing?
![Image 2](https://user-images.githubusercontent.com/86794706/140947740-03674f63-940c-45a0-b088-c3bd691e126f.jpg)

**Comment by takopa** [comment]
‌
 

De : "Durinsson"
A : "WarEmu/WarBugs" ,"takopa" ,"Author"
Envoyé: mardi 9 Novembre 2021 15:57
Objet : Re: [WarEmu/WarBugs] Ostland Quest Desire for corruption (#7223)
 

 

I can't find the chest either. What am I missing?


—
if i remember well this original post concern destruction side , but i made it in the order side i found it around this place ut i don't remember exactly what it was look like
sorry i can't help you more (1 or 2 weeks ago)

You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
