### ISSUE TITLE
Mirelen - Public Quest High Elf Chapter 5

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7224]
- [x] PQ area ID is missing.No progress cant be made at all.

**Comment by Soulwhisper** [comment]
- [ ] Lord Azurael Hero in Stage 3...if he somehow gets killed by NPCs he doesnt respawn again so you cant finish PQ.

**Comment by Lheana** [comment]
Order Champions are now assigned to the second stage, they will no longer be there during the last stage thus the last boss should not be killed anymore by NPCs. Moreover the last boss Lord Azurael can respawn correctly.

**Comment by sioding** [comment]
fixed with patch from 8.12.2017
