### ISSUE TITLE
The Well Springs - Public Quest High Elf Chapter 9

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7228]
- Remove all frenziers and add more Witches.There are not many Witches so it takes forever to complete stage 1 ( X/125 ).
  P.s.Friendly Mobs also ks half of witches so yeah...there should be much much more.
- Stage 2 should spawn only Bloodmaidens.

**P.s. Overall needs mob rearrangement.**

**Comment by Lheana** [comment]
Both Frenziers and Witches will now count for first stage, and reduced the kills required for first stage. Moreover, friendly NPCs will no longer attack enemy NPCs.

**Comment by sioding** [comment]
fixed with patch from 8.12.2017

**Comment by Herdon** [comment]
Just want to report a _cosmetic_ issue with the PQ. 

Ellyrian Prisoners are just looking bored while the Bloodkiss Witches and Frenziers are trying to intimidate them. 
![Passive](https://user-images.githubusercontent.com/2021593/164324929-5fdc5f8c-6803-4751-b602-b58310f9ea92.jpg)
Pretty sure they should be emoting something.

**Comment by lilimx** [comment]
This ticket is closed, please open a new one with your issue.
