### ISSUE TITLE
"Something Hits You For ... " ??Combat bug??

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#723]
Hi.  This bug is seems to be a issue and appears to be not exactly apparent as to it's cause... 

recreation steps:
roll BW
apply Flames of Rhuin to your self..
stand around in the Warcamp Nordland

You will see that your FoR will constantly proc against "something", repeatedly you can see in the Combat Log.

I will theorize that bug is made from one of the Server/Faction wide "buffs", but that it should not be able to cause any interaction with the player..

Types of buffs I am talking about.. Field of Glory?? RvR faction side?? other proximity buff?? RvR proximity buff?? Bolster??

I am guess that a bug somewhere is causing one of these effects to have a irregular effect on the player and can be seen in the Combat Log and in some cases as mentioned, the cause of a strike-back from FoR and likely other similar types of buffs.

By Buff, I don't mean a direct combat ability buff, but am referring to the various effects that are bestowed upon players simply for being in specific areas...  Again, just theorizing a bit.

**Comment by M0rf** [comment]
This happened on the original servers when u had dots on you from someone who was not in the same zone/instance as you and also happened on the attacks made against you from someone in stealth. The game doesnt know what is hitting you so you get "Something".

**Comment by Evildoor** [comment]
@M0rf is correct concerning the game's definition of "Something". Can any BW/Sorc clarify, if the problem with buffs still persists?

**Comment by Evildoor** [comment]
No response, closing.
