### ISSUE TITLE
bug Reference #7121

### ISSUE THREAD

**Issue by Magteridon** [WarEmu/WarBugs#7233]
feel open this post but in the same place you can skip the restrictions placed and access the bug without much problem, I put some photos below
![normak_187](https://cloud.githubusercontent.com/assets/16975012/17643523/ccc2c31a-616c-11e6-9024-ae1d853ff616.jpg)
![normak_188](https://cloud.githubusercontent.com/assets/16975012/17643527/e104b0b8-616c-11e6-8610-6a492a6aceff.jpg)
![normak_189](https://cloud.githubusercontent.com/assets/16975012/17643530/f05736c6-616c-11e6-853e-039e72acd1a6.jpg)
![normak_190](https://cloud.githubusercontent.com/assets/16975012/17643535/fe62bdf8-616c-11e6-8047-47fb22cb6069.jpg)
![normak_191](https://cloud.githubusercontent.com/assets/16975012/17643537/07960984-616d-11e6-86ee-2862c13d97f9.jpg)
![normak_193](https://cloud.githubusercontent.com/assets/16975012/17643539/1ef4992e-616d-11e6-94d6-cc19732ccca5.jpg)
![normak_196](https://cloud.githubusercontent.com/assets/16975012/17643543/2e7452cc-616d-11e6-9143-15a6de97f05f.jpg)

**Comment by Luth-RoR** [comment]
I reopened your old report, thanks. https://github.com/WarEmu/WarBugs/issues/7121#issuecomment-239621677
