### ISSUE TITLE
Gear set bonuses don't show vendor

### ISSUE THREAD

**Issue by FreedomFighter08** [WarEmu/WarBugs#7234]
When you hold the mouse of an armor piece of a set it doesn't show the bonus until you actually equip all pieces

**Comment by Soulwhisper** [comment]
This cant be changed now.And i doubt if it will.Ryan told me that it cant be changed now.You have to purchase a piece.

**Comment by FreedomFighter08** [comment]
Okey but as long as the gear has yellow text it means it's a set?

**Comment by Soulwhisper** [comment]
Orange* Yeah.

**Comment by Luth-RoR** [comment]
A known issue: https://github.com/WarEmu/WarBugs/issues/5373
It worked on the mythic server, so i think it will work here too one day. Atm probably just a lack of knowledge how to communicate it to the client.
