### ISSUE TITLE
Low  T4 influence gain

### ISSUE THREAD

**Issue by Psema** [WarEmu/WarBugs#7236]
After hitting rr40 i get extremely low inf generally even for solo kill  full hp people and even with aao.for example for solo killing with me WE rank 40 AM with 160%aao i took only 100inf.I know i am suppose to get low rp which i do but i asked around and they told me i should get inf normally.

**Comment by Luth-RoR** [comment]
Needs confirmation from a dev if this is due to some custom code (for instance to prevent inf/renown farming) or a bug.
