### ISSUE TITLE
scenario: gromril crossing

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#7237]
![gabri_140](https://cloud.githubusercontent.com/assets/17765890/17644618/c7021b78-618b-11e6-8e00-62559c18236b.jpg)
two control points are free and both have a timer going : how can it be ?

**Comment by Luth-RoR** [comment]
Needs confirmation if intended scenario flag cap mechanic or bug.

**Comment by bloodi** [comment]
I was able to replicate this, basically you can cap flags that are supposed to not be cappable, ie, while a side flag is ticking down, you can go to the base flag and cap it, which should not be possible in the first place.

Also, when the cap that is not supposed to happen succedes, it destroys the flag that was open and throws a handle exception.

**Comment by Luth-RoR** [comment]
From https://github.com/WarEmu/WarBugs/issues/9393

>once last flag is opened to capture,
after that point you can capture it anytime, no matter flag sequence.
so it's possible that 2 different flags are on timer by each realm.
for example, in Gromril Crossing
Pilo O' Warstuff flag is on timer by Destruction
Order capture Da Base Camp flag ( it was opened before )
after both timers up one flag disappear with
[] says: IndexOutOfRangeException was thrown from GivePoint. This object will be destroyed.

**Comment by SecretsOTheP** [comment]
Adding back onto this. 

A solution would be to interrupt any casting that is occurring on interaction, or deny the objective from being captured on the server side upon an objective switching. This is consistent with live behavior.
