### ISSUE TITLE
and when they return they wil make the missing items?????

### ISSUE THREAD

**Issue by denwert** [WarEmu/WarBugs#724]
first missing body armor with black ork,and then the gun Witch Hunter ?patch server disappeared after a horse is inventory for which he gave 5 gold when it is finished?????

**Comment by Thorgatin** [comment]
1. This is very hard to read/understand...
2. There are threads on the forum about missing items.
3. This is a bugtracker, not a forum.
4. Punctuation marks are not pack animals.

**Comment by denwert** [comment]
sent here from the forum supposedly write in bag tracker
