### ISSUE TITLE
Alan Cartwright NPC

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7240]
- Double NPC 57-31 Badlands.Both give the same quests.1 needs to be removed.

**Comment by saupreusse** [comment]
fixed in next patch. he still has doublespawns in this area, but they are far far apart from another. i guess on live he did walk along the road over the whole map.

**Comment by Luth-RoR** [comment]
Can confirm, he wandered along the roads and had a pointless(?) seed quest on the mythic server iirc.

**Comment by saupreusse** [comment]
will keep him in my mind. once we can add some npc movement i will give him back his daily walk.

**Comment by Luth-RoR** [comment]
On destruction it was a stinkin' lil' gobbo, but i'm not sure.
