### ISSUE TITLE
MoM - Rally Master not working

### ISSUE THREAD

**Issue by Malenah** [WarEmu/WarBugs#7241]
In MoM the Rally Master Breaka da Big doesn't show any rewards (grayed out or not) available for the characters for RvR Influence. The issue happens also to other characters, it's not account related.

**Comment by Luth-RoR** [comment]
Known issue: https://github.com/WarEmu/WarBugs/issues/6753
Dwarf/Greenskin T2 RvR influence seems to be generally buggy.
