### ISSUE TITLE
Guild leader issue

### ISSUE THREAD

**Issue by Toriaz** [WarEmu/WarBugs#7243]
Hello, 

I have the guild leader bug as well for my guild, and lost almost all guildmates.
Could you please set me as sole leader?

Kind regards,
Barbaak - Troudz

![barbaak_005](https://cloud.githubusercontent.com/assets/21013785/17645725/1f9ef5fe-61ae-11e6-96c5-5ef0746bd690.jpg)

**Comment by Luth-RoR** [comment]
Hi,
please PM the gamemasters on the forum for support issues like that one. 
They can remove the duplicate guildmaster.
