### ISSUE TITLE
Influence Bar 

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#7244]
This is a very specific Influence bar bug.
If you are 1,2 or 3 level Influence Bar wont show up(It show only text)! From Chapter 1 of Empire to RvR T4 of ELVES doesnt matter.By the time you level up to 4 level then it somehow unlocks.

**Comment by Soulwhisper** [comment]
P.s. I was told that this has something to do with packets.

**Comment by Soulwhisper** [comment]
P.s. I was told that this has something to do with packets.

**Comment by Soulwhisper** [comment]
P.s. I was told that this has something to do with packets.

**Comment by Kaelang** [comment]
As this is a legacy issue, and lots has changed, please re-open if this issue persists as it should be fixed.
