### ISSUE TITLE
Supply Lines Quest

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#7245]
Participating in 3rd Stage of Raven Host Vanguard wont complete the quest.Looks like it only works by participating in Stage 1.

**Comment by Ryanfawkez** [comment]
Correct. Current objective is to kill a Raven Host Marauder, which only appear in stage 1. Quest completion based on PQ participation is not yet supported.

**Comment by Lheana** [comment]
The quest works now.
