### ISSUE TITLE
Plague Mist Vale PQ - Dwarf Chapter 15

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7246]
- [x] Many Stage 1 Mobs (Weeping Sore Cohorts) fall out of the PQ area and killing them doesnt reward nor progress the stage.

**Comment by Soulwhisper** [comment]
- [ ] Contagion the Blighted in Final Stage spawns twice and is beeing attacks by his duplicate and the surrounding mobs.

**Comment by Soulwhisper** [comment]
#8935

**Comment by grunbag** [comment]
Fixed in next patch
