### ISSUE TITLE
Skaven maze and obstacle course.

### ISSUE THREAD

**Issue by J0t4ro** [WarEmu/WarBugs#7248]
Hello,

I reported this to Grandpaa in-game and he told me to make a report about this here.
I have done the Skaven Maze quest and the Skaven obstacle course a while back, but when i was walking through Altdorf i saw they became available again.
So i was able to do it again a second time for the rewards, i'm guessing this also goes for the one at Emperor Karl Franz etc.
And after talking to gramps, i know this isn't normal.
I added a screenshot to show you that i got the rewards for a second time.
(Note: Can't wear the trophy twice though.)
![lord_000](https://cloud.githubusercontent.com/assets/21017640/17647532/6eb19688-61f4-11e6-98bb-1c7912037a0f.jpg)

**Comment by Luth-RoR** [comment]
Probably related to the DB problems a while ago. Needs confirmation from DB devs if a fix is possible at all.
