### ISSUE TITLE
Range DD NPCs don't switch to melee attacks in 5 feet range

### ISSUE THREAD

**Issue by J0t4ro** [WarEmu/WarBugs#7249]
Hello,

I know this skill only affects melee attacks and not ranged but when you get close enough to certain mobs they switch to melee attacks but they're not affected by "On Your Guard!" and will receive no damage in return when they perform a melee attack. 
I only noticed this when i was mass pulling low mobs for salvage items, so i don't know if this applies to other mobs that have the same way of attacking.
e.g. in Ellyrion, Shady Towers PQ

**Comment by Lileldys** [comment]
They are still using ranged attacks, but displaying melee animations. You still have to dodge them.

**Comment by Luth-RoR** [comment]
Needs confirmation from a Dev if working as intended or not.

**Comment by ozarmidrashim** [comment]
OYG! works as intended. Issue is that ranged NPCs do not switch to a melee attack if attacking at short range.
