### ISSUE TITLE
Killing range NPCs (no loot, no quest update)

### ISSUE THREAD

**Issue by thasos** [WarEmu/WarBugs#7251]
Hi,

Impossible to loot Elohir Silverhawk (but I see the hand when mouse is over the corpse), also he repop naked, if it help...

Thank you :)

**Comment by thasos** [comment]
ha, you can loot him (and update the quest) by killing him on his spawning spot, if he don't move, it's ok !

**Comment by Luth-RoR** [comment]
Probably related to wonky AI/pathing on range NPCs: https://github.com/WarEmu/WarBugs/issues/6902

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
