### ISSUE TITLE
WP tatctic "Divine Petitioning"

### ISSUE THREAD

**Issue by Gintofag** [WarEmu/WarBugs#7255]
Instead reduce AP cost by 15, increase ability cost by 15 AP.

**Comment by Luth-RoR** [comment]
Was this really tested (for instance with WSCT addon) or just looked at the tooltip?

**Comment by Gintofag** [comment]
On tooltip it's looked like +15 AP to all ability, but have no effect(tested with PURE addon). On supplication it have no effect on tooltip, but have effect real AP cost.

**Comment by Kaelang** [comment]
As this is a legacy issue, and lots has changed, please re-open if this issue persists as it should be fixed.
