### ISSUE TITLE
The Sundered Fortress [PQ] - Order Empire Chapter 17 West Praag

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7257]
- PQ doesnt work at all as @Gintofag says below.

~~- The door cant be opened so you cant enter the PQ.~~

**Comment by Gintofag** [comment]
This quest don't work anyway.

**Comment by Soulwhisper** [comment]
Quest? What quest? If you mean Public Quest then how do you know that its not working if you cant enter it..?

**Comment by Gintofag** [comment]
Yeah i mean PQ, u can climb near fall and went into castle. Already try this yesterday.

**Comment by Torquemadra** [comment]
placing to ryan to fix dooe when he can

**Comment by Ryanfawkez** [comment]
God damn doors. <3

**Comment by Soulwhisper** [comment]
Back2action Ryan? ;p

**Comment by Ryanfawkez** [comment]
https://github.com/WarEmu/WarBugs/issues/6592 for the door issue.

**Comment by Soulwhisper** [comment]
Just realised its duplicate.Thanks for that Ryan!
