### ISSUE TITLE
Witch Hunter

### ISSUE THREAD

**Issue by Pentarch** [WarEmu/WarBugs#726]
Snapshot does not slow target! Making WH useless
 when you come out of stealth your action bar is changed from whatever # u had the main action bar at to #1 action bar. G

**Comment by Evildoor** [comment]
Snap Shot works now.
Second part is true, after using an opening skill your action bar is changed to number 1. However, i don't know if this is a client limitation or something RoR-related. Can anyone clarify?

**Comment by d3BugErr** [comment]
Checked it on my WH. Set up main action bar to show second action bar, entered stealth - bar changed to separate one as intended, used my opener and instead of second set of abilities main action bar is filled with first set.
Maybe should record a video for clarity...

**Comment by wargrimnir** [comment]
Automatic switching of action bars is intended behavior by the client, not a bug.
