### ISSUE TITLE
Ram owner displacement issue.

### ISSUE THREAD

**Issue by Sporc** [WarEmu/WarBugs#7260]
So, if a ram is placed down by a player and then filled by four others, the ram owner can jump on the ram without actually displacing any of the other 4, giving an easy 5 man ram for 5% swings. Tested multiple times yesterday to see if this could consistently be done, and it worked five/five attempts.

**Comment by Luth-RoR** [comment]
Known issue: https://github.com/WarEmu/WarBugs/issues/7175

**Comment by Luth-RoR** [comment]
Sorry, didn't see the other one was your report too.
