### ISSUE TITLE
PQs/Keeps Chests and Bags

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7262]
- By the time chest spawns(Instantly after you finish PQ/Siege of keep),you can get the bag from chest before you Roll.You should wait for roll and final results before interacting with chest.

**Comment by Luth-RoR** [comment]
Ah, that works like on the mythic server. You could always loot the chest before the client showed the outcome of the roll.

**Comment by Soulwhisper** [comment]
Are you sure Luth??? I think you couldnt loot before it rolled.

**Comment by Luth-RoR** [comment]
Yes, it should. But i think this requires client modification. 
On the mythic server you also just needed line of sight for looting a chest, no certain range. This was probably to make looting easier from a different angle when you can also stand far away (when many people stand in a circle around the chest.

**Comment by Soulwhisper** [comment]
@Luth-RoR https://www.youtube.com/watch?v=gropySBbtj8
8:05 Proof of what you said.
