### ISSUE TITLE
Trade / Trading talisman fragments

### ISSUE THREAD

**Issue by Hogie1982** [WarEmu/WarBugs#7264]
Investigating.

**Comment by Luth-RoR** [comment]
Thanks for the report. I deleted/copied the details, dev team is looking into it.

**Comment by Luth-RoR** [comment]
Can you send me further details in a forum PM: https://www.returnofreckoning.com/forum/memberlist.php?mode=viewprofile&u=589

**Comment by Hogie1982** [comment]
@Luth-RoR How do I send a a PM in the forums....? (maybe stupid question, but I cannot sent private message there, yet.)
Regarding add-ons: I'm not using any at the moment.

**Comment by Luth-RoR** [comment]
![luth](https://cloud.githubusercontent.com/assets/8567481/17666984/244423a8-6303-11e6-9784-2fd92d5658ea.PNG)

There should be a "Send private message option", but afaik you need 3 or 5 forum posts for that.
Just post something like "OMG, awesome hotfix!" here: https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16267
:smile: 
If someone asks, tell them i told you to do so.

**Comment by Hogie1982** [comment]
Ok, will do :) cause I dont see the link yet. Would it work when you send a message to my account? Accountname: Hogie

**Comment by Luth-RoR** [comment]
Gonna try it. But i think you would still need some forum posts to answer.

**Comment by Hogie1982** [comment]
OK

**Comment by Hogie1982** [comment]
I don’t know if others are experiencing similar problems with their backpack as myself, but in case you do…do not worry = ) Here’s a little workaround. Actually there are a few different problems which (IMO) are related somehow. Below I describe the problems I experience, followed by the workaround for the problem. SO far I only experience this issue with talisman making ingredients, in particular fragments and Gold Essence . (Remark: I only have it with my alt character which has Slavaging & Talisman making as gathering and crafting skills.)

1)	When acquiring talisman ingredients from salvaging or normal loot they sometimes seem not to show up in the backpack, not in the main backpack and also not in the crafting backpack. To my experience this is paired with the message in the in log “You could not move <itemname>.” Here, <itemname> can be either any type of fragment (i.e., Savage sturdy debri) or any lvl of Gold essence. 
There are 2 cases. FIRST, you did not have this type of item yet. Then it looks like no new item was added. In first instance one thinks the item is lost, but this is NOT the case. Look in your crafting backpack, and hold the mouse pointer over the first empty slot. There you will notice that the slot is actually occupied. Pick up the item and place it in another empty slot, and it will appear.
SECOND, you already had the type of item, but it was not added to the stack. In this case pick up the stack, and put it on another empty slot.
Remark: In case you were farming, and have several items “missing”. Just check the empty slots in your backpack, or the item in question, and move all items, eventually you will get see all items appearing in correct numbers.

2)	Sometime it seems that several items in the crafting backpack occupy the same slot, which result in the picture of items circulating between different items on the same slot (several different items within a second). This happens spontaneously and can include that an item was moved from its original slot. This was seen for the aforementioned tali fragments.
What works for me here, is quickly right-clicking several time on the circulating slot until the switching between items stops. What one actually does is moving the items to the main backpack, which is where you will find all different items on from the problematic slot.
Three remarks: First, the same problem as mentioned in point 1 can happen in your main backpack, so just check empty slots for missing items and move them to another slot. Second, it can happen that a stack of items splits up, which means that a stack of 5 items, will now occupy 5 slots. Just restack the items =).

3)	Last, but not least, the issue with trading talisman ingredients. When you have the problem, that a trade does not work. Check if any of the items which you have placed in the trade window appears on another slot in you (crafting) backpack.
My procedure in this case is to place items in the trade window, carefully watching if the item currently transferred appears on another slot in the backpack. If not fine, next item. If yes, CANCLE the trade. Then restart the trade, place all items of the failed trade except the last which was problematic. Now the trade should work. Click accept, and continue with a new trade. Now, the problematic item. Open trade window, and place the item there. If nothing happens in the backpack, then accept the trade. If you notice it appearing on another slot, then cancel the trade, and restart the trade. Now it normally is possible to place the item in the trade window without appearing on another slot, and the trade should work. Important, just stick to this single item in this trade. (Since multiple items can be affected it can be tedious (and quite annoying) to trade with them, still with this approach you will be able to trade them.

First, of all I hope that very few experience this problem, still when you read this you probably do. In this case I hope this helps.
Cheers
