### ISSUE TITLE
T2 Order keep doors not resetting

### ISSUE THREAD

**Issue by Swarmofseals** [WarEmu/WarBugs#7267]
I'm not sure what the nature of this bug is, but several times over the past few days I have noticed that keep doors in Order T2 have not been resetting, even after quite a long period of time (pretty sure I saw one hold damage for over an hour yesterday). Of course, this means that there is no def tick either. In T2 Empire v. Chaos right now, Order beat back a Destruction attack which damaged the door of Mandred's to about 80%. Order then went on the attack and got stopped at Stonetroll. The Stonetroll door has already reset once and the Mandred's door is still damaged.

**Comment by Luth-RoR** [comment]
Needs confirmation from a dev if some RvR mechanic could cause this or is intended in certain cases.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
