### ISSUE TITLE
Talisman making - Critical success bug.

### ISSUE THREAD

**Issue by J0t4ro** [WarEmu/WarBugs#7268]
Hello,

I was told to make a report about this so here are the details;
So i had 2 purple fragments, one was made into a purple talisman and the other one was a critical success but ended up blue instead.
And of course, it is worse than the normal one.
I took a screenshot of the ingredients used and outcomes :
![lord_002](https://cloud.githubusercontent.com/assets/21017640/17675481/39e48186-632a-11e6-8633-a9ebfab45d2a.jpg)

**Comment by Lileldys** [comment]
https://github.com/WarEmu/WarBugs/issues/6836
