### ISSUE TITLE
phoenix gate flag dropoff

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#7269]
having been reminded the hard way that you can drop the flag off at the halfway bridge if both realm flags are held i tried to do this myself (playing destruction holding the order flag), when i hit the flag marked "order flag dropoff" i got a popup on the screen telling me that it belonged to the enemy realm, when i trying the one marked "destruction flag dropoff" nothing happened, both realm flags were held at the time so i should have been able to drop it off at the halfway point and score 50 points...

**Comment by Yellowpillow** [comment]
Bug is kinda return, two times flag not drops at the bridge, a made a little video 
https://youtu.be/64zhn3ScXKw
After that scenario I try it more on the next one, and it works fine, bug is disappeared. Can't figure out what triggers it.

**Comment by Yellowpillow** [comment]
Another proof of this bug
https://youtu.be/uLMDZa9YVCs
can someone reopen this report, please?

**Comment by Luth-RoR** [comment]
Sorry, i sometimes don't get mail notifications on reports.

**Comment by Lheana** [comment]
Just had a similar bug in Phoenix Gate that could be linked. Both realms had the flags, destro killed the order who had destruction flag. The destruction flag should have reset but it did not. After a long time, the destro who had the order flag tried to drop it off to the Destruction Capture but he could not, same at the bridge. And finally order could have retaken the destruction flag that did not reset, and they could drop it at the bridge ...
