### ISSUE TITLE
Bugged Brite Mages

### ISSUE THREAD

**Issue by 22635** [WarEmu/WarBugs#727]
![bugmage](https://cloud.githubusercontent.com/assets/12576857/7785519/36d7f988-0150-11e5-9a98-7ec1043ee754.png)

This is screen of my 3rd bugged mage on this account, After creating 1st and getting some lvl's up visiting couple sc's after finishing last scenario I teleportend back but got blue screen, same happened to 2nd mage. But my 3rd mage got blue screen after I got Scenario invitation and ported there,

**Comment by Evildoor** [comment]
Known issue with Zone 0 which has nothing to do with BW. If the problem still persists, try writing /stuck into Say chat, and then Enter - /stuck - Enter during the loading screen. Anyway, closing this, there are plenty of other reports of this.
