### ISSUE TITLE
Stonetroll Crossing Ball

### ISSUE THREAD

**Issue by bloodi** [WarEmu/WarBugs#7274]
After picking it up from the middle, you can cap all 3 zones and when the ball is supposed to reset, it will drop on the ground, letting you pick it again without going to the middle.

It does reset properly after the second run with it, going invisible even if it shows its there on the map and then resetting to the middle, not sure if this happens every time you pick it from the middle and completely cap all points or just happens with the first ball.

**Comment by ozarmidrashim** [comment]
Changed to immediate reset for next patch
