### ISSUE TITLE
Sorcerer Tactic Frozen Fury Bugged

### ISSUE THREAD

**Issue by Zumos** [WarEmu/WarBugs#7275]
Error message when you equip the tactic: "Nonexistent tactic: 9517 Frozen Fury"
The fact that this tactic doesn't work and the Bright Wizard one does grants a huge advantage to the Bright Wizard (and thus order) right now. I hope you can give some priority to this bug as it effects balance significantly.
![zumuss_024](https://cloud.githubusercontent.com/assets/19267650/17700484/359b924e-63c6-11e6-9920-d91060b458b2.jpg)

**Comment by Evildoor** [comment]
#5807

**Comment by Luth-RoR** [comment]
Thanks.
