### ISSUE TITLE
Gold loot bags shouldn't contain gloves or boots

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#7278]
On live gloves and boots (rvr sets) was dropped only from killed players and never was found inside the bags from keep capturing reward chest.

**Comment by Soulwhisper** [comment]
Which bag did contain RvR piece??? And from which Keep did you get it?

**Comment by Ryanfawkez** [comment]
This is correct. We do need details on which Tier and what armor set has boots and gloves from Major bags, though.

**Comment by Nekkma** [comment]
I got the AM Annihilator gloves from a gold (massive?) bag a few days ago from some T4 keep (don't remember which). I have also seen people complain in /t4 about getting boots/gloves from gold bags.

**Comment by Yellowpillow** [comment]
It contained Annihilator boots for my DoK. It was from t4 keep, I don't remember from which particular keep i get this bag.

**Comment by wargrimnir** [comment]
This is intended currently as Conq boots/gloves do not drop from players.
