### ISSUE TITLE
Order Flight Master Nordland->Ekrund.  End up in Mount Bloodhorn

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#728]
I have had this happen several times now..
Take Flight Master from Nordland to Ekrund and you endup around 50k,57k in Mount Bloodhorn.

**Comment by gittoaster** [comment]
I am getting this now also as Destruction, trying to fly from Death's Brink to Mount Bloodhord (off the map)

**Comment by ozarmidrashim** [comment]
#694
