### ISSUE TITLE
zealot tactic "manipulation"

### ISSUE THREAD

**Issue by takopa** [WarEmu/WarBugs#7280]
i don't know which part of this tactic bug but i think after testing it for a while it's a bit too much.
- Distance effect seems to pass 150 ft: i can assist dps one player of my team who is fighting at is limit of distance and heal quietly behind the front line.
- out of view doesn't affect the passif effect :  i can assist dps behind the door (wall) and heal quietly the same way as before.
- the power of the effect do not take in consideration of the real heal but of the potenial heal of the cast :  i can spam heal some full life player and the effect will be full.

sorry for my english (fr) thank you, bye

**Comment by Luth-RoR** [comment]
Number 1 & 2 work like on the mythic server. 
Though i think it was probably a bug that was never fixed; no range restriction and LoS requirement seems to be too wrong to be intended.
About 3: Not exactly sure what is meant here and/or if it works like on the mythic servers atm.

**Comment by takopa** [comment]
the point 3 i was trying to explain if i do a heal  on a character who is full life and so do not need heal. The ability then is activate and consider that i did a full heal.
bye example if i do pandemonium with all my group close enough, It will consider that i did 6 times a heal of 1K  then i will have 6 roll for doing 250 damage to my target, whatever the members of my group were full life or not.
thanks again

**Comment by Luth-RoR** [comment]
I see, thanks for clarification. So it works on "overheal" too.

**Comment by takopa** [comment]
i learn some few technical words thanks as well "overheal". i think i will have to remember this
