### ISSUE TITLE
my characters arnt there

### ISSUE THREAD

**Issue by Goretrex** [WarEmu/WarBugs#7282]
hello 

when i log into ROR it loads up fine but when it goes to character select screen none of my created characters are there and i cant make new ones it shows the picture of the camp site of the order side and i cant do anything please help in how i sort this out thanks.

**Comment by Luth-RoR** [comment]
This is no bug. 
You posted on the bugtracker.
You probably logged in on a different account.
For further _support_ please use the _support forum_.
