### ISSUE TITLE
Oil Attack Button

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#7285]
Once you put Oil when you click it the first time "Drop the boiling oil on the enemy" button works fine (Clicking again doesnt refresh the button).You have to release the Oil and click it again to make it work.
**P.s Dont know if its the same for other Tier or it doesnt only update on T4 Oils.**

**Comment by huntergregg2** [comment]
The same occurs in T3.

**Comment by Soulwhisper** [comment]
Good to know @huntergregg2 This wasnt happening.At least you didnt have to release the oil...you could click on Oil again so it would refresh again.Maybe broke in a patch.But thats not how it is suppose to work...it should refresh automatically on cooldown :P .

**Comment by Soulwhisper** [comment]
The same occurs in T2.

**Comment by Kaelang** [comment]
No longer happens in latest versions of RoR.
