### ISSUE TITLE
T4 Elf epic quest, Unmasking the Enemy

### ISSUE THREAD

**Issue by Grudgegrumbler** [WarEmu/WarBugs#7286]
The t4 elf epic quest, Unmasking the Enemy 

on the part where you are to kill two Wraitwind Lifedrinkers and rescue Taliendhir Fios, you cannot progress as Taliendhir Fios is not clickable. His model is present but we are unable to activate the objective.

Hoping he'll return to normal after a restart, just fyi that he's done this

thanks ;>

**Comment by Razielhell** [comment]
This is fine.

**Comment by sioding** [comment]
checked that - and its fine - close
