### ISSUE TITLE
Instill Fear Morale (SW)

### ISSUE THREAD

**Issue by Lileldys** [WarEmu/WarBugs#7287]
Currently not doing True/Morale Damage.

**Comment by Lileldys** [comment]
If thats a confimation request for me. In the combat log
![adyeta_020](https://cloud.githubusercontent.com/assets/13259775/17774851/8cf944b8-654d-11e6-8a56-35d52ddc74d9.jpg)

**Comment by Luth-RoR** [comment]
Thanks.
