### ISSUE TITLE
Crit on Talisman crafting provides white talisman

### ISSUE THREAD

**Issue by huntergregg2** [WarEmu/WarBugs#7288]
Using green fragments I was crafting lvl 28 (20 int) uncommon (green) intelligence talismans for some alts and crit twice. However, each time I crit I created a lvl 36 (12 int) common (white) intelligence talisman. Shouldn't a crit produce a better quality item and higher lvl item, not just a higher level item with lesser quality?

![talimaker_024](https://cloud.githubusercontent.com/assets/14062714/17752423/993142d0-6480-11e6-9c9c-f26064c4f2ad.jpg)

**Comment by Zealote** [comment]
Assume this is the same as https://github.com/WarEmu/WarBugs/issues/6836, but it doesn't just affect blue frags then.

**Comment by Luth-RoR** [comment]
Yes, already known.
