### ISSUE TITLE
squig herder m3 squigbeast

### ISSUE THREAD

**Issue by M0rf** [WarEmu/WarBugs#7289]
damage increase works but it doesnt increase the size of the squig

**Comment by Zealote** [comment]
https://github.com/WarEmu/WarBugs/issues/5906?

**Comment by Luth-RoR** [comment]
Yes, known thx.

**Comment by M0rf** [comment]
I saw the other report, it said closed and also said the squig grew a bit, when i tested this yesterday the squig didnt grow at all, sadly i dont have enough time right now to search youtube for a vid that shows the correct size, if the correct size is still an issue in the next few days i will try and find one, cheers Luth

**Comment by milosxe** [comment]
https://www.youtube.com/watch?v=zjGw3XZr1ec

after 2 min mark

**Comment by Luth-RoR** [comment]
Thanks.
