### ISSUE TITLE
T4 accessory tome unlock bug (Twisted Hounds are friendly for destro!)

### ISSUE THREAD

**Issue by defleshed2** [WarEmu/WarBugs#7290]
Da Waaagh! Teef (0/4):
Black Toof: (49k, 10k) Travel to Saphery and make your way up to the coordinates given, Southwest of Thornvale Manor High Elf Chapter 13. Slay enough **Twisted Hounds** until you receive Chaos Hound Fang (x10). 

On 17/08/16 I checked this location for 2 hours and all the Twisted Hounds are friendly for destruction.  They were Enemies in the past because people do have the Black Toof [ring].  Would you guys be able to fix it?

P.S Broke Toof spawns for bloodbeast of khrone are not spawning as well so Ryan [DB] told me I can farm 100 PQ's from the starting zone in chaos LOL... so i did.  I worked so hard for this other ring just to see my matching ring ALSO bugged...

**Comment by Ryanfawkez** [comment]
Fixed in next patch.

**Comment by BeepBeepIamJeep** [comment]
ty
