### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by Archangel630** [WarEmu/WarBugs#7291]
Nordland: When traveling through PvE area east of PQ2 (Burning Windmill), south of Order RvR Warcamp, using a mount, typically a wolf enemy npc will spawn or appear on top of player character while riding through the area, and npc is targetable, though target arrows show it a distance further away. Dismounting causes npc to disappear.  Was able to replicate several times, but was not 100 percent successful.  /reloadui does not work.

Ironbreaker (haven't tested other classes): When performing special, then entering into attack or moving to attack, player character is stuck in animation of smoking pipe. Weapons will show in hands but hands are still in position of smoking pipe or performing "special".  Was able to stop the animation by using Book of Binding or using Flight Master to travel elsewhere. /reloadui does not work

**Comment by Archangel630** [comment]
Concerning enemy NPC spawning on top of player character, once this occurs, the game tends to crash to desktop after a few seconds.  Am pretty sure the crash occurs every time.

**Comment by Luth-RoR** [comment]
#1 referring to https://github.com/WarEmu/WarBugs/issues/7292
#2 is a known client side issue in mythics 1.4.8 client and can't be fixed atm

Please only one bug per report, thanks.
