### ISSUE TITLE
The norse are coming ! PQ - Empire Chapter 2

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7293]
- [x] Norse Plunderers on Stage 2 are naked.#6986
- [X] This NPC(The only one) falls out of 1st Stage of the PQ(no infl and not counting him when you kill him).
  ![toufekiaaaa_000](https://cloud.githubusercontent.com/assets/16864486/17780143/0b096534-6573-11e6-990f-7b98b479860d.jpg)

**Comment by Ryanfawkez** [comment]
Need to dress up those pretty boys and include the lone sea dog in the first stage.

**Comment by Torquemadra** [comment]
need to confirm its actually an issue as opposed to items just not loading in on a cycle.

**Comment by Ryanfawkez** [comment]
@Torquemadra - could be for the regular mobs. I know for a fact the heroes and champions in this PQ spawn without clothes at all times. Checking now.

**Comment by Ryanfawkez** [comment]
Hmm, their items are all fine in the wartool. Noticed their subtypes are wrong, though. Fixing that at least.

**Comment by Soulwhisper** [comment]
I dont know if this has been pushed today. **28/08/2016**
Plurenders as you know the spawn 2-2-2-2.
One of each pairing has clothes the other left naked.
Final Hero is clothed.

**Comment by Soulwhisper** [comment]
Checked 3 times in a row the PQ. **28/08/2016**
![pordh_000](https://cloud.githubusercontent.com/assets/16864486/18034543/6e214b1e-6d48-11e6-9742-2a1229b37951.jpg)
![pordh_001](https://cloud.githubusercontent.com/assets/16864486/18034544/6e227b56-6d48-11e6-8ecb-53d147f4a74e.jpg)
![pordh_002](https://cloud.githubusercontent.com/assets/16864486/18034545/6e23ee14-6d48-11e6-9f65-e97d68cdee3c.jpg)
![pordh_003](https://cloud.githubusercontent.com/assets/16864486/18034546/6e282cc2-6d48-11e6-9a3c-92365546bd2e.jpg)
![pordh_004](https://cloud.githubusercontent.com/assets/16864486/18034547/6e2eee0e-6d48-11e6-8cde-f83449e5292f.jpg)

**Comment by Soulwhisper** [comment]
They are still naked.Can someone re-open this?

**Comment by Soulwhisper** [comment]
Many sea dogs on Stage 1 are naked too now.

**Comment by Soulwhisper** [comment]
Works great!That lonely dog fixed.
Only problem is that Mobs are naked which is general problem as i can see.
Closing!

**Comment by Razielhell** [comment]
- [ ] PQ ranks 3-4. Hero level 7...
![warhammer online age of reckoning 02 25 2017 - 00 23 30 02](https://cloud.githubusercontent.com/assets/16864486/23323390/0115a95c-faf1-11e6-9a68-fd4ee73efa5e.png)

**Comment by grunbag** [comment]
Fixed in next patch
