### ISSUE TITLE
Wrong item picture and appearance 

### ISSUE THREAD

**Issue by jpnrd** [WarEmu/WarBugs#7297]
Hi,

I've been doing influence to get the chapter's rewards and encountered 2(3) bugged.

First one, Empire chap. 13, gloves instead of helm and no appearance (shows no helm at all when equipped)
![thrulontin_069](https://cloud.githubusercontent.com/assets/16733126/17794562/d70217a2-65b0-11e6-8ab3-494f8e8c55b3.jpg)

Second one is in Dwarf chap. 21, I haven't unlocked them yet but i guess, as their pictures are inverted, that equiping one of them must give same bug than the first one :) 

![thrulontin_071](https://cloud.githubusercontent.com/assets/16733126/17794699/0d989484-65b2-11e6-9620-e76d9cc315d5.jpg)

thousand thanks for your work! :)

**Comment by jpnrd** [comment]
sorry to bother :/ 

the first helm is truly one but  bugged in appearance
![thrulontin_085](https://cloud.githubusercontent.com/assets/16733126/18034603/619c06c4-6d41-11e6-8d27-a1ed801aea44.jpg)

And the shoulders of chapter21 must have now the correct appearance (for the mini picture has changed) 
but the helm still appears to be shoulders :/ 
![thrulontin_083](https://cloud.githubusercontent.com/assets/16733126/18034615/a2599672-6d41-11e6-949c-a76639fe106c.jpg)


Thanks again for the work, you're awesome

**Comment by Luth-RoR** [comment]
>sorry to bother :/
