### ISSUE TITLE
Emp T1 Lair Boss Fight DC No Loot

### ISSUE THREAD

**Issue by FreedomFighter08** [WarEmu/WarBugs#7298]
This is really sad, just now me and 2 others were waiting for the lair boss to spawn and then during the fight everybody started disconnecting and kept on doing that about 50% of the fight until she was killed. Then none of us got the loot, not anyone, this has never happened before, this must've been because of the dcs affecting the loot somehow, but no loot for anyone, all that commitment for nothing.
Grandpaa GM came to us and he respawned it for us. We went to kill it again and this time a Destro player helped us bring it down to about 5% then he stopped damaging because he wanted us to get the loot, but he got the loot instead somehow, he didn't last hit, auto attack or had dmg on it, and this reminded us of earlier today when we did t1 Elf boss, we brought friends with us who weren't in the group to help us bring down the boss faster but when we got the kill, one of our friends who was helping and who was not in the group got the loot somehow, 100% sure no one other than us did the last hit. Sad day for all of us.

**Comment by Luth-RoR** [comment]
Needs confirmation from a dev, if this can be fixed/tweaked.
