### ISSUE TITLE
Engineer Flame Turret - Wrong Animations

### ISSUE THREAD

**Issue by LordTercept** [WarEmu/WarBugs#7303]
Something I've noticed when using my turret is that the Flame Turret animations don't appear to be working properly, the turret never shows any type of projectile leaving it while it's firing.  Please see the linked video below for an example.  Once again I've tried with and without add-ons to make sure it wasn't something with one of those causing it.

https://www.youtube.com/embed/iCNkbjEEFuw

**Comment by Luth-RoR** [comment]
Known issue: https://github.com/WarEmu/WarBugs/issues/2294
