### ISSUE TITLE
Guild Roster Visual Bug

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7305]
- Once you log in and hit G>Roster> This happens.

**Only way to fix it is to /rel**
![maxeras_000](https://cloud.githubusercontent.com/assets/16864486/17833434/d40d47da-6725-11e6-821b-3a73392b5a1b.jpg)

**Comment by Lileldys** [comment]
https://github.com/WarEmu/WarBugs/issues/1438

**Comment by Soulwhisper** [comment]
@Lileldys Thanks for reference but i see nonone assigned on these(Evildoor left).I suggest keeping this one as it is bugged after latest 15/08/2016 Hotfix.(Worked fine before Hotfix)
