### ISSUE TITLE
[PQ] Empire Chapter 4

### ISSUE THREAD

**Issue by magter3001** [WarEmu/WarBugs#7307]
Killing Bloodbane Devotee doesn't reward influence or contribution toward the PQ. Not able to complete the PQ or get enough influence to start the Empire Chapter 4 quest for the free level scroll.

https://gaarawarrgabs.wordpress.com/2009/12/01/want-a-free-level-a-guide-to-the-war-tract/

**Comment by Soulwhisper** [comment]
#5522
