### ISSUE TITLE
Harbinger of Doom No Longer Converting Int / Magic Crit

### ISSUE THREAD

**Issue by WJamesLord** [WarEmu/WarBugs#7310]
This appears to be a new bug.  I believe Harbinger of Doom worked fine just a couple days ago, but as of today, intelligence and magic crit are no longer converted to wisdom and heal crit.  Oddly, the ability works fine going the other way - wisdom and heal crit are converted to int and magic crit.

**Comment by ozarmidrashim** [comment]
Please ignore the paperdoll.

**Comment by Luth-RoR** [comment]
Closing this as there is a well known issue with stats displayed by the characterwindow. If you want to get the real stats, you have to type .getstats into the chatwindow.
