### ISSUE TITLE
Battlefield Objective's flag can be captured without killing guards

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#7311]
I mentioned that on several BOs, if guards pulled far enough from flag, it can be captured without killing them. In that case all remaining guards are disappearing.
![arena_026](https://cloud.githubusercontent.com/assets/18102127/17837344/0bd7f0ce-67c2-11e6-9b65-a8e43300697a.jpg)

**Comment by sioding** [comment]
Since we have another BO´s system now that works without guards i will close this issue
