### ISSUE TITLE
Gold Bag - Blighted Farm PQ BW - SL

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#7312]
- Doesnt contain the PQ set piece for BW.
  ![pyromanths_099](https://cloud.githubusercontent.com/assets/16864486/17837569/20446dba-67bf-11e6-84a3-837362684b5a.jpg)

**Comment by Soulwhisper** [comment]
Happened Once.Second time i got Gold bag it had boots.If there is a random chance of containing/or not containing a piece then you can close it but i dont think that it should have random chance of containing items or not.It should be in the bag 100% IIRC.

**Comment by BillyMays1** [comment]
same issue for me on the same PQ, and also for Welcome to Troll Valley PQ

**Comment by Soulwhisper** [comment]
Are you a BW?

**Comment by BillyMays1** [comment]
yes

**Comment by Soulwhisper** [comment]
Happened with my Slayer too.
