### ISSUE TITLE
Can't Career Train

### ISSUE THREAD

**Issue by Menstrual** [WarEmu/WarBugs#7314]
I have a lvl 6 Magus that can't career train.  When I select the training available and click "train" nothing happens.  I'm already missing on level 3 and level 6 training.  What can I do?

**Comment by Luth-RoR** [comment]
Career training for basic/core abilites doesn't work yet. You get all non-mastery/renown abilities automatically when you level up.
For magus/engi: https://github.com/WarEmu/WarBugs/issues/4953
