### ISSUE TITLE
Squig's ability - KABOOM and other bugs

### ISSUE THREAD

**Issue by Gesswho** [WarEmu/WarBugs#7315]
After patching  squig's ability - KABOOM any squig can get into those places which are inaccessible to other characters. Today on defence in KV, one of them, ran on a wall and shoot at players, he has got on a wall by means of this ability (unfortunately the screenshot didn't make, but it was seen by several players). 
Other problem: when the player opens before you a door in a Sigmar's Hammer, opens the portal in textural part of Altdorf xD.
If to use a scroll of moving to Sigmar's hammer and to jump up, then the scroll will disappear.
![bootydance_00422](https://cloud.githubusercontent.com/assets/21161944/17840202/c25652b6-6829-11e6-977f-9baa7839f6b0.jpg)
![gesswho_001](https://cloud.githubusercontent.com/assets/21161944/17840203/d410c694-6829-11e6-96e1-bfb4e16741f7.jpg)
![gesswho_004](https://cloud.githubusercontent.com/assets/21161944/17840204/db5b84f2-6829-11e6-871f-2fb6b9c90a49.jpg)

**Comment by Luth-RoR** [comment]
One bug per report please; these issues are completely different from each other.

**Comment by Luth-RoR** [comment]
#1 needs confirmation if the ability can be fixed by a dev at all
#2 is known: https://github.com/WarEmu/WarBugs/issues/6831

**Comment by Gesswho** [comment]
I apologize for the carelessness, I have to edit the message?

**Comment by Luth-RoR** [comment]
No, it's ok. Just create a different report for each issue in the future. :smiley: 
We just wait for a dev response on  number 1.
