### ISSUE TITLE
Ruin set chest have wrong appearance on magus

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#7316]
This is how it looked on live (the only choise for those, who don't like big collars):
![collar](https://cloud.githubusercontent.com/assets/18102127/17840980/7c6823a6-6824-11e6-8319-bc9512d50427.png)

**Comment by Luth-RoR** [comment]
Needs confirmation from DB dev, if it can/will be changed or is intended.

**Comment by Torquemadra** [comment]
its as it will be now
