### ISSUE TITLE
Suderholm - PQ Chaos Chapter 2

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7321]
- [x] Too many duplicate Guards on Stage 1.All of the duplicates fall out of the PQ.
- [x] Also many Guards(Non duplicates) fall out of the PQ.
- [x] Aborrah is there from First Stage.On Stage 3 killing him doesnt finish the PQ.

**Comment by wargrimnir** [comment]
Converted remaining guards to the PQ. Corrected Aborrah.
