### ISSUE TITLE
Destruction of the Weak - PQ Chaos Chapter 2 

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7322]
- Tonas Jorgen in Stage 1 doesnt respawn.

**Comment by Tuffskin** [comment]
He actually is there... he's laying on the ground dead just outside the wagon/box ring!  Seems like he was killed and it didn't credit the kill so the PQ never continued on and since there's no timer on that stage it's just sitting there waiting.  This PQ was working because I completed it on a couple different characters but now it's stuck.

**Comment by Soulwhisper** [comment]
Need to check it again.Awesome call! Thanks man.

**Comment by Tuffskin** [comment]
I forgot to mention he was like halfway in the ground... I'll see if I can find him again later after I get off work.

**Comment by Soulwhisper** [comment]
Post a screenshot if you see him.

**Comment by Luth-RoR** [comment]
There have been NPCs in the past who had a wrong flag in the DB; they lie on the ground but also glimmer like they could be looted. Afaik these should all be fixed, but maybe this is one remnant.

**Comment by Soulwhisper** [comment]
Yeah i remember this PQ working last year!...

**Comment by Soulwhisper** [comment]
- @Luth-RoR Ok i checked the NPC he has been pulled near our(Destruction) friendly NPCs and killed by them probably.He is laying down on the ground dead.As i said above he should respawn.

**Comment by Luth-RoR** [comment]
Ok, thanks.

**Comment by Luth-RoR** [comment]
On second thought: Maybe he should just not be hostile to the friendly enemies, so that he doesn't get killed again.

**Comment by Soulwhisper** [comment]
You mean he should be hostile right?He is Empire.

**Comment by Luth-RoR** [comment]
I mean he should be hostile to players, but maybe not to NPCs, so that players don't have to wait for his respawn every time the NPCs killed him again.

**Comment by Soulwhisper** [comment]
Tested again.I pulled him to our friendly NPCs letting them kill him and he doesnt respawn.

**Comment by Luth-RoR** [comment]
K thanks.

**Comment by avenflar** [comment]
Would it be possible to also have a timer on the last phase, so that even if he gets killed the PQ wil reset after like, 8min?

**Comment by Soulwhisper** [comment]
@avenflar You mean stage 1.Stage 3 iirc has a timer.Stage 1 cant have a timer because if its nature.

**Comment by avenflar** [comment]
@Soulwhisper Isn't 'killing Tonas Jorgen' the last stage of the PQ?

**Comment by Soulwhisper** [comment]
Nope

**Comment by Soulwhisper** [comment]
Ok so now i find him dead inside of the PQ and not up on the hill.And still he doesnt want to respawn.
![shamanakos_000](https://cloud.githubusercontent.com/assets/16864486/19185694/79559096-8c8b-11e6-899b-1bf2849aedf2.jpg)

**Comment by wargrimnir** [comment]
Removed NoRespawn flag from Jorgen.
