### ISSUE TITLE
Holmsteinn Revisited - PQ Chaos Chapter 2

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7323]
There is an invisible chest in the PQ area and needs to be removed.
![shamanakos_000](https://cloud.githubusercontent.com/assets/16864486/17855120/87acada8-687f-11e6-9514-2b0d47c98250.jpg)

**Comment by Yellowpillow** [comment]
thos chests in every PQ right now

**Comment by Soulwhisper** [comment]
1 report per ticket they said.If its easier for Developers to check them from your list then close this.

**Comment by wargrimnir** [comment]
This should be made into a separate ticket regarding visible chests at all PQ's. While testing I found the GO chest is not required for the chest spawn to occur at the end of a stage. It may be able to be removed in the future.

**Comment by Luth-RoR** [comment]
Ok, closing then.
