### ISSUE TITLE
Chaos Chapter 4 and 3 Influence Bars

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7326]
- Standing in Chaos Chapter 4 shows Chaos Chapter 3 Influence bar.Probaply broken Chapter IDs.Needs redesign.
  **Tested more...**
- [ ] Going in Chaos Chapter 4 area of PQs shows Chapter 3 Influence bar.
- [ ] Going in Chaos Chapter 3 area of PQs shows Chapter 4 Influence bar.

**Comment by wargrimnir** [comment]
Fixed in next.
