### ISSUE TITLE
Fields of Woe - Public Quest Chaos Chapter 4 

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7328]
- [x] Stage 1 doesnt work.

**Comment by Yellowpillow** [comment]
#5518

**Comment by Soulwhisper** [comment]
1 report per ticket they said.If its easier for Developers to check them from your list then close this.

**Comment by Luth-RoR** [comment]
I think he just links the single reports to his cumulative report to see when they have been closed.

**Comment by Soulwhisper** [comment]
We can work on this together then.I will keep reporting each PQ individually.

**Comment by wargrimnir** [comment]
Fixed in next.

**Comment by WAR2014** [comment]
The stage 1 of Fields of Woe (Normal) missed 1 Wagon at site. All 10 wagons been killed should complete but not.
