### ISSUE TITLE
Squig Armor not working correctly

### ISSUE THREAD

**Issue by Symex** [WarEmu/WarBugs#733]
I ididnt play Squig Herder on retail so i cant really tell which Part on this issue is the mistake. 

anyways, when i get into squig armor i can still use every abillity (What Blocka?, Plink etc.). In the upper screen region it says "you cannot you this abilitiy while in squig armor" or something along those lines, but they will fire anyways.

**Comment by ozarmidrashim** [comment]
Fixed in next.
