### ISSUE TITLE
I can not get the title The Gory.

### ISSUE THREAD

**Issue by Rahgul** [WarEmu/WarBugs#7332]
I can not get the title. Talabecland 38,5k 38k explore the graveyard. The graveyard explore, but I did not get the title.

Tome of Knowledge - Dare to tread with the undead.

**Comment by Luth-RoR** [comment]
I don't know if this is implemented atm, but if it is, i could imagine that there is some guy or object lieing on the ground, which you have to click for the unlock. Afaik area discovery unlocks don't work like they did originally yet.
Needs confirmation from DB-dev.

**Comment by Rahgul** [comment]
The fact of the matter that there is no object that I could press to unlock.

**Comment by Luth-RoR** [comment]
Yes, it could also be not implemented yet.

**Comment by Ryanfawkez** [comment]
Proximity unlock, cannot fix yet.
http://warhammeronline.wikia.com/wiki/Dare_to_Tread_With_the_Undead

**Comment by Sapphiratelaemara** [comment]
![image](https://cloud.githubusercontent.com/assets/23622177/20628883/f924bcac-b328-11e6-930c-75ca4edb8498.png)
