### ISSUE TITLE
flying for Brothers Keeper quest to Altdorf from Felde Castle

### ISSUE THREAD

**Issue by BillyMays1** [WarEmu/WarBugs#7333]
In the quest it requires you to fly from Felde Castle to Altdorf. Once I arrived to Altdorf every Character and NPC was invisible besides my own and some of thier gear for example; the mounted expedition quartermaster next to the flight master at Altdorf only his gyropack was visible, when I mounted only my saddle on my horse was visible, some gear was visible on the NPC's by the arch that lead out to the market like their weapons. Once I attempted to leave the flight masters room through the arch to the market my game froze momentarily and after about 30 seconds to resumed and it problem fixed itself. not sure if it permanently fixed but I thought it was worth bringing up.

BillyMays, level 13 Bright Wizard

**Comment by Luth-RoR** [comment]
Hi, 
seems like you encountered a type of disconnect/reconnect or network lag. 
Virtually all "stuff that moves" you see ingame is generated on the client by an order from the server, which means that in case of a bad connection NPCs or gameobjects could disappear.
But that's normal, no bug.
