### ISSUE TITLE
Silkens - Public Quest Chaos Chapter 6

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7334]
- [x] Stage 1 doesnt work.
- [x] ~~This chest needs to be removed.~~
  ![shamanakos_001](https://cloud.githubusercontent.com/assets/16864486/17871177/21808d26-68c3-11e6-98b7-a49ae8d31063.jpg)

**Comment by Yellowpillow** [comment]
#5518

**Comment by sioding** [comment]
Fixed with Patch from 25.11.2017
