### ISSUE TITLE
Bells of War - Public Quest Chaos Chapter 5

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7335]
- [ ] Stage 1 doesnt work.
- [x] ~~This chest needs to be removed.~~
  ![shamanakos_000](https://cloud.githubusercontent.com/assets/16864486/17871327/b251cca2-68c3-11e6-9128-38dbc6c55141.jpg)

**Comment by Yellowpillow** [comment]
#5518
