### ISSUE TITLE
Krul'Gor Herd - Public Quest Chaos Chapter 5 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7336]
- [x] Stage 1 doesnt work.
- [x] ~~This chest needs to be removed.~~
  ![shamanakos_000](https://cloud.githubusercontent.com/assets/16864486/17871473/5e122942-68c4-11e6-8cab-087b215fb3e3.jpg)

**Comment by Yellowpillow** [comment]
#5518

**Comment by Razielhell** [comment]
- [ ] Krul Warriors on Stage 2 are double spawns.

**Comment by grunbag** [comment]
Fixed in next patch
