### ISSUE TITLE
Spirits of the Shadow - Public Quest Chaos Chapter 5 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7337]
- ~~Stage 1 doesnt work.~~

**Comment by Yellowpillow** [comment]
#5518

**Comment by Razielhell** [comment]
FIXED.
- [ ] Only problem is that chest spawns in Stage 1(Shouldnt).
![warhammer online age of reckoning 01 28 2017 - 18 43 19 170](https://cloud.githubusercontent.com/assets/16864486/22398127/e151c10e-e589-11e6-9245-7d48e73cc21c.png)

**Comment by grunbag** [comment]
Fixed in next patch
