### ISSUE TITLE
Reaper's Circle - Public Quest Chaos Chapter 6 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7338]
- ~~Stage 1 doesnt work.~~
- This chest needs to be removed.
  ![shamanakos_001](https://cloud.githubusercontent.com/assets/16864486/17871608/fbdedbac-68c4-11e6-8299-216bbafdcd08.jpg)

**Comment by Yellowpillow** [comment]
#5518

**Comment by Razielhell** [comment]
- [ ] Many Wolfs in Stage 1 fall out of the PQ area. They are located West-Northwest from center of the PQ.
**_## PQ Tracker also disappears there._**

**Comment by Lheana** [comment]
I have fixed it with patch of 13th October, all 'Rankhide Wolf' within the PQ area now count for first stage.
