### ISSUE TITLE
Game crash in Altdorf after going through the portal in the market and back

### ISSUE THREAD

**Issue by BillyMays1** [WarEmu/WarBugs#7342]
Game crashed in Altdorf after reentering from the portal in the market. Not sure exactly what did it because it happened about 30 seconds after I reentered Altdorf. 

BillyMays, level 13 Bright Wizard

**Comment by Luth-RoR** [comment]
Known issue: https://github.com/WarEmu/WarBugs/issues/7356
Could have many reasons, but the most common is malfunctioning communication between the server and your client. Devs have to track down the roots of this, but that may take time.
