### ISSUE TITLE
Griffon Outpost - Public Quest Chaos Chapter 7 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7343]
- ~~Stage 1 doesnt work.~~
- ~~Too many heroes inside the PQ area.I think its not intended.Soo mob re-arrangement for Stage 1 Handgunners(There are only a few at 1 of 3 mini-camps).~~

**Comment by Yellowpillow** [comment]
#5518

**Comment by Razielhell** [comment]
- Stage 2 needs to Capture Southwest Camp. I think this is bugged. Killed all NPCs but nothing happened.
- **_There are some flags but are not clickable.Run all over the area._**

**Comment by Lheana** [comment]
Has been fixed
