### ISSUE TITLE
Plaguewood Thicket - Public Quest Chaos Chapter 8 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7345]
- ~~Stage 1 doesnt work.~~

**Comment by Yellowpillow** [comment]
#5518

**Comment by Razielhell** [comment]
- [ ] Stage 1 doesnt count Trolls that are in red circled area.(Picture 1) 
**_There is only 1 Troll north of the PQ that counts._**
- [ ] Strange invisible chest location north of the PQ.(Pictures 2 & 3)
![warhammer online age of reckoning 02 21 2017 - 21 11 07 39](https://cloud.githubusercontent.com/assets/16864486/23181244/ede88596-f87c-11e6-8930-d1a234b93458.png)
![warhammer online age of reckoning 02 21 2017 - 21 09 45 37](https://cloud.githubusercontent.com/assets/16864486/23181246/f0b12792-f87c-11e6-81a7-928d0030469a.png)
![warhammer online age of reckoning 02 21 2017 - 21 09 46 38](https://cloud.githubusercontent.com/assets/16864486/23181249/f13bb5e2-f87c-11e6-9ed9-77f24c85051b.png)
