### ISSUE TITLE
Plague Altar - Public Quest Chaos Chapter 9 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7346]
- ~~Stage 1 doesnt work.~~

**Comment by Yellowpillow** [comment]
#5518

**Comment by Razielhell** [comment]
- [ ] Stage 2 doesnt count Infected Zealous

**Comment by Tyramissoux** [comment]
It counts Bloated Zealots.

**Comment by Razielhell** [comment]
Indeed.

**Comment by Castrael** [comment]
Furthermore, the Bloated Plaguebearers that spawn in stage 2 does not correctly register Plaguebearer kills in your bestiary and the boss, Bulvous the Plaguechyld does not correctly register as a Great Unclean One kill in your bestiary.

**Comment by Lheana** [comment]
Has been fixed
