### ISSUE TITLE
The Blightstone Trolls - Public Quest Chaos Chapter 9 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7347]
- ~~Stage 1 Doesnt work.~~
- ~~This chest needs to be removed.~~
  ![shamanakos_000](https://cloud.githubusercontent.com/assets/16864486/17872566/553790c8-68c9-11e6-8e62-6f28c3ec29c0.jpg)

**Comment by Yellowpillow** [comment]
#5518

**Comment by Razielhell** [comment]
- [ ] I guess objective should be 0/1 ? @Luth-RoR 
![warhammer online age of reckoning 02 18 2017 - 21 03 38 10](https://cloud.githubusercontent.com/assets/16864486/23096054/dcc99a4a-f61d-11e6-9117-37440d34d513.png)

**Comment by Luth-RoR** [comment]
Yes, i think so.
