### ISSUE TITLE
Tearing the Portal - Public Quest Chaos Chapter 9 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7348]
- ~~Stage 1 doesnt work.~~
- This chest needs to be removed.
  ![shamanakos_000](https://cloud.githubusercontent.com/assets/16864486/17872662/bea8fa10-68c9-11e6-9032-883440d08368.jpg)

**Comment by Yellowpillow** [comment]
#5518

**Comment by Razielhell** [comment]
- [ ] Stage 2 doesnt count Infected Zealous
