### ISSUE TITLE
Bog Hunters - Public Quest Chaos Chapter 7 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7349]
- [x] Stage 1 doesnt work.
- [x] ~~This chest needs to be removed.~~
  ![shamanakos_000](https://cloud.githubusercontent.com/assets/16864486/17872787/7b52a60c-68ca-11e6-8971-4475b3e9dba4.jpg)

**Comment by Yellowpillow** [comment]
#5518

**Comment by poutpoutt** [comment]
The first objective of this public quest is "obscure meeting stone" but it should be "Bog trap"

The "obscure meeting stone" is a single interactive object for the quest "Temptress"

**Comment by Razielhell** [comment]
- [ ] Otto von Buergh doesnt spawn in Stage 3.

**Comment by Lheana** [comment]
Has been fixed last patch.
