### ISSUE TITLE
Guts Out - Public Quest Destruction Chaos Chapter 13 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7350]
- [x] PQ UI/Tracker needs to be enlarged.There are many mobs by the hills but UI dissapears there.
- [x] Chest needs replacement or mob rearrangement.It spawns between 6-7 mobs and you cant reach it.
- [x] ~~Ghost chest needs to be removed.~~

**Comment by Yellowpillow** [comment]
#5518

**Comment by Razielhell** [comment]
#9819 

> Morngrim commented 3 days ago
High Pass CH 13 PQ Guts Out Icemaw Sabretusk doesnt't count for the 1 stage

**Comment by Lheana** [comment]
Seems like it was fixed.
