### ISSUE TITLE
Keep of Asavar Kul - Public Quest Destruction Chaos Chapter 13

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7351]
- [x] Some MOBS on Stage 1 fall out of the PQ.
- [x] ~~Stage 2 doesnt work.~~

These and many others that i cant show you exactly their position.
![shamanakos_001](https://cloud.githubusercontent.com/assets/16864486/17873611/23c03be8-68cf-11e6-9ffb-a25c54b63892.jpg)
![shamanakos_000](https://cloud.githubusercontent.com/assets/16864486/17873492/72294924-68ce-11e6-92f5-8d3673a35f9e.jpg)

**Comment by Yellowpillow** [comment]
#5518
