### ISSUE TITLE
Tempest Horn - Public Quest Destruction Chaos Chapter 13 

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7352]
- Stage 1 doesnt work.
- This chest needs to be removed.
![shamanakos_000](https://cloud.githubusercontent.com/assets/16864486/17874007/90bfcc20-68d1-11e6-93a2-fd3fb43bd3a7.jpg)

**Comment by Yellowpillow** [comment]
#5518

**Comment by Razielhell** [comment]
Fixed.
