### ISSUE TITLE
[Quest] Gotta Nosh! t3 dye quest (Destro)

### ISSUE THREAD

**Issue by magter3001** [WarEmu/WarBugs#7357]
This quest is the t3 dye quest for Destruction that is suppose to be repeatable like the Order equivalent, however I was able to do it only once as it was no longer available.

Gobsnik gives the quest in Chapter 11 Greenskin.

**Comment by Luth-RoR** [comment]
Wasn't this a quest from the last event?

**Comment by magter3001** [comment]
No, this quest isn't event based as it was on live as well.
