### ISSUE TITLE
"no choppin me" trait

### ISSUE THREAD

**Issue by powazappa** [WarEmu/WarBugs#7359]
Hi!

The no choppin me trait on the black ork is bugged at the moment. What it used to do was stack the single target and the group buff it provides on one target, meaning your defensive target got about 240 total weaponskill from the buff while the rest of the group only got the 120 ws. On live the buff only applies 120 stats to the defensive target

Tried searching for threads relating to this bug but couldnt find any. Sorry if its already known!

**Comment by ozarmidrashim** [comment]
Intentional fix.
