### ISSUE TITLE
sometimes no spell animation for Bunch O' Waaagh

### ISSUE THREAD

**Issue by Symex** [WarEmu/WarBugs#736]
When i use this Spell it often works great with the animation when im in a PvE environment. in scenarios and oRvR i find it more often that i have the green animation of the spell missing. can be a bit annoying in scs when you dont see it.

screenshot of spell not working:
![image](https://cloud.githubusercontent.com/assets/9036566/7868005/a3c85e98-0579-11e5-983e-ed0fa5e4a232.png)

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
