### ISSUE TITLE
Army of Faith - Public Quest Destruction Chaos Chapter 11

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7362]
- [x] Needs more peasants inside the PQ area...they are too far away from the actual PQ.
- [x] Cant open the door of the Temple.
- [x] Stage 3 doesnt spawn Arch Lector Ansel or maybe he spawns inside the Temple(but door is closed).

**Actually we managed to see that there are mobs inside the temple so yeah...Door needs to be fixed.**

**Comment by Yellowpillow** [comment]
#5518

**Comment by Luth-RoR** [comment]
>Stage 1 asks you to kill the peasants which are placed just outside of the PQ area to the east, killing them allows you to complete the stage, 100 influence received per kill but no extra influence for completing the stage, transit to stage 2.

>Stage 2 asks you to kill the tower guard which are stood outside the entrance of the building that is situated direct in the centre of the PQ area, kill 4 tower guards, 2 of which only spawn at a single time, wait for respawn, kill the next 2 then stage complete, 100 influence received per kill and extra 250 influence for completion of stage 2, transits to stage 3.

>Stage 3 kill Arch forgot the name unable to complete the stage because he is no where to be seen, i suspect he is located inside the building which appears to be a church, the doors however are closed and are unable to be opened, so he must be located either inside behind the inaccessible door, i have also searched the whole area surrounding the church but could not find him there either to complete the quest, result, timer runs out, message PQ finished, no influence or rewards.

From https://github.com/WarEmu/WarBugs/issues/8985

**Comment by Razielhell** [comment]
Natherul
-Fixed the door to the monastery in Talabecland

**Comment by Razielhell** [comment]
- [ ] In last Stage(3) this mob should be champion i guess...otherwise its extreme easy.
![army of faith](https://cloud.githubusercontent.com/assets/16864486/22858198/a9c19f76-f0be-11e6-9041-577f43544c3d.png)
