### ISSUE TITLE
The Eternal Citadal

### ISSUE THREAD

**Issue by OgGori** [WarEmu/WarBugs#7364]
You are able to knock and be knocked off the map and not die leaving you stuck out of play.

**Comment by Luth-RoR** [comment]
Does this always happen due to free fall into the middle abyss or did you touch a wall during the flight?

**Comment by OgGori** [comment]
Ilmy aoology, it happened during the scenario. I was knocked into the
middle area and had to wait out the rest of the scenario.

**Comment by Luth-RoR** [comment]
I see. 
I just saw that someone opened already a report about that issue five hours earlier: https://github.com/WarEmu/WarBugs/issues/7356

**Comment by Luth-RoR** [comment]
I just saw: https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16406#p180240
