### ISSUE TITLE
Mudflats - Public Quest Destruction Chaos Chapter 10

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7366]
- ~~Nothing works here.~~

**Comment by Yellowpillow** [comment]
#5518

**Comment by Razielhell** [comment]
- [ ] Stage 2 needs mob-rearrangement for sure. Way too hard the way it is. Mobs are linked and cant kill the Champions.

**Comment by Lheana** [comment]
Reduced the number of NPCs during second stage

**Comment by sioding** [comment]
Fixed with patch from 13.10.2017
