### ISSUE TITLE
Bitterspring - Public Quest Destruction Chaos Chapter 12 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7369]
- [x] On Stage 2 needs to fill whole area with more Spymasters because right now you have to wait 3 minutes for them to respawn.I think they are 5 or 6 in front of the PQ.Back area is empty.
- [x] ~~This chest needs to be removed.~~

  ![shamanakos_001](https://cloud.githubusercontent.com/assets/16864486/17889009/af3bca22-6936-11e6-91c3-ba9101177e07.jpg)

**Comment by Lheana** [comment]
Has been fixed.
