### ISSUE TITLE
Kolaz Umgal Scouts - Public Quest Destruction Greenskin Chapter 14 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7371]
- ~~Stage 1 doesnt work.~~

**Comment by Yellowpillow** [comment]
#5547

**Comment by Razielhell** [comment]
- [ ] Stage 2 doesnt work. Tents unclickable.
![warhammer online age of reckoning 02 12 2017 - 19 17 48 17](https://cloud.githubusercontent.com/assets/16864486/22864366/cf59acca-f158-11e6-92c2-f4ef1cd85884.png)
