### ISSUE TITLE
Blighted Herd - Public Quest Destruction Greenskin Chapter 14

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7372]
- ~~Stage 1 doesnt work.~~

**Comment by Yellowpillow** [comment]
#5547

**Comment by Razielhell** [comment]
- [ ] On Stage 2 Herdstone is unclickable.**_(If this is it. Searched the area and found nothing.)_**
![warhammer online age of reckoning 02 21 2017 - 15 46 30 30](https://cloud.githubusercontent.com/assets/16864486/23168350/8620ea2e-f850-11e6-978c-01141728402d.png)
