### ISSUE TITLE
Blight Favored Cult - Public Quest Destruction Greenskin Chapter 14

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7373]
- ~~Stage 1 doesnt work.~~

**Comment by Yellowpillow** [comment]
#5547

**Comment by Luth-RoR** [comment]
>greenskin ch 14 PQ that was fixed last night. the cultists kills update the quest now but the blighted nurglings are friendly and unattackable.

from https://github.com/WarEmu/WarBugs/issues/9123

**Comment by Razielhell** [comment]
- [ ] Confirming that you cant complete Stage 1 with Blighted Nurglings beeing friendly and unattackable.
![warhammer online age of reckoning 02 12 2017 - 19 20 20 19](https://cloud.githubusercontent.com/assets/16864486/22864354/984d8120-f158-11e6-9687-a33d14f7cb6b.png)

**Comment by grunbag** [comment]
Fixed in next patch

**Comment by Razielhell** [comment]
Blighted Nurglings dont count when you kill them.
