### ISSUE TITLE
Altstadt - Public Quest Destruction Greenskin Chapter 13

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7374]
- ~~Stage 1 doesnt work.~~
- ~~PQ Area touches RvR area...needs redesign.~~ **_This is fixed_**
(Updated 21/2/2017)

**Comment by Yellowpillow** [comment]
#5547

**Comment by Razielhell** [comment]
- [ ] Piles of dirt are unclickable on Stage 2.
