### ISSUE TITLE
Moonfang Remnant - Public Quest Destruction Greenskin Chapter 12

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7376]
- ~~PQ UI/Tracker doesnt show up(Show i guess PQ area ID is missing)~~
- ~~Nothing works overall.~~

**Comment by Yellowpillow** [comment]
#5547

**Comment by Razielhell** [comment]
- [ ] Stage 1 doesnt count kills

**Comment by sioding** [comment]
Fixed with Patch from 25.11.2017
