### ISSUE TITLE
Kolaz Umgal - Public Quest Destruction Greenskin Chapter 12 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7377]
- ~~Stage 1 doesnt work.~~

**Comment by Yellowpillow** [comment]
#5547

**Comment by Razielhell** [comment]
- [ ] On stage 2 you cant interact with Valves and these 2 fire animations standing on nothing.
![warhammer online age of reckoning 02 21 2017 - 20 58 24 35](https://cloud.githubusercontent.com/assets/16864486/23180942/cae54a80-f87b-11e6-999e-905a1c27ca49.png)

**Comment by grunbag** [comment]
Fixed in next patch
