### ISSUE TITLE
Sigmarite Temple - Public Quest Destruction Greenskin Chapter 13 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7378]
- ~~Stage 1 doesnt work.~~
- ~~Door of the building is closed.~~

**Comment by Yellowpillow** [comment]
#5547

**Comment by Razielhell** [comment]
- [ ] On Stage 2 it only spawns 2 of Redeemers. One in front of the Temple and 1 behind.
_**Scanned carefully the whole area+the building inside and upstairs.**_
![warhammer online age of reckoning 02 21 2017 - 16 03 13 32](https://cloud.githubusercontent.com/assets/16864486/23168180/e75e9df0-f84f-11e6-8fce-9a36502eebfd.png)

**Comment by grunbag** [comment]
Fixed in next patch
