### ISSUE TITLE
Thardrik Smashin' - Public Quest Destruction Greenskin Chapter 10 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7382]
- ~~Stage 1 doesnt work.~~
- This chest needs to be removed.
  ![shamanakos_000](https://cloud.githubusercontent.com/assets/16864486/17891398/36e8884a-6944-11e6-990b-2e5ea4579f01.jpg)

**Comment by Yellowpillow** [comment]
#5547

**Comment by Razielhell** [comment]
- [ ] On Stage 3 only 1 Gruna spawns(Hero) and 1 Champion next to her. Objective says 0/3. 
**_I guess it should be 0/1 for the Hero and 0/1 for the Champion._**
![warhammer online age of reckoning 02 21 2017 - 20 40 27 33](https://cloud.githubusercontent.com/assets/16864486/23181066/2b1335fc-f87c-11e6-9539-00778ab376fe.png)
![warhammer online age of reckoning 02 21 2017 - 20 40 31 34](https://cloud.githubusercontent.com/assets/16864486/23181067/2b4743a6-f87c-11e6-89e8-0a560b89f721.png)

**Comment by grunbag** [comment]
Fixed in next patch
