### ISSUE TITLE
Mutant Exiles Public Quest Destruction Greenskin Chapter 11

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7384]
- Nothing works here.

**Comment by Yellowpillow** [comment]
#5547

**Comment by g4USA** [comment]
PQ is missing its progress UI:
![blahblah 1](https://user-images.githubusercontent.com/29905200/39881702-34d4b046-5471-11e8-8762-8eeeba919346.jpg)
![blahblah 2](https://user-images.githubusercontent.com/29905200/39881705-36e22724-5471-11e8-92a8-6a614654c608.jpg)
