### ISSUE TITLE
Guild Recall Scroll cooldown

### ISSUE THREAD

**Issue by georgehabadasher** [WarEmu/WarBugs#7387]
The guild recall scroll's cooldown was 5 minutes on live.  Here it's 30 minutes for whatever reason.  I didn't see it in the 'intended changes from live' thread so I'm assuming it's a DB bug.

**Comment by georgehabadasher** [comment]
I see it was assigned to "styrkarrr" does that mean it's being worked on or does it still need confirmation?  I've watched a lot of old youtube videos trying to find guild scrolls on CD, but haven't found any yet (which would suggest that the 5 minute cooldown is accurate).

**Comment by Luth-RoR** [comment]
There are some changes on RoR made with intention. I don't know if it's a bug or intended.

**Comment by georgehabadasher** [comment]
I didn't see it in the "Intentional Changes from Live" thread, although that might not be comprehensive.  Either way, can you confirm that I don't need to keep looking for confirmation?

**Comment by Luth-RoR** [comment]
It's more a confirmation request for devs, if it works as intended or not atm.

**Comment by Kaelang** [comment]
No confirmation was provided - I'm going to close this report for now.
