### ISSUE TITLE
Watchtower of Aethwyn - Public Quest Destruction Dark Elf Chapter 12

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7388]
- ~~Nothing works here.~~

**Comment by Yellowpillow** [comment]
#5504

**Comment by Razielhell** [comment]
- [ ] Influence Bar shows Chapter 11 instead of 12.

**Comment by saupreusse** [comment]
i found the issue but its unfixable. talked with nath and he said that the pq code is too messy at the moment.
