### ISSUE TITLE
The Pool of Elthrai - Public Quest Destruction Dark Elf Chapter 11

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7389]
- ~~Stage 1 doesnt work.~~
- This chest needs to be removed.
  ![shamanakos_001](https://cloud.githubusercontent.com/assets/16864486/17895701/9d068b06-6956-11e6-95ac-cb61b912d814.jpg)

**Comment by Yellowpillow** [comment]
#5504

**Comment by Razielhell** [comment]
- [ ] Stage 1 Spawns all Daughters of Isha.
- [ ] On Stage 2 they despawn and only 1 spawns.
**_In general needs to be looked again cause in Stage 1 there is a mess in mob position._**
