### ISSUE TITLE
Login Fail. Wrong Character

### ISSUE THREAD

**Issue by Symex** [WarEmu/WarBugs#739]
I cant really tell when this occurs but sometimes when i log a character out and log in on a new one, i still get the old one with double anymations (ex: i logout with chaos magus and log in with black ork, it will have both animations, so you will see the chaos feet on a ork with abillities of the magus) and the hotbars get all messed up. normally works after doing the logout process again.

**Comment by Evildoor** [comment]
I do believe this was fixed, closing. Comment here if the problem still persists.
