### ISSUE TITLE
Sea Guard Beachhead - Public Quest Destruction Dark Elf Chapter 12 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7391]
- ~~Stage 1 doesnt work.~~
- This chest needs to be removed.
  ![shamanakos_000](https://cloud.githubusercontent.com/assets/16864486/17895831/0a71efbe-6957-11e6-8e87-9f42b4119155.jpg)

**Comment by Yellowpillow** [comment]
#5504

**Comment by Razielhell** [comment]
- [ ] On Stage 2 we cant interact with Oil barrels

**Comment by Lheana** [comment]
Has been fixed.
