### ISSUE TITLE
Dartian Forest - Public Quest Destruction Dark Elf Chapter 11 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7394]
- ~~Stage 1 doesnt work.~~
- This chest needs to be removed.
  ![shamanakos_000](https://cloud.githubusercontent.com/assets/16864486/17898570/e1efea46-6960-11e6-8b75-f8af730781fc.jpg)

**Comment by Yellowpillow** [comment]
#5504

**Comment by Razielhell** [comment]
- [ ] 2 Heroes.
![warhammer online age of reckoning 02 20 2017 - 12 49 17 15](https://cloud.githubusercontent.com/assets/16864486/23121960/10e3ddf6-f76b-11e6-8646-cf39c77201fc.png)
![warhammer online age of reckoning 02 20 2017 - 12 49 19 16](https://cloud.githubusercontent.com/assets/16864486/23121961/1110b722-f76b-11e6-890e-e72f922ab1b0.png)

**Comment by Lheana** [comment]
NPC 'Sorceress Selinja' is now a Champion and no longer a Hero.

**Comment by sioding** [comment]
Fixed with patch from 4.11.2017
