### ISSUE TITLE
Wavesinger - Public Quest Destruction Dark Elf Chapter 10

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7396]
- [ ] On Stage 3 PQ area ID stops behind the red line.Needs to be increased beyond the ship.I went to pull the mobs from the ship and the guy that was helping me fell outside the area just a few feet beyond the line so he lost the reward because of that.
  ![shamanakos_000](https://cloud.githubusercontent.com/assets/16864486/17899758/0fe7cc26-6965-11e6-976b-2115d38861f5.jpg)
- [x] ~~This chest needs to be removed.~~
  ![shamanakos_000](https://cloud.githubusercontent.com/assets/16864486/17896069/e5daef60-6957-11e6-8993-41131f24e5f0.jpg)

**Comment by Lheana** [comment]
Has been fixed.
