### ISSUE TITLE
The White Tower of Hoeth - Public Quest Destruction Dark Elf Chapter 14 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7397]
- ~~Stage 1 doesnt work.Couldnt find Starwatchers.Searched first and second floor.~~
~~**Tower doors should be open? Dont know. Maybe they are upstairs or inside the tower.**~~

**Comment by Yellowpillow** [comment]
#5504

**Comment by Razielhell** [comment]
- [ ] These 2 heroes spawn on Stage 2.
![warhammer online age of reckoning 02 20 2017 - 20 14 32 06](https://cloud.githubusercontent.com/assets/16864486/23137447/bbc96210-f7aa-11e6-9b05-2bbddad8f0a3.png)
![warhammer online age of reckoning 02 20 2017 - 20 14 30 05](https://cloud.githubusercontent.com/assets/16864486/23137448/bbccbea6-f7aa-11e6-8e3b-f147e8d454c2.png)
- [ ] Stage IV Belannaer of Hoeth doesnt spawn.

**Comment by grunbag** [comment]
i set the heros to neutral (they are not PQ npc) , and the last stage will be fixed in next patch
