### ISSUE TITLE
Recompense - Public Quest Destruction Dark Elf Chapter 13 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7398]
- [x] This one is stuck to Stage 3.On Stage 3 there is no timer so it cant reset.Needs 0/5 Deathcrafters but there are no Deathcrafters anywhere in the area.
- [x] ~~This chest needs to be removed.~~

  ![shamanakos_002](https://cloud.githubusercontent.com/assets/16864486/17911242/30251eb4-6995-11e6-9a29-0f8e0f6e9c7c.jpg)

**Comment by Yellowpillow** [comment]
#5504

**Comment by grunbag** [comment]
Fixed
