### ISSUE TITLE
Whitemoon Manor - Public Quest Destruction Dark Elf Chapter 13 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7399]
- ~~Stage 1 doesnt work.~~

**Comment by Yellowpillow** [comment]
#5504

**Comment by Razielhell** [comment]
- [ ] 3 mobs you need to kill in Stage 3 are surrounded by 4-5 Champions which makes it mission impossible. These mobs(Champions) are called Adepts iirc.
![warhammer online age of reckoning 02 20 2017 - 20 57 35 15](https://cloud.githubusercontent.com/assets/16864486/23138596/fd75867a-f7b0-11e6-9dcd-cf5f6722b9eb.png)
![warhammer online age of reckoning 02 20 2017 - 20 58 34 17](https://cloud.githubusercontent.com/assets/16864486/23138597/fd7cc868-f7b0-11e6-83f0-0f5ccd99067f.png)

**Comment by Lheana** [comment]
The different Adepts are no longer Champions but normal NPCs. Alanir Whitemoon, Larotan Stormbreaker and Yrisea Lifecaller are now Champions. Removed the double spawn of Yrisea Lifecaller, and Alanir Whitemoon is now neutral so that he does not attack during the previous stages.

**Comment by sioding** [comment]
Fixed with patch from 4.11.2017
