### ISSUE TITLE
Doesn't animated armor debuff and snare for some classes.

### ISSUE THREAD

**Issue by murmelon** [WarEmu/WarBugs#740]
Doesn't animated snare effect for BO/BG/KotBS/IB/SM.
Doesn't animated armor debuff effect for BO/BG/IB.
It was like here
![bo](https://cloud.githubusercontent.com/assets/12655727/7882460/93d7ab2c-0616-11e5-8f75-1d984c6a4150.jpg)

**Comment by ozarmidrashim** [comment]
Fixed in next. Please keep a lookout for any other abilities which are not correctly displaying.
