### ISSUE TITLE
Oil damage reduced

### ISSUE THREAD

**Issue by Sporc** [WarEmu/WarBugs#7400]
I'm not certain about this, but since the last patch Oil seems to be doing minimal damage, like 600 ticking twice during a pour, which is a negligible amount. Any chance there could be a confirmation over wether this is true or not? Just seems odd that SH's are standing under oil and surviving it.

**Comment by Luth-RoR** [comment]
This is more like a forum question:
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=16406&p=180251&p180251#p180245
