### ISSUE TITLE
Renown in PQ

### ISSUE THREAD

**Issue by Kouba85** [WarEmu/WarBugs#7402]
Hallo i was playing PQ chapter 15 in Etaine and when i was guarding another player, i was rewarded with renown points. 
![perunn_000](https://cloud.githubusercontent.com/assets/15944509/17906460/bab86ce8-6977-11e6-947a-0c82a99459b1.jpg)
![perunn_001](https://cloud.githubusercontent.com/assets/15944509/17906465/bf19b3e6-6977-11e6-8f06-46eea07e6022.jpg)
![perunn_002](https://cloud.githubusercontent.com/assets/15944509/17906470/c2625b3e-6977-11e6-9855-aca3a3f81d05.jpg)
![perunn_003](https://cloud.githubusercontent.com/assets/15944509/17906473/c62839c8-6977-11e6-815c-6871040314b5.jpg)
![perunn_004](https://cloud.githubusercontent.com/assets/15944509/17906477/cb49a9aa-6977-11e6-8c73-3db12ad2371f.jpg)

**Comment by Luth-RoR** [comment]
That was high likely renown, shared by a healer in your group, from healing a damaged player who took part in PvP earlier.

**Comment by Kouba85** [comment]
If you think. So its ok?

**Comment by Luth-RoR** [comment]
Maybe a dev can say if it is bugged atm, but these tiny renown ticks are a good indicator for renown shared from healing iirc.

**Comment by Yellowpillow** [comment]
I have same in destro side in Eataine. Yes it is somehow came from healers.

**Comment by Tesq** [comment]
happened to me too, was on order side with my am leveling in dorf happened to heal a fleeing wh from lv 39 mobs in map corner, he was probably in party with the nearby SW, and i recived 15 renown and 121 exp or something like that

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Kaelang** [comment]
No confirmation was provided. I am now going to close this issue.
