### ISSUE TITLE
Trial By Fire - Public Quest Destruction Dark Elf Chapter 13 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7403]
- ~~Stage 1 doesnt work.~~

**Comment by Yellowpillow** [comment]
#5504

**Comment by Razielhell** [comment]
- [ ] On Stage 3 Thelafin Blazehand attack Flamescale.
![warhammer online age of reckoning 02 20 2017 - 20 48 16 13](https://cloud.githubusercontent.com/assets/16864486/23140844/7f8ce490-f7bc-11e6-8db8-edf740c96175.png)

**Comment by Lheana** [comment]
High Elves and Salamanders will no longer attack each other.

**Comment by sioding** [comment]
Fixed with patch from 4.11.2017
