### ISSUE TITLE
The Watchtower - Public Quest Destruction Dark Elf Chapter 2

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7406]
- [x] Stage 1 doesnt work.
- [x] ~~This chest needs to be removed.~~
  ![shamanakos_002](https://cloud.githubusercontent.com/assets/16864486/17911336/a6412610-6995-11e6-9900-ed0436fc9f9e.jpg)

**Comment by Yellowpillow** [comment]
#5504

**Comment by Soulwhisper** [comment]
- [ ] Swordmasters(Champions) in Stage 2 are unattackable.

**Comment by Razielhell** [comment]
Fixed next patch
