### ISSUE TITLE
Golden Tor - Public Quest Destruction Dark Elf Chapter 3

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7407]
- [x] Nothing works here.
- [x] ~~This chest needs to be removed.~~
  ![shamanakos_002](https://cloud.githubusercontent.com/assets/16864486/17911410/0f3c840c-6996-11e6-86c6-5bd70be66aee.jpg)

**Comment by Yellowpillow** [comment]
#5504

**Comment by Soulwhisper** [comment]
Ok this is working but PQ ID/Tracker needs to be expanded in circled areas.There are a couple of nests up and down but PQ Tracker disappears there.

**Comment by Lheana** [comment]
The PQ area seems correct now.
