### ISSUE TITLE
Nimosar - Public Quest Destruction Dark Elf Chapter 2

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7408]
- [x] ~~This chest needs to be removed.~~
  ![shamanakos_002](https://cloud.githubusercontent.com/assets/16864486/17911564/d2d403f4-6996-11e6-853f-1d9aedac7316.jpg)

**Comment by Soulwhisper** [comment]
- [ ] Double spawn.
![shamanakos_000](https://cloud.githubusercontent.com/assets/16864486/21467244/10656f10-c9ef-11e6-89b5-f353de81ad1e.jpg)

**Comment by Soulwhisper** [comment]
#8935

**Comment by grunbag** [comment]
Fixed in next patch
