### ISSUE TITLE
Mistwood Grove - Public Quest Destruction Dark Elf Chapter 2 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7409]
- [x] Stage 1 doesnt work.
- [x] ~~This chest needs to be removed.~~
  ![shamanakos_000](https://cloud.githubusercontent.com/assets/16864486/17911697/b6f74f3c-6997-11e6-9282-9daa7c2e1500.jpg)

**Comment by Yellowpillow** [comment]
#5504

**Comment by Soulwhisper** [comment]
- [ ] Stage 2 mobs are Untargetable.
**Same with #7406**

**Comment by Razielhell** [comment]
Patch Notes 28/1/2017 said that
- Converted missing mob from stage 2 Mistwood Grove
Issues commented on Dec 24, 2016 still persist.

**Comment by LadyCereus** [comment]
As of 3/12/17:  stage 3 boss still not targetable.  PQ can't be completed.

**Comment by Razielhell** [comment]
Yeah still same issues as i reported above. You can complete it though. Use AoE to pull Last Stage mob.

**Comment by Lheana** [comment]
Fixed next patch
