### ISSUE TITLE
Bug report No.1 multiple bugs list 

### ISSUE THREAD

**Issue by Avatrios** [WarEmu/WarBugs#741]
From Chaos Chosen starting point and onward.

1.In the tower in stating village location, on the left side inside the tower there is a dead body of a guard on the steps leading up. the dead guards body can still attack you and does not respawn.

the Bright wizard is not in the tower at all but outside at the base of it.

this same bug is repeated through out questing and public quest areas (yes i know public quests are not working yet)

2. Npc's are sometimes in weird locations eg. Salzenmund one of the fishermen are in the sea.
I have also seen some Npc's in the road where they are not suppose to be. 

3. there are boss Npc's that are murdered by their underlings eg. in the tomb of ravenborne  and Isolde in the huntsmen camp buy the wilds of war pub quest.

4. Npc's have the annoying habit when they engage you to ether run past you and attack from the sides or back, i thought maybe it was lag but even when standing still for a bit, and then engaging it still happens.

5. some quest rewards do not drop in the starting area.

6.some objects in the crypt  at starting location (skaven npc quest)and dark elf flight point area are floating.

7 sometimes and randomly I was dropped when using a flight point also when i sometimes load into the game i would land up in random locations.

Thats all for now i will make another report when i have played a bit more.

**Comment by Evildoor** [comment]
Please, make separate bugreport for each issue next time.

**Comment by Reggaewaldo** [comment]
Will verify what of the points above are still an issue, most should have been fixed since it was reported.

**Comment by Evildoor** [comment]
All these issues were either fixed or reported elsewhere. If not, they should be reported separately and with more details like "NPC named X located at Y is Z, while he should be W". Closing.
