### ISSUE TITLE
The Stone of Valetear - Public Quest Destruction Dark Elf Chapter 4

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7415]
- Stage 1 doesnt work.
- This chest needs to be removed.
  ![shamanakos_000](https://cloud.githubusercontent.com/assets/16864486/17912304/6d9dfefe-699b-11e6-824b-012c52c7b24d.jpg)

**Comment by Yellowpillow** [comment]
#5504

**Comment by LadyCereus** [comment]
As of right now, the stage 1 mobs are conning orange but level 41, so they can't be killed by appropriate level players in that area.

**Comment by Razielhell** [comment]
- [ ] Indeed.
![warhammer online age of reckoning 03 12 2017 - 11 57 24 50](https://cloud.githubusercontent.com/assets/16864486/23830857/d1d2039c-071c-11e7-9456-1de399d9b8e6.png)

**Comment by wargrimnir** [comment]
Fixed last patch #9428
