### ISSUE TITLE
All T2 Empire PQ loot bags not providing proper loot

### ISSUE THREAD

**Issue by BillyMays1** [WarEmu/WarBugs#7416]
![poopbutt_000](https://cloud.githubusercontent.com/assets/21181996/17915952/b888ae38-697c-11e6-9f8b-a6bc3a12e344.jpg)
I am sure that it is an isolated case (myself and a few others) but it is incredibly irritating finishing PQ's and knowing that regardless of the loot bag that I receive, it wont matter because the best thing I could receive is a journeyman talisman thing and a blue cultivating soil. This problem also pertains to T2 RVR Keep Siege Loot as well. I participated in the keep sieges today and every time it rolled, regardless of the bad I received, I never actually got an item. This has been a recurring issue for the past few days.

**Comment by Yellowpillow** [comment]
#5377

**Comment by BillyMays1** [comment]
thank you for referencing your own report but it is not the same issue. You are say what SHOULD be in the bags and referencing what WAS in them when the game was live. I am stating what is CURRENTLY WRONG i.e. I, and a few other people are not receiving any items with the loot bags in T2 empire specifically.

**Comment by BillyMays1** [comment]
im confused. so ALL of T2 Empire PQ's loot rewards have not been implemented yet?

**Comment by Torquemadra** [comment]
pq loot system is huge across the board and green/blue/purple bags in t1-t3 are not properly consolidated, we know about it it will get fixed at some point.

**Comment by gittoaster** [comment]
Does your team know about T2 Keep bags?  Just received Purple from Stonetroll Keep - no gear in it.

thx
