### ISSUE TITLE
Kron Komar Gap - Public Quest Greenskin Chapter 3

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7418]
- Nothing works here.
- ~~Chest from the center of the PQ are needs to be removed.~~

**Comment by Yellowpillow** [comment]
#5547

**Comment by Soulwhisper** [comment]
- [ ] These guys attack you if you get too close to them  :( 
![warhammer online age of reckoning 12 29 2016 - 16 24 27 03](https://cloud.githubusercontent.com/assets/16864486/21545862/80480b38-cde3-11e6-9e79-0c08df9e0986.png)
![warhammer online age of reckoning 12 29 2016 - 16 25 17 04](https://cloud.githubusercontent.com/assets/16864486/21545863/804c5058-cde3-11e6-8900-d10f2bcc6bfd.png)
![warhammer online age of reckoning 12 29 2016 - 16 22 16 02](https://cloud.githubusercontent.com/assets/16864486/21545793/01c8900c-cde3-11e6-9e1d-ea0f1a7f3cc6.png)

**Comment by 0x1911** [comment]
Encountered on the 22./23. of March 2017 as an ~lvl 10 goblin shaman.

* For some reasons some of the orcs (or freshly spawned ones) are attacking me, while i'm in combat with one of the "* hammerstriker, * thunderbeard". I couldn't reproduce it reliable, sorry.

* Stage I (hard): 40/40 Thunderbeards are already killed. If i now killed Hammerstriker their death counted visually to the Thunderbeards, overcapping the GUI label (41/40 Thunderbeards) -> If i run out of the area of the public quest, and reenter both GUI labels are correct. Until i kill another Hammerstriker in that scenario


(Stage II, and Stage III seemed ok coding wise - I failed on the time limit for Stage III though)

**Comment by Razielhell** [comment]
@0x1911 About GUI label #6935

**Comment by Lheana** [comment]
Seems like it was fixed.
