### ISSUE TITLE
Sacred Grove - Public Quest Destruction Greenskin Chapter 3

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7419]
- ~~Stage 1 doesnt work.~~
- ~~This chest needs to be removed.~~
  ![shamanakos_000](https://cloud.githubusercontent.com/assets/16864486/17924620/0e943a66-69f2-11e6-816e-d130ffe70d9d.jpg)

**Comment by Yellowpillow** [comment]
#5547

**Comment by Razielhell** [comment]
- [ ] Stage 3 mobs fight each other. Is it suppose to be like that?
![warhammer online age of reckoning 01 29 2017 - 23 12 34 236](https://cloud.githubusercontent.com/assets/16864486/22407916/71b15b76-e678-11e6-804d-b307b05f8cae.png)
