### ISSUE TITLE
Players / NPCs appearing naked sometimes

### ISSUE THREAD

**Issue by Bobcat1983** [WarEmu/WarBugs#742]
i have noticed that when you have completed a quest and go to hand it in the text shown by the npc is exactly the same as the text from when you first accepted the quest. as far as i can tell this is for all the quests. also when an npc talks to you instead of using the correct terms the text [name] and other similar things come up instead of your actual name, career, or race. not sure if i should make a new topic for this one but ill include it anyway. whenever you accept or hand in a quest a lot of the time the npc you are talking to appears to take off all their clothes or put them back on.

**Comment by Reggaewaldo** [comment]
Will look into tonight on what can be done.

**Comment by Evildoor** [comment]
To help you out a bit:
https://github.com/WarEmu/WarBugs/issues/276
https://github.com/WarEmu/WarBugs/issues/277
these issues are connected with this one (maybe there were others, but nothing comes to my mind right now).
Also, i do believe that the last problem is more general one, it also affects players (they appear naked or with weapons sheathed sometimes) and maybe (though not sure at all) it was even present in original WAR, in which case we cannot fix it. But that's another problem anyway.

**Comment by Reggaewaldo** [comment]
@Evildoor Yes, I have verified this and not been able to produce the issue on the dev server. Hence I guess this is related to packetloss/load during many players online or something similar affecting the client/server connection.

Tagging this for the emulator and removing DB.

**Comment by Stefanosgr18** [comment]
![war 2015-12-22 10-47-04-33](https://cloud.githubusercontent.com/assets/16375224/11951733/0428eff8-a89c-11e5-801e-6d4e04e095eb.jpg)
![war 2015-12-22 10-46-59-89](https://cloud.githubusercontent.com/assets/16375224/11951734/043392b4-a89c-11e5-9630-12545b0677fa.jpg)

**Comment by Luth-RoR** [comment]
Iirc happened on the mythic server too when there was very high load/lag.
