### ISSUE TITLE
Ironclaw Camp - Public Quest Destruction Greenskin Chapter 2

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7420]
- ~~Stage 1 doesnt work.~~
- ~~Chest from the center of the PQ needs to be removed.~~

**Comment by Yellowpillow** [comment]
#5547

**Comment by Razielhell** [comment]
**Implemented but there are many bugs in this one.**
- [ ] PQ Tracker needs to be enlarged.Check Pictures 1,2 & 3. There are mobs in these areas but tracker dissapears.
- [ ] On Stage 2 the first Dog Marauder from the left doesnt count in the PQ.(Picture 4)
- [ ] In Stage 3 Evert Webb gets attacked by Marauder and gets killed.(Picture 5)
![warhammer online age of reckoning 01 29 2017 - 23 17 43 237](https://cloud.githubusercontent.com/assets/16864486/22408037/ac0d8aae-e67a-11e6-9976-a5cdccc482e5.png)
![warhammer online age of reckoning 01 29 2017 - 23 17 44 238](https://cloud.githubusercontent.com/assets/16864486/22408039/ac15d8a8-e67a-11e6-94b4-6a235c2ffdac.png)
![warhammer online age of reckoning 01 29 2017 - 23 22 18 240](https://cloud.githubusercontent.com/assets/16864486/22408038/ac122f32-e67a-11e6-808c-eccf28e1a122.png)
![warhammer online age of reckoning 01 29 2017 - 23 19 40 239](https://cloud.githubusercontent.com/assets/16864486/22408056/de45f844-e67a-11e6-8cff-620657a15dce.png)
![warhammer online age of reckoning 01 29 2017 - 23 23 27 241](https://cloud.githubusercontent.com/assets/16864486/22408072/0c6350aa-e67b-11e6-9edc-108b7ca21173.png)

**Comment by grunbag** [comment]
Fixed in next patch
