### ISSUE TITLE
Sharpthorn Wud - Public Quest Destruction Greenskin Chapter 2

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7421]
- [x] Stage 2 doesnt work.
- [x] PQ area ID is broken.Needs redesign.
- [x] ~~Chest from the center of the PQ needs to be removed.~~

**Comment by Yellowpillow** [comment]
#5547

**Comment by Razielhell** [comment]
UPDATING this one.
- Stage 1 got a terrain issue(Check video).
- Stage 2 spawns only 2 of they 5 Dryads that needs to be killed.

**Comment by Luth-RoR** [comment]
Not sure if this can be fixed yet; depends on if the invisible blocker is on the client or was placed on the server.
