### ISSUE TITLE
Ugrog's Rage - Public Quest Destruction Greenskin Chapter 1

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7423]
- [x] ~~This chest needs to be removed.~~

  ![shamanakos_001](https://cloud.githubusercontent.com/assets/16864486/17925388/6a86f1a8-69f5-11e6-978c-8d30fa106755.jpg)

**Comment by Soulwhisper** [comment]
- [ ] Many Annoying Squigs double spawns in Stage 1.

**Comment by Soulwhisper** [comment]
#8935

**Comment by grunbag** [comment]
already fixed
