### ISSUE TITLE
Goldfist's Hole Recovery - Public Quest Destruction Greenskin Chapter 4

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7424]
- ~~Stage 1 works but needs mob rearrangement + More thunderers. **_Need to kill 50._**~~
- ~~Stage 2 doesnt count kills.~~

**Comment by Yellowpillow** [comment]
#5547

**Comment by Razielhell** [comment]
@Luth-RoR

**Comment by Razielhell** [comment]
UPDATED

**Comment by Razielhell** [comment]
- [ ] Irontoe master Engineer ( Dont remember mob name but he is a hero ) is there from Stage 1 on the rails. When you get to Stage 3 it spawns another one so there are 2 of them.

**Comment by wargrimnir** [comment]
Removed the extra spawn, changed him to a Champion instead of Hero.
