### ISSUE TITLE
Broketoof Camp - Public Quest Destruction Greenskin Chapter 4

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7425]
- ~~Stage 1 works. Needs to interact with Orc Flags.~~
- ~~Stage 2 doesnt. Doesnt spawn Shamans.~~
![warhammer online age of reckoning 01 21 2017 - 21 13 41 309](https://cloud.githubusercontent.com/assets/16864486/22177043/46ec7bbe-e01f-11e6-8ba7-0b168d3c893a.png)

**Comment by Yellowpillow** [comment]
#5547

**Comment by Razielhell** [comment]
UPDATED
