### ISSUE TITLE
Raider's Haven - Public Quest Destruction Greenskin Chapter 4

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7426]
- Stage 1 doesnt work.
- This PQ is for Ranks 2-3 and its Easy in difficulty.Mobs are 9-10 levels.Need to be lower.
- This chest needs to be removed.
![shamanakos_001](https://cloud.githubusercontent.com/assets/16864486/17926770/3419a2c2-69fb-11e6-88f6-d73d5756ce43.jpg)

**Comment by Yellowpillow** [comment]
#5547
