### ISSUE TITLE
Valley of the Rangers - Public Quest Destruction Greenskin Chapter 15

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7427]
- [ ] Some rangers fall out of the PQ area/Killing them doesnt count on Tracker nor give influence.
- [x] ~~This chest needs to be removed.~~
  ![shamanakos_000](https://cloud.githubusercontent.com/assets/16864486/17927160/076c967e-69fd-11e6-8bbf-ef951db83edc.jpg)

**Comment by grunbag** [comment]
Fixed in next patch
added more dwarfs to stage 1 objectives
