### ISSUE TITLE
The Mysterious M.B. quest

### ISSUE THREAD

**Issue by Solarian14** [WarEmu/WarBugs#7428]
Flask in Ekrund  (Redhammer Brewery) do not clickable anymore.

**Comment by Solarian14** [comment]
![image](https://cloud.githubusercontent.com/assets/21218447/17928674/803e8812-6a04-11e6-8677-a233102292f5.png)

**Comment by Solarian14** [comment]
![image](https://cloud.githubusercontent.com/assets/21218447/17928683/8972e810-6a04-11e6-9b84-35242761dc46.png)

**Comment by Ryanfawkez** [comment]
The flasks that are interactable for the quest are inside. The ones outside are merely there for decoration.
