### ISSUE TITLE
Character lost all clothes and sword

### ISSUE THREAD

**Issue by Raefen** [WarEmu/WarBugs#743]
Logged in today to my witch hunter and had no clothes or sword.

**Comment by ozarmidrashim** [comment]
Side effect of a server restart. We know about it, but I can't promise any kind of fix soon.

**Comment by Raefen** [comment]
Missing items are now back but experience and renown are stuck and will not increase. Please let me know if I need to open as new ticket on this issue.
Thanks.

**Comment by Evildoor** [comment]
Was this fixed? Or still persists?

**Comment by Raefen** [comment]
It was fixed.
