### ISSUE TITLE
Malyros' Rest - Public Quest Destruction Dark Elf Chapter 16

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7432]
- ~~Stage 1 doesnt work.~~

**Comment by Yellowpillow** [comment]
#5504

**Comment by Razielhell** [comment]
- [ ] Last stage asks for 8 of them.
![warhammer online age of reckoning 03 25 2017 - 11 35 47 01](https://cloud.githubusercontent.com/assets/16864486/24321212/be215c16-114f-11e7-8cad-7b8ea8822cdd.png)

**Comment by Lheana** [comment]
Has been fixed.
