### ISSUE TITLE
Zeal HoD item stat converting broken

### ISSUE THREAD

**Issue by retkeszaju** [WarEmu/WarBugs#7436]
Hi, i noticed that zealots core ability has broken, i never calculated before, but i think it was working fine, but yestarday there was some mupltiple patches, one of them about preveting using rr 280+, and i noticed this after it. 
I calculated that converting willpower to inteligence works fine the numbers are correct, but from converting inteligence to willpower, now it isn't working now. 

i got stats whitout any armor 192 inte., 221 willp. 
Whit items used (no tactic no rr used) 357 int 514 willpower - HoD on = 650 int, 221 willpower HoD off = 357 int 514 willp. seems its not converting anyithing now for the healer side.
Sry for my bad english. (magic critical - healing critical converting works fine)

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/7310
The characterwindow is unreliable atm; for exact stats that the server uses to calculate type ._getstats_ into the chatwindow.
