### ISSUE TITLE
A Wyvern in the Hand - Public Quest Destruction Greenskin Chapter 16 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7437]
- This mob is unattackable.Its for Stage 1.
  ![shamanakos_000](https://cloud.githubusercontent.com/assets/16864486/17932307/0eda809a-6a18-11e6-82d4-6d1488e24cb6.jpg)

**Comment by Yellowpillow** [comment]
#5547

**Comment by grunbag** [comment]
invalid npc, i removed it

fixed in next patch
