### ISSUE TITLE
Ambush Canyon - Public Quest Destruction Greenskin Chapter 16

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7439]
- Need to add more Miners in Stage 1.
- Stage 2 doesnt count bombers.Maybe this has something to do with them spawning in first Stage 1 too?(**_Need to check again for this one_**)

**Comment by Yellowpillow** [comment]
#5547

**Comment by Razielhell** [comment]
**_## Updating 18/3/2017_**

**Comment by grunbag** [comment]
Stalkers, Miner, Tracker and Foreman will now count in objective 1

fixed in next patch
