### ISSUE TITLE
Chillwind throwing exceptions and multiple Backlash

### ISSUE THREAD

**Issue by Mezirah** [WarEmu/WarBugs#744]
I'm not 100% sure but I think chillwind ticks caused me to eat 3 backlashes in like 2 seconds. May have been a frozen touch proc too in there? not sure but it sucked/
![nerf 9471](https://cloud.githubusercontent.com/assets/11150264/7895114/0f2c5aa6-0631-11e5-9b31-a883d8266aa6.png)

**Comment by Thorgatin** [comment]
Activate timestamps in the chatwindow next time, so you can see what happens in every second.
Also there is an exception thrown by chillwind, so probably it's bugged.

**Comment by ozarmidrashim** [comment]
Chillwind ticks per se can't cause backlash. The backlash chance is calculated when any Combustion or Dark Magic is added. The issue is something else.

**Comment by ozarmidrashim** [comment]
Think I found the cause of this, but time will tell.
