### ISSUE TITLE
Set jeweles "The Winds Impervios"

### ISSUE THREAD

**Issue by BeepBeepIamJeep** [WarEmu/WarBugs#7443]
i cannot get last item for this set 
"The Obdurate Seal"
+4 Toughness
+12 Wounds
+89 Spiritual Resistance
+178 Elemental Resistance
+104 Corporeal Resistance

After you receive these items, head to The Inevitable City and enter the Lyceum. Speak to the Disciple's Assistant just by the Tome Accessory Librarian, Disciple Venomstung, and purchase the Vial of Concentrated Venom in exchange for your five Arachnid Poison Sac(s).

i can buy Vial of Concentrated Venom. becose NPC Disciple's Assistant have it. But athers items he havenot.

can u fix this, becose i need this item :3

p.s. sry for my Eng - its very bad. But i hope u understand me :P

**Comment by Luth-RoR** [comment]
What do you mean with
> But other items he has not.

?

You probably forgot the first step:
_Travel to Thunder Mountain and make your way to the coordinates given. Slay enough Magma Crawlers until you receive Arachnid Poison Sac (x5)._
You need to exchange these poison sacks at the vendor to get the vial.

**Comment by BeepBeepIamJeep** [comment]
i do this, becose i have Vial of Concentrated Venom. its five Arachnid Poison Sac(s) for this item.

**Comment by Lileldys** [comment]
The Vial is for a different item, not "The Obdurate Seal"

The vial is for the "Crow Caller Chain"

**Comment by Luth-RoR** [comment]
You already exchanged the poison sacks to get the vial.
You need to equip the vial for the ToK unlock, it's a pocket item. Then you can take the jewelry piece from another vendor.

**Comment by Luth-RoR** [comment]
As liledys posted:

_The Obdurate Seal: (49k, 45k) Travel to Caledor and make your way to the coordinates given. Seek and slay a Champion scorpion by the name of Crushclaw. Crushclaw will drop an item called Giant Scorpion Stinger. After you receive the item, exit combat and equip this item as it is a Pocket item. Equipping this item will grant you the tome unlock, “Stick the Sticker”, allowing you to claim The Obdurate Seal._

**Comment by BeepBeepIamJeep** [comment]
ty, can u close this ticket ?

**Comment by Luth-RoR** [comment]
I already did.
