### ISSUE TITLE
Debuff icon copyes itself into same mobs

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#7445]
When i put debuff on one mob i switch target to another one and he have icon of same debuff with same timer, but without any effect, so it is visual bug.
With different named mobs this bug dont show up.
It probably have same source with bug, when characters in fight have not only active buff/debuff icons, but random icons of another unactive effects from another characters (affected by those debuffs), and after fight save those icons with 0sec on timer.
![11](https://cloud.githubusercontent.com/assets/18102127/17940440/3779e504-6a40-11e6-8c12-de60f6dea582.jpg)
![12](https://cloud.githubusercontent.com/assets/18102127/17940441/377d4bfe-6a40-11e6-84b3-5b07dbdaa1df.jpg)

**Comment by Luth-RoR** [comment]
Do you have any addons activated?

**Comment by Soulwhisper** [comment]
Probably addon issue.

**Comment by Yellowpillow** [comment]
Yes, this bug caused by Nerfed buttons addon. Sorry for useless report.
