### ISSUE TITLE
Stoneclan's Demise - Public Quest Destruction Chaos Chapter 21 

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7446]
- Rapidfire Turrets arent killable for Stage 1.They reach at 1HP but you cant kill them.
- They shouldnt move when you attack them.(Probably they should do range damage?)
- Ghost chest needs to be removed from the PQ.

**Comment by Yellowpillow** [comment]
#5518

**Comment by Nekronsieben** [comment]
still can't kill the **Rapidfire Turret** 
![war 2016-10-21 21-01-40-71](https://cloud.githubusercontent.com/assets/22836615/19826604/2cb7d3ba-9d8f-11e6-8049-b53fde84e393.jpg)

**Comment by Soulwhisper** [comment]
@Nekronsieben Thanks but this is not working at all so its better to stay closed.
