### ISSUE TITLE
Slayer Keep - Public Quest Destruction Greenskin Chapter 22

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7448]
- ~~Stage 1 doesnt work.~~
- ~~Keep doors shouldnt be closed though? Chest spawns inside i think.~~

**Comment by Yellowpillow** [comment]
#5547

**Comment by Razielhell** [comment]
- [ ] Ok stage 1 needs 100 Engineers. We counted around 10-15 in the area and all are scattered making it time consuming even with full Party. Maybe create some packs?

**Comment by grunbag** [comment]
Fixed in next patch
