### ISSUE TITLE
[White Lion] Pet ability firing delay

### ISSUE THREAD

**Issue by Jaycub** [WarEmu/WarBugs#7451]
WL pet waits about ~3 seconds in-between each ability before using it rather than using it immediately after the GCD finishes. Meaning it's twice as slow as using the abilities manually which is a real pain.

Muh efficiency

**Comment by Luth-RoR** [comment]
Needs dev confirmation if intended, bug or can't be solved differently atm. 
Afaik the pet comunication between the server and the client is still not completely known/decoded; there are some workarounds in place atm.

**Comment by ozarmidrashim** [comment]
Was resolved
