### ISSUE TITLE
Fallen Keep of Grom Rodrin - Public Quest Destruction Greenskin Chapter 19 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7455]
- ~~Stage 1 needs more mobs and also it doesnt work.~~
- ~~All doors in PQ area are closed.You need to climb the mountains to get in.~~

**Comment by Yellowpillow** [comment]
#5547

**Comment by Razielhell** [comment]
- [ ] Stage 1 needs more Sentries.

**Comment by grunbag** [comment]
fixed in next patch

**Comment by Razielhell** [comment]
Shrines destroyed still dont work.

**Comment by grunbag** [comment]
Fixed in next patch
