### ISSUE TITLE
Got tome unlock 

### ISSUE THREAD

**Issue by runebbb** [WarEmu/WarBugs#7457]
Got the unlock kill 100 snotlings when i was in caladins furnace PQ killing elves got it on video that i can add later if needed

**Comment by Soulwhisper** [comment]
He was killing Caladain Smith-Priests and Caladain Guards iirc.Stage 1 both mobs.

**Comment by Ryanfawkez** [comment]
Both those mobs have the correct type and subtype, @Soulwhisper. Are there any other mobs that he could have killed?

**Comment by Ryanfawkez** [comment]
Nevermind, there was the Caladian Protector, Master of the Furnace, Liraenor and Faruen the Creator that had an incorrect subtype. Fixed in next patch.
