### ISSUE TITLE
make gold mounts chaos war camp

### ISSUE THREAD

**Issue by ricdur** [WarEmu/WarBugs#746]
It's possible to make infinite gold at vendor chaos warcamp nordland, just buy a mount 15 gold and u sell it at the same vendor for 60 gold, but if i seat my ass on a horse i can understand is value go up :)

**Comment by DanaBloodkiss** [comment]
Can you tell me which class and which item name?

**Comment by ozarmidrashim** [comment]
Assuming fixed
