### ISSUE TITLE
Die in Reikland - ressurect in Praag (Destruction) 

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#7461]
After being killed in Reikland, specifically inside BO Frostbeard's Quarry or near it, i resurrect in Southern Garrison keep in Praag, instead of Reikland's warcamp. It happens several times, always near that particular BO, and when i run on foot into Reikland instead of using a flight.

**Comment by Kaelang** [comment]
No longer happens in current version of RoR - closed.
