### ISSUE TITLE
Infinite Health Door on Fangbreaka Swamp Keep

### ISSUE THREAD

**Issue by Sixmoons48** [WarEmu/WarBugs#7462]
Even with constant damage from over half a warband, all objectives owned, and the health is depleted, the door will regen itself back to full everytime.  At around 5:30 CST on Wednesday 8/24 this happened 3 times until a GM notified us that the door will need to be fixed prior to us taking it.  
Thanks ahead of time 

In-Game = Noctophilia

**Comment by Luth-RoR** [comment]
Could it be that you just capped empty areas too fast?
Afaik there is a hidden timer in place to slow down circle raiding; until then the area can't be captured again and the door repairs itself.

**Comment by Sixmoons48** [comment]
Well Grandpaa saw it happen and told me to report this bug specifically as
it happened.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
