### ISSUE TITLE
PQ HE 'Dragon Door' in Shadowlands : NPC 'Uthorin Siegewarrior' are lvl 29 when are is level 14-15

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#7464]

**Comment by avenflar** [comment]
Also, the PQ 'objective count' is very small. We killed mobs 10 metres from their spawning point and they weren't counting. We killed the last stage Hero on the road next to his spawning point and it didn't count.

**Comment by Soulwhisper** [comment]
You mean The Dragon Gate ?

**Comment by Luth-RoR** [comment]
Known: https://github.com/WarEmu/WarBugs/issues/6161

**Comment by Soulwhisper** [comment]
#7217
