### ISSUE TITLE
Experience not gain from low level mobs

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#7467]
Playing for 38 lvl character I stop gain experience points for killing 29 lvl mobs. By killing 30 lvl mobs i gain experience without a problem. I mentioned that issue in lower levels with much lower mobs.
Can't remember that in patch-notes, so i assume this is bug.

**Comment by Gintofag** [comment]
Too high lvl difference.

**Comment by Yellowpillow** [comment]
Is it was announced? I dont remember it at all, so is it?

**Comment by Gintofag** [comment]
I think it's work like on live servers.

**Comment by Luth-RoR** [comment]
If the name of the enemy is colored grey, you can't get anymore XP from it afaik.
