### ISSUE TITLE
My login doesn't log me into my account, but into someone else's

### ISSUE THREAD

**Issue by Chalkstix** [WarEmu/WarBugs#7468]
I type in my username and password in the RoR launcher, but when I get the char selection screen, it's someone else's characters and my characters are not there.

**Comment by Yellowpillow** [comment]
Screenshots may be helpfull, also i guess they may need you'r account name to check it out.

**Comment by Chalkstix** [comment]
![charselect](https://cloud.githubusercontent.com/assets/21231518/17954384/07ee7eb8-6a7b-11e6-9d25-e4e32387a129.jpg)
![warlogin](https://cloud.githubusercontent.com/assets/21231518/17954385/07f00bf2-6a7b-11e6-9cc4-d12a5e31fc39.jpg)

Screenshot from my launcher and from the character select screen I get logged into

**Comment by Luth-RoR** [comment]
Is this fixed now?

**Comment by Chalkstix** [comment]
The issue has been fixed. Thank you very much :)
