### ISSUE TITLE
Altdorf Trolls 

### ISSUE THREAD

**Issue by 22635** [WarEmu/WarBugs#747]
Last 2 days of altdorf Trolls farming, seemed bugged to me. I have droped 34 items, and 25 of the for Wich Hunter! I'm sorry but I dont need that much WH items. Also for a week of farming, I have NEVER seen an item for Slayer and Shadow Warrior, most of the items for Wich Hunter!

Also, my friend have started to play yesterday as Archmage, by his words, he droped 18 items from trolls and 13 of them for Wich Hunter.

**Comment by ozarmidrashim** [comment]
Mobs do not have random drops, they drop from incredibly weird and restricted tables. This will be fixed in the next update.
