### ISSUE TITLE
Genisis Fragment of the Sharpshooter

### ISSUE THREAD

**Issue by Teefz** [WarEmu/WarBugs#7470]
[http://i.imgur.com/LigAVKM.jpg]()

The reason behind this post is that, I am pretty sure that the 2% parry must be a mistake. 

SH' & SW's can argueable benefit from parry if they are Stabbin'/Assault, but engineers? That is far-fetched. The stat on the item is a defensive stat, so I guess it would make most sense to change to another defensive stat. A stat that would benefit every class that uses this set.

**Comment by Daniellita** [comment]
Your link isn't working for me. But yeah, dodge/disrupt would seem more appropriate here.

**Comment by Torquemadra** [comment]
you would be wrong. this is not a bug.
