### ISSUE TITLE
Twisted Hounds friendly? (49k, 10k)Saphery

### ISSUE THREAD

**Issue by BeepBeepIamJeep** [WarEmu/WarBugs#7473]
i need to kill them for geting Chaos Hound Fang (x10)
Da Waaagh! Teef  (jewels)

Destruction: After you receive these items, head to The Inevitable City and enter the Lyceum. Speak to the Disciple's Assistant just by the Tome Accessory Librarian, Disciple Venomstung, and purchase the Amulet of Fangs in exchange for your ten Chaos Hound Fang(s). After you receive this item, equip this item as it is a Pocket item. Equipping this item will grant you the tome unlock, “From Mouth to Neck”, allowing you to claim Black Toof.

**Comment by Ryanfawkez** [comment]
https://github.com/WarEmu/WarBugs/issues/7290
