### ISSUE TITLE
[Item] Casque of Hope

### ISSUE THREAD

**Issue by Halhammer** [WarEmu/WarBugs#7474]
Empire Ch. 20 elite influence reward for KOTBS, Casque of Hope, is missing it's skin. In fact it just turns ya bold...
My quest for a featherless helm continues.

**Comment by Ryanfawkez** [comment]
Let me see what I can do...

**Comment by Halhammer** [comment]
Thx Ryan, although now it has feathers too! I'm sorry but this is lookin more and more like a conspiracy against knights who refuse to wear feathered helms...

Also, Empire Ch. 14 inf reward, Casque of Unterbaum: same story

**Comment by Ryanfawkez** [comment]
I'm sorry bro, but it seems Mythic has denied the Knights their featherless look, at least on the late-game appearances!

I remember the mohawk helmet with no feathers being in the game right now, I believe that's the only Knight helm without feathers... aside from some T1 ones.

**Comment by Halhammer** [comment]
ye the one i have equipped right now. i remember on live i had one from a CW PQ, purple bag drop. what's with the one that genesis vendor dude is wearing? i haz gold. lots.
