### ISSUE TITLE
The Griffon Gate - Public Quest Destruction Dark Elf Chapter 7 

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7475]
- Stage 1 doesnt work.Eagle Claws are unkillable.They stuck at 1 hp if you attack them.Also they follow you but they shouldnt because they are ballistas.Similar problem #7446 with turrets.

**This has nothing to do with #5405**

**Comment by Yellowpillow** [comment]
#684

**Comment by Soulwhisper** [comment]
Fixed!
