### ISSUE TITLE
Stone of Ecelsion - Public Quest Destruction Dark Elf Chapter 7

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7476]
- PQ area ID needs to be enlarged.Missing UI on the west area of the PQ.
- ~~Stage 2 same with #4891.Stones are untargetable.~~

**Comment by Yellowpillow** [comment]
#5504

**Comment by Razielhell** [comment]
Stage 2 Archmages that you changed with 28/1/2017 Patch are untargetable Wargrimnir :P @Luth-RoR

**Comment by Lheana** [comment]
Fixed next patch
