### ISSUE TITLE
The Specter of Battle - Public Quest Destruction Greenskin Chapter 6

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7487]
- [x]  In Stage 1 many Screamers fall out of the PQ(Killing them doesnt count them nor give you influence).Mostly those inside the cave.
- [x] PQ Area ID must be fixed.Inside the cave UI dissapears.
- [ ] ~~In Stage 2 Muzinko doesnt spawn.I dont know where he is suppose to spawn but chest spawns up there(Picture 1).So if chest spawns there,these Rocks/Doors (Pictures 2 and 3) should be used as portal to go up on the mountain.**(P.s. IIRC (see picture 4) this mob should tranform into a ?Ghost? Muzinko.Not sure though.**~~
- [ ] Stage 3 should be Hammerstriker Supplies.These are on the other side of the cave(Picture 5) and you should go there using the Rocks/Doors.
- [ ] Stage 4: Kill Fjelig Thunderbeard.No clue about this one.Probably a Hero mob though.
- [ ] In addition there is an item(Mortal flare picture 6) and a Hero mob i killed(Picture 7) up there.

  ![shamanakos_006](https://cloud.githubusercontent.com/assets/16864486/17976361/cb62a66a-6af5-11e6-95a4-866a1cd52637.jpg)
  ![shamanakos_001](https://cloud.githubusercontent.com/assets/16864486/17976359/cb4619c8-6af5-11e6-93e7-c650f1d034de.jpg)
  ![shamanakos_004](https://cloud.githubusercontent.com/assets/16864486/17976358/cb44b9fc-6af5-11e6-94fb-6155c9f29adb.jpg)
  ![shamanakos_008](https://cloud.githubusercontent.com/assets/16864486/17977352/1fb8cbd2-6afa-11e6-861e-48a2ccf57d85.jpg)
  ![shamanakos_002](https://cloud.githubusercontent.com/assets/16864486/17976634/f1b0e9fc-6af6-11e6-8040-5e40ec9fc5bf.jpg)
  ![shamanakos_003](https://cloud.githubusercontent.com/assets/16864486/17977452/73d85110-6afa-11e6-961d-5eb308f59b25.jpg)
  ![shamanakos_007](https://cloud.githubusercontent.com/assets/16864486/17977412/51f0f822-6afa-11e6-9757-f763dc088481.jpg)

**Comment by Razielhell** [comment]
- [ ] On Stage 3 there are no Hammerstriker Sharpshot.

**Comment by grunbag** [comment]
Fixed in next patch

**Comment by Razielhell** [comment]
Need to check that first after Patch.

**Comment by grunbag** [comment]
I only notice that stage 3 was wrong . I don't know what the mortar is about , and I can't add multiple objectives to stage 3
