### ISSUE TITLE
Renown Points

### ISSUE THREAD

**Issue by AspiringRN2017** [WarEmu/WarBugs#7488]
Hi, 

Whenever I spend renown points, they do not seem to be "recorded" into the renown trainer's window. It shows the correct amount spent and how many are available. It also does not increase my stats. 

Thanks!

**Comment by Luth-RoR** [comment]
Already known: https://github.com/WarEmu/WarBugs/issues/4575
Character window issue is also known: https://github.com/WarEmu/WarBugs/issues/1149
