### ISSUE TITLE
Floating aorund in Dragonwake

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#7489]
Alright this is a bit strange. In Dragonwake around 30k, 22k 
![cimbo_016](https://cloud.githubusercontent.com/assets/16117730/17981235/30d5f22e-6b03-11e6-9855-3a70facd90ce.jpg)
it seems that there are some textures missing for my account/character
![cimbo_013](https://cloud.githubusercontent.com/assets/16117730/17981254/457098ec-6b03-11e6-9b77-350b6c50885b.jpg)
which apprently makes it possible for me to fly around.
![cimbo_014](https://cloud.githubusercontent.com/assets/16117730/17981281/6042782a-6b03-11e6-8743-ea8569074938.jpg)
gaining altitude by jumping. When I relog I'm stuck in in the loading screen and have to do type /stuck twice.
This is only a local issue. When I enter the area with textures again I drop to the ground

**Comment by Luth-RoR** [comment]
Very strange; almost all static models/textures are generated by the client. But the character is generated by the server and only rendered by the client.

**Comment by Cimbas** [comment]
I contacted a GM and asked him if wanted to have a look at me floating around. But he told me just to relog so I don't know if he did.

**Comment by Luth-RoR** [comment]
GMs are well known slackers. :stuck_out_tongue: 
Maybe a dev has a clue how this could be possible.

**Comment by Cimbas** [comment]
I downloaded the client again and that fixed this issue for me.

**Comment by Luth-RoR** [comment]
Ok, this could happen if your client files are outdated or faulty according to the devs.
