### ISSUE TITLE
Reaver's End - Public Quest Destruction Dark Elf Chapter 9 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7490]
- [x] Stage 3 doesnt work.Also Korhandir Elite shouldnt be packed with Stage 3 final mobs.
- [x] Korhandir Elite should be Stage 2 Champion Mobs.

Source : http://warhammer.gamepressure.com/warhammer_public_quest.asp?ID=215

**Comment by Yellowpillow** [comment]
#5504

**Comment by wargrimnir** [comment]
Fixed in next.

**Comment by Razielhell** [comment]
- PQ Looks disabled. No PQ Tracker and area is empty of mobs.

**Comment by Razielhell** [comment]
Works fine now :p

**Comment by grunbag** [comment]
Fixed in next patch
