### ISSUE TITLE
Reservation of Honor - Public Quest Destruction Dark Elf Chapter 8 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7491]
- Stage 2 Spear and Sword Pillars have wrong ids each other? Clicking on Spear registers Sword and reverse.Not sure though.Maybe it has something to do with #6935

**Comment by Yellowpillow** [comment]
may be related to #5517

**Comment by Soulwhisper** [comment]
Closing for now because its not important and most likely related to what Yellowpillow said.

**Comment by Aluviya** [comment]
![pillar of the hoof](https://user-images.githubusercontent.com/17249318/29625287-91823466-882b-11e7-8bce-6f3285417c31.jpg)
In the second stage of this PQ you are asked to click on several pillars, the one on the picture is unuseable, you can only aim it as attack target. Furthermore the PQ skips the stage 2 without ever having the pillar tapped. After stage 2 it works as usual.

**Comment by Lheana** [comment]
The 4 Pillars have now to be destroyed during second stage, and must all work.
