### ISSUE TITLE
Praag Order WC guards not strong enough

### ISSUE THREAD

**Issue by NorKalli** [WarEmu/WarBugs#7492]
The guards protecting the east entrance to the praag RVR lake are not the champions, so you can run into the war camp as destro.

**Comment by Yellowpillow** [comment]
You can't run into the war camp, because after couple of regular mobs there is 40 lvl heroes and 55 lvl champions. I believe staircase is not adjacent territory of the war camp.

**Comment by NorKalli** [comment]
![norkalli_028](https://cloud.githubusercontent.com/assets/19868634/17992646/34edfa28-6afe-11e6-9718-6b16e611eb57.jpg)

**Comment by NorKalli** [comment]
![norkalli_028](https://cloud.githubusercontent.com/assets/19868634/17992667/5318a1b0-6afe-11e6-831f-39f9b514d135.jpg)

**Comment by saupreusse** [comment]
can you make a screenshot where exactly you can sneak in? i couldnt manage to find a spot where you are not killed by guards when trying to get inside.

**Comment by NorKalli** [comment]
Hey diddle diddle right up the middle (sprint right through the low level guards)

**Comment by Ryanfawkez** [comment]
Added capable watchmen to the front gate (and also to a side alley). Also fixed the Vanquisher's Hardmantle's appearance.

**Comment by NorKalli** [comment]
Hey that wasn't a bug :(

**Comment by Luth-RoR** [comment]
Lesson learned today:
Never trust DB-devs :japanese_ogre:
