### ISSUE TITLE
Weapon skill fragment critical efect results in wrong talisman

### ISSUE THREAD

**Issue by Chloupek** [WarEmu/WarBugs#7493]
175 green weapon skill fragemnt combined with 1 skill box, 200 curio, 200 gold and 175 essence results in +24 balistic skill talisman during critical proc.

**Comment by Luth-RoR** [comment]
Crits work generally a bit strange atm: https://github.com/WarEmu/WarBugs/issues/6056 https://github.com/WarEmu/WarBugs/issues/4501
But in these cases it worked vice versa.
