### ISSUE TITLE
Autoroll while dead

### ISSUE THREAD

**Issue by bloodi** [WarEmu/WarBugs#7494]
While you are dead, you are excluded from rolls, as in, an item drops and all your group but you will be able to roll for it.

I however have yet to test if you are able to roll manually.

**Comment by Soulwhisper** [comment]
If your corspe is inside the Area ID and you dont respawn then that is correct.

**Comment by bloodi** [comment]
So this report has been like this for a while, with a strange Public Quests label added, i guess i did not explain myself properly as usual.

The issue here is not about contribution on keeps or in public quests, is simply that when you are in orvr or scenarios, if you are dead, you cant roll on items. You simply have no option to do so if you have autoroll on.

That means that multiple items that drop and you should be able to roll for, as in everyone in your group should, you are losing them for no reason without chance of getting them back.

I am pretty sure this was not on Live and if it was, please tell me so i can argue for a change to it on the forums,

**Comment by Luth-RoR** [comment]
I see; i'm sure this is a bug.

**Comment by Soulwhisper** [comment]
Yes,in scenarios if you die and you click to loot roll while you are dead it doesnt register it.

**Comment by Luth-RoR** [comment]
From https://github.com/WarEmu/WarBugs/issues/9704
>Dead person gets need/greed/pass window, but his choice is ignored by client and is not shown in logs. The roll will be made without dead person's response and living players will get the loot as usual.
If all living players have passed, loot will be lost.

Have repeatedly tested it with a friend.
