### ISSUE TITLE
Soul Essence Regen on RvR influence rewards

### ISSUE THREAD

**Issue by FordPrefect89** [WarEmu/WarBugs#7495]
I have noticed that starting with the T2 Chalice of Thunder that the soul essence regen is set to +8 per second.  Was this a change as intended?  In the original game the inf reward chalice in T4 was the first one that a DoK was able to get that had the +8 SE per second regen.  This may create some hate and discontent for me for bringing this up but as of now I don't seem to have an issue with SE unless I get too spammy with my group heal which I only didn't have that problem when I was in RR80 gear.

**Comment by Luth-RoR** [comment]
I'm 99% sure this is intended in RoR, as the _resource regen on books/chalices_ design was done pretty weak by mythic. It basically made every green and blue book/chalice useless, regardless of it's stats.
You can also get purple books as T2 RvR reward and from PvP too (the original mythic design bound resource regen to the rarity of the item - green, blue, purple, golden).

Though (support) questions should go to the forum.
