### ISSUE TITLE
Gromril crossing

### ISSUE THREAD

**Issue by runebbb** [WarEmu/WarBugs#7496]
order capping 2 bo's at once and in wrong order
![baroz_010](https://cloud.githubusercontent.com/assets/20157418/18023345/969cd2c6-6bf8-11e6-899d-5f05c31edce0.jpg)
![baroz_009](https://cloud.githubusercontent.com/assets/20157418/18023349/9a1e1b8a-6bf8-11e6-9418-e960450cf9e0.jpg)

**Comment by Luth-RoR** [comment]
Flag cap issues with the sc are known: https://github.com/WarEmu/WarBugs/issues/7237
