### ISSUE TITLE
kill count not working/ showing wrong

### ISSUE THREAD

**Issue by runebbb** [WarEmu/WarBugs#7498]
![baroz_006](https://cloud.githubusercontent.com/assets/20157418/18023445/6bb91bea-6bf9-11e6-99dc-2e6ff84bf492.jpg)
this goes also under pve that u get credit for the kill but not the loot or anything yes yes chosens are dps but can still get kills :P

**Comment by Luth-RoR** [comment]
PvE contribution works differently afaik, to prevent KB stealing.
Combatlog needed, to see if the enemy wasn't killed by an ability of yourself, or a buff proc on you from another class (or something like that).

**Comment by runebbb** [comment]
even so u se in the chat that i got a kill and i didnt in the kill count so its a bug there in the picture u can se even whitout the combat log but i will try to get a new screenshot for it the once in the bloomoon time i get a killblow again

**Comment by Luth-RoR** [comment]
What i meant is (for instance):
on the mythic server a WP could get kills in the scenario statistics with 0 damage done, if he buffed other team members with his _prayer of righteousness_ and they did the killing blow with the damage from the buff. 
The chatwindow high likely did say "You have slain ..." in that case too, but in the scenario stats the WP got the killblow.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
