### ISSUE TITLE
Empire Chapter 3 PvE - Respawn area

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7499]
- Dying anywhere inside Chapter 3 PvE area should spawn you in Chapter 3 and not in WC.Tested dying on spots(dots).All times respawned in WC.
  ![pordh_000](https://cloud.githubusercontent.com/assets/16864486/18023854/56d43814-6c07-11e6-83d3-c24ab776416f.jpg)

**Comment by Luth-RoR** [comment]
Current handling is afaik: You always respawn at the nearest healer; though in this case there should be the PvE WC healer nearer from some spots, which is strange.

**Comment by Soulwhisper** [comment]
I know that and that why i tried to die closest to Chapter 3(NorthEast). Maybe its the same issue as #7450 ?? If so

**Comment by saupreusse** [comment]
I should add fixed spawnpoints to all maps. The problem is that its a shitload of work and I am a lazy chap.
