### ISSUE TITLE
SW - Stances don't register after zoning

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#750]
Probably known but I have noticed that all Stance checks do not function after zoning, you guys probably know about this already...

- play scenario and finish as Assault stance
- after zoning or Scenario as Assault stance
- Acid Arrow, Spiral-Fletched Arrow are no longer able to be used

work around - change stances and back again.

**Comment by ozarmidrashim** [comment]
Assault Stance is missing its "PersistsOnDeath" flag on the live server, I believe.
