### ISSUE TITLE
Alter Fate (Rank 4 Morale WP Skill) not working as intended.

### ISSUE THREAD

**Issue by allmynamesaretaken123** [WarEmu/WarBugs#7500]
Me and my guild mates were busy trying to level in Praag (Hell's Fall PQ) and our Warrior Priest decided to test out his Rank 4 Morale skill Alter Fate on my Swordmaster after dying. Long story short, Alter Fate morale ability does not work in PvE (the revive window pops up but you don't actually get revived after accepting it), furthermore the player affected by the Alter Fate buff/heal icon cannot be revived by Breath of Sigmar either. We had to wait till the buff icon faded before actually reviving normally. We haven't tested it on different healers or in PvP.

![fef](https://cloud.githubusercontent.com/assets/21272274/18024929/1736280c-6bee-11e6-98b7-44b4e5f7cc81.png)

IGN: Inayah (Order)

**Comment by Luth-RoR** [comment]
No need to test it for different healers, it should be the same ability ID for every healer.

**Comment by sioding** [comment]
next test - you need not wait until the window fade - a /reloadui works too

**Comment by Bonzoooo** [comment]
Alter Fate still does not work.

**Comment by sioding** [comment]
Fixed
