### ISSUE TITLE
Mind killer - BG 

### ISSUE THREAD

**Issue by herrmarek** [WarEmu/WarBugs#7501]
pictures wrong numbers, in description is for example : lower wisdom/inteligence by 5 points and at strike it lower by 3 points

**Comment by Luth-RoR** [comment]
How did you check this?

**Comment by herrmarek** [comment]
description on ability, vs description after strike, on enemy's bar

**Comment by Luth-RoR** [comment]
I just checked it with .getstats, can confirm.
