### ISSUE TITLE
Talisman making critical success bug.

### ISSUE THREAD

**Issue by arEntropic** [WarEmu/WarBugs#7502]
Critical success on making 28 lvl rare talismans gives you the weaker version of the talisman you made.
![toukan_011](https://cloud.githubusercontent.com/assets/20247573/18028087/89cb58b2-6c7d-11e6-9cdb-dad7ee41969b.jpg)
![toukan_012](https://cloud.githubusercontent.com/assets/20247573/18028089/8e207f82-6c7d-11e6-84ec-90f6242370e2.jpg)
![toukan_013](https://cloud.githubusercontent.com/assets/20247573/18028091/91d35ec4-6c7d-11e6-8531-83e1e359d8c7.jpg)
![toukan_014](https://cloud.githubusercontent.com/assets/20247573/18028092/94f63086-6c7d-11e6-9360-fecd9b475d00.jpg)

**Comment by Luth-RoR** [comment]
Known: https://github.com/WarEmu/WarBugs/issues/6056 https://github.com/WarEmu/WarBugs/issues/4501
