### ISSUE TITLE
Potion does not appear in inventory

### ISSUE THREAD

**Issue by relg** [WarEmu/WarBugs#7508]
I just cultivated the Crimson-Tipped Pyre Ivy seeds for days now until 150 level and brewed 20 portions. No potions came out of it.  I don't know if that gave any skill-ups (none showed) but no molotov-cocktail did nappear in my inventory.
I saw that in another post, but that one was closed, so I think that it might be marked as solved.
Thanks for the game though.
Relg

**Comment by Luth-RoR** [comment]
Already known: https://github.com/WarEmu/WarBugs/issues/1526#issuecomment-143224532
Crafting needs completition & some finetuning.
