### ISSUE TITLE
Loging in to some 1 elses account 

### ISSUE THREAD

**Issue by nirb333** [WarEmu/WarBugs#7512]
after the patch each time i log in to my account i get inside another account with two characters i have never seen.
i want my old account back :( what can i do?
username is nirb333
heres a picture from the new account wich i dont know
![capture](https://cloud.githubusercontent.com/assets/21290262/18033219/f24253ac-6d25-11e6-871f-49ea01383de5.PNG)

**Comment by Luth-RoR** [comment]
Seems like the same issue: https://github.com/WarEmu/WarBugs/issues/7468

**Comment by nirb333** [comment]
indeed looks similar any know solution?

**Comment by Luth-RoR** [comment]
Not yet. I posted this one in the temachat too.

**Comment by nirb333** [comment]
thx for the fast respond.
looks like other post is from 3 days ago and no solution yet. you think a fix would be found soon or should i give up and start a new account?

**Comment by nirb333** [comment]
just logged on and all my characters were back so for now im good :) 
thanks agien for the quick help

**Comment by Luth-RoR** [comment]
Seems like it was a DB loading issue. There should be a general fix soon.
