### ISSUE TITLE
Saving Souls Quest

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#7514]
Looks as completed but its not.
![maxeras_051](https://cloud.githubusercontent.com/assets/16864486/18033624/c3d80446-6d32-11e6-881c-c8d8d3f9dfc2.jpg)

**Comment by thorbolt80** [comment]
Now you can finish the quest but you can't take the reward for now. I am not able to choose between two sets of shoudler as a reward.

**Comment by Razielhell** [comment]
Fixed quest markers for this one. 
The other issue is major when there are multiple quest objectives.
