### ISSUE TITLE
Scenario Visual Bug

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7515]
**This used to work but after some patches stopped working.**
- Once you hit 40 level you dont gain any more xp.Bonus Xp and Xp gain in Scenarios should be 0 for 40levels.
![maxeras_051](https://cloud.githubusercontent.com/assets/16864486/18033724/9a7e5346-6d34-11e6-92e4-307333438cf8.jpg)

**Comment by Luth-RoR** [comment]
This was reverted iirc to allow guilds to gain additional levels, even when there are only level 40 players in the guild. Otherwise people had to play alts to level guilds.
