### ISSUE TITLE
Destruction starter area bugs

### ISSUE THREAD

**Issue by Lanric** [WarEmu/WarBugs#7516]
As of today's patch:
1. The quest "The Heart of Battle" cannot be completed - players do not recieve the item necessary to complete it. Before the patch that step of the quest was auto-completed on pickup.
2. Most of the starter quests now force the players to choose all rewards instead of picking one (not sure if intended, but it allows i.e. to pick all 4 trophies avaiable in the starter zone.

**Comment by Lanric** [comment]
Also, Tower Guards in the same area count as High Elves.

**Comment by Ryanfawkez** [comment]
Also fixed.
