### ISSUE TITLE
CAN'T LOGIN GRUMVIR

### ISSUE THREAD

**Issue by Carsana** [WarEmu/WarBugs#7517]
Hi all,
I have been trying to login Grumvir (Account CARSANA) but I can't manage to go through. It appears among the characters selectable but once selected it starts loading and always brings me back to the character pages and disconnect me from the server.

Thanks a lot in advance for your help with this issue.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/7513#issuecomment-242970201

**Comment by Carsana** [comment]
I have tried now to log on; I initially succeeded but have been logged off in 5 seconds.
I am unable to login as of now.
Sorry for this

**Comment by Luth-RoR** [comment]
Some players have this atm as it seems, the devs look into it.
