### ISSUE TITLE
cannot login on my account

### ISSUE THREAD

**Issue by Inlsl** [WarEmu/WarBugs#7518]
i creat a new acc, and cannot login, but i can use ather

sry for my Eng, iam ru

**Comment by Inlsl** [comment]
my profil
https://www.returnofreckoning.com/forum/memberlist.php?mode=viewprofile&u=129248

**Comment by Ryanfawkez** [comment]
You'll need to PM a GM on the forums to activate your account.

**Comment by Luth-RoR** [comment]
The bugtracker is only for bugs, please use the support forum for support.
