### ISSUE TITLE
Loading currently bug

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#7519]
after keep crash i tryed /stuck 2 times in row, thing is a never seen windows popped telling me

loading 49895 then game crashed again

the char was before the/stuck in IC
![screenshot_003](https://cloud.githubusercontent.com/assets/7527415/18034845/79eddfc6-6d47-11e6-887b-bd7778a9ef51.jpg)

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=2&t=16524
