### ISSUE TITLE
RP/Zealot - RoB/HoD ability Icon appears always on

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#752]
These ability to control this class HPS/DPS mode appears always on, and, the CD timer seem different than from Mythic Live.

**Comment by gittoaster** [comment]
According to some on the bug threads, and I agree, the CD timer should on happen after the rune is turned off...  It's supposed be some sort of toggle afaik.  

Also, at times I am seeing the Flee ability also become "always on" in the icon ability area.

pic here
![Uploading imghost.jpg…]()

**Comment by ozarmidrashim** [comment]
Cooldown element fixed in next.
