### ISSUE TITLE
Keyboard almost all keys stop functioning

### ISSUE THREAD

**Issue by relg** [WarEmu/WarBugs#7520]
I was just in the middle of a scenario when my keyboard suddenly gave up on me. Strangly, the esc-keys and then num-and windows-keys are still working fine, and as you can see I can use it normally when not in the game, but logged into the game, the keyboard is not function any more. I tried to log-out and quit the game, but the problem still continues when relogging into the game and there is nothing I can do to change that.

**Comment by relg** [comment]
After waiting some time, the keyboard is now working again.  I hope that this is not a bug, but instead a problem I have, though I had this problem before. Thats why I posted. 
Thanks for keeping the game running.

**Comment by relg** [comment]
So it just happened again. This time I was not in a scenario, but instead in the city when suddenly the keyboard stopped functioning. Same again, Esc, window are functional.

**Comment by Luth-RoR** [comment]
Client hardware failures are out of reach of the RoR server; very high likely not a bug.
Maybe test it with a different keyboard and/or different games.

**Comment by relg** [comment]
Thanks for replying. I have tried another keyboard. Allways with the same result. I get kicked out of the game one, two or tree times and then the keyboard stops working. It's only this game - in no other situation is the keyboard not working. I am currently writing this while on the destop. In the game itself though, it's like the keyboard is switched off. If I return to the game only 3 keys will be functioning. This doesn't seem to me as a hardware failure. Other games are fine. I never had any problems of this kind before and I have been playing this game for years now. Well, I will just have to try and figure something out. Thanks for the game again - you guys are great.

**Comment by Luth-RoR** [comment]
Ok, then it's maybe related to the disconnect issues that happen since the last patch. Devs work at a solution atm.
