### ISSUE TITLE
Auto Attack can hit players through the keep gates

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#7522]
I mentioned this in TM's left keep. I hit ironbreaker and he entered into the keep's first doors. After that i was able to continue hitting him with my auto attack as long as he was in range of auto attack and in my target. Covenant also worked from auto attack through the doors.
![arena_035](https://cloud.githubusercontent.com/assets/18102127/18035864/3d5e1a1c-6d6f-11e6-9e74-3cd85e5b1e09.jpg)
![arena_036](https://cloud.githubusercontent.com/assets/18102127/18035895/46d9cd4c-6d70-11e6-8d11-ab00167bec60.jpg)

**Comment by Luth-RoR** [comment]
Iirc according the aza this can't be fixed atm.
