### ISSUE TITLE
guild tactic bug

### ISSUE THREAD

**Issue by runebbb** [WarEmu/WarBugs#7523]
![saintofshadws_000](https://cloud.githubusercontent.com/assets/20157418/18036527/e254933c-6d6c-11e6-8270-f0b5d8f41eec.jpg)
![saintofshadws_001](https://cloud.githubusercontent.com/assets/20157418/18036528/e4b807bc-6d6c-11e6-9182-08b4450151aa.jpg)
![saintofshadws_002](https://cloud.githubusercontent.com/assets/20157418/18036529/e6a18f3a-6d6c-11e6-976d-9497eb49ecb4.jpg)
remoced the enchanced of fame and remade it with renown skill instead
![baroz_001](https://cloud.githubusercontent.com/assets/20157418/18036532/086196ec-6d6d-11e6-9c13-66ca869aa473.jpg)
even when relog

**Comment by Soulwhisper** [comment]
These are not implemented yet.

**Comment by runebbb** [comment]
even so u can se it overwrote the other so still a bug when one got removed and overwerote the other

**Comment by Yellowpillow** [comment]
#5292 read comment below
