### ISSUE TITLE
Talisman Making does not work anymore

### ISSUE THREAD

**Issue by BlackFalco** [WarEmu/WarBugs#7525]
Hi guys, as from title my crafting does not work anymore.

This has been happening to me since last server reboot because of patch.

I just cannot move curio from inventory to crafting window.

I've already tried reloggind different times and I did also .respec but with no results :(

**Comment by Soulwhisper** [comment]
I have to ask though.
Have you placed a container first?
If so then have you placed a fragment?
Then you can place curio.

**Comment by BlackFalco** [comment]
Aye, did that but still does not work :(

I've tried on my other chars and it works but it doesnt work on my WE anymore :/

**Comment by Luth-RoR** [comment]
Afaik the DB has still loading issues atm, maybe this is related to it.

**Comment by avenflar** [comment]
To add my anecdote, I completely lost talimaking, pillaging and all my crafting compos on one of my character

**Comment by BlackFalco** [comment]
Let's see what happens...
