### ISSUE TITLE
White Lion bugs

### ISSUE THREAD

**Issue by DUSKANGEL** [WarEmu/WarBugs#7527]
Hello, after some tests on my WL i want to report some Bugs, First of all Character dont get any morale when pet hitting any kind of target. Second, pet dont have same speed with character if he use horse. Pet Taunt (Lion roar) dont work. Third can use Fetch even with out line of site (skill got cooldown but target remain on same spot) while skill should'nt be usable.

**Comment by Soulwhisper** [comment]
1 bug per report please.Or organise them better like this.
- [ ] X
- [ ] XX
- [ ] XXX

**Comment by Luth-RoR** [comment]
I just did a quick test and couldn't use fetch from behind a tree while i was still in range.

Please use a minimum standard for reports: https://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=16399&p=180455t#p180455
