### ISSUE TITLE
award t1 dwarfs order

### ISSUE THREAD

**Issue by Inlsl** [WarEmu/WarBugs#7529]
hello, can u check award t1 dwarf for order, why thera 2 boots 9lvl with the same stats, but different name?

**Comment by Luth-RoR** [comment]
Award?

**Comment by Luth-RoR** [comment]
Just in case my response was unclear: why should someone check the whole DB for hours, just to find the boots that you mean?

**Comment by Inlsl** [comment]
[url=http://radikal.ru/fp/abe864bc8f624b29b4bcb19afa722c78][img]http://s009.radikal.ru/i309/1608/bd/9c0d18af458c.jpg[/img][/url]

[url=http://radikal.ru/fp/d946b78985674824b67003bf6546d996][img]http://s017.radikal.ru/i425/1608/9b/f4da9622b724.jpg[/img][/url]

**Comment by Luth-RoR** [comment]
I see.

**Comment by Ryanfawkez** [comment]
Different name because different items. Next time, please try to include some documentation on how the stats were on live. I will look to see if I can find an item source for the correct stats.

**Comment by Ryanfawkez** [comment]
Going by these sources:
http://www.arsenalofwar.com/armor/Destruction/Lookout%20Darkboots
http://www.arsenalofwar.com/armor/Destruction/Ironmane%20Thighbinds
It seems the boots require two stats, while one of which has offensive stats, the other defensive stats. Will tweak all boots accordingly.
