### ISSUE TITLE
Cast animation/Cast bar stuck when target dies before cast finishes

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#753]
I tested this on 2 classes so far and I am able to repro it, quite easily.  

use a class with 2/3 second cast (i tested fireball/fieryblast/pyroclastic surge/eagle eye/acid arrow)
try to cast the spell when the target is almost dead
cast bar and animation will get stuck (until next ability used)

Only occurs when the target is very close to being dead (or dead already) when the initial cast is started.  
hope that helps..

**Comment by ozarmidrashim** [comment]
Fixed in next.
