### ISSUE TITLE
Potent talisman of purpose

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7531]
Used 100lvl container + 200lvl purple willpower fragment + 200lvl curio + 175 gold essence + 175 magic essence.**Had critical success.**

![phantomas_000](https://cloud.githubusercontent.com/assets/16864486/18064466/456bef12-6e38-11e6-854e-60a0725d4a94.jpg)

**Comment by Luth-RoR** [comment]
Likely the same as https://github.com/WarEmu/WarBugs/issues/7493 https://github.com/WarEmu/WarBugs/issues/6056 https://github.com/WarEmu/WarBugs/issues/4501

**Comment by nalgol** [comment]
found the error fix is pushed to rep
