### ISSUE TITLE
tome unlock “Broken Men, Broken Blades.”

### ISSUE THREAD

**Issue by Durhim** [WarEmu/WarBugs#7533]
Hello,

I collect 5 Broken Wright Blades for unlocking in the tome unlock “Broken Men, Broken Blades.” but it unlocks nothing and I can't get the associated reward, shroud death cape.

Is it a known problem ? And can I hope to get this reward ?

thanks, regards

**Comment by Yellowpillow** [comment]
go to the library and trade those items to single item that's provide unlock

**Comment by Durhim** [comment]
Ok, thanks, it works :)

**Comment by Luth-RoR** [comment]
Next time please use the support forum for support question. Thanks.
