### ISSUE TITLE
The Threat Revealed

### ISSUE THREAD

**Issue by elfwolf** [WarEmu/WarBugs#7534]
The quest in Ellyrion where you have to kill 9 Uthorin Cage Sentries and free 3 Ellyrion Captives. Killing the sentries works fine but in order to free the captives you have to kill Uthorin Wardens and pick keys off their bodies. When I kill the wardens, they don't drop keys, which keeps me from freeing the captives and ultimately completing the quest. Also the person you turn the quest into, Sethys Stormwalk in Reaverspring, has a completed quest icon above his head as soon as you accept the quest.
Hope you can fix it! 
Thanks,
Elfwolf (Lvl 22 Shadow Warrior)

**Comment by Luth-RoR** [comment]
Quest has several issues: https://github.com/WarEmu/WarBugs/issues/6217 https://github.com/WarEmu/WarBugs/issues/3915

**Comment by thorbolt80** [comment]
Not fixing but you can target cage (without effect) Then I also add unfortunately you can also kill the captives with Aoe... :(

**Comment by ErikWPotter** [comment]
Given the age of this ticket I'm not confident that this comment will be noticed anytime soon...but I'll try this first.

Quest: The Thread Revealed

Quest text says slay guards and retrieve keys from wardens to free captive elves.
Step tasks are "Uthorin Cage Sentries 9/9" and "Ellyrian Captives 0/3"

In a copse of trees at about 49k, 57.6k there is a slave wagon surrounded by many Uthorin Warden and Uthorin Cage Sentry. Killing the sentries gives credit but killing the wardens does not earn any keys. No a side note, I've recently deleted (a few quests ago)about 40 quest item gor horns from my quest backpack. While looking for keys I noticed 3 stacks of "Parchment" totaling 86 items had recently appeared after killing wardens. I'm not sure if that is related.

At this same slave wagon area there are "Ellyrian Prisoner"s in cages. They don't respond to interaction and the cages, though selectable, don't either...even after killing many wardens.

Near the perimeter of the map (Example at abot 51,970, 57410) target lake you can find Uthorin Dreadblades guarding Ellyrian Reavers that are ankle chained to stakes. Even after killing wardens these Reavers and their leg chains/stakes don't respond to interaction either.

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
