### ISSUE TITLE
Ch 20 Dark Elf - Senthoi Pool PQ

### ISSUE THREAD

**Issue by NorKalli** [WarEmu/WarBugs#7535]
The mobs necessary to complete the 1st stage PQ are missing

**Comment by Yellowpillow** [comment]
#5504

**Comment by NorKalli** [comment]
1 trueshield was found, but gives no credit for kill

**Comment by Soulwhisper** [comment]
This can be closed :)

**Comment by saupreusse** [comment]
Closing. PQ is not yet active.

**Comment by Razielhell** [comment]
Implemented but stuck on Stage 2 which doesnt work.
![warhammer online age of reckoning 06 10 2017 - 11 46 26 01](https://user-images.githubusercontent.com/16864486/27001432-96f52018-4dd2-11e7-8542-1ecb7913623a.png)

**Comment by Lheana** [comment]
Fixed next patch

**Comment by sioding** [comment]
Fiexed with patch from 10.11.2017
