### ISSUE TITLE
dok reward for quest "theologians" is dubious

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#7539]
There is accessory with intelligence in it. DOKs can't use intelligence in any way. 
![arena_037](https://cloud.githubusercontent.com/assets/18102127/18088053/53ae1262-6ec9-11e6-959e-f98d364391bd.jpg)

**Comment by M0rf** [comment]
possible dok reward is for sorc and sorc reward is for dok, atleast the stats look as if it could be the case.

**Comment by Torquemadra** [comment]
possible green tali jewel from an easy quest may not remain the case
