### ISSUE TITLE
keep lord's knock back enemies too far and reset his HP to 100%

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#7540]
When keep lord agro at somebody and knock back everyone around him - if that person knocked back too - he fly away too far away, even inside keep enemy fly up to the ceiling. Because of that keep lord resets and regain 100% of his health points. In one keep siege it can happens so many times that the whole attack becomes ridiculous, giving defenders unfair advantage. Even without defenders at all keep lord regain HP to 100% all the time because of that.

**Comment by M0rf** [comment]
not a bug imo, while this isnt a place to discuss this, if you have organised players who position correctly,  tanks who taunt/challenge it isnt a problem, instead of complaining give it some time for ppl who are use to no brain keep lord fights to figure out how not to be a nub.

**Comment by Yellowpillow** [comment]
I thought that if he restores 100% health after throws people up inside the keep (and not throwing out of it), it is a bug.

**Comment by Torquemadra** [comment]
you have verifiable proof that the primary agro holder had this happen to him and someone else didnt taunt/hit him with a taunt weapon/hit him while wearing armour with a taunt proc who then went flying out of the room?

**Comment by Torquemadra** [comment]
There might be a z- axis bug with the lords code. Monitoring.

**Comment by Yellowpillow** [comment]
i saw it in High Elven keep (DW). Next time we be there i'll try to record it if i have a chance.

**Comment by sioding** [comment]
keep lords are working fine now. close
