### ISSUE TITLE
Immortal object carrier

### ISSUE THREAD

**Issue by Talissera** [WarEmu/WarBugs#7541]
![1](https://cloud.githubusercontent.com/assets/14876300/18099511/89990fbe-6eef-11e6-9653-7888e3ec0098.jpg)
Black Fire Basin
Enemy team captured the object and activated it bringing 80 points, then KoBS put the point and stay all of the time near the order resp camp. He didnt die all of the scenery from tick. We couldnt kill him or healer because guards are near. Nor we couldnt wean because one kill = just one point on this scenery.

**Comment by Luth-RoR** [comment]
In that case the order side shouldn't get any scenario point ticks (when too close at their spawn/hiding in guard range). Is it confirmed that the order side got any more points during the time the kotbs did this?

**Comment by Talissera** [comment]
They did 1st tick as always putting object to the pile and earn 80 points. Then they just stay with the resped object near the resping camp, effectively freezing a progress. Eighty first point they earn on kill. We made six kills near their resp, hunting theirs WL.

When there was 3 mins till the finish they stop freezing and put the object and we could earn our points, but with less time we lost.

I thought object should kill carrier if he carries the object long enough.

**Comment by Luth-RoR** [comment]
If he has a high HP value/many healers and the other side can't do enough damage or has no incoming healdebuff, this can happen (it did on the mythic server too). 
But that's not a bug.
