### ISSUE TITLE
Ritual of Lunacy visual issues

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#7543]
the zealots ritual of lunacy (the healing one) appears to be incapable of striking critical heals (just laid it down 3 times in pve and didnt get a single crit) and also dosnt trigger any of my on heal tactical effects (dosnt grant shields, heal buffs or ap restore) which a friends of mine who used to play a live zealot all the way to rr100 tells me it should, and i seem to remember it dong so on my own zealot

also it only triggers a healing animation when you first lay it down, none of the subsequent ticks have the animation, and the icon on player buffs just identifies it as "ritual of lunacy" with a timer, and no "periodically recovering X health"

**Comment by Luth-RoR** [comment]
> a friends of mine who used to play a live zealot all the way to rr100 tells me it should

It never did. At least not the mirror ability on the RP. It was like a 100% proc effect (no crit) and procs can't/couldn't proc other procs (tactics in this case).
It would be also _a little bit_ OP if it worked that way.

About the second part of this report: It could be possible that the buff effect had another ability ID and that atm the wrong one is used; in case it had not, this can't be fixed atm as it would be a client side issue. 
A video of the effect would help to verify if it was bugged on the mythic server too.

**Comment by MightyPhred** [comment]
i just screenshotted my combat log with is glorious lack of crits, im gonna have a look on YT to see if i can video evidence of it triggering tactics on live

**Comment by MightyPhred** [comment]
https://postimg.org/image/wj2wrkee1/ - a screenshot of my combat log, showing my 13% heal crit chance (probably supposed to be a bit higher than that) and many ticks of the ritual of lunacy all of which heal for precisely 246 without one single crit

**Comment by ozarmidrashim** [comment]
https://github.com/WarEmu/WarBugs/issues/2343

Please search before posting. Ritual of Lunacy was previously reported as bugged as it would critically heal. It will not be changed.

GFX issue is considered very minor and will not be fixed any time soon.

**Comment by MightyPhred** [comment]
https://www.youtube.com/watch?v=RLG4dbDEPg0 - and here i found a youtube video of someone playing a zealot, which i had to watch at half speed to be sure, in the 2 seconds 25-27, he casts a flash of chaos which heals someone off in the distance for a non-critical 789hp, at this point in time his ritual of lunacy is deployed off screen somewhere (it can be seen on his buff bar), and he triggers a restorative burst (triggered by critical direct heals) BEFORE he casts his next flash of chaos which is a crit

**Comment by ozarmidrashim** [comment]
* Master Rune of Adamant: This ability will no longer trigger effects which are caused by direct heals (such as Restorative Burst).

This is the RP mirror, disproving the first part of your report as well.

**Comment by grunbag** [comment]
Proc never crit since 1.2
