### ISSUE TITLE
"So the other day I was horsepooling and..." 

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#7544]
![arelith_000](https://cloud.githubusercontent.com/assets/19625008/18104641/602fc1d8-6efc-11e6-9a65-ec4a200dd7bd.jpg)

Literally no idea what happened, I summoned my horse next to the emblem/meda vendor and that guy hitched a ride

**Comment by Luth-RoR** [comment]
Referring to: https://github.com/WarEmu/WarBugs/issues/7291 https://github.com/WarEmu/WarBugs/issues/7292

**Comment by Torquemadra** [comment]
linked, no need to keep reports of the same thing open
