### ISSUE TITLE
Divine Favor M1 - Going off on self when no LoS

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#755]
Divine Favor M1 (WP/RP, etc) is going off on self (and criting) when no LoS.  Not proper behavior!

I am not sure if this is just a global heal behavior ATM of the rework, so...

(note however the Range check is working well +1)

**Comment by ozarmidrashim** [comment]
Divine Favor critting was already reported.

Any heal which can't see its target changes its target to self if it is capable of affecting self. Please advise of proper behaviour for all heals.

**Comment by gittoaster** [comment]
Well, what I know is

1) current behavior for ST ability heals uses AP when no LoS (not proper)
2) current behavior for ST Moral heals consumes Moral when no LoS (not proper)

I am fairly certain there should be a LoS check for ST ability heal and ST Moral heals, and not to heal self if no LoS to friendly target.

If someone else knows more, please clarify.

**Comment by ozarmidrashim** [comment]
Confirmed with test group, fixed for next.
