### ISSUE TITLE
Tezakk Gnawbone don't drop loot (T4 lair boss)

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#7550]
We killed him but gain nothing but few silver coins.
![euthanizer_002](https://cloud.githubusercontent.com/assets/18102127/18112544/8c64ec0a-6f39-11e6-9e56-6d4748532372.jpg)

**Comment by Ryanfawkez** [comment]
Requesting documentation for which gear pieces he is supposed to drop.

**Comment by Soulwhisper** [comment]
@Ryanfawkez https://www.youtube.com/watch?v=J4oIr3ftHA8
Pause at 9:30.Can you see it?
Cant see the name of the item.
+ ?44 Armor
+21 willpower
+13 Toughness
+ ?? Intel
+ ?? ????

**Comment by Yellowpillow** [comment]
He supposed to drop shoulders with stats equal shoulders from the lair of Elrin Helfried, but with different name of item (obviously).
On video stats are:
21 WP
13Tou
10 int
20 heal power

**Comment by Ryanfawkez** [comment]
Yup, item prefix is Gnawbone's.

**Comment by Yellowpillow** [comment]
fixed in last patch

**Comment by Yellowpillow** [comment]
He not dropping loot again.
![tranquillity_034](https://cloud.githubusercontent.com/assets/18102127/19022344/47f235f6-88e7-11e6-84d0-c7b87c01567f.jpg)

**Comment by Torquemadra** [comment]
He shouldnt be dropping loot, no lair bosses in t4 should until I give them abilities

**Comment by Soulwhisper** [comment]
Torquemadra

Lair of Tezakk Gnawbone fully functional.
