### ISSUE TITLE
Way to lair of Tezakk Gnawbone can be shortcuted

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#7551]
You supposed to jump through the ruined wall pieces, but there is the way to skip it and reach lair boss.
Invisible wall or something blocking that chaos spike would fix this issue.
![324626262](https://cloud.githubusercontent.com/assets/18102127/18112679/76754e48-6f3a-11e6-8bcc-879f784ae53c.png)

**Comment by saupreusse** [comment]
Fixed in next patch

**Comment by Yellowpillow** [comment]
fixed in last patch
