### ISSUE TITLE
EMPIRE ch. 21

### ISSUE THREAD

**Issue by AldrethCZ** [WarEmu/WarBugs#7555]
Sowing sorrow
Requirements for completing this quest:
Invalid Creature,plz report to GM. QuestID 31002,Objld=42816

**Comment by Ryanfawkez** [comment]
NPC is missing due to the fact it requires a spawn script that was not packet logged.

**Comment by Luth-RoR** [comment]
Known: https://github.com/WarEmu/WarBugs/issues/7097
