### ISSUE TITLE
Lvl 5 Item "Duelist's Standard Gauntlets' has T4 appearance but can't be used as alternative appearance, which is a shame!

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#7557]

**Comment by Luth-RoR** [comment]
There is a guide for a workaround on the forum (iirc by ryan); if an item has no alternate appearance available in the tooltip, it was the same on the mythic server. 
This can't be changed atm and is no bug.

**Comment by Torquemadra** [comment]
doesnt have t4 appearance anymore
