### ISSUE TITLE
Declare Anathema 180turn issue

### ISSUE THREAD

**Issue by Lemonpie1** [WarEmu/WarBugs#7559]
For some reason when you 180turn and use declare anathema while jumping as wh it kicks you in the direction you are facing, so it kicks you through the enemy instead of away from it. It should always kick you in the direction your back is facing. https://youtu.be/aMRL_X-sefc?t=1m52s first 3 minutes are full of assault vaults.

**Comment by Luth-RoR** [comment]
Declare anathema (and the WE counterpart) work differently here to avoid the enemy client abuse that was possible on the mythic server.
This is intended.
