### ISSUE TITLE
Enervating Vengering Resis too low

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#7562]
So I have these to rings and they are bascially the same. Only the resis differ slightly. Since they have the same level and all I assume this is a bug.

![cimbo_000](https://cloud.githubusercontent.com/assets/16117730/18141929/a953eee2-6fbb-11e6-8832-0a43391544d1.jpg)

**Comment by Luth-RoR** [comment]
This was reported earlier and is known by the devs; there are lots of these cases for jewelry. Atm it's the same as on the mythic server, so no bug. I'm sure it will be changed in the future, but only when no more important tasks need to be done.
