### ISSUE TITLE
Bane shield

### ISSUE THREAD

**Issue by DUSKANGEL** [WarEmu/WarBugs#7564]
![finalpride_001](https://cloud.githubusercontent.com/assets/12202629/18144214/27754f8e-6fce-11e6-8132-b40c63dd02ec.jpg)
And this is screenshot only for 2 seconds... was killed in 3 seconds on my tank  from bane shield just by using raze.... This skill never should work in that way.

**Comment by Yellowpillow** [comment]
how exactly this skill should work in your opinion?

**Comment by DUSKANGEL** [comment]
well combat log scroll up to fast and i was not able to make other screen shots but for sure they shouldn't stuck

**Comment by Torquemadra** [comment]
#7545
