### ISSUE TITLE
White lion "Fetch" skill bug 3

### ISSUE THREAD

**Issue by DUSKANGEL** [WarEmu/WarBugs#7567]
"Fetch" skill light up and become usable even when character dont have line of sight with target, (still not able to pul the target, works good here). As a result: skill have cooldown, target is not pulled.

**Comment by Kaelang** [comment]
Appreciate this is a dated report - however this does not provide enough information to identify the issue and/or replicate the problem. Please re-open this issue if this persists in the latest version of RoR.
