### ISSUE TITLE
Summoned Squig - taunt dosen't seem to work

### ISSUE THREAD

**Issue by Morneblade** [WarEmu/WarBugs#7568]
The Summoned Squig, which is supposed to be the "tank" doesn't tank well. He takes more damage than the Horned Squid and holds aggro worse than the Horned Squig, where the opposite should be the case.

**Comment by Luth-RoR** [comment]
Evidence please.

**Comment by Morneblade** [comment]
What form of evidence would you prefer?

**Comment by Luth-RoR** [comment]
Something that confirms that the pet _doesn't tank well_, maybe a combatlog and/or evidence that it wasn't like this on the original server; the tooltip of the horned squig also says that it is _strong against physical attacks but weak against magic_ (which probably means it has high armor and low resistances).

**Comment by Morneblade** [comment]
The major issue is that the Summomed Squig does not hold aggro. It doesn't
seem any tougher than the Horned Squig, but the main job is to hold aggro.
The Horned Squig at this point is as tough, does more damage and hold aggro
better. I have had the Horned Squig grab aggro away from me after I have
gotten aggro, while the Summoned Squig does not.

The important tool tip information: Summon Squig - This pet receives a
bonus to Toughness and Wounds equal to items. This squig generates much
more hatred in enemy monsters than normal.

Tool tip information on Squig Squeal - Pet squeals, interrupting all
building abilities and forcing monsters to attack pet.

I'm positive Squig Squeal is not working as intended. It seems that the
Summoned Squig should also create more hated according to it's tooltip even
without the Squig Squeal. Right now, it doesn't.

After going over combat logs, effects of specials do not show up. I can see
that the attack fires, but only damage shows up in logs ( there is not
"taunted" message, for instance).

I don't have a moving making prog on my machine to make videos and that is
the only real way I can think to show anything at this point.

**Comment by Morneblade** [comment]
It's been about 2 weeks since I last posted and I have not heard anything.
I would like to give you something as evidence, but outside of a movie I'm
not sure what I can provide.

**Comment by Luth-RoR** [comment]
The problem is that this report is lacking data (how it was on the mythic server) and is more oppinion based. It would be good if someone else could post some facts about the SH pets on the mythic server.

**Comment by Morneblade** [comment]
Well, according to the tooltip, the Summoned Squig is the "taunt" squig.
And as someone that played a SH till RR60+, I have some experience with
them and how they work. However, I know you can't just take my word for it.
I suppose I could try and find something on it, an old webpage or
something. Would that be helpful?

**Comment by Morneblade** [comment]
I found a couple things. One is a tooltip and one is patch notes from beta.
I know.......beta..... But it's a start.

http://warhammeronline.wikia.com/wiki/Summon_Squig

http://saltworld.net/forums/topic/7736-war-is-coming-the-warhammer-online-age-of-reckoning-thread/page-2



Beta Build Notes: 09/05/2008
Beta 4.1 Preview Weekend Plus

Squig Herder
*Squig Armor: The Squig Herder can no longer use a mount while inside Squig
Armor. This ability is now Level 9. Also, it is now a toggle that increases
toughness, strength and wounds
*New abilities have been added for use inside of squig armor: 'Ard Noggin,
Big Claw, BOOM!, Indigestion, Big Bouncin!
*All Squigs have had their stats adjusted. They should now deal slightly
more damage and be slightly tougher.
*The basic Squig now has two new abilities: Squig Squeal and Death From
Above.
*Summon Horned Squig: This ability now increases the range of the Squig
Herder's ranged abilities.
*Cut Ya! Is now a rank 8 ability.
*Don't Hit Me! Is now a rank: 30 ability.
*Bounce is now a rank 30 ability.
*Shout: This ability has been removed.
*Lemme Out! This ability has been removed.
*Bite This ability has been removed.
*Spin 'n Slash: This ability has been removed.
*Foot Stab: This ability has been removed.
*Head Butt: This ability now deals a medium knockback as well as damage.
*Summon Gas Squig: This ability now increases the Squig Herder's Armor.
*Bad Gas: This ability now deals PBAE damage and heals the Squig Herder if
he is inside the radius and inside Squig Armor.
*Goop Shootin': This ability's damage has been increased.
*Poisoned Spine: This is a new ability which has been added to the Spined
Squig.
*Spine Fling: This ability now deals channeled damage.
*Stabbity: This ability's damage has been increased
*Chomp: This ability has been renamed to Git Em! and its effect has been
changed so that both the Squig Herder and Squig deal damage.
*Cut Ya!: The damage of this ability has increased
*Drop That!!: Will now disarm and deal damage to the target. Build has
inceased, cost has increased, reuse has increased.
*Don't Hit Me!: The cost of this ability has decreased, and its damage has
increased.
*Bad Gas!: This is a new ability that heals the squig herder and pet, as
well as increasing cool downs of enemies within the radius.
*Finish Em Off: The damage of this ability has been decreased if the target
is greater than or equal to 20% health. Its damage has been increased
significantly, if the target is below 20% health.
*All pet abilities will now queue up on the pet for up to 5 seconds each,
until they successfully fire.
*Sticky Squigz: Duration increased to 10 seconds.
**Squig Squeal: Is now a single target taunt.*
*Ard Noggin: Now has a 5-second cooldown.
Buff <http://warhammeronline.wikia.com/wiki/Buff>
Learned on Rank 1
Core Ability
Usable by Squig Herder <http://warhammeronline.wikia.com/wiki/Squig_Herder>
55 Action Points <http://warhammeronline.wikia.com/wiki/Action_Point>
No
2s
30s
*You may only have 1 active pet*
*Description*
Summons a basic squig pet which you can order around. This pet is very
tough, and can take quite a beating.

*This squig generates much more hatred in enemy monsters than normal.*
*Cooldown will begin when you lose control of your pet for any reason.*

**Comment by Morneblade** [comment]
Some other information I found.


Warhammer 4.1 Patch Notes
<http://www.wowhammer.net/2008/09/warhammer-41-patch-notes/>

*Squig Herder*
- Squig Armor: The Squig Herder can no longer use a mount while inside
Squig Armor. This ability is now Level 9. Also, it is now a toggle that
increases toughness, strength and wounds
- New abilities have been added for use inside of squig armor: ‘Ard Noggin,
Big Claw, BOOM!, Indigestion, Big Bouncin!
- All Squigs have had their stats adjusted. They should now deal slightly
more damage and be slightly tougher.
- *The basic Squig now has two new abilities: Squig Squeal and Death From
Above.*
- Summon Horned Squig: This ability now increases the range of the Squig
Herder’s ranged abilities.
-
-
http://www.wowhammer.net/2008/09/warhammer-41-patch-notes/

**Comment by Morneblade** [comment]
http://warhammeronline.wikia.com/wiki/Squig_Herder_Abilities

Summon Squig <http://warhammeronline.wikia.com/wiki/Summon_Squig> Action
<http://warhammeronline.wikia.com/wiki/Action> Buff
<http://warhammeronline.wikia.com/wiki/Buff> No Range Core Ability *Summons
a basic squig pet which you can order around. This pet is very tough, and
can take quite a beating. This squig generates much more hatred in enemy
monsters than normal.* *Cooldown will begin when you lose control of your
pet for any reason.*

**Comment by Morneblade** [comment]
Squig Squeal


Ability for basic squig. Taunts the enemy forcing them to focus on the
squig. The target will take 30% more dmg from your pets attacks for 10 secs.

http://www.mmorpg.com/gamelist.cfm/game/239/feature/2312/page/2/Squig-Herder-Guide.html

**Comment by Morneblade** [comment]
I know I've been a little redundant, there isn't that much out there
anymore. Your question seemed to be that I need to establish that the
Summoned Squig did in fact have a taunt, is tough, and generates more
hatred than other squigs. I hope I have demonstrated enough evidence in
that regard. The next question is: is it working as intended? Since it
seems there is no taunt from the Squig Squeal and the Summoned Squig does
not appear to create any more hate than other squigs I would say it does
not.

I've attached some screenshots of the current build in RoR of the Squig,
Squig Squeal ability and a combat log. No taunt ever fires.

**Comment by Luth-RoR** [comment]
I think there is a misunderstanding:
I know that the squig should have a working taunt, like the lion pet; my problem is that there is no evidence that the taunt is not working (apologies if i overlooked something).
Taunt is not shown in the combat log, because it doesn't do damage or heals.

The taunt should work like this (the same with every taunt):
The caster gets aggro instantly, but there is no guarantee that he will keep it for a longer period; if there is someone doing lots of damage right after the taunt, the aggro will be lost again.
Furthermore the aggro mechanic is not yet 100% completed afaik (tank aggro tactics not working atm iirc).

_Maybe_ the pet(s) with a taunt ability should get a passive 50%-100% buff to thread generation (like the tank tactic), to better server their purpose. But that's a topic more for a forum discussion imo.

**Comment by Morneblade** [comment]
Ok. I started with the assumption that you knew that Summoned Squig had a
taunt, but the questions you asked made me think you did not. So yes, there
was a definate misunderstanding!

I went and tested some different types of pulls. I usually start off with
Plink and the Squig runs in. The Squig Squeal never fires like this. I did
find that I send the squig in first it will fire, but it doesn't do
anything. Always comes right for me, and never regains aggro even if I just
go to auto attack. You see Death From Above fire, and go through it's
cooldown. I'm not sure if the Summoned Squig as it is now has added hate
associated with it as it did on Live (a related topic, but one I don't have
any information on). I also have a White lion, and it's taunt is what I
expect. It's hard for me to get aggro, and it will pull aggro off me when
it taunts again. I've attached a movie to show different senarios and what
happens in each. At no time does the Squig ever get aggro, even if the
ability appears to go off. Sorry for the files size, I actually just
downloaded the app just for you to do this, and didn't play with settings,
sorry! :)​
 2016_09_17_11_31_11-ses.mp4
<https://drive.google.com/file/d/0B77_IpZ2KHFJaTlVYnBiRHdwUU0/view?usp=drive_web>
​

**Comment by Luth-RoR** [comment]
Ok, thanks.
That the taunt is rarely used is afaik also a problem with the pet coding atm. The packets for pet commands between server and client are not completely decoded, so that atm we have some workaround; e.g. On the mythic server it was possible to priorize pet abilities via the client API (addons).

**Comment by Morneblade** [comment]
Cool, glad I was able to get the information you were looking for. I'm not
expecting a quick fix to this, as it's:
A. more of a PvE issue and that is not the main focus
B. reverse engineering a game is fucking hard.
C. this isn't your full time job.

But I am glad I was able to make you aware that it's not working correctly.


- Jon

**Comment by Luth-RoR** [comment]
Yes, the developer who does combat&career fixes does the major RvR overhaul atm, so it could take some time.

**Comment by Morneblade** [comment]
And that is the priority. I had a pretty long conversation with GM Reyes
(sp) about it and while he didn't tell me what was coming, he said it would
hopefully fix several issues we both seemed to think were pretty bad. And
as RvR is my priority as well, I'd rather see that. But as the SH is my
favorite class, I do want to see it work as intended. Especially since my
wife kinda fell in love with them after watching me play mine, she's
playing one now. But as she doesnt really RvR (I'm still working on her
though!) it's been pretty hard for her with a pet that doesn't taunt and I
don't want her to give up on Noshines! ;)
