### ISSUE TITLE
Chosen: Multiple Auras possible

### ISSUE THREAD

**Issue by dbddhkpuka** [WarEmu/WarBugs#7570]
I did not find a proper issue for this, so I created a new one.
All Chosen auras I have atm (lvl 8) can be activated simultaneously and increase my str, tou and resistances in the character window.
Activating one aura while another is active does not deactivate the other one, but I am able to deactivate it when using the action bar button once more.

**Comment by ozarmidrashim** [comment]
Not a bug.
