### ISSUE TITLE
RvR quest trolls lands t2 order

### ISSUE THREAD

**Issue by Inlsl** [WarEmu/WarBugs#7571]
RvR quest (25kills) performed only once. In athers zones (t1. / t3-t4) 
is repeated

**Comment by Luth-RoR** [comment]
Name of the quest please.

**Comment by Inlsl** [comment]
I can not say , because it rapidly picked up and also performed it . And again I could not take . I can say , if i will lvlup twink to this lvl.

**Comment by Inlsl** [comment]
one of this npc must have this quest
http://s011.radikal.ru/i316/1609/96/0db27f3c5c1bt.jpg

**Comment by Luth-RoR** [comment]
Ok, maybe a DB dev can confirm it.
