### ISSUE TITLE
Enervating Int jewelry

### ISSUE THREAD

**Issue by cimator** [WarEmu/WarBugs#7574]
Item below shouldn't be Bound to Player, and it's item level is 39 not 37
![leakypants_011](https://cloud.githubusercontent.com/assets/17130290/18174931/1967febe-7078-11e6-8027-6f54147d5729.jpg)
other enervating int jewels ex;
![leakypants_012](https://cloud.githubusercontent.com/assets/17130290/18174999/56d634f0-7078-11e6-91d5-eba3f62b9399.jpg)

**Comment by Luth-RoR** [comment]
Why shouldn't it be bound to player? Didn't you equip it?

**Comment by cimator** [comment]
I didnt equip no, and since all the other green 37 lvl jewels are the same except this one, I thought it was a bug. Dunno if it's intented tho

**Comment by Luth-RoR** [comment]
Needs confirmation from DB-dev.
