### ISSUE TITLE
Character Became Merchant

### ISSUE THREAD

**Issue by SteelParliament** [WarEmu/WarBugs#7575]
I was playing on my Black Orc and went into the nearby warcamp in Nordland. Upon entering the camp my character turned into "Agnar Flreshspoil" the craft supply merchant, I was able to move around with ut but I was not able to click myself to purchase goods. My game crashed before I could see if other players could purchase goods.

I recorded a video of the bug - https://www.youtube.com/watch?v=G87lBKvxt8g

**Comment by Luth-RoR** [comment]
Maybe related to https://github.com/WarEmu/WarBugs/issues/7291 https://github.com/WarEmu/WarBugs/issues/7292

**Comment by Torquemadra** [comment]
linked, no need to keep reports of the same thing open
