### ISSUE TITLE
magma + horse = Speed +50%

### ISSUE THREAD

**Issue by romcoll85** [WarEmu/WarBugs#7576]
hello, i have find bug in the magma area karak Karag. in the castle area. In fact you have to climb a horse, then go in the magma with the horse. Once falls from horse, your displacement speed is under constant development by 50%. And it remains all the time until anulation. very practical in pvp.

![hectorvan 03](https://cloud.githubusercontent.com/assets/21694730/18184454/7cb28cc0-7099-11e6-9f71-a56ebf72f55b.jpg)
![hectorvan01](https://cloud.githubusercontent.com/assets/21694730/18184455/7cb5eafa-7099-11e6-8c55-31474f3e1ab5.jpg)
![hectorvan02](https://cloud.githubusercontent.com/assets/21694730/18184456/7cb6789e-7099-11e6-85f0-f26ef0eeae53.jpg)

**Comment by Soulwhisper** [comment]
#798
