### ISSUE TITLE
Bug with sell item

### ISSUE THREAD

**Issue by grim5551** [WarEmu/WarBugs#7577]
Sold by chance two-handed sword , I bought , and it disappeared talismans

**Comment by Ryanfawkez** [comment]
Mascots? Do you perhaps mean talismans put into the item?

**Comment by grim5551** [comment]
yes

**Comment by Elvenalthur** [comment]
Can confirm: Sold a talisman slotted item to a vendor and bought back, the talisman and stats from the talisman were removed.
![aluthor_000](https://cloud.githubusercontent.com/assets/7492543/18218219/2275d828-7159-11e6-8487-8e6643b74c0b.jpg)
![aluthor_001](https://cloud.githubusercontent.com/assets/7492543/18218220/227ab4e2-7159-11e6-8acf-3bb0364d7ac8.jpg)

**Comment by Kaelang** [comment]
I've just tested this - this is now working as intended. The talisman is no longer lost upon 'Buy Back'.
