### ISSUE TITLE
T1 Dwarf Inf Reward item 'Lookout Greaves' has tali slot but not 'Ironmane Greaves'

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#7578]

**Comment by Ryanfawkez** [comment]
Put a talisman slot on all the Lookout and Ironmane items, as they are all supposed to have one.

**Comment by Soulwhisper** [comment]
Is this for Kotbs?

**Comment by Ryanfawkez** [comment]
@soulwhisper - both Blackguard and KotBS boots have the name 'Greaves' - it matters little for DB work, as all the Lookout and Ironmane items have a talisman slot added now.

**Comment by avenflar** [comment]
@Ryanfawkez If I may add something, I very strongly believe most of the 'defense' oriented RvR Inf Rewards items (tough/wounds oriented items) are missing their talis slot.

**Comment by Ryanfawkez** [comment]
Get me a list of prefixes and suffixes by tier and racial pairing, and I'll check them all for a talisman slot.
