### ISSUE TITLE
I think its a bug but i dont know

### ISSUE THREAD

**Issue by elfwolf** [WarEmu/WarBugs#7580]
My archmage, lvl 8 Larinoldos, originally in Troll Country now I'm not so sure, is unusable. When I'm on the character select screen, he looks fine. But when I log on, everything is grey, I have no armor, weapons, stats, abilities, and my backpack (including book of binding and horse) is empty. I'm also dead (but I can walk around). I tried queueing for a scenario, killing myself by jumping off a high cliff, /reloadui, /stuck x2(got me out of grey "zone 0" so I could see all this mentioned above), .unlock, /exit, /leave, /quit nothing worked. I couldn't close the game because you cant be dead when you try and log out/exit the game.
Please help!
Thanks!,
Elfwolf Lvl 23 Shadow Warrior

**Comment by Ryanfawkez** [comment]
Seems like an invalid death state. You can still leave your game by crashing the client, have you attempted this?

**Comment by elfwolf** [comment]
idk how to reply to you but no, what is crashing the client?

**Comment by Luth-RoR** [comment]
Go to your windows dektop and kill the game manually. Though as this is a known bug which could still happen from time to time, this is more a case for the support forum (i guess there are already some threads about this open).
