### ISSUE TITLE
Bug or know how?

### ISSUE THREAD

**Issue by Inlsl** [WarEmu/WarBugs#7581]
t2 marshes of madness destro keep
oil cannot do dmg in  this place, but i can attack door
http://i042.radikal.ru/1609/58/3bed6531cdd6.jpg

**Comment by Ryanfawkez** [comment]
Line of sight issue.

**Comment by Inlsl** [comment]
others do not have this . It turns out somehow unfair

**Comment by Luth-RoR** [comment]
Needs confirmation if it can be fixed at all or needs client modification.

**Comment by Torquemadra** [comment]
line of sigh code needed.

**Comment by Luth-RoR** [comment]
Closed until the client can be modified.
