### ISSUE TITLE
Heroes of lair doesnt drop items.

### ISSUE THREAD

**Issue by Rhungk** [WarEmu/WarBugs#7583]
I have been farming Metoh ( lair troll country, lvl 40) and Silveroak (lair Norsca, lvl 40) and in many situations didnt drop the chest or the helmet as its supposed to do, just cash and sometimes a grey item. At first i thought i had bad luck but i check in the wiki (http://warhammeronline.wikia.com/wiki/Lair) that always drop 1-3 item per kill, so i guess there is some issue with the drop.
 This happened to me with a choppa, i saw the drops of chosen, marauder, shamman, blackguard, zealot, disciple of khaine, sorcerer and wich elf, i cant say for sure for other classes.

**Comment by Torquemadra** [comment]
t4 zone lair bosses drop nothing at the moment as they do not have abilities associated to them and can drop items that are far better than the effort it takes to obtain them. Abilities will come, then items will drop.

**Comment by Nikbushale** [comment]
![itsboshytime_004](https://cloud.githubusercontent.com/assets/21958820/18212952/9733f3d0-714e-11e6-9679-7b5416d8b94f.jpg)
A proove here.

**Comment by Ryanfawkez** [comment]
He only drops helmets. Will check if the Metoh's Skully is included in the drop tables.

**Comment by Torquemadra** [comment]
it is in the drop tables.

**Comment by Rhungk** [comment]
I dont know if i wasnt clear enough, but i will repeat it: 1-3 items per kill, as un can see at the screenshoot, 0 items dropped, just 1 silver and 28 brass coins. Always have to drop an item.

**Comment by Luth-RoR** [comment]
Are you sure that you had "loot rolls" activated in the chat log settings and there was no one else outside of the group who may have grabbed the shinies?

**Comment by Rhungk** [comment]
Yep, just was me and the healer, and this happened to me 3 times, always when i can loot (being a choppa). In the 3 times with different ppl and classes (zelaot, shammy).

**Comment by Rhungk** [comment]
More prooves here that when i can loot (being a choppa) doesnt drop the helmet, just cash: http://imgur.com/S9pVBIi http://imgur.com/7ontbIb http://imgur.com/Gx0LmBN

**Comment by Luth-RoR** [comment]
Tested on the dev server: 3 times in a row he dropped 2x the choppa helm. 
![luthgit_002_crop](https://cloud.githubusercontent.com/assets/8567481/18251669/a487223a-738a-11e6-9a2e-7c3dc449d126.jpg)
![luthgit_002_crop0](https://cloud.githubusercontent.com/assets/8567481/18251674/a96eaa16-738a-11e6-9151-d80decafecc4.jpg)

**Comment by Rhungk** [comment]
But then why i cant get it? Cause no loot as you can look at the screenshoot, maybe all the time the loot get bugged? Cause this has happened to me 3 times or more.

**Comment by Luth-RoR** [comment]
Then it must be something else; i just wanted to make sure that it does indeed drop for choppas.

**Comment by Rhungk** [comment]
ok ill try to do it again as soon as i can, and if it happends again ill take screenshoot, but if its not a dev issue, im not sure whats the problem.

**Comment by Luth-RoR** [comment]
Did any pets engage in the boss fights?

**Comment by Rhungk** [comment]
Nop, just me and the healer, a few times a tank, but that shouldnt influence in the drop, not in the way dropping nothing.

**Comment by Rhungk** [comment]
Recently killed and dropped 2 Metoh´s Skully. Mystery resolved.

**Comment by Luth-RoR** [comment]
Ok, nice.
