### ISSUE TITLE
targeting stealthed char

### ISSUE THREAD

**Issue by JeekElemental** [WarEmu/WarBugs#7585]
In Reik keep, was targeting a WE on the wall with my BW.
WE ran up tower, out of LOS, and stealthed.
I was spamming dots waiting for unstealth, but they seemed to hit stealthed char (I could see dmg numbers).
WE ran back in tower and was now both stealthed and out of LOS, but could still hit with spells.

**Comment by Luth-RoR** [comment]
I don't understand what's the problem here. 
You applied dots to a WE and then she got in stealth?

**Comment by JeekElemental** [comment]
No I was able to hit a stealthed WE with spells, and also LOS seemed to be ignored.

**Comment by Luth-RoR** [comment]
So you still had her in your target during the stealth?

**Comment by JeekElemental** [comment]
Target reticle was cleared when WE stealthed, but I did not change target or clear it manually (ESC).

**Comment by Luth-RoR** [comment]
And you are 100% sure that you could cast on the WE while you didn't have her in the target?

**Comment by JeekElemental** [comment]
Yes
