### ISSUE TITLE
Slayer bug damage 

### ISSUE THREAD

**Issue by Orodisi** [WarEmu/WarBugs#7587]
Slayer core ability and ability "Path of The Giantslayer" with two-handed weapons in berserk deal less damage than in fury.

**Comment by ozarmidrashim** [comment]
No proof!

**Comment by Luth-RoR** [comment]
>in berserk deal less damage than in fury.

I just re-read it and i think there is a comprehension issue:
When you use an exhaustive blow, it ofc does more damage in fury (75) than in berserk (50). It's stated in the tooltips of those abilities.
I furthermore did a quick test with "deathblow" and it works like i described above (and is intended).
