### ISSUE TITLE
Unusual Sun Dragon's in Saphery @ PQ: White Tower of Hoeth

### ISSUE THREAD

**Issue by toxie** [WarEmu/WarBugs#7590]
Killing the "Unusual Sun Dragon" mobs near this PQ counts as killing a "Great Eagle" and not a Dragon in the Tomb of Knowledge.

**Comment by roadkillrobin** [comment]
Coz its a illusion. The Unusual Dragon name should be a hint enough.

**Comment by toxie** [comment]
oh silly me, totally obvious /s
