### ISSUE TITLE
high level in low tier

### ISSUE THREAD

**Issue by randommpa** [WarEmu/WarBugs#7591]
![damagemate_000](https://cloud.githubusercontent.com/assets/21138966/18226676/db0075f6-7217-11e6-9e26-7a53e4492ca7.jpg)
![damagemate_006](https://cloud.githubusercontent.com/assets/21138966/18226681/e8931926-7217-11e6-8484-9ece176b10ed.jpg)
![damagemate_008](https://cloud.githubusercontent.com/assets/21138966/18226683/ed0cb570-7217-11e6-8b0b-850580bde82f.jpg)
![damagemate_011](https://cloud.githubusercontent.com/assets/21138966/18226684/f269867e-7217-11e6-866a-b3c5bffebd47.jpg)

**Comment by Luth-RoR** [comment]
Debolster mechanic.
