### ISSUE TITLE
Guilds

### ISSUE THREAD

**Issue by runebbb** [WarEmu/WarBugs#7592]
so i noticed after the patch yesturday 02.09.2016 the character delete patch that this happend 
![sirren_001](https://cloud.githubusercontent.com/assets/20157418/18227031/1c325cd8-7218-11e6-8959-46fd42c67ff4.jpg)
 for those this dosent make sense to this guild was made after the ddos attacks and all members have been recruited after and we have around 80 members but to me it says just 1/1 and thats me it also happends if i log on other characters i got in the guild

**Comment by runebbb** [comment]
also other guild members got the same problem

**Comment by ozarmidrashim** [comment]
https://github.com/WarEmu/WarBugs/issues/1438

Search
