### ISSUE TITLE
Blessing of Chaos not working properly( Zealot's Tactic)

### ISSUE THREAD

**Issue by verg86** [WarEmu/WarBugs#7594]
Blessing of Chaos not working with any type of HoT's

**Comment by Yellowpillow** [comment]
Info: Blessing of Chaos, core tactic, description: Critical heals will Bless your target for 10 seconds, increasing the power of any heals used on them by 25%.

**Comment by ozarmidrashim** [comment]
https://github.com/WarEmu/WarBugs/issues/2056

No.
