### ISSUE TITLE
Tier 3 keeps bugged

### ISSUE THREAD

**Issue by Kaberu** [WarEmu/WarBugs#7595]
I would seem that in Tier 3 once you cap 3 or 4 of the BO's the enemy keep can not be attacked.  Zone is unlocked, and keeps are set to attack but it would appear that they are bugged out.  Nobody can dmg to doors in any way.  Stoneclaw Castle: Destroy the Outer Door.    Target not attackable, is the what you get when you try.  NOTE:  This is empire only.  Other pairings work just fine.

**Comment by zak68** [comment]
happened in T4 TM too, inner stopped to be attackable at 2% with destro owning all 4 bos; a GM fixed the door, keep was taken but zone did not locked. karak palik bo was in "generating" state with npc already spawned.
