### ISSUE TITLE
Clearing the way Quest Bugged

### ISSUE THREAD

**Issue by Sprak2686** [WarEmu/WarBugs#7596]
Unable to get a few things from this quest... I'm assuming its bugged or am very lost.

Located in Ellyrion.
Rank 18-19 quest

Ellyrion orders read - unable to attain/find orders. I've clicked on any and everything within the red area.
Uthorin Barbspear - will not give me any recognition for kills towards the completion of this quest.

**Comment by Ryanfawkez** [comment]
Ellyrian Orders should be added upon quest acceptance, cannot be fixed yet.
