### ISSUE TITLE
Dual Wielding Bonus to Parry not showing up. (assuming the same for using a 2 hander)

### ISSUE THREAD

**Issue by Esperflame** [WarEmu/WarBugs#7599]
I'm pretty sure on live there was a bonus to parry that was gained when you equipped 2 weapons. I think it was 5% to parry but I can't remember. There was also a bonus when using a two handed weapon to something. (possibly armor penetration).

**Comment by Luth-RoR** [comment]
Weapon bonuses work fine; the character window does not yet. Please only confirmed bugs on the bugtracker (or at least reasonable suspicion), but no guessing.
It's 10% parry for dualwield and 2h weapons had/have 10% block strikethrough.
