### ISSUE TITLE
Doesn't animated snare and other effects for some classes.Pt.2

### ISSUE THREAD

**Issue by murmelon** [WarEmu/WarBugs#760]
Doesn't animated snare for WP/DoK/Engi/WH/WE/Marauder/Choppa/SH/Sorc
SW & WL snare-effect doesn't animated, is animated only infliction of damage.
maybe it need to fix. Make animation like SM snare debuff.
Magus - doesn't animated "Glean Magic".Correctly On pic.
BG - doesn't animated armor debuff.
IB  - doesn't animated armor debuff.
SH - doesn't animated armor debuff.
BO - doesn't animated armor debuff.
BW - doesn't animated disorient debuff (pyroclastic surge)
WP -doesn't animated "Repent" (detaunt)
Incorrectly displays:
IB - inspiring attack (both IB+OF). Correctly displays on pic.
Shadow warrior - "Acid Arrow", now it is animated  like gas squig's aoe attack. Correctly on pic.
![sw](https://cloud.githubusercontent.com/assets/12655727/8026099/b43ae902-0d72-11e5-9ebd-aba9194dd565.jpg)
Engineer - acid bomb (1step - animation of area (green cloud), 2step - animation of debuff. Correctly displays on pic.
Swormaster - doesn't dispalys effect "Dazzling strike".On pic.
Nature's blade - 1step animations of area.( pic1), 2 step animation of debuff (pic2). 
![eng1](https://cloud.githubusercontent.com/assets/12655727/7958806/5f797660-09fb-11e5-8099-41b2df4e1b65.jpg)
White Lion - incorecctly displays "Submission". Inversion on pic.
![night_000](https://cloud.githubusercontent.com/assets/12655727/7958798/4dad7fc6-09fb-11e5-9596-ebb2395e2f4a.jpg)

**Comment by gittoaster** [comment]
ALso KD animations..
