### ISSUE TITLE
Slayer damage bug testing (furios-berserk) combat log screenshots included

### ISSUE THREAD

**Issue by DUSKANGEL** [WarEmu/WarBugs#7600]
Hello few days ago i saw report about slayer damage bug. I did Test of mechanics of my slayer and put 3 screenshots. (time stamp enabled). 
![ashamedpride_000](https://cloud.githubusercontent.com/assets/12202629/18229822/1b5f993e-728f-11e6-8707-745b80e310d6.jpg)
![ashamedpride_001](https://cloud.githubusercontent.com/assets/12202629/18229828/45b2fdd4-728f-11e6-9774-80561f547920.jpg)
![ashamedpride_002](https://cloud.githubusercontent.com/assets/12202629/18229829/4e04ed76-728f-11e6-84af-552c842c8a3b.jpg)
And now i have question why the damage in Berserk is less then in Furios? Damage should be same. And this happen with all skills that exhaust rage. Please fix it cos right now mechanics of slayer is nearly uselless.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/7587
Read the tooltips of exhaustive blows.
