### ISSUE TITLE
Dwarf Ch. 9 - NPC Droki Redbeard (Rally Master) underground

### ISSUE THREAD

**Issue by Shardreg** [WarEmu/WarBugs#7601]
Hello everyone,

as per the title, the NPC Rally Master Droki Redbeard is underground in Dwarf Chapter 9.

Attempted fixes:
- Reloading interface
- Relogging
- Restarting game
- Waiting for server restart

See screenshot here: http://imgur.com/a/Z7D31

**Comment by saupreusse** [comment]
I believe this is related to the strange rally master bug. they somehow always get random emotes or sink into the ground :/ dunno why that is.

**Comment by Ryanfawkez** [comment]
@saupreusse - my best bet would be messed up values in the Rally Master packet structure. As their titles and icons had to be fixed through editing these values, they could've caused the random emote cycles.

**Comment by saupreusse** [comment]
is there any way we could fix this?

**Comment by Lheana** [comment]
Seems fine now.
