### ISSUE TITLE
Chaos Ch. 1 - Unable to turn in quests

### ISSUE THREAD

**Issue by Shardreg** [WarEmu/WarBugs#7602]
Hello everyone,

quests in Chaos Chapter 1 claim that no rewards are selected when trying to turn them in, limiting/halting quest and story progression.

Attempted fixes:
- Reloading interface
- Relogging
- Restarting game
- Redoing the quests
- De-selecting and re-selecting quest rewards
- Selecting different quest rewards
- Waiting for server restart

See two example screenshots here: http://imgur.com/a/unMji

Note: All quests shown as completed in the quest tracker suffer the same issue.

**Comment by Shardreg** [comment]
Update.

Attempted fixes:
- Selecting all rewards simultaneously

This allows players to finish the quests and move on with the story/leveling process.

It seems like unintended behaviour, though.

**Comment by Ryanfawkez** [comment]
It is. I already addressed it in a ticket made one hour after the last patch, that caused this to happen.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/7552
