### ISSUE TITLE
NPC 'Empire Courier' at the wrong place in Beast of War PQ, Praag

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#7603]
![henmal_015](https://cloud.githubusercontent.com/assets/19625008/18231217/edd8dec0-72b2-11e6-85b0-3f954f830bfb.jpg)

The quest description says the guy should be in Ulthuan. No idea where though.

**Comment by Ryanfawkez** [comment]
This NPC has a double spawn; one is correctly placed in Dragonwake, whereas this one in Praag gives the same quest. I'll replace him with a courier that doesn't have a quest enabled.
