### ISSUE TITLE
9

### ISSUE THREAD

**Issue by lexashkola1986** [WarEmu/WarBugs#7609]
Incorrectly calculated the armor, and why the calculation is in thinyou protection, not armor

**Comment by Luth-RoR** [comment]
>is in thinyou protection
?

**Comment by lexashkola1986** [comment]
a set of talismans for the armor  annyhilator  has less armor on the character than cataluny in a small nabakov  mercenary

**Comment by Luth-RoR** [comment]
When you type _.getstats_ into the chat window, you will see your _real_ armor values. The character window doesn't show correct values sometimes; this is a well known problem.

**Comment by lexashkola1986** [comment]
Checked again. I wear the 475 armor,as armor becomes more only 90

**Comment by Luth-RoR** [comment]
Why did you change to report to "9"?
Anyway, closing this report as i don't know any tool to decipher it.
