### ISSUE TITLE
I can't respawn on my own

### ISSUE THREAD

**Issue by jotapem** [WarEmu/WarBugs#761]
When I die, even reloading the UI so the respawn button can reappear, I don't ever respawn on my own, only when ressed by healers.

I can quit the game and reenter, but it is really annoying to leave scenearios on the first death.

**Comment by ozarmidrashim** [comment]
Your class is?

**Comment by jotapem** [comment]
squig herder

**Comment by ozarmidrashim** [comment]
Known issue. This will occur if you die when your pet is out. Fixed in next.
