### ISSUE TITLE
Metoh doesnt loot the helmet for Choppa (?)

### ISSUE THREAD

**Issue by Rhungk** [WarEmu/WarBugs#7610]
As i said in the last issue i have been farming Metoh and sometimes doesnt drop anything. And when i can loot (being a choppa) i just get cash as a normal mob, here the screenshoots:
http://imgur.com/S9pVBIi http://imgur.com/7ontbIb  http://imgur.com/Gx0LmBN

**Comment by Ryanfawkez** [comment]
I'd rather you elaborate on the issue in the previous ticket, instead of opening a new one.
