### ISSUE TITLE
enfeebling strike witch elf too low

### ISSUE THREAD

**Issue by Krimalicious** [WarEmu/WarBugs#7611]
Im hiting for 0 dmg or 1 all my targets... 

![ss](https://cloud.githubusercontent.com/assets/8767404/18233229/854ba674-72e1-11e6-8035-500a7876d556.jpg)

**Comment by Luth-RoR** [comment]
Ability seems to have also other issues: https://github.com/WarEmu/WarBugs/issues/4742

**Comment by Krimalicious** [comment]
The ability now is able to crit and its procing witchbrew dmg...

**Comment by Nfkillz** [comment]
enfeebling strike do physical damage instead corporeal

**Comment by Krimalicious** [comment]
yes, after some patch, all of sudden its doing physical dmg.

**Comment by raptrr** [comment]
https://github.com/WarEmu/WarBugs/issues/8227
