### ISSUE TITLE
Archmage Devastator Hoeth Robe wrong appearance in-game

### ISSUE THREAD

**Issue by Qualor** [WarEmu/WarBugs#7613]
Hi,

The Archmage Devastator Hoeth Robe has a different appearance in-game from what is seen on the character select screen. As you can see from the middle screenshot no alternate appearance is being used.

Not sure which one is the right appearance, but the in-game one (middle picture) has some funky clipping errors in the neck area, so I hope it's the character select screen appearance.

![devastator hoeth robe archmage](https://cloud.githubusercontent.com/assets/17076607/18233332/85e91b22-72e4-11e6-9d12-4903d3e87a01.jpg)

Thanks in advance.

**Comment by Torquemadra** [comment]
item was unified as per https://www.returnofreckoning.com/forum/viewtopic.php?f=11&t=15770

not a bug
