### ISSUE TITLE
T3 lvl 32 flagged, not chickened

### ISSUE THREAD

**Issue by edavoc** [WarEmu/WarBugs#7616]
Today as I was in Highpass I was at 99% to 32 and turned in the kill quest blood in the snow. This leveled me to 32 but did not chicken me. Now I am able to walk around the highpass lake unchickened as a lvl 32.

![scroffus_001](https://cloud.githubusercontent.com/assets/16967436/18233541/dbe3bca8-72b7-11e6-96f1-e8c3093ded5c.jpg)

Here is a screenshot of me lvl 32 at the Ogrund's Tavern BO.

**Comment by Ryanfawkez** [comment]
You probably aren't affected by the chicken effect because you abide to all the rules listed in .ror debolster in-game, despite being level 32.
