### ISSUE TITLE
Greenskin quests chains "Breekin' Teef" and "Da Stick's da Fing" seems to be identical

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#7619]

**Comment by avenflar** [comment]
What do you need to be confirmed? I have finished them so I can't make screenshot :(

**Comment by Luth-RoR** [comment]
It's ok; needs just confirmation from DB devs how it should work.

**Comment by avenflar** [comment]
They're identical, but at one point, one send you to a different NPC than the other. Still the same quest, but different NPC with the matching text.

**Comment by Ryanfawkez** [comment]
Breakin' Teef quest disabled for now.

**Comment by Lheana** [comment]
It appears Breakin' Teef was replaced by the long version and epic quest Da Stick's da Fing by WAR devs, so this ticket seems fixed.
