### ISSUE TITLE
quest: Goradian the creator

### ISSUE THREAD

**Issue by wonka29223** [WarEmu/WarBugs#7623]
ran across this quest, questing in Altdorf. 
Requirements:
 Invalid creature, plz report to GM quest ID 41323,Objld=6470

**Comment by Luth-RoR** [comment]
The quest refers to the endboss in one of the altdorf sewer tunnels. Not implemented yet.

**Comment by Lheana** [comment]
Quest works as Altdorf Sewers are now accessible. I just set the quest markers for the whole quest chain.
