### ISSUE TITLE
Still dead

### ISSUE THREAD

**Issue by mellsok** [WarEmu/WarBugs#7625]
On the end of playing scenario (when the statistics window was open) somebody kills me. When I return into the my location I was dead. I pushed the button to alive and the timer starts (as usual) but when it stops nothing was happend. I still dead and there wasn't some button to alive. Relog helped but I figure that I shoud to tell about that.
![neophyte_001](https://cloud.githubusercontent.com/assets/17993171/18245512/4d53881c-736e-11e6-84e5-fbf2ce96c2cc.jpg)

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/7465
