### ISSUE TITLE
Battle fatigue duration

### ISSUE THREAD

**Issue by georgehabadasher** [WarEmu/WarBugs#7626]
The battle fatigue duration was 3 minutes for PvP deaths and 15 minutes for PvE deaths on live.  Currently it's 15 minutes for both.

Edit: I have gotten the 3 minute duration a few times.  Seems to be about a 3:1 ratio (15 minutes : 3 minutes).

**Comment by Luth-RoR** [comment]
I think this has something to do if you die in a RvR or PvE area; atm the area borders are sometimes not yet like they should be. But this is already known.
