### ISSUE TITLE
Coins appear to be duplicating in mail from Auction House

### ISSUE THREAD

**Issue by Razooly** [WarEmu/WarBugs#7630]
1. Multiple items in the auction house.
2. I had not logged into my character Breedan for several weeks.
3. All items from Auction House appeared to have sold and I had 10 mailings from the Auction House.
4. Started opening and taking attached coins.
5. The attached coins did not disappear.
6. Figured it was lag and went to several more taking the attached coins.
7. Was on a roll opening taking attached coins when I noticed I had taken coins from previous open mail.
8. Tried again with same mail and got coins again.
9. At this point I stopped and deleted the remain emails.
10. Logged on to another character and noticed the same behavior.
    Note: I was disconnected from the server soon after this.

**Comment by Luth-RoR** [comment]
After the relog, was the increased gold amount still in your inventory?

**Comment by Razooly** [comment]
Yes, I just restarted the game and logged onto Breedan.  He still has is 9 Gold, 2 gold which is from the duplication issue.

**Comment by Luth-RoR** [comment]
Ok, thanks.
