### ISSUE TITLE
[Item] Casque of Unterbaum

### ISSUE THREAD

**Issue by Halhammer** [WarEmu/WarBugs#7631]
been lookin for more helm appearances...

Emp Ch. 14 Elite Reward, has no skin

**Comment by Yellowpillow** [comment]
It have skin, but with positioning problem. Look in the stomach area.
![tranquillity_035](https://cloud.githubusercontent.com/assets/18102127/19034731/33336682-8976-11e6-84e7-560257680b93.jpg)
