### ISSUE TITLE
Battle Fatigue Debuff have wrong timer in RVR

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#7634]
it put 15 min on me after i died in RVR lake in Praag. In RVR it should be 3 min.
![arena_044_new1](https://cloud.githubusercontent.com/assets/18102127/18255251/d3843e96-73b8-11e6-9169-48f429257343.jpg)

**Comment by Soulwhisper** [comment]
I confirm that this is happening to me sometimes too.

**Comment by Luth-RoR** [comment]
It could be that this happens only when siege equipment is involved: https://github.com/WarEmu/WarBugs/issues/7688.
Maybe someone can confirm/deny.

**Comment by roadkillrobin** [comment]
I think its what causes the Warband UI bugs aswell. So getting this fixed would be very very nice.

**Comment by Yellowpillow** [comment]
Don't appear after last patch. It seems like redrawing RvR lake solved this problem as well.
