### ISSUE TITLE
MAIL/COD issue

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#7638]
Ok here is the bug.If you try to send a message/COD through mail to a person that at the same time is joining a scenario or travelling to another zone/area with Flight Master **(In other words being in loading screen)** the message never arrives and it falls in abyss.

**Comment by Yellowpillow** [comment]
This issue affects any mail, sended by usual or sended back to mailer.

**Comment by Luth-RoR** [comment]
From https://github.com/WarEmu/WarBugs/issues/9504
>I sent another player and armor tali with CoD, however i have not gotten the gold yet even after he picked the tali up from the mailbox.
I tried refreshing UI and relogging nothing still.
I msged the receiver and he said that he already picked up and the gold was subtracted from him. I did take a SS of our convo if that helps

**Comment by Natherul** [comment]
should be addressed with the next patch

**Comment by Natherul** [comment]
Should be fixed as of todays patch (14/07/2017)
