### ISSUE TITLE
T4 influence open RvR changed

### ISSUE THREAD

**Issue by VUBITA** [WarEmu/WarBugs#7639]
Hello,
I noticed today that he in my Main not have the abgehohlt ichmir time t4 influential cape and belt . Should eigendlich T4 elves belt Wraith s Bladbelt and Chaos Cloak Charon s Torment be. Unfortunately can not say exactly when I have collected the two but are 100 % false .
is possible , the right to get shut it again? Sincerely Lilisara

**Comment by Luth-RoR** [comment]
Bitte auf Deutsch oder google translate ohne Tipfehler, ich habe keine Ahnung was hier gemeint ist.

**Comment by VUBITA** [comment]
Ich habe vor zwei Tagen festgestehlt dass  Gürtel und Umhang vom Einfluss des Offenes RvR , Abschnitt 4 geändert wurden. Ausgesucht hatte  mir den Gürtel und Umhang für Heiler den Wraith`s  Bladebelt  der Elfen und den Umhang Charo´s Torment Cloak des Chaos.
Statdessen hatte ich die Nahkampf Einfulss an die ich mir nicht gehohlt hatte. Bittte um Änderrung auf die  
eigendlichen abgeholten Sachen.
Vielen Dank

**Comment by Luth-RoR** [comment]
Kann sein das die items evtl. geändert wurden, was ich leider hier und im teamchat/auf dem devserver nicht nachvollziehen kann.
Der Bugtracker ist allerdings nur für bugs, das hier ist mehr eine support Anfrage.
Ich weiß nicht ob in diesem Fall items geändert werden, bzw. was hier die Richtlinien sind. 
GM Druin spricht deutsch, Ley auch ein wenig.
