### ISSUE TITLE
Kick to Char Menu after SC 

### ISSUE THREAD

**Issue by Elratie** [WarEmu/WarBugs#764]
since the last patch i have the Problem that almost everytime after an SC end´s that i got kicked to the Char selection Menu and have to login again with the char. Most time it happens with the Kotbs, the other chars are not so frequent.

so i tested it yesterday with a guild mate: Auras and Guard on or off dont change anything but with the BW buff on it happens, is the BW buff off i´m after SC where i was before but have mostly the Combat bug and have to relogg

**Comment by ozarmidrashim** [comment]
Will check the logs, thanks.

**Comment by Reggaewaldo** [comment]
This should be solved by now. Please reopen if the issue appears again.
