### ISSUE TITLE
Tempest Riders Crusher

### ISSUE THREAD

**Issue by Mizrim** [WarEmu/WarBugs#7646]
Stats anomaly

item description is 1h hammer (lvl 9 purple) but has +20 str +20 wounds on it

**Comment by Luth-RoR** [comment]
Just to be clear:
Do you mean the item has too many stat points for a 1h weapon or do you mean it shouldn't have strength on it?

**Comment by Mizrim** [comment]
Too many points - 40 at rank 9!

Sent from my iPhone

On 6 Sep 2016, at 13:39, Luth <notifications@github.com<mailto:notifications@github.com>> wrote:


Just to be clear:
Do you mean the item has too many stat points for a 1h weapon or do you mean it shouldn't have strength on it?

**Comment by Luth-RoR** [comment]
Ok thx; i didn't play low level chars for a while. :smiley:

**Comment by Mizrim** [comment]
Np, that hammer as it stands is a twinks wet dream! :D

Sent from my iPhone

On 6 Sep 2016, at 19:06, Luth <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok thx; i didn't play low level chars for a while. 😃
