### ISSUE TITLE
Grovod Caverns boss types

### ISSUE THREAD

**Issue by bwdaWAR** [WarEmu/WarBugs#7648]
The Order skaven boss in the Grovod Caverns, Warlock Narwoul, is a rank 35 Champion, with the standard 2 minutes NPC respawn time.
The Destruction skaven boss, Plague Priest Vharnal, is still a rank 35 Hero with 30-40 mins respawn.

**Comment by saupreusse** [comment]
Fixed. They are now both lords and got these nice keep lord abilities.

**Comment by Luth-RoR** [comment]
>Fixed. They are now both lords and got these nice keep lord abilities.
edit: they also have 100ft range.
Jk- i have no idea how to change respawn timers

Trolling the bugtracker is a seriouz crime.
I think both bosses should be champs now; it's hard to find a full group for the lords nowadays.

**Comment by Torquemadra** [comment]
they should be champs, respawn is hardcoded

**Comment by Soulwhisper** [comment]
**Patched 13/09/2016**
