### ISSUE TITLE
Mastery point allocation being forgot

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#7652]

**Comment by zak68** [comment]
i'm certain to have trained "can't stop da chop" , then i lvled up, found 1 mastey point available ,trained "path of da wrecha" but now it seems that i lost 2 levels in "path of da'savage"
![orkodiesel_021](https://cloud.githubusercontent.com/assets/17765890/18281115/f135b0c0-745b-11e6-8916-6025c47853a1.jpg)

**Comment by Luth-RoR** [comment]
I just tested it on the dev server with GM commands and it works perfectly fine.

**Comment by zak68** [comment]
another hint: i reached lvl 27 renown, gone to ic to train but i saw 0 renown points available and thought "strange...".
now i'm in nordland wc and this missing point has shown up (26 allocated 1 availble)

**Comment by zak68** [comment]
i moer thing: i switched 1 piece of obliterator armor with a higher spec boots having me wearing only 1 piece of obliterator, wearing 2 pieces of obliterator gives you  "+1 bonus to path of da' savages"

**Comment by zak68** [comment]
now i've understand what happened. sorry for your time.
