### ISSUE TITLE
Quest 'Char Troll' 

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#7653]
The 'Feral Troll' mobs keep getting killed by the many 'Bloody Sun Mangla' and 'Bloody Sun Breaka' on the island, making the quest (and potential PQ) extremely hard to do

**Comment by wargrimnir** [comment]
Check quest rewards.
http://i.imgur.com/5xvxu20.png

Great Will Maskhelm - no stats, should be +19/+12 offensive stats (engi has 19Bal 12Str)
Oathbearer Mashelm - no stats, should be +30 Initiative

**Comment by Lheana** [comment]
Feral Trolls will no longer be in fight with orcs of the PQ.
Checked the items, the correct stats have been added previously.

**Comment by sioding** [comment]
Fixed with patch from 26.01.2017
