### ISSUE TITLE
Moonfang mobs incorrectly counted as Night Goblins

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#7654]

**Comment by Torquemadra** [comment]
and they should be why?

**Comment by avenflar** [comment]
Cause the other Moonfang gobbos are flagged as such.

 And because they're in front of Gunbad.

**Comment by Torquemadra** [comment]
and none of them look like night goblins or reside subterranean as night goblins which leads me to think the error is the other way around

**Comment by Torquemadra** [comment]
out of 21 moonfang mobs 2 were erroneously marked as night goblins, these have now been fixed.
