### ISSUE TITLE
Quest Book/tracker/map messing up

### ISSUE THREAD

**Issue by Sprak2686** [WarEmu/WarBugs#7662]
I'm having an issue that whenever I log out quests in my quest book/tracker/map disappear and go blank. 

The quest title is still there but otherwise will not show any information or show up on my map. 

This happens every single time I log. 

I have found that abandoning and retaking the quest "Fixes" the blank quest. This is a work around, not a solution.

Would appreciate some help! 

Thank you!

**Comment by Luth-RoR** [comment]
Do you have any _quest addons_ activated?

**Comment by Luth-RoR** [comment]
Nvm, seems to be a general problem atm.
