### ISSUE TITLE
Quest "Clearin' Da Way" 

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#7664]
Only 'Sandhowl Wolf' count when 'Umbral Spinner', 'Fulsome Spinner' and 'Rheumal Spinner' should count too

**Comment by Ryanfawkez** [comment]
Multi-mob kill objectives aren't implemented yet.

**Comment by Ryanfawkez** [comment]
Added the four following objectives to the quest requirements:
Kill 2 Sandhowl Wolves
Kill 2 Umbral Spinners
Kill 2 Fulsome Spinners
Kill 2 Rheumal Spinners
