### ISSUE TITLE
Slagrot's Claymore bug

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#7666]
Slagrot's Claymore is two-handed sword 30 lvl, but here's the deal: you can take it in one hand.
Also it have shield appearance and when equipped in right hand looks like shield in left hand. While chosen equipped with normal shield, both of them merge and looks like 2 shields at the same time.
I think stats a little bit too high for one-handed weapon, making it almost the best weapon for chosen with shield.
On character select screen chosen equipped with that item start to make a marauder's "claw" thing.
Can be obtained in 18 chapter of greenskin, influence reward.
![235151515](https://cloud.githubusercontent.com/assets/18102127/18295315/888296dc-74b1-11e6-8c05-84d36d381bb0.png)
![2135511515](https://cloud.githubusercontent.com/assets/18102127/18295319/8d38aaf4-74b1-11e6-8c33-bad49525f41d.png)
![23525211235](https://cloud.githubusercontent.com/assets/18102127/18295324/9190e030-74b1-11e6-8aed-66c526d5592c.png)
![334269843](https://cloud.githubusercontent.com/assets/18102127/18295327/94ddea1c-74b1-11e6-907a-6b155988f454.png)

**Comment by Ryanfawkez** [comment]
Supposed to an Empire two-handed sword. What is this item's origin?

**Comment by Ryanfawkez** [comment]
Nevermind; Greenskin chapter 17. Strange.

**Comment by Ryanfawkez** [comment]
Will make it a Chosen one-hand sword with appropriate name, stats and appearance.
