### ISSUE TITLE
No activation email

### ISSUE THREAD

**Issue by farbroranti** [WarEmu/WarBugs#767]
Hello, i have made an account but i did not get an activation email, the support is not working either. Could i please have this activation email resent to my mail adress.

**Comment by DanaBloodkiss** [comment]
Hello, please don't use a Microsoft related E-Mail address. Thanks. Greetings

**Comment by farbroranti** [comment]
ok thank you that worked but whn i try to log into the game using the RORlauncher it says ´´an error occured...´´. Any ideas what it might be?
Best regards farbroranti

**Comment by DanaBloodkiss** [comment]
Take a look here please -> http://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=2889
