### ISSUE TITLE
T1 oRvR Chaos/Empire battle objectives (destro side)

### ISSUE THREAD

**Issue by Sarineth** [WarEmu/WarBugs#7670]
As of this morning I was unable to cap the Battle objectives in T1 oRvR in the Chaos/Empire zone. No one in my Warband was able to do it.
We cleared out all the NPC mobs and got the message "this objective is already being capped by your side" when trying to cap it. But this was not the case and the NPCs just kept respawning. This was the case for both Festenplatz and New Emskrank.
We were already in controle of The Nordland IX but order capped it and we were unable to recap. The message that appeared was "can't cap due to NPC X being alive". I forgot the exact name but it was the destro champion that guards the BO. Non of us were able to cap it. Time just ran out and it got locked.

**Comment by Soulwhisper** [comment]
#7644
