### ISSUE TITLE
Maraudeur/Magus 

### ISSUE THREAD

**Issue by kabbolt** [WarEmu/WarBugs#7671]
Visiblement le grappin du maraudeur est bien plus rapide que ce qu'il était sur l'officiel et ce d'au moins une seconde voir plus. Je ne suis pas le seul a l'avoir remarquer et a le dire mais ce genre de petit avantage pour nos ennemies est particulièrement irritant. A vrai dire celui ci est tellement rapide qu'il ne nous laisse pas le temps de Silence ou de Stun comme on avais la possiblité de le faire sur l'officiel. Pour ma part, sachant qu'un t'elle sors ( buggé ) soit utilisable par nos adversaire et que nous de notre côté nous n'avons pas de sors équivalent, est pour moi tout bonnement de l'anti-jeu ou encore un net avantage programmer consciemment, ce qui serait bien pire encore mais surtout malheureux..

Parlons maintenant du Magus.

Celui ci est capable ( comme sans doute l'ingénieur ) d'aspirer des joueurs alors qu'ils sont en hauteurs sur les remparts du Fort. Ceci est un bug et na jamais exister auparavant sur l'officiel car la ligne de vue est briser par le positionnement du joueur ce trouvant en hauteur. Il est possible que les concepteur du jeu est en effet ajouter un code a cet effet car le ciblage est possible si une partie supérieur du corps qui dépasse suffisamment pour des spells conventionnel mais pas pour faire une aspi. En théorie.. le moindre petit obstacle au niveau des pieds empêche tout genre d'aspiration. Je n'est pas eu l'occasion de voir un maraudeur le faire mais si une t'elle chose était possible je peu vous dire que c'est une belle connerie.

Cordialement.

 PS: in english with systran.. sorry

Obviously the hook of the petty thief is much faster than than it was on the official one and this of at least a second to see more. I am not the only one to have it to notice and has to say it but this kind of small advantage for our enemy is particularly irritating. To tell the truth that Ci is so fast that it does not leave us the time of Silence or Stun as one had the possibility of making it on the official one to counter the aspi. For my part, knowing that you it leaves (buggé) that is to say usable by our adversary and that we our to dimension we do not have leave equivalent, is for me simply of the anti-play or, a Net favors to program consciously what would be quite worse still but especially unhappy.

Let us speak now about Magus.

That Ci is able (as undoubtedly the engineer) to aspire players whereas they are in heights on the ramparts of the keep. This is a bug and Na never to exist before on the official one because the line of sight is to break by the positioning of the player this finding in height. It is possible that the originator of the play is indeed to add a code for this purpose because the targeting is possible if a superior part of the body which exceeds sufficiently for spells conventional but not to make a aspi. In theory. the least small obstacle on the level of the feet prevents any kind of aspiration. I am not on the occasion to see a petty thief making it but if you it thing were possible I to say little to you that it is a beautiful bullshit.

Cordially

**Comment by Luth-RoR** [comment]
Sorry, but all i understand is that this report has something to do with mara/magus pulls and height differences. 
Maybe someone who speaks french and english could write what's should be wrong here.

**Comment by ozarmidrashim** [comment]
The bugtracker rules explicitly state that if you cannot speak competent English, you are not welcome to post here. Someone who speaks English should report whatever this is independently. I don't want to see a precedent for walls of foreign language and crappy Google Translate results posted here.
