### ISSUE TITLE
shaman spell gedoff! and absorb

### ISSUE THREAD

**Issue by Ravenfox** [WarEmu/WarBugs#7673]
I saw my shaman spell gedoff! , the knockback did not work when it got absorbed

**Comment by Ravenfox** [comment]
could it be that it got distrubted but it showed absorb? sorry

**Comment by Luth-RoR** [comment]
>could it be that it got distrubted but it showed absorb? 
No don't think so; but if the full damage from an ability is absorbed, any other buffs/debuffs the ability has don't work afaik. It's the same as when the the damage got avoided by block/disrupt etc.
