### ISSUE TITLE
Ekrund Warcamp Bug

### ISSUE THREAD

**Issue by Esperflame** [WarEmu/WarBugs#7680]
While mounted a random guard will all of a sudden appear on your horse riding behind you which causes the game to crash. This seems to always happen to me as I'm leaving the warcamp mounted and heading for the Lair Boss.

**Comment by Soulwhisper** [comment]
#7292

**Comment by Luth-RoR** [comment]
As i don't know if this is bound to certain locations or what could cause it, i'll leave this open in case devs need infos where this is happening.

**Comment by Torquemadra** [comment]
linked, no need to keep reports of the same thing open
