### ISSUE TITLE
What Blocka? Ability [SH]

### ISSUE THREAD

**Issue by footpatrol2** [WarEmu/WarBugs#7681]
This ability does not reduce 10% block like it should. It does reduce armor though correctly. 

I have only checked the SH ability. It may be worthwhile to check if Acid Arrow is working correctly or not in reducing block percentage. What Blocka and Acid Arrow are basically identical.

**Comment by noisestorm** [comment]
generally for stuff like that:
let your target make 2 screenshots with .getstats and show proof for it

**Comment by ozarmidrashim** [comment]
What Blocka's tooltip does not, and cannot, display its block reduction.

Please do not report that an ability is bugged in terms of combat formulae and mechanics on the basis of the buff tooltip missing information. Thank you!
