### ISSUE TITLE
Shaman spell Gather round

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#7686]
http://imgur.com/a/yJ11d

tooltip range is incorrect ;it should be 65 ft?

**Comment by Soulwhisper** [comment]
No its not.Its 100ft.Not a bug.
http://waronlinebuilder.org/#abilities=sha;

**Comment by Luth-RoR** [comment]
All group heals are 100 feet, single target heals 150 feet. 
Please only confirmed bugs on the tracker, not problems that can be answered with google.
