### ISSUE TITLE
[DPS Seige Equipment]

### ISSUE THREAD

**Issue by roadkillrobin** [WarEmu/WarBugs#7688]
This aint as much as a conformed bug but after playing months and consistantly getting warband UI bugs, and now new bugs related to the Battale Fattuige were you get 15min debuff in RVR death instead of the 3 min that happens after player death I think they both may be related to Damage from Seige Equipment.

BF: You die from non player dmg and game think this is from a PVE source instead of a flagged player. Pretty simple

WB UI Bug: So this seem to happens consitantly when people die from Oil, Seige Weapons. It pretty much always happen when close to a Enemy Warcamp (Were they often shoot your with cannons) or close to Enemy keeps were they drop oil and cannons.

So I just added the two together, could it be that the Group UI becomes confused somehow coz the dmg that killed the players causes some conflict?

**Comment by Yellowpillow** [comment]
i get 15 min debuff after i was killed by regular player all the time.

**Comment by Luth-RoR** [comment]
Refering to https://github.com/WarEmu/WarBugs/issues/7634
