### ISSUE TITLE
Flickering of mounted players.

### ISSUE THREAD

**Issue by ozarmidrashim** [WarEmu/WarBugs#769]
Posting this one here in case someone other than me has any ideas.

Players repeatedly flicker while mounted. Analysis indicates that player positions have an occasional error of about 300 feet (presumably this is from F_PLAYER_STATE2 position updates) and this causes the player to be detected as out of range, with a removal packet being sent. On the next tick, the player is correctly in range and the creation packet is sent.

**Comment by Thorgatin** [comment]
I have this since the last patch iirc.

**Comment by ozarmidrashim** [comment]
It looks like it's not even F_PLAYER_STATE2 - delta local position from F_PLAYER_STATE2 is perfectly fine. Delta world position is not.

**Comment by ozarmidrashim** [comment]
It's F_DUMP_STATICS. This packet is changing the zone offsets in use. This cannot be correct.

**Comment by ozarmidrashim** [comment]
Fixed.
