### ISSUE TITLE
Kadrin Valley - Kazad Dammaz Keep terrain

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7691]
- Stairs are missing here.Needs to be higher.Now you have to jump.
![pater_000](https://cloud.githubusercontent.com/assets/16864486/18365549/d3ca9cfa-761b-11e6-9372-30598f9c2ab8.jpg)

**Comment by Daniellita** [comment]
I think the stairs are placed slighly too forward ( theydisappear into the tower). It can also result in the player getting stuck on the left side of the stairs here.

**Comment by Luth-RoR** [comment]
Unfortunately this can't be changed until the client can be modified; closed until the moment has come.
