### ISSUE TITLE
Melee power and strength may be wrong balanced

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#7693]
Tests shown, that to gain 1 dps you need 4 melee power or 3 strength (tested from an actual damage). That doesn't seem right. Melee power is just fine, because on live 4 MP was equal 1 dps, same on RoR.
But strength is not supposed to give 1 dps from only 3 points, like it is now. 
On live strength also raise block penetration and parry penetration, and because of that 5 strength gives 1 dps.
On live balanse was:
5 strength = 1 dps + a little bit penetration of parry and block 
4 melee power = 1 dps and no penetration bonus
Melee power (and other "power" stats) used to be more precious than strength on live because of that reason.
Probably it affects inteligence and willpower stats aswell. And this is probably main reason why somebody wearing annihilator set with 700-800 strength now can do damage numbers same as 80rr wearing sovereign (with melee power procs) back on live.
IDK if this is bug or it was intentional, but i'm sure everyone who play on live remember this simple damage formula. So if strength was raised up, than melee power should be raised up too, right?

**Comment by ozarmidrashim** [comment]
I have no idea what testing you've been doing but it's clearly wrong.

        private static void AddOffensiveStats(Unit caster, AbilityDamageInfo damageInfo, float coefficient, bool toPrecalc)
        {
            uint softcap = (uint)(50 + 25 * caster.EffectiveLevel);
            uint hardcap = (uint)(50 + 55 * caster.EffectiveLevel);

            var stat = (uint)caster.StsInterface.GetTotalStat(damageInfo.StatUsed);

            if (stat > hardcap)
                stat = hardcap;

            else if (stat > softcap)
                stat = softcap + ((stat - softcap) / 3);
            
            // Power stats bypass the caps
            switch (damageInfo.StatUsed)
            {
                case 1:
                    stat += (uint)caster.StsInterface.GetBonusStat((ushort) BonusTypes.BONUSTYPES_EBONUS_DAMAGE_MELEE);
                    break;
                case 3:
                    stat += (uint)caster.StsInterface.GetBonusStat((ushort)BonusTypes.BONUSTYPES_EBONUS_HEALING_POWER);
                    break;
                case 8:
                    stat += (uint)caster.StsInterface.GetBonusStat((ushort)BonusTypes.BONUSTYPES_EBONUS_DAMAGE_RANGED);
                    break;
                case 9:
                    stat += (uint)caster.StsInterface.GetBonusStat((ushort)BonusTypes.BONUSTYPES_EBONUS_DAMAGE_MAGIC);
                    break;
            }

            if (toPrecalc)
                damageInfo.PrecalcDamage += stat * coefficient * damageInfo.StatDamageScale * damageInfo.CastTimeDamageMult;
            else
                damageInfo.Damage += stat * coefficient * damageInfo.StatDamageScale * damageInfo.CastTimeDamageMult;
        }

**Comment by Pxl555** [comment]
3 things i can say about this :

a.) you should provide some proof (screenshots/videos) when you make claims in the future
b.) melee power = strength on live and here aswell ( if you think otherwise prove it)
and 
c.) I am 99% certain that when you did in your 'private tests' you simply added a certain amount of damage stat and looked at how much your abilities damage has increased without calculating in the original GCD which also impacted the way instant-cast abilities are calculated for original warhammer,

Now towards the actual issue here, the GCD on RoR is 1.1s and not 1.5s and this post of azarael should provide more clarification on why you might feel that you see increased damage
https://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=10874&p=111036&hilit=global+cooldown#p111036

Here the last part is significant  'This is a buff to any skill with a cast time less than 1.1 seconds'


And as for my last point , If you do tests with abilities with ,lets say a 2 second cast time, if you calculate their damage in conjunction with their cast time you should see the correct values, as they will not get impacted by the shorter gcd.

**Comment by Yellowpillow** [comment]
Okay, I'll try to explain differently. (I'm apologise for my poor english, causing misunderstandings sometimes)
I tested it by hitting in duel one of my friends, and take information about outcoming gamage from chat
test one (without armor):
with 36 melee power i hit him for 255 + 85 mitigated
without 36 melee power i hit him for 246 + 85 mitigated
9 points of damage = 36 melee power
1 damage points (i called it dps) = ~4 melee power
another one (he put armor back because it don't affected test):
without 20 strength i hit him for 152 + 496 mitigated
with 20 strength i hit him for 154 + 474 mitigated
20 strength = 7 dps (damage points)
1 dps = ~3 (rounded from 2,8 with chance that some of strength from another clothes can make it incomplete)

Tomorrow i make more tests with screenshots.

**Comment by Pxl555** [comment]
And exactly there is the problem ( what i said under point C in my previous post is what you did) , you are saying how 9 increased damage = 9 dps which it is NOT. To give you a simple example : 

If you increase your tooltip/hit damage by 9 , and you are using an instant cast ability , on the original GCD of 1.5 seconds your dps increase from that would be 6 ( The fact that we have a lower gcd now doesn't change the fact that thats how it was designed and scaled )

9 increased tooltip damage on instant cast = 6 dps  (under the original 1.5 GCD ) which fits the calculation

As for those numbers and how you have different values for str/melee power , it would be nice  to have some screenshots attached to it with some context ( char screen ,tactics visible etc.) as you already said you are going to make.

**Comment by Yellowpillow** [comment]
Today's results:
I make damage balanced by adding low lvl strength talisman to reach full number.
I use instant ability Transfer Essence.
Base test damage - 601
with additional 20 strength - 609 (20/8=2,5 more damage points)
with additional 36 melee power - 615 (36/14=2,57 more damage points)
2,5 is not 5 as you mentioned above. Even 1.1 vs 1.5 GCD difference is not make sence to me, because it is not twice as big.
![base damage](https://cloud.githubusercontent.com/assets/18102127/18391804/4737279a-76c0-11e6-94bb-6fcea036237b.jpg)
![test 1](https://cloud.githubusercontent.com/assets/18102127/18391805/473a913c-76c0-11e6-876d-54d6fe86db25.jpg)
![test 2](https://cloud.githubusercontent.com/assets/18102127/18391806/473df1e2-76c0-11e6-8a20-c82a592a78bf.jpg)
Yesterday's unfitting of stats may be result of bug of russian client and yesterday i don't round damage numbers by low level talismans.
I think i don't understand something, so if you assume that mechanic is working fine - please close this rerort.

**Comment by Pxl555** [comment]
And thats also the reason why i said you should provide a screenshot with your tactics as you are most likely running divine fury which adds another scaling damage factor ( +25% dmg) into the mix.

To you numbers : 
20str/5 =4dps  ,  4dps *1.5 =6 tooltip damage on instant cast abilties , 6 dmg *1.25=7.5 (from divine fury and i assume its getting rounded to ~8) and lines up with your numbers

36melee power/5 = 7.2 dps  , 7.2dps*1.5=10.8 tooltip damage on instant cast abilities , 10.8*1.25 =13.5 (from divine fury and i assume its getting rounded to ~14) and lines up with your numbers
