### ISSUE TITLE
Icehearth Crossing BO guard bugged out sometimes

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#7696]
There is engineer guardian NPC, who sometimes bugged out and shoot from insides of textures, where he cannot be shooted or reached. After some manipulations with positioning he came out. It happened several times.
![arena_054](https://cloud.githubusercontent.com/assets/18102127/18371877/fd8b6f88-7648-11e6-95b3-7a543ed27210.jpg)
![arena_055](https://cloud.githubusercontent.com/assets/18102127/18371895/2be54f34-7649-11e6-83d9-76c45b231e7f.jpg)

**Comment by Yellowpillow** [comment]
His place on a stone bridge by default and sometimes he stuck up in textures above his position.
 ![arena_098](https://cloud.githubusercontent.com/assets/18102127/18534577/bb581a30-7afd-11e6-91ad-57b2e14ee61c.jpg)

**Comment by sioding** [comment]
Since we have no guards at BO´s anymore - close
