### ISSUE TITLE
NPC perma-acting (High-Elves, Shadowlands)

### ISSUE THREAD

**Issue by Milord9** [WarEmu/WarBugs#7697]
NPC Liradean Swiftarm, in a Shadowlands High Elve camp (52306 - 39010) is permanently doing his sword animation/emote. Please 
![arenia_002](https://cloud.githubusercontent.com/assets/17692456/18373022/f3a4b89c-7640-11e6-80d4-e3385923f513.jpg)

**Comment by Lheana** [comment]
Seems like he stopped.
