### ISSUE TITLE
"Quest completed" logo doesn't disappear 

### ISSUE THREAD

**Issue by Milord9** [WarEmu/WarBugs#7698]
In the quest "Eataine scout" (Eataine, High Elves), we can possibly talk and finish the quest with one of the three scout NPC. But if we do so, the other NPC will keep the orange ticked book "quest completed" above their head.

Same issue than another quest in Saphery in the High Elves side, with three goblins that have to be given mushrooms. (sorry but I dont remember exactly the quest)

![arenia_013](https://cloud.githubusercontent.com/assets/17692456/18373173/4be6c9fe-7642-11e6-9818-0f62bd212c23.jpg)

**Comment by sioding** [comment]
fixed with patch from 31.08.2019
