### ISSUE TITLE
Respawn in Eataine is bugged

### ISSUE THREAD

**Issue by Milord9** [WarEmu/WarBugs#7699]
When we die, we are supposed to respawn to the closest city/town, right ? In Eataine (High Elves), looks like the respawn function is completely inverted: if we die east of the map, we should respawn in Goldenvale manor (61900 - 11900) but instead we restart at Haleril's resolve (20600 - 18500); and if we die west of the map, instead of reappearing in Haleril's resolve, we go back to Goldenvale.

I'm not sure about the respawning system, but I've found weird to be put at the exact oppisite of the map every time.

![arenia_017](https://cloud.githubusercontent.com/assets/17692456/18373306/4ba05b8a-7643-11e6-834c-c775d5fa1876.jpg)

**Comment by Soulwhisper** [comment]
#7259
Please always check if it has already been reported.
