### ISSUE TITLE
Becoming a chicken after SC

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#7701]
I recently completed a Stone Troll Crossing scenario, and upon returning to Thunder Mountain, I was a chicken. I am aware that STC likes to chicken people (even on live I remember it happening). Also I got the pop just before I clicked the flight path to TM, but accepted the SC after I had landed. If it matters I was alive at the end, without resurrection sickness, and Destruction won the Scenario (although there was something like 30 seconds left on the clock)

![iamnotagirl_002](https://cloud.githubusercontent.com/assets/13975292/18376535/bcdc9872-7625-11e6-8c42-6eda55ac1ef0.jpg)

**Comment by Kaelang** [comment]
Appreciate this is a dated report - however this does not provide enough information to identify the issue and/or replicate the problem. Please re-open this issue if this persists in the latest version of RoR.
