### ISSUE TITLE
Empire T1 quest Alive and Well

### ISSUE THREAD

**Issue by Sarineth** [WarEmu/WarBugs#7702]
The quests starts in Altdorf just fine, you can pick up the letter and deliver it to the wife (Agatha Becker) in Nordland but the follow up (also called Alive and Well) can't be done.
You have to read the letter to Agatha but there is no letter in your inventory so you can't complete it.

**Comment by Ryanfawkez** [comment]
Ugh.

**Comment by Ryanfawkez** [comment]
You sure it ain't in your quest inventory?

**Comment by Ryanfawkez** [comment]
Yeah the last quest swallows your item when you complete it, roflmao
So much for implementing a "use item" mechanic...

**Comment by Ryanfawkez** [comment]
Made a work-around - Agatha just now has to be spoken to to complete the quest.

**Comment by Sarineth** [comment]
Spoke to Agatha, doesn't complete the quest for me. Only option I have is
'Goodbye'.

2016-09-09 13:19 GMT+02:00 Ryan Fawkez <notifications@github.com>:

**Comment by Ryanfawkez** [comment]
Yes love, the quest is still broken since we haven't patched in the time that I have fixed this issue. You'll be able to complete the quest after the next patch we do. - it's why this ticket is now flagged as 'Fix Pending'.
