### ISSUE TITLE
Extra mastery point bug.

### ISSUE THREAD

**Issue by Sporc** [WarEmu/WarBugs#7703]
So earlier today I equipped 5 pieces of ruin to get the extra mastery point, and bought a tactic with it, equipping it to my bar. Later, I swapped a piece of ruin out, losing the mastery point, but the tactic remained equipped and effective, despite that I was no longer spec'd into it as I should have lost that point.

**Comment by Sporc** [comment]
In specific, I had da toughest maxed mastery tree maxed out, and used the extra point to buy save da runts for black orc, in case this isn't a general issue.

**Comment by Luth-RoR** [comment]
Just tested it with the IB and merc gear on the dev server, the tactic was removed as soon as the mastery point got lost (by unequipping an item). I don't think there is different code for every set to handle the extra mastery point from the sets.

Are you sure about this?

**Comment by Sporc** [comment]
Certain, I had done it in the inevitable city in order to slot in Stop hittin da runts for the arena without having to spend the gold to respec.

**Comment by Sporc** [comment]
Afterwards I swapped out the ruin feet for my Drengi feetsplate and still had the tactic.

**Comment by Sporc** [comment]
Alright so I did some testing to recreate what had happened. 
![war 2016-09-09 13-34-41](https://cloud.githubusercontent.com/assets/20248229/18396869/b9448742-7693-11e6-8d79-54e089cc3c4a.png)

![war 2016-09-09 13-40-37](https://cloud.githubusercontent.com/assets/20248229/18396884/c0e417b0-7693-11e6-93e8-1f094b4db86e.png)


![war 2016-09-09 13-41-09](https://cloud.githubusercontent.com/assets/20248229/18396891/c78eccea-7693-11e6-85d1-c6eefc02664d.png)

![war 2016-09-09 13-43-21](https://cloud.githubusercontent.com/assets/20248229/18396898/d2fea0aa-7693-11e6-9fd9-31250bc71879.png)

As you can see I was mistaken in it giving you an extra mastery point, however it is removing the "bonus" point gained from the gearset from the top of the bar rather then what it was last spent in, in this case the tactic. My mistake and I'm not sure if this issue has been reported already.

**Comment by Luth-RoR** [comment]
Ofc it does take the top mastery point first, because it is the last one on the "ladder". 
As i see it, it works like the tactics and abilities are like step number 3.5, 5.5, 7.5 etc.
If, for example, you only had allocated 7 mastery points + the tactic (7.5) and removed one set piece then the tactic would have been removed, as i is the last step on the "ladder".
