### ISSUE TITLE
Swordmaster T2 RVR Rewards - Missing Talisman Slots

### ISSUE THREAD

**Issue by mozlei** [WarEmu/WarBugs#7704]
Hi

As above, a number of T2 rvr influence rewards are missing talisman slots on their enteries (and I assume the actual items although haven't been able to test this) where I would expect there to be one (or two). These are the following:

Dwarf
Karaz Blade - 1h Weapon

Elf
Spite's Balancers - Shoulders
Spite's Blade - 1h Weapon
Greatsword of Thunder - 2h Weapon (should have 2 slots?)

Thanks

**Comment by Luth-RoR** [comment]
Thanks, but this is already known for a very long time. I think devs are working atm on this, to complete the items and make stats more reasonable.
