### ISSUE TITLE
Different Character/Character Transformation on Log-in.

### ISSUE THREAD

**Issue by Daniellita** [WarEmu/WarBugs#7706]
This bug happened while logging into the Viper's Pit so it may be related or entirely caused by the Viper's Pit crashing bug/s (#7649).

For context this happened after I attempted to log in my Shaman (Dennied) into Viper's pit and crashed onto the initial game screen. Following that I shook hands, logged in and attempted to log in my Black Orc (Zugzmazh) into Ostland.

Upon logging onto my Black Orc (Zugzmazh) I was instead presented with a character that was a mutant between my Black Orc and my Shaman (Dennied) in appearance. It had the abilities of my Shaman and the UI and location (Viper's Pit)  of my Shaman, but the name of my Black Orc. It  may be that the client retained some information from the previous failed character log-in attempt and then used it in the next one? (Just a pure speculation)

Screenshot of what the situation looked like after logging in onto the Black Orc: http://imgur.com/a/5uygB

**Comment by Luth-RoR** [comment]
Thanks for the additional info.

**Comment by MaxHayman** [comment]
Going to asssume this was fixed as is been 4 years with no more comments.
