### ISSUE TITLE
Strange bug after using BookOfBinding in Ekrund

### ISSUE THREAD

**Issue by Titoos** [WarEmu/WarBugs#771]
When Im using my BoB in Ekrund (in Mount Bloodhorn it works perfectly fine):
1) I am destruction player, and I have my book binded in Chaos Warcamp - Nordland
2) I am in Ekrund and I use da BookOfBinding, after that Im getting Nordland Loading Screen
3) Instead of being in Nordland I am ported to Mount Bloodhorn to 57k,45k coordinates
4) In addition yesterday (10.06) during birthday event, when I got back to da battlefield "by foot", I noticed, that all mounted players have my name beneath their own (screen below), and I am [sic!] invisible to other players. Dont know if this is related to da Book Issue (no mounted players to check :) ) but its worth checking. 
5) After relogging I woke up In Nordland. 
 
![mieczyslav_013](https://cloud.githubusercontent.com/assets/12809856/8101696/e61f388e-1019-11e5-96f4-599c04b6da11.jpg)

**Comment by Evildoor** [comment]
Closing per #639.
