### ISSUE TITLE
[Chosen] Oppression not working without a shield

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#7712]
The path of Corruption ability Oppression functions well with sword and shield, but does not work when using a two handed weapon, or a one handed weapon without a shield. All that the ability requires is a block or a parry, it does not say that it requires a shield in the tooltip.

**Comment by Luth-RoR** [comment]
Hm, yes. This issue was fixed in the past, but seems to be back: https://github.com/WarEmu/WarBugs/issues/7078

**Comment by Luth-RoR** [comment]
Can confirm that the ability activates on parry at the devserver, but can't be executed with a 2H weapon.
Has probably the shield req. again.

**Comment by CaptainoftheHarem** [comment]
I will say that on the live server it does work on parry, but does indeed require a shield to be acquiped

**Comment by Luth-RoR** [comment]
In that case the client shouldn't activate the icon when you use a 2H weapon.

**Comment by CaptainoftheHarem** [comment]
I meant the RoR server rather than back on live, the requirement is only a block or parry (it does not require a shield in the tooltip)

**Comment by Luth-RoR** [comment]
Ah, ok. Most people mean the _non-live_ mythic server when they say _live_.
>but does indeed require a shield to be equipped

**Comment by CaptainoftheHarem** [comment]
On the mythic server (if I recall correctly) I was able to use oppression using a two handed weapon

**Comment by ozarmidrashim** [comment]
Was resolved
