### ISSUE TITLE
[Monster] Grimwing wrong model and level

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#7713]
The monster Grimwing in Eataine (52k,63k) has the model of a giant bat, instead of a griffon. Furthermore it is supposed to be a level 39 or 40 champion rather than a level 23 champion. Killing this monster still grants the title "The Majestic" as it is supposed to.

**Comment by Ryanfawkez** [comment]
https://github.com/WarEmu/WarBugs/issues/7506 - Probably the same issue that occurred here; two NPCs with the same name merged into the same ID.

**Comment by Ryanfawkez** [comment]
There is one spawn in Eataine and another in Talabecland - will create a new, unique entry.
