### ISSUE TITLE
Magus tactic "Flame's Kiss"

### ISSUE THREAD

**Issue by Toldavf** [WarEmu/WarBugs#7714]
This tactic makes Rend winds and flickering red fire undependable. However when they interact with abilities that grant near guaranteed defence such as oath stone it ceases to work and the attacks are blocked.

**Comment by Luth-RoR** [comment]
Needs confirmation if it worked like described on the mythic server (i guess so).
I suspect similar tactics, like http://waronlinebuilder.org/#career=bw;11;0;0;11:;;;;0:0:0:0: to work equally atm.

**Comment by ozarmidrashim** [comment]
This is NOT a bug.

There is a distinction between "virtually/almost always" and "certain" in WAR.

Abilities which are virtually undefendable have +100% to their strikethrough chance.
Abilities which render you "almost always" likely to defend are actually implemented as granting +100% defense chance.

Abilities which are undefendable are NEVER defended under ANY circumstance.
Abilities which render you certain to defend will cause defense checks to ALWAYS pass, UNLESS the ability is undefendable.

**Comment by Luth-RoR** [comment]
Ok, the example with the BW tactic was bad, though the "Flickering winds" tooltip says only _un-defendable_, without any constraint. 
I guess it's handled wrong then atm, but it would be nice if the OP posts screenshots for evidence.

**Comment by ozarmidrashim** [comment]
Changed and fix pending.
