### ISSUE TITLE
Blighted Island, DE Prologue, 'Spearman' NPCs here are humans, not sure it's correct.

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#7718]
![asorath_003](https://cloud.githubusercontent.com/assets/19625008/18412459/20a07288-778f-11e6-8f15-1f90f34171ad.jpg)

The starting quests are talking about High Elf Sea Guard, nothing about humans, so I don't think it's correct.

**Comment by avenflar** [comment]
https://youtu.be/k_5Roo2SV-o?t=9m26s

Found this one video from live, they should indeed be HE and not humans

**Comment by Luth-RoR** [comment]
Thanks

**Comment by Ryanfawkez** [comment]
Another database merge it seems. I hate how NPCs with the same names on live are shared under the same NPC ID...
