### ISSUE TITLE
Bugged BOs

### ISSUE THREAD

**Issue by Swarmofseals** [WarEmu/WarBugs#7719]
I've been getting reports of bugged BOs throughout all tiers. I'm working on investigating now. These BOs can be cleared of NPCs but the flag is not interactable and the BO cannot be flipped. T1 BOs, on the other hand, are permanently locked and do not have guards. This is making many pairing/tier combinations unplayable at the moment. I haven't been able to find volunteers to help me do a complete inventory yet but there seem to be quite a lot of bugged ones. These below appear to be currently bugged based on reports in game or my own findings:

T1: All three BOs in Nordland/Norsca
T2: Ironclad, Crypt of Weapons, Monastery of Morr
T3: Ogrund Tavern
T4: Kurlov's Armory, Karak Palik, Gromril Kruk, Martyr's Square, Hardwater Falls

I've also heard reports that the keep lord in Karak Karag was missing this morning.

It's possible that all of the BOs in the DvG and EvC pairings across all tiers are bugged, but I haven't been able to confirm this yet. I have not gotten any reports of elf pairing BOs being bugged.

**Comment by Luth-RoR** [comment]
Current RvR issues are known and will be fixed with the next patch: https://github.com/WarEmu/WarBugs/issues/7705
