### ISSUE TITLE
Test of Loyalty, Order T4 dye quest

### ISSUE THREAD

**Issue by qualteia** [WarEmu/WarBugs#7720]
Hello!

Quest as per MMODB has dye rewards http://war.mmodb.com/quests/test-of-loyalty-1691.php but our version of the game doesn't have them yet. Further, I cant seem to find the NPC Luke Stockwood but I may be blind..
Thanks! 
![test of loyalty](https://cloud.githubusercontent.com/assets/16740013/18413008/fb16d1ae-7759-11e6-91cf-1ab81a5f90d4.png)

**Comment by Ryanfawkez** [comment]
He's in the south-west corner of the map.

**Comment by thorbolt80** [comment]
Location of luke stockwood? because there is no red mark on the map...
