### ISSUE TITLE
Striking the Source, Order T3 dye quest

### ISSUE THREAD

**Issue by qualteia** [WarEmu/WarBugs#7721]
T3 Elf dye quest in Ch 11 but its not yet repeatable, please see image for details!
Thanks again!
![striking the source](https://cloud.githubusercontent.com/assets/16740013/18413434/306e043e-7765-11e6-8393-fa1bbc567879.jpg)

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/6945

**Comment by qualteia** [comment]
I'm not sure why you closed this one, or referenced a ticket where the issue is not the same.. Ch 11 emp quest Ugly Face is repeatable, why cant this one be?

**Comment by Luth-RoR** [comment]
I see, i checked back with a DB dev and all dye quests should indeed be repeatable.

**Comment by qualteia** [comment]
Thanks guys :)
