### ISSUE TITLE
Dwarf quest "Stout and bitter"

### ISSUE THREAD

**Issue by jpnrd** [WarEmu/WarBugs#7723]
HI :)

I started this quest wit the npc "Hrogir Bitterstone" in Ekrund, chapter 2.
It leads us through that first zone (6 or 7 steps) until we're asked to report to Od Rhodgar in Mount Bloodhorn. 

There, 1 more step is Ok and the next one is bugged. Seems like we have to retrieve dwarf goods in addition to the killing of dog soldiers. The count for the killing is working but the second one gives a Npc's name ( destro side kill collector it seems) 
There are "bitterstone crates" near the men we got to eliminate but clicking them makes nothing happen. 

Some screenshots for the quest description ( + count of tasks)  and location.

![thrulontin_090](https://cloud.githubusercontent.com/assets/16733126/18413747/7a37ab36-77b2-11e6-823f-4b4711be41f7.jpg)
![thrulontin_091](https://cloud.githubusercontent.com/assets/16733126/18413746/7a37a42e-77b2-11e6-9c62-79aebe7f2fb7.jpg)

Od Rhodgar is just behind the Tome :) 

It would be awesome if you can fix that, the quest is really funny and i'd love to end it :)

THanks a lot for all the great work you do!

**Comment by Luth-RoR** [comment]
There was an issue with that quest earlier: https://github.com/WarEmu/WarBugs/issues/7039
Needs confirmation from DB dev if it is bugged.

**Comment by Ryanfawkez** [comment]
Herp-a-derp. I dun goof'd.

**Comment by jpnrd** [comment]
Just to say it now works fine, all to the end, thanks a lot :)
