### ISSUE TITLE
Many of Order's public quest have wrong name inside objective counter

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#7724]
Inside obgective counter PQ called "Destruction" instead of it's real name. For example The Burning Windmill
![tranquillity_000](https://cloud.githubusercontent.com/assets/18102127/18414450/8b5e2f8a-77d9-11e6-8006-85bdc5da9121.jpg)

**Comment by Soulwhisper** [comment]
#7144

**Comment by Yellowpillow** [comment]
change issue, was distracted by wrong name, which is issue itself

**Comment by Soulwhisper** [comment]
Yeap thats a known and really old Major issue.

**Comment by avenflar** [comment]
Weirdly, I believe all Destruction PQ have their correct name

**Comment by Soulwhisper** [comment]
If not all then over 95% of Order PQs have Destruction name on them.

**Comment by Lheana** [comment]
Secrets fixed this last patch. Order PQs now correctly show their name on PQ tracker.
