### ISSUE TITLE
Gates of Elthrai Public Quest - High Elves Chapter 

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7727]
- Loathsome Construct Hero is in the ground(he should be on it).

**When you kill him he pops up for a sec(We can see his animation for that sec).**
**Looks like an ugly BO.**

**Comment by Ryanfawkez** [comment]
He's in a buried animation, as there used to be a script that'd switch him to crawling out of the ground. Will remove his emote for now.

**Comment by Soulwhisper** [comment]
This is patched.

**Comment by Herdon** [comment]
Just a minor note.
There seems to be alot of Loathsome Steed in that PQ for some reason.
![Horses](https://user-images.githubusercontent.com/2021593/164335584-282b7538-6f41-4884-9758-b9f8085d490b.jpg)

**Comment by lilimx** [comment]
This ticket is closed, please open a new one with your issue.
