### ISSUE TITLE
GM Alena exceeds the powers, and baned me on forum

### ISSUE THREAD

**Issue by krisolyub** [WarEmu/WarBugs#7729]
I cant understand why you again ban my account (Krisolyub) and account of my friend (Vttakk).
After 1st ban i made chars on the account "vttakk". That my appleal (https://www.returnofreckoning.com/forum/viewtopic.php?f=87&t=16384) is the same that this 
(https://www.returnofreckoning.com/forum/viewtopic.php?f=87&t=16807). But i got full wipe all my 7 chars 40lvl including SW Pedik 57RR. And mikedg got 7 days ban for the same. Looks like some 1 just hates me.

And now again i got 7 days ban of the account Vttakk when played on SM Dypka. The reson of ban was "2nd violation of name rules". But i didnt get the 1st:)) And when i logged to my own account Krisolyub and asked GM Alena "what is my fail?" she answered type only on forum. I told her that i cant type on forum because i use mobile Internet modem, so my IP is in blacklist. She adviced me to hack this server protection. I told that i dont want to hack server and aked her to help me solve this problem. She just told me that i do "Ban violation" and will be ban on this acc. LOL like deadlock ROBOT!!! 
I understoon there is no reason talk to Alena and asked another GM help me. But that moment i was kicked from server. 

Pls do something with you punishment system! Punish robots!!!
Unban me and return at least my chars gear (purple fragmets on my SW Pedik).

Best regards. Pedik.

**Comment by krisolyub** [comment]
![pedik_144](https://cloud.githubusercontent.com/assets/16418935/18418455/7d1c601a-784f-11e6-9e3a-669864cf700c.jpg)
Screenshot talking to ALena

**Comment by Soulwhisper** [comment]
Why do you even post it here on bugtracker man? Seriously...have you even read the rules before posting something like this on bugtracker?

**Comment by krisolyub** [comment]
Btw Alena asked for invite to our Russian allyance. But that moment our officers made the decision to refuse invite Alena's guild in Ally. Guilds [Gays of Order] and [Beavers] were the largest russian RVR guilds. Some time late i got ban and full acc wipe for 5 min afk in RVR on clicker (included in my mouse driver, mouse - Razor Naga). After this my guild started decay couse no guildleader. Later another guild leader get ban from Alena. Looks like she want to destroy russian allyance.

**Comment by krisolyub** [comment]
Sry but i cant post on forum :(((

**Comment by Yellowpillow** [comment]
* No offensive, vulgar nicknames. This is applies to both your forum account and any character names.

* No ban evasion. Evading a ban by playing on another account will result in the evasion account being permanently banned. The same applies for allowing a banned player to use your account. Helping a banned player in any way will result in a sanction.

Педик - вульгарное и оскорбительное имя. (Русский ГМ на то и русский чтоб фильтровать такие ники)
Использовал второй аккаунт - банят оба. Такие уж правила.
К сожалению бан вполне соответствует правилам.

Зря сюда написал, это вроде запрещено.

**Comment by Luth-RoR** [comment]
>I cant understand why you again ban my account (Krisolyub) and account of my friend (Vttakk).

Yeah, ofc.
https://www.returnofreckoning.com/forum/viewtopic.php?f=86&t=16848

The bugtracker is only for bugs, you can also write mails to GMs if you can't post on the forums.
If your dynamic IP is blacklisted, you could have restarted your router to get a new one; 5 minutes on google or with the search function of the forum should have had revealed that.

I'm pretty sure that no one asked you to "hack" this server protection, which should be close to impossible for someone who needs to be told how to get a new IP address nonetheless.

An advice to the /8 community: there is a new sheriff in the town and i really advise everyone to read and follow the ToS at last, which worked for the rest of the community for a long time now. 
The times of anomy are over and everyone better gets used to it fast.

Spamming the appeal forum and/or the bugtracker won't save anyone.
