### ISSUE TITLE
SM abilities not going through rotation due to no damage.

### ISSUE THREAD

**Issue by Andrain** [WarEmu/WarBugs#773]
When I use Graceful Strike and Eagle's Flight, if the attack is parried, blocked, or absorbed. The Balance rotation is not set into the next position.

**Comment by Andrain** [comment]
Possibly related, when I enter a Scenario after logging in, Graceful Strike and Eagle's flight is always repalced by Ensorcelled Blow and Throw.

**Comment by Evildoor** [comment]
I do believe that the second problem is not related to the first. It is a long standing issue which sometimes puts your lvl 1 skills into your first skillbar when you enter the scenario, on every class, not only swordmaster. It can be avoided by only using skillbars 2-4, or NerfedButtons.

About the first problem - i can add that if your snaring attack (of any class) gets absorbed, then it does not snares, which is also wrong.

**Comment by ozarmidrashim** [comment]
One bug per report, please. First one is fixed in next.
