### ISSUE TITLE
stat initiative showing cahcne to be crit inccorect

### ISSUE THREAD

**Issue by Bhaals** [WarEmu/WarBugs#7731]
its not showing the value based on initiative alone it takesinto consideration flat crit reduc from renown and gear % aswell , the tooltip appears misleading basically wether its an issue or not idk but was worth reporting

**Comment by Luth-RoR** [comment]
Worked like that on the mythic server too. Maybe the character window/paperdoll can be reworked again in the future (client modification). 
There could be also some addons whowing extended values.
