### ISSUE TITLE
Untouchable 

### ISSUE THREAD

**Issue by Toldavf** [WarEmu/WarBugs#7732]
This ability is currently tripling the users defences instead of doubling them like it should. 

<a href="http://s781.photobucket.com/user/taylorjames07Toldavf/media/Gotrin_007_zpse0cgvmu9.jpg.html" target="_blank"><img src="http://i781.photobucket.com/albums/yy95/taylorjames07Toldavf/Gotrin_007_zpse0cgvmu9.jpg" border="0" alt=" photo Gotrin_007_zpse0cgvmu9.jpg"/></a>

<a href="http://s781.photobucket.com/user/taylorjames07Toldavf/media/Gotrin_006_zpslqxtkcya.jpg.html" target="_blank"><img src="http://i781.photobucket.com/albums/yy95/taylorjames07Toldavf/Gotrin_006_zpslqxtkcya.jpg" border="0" alt=" photo Gotrin_006_zpslqxtkcya.jpg"/></a>

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/2598
