### ISSUE TITLE
Shadowlands Battle Objectives bugged

### ISSUE THREAD

**Issue by asfd123** [WarEmu/WarBugs#7734]
Both Shadowlands objectives are bugged, it's impossible to capture them.

**Comment by Luth-RoR** [comment]
Yes, known. The fix for that can be only pushed on live, when the RvR rework is done, which should be soon™.

**Comment by asfd123** [comment]
It was fine 2-3 days ago, I wonder what happened.

**Comment by Luth-RoR** [comment]
Battlefield objectives are generally bugged since the last patch, there are some reports about this problem.
