### ISSUE TITLE
Welcome Back Order Quests T1-T4

### ISSUE THREAD

**Issue by Jenetia** [WarEmu/WarBugs#7738]
A few days agao a lot new quests popped in Altdorf.
The welcome back quests sends you to every tiers empire warcamp to find an "Griffon Warscout"
but hes isnt in even one of them. But by accident i found one accepting all 4 quests in Northland at 27k,50k. Maybe a copy of him in the emp warcamps would make 4 quests work the expected way.

http://imgur.com/a/1Xp6p

**Comment by Jenetia** [comment]
Maybe an missunderstanding. The "Griffon Warscout" isnt part of the WC defense, he is only á turn-in-point for the quest.(wardb lvl 11 Elite) Not sure the quests are useless, normally the send you in the new tier when hit the lvl requirement and exept for missplaced npc the work.

**Comment by Ryanfawkez** [comment]
Still, we'll have to re-adjust the dialogue, properly scale the levels, add in missing completion text, add progress text, ect. ect.

For now, the issue of these guys being the hand-in NPCs, will be resolved, and the quests will be reworked in the future.

**Comment by Jenetia** [comment]
Sorry to nitpick your decision. Maybe i was a bit to cheery finding an bug with an possible solution. Havent realised the conditions also to be aimed around what i have seen.
I'm really sorry.

**Comment by Soulwhisper** [comment]
This is patched.
