### ISSUE TITLE
[Ironbraker] Axe slam tooltip mismatch

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#7739]
Deals 2400 instead of 1600.

**Comment by Evildoor** [comment]
IIRC, 2400 is a correct value. Maybe you've checked tooltip on an IB who has 0 points in Vengeance? Because 15 points needed to pick Axe Slam increase base damage of all things in Vengeance by 50%, including this morale: 1600 * 1.5 = 2400.

**Comment by Luth-RoR** [comment]
True, thanks. I checked also only the base values in the character builder. :blush:
