### ISSUE TITLE
PQ Spirited Resistance - DE Chapter 10

### ISSUE THREAD

**Issue by dryack** [WarEmu/WarBugs#7741]
Killing Dryads granted Snotling kills, including 25 Snotling Kill achievement.

**Comment by Ryanfawkez** [comment]
Full NPC name please.

**Comment by dryack** [comment]
Sorry about that.  Wrathglade Dryads are giving the Snotling kill credit.  The Dryads _are_ being counted correctly for PQ credit purposes.
