### ISSUE TITLE
Pets 

### ISSUE THREAD

**Issue by Mr0wl13** [WarEmu/WarBugs#7742]
On the white lions and herders Squig petomets disappears after you get on the horse + 60%. I suspect that this is due to the fact that pet rate is increased by only 50%. Can I fix this and make 60% of the speed of the pet?

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/5714

**Comment by Luth-RoR** [comment]
Furthermore: my lion doesn't disappear when i mount up.
