### ISSUE TITLE
RvR after patch

### ISSUE THREAD

**Issue by T3rz** [WarEmu/WarBugs#7744]
[T2] Still don't know other tiers.
The patch solved the previous problems, but now after a zone lock almost all the players of the locking faction gain no XP nor RR nor INFLU.

Thanks

**Comment by kamikaiser** [comment]
I experienced this as well. Went through locking all 3 T3 zones and noticed it looked like I hadnt gained much in the way of xp, rr, or inf. So I made it a point to watch my logs when the locks happened for the next 2 locks and I was gaining no reward at all (xp, rr, or inf) even though I was there for the entire keep take. Basically spent a couple hours locking zones for no gains at all other than what we got from killing some defenders.

**Comment by kamikaiser** [comment]
So i did a little more testing on this. Went into T2, took a keep. Got full rewards no problem. Immediately joined a WB in T3 who had just started on outer door and went to join them. Took the keep and got 0 XP, RR, or Inf rewards for it. Was able to confirm that several others in the WB did not get anything either.
