### ISSUE TITLE
Absorb and capping

### ISSUE THREAD

**Issue by Bhaals** [WarEmu/WarBugs#7745]
i had a bubble on me was being hit with some dots but couldnt cap the ore in one of the SC's , someone told me it was supposed to be the other way around

**Comment by sioding** [comment]
**Thanks for the report.** We need as much information as you can give us for reproducing the bug. That means: when... where... what.. and please ensure that you provide the appropriate evidence, be it in screenshot or video format. 

You can help us by following these bugreport rules: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
