### ISSUE TITLE
rvr getting reward for protecting BO in locked zone

### ISSUE THREAD

**Issue by JeekElemental** [WarEmu/WarBugs#7747]
Eataine was locked to order, killed des in sanctuary of dreams, then 5-10 mins after I received medallion for defending BO. I was no where near BO when got reward (orkwerks PQ). Assume that's not intended?

**Comment by Luth-RoR** [comment]
According to the big RvR masterplan:

**Comment by Luth-RoR** [comment]
According to the big RvR masterplan, BOs should be linked to area quadrants now, so that people don't have to crowd at BOs in fear to loose any rewards.
I don't know if this has been pushed with the partial rework, but i guess so.

Needs dev confirmation.

**Comment by JeekElemental** [comment]
Aha, that explains the distance. To clarify tho, the zone was locked, the BO was not in play (no guards).
