### ISSUE TITLE
Engi pull 

### ISSUE THREAD

**Issue by Bhaals** [WarEmu/WarBugs#7748]
hi during keep siege in praag today i got pulled into a wall i actually dont know what did it but the enemy as making its way in through the doors i did not see any engineer position himself against a wall at the bottom of our ramp that was decently populated ; i remember this same exact thing being cried about on live in the first months

**Comment by Bhaals** [comment]
so i mean he palced it outside the wall , pls look into this

**Comment by Luth-RoR** [comment]
Screenshot?

**Comment by sioding** [comment]
fixed
