### ISSUE TITLE
global cool down

### ISSUE THREAD

**Issue by vithoria** [WarEmu/WarBugs#775]
global cool Down is to long compared to the build up abillitys "cast time" GBC should be 1 sec
and should not be affecting morales

**Comment by Thorgatin** [comment]
Global cooldown was always 1.5 seconds in WAR, from the beginning till the end.

**Comment by vithoria** [comment]
well then, GBC shouldn't effect aballitys that have cast time, look dok and WP abillity that 0.5 sec cast time

**Comment by Thorgatin** [comment]
These abilities have only a short cast time, so that they can't be cast while moving around.

**Comment by ozarmidrashim** [comment]
Please do not post here if you don't know what you're talking about.

The client's word on the GCD is law. If you see the GCD effect on the client, that means the given ability triggers the GCD. The duration of the GCD is fixed by the client and is 1.5 seconds.
