### ISSUE TITLE
Keep loot chest shouldn't appear if there is no loot rewards

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#7755]
After a successful attack of the keep there was no loot rewards because of the small number of defenders opponents. Nevertheless, there was a chest, I'm sure it should not be in the absence of bags rewards.
![arena_097](https://cloud.githubusercontent.com/assets/18102127/18497008/fa530410-7a3b-11e6-929d-3eef7a436889.jpg)

**Comment by Luth-RoR** [comment]
I guess this can't be solved differently atm.
