### ISSUE TITLE
dwarf chapter 9 need more 55 lvl guards inside

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#7758]
After i done taking unlock for quest i mentioned that i can go insige dwarfen camp. Only few mobs attack me and they fail. 
I guess there should be another 55 lvl guardian. But he not suppose to lock that dwarfen cave, so destro-players can still get unlocks.
![arena_088](https://cloud.githubusercontent.com/assets/18102127/18497424/2cd30a36-7a3f-11e6-925f-ed026f9c5dab.jpg)
![arena_089](https://cloud.githubusercontent.com/assets/18102127/18497425/2cd36292-7a3f-11e6-8353-964d5faf504c.jpg)

**Comment by Soulwhisper** [comment]
This is patched.
