### ISSUE TITLE
Mourkain Temple...being punted to higher gorund and res rune of RP

### ISSUE THREAD

**Issue by lawfol** [WarEmu/WarBugs#7759]
I had apsecial moment in the Mourkain Temple.
First I was punted while holdingthe bubble up one of the erected stones...only reachable by ranged dps. 
After the dps and the bubble killed me (I am a WP,s opretty tanky) the RP in my party used the res rune ressing everyone near him.
So I was still on the pillar and picked up the bubble.
Shortly after that I was punted off the pillar by soem greenskin jumping up and down to get me in range.

I do not know if that is a bug of any sort,but it can be worth looking in the matter.

**Comment by Luth-RoR** [comment]
And what may be the bug here?
