### ISSUE TITLE
[Keep Loot] Reward with no contribution

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#7761]
Just now (Sept 14, 2016 ~20:15 GMT) when destruction took Karak Dammaz in Kadrin Valley, I managed to place 14th on the scoreboard (and got a bag). The problem is that I had not been in Kadrin Valley on the character for several days, and was in the middle of Avelorn farming. I had taken part in the earlier attack on Karak Karag in Thunder Mountain. I am very confused as to why I got this bag.

Edit: it should be noted that I had previously been in the warband that took KV, but I had left shortly before they went there. I had been in this warband during the take of Thunder Mountain

![kesserac_003](https://cloud.githubusercontent.com/assets/13975292/18528765/ef58660a-7a8f-11e6-8ec5-3eedf6e8479d.jpg)

**Comment by runebbb** [comment]
got it when i was in SC something is wrong with it and same with getting medalions for BO caps in Warcamp

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
