### ISSUE TITLE
Karaz Blade don't contain talisman slot

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#7766]
Karaz Blade is a Sword Master's reward for RvR influence in T2, it should contain talisman slot, but it didn't.
![tranquillity_007](https://cloud.githubusercontent.com/assets/18102127/18536267/d107815e-7b0c-11e6-8bd8-28cf847fa5ce.jpg)

**Comment by Soulwhisper** [comment]
This is patched.
