### ISSUE TITLE
Grearsword of Thunder missing talisman slots

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#7767]
Grearsword of Thunder is a Sword Master's reward for RvR influence in T2, it should contain 2 talisman slots, but it didn't.
![tranquillity_008](https://cloud.githubusercontent.com/assets/18102127/18536304/45e8aebc-7b0d-11e6-8317-e0e6539e3088.jpg)

**Comment by Soulwhisper** [comment]
This is patched.
