### ISSUE TITLE
Spite's Blade missing talisman slot

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#7768]
Spite's Blade is a Sword Master's reward for RvR influence in T2, it should contain talisman slot, but it didn't.
![tranquillity_009](https://cloud.githubusercontent.com/assets/18102127/18536346/a162168e-7b0d-11e6-92c8-e7087e21f158.jpg)

**Comment by Soulwhisper** [comment]
This is patched.
