### ISSUE TITLE
Spite's balancers missing a talisman slot

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#7769]
Spite's balancers is a Sword Master's reward for RvR influence in T2, it should contain talisman slot, but it didn't.
![tranquillity_006](https://cloud.githubusercontent.com/assets/18102127/18536369/d5a6c0f2-7b0d-11e6-8824-b33f93284882.jpg)

**Comment by Luth-RoR** [comment]
DB devs are aware of the issues; they will rework them soon™ afaik.

**Comment by Yellowpillow** [comment]
okay, just trying to do my best and report whatever i find.

**Comment by Ryanfawkez** [comment]
Luth, items that should have a talisman slot can be reported at any time. Stats are not an issue being reported here :P

**Comment by Soulwhisper** [comment]
This is patched.
