### ISSUE TITLE
Roll bug

### ISSUE THREAD

**Issue by Gintofag** [WarEmu/WarBugs#7771]
Today we def keep in Praag and there our roll on chest. Somthing strange i think.
http://i.imgur.com/T9dp90E.jpg

**Comment by Soulwhisper** [comment]
Yeap this happened before for another Keep.Its a specific bug.Thanks for reporting it.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
