### ISSUE TITLE
merchant/shop decided to join me

### ISSUE THREAD

**Issue by runebbb** [WarEmu/WarBugs#7772]
![sirren_009](https://cloud.githubusercontent.com/assets/20157418/18554631/16277200-7b65-11e6-810f-2b318d63b3b7.jpg)

**Comment by Luth-RoR** [comment]
Probably the same issue: https://github.com/WarEmu/WarBugs/issues/7292

**Comment by runebbb** [comment]
yeah seems so but didnt find anything when i searchd for it :)

**Comment by Luth-RoR** [comment]
Closing due to main report for this is: https://github.com/WarEmu/WarBugs/issues/7291
