### ISSUE TITLE
mob error in blind justice

### ISSUE THREAD

**Issue by runebbb** [WarEmu/WarBugs#7773]
![sirren_008](https://cloud.githubusercontent.com/assets/20157418/18554743/82540d3a-7b65-11e6-8846-d66a87c05de8.jpg)

**Comment by Luth-RoR** [comment]
Unfortunately i fail to see what's wrong here after studying the picture for about a minute. Clarification needed, as _mob error_ could mean anything.

**Comment by runebbb** [comment]
elfs counts as snotlings as u se in the beastary unlock

**Comment by runebbb** [comment]
was the same in the pq of furnace just need to re-assign mob name to elf instead of snotlings :) dont wanna insult the snotlings ;)

**Comment by Ryanfawkez** [comment]
It's not mob name, it's subtype. I need exact Elf NPC names that have this subtype currently.

**Comment by Ryanfawkez** [comment]
Alright, fixed the Shimmerknight Captain and Banildror the Wise subtypes. Would like the names of the other Champions at this PQ, and hero, as I assume they suffer from the same issue.

**Comment by runebbb** [comment]
sure i will take a look at it later today

**Comment by Soulwhisper** [comment]
This is patched.
