### ISSUE TITLE
oil blocks all melee attacks

### ISSUE THREAD

**Issue by runebbb** [WarEmu/WarBugs#7775]
![sirren_003](https://cloud.githubusercontent.com/assets/20157418/18555141/07bf3214-7b67-11e6-918a-1b82a819bcde.jpg)
![sirren_004](https://cloud.githubusercontent.com/assets/20157418/18555145/0b2b9ab4-7b67-11e6-8905-d16fc6bb4c54.jpg)
it also goes on throws from melee tested with WE and Chosen 100% block

**Comment by Luth-RoR** [comment]
Probably working as intended (partial RvR overhaul). Needs confirmation from developer.

**Comment by runebbb** [comment]
well its wierd that it blocks attacks when ur physicly hitting on it i mean like in a real situation it would be alot quiker to destroy it/sabotage it if u where on it instead of useing magic/shooting arrows on it so its abit wierd :p but if it works as intended i guess stilll seems as a bug though

**Comment by Soulwhisper** [comment]
#6783

**Comment by Luth-RoR** [comment]
Thanks.
