### ISSUE TITLE
Guild cloak available to early

### ISSUE THREAD

**Issue by LordMort** [WarEmu/WarBugs#7777]
RoR Server: Martyrs Square
Version 1.4.8 Build 573

Hi there,

I have notices the following regarding guild cloaks:
Usually the ability to wear / display a guild cloak instead of your own / standard cloak becomes available at guild rank 15 (see description in the screenshot hereafter):
![gottrekson_150](https://cloud.githubusercontent.com/assets/21020953/18559278/e3cc71e0-7b76-11e6-9a9d-dee3cfe2ada3.jpg)

What I found is that it is actually possible to wear / display guild cloaks as early as guild rank 1, because the option for this is available at that time already in the character winwo (see screenshot):
![gottrekson_151](https://cloud.githubusercontent.com/assets/21020953/18559372/4609a6c0-7b77-11e6-8d9f-9255add17554.jpg)

In my case the guild is on rank 10, but checking this option already let's me display the guild cloak (see screenshot):
![gottrekson_152](https://cloud.githubusercontent.com/assets/21020953/18559417/6d1cdbf6-7b77-11e6-8b31-e21dd813056b.jpg)

I don't know whether or not this is the case, but potentially this could also influence the guild heraldry, as talked about in issue #7776 .

**Comment by geezereur** [comment]
I notice the same thing with my Guild but you are the only one that can see the guild cloak other people cant.

**Comment by Luth-RoR** [comment]
Ok, thanks. Then it's working as intended i guess.
