### ISSUE TITLE
NPC 'Longbeard Hjolfersson' and his 'Redmane Overseer' buddy are spawned thrice

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#7779]

**Comment by Ryanfawkez** [comment]
Redmane Overseers have 16 spawns, this seems to be intended. Hjolfersson himself is spawned 4 times around the Destruction area in Greenskin Chapter 15. Will remove those.

**Comment by avenflar** [comment]
Yep, but he is accompanied by an Overseer each time. So I guess to have it clean you'd need to remove the 3 superfluous Overseers I guess.

**Comment by Soulwhisper** [comment]
This is patched.
