### ISSUE TITLE
Bug Scenario Serpent's Passage

### ISSUE THREAD

**Issue by Crisiteck** [WarEmu/WarBugs#7783]
Hi, 
Hope you are doing well. 
I just would like to report a bug that I noticed earlier today. 

To make long story short: 

In the Serpents's Passage scenario, 
Once you capture the objective, and back to base to tag and get 75 points for your team. 
If you cancel the casting time by moving during the animation and restart the "tagging" process instantaneously to get the points, you can actually tag twice and get twice more points for your team (150 points). 

Hope that will be helpful! 
Thanks for the work and this great game. 

---

P.S. I know it is out of topic, but I was thinking about something that, for me, would add lot of value to the game: 
I think it will be good to be able to "save" 2 or 3 specialization trees instead of 1, specially for casual player like me which dont have much in-game ressources and have to spend 1 or 2 gold each time we want to change our play style. 
I think it would be also good for other player so they can develop further other play style on a same character, or be able to fit better in team or WB depending on the needs.
Let's for example imagine that you can only switch between one of the 3 pre-made specializations in the bivouac in RvR zone by talking to a PNJ, and not only in the capital by spending 2 gold. 

Take care, 
Xxx

**Comment by bloodi** [comment]
#7032 

Also, its not just twice, you can win the scenario with just 1 ball.

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=18653
