### ISSUE TITLE
WH Tactic

### ISSUE THREAD

**Issue by Stopcast** [WarEmu/WarBugs#7785]
WH tactic "Encourage Confession" no work , and disarmament does not impose irresistible in live.

**Comment by Luth-RoR** [comment]
Okay.

1. Only one bug per report.
2. Evidence?
3. On "issue 1": I wonder how you _found this out_ (see the attached pictures). 
4. On "issue 2": I guess you mean that the the 4 second disarm should not give any immunity. 
I won't explain here why this would be complete bullshit from a balancing perspective nor am i going to search the internet to find any evidence for you.
5. The bugtracker is no place for half-assed assertions or wishlists
6. Read the bugtracker rules.

![luluth_000_crop](https://cloud.githubusercontent.com/assets/8567481/18587402/2877005c-7c22-11e6-91d9-178b1c84f103.jpg)
![luluth_001_crop](https://cloud.githubusercontent.com/assets/8567481/18587408/2d75831c-7c22-11e6-9553-eb4f074ebf15.jpg)
