### ISSUE TITLE
instant rank 40 from level 1 from t1 zonelock

### ISSUE THREAD

**Issue by FrenzikBludkraze** [WarEmu/WarBugs#7786]
So i logged into my level 1 ironbreaker, Garam, and walked into the rvr lake. Zone locks. Instant rank 40, renown rank 7.

**Comment by FrenzikBludkraze** [comment]
![garam_001](https://cloud.githubusercontent.com/assets/22234872/18581903/e89ef92c-7c02-11e6-8a19-4aa946ca5c59.jpg)

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
