### ISSUE TITLE
dark protector cap fail

### ISSUE THREAD

**Issue by Bhaals** [WarEmu/WarBugs#7787]
couldnt snag u a ss but in the logrins forge sc i took off gaurd from a dok, he had  dark protector buff and i ninja capped the forge vs 2 heal classes as they were focused on the dok originally ninja capping and it finished its cast bar but nothing happaned the RP i had eyes on was standing there and the archmage was  dps trying to kill the dok /shrug

**Comment by Luth-RoR** [comment]
If the castbar is complete on the client, it isn't necessarily on the server. This can't be often seen when one wants to mount up and the bar is full, but the mount did not yet appear; if you start walking too early (even if the bar is full), the mount won't be summoned.
