### ISSUE TITLE
unable to log while in Sigmar's Hammer

### ISSUE THREAD

**Issue by BillyMays1** [WarEmu/WarBugs#7789]
Yesterday, I Logged out while in Sigmar's Hammer and now today I tried to log in and the game crashes while loading Sigmar's Hammer. I never make it into the game, just the loading screen for Sigmar's Hammer.

Update, after around 15 tries I finally logged in.

**Comment by Elvenalthur** [comment]
If you're ever "stuck" during the loading screen, try typing /stuck twice during the loading screen. It works nearly every time.*

*Subject to excluding bugged characters that prevent loading the character from the DB.

**Comment by Luth-RoR** [comment]
Known issue with guild taverns. https://github.com/WarEmu/WarBugs/issues/7649
