### ISSUE TITLE
Lost a keep defense in T2, didn't get rewards even as it says our realm won some points for the effort.

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#7791]
I wasn't AFK but we were overnumbered and thus we couldn't do much but grab a few kills when the enemy attacked the Lord after taking potshots from the walls during the door hitting.

So is it an issue of simply not doing enough to count as 'contributing'? It defeat a bit the purpose of the buff if it is :(

**Comment by Luth-RoR** [comment]
The details of the contribution mechanic are kept secret (that means i don't know them too, so please no PMs to me from anyone regarding this). 
It's a work in progress and is fine tuned continously; i think this is more a case for the forum, if it needs discussion.
