### ISSUE TITLE
T1 Dwarf basic reward Item 'Stonemine Bloodwades' has Str instead of Will, when item 'Cannoneer Bloodwades' is the Str 'set'

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#7792]

**Comment by Torquemadra** [comment]
and? doks need str for melee attacks

**Comment by avenflar** [comment]
Oh crap sorry, I forgot to add that's it's the T1 Dwarf basic reward, and that the 'Cannoneer Bloodwades' are the one 'set' giving Str.

**Comment by Torquemadra** [comment]
thanks
