### ISSUE TITLE
Guild Heraldry no warning cost

### ISSUE THREAD

**Issue by NorKalli** [WarEmu/WarBugs#7793]
I set my guild heraldry, it warned me it was going to cost "1 17098" and I clicked accept, assuming it was free to set-and it took 500 gold from me. Would it be possible to refund my gold?

**Comment by NorKalli** [comment]
Also, my banner is invisible. When I mount with it and jump, my character flies off his mount.

**Comment by Luth-RoR** [comment]
On number 1: the different costs are an intended RoR feature to prevent people from changing the banner like their underwear. No bug, support requests go to the forum/GMs.
On number 2: I don't know what is exactly meant here, but standards are a very basic feature atm, barely working at all (this is knownto the devs).
Only one issue per report please.
