### ISSUE TITLE
Taunt

### ISSUE THREAD

**Issue by Bhaals** [WarEmu/WarBugs#7797]
according to my addon taunt stacks are being eaten by mob auto attacks
http://imgur.com/a/zUyJ8
http://imgur.com/a/c01Pw

**Comment by Bhaals** [comment]
also unsure but might not be effecting auto attacks i did some quick math check but its been ages

**Comment by ozarmidrashim** [comment]
1360 Taunt
You enrage your opponent, interrupting any currently building abilities and forcing monsters to attack you. While taunted your opponent will take 30% more damage from your attacks. This effect will fade after 15 seconds or after your opponent has hit you 3 times.
