### ISSUE TITLE
Quest - Call of the hunt

### ISSUE THREAD

**Issue by poutpoutt** [WarEmu/WarBugs#7799]
Aethlys Dreamsong doesn't appear on radar (no red zone) whereas the other High elf you have to kill does have a killing zone.

**Comment by Luth-RoR** [comment]
Referring to https://github.com/WarEmu/WarBugs/issues/4797

**Comment by Ryanfawkez** [comment]
Multiple quest markers, as they are called, are not yet supported.

**Comment by Luth-RoR** [comment]
Closing this because https://github.com/WarEmu/WarBugs/issues/8048 has updated info.
