### ISSUE TITLE
Rooting out Corruption Quest bug

### ISSUE THREAD

**Issue by Mefra** [WarEmu/WarBugs#780]
T2 Troll Country, Completed quest but choice of loot does not show in inventory

**Comment by Evildoor** [comment]
I did this quest several times on different characters (WH, Slayer, KotBS, SM, etc), had no problems. Can you specify the class of your character?
Side note - this quest has different problem for now (https://github.com/WarEmu/WarBugs/issues/1243), so it cannot be completed.

**Comment by Reggaewaldo** [comment]
Tested the quest for loot but no issue there. Closing this one and keeping #1243 open instead.
