### ISSUE TITLE
Quests do not appear in ToK

### ISSUE THREAD

**Issue by Toriaz** [WarEmu/WarBugs#7803]
Hello, on my character Barbaak, I took some quests but they do not appear in the ToK page (see screenshot).
I tried deleting all the quests I could see in the ToK in case it was an issue of having too many at the same time but it does not solve the issue. Also this is not fixed by a server reboot.
Could you please help me out?
Barbaak
![barbaak_006](https://cloud.githubusercontent.com/assets/21013785/18608407/98b447f0-7ce8-11e6-8fad-0aec4d3db4de.jpg)

**Comment by Luth-RoR** [comment]
Referring to https://github.com/WarEmu/WarBugs/issues/7803

**Comment by Toriaz** [comment]
Hello, do you need any additional information?
I was able to pick up on the Annihilation quest with a guildie, and it enabled me to proceed with the quest (and it was present in the book) but on the following log-in the quest wasn't there anymore.

**Comment by Luth-RoR** [comment]
I don't know what's causing this to happen, but iirc someone mentioned it only happens to newer accounts.

**Comment by Toriaz** [comment]
Hello, FYI, some quests came back, some didn't, hope this helps... :P

**Comment by Toriaz** [comment]
Hello, can't take any new quests with the same character despite having abandoned all the quests that are visible in the ToK. Can't do the live event :(
Any way to go around this?

**Comment by Luth-RoR** [comment]
I asked on the teamchat but atm there is no solution for it unfortunatelly.

**Comment by Toriaz** [comment]
WuT? :) Fixed, dunno what you changed but am able to view all my quests :)

**Comment by Luth-RoR** [comment]
Maybe a silent fix. :smile:
