### ISSUE TITLE
Mercenary set cost for Destruction

### ISSUE THREAD

**Issue by Thaligon** [WarEmu/WarBugs#7805]
Oder side costs for helm is 80 tokens and 150 tokens for boots, while Destro has to pay 150 for helm and 80 tokens for boots meaning destruction players have to pay 70 more tokens for full mercenary set, becose you can buy boots/gloves for gold.

**Comment by Torquemadra** [comment]
they are 150 both sides, they were changed recently so the items that dropped were the cheapest to buy.
