### ISSUE TITLE
1000 Pegasus Kills, Cloak Unlock Not Working

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#7807]
Hello, I've just spent the last 3 days killing 1,000 pegasi to obtain the Cloak of the Pegasus. Well my Tome of Knowledge has acknowledged the kills, but sadly the unlock is not showing the cloak item in my ToK, and in the library there is nothing waiting for me to collect *sad face*. My character is Senthoi, Shadow Warrior. Account name is Senlui.

**Comment by Ryanfawkez** [comment]
You should be able to buy the Cloak of the Pegasus at the library vendor Mandred Vogt, regardless of what the ToK reward says. Try again.

**Comment by Senthoi** [comment]
Dear Ryan,

Thank you it has worked! Absolutely delighted, you've made my week!

Kind regards,

Sen

Get Outlook for Android<https://aka.ms/ghei36>
