### ISSUE TITLE
"The Howler" title unlock not working

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#7808]
Near Dreamshade and The Watchtower PQ on the cliff top on the Blighted Isle (Destruction side 4k, 49.8k), you get a tome unlock for "The Howler" title when walking through this area. At the moment this is not working. Have tried multiple spots a few times just to be sure. Further details of this tome unlock are here 
[http://warhammeronline.wikia.com/wiki/View_With_a_Howl]

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/5096
