### ISSUE TITLE
NEW! Kick to Char Menu after SC

### ISSUE THREAD

**Issue by AirIBreathe** [WarEmu/WarBugs#781]
So, I`ve got a simmilar thing as guy with the same topic name BUT, there is no solution in my case.
Today Ive leveled up from 12 to 13 lvl, then I`ve accepted a scenario Gates of Ercund. I`ve bacame a chicken cause of lvl, but in scenario was 13 lvl chars and 20 lvls are okay. So, Ive decided to leave it. 
Exit was not working due to of some error, scroll book didnt worked too, then I just logged out.
After all Iam unnable to enter in any location. PC allways says my char In Gates of Erkund location and he wanna drop me there, but only place Ive dropped is - char select menu in th end. 50 min passed for shure from the begginning of the scenario and I cant get in.

**Comment by ozarmidrashim** [comment]
Use /stuck while loading

**Comment by Evildoor** [comment]
^
