### ISSUE TITLE
High Elf Chapter 2 - Thanalorn Forest PQ

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#7810]
Hello, I know you're working through things at the moment and you're doing a terrific job! So you're probably aware that the Thanalorn Forest PQ is not working. No influence appearing, nor kills appearing on the PQ counter.

**Comment by Soulwhisper** [comment]
Hello and thanks for reporting.Database Developers are aware of the PQs that are not implemented/not working at all at the moment.So no need to report PQs which dont work at all.If you find bugs in some working PQs then report them! Thanks again!

**Comment by Senthoi** [comment]
Thanks Soulwhisper!

I had only found out about Bug Reporter yesterday, and learned that the old bug report isn't working in the game! That'll teach me to read the forums more. Cheers for this information. Many thanks,


all the best Sen


________________________________
