### ISSUE TITLE
lair boss wall hax

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#7811]
it appears that if a lair boss (only tested in t1 where kite style fighting is used more often) dies while passing through a piece of terrain, 5/6 (or just one less than however many you have) party members will be able to see its corpse sticking out of said terrain, but none of them will be able to loot it, and the one person who cannot see the corpse will be the person who is supposed to loot it, therefore meaning that the party gets no loot

this has now happened to me in both the dwarf and elf lairs in t1, on both occasions the boss died while partially concealed in a rock, one person on the team was unable to see a corpse, and thus there was no loot (and it was me that couldnt see the elf lair bosses corpse so i know it wasnt just someone trying to scam the team out of the drop)

**Comment by iamjamoca** [comment]
Heya, where you in my group, I believe.
Agero here (WL)
https://github.com/WarEmu/WarBugs/issues/7815

**Comment by Luth-RoR** [comment]
One report for the same issue is enough.
NPCs movement is not yet completely implemented; the devs develop a tool atm to handle NPC movement better in the future; Until then, this can't be fixed.
