### ISSUE TITLE
Engi helmet for a zealot

### ISSUE THREAD

**Issue by braingunk** [WarEmu/WarBugs#7814]
I went to go buy ruin shoulders for my zeal, but once I did that, it turned into an engi helmet.
I'm not sure if this happens to any other pieces of armor, since I only bought the shoulders.

![boogey_001](https://cloud.githubusercontent.com/assets/22270680/18613434/bc4bae8c-7d2f-11e6-9926-1bc62ec47bf1.jpg)

**Comment by Luth-RoR** [comment]
Could not be reproduced on the live server; Maybe DB loading issues.

**Comment by Luth-RoR** [comment]
Ok, as the vendor shows all items for both factions (with filter settings off) this was probably caused by misclicking.
