### ISSUE TITLE
Tome Trophy Unlock broken "Soul Catcher"

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#7816]
In Praag on order side, beneath a waterfall is a lvl 39 wraith named Gloomveil (approx 22000, 53000). Killing this this mob unlocks the set ring Foserain from The Sundered Rings set. I've killed this mob and my ToK is showing that I've done this, but the item unlock is not showing, and there's nothing in Altdorf library.
![soul](https://cloud.githubusercontent.com/assets/22262165/18614585/c8a84a92-7d88-11e6-80f3-701c7cde3e96.png)

**Comment by Luth-RoR** [comment]
I just did the quest on the dev server and took _Foserain_ from Manfred Vogt.

**Comment by Senthoi** [comment]
Thank you Luth, I will try this later today.


kind regards,


Sen


________________________________
