### ISSUE TITLE
Witch Elf stucked stances

### ISSUE THREAD

**Issue by gulde** [WarEmu/WarBugs#7817]
Just noticed, that WE's battle stance (that crouching) stops displaying right after I use Enslaved pack mule. After that, during the combat after each hit WE returns to the ordinary stance (just like when Iam standing still and off the battle), which, given to the circumstances, doesn't look good at all. 
Another stuck happens when I use command '/special'. It just stucks and that energy orb is still on my hand no matter what Iam doing.
Both problems are solved after reloging.

**Comment by Luth-RoR** [comment]
Only one bug per report please.
On 1: what does _WE's battle stance (that crouching)_ mean?
On 2: well known client side bug.

**Comment by gulde** [comment]
![witch_elf_ss](https://cloud.githubusercontent.com/assets/22275274/18616307/baf606a6-7db9-11e6-88c6-c23b21e6365d.jpg)
something like that (illustrational only), but instead, she just stands still, then attacks and standing still again.

**Comment by Luth-RoR** [comment]
Ok, i tested it on the devserver. The animations are not fluid anymore after dismounting, the idle animation activates too early after executing a different animation.
Both issues are handled clientside and can be fixed until the client can be modified.
