### ISSUE TITLE
Quest: Goldenwing Eyas

### ISSUE THREAD

**Issue by gulde** [WarEmu/WarBugs#7819]
During the Dark Elves quest Goldenwing Eyas in Blighted Isle (near Poisoblade Heath), you are suppossed to kill wolves, take their meat and feed three Goldenwing eagles with it. Problem is, that these three eagles are always attacked by all eagles arround and killed. After that you have to wait for respawn and quickly interact with them, otherwise they'll be killed and you'll have to wait again. Quest is possible to finish anyway, but doesn't feel good that way.

**Comment by Luth-RoR** [comment]
Known: https://github.com/WarEmu/WarBugs/issues/4600
