### ISSUE TITLE
Swords for Witch Elfs by renown gear merchant

### ISSUE THREAD

**Issue by gulde** [WarEmu/WarBugs#7822]
By the renown gear mechant there are also swords besides daggers in his offering. But for a Witch Elf, weapon type (sword in this case) is not shown shown in red, indicating that I am not able to use it. I think, that there shouldn't be swords even shown as an offer (I think that it should show only things I can wear).

**Comment by Ryanfawkez** [comment]
That's because they are still Dark Elf weapons without a Blackguard/Disciple of Khaine class restriction.

**Comment by sioding** [comment]
fixed with patch 21.10.2017
