### ISSUE TITLE
Mourkain temple Bug 

### ISSUE THREAD

**Issue by ninjau** [WarEmu/WarBugs#7823]
If you pick up the idol and hold it up on the hill near your spawn if you die your team can pick it up before they drop down to RVR and therefor win

**Comment by Luth-RoR** [comment]
The sc mechanic prevents any points, if people decide to walk back to their spawn with the buff.

**Comment by ninjau** [comment]
Not if you stand at the edge of the camp it will give you points and melee
dps cant get close enough to hit

**Comment by Luth-RoR** [comment]
Ok, needs evidence then.

**Comment by ninjau** [comment]
somebody has a screenshot of me holding it up there forgot the name will
try to find it

**Comment by ninjau** [comment]
ask gyrmn for the screenshot

**Comment by Evildoor** [comment]
#2547?

**Comment by Luth-RoR** [comment]
Gonna close this + trying to get some info how it works atm. Iirc if one faction camps the other at the spawn, the sc should be over very fast nonetheless.
