### ISSUE TITLE
Harbinger of doom doesn't convert int, spell power etc. into healing power, willpower etc.

### ISSUE THREAD

**Issue by Tosher85** [WarEmu/WarBugs#7825]
![serpento_000](https://cloud.githubusercontent.com/assets/20247320/18619465/e1df8f98-7e05-11e6-99a8-6fe36848fcef.jpg)
![serpento_001](https://cloud.githubusercontent.com/assets/20247320/18619467/e62a7914-7e05-11e6-86d4-60c988d615ac.jpg)

**Comment by ozarmidrashim** [comment]
https://github.com/WarEmu/WarBugs/issues/1894
