### ISSUE TITLE
Absorb Potions Unusable

### ISSUE THREAD

**Issue by georgehabadasher** [WarEmu/WarBugs#7830]
I've tested and confirmed the following potions are unusable and can send them to devs on Order for confirmation if necessary.

Lasting Protecting Potion
Fleeting Protecting Potion
Lasting Aversion Potion
Fleeting Aversion Potion

I haven't tested any other absorb potions, but I suspect they're also unusable.

**Comment by Luth-RoR** [comment]
Not implemented due to design decissions atm. Not a bug. https://github.com/WarEmu/WarBugs/issues/1577
