### ISSUE TITLE
Bug in chaos cap.2

### ISSUE THREAD

**Issue by Xinohp** [WarEmu/WarBugs#7831]
forgive but I did not know, was that he was alone in chapter 2 chaos and time to kill tonas jorgen pulled him to the characters in thrall raven and died, the problem is it was not me who killed him but the npc and not conto for the mission, therefore it has been frozen at that point.

I hope you can fix it

I apologize for the inconvenience.
![gromkhal_000](https://cloud.githubusercontent.com/assets/22294257/18645356/c1a78678-7ea4-11e6-82f1-e21a0bc3feb9.jpg)

**Comment by Xinohp** [comment]
and two days xD

**Comment by Luth-RoR** [comment]
It's not your fault, nothing you need to apologize for. 
It's a known problem: https://github.com/WarEmu/WarBugs/issues/4853
