### ISSUE TITLE
Items can't be removed from bank

### ISSUE THREAD

**Issue by Swarmofseals** [WarEmu/WarBugs#7832]
Ran into a strange one today. On my character, Grumpbot, I cannot take items out of the bank. When I drag and drop into my backpack I get a "do you want to destroy?" prompt as if I were dragging and dropping into thin air. Things I have tried:

1. Moved bank and backpack windows around.
2. Disabled all addons and /reloadui. This removed the destroy prompt, but when I drag and drop nothing happens.
3. Restarted WAR (addons still disabled). Destroy prompt is back, still does not work.
4. Switched to a different character (Margrav). This character can use the bank just fine.
5. Switched back to Grumpbot, still get the destroy prompt. 
6. Tried using different bank tellers. no change.

I have tried moving various different items and all get the same destroy prompt.

EDIT: I found that i could move items around within the bank and within my backpack with both open, and then I tried depositing and immediately removing an item. That worked, and then after I did that I could remove other items as normal. Very strange.

**Comment by Luth-RoR** [comment]
Maybe some temporary DB issue.
