### ISSUE TITLE
Quest: A Tight Spot

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7834]
Realm: Order - Empire
Region: High Pass
Quest Giver: Adelbert Bohm at Chap10
Target Coordinates: 04k/04k at Badlands
Subject: Speak to Brudig Stouthelm
NPC: Brudig Stouthelm

Problem: The mentioned NPC is located inside Mount Gunbad, which has not been implemented yet. In addition to that the quest marker for target area on the map is missing.

![2](https://cloud.githubusercontent.com/assets/18719012/18867570/0d947f2c-84a5-11e6-822c-5ec6c5e6748a.jpg)

![1](https://cloud.githubusercontent.com/assets/18719012/18867573/12309110-84a5-11e6-940f-f4430750a95f.jpg)

![3](https://cloud.githubusercontent.com/assets/18719012/18867579/17fa22be-84a5-11e6-9730-de19eaa3ac33.jpg)

![4](https://cloud.githubusercontent.com/assets/18719012/18867586/1dc0ac90-84a5-11e6-9da2-0e89569cd618.jpg)

**Comment by Ezella** [comment]
Similar issue like #7835

**Comment by Akenatoth** [comment]
Beudig Stouthelm can be found in dwarf ch 11 in the Badlands. He has the yellow hand-in marker but nothing happens when talking to him.
![adhelm_001](https://user-images.githubusercontent.com/35481383/38262215-70e83bf4-3764-11e8-8920-09b90f3b952a.jpg)

**Comment by sioding** [comment]
fixed with patch from 08.10.2018
