### ISSUE TITLE
Quest: An Army Marches

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7836]
last step of the quest line ('kill magus of fate'):
target area not shown on the right spot of the map. area should be around 13k/49k at high pass

**Comment by Ryanfawkez** [comment]
Wrong. The Magus of Fate has a double spawn; one at the quest marker and another at 13k 49k. Will remove the spawn at 13k 49k.

**Comment by Ezella** [comment]
ok. will double-check next time before posting. sorry for the confusion

**Comment by Soulwhisper** [comment]
This is patched.
