### ISSUE TITLE
PQ Marsh Conquest - wrong description

### ISSUE THREAD

**Issue by gulde** [WarEmu/WarBugs#7837]
PQ Marsh Conquest in Marshes of Madness shows apparently wrong description, because during a play as a black orc (thus destro), it mentions that Rok lobbers and greenskins has to be destroyed.
![steroid_002](https://cloud.githubusercontent.com/assets/22275274/18649897/56f03e06-7ec2-11e6-8560-708ab8226531.jpg)

**Comment by Luth-RoR** [comment]
They high likely don't have to be destroyed, but fired (clicked); Also: https://github.com/WarEmu/WarBugs/issues/7486

**Comment by gulde** [comment]
"Clear the greenskins" doesn't seem proper, if Iam playing as a greenskin/Destro.

**Comment by Luth-RoR** [comment]
Needs confirmation how the quest should work then.

**Comment by gulde** [comment]
Don't exactly remember how this PQ worked on an official server, but according to this description, it looks more like it is taken from a PQ from Order side (=clear out greenskins and destroy their warmachines). 
On the other hand it also may be understanded like it is a some sort of a dispute between greenskin clans (which would be not surprising, according to the nature of the greenskin species). But in this case it would be quite weird, because Orcs around these warmachines (catapults) are friendly to you, which doesn't seem logical, if you are to destroy their catapults.
Thats my point of view

**Comment by Luth-RoR** [comment]
Yes, maybe only the text is wrong and the catapults have to be fired on some dwarfs.

**Comment by Soulwhisper** [comment]
#7486

**Comment by poutpoutt** [comment]
Firing the catapults on dwarfs does not work for completing the "rock lobbas" part of the PQ!

**Comment by wargrimnir** [comment]
This is a dual faction PQ. This bug just means that the current description is set to the wrong faction. We did figure out how to implement this, it just takes some time.

**Comment by grunbag** [comment]
it seems the pq are operational, someone already fixed this ticket
