### ISSUE TITLE
Destruction quest Von Rhine's Express duplicit description

### ISSUE THREAD

**Issue by gulde** [WarEmu/WarBugs#7839]
During the destruction quest Von Rhine's Express is on a tracker HUD written both "Salzemund Trackers" and "Kill Salzemund Trackers", which both are trigerred by killing a Salzemund Tracker

![steroid_003](https://cloud.githubusercontent.com/assets/22275274/18665308/e3235106-7f26-11e6-853d-afa8c551b429.jpg)

But on a map HUD, it shows "Salzemund Trackers" and "Von Rhines orders"
![steroid_004](https://cloud.githubusercontent.com/assets/22275274/18665348/1ebc02f8-7f27-11e6-9571-7d109c719bb5.jpg)

**Comment by Ryanfawkez** [comment]
Salzenmund Trackers are supposed to drop Von Rhine's Orders. Will fix that.

**Comment by Soulwhisper** [comment]
This is patched.
