### ISSUE TITLE
Useless quest reward for a quest Pillaging

### ISSUE THREAD

**Issue by gulde** [WarEmu/WarBugs#7841]
Playing as a squig herder, a quest Pillaging near the start of the game in Norsca gives one of the options quite useless reward as a bow, which is actually even worse then the starting one. Quite trivial thing, but should be noted as well.
![dekin_000](https://cloud.githubusercontent.com/assets/22275274/18669350/e4d7241e-7f3a-11e6-9205-62b5103ab733.jpg)

**Comment by Soulwhisper** [comment]
There are many-many-many useless quest rewards like this.Tweaking 1by1 might cause inbalance.

**Comment by gulde** [comment]
Got your point, but not sure about quest rewards that are worse than starting gear.

**Comment by Soulwhisper** [comment]
You are right about this one.Those can be fixed now.

**Comment by Ryanfawkez** [comment]
In my estimation these weapons should be removed; the original item choice was between the potion (which is also broken) and the belt.

**Comment by Soulwhisper** [comment]
True.
