### ISSUE TITLE
Guild Icon

### ISSUE THREAD

**Issue by Booni2** [WarEmu/WarBugs#7844]
just tried to creat a guild icon, so took the 500g tried to creat it, it took the money but no change on the icon itself, pmed a gm he told me there whas some problems with it and told me to report it here.

char name : Palbrecht
Guild name : Ironwatch Regiment

**Comment by Luth-RoR** [comment]
Which level has the guild?

**Comment by Luth-RoR** [comment]
Not until guild rank 20. https://github.com/WarEmu/WarBugs/issues/7776
