### ISSUE TITLE
Spreading Flames

### ISSUE THREAD

**Issue by PandaOrc** [WarEmu/WarBugs#7846]
Spreading Flames requires Hex to work and once there is a hex on a target icon lights up and shows that it can be used. If target is affected by Flame Breath then Spreading Flames does not light up even though it can be used (as it should be considering breath puts dot on a target).

Could it be possible to have Spreading Flames light up when target is affected by flame breath?

**Comment by Luth-RoR** [comment]
Not possible atm, as this is handled client side (for the client it is no hex).
