### ISSUE TITLE
Temple of Isha, 3 groups in scenario/Scenario Handler Issues

### ISSUE THREAD

**Issue by Daniellita** [WarEmu/WarBugs#7847]
We got a pop for Temple of Isha when there were already 2 groups in that scenario, nobody left there were actually 19 people at one point when an additional person joined the 4th party. 

http://imgur.com/a/9ckRx

Also we've had like 4-6 empty Caledor Woods pops that might be related to this, however it might also just be someone trolling/griefing and intentionally queuing for CW and leaving the queue.

**Comment by Luth-RoR** [comment]
Known problem: https://github.com/WarEmu/WarBugs/issues/6152
