### ISSUE TITLE
[Ability] No internal cooldowns on procs like covenants and frozen touch

### ISSUE THREAD

**Issue by Ktaan** [WarEmu/WarBugs#7849]
![asdfsadf](https://cloud.githubusercontent.com/assets/17799901/18719688/19dc3428-8031-11e6-8597-06a257e10dab.png)

Also, #7788, greatly illustrates that frozen touch and similar buff from BW don't have internal cooldown either (besides the fact that tactic Loudmouth is bugged and can trigger them in first place)
![f2bb4762-7c39-11e6-9a6b-6fa73fcc29ed](https://cloud.githubusercontent.com/assets/17799901/18720310/fda90f26-8033-11e6-8745-e74198887d5f.png)

To further illustrate capabilities of this proc based damage
![sdfgsdffds](https://cloud.githubusercontent.com/assets/17799901/18719916/179ed0e8-8032-11e6-91e8-a21aa7dd54e3.png)
AOE slayer (in ID spec) + WL makes less damage then def specced borc, whos actual skills and auto attacks hitting for less than 40 dmg.
This issue is similar like it was on Witchbrew (no internal cooldown)

**Comment by Luth-RoR** [comment]
Proc problems are known already: https://github.com/WarEmu/WarBugs/issues/7848 https://github.com/WarEmu/WarBugs/issues/7754
