### ISSUE TITLE
Unremovable auction house bids

### ISSUE THREAD

**Issue by Serioskiller** [WarEmu/WarBugs#7850]
Face that problem. Have 3 unremovable bids and my character marked as _Sevensixtytwo_. Screenshots below:
http://imgur.com/a/Cfflu
http://imgur.com/a/fOJFL

**Comment by Luth-RoR** [comment]
Does it work without AH addons activated?

**Comment by Serioskiller** [comment]
Same with/without addon.

**Comment by Luth-RoR** [comment]
Seems like the AH bids are allocated to that character: https://www.returnofreckoning.com/armory.php?character_id=425176&character_name=Sevensixtytwo

**Comment by Luth-RoR** [comment]
Could be related to https://github.com/WarEmu/WarBugs/issues/1103 https://github.com/WarEmu/WarBugs/issues/3904

**Comment by Serioskiller** [comment]
So what should i do now? Wait or...?

**Comment by Luth-RoR** [comment]
Yes, the first report is pretty old, so i guess it's unknown what causes this.

**Comment by Serioskiller** [comment]
UPDT
Risky chance to unbug myself by buyout those allocated bids(cost not to much), maybe it helps. Shot to try :)

**Comment by Serioskiller** [comment]
UPDT #3 
Problem is back. Will stop playing for now, game is to buggy.

**Comment by lilimx** [comment]
Hey,

im closing this ticket today. It's an old issue and could be already fixed after 6 years.
If the issue still persist, we can reopen it.
