### ISSUE TITLE
Quest: The Lost Pfefferstocks

### ISSUE THREAD

**Issue by Serioskiller** [WarEmu/WarBugs#7851]
Starts @Count Marcus von Rendt npc / Praag / Westmark Barricade War Camp.
Goal @Jupp Lohenback npc was missing / Map markers not showing.
http://imgur.com/a/XLLyv

**Comment by Gakvar** [comment]
No map markers, no directions. Impossible to determine where Jupp Lohenback npc is in Reikland.
