### ISSUE TITLE
Sorcerer Class Special Is Not Working!

### ISSUE THREAD

**Issue by Snorkl** [WarEmu/WarBugs#7852]
After latest patch Dark Magic does not give any crit or crit dmg buffs any more, both crit chance and dmg output are the same at 0 and 100 dark magic. Screenshoots atached.

![gottacrit_000](https://cloud.githubusercontent.com/assets/22361356/18736384/21c23d3a-80b9-11e6-99ab-cdf169dbfdcb.jpg)
![gottacrit_002](https://cloud.githubusercontent.com/assets/22361356/18736383/21c1db56-80b9-11e6-873d-e0b8da1c97a6.jpg)
![gottacrit_003](https://cloud.githubusercontent.com/assets/22361356/18736385/22266062-80b9-11e6-8d09-1abbc773ae80.jpg)

**Comment by Luth-RoR** [comment]
As already known by most, the character window/paperdoll is not reliable atm. Type .getstats into the chat window to get your real (server side) sats.

**Comment by milosxe** [comment]
You can't test it on doors. They can't be crit. Works just fine.
