### ISSUE TITLE
Zealot Harbinger of Doom not properly converting

### ISSUE THREAD

**Issue by Lobotobear** [WarEmu/WarBugs#7856]
I talked to GM Grandpa earlier and told me to report this. In the screenshots provided I have two items that give me a total of +19 intelligence which remains static with Harbinger of Doom turned off. However when I toggle Harbinger of Doom on, all of my willpower is converted to intelligence and leaves nothing static. Which I think means that Harbinger of Doom doesn't turn Intelligence to Willpower when toggled off. I don't know if this is a known thing or just a bug I'm experiencing. I even tried experimenting and equipping more Intelligence gear and it still didn't convert with Harbinger of Doom turned off yet still converted Willpower into Intelligence.

![](https://puu.sh/rkFtN/8aef08b7e7.jpg)

![](https://puu.sh/rkFur/063466fcf3.jpg)

![](https://puu.sh/rkFuI/6d9d3d0584.jpg)

![](https://puu.sh/rkFv0/bb8ffab414.jpg)

![](https://puu.sh/rkFvw/0d136a17cc.jpg)

![](https://puu.sh/rkFw3/99954e4053.jpg)

![](https://puu.sh/rkFwl/fc598b885c.jpg)

**Comment by Torquemadra** [comment]
paper doll is not accurate at this point, use .getstats for a true value representation. Also may I suggest the Harbinger mod for tracking the toggle when zoning.
