### ISSUE TITLE
Training via Pets

### ISSUE THREAD

**Issue by dretzl** [WarEmu/WarBugs#7858]
When I right click on my turret (any type) it opens the popup window that allows me to train career, mastery, renown abilities. I was able to allocate points like this as well.

**Comment by avenflar** [comment]
Same thing with Lions.

**Comment by Luth-RoR** [comment]
Them OP engis.

**Comment by Evildoor** [comment]
#5311?

**Comment by sioding** [comment]
fixed with patch from 28.ß3.2018
