### ISSUE TITLE
Quest: Grauenburg's Goons

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7859]
Realm: Order - Empire
Region: Reikland
Quest Giver: Calvert Breuger inside Castle Grauenburg
Target Coordinates: 04k/11k

Problem: The target 'Grauenburg's Goon' can't be located at the marked spot and neither in the surrounding area of Castle Grauenburg.

![1 grauenburgsgoons](https://cloud.githubusercontent.com/assets/18719012/18798286/0a45fb1e-81d2-11e6-88a5-365de3b03540.jpg)

![2 grauenburgsgoons](https://cloud.githubusercontent.com/assets/18719012/18798296/148df02c-81d2-11e6-8118-279e4c302641.jpg)

![3 grauenburgsgoons](https://cloud.githubusercontent.com/assets/18719012/18798300/1b563e6e-81d2-11e6-95c4-e0a7a48fc115.jpg)

**Comment by thorbolt80** [comment]
FYI, 'Grauenburg's Goon' is located in the middle of the "enemy within" PQ reikland 12.16. You just have to move the red mark  31.14 to 12.16.

**Comment by Eusebeus82** [comment]
More specifically, the graueneberg goons are the 2nd stage champions for the Enemy Within PQ, for anyone looking for an answer here....
