### ISSUE TITLE
Raven Host Vanguard bug

### ISSUE THREAD

**Issue by tiko0401** [WarEmu/WarBugs#7860]
There's a bug at the Raven Host Vanguard public quest, where the last boss, a huge giant, cant be targetet. It is for some reason only one person, who can target the boss. So you cant complete it without a healer ;)
-Elenwen

**Comment by Soulwhisper** [comment]
True but there is an already open ticket here #6933.I will put it in there.Thanks.

**Comment by Luth-RoR** [comment]
Closing it then.

**Comment by Soulwhisper** [comment]
Torque said that need specific names of mobs so better re-open this.I removed the report on my ticket.
