### ISSUE TITLE
Mourkain and Doomfist SCs Dwarf camp cannons are not working.

### ISSUE THREAD

**Issue by avenflar** [WarEmu/WarBugs#7862]

**Comment by avenflar** [comment]
Can't click on them, it's as if they were decor

**Comment by Soulwhisper** [comment]
Maybe this has something to do with Champions in many areas in the world becoming untargetable.

**Comment by avenflar** [comment]
I found the Elf siege weapons to be working by example in Pheonix Gate.

**Comment by Ryanfawkez** [comment]
Appears to be fixed now.
