### ISSUE TITLE
War lion can be used as a "career trainer"

### ISSUE THREAD

**Issue by hogo2hogo** [WarEmu/WarBugs#7863]
Hello, as seen from the attached pic, i can use any war lion (either as default or a renamed one) as a career trainer. I also tried it out and i successfully trained 2 mastery points while in etaine pq.
![warlion](https://cloud.githubusercontent.com/assets/16440840/18800687/04a033fe-81e7-11e6-9865-c52c93e47c9c.png)

**Comment by Luth-RoR** [comment]
Known: https://github.com/WarEmu/WarBugs/issues/7858
