### ISSUE TITLE
T3 keep guards at "Ghrond´s Sacristy" and "Well of Qhaysh" can't be targeted

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#7864]
the npc guards in ghronds sacristy have turned transparent and untargetable(some of them at least), i think there still susceptible to aoe damage but i have none of my own to test that theory with
![aurias_000](https://cloud.githubusercontent.com/assets/16922842/18800969/e8b81d64-81d7-11e6-99f7-e76c73f1d764.jpg)

**Comment by MightyPhred** [comment]
additional, while fighting in the keep i just got an interaction window popup offering me the services of renown/career/mastery/crafting trainer, from someone/thing called "ieatsdwarfs"

**Comment by MightyPhred** [comment]
additional additional, same bug appears to be effecting the guards in well of qhaysh, i only just visited it

**Comment by MightyPhred** [comment]
further addition, it seems that "ieatdwarfs" is somebodies pet lion, i just crashed into him again in talabecland

**Comment by Luth-RoR** [comment]
Only one bug per report; that pets count as career trainers is already known and can be found via the search function.

**Comment by Torquemadra** [comment]
fixed ages back, needs a push
