### ISSUE TITLE
Battle of Remembrance issues

### ISSUE THREAD

**Issue by Rolutir** [WarEmu/WarBugs#7867]
Hy everyone,

During the epiq quest Battle of Remembrance (the Dwarf epic quest), I found an issue. When you have to speak to Brol Gornbrow in Kadrin Valley (it's a slayer figthing with two ogres), you can see him but you can't to interact with him and can't continue the quest. I think it's an issue due to the last patch (some hours ago). 
I don't know where to post this information so I use this Discussion. 
If somebody have the same problem, maybe it will be the same for everybody... 

Thanks for your help 

PS : sorry for my bad english

**Comment by Nizdizzle** [comment]
Can confirm, having same issue. NPC is there, but can't be interacted with (thus stopping the quest chain progression).

**Comment by Yoreik** [comment]
I confirm this bug. can't interact with Brol Gornbrow NPC. Chain quest stopped at this step.

**Comment by Drum666** [comment]
I confirm too this bug. There is no way to interact with Brol Gornbrow NPC. Chain quest stopped at this step.

**Comment by roflaa** [comment]
issue still there
