### ISSUE TITLE
Unreal ammount of Medals

### ISSUE THREAD

**Issue by tlitschye** [WarEmu/WarBugs#7868]
Just got 7700 Medals from Orderlock in TM, that must be a bug.

Greets

**Comment by Culdu** [comment]
same here

**Comment by Torquemadra** [comment]
can we have a screenshot of gaining please, is it a bunch all at once or lots of little ones

**Comment by Culdu** [comment]
![starilas_218](https://cloud.githubusercontent.com/assets/14928735/18803702/c9b74672-81f2-11e6-8150-cf847a8da138.jpg)

**Comment by Culdu** [comment]
about 7100 from the bug

**Comment by Culdu** [comment]
it was one mail with 7100 ~~ and another mail with one
