### ISSUE TITLE
Haldar Rally Master Norsca Icon Over Head

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#7877]
- [ ] If you take all 3 influence rewards from him his skull sign above his head disappears.Relogging doesnt solve it.

![shamanakos_002](https://cloud.githubusercontent.com/assets/16864486/18808223/f3d9016c-8264-11e6-83d8-167fe4c1262e.jpg)

**Comment by ozarmidrashim** [comment]
Must have been intended to work that way by Mythic

**Comment by Soulwhisper** [comment]
This is not happening to all rally masters though.If you take rewards the skull stays but grayed out.I can close it if this cannot be fixed yet?

**Comment by Soulwhisper** [comment]
**Should work that way as Aza said,after some further testing.I report Rally Masters which still have Skull over their heads after taking 3 infl rewards.**
