### ISSUE TITLE
"Dangerous Assumption" [destruction][Troll Country][quest]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#788]
Quest reward get assigned randomly or incorrect ( another guilmate told me he recived too the wep skill 1h axe)

If possible reset it so that ppl can do that again.

**Comment by Evildoor** [comment]
I did this quest several times and had no problems. There are issues with items themselves (stats), but that's another question. Does this problem still persists for you?

**Comment by Tesq** [comment]
if it work you must be fixed, all those type of quest had problem back at t2 relase, so if it work for 1 persone must work for all.

**Comment by Evildoor** [comment]
Okay, then i'm closing this until (and if) someone encounters this problem again.
