### ISSUE TITLE
Officer's healing elixir 

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#7880]
If used just before death no efect

**Comment by Ryanfawkez** [comment]
Well maybe you died before being able to use the potion?

**Comment by MKorin** [comment]
No info in log, CD on pots

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
