### ISSUE TITLE
Book of Binding - Rally Point 'Lieberholz's Command'

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7881]
Realm: Order - Empire
Region: Praag
Target Coordinates: 14k/56k
Subject: Rally Point 'Lieberholz's Command'
NPC: Rally Master 'Captain Lieberholz'

Problem: Using the 'Book of Binding' leads to 'Zone 0'

![1 rallypointlieberholzscommand](https://cloud.githubusercontent.com/assets/18719012/18809601/5917e8fc-8280-11e6-8742-07a0fefb73c6.jpg)

![2 rallypointlieberholzscommand](https://cloud.githubusercontent.com/assets/18719012/18809603/5fefe13e-8280-11e6-888f-83a1397d77ab.jpg)

**Comment by Razielhell** [comment]
Fixed next patch. Ty!

**Comment by sioding** [comment]
Fixed with patch 21.10.2017
