### ISSUE TITLE
Ruinous Power Stage III Boss not targetable

### ISSUE THREAD

**Issue by Exanimalis** [WarEmu/WarBugs#7882]
Hey, 
I've encountered this issue first time today, another player said he had it yesterday already (not confirmed): The boss "Kar'thok the Bloodhowler" spawns as planned after stage II but is not selectable target, has no name above him as well. Here is a screenshot of what it looks like ingame.

Regards,
Exa
![nox_001](https://cloud.githubusercontent.com/assets/22417155/18809871/6f191370-827f-11e6-8ad4-efc9ef155996.jpg)

**Comment by Soulwhisper** [comment]
This started happening yesterday after the first rollback.Need confirmation from Developer if its a major issue because right now it happens with many Champion mobs in PvE PQs and some siege weapons in scenarios too iirc.

**Comment by Torquemadra** [comment]
need specific reports on each effected mob name

**Comment by Soulwhisper** [comment]
oh boy.So have to open new tickets.
