### ISSUE TITLE
Black Toof NPC dont give Quest Item

### ISSUE THREAD

**Issue by Vrafthudnir** [WarEmu/WarBugs#7883]
Hi there, 

the quest NPC Golgrund Stonefist dont give the item "Amulet of Teeth" , if i translate it right.
You need this item to get the "Black Toof" Accessoire. If you have the Amulet you have to kill Turned Hounds to pick up 10 pieces of teeth... but i cant finish it without the Amulet.

Greetings Vitisus

**Comment by Ryanfawkez** [comment]
It's the other way around now. Kill the Turned Hounds, and buy the Amulet of Fangs at the library assistant.
