### ISSUE TITLE
Quest: Sundered Rock

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7884]
Realm: Order - Empire
Region: West Praag
Target Coordinates: 50k/32k
Subject: Kill Brakus Construct Keeper, kill Goriun Metalflesh, kill Raven Sunderer

Problem: Quest marker for target area on the map is missing

![1 sunderedrock](https://cloud.githubusercontent.com/assets/18719012/18810118/28d04898-828e-11e6-9939-4cd9af209b68.jpg)

![2 sunderedrock](https://cloud.githubusercontent.com/assets/18719012/18810120/2dab2ed2-828e-11e6-80de-17036495fa2e.jpg)

![3 sunderedrock](https://cloud.githubusercontent.com/assets/18719012/18810122/359bce76-828e-11e6-8f8e-39ff87bd1cfe.jpg)

![4 sunderedrock](https://cloud.githubusercontent.com/assets/18719012/18810123/39cfb8cc-828e-11e6-9b86-125fea9d9e34.jpg)

![5 sunderedrock](https://cloud.githubusercontent.com/assets/18719012/18810124/3fa3c996-828e-11e6-99ec-bd1b138e3a24.jpg)

**Comment by sioding** [comment]
fixed with patch from 05.11.2018
