### ISSUE TITLE
Quest: Knights Errant

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7886]
Realm: Order - Empire
Region: Praag
Quest Giver: Courier Harlen at Chap17
Target Coordinates: 64k/61k at Chaos Wastes
Subject: Speak to Dagobert Schyler
NPC: Dagobert Schyler

Problem: The mentioned Dagobert Schyler is a NPC inside the Bastion Stair, which has not been implemented yet. In addition to that the quest marker for target area on the map is missing.

![1 knightserrant](https://cloud.githubusercontent.com/assets/18719012/18810337/fd352dec-8293-11e6-9cc0-139714584793.jpg)

![3 knightserrant](https://cloud.githubusercontent.com/assets/18719012/18810340/07fd4ade-8294-11e6-90de-2c02ca2ac83a.jpg)

![2 knightserrant](https://cloud.githubusercontent.com/assets/18719012/18810339/01859288-8294-11e6-9b4b-6e989dfde06e.jpg)

![4 knightserrant](https://cloud.githubusercontent.com/assets/18719012/18868110/4d894872-84a7-11e6-91e1-03645f97b7fb.jpg)

**Comment by Kabucoror** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 06.07.2019
