### ISSUE TITLE
Gained ~10 renown ranks instantly

### ISSUE THREAD

**Issue by Nycta** [WarEmu/WarBugs#7888]
A few minutes after the announcement that the server will be brought down to investigate the server, Yipikaye and Axeronea got about 10 renown ranks each. Yipikaye was rr55 and 78% and got to 65 and 24%, Axeronea was 52+(can't remember exactly but must have been around 30%) and got to 62 +50%.

**Comment by ozarmidrashim** [comment]
Should already be fixed

**Comment by Nycta** [comment]
Unfortunately, yes.. :P
