### ISSUE TITLE
Server Rollback 24/09/2016 - Bestial Tokens/Tome Unlocks

### ISSUE THREAD

**Issue by Toonmanisback** [WarEmu/WarBugs#7890]
Had done some bestial tokens Saturday morning about 2 hours before a new server roll back was announced. 

Farmed the following Tome Unlocks for tokens:

http://warhammeronline.wikia.com/wiki/Engage_the_Gorger - 1 token
http://warhammeronline.wikia.com/wiki/Dispense_Justice - 1 token
http://warhammeronline.wikia.com/wiki/For_the_Promise_of_Power - 1 token

Server rollback happened and once the server was back up, I logged in and my tokens were gone, but the Tome Unlocks are registered as complete and aren't able to be completed again to gain my tokens back.

**Comment by Luth-RoR** [comment]
Hi, 

you can contact a GM with this issue, so that they can solve the problem. You can link the report to them for clarification.

**Comment by Toonmanisback** [comment]
Thank you
