### ISSUE TITLE
So, I got all the possible influence and quest rewards for a time.

### ISSUE THREAD

**Issue by Gilandar** [WarEmu/WarBugs#7891]
A while back, the same day when I created my sorcerer, I had a very strange bug. When I got to the first destro camp, where you meet your first rally master, and completed all the quests, as well as did the local PQ, I went back to claim my rewards. I noticed suddenly that after having selected my reward, I couldn't turn in the quest. For some time I was confused, until I tried to select the other reward and it seemed to have selected both of them. I clicked accept, and found both of the rewards in my inventory. The same for the influence rewards, I had every single one of them.

I'm still not sure what caused this bug to happen and it was a few weeks ago. I didn't really think to report it back then. I still have all the possible dark elf quest trophies in my inventory.

**Comment by Ryanfawkez** [comment]
No longer applies, bug was fixed.
