### ISSUE TITLE
Quest: Timeless Wisdom

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7894]
Realm: Order - Empire
Region: Praag
Target Coordinates: 04k/44k
Subject: Kill Reinforcing Captain, -Captain, -Magus, -Warrior
NPC: Reinforcing Champion

Problem: The first mention of 'Kill Reinforcing Captain' should be 'Kill Reinforcing Champion' and refer to the corresponding champion mob at this spot.

![1 timelesswisdom](https://cloud.githubusercontent.com/assets/18719012/18815449/3c6b4b6a-8332-11e6-8e80-2d42d1c4f5bd.jpg)

![2 timelesswisdom](https://cloud.githubusercontent.com/assets/18719012/18815450/4222f738-8332-11e6-9eb0-dd24991237af.jpg)

![3 timelesswisdom](https://cloud.githubusercontent.com/assets/18719012/18815452/484f66f0-8332-11e6-919b-50b4d04dc700.jpg)

**Comment by Lheana** [comment]
The correct objective in real is to find the GO 'Battle Plans'. Hence I have set the quest that way, and added/corrected the quest markers.

**Comment by sioding** [comment]
Fixed with patch from 29.09.2018
