### ISSUE TITLE
Quest: Bait & Switch

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7895]
Realm: Order - Empire
Region: Praag
Target Coordinates: 10k/42k
Subject: Kill Doomglade Vraslyn

Problem: Quest Requirements should be 'Kill Vraslyn D'raeth' and refer to the corresponding mob. In addition to that the marked area on the map would be at 10k/42k. 

![1 bait switch](https://cloud.githubusercontent.com/assets/18719012/18815464/b6d2926e-8332-11e6-86a2-561cea86a756.jpg)

![2 bait switch](https://cloud.githubusercontent.com/assets/18719012/18815467/bb7157e2-8332-11e6-9942-ebaae521f18f.jpg)

![3 bait switch](https://cloud.githubusercontent.com/assets/18719012/18815468/c5472170-8332-11e6-8c1d-4389943aaa6a.jpg)

**Comment by Ezella** [comment]
Reference #6793

**Comment by Waldemard** [comment]
As he said this location is not exact as the same for the NPC Name and killing Vraslyn D'raeth do not complete the quest.

**Comment by Lheana** [comment]
The quest is correct, you have to kill Doomglade Vraslyn (it's a trap, not the real Vraslyn), thus the quest marker is correct. You will kill the real Vraslyn with the next quest.
