### ISSUE TITLE
Rally Point: Empire Chapter 19

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7896]
Realm: Order - Empire
Region: Praag
Target Coordinates: 27k/25k
Subject: Set Rally Point
NPC: Krasa Falkenheim at Chap19

Problem: Setting Rally Point causes an Error 'Unknown Rally Point NPC(301)'

![1 rmemp19](https://cloud.githubusercontent.com/assets/18719012/18815568/221d7df6-8336-11e6-8bed-8df3c39d141f.jpg)

![2 rmemp19](https://cloud.githubusercontent.com/assets/18719012/18815569/27b89fca-8336-11e6-9a33-dbb596dc851c.jpg)

**Comment by sioding** [comment]
fixed with patch 21.10.2017
