### ISSUE TITLE
Quest: Desperate Gambit

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7901]
Realm: Order - Empire
Region: Praag
Target Coordinates: 27k/23k (Battle Wizard Krishtof) and 14k/48k (Vladimir Von Korbel)
Subject: Convince Battle Wizard Krishtof, -Leopold Rohric, -Vladimir Von Korbel
NPCs: Battle Wizard Krishtof (Empire Chapter 19), Vladimir Von Korbel (Empire Chapter 18)

Problem: Quest markers for target areas on the map are missing for the two mentioned NPCs

![1 desperategambit](https://cloud.githubusercontent.com/assets/18719012/18816375/d44980c6-8348-11e6-9f84-77dd86adcdd5.jpg)

![2 desperategambit](https://cloud.githubusercontent.com/assets/18719012/18816376/d95a8e02-8348-11e6-8a61-abd7673a72df.jpg)

![3 desperategambit](https://cloud.githubusercontent.com/assets/18719012/18816378/e069b06a-8348-11e6-8a4a-4ef347226513.jpg)

![4 desperategambit](https://cloud.githubusercontent.com/assets/18719012/18816379/e5d2e166-8348-11e6-9fb8-29cf3e46a8de.jpg)

![5 desperategambit](https://cloud.githubusercontent.com/assets/18719012/18816380/eb826bfe-8348-11e6-8ca0-ec77f0f5c6d2.jpg)

**Comment by Razielhell** [comment]
Fixed. Added the two additional quest markers.
