### ISSUE TITLE
PQ: PQ roll

### ISSUE THREAD

**Issue by Emroi** [WarEmu/WarBugs#7903]
Easy PQ drop gold and purple bags! 
![emroi_015](https://cloud.githubusercontent.com/assets/22431827/18816857/b7a3e26a-835a-11e6-8eb7-024db64de82c.jpg)

**Comment by Soulwhisper** [comment]
Proof? I did multiple times Lonely Tower and it dropped only Green/White bags.

**Comment by Emroi** [comment]
today with shammy i drop purple, sry dont screen, if its need i go and get it again

**Comment by Emroi** [comment]
PROOF
![emroi_017](https://cloud.githubusercontent.com/assets/22431827/18817425/89ad14cc-8368-11e6-83fb-837441cd6220.jpg)

**Comment by Soulwhisper** [comment]
Thanks for picture
**.Normal PQs 6< Players drop 1 Blue,3 Green and 1 White bag with a high chance to drop at least 1 Purple bag.There is a low chance to drop 1 Gold bag.**
Most likely this belongs to normal PQs but the MAP ID shows it as Easy.
I dont even know if Devs can change PQs ID inside Map.Maybe hardcoded and client related.

**Comment by Soulwhisper** [comment]
This can close too @Luth-RoR.
This problem is about text IDs on map and its only visual.
It will be handled in the future with the new client.
Thanks.

**Comment by Torquemadra** [comment]
already "fixed" but be aware pqs are a state of flux and things may be  being tried at them
