### ISSUE TITLE
Mara Defensive Procs

### ISSUE THREAD

**Issue by Toldavf** [WarEmu/WarBugs#7907]
For some time not i have been keeping an eye on the abilities mara posses that require a parry or disrupt specifically death grip and mutated energy. Some times these abilities will not light when you defend an attack.

**Comment by ozarmidrashim** [comment]
The abilities light in response to the client receiving a defense result from the server. If you see "Parry" and the ability does not light, it's nothing to do with me.

**Comment by Luth-RoR** [comment]
Similar to https://github.com/WarEmu/WarBugs/issues/7846
Needs client modification.
