### ISSUE TITLE
[Quest] Desperate Gambit [Chaos Wastes, Empire ch 20]

### ISSUE THREAD

**Issue by Gakvar** [WarEmu/WarBugs#7909]
Location: Lost Artifacts PQ

Requirements
 - Black Ice Chests Opened 8/8

Objectives completed, Nowhere to turn. No directions on what NPC would move this quest foward.

**Comment by Hargrim** [comment]
Whole quest line fixed, 2h reward items got 2 tali slots. Should be available in next patch.
