### ISSUE TITLE
Quest: Daemonic Possessions

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7910]
Realm: Order - Empire
Region: Chaos Wastes
Target Coordinates: 52k/36k (Reaping Bloodletter) and 26k/60k (Wasteland Flamer and Wasteland Daemonette)
Subject: Kill Reaping Bloodletter, -Wasteland Flamer, -Wasteland Daemonette

Problem: Quest markers for target areas on the map are missing

![1 daemonicpossessions](https://cloud.githubusercontent.com/assets/18719012/18819632/8fe790ca-8394-11e6-9d91-160cbdc5b481.jpg)

![2 daemonicpossessions](https://cloud.githubusercontent.com/assets/18719012/18819614/3f1b4812-8394-11e6-9762-4923bfdf17c9.jpg)

![3 daemonicpossessions](https://cloud.githubusercontent.com/assets/18719012/18819616/45a79eec-8394-11e6-818b-58707b2b183f.jpg)

![4 daemonicpossessions](https://cloud.githubusercontent.com/assets/18719012/18819619/4aab90ec-8394-11e6-87b3-cec83e841fc2.jpg)

![5 daemonicpossessions](https://cloud.githubusercontent.com/assets/18719012/18819620/5177dcc8-8394-11e6-83f9-9c3aeb44ae63.jpg)

![6 daemonicpossessions](https://cloud.githubusercontent.com/assets/18719012/18819623/557f5c60-8394-11e6-8954-86c2bf61941b.jpg)

**Comment by Luth-RoR** [comment]
Afaik multiple questmarkers for one quest are not supported yet.

**Comment by Ezella** [comment]
Ok thanks Luth, i ll keep that in mind for future issues which relate to multiple questmarkers.

**Comment by Ezella** [comment]
Surprisingly I could discover a quest today which uses multiple questmarkers, maybe the code behind can help to understand how this has been solved by the originally developers:

Quest: Artistry Of War

Realm: Order
Region: High Elf - Blighted Isle
Coordinates: 43k/40k
Subject: Recruit Shield Bearers, -Spearmen

![1 artistryofwar](https://cloud.githubusercontent.com/assets/18719012/18846632/2ea0bd4e-8427-11e6-9763-c046854f08f6.jpg)

![2 artistryofwar](https://cloud.githubusercontent.com/assets/18719012/18846636/32fee744-8427-11e6-9d3e-39c24cada340.jpg)

**Comment by Luth-RoR** [comment]
On second thought, i think the problem was that they won't update when, for instance, the spearmen are done. But it could be wrong/outdated. Maybe a DB dev can clarify.

**Comment by Ezella** [comment]
ah I see, thanks for responding Luth

**Comment by Razielhell** [comment]
Fixed in next Patch.
Quest markers will show correctly now.
