### ISSUE TITLE
Quest: Into The Depths

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7911]
Realm: Order - Empire
Region: Chaos Wastes
Target Coordinates: 60k/35k
Subject: Kill Wastetorn Manticore

Problem: Quest marker for target area on the map should be changed to the mentioned coordinates

![1 intothedepths](https://cloud.githubusercontent.com/assets/18719012/18820117/23184276-839b-11e6-94ed-7680471242d5.jpg)

![2 intothedepths](https://cloud.githubusercontent.com/assets/18719012/18820121/283933c8-839b-11e6-8e6d-11288fd9b450.jpg)

![3 intothedepths](https://cloud.githubusercontent.com/assets/18719012/18820127/2d60147a-839b-11e6-9e9a-8017fa2cea16.jpg)

**Comment by Ezella** [comment]
Reference #8027

**Comment by Hargrim** [comment]
Corrected, fixed in next patch.

**Comment by Soulwhisper** [comment]
Patched.
