### ISSUE TITLE
Quest: Sowing Sorrow

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7912]
Realm: Order - Empire
Region: Chaos Wastes
Target Coordinates: 57k/31k
Subject: Kill Daemon Guthul Pusreaver
NPCs: Gregor Freught, Daemon Guthul Pusreaver

Problem: The mentioned daemon should spawn near questgiver Gregor Freught after taking this quest, but it doesnt (Invalid Creature - QuestID 31002, Objld=42816). In addition to this the quest marker for target area on the map is missing.

![1 sowingsorrow](https://cloud.githubusercontent.com/assets/18719012/18820705/3654e8da-83a0-11e6-98c2-2beae3aa1e19.jpg)

![2 sowingsorrow](https://cloud.githubusercontent.com/assets/18719012/18820706/3a30ccee-83a0-11e6-97f8-2e893b401739.jpg)

![3 sowingsorrow](https://cloud.githubusercontent.com/assets/18719012/18820709/3ef1a12c-83a0-11e6-926b-d13f341a5fd2.jpg)

**Comment by Ezella** [comment]
References: #7097 #7555

**Comment by Soulwhisper** [comment]
This can close.Patched.
