### ISSUE TITLE
Quest: Shroud Of Faith

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7913]
Realm: Order - Empire
Region: Chaos Wastes
Target Coordinates: 58k/50k
Subject: Find Bloody Mess Kit

Problem: Quest marker for target area on the map is missing

![1 shroudoffaith](https://cloud.githubusercontent.com/assets/18719012/18822188/8ca29d24-83ad-11e6-81eb-40b31a0873a4.jpg)

![2 shroudoffaith](https://cloud.githubusercontent.com/assets/18719012/18822193/92d4db62-83ad-11e6-9fe5-9459b68ad25c.jpg)

![3 shroudoffaith](https://cloud.githubusercontent.com/assets/18719012/18822196/97fcfde0-83ad-11e6-8fd1-b6d4e6053eaf.jpg)

**Comment by Ezella** [comment]
Thanks Wotann for your appreciated help!

**Comment by Ryanfawkez** [comment]
Not often that I find people actually reading quest descriptions. I will amend that as well as adding the proper quest markers.

**Comment by Soulwhisper** [comment]
This can close.Patched.
