### ISSUE TITLE
Quest: World Gone Mad

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7915]
Realm: Order - Empire
Region: Chaos Wastes
Target Coordinates: 47k/18k
Subject: Kill Maddening Horror, Find Altar of Madness

Problem: The Altar of Madness is not clickable and can be found twice in this area. In addition to this the quest marker for the target area on the map should get changed/extended to the mentioned coordinates.

![1 worldgonemad](https://cloud.githubusercontent.com/assets/18719012/18823878/3982614a-83be-11e6-9b57-299c93c2c918.jpg)

![2 worldgonemad](https://cloud.githubusercontent.com/assets/18719012/18823887/3ef5e6a6-83be-11e6-807f-67f497f51a02.jpg)

![3 worldgonemad](https://cloud.githubusercontent.com/assets/18719012/18823891/44c983b2-83be-11e6-89db-e5e97d5cab1c.jpg)

![4 worldgonemad](https://cloud.githubusercontent.com/assets/18719012/18823894/498e01a2-83be-11e6-9404-624f193004ad.jpg)

**Comment by Soulwhisper** [comment]
This can close.Patched.
