### ISSUE TITLE
Quest: In The Footsteps Of Evil // Needs confirmation!

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7916]
Realm: Order - Empire
Region: Praag
Target Coordinates: Entire Praag
Subject: Find Souleater's Mirror
NPC: Breitenhoff the Faithful (Empire Chapter 17)

Problem: Souleater's Mirror is not locatable, maybe someone can help with this issue.

![1 inthefootstepsofevil](https://cloud.githubusercontent.com/assets/18719012/18825457/da4ae55c-83c8-11e6-83dc-efcca9da590e.jpg)

![2 inthefootstepsofevil](https://cloud.githubusercontent.com/assets/18719012/18825462/deaf1ca8-83c8-11e6-896a-d54b6bfd247c.jpg)

![3 inthefootstepsofevil](https://cloud.githubusercontent.com/assets/18719012/18825465/e520dd60-83c8-11e6-8de1-f2d6a5dd34cc.jpg)

**Comment by Ryanfawkez** [comment]
The Mirror is a game object located in West Praag. Added a quest marker for its location.

**Comment by Soulwhisper** [comment]
This can close.Patched.
