### ISSUE TITLE
Quest: A Bear Of A Time // Needs confirmation!

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7917]
Realm: Order - Empire
Region: Chaos Wastes
Target Coordinates: Entire Reikland
Subject: Sable Bearskin
NPC: Cuthbert Lawry (Empire Chapter 20)

Problem: Not a single killed bear at Reikland 'dropped' the Sable Bearskin (almost exterminated the whole reikland bear population, *cough*), maybe someone can help with this issue.

![1 abearofatime](https://cloud.githubusercontent.com/assets/18719012/18825544/4de287ea-83c9-11e6-9a23-5f57e7e1f5df.jpg)

![2 abearofatime](https://cloud.githubusercontent.com/assets/18719012/18825549/5299cb72-83c9-11e6-8bf3-a2eee86ea748.jpg)

![3 abearofatime](https://cloud.githubusercontent.com/assets/18719012/18825553/58c472c2-83c9-11e6-9b28-5c5bed4d4798.jpg)

**Comment by Ezella** [comment]
Similar issue like #7918

**Comment by Soulwhisper** [comment]
This can close.Patched.
