### ISSUE TITLE
Quest: Beastly Burden // Needs confirmation!

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7918]
Realm: Order - Empire
Region: Chaos Wastes
Target Coordinates: Entire Praag
Subject: Corrupted Hearts
NPC: Cuthbert Lawry (Empire Chapter 20)

Problem: No beastman at Praag that has been killed could fit the bill , maybe someone can help with this issue.

![1 beastlyburden](https://cloud.githubusercontent.com/assets/18719012/18825615/9c7f7638-83c9-11e6-988a-367e2f7584cb.jpg)

![2 beastlyburden](https://cloud.githubusercontent.com/assets/18719012/18825620/a1eecff6-83c9-11e6-8e02-1330cde66e51.jpg)

![3 beastlyburden](https://cloud.githubusercontent.com/assets/18719012/18825626/a7e26954-83c9-11e6-9215-c2dc6633872e.jpg)

**Comment by Ezella** [comment]
Similar issue like #7917

**Comment by Ryanfawkez** [comment]
Corrupted Hearts do not drop because the item itself doesn't exist in the database. Fixing.

**Comment by Soulwhisper** [comment]
This can close.Patched.

**Comment by lennip** [comment]
Not fixed. I just got that quest and killed dozens of beastmen all over Praag, none of them dropped the Corrupted Heart...

**Comment by Algenubi** [comment]
Problem still exists. I killed all types of beastmen in Praag. No one counts.

**Comment by sioding** [comment]
Fixed with patch from 29.09.2018
