### ISSUE TITLE
Wrong Dawnbreak Stalkers model rendering

### ISSUE THREAD

**Issue by gulde** [WarEmu/WarBugs#7919]
During the second phase of the PQ 'Dawn's Early Fight' in DE T2 - Shadowlands, game spawns Dawnbreaker Stalkers, which seems to have a problem with model rendering:
![steroid_007](https://cloud.githubusercontent.com/assets/22275274/18834602/1d464b34-83f7-11e6-9c86-5726243d0848.jpg)

**Comment by Soulwhisper** [comment]
Not happening everytime though...right? Cause when i tested it,it was fine.
Maybe too much Steroid?

**Comment by Soulwhisper** [comment]
This can close.Patched.
