### ISSUE TITLE
"setting the trap"[destruction][Ostland][Quest]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#792]
enemy mob in the red area fight each other ( and being champ attacking low mob is hard get refuges)

![vlodar_053](https://cloud.githubusercontent.com/assets/7527415/8264675/9f1dd338-16e9-11e5-8cba-d52507a229a7.jpg)
![vlodar_054](https://cloud.githubusercontent.com/assets/7527415/8264685/bc636c6e-16e9-11e5-898b-e1189d4147f5.jpg)

**Comment by Thayli** [comment]
Fix pending.
