### ISSUE TITLE
Quest: Sins Of The Past

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7921]
Realm: Order - High Elf
Region: Blighted Isle
Target Coordinates: 37k/04k
Subject: Kill Dark Sprites

Problem: Dark Sprites are not clickable, but its possible to kill them with an aoe attack. In addition to that they are not lootable.

![1 sinsofthepast](https://cloud.githubusercontent.com/assets/18719012/18842786/8a995b62-8416-11e6-8a93-7b0ebc660f18.jpg)

![2 sinsofthepast](https://cloud.githubusercontent.com/assets/18719012/18842810/9673b5f4-8416-11e6-99d1-b68e6e567517.jpg)

![3 sinsofthepast](https://cloud.githubusercontent.com/assets/18719012/18842814/9c98b556-8416-11e6-89af-08ba205a71ad.jpg)

![4 sinsofthepast](https://cloud.githubusercontent.com/assets/18719012/18842827/a2306a04-8416-11e6-9c71-ae040d0819cd.jpg)

**Comment by Soulwhisper** [comment]
This can close.Patched.
