### ISSUE TITLE
Quest: Tireless Honor

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7923]
Realm: Order - High Elf
Region: Blighted Isle
Quest Giver: Laretha the Sun Mage at Narthain Rally Point between Chap1 and Chap2
Target Coordinates: 52k/13k
Subject: Relieve a Mournfire From Combat
NPCs: Halael- ,Cadrir- and Geran Mournfire

Problem: Once safe from the incoming attacks, none of the mentioned NPCs triggers a reaction while getting clicked.

![1 tirelesshonor](https://cloud.githubusercontent.com/assets/18719012/18848948/f89214c8-8430-11e6-9222-ac0c1062cfc7.jpg)

![2 tirelesshonor](https://cloud.githubusercontent.com/assets/18719012/18848952/fc9402c0-8430-11e6-8c70-9aafbcd59bac.jpg)

![3 tirelesshonor](https://cloud.githubusercontent.com/assets/18719012/18848959/02a15f28-8431-11e6-9cec-ee6ca7da085b.jpg)

![4 tirelesshonor](https://cloud.githubusercontent.com/assets/18719012/18848966/08ab4b5e-8431-11e6-8d9e-63d8e8a14f53.jpg)

![5 tirelesshonor](https://cloud.githubusercontent.com/assets/18719012/18848968/0cdc65f0-8431-11e6-858e-97626e5b7509.jpg)

![6 tirelesshonor](https://cloud.githubusercontent.com/assets/18719012/18848973/1040b0b6-8431-11e6-8b01-599528ce3188.jpg)

**Comment by Paleolog77** [comment]
confirm, bugg exist at 17.11.2016

**Comment by Luth-RoR** [comment]
There is no need to confirm any reports that don't have the "confirmation request" label; particularly not the ones that are flagged with "not implemented yet".

**Comment by sioding** [comment]
Fixed with patch from 15.06.2019
