### ISSUE TITLE
Questgiver Thana Soreyn unselectable

### ISSUE THREAD

**Issue by LessRight** [WarEmu/WarBugs#7927]
Faction: Order
Zone: Shadowlands
Coordinates: 44000, 24000
NPC: Thana Soreyn

Thana Soreyn spawns in a cowering emote, and is unselectable for quests. This appears to be irrespective of whether she is under attack from the spiders which spawn next to her.

She also spawned naked once.

**Comment by Ryanfawkez** [comment]
NPC is supposed to be invincible, while Nightweb Spiders threaten her. Made her a champion mob for now, so that she 1. doesn't die and 2. can be spoken to.

**Comment by Soulwhisper** [comment]
This can close.Patched.
