### ISSUE TITLE
Book of Binding - Rally Point 'Blightsward', High Elf Chapter 3

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7928]
Realm: Order - High Elf
Region: Chrace
Target Coordinates: 51k/02k
Subject: Rally Point 'Blightsward' Chap3
NPC: Rally Master 'Morithwen Nightwhisper'

Problem: Using the 'Book of Binding' leads to 51k/06k

![1](https://cloud.githubusercontent.com/assets/18719012/18869404/88f51b52-84ac-11e6-8527-1e26d2263a17.jpg)

![2](https://cloud.githubusercontent.com/assets/18719012/18869409/8c8d683c-84ac-11e6-98f4-2634d6279b20.jpg)

![3](https://cloud.githubusercontent.com/assets/18719012/18869416/915e998a-84ac-11e6-9663-28d27142537d.jpg)

**Comment by saupreusse** [comment]
Fixed in the next patch.
