### ISSUE TITLE
"Craving Succor" [destruction][Nordland/Ostland][Quest]

### ISSUE THREAD

**Issue by CarlistRieekan** [WarEmu/WarBugs#793]
Zaccur the Despised [NPC] seems to be missing. He should be located in Raven's Edge [Chaos T2 Warcamp].

(I pressume he's missing because he's giving non-functional RvR quests.)

**Comment by Evildoor** [comment]
I've not tested this quest, but i'm pretty sure that Zaccur was added to Raven's Edge. Will check the quest later.

**Comment by CarlistRieekan** [comment]
Hey, Evildoor.
The quest works, of course.

This submission is from Jun 20 (before Zaccur was added) and can be closed as outdated.

**Comment by Evildoor** [comment]
Thanks for the confirmation, closing.

**Comment by Evildoor** [comment]
Broken again according to #2119 - Zaccur does not completes quest, and quest text is wrong.
