### ISSUE TITLE
Item Set: Fortune's Baubles

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7930]
Category: Jewelery
Number of  Items: 4
Item Names: Hapless Ha'penny, Gorkamork, Wind of Change, Fullbelly's Lucky Foot

Problem: Set bonuses are not working.

![1](https://cloud.githubusercontent.com/assets/18719012/18877074/4b9eb9a0-84cc-11e6-92ac-482ff17c3cd1.jpg)

![2](https://cloud.githubusercontent.com/assets/18719012/18877081/5021000a-84cc-11e6-8c50-fa8852d986b5.jpg)

![3](https://cloud.githubusercontent.com/assets/18719012/18877087/539d139a-84cc-11e6-9f33-3c9a213a7de1.jpg)

![4](https://cloud.githubusercontent.com/assets/18719012/18877091/57656b08-84cc-11e6-9af3-cde5ac3c2681.jpg)

**Comment by Luth-RoR** [comment]
Works fine for me; tested with .getstats on a naked char with only the jewelry set equiped:
![luthengi_000_crop](https://cloud.githubusercontent.com/assets/8567481/18879146/899e7342-84d3-11e6-975c-a8baf047bb85.jpg)

The character window/paperdoll is still unreliable though.

**Comment by Ezella** [comment]
Used .getstats and yes it worked for me too. Sorry for the superfluous work mate.
