### ISSUE TITLE
T1 lair Bugg !! 

### ISSUE THREAD

**Issue by Claudiamus** [WarEmu/WarBugs#7932]
I maked today T1 lair Dwarf and Elf and when boss was low (IB i was taunting) boss just killed me and i saw the Shiny things thats shows i have the drop ! when returned lair was no drop ! Same thing happens at Elf ! Hope you can resove the bug

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/6885
