### ISSUE TITLE
Yer a Weakling' and You'z Squishy

### ISSUE THREAD

**Issue by roadkillrobin** [WarEmu/WarBugs#7933]
Neither of these attacks are considereed an actually attack and won't trigger Ere We Go, I'm 100% sure the did so on live, they actually won't even aggro NPC mobs.

**Comment by ozarmidrashim** [comment]
They are not attacks and will not trigger 'Ere We Go!. Sorry, but the definition of an attack is pretty clear: attacks dela damage. It is for you to demonstrate hard proof that this happened on live, "100% sure" is against the rules of the tracker.

**Comment by roadkillrobin** [comment]
So if they arn't attacks, how come they can be both disrupted and blocked????

**Comment by roadkillrobin** [comment]
![heman_000](https://cloud.githubusercontent.com/assets/16356956/18902657/abb7c222-8554-11e6-8711-5c8c039c5f1d.jpg)
![heman_001](https://cloud.githubusercontent.com/assets/16356956/18902660/af50084a-8554-11e6-819f-59707b0f6edb.jpg)
![narfzon_032](https://cloud.githubusercontent.com/assets/16356956/18902747/1e6a8cd2-8555-11e6-8b24-e224e7d16d22.jpg)

**Comment by bloodi** [comment]
Are you seriously arguing that debuffs are attacks?

**Comment by roadkillrobin** [comment]
Are you seriusly argueing that they arn't? I presented proof here that they are attacks that can be defended like any other attacks by the game mechanics called Block and Disrupt. So either they are not attacks and can't be defended. Or they are attacks and can be defended against but then they need to proc everything that other attacks does aswell. Offensive spells that arn't attacks are Detaunts/Tauny/Challange these spells can't be disrupted or blocked and are therefor work acordoing to the mechanics of the game. But Listed spells are NOT.

**Comment by bloodi** [comment]
No, if what you said had any truth behind it, they also would proc Frozen touch and the dok covenants, yet they dont.

If getting "disrupt" made it an attack things like Terrible Embrace would also proc things, they dont.

You are just trying to grasp at straws to get a buff for shamans, spells are spells and they are all not attacks, simple as that.

**Comment by roadkillrobin** [comment]
So were's your proofs Bloodi???
You're just asuming that the current in game mechanic of "debuff" is the right one. I actually presented  proofs of the wording of Block and Disrupt, and they CLEARLY state that ATTACKS is what you're DEFENDING against.

**Comment by Luth-RoR** [comment]
May i ask the gentlemen to continue the controversal discussion on the forum?

**Comment by bloodi** [comment]
My proof is that someone who has access to the client told you are wrong and the fact that every single spell that can get disrupted but its not an attack, as in, the debuffs, behaves in that manner.

You are taking a tooltip as your proof.

@Luth-RoR I dont think there is much to discuss here to be honest.

**Comment by roadkillrobin** [comment]
I've said what i needed to say. The inconsistancy of the interactions with the rulings are pretty straight forward. If you chose to change the rulings it's totally up to you.
