### ISSUE TITLE
Shadow prowler bugs attacks

### ISSUE THREAD

**Issue by runebbb** [WarEmu/WarBugs#7937]
![sirren_025](https://cloud.githubusercontent.com/assets/20157418/18927161/0b2b94d4-85bb-11e6-9f04-66dd99a02920.jpg)
![sirren_024](https://cloud.githubusercontent.com/assets/20157418/18927163/0c03edf2-85bb-11e6-9d98-748a939f0779.jpg)
 basicly if you get the bug you wont be able to attack for a good 30 sec before you get the skill of CD again

**Comment by Luth-RoR** [comment]
Couldn't reproduce it on the dev server.

**Comment by runebbb** [comment]
i'll look more into it and post a video then since im not sure what couses it but it happends often at times and rearly other times sounds good?

**Comment by Luth-RoR** [comment]
That would help of course. I tested it with a level 10 WE and about 20 times only.
