### ISSUE TITLE
T1 Dwarf Quest: Stout and Bitter

### ISSUE THREAD

**Issue by Deladriendil** [WarEmu/WarBugs#7940]
Requirements: 
Escort to Third Post
Escort to First Post
Escort to Second Post

Continue to Stemni Bitterstone afterward.

The caravan never spawns, yet you can speak with Stemni to complete the quest. However, he expects you to pick 2 rewards (of 3 total). When you select two and attempt to complete the quest nothing happens.

**Comment by Ryanfawkez** [comment]
The caravan spawns and scripted movement paths are not yet implemented. However, the quest should allow you to pick two rewards; a class-specific shoulder piece and a trophy.

**Comment by Deladriendil** [comment]
Attempted this again on my character Falgrimm. The issue isn't that scripting has yet to be implemented. The issue is being unable to complete quest when two rewards are selected.
