### ISSUE TITLE
Quest: Disenchanting the Stone

### ISSUE THREAD

**Issue by LessRight** [WarEmu/WarBugs#7942]
Quest: Disenchanting the Stone
Faction: Destruction
Zone: Shadowlands
Coordinates: 20k, 54k (the Stone of Ecelsion)
Objective: Collect 10 Dark Gems

The Adorned Gems that cover the Stone of Ecelsion area do not give a Dark Gem when right clicked.

**Comment by Soulwhisper** [comment]
This can close.Patched.
