### ISSUE TITLE
Quest: Unmasked

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7944]
Realm: Order - High Elf
Region: Shadowlands
Quest Giver: Argolis Wildhelm at Mathrin's Watch, Chapter 5

Subject: Find Uthorin List
Target Coordinates: 47k/16k

Problem: Quest marker for target area on the map is missing

![1](https://cloud.githubusercontent.com/assets/18719012/18943634/2b25df22-8621-11e6-97ae-18ae347d20cf.jpg)

![2](https://cloud.githubusercontent.com/assets/18719012/18943639/301868a6-8621-11e6-90be-fdfe5f443889.jpg)

![3](https://cloud.githubusercontent.com/assets/18719012/18943646/37ba7748-8621-11e6-9ff0-d759c6934da8.jpg)

![4](https://cloud.githubusercontent.com/assets/18719012/18943673/5b5ceb18-8621-11e6-99b3-970ac7c16e57.jpg)

![5](https://cloud.githubusercontent.com/assets/18719012/18943676/6150e466-8621-11e6-9998-eea72123a50a.jpg)

**Comment by saupreusse** [comment]
Fixed in the next patch.

**Comment by saupreusse** [comment]
Btw, awesome Bugreport. comes in very handy.

**Comment by Ezella** [comment]
ty, just want to make your much appreciated work as comfortable as possible
