### ISSUE TITLE
Objective-based scenarios give rewards for killing

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#7945]
aren't they supposed to give no rewards for killing?
they are giving a lot of renowns for killing atm
i've checked changelogs and found no words about going back to give rewards for killing

and winners score scaled up to 500 but losers score don't scale up

![ph1](https://cloud.githubusercontent.com/assets/19988772/18946323/52eb2c68-8669-11e6-94a1-e2aab613a4bb.jpg)
![ph2](https://cloud.githubusercontent.com/assets/19988772/18946327/574cb704-8669-11e6-908f-06e38d9bab3e.jpg)
![li](https://cloud.githubusercontent.com/assets/19988772/18946331/5cdcf51c-8669-11e6-8283-5a62339601d9.jpg)
players who got highest renown are under 40 RR ranks 
premade tend to queue only these SCs
my apology if it's not a bug

**Comment by sioding** [comment]
This is fixed long ago
