### ISSUE TITLE
Renown points missing? 

### ISSUE THREAD

**Issue by runebbb** [WarEmu/WarBugs#7948]
![sirren_027](https://cloud.githubusercontent.com/assets/20157418/18964780/a6cc35e6-867a-11e6-98e2-8a98be6c69cd.jpg)
says i got no renown points used/at all and im RR 45 havent used it in a small while but it seems like everything was reset and i got no points to spend anywhere

**Comment by runebbb** [comment]
i can take screenshots of the entire list of skills but i dont se the point since what it says in the points i got and to spend

**Comment by Luth-RoR** [comment]
Did you try something else, relog etc.?

**Comment by runebbb** [comment]
nvm it seems to be working after relog my bad (:
