### ISSUE TITLE
 Appearance bug after ress

### ISSUE THREAD

**Issue by skizzo666** [WarEmu/WarBugs#7950]
An ally resurrected me during a keep siege and this bug appearance popped up. I tried to die and mount and dismount but it didnt resolve the visual bug. Here is attached a video that I uploaded in youtube to prove this.
https://www.youtube.com/watch?v=cEyL5zW67pE

**Comment by Luth-RoR** [comment]
That's a LoL video.

**Comment by Soulwhisper** [comment]
@Luth-RoR He probably means this : https://www.youtube.com/watch?v=23pB8-2gW4M

**Comment by Luth-RoR** [comment]
Thanks.

**Comment by Torquemadra** [comment]
I knwo what this is, closing
