### ISSUE TITLE
Order High Elves Chapter 9 thirf influence reward contain different stats

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#7952]
Looks like Kotbs reward missing 10 toughness in compare with SM's. (Выносливость = Toughness)
 ![default](https://cloud.githubusercontent.com/assets/18102127/18976701/11b74c8e-86c5-11e6-8648-25961b9089f7.png)

**Comment by Soulwhisper** [comment]
Im providing IBs helm from High Elf Chapter 9 which misses too 10 toughness like Kotbs.
![pordh_000](https://cloud.githubusercontent.com/assets/16864486/18985953/39e82ea6-8703-11e6-9574-1789f59e5c13.jpg)

**Comment by wargrimnir** [comment]
Fixed a long time ago
