### ISSUE TITLE
suppression vs ram[chosen][skill]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#7953]
dosen't buff when used on ram

**Comment by Tesq** [comment]
it was workign some patch ago, so it was implemented

**Comment by Luth-RoR** [comment]
I think there was a misunderstanding as _Suppression_ is not a tank archetype RvR ability, but a specific class ability; the question is if it happens to other buff abilities too and if this is intended.

**Comment by Tesq** [comment]
so i need to test another skill on it which give a self buff? i can only think to some wp skill and kobs which i have not even in t2. Aza response may be better in this case, as even if they would not work it would still remain the doubt about if it's intended or not.
