### ISSUE TITLE
No realm controls Nordland - T1 bar is not moving for hours

### ISSUE THREAD

**Issue by razeklol** [WarEmu/WarBugs#7954]
We have the control of the 3 points in T1 empire, already for at least 1 hour and the bar is not going down. 

Thank you for looking into it!

**Comment by Ryanfawkez** [comment]
In order to lock a Tier 1 zone, you need not only total BO control, but a predominant lead on kills over the enemy. Perhaps your realm was dying too much, or did not get enough kills yet to claim full control over the zone.

**Comment by szejoza** [comment]
T1 works fine now
