### ISSUE TITLE
bathing in blood[skill][Black guard]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#7955]
suffer from the same problem of  corruption retribution before the fix it should not refresh itself or it make the tactic useless as you do not gain the benefith of the regen due to the refresh

**Comment by Tesq** [comment]
sy but what confirmation you need? the regen dosen't work as while you kills stuff it keep reset itself and you got no heals......

**Comment by Tesq** [comment]
This not dubbious any fix inc for this?

**Comment by dalen** [comment]
This has been fixed and seems to be working now
