### ISSUE TITLE
Warrant item bug+obdurate seal problem

### ISSUE THREAD

**Issue by AmidalaEstellanor** [WarEmu/WarBugs#7957]
1) I have taken from a green bag a warrant piece.I have taken from npc a willpower jewelry,but in my bag a int belt appeared.

2)My friend can't take from NPC  The Obdurate Seal
+4 Toughness
+12 Wounds
+89 Spiritual Resistance
+178 Elemental Resistance
+104 Corporeal Resistance

Giant Scorpion Stinger is equipped in his pocket

**Comment by Luth-RoR** [comment]
Only one issue per report please. 
For issue 2 https://github.com/WarEmu/WarBugs/issues/7958 will be used, as another item in the set seems to be affected too.
Issue 1 is way to unspecific (_from npc_, _a willpower jewelry_, _a int belt_) and can't be fixed at all without a :crystal_ball: .
