### ISSUE TITLE
RunePriest Ancestor's Echo

### ISSUE THREAD

**Issue by deadkoo** [WarEmu/WarBugs#7961]
So, I am unsure if a bug, or intended.. However, Ancestor's Echo will proc even if the recipient of the heal is at max health(Ie, everything is overcast). The tactic Blessing of Grungi doesn't proc on a crit(Nor have I noticed restorative burst) if the target is at max health, which makes me think it is a bug... But the wording on AE is about direct heals Cast, so possibly the effect is moot.

I was using the strat to grp-heal prebattle to have the bubble on everyone as the fight starts. But unsure if that is how it is supposed to work...

**Comment by Luth-RoR** [comment]
![luthrp_003_crop](https://cloud.githubusercontent.com/assets/8567481/19012309/94dbc3f0-87b1-11e6-95c4-3572b2bc9c4d.jpg)

All three tactics proc with a full HP bar and this works like on the mythic server; _a direct heal_ on an ally doesn't necessarily need to _restore healthpoints_.
