### ISSUE TITLE
Quest: For Honor and Glory

### ISSUE THREAD

**Issue by LessRight** [WarEmu/WarBugs#7964]
Faction: Order
Zone: Nordland
Coordinates: 25k, 56k
Objective: Speak with Stephan Busso

When you speak with Stephan, the quest will show "Speak with Stephan Busso 1/1," but talking to him only takes you straight to his vending menu. There's no way to turn in the quest with him, and he continues to have the yellow circle. The giver of this quest won't accept it either.

**Comment by Ryanfawkez** [comment]
Always get a prompt before the vendor window; can hand in the quest just fine.
