### ISSUE TITLE
Disciple Venomstung no longer offers T4 Jewellery

### ISSUE THREAD

**Issue by Gobtar** [WarEmu/WarBugs#7966]
The T4 Tome unlock jewellery are no longer available from Disciple Venomstung, and TOK references to unlocked items apear as ???, the character is still granted the unlock in both the achievements however.

Curiously Venomstung's available goods is similar to some of the other vendors in the library, where as before his options were unique.

**Comment by Luth-RoR** [comment]
There is some general issue with the merchant system atm; devs are at it.
