### ISSUE TITLE
Renown gear merchants not showing the proper trade window

### ISSUE THREAD

**Issue by Serbiansword** [WarEmu/WarBugs#7967]
Renown gear merchants in Altdorf are not displaying the proper trade window, i.d, you can't buy their items. When clicked upon, they are showing the last opened NPC trader window (in my case that's the special color trader window as showed in the picture).
![war-2016-10-01-11-43-04-90](https://cloud.githubusercontent.com/assets/22558420/19013275/68cb1f52-87cc-11e6-9b18-531dbc31e15a.jpg)

**Comment by Luth-RoR** [comment]
Known and high likely the problem as https://github.com/WarEmu/WarBugs/issues/7966

**Comment by DochiBaba** [comment]
Same in The Inevitable City with Elite Renown Gear Merchant.

**Comment by sioding** [comment]
**Thanks for the report.** Since there is no confirmation, i will close this issue now. Please make sure to follow the bugtracker rules which you can find here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)
