### ISSUE TITLE
Squig herder ability git em dmg bug

### ISSUE THREAD

**Issue by muniramunira** [WarEmu/WarBugs#7969]
hello,

the ability "Git em!" from the squig herder does too little dmg on the pets side of the attack.

Evidence in the screenshot (dmg log, ability description) 
![ginko_042](https://cloud.githubusercontent.com/assets/22560571/19014220/55eb4fcc-87e7-11e6-95d5-800e50886d23.jpg)

**Comment by milosxe** [comment]
What happens when you use Horned Squig instead? Afaik Git em dmg scales with str, and spikey has almost none of it.

**Comment by muniramunira** [comment]
just test it with the horned squig, it was about the same as the spiked squig.

**Comment by Pxl555** [comment]
Slot the tactic He's a Biggun' on/off (Increases squig strenght by 160) you will see its damage increase/decrease  respectivley .

**Comment by muniramunira** [comment]
was the same dmg acually, with "He´s A Biggun´" tactic he dealt 76 dmg twice.

The tactic "sharp toofs" is also not working. "Git ems dmg is increasd to 585 on your squigs first attack and the two ticks of git em from my pet were still both 76 dmg.

**Comment by Pxl555** [comment]
worked perfectly fine for me (damage increase/decrease with the tactic) , will need confirmations from luth about this

**Comment by muniramunira** [comment]
i dont know what you do but those tactics have 0 effect for me.

**Comment by Luth-RoR** [comment]
On the devserver:
Damage with tactic "he's a big un"

![luthgob_000_crop](https://cloud.githubusercontent.com/assets/8567481/19015442/aa173e72-8804-11e6-9a95-5f8229a596d2.jpg)

and without tactic

![luthgob_001_crop](https://cloud.githubusercontent.com/assets/8567481/19015446/b52606a4-8804-11e6-9b29-ea393b6eb645.jpg)

Sharp toofs tooltip says only "on the first hit", so it should work like intended.

**Comment by muniramunira** [comment]
now i get what you meant, thought it would be a big difference and not 30 dmg. This case is solved then, just the description of the ability shows your strength scalling for both yours and your pets attack is wrong.
