### ISSUE TITLE
Chosen belts

### ISSUE THREAD

**Issue by Shtrober** [WarEmu/WarBugs#7970]
Greetings ladies and gentlemans. I've noticed, chosens best belts have only 2% of parry and all other tanks  have 2% of block. Its seems unfair. I hope, you will change parry to block. I guess, names of that belts are: enervating deathgirdle (green one), grim deathgirdle (blue one) and brigand deathgirdle (purple one). As proof, I give you this screenshots from other tanks. 
![bg belt](https://cloud.githubusercontent.com/assets/16929424/19014719/48baaf44-87fd-11e6-9d2d-8cb5f563bee2.PNG)![bg belt gr](https://cloud.githubusercontent.com/assets/16929424/19014720/4d42ec3e-87fd-11e6-8987-c45b37bcdbba.PNG)
![bo belt](https://cloud.githubusercontent.com/assets/16929424/19014722/574eac18-87fd-11e6-9392-0a4f86ce1203.PNG)![kobs belt](https://cloud.githubusercontent.com/assets/16929424/19014723/5c35c914-87fd-11e6-8f74-50aec261126f.PNG)
![sm belt](https://cloud.githubusercontent.com/assets/16929424/19014725/6095f2a4-87fd-11e6-8d7f-ac72adbb222d.PNG)![sm belt b](https://cloud.githubusercontent.com/assets/16929424/19014727/66915a5e-87fd-11e6-8015-08a606670d80.PNG)
![ib belt b](https://cloud.githubusercontent.com/assets/16929424/19014726/64d322f6-87fd-11e6-95a4-45ba26099b61.PNG)![ib belt](https://cloud.githubusercontent.com/assets/16929424/19014746/c5cfb7a4-87fd-11e6-9d9b-dbdf806a54f1.PNG)
![chosen belt](https://cloud.githubusercontent.com/assets/16929424/19014729/67d5da16-87fd-11e6-9a40-76fb9d1b05bc.PNG)
Sorry, I didn't found some belts, cause they are ultra rare. My best regards.

**Comment by Luth-RoR** [comment]
Needs confirmation from DB devs if intended.

**Comment by Torquemadra** [comment]
historical, not a design choice , 2 hander chosens exist so not changing.
