### ISSUE TITLE
quitter debuff added when i don't join scenario

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#7971]
It suppose this debuff suppose to add if i quit scenario, not for rejection of joining. Now if I in a middle of the fight I don't have option not to have this debuff.
![tranquillity_026](https://cloud.githubusercontent.com/assets/18102127/19015164/1ecc242a-8810-11e6-84ab-fa6c989a8886.jpg)
![tranquillity_028](https://cloud.githubusercontent.com/assets/18102127/19015165/1ecce964-8810-11e6-9d55-c084d35f858d.jpg)

**Comment by Soulwhisper** [comment]
The Quitter debuff, which prevents scenario queueing, will now be invoked on players under the following circumstances:

- Explicit refusal of a pop.

**Comment by Yellowpillow** [comment]
reported before patch note.

**Comment by Luth-RoR** [comment]
As stated, it's working as intended atm; maybe it will be fine tuned in the (near) future.
