### ISSUE TITLE
Swordmaster weapons

### ISSUE THREAD

**Issue by Sprak2686** [WarEmu/WarBugs#7973]
I'm not sure if this is a bug or if this is where to report it... but I wanted to post either way, just in case there is something wrong. 

**Redwind** Increases my overall damage bonus more than the other 2 weapons. 
Weapon dps = 69.6
2.7 Speed
Strength = 72
Toughness = 20
Weapon Skill = 30

**Greatsword of Remembrance** Does improve armor pen by about 2-3 % more than Redwind, but damage is still lower.
Weapon dps = 76.9
3.4 Speed
Strength = 64
initiative = 15
Weapon Skill = 61

**Titans masterblade of Solemnity** significantly lower damage bonus and armor pen from other 2. (not entirely sure how important 4% crit chance is though).
Weapon dps = 74.2
3.4 Speed
Strength = 51
Wounds = 37
6 ap per sec
4% Crit chance

Not sure if the epic weapon is supposed to be the better weapon or not, considering its proc... Or maybe there is a calculation that isn't adding up properly or as intended.

Or maybe its as intended and this can be closed.

**Comment by Luth-RoR** [comment]
The character window is still unreliable; maybe it just displays the damage bonus from strength. The server side calculation should be correct though.
