### ISSUE TITLE
Quest: Faith Is Madness

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7976]
Realm: Order - Empire
Region: Chaos Wastes
Quest Giver: The Stranger at Fires of Sigmar, Chapter 22

Subject: Rescued from Confusion and Corruption
Target Coordinates: 50k/04k

Problem: Quest marker for target area on the map is missing

![1](https://cloud.githubusercontent.com/assets/18719012/19017244/93e6f4a6-8833-11e6-9155-ed66835fbdd5.jpg)

![2](https://cloud.githubusercontent.com/assets/18719012/19017246/990c960c-8833-11e6-87b9-fe19c5a56d70.jpg)

![3](https://cloud.githubusercontent.com/assets/18719012/19017248/9d968ad4-8833-11e6-9e27-94e6ec434a9f.jpg)

![4](https://cloud.githubusercontent.com/assets/18719012/19017250/a4353f3e-8833-11e6-9425-eb062ce2ba7d.jpg)

![5](https://cloud.githubusercontent.com/assets/18719012/19017252/aa3096ea-8833-11e6-99c0-080d4fa48448.jpg)

![6](https://cloud.githubusercontent.com/assets/18719012/19017254/af8f03d8-8833-11e6-8fba-3d9305c6628b.jpg)

**Comment by Soulwhisper** [comment]
Patched.
