### ISSUE TITLE
Quest: Clearing The Way

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#7977]
Realm: Order - High Elf
Region: Ellyrion
Quest Giver: Thalian at Reaverspring, Chapter 9

Subject: 'Invalid Game Object' and kill Uthorin Barbspear
Target Coordinates: 32k/45k

Problem: Invalid GameObject - QuestID 34823,ObjId=11113

![1](https://cloud.githubusercontent.com/assets/18719012/19017272/72910ebc-8834-11e6-961e-61743fcc7c16.jpg)

![2](https://cloud.githubusercontent.com/assets/18719012/19017273/782fcb88-8834-11e6-8a93-192c6e74f36a.jpg)

![3](https://cloud.githubusercontent.com/assets/18719012/19017274/7b85785a-8834-11e6-9fa3-39e6b2583aaf.jpg)

![4](https://cloud.githubusercontent.com/assets/18719012/19017276/80f6e2d8-8834-11e6-8873-925644ad5aaf.jpg)

![5](https://cloud.githubusercontent.com/assets/18719012/19017277/857fd0c6-8834-11e6-99c3-800ec6043c94.jpg)

**Comment by Ezella** [comment]
Reference: #7596

**Comment by Soulwhisper** [comment]
Patched.
