### ISSUE TITLE
Shadow Warrior Stances and weapon procs

### ISSUE THREAD

**Issue by HappyCultist** [WarEmu/WarBugs#7979]
Hi there!

Beithir(Decay IX)
Nightstalker(Concussion IX)

After logging in with no active stance selected, both procs work.
Now, as soon as i'm switching into a stance (scout/assault/skirmish-doesn't matter), neither of those two procs work anymore.

I never had any proplems with my other toons, using t4 epic weapons.

**Comment by Torquemadra** [comment]
#6615
