### ISSUE TITLE
Keep bag for wrong zone

### ISSUE THREAD

**Issue by akalukz** [WarEmu/WarBugs#7981]
I was in Praag earlier, took a couple of undefended bo's then went to TM to help defennd keep.   Killed several players solo around bo's in TM, then on way back to keep I joined an Open WB.   Made it almost all the way to TM keep (defense) saw a bag roll, thought it was for TM defense, went into keep, no chest spawn outter still up.  Then noticed that bag rolls was for southern garison in Praag.  One or two members of my group in the open warband were in praag.  I placed and got a bag in a keep take I wasn't even a part of, never even went to that keep.

Akalukz.  I have some SS if needed.

**Comment by akalukz** [comment]
![akalukz_015](https://cloud.githubusercontent.com/assets/19689379/19021634/683316bc-8894-11e6-8b58-782bdfb4cac0.jpg)

**Comment by Luth-RoR** [comment]
Rewards for contribution works like this now; you even get mails for keep/area captures from your earlier contribution when you are offline.

**Comment by akalukz** [comment]
ok, but i was never at South Keep in praag.  just wanted to point this out
