### ISSUE TITLE
Quest Necessary Regret provides useless rewards

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#7983]
Judging by icon there should be HOT potion and strength buff potion to choose.
![tranquillity_040](https://cloud.githubusercontent.com/assets/18102127/19024195/6704254e-890f-11e6-9f12-192096cee270.jpg)
![tranquillity_041](https://cloud.githubusercontent.com/assets/18102127/19024196/6704e8e4-890f-11e6-8b61-3c5d1718871f.jpg)

**Comment by sioding** [comment]
fixed with patch from 01.06.2019
