### ISSUE TITLE
Invisible mounts

### ISSUE THREAD

**Issue by Illimo** [WarEmu/WarBugs#7985]
Been experincing players running around with their mount buff active, while not actually mounted
In Howling Gorge scenario they can pick up the powder keg while still running with mounted speed
and my attacks did not unmount him, or rather make the "mount buff" disappear.

**Comment by Illimo** [comment]
![shaelen_001](https://cloud.githubusercontent.com/assets/22582200/19025643/debaf386-891b-11e6-9306-8a3b6b251399.jpg)

**Comment by Illimo** [comment]
Managed to pull it off on one of my characters.
Still running in mounted speed, not quite sure what causes it though

**Comment by Torquemadra** [comment]
#798
