### ISSUE TITLE
PvE Drop / Mailing issue : Enervating Warp pendant ( jewel 37)

### ISSUE THREAD

**Issue by Yaliskah** [WarEmu/WarBugs#7986]
This pendant droped in PvE ( green lvl 37) is linked to player. Dunno if it normal other "Enervating" items aren't.

**Comment by Ryanfawkez** [comment]
https://github.com/WarEmu/WarBugs/issues/7574 - seems your item was bound during the days this bug was active. Sadly, nothing can be done about your current item; it's bound forever to you now.
