### ISSUE TITLE
Quest Bug "The Sport of Princess" - killing NPC target-objective is not recognized by quest

### ISSUE THREAD

**Issue by sotora** [WarEmu/WarBugs#7989]
Location: Eataine
Realm - Destruction
Quest giver:  Celmar Gravemist @ Asuryan's End camp.   42988, 41980
Quest objective: Luinor Truelight and his escorst 58800, 53000

Situation&Problem:
Killing Luinor Truelight escorst is registered while killing Luinor Truelight himself is not registered. Thus quest cannot be finished.

How-to reproduce:
Accept Quest from Celmar Gravemist @ Asuryan's End in Eataine and go kill Luinor Truelight with his escorts.

![rani_053](https://cloud.githubusercontent.com/assets/22590838/19038614/966b89ae-897c-11e6-9996-f7f850590c21.jpg)
![rani_052](https://cloud.githubusercontent.com/assets/22590838/19038622/9baf77c2-897c-11e6-9313-c8dbf4fcec67.jpg)

**Comment by Soulwhisper** [comment]
Patched.
