### ISSUE TITLE
Any change in non-set gear drops an set-bonus mastery point from Mastery Tree

### ISSUE THREAD

**Issue by sotora** [WarEmu/WarBugs#7992]
_Problem_

Change in any item equipped, either equipping new one to a empty slot, swapping anything or unequipping anything -  Including trophies, jewelry or weapons - take out bonust mastery (from 5 piece set) point from an relevant tree.

From reports of other players it seem like an general issue that plague all sets and all classes.

Personally I confirmed it with Ruin and Anihilator WE sets. 

_How to reproduce:_

Equip any 5 piece set that give bonus mastery point.   Equip, swap or unequip any non-set equipment such as weapon, cloak, jewelry or trophy.

**Comment by Luth-RoR** [comment]
Known issue: https://github.com/WarEmu/WarBugs/issues/7024
