### ISSUE TITLE
Aphotecary window not accepting container - with bug reproduction how-to

### ISSUE THREAD

**Issue by sotora** [WarEmu/WarBugs#7993]
_Problem:_

After adding container flask and all ingridients if player click "Brew" button "too fast", Apthotecary window won't accept another stack of flasks.  Only solution seem to relog.

_How-to-reproduce:_

Add flasks and ingridients.  Click on "Brew" button as fast as you can until you use up all flasks&ingridients.   Tried few times = 100% reproduction rate.

**Comment by Luth-RoR** [comment]
Could this be related: https://github.com/WarEmu/WarBugs/issues/7993

**Comment by sotora** [comment]
It most likely is related to #7411,  when I first asked about crafting window not accepting more craft ingridients in /advice I got multiple resonses fast so it seems like widespread issue.  

It is easy to both avoid and reproduce as It never happens (for me) if I click "Brew" button with slow or moderate speed and has 100% reproduction rate if I click "Brew" button very fast on purpose when trying to reproduce this bug. 

I think it affects Talisman Making window/crafting too, but I haven't tried to reproduce it there yet.

**Comment by sotora** [comment]
Bug presentation video:
https://my.mixtape.moe/jnnykc.mp4

**Comment by Kaelang** [comment]
Video link doesn't work for me, and I was unable to replicate this on the latest version of RoR. Please re-open if issue persists with a new video highlighting how to replicate the problem.
