### ISSUE TITLE
PQ : Beacon of Firengrom - partially untargetable and fully unlootable Stage I objective NPCs

### ISSUE THREAD

**Issue by sotora** [WarEmu/WarBugs#7994]
Zone: High Pass
Realm - Destruction
PQ: Beacon of Firengrom
Coordinates: 30495, 7575

One of objectives of first stage is to kill 10 Beacon Groblars.   Those NPCs are untaretable by mouse click, player has to wait till Becon Groblar will be pulled by agrooed Ogre (other NPC that in the area and is targetable normally) and then to game ui to target Beacon Groblar automatically (it does that when mob is attacking player and player has no target selected).   Another work-around is to attack/agroo them by using AOE skills that don't require targetting if player class has such skills.

Once dead Beacon Groblars seem to be theoretically lootable (specific glow/sparks above NPC body) but since they are not normally targettable player cannot loot them.

**Comment by Soulwhisper** [comment]
Yeah its the issue with other PQ Mobs too.You cant target them.If you find any other please report them like this! Thanks!

**Comment by sotora** [comment]
I will :)
