### ISSUE TITLE
DoT's on combat log minor bug

### ISSUE THREAD

**Issue by gke96** [WarEmu/WarBugs#7997]
Entering a dots all damage over time in one entry to the combat log even if its recast. (The recast thing is about that an engineer dots total damage will never get close to 21k even with crit if its cast only once so I just presumed its cast multiple times)
![horsewhisperer_028](https://cloud.githubusercontent.com/assets/11146551/19053817/3f848cf0-89c5-11e6-8aa8-10d45b5a0f48.jpg)
![horsewhisperer_029](https://cloud.githubusercontent.com/assets/11146551/19053823/45ee79d4-89c5-11e6-9100-df0f9180b9bf.jpg)

**Comment by gke96** [comment]
Btw this isn't the first time im seeing something like this but also this doesnt always happen i think

**Comment by Luth-RoR** [comment]
Known issue: https://github.com/WarEmu/WarBugs/issues/2645
