### ISSUE TITLE
SC Wep R39 not Converting Magic crt/Zealot

### ISSUE THREAD

**Issue by Hyronen** [WarEmu/WarBugs#7998]
Hello,
R39 sc wep dosent switch the magic crt to healing crt when using Harbinger of Doom.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/7856
https://github.com/WarEmu/WarBugs/issues/7825
https://github.com/WarEmu/WarBugs/issues/7310
