### ISSUE TITLE
Your current level is too low to use that skill (Barrage)

### ISSUE THREAD

**Issue by Illimo** [WarEmu/WarBugs#7999]
When playing on my SW when i try to use the mastery skill "Barrage" it says "Your current level is too low to use that skill" sometimes the skill activates, and sometimes not
![shaelen_007](https://cloud.githubusercontent.com/assets/22582200/19059124/a6bf71ba-89dd-11e6-8693-d630b5917030.jpg)

**Comment by Illimo** [comment]
As you can see here im way above the Barrage skill so this should not be a problem, and yet..
![shaelen_006](https://cloud.githubusercontent.com/assets/22582200/19059134/c72dd022-89dd-11e6-9157-67d3ff0102be.jpg)

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/4964
https://github.com/WarEmu/WarBugs/issues/4072
