### ISSUE TITLE
"Enemies Abound" part 2. cannot interact with NPCs

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#80]
On this quest, you are required to "interrogate" 15 suspicious characters outside the Grey lady inn.

My memory is a little fuzzy on this quest as I seem to think it was just 5 people to "interrogate" with. I checked the website and it also says 15.

Link: http://warhammeronline.wikia.com/wiki/Enemies_Abound_II

Perhaps someone else could confirm either way. 

Anyway, that said. Since characters cannot be interact with. This quest cannot be done.

![enemies about part 2](https://cloud.githubusercontent.com/assets/7492543/2922069/50a72c14-d6fc-11e3-8c5d-03b296673bf1.png)

**Comment by Reggaewaldo** [comment]
This has been set to 15 interactions according to the source:
http://warhammeronline.wikia.com/wiki/Enemies_Abound_II

I have set so that you can talk to them to interogate them. I will test this when I have access to the Test client.

**Comment by Reggaewaldo** [comment]
This is working to just right click to interact as of now. I will close this for now.
