### ISSUE TITLE
[Global Bug] The quest icon lights up like it was finished immediately after receiving

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#8000]
The quest completion icons appearing above NPC before it was actually complete, and i think it is not the random bug. In fact, they appear immediately after getting the quest. Tests show: they always lights up orange immediately in the case where the assignment location, the one marked with a red, coincides with the area in which stand the NPS who suppose to receive quest after completion.
  My theory are as follows:
In the normal order (on live) after receiving the quest there is mark on the area appears, pointing where to done it's objectives. After completion of the quest's objectives this mark disappears and another mark reappears to show the area where you can find NPC who will take the quest off you and provides rewards. On a private server, only one mark of the area appears - the area with the objectives. The client saw that the area is located in a zone where the NPC stand, saw that the mark is the last in quest, mistaking it for the mark of area marked for the delivery of completed quest, and illuminates an orange icon of the completion.
  Tests have shown that this bug does not appear if NPC who provides the quest stand inside marked area, but he has another one or several quests to choose.
  If the NPC who provides the quest is within marked area, but after objectives will be completed the quest need to be take off in another place with another NPC - the icon does not light up. This confirms my theory.
  If the NPC is in RvR warcamp and the quest's objectives supposed to be done inside RvR lake, the orange icon of quest completion lights up immediately after receipt, the client probably sees RvR lake and a warcamp as one location, and because this mark is last one in quest - client lights up orange the NPC's icon.

**Comment by Lheana** [comment]
@MaxHayman I think we can close this one?

**Comment by Lheana** [comment]
This has been fixed.
