### ISSUE TITLE
(BG) WP buff from Brutal Smash not affecting Disrupt% 

### ISSUE THREAD

**Issue by ninepaces** [WarEmu/WarBugs#8003]
I tested on some gors in IC:

I cast brutal smash with max hatred raising my willpower from 150>>450. The chance in stat appears in character page. When I switch to defense page to check disrupt % it doesnt change. Not sure if visual bug or something wrong with ability. 

Thanks.

**Comment by ninepaces** [comment]
Actually I'm fairly certain this is visual bug as other buffs of willpower like a willpower pot isnt changing the disrupt % either.

**Comment by Yellowpillow** [comment]
probably well known client bug, you should use .getstats command to test any stats related things.
