### ISSUE TITLE
 Improvised Upgrades stack up to 8 times instead of 5(Engineer)

### ISSUE THREAD

**Issue by Morulan** [WarEmu/WarBugs#8007]
As of today, Improvised Upgrades stack up to 8 times(+32% damage) instead of 5(+20%). No idea how it works for Magus(at first I thought it was because of Expert Skirmisher, but after checking it without it, it still stacks up to 8 stacks)

**Comment by Luth-RoR** [comment]
This was pushed on live with the last patch/hotfix; it actually meant to be tested a little longer on the devserver, but it's not a bug.
