### ISSUE TITLE
Warhammer , Return of Reckoning 

### ISSUE THREAD

**Issue by LazaridesKyriakos** [WarEmu/WarBugs#8008]
Empire Ostland , tier II , pqs out of order tho farmable .
Old Brier area , imperial troops appear hostile to Order Players 
Have gained an unlock : Undead Tactic Fragment (0/12) , by killing a necromancer in the area of Old Brier

**Comment by LazaridesKyriakos** [comment]
Please fix one Public Quest for the Empire Chapter 8

**Comment by Luth-RoR** [comment]
Only one bug per report and the report is way to unspecific.
