### ISSUE TITLE
Disconnects linked to guild tag

### ISSUE THREAD

**Issue by Mizrim** [WarEmu/WarBugs#8009]
I get DC's and problems connecting to the game with Chr's that are members of Nazgul. The DC's occur during transitions, zone to zone and on entry & exit of sc's which now result in Quitter debuff. Also toons take multiple attempts to log into server on occassion. I have tested with non guild tag toons vs tagged toons. Chrs effected are
Mizrim
Corvuscorax
Daemonica

any Chrs I have not in Nazgul have no issues. I understand that other members of Nazgul may also be effected.

**Comment by Luth-RoR** [comment]
The root for this problem is still unknown; unfortunately atm the only (temporary) fix is to leave the guild.

**Comment by Luth-RoR** [comment]
From https://github.com/WarEmu/WarBugs/issues/9742

>I had the problem with my char that i have dcs when i tried to join scs when i was in a guild. I tried some things, even with the help from a gm. Nothing really helped.

>**Now i changed my char name and i havent any dcs**. Maybe this simple trick solves this problem.

**Comment by MaxHayman** [comment]
I assume this is now fixed.
