### ISSUE TITLE
WL pet bar issue 

### ISSUE THREAD

**Issue by Hekireki** [WarEmu/WarBugs#801]
it disapear each 10 sec or so, sometimes my pet disapear too, sometimes it's just the icon bar, sometimes there is the icon bar but without the abilities of training to kill for exemple. Also my pet doesn't get the bolster when I join an area rvr, I have to summon him again... the cooldown is 15 sec, if I have to summon him again because any other bug occur I have to wait 30 sec in rvr area praying to avoid opponents. 
Not a bug but I think the cooldown is too big, also the fact that the nature's bond is pretty much useless it heals nothing and our pet die in 5 sec pretty much :/

**Comment by jelczi** [comment]
Same with the Squig Herder whenever you get too far away from him on the mount. Or out of the blue sometimes.

Ability bar disappears and the squig is stuck in whichever mode it was in,
Can't command it, but it will attack and use skills if on aggressive/defensive. game does not register as you having a pet active - cannot use squig frenzy nor tastes like chicken.

**Comment by NervZ** [comment]
So, i spent some time the last 2 days playing a WL. The lion is buggy. As it mentioned the bar disappear most of time after ~2mins even if the lion is next to you. However, the lion still keeps to assist you if it was in aggressive or defensive mode.
The stances do not work properly. Most of time if you wanna get a specific stance's skills u have to unsummon the pet change stances back and forth few times and then summon the pet again.
The skills cannot be deactivated and most of them the pet never use them auto or it uses them very rare.
For me though the worst thing was the speed of lion... It so slow that if you chase an enemy the lion isnt able to reach him. Same, when u try to run away from an enemy and want the lion atk him and use the slow ability it cant reach it.
In general, WL is so weak right now.. It has some good burst dmg if you are lucky and the pet is next to you with the pet bar not disappeared and the enemy stands still. My toon is 20/19 blue/green geared and i got outdps by all the rest mdps classes. In a good SC for me i will get maximum 40k dmg when with my 16lvl choppa i did 90k dmg today.

**Comment by ozarmidrashim** [comment]
Closed, we'll use the more recent thread regarding pet issues
