### ISSUE TITLE
Tome unlock for killing 10K Dark elves not working correctly

### ISSUE THREAD

**Issue by Grendel1892** [WarEmu/WarBugs#8010]
recently killed my 10026 dark elves and got the unlock for killing 100K but never for killing 10K.
![indranor_001](https://cloud.githubusercontent.com/assets/17376568/19084324/1955497e-8a34-11e6-99b6-69d798ce4712.jpg)

**Comment by Ryanfawkez** [comment]
Whoopsie.

**Comment by Soulwhisper** [comment]
Patched.
