### ISSUE TITLE
Mounts dissapearing?

### ISSUE THREAD

**Issue by Rutena** [WarEmu/WarBugs#8011]
I haven't had it happen to myself, but I've heard people talking about 10g and even 100g mounts suddenly having disappeared out of their inventory when they log out and back in. Didn't see it posted here so thought I might

**Comment by Soulwhisper** [comment]
I heard that too.But most likely it was due to rollbacks.

**Comment by Torquemadra** [comment]
I appreciate your sentiment but if someone else has a bug they should post it, we cnat work on 3rd party hearsay
