### ISSUE TITLE
[Engineer] Keg tick x2 in 1s

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#8013]
Double tick, not 100% time but quite often.

**Comment by Luth-RoR** [comment]
Could be lag, needs evidence/confirmation.

**Comment by MKorin** [comment]
http://oi64.tinypic.com/29z7zoy.jpg

**Comment by M0rf** [comment]
Double tick is legit, keg has a 10 sec cooldown and lasts for 15 seconds so you can get 2 double ticks before the first keg you used disappears.

**Comment by Luth-RoR** [comment]
True, thanks.
