### ISSUE TITLE
Stationary skills like Gunshot and Snipe can be used while walking(details inside)

### ISSUE THREAD

**Issue by Morulan** [WarEmu/WarBugs#8015]
I can't cofirm whether it works with other classes. but, atleast as an Engi, if I toggle walking(instead of the normal running), and start casting a spell while stationary, I can continue to move without the cast interrupting, and it also works with my channeling skill Focus Fire: start it while stationary, toggle walking, and I can move while dealing damage. 
It works as intended if I have running toggled on: I start casting a spell, I start moving, the spell gets interrupted.
EDIT: And I also think that it works like that if I'm slowed by Shaman's green field(however the spell may be called) or any other slowing effect, but I can't confirm that

**Comment by Soulwhisper** [comment]
#8015 Already known.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/1540
