### ISSUE TITLE
[Item] Gork's Toof

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#8018]
Dunno if bug but proc give "empty" wounds, no heal.

**Comment by Luth-RoR** [comment]
Which item is that (screenshot would help etc.)?

**Comment by MKorin** [comment]
Its epic quest (The Ebon Flame) reward for shaman

**Comment by Luth-RoR** [comment]
Ok, thanks. Waiting for dev reply if intended (probably not intended, but don't know).
