### ISSUE TITLE
WP /Tactic "Intimidating Repent" resets when equip/unequip 2H Hammer

### ISSUE THREAD

**Issue by Warfox81** [WarEmu/WarBugs#8019]
For Healspec i learned the Tactic Intimidating Repent in Skilltree Path of Wrath.
Works Great with 1h Hammer and Offhand Tome.
But in this Moment when i equip and unequip a 2H Hammer, which one has that Ability too, the Mastery Intimdating Repent resets.
Than i must go visit Masterytrainer and learn it again.

**Comment by ozarmidrashim** [comment]
You're not supposed to have Intimidating Repent on when using a two-handed weapon, because any two-handed weapon casts the tactic.
