### ISSUE TITLE
Guild recall scroll timer bug

### ISSUE THREAD

**Issue by Gorbagg** [WarEmu/WarBugs#8020]
When i use the Guild recall scroll a 30mn timer appears, but if i buy a new one this timer disappear so i can't see when i can use it again.

**Comment by Kaori1** [comment]
Have you tried dragging the item to one of your action bars? It might display the cooldown like a normal ability.

**Comment by Luth-RoR** [comment]
From https://github.com/WarEmu/WarBugs/issues/9752
>When using the recall scrolls and LEAVING the guild hall the cooldown of guild recall scrolls gets reset. It still shows the 30min timer on the scroll icon, but when clicking the scroll is usable.

>Now, when using the recalls scrolls, buying new scrolls and leaving the guild hall the timer even resets on the scroll icon and is no longer displayed as "in cooldown".
In the moment when using guild recall scrolls (that would normally still have a cooldown) the regular cooldown is shown on the scroll icon and will remain (without effect) if you cancel scroll activation.

>Effectively recall scrolls have no cooldown timer at the moment. However they know that they should have one and know their regular cooldown time.

**Comment by Benwyse** [comment]
this is actually not the same problem as #9752

this here talks about a bugged display whereas the timer still works and scrolls are not usable when in cooldown.

#9752 talks about the cooldown not working. scrolls are usable without cooldown.

**Comment by Luth-RoR** [comment]
There is a disparity what's shown on the client and what's happening on the server for the guild scroll item in both cases and the issues have probably the same root and will therefore be fixed altogether.

**Comment by Benwyse** [comment]
agreed. just wanted to make sure you dont mix up the 8 months old problem with the new one :)

**Comment by Kaelang** [comment]
As this is a legacy issue, and lots has changed, please re-open if this issue persists as it should be fixed.
