### ISSUE TITLE
Quitter Debuff Bug

### ISSUE THREAD

**Issue by Sileq** [WarEmu/WarBugs#8023]
When the Scenario menu appears. Basically: Join scenario etc. 
Leaving a queue for another scenario, will evoke the Quitter Debuff despite the scenario offered being completely different.
My anecdote: I clicked 'Join All' on all Scenarios. Now I don't want to do Caledor Woods so I click to leave the queue for the Caledor Woods scenario. However in the timeframe I leave, (the instant I clicked to leave) I get a Scenario for Logrin's Forge.  However by leaving Caledor Woods, the scenario screen the one necessary to join a scenario, disappears. I can only assume this method assumes I left the scenario and thus gives the quitter debuff despite me leaving the queue on an entirely different scenario. 
![sc bug](https://cloud.githubusercontent.com/assets/22659318/19151499/b3374e4e-8c18-11e6-85d3-90f046091329.jpg)

**Comment by Tesq** [comment]
also my report #8014

**Comment by Kaberu** [comment]
This very thing has happened to me all morning with a slight twist.  I've found that each time I "Join all" and then click "Leave Stone Troll Crossing"  I get a queue pop at that moment for Stone Troll Crossing.  I have tried this now with a couple of different scenarios and it's happened each time today.
