### ISSUE TITLE
Quest: Into the Depths

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#8027]
Realm: Order - High Elf
Region: Avelorn
Quest Giver: Rathia Goldspire at Grimwater, Chapter 11

Subject: Speak to Snorgan Axegrinder
Target Coordinates: 04k/03k at Badlands

Problem: The mentioned Snorgan Axegrinder is inside Mount Gunbad, which has not been implemented yet. In addition to that the quest marker for target area on the map is missing

![1](https://cloud.githubusercontent.com/assets/18719012/19162277/7f1ad890-8bf7-11e6-8fe3-fce50c316170.jpg)

![2](https://cloud.githubusercontent.com/assets/18719012/19162284/8341cd16-8bf7-11e6-810e-ceb1de49cda7.jpg)

![3](https://cloud.githubusercontent.com/assets/18719012/19162293/874db96a-8bf7-11e6-85b9-132f3807389c.jpg)

![4](https://cloud.githubusercontent.com/assets/18719012/19162296/8c6aa7b4-8bf7-11e6-952f-893b58d23cae.jpg)

**Comment by Ezella** [comment]
Reference  #7911

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
