### ISSUE TITLE
Quest: Voracious Little Beasts

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#8028]
Realm: Order - High Elf
Region: Avelorn
Quest Giver: Terissa Dreamweaver at Well of Whisper, Chapter 12

Subject: Speak to Olin Falirsson
Target Coordinates: 04k/03k at Badlands

Problem: The mentioned Olin Falirsson is inside Mount Gunbad, which has not been implemented yet. In addition to that the quest marker for target area on the map is missing

![1](https://cloud.githubusercontent.com/assets/18719012/19162392/04ebd406-8bf8-11e6-8985-639f32af8c4c.jpg)

![2](https://cloud.githubusercontent.com/assets/18719012/19162407/09667158-8bf8-11e6-8539-88c9789e18ff.jpg)

![3](https://cloud.githubusercontent.com/assets/18719012/19162412/0e14c628-8bf8-11e6-943b-09a58f0c5099.jpg)

![4](https://cloud.githubusercontent.com/assets/18719012/19162420/147700c6-8bf8-11e6-9b03-a565e03cff80.jpg)

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
