### ISSUE TITLE
[Squig Herder][Abilities] Squig skills missing

### ISSUE THREAD

**Issue by jelczi** [WarEmu/WarBugs#803]
Skills on squigs appear to be random;
Sometimes some skills are missing on the squig ability bar and with each summoning they are different; 
Knockdown on 'Summon Squig' missing.

**Comment by ozarmidrashim** [comment]
Can't fix this right now.

Pet skills will be correct on the server, irrespective of the client's opinion on the matter.

**Comment by ozarmidrashim** [comment]
Closing as issue is mentioned in more recent bug report (and the bug is very obvious)
