### ISSUE TITLE
Khaine's Embrace battlegroud

### ISSUE THREAD

**Issue by Sheevar** [WarEmu/WarBugs#8033]
I just joined the BG:

My screen is blue except for the UI
I can move but i don't fall or get stuck anywhere
i hear the ingame sound
I still get the roll for the loot
I tried the reloadUI command but nothing changed
The minimap and the map is totally empty

![lagann_000](https://cloud.githubusercontent.com/assets/22686102/19200009/1133f28c-8cc7-11e6-88c3-74a3f45faf0b.jpg)

![lagann_001](https://cloud.githubusercontent.com/assets/22686102/19200019/1c0e3cbc-8cc7-11e6-8acb-4a9fb383c87b.jpg)

**Comment by Luth-RoR** [comment]
Known issue with unknown root, happens rarely though: https://github.com/WarEmu/WarBugs/issues/6831
