### ISSUE TITLE
[Tactic] Close Quarters

### ISSUE THREAD

**Issue by Aeriell** [WarEmu/WarBugs#8036]
I'm a sorc and I was trying to use close quarters tactic (Your cast timers are reduced by 50% if you are within 20 feet of the target). But even if I get almost to melee range of the target, the cast timers are still the original spell ones. Is it just me or everybody has this problem?

**Comment by gittoaster** [comment]
works fine on BW tested with NPC+PvP.

**Comment by Aeriell** [comment]
It doesn't work on sorcerer, I tried again today

**Comment by Luth-RoR** [comment]
Tested on the devserver; works as it should.
![luthsorc_000_crop](https://cloud.githubusercontent.com/assets/8567481/19278218/c03f09c0-8fdc-11e6-8512-64ce5038df67.jpg)

**Comment by LadyCereus** [comment]
Close Quarters is bugged for me as of the last few days.  In melee range, my casting times are no shorter.  If I remove the tactic then add it back to the slot, sometimes it will work for a few spells.  After I kill a few enemies, it goes back to not working.
