### ISSUE TITLE
Portal Saphery to Caledor

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#8037]
35k - 65k Portal Saphery to Caledor doesnt work.Caledor to Saphery worked.
Gives message error : Region currently not available. Please try again later.
![shamanakos_000](https://cloud.githubusercontent.com/assets/16864486/19213069/6077c7b2-8d6a-11e6-872e-ecf6634f9866.jpg)

**Comment by Ryanfawkez** [comment]
Works fine on dev server.

**Comment by Soulwhisper** [comment]
Gonna test it again right now.

**Comment by Razielhell** [comment]
yeap works.

**Comment by Razielhell** [comment]
Fixed in next Patch.
