### ISSUE TITLE
should not be chicken in the WC

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#804]
i find that the player should not become a chicken in the warcamp, instead it happens when "Entering RvR"

**Comment by Tesq** [comment]
He is  correct, flag statu should not occur automaticaly in wc, only when enter in rvr lake outsie wc.

**Comment by Evildoor** [comment]
This happened because RVR zone included some warcamps. Now, many of them are out of RVR, and you do not turn into chicken. Therefore, i'm closing this and any warcamps which turn you into chicken should be reported individually.
