### ISSUE TITLE
Learning Their Strength - Dragonwake Quest

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#8043]
Hi,

I've started this quest, but the named character "Malthar Sorrowblade" is not about in the quest area. I've tried a couple of times, and searched the bodies in case the NPCs have been killing him, but he's not there that I can see.

![dwquest](https://cloud.githubusercontent.com/assets/22262165/19215293/d6c5aa5c-8d91-11e6-833a-74bd1bbf5924.png)

**Comment by Ryanfawkez** [comment]
He has a double spawn, actually. All fine on the dev server.

**Comment by Senthoi** [comment]
Thanks, I'll have another look then.

Have a great day!

Get Outlook for Android<https://aka.ms/ghei36>



On Tue, Oct 11, 2016 at 10:27 PM +0100, "Ryan Fawkez" <notifications@github.com<mailto:notifications@github.com>> wrote:


He has a double spawn, actually. All fine on the dev server.

-
