### ISSUE TITLE
Quest: A Subtle Wind

### ISSUE THREAD

**Issue by LessRight** [WarEmu/WarBugs#8047]
Faction: Destruction
Zone: Nordland
Coordinates: 51.5k, 47.5k
Objective: Speak to Konrad Schulman 1/1

I get an inventory overflowing error despite my inventory not being overflowing. I cleaned up more spots than there are choices listed for reward items.

EDIT - I'm having lots of problems with my inventory generally on this toon, we might want to delete this since I can't say that the problem is definitely related to the quest.

EDIT2 - A screenshot of my backpack as I open it 
![nikea_000](https://cloud.githubusercontent.com/assets/22410672/19218497/697b61e8-8dc9-11e6-9ec5-4423b61d598e.jpg)

**Comment by Luth-RoR** [comment]
This is an issue with your character afaik.

**Comment by Lheana** [comment]
The quest has been fixed for a while now, and I think the inventory issue must have fixed itself since.

**Comment by KULER125** [comment]
How to fix this inventory?

**Comment by KULER125** [comment]
> The quest has been fixed for a while now, and I think the inventory issue must have fixed itself since.

How to fix this inventory breakdown? Please tell me if you coped with this

**Comment by Lheana** [comment]
Use the forum for tech support.
