### ISSUE TITLE
Quest: Call of the Hunt

### ISSUE THREAD

**Issue by LessRight** [WarEmu/WarBugs#8048]
Faction: Destruction
Zone: Chrace
Coordinates: 29.5k, 50k
Objectives: Aethlys Dreamsong's Head 0/1
Gaelnir Stormbrow's Head 0/1

Aethlys appears in the first red area, but Gaelnir Stormbrow does not appear in the other red area that I gave the coordinates for.

**Comment by Ryanfawkez** [comment]
Multiple quest markers are not yet supported.

**Comment by Razielhell** [comment]
Fixed in next Patch.
