### ISSUE TITLE
Ability - Storm of Ravens

### ISSUE THREAD

**Issue by Gessian** [WarEmu/WarBugs#8049]
Yo!
In the last few days I test dd zealot/runepriest builds. Including "Storm of Ravens" ability. Zealot 27 level, with magic crit 5% , hit same lvl mobs, Noticed chance of crit this ability much less then Runeprieste's "Rune of Burning" on 26lvl my Runepriest with 2% magic crit.Basic dmg identical. Same at open RvR. Always thought that abilities have the same damage formulas. So, this ability is broken like on live server ages ago, or i made mistake?
P.s. Of course I tested this abilities of not one mob, killed several dozen.
Sry for bad english,not my language

**Comment by ozarmidrashim** [comment]
You need actual evidence when trying to report something this outlandish.

**Comment by Gessian** [comment]
Ok, make screenshots in ~2h.

**Comment by Gessian** [comment]
Test it again,but hit same mobs, and just 3 of em. No RR points. RP without magic crit/ Zeal have 3crit.
RP - 7+7+6 ticks & 1+1+2 crit/per 
Zeal- 7+7+6 ticks & 2+ 2+3 crit/per
soo,thats my fault. 
Because i remember topics on live forum about "storm of ravens" broken mechanic,but now see RoRs command fix it!
It was just a godlike random(
![elrizag_002](https://cloud.githubusercontent.com/assets/15679327/19219807/ed4efc58-8e25-11e6-8e9d-12fa93949692.jpg)
![veil_001](https://cloud.githubusercontent.com/assets/15679327/19219808/ed51a19c-8e25-11e6-8543-d7fdf1700aa6.jpg)
![elrizag_005](https://cloud.githubusercontent.com/assets/15679327/19219817/13ed4914-8e26-11e6-8aa7-9e1182b052c9.jpg)
![veil_000](https://cloud.githubusercontent.com/assets/15679327/19219818/13f02896-8e26-11e6-9ddf-49d63f3888c0.jpg)
