### ISSUE TITLE
players character doesn't change when "relogging" a different character

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#805]
players character doesn't change when changing your character

play one char
exit to menu
load another char

(tested on Order IB + RP)

**Comment by Tesq** [comment]
Happen usually when the game lost connection/crash while log out.

**Comment by gittoaster** [comment]
it might also matter if you are relogging to different realm without closing the whole program... you see a big problem with groups being visible of the wrong side, also

**Comment by Evildoor** [comment]
I do believe this was fixed, closing. Comment here if the problem still persists.
