### ISSUE TITLE
RvR Quest turned in without talking to NPC

### ISSUE THREAD

**Issue by EvfretFeaulx** [WarEmu/WarBugs#8051]
Last night I leveled out of Tier 2 while simultaneously completely the keep siege quest and other RvR quests in the Marshes of Madness. While saying my goodbyes I was standing next to the NPC for turning in the keep capture quest so I could log in later to turn it in with some Rest bonus. Suddenly, the messages flashed across my screen and chat log saying I had finished, turned in, and been rewarded for the completion of the capture quest without even having the NPC targetted.
![maryulan_001](https://cloud.githubusercontent.com/assets/22728167/19221185/d3936118-8e03-11e6-930b-568d02c9a599.jpg)

**Comment by Luth-RoR** [comment]
I can't see anything about a completed quest on the screenshot, only an abandoned one.
Could it be that you just got delayed XP from RvR contribution?

A hint: I think rested XP doesn't work on quest XP (like on the mythic server).

**Comment by EvfretFeaulx** [comment]
I couldn't get the screenshot in time of the on-screen message but every time I turn in an RvR repeatable quest like this one it always says the quest is abandoned and not completed, yet I still get the rewards like quest completed - just as I did in this situation. The only thing different from this turn in I experienced from all the others I've done is I never had the NPC targetted nor did I intend to turn it in.

**Comment by Kaelang** [comment]
This issue does not seem to be effecting later versions of RoR. If you are still playing - please feel free to re-open this issue if you find it persisting.
