### ISSUE TITLE
Get in the scenario without actually being in the scenario

### ISSUE THREAD

**Issue by Zumos** [WarEmu/WarBugs#8059]
We were queued with party and got a pop. All of us joined, but two including me got some kind of outsynced. You are in the scenario zone, but you cannot the see points, cannot open the scenario window, and you cannot see the scenario parties. My unit frames did show the original party I queued with. Also we got quitter debuff. Also we didnt count towards the scenario population, meaning there was an imbalance between destro and order. When the scenario ends, basically nothing happens so you have to relog to get out of the scenario zone.

I added screenshot of beginning and end of the scenario from my PoV and one from the other person the in party.
![zumoswp_030](https://cloud.githubusercontent.com/assets/19267650/19283256/7a06110a-8ff1-11e6-96dd-31ae149aa814.jpg)
![zumoswp_031](https://cloud.githubusercontent.com/assets/19267650/19283255/7a03ffe6-8ff1-11e6-90a2-136f397a7b8a.jpg)
![daniellita_004](https://cloud.githubusercontent.com/assets/19267650/19283347/bb814c26-8ff1-11e6-88a2-f2c150662f1d.jpg)

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/7076

**Comment by kamikaiser** [comment]
Similar thing happened to me AND it also chickened me after saying I was too powerful for the area. I am level 34, in a T4 SC. Apparently my RPness is too OP even for T4.

On a serious note. No I was not in a lower zone or anything else which would have chickened me. I was in Thunder Mountain, not even in RvR lake, and had just done a T4 SC 5 minutes earlier with no issue.

I am also unable to leave the scenario. When I try to, and it prompts me to leave and I click "Yes" it says "No active Scenario"

**Comment by Vandorkholme** [comment]
Getting this aswell, I qued up and tried to unque instantly so I could reque with group. I was in the middle of dropping the SCs when I got hit with the pop and it immediatley hit me with quitter debuff while I still could have taken the scenario.

**Comment by Natherul** [comment]
same issue as https://github.com/WarEmu/WarBugs/issues/8162 @Luth-RoR please link them and close this one :D

**Comment by Luth-RoR** [comment]
Using this one as it is the oldest one with the most info, thanks for finding the duplicates.

**Comment by Cimbas** [comment]
Yep also just happend to me. Here is a screen with me as a chicken in the scenario.
![cimbina_018](https://cloud.githubusercontent.com/assets/16117730/20728434/0027f516-b67e-11e6-838a-d10c64d42bcc.jpg)

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=18792
