### ISSUE TITLE
Mail is not working most of the time

### ISSUE THREAD

**Issue by NervZ** [WarEmu/WarBugs#806]
So i tried to send few gold to my new toon and the mail never arrived. 
Then i tried again to send some items and it worked.
I talked with some other ppl and reported me the same issue some time it works some time it does not

**Comment by ozarmidrashim** [comment]
Mail system isn't loading for everyone. To fix

**Comment by Lerilla** [comment]
![Allyselle_027](https://user-images.githubusercontent.com/16804997/62918906-6269dc80-bda1-11e9-8870-83f07372a957.jpg)

sended amail today.  8:0024 o'clock i had it in my mail, you can see the text in the screen, and at 8:00:37 it disappeared. But i never take the stuff out of the mail
