### ISSUE TITLE
Knight influence rewards and item appearances t4

### ISSUE THREAD

**Issue by edavoc** [WarEmu/WarBugs#8062]
I starting to think that all almost all belt and helmet appearances that are supposed to be alternate for the knight are bugged for chapter influence rewards. Every single reward I've tried has no appearance as though you are not wearing anything at all.

Example: Chapter 20 dwarf rewards Grudgejoining Casque and Cragwalker Fauld have no appearance, neither does Rumbleground Faulds from chapter 16 dwarf.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/7474
https://github.com/WarEmu/WarBugs/issues/7631
https://github.com/WarEmu/WarBugs/issues/7632
https://github.com/WarEmu/WarBugs/issues/7633
Only one bug per report, like stated in the rules.
