### ISSUE TITLE
The Siren Sea - Public Quest Empire Chapter 21

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#8064]
This Siren Daemonette falls out of the PQ in Stage 1.
![maxeras_001](https://cloud.githubusercontent.com/assets/16864486/19306429/53b5ec2c-907e-11e6-8b52-1c6cdda64e22.jpg)

**Comment by Hargrim** [comment]
Corrected all 8 occurrences of this mob not counted in Stage 1. Fixed in next patch.

**Comment by Soulwhisper** [comment]
Patched.{Works ! Good job! }
