### ISSUE TITLE
Keep Door side attack

### ISSUE THREAD

**Issue by Ercenberth** [WarEmu/WarBugs#8066]
During an assault on a Destruction keep in T2 (MoM) defenders placed oil. The attackers, to avoid the oil splash, moved on the side of the keep door (as showed in the image below) and continued to hit the door as if there wasn't a wall between them and their target and without being hit by the oil. The same thing happened in Shadowlands, while taking Destruction keep, but I don't know in other keeps.
![side door](https://cloud.githubusercontent.com/assets/22793740/19311818/33f9ebc4-9090-11e6-841e-9a784e4e0cdb.jpg)

**Comment by Luth-RoR** [comment]
Known https://github.com/WarEmu/WarBugs/issues/7581
