### ISSUE TITLE
Using mount in Serpent's Passage

### ISSUE THREAD

**Issue by coldnegative** [WarEmu/WarBugs#8068]
As I know it is always a forbidden action to use 'Summon Mount' ability being a courier of some object in scenarios. However I was able to use 'Summon Mount' ability more than once in Serpent's Passage scenario. Actually you don't have a mount's model but still 60% faster without using any other abilities.
![war 2016-10-13 01-25-57-11](https://cloud.githubusercontent.com/assets/9000735/19330323/6ef2d29e-90e6-11e6-9ab2-cbc4bd606ff3.jpg)
![war 2016-10-13 01-27-44-93](https://cloud.githubusercontent.com/assets/9000735/19330322/6ef1b332-90e6-11e6-830c-4eed6839260b.jpg)

**Comment by Luth-RoR** [comment]
Already known: https://github.com/WarEmu/WarBugs/issues/6229
