### ISSUE TITLE
Auction House Search results

### ISSUE THREAD

**Issue by coldnegative** [WarEmu/WarBugs#8069]
Tried to search any 'Very Rare' crafting materials in AH and got a very weird result (armor, talismans, dye and even siege weapon instead of materials) . Probably a DB sorting issue.
![war 2016-10-13 02-47-51-70](https://cloud.githubusercontent.com/assets/9000735/19332093/9a151da0-90f1-11e6-9f99-6bc8f122e66b.jpg)
![war 2016-10-13 03-06-43-43](https://cloud.githubusercontent.com/assets/9000735/19332174/573f8d2a-90f2-11e6-9fea-6611b3f09bba.jpg)
![war 2016-10-13 03-06-59-98](https://cloud.githubusercontent.com/assets/9000735/19332176/5744d492-90f2-11e6-9aca-ea3a49d5dc44.jpg)
![war 2016-10-13 03-07-09-89](https://cloud.githubusercontent.com/assets/9000735/19332175/574139c2-90f2-11e6-85d0-d5b1eac72f11.jpg)

**Comment by Ryanfawkez** [comment]
As far as I know, crafting good sorting isn't functional within the AH database yet.
