### ISSUE TITLE
290 mastery points avalaible.

### ISSUE THREAD

**Issue by NervZ** [WarEmu/WarBugs#807]
So i made a 2level SW and i was messing around with the "everywhere trainer" addon and at mastery tab i had 290 mastery points available and i tried to see if i could use them. I spent them on all 3 paths and my character now have all the skills and tactics you can gain from all the 3 paths. However, i couldnt use the skills and the tactics. I left him at lvl 6 so i do not know if i can use the tactics at lvl 10

**Comment by ozarmidrashim** [comment]
Resolved in hotfix
