### ISSUE TITLE
Bloody Sun Watcher Hidden in terrain

### ISSUE THREAD

**Issue by Simmox** [WarEmu/WarBugs#8070]
Area Black Crag
 SE Corner of Map 54541k,56987k near on route close to trophy pile for battle of rememberance quest
almost directly under the wooden bridge structure bloody sun watcher arrow boy

archer type plnks away at you from inside the mountain,kiled a few unsuspecting players battling through for the quest unlock,very amusing.

**Comment by Ryanfawkez** [comment]
Sneaky bugger using some sort of rock camouflage...
