### ISSUE TITLE
Few issues from Hipo: Logrins forge, sc pop in sc, rr dropped to 0 & exp maxed.

### ISSUE THREAD

**Issue by Hipokryta** [WarEmu/WarBugs#8071]
Hello,
The  few issues i got when playing war:
1) in logrins forge sc i fell under textures, twice. The 2nd time was on purpose. Im not yet verry skilled in doing it since this sc doesnt pop for me too often. Baisicly when you go left from destro spawn and arrive near the bo there are some barrels. Near the other bo the barrels can be used to jump on some kind of elevation so melee cant hit your toon. On this side barrels are not that high, so you cant jump up, but you can stuck there & fall under textures. 
![hipokryt_000](https://cloud.githubusercontent.com/assets/22821464/19359407/515888e8-917a-11e6-8849-0933140dd24b.jpg)
2) I got sc pop while in serpents passage. When accepted  "scenario join faliure" error showed up in chat. 
![hipomara_000](https://cloud.githubusercontent.com/assets/22821464/19359423/655847ca-917a-11e6-9d1e-11df70554bbb.jpg)
3) My game crashed after a sc. When i logged back into the game my toons renown was 0 (from 35) and my exp showed as "max" even tho my lvl was 36. I quit the game & tried to log in but failed in a few attempts. After succesfully loging in everything was fine again.
4) Don't know if this is ok, or entrance there should be fixed
![hipokryta_003](https://cloud.githubusercontent.com/assets/22821464/19359454/8916f29c-917a-11e6-9398-f740bc547eb6.jpg)

Sorry for my imperfect english.

**Comment by Ryanfawkez** [comment]
Next time, one issue per ticket, please.
I'll look into the terrain issues, the other two issues are commonly known in Scenarios.
