### ISSUE TITLE
[Choppa/Slayer] Hurtin' Time/Reckless Gamble

### ISSUE THREAD

**Issue by Killham** [WarEmu/WarBugs#8077]
As you can see in this video these abilities must depend on rage / berserk
https://youtu.be/Jx-H649tSB8?t=274
green area - 84 damage
rage - 105 damage
berserk-119 damage

**Comment by Luth-RoR** [comment]
Additionally the self damage is increasing too in the video.

**Comment by Killham** [comment]
> Additionally the self damage is increasing too in the video.

ofcouse
