### ISSUE TITLE
[White Lion] small overview and pet's AI

### ISSUE THREAD

**Issue by NervZ** [WarEmu/WarBugs#808]
So, i spent some time the last 2 days creating and testing a WL. The lion is buggy. As it mentioned in an other bug thread the bar disappear most of time after ~2mins even if the lion is next to you. However, the lion still keeps to assist you if it was in aggressive or defensive mode.
The stances do not work properly. Most of time if you wanna get a specific stance's skills u have to unsummon the pet change stances back and forth few times and then summon the pet again.
The skills cannot be deactivated and the pet never use them automatically or it uses them very rare.
For me however the worst thing was the speed of lion... It so slow that if you chase an enemy the lion isnt able to reach him. Same, when you try to run away from an enemy and you want the lion to atk him and use the snare ability it cant reach him.
In general, WL is so weak right now.. It has some good burst dmg if you are lucky and the pet is next to you with the pet bar not disappeared and the enemy stands still. My toon is 20/15 with lvl 19 blue/green gear and i got outdps by all the rest mdps classes.
 In a SC if everything is going well(have guard and a healer heal my ass) i will get maximum 40k-50kdmg when with my 16lvl choppa i did 90k dmg today.

**Comment by ozarmidrashim** [comment]
OK, so:

- Disappearing bar is finally solved - game was trying to resurrect pets, which caused problems with the bar as resurrect is redirected to destroy them

- Skills are a visual problem - the pet has the correct skills on the server, though this may stop you from commanding the pet to use a certain skill. We don't know how to fix that yet

- I've modified the speed and will update the follow code soon
