### ISSUE TITLE
Bug with apothecary npc

### ISSUE THREAD

**Issue by Soapz** [WarEmu/WarBugs#8080]
Hello, as I was in IC, I right clicked on the apothecary npc by mistake. Unfortunately for me, and this is prolly a bug, I did'nt have the question 'Would you like to respec talisman making'.  What happened is that I learnt the apothecary crafting skill and lost of my progression in talisman making (I was level 200). When this occurred, I then tried to learn talisman making, but, I am now level 1 instead of 200. I would really appreciate to  get back to my former level as talisman maker.

best regards

Soapz. Choppa

**Comment by Natherul** [comment]
will be fixed in the next patch

**Comment by sioding** [comment]
fixed with patch from 09.03.2018
