### ISSUE TITLE
T4 Epic Quest Duplication

### ISSUE THREAD

**Issue by Blueberry98** [WarEmu/WarBugs#8085]
I was minding my own business abandoning quests when i notice i still have to hand in ebon flame (even though i already have done it and have the "Doom's Edge" Sword in my bank so i go to hand it in and take the Shield from it. I can see this a bug and could be replicated and used in a unfairly manor so i have locked the shield away in my bank until further notice.

**Comment by Luth-RoR** [comment]
That's known to the devs, the source for this is unknown though afaik.
