### ISSUE TITLE
Party queue, quitter debuff bug

### ISSUE THREAD

**Issue by Sileq** [WarEmu/WarBugs#8087]
![quitter debuff](https://cloud.githubusercontent.com/assets/22659318/19407607/d0b9f760-92f2-11e6-9670-283a890ad04b.jpg)

Party queue for scenario, we all join. Got message that the sc has ended, some of our group got in, others did not. We all got quitter debuffs. People in the sc reported inability to get out when timer ended, or trying to physically get out. No one else in the sc except for the people who managed to join from our group.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20quitter
