### ISSUE TITLE
need on item not of your class

### ISSUE THREAD

**Issue by jonyjones** [WarEmu/WarBugs#8088]
every one can need any item, even not for their class.

**Comment by Luth-RoR** [comment]
When someone _needs_ an item he can't use, the server automatically _greeds_ the roll. In this case you will see a chat message (if it is not filtered by your settings).

**Comment by Soulwhisper** [comment]
You might mean that the item is for example Empire flagged but its actually a book for WP and Kotbs,Bright Wizard and Witch Hunter can choose need.Is that it?

**Comment by Yellowpillow** [comment]
probably he meant visual client bug
