### ISSUE TITLE
Broken Recruit's Medallion Quartermaster in Blighted Isles

### ISSUE THREAD

**Issue by Khalt** [WarEmu/WarBugs#809]
The vendor Bursar Halenbaen in the Blighted Isles Order WC is giving away free boxes of Recruit's Medallion, though they cannot be used/opened, as far as I can tell. The other gear he carries are paid for with "Grudjejoining Taen". No idea what those are.

**Comment by Evildoor** [comment]
To prevent further abusing, vendor was temporarily removed. He should be returned with proper wares and their proper prices.

**Comment by genisaurus** [comment]
Fixed ages ago
