### ISSUE TITLE
Gutslime Magus Staff - Still only 2% crit

### ISSUE THREAD

**Issue by ItsJustJono** [WarEmu/WarBugs#8095]
The staff that drops from the Gutslime crit weapon lair boss is still only 2%. Not sure where else to post this.

**Comment by Luth-RoR** [comment]
True, i just killed him on the dev server:

![luthmagus_002_crop](https://cloud.githubusercontent.com/assets/8567481/19416043/cafcac6c-9385-11e6-87bc-effa89be6ca2.jpg)
