### ISSUE TITLE
Bandit's Bane Quest

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#8099]
There is no mark on map.
You must turn it in the NPC that is on the road to Norsca.

**Comment by Hargrim** [comment]
There is a mark on map, but this is in Norsca. Please find 2 below screens:

![image](https://cloud.githubusercontent.com/assets/16460565/19435518/5cfff82c-946b-11e6-9038-66567cf1c01f.png)

![image](https://cloud.githubusercontent.com/assets/16460565/19435540/78bbea44-946b-11e6-8c60-15bc58592761.png)

Solved.

**Comment by Soulwhisper** [comment]
Thats not it. @Ryanfawkez re-open it please.

**Comment by Hargrim** [comment]
Can you upload some screens and coordinates? Up to this point it worked.

**Comment by Soulwhisper** [comment]
Yes i will provide them as soon as i can.Have to go now.

**Comment by Soulwhisper** [comment]
Told ya that you must turn it in the NPC that he is on the road to Norsca.
![pordh_000](https://cloud.githubusercontent.com/assets/16864486/19450288/7a7625ca-94b1-11e6-8e2e-b2f75bf16946.jpg)
![pordh_001](https://cloud.githubusercontent.com/assets/16864486/19450289/7a79d5b2-94b1-11e6-8d84-dfe8ccc11f0e.jpg)
![pordh_002](https://cloud.githubusercontent.com/assets/16864486/19450290/7a87b2a4-94b1-11e6-8db7-18a41af2ea6d.jpg)

**Comment by Luth-RoR** [comment]
Afaik this can't be fixed yet; the quest areas generally don't update after a step is fulfilled atm.

**Comment by Soulwhisper** [comment]
It says along the road that leads to Norsca though...i quess its pretty obvious.
Closing for now.
@Luth-RoR Thanks.

**Comment by Soulwhisper** [comment]
Hm? Someone fixed it.LOL

**Comment by Luth-RoR** [comment]
Must be Halloween. :ghost:
