### ISSUE TITLE
Tactics bar switches to empty set

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#81]
When you gain a tactic ability for the tactic hot bar. It behaves in the same way as the hot bar, where it is removed from the hotbar when you log back on.

Same as #9 

![tactics hot bar](https://cloud.githubusercontent.com/assets/7492543/2922201/19a9587a-d6fe-11e3-9d78-e32eff7deb4a.png)

**Comment by Evildoor** [comment]
Since the hotbar problem was (mostly) fixed, i changed the name of the issue to a more accurate one.

**Comment by Evildoor** [comment]
Fixed in 18.12.2015 patch.
