### ISSUE TITLE
Monsters disappearing until next server restart

### ISSUE THREAD

**Issue by xyeppp** [WarEmu/WarBugs#810]
When fighting a monster he just disappears mid-fight forever and will never respawn. 
Only a server restart brings him back.
It happened at least 10 times in the last two days to me, and just now again to 'Huurgan Bonechewer' at 12k,16k Troll Country if that helps the logs. 
Don't know how to reproduce it, but my class is the Squig Herder so maybe a pet is a factor.

Mandred's Keep lord is also subject to this bug - missing after we pulled him and he disappeared.

**Comment by ozarmidrashim** [comment]
This happens if an exception gets thrown on the mob, so it should be easy to find. I can't access the current log until the next server restart, however.

**Comment by ozarmidrashim** [comment]
Tentatively marking as fixed

**Comment by jelczi** [comment]
I find it happened for the third time now right when my Spiked Squig used the Spine Fling ability.

**Comment by ozarmidrashim** [comment]
Spiked Squigs kept throwing if Spine Fling is broken in a certain way before it's initialized. Because the channel buff was initialized from a callback from the buff interface of the person you attacked, the exception would cause the NPC to be deleted.
