### ISSUE TITLE
Quest: Betta Booms

### ISSUE THREAD

**Issue by Nekronsieben** [WarEmu/WarBugs#8100]
Mission: "Kill Dragonbless Ferkath."
Problem: missing NPC

I have searched for him on the map marked location and the sorrouunding places for about 10-15min.

**Comment by Hargrim** [comment]
His spawn is shown below, he had incorrect faction and was killed instantly by surrounding mobs. Corrected, fixed in next patch.

![image](https://cloud.githubusercontent.com/assets/16460565/19420330/950ca896-93e9-11e6-8a93-8f68bacb710b.png)

**Comment by Nekronsieben** [comment]
thanks
