### ISSUE TITLE
Mobs in rvr using your pve lvl to calculate dmg.

### ISSUE THREAD

**Issue by Kweedko** [WarEmu/WarBugs#8101]
Instead of your bolstered in rvr, level let's call it "rvr lvl" mob's in rvr lakes using your actual lvl(pve lvl) to calculate damage they done to you, what leads to 2,5k - 5k(in t3)  non crit non mitigated damage which vaporaise you in one hit.

**Comment by Luth-RoR** [comment]
**People are bolstered to about _level 31_ in T3; the skaven is a _level 39 champion_.
Damage on a level 31 player (to clarify: no bolster buff on the character):**

![20161016203240_1_crop](https://cloud.githubusercontent.com/assets/8567481/19419854/70be50ec-93e0-11e6-9f20-f82c99ef83b5.jpg)

**Comment by Kweedko** [comment]
yeah then why my sham 23 lvl (in t3) got hits 2,5 - 5k, problem is in bolster and you testing without it, made low lvl char and go fight champs neer keep or on bo

**Comment by Luth-RoR** [comment]
I was hit with constant 3298 damage on a level 31 character; this is in your 2.5-5k range. You could start to follow the bugtracker rules and post some evidence (screenshots etc.), because i'm not interested in spoonfeeding any bad habbits.

**Comment by Kweedko** [comment]
so then it's ok mobs killing you in 2 hits, basicaly work as intended, we must gather a party to kill one champion.

**Comment by Luth-RoR** [comment]
If the champion is 8 levels above you, it seems so.
