### ISSUE TITLE
Mirror of Madness didn't crit, and it's damage applying before healing.

### ISSUE THREAD

**Issue by Kweedko** [WarEmu/WarBugs#8104]
No crit damage for MoM hits.

And damage from it applying before heal which proc it, nullifying the damage done.

**Comment by Luth-RoR** [comment]
Number 1: 
Patch 1.3.2
_Mirror of Madness: Fixed an issue that allowed this ability to benefit from stat contribution and deal critical damage_

Number 2: 
I don't know what that means, but i guess it's related to https://github.com/WarEmu/WarBugs/issues/1444
In case it's not related: clarify, post screenshots etc. pp.

**Comment by Kweedko** [comment]
So you telling me that, you gonna use changes from patch 1.3.2 where still old harbringer 
mechanics, why won't you bring stupid bird back then, if devs on old war never reverse this change after changing harbringer mechanics, no wonder nobody use this skill ever, cause skill not benefiting from stat and dealing no critical damage,  with low base damage and restrictions in use - never gonna work.

**Comment by Luth-RoR** [comment]
I'm not going to search every patchnote for zealot changes; if the ability is working wrong at the moment, feel free to post evidence.

**Comment by Kweedko** [comment]
cause you can't find them from the souce - war herald is closed, yes i can find 1.3.2 patch notes on some site, but, not all full other patch notes, from every patch and there were 12 more patches after this.
And due to minority of ddzealot on old war neither of us can find a video of zealot using the MoM after 1.3.2 patch.

But in regards of common sense, MoM  will not be "OP omg nerfplis now" abil if it gonna benefit from stat contribution and deal critical damage, hits are gonna be around 600-800 dmg to cloth target with no big amounts of toughness, besides that this skill already mitigates from toughness and due not benefiting from int it's making it even worse to use.

**Comment by Luth-RoR** [comment]
Voilà:
https://web.archive.org/web/20131227093042/http://www.warhammeronline.com/PatchNotes
https://web.archive.org/web/20131227093507/http://www.warhammeronline.com/news/HotFixes

As i already wrote in the past in one of your reports: The bugtracker is not for balance discussions, only for bugs.
