### ISSUE TITLE
[Runepriest] Oath Rune lag

### ISSUE THREAD

**Issue by Bonzoooo** [WarEmu/WarBugs#8106]
It's not everytime that I cast an Oath Rune on myself, but a would wager that roughly half the times I cast any Oath Rune on myself I get 2-5s of screen freezing lag. It seems to happen more in scenarios than not.

Was in a group with a BW and he had the same lag last night, but only once in the several hours we played and several times I put an Oath Rune on him.

It doesn't appear to matter which Oath Rune either.

**Comment by ozarmidrashim** [comment]
Clientside.
