### ISSUE TITLE
Vendor for tradeskill bug (removes current tradeskill)

### ISSUE THREAD

**Issue by Nekronsieben** [WarEmu/WarBugs#8107]
If you right-click on one of the vendors for the Tradeskills in IC center, you lose your current skill.
There should be a extra window warning you from that!

http://i.imgur.com/4kFWKkT.jpg

**Comment by ozarmidrashim** [comment]
Please don't post "Please fix" in reports.

Please demonstrate proof that you can lose a skill without clicking "Learn Trade Skills."

**Comment by Nekronsieben** [comment]
okey

**Comment by Nekronsieben** [comment]
Ticket can be closed, checked the bug with an other character, but could not recreate the bug, or maybe the bug got caused by an other tradeskill vendor somewhere alse. I am not sure, but I'll keep looking out for this weird bug. Thank you for the fast responding.

**Comment by Luth-RoR** [comment]
Could be a specific type of trainer: https://www.returnofreckoning.com/forum/viewtopic.php?f=5&t=17669#p192423
