### ISSUE TITLE
Quest: Fightin' Infightin'

### ISSUE THREAD

**Issue by Nekronsieben** [WarEmu/WarBugs#8109]
Mission: "Kill Tulk...and then speak with low boss Brung, who will only come out after Tulk is dead."
Problem: NPC for returning Quest is missing.

Also went to chapter 17,18 and 19 + warcamp in Thunder Mountain, but I could not return that Quest.

**Comment by Lheana** [comment]
This has been fixed with patch of 14/07/2017, see #12021
