### ISSUE TITLE
Pet panel gets visually bugged

### ISSUE THREAD

**Issue by magter3001** [WarEmu/WarBugs#811]
1. Pet ui/abilities bugged after 2 mins (you already know this, I know)
2. The self punt ability works incorrectly compared to the way it was on Live. The way it was on live, the ability would go through a check where you had to snare a target in order to be able to self punt. For example, if you fight an enemy and he is not snared... whether he uses an ability to become immune to snares, like many mpds can do, has diminishing returns immunity, or is just out of range, the SH or SW would not punt in the situation. If you're fighting 2 enemies, one is immune and one does get snared, the punt would still work because at least one target got snared. Only after that check does the ability grant the self punt to the SH or SW.
3. The morale 2 ability that increases damage by 100% work incorrectly compared to Live as well. Currently, if you use an ability such as a 15 second DoT while under effect of the morale, the DoT will do 100% damage for it's entire duration. The way it was on Live though, the DoT would only do 100% for the 7 second duration of the morale ability. On Live, say you put the 15s DoT before using the morale... if you activated the morale, the active DoT will do 100% damage for the 7 seconds and then will switch back to it's normal damage after those 7 seconds. The same with SW. The way a SH would do it on live, using the morale, was that they would put 2 DoTs on an enemy, then activate the morale, and then use their other abilities to maximize their damage. As it stands on RoR, all abilities cast during those 7 seconds will deal 100% for an entire duration.
4. The abilities Run 'n Shoot and What Blocka? are a little slower than on Live as well by a small fraction. The cast and cooldowns are correct but the projectile speed is just a little too slow, maybe about 1/4th of a second. The other abilities seem correct though on their projectile speed.

**Comment by jelczi** [comment]
Just so you remember and can check in case -  When casting "What Blocka?" and spamming "Plink" button to cast right after "What Blocka?" results in "What Blocka?" not being finished fully and never actually firing.

**Comment by xyeppp** [comment]
About number 2 - I'm not sure what do you mean, but "you had to snare a target in order to be able to self punt" is wrong. You could run into blocks of enemies and AoE snare them. What you are saying would make it useless as you use it to get back when being jumped. The only check there might have been (can't remember), was that if the target is immune to snare then you would not be able to self-punt, which from "If you're fighting 2 enemies, one is immune and one does get snared, the punt would still work because at least one target got snare" seems to be what you are trying to say.

5. Squig Armor currently doesn't increase Toughness or Wounds, but you already probably know that. 
However, the cooldown on the skill is wrong at the moment, because it should only get on cooldown once you leave the Squig Armor, not when you enter it. See https://youtu.be/LSBkWQsGHOA?t=14s for HP increase and cooldown.

**Comment by magter3001** [comment]
About number 2 -  Currently on RoR, you don't have to be in range of an enemy to use the self punt. On live, if you were on a one on one situation against a WH for example - your self punt would not work if the WH is 1, out of range of the ability... which I think is 30 ft or something, or 2, he has the snare or root immunity. 

It still worked on group of enemies like on live, where you could go into a group and AoE snare them... that is correct.

" What you are saying would make it useless because you couldn't even use it to get back when being jumped" - But that is exactly how it was used on live by smart players. When I played my WH and fought SH, I would always pop out of stealth, knock them down, and before they get up... I used my snare immunity. You could see SH's Sticky Feetz animation go but nothing would happen since I was the only one they were fighting and was immune. They would not be able to self punt and snare. That is the check I'm talking about.

On number 4 - I did a little more testing since posting that and have come to the conclusion that Mythic and RoR devs have different formulas to calculating the abilities. RoR devs made it where - if your target is farther... the ability will take longer to get there. Mythic devs on the other hand made it that - abilities will close the distance gap at the same time frame. So if you shoot from 100ft or 30 ft. What Blocka would get there in .5 seconds (placeholder time - I don't know exactly how long it takes)

**Comment by xyeppp** [comment]
Yes, I agree but look again at your wording "where you had to snare a target in order to be able to self punt." - This would mean, exactly, that you first would have to use Stop Runnin! and snare the enemy, and only then be able to self-punt away.

**Comment by magter3001** [comment]
No, I don't mean using Stop Runnin' to snare targets.... I mean that the Sticky Feetz's snare must be APPLIED to the enemy to self punt. I'm only talking about Sticky Feetz ability not Stop Runnin', sorry if you misunderstood that. Sticky Feetz does two things. One, it snares everyone within 30ft or so, and two, IF Stwicky Feetz sanres at least "one person" then you will self punt.

I've been going through Warhammer Videos trying to find this but no luck so far.

**Comment by taccr** [comment]
Any chance in getting this fixed?
Like people said before: You have to apply the snare to at least one person to get the self punt effect.
No snare, no punt.

**Comment by Evildoor** [comment]
Renamed the report to reflect the only relevant point left. Self punt was already fixed, bugged again and fixed again. Projectile speed is, as said in comments, the difference of implementation in RoR and i doubt that it will be changed. Morale + DoTs is a general issue with DoTs in the game which has its own report.
