### ISSUE TITLE
[Chosen] Repel(knockback) with tactic Hastened Dismissal(increases the leght)

### ISSUE THREAD

**Issue by Killham** [WarEmu/WarBugs#8111]
In these videos you can see what should be the knockback with tactic:
https://youtu.be/xTQSzAW68c8
https://youtu.be/y-kSBW7Vv24
https://youtu.be/9TpoIo9QcHg
https://youtu.be/0c-Bqs06NbY
https://youtu.be/w-uX-IoxlkY
so chosen knockback(with tactic) looks exactly the same as ironbreaker have.

**Comment by Luth-RoR** [comment]
The KB values have been taken from the 1.4.8 client and the chosen/knight KB was the highest one of all KBs with tactic on the 1.4.8; maybe it was changed between 2011-2013?
Maybe someone can confirm/remember if there were different values for the KBs on earlier patches.

**Comment by Tesq** [comment]
1.4.7 messed all anything could had happened

**Comment by ozarmidrashim** [comment]
KB values are read from client for both KBs.
