### ISSUE TITLE
Can't see mounts at mount vendors exept horses

### ISSUE THREAD

**Issue by Lethalar** [WarEmu/WarBugs#8113]
Hello!
Playing as Dwarf Engi (lvl19) cant see any mounts exept horses at Altdorf mount vendor.
Checked 3 vendors In Altdorf and t3 Quartermaster in Dwarf camp.
Vendor filter set to "Show all"
Here are the screens:
![barrager_001](https://cloud.githubusercontent.com/assets/22896636/19453704/fd89c0a4-94be-11e6-88db-843b06060017.jpg)
![barrager_002](https://cloud.githubusercontent.com/assets/22896636/19453703/fd870454-94be-11e6-9135-76635cfd75bc.jpg)
![barrager_000](https://cloud.githubusercontent.com/assets/22896636/19453702/fd855dde-94be-11e6-921c-ef685c5f9c7b.jpg)

**Comment by Luth-RoR** [comment]
Bronze, silver and iron contraption are shown on your last screenshot; these are dwarf mounts.

**Comment by Soulwhisper** [comment]
Filter man :D :P

**Comment by Lethalar** [comment]
oh LOL.. thought it named like nearby Gyros......sry for panic
Solved.
