### ISSUE TITLE
Quest "A Lord's Game"

### ISSUE THREAD

**Issue by deppenjaeger79** [WarEmu/WarBugs#8118]
This quest from the Shadowlands, given by "Deshira the Collector" is unsolvable.
One of the NPC you have to kill doesnt count for the quest and so hes a named npc it doesnt work at all.
The problematic NPC is "Chronicler Devion" regardless of how often you kill him. the quest wont update itself.

**Comment by wargrimnir** [comment]
Wrong NPC was flagged. Fixed in next patch.
