### ISSUE TITLE
2nd tanks morale Raze only do half damage on engi turret

### ISSUE THREAD

**Issue by Killham** [WarEmu/WarBugs#8120]
![shmyak_001](https://cloud.githubusercontent.com/assets/18173840/19486636/dcc37fdc-9567-11e6-9b62-8c4d6ebef1d4.jpg)
![shmyak_003](https://cloud.githubusercontent.com/assets/18173840/19486641/e2cbcc36-9567-11e6-802a-4b7b8196a6ad.jpg)

**Comment by Luth-RoR** [comment]
On RoR pets get only 50% damage from AoE attacks to prevent them from dying in 2 seconds in zerg vs zerg situations.
