### ISSUE TITLE
Bigchomp Squig Mobs Untargetable

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#8121]
Inside Ugrog's Rage Public Quest.
They are buried in the ground and they are untargetable.

**Comment by wargrimnir** [comment]
Flagged them as aggressive now, should pop out of the ground.

**Comment by Soulwhisper** [comment]
Nope.Still buried and untargetable.
![warhammer online age of reckoning 12 25 2016 - 22 45 21 08](https://cloud.githubusercontent.com/assets/16864486/21472843/dbb4db9c-caf3-11e6-88a6-5dbd3a42c5ff.png)

**Comment by Soulwhisper** [comment]
Fixed now.
