### ISSUE TITLE
Sticky feetz/MotM

### ISSUE THREAD

**Issue by gebajger** [WarEmu/WarBugs#8126]
AoE radius has been decreased significantly, its almost impossible to hit a moving target now, or slow down more than 1-2 enemy

**Comment by Luth-RoR** [comment]
Probably because of https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=17634
Though it could now be just like on the mythic server and people only got used to a higher radius on RoR.

**Comment by gebajger** [comment]
This ability has always been weaker in RoR. On the live servers, the moment you used it , it applied the snare, and the radius was bigger than the visual 'pond' .
In RoR there is a slight delay , maybe half a second that already made it more difficult to use properly.
Now, with the decreased radius its almost not worth the points.

**Comment by grunbag** [comment]
it match the visual effect, no issue here
