### ISSUE TITLE
Client immediatly close on invite group

### ISSUE THREAD

**Issue by gschouweiler** [WarEmu/WarBugs#8127]
Sometimes on group creation or on accept invite, client war.exe close immediatly like alt+f4 or silent crash.

After test we find the bug appear on IC when player is near mailbox area.

**Comment by Kaelang** [comment]
This sounds more like an individual issue, and not a flaw with the client. I appreciate this was back in 2016 - if you are still playing RoR, please feel free to re-open this issue if it persists or ask for help on our Technical Support forum.
