### ISSUE TITLE
There is no possibility to enter the game

### ISSUE THREAD

**Issue by polikotop** [WarEmu/WarBugs#813]
Good day.
I went into the character selection screen, press start, writes, Loading interface and returns back to the character selection screen.
Please tell me, what can it be? What are my options?
Thanks in advance.

**Comment by jelczi** [comment]
When on loading screen type /stuck

**Comment by polikotop** [comment]
What  loading screen type /stuck?
I'm not stuck! It takes a load. Then you return to the character selection screen!
Thank you.

**Comment by polikotop** [comment]
Thank you very much. Everything turned out. Problem solved.
