### ISSUE TITLE
One mastery point lost on equip accessories set bonuses

### ISSUE THREAD

**Issue by gschouweiler** [WarEmu/WarBugs#8132]
Hello,

This is the second time today i buy an item from set "of the medic". When I equip an item from this set , I lost my M4 and one point mastery.

After taking over M4, on unequip or equip, I lost again my M4 and one point mastery.

I'm Zealot and I use M4 from path of alchemy.

**Comment by gschouweiler** [comment]
I use set ruin, if I unequip a item from set, I lost also my M4 from path of alchemy.
The problem must be link to bonus 1 point to path of alchemy and refresh on calculte set bonus.

**Comment by fredator666** [comment]
Hi,
Losing the M4 is logical if you remove a piece of the set.
In my case, on my marauder, I lose the last skill from the mastery tree linked to the bonus from ruin set sometimes when I travel or disconnect/reconnect. I'll verify if its when I travel via fly masters or book/scrolls.

**Comment by gschouweiler** [comment]
Another test.

When I set a skill like last point in my mastery path of alchemy and I unequip any item(belt, jewel) from my character not necessarily an item of set ruin. The mastery point under skill disappear and reappear but the skill is lost.

**Comment by Luth-RoR** [comment]
Known issue: https://github.com/WarEmu/WarBugs/issues/7024
