### ISSUE TITLE
Auto Attack on Pets in not RvR marked Zones

### ISSUE THREAD

**Issue by Peppi1992** [WarEmu/WarBugs#8133]
Hi,
i saw this bug as we waited for _Nerx Gutslime_ ( Lair Boss ) to spawn.

My M8 a White Lion was standing there and two Sorcs autohittet his Pet till deatch.
When my M8 put on "Aggresiv" the Lion attacked the Sorcs and nearly killed one... 

If there are more Pet- Chars, they are maybe able to rly kill some1 who is waiting there?

Greetings
Sichlor

**Comment by Luth-RoR** [comment]
Was the sorc flagged for RvR?

**Comment by Peppi1992** [comment]
Nope. The name was still orange. She was able to Meele Autohit the Pet until it was dead.
We wanted to flag us to kill them, but it was in T1 and we don't did it then.

Don't you get Chickened when your flagged in lower Tiers?
Greetz Sichlor

**Comment by Luth-RoR** [comment]
Yes.

**Comment by Peppi1992** [comment]
Mh. Weird.
Dont know how it was on offi servers. 

BR
Sichlor

**Comment by Peppi1992** [comment]
Hi Luth,

no the Sorc wasn`t. Her name was still Orange as she meele autohittet the Pet -> I was trying to kill her so I flagged me for RvR but it didn't worked.

And my M8 ( The Lion ) was scared of being flagged while his Pet was attacking her while its was on aggresiv, so he pulled it on passiv,

but the sorc was still able to auto hit the pet... spooky...

Isnt that so, that you cant get flagged in T1 Locations?

Because we were in the Lair Boss Room from Nerx Gutslime in Dwarf T1...


Greetings
Dennis


________________________________
Von: Luth <notifications@github.com>
Gesendet: Donnerstag, 20. Oktober 2016 18:03
An: WarEmu/WarBugs
Cc: Peppi1992; Author
Betreff: Re: [WarEmu/WarBugs] Auto Attack on Pets in not RvR marked Zones (#8133)


Was the sorc flagged for RvR?

-

**Comment by Peppi1992** [comment]
Mhh. Weird. I really can not say how it was on the offi servers...

BR
Sichlor

Gesendet mit meinem HTC

----- Nachricht beantworten -----
Von: "Luth" <notifications@github.com>
An: "WarEmu/WarBugs" <WarBugs@noreply.github.com>
Cc: "Peppi1992" <dz1992@live.de>, "Author" <author@noreply.github.com>
Betreff: [WarEmu/WarBugs] Auto Attack on Pets in not RvR marked Zones (#8133)
Datum: Fr., Okt. 21, 2016 19:05


Yes.

-

**Comment by Luth-RoR** [comment]
The flag should be a "one-way street": You can decide to attack someone _who is flagged_, but you will be flagged in the same second as well. No one should be able to attack you _and your pet_ if you are not flagged.

**Comment by Tesq** [comment]
pet ingore the flag, this should be well know from sometimes now i belive

**Comment by Peppi1992** [comment]
Yeah,

I think the problem here is, when u really trying to fight a Lair boss or your farming mobs,

u hittet the pet before -  or the Lion pulls it on aggresiv, it will attack u and make huge trouble when ur infight.


I don't really know if this will work if they don't attacked the pet via auto attack before,

but there will be guys who will use it for their advantage... and the pets in WAR are kind of OP [😃]


Its nice to report things and trying to help. :) Your doing great work with RoR - I love this game and played it on offi times with a mate.

He sadly passed away 7 years ago and he was a gr8 white lion...


He was like me, trying to help and make things better and easier for others. [😊]  He would love RoR... Thx for that.


Go on and nice weekend guys! :)

________________________________
Von: Tesq <notifications@github.com>
Gesendet: Donnerstag, 27. Oktober 2016 00:14
An: WarEmu/WarBugs
Cc: Peppi1992; Author
Betreff: Re: [WarEmu/WarBugs] Auto Attack on Pets in not RvR marked Zones (#8133)


pet ingore the flag, this should be well know from sometimes now i belive
