### ISSUE TITLE
quest log bugged

### ISSUE THREAD

**Issue by deathsfingers** [WarEmu/WarBugs#8134]
I started out with 6 quests in my log, handed in 3 rvr quests. Tried to pick new quests and says quest log is full. I abandoned 2 quests and tried again and said full. Only shows 1 quest in my log. Reload ui and relog doesnt work.

**Comment by Luth-RoR** [comment]
Maybe your account is bugged.

**Comment by sioding** [comment]
No answer since 21.10.2016 - close for now.
