### ISSUE TITLE
Cannot be dyed and no appearence.

### ISSUE THREAD

**Issue by Rhungk** [WarEmu/WarBugs#8135]
Hi, the belt [Bellybuckle of Hatred],influence t4 belt, has no appearence and cannot be dyed, also the Mercenary set for Choppa cannot be dyed. Here the screenshots: http://imgur.com/pqN239G 

http://imgur.com/pqN239G    http://imgur.com/pqN239G

**Comment by Rhungk** [comment]
http://imgur.com/hiqDn7H  http://imgur.com/cBU06hW

**Comment by Luth-RoR** [comment]
Some items (models/textures) can't be died due to client side restrictions afaik.

**Comment by Rhungk** [comment]
So is there any solution or should i forget about it?

**Comment by Luth-RoR** [comment]
If the item has invisible/non-existant textures: i think it can be fixed.
If the item can not dyed with a second color: i think not (at least not at the moment).
Perhaps a DB-dev can clarify.

**Comment by Rhungk** [comment]
I post it because i have seen players with the mercenary shoudrers dyed (all the piece, even the maw as if  it has only one cap) and the same belt that i have, so idk if there is some "legal" bug like change the appearance of a non apearance avaiable piece (switching the position on the bag) or something. Its not a whim, i saw it.

**Comment by Luth-RoR** [comment]
You applied alternate appearance to both items; in this case of course the models/textures of the _Darkshroud Bellybuckle_ and _Gnawbone's Shouldaspikes_ are used to check if they can be dyed.
If you want to dye your merc shoulder and hatred belt, you'll just have to remove the alternate appearance.

**Comment by Luth-RoR** [comment]
Belt textures will be fixed, the shoulders can't be fixed yet.

**Comment by Rhungk** [comment]
Ok ty ^^
