### ISSUE TITLE
[Black Orc] Loudmouth no longer crit + do less damage than a written on tactics+different damage from various war bellow+does not increase damage from tactic with +% damage.

### ISSUE THREAD

**Issue by Killham** [WarEmu/WarBugs#8139]
Many many many many times tested on 37 lvl mobs:
1. tactic dont crit anymore
2. with Da Biggest! war bellow do 180(35)=215 damage, 
with Da Toughest!  war bellow do 163(32)=195 damage, 
with Da Greenest war bellow do 126(24)=150 damage,
so not even close to 226 damage which written on tactic
3. tactic with +% damage does not effect on Loudmouth (focused offense +15% outgoing damage and Guud at Big Choppin! +10% outgoing damage) so same damage with +% damage tactic and without
4. -armor debuff does not effect on Loudmouth so with -armor or without armor debuff tactic do the same damage
only with taunt do more damage.

**Comment by Luth-RoR** [comment]
Damage from procs didn't crit on the mythic server. Same with increased damage percent buffs. A screenshot/evidence would have been nice.

**Comment by Killham** [comment]
![1](https://cloud.githubusercontent.com/assets/18173840/19620417/9d8974c2-9885-11e6-963c-ba9cc4f20031.jpg)
![2](https://cloud.githubusercontent.com/assets/18173840/19620418/a6196da4-9885-11e6-9b68-5b34f5c4e16e.jpg)
![3](https://cloud.githubusercontent.com/assets/18173840/19620420/b0f0580a-9885-11e6-827a-4620d89546a5.jpg)

**Comment by Killham** [comment]
couple screen with SM tactic potent enchantments have a crit:
![Uploading 4.jpg…]()

**Comment by Luth-RoR** [comment]
No one on the dev team can read cyrillic and there is a general rule to post in english.
About tactics that crit: https://github.com/WarEmu/WarBugs/issues/8165
