### ISSUE TITLE
[Magus] If pet gets the killing blow the kill is not acknowledged in the scenario

### ISSUE THREAD

**Issue by fesust** [WarEmu/WarBugs#8140]
Played a Highpass Cemetery today. We all finished the scenario on destruction side with 0xp and 0rp 0kills. However I was able to kill 2 shadow warriors with my magus. None of the were counted toward destruction points, since the killing blow was done by the demon turret.

**Comment by Luth-RoR** [comment]
All objective based scenarios don't show that: https://github.com/WarEmu/WarBugs/issues/7871
