### ISSUE TITLE
Kotbs Aura On Your Guard procs from rdd atttacks

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#8142]
http://take.ms/ZvGDS

**Comment by Luth-RoR** [comment]
If any character/NPC enters melee range, he switches to melee auto attacks:
**Range AA with OyG (not in melee range):**
![20161022153144_1_crop](https://cloud.githubusercontent.com/assets/8567481/19619722/fc8a8c3a-986d-11e6-9e9d-ca7644b3fcb6.jpg)

**Melee AA with OyG (in melee range):**
![20161022153219_1_crop](https://cloud.githubusercontent.com/assets/8567481/19619731/227abde8-986e-11e6-8e57-5cc28e0ce4e1.jpg)
