### ISSUE TITLE
Titles not working

### ISSUE THREAD

**Issue by Riefenstahl** [WarEmu/WarBugs#8143]
Hey Devs: The easy obtainable Titles (granted via social menu), are not working.

For example The Snob (add 5 people to your ignore list) They do not work.

Also take a look at those maybe?

     Been resurrected 20 times - Title: The Revived, 66xp
    Been resurrected 100 times - Title: The Reborn, 66xp
    Been resurrected 500 times - Title: The Re-animated, 66xp
    Been resurrected 1000 times - Title: The Healer's Hassle, 66xp
    Been resurrected 10 000 times - Title : The Pheonix's Brother, 66xp
    Triggered 25 Critical Hits - Title: The Crucial Crusher, 66xp
    Triggered 250 Critical Hits - Title: The Strategic Hitter, 66xp
    Triggered 5,000 Critical Hits - Title: The Pivotal Force, 66xp
    Triggered 50,000 Critical Hits - Title: The Timed Striker, 66xp
    Triggered 500.000 Critical Hits - Title: The Dire Dealer, 66xp

**Comment by Luth-RoR** [comment]
Please check the rules of the bugtracker. Only one bug per report and no generic reports (for obvious reasons).
Also: no requests.
These titles don't work, because the prerequisites havn't been coded yet.
