### ISSUE TITLE
Guildquit and guildleave not working

### ISSUE THREAD

**Issue by fesust** [WarEmu/WarBugs#8144]
Don't know if it's only me, but I can't use /guildquit or /guildleave commands. Nothing happening, I'm staying in the guild.
I'm not the last person in the guild, there are others online as I try to quit, nor am I leader.

**Comment by Soulwhisper** [comment]
Why they should work? There is a button to leave...

**Comment by sioding** [comment]
No answer since 22.10.2016 - close for now.
