### ISSUE TITLE
Chaos ch16 "Fury Tamed"

### ISSUE THREAD

**Issue by Gakvar** [WarEmu/WarBugs#8146]
Creature Ironmaw is nowhere to be found, no map indication of its location and no text reference of directions.

**Comment by lennip** [comment]
I can confirm the absence of a marker on the map when accepting the quest, which makes it very difficult to locate Ironmaw. I searched it everywhere around chapt 16 and couldn't find it so I can't tell if creature is missing or just very hard to find

**Comment by zak68** [comment]
you can find it in cw, lower left corner, near the road; gray at lvl 40.

**Comment by sioding** [comment]
questmarker fixed next patch

**Comment by sioding** [comment]
Fixed with patch from 18.09.2018
