### ISSUE TITLE
Double quest rewards

### ISSUE THREAD

**Issue by xyeppp** [WarEmu/WarBugs#815]
After the hotfix applied by nalgol, quests now give two rewards instead of one. Got two jewels for the event quest, same with a quest in Trollhaugen where you select one of two belts - have gotten both.

**Comment by Reggaewaldo** [comment]
This should be fixed, can someone confirm ?

**Comment by nalgol** [comment]
should be fixed long ago the selection was bitwise not byte whise that was the problem
