### ISSUE TITLE
Double spawn Thanris the Twisted, Avelorn

### ISSUE THREAD

**Issue by Gideon404** [WarEmu/WarBugs#8151]
As title.

**Comment by Luth-RoR** [comment]
Coordinates would be helpful.

**Comment by Gideon404** [comment]
Apologies, I was not sure which fields you could query.  She's at the 35k,16k chaos NPC camp

**Comment by Luth-RoR** [comment]
Thanks.

**Comment by wargrimnir** [comment]
Removed doublespawn.
