### ISSUE TITLE
Public Quest next to Chapter 20. Empire

### ISSUE THREAD

**Issue by Peppi1992** [WarEmu/WarBugs#8154]

**Comment by Peppi1992** [comment]
Hi, 
At the public quest next to chapter 20, the Champions in the fourth step can't be klicked on by Mouse. You have to w8 till they attack you, to get them into target to kill.
Its a little annoying when there are more ppl. 
The PQ is nice for solo farming fragments for Ruin Set. 

Greetz sichlor

**Comment by Peppi1992** [comment]
Add. In Chaoswaste

**Comment by Luth-RoR** [comment]
What's the name of the PQ and the champions?

**Comment by Peppi1992** [comment]
Pq - Raizing an Army
Champs - Frostmarrow Deadraiser

Greetz sichlor

**Comment by Luth-RoR** [comment]
Seems like this bug is back then: https://github.com/WarEmu/WarBugs/issues/8065

**Comment by Soulwhisper** [comment]
We should close this.Reopen 8065.

**Comment by Soulwhisper** [comment]
Wait...i just did the PQ.They are fine(Frostmarrow Deadraiser).

**Comment by Luth-RoR** [comment]
Thanks; closing then.

**Comment by Peppi1992** [comment]
Mhh.

no, my bad. I just registered me on Github this week, and I thought about this bug, as I farmed my ruin gear fragments.

that is 2 weeks ago. Sorry I should had seen this report, I checked them for this bug... Maybe because I didn't knew the creepnames, checked them via Warhammerwikia yesterday.

BR
Sichlor


________________________________
Von: Luth <notifications@github.com>
Gesendet: Sonntag, 23. Oktober 2016 20:41
An: WarEmu/WarBugs
Cc: Peppi1992; Author
Betreff: Re: [WarEmu/WarBugs] Public Quest next to Chapter 20. Empire (#8154)


Seems like this bug is back then: #8065<https://github.com/WarEmu/WarBugs/issues/8065>

-

**Comment by Peppi1992** [comment]
Sorry than. >.<

My bad.


BR
Sichlor


________________________________
Von: Luth <notifications@github.com>
Gesendet: Montag, 24. Oktober 2016 21:07
An: WarEmu/WarBugs
Cc: Peppi1992; Author
Betreff: Re: [WarEmu/WarBugs] Public Quest next to Chapter 20. Empire (#8154)


Thanks; closing then.

-
