### ISSUE TITLE
Quest: All Wrapped Up

### ISSUE THREAD

**Issue by Nekronsieben** [WarEmu/WarBugs#8155]
After you got the quest objective **Hagan's Belongings** the quest description tells you to "return them to Hagan at **Wulfsiege**" but thats wrong, the quest return is at **Sorcerer's Axiom** (where you got the quest from) and thats what it should be in the description.

**Comment by Luth-RoR** [comment]
According to https://github.com/WarEmu/WarBugs/issues/5790 it should be Hagan, but i don't know.

**Comment by Nekronsieben** [comment]
yes it is Hagan, but the writen down location of the return quest is wrong in the description.

**Comment by wargrimnir** [comment]
Updated description
