### ISSUE TITLE
WE's Kiss of Death didn't proc at all.

### ISSUE THREAD

**Issue by spacestarkid13** [WarEmu/WarBugs#8156]
Got Kiss of Death  on, and it didn't proc at all. Or procs sometimes but not as 25%. Like 1-2 times for a fight. It has to proc from ability and aa.
![mashka_010](https://cloud.githubusercontent.com/assets/16030337/19628945/a49176fa-9972-11e6-88ee-7a85da5d1606.jpg)

**Comment by Torquemadra** [comment]
such is the  nature of rng
