### ISSUE TITLE
[Token bag] Ruin's Armor

### ISSUE THREAD

**Issue by D4W0lf** [WarEmu/WarBugs#8157]
I did a search but did not find that a similar problem had been reported, therefore in doubt.
Yesterday I go to the armor seller of ruin and inadvertently I sold him a green bag.
I immediately bought the bag one copper coin, but now I can not open it.
When I click on it nothing happen.
I reloadui + reboot the game, but nothing too.

**Comment by Luth-RoR** [comment]
Known: https://github.com/WarEmu/WarBugs/issues/6840

**Comment by D4W0lf** [comment]
Ok, sorry then.
