### ISSUE TITLE
Bump into south keep praag / squig

### ISSUE THREAD

**Issue by Tholkienn** [WarEmu/WarBugs#8160]
The squig can jump into the south keep praag, with their bump they jump on outer walls on the east side.

**Comment by Luth-RoR** [comment]
This was fixed a while ago iirc.

**Comment by Tholkienn** [comment]
That not fixe, i see a squig done that yesterday.

**Comment by Luth-RoR** [comment]
Is it just a special spot (screenshot etc. would help to see what's meant)?

**Comment by Tholkienn** [comment]
http://img15.hostingpics.net/pics/136721Aniomed099.jpg

**Comment by saupreusse** [comment]
temp fixed with some palisades until we have client control
