### ISSUE TITLE
SC Bug - Not in a Match

### ISSUE THREAD

**Issue by JackBlackthorn** [WarEmu/WarBugs#8162]
![scbug](https://cloud.githubusercontent.com/assets/23072923/19719095/b17655dc-9b68-11e6-879c-3ce18a11f5a8.jpg)
I do not know how to describe it correctly. I joined a SC with three players. The score screen only shows two(see screenshot), me (Spite) and the RP(Bärtiger) but we also had a Sorc(Lysandrosas).

The SC did not start even after the timer ticket down, we could leave the Spawn point while the timer was > 0. Taking the SC-Objective did not earn any points. Only way to leave the SC was to leave the game.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/8059
