### ISSUE TITLE
Debolstering to 15 from 38 instead of 11 in T1 RVR

### ISSUE THREAD

**Issue by RevMalthus** [WarEmu/WarBugs#8164]
I made contact with GM Grandpa prior to this report. I debolstered from T4 (lvl 38 KOTBS) to T1 RVR earlier this afternoon, and after originally being debolstered to 11, I subsequently died, and then was "re-debolstered" to level 15. 

I can attempt to recreate the issue if necessary, but I was able to easy outperform other players in T1 RVR and had attempted to flag a GM about the issue at the time. I brought it up with Grandpa after he thought I was botting (but truly just making my wife a sandwich while AFK, with KOTBS passive AOE on) 

Please feel free to contact me in game, my player name is Rochambeaux. 

If this is a bug can I get one of those sweet bird mounts?!?!

All the best,
Jack/Rochambeaux

**Comment by Luth-RoR** [comment]
I tried this on the dev server and it didn't work; the bolster tooltip always says level 15, which can't be changed yet. No evidence posted too.

> If this is a bug can I get one of those sweet bird mounts?!?!
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366#p118993

**Comment by Soulwhisper** [comment]
Wow...hahaha #4200 Found it!
