### ISSUE TITLE
SM:Ensorceled Agony

### ISSUE THREAD

**Issue by lastadm** [WarEmu/WarBugs#8165]
Critical damage from tactic. I think tactics can not critical hit.
![image](https://cloud.githubusercontent.com/assets/18344297/19764927/1615bad6-9c5f-11e6-9f5e-28b5538ee67d.png)

**Comment by Luth-RoR** [comment]
Refering to https://github.com/WarEmu/WarBugs/issues/8139

**Comment by ozarmidrashim** [comment]
https://taugrim.com/2009/08/16/war-swordmaster-guide-mechanics-part-2/
