### ISSUE TITLE
Unable to connect to game servers ingame

### ISSUE THREAD

**Issue by LegendaryPow** [WarEmu/WarBugs#8166]
played for last month without any troubles. last two days got bug with connection to game servers. game loads and I`m just panding in character choice menu, tried all fixes from forum guides, but non of them helped. Bug like in this guide in login section
 https://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=2889
I`m not only who got this bug. 
https://www.returnofreckoning.com/forum/viewtopic.php?f=4&t=17922
Gms in game said that I can get reward if found some bugs) hope get griffon)

**Comment by Luth-RoR** [comment]
The bugtracker is for bugs. 
Every support goes to the support forum.
The server is online and communicating with many clients atm (Player count : 575/1400).
Solving any client side connection issues is primarily a problem of the user and out of reach of any staff member.

https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366#p118993
