### ISSUE TITLE
T4 Scenario reward weapons

### ISSUE THREAD

**Issue by Disturbedst** [WarEmu/WarBugs#8169]
T4 scenario reward weapons on destro side: Sentry's Sword of Vehemence and Sentry's Chaosaxe of Vehemence are not quite the same. The sword has one less thoughness (19) while the axe has 20. The axe also doesn't have alternate appearance available like the sword does.
![bugtracker](https://cloud.githubusercontent.com/assets/19360409/19779035/a465eb06-9c7f-11e6-9a31-1a36cde7c559.png)

**Comment by wargrimnir** [comment]
Updated several Vehemence items.
