### ISSUE TITLE
How to break witchfire PQ

### ISSUE THREAD

**Issue by RevMalthus** [WarEmu/WarBugs#8170]
So, I was grinding on the Witchfire PQ in Talabecland, and I failed to click on all of the posts (stage 2) and the PQ failed, with a message that it failed. 

I'm not sure if this is the appropriate place for a comment such as this, but as the PQ list said it was functioning correctly, i figured I'd mention it.

All the best,
Rochambeaux

**Comment by Soulwhisper** [comment]
Looking into it.

**Comment by grunbag** [comment]
Need to be fixed , or close it ?

**Comment by Luth-RoR** [comment]
Forgot to close it.
