### ISSUE TITLE
Buying equipment bug

### ISSUE THREAD

**Issue by RevMalthus** [WarEmu/WarBugs#8174]
Hey all,

I found an actual bug this time- when you shift and right click to purchase multipe RVR accessories- the vendor takes the money but does not give you ANY of the items!!!

T1 RVR, tried with Battle Ring of Vengeance and Runed Band of Vengeance, occured both times., multiple times each !

Please feel free to contact me. 

Best,
Jack/Rochambeaux/Lafayette

**Comment by Luth-RoR** [comment]
Doesn't work for me on the dev server, neither on the T1 RvR vendors nor on other vendors i tested. Do you have any addons activated that could cause that?

**Comment by RevMalthus** [comment]
I dont believe so- I was using healgrid at the time- I cant imagine that
healgrid would have caused that.

**Comment by Luth-RoR** [comment]
I tried several times to shift+rightclick some items on the vendors (also the mentioned ones, to be sure) but they neither moved to the inventory nor any gold was taken.

**Comment by RevMalthus** [comment]
I should have mentioned that after shift right clicking I entered 3 as the
amount. How many did you try?

**Comment by Luth-RoR** [comment]
That's my problem: i don't get a window to enter something. :smile:

**Comment by Luth-RoR** [comment]
It was my fault; some addon on my client prevented the window from popping up.

**Comment by RevMalthus** [comment]
Did you observe that you didnt get the items?

**Comment by Luth-RoR** [comment]
Yes, no items for me and the gold was taken away. I guess this is simply not yet coded on the server.
