### ISSUE TITLE
Items from another player listed in my Auction House

### ISSUE THREAD

**Issue by SeskaBlack** [WarEmu/WarBugs#8176]
![ahitembug_28-10-16](https://cloud.githubusercontent.com/assets/23119036/19804385/dedcd89a-9d05-11e6-9263-ef5ef6be6a3e.jpg)

I seem to be getting another person's AH items appear on my AH. If I try and 'Cancel' said items I get the message "An unknown error was encountered with the auction house." (as per the screenshot).

There's so many of these items I now don't know which are mine and which aren't. I've searched the forums and bug list and can't find any similar issues.

**Comment by Luth-RoR** [comment]
Known: https://github.com/WarEmu/WarBugs/issues/3904 https://github.com/WarEmu/WarBugs/issues/8067

**Comment by SeskaBlack** [comment]
Apologies. Clearly didn't look/search hard enough.
