### ISSUE TITLE
Reward from epic quest

### ISSUE THREAD

**Issue by lastadm** [WarEmu/WarBugs#8178]
![image](https://cloud.githubusercontent.com/assets/18344297/19805901/a389f072-9d30-11e6-9f22-e1f2640bd6f8.png)

**Comment by Torquemadra** [comment]
you are linking a test quest, one thats not accessable in the world

**Comment by lastadm** [comment]
i am not tester

**Comment by Luth-RoR** [comment]
You linked the wrong quest ID in the chat, one from a quest that is not accessable in the world. 
You need the correct ID from the _Annihilation_ qest.
