### ISSUE TITLE
Flood Error since patch 28/10

### ISSUE THREAD

**Issue by gschouweiler** [WarEmu/WarBugs#8179]
Please find an error appear since Patch 28/10/2016

A flood in message system

![image](https://cloud.githubusercontent.com/assets/22920863/19806362/a54562b8-9d1a-11e6-9ba4-f283881ec593.png)

**Comment by Luth-RoR** [comment]
I'm going to close this, as the server side log is spammed too and Devs notice it anyway/are at it.
