### ISSUE TITLE
Bug 1hander healing dwarf influence healing hammer.

### ISSUE THREAD

**Issue by Xiphy** [WarEmu/WarBugs#8182]
The 1hander Healing dwarf influence healing hammer is giving +8 RF.

**Comment by Luth-RoR** [comment]
>The 1hander Healing dwarf influence healing hammer is giving +8 RF.

Class? 
I guess it's warrior priest, though it would be nice to mention it, so that can others find the report too via the search function.
Dwarf influence? From which tier, RvR or PQ?
How was this tested? 
Evidence/screenshot?

**Comment by Luth-RoR** [comment]
Nvm, this report will be used for the case: https://github.com/WarEmu/WarBugs/issues/8183
It's far more complete.
