### ISSUE TITLE
Righteous Fury regeneration bug

### ISSUE THREAD

**Issue by Ondorie** [WarEmu/WarBugs#8183]
Since the patch was released on the 28/10/16 the Apostel´s Tome of Seoleminity (T4 scenario weapon) won´t regenerate any righteous fury, instead the Bloodfist Battlehammer (T4 Dwarfs - influence reward) will regen it and even has the text saying so.
Every book tested so far won´t regen any fury at all.

**Comment by Torquemadra** [comment]
tome of solemnity is showing the correct effect, effect removed from battlehammer
