### ISSUE TITLE
Tier 1 Locking after capturing all BO's

### ISSUE THREAD

**Issue by Renork** [WarEmu/WarBugs#8184]
"Tier 1 will now lock when all battlefield objectives have been held by a realm for 15 minutes.

Players will no longer earn rewards for kills made in a pairing that does not contain an open zone.

Players tend to continue fighting in Nordland even when it's locked. Get out and see the world, Mount Bloodhorn is nice at this time of year."

Zone is automatically locking, without waiting 15 minutes.

**Comment by gittoaster** [comment]
In Mount Bloodhorn, as Order, could not cap the Lookout BO when it was showing "open" and the zone was contested.

thx
