### ISSUE TITLE
dyed cloaks are only visible to yourself

### ISSUE THREAD

**Issue by Culdu** [WarEmu/WarBugs#8186]
Other Player only see basic color on a cloak and not the color you have dyed on it. 
Very sad with this amazing new halloween cloaks :(

**Comment by Culdu** [comment]
![cloak](https://cloud.githubusercontent.com/assets/14928735/19818630/e699c70a-9d50-11e6-904b-51320a8c3dce.jpg)

**Comment by Vancerus** [comment]
![vancero_235](https://cloud.githubusercontent.com/assets/14907399/19818652/f74f7144-9d50-11e6-81e9-e8eb74546775.jpg)

**Comment by Luth-RoR** [comment]
Maybe not possible atm, as the cloaks were not used on the 1.4.8 client for players.

**Comment by Culdu** [comment]
affecting all cloaks not only the new ones

**Comment by MaxHayman** [comment]
Fixed a while ago.
