### ISSUE TITLE
Battle crosses should refresh

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#8187]
They just pile up across the whole map, so there is no use - all of the map is covered with them and you don't see where is fight actually going.
In old Warhammer they refreshing themselves and stay only in on-going-fight areas. Probably there was a limit, but i can't say for sure.
![default](https://cloud.githubusercontent.com/assets/18102127/19817408/85a3478a-9d5c-11e6-8410-7bae95ce8266.png)

**Comment by Luth-RoR** [comment]
Londo updated the hotspot logic already; it will be pushed on the next patch/hotfix.
