### ISSUE TITLE
Burn Salve - Engineer

### ISSUE THREAD

**Issue by Pumpgunpete** [WarEmu/WarBugs#8189]
Hi, 
if the Engi remove a single part of the equiped gear (Armor / Jewerly / Weapon), it´s also remove the group buff "Burn Salve". There is no problem to rebuff. 
Cant remember it was existing before the last patch 28102016. 
The self buff "Flak Jaket" is **not** affected by this bug.

Many thanks!
BR

**Comment by Torquemadra** [comment]
This is related to the extra +1 to trees from a set bonus, changing any item will reset abilities that are boosted by any of the three trees. Flak Jacket is core and not boosted by any tree which is why its unaffected.
