### ISSUE TITLE
Black Orc's "Save'n Me Hide" duration of effect is incorrect & animation

### ISSUE THREAD

**Issue by murmelon** [WarEmu/WarBugs#819]
effect exists from 2 parts:
1. self buff-  increase tougness by 4 sec instead  20 sec.
2. party buff  - decrease incoming magic dmg by 4 sec -This effect buffs black orc now, it is incorrect.

Mass Taunt - doesn't  animated at enemies.

**Comment by ozarmidrashim** [comment]
Forgot to update the ability modifiers table. This issue will be fixed the next time the server restarts.
