### ISSUE TITLE
Mismatched Warrior Priest and Disciple of Khaine SC healing weapons

### ISSUE THREAD

**Issue by CecilHarvey9** [WarEmu/WarBugs#8191]
![stats](https://cloud.githubusercontent.com/assets/16202660/19822029/471c0fe2-9d16-11e6-81bb-6307ff36608d.jpg)
Pictures of the healing Warrior Priest and Disciple of Khaine weapons/offhand. 
My assumption is they should look like the WPs with the armor pen and chance to be crit reduction.

**Comment by Torquemadra** [comment]
thank you
