### ISSUE TITLE
Quest: Pile On (npc out of place)

### ISSUE THREAD

**Issue by Nekronsieben** [WarEmu/WarBugs#8193]
## Quest mission:

![war 2016-10-29 02-50-50-94](https://cloud.githubusercontent.com/assets/22836615/19826548/cff645b8-9d8d-11e6-92a4-5c2693d0df67.jpg)
## Problem:

The NPC **Boozraz Waaagzzug** is not at the marked location. 
_I know that on official server he would be patrouling that street, 
but since this is not possible he is quite far away and I only found him by accident._

![war 2016-10-29 02-50-17-01](https://cloud.githubusercontent.com/assets/22836615/19826552/e1edf126-9d8d-11e6-98d7-5962f13a8286.jpg)

![war 2016-10-29 02-50-24-77](https://cloud.githubusercontent.com/assets/22836615/19826554/f08379a4-9d8d-11e6-8644-d080a92df8c5.jpg)

**He should be standing at the marked location.**
![war 2016-10-29 02-50-42-73](https://cloud.githubusercontent.com/assets/22836615/19826556/0b5b0d0a-9d8e-11e6-93ea-b6d6dfc1932d.jpg)

**Comment by saupreusse** [comment]
Fixed in the next patch.
