### ISSUE TITLE
Quest: Making Magic (object still buged)

### ISSUE THREAD

**Issue by Nekronsieben** [WarEmu/WarBugs#8195]
---> closed ticket #8078
Object is still not working, just tested today.
![war 2016-10-29 03-09-44-95](https://cloud.githubusercontent.com/assets/22836615/19826664/19e6d194-9d91-11e6-9b16-1d99ada071ce.jpg)

![war 2016-10-29 03-08-33-43](https://cloud.githubusercontent.com/assets/22836615/19826667/316e6570-9d91-11e6-8e5a-b32058adc803.jpg)

**Comment by Luth-RoR** [comment]
I re-opened the old one, thanks for the report.
