### ISSUE TITLE
NPC: skyrage sharptalon (out of range)

### ISSUE THREAD

**Issue by Nekronsieben** [WarEmu/WarBugs#8196]
I have noticed that many (like 50%) of the **skyrage sharptalon** were marked as 
1. "...to close" or 
2. "...out of range". 
_Even with ranged attackes they were not attack able._ 

1.
![1 to close](https://cloud.githubusercontent.com/assets/22836615/19826741/32dba628-9d93-11e6-93fd-ddacc7d48d1a.jpg)

2.
![2 out of range](https://cloud.githubusercontent.com/assets/22836615/19826743/37368404-9d93-11e6-8d01-a6864ae3e4b7.jpg)
### Location:

![3 map marker](https://cloud.githubusercontent.com/assets/22836615/19826748/60b940dc-9d93-11e6-8bbb-93f60eb27c81.jpg)

**Comment by Luth-RoR** [comment]
I think this still is a general problem with NPCs who can fly around.

**Comment by Nekronsieben** [comment]
I could solve the quest because there where enough killable enemys, but it was still annoying.
If there is no short way to fix it, I think its not that big of a problem.

**Comment by Lheana** [comment]
I think this has been fixed since NPCs can fly.
