### ISSUE TITLE
PQ - Lonely Tower - Not Dropping Gold/Purple

### ISSUE THREAD

**Issue by Unkillachosen** [WarEmu/WarBugs#8197]
Dont know if this is a intended thing but this specific PQ doesnt seem to give epic or gold bags ever. Wonder if it was a bug or a balance change for loot drops not mentioned in the patch

**Comment by Luth-RoR** [comment]
https://youtu.be/cMNILk2vXYY?t=212
>doesnt seem to give epic or gold bags ever

How was this tested?

**Comment by Soulwhisper** [comment]
Why it should drop Gold bag? It has a chance to drop a Purple bag though.
This PQ is flagged on map as "Easy" but its true ID and the Loot Code behind it is as "Normal".
So it drops 1 Blue,3 Green and 1 White bag with a high chance to drop at least 1 Purple bag.There is a low chance to drop 1 Gold bag.

**Comment by Unkillachosen** [comment]
it was tested after doing around 30 straight PQs. but thanks for the response and correction, ty
