### ISSUE TITLE
SW arrows floating, mobs dying but not "dying"!

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#8199]
Hi,
This happens a bit from time to time, but have noticed yesterday and today that it is a lot more frequent. I've been attacking the mobs for the Live Event using Skirmish Stance on my Shadow Warrior. At times, I will kill a mob but the arrows will hover in mid air and not land. I can see the sparkles to note there is loot to pick up, but I can't get it as the mob is still standing as if he is not slain. Sometimes this will fix itself over about 30 seconds if I just stand still and wait, but most of the time the mob will disappear and respawn before the arrows "catch up" with the mob being killed, and him falling to the floor so I can collect any loot. I've found if I relog it will fix it for a little while, but it seems to be worse if there are other players in the same area as my character - sometimes I can only kill 4 mobs before this starts to happen. Here are a couple of screenshots for you. Really enjoying the Live Event by the way!
![senthoi_012](https://cloud.githubusercontent.com/assets/22262165/19829010/3b1b5866-9dce-11e6-9646-7494514150e3.jpg)
![senthoi_013](https://cloud.githubusercontent.com/assets/22262165/19829011/3b2223f8-9dce-11e6-9088-414f27f07f72.jpg)

**Comment by Luth-RoR** [comment]
I noticed this too on my engi. Could be lag/latency related though.

**Comment by Kaelang** [comment]
As of 22/04/2020 this should have been fixed. 

- Finished to fix all projectile speed on ranged abilities. They almost all had a longer flight time than intended.

Please re-open this report if you are still experiencing this issue.

**Comment by Senthoi** [comment]
Thank you! ;)
