### ISSUE TITLE
[abilities] Unable to purchase abilities from the career trainer

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#82]
Up until this point abilities have been automatically given to characters instantly. 

I noticed one ability (tactic ability) that had not been added. Perhaps this one is bugged?? 

When I tried to purchase it, I could not gain it.

![skills purchase](https://cloud.githubusercontent.com/assets/7492543/2922267/f6a100b6-d6fe-11e3-9c0e-4c4d7d90771c.png)

**Comment by Reggaewaldo** [comment]
As JeFawk said. That's how it was on live but it's different on the server. Should we keep it as is or change to align with how it was on live ?

**Comment by Evildoor** [comment]
This (CoT or any other ability/tactic being unavailable) stopped happening long time ago. The only exceptions are pet abilities (and they are a separate problem, with their disappearances on zoning and other crap) and things intentionally moved around (Don't Hate Da Choppa, for example).

The fact that you don't need to purchase abilities and tactics is not a bug, more like "Not implemented". And, to be honest, i hope that it stays that way. I don't see any positive thing the project can gain by spending time and effort of the devs to implement it.
