### ISSUE TITLE
[Marauder] Mutations, auto attack bugs

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#820]
**Auto-attack**
Off-hand auto attack works only in Gift of Brutality duration proc or if main hand attack crit.

**Gift of Brutality, Gift of Monstrosity**
Gift proc not dissapear on mutation change.
Gift proc can reproc while its effect duration.

**Comment by ozarmidrashim** [comment]
Partial fix (gift refreshing)
