### ISSUE TITLE
CD decrease are not retroactive

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#8200]
once a cd decrease got used in live after one of your skill was under a cd increase eff the reduction was applied to the currently ongoign CD count and not only to future cd.

exemple:

1) shatter limbs
2)use aoe heals
3) aoe heals get 5 sec CD
4)choppa fasta 
5) heal can be spam again "immidiately"

here on ror atm, i still get the full reduction duration.

**Comment by Kaelang** [comment]
Appreciate this is a dated report - however this does not provide enough information to identify the issue and/or replicate the problem. Please re-open this issue if this persists in the latest version of RoR.
