### ISSUE TITLE
Oath runes not giving Granted abilities to caster.

### ISSUE THREAD

**Issue by AlistaireCrowley** [WarEmu/WarBugs#8201]
When as RP casting an Oathrune on self you dont get the granted ability tied to the rune. 

I clearly remember that you actually got the Granted ability on live. 

Best regards

**Comment by Luth-RoR** [comment]
![luthrp_009_crop](https://cloud.githubusercontent.com/assets/8567481/19830447/fb8b1a8a-9df8-11e6-8b2a-94b9c53994b8.jpg)
![luthrp_008_crop](https://cloud.githubusercontent.com/assets/8567481/19830449/06120c84-9df9-11e6-8ef9-3977e5125264.jpg)
![luthrp_007_crop](https://cloud.githubusercontent.com/assets/8567481/19830454/1156206c-9df9-11e6-831a-b5df8b061c3a.jpg)
![luthrp_006_crop](https://cloud.githubusercontent.com/assets/8567481/19830458/1e08b5d6-9df9-11e6-9be4-6e278409a8f7.jpg)
