### ISSUE TITLE
Unable to drop off aquired supplies

### ISSUE THREAD

**Issue by istherepie** [WarEmu/WarBugs#8203]
Greetings, 

I have encountered the following issue after the delivering supplies to the drop off point:
- The animation (blue beam) for carrying supplies persists
- I was able to interact with the drop off banner several time 
- Each time interacting with the banner, I was rewarded wtih 36 renown points

The screenshot shows several entries where I am gaining 36 renown points:

![Screenshot](https://cloud.githubusercontent.com/assets/12992622/19831851/e3b32526-9e14-11e6-825a-46df99d78ef5.png)

The supplies used in this scenario where aquired by killing an enemy supply carrier and not from a captured objective. 

Regards, 
Beanieparrot

**Comment by istherepie** [comment]
I have interacted with the drop off banner around 7 times if you wish to deduct the extra unintended renown points (7 * 36 rp).

**Comment by vidummy** [comment]
Can confirm still happening. Grabbed supplies from Sari' Daroir in Saphery and was able to continuously turn in supplies. Details: I stood around with the supplies for awhile before even trying first turn in. Keep had just been fully repaired from siege. Class Shaman.

**Comment by sioding** [comment]
Since we have totally changes the open rvr campaign and there is no need to carry supplies i will close this now. Thanks for the report.
