### ISSUE TITLE
Delving in the Deep

### ISSUE THREAD

**Issue by Nefarian11** [WarEmu/WarBugs#8204]
Killing the spirit dwarves in Grom Rodrin (in Death Peak) doesn't give you credit towards the completion of the quest, making this quest impossible to complete. 

Tried killing every type of ghost-dwarf npc found in Grom Rodrin, but no one of them counts

**Comment by Ryanfawkez** [comment]
Valayan Disciples count.

**Comment by sioding** [comment]
works fine
