### ISSUE TITLE
Some bugs I've noticed that need some serious attention.

### ISSUE THREAD

**Issue by Svatyr** [WarEmu/WarBugs#8207]
Im just going to make a list of things that have been going on for a little bit, stuff that is kind of annoying.

1. The map does not work once so ever, 95% of the time it places people where they arent. This makes rvr really hard because most of the time team dots are EVERYWHERE. 

2. My lion keeps disappearing as I move through the zones, but when I go to summon him it makes me wait for his re-spawn timer. He even has vanished mid way through a lair boss for no reason other than random crap, just fades through the floor kind of crap.

3. Some objectives in Tier 1 will reset when you cap them, and give you nothing in return simply going to opposite faction control , or going neutral and being un-capable (( really prevalent in dwarf.))

And Finally I've been experiencing issues staying in game with little things like, team fights making me crash but not crash. The game is still running and I cant make it come back, normally having to task manager it to make it stop. This is just sutff Id like to have addressed at your earliest connivance , thanks for your time and have a good one. (( P.S I cant wait for the other capital cities <3)). My character name is the same as my user name, Im on order so you know if you need to get a hold of me.

**Comment by Luth-RoR** [comment]
>Im just going to make a list

On report per bug; also check the search function for known bugs.

>This is just sutff Id like to have addressed at your earliest connivance

...
