### ISSUE TITLE
[Items] All destructions boundless cloaks

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#8208]
Same resistances set (high spirit) as for order

**Comment by Luth-RoR** [comment]
Maybe you could post what the issue is here + screenshots etc.

**Comment by MKorin** [comment]
Order need spirit resits.
Destro need corp resist.
Both got spirit.
![bad](https://cloud.githubusercontent.com/assets/13823154/19836020/5ef3c102-9e95-11e6-9750-6d45fede8d31.jpg)
![mac](https://cloud.githubusercontent.com/assets/13823154/19836021/64f42ad8-9e95-11e6-9fb0-cd7def95581b.jpg)

**Comment by Luth-RoR** [comment]
As i understand it, you think that the destruction cloaks should get corporal resistance instead of spirit because corp is generally more important than spirit for them. Though this is not how the bugtracker works; only real bugs are allowed here, no suggestions and requests.
