### ISSUE TITLE
Mourkain temple cannons

### ISSUE THREAD

**Issue by edavoc** [WarEmu/WarBugs#8211]
After the change to siege the cannons in the latest patch, the cannons now completely unbalance the scenario. 
One side can grab the artifact and bring it to their spawn forcing the other side to have to come to take it. Once the opposing side comes to get the artifact they get nailed my the siege weapons because they have to group together to kill the carrier.
 If the part is dropped it is almost impossible for the other side to retrieve it because the siege keeps knocking them back. 
The siege cannon can also reach outside portion of the temple so it makes it very difficult to avoid getting hit.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/2547

**Comment by Luth-RoR** [comment]
Imo the artifact carrier should simply be killed and the part reset if he runs too far into the spawn location.

**Comment by Ryanfawkez** [comment]
Could simply change the AoE cannons to ST cannons to reduce spawn obliteration. Unless a separate set of siege weapons for SCs with reduced range can be made, or somebody nerfs the range/damage again, that is.

**Comment by Kaelang** [comment]
This should have been classified as feedback as opposed to a bug. Closing.
