### ISSUE TITLE
[Guard] Guard Distance Unusual

### ISSUE THREAD

**Issue by CaptainoftheHarem** [WarEmu/WarBugs#8212]
I have been testing the range of guard, and have come up with the following data (using Enemy to give me the specific range). I tested this using a forlorn/fatelost soul in the Inevitable City, hitting a level 40/40+ zealot who I was guarding as a 40/28 chosen, names upon request. From 0-27 feet I took guard damage as normal, but beyond 28 feet I took no guard damage. The tool tip says that it has a 30 foot range, while the lastest patch notes say "Fixed some remaining incorrect AoE ranges. All fixed ranges have been reduced by 10 feet. Guard is affected in this patch." So either way it doesn't fit with what has been said. 
If this is working as intended please ignore this post.

**Comment by Luth-RoR** [comment]
Working as intended; the guard range was 40 feet before and now it's 30 feet (server side). Though i wouldn't count on that _enemy_ checks the range 100% correct.
