### ISSUE TITLE
Resources in orvr.

### ISSUE THREAD

**Issue by Bobbiom** [WarEmu/WarBugs#8213]
I stumbled upon a bug last night in TM where I could leave resources indefinitely at the flag inside the keep.

Not 100% sure how it happend but as far as I know, I took up the resource at the Headwall BO while making sure Headwall was secure with my party and then after awhile another resource appeared and someone in my group picked it up.
So the two of us headed back to the keep to drop them of at the flag.

The one who picked up the resource recently lost the indicator of having a resource while I didn't lose mine so I could stand by the flag and continue to click and the keep gained the points.

I lost the resource indicator after we defeated the keep lord.

**Comment by sioding** [comment]
Since you can´t carry any resources anymore i close this issue now. Thanks for the report.
