### ISSUE TITLE
charge/flee overwrite low wounds snare

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#8215]
as the title these skill sintead compensate with an increase of speed, totall overwrite the meccanic snare.
Moreover if you jump the overwrite end.

it didn't worked like this on live; the low wounds snare overwrite the base speed let's say of 100% with x% snare , this new base was used to calculare the 50% speed increase, which is not a raw 50% but half of the X%

currently melee fuck off and run away even if the low wounds snare get apply bypassing the low woudns limitation.

**Comment by Luth-RoR** [comment]
Known: https://github.com/WarEmu/WarBugs/issues/7650

**Comment by Tesq** [comment]
a correction flee dosen't do that only charge

**Comment by Luth-RoR** [comment]
For me, it works with flee too.
