### ISSUE TITLE
Terrifying Roar debuffs AA for 30% instead of 20%

### ISSUE THREAD

**Issue by lastadm** [WarEmu/WarBugs#8216]
Terrifying Roar (WLs Pet Ability, Reduces autoattack speed of all enemys within 30 feet by 20% for 10 second. Cooldown: 30sec)

Work like "by 30% for 10 second" not 20%

**Comment by Luth-RoR** [comment]
Could you post a screenshot with the values (evidence)?

**Comment by lastadm** [comment]
I dont save screenshots, but we test it with Viny and he check it with getstats.
