### ISSUE TITLE
Arkhan the Black abilities

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#8217]
Bloodcall says damaging.Applies on players but doesnt do any damage.
Not implemented or just not working(bugged)?
![warhammer online age of reckoning 10 30 2016 - 22 06 02 04](https://cloud.githubusercontent.com/assets/16864486/19839576/20ce4264-9eed-11e6-9210-62b7eb325167.png)

**Comment by Torquemadra** [comment]
not a bug
