### ISSUE TITLE
item appears wrong - Steelhelm of Dominion

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#8219]
This piece of gear for sale at merchant is listed as a 'white' with no stats.  All other 'Dominion' gear listed alongside it is 'Green' quality and with stats.  
item is gear for WL lvl 16

**Comment by Luth-RoR** [comment]
Not a bug; all dominion helms are like that and it was like that on the mythic server too.
The bugtracker is only for bugs.
