### ISSUE TITLE
Stalker kill quests do not progress inside of scenarios

### ISSUE THREAD

**Issue by Blaqwar** [WarEmu/WarBugs#8221]
Don't know if this is a known issue but figured I'd report it just in case. Since the last patch the Stalker kill quests requiring killing players of a certain career to advance them no longer count kills made in Scenarios.

I took a couple of screenshots (cause I know you guys like screenshots) but it's kinda difficult to capture before and after killing a player to show the quest hasn't advanced. Suffice it to say that there was 1 BW with 11 deaths and 3 KotBS players with 8 deaths combined in the scenario and my two remaining quests didn't advance.

Before:
![camael_007](https://cloud.githubusercontent.com/assets/5108812/19841417/ddc85440-9f0b-11e6-82a0-2a1907f9cb70.jpg)

After:
![camael_010](https://cloud.githubusercontent.com/assets/5108812/19841425/f671cd96-9f0b-11e6-86c2-a910c26729d0.jpg)

**Comment by wargrimnir** [comment]
It's correct in the DB, might need another full push to update correctly. If not I'll look into it further.

**Comment by sioding** [comment]
checked - looks fine - close
