### ISSUE TITLE
Warband Bug & Crash

### ISSUE THREAD

**Issue by Haojun-Phalanx** [WarEmu/WarBugs#8223]
* Hello all; https://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=17682&p=192633#p192633
After the 28/10/2016 patch, seems warband visual bug "mostly" fixed. as a warband player, warbands visually bugging when:

1-Inviting a player to warband who is not in the keep range. [ Location Related ]
2-Deaths and Ressurrection. [ i think it's location related also, probably server loses the players current coordinates when player dead-ressed. ]
3-In Combat Bug. [ Fixed ]
4-Being hit by siege weapons. [ Rare but sometimes happening ]
5-Swapping players in warband. [ Sometimes it crashes players also ]

To fix it:

1- Swapping players to other party.
2- Move away from keep range. [ Every player have to leave keep range ]
3- If a player got "in combat bug" ( you can see that in a safe place, check morales ) you need to kick that players from warband. [ Fixed already ]

* About  warband "invite" crashes: [ also Location related ]

1-To unbug it; crashed player should change his current zone [ the zone he crashed ].

**Comment by MaxHayman** [comment]
@sioding this is old right?

**Comment by sioding** [comment]
yes - close for this
