### ISSUE TITLE
Set Bonus Reset

### ISSUE THREAD

**Issue by Haojun-Phalanx** [WarEmu/WarBugs#8224]
Hello,
[ +1 path bonus ] resets when you change "any" item.
This happens only if you pick [Morale 4] on path.

![haojun_000](https://cloud.githubusercontent.com/assets/23129933/19849570/b1ed1454-9f5c-11e6-8436-6d02b14a23ee.jpg)

![haojun_001](https://cloud.githubusercontent.com/assets/23129933/19849573/b6675242-9f5c-11e6-8557-6e4d49b392fa.jpg)

**Comment by Yellowpillow** [comment]
#7024

**Comment by Luth-RoR** [comment]
Yes, known since the set bonus has been introduced.
