### ISSUE TITLE
Tier 2 Barak Varr - Ironclad BO - Bugged NPC's

### ISSUE THREAD

**Issue by Scrazna** [WarEmu/WarBugs#8225]
So for some reason I was in a group of 6 players yesterday attacking the Ironclad BO. When we reached the RP / Engi / Ironbreaker champion NPC's on the boat, they all became bugged.

Basically, they were targetable but not hittable (range or melee). As order were defending, we went inside the boat to reset the NPC's.

This didn't work as both ranged NPC's were sniping us through the boat itself and (eventually) Order managed to kill us because of the fact I, as a zealot, had too much ranged dps pressure from the NPC's. 

Is there any way this could be fixed so that they reset after a certain distance or that they follow us in to the boat itself. Alternatively, if they just became "hittable" again - this would be great!

Thanks,

Arlec

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
