### ISSUE TITLE
Neborhest's Vanguard - Dwarf Chapter 9 PQ

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#8229]
- [x] ~~There is one more PQ tracker when you are inside the area of this PQ but i dont know from which exact PQ.~~
**This has to do with PQ tracker persistence.** #6883
- [x] Also on Stage 2 and 3 Champions are linked(**With Azarael's system**)and Hero is linked with Champions in Stage 3.Its way too hard even for a group at the appropriate levels to do it...
![warhammer online age of reckoning 10 31 2016 - 19 00 30 05](https://cloud.githubusercontent.com/assets/16864486/19863597/737074dc-9f9d-11e6-9a27-d06207171adf.png)
![warhammer online age of reckoning 10 31 2016 - 19 05 52 06](https://cloud.githubusercontent.com/assets/16864486/19863661/b0422dec-9f9d-11e6-8c67-01d4242bae70.png)

**Comment by wargrimnir** [comment]
Spread out the champions and added more Engineers. Couldn't find any heal Kegs, so they're probably doomed.

**Comment by Luth-RoR** [comment]
😢

**Comment by Luth-RoR** [comment]
😢

**Comment by Soulwhisper** [comment]
**Is this for next patch?**
- [ ] Also noticed a duplicate.
![warhammer online age of reckoning 12 20 2016 - 18 41 46 03](https://cloud.githubusercontent.com/assets/16864486/21359195/1786e39a-c6e4-11e6-8223-f8c4133ed09c.png)

**Comment by wargrimnir** [comment]
Yes, it's for next patch. It will be in the patch notes.

**Comment by Soulwhisper** [comment]
- In last stage if Hero gets killed by NPCs she wont respawn so you cant finish PQ.I guess that respawn timers for Heroes need to be manually changed for each PQ.
![warhammer online age of reckoning 12 25 2016 - 12 06 09 03](https://cloud.githubusercontent.com/assets/16864486/21470649/8d68c916-ca9a-11e6-9299-90cfe3ac7722.png)
