### ISSUE TITLE
The Tower of Neborhest - Dwarf Chapter 9 Public Quest

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#8230]
- [x] There is no Public Quest Tracker inside the PQ.
(**Nor influence bar with the Chapter nowhere around the area of the PQ.**)

P.s.Im providing you the influence bar issue too because its not major but looks like for some specific areas.(**_For example in green area it appears normally but in black doesnt._**) 
![warhammer online age of reckoning 10 31 2016 - 19 24 23 08](https://cloud.githubusercontent.com/assets/16864486/19864547/61347148-9fa1-11e6-8c83-d9063535763f.png)

**Comment by wargrimnir** [comment]
This is an issue with the mapping, Saupresse should be working on it.

**Comment by wargrimnir** [comment]
This was fixed in the last patch.
