### ISSUE TITLE
Dwarf Chapter 8 wrong respawn

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#8231]
- [ ] Dying in black area spawns you in Chapter 9 instead of 8.
![warhammer online age of reckoning 10 31 2016 - 19 48 00 09](https://cloud.githubusercontent.com/assets/16864486/19870890/44e2c926-9fbb-11e6-973f-e68a9e8fc128.png)

**Most likely it has something to do with the closest healer thing and needs to be changed manually.
Our great Developer @saupreusse  knows about this i think :P.**

**Comment by sioding** [comment]
fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 14.04.2018
