### ISSUE TITLE
Blood of the Black Cairn scenario isn't working as intended

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#8234]
after taking 2 ours and 1 central flags i take one of enemy's flags and then nearest to our wc flags reset.
![arena_126](https://cloud.githubusercontent.com/assets/18102127/19870534/67e55cae-9fca-11e6-9f21-158766153983.jpg)
After enemy capture 4 flags i wasn't be able to recapture nearest to our wc flag, but in the same time (one of the nearest to our wc flags was captured and another was neutral) central could be captured (progress bar moved)
![arena_127](https://cloud.githubusercontent.com/assets/18102127/19870634/d4553300-9fca-11e6-8bf9-84cf8c7047b3.jpg)
My guess is the game mixed up central flag with others, when central flag should be reset - game resets nearest to wc flags, and same with capturing.

**Comment by Natherul** [comment]
should be fixed as of today
