### ISSUE TITLE
[Knight of the Blazing Sun] Morale 3 "No escape"; root component has the wrong duration

### ISSUE THREAD

**Issue by Luth6409** [WarEmu/WarBugs#8237]
The AE-root of knights M3 "No escape" was changed to 5 seconds duration in patch 1.3.2:

_No Escape: This Morale ability is now available at Rank 36 and is now a Rank 3 Morale ability. The ability's damage has been increased, and the duration of the root has been reduced._

https://web.archive.org/web/20131227093328/http://www.warhammeronline.com/article/Game-Update-132-1015

_...and at M3 No Escape which deals 1360 damage to all enemies within 30 feet of the character and roots them for 5 seconds..._

https://ekaslime.wordpress.com/2011/04/11/mirror-war-kotbs-v-chosen

**Comment by Luth-RoR** [comment]
Hint: the blog says 1360 damage instead of 1200 high likely because of RR80+ "hidden levels", so the damage component works correctly.

**Comment by Londo001** [comment]
Blog is wrong. Here is actual damage values read from client's  ability database (Where tooltips pull their values from). It might have been that Mythic updated values in 1.4.6

36=1092
37=1120
38=1144
39=1172
40=1200
41=1224
42=1252
43=1280
44=1304
45=1332

**Comment by Luth-RoR** [comment]
Iirc with the release of 1.4.0 the maximum hidden rank on level 100 was level 60, one per renown rank; they changed it later to maximum 45.

**Comment by lilimx** [comment]
This was fixed a while ago.
If the issue still persist, we can reopen the ticket.
