### ISSUE TITLE
WL Pet abilities while being KD

### ISSUE THREAD

**Issue by korhill** [WarEmu/WarBugs#8239]
Hello,

after last Patch 31/10/16 my WL cant use any abilitites (frenzy, brutal pounce, silence skill, disrupt skill) while being Knocked down. I am not sure how it was on live but before this patch it was possible. If it was an mistake please make it undone.

Thank you!
----------------------------------------------------------------------------------------------------------------
That the good damage is dependent on pet was always a disadvantage for the WL. Positiv was (when pet is alive) that you atleast could use also KD, silence, disrupt or frenzy when you get Knocked down. Was good in 6v6 or any WB since you had also in this case an advantage having skills on pet since you still could silence or KD someone with pet while being KD. Now with this update/mistake we lost this advantage.

**Comment by Luth-RoR** [comment]
>I am not sure how it was on live

Then you should ask in advice chat first and/or gather additional info before you open a report (see: bugtracker rules).
This was obviously a fix and is no bug. 
Please read the tooltips: they say "You command..."; i wonder how one commands his pet when he is knocked down. Before the next report is opened: i didn't test it but i guess when the player is silenced he can't use pet abilities too (as with detaunts).

**Comment by korhill** [comment]
Thanks for the answer Luth. Than ill do a post on the balance section. I do understand that you cant give commands while being silenced.
But being Knocked Down you should still be able to talk and give commands.The pet is the WL best friend and should not watch and wait, once you are in trouble.

Thank you
