### ISSUE TITLE
[Archmage\Shaman] AOE Detaunt duration bug

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#824]
AOE detaunt duration now 5 sec (like self buff) instead of 10 sec on live.

**Comment by noisestorm** [comment]
AM aoe detaunt was always 5 seconds and you can even read that in the skills tooltip.
Show sources of 'obvious' changes.

**Comment by Silentguard** [comment]
Always 5 seconds was only buff that gives you immune to setback while casting. Detaunt was 60 sec cooldown, 5 sec duration till 1.2.0 patch.
http://warhammeronline.wikia.com/wiki/Game_Update_1.2.0/Combat_and_Careers/Archmage

**Comment by ozarmidrashim** [comment]
Good enough for me. Added.

**Comment by ozarmidrashim** [comment]
Personally verified as working.
