### ISSUE TITLE
Shackle not working

### ISSUE THREAD

**Issue by RevMalthus** [WarEmu/WarBugs#8243]
KOTBS ability- Shackle not working

Shackle isnt working- there is no root, although the visual graphics are in tact, and the cool down is still in tact... just the root effect isnt working at all, for any amount of targets

feel free to message me in game

 - Rochambeaux

**Comment by RevMalthus** [comment]
i should clarify - it works in PvE, but does not work against other players in PVP 

ran into a crowd to test w/o damaging anyone, did not root players

**Comment by Haojun-Phalanx** [comment]
Did you check immunities ?

**Comment by Kaelang** [comment]
No confirmation was provided. I am now going to close this issue.
