### ISSUE TITLE
renown respecialization

### ISSUE THREAD

**Issue by calsidar** [WarEmu/WarBugs#8244]
Hi 
I am trying to respecialize in renown 
I cant do it through the Anywheretrainer (works if am near a trainer in temple)
When i go to a trainer i get back my points but i always see a "spent 10" . tried to restart but i got no results

**Comment by Luth-RoR** [comment]
How many points can you assign? What's your renown rank?

**Comment by D4W0lf** [comment]
Hej!
Same things for me. I'm RR46 and when I get back my point, I always see the same amount as "spent".
Don't know if it's an Anywheretrainer effect or not.
But not sure cause I'm not at home but If I restart the game it's well displayed for me (0 as psent and xx as usable)...
