### ISSUE TITLE
Rested bug.  

### ISSUE THREAD

**Issue by Ripliel** [WarEmu/WarBugs#8246]
Sorry If it is a known issue, haven't found it by search. 
While you are not in game and your character is in guild tavern/Viper pit it doesn't grant you higher speed of gaining rested (as it must do according to official servers). 
Maybe it isn't a bug and I missed something in old patchnotes.

**Comment by Luth-RoR** [comment]
Iirc only the officer hall gave you increased rested bonus, in the rest of the tavern it was like altdorf; could be wrong though.
