### ISSUE TITLE
Stonetroll Crossing: Being able to cap a point after time ran out

### ISSUE THREAD

**Issue by Zumos** [WarEmu/WarBugs#8247]
I don't have any proof because I wasn't recording, but after the timer ran out, someone was still able to cap a point in the scenario. It looked like he was able to interract with the point after the timer ran out, but it could have been that he started interracting just before it ran out and that way was able to cap even though the flag had been dropped.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
