### ISSUE TITLE
Bugged stats on item: Spatterguards of the depraved

### ISSUE THREAD

**Issue by Thatsmybanana** [WarEmu/WarBugs#8248]
Insignificant, but noticed this item as only having armour values on it as a blue item.

![banaknight_002](https://cloud.githubusercontent.com/assets/23216277/19932901/93c301ba-a109-11e6-8eae-b7570207eb03.jpg)

**Comment by wargrimnir** [comment]
Corrected stats on all Order and Destro "of the Depraved" armor. These are found at both R15 and R23. ~240 items total.
