### ISSUE TITLE
Serious crashing

### ISSUE THREAD

**Issue by Svatyr** [WarEmu/WarBugs#8251]
Everytime I join a warband in tier 2 I crash. I cant figure out what the issue is but alot of other people are having it too.

**Comment by Soulwhisper** [comment]
Change Tier/Map then try to join.

**Comment by Svatyr** [comment]
I did, I was in the city then I tried in the zone and it still did not work. It eventually stopped but thats about all that happened.

**Comment by Luth-RoR** [comment]
A known issue, afaik somehow related to guild membership; unfortunately what causes this is still unknown.
