### ISSUE TITLE
Lions and Squigs disappearing?

### ISSUE THREAD

**Issue by Svatyr** [WarEmu/WarBugs#8253]
When we cross say from ostland to troll country our pets disappear, they also randomly will vanish when in RvR/PvE lakes. Kinda hurts us when one of our main sources of dps completely vanish and have to be de-spawned and re spawn with their cool-down acting like they died.

**Comment by Luth-RoR** [comment]
That's known; devs are at it to prevent this.

**Comment by Svatyr** [comment]
Alright thank you 

    On Thursday, November 3, 2016 2:11 AM, Luth <notifications@github.com> wrote:
 

 That's known; devs are at it to prevent this.—
