### ISSUE TITLE
Illuminations of Ruin - BW Shoulders

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#8256]
Shouldnt have weapon skill.
![1234](https://cloud.githubusercontent.com/assets/16864486/19973951/77a2c998-a1ef-11e6-9a0b-a5739abca2d1.png)

**Comment by Luth-RoR** [comment]
Yes makes no sense on the class, though the ruin stats have the original stats from the mythic server and it has been stated by the devs (geni) that they won't be changed. https://github.com/WarEmu/WarBugs/issues/8181
