### ISSUE TITLE
Quitter! Debuff

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#8257]
It applies to other characters too.
Pressed no with my BW.
Logged in with my WP and i had it on me.

**Comment by Blaqwar** [comment]
I was under the impression that this was intentional?

**Comment by Soulwhisper** [comment]
Splitting to other characters too? Why? Whats the point?

**Comment by Luth-RoR** [comment]
Indeed working as intended.

**Comment by Soulwhisper** [comment]
@Luth-RoR Cool so its an "account" debuff/punishment :)
@Blaqwar You were right.
