### ISSUE TITLE
[Witch Elf] Kiss buff issues

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#826]
Proc from kisses does not have any retrigger time so it can proc 3 times per gcd. Especially deals huge damage while channeling Ruthless Assault (3-5 procs). Tested on Kiss of Agony. All buffs and tacs with onHit proc on live had 1 sec retrigger time.
Also proc chance by test was 41% instead of 25%. Could be bug.

**Comment by ozarmidrashim** [comment]
Of the testers I've spoken to, all disagree with your report. Could you please corroborate this?

**Comment by Silentguard** [comment]
Which part of this?

**Comment by ozarmidrashim** [comment]
The 1 second retrigger time.

**Comment by Silentguard** [comment]
Im not sure about exact value but it should be between 1 and 1.5 sec. I did tests on live of WE and WH self buff mechanics. WH Blessed bullets proc ONCE for first target from Dragon Gun and TWICE from Trial by Pain on first shot and last shot in channeling. WE have almost same mechanic, could proc once or none from On Your Knees and 0-2 from Ruthless Assault.

I dont know was it from release or be nerfed in patch like Riposte that was nerfed from CAN_CRIT = true and retriggerTime = 0 to CAN_CRIT = false and retriggerTime = 1 after huge pain about WH Repel and Riposte mechanics.

Need to check patch notes. I tought it obvious. No retrigger time means WE have almost uncleanseable heal debuff, can kill kiter by dagger throws and deal equal damage or even more than Ruthless Assault deals in low tiers.

**Comment by Silentguard** [comment]
Ok, I find nice WE duels video for you. Frames are big enough and you can see how often this proc trigger. In whole video ive seen couple of times when kiss reproc from 4th second. So i think its 1 sec retrigger time, not 1.5

https://youtu.be/EUSOj09ALAE
