### ISSUE TITLE
Bugman's Best and Morale Gain

### ISSUE THREAD

**Issue by Morulan** [WarEmu/WarBugs#8260]
I noticed today, than when I kept creating Bugman's Best every time it got off CD, it semi-put me in combat: I was gaining morale, but if I remember correctly, I was still able to change my tactics(I might misremember this part, though). When I stopped casting it for 20 seconds, my morale started dropping just like it should out of combat, but when I dropped the keg once again, it halted the morale loss, and it started going up again(There were completely no enemies in sight during this, I was at the hill at Pelgorath's Ember in Dragonwake)

**Comment by Luth-RoR** [comment]
I just tested this in DW at the BO and near it, as well as in different locations. It didn't work for me.

**Comment by Morulan** [comment]
Hm. I'll try that again tommorow then, when I get back home. Maybe it was just a strange coincidence
