### ISSUE TITLE
Oil oneshotting t4 ram

### ISSUE THREAD

**Issue by Nefarian11** [WarEmu/WarBugs#8262]
a Heavy Chaos Ram got oneshotted by a SINGLE Oil dump (Dragonwake "Covenant of Flame" keep).

don't have any screenshot or combat logs, but there's 10+ witnesses.

This happened just after 03/11/16 patch

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/8261
