### ISSUE TITLE
Auction House mail

### ISSUE THREAD

**Issue by Brutalassault** [WarEmu/WarBugs#8263]
When i opened the mailbox to receive the gold payment from Auction House and tried to close the mail, it poped up again. And when i tried again to close the window and didnt stopped to pop up on my screen. When i moved away from the mailbox it stopped but the mailbox notification from my radar it is not dissdapeared and the notification is still there. 

Thanks for reading my bug report

**Comment by Luth-RoR** [comment]
Hi,
that's a very old bug that exists for as long the mail system exists on RoR.

**Comment by Brutalassault** [comment]
ok i see, well thanks for the reply, but it is removed from my
notifications when i relogged :)

2016-11-04 10:58 GMT+02:00 Luth <notifications@github.com>:

**Comment by Natherul** [comment]
Should have been fixed with the patch from yesterday
