### ISSUE TITLE
Engineer Tactic: Extra Powder Doesn't Increase Range of Fragmentation Grenade.

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#8265]
Engineer Tactic: Extra Powder Doesnt Increase Range of Fragmentation grenade.

The Tactic should increase Acid Bomb and Fragmentation Grenade.
I testet it on severl npc wild pigs.

Without tactic Acid Bomb and Frag are equal.
After Tactic activation Acid bobms also hits pigs hich are farhter away.
BUT Frag Grenade still has original range and doesnt give dot to farhter away npcs.

I have tested it with two pigs. Hitting Pig A and Pig B.
If I hit either Pig A or Pig with a acid bomb the other Pig gets the Dot.

If I hit Pig A or Pig B with Frag Grenade the other Pig doesnt get a dot.
On one occasion the other Pig got the Dot in its Health bar.
But it doesnt get any damage from it, and after 3 second the Frag Dot dissapeared without any effect.

**Comment by LestiArdisson** [comment]
As of current state: 08.12.2016 the tactic is still broken on frag grenade with a retest on 7.12 before patch on 7.12.
With hinsight of the changes on the Engie Turrets it would be really nice to have the increased range on the Frag grenade.

**Comment by LestiArdisson** [comment]
Additional Information:
Made a retest on 12.02.2017
Bug is active.

**Comment by Torquemadra** [comment]
please confirm this is still an issue

**Comment by LestiArdisson** [comment]
Retestet in Elf starter Area on 16.05.2017

Bug still persists.

![lesti_031](https://cloud.githubusercontent.com/assets/14627932/26091896/5a2e058c-3a0e-11e7-9cc0-db4da6fe994a.jpg)

If I hit these three elves, starting with the most left...

Without Extra Powder I hit 2 with Acid Bomb and 2 with Frag Grenade.

WITH Extra Powder I hit 3 with Acid Bomb but only 2 with Frag Grenade.
