### ISSUE TITLE
Ram deployed at enemy keep gets bugged when trying to tow away

### ISSUE THREAD

**Issue by stprime** [WarEmu/WarBugs#8267]
Was playing in T2 and attacking the Cascade of Thunders. Spawned a ram and hauled it to Order's keep. I realized that I didn't position it correctly because it wasn't dealing any damage, so I got up on my mount, right-clicked the ram to tow it away and at that moment the ram became frozen. 

Right-clicking it again prompted the chat message "You cannont deploy a siege weapon while it is being towed". The same message about towing was confirmed by other people in the warband. The ram became useless and we eventually lost it to damage.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
