### ISSUE TITLE
Swapping Weapons while using +1 Mastery Set Bonus

### ISSUE THREAD

**Issue by Zoggof** [WarEmu/WarBugs#8270]
If you swap weapons while utilizing a set bonus (for example: Black Orc Mercenary (4) +1 to Da' Brawler Abilities) the game will think you are swapping armor sets and you will lose the +1 to the mastery abilities. 

This will then require you to visit the career trainer and respec your mastery tree every time you swap weapons.

**Comment by Luth-RoR** [comment]
That's a known problem and can't be fixed yet; you can download the addon "anywhere trainer" to assign the mastery point again wherever you are after that happened.
