### ISSUE TITLE
[Chosen] Tzeentch's Reflection bugs a lot

### ISSUE THREAD

**Issue by gke96** [WarEmu/WarBugs#8271]
This happens quite often (Like %20-30 of the time i use it in a fight)  It either doesnt enter cooldown visually and uses the skill, or doesn't use the skill at all.

 Using TR to cancel another channeling-cast time ability makes it work (like using it while HTL on or using it while mounting up) but I have to cast it like this most of the time and this changes my gameplay slightly.

**Comment by Luth-RoR** [comment]
I just tested this for about 10 minutes while ~ 15 mobs attacked me and it worked perfect. Are you sure it's only this ability? I guess this could maybe come from server-client lag.

**Comment by gke96** [comment]
Hmm I should record a video of it in RvR I think. Yes its only this ability

**Comment by gke96** [comment]
"I guess this could maybe come from server-client lag."
It maybe related since it probably only happens in RvR-SC, but it is still only this ability. No such problems with similiar abilities such as "Bane Shield" for example..
