### ISSUE TITLE
Loryndaal easy PQ grants normal instead of basic rewards

### ISSUE THREAD

**Issue by Bubiger** [WarEmu/WarBugs#8272]

**Comment by Soulwhisper** [comment]
Confirmed
![warhammer online age of reckoning 11 05 2016 - 15 08 58 12](https://cloud.githubusercontent.com/assets/16864486/20030250/e7b28f68-a369-11e6-8ee2-c09a7a790673.png)

**Comment by Luth-RoR** [comment]
Ok, i read it like "normal" and "basic" should be the bag rarities (green and white) and not quest difficulties, what made me wonder how this was tested.
Next time please add evidence according to the bugtracker rules.

**Comment by Soulwhisper** [comment]
@Luth-RoR Torquemadra can fix this?

**Comment by Torquemadra** [comment]
what did i say in 7903? not a bug

**Comment by Soulwhisper** [comment]
Oh that you trying things on PQs.
Sorry didnt get it.
