### ISSUE TITLE
Shadow Warrior's bolster war engine broken

### ISSUE THREAD

**Issue by RevMalthus** [WarEmu/WarBugs#8274]
When attempting to use the Bolster War Engine skill in T3 keep raid I get the message "14406 Bolster War Engine has no implementation" 

Just reporting in case it is supposed to be implemented

Best,
Rochambeau SW / Rochambeaux KOTBS

**Comment by Luth-RoR** [comment]
Hi,
the abilities that are not implemented yet are all known; the bugtracker should be only used for content that is implemented, but still buggy. Thanks.
