### ISSUE TITLE
Igor Brunwolf failure to respawn

### ISSUE THREAD

**Issue by RevMalthus** [WarEmu/WarBugs#8275]
Doing quest for Stalker armor "Chosen Poorly" - the mob you are supposed to kill is Igor Brunwolf, at approx 35k, 35k in Highpass. For some reason when I was trying to kill him, the wolves around him attacked him (aggro wolves generally attack me) 

regardless, I was kiting Igor and the wolves killed him. After the aggroed me, I died, and ran back to try to kill him again. Unfortunately, I found that he has not respawned. I'm assuming this has something to do with the wolves killing him. 

Feel free to contact me in game,
Rochambeau/Rochambeaux

**Comment by RevMalthus** [comment]
![rochambeau_002](https://cloud.githubusercontent.com/assets/4071605/20035241/a2622c18-a399-11e6-9b5d-60005f2ed79c.jpg)

additionally, his corpse isnt decaying, and when I click him it indicates that he is an "easy" target

- Rochambeau

**Comment by RevMalthus** [comment]
he just repopped.

**Comment by Luth-RoR** [comment]
Champ and hero respawns take longer than normal mobs. NPCs can be hostile to each other, e.g. empire vs chaos soldiers, or humans vs beasts.
