### ISSUE TITLE
Battlefield Verses Quest

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#8279]
- [ ] There is no questmarker.
**(Yes i clicked on Mark on map and i had selected only this from all the quests i got.)**
- [ ] There is no option to complete this quest on the NPC as you can see on Picture.
**Tried with my T2 character but there is no option to take this quest.Looks like is removed.
Intended or not though?**
![warhammer online age of reckoning 11 06 2016 - 16 16 13 01](https://cloud.githubusercontent.com/assets/16864486/20038430/62a16c44-a43c-11e6-8b81-5cc2fe4490a3.png)

**Comment by Ryanfawkez** [comment]
Yup, disabled.
