### ISSUE TITLE
The Shame of War! Quest

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#8280]
- [ ] Has no questmarker where to complete this Quest.
**_You have to speak with Kag Malosson NPC in TM just a little further down of WC._**

**Comment by Ryanfawkez** [comment]
None of the 150 T4 killquests have a hand-in marker.

**Comment by Soulwhisper** [comment]
@Ryanfawkez So they will be handled in the future? 
No need to report these? Many of them dont write in quest-lines where to report.So you have to search all Warcamps to find the right one.

**Comment by sioding** [comment]
Checked - Killsquest has hand-in Marker
