### ISSUE TITLE
Ulfred Quest - Can't get the reward

### ISSUE THREAD

**Issue by Ephreat** [WarEmu/WarBugs#8281]
Hello,

I took the quest _Murder Wood (Order - Nordland - Tier 1)_ given by _Ulfred_ and he didn't give the rewards.

After completing objectives, I returned the quest to him to get the reward (cf. below) 
![ulfred_bug](https://cloud.githubusercontent.com/assets/9019713/20039829/87cdddcc-a44b-11e6-9b16-4f2efa5bc874.jpg)
 : 
 - I right-clicked on him,
 - I selected _Murder Wood_ quest,
 - I choosed one of the two rewards (_Initiate Fleeting Corporeal Screen Potion_ or _Heavy Bronze Hammer_), (The results are the same whichever the reward selected)
 - I clicked on Complete.

Results : 
 - The quest remains active (as if I didn't returned it)
 - I don't get my XP reward nor my selected reward.

**Comment by sioding** [comment]
checked - everything is fine - close
