### ISSUE TITLE
RvR lake buffs stuck on

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#8282]
Hello,

I encountered an issue where the RvR lake buffs(Against all odds and Fields of Glory) remained on after leaving the RvR lakes. I played a few scenarios and seemed to be getting significantly more RP/XP than other players so I am sure it is not just a display bug.

Logging out resolved the issue.

I can give more details on exactly what I did leading up to the issue, but don't want to post the details publically.

Thanks!

**Comment by Soulwhisper** [comment]
Tried to do a /rel when you are out of the RvR lake?

**Comment by Luth-RoR** [comment]
>I can give more details on exactly what I did leading up to the issue, but don't want to post the details publically.

You can PM me on the forum; username is _Luth_

**Comment by sioding** [comment]
No answer since 09.11.2016 - close for now.
