### ISSUE TITLE
unable to see item/abilitie names and stats 

### ISSUE THREAD

**Issue by normanis** [WarEmu/WarBugs#8287]
hello i recently received some weird error or bug. i can see item/abilitie names or stats. byt i can see only ather pleyers when i put my mouse on tham as u can see in pictures i have mouse on item byt i cant see stats of item. 1 is with addons and second is without. is it my client bugged? 
![raganina_001](https://cloud.githubusercontent.com/assets/23311386/20055724/3f4a461c-a4eb-11e6-9c6c-0fa2629d0683.jpg)
![raganina_000](https://cloud.githubusercontent.com/assets/23311386/20055725/3f5aa822-a4eb-11e6-98c0-01ee1a3aa887.jpg)

**Comment by Luth-RoR** [comment]
Activate "show tooltips" in the settings. This is completely handled client side.

**Comment by normanis** [comment]
thx its worked, byt i never was make it off. its somehow happen when i flied to capital city. byt thx
