### ISSUE TITLE
Ram Issue

### ISSUE THREAD

**Issue by tootin** [WarEmu/WarBugs#8288]
Spawned a ram in T2 as Destro at Fangbreaka due to it not letting other members a guild issue even though that was changed. Another member of the warband grabbed it as I spawned it and then tried going through the cave to Dok Karaz. When he did so the ram went flying on the map and now can not spawn another due to Your supply lines cannot support any more rams. Ram is not visible any more so not sure if it was caused by maybe he didnt have a guild, the cave it self when moving zones, or if it needs to be carried by the person who spawns it.

**Comment by tootin** [comment]
Found where the ram went to but it will now not let anyone interact with it.

**Comment by tootin** [comment]
Okay so to add on to the tier 2 errors, after a server update the ram did despawn so were able to spawn one. Then after we took the keep no supplies for the keeps in the other zones started spawning

**Comment by Sheevar** [comment]
Dunno if i have to report it in this thread but: In TC, i tried towing the ram from our keep to the enemy one. Every time we go into the other half of the map, the ram start move without anyone towing it and selfdestroy

**Comment by sioding** [comment]
Since we have totally changes the open rvr campaign i  will close this now. Thanks for the report.
