### ISSUE TITLE
Boar Hooves

### ISSUE THREAD

**Issue by Malvius** [WarEmu/WarBugs#8289]
Killing any kind of boar now drops a Boar Hoof for me (quest item, bind on pickup, ID 129 838 679). Order side, haven't tested destro side.

I am not the only one with this problem, and we suspect the culprit to be the Halloween event quest for the skeleton potion, since my friends who completed that quest have the same problem now, but the rest of them don't. I think I did the T2 version of it, I know one person did the T1 version of it, I don't know if the T3 and T4 versions cause this as well or if it's the same quest anyway, available at different NPCs.

It might not seem like an issue, but if you're killing larger numbers of them, you not only have to spam click to accept the dialoge about the bind on pickup item which pops up every time, but they also fill up your quest inventory and once that is full they fill up your main inventory. You end up spending half the time looting and deleting them again.. fun times :D

**Comment by Luth-RoR** [comment]
Loot tables don't work quest related; NPCs either drop something or they don't drop it and this is only temporary anyways (until the event runs).

**Comment by Malvius** [comment]
But quest items only drop for you if you have the quest related to them, right? And these did not drop until the quest was accepted and have not stopped dropping after completing it.

**Comment by Luth-RoR** [comment]
The items have been high likely added to the droplist on the same patch as the halloween event went live. So that you took the quest right after the start and it only looks like that.
All items simply drop from the NPCs droptable with a cartein chance afaik.

**Comment by Malvius** [comment]
There are definitely items that cannot drop unless you have the quest associated with them. an example would be the items needed for the tome unlock of the Oathstone of Karak Eight Peaks (https://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=13566). I have tried to get those drops before having the quest since i was in the area and they do not drop until you have the quest.
Furthermore, as I stated above, the items in question here are in fact labeled as quest items and go in your quest item bag and I have never gotten such an item anywhere unless I had the quest for it.

Just tested it again:
Character that never touched the quest: no drops whatsoever
Character that has accepted but not yet completed the quest: drop on every kill
Character that has accepted then abandoned the quest: no drops whatsoever
Character that has completed the quest: drop on every kill

**Comment by Luth-RoR** [comment]
I see, maybe there was a DB change with new features; trying to get info.

**Comment by Luth-RoR** [comment]
Ok, this is supported now, apologies and they should indeed stop to drop after the quest is finished.

**Comment by Malvius** [comment]
No worries, and thanks.

**Comment by Paleolog77** [comment]
![4](https://cloud.githubusercontent.com/assets/23325288/21093028/b5b3892c-c060-11e6-8d71-3ce356a258b0.jpg)

**Comment by wargrimnir** [comment]
Set drop chance to 0 for these quests. That should do the trick.
