### ISSUE TITLE
Channeling abilities interrupt issue

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#829]
Any ability starts and drops cast when you press it while GCD duration. Unlike any others channeling abilities set to CD after this. Seems like client trying to send ability press to que on server and interrupts it when dont get respond.

**Comment by Zealote** [comment]
Not sure if closing implies that it's fixed but just in case, this bug was still occurring as of about an hour ago. Seemed less common but tht could've just been cos I was being more careful waiting for gcd to be up.
