### ISSUE TITLE
Crafting Inventory Bug

### ISSUE THREAD

**Issue by Esperflame** [WarEmu/WarBugs#8290]
I have no idea how this bug is happening but it only seems to be popping up on the first char I made back in August, Braerithryn my Blackguard. (He seems to be getting most of the bugs.)

So when I'm running around playing and I was collecting stuff via scavenging, I started to notice my game performance took a huge hit. I found out the cause of this problem had to do with my crafting bags. What normally should happen is when you collect crafting materials if it's a new item or the previous stack is full, it's supposed to take the next available empty slot. For some reason though, my bag seems to toss everything in random empty slots until it finally bugs out and starts to stack multiple crafting materials into a single slot. I also noticed that most of the time my items were invisible in my bag. Once it starts stacking items into the same slot that slot starts to cycle through all the crap thats in that one slot and my framerate even when the bag isn't open takes a dive and I notice a ton of hitching and stuttering in my FPS.

I have tried to fix this by selling everything in my crafting bag and even by respecing my collection skill to get rid of the bags. When I sell everything it fixes it for a very short while but evenetually does the same thing. When I reset my collecting skill it failed to get rid of the extra bags I earned as well so now I have a lvl 37 BG who can never do anything with his crafting bags or else it bugs out badly.

Edit - I also wanted to note this problem didn't seem to start til sometime after the halloween stuff started.

**Comment by Luth-RoR** [comment]
A known bug of unknown origin: https://github.com/WarEmu/WarBugs/issues/8032; happens also only to some chars/accounts.
