### ISSUE TITLE
Can lock a zone with no suplly line

### ISSUE THREAD

**Issue by Tholkienn** [WarEmu/WarBugs#8293]
If you manage to bring a ram from the zone you lock, to the next zone, and if the supply line go to another tier, ram still work on a zone without supply.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
