### ISSUE TITLE
The are 2 NPC Deridian Gor

### ISSUE THREAD

**Issue by gschouweiler** [WarEmu/WarBugs#8295]
At Ellyryon, there are 2 Deridian Gor character. One works for quest and another (under tent) not work.

![double npc](https://cloud.githubusercontent.com/assets/22920863/20094049/d9b38d58-a59f-11e6-8573-23854e36fbf4.PNG)

![localisation](https://cloud.githubusercontent.com/assets/22920863/20094057/e098b260-a59f-11e6-8218-89e04a1de716.PNG)

**Comment by Natherul** [comment]
fixed

**Comment by Luth-RoR** [comment]
Thanks.
