### ISSUE TITLE
Occupation

### ISSUE THREAD

**Issue by hibl** [WarEmu/WarBugs#8296]
Hey there, im not sure if it is a bug, but i hope u can fix that anyway.

I was on Skill 200 apothecary. For some reason i missclicked the talisman trainer one time. Now i was a lvl 1 Talisman builder. I know it was prob. my own dumb, but a single question like "are u sure u want respec" or something would be nice.

ty very much

P.S. is there any way to get my 200 apotecary  back? :) Account name hibl, char ladybboy

**Comment by Luth-RoR** [comment]
Hi, this can't be solved via the bugtracker. You can try it on the support forum but i don't think the rank can be restored. 
Something like that was also posted already earlier: https://github.com/WarEmu/WarBugs/issues/8107
