### ISSUE TITLE
RvR tracker

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#8298]
- [ ] Not triggering only in Nordland RvR lake.
**_Londo is the man for this._**

**Comment by Luth-RoR** [comment]
>Londo is the man for this.

**Comment by Soulwhisper** [comment]
If you mean that he knows it...then close it if you want :)

**Comment by Luth-RoR** [comment]
I mean it's known from the patchnotes, though he can't be assigned on bugs.
