### ISSUE TITLE
[Engi] M3 Cannon Smash does NOT stack with Range increase.

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#8299]
CANNON SMASH DOES NOT stack with Range increase.
Tooltips said before current Patch that it has a Range of 140 ft with full Buff.
Today it says 125 ft with full Buff.
But its working Range is still 100 ft.

If you fire it at an 125 ft Target the Animation of it starts but no Damage gets dealed to the target.
If have hit the Moral Button 4 times and made a video of it. Animation starts, but no damage.

Test Enviroment:
I have selected an NPC Wild Boar.
Gunblast was red, out of Range. Meaning target is > 100ft.
Then setting up Turret. With x8 Buff the Target became white for Gunblast. Meaning Target is between 120 and 125ft.

So I can hit the target all the time with my Gunblast. While Cannon Smash who was also activated then says it can also be fired at 125 ft. But it didnt dealt damage to the Wild Boar.

Summary:
NO Destro ever was hit by a Cannon Smash past 100 ft.
So Cannon smash is still like on AoR.

**Comment by Yellowpillow** [comment]
i don't think morales should be affected by any of buffs/debuffs. I think it visual interface bug.

**Comment by Torquemadra** [comment]
Morales gain nothing from buffs and will remain this way.
