### ISSUE TITLE
WH stealthing with part in Phoenix Gate scenario

### ISSUE THREAD

**Issue by Zumos** [WarEmu/WarBugs#8300]
In the screenshots which are 2 seconds apart you can see our flag carrier on the screen but not the enemy flag carrier. Then the enemy flag carrier managed to cap the point in the middle while stealthed. 

![zumuss_013](https://cloud.githubusercontent.com/assets/19267650/20115222/bc2909d6-a5f7-11e6-9a6f-de49c19cc73e.jpg)
![zumuss_014](https://cloud.githubusercontent.com/assets/19267650/20115223/bc293f1e-a5f7-11e6-8ab6-07e0768877f9.jpg)

**Comment by Torquemadra** [comment]
known issue

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/7974
