### ISSUE TITLE
gun turret bug (level 1) since last patch

### ISSUE THREAD

**Issue by peusnaugrim** [WarEmu/WarBugs#8302]
since last patch the gun turret are level 1 whoever the level you have
so at level 40 you have a turret level 1 mean debuff armor only 24... and damage are level 1 gun turret  also
In fact all turret are level 1 flame turret and artillery turret...

**Comment by Luth-RoR** [comment]
On the live server my level 32 engi has level 32 turrets, whose debuffs debuff for level 32 values (checked with .getstats) and who damage for level 32 values (checked with combatlog). 
I don't know what you _tested_, but i guess you just saw the abilities on the pet ability bar that show level 1, which is a know _visual-only_ issue. 
Next time please tests something and post evidece, according to the bugtracker rules.
