### ISSUE TITLE
Renown gain seems fishy

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#8305]
So I was just running around solo in Chaos Wastes. And was quite happy about the amount of renown I was getting. 
![cimbina_011](https://cloud.githubusercontent.com/assets/16117730/20152232/b4d1e466-a6bd-11e6-89a6-e36339171867.jpg)

I mean 1,7k renown for something that wasn't even a solo kill is in my opinion quite alot. Especially when you consider that there were so many order that we had diminishing rations. But okay this was close to a keep so you get this field of glory. It might be explained by that.

What confuses me is the 1158 renown for defending The Statue of the Everchosen. I mean I made literally 2 or 3 kills in the zone. None of which were close to the object. In fact the only thing I ever did at the object was riding by.

I mean I have no clue how this contribution stuff works so this might be alright but it seems a bit off to me.

**Comment by RogovArtem** [comment]
I have sim bag in T1. When you kill solo,without wb, another player, i got 30% Influence on T1.

**Comment by Luth-RoR** [comment]
High likely changed in the meantime due to ongoing RvR mechanic changes.
