### ISSUE TITLE
T3, Dwarfs vs. Greenskins,Badlands: Award for influence(награды за влияние).

### ISSUE THREAD

**Issue by RogovArtem** [WarEmu/WarBugs#8306]
Maybe you wrote about these bugs, but I decided to write about those that I have found.

Initially, the top i see that I have the full influence (came for the first time here), awards are not displayed 
the curator.

After rejoining the band was gone, so it looks like the curator
![image](https://cloud.githubusercontent.com/assets/12447382/20154206/5c49d2a8-a6d7-11e6-900b-8360a4d64131.png)
P.S in other T too was it seems too,maybe at the Greenskins.

Sorry for my English, in Russian.

В Бесплодных землях при заходе в локацию полоса влияние полная, у Куратора не отображается ничего. При релоге полосы нет вообще, а вот так выглядит окно куратора. 

P.S Тоже самое было и на других Тирах, кажется у Зеленокожих.

**Comment by RogovArtem** [comment]
![image](https://cloud.githubusercontent.com/assets/12447382/20166186/268a1c5c-a724-11e6-95cd-ed5d492054c6.png)

**Comment by RogovArtem** [comment]
![image](https://cloud.githubusercontent.com/assets/12447382/20166376/6f1651ec-a725-11e6-82e4-320b4ec9a3db.png)

**Comment by Soulwhisper** [comment]
This is a known issue.They cant split influence rewards to other pairings yet.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/6320#issuecomment-241884966
