### ISSUE TITLE
No item stats display

### ISSUE THREAD

**Issue by Ellenwe** [WarEmu/WarBugs#8308]
Just as the title  : I created a character, and I can't see any stats on his gear. The bubble for items stats (or comparaison with actual gear) don't even come. This hapend all the time, from inventory or from character page.

I will try these tests to see from where this isue come from : 
_ Create another character : this one may be bugged from start ?
_ Change resolution
_ desactivate all adds-on or/and one per one

**Comment by Luth-RoR** [comment]
This should solve it: https://github.com/WarEmu/WarBugs/issues/8287
