### ISSUE TITLE
[Quest][Destruction] Legend and infamy

### ISSUE THREAD

**Issue by lennip** [WarEmu/WarBugs#8309]
Quest: Legend And Infamy
Race / Chapter: Dark Elf Chapter 2
Location: The Blighted Isle

In this quest from Dark Elf Chapter 2 you're supposed to kill Nimosar Guardians and Nimosar Warriors. Problem is no Nimosar Warriors can be found, only Guardians, so the quest cannot be completed.

From the info I gathered about the PQ at Nimosar, there should be at least 2 types of mobs there: Nimosar Guardians and Nimosar Warriors:
[http://warhammeronline.wikia.com/wiki/Nimosar](http://warhammeronline.wikia.com/wiki/Nimosar)
And in this screenshot from the original game, you can also see Nimosar Artisans (orange):
![malineta_0221](https://cloud.githubusercontent.com/assets/2891053/20189508/c8e8c008-a77d-11e6-9286-7b626d88af87.jpg)

In the current version in RoR there are like 3 times more mobs in that place, but they are all Nimosar Guardians. There are also a couple of shadow warriors, but they are called "Menarheim Strongbow", so killing them doesn't count to validate quest requirements.

**Comment by Natherul** [comment]
This is currently working, no idea when fix was implemented. The warriors spawn at stage 2 of the PQ
