### ISSUE TITLE
[Duels] bug list

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#831]
Duel flagged players can attack ally NPC by aoe skills inside any duel zone even started by other players. Cant loot killed mobs but probably get exp for this.

Duel flagged player can join scenario as hostile non attackable unit. He can not be targeted by any direct positive effect but can be healed by aoe heal. Group frame of this player not updates.

Duel flagged player can be killed by any allied summon, line or turret as hostile player. Drops loot, exp and renown. Can easily be abused.

Duel zone (not sure) exist till both flagged players relog. All npc stay attackable in its duration.

**Comment by ozarmidrashim** [comment]
1, 3 and 4 fixed in next patch.
