### ISSUE TITLE
Incorrect picking/using objects

### ISSUE THREAD

**Issue by RogovArtem** [WarEmu/WarBugs#8310]
Many actions with lifting/using things you can do with one. Even the lift to influence a solo for 20 minutes.
https://youtu.be/JlGpCvR85h8?t=48s
https://youtu.be/JlGpCvR85h8?t=4m36s

**Comment by Luth-RoR** [comment]
Thanks for the videos, but this is known and not directly a bug; it's a missing feature that has not been implemented yet.
