### ISSUE TITLE
death under the bridge in Kadrin Valley's RvR lake counts as PvE and put 15m debuff

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#8315]
I was killed in Kadrin Valley's RvR lake and when i resurrect - i found myself in 21 chapter (Destruction) with 15m debuff. 
My guess is it happened because i died under the bridge.
https://youtu.be/5dAOnNNASLo

**Comment by saupreusse** [comment]
bridges dont count as RvR Lake.  So everything underneath a bridge is PvE. That's a known issue but the priority is pretty low because londo is busy with other stuff. Just try to keep this in mind and it shouldn't be much of a problem until it can be fixed.
