### ISSUE TITLE
archimage tactic , bolstering boon

### ISSUE THREAD

**Issue by Bufitos** [WarEmu/WarBugs#8318]
Before upgreat morale for all, this tackick helped UP morale ( 1heal = morale 1 , 3 eals = morale 2 , 8 heals = morale 3 , 15-16 = morale 4)
Now 7 heals = morale 1....  20-30 to lvl 2... (you lvl up faster morale thithout helsp) in rvr... well PLZ repair TACTIC, ( morale bonus on use direct heal )

**Comment by Luth-RoR** [comment]
Working as intended; read the patchnotes.
