### ISSUE TITLE
[Quest][Destruction] Prize of War quest chain

### ISSUE THREAD

**Issue by lennip** [WarEmu/WarBugs#8319]
Quest: Prize of War (quest chain, this is the 3rd or 4th part i think)
Location: The Blighted Isle
Race, Chapter: Dark Elf Chapter 2

I know there was a bug (now fixed) in the first part of Prize of war, but this isn't the same as it refers to one of the followup quests in the same chain. In this one, the quest requirements are mixed up, so the quest can't be completed.

Quest dialog and particulars indicate that the player should bring the Necklace to Urathos Baneblade, who is also in the Chapter 2 camp, a few meters away. 
![gwaendal_001](https://cloud.githubusercontent.com/assets/2891053/20238647/aa9bb0c8-a8f0-11e6-9f98-7deb19afcff0.jpg)
However, interacting with Baneblade does nothing. 
![gwaendal_000](https://cloud.githubusercontent.com/assets/2891053/20238664/e311698e-a8f0-11e6-80fc-577dc1befdb9.jpg)

Also, there is a mixup in the requirement list, as it appears as:
* Kill Adept Telrothral (already orange)
* Get Magicall Scroll 0/1

These requirements are the same as a previous quest from Chapter 2 that I already did (I think it was one of the previous parts of the same chain). The quest marker on the map is also wrong and shows the location of Adept Telrothral.

The correct requirement should be: 
* Speak with Urathos Baneblade 0/1

And Baneblade should appear with the orange overhead marker and trigger quest completion

Edit: I just noticed quest rewards are also mixed up, as they are the same as the one the requirements belong to.

**Comment by wargrimnir** [comment]
Should be fixed now. I only see one set of quest rewards however.
