### ISSUE TITLE
"Saving Grace" quest's goal missing

### ISSUE THREAD

**Issue by vonVince** [WarEmu/WarBugs#8324]
The goal of "Saving Grace" quest (in Praag by NPC Pontius Kosluvor) seems to be missing: the goal is to find "munitions crate", but after literally spending a couple of hours looking for the damn thing it looks like it is nowhere to be found.

**Comment by wargrimnir** [comment]
Confirmed there is a Munitions Crate spawn in Praag.

**Comment by Ryanfawkez** [comment]
Placed two extras, nothing wrong here.
