### ISSUE TITLE
Empire Chapter 18 Rally Master

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#8326]
- [ ] Skull above his head is blue but nothing to give.

**_Iirc Aza fixed restored/fixed these issues with Rally Master icons._**
![warhammer online age of reckoning 11 13 2016 - 17 34 09 11](https://cloud.githubusercontent.com/assets/16864486/20246797/92a02a6c-a9c7-11e6-9c4e-8a65aac5fe9d.png)

**Comment by Torquemadra** [comment]
you have a quest where hes the hand in/or speaking to him is a minor aspect of that needs to be completed which is causing the light up.

**Comment by Soulwhisper** [comment]
@Torquemadra Tested with my main and completed all the quests he had to give me.Still the same issue.
