### ISSUE TITLE
Cant join specific Warband-s?

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#8327]
Related to this #2513 ?
- [ ] Im not sure.Tried to join a WB last night as you see on video but it wouldnt let me in.I asked for inv and it worked.All players as you can see were in Party2(**maybe related?**)
https://www.youtube.com/watch?v=IW0fP6zFMAU
**_P.s. Tried everything from relogging to exiting game--->closing client and restarting game/restarting PC.
Still didnt work without invitation._**

**Comment by Soulwhisper** [comment]
No response and closing...most likely Warband packets not fully decrypted yet?

**Comment by Luth-RoR** [comment]
I got no notification on this one; reopening as this report has a better description and visual evidence.

**Comment by Natherul** [comment]
probably not related to #2513 I did a change to figure out what was wrong with the WB wide crashes (stated it in the patch notes as well) and I did a logical error that was not caught in dev. I will fix tonight when Im home from work.
