### ISSUE TITLE
Bug: resourse from keep

### ISSUE THREAD

**Issue by Bufitos** [WarEmu/WarBugs#8329]
How is bugged: you can return suples infine times:
1) pull suples , wait any 10 min, whithout return suples, when he spawn on BO, you can return infinite times suples on keep , ( repair spawn suples on BO, if they token from any 1 no spawn , will be bugged  , how on me, ) ( BO was token 2times from destros and order, ) 
(was banned for 1h for spawn 20 times it on keep)

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/8236
https://github.com/WarEmu/WarBugs/issues/8213
