### ISSUE TITLE
AM self target hot

### ISSUE THREAD

**Issue by Hekireki** [WarEmu/WarBugs#833]
When I play my AM I usually HoT myself or Moral 1 myself without having to target myself. Now I cannot do that anymore, I can spam my Lambent aura (HoT), the GCD goes like the spell trigger but it won't apply the HoT, I have to manually target myself and then it works. Same goes with moral 1, if I use it without targeting myself first, the CD goes off 1 min to wait, and I don't get any heal from the moral 1.

**Comment by ozarmidrashim** [comment]
#817 

Please read recent bugs before posting.
