### ISSUE TITLE
[Potent Enchantments] 

### ISSUE THREAD

**Issue by roadkillrobin** [WarEmu/WarBugs#8332]
Deals spirit dmg when tooltip says it should deal damage. All other tooltips in the game that says it deals no specific damage type refer to either physical or unmitigrated Morale damage. All tooltips that deals a specific damage type clearly says so. Here's before and after WoH debuff. 

![sworin_012](https://cloud.githubusercontent.com/assets/16356956/20250309/8cffaaec-aa0d-11e6-818c-79af5d696e63.jpg)
![sworin_013](https://cloud.githubusercontent.com/assets/16356956/20250310/8f93db66-aa0d-11e6-9d41-3478d3d8b2fc.jpg)

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/8167
