### ISSUE TITLE
T1 Lair Drop Issue

### ISSUE THREAD

**Issue by HeavyMetaloid** [WarEmu/WarBugs#8333]
Ok so we just killed the Dwarf T1 lair we got it down no problem but when it came to the loot i passed on a Warrior priest helm that dropped, i needed the Witch hunter helm that dropped and i dont know what happened but i didnt receive the helm. Everybody else passed on the item and yet i didnt receive it and my roll didnt come up at all. Any help would be appreciated. HeavyMetaloid

**Comment by Luth-RoR** [comment]
A screenshot of the chat log with the loot rolls would help to clarify.

**Comment by HeavyMetaloid** [comment]
![astraea_006](https://cloud.githubusercontent.com/assets/23444002/20254209/37057640-aa2a-11e6-9134-ddf5bb8c5cb6.jpg)
![astraea_007](https://cloud.githubusercontent.com/assets/23444002/20254207/370512a4-aa2a-11e6-8609-90484820df21.jpg)
![astraea_008](https://cloud.githubusercontent.com/assets/23444002/20254208/3705205a-aa2a-11e6-8101-be364880c6d4.jpg)
![astraea_009](https://cloud.githubusercontent.com/assets/23444002/20254212/37060632-aa2a-11e6-833b-69831fc8e9af.jpg)
![astraea_010](https://cloud.githubusercontent.com/assets/23444002/20254210/3705ad36-aa2a-11e6-9aa9-f84301a866e0.jpg)
![astraea_011](https://cloud.githubusercontent.com/assets/23444002/20254211/3705cd02-aa2a-11e6-8c0b-822e9f0ed356.jpg)
![astraea_012](https://cloud.githubusercontent.com/assets/23444002/20254213/3717db8c-aa2a-11e6-9cc7-a65013a10fca.jpg)
![astraea_013](https://cloud.githubusercontent.com/assets/23444002/20254214/3719debe-aa2a-11e6-817e-96b9de1f7df4.jpg)
![astraea_014](https://cloud.githubusercontent.com/assets/23444002/20254215/371a6d2a-aa2a-11e6-8df2-4cea72fcc0de.jpg)
![astraea_015](https://cloud.githubusercontent.com/assets/23444002/20254216/371c381c-aa2a-11e6-83f4-244992684c57.jpg)
![astraea_016](https://cloud.githubusercontent.com/assets/23444002/20254218/3720e894-aa2a-11e6-86e9-44005b9e30bf.jpg)
![astraea_017](https://cloud.githubusercontent.com/assets/23444002/20254217/371f0006-aa2a-11e6-96ef-cfa80fffe0db.jpg)
![astraea_005](https://cloud.githubusercontent.com/assets/23444002/20254219/372bab58-aa2a-11e6-8125-0dd31385bb17.jpg)

**Comment by Soulwhisper** [comment]
@HeavyMetaloid Were you dead when you pressed Want for your item loot?

**Comment by HeavyMetaloid** [comment]
yeah think so, that stop you getting the loot?

**Comment by Soulwhisper** [comment]
Yes its a known bug.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/7494
