### ISSUE TITLE
Incorrect Inf Reward Icon

### ISSUE THREAD

**Issue by Simmox** [WarEmu/WarBugs#8334]
Empire chapter 15 Influence reward
Master's Phenomenon jewelery item shows chest armour icon
Gregor Korsekov

**Comment by Soulwhisper** [comment]
Pyromancer's Phenomenon too.
Craftman's Phenomenon too.
Wiseman's Phenomen too.
All are jewerlies but show chest armour icon.

**Comment by Soulwhisper** [comment]
Woodsman's Phenomenon
![warhammer online age of reckoning 01 12 2017 - 13 24 34 81](https://cloud.githubusercontent.com/assets/16864486/21887917/b04abd98-d8ca-11e6-9333-35b98d0e5dbf.png)

**Comment by wargrimnir** [comment]
Fixed in next.
