### ISSUE TITLE
Squigherder tactic Ere Squiggy makes pet attack SH.

### ISSUE THREAD

**Issue by AlistaireCrowley** [WarEmu/WarBugs#8335]
When you use Ere Squiggy tactic ( 25% chance pet will take damage directed to SH) and pet takes damage it starts to attack the SH. Have to release pet to make it stop. 

Dont know if its been posted before but it surely is annoying. 

Best regards

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/8112
