### ISSUE TITLE
Tier 2 ORvR - Bugged

### ISSUE THREAD

**Issue by Scrazna** [WarEmu/WarBugs#8337]
Hi,

I'm not sure if it's been fixed but I've only had a chance to report it today.

Yesterday, the only active zone in T2 is Dwarf vs Greenskins. After a side locked the zone, it was then impossible to use any other zone as supply did not drop for some reason.

Most people then logged out and switched to their alts to fight in other tiers / zones. As I'm still new to the game, T2 was the only option I had so I pretty much had to wait however long it took for the zone to reset. (Happened 3-4 times before I logged out). 

Because everybody switched characters after a zone lock, scenarios weren't an option either as they simply weren't popping.

I'd be grateful if the supply drops in T2 Elf or Emp could be fixed just so those zones aren't completely useless. 

Cheers,

Scrazna

**Comment by Luth-RoR** [comment]
Known: https://github.com/WarEmu/WarBugs/issues/8258
