### ISSUE TITLE
Bottles of Naphtha

### ISSUE THREAD

**Issue by Uchoo** [WarEmu/WarBugs#8339]
![galrauch_005](https://cloud.githubusercontent.com/assets/15972308/20277644/054a0138-aa67-11e6-8711-6dcd81593535.jpg)
The Bottles of Naphtha seen here are not added to your inventory upon clicking.

Location:

![galrauch_006](https://cloud.githubusercontent.com/assets/15972308/20277661/2591d5f6-aa67-11e6-8e05-bd424b4065d4.jpg)
The bottles are used to clear the following vines, allowing access to that area.

![galrauch_003](https://cloud.githubusercontent.com/assets/15972308/20277692/3ea829fa-aa67-11e6-9b36-f4bcb60b201f.jpg)

Location:

![galrauch_004](https://cloud.githubusercontent.com/assets/15972308/20277700/49d72cf4-aa67-11e6-91b8-ea6d27c5761c.jpg)

**Comment by Luth-RoR** [comment]
Complex quests like this one mostly don't work yet afaik.

**Comment by Ryanfawkez** [comment]
I think this was related to an old live event lair. Lemme find the HammerWiki page.
