### ISSUE TITLE
Mail CoD payment not "given"

### ISSUE THREAD

**Issue by deadkoo** [WarEmu/WarBugs#8342]
Howdy.

So yesterday, sent a ring on CoD to Dehart(made sure he was logged in so it didn't disappear into the ether). Guess he forgot to buy it till today, I login showing no mail received, PM dehart about it, and am told that they bought the CoD earlier today when I was offline. 

Checked the other CoD posts, don't see anything about gold not being sent if original CoD seller is offline.

Edit: I did happen to use .changename on my toon yesterday however after the CoD was sent... I hope I didn't screw myself with that actually, but didn't think about it.

**Comment by Luth-RoR** [comment]
>to use .changename on my toon yesterday however after the CoD was sent

If you used the namechange before he paid for the item, the gold was maybe sent to your old character name. 
I will try to clarify, if mails are send to character names or IDs.
