### ISSUE TITLE
"Unknown2" Invisible lvl55+ lords around the Orcwerks

### ISSUE THREAD

**Issue by Nefarian11** [WarEmu/WarBugs#8344]
After farming the Orcwerks PQ for some time i noticed that there are invisible lvl55+ lord npcs all around the area, in the water. i don't know if those npcs were placed intentionally or not. (didn't find any posts on the forums about this) 
 
some screenshots.

http://imgur.com/a/m26Rx

**Comment by Luth-RoR** [comment]
Iirc these NPCs have been created automatically and served for some unknown purpose on the ToK.

**Comment by Ryanfawkez** [comment]
They were placed by a database dev with the intention of stopping enemy forces from griefing this PQ.
