### ISSUE TITLE
Quest  : Bone of contention (multiple bug)

### ISSUE THREAD

**Issue by gschouweiler** [WarEmu/WarBugs#8346]
T3 quest Avelorn.

This quest is impossible to finish actually.

After kill several oaktalon eagles and brownback gouger. No item drop  to complete each step.
After look for jade wizards on all aera Everspring, there is no NPC
On map there is no indication for an aera to do the quest, and not listed on right.

![missions](https://cloud.githubusercontent.com/assets/22920863/20306281/bb598ade-ab39-11e6-936b-1a9808e401e2.PNG)
![action](https://cloud.githubusercontent.com/assets/22920863/20306285/bf1e832c-ab39-11e6-9d44-8dd7ece69906.PNG)

**Comment by wargrimnir** [comment]
Need to create these items and drop tables for the specific mobs. Confirmed are 21 Jade Druids spawned on this map.
