### ISSUE TITLE
Quest : Fellowing (shadowlands)

### ISSUE THREAD

**Issue by Ellenwe** [WarEmu/WarBugs#8347]
In this quest, you have to kill different Harpies (3 different names). Two of these don't work at all. The last one flag for all 3 types (so you don't have to kill 15 harpies, but only 5 of the only type that count). 

Hope it help a little !

**Comment by Luth-RoR** [comment]
What are the names of the harpies who don't work?

**Comment by wargrimnir** [comment]
Mobs were all flagged for the same harpy. They should be split up now.
