### ISSUE TITLE
Flame Arrow (Shadow Warrior)

### ISSUE THREAD

**Issue by Ellenwe** [WarEmu/WarBugs#8348]
The speed of the projectile is incredibly low. The damages seems as per tooltill (but I think the second part don't land immediatly, but after the first tick). 
The only real problem with that is for deathblow : if the flamming arrow deal the deathblow, the the NPC/player will be freezed in his basic stance, as long as the arrow don't land on it. In this case, it is impossible to loot, and sometimes the kill isn't recorded.
Sometimes, the  tick of AoE damage is applied when the arrow reaches is target : I've been locked in combat because the arrow reached a dead NPC who already respawned, he took the AoE damage and then engaged fight.

Hope it help, I can try to add screenshots in PvE mode.

**Comment by sioding** [comment]
fixed
