### ISSUE TITLE
Ram self destruction (T3 order: Talabecland)

### ISSUE THREAD

**Issue by Ellenwe** [WarEmu/WarBugs#8349]
Yesterday, I've seen 3 times a ram be self destructed. 

It happened all 3 times near the zone to High Pass, on the top of the hill. The player didn't get attacked, only goes straight from the catle gates, and was moving to the battle objective in High Pass.
Nothing more information, the ram only dissapear. The zone braodcast for ram destruction work.

Hope it can help.

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
