### ISSUE TITLE
[ToK] Brutal Nose Ring doesnt work.

### ISSUE THREAD

**Issue by Rhungk** [WarEmu/WarBugs#8350]
Hi, the item [Giant Nosering] dropped by Vragi the Brute (Chaos troll, lvl 39)  in KV (33500,28000 aprox) that unlocks the ToK "Brutal Nose Ring" of gigants,  that gives you a Gigant tactic fragment when used, can´t be used. Screenshoot here: 
http://imgur.com/XTJxK3g

**Comment by Luth-RoR** [comment]
I don't think any of the ToK entries that give PvE tactics work yet (as well as the tactics).

**Comment by Rhungk** [comment]
A few of them works like the ToK entrie of "It´s a Snap" (killing champion troll at Troll Country) works, or killing 1,000 nurglins. I just found it and think its my duty inform of it.

**Comment by Luth-RoR** [comment]
Yes, many ToK entries work atm, though the PvE tactics are low priority i guess.

**Comment by Rhungk** [comment]
Sure, i undestand that fix the balance classes, implemet renown habilities like trivial blows (cross fingers) or improve the actual rvr is priority, but the report will be here when you think fit to fix it jaja.

**Comment by Lheana** [comment]
Think it is now fixable :) The item still drops but does not provide the unlock.
