### ISSUE TITLE
Ironbreaker/Earthshatter doesnt damage targets.

### ISSUE THREAD

**Issue by eder86** [WarEmu/WarBugs#8351]
Earthshatter doesnt damage targets. Targets get snare effect but doesnt get any damage.
![scagat_007](https://cloud.githubusercontent.com/assets/23484096/20318211/6702db34-ab7a-11e6-8351-dc096ee6e4c7.jpg)

**Comment by Ryanfawkez** [comment]
https://github.com/WarEmu/WarBugs/issues/6824
