### ISSUE TITLE
Drop of destruction intem on order side

### ISSUE THREAD

**Issue by Hastykrasty** [WarEmu/WarBugs#8352]
During rvr in KV I dropped the Armscales of the Eternal, which are for DoKs. While I am a WH.

![lymond_000](https://cloud.githubusercontent.com/assets/23488003/20327835/2f702c16-ab8f-11e6-85c1-550b520d3561.jpg)

**Comment by wargrimnir** [comment]
I couldn't find any reason for this. Slap that dubious tag on it.

**Comment by Luth-RoR** [comment]
Probably fixed already, closing.
