### ISSUE TITLE
murderous intent

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#8353]
should also give 10% heal crit, it give not., probably happen the same on wp tactic counterpart.

**Comment by bozzax** [comment]
Yes I tested this on live and that is how it was even though I always thought "critical hit" never should increase heals

(DT, LS, MI, ...)

**Comment by Tesq** [comment]
until the changes yes, now it's pretty mandatory for both classes, you need that parry/crit to work efficently; anyway the benefith is a raw 10% and it would be in line with other tactics

loose 20% heals, gain 10% parry + 10/10% crit so is +10% with out other trade off and is in line then.

**Comment by Luth-RoR** [comment]
The bugtracker rule to post evidence instead of wild guessing applies to everyone, particularly veteran players who should know better.
Because of the lack of screenshots and information, i just tested it and the .getstats output for both classes with the tactic slotted shows _CriticalHitRate 10_, which is the general crit rate. _MeleeCritRate_ is for melee crits only. 

![luthwp_000_crop](https://cloud.githubusercontent.com/assets/8567481/20342262/064020e8-abea-11e6-9b56-c66a80174ce7.jpg)

**Comment by Tesq** [comment]
Then problem lies elsewhere then with the same crit chance from renow and murderous intent i crit a lot less.
Basically with or with out my crit dosent increase or decrese.
I also looked at get stat and i didnd't saw the 10% in the general crit rate some daya ago. Just 10 in melee strange i will give it a look again, maybe it was a bug with the new stances? Because i was testing the change during firat day.

**Comment by Tesq** [comment]
re test it today i came to the conclusion that there is 1 stackig problem somewhere in crit stack between different source seems to be linked to the fact that a general crit rate dosen't stack with the 10% that every healer have for crit at base maybe they end in the same stack group and don't stack? i say this because main hand test show that the crit dosen't increase at  all cast heals  over 100 heals.

**Comment by Luth-RoR** [comment]
About 20 heals is no base for statistics.

Tested with enemy combatlog:

100 tries with no crit chance: 11% crits on average
![20161120211323_1_crop](https://cloud.githubusercontent.com/assets/8567481/20465878/0ae24fb4-af68-11e6-995c-000607d37a28.jpg)

300 tries with 10% crit chance on everything (tactic): 17% crits on average
![20161120211330_1_crop](https://cloud.githubusercontent.com/assets/8567481/20465885/482ab28a-af68-11e6-862c-415cceeee484.jpg)

100 tries with 19% crit chance (tactic + 9% renown): 30% crits on average
![20161120211904_1_crop](https://cloud.githubusercontent.com/assets/8567481/20465893/75ba3824-af68-11e6-8b5c-9568b8ffe811.jpg)

This is what i mean with evidence.

**Comment by Tesq** [comment]
Luth im seriouse i tested it even with out of party heals i had a 26% which is 36% with hidden crit and i didn't even once i not critted there is no way i make no crit with a 36 %  on 5 ppl multiple times in row it must be a wrong inplementatiom of murderous intent only then you tested it only on wp, try on dok not wp. Im 100% sure murderous intent is bugged
