### ISSUE TITLE
Squignoggin of Dominion

### ISSUE THREAD

**Issue by Scrazna** [WarEmu/WarBugs#8354]
Hi,

Please see the attached file below. The Rank 16 / Renown Rank 11 Squig Herder helmet doesn't have any stats besides armour whereas all the other Dominion gear does.

Thanks,

Scrazna

![scrazna_000](https://cloud.githubusercontent.com/assets/23169848/20329647/70816bb4-ab91-11e6-878f-02d7dc97340c.jpg)

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/8219
