### ISSUE TITLE
Unequip Weapon/Ring =-1spec point

### ISSUE THREAD

**Issue by Stophy22** [WarEmu/WarBugs#8355]
I keep losing and then imediately gaining my spec point when I unequip my SNB and put on a 2 hander. This also happens when I put on different cloaks / rings

**Comment by Luth-RoR** [comment]
This is known and can't be fixed atm. It happens because you got an additional mastery point due to an armor set bonus. Every time that happens, you can download the "anywhere trainer" addon to assign the stat point again without the need to visit a trainer.

**Comment by Stophy22** [comment]
Thank you very much that helps
