### ISSUE TITLE
strange issue with a scenario.

### ISSUE THREAD

**Issue by Nefarian11** [WarEmu/WarBugs#8356]
Me and my guild were queueing premade scenarios (around 3am central europe time), we joined a scenario (Maw Of madness) and it happened that i was in kind of a limbo. i was in the scenario but not really. my group mates didn't see me at all in the scenario, but i could see them. i was in their same group, i could guard, target them but they didn't see me at all. a marauder joined in the group too, so we were 7 in a group (even if they didn't see me). when the scenario ended my character had a rollback or something, and i found myself in praag warcamp, the place i was about 30-35minutes before. 

i hope it's all clear, it's kinda hard to explain because my main lenguage isn't english

**Comment by Luth-RoR** [comment]
Everything is understandable.

**Comment by wagwan** [comment]
I'm having the same problem. I queued and once i got in there wasnt anyone there and there was no timer.. I left but i pressed no by mistake so im kinda stuck inside the sc .. but then people started showing up and Im not included in the fight i cant join parties i cant leave the sc 

basically i got the quitter debuff while im inside and it kept me locked in the sc

**Comment by Natherul** [comment]
Same issue here with one of my friends, he joined but was not part of the groups, he got the quitter debuff while in the SC and he could not exit the SC once it was done...

**Comment by Natherul** [comment]
@Luth-RoR this is same issue as https://github.com/WarEmu/WarBugs/issues/8162 please close this one and link them

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/8059
