### ISSUE TITLE
Ironbreaker Earthshatter targets.

### ISSUE THREAD

**Issue by eder86** [WarEmu/WarBugs#8357]
We have 100 grudge.
We have 4 rats.
Use EarthShatter give snare effect on 4 rats but damage only -2 or 1.
![scagat_000](https://cloud.githubusercontent.com/assets/23484096/20336833/4ddc5c66-abde-11e6-95f4-e4e856afa6d8.jpg)
Reading the tooltip. 
"Deals damage to each enemy hitting by snare effect"
All rats have snare debuff.
Before 8 november skill works properly.

**Comment by Luth-RoR** [comment]
Maybe related to https://github.com/WarEmu/WarBugs/issues/8357
