### ISSUE TITLE
pots from vendors 

### ISSUE THREAD

**Issue by destruch** [WarEmu/WarBugs#8358]
not salable pots (for recruits, scouts etc. medals and emlbems) can be sold to vendor
U cant sell them by right clicking but u can if u just grab them from backpack and put to a vendor.

**Comment by Kaelang** [comment]
Appreciate this is a dated report - however this does not provide enough information to identify the issue and/or replicate the problem. Please re-open this issue if this persists in the latest version of RoR.

(Tried testing on live - no result)
