### ISSUE TITLE
Unlootable corpses

### ISSUE THREAD

**Issue by xyeppp** [WarEmu/WarBugs#836]
When killing mobs something causes them to become unlootable - sometimes it lets you loot after a short while, most of the times however the corpse will just lay there showing lootable but will not let you.

**Comment by Silentguard** [comment]
All lootable-highlited corpses also becomes unlootable in case of player death.

**Comment by Tesq** [comment]
I saw that low level " trivial" mob give me no drop and no money, wasn't like that on official, this could be maybe related.

**Comment by Reggaewaldo** [comment]
This should have been resolved.
