### ISSUE TITLE
Quest : Lord's game

### ISSUE THREAD

**Issue by gschouweiler** [WarEmu/WarBugs#8360]
Probably missing a NPC to complete quest
After kill Elder Meresene, area indication disappear on map.
I look for on all zone of "Shattered Basin" during several hours and just find Elder karadon (three NPC exists with same name) but Elder Kadrias is missing.

![missions](https://cloud.githubusercontent.com/assets/22920863/20352563/fca395dc-ac17-11e6-8a47-06e05628c051.PNG)
![map](https://cloud.githubusercontent.com/assets/22920863/20352573/01be55a2-ac18-11e6-960e-fdb05a25d0d4.PNG)

**Comment by Luth-RoR** [comment]
Refering to https://github.com/WarEmu/WarBugs/issues/8118

**Comment by wargrimnir** [comment]
Confirmed there is a creature spawn for this mob.

**Comment by gschouweiler** [comment]
Ok Fixed.

![image](https://cloud.githubusercontent.com/assets/22920863/26108836/efd06730-3a4d-11e7-9a0a-e45b60777832.png)
