### ISSUE TITLE
Squig herder item: Vile

### ISSUE THREAD

**Issue by Squea** [WarEmu/WarBugs#8364]
Item: Vile
Main hand Spear
Item Level: 36

If I remember correctly this is the spear reward for the Greenskin T4 epic quest. Equipping this item un-summons the currently summoned squig. Other spear items do not un-summon the pet. It happens only when you equip Vile, if you unequip the item with a squig the pet behaves as normal.

**Comment by Luth-RoR** [comment]
It doesn't happen when you unequip other items?

**Comment by Squea** [comment]
Unequipping items behave as normal and do not affect the pet. To be clear unequipping Vile behaves as normal as well. It is only on equip, and only with Vile, that the pet is unsummoned.

**Comment by Luth-RoR** [comment]
Ok, i thought it might be because of the additional mastery point on the T4 sets, but then it has to happen with every item.

**Comment by wargrimnir** [comment]
Need to test this one later.

**Comment by wargrimnir** [comment]
Nope, just an old weird ticket. Seems to be working fine.
