### ISSUE TITLE
Exp explosion after failed keep defense (empire, Order)

### ISSUE THREAD

**Issue by exelendo** [WarEmu/WarBugs#8365]
I was defending the keep Passwatch Castle, when Destro took it i instantly went from rank 28 to lvl 40, was standing on the top floor, me and a mate were killing alot before they took it. dunno if the multiplyer went insane? had also been in highpass\talbac for the last 2 hours fighting.

**Comment by Luth-RoR** [comment]
Known problem: https://github.com/WarEmu/WarBugs/issues/8363
