### ISSUE TITLE
Book of Binding - wrong location

### ISSUE THREAD

**Issue by rngvp** [WarEmu/WarBugs#8367]
I had my rally point set to Sorcerer's Axiom(Norsca) and I was in Amund's Barrow(Norsca) on a quest.  I used my Book of Binding to get back to Sorcerer's Axiom but it took me to the elf starting area in the blighted Isle. Even if I didn't bind to Sorcerer's Axiom correctly, I'm certain that I was bound to the first town in Norsca.

**Comment by Soulwhisper** [comment]
Can you test it again please because i tried it with my Sorcerer and it worked fine.

**Comment by rngvp** [comment]
I tried again but not to and from the same locations and it worked fine.  Is the default for any elf character that starting zone?  It could have been that I didn't ever get the rally point set because of lag or something like that.

**Comment by Soulwhisper** [comment]
Yes..its by default.All players start from chaos but Dark elves and Greenskins have diferrent rally points by default for some reason.
@Luth-RoR This can close.

**Comment by Luth-RoR** [comment]
Sorcerer's axiom binding point works fine on the dev server.
