### ISSUE TITLE
Debolster cleaning all potions

### ISSUE THREAD

**Issue by Paleolog77** [WarEmu/WarBugs#8368]
When debolster is lowering my lvl, ANY potions buff will cleaned. It cleaning t1 potions. I want to go to another RvR t1 realm. I'm fly, & become high lvl, than go to RvR, & t1 potion buff is cleaning.

**Comment by Luth-RoR** [comment]
What's a "T1 potion"?

**Comment by Paleolog77** [comment]
What's a "T1 potion"?

I mean potions, that using in t1 RvR.
-Lasting Spirit Block Potion
-Lasting Potion of Muscle
& other like this

**Comment by Luth-RoR** [comment]
Those are level 10 postions with item level 12. As the bolster debuffs you to level 9 in T1, the buff is removed from you as soon as you debolster (because buff > level).
See also https://github.com/WarEmu/WarBugs/issues/5009 
and https://www.returnofreckoning.com/forum/viewtopic.php?f=66&t=17151
