### ISSUE TITLE
[Guild] Item disappearing from guild vault

### ISSUE THREAD

**Issue by notre4ror** [WarEmu/WarBugs#8370]
Like here: 
https://github.com/WarEmu/WarBugs/issues/8198 
&
https://github.com/WarEmu/WarBugs/issues/8214

Hi,
In the pas few days lot of items randomly disappear of the first vault,  instead of the "hole"(lack of item) i got "copies" of the near items, i'll explain:

On the first vault i put some dyes sorted by "colour order" & "quality order" (greens, blues, etc.. & uncommon, rare, very rare), today i see duplicate stacks of dyes (same color, same amount, wich isn't possible with "colour order") and missing other colours stacks and stacks of very rare dyes.

This happens since last week aprox. ( i see this three times in the alst week) and seems to affect only on the first vault, the second and third has no issues. Before i have no problems with the guild vault.

**Comment by Luth-RoR** [comment]
Always use existant reports for the same problem instead of opening new one; i copied your post to the one you already linked.
