### ISSUE TITLE
RvR Zone Plotholes

### ISSUE THREAD

**Issue by Pumatouch** [WarEmu/WarBugs#8372]
In Kadrin Valley I discovered a spot within the RvR zone where you don't get RvR tagged. 
It's down the tunnel, into the alcove on your right if you travel south. The left alcove does not seem to have it.

![](http://i.imgur.com/4Wwi4ul.jpg)

![](http://i.imgur.com/sEXtS5N.jpg)

**Comment by Luth-RoR** [comment]
Afaik that can't be solved atm.
