### ISSUE TITLE
[Ritual of Lunacy]

### ISSUE THREAD

**Issue by roadkillrobin** [WarEmu/WarBugs#8375]
Doesn't seem to have a crit component.
This is after about 6-7 scenarios. 

![nocrit](https://cloud.githubusercontent.com/assets/16356956/20441103/5c39297e-adc3-11e6-9038-ab76c8bd2341.jpg)

**Comment by Luth-RoR** [comment]
The ability could neither crit on 1.4.8 nor proc anything.

**Comment by roadkillrobin** [comment]
Something that was changed later on then, i remember it not being able to proc on direckt heal things, But I deffintly remember it procing both AP and healpower  buffs from Sovereign gea as these for on heal procs rather then direckt heal.
It crits quit often in this video btw:
https://www.youtube.com/watch?v=-n9Azxp4UGY,

**Comment by Luth-RoR** [comment]
> youtube video from 13.02.2010

https://github.com/WarEmu/WarBugs/issues/7543
https://www.returnofreckoning.com/forum/viewtopic.php?f=72&t=16566
