### ISSUE TITLE
The mysterious M.B. quest, duplicate non-functional "Dusk covered flasks"

### ISSUE THREAD

**Issue by peusnaugrim** [WarEmu/WarBugs#8378]
hi, the LAST part of the quest is broken. 
![thorbolt_022](https://cloud.githubusercontent.com/assets/16274785/20453100/4783043e-ae1b-11e6-9b0d-a4d67cd33720.jpg)

you can take the last flask "dust covered flask" 

the  first part of the quest was fixed on August 25th. but it wasnt the "dust covered flask

**Comment by peusnaugrim** [comment]
you click on the "dust covered flask and nothing happen (btw the flask seems to be inside the wall)
May be you can fix it? thank in advance.

**Comment by Luth-RoR** [comment]
I did the quest about a week ago and just checked it again on the dev server; dust covered flask works like charm.
You probably found a duplicate/wrong one.

![luthslayer_006_crop](https://cloud.githubusercontent.com/assets/8567481/20454115/f875bf64-ae36-11e6-82da-b2b1806b2185.jpg)
![luthslayer_007_crop](https://cloud.githubusercontent.com/assets/8567481/20454116/fc8c1d3c-ae36-11e6-9a4d-1cb631d15460.jpg)

**Comment by Luth-RoR** [comment]
This report was probably about the same issue https://github.com/WarEmu/WarBugs/issues/6973

**Comment by Blaqwar** [comment]
Just tested this and the correct flask works but the weird thing is that clicking the one in the wall targets the correct flask which is on the other end of the room. Are they the same flask but targettable inside the wall on that spot? O_o

**Comment by Luth-RoR** [comment]
It could be also that this is needed for a workaround to get the ToK unlock.

**Comment by peusnaugrim** [comment]
What is the location of the correct flask?

**Comment by Blaqwar** [comment]
Back of the same cave section, very easy to find, it's a bunch of bottles.

**Comment by ellionkeman** [comment]
sand covered flask can't be clicked

![balpharuoth_054](https://cloud.githubusercontent.com/assets/18136746/24162439/92bb9c50-0e78-11e7-92c3-45c8c99f1626.jpg)
