### ISSUE TITLE
Live Event "Minions of the Under-Empire: Skaventide

### ISSUE THREAD

**Issue by Renomaker** [WarEmu/WarBugs#8380]
Hi, my character name is Renomaker, its a wp. i would like to get the skaven cloak so i did the Lost in the Darkness i went to the maze, find the dead dwarf (Burgok) i killed the skaven champ. I got the skaven token and the skaven trophy but when i came out from the maze, i cant speak the quest giver (Mining Overseer Kamrod). So i dont get the skaven cloak. I tried to do it over and over again i have some Burgok' notes. But i cant contact the quest giver Mining Overseer Kamrod.
I would like to ask you if you have a lil time help me out. I really like to get the skaven cloak. If you reset the bugged quest on me i can do it again. 
Surely noticed English is not my forte, 
I apologize for it.

**Comment by Luth-RoR** [comment]
Can you make a screenshot of the quest in your tome of knowledge?

**Comment by Renomaker** [comment]
Hi, thank you your agility.  When i realised i cant speak the npc (Mining Overseer Kamrod),  i tried to do it again( 3 times maybe), and when i realised it was not working i abadonded the quest. In a hope i can get again the quest starting from the begining. It didnt work either. I spoke some GM one of them told me maybe a server restart will solve my problem but it didnt. So another GM told me it is a bug and you can help me. I made sceershot about the skave trophy you can see on this picture have the skaven ring, i made a picture about the 2 skaven token one from the skaven ring quest the other skaven token from this bugged quest. And i made picture from the bugged quest item burgok'notes (i have 2 of them, i deleted some in a hope it can solve the problem. Thank you again your work.
![renomaker_041](https://cloud.githubusercontent.com/assets/23578687/20455644/d6594c14-ae60-11e6-8c34-d7b4d82edc03.jpg)
![renomaker_040](https://cloud.githubusercontent.com/assets/23578687/20455647/e63b2620-ae60-11e6-9051-34898329cb41.jpg)
![renomaker_039](https://cloud.githubusercontent.com/assets/23578687/20455651/f54d75d2-ae60-11e6-9705-14859bda920b.jpg)

**Comment by Renomaker** [comment]
(the server drop me out) i take another picture about my quest and i cant contact the npc. the other picre about my inventory and i cant contact the npc. Thank you.
![renomaker_042](https://cloud.githubusercontent.com/assets/23578687/20455693/1ac50130-ae62-11e6-8bcd-95fa789386fc.jpg)
![renomaker_043](https://cloud.githubusercontent.com/assets/23578687/20455706/334aa3cc-ae62-11e6-98ad-1e550cece917.jpg)

**Comment by Luth-RoR** [comment]
Ok, i just checked it: for the cloak you have to do the quest "lost in the darkness" (questgiver: toxinol).

The rewards are mixed up in this guide: https://www.returnofreckoning.com/forum/viewtopic.php?f=19&t=9235#p98489

![luthslayer_008_crop](https://cloud.githubusercontent.com/assets/8567481/20497315/f4998dc8-b028-11e6-80f5-aecff5ac33ca.jpg)
