### ISSUE TITLE
Artifact Weapon.

### ISSUE THREAD

**Issue by Juddgt** [WarEmu/WarBugs#8382]
I chose an influence reward at the "Dragon's Blessing" PQ, Chapter 17, Thunder Mountain. When I got it it had Career IB but had ballistics on the stats.

![toffu_002](https://cloud.githubusercontent.com/assets/22923758/20457665/b465e06a-aef4-11e6-9be5-b544bd6add8c.jpg)

**Comment by Luth-RoR** [comment]
It has probably the same stats as on the mythic server.

**Comment by Torquemadra** [comment]
probably but worthless stats are not a staple here.

**Comment by wargrimnir** [comment]
This was fixed some time ago
