### ISSUE TITLE
Trapped without exit in Barak Varr

### ISSUE THREAD

**Issue by dicoca** [WarEmu/WarBugs#8383]
Greetings, it seems that there is a kind of trap in the risk of foultooth's warcamp, where when jumping I was trapped in the slope looking like I'm falling so any spell is interrupted, including my book of bindnig, have i just loss one of my characters?

**Comment by Luth-RoR** [comment]
Type 2x _/stuck_ into the chat window to get ported to the starting location. Next time please use the support forum for support questions, the bugtracker is only for bugs.

**Comment by dicoca** [comment]
ty a lot!!!! :D
