### ISSUE TITLE
Feetsplate of havoc

### ISSUE THREAD

**Issue by skarsik** [WarEmu/WarBugs#8385]
The black Orc Havoc set boots are bugged and doesnt have the 1% stat on them unlike other classes. I believe they suppose to have block but I cant remember the stat that is missing.

![greedo_002](https://cloud.githubusercontent.com/assets/23616633/20464311/53ab84c2-af13-11e6-875b-ee9a721bb76c.jpg)

**Comment by Natherul** [comment]
fix pending, was melee crit
