### ISSUE TITLE
Bug: Can't complete quests with item rewards.

### ISSUE THREAD

**Issue by moboyland** [WarEmu/WarBugs#8387]
I can not turn in quests and receive my reward. It gives me the error message that I must empty overflow. I have empty inventory space. Character name is Defiled.

**Comment by Luth-RoR** [comment]
That's a known issue; your either your normal inventory or your crafting inventory was full as you tried it the first time. 
If you try it again _after a server restart_ it should work. But before you try it again, please make sure that your main inventory **and** your crafting inventory are not completely filled up.
