### ISSUE TITLE
ToK unlock 'Dark Rites'

### ISSUE THREAD

**Issue by Sapphiratelaemara** [WarEmu/WarBugs#8399]
Approaching altar does not provide unlock.
![image](https://cloud.githubusercontent.com/assets/23622177/20468514/cd78bb4c-af97-11e6-9ac4-6a6bb6fbe5e5.png)

**Comment by Lheana** [comment]
Fixable if the unlock is linked to the 'Altar of the Scepter' (17.8k 20.7k). It is already possible to interact with the altar, thus interacting with it could provide the unlock.
