### ISSUE TITLE
ToK 'The Bloodfiends'

### ISSUE THREAD

**Issue by Sapphiratelaemara** [WarEmu/WarBugs#8402]
Interacting with Mark of Khorne does not provide unlock.
![image](https://cloud.githubusercontent.com/assets/23622177/20474361/550bd55c-afc6-11e6-9b46-27b1cb2e66a2.png)

**Comment by Lheana** [comment]
Unlocks triggered by interacting with objects like for this H&L unlock, can not be fixed yet ?
![anaehll_302](https://cloud.githubusercontent.com/assets/11537611/21386606/db7f9064-c773-11e6-808b-a74b275d0312.jpg)

**Comment by Luth-RoR** [comment]
Was my mistake, it high likely can be fixed.
