### ISSUE TITLE
Tooltip stat changes 

### ISSUE THREAD

**Issue by xyeppp** [WarEmu/WarBugs#841]
Upon zoning, my ballistic stat seems to randomly change. Normally I have 362 ballistics with the Masterful Aim tactic on - upon zoning it lowers down to 356.  

![github_005](https://cloud.githubusercontent.com/assets/12982209/8344665/918df120-1adc-11e5-8965-9e5c6c29b81f.jpg)
![github_006](https://cloud.githubusercontent.com/assets/12982209/8344667/9470afae-1adc-11e5-9919-c403fd3f2d2a.jpg)

**Comment by ozarmidrashim** [comment]
Might be related to Masterful Aim.

**Comment by Silentguard** [comment]
This is not a bug. You just bolsted in firs case to lvl21 instead of your lvl20 and it gives you a very small scaling of stats.

**Comment by xyeppp** [comment]
Well shit, that's embarrassing.
