### ISSUE TITLE
Axerust Peak - Normal Public Quest Dwarf Chapter 5

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#8411]
- [x] There is not chest when you finish the PQ if you havent unlocked Dwarf Chapter 9.
- [x] There is no PQ tracker inside the area if you havent unlocked Dwarf Chapter 9.
- [x] There is no Chapter bar if you havent unlocked Dwarf Chapter 9 and if you do so,it shows as Dwarf Chapter 9 inside of the PQ area.
**Referring** #8412
![warhammer online age of reckoning 11 21 2016 - 16 50 57 01](https://cloud.githubusercontent.com/assets/16864486/20487099/ce6c220a-b00a-11e6-9e52-1cc95f6edf07.png)
![warhammer online age of reckoning 11 22 2016 - 16 49 47 10](https://cloud.githubusercontent.com/assets/16864486/20528253/1bc43028-b0d4-11e6-84ef-2c1eac3181b5.png)
![warhammer online age of reckoning 11 22 2016 - 16 50 27 11](https://cloud.githubusercontent.com/assets/16864486/20528254/1bce7a1a-b0d4-11e6-8c92-2b6fcfac814a.png)

**Comment by Blaqwar** [comment]
Everything worked for except for the influence bar (the PQ tracker has spazzed out on the SS but it was working fine before that):

![axerustpeak](https://cloud.githubusercontent.com/assets/5108812/20526615/17fcba6e-b0c5-11e6-925e-aea4592b7b30.jpg)

**Comment by Soulwhisper** [comment]
Im pretty sure that it has something to do with unlocks on Chapters...Tested with my Slayer and PQ tracker works fine.Bar appears too but shows Ch9.

**Comment by wargrimnir** [comment]
Fixed in next patch.
