### ISSUE TITLE
ToK unlock 'Vaulkor'

### ISSUE THREAD

**Issue by Sapphiratelaemara** [WarEmu/WarBugs#8419]
Norsca Chapter 1 kill collector does not provide his unlock.
![image](https://cloud.githubusercontent.com/assets/23622177/20508179/15c55ad6-b060-11e6-9395-7c5fbd8b3659.png)

**Comment by Lheana** [comment]
Not fixable now ? Just need to talk to kill collector.

**Comment by Lheana** [comment]
Maybe reopen it ? :)

**Comment by Luth-RoR** [comment]
Forgot it 😀
