### ISSUE TITLE
Respecialization cost not showing

### ISSUE THREAD

**Issue by xyeppp** [WarEmu/WarBugs#842]
Very minor visual with the cost of respec not showing - it showed 80s when I was still at 4 points but does not show me 1 gold when at max lvl and 5 points.

![github_008](https://cloud.githubusercontent.com/assets/12982209/8345113/831c39b6-1ae2-11e5-96d3-8df2953c4a43.jpg)

**Comment by Evildoor** [comment]
Problem still persists?

**Comment by Evildoor** [comment]
No response, closing.
