### ISSUE TITLE
ToK unlock 'The Order of the Griffin' (Order)

### ISSUE THREAD

**Issue by Sapphiratelaemara** [WarEmu/WarBugs#8424]
Unlock should trigger upon talking to any NPC with Griffon in their name; presumably exist all over the world but first encountered in Nordland.

**Comment by Lheana** [comment]
If that's really talking to a NPC, it can be fixed.

**Comment by Ryanfawkez** [comment]
It'd count for all NPCs. Original unlock mandates NPCs at the start should give it.

**Comment by PeskyGobbos** [comment]
This bug still exists, any update?
