### ISSUE TITLE
ToK unlock 'Militia' (order)

### ISSUE THREAD

**Issue by Sapphiratelaemara** [WarEmu/WarBugs#8425]
Does not trigger at location.
![image](https://cloud.githubusercontent.com/assets/23622177/20509127/d2cbdaa0-b066-11e6-9a24-837b28753237.png)

**Comment by Lheana** [comment]
According to http://rift.zam.com/wiki/Militia_%28WAR_History_and_Lore%29 this is not a proximity unlock. This unlock should be triggered by talking to 'Jakob Hebel' (27.5k 51.2k) during the quest 'A Son's Sacrifice' in Nordland.

**Comment by Ryanfawkez** [comment]
Rally all conscripts fit for duty...
