### ISSUE TITLE
ToK unlock 'Superstition'(Order)

### ISSUE THREAD

**Issue by Sapphiratelaemara** [WarEmu/WarBugs#8427]
Should trigger upon entering Inn; can probably be tied to the interactive door object.
![image](https://cloud.githubusercontent.com/assets/23622177/20509206/5ef9906c-b067-11e6-8288-49d63573c69d.png)

**Comment by Lheana** [comment]
Fixable if interacting with the door 'Empire Bar Door' of the Grimmenhagen Inn, provides the unlock.

**Comment by Ryanfawkez** [comment]
An astute observation! <3
