### ISSUE TITLE
ToK unlock 'Isolated Settlements' (Order?)

### ISSUE THREAD

**Issue by Sapphiratelaemara** [WarEmu/WarBugs#8428]
Does not display on screen when interacting with corpse but unlocks in tome. Seem to recall it displaying yesterday when I snuck in with my Destro character.
![image](https://cloud.githubusercontent.com/assets/23622177/20509248/a50696ae-b067-11e6-8f0d-6233fc52f0f5.png)

**Comment by Lheana** [comment]
#8422
