### ISSUE TITLE
Frightened Citizen (Empire chapter 3)

### ISSUE THREAD

**Issue by Sapphiratelaemara** [WarEmu/WarBugs#8432]
NPC at 
![image](https://cloud.githubusercontent.com/assets/23622177/20512089/5ec373e0-b07d-11e6-936d-cc0f9a904181.png) gives the Stirring Up Trouble achievement. Should actually give Troubling Indeed under the Stirring Up Trouble category.

**Comment by Ryanfawkez** [comment]
http://warhammeronline.wikia.com/wiki/Stirring_Up_Trouble - Frightened Citizen.
http://warhammeronline.wikia.com/wiki/Troubling_Indeed - Frightened Peasant.

**Comment by Sapphiratelaemara** [comment]
Yeah sorry I expressed that badly. He's in the wrong town; the NPC that should be in that location is Frightened Peasant while the citizen should be in Grimmhagen
