### ISSUE TITLE
[Halloween Event] Warboars still drop Cloven Hof

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#8435]
As the title says, the Warboars still drop the quest item Cloven Hof and are therefore very work intensive to farm, as Cloven hof doesnt stack and simply clotter my Quest Bag.

Is this intentional?
Can this be deactivated?

I'm currently at 20.889 Boars, and I will die if I need to remove 79111 Cloven Hofs singlehandidly from my inventory one by one. ;)

**Comment by Luth-RoR** [comment]
Known issue https://github.com/WarEmu/WarBugs/issues/8289
