### ISSUE TITLE
'Very Large Telescope' object missing

### ISSUE THREAD

**Issue by Sapphiratelaemara** [WarEmu/WarBugs#8437]
Should be on top of a stone wall 
![image](https://cloud.githubusercontent.com/assets/23622177/20515903/f655c968-b093-11e6-85ac-a9977c243d0d.png) in Troll country to provide ToK Unlock 'Mannslieb and Morrslieb'
Location
![image](https://cloud.githubusercontent.com/assets/23622177/20515941/2aa6c33e-b094-11e6-8ebb-e7f2dbf58526.png)

**Comment by Ryanfawkez** [comment]
It ain't missing; I moved it up on a stone tower you can access by a jumping puzzle I've created in Felde.

**Comment by Lheana** [comment]
But interacting with it does not provide unlock

**Comment by d3BugErr** [comment]
No unlock upon interacting, yes.

**Comment by Luth-RoR** [comment]
I forgot to reopen this.

**Comment by Ryanfawkez** [comment]
Removed jumping puzzle, added teleport. Unlock should work.
