### ISSUE TITLE
ToK 'Soulblight Stone'

### ISSUE THREAD

**Issue by Sapphiratelaemara** [WarEmu/WarBugs#8443]
Clicking object 'Dead Marauder' does not provide unlock.
![image](https://cloud.githubusercontent.com/assets/23622177/20518350/2b4509bc-b09f-11e6-96da-f461e407c7bb.png)

**Comment by Lheana** [comment]
Interacting with the Dead Marauder still does not give the unlock, despite the patch.

**Comment by Lheana** [comment]
Is it normal it has been closed even if the patch did not fix this unlock ?

**Comment by Luth-RoR** [comment]
No, maybe it was fixed again and is now back due to database errors.

**Comment by Lheana** [comment]
Still not working

**Comment by Ryanfawkez** [comment]
There's a bunch of Dead Marauder gameobjects. One of them has it.

**Comment by Lheana** [comment]
In real the object is called 'Dead Maurauder', maybe there are less ?

**Comment by Ryanfawkez** [comment]
Gameobject renamed to Slain Marauder, ToK unlock added,
