### ISSUE TITLE
Champions, Heros & Lord without corpse

### ISSUE THREAD

**Issue by willowi** [WarEmu/WarBugs#8449]
Farmed low level gear in order t2 public quest to level up magical salvaging. Noticed that last mobs just before next stage of public quest wont leave corpse/loot behind. And last stage is that chest so boss mob at the end doesnt leave corpse to loot or scavenge for. Not sure is this problem in every PQ in game or is it meant to be that way. Think not.

**Comment by Luth-RoR** [comment]
When a PQ step is done, all mobs are cleared. This is intended.
