### ISSUE TITLE
WP Book provides fury regardless of prayer

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#8452]
EDIT:The fury regeneration seems to be bugged on the book. It works regardless of the stance. This means you have 16 fury reg in backline mode (with no enemies around) and 8 in melee heal.

If this is intentional then I'm sorry but I didn't read anything in the patch notes regarding this.

**Comment by Cimbas** [comment]
Apprently this started yesterday evening as far as we know.

**Comment by Blaqwar** [comment]
Confirming this for Chalices as well. In combat SE regen with a chalice is 8 SE/sec without players nearby (at least 375 feet when the morale scaler should activate). 16 SE/sec with Covenant of Tenacity and a chalice.

**Comment by ozarmidrashim** [comment]
Dealt with
