### ISSUE TITLE
[Scenarios] Auto-shutdown of SC due to player imbalance failing to occur

### ISSUE THREAD

**Issue by Vandorkholme** [WarEmu/WarBugs#8453]
see title

Scenarios very rarely, if ever close down due to a pop imbalance lately.

Just one such example: 9v12 http://i.imgur.com/aEvRWxV.jpg

**Comment by Luth-RoR** [comment]
It doesn't work like that on ROR; instead the scenario should be over way faster, with a win for the dominating side; the player imbalance was caused by players of the own realm who didn't join, a shutdown would punish the other side who joined the scenario as intended.
