### ISSUE TITLE
Missing NPC 'The Herald' and ToK unlocks

### ISSUE THREAD

**Issue by Sapphiratelaemara** [WarEmu/WarBugs#8456]
NPC 'The Herald' missing at loc
![image](https://cloud.githubusercontent.com/assets/23622177/20559659/f4c9b694-b175-11e6-9a26-409d6131b47f.png)
Hostile to order, friendly to Destruction then hostile after clicking.

Gives unlock 'The Herald' when killed, also summons two 'Minion of Flame' horror-type demons which give unlock 'Wandering Alone' when killed.

Heralds loot consists of an object called 'Profane Writ' that provides unlock 'Carrying His Word' when used in inventory.

**Comment by Lheana** [comment]
The last part 'Carrying His Word' can not be made by destro side : The Herald does not become hostile after clicking. He gives the unlock 'The Herald' when interacting with, but can not attack him, and does not give the item for 'Carrying His Word'. (Order can complete all parts)

**Comment by Lheana** [comment]
Even after the patch, destro can not complete the whole pursuit : "The last part 'Carrying His Word' can not be made by destro side : The Herald does not become hostile after clicking. He gives the unlock 'The Herald' when interacting with, but can not attack him, and does not give the item for 'Carrying His Word'. (Order can complete all parts)"

**Comment by Luth-RoR** [comment]
I don't know if _friendly NPCs turning hostile_ after interaction is supported atm.

**Comment by Ryanfawkez** [comment]
Made The Herald hostile to all.
