### ISSUE TITLE
Skeleton Horses twitching on the ground

### ISSUE THREAD

**Issue by Sapphiratelaemara** [WarEmu/WarBugs#8459]
location 
![image](https://cloud.githubusercontent.com/assets/23622177/20561312/4e9d47d2-b17e-11e6-8ac4-ec9d3d9c898e.png) has a bunch of them laying on their sides doing a 'sleeping dog' kinda running animation.
Going out on a limb here and guessing that's not intended behavior.

**Comment by Ryanfawkez** [comment]
It is intended behavior ;)
