### ISSUE TITLE
"Priceless" quest, Eataine zone, Order

### ISSUE THREAD

**Issue by banned85** [WarEmu/WarBugs#8461]
in this quest you must grab the "eataine promise", i see this object (its a green bush) but when i click on it then nothing happens, i just cant "interact" with the object, please fix it, thanks in advance

**Comment by Blaqwar** [comment]
Doesn't work for me either (it worked 1-2 patches ago).

![hathol_009](https://cloud.githubusercontent.com/assets/5108812/20598999/1dacab8a-b24c-11e6-88cb-0227a413d3db.jpg)
