### ISSUE TITLE
ToK 'Feiten's Lock'

### ISSUE THREAD

**Issue by Sapphiratelaemara** [WarEmu/WarBugs#8463]
Should proximity unlock when passing through gate at
![image](https://cloud.githubusercontent.com/assets/23622177/20565489/07ff87f4-b192-11e6-8dc1-24f66d50b244.png)

**Comment by Lheana** [comment]
According to official server, this unlock should be linked to the door at 40k 64k in High Pass, not the door of the BO Feiten's Lock (see Sapphira's ss).
