### ISSUE TITLE
Character Login: Character Broken by Guild Bank?

### ISSUE THREAD

**Issue by Loneminecrafter** [WarEmu/WarBugs#8469]
I've had this issue for... A few months now; sometime before the DDOS attack.
My character 'Reticence' has since been unable to log in; even after server restarts and the DDOS issue.

TL;DR: Character broke while organising our guild bank (back and forth right clicking).
Looks like maybe a database issue to me?
Don't care if character makes it out alive, this is WAR! Nobody ever makes it out alive.

I've attempted as many potential fixes as I've heard and could think of:
1. /stuck twice while loading.
2. Have a Game Master re-spawn me/teleport me someplace else.
3. Move the character's GUI profile out of the loading directory.
4. Launch from another computer.
5. `assert < 100 guild_members: pass`

What I can remember: (Times approximate.)
-  T+0:00 Flew into The Inevitable City.
-  T+1:00 Opened the guild bank.
-  T+1:10 Began organising the messy guild bank.
(Was right clicking items back and forth between bank and player inventories.  Probably what caused the break.)
-  T+2:00 Game crashed.
-  T+2:20 Attempted to login again.
-  T+2:22 Loading screen comes up.
-  T+2:52 Loading screen finishes.
-  T+2:53 GUI loads.
-  T+2:53 Loaded into an empty grey world with the title "Inevitable City".
-  T+2:53 Game crashed.

The last two packets received before the crash packet were of the types:
-  [Server] packet : (0x95) UNKNOWN  Size = 20 
(Unintelligible.)
-  [Server] packet : (0xAA) F_GET_ITEM  Size = 1456
(A bunch of Talismans, several pieces of armour, and a weapon.)

So this makes me think it _may_ be a database issue?
(Note: I don't actually have any experience, and little to no knowledge of databases;
Or how any of this really works.)

Now having another Witch Elf at almost the same level; I don't care much about this one anymore, so it wouldn't bother me too much if it stays broken or gets deleted.
Just figured you guys'd like to know there's a broken character out there, with a possible bug.

**Comment by Luth-RoR** [comment]
>Character broke while messing with a guild bank.

What does that mean?

**Comment by Loneminecrafter** [comment]
I had both my inventory and the guild bank open, and was repeatedly right clicking items back and forth between the guild bank and my inventory.

I.E. Right click multiple items in the bank to move them to the player, then right click those same items from the player to move to first open slot in bank.

**Comment by Luth-RoR** [comment]
Ok thanks, unfortunately the character can't be restored.
