### ISSUE TITLE
Respawn points jumbled up for PQ's in Eatine.

### ISSUE THREAD

**Issue by Earthpacu** [WarEmu/WarBugs#8470]
The respawn points for public quests in High elf ch15 & 16 seem jumbled up. Dying in the ch15 PQ's you respawn at the ch16 settlement and dying in the ch16 PQ's resapwns you in ch15. I've only tested this with the functional PQ's in these chapters which are "The Tower of Lysean" in ch16 and "Da Orcwerks" in ch15.

**Comment by Soulwhisper** [comment]
#7259 
#8312

**Comment by Luth-RoR** [comment]
Closing then.
