### ISSUE TITLE
inventory cycling through items, creating a ton of lag for user

### ISSUE THREAD

**Issue by RevMalthus** [WarEmu/WarBugs#8471]
Hey all, created a video to show you what I mean - 

I keep getting a message "item move failed attempted to move 20 of the item (X) while only having 1."

creates a ton of lag for me- stops between 5 and 20 minutes after I log in - not sure whats going on

created a video so that you can see what I mean 

http://sendvid.com/e8wv0077

**Comment by Luth-RoR** [comment]
Yes that's known, but there is no solution for it yet. https://github.com/WarEmu/WarBugs/issues/2427
