### ISSUE TITLE
ToK 'Urun'

### ISSUE THREAD

**Issue by Sapphiratelaemara** [WarEmu/WarBugs#8474]
Rally master does not provide his unlock
![image](https://cloud.githubusercontent.com/assets/23622177/20599119/cd05baae-b24c-11e6-97b8-f302ce912814.png)

**Comment by Ryanfawkez** [comment]
I love all the reports you've been making thus far; that Map Monster addon seems incredibly handy for locating missing ToK unlocks. Is there any way you could share this addon, so the team can go over each missing unlock that may or may not be able to be fixed?

**Comment by Sapphiratelaemara** [comment]
Sure! The addon doesn't actually contain any notes though, I've been adding
them all by hand and then inspecting them so I've only had time to do a few
zones so far; I'd be happy to upload the text file somewhere though!
