### ISSUE TITLE
[Shaman] I'll take that  dmg not right

### ISSUE THREAD

**Issue by Freki123** [WarEmu/WarBugs#8475]
Hi the skill  "I'll take that" in my tooltip states it does 428 dmg. In a duel it does 225 (74) mitigated, Thats not nearly 428. Also shoudnt it deal 25% more on players in experimental mode?
![1](https://cloud.githubusercontent.com/assets/19626877/20603336/6569b62e-b261-11e6-97b7-4d87365e96e1.jpg)
![2](https://cloud.githubusercontent.com/assets/19626877/20603337/656bcb76-b261-11e6-9f6d-83fc985d3c0a.jpg)
You#z squishy i coudnt even land one hit on him. Tried 15 times atleast even when there are only few shown on the screenshot. So out of 15 tries atleast 3 or so should hit

**Comment by ozarmidrashim** [comment]
Failure to understand experimental mode
