### ISSUE TITLE
Scenario issue (could be abused)

### ISSUE THREAD

**Issue by Aliasbe** [WarEmu/WarBugs#8477]
Hi,

First, sorry for my bad english, I do my best and I play in french version of the game.

The scenario is "passage du serpent" in french and I guess english name should be snake pass or something like that.  That's the one with the salvage part and the ships.

Here is the bug that could be abused : 

When you have the salvage part, go to your cart, click, wait half a second to launch the loading time and move during the loading time of the "salvage part validation" to interrupt it.  

The game counts the points and the message appears... but you keep the salvage part.  Do it again and again and you have the points each time.  It could occurs at least 3 times with one salvage part.  Maybe more, I didn't test to do it 4 or 5 times but it should be possible.

Tested 3 times and it worked each time.  I think that I could probably win the sc with only one salvage part when using this abuse.

**Comment by Luth-RoR** [comment]
Hi, this is known already: https://github.com/WarEmu/WarBugs/issues/7783
