### ISSUE TITLE
[Item] T4 Epic Quest item: The Fixer 2h Spanner doesn't activate it's bonus damage

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#8478]
Hello I asked meself today when the t4 items activate their extra Damage Bonus. Better said on what abilities at the Enginee.

So I tested the t4 Epic Quest item: "The Fixer" It is the lovely 2h Spanner.
![lesti_476](https://cloud.githubusercontent.com/assets/14627932/20620255/20d9d91a-b2f9-11e6-9f22-c3a33364a815.jpg)

It bonus damage says: Judgement IX:
I have removed my rifle and then hit 200 times Mobs in the Chaos Waste with the Ability "Spanner Swipe"
It is the Engineers close combat attack and if I remove the Spanner it is getting grey. So this ability should activate the bonus damage.

But in the combat log I didnt find any of the mentioned spirit damage that should be dealt to the target. 
Only my damage of the spanner swipe and critical hits of the  spanner swipe.

Countertest:
I equiped the T4 epic pistol "Revenge" It has also a bonus damage, but a dot.
When the dot is activated I see it in the combat log, when it does damage to the target.
Also the source of the damage is labeled as: Agony XI, which is the extra damage dot of the pistol.

**Comment by Luth-RoR** [comment]
I couldn't reproduce it on the dev server. With only the spanner equipped on AA + ability hits; it procced the item damage from AA and also abilities (spanner swipe):

![luthengi_003_crop](https://cloud.githubusercontent.com/assets/8567481/20631816/199413a6-b339-11e6-84a2-fab95e487612.jpg)
