### ISSUE TITLE
Missing Mail to one character.

### ISSUE THREAD

**Issue by GreatHarlequin** [WarEmu/WarBugs#848]
Whenever I send mail to one of my alts, the mails disappear and never arrive. I make sure I enter their name correctly.

Character = LESSEI

**Comment by Thorgatin** [comment]
Mails are working unreliable atm. Known issue.

**Comment by Evildoor** [comment]
Hmmm. Have you logged onto that alt at least once? Or just created the character without logging on them, and send mail to them?

**Comment by GreatHarlequin** [comment]
This was an old bug that no longer occurs. Safe to close from my end.
