### ISSUE TITLE
ToK 'Appalling Fashion' (Destruction)

### ISSUE THREAD

**Issue by Sapphiratelaemara** [WarEmu/WarBugs#8480]
Hostile NPC Witch Hunter Adept (level 9 champ) missing at loc
![image](https://cloud.githubusercontent.com/assets/23622177/20628807/788adaa4-b328-11e6-9970-2f373b02f97e.png)
Drops 'Grisly Necklace' which provides unlock.

Grisly Necklace also fails to provide unlock when interacted with.

**Comment by poutpoutt** [comment]
Hostile NPC Witch Hunter Adept (level 9 champ) is at 48k, 42k (double spawn, even).

But killing this NPC doesn't drop 'Grisly Necklace' for the unlock. Neither does Casimir Por who is close by and should give the necklace after you've killed the witch hunter adept.

**Comment by Lheana** [comment]
Can not loot 'Grisly Necklace' on Witch Hunter Adept, but Bestigors not far from him drop this item. Nevertheless, Grisly Necklace does not provide the unlock 'Appalling Fashion'.

**Comment by poutpoutt** [comment]
Really?
According to the topic for TOK on ror site, I thought it would : 

Beastman, Bestigor - Appalling Fashion
CHAOS TOME TACTIC
(O) TALABECLAND @ 48.5, 39. Head to the Blackhorn Heardstone. Kill them to receive a Grisly Necklace. Beastman Bestigors have the best droprate. Right click it for the unlock.
(D) TALABECLAND @ 55, 35 or 48, 42. Confirmed at 1st coords by right clicking Casimir Por in the Beastman area E of the Herdstone. At 2nd coords, killing blow the L9 champ Witch Hunter Adept and he will give you the necklace that you click on for the unlock.
By Blodsalv, armorum, Archaides, Kellithe & Shaz
20081124

**Comment by Lheana** [comment]
Half fixed: Made of Grisly Necklace a pocket item, equip it for the unlock. Witch hunter adept does not drop this item yet.

**Comment by Lheana** [comment]
Totally fixed: Witch Hunter Adept will now drop 'Grisly Necklace'.
