### ISSUE TITLE
quest:  keeping secrets

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#8484]
this t3 quest says to search the "wood choppaz camp" bo in Avelorn for a npc named "Moenar Karinth"; in the highlited area showed on the map there's only a npc and it's named "Maneus Seren".

**Comment by Natherul** [comment]
first part of quest will be fixed in the next update, dont think we can fix the rest of the chain currently however...

**Comment by Natherul** [comment]
revisited this ticket and addressed it so that the entire quest chain is now possible.
