### ISSUE TITLE
Tactic: Intimidating Repent

### ISSUE THREAD

**Issue by KyleSaysThings** [WarEmu/WarBugs#8487]
Experimental change added AoE Repent with Devotion Prayer on 25s CD.

When using the Intimidating Repent tactic from the Wrath tree the CD for Repent in Devotion remains at 25s, despite it being 15s when used while running one of the other 2 Prayers.

Not sure if intended or not.

**Comment by ozarmidrashim** [comment]
intentional. could be considered as tweak
