### ISSUE TITLE
Warrior Priest, Exalted Defenses tactic, change weapons, willpower->disrupt.

### ISSUE THREAD

**Issue by Emegale** [WarEmu/WarBugs#8489]
I think dont work **Exalted Defenses**, after triggering this tactic I hung up on self hot and there was no change.
If you change weapons, lost **Prayers** and **Sigmar's Grace**
Bonuses of **disrupt** do not depend on **willpower**

**Comment by Luth-RoR** [comment]
One bug per report, please check the bugtracker rules.

1. Exalted defenses works correctly; i don't know how you checked this (no evidence posted -> bugtracker rules)
2. Known issue (search function -> bugtracker rules)
3. Paperdoll issue, also known (search function...)
