### ISSUE TITLE
[NPC][Quest] Quest auto complete

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#849]
Interact with NPC -> Open finished quest -> Move out of NPC interaction range -> Quest complete
In this case if quest has more than one reward you'll get nothing.

**Comment by sioding** [comment]
Checked - and still an issue.

**Comment by Lheana** [comment]
Tip: You can avoid it by talking to another NPC nearby before leaving from the quest NPC

**Comment by MaxHayman** [comment]
Fixed in next patch

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
