### ISSUE TITLE
being mooned for no reason 

### ISSUE THREAD

**Issue by lawfol** [WarEmu/WarBugs#8490]
I was told by azarael himsefl to use this way to appeal to get un-mooned...think using ban apeal would not be appropiate too,as it is a 24h moon.

I was banned with system message to have abused the advice channel to get an invite. I typed last "t+" actually.
My line beofre was "emporarily" and I wanted to add an "t" to that....so making it "temporarily2

I was always in a wb with arthur,the leader of the Bitterstones,so plainly not even close to find a group anyways.

Thank you in advance and I hope I get released soon.

**Comment by ozarmidrashim** [comment]
I didn't tell you to use the bugtracker at all, sorry

**Comment by lawfol** [comment]
lots of missreads than. Thanks for the time and effort...and take a deep breath 🗡

**Comment by Luth-RoR** [comment]
>and take a deep breath 🗡

What?
