### ISSUE TITLE
Choppa: Requires Great Weapon bug

### ISSUE THREAD

**Issue by Firstofone** [WarEmu/WarBugs#8492]
Both of the Choppa Requires Great Weapon ability's are bugged. They are Tired Already? and Weakling killa. 
When the ability(s) should be ready to fire, they remain greyed out like you don't great have a weapon equipped or you don't have enough career resource built up. however they DO fire when the button is pressed. However an error pop ups up on screen "This Ability requires great weapon". Also they remain greyed out and missing the visual queue of them lighting up is affecting my play more than i care to admit.

Edit I am not exactly sure how long this has been this way, it may have started when Az adjusted the cooldown on Weakling killa last week, however that is just a guess.

**Comment by Luth-RoR** [comment]
Both abilities work fine with an equipped 2h weapon on the dev server. It seems like the client doesn't realize that you have a 2h weapon equipped, though the server does. Maybe just you equipped weapon is bugged. What's the name of the weapon?

**Comment by Firstofone** [comment]
Vanguard Bigchoppa of the Fighter.

I will try a different 2 hander and see

**Comment by Firstofone** [comment]
OK, you were right.
But It is (all?)the renown 2 handed axes that are bugged. I used a few I bought off the renown vendor and they all did the same thing. I bought a cheap one off the AH and it was fixed.

**Comment by Luth-RoR** [comment]
I tested the slayer 2h axes, but everything works fine here.

**Comment by Blaqwar** [comment]
This issue occurs for Black Orcs as well. At least with a vendor bought Fighter's Bigchoppa of Vengeance - when using Da Big Un' the ability is greyed out (in the correct stance, wielding a greatweapon), it still fires on using it but displays the "Requires Great Weapon" error.

You seem to be correct in thinking Orc greatweapons are bugged in this regard.

**Comment by Luth-RoR** [comment]
Yes, the axes are not restricted to choppas; though Ryan already fixed it. Should go live with the next patch.
