### ISSUE TITLE
Hard public quest in Inevitable City not work

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#8496]
There was hard Public quest in IC for 38-40 lvl players, to activate it you should interact with this skull:
![arena_161](https://cloud.githubusercontent.com/assets/18102127/20644179/d02779ac-b445-11e6-9d1c-8a1a38aff600.jpg)
After that spawn creature appears. On 1st stage it is small (literaly) and have regular mob status. After you kill it it reappears with bigger size and with higher level, then with champion status, then with hero status, then with hero status and higher level, and in the end it appears with Lord status. All the time when it reappears it grows in size.
Here is invisible chest with rewards from this PQ:
![arena_162](https://cloud.githubusercontent.com/assets/18102127/20644195/482c3e6a-b446-11e6-8d32-4cad7a87e8ce.jpg)
and here is the creature itself:
![arena_163](https://cloud.githubusercontent.com/assets/18102127/20644198/5d02c11a-b446-11e6-9ebe-b83ea9db7c8a.jpg)
Was really hard PQ even for those who wearing sovereign.

**Comment by Luth-RoR** [comment]
Not implemented yet; will be reopened once it is.
