### ISSUE TITLE
Easy public quest in Inevitable City not work

### ISSUE THREAD

**Issue by Yellowpillow** [WarEmu/WarBugs#8498]
There was easy PQ in IC for 12-14 lvl players.
It starts here:
![arena_164](https://cloud.githubusercontent.com/assets/18102127/20644223/14fd15cc-b447-11e6-89a6-16d3ad04e2c9.jpg)
After killing few mobs counter appeared. After killing about 20 scared souls you should go into the temple, where another mobs waiting you (8 to kill as i remember, and few regular just to make it harder to complete). On 3rd final stage magus with champion status shows up, i believe this is him:
![arena_165](https://cloud.githubusercontent.com/assets/18102127/20644237/7613e368-b447-11e6-826f-3671cc8ca2aa.jpg)
After that chest drops outside the temple, because inside was too much mobs at a time.

**Comment by Luth-RoR** [comment]
Not implemented yet; will be reopened once it is.
