### ISSUE TITLE
the great oathstone set

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#8501]
set bonus is bugged, the tooltip instead reduces attack speed sum a+15 over your existing attack speed  so basically i get show  that i have 18,4 sec for make an auto attack, anyway it's jsut visual there is not effect at all, 

idk the live implementaion of course it should be a buff not a debuff to your attack speed,  idk if it was to mean a 15% reduction or a 1.5 reduction (very huge)/ or it was even bugged since there.

**Comment by Luth-RoR** [comment]
Known issue: https://github.com/WarEmu/WarBugs/issues/6380
