### ISSUE TITLE
ToK 'X Marks the Spot'

### ISSUE THREAD

**Issue by Sapphiratelaemara** [WarEmu/WarBugs#8502]
Keg of bugmans at 
![image](https://cloud.githubusercontent.com/assets/23622177/20644772/6899b7b2-b442-11e6-85e1-b54b027724e9.png)

 does not provide unlock

**Comment by Sapphiratelaemara** [comment]
There's also one at about 
![image](https://cloud.githubusercontent.com/assets/23622177/20644779/c802a736-b442-11e6-8a17-d441b08c4772.png), dwarf chapter 18

**Comment by Ryanfawkez** [comment]
There's a keg of Bugman's XXXXXX that will give you the unlock. the other kegs are either bugged or part of a quest.

**Comment by Sapphiratelaemara** [comment]
Aah, I was under the impression that it's there for Destruction players since getting to the order camp one seems to be impossible even with a player distracting the guards :)

**Comment by Ryanfawkez** [comment]
Yeah; I cranked up the security there; back on live Destro had to get the unlock at the same spot. I added a second barrel now, outside of the keep ;)
