### ISSUE TITLE
nordenwatch/orvr mashup

### ISSUE THREAD

**Issue by MightyPhred** [WarEmu/WarBugs#8505]
i just joined a nordenwatch scenario pop, when i loaded in i was given the quitter debuff, and the scenario was treated as if it was an ordinary open rvr zone, i had no party interface, scenario score/objective tracker, i stacked battle fatigue when i died, and according to a runepriest i spoke to briefly i was not contributing to objective captures (as can be seen in the screenshots i am very clearly in the nordenwatch map, but i have both battle fatigue and quitter!, which shouldnt be possible), when the scenario ended i received no reward and i had to get out using my book of binding
![dsparill_002](https://cloud.githubusercontent.com/assets/16922842/20646656/b20a5530-b476-11e6-8f28-5c365efed37e.jpg)
![dsparill_003](https://cloud.githubusercontent.com/assets/16922842/20646658/c6dcb17e-b476-11e6-8d1c-d8bb31d0d94f.jpg)

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/8059
