### ISSUE TITLE
Praag Southern Keep Doors

### ISSUE THREAD

**Issue by sshabel** [WarEmu/WarBugs#8506]
The Southern Keep doors wouldn't repair and we ranked the keep up to rank 2. We also never got a defense tick.

**Comment by Luth-RoR** [comment]
It seems that there was a fix on the northern keep: https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=18596&start=40#p202333
Maybe the southern keep has been fixed to.

**Comment by Luth-RoR** [comment]
Seems like it was the southern keep: https://github.com/WarEmu/WarBugs/issues/8497 😕 
Closing then.
