### ISSUE TITLE
Cultivating:  Scrubby Thief's Nettle 175 - Crit to different item

### ISSUE THREAD

**Issue by wpc56** [WarEmu/WarBugs#8507]
Scrubby Thief's Nettle level 175 seed for ballistic skill critical to Smoking Pyre Ivy, a level 1 mototov potion.  

175 balistic cultivating should critical to a 200 balistic seed

**Comment by Luth-RoR** [comment]
Known issue: https://github.com/WarEmu/WarBugs/issues/5402
