### ISSUE TITLE
chosen combat stance broken

### ISSUE THREAD

**Issue by RevMalthus** [WarEmu/WarBugs#8508]
it appears that when you right click a combat target in game the chosen class does not go into a "combat stance" like the kotbs, etc.

its aesthetic for sure but annoying

**Comment by Luth-RoR** [comment]
Works for me with S&B and 2H sword equipped on the dev server. Do you have a 2H axe equipped?

**Comment by sioding** [comment]
No answer since 28.11.2016 - close for now.
