### ISSUE TITLE
Impassable mob in Tier 3 Destruction Leveling Zone.

### ISSUE THREAD

**Issue by methority** [WarEmu/WarBugs#8509]
There is that hero-mob atop of Tower of the Fallen, Talabecland, who can't get beaten even by 39 Chosen with a shield, and it aggro-assaults through the textures on every player who tries to get objectives for two different quests which are not even meant to be hopeless suicidal.

**Comment by Luth-RoR** [comment]
A screenshot and generally a more specific description would help.
