### ISSUE TITLE
Bloody Savages - Public Quest Dwarf Chapter 14 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#8512]
- [x] On Stage 1 need to put more Slashas.They are about half of the Hackas number.And it feels very slow to get Slashas.Tested with party.
- [x] On stage 2 cant interact with torches.
![warhammer online age of reckoning 11 29 2016 - 21 20 08 01](https://cloud.githubusercontent.com/assets/16864486/20727217/525c4b7c-b681-11e6-93a7-fa82ee2e81e7.png)

**Comment by Razielhell** [comment]
This Hacka doesnt count in PQ.
![warhammer online age of reckoning 03 31 2017 - 01 02 44 114](https://cloud.githubusercontent.com/assets/16864486/24528106/c72d2d28-15ad-11e7-9e1e-311e664fdd5e.png)

**Comment by dansarii** [comment]
Confirming torches still untargetable and a few more Slashas would make the QOL for the PQ better.

**Comment by grunbag** [comment]
added more slasha to stage I, stage II works fine, torch got the usual visual bug and count as kruncha's,

**Comment by Razielhell** [comment]
@grunbag It works fine on Dev server. On live you can't click on the torches.

**Comment by grunbag** [comment]
Ok I'll change the entry for one that work for non dev account .

**Comment by grunbag** [comment]
@Razielhell the is only 2 torch that don't work on live server (and i dont know why. i don't want to touch them to not break it all)
![skori_301](https://cloud.githubusercontent.com/assets/24207191/26616169/e8982f04-45cc-11e7-9545-16dca90bd740.jpg)
![skori_302](https://cloud.githubusercontent.com/assets/24207191/26616175/f1d976ea-45cc-11e7-9449-7859f682ac72.jpg)
![skori_303](https://cloud.githubusercontent.com/assets/24207191/26616178/fbbbb290-45cc-11e7-856a-d1239892bc0b.jpg)
![skori_304](https://cloud.githubusercontent.com/assets/24207191/26616186/080fe4bc-45cd-11e7-9b57-72a95993a91d.jpg)
![skori_305](https://cloud.githubusercontent.com/assets/24207191/26616193/118e8296-45cd-11e7-9119-913ada64254c.jpg)
