### ISSUE TITLE
Black Orc Slog - Easy Public Quest Dwarf Chapter 14

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#8513]
- [x] Bloody Sun Overseers need to be downgraded.
![warhammer online age of reckoning 11 29 2016 - 21 27 23 02](https://cloud.githubusercontent.com/assets/16864486/20727309/a3bbe090-b681-11e6-9a21-5448702af31f.png)

**Comment by Natherul** [comment]
should be fixed in the next push
