### ISSUE TITLE
[Shaman] Get'n Smarter not affected by intelligence

### ISSUE THREAD

**Issue by jonomurphy** [WarEmu/WarBugs#8516]
The new Shaman DoT, 'Get'n Smarter', does not seem to be affected by intelligence as it is hitting for very low amounts in comparison to the other dots (and despite being on a shorter duration than one)

https://s22.postimg.org/5c32bp9gh/Section_004.jpg

https://s16.postimg.org/8qpf9muv9/Section_005.jpg

**Comment by jonomurphy** [comment]
In retrospect: some of the crits seem to be in line with Life Leaka, but the average damage/minimum ticks don't.

**Comment by Blaqwar** [comment]
If your claim is that it's not scaling with intelligence then the best way to prove that would be to showcase how much damage it does with no intelligence gear/renown vs normal intelligence gear/renown.

**Comment by Luth-RoR** [comment]
Nvm, just tested it; it hits for the same damage with 196 and 224 intelligence.

**Comment by ozarmidrashim** [comment]
fixed.
