### ISSUE TITLE
Not sure Kaboom Squigh herder ability is working as intended

### ISSUE THREAD

**Issue by rbugsearchpla** [WarEmu/WarBugs#8517]
Looking at this vid about a original server squig herder gameplay lvl 100, i noticed the Kaboom's jump animation is not triggering with the ability use, the ability in the video shows it is only doing knowback on the enemy but the Squig Herder player himself doesn't jump as it is doing in return of reckoning, giving him more time for run out of attackers and higher chances of survive than it does in return of reckoning, because you don't  lose any time in a jump which stay exactly at same spot.

Look at minute 1:06 and minute 4:31, he use the kaboom ability, you can even select the video reproduction speed 0,25 in youtube and shows exactly how the SH is not jumping, and he is only kicking the enemy away

[https://www.youtube.com/watch?v=AcNHwWDJKmA](url)

(i don't know why clicking on link doesn't work, but if you copy and paste link in browser will send you to youtube video and you will see how kaboom was in original server, in the end of times)

**Comment by Luth-RoR** [comment]
On 1:06 the SH had "Immovable" immunity, which means that on the mythic server he didn't jump upwards _with running immunity_ when using the ability.
On 4:31 he jumped upwards about one second later (no immovable immunity), high likely due to lag.

**Comment by rbugsearchpla** [comment]
Don't know, never played Squigh herder in live, Chaoselfa appear in last part of video grouped with him, maybe we can ask him if he remembers Kaboom beign reworked to make Squig Herder not jump.

Honestly the second i lose on jumps, killed me more times than saved me, i think is a lost time and makes more sense like it shows in video.

Will keep searching info about it

**Comment by rbugsearchpla** [comment]
I am almost certainly Luth-RoR is right, seen other videos of lvl100 Squig Herders following him theory
If SH had immovable immunity didn't jump, and if the squigh herder had not inmunity half second after made a jump prolly because the lag.

In best case would be just a problem with immovable not affecting the jump if you have the inmmunity running, can close the bugreport if you want.
