### ISSUE TITLE
WP heal range

### ISSUE THREAD

**Issue by DiodosXoX** [WarEmu/WarBugs#8518]
seems that the heal range is not really 100ft - more like ~92ft (this is measured with Enemy, don't have another addon).

Demonstrated with grp-heal, but sigmars radiance, etc. looks the same.

https://www.youtube.com/watch?v=ghlpMXYLCgA

**Comment by Luth-RoR** [comment]
Hi,

all the ranges are like they where on the mythic server (data is from the client itself). Enemy calculates ranges differently than other addons afaik and it could be that range measuring is generally not correctly _displayed_ on RoR atm (i know this was a problem in the past).
