### ISSUE TITLE
Guild Recall Scroll issue - disappearance when interrupted

### ISSUE THREAD

**Issue by RevMalthus** [WarEmu/WarBugs#8519]
when you attempt to use a guild scroll and you are interrupted - ie accidentally hit the move arrows - you lose the scroll.

I know its a minor issue but I figured I would report.

**Comment by Ryanfawkez** [comment]
Not sure if it was any different on live, to be honest; I remember that all consumables would have to be consumed before the ability is cast. Besides, the scrolls are cheap ;)

**Comment by sioding** [comment]
No answer since 2.12.2016 - close for now.
