### ISSUE TITLE
WL pet bug

### ISSUE THREAD

**Issue by Kvcherk** [WarEmu/WarBugs#852]
After last server restart 25.06.2015 WL pet disappears when you enter the combat. And on further summoning pets abilities that it has due to 'Trained to ...' skills do not appear on pet control bar. Recast of 'Trained to ...' doesn't help it.

**Comment by Silentguard** [comment]
Same as engi turret. Seems all pets dissapear while trying to attack.

**Comment by Kvcherk** [comment]
yep, interesting what destros have to say about it

**Comment by xyeppp** [comment]
It always disappears when you enter the combat? Does not happen with my squig.

**Comment by Silentguard** [comment]
Magus demons dont as we checked.

**Comment by Silentguard** [comment]
Hm, maybe because low level pet have no abilities, only AA.

**Comment by Kvcherk** [comment]
All fights i've started lion strikes once or twice then disappears. Summon skill icon on hotbar highlighted as active. WL rank 17

**Comment by xyeppp** [comment]
No - my squig has abilities, yet it does not disappear.

**Comment by ozarmidrashim** [comment]
Fixed in restart 1 minute ago.

**Comment by xyeppp** [comment]
Well that was... fast.

**Comment by Kvcherk** [comment]
indeed
