### ISSUE TITLE
Supplies disappearing while carrying

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#8520]
Yesterday evening while destro attacked the order keep in praag we decided to capture kurlovs armory and carry resources down to the keep to repair the order keep door.

After we succesfully took armory we immediately picked up the supplies and moved towards the southern keep. Unfortunately a few meters behind the destro warcamp the supplies vanished from the carrier. They were not dropped and we were not attacked.
Total time between picking up the supplies and vanishing max. 90 seconds.

**Comment by Blaqwar** [comment]
This has happened to me as well, supplies decaying shortly after being picked up, my guess is that the decay timer doesn't reset upon picking up the resource. I haven't timed it yet so I might be wrong, I'll try and time it today.

This behaviour might be intended to prevent the dominating side from simply stashing the resource at the BO for the full timer then picking it up before it decays to reset the timer and thus manipulate the system a bit. Or it might just be a bug.

**Comment by sioding** [comment]
Since we have totally changes the open rvr campaign and there is no need to carry supplies i will close this now. Thanks for the report.
