### ISSUE TITLE
A LAST GIFT QUEST TROUBLE

### ISSUE THREAD

**Issue by Horusaximand** [WarEmu/WarBugs#8521]
Can not take reward for quest "The Last Gift", it says that not enough place in the Inventory, but there is lots of space, all required conditions are done (including killed Stormvermin and Mushroom Satchel in the inventory).

**Comment by Luth-RoR** [comment]
A known bug; you have to 
1. make room in both inventories, normal **and** crafting
and
2. wait for a server restart
to take your reward/complete the quest.
