### ISSUE TITLE
[Swordmaster] Impeccable Reactions procs on Dodge

### ISSUE THREAD

**Issue by Blaqwar** [WarEmu/WarBugs#8522]
Impeccable Reactions is a tactic that provides a 100% chance to parry an attack after you parry. It wrongly triggers off Dodge as well (not sure about disrupt). Didn't have the combat log up but you can see that I was dodging attacks by the Squig Herder off the screen, the WSCT shows that Impeccable Reactions is the buff shown above the unit bar (Truncated as IR). Not that difficult to reproduce either.

![enses_023](https://cloud.githubusercontent.com/assets/5108812/20843615/3fb18b44-b8bc-11e6-9485-3893eb6e1587.jpg)

**Comment by ozarmidrashim** [comment]
was fixed
