### ISSUE TITLE
Engineer landmine undefendable

### ISSUE THREAD

**Issue by faiden** [WarEmu/WarBugs#8523]
When Engineers equip the tactic "Concussive mine" the mine gets undefendable.

Played a few scenarios to check this out and when dodging some mines I do not get stunned.
Each time I dodge a mine and still get staggered the "Concussive mine" tactic is applied.
After some long and tedious testing and "mining" I got a good screenshot showing it clearly.
![concussive-mine](https://cloud.githubusercontent.com/assets/6273311/20847201/4ceccd30-b8cd-11e6-840c-2d854ab8788c.png)

**Comment by Luth-RoR** [comment]
Thanks for the screenshot. Could it be that you didn't get staggered in some cases because you had the immunity? 
I could also imagine that the engi/magus stagger have an exception and you can only dodge the damage from the mine, not the stagger (just guessing).

**Comment by ozarmidrashim** [comment]
already dealt with
