### ISSUE TITLE
Unidentified yellow body 

### ISSUE THREAD

**Issue by esariobug** [WarEmu/WarBugs#8524]
Hi,
In the praag map, there is a unusual yellow body just under a common NPC at the chaos 17's chapter. On 6200 - 10800 coord. It's under the NPC named "Korzah the exalted". I took  a screenshot if u want.
Sorry for my bad english. bbye

**Comment by Luth-RoR** [comment]
Couldn't reproduce.

![000_crop](https://cloud.githubusercontent.com/assets/8567481/20858039/64a0ec4a-b93b-11e6-9cf3-f759d9bb0f79.jpg)
