### ISSUE TITLE
[Gas Squig] Spore cloud does not heal your battle squig

### ISSUE THREAD

**Issue by smingleton** [WarEmu/WarBugs#8527]
The gas squigs spore cloud is supposed to heal any of your squigs including your battle squig within a 30 ft radius of the targeted enemy. Right now it just heals the gas squig if its in the radius, but heals it twice if you are both in the radius
![matrik_029](https://cloud.githubusercontent.com/assets/24352165/20858136/a249c88a-b8f2-11e6-8616-569d7bd8a5c5.jpg)
![matrik_030](https://cloud.githubusercontent.com/assets/24352165/20858138/aaceb8da-b8f2-11e6-95d0-11d814bed27e.jpg)

These screen shots show that before and after spore cloud is cast I have the same health.

**Comment by smingleton** [comment]
I was hoping for some news on this issue, Is their any more information I can provide?

**Comment by Luth-RoR** [comment]
No additional info needed; the developer who created 99.9% of the combat/ability system is taking a break and so ability bugfixing is slowed down for the moment.

**Comment by smingleton** [comment]
Just popping in for an annual check up on my favorite bug, I hope all is well :) I noticed squig squeal was fixed recently and was hoping something similar was in store for gas squigs spore cloud perhaps. Take care, and thanks for all your hard work.

**Comment by hrothgar22** [comment]
Any news on if this is going to get fixed anytime soon?
