### ISSUE TITLE
Debolstering at T1, Changelog 03/12/16

### ISSUE THREAD

**Issue by Ezella** [WarEmu/WarBugs#8530]
just tested to debolster in t1 on a r20 alt and it seems it doesnt work correctly or maybe its just a visual bug, cause my alts rank is still shown as r20 (no debolster buff) and i ve seen some other player alts above rank15 with the same issue.

used the .getstats command to have a look for the changes between not rvr flagged and debolstered rvr flagged, no difference

![debolsteringt1](https://cloud.githubusercontent.com/assets/18719012/20860630/0aa3583a-b97d-11e6-8e1e-e872e4c48750.jpg)

**Comment by Smokeras** [comment]
Debolster is broken.As i tested, you just go at any level there with the previous debolster rules at rvr lake.After you pass the rvr check then you can put masteries and renown using anywhere trainer.Also the bolster is for low level characters at 19 but that not stoping you to put more points in mastery trees and renown.I was testing it with 24 level debolster character.

**Comment by Ezella** [comment]
checked this issue on a rank40 alt and i was able to use all carrier/mastery morale abilities. further more all tactics worked too, 4 slots available. it was even possible to use the r38 mount

**Comment by Ezella** [comment]
checked some discrepancies in relation to the bolstered ranks. could verify the following rank brackets:

chars rank 1-7 = bolstered rank 19
chars rank 8-11 = bolstered rank 17
chars rank 12-14 = bolstered rank 15
chars above rank 14 kept their ranks

there were also some exception, chars that should get bolstered but they kept their ranks (e.g.r3, r4, r9)

**Comment by Evildoor** [comment]
> checked some discrepancies in relation to the bolstered ranks. could verify the following rank brackets:
> 
> chars rank 1-7 = bolstered rank 19
> chars rank 8-11 = bolstered rank 17
> chars rank 12-14 = bolstered rank 15
> chars above rank 14 kept their ranks

I think this is intentional since both old and new bolsters work in such way (#4566), i'm not sure though.
