### ISSUE TITLE
pq bugs

### ISSUE THREAD

**Issue by normanis** [WarEmu/WarBugs#8531]
hello i dont know is it bug or bad luck. u can do most action in public quest bet when its comes to roll for loot u are always in last place and have from 001-300 points, ather ppl seems like just stay and dont sweat byt always have loot. is it bug or roll system is random. also i noticed if u are outside group u have always 001 point for rolling , even u are in action all time . 
p.s can u cheat rolls?

**Comment by normanis** [comment]
i know developers are bisy for such minor bugs or something, they doo great work, and cant watch evrything,

**Comment by Soulwhisper** [comment]
#8311 ?

**Comment by Luth-RoR** [comment]
As i understand it, he means that you always get only 1 contribution without a group regardless what you do.

**Comment by Soulwhisper** [comment]
@Luth-RoR If he means that then its not true.

**Comment by Luth-RoR** [comment]
Ok seems to be just RNG then. 
@normanis: There is a huge random factor in the rolls to prevent that classes with the most AOE damage get the most contribution.

**Comment by normanis** [comment]
yes, not always byt , most of time. if u are outside group. and sometimes when in group (from 001-500) . maby its not bug its my bad luck. and if u die and dont resurrect u need respawn its start from  zero. i am not expierenced with public quests, maby its just my luck.
because i tested with my kobs and u most time get bag, as witch hunter its problematic.
P.s i got some wins also byt i need as crazy spam dragon gun. ah yes and i cant go stealth. than i got nothing.

**Comment by normanis** [comment]
/*<![CDATA[*/
 blockquote.c2 {border-left: 1px solid #cccccc; margin: 0pt 0pt 0pt 0.8ex; padding-left: 1ex}
 p.c1 {color: #666; font-size: small}
/*]]>*/

ok thx for replay,

**Comment by Luth-RoR** [comment]
Afaik there is a huge random component (1/3 contribution and 2/3 random, not sure though).

**Comment by normanis** [comment]
i understand thx for your time
