### ISSUE TITLE
Still getting rr /inf/metalions at locked t4 areas.

### ISSUE THREAD

**Issue by Smokeras** [WarEmu/WarBugs#8532]
After an area like reikland or praag locked and having CW opened for rvr, players still get rewards if they kill at locked regions.AAO counts in lock area so you take more rr.I tried it in reik while the area was locked with praag and was geting still rr and inf.

**Comment by tlitschye** [comment]
Doesnt it depend on WHO locked the Zone? Like when Destro Locks, Order cant get anymore RP.
