### ISSUE TITLE
Inappropriate scenario queue debuff

### ISSUE THREAD

**Issue by dryack** [WarEmu/WarBugs#8535]
Today, perhaps 2-5 minutes after the server restart on/around 8pm UTC, I queued for all scenarios, then I left Caledor Woods and Stone Troll  Crossing.  Maybe 10 seconds later I got a pop for Nordernwatch.  I clicked Join, but the window closed and the message "Scenario join failure:  No pending scenario." displayed.  Following this I was given the Quitter Debuff.

![axielle_004](https://cloud.githubusercontent.com/assets/4473431/20861946/5d72510e-b952-11e6-92bc-882ef2ef99e2.jpg)

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/8017
