### ISSUE TITLE
[Squig herder] Ere Squiggy bug 

### ISSUE THREAD

**Issue by smingleton** [WarEmu/WarBugs#8536]
I'm pretty sure ere squiggy tactic is causing my pet to attack me.
It seems to happen most when using farty squig and tastes like chicken.
This bug affects git em, causing me to hit my target then my self and the squig will just hit me twice.

I think it has to do with defensive mode, but when in other modes the pet will hit me once  and stop attacking.

I had also looked at a screen shot I took from earlier on and it shows demonic chill hitting my pet as well, it may be related.

![matrik_040](https://cloud.githubusercontent.com/assets/24352165/20865628/0f0abaf4-b9cc-11e6-98b1-e6be64925b1b.jpg)

![matrik_032](https://cloud.githubusercontent.com/assets/24352165/20865576/4d4df642-b9cb-11e6-9062-faacdcff576c.jpg)
![matrik_033](https://cloud.githubusercontent.com/assets/24352165/20865578/50e1c496-b9cb-11e6-964a-7ed254e5e341.jpg)
![matrik_034](https://cloud.githubusercontent.com/assets/24352165/20865579/54429eb2-b9cb-11e6-80fd-62fd0a7dc285.jpg)
![matrik_036](https://cloud.githubusercontent.com/assets/24352165/20865583/5adcea5c-b9cb-11e6-8a82-8b9c3ccf7775.jpg)
![matrik_037](https://cloud.githubusercontent.com/assets/24352165/20865585/5de087c2-b9cb-11e6-8a1e-a5549948952d.jpg)
![matrik_038](https://cloud.githubusercontent.com/assets/24352165/20865589/67505512-b9cb-11e6-8444-23b65955560a.jpg)

**Comment by Luth-RoR** [comment]
Known: https://github.com/WarEmu/WarBugs/issues/8112
