### ISSUE TITLE
ToK unlock: Hydra Tamer

### ISSUE THREAD

**Issue by sioding** [WarEmu/WarBugs#8540]
While clicking on "Deathclaw"- the griffin behind Karl Franz - you´ll get the wrong tome unlock. Attached as Screenshot.
![unbenannt](https://cloud.githubusercontent.com/assets/18517842/20869251/ac9926a0-ba6e-11e6-864f-882047b2622b.PNG)

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/8136
