### ISSUE TITLE
Nerx Gutslime Lair - certain weapons for certain class never drops

### ISSUE THREAD

**Issue by sotora** [WarEmu/WarBugs#8541]
Nerx Gutslime Lair never drops 2 handers for Orcs and Chaos.  I've done it many times personally and I've known people that been doing it many times - I haven't found single person that could link or even saw above two handers drop.

**Comment by Yellowpillow** [comment]
I don't think this lair provided 2handers on live. As i remember 2 handed weapons drops only in west praag (and bastion stairs, but it isn't lair).

**Comment by NiteMoves** [comment]
Here's a video from 2010 when a HE 2-hander drops.
https://www.youtube.com/watch?v=WJcHwODSSag

**Comment by sotora** [comment]
Additionally Nerx Gutslime Lair already drops Blackguard 2 hander, and also Sorc and Goblin staffs. (and maybe others but that ones I am sure).   + of course any possible order drops I have no knowegedle of as atm I am destro only player.

**Comment by Luth-RoR** [comment]
According to DB-devs he drops 24 different weapons, not every possible weapon type that a class can equip; please keep in mind that other, atm incomplete, lairs drop also weapons, as already pointed out.
Single T1 lair bosses don't drop every weapon for every class too.
