### ISSUE TITLE
please check Runepriest healing and Willpower buff

### ISSUE THREAD

**Issue by Highbulp** [WarEmu/WarBugs#8543]
Lately Ik have been noticing my healing was really low, so I started to check my willpower and such.  I noticed the Rune of iron buff was not adding 50 willpower to my stats  on character screen and even after doing .getstats.  So i started checking other things healing power wasn't increasing.  I logged and relogged but it is still there.  Please check the Runepriest healing, and that the oath rune of iron is properly adding stats. 
 
Without Rune of iron
![bupu_001](https://cloud.githubusercontent.com/assets/24384115/20878809/de1843ca-ba9e-11e6-8e18-baa8fbc5ada4.jpg)

With rune of iron
![bupu_000](https://cloud.githubusercontent.com/assets/24384115/20878812/e3878cb2-ba9e-11e6-9fe5-0cf7bbab252b.jpg)

Without using .getstats
![bupu_002](https://cloud.githubusercontent.com/assets/24384115/20878853/11a5f818-ba9f-11e6-8b13-b689c8fd535b.jpg)

With using .get stats
![bupu_003](https://cloud.githubusercontent.com/assets/24384115/20878864/1c35b28c-ba9f-11e6-8b4c-caf18560439a.jpg)

**Comment by Zumos** [comment]
It looks like you are using a willpower potion and the RP buff does not stack with a willpower pot.

**Comment by Highbulp** [comment]
Ah was not aware of that.  Thank you for your assistance
