### ISSUE TITLE
[Sorcerer tactic] Shadow of Disaster

### ISSUE THREAD

**Issue by Asherdoom** [WarEmu/WarBugs#8544]
It says "The cost of Chillwind is reduced by 20 and it will reduce the enemy's spiritual resistance by 330 for 9 seconds"

The cost reduction is applied but no debuff of resitance is applied on use. I checked in duel with some guildmates to confirm. it applies only normal chillwind effect to me.

**Comment by Luth-RoR** [comment]
Check .getstats.

**Comment by Asherdoom** [comment]
i checked and i still got same resistance (dueled with enemy sorceress) i had 960 spirirt resistance and still got that much :(

**Comment by Luth-RoR** [comment]
>i checked

And how was it checked?
