### ISSUE TITLE
Can bolster into T4 at level 18

### ISSUE THREAD

**Issue by fart69** [WarEmu/WarBugs#8546]
According to patch notes I'm assuming this is a bug, was playing BO in elf T4 but I don't believe it's exclusive to class or area.

**Comment by Luth-RoR** [comment]
I can't reproduce this on a level 18 char in any T4 area. Any screenshots etc?

**Comment by fart69** [comment]
I was in t4 earlier and wasn't receiving a bolster anymore. will check around. Didn't screenshot.

**Comment by fart69** [comment]
yeah today's update fixed it
