### ISSUE TITLE
Cant' Touch Us

### ISSUE THREAD

**Issue by footpatrol2** [WarEmu/WarBugs#8548]
Can't Touch Us morale 4 on the black orc AP feed is not feeding the black orc nor his group upon use. It is suppose to add 200 ap for the entire group. This effect is not happening. The absorb looks to be working correctly.

**Comment by footpatrol2** [comment]
I tried to do this with pictures. I don't have a fancy recording device. The first picture is me draining all my AP. The 2nd picture is me poping Can't touch Us morale 4 ability. The ap that is there in the 2nd picture is the natural ap regen and not from the ability. The action bar should recover 4/5 of the entire action bar. It is so much easier to show if you try this out yourself on the server. I also tested this out with guildmates and them blowing all their AP to see if only the BO is not affected by AP feed. My guildmates did not regain AP either. Is this enough proof? 

`http://files.enjin.com.s3.amazonaws.com/1260339/module_gallery/original/2754543.jpg`

http://files.enjin.com.s3.amazonaws.com/1260339/module_gallery/original/2754544.jpg

**Comment by Luth-RoR** [comment]
Yes, only the absorb part of the morale works; i was just able to test it. I dropped my AP with hold the line and the bar didn't fill when using the M4.

You can drag&drop screenshots from your folder into the posting window; they get uploaded to github.

**Comment by footpatrol2** [comment]
I'd also check shield of valor also from the swordmaster m4. It is extremely similar to the BO's version. I don't have a SM to test shield of valor m4.
