### ISSUE TITLE
killed by 30k abitillies 

### ISSUE THREAD

**Issue by ThallySlayer** [WarEmu/WarBugs#8549]
Yesterday night i got oneshoted by some destro players doing 30k or more damage , check printscreens.

Bug or hacks ? 

thks

![thally_026](https://cloud.githubusercontent.com/assets/24410548/20925008/33862c06-bbac-11e6-9cdb-e6411eb89a68.jpg)
![thally_027](https://cloud.githubusercontent.com/assets/24410548/20925009/3386a2e4-bbac-11e6-8d97-769ce022e068.jpg)
![thally_028](https://cloud.githubusercontent.com/assets/24410548/20925010/3387b2e2-bbac-11e6-80ea-57d1cc8c4ae2.jpg)

**Comment by Ryanfawkez** [comment]
Blight IX is a weapon proc as far as I know.

**Comment by Luth-RoR** [comment]
Loudmouth is a BO tactic that procs damage every time a war bellow procs. Maybe a general bug with procs.

**Comment by ThallySlayer** [comment]
@Ryanfawkez , well it was the same, the WE one shot me , the 65k mitigation is a reflect of the damage i took, she was out of steath in front to me , i have 7.5k hp and 55% parry , she was rr33 no way she could one shot me

**Comment by ThallySlayer** [comment]
![thally_029](https://cloud.githubusercontent.com/assets/24410548/20940267/01a3f734-bbea-11e6-895e-42a11cc2af40.jpg)
![thally_030](https://cloud.githubusercontent.com/assets/24410548/20940268/01a41d9a-bbea-11e6-94ea-d53c213cab7f.jpg)
![thally_031](https://cloud.githubusercontent.com/assets/24410548/20940266/01a3da88-bbea-11e6-8690-46c3cbec11cd.jpg)
![thally_032](https://cloud.githubusercontent.com/assets/24410548/20940270/01a7b04a-bbea-11e6-88b2-c84033def2cb.jpg)
![thally_033](https://cloud.githubusercontent.com/assets/24410548/20940269/01a666b8-bbea-11e6-8143-cbfb39b0e61d.jpg)


Problem persists its impossible to play

**Comment by ThallySlayer** [comment]
I think the problem may be from putting the banner equiped, i tryed to remove now i cant even log in

**Comment by Luth-RoR** [comment]
I just tested one of my chars with a banner, but i couldn't reproduce it. It must be something else.

**Comment by Luth-RoR** [comment]
I just tried a scenario (with my slayer, just to be sure) and i didn't got any insta-death from neither normal damage nor procs. I guess it must be related to your character/account somehow.

**Comment by ThallySlayer** [comment]
It only happens on rvr, never got a issue on scs

**Comment by ThallySlayer** [comment]
i remove all gear , specc and log , going to give it a try again on rvr
