### ISSUE TITLE
Fall Damage Suicide: Missing Renown

### ISSUE THREAD

**Issue by Pumatouch** [WarEmu/WarBugs#8550]
When fighting a group of opponents, some folks choose to jump over edges of high bridges/cliffs in order to suicide below, instead of fighting till the end. This act robs the winning side of renown from the battle - Fall Damage Suicide awards no renown at all.
 Because renown is not awarded by doing this, it has become a regular tactic deployed in combat to deny opponents awards. Reinstating awards from Fall Damage Suicide should make this tactic useless.

**Comment by Luth-RoR** [comment]
It also prevents bots from renown farming.
