### ISSUE TITLE
Shaman Tactic (Шаман Тактика)

### ISSUE THREAD

**Issue by Anatoly72** [WarEmu/WarBugs#8551]
http://waronlinebuilder.org/#career=sha;0;0;0;;;;5308:;0:0:0:0:
Shaman Tactic
"Whazat Behind You?!"
Does not work properly
Thank you!

Шаман Тактика
"А чо это у тя сзади?"
Работает не корректно
Спасибо!

**Comment by Luth-RoR** [comment]
>Does not work properly

WHatever that means. Please read the bugtracker rules.

**Comment by Anatoly72** [comment]
Tactics written which reduces 75% damage, but it is not!

**Comment by Luth-RoR** [comment]
> "...causing them to deal 75% damage to you for 5 seconds..."
