### ISSUE TITLE
Main hand spanners (normally MH/OH)

### ISSUE THREAD

**Issue by Gideon404** [WarEmu/WarBugs#8553]
Marksman's spanner of vengeance and survivalist's spanner of vengeance (T1 renown vendor spanners) are main hand only while nearly all other spanners in the game are main hand or off hand.

This gamebreaking discrepancy affects appearance options.  As always, thank you for the time you put into this project.

**Comment by Luth-RoR** [comment]
Can't be fixed yet afaik. Will be reopened when it can be fixed.

**Comment by Luth-RoR** [comment]
According to DB devs this can be actually fixed now.

**Comment by Gideon404** [comment]
Cool. Then see also #8226
