### ISSUE TITLE
A Bottle Before Battle: Missing Quest Reward

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#8554]
Quest giver is in Eataine, 32855:14025, Saleh Vinesinger. Order Quest.

Objective is to take a bottle of Caledor Blush from his cart, then give it to him. Can complete the quest, the item interaction works, but he does not give you a bottle of Caledor Blush in return on completion of the quest. Used to be an item that you just kept in your backpack. It's a gimp item really, but for RP purposes, would be fun to have a bottle of this to pull out now and again :-)

**Comment by wargrimnir** [comment]
Updated quest reward.
