### ISSUE TITLE
[Engineer] Flame turret Buff doesnt affect Keg, Napalm, Rod, Landmine

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#8555]
I made some tests on the increased AoE Range of the Flame turret.

Increased AoE Radius works on the following abilities for sure:
Static discharge
Fricition burn
Blunderbuss Blast
Barbed Wire
Frag Grenade (Extra Powder Tactic is still broken on Frag Grenade. So doesnt stack.)
Acid Bomb (stacs with Extra Powder tactic.)
Self Destruct (Only if used with Flame Turret and Flame Turret Buff)

Increased AoE Radius DOES NOT increase the following AoE Abilities:
(Tested on lvl 7-8 pigs in Nordland and Rats on Altdorf Market place.)
Lightning Rod
Keg
Napalm
Landmine

No current tests on:
Flashbang
Phosphourous Shell
Sticky Bomb
Strafing Run
Shock grenade

Tests on AoE Cap increase.
Get Increased AoE Cap:
Static discharge (Hits 11 npcs. So AoE Cap was increased.)
Fricition burn
Blunderbuss Blast
Frag Grenade

Get NOT increased AoE Cap:
Ligthing Rod (Still hits only 9 npcs max.)
Keg (Tested with Warband)
Napalm

Screenshot shows damage on a Gor Horde.
![lesti_521](https://cloud.githubusercontent.com/assets/14627932/20966784/57e23ca4-bc7c-11e6-8d6a-6697cb0caa2e.jpg)

**Comment by Luth-RoR** [comment]
Aza thinks about changing lightning rod, but the others (Keg, Napalm, Landmine) are intended.
