### ISSUE TITLE
[Magus] Indigo Fire of Change crits

### ISSUE THREAD

**Issue by faiden** [WarEmu/WarBugs#8556]
This skill has odd crit damage values.
Tested vs a melee mob. No buffs or debuffs
Crits seems to be random value

The non crit attacks stay at the same value each tick
![2016-12-07-134814_710x186_scrot](https://cloud.githubusercontent.com/assets/6273311/20969371/f980be44-bc88-11e6-8497-2713bc70f391.png)
![2016-12-07-141851_709x187_scrot](https://cloud.githubusercontent.com/assets/6273311/20969377/fe0ab71c-bc88-11e6-88a3-e7369483c911.png)
![2016-12-07-142302_709x185_scrot](https://cloud.githubusercontent.com/assets/6273311/20969378/fe312f3c-bc88-11e6-9afb-eb1ef3239c84.png)

**Comment by Luth-RoR** [comment]
Yes, this is how all crits work (and worked on the mythic server). Most people think they had fixed values, which is wrong.
