### ISSUE TITLE
[Shaman] Fury Of Da Green is raw healing

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#8557]
Fury Of Da Green seems to be unable to critheal. While it has been explained that the damage portion of lifetaps is not supposed to crit (and it never does), the healing portion should be able to crit, yet does not on Fury of Da Green (yet works on I'll Take That!).

From the experimental mode post on the forums regarding Shaman/Archmage lifetaps:
+ The heal component gains the Healing type instead of the Raw Healing type. It will be heal debuffed/blessed, can crit as a heal would and is able to proc effects.

This does not work on Fury Of Da Green (presumably not on the Archmage equivalent, Energy of Vaul, either?). In over half an hour of testing with 20% heal crit, Fury Of Da Green never crithealed once, with or without career mechanic charges.

**Comment by Thayli** [comment]
Azarael has verbally confirmed that this is simply not implemented as of yet.

**Comment by Rockalypse** [comment]
#17808 Fixed
