### ISSUE TITLE
[Magus] Indigo Fire of Change movement

### ISSUE THREAD

**Issue by faiden** [WarEmu/WarBugs#8558]
The skills gets interrupted even thou the pet buff from flamer pet is active
Added a link: [youtube](https://youtu.be/FPs9OHutqgo)

**Comment by ozarmidrashim** [comment]
It is explicitly stated that this does not work on IFOC

**Comment by faiden** [comment]
Do you have a source where this is stated?.
Patch notes says: Provided you have at least one Unholy Empowerment stack, allows you to use Path of Changing skills while moving.

**Comment by Natherul** [comment]
patchnotes updated. thanks for finding this discrepancy
