### ISSUE TITLE
The job is "Worth it"

### ISSUE THREAD

**Issue by Anatoly72** [WarEmu/WarBugs#8559]
Getting the "Bestial Token" for killing the "Bridge Troll" does not work.
That is, I didn't get the animal sign in a bag
Checked 2 personage. 
Thank you!
( Items that cannot be sold Can be sold in the transfer window dealer
As it should be? )

**Comment by Ryanfawkez** [comment]
http://warhammeronline.wikia.com/wiki/Takes_its_Toll - doesn't award a bestial token. It only rewards the Revolting Crock pocket item at the library vendor.
