### ISSUE TITLE
WB crashed while I was entering the zone

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#8560]
in both case at least 1 faction had 24+ players in the keep 

1. open WB was in KV attacking south keep and i joined it from TM
i was running from TM to KV in the rvr lake
when i entered KV there was a brief zoning lag 
( or loading? where minimap briefly flicker and zone name's changed )
and i was heading toward the south keep
then 3/4 of WB members just disapeared
me and some others were still in WB

2. i was a leader of overflow open WB in KV attacking the south keep. we were in the inner yard 
only our WB got crash. when i back in there was a 1 man in the WB. 
i asked him and he just came from TM

**Comment by Luth-RoR** [comment]
Random WB crashes are known, but the root of the problem is not yet unfortunatelly.
