### ISSUE TITLE
[Engineer] Grenade Turret Buff doesn't Buff Keg, Rod, Napalm

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#8561]
**Grenade Turret**

Decreased Dot Time **WORKS** on this Abilities
Frag Grenade (Full Buff from 15sec to 9sec, from tic 3 secs, to tic 1,8secs, still 5 tics total, same damage)
Acid Bomb (Full Buff from 21sec to 13sec, from tic 3 secs, to tic 1,85secs, still 7 tics total, same damage)
Sticky Bomb (Full Buff from 15sec to 9sec, same damage, not tested the activated ability.)
Friction Burn (Full Buff from 9sec to 5sec, from tic 3 secs, to tic 1,66secs, still 3 tics total, same damage)

Decreased Dot Time **DONT** works on this Abilities
Incendary shot (Works as intended I guess. Change log says Grenade and Tinkerer Dots decrease.)
Signal Flare (Works as intended I guess. Change log says Grenade and Tinkerer Dots decrease.)
Keg (Is a Tinkerer dot but isn't affected)
Lighting Rod (Rod makes 4 hits, one every 3 secs. Before and after Grenade Turret Buff.)
Napalm (Napalm makes a hit every 2 secs. Before and after Grenade Turret Buff.)

**Comment by Luth-RoR** [comment]
The keg is a hot, no dot. Lightning rod has a pulsating effect and napalm is gtAoE, so i think those are different. These abilities do damage over time, though the don't apply a debuff on a target.

**Comment by Luth-RoR** [comment]
Confirmed as working as intended.
