### ISSUE TITLE
[Engineer] After 7.12 Patch Flame Turret increases Dodge Disrupt by max 24% not 32% as notes say.

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#8562]
[Engineer] After 7.12 Patch Flame Turret increases Dodge/Disrupt by max 24% not 32% as notes say.

What the title says.
Checked it with .getstats.

Evade was 20% before buff. 
44% after full Flame turret buff.

**Comment by LestiArdisson** [comment]
Before Flame buff
![lesti_522](https://cloud.githubusercontent.com/assets/14627932/21002871/567c6f72-bd28-11e6-8c95-3b354242c5a1.jpg)

After full 8x Flame Buff
![lesti_523](https://cloud.githubusercontent.com/assets/14627932/21002872/567eeacc-bd28-11e6-9658-1df518049b2e.jpg)

Increase by 24% instead of 32%

**Comment by Luth-RoR** [comment]
Should be fixed now: https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=18817
