### ISSUE TITLE
Emperor's Ward

### ISSUE THREAD

**Issue by Yry85** [WarEmu/WarBugs#8563]
Hi, 
I think I've found a problem with that tactic, it says that it will not trigger more than once every 3 seconds, but in my KotBS sometimes triggers once the previous is consumed.

**Comment by Luth-RoR** [comment]
If the absorb effect was active for at least 3 seconds it can ofc proc again right after it was consumed.

**Comment by sioding** [comment]
No answer since 8.12.2016 - close for now.
