### ISSUE TITLE
Consolidated report: Fall damage bug

### ISSUE THREAD

**Issue by RevMalthus** [WarEmu/WarBugs#8564]
just got killed by falling while trying to jump- 11kish damage. Was no fall- you will see I am at the top of the bridge. 

Heres a picture

![rochambeaux_041](https://cloud.githubusercontent.com/assets/4071605/21002720/742bfc5c-bce4-11e6-84e3-8f595f8117da.jpg)

**Comment by Luth-RoR** [comment]
Did you "hang in the air" between two obstacles for a few seconds before this happened?

**Comment by RevMalthus** [comment]
hmm... i remember jumping on that rail and "sliding" a little bit... so yes, I would probably say so, but I dont remember there being a second object unless it was the end of that bridge. like the "pillar" part

**Comment by Luth-RoR** [comment]
If you "hang in the air" for a time, the game thinks that you fell down (like from a cliff, wall etc.). Maybe this was the case here.

**Comment by Grendel1892** [comment]
We have had Several guild members die in incidents like this. not just in this SC. always 11K damage. for a nothing fall.

**Comment by Luth-RoR** [comment]
I had it recently when i jumped several times in a row, but that could be a coincidence.

**Comment by RevMalthus** [comment]
just happened again in Nordland, outside of SC - on a rock

Also know that this happened to a buddy of mine when we were trying to run to Metoh lair in Troll Country

This time there was no glide or "hover" though

![rochambeaux_120](https://cloud.githubusercontent.com/assets/4071605/21170814/ec4ecd46-c184-11e6-9dab-508ce176bd0f.jpg)
![rochambeaux_119](https://cloud.githubusercontent.com/assets/4071605/21170818/efc0071a-c184-11e6-8af3-8da00fe02cbf.jpg)

**Comment by sotora** [comment]
The Apex stairs in IC have relatively high reproduction rate of this.   Just jump around on The Apex, eventually you die.

**Comment by tlitschye** [comment]
On the rocks at Karak Palik, happended one time to me and one time to a mate.

**Comment by Luth-RoR** [comment]
Stonetroll crossing https://github.com/WarEmu/WarBugs/issues/9097
Altdorf: https://github.com/WarEmu/WarBugs/issues/9101

**Comment by saupreusse** [comment]
there are thousands of places where this happens. no idea where it came from but i guess its something the coders might know?

**Comment by Luth-RoR** [comment]
Praag, Kurlov's Armory BO https://github.com/WarEmu/WarBugs/issues/8954
20826 28370 in Thunder Mountain https://github.com/WarEmu/WarBugs/issues/9437

**Comment by Luth-RoR** [comment]
Eataine https://github.com/WarEmu/WarBugs/issues/9435

**Comment by dalen** [comment]
This is fixed now with the new fall damage calculations.
