### ISSUE TITLE
Howling Forge mounting issue

### ISSUE THREAD

**Issue by amyristos** [WarEmu/WarBugs#8565]
As soon as someone picks up the keg , there is no way he is going to mount up again after dropping it. After you drop the keg at the detonation point whether you die or not, you cannot mount up again for the rest of the scenario. Faced that in all the howling forge scenarios i popped today. The message i received is the one that you get when you carry the keg.

**Comment by Luth-RoR** [comment]
Known https://github.com/WarEmu/WarBugs/issues/6975
