### ISSUE TITLE
Missing Guild Vault items

### ISSUE THREAD

**Issue by Halmann** [WarEmu/WarBugs#8566]
the issue is, today i have checked my guild vault 2 from my guild <Guardia Imperial> (Order) and some talismans have been dissappeared (10 of 150 armour & some more) and it is not the first time that it happens. I am the guild leader and obviously im the only one who have permission to take away items from this vault. Lot of effort and money have missed with that loss. 

hope can i get an answer or solution. Thanks

**Comment by Luth-RoR** [comment]
Known issue: https://github.com/WarEmu/WarBugs/issues/8198
