### ISSUE TITLE
Warcamp guard in PVE

### ISSUE THREAD

**Issue by andytomlins** [WarEmu/WarBugs#8569]
On the exit to Dwarf Chapter 22 quest hub there is a group of regular Orc mob spawns. Since the latest patches one of them is a Hostile Orc level 40 hero camp guard that one shots anyone leaving the quest hub. Spawn position is approx 34 46

**Comment by Torquemadra** [comment]
name and screenshot please

**Comment by wargrimnir** [comment]
I see no R40 hero in the area, this appears to be fixed.
