### ISSUE TITLE
Tower of Neborhest PQ - Boss model

### ISSUE THREAD

**Issue by badbreff** [WarEmu/WarBugs#8570]
The model for Dork Redeye, Undead Orc Warlord and boss of Stage 4 of the Tower of Neborhest PQ, is of a naked Goblin. 

It's...silly.

**Comment by wargrimnir** [comment]
Applied Zomborc model and equipment.

**Comment by wargrimnir** [comment]
![2016-12-21_17-45-09](https://cloud.githubusercontent.com/assets/12942408/21408893/6c10de54-c7a5-11e6-9a7a-27f6a72cd3f9.png)
