### ISSUE TITLE
WP M3 Penance broken

### ISSUE THREAD

**Issue by Grendel1892** [WarEmu/WarBugs#8571]
When using WP M3 Penance I get cast bugged saying I'm currently casting and I cant do anything else. Message 8304 Penance threw an unhandled exception error..
![bolimor_007](https://cloud.githubusercontent.com/assets/17376568/21069792/5610cf5a-be4b-11e6-8905-98247d4d190d.jpg)

**Comment by Luth-RoR** [comment]
Could it be the same issue as this one https://github.com/WarEmu/WarBugs/issues/5947 ?

**Comment by Grendel1892** [comment]
I don't think it is quite the same as 5947. Notice that my health bar is low I cant use any abilities after this error. Soulfire remains at 0 seconds forever. it has been 23 seconds since I cast penance and since that time no abilities could be used. After respawning I wasn't able to mount up because it said I was "still casting" Maybe it has something to do with casting Soulfire, before or immediately after using M3... I just did it again, but the first time I used penance it fired normally, the second time I cast it, I bugged out again.

**Comment by Luth-RoR** [comment]
As the other report should be fixed with the next patch, maybe you could report back if the bug still persists once it went live.

**Comment by Grendel1892** [comment]
Not fixed as of 5 AM EST. 
![bolimor_010](https://cloud.githubusercontent.com/assets/17376568/21136936/b4eff0c6-c0f5-11e6-9781-dd9fbb0e367e.jpg)
Notice the chat window text.

**Comment by Luth-RoR** [comment]
The fix has probably not been pushed yet; usually there should be patchnotes.
