### ISSUE TITLE
unable to mount horse after dying with powder keg

### ISSUE THREAD

**Issue by RevMalthus** [WarEmu/WarBugs#8572]
hey guys, after dying with the Powder keg in the Howling Gorge scenario, I was unable to mount my horse. 

I know there was a recent fix to stop mounting WITH the powder keg, but I wanted to report this to make sure it wasnt happening to others 

Heres a picture

![rochambeaux_060](https://cloud.githubusercontent.com/assets/4071605/21071600/e7ed1b56-be62-11e6-9707-3a9422bc66b5.jpg)

**Comment by Luth-RoR** [comment]
Hi, this is a known issue: https://github.com/WarEmu/WarBugs/issues/6975
