### ISSUE TITLE
Dwarf Chapter 9 Influence Bar shows as Chapter 5

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#8573]
- [ ] As said on tittle...when you are in Dwarf Chapter 9 PQs it shows Chapters 5 bar.

**Comment by Soulwhisper** [comment]
Hm...same issue like these.
#8411
#8412

**Comment by wargrimnir** [comment]
This is mostly fixed. The only problem left is the Ch6 area covers the Foul Ruins PQ and the Ch5 camp,that needs to be redrawn.

**Comment by Soulwhisper** [comment]
I think this is fixed...needs to be confirmed.

**Comment by wargrimnir** [comment]
It was fixed in last patch.
