### ISSUE TITLE
Precursor Crusher

### ISSUE THREAD

**Issue by Skutrug** [WarEmu/WarBugs#8574]
Dear Database team,
I just received a precursor crusher (39) - It indicates it is a one-handed hammer for chosen.
Chosen don't use hammers - It's either for a marauder and it's a hammer, or for a chosen and it's an axe.
The icon looks like an axe.
Thank you for all the work.
Cheers,
Skut

**Comment by Luth-RoR** [comment]
Just for clarification: The item has the class restriction "chosen"? A screenshot is always helpful.

**Comment by Skutrug** [comment]
Will send screenshot - I kept the item

**Comment by Torquemadra** [comment]
the icon was an axe, now a mace, marauder specific item, thanks
