### ISSUE TITLE
SHs(prolly not only) ranged pet hit through walls again

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#8575]
I was on outer and pet was down, next to wall, no LoS but he hit me.

**Comment by Luth-RoR** [comment]
>ranged pet hit through walls again 

>pet was down

❓

**Comment by MKorin** [comment]
Not on wall but next to

**Comment by Luth-RoR** [comment]
I thought you mean your pet was dead, which made no sense to me.
Devs confirmed that this is an issue atm, but it can't be fixed yet. They are aware of it though.
