### ISSUE TITLE
[Spanish client] Can't use the Advice channel

### ISSUE THREAD

**Issue by kurwen** [WarEmu/WarBugs#8576]
When I try to use the advice channel writing "/ad" (without quotes) I get the error: "Unknown command /ad." without quoutes and in spanish. After the advice channel is active on my chat window, and I justs hit enter and write I get the same error.

**Comment by Luth-RoR** [comment]
Do you have any addons installed?

**Comment by sioding** [comment]
No answer since 14.12.2016 - close for now.
