### ISSUE TITLE
Stealth + Resources

### ISSUE THREAD

**Issue by Sprak2686** [WarEmu/WarBugs#8577]
Playing in DW today, a WE took the resources and went stealth as we approached her (with the resources) and got them into the keep. 

Not sure if this is intended or not.

**Comment by Luth-RoR** [comment]
I don't think it's intended, for the same reason it should not work in scenarios.

**Comment by Sprak2686** [comment]
Here is proof of WH (probably same with WE's) being able to stealth with resources.

http://imgur.com/oAwhXt1
