### ISSUE TITLE
[Core] LoS packets interrupts

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#8578]
LoS check interrupts ability cast on every server step tick. In fact any tiny stick in game interrupts your cast and can be used to make you unattackable by any non-instant ability. War live server has two rules for casts.
1) Start and first 25% of cast time can be interrupted on every server step. Rest 50% bypass check. Last LoS check at 75% cast time.
2) Chennelings same as common cast with additional on every tick check.

**Comment by Luth-RoR** [comment]
Confirmed by the devs as working as intended at the moment. Maybe it will be adjusted in the future if balancing requires it.
