### ISSUE TITLE
High Elf chapter 10 influence reward for slayer "Torc of simple runes"

### ISSUE THREAD

**Issue by Gideon404** [WarEmu/WarBugs#8579]
![dumac_017](https://cloud.githubusercontent.com/assets/16654707/21081421/45c0aa02-bfbe-11e6-85c0-e3875dae9218.jpg)
Boots on shoulders?

![dumac_018](https://cloud.githubusercontent.com/assets/16654707/21081433/95a4bffe-bfbe-11e6-8818-4073b5855bbd.jpg)
Missing armour stat?

**Comment by wargrimnir** [comment]
The first one should be Arboreal Chargers. - fixed in next.
The second one should be Torc of Gamesmanship. - fixed in next
Also corrected stats on all Arboreal Boots and Gamesmanship Shoulders.
