### ISSUE TITLE
Zealot [Abilitie] Leaping Alteration

### ISSUE THREAD

**Issue by Elratie** [WarEmu/WarBugs#858]
The Zealot skill Leaping Alteration isn´t working correctly, it dosen´t jump to the next Target´s just the first target get´s the HoT

**Comment by Elratie** [comment]
i did today some more testing with it on Zealot and RP (Rune of Serenity)
with the RP it works like the tooltip says, jumps to the next in range after the 9s

so the Zealot: it does jump exactly like the RP Hot but Tooltip and on the Live server it jumped to the next 6 target´s instantly who where in range and it dosen´t matter if they are in the same group or not, has to be friendly. for the RP hot i think it was the same like Zealot on live but can´t say that for sure never played the class on live 

hope this help´s more

**Comment by ozarmidrashim** [comment]
If it currently matches the tooltip, then it's good enough for me.
