### ISSUE TITLE
Cloak dye bug, related to guild

### ISSUE THREAD

**Issue by gke96** [WarEmu/WarBugs#8580]
As long as you are in any guild cloak dye dont work (probably related guild herald), but if you arent in any guild dyeing cloaks normally work, just tested it.

(Cloak dye bug: the bug that you dye your cloak but others see your cloak not dyed)

**Comment by Luth-RoR** [comment]
Yes that's a known issue, though it's unknown at the moment how to fix it, so that both options work when in a guild.
