### ISSUE TITLE
Destro Quest: The Torment of Caledor

### ISSUE THREAD

**Issue by appdevman** [WarEmu/WarBugs#8581]
Destro quest in Caledor.

Can not interact with or attack the Firescale.
I achieved  "The Blood of the Righteous" portion of the quest, but am unable to complete quest via the Firescale I found located just outside the BO "Shrine of the Conqueror", on the ground.

**Comment by Natherul** [comment]
I checked the quest on dev and it worked fine currently with a random firescale, to check if its an issue with a particular firescale I would need some coordinates,
