### ISSUE TITLE
[ Marauder ] Wave of Terror Ability 

### ISSUE THREAD

**Issue by Haojun-Phalanx** [WarEmu/WarBugs#8584]
http://waronlinebuilder.org/#career=mar;0;13;0;;13:;;;0:0:0:0:

Tooltip says; Ability prevents all morale regeneration for 5 seconds.

Morale gain still continues with  "Embrace the Flames [BW Morale Tactic] "

With Morale Tactic:
![hao_000](https://cloud.githubusercontent.com/assets/23129933/21140147/2bd619e2-c13f-11e6-922d-16b4eacad994.jpg)
![hao_002](https://cloud.githubusercontent.com/assets/23129933/21140155/311d2e18-c13f-11e6-8e03-f3e13f31ab56.jpg)

Without Morale Tactic:
![hao_015](https://cloud.githubusercontent.com/assets/23129933/21140136/2014619a-c13f-11e6-904f-3a6fa925511b.jpg)

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/8438
