### ISSUE TITLE
ToK unlock "A Matter of Scales"

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#8586]
This giant lizard unlock must be triggered by right clicking on "Scaly Skin". This item can be looted by killing salamanders in Barak Varr, but does not give the unlock when right clicking on it.

**Comment by Lheana** [comment]
The "Scaly Skin" is now a pocket item, and gives the unlock but not the title "The Lizard Hunter".

**Comment by Luth-RoR** [comment]
See https://github.com/WarEmu/WarBugs/issues/5439

**Comment by Lheana** [comment]
Equiping the Scaly Skin still does not provide the title associated 'The Lizard Hunter'.

**Comment by Lheana** [comment]
Furthermore, killing 'Beach Salamanders' neither provides the associated title.

**Comment by Ryanfawkez** [comment]
Put 'A Matter of Scales onto the Beach Salamanders. Item now gives the title.

**Comment by Lheana** [comment]
Order task for this unlock is to kill 'Scorch Tails' and 'Scorch Breaths' inside cave 'Fire Crystal Cavern' in the Blighted Isle (36.5k 20.3k). Killing them does not provide the unlock, and they don't seem to drop 'Scaly Skin' needed for the associated title.

**Comment by DayleD** [comment]
I got the unlock without clicking on the Scaly Skin, just as soon as it drops. And I can also confirm I don't have the title, just the Journal unlock.  
Journal still says Title: ??? - Must get a particular item.
