### ISSUE TITLE
ToK unlock "Off With His ..."

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#8589]
This slayer bestiary unlock should be triggered by collecting 20x "Slayer Scalp" and then talk to Reezel in chap 7 in Barak Varr. The slayer scalp can be collected, but talking to Reezel does not give the bestiary unlock.

**Comment by Ryanfawkez** [comment]
Work-around made. Spend 20 Slayer Scalps at the Library/Disciple's Assistant.

**Comment by Lheana** [comment]
Order can not loot Slayer Scalps, so work-around does not permit to have the unlock.
Order must now talk to 'Captain Erginsson' in Barak Varr for this unlock, as it is meant to be.
