### ISSUE TITLE
Mandred's Hold missing Keep Lord

### ISSUE THREAD

**Issue by xyeppp** [WarEmu/WarBugs#859]
Keep lord along with one champion is missing from Mandred's Hold Keep.

**Comment by ozarmidrashim** [comment]
Checked Stonetroll, it's Destruction controlled and all NPCs are there. Order control Mandred's Hold and KL + a champ are missing.

**Comment by xyeppp** [comment]
Sorry meant Mandred's, my fault.

**Comment by xyeppp** [comment]
Lord also missing in Stonetroll now.

**Comment by xyeppp** [comment]
I found the now-missing Stonetroll Lord, so he is definitely not getting removed completely. He was also in a different position than I found another lord before - this time at 38k,12k Trollcountry but he disappeared after a while.

**Comment by ozarmidrashim** [comment]
Still happening despite today's patch, so in next patch there are sanity checks and logging everywhere.

**Comment by xyeppp** [comment]
Mandred's Keep lord missing again. Is it possible that some skill maybe causes him to get TPd akin to the punt in the scenarios? Because he is somewhere on the map again probably, but not where he was supposed

**Comment by xyeppp** [comment]
Missing from Stonetroll, found at 25k, 44k TC
All guards are there tho, only the lord missing this time

**Comment by Reggaewaldo** [comment]
This seems to be resolved with the last patch.
