### ISSUE TITLE
Slayer: Rampage

### ISSUE THREAD

**Issue by tlitschye** [WarEmu/WarBugs#8603]
Rampage hits trough Morale 1 "Confusing Movements"

Rampage says: For the next 10 seconds, you attacks cant be Blocked or Parried. ...
Confusing Movenments says: ..., you will be able to Dodge and Parry all attacks against you for 7 seconds.

Afaik a SKILL should not be stronger than a MORALE.

Greets

**Comment by ozarmidrashim** [comment]
Proof?

**Comment by Evildoor** [comment]
#1787 may be related.

**Comment by tlitschye** [comment]
You need a Screenshot that it DOES ignore CM? or something else?

**Comment by Zumos** [comment]
No, proof that on live CM worked against Rampage. And as CM gives +100% parry/dodge and Rampage I guess removes 100% parry, I wouldn't know why Rampage is not supposed to work against CM.

**Comment by Silentguard** [comment]
Mythic made CM gives you +100% in parry\dodge check, this is not a buff, means not grant you parry as stat or it works this way. Means CM as pseudo buff can not be decreased by any debuff, however Rampage is +100% strikethrough buff and subt after all of your effects. In fact i dont remember if target could parry anything against Rampage by following this logic: Target.parry+100 - Player.parry_strikethrough+100. Maybe it's just defense ignore buff.

**Comment by tlitschye** [comment]
So actually if i read right, i should still have my normal 30% parry if i have CM up an the Slayer has Rampage on.

That isnt right, the slayer negates ALL of my parry, i get 0 parry when ramage is up, il try to get some Screens of that.

Greets

**Comment by Krimalicious** [comment]
People should forget the usual "proof"!!
Live happened 8 years ago, kinda hard to give proof on something rly old..they want a HD video showing CM worked against Rampage..LOL 
Lets use Common sense, a skill on a 10 sec cooldown should be better than morale 1 ? Dont think so. Parry its pretty expensive to stack also.

**Comment by Kaelang** [comment]
Looks like conversations here were learning towards this as a Balance Feedback as opposed to a bug. Closing.
