### ISSUE TITLE
Suddenly unable to use abilties in scenarios

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#8604]
Our group is experiencing a bug where players are suddenly unable to use abilties. For the reminder of the scenario. This has now occured in two different scenarios (Khaine's embrace & Morkain Temple) on three different players in total 4 times (1x AM, 1x WH, 2x BW) .
After leaving the scenario you can use abilties again. This hasn't happend in oRvR so it seems limited to scenarios.

**Comment by sotora** [comment]
While I can't confirm it myself I saw one long term player with good reputation posting same thing in chat today.

**Comment by Luth-RoR** [comment]
There was a hotfix today that fixed another issue with scenarios; does it still happen?

**Comment by Cimbas** [comment]
We haven't encountered this problem since the hotfix so it seems to be solved.
