### ISSUE TITLE
WP Morale 3 - Penance

### ISSUE THREAD

**Issue by SATANICOMODERNO** [WarEmu/WarBugs#8606]
Penance doesnt work properly, at least at mobs. I was farming some fragments for talismans in Reikland with mobs level 33. When I used penance, it did nothing and I could not inflict damage on mobs anymore. In fact, I discovered that it's me that cant use my abilities. Trying to cast heal or use other morale (it's because Penance wasn't casted in that way) or any other ability i got stuck.
It's like when we are about to be disconnected and we try to hit the enemy and our attacks doest work, the effect is the same, and i just noticed that this bug was happening after i use Penance for the third time.

**Comment by Luth-RoR** [comment]
Known: https://github.com/WarEmu/WarBugs/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20Penance
