### ISSUE TITLE
Battle Fatigue appear to persist after healing

### ISSUE THREAD

**Issue by Dallidiem** [WarEmu/WarBugs#8607]
I died in PVE.  Healed.   Left-click self.  Look like I still have battle fatigue.  My wounds though seem to be correct - not reduced.

![war_2016-12-13_22-01-24](https://cloud.githubusercontent.com/assets/24558782/21168495/59f4e838-c182-11e6-8251-6eb40e6a45e8.jpg)

**Comment by Luth-RoR** [comment]
You need to use "heal all". This will remove every debuff.

**Comment by Dallidiem** [comment]
I only had 1 to heal.   The debuff didn't show unless I clicked myself.
But I'll try that next time
