### ISSUE TITLE
+25AP at RR65 & +25AP at RR75.

### ISSUE THREAD

**Issue by Teefz** [WarEmu/WarBugs#8609]
Hello. 

Was going through old WAR videos when I noticed that the +25AP at RR65 does not apply to the character here on the RoR servers. If i remember correctly - and judging by youtube videos - the last +25AP was added at RR75 for a grandtotal of 300AP. Is this an intended feature or lack thereof?

**Comment by Luth-RoR** [comment]
Hi,
it's known how it used to work, but the missing implementation is intended atm.
