### ISSUE TITLE
Big Choppa of Conquest again [item]

### ISSUE THREAD

**Issue by Titoos** [WarEmu/WarBugs#861]
This item was changed today from one handed into great weapon, which is ok. The problem is, that it has dps rate as one handed weap: 25dps , while Chosens Deathaxe of Conquest and BG's Glaive of Conquest both have 36dps rating. Dunno what about slayer's version of the weapon, which I assume was fixed too.

**Comment by Tioos** [comment]
edit [from one handed into great weapon]

**Comment by xyeppp** [comment]
Can you somehow unequip the people that are wearing it right now?

**Comment by Tioos** [comment]
Agree, and if You increase it's dps they will be truly OP now :)

**Comment by Tioos** [comment]
Ok it has proper dps now, and it's Great Weapon, but it's looks like one hander :)

**Comment by Evildoor** [comment]
You can use abilities despite the warnings like "Great Weapon required". Closing.
