### ISSUE TITLE
Crash - Black screen & reboot

### ISSUE THREAD

**Issue by Tederic** [WarEmu/WarBugs#8610]
Hello,

I have a problem with ROR client, i have a black screen 2 per day & i must reboot my PC (keep on black screen & sound stop). I can't make a Alt TAB/ ALT F4 / Ctrl Alt Supp.

I can crash with no raison anytime : BG / RVR / IC or just make a culture on afk mode.

How can i get some log to communicate ?

OS : Win 10
RAM : 16 GO DDR4 3000+
SSD & I7 6700K
Radeon R9 290x

I have try all graphic config & desactivate all add on, no result.

**Comment by Luth-RoR** [comment]
Hello,

the bugtracker is only for bugs; please use the _support forum_ for _support_. Furthermore the RoR staff can't fix any hardware or OS problems the player might have.
