### ISSUE TITLE
Warrior Priest 2h weapon T4 epic quest reward has no procs anymore

### ISSUE THREAD

**Issue by amyristos** [WarEmu/WarBugs#8611]
My 2h Virtue has no procs at all.

**Comment by Luth-RoR** [comment]
![20161215143601_1_crop](https://cloud.githubusercontent.com/assets/8567481/21226163/936aeac4-c2d4-11e6-98a6-11746835a5d1.jpg)
![20161215143558_1_crop](https://cloud.githubusercontent.com/assets/8567481/21226164/9371a012-c2d4-11e6-8591-93385716d59e.jpg)
![20161215143554_1_crop](https://cloud.githubusercontent.com/assets/8567481/21226162/9369881e-c2d4-11e6-97e8-b203e25c9300.jpg)
