### ISSUE TITLE
Potential bug for Crafting skills 

### ISSUE THREAD

**Issue by Crisiteck** [WarEmu/WarBugs#8612]
Hi, 
I was playing today on my Choppa, Crocblanc, talisman making 175+. 
However, by talking (clicking) to the apothecary PNJ in the IC, I lost all my tali skills. 
Because of that, I also lost my crafting items as my bag size decreased and the content got destroyed.

If you can do anything about my tali skill, it is great. If not, too bad for me. 

Have a good day. 
Sincerely yours. 
C.

**Comment by Luth-RoR** [comment]
Did you just click him and got no confirmation window?

**Comment by Crisiteck** [comment]
I just clicked on the elf apothecary PNJ in Apex, the dialogue box opens and close, and the message "apothecary skill 1" appeared.

To reset crafting skills, are we not supposed to type .something anyway?

**Comment by Luth-RoR** [comment]
I just tested it; you must have clicked "Learn tradeskill" because if you just click "Goodbye" or walk away, nothing changes.
The commands _.respec gathering_ and _.respec crafting_ were just temporary workarounds and have been disabled in a patch a while ago.
