### ISSUE TITLE
[Bright Wizard] Metoh's Grille using Skin Texture 

### ISSUE THREAD

**Issue by Osgrim** [WarEmu/WarBugs#8613]
Image explains it.Its definately the skin texture as it matches the character. Also tested changing the characters skin colour and the bug changed colour to match. 

It looks like its distorting the mesh UV's underneath the clothing causing a spike. 

![oswulf_002](https://cloud.githubusercontent.com/assets/22075763/21247062/b10c695e-c324-11e6-862c-7f3258f6a440.jpg)

![screenshot_000](https://cloud.githubusercontent.com/assets/22075763/21247098/ec8a3ab0-c324-11e6-911c-b20a8ff555fa.jpg)

**Comment by Luth-RoR** [comment]
High likely a client side issue, but maybe a DB dev can change it to another texture.

**Comment by Osgrim** [comment]
![oswulf_003](https://cloud.githubusercontent.com/assets/22075763/21288082/e6c25678-c471-11e6-9aa1-8b5739025f08.jpg)

The same error on other players but it differs.

**Comment by Osgrim** [comment]
Females also have this problem. It seems to be pulling in textures from other items and overlaying them on top of the Helmets UVs for some reason. Its completely random from person to person. 

![oswulf_005](https://cloud.githubusercontent.com/assets/22075763/21288387/8f54a5fa-c479-11e6-97e8-fdd326e9f84f.jpg)

**Comment by Luth-RoR** [comment]
Hm, could it be that one of your .myp files in the RoR directory is damaged/buggy?

**Comment by Osgrim** [comment]
I replaced the myp with newly downloaded files only to be greeted with this error. 

Data.myp:
System.Exception: You need to stop application currently using the following file: data.myp
   at MYPHandler.MYPHandler.WriteFileToArchive(FileInArchive archFile, MemoryStream MS)
   at MYPHandler.MYPHandler.ReplaceFile(FileInArchive archFile, FileStream newFile)
   at RoRLauncher.Client.UpdateWarData()

**Comment by Luth-RoR** [comment]
Seems like only the metoh's grille texture is bugged then; thanks for clarification.

**Comment by Osgrim** [comment]
I'll try to acquire the bandit queen skin and post my findings here if you need me to.

**Comment by Luth-RoR** [comment]
No, it's ok, thanks a lot. DB devs can spawn any item to test it on the dev server.

**Comment by Torquemadra** [comment]
its the same item code, your pocket items are more than likely causing the issue, unequip them

**Comment by Osgrim** [comment]
I have no pocket items equipped.

**Comment by Osgrim** [comment]
Similat thing?

https://www.returnofreckoning.com/forum/viewtopic.php?f=74&t=18979&p=207640#p207640

**Comment by Luth-RoR** [comment]
Hm, could be as on the screenshots i see a halloween mask equipped. Can you try it jow it looks without the mask?

**Comment by Osgrim** [comment]
I dont have a halloween mask.

**Comment by Luth-RoR** [comment]
Oh, nvm i thought it was your BW on the pics with the demon mask.

**Comment by Kaelang** [comment]
No confirmation was provided. I am now going to close this issue.
