### ISSUE TITLE
Stompas of Havoc DB issue

### ISSUE THREAD

**Issue by coldnegative** [WarEmu/WarBugs#8614]
Stompas of Havoc which you can get from Gold Bag (T2 PQ) is Blue Item.
Probably DB issue.
It still gives Tome Unlock but not set bonus.
![romoz_108](https://cloud.githubusercontent.com/assets/9000735/21275086/2f82f08e-c3dc-11e6-983f-e62c86a32518.jpg)
![romoz_109](https://cloud.githubusercontent.com/assets/9000735/21275088/2f8615f2-c3dc-11e6-9616-de0125bb98b0.jpg)
![romoz_110](https://cloud.githubusercontent.com/assets/9000735/21275087/2f85e564-c3dc-11e6-9a05-4e2316ac0d44.jpg)
![romoz_111](https://cloud.githubusercontent.com/assets/9000735/21275090/2f885aec-c3dc-11e6-9081-afdcabb24206.jpg)
![romoz_112](https://cloud.githubusercontent.com/assets/9000735/21275089/2f86c858-c3dc-11e6-9998-1bcd27273f6b.jpg)

**Comment by Natherul** [comment]
should be fixed with the next update
