### ISSUE TITLE
[Knight of the blazing sun] Tactic "Mighty soul" changes the healing from "Stay focused!" to damage

### ISSUE THREAD

**Issue by Ansalein** [WarEmu/WarBugs#8620]
Don't work aura "Stay Focused!" (Heals with with negative values) 
![heydvald_000](https://cloud.githubusercontent.com/assets/24624378/21288198/71b638b8-c4b7-11e6-898f-a33354b1e201.jpg)

**Comment by Luth-RoR** [comment]
Works fine for me, maybe it's just a visual issue with the russian client.

![20161217181158_1_crop](https://cloud.githubusercontent.com/assets/8567481/21288505/1581cc10-c485-11e6-8079-8f90ba435268.jpg)

**Comment by Ansalein** [comment]
No, the same situation in the English client. Aura deals damage instead of healing.
![default](https://cloud.githubusercontent.com/assets/24624378/21289302/a5e81e9a-c4d4-11e6-9ae8-f1f44498a312.jpg)

**Comment by Luth-RoR** [comment]
And it does **real** damage or is there just a - in the combat log?

**Comment by Luth-RoR** [comment]
Nvm, it's a bug with the tactic "mighty soul". At least i know now what this report https://github.com/WarEmu/WarBugs/issues/8605 meant.

**Comment by Luth-RoR** [comment]
I checked it by taunting altdorf rats just to be sure; the aura does indeed damage the knight instead of healing him.
