### ISSUE TITLE
Marauder: Touch of Rot (pve)

### ISSUE THREAD

**Issue by Squea** [WarEmu/WarBugs#8621]
Touch of Rot is not proccing or activating damage on the attacks of pve mobs. I don't pvp with Marauder, so I don't know if the handling is different in pve vs pvp. Tested by applying Touch of Rot immediately on mob and turning my back. Backlash, Warped Flesh, and Jagged Edge do proc; so some procs are working.

The tooltip says melee ability and not melee attack, this may be working as intended.

**Comment by Luth-RoR** [comment]
Yes, the tooltip says "melee ability" and PvE mobs do only autoattacks so far (with some rare exceptions, e.g. keeplords).
