### ISSUE TITLE
tok Insane in the Membrane tome unlock doesn't give the tile

### ISSUE THREAD

**Issue by iiiLollo** [WarEmu/WarBugs#8622]
Clicking on the "Scintillating Scale" gives the unlock "Insane in the Membrane" but not the corresponding tile "The Insane"

**Comment by Luth-RoR** [comment]
Known issue: https://github.com/WarEmu/WarBugs/issues/5748

**Comment by iiiLollo** [comment]
This is actually a different issue, the closed issue in #5748 is regarding the Scintillating Scale not giving the Tome unlock, which is fixed via workaround. This is the tome unlock doesn't give the tile and this bug is still present.

**Comment by Luth-RoR** [comment]
True, i misunderstood.

**Comment by Lheana** [comment]
When I equiped the "Scintillating Scale" I had the unlock, and the title "The Insane", as can be seen on screenshot.
![anaehll_303](https://cloud.githubusercontent.com/assets/11537611/21406045/d4f7a096-c7c9-11e6-8b42-76acd37954f2.jpg)

**Comment by Luth-RoR** [comment]
Thanks.

**Comment by iiiLollo** [comment]
On my unlock the title name is missing, 
![capture-no title](https://cloud.githubusercontent.com/assets/15178815/21416677/190b841e-c815-11e6-8469-050e67d774bd.JPG)
and it's not in the title page
![empty](https://cloud.githubusercontent.com/assets/15178815/21416681/1b929042-c815-11e6-83ec-5ffb58d1871f.jpg)

**Comment by iiiLollo** [comment]
Confirmed, re-equipping the scale unlocked the title
