### ISSUE TITLE
willpower from gear not contributing disrupt to getstats

### ISSUE THREAD

**Issue by footpatrol2** [WarEmu/WarBugs#8624]
Basically what the title says. 

![willpower - copy](https://cloud.githubusercontent.com/assets/19285115/21291171/5fc3df70-c48a-11e6-8eb9-5ce9cd3b5f3d.png)

**Comment by wargrimnir** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=16694

Intentional change from live.
