### ISSUE TITLE
Kotbs and Ironbreaker 2H epic weapons have 1 proc

### ISSUE THREAD

**Issue by amyristos** [WarEmu/WarBugs#8634]
Is supposed to be that way or is it a bug ? All 2H epic weapons for Kotbs and Ironbreaker have 1proc instead of 2.

**Comment by Blaqwar** [comment]
All tank Epic quest weapons have one proc only (Order and Destro). This is most likely intended.

**Comment by Luth-RoR** [comment]
Yes and the procs are actually very powerful.
