### ISSUE TITLE
Kotbs aura "Press the Attack" not enabled on other players sometimes 

### ISSUE THREAD

**Issue by amyristos** [WarEmu/WarBugs#8635]
![papaflessas_010](https://cloud.githubusercontent.com/assets/24459615/21294392/0a16c636-c544-11e6-8381-1c38abbcddf3.jpg)

Although it is active at Kotbs , in my wp it is not.It works when he re-enables it.
Sometimes that happens also with guard.

**Comment by Luth-RoR** [comment]
I guess that's just a visual issue?

**Comment by amyristos** [comment]
No. I checked my stats and no strength was gained, which means the aura is not enabled on my character although kotbs has it enabled. Same with guard. He gets zero damage when i get attacked although at his screen, guard is enabled.

**Comment by Luth-RoR** [comment]
Hm, very strange.

**Comment by Cimbas** [comment]
It also happens occasionally with other auras. In our case it's often Stay Focused with heal tactic. Restarting the aura fixed it for us everytime so far.
