### ISSUE TITLE
ToK unlock "A Defiled Life-Force"

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#8637]
This bestiary unlock for spires should be triggered by killing a hero in Mount Bloodhorn "Tainted Grove Spite" (9k 61k), who drops a "Tainted Spite Essence". Then talk to Bloody Sun Burner (chap 3 greenskin Mount Bloodhorn) to unlock it.

**Comment by Lheana** [comment]
Work-around possible ?

**Comment by Ryanfawkez** [comment]
Work-around added to the Burner in question.

**Comment by Lheana** [comment]
Forgot to precise: a work-around should be added for Order to 'Hammerstriker Hasher' in Dwarf Chap 3.
