### ISSUE TITLE
[T2/T3 Merge] Rats XP

### ISSUE THREAD

**Issue by jspieckermann** [WarEmu/WarBugs#8639]
Went to troll country and killed a rat with my level 16 slayer. Due to bolster level 18 champ rats are easier than normal level 15 pve mobs but grant 10 times the XP.

**Comment by Luth-RoR** [comment]
There shouldn't be any champ rats in the RvR lakes anymore.

**Comment by jspieckermann** [comment]
Just checked this morning. Troll country level 18 champ rats and they respawn on a low rate after killed

**Comment by Luth-RoR** [comment]
Where are they located? On the usual spots or somewhere else, coordinates would help.

**Comment by jspieckermann** [comment]
Usual spot .Not online at the moment but can provide coordinates later. Although like I said it is the usual spot close to order warcamp

**Comment by Soulwhisper** [comment]
He means Moulder Packmasters(Skaven).

**Comment by Luth-RoR** [comment]
I see thx.

**Comment by wargrimnir** [comment]
I can't find these in the DB, they may have already been removed. Currently the only thing with non-standard respawn rate is the Giants from the event. If these are specifically named Moulder Packmaster, there are no spawns set to that area for them on dev currently. So, probably fixed in next.
