### ISSUE TITLE
[White Lion] some more bugs :/

### ISSUE THREAD

**Issue by Zaccar20** [WarEmu/WarBugs#864]
- The war lion is very slow, he can't follow any enemy or myself. Pls fix this!

- Every time i switch between Ostland & Troll Country my war lion run away and don't come
back till i resummon him again

- Sometimes in combat the War Lions action-bar is hidded

- The Abilities of the war lion are not manually useable most of the time

- The war lion corpse lies very long around so u can spawn very very much bodies

**Comment by Tesq** [comment]
![tesq_134](https://cloud.githubusercontent.com/assets/7527415/8368747/cc81c0b8-1bae-11e5-9bc4-29e46d7b96a0.jpg)

**Comment by ozarmidrashim** [comment]
Corpses will be fixed in next.

**Comment by Zaccar20** [comment]
Nice.
The speed too? would be great :)

**Comment by ozarmidrashim** [comment]
Nope. That requires more work on the follow code than I have time to do.

**Comment by Zaccar20** [comment]
Ok,
i also notice that at some areas the Lion is fast enought to follow me
and at other hes slow if this help by found the problem.
Pls let us now if the speed is fixed.
U do a great work, and the other devs also of course!

**Comment by Zaccar20** [comment]
- Feline Grace don't work correctly
Its remove all roots and snares from you,
but you are not immune for the next 10 sec, they can slow me immediately again after aktivate

**Comment by Evildoor** [comment]
All of these were fixed or reported elsewhere. Feline Grace problem should have been reported separately, but it should be working now. Closing.
