### ISSUE TITLE
[Tactic][Stats][Slayer] Breaking Point Tactic Causing Negative Crit Chance. 

### ISSUE THREAD

**Issue by Osgrim** [WarEmu/WarBugs#8640]
While buffing crit chance via renown points I noticed it wasnt increasing crit chance. While having Breaking point tactic equipped. 
![osgard_040](https://cloud.githubusercontent.com/assets/22075763/21297702/58fb56e4-c57c-11e6-8df0-2d192de7c648.jpg)

![osgard_041](https://cloud.githubusercontent.com/assets/22075763/21297707/633e8e5a-c57c-11e6-90e5-1febbdccacad.jpg)

**Comment by Luth-RoR** [comment]
The character window doesn't work 100% correct. Always type .getstats into the chat window to get your real stats.
With the tactic:
_CriticalHitRateReduction -10 [(0 + -10) x 1]_
With the tactic and Futile Strikes III renown spec:
_CriticalHitRateReduction 5 [(15 + -10) x 1]_
