### ISSUE TITLE
Boomin business + my stack bug

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#8646]
i have a stack issue in the event quest, i cannot reset the stacK; reset the quest and drop or consume one firework make the previously cancelled  number in db stack with the inventory one 

it dosent allow me to complete it tough even if i have 76/20 etc

every time i reset it return to 0, but once i either dropo or consume/move  something stack issue came back again.

![tesq_147](https://cloud.githubusercontent.com/assets/7527415/21316440/0b6d3e58-c601-11e6-8e52-8842452e70ad.jpg)

bugged char is tesq only

**Comment by Ryanfawkez** [comment]
You should be able to hand in the quest when you have gone past all the requirements.

**Comment by Tesq** [comment]
i manage it somehow

**Comment by tlitschye** [comment]
HOW? I tried all kinds of variants, no success
