### ISSUE TITLE
Revoltin' Gobbos - Public Quest Chapter 11 Dwarfs

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#8649]
- [x] Stage 1 needs to kill 100 Moonfang Stickpointa.
There are only a few of them inside the PQ...it takes forever to complete first stage...either reduce it down to 50...or fill the area with more Stick pointa.I think adding more mobs is more appropriate.PQ area is empty atm.
- [x] ~~Stage 2 looks impossible...even with 9 Players of Tier 3...! Because Champions are linked with Hero...so if you pull 1 all come to you.~~
![warhammer online age of reckoning 12 19 2016 - 18 37 40 01](https://cloud.githubusercontent.com/assets/16864486/21321848/3edcb0d4-c61f-11e6-86d1-cc43e75ba99a.png)

**(Need to unlink all mobs)**

**Comment by Natherul** [comment]
Added some more gobbos, but i'm not sure about the hero being an issue since its a hard PQ designed for 9+ players. left that stage as it was. (the PQ is not meant be to able to do solo or 2 players)

**Comment by Soulwhisper** [comment]
Yeah you are right.Its fine.Just the mob linking system make it hard because if you pull 1 all of them come.
