### ISSUE TITLE
Sweating the Stone - Public Quest Chapter 14 High Elves

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#8650]
- [x] Stage 1 needs to kill150 chillguards.Same issue with #8649.Mobs are not balanced.Either reduce it down to 125 or 100 or just add more/replace some Chillguards.Takes wayy too long to complete it.
- [x] Stage 2 spawned Adamant Guards but objective wants to kill 4 Chillguards again.Cant get past Stage 2.
![warhammer online age of reckoning 12 19 2016 - 19 03 25 02](https://cloud.githubusercontent.com/assets/16864486/21321527/ed6ca7f0-c61d-11e6-821b-ac377dc32614.png)

**Comment by Natherul** [comment]
fix is pending for the pq with next update.
