### ISSUE TITLE
Black Orc No Choppin' Me and Follow 'me Lead

### ISSUE THREAD

**Issue by bozzax** [WarEmu/WarBugs#8653]
Doesn't stack like it did on live

FML gave a ft buff and NCM buffed all in range inc ft

**Comment by Luth-RoR** [comment]
Maybe an intended fix, don't know.

**Comment by bozzax** [comment]
Makes little sense in that case as the right tree is utter garbage and this effect (from an 11pts tactic) pretty much can be achieved by moving guard and using FML

**Comment by Luth-RoR** [comment]
I was just guessing, waiting for confirmation.

**Comment by Silentguard** [comment]
Reported similar issues long time ago about no tactic effect stack with abilities, iirc "Dat was great" and this one has no effect over common abilities buff\debuff.

**Comment by ozarmidrashim** [comment]
Intentional. Will not replicate.
