### ISSUE TITLE
Danurgi's Rangers - Public Quest Greenskin Chapter 5

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#8656]
- [x] ~~This ghost chest needs to be removed from the PQ area.~~
![warhammer online age of reckoning 12 19 2016 - 22 27 12 03](https://cloud.githubusercontent.com/assets/16864486/21328851/795a2452-c63e-11e6-92b8-fb9a53cd3303.png)

**Comment by wargrimnir** [comment]
This can be closed.
