### ISSUE TITLE
Firebeard's Slayers - Public Quest Destruction Greenskin Chapter 5

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#8657]
- [x] The white area misses PQ tracker and killing Slayers doesnt count them nor give influence.
~~PQ ID area needs to be extended all the way to the beach and make all Slayers count in PQ objective.~~
- [x] ~~Ghost chest needs to be removed from the PQ.~~
![warhammer online age of reckoning 12 19 2016 - 22 57 32 04](https://cloud.githubusercontent.com/assets/16864486/21328920/c7383498-c63e-11e6-837e-6409e38e5aef.png)

**Comment by wargrimnir** [comment]
Removed Sea Anvil Slayers nearby that were not included. Others on the beach will stay as they're far enough away from the PQ that no one should be confused by them. The PQ chests we will handle once they can be safely removed. No need to open tickets for each PQ, just one is fine.
