### ISSUE TITLE
Up the Creek Without a Battle - Public Quest Greenskin Chapter 5 

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#8658]
- [x] Stuck in Stage 2.Mob respawn issues same with #7143 .
![warhammer online age of reckoning 12 19 2016 - 23 27 34 05](https://cloud.githubusercontent.com/assets/16864486/21329843/76ccc8e8-c643-11e6-9730-a76cc81eff27.png)

**Comment by wargrimnir** [comment]
Added an additional set of mobs in case some are killed without counting towards the PQ.

**Comment by Soulwhisper** [comment]
Works fine now!
