### ISSUE TITLE
"Where's Da Wotnot" Quest Greenskin Chapter 4

### ISSUE THREAD

**Issue by TheLordboud** [WarEmu/WarBugs#8660]
"Find and defeat Friznik Fizzlefang. He will be a tough challenge alone, but Brootus has promised to join the fight. When Friznik is defeated, speak to Brootus."

Sadly, while fighting the Champion Friznik, Brootus does not appear anywhere, or helps you in the fight, thus making it way too hard /annoying to fight Fizzlefang.

**Comment by Luth-RoR** [comment]
Dynamic spawning mobs doesn't work yet afaik, maybe the missing NPC can be placed around the other one in the meantime.
