### ISSUE TITLE
Invisible Chests at PQ's

### ISSUE THREAD

**Issue by wargrimnir** [WarEmu/WarBugs#8661]
We may be able to remove these chests and still keep the functionality. Mostly Destro PQ's in the game have them. Once we determine if they're still needed, or just old holdovers from days gone past, we may remove them.

![](http://i.imgur.com/drQJkEl.png)

**Comment by Soulwhisper** [comment]
Good to know.I will stop reporting them then.

**Comment by Soulwhisper** [comment]
Do you want me to report the PQs that have this?

**Comment by Soulwhisper** [comment]
Holmsteinn Revisited - PQ Chaos Chapter 2
Danurgi's Rangers - PQ Greenskin Chapter 5
Firebeard's Slayers - PQ Greenskin Chapter 5
Ruins of Schloss von Rubendorff - PQ Empire Chapter 2
Loryndaal - PQ Dark Elf Chapter 16
Stoneclan's Demise - PQ Chaos Chapter 21

**Comment by Ryanfawkez** [comment]
We'll have to look into all the 'Chest' spawns, GO ID 188. There's 222 of them in total and some are for quests/ToK unlocks.
