### ISSUE TITLE
WP - Intimidating Repent 

### ISSUE THREAD

**Issue by Mortkin** [WarEmu/WarBugs#8662]
The tatic is not working as it should.

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

**Comment by Mortkin** [comment]
sorry dont get it? should i post more info or what?

**Comment by ozarmidrashim** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=8768&p=92913

Book players don't get to benefit from Intimidating Repent here
