### ISSUE TITLE
KOTBS. More than 3 auras

### ISSUE THREAD

**Issue by Stalkerbrncoat** [WarEmu/WarBugs#8663]
![asentinel_000](https://cloud.githubusercontent.com/assets/24666606/21340462/be5e95cc-c654-11e6-805d-e02e0aef6359.jpg)
I have seen where I can turn on 4 auras and it seems like they are running for my group as well.

**Comment by Stalkerbrncoat** [comment]
I also will be out of town for a few days for holidays. Everyone have a good holiday. Hope you can see the image well enough. It does have me with 4 auras running.

**Comment by Luth-RoR** [comment]
Maybe the same root as https://github.com/WarEmu/WarBugs/issues/8635

**Comment by ozarmidrashim** [comment]
Can confirm same root

**Comment by Paleolog77** [comment]
You hide your party window. May be another kobts in party with you.
