### ISSUE TITLE
PQ Scoreboards Visual bugs

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#8664]
## **All PQ Scoreboard Visual bugs in here.**
------------------------------------------------------------------------------------------------------------
### **Ruins of Schloss von Rubendorff - PQ Empire Chapter 2**
![1](https://cloud.githubusercontent.com/assets/16864486/21351283/73884f82-c6c4-11e6-8846-b60fbf9d8ee7.jpg)
![2](https://cloud.githubusercontent.com/assets/16864486/21351284/73b0b6ac-c6c4-11e6-809a-af0409bcd360.jpg)
![3](https://cloud.githubusercontent.com/assets/16864486/21351285/73b51d78-c6c4-11e6-834d-60737e6b434c.jpg)

**Comment by Soulwhisper** [comment]
**### Up the Creek Without a Battle - Public Quest Greenskin Chapter 5**

**Comment by Soulwhisper** [comment]
### **Assault on Coal Ridge Depot - PQ Dwarf Chapter 6**
![warhammer online age of reckoning 12 21 2016 - 20 15 40 05](https://cloud.githubusercontent.com/assets/16864486/21400810/7ee56d3c-c7ba-11e6-9e2e-3d9468332a39.png)
You opted out of this loot roll.
![warhammer online age of reckoning 12 21 2016 - 20 15 52 06](https://cloud.githubusercontent.com/assets/16864486/21400811/7eed1c08-c7ba-11e6-88da-19785ddb0b30.png)
Then stucks like this forever.
![warhammer online age of reckoning 12 21 2016 - 20 17 50 07](https://cloud.githubusercontent.com/assets/16864486/21400828/96e7e284-c7ba-11e6-9bd3-ca82fc5f3a9a.png)

**Comment by Soulwhisper** [comment]
### **Shrine of the Dragontamer - PQ High Elf Chapter 21** 
Doesnt show scoreboard.Stucks like that(on screenshoot) for ever + it tells you before that, that you havent participated enough to get a reward.
![12345](https://cloud.githubusercontent.com/assets/16864486/21353453/b491837c-c6ce-11e6-88b8-e55b42185238.jpg)

**Comment by Razielhell** [comment]
### **Long Drong and the Slayer Cove - PQ Greenskin Chapter 9** 

What you see. Providing a video too.
![warhammer online age of reckoning 02 12 2017 - 19 08 08 14](https://cloud.githubusercontent.com/assets/16864486/22864391/435f53d6-f159-11e6-9b7d-b5ef827833d7.png)
![warhammer online age of reckoning 02 12 2017 - 19 09 44 15](https://cloud.githubusercontent.com/assets/16864486/22864392/4362bfda-f159-11e6-862b-33bfdb507854.png)

**Comment by Razielhell** [comment]
### **Reiksguard Training Grounds.Normal Public Quest Destruction Chaos Chapter 22**

![warhammer online age of reckoning 03 28 2017 - 17 42 36 02](https://cloud.githubusercontent.com/assets/16864486/24411233/10f88e56-13de-11e7-8b1f-7db3bfdf29f7.png)

**Comment by Lheana** [comment]
Should have been fixed with patch of 07.12.2019.
