### ISSUE TITLE
Returned mail not returning with attached items

### ISSUE THREAD

**Issue by Arbaal** [WarEmu/WarBugs#8665]
Hi
I sent some mail to another toon to salvage. I have been away travelling and came back and the mail has been returned to the sending character but without all the items. There was six mails worth. Not happy. Not whinging but this kind of thing totally saps my will to play. Levelling trade skills is that much more difficult but this issue doesn't just affect that, it is far reaching and may also affect the economy.

**Comment by Luth-RoR** [comment]
Yes, mail attachments are deleted after 30 days. Maybe one day it works like on the mythic servers, but that is no priority as people can simply take out the items before the 30 days are over. 
I guess to let people abuse the mail system as a bank vault extension could also put unnecessary pressure on the DB atm.
