### ISSUE TITLE
Intimidating Repent

### ISSUE THREAD

**Issue by Mortkin** [WarEmu/WarBugs#8666]
Test the tatic and is not detauting enemies within 30 feet of my target, i remember the tatic used to work , maybe its some kind of bug?

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=18929

**Comment by Mortkin** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=18929
