### ISSUE TITLE
Repetitive quests at Eatan's WC: "Solemn defense of Eataine"

### ISSUE THREAD

**Issue by Paleolog77** [WarEmu/WarBugs#8668]
Usually, at any WC we have repetitive quest on 25 enemy killing, and on castle capturing. At Eatan WC we have two quests on 25 enemy killing. I think two of the same quest is it a bug. Should be a quest to capture the castle. 
![5](https://cloud.githubusercontent.com/assets/23325288/21391235/d67c3554-c79b-11e6-9b6e-18ca99cd7398.jpg)
![6](https://cloud.githubusercontent.com/assets/23325288/21391243/de18379a-c79b-11e6-9e10-dc26f56666f3.jpg)

**Comment by Ryanfawkez** [comment]
Solemn Defense quests are the 25 killquests in Elf zones. The keep capture quests in all end zone were disabled before. Enabling them all now, as all zones start with one keep for each side.
