### ISSUE TITLE
Scout's Resolute Tasset belt has no appearence

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#8674]
- This is mostly found in blue bags of some low chapter PQs.
![warhammer online age of reckoning 12 22 2016 - 10 22 49 08](https://cloud.githubusercontent.com/assets/16864486/21419884/0ac0fbc8-c833-11e6-804f-f7c364b6b491.png)

**Comment by wargrimnir** [comment]
These are going in the dumpster when we start the itemization phase for PQ's.
