### ISSUE TITLE
[Destru][Quest: Worthy Battle]

### ISSUE THREAD

**Issue by Ghostroo** [WarEmu/WarBugs#8675]
"Slay Nordland Millers you find hiding throughout the Pillage and Plunder Public Quest"

Today I noticed the Millers do not seem to be spawning. Specifically, the one by the central cart, the two on the windmill platform and the one by the northern cart.  Nordland Swordsmen are spawning. I scouted around the site and cannot see any Millers.

Coord 53594, 7690

**Comment by wargrimnir** [comment]
Fixed in next with PQ implementation.
