### ISSUE TITLE
ToK unlock "Deadly When Dead"

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#8676]
This bestiary unlock for giant scorpions should be triggered by killing Poisontail Pincers and Poisontail Stingers in Shadowlands (3k 41k), until receiving the unlock "Deadly When Dead". Don't know more about this unlock, it is not linked to a dropped item, nor a certain number of Pincers/Stingers killed. I killed about 60-70 Poisontail Pincers/Poisontail Stingers and did not have anything.
(Maybe devs know more about it ?)

**Comment by Ryanfawkez** [comment]
Look on HammerWiki for ToK unlocks. It has a lot of documentation that will help us determine whether something can be fixed or not.

http://warhammeronline.wikia.com/wiki/Deadly_When_Dead

We cannot fix this at the moment, as it is a Bestial Tactic fragment unlock. Also, requires specific killcount coding which we do not have for unlocks such as this.

**Comment by Lheana** [comment]
I always base my information on what there is in this website. Nevertheless, I wanted to report it in case you had more information than HammerWiki.

**Comment by Luth-RoR** [comment]
Closing until fix is available.
