### ISSUE TITLE
Penace buggy on WP

### ISSUE THREAD

**Issue by Buschfrau1** [WarEmu/WarBugs#8677]
The m3 skill on WP/DoK is bugged it throws NullPointRef and you instakill someone + you are stuck in animation for the rest of the zone.

here are some screenshots: 

http://imgur.com/a/Ven7s

greetings Thebest

**Comment by gke96** [comment]
![horsewhisperer_059](https://cloud.githubusercontent.com/assets/11146551/21423998/0c2a3236-c851-11e6-82fd-fc706fdaa2e2.jpg)
![horsewhisperer_057](https://cloud.githubusercontent.com/assets/11146551/21424002/16ff5c72-c851-11e6-9f8a-f606ecf60612.jpg)
it insta killed me again after i respawned by the way. this happened a few tims until respawn bugged and it didnt respawn layed there dead

**Comment by Luth-RoR** [comment]
Will be fixed on next server restart.
