### ISSUE TITLE
event quest boomin buisiness

### ISSUE THREAD

**Issue by normanis** [WarEmu/WarBugs#8678]
hello i found some bug, in first i started it yesterday , previous quest was kill ogres and gnoblars i killed tham all and loot tham. today its buggy quest called boomin buisiness. i tooked tons of those fireworks and  they count in quest too much (overdone) need 10 fire works i have 22 need 20 coomon fireworks i have about 60. i delted tham all and start from begin( retake quest) and the same i loot tonns byt i cant give quest. somwhere in my inventory they are invisible and every time i take tham they count my all
![galins_003](https://cloud.githubusercontent.com/assets/23311386/21424259/4043755c-c84a-11e6-8a0f-01b720962c72.jpg)
![galins_004](https://cloud.githubusercontent.com/assets/23311386/21424261/4047de62-c84a-11e6-954f-2d50506846f2.jpg)
![galins_005](https://cloud.githubusercontent.com/assets/23311386/21424260/40478dea-c84a-11e6-9e66-6f588722305d.jpg)
![galins_006](https://cloud.githubusercontent.com/assets/23311386/21424262/40483de4-c84a-11e6-9ae3-7d5c8dd593a6.jpg)

**Comment by normanis** [comment]
i reloged also

**Comment by Ryanfawkez** [comment]
Just hand in the quest at the mentioned NPC.

**Comment by normanis** [comment]
i cannot give back that quest because npc dont recognise it complited. evry time i start it from begining  quest counts invisible fireworks or beer kegs and its always ends i have over done

**Comment by Luth-RoR** [comment]
Then i guess either your normal or your crafting inventory was full at the time you wanted to claim the quest reward; afaik you'll have to wait to hand in the quest until the server restarted, then you should be able to complete it, but **only if both inventories have room**.

**Comment by normanis** [comment]
ok thx for help, meryy christmass
