### ISSUE TITLE
ToK unlock "A Trail of Pure Vile Evil"

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#8679]
This bestiary unlock for Plaguebeasts should be triggered by following different steps in Ostland (20k 15k)  :

- First kill one of the four zealots named "Plaguesworn Noble" around the nurgle altar
- When the zealot respawns, all the four should start a ritual
- This ritual spawns "Noxious Plaguebeast" (Champion)
- Kill this Noxious Plaguebeast, and he should drop an item [don't know the name but it looks like a potion]
- [Destro] Once this item looted, talk to Voxanna The Transmuter (chap 6 Chaos in Troll Country) to have the unlock 'A Trail of Pure Vile Evil'

**Comment by Natherul** [comment]
Currently not possible to implement, need client control
