### ISSUE TITLE
MOBs make hotbar offensive abilities red - Visual bug

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#8681]
@wargrimnir
- Putting a sample video.
https://www.youtube.com/watch?v=4akkDZwergY
- [x] Herald of Doom in Macabre Fervor PQ.
- [x] Grave Diggers in Grave Diggers PQ.
- [x] Blighted Demagogues in The Blighted Farm PQ.
- [x] Guardian White Lion in Stone of Valetear PQ.
- [x] Beastlord Kahn in Cold Hearted Predators PQ.
- [x] Anurion the Green in Ghyran's Embrace PQ.

**Comment by Luth-RoR** [comment]
The number turns red, because dead targets can't be damaged/affected by most abilities; the same happens when you are out of range etc.

**Comment by Soulwhisper** [comment]
@Luth-RoR Dead? o.O Check the video :P Also a text pops in mid-screen that says Target it not attackable.

**Comment by Luth-RoR** [comment]
Ok, i thought you mean the position at 0:13 where the NPC is dead and the mouse arrow is moved repeatedly over the red abilities.

**Comment by Soulwhisper** [comment]
Nope.Im talking about 0:01 to 0:09 just before he dies.During combat in other words.

**Comment by Razielhell** [comment]
From 0:00 to 0:02 check hotbar buttons(numbers) are RED. And when i cast Bunch o' Waaagh Target is not attackable pops in middle screen.
https://www.youtube.com/watch?v=wTGr17n7XKs

**Comment by Razielhell** [comment]
Fixed in next.
