### ISSUE TITLE
Quest "Chosen"

### ISSUE THREAD

**Issue by Piemur** [WarEmu/WarBugs#8683]
Interacting with the "Altar of the Scepter" does not update quest status.

**Comment by lennip** [comment]
Update: the issue described by OP still exists. It happens in one of the last parts of the quest chain "Chosen" (Chaos chapter 8). The quest objectives are as follows:
![mutty_002](https://cloud.githubusercontent.com/assets/2891053/25179011/65baace0-2508-11e7-9d86-7a75ec7e336f.jpg)
I killed Dredvulos and obtained the Darkflame Scepter, that one validates normally.
However, the other quest objective is to find the Altar of the Scepter, but it can't be completed: there is indeed a clickable altar at the given location, but clicking it does nothing, when obviously it should validate the corresponding quest objective:
![mutty_001](https://cloud.githubusercontent.com/assets/2891053/25179308/9850c49a-2509-11e7-94b1-984788092f88.jpg)
Could you please reopen this ticket? Thanks!
