### ISSUE TITLE
Cant activate Keg slayer tittle

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#8685]
Yeah im talking about the tittle about your character.
In ToK it unlocks.You just cant activate it on your char.

**Comment by Ryanfawkez** [comment]
The heads-up display wasn't filled in. It should be in your title rewards section regardless.

**Comment by Soulwhisper** [comment]
It is indeed.

**Comment by Soulwhisper** [comment]
Nope...still cant activate it.

**Comment by Kaelang** [comment]
As this is a legacy issue, and lots has changed, please re-open if this issue persists as it should be fixed.
