### ISSUE TITLE
[Choppa/Slayer] All the DoTs that have been received in a Berserk(-50% armor+res) still do damage as if the character was in a berserk(with debuff armor and res) even if he dropped berserk in green area after receiving any DoT.

### ISSUE THREAD

**Issue by Killham** [WarEmu/WarBugs#8689]

**Comment by Pxl555** [comment]
DoTs are not dynamic in regards to resistances/armor but rather static. Meaning if you are resistance /armor debuffed for example and someone applies a dot , it will still tick for the same value when the resistance debuff wears off.

 I assume the same is the case for the slayer/choppa mechanic as it impacts those 2.

For further clarification you can take this as a reference:
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=16694

[DoT/HoT Precalculation]

The effects of the following are calculated for a DoT at strike time and not on tick:

- Offensive stat / Toughness contribution
- Armor/Resistance mitigation

**Comment by Luth-RoR** [comment]
Iirc according to devs only buffs/debuffs with fixed numbers (e.g. armor debuffs) work this way; percentage based buffs/debuffs (e.g. +10% damage ability or the slayer/choppa mechanic) should not.

Report needs evidence though.

**Comment by sotora** [comment]
Detaunt is percentage based (50%) and Dots are not modified by detaunt on your enemy in any way. It is all calculated on strike time and not on each dot tick.

**Comment by Luth-RoR** [comment]
It's well known that detaunts always were an exception in WAR.

This is about RoR specific changes:
_[DoT/HoT Precalculation]_

_The effects of the following are calculated for a DoT at strike time and not on tick:_

_- Offensive stat / Toughness contribution_
_- Armor/Resistance mitigation_
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=16694

It could also be that it is intended due to armor/resistance debuff, though i was told that percentage debuffs work on strike time.

**Comment by Silentguard** [comment]
Oh wow, thats an epic bug, every dps class in the game places his own debuff last except bw\sorc and none of their retotaions works as i should. What is reason of such implementation? I can guess it's for economy processor time and db requests, but you can don't need to request vars and recalculate on every tick step if just update initial dot instance tick value on target defense changed event.

**Comment by Luth-RoR** [comment]
The general handling is no bug and intended by the devs; discussions have to take place on the forum, not on the bugtracker.

**Comment by sioding** [comment]
Since DoT´s calculated correctly i will close this now.
