### ISSUE TITLE
Kills made by ranged channeled abilities

### ISSUE THREAD

**Issue by xyeppp** [WarEmu/WarBugs#869]
Something with Spine Fling makes the mob stay in a fake-alive state after I have killed him. 

He stops all animation and stands in one place at 0% and doesn't attack. I must use a melee attack to re-kill him only, ranged ones do not work. He dies properly after a few seconds when the spine fling on-hit effect shows on him and lets him die.
![github_012](https://cloud.githubusercontent.com/assets/12982209/8368566/f3ff2ec4-1ba3-11e5-8ec3-009f0db8a120.jpg)

**Comment by Evildoor** [comment]
Seems to be general problem with enemies killed by ranged chanelled abilities (Lots of Arrers/Rapid Fire, for example) - works on players too, i experienced this myself many times.
