### ISSUE TITLE
Rudrin Ironspigot NPC

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#8691]
- [x] Naked and sexy. 52k,45k
![warhammer online age of reckoning 12 24 2016 - 13 54 46 70](https://cloud.githubusercontent.com/assets/16864486/21466881/acb4b10a-c9e0-11e6-8a0f-76a0bbea24bf.png)

**Comment by Luth-RoR** [comment]
Is this the known bug (that happened also on WAR) when NPC/PC clothes are sometimes not loaded to the client? Or does he really have no clothes all the time?

**Comment by Soulwhisper** [comment]
Will test if further and post again.Tried to take and finish the quest he had to refresh him.But still he is naked.Will try with other toons and get back.

**Comment by Soulwhisper** [comment]
Nope.He is just naked.Someone needs to dress him.

**Comment by Natherul** [comment]
Leave the stuntie alone, he is as he is supposed :P http://warhammeronline.wikia.com/wiki/File:Rudrin_Ironspigot.jpg

**Comment by Soulwhisper** [comment]
Naked and sexy it is then!
