### ISSUE TITLE
ToK unlock 'Handy Dandy'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#8695]
This bestiary unlock for Chaos Mutants should be triggered by right clicking 10x 'Mutant Hands'. Mutant Hands drop correctly on Mutant around 22k 31k or 5k 32k in Talabecland. But right clicking on 10x Mutant Hands does not provide the unlock nor the assigned title 'The Unsullied'.

**Comment by Ryanfawkez** [comment]
Made a work-around at the Library/Disciple's Assistants
