### ISSUE TITLE
Troll Island - Public Quest Dwarf Chapter 11 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#8698]
- [x] In Stage 1 PQ tracker needs Bloody Sun Manglas but those mobs are Bloody Sun Big Breakas(They are Champions in Stage 1-should make them normal).Need to rename the MOBs to Sun Maglas i guess because on Stage 2 Objective needs Bloody Sun Big Breakas again(They are normal in Stage 2,should make them Champs).
- [x] Also Bloody Sun Breakas attack Trolls.Shouldnt.

**Comment by grunbag** [comment]
Fixed in next Patch
