### ISSUE TITLE
"Kinschel's stronghold" tunnel's door[Ostland]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#870]
This flag have a tunnel system that allow attackers to attack from tunnel, you need to fix doors (or add temp door).

61k; 8k
![tesq_136](https://cloud.githubusercontent.com/assets/7527415/8368673/a1a7395a-1bad-11e5-8670-ee0f932d8841.jpg)
![tesq_137](https://cloud.githubusercontent.com/assets/7527415/8368687/daded46c-1bad-11e5-9e5a-32d2606fa227.jpg)

**Comment by Evildoor** [comment]
I do believe that the lever was added first, and then a normal door.

**Comment by Tesq** [comment]
re open it, doors dont work

**Comment by Evildoor** [comment]
yeah, tested myself too, both doors are not working. Sorry, my bad.

**Comment by Ryanfawkez** [comment]
Fixed.
