### ISSUE TITLE
Chaos Ch 9 Quest: Chosen

### ISSUE THREAD

**Issue by Sayce78** [WarEmu/WarBugs#8700]
I have the Soulblight Stone from Blightgore and the next part of the quest is (per the Particulars):
"deliver the stone... by setting it on the Altar before the Chaos Portal in northern Troll Country."

I found the Altar in front of the portal in the "Tearing the Portal" PQ in northern Troll Country but clicking on it does nothing.

**Comment by Natherul** [comment]
currently not possible to fix as we cant have game objects as quest finishers. currently the turn in point is the same place as where you got the quest
