### ISSUE TITLE
Tomb of Kali'Amon - Public Quest Dwarf Chapter 13

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#8701]
- [x] Stage 2 Risen Kali'Amonar mobs in cave are untargetable.
- [x] I think in Stage 3 are the same mobs(Risen Kali'Amonar) guarding the Hero.Again untargetable.Hero is fine.
- [ ] If you could just remove chest spawn :p 
![maxeras_000](https://cloud.githubusercontent.com/assets/16864486/21468511/4e93e2ca-ca1d-11e6-8f34-62118ba9e8b4.jpg)

- PQ Tracker/Counter is really tricky/buggy in the caves.But most likely realated to this #6935.

**Comment by Hargrim** [comment]
NPCs are now targetable, ticket solved.

I will check about the chest, but no promises.
