### ISSUE TITLE
Skullsmasher's Boyz - Public Quest Dwarf Chapter 14

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#8702]
- [ ] In Stage 2 there are many Champion mobs that are outside of the PQ area.Either extend PQ tracker/area ID to the white circle or just put them inside.
![maxeras_000](https://cloud.githubusercontent.com/assets/16864486/21468546/c21a5b28-ca1f-11e6-8f07-87972479b55f.jpg)
![maxeras_001](https://cloud.githubusercontent.com/assets/16864486/21468547/c21e72a8-ca1f-11e6-8e31-24d74f194e64.jpg)

**Comment by grunbag** [comment]
Fixed in next patch
