### ISSUE TITLE
T1 PQ Raven Host Vanguard, Father Sigwalds Peasants

### ISSUE THREAD

**Issue by valancian** [WarEmu/WarBugs#8704]
The peasants that spawn with Father Sigwald in stage 2 of the public quest will at times become hostile and spawn in higher numbers, then they will focus one person and kill them very very quickly unless you flee. They are still blue while they kill you, so you cant fight back either. I've experienced this twice now.
![valancian_000](https://cloud.githubusercontent.com/assets/24758385/21469078/11ee932c-ca06-11e6-9f14-5adc44d0e9cf.jpg)
As you can see they turned their attention to me

**Comment by Soulwhisper** [comment]
Did you read the rules before posting a bug on bugtracker? There is already an opened ticket.  #6933

**Comment by valancian** [comment]
i apologise but i didnt know it was already an opened ticket. just wanted to bring attention to it.

**Comment by Soulwhisper** [comment]
Well this doesnt help.Even if you had the solution to the problem.

**Comment by valancian** [comment]
Again, Apologies. guess i acted a bit too quickly.
