### ISSUE TITLE
Marsh Conquest - Public Quest Greenskins Chapter 6

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#8705]
- Stage 1 half-works by killing 30/30 Warriors.0/3 Rock Lobbas dont work.

**Comment by Hargrim** [comment]
This quest is currently not active for Order - how did you manage to try to progress Stage I?

**Comment by Soulwhisper** [comment]
..Will check and tell you again. This was a month ago.

**Comment by Razielhell** [comment]
**_Sorry for late respond but was trying to figure out whats going on here :P_** 
- [ ] This is double function. NO PQ UI no nothing. But killing Hammerstriker Warrior rewarded me influence for DWARF Chapter 6 Storyline and not Greenskin. I think this is correct.
But the problem is that there is no PQ Tracker and you cant get past Stage 1 because Rock Lobbas dont work. Same for Order #7486 
![warhammer online age of reckoning 01 30 2017 - 01 24 24 248](https://cloud.githubusercontent.com/assets/16864486/22408971/fa64e1c4-e68a-11e6-99d1-9f1d180b7489.png)
