### ISSUE TITLE
Items missing stats

### ISSUE THREAD

**Issue by xyeppp** [WarEmu/WarBugs#871]
Murderer's blue items along with various rare are missing their stats.
Murderer's Chewtop only has +15 Toughness, meanwhile it should also have +19 ballistic as shown in http://www.warbits.com/gold-items-15211-Murderers-Chewtop.html

Same issue observed for the following:
Murderer's Bodyplate - Missing +15 Weapon Skill
Murderer's Eadplate - Missing +8 Willpower
Murderer's Embracers - Missing +14 Strength
Murderer's Gown - Missing +19 Intelligence
Murderer's Shoulderguards - Missing +15 Wounds
Murderer's Spellcrown - Missing +23 Intelligence
Murderer's Warpmantle - Missing +15 Intelligence
Ravager's Liegecollar - Missing +14 Intelligence
Slaughterer's Bracers - Missing +16 Intelligence
Slaughterer's Morkyfeets - Missing +16 Intelligence
Slaughterer's Squignoggin - Missing + 26 Ballistic Skill

I assume more rare items are affected, but to those I've seen in-game I cannot find any reliable reference. Will keep updating this with whatever I gather.

**Comment by wargrimnir** [comment]
These appear to be correct.
