### ISSUE TITLE
House Arkaneth HE Chapter 1 PQ - Friendly Mobs Attacking 

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#8712]
Hi, Merry Christmas to you!

I thought I'd have a go at the PQs now so much work has been going into them. Have killed some Dark Elves at this PQ, which gives influence fine, but have found that the friendly mobs they are fighting with then turn around and attack my character. 
![galinel_008](https://cloud.githubusercontent.com/assets/22262165/21485785/74a66062-cba0-11e6-9c9b-8c1ed7b5d6b7.jpg)

**Comment by Luth-RoR** [comment]
Hi,

Merry Christmas to you too. There is already a report open for the PQ: https://github.com/WarEmu/WarBugs/issues/4721 as it is for many other PQs.
