### ISSUE TITLE
ToK unlock "Broken Bones"

### ISSUE THREAD

**Issue by Iziel** [WarEmu/WarBugs#8713]
Broke Toof: (13k, 23k) Travel to Chaos Wastes and make your way to the coordinates given. Just Northwest of the Malevolent Warband Major, slay 100 Blood Spawns (Bloodbeasts of Khorne) until you are granted the tome unlock, "Broken Bones", allowing you to claim Broke Toof.
Does not work right, grands you some "???" Title and does not open 100 kills.

**Comment by Luth-RoR** [comment]
_Broke Toof is unlocked by killing 100 Bloodbeasts of Khorne, not Chaos Spawns._
https://github.com/WarEmu/WarBugs/issues/6842
