### ISSUE TITLE
Quest: Servitude [Talabecland]

### ISSUE THREAD

**Issue by Goobysnacks** [WarEmu/WarBugs#8714]
Quest description says to get rusted strongbox from bell tower, how ever that tower cannot be entered, there is magical barrier preventing it. There are ratlings inside that agro from inside but no strongbox.

Chaos quest, location Talabecland. loc: 300085 16790.

**Comment by Ryanfawkez** [comment]
Use the new entrance tunnel. Will move the questmarker to there.
