### ISSUE TITLE
Potent Refreshing Draught can't use

### ISSUE THREAD

**Issue by Paleolog77** [WarEmu/WarBugs#8719]
![7](https://cloud.githubusercontent.com/assets/23325288/21511840/cc60bca0-ccb6-11e6-8b8d-26301358e6e8.jpg)

**Comment by Luth-RoR** [comment]
What's your characters level?

**Comment by Paleolog77** [comment]
12 lvl, but still can't use.

**Comment by Luth-RoR** [comment]
Seems to be a general issue with all blue ones: https://github.com/WarEmu/WarBugs/issues/2437#issuecomment-166789485
