### ISSUE TITLE
BO guards not champions

### ISSUE THREAD

**Issue by xyeppp** [WarEmu/WarBugs#872]
The battlefield objective guards are incorrectly labeled as normal NPCs instead of champions. This is the case with both T1 and T2.

**Comment by ozarmidrashim** [comment]
Changed T2 ones to champs. Don't see much point in changing T1.

**Comment by xyeppp** [comment]
After research, the T1 ones are actually normal strength and one higher.
It is only the higher tiers that should have champions on them.

"For Tier 1,warhammer gold four of these guards are standard strength NPC monsters. The fifth guard is the commander of the battlefield objective is a Champion strength NPC monster. For upper tiers, the guards become considerably stronger requiring a stronger and larger force to capture them (often times 4 champion monsters and 1 hero)" 

Right now in T2 all 5 of them have been labeled as champions, meanwhile the sergeant should be higher than his guards. Sorry to nag you about this, but this is how it should have been.
