### ISSUE TITLE
[Am\Sham] Puddle effect size

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#8720]
Live war puddle size was a bit bigger of its visual effect size. Now it have this. At best you'll get a couple seconds till enemies crossing straight a puddle. Not even talking about kiting around it.
![rachik_001](https://cloud.githubusercontent.com/assets/13031465/21513733/1127ff7a-ccf7-11e6-88be-d4c4a86a3251.jpg)

**Comment by Silentguard** [comment]
https://www.youtube.com/watch?v=69pvebEbW8Q
1:48
2:09
5:25
9:04
11:05 - WE got snared behind puddle border while kiting back (note that she almost crossed puddle between effect apply ticks)

**Comment by Luth-RoR** [comment]
The real AoE ranges have been extracted directly from the 1.4.8 client: https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=17634
It's also unclear if the video shows the same position of the WE on the WE-players client and the AM one, or if there is a difference due to lag.
