### ISSUE TITLE
Number One Quest

### ISSUE THREAD

**Issue by Ghostroo** [WarEmu/WarBugs#8721]
Number One Quest Hand in Bug

Destruction side, Quest starts and ends in Inevitable City

introduction:
When the quest is complete and you return to IC to hand in, you cannot complete the quest even if you choose a reward as instructed.

Details:
When handing in to Laxinol after completing quest successfully, you can select a reward but the quest completion behaves as if you have not chosen a reward. Attached are screenshots of attempts.

Evidence: Screenshots included
![gibberer_002](https://cloud.githubusercontent.com/assets/17996297/21513947/664caaf6-cd0a-11e6-8f50-229e33510756.jpg)
![gibberer_003](https://cloud.githubusercontent.com/assets/17996297/21513948/664cdc24-cd0a-11e6-8cc2-1bf0afdf0e1d.jpg)

How to reproduce the bug:
Pick up quest in IC by speaking to Laxinol. 
Run the quest  by entering portal ( a short obstacle course), speak to Laxinol at the end of the course. 
Return to IC via the portal
Attempt to hand in to Laxinol while choosing either of the rewards.
Bug will manifest whichever reward you choose.

Logged out and tried to hand in again with the same results.

Laxinol coord IC: 20755, 35619
This is part of the Skaven quest line.

**Comment by Paleolog77** [comment]
you must select both
