### ISSUE TITLE
Destruction quest (Dark Elf): A newfound urgency

### ISSUE THREAD

**Issue by Arbaal** [WarEmu/WarBugs#8723]
The bolt throwers situated near the quest giver do not count toward the quest.

**Comment by Luth-RoR** [comment]
A screenshot would help.

**Comment by Arbaal** [comment]
Ok; there is some elves at the Caladain Steppe, right near Dark Elf Ch19 and I found those bolt throwers worked but not the ones at 52,57, on the ledge

**Comment by Razielhell** [comment]
Fixed in next.
