### ISSUE TITLE
Quest: Mourning Beauty

### ISSUE THREAD

**Issue by Goobysnacks** [WarEmu/WarBugs#8724]
Quest is Mourning beauty in talabecland, bell cannot be rang, door to the room is closed and cannot be opened. Quest giver is Anselma Selki.

Destruction quest.
Tower Loc: 19845 22626

**Comment by Natherul** [comment]
I added the bell and will see if I can fix more later, if I dont remember wrong from live you used to pres the rope in the room below, not opening the door... :P Again Ill see later what I can do

**Comment by Natherul** [comment]
will be fixed in the next patch. Cant implement like live (using the rope) but the doors are now working with bell inside
