### ISSUE TITLE
[Sham] Fury of da green mork stack decrease ability damage

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#8725]
Mork cast
![rachik_003](https://cloud.githubusercontent.com/assets/13031465/21520964/9396308a-cd33-11e6-9036-4c9653301a89.jpg)

Gork cast. Also tootlip damage mismatch.
![rachik_004](https://cloud.githubusercontent.com/assets/13031465/21521009/ed0408e0-cd33-11e6-917d-4933b0d3928c.jpg)

**Comment by ozarmidrashim** [comment]
Please read the notes of experimental mode.

**Comment by Silentguard** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=18310
If an ability is cast on another player, and consumes mechanic points, it will gain the following bonuses:
+ The bonus stat contribution will be derived from a factor of your total bonus stats from items, if this is higher than the ability's normal scaling stat. Reduced stat contribution works as normal.
+ The ability will cast using your Career Rank instead of your Mastery Level.

Gork ability losing damage while casting under mork stacks. As writen above it "cast using your Career Rank instead of your Mastery Level" which in this case are same. Did i miss something?
