### ISSUE TITLE
[Sham] Fury of da green not healing defensive target not in your party

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#8726]

**Comment by Luth-RoR** [comment]
Global changes to Shaman:
+ Fury of Da Green heals the group.

**Comment by Silentguard** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=18310
+ Fury of Da Green and Energy of Vaul will additionally heal for their base damage multiplied by the number of foes hit.

Same for ingame ab ex

**Comment by Luth-RoR** [comment]
Ingame: _.ab changelist_ shows it.
