### ISSUE TITLE
Renown points bug

### ISSUE THREAD

**Issue by Wagrash** [WarEmu/WarBugs#8727]
Hello, my SM character has 40 renown lvl, but only 35 points he can use
![sammael_000](https://cloud.githubusercontent.com/assets/16164209/21524321/53c3678c-cd26-11e6-90a0-75933e60cf1c.jpg)
![sammael_001](https://cloud.githubusercontent.com/assets/16164209/21524322/53f0b782-cd26-11e6-9c58-2f69b6ed89b8.jpg)

**Comment by Soulwhisper** [comment]
I think this is known and it will get fixed with client control? UI related? Visual bug only. @Luth-RoR

**Comment by Luth-RoR** [comment]
That's because it is an old char who with renown level 40 but only level 35; this was changed and now your renown level can't be higher than your character level. Just level up and you can use the other renown points (relog could be necessary after a level up, don't know).
