### ISSUE TITLE
ToK unlock 'Bossy Beastie'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#8728]
This bestiary unlock for Bestigors should be triggered by killing 'Khurraak Might-Horns' in Avelorn (37K 42K). Khurraak is missing, I could not find him.

**Comment by Blaqwar** [comment]
Khurraak Might-Horns can be found at 46k, 39k in Avelorn. He correctly gives the Bossy Beastie unlock.

**Comment by Luth-RoR** [comment]
According to http://warhammeronline.wikia.com/wiki/Khurraak_Might-Horns the spawn coordinates should be changed then (or the wiki entry 🙃 ).

**Comment by Blaqwar** [comment]
To be honest, he's standing in the middle of the main road, miles away from any other Beastmen. It would make heaps of sense for him to be spawned at that Herdstone instead. :)

**Comment by Lheana** [comment]
As said Luth, wiki says it should be around 37k 42k : http://warhammeronline.wikia.com/wiki/Bossy_Beastie but found him at 46k 39k and working. So nvm for this issue :)

**Comment by Luth-RoR** [comment]
Ok, i guess i just close it then.
