### ISSUE TITLE
Doing PQ alone - contribution is lost if you leave area before roll

### ISSUE THREAD

**Issue by Grock-r** [WarEmu/WarBugs#8734]
Did Siege of Bohsenfels (Ostland, Emp Ch.8) on my 16-17lvl Engineer a few times. On two occasions i did it completely alone with no other players even entering the area. Both these times i got no reward - clicking on the chest didn't do anything and no bag appeared in mail either. 

Basically what happened is i left PQ area before reward roll, which supposedly reset all my contribution.

First time i killed the final champion mob while i was in PQ area and rolling timer appeared for couple of seconds, i could even open the window and see that there was one **gold bag**, but as i was moving towards the chest i stepped out of PQ area and when i got back the rolling timer was gone and there was reset timer instead. 
I couldn't click on chest and got no reward. About 4 hours later there's still no mail from that try.

Some time(1-2 hours) later i was doing it again, now with few other guys. I got some rewards as usual, but at the end i left without finishing another stage - i got **blue bag** in the mail just a few minutes after that. This happened before my second solo attempt!

Second time solo i finished final champ mob outside of PQ area and when i got closer there already was PQ reset timer in place, once again i couldn't click on the chest and got no reward in mail (about 30-40 minutes has passed since that as of sumbitting this post)

I can try to replicate and make a video if this needs further evidence.

**Comment by Luth-RoR** [comment]
Seems like there is a misunderstanding: What was your level at the first time you tried to do the PQ?

**Comment by Grock-r** [comment]
Either 15 or 16, i quickly leveled up after i arrived in Ostland and i dont remember was it already in PQ area or not.

**Comment by Soulwhisper** [comment]
I understand everything you saying but oh boy...yes the whole system needs to be reworked.

**Comment by Luth-RoR** [comment]
Ok, then it's a known bug since the last patch, atm you can't get contribution/bags in T2 PQs under level 16.
