### ISSUE TITLE
Ork ch22 - Stunty Manes

### ISSUE THREAD

**Issue by Arbaal** [WarEmu/WarBugs#8739]
This quest requires a player to kill 20 dwarven defenders (any type) at the Slayer Keep in east Kadrin Valley. No dwarves count for this quest.

**Comment by Natherul** [comment]
Currently not fixable, we cant (to my knowledge) add multiple possibilities for objectives and as such currently only engineers counts towards this quest

**Comment by Luth-RoR** [comment]
Thanks, closing it then until it can be fixed.
