### ISSUE TITLE
[Choppa] Hurtin' Time

### ISSUE THREAD

**Issue by danissrv** [WarEmu/WarBugs#874]
For every target that you hit, it also procs on yourself also. For example if you hit 3 targets it procs 3 times in yourself. It should always trigger one time to you.

**Comment by Silentguard** [comment]
Confirm. Slayer also have same bug. This effects adds to ability as additional damage not like proc mechanic. Same as Choppa\Slayer M3 adds damage to ability onUse.

**Comment by Evildoor** [comment]
Closing since there was an argument about this and then a clarification in here: https://github.com/WarEmu/WarBugs/issues/1199 .
