### ISSUE TITLE
[PQ] Ankul Grob - Public Quest Dwarf Chapter 19

### ISSUE THREAD

**Issue by Halhammer** [WarEmu/WarBugs#8742]
Running the new PQs from patch, in stage 2 all mobs aggro at once if you attack one. Mabye scatter them a bit if possible.

**Comment by Soulwhisper** [comment]
Please change title of the ticket to : Ankul Grob - Public Quest Dwarf Chapter 19
For easier access.
In addition : 
- [ ] There are a couple of Oathbearers tha spawn inside of the PQ.They are aggressive and dont have names above their heads.
![maxeras](https://cloud.githubusercontent.com/assets/16864486/21548732/c773bd0a-cdf6-11e6-9145-f160f17e2922.jpg)
- [ ] This herda doesnt count in PQ.There are a few more Squigs and Herdas too that dont count.
![maxeras_101](https://cloud.githubusercontent.com/assets/16864486/21548749/e29a2308-cdf6-11e6-933a-3293e51a91d1.jpg)

**Comment by Natherul** [comment]
fixed all but the OP as I would want a go ahead from @Torquemadra before I address something like that :D 
Also fixed the last stage where the anvil part was completed by opening the door

**Comment by Soulwhisper** [comment]
- [ ] Doors have name :P 
![warhammer online age of reckoning 01 08 2017 - 17 21 48 07](https://cloud.githubusercontent.com/assets/16864486/21751294/d5e16a84-d5cd-11e6-9171-8af6f90cc122.png)
- [ ] On Stage 2 Drakk Guardian are double spawns.

**Comment by Hargrim** [comment]
Just checked - Drakk Guardians are not double spawns.

**Comment by Soulwhisper** [comment]
Will do a run again today and post a screenshot...

**Comment by Hargrim** [comment]
It seems that there is an issue with PQ spawns - from DB pov there are only 10 spawn of Drakk Guardians:

![image](https://cloud.githubusercontent.com/assets/16460565/22012603/323ac4d8-dc95-11e6-9c83-f94f6d6456ff.png)

Please create a ticket for this issue (sometimes NPCs spawn twice on PQ - reason unknown) and link this case to it.

I will try to scatter them a bit, one day. Maybe 5 groups instead of 3 big ones.

**Comment by Soulwhisper** [comment]
#8935

**Comment by grunbag** [comment]
there is no issue, i count 10 guardian, and 20 excavator

just need to split them

fixed in next patch

**Comment by grunbag** [comment]
close it please
