### ISSUE TITLE
Kotbs helmet "Karagaz casque" showing in belly

### ISSUE THREAD

**Issue by mbanane** [WarEmu/WarBugs#8743]
![huguenon_002](https://cloud.githubusercontent.com/assets/24827269/21545392/9fd1ebc4-cdd7-11e6-9464-8c99d79c8e10.jpg)

When not hidden, this helmet is not on my head (picture above).

**Comment by wargrimnir** [comment]
Fixed in next. It was set to a Squig Herder appearance.
