### ISSUE TITLE
Ambush Pass - Public Quest Dwarf Chapter 15 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#8744]
- [x] This mob doesnt count in the first Stage of the PQ.
![warhammer online age of reckoning 12 29 2016 - 16 35 55 05](https://cloud.githubusercontent.com/assets/16864486/21562456/b11d4fa4-ce81-11e6-87d6-7b32bb4d1266.png)
- [x] Also Stage 1 needs 75 of them and there are only around 10-15 in the area and scattered.A mob rearrangement would be nice!
- [ ] ~~Many Ambushas in Stage 1 are unattackable.You press the abilities but it cancels.Dont know why.They can take AoE damage though.Mostly those which are in sit position.~~

**Comment by Natherul** [comment]
will be fixed on the next update, I cant confirm the bug about not being able to attack some of them however, did some testing and it worked fine for me.

**Comment by Soulwhisper** [comment]
Still have the same issue with attacking some of Ambushas! Sometimes you can attack them but sometimes you cant...i dont know whats going on! Its too random.

**Comment by Luth-RoR** [comment]
Do they take damage from untargeted AOE?

**Comment by Luth-RoR** [comment]
Iirc one of the patches in the last months fixed many of these NPCs: maybe some remnants.

**Comment by Soulwhisper** [comment]
They bug for some seconds...if you move and try to attack them again you might succeed.

**Comment by Hargrim** [comment]
Added 10 more previously missing ambushas to the PQ.

There are 46 Ambushas around, enough to do it fast.
