### ISSUE TITLE
Red with Envy - Public Quest Dwarf Chapter 17 

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#8748]
- [x] These dont count in Stage 1.~~Also there is 1 more Red Basha somewhere in the middle of the PQ which doesnt count.~~
![warhammer online age of reckoning 12 29 2016 - 17 36 05 08](https://cloud.githubusercontent.com/assets/16864486/21547386/5edb777c-cdee-11e6-8d1c-a4f6558631bd.png)

**Comment by Natherul** [comment]
fixed in the next update, though I could not find the gobbo you are talking about in the middle of the camp, the ones on the hill are fixed
