### ISSUE TITLE
Night Riders - Public Quest Dwarf Chapter 16

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#8749]
- [ ] PQ Tracker timer is bugged(Check picture 32353 stuck).
- [x] ~~PQ area is populated with Sentries.Replace Sentries with Outriders.Too many of them.Only a few Outriders for the PQ...~~
![warhammer online age of reckoning 12 29 2016 - 17 22 20 07](https://cloud.githubusercontent.com/assets/16864486/21547685/43db0df0-cdf0-11e6-9afa-832660e753f6.png)

**Comment by Hargrim** [comment]
No need to replace Outriders - there are 25 of em, you can finish PQ with 3 runs around.

**Comment by Soulwhisper** [comment]
Whatever you say. Leaving it open for PQ Tracker visual issue.

**Comment by Kaelang** [comment]
There is no longer a timer for Stage 1. The timer for Stage 2 is working as intended.
