### ISSUE TITLE
NPC on BO too high lvl

### ISSUE THREAD

**Issue by xyeppp** [WarEmu/WarBugs#875]
On the sources I have found:
http://iml.jou.ufl.edu/projects/Spring09/porter_c/pvp/rvr.html
http://www.arksark.org/blog/474/warhammer-online-experience-and-1-03-patch-notes/ < This one specifically for T2
https://thewarhammertimes.wordpress.com/tag/battlefield-objective/ < this one describing the NPC status
The Tier 2 BO is mentioned as having a level 20 hero and 4x champions. 
Right now they're all 5x champion status, level 24 and I think hit a bit harder than they should - With one or two order around Morr, for example, it feels as if their damage is a bit excessive and the guards wipe a group with ease.

**Comment by saupreusse** [comment]
they had their levels adjusted after the t2 t3 merge. closing :)
