### ISSUE TITLE
Emberlight Mine Stronghold - Public Quest Dwarf Chapter 18

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#8752]
- [x] Need to add more Axegrindas and Armbreakas **inside the PQ**.Not only outside.
- [x] Needs a lot of mob rearrangement.~~In general a lot of irrelevant mobs in the PQ area(mostly outside because as i said inner is clear).~~
![warhammer online age of reckoning 12 29 2016 - 18 13 16 09](https://cloud.githubusercontent.com/assets/16864486/21548565/b5735fe4-cdf5-11e6-9da0-7c4b1201953b.png)

**Comment by Hargrim** [comment]
I added 10 of each orks outside of the dungeon - this PQ is about assaulting this complex and taking the banners, so Stage I should be done outside.

Also, I changed the name of Stage II banner to Tattered Bloody Sun Banner.

Kindly check after next DB push and let me know if we can close this.

**Comment by Soulwhisper** [comment]
- Ok Stage 3 double or triple spawns the squig champion mob.Also stage 3 mobs spawn from Stage 1...but they shouldnt.
- Stage 4 is a mess. Many mobs spawn on each other along with hero.

**Comment by Hargrim** [comment]
There are no squig champions in stage 3 and no multiple spawns. Are you sure this is the correct PQ you are talking about? Any screenshots?

**Comment by Soulwhisper** [comment]
Rorg Bloodgash.
![141](https://cloud.githubusercontent.com/assets/16864486/21981371/c1d0127a-dbef-11e6-9012-e8c5ee64afe7.png)

**Comment by Hargrim** [comment]
I checked today and saw only one - when did you check?

**Comment by Soulwhisper** [comment]
It was 2 days ago.

**Comment by Soulwhisper** [comment]
Pause at 6:03 and put slow motion x0.25 at video. Double spawn.
https://www.youtube.com/watch?v=It4f9kVe2GQ

**Comment by Hargrim** [comment]
It seems that there is an issue with PQ spawns - from DB pov there is only 1 spawn of Rorg:

![image](https://cloud.githubusercontent.com/assets/16460565/22012538/ca928b36-dc94-11e6-8768-13d9ba078c82.png)

Please create a ticket for this issue (sometimes NPCs spawn twice on PQ - reason unknown) and link those 2 cases to it.

About the 'issue' with NPC from other stages - I add them as cannon fooder, so this is not an issue, just cosmetics :).

Issue solved.

**Comment by Luth-RoR** [comment]
Opened https://github.com/WarEmu/WarBugs/issues/8935 and closing this.
