### ISSUE TITLE
Gates of Grung Grimaz - Public Quest Dwarf Chapter 16

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#8754]
- [ ] Reapers dance after you kill them.
https://www.youtube.com/watch?v=BQNxIii_omo
- [x] Deadknights dont count in Stage 2 and they suppose to be Champions.
![warhammer online age of reckoning 12 29 2016 - 18 34 29 10](https://cloud.githubusercontent.com/assets/16864486/21549235/7d7e26a6-cdf9-11e6-995d-48a6f74d5f27.png)

**Comment by Hargrim** [comment]
Dreadknigh is now a champion.
