### ISSUE TITLE
Quest Npc's Choas Start

### ISSUE THREAD

**Issue by Ravyen** [WarEmu/WarBugs#8756]
At Choas Start. Grimmnot Eatbasha and Madgr the Soul Reaper weared Clothes before i got Quests from them, somehow if i take a Quest from these two they seem to get naked. First i had to laugh cause they lose their clothes after talking with them. Wierd guys.

i found some similar reports but it were naked players or other Npc's Vendors ect. so i didnt knew where to put it. They also seem to be naked without taking a quest from them, so it may is another issue. 

Add: Edit: Seems to be they got their clothes back on if i go on with Quests. So its maybe not a high priority Bug.

Greets

**Comment by Blaqwar** [comment]
It's a client-side bug, NPCs sometimes spawning without clothing. If you relog it should be fixed and only NPCs who don't regain their clothing upon relog is an actual server-side bug that they can fix.

**Comment by Luth-RoR** [comment]
Yes, well known and it happened on the mythic servers too sometimes.
