### ISSUE TITLE
Stonetroll Dark Band bug

### ISSUE THREAD

**Issue by raptor915** [WarEmu/WarBugs#8760]
The stonetroll dark band, an influence reward in T2 open RvR, is bugged for chaos. It auto unequipped and now it says its only usable by blackguard (I am a chosen right now, username is Raronael).

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/7007

**Comment by Ryanfawkez** [comment]
Intended. IDs were swapped months ago to fix its appearance in the Tome of Knowledge.
