### ISSUE TITLE
Multiple ressource delivery

### ISSUE THREAD

**Issue by ZaruLol** [WarEmu/WarBugs#8770]
Recently I was in Caledor and a player (as seen on the screenshot) was able to deliver the ressource he drags multiple times.

I assume this is an bug or can someone help me or the other player to resolve this fact.

The other player said to me, the ressources were gone as he was killed by a destruction player.

![zaruo_043](https://cloud.githubusercontent.com/assets/16409087/21580782/415f6eea-d011-11e6-8dc8-63dc1f334f53.jpg)

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/8769 https://github.com/WarEmu/WarBugs/issues/8236
