### ISSUE TITLE
Auctioneer 

### ISSUE THREAD

**Issue by kotsosman** [WarEmu/WarBugs#8771]
There seems to be a bug with auctioneer, when you cancel an auction after you click ok the item continues to be shown in the list. if you cancel it again and click ok then it is removed from the list. when you go check the mail you get 2 mails with the same item. i have no idea how to reproduce this or if it works with certain items only or if there need to be more than a certain amount of auctions for this to happen. has anyone else seen this?

**Comment by MaxHayman** [comment]
Should be fixed
