### ISSUE TITLE
ToK unlocks 'Tethlis the Slayer' and 'Caledor the Conqueror'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#8777]
These History & Lore unlocks in Caledor should be triggered by :

- For 'Tethlis the Slayer', interacting with a book named 'Chronicle of the Phoenix Kings' around 9k 3k in Caledor
- For 'Caledor the Conqueror', interacting with the bust 'Phoenix King Caledor I' around 42k 40k in Caledor

Interacting with 'Chronicle of the Phoenix Kings' provides the wrong H&L unlock : 'Caledor the Conqueror'. Interacting with 'Phoenix King Caledor I' does not give anything.

**Comment by Natherul** [comment]
should be fixed in the next update
