### ISSUE TITLE
Stats tactic[Destruction][Order][emulator]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#878]
Seems stats tactics like rugged after a zone change do not add/display the value, you need to unequit and re equit them again, dont know if it's only graphic bug or not but it is probably.

**Comment by ozarmidrashim** [comment]
Graphical issue. Select self to fix, I think.

**Comment by xyeppp** [comment]
I noticed with Aiminy Quickly and this bug, every other cast I get is reduced to 1s as if the tactic was working, but mostly it still cast a 2sec.

**Comment by Evildoor** [comment]
AFAIK, this was fixed. Focused offence has a visual bug, but it's not a stat tactic. Closing.
