### ISSUE TITLE
ToK unlock 'The Black Heart Coven'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#8782]
This History & Lore unlock should be triggered by interacting with 'Pile of Skulls' in Dragonwake RvR area, halfway down the cliffside around 39k 40k. It is not possible to interact with 'Pile of Skulls'.

**Comment by Natherul** [comment]
should be fixed in the next update

**Comment by Tibdum** [comment]
The History & Lore Unlock 'Pile of Skulls' is not triggered when interacting with the Item and the mouse cursor is not switching to a 'hand' like an interaction. 
![Tibdum_028](https://user-images.githubusercontent.com/47664666/69006254-15178100-0935-11ea-9102-04f2b1bf97eb.jpg)
