### ISSUE TITLE
ToK unlock 'The Lothern Seaguard' [Destro]

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#8786]
This History & Lore unlock is triggered by interacting with 'Seaguard Banner' in Eataine near High Elf chap 15. This unlock works as order, but destro can not reach the banner because of 55 champ.

**Comment by Natherul** [comment]
should not be obtainable for destro? Not all TOK are for both factions

**Comment by Lheana** [comment]
Think destro is meant to be able to unlock it, as it appears in the list :
![anaehll_306](https://cloud.githubusercontent.com/assets/11537611/21655363/03c175dc-d2ba-11e6-94ad-fc0638427db0.jpg)

**Comment by Torquemadra** [comment]
tok has inf for order side pqs too, not intended.

**Comment by Natherul** [comment]
In accordance to file history in the SS http://warhammeronline.wikia.com/wiki/File:Eat-lothern.jpg it was possible for destro to get this ToK on live. I have now made it possible as well in the next DB update
