### ISSUE TITLE
PQ: Kazad Drung - Dwarf Chapter 10: not working

### ISSUE THREAD

**Issue by DonCarlos3850** [WarEmu/WarBugs#8787]
Stage 1 is ok.
But none of the skaven Verminkin for stage 2 did spawn (needed to kill 8).
Searched the area and the cave and couldn't find a single one.

**Comment by Soulwhisper** [comment]
They are in cave.What are you talking about?
![warhammer online age of reckoning 01 03 2017 - 11 00 50 01](https://cloud.githubusercontent.com/assets/16864486/21603185/ee302aa4-d1a3-11e6-8dc4-aa2e18edaba6.png)
4 as you enter and then another 4 in the right side of the cave.
