### ISSUE TITLE
Chaos Chapter 7 PQ

### ISSUE THREAD

**Issue by Squeekyshoes** [WarEmu/WarBugs#8788]
I have noticed that none of the PQs in chaos chpt 7 give influence or count toward totals.
Is this the same issue as what happened with Chapter 5 in that it has not been added on to the game yet?

Many thanks 

Squeekyshoes

**Comment by Soulwhisper** [comment]
![135](https://cloud.githubusercontent.com/assets/16864486/21605032/2bd45d02-d1af-11e6-9e03-4c08eee92114.png)
