### ISSUE TITLE
SH T4 Greenskin influence reward Spear of Remembrance can't be 'alternate appearanced'

### ISSUE THREAD

**Issue by sinadin** [WarEmu/WarBugs#8790]
SH T4 Greenskin influence reward Spear of Remembrance can't be 'alternate appearanced'

The confirmation message box appears but nothing happens after you click ok

**Comment by wargrimnir** [comment]
Use this workaround. We're not able to fix items like that.
https://www.youtube.com/watch?v=v-tA9_h7vZM
