### ISSUE TITLE
Wrath's Resolve Keep PQ Scoreboard Visual Bug

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#8795]
Inner Doors were up.Outer down.
Returned supplies and it insta ticked for roll.
We all got this visual mess.
![warhammer online age of reckoning 01 05 2017 - 15 51 29 12](https://cloud.githubusercontent.com/assets/16864486/21682882/80a87348-d35f-11e6-8f5b-684246d70320.png)
![warhammer online age of reckoning 01 05 2017 - 15 52 29 13](https://cloud.githubusercontent.com/assets/16864486/21682881/80a64b22-d35f-11e6-9700-ad3c252614cc.png)

**Comment by Luth-RoR** [comment]
When looking at the second screenshot, i blame BWs. Or dragons.

**Comment by sioding** [comment]
Since we have totally changes the open rvr campaign and there is no need to carry supplies i will close this now. Thanks for the report.
