### ISSUE TITLE
Chosen ability Rending Blade bug

### ISSUE THREAD

**Issue by PeraNekron** [WarEmu/WarBugs#8797]
Hello.

Chosen ability in Dread mastery tree Rending Blade states it requires Great Weapon.
My chosen wields a 2handed weapon, but the skill button is greyed out constantly, and whenever I use it, the big yellow text appears on screen "requires great weapon". Despite that,, the ability is still executed.  While the ability works as intended, the bug is quite annoying sometimes.

Regards.

**Comment by Luth-RoR** [comment]
What is the name of the great weapon?

**Comment by PeraNekron** [comment]
I use Echelon Deathblade of the Fighter, but I use Opportunist Claymore
(rewards from Chapter 1 influence) appearance.
Funny thing, when I equip Opportunist Claymore, the ability works just
fine, highlighted and all.
Could it be that the item bugs out when you change its appearance?

**Comment by Luth-RoR** [comment]
> I use Echelon Deathblade

Yes, that's what the linked report is about. Some of the green 2h vendor weapons are bugged and don't count as 2h weapons for the client. The appearance doesn't matter.

**Comment by PeraNekron** [comment]
Ok, hope it get fixed someday. :)
