### ISSUE TITLE
Gromril crossing destro guards

### ISSUE THREAD

**Issue by M0rf** [WarEmu/WarBugs#8808]
The destro guards by the spawn in gromril crossing sc dont attack order players who push right to the spawn area, not sure if its a range issue or if they just dont do any damage at all.

**Comment by Torquemadra** [comment]
name of guards?

**Comment by M0rf** [comment]
bloody sun war shoota

**Comment by Lheana** [comment]
Confirming destro wc guards in sc Gromril Crossing don't attack at all, comparing to order ones who correctly attack when just under the wc.
