### ISSUE TITLE
Attacking corpses

### ISSUE THREAD

**Issue by xyeppp** [WarEmu/WarBugs#881]
Some corpses on the body are in fact 100% health mobs who aggro and attack you. They also teleport to you so it proves a hard task fighting them.
![morog_002](https://cloud.githubusercontent.com/assets/12982209/8390104/c8535362-1c7b-11e5-852b-3fb3a9c23c5d.jpg)
![morog_003](https://cloud.githubusercontent.com/assets/12982209/8390107/cb967626-1c7b-11e5-8a62-0dac8737f8f7.jpg) < Still getting hit, the mob is in fact next to me attackable even though he shows at a distance and as a corpse.

**Comment by DanaBloodkiss** [comment]
Fixed long time ago.
