### ISSUE TITLE
ToK unlock 'Saving Face'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#8810]
This bestiary unlock for Tuskgors should be triggered by collecting 5x 'Unchipped Tusks' on 'Bloodsnout Tuskgor' (Destro ; High Pass) or 'Ravaging Tuskgor' (Order ; Eataine). Unchipped Tusks correctly drop on Bloodsnout Tuskgor (did not try on Ravaging Tuskgor), but collecting them does not provide the unlock.

**Comment by Ryanfawkez** [comment]
Work-around made. Buy a Belt of Tusks at the Library/Disciple's Assistant.
