### ISSUE TITLE
Rally Master Empire Chapter 11

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#8813]
- [ ] Blue Skull above her head all the time.
Exactly the same with #8326 .
![warhammer online age of reckoning 01 07 2017 - 14 57 10 04](https://cloud.githubusercontent.com/assets/16864486/21742294/3b120e02-d4f4-11e6-9bc5-0871a73fe8cd.png)

**Comment by Natherul** [comment]
currently not something we can fix as its an unknown variable
