### ISSUE TITLE
crowd control immunity not working properly

### ISSUE THREAD

**Issue by Harnag** [WarEmu/WarBugs#882]
I believe that once player is hit with crowd control (knock back, knock in, stagger, snare, stun) he should be immune for 15 seconds.  This immunity is not working properly or consistently.  We often get staggered, then knocked back before the stagger even ends, or end up with movement snare as soon as we recover from a stun.  Particularly obvious now in T2 with more crowd control abilities going on.

**Comment by xyeppp** [comment]
SWs still being reported as being able to escape from Champion's Challenge, even after the fix. KBs from m1 are working in the same way apparently.

**Comment by Harnag** [comment]
I see my knockbacks and snares don't always work, so maybe this is the ability of the opponent to break/ignore it, or there is some immunity working.  But the immunity is not consistent or uniform.

**Comment by Tesq** [comment]
i alredy reported all skil that make you able to escape from champion challenge

**Comment by ozarmidrashim** [comment]
"I believe that once player is hit with crowd control (knock back, knock in, stagger, snare, stun) he should be immune for 15 seconds."

Be SURE before posting on the tracker. It ACTUALLY works like this:

- Being hit by knockbacks, pulls or roots triggers the Immovable immunity, which protects against them for 30 seconds.

- Being hit by disarms, silences, knockdowns or staggers triggers the Unstoppable immunity, which protects against all of them for (duration of original CC in seconds * 10.)

- Snares don't get immunity.

"We often get staggered, then knocked back before the stagger even ends, or end up with movement snare as soon as we recover from a stun."

In the first case, the stagger gives Unstoppable, which does not protect against knockbacks.
In the second case, nothing immunizes against snares.

1) Unstoppable and Immovable are different immunities

**Comment by ozarmidrashim** [comment]
Also, report is valid RE: Champ's Challenge, fixing...

**Comment by Tesq** [comment]
i found today that soemtimes you can get stag x2 times, dont know which trigger this but happen always when immunity are around 28-30 seconds.

**Comment by Evildoor** [comment]
Champion's Challenge was fixed, report about durations is invalid (explanations above). Closing.
