### ISSUE TITLE
[Magus] Dark Elves T4 RVR Inf rewards (missing item)

### ISSUE THREAD

**Issue by Zhentarim** [WarEmu/WarBugs#8820]
There's a staff that is missing for Magus that is supposed to be a better version of Ninestaff of dreams for r38/rr38. Right now there's only one rr38 staff available from T4 Dark elf inf rewards.

Screenshot: http://imgur.com/a/Zg6AZ

**Comment by Luth-RoR** [comment]
Do you have the name of the staff?

**Comment by Zhentarim** [comment]
I dont know the name of it for sure but it should be "Daemonstaff of Light" if its gonna fit with the other classes rewards.

**Comment by wargrimnir** [comment]
Ninestaff of Light appears to be correct as a reward and as an item, perhaps it was fixed recently?

**Comment by Zhentarim** [comment]
I just checked it on my Magus and the reward available seems to be a zealot charm "Fetish of light". So maybe they are working on it atm. Did you get a screenshot of the Ninestaff?

**Comment by wargrimnir** [comment]
Added missing career requirement to the Fetish, it would have been showing up for any Chaos class.
