### ISSUE TITLE
[AM\Sham] Ap drain tick rate

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#8821]
Didnt seen in patch notes, currently ap drain have 1 sec tick rate instead of common 3 sec. Issue with current state - casts longer than 1 sec can not be used on low ap, cause you lose ap in short time of casting while ap regen paused on cast start.

**Comment by Pxl555** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=8768&p=92913&hilit=Drain+magic#p92913

Archmage
Drain Magic steals 20 AP every second rather than 60 AP every 3 seconds.

Shaman
Yer Not So Bad steals 20 AP every second rather than 60 AP every 3 seconds.
