### ISSUE TITLE
ToK unlock 'The Jade College'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#8822]
This History & Lore unlock for Reikland should be triggered by :

- For order : talking to Davan Stonebach in Praag, emp chap 19
- For destro : killing Jade Wizard in Reikland, south of chaos chap 21

Tried on order and destro sides, none provides the unlock.

**Comment by Ryanfawkez** [comment]
Sure it's not Jade Order? Jade College does not exist.

**Comment by Lheana** [comment]
In my list of H&L unlocks in Reikland I have "The Jade College" :
![anaehll_308](https://cloud.githubusercontent.com/assets/11537611/21763435/30f2bc30-d65e-11e6-8e5b-50d8c423fc04.jpg)
