### ISSUE TITLE
RoR Launcher unusable after starting game

### ISSUE THREAD

**Issue by zulnam** [WarEmu/WarBugs#8825]
STR:
1. Start the RoR launcher.
2. Successfully connect to the server and launch the game.
3. Exit the game.
4. Attempt to start the game again with the launcher that remained open.

Expected: Launcher should be able to re-launch the game or, if the case, auto-close after the initial game launch.

Actual: "Connect" button inactive. User has to close the ROR Launcher and reopen it.

**Comment by Luth-RoR** [comment]
Yes, that's needed to establish a new connection, a technical necessity. Nevertheless developers forge an actual _patcher_ atm, which should be ready soon™ (though i don't know if the new patcher will has a different handling regarding client restarts).
