### ISSUE TITLE
ToK unlock 'Agitators'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#8831]
This History & Lore unlock for Reikland should be triggered by interacting with 'Soap Box' in Talabecland, inside destro PQ 'Army of Faith' and/or with 'Soap Box' in Reikland (6800 9350). I tried interacting with the box in Reikland, but did not provide the unlock. Could not reach the one in Talabecland as doors are closed.

**Comment by Ryanfawkez** [comment]
Soap Box will provide the unlock. Soapboxes are stand-alone objects.
