### ISSUE TITLE
Invisible concealment in IC

### ISSUE THREAD

**Issue by Alvendo** [WarEmu/WarBugs#8833]
Heyho its my First time here and would to try Help find some Bugx?

Above the mailbox seems an invisible concealment that obscures the names of the other Players 

Here some Pics

http://www.bilder-upload.eu/show.php?file=14b19c-1483964282.jpg
http://www.bilder-upload.eu/show.php?file=3de7b4-1483964341.jpg
http://www.bilder-upload.eu/show.php?file=18054a-1483964358.jpg

It is not a Big Bugg but its my first Bug , that i post here =)

**Comment by Ryanfawkez** [comment]
Client related issue. Same thing occurs with the Zealot's Harbinger mechanic; buff effect on the hands has an invisible texture surrounding it that obscures names in an odd manner.

**Comment by Alvendo** [comment]
okey ^^

**Comment by Luth-RoR** [comment]
Closing until fis is possible.
