### ISSUE TITLE
ToK unlock 'The Family That Dies Together'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#8839]
This bestiary unlock for Zombie should be triggered by killing the whole Spolfinkr Family (Tomas Spolfinkr, Papa Spolfinkr, Annabelle Spolfinkr and Croetch Spolfinkr) located around a ruined house in the Chaos Wastes (15k 58k). Killing them does not provide the unlock.

**Comment by Ryanfawkez** [comment]
Work-around made. Interact with 'Family Dining Table' next patch.
