### ISSUE TITLE
Taunt

### ISSUE THREAD

**Issue by Evildoor** [WarEmu/WarBugs#884]
It seems that taunt is removed when the tank hits their target 3 times, should be when the target hits the tank 3 times. Also, the "x3" hits counter does not changes. Can someone clarify how does mass taunt works in this regard?

**Comment by ozarmidrashim** [comment]
Fixed first in next.
Second can't be fixed yet without the side effect of scrolling combat text spamming you with [-Taunt][Taunt]

**Comment by Evildoor** [comment]
Works properly now, thanks. Closing.
