### ISSUE TITLE
ToK unlock 'Song and Dance'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#8842]
This bestiary unlock for Daemonettes should be triggered, for destro, talking to 'Bladedancer' in Chaos Wastes (24k 55k). Talking to her does not provide the unlock, and she has double spawn.

**Comment by Lheana** [comment]
Tried to kill 'Eidih the Helator' in Chaos Wastes (15k 40k), and did not provide neither the unlock.

**Comment by Ryanfawkez** [comment]
Tome and title unlock added to both NPCs.
