### ISSUE TITLE
Returned Mail - Items lost

### ISSUE THREAD

**Issue by Dallidiem** [WarEmu/WarBugs#8843]
1. I sent mail from one character on my account to another with attached items
2. On the recipient, I returned the mail JUST A FEW DAYS LATER (not exceeding time constraints)
3.  On the original - the mail I sent was returned - but  no items were attached even though I'd NOT removed them.  

Shame to lose those items.. oh well.

**Comment by Istwid** [comment]
When click return a letter, the letters are returned empty, offensively.

**Comment by sioding** [comment]
fixed
