### ISSUE TITLE
Blue bag Burning Windmill

### ISSUE THREAD

**Issue by Soulwhisper** [WarEmu/WarBugs#8844]
Now that you filled Purple/Blue bags with items..
I saw 1 blue bag with no item inside(Picture 3).IB class.Burning Windmill PQ.
Might be a blank spot in DB? Got blue sagain and they had items in them(Picture 1 & 2)
![warhammer online age of reckoning 01 10 2017 - 02 43 24 08](https://cloud.githubusercontent.com/assets/16864486/21805702/3ddd9196-d73e-11e6-8d32-4b8de6ff8576.png)
![warhammer online age of reckoning 01 10 2017 - 02 33 24 07](https://cloud.githubusercontent.com/assets/16864486/21789396/60a25ee8-d6dd-11e6-94c2-b505f5d77f64.png)
![warhammer online age of reckoning 01 10 2017 - 02 24 17 06](https://cloud.githubusercontent.com/assets/16864486/21789215/020a5044-d6dc-11e6-93d0-f171f8753bf3.png)

**Comment by wargrimnir** [comment]
Probably from some erroneous generic gear. Fixed in next.
