### ISSUE TITLE
ToK unlock 'Cutting Bonds'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#8849]
This bestiary unlock for Daemonvines should be triggered by interacting with 'Mound of Dirt' in Chaos Wastes (50k 47k), to get a 'Sacrificial Kris'. Then should kill the Daemonvine 'Xavian's Pride' around 47k 5.3k in West Praag.
Interacting with a 'Mound of Dirt' does not give the item, nor provide the unlock. Tried to kill 'Xavian Pride', but did not find it, maybe missing ?

**Comment by Ryanfawkez** [comment]
NPC added with unlock.
