### ISSUE TITLE
T4 Greenskin/Dwarf RVR Influence reward blue weapons

### ISSUE THREAD

**Issue by Zhentarim** [WarEmu/WarBugs#8855]
The blue 31/31 weapons you get in greenskin/dwarf rvr have 4% crit on staffs and 2% crit on onehanders, while the purple ones were nerfed to 2% and 1%. I guess the blue ones forgot to be nerfed.

Screenshot: http://imgur.com/a/GKUx7

**Comment by Ryanfawkez** [comment]
Not expecting people to take the blue weapons, but alas this has to be fixed for the sake of consistency.

**Comment by wargrimnir** [comment]
Crit reduced.
