### ISSUE TITLE
Quest "Foul Works" not working.

### ISSUE THREAD

**Issue by Solutar** [WarEmu/WarBugs#8856]
Hello,
i cant complete the quest "Foul Works". ive killed all tower guards, but when i try to talk to the quest giver, he isnt giving me the loot cause i get a message that says my inventory is full, even so it isnt full. 6 open spaces. Please help. My ingame name is Solutar too.

**Comment by Luth-RoR** [comment]
Due to a known bug, your crafting inventory needs room too; you need to wait for a server restart *and* make sure that both inventories have enough room before you try it again.

**Comment by Solutar** [comment]
Thank you. :)
