### ISSUE TITLE
ToK unlock 'Redfang Camp'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#8858]
This History & Lore unlock should be triggered by walking near 50k 58k in Black Crag.

**Comment by Natherul** [comment]
proximity currently is not possible

**Comment by Lheana** [comment]
I know but Luth told me to report it anyway :)

**Comment by Natherul** [comment]
yes, that is good. Im stating that simply so that if Luth did not know he can add the right tags to it :P

**Comment by Luth-RoR** [comment]
Impertinence! 😛
