### ISSUE TITLE
ToK unlock 'Fire Seldom Dies Alone'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#8862]
This bestiary unlock for Dryads should be triggered by :

- Interacting with 'Crate of Torches' which should give 10x Torches
- Use these Torches to kill 'Ashridden Dryad'  (for example around Lobba Mill BO, or around 25k 48k), to receive the item 'Dryad Ash'
- Need to collect 10x 'Dryad Ash', then talk to 'Snotgul' in greenskin chap 15

None of the steps is working.

**Comment by Natherul** [comment]
step 2 and 3 is currently not possible
