### ISSUE TITLE
ToK unlock 'Indigestion'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#8865]
This bestiary unlock for Stone Trolls should be triggered by :

- Interacting with 'Drul's Lunch' in Black Crag (500 20k) inside 'The Despair Pits'
- Killing 'Skittering Spiders' at the north of this cave, to get a 'Poison Gland'
- Interacting again with 'Drul's Lunch'

'Poison Gland' correctly drops on 'Skittering Spiders', but interacting with 'Drul's Lunch' does not provide the unlock.

**Comment by Natherul** [comment]
currently cant add multiple requirements for ToK unlocks but a workaround is issued with the next patch. We may want to revisit this one at a later time to fix as live
