### ISSUE TITLE
ToK unlock 'Scales of Mourning'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#8868]
This bestiary unlock for Basilisks should be triggered by killing 'Stinky' inside 'Sulfur Caves' in Black Crag (6k 8.5k). Killing it does not provide the unlock.

**Comment by Natherul** [comment]
fixed in the next patch

**Comment by Lheana** [comment]
This unlock should also be provided by killing the champion basilisk 'Black Scale' in Black Crag (40.7k 38.7k). Killing it does not provide the unlock 'Scales of Mourning'. This mob also has triple spawn.

**Comment by Lheana** [comment]
Black Scale will provide his unlock. Removed his triple spawn and he will count as Basilisk.
