### ISSUE TITLE
Da Big Un (/w Fighter's Bigchoppa of Vengeance

### ISSUE THREAD

**Issue by WahookaTG** [WarEmu/WarBugs#8874]
I noticed variations of this issue have been posted before but I believe I have a new one.

Even though al req's are met, the skill button will not 'light up'.
When pressing the hotkey, the message "This skill requres a great weapon" pops up.

Funny thing is: the skill does execute correctly when I do this.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/8492
