### ISSUE TITLE
Canceled Auctions return extra message

### ISSUE THREAD

**Issue by zulnam** [WarEmu/WarBugs#8875]
[Note] This bug is general to all system messages relating mail (i.e: regular mail will also display an AH message).

STR:
1. Create a new auction house.
2. Cancel said auction house.

Actual: user receives 2 messages instead of one:
You have 0 messages in your inbox.
You have 1 unread message in y our Auction mailbox.

Expected: user should only receive the AH-related message.

**Comment by MaxHayman** [comment]
Fixed in next patch

**Comment by Kaelang** [comment]
This should now be fixed. Please re-open if issue persists.
