### ISSUE TITLE
Public Quest Bug

### ISSUE THREAD

**Issue by Xhound40k** [WarEmu/WarBugs#8876]
Im pretty new to all this but I found a quest breaking bug that makes it easy as heck to farm.

Squig Herder, first available Public Quest from when you first start in the game. The second stage is clicking on gravestones. I was able to just click one gravestone and spam it and get to 25/25 within like three seconds.

**Comment by Soulwhisper** [comment]
Thats a known issue with many objects in the world. 
Thanks though.

**Comment by Luth-RoR** [comment]
Yes, that's well known and afaik the only reason why it is not fixed yet, is that DB devs do it by hand for every object. Closing.

**Comment by Xhound40k** [comment]
I tried. Want that mount so bad!
