### ISSUE TITLE
T3 PQ - Guts Out - Stage 1 mob progression display incorrect

### ISSUE THREAD

**Issue by zulnam** [WarEmu/WarBugs#8877]
STR:
1. Reach Empire T3, High Pass as a destruction player.
2. Proceed to the Guts Out PQ.
3. While at Stage 1, kill more than 10 mobs of each required type.

Actual:
Stage 1 displays mob#2 progress for mob#1 and vice-versa (see image below).

Expected:
Stage progression should display accordingly.

[Note] PQ can be completed.

![leslie_001](https://cloud.githubusercontent.com/assets/19802847/21875689/bf86740a-d875-11e6-8370-62b9580817fb.jpg)

**Comment by Soulwhisper** [comment]
#6935

**Comment by Soulwhisper** [comment]
#6935 Known.

**Comment by Luth-RoR** [comment]
Thanks.
