### ISSUE TITLE
High pass PQ (Lake of the damned)  lord bug

### ISSUE THREAD

**Issue by iRolland** [WarEmu/WarBugs#8889]
The final boss can be kited  without you taking any damage. If you kite him along the edges of the lake.

**Comment by grunbag** [comment]
added spawn along the edge of the lake. the boss can't be kited anymore

fixed in next patch

**Comment by Razielhell** [comment]
Horrors dont register on Stage 1 now...

**Comment by Lheana** [comment]
Works fine.
