### ISSUE TITLE
ToK unlock 'To the Death'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#8892]
This bestiary unlock for Rat Ogres should be triggered by killing 'Burrow Champion' inside a cave in Kadrin Valley (59k 40k). Killing him does not provide the unlock.
(Title associated : The Scarred)

**Comment by Natherul** [comment]
ToK should work in the next patch

**Comment by Lheana** [comment]
Killing 'Burrow Champion' correctly triggers the unlock, but not the title associated 'The Scarred'.

**Comment by Natherul** [comment]
will work in the next patch
