### ISSUE TITLE
ToK unlock 'Say Hello to My Little Friends'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#8893]
This bestiary unlock for Nurglings should be triggered by killing 'Vlasi Ipatiev' in Kadrin Valley (40k 25k). Killing him does not provide the unlock.

**Comment by Natherul** [comment]
should be fixed in the next patch... Also @Luth-RoR this is not any item involved in this one :D

**Comment by Luth-RoR** [comment]
Oh, mistake.

**Comment by Lheana** [comment]
Killing 'Vlasi Ipatiev' triggers the unlock 'Kill 10 000 Giant Lizards' ! So the wrong unlock :p

**Comment by Natherul** [comment]
my bad, should be fixed in the next push, I did a typo on first change
