### ISSUE TITLE
Dok Annihilator bugg

### ISSUE THREAD

**Issue by Alvendo** [WarEmu/WarBugs#8898]
Heyho,

 i have screenshot about that, u see my DoK , i try to Color it in Red my Full Annihilator Set but it doesnt work  =(

http://www.bilder-upload.eu/show.php?file=c2c24b-1484254286.jpg

Is that a bugg ?? i cant no Color it when Primary or secondray or "all" Color

Is that fixiable , i Need my Dok with my full Color pls =(

**Comment by Luth-RoR** [comment]
That's a client restriction that can't be fixed.
