### ISSUE TITLE
Marauder Path tactics not working

### ISSUE THREAD

**Issue by slave1974** [WarEmu/WarBugs#890]
My Login is Slave1974

On MY marauder, none of the path tactics are workimg. It doesn;t matter what gift I have up, none of them change my stats.

I did get it to change once, but it only granted 21 strength, instead of the 68. My initiative did not go up at all.

**Comment by ozarmidrashim** [comment]
#876 

They do work, but you will need to cycle your mutation. They do not show in the char screen.

**Comment by slave1974** [comment]
I did cycle.  So, behind the scenes, I am getting the 69 to str and 68 to initiative?
