### ISSUE TITLE
[Kotbs] Shield of the Sun has no retrigger interval

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#8900]
![fallos_011](https://cloud.githubusercontent.com/assets/13031465/21933410/4621e858-d9e0-11e6-9c6a-1511510f8682.jpg)

**Comment by Luth-RoR** [comment]
Proc's don't have an internal cooldown atm, if it is not mentioned in the tooltip or other evidence has been presented.

**Comment by Luth-RoR** [comment]
Confirmed as working as intended by devs.
