### ISSUE TITLE
ToK unlock 'Worth the Waiting For'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#8901]
This bestiary unlock for Spirit Hosts should be triggered by killing 'Mabel Reiss' in Reikland (12k 44k), who turns into a Spirit Host once killed. Killing this spirit host should provide the unlock. I killed 'Mabel Reiss' but did not give anything.

**Comment by Natherul** [comment]
sadly right now there is no way to spawn a mob in this manner
