### ISSUE TITLE
Can't click banker

### ISSUE THREAD

**Issue by Gitfaced** [WarEmu/WarBugs#8905]
The solo player (not guild banker) is bugged and cannot be clicked.

**Comment by Luth-RoR** [comment]
>The solo player

I don't understand; what is the name of the NPC?

**Comment by Soulwhisper** [comment]
Altdorf works fine. Just checked.

**Comment by Ryanfawkez** [comment]
There is a very temporal bug with various capital NPCs. I've had reports before of the IC banker not working, as well as the Very Special dye vendors. They'd work fine on the dev server, and usually a server restart got these NPCs out of their bugged state. I might wipe their figleaf data to see if the bugs stop occurring, but for now, I cannot be sure if this is causing the issue.
