### ISSUE TITLE
Shadow Warrior Ability Bug

### ISSUE THREAD

**Issue by mgsmrcl** [WarEmu/WarBugs#8906]
The whirling pin slows down enemies but it doesnt knock you back away from your enemies

-Lothriel SW 15 rr 15

**Comment by Luth-RoR** [comment]
I just tested it on an NPC; whirling pin works fine.

**Comment by sullemunk** [comment]
I know you used to be able to self defend against the knock back,  is that fixed?

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/4126
