### ISSUE TITLE
Talabec Dam

### ISSUE THREAD

**Issue by baconzilla** [WarEmu/WarBugs#8907]
After returning keg to dam and dying from explosion, upon respawn could not spawn mount.  it said cannot spawn mount while carrying keg.

**Comment by Luth-RoR** [comment]
Referring to https://github.com/WarEmu/WarBugs/issues/6975

**Comment by Luth-RoR** [comment]
Stealth doesn't work too according to https://github.com/WarEmu/WarBugs/issues/9370
>When one then plays a class WH / WE you can not go to the whole scenario in stealth.

**Comment by Natherul** [comment]
this has been fixed some time ago.
