### ISSUE TITLE
Land of the dead teleportation item...

### ISSUE THREAD

**Issue by Stophy22** [WarEmu/WarBugs#8908]
So upon log in I was given an item to teleport to land of the dead via mail from a user(shown in screenshot) and I'm not sure if this is from a GM, because the name doesn't say GM. And then this all just really confused me... here are some screenshots.

![thermidor_016](https://cloud.githubusercontent.com/assets/23489906/21959776/71cb7744-da8f-11e6-8552-c910dcde779e.jpg)
![thermidor_017](https://cloud.githubusercontent.com/assets/23489906/21959778/7fa39b3a-da8f-11e6-9f12-26fd8e037fda.jpg)
![thermidor_018](https://cloud.githubusercontent.com/assets/23489906/21959779/81c415d4-da8f-11e6-93b9-2ddbe140e7cb.jpg)
![thermidor_019](https://cloud.githubusercontent.com/assets/23489906/21959781/83c22114-da8f-11e6-8f5a-3658deaf9269.jpg)
![thermidor_020](https://cloud.githubusercontent.com/assets/23489906/21959782/8589d5b4-da8f-11e6-9422-428742816921.jpg)
![thermidor_021](https://cloud.githubusercontent.com/assets/23489906/21959783/871565e2-da8f-11e6-9eba-28386e511971.jpg)

The item(A Golden Ticket.......) came in my mail and had instructions that if I find bugs in LOTD I was to report them, and it said Travelogue reward, not sure what a travelogue reward is and I never heard of this anywhere so this all just seems all sorts of shady... Don't wanna get banned for being some place I wasn't allowed to be.

Side note: It also said if I tried to sell this on the AH I would have sanctions applied to my account. If this truly is a GM contacting me and rewarding me I feel like I should have been informed better of the status of said player and then told this item takes me to LOTD so I didn't waste it.

**Comment by Stophy22** [comment]
I will not log into my character Thermidor until I am cleared by a GM that this **in fact** a gift that I can use to explore LOTD.

**Comment by Stophy22** [comment]
Yali**s**kah is a gm in the gm list I just checked, but the person who sent me the mail is named Yali**sh**kah

**Comment by Stophy22** [comment]
My actions in land of the dead included: 
-killing two mobs(only money dropped, shown in screenshot.) 
-clicking on the chest you see in the picture (nothing happened)
-walking around to take the other screenshots.
-leaving LOTD via scroll, after 2 log ins and outs. (internet cut out)

**Comment by Zhentarim** [comment]
Its a reward for posting a screenshot in this thread:
https://www.returnofreckoning.com/forum/viewtopic.php?f=2&t=19134&start=40

**Comment by Tyramissoux** [comment]
You're not alone there. Others also got the ticket and I think you're supposed to explore the area a bit.

**Comment by Stophy22** [comment]
Well wups haha thought I didn't qualify from that because he commented on
my photo

**Comment by Luth-RoR** [comment]
It's always advisable to follow threads that one has contributed to/posted a reply. Furthermore if this had been a fake-mail from a non-GM, it would be better to contact one of the GMs next time as the bugtracker is only for bugs.
