### ISSUE TITLE
AM Searing Touch: Able to use it while swimming / moving in water

### ISSUE THREAD

**Issue by RevMalthus** [WarEmu/WarBugs#8910]
Hey guys,

Just figured out that on my AM I can melt gobbo face whilst swimming with searing touch

I figured this is probably not intended as you cannot move while using it on land - so I cant see why there would be any reason that you should be able to use it while swimming.

All the best,
Rochambeauxx

**Comment by Luth-RoR** [comment]
Known issue: https://github.com/WarEmu/WarBugs/issues/1540
