### ISSUE TITLE
LOTD WC Order Side : vendor dont Selling anything

### ISSUE THREAD

**Issue by grunbag** [WarEmu/WarBugs#8912]
This vendor at LOTD WC on order side , not selling any item

[URL=http://www.casimages.com/i/170115111345847239.jpg.html][IMG]http://nsa38.casimages.com/img/2017/01/15/170115111345847239.jpg[/IMG][/URL]

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/8909
