### ISSUE TITLE
LOTD Order WC Sellers : no windows pop

### ISSUE THREAD

**Issue by grunbag** [WarEmu/WarBugs#8913]
Those seller doesn't have any selling window poping when you talk to them

[URL=http://www.casimages.com/i/170115111738878475.jpg.html][IMG]http://nsa38.casimages.com/img/2017/01/15/170115111738878475.jpg[/IMG][/URL]

[URL=http://www.casimages.com/i/170115111738111582.jpg.html][IMG]http://nsa37.casimages.com/img/2017/01/15/170115111738111582.jpg[/IMG][/URL]

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/8909
