### ISSUE TITLE
LOTD River don't kill you

### ISSUE THREAD

**Issue by grunbag** [WarEmu/WarBugs#8914]
LOTD river doesn't hurt you when you swim in

[URL=http://www.casimages.com/i/170115112826848616.jpg.html][IMG]http://nsa37.casimages.com/img/2017/01/15/170115112826848616.jpg[/IMG][/URL]

**Comment by Luth-RoR** [comment]
That's known; it's the same with lava and it is just a low priority fix, thanks.

**Comment by grunbag** [comment]
It will be an issue since if you follow the river til the end you came to a big area that allow players to walk up on mountains til normal lots map and come up on the wc roofs

**Comment by grunbag** [comment]
Normal lotd map*
