### ISSUE TITLE
LOTD MOB doesn't have red names

### ISSUE THREAD

**Issue by grunbag** [WarEmu/WarBugs#8916]
Somes mob in LOTD doesn't have red names upon their head, so you can't see them 

[URL=http://www.casimages.com/i/170115113526184107.jpg.html][IMG]http://nsa38.casimages.com/img/2017/01/15/170115113526184107.jpg[/IMG][/URL]

[URL=http://www.casimages.com/i/170115113247663762.jpg.html][IMG]http://nsa38.casimages.com/img/2017/01/15/170115113247663762.jpg[/IMG][/URL]

**Comment by Luth-RoR** [comment]
Something is wrong with the images; you can drag&drop any image from you screenshot folder into the post window. There is no need to link them.

**Comment by Luth-RoR** [comment]
These are PQ mobs who are not implemented yet/lack scripting etc.
