### ISSUE TITLE
Something terrible happend to the Uthorin Dark Rider

### ISSUE THREAD

**Issue by Cimbas** [WarEmu/WarBugs#8917]
![cimbina_031](https://cloud.githubusercontent.com/assets/16117730/21961985/937c61c6-db18-11e6-8c3a-91fe918e4cb0.jpg)
![cimbina_032](https://cloud.githubusercontent.com/assets/16117730/21961987/9630696c-db18-11e6-8f13-d22833dac5fb.jpg)

It looks like one of the dark gods performed genetic experiments with the Uthorin Dark Rider and transplanted Dwarf Heads to their bodies.

**Comment by Ryanfawkez** [comment]
Uh oh. Bloody Winds of Magic revving up again!
