### ISSUE TITLE
[WL] pack assault ability

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#892]
Adittional damage of Pack Assault do damage without mitigation and doesnt apply on pet and group members.

**Comment by Paninii** [comment]
I can confirm at least the facts that it doesn't apply to your pet or group members.
I dont know about mitigation or how it was on live.

**Comment by Nfkillz** [comment]
Look at screenshot and you will see that additional damage wasnot mitigated (66 damage) Also within 4 attacks my pet didnt attack by Pack assault.

http://take.ms/C4yBu

**Comment by Paninii** [comment]
yes i was wrong , the initial damage is mitigated, the proc isn't.

**Comment by ozarmidrashim** [comment]
I think the WL may be getting credit for the PA damage.

For those of you with BuffHead, check whether your party members get the buff when PA is cast. I used it yesterday and saw the buff being spread.

**Comment by Evildoor** [comment]
Pet receives PA buff and procs it, dunno about party members.

**Comment by Nfkillz** [comment]
yes now it works correct
