### ISSUE TITLE
Muck Pen- Public Quest Dwarf Chapter 21

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#8920]
- [x] Stage 2 bugged.

**Comment by Hargrim** [comment]
PQ Works - all you need in Stage II is to click on Pile of Filth. Also, provide more details...

**Comment by Soulwhisper** [comment]
Tested with 4 more people and we couldnt find Pile of Filth objects nowhere in the area.

**Comment by Natherul** [comment]
![stabby_002](https://cloud.githubusercontent.com/assets/3688166/21999869/890bcdec-dc3c-11e6-879c-1b9ec0ae1149.jpg)
Works fine,  here is one of those piles...

**Comment by Soulwhisper** [comment]
Yeah i imagined but we couldnt click on them. They are untargetable to us. Will test again later on today.

**Comment by Natherul** [comment]
works on dev server so either its something bugged in that boot or someone else have fixed this issue and not noticed this bugreport. In either case it should be fine in the next db patch

**Comment by Razielhell** [comment]
@Natherul No it still doesnt work. Untargetable.
![maxeras_000](https://cloud.githubusercontent.com/assets/16864486/22286450/db4fbc6e-e2f7-11e6-9b88-2d94e74c397b.jpg)

**Comment by Hargrim** [comment]
![image](https://cloud.githubusercontent.com/assets/16460565/22299426/528d2d58-e324-11e6-9e2c-991cc02c178a.png)

Targetable

**Comment by Razielhell** [comment]
@Hargrim Hahahaha yeah but we(Players) cant :( Whats going on? hahaha

**Comment by Hargrim** [comment]
It was taken today on live and client cannot differentiate between staff and non staff accounts for the purpose of GOs.

**Comment by Razielhell** [comment]
Pile of shit xD

**Comment by Thayli** [comment]
Same thing as in #8921. Works fine on dev, so I have no idea what's going on here.

**Comment by Razielhell** [comment]
Yeah...nobody knows yet.

**Comment by grunbag** [comment]
Tried to fix it, tell me if it worked on next patch

**Comment by Razielhell** [comment]
- [ ] grunbag is the man.

> Fixed.
