### ISSUE TITLE
[Bolster] Weird behaviour in T1

### ISSUE THREAD

**Issue by Blaqwar** [WarEmu/WarBugs#8922]
This struck me as a situation where something is very likely broken or being abused. I don't know exactly where the fault lies but the signs seem to point at bolster. Hopefully it can be investigated.

Playing a CR10 Witch Elf in the Gates of Ekrund scenario I came across a nigh-unkillable CR10 White Lion who annihilated me. The damage he was receiving and the damage he was dishing out were nowhere close to a fight between two equal level opponents. Have a look at the screenshots below:

This is the end of the scenario window which proves that the WL in question was CR10 (Galadhon, don't see the point in hiding the name of a T1 character, if that's an issue let me know and I'll edit the screenshots and blank out their name), as well as my own WE (Ravaged):

![scenwindow](https://cloud.githubusercontent.com/assets/5108812/21966150/6848d8e4-db6e-11e6-8463-4a3593ea6f7c.png)

These are my bolstered stats, nothing wonky going on:

![westats](https://cloud.githubusercontent.com/assets/5108812/21966149/68489438-db6e-11e6-9902-7dce9223db89.png)

These two screenshots are my character taking crazy amounts of damage while dealing almost none:

![combatlog2](https://cloud.githubusercontent.com/assets/5108812/21966183/f027ea5c-db6e-11e6-9c37-701d901b3693.png)

And this is a SS of his Sever Nerve (MDPS morale 1) hitting me for 1200 damage, which I believe is the value that morale ability does at CR40:

![combatlog1](https://cloud.githubusercontent.com/assets/5108812/21966193/2648315a-db6f-11e6-9588-bc4bbb71c768.png)

To make sure it wasn't just Sever Nerve that was bugged I went out into the RvR lake and used it (you can see I was bolstered in the SS):

![wem1](https://cloud.githubusercontent.com/assets/5108812/21966198/33830822-db6f-11e6-9c3c-9138077e6a36.png)

Something to note is that my character itself could not have been bugged and was bolstered correctly since I had a decently close fight against a CR~6 Swordmaster just before I ran into the White Lion.

As I pointed out above, the fact that Sever Nerve was using the CR40 value makes me think that bolster was to blame in this case. I have no clue however, if this was simply a bug or intentional abuse.

**Comment by Tyramissoux** [comment]
Seen this happening before to my shaman. Crappy geared low lvl shaman suddenly doing 2k non crit direct heals after lvling up. Lasted until I logged out. Happened a long time ago. (4th of April 2015)
Think it didn't affect my stats (hp pool was normal) but the ability scaling.
