### ISSUE TITLE
Focused Mind give immune for knock down 

### ISSUE THREAD

**Issue by Killham** [WarEmu/WarBugs#8925]
![111](https://cloud.githubusercontent.com/assets/18173840/21968212/461a5024-dba3-11e6-91d8-e6a7d090d173.jpg)
But the description says it gives only immune for silence, disarm, root and snare.

**Comment by Luth-RoR** [comment]
Iirc there was some evidence presented over a year ago that it gave KD immunity too on the mythic server (i don't remember).

**Comment by gebajger** [comment]
It made you immune to everything except knockback on live.
If you got chched (champion's challenge) you couldnt get out of it with FM (I think thats silly since fm is m2, chch is m1), BUT if you popped fm 1st, you could not be chched

**Comment by Luth-RoR** [comment]
Closing then. 
About CC: it has the exception in the tooltip (can't be broken).
