### ISSUE TITLE
[Quest] The Festerin' Marshes (t1-->t2)

### ISSUE THREAD

**Issue by Paleolog77** [WarEmu/WarBugs#8926]
Can't end the quest, the NPC is not active.
![9](https://cloud.githubusercontent.com/assets/23325288/21969136/af184ab4-dbac-11e6-9f34-fbff24448a46.jpg)
1. I'm taking quest from curator dwarfs chapter 4 Captain Scalfson.

![10](https://cloud.githubusercontent.com/assets/23325288/21969188/357937c6-dbad-11e6-9ac1-fc5a8e499a87.jpg)
2. Can't end quest to curator dwarfs chapter 5 Durrig Olfrinson.

P.S. I think NPC Durrig Olfrinson is broken.

**Comment by Natherul** [comment]
should be fixed in the next patch
