### ISSUE TITLE
[Quest] The Hunt for Oathgold 

### ISSUE THREAD

**Issue by Paleolog77** [WarEmu/WarBugs#8927]
Quest from WC dwarf -->to chapter 5 curator.
![11](https://cloud.githubusercontent.com/assets/23325288/21969576/6041db0e-dbb0-11e6-8a0c-7a85e7615af3.jpg)
1. I'm taking quest from Oskella Skorassdotr WC t2 dwarfs.
![12](https://cloud.githubusercontent.com/assets/23325288/21969649/d067e662-dbb0-11e6-9df1-236a79279651.jpg)
2. Can't end quest to curator dwarfs chapter 5 Durrig Olfrinson.

P.S. I think NPC Durrig Olfrinson is broken.

**Comment by Luth-RoR** [comment]
Should have the same root as your report https://github.com/WarEmu/WarBugs/issues/8926 so i'm closing this.
