### ISSUE TITLE
[WL][Squig] pets

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#893]
While mounting I can send my pet attack other players.

**Comment by Zaccar20** [comment]
Also the War Lion is slow like normal when i'm mounted :(

**Comment by ozarmidrashim** [comment]
Complaints about War Lion speed have been thoroughly noted, thank you.

One issue per report.

**Comment by xyeppp** [comment]
I don't know if you noticed before, but the pet runs away from always exactly when you change the zones in the middle of the RvR lake - from Ostland to Troll Country and vice-versa. If you come back to the line where the pairing divides back to the zone you came from, the pet comes back to you everytime.

**Comment by Evildoor** [comment]
https://github.com/WarEmu/WarBugs/issues/604
