### ISSUE TITLE
PQ:Destruction

### ISSUE THREAD

**Issue by pugdishcobo** [WarEmu/WarBugs#8930]
This public quest is buged. the mobs are all dead and they dont respawn  its stuck at stage 1 Cruel Overseer9/10, Murderous Raider 27/30. you also cant finish the quest "Promise of Battle" because the raiders wont spawn.

**Comment by Soulwhisper** [comment]
This is for @Luth-RoR and its true. All mobs are dead. I told wargrimnir to put respawn flags on PQ mobs but...:P  #7143
