### ISSUE TITLE
Tier 2 Troll Country Public Quests.

### ISSUE THREAD

**Issue by Zaethus** [WarEmu/WarBugs#8932]
Each of the public quests in the destruction area.

Plaguewood Thicket
Lursa's Blight
Gryphon Outpost

Do not seem to register story progression kills so i appear to be stuck on chapter 1, neither do any of these give rally master reputation for any relative kills.

Cheers,

z

**Comment by Luth-RoR** [comment]
What are story progression kills?
What is rally master reputation?

**Comment by Zaethus** [comment]
Let me phrase that better sorry, Public quest progression kills advance the PQ stage (story) and you don't get area of influence, influence (reputation) for killing the PQ monsters.

**Comment by Luth-RoR** [comment]
The PQs are not implemented yet: https://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=16392
Please report only PQs that are implemented and buggy (actually most/all PQ bugs can be found on the bugtracker already).
