### ISSUE TITLE
ToK unlock "Broken Bones"

### ISSUE THREAD

**Issue by Xanics** [WarEmu/WarBugs#8936]
[ToK unlock "Broken Bones"](https://github.com/WarEmu/WarBugs/issues/8713)

Broke Toof: (13k, 23k) Travel to Chaos Wastes and make your way to the coordinates given. Just Northwest of the Malevolent Warband Major, slay 100 Blood Spawns (Bloodbeasts of Khorne) until you are granted the tome unlock, "Broken Bones", allowing you to claim Broke Toof.

I just did the Tome unlock, after killing 100 Boodbeasts of Khorne (the correct ones), Broke Bones unlock is granted, but it says Titel: ??? And opens up Kill 100 Bloodbeasts Tome, but does not award 100 kills

![image](https://cloud.githubusercontent.com/assets/14800906/22018863/37e555da-dcb1-11e6-85fb-4caa74307926.png)

**Comment by Ryanfawkez** [comment]
Cannot fully fix this until we have client control. Seeing as it's only a visual bug, I'm not too concerned about it either.

**Comment by Xanics** [comment]
Which one is just a visual bug, the Titel which is not granted, or the 100 kills?

**Comment by Ryanfawkez** [comment]
Actually, I think there is a way to fix it. Will have to assign the 100 kill objective to its correct spot, then assign that ToK unlock to to Broke Toof item in the ToK shop. According to Hammerwiki, Broken Bones is NOT the ToK unlock required for the Broke Toof.

http://warhammeronline.wikia.com/wiki/Broken_Bones

**Comment by Ryanfawkez** [comment]
http://warhammeronline.wikia.com/wiki/Broken_Bones - Judging by this page, Broken Bones and 100 bloodbeast of Khorne kills are separate objectives. I've assigned the correct ToK unlock to the Broke Toof reward now; requiring you to kill 100 Bloodbeasts of Khorne which will now award the correct unlock. Broken Bones can be obtained from the Bones of a Bloodbeast pile in Kadrin Valley. No idea what the title unlock is supposed to be, though.

**Comment by Xanics** [comment]
Oh, that can be, yes. Shall I open a separate ticket for the Bones of Bloodbeast Title?

**Comment by Ryanfawkez** [comment]
No need. Will check what title's associated to the Broken Bones unlock.

**Comment by Lheana** [comment]
I had already killed 100 Bloodbeasts of Khorne before the patch of today, and I can't have the unlock 100 Bloodbeasts of Khorne, even if I kill some again. The title is not triggered neither.

**Comment by Ryanfawkez** [comment]
You can only get the title if you interact with the Bones of a Bloodbeast pile. I'm afraid that you cannot obtain the Broke Toof unlock if you've already gotten 100 Bloodbest of Khorne kills.
