### ISSUE TITLE
REgistration Issue but no Chance to contact without Registration

### ISSUE THREAD

**Issue by Frostlatte** [WarEmu/WarBugs#894]
Hello,

i tryed about hours to reactivate or create an Account on the Homepage. No Activation Email seems to be sent. The PW - Reset MAils too.

...also the Web - Contactformular needs an active REgistration?!

So how could i contact an admin for RegistrationIssues without Registration ?

mfG  Frost

**Comment by xyeppp** [comment]
This is for in-game bugs only.
 Use the forum for support regarding your account, also read the text in red http://www.returnofreckoning.com/forum/download/file.php?id=343

**Comment by Frostlatte** [comment]
I did andknow all this, but thx for answer. I tried Your Solutions, dont works. ;b

**Comment by Evildoor** [comment]
Unresolved technical problems about getting into game/installing the game/whatever go here:
http://www.returnofreckoning.com/forum/viewforum.php?f=4
