### ISSUE TITLE
WL Tactic Flashing Claws

### ISSUE THREAD

**Issue by DragonTank** [WarEmu/WarBugs#8940]
Not sure if this tactic is working doesn't feel like its working as it should?

should give 10% parry to player and pet while pet is active ive selected the tactic and cleared it and looked at my parry stat doesn't change on the stats panel but when i select other resistances and other stat changers it changes on the stats panel.

Can this be looked into by someone who knows how to definitively check it!  thanks!

![dragontnk_006](https://cloud.githubusercontent.com/assets/6575208/22076073/7c26fc58-dda6-11e6-8812-03ab1092a571.jpg)
![dragontnk_008](https://cloud.githubusercontent.com/assets/6575208/22076074/7c2b59ec-dda6-11e6-88be-ad83a9935289.jpg)

**Comment by DragonTank** [comment]
okay ive seen some older posts about this looks like its a display error just doesnt seem like it works ! :(

**Comment by Blaqwar** [comment]
It is working correctly for the player at least, I have no clue how to check that for the lion as I'm not sure I've ever seen a lion parry.

For further reference you can use the command .getstats when targetting yourself to get your stats that the server is seeing and using for calculations directly from the server itself. The paperdoll is buggy.

**Comment by DragonTank** [comment]
thanks Blaqwar looks like it is working didn't know about that command till now yeah i cant use it on my pet so i dont know if its working on pet i guess ill look out for my pet parrying which i dont really see.

**Comment by Luth-RoR** [comment]
Works for the pet too:

[Stats for War Lion]

Strength 221 [(221 + 0) x 1]
Willpower 123 [(123 + 0) x 1]
Toughness 172 [(172 + 0) x 1]
Wounds 586 [(518 + 68) x 1]
Initiative 219 [(148 + 71) x 1]
WeaponSkill 197 [(197 + 0) x 1]
BallisticSkill 96 [(96 + 0) x 1]
Intelligence 72 [(72 + 0) x 1]
SpiritResistance 426 [(0 + 426) x 1]
ElementalResistance 302 [(0 + 302) x 1]
CorporealResistance 549 [(0 + 549) x 1]
Armor 2161 [(0 + 2161) x 1]
**Parry 10 [(0 + 10) x 1]**
CriticalDamage 50 [(0 + 50) x 1]
Item Stat Total: 139
Speed: 235
Stats Speed: 235

Without the tactic it's zero parry.
