### ISSUE TITLE
Highpass: Monster not interactable

### ISSUE THREAD

**Issue by Xanics** [WarEmu/WarBugs#8941]
Came past a goblar in Highpass which is non-interactable, non-clicky, but should be red. 

Location: 20k, 6,3k

![image](https://cloud.githubusercontent.com/assets/14800906/22086819/f181821e-ddda-11e6-805f-7d9e4ea2458b.png)

**Comment by Xanics** [comment]
a few more at: 29k,11k

![image](https://cloud.githubusercontent.com/assets/14800906/22087058/25536f66-dddc-11e6-8206-dd43460127aa.png)

**Comment by Luth-RoR** [comment]
DB devs need always the complete names to find them in the database.

**Comment by Xanics** [comment]
Cant give you the name as they are non clickable, when you hover overthem they show nothing. But in the area are a lot of goblar types. I'll see if i can note down a few later when i have time logging in.

**Comment by Ryanfawkez** [comment]
Use tab target function.

**Comment by Xanics** [comment]
U can not tab them either....

**Comment by Xanics** [comment]
I found out what it is, so dunno if it is intended or not: They are called **Beacon Gnoblar**

Accidentally AOE'd one, but you can't attack them, it always says: "Invalid Target" when you try to hit. 

![image](https://cloud.githubusercontent.com/assets/14800906/22107011/eec15a74-de4b-11e6-8cdf-47db725f9a0e.png)

**Comment by Luth-RoR** [comment]
Thanks.

**Comment by StaH84** [comment]
I can confirm that those Gnoblars are white, not red. They attack, they cannot be targetted by right click or looted. Only way is to press ESC to loose target and then they appear as target. You can use skills on them, but number on skills become red like, You would try to attack friendly NPC.
