### ISSUE TITLE
Ditry tricks - tactic. Should give 10% crit chance but giving only 5.

### ISSUE THREAD

**Issue by exotlv** [WarEmu/WarBugs#8942]
Ditry tricks - tactic. Should give 10% crit chance but giving only 5.
![erihon_007](https://cloud.githubusercontent.com/assets/8436809/22105250/d3adb5de-de4b-11e6-9537-bbdc45cb5cfe.jpg)
![erihon_006](https://cloud.githubusercontent.com/assets/8436809/22105276/e8a1c372-de4b-11e6-8c3a-4e3449b45e51.jpg)

**Comment by Soulwhisper** [comment]
Maybe tooltip visual bug?

**Comment by Blaqwar** [comment]
Try verifying it with .getstats

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=8768
