### ISSUE TITLE
ToK Unlock: Simpleton's Guide to Runes

### ISSUE THREAD

**Issue by Xanics** [WarEmu/WarBugs#8943]
[Item: #3986](https://github.com/WarEmu/WarBugs/issues/3986)

Still not working. One gets the unlock:

![image](https://cloud.githubusercontent.com/assets/14800906/22104243/965c9266-de3e-11e6-8140-c93493256b38.png)

But it is not possible to buy the item from the vendor in Altdorf.

**Comment by Blaqwar** [comment]
I just tested this on Destro, I was able to "buy" the pocket item in IC after receiving the tome unlock, even though the tome unlock will show a ??? next to the XP reward, it corrects itself and displays the pocket item after you buy it.

**Comment by Luth-RoR** [comment]
Thanks. Closing then.

**Comment by Xanics** [comment]
I still cant buy it.....

**Comment by Xanics** [comment]
Strange.... i'll try it again later
