### ISSUE TITLE
ToK Unlock: Plumes of the Eye Killer

### ISSUE THREAD

**Issue by Xanics** [WarEmu/WarBugs#8944]
Located in Blightwald, Saphery; Kill the Mob "Slashbeak" (26 Champion). 

Before you kill the mob, click on the corpse "Petrified Corpse" behind him (see picture), and you will receive a “Cockatrice Charm.”, then kill Slashbeak.  Once Slashbeak is dead you will receive the tome unlock “A Charmed Life” and the charm will vanish from your inventory. 

Clicking the "Petrified Corpse" does not grant the Charm. So killing Slashback will nit grant tome unlock.

![image](https://cloud.githubusercontent.com/assets/14800906/22106536/5ec72680-de49-11e6-8cba-471db1b7615a.png)

**Comment by Luth-RoR** [comment]
Known: https://github.com/WarEmu/WarBugs/issues/5656
