### ISSUE TITLE
hold the line ability

### ISSUE THREAD

**Issue by footpatrol2** [WarEmu/WarBugs#8945]
When conducting The Hold the line ability, it is not providing the 15% dodge/disrupt chance on allies behind the tank from getstats. 

Hold the line is providing the 45% dodge/disrupt on the tank conducting it but it is not providing any other buffs to allies behind him. 

I've tested this out on multiple tanks and its a issue with the ability itself. 

This could just be a issue that getstats doesn't show the 15% dodge/disrupt gain. I don't know. If it is known that getstats won't show this increase in dodge/disrupt, sorry for the but report.

**Comment by ozarmidrashim** [comment]
getstats doesn't show this increase because of how it is implemented
