### ISSUE TITLE
Lissariel's Glade Public Quest  Order, Empire, Chapter 7

### ISSUE THREAD

**Issue by GHUrekMazino** [WarEmu/WarBugs#8946]
I dont know if somebody already did report this but inn the public quest (name in the title) you have to collect wood which you do by clicking on tree stems. You can basically click on the same stem 50 times and grind influence incredible fast. The same works with the Scarecrows from the Blighted Farm (i think that was it's name) in Empire Chapter 5 but there you only need to interact with 10.

**Comment by Soulwhisper** [comment]
#5566 @Luth
