### ISSUE TITLE
Quests wiped after crash

### ISSUE THREAD

**Issue by Afterlife92** [WarEmu/WarBugs#8947]
So during loading screen on my wp my client crashed, after I logged in again I noticed my quest log wiped. On ToK time played changed to 1360+ days (before was like 3-5 days). I also noticed that I can do all the quests again (including epic ones). On my all other chars I don't have this time played bug.

**Comment by Soulwhisper** [comment]
A server restart might fix it.

**Comment by Xanics** [comment]
Happens quite often when you get disconnect. Dont count on the server restart, somehow never worked for me, at least...

**Comment by Luth-RoR** [comment]
Known: https://github.com/WarEmu/WarBugs/issues/2001
