### ISSUE TITLE
Rank 89 mob in IC

### ISSUE THREAD

**Issue by cimator** [WarEmu/WarBugs#8949]
Here is the ss, guessing its just a typo. ![leakypants_008](https://cloud.githubusercontent.com/assets/17130290/22151841/f1e1e1c0-df30-11e6-9c4e-fadf9697d1ec.jpg)

**Comment by Luth-RoR** [comment]
No typo; he's really 89, but DB-devs are aware of it.

**Comment by Ryanfawkez** [comment]
This should be fixed on live right now.
