### ISSUE TITLE
Scenario Bolstering Stats Bug

### ISSUE THREAD

**Issue by CeeJay89** [WarEmu/WarBugs#8951]
I'm unsure if this has already been reported, however, I have noticed that there is a bug with ORvR stats when you leave a scenario. Earlier today, I was in Nordland ORvR at lv. 15, and I had a scenario pop while I was fighting. I backed away and waited for combat to end, and had the "stuck in combat" bug trigger. I used ".unlock" and entered the scenario. Obviously, I was bolstered to Tier 2 stats. Played out the scenario, and after exiting, I didn't get ported to town, and was in Nordland ORvR. I continued playing before noticing that my HP was still 3370 like I had in the Scenario (Normally 2320). I then looked at my defensive stats, and noticed that my armor was 1042 at 75% mitigation (instead of normally 403), and my disrupt and Dodge were 40+ (instead of 29/22 respectively). I was basically invincible as a Shaman. 

I don't know exactly how to replicate this bug, and I didn't take screenshots that particular time, because I didn't think anything of it.

I attempted to replicate it, however, I couldn't get the "stuck in combat" bug to trigger, so I tried ".unlock" without, and here are the results

Stats after Scenario in T1 ORvR

![guus_000](https://cloud.githubusercontent.com/assets/25260106/22172426/8793437e-df74-11e6-9b56-0642f3f99dbc.jpg)
![guus_001](https://cloud.githubusercontent.com/assets/25260106/22172427/8b9d8fe2-df74-11e6-9a02-4c4e4b6fe536.jpg)

Normal stats in T1 ORvR (after logging out)

![guus_002](https://cloud.githubusercontent.com/assets/25260106/22172428/9554c866-df74-11e6-8f80-099c9d69de12.jpg)
![guus_003](https://cloud.githubusercontent.com/assets/25260106/22172429/97b98f9c-df74-11e6-8b26-a21145d67730.jpg)

As you can see, my HP is 330 higher, my armor is 201 points higher, my Dodge and Disrupt only rose marginally this time (0.6% and 2.7% respectively). These stats persisted even after leaving the ORvR area (at least at lv. 15)

Now, this isn't as crazy as it was the first time, however...two differences from the first time are...

1) I didn't trigger the stuck in combat bug.
2) I was warped back to town after the scenario instead of being stuck in Nordland's ORvR

Either way, my stats are higher than they should be. This could be abused if the proper trigger were discovered. I also am unsure how this would affect people who debolster to lower level ORvR and trigger it, how their stats might be affected. 

Even if I can't show the first situation, unfortunately, it did happen. My armor has been bumped up by 50% the second time as shown in the screenshots (More than an Armor pots worth), and my HP by 320 for no good reason.

Anyways, apologies if this has been reported before, didn't have time to sift through the entire thing to see if it had been reported.

**Comment by Luth-RoR** [comment]
Hm, did you actually check your stats with .getstats too?

**Comment by Luth-RoR** [comment]
Nvm, in the first screenshot your HP are also higher on the bar.

**Comment by CeeJay89** [comment]
I didn't. Didn't know it existed. I wish I would have screened the first time it happened. However, these screenshots were taken minutes apart. I took the scenario to test it, I went back to town, logged out, and back on and my stats reset to what they were. My HP was definitely higher and the first time it happened, I was taking single digit/low double digit damage from some players who were around my level (WH's, WL's, IB's.)

The exact situation the first time it happened was near the tree on the hill outside Order. I was stuck in combat when the scenario popped, I did ".unlock", entered the scenario, can't remember if I won or lost, and afterwards, I was returned to the same location in ORvR (not to town). My defensive stats and HP persisted from the scenario bolster.

**Comment by CeeJay89** [comment]
Just to show that the bolstered stats are not just visual and are working...

Mitigation from a boar w/ bolstered stats (consistently 51 and 68 mitigation). (604 Armor)

![guus_004](https://cloud.githubusercontent.com/assets/25260106/22176125/1d39bdde-dfd1-11e6-8ddd-724a6a51a33b.jpg)

Mitigation from boar after immediately logging out, original stats, no change in gear. (403 Armor)

![guus_005](https://cloud.githubusercontent.com/assets/25260106/22176140/55a2b496-dfd1-11e6-8df1-7f42ac7534f8.jpg)

I still haven't figured out how to replicate the full blown increased stats like I had the first time, but I think it has to do with triggering the stuck in combat bug, as when I left the scenario, I was still flagged for RvR the first time.

However, the minor stat increase as shown in the above two is easily replicated. Just ".unlock" before a scenario (Not sure if this step is necessary), and then play it out or even leave, and you get the bolstered stats until you log out. It persists even after death.

**Comment by TheSockPuppet** [comment]
Well gentlemen, raise your dongers for i have found a way to consistently replicate the bug!

Step 1: Go to an orvr area in T2

![image](https://cloud.githubusercontent.com/assets/25719734/23165616/bcd61626-f845-11e6-9b28-69b2b0fea04d.png)

Step 2: Enter it (Just enter it, no need to get rvr status)

![image](https://cloud.githubusercontent.com/assets/25719734/23165660/eee759d6-f845-11e6-9a34-402fbcc3bcf5.png)

Step 3: BECOME FUCKING HUGE (Until you log off)

![image](https://cloud.githubusercontent.com/assets/25719734/23165731/414ff5c0-f846-11e6-8ad3-ea8cde703ba8.png)

Step 4:BECOME A FARMING GOD! (Until you log off)

![image](https://cloud.githubusercontent.com/assets/25719734/23165934/23b08510-f847-11e6-817b-a6be382bdf13.png)

Step 5: Report bug in bugtracker, then slowly but steadily build a temple to celebrate your divinity using the corpses of your enemies as material.

![image](https://cloud.githubusercontent.com/assets/25719734/23166104/e04a134e-f847-11e6-8833-c16222e80406.png)

**Comment by TheSockPuppet** [comment]
On another note (and forgive me for quite possibly stating a different bug in the same bug thread), i noticed that while i had my absorb shield up, it absorbed far more damage than it should (instead of the damage in question being mitigated by my HUGE ARMOR RATING), i don't know if this is a known bug, a fuckup caused by this bug or if it's working as intended.

**Comment by CeeJay89** [comment]
A little different from what I reported. That would impact PvE, but the bolstering I was referring to impacts ORvR.

**Comment by Blaqwar** [comment]
Exactly, you need to take your bug report and make a new issue, these two are not the same. Your bug report deals with bolster not falling off in PvE areas. The OP's bug deals with bolster boosting past the normal tier bolster for some reason.

Also if you post the bug in a concise manner without the unecessary fluff (this isn't a forum) it will probably be more appreciated.

Also the increased absorb value you are seeing can potentially be attributed to your toughness since it affects the value of absorb shields.

**Comment by HerkRoR** [comment]
Hello,

I encountered the bug the original poster reported in comparable circumstances and would like to provide some complementary informations.

I intended to see if I could still access the T1 scenarii bracket while above rank 15 and debolstered in T1 ORvR area.
I tested with a rank 16 character who entered Nordland battlefield and got debolstered. Some minutes later he entered the Nordenwatch scenario from Nordland ORvR area, and got bolstered to rank 36. I left the scenario and got the 'quitter' debuff, I was then back to Nordland.
As I have previously noticed that the values displayed by the stats window while debolstered were wrong, I entered the command ".getstats" to check I was back to T1 debolstered stats. It wasn’t the case, the stats were higher.

To be sure it wasn’t an erroneous info given by the .getstats command, I left the ORvR area and ride to Norsca, while still flagged for RvR and debolstered, to a spot I had done some damage testing before, on rank 10 "Norse invaders" and on rank 9 champion "Aolbrandr".
I had checked that the damages were the same while my character was at rank 15, and then at rank 16 while debolstered to 15 (the tests were done in skirmish stance without VoN). They are indeed exactly the same. This time the damages, on the same mobs, were higher.

I join 2 pictures, the 1st is a recap of stats and damage tests at rank 15 (or debolstered to 15) with no bug, and the 2nd is a screenshot while bug-debolstered with an additional big combat window displaying the damages on mobs and another chat window displaying the .getstats results. Please note that despite the buffs icons appearing under the character portrait, he was not grouped nor buffed, these were a remaining visual bug from when I entered the Nordenwatch scenario and a KoTBS and a BW casted their buffs.

I hope it may help.
Regards.

![debolster infos](https://cloud.githubusercontent.com/assets/26221439/23609592/09ea4aa8-026f-11e7-859a-da8745a96d18.jpg)
![debolster bug](https://cloud.githubusercontent.com/assets/26221439/23609600/145046f0-026f-11e7-850e-97ae71fa925f.jpg)
