### ISSUE TITLE
Deadly terrain

### ISSUE THREAD

**Issue by Halhammer** [WarEmu/WarBugs#8954]
Ever since some recent patch I've come across some terrain that can insta-kill you now.

In Praag, Kurlov's Armory BO, that rubble around the breach in the backside wall can kill you if try n jump across. Same with GoE SC, the ramp goin from the center flag, left-handside if you're facing the Ammo flag.

There's prolly more, those 2 I've found so far.

**Comment by Direbolic** [comment]
Yeah the Gates of Ekrund one is really frustrating.. 2 insta full-health deaths today in 2 matches :(

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/8564
