### ISSUE TITLE
[Engineer] Keg is again on 30 Feet Range and Group only heals.

### ISSUE THREAD

**Issue by LestiArdisson** [WarEmu/WarBugs#8956]
Hello,
the Keg Heal Range is now on 30 Feet AND Group Membership condition.
It was on 60 feet and Group Membership when it was introduced with Group only heals.

On the Screenshot you can see party member who needs to be this close to receive heals.
and that looks a lot like 30 feet.

![lesti_606](https://cloud.githubusercontent.com/assets/14627932/22176192/f2cf2956-e004-11e6-83e0-08060a8fba34.jpg)

**Comment by Luth-RoR** [comment]
I just tested it and for heals on myself, it is 60 feet range.

**Comment by LestiArdisson** [comment]
Made some more testing.

On yourself Keg Range is 60 feet. If you are in a group or not.

On Group Members Keg Range IS 30 feet.

He should get a heal, but is just out of range. > 30 feet,
![lesti_607](https://cloud.githubusercontent.com/assets/14627932/22178905/5153ccd6-e044-11e6-8ff4-95fe49005b4e.jpg)

I am positioned past my group member and still get the heals, but he doesnt.
![lesti_609](https://cloud.githubusercontent.com/assets/14627932/22178913/68f9a11c-e044-11e6-94c6-e5919bb7ba89.jpg)

**Comment by Luth-RoR** [comment]
K, thanks for clarification.

**Comment by LestiArdisson** [comment]
Additional Information:
Made a retest on 11.02.2017
Bug is active.

**Comment by Seluzz** [comment]
More information about the keg...

Ive noticed that the keg wont heal my own turret, is that a bug?
Imo i see my turret as an ally, as the White Lion pet also is....

**Comment by LestiArdisson** [comment]
@Seluzz 
The Keg Heals your turret but ONLY if you are in a group.
If you are alone the Turret doesnt count as your groupmember.

**Comment by LestiArdisson** [comment]
One of the devs sais that propably one of the files regarding the ranges was mixed.
Also this is a bug report and not somekind of changerequest form.

Currently Keg heals yourself limitless range
And Group members 30 Feet.

When it was released it was around 100 feet self, and 60 feet turret.
The Dev also said that this is a bug and not intentional as it is now.

**Comment by Natherul** [comment]
keg now works as it should after next incoming hotfix (there is a slight issue with it atm)

It is 30 feet range and heals group only
