### ISSUE TITLE
Robefings of Newfound Purpose Appearance

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#8957]
- [ ] No appearance.
![warhammer online age of reckoning 01 21 2017 - 22 25 12 337](https://cloud.githubusercontent.com/assets/16864486/22177549/d0ab6c26-e028-11e6-9e3a-1ca2f7e2b6d0.png)

**Comment by Torquemadra** [comment]
yes it does, its a loincloth GO_Armor_SH_01_Body

**Comment by Razielhell** [comment]
Indeed! My bad. Dont know anything about Destro Appearances and how they look like.
