### ISSUE TITLE
Range attacking mobs bug

### ISSUE THREAD

**Issue by Kvcherk** [WarEmu/WarBugs#896]
There is a bug allowing farming range attacking mobs (even champs and heroes) without any harm. Atm tested only at SW and the main idea is in spam long range attack (e.g. Eagle Eye) on mob. Mob doesn't come close enough to use its own AA and stays still.
![selanoel_005](https://cloud.githubusercontent.com/assets/13048794/8396171/7403a360-1da3-11e5-87ba-a9d1f12cbd9c.jpg)
![selanoel_004](https://cloud.githubusercontent.com/assets/13048794/8396170/74032bd8-1da3-11e5-9dec-3ba62e9847f4.jpg)
![selanoel_003](https://cloud.githubusercontent.com/assets/13048794/8396172/74067a68-1da3-11e5-8dec-d5e3455fc0d5.jpg)
![selanoel_002](https://cloud.githubusercontent.com/assets/13048794/8396173/740854f0-1da3-11e5-9e97-927456e33c17.jpg)

**Comment by Evildoor** [comment]
No longer possible. Now ranged mobs run to you until they are close enough to shoot.
