### ISSUE TITLE
Empire T1: Tri-blaster and hellcannon damage

### ISSUE THREAD

**Issue by Direbolic** [WarEmu/WarBugs#8960]
Seems like one of these is excessive damage or the other is under powered?

Destruction Tri Barrel Hellcannon does 600-900 damage (its not consistent)
![tribarrel-hellcannon](https://cloud.githubusercontent.com/assets/25277651/22181188/a2734240-e0da-11e6-94fe-ab85e2257f37.jpg)

And Order Hellblaster Cannon hits for 291 pretty consistently.
![order-hellblaster](https://cloud.githubusercontent.com/assets/25277651/22181204/f6b19f5a-e0da-11e6-906b-c392b8433ae8.jpg)

Maybe one or both need adjusting? not sure.

**Comment by Luth-RoR** [comment]
_The damage of an artillery weapon increases the more enemies are concentrated around the spot at which it is fired. Artillery weapons inflict a stacking snare (suppression/pin) if enough targets are in the area, and the effectiveness of this snare increases further if the density of players is exceptional._
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=18308
