### ISSUE TITLE
LotD Bug, Damage through Roof

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#8961]
Thanks so much for giving me the opportunity to have a wander around Zandri again. I came across a few buggy things, but looking through this bug database a lot of them have already been reported. Hoping the ones I report aren't duplicates.

First one was this. When my character first appeared next to the pyramid in LotD, I thought to run through the tunnel sections underneath the plaza that is in front of the pyramid itself. It takes you underground, weaves about a bit, then comes up at the opposite side of the plaza. 

My character was taking damage from the mobs above this tunnel even though my character was underground and couldn't see or target them. Location marked in red on the map below. 

![lotd1](https://cloud.githubusercontent.com/assets/22262165/22183205/3fc72b54-e0b0-11e6-8863-1aca49cd8ce7.png)

![senthoi_075](https://cloud.githubusercontent.com/assets/22262165/22183213/5dda9504-e0b0-11e6-8319-7a132bbf95ac.jpg)

**Comment by lilimx** [comment]
This was fixed after LotD release.
If the issue still persist, please open a new ticket.
