### ISSUE TITLE
LotD Bug, Roaming Mobs not well... Roaming

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#8962]
Another thing I noticed, is that clusters of mobs that would be walking about in live, were just stood still in LotD. Some would also come up with "Target not Attackable" when I engaged with them, even though I could kill them and was taking damage from them as normal. Particular culprits for this were Zandri lions and mounted skeletons near to the River Mortis, but not all of them did this.

![senthoi_085](https://cloud.githubusercontent.com/assets/22262165/22183227/ca181b2e-e0b0-11e6-8d28-19bcdb16957a.jpg)

**Comment by Luth-RoR** [comment]
All the mobs lack scripting atm, that's known and just not implemented yet. Therefore i'm going to close this, thanks for reporting.
