### ISSUE TITLE
LotD Bugs, Tome Unlocks

### ISSUE THREAD

**Issue by Senthoi** [WarEmu/WarBugs#8963]
Obviously it was not possible to try all of these as PQs and Enemy Camp raid are disabled. But I did look for a couple and whilst the items were "clickable" nothing happened. Here's a list of many of the Tome Unlocks that were working in live, although I'm sure you're aware of these.

[http://gaisciochnaanu.com/warhammer/land_of_the_dead/](url)

**Comment by Luth-RoR** [comment]
The reason for this is that the PQs are not implemented yet and DB devs know the list, nevertheless thanks for reporting.
