### ISSUE TITLE
A little detail in Kadrin Valley destro keep 

### ISSUE THREAD

**Issue by Grazghal** [WarEmu/WarBugs#8964]
One of the Kazad Dammaz Stickas at the inner door lacks face textures which looks hilarious :)
![image](https://cloud.githubusercontent.com/assets/25287661/22187205/60d7cdb0-e102-11e6-9e64-1db46a20c4d0.png)

**Comment by Thayli** [comment]
Unable to reproduce. Just a visual bug, perhaps?

**Comment by Luth-RoR** [comment]
Maybe stealth fix or weird DB loading issue.
