### ISSUE TITLE
Animations: Mob lying on the ground during fight

### ISSUE THREAD

**Issue by Xanics** [WarEmu/WarBugs#8965]
While roaming through area (actually found 2 in different areas) I came across a wolf (lying on the ground), which attacked me in the same position. See images below. Throughout the whole fight stayed in that position. Probably only a minor glitch, still wanted to report it. 

One is in Reikland at position 8.3k, 44.6k Mob: Reikwolf):

![xanics_031](https://cloud.githubusercontent.com/assets/14800906/22196751/fadd026c-e14e-11e6-8847-f728cb307f02.jpg)

![xanics_034](https://cloud.githubusercontent.com/assets/14800906/22196798/42396646-e14f-11e6-9619-f49bb4fbe542.jpg)

Other one is in Dragonwake at 8.1k, 53.8k (Mob: Bloodfur Hunter)

![xanics_038](https://cloud.githubusercontent.com/assets/14800906/22196787/2de11b26-e14f-11e6-8566-7e3b2858af7b.jpg)

**Comment by Ryanfawkez** [comment]
Can't fix this yet, as the loop emotes these mobs have cannot be broken without the proper scripting.

**Comment by Ryanfawkez** [comment]
This should be fixed now.
