### ISSUE TITLE
Annihilation (epiq quest in Reikland) is bugged!

### ISSUE THREAD

**Issue by sansaraeternal** [WarEmu/WarBugs#8966]
When I go to the Dead Mans Cave in Reikland and try to interact with the altar - nothing happens. I tried to abandon the quest - nothing helped. Cant finish this quest. Help!

**Comment by Hulawar** [comment]
Yeap , its still buged. Cant get my chopa...

**Comment by Luth-RoR** [comment]
https://translate.google.com/?tl=hr#auto/hr/fix%20pending
