### ISSUE TITLE
Magus`s Moral 2

### ISSUE THREAD

**Issue by Glohroc** [WarEmu/WarBugs#897]
Moral of Magus`s class "Siphon`s Power" doesn`t work properly-it lowers intelligence of target, but doesn`t give ap as it should.

**Comment by Tesq** [comment]
it should give ap only if/and for the ammount of the target having ap  (0 to 200 so), it should always give 200 ap from mobs indeed.

**Comment by Evildoor** [comment]
So, i do believe this morale (as well as Force Of Will) is bugged after all. When used against you it correctly reduces your AP, but many times when i used it myself (on players) i got no AP at all. Well, maybe it's a coincidence that i used it on targets with exactly 0 AP like 10-12 times in a row, but i doubt it...

**Comment by ozarmidrashim** [comment]
Disagree.

            private bool StealAp(AbilityCommandInfo cmd, byte level, Unit target)
            {
                Player plrTarget = target as Player;

                if (plrTarget == null)
                    return false;

                if (cmd.PrimaryValue != 0)
                {
                    short deltaAp = plrTarget.ModifyActionPoints((short) -cmd.PrimaryValue);
                    ((Player) _caster).ModifyActionPoints((short) -deltaAp);
                }

                else
                    ((Player)_caster).ModifyActionPoints(Math.Abs(cmd.lastCommand.CommandResult));

                return true;
            }
