### ISSUE TITLE
Zealot Bug Issue Graphics Bug ; Harbinger Of Doom Bug

### ISSUE THREAD

**Issue by DenizFA1994** [WarEmu/WarBugs#8970]
I dont know if this will help , but i think i found a bug in Warhammer Age of Reckoning ,
I cant say much about this bug only which skill it affects, the so called bug comes from the Zealot Skill Harbinger Of Doom.  

I post some Screenshots for the Team to look at it for yourself , maybe it is just a temporary bug , but i saw it randomly .
![shillsslayer_008](https://cloud.githubusercontent.com/assets/25309837/22225082/55c33e7c-e1c1-11e6-9bbb-efad67a85499.jpg)
![shillsslayer_003](https://cloud.githubusercontent.com/assets/25309837/22225083/55c50c48-e1c1-11e6-90de-cf5d7df6f437.jpg)
![shillsslayer_004](https://cloud.githubusercontent.com/assets/25309837/22225086/55c67b5a-e1c1-11e6-909f-38506077ff39.jpg)
![shillsslayer_005](https://cloud.githubusercontent.com/assets/25309837/22225087/55c70f48-e1c1-11e6-882e-0deb7cf0ee35.jpg)

with friendly greetings DenizFA A.k.A Shillslayer

**Comment by Blaqwar** [comment]
Client-side issue, not fixable yet. See here: #8833

**Comment by DenizFA1994** [comment]
Okay just wanted to let you know guys ,
by the way i love this game . 💃
