### ISSUE TITLE
Pets/turrets keep attacking even when user flees.

### ISSUE THREAD

**Issue by CaledorTree** [WarEmu/WarBugs#8974]
It is a very well known issue that even when SH/WL/engi/magus use flee, their pets keeps attacking you so their escape is guaranteed. Once a squig  pet was attacking me for minutes no matter the SH was not even visible. He had used flee several times. It is a very well known issue but I can provide video if needed.

**Comment by Blaqwar** [comment]
Afaik the pet's behaviour when the owner flees is working as intended. So unless you were told that it's not by a member of the RoR team or can provide proof that it's not working as intended (compared to how it worked on AoR) you'll simply get this closed.

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=15&t=19678&p=215546#p215546

**Comment by Silentguard** [comment]
WL pet just teleporing to you every attack, can easy chase you even on mount.

**Comment by Nfkillz** [comment]
https://youtu.be/nvDM7jbl2Lo

**Comment by Luth-RoR** [comment]
Lion without "speed training" tactic?
And i thought this report is about that pets should stop attacking when their master is pressing "flee".

**Comment by Luth-RoR** [comment]
About pet speed: https://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=19731#p216305

**Comment by Kaelang** [comment]
No confirmation was provided. I am now going to close this issue.
