### ISSUE TITLE
Talabec dam, stuck issue

### ISSUE THREAD

**Issue by M0rf** [WarEmu/WarBugs#8975]
Where the bomb drop off is for order its possible to get stuck between what appears to be 2 invisible barriers behind the fence, you cant move at all.

If its possible, removing 1 of the invisible barriers and bringing the other infront of the fence instead of inside it should solve this issue.

**Comment by seraxes** [comment]
I've just successfully punted a Sword Master who landed on the fence and got stuck, he couldn't be damaged anymore, couldn't move. 
![rexar_001](https://cloud.githubusercontent.com/assets/16610103/22397215/21c7ae14-e56d-11e6-9c35-028508c6f9b4.jpg)
