### ISSUE TITLE
Nobility-Quest

### ISSUE THREAD

**Issue by atharol** [WarEmu/WarBugs#8976]
**Quest Name:** _Nobility_

**Explanation:**
The objective text and mission is bugd, The text tells us to kill the same thing 1 and 10 times.
There is only 1 Blighted Believer in the middle of the field surrunded by npcs called "Blighted Mutant"
-------------------------------------------------------------------------------------------------------------
**Problem**

_Quest objective: 

Kill Blighted Believer 0/1
Kill Blighted Believer 0/10_
-------------------------------------------------------------------------------------------------------------
**Solution:**

_Change text of the quest objective to following:

Kill Blighted Believer 0/1
Kill "Blighted Mutant" 0/10  <--

And change in database so that Kill "Blighted Mutant 0/10" is no more Blighted Believer._

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20Nobility
Additionally the abuse of formatting for no reason makes this very hard to read.
