### ISSUE TITLE
[Witch Elf]T3 Scenario Weapon cost issues

### ISSUE THREAD

**Issue by Blaqwar** [WarEmu/WarBugs#8977]
T3 Witch Elf weapons from the scenario vendor cost the following amounts:

CR24/RR24: 32 Emblems
CR29/RR29: 30 Emblems

It doesn't make sense for the lower level/power weapon to cost more.
For comparison, Witch Hunter weapons cost:

CR24/RR24: 19 Emblems
CR29/RR29: 30 Emblems

I imagine this is an oversight but I believe it's a relatively easy fix.

**Comment by wargrimnir** [comment]
Fixed in next
