### ISSUE TITLE
[AM/Sham] Ap drain still tick once per second instead of 3

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#8982]

**Comment by arthur3k** [comment]
AP Drain is suppose to drain 20AP/ 1s for 3s insted of 60AP/3s?

**Comment by Blaqwar** [comment]
Yes:

`Drain Magic steals 20 AP every second rather than 60 AP every 3 seconds.`

From https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=8768

**Comment by Silentguard** [comment]
Oh wait... this is buff of OP ability. Every time i reporting broken OP shit someone says "not a bug, it's a feature".

**Comment by Luth-RoR** [comment]
Please stop opening new tickets for

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/8821

**Comment by ozarmidrashim** [comment]
Please don't whine. You are better than that.
