### ISSUE TITLE
Army of faith PQ in Talabecland chapter 11 stage 3 inaccessible 

### ISSUE THREAD

**Issue by IxanderousI** [WarEmu/WarBugs#8985]
Stage 1 asks you to kill the peasants which are placed just outside of the PQ area to the east, killing them allows you to complete the stage, 100 influence received per kill but no extra influence for completing the stage, transit to stage 2.

Stage 2 asks you to kill the tower guard which are stood outside the entrance of the building that is situated direct in the centre of the PQ area, kill 4 tower guards, 2 of which only spawn at a single time, wait for respawn, kill the next 2 then stage complete, 100 influence received per kill and extra 250 influence for completion of stage 2, transits to stage 3.

Stage 3 kill Arch *forgot the name* unable to complete the stage because he is no where to be seen, i suspect he is located inside the building which appears to be a church, the doors however are closed and are unable to be opened, so he must be located either inside behind the inaccessible door, i have also searched the whole area surrounding the church but could not find him there either to complete the quest, result, timer runs out, message PQ finished, no influence or rewards.

**Comment by Razielhell** [comment]
#7362

**Comment by Razielhell** [comment]
@IxanderousI Yo! Thanks for the detailed report though!! Please next time make sure that the problem isnt already reported.

**Comment by Luth-RoR** [comment]
Copied the details to the linked report.
