### ISSUE TITLE
(BO Tactic) Dat was great not stacking.

### ISSUE THREAD

**Issue by Esperflame** [WarEmu/WarBugs#8986]
I was discussing with Druin and he suggested I bug report this. The tactic Dat was great isn't properly stacking with the stat steal of Da Biggest. He stated that tactics should always stack with just about everything. As this is an ability and a Tactic I'm thinking these are supposed to be stacking.

**Comment by ozarmidrashim** [comment]
Nope. DWG! modifies Wot Armor's debuff, which is Standard type. They don't stack.
