### ISSUE TITLE
No influence afther lock KV

### ISSUE THREAD

**Issue by andarkk** [WarEmu/WarBugs#8988]
it's 3th times that when a zone lock i gain renow and influence but only renow bar is refresh.
So i lost first time 3800 influence and now, afther 4 hours at kadrin, 7200 influence.
If you see combat log, it show that i gain 7200 influence.
Pls fix this bug...

Andarkk

**Comment by Razielhell** [comment]
...:P

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/8924

>Pls fix this bug...

Thanks for the reminder. Without it, maybe devs forget to fix them bugs.
