### ISSUE TITLE
Ironfeather loot Bug

### ISSUE THREAD

**Issue by Solutar** [WarEmu/WarBugs#8989]
Hello,
Me and my Friend just killed Ironfeather, the Mob in Eataine, to get the Item called "Eagle-Eye" for the Jewelry Set. Sadly the Mob doesnt Drop the Item for us for no explainable Reason for us.
Details: We are 2, one Chosen(me) and One Black Guard, We are in Eataine and killed both the Mob Ironfeather. First we killed together, after we noticed it didnt dropped the Item we killed it Solo, again no Item.
Also it changed it appearance after it got killed. First it looked like a Griphon, after it respawned it looked like an Eagle. Again killed it respawned it looked like a Griphon again etc.

Many thanks in advance, hoping I am not wasting your guys Time. :)
Solutar.

**Comment by Natherul** [comment]
they do not drop it, they give tok unlock that allows you to buy the items from the capital https://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=13566&hilit=oathstone

**Comment by Solutar** [comment]
Thank you.
