### ISSUE TITLE
[SC][Terrain] Battle For Praag - barrier placing

### ISSUE THREAD

**Issue by Tyramissoux** [WarEmu/WarBugs#8990]
Nothing of high importance but in battle for praag, the barriers at mid BO should be either a bit closer to one another or a tad further away. Got stuck in between and couldn't get out anymore. 
Would be nice to get that adjusted one day because the elements are present in the middle of the fighting area and might cause problems for others, too.
![noiree_131](https://cloud.githubusercontent.com/assets/13544944/22315300/37f1622e-e366-11e6-8ff8-55646e70c5c8.jpg)

**Comment by Ryanfawkez** [comment]
Placed some objects in-between, since displacing these barricades is a pain in the ass.
