### ISSUE TITLE
Exp over gain...

### ISSUE THREAD

**Issue by SweNinja** [WarEmu/WarBugs#8991]
ive enterd black crag, and was walking just north of the war camp over the bridge. as i enterd the next area i gain over 200.000 exp.... i have screen shot if it's interesting
please contact me =)

![sweninja_000](https://cloud.githubusercontent.com/assets/25357451/22316120/4ecf4f4c-e36b-11e6-9e1a-44d7a441d544.jpg)

**Comment by Luth-RoR** [comment]
Did you actually got the experience or was it just shown in the chat window?

**Comment by SweNinja** [comment]
hi.... to be honest, i cant be 100% sure. ive just gained a lvl, so i think i got it... but the wierd thing is that when it happend my RN'bar went missing.. so i couldnt use some gear. got really scared so i relogged, and it was back... you can see that its missing on the pic.... wright me back

**Comment by SweNinja** [comment]
As i wrote on Github. i've just lvl'ed up just before that happend. So i
cant be 100% sure that i gained the exp, but i think so... And when it
happend my Renown bar went missing as seen on the pic. That however came
back when i re logged... please get back to me thanks up front

 /SweNinja

2017-01-26 14:35 GMT+01:00 Luth <notifications@github.com>:

**Comment by Luth-RoR** [comment]
>please get back to me thanks up front

Hi, it's atm unknown what could cause this, maybe others experienced it too; at this point we have to wait.

**Comment by SweNinja** [comment]
Ok i see... I do hope that people are as honest as i am regarding reporting
bugs that are positive as well as  negative... =)
any how keep in touch if something comes up....
And a last thing, my jewelry that was for the other Faction(realm) are
still for me.... cant use them... do u want me to send a picture?


//Swe Ninja

2017-02-12 10:07 GMT+01:00 Luth <notifications@github.com>:

**Comment by Luth-RoR** [comment]
The class requirements on jewelry/cloaks have been adjusted in recent patches; you can still use them to get talisman fragments out of it.
