### ISSUE TITLE
DoK bugg with White Lion

### ISSUE THREAD

**Issue by ka3vas** [WarEmu/WarBugs#8994]
![sciezka_002](https://cloud.githubusercontent.com/assets/25376843/22353797/8e846ee4-e422-11e6-85d6-39ecfbcafc66.jpg)

Im not sure if it really gives so much resistance, but this is what it displays when the cat hits you with hes armor penetrating skill.

**Comment by Luth-RoR** [comment]
You can use .getstats in the chat window to see your real values.

**Comment by Silentguard** [comment]
Thats happens because 'not OP' WL pet drops your armor below zero.

**Comment by Kaelang** [comment]
No confirmation was provided. I am now going to close this issue.
