### ISSUE TITLE
SC Items bound to player

### ISSUE THREAD

**Issue by DonCarlos3850** [WarEmu/WarBugs#8995]
I won -as a rune priest- Spatterguards of the Mercenary (shoes of mercenary set for sigmar priest) in a scenario.
The item was bound to the player (me)
This is wrong, it should be Bound on equip or something like that.

**Comment by Luth-RoR** [comment]
It isn't bound to you; you can trade it via the autction house or put it in the guild vault for others. There is a known visual issue with the items, which show them as bound on pickup, but they are not. This can't be solved atm.
