### ISSUE TITLE
bugged pq in warhammer online

### ISSUE THREAD

**Issue by BlckGrif0n** [WarEmu/WarBugs#9005]
Pq named Plague Mist vale(10486,18175) in Kadrin Valley is bugged.minions are twice more and they on stage 2 kill each other.On stage 3 pq spawn 2 bosses and creatures from stage 2 as well and they start to kill each other.Sorry for bad english

nickname in game Anhur 
![anhur_000](https://cloud.githubusercontent.com/assets/25391293/22381891/7b74a0d2-e4d4-11e6-9971-4abc24357306.jpg)
![anhur_001](https://cloud.githubusercontent.com/assets/25391293/22381899/814bcff8-e4d4-11e6-9b2a-db90119406af.jpg)
![anhur_002](https://cloud.githubusercontent.com/assets/25391293/22381901/86f2af08-e4d4-11e6-8454-0231c447eeee.jpg)
![anhur_003](https://cloud.githubusercontent.com/assets/25391293/22381903/8a8ec3e0-e4d4-11e6-87f0-51994491d952.jpg)
![anhur_004](https://cloud.githubusercontent.com/assets/25391293/22381906/8d0e964a-e4d4-11e6-9651-ccbe75486f3d.jpg)

**Comment by Luth-RoR** [comment]
There is already a report for the PQ: https://github.com/WarEmu/WarBugs/issues/7246
