### ISSUE TITLE
Scenario Disbalance

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#901]
WTF?

http://take.ms/oFLTa

**Comment by ozarmidrashim** [comment]
Closed because I have no idea what on earth you're trying to point out here.

**Comment by Silentguard** [comment]
Agreed with subject. Need to do something with this, at least fix the bolster. For now chars below level 8 deal damage to high level tanks with 75-90% mitigation, even cloth armor have mitigation over 50%.

**Comment by Tesq** [comment]
level 2- 5 schould not do pvp :/ 

that's totaly normal, aza could provide a better bolster value but that's your fault to enter sc with so low levels that cannot have a propper gear.
Dont know what right you should have to be lv 2-5 and be the same fo a level 10-11.....you just need 2 h to arrive at level 7 at least. You can bear it..........

**Comment by Silentguard** [comment]
Let me be clear. Its a pvp game and any player should be able to play pvp even from lvl1. So im talking about things making this game challenging and actualy not talking about 1lvl should be the same as 11lvl.

**Comment by Silentguard** [comment]
Or you can play sc like this kicking shit around 10 minutes.
![2015-06-30 04 27 00 013](https://cloud.githubusercontent.com/assets/13031465/8417627/577037fc-1ee0-11e5-86f6-034db2dd08b6.png)

**Comment by Nfkillz** [comment]
Each side should have chances for victory on scenario . But when I offen look at scenario summary I realise that its fail for us. For example games with 0-1 healers vs 2-5 healers.

**Comment by Evildoor** [comment]
Not a bug.
