### ISSUE TITLE
Loot disappearing when party member disconnects

### ISSUE THREAD

**Issue by M0rf** [WarEmu/WarBugs#903]
As title says, 2 ppl in party, loot drops and player disconnects during roll before they can need/greed/pass and loot is gone.

**Comment by Evildoor** [comment]
Has to be tested. There was a problem which caused the item to disappear when at least one party member pressed no need/greed/pass at all, and it was fixed. I don't know, if this is the same one or not.

**Comment by Luth-RoR** [comment]
No evidence/response -> closed.
