### ISSUE TITLE
Chapter 6 Greenskin [Public Quest] The Specter of Battle

### ISSUE THREAD

**Issue by Zoggof** [WarEmu/WarBugs#9031]
In Stage III there are no Hammerstrike Sharpshots anywhere to kill and you cannot progress through the PQ after this stage.

Also not sure if intended but you can also get stuck in room in the caves where Muzinko's Remains are and you are forced to book out.

**Comment by Luth-RoR** [comment]
There is already a report about that PQ:https://github.com/WarEmu/WarBugs/issues/7487
