### ISSUE TITLE
Sharpthorn Rock Mine - Public Quest Greenskin Chapter 2

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9032]
- [x] PQ Tracker needs to be extended in Red areas.

**_There are mobs in Stage 2 and especially one Hero in Stage 3(Last Stage) in the red marked area where PQ Tracker dissapears so if its the last mob you need to kill and you go in there you lose the loot roll._**
![warhammer online age of reckoning 01 28 2017 - 12 39 53 168](https://cloud.githubusercontent.com/assets/16864486/22396060/29be95ac-e558-11e6-9455-3362591882c5.png)
![warhammer online age of reckoning 01 28 2017 - 12 39 34 167](https://cloud.githubusercontent.com/assets/16864486/22396077/f3dfa45c-e558-11e6-9ca1-975d2e8cbe76.png)

**Comment by wargrimnir** [comment]
I'll have to check the map, the correct one may not be on live.

**Comment by saupreusse** [comment]
fixed in next patch
