### ISSUE TITLE
Talabec Dam bugs

### ISSUE THREAD

**Issue by Lanric** [WarEmu/WarBugs#9035]
1. If you die with the keg on you, you are unable to mount after respawning (I presume this one is known already)
2. If you are positioned in a certain way you can get stuck by the explosion on the dam side of the map, inside the fence - posting a screenshot to back it up. You're not able to move, the /stuck command doesn't seem to work inside a scenario and you can't even target the enemies on the other side of the fence.

http://i.imgur.com/Nu6zTza.jpg

**Comment by Blaqwar** [comment]
Sorry but if you had done a simple search of "Talabec Dam" you'd see that both are already reported.

#8975
#8907
