### ISSUE TITLE
Quests resetting/restarting?

### ISSUE THREAD

**Issue by Sciberr** [WarEmu/WarBugs#9036]
I was just playing and realized some of my partially done quests/already finished quests have gone away or was available to do again and this allowed me to get 4 skaven tokens for the companion by doing the same couple of quests twice.

**Comment by Afterlife92** [comment]
I had same thing on my wp after my game crashed during loading screen. I think it's not fixable right now and it's releated to client issue. This issue is know already https://github.com/WarEmu/WarBugs/issues/2001
