### ISSUE TITLE
Talisman Making bugs out when adding Strand of Veridian Haze

### ISSUE THREAD

**Issue by Suqubi** [WarEmu/WarBugs#9038]
Filled talisman making window with 

Apprentice Relic Box
Any Fragment
any gold, curio, essence

if the fragments run out the whole thing goes blank when adding
Strand of Veridian Haze

trying to add a different fragment after works fine, even auto fills all the slots.

![wry_001](https://cloud.githubusercontent.com/assets/25412926/22402628/e2ca3182-e5b2-11e6-87f5-8eec76a382b8.jpg)
![wry_000](https://cloud.githubusercontent.com/assets/25412926/22402629/e2cadd1c-e5b2-11e6-8b31-05b22f017d3f.jpg)

**Comment by Suqubi** [comment]
Update:
Cant add Strand of Veridian Haze to Talisman making window at all.

**Comment by Luth-RoR** [comment]
Stacks don't renew on the crafting window, which is known.
Adding strand of veridian haze to the window works fine for me; some addons bug the window (ezcraftx afaik).
