### ISSUE TITLE
ToK or Lore

### ISSUE THREAD

**Issue by Ivnerd** [WarEmu/WarBugs#9039]
When activated has to be Tok unlock. Don't remember what exactly.
![ivnel_001](https://cloud.githubusercontent.com/assets/25414475/22403428/e9eb8d60-e627-11e6-9034-7bb57497d244.jpg)
![ivnel_000](https://cloud.githubusercontent.com/assets/25414475/22403429/edfb2834-e627-11e6-9540-6fdddbb04f83.jpg)

**Comment by Ivnerd** [comment]
Don't remember that High Elve should be here, also as enemy and with Tok unlock about manticor
![ivnel_006](https://cloud.githubusercontent.com/assets/25414475/22403463/efcea93c-e628-11e6-80f4-cb906ebbfea3.jpg)
![ivnel_004](https://cloud.githubusercontent.com/assets/25414475/22403464/f36709fe-e628-11e6-81ab-24a0aae70fa1.jpg)
![ivnel_005](https://cloud.githubusercontent.com/assets/25414475/22403465/f57e2646-e628-11e6-983f-68fd578150cc.jpg)

**Comment by Ivnerd** [comment]
The giant sceleton should to appear after kill some normal sceletons and destroy urns. And giant sceleton has to be champion as minimum
![ivnel_002](https://cloud.githubusercontent.com/assets/25414475/22403479/5e7b37ce-e629-11e6-8ccc-03e426741cda.jpg)
![ivnel_003](https://cloud.githubusercontent.com/assets/25414475/22403480/660641be-e629-11e6-9b37-bb7c2781e0be.jpg)

**Comment by Luth-RoR** [comment]
One report per bug, please check the bugtracker rules. 
Furthermore the last issue is simply not implemented yet and the rest is literally "something is wrong, but i can't remember what and how it was called", which is not useful. Again, please read the bugtracker rules before opening another report.
