### ISSUE TITLE
Build up cancels if pre-casted after an insta

### ISSUE THREAD

**Issue by Mezirah** [WarEmu/WarBugs#904]
If you cast chillwind, then any build up spell such as doombolt, gloomburst, arctic blast, the build up cancels and you must re-activate. The biggest culprit is chillwind, and then something, but the bug also happens to me after casting any insta on my bars including my buffs.

**Comment by xyeppp** [comment]
#843 Like this?

**Comment by Mezirah** [comment]
The spell is not delivered server side on my bug.

**Comment by xyeppp** [comment]
Yeah, because you might be spamming it when the gcd should still be up and that's what's broken. It will get interrupted, because you should still be on gcd.

**Comment by xyeppp** [comment]
Yes. But what I mean is that insta-casts trigger your GCD as well which is incorrectly being shown on the client, therefore allowing you to charge a spell in that split second the gcd is up but it will never fire, because it should not.

**Comment by Krazis** [comment]
I am having the same issue as Mez, however I will double check with what you say xyeppp. 
How can I check if the spell is delivered server side Mez?

**Comment by Evildoor** [comment]
Tested, seems to be fixed.
