### ISSUE TITLE
Public Quests (something wrong)

### ISSUE THREAD

**Issue by Ivnerd** [WarEmu/WarBugs#9040]
PQ, Avelorn, doesn't count when killing NPC
![ivnel_000](https://cloud.githubusercontent.com/assets/25414475/22403564/2b75d26e-e62c-11e6-9bb4-b8bc0d7948a3.jpg)
![ivnel_001](https://cloud.githubusercontent.com/assets/25414475/22403565/2d1265ce-e62c-11e6-924a-da96fd8276f6.jpg)

**Comment by Ivnerd** [comment]
Checked also PQs Rotten Embrace and Ritual of Corruption have the same situation. Cannot do PQ

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=16052
