### ISSUE TITLE
[BG] Mind Killer decrease wp and int lower then in description.

### ISSUE THREAD

**Issue by Killham** [WarEmu/WarBugs#9042]
![karasik_000](https://cloud.githubusercontent.com/assets/18173840/22407365/2c08c174-e676-11e6-9435-24d50a081abf.jpg)
![karasik_001](https://cloud.githubusercontent.com/assets/18173840/22407369/3594b946-e676-11e6-9975-59395787363b.jpg)
AND ITS NOT VISUAL BUG OR SOMTHING ELSE.

**Comment by Luth-RoR** [comment]
Known: https://github.com/WarEmu/WarBugs/issues/7501 and i just checked it with getstats.
