### ISSUE TITLE
PvE zone of the Keep Covenant of Flame (Dragonwake t4) 

### ISSUE THREAD

**Issue by Thunderblood** [WarEmu/WarBugs#9046]
A small area in the Keep to create AAO buff or other things. 

![kobrin_000](https://cloud.githubusercontent.com/assets/25457842/22468519/bb0dabbe-e7f2-11e6-8538-a60d09c6a369.jpg)
![kobrin_002](https://cloud.githubusercontent.com/assets/25457842/22468520/bb0eb27a-e7f2-11e6-9044-977221103ac7.jpg)

**Comment by saupreusse** [comment]
fixed as good as possible. but might still be an issue. there is a cave beneath this place and i dont want to rvr flag it...
