### ISSUE TITLE
Battle at Blood Fen - Public Quest Destruction Greenskin Chapter 6

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9048]
- [ ] Double spawn over here. One of them doesnt count by killing him.
![warhammer online age of reckoning 01 31 2017 - 23 06 20 03](https://cloud.githubusercontent.com/assets/16864486/22484954/5c3dd23e-e80c-11e6-8b2e-bf86af68c9e2.png)

**Comment by Thayli** [comment]
Fix pending.
