### ISSUE TITLE
Latest Patch: AoE (de-)Buff affected Siege engines?

### ISSUE THREAD

**Issue by salamisocke** [WarEmu/WarBugs#9049]
Since the latest Patch from 31/1/2017 the AoE-Dmg got increased, but was it intended that this Buff will affect siege engines? i shot the hellfire cannon from the chaos camp in t1.  it shot 1000-1500, and sometimes even 1700aoe dmg  (in T1!). seems to be very overpowered
before the patch it was something like 400-600 afaik.

sorry for my english

**Comment by Luth-RoR** [comment]
The damage of AoE cannons depends of how many enemies are hit by it; it was like that even before the patch.
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=18308

**Comment by Luth-RoR** [comment]
Was this in a scenario or in the normal warcamp?

**Comment by sioding** [comment]
No answer since 01.2.2017 - close for now.
