### ISSUE TITLE
Greenskin Chapter 4 Influence Bar

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9050]
- [x] Bar not filling on UI and ToK. Players normally see influence pop on their screen/chat log by participating in Chapter 4 though. 
**_Waited for 2-3 server restarts but didnt fix it._**
![warhammer online age of reckoning 01 31 2017 - 23 38 19 05](https://cloud.githubusercontent.com/assets/16864486/22485602/f22cf7be-e80e-11e6-8ac4-4949fa012b2c.png)

**Comment by Draxonfly** [comment]
Just wanted to add that this is still an issue. The Influence Bar is not filling up so in turn unable to receve greenskin Chapter 4 pq influence items.

**Comment by wargrimnir** [comment]
Fixed in next, had the wrong influence set.
