### ISSUE TITLE
[SC][Terrain] falling dmg insta kill in Nordenwatch

### ISSUE THREAD

**Issue by Tyramissoux** [WarEmu/WarBugs#9051]
Discovered another killer rock. Got punted, landed at the edge of a rock and instantly died. Should have taken another screen for better position viewing. 

![noiree_136](https://cloud.githubusercontent.com/assets/13544944/22487696/aa530ce4-e80e-11e6-8603-801ecd05da84.jpg)

**Comment by saupreusse** [comment]
hmm its not fixable.  the insta gib terrain spots are in many places
