### ISSUE TITLE
Chaos Chp 7. Quest Temptress

### ISSUE THREAD

**Issue by GHUrekMazino** [WarEmu/WarBugs#9052]
I've tried attacking it, looking for items (even hidden items since mir dye sometimes bugs out and isn't shown in my bag) but i couldn't find a way to destroy the shrine.

**Comment by GHUrekMazino** [comment]
nevermind just found out that the circle is on the wrong spot on the map 

![image](https://cloud.githubusercontent.com/assets/25225415/22504119/20ff701a-e875-11e6-93ee-5a8b188cf3e1.png)

**Comment by Luth-RoR** [comment]
A known issue: https://github.com/WarEmu/WarBugs/issues/8255
