### ISSUE TITLE
Impossible loot in Backpack

### ISSUE THREAD

**Issue by SweNinja** [WarEmu/WarBugs#9054]
Hi as i was browsing my backpack i found a RARE item in it... A ring made for the opposite Faction/Realm....so il show you to make it easy =)... due to the lack of english skills from my side =)

please wright me back asap

![sweninja_001](https://cloud.githubusercontent.com/assets/25357451/22517765/8a96b24c-e8aa-11e6-8474-804339cb08f7.jpg)

//SweNinja

**Comment by Torquemadra** [comment]
Jewellery that was missing a flag now correctly has it applied, as the name suggests "ember" is a ring for a BW, not any destruction class.
