### ISSUE TITLE
[item] precursor choppa

### ISSUE THREAD

**Issue by zak68** [WarEmu/WarBugs#9056]
seems that two versions of the same item exist:
both are uncommon lvl 39 47dps 2.9 speed axes but one is
31str 16ws 2%disrupt
while the other is
28str 28th 14ws

**Comment by Luth-RoR** [comment]
Any screenshot?

**Comment by zak68** [comment]
![untitled](https://cloud.githubusercontent.com/assets/17765890/22564200/ecc10844-e983-11e6-8238-12b44c986578.png)

**Comment by Luth-RoR** [comment]
Thanks.

**Comment by zak68** [comment]
np, anyway seems that more items have different stats while having the same name: try "Enduring Choppa" or "Choppa of the Eternal".

**Comment by wargrimnir** [comment]
Renamed the Precursor item. Is this just something common to the Choppa items?
