### ISSUE TITLE
[RvR] Diminishing Rations probably applied on defenders not on attackers.

### ISSUE THREAD

**Issue by Killham** [WarEmu/WarBugs#9057]
Yesterday in two keep sieges DR applied on defenders both times, first it happend in eataine destro was defend keep and order attack and on destro applied DR with nearly 15-20% wounds debuff when in keep area order has probably in 2-2.5 times more people, second time in caledor (today in 1 a.m.) DR applied on order when destro attacked keep with surpassing numbers of players.

**Comment by Killham** [comment]
SOME EVIDENCE WITH DIMINISHING RATIONS ON DEFENDERS WITH AAO AND WOUNDS DEBUFF
![5](https://cloud.githubusercontent.com/assets/18173840/22566124/d087ff9e-e99b-11e6-82f2-5350dd55ce77.jpg)

**Comment by Natherul** [comment]
diminishing rations should be applied to defenders and not attackers...

**Comment by wargrimnir** [comment]
> A keep can support 25% of the attacking force's total numbers as defenders at rank 0, and can support an additional 15% per rank attained. If this limit is exceeded, Diminishing Rations applies.
