### ISSUE TITLE
Magic item

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#907]
![warhammer_ age of reckoning version 1 4 8 copyright 2001-2012 electronic arts inc 2015-06-29 17 42 10](https://cloud.githubusercontent.com/assets/13031465/8405331/46ad0b20-1e86-11e5-9889-edfaddc9d8c0.png)

**Comment by Evildoor** [comment]
Block does not works, btw.

**Comment by Reggaewaldo** [comment]
This has now been changed on the dev server according to online sources.
http://www.warbits.com/gold-items-27995-Marsthum-Bladestoppa.html

The change will carry over to the live server when next hotfix.

Closing.
