### ISSUE TITLE
SC serpent's passage disconnecting issue

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#9085]
in your very first serpent's passage SC after login
if u didn't get dmg nor deal dmg
like walk there, grab it and drop it like nobody around 
when droping action bar completed you get disconnected from server
experienced this 2 times and saw once someone disappear in same situation
didn't get points, part just respawn
you can rejoin server with no problem after dc screen

**Comment by Kaelang** [comment]
Tested without any issues. Please re-open if issue persists on live servers.
