### ISSUE TITLE
Order Tier 4 Keep Lords

### ISSUE THREAD

**Issue by tionblack** [WarEmu/WarBugs#9086]
Tier 4 Keep Lords  are unclickable thus making us unable to take defence quests or any if exists.
1 week ago they were working.

Also i created a dwarf character and some achievements are applying but you dont see that small screen telling you what you have unlocked.Thanks for your time and effort.

**Comment by Luth-RoR** [comment]
Only one bug per report as stated in the BT rules please.

**Comment by sioding** [comment]
**Thanks for the report.** Since there is no confirmation, i will close this issue now. Please make sure to follow the bugtracker rules which you can find here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)
