### ISSUE TITLE
Waruhag the Black not clickable

### ISSUE THREAD

**Issue by milosxe** [WarEmu/WarBugs#9087]
Quest giver for destro epic quest chain Time to Waaagh! in Greenskin ch22 cannot be interacted with.

**Comment by Ryanfawkez** [comment]
No issue on dev. No figleaf data interfering. Only possible options is unks or client.

**Comment by milosxe** [comment]
I tried relogging back then and checked on few characters. Wasn't clickable. Tried today and he is.
