### ISSUE TITLE
Can't open loot bag

### ISSUE THREAD

**Issue by AndrewDawnbringer** [WarEmu/WarBugs#9088]
I received a Loot bag in mail, from a PQ, but actually, I can't open it.
Screenshot: http://imgur.com/a/5DWkE

**Comment by Luth-RoR** [comment]
Report needs info which PQ it was.

**Comment by AndrewDawnbringer** [comment]
Maybe the Ruinous powers or the 2nd one in Destuction chapter 2. I don't remember, I just got the loot in mail.

**Comment by Luth-RoR** [comment]
Should be fixed now.
