### ISSUE TITLE
Snake Passage/Salvage Part delivery (Bug?)

### ISSUE THREAD

**Issue by Solutar** [WarEmu/WarBugs#9089]
Me and 2 of my Friends just played Snake Passage, and i GUESS we saw a Bug. I captured multiple times the salvage Parts, and everytime at our Cage Wagon was a Knight of the Blazing Sun, when i was close to the Wagon, to deliver the Parts, the Knight kicked me ONCE back, did nothing else, and the Parts just dissappeared on me. I know this has nothing to do with a Timer or something, because i arrived at the Cage Wagon at different times, and they only dissappeared when the Knight kicked me away, when i was Close to the Wagon.
(After that he killed himself by running in the Ship Guards, so i guess he knew what he was doing, gameplay wise or Bug abusing wise.)

Thanks for your time, hope i could help, have a great Day. :)

**Comment by Natherul** [comment]
we do have timers and they can be random inside a predetermined interval. I am unable to replicate so I am going to assume this was a timer.
If it happens again please just open a new ticket
