### ISSUE TITLE
Twisted mob

### ISSUE THREAD

**Issue by Ancrath** [WarEmu/WarBugs#9090]
I was walking through Dragonwake and noticed two "strange" mobs. They are a bit weird. 
Coordinates are about 33 800 and 8 700.
[Screenshot](https://cloud.githubusercontent.com/assets/19807678/22628115/0c424cbe-ebd7-11e6-8e74-d0813f11f794.png)

**Comment by Razielhell** [comment]
Attach files by dragging & dropping, selecting them, or pasting from the clipboard.
