### ISSUE TITLE
White Lion Stance-Trained to Threaten Ability- Lions Roar dosent work

### ISSUE THREAD

**Issue by knickk** [WarEmu/WarBugs#9092]
Ability Lions Roar dosen´t work at the moment
NPC´s dont target the pet and make the same damage (tooltip said 30% less damage for 5 sec from NPC or Players)
tested with npc in chaos wastes
first screen npc auto attack without debuff
![20170206124645_1](https://cloud.githubusercontent.com/assets/25160644/22646194/5cb992b2-ec6b-11e6-86c9-fc814ad9d909.jpg)

second screen same dmg with debuff
![20170206124655_1](https://cloud.githubusercontent.com/assets/25160644/22646213/7804bd26-ec6b-11e6-9e72-0413408153ba.jpg)

**Comment by Luth-RoR** [comment]
The pet ability bar is still not working correctly and shows the wrong tooltip in this case, this should be the correct one:
_Your pet roar, interrupting any currently building abilities and forcing monsters to attack it. While taunted your opponent will take 30% more damage from your pet's attacks. This effect will fade after 5 seconds. _ 

You can also check the debuff tooltip once it is applied to the enemy.
