### ISSUE TITLE
Gates of Ekrund

### ISSUE THREAD

**Issue by SweNinja** [WarEmu/WarBugs#9094]
sorry for my spellings....  =)
As we were taking flag in the middle of the map, cant remember the name of the BO. 
I just dropped through the floor taking 900dmg. I wasnt Punted or so, just felt through as the pic show
please get back to me =)

![sweninja_010](https://cloud.githubusercontent.com/assets/25357451/22655763/7530445a-ec91-11e6-9962-6510d898f1f1.jpg)

SweNinja BG-40
NinjaSwe WE-40

**Comment by Luth-RoR** [comment]
Can't be fixed until client modification is possible.
