### ISSUE TITLE
Defending while disabled (Knockdown)

### ISSUE THREAD

**Issue by Nadril21** [WarEmu/WarBugs#9095]
When the Target is Knocked down, I am constantly getting skills parried. These skills are fired well within the 3 second duration of the KD. From my understanding the character being able to "move" around while knocked down is just a visual bug? Regardless whether they are facing towards or away from me seems to make no difference this happens quite frequently.

This doesn't seem to be specific to any 1 class.

**Comment by Luth-RoR** [comment]
About parry during KD: https://github.com/WarEmu/WarBugs/issues/6839
The "players can turn" issue is just a visual problem on the client, which is known and can't be fixed yet.
