### ISSUE TITLE
Fall damage bug in Stronetroll Crossing

### ISSUE THREAD

**Issue by carmine3161** [WarEmu/WarBugs#9097]
Walking over the branch circled in the picture caused me to fall for 10k damage

![rodryn_001](https://cloud.githubusercontent.com/assets/19709971/22690195/664cba38-ece9-11e6-816e-8e22c8372398.jpg)

**Comment by Luth-RoR** [comment]
I posted this report in https://github.com/WarEmu/WarBugs/issues/8564
