### ISSUE TITLE
Troll Island pq in the Badlands has all mobs as champs

### ISSUE THREAD

**Issue by carmine3161** [WarEmu/WarBugs#9098]
This pq is designed for ranked 22-23, with 2-3 players, yet all the mobs are champs? unsure if this is on purpose or not, seemed fishy
![rodryn_002](https://cloud.githubusercontent.com/assets/19709971/22690293/ff876a9a-ece9-11e6-9d94-d64534e18bbd.jpg)

**Comment by Razielhell** [comment]
#8698
