### ISSUE TITLE
[quest](destru)"foul works"

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#91]
kill from guard not granted , you get only the first defender (NOTE that the quest tracker refer to the single kill "0/1" to the name of the mob, for the 0/10 kill, indeed it talk about general mobs around the tower, it should instead be change to kill 10 total defender=only the mob that show in the name "defender")
![tesq_014](https://cloud.githubusercontent.com/assets/7527415/2925958/be2abe56-d754-11e3-82c2-4fff7d09273a.jpg)

**Comment by Reggaewaldo** [comment]
Closing since we can't currently fix.
