### ISSUE TITLE
Fall damage glitch in Altdorf warquarters

### ISSUE THREAD

**Issue by carmine3161** [WarEmu/WarBugs#9101]
![syebella_001](https://cloud.githubusercontent.com/assets/19709971/22690425/a1d82456-ecea-11e6-81bc-240dfd11adfd.jpg)
![syebella_002](https://cloud.githubusercontent.com/assets/19709971/22690429/a716c454-ecea-11e6-8bef-3aaa3fd7edd3.jpg)

**Comment by Luth-RoR** [comment]
I posted this report in https://github.com/WarEmu/WarBugs/issues/8564
