### ISSUE TITLE
Fabricated Journeyman's Relic Box

### ISSUE THREAD

**Issue by brewzur** [WarEmu/WarBugs#9103]
I seem to have doubled my inventory of relic boxes and I believe it is because of swapping tabs when I'm doing tali making as 4 appeared in craft tab and 4 in reg bags, also I didn't use any up.

Hopefully this makes sense and hasn't been already reported.

**Comment by Kaelang** [comment]
Appreciate this is a dated report - however this does not provide enough information to identify the issue and/or replicate the problem. Please re-open this issue if this persists in the latest version of RoR.
