### ISSUE TITLE
Hollow Graphics

### ISSUE THREAD

**Issue by Pumatouch** [WarEmu/WarBugs#9104]
KV Gromril Junction BO is a great playground. So many possibilities in that area. This one, however, is not supposed to be. It's possible to drop down onto and IN to the train's graphics. The damn thing is a hollow log on wheels! 

[https://youtu.be/crR2haRoVIY](url)

**Comment by Kaelang** [comment]
Appreciate this is a dated report - however this does not provide enough information to identify the issue and/or replicate the problem. Please re-open this issue if this persists in the latest version of RoR.

The video link is no longer live.
