### ISSUE TITLE
Dead/prop NPC aggro

### ISSUE THREAD

**Issue by Blaqwar** [WarEmu/WarBugs#9105]
The dead dragon lying on the ground in Dragonwake at around 10k, 31k can be aggroed with AoE attacks. He can potentially kill people since he hits for 2,5k, I assume he's a hero type. Minor as hell but it's a bug.

![feistydragoncorpse](https://cloud.githubusercontent.com/assets/5108812/22750206/329ad524-ee30-11e6-9060-896568acb498.png)

**Comment by Thayli** [comment]
There's actually 2 spawns of this dragon close to each other with the same issue. Seems like a variable we currently do not know that's set to an incorrect value. Not fixable until we figure that out.
