### ISSUE TITLE
(Some) Enervating Warp Pendant binding on pickup/player

### ISSUE THREAD

**Issue by landgoat** [WarEmu/WarBugs#9106]
Was in TM at Gnoblar's PQ when looted. All of the other enervating jewls are allowed to be mailed/traded and I noticed I could not with this particular one. That is when I noticed the "Bound to player" text when looking at the info/stats of the jewl piece. After asking in advice channel chat if this was normal, it appeared to not be, and I was referred to this Bugtracker to report the bug. 
Hope this helps!

**Comment by Luth-RoR** [comment]
Thanks for reporting; using this report for the issue: https://github.com/WarEmu/WarBugs/issues/9121#issuecomment-279173606
