### ISSUE TITLE
Some NPCs does not respawn when killed during quest progress twice

### ISSUE THREAD

**Issue by orion22cz** [WarEmu/WarBugs#9107]
Two days ago I was doing quest Words of Another (in Ostland), I cannot found NPC "Jorn the Purifier". Today I found him on place where I was looking before (probably server restart fixed it). I killed him, not turned quest and killed him second time. He said some error to the chat. Since that he does not respawn anymore.
![gallardo_001](https://cloud.githubusercontent.com/assets/25650000/22762984/829152ec-ee62-11e6-92e5-c1b5c692a575.jpg)

Same issue is in the quest "Chosen", someone probably killed Bor Graymane twice. More quests are probably affected.

**Comment by Thayli** [comment]
I wasn't able to reproduce this. It seems related to loot drops, in any case. While the quick and dirty fix for such a case would be to remove the loot drops from said NPCs, it might be more interesting to figure what exactly is causing the exception to be thrown. It would require someone with more access than me to investigate.

**Comment by BrutalBeast** [comment]
Found Jorn the Purifier dead again on the ground so this seems not yet fixed.

**Comment by Ryanfawkez** [comment]
He's safe and sound now, closing ticket.

**Comment by VonEpic** [comment]
Didn't know whether to open new ticket for this or not but the "Show on Map" watermark is not active for this quest, and the verbiage of the quest simply states "Ferlangen Forest".
