### ISSUE TITLE
Some Chaos T1 PQ bugs

### ISSUE THREAD

**Issue by AndrewDawnbringer** [WarEmu/WarBugs#9108]
Chaos Chapter 1
Ruinous Powers PQ
- You can click the same gravestone five times and it counts in Stage II.

Chaos Chapter 2
Holmsteinn Revisited PQ
- Ghost chest with effect after PQ ends -> http://imgur.com/c6xsaH0

Chaos Chapter 3
The wilds of war PQ
- Scout dogs animation bugged, they just laying on the ground while attacking in Stage I.

**Comment by Razielhell** [comment]
#5033 You can report here for Ruinous Powers PQ.
#7323 You can report here for Holmsteinn Revisited PQ and also the problem is known(Here #8661)
#7327 You can report here for The wilds of war PQ.

**Comment by Luth-RoR** [comment]
@OP Only bugs in the same report that are related to each other please. Otherwise they can't be closed once , for example, one PQ is fixed.
