### ISSUE TITLE
Magus - Range decrease with Blue Demon's Unholy Empowerment

### ISSUE THREAD

**Issue by Goyfyo** [WarEmu/WarBugs#9109]
Stacks of Unholy Empowerment (which are gained from being close to your summoned demon) from blue horrors reduce range instead of increasing it. Pink meanwhile increases range, and flamer leaves range unaffected.

I've looked around the Experimental forums and some of the recent patches and I've never seen notes that illustrate the range decrease -- leading me to believe it could possibly be an oversight. I could understand it being an intended mechanic so I'm just putting this out there in case it isn't.

![beyblade_000](https://cloud.githubusercontent.com/assets/25676822/22811805/f1643d90-eef5-11e6-93ec-624fa84207ff.jpg)
![beyblade_001](https://cloud.githubusercontent.com/assets/25676822/22811808/f45d26c4-eef5-11e6-8c70-a08f600055f7.jpg)
![beyblade_002](https://cloud.githubusercontent.com/assets/25676822/22811811/f7f086f0-eef5-11e6-9a7c-092f9a211e86.jpg)

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=18792
The experimental forum is a little bit outdated atm (the patchnotes too, but the ranges are like mentioned atm). You can also type .ab changelist into the ingame chat window to see any career specific changes.
