### ISSUE TITLE
Veteran Renown Gear salvageable

### ISSUE THREAD

**Issue by dockmeister** [WarEmu/WarBugs#9113]
Veteran Renown Gear bought from "Dominion Champion/Marshal/Protector" in Altdorf is salvageable.

- This affects at least Robes and Belts for Runepriests for Rank 11-20 and Renown 7-14.
- Jewelry and Weapons were not salvageable
- Renown Gear for other Ranks were not salvageable
- I did not test any other Classes than RP

If you need a complete list of affected items, let me know

**Comment by Luth-RoR** [comment]
Thanks for the info.
