### ISSUE TITLE
T3 24 level SC weapons prices

### ISSUE THREAD

**Issue by Antalor** [WarEmu/WarBugs#9115]
I can't believe that none reported it before. :)
![destro_001](https://cloud.githubusercontent.com/assets/13917674/22836657/9b4ae724-efbd-11e6-94cb-3677589a195a.jpg)
![order_001](https://cloud.githubusercontent.com/assets/13917674/22836661/a1e27c3c-efbd-11e6-9b3d-6bd18b8da47f.jpg)

Greetings!

**Comment by Razielhell** [comment]
Yeah and BW has swords :P I reported it before but Devs told me that they know about it.

**Comment by Blaqwar** [comment]
I don't see the bug. Are you implying that weapons should have career restrictions? Cause that's highly redundant.

**Comment by Antalor** [comment]
And WEs got swords either. :D But the main problem is with this prices. On one side 19 emblems on other 32 emblems. A bit not fair. :)
Greetings.

**Comment by wargrimnir** [comment]
Fixed in next.
