### ISSUE TITLE
sigmar's grace

### ISSUE THREAD

**Issue by lftr** [WarEmu/WarBugs#9116]
sigmar's grace (wp life buff) is bugged in sc score (at the end of sc)
everytime it's cast that count like heal and score like a heal  even when people are full life

**Comment by Luth-RoR** [comment]
It's working as a real heal and this is intended by the devs. I think the "overheal" bug can be fixed once the client can be modified.

**Comment by lftr** [comment]
hello
thank for your answer
but i clearly remenber a similar bug long time ago when only t1 were
avaible
during 1 day or 2 we could overheal full life people and score in sc the
bug was resolute even wthout client control

we can't fix the bug with sigmar's grace by the same way?

2017-02-11 9:18 GMT+01:00 Luth <notifications@github.com>:

**Comment by Luth-RoR** [comment]
The point is that SG didn't heal on WAR, it just raised the healthpoint value. Here it is healing for the same amount, but the client expects it to be differently.
The scenario score bug was happening for every healing ability.

**Comment by lftr** [comment]
so if scenario score bug happened for every healing ability in past and are
now fixed
what SG couldn't be fixed by the way ?
what we need client control ?

2017-02-14 8:48 GMT+01:00 Luth <notifications@github.com>:

**Comment by lftr** [comment]
so if scenario score bug happened for every healing ability in past and are
now fixed
what SG couldn't be fixed by the way ?
what we need client control ?

note: i understood than SG  heal now on ROR i'm not speaking about that
but about the fact you can overheal people  and score in sc

and i'm also worry about the fact you can bypass debuff heal with SG i have
not tested that so don't now if we can do but the way SG now heal make me
doubtful about healdebuff mechanic


2017-02-14 11:30 GMT+01:00 Monty Burns <monty.burns6@gmail.com>:

**Comment by lftr** [comment]
also i noted you closed my bug report
but the bug is still here can you re-open pls?

2017-02-14 11:43 GMT+01:00 Monty Burns <monty.burns6@gmail.com>:

**Comment by Luth-RoR** [comment]
I closed it because
>Luth-RoR added this to the **Client | Issues can not be fixed yet** milestone 3 days ago

Bugs that can't be fixed atm are closed until they can be fixed.
I can't explain you in detail how it will be fixed, because i'm no coder.
Visual/UI issues have also a minor priority.
Any discussions about the balancing of the ability have to take place on the forums.

**Comment by lftr** [comment]
i still didn't understand why overheal bug can't be fixed atm
when it was already be done in t1

but ok
thanks for you answers

2017-02-14 11:53 GMT+01:00 Luth <notifications@github.com>:

**Comment by Luth-RoR** [comment]
>i still didn't understand why overheal bug can't be fixed atm when it was already be done in t1

Because the ability never healed, unlike the other healing abilities; the client doesn't expect it to be a heal and it can't be modified atm.
