### ISSUE TITLE
SW stances - Scout stance abilities won't fire

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#912]
Many scout stance abilities won't fire off after;
loading a sc
zoning
respawning (sometimes)

Acid Arrow
Flame Arrow
Takedown

etc..

thx

**Comment by Elratie** [comment]
mouse leftclick on your char the buffs should show up again

**Comment by ozarmidrashim** [comment]
Elratie's advice is the best solution for this issue at present.

**Comment by Evildoor** [comment]
No longer occurs.
