### ISSUE TITLE
damaged for 2.4k by hellblaster cannon in t1 (nordland)

### ISSUE THREAD

**Issue by RevMalthus** [WarEmu/WarBugs#9120]
this cant be right

hellcannon wiped out like 6 people in one shot

![pancakez_004](https://cloud.githubusercontent.com/assets/4071605/22852586/070061a4-effc-11e6-8d55-e85ee690e65f.jpg)

**Comment by Luth-RoR** [comment]
Happens only when many people are standing very close to each other, which is intended.
