### ISSUE TITLE
Bind on pickup

### ISSUE THREAD

**Issue by Ancrath** [WarEmu/WarBugs#9121]
Is it normal that blue item of different class has "bind on pickup"?
[Screenshot](https://cloud.githubusercontent.com/assets/19807678/22852994/f77d2cac-f051-11e6-8e66-a82928c3ad19.png)

**Comment by Luth-RoR** [comment]
Yes, BoP/BoE is wrongly shown on some items, you can still put it in the vault/trade it via AH.

**Comment by wargrimnir** [comment]
It's actually a side effect of those items being in the ch1 blue/purple bags. They dropped so infrequently, it wasn't thought that it would be an issue. I'll need to amend the drop tables.

**Comment by Luth-RoR** [comment]
Refering to https://github.com/WarEmu/WarBugs/issues/9106

**Comment by Ancrath** [comment]
I can't do those thing with this item. I've checked. Screenshots:
[screenshot I](https://cloud.githubusercontent.com/assets/19807678/22857238/0fdc737c-f0aa-11e6-9fbf-831229e6dd6b.png)
[screenshot II](https://cloud.githubusercontent.com/assets/19807678/22857239/144ce716-f0aa-11e6-8652-3df09ddbc1ed.png)

**Comment by Luth-RoR** [comment]
Yes, i thought it's the same issue as with set boots/gloves, but it isn't.

**Comment by Ancrath** [comment]
One more thing.
"It's actually a side effect of those items being in the ch1 blue/purple bags."
I sure for 80-90% this item dropped not from bag, but mob. If it is important.

**Comment by wargrimnir** [comment]
Yes, we re-used the drop gear. I'm removing the stuff that is currently in bags from the drop tables. There will still be some wrought gear that will drop, but the majority will be from the ch1 PQ and BoP. The rest will be unbound and from drops.
