### ISSUE TITLE
Poisonwing Canyon - Public Quest Dwarf Chapter 22

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9124]
- [ ] Stage 3 Diemonus is untargetable.
![warhammer online age of reckoning 02 11 2017 - 14 16 10 15](https://cloud.githubusercontent.com/assets/16864486/22853784/aa5cb38c-f067-11e6-9e95-2d50a12c2d9f.png)

**Comment by wargrimnir** [comment]
Fixed in next. Stupid figleaf flags..
