### ISSUE TITLE
Dammaz Skar - Public Quest Dwarf Chapter 22 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9125]
- [ ] These lobbers are unkillable and they keep following/attacking you.**Picture1**
- ~~So both PQ icons should be activated.(Based on Wargrimnir's comment below if there are 2 areas for this PQ).**Picture 2 & 3** Client related, leaving it for now.~~
![warhammer online age of reckoning 02 11 2017 - 13 47 20 11](https://cloud.githubusercontent.com/assets/16864486/22853810/35a3f55e-f068-11e6-910d-8dd367787353.png)
![warhammer online age of reckoning 02 11 2017 - 13 58 42 13](https://cloud.githubusercontent.com/assets/16864486/22853811/3810e612-f068-11e6-86a7-6934f9641071.png)
![warhammer online age of reckoning 02 11 2017 - 13 58 43 14](https://cloud.githubusercontent.com/assets/16864486/22853812/38db16f8-f068-11e6-91ba-013ba371ddb3.png)

**Comment by wargrimnir** [comment]
Go across the bridge after stage one. Reading objective descriptions is fun.
