### ISSUE TITLE
Moonfang Stickpointa - Will of the Warboss

### ISSUE THREAD

**Issue by charlysixb86** [WarEmu/WarBugs#9126]
Just can find Moonfang Headhitta's, looks like Stickpointa are missing from spawn points ( i checked Mazadum's video for the right loc ) Will of the Warboss cant be done at this moment.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/8757#issuecomment-269819240

**Comment by ArdzofPT** [comment]
Yes, these mob kills do not count for quest.
![zdra_002](https://cloud.githubusercontent.com/assets/15960258/23823281/0e52c64e-0614-11e7-9178-dde26b36ba9d.jpg)
