### ISSUE TITLE
Gudrim's Veterans - Public Quest Dwarf Chapter 7

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9127]
- [x] There are mobs from Stage 1 in the black circled area but the PQ tracker dissapears there. Need to extend the PQ area. **_Same with #9128_**
![warhammer online age of reckoning 02 11 2017 - 15 25 54 17](https://cloud.githubusercontent.com/assets/16864486/22854347/3195dbdc-f075-11e6-9315-cef28750f83e.png)
![warhammer online age of reckoning 02 11 2017 - 15 34 12 18](https://cloud.githubusercontent.com/assets/16864486/22854325/bef81c7a-f074-11e6-8e04-6f9fb450ffcc.png)

**Comment by saupreusse** [comment]
fixed in next patch

**Comment by Razielhell** [comment]
- [ ] This one is not fixed.

**Comment by grunbag** [comment]
removed the mobs that were outside the p, and spawn more in th pq area

fixed in next patch
