### ISSUE TITLE
Gudrim's Veterans - Public Quest Greenskin Chapter 7

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9128]
- [x] There are mobs from Stage 1 in the black circled area but the PQ tracker dissapears there. Need to extend the PQ area.  **_Same with #9127_**
![warhammer online age of reckoning 02 12 2017 - 00 36 39 28](https://cloud.githubusercontent.com/assets/16864486/22858039/8f32e00a-f0bb-11e6-81ac-78f47ea0ca98.png)
![warhammer online age of reckoning 02 12 2017 - 00 36 41 29](https://cloud.githubusercontent.com/assets/16864486/22858040/8f382a6a-f0bb-11e6-94bc-ce6875dc7d1a.png)

**Comment by saupreusse** [comment]
fixed in next

**Comment by Razielhell** [comment]
This one is not fixed.
