### ISSUE TITLE
Merc/Duelist items not giving tome unlock after equiping. 

### ISSUE THREAD

**Issue by Bamboozeled** [WarEmu/WarBugs#9129]
Recently bought duelist and merc boots/gloves from AH and equiped and no armor unlock in tome. Is this a known issue with sc sets or because I bought off AH? 

EDIT* This isn't in regards to titles as I know they aren't in yet but the set pieces don't even show up in armory.
![bamboozeled_008](https://cloud.githubusercontent.com/assets/25716958/22859927/9512260c-f0bb-11e6-8221-6c06b9af2414.jpg)

**Comment by Luth-RoR** [comment]
Because they didn't exist in original WAR.
