### ISSUE TITLE
Door of Mandred's Hold bugged after Black Orc AoE-Kick

### ISSUE THREAD

**Issue by tutti13** [WarEmu/WarBugs#913]
We were attacking the door at Mandred's Hold, when a Black orc aoe-kicked us from inside through the gate.

The chat then gave out the following message, causing the keep door to be unclickable and unattackable:

"[Keep Door] says: NullReferenceException was thrown. This object will be destroyed."

**Comment by ozarmidrashim** [comment]
This can be caused by pets. I've fixed this just now, and hopefully this issue will stop in the future.
