### ISSUE TITLE
When the Ship Hits the Sand - Public Quest Greenskin Chapter 9

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9131]
- [ ] No engineers so you cant get through Stage 1. 
_**There are suppliers, maybe thats it? Replaced objective to suppliers?**_
![warhammer online age of reckoning 02 12 2017 - 17 45 52 05](https://cloud.githubusercontent.com/assets/16864486/22863555/1fefe450-f14b-11e6-8506-c6210ee97c67.png)

**Comment by Thayli** [comment]
Replaced the suppliers with engineers, they made more sense.
