### ISSUE TITLE
Ironrock Point - Public Quest Greenskin Chapter 9 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9132]
- [x] On Stage 2 there is only 1 Sieger on the coast. 
_~~Checked inside the ship and found 2 more but in there the PQ Tracker dissapears.~~_
- [ ] Also if you die in that area it spawns you in Chapter 5 instead of 9. 
![warhammer online age of reckoning 02 12 2017 - 18 02 02 11](https://cloud.githubusercontent.com/assets/16864486/22863709/1f8cab94-f14e-11e6-9ace-404ecb64e7ea.png)

**Comment by Thayli** [comment]
I've added some more Siegers close to where the first one is, around the barricade, and removed the ones in the ship. The PQ is centered around the offense on the lighthouse, the ship is technically not part of that, so I believe it is not necessary to expand the PQ area. Either way, it can be completed as intended now.

**Comment by Razielhell** [comment]
About respawn area i guess it spawned me there because Chapter 5 healer was closer ? That aint right though.

**Comment by Thayli** [comment]
I spawn in the correct chapter if I die anywhere except on the ship. No idea on how to fix this, though. Will need someone else to take a look at that one.

**Comment by Razielhell** [comment]
Closing for now. Low priority i guess by the time PQ now takes place on the beach.
Thanks Thayli.
