### ISSUE TITLE
[Bolster] dual wield 10% parry bonus affected by bolster

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#9133]
Lvl.2 WH stats. Tested - works in combat.
![bolsterparry](https://cloud.githubusercontent.com/assets/13031465/22864165/333eca80-f187-11e6-855d-46fc51675e91.jpg)

**Comment by Blaqwar** [comment]
That explains so much, I've been seeing abnormal parry rates from low level characters but simply attributed it to bolster giving too much weaponskill or something...
