### ISSUE TITLE
Black Fire Basin Graphical bug

### ISSUE THREAD

**Issue by GeneDauch** [WarEmu/WarBugs#9135]
While doing the Black Fire Basin Scenario, the animation for the flag carrier gets stuck. Showing multiple people potentially having the objective. Nothing Seems to recreate this, it seems to just do it when it feels. Have the played the scenario start to finish with nothing happening. Others where it seems there are 3 people with the objective.

**Comment by Kaelang** [comment]
Appreciate this is a dated report - however this does not provide enough information to identify the issue and/or replicate the problem. Please re-open this issue if this persists in the latest version of RoR.
