### ISSUE TITLE
ToK Unlock Jewelry BUG 

### ISSUE THREAD

**Issue by Enwaaghman** [WarEmu/WarBugs#9136]
The Oathstone of Karak Eight Peaks , this unlock is not working , even if i have the one of each item and when i click nothing happens, there is no unlock and cant buy the jewerly ,the name of the unlock is Gnobblar - Sum of the Whole.

**Comment by Ryanfawkez** [comment]
Do the quest. Get the pocket item. Equip it. ????. Unlock.
