### ISSUE TITLE
Mobs missing nameplates

### ISSUE THREAD

**Issue by d3BugErr** [WarEmu/WarBugs#9139]
Some mobs have no nameplate at all. At least those ones: "Empire Turncoats" at Emp ch3 and "Bloody Sun Choppas" at Dwarf ch2
![bloodychoppanoname](https://cloud.githubusercontent.com/assets/25364850/22922999/cdc7936e-f2b0-11e6-85c3-60c5228b287a.jpg)
![turncoatnoname](https://cloud.githubusercontent.com/assets/25364850/22922998/cdc33116-f2b0-11e6-8c93-187b10daee76.jpg)

**Comment by Ryanfawkez** [comment]
Empire Turncoats can keep their nameplate off, those mobs are supposed to be stealthed. Will enable nameplates for bloody sun boyz though.
