### ISSUE TITLE
Tier 1 Battlefield Objectives

### ISSUE THREAD

**Issue by Topologic** [WarEmu/WarBugs#914]
Today, New Emskrank in Nordland had a lock timer for around 7 hours when I last saw it.  In addition to that, T1 Elf was not spawning NPCs to defend its BOs, and T1 Dwarf was spawning level 25 defenders (except for the boss NPC, which remained at level 15).

**Comment by Soulwhisper** [comment]
This one can close.

**Comment by Soulwhisper** [comment]
Works now. @Luth-RoR
