### ISSUE TITLE
"The Infected" title unlock misplaced

### ISSUE THREAD

**Issue by d3BugErr** [WarEmu/WarBugs#9140]
Killing an "Plagued Farmer" in Troll Country rewards this title though ToK hints about different place and probably not about killing a mob.
![infected](https://cloud.githubusercontent.com/assets/25364850/22923226/9891f576-f2b1-11e6-8504-b31504e653f0.jpg)

**Comment by Luth-RoR** [comment]
http://warhammeronline.wikia.com/wiki/People_Pop_Up
