### ISSUE TITLE
"Echo Hunter" title unlock

### ISSUE THREAD

**Issue by d3BugErr** [WarEmu/WarBugs#9141]
This guy should grand a title "Echo Hunter" if you click on him having that precise item "Bat Wing" in your inventory. 
![alchemist](https://cloud.githubusercontent.com/assets/25364850/22923368/477acdce-f2b2-11e6-8b00-131dce8a4368.jpg)

**Comment by Luth-RoR** [comment]
This type of ToK unlock is not supported yet.

**Comment by Luth-RoR** [comment]
Alternative unlock: https://github.com/WarEmu/WarBugs/issues/5501
http://warhammeronline.wikia.com/wiki/For_Once_it_Isn%27t_Guano
