### ISSUE TITLE
Black Guard; Ability; Brutal Smash; Willpower; Disrupt chanse

### ISSUE THREAD

**Issue by cuga5** [WarEmu/WarBugs#9142]
The increase in willpower using brutal smash does not increase disrupt chance.
![thq_000](https://cloud.githubusercontent.com/assets/25765970/22923782/1434cdd4-f2a3-11e6-89a4-81a5b8cf9ddc.jpg)
![thq_001](https://cloud.githubusercontent.com/assets/25765970/22923783/1435f4e8-f2a3-11e6-9318-1a9fa9a97dca.jpg)

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/9111
