### ISSUE TITLE
Title "The Plaguebearer Hunter" unlock misplaced

### ISSUE THREAD

**Issue by d3BugErr** [WarEmu/WarBugs#9143]
Should unlock via talking to Witch Hunter Adept at Dwarf ch2, but it doesn't. Instead is granted via killing a Forsaken Acolyte in Ulfenwyr PQ, Emp ch4.
![plague1](https://cloud.githubusercontent.com/assets/25364850/22925905/81cc0656-f2bb-11e6-95d2-fdb9f60e9cc6.jpg)
![plague2](https://cloud.githubusercontent.com/assets/25364850/22925906/82045920-f2bb-11e6-9e12-4ccb9b9c84ed.jpg)

**Comment by Ryanfawkez** [comment]
Killing a Forsaken Acolyte is Destro's way of getting the unlock.

**Comment by ArdzofPT** [comment]
Fix Pending removed, but still not able to get the branch in Ekrund?

**Comment by Luth-RoR** [comment]
So, you did: http://warhammeronline.wikia.com/wiki/A_Tale_by_the_Fire

**Comment by ArdzofPT** [comment]
Oh - Tome Titan had that as an NPC hiding in a bush giving you a branch
etc. Unlock works this way.
