### ISSUE TITLE
Scenario party population check.

### ISSUE THREAD

**Issue by Titoos** [WarEmu/WarBugs#915]
First of all, thank you for great SC fix last night, second, It not actually a bug, but rather a suggestion. Take a look a this scenario:
- Party X is full 
- When you click 'join' button in scenario party tab, you are transferred into that party. 
- Even though you get error message "party full", and you are not visible in party frames, you are in that party, get kill contribution, group heals, etc. I think it is also a cause of other problems, like dissapearing frames in example. 
Don't know if thats technically possible, but if you implement party population verification before allowing to join it, not after, it would solve many problems.

**Comment by ozarmidrashim** [comment]
Please post suggestions to the Suggestions and Feedback section of the forum.
