### ISSUE TITLE
Riding a mount without mount

### ISSUE THREAD

**Issue by Ergreen5712** [WarEmu/WarBugs#9151]
When i destroyed mount from inventory during using it mount disappeared - but i still remained mounted
![manufactur_000](https://cloud.githubusercontent.com/assets/25828700/23037581/ee478656-f497-11e6-98a9-678f7289d717.jpg)

**Comment by Razielhell** [comment]
Thats how it used to work on live too afaik. Not a bug.

**Comment by Luth-RoR** [comment]
Yes.
