### ISSUE TITLE
Quests Being Hidden On The Screen After Reload UI/Relog Or Completing The Quest

### ISSUE THREAD

**Issue by Gobbobobbo** [WarEmu/WarBugs#9152]
I don't know what's the problem, maybe new Addons but it's annoying so much. I'm opening my Tome of Knowledge and tick on empty boxes constantly whenever my quests being hidden on the screen. And it happens when I complete my quest too but only the quest that I've completed just hidden. Others keep staying visible.

**Comment by Luth-RoR** [comment]
Please deactivate any quest related addons.

**Comment by Gobbobobbo** [comment]
I don't know which of them are quest related addons. -_-
