### ISSUE TITLE
Can't Take 5 Soldier's Medallion From Herald of Nurgle

### ISSUE THREAD

**Issue by Gobbobobbo** [WarEmu/WarBugs#9153]
When I'm clicking on Complete button I'm getting the error text as "Cannot salvage. Inventory overflowing. Open backpack to remove overflow."

**Comment by Luth-RoR** [comment]
Due to a known bug, you need a main inventory and a crafting inventory with enough room to take rewards from Quest NPCs.
You probably have to wait for a server restart to get rid of that issue and then try it again with enough room in both inventories.

**Comment by Gobbobobbo** [comment]
Okay, thanks. But may I ask why you don't fix it? You can't fix or you just don't? Don't get offend by me, I just asked. Also when server patching that means server resetted too? Thanks for helping. :)
