### ISSUE TITLE
EXP Bar Starts From The Middle of The Renown Bar And Ends Before The Screen End

### ISSUE THREAD

**Issue by Gobbobobbo** [WarEmu/WarBugs#9155]
![adsiz](https://cloud.githubusercontent.com/assets/25829131/23039942/1a97263a-f498-11e6-94f4-405d4450ca62.png)

**Comment by Razielhell** [comment]
wait what? :P ESC>User Settings>Interface>Layout editor.

**Comment by Gobbobobbo** [comment]
That doesn't make it full. That just change it's place.

**Comment by Razielhell** [comment]
It is not suppose to cover horizontally whole screen.

**Comment by Razielhell** [comment]
It is not suppose to cover horizontally whole screen.
