### ISSUE TITLE
Ironbreaker | Ability "Cave in" causes a wrong immunity duration

### ISSUE THREAD

**Issue by Luth-RoR** [WarEmu/WarBugs#9156]
The 40 second immunity duration doesn't fit to the 3 second knockdown duration.

**Comment by Torquemadra** [comment]
thats because its set as a 4s KD... nice Catch luth I amended it for you

**Comment by Luth-RoR** [comment]
Not my discovery: https://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=20026&p=220498#p220489
https://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=20026&p=220498#p220498
I just tested it and created the report because IBs failed to report it since T2.
