### ISSUE TITLE
T4 character login problem + inventory bug

### ISSUE THREAD

**Issue by Rahmirg** [WarEmu/WarBugs#9158]
Started to experience some login problems with only my **T4 characters** as I stated above. After I push the "PLAY" button after around 15 sec there is a blue blink and the server drops the connection with my computer and I have to select Martyrs Square again.
After 3-5 times to try I usually can log in so I wasnt very excited but now this bug acts up when the characters try to travel or use the Book of binding.

Last time I travelled my character arrived with **empty inventory**.

https://postimg.org/image/irw8h7g8x/

As it shows the Book of binding is on cooldown but and my mount is nowhere, as the other stuff.

My username is Blasio.

Ty

**Comment by Luth-RoR** [comment]
The server and login process work fine; that means the problem must be on your side/your connection. 
As the bugtracker is only for bugs and no support i'm closing this (ISP connection support etc is impossible for us anyway).
