### ISSUE TITLE
Removing Buffs from yourself

### ISSUE THREAD

**Issue by Titoos** [WarEmu/WarBugs#916]
We sould be able to remove self/friendly buffs, in particular own/friendly guards by right clicking on its icon under character frame. 
Of course debuffs shouldn't  be removable :)

**Comment by Silentguard** [comment]
AIK you can remove at least self apllied buffs.

**Comment by Evildoor** [comment]
Not all of the self buffs can be removed - i'm pretty sure that WE's Kiss of Agony cannot be.

**Comment by geolyk** [comment]
i checked on my WE none can be removed also on my DoK the same
