### ISSUE TITLE
[Ability] KOTBS - On Your Guard!

### ISSUE THREAD

**Issue by IMRZ** [WarEmu/WarBugs#917]
This ability does not fire when your character blocks or parries.
>[On Your Guard] You order your group to ready their defenses, causing n damage back against any attacker who strikes a groupmate within 150 feet with a melee attack.

Can't remember what it was like on live (has been awhile), so shoot me down if I'm wrong.

Edit: Yes, it does fire after melee damage is taken, but not when you block or parry.

**Comment by Nfkillz** [comment]
you are wrong. it does fire after melee damage.

**Comment by Silentguard** [comment]
Can be confirmed by any kotbs duel video. Triggers only onMeleeDamageTaken. Not triggers when damage absorbed, blocked or parried.

**Comment by ozarmidrashim** [comment]
Closing per Silentguard
