### ISSUE TITLE
Gore Wood - Public Quest Empire Chapter 9 

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#9173]
- [ ] Dying in the PQ respawns you in Chapter 8 instead of 9. All PQs circled, belong in Chapter 9 and should spawn you there accordingly.
![warhammer online age of reckoning 02 18 2017 - 10 57 57 04](https://cloud.githubusercontent.com/assets/16864486/23091941/7f898a24-f5c9-11e6-9843-9473ae53a603.png)

**Comment by boss21** [comment]
I am able to get all three rewards, but the rally master still has the icon above his head, the first reward is invisible, and the second and third rewards are darkened out

**Comment by Kaelang** [comment]
Dying here now respawns you in Chapter 9.
