### ISSUE TITLE
[Quest] "Sanctified Ground" stuck after killing Thomas

### ISSUE THREAD

**Issue by IIxGH0STxII** [WarEmu/WarBugs#9174]
After you kill "Thomas the Champion" in the Grim Monastery in Ostland (59k/50k) you're supposed to "restore the desecrated statue of Sigmar through fervent prayer". Although the item that you're supposed to use (a big flame symbol at the bottom of the Sigmar statue labelled "Desecrated Monastery") is there, you can't actually use it and therefore can't turn in the quest. 
This is the object that's supposed to finish the quest:
![alathorn_005](https://cloud.githubusercontent.com/assets/25819236/23091939/146c3870-f5c1-11e6-9908-29703c60d49d.jpg)

**Comment by Luth-RoR** [comment]
Copied to https://github.com/WarEmu/WarBugs/issues/6189
