### ISSUE TITLE
Howling Vale - Public Quest Empire Chapter 9

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9175]
- [ ] This guy is 36 Level.
![warhammer online age of reckoning 02 18 2017 - 11 07 27 05](https://cloud.githubusercontent.com/assets/16864486/23092121/a4d0eacc-f5cc-11e6-8191-a8be7507bafe.png)
- [ ] Bray Karkaris is missing so cant get through Stage 3.

**Comment by Razielhell** [comment]
Ehhh there is another one #6038 @Luth-RoR

**Comment by Thayli** [comment]
Both problems fixed.
