### ISSUE TITLE
Nurenmir's Lancers - Public Quest Empire Chapter 8 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9176]
**PQ is for RANKS 16-17.**
- [x] 3 Heroes? And 17-18-20 Levels...xD 
![warhammer online age of reckoning 02 18 2017 - 12 07 26 07](https://cloud.githubusercontent.com/assets/16864486/23092422/fd2e8a52-f5d2-11e6-93e2-dda89702481f.png)
![warhammer online age of reckoning 02 18 2017 - 12 07 27 08](https://cloud.githubusercontent.com/assets/16864486/23092423/fd351eb2-f5d2-11e6-9b58-ba0836d7a8a3.png)
![warhammer online age of reckoning 02 18 2017 - 12 07 29 09](https://cloud.githubusercontent.com/assets/16864486/23092424/fd38924a-f5d2-11e6-9064-cc39c852dfc6.png)

**Comment by Thayli** [comment]
Adjusted the hero, who was indeed a level too high. Keep in mind that the NPC spawns don't always seem to respect the limits in the database, though. Some NPCs are level 17 on paper yet spawn as 18 randomly.

**Comment by Razielhell** [comment]
yeah i know that from Dana :)
