### ISSUE TITLE
PQ T2 CH9 Greenskins

### ISSUE THREAD

**Issue by Teefz** [WarEmu/WarBugs#9177]
Did a small PQ hunt with guildies:

'When the Ship Hits the Sand'

Engineers are missing on stage 1. 

'Ironrock' & 'Longdrong'

Both PQs work. Only issue I can imagine is that this PQ will be hell on earth for lowbie group as the mobs do not respect los on the boats. I know this cannot be fixed at the moment, but just wanted it make it known.

**Comment by Razielhell** [comment]
When the Ship Hits the Sand works fine, just did it. 
I dont understand which is the other one. If you are talking about Ironrock Point then its here #9132 and Thayli fixed Siegers(Only respawn issue left which must be done manually i guess)

**Comment by Luth-RoR** [comment]
NPC LoS issue is well known.
