### ISSUE TITLE
Agymah's Lair - Public Quest Dwarf Chapter 9 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9178]
- [x] Too many Tomb Sworns in the cave. Only a few Warriors and it doesnt count them for Stage 1.
- [x] Also PQ Tracker is a mess in there...disappears randomly.

**Comment by Thayli** [comment]
This PQ is a bit of a mess. I could fix the spawns but it wouldn't make much sense when the PQ area is all over the place. It makes it pretty hard to test, as well. I'll need someone to fix that first, then I can take a look at fixing the spawns.

**Comment by saupreusse** [comment]
fixed the tracker

**Comment by grunbag** [comment]
fixed in next patch
