### ISSUE TITLE
BW starter boots as appearance

### ISSUE THREAD

**Issue by GloomySam** [WarEmu/WarBugs#9189]
BW start bootsies (Ragged Peasant Boots) cannot be used as appearance.
That's no bug, ofc, but a very kind and handsome DB Dev told me that could be changed, so i'm posting it here.

**Comment by Ryanfawkez** [comment]
All Empire classes start with Ragged Peasant Boots. Would have to make individual shoes for each class to make them usable for appearance. Would prefer to initiate a work-around through the Cosmetic Fanatic vendor.
