### ISSUE TITLE
Catapult near of PQ of ruin in Black Crag

### ISSUE THREAD

**Issue by Magteridon** [WarEmu/WarBugs#9190]
![wazzdakka_056](https://cloud.githubusercontent.com/assets/16975012/23101772/da67eeb8-f69b-11e6-8826-729f38e4f738.jpg)

**Comment by Razielhell** [comment]
#7427

**Comment by Luth-RoR** [comment]
Is the catapult part of the PQ and needs to be placed closer or just completely wrong at this place?

**Comment by Magteridon** [comment]
is up of mountain  near no have nothing for used this catapult

**Comment by Luth-RoR** [comment]
Must be removed then, thanks.

**Comment by Magteridon** [comment]
![wazzdakka_064](https://cloud.githubusercontent.com/assets/16975012/23102586/046cd0a6-f6ac-11e6-80ed-7581c2d7176b.jpg)

**Comment by Ryanfawkez** [comment]
It's been there since live. I think it used to catapult players down to the PQ, as per Greenskin start area that had teleport catapults for Ironmane's Lock.
