### ISSUE TITLE
This unlock no work in Black crag too  near of Warcamp

### ISSUE THREAD

**Issue by Magteridon** [WarEmu/WarBugs#9191]
![wazzdakka_055](https://cloud.githubusercontent.com/assets/16975012/23101778/f30496b0-f69b-11e6-8f13-cfe0d325f092.jpg)

**Comment by Luth-RoR** [comment]
>This unlock no work

I don't understand what the problem is here. What's meant with "the unlock"?

**Comment by Ryanfawkez** [comment]
I actually added a custom unlock there, but I cannot remember for the life of me which one it was...
