### ISSUE TITLE
Npc "Gibbitz" is only lvl 1 in Black Crag 

### ISSUE THREAD

**Issue by Magteridon** [WarEmu/WarBugs#9192]
![wazzdakka_054](https://cloud.githubusercontent.com/assets/16975012/23101787/288f8538-f69c-11e6-8058-ef1d393e8ced.jpg)

**Comment by Ryanfawkez** [comment]
As far as I can tell, he's a craft supply NPC. Going by the fact other craft supply NPCs are level 40, will change it accordingly.
