### ISSUE TITLE
Supplies in t4

### ISSUE THREAD

**Issue by Runnistik** [WarEmu/WarBugs#9193]
I took the resources and they bug me! I can take them indefinitely( it's been 6 minutes and I did not lose! Please fix this bug

**Comment by Runnistik** [comment]
Thus it is possible to get infinite experience RVR and medals!

**Comment by LestiArdisson** [comment]
Not a GM here: 
But be advised that this happens sometimes. And if a player likes to hand over the ressources several times he will get a ban or worse.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/8316
