### ISSUE TITLE
Player induced pet CC abilties don't fade after successful avoidance check on the enemy

### ISSUE THREAD

**Issue by cimator** [WarEmu/WarBugs#9194]
Squig's disarm doesnt fade even when the target dodges it, so it keeps trying to disarm until he no longer dodge, making it simply unpreventable. Here is the video proof for it, tried it with WL's %100 dodge morale; https://youtu.be/PmSj1dkVZHk , couldnt upload it here for the size sorry about that :P

**Comment by Luth-RoR** [comment]
Reported to be the same with other player induced pet CC, for instance WL knockdown.
