### ISSUE TITLE
Bog Hunters PQ in Troll Country Bug.

### ISSUE THREAD

**Issue by Svatyr** [WarEmu/WarBugs#9196]
So my lil shaman Greenskaar and a few of his friends were doing a PQ, and the final stage did not work out as we thought it would. The boss did not appear and as a consequence would could not complete the PQ, The rest of it works fine. It's just the final stage boss does not show up which means we have to sit through a five minute timer, and then sit through he re-spawn timer.

this would not be an issue But the Ragash's last stand re-spawn timer is Bugged, so we cant do that one either and all we are doing is working our way a crossed the map. If you could please find out whats going on, and fix it Id very much appreciate it <3.

**Comment by Razielhell** [comment]
#7349
