### ISSUE TITLE
Brigand's whipsash

### ISSUE THREAD

**Issue by brewzur** [WarEmu/WarBugs#9198]
+24 wounds 
+137 spirit. resist.
+60 ele. resist.
**+2% parry**
rank: 31
career: magus

I don't think a magus needs parry

**Comment by Ryanfawkez** [comment]
...Why not?

**Comment by Ryanfawkez** [comment]
Aight, judging by the database, the 2% parry should be +4 morale regen in accordance with the Sorc/BW belts, which have morale regen as well. Engi/SW/SH belts come with 2% dodge.
