### ISSUE TITLE
using mounts while debolstered

### ISSUE THREAD

**Issue by pigbearman202** [WarEmu/WarBugs#9199]
While debolstering in t1 if you mount before going into a zone you will stay on your mount, both lvl 16 mount and 38 armored, while mounted and after running into water it can be very deceiving with how fast you are running and can be abused

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/8530#issuecomment-264653432
https://github.com/WarEmu/WarBugs/issues/798
