### ISSUE TITLE
[quest](destru)"the eager"

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#92]
When complete and select the rewad it give you nothing, ( i selected the axe)
![tesq_015](https://cloud.githubusercontent.com/assets/7527415/2925985/488e98ec-d755-11e3-9e9c-28afdefad6ef.jpg)

**Comment by Reggaewaldo** [comment]
Tested OK.

Closing.

**Comment by Ryanfawkez** [comment]
Fixed in next patch.
