### ISSUE TITLE
Tomb of the fallen Slayer Lair

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9201]
**_Ahhh...not sure about this one._**
- Not working or not implemented yet? Dunno. Just reporting it.
![warhammer online age of reckoning 02 20 2017 - 22 03 13 25](https://cloud.githubusercontent.com/assets/16864486/23140112/75847c6e-f7b8-11e6-9b64-dc9959c335ef.png)
![warhammer online age of reckoning 02 20 2017 - 22 03 14 26](https://cloud.githubusercontent.com/assets/16864486/23140113/758a4fae-f7b8-11e6-9092-25acc08af3f0.png)

**Comment by Razielhell** [comment]
@Luth-RoR Its a lair...not a PQ xD PQ tracker just stuck as usual.

**Comment by Luth-RoR** [comment]
Oh, lel.

**Comment by Razielhell** [comment]
A Dev should enlighten us about this Lair though.

**Comment by Luth-RoR** [comment]
According to DB devs, the boss is not in the DB yet.
