### ISSUE TITLE
Burnbeard's Oath - Public Quest Greenskin Chapter 20

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9202]
- [x] Cant do ~~Gyrocopter~~ and Statue on Stage 2
![warhammer online age of reckoning 02 20 2017 - 21 41 16 24](https://cloud.githubusercontent.com/assets/16864486/23140158/b9f54f40-f7b8-11e6-8747-6fc2634d305b.png)

**Comment by grunbag** [comment]
Fixed on next patch

**Comment by grunbag** [comment]
no you didn't removed it !

fixed in next patch
