### ISSUE TITLE
House of Cards - Public Quest Dark Elf Chapter 14 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9203]
- [x] On Stage 1 Havocbows attack Annigilators and kill them.
![warhammer online age of reckoning 02 20 2017 - 20 27 29 09](https://cloud.githubusercontent.com/assets/16864486/23140425/3c1818ee-f7ba-11e6-9f1e-8a9103a996d6.png)
- [x] Stage 2 doesnt spawn Black Lords.
![warhammer online age of reckoning 02 20 2017 - 20 31 09 10](https://cloud.githubusercontent.com/assets/16864486/23140446/53221d32-f7ba-11e6-882c-1b9fa3dd6a05.png)

**Comment by grunbag** [comment]
fixed on next patch

**Comment by Razielhell** [comment]
- [ ] Black Lords are suppose to be hostile and not friendly on Stage 2.
![warhammer online age of reckoning 06 10 2017 - 12 22 50 02](https://user-images.githubusercontent.com/16864486/27001627-95a98118-4dd7-11e7-808d-9fc34fde7e71.png)

**Comment by grunbag** [comment]
Fixed in next patch
