### ISSUE TITLE
The Storm is Coming - Public Quest Chaos Chapter 15 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9204]
- [ ] These "things" are all over the place in this PQ.
![warhammer online age of reckoning 02 20 2017 - 21 30 11 21](https://cloud.githubusercontent.com/assets/16864486/23141729/e5b7ad8c-f7c0-11e6-8255-6dfbe3a30270.png)
![warhammer online age of reckoning 02 20 2017 - 21 28 49 20](https://cloud.githubusercontent.com/assets/16864486/23141730/e5bae038-f7c0-11e6-9ed4-1ab9ebfed6fd.png)

**Comment by grunbag** [comment]
Fixed on next patch
