### ISSUE TITLE
[Engi\Magus] Dots tick dont break stagger

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#921]

**Comment by ozarmidrashim** [comment]
That sounds like it would make stagger practically useless. It was definitely like this?

**Comment by Silentguard** [comment]
True. After stagger nerf from 9 to 3 sec it becomes almost unusable. Otherwise 3 seconds of strong stagger makes it op when you get huge pack of dots and easily can die staggered. Two engies with M2 enough for this. Compromise could be fragile stagger with 5 sec duration.

**Comment by ozarmidrashim** [comment]
I'd make a thread about this on the forum.

**Comment by ozarmidrashim** [comment]
Fixed, but could use discussion.
