### ISSUE TITLE
Cost of one 16 level mount.

### ISSUE THREAD

**Issue by Antalor** [WarEmu/WarBugs#9213]
Today I saw this on one of the vendors in TC WC. 
All 3 have same 50% speed and same 75% chance to dismount on hit.
Is that a bug ?
![001](https://cloud.githubusercontent.com/assets/13917674/23180526/ff3250ee-f871-11e6-9aee-1d895cdf6b6e.jpg)

**Comment by IIxGH0STxII** [comment]
https://github.com/WarEmu/WarBugs/issues/9195

**Comment by Antalor** [comment]
Good that someone already reported it.
