### ISSUE TITLE
Black Guard - Ruin Set - 5pc Bonus

### ISSUE THREAD

**Issue by marsares666** [WarEmu/WarBugs#9214]
In order to get the 5-pc bonus for the T4 Ruin set for the Black Guard, you require "Dark Greaves of Ruin".

However, you can only purchase "Greaves of Ruin" and therefore the full Ruin set does not provide the 5pc bonus of "+5% Block".

**Comment by Ryanfawkez** [comment]
https://github.com/WarEmu/WarBugs/issues/9172
