### ISSUE TITLE
[Quest] Inevitable Power

### ISSUE THREAD

**Issue by Ademai** [WarEmu/WarBugs#9215]
I've come across a stage in the T3 Epic quest chain for dark elves that doesn't work as it should. The quest item I'm to use and the mob I'm to kill is just destribed with Invalid Object id or Invalid Creature id. I'm not sure if I'm supposed to interact with a quest item, or a world object, but I think it's safe to say it doesn't exist.

I've had this quest at this stage for 3-4 days as of Feb 22. And accordingly to /advice, it shouldn't be a problem, and at least one other person have managed to complete the chain in the last 24 hours. I have tried abandoning the quest, relogging, and picking it up again. But Lycithas the Harridan Seer keeps offering me the same quest with the same details and information. Nothing changes.

Attached are screenshots from the Monolith in Inevitable City where the quest strands me.

![malesin_010](https://cloud.githubusercontent.com/assets/10104679/23192778/8fcaad30-f8a5-11e6-99fa-6be52a8b2612.jpg)
![malesin_008](https://cloud.githubusercontent.com/assets/10104679/23192722/5010dde0-f8a5-11e6-9ec9-f6c17db9e2e0.jpg)

**Comment by Torquemadra** [comment]
thats a quest thats past where I ended the quest line, you shouldnt have it, is that an old character?

**Comment by Ademai** [comment]
The character is max 2-3 months old. And I picked up the quest about a week ago, perhaps a bit more.

**Comment by Torquemadra** [comment]
thanks
