### ISSUE TITLE
Champion "Backhand Karl" (15) is triple cloned

### ISSUE THREAD

**Issue by d3BugErr** [WarEmu/WarBugs#9218]
This one guy got three bros around bandit camp in Emp ch7.
![clonedchampoinemp1](https://cloud.githubusercontent.com/assets/25364850/23214182/c95a3ca4-f91e-11e6-838d-5c40c89303a7.jpg)
![clonedchampoinemp2](https://cloud.githubusercontent.com/assets/25364850/23214183/c9793c9e-f91e-11e6-926d-901a8ead498a.jpg)

**Comment by wargrimnir** [comment]
Fixed in next.
