### ISSUE TITLE
Guard Swap bug

### ISSUE THREAD

**Issue by Daniellita** [WarEmu/WarBugs#9220]
Sometimes when any tank class tries to remove and reapply guard, the ability doesn't go off. This has been a consistent problem experienced by multiple people:

https://www.returnofreckoning.com/forum/viewtopic.php?f=66&t=20101&p=221653#p221653

It is unlikely this is a latency issue, because other abilities are working correctly; it doesn't happen that we press a heal and that spell doesn't trigger. The issue seems to be unique to guard.

I am not exactly sure what is causing this problem so if someone has a better idea of how the bug works, please contribute to the discussion.

**Comment by Ryanfawkez** [comment]
Well you cannot remove a heal from somebody when you press the same ability again. Guard does this, and thus the handling has some delay. When you guardswap you don't select your guarded target and then select the unguarded one, no; you press Guard once to remove the effect from your guarded group member without targeting them, and then press it again to apply it to your selected target. I'm not sure how much different it is to live seeing as I didn't play a tank back then, but for RoR the issue is common and I'm not sure if it's fixable. Would need more clearance from a core dev.

**Comment by Luth-RoR** [comment]
From my post there: https://www.returnofreckoning.com/forum/viewtopic.php?f=66&t=20101&p=221732#p221732
>EBG had sometimes the same issue as described in the OP on WAR. I don't have issues with guard swapping; it would be nice if somewith deactivated EBG addon can confirm that he has the same problem.
There could be also another issue with EBG, e.g. it doesn't check 100% correctly if guard is applied, player hammers the key too frequently -> guard is taken away again.

**Comment by Luth-RoR** [comment]
Seems to happen with many players, with or without the addon.

**Comment by Daniellita** [comment]
> When you guardswap you don't select your guarded target and then select the unguarded one, no; you press Guard once to remove the effect from your guarded group member without targeting them, and then press it again to apply it to your selected target that needs the guard. I'm not sure how much different it is to live seeing as I didn't play a tank back then, but for RoR the issue is common and I'm not sure if it's fixable. Would need more clearance from a core dev on whether it's latency or internal ability handling

So theoretically speaking the same error could be occuring with RP Rune of Breaking and Zealot alternative since they work in a turn on/turn off manner without a GCD? Just going on a limb here following your logic and trying to think about the mechanic behind the problem.

**Comment by Ryanfawkez** [comment]
I tend to notice a tiny freeze at times whenever a Runie applies their buff to me; I'm not sure if they suffer from the same thing, Same thing when swapping parties.

**Comment by Luth-RoR** [comment]
I think the tiny freeze comes from the increased stat calculation off the RP buff with bolster involved.

**Comment by Halhammer** [comment]
>  I'm not sure how much different it is to live seeing as I didn't play a tank back then, but for RoR the issue is common and I'm not sure if it's fixable.

On live you'd just select the new guard target and hit guard, so it removed guard from the old target, one click.

**Comment by Tesq** [comment]
Was like halhammer said in ror too till It got changed to had a delay in ror if not mistake because the swap guard was istantly and didn't invoke a CD back then or something like that

**Comment by Kaelang** [comment]
This should now be fixed.
