### ISSUE TITLE
Can pass  for Fix zone  and enter in castle of order in TM

### ISSUE THREAD

**Issue by Magteridon** [WarEmu/WarBugs#9221]
This previous error is fixed, but it can continue entering the castle without some difficulty some
![wazzdakka_068](https://cloud.githubusercontent.com/assets/16975012/23250045/a6ad2034-f9a7-11e6-9b6c-769f0a1346cd.jpg)
Can enter for here --->
![wazzdakka_069](https://cloud.githubusercontent.com/assets/16975012/23250044/a6acd26e-f9a7-11e6-8505-b20fac226741.jpg)
![wazzdakka_070](https://cloud.githubusercontent.com/assets/16975012/23250046/a6b1852a-f9a7-11e6-94f7-6902c880a02b.jpg)

**Comment by saupreusse** [comment]
fixed
