### ISSUE TITLE
WB crash in RvR

### ISSUE THREAD

**Issue by Gandam01** [WarEmu/WarBugs#9222]
I can't find a post saying why we have mass disconnects in war bands during ennemy sieges. The fact is that these crashes always occur when a player tries to join a wb from the capital city. 

Say you are in Thunder mountain with your wb, and a new player joins the open wb from the capital, then a lot, if not all players from the wb are instantly disconnected. 

Now, a lot of people know this and will be able to confirm, and it seems that some people have decided to use this to get an advantage during keep sieges. How to get ride of ennemy forces during a siege, just log on to the other side, go to the capital, and join the open wb, then just reconnect and take the keep !

I'm not 100% sure that this is the only time that mass crashes happen, but it's one of them at least. And if that isn't a major bug, then i don't know what is.

Thx for your help and hard work on this great game.

**Comment by Luth-RoR** [comment]
This particular problem is a known issue, though the root of the problem is still unknown. Here we already got open RvR logs: https://github.com/WarEmu/WarBugs/issues/4898#issuecomment-205963239
