### ISSUE TITLE
Offhand AA randomly not hit on its normal timing

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#9223]
Got this issue on every dual wield char.

Just in case.
https://youtu.be/SzaJHvEnLfI?t=41s

**Comment by Blaqwar** [comment]
In WAR offhand swings are considered procs with a 50% proc chance (afaik). Therefore the swings won't necessarily be regular since it's a chance based system that ends up contributing the 50% offhand damage.
