### ISSUE TITLE
PQ Loot Bags empty except for crafting materials

### ISSUE THREAD

**Issue by ChristerGustavsson** [WarEmu/WarBugs#9226]
Something that has happened lately, on more than one of my characters, is that I get essentially nothing in PQ loot bags. I can only pick crafting material. This seems to be for anything but Massive loot bags that thankfully still contain set items.

I thought it was just a fluke the first few times but this has become a recurring theme now that's just really annoying. I'm attaching some screenshots to highlight that there's practially nothing inside the a Major loot bag I received from a PQ in Empire Chapter 6.

![cruril_000](https://cloud.githubusercontent.com/assets/894998/23274987/00bf4afe-fa05-11e6-9b30-f199797edc93.jpg)
![cruril_001](https://cloud.githubusercontent.com/assets/894998/23274988/00c2050a-fa05-11e6-8f74-16a4e4cb8b25.jpg)
![cruril_002](https://cloud.githubusercontent.com/assets/894998/23274986/00bb2884-fa05-11e6-827b-d7a330b60357.jpg)

**Comment by Razielhell** [comment]
Items not added yet in bags for higher Chapters.

**Comment by ChristerGustavsson** [comment]
Ah, I see. Well I suppose crafting materials is better than nothing. Thanks for the quick reply.
