### ISSUE TITLE
Movement Buttons Doesn't Work When I Manage Them As The Ability Buttons

### ISSUE THREAD

**Issue by SymbioteWolverine** [WarEmu/WarBugs#9227]
So I'm using some movement buttons like QE but not even the RTYU works sometimes. When I use Default settings then change them back it works but then it being bugged again. See how it's annoying?

Edit: Restarting the game fixes this issue. But iirc relog without close the game wasn't fixing that. I'm not sure about that though.

**Comment by Blaqwar** [comment]
Are you running the game windowed? Do the hotkeys sometimes work but sometimes they don't? Make sure you're not pressing any modifier keys (Shift, Ctrl, Alt) when you're loading into the game from the char select.

**Comment by Luth-RoR** [comment]
That's high likely a client issue.
