### ISSUE TITLE
Can't get the "Bloodmaw Gnoblar's Nose" from "Bloodmaw Gnoblar"

### ISSUE THREAD

**Issue by shinwiki** [WarEmu/WarBugs#9228]
Can't get the "Bloodmaw Gnoblar's Nose" from "Bloodmaw Gnoblar" for the "Oathstone of Karak Eight Peaks" unlock, seems bugged

**Comment by Ryanfawkez** [comment]
Be sure you get the quest first.

**Comment by shinwiki** [comment]
I got  Quest "Gnoblar Huntin'" you bet.
with that in mind, reported. please confirm.
