### ISSUE TITLE
[BW] Rank 4 Morale Removes Itself.

### ISSUE THREAD

**Issue by NerrawMS** [WarEmu/WarBugs#9229]
I do not know if this issue has been mentioned before, I did do a search of the Bugtracker and did not manage to find it. Apologies in advance if I have missed it.

Basically, I am a BW who has spent all of my available mastery points in the Incineration tree, up to and including the rank 4 morale ability 'The Burning Head'.

It may also be important to mention that I am equipped with full Ruin gear, as I believe this may be related to the issue (Note: the 4 piece BW set bonus for ruin gives a mastery point in the incineration tree).

The bug is, whenever I UNEQUIP my 'Dreadfire' staff (Empire epic reward) I receive a pop up message indicating that I have gained a specialization point, and The Burning Head is subsequently refunded and removed.

Again, if I have missed that this issue has been flagged up on a previous occasion, I apologise unreservedly. Additionally, as I am not terribly experienced with the game to such a level of understanding if this is intentional for any reason, I do hope that you can forgive my unintentional ignorance. If requested I could do some more testing with different weapons/armour sets and trees.

Regards and Thankyou,

Warren.

**Comment by Luth-RoR** [comment]
That's a known issue that can't be fixed atm unfortunately: if a set gives you an additional mastery point, it will be removed if you change any item; you can assign the mastery point again from anywhere, if you instal the addon "anywheretrainer".
https://github.com/WarEmu/WarBugs/issues/7024
