### ISSUE TITLE
[Engineer] Fragmentation grenade wrong damage type

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#923]
Ability deal corporeal damage instead of physical. Also have some issues with near zero mitigation. Also ability have no LOS check onCastEnd.

**Comment by ozarmidrashim** [comment]
Damagetype fixed.

**Comment by Silentguard** [comment]
Looks like it ignore toughness.
![engi grenade bug](https://cloud.githubusercontent.com/assets/13031465/8586798/a6773e76-2625-11e5-8759-e91044da90e2.png)

**Comment by ozarmidrashim** [comment]
Checked it and it isn't.
