### ISSUE TITLE
KV Beastlord Lair 

### ISSUE THREAD

**Issue by naytendox** [WarEmu/WarBugs#9231]
There is a spot in this lair that takes you out of RvR it looks like. Maybe this could be used for a group to fight the lair boss while the opposite faction could not attack them.
![vegapunk_034](https://cloud.githubusercontent.com/assets/26011479/23315826/ef424812-fa95-11e6-9d42-34ef4b6adbae.jpg)

**Comment by naytendox** [comment]
Upon further testing, if I log out and log back in, in this spot it unflags me for RvR and it is in range to pull boss.

**Comment by wargrimnir** [comment]
Hotfixed already.

**Comment by naytendox** [comment]
Does this qualify for a Bug Report Token? @wargrimnir
