### ISSUE TITLE
Game breaking bug

### ISSUE THREAD

**Issue by FearTheGriff** [WarEmu/WarBugs#9232]
medallion is spelt wrong ? 
![e](https://cloud.githubusercontent.com/assets/16886300/23318307/b97eb0e2-fac9-11e6-8310-824cd20c9209.PNG)

**Comment by Luth-RoR** [comment]
All dev resources will be re-routed to this issue asap. 😛

**Comment by Ryanfawkez** [comment]
It's been bothering the fuck outta me since I saw it...
