### ISSUE TITLE
Uthorin Siege Camp BO

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9235]
- [ ] It was under assault and wanted us to **Claim** it. Killed all Destro guards, had 20 seconds left before it was secured for Destro but this message showed up to everyone that tried to interact with the flag.
![razielhell_000](https://cloud.githubusercontent.com/assets/16864486/23335998/b34fb610-fbca-11e6-8bd6-f3e531141491.jpg)

**Comment by Luth-RoR** [comment]
From https://github.com/WarEmu/WarBugs/issues/9802
>The two guards next to the wagons (south of the three next to the flag) do not count towards taking the BO. You can take the BO without killing them.

**Comment by Razielhell** [comment]
Same issue diferrent BO.
![warhammer online age of reckoning 06 25 2017 - 11 55 25 03](https://user-images.githubusercontent.com/16864486/27514804-9290da9a-599d-11e7-8072-8b9f7a3119ea.png)

**Comment by sioding** [comment]
Since we have no guards at the BO anymore i will close this now. Thanks for the report
