### ISSUE TITLE
[Shaman] QE + RUN AWAY! dont stack

### ISSUE THREAD

**Issue by MKorin** [WarEmu/WarBugs#9237]
as it was on live

**Comment by Silentguard** [comment]
Every speed proc on live was stackable (not sure about charge). Played am with QE+Odjira long time till QE onCast breakable was fixed.

**Comment by Luth-RoR** [comment]
Yes, that's known; waiting for dev confirmation, because it is high likely intended on RoR.

**Comment by Torquemadra** [comment]
confirmed
