### ISSUE TITLE
DoK Career Tactic Bound by Blood

### ISSUE THREAD

**Issue by ShoxRethgor** [WarEmu/WarBugs#9239]
DoK Career Tactic Bound By Blood does not ever proc the Self healing aspect of the tactic.
Using the Consequence Chalice and the 10% Proc chance for increased Elemental resistance shown on multiple allies throughout testing. Never observed Bound By Blood returning any healing despite stating its a 25% proc chance. Would like to be able to test in a more controlled situation other then mob farming with my buddy, and not sure how to post Combat log test of my healing.(not sure if that could help either).

**Comment by ShoxRethgor** [comment]
After Latest Build Bound By Blood is working correctly

**Comment by Tesq** [comment]
It work corretly, the value is added directly to the used heal and not show alone in combat log

**Comment by ShoxRethgor** [comment]
Yes I noticed after using the tactic in a leased controlled but actual
situation in a SC. The proc will never show for overhealing but only for
actual healing done. It only factors what was healed not the full amount of
the healing done. So when first looking at it in IC it would appear to
never go off. Thanks for looking into it, but it is totally working as
intended. Sorry for ticket looking back I should have know it wouldn't
factor overheal.
