### ISSUE TITLE
Keeps kill quests

### ISSUE THREAD

**Issue by ghost** [WarEmu/WarBugs#9240]
- [ ] When you complete it it says abandoned instead of Completed.
**_Both chat and middle screen messsage._**
![warhammer online age of reckoning 02 27 2017 - 00 29 16 14](https://cloud.githubusercontent.com/assets/16864486/23344372/ef1c1e7c-fc83-11e6-9e52-6e212ed425d4.png)

**Comment by Lheana** [comment]
#4846
