### ISSUE TITLE
Infinite resources drop

### ISSUE THREAD

**Issue by santa85** [WarEmu/WarBugs#9241]
User can infinite use "Resource Drop" place and obtain medalions, exp, rr from this action.
Red light over player will be never ending (after zone lock too).

Reproduced on characters Bubbabubba (T3 emp) and Subbasubba (T4 Praag, Feb 27, ~8:30 UTC).
Steps to reproduce:
1. Player must be WB leader
1. Player must invite other player who bring resources to WB
1. Other player must reject invitation

![subbasubba_007](https://cloud.githubusercontent.com/assets/26056969/23354445/e8f98b1e-fcd9-11e6-919d-f570a16dd47c.jpg)
![subbasubba_008](https://cloud.githubusercontent.com/assets/26056969/23354446/eb623892-fcd9-11e6-9ef0-f63d77443783.jpg)

**Comment by Luth-RoR** [comment]
As described, it couldn't be replicated by the devs.
