### ISSUE TITLE
Quest "On the Brink of Chaos" Emp ch15

### ISSUE THREAD

**Issue by d3BugErr** [WarEmu/WarBugs#9242]
Not sure I should've open a ticket. But whatever.
This quest as seen here http://ironbreaker.tumblr.com/post/28551909839/on-the-brink-of-chaos
should be quite lengthy and end up with lvl28 blue wep. But it is just two or three steps ending abruptly.
Is there a possibility of reconstructing at least part of it? Or the wep rewards?

**Comment by Luth-RoR** [comment]
High likely not implemented yet.

**Comment by wargrimnir** [comment]
Fixed in next, probably.
