### ISSUE TITLE
Zone rolls when locking

### ISSUE THREAD

**Issue by Waaghaa** [WarEmu/WarBugs#9243]
Wonder if you could take a look at the mechanics for rolls when you lock a zone?

When is it determined that a character is eligable for the loot roll?

I have 3 different characters, SH, Sorc & Magus, the SH & Sorc I played for 5-10 min in Black Crag, the Magus for 2½hrs, all 3 characters recieved rr and medallions (my magus received the most as it should be) but the Sorc also recieved a green bag in the mailbox?

The roll table showed that my Magus ended up at number 181 on the roll, we where not so many destro at anytime in Black Crag (as they often did a population check) , we were less than 110, slightly more than the aprox 100 order and it also showed 23 anon at the latest check which occurred aprox 5 min before zone was locked.

**Comment by Luth-RoR** [comment]
Not a bug report. Support forum: https://www.returnofreckoning.com/forum/viewforum.php?f=5
