### ISSUE TITLE
The Rally Point bugged.

### ISSUE THREAD

**Issue by Antalor** [WarEmu/WarBugs#9244]
Hello.
I've discovered that one Rally Point is bugged. It's located in Chaos Chapter 12 (Volgen) in Talabecland.
After I using my Book of Binding I've get throwed not to Volgen in Talabecland but to place nearby Order T3 warcamp in High Pass. I've sending a screenshot with this issue.

![adrian_003](https://cloud.githubusercontent.com/assets/13917674/23372993/52bb71c2-fd1e-11e6-888d-e6286c6e9424.jpg)

![adrian_004](https://cloud.githubusercontent.com/assets/13917674/23373000/5a26a0c6-fd1e-11e6-9aa0-6e513525fc5f.jpg)

![adrian_005](https://cloud.githubusercontent.com/assets/13917674/23373006/60b2183a-fd1e-11e6-9444-c9a9ed9b1216.jpg)

![adrian_006](https://cloud.githubusercontent.com/assets/13917674/23373015/67cb0050-fd1e-11e6-932e-8ec730388c39.jpg)

Greetings.

**Comment by saupreusse** [comment]
fixed in next patch.
