### ISSUE TITLE
NPC faction

### ISSUE THREAD

**Issue by ellionkeman** [WarEmu/WarBugs#9246]
T1 high elves. The blighted isle. House Arkaneth PQ. At some moment npcs of my faction began to attack me, though the didn't kill me, just lowered my HP to 24 points.  
![aleerah_006](https://cloud.githubusercontent.com/assets/18136746/23373793/8d30e972-fd32-11e6-9e3f-f5ef358a46a5.jpg)
![aleerah_010](https://cloud.githubusercontent.com/assets/18136746/23373792/8d3039be-fd32-11e6-90fc-3c95e89603ed.jpg)

**Comment by ellionkeman** [comment]
same with Raven Host Vanguard PQ 
![kem_013](https://cloud.githubusercontent.com/assets/18136746/23475112/8602b022-fec7-11e6-97a6-50bce1a3eb47.jpg)

**Comment by sioding** [comment]
checked - not reproduceable
