### ISSUE TITLE
Slayer Beastlord Helm

### ISSUE THREAD

**Issue by blakokami** [WarEmu/WarBugs#9251]
Seems like the gear between choppa and slayer is perfectly mirrored (which is intended afaik) besides the resists on some pieces because of difference in importance of resist depending on what side you are playing. All other stats/bonuses are the same except for the helm. Slayer has 20 toughness on the helm, and Choppa has 20 wounds. I believe both should be wounds :) or atleast I hope so. Thanks.

**Comment by wargrimnir** [comment]
Fixed in next.
