### ISSUE TITLE
Beastlord token quests

### ISSUE THREAD

**Issue by Kukuretina** [WarEmu/WarBugs#9253]
Quests are bugged for many people,I personaly didnt get beastlord token quests after blood hunt shoulder and back piece quest and can not re take/do blod hunt quests again,some people completed same token quest 5 times  and got hunting guide after killing only 1 beast,some completed multiple time beastlord quest only then to recive token quest...

**Comment by Kukuretina** [comment]
Beastlord hun no blood hunt sorry xD

**Comment by Kukuretina** [comment]
Beastlord hunt no blood hunt sorry xD

**Comment by Ryanfawkez** [comment]
Now watch and learn, here's the deal;
- The Cloak quest is repeatable, upon completing it once you get the Elf Token quest, also repeatable.
- All the other quests are not repeatable.

ALL quests are currently set to a fixed state. The only way to unfuck potential database inconsistencies would be through individual quest resets. If you can do the repeatable killquest for the Beastlord token, you can still get your full set.

**Comment by sioding** [comment]
**Thanks for the report.** Since there is no confirmation, i will close this issue now. Please make sure to follow the bugtracker rules which you can find here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)
