### ISSUE TITLE
Darkhelm Residence

### ISSUE THREAD

**Issue by ArdzofPT** [WarEmu/WarBugs#9254]
Walking up to the door in Barak Varr @47k 19k should give an unlock for Darkhelm Residence. Door is there, unlock doesn't work.

**Comment by 47k** [comment]
? I think you have the wrong name ;)

**Comment by d3BugErr** [comment]
An exploration unlock
http://warhammeronline.wikia.com/wiki/Achievements_(Exploration:_Darkhelm_Residence)

**Comment by Ryanfawkez** [comment]
Made a work-around.
