### ISSUE TITLE
Possible log in and lag issue.

### ISSUE THREAD

**Issue by albensambo** [WarEmu/WarBugs#9258]
So I have noticed that at times on my Magus cant log in or it takes several minutes to stop the insane lag and graphic to load. I noticed That it happens only when I log on and my bag is on the crafting bags.
I am getting an "Item move failed: attempted to move (number of items) while only having ( name and number of item)." 
It continues this indefinitely unless I open bag and switch to another bag other than crafting. sometimes impossible as nothing responds. This has caused my character to at time not even load into game depending if many players are around or if in a place that eats up FPS. I don't know the reason why, I have a screen shot that show it going on and on with item error.

**Comment by Luth-RoR** [comment]
Known https://github.com/WarEmu/WarBugs/issues/5654
