### ISSUE TITLE
Fluctuation discordant is bugged

### ISSUE THREAD

**Issue by borgute** [WarEmu/WarBugs#926]
![thraiiiiin](https://cloud.githubusercontent.com/assets/10282361/8479051/8bc4b888-20d5-11e5-9e05-8ffc1e15d8bb.gif)
Chosen's aura fluctuation discordant work for all attacks, MAGIC and PHYSICAL, but when you read the skill, aura must work ONLY ON MAGICS ATTACKS, that's why chosen hit very hard in t1-t2 an are cheated, please stop this bug thanks :)

I AM THRAIN SON OF THROR !!!

**Comment by Silentguard** [comment]
Confirm. Works that way only for aura owner, not for groupmates.

**Comment by ozarmidrashim** [comment]
Let's not start the "Thrain son of Thror" shit on the bugtracker as well, thanks.
