### ISSUE TITLE
[Loot] Keep gold bag has no drop

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#9263]
![rachik_009](https://cloud.githubusercontent.com/assets/13031465/23577610/194bf832-00ff-11e7-9e4e-c859940b5bcb.jpg)

**Comment by milosxe** [comment]
I had the same issue
https://github.com/WarEmu/WarBugs/issues/9266

**Comment by Cugar07** [comment]
Me to.

**Comment by Halhammer** [comment]
![halhammer_054](https://cloud.githubusercontent.com/assets/13981830/23598310/f656d39c-0239-11e7-9d2d-4f781caae4f5.jpg)

Same just now

**Comment by Torquemadra** [comment]
Were these on win or loss?

Were these win rolls or loser rolls?

Did you pick up in mail or from chest?

**Comment by Halhammer** [comment]
Loser roll, from mail

**Comment by milosxe** [comment]
Mine was winner, picked it up from chest.

**Comment by Silentguard** [comment]
Def roll from mail

**Comment by Cugar07** [comment]
![cugar_000](https://cloud.githubusercontent.com/assets/26207269/23678091/f48e9140-0382-11e7-8198-36c1d4c3abe7.jpg)
Win roll,from Mail

**Comment by Torquemadra** [comment]
when was that cugar?

**Comment by Cugar07** [comment]
05 March Sunday,Praag Win Loc Destro , i think 00.30-01.15 (CET)

**Comment by Cugar07** [comment]
Is there any news?

**Comment by SimbaRoR** [comment]
I had the same issue on my IB early hours this morning, i have screenshots if needed... help me out please

**Comment by SimbaRoR** [comment]
Also it was 1st place win roll, IB name is Beef

**Comment by kalmatar** [comment]
[IMG]http://i.imgur.com/t4ZKtOB.jpg[/IMG]

more proof if needed
got 1st contri place after lock, rolled high enough, 2nd place, went to keep to fetch bag, image shows what is in it

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=2&t=20514

**Comment by Razielhell** [comment]
#10279
