### ISSUE TITLE
Engineer T4 zone lock reward Purple bag not displaying all rewards

### ISSUE THREAD

**Issue by Fractus1484** [WarEmu/WarBugs#9264]
Hi,

On the zone lock for BC 04/03/17 in T4, i won the purple bag while playing as my engineer (Ract).

The bag was delivered by mail, opened in BC from mail and only displays 3 rewards:
- Loam
- Gold
- Conq medallions

There is no option to take either a weapon or cloak as there should be.

I've tried re-logging, reloading game etc, nothing has changed.

I still have the unopened bag in my inventory if any testing is needed.

Screenshot attached,

Thanks,
![ract_123](https://cloud.githubusercontent.com/assets/26185873/23579476/0a30024e-00e6-11e7-96d1-4558f3e21faa.jpg)

**Comment by Torquemadra** [comment]
#9263
