### ISSUE TITLE
Black Orc: Waaaaaaagh ability

### ISSUE THREAD

**Issue by Grolar** [WarEmu/WarBugs#9267]
I have tested this over and over and its doesn't seem to have the 30 ft range it us suppose to. Currently it seems half of that at only 15 ft.  I could dismiss this as a latency issue, but I wanted to bring it to your attention in case it is not.

**Comment by sioding** [comment]
**Thanks for the report.** Since there is no confirmation, i will close this issue now. Please make sure to follow the bugtracker rules which you can find here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)
