### ISSUE TITLE
Guild bugged my char

### ISSUE THREAD

**Issue by Lerilla** [WarEmu/WarBugs#9268]
Hello,

i have the problem that i have many dcs when im in a group. Dcs when i want to join a sc, want to fly to another zone etc. I worte with Adary and we find out that it is may be the guild.
When im not of a guild i have no problems. But of course i want back in my guild, so we tried it. The first sc was fine but then i got one dc after another. I even must tried to logg in 5 times and /rel /rel dosent work fine. 

Greetings

**Comment by LestiArdisson** [comment]
The thing you are witnessing is part of the "Guild Bug"

Sometimes Guilds get it. 
Story is that if a guild goes over 1000 players it gets it, our guild got it after being around 300 players.

Only Sollution we found is rebuilding the guild and invite everyone into the new guild.

**Comment by Lerilla** [comment]
The guild is small, only 71 characters. so i dont think this is my problem. And i'm the only one who has this problem.

**Comment by Luth-RoR** [comment]
There are already many "disconnect reports" on the bugtracker: https://github.com/WarEmu/WarBugs/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20disconnect
