### ISSUE TITLE
chosen missing 1h tyranny weapon from vendor

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#9269]
chosen missing 1h "def"  tyranny sword from vendor,  it only have 1h "def" axe.

**Comment by Ryanfawkez** [comment]
Name of the defensive axe, please. Also provide the name of the defensive sword you're referring to, if you could.

**Comment by Torquemadra** [comment]
Never existed on live.

**Comment by Tesq** [comment]
em can there are both 2 x axe 1h so why there should not be 2x  sword 1h...

there are also 2h axe/sword only 1 off and only 1 def, it kill appereance
