### ISSUE TITLE
Warrior Priest skills on Zealot.

### ISSUE THREAD

**Issue by Curtsie** [WarEmu/WarBugs#927]
I am able to get free spammable WP spells on a Zealot by simply making a WP and then logging onto my Zealot, able to recreate bug.

![skillsbug](https://cloud.githubusercontent.com/assets/13152617/8479839/51087306-20a8-11e5-9c27-f29f578ac0a1.png)

**Comment by jakerty** [comment]
scary stuff

**Comment by Bronli** [comment]
This happened to me (archmage skills --> ironbreaker) after logging out from my Archmage and to my Ironbreaker.

Archmage zone 0'd into a Nordenwatch scenario. Used /stuck to get out of scenario, but was still inside the scenario's warband (and couldn't leave it), so I just logged to my ironbreaker and ended up with the skills.

**Comment by Evildoor** [comment]
I think this exact problem was resolved (/stuck reworked, party-scenario interaction reworked, etc), and there are similar ones which are created by different causes (exporting/importing profile, for example), skills given by them are not usable. Closing this.
