### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Dekata** [WarEmu/WarBugs#9270]
My game crash on loading screen on my main char in Aldorf. Other chars loads in Aldorf normal. What can i do?

**Comment by Dekata** [comment]
The departure steadily comes from a game in attempt to approach vendors of RVR of sets near a tavern. I have tried to make on it from another char and have caught the same problem. Now and this char isn't loading in Aldorf. :)

**Comment by Dekata** [comment]
Problem is solved. Thank you...

**Comment by Razielhell** [comment]
You can close your own tickets. Its next to comment button.
