### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Gokudou** [WarEmu/WarBugs#9271]
When i come out of the Hammer of Sigmar in Altdorf game crashes.
attempts enter the game ends on the window loading (during a transition in Aldorf) and crashes again

**Comment by Gokudou** [comment]
all else fails, the problem is not solved. request to send me my character in any location except for Aldorf

**Comment by Gokudou** [comment]
HEEEELP!!!!

**Comment by LestiArdisson** [comment]
At the loading screen, when you see the book, type very fast:
/stuck /stuck

That will bring you to nordland.
