### ISSUE TITLE
[Subjugator weapon`s proc] Proc doesnt work

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#9274]
http://take.ms/8x1MmU

**Comment by Torquemadra** [comment]
Theres a conflict with having the kiss proc buff up, will have to look into it

**Comment by Psema** [comment]
I have issues as well with the rapier(sword for WH) the proc isnt working at all

**Comment by Torquemadra** [comment]
same mechanic, same conflict
