### ISSUE TITLE
Healers and Mayhem PQ

### ISSUE THREAD

**Issue by Celticwitch** [WarEmu/WarBugs#9278]
Chaos ruins PQ high pass chap 10 - healers not seeming to get contribution to loot rolls while healing party.  RP after 8 runs got no gold bad while dps all got.  We did a run with RP dpsing and WP healing and the RP got a gold bag.  Only DPS seems to give a big enough contribution, surely this isn't how it should be?

**Comment by Luth-RoR** [comment]
There is a huge random component for the rolls.
