### ISSUE TITLE
Saphery keep DC issue

### ISSUE THREAD

**Issue by Celticwitch** [WarEmu/WarBugs#9279]
When carrying supplies from BOs, randomly, people are disconnecting from the game when using any of the doors into the Saphery keep.

**Comment by sioding** [comment]
**Thanks for the report.** Since there is no confirmation, i will close this issue now. Please make sure to follow the bugtracker rules which you can find here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)
