### ISSUE TITLE
Bossy beasty not dropping token.

### ISSUE THREAD

**Issue by Celticwitch** [WarEmu/WarBugs#9281]
Tried to get a beastial token from the NPC - Khurraak Might-Horn - in Avelorn. Did work last week, no longer working.  You get the note in the tome and a blank square, but no token in bag so can't get trophy.

**Comment by Ryanfawkez** [comment]
Yeah, no more bestial token from that guy. Never awarded one on live.
http://warhammeronline.wikia.com/wiki/Bossy_Beastie
