### ISSUE TITLE
lvl 15 -lvl16 lvl up bugged me back to 15

### ISSUE THREAD

**Issue by lazeruz** [WarEmu/WarBugs#9282]
hello i had an bug experience i was lvl 15 and lvld up too 16 but i didn´t recieved the lvl
so i tried again i gained the lvl 16 i dunno what happend but but i did lvl 16 twice to recief it
would be nice if admins/gms would give me one lv + because i invested my realive time for it 
iam 16 now but i wasted time 2lvl for one what an bug would be nice if admins would do this 
have a nice day

ingame name is Cerberuz

**Comment by Luth-RoR** [comment]
The BT is no support forum. Furthermore: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=16391 + GMs generally don't give free levels on request.
