### ISSUE TITLE
Tzeentch's Lash is incorrectly undefendable.

### ISSUE THREAD

**Issue by Daniellita** [WarEmu/WarBugs#9287]
The 4s zealot silence cannot be disrupted, it was never meant to be this way, wasn't this way on live and RP alternative is disruptable. Over a count of 902 Tzeentch's Lashes in combat log 0 have been disrupted.  
Bug Demonstration using WH 100% disrupt and Engi 100% disrupt morale:

https://youtu.be/NNlgovfOA3o
http://sendvid.com/i8nulsgv

**Comment by Torquemadra** [comment]
was missing an attacking stat, fix inc
