### ISSUE TITLE
Ironbreaker Beastlord shoulder piece with no trophy slots

### ISSUE THREAD

**Issue by Fractus1484** [WarEmu/WarBugs#9288]
Ironbreaker Beastlord shoulder piece with no useable trophy slots

![rakt_275](https://cloud.githubusercontent.com/assets/26185873/23664635/ffbecc72-034d-11e7-9dff-05cef6dcad1e.jpg)
![rakt_273](https://cloud.githubusercontent.com/assets/26185873/23664727/47b9c0c2-034e-11e7-8c67-d90c4ce95e4f.jpg)

**Comment by Torquemadra** [comment]
not a bug, item doesnt have any.
