### ISSUE TITLE
SOLVED: Chaos Tier 4 Open RVR Rally Master does not have rewards

### ISSUE THREAD

**Issue by Luuca** [WarEmu/WarBugs#9289]
I am at the correct ORVR Influence Rally Master; however, he does not have selectable rewards. ToK confirms the correct Rallymaster and rewards have been earned. I have attempted to reload my UI as well as a relog completely out of the game to resolve.  Image of ToK open and Rally Master rewards open as well. 

![t4 rewards](https://cloud.githubusercontent.com/assets/13863553/23673108/e53a44f8-0325-11e7-895c-1ee35cae59e0.png)

**Comment by Luuca** [comment]
I found that by flying to Chaos Wastes, the Rally Master there had the rewards and i was able to select it.

**Comment by Luth-RoR** [comment]
Yes that's known; you have to pass certain points on the maps with a character to get the unlocks. Not 100% reliable yet.
