### ISSUE TITLE
Weapon skill not applied to ranged attacks

### ISSUE THREAD

**Issue by xyeppp** [WarEmu/WarBugs#929]
Weapon skill is not applied to ranged abilities - tested on SH's Plink.

Plink:
112 WS - base, no +wep skill items - 14% armor pen
Tank's HP left - 3614

129 WS - 16.1% pen < one and only change that mattered in damage was going from grey to green weapon skill in your stats window, after that it seems to cap.
HP left 3592

139 WS - 17.4% pen
HP left 3592
149 WS -18.6% pen
HP left 3592
159 WS - 19.9% pen
HP left 3592
169 WS - 21.1% pen
HP left 3592
HP remaining in each case is exactly the same.

If a melee or ranged attack has a magic element to it, such as Festering Arrow (Corporeal damage), Weapon Skill shouldnt not apply.

**Comment by Tesq** [comment]
Seems it do not work at all, ppl on forum wrote about it, it do not lower enemy armor.

**Comment by ozarmidrashim** [comment]
Fixed as of patch ~2 days ago

**Comment by xyeppp** [comment]
On a level 3 KoTBS you have 2 abilities - Sunder, hits for 49 and Precision Strike, hits for 55 and also ignores 25% of target armor.
On a level 3 mob, Sunder hits for 42, meanwhile Precision Strike for 33.

After the patch, my plink still capped out at 306 even after adding more WS and mitigation going down from 107 to 101. Testing with a marauder yesterday, and he seemed to have no DMG increase after WS and Scything talons.
