### ISSUE TITLE
No loot rolls after zone lock

### ISSUE THREAD

**Issue by Halhammer** [WarEmu/WarBugs#9290]
Has happened a few times now that I get no loot rolls after a zone lock despite havin spent quite a considerable amount of time (3+ hrs) with plenty of kills etc. in the zone.

It's either not showin any roll at all, or gives you that little thumbs down symbol. Dunno if that's visual and I just didn't win anythin, or if I really didn't even get to roll.

**Comment by bloodi** [comment]
Crashing during Orvr seems to make this issue happen, if you go and move out the zone and back in, you will get a loot roll.

Its oodd since you still get RR and inf as normal but there is no loot roll at all.

**Comment by Halhammer** [comment]
Yea I noticed that too but at least in 2 cases I was there the whole time w/o DCs

**Comment by Daniellita** [comment]
Sometimes the PQ loot roll interface doesn't appear; which is a visual bug non-specific to RvR, it happens during ruin pqs as well and it is unrelated. I won bags even when the roll interface didn't show for me. Whether or not crashing somehow affects contribution is another matter I don't know the answer to, but it's hard to tell for a SnB tank as the contribution system on it isn't obvious to me. IE.: If you are a dps and have loads of kills and damage compared to others in zone it's obvious you should be high on the contribution list. If a healer is healing a high damage/killing dps; same applies. Usually a party will be stacked together on contribution if they have been together in a zone, so if all 5 people are numbers 1 to 5 and you have been with them, crashed and aren't even in top 24, it probably means the crashed caused a problem.

**Comment by Luth-RoR** [comment]
With many players rolling, not everyone can get something. The UI can sometimes bug though, as already mentioned.
