### ISSUE TITLE
Quests all gone in the tome of knowledge.

### ISSUE THREAD

**Issue by Bobbiom** [WarEmu/WarBugs#9291]
Hello,
I had all my quests disappear on me after I got lagged out/disconnected from the server.
After I returned into the game I noticed that all the quests in my book were gone.
I further discovered that the beastlord quests could be taken a second time.
I then went to see if the t4 epic weapon quests were available for me aswell and they are, quests that I have already done in the past.

There is no problem receiving new quests.

I had some kind of bugged quest since the undead event that keept giving me hoof quest item from the boars which is now gone, no more hoofs which is good.

So somehow the quests for me got reseted.

My other characters seems to be all unaffected by this.

**Comment by Luth-RoR** [comment]
Known https://github.com/WarEmu/WarBugs/issues/2001
