### ISSUE TITLE
Didn't receive bag after zone lock

### ISSUE THREAD

**Issue by ItsJustJono** [WarEmu/WarBugs#9292]
order locked zone earlier today in praag, managed to come 3rd and I didn't receive my bag - despite it saying that I had won one. didn't get it in mail. :/

**Comment by Luth-RoR** [comment]
Could be the buggy UI: https://github.com/WarEmu/WarBugs/issues/9293#issuecomment-285771499

**Comment by grunbag** [comment]
It happened to me several times : bag come later by mail (one or two weeks later)

**Comment by Razielhell** [comment]
Merging with #10279
