### ISSUE TITLE
"Strong Finish" choppa Tactic

### ISSUE THREAD

**Issue by Brutalassault** [WarEmu/WarBugs#9297]
Greetings, 

I had found a visually bug for choppa tactic "Strong Finish". The tooltip says "Increases the chance to critically hit with "Path of Da' Big Hitta" abillities by 15% but decreases the abillity to defend critically hits by 10%". I checked on my melee panel stats and instead of having 10% bonus crit chance, i had 0%. I tested this one with a friend whitch he had 0% incoming crit chance and i done some crit hits on him (with not only "Da' Big Hitta" abillities). So this is only a visual bug, or there is something have changed on this career?

Thanks for reading :)

**Comment by Luth-RoR** [comment]
Character window is bugged - well known - please type .getstats in the chat window instead.
