### ISSUE TITLE
quest Beastlord Hunt : the fire of ulthuan

### ISSUE THREAD

**Issue by hashkampf** [WarEmu/WarBugs#9298]
took the quest in DW WC,  completed the quest in several steps, i have the cape from the NPC but if i try to continue, it gives me the same quest not the next one where you get the token.

send me if i'm online

**Comment by Antalor** [comment]
Same problem here. Any idea how to fix it, please ?
Greetings.

**Comment by Antalor** [comment]
Same problem here.
