### ISSUE TITLE
Buff general problem for guard /auras/ etc [Destruction][Order][Emulator]

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#930]
There is a problem for buff like auras and guard ( maybe other). You cannot double buff charatcer so this make impossible guard for exemple another char that alredy have 1 guard, make impossible swap guard to save someone if it's tank is away/afk/KB.
For auras i alredy reported it before, you should be able to have 2 same aura in party but only the best should work. This due to chosen/kobs alwasy want 100% time active the resistence aura.
Probably other buff behaviour this way, like dark protector etc; i'm not sure tought.

**Comment by ozarmidrashim** [comment]
What should happen if you attempt to guard a target that already has it?

**Comment by Thorgatin** [comment]
On guard:
My guess is, that you split damage with the tank who has the least range if you have multiple guards on you.

**Comment by Tesq** [comment]
guard and aura do not active that's what happend, You click on aura, it trigger animation but nothing happen, same for guard.

Auras should not be applied twice like all other stuff that do not stack only the highest get apply, Being auras a meccanic i think is need to handle as an  excetion, it behaviour like a buff for the stack purpose but only one got showed, considering that it would take indeed  6 spot with 2 chosen in party, so less space for dot.
Thorga (luth is it you?) should have right about guard the best in range get the split.

**Comment by ozarmidrashim** [comment]
Multiple guard now works.
