### ISSUE TITLE
Black Fire Basin Flag spawn glitch

### ISSUE THREAD

**Issue by Sejanus1** [WarEmu/WarBugs#9300]
Just noticed this in my last run of BFB, but wasn't able to get a screenshot or recording. 

When a flag carrier dies and drops the flag, when the opposing team picks it up and turns it in, the flag doesn't reset in center, it resets where the body died at.  Which led, in this instance, the opposing team getting two rapid fire caps because the flag reset on basically their front door.

**Comment by sioding** [comment]
No answer since 12.3.2017 - close for now.
