### ISSUE TITLE
Bug in Quest: "No End of Greenskins" Talabecland

### ISSUE THREAD

**Issue by Banthtex** [WarEmu/WarBugs#9304]
Only 1 (out of the many) "Swamptoof Shootas" count towards the quest "No End to Greenskins".
The quest is in Empire chapter 13, Talabecland, located at the Bitterchaum Swamp PQ.
Below is a screenshot of the only Shoota that seems to count towards the progress of the quest (there may be more than one, however I must've killed 10 other different spawns of the mob. Also included is the quest objectives.
![banth_009](https://cloud.githubusercontent.com/assets/26236213/23824556/b02dfb62-0670-11e7-84d4-5a3319231aef.jpg)
![banth_010](https://cloud.githubusercontent.com/assets/26236213/23824564/c48af812-0670-11e7-9f27-ff4cde0956cb.jpg)
Hope this is enough info :)
Edit: I found a second (screenshot below) working spawn of this, however I tested a few other spawns of this mob and it didn't count towards the quest.
![banth_014](https://cloud.githubusercontent.com/assets/26236213/23824647/09fcf98a-0672-11e7-8593-8933f1be4c58.jpg)
Edit 2: These 2 spawns actually do not count towards the PQ in the same area, although the rest of the mobs (that don't count for the quest). The 2 spawns mentioned do not generate influence - this appears to be the cause of the issue.

**Comment by wargrimnir** [comment]
This should be fixed already.
