### ISSUE TITLE
DOK T1 elite influence rewards Chaos realm

### ISSUE THREAD

**Issue by deLunel** [WarEmu/WarBugs#9305]
Hi,
for DOK the T1 influence reward in chaos is only 1 level 9 option, ie no choice? All other 3 choices are level 4. Shouldn't one of the Harvest blades be level 9 so there is a choice for dps vs healer maybe?
Thank you! :)

**Comment by wargrimnir** [comment]
I'm guessing one of the BG items that was missing it's career req was causing this. Should show the proper alternative items next patch.
