### ISSUE TITLE
Dark Elf T1 PQ issue

### ISSUE THREAD

**Issue by deLunel** [WarEmu/WarBugs#9306]
Hi,
From reading the 'working PQ map' I think Dark Elf T1 PQ Tor Achare in Chrace should work fully, yes?
At stage 2, one of the two types of enemy to kill I think was called Hunt Master (4 to kill - one in each group by corner buildings). The PQ did not count those kills - they remain at 0 kills so timer runs out and then PQ reset.

**Comment by Razielhell** [comment]
Works fine for me.
