### ISSUE TITLE
Abilities usable through Keep doors

### ISSUE THREAD

**Issue by Disc0nnected1** [WarEmu/WarBugs#931]
Abilities which do not require line of sight targets are usable though Keep walls and doors.    

Will update with screen shot.

**Comment by ozarmidrashim** [comment]
Cannot be fixed yet.

**Comment by Disc0nnected1** [comment]
TY for the updated

On 7/8/15, Azarael <notifications@github.com> wrote:
> Cannot be fixed yet.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/WarEmu/WarBugs/issues/931#issuecomment-119503825


-- 
Sarron Field

**Comment by Evildoor** [comment]
LoS check was implemented for scenarios and Empire RVR zones. Keep doors are still transparent for AoE.

**Comment by Evildoor** [comment]
Changelog for April 8th, 2016

[General]

Londo:
- Server side Line-of-Sight checks are now performed everywhere in WAR world. AOE damage and magus/engineer pulls will no longer go through walls, trees, fences, etc.
- All doors will now block aoe damage/pull when closed.
