### ISSUE TITLE
Mobs associated with PQ's don't give quest credit

### ISSUE THREAD

**Issue by PlanetTheGreat** [WarEmu/WarBugs#9310]
This is at least true of the first two Chaos zones, but mobs associated with Public Quests do not give quest credit. 

This might be a wider issue as at the start of the beginner Chaos zone there is a quest to participate in the first Public Quest, and no matter whether you kill the militia, click the grave stones, or kill the boss, you don't get quest credit for participating. You get PQ credit as far as I can tell, but not quest credit. This makes quests that involve killing PQ mobs impossible to complete.

**Comment by PlanetTheGreat** [comment]
Screenshot examples

![tzartaal_000](https://cloud.githubusercontent.com/assets/26360760/23832158/3c717b16-077b-11e7-8c2d-e8c124c225c1.jpg)
![tzartaal_001](https://cloud.githubusercontent.com/assets/26360760/23832159/3c755c90-077b-11e7-98c4-ac2c15c52965.jpg)
![tzartaal_002](https://cloud.githubusercontent.com/assets/26360760/23832160/3c7efdf4-077b-11e7-8391-f7defa1dc8e6.jpg)
![tzartaal_003](https://cloud.githubusercontent.com/assets/26360760/23832161/3c83ed14-077b-11e7-90cd-59be96b41c8e.jpg)
![tzartaal_004](https://cloud.githubusercontent.com/assets/26360760/23832162/3c84f1aa-077b-11e7-95c9-ceb9f8cbbeab.jpg)
![tzartaal_005](https://cloud.githubusercontent.com/assets/26360760/23832163/3c8a64d2-077b-11e7-978f-db9d90ed1fce.jpg)
![tzartaal_006](https://cloud.githubusercontent.com/assets/26360760/23832164/3c9efdf2-077b-11e7-84a7-95957fe90387.jpg)
![tzartaal_008](https://cloud.githubusercontent.com/assets/26360760/23832165/3ca63f68-077b-11e7-8bfa-df69f2aed6c3.jpg)

**Comment by PlanetTheGreat** [comment]
Important info I forgot to mention, this only started happening after the latest patch. Pre-patch these quests completed fine.

**Comment by Luth-RoR** [comment]
From #9327

>Leveling a new character today, I found a lot of quests which require you to "Kill X amount of Y" are bugged. It seems to only effect the quests which require you to kill things within a PQ area on the map.

Workaround Solution: If you can somehow kite the mob in question outside the PQ radius (so the little PQ title doesn't appear in the corner of the screen) and kill it without it resetting, only then it will count towards the quests kill progression.

Might have something to do with the recent Patch Notes 10/3/2017 - https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=20390

Specifically "Quest credit for kills has been adjusted"

**Comment by bitemebg** [comment]
T3 Epic quests all bugged

**Comment by korwrath** [comment]
The Order Epic quest, ancient horror,  for t3 in dwarf has this problem with Killing Restless Tomb Guardians

**Comment by bitemebg** [comment]
There is no mob's at all :)

**Comment by bitemebg** [comment]
So there is no more T3 Epic Quest's?

**Comment by bitemebg** [comment]
Inevitable Power, Will of the Warboss and Honoroble Deceit has the same problem

**Comment by Luth-RoR** [comment]
Fixed.
