### ISSUE TITLE
Book of Binding

### ISSUE THREAD

**Issue by birigozzo91** [WarEmu/WarBugs#9312]
the rally points set change random...

**Comment by wargrimnir** [comment]
No they don't.

**Comment by birigozzo91** [comment]
Set rally point to nordland and will teleport me to starter elf zone... set it to reikland and tp menon praag... it's a little bugged

**Comment by wargrimnir** [comment]
That's better. Now we have some examples to investigate. Do you have any more?

**Comment by birigozzo91** [comment]
now too.. i set rally point to Reikland and it becomes again Southern Breach... it's second time today ^^

**Comment by wargrimnir** [comment]
There are multiple places to bind at for each realm. Be specific with the locations. Order warcamp reikland? Destro chapter 20?

I just checked Order warcamp reikland and it worked correctly. They each have a specific entry that needs to be correct.

**Comment by birigozzo91** [comment]
it's Destro Warcamp Reikland

**Comment by Razielhell** [comment]
Fixed next patch. Thanks!

**Comment by sioding** [comment]
Fixed with patch 21.10.2017
