### ISSUE TITLE
WP jewelry - no strength, intelligence instead

### ISSUE THREAD

**Issue by mickeye** [WarEmu/WarBugs#9313]
After the changes to the jewelry, all grenn and blue strength jewelry has been wiped out fo Warrior Priest. Instead he can wear intelligence jewelry for runepriests and warrior priest.

**Comment by wargrimnir** [comment]
WP/DoK shares jewelry with MDPS classes for access to STR items, and Healer classes for access to WIL items. Some healers use INT. We would need to refactor all the drop items to fix this, so it's not going to happen. Buy/Sell/Trade/Salvage whatever you need or don't.

**Comment by mickeye** [comment]
I'm sorry but I don't understand what you trying to say. WP definitely doesn't share jewelry with MDPS classes. He shares INT jewelry with Runepriest, Archmage. You're saying that either this is correct or incorrect you're not gonna change it?

![obrazek](https://cloud.githubusercontent.com/assets/12357366/23834033/b83a931c-074f-11e7-9ea0-7be439a1ceb6.png)

**Comment by wargrimnir** [comment]
That looks incorrect to me. Details are in these patch notes https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=19970

This should have been caught a while ago, I'll see about getting them fixed. WP will still have access to the healer gear however.

**Comment by wargrimnir** [comment]
Fixed in next patch.

**Comment by mickeye** [comment]
Cheers
