### ISSUE TITLE
Chillwind manor BO in eataine

### ISSUE THREAD

**Issue by lazydna** [WarEmu/WarBugs#9316]
Destruction cannot reclaim this BO from order because one of the guardians that order has killed gives an error to destruction that it is still alive so the flag cannot be touched.

**Comment by Luth-RoR** [comment]
What's the name of the NPC?

**Comment by Razielhell** [comment]
Hm? Same issue here i think, with the BO on the other side of the map #9235

**Comment by lazydna** [comment]
mmm, forgot. i'll have to wait for eataine to be contested again to find out for sure, but i'm certain is was the name of one of the destruction guardians that defend it normally.

**Comment by sioding** [comment]
Since we have a ORvR System without guards atm i will close this issue now. Thanks for the report.
