### ISSUE TITLE
Bug in Quest: "Tireless Honor" The Blighted Isle

### ISSUE THREAD

**Issue by Rev0x** [WarEmu/WarBugs#9319]
Hello devs, I have encountered a bug in the titled quest where I cannot speak to the NPC named "Halael Mournfire" after defending him. Screenshots below. This prevents me from completeing/continuing any quest chain involved. Thank you for your help and dedication to improving the server.
![revox_000](https://cloud.githubusercontent.com/assets/26367456/23836090/118762c6-0749-11e7-9ea3-5fc918d29fa1.jpg)
![revox_001](https://cloud.githubusercontent.com/assets/26367456/23836093/1aee2a34-0749-11e7-9f25-606fe15590a6.jpg)

**Comment by ellionkeman** [comment]
Same here. 
![alerdir_001](https://cloud.githubusercontent.com/assets/18136746/23866895/49b5f38c-082b-11e7-86b8-63ddabf9e838.jpg)

**Comment by Luth-RoR** [comment]
Known https://github.com/WarEmu/WarBugs/issues/7923
I'm re-opening the old report, maybe it can be fixed now or get a workaround.
