### ISSUE TITLE
Tactic ability broken / Expert Skirmisher / Close Quarter

### ISSUE THREAD

**Issue by albensambo** [WarEmu/WarBugs#9320]
The tactic "close quarter" for magus says it requires enemy to be with 20 feet to activate 50% cast time reduction, I can activate it any time with no enemy around. If this is on both factions then it probably works the same for other classes.

**Comment by Pxl555** [comment]
I'm not sure how its supposed to work , but i do know it doesn't say it requires your enemy but rather that it requires your 'target' (which can include you) to be within 20 feet.

**Comment by albensambo** [comment]
if that the case then it is broken, it should simply stat reduction in cast time, not target, the fact that it says target implies enemy and not youself

**Comment by Luth-RoR** [comment]
>but i do know it doesn't say it requires your enemy but rather that it requires your 'target'

Friendly target makes sense for buffs on members off the same faction, not for damage on enemies.

**Comment by Luth-RoR** [comment]
From https://github.com/WarEmu/WarBugs/issues/9409

>Looks like the "Lileath's Arrow" skill gets the defensive target for the "Expert Skirmisher" tactic to work instead of the offensive one. Skills that require target work fine. Don't know if "Shoot Thru Ya" has the same issue.

https://youtu.be/jaZpzGuXv4Y

>i tested it on rvr too, i can post video if i have too.

Ready ----> https://youtu.be/paKbPhLVblM

**Comment by timoteiz** [comment]
The skill expert skirmisher after the patch 25/11/2017 still has issues with engies. 
The turret and keg not deploying 50% faster when not in combat.. and the skill states target where target is the engie himself.

also in combat it works if u deploy the turrent but if you  re-deploy it doesnt work.. 

I am not goood with video and stuff - if need it let me know and i will see what i can do to produce one.

thank you.

**Comment by Torquemadra** [comment]
target is enemy target not self.

**Comment by timoteiz** [comment]
New issue with this tactic.. when u have 1 enemy at 0feet and u have targeted one at 21+ feet the speed buff dont apply, or if by mistake you target is a dead one. Also this is a problem with aoe skills in engie that doesnt require targeting..

**Comment by Pumatouch** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=24072
[Abilities]

Natherul
- Hardcode so that expert skirmisher correctly affects Lileaths arrow or shoot through ya, the client is however hardcoded to change the castbar if out of range but the cast wont go off earlier

Engineers have also been subjected to this delay of castbar for Friendly Builds, ie Turrets, Electro Rod, Bugman's Keg and a few other friendlies. _Magus and Squig Herder does not have the same delay_ on their friendly builds, ie Daemons and Squigs, that was instituted as per the fix. 
See also https://www.returnofreckoning.com/forum/viewtopic.php?f=74&t=24492&p=275585&hilit=expert+skirmisher&sid=400d95866004388866ca4cbb4363e213#p275585 for clarification on the SW nerf mentioned in patch notes. 

Conclusion: Engineers have been silently hit with Shadow Warrior fix, while every other class than these two who have either Expert Skirmisher or Close Quarters retain their fast friendly builds.

**Comment by Pumatouch** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16616998/36076933-78bbbda2-0f63-11e8-8e8e-cbdec6189242.gif)

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/16616998/36076935-80ba237c-0f63-11e8-8daf-838985120ef1.gif)

Here the Engineer and the Magus both summon all 3 Turrets/Daemons using Expert Skirmisher/Close Quarters to friendly-build faster. Engineer had a fix done to its end of Expert Skirmisher on Nov 25. As is evident from the much faster summoning, the Magus is not affected by this fix. When checking with a friend, Squig Herders are not affected either.

**Comment by Natherul** [comment]
at the time when I wrote that patch note I did not know that ES was shared with more then SH and SW. It applies to all versions of ES

**Comment by Pumatouch** [comment]
ES has an identical twin also, Close Quarters. Magus has it for one. Wording and effect is the same.

**Comment by Pumatouch** [comment]
Quote Natherul:
_at the time when I wrote that patch note I did not know that ES was shared with more then SH and SW._

SH is not affected by any fix. Only Engineer got the fix along with SW. You can go on SH and build fast squigs with impunity using Expert Skirmisher right now.

**Comment by Natherul** [comment]
from the forum topic:
"Not true, I just checked on my local, the casterbar is not correct for squigs. ES does not speed up the cast.

In the case for close quarters is because its set differently in the DB and does not use the fix. So there is nothing wrong in code."

**Comment by Natherul** [comment]
close quarters will be fixed in the next patch. I double checked and it was just missed in the db

**Comment by sioding** [comment]
fixed with hotfix from 11.2.2018
