### ISSUE TITLE
Bug in Quest: "Trail of Darkness" The Blighted Isle

### ISSUE THREAD

**Issue by Rev0x** [WarEmu/WarBugs#9323]
Hello, killing Bloodfueled Devotees is not counting towards quest progression. This of course prevents the player from completing the quest.
![revox_002](https://cloud.githubusercontent.com/assets/26367456/23838598/b634f6ac-076d-11e7-9e0a-e518cf1b4fd6.jpg)
![revox_003](https://cloud.githubusercontent.com/assets/26367456/23838599/b9b0bb5e-076d-11e7-9f5d-880016085277.jpg)

**Comment by Luth-RoR** [comment]
Refering to https://github.com/WarEmu/WarBugs/issues/9310

**Comment by Luth-RoR** [comment]
Closing as it seems to be a general issue with all quests that share NPCs with PQs.
