### ISSUE TITLE
Bug in Quest: "Horrors of War" Chrace

### ISSUE THREAD

**Issue by Rev0x** [WarEmu/WarBugs#9324]
Hello devs, there is a bug in the titled quest in Chrace. Neither the brutes or corsairs are counting towards progression for the quest. Screenshot below. Note how in the top right hand corner you can see i killed mobs they counted towards the PQ but not the quest itself.
![revox_004](https://cloud.githubusercontent.com/assets/26367456/23838776/707e9ada-076f-11e7-9a51-311a7426e540.jpg)

**Comment by Luth-RoR** [comment]
Refering to https://github.com/WarEmu/WarBugs/issues/9310

**Comment by Luth-RoR** [comment]
Closing as it seems to be a general issue with all quests that share NPCs with PQs.
