### ISSUE TITLE
Quest Bugs - Kills not counting towards quest

### ISSUE THREAD

**Issue by Zoggof** [WarEmu/WarBugs#9327]
Leveling a new character today, I found a lot of quests which require you to "Kill X amount of Y" are bugged. It seems to only effect the quests which require you to kill things within a PQ area on the map.

_Workaround Solution_: If you can somehow kite the mob in question outside the PQ radius (so the little PQ title doesn't appear in the corner of the screen) and kill it without it resetting, only then it will count towards the quests kill progression.

Might have something to do with the recent Patch Notes 10/3/2017 - https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=20390

Specifically "Quest credit for kills has been adjusted"

**Comment by bitemebg** [comment]
I have the same issue.

**Comment by Luth-RoR** [comment]
#9310
