### ISSUE TITLE
Different resists on 'same' jewelry

### ISSUE THREAD

**Issue by mickeye** [WarEmu/WarBugs#9328]
Hello, since I already asked about WP jewelry, I'd like to ask why are there discrepancies between Str/Wou lvl 37 green jewelry. It seems like one of the items has been overlooked in resists values. See screenshot. Is it possible to fix this, so they share same stats?
Thanks

![str wou jewelry](https://cloud.githubusercontent.com/assets/12357366/23871549/310dbf36-082b-11e7-9333-cbf531f20980.png)

**Comment by wargrimnir** [comment]
Fixed in next.
