### ISSUE TITLE
All of my quests disappeared.

### ISSUE THREAD

**Issue by mailie** [WarEmu/WarBugs#9329]
I got disconnect and all my quests disappeared. Its like it has reset to beginning. All my BL quest progress is gone too.

Note I only have 2 quests available because  I recently got them when I went to IC to get my T4 accessory and thats when I noticed that all my quests were gone from my book.

![gitcheech_004](https://cloud.githubusercontent.com/assets/26393623/23877366/f3701622-087c-11e7-9cc7-c4d61ea36c04.jpg)

**Comment by Luth-RoR** [comment]
Known issue https://github.com/WarEmu/WarBugs/issues/2001
