### ISSUE TITLE
[Archmage/Shaman] SoS / DFN not affected by mechanic points

### ISSUE THREAD

**Issue by Xvim22** [WarEmu/WarBugs#933]
I am only seeing changes on Law of Conductivity, Searing Touch, Transfer Force, and Lambent Aura (as of level 9).

**Comment by ozarmidrashim** [comment]
If you're saying that the cast time bonuses don't work, it's a known issue, happens after you zone.

**Comment by Xvim22** [comment]
For the most part....however the tooltip for Shield of Saphery buff shows the same value no matter the stacks (hard to double check the actual combat effect when absorbed hits are not registered).

**Comment by Illiyara** [comment]
The bonus from high magic isn't shown by tooltips. You have to test it by casting. I'll see if I can test shield of saphery with someone's morale ability to see how much it does absorb.

The issue I'm sure of is that High Magic is only partially working for spells with cast times. Unless you cast with 5 points while moving, you will go through the normal spell animation, which is really annoying. The spell will go off at the right time, but you'll still finish the animation and be unable to start another spell until you finish it. This can't be cancelled by movement or spamming another skill.

For example, if I have 3 Force and cast Blessing of Isha (2.5s cast normally), the spell will go off 1.5s into the cast animation, but I can't start casting another spell until the whole 2.5s animation finishes.
It does work properly if with 5 points while moving, though (becomes instant cast and skips the staff-twirling animation).

**Comment by Illiyara** [comment]
OK, tested with a friend. Shield of Saphery indeed doesn't benefit at all from high magic.
