### ISSUE TITLE
Cross Faction Item Drop 

### ISSUE THREAD

**Issue by Zoggof** [WarEmu/WarBugs#9330]
Item dropped from Wavering Sigmarite (21) is unusable since it is a High Elf item.

![khalakh_000](https://cloud.githubusercontent.com/assets/23256143/23888598/ecd6f9c4-08dc-11e7-8a73-db7fb1cf60c6.jpg)

Location - Talabecland 9.3, 29

![khalakh_001](https://cloud.githubusercontent.com/assets/23256143/23890577/8e48950c-08e6-11e7-9d00-8db359863b90.jpg)

Dropped from Playful Peasant (21)
Location - Talabecland - Steinbruck Manor PQ

![khalakh_002](https://cloud.githubusercontent.com/assets/23256143/23890984/4519daa6-08e8-11e7-9d62-bf1e0def79bd.jpg)

**Comment by Torquemadra** [comment]
when precisely did these happen

**Comment by Lileldys** [comment]
Has just happened to me 14/03 ![lidlid_000](https://cloud.githubusercontent.com/assets/13259775/23919513/046f8e9a-08ef-11e7-8abd-f41db1252ac3.jpg)

**Comment by Zoggof** [comment]
15 Hours ago, I was saving screenschots and uploading the bug report here as they dropped for me.

**Comment by jcera25** [comment]
I had it happen last night, from roughly 8:50pm until 9:20pm (UTC-6).  On my Runepriest my last 4 items I looted were a DoK shoulder item, a WE dagger, a Chaos sward and a Green Skin stabba.

**Comment by wargrimnir** [comment]
This should be fixed now, any further reports?

**Comment by Zoggof** [comment]
I've been grinding most of the night and I haven't seen a single cross faction item drop, nor have I seen any people talking about it in chat which they usually do. Looking good..

**Comment by Luth-RoR** [comment]
Thanks, closing.
