### ISSUE TITLE
Ravenraid/Nordland Major Graphic Issue

### ISSUE THREAD

**Issue by tazmaniac93** [WarEmu/WarBugs#9332]
Upon using a flight path from Inevitable City to Nordland, I loaded in to nothingness. The character does not fall, nor die. The ground and all NPCs simply do not exist. I wandered around to test if the area would eventually load. It did not. I proceeded to unstuck twice to starting zone. Upon walking towards Ravenraid, the same issue occurred. Attempting to walk away from Ravenraid did nothing. The area appears unstable.

Extra things to note: Occurs on Rank 37 WE, occurs on any sort of entrance into the Ravenraid area (flight path or walking), does not appear random, but in fact a guaranteed occurrence. 

UPDATE: Third attempt walking from starting zone to Ravenraid. This time, I detoured through the Macabre Fervor PQ. Still, the moment the zone title "Ravenraid" appeared on screen, the world vanished. My WE is stuck until book of binding cooldown resets. 

UPDATE 2: Using /stuck command once places me in Ravenraid with no graphic issue.

**Comment by Luth-RoR** [comment]
High likely the very old and well known "zone 0" bug, which happens very rarely nowadays.
