### ISSUE TITLE
T1 epic quest Among the Shadow 

### ISSUE THREAD

**Issue by Ghatisgob** [WarEmu/WarBugs#9335]
This quest line is broken, this NPC should give the continuation of the Epic Quest Among the Shadow
![broduin_000](https://cloud.githubusercontent.com/assets/25305100/23963848/dfde64b0-09b2-11e7-9033-f691ce427be9.jpg)

**Comment by wargrimnir** [comment]
Fixed in next, and the rest of the quest too, probably.

**Comment by WAR2014** [comment]
Hey Devs and DBs, 
Sorry to interrupt your closed ticket! The OP was right, I had done this quest till the above map (Stage IX), the quest returned to this NPC then no more continuation for next stage. 
Please refer this quest on hammerwiki link http://warhammeronline.wikia.com/wiki/Among_the_Shadows_IX

Ta!

**Comment by wargrimnir** [comment]
It should start on Larineth Spearsong, looks like the quest indicator doesn't show up. I'm moving that one back to Liraenor in the next patch, and there's another step later on that's broken too. Fixing the items too.

**Comment by wargrimnir** [comment]
Fixed in the last patch.
