### ISSUE TITLE
The Ebon Flame Epic Quest bug.

### ISSUE THREAD

**Issue by Discodeath** [WarEmu/WarBugs#9336]
On the quest chain where you have to kill Truelight Guardians you get no credit for killing them. But you still get credit for adepts. Relogging and abandoning the quest and retaking it did not fix this. 
![aggrophobia_011](https://cloud.githubusercontent.com/assets/26455224/23987919/53f09752-0a02-11e7-8318-429a6888fe87.jpg)

**Comment by Lileldys** [comment]
This is because its a PQ mob in the PQ area, if you pull them out of the PQ area you can progress your quest.

**Comment by Discodeath** [comment]
Nope, tried that. pulled them clear out of the PQ and still got nothing. It works fine now tho after the most recent patch.
