### ISSUE TITLE
Soulfire casttime decreases to 1 second upon spam

### ISSUE THREAD

**Issue by ItsJustJono** [WarEmu/WarBugs#9337]
Normally it's 2 seconds, but if you spam it, it goes down to 1 sec. Feel free to check my stream/saved vods to see it.

**Comment by Luth-RoR** [comment]
Shouldn't be possible, maybe the the same issue as https://github.com/WarEmu/WarBugs/issues/8902#issuecomment-275174286?

**Comment by ItsJustJono** [comment]
tested it, seems to reset the duration - and 1 second.
https://www.youtube.com/watch?v=-d1gjrfkE8Q&feature=youtu.be

**Comment by Luth-RoR** [comment]
For me the cooldown is reseting too when i spam it, but it doesn't do damage when i break the full cast time like that. Maybe it's a problem in the mythic 1.4.8 client.

**Comment by Torquemadra** [comment]
try it now

**Comment by Luth-RoR** [comment]
Can't be spammed under 2 seconds anymore, thanks. It just didn't do damage in my earlier test because the DoT timer is reset on the re-application of the debuff and it has no direct damage component.
