### ISSUE TITLE
Gold bag from zone flip does not reward item piece

### ISSUE THREAD

**Issue by wilesa** [WarEmu/WarBugs#9339]
![capture](https://cloud.githubusercontent.com/assets/12731177/24024823/9fe07e5e-0a8c-11e7-802e-27c29952b5ad.JPG)
Received zone flip (Caledor) gold bag reward in mail, only these three rewards available. 

Happened around 9pm EST March 16th, 2017 (1am UTC March 17th)

-Auzzimvpness

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/9263 known
