### ISSUE TITLE
Caduin Goldbough

### ISSUE THREAD

**Issue by ArdzofPT** [WarEmu/WarBugs#9342]
The Rally Master for High Elf chapter 4, Caduin Goldbough, is missing. The map marker for the NPC could also be wrong, but I didn't see Caduin in the chapter or the map marker spot.
![wiggleworm_000](https://cloud.githubusercontent.com/assets/15960258/24068504/a9e23566-0b4d-11e7-846c-9641ac772498.jpg)

**Comment by wargrimnir** [comment]
He's inside the tower, it goes underground.

**Comment by wargrimnir** [comment]
![image](https://cloud.githubusercontent.com/assets/12942408/24574366/6bc88074-165f-11e7-8473-1d1bf38897b6.png)
![image](https://cloud.githubusercontent.com/assets/12942408/24574373/7e057a08-165f-11e7-9351-ef19ebc3c58c.png)
