### ISSUE TITLE
T4 RvR zone control is bugged

### ISSUE THREAD

**Issue by Blubberino** [WarEmu/WarBugs#9343]
We just capped TM's keep. We had 80% and dropped to 50% while having all bo's + carrying ressources. Looks like only one side is getting the % from doing stuff. (currently order) 
Also map seems to be bugging out too now shows TM and KV are open.

**Comment by Blubberino** [comment]
Order has the same problem now T4 rvr compleatly bugged out

**Comment by Blubberino** [comment]
Well seems that they can't get higher than 80%. So double buggy.

**Comment by Blubberino** [comment]
Looks like it was fixed now.

**Comment by Blubberino** [comment]
Bug reappeared again today in praag
Order stuck at 80%

**Comment by sioding** [comment]
Since we have a complete new ORvR system i will close this issue now. Thanks for the report.
