### ISSUE TITLE
Tzeentch Cultist

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9345]
- [x] 40 level mob on the road just outside Ulfenwyr PQ.
![warhammer online age of reckoning 03 17 2017 - 12 11 04 150](https://cloud.githubusercontent.com/assets/16864486/24071346/1bb08578-0bd8-11e7-9ffd-3ccf107d26e3.png)

**Comment by wargrimnir** [comment]
Fixed in next.
