### ISSUE TITLE
Quest: Mandatory Conscript 

### ISSUE THREAD

**Issue by ArdzofPT** [WarEmu/WarBugs#9346]
Kills in Troll Country are not counting towards this quest.
![wiggleworm_001](https://cloud.githubusercontent.com/assets/15960258/24071735/b78f560a-0b96-11e7-8dc5-0b6c6bb6fd06.jpg)

**Comment by Luth-RoR** [comment]
Are the NPCs located in public quest areas?

**Comment by Razielhell** [comment]
This quest is located at the entrance of Order TC WC. Click on Marauders.

**Comment by Luth-RoR** [comment]
>Kills in Troll Country are not counting towards this quest.

**Comment by Razielhell** [comment]
OP must check.

**Comment by ArdzofPT** [comment]
The quest is an RvR quest.

**Comment by Luth-RoR** [comment]
Isn't this the quest that requires to just click some corpses at the T2 warcamp entry?

**Comment by Razielhell** [comment]
@ArdzofPT Please try clicking on these bodies and report back.
![warhammer online age of reckoning 03 26 2017 - 23 09 38 49](https://cloud.githubusercontent.com/assets/16864486/24334796/ae40268a-1279-11e7-8963-077cceb7059b.png)

**Comment by Luth-RoR** [comment]
No response, closing.
