### ISSUE TITLE
Skargor da Traitor - Public Quest Greenskin Chapter 16

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9348]
- [ ] Needs mob rearrangement and **MORE** Rebellin Gits for Stage 1.**_Counted 12-13 in the area_**
- [ ] This champion needs to be removed.
![warhammer online age of reckoning 03 18 2017 - 15 31 53 153](https://cloud.githubusercontent.com/assets/16864486/24072491/661627cc-0bf0-11e7-83e4-310695ec6fb5.png)

**Comment by grunbag** [comment]
Fixed in next patch
