### ISSUE TITLE
Precursor Keymantle item

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9349]
Not for Bright Wizard? 
![warhammer online age of reckoning 03 18 2017 - 18 47 40 161](https://cloud.githubusercontent.com/assets/16864486/24074143/874089f4-0c0b-11e7-9504-0edd51a1ffa4.png)

**Comment by voina817** [comment]
yeah, i also found this bug... 
check it plz~

**Comment by wargrimnir** [comment]
Fixed
