### ISSUE TITLE
[MAGUS] Blue horror's aura affects spells'range

### ISSUE THREAD

**Issue by karatak** [WarEmu/WarBugs#9353]
Hello,

I looked for this strange bug in the bugtracker but didn't find'it.

The bug is pretty simple : when a magus summons a blue horror, her aura, which strengtens the magus as it should be, also affects the range of all magus spells, wich vary in a very weird way : it progressively decreases or increases over the time (from approximatively -40 to+40% i would say). When you go out of range from the blue horror aura, the range progressively gets back to normal. So i am pretty sure that's a blue's horror aura bug. The other magus pets don't seem to be affected by this bug.

![baalkoth_003](https://cloud.githubusercontent.com/assets/26520450/24080350/8d740e4e-0c9d-11e7-9b22-d5673f59dfdd.jpg)
![baalkoth_005](https://cloud.githubusercontent.com/assets/26520450/24080347/8d73577e-0c9d-11e7-9973-781cb0f26350.jpg)
![baalkoth_009](https://cloud.githubusercontent.com/assets/26520450/24080351/8d7dddfc-0c9d-11e7-87d3-cc842e6369f2.jpg)
![baalkoth_012](https://cloud.githubusercontent.com/assets/26520450/24080349/8d73f58a-0c9d-11e7-8e82-7e1465808ba4.jpg)
![baalkoth_015](https://cloud.githubusercontent.com/assets/26520450/24080348/8d73f4b8-0c9d-11e7-916f-b31017fbd7be.jpg)

Thanks in advance ! And thanks too for making this awesome game alive again !

**Comment by Luth-RoR** [comment]
Type *.ab changlist* into the chat window to see the RoR specific magus changes.
