### ISSUE TITLE
19/03/2017 Praag Destro Keep

### ISSUE THREAD

**Issue by tionblack** [WarEmu/WarBugs#9359]
We order besieged the keep and got the doors down and wiped at the boss then suddenly the doors went up.Destro had no battle objectives or supply runs.At order side we need to carry loads of supplies for this but after a short time destro gets their doors up.Please look into this and thanks in advance ! Cheers!

**Comment by sioding** [comment]
**Thanks for the report!** A lot of things have been changed since creating this problem. Please confirm that it is still a current issue.. You can help us by following the bugtracker rules, which can be found here: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366
