### ISSUE TITLE
Magus`s pets.

### ISSUE THREAD

**Issue by Glohroc** [WarEmu/WarBugs#936]
1. Demons don`t adopt Magus`s intelligence 
2.DoT of pink demon works really rarely.
3.Pink demon`s skills don`t lower target`s resistance.

**Comment by Zealote** [comment]
Tested this on a lvl 20 magus against lvl 21 Yetis.

1) I tried with 206 int and then with 141 int:
          - AA: 79 -> 79 (imagine it should be affected by int as well?)
          - Daemonic Fire (DF): 110 -> 94
          - Daemonic Consumption  (DC): 28 -> 21 (on each DoT tick)

2) Not sure about this. I did notice that the daemon's DF/DC icons didn't always show up on target's hp bar; they usually did show if you cleared your target and re-targeted though. The pet's abilities also disappear from pet's action bar which might make it seem like they're not working, but think that's known. 

3) Seems to be working but there's one issue which might be a general combat one: DoTs cast before DF don't increase in dmg on subsequent ticks (think it applies to Daemon's own DC as well). However, there was an increase when using Surging Violet Fire before and after Pink Horror's DF:
          Level 21 yeti: 149 dmg -> 182
The only possibly strange thing is:
          Level 22 yeti: 147 dmg -> 182 (Not sure if doing 182 to the different lvl mobs is correct or not)

**Comment by Glohroc** [comment]
Thanks for reply. Will look for it a bit later and maybe will reply if I find something about this topic.

**Comment by Evildoor** [comment]
It seems to me that 1 is fixed according to @Zealote (i don't know about magus pets AA and i'm not sure that we can obtain more or less reliable source on its value/scaling/etc), 2 should be fixed now since general pet intelligence was improved (delay between skills reduced) and 3 is a general issue unrelated to magus pets. Closing.
