### ISSUE TITLE
Cant sell crafting items to merchant

### ISSUE THREAD

**Issue by Seluzz** [WarEmu/WarBugs#9362]
Well.. As you can see im not able to sell items to merchants.. 

I hope this bug is a token worth ;o) 

![eraze_001](https://cloud.githubusercontent.com/assets/26539995/24103086/78338816-0d7e-11e7-97db-e1701a7a6490.jpg)
![eraze_002](https://cloud.githubusercontent.com/assets/26539995/24103087/784a7288-0d7e-11e7-9e00-4ba6d23f9ce8.jpg)
![eraze_003](https://cloud.githubusercontent.com/assets/26539995/24103088/7855babc-0d7e-11e7-9bfe-4f1403b056a6.jpg)
![eraze_004](https://cloud.githubusercontent.com/assets/26539995/24103089/78574df0-0d7e-11e7-98b2-dbce940886d4.jpg)

**Comment by Ryanfawkez** [comment]
Try selling it to a different vendor...?

**Comment by Seluzz** [comment]
Yeah i did try another merchant.. This issue is the same on both Destruction and Order side...

**Comment by Luth-RoR** [comment]
Drag&drop the items into the vendor window; only the client says "no sell price" but the server accepts it and gives you le gold.

**Comment by Seluzz** [comment]
Thanks for the assistance, but its still a bug, and the report should still be open, since its not resolved.?
If other players dont know about the drag and drop to merchant, they will do the same as i did for a long time.. 
I think i lost well over 100 - 200g due to crafting loot drops i deleted...

**Comment by Luth-RoR** [comment]
If the tootips don't say that they can't be sold, they couldn't be sold on the mythic servers too; we use the latest 1.4.8 client with the same tooltips.
And as tooltips are client side, they can't be changed anyway atm.
