### ISSUE TITLE
Witch elf Sacrifices Rewarded

### ISSUE THREAD

**Issue by Yardape** [WarEmu/WarBugs#9364]
I'm not too savvy on how Absorb works but i am running the Scrifices Rewarded tactic and would assume it triggers every 3 seconds based on direct critical attacks and absorbs a total of 600 damage.

I am yet to see it absorb a total of 600 damage. and it also doesn't even trigger at all in some instances

https://gyazo.com/53a49c9e4e8d12514d59388890cfb453

The link above shows that it never absorbed 600 total at all, and if i understand right all damage is within 1 second.

https://gyazo.com/16f783c6043e9012d8a613bfa9aec8b7

The above link shows a total absorb of 522....which is close but not 600, 

https://gyazo.com/5d0beff83c5594b5b17f756f942e1cdd

The above link i only absorbed 30 damage,

https://gyazo.com/65192844b37cf759bf2c9c23d1d760cc

In the above link it obviously doesn't trigger off auto attacks (not direct i guess) However when it did trigger it absorbed only 87

https://gyazo.com/c0ea966ba435635dfdadc5d7431b3d42

Here an Auto Attack does trigger the Absorb..???? `````````

https://gyazo.com/9b720c3219035006afc3b783e7ca5bdd

The above link, the absorb did its job and went to 600

I'm not sure How it all works but i kinda see something not right here

**Comment by Torquemadra** [comment]
It behaves 100% as it should in testing, I would suggest its a combat log issue. Feel free to continue testing but I can find no error here, or in tables.

**Comment by dalen** [comment]
This combat log display issue is fixed now.
