### ISSUE TITLE
Mount and stealth bug

### ISSUE THREAD

**Issue by Ristom81** [WarEmu/WarBugs#9370]
So in the following scenarios where you have to record the barrel (for example Talabec dam) the following bug exists. And if you do not create the barrel or you are killed before, you can not move the whole scenario to the mount.When one then plays a class WH / WE you can not go to the whole scenario in stealth.It is then said to me namely, I would just move an object and therefore you can not mount or stealth.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/6975
https://github.com/WarEmu/WarBugs/issues/8907
