### ISSUE TITLE
Infinite resources

### ISSUE THREAD

**Issue by Psema** [WarEmu/WarBugs#9372]
This morning i was in TM carrying resources after 8-9 normal runs from the bo to the keep,i went to keep to leave the resources and after i turned them in i noticed i still had the light  column indicating i still had them.In the beginning i thought i moved without giving them,so i pressed again i saw i took some rp but the light remained.I retried them  and i got and the message that i turned them in and i took some rp(and i was still carrying the resources) at that point i contacted a gm and he told me to make a bug report.The issue got fixed after i relogged but to what i understood i could turn them on again and again which could cause people to gain huge amounts of rp and contribution

**Comment by Luth-RoR** [comment]
Known https://github.com/WarEmu/WarBugs/issues/9241
