### ISSUE TITLE
Several bugs associated with white lion and orvr

### ISSUE THREAD

**Issue by malvic1** [WarEmu/WarBugs#9373]
Hello! gathered some bugs over a time now..

starting off with the most obvious one - Ordnance items in orvr zones does not work!

white lion abilities - Submission ability does not work

White lion pet needs to be resummoned when entering a rvr zone for the damage increase from the bolster buff to take effect.

(BONUS - The server change from the live version with adding 10sec cd on pounce and increasing movement speed instead is a flaw and personally I'd like to see it restored to the old version without movement speed increase and no cd!)

White lion pet does not have appropriate threat levels.
if pet is tanking as soon you step within range of the mob they will swap to you or after a first hit they will even tho that hit is with Submission ability!

Bolster buff ORVR zone - the bolster buff disapear after gaining a rank in rvr zones not renown ranks but regular one that cause you to drop down to your actual HP and have to regain the HP given by the Bolster buff.

Entering a Tier 1 ORVR zone as a rank 1-3 character with no gear except the starter items your parry chance is absurd, been called hacker several times for parrying all their attacks while entering on my first character before I understod what was going on!
Probably is associated with the Bolster buff.
this effect disapear after around rank 3-5

Submited by Lionbun - White Lion 
< WAR Veteran >

**Comment by Luth-RoR** [comment]
Please read the bugtracker rules, for example "use the search function before posting", "reports need evidence", "one bug per report" and "only bugs; no suggestions etc.".
