### ISSUE TITLE
RR45 engineer SC hammer is missing

### ISSUE THREAD

**Issue by grunbag** [WarEmu/WarBugs#9374]
According to this guide : 

https://gaarawarrgabs.wordpress.com/2010/06/03/the-weapons-of-war/#Cost

Engineer def hammer is missing from merchant ingame :

Sentry’s Trollsmasher of Glory
56.0 DPS, 2.4 Speed
21 Toughness
27 Wounds
20 Hit Points Every 4 Seconds
2% Reduced Armor Penetration
2% Reduction in being Critically Hit

Actually we only can buy def spanner and def rifle at merchant.

**Comment by grunbag** [comment]
Torque told me to report it on bug tracker 

https://www.returnofreckoning.com/forum/viewtopic.php?f=74&t=20561

**Comment by wargrimnir** [comment]
Update career req to include Engineer. Both Sniper weapons appear to be correct.
