### ISSUE TITLE
[SW] Assault Stance- Range Power not converted into Melee Power

### ISSUE THREAD

**Issue by Pxl555** [WarEmu/WarBugs#9375]
How it is supposed to behave:
![assault2](https://cloud.githubusercontent.com/assets/17297910/24244043/98259c5e-0fbd-11e7-9a93-269d090586af.png)

Getstats without assault stance:
![swscout](https://cloud.githubusercontent.com/assets/17297910/24244048/a48c1568-0fbd-11e7-8df0-52849a953d6b.png)

Getstats with assault stance:
![swassault](https://cloud.githubusercontent.com/assets/17297910/24244080/bc7aef78-0fbd-11e7-81f4-21ea4b784e7d.png)

Melee Power is missing from the .getstats when in assault  and your item's with range power do not seem to impact ability damage of melee abilities when in assault.

**Comment by Lileldys** [comment]
This also happens with Zealot/RP Converting Healing Power into Magic Power. Believe there is a ticket for that one somewhere.
