### ISSUE TITLE
Enduring Wrap item

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9378]
Not for BW? Same with #9349
![warhammer online age of reckoning 03 24 2017 - 18 59 56 206](https://cloud.githubusercontent.com/assets/16864486/24305046/4427c868-10c4-11e7-8ad6-8e2e284715dc.png)

**Comment by wargrimnir** [comment]
This is an Archmage healer cloak. I'm not making an exception for each healer cloak just because it has INT on it. They're just not standardized like that. 

BW can bugger off and WP can deal with it.
