### ISSUE TITLE
Unlearning Mastery ability on switching gear items.

### ISSUE THREAD

**Issue by Castrael** [WarEmu/WarBugs#9379]
Hello.

I am experienced a bug in which the mastery ability Wave of Scorn on my Blackguard is unlearned (as in ability disappears and I get the specialization point refunded) each time I put on a new item, weapon, jewelry or armor doesn't matter.

Regards
Castrael

**Comment by Luth-RoR** [comment]
This is a well known bug that can't be fixed atm. Use the addon "anywheretrainer".
