### ISSUE TITLE
Party members dots are not visible on the map

### ISSUE THREAD

**Issue by MrAngel0** [WarEmu/WarBugs#938]
Hi,

For some reason all these "blue dots" of the party members do not show on the map. The bug was spotted while I was managing RVMods Range API. Specifically "GetMapPointData" - the game UI API -  does not return details for the party members. This is though not the case for rest entities like the quest NPCs.

Example of the API call:
```PointData = GetMapPointData("EA_Window_WorldMapZoneViewMapDisplay", PointIndex);```

I believe the map points data is not activated somehow, or server should send that information.

Regards.

**Comment by Evildoor** [comment]
Status? The dots seem to be working most of the time.

**Comment by Evildoor** [comment]
No response, closing.
