### ISSUE TITLE
Epic Quest "Will of the Warboss" Roadblock

### ISSUE THREAD

**Issue by grackstub** [WarEmu/WarBugs#9381]
In the third step of the epic questline "Will of the Warboss" you are required to kill 8 Moonfang Headhittas and 6 Moonfang Stickpointas. Others have reported this quest working as intended in the past, and videos have shown it being possible to complete, but as of now there are no Stickpointa NPCs to kill, only Headhittas, and so the questline can't continue.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/9352
