### ISSUE TITLE
Annihilation - Reiksguard Cannoneers

### ISSUE THREAD

**Issue by Lileldys** [WarEmu/WarBugs#9386]
Hello,

Since the recent update to fix the PQs, the following issues have arrised with the Emp Epic Quest, when you need to enter the PQ "Reiksguard Training Grounds" to kill Duke Wickham, Reiksguard Cannoneers and Reiksguard Defenders.

The first issue is that you now need to progress the PQ to stage two where you are able to kill Reiksguard Cannoneers, which is tedious requiring 50 mob kills on a fairlyscattered foe.

Secondly, all the Cannoneers are now champions, so once you grind the 50 Reiks Knights you've then got to tediously kill 5 champs, which are scattered around other mobs.

This quest was do-able before patch on a WE, but now its just taking forever on a Melee DoK...

**Comment by Razielhell** [comment]
Fixed in next. Added Reiksguard Cannoneers and Reiksguard Defenders near the PQ.
