### ISSUE TITLE
Didn't receive mail with oRvR reward bag.

### ISSUE THREAD

**Issue by Shyntiara** [WarEmu/WarBugs#9388]
Heya, after locking Praag map 26.3. around 19:40 CET my order char Shyntiara ended up 5th in contri, 7th after rolls - earned blue bag but never received it in mail. Relog didn't help.

**Comment by Razielhell** [comment]
Maybe https://www.returnofreckoning.com/forum/viewtopic.php?f=2&t=20514 ?

**Comment by Razielhell** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=2&t=20514

**Comment by Shyntiara** [comment]
Ah right, missed that. Thank you.
