### ISSUE TITLE
Change Tactics when in combat

### ISSUE THREAD

**Issue by Ghatisgob** [WarEmu/WarBugs#9391]
Hello, i was in Caledor with some friends and during an endless fight, i noticed that i could change my tactic set.
Here is a screenshot to demonstrate the issue
![ghatisgob_002](https://cloud.githubusercontent.com/assets/25305100/24363386/01d92864-1310-11e7-8cd9-aea5930b4c09.jpg)

**Comment by Luth-RoR** [comment]
And this it did not just happen visually because of some addon?

**Comment by Ghatisgob** [comment]
This happened only once, but during this time, i could change my tactics as i want.
I did this report because all my addons are working perfectly (green) and its weird.

**Comment by Luth-RoR** [comment]
Yes, very strange indeed; maybe others encountered it too.

**Comment by Luth-RoR** [comment]
From https://github.com/WarEmu/WarBugs/issues/9424
>So i did some testing with my AM friend and we figured it out

>here is a test before hurried res
![sybella_046](https://cloud.githubusercontent.com/assets/19709971/24587200/18e48aa2-1767-11e7-8c2f-f4d327a216ad.jpg)
![sybella_047](https://cloud.githubusercontent.com/assets/19709971/24587202/27c3560c-1767-11e7-9578-9cf5fa9c09a3.jpg)
To completely recreate this glitch, you cant just do hurried res, you have to use RESOLUTE DEFENCE before you hurried res, which allows infinite switching of tactics in combat.

**Comment by Luth-RoR** [comment]
From https://github.com/WarEmu/WarBugs/issues/9431#issue-218829714

>Tested it with zealot shaman and dok, both self resurrect and normal resurrection does the trick and its not visual bug only. here are the videos;

>Zealot: https://youtu.be/85VQ5F7hNCw
Shaman: https://youtu.be/zvfpyLTX_kI
Dok: https://youtu.be/UMRS7hkmIkY

>will test it furthermore and post the results.

**Comment by Luth-RoR** [comment]
From https://github.com/WarEmu/WarBugs/issues/9431#issuecomment-291050383
>2 more tests on why it happens; https://youtu.be/wUTMheIkMf4 and https://youtu.be/sfLaldEz0Ns, if you pick the resurrection fast and get back in combat, before you see the - combat text which pops after 10 seconds, it will allow you to change tactics.(also horsewhisperer had one - combat text right when he died and another one after 10 seconds. have to take the res and hit someone between those 2 to make the bug happen.

**Comment by Luth-RoR** [comment]
>https://github.com/WarEmu/WarBugs/issues/9431#issuecomment-291050383
>So basically, after you die, you have to wait 10 seconds to change your tactics but if you get resurrected before that, it will allow you to change your tactics as soon as you resurrect and if you get in combat before 10 seconds you wont get +combat text.

**Comment by Luth-RoR** [comment]
From https://github.com/WarEmu/WarBugs/issues/9431#issuecomment-291052122
>https://youtu.be/K9fsW8cV4aA the version with self resurrect also /bug is clearest seen here:P

**Comment by Luth-RoR** [comment]
From https://github.com/WarEmu/WarBugs/issues/9431#issuecomment-291056608
>I made a video attempting these glitches it worked with AM but not RP https://youtu.be/QkqUGVRfcdQ
i think i was to slow with the RP

**Comment by Luth-RoR** [comment]
From https://github.com/WarEmu/WarBugs/issues/9431#issuecomment-291197147
>yes its about how fast you take it, shaman/am insta res sure makes it easier but not the actual reason since it works for all healers

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/9720
