### ISSUE TITLE
(Choppa) (Tactic) Don't Wanna Live Foreva:  Not getting Parry increase from extra WS.

### ISSUE THREAD

**Issue by Regicyde** [WarEmu/WarBugs#9392]
My Parry stays the same with the tactic being used or not. Should be a 4 to 5% increase in Parry I'm guessing.

![dwlf](https://cloud.githubusercontent.com/assets/19365956/24381167/b7ac2b12-1303-11e7-8ea7-b8fb3db09bb9.png)

With Tactic:

![with](https://cloud.githubusercontent.com/assets/19365956/24381186/d3846f02-1303-11e7-9392-124d9bc9ae2d.png)

Without Tactic:

![without](https://cloud.githubusercontent.com/assets/19365956/24381197/de1201e6-1303-11e7-9e93-7d6475771532.png)

**Comment by Luth-RoR** [comment]
Parry from weaponskill is not shown with .getstats, because it's calculated against the attackers strength (which lowers the parry chance again). It changes dynamically, depending on the enemy attacking you.
