### ISSUE TITLE
Battle for Praag / Gromril Crossing IndexOutOfRangeException

### ISSUE THREAD

**Issue by anarchypark** [WarEmu/WarBugs#9393]
once last flag is opened to capture,
after that point you can capture it anytime, no matter flag sequence.
so it's possible that 2 different flags are on timer by each realm.
for example, in Gromril Crossing
Pilo O' Warstuff flag is on timer by Destruction
Order capture Da Base Camp flag ( it was opened before )
after both timers up one flag disappear with
[] says: IndexOutOfRangeException was thrown from GivePoint. This object will be destroyed.

**Comment by Luth-RoR** [comment]
Known and merged with https://github.com/WarEmu/WarBugs/issues/7237
