### ISSUE TITLE
Quests in Altdorf

### ISSUE THREAD

**Issue by mamabunny03** [WarEmu/WarBugs#9396]
Hello, 

Just a quick blurb about a few quests in Altdorf that do not seem to work properly. First is "The Devil Inside".  The second is "Chapter 3: The Trail of Bones".  and the third and final one is killing rats in the sewers of Altdorf (but i know that one wont work until we have dungeons up so im not concerned with that one). For The Devil Inside i have talked to the crazy peasant but can not attack. For trail of Bones the guy is just missing.
 
![zoeybird_010](https://cloud.githubusercontent.com/assets/26738830/24401611/0c90e486-1383-11e7-9e3b-9eceec663154.jpg)
![zoeybird_011](https://cloud.githubusercontent.com/assets/26738830/24401610/0c8edd30-1383-11e7-942c-8fafaaa4aa79.jpg)

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/2303
Quests are just not implemented yet and one bug per report in the future please.
