### ISSUE TITLE
Galiron's Mouth - Public Quest Dark Elf Chapter 18

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9398]
- [ ] On stage 1 killing Dragonwake Sentinel rewards you Influence **only on Log** for this PQ.(**Doesnt count the kills**) 
## Looks like that those kills are registered for Keeper's Vigil PQ Stage 1. #9399
- [ ] On stage 2 not all rocks work.

**Comment by grunbag** [comment]
Fixed on next patch
