### ISSUE TITLE
Keeper's Vigil - Public Quest Dark Elf Chapter 18

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9399]
- [ ] Stage 1 Kills[Dragonwake Sentinel] can be registered from Galiron's Mouth PQ. 
**Influence doesnt fill up in ToK.** 
#9398

**Comment by grunbag** [comment]
fixed on next patch

**Comment by Akenatoth** [comment]
I don't know if this is due to the PQ or not, but I just soloed it on 19 Jan 2018 and I didn't get influence from it.
