### ISSUE TITLE
[Quest] "Woebegone" Part 3 - Quest item is not removed upon completion

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#94]
For this quest you are required to kill "Kruk'tar" and claim the "Bugman's XXXXXX" barrel. Then return it to "Orgni Stouthammer". He should then take the barrel from your backpack, but it is still there upon completion of the quest.

***NOTE***

Just a thought. Are we going to look into the backpack tabs "Currency, Crafting and quest items"? Quest items and crafting items are put into the general tab of the backpack.

![bugman s xxxxxx](https://cloud.githubusercontent.com/assets/7492543/2926391/e47d865e-d75b-11e3-8b53-a402bf4ab9f7.png)

**Comment by Reggaewaldo** [comment]
The quest item is now put in your quest item backpack. But still not removed.

**Comment by Evildoor** [comment]
Closing as a particular case of #282.
