### ISSUE TITLE
Rain of Fire - Public Quest Chaos Chapter 20 

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9405]
- [x] Stage 1 doesnt count kills.

**Comment by orfeaskappa** [comment]
Stage 1 of  Ambush at Garrisonburg Doesnt count kills too.(and of course gives no influnence)

**Comment by Razielhell** [comment]
Nothing to do with Rain of Fire though. Make a new ticket please.

**Comment by grunbag** [comment]
Fixed on next patch
