### ISSUE TITLE
Dark Retribution - Public Quest Chaos Chapter 20

### ISSUE THREAD

**Issue by Razielhell** [WarEmu/WarBugs#9406]
- [ ] There are several Holyhelm double spawns on Stage 1.
- [ ] Stage 2 is skipped.

**Comment by Wulfbayne** [comment]
Within Stage 3 the statues on the top floor of the cathedral are not clickable thus preventing the completion of stage 3.

**Comment by grunbag** [comment]
fixed in next patch
