### ISSUE TITLE
Bag is bugged, Choosing to open a sc logs you off

### ISSUE THREAD

**Issue by Dratsummr** [WarEmu/WarBugs#941]
Bag shows nothing when opening. Items are white. When choosing a tab the bag freezes. 

When joining an sc it promptly logs you off. Selecting play on character screen then allows you to join the sc.
![diem_003](https://cloud.githubusercontent.com/assets/13211474/8537566/6ffa43ee-2426-11e5-868b-a3c43f9fd737.jpg)

**Comment by shamallow** [comment]
i've just had the same problem
![image](https://cloud.githubusercontent.com/assets/16374367/12523897/d8d5ceb2-c159-11e5-98cf-3afb67edd0cb.png)

**Comment by Dratsummr** [comment]
The Fix: Made a character of the same class. Deleted old "EA_BackpackWindow" found in Warhammer folder under user,settings,MaryrsSquare, "CharactersName". Replaced "EA_BackpackWindow" with new one found on New Characters profile folder. 

Everything works as it should now.

http://www.returnofreckoning.com/forum/viewtopic.php?t=4828

**Comment by Evildoor** [comment]
Closing since the problem was resolved in this case and wasn't reported since then by anyone else.
