### ISSUE TITLE
BL quest

### ISSUE THREAD

**Issue by rayzrblayde** [WarEmu/WarBugs#9410]
i have finished the beastlord engineer quest and cannot turn it in. i have already turned it in and picked up the coin so i had thought i can no longer talk to Wotgrok Da Weird to turn it in. i currently only have 4 coins and have finished the quest. i have relogged and the server has reset before coming here to try and get it fixed.

**Comment by wargrimnir** [comment]
Do the Elf quest again for your 5th token. That's why it was made to be repeatable, in case players had a quest bug out like this.
