### ISSUE TITLE
Magus Indigo fire of change on keep lords

### ISSUE THREAD

**Issue by andarkk** [WarEmu/WarBugs#9412]
The magus cast indigo fire of change don't function on keep lords. Cast bar start and istant stop.
Tested it on 3 keep lords atm

**Comment by milosxe** [comment]
Iirc there's a limit to the number of debuffs that a target can have at any given moment. At some point you won't be able to dot a Lord if the force is big enough, and you can't use channel attacks cause they also add an effect on the target. Only direct dmg abilities.

**Comment by andarkk** [comment]
but indigo fire of change don't apply any dot/debuff and i think is direct damage...
Btw is a bug or work as intended?

**Comment by milosxe** [comment]
Yes, it doesn't apply dot/debuff, but it still shows on target as a dmging effect, and like I said, there's a limit on how many effects there can be on a target.

**Comment by milosxe** [comment]
https://github.com/WarEmu/WarBugs/issues/1469

**Comment by Luth-RoR** [comment]
Thanks, closing.
