### ISSUE TITLE
[Appearance] Gholnaros' Warhammer skin cant be used in Appearance window

### ISSUE THREAD

**Issue by Osgrim** [WarEmu/WarBugs#9414]
I cant seem to use the weapons appearance despite saying it was allowed. 

![osgrim_006](https://cloud.githubusercontent.com/assets/22075763/24427216/11e59df8-1402-11e7-850e-ca4abd7eb221.jpg)

**Comment by k0ut4l1** [comment]
great hammer and great axe.

**Comment by Osgrim** [comment]
close this bug.
