### ISSUE TITLE
Questgiver jump's on horse

### ISSUE THREAD

**Issue by Tykros** [WarEmu/WarBugs#9416]
Was riding in T3 Emp WC when I saw a questgiver running across the camp. When I ran over him he jumped on my horse. (see picture) 
Game crashed when I left the WC on PVE-side (don't know if this is related).

![questgiver jumps on horse](https://cloud.githubusercontent.com/assets/25689339/24462125/77e6a8c6-14a3-11e7-961e-7c4a8a5a5a6a.png)

**Comment by Luth-RoR** [comment]
Known https://github.com/WarEmu/WarBugs/issues/7292
