### ISSUE TITLE
Ram Disappearing bug in high pass

### ISSUE THREAD

**Issue by bridledname** [WarEmu/WarBugs#9418]
From time to time when you bring a ram from Passwatch castle (Talabecland) to high pass (where destruction keep stoneclaw castle is) it will disappear once you reach the bordering area where High pass and talabecland meet. the message "Ram has been destroyed" will pop up and you have to wait 10 minutes to buy another ram and hope that won't disappear too. (Happens if you buy from castle and not the warcamp)

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/8349
