### ISSUE TITLE
i can pass between a wall of artdolf

### ISSUE THREAD

**Issue by eldrad85** [WarEmu/WarBugs#9421]
ok, when i jump in to the wall, i can roam under all Artdolf, except some hole.
![fuenriel_013](https://cloud.githubusercontent.com/assets/26821965/24560247/425e77ec-1642-11e7-9a55-f9517c0667bd.jpg)
![fuenriel_014](https://cloud.githubusercontent.com/assets/26821965/24560508/59c69e40-1643-11e7-89a5-e39459876e3b.jpg)
![fuenriel_012](https://cloud.githubusercontent.com/assets/26821965/24560537/75e23aee-1643-11e7-97b3-c3b040f8d01d.jpg)

**Comment by Razielhell** [comment]
Old one. I think there is already one ticket for this one. Cant find it.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/4297
