### ISSUE TITLE
Magus's Daemons OP sometimes

### ISSUE THREAD

**Issue by WAR2014** [WarEmu/WarBugs#9422]
I had engi and Magus both for farming mobs. I figured sometimes daemons(magus) specially long range will over damaged/over power than Magus; but engi's turret doesn't had such as similar issue. Even both characters used same addons like Loyalpet and Petassist, and the setup are same like auto-attack character's target only. Sometimes the daemon can kill the mobs itself and my Magus can't loot and gathering. I'd tried both characters at difference area for test, the issue remain on Magus only. 

For solution on Magus, I will disable the Daemon(s) just use magus killing mobs until last stage of PQ the boss appear, then summon the range daemon and dot the boss first before daemon start on it :PP

**Comment by Luth-RoR** [comment]
Known and can happen sometimes https://github.com/WarEmu/WarBugs/issues/5039#issuecomment-212943186
