### ISSUE TITLE
Texture bug in nordland

### ISSUE THREAD

**Issue by ergreenMD** [WarEmu/WarBugs#9423]
Maybe it is known issue. . . . Have mention this bug few years ago on EU warhammer, then on RU, and now managed to reproduce it here. In nordland rvr lake, bo Nordland XI it is possible to get inside the ship; then you are free to cast and to do ranged attacks - enemies can target you, but can't see to cast or attack. Flag also can be used from inside. 
If necessary. I can explain how to reproduce it and get inside. Screenshots added.
![01](https://cloud.githubusercontent.com/assets/26840627/24580140/90f71d7c-170b-11e7-8c52-72e5cc834234.jpg)
![02](https://cloud.githubusercontent.com/assets/26840627/24580141/90f81362-170b-11e7-9e39-46b7f72591bf.jpg)
![03](https://cloud.githubusercontent.com/assets/26840627/24580144/90fe1bb8-170b-11e7-95db-7ad365c7ebe1.jpg)
![04](https://cloud.githubusercontent.com/assets/26840627/24580143/90fdceba-170b-11e7-879a-48e912d4482d.jpg)
![05](https://cloud.githubusercontent.com/assets/26840627/24580142/90fc1930-170b-11e7-8c99-4c87e99f73c3.jpg)

**Comment by Luth-RoR** [comment]
Client sided texture bug; can't be fixed yet.
