### ISSUE TITLE
Archemage "Hurried Restore" tactic allows the resurected to change tactics in combat

### ISSUE THREAD

**Issue by carmine3161** [WarEmu/WarBugs#9424]
![sybella_041](https://cloud.githubusercontent.com/assets/19709971/24585257/1b8e4b70-173b-11e7-9db8-1163163336bd.jpg)

**Comment by Luth-RoR** [comment]
Nice, maybe this is the answer to https://github.com/WarEmu/WarBugs/issues/9391

**Comment by carmine3161** [comment]
So i did some testing with my AM friend and we figured it out

here is a test before hurried res
![sybella_046](https://cloud.githubusercontent.com/assets/19709971/24587200/18e48aa2-1767-11e7-8c2f-f4d327a216ad.jpg)
![sybella_047](https://cloud.githubusercontent.com/assets/19709971/24587202/27c3560c-1767-11e7-9578-9cf5fa9c09a3.jpg)
To completely recreate this glitch, you cant just do hurried res, you have to use RESOLUTE DEFENCE before you hurried res, which allows infinite switching of tactics in combat.

**Comment by carmine3161** [comment]
I got ressed by an AM in an SC with out this setup and i was able to swap tactics in combat but didnt work outside sc's

**Comment by Luth-RoR** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/9391
