### ISSUE TITLE
You can mount while moving straight in water

### ISSUE THREAD

**Issue by carmine3161** [WarEmu/WarBugs#9425]
![sybella_044](https://cloud.githubusercontent.com/assets/19709971/24585289/e45bd432-173b-11e7-815d-94062443c7e4.jpg)
![sybella_043](https://cloud.githubusercontent.com/assets/19709971/24585290/ebc0f554-173b-11e7-91e7-f2612373fda9.jpg)

**Comment by Luth-RoR** [comment]
Known and atm unknown how to fix https://github.com/WarEmu/WarBugs/issues/1540#issuecomment-143696947 and https://github.com/WarEmu/WarBugs/issues/798#issuecomment-116021655
