### ISSUE TITLE
Skaven tunnels in Kadrin Valley

### ISSUE THREAD

**Issue by lawfol** [WarEmu/WarBugs#9426]
The tunnels are operational,but I see a big difference in roder and destruction tunnels: the order one is BEHIND the warcamp so pretty hard to reach by destruction (if at all).
The destruction one can easily be reached by one of the ramps up to pve, as there is only one guard and if one stays on the other side it does not even aggro.
So basically order has two tunnels for redeployment and could even try to block the destruction one( it is also reachable from rvr area going up the hill south/east of Cairn BO)
Pretty sure some champs should be placed there or the destru tunnel relocated BEFORE the crying game of order bias starts.

**Comment by Torquemadra** [comment]
The bugtracker is not for opinions, take it to suggestions on the forums.
