### ISSUE TITLE
T1 epic quest Dwarf Stout and Bitter

### ISSUE THREAD

**Issue by WAR2014** [WarEmu/WarBugs#9427]
I can't find any info from our wikis secter so I do my searching on hammerwiki and try to get this quest done. But when reached to stage XII at Mt Bloodhorn ch6 camp, the quest descrition was require 1 opjective: Raid Thwarted. But there's nothing come to attack the camp, I think the quest was bugged on this stage. I don't know how to link an screenshot here, so apologize for that. But I link the hammerwiki here for further info: 
http://warhammeronline.wikia.com/wiki/Stout_and_Bitter_XII

**Comment by Luth-RoR** [comment]
Mob spawn scripting is not implemented yet https://github.com/WarEmu/WarBugs/issues/7940#issuecomment-250443105
