### ISSUE TITLE
Target with multiple snares no longer snared when (only) the first is cleansed

### ISSUE THREAD

**Issue by Zealote** [WarEmu/WarBugs#943]
Not 100% sure on this, I just thought I noticed it happening before - after cleansing one snare, ally seemed to be moving at normal speed even though they had a second snare on them. Afaik, the 2nd one should kick in when the 1st ends or is removed.

Don't know if it happens when first snare naturally reaches the end of its duration.

Might be a general issue related to https://github.com/WarEmu/WarBugs/issues/823

**Comment by ozarmidrashim** [comment]
Suspected this might be the case. Will test when back.

**Comment by Silentguard** [comment]
Confirm. Removing one of SW snare ignore effect of second.

**Comment by ozarmidrashim** [comment]
Fixed in next.
