### ISSUE TITLE
Being resurected By RP in SC allows you to switch tactics in combat

### ISSUE THREAD

**Issue by carmine3161** [WarEmu/WarBugs#9430]
![sybella_049](https://cloud.githubusercontent.com/assets/19709971/24593105/d4ab55a0-17d4-11e7-9609-a5260e427823.jpg)
Ill do some more investigating on this issue when i can but every time i get ressed by RP's in SC's i can switch tactics freely in combat

**Comment by carmine3161** [comment]
My group and i experienced the same results with AM

**Comment by cimator** [comment]
I just tested it with zealot self resurrect on other players, target has to be in combat upon dying and when self resurrected, he can change tactics in combat, will post a video of it soon. Doesnt work in normal resurrections

**Comment by cimator** [comment]
Tested it with zealot, both self resurrect and normal resurrection does the trick and its not visual bug only. https://youtu.be/85VQ5F7hNCw here is the link, will test it with dok and shaman soon also.

**Comment by cimator** [comment]
Shaman version(works): https://youtu.be/zvfpyLTX_kI

**Comment by cimator** [comment]
Dok version(works): https://youtu.be/UMRS7hkmIkY , seems it works for every resurrection actually but need to get back in combat fast after the res

**Comment by carmine3161** [comment]
I will make a video of Order side healers

**Comment by Luth-RoR** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/9391
