### ISSUE TITLE
Able to change tactics in combat and how to do it.

### ISSUE THREAD

**Issue by cimator** [WarEmu/WarBugs#9431]
Tested it with zealot shaman and dok, both self resurrect and normal resurrection does the trick and its not visual bug only. here are the videos;

Zealot: https://youtu.be/85VQ5F7hNCw
Shaman: https://youtu.be/zvfpyLTX_kI
Dok: https://youtu.be/UMRS7hkmIkY

will test it furthermore and post the results.

**Comment by cimator** [comment]
2 more tests on why it happens; if you pick the resurrection fast and get back in combat, before you see the - combat text that pops after 10seconds, and it will bug it out.(also horse had one - combat text right when he died and another one after 10 seconds. have to take the res and hit someone between those 2 to make the bug happen.

**Comment by cimator** [comment]
So basically, after you die, you have to wait 10 seconds to change your tactics but if you get resurrected before that, it will allow you to change your tactics as soon as you resurrect.

**Comment by cimator** [comment]
https://youtu.be/K9fsW8cV4aA the version with self resurrect also

**Comment by cimator** [comment]
#9430  #9424  #9391

**Comment by carmine3161** [comment]
I made a video attempting these glitches it worked with AM but not RP https://youtu.be/QkqUGVRfcdQ
i think i was to slow with the RP

**Comment by cimator** [comment]
yes its about how fast you take it, shaman/am insta res sure makes it easier but not the actual reason since it works for all healers

**Comment by Luth-RoR** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/9391
