### ISSUE TITLE
Iron Contraption speed bug

### ISSUE THREAD

**Issue by giugiugau** [WarEmu/WarBugs#9433]
As a Dwarf Engineer, when I step into the water and then come out, while using an Iron Contraption mount, my characheter retain the speed of the Iron Contraption while I'm on foot. Activating the mount again while on foot the charachter does the dismount animation

**Comment by Luth-RoR** [comment]
That's know and can't be fixed atm.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/798#issuecomment-116021655
https://github.com/WarEmu/WarBugs/issues/1540#issuecomment-143696947
