### ISSUE TITLE
Blood of the Black Cairn SC glitch

### ISSUE THREAD

**Issue by SardonicWrath9** [WarEmu/WarBugs#9434]
I was playing in the Blood of the Black Cairn Scenario and I got knocked back into the fountain structure where I went through the wall and glitched inside of the fountain, the fountain is directly to the left as soon as the scenario starts on Destruction side thought this was worth noting since I'm not exactly sure if it's a known glitch but it sucked being stuck inside for the rest of the match.  -Diabaal Worldeater

**Comment by Luth-RoR** [comment]
This is a problem with the mythic 1.4.8 client, which can't be modified yet.
