### ISSUE TITLE
Falling area in the middle of bo in Eataine

### ISSUE THREAD

**Issue by SATANICOMODERNO** [WarEmu/WarBugs#9435]
Hello guys, I found this spot when getting back to wc. I was ridnig and just passed over it and died as if i have fallen. I believe the screenshot can say more than I. 
![lirianna_002](https://cloud.githubusercontent.com/assets/14305777/24636386/40b317fc-18b0-11e7-803c-d8c58e0a188a.jpg)

**Comment by cimator** [comment]
Known bug probably, happens in a lot of places.

**Comment by Luth-RoR** [comment]
Yes, some spots in scenarios have been temporarily fixed by placing game objects there, but afaik the root of the problem is still unknown.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/8564#issuecomment-292964336
