### ISSUE TITLE
REMOVE BUFFS

### ISSUE THREAD

**Issue by geolyk** [WarEmu/WarBugs#9439]
Hello
i want to report a bug...that if you want to remove one buff from you you cant with the right click 
i want to do BL bosses and i want to remove the dots and i couldnt
![koukou_001](https://cloud.githubusercontent.com/assets/26933999/24718058/4791387c-1a3d-11e7-92cc-89f09171a79e.jpg)

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/916
