### ISSUE TITLE
Quest Broken

### ISSUE THREAD

**Issue by BreakfastGaming** [WarEmu/WarBugs#9442]
The Blighted Hopes quest will not complete.

**Comment by sioding** [comment]
**Thanks for the report.** Since there is no confirmation, i will close this issue now. Please make sure to follow the bugtracker rules which you can find here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)

**Comment by torlan-hub** [comment]
Sorry to bother, I too am currently having issue with the "Blighted Hopes" quest.
As seen in the screenshot, it says <Collect samples of tainted grain from Plagued Farmers at the Blighted Farm...>, but there is no such kind of mobs in the Blighted Farms; you an find them in Blighted Hills, spot for the PQ"Plague in the wind". Anyway, even killing those farmers give no tainted grain, so the quest does not progress.
If it can be of any use, I'm trying to finish the quest on a rank 17 KoTBS.
Hope I gave you enough details on the issue.
Thanks in advance for looking into it.

**Comment by Lheana** [comment]
I won't reopen this ticket as this quest is currently not completable because I was working on it when there was the last patch, so the quest was half finished, and thus bugged. It is already fixed on dev server, and it will be working fine with the next patch.

**Comment by torlan-hub** [comment]
Ok, got it.
Thanks for checking and for the answer :)

**Comment by Lheana** [comment]
Feel free to comment here if it's not fixed with the next patch :)

**Comment by Hodds** [comment]
I am trying to attempt this quest myself, it seems to be still bugged, i am stuck on the same step, Tainted Grain Samples 0/6

**Comment by Lheana** [comment]
Even after the patch of today?

**Comment by Hodds** [comment]
I did not go back right away  after the patch at the start of the event, BUT as of 03/08/2020 it is working.

**Comment by Razielhell** [comment]
Not working 8th of September. Can't collect Grain Samples.

**Comment by Lheana** [comment]
It works fine.
![Lheawll_008](https://user-images.githubusercontent.com/11537611/92509275-49cd2f80-f20a-11ea-8af7-3fe624aa43d3.jpg)

**Comment by Razielhell** [comment]
Quest Description says at the Blighted Farm(which is PQ name), despite farmers being in the Plague on the Wind PQ.

**Comment by Lheana** [comment]
But the quest marker is fine and correctly indicates that it does not refer to the PQ with this name, but just another farm touched by the plague.
