### ISSUE TITLE
Talabec dam DC

### ISSUE THREAD

**Issue by Tellmar** [WarEmu/WarBugs#9443]
Short: Got DC when returning keg at talabec dam.

Hello. Not in 1st time when returning keg got disconect (stucked in animation of interacting with keg, everyone around stops and i can move about 20 seconds then serverlist screen) No suggestions of what cause it. Happening only at talabec dam, never get this kind of DC except when i loosing internet connection.

**Comment by Lheana** [comment]
Just had the same bug, don't know what causes that. I placed the keg, then everything stopped moving. And few seconds later I was disconnected. And I am sure it was not an internet problem as someone was playing with me on the same connection.

**Comment by Kaelang** [comment]
This SC has been around on a lot of rotations since this report was live. I've also just tested handing this WO in multiple times and don't have any issues with this. I'm going to close this report up as it's likely to have been fixed in the interim. 

Please re-open if this issue persists on live.
