### ISSUE TITLE
Beastlord Hunting Guide "Duplicate"

### ISSUE THREAD

**Issue by Pumatouch** [WarEmu/WarBugs#9446]
I have acquired two Hunting Guide pocket items, from repeating the killquest for tokens in Dragonwake. 
They do share a 30 minute cooldown, but a simple relog takes care of that, so that one may load a second pocket item ready for use in an upcoming battle.

**Comment by Luth-RoR** [comment]
Can you actually use it or is it just shown without a cooldown?

**Comment by Pumatouch** [comment]
After the relog it can be used, yes.

**Comment by Pumatouch** [comment]
In fact, one does not even have to reslot anything; the 2nd piece in the bag will activate first at any rate. After relogging, even though the cooldown will still show, you can go ahead and click the item you are actually wearing still, the only cooldown being present on the bagged item. The hotbar'd Hunting Guide will simply show a little "2", showing you got a stacked item, although they are not stackable.

**Comment by Pumatouch** [comment]
The bagged Guide, the equipped Guide and their representation in the hotbar.

![](http://i.imgur.com/onHt8jq.jpg)

Upon using the Guide;

![](http://i.imgur.com/BClBcXy.jpg)

After the relog it looks like so; 

![](http://i.imgur.com/s4rDOby.jpg)

The hotbar shows a CD but upon clicking it..

![](http://i.imgur.com/3VCJsNY.jpg)

The CD starts over as I just activated the second Guide.

**Comment by asdf92** [comment]
I have something to contribute to this
https://www.dropbox.com/s/60k1bbj35xcg6co/2018-03-03%2015-47-00.flv?dl=0

The cd gets glitched I used it twice in a single SC when I first found out of this, in this example it was on CD from previous use I joined a SC and used it again so its glitchy
