### ISSUE TITLE
Home Invasion quest in Altdorf is unable to be finished

### ISSUE THREAD

**Issue by carmine3161** [WarEmu/WarBugs#9449]
![sybella_001](https://cloud.githubusercontent.com/assets/19709971/24847613/db711472-1d76-11e7-9c0e-0995915ba8ed.jpg)
The NPC's required to finish the quest are unable to be targeted and cant be killed by the player, 2 Ruffians and 1 Ruffian leader, they are however kill-able by other NPC's and their names are revealed in chat

**Comment by Lheana** [comment]
Has been fixed with patch of 24 September 2017.
