### ISSUE TITLE
Merchants don't sell any items since last patch

### ISSUE THREAD

**Issue by ArdzofPT** [WarEmu/WarBugs#9450]
The merchant for the skaven token pet will dye my gear, but will not sell me a pet any more.
![ardz_001](https://cloud.githubusercontent.com/assets/15960258/24848534/fbf0c36e-1d7b-11e7-852e-a1be9fcd20f9.jpg)
![ardz_002](https://cloud.githubusercontent.com/assets/15960258/24848539/014a7418-1d7c-11e7-9aa4-6f5ddd0f606f.jpg)

**Comment by Luth-RoR** [comment]
Seems to be a general problem:
https://github.com/WarEmu/WarBugs/issues/9452
https://github.com/WarEmu/WarBugs/issues/9451

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/9457

**Comment by korwrath** [comment]
Skaven merchant order side is broken as well.
