### ISSUE TITLE
Black Orc + Conq Shoulders + Trophies

### ISSUE THREAD

**Issue by ragafury** [WarEmu/WarBugs#9456]
Trophies look glitchy on the conq spaulders for Black Orc.

![ragafury_039](https://cloud.githubusercontent.com/assets/26032314/24886264/a3dbef18-1e53-11e7-9e23-48a57f104190.jpg)
![ragafury_040](https://cloud.githubusercontent.com/assets/26032314/24886265/a3dd7734-1e53-11e7-9bee-ef17c6d351f6.jpg)
![ragafury_041](https://cloud.githubusercontent.com/assets/26032314/24886266/a3e12500-1e53-11e7-9a75-8cda964407a0.jpg)

**Comment by ragafury** [comment]
Oh side note. 
That are not the actual Conq shoulders. That are Ruin shoulders with alternate appereance, but I don't think it will have any impact.

**Comment by Torquemadra** [comment]
unable to do anything with it at this point.
