### ISSUE TITLE
Vendors in starting village Chaos

### ISSUE THREAD

**Issue by mamabunny03** [WarEmu/WarBugs#9457]
Trying to sell to vendors and cannot open to sell but i can dye items, very strange.
i tried to upload i video but the type is not supported.
![zoliby_007](https://cloud.githubusercontent.com/assets/26738830/24888865/7796b240-1e34-11e7-8b50-db6e4b69e8a8.jpg)
![zoliby_011](https://cloud.githubusercontent.com/assets/26738830/24888870/7e997bb8-1e34-11e7-92b7-edab5678693e.jpg)
![zoliby_012](https://cloud.githubusercontent.com/assets/26738830/24888876/817a63b0-1e34-11e7-92e7-830c5437ad92.jpg)

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/9450
