### ISSUE TITLE
R15 Green Chaos Axes

### ISSUE THREAD

**Issue by cimator** [WarEmu/WarBugs#9458]
![leakypants_037](https://cloud.githubusercontent.com/assets/17130290/24899216/246b8e0a-1ea8-11e7-97e0-882dc71cdacf.jpg)

One handed axe giving double the stats of the two hander, should be the opposite. Their dps seems buggy also, both has the same.

**Comment by wargrimnir** [comment]
Corrected stats and DPS on both.
