### ISSUE TITLE
Crash in Altdorf (Back to Windows) if you use the "Scroll of Altdorf" 

### ISSUE THREAD

**Issue by Fazon44** [WarEmu/WarBugs#9459]
Hi !

If you use the "Scroll of Altdorf" object, the Warhammer program closes after several seconds.
To unlock, you must type the "/stuck" command several times during loading in order to be teleported to Norsca
This problem does not exist if one arrives in Altdorf by the Sigmar's Hammer or the master of the flights.

![scroll](https://cloud.githubusercontent.com/assets/27313834/24934375/860ae1e2-1f1b-11e7-9828-07c4e504486a.jpg)

Fadasse Warrior Priest lvl 40

**Comment by carmine3161** [comment]
I use the Scroll and get teleported in front of the Auction house Npc's in the market, no crash for me.

**Comment by Luth-RoR** [comment]
Yes, for me neither. I just ported successfully from Thunder Mountain to altdorf via the scroll. 
It must be somthing else.
