### ISSUE TITLE
Unclickable npc giver Bred, Fed, and Led

### ISSUE THREAD

**Issue by Poochka** [WarEmu/WarBugs#9460]
Upon completing quest "Bred, Fed and Led" for blue cloak reward (with 2 empty sockets), I found quest giver npc named Thordis Valdar unclickable. So it is impossible to complete this quest right now.
Checked it with 3 characters overall and this quest cannot be started also.

**Comment by Torquemadra** [comment]
fixed

**Comment by WAR2014** [comment]
Can I ask where is the Ruin of Hazelhof belong at? The Map marked area is Knightly Riders (PQ), not the same name/area.
![default](https://user-images.githubusercontent.com/17757461/44088281-e9a8b014-a005-11e8-9132-268e6b1004c6.png)
