### ISSUE TITLE
Keep Lord Bug - Dragonwake

### ISSUE THREAD

**Issue by exxyx** [WarEmu/WarBugs#9461]
Atm it isnt possible to get or complete the kill quest from destros keep lord in dragonwake 
(Berran Venomtear)
if you scroll over that NPC, you have the icon of the speechbubble, but it doesnt show anything if you click on it

**Comment by Razielhell** [comment]
that's temporary and it happens randomly on characters. Once server reboots it will be ok for your char.

**Comment by exxyx** [comment]
ahh okay thank you. will close this thread then
