### ISSUE TITLE
Quest in Gates of Ekrund

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9464]
The scenario quest in Gates of Ekrund is not available. I think it's because it is not repeatable, as I remember I could have taken it once, but not more.

**Comment by Lheana** [comment]
I noticed it's only the destro quest. Order quest seems correctly repeatable.

**Comment by wargrimnir** [comment]
Need the quest name for these.

**Comment by Lheana** [comment]
Do quests have the same name on order and destro side ? Because as it is not possible to take the quest on destro side, it is not possible to know the name of a quest we can't see.

**Comment by Lheana** [comment]
The order Gates of Ekrund quest is called 'Battle at the Gates of Ekrund'.

**Comment by Ryanfawkez** [comment]
All Scenario quests are flagged as active and repeatable.
