### ISSUE TITLE
GameData.GetScenarioPlayerGroups() api will not return fresh and correct data

### ISSUE THREAD

**Issue by MrAngel0** [WarEmu/WarBugs#947]
Hello,

"GameData.GetScenarioPlayerGroups" api is using by the game UI. Specifically by the vanilla "ea_scenariogroupwindow" addon. The issue can be clear visible if checking Scenario Window - the health values are not correct.

Squared - the group frames addon - is also depends on that, and in scenarios does not showing correct healths either.

**Comment by ozarmidrashim** [comment]
We don't know what to send to make the client work correctly.
