### ISSUE TITLE
Grublug Onetoof Quests

### ISSUE THREAD

**Issue by l3liss** [WarEmu/WarBugs#9473]
I believe the quest provided by this NPC are not able to be completed due to the mobs not spawning. The monsters are supposed to be roaming across the zones but i have yet to be able to locate them after days of searching.

Ultimate Mushroom
Gnobble-Hide

Those are the 2 quests I'm referring too.

**Comment by Kabucoror** [comment]
The NPC walks around with next patch

**Comment by sioding** [comment]
fixed with patch from 10.06.2019
