### ISSUE TITLE
guild vanished

### ISSUE THREAD

**Issue by sufferkate** [WarEmu/WarBugs#9476]

**Comment by sufferkate** [comment]
lost my guild (sadist) after a server crash...once back on i'm no longer in my own guild. happened around 3:20ish (NA) central time.

**Comment by Kharash** [comment]
Same problem here my guild is gone (Armee der Finsternis)

**Comment by Celticwitch** [comment]
Other guilds gone are - The gentlemens club - and bloodstone clan

**Comment by Bonzoooo** [comment]
Same here. 

On the forum, they've said that they should come back after a restart. No clue when they'll restart.

**Comment by KillDezba** [comment]
I also lost my guild Crits R Us

**Comment by Bonzoooo** [comment]
Restart/Patch did not fix it for Fluffy Pink Bunnies and Crits R Us.

**Comment by mamabunny03** [comment]
Nordland Beach bums are also missing :(

**Comment by Mallakai** [comment]
Guild "Ghal-Maraz" is also deleted.
Waited for restart. Nothing happend :/

**Comment by whitehemull** [comment]
Same problem here. Retribution, order is still missing

**Comment by wargrimnir** [comment]
This is fixed now.
