### ISSUE TITLE
No renown ( inf /xp ) at zone lock since the patch 16/4/2017

### ISSUE THREAD

**Issue by Enarion** [WarEmu/WarBugs#9478]
Hi ,

Since this morning and the patch16/4/2017 i don't gain renown (neither inf or xp ), or gain some of the new currency described in the patch note, on zone lock  ( Praag , TM and DW ). Other menber of our warband have the same problem. Normal gain on fight , BO and on the Keep Lord death but nothng at the zone lock.
Could it be link with the change described in the patch note about renown at lock and aao ?
![sc004](https://cloud.githubusercontent.com/assets/19255238/25071633/bcb595d0-22bc-11e7-897e-586922d6d6e3.jpg)

Best regards
Enarion

**Comment by korwrath** [comment]
I have noticed with characters in guilds the inf/rp is nonexistant on a zone lock in t2/3, but unguilded chars get the inf/rp.  (Note: if you "are" in a guild but due to the bug showing you as guildless or yoru guild doesn't exist you seem to also lack the inf/rp)

**Comment by Luth-RoR** [comment]
Thanks a lot.

**Comment by Luth-RoR** [comment]
Guildless players getting renown/influence couldn't be reproduced by a dev.

**Comment by korwrath** [comment]
Don't know what to really say, just my dwarf chars, who are/"were" in Bitterstone Thunderers got zero info and RP last time I took them into the lakes after taking part in the zone cap.  My still guilded elfs (SW) had this happen as well..

**Comment by Enarion** [comment]
Hi,

Destro has just locking DW , and still no rp/inf/xp from the lock. I'm not guilded ( no the guild bug i was without guild before the patch ).
![dw_18042017](https://cloud.githubusercontent.com/assets/19255238/25149201/e6568256-247d-11e7-9d76-e5eac57db06f.jpg)

**Comment by Enarion** [comment]
Hi,
I thing i made a mistake with the bug tracker , the bug appear to be closed by me but it is not.
Best regards.


      De : Luth <notifications@github.com>
 À : WarEmu/WarBugs <WarBugs@noreply.github.com> 
Cc : Enarion <francois.hopin@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Mardi 18 avril 2017 18h11
 Objet : Re: [WarEmu/WarBugs] No renown ( inf /xp ) at zone lock since the patch 16/4/2017 (#9478)
   
Guildless players getting renown/influence couldn't be reproduced by a dev.—

**Comment by wargrimnir** [comment]
This is working now, confirmed today.
