### ISSUE TITLE
No group invite possible

### ISSUE THREAD

**Issue by Siggilinde** [WarEmu/WarBugs#9479]
1. i´m in  a full group. 
2. all me group members are leaving the group, so i´m allone.
3. i cant leave me own group cause  leaving group isn´t available.
4. no one can invite me in his group until i relog

**Comment by Luth-RoR** [comment]
Does this happen since last patch or happened also earlier?

**Comment by Siggilinde** [comment]
Didnt play in Groups for a while, so i can´t judge.
