### ISSUE TITLE
t2/t3 exp/rp 

### ISSUE THREAD

**Issue by koza2205** [WarEmu/WarBugs#9480]
hello there i would like to comment that when are you moving supplies from t2/t3 dwarf  zones while you move from skaven tunnels the exp and rp that you will get is extremely hight around8-10 k xp per supplie i check it on both badlands/blackfirepass  and barak varr/marshes of madness

**Comment by koza2205** [comment]
Hello again I try it again tomorrow and the results are the same

**Comment by sioding** [comment]
Since there is no evidence and we have a new ORvR System without players carrying the supllies i will close this now.
