### ISSUE TITLE
Flee with AP pot at the same time

### ISSUE THREAD

**Issue by Calarian** [WarEmu/WarBugs#9483]
Should this be used as an offensive skill? I've seen it used a lot where people will Flee then AP pot right away to catch there target and kill them. They get the benefit of the speed boost and the ability to attack as they bypass having no AP while Fleeing.

**Comment by Torquemadra** [comment]
prove this wasnt the case on live, otherwise it isnt a bug

**Comment by Luth-RoR** [comment]
I can confirm that it worked like this on the mythic server and is no bug; a design flaw to discuss on the forums.
