### ISSUE TITLE
Shaman tactic: Nuthin' but da waaagh!

### ISSUE THREAD

**Issue by cimator** [WarEmu/WarBugs#9485]
![leakybrains_000](https://cloud.githubusercontent.com/assets/17130290/25140168/1989f72c-2468-11e7-9960-c2d9c4750b13.jpg)
Tactic doesnt change anything since shaman absorb increases damage by %15 no matter you use the tactic for it or not.

https://youtu.be/YbZmWaM_euk  couldnt upload here :P

**Comment by Luth-RoR** [comment]
I tested it too and can confirm.

**Comment by Torquemadra** [comment]
fixed, thx
