### ISSUE TITLE
No armor un gold bug

### ISSUE THREAD

**Issue by Crowhunter** [WarEmu/WarBugs#9486]
Today is locked Praag. I got the 1st place and a gold bag. But there is no armor in the choice
![mefistofeles_004](https://cloud.githubusercontent.com/assets/27734733/25142759/c1f30dce-2470-11e7-973b-d7f3779ec1ed.jpg)

**Comment by Razielhell** [comment]
Maybe this? https://www.returnofreckoning.com/forum/viewtopic.php?f=2&t=20514

**Comment by Crowhunter** [comment]
I am disappointed ((
