### ISSUE TITLE
King quests don't seem balanced to Rank

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#9487]
A couple quests I notice refer my (rank 40) to T3 RvR locations.
Honor's Guard - refers me to Avelorn and Saphery
Finding the Strength - refers me to Shadowlands and Ellyrion
The Green Menace - refers me to Blackfire Pass or Badlands

possible solution - tweak the quest to be any Tier for the suggested pairing
or else enable rank restriction for the quest to end after T3 ranks.

**Comment by Luth-RoR** [comment]
They seemed to have a max. level requirement according to
_Here is a list of basic quests in Altdorf that can be completed by characters of rank 11 to 20._ 
http://warhammeronline.wikia.com/wiki/Altdorf_Quests_2
_Here is a list of basic quests in Altdorf that can be completed by characters of rank 21 to 30._ 
http://warhammeronline.wikia.com/wiki/Altdorf_Quests_3

But as we have a downbolster mechanic, a max. level req. makes no sense.
