### ISSUE TITLE
[Quest][Chaos] "Chosen" (chapt. 8) - Quest objective can't be completed

### ISSUE THREAD

**Issue by lennip** [WarEmu/WarBugs#9488]
This is actually an update of #8683 which was closed but doesn't seem to have been fixed - sorry for the duplicate post but I'm not sure how to ask for a closed issue to be reopened or re-checked.

The problem happens in one of the last parts of the quest chain "Chosen" (Chaos chapter 8). The quest objectives are as follows:
![mutty_002](https://cloud.githubusercontent.com/assets/2891053/25180032/ae1d3ae4-250c-11e7-8f49-c18d9eab2684.jpg)
I killed Dredvulos and obtained the Darkflame Scepter, that one validates normally.
However, the other quest objective is to find the Altar of the Scepter, but it can't be completed: there is indeed a clickable altar at the given location, but clicking it does nothing, it does not trigger the validation of the corresponding quest objective as expected:
![mutty_001](https://cloud.githubusercontent.com/assets/2891053/25179308/9850c49a-2509-11e7-94b1-984788092f88.jpg)

And of course, I tried interacting with the altar while standing next to it, not from as far as it appears in that screenshot ;)

**Comment by v1p4** [comment]
The Quest description is absolutely a mess!

Go back to the Questgiver to get the reward:
http://imgur.com/a/VPYum

**Comment by wargrimnir** [comment]
Fixed, either altar will work now.
