### ISSUE TITLE
scenario exp/rr bug

### ISSUE THREAD

**Issue by omegachief** [WarEmu/WarBugs#949]
Joining scenario party and after using
  /stuck command in scenario or book of binding in scenario -
player gets teleported to starting zone as chicken , but not get kicked from scenario warband. After waiting for scenario end,  get full exp and renown bonus reward from completing scenario , ammount of exp and rr deepends if his team won or lost game.
After clicking end game on scenario score board , player get moved to place from where he clicked accept to join scenario map .
edit:
player can attack mobs and heal (outside scenario) and it will contribute to scoreboard

**Comment by Evildoor** [comment]
It seems that 

> player get moved to place from where he clicked accept to join scenario map

no longer occurs. #2607 describes current behavior.
