### ISSUE TITLE
"No End Of Danger" quest (High Pass / Order)

### ISSUE THREAD

**Issue by banned85** [WarEmu/WarBugs#9491]
In this quest You must kill one tundratusk, five shiftpaw wolves, five shiftclaw wolves and five moltclaw eagles

the problem is that when you kill any SHIFTCLAW WOLF the computer do not notice this (You can kill and kill them and You still will be have 0/5) so You cant finish the quest

cya

**Comment by wargrimnir** [comment]
Killing Shiftclaw Wolf should now advance properly.
