### ISSUE TITLE
Bug with melee speed on conq/WL shoulder

### ISSUE THREAD

**Issue by Lithriella** [WarEmu/WarBugs#9492]
Heya.
I notice something on my WL after I got the conq shoulders on then my melee speed went up to 8.8 and it was on 2.1 before. So it could be nice if it could be fix. Because the auto attack gets way slower when I take them on
![lithriella_006](https://cloud.githubusercontent.com/assets/27835347/25256930/b97ffaba-2634-11e7-950e-54b965a8e821.jpg)
![lithriella_007](https://cloud.githubusercontent.com/assets/27835347/25256931/b9860df6-2634-11e7-97d6-220ca8a39119.jpg)

**Comment by Luth-RoR** [comment]
Character window is buggy, type .getstats in the chat window instead.
