### ISSUE TITLE
issue logging 

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#9493]
![tesq_209](https://cloud.githubusercontent.com/assets/7527415/25268124/d49ec0fe-2677-11e7-8525-2b65f3e77de0.jpg)
![tesq_208](https://cloud.githubusercontent.com/assets/7527415/25268133/d99bbfa8-2677-11e7-9b64-50d094d08f34.jpg)

all my chars seems have logging issue, yesterday i played normally, when i log in with any they are dead, not loading equip and bag but they have /show equipped gear in logging menu.
(look in chat first screenshot for more detail)

EDIT: seems that my t1 + out of guild toons are not affected by this
EDIT: seems a guild related problem
EDIT: leave the guild (and restart the client) solve the problem but idk if you can then safe re join it.

**Comment by Akilinus** [comment]
Same problem for me. Account name: Akilinus, sh:Nosexak

**Comment by wiscel** [comment]
Same on all my characters. Also all abilities, tactics and morals are gone.
Account name: wiscel

**Comment by Tesq** [comment]
.....mm maybe leave the guild will help? could it be another guild related problem?

**Comment by Akilinus** [comment]
Maybe logged on to one of my toons whos not in a guild and it worked fine

**Comment by Akilinus** [comment]
Maybe. I could also log onto one of my toon thats not in a guild

**Comment by manglik** [comment]
Same problem. Checked on 3 computers already and it's still the same. Black screen when i log on 2 of my characters - Astral and Oioi. Other characters seems working fine. Searched a lots of topics, reinstalled game, nothing working.

**Comment by manglik** [comment]
Might be guild problems because my characters outside guild working, only ones in guild won't work (guild - TUP).

**Comment by Akilinus** [comment]
Could not leave the guild in Norsca. Also in TUP

**Comment by Tesq** [comment]
Yes my magus wich remained by long time out of guild work

**Comment by Akilinus** [comment]
Okay apparently I left the guild now. So that seems to fix it. Press leave the guild and restart that worked for me

**Comment by wargrimnir** [comment]
TUP and Nazgul have an invalid Alliance setup. I've removed them, but it will need a reboot to apply. Next time the zones lock.

**Comment by wargrimnir** [comment]
Server has booted, try logging in now.

**Comment by Tesq** [comment]
will see tomorrow
