### ISSUE TITLE
An enemy's race "Destroyer" Trophy.

### ISSUE THREAD

**Issue by Antalor** [WarEmu/WarBugs#9494]
Good afternoon.
Well, I knowed about it before, but I decided to post a issue about after I asked out a GM (Thanks Alena). Well, so there is a Tome Trophy Librarian in the Library which offers you to obtain a Destroyer Trophy which you earn after a specific race kill. (e.g. 1000 greenskins; 1000 dwarfs). So basically I already made it on my Order toon. I've killed enough of them (1000+ for every race) to obtain a normal One Pip and Golden One Pip trophy. (Two Pip and Three Pip you get after more race kills unlocks). I've already took the Greenskins and Chaos normal and golden ones but actually I can't do that on the Dark Elf trophies. Same problem with normal and golden One Pip trophy. Can't take it and equip. It seems for bugged. Also... On my Destro toon which got even way more kills same problem occur.
Greetings and have a nice day.
![frw](https://cloud.githubusercontent.com/assets/13917674/25277626/c320fc34-269f-11e7-8228-f68b07c7eb0e.png)
![frw2](https://cloud.githubusercontent.com/assets/13917674/25277662/e68c6762-269f-11e7-89fa-147a9aa6aa91.png)

**Comment by Lheana** [comment]
Should be fixed in next patch.
