### ISSUE TITLE
Stuck area

### ISSUE THREAD

**Issue by SATANICOMODERNO** [WarEmu/WarBugs#9497]
This is a terrible area to get stuck in Nordenwatch sc. This spot is near the Fortress flag, I don't know if you guys look for stuck areas to solve it, but I'm reporting this spot anyway for registration. 

![hielenia_000](https://cloud.githubusercontent.com/assets/14305777/25296799/77810d70-26c0-11e7-893f-4162ef42440f.jpg)
![hielenia_001](https://cloud.githubusercontent.com/assets/14305777/25296801/816ca042-26c0-11e7-9265-ede8524a7708.jpg)

**Comment by wargrimnir** [comment]
I never liked that lamp post anyway.
