### ISSUE TITLE
Keep siege engines lootable by defending faction

### ISSUE THREAD

**Issue by LordCarve** [WarEmu/WarBugs#9498]
Siege engines that are automatically deployed on walls on reaching certain keep ranks, after being destroyed drop loot that can be picked up by friendly faction. Possibly related #6463

The dropped loot, apart from coins and general drops, also involve items usable by opposing side, as if it was meant to be lootable by enemies only. This leads me to a suspicion that it being lootable by allies is a mistake, hence this report.

Pictured below _Precursor Darkboots_ (Chosen only) looted from a friendly destroyed _Heavy High Elf Ballista_ on Order side:
![darkboots_order](https://cloud.githubusercontent.com/assets/27449516/25304171/00906614-2762-11e7-96d8-9079f92986dd.jpg)

Notes:
- tested only on Order side
- happened in both Black Crag and Caledor so most likely a general issue not limited to a certain region/keep

**Comment by NorKalli** [comment]
Loot tables removed a while back
