### ISSUE TITLE
Slayer skill "Flurry" can hit more than 3 enemies.

### ISSUE THREAD

**Issue by Lileldys** [WarEmu/WarBugs#950]
The slayer skill "Flurry" is meant to hit up to 3 targets. Currently hits more. not sure on the max

The Choppa skill Lotsa Choppin is capped to 3 targets like normal.

![slayerflurry](https://cloud.githubusercontent.com/assets/13259775/8609233/994a660e-269a-11e5-8d83-ffaf4b3fad9c.png)

**Comment by Silentguard** [comment]
If that was a bug than i can say for sure only melee aoe class will be blackguard.

**Comment by ozarmidrashim** [comment]
Fixed in next patch.
