### ISSUE TITLE
Death Rocks

### ISSUE THREAD

**Issue by Walhart** [WarEmu/WarBugs#9500]
Any series of boulders that can be jumped on in and outside of RvR zones will occasionally randomally strike you for 2000-15000 "fall damage" I'm assuming. Makes navigating the SCs when kiting people, or if trying to escape people as a healer a bit of a death or death situation.

This is a bit of a immersion breaker to just randomally combust if you land on a rock just the right way. It doesn't even require that you hit the rock "barely" you can land on it perfectly fine and splat. Death. Is there anything that can be done about these massive sleeper agents of the Order?

**Comment by Luth-RoR** [comment]
There are many places like that and also many reports about that issue already; the root of the problem is still unknown and in scenarios some workarounds have been placed.
