### ISSUE TITLE
Client shut down when entering war quarters from south

### ISSUE THREAD

**Issue by iljuro** [WarEmu/WarBugs#9501]
I've got several CSDs with two separate toons in the passage between the gate and the corner.
I also got one CSD when exiting from wq, just when turning right towards market.

One toon survived in the passage between the gate and the corner, and the other toon was at the Altdorf healer each time

**Comment by Luth-RoR** [comment]
Using this report https://github.com/WarEmu/WarBugs/issues/9502

**Comment by Luth-RoR** [comment]
Short after every login you should get a chat message about your ping; how high is it?

**Comment by iljuro** [comment]
I don't get that message, and according to my chat log I've never got any. Wireshark says it's about 40 ms.
But it works today so I guess it was a fluke.
I did ask in advice before submitting though, and there were at least one more who had the same issue yesterday.

**Comment by Luth-RoR** [comment]
Maybe this can happen also because of temporary DDoS butthurtness (see ban appeals subforum).
