### ISSUE TITLE
Altdorf Gates War Quarters

### ISSUE THREAD

**Issue by raptrr** [WarEmu/WarBugs#9502]
When you leave the Warquarters in Altdorf trough the middle part (RIP Spongel statue - 1st picture @my marker position) and head to the two Gates (1st picture, red circle), these two aren't clickable all the time. Somestimes you can click them to open, sometimes you cannot (2nd picture). 
![raotrr_002](https://cloud.githubusercontent.com/assets/27915421/25312862/d41fc1fc-2823-11e7-938d-8757755279ef.jpg)
![raotrr_003](https://cloud.githubusercontent.com/assets/27915421/25312876/ff2c1bb6-2823-11e7-87d3-6fcbb2ff8412.jpg)

When you come from the other side, you can open the 1st gate (picture 3):
![raotrr_005](https://cloud.githubusercontent.com/assets/27915421/25312891/5ae0e676-2824-11e7-9885-880465a20035.jpg)

The 2nd gate isn't clickable.

A week ago both ways & gates worked, couple of days before that I had the same issues I've wrote down above.
So it works sometimes and some other time it doesn't.

**Comment by grunbag** [comment]
it seems to be already fixed, just tried the doors

**Comment by grunbag** [comment]
it seems to be already fixed, just tried the doors
