### ISSUE TITLE
D/C issue when dropping barrel off in Talberc Dam SC

### ISSUE THREAD

**Issue by Krumpguts** [WarEmu/WarBugs#9503]
This bug has happened 3 times now on two different characters.

Basically, when you drop the barrel off at the windmill in the SC, for around 15s I can walk around although not use any abilities/mount up and my character stays in the kneeling position that they take when placing the barrel. After this I D/C and I am immediately kicked from the SC upon relogging.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/9443
