### ISSUE TITLE
CoD not received

### ISSUE THREAD

**Issue by rgMarkon** [WarEmu/WarBugs#9504]
I sent another player and armor tali with CoD, however i have not gotten the gold yet even after he picked the tali up from the mailbox.

I tried refreshing UI and relogging nothing still.

I msged the receiver and he said that he already picked up and the gold was subtracted from him. I did take a SS of our convo if that helps

**Comment by Luth-RoR** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/7638
