### ISSUE TITLE
Apothecary bugg

### ISSUE THREAD

**Issue by Listigerrfuchs** [WarEmu/WarBugs#9505]
After you brewed you stuff and the container are empty you cant put another container inside . i have to relogg always. Nice game keep going

**Comment by cimator** [comment]
Its a known bug I think, you gotta click brew slowly, or count your clicks so you dont click it extra, that bugs it out

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues/7411
