### ISSUE TITLE
Bright Wizard tactic: Wildfire

### ISSUE THREAD

**Issue by nohh** [WarEmu/WarBugs#9506]
I have a question about issue: [https://github.com/WarEmu/WarBugs/issues/1940](#1940)
How it was fixed?

Now wildfire does not proc on Flame Breath, Spreading Flame, Backdraft.

**Comment by Luth-RoR** [comment]
You can post in closed reports. I don't remember how it was fixed, but high likely i got confirmation on teamchat. I just tested it with flame breath and can confirm that it doesn't proc wildfire.

Merging with https://github.com/WarEmu/WarBugs/issues/1940
