### ISSUE TITLE
Guild Cloak. 

### ISSUE THREAD

**Issue by EykoFox** [WarEmu/WarBugs#9509]
Hi,

Since the creation of our guild (27/02/2017), we could not custom our guild cloak. Our guild is lvl 20 (name : NPNB).
I tried everyday since 1 month to custom it but without any success. 
![eyko_013](https://cloud.githubusercontent.com/assets/27953252/25333468/991fa06e-28ea-11e7-98f7-eeccb12d55d9.jpg)
Here we can see that i try to custom our guild cloak.
![eyko_014](https://cloud.githubusercontent.com/assets/27953252/25333495/b8941c18-28ea-11e7-88ca-aee16bb1c5a8.jpg)
After when I click on "Save" there is a strange message who indicate that we have to pay "0 1704". Then I click on "Yes"
![eyko_015](https://cloud.githubusercontent.com/assets/27953252/25333566/00c26404-28eb-11e7-9461-c4ff5bd415ea.jpg)
And here we can see that nothing has changed.

Is it normal ? Because I saw all the other guilds with their own guild cloak.
Thank you for your understanding,
Best regards,
Eyko

**Comment by Luth-RoR** [comment]
Guild needs to be level 20 at least https://github.com/WarEmu/WarBugs/issues/7776#issuecomment-247409916
See also https://github.com/WarEmu/WarBugs/issues/9295

**Comment by EykoFox** [comment]
Yes but our guild is lvl 20 ! I putted screenshot to my post and other topic are not answering this...

**Comment by Luth-RoR** [comment]
Ah ok, i didn't see guild rank, sorry.
Seems like this feature worked and is somehow broken now.

**Comment by Ufurious** [comment]
I am still having the same issues and it's been almost a week with the only help from the GM's is "wait for server restart".....I still can't change my Heraldry colors, and my gold was deducted for the change....any and all help will be appreciated.
Thank you

**Comment by MaxHayman** [comment]
This should have been fixed a while ago.
