### ISSUE TITLE
alliance formation (guild)

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#9511]
nazgul guild is currently unable to form alliance with path of wreckage, the request is sent and the other guild leader accept but the ally is not formed. We also tryed to be invited by them with no results.

Edit: was able to form alliance with another guild ; basically you need to spam the request and they need to spam the accept, that's still bit buggy; i leave the report open even if the problem was solved, if you want btw you can close it but that thing should be looked upon it.

**Comment by Luth-RoR** [comment]
Maybe related to the more recent issues with guilds and the "Nazgul guild merge" issue.

**Comment by Tesq** [comment]
uh no, dont think so, the roor leader told me how to do it because he knew and done it in past.
Must be in this by a long time can ask him from how much time work like this.

**Comment by Natherul** [comment]
same issue as
https://github.com/WarEmu/WarBugs/issues/4528#issuecomment-463590823
fix pending
