### ISSUE TITLE
Moonstorm Shadow Warriors

### ISSUE THREAD

**Issue by l3liss** [WarEmu/WarBugs#9513]
These enemies in Western Praag are double spawns {Coords 49.52;8.65}

**Comment by Luth-RoR** [comment]
Can you post where they can be found?

**Comment by l3liss** [comment]
They are in North East, western praag i can post the coords when i get home but that wont be till tomorrow

**Comment by Luth-RoR** [comment]
No hurry, afaik it's useful to DB devs. Thanks.

**Comment by l3liss** [comment]
Updated with coords

**Comment by Luth-RoR** [comment]
Thanks.

**Comment by saupreusse** [comment]
Why should they be doublespawns? looks good imo. There are several of them surrounding the chaos camp.

**Comment by l3liss** [comment]
there are 2 inside of each other you can see them glitching out, and you have to kill 2 of them.

**Comment by wargrimnir** [comment]
Doublespawns removed.
