### ISSUE TITLE
Sticky feetz

### ISSUE THREAD

**Issue by Vdovics** [WarEmu/WarBugs#9518]
Just tested AOE radius effect and its something between 5-10 feets insted of 20.  On live the effect of this skill was much larger. Skill as it is now is nearly to useless atm.
Several proofs, that on live AOE effect was much bigger than skill graphical effect. For example 2.25 or better 5:30
https://www.youtube.com/watch?v=aNcCFp2sr-0&t=403s

**Comment by cimator** [comment]
Can confirm on several aoe skills actually, STY/Lileath arrow for ex. hits up to 40-45 ft instead of 65, choppa/slayer aoe is around 15ft instead of 25, tho the aoe abilities that explode on target seems fine.

**Comment by Luth-RoR** [comment]
https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=17634&p=191833
