### ISSUE TITLE
Supplies and Stealth

### ISSUE THREAD

**Issue by Smokeras** [WarEmu/WarBugs#9519]
A stealth class we/wh can stealth with supplies and not drop them as it was before some patches ago.This give the advantage if you play it right, to pass a keep blockade undetectable and fix the doors of the keep.Or better you can stealth every 30 sec and cover distances passing enemys premade or zerg.This give a large advantage also in contribution because for minimum effort you get high rewards and probably you are close to a gold bag than others classes with no stealth ability.

**Comment by Luth-RoR** [comment]
Needs confirmation from dev wether intended or not.

**Comment by sioding** [comment]
Since we have a new ORvR System without players carrying the ressources i will close this now. Thanks for the report.
