### ISSUE TITLE
[DESTRO] Client Crash in IC by AH & Mailbox

### ISSUE THREAD

**Issue by appdevman** [WarEmu/WarBugs#9523]
Random & consistent client crash to desktop when in this area.
Can happen by either running to the immediate area, or but coming in with IC scroll (obtained in T3).
This issue happened about a year ago, and got fixed. Somehow it worked its way back.

**Comment by Kaelang** [comment]
This crash is likely based on something on your end as opposed to server-side. Please use the Technical Support forums for troubleshooting issues and if you are able to replicate this problem please re-open a ticket.
