### ISSUE TITLE
Didn´t got my T4 Purple Bag

### ISSUE THREAD

**Issue by Sahnebonbon** [WarEmu/WarBugs#9527]
I won a purple bag yesterday in Black Crag with my Witch Elv named Kiarah but i didn´t got it yet.
Maybe because i was in loading screen when the mail arrived?!

I hope you can help me

Greetings

**Comment by Luth-RoR** [comment]
known: https://github.com/WarEmu/WarBugs/issues/9469
and also:
https://www.returnofreckoning.com/forum/viewtopic.php?f=2&t=20514
