### ISSUE TITLE
Stuck at Northland Beach

### ISSUE THREAD

**Issue by Kalebdaark** [WarEmu/WarBugs#9528]
Hello,

I am stuck for more than 2 weeks.
I did not log for the time I was stuck until today and I am at the same place.
When I type /stuck in the chat the game back to the character selection
Then I press start and I come back at the stuck place.

My character name is Kalebdaark.
It is 08H30 ( French time)

Regards.
![kalebdaark_584](https://cloud.githubusercontent.com/assets/28180821/25553597/f1d46dae-2cb7-11e7-87f9-774bd6d6b0e4.jpg)

**Comment by Kalebdaark** [comment]
Finally I ask to an order to kill me

**Comment by Luth-RoR** [comment]
When you type /stuck first you will get a loading screen; during the loading screen you can hit _enter_, type _/stuck_ again and confirm with _enter_ this should port you to your starting location.

**Comment by Kalebdaark** [comment]
when I press /stuck I don't have a loading screen I have a count down from 20 sec to 0
What does the loading screen looks like please ?

**Comment by Luth-RoR** [comment]
Ah ok, then iirc you need to type /stuck and hit enter and again /stuck+hit enter on the next login during the loading screen.

**Comment by Kalebdaark** [comment]
Ok, I thank you I will try next time during the count down to type again /stuck + [Enter}

Thank you for your quick reply.
Big thanks for your great job, to you and all your team !!!!
