### ISSUE TITLE
Magus: Warpfire radius

### ISSUE THREAD

**Issue by nohh** [WarEmu/WarBugs#9530]
Blue horror does not increase the radius of Warpfire.

**Comment by nohh** [comment]
The number of targets also does not increase (hit only 9 targets)

**Comment by Luth-RoR** [comment]
According to the devs, it's intended that these kinds of AoE effects (pulsating damage) are excluded from the radius/target cap buff. Same with the engineer.

**Comment by nohh** [comment]
Change description of .ab changelist for avoid misunderstanding maybe...
