### ISSUE TITLE
Beastlord Hunt: Druchii [Destruction BL Token quest bugged)

### ISSUE THREAD

**Issue by Antalor** [WarEmu/WarBugs#9533]
Hello. 
I' want to report a bug with the quest from the title of the issue. After completing the quest for Beastlord cloak questgiver don't show up the further Token quest. Any idea how to fix it, please ?
Greetings.

**Comment by Antalor** [comment]
It's still broken. It worked well on my second character, but quest on first one is still missing.

**Comment by Kaelang** [comment]
The Beastlord Hunt chain is working as intended as of later versions of RoR.
