### ISSUE TITLE
Impossible to recap Battlefield Objective

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9536]
Had a bug : it was impossible to recap a Battlefield Objective. A message appeared and said 'Can't capture while a guard (name of the guard) is still alive'. But in real, no guard was alive as the BO was already claimed by order.
![anaehll_354](https://cloud.githubusercontent.com/assets/11537611/25564149/9406d856-2dac-11e7-9322-69cc44ddaa95.jpg)

I think it can be linked to the fact that it is possible a guard respawns while someone is capping the BO. In this case, the guard is not killed and the game may consider a guard is still alive, even it is not true.

**Comment by Luth-RoR** [comment]
From https://github.com/WarEmu/WarBugs/issues/9778

>You can capture the Utorin Siege Camp in Eataine with one of the Gaurds still alive.
At least a Wh just did it in front of me, as I pulled the last guard, standanding far away from flag
got it on a short video clip as well
https://youtu.be/S1Lj2S04i00
(sorry for bad quality)

**Comment by sioding** [comment]
I will close this now since we have a ORvR System without guards at the BO´s. If we ever use guards again and this issue comes back - please reopen it.
