### ISSUE TITLE
Beastlord Hunt: Festitt

### ISSUE THREAD

**Issue by Kubzes** [WarEmu/WarBugs#9539]
I've returned the "Beastlord Hunt: Festitt" quest with 30/30 Enemy player killed and Slay Festitt 1/1 and recived "Beastlord Wingmantle" (Shoulders for Zealot). The problem is that, the Brolgr (NPC) don't give me a next "stage" with players killed (for example Slayers or Engineers). The NPC is still giving me quest for killing Festitt and players ONCE MORE.

I don't know what to do, I've multiply killed Festitt and it doesn't work.

**Comment by Kubzes** [comment]
UPDATE: When you have Quest done, and someone want to share it - it worked and bug the NPC. Don't work with others BL quest.

**Comment by wargrimnir** [comment]
Your quests are probably bugged. Try contacting a GM in-game to have them reset.
