### ISSUE TITLE
Lost Items in Drop System 

### ISSUE THREAD

**Issue by lildwarfBIGWAR** [WarEmu/WarBugs#954]
Two ways I've seen items become unlootable/lost in time:

1. When in a group outside of a scenario while one or more party members are inside of a scenario and being in two parties at once causes the dropped non-scenario item to become frozen due to an unfinished roll system from all the players. 
2. Loot dropping at the end of a scenario and the scenario ends before the item giveaway finishes/cashes out. 

Not sure if intended or not, thought I'd try to help and losing items can be an annoyance. Awesome work so far though.

**Comment by Evildoor** [comment]
AFAIK, this was fixed.
