### ISSUE TITLE
Bags in the mail not opening.

### ISSUE THREAD

**Issue by Celticwitch** [WarEmu/WarBugs#9541]
for the last 2 days ive got 3 green and 4 blue bags from PQs in the mail and can't open any of them.

**Comment by Luth-RoR** [comment]
I just got a bag and can open it. Was it from any special PQ or many different ones?

**Comment by Celticwitch** [comment]
It was from a few different ones, i also got a couple of bags yesterday and were able to open them it seems if i log out with bags in mail unopened i can't open them when i get back into game usually the next day.

**Comment by Luth-RoR** [comment]
Probably this issue: https://github.com/WarEmu/WarBugs/issues/5768
