### ISSUE TITLE
Broken Vendors in Empire Starting Area Grimmhagen

### ISSUE THREAD

**Issue by LadyCereus** [WarEmu/WarBugs#9543]
As of last night all 3 outdoor vendors in the Empire starting area were bugged.  If a player talked to them, they give you the white conversation bubble asking whether you want to see their wares or dye items.  Clicking dye items works fine, but if you click to see their wares nothing happens.  You don't get the normal vendor screen and cannot sell your loot.  I noticed this problem with 3 vendors outside around the center of the village:  the mount vendor, the small companion vendor, and the main merchant.  

Thanks for letting us enjoy this great game again!

**Comment by wargrimnir** [comment]
Not able to reproduce. Able to click on, get normal interface, and sell items. They don't have anything for sale currently by design.
