### ISSUE TITLE
WE "vehement blades" and WH "burn armor" damage procs multiple times from AoE attacks

### ISSUE THREAD

**Issue by Antiquities1** [WarEmu/WarBugs#9544]
Vehement Blades, when opening on a Slayer that is using flurry and hitting multiple targets is proccing on the number of players being hit by flurry and not the activation of the skill, singularly, respectively.

In order to recreate this bug you need a Witch Elf and a Slayer using flurry hitting a group of people. Pretty straight forward.

**Comment by Luth-RoR** [comment]
Probably the same with choppa "lotsa choppin" and WH "burn armor".

**Comment by Luth-RoR** [comment]
Confirmed that it works on all AoE attacks.

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by sioding** [comment]
fixed with patch from 20.04.2019

**Comment by sioding** [comment]
Fixed with patch from 27.04.2019
