### ISSUE TITLE
ToK unlock 'Empire Steam Tank'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9545]
This History & Lore unlock should be triggered by walking near the steam tank in Empire chap 11 (High Pass, 11k 59k). Walking next to it does not provide the unlock.

**Comment by MaxHayman** [comment]
![image](https://user-images.githubusercontent.com/1018809/91725497-bd31ca00-eb96-11ea-9bce-0fd93e57b3a2.png)

**Comment by MaxHayman** [comment]
@Lheana do we want this to be a hidden area? (so its name doesnt appear)

![image](https://user-images.githubusercontent.com/1018809/91725603-e3576a00-eb96-11ea-843e-48c04b035077.png)

**Comment by Lheana** [comment]
Sure, I see no reason it should not be hidden.
