### ISSUE TITLE
ToK unlock 'Lair of Silveroak'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9547]
This Achievement unlock should be triggered by walking near to Silveroak in Norsca (17k 28k). Silveroak is there but walking next to him/killing him does not provide the unlock.

**Comment by MaxHayman** [comment]
![image](https://user-images.githubusercontent.com/1018809/91723403-9c1baa00-eb93-11ea-8634-dd03ceb4c4c1.png)
