### ISSUE TITLE
[Blackguard] Spiteful Slam KD times not scaling correctly with hate

### ISSUE THREAD

**Issue by Zealote** [WarEmu/WarBugs#955]
Seems the kd time is 1s less than it should be for each hate level. The numbers I got were:
    0 hate - 2s kd (correct)
  30 hate - 2s kd (should be 3s)
  60 hate - 3s kd (should be 4s)
100 hate - 4s kd (should be 5s)

Assume it's the same for all the numbers in between but couldn't check that.

**Comment by Tesq** [comment]
aye base should be 3 sec and scale up

**Comment by ozarmidrashim** [comment]
Fixed in next.
