### ISSUE TITLE
ToK unlock 'Lair of Lady Alisha'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9550]
This Achievement unlock should be triggered by entering inside the lair of Lady Alisha in Blighted Isle (35k 50k). Lady Alisha is there but entering inside her lair/killing her does not provide the unlock.

**Comment by MaxHayman** [comment]
![image](https://user-images.githubusercontent.com/1018809/91673713-575d2800-eb2d-11ea-83b2-f68ca9ad5c68.png)
