### ISSUE TITLE
[Chosen] Crippling Strikes stacks again with challenge

### ISSUE THREAD

**Issue by Pxl555** [WarEmu/WarBugs#9551]
As per #1216 ( and https://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=6812&p=79924&hilit=crippling+strikes#p79924)  this should have been fixed quite some time ago and is currently stacking with challenge in a mulitplicative way , reducing damage of everyone affected to 52.5%

Control Test - https://www.youtube.com/watch?v=EeqWPEGxK5k

Challenge - https://www.youtube.com/watch?v=JbBVDJ_o0S8

Challenge and Crippling Strikes - https://www.youtube.com/watch?v=VUwTXWFVL5E

**Comment by wargrimnir** [comment]
This was fixed in a recent patch.
