### ISSUE TITLE
ToK unlock 'Lair of the Bandit Queen'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9552]
This Achievement unlock should be triggered by entering inside the lair of the Bandit Queen in Ekrund (62k 1k4). Renatta Betz is there but entering inside her lair/killing her does not provide the unlock.

**Comment by MaxHayman** [comment]
![image](https://user-images.githubusercontent.com/1018809/91712521-cbc0b700-eb7f-11ea-9c57-b2c56e790b00.png)
