### ISSUE TITLE
ToK unlock 'Lair of Morra'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9553]
This Achievement unlock should be triggered by entering inside the lair of Morra in Nordland (31k 60k). Morra is there but entering inside her lair/killing her does not provide the unlock.

**Comment by MaxHayman** [comment]
![image](https://user-images.githubusercontent.com/1018809/91714681-29570280-eb84-11ea-8894-94ad66ffcd76.png)
