### ISSUE TITLE
ToK unlock 'Lair of Gutslime'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9554]
This Achievement unlock should be triggered by entering inside the lair of Gutslime in Mount Bloodhorn (55k 45k). Nerx Gutslime is there but entering inside his lair/killing him does not provide the unlock.

**Comment by MaxHayman** [comment]
![image](https://user-images.githubusercontent.com/1018809/91713270-56ee7c80-eb81-11ea-906a-9ce35d97e2d9.png)
