### ISSUE TITLE
ToK unlock 'Lair of Kelbrax

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9555]
This Achievement unlock should be triggered by entering inside the lair of Kelbrax in Chrace (18k 63k). Kelbrax is there but entering inside his lair/killing him does not provide the unlock.

**Comment by MaxHayman** [comment]
![image](https://user-images.githubusercontent.com/1018809/91715603-ded68580-eb85-11ea-8613-5935ce3e54e9.png)
