### ISSUE TITLE
Heavy Armor wearable on Witch Elf (Light Armor only)

### ISSUE THREAD

**Issue by ForlornRoR** [WarEmu/WarBugs#956]
The Item "Faithbreaker Grimbraces" is Heavy Armor but can be equipped by Witch Elves, which shouldn't be the case. When equipped, the Item will not show a 3d-Model on the character in the Inventory. Stat changes seem to be logged correctly.
The Item is a Reward for a Quest in Troll Country, Felde on Destruction Side. Quest might be "Deadly Task" or "Foul Works"

Might be related to "[Armor] Heavy boots on Squig Herder #53" Issue. The Issue was closed for unknown reasons (Squigherder supposedly able to wear Heavy Armor?).

**Comment by Evildoor** [comment]
Can someone make a screen of this item? I don't have a WE, let alone WE in T2.

**Comment by Evildoor** [comment]
Seems to be fixed - item is now restricted to Black Guards.
