### ISSUE TITLE
ToK unlock 'Lair of Metoh'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9560]
This Achievement unlock should be triggered by entering inside the lair of Metoh in Troll Country (9k 4k). Metoh is there but entering inside his lair/killing him does not provide the unlock.

**Comment by MaxHayman** [comment]
![image](https://user-images.githubusercontent.com/1018809/91713883-7c2fba80-eb82-11ea-99bd-ace574acace0.png)
