### ISSUE TITLE
ToK unlock 'Lair of Gorthlak'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9561]
This Achievement unlock should be triggered by entering inside the lair of Gorthlak in Blighted Isle (34k 18k). Gorthlak is there but entering inside his lair/killing him does not provide the unlock.

**Comment by MaxHayman** [comment]
![image](https://user-images.githubusercontent.com/1018809/91712023-da5a9e80-eb7e-11ea-99ec-8ca56bbb2e6f.png)
