### ISSUE TITLE
5h conqueror set bonus- Preservation

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#9563]
After log in game the wounds buff didn't proc, i had to unequip and re equip a piece for refresh the application (always tried with the chest). This also happen everytime i die, the proc stop work and everytime i have to remove and re apply a piece of gear.

Tested with 5 pieces  on 6 (no boots).

I tested it both in pve and in rvr, (didn't test with res just by respawning).

p.s. for the rest the proc heal you correctly for 1k.

**Comment by Luth-RoR** [comment]
Could be a similar issue as with https://github.com/WarEmu/WarBugs/issues/6615#issuecomment-250998901 (guessing).

**Comment by Torquemadra** [comment]
negative, procs work fine now, as will this
