### ISSUE TITLE
Legacy of Ruin

### ISSUE THREAD

**Issue by ingurbard** [WarEmu/WarBugs#9564]
Hi there, I'm ingur
I address to you due a bug  that prevents you from completing the Legacy of Ruin quest line. When I completed the first stage of this quest (obtaining the seal) the seal didnt appear in my inventory, but questgiver recognized the stage as completed anyway, in the next stage one needs to use the seal to kill Rauthaur but as the seal does not appear in the quest items of the inventory this stage is impossible to complete, even if you kill Rauthaur in your own

**Comment by wargrimnir** [comment]
Killing Rathaur should now finish the quest. Next patch.

**Comment by ingurbard** [comment]
Thank you :) 

    El Martes, 9 de mayo, 2017 22:02:01, wargrimnir <notifications@github.com> escribió:
 

 Killing Rathaur should now finish the quest. Next patch.—
