### ISSUE TITLE
[Mobs] Corpses attacked me in Inevitable city

### ISSUE THREAD

**Issue by SODIX** [WarEmu/WarBugs#9567]
Just lurked there for some rare loot&quests and found this dead guys, who at one side with living mobs tried kill me. They attack while playing dead animation. You are free to fix this. 
![war 2017-04-29 21-02-17](https://cloud.githubusercontent.com/assets/22780561/25710953/6808172c-30f6-11e7-9bd9-efa1f8b0273e.png)
![war 2017-04-29 21-02-34](https://cloud.githubusercontent.com/assets/22780561/25711254/26f6c85e-30f7-11e7-976d-6cfce5bcc7d4.png)

**Comment by SODIX** [comment]
PS. Excuse me for Russian there, I should did /lang 11 before post it, but i'm lazyfakk.

**Comment by Luth-RoR** [comment]
Is the name of the dead npcs "bloodfiend flayerkin"?

**Comment by SODIX** [comment]
No, just "corpse".

**Comment by wargrimnir** [comment]
This is because you're running a damage aura. Mobs don't change states yet when attacking.

**Comment by SODIX** [comment]
Doesn't Corpses just should be really dead, decorative? Like a dead bodies killed by chaos hordes?

**Comment by NorKalli** [comment]
Corpse set to destro faction - no more zombies

**Comment by sioding** [comment]
Fixed with patch from 11.05.2018
