### ISSUE TITLE
[Quest] Temptress, Chaos T2

### ISSUE THREAD

**Issue by SODIX** [WarEmu/WarBugs#9569]
Quest marker highlights WRONG wayshine. I looked for proper and found it a 200m away, from a right side of road. 
![war 2017-04-30 01-26-25](https://cloud.githubusercontent.com/assets/22780561/25712145/7c990bf8-30f9-11e7-8f26-d28600471906.png)

**Comment by Luth-RoR** [comment]
A known issue: https://github.com/WarEmu/WarBugs/issues/8255
