### ISSUE TITLE
1H\2H Weapons issue

### ISSUE THREAD

**Issue by Silentguard** [WarEmu/WarBugs#957]
There is no difference of ability damage between wearing 1h\2h weapons. In WHO duals grants you +10% parry, 2H weapon have about 10-15% higher ability damage. And dps of weapon in off-hand has no effect on ability damage.

**Comment by Evildoor** [comment]
Sorry, but where does "10-15% ability damage" info comes from? As far as i remember, I did some tests myself when WHO was alive, with lvl 20 scenario weapons for Slayer, which give same amount of STR from duals and twohander - damage from abilities was equal. While 10% parry from duals is obvious, i never really got a definite answer about twohander bonus, only speculations that its either "ignore 10% of enemy block" or "ignore 10% of enemy block/parry" - both of which can't be seen in char panel.

**Comment by Silentguard** [comment]
1H weapon have less wep.dps than 2H. In this case contribution of 2H wep.dps grants higher ability damage. I heard the same about 10% ignore of parry\block but never tested this.

**Comment by Evildoor** [comment]
Should not affect? Why? That is exactly the point. Of course, if we take a single onehander vs twohander, then twohander has higher dps and thus gives more damage - so, offhand should also affect the damage. It's a shame that official WHO forum was nuked, since there was a good article about damage calculation, which could have clarified this...
P.S. As far as i know, devs cant change the game client, so its tooltips are still correct (and devs are using them to understand scaling of different abilities). Therefore, you can log into game and compare your ability damage with single onehander vs same onehander + some offhander with 0 STR (i picked Mara's Monstro Gift, which remained from the patch), and notice that tooltip damage increases, and so does real damage.

**Comment by Silentguard** [comment]
I mean only dps of off-hand weapon has no affect on ability damage but stats do. Many players uses LOTD weapons with Colo talismans in off-hand just because that grants you more stats and more crit than even 100rr scenario weapon dps which has no contribution in ability damage at all.

**Comment by Titoos** [comment]
Off hand dps contributes in auto-attack (of-hand) damage.

**Comment by noisestorm** [comment]
The benefit from Dual wield is simply the higher amount of crits and proccs you get off of them.  The overall AA damage most likely will also be higher, while 2 handers grant you (through the higher DPS alone) better ability dmgs

**Comment by ozarmidrashim** [comment]
Analyse the client. If your tooltip damage changes with an offhand on, your offhand does indeed contribute DPS.

**Comment by Silentguard** [comment]
Tooltip changes because off-hand have stats, not because of its dps. I have no doubts about it, almost all players equip LOTD 32lvl off-hand with crap wep.dps and it boost damage.

**Comment by Evildoor** [comment]
Client tooltips do show more damage with offhand weapon equipped, even when offhand weapon has zero STR on it. LOTD weapons were giving TONS of stats with right talismans, which was outweighting the DPS loss.

**Comment by ozarmidrashim** [comment]
I will also note that I tested extensively when calculating skill damage, including whether the offhand affected abilities. Any offhand that has DPS will contribute 46% of that DPS to the ability's damage.

So yeah, two handed weapons are pretty trash. All you get on RoR from equipping a two hander is +10% block strikethrough, which is about the most useless bonus ever.

**Comment by Silentguard** [comment]
We are all arguing with no proofs so i guess it makes no sense.

**Comment by Evildoor** [comment]
No proofs? Ahem.
Point 1. Client tooltips reflect the state of original game, RoR devs cannot change them. So, the tooltips can be used to understand, how were the numbers calculated in original WAR.
Point 2. Equip onehander. Then equip an offhand weapon without offensive stats. Watch the damage difference in tooltip.
Which of these points you want to disagree with?

**Comment by Silentguard** [comment]
Can you confirm 1st point?

**Comment by ozarmidrashim** [comment]
"Point 1. Client tooltips reflect the state of original game, RoR devs cannot change them. So, the tooltips can be used to understand, how were the numbers calculated in original WAR."

I can confirm. We use tooltips to calculate all damage.
