### ISSUE TITLE
ToK unlock 'Lair of Stinkfang'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9572]
This Achievement unlock should be triggered by entering inside the lair of Stinkfang in Ellyrion (55k 42k). Stinkfang the Vomitous is there but entering inside his lair/killing him does not provide the unlock.

**Comment by MaxHayman** [comment]
![image](https://user-images.githubusercontent.com/1018809/91719786-d5e9b200-eb8d-11ea-9c04-36a7c99add8c.png)
