### ISSUE TITLE
ToK unlock 'Lair of Reaver'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9573]
This Achievement unlock should be triggered by entering inside the lair of Reaver in Barak Varr (1k 21k). Karerg the Reaver is there but entering inside his lair/killing him does not provide the unlock.

**Comment by MaxHayman** [comment]
![image](https://user-images.githubusercontent.com/1018809/91673407-e2d5b980-eb2b-11ea-8dcc-70d63c80207c.png)
