### ISSUE TITLE
ToK unlock 'Lair of Old Oozeback'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9574]
This Achievement unlock should be triggered by entering inside the lair of Old Oozeback in Marshes of Madness (25k 60k). Old Oozeback is there but entering inside his lair/killing him does not provide the unlock.

**Comment by MaxHayman** [comment]
You mean Marshes of Madness?

**Comment by MaxHayman** [comment]
![image](https://user-images.githubusercontent.com/1018809/91711135-4b00bb80-eb7d-11ea-863f-ba08dc49ec89.png)
