### ISSUE TITLE
Quest "Legend and Infamy"

### ISSUE THREAD

**Issue by Choppstix** [WarEmu/WarBugs#9575]
NPC issuer: Sorceress Rathia
Zone Location: Chrace
Camp Location: Malagurns' Charge (Dark Elf Chapter 4)
Quest Objective: 
   -Kill Kerilas 0/1 
   -Kill Shining Guard Knight 0/3
Quest Location: 
   -Stone of Valetear Public Quest

The issue is that when killing the Shining Guard Knights; the quest will not update and count the kills toward the quest leaving players unable to finish the quest. Killing Kerilas counts towards the quest. The Shining Guard Knights are also naked with no armor while sitting on their horses.

**Comment by wargrimnir** [comment]
Fixed in next patch. Should count for the quest, and be armored.
