### ISSUE TITLE
Keep Lord Bloodfist Rock not found

### ISSUE THREAD

**Issue by raptrr** [WarEmu/WarBugs#9576]
Im standing right in the Bloodfist Rock Keep (TM) and there is no Lord.
Might have not spawned properly after reset
![raotrr_007](https://cloud.githubusercontent.com/assets/27915421/25736102/18dddc84-3170-11e7-893e-07959d268dfc.jpg)

**Comment by raptrr** [comment]
All done, he is back ^^

**Comment by raptrr** [comment]
OK, when you enter Keep he is there but then despawns it seems. I had him in target and as we went up, he dissapeared

**Comment by sioding** [comment]
Since there is no confirmation i close this ticket now. Thanks for the report.
