### ISSUE TITLE
5 parts conc setbonus vor Witchelf

### ISSUE THREAD

**Issue by tlitschye** [WarEmu/WarBugs#9577]
Hi,

i tested the toughness debuff/buff proc of the Witchelf conc set.

The PROC does NOT stack with "wracking pains" the witchelf dot that reduces toughness. That making it VERY useless.
Is it possible to make it stack? Or maybe switch it to another proc?

Greets

**Comment by Krimalicious** [comment]
I expected that when they release the gear...didnt even bother trying hard to get full conq. I doubt they change something to help WEs.
5 beast / 2 ruin /2 conq its the best combo in my opinion.

**Comment by Torquemadra** [comment]
Not a place for suggestions or requests, it works fine.
