### ISSUE TITLE
ToK unlock 'Lair of the Bleakwing Matriarch'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9579]
This Achievement unlock should be triggered by entering inside the lair of the Bleakwing Matriarch in Talabecland (46k 64k). Killing Unguarded Griffon Eggs should make Bleakwing Griffons attacking you, then they make you fly onto the ledge of lair. It is nevertheless possible to go to the lair through moutains. Bleakwing Matriarch is there but entering inside his lair/killing him does not provide the unlock.

**Comment by MaxHayman** [comment]
![image](https://user-images.githubusercontent.com/1018809/91720362-ea7a7a00-eb8e-11ea-941a-f863279ae8b0.png)
