### ISSUE TITLE
Shadow warrior - Stance bug after using Flee

### ISSUE THREAD

**Issue by Paninii** [WarEmu/WarBugs#958]
searched Github and couldn't find it.

after using Flee, most of the spells won't work anymore, until you hit a stance, then they work again.

1 example, Flame Arrow after using Flee (and having approriate AP ofcourse) won't fire.

**Comment by gittoaster** [comment]
sounds like the same or related issue as here https://github.com/WarEmu/WarBugs/issues/912#issuecomment-117283715

**Comment by Paninii** [comment]
That seems to be indeed the case - is there a possibility in this bugtracker to merge, or relate 2 bugs?
Can search for that function later, at work atm :>

**Comment by ozarmidrashim** [comment]
No, this is a different issue.

Flee sets career resources to 0. It shouldn't act in the case of classes which use stances. Will test.

**Comment by ozarmidrashim** [comment]
Confirmed. Fixed in next.
