### ISSUE TITLE
ToK unlock 'Lair of Elrin Helfried'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9580]
This Achievement unlock should be triggered by entering inside the lair of Elrin Helfried in Avelorn (62k 48k). Elrin Helfried is there but entering inside her lair/killing her does not provide the unlock.

**Comment by MaxHayman** [comment]
![image](https://user-images.githubusercontent.com/1018809/91723598-e8ff8080-eb93-11ea-9507-80792538e8ea.png)
