### ISSUE TITLE
[WL] Trained to Hunt - Proc part scaling significantly more then intended

### ISSUE THREAD

**Issue by Pxl555** [WarEmu/WarBugs#9581]
Trained to hunt proc(Hunter's Strike)  scales with offensive stat 2-2.5 times more then its intended value (which is shown by the tooltip)

The following screenshots will show how much the actual damage increase is by adding brute force  (+160 str)

First control test - the actuall dmg with my current amount of str. is already significantly higher then the tooltip indicates: In this case 738 instead of the intended 420

![wl1](https://cloud.githubusercontent.com/assets/17297910/25754323/0483d58c-31bf-11e7-9ab9-0742913062d5.png)

Second - The damage is  819 with the addition of brute force , and the intended value is supposed to be 459 

![wl2](https://cloud.githubusercontent.com/assets/17297910/25754433/7305effe-31bf-11e7-9899-cd3d355b3338.png)

A damage difference of 81(Δreal values) instead of the intended 39(Δtootlip values) indicates that the scaler is most likely too high for this proc causing it to benefit more then 2 times as much from the offensive stat.

**Comment by Krimalicious** [comment]
well done!! amazing to see this coming from a WL..,most are aware of many glitchs with the class right now and remains slient about it...I was going to roll a WL just to help fix glitches ...the class still feels alot stronger comparing to others.

**Comment by Krimalicious** [comment]
![krima_214](https://cloud.githubusercontent.com/assets/19318335/25770034/0ad075c0-3201-11e7-9781-a1e9d46b8997.jpg)

hunter strike dmg is skyrocket !!
