### ISSUE TITLE
ToK unlock 'Lair of Festitt'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9584]
This Achievement unlock should be triggered by entering inside the lair of Festitt in Caledor (34k 38k). In real, Festitt is in the lair of Tezakk Gnawbone in Chaos Wastes (36k 6k), and Tezakk Gnawbone is in the lair of Festitt in Caledor (34k 38k). Nevertheless, entering inside the lair of Festitt in Caledor, or killing him in Chaos Wastes does not provide the unlock.

**Comment by MaxHayman** [comment]
We need to decide what we want to do here.

**Comment by Lheana** [comment]
The lair bosses are back into their correct lair for a while, so it's not a problem anymore.

**Comment by MaxHayman** [comment]
![image](https://user-images.githubusercontent.com/1018809/91747757-a56a3e00-ebb6-11ea-9440-e9f479056b22.png)

**Comment by MaxHayman** [comment]
![image](https://user-images.githubusercontent.com/1018809/91748401-d5661100-ebb7-11ea-9b0b-7c18d3114bd8.png)
