### ISSUE TITLE
ToK unlock 'Lair of the Defiler'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9587]
This Achievement unlock should be triggered by entering inside the lair of the Defiler in Ostland (8k 62k). I don't think Feculesh the Defiler is there and entering inside his lair (as far as we can go) does not provide the unlock.

**Comment by MaxHayman** [comment]
![image](https://user-images.githubusercontent.com/1018809/91672412-4ceb6000-eb26-11ea-8cf8-4718f693b7a3.png)
