### ISSUE TITLE
ToK unlock 'Lair of Ravack'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9589]
This Achievement unlock should be triggered by entering inside the lair of Ravack in Black Fire Pass (63k 7k). Ravack is there but entering inside his lair/killing his does not provide the unlock.

**Comment by MaxHayman** [comment]
![image](https://user-images.githubusercontent.com/1018809/91673089-2a5b4600-eb2a-11ea-9da5-e33238781706.png)
