### ISSUE TITLE
[Blackguard] Terrifying Foe tactic - % buff to toughness too high and not scaling correctly

### ISSUE THREAD

**Issue by Zealote** [WarEmu/WarBugs#959]
Buffs toughness by 60% at 100 hate; max should be 45%

I think it's working like some of the other BG abilities that increase every 25 hate, rather than every 30 hate, since it also seems to buff by 30% at 50 hate and 45% at 75 hate (should need 60 and 90 hate respectively)

**Comment by ozarmidrashim** [comment]
Fixed in next.

**Comment by Gobtar** [comment]
This tactic is no longer functional
![raikuel_002](https://cloud.githubusercontent.com/assets/7888608/13194648/059557bc-d76f-11e5-876c-5a62fd062268.jpg)

**Comment by Gobtar** [comment]
Opposed to 0 Hatred 
![raikuel_003](https://cloud.githubusercontent.com/assets/7888608/13194661/b5bec150-d76f-11e5-873e-864bd70ed162.jpg)

**Comment by Evildoor** [comment]
1) Tested, tactic works (except that it buffs by 44% instead of 45%).
2) I don't see Terrifying Foe buff on your screenshots.

**Comment by Gobtar** [comment]
I didn't see a toughness increase on my paperdoll nor any mention of it on Get stats. I will look again when I log in.

**Comment by Gobtar** [comment]
Alright so here i took .getstats of before and after with the tactic on...no toughness increase from Terrifying foe despite being full hate...tried this with + without Rugged slotted.
![raikuel_006](https://cloud.githubusercontent.com/assets/7888608/13209022/52da1418-d8f5-11e5-811a-8ca444f25197.jpg)
![raikuel_005](https://cloud.githubusercontent.com/assets/7888608/13209021/52d84926-d8f5-11e5-82b4-b5f9b701dc60.jpg)
