### ISSUE TITLE
ToK unlock 'Lair of the Shambler'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9590]
This Achievement unlock should be triggered by entering inside the lair of the Shambler in Black Fire Pass RvR lake (2k 26k). Ulnac the Shambler is there but entering inside his lair/killing him does not provide the unlock.

**Comment by MaxHayman** [comment]
![image](https://user-images.githubusercontent.com/1018809/91672920-3a265a80-eb29-11ea-82ee-5202a1b3b35a.png)
