### ISSUE TITLE
ToK unlock 'Lair of Krela Darkshroud'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9591]
This Achievement unlock should be triggered by entering inside the lair of Krela Darkshroud in Badlands RvR lake (22k 63k). Krela Darkshroud is there but entering inside her lair/killing her does not provide the unlock.

**Comment by MaxHayman** [comment]
![image](https://user-images.githubusercontent.com/1018809/91672667-ad2ed180-eb27-11ea-968c-53f4fa6d1def.png)
