### ISSUE TITLE
Death bug in Eataine

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9595]
This bug is really weird, as destro, and only as destro, I die on the northeast of Eataine on a certain zone (see ss and video). I don't know what happens, but it reminds me the bug that makes players die when walking on a small climb. Nevertheless, this time there are no climbs, and it happens about every time. For example to reach the ToK object located about 63k 8k, as destro I died like 7 times before I could reach it.
![anaehll_364 1](https://cloud.githubusercontent.com/assets/11537611/25772064/8190a426-3262-11e7-9a18-7ddb40519509.jpg)
Video : https://www.youtube.com/watch?v=EKVAcFCFpXk

**Comment by milosxe** [comment]
I think it's the invisible guards put there back when people thought that it's fun to gank lowbies farming ruin. But it probably needs confirmation.

**Comment by Torquemadra** [comment]
it is
