### ISSUE TITLE
Swordmaster debuffs stacking

### ISSUE THREAD

**Issue by Culdu** [WarEmu/WarBugs#9598]
I know it is kind of public knowledge that Swordmaster Bladeenchantment Heavens Blade Debuff stacks with other resi debuffs.
Nevertheless I want to report that, because in all the definitions which were made for ROR which things should stack (skill/tactic/moral) These 2 abilities should not stack. If Bladeenchantments & War Bellows should stack with normal abilities this should also count for the stats drain (Natures Blade & Da Biggest) with any other stat buff/debuff or Da Greenest. We also tried with Black Orc buff, da Greenest this one also does not stack with any other resistance buff.

**Comment by Luth-RoR** [comment]
The resistance debuff from the enchantment stacked on the mythic server and it intendedly stacks on RoR according to devs.
