### ISSUE TITLE
Black Orc War Bellow da Greenest does not stack with other armor/resistance buffs

### ISSUE THREAD

**Issue by Culdu** [WarEmu/WarBugs#9599]
Black Orc ability da Greenest Armor / resistance buffs for the group does not stack with any other resistance or armor buffs. Due to definition in forum that class based abilities should stack (i.e. Flak Jaket) and that Swordmaster Bladeenchantment Heavens Blade does stack intentionally with other resistance debuffs (see #9598 ) the buff should stack with other buffs.

**Comment by Luth-RoR** [comment]
War bellows didn't stack on the mythic server while flack jacket/daemonic armor stacked on the mythic server, which was another rare exception (check the original mythic patch notes).
**Stop opening bugtracker reports for balance requests; the bugtracker is only for bugs.**
