### ISSUE TITLE
Users can create characters  with profanity names 

### ISSUE THREAD

**Issue by Elvenalthur** [WarEmu/WarBugs#96]
You can create character names with pretty much any bad language word.

I guess some restrictions on what words can be used :laughing: 

![naughty slayer](https://cloud.githubusercontent.com/assets/7492543/2926618/ed8d0b5e-d75e-11e3-97a3-e1b8d4218b89.png)

**Comment by akanieski** [comment]
I noticed too that character names with nonsensical characters in them, and I don't mean accent marks and whatnot.

Perhaps we should add some logic that validates the name a little bit. 

Any suggestions on those rules?

**Comment by sebid** [comment]
Either there is client checking for names, or server side checking through some kind of packet type.
You can check a list of profanities used for World of Warcraft here: http://pastebin.com/GVdgBGUZ

**Comment by genisaurus** [comment]
Mostly a moderation issue
