### ISSUE TITLE
Nurenmir's Lancers - Fell through World

### ISSUE THREAD

**Issue by raptrr** [WarEmu/WarBugs#9602]
When I explored the Emp. PQ Nurenmir's Lancers, I immidiatly fell through the world and gut stuck their.
![raotrr_008](https://cloud.githubusercontent.com/assets/27915421/25778377/7fc50bba-32fc-11e7-959c-bc3bf354d0b9.jpg)

Something "attacked" me the whole time:
![raotrr_010](https://cloud.githubusercontent.com/assets/27915421/25778375/72184a72-32fc-11e7-999d-7bc11151b1d6.jpg)

**Comment by Luth-RoR** [comment]
When you look at your minimap, it shows "Zone 0". Getting into that zone is a very old bug that exists as long a s the server exists now, but happens fortunately very rarely nowadays. https://github.com/WarEmu/WarBugs/issues/6831

**Comment by raptrr** [comment]
Ah cool. Thank you
