### ISSUE TITLE
ToK kill count for Black Crag PQ 'Venom Lake' (Order)

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9605]
Mobs of this PQ don't count as they should on ToK :

- Venom Slimehound : should count as Slime Hounds
- Festering Plaque Bearer : should count as Plaguebearers
- V'kyr the Festering (Champion on Second Stage) : should count as Plaguebeast

Btw, I think 'Festering Plaque Bearer' should call 'Plague' and not 'Plaque'.

**Comment by Ryanfawkez** [comment]
Fixed the name. Overall issue with subtype not working if PQ mob remains a mystery.
