### ISSUE TITLE
[WL] Pack assault - proc part scales unintentionally with strength

### ISSUE THREAD

**Issue by Pxl555** [WarEmu/WarBugs#9606]
**How it should behave(it is essentially the same ability):**
![sb1](https://cloud.githubusercontent.com/assets/17297910/25783353/4b4060c4-335b-11e7-8842-736ee6c228e5.png)

The proc part is a flat 110 dmg according to tooltip and it is working like that in reality

**How WL pack assault behaves:**
![pa2](https://cloud.githubusercontent.com/assets/17297910/25783363/6c849fb6-335b-11e7-9983-bc9dbebc39cc.png)
This first screenshot already demonstrates that it indeed does  a significantly higher amount of proc damage then intended.

![pa1](https://cloud.githubusercontent.com/assets/17297910/25783362/6a346926-335b-11e7-89ca-4ec8485ee107.png)
Second Screenshot is the addition of brute force (to illustrate that it is scaling and not just a base dmg issue)

The initial damage increase is in line with brute force strength increase while In both of these screenshots the proc part value remains a static 130 , yet in reality it scales every proc as if it were a normal ability as demonstrated in the transition from 1st to 2nd screenshot. 
Considering the pet also benefits from the proc, and potential 2 tanks  and 1 more dps can proc it aswell the difference compared to the intended value can be upwards to 2 thousand of unintended proc damage upon focusing a target.

**Comment by Torquemadra** [comment]
fixed, thanks
