### ISSUE TITLE
Won a Gold bag out of nowhere

### ISSUE THREAD

**Issue by cimator** [WarEmu/WarBugs#9607]
I was just waiting in praag wc for zones to open, and when it unlocked this happened;
![leakyskull_000](https://cloud.githubusercontent.com/assets/17130290/25783931/354489be-336d-11e7-9bbb-df17e98ece9d.jpg)

**Comment by Razielhell** [comment]
You were doing Scenarios? Did you walk by the PQ Wilhelm's Fist?

**Comment by cimator** [comment]
This was before all the orvr changes, doesnt happen anymore. closing
