### ISSUE TITLE
[Blackguard] Shield of Rage - incorrect absorb amount (might be general issue with absorbs)

### ISSUE THREAD

**Issue by Zealote** [WarEmu/WarBugs#961]
Tooltip for SoR on my lvl 20 BG says it should absorb 415 dmg. 

Tested it a few times with a lvl 22 yeti whose normal attack hit me for 116: I absorbed one attack and then the 2nd did either 6 or 9 dmg. Even if both were crits (and it's not likely since I did it a few times), there's still ~76 dmg absorption missing I think.

Also tried several times with a lvl 13 mob whose attack hit for 27 dmg:
Absorbed 3 attacks then received 5 dmg, which I think totals an absorption of just 103 dmg if none were crits, or 159 if *all* were crits.

Not sure if I'm missing sth obv here, or it's just a problem with the tooltip, or sth else. I tried briefly with shammy absorb as well and the difference between tooltip and actual absorb was ~120.

**Comment by noisestorm** [comment]
Remember: Absorbs count before your Resistances. So you got 0 Armor while Abs is calculated

**Comment by Zealote** [comment]
Ahhh damn ofc it's only tough that's taken into account isn't it? Just tried quick on one mob, with 0 armor and was 415 absorbed.

Sorry for false alarm.

**Comment by ozarmidrashim** [comment]
Closing.
