### ISSUE TITLE
Heal Grid not working properly

### ISSUE THREAD

**Issue by novitaun** [WarEmu/WarBugs#9615]
This morning my heal grid worked properly I connected myself some hours after and it does not work:

Does not show warband members
Does not show party members
Does not show friendly scenario members

These windows are not shown either in game or on the layout editor, they have varnished

The Heal Grid GUI configurator shows no information for sections Group, Warband and Scenariogroup

**Comment by Luth-RoR** [comment]
The bugtracker is only for server and client issues, not addons. Other group addons work fine, as well as the normal group UI.
