### ISSUE TITLE
Git to da choppa breaks Incognito.

### ISSUE THREAD

**Issue by Lemonpie1** [WarEmu/WarBugs#9618]
http://imgur.com/m3aT49A

**Comment by Torquemadra** [comment]
and?

**Comment by Lemonpie1** [comment]
it shouldn't

**Comment by Torquemadra** [comment]
why?

**Comment by Luth-RoR** [comment]
Is it even confirmed wether GtdC broke it or a successful stealth check?

**Comment by Luth-RoR** [comment]
Known issue (if not intended): https://github.com/WarEmu/WarBugs/issues/5166#issuecomment-211121406
