### ISSUE TITLE
Postional skills.

### ISSUE THREAD

**Issue by Lemonpie1** [WarEmu/WarBugs#9620]
When you use Pistol Whip or Burn Away lies without Feinted Position on a target that turns away they sometimes stop do nothing and  go on cooldown.

**Comment by Krimalicious** [comment]
correct...that happens also with all WE finishers.

**Comment by Nadril21** [comment]
This would happen to me occasionally, but the past few weeks it has gotten a lot worse. Atleast 50% of the time it seems lately, if the target is moving and I use PW/BAL on them (with or without Feinted Position, it does not seem to make any difference), the ability goes on CD but does not fire. It is not blocked/parried or anything, there is nothing at all in combat log about me using it, but it gets a CD.

**Comment by Luth-RoR** [comment]
What is your ping to the server (shown short after login in the chat window)?

**Comment by Krimalicious** [comment]
mine is 250s and happens quite often...it get worse if you try to spam buttons with mouse softwares...

**Comment by Luth-RoR** [comment]
>it get worse if you try to spam buttons with mouse softwares

Yes ofc. By spamming abilities, the client will send one ability occasionally on cooldown, while the server is only executing one at a time/per global cooldown. See: https://github.com/WarEmu/WarBugs/issues/8902#issuecomment-274892676
I guess the effect happens more often with longer packet travelling times to the server.

Does this often happen after the opening attack from stealth, for instance right after "enfeebling strike"?

**Comment by Krimalicious** [comment]
If you dont use Feinted Position right after stealth...yes  + players riding 60% mounts to make things worse

What I do is...bind enfeebling strike + feinted position together so this bug doesnt happen...
WE/WHs basicaly have to waste feinted position right after stealth to play properly..

Can fix by removing the position requiriment from Pistol Whip/ Heart Seeker, Sacrificial Stab/ Burn Away Lies...

**Comment by Zealote** [comment]
> Can fix by removing the position requiriment from Pistol Whip/ Heart Seeker, Sacrificial Stab/ Burn Away Lies...

Lol.

In case it's related or a more general issue... 'Point-Blank' M1 knockback quite often goes on cd, with no effect or dmg, when I use it while strafing. Seems unlikely to be a coincidence that both issues involve relative player position/orientation.

**Comment by Luth-RoR** [comment]
Yes, probaly the same issue, maybe for the client you had a legit angle to the target, but for the server not.

**Comment by Lemonpie1** [comment]
Noticed the moral thing as well tho further in the past for me since this used to happen to my engineer a lot with cannon smash and people seemingly in range, as we're all aware there is a massive client/server issue since warhammer was released and phantom range, desync and a horrible netcode were always a problem plaguing the game I bet its one of these. It can easily be reproduced with Declare Anathema as proof for the lag/desync just make a 180° turn whilst jumping you should be punted where your back is facing tho you will be punted in the opposite direction instead which indicates that your back didn't instant spin with you i tried this with a friend and on his screen i didn't turn until i had landed again which indicates that there is actually a full 0.5-1 sec delay.
