### ISSUE TITLE
Marching Orders

### ISSUE THREAD

**Issue by ingurbard** [WarEmu/WarBugs#9622]
![ingur_063](https://cloud.githubusercontent.com/assets/28376479/25889023/0573c750-352e-11e7-8c21-4b695c1d90d2.jpg)

To make story short, quest tasks were completed but questgiver doest have the quest topic anymore. I post it bc I didnt find it in searcher and its frustating to b unable to finish sveral qusts, i feel i wasted my time, many quests in the High Elf vs Dark Elf area were bugged too and I didnt complain knowing I'd get little atention,

**Comment by Luth-RoR** [comment]
There seems to be an issue with that NPC in general: https://github.com/WarEmu/WarBugs/issues/7881
Furthermore the term "alpha phase" in red letters under "Return of Reckoning" implies that the game is in an unfinished state: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=16391

**Comment by ingurbard** [comment]
Ok

**Comment by Ryanfawkez** [comment]
You're at the wrong NPC. Hand-in point is at General Ludwig Klunst, not Captain Lieberholz.

**Comment by ingurbard** [comment]
I considered that possibility (bc he had a complete quest marker) but I clicked him nothing happened either 

    El Domingo, 14 de mayo, 2017 5:58:20, Ryan Fawkez <notifications@github.com> escribió:
 

 You're at the wrong NPC. Hand-in point is at General Ludwig Klunst, not Captain Lieberholz.—
