### ISSUE TITLE
[Public Quest] Caladain's Furnace not working

### ISSUE THREAD

**Issue by Novgoroth** [WarEmu/WarBugs#9623]
The PQ Caladain's Furnace (DW chap19 hard) is no longer working. It is supposed to work for a while now, i've done it many times, and it is set as working on the PQ guide.
Right now, when you are on the PQ, there is no PQ indicator, and there is less mobs than usual.
Maybe because doable once after a reboot ?

**Comment by grunbag** [comment]
Fixed in next patch
