### ISSUE TITLE
ToK unlock 'The Picks & Goggles'

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9629]
This order only History & Lore unlock should be triggered by entering inside Picks & Goggles tavern in dwarf chap 1 in Ekrund (22k 39k).

**Comment by Ryanfawkez** [comment]
Proximity unlock.

**Comment by MaxHayman** [comment]
![image](https://user-images.githubusercontent.com/1018809/91671995-4c9d9580-eb23-11ea-8e84-d79c0ca070c4.png)
