### ISSUE TITLE
NullReferenceException from GenerateLoot : Krul gor ambushers

### ISSUE THREAD

**Issue by acidicrain** [WarEmu/WarBugs#9632]
![fluf_000](https://cloud.githubusercontent.com/assets/28633576/25966927/c3e20238-368c-11e7-86c6-5607a6c73ac5.jpg)

was pve mob grinding and got this error, sounds like posible a loot item in table which may not be right, a guess only SS included

**Comment by wargrimnir** [comment]
Does this happen every time they're killed?

**Comment by acidicrain** [comment]
Hi
No this happened probably twice while PVE mob leveling on these mobs. There was no adverse affect to me other than no loot from the two mobs , that's why I suspected it was some unclean item in the loot table for these guys. 
This issue has very low impact and low occurrence .
/hendrik

**Comment by sioding** [comment]
Fixed with patch from 4.11.2017
