### ISSUE TITLE
Stuck Location in Talabec Dam

### ISSUE THREAD

**Issue by dansarii** [WarEmu/WarBugs#9633]
Happened when someone got punted into the wall after an ally turned in the keg.
![stuck talabec dam](https://cloud.githubusercontent.com/assets/25072274/26023196/ce9d8424-3784-11e7-91e2-fd267845fd76.png)

**Comment by landgoat** [comment]
I too have also gotten stuck here after the enemy detonated the bomb: https://imgur.com/a/IRfhU .. hope this helps.

**Comment by NorKalli** [comment]
invisible walls placed

**Comment by sioding** [comment]
Fixed with Hotfix from 29.04.2017
