### ISSUE TITLE
The Gift of War quest not working all the time for killcounts

### ISSUE THREAD

**Issue by Novgoroth** [WarEmu/WarBugs#9635]
I was debolster in t3 (on all 3 zones) with 2 other mates, and made a bunch of kills on different people, but the kill counts are not taken most of the time.
Impossible to get a killcount on empire people.
I checked if people were debolstered, or t2 or t3 level, if you get the killblow or not, but it does not influence at all.
After about 100 kills in the party, i was about 1 dwarf kill, 9 elves kills, and 0 empire kills.
Anyway, people are still looting medals, stuff and seals. So only the quest seems bug, not the killing mechanic itself.

**Comment by Torquemadra** [comment]
was an issue with debolster, fixed next patch
