### ISSUE TITLE
The Key to Success Bugged

### ISSUE THREAD

**Issue by IxanderousI** [WarEmu/WarBugs#9636]
Description on the wiki reads as.......

Use the "Talisman Key" that is gained from Battered But Not Forgotten and use it on a "Battered Strongbox" at 59700,32900 in the Chaos Wastes. The box is in the northeast corner of the "Reaping Fields" PQ, behind a bush. The chest will be opened and reveal a smaller chest inside and you will get the following text:

You now see that the shape of the talisman matches the shape where the initials are engraved. As you apply the talisman to the strongbox, the chest opens with a magical burst.

Click on the smaller "Battered Strongbox" to receive a "Bejewelled Skull". Click on the "Bejewelled Skull" in your inventory to spawn Cihtym, a level 39 Champion Bloodletter and see the following text:

Deciding to tinker with the skull, you knock out the gems from the eye sockets.

Kill Cihtym to receive the unlock.

***********************************

I have attempted to do this by clicking on the box but nothing happens, i receive no item is received so the Cihtym champion will not spawn and cannot receive bestial token.

**Comment by Luth-RoR** [comment]
This requires additional coding and can't be fixed yet: https://github.com/WarEmu/WarBugs/issues/6102
