### ISSUE TITLE
Altdorf crashes

### ISSUE THREAD

**Issue by Halhammer** [WarEmu/WarBugs#9637]
Massive crashes for me in Altdorf again since the last patch. Dunno if already reported.

**Comment by Vancerus** [comment]
Same for some of my guildmates and myself. The crash is not triggered by any active player action, just by standing there. can´t stay in Altdorf for a long time since a few days. Can´t figure out, what´s triggering it. In group or outside group doesn´t matter, crashes too.

**Comment by Simmox** [comment]
i get this occasionally.it seems to be in and around the market square.
and only if i have logged off in that area,prior to relogging.
log/relog at the bank or war quarter has no ill effects.

if i log on and im in market square and i move immediately away from market square(to say the bank area) i can continue without fault.if however i remain at MS for a min or 2,it will crash to character screen and possibly even desktop once or twice

**Comment by Kaelang** [comment]
As this was related to a particular patch, from 2017, I'm going to ahead and close this up for the time being.
