### ISSUE TITLE
[Quest] Conqueror Quests 'Battle for...'

### ISSUE THREAD

**Issue by Halhammer** [WarEmu/WarBugs#9638]
The 'Battle for Dragonwake/Praag/Thunder Mountain' quests that reward you 4 medals seem to be bugged when turning in. Can only report for the Dragonwake one so far, got all kills but the quest guys at the BOs in Caledor are greyed out.

Edit: Battle for TM works fine

Edit2: Battle for Praag workin as well

**Comment by Halhammer** [comment]
Now I can't retake the Battle for TM quest on one of my toons, seems to be workin on others.

**Comment by Luth-RoR** [comment]
Just to be sure: did check if you can take any new quests when this happened (max. quest limit not reached)?

**Comment by Halhammer** [comment]
Yea I have 26 active quests on that toon, so not even close to the limit.

**Comment by Luth-RoR** [comment]
k, thanks.

**Comment by Halhammer** [comment]
Same thing just happened now with the Secure Eataine quest.

I've noticed the quest text reads '... speak to any Wrath's Resolve Vanquisher'. 
There are no Wrath's Resolve Vanquishers in DW, only Covenant of Flame Vanquishers, dunno if that's somehow related.

**Comment by lawfol** [comment]
The quest give in npc are mixed up...you need to bring in DW quest in DW instead of Caledor , andthe Eataine conq eust in Caledor instead of dragonwake. Ifthe other 6 quests are the norm to "push the pairing".

**Comment by wargrimnir** [comment]
Fixed turn ins so they advance the campaign as intended. Eataine quest should turn in at Dragonwake BO's, Dragonwake quest should turn in at Caledor BO's
