### ISSUE TITLE
Queuing for scenarios in Altdorf sometimes fails 

### ISSUE THREAD

**Issue by novitaun** [WarEmu/WarBugs#9640]
Hello

I noticed that randomly when you queue for a scenario in Altdorf it assumes that you are in combat and it does not let you in (obviously you are not in combat you might even be crafting or at the auction). Even using the book of binding to teleport to another location does not solve this.

I am not the only player facing this issue as per now I know at least one person having this problem. Although it is not happening allways it sometimes happens. Workarround is to close client and log back in the game again.

Thanks br
Jose

**Comment by Luth-RoR** [comment]
This bug is well known and the only way to fix this is to type .u or .unlock in the chat window.

**Comment by novitaun** [comment]
Thanks a ton  better that than having to restart ;)

Much appreciated
