### ISSUE TITLE
5 Piece Bonus Conq (Preservation) - Doesn't proc from being hit by guard damage

### ISSUE THREAD

**Issue by Zoggof** [WarEmu/WarBugs#9642]
Should the Conqueror 5 piece bonus (Preservation - On being hit: 10% chance to increase wounds by 100 for 20 seconds) for the tank archetype **not** be proc'ing from guard damage?

![zoggof_040](https://cloud.githubusercontent.com/assets/23256143/26034167/b8a9bf98-38fb-11e7-8eab-e5eac07bd85e.jpg)

**Comment by Torquemadra** [comment]
yes, its a proc off direct damage, guard damage isnt.
