### ISSUE TITLE
renown carrer stats

### ISSUE THREAD

**Issue by DRyOLCU** [WarEmu/WarBugs#9648]
i am renown rank 13 now. from the beginning of my play time i couldnt give renown points. always it shows less then that i have and the skill points i gave not shown in my skill screen. and when i come back to trainer again i see that totally wrong renown stats shown. (at rr 13 i see 7 used 2 left for example and no skill shown) thank you - escordie chosen

**Comment by Luth-RoR** [comment]
Known and just visual: https://github.com/WarEmu/WarBugs/issues/1486
