### ISSUE TITLE
Blood of the black Cain SC

### ISSUE THREAD

**Issue by Celticwitch** [WarEmu/WarBugs#9650]
Playing a WE -  the flags are not registering me as being stood by them, OUT OF STEALTH - its almost like they think i am still stealthed.  This has happened on 2 SCs now where the flags won't change to red while i stand there, tried restealthing and unstealthing again but still didn't seem to register me as being there, the flag only moved and turned red when other destro players stood with me.

**Comment by Kaelang** [comment]
This no longer happens on the current version of RoR. Please re-open if you are finding the issue persisting somehow.
