### ISSUE TITLE
IB/BG - Grudge/Hate gets stuck at 95/98/99

### ISSUE THREAD

**Issue by tutti13** [WarEmu/WarBugs#966]
Sometimes, my grudge gets stuck at 98/99 and doesnt increase to 100.

**Comment by Evildoor** [comment]
Never encountered this issue in proper combat, but when i was testing some other bug report on my BG today, my hate indeed got stuck on 95 until i spent a part of it.

**Comment by Luth-RoR** [comment]
Is this still an issue?

**Comment by wargrimnir** [comment]
Mechanic was refined recently. Should alleviate this issue.
