### ISSUE TITLE
[WP] Divine Assault broken

### ISSUE THREAD

**Issue by Tyrean** [WarEmu/WarBugs#968]
I all ! 

I got a problem whit divine assault abilitie when i want to use it sometimes i cant launch it or the abilitie begin but after 0.5 or 1 second it's stopped .

**Comment by grumcajs** [comment]
It is same as for example shammy chanelled ability. Or same for every cast time ability. Looks like when you cast a spell and you do not wait for the animation to finish, your next cast time spell would fail - your toon would start to cast bu after 0,5 sec or so the casting would stop. Same for divine assault 1 tick

**Comment by Evildoor** [comment]
Known general issue unrelated to Divine Assault. Closing.
