### ISSUE TITLE
elf quests (the blighted isles)

### ISSUE THREAD

**Issue by lilsabin** [WarEmu/WarBugs#9684]
Hi , there is a quest named " Tireless Honor" that doesnt work correctly , the quest is completed , but i cannot turn it in ...it is in the begining , you have to save a "MOURNFIRE" then talk to him to complete quest . but i cannot talk to him to complete it :)

**Comment by Luth-RoR** [comment]
Known: https://github.com/WarEmu/WarBugs/issues/7923
