### ISSUE TITLE
Public Quests

### ISSUE THREAD

**Issue by ChilontheBW** [WarEmu/WarBugs#969]
Im not sure if this is an issue in other areas but in Nordland all the PQ's go to stage 3 and then abruptly reset as soon as a player enters the PQ area. Also when the timer runs out, no objective is shown and nothing can be done to progress in the PQ.

**Comment by Radiantknight** [comment]
PQs actually reset now to stage 1.

**Comment by Stefanosgr18** [comment]
Yes this is a general bug...and the most critical to make ALL PQs unfunctionall unfortunately. We have to wait...

**Comment by Evildoor** [comment]
First steps regarding the PQs were made, so this will be outdated pretty soon (if not already).
