### ISSUE TITLE
Guild XP moast likly the cause of moast of the ORVR lag.

### ISSUE THREAD

**Issue by roadkillrobin** [WarEmu/WarBugs#9690]
When making and playing as a Guild warband you see huge lagspikes, especially upon getting kills. Moast likly due to the assisted guild xp the entire guild is generating. 

After Wargrimm decided to close my thread about experimenting with loot to reduce ORVR lag i decided to look into another option suggested in the thread. Whole guild was complaining about laggy RVR except for Tyr  who was the only member not from Phalanx playing with us atm. He said he got no lag at all. So i decided to leave the guild while still playing in the warband and it increased my performance to hights that I never seen before. Then more people tried it aswell and experienced the same performance increase. The lag was completly gone. Eventually there was so few people left in the guild that we didn't generate very much Guild xp and those still guilded stopped lagging aswell. 

On Tyrs request one guildy made a video domonstrating perforamnce difference between being guilded and not. The start of the video shows him guilded morale dumping and the end after he left. Its pretty clear that it has a massive impact on the peformance. 

You can ask pretty much any active Phalanx member they will confirm the performance increase

https://www.youtube.com/watch?v=6caLiNswuWs&feature=youtu.be

**Comment by Luth-RoR** [comment]
I think the implementation of guild features is over a year old now and iirc some features were hardcoded, e.g. the first two upper guild ranks have forced, exclusive officer chat read/write permissions, while the according settings don't do anything. 
There are probably some more features which are not working as intended.

**Comment by Haojun-Phalanx** [comment]
The difference between being in a guild / without a guild is crucial. The game %100 more smooth without guild now.

**Comment by Haojun-Phalanx** [comment]
Lag is back with/without the guild. I dunno whats changed in 2 weeks. The game is unplayable as bomb warband.

**Comment by Luth-RoR** [comment]
Something was changed in the last patch; can you confirm if it's still happening?
_Fixed a performance issue caused by guilds less than level 20 with many members online_
https://returnofreckoning.com/forum/viewtopic.php?f=42&t=21564

**Comment by Haojun-Phalanx** [comment]
We can confirm it tomorrow or sunday -official warband day.-

**Comment by Luth-RoR** [comment]
Thanks.
