### ISSUE TITLE
Rally Master 'Prince Endhil' location

### ISSUE THREAD

**Issue by Lheana** [WarEmu/WarBugs#9691]
This Rally Master appears at 3 locations : at his correct elf chapter 20 and at elf chapter 19 (7k 48.2k) in Dragonwake. I don't think he is meant to be at chapter 19.
Edit : I noticed he is at Elf Chapter 21 too, next to a dragon in Caledor (49.3k 49.7k).

**Comment by Ryanfawkez** [comment]
Probably part of a questline.

**Comment by Razielhell** [comment]
About Chapter 21 #8386

**Comment by sioding** [comment]
fixed with patch from 31.08.2019
