### ISSUE TITLE
Can't select character in selection screen

### ISSUE THREAD

**Issue by Templergun** [WarEmu/WarBugs#9695]
Hi,

below on my screenshot you can see my big Blackork. And behind him stands my small Zealot.
So the problem i have right now is, due to the bigger hitbox of the Blackork i cant click my Zealot to play with him. But i dont want to delete any other characters to shift their standing positions around.

Can you impliment a priorityorder, that for example Orks get positioned in the back in order to avoid this problem?
I now have to unequip my helmet every time i log out to be able to click on my zealot.^^

![warhammer-cant-click-character](https://cloud.githubusercontent.com/assets/28786625/26211236/62b5a9a4-3bf2-11e7-9f77-f17d30c8adb4.png)

Kind Regards
Gohr

**Comment by Luth-RoR** [comment]
This is high likely completely handled by the client.

**Comment by Luth-RoR** [comment]
Confirmed as client sided issue; can't be fixed yet.
