### ISSUE TITLE
Horse twitch/jump problem. quest items (chaos story)

### ISSUE THREAD

**Issue by doombot696** [WarEmu/WarBugs#9696]
when i stand still but turn my mount its legs twitch. look into it please. and when i jump while moving foreward with my mount i stand on it. I also stand on it when my horse and i are idle. In all horse problems. please fix that. quest items that are visible interactive quest objects ingame can be used infinitely during a quest and may intefere with completing quests. fix. merchants dont have any ware

**Comment by Luth-RoR** [comment]
Read the bugtracker rules.
