### ISSUE TITLE
Objective Guards:Ekrund and Mount Bloodhorn

### ISSUE THREAD

**Issue by ChilontheBW** [WarEmu/WarBugs#970]
All the NPC's at the objectives in Ekrund and Mount Bloodhorn are about twice as high as they should be. They range from lvl 18 to 24.

**Comment by Lumberjackscoot** [comment]
Yeah this kinda makes taking a BO extremely challenging without a healer but with Tank and dps. They also have like a 2 to 3 min CD making them respawn really really quick. Any word on this?

**Comment by Luth-RoR** [comment]
RvR contend will be and has been constantly reworked, tested and reworked again.
