### ISSUE TITLE
Secure Black Crag! conq quest

### ISSUE THREAD

**Issue by Palitelj** [WarEmu/WarBugs#9700]
There is no npc Kazad Damaz Ead Basha in Tunder Mountain, so quest Secure Black Crag is impossible to finish. Checked on every BO, every sergant is called Bloodfist Rock Ead Basha.

**Comment by Zoggof** [comment]
Kazad Dammaz Ead Basha are the BO sergeants in Kadrin Valley.

**Comment by Palitelj** [comment]
Yes I know but if you read quest it says bring back to any Kazad Damaz Ead Basha in Thunder Mountain. Quests for 8 medalions should finish in mid zones.

**Comment by wargrimnir** [comment]
Fixed in next
