### ISSUE TITLE
SM tactic "Blessing of Heaven" and Bolstering Enchantment"

### ISSUE THREAD

**Issue by kam19080** [WarEmu/WarBugs#9702]
Is it work in getting RP for healing allies before?

Could it be getting RP for the ally healing?

It could not get any RP for the healing at now.

Is it normal (couldn't get the RP) for this tactic?

**Comment by kam19080** [comment]
Additional: Was the beer of eng (Healing skill) earning any RP while healing allies?

**Comment by Luth-RoR** [comment]
Questions are for the advice chat, the support forum or www.google.com; the bugtracker is only for bugs.
Please read the bugtracker rules.
Hint: it was already stated several times by the devs that the flawed handling from the mythic server for out-of-group healing won't be implemented here for obvious reasons.
