### ISSUE TITLE
[Loot] Dead people cannot get normal need/greed/pass loot

### ISSUE THREAD

**Issue by OldPlayer** [WarEmu/WarBugs#9704]
Dead person gets need/greed/pass window, but his choice is ignored by client and is not shown in logs. The roll will be made without dead person's response and living players will get the loot as usual.
If all living players have passed, loot will be lost.

Have repeatedly tested it with a friend.

**Comment by Luth-RoR** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/7494
