### ISSUE TITLE
Secure the Chaos Wastes

### ISSUE THREAD

**Issue by kalmatar** [WarEmu/WarBugs#9706]
Destro CW Conq kill quest seems to count kills done in Praag too, allowing it to be repeated in case one fetches quest during Praag fighting by visiting CW at some point. If I recall, Praag kill quest was also counting kills done in Reikland few days ago; meaning that Chaos pairing kill quests might be counting kills in all Chaos/Emp RvR lake areas? 
Not gamebreaking, but feels somewhat cheesy to do 2x Chaos Waste 8 medal quests a day; 20 medals feels so much more than the usual 5-10 earned in one evening.

**Comment by wargrimnir** [comment]
That's how progression works for the quests as intended.

CW + Praag
Praag + Reikland
Reikland alone
