### ISSUE TITLE
Unable to mount manticore due to career restriction

### ISSUE THREAD

**Issue by taccr** [WarEmu/WarBugs#9707]
Self-explanatory.
Cannot mount my manticore anymore as maurader :(

![manticore](https://cloud.githubusercontent.com/assets/14852547/26279771/5956e44c-3dbc-11e7-8ae3-02928cdaa672.png)

**Comment by Torquemadra** [comment]
contact a GM in game for a replacement, they had models fixed for warriors and orcs
