### ISSUE TITLE
Engineer Turret's

### ISSUE THREAD

**Issue by ChilontheBW** [WarEmu/WarBugs#971]
Two things, first the Flamethrower Turret doesn't attack things when in aggressive mode, or protective.
Strange thing is, when I use the attack command it works for 1 or two attacks then stops.

Second, the special abilities for the turrets disappeared, I found them in the ability story but they are not purchasable. But they seem to work every now and again when I go to and from scenarios.

**Comment by Evildoor** [comment]
Tested Flame Turret, works fine. Second problem is known and occurs to all pets. Closing.
