### ISSUE TITLE
Bug because of the created characters

### ISSUE THREAD

**Issue by htyrmd** [WarEmu/WarBugs#9711]
Yesterday I have created the character "Zzzzzzzzzzzzzz" https://www.returnofreckoning.com/armory.php?character_id=660834&character_name=Zzzzzzzzzzzzzz. I ask you it to remove as at me after his creation such window hangs here. https://ibb.co/gVpgyF

**Comment by Luth-RoR** [comment]
The bugtracker is only for bugs not for support requests.
