### ISSUE TITLE
PQ problem 

### ISSUE THREAD

**Issue by geolyk** [WarEmu/WarBugs#9723]
At stage 3 is asking 8 hero to kill and only one is poping ..area Dragonwake
![koukou_002](https://cloud.githubusercontent.com/assets/26933999/26364481/2a5893ec-3fed-11e7-80ca-fea1642712ea.jpg)

**Comment by Luth-RoR** [comment]
Known: https://github.com/WarEmu/WarBugs/issues/7432 and besides that, a bug report should be more descriptive, i.e. "pq problem" is a bad title.
