### ISSUE TITLE
Whoosha's boys PQ in Death Peak

### ISSUE THREAD

**Issue by grunbag** [WarEmu/WarBugs#9729]
there is a problem on stage 1 of this PQ : kills don't count for the right mob : 
![skragg_010](https://cloud.githubusercontent.com/assets/24207191/26409021/ac85d534-409f-11e7-8622-5af74423241c.jpg)

also , champion at last stage got bugged texture when he's dead 
!
![skragg_014](https://cloud.githubusercontent.com/assets/24207191/26409070/d1d245fc-409f-11e7-86ee-fb95dfe6e1a2.jpg)
[skragg_013](https://cloud.githubusercontent.com/assets/24207191/26409062/cb602e28-409f-11e7-9d33-b9a47b73396d.jpg)

**Comment by Luth-RoR** [comment]
>kills don't count for the right mob

Which mob is not counted correctly?

**Comment by grunbag** [comment]
The 3 of them are wrong . Squig count as rope , and rope/gits count as gits

**Comment by Razielhell** [comment]
Maybe the already known problem with counter?

**Comment by grunbag** [comment]
after checking it's a visual bug, you can close the issue

**Comment by Razielhell** [comment]
#6935
