### ISSUE TITLE
[Swordmaster] Tactic - Bolstering Enchantments heal scales off blade enchantment level not mastery level

### ISSUE THREAD

**Issue by Osgrim** [WarEmu/WarBugs#9732]
I'm not sure if this is intentional but Ive found the tactic is weaker when using lower level blade enchantments. In order to get the ,max healing you have to use the blade enchantment with the most mastery points invested in.

**Comment by Luth-RoR** [comment]
Seems like a bug; should scale with mastery points in path of hoeth.

**Comment by roadkillrobin** [comment]
I reported this exactly same thing on Black Orcs You got nuffin! about a year ago

**Comment by Luth-RoR** [comment]
Thanks, merging with https://github.com/WarEmu/WarBugs/issues/6113
