### ISSUE TITLE
Sc Objectives

### ISSUE THREAD

**Issue by Lemonpie1** [WarEmu/WarBugs#9733]
Temple of Isha*, Howling Gorge Talabec Dam all of them have objectives you have to carry and if you blow up or die with them in hand you can neither stealth nor mount up for the entire scenario. If you don't let the cast to place the keg finish, the same happens. Yes, you can place the keg instantly by just clicking the barrel once and will be rewarded with points even when you don't finish the cast. 

*Isha is a special snowflake because you can't stealth or mount up with the objective even as WH tho it doesn't glitch out on death.

**Comment by Luth-RoR** [comment]
This is known for a long time and there are already several reports about each issue.
