### ISSUE TITLE
Enter Key resizing game to window mode RESTART FIXES

### ISSUE THREAD

**Issue by Grimmark** [WarEmu/WarBugs#9736]
Kinda odd and annoying.. Whenever I try messaging buds or guildies, the screen resizes itself to the window mode. I somewhat made it less annoying by making the window mode size the same as full screen size. 

I fixed it by restarting the game.

Thought I'd share for anyone else having the problem and to give it to the devs

**Comment by Luth-RoR** [comment]
High likely related to the client OS or the WAR client. Both can't be fixed by RoR staff.
