### ISSUE TITLE
Cant log in + Workaround

### ISSUE THREAD

**Issue by Templergun** [WarEmu/WarBugs#9739]
Hi,

today around 13:50 UTC+1 (German time) 
I got disconnected from the game in Talabec after we locked the zone,
I am not sure why. maybe somewone flew to IC but i could not connect back to Talabecland.
I cleared my cache. logged in ith different character but i could not enter Talabec with my other character.

My way of workaround:
Because youa re able to use the chat while being in loadingscreen i typed /stuck two times. and the loading screen switched to norsca. so i  was able to enter the game properly again.

I hope this woks for some as well.

Greetings
Squigmasta / Gohr

**Comment by milosxe** [comment]
I have been crashing a lot around destro Tala wc whole day

**Comment by Luth-RoR** [comment]
>My way of workaround:
Because youa re able to use the chat while being in loadingscreen i typed /stuck two times. and the loading screen switched to norsca. so i was able to enter the game properly again.

Thanks, but this is well known.
