### ISSUE TITLE
Dwarf chapter 17 influence rewards

### ISSUE THREAD

**Issue by svenimir** [WarEmu/WarBugs#9740]
For the Ironbreaker, there are 4 elite weapons available.  All show both hands.  The Mititempered greatweapon show both hands or off hand.  Weapon DPS is for a greatweapon, but stats appear to be for a one hand weapon.

**Comment by wargrimnir** [comment]
Added class requirements. Ironbreakers receive defensive 2h weapons, Slayers receive offensive 2h weapons, Mititempered Hammer adjusted for Engineers.
