### ISSUE TITLE
[Bring it On]

### ISSUE THREAD

**Issue by roadkillrobin** [WarEmu/WarBugs#9741]
This abillity seem to only be able to hit 1 target back every ICD wich is really wierd for an abillity in a AoE Mastery. I'm asuming the Slayers equvilent is the same due to ICD being handled in the same way. I'm guessing  It should be ICD on the target that attacks you not ICD on the abillity itself

**Comment by Luth-RoR** [comment]
Ability tooltip says "this effect can only be triggered once every second" which is different from, for instance, the kotbs "on your guard" (targets can only be damaged once every two seconds). 
As there is no evidence that it worked like OYG and is working according to it's tooltip, it's a case for the balance suggestion subforum.
