### ISSUE TITLE
I think i solved the "Guild bugged my char" bug

### ISSUE THREAD

**Issue by Lerilla** [WarEmu/WarBugs#9742]
I had the problem with my char that i have dcs when i tried to join scs when i was in a guild. I tried some things, even with the help from a gm. Nothing really helped.

Now i changed my char name and i havent any dcs. Maybe this simple trick solves this problem.

**Comment by Luth-RoR** [comment]
Thanks, merging with https://github.com/WarEmu/WarBugs/issues/8009
