### ISSUE TITLE
[Warrior Priest] AP regen while Divine Assault

### ISSUE THREAD

**Issue by cl0wndavid** [WarEmu/WarBugs#9745]
Hello,

performing Divine Assault on WP prevents the AP to regen.
I never noticed it on live, since i was able to empty Ap -> Divine Assault -> use AP abilities again.

Would be great if someone could look after it.

Best regards

**Comment by Luth-RoR** [comment]
AP regen was bugged for a long time on the EA servers; no AP regen during channeling or building up a spell is working as on the EA servers and is intended.
