### ISSUE TITLE
Nerx Gutslime has RvR Lord damage debuff

### ISSUE THREAD

**Issue by geolyk** [WarEmu/WarBugs#9746]
The boss is having the Lords buff -75% incoming dmg
Mount Bloodhorn  Lair of Gutslime
![gouga_008](https://cloud.githubusercontent.com/assets/26933999/26584169/96f966e4-4550-11e7-8796-71f07f690c53.jpg)

**Comment by Lheana** [comment]
The lair boss does not seem to have again this buff.
