### ISSUE TITLE
Quest : Cleansing an Empire

### ISSUE THREAD

**Issue by Smokeras** [WarEmu/WarBugs#9747]
The stage that  want you to click on structures like a)guilty pyre b)guilty rack c) guilty cage cant complete.Option C( guilty cage) cant be click because the stracture is inside barriers. **29928,42424 talabecland** 

![smokemygun_052](https://cloud.githubusercontent.com/assets/22015063/26586727/c1b2db60-4558-11e7-9976-b56eddcdc8ff.jpg)

**Comment by wargrimnir** [comment]
This can be found outside of Unterbaum as well.
