### ISSUE TITLE
/stuck command not working

### ISSUE THREAD

**Issue by novitaun** [WarEmu/WarBugs#9749]
Hello

Got stuck at chaos wastes order keep on the outer wall when trying to jump down. Tried to use /stuck several times but the game just loged me off. Whenever I tried to log in, it would place me on the same place again .... stuck.
My book of binding had a 26 minute timer.

It would be cool that for these cases you could implement a /suicide command so at least you are able to spawn on a different place.

Thanks & regards
Jose

**Comment by Luth-RoR** [comment]
During the login screen hit enter and type /stuck and enter and again enter, /stuck and enter (2x /stuck); this will port you to the starting location.
