### ISSUE TITLE
[Black Orc] Da Toughest! war bellow doesn't increase wounds when bolstered

### ISSUE THREAD

**Issue by Zealote** [WarEmu/WarBugs#975]
It still heals for the correct amount, just doesn't increase wounds.

Bolstered from lvl 13, in case it's relevant.

**Comment by ozarmidrashim** [comment]
Bug affects everyone on the server - Bolster counted as a Buff and its bonuses would not stack with other buffs.

Fixed in next.

**Comment by milosxe** [comment]
Tested with lvl13 BO in t2 RvR. Fixed. Closing.
