### ISSUE TITLE
[Blackguard] 2H Knockdown (Get Down) CLEANSABLE

### ISSUE THREAD

**Issue by Vancerus** [WarEmu/WarBugs#9750]
Hello guys!

The Blackguard 2h Knockdown, Get Down, is Ailment and therefore cleansable. Therefore gamebraking.

Tested with AM cleanse.
Please fix as SOON as possible. Thank you.

Cheers,
Vancero

**Comment by Torquemadra** [comment]
as is every other KD

**Comment by Kaloell** [comment]
nope.
Neither AM nor WP can cleanse the Chosen KD.
We tested it before with various other KD's and classes, but did not record it.
All of them were labeled "Damaging" only the BG KD is an "Ailment".
![gwyndolinn_024](https://cloud.githubusercontent.com/assets/29151272/26740328/5ed2d75a-47d5-11e7-82fa-6bd495c6ccfb.jpg)
If you need help testing it feel free to ask one of us...

**Comment by Vancerus** [comment]
@Torquemadra Thank you for your in depth answer.

WE KD not cleansable either. Tested with AM & WP.
SW KD not cleansable as well.

Need more? We are more than glad to help you.

![vancecca_008](https://cloud.githubusercontent.com/assets/14907399/26741681/a9115bc0-47da-11e7-9422-e3c561aea86c.jpg)
