### ISSUE TITLE
Guild Recall Scroll Cooldown bugged (no cooldown!)

### ISSUE THREAD

**Issue by Benwyse** [WarEmu/WarBugs#9752]
When using the recall scrolls and LEAVING the guild hall the cooldown of guild recall scrolls gets reset. It still shows the 30min timer on the scroll icon, but when clicking the scroll is usable.

Now, when using the recalls scrolls, buying new scrolls and leaving the guild hall the timer even resets on the scroll icon and is no longer displayed as "in cooldown".
In the moment when using guild recall scrolls (that would normally still have a cooldown) the regular cooldown is shown on the scroll icon and will remain (without effect) if you cancel scroll activation.

Effectively recall scrolls have no cooldown timer at the moment. However they know that they should have one and know their regular cooldown time.

**Comment by Luth-RoR** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/8020
