### ISSUE TITLE
Update display and lootchest from Public Quest  bugging

### ISSUE THREAD

**Issue by Snuski** [WarEmu/WarBugs#9756]
Seems like the update display on pq's only updates once the zone is left. 
The loot chests from pq's won't give loot. Pressing the loot chest is possible but nothing happens!

This was experienced on public quest Bells of war and some other pq in ostland and norland on the destruction faction

**Comment by Razielhell** [comment]
> Seems like the update display on pq's only updates once the zone is left.
#6935?
