### ISSUE TITLE
[Blackguard] 2H Knockdown (Get Down) CLEANSABLE #9750

### ISSUE THREAD

**Issue by Vancerus** [WarEmu/WarBugs#9757]
Some may believe the care inside the Bugtracker is insufficient, but we still believe we should contribute errors to a defective game/database.

So @Torquemadra, you quickly closed our report prematurely and continued to ignore the proof we provided.
Therefore we had to open a new one, which we hope, for the future of the report system, will be investigated with proper care this time. 

Please see report #9750 for more information and proof provided by 2 parties.

Thank you so far for your proper examination.
Cheers,
Vance

**Comment by wargrimnir** [comment]
From a different perspective, this ability will likely remain cleansable until we have client control. The buff handler that was used, already existing in the client, is what requires it to be flagged as an Ailment. While we could change behavior on the server to force it to be a Damaging effect, any healer that can cleanse an Ailment will still see their Cleanse ability as active. As a secondary note, as this ability was pulled from the client, it shows that at some point Mythic had hard CC effects tied to the cleanse system. Take that for what you will.

**Comment by Kaloell** [comment]
Nice to know, that Mythic had some discarded ideas.
I get that there is no perfect fix. But is this not exactly the same as detaunts not being cleansable?
Some were, the client flags them, pushing the cleanse ability just does nothing.
I don't think the cleanse ability lighting up is worse than being able to cleanse something you are not supposed to cleanse. Just like the detaunts.
Anyways, thanks for an actual answer. I hope you can find a way to fix it at some point.

**Comment by Vancerus** [comment]
Thank you for the statement.
