### ISSUE TITLE
Apothecary - Main ingredient Lvl 1 crits for Lvl 35 blue pots

### ISSUE THREAD

**Issue by Benwyse** [WarEmu/WarBugs#9758]
When using an apothecary level 1 main ingredient for crafting pots and you have a critical success the result is a blue lvl 35 potion.
Tested with
- main ingredient lvl 1 for main stat (tested int, str) (from cultivator, not butcher)
- secondary ingredient lvl 200 resin, multiplier, duration (from cultivator, not butcher)

**Comment by Torquemadra** [comment]
names please

**Comment by Luth-RoR** [comment]
Refering to https://github.com/WarEmu/WarBugs/issues/7096 and https://github.com/WarEmu/WarBugs/issues/1644
