### ISSUE TITLE
Two issues on this one.

### ISSUE THREAD

**Issue by SparkyTheOld** [WarEmu/WarBugs#9759]
First: not sure how common it is but as I was taking a stroll through Inevitable City around the Apex as Chosen Graxxor I happened to be warped into an unknown place called "Zone 0" and as I've died thrice in there as I was being constantly warped away from the Healer back to "Zone 0" to my inevitable death, but double /stuck fixed the problem. Second thing I noticed on my Marauder named Motrax, thing is with item called "Pummelers of the Eternal" as it has the same image in inventory as "Tramplers of the Eternal" and as I've browsed the Auction House it appears that "Bandit's Pummelers" face the exact same problem. Hope it was even little bit helpful.

**Comment by Luth-RoR** [comment]
Zone 0 bug is almost as old as RoR and happens only very rarely nowadays: https://github.com/WarEmu/WarBugs/issues/6831
On items: not every single item has a separate icon, there are not enough available on the client.
In the future please one bug per report.
