### ISSUE TITLE
Deadly Rock by Wayshrine of Sigmar

### ISSUE THREAD

**Issue by Gitzpoon** [WarEmu/WarBugs#9761]
![gitzpoon_000](https://cloud.githubusercontent.com/assets/29190593/26770765/58e8cdd2-496e-11e7-8794-ec2a3e175c7f.jpg)
![gitzpoon_002](https://cloud.githubusercontent.com/assets/29190593/26770815/c68a66b6-496e-11e7-8dcb-c8049b1d35d9.jpg)
![inkedgitzpoon_003_li](https://cloud.githubusercontent.com/assets/29190593/26770827/e94a9d74-496e-11e7-9722-73737f570da1.jpg)

There is a rock next to the Chapter 6 Party Quest Wayshrine of Sigmar. It is two rocks(on the side closest to the Warcamp/Crypt of Weapons) right next to eachother with one being slightly higher than the other. If you stand on the lower rock and jump up to the higher one it kills you. I've tested it multiple times and so have my friends. My character name is Gitzpoon.

**Comment by Luth-RoR** [comment]
Thanks but this is a well known bug and DB devs stopped with bandaid fixes because there are too many of those spots around; instead the root of the problem is still searched.
