### ISSUE TITLE
Riposte tactic has no internal CD

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#9762]
on live it has 1 sec cd

http://take.ms/QdcgZ

**Comment by Nfkillz** [comment]
proff https://www.youtube.com/watch?v=9hdEvb3PTA4&t=77s
1:33 count parries and ripostes proc
37s 3 parries (impale, AA,AA) and 1 riposte proc

**Comment by Luth-RoR** [comment]
Thanks a lot.

**Comment by Silentguard** [comment]
Thanks for the awesome video. As i told. Basic rule of WHO procs - if it have no described cooldown than it have 1 sec by default.

**Comment by Torquemadra** [comment]
There is no blocker in place for a ICD on riposte therefore we cannot add one.

**Comment by Nfkillz** [comment]
prob better turn off this tactic because of a lot abusers like 2-3x dmg from it or decrease dmg.

**Comment by geezereur** [comment]
This tactic is way to OP in its current form.

**Comment by sioding** [comment]
This is not a forum nor a balance talk. If you wanna bring in a proposal to change something use our forum. Thanks.
