### ISSUE TITLE
Continuous CTD upon entering Reikland Keep Outer door 

### ISSUE THREAD

**Issue by Gnashspike** [WarEmu/WarBugs#9763]
Haven't played in almost 9 months. Since returning, RoR has played flawlessly from log in til log out in wee hours of morning(s). This is the first time since returning to RoR this has happened, and the first time since travelling to Reikland Keep (Morr's Repose). The ride from the WC to the outer door was flawless as well.

As the title says; and successively and immediately after logging back in (complete log off of launcher each time; reproduced even after restarting my rig. The GF (Dontdie Yet, Zealot) and I play sitting right next to each other as we have since live. This used to happen to her quite a bit (she loves to "rage O/S reset" her comp) due to corrupted registry items. I've had my share of DC's, but never in succession like this. Have the newest Xfinity access point; both of us are hard wired to it. Both of us have been very candid with devs/mods regarding this (Aza was the first) so as not to appear to be defying ToS (multi-boxing/multi-accounts/spying, etc.) so i don't think it's that. Plus as I type this, the GF's still playing, but having great difficulty rezzing troops as many of those needing rez's (corpses to click) are not visible on her screen. In addition, and maybe the, or one of the reasons might have been a multitude of Order appeared this instant many other of my WB members were experiencing CTD. Experienced many crashes on live and RoR when that is case. Not implying anything other than probably the good ol' mass-log-and-relog-to-opposition when those on the "winning" side motivate themselves toward the belief that CHOOSING a side is somehow detrimental to game mechanics and server operational challenges, therefore it MUST be done to retain some kind of integrity/self respect, or worse, believe it is THE solution to the survival of most PvP (RvR) computer games.

Or it could be the update about 2 hours ago that placed the NPCs at the Wyvern perch (Gnoblar, Chosen, etc. Hope this gets fixed SOON. Cheers!

**Comment by Luth-RoR** [comment]
There are many reports about odd crashes already on the bugtracker. About your connection to the server: it depends on more than your hardware, there could be also temporary issues with packet routing or general ISP problems etc.
In the future please restrain yourself on writing down useful information instead of long stories containing useless info about x-realming and the like. Thanks.

**Comment by Gnashspike** [comment]
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "Luth [Masked]" <FWD-737QTYSMENAIYCQANIQDDYCDEBMCIZLAI2UAJYAOENM3M35AKYQQYQYX5YAIME4QBHQBTLQIIUMXWHGINA4GKDRCORSNQPMSPQCXBCSL4ZAVYQSSGJCUTGCEAFI42GFMIA5QDOS4RQIDQJAYAAVEEYSAE4QC4MBJGARHAIJQFJYOGO7AD3QBNYALWUQO2YEAGCQQAIAAEA======@opayq.com> is being returned by server outscan-backup.junkemailfilter.com on Sun, 11 Jun 2017 02:44:31 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  sadlyknotmyself@gmail.com
    host alt2.gmail-smtp-in.l.google.com [173.194.219.27]
    SMTP error from remote mail server after RCPT TO:<sadlyknotmyself@gmail.com>:
    452-4.2.2 The email account that you tried to reach is over quota. Please direct
    452-4.2.2 the recipient to
    452 4.2.2  https://support.google.com/mail/?p=OverQuotaTemp t71si1558614ywf.382 - gsmtp:
    retry timeout exceeded

**Comment by Gnashspike** [comment]
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "Luth [Masked]" <FWD-737QTYSMENAIYCQANIQDDYCDEBMCIZLAI2UAJYAOENM3M35AKYQQYQYX5YAIME4QBHQBTLQIIUMXWHGINA4GKDRCORSNQPMSPQCXBCSL4ZAVYQSSGJCUTGCEAFI42GFMIA5QDOS4RQIDQJAYAAVEEYSAE4QC4MBJGARHAIJQFJYOGO7AD3QBNYALWUQO2YEAGCQQAIAAEA======@opayq.com> is being returned by server outscan-backup.junkemailfilter.com on Sun, 11 Jun 2017 03:03:18 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  sadlyknotmyself@gmail.com
    host alt2.gmail-smtp-in.l.google.com [173.194.219.26]
    SMTP error from remote mail server after RCPT TO:<sadlyknotmyself@gmail.com>:
    452-4.2.2 The email account that you tried to reach is over quota. Please direct
    452-4.2.2 the recipient to
    452 4.2.2  https://support.google.com/mail/?p=OverQuotaTemp w67si1508186ywe.1 - gsmtp:
    retry timeout exceeded
