### ISSUE TITLE
[Arghmage]-Walk between Worlds -duration is incorrect

### ISSUE THREAD

**Issue by murmelon** [WarEmu/WarBugs#977]
Walk between Worlds- duration 10 sec instead 5

**Comment by ozarmidrashim** [comment]
Will not modify per #824

**Comment by Silentguard** [comment]
https://youtu.be/3NQKiNGN8XU?t=4m43s

**Comment by dalen** [comment]
Looking into ability files, the AoE detaunt was in fact 10s duration, while the set back reduction effect was only 5s.
