### ISSUE TITLE
Stinkfang the Vomitous

### ISSUE THREAD

**Issue by zageen** [WarEmu/WarBugs#9772]
This boss just have a weird aggro, always switching between me and the dps , taunt doesn't work on him too .

**Comment by wargrimnir** [comment]
There are no mechanics attached to this boss,.

**Comment by Gnashspike** [comment]
** Recipient inbox full **

Your message couldn't be delivered to sadlyknotmyself@gmail.com. Their inbox is full, or it's getting too much mail right now.



The response was:

Storage quota exceeded

**Comment by sioding** [comment]
**Thanks for the report.** Since there is no confirmation, i will close this issue now. Please make sure to follow the bugtracker rules which you can find here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)
