### ISSUE TITLE
Quest / Tome Progress Reset after Debolstering for T1 Event

### ISSUE THREAD

**Issue by Absolem33** [WarEmu/WarBugs#9773]
This was day 1 of the Tier 1 3 year anniversary event.  This occurred just now, maybe 30 minutes ago by the time I post this.  I had debolstered down to t1 to do the event quest.  I logged out, possibly in the RvR lake, and logged back in maybe 2-3 hours later to find that my graphics settings had been reset, the chat filter was back on, I had no quests in my quest log, and my quest chains reset, I also seem to be missing substantial parts of my Tome progress on my character Otarin, on Order.  :(

I don't know what could've caused this bug.  I feel like it might have something to do with debolstering and logging out with my character debolstered, but I have no idea.  The event quest was the most recent quest in my log.  I have very few addons active, Miracle Grow, Squared, Potion Bar, and Buff Head.  I launched the game as I always do, using the RoR launcher, did not move or change any files in between log-ins.  The only out-of-the-ordinary thing I did was log out debolstered.   I'll attach the dxdiag of the pc I played on as well.

[DxDiag.txt](https://github.com/WarEmu/WarBugs/files/1053551/DxDiag.txt)

**Comment by Torquemadra** [comment]
being looked into

**Comment by Absolem33** [comment]
My Tome progress and quest log was restored when I logged in today after the latest patch.
