### ISSUE TITLE
Riposte not scaling with Choppa/slayer mechanic

### ISSUE THREAD

**Issue by Chopmasta** [WarEmu/WarBugs#9780]
As found in following video:  https://www.youtube.com/watch?v=9hdEvb3PTA4&t=77s
taken from ~1:30-2:30
Slayer riposte dmg scales based on mechanic: 
Green dmg = 310+(299 mitgated) = 609 total.
Yellow dmg = 393+(347 mitgated) = 740 total, 387+351 = 738 total
Red dmg = 360+(446 mitigated) = 805 total

Tested on RoR, no change in riposte dmg on mechanic change, consistent damage.

**Comment by Nfkillz** [comment]
[https://github.com/WarEmu/WarBugs/issues/2291](url)

**Comment by Luth-RoR** [comment]
Merged with #2291
