### ISSUE TITLE
Cinderash Enclave / Easy Public Quest  (Destruction)

### ISSUE THREAD

**Issue by Zaccar20** [WarEmu/WarBugs#9781]
Hey,
Cinderash Enclave / Easy Public Quest (Destruction) at Chaos Chapter 18 (RANK 36)
didn't work at the moment i think.
Stage 1:
Kill 20xCinderash Flamesword
Kill 20xCinderash Pyrepike

Some of the Cinderash Flameswords work but the Cinderash Pyrepike didn't count.
Killed about 30+ but its still 0/20.
Not working npcs also don't give any inf for Chap. 18

**Comment by grunbag** [comment]
Fixed on next patch
