### ISSUE TITLE
Gift of Monstrosity proc lost before timer exipres.

### ISSUE THREAD

**Issue by chrismath2004** [WarEmu/WarBugs#9782]
As you all know marauders have 3 different proc buffs depending on what mutation they choose. Typically when you proc a buff and then choose to swap to another mutation, the buff still persists until the timer runs out.

For example if you choose savagery and proc debuff on enemy, right after you switch to either monstrosity or brutality the debuff on the enemy will continue until it runs out of time (5 sec timer). Similarly if you choose brutality and proc gift on yourself, right after you switch to either savagery or monstrosity the buff will continue until time expires.

However this is not the case with the "gift of monstrosity". If you proc the buff on yourself and decide to switch mutation, as soon as you do so the buff will vanish regardless that there was a remaining timer on it to begin with.

I'll be happy to provide more information on the topic. Thanks for the attention.

**Comment by Luth-RoR** [comment]
Could be intended.

**Comment by Kaloell** [comment]
I have no idea if its right/ balanced/ intended, but:
It seems Gift of Monstrositys buff was removed on live too, upon switching mutations.
First google hit searching for a rr100 marauder: https://youtu.be/jINtZ9XLpew?t=1m45s
It was not removed by anything else, since SWs don't have something to remove it, and there was no other enemy nearby.

**Comment by Luth-RoR** [comment]
Monstrosity buff is 5 seconds, so maybe it expired. I can't see the timer because of the quality of the video. Nevertheless it could be an intended change on RoR.

**Comment by Kaloell** [comment]
It procs just before he switches. The timer has about 4.5s left. I probably should have written that in the first place...

**Comment by Luth-RoR** [comment]
Ah ok at 1.49-1.50 with 0.25 speed i saw it, thanks.
