### ISSUE TITLE
[ITEM] "Merciless" dagger

### ISSUE THREAD

**Issue by murmelon** [WarEmu/WarBugs#9783]
Is it possible to make "Merciless" dagger available for off hand too, like other daggers for Witch elf?
![milady_005](https://user-images.githubusercontent.com/12655727/26878324-c8d24ac8-4b95-11e7-855e-996489a42b2c.jpg)

**Comment by wargrimnir** [comment]
The Bugtracker is not an appropriate place for requests. This is where we keep track of actual problems.

**Comment by murmelon** [comment]
i write like that because i dont know is it done special or bug

**Comment by Torquemadra** [comment]
not a bug
