### ISSUE TITLE
'Dreamshade Forest' Public Question and so the 'Deathbringer' and 'Legend and Infamy' Quests

### ISSUE THREAD

**Issue by EoinSpetre** [WarEmu/WarBugs#9784]
I am a trying to do the 'Deathbringer' and the 'Legend and Infamy' quests where I have to kill Dreamshade Hunters and Dreamshade Ambushers, respectively. At the same time I was also going to farm the 'Dreamshade Forest' Public Quest to get Renown. However, the Hunters and Ambushers don't seem to be spawning. The Whisperers are there along with the guy on the horse and the White Lions to the North but no one else. I can hear them talking, I think, and sometimes it sounds like I've aggro'ed them but I don't enter combat and nothing else happens. This is really annoying to say the least.

**Comment by Luth-RoR** [comment]
One bug per report and according to closed reports, the quests and the PQ should work. If something is bugged, please post evidence in the old reports that can be find via search function or open new ones with evidence: https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366

>This is really annoying to say the least.

Ok. 
https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=16391
