### ISSUE TITLE
PQ: Order, Chap. 2, Burning Windmill Stage 3 does not register kill

### ISSUE THREAD

**Issue by dockmeister** [WarEmu/WarBugs#9786]
PQ: The Burning Windmill
Loc: Order, Nordland, Chap. 2

The objective in Stage 3 is to kill Seeker Flamer and Volkryth Flamecaller. While the kill of Seeker Flamer gets registered fine, the kill on Volkryth Flamecaller is not.

I killed him 3 times, without success:
![burning_windmill_pq](https://user-images.githubusercontent.com/1413853/26972184-f6769066-4d10-11e7-8eee-d1ba064442bf.jpg)

**Comment by grunbag** [comment]
Fixed in next Patch
