### ISSUE TITLE
Guild Heraldry Problem

### ISSUE THREAD

**Issue by Talorth** [WarEmu/WarBugs#9791]
I am a leader of a guild called Elite chaos and I had 100 gold and I used it to buy my guild a cool heraldry flag. I made the flag the color I wanted but when I went to do the emblem on it I put number 81 and when I paid the 100 gold it showed up as the number 1 emblem/ default one and I was kinda mad I lost 100 gold. If anyone can fix this bug or help me get emblem 81 on my guild flag that would be awesome, Thank you!

**Comment by Ufurious** [comment]
I am still having a similar issue and it's been almost a week with the only help from the GM's is "wait for server restart".....I still can't change my Heraldry colors, and my gold was deducted for the change....any and all help will be appreciated.
Thank you

**Comment by sunspearhonor** [comment]
Same issue for me, the colors and pattern took, however the emblem itself did not. I was asked by a GM to keep trying as it was buggy and it costed me 100 gold and no change to the emblem, yet the money was deducted from my account. Was attempting to use Empire emblem 22/111

**Comment by crimsonlotus1978** [comment]
I am having the same issue. Guild- Vanguard of Thorns. Just spent over an hour choosing empire heraldry and emblem 105/276, but when I exited the appearance of emblem 1 has defaulted. Please help!

**Comment by Kruelistik** [comment]
I am having the same issue. Guild Unsainted. Shape 1/Pattern 39/Emblem 80. Chose the heraldry and it didn't take, after a re-log I tried again and only the pattern and colour took but not the emblem. Spent 100g tryin to fix this. Please fix and maybe reimburse :)!

**Comment by 816384138** [comment]
So apparently others are having this issue as well. Is there any plan to reimburse or direction for how to fix?

**Comment by crimsonlotus1978** [comment]
> So apparently others are having this issue as well. Is there any plan to reimburse or direction for how to fix?

Not yet that I have heard.

**Comment by Xicoz** [comment]
@Kaelang I believe the issue is that the emblem for cloak and everything else unlocks at level 20, where as u can choose it at lvl 10(making people think their cloak reservation wasn't working) but if u reserve at 10, and wait till 20, your emblem will start to display correctly. so an easy fix would either be let emblem unlock at 10, or state it more clearly that it wont show up on cloaks until 20

**Comment by Whitebeardcz** [comment]
Hello. I just tried to change our guild heraldry. The same problem. 100g are away, only colors and pattern is made. No emblem. I wanted to take number 85. Can you please repair it?

**Comment by Unknown-zz** [comment]
I have this same issue on my guild <Tzeentch and Chong>.  My char Deadsled paid 100g but only the color, shape and trim saved, please change emblem to 23.

**Comment by LordVanidas** [comment]
I'm having the same issue changing my heraldry. Everything changed fine except the symbol, and it deducted me an extra 100 gold. If anyone knows what's up with this, help would be much appreciated.

**Comment by Whitebeardcz** [comment]
Hi. If your guild level is something about 15 or how many it was, you dont change your heraldry, you only reserve it. Look at the bonuses you get with guild level. There is just a reservation. Guild heraldry you get later, 10 levels later or something like that. Odesláno z mého zařízení Galaxy
-------- Původní zpráva --------Od: Vanidas ***@***.***> Datum: 15.01.22  23:41  (GMT+01:00) Komu: WarEmu/WarBugs ***@***.***> Cc: Whitebeardcz ***@***.***>, Comment ***@***.***> Předmět: Re: [WarEmu/WarBugs] Guild Heraldry Problem (#9791) 
I'm having the same issue changing my heraldry. Everything changed fine except the symbol, and it deducted me an extra 100 gold. If anyone knows what's up with this, help would be much appreciated.
