### ISSUE TITLE
KV lock not granting Influence.

### ISSUE THREAD

**Issue by TenhiYT** [WarEmu/WarBugs#9793]
Like the title says locking zones seems to not award influence for me. It happend for the 3rd time now and this time around I took some screenshots. First time was in TM where it didnt apply the influence, and now KV two times in a row. Charactername is Celil. From what I can tell its not a visual problem, the ToK still shows me missing some points and the Rally Master doesnt offer the reward to me.

![celil_000](https://user-images.githubusercontent.com/29344146/27006715-bd9ac61e-4e3b-11e7-8da6-7cb87f87deea.jpg)

![celil_003](https://user-images.githubusercontent.com/29344146/27006717-c797eeee-4e3b-11e7-8374-c4bbf2917bad.jpg)

**Comment by sioding** [comment]
**Thanks for the report.** Since there is no confirmation, i will close this issue now. You can help us by following the bugtracker rules which you can find here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)
