### ISSUE TITLE
Book of Binding

### ISSUE THREAD

**Issue by ChilontheBW** [WarEmu/WarBugs#9797]
Strangest thing, every time I am bound to the Altdorf rally master and use the book of binding it teleports me to zone 0 and I die instantaneously. I have tried this a handful of times now and its a tad bit frustrating.

**Comment by Luth-RoR** [comment]
Should be fixed according to https://github.com/WarEmu/WarBugs/issues/6080
Maybe bugged again.

**Comment by NorKalli** [comment]
Is this still an issue?

**Comment by sioding** [comment]
No reaction since 15 days. close.
