### ISSUE TITLE
[Slayer] [Influence Rewards][Armor Stats][T2-RVR]

### ISSUE THREAD

**Issue by papsbug** [WarEmu/WarBugs#980]
Looks like accurate stats or closer then now:
http://warhammeronline.wikia.com/wiki/Slayer_influence_rewards

this video have axe confirmation on stats and maybe more.
https://www.youtube.com/watch?v=4r8o-EnOpa4

**Comment by papsbug** [comment]
empire

gona write

**Comment by papsbug** [comment]
dwarf

**Comment by papsbug** [comment]
elf

**Comment by ShlomoSheckelberg** [comment]
Same for my WH and Mara

**Comment by Silentguard** [comment]
IMO need to actualize stats on this items.

**Comment by Paninii** [comment]
I'll just add here - Magus influence rewards don't seem correct. (Jewel with either wounds or strength and willpower chest)

**Comment by Evildoor** [comment]
All of the stats are now as they should be (list misses talisman slots on gloves), except for procs (not implemented yet) and missing talisman slot on Stonetroll Armbraces.

**Comment by Evildoor** [comment]
Closing per #4660
