### ISSUE TITLE
Chapter 16 Elf Tower of Lysean

### ISSUE THREAD

**Issue by svenimir** [WarEmu/WarBugs#9800]
PQ is shown as working (green).  The corsairs count toward the PQ but i couldnt get kill credit from the reavers or the bruisas that i killed.

**Comment by grunbag** [comment]
Fixed in next patch

**Comment by svenimir** [comment]
Just tried again on 6/19 around 2130 Eastern US time.  I killed all the Bruisas I saw and none counted toward PQ.   Reavers were complete when i got there, so I assume some counted.   I killed the Corsairs on the eastern side of the PQ and only 1 of the 5 counted.
