### ISSUE TITLE
3yrs old event bugs (Destro)

### ISSUE THREAD

**Issue by mwasp** [WarEmu/WarBugs#9801]
-Chaos moon Revisited-Spirit's coffin-Norsca Entrance 48K/44K
-Very Very Frightenin' -Redmane Trasure Vault -Black Crag 59.7K/29.5K

Both destro event spots broken, bugged (tested bíy Chosen and BO, Choppa)

**Comment by Ryanfawkez** [comment]
Should work fine now on live.
