### ISSUE TITLE
[ Combat Mechanic ] Annihilate/Disastrous Cascade Range

### ISSUE THREAD

**Issue by Haojun-Phalanx** [WarEmu/WarBugs#9804]
![aoe](https://user-images.githubusercontent.com/23129933/27031083-795f9c12-4f77-11e7-9b05-cdd1cd4b70d1.jpg)

I tested on both classes BW/Sorc, these abilities not acting like 30 feet, actually around like 15-20.
Can provide video later.

I think related something about this thread aswell.

https://www.returnofreckoning.com/forum/viewtopic.php?f=8&t=21045&hilit=sticky+feetz+range

**Comment by Luth-RoR** [comment]
Closing for the same reasons as stated here: https://github.com/WarEmu/WarBugs/issues/9525#issuecomment-298095317
