### ISSUE TITLE
[ Item ] Guild Scrolls can be used with cooldown.

### ISSUE THREAD

**Issue by Haojun-Phalanx** [WarEmu/WarBugs#9805]
I'm not sure what caused this but guild scrolls are avaliable even with cooldown.

**Comment by Kaloell** [comment]
This also applies to the Book of Binding. When changing zone the cooldown gets removed, but still displayed. If you click it, you can use it, despite the displayed cooldown.
I think it has been this way since the "cooldown rework on zone change" in general and was told it might be intentional(?).

**Comment by Luth-RoR** [comment]
Known: https://github.com/WarEmu/WarBugs/issues/8020
