### ISSUE TITLE
Portal from Tablecland - Reikland does not work

### ISSUE THREAD

**Issue by Fractus1484** [WarEmu/WarBugs#9807]
When trying to use PVE the portal from Tablecland to Reikland, it does not work from Tablecland, screenshot attached
![talitus_113](https://user-images.githubusercontent.com/26185873/27044022-0a0dbcf0-4f94-11e7-82a1-a82fb995df29.jpg)

**Comment by Luth-RoR** [comment]
Known: https://github.com/WarEmu/WarBugs/issues/5671
