### ISSUE TITLE
Oil Bug

### ISSUE THREAD

**Issue by Goruk** [WarEmu/WarBugs#9809]
I have seen 3 Players on the Keepdoor and they dont taking Demage from the Oil.
I have two screenshots

**Comment by peusnaugrim** [comment]
Right if you enter inside the ram at extreme range to left and right fo the ram. You don't take oil damage.

**Comment by Goruk** [comment]
thats too

**Comment by Goruk** [comment]
But under the Oil?

**Comment by peusnaugrim** [comment]
Under oil is fine you took damage.  Its just at extreme range when you entre inside the ram particulary to the left and the right of the ram.

**Comment by Luth-RoR** [comment]
>I have two screenshots

**Comment by sioding** [comment]
**Thanks for the report.** Since there is no confirmation, i will close this issue now. You can help us by following the bugtracker rules which you can find here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)
