### ISSUE TITLE
Abilities refusing to fire

### ISSUE THREAD

**Issue by Toldavf** [WarEmu/WarBugs#981]
I've noticed it allot some times when I'm chasing a target unless I'm actually touching them abilities will refuse to fire in spite of clearly being in range. Could be lag or client disagreement I guess but it is annoying yo not be able to fire abilities if your target is moving directly away from you.

**Comment by Thorgatin** [comment]
Afaik it's network lag between the clients and there are no ability queues on the server yet.

**Comment by Evildoor** [comment]
Improvements regarding this problem were implemented in one of the recent patches, and now melee abilities work much better, so i'm closing this.
