### ISSUE TITLE
Caledor Quest NPC/Bugs 

### ISSUE THREAD

**Issue by Valdena** [WarEmu/WarBugs#9812]
Questname:  "An Eye for Trouble" (aprox 2/2)
the marked quest area is outside the border of the map, in an erea that is forbiden, if you enter the quest area, you are teported to your bindig point. Also the quest description contains the following message: "Invalid creatur- QuestID 44621,Objld=1722 0/8"

Questname:  "An Eye for Trouble" (aprox 29/3)
Kill "Wavebreaker Seafarer" and "Weary Wavebreaker" the seafarer can be found in the marked area, but not a single "Waery Wavebreaker" can be found there. 

Questname:  "An Eye for Trouble" (aprox 2/2) and  "An Eye for Trouble" (aprox 29/3)
Double quest name, due to the fakt that I can have them both active at the same time, there seems to be something wrong with it.

Questname: "Worth dying for"
Description says "Collect 14 shimmering scales from "ANY Dragon" but only "Scorchtail Dragons" seem to dropp them

Questname: Eagle Feathers
From Scroggo da Green, only provides 70 Exp. after comlpletion, which seem extremly little.

Questname: "A weapon of Doom"
Step: " Kill Escaped Engineer" 
It is the Quest NPC you should kill, but he stays friendly (blue) and can't be attacked.

NPC "Captured Engineer" (lvl 32)
the NPC exists two times in Caledor @ 35/12 and also @ 15/11

NPC "Scroggo da Green" (Lvl 1)
the NPC exists two times in Caledor @ 30/10 and also @ 27/7

Mob "Firewing Griffon" (lvl 32) 
Standing in the middle of the road @ 37/8 and is agrro (red) but won't attack. Also he can't be attacked melee, only ranged (pull), then he get's attackable in melee also.

Valdena, Witchelf, beloved of Morathi

**Comment by Luth-RoR** [comment]
One report per bug please and with ~ 1300 active reports there is a high chance that it was already reported, e.g. https://github.com/WarEmu/WarBugs/issues/5686
