### ISSUE TITLE
Spirit Coffin Bugged, blocking Chaos Moon Revisited

### ISSUE THREAD

**Issue by Melisandrea** [WarEmu/WarBugs#9813]
Since yesterday Spirit Coffin in Norsca is bugged, blocking amazing Chaos Moon Revisited event questline. Destro has 1 less event token at this moment. I checked this issue on several alts yesterday and today.

**Comment by geezereur** [comment]
Can confirm it worked yesterday but not today.

**Comment by Mortkin** [comment]
ye still not working

**Comment by Rildetarma** [comment]
This is still not working
