### ISSUE TITLE
[Zealot] Buff Ability Cooldown Bug

### ISSUE THREAD

**Issue by wwright72** [WarEmu/WarBugs#9815]
The Zoning cool-down bug is still happening to the zealot buff abilities. It happens when zoning or when you try to reapply the buff with it still on you.

![untitled](https://user-images.githubusercontent.com/29286837/27122594-d23650ee-50b0-11e7-818b-2b579dea5489.png)

This screenshot was taken 6/9, after the ability cool-down fix. I know it might be hard to see but my mark of the spell destroyer has a 5 digit cool-down

**Comment by Luth-RoR** [comment]
Merging with https://github.com/WarEmu/WarBugs/issues/9811
