### ISSUE TITLE
destro lord in caledor

### ISSUE THREAD

**Issue by AmidalaEstellanor** [WarEmu/WarBugs#9816]
With single target cannon/aoe cannon ,it's possible taunt the destro lord room in caledor out of the keep(on the outer wall) and damage it

http://imgur.com/WG9UsHq

**Comment by Luth-RoR** [comment]
Doesn't he reset his position and health points short after that happened?

**Comment by Luth-RoR** [comment]
Nevermind, it seems that the keeplord killed you. Don't try to shoot inside the lord room for whatever reason.

**Comment by AmidalaEstellanor** [comment]
It s possible taunt him more times.then if he kill me/ppl around cannons ,ofc he go back in his position with full hp.
But hit the lord keep was not my intention.intention was hit the destro players in the keep near oil spot!
In praag and cw for example i never saw this situation on destro keep(and i am using always the same cannon from outer wall)

**Comment by Luth-RoR** [comment]
The keeplord can't be made immune to siege damage, otherwise people would shoot into the lord room to kill the defenders there. The other keeps are differently designed by mythic and have high likely a wall between the oil and the keep lord.
