### ISSUE TITLE
High Elf Bolt Thrower @WC in Etaine

### ISSUE THREAD

**Issue by rekkir** [WarEmu/WarBugs#9817]
it hits like a truck! I think it is bugged?

Look at this video, fully charged it hits for 4 k then 2-2,5 k barely charged
https://www.youtube.com/watch?v=OKyhO9jhkd4&feature=youtu.be

**Comment by Luth-RoR** [comment]
>- Be careful if you approach warcamps or you will get surprised! Order and destruction gods are protecting them...

https://www.returnofreckoning.com/forum/viewtopic.php?f=42&t=21520
