### ISSUE TITLE
Slayer ability [Inevitable Doom] + tactic [Jagged edge]

### ISSUE THREAD

**Issue by rekkir** [WarEmu/WarBugs#9818]
As this video shows, the inevitable doom splash crit on NPC's standing in range and get crit will trigger jagged edge. IDK if this is intended, but it makes me think I should post about it

https://www.youtube.com/watch?v=dq8v-vb1gZo&feature=youtu.be

**Comment by Luth-RoR** [comment]
Slayer ability "Inevitable doom" was no normal DoT on the WAR server, every AoE tick counted as direct damage and will trigger procs. Working as intended in RoR too ofc.
