### ISSUE TITLE
missing gate lever.. Ostland....

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#982]
Hi..

This gate is missing a lever, can you please add it in for this quest pls..
Ostland 62k 45k

thx

**Comment by Meralors** [comment]
Cemetary door is fixing, there is a crypt door after that one I cant fix by now, we are still working on it ;)

**Comment by gittoaster** [comment]
I'm not exactly sure which crypt u talking about but one there is a far more complex ToK unlock in the area (graveyard)

**Comment by Meralors** [comment]
I fixed both door ( was a cemetary one and a crypt one, they are both working now. )
