### ISSUE TITLE
Scroll of the Inevitable City - Cooldown broken

### ISSUE THREAD

**Issue by retkeszaju** [WarEmu/WarBugs#9822]
Pretty much the tile says all, Scroll of the Inevitable City cooldown broken, i can use it countless times, its display the timer on it but beside that i can use it one after an other one. After a use i fly to a different zone than cast again.

**Comment by Luth-RoR** [comment]
Known https://github.com/WarEmu/WarBugs/issues/8020#issuecomment-305895254
