### ISSUE TITLE
Can't mount in Talabec dam after delivering bomb!

### ISSUE THREAD

**Issue by Snuski** [WarEmu/WarBugs#9824]
If you get "interrupted" while deploying the bomb then it still explodes and you gain points but afterwards you can't mount because it says "Can't do that while carrying an object" or something like that. This persist until you deploy the bomb without getting interrupted.

**Comment by Luth-RoR** [comment]
https://github.com/WarEmu/WarBugs/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20talabec%20dam
