### ISSUE TITLE
Quest Mob Hagar Ironrune is not in T2 Dwarf Warcamp Marshes of Madness

### ISSUE THREAD

**Issue by Spielteufel** [WarEmu/WarBugs#9825]
Quest Mob Hagar Ironrune is not in T2 Dwarf Warcamp Marshes of Madness and so i dont can finished 2 Quests. 

1. Know the Enemy
2. Trouble in the Marshes

Thx for help

**Comment by sioding** [comment]
checked - NPC is on his place
