### ISSUE TITLE
Inspiring Attack Iron breaker 

### ISSUE THREAD

**Issue by Arkute** [WarEmu/WarBugs#9827]
Probably Inspiring attack skill on brotherhood tree doesn't work as intended.

Tooltip states that it gives X amount of willpower per grudge gain.This much is true. But issue lies after that buff occurs. Once you reicieved appropriate amount of willpower it doesn't contribute to Disrupt...

On live it was my base for triggering tactic Avalanche from Brotherhood tree too.

I tested this with .getstat in game... and willpower from this skill do not affect Disrupt.

On request can provide screenshot or video of test.

**Comment by Luth-RoR** [comment]
All avoidance stats from weaponskill, initiative, willpower and shields are not shown in .getstats as they calculated directly against the enemies strength, intelligence and ballistic skill. For instance check .getstats with no additional parry modifieres and you will see that it shows no parry from weaponskill too. 
Only percentage based modifiers (e.g. +10% disrupt) are shown in .getstats.
