### ISSUE TITLE
I'm stuck and I can not get out. The command does not work

### ISSUE THREAD

**Issue by lo240** [WarEmu/WarBugs#9828]
![diridsteelhead_000](https://user-images.githubusercontent.com/29508802/27255202-e3489a7c-5399-11e7-933b-d5e1e24c78b2.jpg)

**Comment by Luth-RoR** [comment]
The bugtracker is not the support forum. Hit enter, type /stuck and hit enter then do it again quickly while still at the loading screen during log in.
