### ISSUE TITLE
Book Of Binding

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#9829]
Since a couple of days my Book Of Binding is having some issues. When I set my rally point for the Praag warcamp I end up in Chaos Wastes. When I set if for Caledor I end up in Eataine.

**Comment by wiscel** [comment]
Looked a bit more into it. It's not the Book Of Binding which is not working properly. It's the Rally Masters, for example the Reikland Rally Master sets your book of binding point to another Emp zone. And so on.

**Comment by saupreusse** [comment]
Can you tell which rally masters exactly?

**Comment by Razielhell** [comment]
Figured it out. Fixed next.

**Comment by sioding** [comment]
Fixed with patch 21.10.2017
