### ISSUE TITLE
PQ: Order, Chap. 8, Siege of Bohsenfels - Stage 2 does not register kills

### ISSUE THREAD

**Issue by dockmeister** [WarEmu/WarBugs#9831]
PQ: Siege of Bohsenfels
Loc: Ostland, Chap. 8

Kills of "Savage Corruptor"s in Stage 2, doesnt get registered by the PQ. I definitely killed more than 5, so its not just a visual bug.

![bugreport](https://user-images.githubusercontent.com/1413853/27264427-5b76f298-547e-11e7-8960-bfb8da628452.jpg)

**Comment by grunbag** [comment]
Fixed in Next Patch

**Comment by grunbag** [comment]
close it please
