### ISSUE TITLE
Dagger autoattack

### ISSUE THREAD

**Issue by spacestarkid13** [WarEmu/WarBugs#9833]
Every emblem dagger have the same AA like any other one-handed weapon. Dagger/Rapier/Pistol is the fastest type of weapons in game.

**Comment by wargrimnir** [comment]
This is not a bug. It's a complaint. Don't use the bugtracker to complain. If you have issues with weapons, you need to prove they are inappropriate. Not simply assume these weapons are not uniform when it's more than possible it could be by design.

**Comment by Krimalicious** [comment]
space...could you contact me in game? I have some idead we could work together to improve the game lore. 
@krima
