### ISSUE TITLE
chapter 10 dwarf influence

### ISSUE THREAD

**Issue by svenimir** [WarEmu/WarBugs#9834]
Rewards for the knight have a warrior priest book as an elite reward.  Doesnt show in the tome under ch 10, first saw it when i went to redeem rewards.

**Comment by svenimir** [comment]
![stacylynn_000](https://user-images.githubusercontent.com/19368711/27314234-7efa0e72-5540-11e7-9f07-116e4ee33c21.jpg)

**Comment by Razielhell** [comment]
Fixed next patch.

**Comment by sioding** [comment]
Fixed with patch 21.10.2017
