### ISSUE TITLE
Order PQ "Da Orcwerks" Highelf Ch15 not counting kills

### ISSUE THREAD

**Issue by Vancerus** [WarEmu/WarBugs#9835]
Hey guys,

As many other PQs at this time (dunno why) this one is not counting kills as well. Tried 4 days every day now. Unfortunately every time i looked into it, there was no GM online.

Cheers,
Vance

**Comment by wargrimnir** [comment]
Don't bother GM's with bugs, they can't fix them anyway. We pushed a hotfix related to PQ's an hour ago, try again.

**Comment by Vancerus** [comment]
Working again, thank you.

**Comment by Vancerus** [comment]
Bugged again.

**Comment by Torquemadra** [comment]
someones messed it up, wait for next pacth

**Comment by grunbag** [comment]
close it please
