### ISSUE TITLE
Scenario Pop closes after /rel 

### ISSUE THREAD

**Issue by Peppi1992** [WarEmu/WarBugs#9836]
Hey,
yesterday i joined the queue for SC and it popped.
Then i saw, that the Guildboard was bugged and i typed in /rel.
After that the SC window for joining disappeared and i couldn't join sc.
Even i couldn't  queue again... After a few mins trying all i could, i got deserteur for 10 min. :/
That was hard, cause i needed Elf kills for the eventq...

Greetz Shiekah

**Comment by Kaelang** [comment]
No longer happens on live version of RoR.
