### ISSUE TITLE
fireball too high dmg

### ISSUE THREAD

**Issue by Tesq** [WarEmu/WarBugs#9837]
![report](https://user-images.githubusercontent.com/7527415/27342864-a62da778-55e1-11e7-8f5a-b05e221ea49f.jpg)

per scrennshoot i think there is something wrong with fireball or either well someone is cheating

i got something pretty strange today a bw hitted me for 3k( 3k mitigated) with a fireball total of 6k of fireball of output

now max dmg at rr 70 with full spec into correct mastery is:

base skill dmg 659 (source warbuilder) +100% crit +250% crit from meccanic =is 2965.5 (mitigated like in this case would had been 1500) so there is either something wrong with fireball (doing 6k isntead 3k of dmg) or this bw hide something.

clear a bit max fireball dmg should be 3k before mitigation, i instead was hit by a 6k fireball (3k is considering raw stats wihth out int)(even with intelligence caped  is not more than 3910........)

possible explaination are either some strange stacking issue with  effect from sc where you can have a dmg buff which get keep around idk anyway worth ivnestigatin i think

About effect i was in logrin forge, out our side of the map as show on minimap, so i dont think there is anyway a bw that could had any dmg increase from any source.....and what is strange is that only fireball hitted me for so much all the other hits are low/normal value which make this even more strange as an effect that would increase dmg would had make all the hits higer.

Of course i can also provide teh screenshoot with name

**Comment by wargrimnir** [comment]
The buff in Logrin's Forge doubles damage. It lasts for 30s after both points are capped.

**Comment by Tesq** [comment]
k then all normal pretty high value anyway

**Comment by Tesq** [comment]
closing this as its way too old and way too many formula fix has been done
