### ISSUE TITLE
About Jewelry item named "Black Toof"

### ISSUE THREAD

**Issue by Xorakk** [WarEmu/WarBugs#9838]
On forum in the "T4 Accessory Tome Unlock Guide: Last Update - December 8, 2016" Section the cords given to Black Toof 49k, 10k where The mob Twisted Hound can be found cant be killed by Destro they in some kind "Alliance" and makes the target unkillable by destro.

Zone - Saphery
Cords - 49k, 10k
Object - 10x Chaos Hound Fang
Mob - Twisted Hound

with pleasent regards from Nemekhar the frindly chosen xD
![nemekhar_003](https://user-images.githubusercontent.com/29585339/27358688-0dfcae40-5618-11e7-82c5-d11edcd64898.jpg)

**Comment by saupreusse** [comment]
That was me. Fixed in next patch

**Comment by Xorakk** [comment]
Its fixed Thank you :D
