### ISSUE TITLE
[Barak Varr] Going to the end of the World

### ISSUE THREAD

**Issue by Blazi** [WarEmu/WarBugs#9841]
![blazing_136](https://user-images.githubusercontent.com/25330314/27429831-d18e4024-5746-11e7-8831-2b36ca38588a.jpg)
I know its not a bug but I dont think that you as a player are not supposed to go to an area where you can fall from the world all the time. Maybe you know about this because you placed a "Bloody Sun War Stompa" there to defend that place. And when you go further to that mountain behind that guy you see a lost tavern and a portal and some hills and trees.
![blazing_129](https://user-images.githubusercontent.com/25330314/27426914-6bbfbbdc-573d-11e7-8091-e6c919c8a810.jpg)
When you swim to the mountain (in the background) and go further you slightly come to an end.
![blazing_130](https://user-images.githubusercontent.com/25330314/27427077-fbe27fd8-573d-11e7-86a8-1699b8bc3978.jpg)

![blazing_145](https://user-images.githubusercontent.com/25330314/27427168-4ddd9be2-573e-11e7-89df-7d0ac9167ecd.jpg)

And there you go there is the end and of course you can fall of the cliff.
![blazing_147](https://user-images.githubusercontent.com/25330314/27427186-5a2369c2-573e-11e7-9343-1983b5ea0f26.jpg)
![blazing_152](https://user-images.githubusercontent.com/25330314/27427232-7fe8cd3c-573e-11e7-9d82-351afcf01c78.jpg)

I dont know if you can place a Terrain Collider or other barriers there that you cant do that anymore.

And if that post is nonsense delete it or close it.

thanks in advance :)

**Comment by saupreusse** [comment]
We need dangerous territories in our database to fix these issues. Need someone with knowledge on how to correctly setup new zones in the server.

**Comment by Blazi** [comment]
Oh ok well thats sad but thanks for the answer appreciate it :)

**Comment by NorKalli** [comment]
long ago fixed
