### ISSUE TITLE
Gholnaros the Deathless quest not updated after kill

### ISSUE THREAD

**Issue by Melisandrea** [WarEmu/WarBugs#9844]
BL quest wasnt updated after our group killed Gholnaros the Deathless around 4. pm CET. After we killed Xaphan the Pyre in Caledor (updated normally, went orange, done) we went in to Gholnaros lair with our destro group, killed order group fighting with DW dragon, boss reseted. We started boss and killed it quickly, there were no other players in lair, just our group. After kill BL quest on mine BG character Mahnson remained the same as before kill (no kill update on Gholnaros, name still white on quest), i asked ppl in group, some other (Dogman) confirmed it might be bug. Or maybie whole BL was already disabled at 4 pm CEt today...

**Comment by Lheana** [comment]
Beastlord quests have changed, so I don't think this is still an issue.
