### ISSUE TITLE
Mob allocation bug table same purple items for hours...

### ISSUE THREAD

**Issue by peusnaugrim** [WarEmu/WarBugs#9847]
HI, after farming squig in Black crag for more than 7 hours always drop the same purple items : "the boundless solerets" It was the only purple item dropped so I got it **12** times in 7 hours... Also during all this time I got only 2 blue item.  May be you can fix it. Thanks

**Comment by wargrimnir** [comment]
Fixed the odd purple dropping. I don't see anything with the blues, would need more data.
