### ISSUE TITLE
Infinite resource

### ISSUE THREAD

**Issue by Warauros** [WarEmu/WarBugs#9850]
25.6.2017
Praag, Destro keep resources delivery.
Was delivering resources in Praag, On the way to keep i did kill a AM in front of a keep without taking any damage so i didnt drop the resources. After delivery at keep i didnt loose the aura and was able to deliver the resources multiple times(probably infinite). Went for the zerg to get killed which eventually reseted the resource aura.

**Comment by sioding** [comment]
since we have no resource delivery anymore - close

**Comment by Natherul** [comment]
Has this happened since the recent patch where I reworked the buffsystems backbone?

**Comment by sioding** [comment]
No answer since 13 days. Close
