### ISSUE TITLE
Skaven token NPC

### ISSUE THREAD

**Issue by Dragothurch** [WarEmu/WarBugs#9851]
Hi !

High Pass zone, skaven maze. Skaven npc who selling the pet for skaven token, not working. Can speak whit npc but not sell pet. Pls repair, thx. ( sry for my english)

**Comment by Razielhell** [comment]
sell or buy? if buy, do you have 4 tokens? Check backpack.

**Comment by Dragothurch** [comment]
I got 4 token and cant buy pet. NPC backpack empty, he does not offer anything.

**Comment by Lheana** [comment]
Warlord's Fell Hound (Destruction) and Imperial Hunting Hound (Order) are now once again buyable from Dexiol/Polintel, with 4 'Skaven Token'.
Tell if more items were sold by these vendors before.

**Comment by mwasp** [comment]
Polintel BROKEN.... has nothing to offer. The npc'c backpack is empty. (I have 4 tokens) and cannot buy anything from  him. I checked 5 minutes ago.

**Comment by Lheana** [comment]
It will be fixed in next patch, just be patient.

**Comment by mwasp** [comment]
Cool! Make my day! :)
