### ISSUE TITLE
1 Shot from WL

### ISSUE THREAD

**Issue by tlitschye** [WarEmu/WarBugs#9861]
Hey just got like 1 shotted from a WL.... WTF is that
![tlitschye_243_1](https://user-images.githubusercontent.com/20156460/27710084-bbb609de-5d1e-11e7-879a-8cdcac154c8f.jpg)

**Comment by Krimalicious** [comment]
Just another day at the office for WLs 👍 🥇

**Comment by tlitschye** [comment]
loved it!

**Comment by tlitschye** [comment]
Flames of Rhuin for 1k dmg!!!

**Comment by Noronn** [comment]
Hey. I was playing the WL. 
Witch elf stood about 30 feet in front of Black Crack order warcamp. 

Someone told me you get a buff when fighting near to your warcamp. Maybe that's what happened.

Cheers

**Comment by Nfkillz** [comment]
btw Flames of Rhuin on live worked only if bw was in 100 ft near to you. But on ROR bw can afk in Aldorf))))

**Comment by MRejou** [comment]
You should not approach warcamps, it's dangerous. No worries, you're not the first one ;)

--> closed
