### ISSUE TITLE
something wrong with subgugators proc or i am very lucky

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#9862]
3 procs in 1 sec. even with 2 weapons proc shoul be trigger 1 on 10 attacks

http://take.ms/2BfLz

**Comment by Krimalicious** [comment]
Weird..I have 2 weapons sub on my WE and it barely proc at all. I just checked forums and this mara has only one sub Weapon ! His dmg and DBs on that sce is abnormal for a rr 49 mara. 

WEs share the same proc on both daggers the concusion X also. Yet WHs, SHs have 2 kind of procs 1 for each weapon. for some reason 2 different procs seems to proc alot more than having 2 weapons with the same proc name.

**Comment by Nfkillz** [comment]
all procs in game should have 1 sec internal cd... as it was on live.
