### ISSUE TITLE
Gnol Baraz loot chest glitched

### ISSUE THREAD

**Issue by Jpederse2** [WarEmu/WarBugs#9863]
Hi! 

Yesterday, between around 6 and 7pm EST (NA), myself and a group of ~12 destruction players successfully raided and captured Gnol Baraz, the Order keep in Blackfire Pass. 

I wanted to report that the loot chest appeared and reported the winners, but didnt actually hand out the loot rewards. 

Thanks for your time and all the work you put it in on making this game run better.

**Comment by wargrimnir** [comment]
Loot should be delivered by mail if you don't get it at the keep. In rare occurrences it can show up quite some time later.

**Comment by sioding** [comment]
**Thanks for the report.** Since there is no confirmation, i will close this issue now. You can help us by following the bugtracker rules which you can find here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)
