### ISSUE TITLE
 PQ T1 CH1 Ekrund - Battle of Bitterstone Passive Boss Stage 3

### ISSUE THREAD

**Issue by Juppstein** [WarEmu/WarBugs#9866]
Smasha Skag is passive and does not attack when being hit. Animations are missing as well for him so he glides over the terrain. He can be killed though and the PQ can be finished. The other three Orks that are part of the quest objective fight and behave as expected.

**Comment by Razielhell** [comment]
You mean Krusha Skag?

**Comment by Torquemadra** [comment]
seems fine on dev

**Comment by Juppstein** [comment]
I did relog and it was still the same. And yes, it was Krusha Skag :)

**Comment by Lheana** [comment]
Changed something that could make him bug. So I close it (will be updated with next patch).
