### ISSUE TITLE
Mastery abilities don´t appear (shadow warrior)

### ISSUE THREAD

**Issue by Estigia59** [WarEmu/WarBugs#9867]
Hi! So I reached lvl 40 and went to get my mastery abilites, spent some points in the path of the scout, did everything right but then I didn´t get the abilities, they don´t appear so I cannot use them. I tried /rel but nothing happened. I took a screenshot.
![elbhereth_039](https://user-images.githubusercontent.com/29825413/27766001-0f2e2ab6-5ec2-11e7-82c1-ef9bd58476c3.jpg)
If I could get some help it would be much appreciated. Thanks!

**Comment by wargrimnir** [comment]
This is not appropriate for the bugtracker. Use the /advice channel in game.

**Comment by Estigia59** [comment]
I did, told what to do /rel etc, did it, still nothing, so I thought It might be a bug?

**Comment by Torquemadra** [comment]
you need to spend an additional point to 'buy' the ability so you reach the right level then click the ability to spend an additional point. Most of us fell for this at the start.
