### ISSUE TITLE
Sacrifices Rewarded (Witch elf) 

### ISSUE THREAD

**Issue by Krimalicious** [WarEmu/WarBugs#9868]
Its not absorbing the full dmg.. After first crit it abosorbed only 300 dmg..

On time 14;22;34 should have got the shield..since it was past 3 secs cooldown..it did not happened. 

Basicaly a very long fight vs a WH and it abosrbed only 300 dmg... its way off 

![sacrifices reward](https://user-images.githubusercontent.com/19318335/27766809-4e663f4c-5eb4-11e7-9930-10ce02233a1a.jpg)

**Comment by Torquemadra** [comment]
#9364
