### ISSUE TITLE
Officer medalion lost during transaction with NPC

### ISSUE THREAD

**Issue by Thifall** [WarEmu/WarBugs#9869]
Hello,

today, arround 12:20 after Order zone-lock (Eataine) i went back to IC Undercroft, to fill up my healing potions supplies. I had over 600 Soldier Medalions, and nearly 500 Officers. After changing soldiers to officers, I had round 600 medalions (or at least tooltip showed that). I bought 70 Officer's Healing Elixirs (1,5k heal pot for 1 Officer Medalio each), and wanted to buy few annihilator gloves/boots for salvaging. I did shit+rightclick to get multiple boots at once, typed 15 into textbox and droped on my bag inventory slot. Suprisingly - nothing happened. Or i should rather say, the purchase did not happen, cause i had too few medalions in my bag. Did not check medalions quantity in between pruchases, however I should have had 530 Officers Medalions before boots purchase, and 15 x 23 = 345, so even if purchase happened, but boots did not show in my inventory i should have more than 70 officers left.

No idea, what could have happen, have also no screenshots or detailed flow, cause i did not expect so casual thing to cause issue at that time.

**Comment by wargrimnir** [comment]
Buying multiple items with special currency is broken.

**Comment by sioding** [comment]
#8174
