### ISSUE TITLE
Caledor Manticore Bestiary bug

### ISSUE THREAD

**Issue by Cofry324** [WarEmu/WarBugs#9870]
There is a manticore in Caledor that you must kill for a bestial token. Whenever you get near it, a message pops up and says that I am in an illegal area and boots me back to the Inevitable City. My name in game is Rylde of Destruction. Dontdie of Destruction has also experienced this and a few other players I can not remember the names of.

**Comment by Lheana** [comment]
Was in fortress zone, I close this.
