### ISSUE TITLE
Runepriest AOE Resurrection Habilities not working in different levels

### ISSUE THREAD

**Issue by novitaun** [WarEmu/WarBugs#9871]
Affecting the following 2 habilities: Grimnir's Fury and morale 4 Alter Fate.

These habilities work as an aoe heal of 30 feet range. You can use them to resurrect even without line of sight for example through keep walls. 

The problem is that if the target death ally is on a different hight level they do not work (supposing that the dead ally is in range). 

Regards

**Comment by roadkillrobin** [comment]
AF working on RP? I havn't get it to work on any other healer.

**Comment by novitaun** [comment]
To be honest, I never managed to res anyone with AF, thought it was because of the levels.

Grimnir's fury does work (on the same level) when on different heights it does not.
