### ISSUE TITLE
Dueling bug

### ISSUE THREAD

**Issue by Cofry324** [WarEmu/WarBugs#9873]
I am Rylde of Destruction and I was dueling Caligula of Destruction. The duel would end but one of us would still be red and marked as a target. It left our party not being able to que  for scenarios. One of us would always have to log out in order to fix this and it was inconvenient. This has happened more than occasionally. Not sure if this is supposed to be apart of the game but it is annoying.

**Comment by Kaelang** [comment]
The duel system has been reworked. Please re-open if issues persist in the new Garden zone.
