### ISSUE TITLE
Unattackable npc in pve

### ISSUE THREAD

**Issue by Cofry324** [WarEmu/WarBugs#9875]
There are a number of npcs that cannot be attacked in the pve areas of this game in different zones.
- [x] Norsca, Carrion Seeker Vultures, 38k,36k
- [x] Dragonwake, Frenzied Manticore, 58k,47k

Dontdie of Destruction has confirmed that these creatures cannot be attacked

**Comment by Lheana** [comment]
Should be fixed in next patch
