### ISSUE TITLE
CoD reciver cancel trade = items from mail transfer to matrix

### ISSUE THREAD

**Issue by retkeszaju** [WarEmu/WarBugs#9878]
I sent 2 lvl 39 purple weapon to a guy, but we misunderstood each other, he only wanted to buy 1 item, so he canceled the trade, sent back the mail whitout pay, and i recive the mail, but whit no items in it... so somehow items lost in the abyss...

**Comment by tlitschye** [comment]
he just kept the weapons!

**Comment by retkeszaju** [comment]
nah i recived no gold, no items in the returning mail

**Comment by MaxHayman** [comment]
This should be fixed.
