### ISSUE TITLE
Hacker?

### ISSUE THREAD

**Issue by Cofry324** [WarEmu/WarBugs#9879]
Hao of Destruction said he hacked to get Manticore. Not sure how true it is but just letting you guys know

**Comment by Cofry324** [comment]
This is Rylde of Destruction btw

**Comment by Cofry324** [comment]
Bro, you made a few people think you were hacking Lmao

**Comment by wargrimnir** [comment]
1. Not appropriate for the bugtracker.
2. Not true.
