### ISSUE TITLE
(WH) Snap Shot cooldown

### ISSUE THREAD

**Issue by Bremort** [WarEmu/WarBugs#9882]
The tooltip for the Witch Hunter skill Snap Shot says "No Cooldown" however it appears to have a 3 second cooldown. Is the tooltip wrong, or should is the cooldown incorrect?

**Comment by tlitschye** [comment]
They added the cooldown but made it also procc from the side and rear, BUT that dsnt seem to work anymore, people can still strafe away and wont get the slowprocc sometimes.

**Comment by tlitschye** [comment]
So what is it now? with cooldown or without?
With procc from rear AND side or not?

**Comment by Torquemadra** [comment]
no cooldown
