### ISSUE TITLE
Conqueror Quests aren't working again. 

### ISSUE THREAD

**Issue by Oreas** [WarEmu/WarBugs#9884]
Like i described in 
Quest - Battle for Dragonwake #9806
the quests aren't functional again.

Quote myself from #9806 :
"All the Conqueror Quest NPCs in the RvR-Lakes seem to be buggy.
It is not possible to obtain the Quests or turn them in:
Secure Kadrin Valey/Reikland/Eataine
Battle for Thunder Mountain/Praag/Dragonwake
It is not possible to obtain the Quests from NPC (Keep Lord):
Conquest of Black Craig/Chaoswastes/Caledor
The last three can be turned in at Altdorf Palace"

To be honest, i didn't try them all again, but it seems to be the same bug.

AFAIK Destruction has the same problem.

Note: After the server crash the quests work again.

2nd Note:
And a couple of hours later they  stopped working again.

The "Defend (keep name)" quests seem to be buggy too. Keep Lords are not giving them. Might be related.

**Comment by VonRugen** [comment]
Same in High pass
