### ISSUE TITLE
Runepriest Ability: Rune of Breaking

### ISSUE THREAD

**Issue by Vandinar** [WarEmu/WarBugs#9886]
When the ability is toggled off intelligence from items does not transfer to willpower. My RP does not have the gear available to investigate Magic Power->Healing Power and Magic Critical Chance->Healing Critical Chance. Rune of Breaking's active component is working as intended.

**Comment by Niobandi** [comment]
As mentioned above, the Rune of Breaking ability is half working.

When toggle on, the effect is correct, all the Willpower / Healing Power / Healing Critical Chance bonus of the equipment were convert into Intelligence / Magic Power / Magic Critical Chance.

But when it's toggle off there is no effect other than equipment bonus return at their normal state : Willpower give Willpower, Intelligence give Intelligence.

Here you can see i'm only equip with a helmet with +8 Willpower and +5 Intelligence.
![aldroin_002](https://user-images.githubusercontent.com/16079024/31613113-5c9d00f6-b282-11e7-9297-cba09bb383fa.jpg)

With Rune of Breaking toggle off, it grant me what it's write : +8 Willpower and +5 Intelligence.
![aldroin_003](https://user-images.githubusercontent.com/16079024/31613141-77657710-b282-11e7-8898-0b1c1000f8df.jpg)
![aldroin_004](https://user-images.githubusercontent.com/16079024/31613142-778335c0-b282-11e7-81e1-8e4e804ebfe8.jpg)

When Rune of Breaking is toogle on, the effect is working and grant me +13 Intelligence ( the +5 base bonus and the +8 Willpower convert in Intelligence ).
![aldroin_005](https://user-images.githubusercontent.com/16079024/31613220-bbc6acf8-b282-11e7-8b6b-3118fd94839f.jpg)
![aldroin_006](https://user-images.githubusercontent.com/16079024/31613221-bbe74954-b282-11e7-8fb6-32809b427c13.jpg)

**Comment by dansarii** [comment]
I thought this was an issue, but it's not. The stat doll does not take into account the added willpower you get from Rune of Breaking. 

Below, I have Rune of Breaking toggled off, my willpower as shown in the stat doll (794), my willpower shown in getstats (872), and a belt with only intelligence (31) on it.

![rune of breaking check 1](https://user-images.githubusercontent.com/25072274/34185598-429f6244-e4f4-11e7-92e5-2a469ef2f33f.png)

Next, I have Rune of Breaking still toggled off, statdoll WP shows 794 unchanged, and my willpower shown in getstats has been decreased by 31 to 841.

![rune of breaking check 2](https://user-images.githubusercontent.com/25072274/34185636-7df38b86-e4f4-11e7-8e2d-53c62b14046b.png)

**Comment by grunbag** [comment]
Fixed with next patch

**Comment by sioding** [comment]
Fixed with patch from 03.08.2019
