### ISSUE TITLE
Lighth Quest Flanrock mine bugy

### ISSUE THREAD

**Issue by Stinkmorchel** [WarEmu/WarBugs#9891]
![stinkmorchel_011](https://user-images.githubusercontent.com/29592386/27915787-861be728-6267-11e7-91d0-7cc37505c0e7.jpg)
I kill Oathbearer Stouthammer  but it does not count 
and quest Drak kult the cages does not count 
i hope i can halp d to fix probs thx
lg Stinkmorchel

**Comment by Razielhell** [comment]
#6935
