### ISSUE TITLE
 PQ T2 CH6 Marshes of Madness- Oathgold Mine Stage 1 Stuck

### ISSUE THREAD

**Issue by Juppstein** [WarEmu/WarBugs#9892]
Task is to gather 5 tough stone and 10 oathgold deposits. But when you gather an oathgold deposit it counts towards the tough stones, but nothing counts towards the oathgold deposits. So the quest broken/stuck at stage 1 at the moment.

**Comment by Torquemadra** [comment]
Counter goes a bit screwy, works

[img]http://i.imgur.com/aA3idWC.jpg[/img]

[img]http://i.imgur.com/KgRoAUO.jpg[/img]
