### ISSUE TITLE
Hidden item Norsca secluded horn give an hidden quest don't work

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#9893]
Hidden item: LOC 60555 X 42424  NORSCA

Clicking on the SECLUDED HORN hanging from the tree trigger nothing

Normally should reward xp and item

**Comment by Lheana** [comment]
A ToK unlock ? You must precise what it should trigger.

**Comment by thorbolt80** [comment]
No Tok. 

He should be some reward experience and item

**Comment by Lheana** [comment]
Need more information about this quest, its name for example.

**Comment by Lheana** [comment]
This should have been fixed with the patch of today.
