### ISSUE TITLE
Stuck spot on pier in Reikland Factory

### ISSUE THREAD

**Issue by Specialpatrol** [WarEmu/WarBugs#9896]
On Order side there's a good chance to get stuck on the loading pier in Reikland Factory scenario. If some crafty carpenters could be dispatched to fix it, it would be greatly appreciated!

The issue visualised:
[puffed_017](https://user-images.githubusercontent.com/17357343/27932319-aab877e6-629d-11e7-9fb6-d7d66e7c87bd.jpg)

**Comment by sioding** [comment]
can not replicate

**Comment by soekmego** [comment]
I have experienced the same today. Fell down the pier (due to my own fault) and got stuck at the exact same spot. 

See screenshot

![endurance_010](https://user-images.githubusercontent.com/22181062/36845787-56cca4ce-1d58-11e8-9f69-8e24ddab84ab.jpg)
