### ISSUE TITLE
Can't turn in quest "secure Reikland"

### ISSUE THREAD

**Issue by tomaslumba** [WarEmu/WarBugs#9897]
All the conditions are filled and the quest NPC are marked with a yello badge, still nothing happens when I click him.

What to do?

Kind regards

**Comment by Razielhell** [comment]
You can click on him but nothing happens? Can you try again now please?

**Comment by Oreas** [comment]
Since the last patch the "Secure Reikland" quest can be turned in correctly.

**Comment by tomaslumba** [comment]
Could turn in quest now but didnt give any medals, just 3 gold...

**Comment by Razielhell** [comment]
he gives it. Just doesn't register on chat log. They are added in your backpack. Don't worry.

**Comment by tomaslumba** [comment]
Thx mate :) keep up the great work!
