### ISSUE TITLE
Tier 1 rvr map bug

### ISSUE THREAD

**Issue by Cofry324** [WarEmu/WarBugs#9898]
There is a map glitch on the Nordland XI battle objective. Some order have jumped around on the rain next to the flag and they can fall through the floor and stay behind a door and cannot be seen. Theyou are also able to heal everyone and attack without being attacked themselves. I have seen order do this on my lvl 40 chosen, Rylde and my lvl 6 white lion.

**Comment by Cofry324** [comment]
White lion's name is Mafdet

**Comment by Lheana** [comment]
Fixed in next patch.

**Comment by Cofry324** [comment]
Ok
