### ISSUE TITLE
T2 Shadowlands epic quest - wrong reward & quest disappeared from tome

### ISSUE THREAD

**Issue by deLunel** [WarEmu/WarBugs#9899]
Hi, 
I saw t2 epic quest A Lord's Reward was fixed and would yield a helmet on forum update.
I have just gone through all the steps until was shown 2 gear pieces as reward by Lordling Barakus in Ch 8.

At this point the message shows "A Lords Game Accepted" but it struck me the shown rewards are NOT helmets but were two hauberks: (i) Strength and Toughness and (ii) 19 toughness (playing my BG name Ethanlind)

Also, looking in my tome I see my quest is also completely gone and I have no reward in my bag? Attaching screenshot from immediately after this last stage/step of quest was accepted showing tome empty but text lower left showing cleary quest accepted. Unfortunately cannot show reward screenshot as all gone in tome.

**Comment by deLunel** [comment]
![ethalind_000](https://user-images.githubusercontent.com/26348163/27984012-76e6eac2-63fd-11e7-8976-b3c1f724b922.jpg)

**Comment by deLunel** [comment]
Name of character is Ethalind (above was a typo in name)

**Comment by deLunel** [comment]
Hm, maybe 5-10mins later the quest is suddenly back in my tome BUT the quest information for the last stage and the rewards are all blank - see attached

**Comment by deLunel** [comment]
![ethalind_002](https://user-images.githubusercontent.com/26348163/27984154-a4493580-6400-11e7-86da-7cbc0972b827.jpg)

**Comment by ragafury** [comment]
![ragah_025](https://user-images.githubusercontent.com/26032314/27990722-f7d94d16-645f-11e7-8181-7b5ede79a926.jpg)

gonna add this here so no dublettes are opened up.

trumpet seems bugged,... we waited a little longer. x)
named NPC was sucessfully summoned as you can see and dropped the item, so that part works.

**Comment by deLunel** [comment]
Working fine after mysteriously disappearing and then later reappearing in my tome. Will try to close.
