### ISSUE TITLE
PQ Plague Mist Vale Broken

### ISSUE THREAD

**Issue by nevrotico** [WarEmu/WarBugs#9903]
Kadrin Valley, PQ Plague Mist Vale its broken, it have an infinite triple mobs spawn or maybe more in the same place, also if you go to the next stage the mobs of the previous stage spawn anyway.

hope can help you

ty in advance

**Comment by grunbag** [comment]
this is intended. there is same mobs in stage 2 and 3 (stage 2 they are part of the objective) and stage 3 they defend stage 3 objective
