### ISSUE TITLE
WE Throwing dagger has no cooldown (prob WH too)

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#9904]

**Comment by Nfkillz** [comment]
tested on WH snap shot has no cd as well

**Comment by tlitschye** [comment]
Did they remove the CD? Or did you just spamklick the ability?

**Comment by Juppstein** [comment]
The CD is definitely not triggered. You can Snap Shot to your hearts content whenever you want. The cooldown timer can be ignored at the moment. Though GDC still seems to apply at least :)
