### ISSUE TITLE
Gutbashed gnoblars mobs

### ISSUE THREAD

**Issue by hasashim** [WarEmu/WarBugs#9908]
In the Pq Gutbashed Gnobars in TM,after you fininsh the quest some mobs dont disappear,like some ogres on the entrance and some gnoblas near the chest

**Comment by Razielhell** [comment]
Fixed some Gnobleaters falling out of the PQ.
Keep in mind that mobs from now on won't despawn instantly when you advance to the next stage of a PQ.
