### ISSUE TITLE
WP`s HP buff Sigmar grace restores HPs

### ISSUE THREAD

**Issue by Nfkillz** [WarEmu/WarBugs#9909]

**Comment by Vancerus** [comment]
And is already getting abused as main grp heal in decent grp fights.
With SM CD Reduce and Moral 2 for quick casts.

**Comment by tlitschye** [comment]
Just give it a higher CD and suddenly no abuse possible, like it says, it should be a BUFF not a HEAL

**Comment by wargrimnir** [comment]
All wounds buffs act as a heal.

**Comment by tlitschye** [comment]
All other HP buffs state in the tooltip, that they increase and heal for the defined amount, WP buff doesent mention the healing in the tooltip, so it was that way on LIVE Server see ticket 9116

All other HP buffs are single target.
All other HP buffs have minutes of cooldown or are proccs(e.g from BO)

Simple fix would be to make it NOT spammable like the increased cooldown on the SORC buffs
if you need an example i can provide it to you.

**Comment by Nfkillz** [comment]
increasing CD would be good to make this ability buff.

**Comment by dalen** [comment]
This has a cooldown now and is not spammable. So I guess the ticket could be closed as the suggested solution is implemented.
