### ISSUE TITLE
Squig Herder Path of Quick Shootin' mastery point bug

### ISSUE THREAD

**Issue by Zzeppenn** [WarEmu/WarBugs#991]
Currently, when I put mastery points into the Path of Quick Shootin', the damage of the abilities belonging to this tree will not be enhanced, meaning that any point put into QS is ultimately wasted.
I've tested it and it's not the tooltip that is bugged, there's effectively no damage increase for Yer Bleedin', Stop Runnin', Run 'n' Shoot and Not So Fast.

I've asked a SH friend to test too, and his damage did not increase either.
I've also tested Path of Big Shootin', and it works perfectly, so it is not the entire career being bugged, but Path of Quick Shootin'. I haven't tested the Path of Stabbin' mastery tree / abilities.

I know we are only in t2 and we only have 5 mastery points right now, but still, since all other careers seem to get their bonuses as they are supposed to (or, at least I hope so), QS specced SHs have a disadvantage right now.

Sorry if it's TL, DR, I hope there is a solution. Thank you in advance, and have a nice day.

**Comment by Evildoor** [comment]
According to comments here:
https://github.com/WarEmu/WarBugs/issues/1001
this was fixed.
