### ISSUE TITLE
ToK Unlock 'Chaos Portal' #8417  history & lore Norsca don't work  & order can't do it

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#9910]
1. May be reopen this issue #8417 that wasn't fixed as some progress have been made about world object.

"Approaching Chaos Portal in Norsca should provide the ToK unlock." don't work yet

2. Order side can't unlock it because a lot of 56 level guards were addded everywhere in the starting area.

Solution : May be remove all the 56 level guards in the starting area  except in chaos chapter 1 as in live server.

3. Location : Norsca 27.10 history & lore ToK Unlock

**Comment by Lheana** [comment]
Proximity unlocks are not implemented yet. We close reports until it is fixable, that's why it was closed.
