### ISSUE TITLE
Tok unlock "the raven god" order can't unlock because level 55 guards were added

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#9911]
Tok unlock "the raven god"  click on the tome of the reaven to unlock : "the raven god" history & lore

1. Order side can't unlock it because a lot of 56 level guards were addded everywhere in the starting area.

Solution : May be remove all the 56 level guards in the starting area except in chaos chapter 1 as in live server.

Location : Norsca (31.12)

**Comment by Lheana** [comment]
According to wiki https://web.archive.org/web/20130502022449/http://warhammeronline.wikia.com/wiki/Norsca/History_%26_Lore only Destruction players could trigger the unlock The Raven God.
