### ISSUE TITLE
Tok unlock "hell cannon" order can't unlock because level 55 guards were added

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#9912]
Tok unlock "hellcannon" click on the ammunition to unlock : "hellcannon"  history & lore

1. Order side can't unlock it because a lot of 56 level guards were addded everywhere in the starting area.

Solution : May be remove all the 56 level guards in the starting area except in chaos chapter 1 as in live server.

Location : Norsca (38.10)

**Comment by Lheana** [comment]
According to wiki https://web.archive.org/web/20130502022449/http://warhammeronline.wikia.com/wiki/Norsca/History_%26_Lore only Destruction players could trigger the unlock Chaos Portal
