### ISSUE TITLE
Should we still report proximity unlock? fixed or not? History and Lore Unlock: Norse Tribes #3799

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#9915]
History and Lore Unlock: Norse Tribes #3799

Evildoor, the Tome of Knowledge is currently under reconstruction, including these History and Lore ones. **# Proximity unlocks are not implemented** yet, while we currently can fix the one's that require GO interaction. I would still encourage people to report those that are associated with GO interaction/NPC killing/interaction, since they can and will be fixed.

**Comment by Lheana** [comment]
Don't report bugs that have already been reported, thanks.
Proximity unlocks are not implemented yet, so not fixable yet.
