### ISSUE TITLE
greenskin chapter 18 PQ item

### ISSUE THREAD

**Issue by dragot88** [WarEmu/WarBugs#9916]
chapter 18 item have wrong look and stats
![dragot_011](https://user-images.githubusercontent.com/30019818/27993217-e53332bc-64be-11e7-841b-bcaae038073e.jpg)

**Comment by SecretsOTheP** [comment]
This item appears to have the right stats. They were corrected in this update.

http://everquest.allakhazam.com/wiki/WAR_Update_1.2.0

If you can find evidence to the contrary the item will be corrected.
