### ISSUE TITLE
Order Keep Lords in Praag and TM don't give Conqueror Quests

### ISSUE THREAD

**Issue by Oreas** [WarEmu/WarBugs#9917]
As the title sais, the Order side Keep Lords in Praag and TM don't offer the Conqueror Quests ("Battle for Praag", Battle for Thunder Mountain") 

Note: All 9 Destruction Keep Lords are working fine.

**Comment by wargrimnir** [comment]
Fixed next patch. In the meantime, you can grab the quest from the captured keep in TM after the zone flips.

**Comment by Oreas** [comment]
Thanks for finding a solution.

Note:
Keep Lord in Praag works normal. Maybe i made a mistake with that one.
