### ISSUE TITLE
Lvl 40 but exp bar is still increasing

### ISSUE THREAD

**Issue by Cofry324** [WarEmu/WarBugs#9920]
I am a lvl 40 chosen and I logged on and killed something down in chrace and it filled my bar up to 42% and now says I have rested exp. We're the lvl caps raised or is this a bug?

**Comment by Razielhell** [comment]
just a weird bug. Is your bar still at 42%?

**Comment by Cofry324** [comment]
It was every now and then. I just deleted the game entirely
