### ISSUE TITLE
[Ekrund] [T1 warcamp] Hoardmaster Keggle

### ISSUE THREAD

**Issue by BastionWAR** [WarEmu/WarBugs#9921]
This npc doesn't work or doesn't have shop. When you click in button nothing happens. Dyes works.
![durrigt_000](https://user-images.githubusercontent.com/30054005/28031028-4abbb996-65a6-11e7-8ef7-de0097e32dcd.jpg)

**Comment by Lheana** [comment]
Fixed in next patch.
