### ISSUE TITLE
[Ellyrion][PQ] Starbrook Falls Stage 3. Champion lvl 27 in PQ rank 16-17

### ISSUE THREAD

**Issue by BastionWAR** [WarEmu/WarBugs#9922]
Maybe would must be level 17 instead 27.

![thyrom_000](https://user-images.githubusercontent.com/30054005/28031255-f7d8eb62-65a6-11e7-9260-1292d2fe5d7f.jpg)

**Comment by Razielhell** [comment]
Fixed in next.
