### ISSUE TITLE
Maw of Madness Scenario into Altdorf

### ISSUE THREAD

**Issue by Manatikik** [WarEmu/WarBugs#9925]
Me (Fenryl) and Ricksanchez were grouped today in Altdorf and got a Scenario pop for Maw of Madness. When we loaded in we were in a skybox or the ground, map was labeled Zone 0, we died, and respawned in a version of Altdorf that had just the two of us and select NPC's. Still said we were in the Scenario and could use /sc to chat with people in the Scenario. Only seemed to happen to us. 
![glitch](https://user-images.githubusercontent.com/19319894/28050832-ba225df2-65c5-11e7-8de4-d0c61771cab5.png)

**Comment by MaxHayman** [comment]
Should be fixed next patch

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
