### ISSUE TITLE
[WL] HOTBAR Pet skills are doing significantly less damage than tooltip (not scaling correctly?)

### ISSUE THREAD

**Issue by Osgrim** [WarEmu/WarBugs#9928]
I was wondering if this is intentional. The damage on the tooltip for hotbar pet skills is usually in the high 400's, yet while testing on mobs which have very low toughness and armour they're hitting for mid 100s with very little mitigation. I was wondering if the hotbar pet skills arent scaling correctly despite using TTK which ups pet strength. I'm getting similar low damage with throat bite as well. 

Pics attached. 

![1_wl](https://user-images.githubusercontent.com/22075763/28067803-b3aa126a-663a-11e7-9f15-a50fb799f65b.JPG)
![2_wl](https://user-images.githubusercontent.com/22075763/28067810-b9fd86a6-663a-11e7-9b33-2acda93376e2.JPG)

**Comment by Torquemadra** [comment]
They are doing the correct damage, the system is drawing the tooltip from the Players stats not the lions. They line up to a variance of 1% regarding damage values as laid out in the client.
