### ISSUE TITLE
Chasing Oathgold (Marsh T2 Epic quest)

### ISSUE THREAD

**Issue by Symbelmyne** [WarEmu/WarBugs#9929]
On one step when I suppose to click Dark Creature body to summon Soulless Thrall, said spawned mob is easy to kill by Konrad Boel. Body is ticked for questline so cant be clicked again for summon, waited 15-20 min, killing mobs around and doing 1 scenario.

**Comment by Razielhell** [comment]
Will be fixed next Patch.
