### ISSUE TITLE
Spore Cloud

### ISSUE THREAD

**Issue by Harnag** [WarEmu/WarBugs#993]
None of the Gas Squig's attacks are hitting all enemies within 20ft/30ft as they should (depending on the attack).  They only damage a single enemy, whether NPC or player.

**Comment by Harnag** [comment]
This looks to be fixed now (only the animation looks single-target).

**Comment by Harnag** [comment]
This problem is now back again.  None of the Gas Squig's attacks are hitting all enemies within 20ft/30ft as they should (depending on the attack). They only damage a single enemy, whether NPC or player.

**Comment by Evildoor** [comment]
Tested, Goop Shootin' is aoe. Can't make the squig to use Spore Cloud at all...

**Comment by Evildoor** [comment]
It seems that there is a problem with Spore Cloud - pet refuses to use it even after fix for pets AI. Other pets (i tested lion, spiked squig and horned squig) use their abilities properly.

**Comment by ozarmidrashim** [comment]
Spore Cloud was not implemented at all.
