### ISSUE TITLE
Multiple NPC'S.

### ISSUE THREAD

**Issue by Seranei** [WarEmu/WarBugs#9930]
Hello, I'm a fairly new person to the server and was brought by a friend. I've been enjoying questing alone and with my friends and have begun learning the lore. Thus I wanted to level up my dark elf in dark elf lands. So I asked my friend and he told me it was possible and so I headed out on an adventure. Although I struggled a bit. It seems that the npcs are spawned twice or thrice which makes it nearly impossible without a group or someone who helped me. Is it just me that has this problem?

**Comment by Razielhell** [comment]
where?

**Comment by Seranei** [comment]
Uh, mainly in the Dark Elves vs High Elves. More exact from chapter 3-6, six is where I am at.

**Comment by Seranei** [comment]
Especially in the Ruins of Anlec, Gon'Seraph, Tor Achare and the Dreamshade

**Comment by Razielhell** [comment]
Will clear them but it would really help if you posted some screenshots.

**Comment by Torquemadra** [comment]
and NAMES

thanks ;)

**Comment by Seranei** [comment]
Since I haven't played the retail version I don't know what the right amount of npcs is but the current amount of Nagarythe lamentors etc jsut seem impossible for people to solo. Other npcs are those in the Dreamshade and are called Dreamshade, something something. My friend who was level 30 helped me there and even he found it an absurd amount. But I do understand that you focus more on the main storyline and questline in Norsca than the other two.

**Comment by Razielhell** [comment]
> But I do understand that you focus more on the main storyline and questline in Norsca than the other two.
Not true

**Comment by Seranei** [comment]
Oh, apologies then. Again, I'm a bit new to the whole game but didn't really encounter a struggle in the chaos vs empire or dawi vs greenskins as in the elf scenario.

**Comment by Razielhell** [comment]
Cleaned all double spawns.
