### ISSUE TITLE
SC Eternal Citadel: Portal and Torch on the wall

### ISSUE THREAD

**Issue by tlitschye** [WarEmu/WarBugs#9932]
Hey,

you guys know the Portal in Eternal Citadel, the one that goes OUT of the Scenario.
Now my issue is that some people ABUSE that portal and intentionally kick people BEHIND it.
You get stuck there and have no possibility to leave. Same problem, there is some kind of torch on the wall close to the portal. You can also get stuck there.
Is it possible to move the Portal closer to the Wall or make some kind of balcony over it, so no more kicks into that place are possible?

Thank you very much.

Greets

**Comment by Lheana** [comment]
Fixed in next patch
