### ISSUE TITLE
Can't fuse 2 talismans of the same type on an item.

### ISSUE THREAD

**Issue by sofronguy** [WarEmu/WarBugs#9934]
Happens with Sledge of the subjugator on the wp while trying to gem it with 2 strength talismans, as well as on runu priest with willpower talismans on the staff of the subjugator.

**Comment by tlitschye** [comment]
you cant slot 2 talisman of the same kind on a 2 slop weapon.... got fixed like 8 years ago on LIVE

**Comment by Lheana** [comment]
Intended
