### ISSUE TITLE
blackened characters

### ISSUE THREAD

**Issue by ingurbard** [WarEmu/WarBugs#9936]
I just gogged in and found this, no need more explanations, you can see whats going on on the screens I atatch to you, it's in all characters including my lion
![yngur_069](https://user-images.githubusercontent.com/28376479/28134944-3f98a3ca-670a-11e7-81e5-a27d73d1d184.jpg)

**Comment by Razielhell** [comment]
Turn graphical settings off. Relog.

**Comment by ingurbard** [comment]
thanks it worked :) 

    El Miércoles, 12 de julio, 2017 14:29:50, Razielhell <notifications@github.com> escribió:
 

 Turn graphical settings off. Relog.—
