### ISSUE TITLE
Dwarf Chapter 8 Chasing Oathgold - Kill Soulless Thrall

### ISSUE THREAD

**Issue by Juppstein** [WarEmu/WarBugs#9937]
When you examine the victim laying on the floor the soulless thrall will spawn, but there is a war priest named Konrad Boel (level 41) some distance away that will instantly run up and kill the thrall, which leaves the quest open because I am not able to kill the thrall in time (Boel basically one-hits the monster). The aggro perimeter of Konrad Boel seems to be a tad too big.

http://i.imgur.com/3KyKlqP.jpg

**Comment by Razielhell** [comment]
Already fixed. #9929
