### ISSUE TITLE
Tok History & Lore: "The End Times" Troll country cant' unlock

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#9942]
ToK History & Lore: The End Times

Notes: Located among the Great Eagle Nests (Major Landmark), there is a nest near the ledge to the your right while going up the long hill. There is a book, which is mostly obscured by the nest, titled "This Will Be Your Doom". Interact with the book.

source : https://gaisciochnaanu.com/warhammer/history_and_lore_unlocks/

There is no book

**Comment by Lheana** [comment]
This unlock works perfectly https://wiki.returnofreckoning.com/index.php?title=Troll_Country_History_and_Lore
The RoR wiki is perfectly updated about unlocks on RoR, base on this before doing reports.
