### ISSUE TITLE
Swimming through water while riding retains riding speed

### ISSUE THREAD

**Issue by Juppstein** [WarEmu/WarBugs#9943]
When I ride on a horse and cross a river that is so deep that I start to swim I will retain my riding speed while swimming and also after reaching land, without actually sitting on a horse. This was tested  with a regular 10 gold horse (chestnut) several times while crossing a river and lake in Ostland at around 42/34. 

Interestingly when you hit the button to mount the ride, you see the dust cloud that would usually indicate that you've just dismounted. You then have to click the button again to actually mount the horse. So it seems it just removes the horse from the player model, but retains all stats as if you would still sit on it.

**Comment by Razielhell** [comment]
#6591
