### ISSUE TITLE
Bug in first public quest Raven Host Vangaurd.

### ISSUE THREAD

**Issue by triedset** [WarEmu/WarBugs#9944]
Hi.

In the first Public quest in Nordland, Raven Host Vanguard.
When you are going to slain Father Sigwald, you can't attack his guards, because they are friendly.
It doesn't happen every time, but today it happened 3 times out of 5.

**Comment by Razielhell** [comment]
You need to protect him. Objective name is wrong. It was like that on live too.
Even if it says Slain you need to protect him.
> Father Sigwald is the backbone of Grimmenhagen.  Assist the brave peasants in protecting him.

**Comment by triedset** [comment]
Hi.

I know that, and thats not the problem.
The problem is he has 2 guards with him, that some times attacks you
instead of the enemy :)
I hope it is something you can look at, and then get it fixed.

Yours sincerely
triedset

2017-07-13 18:17 GMT+02:00 Razielhell <notifications@github.com>:

**Comment by Razielhell** [comment]
#6933
