### ISSUE TITLE
Tok "exorcism" high pass order side can't interact with the chest labeled Blair's Raiments at 42k/56k to trigger this unlock.

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#9949]
Exorcism (WAR History and Lore)   Share
Due to this unlock being surrounded by level 55 Champion guards inside Bitter Woods, it is an Order only unlock.

Can't interact with the chest labeled Blair's Raiments at 42k/56k to trigger this unlock.

source : [http://everquest.allakhazam.com/wiki/Exorcism_%28WAR_History_and_Lore%29](url)

**Comment by Lheana** [comment]
This unlock works perfectly https://wiki.returnofreckoning.com/index.php?title=High_Pass_History_and_Lore
The chest 'Blair's Raiments' is in High Pass Order Chapter 12, is perfectly interactable, and provides the unlock.
