### ISSUE TITLE
Queuing in Nordland almost always puts you in a T1 scenario /w chicken debuff

### ISSUE THREAD

**Issue by gittoaster** [WarEmu/WarBugs#995]
I spent a lot of time this release dealing with this issue. 
It seems that the tiers is currently separated by the zones?  IDK??  
anyway that would be nice to fix... thx

**Comment by Evildoor** [comment]
Queued two times from T1 today, from different zones. Had no problem. Seems to be fixed?

**Comment by gittoaster** [comment]
i experienced this as recent as last week.  I can try to check again.

**Comment by gittoaster** [comment]
I just tried today and it happened.  It didn't put me in T1 sc it put me in a t2 sc but as a chicken, dying did not help either.

this is what I did to occur
Load program - play RP at Windmill PQ
I was in combat vs t1 mobs
queued and accept
was chickend in the sc ->force game restart

thx

**Comment by gittoaster** [comment]
this particular issue seems to now not occur.  new issue reported (return from scenario a chicked) which I don't think is related.
