### ISSUE TITLE
Tok killed 25 then 100 high elf don't trigger in Tok

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#9950]
I got the message in blue in the discussion channel :" you killed 25 high elf" but no Tok unlock. Same when I killed 100 high elf

FYI it was high elf killed in "echoes of war" quest high pass order 36.47

**Comment by Lheana** [comment]
It is normal, as Order you haven't the unlocks for killing NPC/classes of your own faction.
You triggered the unlocks as it is not set per faction yet.
