### ISSUE TITLE
[Badlans] Chapter 13 Dwarf Flymaster Z position issue

### ISSUE THREAD

**Issue by BastionWAR** [WarEmu/WarBugs#9951]
This flymaster is in Z gameobject position.

![thyrom_004](https://user-images.githubusercontent.com/30054005/28221043-1607fd08-68c2-11e7-9bc7-4972b3199b67.jpg)

**Comment by Lheana** [comment]
It is not permanent.

**Comment by Juppstein** [comment]
You will see this behaviour all over the world, but it is not a consistent issue and the same flight master has the the problem one day and appears to to be located correctly the other. I assume it is tied to the phases of the moon. Hard to patch the moon though I think.

**Comment by sioding** [comment]
**Thanks for the report.** Since there is no confirmation, i will close this issue now. You can help us by following the bugtracker rules which you can find here: [https://www.returnofreckoning.com/forum/viewtopic.php?f=52&t=10366](url)
