### ISSUE TITLE
[Badlands] PQ Savage Assault Stage 3 spawn of champion stage 2

### ISSUE THREAD

**Issue by BastionWAR** [WarEmu/WarBugs#9952]
Teoricly in this stage, only must be HERO but, there is a spawn of a orc champion from Stage 2. (Orc mounted in boar)
![thyrom_005](https://user-images.githubusercontent.com/30054005/28221197-a9179914-68c2-11e7-84c1-ae3d7802f660.jpg)

**Comment by Razielhell** [comment]
Database is clean. Has something to do with respawn code. This happens in every PQ. Will be looked asap.
