### ISSUE TITLE
Hoardmaster Keggle in Ekrund (Recruit Medallion Vendor)

### ISSUE THREAD

**Issue by ferraz19** [WarEmu/WarBugs#9954]
The recruit medallion vendor in Ekrund might be bugged.
I cant access the items he has for sale.
I was thinking it might be because of my level but I thought id let yall know just in case.
Thanks again for all the hard work! 

Schwift

**Comment by Lheana** [comment]
Has been fixed with patch earlier #9921

**Comment by ferraz19** [comment]
Cool!
Thanks!
