### ISSUE TITLE
Double spawn mob with unique name : elorian (troll country and high pass)

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#9957]
"Elorian" in Troll Country at 8.6k 47.2k. (the good one)

"Elorian" is also in High pass at 58.16 among other spite (around 60 feet east of skaven enclosure)

**Comment by Lheana** [comment]
This mob had double spawn on official : https://www.returnofreckoning.com/forum/viewtopic.php?t=1837 (search for 'Lost and Found' and you'll see he is meant to be there)
