### ISSUE TITLE
Nordland - Grimmenhagen - Quest: "Hearts and Minds" is buggy

### ISSUE THREAD

**Issue by Spielteufel** [WarEmu/WarBugs#9958]
Nordland - Grimmenhagen - Quest: "Hearts and Minds" is buggy, is faulty
The Marauder Sympathizer dont spwan
The Marauder sympathizers do not appear

**Comment by Razielhell** [comment]
Someone needs to push the script. Next patch just click on Farmer

**Comment by Lheana** [comment]
The quest has been disabled, so it's no longer an issue.
