### ISSUE TITLE
[Choppa] Git To Da Choppa missed 30 sec cooldown and can be used without cd.

### ISSUE THREAD

**Issue by Killham** [WarEmu/WarBugs#9960]
I found what cd starting only if u interrupt cast by jumping couple times and used ability again and again.
![killham_006](https://user-images.githubusercontent.com/18173840/28243062-ce571ae2-69c6-11e7-9245-d89f44ac329c.jpg)
![killham_007](https://user-images.githubusercontent.com/18173840/28243063-cf6cba36-69c6-11e7-8d72-79bc25e4ed81.jpg)

**Comment by Torquemadra** [comment]
fixed thx
