### ISSUE TITLE
Badlands Dwarv T3 PvE Quest Ancient Horror Pt.1 partially missing map circle 

### ISSUE THREAD

**Issue by Juppstein** [WarEmu/WarBugs#9966]
While the Promising Stones are marked on the map, the Interesting Stones at around 6050/31870 are missing the indicator on the map.

![osimus_005](https://user-images.githubusercontent.com/8590930/28262447-491de482-6ae3-11e7-8635-ece0b1cfa10f.jpg)

**Comment by rekkir** [comment]
I did it yesterday, and it shows both areas until you click one stone, then both disappeared for me.
Furthermore for the later stage where you are told to travel to BFP there is no red arrow indicating you are meant to cross zones.

**Comment by Razielhell** [comment]
Fixed quest markers. If you find any other bug regarding this quest chain do report here again.

**Comment by BadHand89** [comment]
Quest Marker for Interesting Stones not working again.

**Comment by Yueizen** [comment]
Quest Marker for Interesting Stones not working after getting Muddied stone.
