### ISSUE TITLE
Quest: "Ritual of Murder." Bugged Fountain

### ISSUE THREAD

**Issue by FatWizard** [WarEmu/WarBugs#9967]
Dragon Wake 8010, 9073

The quest asks you bathe in the Sacred Fountain after killing 5 Shining Absolved high elves (acquiring their essence upon killing them). But when you jump in the fountain (after killing and gathering the essence of  5 Shining Absolved) it doesn't complete the quest task.

![gult_000](https://user-images.githubusercontent.com/30001739/28264260-180d8d60-6b25-11e7-8033-d8906c0ab8a1.jpg)

![gult_002](https://user-images.githubusercontent.com/30001739/28264263-1aec9c42-6b25-11e7-87ce-c76412875fa2.jpg)

**Comment by Razielhell** [comment]
We can't make areas trigger for quests objectives yet.

**Comment by sioding** [comment]
Fixed with patch from 23.03.2019
