### ISSUE TITLE
Reikland mob non targetable 20.17 hawk

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#9968]
Standing in the water near a small rock 60 feet east of watermill

**Comment by Razielhell** [comment]
Not targetable or attackable?

**Comment by Razielhell** [comment]
Fixed in next patch

**Comment by thorbolt80** [comment]
attackable


________________________________
De : Razielhell <notifications@github.com>
Envoyé : lundi 17 juillet 2017 14:01
À : WarEmu/WarBugs
Cc : thorbolt80; Author
Objet : Re: [WarEmu/WarBugs] Reikland mob non targetable 20.17 hawk (#9968)


Not targetable or attackable?
