### ISSUE TITLE
Dwarven T3 Badlands PQ CH10 Kazad Drung St.1 kills are not counted

### ISSUE THREAD

**Issue by Juppstein** [WarEmu/WarBugs#9969]
You are supposed to kill the skaven ( 30 Warpclaw Clanrats) in the first stage of the PQ, but they dont count in any way to the progress of the PQ, though influence is given correctly upon a kill.

![osimus_006](https://user-images.githubusercontent.com/8590930/28270680-a7b2e8d0-6b06-11e7-9cca-591d3bced858.jpg)

**Comment by grunbag** [comment]
just tested it, it works properly

**Comment by Razielhell** [comment]
Kill 3-4 of them leave the area so PQ Tracker goes away and go inside again and tell me if it works.
