### ISSUE TITLE
Dwarf CH10 T3 Influence Rewards cannot be picked

### ISSUE THREAD

**Issue by Juppstein** [WarEmu/WarBugs#9970]
The rally master at Dwarven CH10 T3 Badlands does not list first level rewards when you have enough points to pick them. 

![osimus_007](https://user-images.githubusercontent.com/8590930/28270989-af089390-6b07-11e7-838b-93c2b79485b3.jpg)

**Comment by Razielhell** [comment]
You don't have enough points...i can see your main infl bar is empty. And your addon bar is ticked for Basic rewards. But there aren't any for this Chapter so yeah.
![desktop 07 17 2017 - 17 21 28 21](https://user-images.githubusercontent.com/16864486/28272550-8373611c-6b14-11e7-887c-12d40d3c188d.png)
