### ISSUE TITLE
Quest : "Test of Loyalty", Orderside. Wrong location of NPC lukas Stockwood (Reikland)

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#9971]
Quest :  "test of loyalty" (dye quest)

Wrong location of Lukas stockwood NPC. Map show him with red circle around 8.55

In fact he is inside the castle at 9.62 (inside Heinrich estate PQ)

**Comment by Razielhell** [comment]
Thanks for reporting. Fixed next Patch.
