### ISSUE TITLE
RVR influence counting for PVE Chapter

### ISSUE THREAD

**Issue by cupnoodles14** [WarEmu/WarBugs#9973]
If you go from RVR zone to PVE chapter (as indicated by label under influence bar), you will be awarded with this chapter's influence when zone locks. I believe this happens not just for locks but for any influence tick if you manage to make game think you're not in RVR area.

Influence pre-lock:
![chpopa_004](https://user-images.githubusercontent.com/29466521/28280537-b4bbd426-6b2c-11e7-9fcf-542137ae468d.jpg)
![chpopa_005](https://user-images.githubusercontent.com/29466521/28280538-b4bf4e12-6b2c-11e7-9b23-d1679c25a148.jpg)

Influence post-lock:
![chpopa_006](https://user-images.githubusercontent.com/29466521/28280559-ccd32258-6b2c-11e7-93dc-eeb07469cf08.jpg)
![chpopa_007](https://user-images.githubusercontent.com/29466521/28280539-b4c01400-6b2c-11e7-9d58-4ff261eb4371.jpg)

**Comment by Lheana** [comment]
This should have been fixed with patch of 22/02/2020.
