### ISSUE TITLE
[White Lion] Switching stances heals pet lion

### ISSUE THREAD

**Issue by wdesu** [WarEmu/WarBugs#9974]
Switching between Trained to Hunt and Trained to Threaten stances heals the lion while in combat. 
Example values (lvl 36 WL, devastator gear, PVE - no bolster): 
- switching to TtT: +1650 (165 wounds buff),
- switching to TtH: +820 (82 wounds buff).

Because stances have no cooldown, no AP cost, no range requirement, you can just stance dance between those two and the pet will be healed by ~2470+ in just 3 seconds (2 GCDs), this makes the lion pet almost unkillable while solo and WL's 15s 150ft HoT useless.

**Comment by Pxl555** [comment]
https://github.com/WarEmu/WarBugs/issues/9548

**Comment by wdesu** [comment]
Yep, a duplicate. Closing this
