### ISSUE TITLE
Howling Gorge barrel placing issue

### ISSUE THREAD

**Issue by rekkir** [WarEmu/WarBugs#9975]
Could not place the barrel of explosives in a mid tier SC the other day, others also said they could not.

**Comment by tomaslumba** [comment]
Same for me and for other team right now in T4. OK to pick up the barrel but can not deliver it, nothing happens when clicking the "goal".

**Comment by Torquemadra** [comment]
scenario off rotation on live atm

**Comment by Lheana** [comment]
#10201

**Comment by Natherul** [comment]
probably related to
https://github.com/WarEmu/WarBugs/issues/10201
and it should have been fixed some time ago now
