### ISSUE TITLE
Wiki needs update!

### ISSUE THREAD

**Issue by DedMango** [WarEmu/WarBugs#9982]
Hey all, Broked here.

So this isnt a bug, however could be useful info for someone else if theyre referring to the wiki like I was and get lost.

The Ch 6 Chaos influence master for PQ rewards (not the RvR ones) is in Felde, of Troll Country however on the wiki it says the T2 Chaos Warcamp which it is not

**Comment by Razielhell** [comment]
There is a Wiki section where you can post such things. Bugtracker is for game bugs only.
