### ISSUE TITLE
Ram randomly dying

### ISSUE THREAD

**Issue by Kourraj** [WarEmu/WarBugs#9984]
Happened to me 2 times in KV sunday night (dest side), then one time this morning to Order side.
1st time, the ram was suddenly at 3% hp with barely anyone hitting it.
2nd time, it was inactive, not towed, on the ground, no enemy near and it got destroyed.
Heard the latter happened to Order too.

And just happened again to dest in DW.
Another time, took a 50% hit, then a 20% hit.

**Comment by Kaelang** [comment]
The ram can time out if not around siege equipment / anyone using it. It's to stop people spawning it and hiding it. 

Apart from this - please re-open if this issue persists on the current version of RoR as I have not seen this happen across 100's of sieges.
