### ISSUE TITLE
PQ Chaos Waste : "lost artifacts" stage 2 bug order side

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#9985]
PQ name : "lost artifacts"     order side

Stage 1 : work fine

Stage 2 : you must destroy : daemonskin tome, bleeding helm, skull of Naroth, well of souls 

They are all non targetable, non attackable.

**Comment by Razielhell** [comment]
Made them targetable and attackable.

**Comment by sioding** [comment]
Fixed with patch 21.10.2017
