### ISSUE TITLE
Broken map area near Emp Chap 1 

### ISSUE THREAD

**Issue by ChilontheBW** [WarEmu/WarBugs#9988]
I tried to get to the warcamp from the initial spawn point in Emp. Walking by the portal area made me fall through the map. I tried to replicate this, it happened 3 times. I took my initial screenshot then successive ones to try and document it. 

![fyodor_001](https://user-images.githubusercontent.com/13327486/28396321-6dad9bbc-6caf-11e7-9e27-2646fc91aa0b.jpg)
![fyodor_002](https://user-images.githubusercontent.com/13327486/28396322-6db3d6da-6caf-11e7-94de-14b8c94f2ba8.jpg)
![fyodor_003](https://user-images.githubusercontent.com/13327486/28396325-6db82302-6caf-11e7-90b3-e88d09db0752.jpg)
![fyodor_004](https://user-images.githubusercontent.com/13327486/28396324-6db47fb8-6caf-11e7-8fa2-e25756f18197.jpg)
![fyodor_005](https://user-images.githubusercontent.com/13327486/28396323-6db47202-6caf-11e7-906d-9fbdcc0d61cb.jpg)

**Comment by Razielhell** [comment]
Which Portal area?

**Comment by ChilontheBW** [comment]
Sorry. I dont check these that often. Anyways its the static portal near the hellfire cannons in chapter 1 of emp. Near 19k, 48k
