### ISSUE TITLE
"it only takes one" (quest chaos waste order side)  bug order side

### ISSUE THREAD

**Issue by thorbolt80** [WarEmu/WarBugs#9991]
Mallek von Coutras 48.27 (NPC inside a cage) chaos waste:   ask : "examine the map in your inventory in order to examine it closely"

examine the map : 0/1   

1) No map in the inventory
2) Trying to click on NPC Mallek von Countras more than one time do nothing.
3) Trying to abandon quest and retake it do nothing

**Comment by Razielhell** [comment]
Speak with him again for now.
