### ISSUE TITLE
Harbinger of Doom graphic bug

### ISSUE THREAD

**Issue by wiscel** [WarEmu/WarBugs#9997]
Ok, posted this bug earlier and thought I fixed it but the bug is  back. Each time I use the Harbinger of Doom ability on my Zealot 2 almost invisible boxes appear on the chars hands, also when I jump my healthbar goes to half health. I've tried different video setting, and turning on/off shader but it doesnt help.

When in water you can see clearly what I mean, see the links 

http://i1036.photobucket.com/albums/a442/Wim_de_Nooyer/Snookey_006_zpsc1pm2kpn.jpg 
http://i1036.photobucket.com/albums/a442/Wim_de_Nooyer/Snookey_005_zpsstbwqphs.jpg

It only happens on this char, never experienced this before.

**Comment by wiscel** [comment]
I think there might be something more wrong with the abiltiy itself. When I turn it on, nothing happens. I wait 20sec till cooldown and try it again, and then it's finally swopping willpower for intelligence.

**Comment by Torquemadra** [comment]
longstanding issue with the VFX of harbinger, please use .getstats on self and verify stat swapping issue

**Comment by Madsn** [comment]
Have the same issue.. Is there a workaround?

With HoD:
![image](https://user-images.githubusercontent.com/1026046/54083906-3c3f9c80-432a-11e9-9639-f296a93b83c4.png)

Without HoD:
![image](https://user-images.githubusercontent.com/1026046/54083905-3944ac00-432a-11e9-8113-44d85593f923.png)

.getstats:
![image](https://user-images.githubusercontent.com/1026046/54083918-55484d80-432a-11e9-8145-6523881bf855.png)

**Comment by Madsn** [comment]
FYI for others with this issue.

There is a workaround, disabling shader performance optimizations: https://github.com/WarEmu/WarBugs/issues/9989

Had to restart game for it to take effect.

**Comment by Madsn** [comment]
Disabling shader performance optimizations didn't actually fix it for me. After messing around with the settings for a bit, it seems the only fix is to disable all animations.. Not ideal.

Any further details on this anywhere, or suggestions on how to fix it? I might give it a go if it's not a huge thing.
