### ISSUE TITLE
Order CH10 Chaos Ruins in Highpass gives Level 25 items as reward for a Level 21 quest

### ISSUE THREAD

**Issue by Juppstein** [WarEmu/WarBugs#9998]
Got a blue ring level 25 from that public quest, which is a bit high for a pq that is meant to be level 20 to 21.

![osimus_008](https://user-images.githubusercontent.com/8590930/28436516-79a75d02-6d97-11e7-936a-fa35906ba6e2.jpg)

**Comment by wargrimnir** [comment]
There are a few WH items that were added quite some time ago to test items in PQ bags. They'll be updated eventually as the bags are filled with appropriate gear.

**Comment by Razielhell** [comment]
Will be fixed when we have a decent amount of gear made in bags. Then we can link them to each PQ.
